### ISSUE TITLE
error   clang.executable

### ISSUE THREAD

**Issue by andychen2016** [Microsoft/vscode#17059]
- VSCode Version: Code 1.7.2 (7ba55c5860b152d999dda59393ca3ebeb1b5c85f, 2016-11-21T22:14:18.217Z)
- OS Version: Linux x64 4.4.0-53-generic
- Extensions:

|Extension|Author|Version|
|---|---|---|
|makeRunner|alexnesnes|0.1.1|
|code-gnu-global|austin|0.2.1|
|vscode-instant-markdown|dbankier|0.2.1|
|python|donjayamanne|0.5.5|
|CppSnippets|hars|0.0.5|
|vscode-auto-open-markdown-preview|hnw|0.0.3|
|MagicPython|magicstack|0.6.1|
|vscode-clang|mitaki28|0.2.1|
|cpptools|ms-vscode|0.9.3|
|Spell|seanmcbreen|0.9.1|
|python|tht13|0.2.3|

---

Steps to Reproduce:

error:Please install [clang](http://clang.llvm.org/) or check configuration `clang.executable`
how to solve this error??

**Comment by alexandrudima** [comment]
Moved to Microsoft/vscode-cpptools#403
