### ISSUE TITLE
i cannot do terminal

### ISSUE THREAD

**Issue by rulikname** [microsoft/vscode#170599]
Type: <b>Bug</b>

my terminal gone wrong, i cannot do anything with my nvm on terminals, my nvm is already installed and on, it shows on my cmd and windows powershell, but with vscode it is not recognized, please help. This is the messages that shown : 
nvm : The term 'nvm' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of th
e name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ nvm ls
+ ~~~
    + CategoryInfo          : ObjectNotFound: (nvm:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

VS Code version: Code 1.74.2 (e8a3071ea4344d9d48ef8a4df2c097372b0c5161, 2022-12-20T10:29:14.590Z)
OS version: Windows_NT x64 10.0.19045
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 2500U with Radeon Vega Mobile Gfx   (8 x 1996)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|6.96GB (0.91GB free)|
|Process Argv|--crash-reporter-id b9dab45d-3d40-48a6-90b6-dde822511d76|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (25)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-zipfs|arc|3.0.0
npm-intellisense|chr|1.4.4
path-intellisense|chr|2.8.4
vscode-eslint|dba|2.2.6
vscode-archiver|ecm|0.0.27
vscode-npm-script|eg2|0.3.29
chocolatey-vscode|gep|0.7.2
zip-preview|jac|0.0.4
search-node-modules|jas|1.3.0
node-module-intellisense|lei|1.5.0
powershell|ms-|2022.12.1
vscode-versionlens|pfl|1.0.10
java|red|1.13.0
vscode-zipexplorer|sle|0.3.1
node-pack|Swe|0.1.16
zip-file-system|Tom|2.0.0
intellicode-api-usage-examples|Vis|0.2.6
vscodeintellicode|Vis|1.2.29
vscode-java-debug|vsc|0.47.0
vscode-java-dependency|vsc|0.21.1
vscode-java-pack|vsc|0.25.7
vscode-java-test|vsc|0.37.1
vscode-maven|vsc|0.40.2
nodejs-extension-pack|wad|0.1.9
JavaScriptSnippets|xab|1.8.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
azure-dev_surveyone:30548225
pyindex848:30577860
nodejswelcome1:30587005
282f8724:30602487
iaj6b796:30613358
f6dab269:30613381
fim-prod:30623723

```

</details>

**Comment by meganrogge** [comment]
that error means nvm is not on your `PATH`,
run `echo $PATH` in your terminal to confirm that is the case
