### ISSUE TITLE
Expanding the view created in SCM

### ISSUE THREAD

**Issue by inchara-1998** [microsoft/vscode#170540]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 
- OS Version: 

Steps to Reproduce:

1. I have created 2 views in Source control view for new extension 
    ![image](https://user-images.githubusercontent.com/118963451/210513559-d7452ffe-b77a-4766-b804-72ffd9761eef.png)
2. i  need to expand one of the view all the time but some times its collapsing some time its expanding 
    
![image](https://user-images.githubusercontent.com/118963451/210513779-3d94092d-ab75-4591-aa50-f25e0c44a4be.png)

How to set that view to expand all the time..?
If there is anything i can use please let me know.

**Comment by lszomoru** [comment]
You can use the `initialSize` property that is documented [here](https://code.visualstudio.com/updates/v1_72#_tree-view-initialsize-contribution-finalized). Let me know how it goes. Thanks!
