### ISSUE TITLE
Incorrect indentation when using the default HTML formatter

### ISSUE THREAD

**Issue by kanlukasz** [microsoft/vscode#170509]
Does this issue occur when all extensions are disabled?: **Yes**

**VS Code Version:**
```
Version: 1.74.2
Commit: e8a3071ea4344d9d48ef8a4df2c097372b0c5161
Date: 2022-12-20T10:29:14.590Z
Electron: 19.1.8
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.22621
Sandboxed: No
```
**OS Version:** 
```
OS Name:                   Microsoft Windows 11 Pro
OS Version:                10.0.22621 N/A Build 22621
```

**Steps to Reproduce:**

1. Create HTML File
2. Add this code --->  `<h2><a href=""><p>Text</p></a></h2>`
3. Use `Format Document`

**Video GIF with example:**
![hhhhh](https://user-images.githubusercontent.com/30685349/210420096-3191492b-0985-474f-810c-049ac5a8c25a.gif)

**VSCode Settings:**
- default

**Comment by Teraskull** [comment]
Any updates or workarounds for this?

**Comment by aeschli** [comment]
The currently implemented folding strategy is based purely on the indentation of lines. A folding region starts when a line has a smaller indent than one or more following lines, and ends when there is a line with the same or smaller indent.

To be smarter and to, for example, understand go markdown header syntax, we will have to go one step further and introduce language agnostic folding regions. We have issue #3422 for this.

**Comment by aeschli** [comment]
We use [beautifyjs](http://jsbeautifier.org/) as the underlying HTML formatter. Would you mind filing this request directly against https://github.com/beautify-web/js-beautify ?
