### ISSUE TITLE
Tokenization and textmate  color mismatch

### ISSUE THREAD

**Issue by 9r0x** [microsoft/vscode#170523]
Does this issue occur when all extensions are disabled?: Yes

<img width="584" alt="Screen Shot 2023-01-03 at 16 30 31" src="https://user-images.githubusercontent.com/14857092/210444585-374959e8-f0a7-4ba0-8c75-5e3205e4ffc8.png">

- VS Code Version: 
```
1.75.0-insider
6ed4d436a9b6ae131732f4e2a723868231f4473a
x64
```
- OS Version: 
21.4.0 Darwin Kernel Version 21.4.0

Steps to Reproduce:

1.  Customize`editor.tokenColorCustomizations`
2. The color is not correct

Notice that the hex number(it's a bit hard to see), already shows as with `#8DDEE6` foreground color, but still appears black

<img width="537" alt="Screen Shot 2023-01-03 at 16 26 06" src="https://user-images.githubusercontent.com/14857092/210444223-a5c538ca-d51d-4c25-9b46-5634584709a6.png">

**Comment by IllusionMH** [comment]
Are you using custom fonts with ligatures? If yes, could you please try with default fonts?

**Comment by aeschli** [comment]
See https://github.com/microsoft/vscode/issues/100840
