### ISSUE TITLE
Debug doesn't create launch.json or detect one when I create it manually

### ISSUE THREAD

**Issue by desduvauchelle** [Microsoft/vscode#17058]
- VSCode Version: Code 1.7.2 (7ba55c5860b152d999dda59393ca3ebeb1b5c85f, 2016-11-21T22:01:10.756Z)
- OS Version: Darwin x64 16.1.0
- Extensions:

|Extension|Author|Version|
|---|---|---|
|beautify|HookyQR|0.6.2|
|material-icon-theme|PKief|1.1.4|
|jsx|TwentyChung|0.0.1|
|html-css-class-completion|Zignd|1.0.3|
|vscode-color|anseki|0.2.2|
|path-intellisense|christian-kohler|1.2.0|
|vscode-svgviewer|cssho|1.2.0|
|vscode-eslint|dbaeumer|1.1.0|
|vscode-babel-coloring|dzannotti|0.0.4|
|php-debug|felixfbecker|1.10.0|
|auto-rename-tag|formulahendry|0.0.8|
|terminal|formulahendry|0.0.5|
|rest-client|humao|0.11.0|
|node-module-intellisense|leizongmin|1.2.0|
|vscode-todo-parser|minhthai|1.8.3|
|prettify-json|mohsen1|0.0.3|
|vscode-less|mrmlnc|0.6.0|
|debugger-for-chrome|msjsdiag|2.3.2|
|node-modules-resolve|naumovs|1.0.2|
|seti-icons|qinjia|0.1.3|
|vscode-icons|robertohuertasm|4.1.0|
|code-spell-checker|streetsidesoftware|0.12.2|
|react-beautify|taichi|0.3.0|
|vscode-react-native|vsmobile|0.2.4|
|bootstrap-3-snippets|wcwhitehead|0.0.8|
|webpack-progress|wk-j|0.0.8|
|JavaScriptSnippets|xabikos|1.2.0|
|ReactSnippets|xabikos|1.2.0|
|Material-theme|zhuangtongfa|1.0.3|

---

Steps to Reproduce:

1. Open project in VS
2. Go to debugger
3. Click the gear icon to create launch.json file (nothing happens)
4. Create manually a launch.json -> Debugger doesn't find it.

**Comment by isidorn** [comment]
It seems like file events are broken in your wokrspace. What happens if you open a file in vs code and change that file in vscode - do you see the changes picked up in vsocde.

**Comment by bpasero** [comment]
@desduvauchelle ping

**Comment by bpasero** [comment]
A number of days has past without answer on the questions asked. I am thereby going to close this issue to clean up our backlog of issues. Once you can answer on the questions, the issue can be reopened again. Thanks for understanding this process!
