### ISSUE TITLE
Failing unit test:  Workbench - TerminalLocalLinkDetector macOS/Linux Link: ./foo should detect in "./foo (5)"

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#170546]
Failure: https://dev.azure.com/monacotools/Monaco/_build/results?buildId=198557&view=logs&j=55ac390b-ffb1-50ea-3650-525dd9a3fd80&t=c01b9029-2b08-503e-eba8-b45cf5956c33

```
The followings tests are failing:
 - Workbench - TerminalLocalLinkDetector macOS/Linux Link: ./foo should detect in "./foo (5)" (reason: Timeout of 5000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.)

```

**Comment by andreamah** [comment]
Happened again https://dev.azure.com/monacotools/Monaco/_build/results?buildId=199948&view=logs&j=55ac390b-ffb1-50ea-3650-525dd9a3fd80&t=c01b9029-2b08-503e-eba8-b45cf5956c33

**Comment by Tyriar** [comment]
This code got a major refactor the other day, hope that fixes this flake which didn't make much sense to me before 🤞 https://github.com/microsoft/vscode/pull/172930
