### ISSUE TITLE
Visual Studio Code is getting slower and freezesing all out of the sudden and shows not rospending message 

### ISSUE THREAD

**Issue by badriyahaddad** [microsoft/vscode#170587]
Type: <b>Performance Issue</b>

I have a problem with VS Code: whenever I code, debug, or run the code on my physical device using Flutter, it gets very slow, freezes, and shows "Windows is not responding: Reopen!" I disabled all the extensions, but nothing worked. I even tried some commands like deleting the user directory and disabling the extensions, but I still faced the same issue. I deleted the cache in AppData/Roaming/code, but still no luck. I also deleted the code file, and the same issue still exists! I even did this: -Open the Command Palette (Ctrl+Shift+P). Run the Preferences: Configure Runtime Arguments -Add "disable-hardware-acceleration": true. -Restart VS Code. I have looked it up all over the internet, and nothing worked! Please help me! 

VS Code version: Code 1.74.2 (e8a3071ea4344d9d48ef8a4df2c097372b0c5161, 2022-12-20T10:29:14.590Z)
OS version: Windows_NT x64 10.0.19045
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3230M CPU @ 2.60GHz (4 x 2594)|
|GPU Status|2d_canvas: unavailable_software<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>opengl: disabled_off<br>rasterization: disabled_software<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|11.88GB (7.49GB free)|
|Process Argv|--crash-reporter-id 1a675964-9480-480a-9e36-db659f4328a9|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    3	    99	  6792	code main
    0	   147	  2700	   extensionHost
    0	    79	  7100	     "C:\Users\AL-NOOR\AppData\Local\Programs\Microsoft VS Code\Code.exe" --ms-enable-electron-run-as-node "c:\Users\AL-NOOR\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\json-language-features\server\dist\node\jsonServerMain" --node-ipc --clientProcessId=2700
    0	     4	  8060	     C:\Windows\system32\cmd.exe /d /s /c ""C:\FlutterPath\flutter\bin\cache\dart-sdk\bin\dart.exe" "language-server" "--protocol=lsp" "--client-id=VS-Code" "--client-version=3.56.0""
    0	    11	  3980	       console-window-host (Windows internal process)
    0	   284	 10120	       "C:\FlutterPath\flutter\bin\cache\dart-sdk\bin\dart.exe"  "language-server" "--protocol=lsp" "--client-id=VS-Code" "--client-version=3.56.0"
    0	     5	  9696	     C:\Windows\system32\cmd.exe /d /s /c ""C:\FlutterPath\flutter\bin\flutter.bat" "daemon""
    0	    11	  2240	       console-window-host (Windows internal process)
    0	   146	  5708	       electron_node config.js 
    0	     4	  9836	     C:\Windows\system32\cmd.exe /d /s /c ""C:\FlutterPath\flutter\bin\cache\dart-sdk\bin\dart.exe" "devtools" "--machine" "--try-ports" "10" "--allow-embedding""
    0	    71	   124	       "C:\FlutterPath\flutter\bin\cache\dart-sdk\bin\dart.exe"  "devtools" "--machine" "--try-ports" "10" "--allow-embedding"
    0	    11	  9780	       console-window-host (Windows internal process)
    2	    61	  6864	   gpu-process
    7	    89	  7712	   issue-reporter
    0	    89	  8204	   window (undefined)
    0	   108	  9228	   shared-process
    0	    70	  3852	     ptyHost
    0	    76	  5076	     fileWatcher
    0	    27	 10156	   crashpad-handler
    0	   181	 10920	   window (Extension: Material Icon Theme - petme - Visual Studio Code)
    0	    41	 11232	   utility-network-service
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (Extension: Material Icon Theme - petme - Visual Studio Code)
|    Folder (petme): 1414 files
|      File types: xml(122) json(119) flat(98) png(81) jar(39) len(32) txt(23)
|                  bin(20) properties(13) class(13)
|      Conf files: cmake(2);
```

</details>
<details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
dart-code|Dar|3.56.0
flutter|Dar|3.56.0
material-icon-theme|PKi|4.23.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
azure-dev_surveyone:30548225
vsccc:30610678
pyindex848:30577860
nodejswelcome1:30587005
2e4cg342:30602488
iaj6b796:30613358
f6dab269:30613381
fim-prod:30623723

```

</details>

**Comment by deepak1556** [comment]
Merging to https://github.com/microsoft/vscode/issues/170585

Can you comment on the other issue with a minimal repro, thanks!
