### ISSUE TITLE
In full screen mode, the upper part of tabs would become title bar?

### ISSUE THREAD

**Issue by ShangxuanWu** [Microsoft/vscode#17052]
- VSCode Version: Code 1.7.2 (7ba55c5860b152d999dda59393ca3ebeb1b5c85f, 2016-11-21T22:14:18.217Z)
- OS Version: Linux x64 4.4.0-53-generic
- Extensions:

|Extension|Author|Version|
|---|---|---|
|matlab|Gimly81|0.4.0|
|python|donjayamanne|0.5.5|
|Lua|keyring|0.0.8|
|cpptools|ms-vscode|0.9.3|

---

Steps to Reproduce:

1.Press F11 to enter full screen mode
2.Click the upper part of the tabs would be clicking the title bar, which is strange.

**Comment by bpasero** [comment]
@ShangxuanWu can you share a video or screenshot what you mean?

**Comment by bpasero** [comment]
@ShangxuanWu ping

**Comment by bpasero** [comment]
A number of days has past without answer on the questions asked. I am thereby going to close this issue to clean up our backlog of issues. Once you can answer on the questions, the issue can be reopened again. Thanks for understanding this process!
