### ISSUE TITLE
windows bat file syntax highlighting problem

### ISSUE THREAD

**Issue by kokutoukiritsugu** [microsoft/vscode#170593]
Type: <b>Bug</b>

windows batch:
```
if not %errorlevel%==0 echo error!!! & echo; & exit /b
if not %errorlevel%==0 echo error!!! && echo; && exit /b
if not %errorlevel%==0 echo error!!! || echo; || exit /b

```
![image](https://user-images.githubusercontent.com/5471433/210677209-80731e47-c823-4169-a7ce-b17197611b69.png)

the second "echo" and "exit" command not highlighting

VS Code version: Code 1.74.2 (e8a3071ea4344d9d48ef8a4df2c097372b0c5161, 2022-12-20T10:29:14.590Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 5600X 6-Core Processor              (12 x 3700)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.93GB (2.93GB free)|
|Process Argv|K:\\EasyU\\driver\\_common_printer_add.bat --crash-reporter-id bbaba037-8e76-4429-9304-78de16cb0895|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (34)</summary>

Extension|Author (truncated)|Version
---|---|---
ZwLisp|Zws|1.0.8
maxscript|And|0.0.2
bat-snippets|bat|0.2.0
auto-align|bla|0.0.13
prettier-toml|bod|0.1.0
vscode-better-align|cho|1.3.1
xml|Dot|2.5.1
vscode-glsllint|dto|1.8.0
shell-format|fox|7.2.2
reg|ion|1.1.0
columnpaste|joh|0.0.7
vscode-smart-column-indenter|lmc|0.0.13
auto-build|mar|2.1.45
clang-format|mjo|1.10.0
vscode-language-pack-zh-hans|MS-|1.74.12140931
csharp|ms-|1.25.2
isort|ms-|2022.8.0
python|ms-|2022.20.1
vscode-pylance|ms-|2022.12.20
jupyter|ms-|2022.11.1003412109
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.12
vscode-jupyter-cell-tags|ms-|0.1.6
vscode-jupyter-slideshow|ms-|0.1.5
cpptools|ms-|1.13.8
powershell|ms-|2022.12.1
platformio-ide|pla|2.5.5
vscode-xml|red|0.23.0
vscode-yaml|red|1.10.1
vscode-vba|ser|0.8.0
shader|sle|1.1.5
sq|sq|0.0.1
even-better-toml|tam|0.19.0
clang-format|xav|1.9.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vstes627:30244334
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
azure-dev_surveyone:30548225
pyindex848:30577860
nodejswelcome1cf:30587006
2e4cg342:30602488
3d0df643:30613357
89544117:30613380
fim-prod:30623723

```

</details>

**Comment by kokutoukiritsugu** [comment]
another problem:
echo new line:
```
echo,
echo;
echo(
echo/
echo+
echo=
echo.
echo\
echo:

```

only two of then highlighting
![image](https://user-images.githubusercontent.com/5471433/210677672-e4a64340-c41c-4265-960e-085cd5cd5a61.png)


https://stackoverflow.com/a/6379940

**Comment by alexr00** [comment]
Copied to upstream repo: https://github.com/mmims/language-batchfile/issues/39
