### ISSUE TITLE
Get Started Page, Command Palette, Python Interpreter

### ISSUE THREAD

**Issue by IrshaadAli1** [microsoft/vscode#170592]
Type: <b>Bug</b>

When on VSCode [Visual Studio Code], I tried setting up Python on the "Get Started" page. I clicked on [Select Python Interpreter] but nothing appeared.
I tried doing it manually by going on the "Command Palette" and typing in 'Select Interpreter' but came up with the error upon clicking the command:

Visual Studio Code
Command 'Python: Select Interpreter' resulted in an error (command 'python.setInterpreter' not found)
![image](https://user-images.githubusercontent.com/98787249/210676010-32c5e2ed-bcbd-4ad0-95f0-b894073f1d9f.png)

VS Code version: Code 1.74.2 (e8a3071ea4344d9d48ef8a4df2c097372b0c5161, 2022-12-20T10:29:14.590Z)
OS version: Windows_NT x64 10.0.19044
Modes: Restricted
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz (4 x 2712)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|7.91GB (0.46GB free)|
|Process Argv|--crash-reporter-id 2f835283-b323-4fa7-b02c-5d4bf13aa264|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2022.20.1
vscode-pylance|ms-|2023.1.10
jupyter|ms-|2022.11.1003412109
jupyter-keymap|ms-|1.0.0
java|red|1.13.0
vscodeintellicode|Vis|1.2.29
vscode-maven|vsc|0.40.2

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263cf:30335440
vscorecescf:30445987
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vscaac:30438847
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
azure-dev_surveyonecf:30548226
pyindex848cf:30577861
nodejswelcome1cf:30587006
3biah626:30602489
3d0df643:30613357
89544117:30613380
fim-prod:30623723
```

</details>

**Comment by bhavyaus** [comment]
This appears to be an issue with the [vscode-python](https://github.com/microsoft/vscode-python). Please use the Python: Report issue command to report this issue.
cc: @karrtikr

Related: https://github.com/microsoft/vscode/issues/170517
