### ISSUE TITLE
Provide a setting to disable the selection mode while holding down the ALT key

### ISSUE THREAD

**Issue by valord577** [microsoft/vscode#170555]
Does this issue occur when all extensions are disabled?: No

- VS Code Version: 1.74.2
- OS Version: Windows_NT x64 10.0.22623

https://code.visualstudio.com/docs/terminal/basics#_mouse-events-mode

https://user-images.githubusercontent.com/30427460/210571529-fe694739-21bc-4eb2-995a-445b35054abd.mp4

**Comment by meganrogge** [comment]
Not sure what you mean - can you pls elaborate?

**Comment by valord577** [comment]
I can't use these shortcuts. Because when I press the ALT key, the cursor turns into a cross and goes into selection mode.

![1673021701164](https://user-images.githubusercontent.com/30427460/211052662-d29693eb-e6fb-488d-aa0b-95cd66f880b4.png)

**Comment by meganrogge** [comment]
this setting disables that for mac, `terminal.integrated.macOptionClickForcesSelection` but I don't believe we can disable it for windows. @tyriar might know why that is the case

**Comment by valord577** [comment]
> this setting disables that for mac, `terminal.integrated.macOptionClickForcesSelection` but I don't believe we can disable it for windows. @Tyriar might know why that is the case

`terminal.integrated.macOptionClickForcesSelection` does not work for windows.

**Comment by valord577** [comment]
And I also can't use the Emacs shortcuts on search input box.

![1673022695350](https://user-images.githubusercontent.com/30427460/211055197-cddcc95f-aa72-44b6-97b5-84a75be3e9d1.png)

**Comment by Tyriar** [comment]
What are you trying to do with alt+click where you need to disable this?

**Comment by valord577** [comment]
Not alt+click. When I press the ALT key, the cursor turns into a cross and goes into selection mode. So I can't use the shortcuts, such as alt+f, alt+c, alt+v...

**Comment by valord577** [comment]
Could you provide a setting to disable the selection mode while holding down the ALT key? @Tyriar

**Comment by Tyriar** [comment]
Oh, that's nothing to do with the cursor. See https://code.visualstudio.com/docs/terminal/advanced#_mnemonics for how to allow mnemonics.
