### ISSUE TITLE
`insert snippet with clipboard variables` test triggers permission dialog

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#170511]
When I run `scripts/test-web-integration.sh --debug` on my macOS, they eventually hang here asking for permissions for clipboard:

<img width="1314" alt="image" src="https://user-images.githubusercontent.com/900690/210421699-eb1c0782-5162-4f7a-884f-4d0fd8ce0b20.png">

Works fine when I skip this test:

https://github.com/microsoft/vscode/blob/c258547b50e70486896a3dafcc1447fe28ea4400/extensions/vscode-api-tests/src/singlefolder-tests/editor.test.ts#L53

I think we need something like https://playwright.dev/docs/api/class-browsercontext#browser-context-grant-permissions if we wanted to avoid such a popup.

//cc @alexdima

**Comment by bpasero** [comment]
https://github.com/microsoft/vscode/pull/170490/commits/9d2bdb850db5eb464318cd7f773244f6364112d0#diff-1254034211415436e2a808273dbb33090414834222490e8998a908bafe41b2e8R38 seems to make this work for me, please take a look

**Comment by jrieken** [comment]
@bpasero What did change here? The test is already 3 years old. Is this a playwright or browser update?

**Comment by bpasero** [comment]
Yeah its possible newer playwright versions caused this.

**Comment by jrieken** [comment]
Then we are good with https://github.com/microsoft/vscode/commit/9d2bdb850db5eb464318cd7f773244f6364112d0#diff-1254034211415436e2a808273dbb33090414834222490e8998a908bafe41b2e8R38, right?

**Comment by bpasero** [comment]
Oh yeah, forgot that this got merged already.
