### ISSUE TITLE
Git not working in visual studio code.

### ISSUE THREAD

**Issue by queston02** [Microsoft/vscode#17056]
- VSCode Version: Code 1.7.2 (7ba55c5860b152d999dda59393ca3ebeb1b5c85f, 2016-11-21T22:06:37.428Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions:

|Extension|Author|Version|
|---|---|---|

---

Steps to Reproduce:

1. Install Git
2. Install Visual Studio Code.
3. Open any folder which is a git repository.
4. Get following message "There was an issue running a git operation. Please review the output or use a console to check the state of your repository."
5. Output does not display anything.

**Comment by joaomoreno** [comment]
Which Git version did you install? If you open a Command Prompt, can you run any git commands? If you open the dev tools, `F1 > Toggle Developer Tools`, is there any information there?

**Comment by queston02** [comment]
Sorry missed your reply. Below is the answer to all your questions.

1. version 2.11.0.windows.1
2. Yep, i am able to run all git commands from command prompt.
3. F1 in VS code opens commands palette.

**Comment by queston02** [comment]
Any Updates?

**Comment by hickerm** [comment]
I look to be having the same issue, been trying to get the git integration going in VSCode for a couple weeks now.

1. Running VSCode 1.8.1
2. Running git version 2.11.0.windows.1
3. I am able to run git commands from the VSCode command prompt, but it gives me a red "error" box "there was an error running a git operation". It also gives me a blue "info" box with some git commits (the hash and commit message), so it's odd it appears to not work, yet work. I've not been able to do any sort of pull via VSCode, I'm still using the git bash for all git operations in my workflow.
4. Below is the error message in developer tool console.

messageService.ts:126There was an issue running a git operation. Please review the output or use a console to check the state of your repository.: Error: There was an issue running a git operation. Please review the output or use a console to check the state of your repository.
    at Object.g [as create] (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:30:20765)
    at t.wrapGitError (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:105:18911)
    at file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:105:18594
    at Object.v [as _notify] (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:32:13263)
    at Object.enter (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:32:16768)
    at _run (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:32:18089)
    at _chainedError (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:32:17448)
    at n (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:32:15271)
    at Object.v [as _notify] (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:32:13263)
    at Object.enter (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:32:16768)

**Comment by joaomoreno** [comment]
Does it work if you set it to:

```
C:\Program Files\Git\bin\git.exe
```

**Comment by hickerm** [comment]
That helped a little but I run into other problems.  For the record, my settings.json file was updated to (double backslashes):

    "git.path": "C:\\Program Files\\Git\\bin\\git.exe"

With that I can push to our Atlassian Stash server, but when I try to push/deploy to any development server I get:

    Permission denied, please try again.
    Permission denied (publickey).
    fatal: Could not read from remote repository.

    Please make sure you have the correct access rights and the repository exists.

I found http://blog.alner.net/archive/2015/08/24/vs_code_with_git_ssh_keys_that_use_passphrases.aspx which basically says:
    
    Open a command prompt.
    Run "start-ssh-agent" and answer passphrase prompts.
    Run "code" to launch VS Code from that environment.

So tried that but get the same permission denied errors.

I'm just going to use the git bash as that's never given me any problems.

**Comment by joaomoreno** [comment]
I will close this, since the fix is to set the `git.path` variable.

--

@hickerm, now you're just stuck behind the SSH key configuration. I suggest to read https://help.github.com/articles/generating-an-ssh-key/#platform-windows

**Comment by queston02** [comment]
Hi @joaomoreno,

For me issue didn't resolved even after setting `git.path` variable.
Still getting "There was an issue running a git operation. Please review the output or use a console to check the state of your repository."

Thanks,
Chandramani Pandey

**Comment by ChrisW123** [comment]
I get the same error above.

**Comment by inferiorhumanorgans** [comment]
Yep I'm seeing the same problem on OSX (10.11.6)

**Comment by QuadCoreBr** [comment]
**Same error above** as hickerm on Windows 10. Configuring git.path as joaomoreno said doesn't seem to work. I even configure the terminal to use the git bash terminal and it's the same. VS code can't resolve the ssh auth and I'm sure it's VSC git managment because I can do everything normally inside the git bash. 
This is the small log in the output:
git fetch
**Permission denied (publickey).
fatal: Could not read from remote repository.**

Please make sure you have the correct access rights
and the repository exists.
git fetch
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by ChrisW123** [comment]
I posted my solution to this in another thread.  Here it is again.... Maybe it will work for you.

1) Uninstal Git.
2) Uninstal GitHub gui app.  You can try to reinstall it later if you need it.
3) Checked Windows credentials for GitHub password. Make sure your credentials are correct.
4) Reboot.
5) Exit VS Code or WebStorm, etc.
6) Install Git from here: https://git-scm.com/download/win filename: Git-2.12.1-64-bit.exe
7) Restart VS Code, WebStorm, etc. Open one of your local repos and see if Git works now.

**Comment by UKirsche** [comment]
Here is my solution:
When i installed git-scm it set its home directory somewhere on another drive. thus it read from the ./ssh directory on that drive which was empty. start git bash and enter `pwd` to see where you are. the change with `cd ./ssh` to the ssh-directory used for the bash. i copied my files from c:/.../.ssh/id_rsa.* to this folder
