### ISSUE TITLE
${fileBasename}  contains extensions

### ISSUE THREAD

**Issue by yycalm** [Microsoft/vscode#17055]
- VSCode Version:1.7.2
- OS Version:windows7 64bit
- extensional：cpptools 0.9.2

Steps to Reproduce:

1. In launch.json，${fileBasename}  contains extensions,

"program":"${workspaceRoot}/${fileBasename}.exe",

 ==>"program":"d:/test/filename.cpp.exe",

I  need is  "program":"d:/test/filename.exe".

**Comment by isidorn** [comment]
Try using ${fileBasenameNoExtension} that should be available in 1.8 in a week or currently in vscode insiders which can be found 
http://code.visualstudio.com/
