### ISSUE TITLE
Can't display project name when restart VScode in workspace mode

### ISSUE THREAD

**Issue by weijuer** [microsoft/vscode#170600]
Type: <b>Bug</b>

1.Some projects in workspace mode;
2.open some project in terminal, and then restart IDE(VScode);

VS Code version: Code 1.74.2 (e8a3071ea4344d9d48ef8a4df2c097372b0c5161, 2022-12-20T10:29:14.590Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6400 CPU @ 2.70GHz (4 x 2712)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.91GB (4.84GB free)|
|Process Argv|--crash-reporter-id 427fd4e9-daf9-45b0-ba2d-726b48f78fd4|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (90)</summary>

Extension|Author (truncated)|Version
---|---|---
codesnap|adp|1.3.4
Bookmarks|ale|13.3.1
project-manager|ale|12.7.0
vscode-sqlite|ale|0.14.1
arepl|alm|2.0.4
browse-lite|ant|0.3.0
vite|ant|0.2.5
ascii-tree-generator|apr|1.2.4
emojisense|bie|0.9.1
converttoasciiart|Bit|1.0.3
wechat-snippet|Cha|0.4.11
wxml-vscode|cny|0.1.2
coderoad|Cod|0.17.2
miniprogram-vscode-extension|cra|1.4.15
native-ascii-converter|cwa|1.0.9
vue-peek|dar|1.0.2
vscode-eslint|dba|2.2.6
githistory|don|0.6.19
python-environment-manager|don|1.0.4
gitlens|eam|13.2.0
remotehub|eam|0.5.0
easymock|Eas|1.0.14
prettier-vscode|esb|9.10.3
front-end-daily-question|eve|1.1.7
auto-close-tag|for|0.5.14
auto-rename-tag|for|0.1.10
code-runner|for|0.11.8
remotehub|Git|0.48.0
live-sass|gle|5.5.1
google-translate|han|1.2.7
debug-visualizer|hed|2.4.0
vscode-drawio|hed|1.6.4
rest-client|hum|0.25.1
comment-translate|int|2.2.4
solidity|Jua|0.0.141
vsc-python-indent|Kev|1.18.0
vscode-gutter-preview|kis|0.30.0
vscode-leetcode|Lee|0.18.1
i18n-ally|lok|2.8.1
git-emoji-zh|mai|1.1.9
rainbow-csv|mec|3.5.0
git-graph|mhu|1.30.0
dotenv|mik|1.0.1
easy-less|mrc|1.7.4
vscode-goto-node-modules|mrl|1.2.1
vscode-docker|ms-|1.23.3
vscode-language-pack-zh-hans|MS-|1.74.12140931
isort|ms-|2022.8.0
python|ms-|2022.20.1
vscode-pylance|ms-|2023.1.10
jupyter|ms-|2022.11.1003412109
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.12
vscode-jupyter-cell-tags|ms-|0.1.6
vscode-jupyter-slideshow|ms-|0.1.5
remote-containers|ms-|0.266.1
remote-wsl|ms-|0.72.0
vscode-remote-extensionpack|ms-|0.23.0
azure-repos|ms-|0.24.0
live-server|ms-|0.4.4
remote-repositories|ms-|0.26.0
vsliveshare|ms-|1.0.5797
sftp|Nat|1.16.1
vscode-vue3-snippets|Nic|0.1.0
vetur|oct|0.36.1
vscode-versionlens|pfl|1.0.10
minapp-vscode|qiu|2.4.8
vscode-thunder-client|ran|2.2.4
LiveServer|rit|5.7.9
partial-diff|ryu|1.4.3
esdoc-mdn|sam|0.11.0
vscode-javascript-booster|sbu|14.0.1
vue-vscode-snippets|sdr|3.1.1
vue-helper|she|2.4.7
sourcegraph|sou|2.2.14
vs-picgo|Spa|2.1.6
language-stylus|sys|1.16.0
stylus-supremacy|thi|2.17.4
truffle-vscode|tru|2.7.1
codelf|unb|11.7.0
intellicode-api-usage-examples|Vis|0.2.6
vscodeintellicode|Vis|1.2.29
vscodeintellicode-completions|Vis|1.0.20
vscode-icons|vsc|12.0.1
volar|Vue|1.0.22
vscode-typescript-vue-plugin|Vue|1.0.22
vscode-todo-highlight|way|1.0.5
JavaScriptSnippets|xab|1.8.0
markdown-all-in-one|yzh|3.5.0
markdown-editor|zaa|0.1.10

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscoreces:30445986
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
azure-dev_surveyone:30548225
vscccc:30610679
pyindex848cf:30577861
nodejswelcome1cf:30587006
2e4cg342:30602488
iaj6b796:30613358
89544117:30613380
fim-prod:30623723

```

</details>

**Comment by weijuer** [comment]
![image](https://user-images.githubusercontent.com/12313268/210693469-98211290-c467-480b-8d35-af7e0401c704.png)

**Comment by joyceerhl** [comment]
After reloading a window containing a workspace with two terminals open, my terminals aren't restored. This repros for me on Windows with the workspace file from https://github.com/microsoft/vscode/blob/2ef9d1c99fb322b8a3f61279507164161bedc8ff/extensions/vscode-api-tests/testworkspace.code-workspace

Before reload 
![image](https://github.com/microsoft/vscode/assets/30305945/be8440cc-1793-4e14-b040-9c49dcf2dda3)

After reload 
<img width="1105" alt="image" src="https://github.com/microsoft/vscode/assets/30305945/e197f9e4-a55d-456b-b56e-332ed4a2ab97">

**Comment by Tyriar** [comment]
@joyceerhl btw you must enter text into the terminals for them to be restored.

I can reproduce the problem:

![image](https://github.com/microsoft/vscode/assets/2193314/30e86796-38fa-4e07-889e-eba48f022b41)

Apparently we don't serialize the tab titles properly
