### ISSUE TITLE
New macOS application icon

### ISSUE THREAD

**Issue by vancura** [Microsoft/vscode#17066]
Hi,

I have a new application icon for you – the icon reflects visual rendering of the icon I designed for the Visual Studio for Mac.

![tmp 2x](https://cloud.githubusercontent.com/assets/4982/21095074/294a1894-c05a-11e6-8985-58faaf204283.png)

I'd like to create a PR – I just can't find the icns files anywhere, could you please direct me where they are? It seems they're not in this repo.

Here's the preview of how a patched vscode looks in the Dock.

![unspecified](https://cloud.githubusercontent.com/assets/4982/21094887/54d05ef2-c059-11e6-8d91-99fe46e7ef9a.png)

**Comment by bpasero** [comment]
I LOVE this icon.

**Comment by replete** [comment]
Pretty! +1

**Comment by davidbarsky** [comment]
I absolutely love this icon. Question: is there any way that you can share the `.icns` file so that I can apply it to my editor right now?

(I understand if that might not be feasible...)

**Comment by ktml** [comment]
Love it. I think the border thickness is perfect, it would scale well for smaller dock size.

**Comment by ktml** [comment]
Wait how did I unassign bgashler1, didn't mean to do that...

**Comment by danqing** [comment]
It'll be so good if this can be used..

and +1 for the icns file if that can be shared!

**Comment by trondwernerhansen** [comment]
@vancura Great job! Is this icon available somewhere?

**Comment by brhs** [comment]
This is so great. Do you mind uploading it somewhere so we can use it before it gets merged?

**Comment by chrisdias** [comment]
Closing all icon issues against https://github.com/Microsoft/vscode/issues/6607
