### ISSUE TITLE
typing  anything in settings search box makes the content on the left overlaps 

### ISSUE THREAD

**Issue by avi-dey** [microsoft/vscode#170699]
whenever I type anything on the settings' search box, the content on the left starts overlapping. I believe it is not text that is overlapping but some strange characters. it goes as soon as I hover over them and comes back when I remove my cursor. the degree of the overlap varies with respect to what is being typed in the search box.

Does this issue occur when all extensions are disabled?: Yes

- VS Code Version:  1.74.2
- OS Version: PopOS 22.04 LTS

Steps to Reproduce:

1. open settings tab
2.  search anything in the search box

Image with extensions disabled: 
![Screenshot from 2023-01-06 21-14-25](https://user-images.githubusercontent.com/97702087/211046688-aef81ada-c817-4a7e-9f68-2a2aa80bff59.png)

Image with extensions enabled:
![Screenshot from 2023-01-06 19-49-25](https://user-images.githubusercontent.com/97702087/211046698-232b539c-7122-43ea-b0d5-0328dc3aec07.png)

**Comment by rzhao271** [comment]
Does this issue still occur when running code with `--disable-gpu`?

**Comment by rzhao271** [comment]
Closing in favour of #171367
