### ISSUE TITLE
Automatically complete statement on semicolon

### ISSUE THREAD

**Issue by tzengshinfu** [microsoft/vscode#170661]
It works like Visual Studio C# IntelliSense 'Automatically complete statement on semicolon'
![vs_crash](https://user-images.githubusercontent.com/2170033/210957772-e0ee1913-18f6-4a64-aebe-203a02833c33.gif)

![image](https://user-images.githubusercontent.com/2170033/210955037-9dee65ac-02a6-47b5-85e3-893526aac80d.png)

**Comment by jrieken** [comment]
The setting is called `editor.acceptSuggestionOnCommitCharacter`

**Comment by tzengshinfu** [comment]
Hi, jrieken:
Thank you for your reply. I didn’t make it clear enough.

I mean the function that is within parentheses and you type a semicolon , it automatically moves it to the end of the brackets 
even no parameter method.
![vs_semicolon](https://user-images.githubusercontent.com/2170033/211230196-f75ab82a-71b4-4c80-bc07-998f3a18774f.gif)
