### ISSUE TITLE
`xterm` and addons should not be a `remote` dependency

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#170615]
At least those components that require `browser` API:

https://github.com/microsoft/vscode/blob/689624e401b5fb93ddbdf1b764997d936b6fa636/remote/package.json#L27-L33

**Comment by Tyriar** [comment]
Isn't `remote/` for `scripts/code-server` which serves the frontend?

**Comment by bpasero** [comment]
@Tyriar hm, we also have `remote/web/package.json`, maybe as a build step the two should merge then? I see the `remote/package.json` as server only dependencies.

**Comment by Tyriar** [comment]
Right, but it is a server dependency as the server needs to serve `xterm` (and uses `xterm-headless` internally). As opposed to web which only needs to serve the frontend (no `xterm-headless`). Merging seems like it's overcomplicating things to me, but if we do that we can remove them

**Comment by alexdima** [comment]
@Tyriar Perhaps an exploration item could be to remove all except `xterm-headless`.

**Comment by Tyriar** [comment]
Closing as designed as it's my understanding they are server dependencies (the server needs to serve them) as well as web frontend dependencies (the "serverless" frontend needs to server them too).

Feel free to remove them from server if my understanding is wrong and server uses deps from web.
