### ISSUE TITLE
Allow setting for viewing Open Editors list by recently viewed

### ISSUE THREAD

**Issue by johnbendi** [microsoft/vscode#170678]
As per https://github.com/microsoft/vscode/issues/12453, I will like to open editors to be sorted by recently used

**Comment by gjsjohnmurray** [comment]
This was a Backlog Candidate as #137292 but didn't get enough support to progress to Backlog.

**Comment by johnbendi** [comment]
The default behavior is the Command `View: Show All Editors By Appearance` which I bound to some key. I will like that View to be sorted by recently used.

**Comment by johnbendi** [comment]
> This was a Backlog Candidate as #137292 but didn't get enough support to progress to Backlog.

Okay just saw it now

**Comment by johnbendi** [comment]
> > This was a Backlog Candidate as #137292 but didn't get enough support to progress to Backlog.
> 
> Okay just saw it now

I'm thinking it should be some improvement to #12453, though in my case I will prefer `last accessed` as opposed to `last modified`

**Comment by johnbendi** [comment]
I believe I'm currently being satisfied by `Most Recently Used (mru)` setting. So closing this issue.
