### ISSUE TITLE
not work "NPM SCRIPTS"

### ISSUE THREAD

**Issue by darqus** [microsoft/vscode#170646]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: insiders 1.75
- OS Version: win11

Steps to Reproduce:

1. expand "npm scripts" panel on any project
2. click "run" on any task

![изображение](https://user-images.githubusercontent.com/30623895/210850067-d2f03a2d-3809-46d2-99c1-6c8542b1785c.png)

settings
"npm.packageManager": "auto",

**Comment by meganrogge** [comment]
Can you provide your package.json with those scripts?

**Comment by darqus** [comment]
> @meganrogge

https://github.com/darqus/JEST/blob/main/package.json

**Comment by marcellourbani** [comment]
@darqus Can't read that language, but looks like a file permission issue
What happens if you run in the terminal:
```
yarn run test
```

**Comment by meganrogge** [comment]
I believe this is already fixed, can you see if you can reproduce in the [Insiders build](https://code.visualstudio.com/insiders)?
/label info-needed
