### ISSUE TITLE
From TS's perspective, there's no difference between this code and

### ISSUE THREAD

**Issue by Fgu67** [microsoft/vscode#170608]
From TS's perspective, there's no difference between this code and
```ts
const func = (obj1: A[] | B[], obj2: A[] | B[]):void => {
      obj1[0].children.push(obj2[1])
}
```
which is clearly unsafe. We don't track where objects "came from" to establish higher-order relations.

_Originally posted by @RyanCavanaugh in https://github.com/microsoft/TypeScript/issues/52084#issuecomment-1370174616_

**Comment by IllusionMH** [comment]
Is there actual issue you want to report?
