### ISSUE TITLE
Whether the Vs code can add and save search items., not just historical records.

### ISSUE THREAD

**Issue by ednykissyou** [microsoft/vscode#170625]
Whether the Vs code can add and save search items.
Can save search items, not just historical records.
In this respect, Adobe InDesign does the best job of searching and replacing, and can save its own replacement projects.
You can import or export your own search items.
It can be called directly when necessary.

Emiditor does a good job in this respect, but it is only a historical record. It cannot be saved, imported or exported

**Comment by andreamah** [comment]
You can use the search editor for this. Just run `Search Editor: Open Search Editor` and run your search. You should be able to save the result and open the file later.
