### ISSUE TITLE
Add slim template engine support

### ISSUE THREAD

**Issue by davidesantangelo** [Microsoft/vscode#1706]

**Comment by tonyedwardspz** [comment]
+1

**Comment by ozepon** [comment]
+1

**Comment by Yukaii** [comment]
There is already [an extension in marketplace](https://marketplace.visualstudio.com/items?itemName=sianglim.slim), but not work as expected when parsing embedded ruby code For example:

> vscode ruby slim

![vscode](http://i.imgur.com/5mHRMWC.png)

> sublime ruby slim

![sublime](http://i.imgur.com/jF4xz4m.png)

**Comment by liqueflies** [comment]
+1

**Comment by mjbvz** [comment]
This is something that I would expect an extension to provide. Please try to file any issues against that extension (I can't seem to find a repo for it however), or look into creating a new extension that fixes these issues.
