### ISSUE TITLE
Jupyter audio cues stop working

### ISSUE THREAD

**Issue by TeamDman** [microsoft/vscode#170648]
## Does this issue occur when all extensions are disabled?: Yes

Disabled all extensions then enabled Python extension which enabled a few others
![image](https://user-images.githubusercontent.com/9356891/210854440-5142f41b-64a3-495f-8297-50f71bb9bacf.png)

## VSCode info

Version: 1.74.2 (system setup)
Commit: e8a3071ea4344d9d48ef8a4df2c097372b0c5161
Date: 2022-12-20T10:29:14.590Z
Electron: 19.1.8
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.19044
Sandboxed: No

## Steps to Reproduce:

1. Open settings.json, use values
```json
    "audioCues.notebookCellCompleted": "on",
    "audioCues.notebookCellFailed": "on",
```
2. Git clone https://github.com/Curt-Park/rainbow-is-all-you-need/blob/master/04.dueling.ipynb
3. Open the 04.dueling.ipynb notebook
4. Run the cells up to and including the `Initialize` header, the audio cue should play
5. Run the cell containing `agent.train`
6. Minutes later the cell completes, audio cue doesn't play
7. All cells no longer play happy audio cues ): even in other notebooks
8. Run a cell with `assert False` and the sad audio cue still works
9. Reload window and the success cues work again until they stop again for some reason

**Comment by roblourens** [comment]
Is it always that cell with `agent.train` that breaks it? Are you doing anything else while it's running? (working in other notebooks, making edits in this notebook, etc)

**Comment by TeamDman** [comment]
There's a lot that seems to not be working upon further inspection

Here's a video, make sure to turn the volume on. The extensions are what gets enabled when I enable python after disabling everything.

https://user-images.githubusercontent.com/9356891/211127264-441819c6-32cd-4f14-bae1-cba9204a20ba.mp4

A few things I noticed

- Sounds didn't work at the start before agent.train was called
- Sound doesn't play consitently when running the same cell over again
- Sound breaks after running train with 1000 but not 100 or 10
- Sounds for errors dont break but they also have consistency issues
- Right now the sound is only played once when running multiple cells

**Comment by roblourens** [comment]
I can repro this. I sometimes get this error

<img width="1312" alt="image" src="https://user-images.githubusercontent.com/323878/211219125-63e5a0c5-8565-47db-b1ec-cf4fe515052e.png">

then the sound won't play anymore. Need to remove the sound from `this.playingSounds` when it fails to play

**Comment by roblourens** [comment]
It doesn't happen reliably though. I'm not sure why I got this error.

**Comment by roblourens** [comment]
And when I set a breakpoint in `playSound` then it seems to happen every time.

**Comment by hediet** [comment]
> Need to remove the sound from this.playingSounds when it fails to play

This is fixed now. Does this bug still reproduce?

**Comment by DonJayamanne** [comment]
Marking as verified by author.
