### ISSUE TITLE
CSS format setting: Space around Selector Seperator is not working

### ISSUE THREAD

**Issue by SaroGFX** [microsoft/vscode#170627]
Type: <b>Bug</b>

Despite having the option ticked on both the user and workspace, it is still removing the space between selectors such as > and +. 

![Screenshot 2023-01-05 at 15 33 06](https://user-images.githubusercontent.com/3781800/210804275-4e2d0cfc-50ea-49e5-a228-25a9398ddce1.png)

![Screenshot 2023-01-05 at 15 38 12](https://user-images.githubusercontent.com/3781800/210805299-f7836196-d896-45a3-b621-480cc499dcb1.png)

I am also using Prettier, but it also occurs when it is disabled. 

Please let me know if you require any other details or have ideas what could be causing this. 

VS Code version: Code 1.74.2 (Universal) (e8a3071ea4344d9d48ef8a4df2c097372b0c5161, 2022-12-20T10:26:09.430Z)
OS version: Darwin x64 22.1.0
Modes:
Sandboxed: No

<details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
azure-dev_surveyone:30548225
pyindex848:30577860
nodejswelcome1:30587005
282f8724:30602487
iaj6b796:30613358
89544117:30613380
fim-prod:30623723
vscup:30628656

```

</details>

**Comment by aeschli** [comment]
Can you provide the complete (but small) css code sample?
```
> div {
    
}
```
is not valid css.

**Comment by SaroGFX** [comment]
My example was from nested SCSS, so essentially this is `header > div { /*props*/ }` 

Which gives the same behaviour.

**Comment by aeschli** [comment]
When I try your sample, with `"css.format.spaceAroundSelectorSeparator": true` spaces are added.

![Peek 2023-01-11 18-00](https://user-images.githubusercontent.com/6461412/211869454-fa6dccf4-8c59-4e73-abe9-f140dd324cb2.gif)

I also tried
`>div { /*props*/ }` in SCSS

 with `"scss.format.spaceAroundSelectorSeparator": true`

![Peek 2023-01-11 18-04](https://user-images.githubusercontent.com/6461412/211870111-5eb6690d-ac89-4358-87f2-42c858ed03e8.gif)

**Comment by SaroGFX** [comment]
Thank you! I missed the fact that the css and scss had it's own setting 🙈 (I searched for CSS in settings) 

So after enabling it also for scss, it now works like it should. Closed report.
