### ISSUE TITLE
Can't bring command center back

### ISSUE THREAD

**Issue by marky-123** [microsoft/vscode#170621]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: Insiders
- OS Version: Windows 11

Steps to Reproduce:

1. Hide the go back and go forward buttons next to the command center by right clicking on the command center and clicking the buttons to hide the go back and go forward buttons.
2. Hide the command center by right clicking on the command center and clicking the button to hide the command center which is below the button to hide the go forward button. There are two buttons to hide the command center which seams strange.
3. Now the command center is hidden and it won't come back by right clicking on the menu bar and clicking to show the command center. I've re-installed vscode and it still won't come back.

https://user-images.githubusercontent.com/106014361/210779678-d2cf86a4-b45c-44d2-b271-011da113031b.mp4

**Comment by gjsjohnmurray** [comment]
I was able to recover from this by opening Command Palette (F1) and running `View: Reset All Menus`

**Comment by sbatten** [comment]
@jrieken, this seems like an issue in all toolbars, yes?

**Comment by jrieken** [comment]
Depends. Usually commands hide into the `...`-overflow menu. Tho, some menus don't have that and IMO shouldn't have it (the CC would look funny with `...`). Tho, that causes the problem of being able to hide everything and than you are only left with the nuclear "reset all" option

**Comment by jrieken** [comment]
I believe these overflow-less cases need to be handled case by case, e.g for CC we could connect it with its setting

**Comment by sbatten** [comment]
I was thinking more generally that toolbars which do not have an overflow just disable hiding the last item. It's a pattern we already have for views. Also, should the command center entry within the command center be renamed to something else like "Start search" or something better to differentiate it.

**Comment by jrieken** [comment]
:+1: for both +2️⃣

**Comment by ArturoDent** [comment]
It is confusing that when all the elements of the CC have been hidden that the context menu on the TitleBar (or is it the MenuBar?) will show the CC as enabled still - which I guess it technically is - enabled but hidden is an odd state.  

Could that context menu be modified to show a crossed-out eye icon (i.e., not visible) that when pressed would make it visible again?

**Comment by yilmazdurmaz** [comment]
when its visibility is removed, CC should minimize itself to an icon (maybe near layout icons), or mark itself disabled then enable the title back again (it has issues with window title).
