### ISSUE TITLE
Windows text document URIs not correct

### ISSUE THREAD

**Issue by sideninja** [microsoft/vscode#170618]
Does this issue occur when all extensions are disabled?: Yes

I'm noticing incorrect text document URI format on Windows. When a codelens message is sent to the language server the payload looks like this:
```
[Trace - 12:58:20 PM] Sending request 'textDocument/codeLens - (82)'.
Params: {
    "textDocument": {
        "uri": "file:///c%3A/Users/foo/Documents/test/test.go"
    }
}
```
If you look at the URI it contains an extra `/` so using any standard URI parsing methods it will output a file location as: `/c:/Users/foo/Documents/test/test.go` which is not a valid path for Windows. This works ok on UNIX based systems as the first `/` denotes an absolute path. 

I tried looking into whether that was our extension issue but I've managed to reproduce the issue on other extensions. It makes me believe this is a vscode issue.

Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.74.2
- OS Version: Windows 11

Steps to Reproduce:
1. Use an extension implementing LS
2. Set it to verbose communication and open output of that extension
3. Check what is sent as a document URI when used on Windows

I might be misunderstanding something here after all if anyone knows how to handle windows paths must be you guys :D but still on the LS side we need to load the file provided with that path and it doesn't work unless we strip that extra slash.

**Comment by jrieken** [comment]
> If you look at the URI it contains an extra / so using any standard URI parsing methods it will output a file location as: /c:/Users/foo/Documents/test/test.go which is not a valid path for Windows.

That's because it's a uri-path and not a file system path. For the latter you must use `fsPath`

**Comment by sideninja** [comment]
@jrieken thank you for your answer. Few clarifications.

> That's because it's a uri-path and not a file system path.
I don't quite understand what do you mean it's not a file system path? isn't it supposed to be file system path converted to URI schema, which is defined here https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#uri 
according to that I don't understand why the extra slash is added, isn't the path without valid as well?

> For the latter you must use fsPath
Doesn't really apply to Go and possible other languages, and that's why I raised this, if you use standard library in Go (or some other languages) it will return the path with extra slash which is not valid.

**Comment by jrieken** [comment]
> I don't quite understand what do you mean it's not a file system path?

https://nodejs.org/api/url.html#urlfileurltopathurl does a good job of explaining the difference between a URI-path and FS-path. The `fileURLToPath` is similar to `fsPath` of vscode-uri

> Doesn't really apply to Go and possible other languages, and that's why I raised this, if you use standard library in Go

I am sorry, I am no Go expert but I am confident similar utils will exist there to
