### ISSUE TITLE
decorations aren't in the right spot

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#170651]
no repro atm

![Screenshot 2023-01-05 at 5 08 53 PM](https://user-images.githubusercontent.com/29464607/210897449-df5f13db-d71f-4876-a780-eb6c149f9ad6.png)

**Comment by Tyriar** [comment]
Was this after a resize in either direction or creating a split pane?

**Comment by meganrogge** [comment]
It could've been after a resize vertically, but not 100% certain
