### ISSUE TITLE
OpenSSL error when using copilot in linux machine

### ISSUE THREAD

**Issue by ysig** [microsoft/vscode#170624]
Hi,

I get the following error when using the copilot extension,

`[ERROR] [default] [2023-01-05T14:34:00.913Z] GitHub Copilot could not connect to server. Extension activation failed: "tunneling socket could not be established, cause=write EPROTO 140473655486400:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:332:`

Is there a way to resolve it?

**Comment by lszomoru** [comment]
As this seems to be specific to the Copilot extension, please post a message in their [discussion forum](https://github.com/community/community/discussions/categories/copilot). Thank you!
