### ISSUE TITLE
output window:The compiler output Chinese garbled

### ISSUE THREAD

**Issue by yycalm** [Microsoft/vscode#17061]
- VSCode Version:1.7.2
- OS Version:win7

Steps to Reproduce:

1. output window:The compiler output Chinese garbled.
2. output:
running command> cmd /c cl /Zi /EHsc d:\test\cpp\tmp.cpp 
���� x86 �� Microsoft (R) C/C++ �Ż������� 19.00.24210 ��
��Ȩ����(C) Microsoft Corporation����������Ȩ����
tmp.cpp

**Comment by dbaeumer** [comment]
Dups 3550
