### ISSUE TITLE
Splash image background glitch

### ISSUE THREAD

**Issue by vancura** [Microsoft/vscode#17067]
- VSCode Version: 1.7.2 (1.7.2)
- OS Version: 10.12.2 Beta (16C63a)

Steps to Reproduce:

1. Switch to some darker theme
2. Observe incorrect background of the splash mage:

![screen shot 2016-12-12 at 11 42 09](https://cloud.githubusercontent.com/assets/4982/21096466/48da2572-c060-11e6-85fc-a6957b892b7a.png)

Hopefully you can see it, here's an enhanced version from Photoshop: http://vncr.in/iPva

If you tell me where's the image, I can fix it for you – but it's not in this repo.

**Comment by vancura** [comment]
It seems it's not in the image, right now I have the same glitch above search panel, and splash is fine. I think it's a GPU problem with beta macOS, so be free to close the issue if you think it's Apple to blame :)

**Comment by mrmlnc** [comment]
Sorry, but, please, use search before create a new issue.

See official release notes: http://code.visualstudio.com/updates/v1_6#_macos-sierra-support
See already created issues: #12473, #12474, #12523, #12571, #13175, #13192, #13959, #14233, #14540, #14692

**Comment by vancura** [comment]
Sorry!
