### ISSUE TITLE
Markdown code block highlighting not present for Preview but present in editor

### ISSUE THREAD

**Issue by rafrafek** [microsoft/vscode#170706]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: Version: 1.74.2 (Universal)
Commit: e8a3071ea4344d9d48ef8a4df2c097372b0c5161
Date: 2022-12-20T10:26:09.430Z
Electron: 19.1.8
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Darwin arm64 22.2.0
Sandboxed: No
- OS Version: MacOS Ventura 13.1

Steps to Reproduce:

1. Create .md file and create ` ```py3 ` block with some Python code
2. Open preview

<img width="1250" alt="image" src="https://user-images.githubusercontent.com/23004737/211063274-66ab467a-44dd-422e-a7a3-a25722a6b37c.png">

As you can see, the code in the editor on the left is being highlighted, but in the preview on the right it is not.

The issue occurs for ` ```py3 `.

For ` ```py ` and ` ```python ` it works for both editor and preview. For ` ```python3 ` there is no highlighting at all.

**Comment by mjbvz** [comment]
`python` supports python 3 syntax. Do you really need to use `py3` / `python3`?

**Comment by rafrafek** [comment]
I think I don't really need them. I may have some markdown files with `python3` blocks since GitHub supports them, but it should be relatively easy for me to find & replace them with `python`.

What bothers me the most is the inconsistency of highlighting between code editor and preview for `py3` blocks. Where does the difference come from? Are there any other block types with such inconsistence?

We can also consider it as a fun fact and close the issue since it is very low priority even for the reporter (me). Thanks and have a good week!

**Comment by avisinghal6** [comment]
Hi, I am a newbie to open source and would like to contribute. @mjbvz can I take this up? Could you provide some hints on getting started as well?

**Comment by ArthurLokhov** [comment]
Hi, the problem lies in `hljs`, this library does not have an alias for `py3` and `python3`, only for `python`, `py`, `gyp` and `ipython`. I have solved this problem, but is it really necessary to work with `py3` and `python3` at all? If yes, then I will try to make a pull request (this is my first commit, I don't know how to do it yet).
![2023-01-29_17-18](https://user-images.githubusercontent.com/79355695/215332703-439ad9af-7006-41b6-b92e-938cc26e91a6.png) 

Also, if I understand where to do it, I will turn on the highlight for `ipython` and `python3`. (If anything, I'm sorry, I'm just learning English.)

**Comment by ArthurLokhov** [comment]
Also, please tell me. Do I need to make a PR to the `hljs` library and then when it is updated in `markdown-language-features`, will the changes catch up by themselves? Or can it be changed directly in `node_modules/highlightjs`? I'm just not sure if it's possible to use the second method at all and won't it break something in the future. My experience in the frontend (not commercial) is only a few months, so my question may seem completely stupid to someone. But we have what we have.

**Comment by mjbvz** [comment]
You should just need to add a language mapping to this list: https://github.com/microsoft/vscode/blob/990a496681948ec274da5503b35cd49a7d06c0a2/extensions/markdown-language-features/src/markdownEngine.ts#L414
