### ISSUE TITLE
Markdown preview doesn't correctly parse escaped parenthesis

### ISSUE THREAD

**Issue by ErikSchierboom** [Microsoft/vscode#1707]
For example, consider the following URL: https://msdn.microsoft.com/en-us/library/f7dy01k1(v=vs.110).aspx

This URL has two parentheses in them. To be able to use this URL in a Markdown link, we have to escape the parentheses by prefixing them with a backslash:

`[ildasm](https://msdn.microsoft.com/en-us/library/f7dy01k1\(v=vs.110\).aspx)`

However, the Markdown preview doesn't correctly parse these links:

<img width="1440" alt="screen shot 2015-12-30 at 11 28 12" src="https://cloud.githubusercontent.com/assets/135246/12049531/72ef0f1a-aee8-11e5-9921-aa85e70f5099.png">

**Comment by bpasero** [comment]
Dupe
