### ISSUE TITLE
Allow configuring the built-in formatter to leave `/>` on its own line

### ISSUE THREAD

**Issue by TomasHubelbauer** [microsoft/vscode#170796]
Hi, I have configured the HTML formatter to my liking by disabling extra liners, enabling indentation of `head` and `body`, configuring the formatter to leave my indentation of attributes alone and turning off maximum line length (opting to control it myself instead). I am missing once piece of configuration that would allow me to write HTML the way I prefer, like so:

```html
<input
  autocomplete="off"
  autofocus
  list="suggestionsDatalist"
  placeholder="Press Enter to submit…"
/>
```

With `editor.formatOnSave`, when I save this document, the formatter will move the `/>` after the last attribute, like so:

```html
<input
  autocomplete="off"
  autofocus
  list="suggestionsDatalist"
  placeholder="Type a command or a draft and press Enter…" />
```

I am hoping a setting could be introduced to control this. I want all attributes on one line, when the entire tag fits on a single line, or all attributes on their own line, when it doesn't, with just the attributes on each line, the opening and closing tags on their own respective lines as well.

**Comment by aeschli** [comment]
We use [beautifyjs](http://jsbeautifier.org/) as the underlying HTML formatter. Would you mind filing this request directly against https://github.com/beautify-web/js-beautify ?
