### ISSUE TITLE
Some background colors are changing the foreground color

### ISSUE THREAD

**Issue by heaths** [microsoft/vscode#170732]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.74.2
- OS Version: Windows 11 version 10.0.22621

Steps to Reproduce:

1. Run PowerShell in Windows Terminal and VSCode integrated terminal side-by-side.
2. In both, type ``"`e[38;2;247;246;245mwhite`e[0m"`` and you'll see white foreground text.
3. In both, type ``"`e[48;2;5;163;226m`e[38;2;247;246;245mwhite on blue`e[0m"``.

<img width="793" alt="image" src="https://user-images.githubusercontent.com/1532486/211111731-68426075-e23f-40ba-8eef-8a204e704dee.png">

Notice how the colors are not correct in VSCode.

Note: this is a simplified repro of my OMP prompt, which you can also see the discrepancy in the screenshots. It works with some colors, though, such as white on purple.

**Comment by Tyriar** [comment]
This is an accessibility feature, see https://code.visualstudio.com/docs/terminal/appearance#_why-are-the-colors-in-the-terminal-not-correct
