### ISSUE TITLE
Visual Representation for `Enable All Extensions`

### ISSUE THREAD

**Issue by Siddhant-K-code** [microsoft/vscode#170772]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: (doesn't matter for this)
- OS Version: (doesn't matter for this)

```
Version: 1.74.2 (Universal)
Commit: e8a3071ea4344d9d48ef8a4df2c097372b0c5161
Date: 2022-12-20T10:26:09.430Z
Electron: 19.1.8
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Darwin arm64 22.2.0
Sandboxed: Yes
```
---

Steps to Reproduce:

1. Open the Extensions Tab
2. Click on three dots of `View More`:

<img width="313" alt="image" src="https://user-images.githubusercontent.com/55068936/211166012-553f4f34-dd2d-47e6-a4f4-4ab74fa9b0ae.png">

---

Technically this does enable "all" the installed extensions:

https://github.com/microsoft/vscode/blob/68efb6fe56bd1476e3642ba5752930ce021f5fad/src/vs/workbench/contrib/extensions/browser/extensions.contribution.ts#L697-L699

We could make this consistent & clear with the second option for disable.

Desired Change: `Enable All Extensions` -> `Enable All Installed Extensions `

**Comment by sandy081** [comment]
This also enables any disabled built in extensions. Hence it is called like so
