### ISSUE TITLE
Markdown highlighting bug for the darkmode

### ISSUE THREAD

**Issue by stack-dhruv** [microsoft/vscode#170759]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.74.2 (Universal)
- OS Version: Darwin arm64 22.2.0

Steps to Reproduce:

1. Using the markdown highlighting CDN. (path: `https://cdn.jsdelivr.net/gh/Microsoft/vscode/extensions/markdown-language-features/media/markdown.css`). Using dark mode isn't producing proper background for the code
2. 
<img width="1291" alt="Screenshot 2023-01-07 at 17 24 02" src="https://user-images.githubusercontent.com/59140576/211150670-a714127d-c0ae-4d59-b0cf-b6ab248e7080.png">

## Possible Solution

Change the background `opacity` to 1 to properly configure the dark mode in markdown.

<img width="1148" alt="Screenshot 2023-01-07 at 18 00 52" src="https://user-images.githubusercontent.com/59140576/211150779-4917962c-1eef-471b-9453-9984d7f2459d.png">

**Comment by mjbvz** [comment]
Your markdown preview does not appear to be in dark mode. This is likely either an issue with custom css you are applying to the preview or is being caused by an extension
