### ISSUE TITLE
Notebook diff navigation keybindings need "when"

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#170779]
https://github.com/microsoft/vscode/blob/70c45ba0297f1ce516eafbc56d679a4a2c5a17e7/src/vs/workbench/contrib/notebook/browser/diff/notebookDiffActions.ts#L309-L338

Looks new, this is overriding alt+f3 "show next change" in text editors

**Comment by rebornix** [comment]
@roblourens very good catch. I also wish to have AI detecting this sort of mistakes. Fix is coming https://github.com/microsoft/vscode/pull/170814
