### ISSUE TITLE
Autocomplete consumes word behind cursor

### ISSUE THREAD

**Issue by dmartin** [microsoft/vscode#170712]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.74.2
- OS Version: macOS Ventura 13.1

Steps to Reproduce:

1. Have some token `foo` in your code.
2. Realize that you actually need `SomeClass.bar(foo)` instead. (A class doesn't need to be involved, but it helps illustrate the issue since `.` opens autocompletion.)
3. Place cursor before `foo` and attempt to type `SomeClass.bar(`
4. While autocompleting `SomeClass.bar`, `foo` is deleted.

I don't necessarily expect VSCode to auto-wrap `SomeClass.bar(foo)`, but I would prefer `SomeClass.barfoo` (or a setting to toggle this behavior), so that I don't need to remember what the deleted token was and re-enter it.

Examples:

https://user-images.githubusercontent.com/1657652/211082445-c4090fc4-da3d-4c2d-bc52-4bc0296b7543.mov

https://user-images.githubusercontent.com/1657652/211082451-066e1b45-756d-4ef5-9a27-ff07b01cb18d.mov

**Comment by jrieken** [comment]
This issue lacks

* mentioning of the language and extension providing suggestions
* copy-paste friendly source code samples (we cannot copy and paste images or videos into VS Code to reproduce something)
* precise steps

**Comment by dmartin** [comment]
Turns out that at some point I must have set `"editor.suggest.insertMode": "replace"` rather than the default `"insert"`. Sorry for the false report.
