### ISSUE TITLE
createWebviewPanel with preserveFocus: true, takes focus anyway.

### ISSUE THREAD

**Issue by thpeder** [microsoft/vscode#170751]
Does this issue occur when all extensions are disabled?: Yes

Version: 1.75.0-insider (user setup)
Commit: 727d2d32aea02baf7d13fa38787e8ed64dd858d0
Date: 2023-01-06T05:21:40.528Z
Electron: 19.1.8
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.22621
Sandboxed: Yes

And

Version: 1.74.2 (system setup)
Commit: e8a3071ea4344d9d48ef8a4df2c097372b0c5161
Date: 2022-12-20T10:29:14.590Z
Electron: 19.1.8
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.22621
Sandboxed: No

Steps to Reproduce:

1. Create the extension
2. Invoke the command `Hello World`

**Expected:**
I expected that the property `preserveFocus` to mean that when I open the webview within the active ViewColoumn then it would open it as a new document, but not give it focus, ie. stay on the same document open.

**Actual:**
![PreserveFocus](https://user-images.githubusercontent.com/24276180/211142429-a7f9a6d3-941e-445e-ad33-ccc616499bde.gif)

![image](https://user-images.githubusercontent.com/24276180/211142396-1c925c15-671b-4ad2-a226-2e5c60646316.png)

```Javascript
import * as vscode from 'vscode';

export function activate(context: vscode.ExtensionContext) {
	console.log('Congratulations, your extension "First" is now active!');
	let disposable = vscode.commands.registerCommand('First.helloWorld', () => {
		vscode.window.showInformationMessage('Hello World from FirstApp!');
		if (!vscode.window.activeTextEditor) {
			return;
		}

		const panel = vscode.window.createWebviewPanel(
			'catCoding',
			'Cat Coding',
			{ preserveFocus: true, viewColumn: vscode.ViewColumn.Active },
			{ enableScripts: true }
		);
		panel.webview.html = getHtml();
	});

	context.subscriptions.push(disposable);
}

function getHtml() {
	return `
<!DOCTYPE html><html><head></head>
<body>
<h1> Hello </h1>

<script>
window.onfocus = function() {
	console.log('window focused!');
}

</script>
`
}

export function deactivate() { }
```

**Comment by mjbvz** [comment]
`preserveFocus` preserves the current focus when opening a new webview in a different editor group. The setting does not  affect which editor group the webview is opened in. You can use the `viewColumn` option for that 

This matches how `TextDocumentShowOptions.preserveFocus` works
