### ISSUE TITLE
Profiles: Not clear the tree pane is vertically resizable in the Show Contents View

### ISSUE THREAD

**Issue by chrisdias** [microsoft/vscode#170734]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 
```
Version: 1.75.0-insider
Commit: 727d2d32aea02baf7d13fa38787e8ed64dd858d0
Date: 2023-01-06T05:21:04.561Z
Electron: 19.1.8
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Darwin x64 20.6.0
Sandboxed: Yes
```
- OS Version: 
Mac BigSur 11.7.2

Steps to Reproduce:
- Use the Default Dark theme
- Create a new empty profile
- Open the `Show Profile Contents` view
- Since there is little/nothing in the Profile, the Export/Close buttons are located close to the top of the view

![image](https://user-images.githubusercontent.com/1487073/211118234-1dabf008-3d48-4072-ad9f-c8684de10f81.png)

- Install the Python extension (which installs a bunch of extensions as well)
- Open the `Show Profile Contents` view again
- Note that the visible area of the tree is the same size and the scrollbar isn't visible by default
- It looks like there are only 3 extensions installed (when there are really about 9)

![image](https://user-images.githubusercontent.com/1487073/211118272-274238b6-3d4b-4d78-aac6-d4261a260234.png)

- Now scroll the tree down with the mouse and you can see the rest of the extensions

![image](https://user-images.githubusercontent.com/1487073/211118412-e06916b2-5858-4190-8963-233991f4415d.png)

Ideally there is a visible sash between the area where the tree is and the area that contains the `Export` and `Close` buttons, which makes it possible to expand the area with the tree.

**Comment by isidorn** [comment]
Good catch. But in this case it seems like a bug is that the view has a wrong initial size. It takes the previous size, instead of the larger one that is needed.
But having a visible scrollbar would also help.

**Comment by sandy081** [comment]
Yes it's a bug to resize the initial size when contents are updated. IMO invisible scrollbar is a general issue across our UX.

**Comment by sandy081** [comment]
I can only reproduce it if I manually click on refresh button in the view after installing new extensions. Fixed this case.

**Comment by isidorn** [comment]
@sandy081 thanks!
@chrisdias let us know if you see it again.
