### ISSUE TITLE
Allows the Extensions and Run & Debug options to move to the secondary sidebar and bottom bar

### ISSUE THREAD

**Issue by L2750558108** [microsoft/vscode#170741]
Allows the "File", “Extensions” and “Run & Debug” options to move to the secondary sidebar and bottom bar, like this:
![image](https://user-images.githubusercontent.com/119792950/211127681-3eec7377-feee-4068-91f2-21f5fdd94396.png)

**Comment by roblourens** [comment]
https://github.com/microsoft/vscode/issues/143264
