### ISSUE TITLE
New Terminal Error

### ISSUE THREAD

**Issue by matthewdaclark** [microsoft/vscode#170724]
I have Remote Extension - WSL that I use with a shortcut:
"C:\Users\myusername\AppData\Local\Programs\Microsoft VS Code\Code.exe" --remote wsl+NameOfWSLDistro FullPathOfWorkSpaceFileWithinWSL

When I use this setup; new terminal bash works. However, when I use default terminal of bash it gives \usr\bin\bash invalid error

![image](https://user-images.githubusercontent.com/76482259/211093201-e81733d2-2f06-4365-b80a-23807d59ee5f.png)

**Comment by joyceerhl** [comment]
I can't reproduce this, creating a new bash terminal works as expected for me. Can you please provide more details / logs?

**Comment by matthew-da-clark** [comment]
So, here is the details:
Visual Studio Code 1.85.1
WSL (Remote VS Code Extension) v0.81.8
WSL O/S Ubuntu 20.04
I use a shortcut with this to open VS Code - WSL:
"C:\Users\username\AppData\Local\Programs\Microsoft VS Code\code.exe" --remote wsl+NameOfDistro /wsl/.vscode/wsl.code-workspace

code-workspace file used:
{
	"folders": [
		{
			"path": "/wsl"
		},
		{
			"path": "/git"
		}
	],
	"settings": {
		"workbench.colorTheme": "Default Dark+",
		"editor.renderWhitespace": "all",
		"workbench.startupEditor": "welcomePageInEmptyWorkbench",
		"task.allowAutomaticTasks": "on",
		"terminal.integrated.cwd": "${fileDirname}",
		"terminal.integrated.defaultProfile.linux": "Ubuntu bash",
		"terminal.integrated.profiles.linux": {
			"bash": {
				"path": "bash",
				"icon": "terminal-bash"
			},
			"Ubuntu bash": {
				"path": "bash",
				"icon": "terminal-ubuntu"
			},
			"sh": {
				"path": "/bin/sh"
			},
			"JavaScript Debug Terminal": null,
			"zsh": null,
			"fish": null,
			"tmux": null
		},
		"ansible.python.interpreterPath": "/bin/python3"
	}
}
The mains settings tried to change to help out is this section of it (had error before adding these):
		"terminal.integrated.cwd": "${fileDirname}",
		"terminal.integrated.defaultProfile.linux": "Ubuntu bash",
		"terminal.integrated.profiles.linux": {
			"bash": {
				"path": "bash",
				"icon": "terminal-bash"
			},
			"Ubuntu bash": {
				"path": "bash",
				"icon": "terminal-ubuntu"
			},
			"sh": {
				"path": "/bin/sh"
			},
			"JavaScript Debug Terminal": null,
			"zsh": null,
			"fish": null,
			"tmux": null
		},

In regards to logs only thing I could find when I try to start terminal using the + is in Server log showing this:
2023-12-14 07:31:15.467 [error] ptyHost was unable to resolve shell environment Unable to resolve your shell environment in a reasonable time. Please review your shell configuration and restart.

Again this only happens using the + icon for new terminal. If I use dropdown next to it and select it works.

**Comment by matthewdaclark** [comment]
See above comment; didnt realize was other account I created issue in.
