### ISSUE TITLE
"Step Into" not working when debugging simple node.js setup

### ISSUE THREAD

**Issue by KresimirJurkovic** [microsoft/vscode#170795]
Type: <b>Bug</b>

1. Create a starting point JS file (e.g. index.js)
2. Create any class bassed JS file and export it via module.exports
3. Require that class module in your index.js
4. Place a break point on the require line in index.js
5. Start the debug session and try to step into the require of that module -> it will not step into it.

VS Code version: Code 1.74.2 (e8a3071ea4344d9d48ef8a4df2c097372b0c5161, 2022-12-20T10:29:14.590Z)
OS version: Windows_NT x64 10.0.19045
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 1600 Six-Core Processor             (12 x 3200)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.95GB (6.96GB free)|
|Process Argv|--crash-reporter-id 8634325e-d929-4f06-826c-44bbe959bd5b|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (36)</summary>

Extension|Author (truncated)|Version
---|---|---
node-essentials|afr|1.1.0
vscode-eclipse-keybindings|alp|0.16.1
jsoncrack-vscode|Ayk|1.0.8
vscode-icontheme-nomo-dark|be5|1.3.6
node-snippets|chr|1.3.3
path-intellisense|chr|2.8.4
vscode-eslint|dba|2.2.6
es7-react-js-snippets|dsz|4.4.3
gitlens|eam|13.2.0
EditorConfig|Edi|0.16.4
prettier-vscode|esb|9.10.3
code-runner|for|0.11.8
vscode-pull-request-github|Git|0.56.0
search-node-modules|jas|1.3.0
dotenv|mik|1.0.1
vscode-kubernetes-tools|ms-|1.3.11
vscode-typescript-tslint-plugin|ms-|1.3.4
vsliveshare|ms-|1.0.5797
debugger-for-chrome|msj|4.13.0
vscode-react-native|msj|1.10.0
vscode-jest|Ort|5.1.0
material-icon-theme|PKi|4.23.1
fabric8-analytics|red|0.3.6
java|red|1.13.0
vscode-yaml|red|1.10.1
LiveServer|rit|5.7.9
intellicode-api-usage-examples|Vis|0.2.6
vscodeintellicode|Vis|1.2.30
vscode-java-debug|vsc|0.47.0
vscode-java-dependency|vsc|0.21.1
vscode-java-pack|vsc|0.25.7
vscode-java-test|vsc|0.37.1
vscode-maven|vsc|0.40.2
quokka-vscode|Wal|1.0.520
vscode-import-cost|wix|3.3.0
JavaScriptSnippets|xab|1.8.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vscaat:30438848
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
azure-dev_surveyone:30548225
vscccc:30610679
pyindex848:30577860
nodejswelcome1cf:30587006
3biah626:30602489
iaj6b796:30613358
89544117:30613380
fim-prod:30623723

```

</details>

**Comment by connor4312** [comment]
This is as designed, since Node internal code is added to skipFiles by default. If you want to debug these internals, you can add `skipFiles: []` to your launch.json so that nothing gets skipped.
