### ISSUE TITLE
Profiles: Export when Show Profile Contents view is open doesn't bring up quick pick

### ISSUE THREAD

**Issue by chrisdias** [microsoft/vscode#170736]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 
```
Version: 1.75.0-insider
Commit: 727d2d32aea02baf7d13fa38787e8ed64dd858d0
Date: 2023-01-06T05:21:04.561Z
Electron: 19.1.8
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Darwin x64 20.6.0
Sandboxed: Yes
```
- OS Version: 
MacOS Big Sur latest

Steps to Reproduce:
- Create a new profile
- Click on the Profile Activity Bar icon, then choose `Export Profile...`

Result: the quick pick comes up...

![image](https://user-images.githubusercontent.com/1487073/211119091-e2f76764-1406-4bf2-8962-2be04d9bed5e.png)

- Now click on the `Show Profile Contents` menu item to bring up the view
- Click on the `Export Profile...` menu item again

Result: focus just moves to the `Show Profile Contents` pane

![image](https://user-images.githubusercontent.com/1487073/211119215-5dce71a0-bb58-4a5f-9622-f64998ed4b79.png)

Expectation: Show the Quick Pick so the menu works the same regardless of whether or not the content view is open

**Comment by isidorn** [comment]
I was also hit by this - that by clicking on "Export Profile..." it looks like it has no effect, when it fact it just passed the focus.
@sandy081 we could always show quick pick as Chris suggests?

**Comment by sandy081** [comment]
What about the contents view when you click on `Export Profile...` again? Does this has to be closed or remain like this? May I understand what is confusing in navigating to the contents view when you click on export profile button?

**Comment by chrisdias** [comment]
I think you can leave the view open, but I would open the Quick Pick right away, not force the user to click on the Export button (again).

**Comment by sandy081** [comment]
Another idea (that was also mentioned in the UX call) is how about always open the view and ditch quick pick? This was initial flow actually.

**Comment by isidorn** [comment]
I think that flow might work. My biggest concern is that users might not notice that the focus moved to the view (especially if the view is already open). Long term - maybe the view becomes a custom editor?

fyi @daviddossett @stevencl

**Comment by sandy081** [comment]
Quick pick is removed and by default we show the contents view now.
