### ISSUE TITLE
Preview cache html

### ISSUE THREAD

**Issue by albu77** [Microsoft/vscode#17074]
- VSCode Version:1.7.2
- OS Version: Windows7

Steps to Reproduce:

1. Write a html file with bootstrap
<div class="panel-heading">Panel Heading

<a id="chsaison" title="Suppression pour changement de saison" class="btn btn-lg btn-primary">Suppression des pièces jointes <span class=" 	glyphicon glyphicon-trash"></span></a>
2. Preview with shortcut Ctrl+Shift+V 
3. Display correctly
4. Modify the text of the link button
5. Should display the new text on a new preview command but stay the same
6. Preview another file
7. Come back to the previous one and the change shows..

**Comment by kieferrm** [comment]
@albu77 What command palette command do you use.  Can you pls go to `Command Palette > Help:Report Issue` can copy the list of extensions from the pre-populated issue into this one? Thanks.

**Comment by albu77** [comment]
- VSCode Version: Code 1.7.2 (7ba55c5860b152d999dda59393ca3ebeb1b5c85f, 2016-11-21T22:06:37.428Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions:

|Extension|Author|Version|
|---|---|---|
|project-manager|alefragnani|0.7.1|
|phpmd|linyang95|1.1.1|
|csharp|ms-vscode|1.2.2|
|debugger-for-chrome|msjsdiag|2.1.1|

---
[Microsoft/vscode] Preview cache html (#17074)

Steps to Reproduce:


1.Ok, Sorry, I was using Ctrl+Shift+V which Toggle MarkDown Preview and wasUsing it againt a Html File which in some case give a close result and that's why I thought it was a bug.
I understabnd that for Html I need an extension
2.Regards

Alain

**Comment by kieferrm** [comment]
@albu77 Thanks!
