### ISSUE TITLE
HTML language server throws exception when initialization options are empty

### ISSUE THREAD

**Issue by mniewrzal** [Microsoft/vscode#17071]
- VSCode Version:
Version 1.7.2
Commit 7ba55c5860b152d999dda59393ca3ebeb1b5c85f
Date 2016-11-21T22:14:18.217Z
Shell 1.3.8
Renderer 52.0.2743.82
Node 6.5.0
- OS Version: Fedora 25

Steps to Reproduce:

1. Use this request to initialize HTML language server
```json
{
  "id": "1",
  "method": "initialize",
  "params": {
    "rootPath": "/home/wywrzal/development/ZEND/Che/runtime-IDE/Test",
    "capabilities": {},
    "clientName": "Eclipse Platform"
  },
  "jsonrpc": "2.0"
}
```
2. As an response error will be returned:
```json
{
  "id": "1",
  "error": {
    "code": -32603,
    "message": "Request initialize failed with message: Cannot read property \u0027embeddedLanguages\u0027 of undefined"
  },
  "jsonrpc": "2.0"
}
```
Isn't a big problem but it would be nice to handle this simple case without exception.

**Comment by aeschli** [comment]
Fixed in 1.8.

As a workaround for 1.7, pass in an initializationOptions.embeddedLanguages = {} to the service
