### ISSUE TITLE
Insert final new line doesn't work with format JSON on save

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#17078]
* configure format on save
* configure insert new line
* save a JSON file with a trailing newline
* 🐛 trailing newline is gone, I guess that's because the css formatter removes it and because the insert final new lines come before extensions. I'd expect insert final new to be consistent

**Comment by bpasero** [comment]
@jrieken which extension is that for formatting?

**Comment by jrieken** [comment]
Sorry, not CSS but JSON and that's the same formatter you use.

**Comment by jrieken** [comment]
> I can look into changing it but users might equally expect a formatter to win over the newline setting. Hard to say what is right or wrong in this case.

I'd go for consistency here

**Comment by bpasero** [comment]
@jrieken I moved it to be after `FormatOnSaveParticipant` so this particular issue is fixed. The `ExtHostSaveParticipant` is still last in the list though so might win over the others after all if there is another formatter running. Should it move to be the last?

**Comment by jrieken** [comment]
I think it's ok like that - formatter shouldn't run via the `willSave`-hook but via the *real* API
