### ISSUE TITLE
"Find all references" Not working

### ISSUE THREAD

**Issue by dfroze** [Microsoft/vscode#17070]
Version 1.7.2
Commit 7ba55c5860b152d999dda59393ca3ebeb1b5c85f
Date 2016-11-21T22:14:18.217Z
Shell 1.3.8
Renderer 52.0.2743.82
Node 6.5.0

Since the first time I installed the vscode till now (so it isn't only just recent), this feature never worked for me. It always showed an empty list. I thought that it was a cpptool problem but they never responded.
Can anyone help me with it? Do I need to configure something !?

Thank you.

**Comment by alexandrudima** [comment]
@dfroze What file types are you running find all references on?

**Comment by dfroze** [comment]
*.c, *.h are the main ones with empty results.
On *.py it shows me only the ones in the same file. And for *.pl there is no such option.

**Comment by alexandrudima** [comment]
Indeed, find all references is or is not implemented for *.c or *.h files by the extension, so moving this issue to Microsoft/vscode-cpptools#404
