### ISSUE TITLE
VS Code validates Handlebars helpers as Javascript if helper is used in an event attribute

### ISSUE THREAD

**Issue by t-sauer** [Microsoft/vscode#17077]
- VSCode Version: 1.8.0-insider 40243d1e01f426f54670f3dbaa6b77d18469310d
- OS Version: macOS 10.11.6

Steps to Reproduce:

1. Create a new Handlebars file
2. Add the following content:
```hbs
<div onclick={{if foo (action "bar")}}>
</div>
```

VS Code displays a false error after the `if` (`'(' expected`). 
<img width="321" alt="screen shot 2016-12-12 at 14 56 38" src="https://cloud.githubusercontent.com/assets/5306662/21101954/fef8d4aa-c07b-11e6-834f-ab90c4ed2fa5.png">

Since I get Javascript intellisense in there, I assume it tries to validate the text as Javascript (in which case the expected bracket would make sense).

**Comment by mjbvz** [comment]
@aeschli Can you please take a look at this. I think that this is coming from the HTML extension

**Comment by aeschli** [comment]
fixed by 9b47ab533907c71357d835b749674760dec3d9fb.

The fix turns of javascript validation for handlebars
