### ISSUE TITLE
settings sync w/ microsoft account fails on github.dev

### ISSUE THREAD

**Issue by diminutivesloop** [microsoft/vscode#170717]
I am currently using my personal microsoft.com account for settings sync. I do this because my work requires dedicated GitHub accounts, but I would still like to keep my VSCode settings in sync between my work and personal computer. However when I try to enable settings sync for the web version of VSCode at github.dev I get the following error:
```
Error while turning on Settings Sync. {"error":"invalid_grant","error_description":"AADSTS500202: User account '{EmailHidden}' from external identity provider 'live.com' is not supported for API version '2.0'. Microsoft account pass-thru users and guests are not supported by the tenant-independent endpoint.\r\nTrace ID: 27a68633-b94f-448f-bc5b-b5c3b9af9c01\r\nCorrelation ID: ba847e22-baa5-4f98-95e3-fa74d7973219\r\nTimestamp: 2023-01-06 19:17:38Z","error_codes":[500202],"timestamp":"2023-01-06 19:17:38Z","trace_id":"27a68633-b94f-448f-bc5b-b5c3b9af9c01","correlation_id":"ba847e22-baa5-4f98-95e3-fa74d7973219"}
```
I can duplicate this issue in both Chrome and Firefox. 

Version: 1.74.2
Commit: e8a3071ea4344d9d48ef8a4df2c097372b0c5161
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36
Embedder: github.dev

**Comment by sandy081** [comment]
Assigning to @TylerLeonhardt for auth related and @Tyriar for log into settings sync server

**Comment by TylerLeonhardt** [comment]
@diminutivesloop does enabling setting sync work for you in https://vscode.dev ? I'm curious if this is scoped just to github.dev.

**Comment by diminutivesloop** [comment]
@TylerLeonhardt So I just tried reproducing the issue in [vscode.dev](https://vscode.dev). It wasn't already signed-in to GitHub and when I tried signing-in to my Microsoft account for settings sync and then signed-in to GitHub it worked without issue. And just to confirm I tried signing-in to [github.dev](https://github.dev) in a private window and I still encounter the original issue as reported.

**Comment by TylerLeonhardt** [comment]
Ok @jkeech, I remember we talked about "Microsoft auth in github.dev" ages ago... and at the time, it was considered out of scope. Did that change at all? @diminutivesloop would like to use Microsoft auth for settings sync, to be consistent everywhere, but they can't with github.dev.

**Comment by jkeech** [comment]
> Ok @jkeech, I remember we talked about "Microsoft auth in github.dev" ages ago... and at the time, it was considered out of scope. Did that change at all? @diminutivesloop would like to use Microsoft auth for settings sync, to be consistent everywhere, but they can't with github.dev.

That's correct. github.dev only supports the GitHub account currently for Settings Sync. github.dev is also automatically authenticated with GitHub and the account that is signed into github.dev is the one that is used for Settings Sync.

**Comment by TylerLeonhardt** [comment]
@jkeech Thanks for confirming. I'll go ahead and close this issue since there's nothing on the VS Code side to do... but maybe you could point @diminutivesloop in the right direction to ask for this support?

**Comment by jkeech** [comment]
@diminutivesloop, feel free to open a discussion on https://github.com/community/community/discussions asking for this support.
