### ISSUE TITLE
vscode terminal tabs Chinese path garbled

### ISSUE THREAD

**Issue by vickllny** [microsoft/vscode#170793]
Type: <b>Bug</b>

When I use the zsh terminal in vscode, and the current directory name contains Chinese characters, the tabs Chinese path in the vscode terminal is garbled

VS Code version: Code 1.74.2 (e8a3071ea4344d9d48ef8a4df2c097372b0c5161, 2022-12-20T10:26:09.430Z)
OS version: Darwin x64 20.6.0
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E3-1230 v3 @ 3.30GHz (8 x 3300)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (3.05GB free)|
|Process Argv|Linux三剑客 --crash-reporter-id f997d75e-d0bf-4882-a41f-150202e05561|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (36)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|2.2.6
githistory|don|0.6.19
vscode-html-css|ecm|1.13.1
auto-close-tag|for|0.5.14
auto-rename-tag|for|0.1.10
nsis|idl|3.52.0
intellij-idea-keybindings|k--|1.5.5
isort|ms-|2022.8.0
python|ms-|2022.20.1
vscode-pylance|ms-|2023.1.10
jupyter|ms-|2022.11.1003412109
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.12
vscode-jupyter-cell-tags|ms-|0.1.6
vscode-jupyter-slideshow|ms-|0.1.5
vetur|oct|0.36.1
vscode-boot-dev-pack|Piv|0.2.0
vscode-spring-boot|Piv|1.43.0
java|red|1.13.0
vscode-xml|red|0.23.0
LiveServer|rit|5.7.9
snippets-ranger|rob|0.22.1
rust-analyzer|rus|0.3.1348
vscode-lldb|vad|1.8.1
intellicode-api-usage-examples|Vis|0.2.6
vscodeintellicode|Vis|1.2.30
vscode-java-debug|vsc|0.47.0
vscode-java-dependency|vsc|0.21.1
vscode-java-pack|vsc|0.25.7
vscode-java-test|vsc|0.37.1
vscode-lombok|vsc|1.1.0
vscode-maven|vsc|0.40.2
vscode-spring-boot-dashboard|vsc|0.9.0
vscode-spring-initializr|vsc|0.11.1
JavaScriptSnippets|xab|1.8.0
vscode-java-ibatisx|yan|2022.12.16240001

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
azure-dev_surveyone:30548225
pyindex848cf:30577861
nodejswelcome1cf:30587006
3biah626:30602489
iaj6b796:30613358
89544117:30613380
fim-prod:30623723

```

</details>

**Comment by vickllny** [comment]
the screenshot  as follows
![image](https://user-images.githubusercontent.com/31479141/211186909-ecd3c60a-3254-42c3-b184-2ca7952892e5.png)

**Comment by meganrogge** [comment]
I believe this is already fixed, can you see if you can reproduce in the [Insiders build](https://code.visualstudio.com/insiders)?
/label info-needed

**Comment by vickllny** [comment]
Ok I'll try it out as soon as I get time and give you the results

**Comment by vickllny** [comment]
I downloaded the latest vscode-insiders, the problem of garbled characters has been fixed, but the terminal tabs on the right only show zsh, is it correct?

![image](https://user-images.githubusercontent.com/31479141/211595548-c336278f-1554-4feb-99ac-64570917ff97.png)


vscode-insiders version info as follow

Version: 1.75.0-insider (Universal)
Commit: e7b5449579249db344d473370d56a5df9446c826
Date: 2023-01-10T05:21:34.436Z
Electron: 19.1.9
Chromium: 102.0.5005.194
Node.js: 16.14.2
V8: 10.2.154.23-electron.0
OS: Darwin x64 20.6.0
Sandboxed: Yes

**Comment by meganrogge** [comment]
what are you expecting them to show if not zsh?

**Comment by dididudu998** [comment]
that is the problem after an update of vscode. if should be look like this:
![截屏2023-01-12 08 03 27](https://user-images.githubusercontent.com/9048271/211944273-a19928a8-2146-46a6-af09-50b4218f7919.jpg)

but also need the {cwd} by default. the {cwd} here is not correctly. 
that is not a shell configuration issue, mostly the vscode issue.

**Comment by dididudu998** [comment]
> that is the problem after an update of vscode. if should be look like this:
> ![截屏2023-01-12 08 03 27](https://user-images.githubusercontent.com/9048271/211944273-a19928a8-2146-46a6-af09-50b4218f7919.jpg)
> 
> but also need the {cwd} by default. the {cwd} here is not correctly. 
> that is not a shell configuration issue, mostly the vscode issue.
> 

Update:

upgrad to latest version of vscode, it fixed.
