### ISSUE TITLE
Extensions won't load in Linux

### ISSUE THREAD

**Issue by Nightenom** [microsoft/vscode#170755]
Type: <b>Bug</b>

Steps to Reproduce:

1. update from 1.73.1
2. see no extensions found

Might be dupe of #169808 or #170337, but I'm running on linux

[Logs captured for both versions](https://gist.github.com/Nightenom/dcf94f69541c234ea76ee01a3ac5ff38) using `shared trace` (tho in older version the setting looks different than in newer one): , notice different `Scanned user extensions` - 35 vs 0

VS Code version: Code 1.74.2 (e8a3071ea4344d9d48ef8a4df2c097372b0c5161, 2022-12-20T10:27:19.253Z)
OS version: Linux x64 5.10.0-20-amd64
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 9 7900X 12-Core Processor (24 x 2999)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|0, 0, 0|
|Memory (System)|30.58GB (27.20GB free)|
|Process Argv|--crash-reporter-id e4aa2530-b0be-4069-8355-e5851d07ffa0|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|undefined|
|XDG_CURRENT_DESKTOP|KDE|
|XDG_SESSION_DESKTOP|undefined|
|XDG_SESSION_TYPE|tty|
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vscaat:30438848
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
azure-dev_surveyone:30548225
pyindex848cf:30577861
nodejswelcome1cf:30587006
282f8724:30602487
iaj6b796:30613358
89544117:30613380
fim-prod:30623723
vscsbc:30628655

```

</details>

**Comment by Nightenom** [comment]
`/media/schimpet/progs/apps/linux64/vscode/data/extensions/extensions.json` is full and looks correct, however, since I'm often switching Windows and Linux OSes, all the extension paths are in windows format and pointing to valid windows locations (when on Windows, obviously can't reach any of them on Linux)

**Comment by sandy081** [comment]
> however, since I'm often switching Windows and Linux OSes, all the extension paths are in windows format and pointing to valid windows locations (when on Windows, obviously can't reach any of them on Linux)

Can you please explain how are you switching the platforms? 
What are the locations of the extensions in the extensions.json file?

**Comment by Nightenom** [comment]
> Can you please explain how are you switching the platforms?

I have two folders for binaries, one for Windows + one for Linux, which are updated manually from respective zip/tgz downloads. Then I have one data folder, which is linked to both binary folders as `data` directory (for Windows using junction link `mklink /j`, for Linux iirc using normal soft link). Start of vscode is then done by clicking `code.exe` (and modifying shell environments for some other software to work correctly).

> What are the locations of the extensions in the extensions.json file?

The answer is in the paragraph above - for both instances I use the completely same data folder (that is linked like said above). This setup is working since I use vscode (4 or 5 years).

**Comment by sandy081** [comment]
Thanks for the explanation. I see that this bug is happening because of the absolute paths stored in extensions.json file. We fixed it in the current release here - https://github.com/microsoft/vscode/issues/169006 This shall start working from the next release that will be available in 2 weeks. Meanwhile you can always use our insiders build that has the fix - https://code.visualstudio.com/insiders/

Apologies for the bug.
