### ISSUE TITLE
Services: Services in Account Activity Bar menu are inconsistent

### ISSUE THREAD

**Issue by chrisdias** [microsoft/vscode#170737]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 
```
Version: 1.75.0-insider
Commit: 727d2d32aea02baf7d13fa38787e8ed64dd858d0
Date: 2023-01-06T05:21:04.561Z
Electron: 19.1.8
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Darwin x64 20.6.0
Sandboxed: Yes
```
- OS Version: 
macOs Big Sur

Steps to Reproduce:
- Turn on Setting Sync, you are presented with a set of settings to synchronize and a button to `Sign in & Turn On`

![image](https://user-images.githubusercontent.com/1487073/211120264-ce0395cc-3117-473d-9fbe-fe65fdaf3a87.png)

- Turn on Cloud Changes or Remote Tunnel Access, you are given the option to sign in
![image](https://user-images.githubusercontent.com/1487073/211120284-ec9f6334-2cdd-447a-ab2f-cad39c388862.png)
![image](https://user-images.githubusercontent.com/1487073/211120298-b6cdcfae-d97c-4ceb-806c-3cb13906b4d9.png)

I realize that Remote Access only supports GH Sign In right now, which is why it is different from Cloud Changes, but Settings Sync has a different model for turning it on.

Also, once on, the services have different state.

- turn on Settings Sync, Cloud Changes, Remote - Tunnels access
- look at Account menu:

![image](https://user-images.githubusercontent.com/1487073/211119822-07fe474e-8a5c-47c9-a029-d22879edd19f.png)

Result: Settings Sync and Remote Tunnel Access both say they are On, but I have the option to turn off Cloud Changes (which indicates it is on).  We should be consistent with everything being on or having the ability to turn everything off.

**Comment by sandy081** [comment]
@TylerLeonhardt Is not this related to what we are discussing recently?

**Comment by keeganwitt** [comment]
I noticed "Turn on cloud changes" in the settings, but have no idea what it does. The [doc page](https://code.visualstudio.com/docs/editor/settings-sync) has no instances of "cloud changes" or "Edit sessions" (which is apparently what it labeled before).
