### ISSUE TITLE
Some JavaScript code does not work in 'Embedded Preview'

### ISSUE THREAD

**Issue by deepindersinghbti** [microsoft/vscode#170883]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.74.2
- OS Version: Windows NT 10.0, Version 22H2, OS Build 19045.2364

Steps to Reproduce:

1. Create two files: index.html and script.js
2. Connect them by using <script src="script.js"></script>
3. Create a button in the HTML file using the <button> tag
4. Create a function **showAlert()** in the JS file to show an alert ("Hello World.")
5. Connect the HTML button to the JS function 
6. Start the server in embedded preview
7. Required alert "Hello World" does not show on clicking the button, but it does when External browser preview is started from Menu > Open in Browser.

**Comment by mjbvz** [comment]
Webpages in VS Code are not allowed to show alert dialogs or any UI elements outside of the page. If you need to user alerts, you have to use an external browser instead
