### ISSUE TITLE
Perf: `registerTerminalActions` is taking quite some time

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#170827]
On startup I notice how many terminal actions are registered:

![register-terminal-actions](https://user-images.githubusercontent.com/900690/211262721-89dd4c35-a92d-443b-9eb4-cdcdcbec6b76.png)

I am not entirely sure there is something to do about it, but thought I would file it anyway. Not surprisingly given the amount of calls all `registerAction2` contributes quite significantly to the startup:

![image](https://user-images.githubusercontent.com/900690/211262855-00cd8b39-4139-4212-a422-f6f48fcf9a22.png)

But maybe the terminal actions can only be registered after editor has restored?

//cc @jrieken 

The following profile:
* was taken on Windows
* with a non-minified / non-mangled build to aid reading
* has the `ellapsed` event at `6755ms`

[prof-QIBV4was.main.zip](https://github.com/microsoft/vscode/files/10371380/prof-QIBV4was.main.zip)

**Comment by jrieken** [comment]
This is rarely a problem with the actions but with listeners for events that get fired when registering something

**Comment by Tyriar** [comment]
I see a lot of time is spent in creating/normalizing context key expressions. Sharing the keys will probably speed this up
