### ISSUE TITLE
Sticky scroll: Missing border between two editors

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#170851]
![image](https://user-images.githubusercontent.com/22350/211318657-18dacc21-b935-4590-99b2-16cfeb95aee8.png)

**Comment by jrieken** [comment]
regression from https://github.com/microsoft/vscode/issues/165698

**Comment by joaomoreno** [comment]
That's odd. The sash is transparent: it shouldn't render at all, unless you hover it. Are you sure this is the sash?

**Comment by jrieken** [comment]
Might actually not be the sash but [this](https://github.com/microsoft/vscode/blob/a3192fbad7bb02871ae8b6d3703c8bfc5433e661/src/vs/base/browser/ui/splitview/splitview.css#L52-L60) from the split view

**Comment by jrieken** [comment]
Yeah, settings its `z-index` actually fixes this issue

**Comment by jrieken** [comment]
https://github.com/microsoft/vscode/pull/172020
