### ISSUE TITLE
Untitled restores even when files.hotExit is turned off in some cases

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#17080]
Steps to Reproduce:

1. configure files.hotExit: false 
2. create untitled file with some content and quit, discard the file quickly enough before our 1s backup model tracker kicks in
3. restart

=> the untitled file restores with its backup

**Comment by bpasero** [comment]
@Tyriar moving to you, it looks like on shutdown we are not properly stopping the backup editor tracker to produce backups after 1s, so if I manage to quit quickly enough after making changes to an untitled file, I see the backup directory show backups for the untitled file (and probably others too) even though I explicitly said to discard the untitled file. Upon restart it will restore from there.

**Comment by Tyriar** [comment]
I don't think this is an issue anymore, there is a hot exit check in `TextFileService` shutdown which either shows prompt or goes ahead with the hot exit. I can only repro th bad hot exit when closing so fast after changing the setting that `TextFileService.onConfigurationChange` doesn't have a change to run.

**Comment by bpasero** [comment]
Reproduces quite easily:

![panel-red](https://cloud.githubusercontent.com/assets/900690/22193175/ea49c44a-e139-11e6-8d79-ad3c8b86f532.gif)

**Comment by Tyriar** [comment]
Ah I misunderstood. Thanks for the gif, should be able to fix tomorrow.
