### ISSUE TITLE
Extension's context.storagePath randomly returns some undefined value

### ISSUE THREAD

**Issue by fbricon** [Microsoft/vscode#17089]
- VSCode Version: 1.8.0-insider 40243d1e01f426f54670f3dbaa6b77d18469310d 2016-12-09T12:04:24.015Z
- OS Version: macOS 10.12

Steps to Reproduce:

Frequently, running[ vscode-java](https://github.com/redhat-developer/vscode-java) from source on a folder containing a java project, the Java Language Server fails to start because the [workspace path that is sent](https://github.com/redhat-developer/vscode-java/blob/master/src/extension.ts#L80) is `/undefined/redhat.java`.

On the next start, the path would be something like `/Users/username/Library/Application Support/Code - Insiders/User/workspaceStorage/644625e5a6a01f8af867112db58dc2e6/redhat.java`

I haven't found a pattern to reproduce the issue reliably, but it's pretty frequent.

**Comment by jrieken** [comment]
Pretty confident this happens when opening just a file, not a folder. Based on that the following steps to reproduce:

* have extension code as shown below, make it active eagerly
* open a folder => it prints a path like `/SOME/DIR/workspaceStorage/HASH/extension-id`
* open a file => 🐛 it prints a path like `undefined/extension-id`, it should just print `undefined`

```ts
export function activate(context: vscode.ExtensionContext) {
    console.log(context.storagePath);
}
```

**Comment by jrieken** [comment]
@ramya-rao-a fyi - this requires a rebuilt of insiders.

**Comment by fbricon** [comment]
So I think this narrows it down to:

1 - open a folder containing a java project, storagepath is set
2 - while vscode is opened, open a separate, standalone file from another folder
3 - close and reopen vscode
4 - both the standalone file and the project folder are reopened, but the standalone file takes precedence somehow and an undefined storagePath is returned.

**Comment by fbricon** [comment]
So what I'm expecting is if you're opening multiple standalone files and a folder, the storagepath of the folder should be returned.

I don't think you can have 2 folders opened at the same time

**Comment by fbricon** [comment]
If ^^ is not possible directly from vscode/storagePath then, is there a way, from an extension perspective, to determine what files/folders are opened during activation, so we can compute the appropriate workspace ourself?

**Comment by jrieken** [comment]
Each VS Code window is independent and has its own 'scope'. Wrt the `storagePath` the rules are that when a folder has been opened it is defined, and in case of a file it is `undefined`
