### ISSUE TITLE
Terminal scroll lag

### ISSUE THREAD

**Issue by ygoe** [microsoft/vscode#170873]
Type: <b>Bug</b>

When scrolling the integrated terminal with the mouse wheel, the view changes only after a considerable time lag or delay. This doesn't happen all the time, but sometimes when the terminal panel contains some 200 lines. It takes longer as the terminal panel height increases. Must be around 0.3 s with the default small height and up to 0.6 s at full screen height (1200 px). The terminal cannot be scrolled interactively, it's always a wait after each wheel turn.

VS Code version: Code 1.74.2 (e8a3071ea4344d9d48ef8a4df2c097372b0c5161, 2022-12-20T10:29:14.590Z)
OS version: Windows_NT x64 10.0.19045
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3770 CPU @ 3.40GHz (8 x 3400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.71GB (4.99GB free)|
|Process Argv|C:\\Source\\Komprenu\\Kappa-Indect\\core-daemon-cs --crash-reporter-id 1b00a758-578c-4b77-a258-fe145c18e004|
|Screen Reader|no|
|VM|33%|
</details><details><summary>Extensions (24)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-solution-explorer|fer|0.7.5
vscode-todo-highlight|jgc|2.0.4
ecdc|mit|1.8.0
vscode-language-pack-de|MS-|1.74.12140926
csharp|ms-|1.25.2
vscode-dotnet-runtime|ms-|1.6.0
isort|ms-|2022.8.0
python|ms-|2022.20.1
vscode-pylance|ms-|2023.1.10
jupyter|ms-|2022.11.1003412109
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.12
vscode-jupyter-cell-tags|ms-|0.1.6
vscode-jupyter-slideshow|ms-|0.1.5
remote-ssh|ms-|0.94.0
remote-ssh-edit|ms-|0.84.0
cpptools|ms-|1.13.9
remote-explorer|ms-|0.0.3
vscode-nuget-gallery|pat|0.0.24
platformio-ide|pla|2.5.5
better-pageup-pagedown|rus|0.0.1
jinjahtml|sam|0.19.0
trailing-spaces|sha|0.4.1
cursorCharCode|zei|0.2.2

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscorecescf:30445987
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
azure-dev_surveyone:30548225
pyindex848:30577860
nodejswelcome1cf:30587006
2e4cg342:30602488
3d0df643:30613357
89544117:30613380
fim-prod:30623723

```

</details>

**Comment by ygoe** [comment]
I've just seen my settings and would like to add these in case they're relevant:

```
    "terminal.integrated.cursorBlinking": true,
    "terminal.integrated.gpuAcceleration": "off",
```

I don't know anymore why I've set the second one. There was probably some other bug that could be resolved with it in the past.

**Comment by meganrogge** [comment]
>  "terminal.integrated.gpuAcceleration": "off",

GpuAcceleration helps with rendering performance, so it's possible that removing that line could fix this for you

**Comment by DrChat** [comment]
Also chiming in here to say that I'm seeing this when I open the terminal in a RDP session and then move back to the console session.
If I turn off GPU acceleration (including if I toggle it off and on) then this stops happening.

I also noticed that the scrollbar itself updates with no delay, but it takes 200-300ms for the text in the terminal to update.

**Comment by Tyriar** [comment]
Rendering improved greatly a few months ago when GPU acceleration if off. If you still see a problem you can capture a devtools performance trace (Help > Toggle Developer Tools) which will give us some info about it
