### ISSUE TITLE
Can not preview or open images on the remote machine.

### ISSUE THREAD

**Issue by lengmo1996** [microsoft/vscode#170821]
Does this issue occur when all extensions are disabled?: Yes/No
No. We will not connect to the remote machine if we disable all extensions.

- VS Code Version:  1.74.2 (user setup)
- Local OS Version: Windows_NT x64 10.0.19045
- Remote OS Version: Ubuntu 20.04.5 LTS
- Electron: 19.1.8
- Chromium: 102.0.5005.167
- Node.js: 16.14.2
- V8: 10.2.154.15-electron.0

- Sandbox: No

Description: When I connected to a remote machine and double click a image in the vs code file explorer, there is nothing happened like fig. 1.
![fig1](https://user-images.githubusercontent.com/40485465/211245795-71960982-e739-4cf0-b4de-b7b8d066b774.png)

However, if I open a folder in my local machine at the same time and then double click a image in this local folder, the images in remote machine will have a preview. Another observed fact is after twice displayed remote images, there is no preview again. I must reclick a local image then get the remote image preview.

Steps to Reproduce:
I do not know how to reproduce this problem. I have tried to reinstall local and remote vs code, but it does not work.

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled) (besides the remote extensions)?

**Comment by lengmo1996** [comment]
> Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled) (besides the remote extensions)?

Yes, if disabled all extensions except remote, it will reproduce

**Comment by lengmo1996** [comment]
In order to confirm the reason, I have tried to downgrade the vs code version from 1.74.2 to 1.66.2 and deleted all the personal files or cache files to keep a clear environment. 
After downgrading the vs code, this problem **disappears** and I can preview remote images successfully. Then, I tried to rule out the reasons for personal settings by syncing my settings one by one. This problem **did not** occur until all settings were synced. However, once I upgrade the vs code version, the problem **reproduces** immediately. 

For excluding devices influencing, I have tried to change local and remote machines individually or both. The remote image preview works well in lower versions but fails in high versions. I think the reasons for this problem are hidden in the version upgrade, but I am not sure which version upgrade caused this problem.

Utile now, I have no conditions to further locate the reasons for this problem. So I hope my additional information is helpful to solve this problem. Thanks.

**Comment by lengmo1996** [comment]
> In order to confirm the reason, I have tried to downgrade the vs code version from 1.74.2 to 1.66.2 and deleted all the personal files or cache files to keep a clear environment. After downgrading the vs code, this problem **disappears** and I can preview remote images successfully. Then, I tried to rule out the reasons for personal settings by syncing my settings one by one. This problem **did not** occur until all settings were synced. However, once I upgrade the vs code version, the problem **reproduces** immediately.
> 
> For excluding devices influencing, I have tried to change local and remote machines individually or both. The remote image preview works well in lower versions but fails in high versions. I think the reasons for this problem are hidden in the version upgrade, but I am not sure which version upgrade caused this problem.
> 
> Utile now, I have no conditions to further locate the reasons for this problem. So I hope my additional information is helpful to solve this problem. Thanks.



> To confirm the reason, I have tried to downgrade the vs code version from 1.74.2 to 1.66.2 and deleted all personal or cache files to keep a clean environment. After downgrading the vs code, this problem **disappears** and I can preview remote images successfully. Then, I tried to rule out the reasons for personal settings by syncing my settings one by one. This problem **did not** occur until all settings were synced. However, once I upgrade the vs code version, the problem **reproduces** immediately.
> 
> To exclude devices influencing, I have tried to change local and remote machines individually or both. The remote image preview works well in lower versions but fails in high versions. I think the reasons for this problem are hidden in the version upgrade, but I am not sure which version upgrade caused this problem.
> 
> Utile now, I have no conditions to locate the reasons for this problem further. I hope my additional information is helpful in solvinghis problem. Thanks.

When I update my vs code version from 1.73.1 to 1.74.*, this problem will reproduce.

**Comment by lengmo1996** [comment]
@mjbvz I am adding more information. Is it helpful to this issue?

**Comment by mjbvz** [comment]
Can you share your ssh configuration (pre remove any information that should not be public)

A few users have reported issues with ssh configs that contain non-english characters. I'm curious if that could be the root cause of this issue too

**Comment by lengmo1996** [comment]
Thanks for your reply. I have no time to see if this problem is fixed in vs code version 1.74.*. However, when I update vs code from 1.73.1 to the new least version, 1.76.2, this problem does not appear.
