### ISSUE TITLE
Multi-select quickpick not handling mouse click events properly in Insiders

### ISSUE THREAD

**Issue by jkeech** [microsoft/vscode#170880]
When opening as quickpick with [multi-select options](https://code.visualstudio.com/api/ux-guidelines/quick-picks#multiple-selections), the latest Insiders builds only handle click events on the checkbox and not on the row item. In Stable, clicking on the row works as expected. This sounds very similar to https://github.com/microsoft/vscode/issues/170559 and might have the same cause.

Does this issue occur when all extensions are disabled?: Unsure, probably yes

- VS Code Version: 1.75.0-insider, Commit: 727d2d32aea02baf7d13fa38787e8ed64dd858d0
- OS Version: Windows11(22621.963), macOS Ventura 13.1; using the VS Code in the web

Steps to Reproduce:

1. Open a quick pick UI with multiple selection options
2. 🐛 Try to click a row and observe that the selection doesn't change
3. Click on the checkbox and observe the selection does change

This bug was observed with the Codespaces extension, but should happen for any extension/UI using multi-select quick picks.

**Comment by TylerLeonhardt** [comment]
@jkeech can you update to the latest Insiders from today and try again?

**Comment by roblourens** [comment]
Yes, more fallout from https://github.com/microsoft/vscode/pull/169680/files, apologies
