### ISSUE TITLE
Relative paths and paths without columns not linked in debug console

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#17085]
![image](https://cloud.githubusercontent.com/assets/1926584/21108679/4c364152-c096-11e6-9fec-22f4e95f69e2.png)

fyi @felixfbecker 
ref https://github.com/Microsoft/vscode/issues/13370

**Comment by felixfbecker** [comment]
Summary what doesn't work:
- File paths without columns (shown in screenshot)
- Relative paths

**Comment by michelkaporin** [comment]
This has been addressed in #24451, with the test plan item created #26203.
