### ISSUE TITLE
Special case of pasting multiple lines to the same number of multicursors

### ISSUE THREAD

**Issue by HolyBlackCat** [microsoft/vscode#170846]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.74.2
- OS Version: Xubuntu 22.04.1

Steps to Reproduce:

1. Select and copy multiple lines of text (N lines) (in the normal way, without creating multiple cursors)
2. Have multiple cursors (N cursors, with the same N)
3. Paste
4. Observe that a single line was pasted to each respective cursor, as opposed to the whole clipboad being pasted to each cursor.

This doesn't happen when the number of cursors is different than the number of copied lines (then the whole clipboard is pasted to each cursor).

I frequently paste multiline selections to multiple cursors, and when the number of cursors & lines just happen to match, this blows up in my face.

This was introduced on purpose in commit https://github.com/microsoft/vscode/commit/1374fa6aa7df492b667e5c3c7ffd5e7f025b97e4, but I can't fathom why anybody would want it to be a special case, when you can already trigger this behavior by selecting the original text using multicursors. At least this should be a config option.

**Comment by gjsjohnmurray** [comment]
Please check out the `editor.multiCursorPaste` setting.
