### ISSUE TITLE
[perf] Investigate `getOverrideValue` usages in renderer

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#170877]
re https://github.com/microsoft/vscode/issues/170954

Automatic renderer profiling shows many calls/usages of [getOverrideValue](https://github.com/microsoft/vscode/blob/67fd9d10519006d7d2ab34ebfce1a6edd5acebf2/src/vs/platform/configuration/common/configurationModels.ts#L93). The call stack hints towards the settings editor, e.g this is a sample for the `727d2d32aea02baf7d13fa38787e8ed64dd858d0` insiders release

```
inspect#workbench.desktop.main.js:641:13951
<inspect#workbench.desktop.main.js:1191:2877
<inspect#workbench.desktop.main.js:2275:21560
<o#workbench.desktop.main.js:2031:4115
<t#workbench.desktop.main.js:2031:3814
<(anonymous)#workbench.desktop.main.js:2031:3595
<p#workbench.desktop.main.js:2031:3471
<(anonymous)#workbench.desktop.main.js:2031:3720
<p#workbench.desktop.main.js:2031:3471
<(anonymous)#workbench.desktop.main.js:2031:3720
<p#workbench.desktop.main.js:2031:3471
<update#workbench.desktop.main.js:2031:2777
<Gc#workbench.desktop.main.js:2289:56620
```

**Comment by sandy081** [comment]
@rzhao271 Can you please start investigating this beginning with settings editor and let me know if there is anything to be done in the model, say a way of getting values in bulk for eg?

**Comment by jrieken** [comment]
Might have been a fluke - this showed for one insiders build but not for yesterdays...

**Comment by rzhao271** [comment]
Let me know if this shows up again.
I believe that inspect is called when switching scopes (like User to Workspace), and when a language filter is applied.

**Comment by jrieken** [comment]
> Let me know if this shows up again.

Even better - you can now just check error telemetry for this function

**Comment by rzhao271** [comment]
I believe this is fixed now
