### ISSUE TITLE
VScode terminal keyboard shortcuts ctl-c and ctl-v not working

### ISSUE THREAD

**Issue by hubbertsmith** [microsoft/vscode#170813]
Type: <b>Bug</b>

vs code 1.74.2 - Ubuntu 20.04
highlight text in terminal, ctl-c >> does not copy
copy text onto clipboard, ctl-v >> does not paste

this worked as expected, then broke. can I fix?

VS Code version: Code 1.74.2 (e8a3071ea4344d9d48ef8a4df2c097372b0c5161, 2022-12-20T10:27:19.253Z)
OS version: Linux x64 5.15.0-57-generic
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz (8 x 3699)|
|GPU Status|2d_canvas: unavailable_software<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>opengl: disabled_off<br>rasterization: disabled_software<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software<br>webgpu: disabled_off|
|Load (avg)|1, 1, 0|
|Memory (System)|15.05GB (11.53GB free)|
|Process Argv|--user-data-dir /home/hubbert/.anaconda/navigator/Code --crash-reporter-id d1bccc3d-d176-48f4-b00f-302a10cb4306|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|plasma|
|XDG_CURRENT_DESKTOP|KDE|
|XDG_SESSION_DESKTOP|KDE|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-docker|ms-|1.23.3
python|ms-|2022.20.1
vscode-pylance|ms-|2023.1.10
remote-containers|ms-|0.266.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
azure-dev_surveyone:30548225
pyindex848:30577860
nodejswelcome1:30587005
3biah626:30602489
3d0df643:30613357
f6dab269:30613381
fim-prod:30623723

```

</details>

**Comment by hubbertsmith** [comment]
thanks for your kind response.
on windows 11 C:\Users\hubbe\AppData\Roaming\Code\User\settings.json
(guessing settings.jsonthey are same for Win or Linux). and my linux system
is doing the same thing.
I can provide from my Ubuntu system if that is more convenient for you
thanks again
{
    "python.pythonPath": "C:\\Users\\hubbe\\miniconda3\\python.exe",
    "files.associations": {
        "*.rmd": "markdown"
    },
    "kite.showWelcomeNotificationOnStartup": false,
    "yaml.schemas": {
        "file:///toc.schema.json": "/toc\\.yml/i"
    },
    "workbench.colorTheme": "Cobalt3",
    "workbench.editorAssociations": {
        "*.ipynb": "jupyter-notebook"
    },
    "vs-kubernetes": {
        "vs-kubernetes.minikube-path.windows": "C:\\Users\\hubbe\\
.vs-kubernetes\\tools\\minikube\\windows-amd64\\minikube.exe",
        "vs-kubernetes.helm-path.windows": "C:\\Users\\hubbe\\.vs-kubernetes
\\tools\\helm\\windows-amd64\\helm.exe",
        "vs-kubernetes.draft-path.windows": "C:\\Users\\hubbe\\
.vs-kubernetes\\tools\\draft\\windows-amd64\\draft.exe",
        "vscode-kubernetes.minikube-path.windows": "C:\\Users\\hubbe\\
.vs-kubernetes\\tools\\minikube\\windows-amd64\\minikube.exe"
    },
    "redhat.telemetry.enabled": true,
    "notebook.cellToolbarLocation": {
        "default": "right",
        "jupyter-notebook": "left"
    },
    "python.defaultInterpreterPath": "C:\\Users\\hubbe\\miniconda3\\
python.exe",
    "remote.SSH.remotePlatform": {
        "10.0.0.25": "linux",
        "172.26.110.144": "linux"
    },
    "security.workspace.trust.untrustedFiles": "open",
    "editor.minimap.enabled": false,
    "http.proxyAuthorization": null
}
***@***.*** | 385 321 0757 | LinkedIN
<https://www.linkedin.com/in/hubbertsmith/>
Inspiring Remote Tech Teams
<https://www.amazon.com/Inspiring-Remote-Tech-Teams-Performance-ebook/dp/B08VLFYTT3/ref=sr_1_1?crid=H8M90B2UMA6Q&dchild=1&keywords=hubbert+smith&qid=1624635961&sprefix=hubbert+s%2Caps%2C209&sr=8-1>
*Linkedin Learning: Program Management for IT Professionals
<https://tinyurl.com/y8rzzzoa>*
Blog - hubbertsmith.com <http://hubbertsmith.com>
Schedule a MEETING <https://calendly.com/hubbert/60min>

**Comment by meganrogge** [comment]
thanks, you'll want to use the command `Toggle keyboard shortcuts troubleshooting` to figure out your configuration issue

**Comment by hubbertsmith** [comment]
these instructions did not work. kindly spell it out for me.
I appreciate the help

***@***.*** | 385 321 0757 | LinkedIN
<https://www.linkedin.com/in/hubbertsmith/>
Inspiring Remote Tech Teams
<https://www.amazon.com/Inspiring-Remote-Tech-Teams-Performance-ebook/dp/B08VLFYTT3/ref=sr_1_1?crid=H8M90B2UMA6Q&dchild=1&keywords=hubbert+smith&qid=1624635961&sprefix=hubbert+s%2Caps%2C209&sr=8-1>
*Linkedin Learning: Program Management for IT Professionals
<https://tinyurl.com/y8rzzzoa>*
Blog - hubbertsmith.com <http://hubbertsmith.com>
Schedule a MEETING <https://calendly.com/hubbert/60min>
