### ISSUE TITLE
vs code crashes on ventura

### ISSUE THREAD

**Issue by mohamedfelfl** [microsoft/vscode#170800]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.74.2
- OS Version: 13.1

Steps to Reproduce:

1. Reinstalling vs code
2. Updating mac to latest version

 
![Screenshot 2023-01-08 at 3 32 25 PM](https://user-images.githubusercontent.com/19213098/211198851-26842a6a-4641-421b-934a-5cc8b9d060b6.png)

**Comment by bpasero** [comment]
Can you please follow the steps in https://github.com/Microsoft/vscode/wiki/Native-Crash-Issues to get at more details around the crash and attach the result here? Thanks!

**Comment by deepak1556** [comment]
Merging to https://github.com/microsoft/vscode/issues/165127
