### ISSUE TITLE
Perf: consider to further delay `_savePartsSplash`

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#170825]
I noticed that saving parts splash occurs during startup, even though delayed:

![part-splash](https://user-images.githubusercontent.com/900690/211261862-3f90b9e6-34bd-4b51-91c2-a025c5e31393.png)

I am not sure we need that, maybe we can put that on the `Restored` phase.

The following profile:
* was taken on Windows
* with a non-minified / non-mangled build to aid reading
* has the `ellapsed` event at `6755ms`

[prof-QIBV4was.main.zip](https://github.com/microsoft/vscode/files/10371380/prof-QIBV4was.main.zip)

**Comment by jrieken** [comment]
Moved it out a bit further but the overall timing is a lottery because it depends on the current state (destruction) of the dom and how long measuring will take
