### ISSUE TITLE
The control goes to the bottom of the file upon pasting a word any where on a file

### ISSUE THREAD

**Issue by ranjithrb** [microsoft/vscode#170878]
Type: <b>Bug</b>

Steps to Reproduce:

1. My project file had about 250 lines, which I opened in VS code
2. I copied a word and just pasted it on top of the file.
3. Upon pasting, the cursor jumped to the bottom of the file 

Extension version: 0.0.3
VS Code version: Code 1.74.2 (Universal) (e8a3071ea4344d9d48ef8a4df2c097372b0c5161, 2022-12-20T10:26:09.430Z)
OS version: Darwin arm64 22.2.0
Modes:
Sandboxed: No

**Comment by eleanorjboyd** [comment]
@ranjithrb, are you still having this issue?
