### ISSUE TITLE
workspace.applyEdit fails in git view

### ISSUE THREAD

**Issue by hoovercj** [Microsoft/vscode#1708]
I have a code action that performs a WorkspaceEdit which works just fine in the normal view but fails in the diff view.

Code:
```javascript
let edit = new vscode.WorkspaceEdit();
edit.replace(uri, range, replacementText);
vscode.workspace.applyEdit(edit);
```

Message:
TypeError: i.getModel(...).getAssociatedResource is not a function

Stack:
TypeError: i.getModel(...).getAssociatedResource is not a function\n    at Object.a [as finish] (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:36:9471)\n    at Object.d [as bulkEdit] (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:36:9143)\n    at e.applyWorkspaceEdit (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:61:18416)\n    at t.e.handle (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:52:3220)\n    at a (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:38:12357)\n    at Object.h.handle (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:38:12921)\n    at file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:67:5098\n    at ChildProcess.<anonymous> (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:67:7608)\n    at emitTwo (events.js:87:13)\n    at ChildProcess.emit (events.js:172:7)

**Comment by alexandrudima** [comment]
@jrieken Isn't this your area? - `src\vs\editor\common\services\bulkEdit.ts`:

```typescript
function finish(): TPromise<ISelection> {
		...
		if (editor) {
			uri = editor.getModel().getAssociatedResource();
			selections = editor.getSelections();
		}
		...
}
```

**Comment by jrieken** [comment]
Unfortunately yes...

**Comment by alexandrudima** [comment]
:)

**Comment by jrieken** [comment]
@hoovercj Do you have more precise steps? Do you open a diff view and apply the edit? is `uri` the left or right side of the diff view?

**Comment by hoovercj** [comment]
This manifests in [my extension](https://github.com/hoovercj/vscode-haskell-linter/blob/master/src/features/hlintProvider.ts) line 144 `provideCodeActions`, line 270 `runCodeAction`.

The precise steps as a user would be:
1. Make a change to a file that will cause an actionable diagnostic to be provided.
2. Switch to the git diff view
3. Notice the diagnostic on the right side of the diff view
4. Highlight the code and see a lightbulb
5. Click the lightbulb to trigger the code action
6. Wonder why nothing happened

The `uri` being provided to the `provideCodeActions` via the `vscode.TextDocument` object is simply the normal path. `file:///path/to/file.hs`, no right or left or anything.

**Comment by hoovercj** [comment]
I know I'm a bit late, but I finally got around to checking if this was working. I haven't made any code changes to my extension and I'm running 1.1.0 and set the engine to ^1.0.0 package.json and when I go through the steps I listed above it doesn't make the change and I get the following exception in the extension host console:

```
shell.ts:416 i.getModel(...).getAssociatedResource is not a function: TypeError: i.getModel(...).getAssociatedResource is not a function
    at Object.a [as finish] (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:57:10149)
    at Object.d [as bulkEdit] (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:57:9775)
    at e.$applyWorkspaceEdit (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:84:1399)
    at t.e.handle (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:73:8350)
    at s (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:55:27689)
    at f (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:55:28366)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```
Does this bug need reopened or am I doing something wrong?

To clarify: doing a normal edit in a normal file still works, but the same edit fails when viewing the file in diff mode.
