### ISSUE TITLE
[Bug] Cannot load windows.h correctly

### ISSUE THREAD

**Issue by youzi-2333** [microsoft/vscode#170942]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.74.2
- OS Version: Windows 10.0 Home Edition

Steps to Reproduce:

1. Open a cpp file on Visual Studio or Visual Studio Code;
2. Everything that depends on windows.h cannot load correctly.

Hi,
The information below is important.
I've just installed Kits in Visual Studio. Since then, I can't load windows.h correctly, even I reinstalled Visual Studio *completely*. You can always contact me by commenting to this Issue or Emailing [youzi5201086@163.com](mailto:youzi5201086@163.com).

**Comment by Qiyuanqwq123** [comment]
THANKS FOR HELPING ME

**Comment by Qiyuanqwq123** [comment]
That's not work.......
