### ISSUE TITLE
Analyse renderer performance traces

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#170954]
We have an active experiment in which renderers that experience long tasks are optimistically profiled for a bit. Interesting CPU profiles are uploaded as anonymous telemetry events and it's on us to follow up.

**Comment by Jwhitmer0110** [comment]
[https://github.com/microsoft/vscode/issues/170877#issue-1525931366](https://github.com/microsoft/vscode/issues/170877#issue-1525931366) @ # # #
Duplicate of #

**Comment by Jwhitmer0110** [comment]
1. ### 

- [ ] _****_
