### ISSUE TITLE
installing issus

### ISSUE THREAD

**Issue by Jamaalmjt** [microsoft/vscode#170974]
Type: <b>Performance Issue</b>

i'm unable to install any Extension on the new version of visual studio code i've tried everthing from reinstalling visual studio code to chaning my DNS nothing working . i've even tried  doing it manually put it come back with a JSON input error

VS Code version: Code 1.74.2 (Universal) (e8a3071ea4344d9d48ef8a4df2c097372b0c5161, 2022-12-20T10:26:09.430Z)
OS version: Darwin x64 20.3.0
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4260U CPU @ 1.40GHz (4 x 1400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|2, 2, 2|
|Memory (System)|4.00GB (0.10GB free)|
|Process Argv|--crash-reporter-id 1cad82e3-8a04-455f-9fa3-6cb42770be0e|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
   15	    94	 31012	code main
    3	    37	 31034	   gpu-process
    0	    16	 31041	   utility-network-service
    4	   111	 31087	   shared-process
    0	    25	 31104	     ptyHost
    0	    25	 44549	     fileWatcher
    0	     0	 50439	     /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0	   160	 44528	   window (Extension: Python Extension Pack)
    0	    33	 44548	   extensionHost
    0	    66	 49525	   window (undefined)
    0	    66	 50368	   issue-reporter
```

</details>
<details>
<summary>Workspace Info</summary>

```
;
```

</details>
Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
azure-dev_surveyone:30548225
pyindex848cf:30577861
nodejswelcome1:30587005
2e4cg342:30602488
3d0df643:30613357
f6dab269:30613381
fim-prod:30623723

```

</details>

**Comment by sandy081** [comment]
Can you please let us know if you are seeing any error?  If possible please share a gif/video?
Can you please enable log level to trace and provide logs:

- F1 > Set Log Level... > Trace
- Reproduce the issue
- Share the log - F1 > Open View > Shared
- Share the console log - F1 > Developer: Toggle Shared Process > Console

**Comment by Jamaalmjt** [comment]
![Screenshot 2023-01-11 at 09 55 31](https://user-images.githubusercontent.com/108972901/211749619-d17da156-c7ff-408f-a6fa-307634ea998c.png)
 this is the error i get when trying to install

**Comment by Jamaalmjt** [comment]
![Screenshot 2023-01-11 at 09 56 10](https://user-images.githubusercontent.com/108972901/211749829-58dd0bcc-d529-4c1a-a1c1-d76bffd1f38c.png)
this is the log error i get

**Comment by Jamaalmjt** [comment]
I'm using MacBook air if that help in any way

**Comment by sandy081** [comment]
What do you see here

- F1 > Open View > Shared
- Can you please open extensions folder - F1 > Open Extensions Folder and check `extensions.json` file has any errors?

**Comment by Jamaalmjt** [comment]
No it has no error message

**Comment by Jamaalmjt** [comment]
![Screenshot 2023-01-13 at 14 25 18](https://user-images.githubusercontent.com/108972901/212319964-b6093bbe-8845-4d5d-ade6-2ad22390c5ed.png)
 that's what in the file when i open it

**Comment by sandy081** [comment]
Can you please delete this file and retry?

**Comment by Jamaalmjt** [comment]
It worked thank you

**Comment by Jamaalmjt** [comment]
it  worked
