### ISSUE TITLE
VSCode error compiling c++ exe not found

### ISSUE THREAD

**Issue by Mugiwara303** [Microsoft/vscode#17092]
- VSCode Version: 1.7.2
- OS Version: windows 8.1 v6.3 build 9600

Steps to Reproduce:

1. i have a problem with compiling .cpp to .exe, but i can compile from cmd without problems
2. when i click debug it gives me an error main.exe not found
after trying i am clicking ctrl+shift+b to build then F5 to run, why i can't just click F5 and it should build and run? thank you

tasks.json
```
{
    "version": "0.1.0",
    "command": "C:\\CodeBlocks\\MinGW\\bin\\g++.exe",
    "isShellCommand": true,
    // compiles and links with debugger information
    "args": ["-g", "-o", "main.exe", "main.cpp"],
    // without debugger information
    //"args": ["-o", "hello.exe", "hello.cpp"],
    "showOutput": "always"
}
```

launch.json
```
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "C++ Launch (Windows)",
            "type": "cppdbg",
            "request": "launch",
            "program": "${workspaceRoot}/main.exe",
            "MIMode": "gdb",
            "miDebuggerPath": "C:\\CodeBlocks\\MinGW\\bin\\gdb.exe",
            "stopAtEntry": false,
            "cwd": "${workspaceRoot}",
            "externalConsole": false,
            "visualizerFile": "${workspaceRoot}/my.natvis"
        },
        {
            "name": "C++ Attach (Windows)",
            "type": "cppvsdbg",
            "request": "attach",
            "processId": "${command.pickProcess}" 
        }
    ]
}
```
![11](https://cloud.githubusercontent.com/assets/24526558/21119156/28f44c98-c0b9-11e6-9599-a041a45860ec.jpg)
![22](https://cloud.githubusercontent.com/assets/24526558/21119157/28fecfe2-c0b9-11e6-8c51-c21d045c8b19.jpg)

**Comment by mjbvz** [comment]
I believe you need to set a [`preLauchTask` in the `launch.json`](https://github.com/Microsoft/vscode/issues/2086). This will automatically run the build task when you launch the debugger with f5.

Let me know if that solves your problem.

**Comment by Mugiwara303** [comment]
@mjbvz thank you, i have added `"preLaunchTask": "C:\\CodeBlocks\\MinGW\\bin\\g++.exe"` and it works, but one small problem when i click F5 the output console pops up instead of the debug console, is there a way to fix it or a shortcut? thank you

**Comment by Mugiwara303** [comment]
@mjbvz thank you, i have added `"preLaunchTask": "C:\\CodeBlocks\\MinGW\\bin\\g++.exe"` and it works, but one small problem when i click F5 the output console pops up instead of the debug console, is there a way to fix it or a shortcut? thank you
