### ISSUE TITLE
Feature 'Format On Save Mode' in settings doesn't work properly

### ISSUE THREAD

**Issue by zhkvivan** [microsoft/vscode#170961]
Type: <b>Bug</b>

https://code.visualstudio.com/updates/v1_49#_only-format-modified-text

According to this :arrow-up: update, choosing option 'modifications' in the 'Format On Save Mode' menu would lead to the behaviour when pretier would format only lines that you've changed. And if there would not formatted pieces of code already commited before - it wouldn't format them. 

But in reality it format those pieces of code too. It works this way: if you have 'modifications' turned on, it doesnt format the file on save if you haven't made any changes to the file. But as soon as you change even one single line - it formats the whole file.. 

VS Code version: Code 1.74.2 (Universal) (e8a3071ea4344d9d48ef8a4df2c097372b0c5161, 2022-12-20T10:26:09.430Z)
OS version: Darwin arm64 21.6.0
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|5, 6, 6|
|Memory (System)|16.00GB (0.07GB free)|
|Process Argv|--crash-reporter-id 1b43ade5-b992-49b8-9cdb-be7f8e7a23f7|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (39)</summary>

Extension|Author (truncated)|Version
---|---|---
codesnap|adp|1.3.4
vscode-sql-formatter|adp|1.4.4
vscode-color|ans|0.4.5
bemhelper|Box|1.4.5
htmltagwrap|bra|0.0.7
vscode-eslint|dba|2.2.6
es7-react-js-snippets|dsz|4.4.3
gitlens|eam|13.2.0
EditorConfig|Edi|0.16.4
prettier-vscode|esb|9.10.3
auto-rename-tag|for|0.1.10
code-runner|for|0.11.8
shell-format|fox|7.2.2
beautify|Hoo|1.5.0
rest-client|hum|0.25.1
elixir-ls|Jak|0.13.0
vscode-gutter-preview|kis|0.30.0
vscode-language-babel|mgm|0.0.36
vscode-language-pack-ru|MS-|1.74.12140931
data-workspace-vscode|ms-|0.3.0
mssql|ms-|1.16.0
sql-bindings-vscode|ms-|0.3.0
sql-database-projects-vscode|ms-|0.19.0
live-server|ms-|0.4.4
vsliveshare|ms-|1.0.5797
vscode-css-navigation|puc|1.13.3
vscode-thunder-client|ran|2.3.0
vscode-commons|red|0.0.6
vscode-xml|red|0.23.0
live-sass|rit|3.0.0
LiveServer|rit|5.7.9
html5-boilerplate|sid|1.1.1
autoimport|ste|1.5.4
vscode-styled-components|sty|1.7.5
vscode-stylelint|sty|1.2.3
sass-indented|syl|1.8.23
highlight-matching-tag|vin|0.10.1
JavaScriptSnippets|xab|1.8.0
ReactSnippets|xab|2.4.0

(3 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
azure-dev_surveyone:30548225
pyindex848cf:30577861
nodejswelcome1cf:30587006
2e4cg342:30602488
3d0df643:30613357
f6dab269:30613381
fim-prod:30623723

```

</details>

**Comment by jrieken** [comment]
This issue lacks

* mentioning of the language and extension providing formatting edits
* copy-paste friendly source code samples

**Comment by zhkvivan** [comment]
1. We tried it on TypeScript and XML also. 

As you can see on the gif below, before editing this file I saved - and nothing have been formatted which is fine. 
But after I edited one line at the end of the file and saved it - it formatted the whole document although meant to format only newly added line
![Jan-10-2023 14-30-31](https://user-images.githubusercontent.com/65277182/211578443-9be6767c-f52e-4528-8857-412000097db0.gif)

2. https://github.com/zhkvivan/example

**Comment by aeschli** [comment]
We don't provide a built-in XML provider. Which XML extension do you use?

**Comment by aeschli** [comment]
Please file the issue against the extension that provides the formatter.
