### ISSUE TITLE
Error: Cannot find module '"/Applications/Visual' when using the Javascript Debug Terminal

### ISSUE THREAD

**Issue by hamzahamidi** [microsoft/vscode#170957]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.74.2 (Universal)
- OS Version: Mac OS 13.1 (22C65)
- Nodejs version: v10.19.0
- nodemon: 1.19.4

I'm getting the below error when using the Javascript Debug Terminal

> 
> ➜  some-nodejs-project git:(master) ✗ npm run dev
> internal/modules/cjs/loader.js:638
>     throw err;
>     ^
> 
> Error: Cannot find module '"/Applications/Visual'
>     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
>     at Function.Module._load (internal/modules/cjs/loader.js:562:25)
>     at Module.require (internal/modules/cjs/loader.js:692:17)
>     at Module._preloadModules (internal/modules/cjs/loader.js:901:12)
>     at preloadModules (internal/bootstrap/node.js:602:7)
>     at startup (internal/bootstrap/node.js:273:9)
>     at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)

Steps to Reproduce:
package.json scripts:
    "dev": "nodemon --inspect  server.js",

1. Open a Javascript Debug Terminal
2. Run the nodejs script

**Comment by connor4312** [comment]
We no longer support Node 10 in the debug terminal. Node 10 [reached its end](https://github.com/nodejs/Release) of life almost two years ago; I recommend updating to have the latest security patches and features.
