### ISSUE TITLE
CPU usage skyrockets when holding down an input button

### ISSUE THREAD

**Issue by Kwoth** [Microsoft/vscode#1709]
VS Code Version: 0.10.6 (dcb02458)
OS: Windows 10

How to reproduce:  
- Open task manager  
- Open a new file  
- Hold down a letter or a space bar or enter  

Arrow button also causes this, but cursor needs to move i think. So if you add some text and hold down an arrow key, it will produce the same issue.

CPU usage goes from ~0 to ~33% for me (i5 cpu). 

From my limited knowledge, i can assume 2 things: 
This is either fixable by making the whatever code executes when cursor changes position be executed only if cursor didn't change position for 100-200 milliseconds 
**or**
Input handling is not limited by "fps", so the app gets overwhelmed

**Comment by Spown** [comment]
On my AMD 1055t (2.8GHz) it also eats up to 30%, but is it really an issue for a desktop app written entirely in TS/JS? Especially when you think about how many things are happening in the background on the input (Intellisense, syntax highlighting, gui interraction, file state...). I experience no slowdowns. things surely can be a subject of improvement, but I don't think its a bug.

**Comment by alexandrudima** [comment]
From my measurements, handling the typing of one letter takes ~2ms on my machine, followed by the rendering of the editor at the next animation frame of around ~5ms.

I believe typing is fast enough. I believe the repeat rate for a keypress can be configured at the OS level and Electron/Chromium will respect that.
