### ISSUE TITLE
cmd+shift+B with multiple "isDefault" build tasks should only show those build tasks

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#170918]
- Have multiple tasks configured with 

```
"group": {
    "kind": "build",
    "isDefault": true
},
```
- Press cmd+shift+B
- See all detected tasks

See the vscode-jupyter repo for an example. I see dozens of tasks, including stuff detected from stuff that isn't even my repo. 

<img width="625" alt="image" src="https://user-images.githubusercontent.com/323878/211433507-15ec2249-58be-41eb-b3ab-fe7067b08fc1.png">

I'm not sure what this list is since the "Run task" list is much cleaner

<img width="620" alt="image" src="https://user-images.githubusercontent.com/323878/211433697-9728a47f-f827-434d-91ec-54775519442e.png">

It's weird that I get

- 1 default task -> cmd+shift+B runs it
- 2 default tasks -> cmd+shift+B shows dozens of tasks

**Comment by meganrogge** [comment]
This has been fixed
