### ISSUE TITLE
Profiles: Cannot export extensions installed from `.vsix`

### ISSUE THREAD

**Issue by jeswr** [microsoft/vscode#170932]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.75.0-insider 04b15ff231a2c3cfcdd90d90c16075a9c1e6da15 x64
- OS Version: Linux ubuntu 22.10 (Kinetic Kudu)

Steps to Reproduce:

1. Open vscode with a new profile `code-insiders profile=myNewProfile`
2. Install a new extension from a `.vsix` using `Extensions: Install from VSIX...`
3. Export the profile using `Profiles: Export Profile (myNewProfile)...`

Expected Behavior:

The extension installed in step 2 is included in `myNewProfile.code-profile`

Actual Behavior:

It is not included.

**Comment by jeswr** [comment]
The context for this bug report is that I have a monorepo with 2 extensions. One extension is an `AuthenticationProvider`; and the other extension uses that authentication provider. Thus I need to have the `AuthenticationProvider` extension installed when I am working on the extension that consumes that provider; ideally the `AuthenticationProvider` would be automatically installed in a temporary profile whenever a debugger for the consumer is launched.

**Comment by gjsjohnmurray** [comment]
I assume you are installing from VSIX because that extension hasn't yet been published, or maybe isn't intended for publication.

In that case how do you suggest VS Code should obtain that extension if I import your exported profile?

**Comment by sandy081** [comment]
In general, it does not makes sense to include non-published extensions while exporting the profile. Can you please explain your use case in detail and why exporting a profile is involved?

**Comment by jeswr** [comment]
Sure @sandy081 - I've put together a minimal repo to demonstrate the issue and described the problem statement there https://github.com/jeswr/minimal-extensions-monorepo.

As noted in the repo exporting non-published extensions is just one of several ways I have tried to solve my issue.

**Comment by sandy081** [comment]
Ok, I understood why it did not work. There is a bug in the following line

```
code --profile=myProviderProfile --install-extension=./extensions/myauthprovider/myauthprovider-0.0.1.vsix
```

Extension will be installed in the profile, only if the provided profile exists. This is a limitation in CLI that, one cannot create profiles from CLI. So I would recommend to create a profile with above extension from VS Code UI:

- Open VS Code
- Create an empty profile
- Install the above extension

Use this profile for debugging your extension.

Meanwhile, I will update the CLI to throw an error in this case so that users can know about it.
