### ISSUE TITLE
Security concern - improve the misleading "verified ownership" blue icon for extensions

### ISSUE THREAD

**Issue by nunoperalta** [microsoft/vscode#170934]
For a long time, I thought the blue icon meant that the extension is a Trusted/Featured Extension, totally safe to install, because it's flagged by Microsoft as so.

<img width="131" alt="image" src="https://user-images.githubusercontent.com/487079/211480899-3b022c8f-9df8-4305-8b70-e7175591eacc.png">

However, apparently it just means that the verified blue check mark merely means that whoever the publisher is has proven the ownership of a domain. **That means any domain.** In reality, a publisher could buy any domain and register it to get that verified check mark.

In other words, **this icon is totally useless and misleading**.

This opens a huge security concern, as someone can completely impersonate another popular extension, mark it was "verified ownership", and developers might trust the "verified" one, install that one, and compromise their device.

For example - the popular Prettier extension does not have the "verified" flag.
Anyone can create a new extension, impersonate as prettier, even having a namespace very similar to it (with `pretier` instead of `prettier`), and verify ownership:

<img width="239" alt="image" src="https://user-images.githubusercontent.com/487079/211482131-b004991b-e6d4-4e4f-a63d-b76998f5730f.png">

**Comment by sketchbuch** [comment]
Maybe you can have a verification system that works for people wihout websites, who maybe just use github for hosting extensions.

**Comment by PEZ** [comment]
> Anyone can create a new extension, impersonate as prettier, even having a namespace very similar to it (with `pretier` instead of `prettier`), and verify ownership

I think there are manual steps in the process, so not sure ”anyone can verify ownership” is true.

**Comment by nunoperalta** [comment]
@PEZ 
> I think there are manual steps in the process, so not sure ”anyone can verify ownership” is true.

Even so, while the manual review happens, the extension can seem like a legit one, doing XYZ function, to trick the reviewer.
And as soon as it's approved, the extension owner can change the Name, Image and Description of the extension. (just the namespace cannot be changed, but that doesn't even appear in the sidebar results)

**Comment by isidorn** [comment]
Thank you for opening this issue and for sharing feedback.

I agree that the verified checkmark is not perfect, but I do believe it brings much more good than harm:
* As @pez points out each verified extension goes through a manual review process
* On hover of the verified checkmark we show the verified domain, so user can make the informed decision before downloading the extension (image attached) 
* The official Prettier extension will soon get verified (awaiting some things from extension author)

I do not think we will remove the verified checkmark, but we are open for feedback on how can we improve it. And I know the marketplace team is working on tackling many of the concerns shared in the first comment. Thank you.

fyi @amit-kulkarni-in 

![Screenshot 2023-01-12 at 11 31 17](https://user-images.githubusercontent.com/1926584/212043552-4f252974-45e3-4cbb-977d-350c96dac9ae.png)

**Comment by nunoperalta** [comment]
@isidorn - Just because you have it saying "publisher has verified ownership of xyz.com" appearing only on mouse-over, it doesn't mean everyone will see it. As I said, I only understood what the blue icon means recently, and I use VSCode for a long time already.

I don't see any utility in that blue icon appearing in the main list, visible by default, if the meaning of it isn't that the extension is trusted. **This icon is a very dangerous thing.**

**Comment by nunoperalta** [comment]
@isidorn - Just because you have it saying "publisher has verified ownership of xyz.com" appearing only on mouse-over, it doesn't mean everyone will see it. As I said, I only understood what the blue icon means recently, and I use VSCode for a long time already.

I don't see any utility in that blue icon appearing in the main list, visible by default, if the meaning of it isn't that the extension is trusted. **This icon is a very dangerous thing.**

Several people seem to agree that this is a security issue, based also on the Upvotes in this Reddit thread: https://www.reddit.com/r/vscode/comments/1083a1b/security_concern_remove_the_misleading_verified/

**Comment by nunoperalta** [comment]
@isidorn - This is a much better way of doing it, if you definitely want to keep it showing in the main feed.

Clear that it relates to the domain, and not misleading in my opinion.

![124186561-7fd5eb80-da8a-11eb-8a0f-c6fe5009d368](https://user-images.githubusercontent.com/487079/212191452-fc23caaa-7f15-47ab-a1a1-47a1248ad443.png)

![124186392-40a79a80-da8a-11eb-9b16-9ba63e421cce](https://user-images.githubusercontent.com/487079/212191490-07195cbf-a3e2-4a67-b742-be08fe67967b.png)

**Comment by isidorn** [comment]
@nunoperalta thanks for your suggestion.
I am concerned about the available real estate in the extensions view. Since there can be many more icons, and we are very careful what we put in the limited real estate we have available.

But I 100% agree that we should show it in the extension details page.
@sandy081 what do you think?

**Comment by sketchbuch** [comment]
@isidorn Can't you have a way to verify using a github repo. Most extension devs won't have websites.

**Comment by isidorn** [comment]
@sketchbuch that I feel like is a separate feature that is orthogonal to this. We could also verify a repository. Can you file a new issue for this here https://github.com/microsoft/vsmarketplace
In practice so far - most extension devs do have websites.

**Comment by sketchbuch** [comment]
https://github.com/microsoft/vsmarketplace/issues/557

**Comment by PEZ** [comment]
> we are very careful what we put in the limited real estate we have available.

Something like this, maybe?

<img width="302" alt="image" src="https://user-images.githubusercontent.com/30010/212308121-94b8ae9d-ec32-4caf-9407-18a67fd7a4f7.png">

It prioritizes the verified status before the publisher name, which at least for me is how I want it prioritized.

**Comment by sandy081** [comment]
> But I 100% agree that we should show it in the extension details page.
@sandy081 what do you think?

Yeah, makes sense to me.

**Comment by isidorn** [comment]
@sandy081 great. I went ahead and assigned this to the next milestone since I feel this is low hanging and we can look into it in February.

**Comment by isidorn** [comment]
We started by rendering it in the extensions details page.
We will have follow up discussions if we will also render it in the extension view on the left.

<img width="689" alt="image (8)" src="https://user-images.githubusercontent.com/1926584/218102764-04b14258-bcd1-4c52-8743-1ad4016f692a.png">
<img width="616" alt="image (7)" src="https://user-images.githubusercontent.com/1926584/218102771-caac774f-842b-4eed-b55d-e92f670eb505.png">
<img width="581" alt="image (6)" src="https://user-images.githubusercontent.com/1926584/218102773-1aa2b254-a5ba-4838-a21b-255e644a7308.png">

**Comment by nunoperalta** [comment]
Thank you very much! That's a great improvement.
Have a great day.
