### ISSUE TITLE
Flaky install dependencies

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#170935]
Also yesterday.

https://monacotools.visualstudio.com/DefaultCollection/Monaco/_build/results?buildId=198946&view=results

<img width="437" alt="image" src="https://user-images.githubusercontent.com/900690/211483985-80207d2d-7b42-443a-9ba8-facbc2c4ad40.png">

**Comment by joaomoreno** [comment]
Sadly this is Terrapin. We already repeat it 3 times. This specific build failed those 3 times. All we can do is tell them (which we have) or increase the retry count.
