### ISSUE TITLE
I can't bind one key with two or more commands in keybindings.json

### ISSUE THREAD

**Issue by foisonocean** [Microsoft/vscode#171]
My user keybindings.json is like this:
    [
    {
    "key": "ctrl+/",
    "command": "editor.action.commentLine && cursorDown",
    "when": "editorTextFocus" 
    }
    ]
But it doesn't work.

**Comment by joaomoreno** [comment]
I don't think this is supported. You can, though, define a new command in an extension which simply calls two other commands. You can then assign a keybinding to that command.

**Comment by alexandrudima** [comment]
@foisonocean Is your intent to define a macro: e.g. Ctrl+/ should comment current line and move cursor to the next one?

**Comment by foisonocean** [comment]
@alexandrudima yes

**Comment by alexandrudima** [comment]
Even though #871 came up later, let's track this feature request in #871 (has more upvotes)
