### ISSUE TITLE
0/0 tests passed after test run

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#171019]
Type: <b>Bug</b>

After running all tests in VS Code (for the vscode repo), test view still says 0/0 passed

<img width="331" alt="image" src="https://user-images.githubusercontent.com/876920/211698459-602bb6ed-420a-4d81-92bd-525474ac75aa.png">

VS Code version: Code - Insiders 1.75.0-insider (Universal) (04b15ff231a2c3cfcdd90d90c16075a9c1e6da15, 2023-01-09T05:30:04.983Z)
OS version: Darwin x64 22.2.0
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|4, 4, 5|
|Memory (System)|32.00GB (0.10GB free)|
|Process Argv|--enable-proposed-api ms-vscode.vscode-notebook-history --enable-proposed-api vscode.notebook-editing --enable-proposed-api vscode.vscode-test-resolver --enable-proposed-api donjayamanne.kusto --enable-proposed-api donjayamanne.jupyterpowertools --enable-proposed-api rebornix.better-jupyter-errors --enable-proposed-api rchiodo.jupyter-tools --crash-reporter-id 1a907bbd-fa02-4595-81e0-63e1648afb31|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (94)</summary>

Extension|Author (truncated)|Version
---|---|---
tsl-problem-matcher|amo|0.6.2
comment-tagged-templates|bie|0.3.1
github-markdown-preview|bie|0.3.0
markdown-emoji|bie|0.3.0
markdown-footnotes|bie|0.1.1
markdown-mermaid|bie|1.17.3
markdown-preview-github-styles|bie|1.0.1
vscode-github-actions|csc|0.24.4
vscode-svgviewer|css|2.0.0
vscode-eslint|dba|2.2.6
prettier-java|dot|0.1.1
gitlens|eam|13.2.0
EditorConfig|Edi|0.16.4
vscode-npm-script|eg2|0.3.29
prettier-vscode|esb|9.10.3
codespaces|Git|1.13.5
copilot|Git|1.65.7705
remotehub|Git|0.48.0
vscode-pull-request-github|Git|0.56.0
go|gol|0.37.0
vscode-graphql|Gra|0.8.4
vscode-graphql-syntax|Gra|1.0.5
vscode-mocha-test-adapter|hbe|2.14.1
vscode-test-explorer|hbe|2.21.1
vscode-drawio|hed|1.6.4
handydandy-notebook|jak|0.1.4
beancount|Len|0.9.1
container-jupyter-server-provider|mic|0.0.1
fluent-icons|mig|0.0.18
vscode-fluent-icons|mig|0.0.1
theme-monokai-pro-vscode|mon|1.2.0
vscode-azurefunctions|ms-|1.9.0
vscode-azureresourcegroups|ms-|0.5.6
vscode-azurestaticwebapps|ms-|0.11.3
vscode-docker|ms-|1.23.3
vscode-language-pack-qps-ploc|MS-|1.75.12280922
vscode-language-pack-zh-hans|MS-|1.75.12280919
csharp|ms-|1.25.2
isort|ms-|2022.8.0
python|ms-|2023.1.10101015
vscode-pylance|ms-|2023.1.11
jupyter|ms-|2023.1.2000102234
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.12
notebook-renderers|ms-|0.0.1
vscode-jupyter-cell-tags|ms-|0.1.6
vscode-jupyter-slideshow|ms-|0.1.5
remote-containers|ms-|0.269.0
remote-ssh|ms-|0.95.2023010915
remote-ssh-edit|ms-|0.84.0
azure-account|ms-|0.11.2
azure-repos|ms-|0.24.0
hexeditor|ms-|1.9.9
js-debug-nightly|ms-|2023.1.917
live-server|ms-|0.5.2023010901
powershell-preview|ms-|2023.1.0
remote-explorer|ms-|0.1.2023010209
remote-repositories|ms-|0.26.0
test-adapter-converter|ms-|0.1.6
vscode-github-issue-notebooks|ms-|0.0.128
vscode-js-profile-flame|ms-|1.0.5
vscode-markdown-notebook|ms-|0.0.26
vscode-notebook-history|ms-|0.0.1
vscode-selfhost-test-provider|ms-|0.3.11
vscode-typescript-tslint-plugin|ms-|1.3.4
vsliveshare|ms-|1.0.5797
debugger-for-chrome|msj|4.13.0
vetur|oct|0.36.1
excalidraw-editor|pom|3.3.4
geo-data-viewer|Ran|2.6.0
better-jupyter-errors|reb|0.0.1
toggle|reb|0.0.2
typing-practice|reb|0.0.1
vscode-chat-iw|reb|0.0.1
vscode-code-renderer|reb|0.0.2
java|red|1.13.0
vscode-xml|red|0.23.0
kuskus-extensions-pack|ros|1.0.10
kuskus-kusto-language-server|ros|1.0.31
kuskus-kusto-syntax-highlighting|ros|1.1.21
vsc-nwjs|rua|1.0.18
swift-lang|ssw|0.10.0
tldraw-vscode|tld|1.25.2
luna-paint|Tyr|0.16.0
sourcekit-lsp|unp|0.0.1
vscode-lldb|vad|1.8.1
vscode-swiftlint|vkn|1.8.1
vscode-java-debug|vsc|0.47.0
vscode-java-dependency|vsc|0.21.1
vscode-java-pack|vsc|0.25.7
vscode-java-test|vsc|0.37.1
vscode-maven|vsc|0.40.3
notebook-editing|vsc|1.0.0
vscode-test-resolver|vsc|0.0.1

(7 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30422396
pythontb:30258533
pythonptprofiler:30281269
vsdfh931cf:30280410
vshan820:30294714
pythondataviewer:30285072
vscod805:30301674
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30404738
cppdebug:30492333
vsclangdf:30492506
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30618038
pylantcb52:30590116
pyindex848:30611229
nodejswelcome1:30587009
pyind779:30611226
pythonsymbol12cf:30622697
fim-prod:30623723

```

</details>

**Comment by MmAaXx500** [comment]
It's fixed in 1.75.1. See #173014
