### ISSUE TITLE
Extension host eating insane amounts of memory - how to debug?

### ISSUE THREAD

**Issue by CherryDT** [microsoft/vscode#171017]
Type: <b>Bug</b>

I noticed that there is a `node` process in WSL1 which is eating insane amounts of memory (7 GB). This seems to be the extension host. I would like to understand why this is the case and how to debug it, for example how I can get a heap snapshot?

Also, this is new, I definitely didn't have this issue a few weeks ago.

`top` output:

![image](https://user-images.githubusercontent.com/6010463/211687858-c1d098dd-af1a-48b6-a03e-201f0c1da616.png)

Performance graph in Process Hacker:

![image](https://user-images.githubusercontent.com/6010463/211687885-3f3b8813-0dff-4c62-8133-0200ca14e0dc.png)

VS Code version: Code 1.74.3 (97dec172d3256f8ca4bfb2143f3f76b503ca0534, 2023-01-09T16:59:02.252Z)
OS version: Windows_NT x64 10.0.19045
Modes:
Sandboxed: No
Remote OS version: Linux x64 4.4.0-19041-Microsoft
Remote OS version: Linux x64 4.4.0-19041-Microsoft

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 PRO 4750U with Radeon Graphics (16 x 1697)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.23GB (0.36GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-20.04|
|OS|Linux x64 4.4.0-19041-Microsoft|
|CPUs|AMD Ryzen 7 PRO 4750U with Radeon Graphics (16 x 1700)|
|Memory (System)|31.23GB (0.34GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-20.04|
|OS|Linux x64 4.4.0-19041-Microsoft|
|CPUs|AMD Ryzen 7 PRO 4750U with Radeon Graphics (16 x 1700)|
|Memory (System)|31.23GB (0.34GB free)|
|VM|0%|
</details><details><summary>Extensions (64)</summary>

Extension|Author (truncated)|Version
---|---|---
auto-close-tag|for|0.5.14
vscode-graphql-syntax|Gra|1.0.5
dotenv|mik|1.0.1
vscode-aql|mon|1.7.0
jupyter-keymap|ms-|1.0.0
remote-containers|ms-|0.266.1
remote-ssh|ms-|0.94.0
remote-ssh-edit|ms-|0.84.0
remote-wsl|ms-|0.72.0
remote-explorer|ms-|0.0.3
ejs-language-support|Qas|0.0.1
vscode-todo-highlight|way|1.0.5
vscode-devdocs|akf|1.0.3
svelte-intellisense|ard|0.7.1
vscode-intelephense-client|bme|1.9.3
npm-intellisense|chr|1.4.4
js-codeformer|cms|2.6.1
compulim-vscode-closetag|Com|1.2.0
vscode-eslint|dba|2.2.6
devdocs|dei|0.2.0
vscode-new-file|dku|4.0.2
dbux-code|Dom|0.7.9
xml|Dot|2.5.1
EditorConfig|Edi|0.16.4
copilot|Git|1.65.7705
vscode-graphql-execution|Gra|0.1.6
vscode-graphql-syntax|Gra|1.0.5
vscode-git-blamer|how|1.1.2
join-comment-aware|joh|0.0.3
solidity|Jua|0.0.141
edge|luo|0.3.2
rainbow-csv|mec|3.5.0
csharp|ms-|1.25.2
vscode-dotnet-runtime|ms-|1.6.0
isort|ms-|2022.8.0
python|ms-|2022.20.1
vscode-pylance|ms-|2023.1.10
jupyter|ms-|2022.11.1003412109
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.12
vscode-jupyter-cell-tags|ms-|0.1.6
vscode-jupyter-slideshow|ms-|0.1.5
cpptools|ms-|1.13.9
hexeditor|ms-|1.9.9
hexeditor|not|1.8.2
vscode-print|pdc|0.10.20
svelte-extractor|pro|0.0.3
vscode-data-preview|Ran|2.3.0
vscode-data-table|Ran|1.12.0
vscode-yaml|red|1.11.0
ActiveFileInStatusBar|Ros|1.0.3
vscode-paste-and-indent|Rub|0.0.8
bracket-jumper|sas|1.1.8
trailing-spaces|sha|0.4.1
vscode-standard|sta|2.1.3
runme|sta|0.4.2
ignore-gitignore|stu|1.0.1
svelte-vscode|sve|107.0.1
es6-string-html|Tob|2.12.0
sort-lines|Tyr|1.9.1
use-strict-everywhere|vee|0.1.3
bracket-padder|via|0.3.0
change-case|wma|1.0.0
html-css-class-completion|Zig|1.20.0

</details>

**Comment by roblourens** [comment]
Here are some tips for analyzing these issues: https://github.com/microsoft/vscode/wiki/Performance-Issues

But the easiest first step would be to figure out which extension is doing this. You can disable extensions or use the "Extension Bisect" command to figure it out

**Comment by CherryDT** [comment]
Thanks, Extension Bisect was helpful and identified `stateful.runme` as culprit. [I opened an issue there.](https://github.com/stateful/runme/issues/99)
