### ISSUE TITLE
integrated powershell hangs in 'activating extensions'

### ISSUE THREAD

**Issue by mdavid01** [microsoft/vscode#171054]
Type: <b>Bug</b>

integrated powershell hangs in 'activating extensions'.  tried updating vscode, tried rebooting.  pwsh.exe works fine.

VS Code version: Code 1.74.3 (97dec172d3256f8ca4bfb2143f3f76b503ca0534, 2023-01-09T16:59:02.252Z)
OS version: Windows_NT x64 10.0.19044
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz (8 x 2995)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.25GB (21.04GB free)|
|Process Argv|--crash-reporter-id b634c4b0-8796-48a2-8242-f019affd5e59|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
remote-ssh|ms-|0.94.0
remote-ssh-edit|ms-|0.84.0
powershell|ms-|2022.12.1
remote-explorer|ms-|0.0.3

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
azure-dev_surveyone:30548225
pyindex848:30577860
nodejswelcome1cf:30587006
3biah626:30602489
3d0df643:30613357
f6dab269:30613381
fim-prod:30623723
vscsbc:30628655

```

</details>

**Comment by Tyriar** [comment]
Please provide a screenshot or [a gif](https://gifcap.dev/) illustrating the problem (attaching images won't work via email, you need to go to github.com). See [this wiki page](https://github.com/microsoft/vscode/wiki/Terminal-Issues) for more general info on how to report actionable terminal issues.

/label "info-needed" terminal

**Comment by mdavid01** [comment]
Thanks, Daniel for your quick response.  Turns out that the order of PSModule path is relevant.  Below is the order that fixed my issue.  I believe the problem was when PS5.1 modules (%SystemRoot%\system32\WindowsPowerShell\v1.0\Modules) were first.  I did not see any documentation on this.  Hope I didn’t just miss it.  I would recommend automating a check and at least pop a warning about the order; better yet, automate the correct order.

%ProgramFiles%\PowerShell\Modules
%ProgramFiles%\WindowsPowerShell\Modules
%SystemRoot%\system32\WindowsPowerShell\v1.0\Modules

Please close Issue #171054.
