### ISSUE TITLE
[Help] Any example of an editor extension with rich custom UI.

### ISSUE THREAD

**Issue by SukantGujar** [Microsoft/vscode#17101]
Hi,

I am working on a nodejs based product where we have some json files which represent business flows. We want to write rich editors to allow developers to quickly edit these files without messing around with the raw JSON. I was looking for examples of such extensions in the market place but the closest ones I found were around previewing binary media, like SVGs or images. Could anyone point me in the right direction?

Thanks!

**Comment by kieferrm** [comment]
Checkout: https://github.com/Microsoft/vscode-extension-samples/tree/master/previewhtml-sample

**Comment by SukantGujar** [comment]
Thanks @kieferrm. This and a few others are basically rich views of the JSON. As the editor would need to be able to change the source code, would the recommended approach be to directly change the source json from it, or would that need to be done through other VS Code APIs?

**Comment by kieferrm** [comment]
You can use TextEditor.edit to make the changes to the json file.
