### ISSUE TITLE
Provide a list of deduped and nicely names codicons for use in product

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#171076]
The terminal has a feature to change the tab/profile icon which opens this:

<img width="339" alt="image" src="https://user-images.githubusercontent.com/2193314/211871176-d86594d3-f44a-482f-a3ce-8b4b7979a89c.png">

It's very convenient to use but it would be nicer if it was instead:

```
➕ Add - add
💡 Lightbulb - lightbulb
etc.
```

The `- text` above would be the greyed out backing id.

_User_ profiles could also use this as @sandy081 has explored.

**Comment by isidorn** [comment]
Also would it be possible to add the list of icons of the most common languages to our Codicons?
I know @chrisdias wanted to use a Python icon for his "Python 101" profile. And I think that makes sense.

**Comment by aeschli** [comment]
While the Codicons offers a quick way to get a nice selection of icons, I think not all of the ids are useful and well chosen.
What about having a curated list of the ones that are meaningful in the context of terminal/user profile?
That allows you to add descriptions as well.

If you want to allow that extensions can contribute new icons, use the iconRegistry (IIconRegistry) instead. Have a name convention for your icons so you can also pick up contributed icons.

`registerIcon('terminal-viewicon-cloud', Codicon.cloud, 'Cloud') ...

**Comment by daviddossett** [comment]
It may also be nice to allow for emojis as well. Although I think at one point this was possible?

**Comment by Tyriar** [comment]
@daviddossett emoji can be used where text is used, I dislike when extensions do this though as they're the only non-monochrome icons in the UI and stand out like a sore thumb. For example: https://github.com/MicrosoftDocs/live-share/issues/4185

**Comment by sandy081** [comment]
This is done by @hbons here - https://github.com/microsoft/vscode/issues/188972

Hence closing this.

**Comment by Tyriar** [comment]
This should be closed when it's compatible with the terminal (no debian, ubuntu, etc.?) and it's adopted in the terminal icon picker.

**Comment by aeschli** [comment]
[I suggest](https://github.com/microsoft/vscode/issues/171076#issuecomment-1381836136) to have a curated list of icons.
Register these icons with:
`registerIcon('terminal-viewicon-cloud', Codicon.cloud, 'Cloud') ...`
Pick the icons that seem useful in the context of terminal, and give them a good description
- use a name convention for the icons you show, e.g. all the ones that start with `terminal-`. Extensions that contribute icons can also use that name conventions so they show up in your icon picker.
- that's the way all components should use icons. Define a component specific icon name, allows theme authors to individually design icons for each component. E.g some theme could decide to give all terminal icons a certain look.

**Comment by Tyriar** [comment]
I used `iconRegistry.getIcons()` but the list wasn't deduped as expected:

```ts
		const iconRegistry = getIconRegistry();
		for (const icon of iconRegistry.getIcons()) {
			items.push({ label: `$(${icon.id}) ${icon.id}`, description: icon.description, icon });
		}
```

Gave:

![image](https://github.com/microsoft/vscode/assets/2193314/d9e111c6-c392-4dc8-8a50-3d0b55067b74)

Proof description is working:

![image](https://github.com/microsoft/vscode/assets/2193314/cb73433d-c55d-4850-9042-fdf52cbc77d1)
