### ISSUE TITLE
Panel title overflow does not have background hover feedback like other similar icons

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#171077]
![Recording 2023-01-11 at 09 12 01](https://user-images.githubusercontent.com/2193314/211871778-a661f3f5-3611-467d-932e-86aa62d67a8b.gif)

**Comment by benibenj** [comment]
I'm not sure about this idea. We don't have the background color for the view container icons so I don't think we should have it for the overflow. I think it makes sense for the overflow icon to align with the view icons/labels.

![Image](https://github.com/user-attachments/assets/3746b6ec-fe91-4904-a021-40e4548e6239)

Also FYI, this month we introduced icons in the panel title

![Image](https://github.com/user-attachments/assets/1f7557f4-f51b-4ef7-89ed-3cdb4441ef0a)

**Comment by sbatten** [comment]
I see where you come from @benibenj, but I think I agree with @Tyriar. The view icons/labels are all switching the view on click. The triple dot opens a menu, it is button, not a tab.
