### ISSUE TITLE
Waterfall startup sequence

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#17108]
The overall startup sequence from starting the main process to starting the renderer process is waterfall'ish, esp. since we don't just wait for the app to be ready but because we do many things before starting the renderer (which itself doesn't do anything else than loading code for the first 1 second). Let's identify what can run after or in parallel to getting the renderer ready. Also, I have created a benchmark, stripped down, electron app, which should set the baseline - we can't get faster but should strive to become as close as possible. 

The timings for a simple app (attached) are 

```
app,started: (absolute) 0ms, (relative) 0
app,ready: (absolute) 58ms, (relative) 58
mainWindow,created: (absolute) 90ms, (relative) 32
renderer,html: (absolute) 378ms, (relative) 288
```

VS Code (on my mac) takes ~750ms before loading the main window (compare to `mainWindow,created`) and ~1200ms before loading the big chunk of code (workbench.min.js, compare with `renderer,html`). That makes roughly 600ms that are spending somewhere. Since that is roughly the time it takes to load the main portion of our code, I wonder if those 600ms initialisation work can run in parallel, while we load the code of the workbench.

**Comment by jrieken** [comment]
The baseline electron app can be found here: https://github.com/jrieken/electron-startup-perf-baseline

**Comment by jrieken** [comment]
related to https://github.com/Microsoft/vscode/issues/15455

**Comment by joaomoreno** [comment]
Can you put the timings for vanilla vs code side-by-side on a table, along with their relative difference? Makes it easy to reason about things.

**Comment by jrieken** [comment]
It's two numbers:

 -- | from start to loadURL (absolute) | from start to index.html (absolute)
--|---------------------------------|------------------------------------
vanilla | 90ms | 378ms
vs code | 750ms | 1200ms

**Comment by jrieken** [comment]
The following are some operation we perform that take long, like spawning a process or listening on a port

- [ ] [`getHttpCommonHeaders`](https://github.com/Microsoft/vscode/blob/master/src/vs/code/electron-main/window.ts#L211) will eventually reach into `getmac` which execs a process blocking for ~15ms, depending on virus scanners longer
- [ ] [spawning the shared process](https://github.com/Microsoft/vscode/blob/master/src/vs/code/electron-main/main.ts#L152), like above is blocking for some millis
- [ ] [`setupIPC`](https://github.com/Microsoft/vscode/blob/master/src/vs/code/electron-main/main.ts#L268) takes ~5ms for starting to listen

**Comment by bpasero** [comment]
Would it not be possible to wait creating the shared process until the first window is loading? All shared process related methods are promises anyways and it seems ok to wait until a window is visible.

Now that we look into moving the shared process into a real Electron window, I fear that startup would even get slower compared to just spawning a process.

For the setJumpList call, I simply wait for the first window via `win.webContents.on('did-start-loading',...)`

**Comment by jrieken** [comment]
Yes - we are moving the shared process into a browser window to begin with and should then also be able to make it after the first, user-windows started loading: #22091

**Comment by jrieken** [comment]
fyi - I have moved waiting for the ready-state into the `main.ts` such that we at least load the loader and code while waiting

**Comment by jens1o** [comment]
is there any further progress here @jrieken since you apparently started working on it?

**Comment by joaomoreno** [comment]
I've changed the `getCommonHttpHeaders` thing to simply use a UUID which we store after generating it. Getmac won't be called anymore. Unfortunately this is still happening on startup in a sync fashion. The reason for this is that we don't have an atomic storage mechanism across all processes. If we don't generate it sync on startup, we might have 2 processes generating 2 different UUIDs. The mitigation for this is to use a single `machineid` file for this in user data. This will make reading and writing to this file extremely fast.

--- 

@jrieken `setupIPC` is a hard nut to make faster. We use sockets/named pipes to make sure we don't execute two instances at the same time. Do you know of anything else that has the same atomic properties yet is faster?

**Comment by jrieken** [comment]
> Do you know of anything else that has the same atomic properties yet is faster?

Yeah, no real clue. The good news is that I haven't seen it take much longer on other machines. So in contrast to launching (part of getmac) which can take a second on some machines this seems to be more or less constant. Ok for me to leave it as is

**Comment by joaomoreno** [comment]
Cool, let's close it!
