### ISSUE TITLE
After completing a word the first intellisense completion isn't selected

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#171086]
This is in a simple launch.json, I expect enter, enter or enter, tab to complete the top entry.

![Recording 2023-01-11 at 10 49 21](https://user-images.githubusercontent.com/2193314/211892575-dd29df23-5653-4feb-9988-adc1fb2c56cb.gif)

Version: 1.75.0-insider (user setup)
Commit: 89e427274e1c9e555f8bfa21bd1e9c50c0225403
Date: 2023-01-11T16:42:24.636Z
Electron: 19.1.9
Chromium: 102.0.5005.194
Node.js: 16.14.2
V8: 10.2.154.23-electron.0
OS: Windows_NT x64 10.0.22621
Sandboxed: Yes

**Comment by jrieken** [comment]
please share your settings, esp check for `editor.suggest.selectionMode`

**Comment by Tyriar** [comment]
I have a ~500 line settings file, but when I comment it all out (so using the defaults) then the behavior is the same. I also see I have  `"editor.suggestSelection": "first"` explicitly set fwiw.

**Comment by Tyriar** [comment]
1.74.2:

![Recording 2023-01-12 at 08 12 24](https://user-images.githubusercontent.com/2193314/212120649-6b3aa917-a884-4ab2-b714-46b230520d0e.gif)

Insiders:

![Recording 2023-01-12 at 08 13 14](https://user-images.githubusercontent.com/2193314/212120850-044852ea-259d-4ee9-9e4b-13ccd796ad59.gif)

**Comment by jrieken** [comment]
https://user-images.githubusercontent.com/1794099/212122285-c97f6009-a077-4170-8831-a5a321e351ab.mov

**Comment by Tyriar** [comment]
@jrieken try completing a key in launch.json specifically

**Comment by jrieken** [comment]
oh, so steps are

* open launch.json
* trigger suggest for `console`
* snippet mode is engaged, suggest is **re**triggered, but not selected


So, this is actually on purpose and a recent addition to tackle the issue that `Tab` accepts completions _and_ advances tab to the next tab stop. 


Do you have `editor.suggest.snippetsPreventQuickSuggestions` configured?

**Comment by Tyriar** [comment]
Setting that to false fixes my problem. I think this snippet only has a single tab stop so should it act differently in that case?

**Comment by jrieken** [comment]
> I think this snippet only has a single tab stop so should it act differently in that case?

It's usually two tabstops the "actual" stop and the final placeholder which terminates snippet mode

**Comment by Tyriar** [comment]
👌 feel free to close if it's as designed as my issue is fixed, this is feedback that it felt like a bug to me though.

**Comment by jrieken** [comment]
Yeah, closing but keeping on 👂 open because I have only changed this during the current milestone
