### ISSUE TITLE
Pick icon list is raw and should be de-duplicated

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#171089]
As pointed out by @daviddossett the Pick Icon flow for profiles is very raw. Could we:
* De-duplicate entries with same icon
* Show user friendly names of icons

Terminal has the same issue. fyi @Tyriar @meganrogge 

![Screenshot 2023-01-11 at 20 07 49](https://user-images.githubusercontent.com/1926584/211896175-9632dc45-f86a-40ad-96d7-6ad89ba2a497.png)

**Comment by Tyriar** [comment]
Beat you to it 🙂 

/duplicate https://github.com/microsoft/vscode/issues/171076

**Comment by isidorn** [comment]
You de-duped my issue about de-duping 😄
