### ISSUE TITLE
getting blur and white lines

### ISSUE THREAD

**Issue by Gnanashritej** [microsoft/vscode#171079]
Type: <b>Bug</b>

the visual studio code on my laptop is getting blur and it is filling with white lines suddenly and it's not the fault of my machine i have checked with all tht other applications please check it and provide me a valid solution.

VS Code version: Code 1.74.3 (97dec172d3256f8ca4bfb2143f3f76b503ca0534, 2023-01-09T16:59:02.252Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz (16 x 2304)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.71GB (9.12GB free)|
|Process Argv|--crash-reporter-id 248c418b-aaa8-48d9-8c27-a68fa802a4f7|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (34)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
lua-debug|act|1.61.0
vscode-sql-beautify|cla|0.3.16
vscode-html-css|ecm|1.13.1
prettier-vscode|esb|9.10.3
vscode-dotnet-runtime|ms-|1.6.0
data-workspace-vscode|ms-|0.3.0
mssql|ms-|1.16.0
sql-bindings-vscode|ms-|0.3.0
sql-database-projects-vscode|ms-|0.19.0
isort|ms-|2022.8.0
python|ms-|2022.20.1
vscode-pylance|ms-|2023.1.10
jupyter|ms-|2022.11.1003412109
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.12
vscode-jupyter-cell-tags|ms-|0.1.6
vscode-jupyter-slideshow|ms-|0.1.5
sqltools|mtx|0.27.1
oracledevtools|Ora|21.5.0
java|red|1.13.0
LiveServer|rit|5.7.9
vscode-sql-beautify|sen|0.0.4
intellicode-api-usage-examples|Vis|0.2.6
vscodeintellicode|Vis|1.2.30
vscode-java-debug|vsc|0.47.0
vscode-java-dependency|vsc|0.21.1
vscode-java-pack|vsc|0.25.7
vscode-java-test|vsc|0.37.1
vscode-maven|vsc|0.40.3
php-debug|xde|1.30.0
plsql-language|xyz|1.8.2
luahelper|yin|0.2.19
plsql-debug|zer|1.0.8

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
azure-dev_surveyone:30548225
pyindex848:30577860
nodejswelcome1:30587005
3biah626:30602489
3d0df643:30613357
f6dab269:30613381
fim-prod:30623723

```

</details>

**Comment by rzhao271** [comment]
Hi, does running `code --disable-gpu` from the terminal help?
Also, did this issue just appear, or was it there in previous versions?

**Comment by Gnanashritej** [comment]
I had fixed it with using compatibility by using previous versions
It was working fine with windows 8 compatibility
But not good in windows 11 22h2 version
Thank you so much for your fast response

**Comment by deepak1556** [comment]
Merging to https://github.com/microsoft/vscode/issues/124226

**Comment by Gnanashritej** [comment]
Now I have encountered a new problem by using compatibility mode now I
can't use the terminal in vscode editor please find the solution regarding
this issue and help me iam attaching a screenshot of my problem please help
me with the possible solution. Iam counting on you.
