### ISSUE TITLE
workbench.action.terminal.copyLastCommand Copies output of last command rather than last command

### ISSUE THREAD

**Issue by djpaidev** [microsoft/vscode#171073]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.74.3
- OS Version: macOS 12.2

Steps to Reproduce:

1. Run workbench.action.terminal.copyLastCommand
2. Paste

**Comment by meganrogge** [comment]
The bug is that this function is named incorrectly - it should be `Copy Last Command Output`
![Screenshot 2023-01-11 at 4 05 59 PM](https://user-images.githubusercontent.com/29464607/211927953-4a73baf5-e968-4098-bbd1-cd59bb2ed353.png)

**Comment by dhananjaipai** [comment]
Wow, that was super fast!
Thanks for confirming. Since I have a lot of customizations on my shell, was half confused about whether it was an error because of my setup.

**Comment by meganrogge** [comment]
No, but that's likely a windows issue that we cannot fix, correct @tyriar?

**Comment by Tyriar** [comment]
Yes it may copy the prompt as well on Windows, this will be fixed eventually from an upstream fix in conpty.
