### ISSUE TITLE
after installing or upgrading extension(s) open explorer viewlet on restart

### ISSUE THREAD

**Issue by chrisdias** [Microsoft/vscode#17102]
Most (all?) of the time when I restart VS Code after installing or updating an extension, I don't want the extension viewlet open on restart.

My mental model is that I've discovered and installed all of the extensions I'm interested in and upon restart I want to start using them. I want to start opening files (e.g. a Dockerfile after installing DockerSupport) and rarely do I want to search for new extensions or mange the existing ones.

I suggest that upon restart after installing/updating an extension that we go back to the Explorer view.

**Comment by bpasero** [comment]
@chrisdias please see https://github.com/Microsoft/vscode/issues/8269
