### ISSUE TITLE
Performance problem

### ISSUE THREAD

**Issue by Ghassen-bgh** [microsoft/vscode#171043]
Type: <b>Performance Issue</b>

Vscode is using 100% of the cpu and 81% of ram

VS Code version: Code 1.74.3 (97dec172d3256f8ca4bfb2143f3f76b503ca0534, 2023-01-09T16:59:02.252Z)
OS version: Windows_NT x64 10.0.25267
Modes:
Sandboxed: No

<details>
<summary>Process Info</summary>

```
undefined
```

</details>
<details>
<summary>Workspace Info</summary>

```
undefined;
```

</details>
Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vscaat:30438848
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
azure-dev_surveyone:30548225
pyindex848cf:30577861
nodejswelcome1:30587005
282f8724:30602487
3d0df643:30613357
89544117:30613380
fim-prod:30623723

```

</details>

**Comment by Tyriar** [comment]
It looks like the process info didn't come through:

<img width="107" alt="image" src="https://user-images.githubusercontent.com/2193314/211806035-344e3cb9-6aa5-4768-9909-da5788cad027.png">

We need that to see which process is the issue, if it's the "extension host" it's likely an extension that is causing the problem.
