### ISSUE TITLE
local host - 3000 not connected to my program

### ISSUE THREAD

**Issue by zozonono** [microsoft/vscode#171006]
ADD ISSUE DESCRIPTION HERE

Version: 1.74.3
Commit: 97dec172d3256f8ca4bfb2143f3f76b503ca0534
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.0 Safari/605.1.15
Embedder: codespaces

**Comment by zozonono** [comment]
found the solution

**Comment by jahuarcristian** [comment]
Ok
