### ISSUE TITLE
Support auto detect of file encoding

### ISSUE THREAD

**Issue by mohusheng** [Microsoft/vscode#17109]
- VSCode Version: 1.7.2
- OS Version: 6.1.7601

**Comment by mohusheng** [comment]
My project mix gbk and utf8 encoding files, so it need support ["files.encoding": "auto"], no just ["files.encoding": "utf8"] or ["files.encoding": "gbk"].

**Comment by kieferrm** [comment]
One alternative would be that we remember the encoding a file has been opened before. I.e. when the user chooses `Change File Encoding` > `Reopen with Encoding` from the command palette we use the same encoding when the file is opened again.

**Comment by visitantz** [comment]
Support this request, it's indeed annoying, usually web related files are utf-8 encoding, windows platform files are local encoding, so "files.encoding" setting is not helping at all, you still need to manually set half files each time.

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/5388
