### ISSUE TITLE
Double red diff decoration

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#17104]
Notice how when a line is deleted, the red decoration appears stronger, but only after the line number. While when a line is simply modified, the red decoration is OK.

![image](https://cloud.githubusercontent.com/assets/22350/21133832/2110ad0c-c11b-11e6-990a-cec4c8d679aa.png)

**Comment by joaomoreno** [comment]
Oh, this is as expected:

![Uploading image.png…]()
