### ISSUE TITLE
Sort order of branches in the quick pick is incorrect

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode#171015]
Does this issue occur when all extensions are disabled?: Yes/No

- Version: 1.75.0-insider (Universal)
- Commit: e7b5449579249db344d473370d56a5df9446c826
- Date: 2023-01-10T05:21:34.436Z
- Electron: 19.1.9
- Chromium: 102.0.5005.194
- Node.js: 16.14.2
- V8: 10.2.154.23-electron.0
- OS: Darwin arm64 22.2.0
- Sandboxed: Yes

Steps to Reproduce:

1. Open an existing workspace folder with git
2. create a few branches with commits
3. attempt to switch branches
4. the list of branches does not display the recent branches on top
5. Open the same workspace folder in vscode stable and the order is as expected

**Comment by bpasero** [comment]
💯
