### ISSUE TITLE
Settings UI looks bad in a few themes

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#17103]
Tomorrown Night Blue:

![image](https://cloud.githubusercontent.com/assets/22350/21133221/1f5659f6-c118-11e6-8599-abaac285836b.png)

- We should remove the background colors from the input box container and section headers
- We should inline the result summary inside the search text box, aligned to the right

**Comment by sandy081** [comment]
@bgashler1 With latest changes of moving Search bar to complete editor and after suggestions from @joaomoreno Settings editor looks as below in different themes

![image](https://cloud.githubusercontent.com/assets/10746682/21726894/ff40ba3c-d43e-11e6-822b-3ffbdd5d5719.png)

![image](https://cloud.githubusercontent.com/assets/10746682/21726904/0aacf6ce-d43f-11e6-9812-3264e1e57f94.png)

![image](https://cloud.githubusercontent.com/assets/10746682/21726883/eeeb949a-d43e-11e6-938f-9967b6e5d505.png)

What do you think?

**Comment by bgashler1** [comment]
@sandy081 I love that the results are in the search bar.  Also, I like that it looks better now in different themes.

**Comment by bpasero** [comment]
There is still some ugly grey e.g. when hovering over a section:

![image](https://cloud.githubusercontent.com/assets/900690/22335376/c8359a44-e3de-11e6-940e-4dbbb0707361.png)

I think the original issue though was that we would always show section background color.

**Comment by sandy081** [comment]
Agreed that section background color does not look good for some themes. But I think, it is difficult to get a color that goes well with all themes . Or we can completely remove the background color for section headers. But that might not be consistent with our tree UI.

**Comment by joaomoreno** [comment]
Have you tried simple grey with various degrees of opacity? It goes a long way. 👍

**Comment by sandy081** [comment]
No. Will try

**Comment by bpasero** [comment]
Same is true for our text input fields in Problems view and Preferences.

**Comment by aeschli** [comment]
Created #19519 & #19520 to mark as verified.
