### ISSUE TITLE
Opening a new folder should use the current profile

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#171087]
I know I suggested https://github.com/microsoft/vscode/issues/169260 but after trying it out I am convinced that was a wrong suggestion. I think we should just revert it, and whenever we open a new folder it should be using the CURRENT profile.

I know @bpasero and @chrisdias feel the same.

**Comment by sandy081** [comment]
Lets discuss this!

**Comment by sandy081** [comment]
Actually I liked this behaviour too. Reverted this after our discussion. Bringing this back now :)

**Comment by isidorn** [comment]
Awesome - thanks!

**Comment by mirao** [comment]
Is it possible to associate a workspace (or folder) with a profile?
E.g. can I set that if I open a workspace (or folder) "A", current profile will be switched to "Default" and if I open a workspace "B", current profile will be switched to "Work"?

**Comment by mirao** [comment]
> Is it possible to associate a workspace (or folder) with a profile?

Well, it seems to be already working: #167513
