### ISSUE TITLE
feature request: remote edit browser for linux

### ISSUE THREAD

**Issue by rosrad** [Microsoft/vscode#17100]
hi guys
I just want to post a feature request .
since always we need to debug or edit some code on linux server,
but we can not got a x-window gui sometime, can only login under tty (console).
and edit my code with vim /emacs.  
as I know, vscode is based browser render, is this possible to run vscode service on linux, and render/edit operations under remote desktop(such as windows, mac).

thanks.

**Comment by kieferrm** [comment]
//cc @egamma

**Comment by jheiselman** [comment]
Something similar to Zed (http://zedapp.org) would be nice. It contains a small binary that you can run on your server that your local editor will connect to so you can edit files. This solution is nice in cases where the user I can SSH as is not the same as the owner of the files. The file owner can run the daemon to avoid permission problems.

**Comment by netheril96** [comment]
Many people these days code on servers, and none of the fancy IDEs or editors work reliably over remotes. This could be the definitive advantage of vs code, in addition to shutting up everyone who thinks it is overkill to bring a browser shell for an editor.

**Comment by batobolg** [comment]
we need remote editing why not ?
