### ISSUE TITLE
Vertical gap in output in terminal

### ISSUE THREAD

**Issue by GlitchgodGG** [microsoft/vscode#171055]
![Screenshot 2022-10-27 211211](https://user-images.githubusercontent.com/115570727/211798899-a1b5e843-1c7d-4752-b78a-b660e1b21f83.png)
![Screenshot 2022-10-29 235252](https://user-images.githubusercontent.com/115570727/211798905-29413e85-bb37-427b-8660-a97ccf4ab5ea.png)

- VS Code Version: 1.73.1
- OS Version: Windows 11

There is a vertical gap in the output in terminal code when I selected delete previous output setting for code runner as I want to delete the previous output every time a run a code. It works fine when this setting is turned off but after turning it on there is a gap of a few lines in the terminal before I can enter the input for my code.

**Comment by meganrogge** [comment]
> when I selected delete previous output setting for code runner 

this sounds like an extension issue, pls file an issue for the appropriate extension
