### ISSUE TITLE
error: Cannot read properties of undefined (reading 'id')

### ISSUE THREAD

**Issue by shawnfeng0** [microsoft/vscode#171070]
When I click the `SYNC` button of `SYNC ACTIVITY (LOCAL)`, an error pops up:
![image](https://user-images.githubusercontent.com/23150404/211835919-6c27f2c9-40e5-4e07-9fb5-79a0ddf55b38.png)

Information about my vscode version:
![image](https://user-images.githubusercontent.com/23150404/211836255-c21e63cc-d4c6-4106-a6bb-e6bbc45a59e3.png)
Version: 1.74.3
Commit: 97dec172d3256f8ca4bfb2143f3f76b503ca0534
Date: 2023-01-09T16:57:40.428Z
Electron: 19.1.8
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Linux x64 6.1.1-1-MANJARO
Sandboxed: No

**Comment by Aharito** [comment]
I have the exact same error. But I have VSCode installed as Portable on Win 10.

Version: 1.74.3
Commit: 97dec172d3256f8ca4bfb2143f3f76b503ca0534
Date: 2023-01-09T16:59:02.252Z
Electron: 19.1.8
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.19044
Sandboxed: No

**Comment by Aharito** [comment]
![image](https://user-images.githubusercontent.com/6253807/213377144-ec147f92-e11b-45a4-bf98-cdb3e8f3e8d3.png)
