### ISSUE TITLE
Preserve picked language for files across restarts

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#17115]
Steps to Reproduce:

1. open a file 
2. change its language to something else
3. close VS Code
4. re open

=> the selected language is back to default

**Comment by Alfrex92** [comment]
Are you planning to fix this bug soon?

**Comment by bpasero** [comment]
via https://github.com/microsoft/vscode/pull/73678

**Comment by bpasero** [comment]
**Verification**: open a file and change the language mode, reload and verify the language mode is still there.
