### ISSUE TITLE
Quick Open doesn't stay open

### ISSUE THREAD

**Issue by jtsom** [Microsoft/vscode#17114]
- VSCode Version: Version 1.8.0-insider (1.8.0-insider) (2abfc207828739bd5b10d0bb8dbfea13506cfc69)
- OS Version: OS X 10.12.1

Steps to Reproduce:

1. Hit Control-Q to open Quick Open
2. As soon as keys are released, Quick Open closes, so you can't select anything

Trying to hold down the Control Key then hitting the arrows, triggers the system function in my case of Mission Control

**Comment by bpasero** [comment]
Try setting `"workbench.quickOpen.closeOnFocusLost": false`

**Comment by jtsom** [comment]
Nope, sorry, that didn't make any difference. As soon as I release the keys the menu closes. And B. why would that be an option? If the menu auto closes so I can't pick anything, that doesn't sound very usable...

**Comment by jtsom** [comment]
And, this happens not on just OS X - Windows and Linux versions do the same thing.

**Comment by bpasero** [comment]
@jtsom Ctrl+Q is actually meant to close, what are you trying to open? Can you share your keybindings?

**Comment by jtsom** [comment]
I think the problem is I'm confusing the "Quick Open" with the new "View Picker". The release notes seemed to call it "Quick Open" - it was confusing as to what it was... I think it's doing the right thing? now that I know what I'm looking at... Thanks

**Comment by bpasero** [comment]
@jtsom all right, this setting I was talking about helps for quick open like pressing Ctrl+P
