### ISSUE TITLE
View is cut off and can't scroll

### ISSUE THREAD

**Issue by TylerLeonhardt** [microsoft/vscode#171142]
![image](https://user-images.githubusercontent.com/2644648/211972353-e3ba669b-f549-4cc0-824e-76430dd1a9c5.png)

I am unable to scroll to see the 2nd button under Export

**Comment by sandy081** [comment]
Can you please export this profile and share it with me so that I can repro?

**Comment by TylerLeonhardt** [comment]
Here you go: https://gist.github.com/TylerLeonhardt/400a96590f08deeb2314ec20a44acb5c
