### ISSUE TITLE
Copy files in VS Code

### ISSUE THREAD

**Issue by WellWells** [microsoft/vscode#171147]
Type: <b>Feature Request</b>

Hi, I'm Wells. Working in Linux kernel.
When I copy files from A directory to B directory in VSCode.
If the file exists, the default action is to append " copy.ext" to the end of the file.
Is it possible to ask the user what to do if the file exists?
Also, using "_copy" instead of " copy" (white space) reduces bugs in Linux...

VS Code version: Code 1.74.3 (97dec172d3256f8ca4bfb2143f3f76b503ca0534, 2023-01-09T16:59:02.252Z)
OS version: Windows_NT x64 10.0.19045
Modes:
Sandboxed: No
Remote OS version: Linux x64 4.4.0-210-generic

**Comment by gjsjohnmurray** [comment]
Did you investigate the `explorer.incrementalNaming` setting?

**Comment by WellWells** [comment]
I see, there is a simple/smart/disabled change to the naming behavior of pasted files.
Thanks you for helping me.
