### ISSUE TITLE
Code tunnel under WSL is unable to start using CLI

### ISSUE THREAD

**Issue by morkovka1337** [microsoft/vscode#171196]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 
Version: 1.74.3 (user setup)
Commit: 97dec172d3256f8ca4bfb2143f3f76b503ca0534
Date: 2023-01-09T16:59:02.252Z
Electron: 19.1.8
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.22000
Sandboxed: No
- OS Version: 
Windows 11 Pro 21H2 build 22000.1455, in WSL Ubuntu 18.04.5 LTS

Steps to Reproduce:

1. Start WSL
2. Try to start code tunnel under WSL via CLI

Instead of starting tunnel session, code opens new file named "tunnel". I've managed to start tunnel session via UI.
But when I connect to tunnel from the remote machine and run "code <any file\folder>", file\folder is opened on the host machine (where I start tunnel, let's call it server), not on the remote machine (client).

**Comment by connor4312** [comment]
For the moment, you need to manually [download](https://code.visualstudio.com/#alt-downloads) and run the Linux version of the CLI in WSL for tunnels to work there. However this is something that we're working on this month: https://github.com/microsoft/vscode-remote-release/issues/7783

**Comment by dsm-72** [comment]
@connor4312 any recommendations for place to put it?
