### ISSUE TITLE
Enable property to show unsaved(dirty) indicator for Webviews 

### ISSUE THREAD

**Issue by rangav** [microsoft/vscode#171157]
Can you please provide option in vscode api to show/hide unsaved/dirty indicator dot for webview, I am currently developing [Thunder Client ](https://marketplace.visualstudio.com/items?itemName=rangav.vscode-thunder-client)extesnion. This feature will be very useful to show the state of data on the webview.

![127617430-3b16f4b6-c5a1-477a-943d-660fe58ac307](https://user-images.githubusercontent.com/8637550/212050545-8b674e50-f677-40b7-aac3-5e3b44c03cb7.png)

I know its possible with Custom Editor, But for below reasons this feature will be useful for Webviews

- Enabling dirty indicator on Webviews gives developers more flexibility, to develop UI based extensions.
- And also Webviews are easier to use than Custom Editors in VSCode.

I have opened new issue as suggested by @isidorn in https://github.com/rangav/thunder-client-support/issues/958#issuecomment-1380132645

**Comment by mjbvz** [comment]
Sorry but you need to use a custom editor for this. We don't give extensions direct control over the dirty indicator because it can easily lead to confusing user experiences around saving files and potentially data loss. Custom editors are the solution for this

**Comment by rangav** [comment]
@mjbvz The users are already having bad experience with webviews as they is no way to show unsaved indicator.

You suggest to use Custom Editors, but I requested for example to use Custom Editor with Virtual Documents which is never provided?

I have feature request for that also 
https://github.com/microsoft/vscode-extension-samples/issues/477

@isidorn @mjbvz Either please provide a clear example how to use Custom Editor with virtual documents `OR` Enable dirty indicator in webview?
