### ISSUE TITLE
JS syntax highlight bug (division / regexp)

### ISSUE THREAD

**Issue by Inuart** [Microsoft/vscode#17111]
- VSCode Version: Code 1.7.2 (7ba55c5860b152d999dda59393ca3ebeb1b5c85f, 2016-11-21T22:01:10.756Z)
- OS Version: Darwin x64 16.1.0
---

Steps to Reproduce:

1. `let a = 1 / 2, b = 1 / 2;` syntax highlight works fine
2. `let a = 1 / 2, b = 1 / (2);` syntax highlight thinks it's a regexp

![image](https://cloud.githubusercontent.com/assets/441979/21138188/383e83ac-c12d-11e6-8235-4479319401a9.png)

**Comment by mjbvz** [comment]
I believe this has been fixed

<img width="297" alt="screen shot 2016-12-13 at 11 23 06 am" src="https://cloud.githubusercontent.com/assets/12821956/21155313/8ddfb77e-c126-11e6-9813-8f47231a78b7.png">

Please try out [the latest insiders builds](https://code.visualstudio.com/insiders) or VSCode 1.8 once is release and let us know if you still see this. 

Thanks
