### ISSUE TITLE
Expected Copy Link to be GH gist link

### ISSUE THREAD

**Issue by TylerLeonhardt** [microsoft/vscode#171192]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 
- OS Version: 

Steps to Reproduce:

1. Export a Profile as a GitHub Gist
2. Copy Link:
![image](https://user-images.githubusercontent.com/2644648/212148112-9aeb9759-6118-4b64-9a14-166b086a4f5c.png)

Here's what I get: `vscode-insiders://profile/github/52c822a931ffa00620641fcd49dbffad`
I was expecting the link: https://gist.github.com/TylerLeonhardt/52c822a931ffa00620641fcd49dbffad

**Comment by sandy081** [comment]
Expected. Copied link is the link that VS Code detects and shows import flow.

**Comment by TylerLeonhardt** [comment]
@sandy081 can the text call that out?

**Comment by sandy081** [comment]
Hmm may be. Any recommendations?
