### ISSUE TITLE
Allow specifying workspace-specific EnvironmentVariableCollection mutators

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#171173]
For example:

```ts
export interface EnvironmentVariableMutator {
	readonly type: EnvironmentVariableMutatorType;
	readonly value: string;
	readonly workspace: Workspace | undefined;
}

export interface EnvironmentVariableCollection extends Iterable<[variable: string, mutator: EnvironmentVariableMutator]> {
	replace(variable: string, value: string, workspace?: Workspace): void;
	append(variable: string, value: string, workspace?: Workspace): void;
	prepend(variable: string, value: string, workspace?: Workspace): void;
}
```

Context: https://github.com/microsoft/vscode-python/issues/20492#issuecomment-1380579731

**Comment by karrtikr** [comment]
Feedback from API sync:

As we anticipate we might need shell scoping as well in the future, use something similar to
```typescript
workspace.getConfiguration(section?: string, scope?: ConfigurationScope): WorkspaceConfiguration;
```
instead.

Updated proposal:

```typescript
export interface EnvironmentVariableMutator {
	readonly type: EnvironmentVariableMutatorType;
	readonly value: string;
	readonly scope: EnvironmentVariableScope | undefined;
}

export interface EnvironmentVariableCollection extends Iterable<[variable: string, mutator: EnvironmentVariableMutator]> {
	replace(variable: string, value: string, scope?: EnvironmentVariableScope): void;
	append(variable: string, value: string, scope?: EnvironmentVariableScope): void;
	prepend(variable: string, value: string, scope?: EnvironmentVariableScope): void;
}

export type EnvironmentVariableScope = { workspace?: Workspace };
```

One issue with this is that `readonly scope: EnvironmentVariableScope | undefined;` carries optional properties.

**Comment by Tyriar** [comment]
> One issue with this is that readonly scope: EnvironmentVariableScope | undefined; carries optional properties. Hence an alternative could be:

The required would need to be removed when we added a second one anyway, we can just treat `{}` and `{ workspaceFolder: undefined }` the same as `undefined`

**Comment by karrtikr** [comment]
Sorry what do you mean by the "second one"? Mostly I was trying to follow [Extension-API-guidelines](https://github.com/Microsoft/vscode/wiki/Extension-API-guidelines#optional-properties--vs--undefined):

> For readonly properties on interfaces that VS Code exposes to extensions: Use | undefined as this makes it clear the property exists but has the value undefined.

But I guess we don't have to strictly follow it?

**Comment by Tyriar** [comment]
@karrtikr by a second one I mean a second scope, we don't want the user to explicitly enumerate all the scopes to set it which `Required<>` would do.

**Comment by karrtikr** [comment]
Updated proposal:
```typescript
export interface EnvironmentVariableMutator {
	readonly type: EnvironmentVariableMutatorType;
	readonly value: string;
	readonly scope: EnvironmentVariableScope | undefined;
}

export interface EnvironmentVariableCollection extends Iterable<[variable: string, mutator: EnvironmentVariableMutator]> {
	replace(variable: string, value: string, scope?: EnvironmentVariableScope): void;
	append(variable: string, value: string, scope?: EnvironmentVariableScope): void;
	prepend(variable: string, value: string, scope?: EnvironmentVariableScope): void;
	get(variable: string, scope?: EnvironmentVariableScope): EnvironmentVariableMutator | undefined;
	delete(variable: string, scope?: EnvironmentVariableScope): void;
	clear(scope?: EnvironmentVariableScope): void;
}

export type EnvironmentVariableScope = {
	/**
	* The workspace folder to which this collection applies to. If unspecified, collection applies to all workspace folders.
	*/
	workspaceFolder?: WorkspaceFolder;
};
```

**Comment by karrtikr** [comment]
Closing in favor of https://github.com/microsoft/vscode/issues/182069 as these issues were only open to finalize proposed API.

**Comment by alexr00** [comment]
Moving this out of June as it's a feature request.

**Comment by karrtikr** [comment]
### Updated proposal

```typescript
export interface ExtensionContext {
	/**
	 * Gets the extension's environment variable collection for this workspace, enabling changes
	 * to be applied to terminal environment variables.
	 *
	 * @param scope The scope to which the environment variable collection applies to.
	 */
	readonly environmentVariableCollection: EnvironmentVariableCollection & { getScopedEnvironmentVariableCollection(scope: EnvironmentVariableScope): EnvironmentVariableCollection };
}

export type EnvironmentVariableScope = {
	/**
	* Any specific workspace folder to get collection for. If unspecified, collection applicable to all workspace folders is returned.
	*/
	workspaceFolder?: WorkspaceFolder;
};
```

**Comment by Tyriar** [comment]
@karrtikr I was expecting this so it's easier to understand for an API user:

```ts
export interface ExtensionContext {
	readonly environmentVariableCollection: EnvironmentVariableCollection;
	getScopedEnvironmentVariableCollection(scope: EnvironmentVariableScope): EnvironmentVariableCollection;
}
```

**Comment by karrtikr** [comment]
That's what I had initially had https://github.com/microsoft/vscode/issues/182069#issuecomment-1544072299, you're the one who recommended that perhaps we should put it inside `EnvironmentVariableCollection` itself: https://github.com/microsoft/vscode/issues/182069#issuecomment-1544291171 👀

**Comment by karrtikr** [comment]
API sync also seemed to be in agreement with that, but maybe we should check again.

**Comment by Tyriar** [comment]
@karrtikr my mistake, I forgot some of the conversations as this has gone through a few iterations 😅

**Comment by karrtikr** [comment]
Based on discussion in API sync, we should probably deprecate existing environmentVariableCollection API and merge it with the scoped one (similar to `workspace.getConfiguration()`)

```typescript
export interface ExtensionContext {
	/**
	 * Gets the extension's environment variable collection for this workspace, enabling changes
	 * to be applied to terminal environment variables.
	 *
	 * @deprecated Use {@link getEnvironmentVariableCollection} instead.
	 */
	readonly environmentVariableCollection: EnvironmentVariableCollection;
	/**
	 * Gets the extension's environment variable collection for this workspace, enabling changes
	 * to be applied to terminal environment variables.
	 *
	 * @param scope The scope to which the environment variable collection applies to.
	 */
	getEnvironmentVariableCollection(scope?: EnvironmentVariableScope): EnvironmentVariableCollection;
}

export type EnvironmentVariableScope = {
	/**
	* Any specific workspace folder to get collection for. If unspecified, collection applicable to all workspace folders is returned.
	*/
	workspaceFolder?: WorkspaceFolder;
};
```

**Comment by Tyriar** [comment]
Assigning myself too so it's easier for me to track 🙂

**Comment by karrtikr** [comment]
@meganrogge @Tyriar When viewing contributions, is it possible to open the preview of the markdown directly instead of the `.md` file?

![image](https://github.com/microsoft/vscode/assets/13199757/45825872-e969-4913-bf8b-2b51b7a776cd)

as opposed to

![image](https://github.com/microsoft/vscode/assets/13199757/e394a901-f531-4fec-a7a3-a24bd1af547b)

I can open preview using:

![image](https://github.com/microsoft/vscode/assets/13199757/4e830806-7cdc-44bb-b4d4-591b67be1f8e)

**Comment by Tyriar** [comment]
@karrtikr since this is an advanced feature I think the raw markdown is more flexible as the user can navigate and copy section of it better. So I don't think this is a necessary change personally

**Comment by Tyriar** [comment]
Feedback before finalization:

- Add an interface `GlobalEnviornmentVariableCollection` implements `EnvironmentVariableCollection`
- Add `getScoped` to the `GlobalEnviornmentVariableCollection`
- Clarify how scoped interacts with the non-scoped collection
- Don't deprecate

**Comment by karrtikr** [comment]
### Updated proposal:

```typescript
export interface ExtensionContext {
    /**
     * Gets the extension's global environment variable collection for this workspace, enabling changes to be
     * applied to terminal environment variables.
     */
    readonly environmentVariableCollection: GlobalEnvironmentVariableCollection;
}

interface GlobalEnvironmentVariableCollection extends EnvironmentVariableCollection {
    /**
     * Gets scope-specific environment variable collection for the extension. This enables alterations to
     * terminal environment variables solely within the designated scope.
     *
     * Each object obtained through this method is isolated and does not impact objects for other scopes,
     * including the global scope.
     *
     * @param scope The scope to which the environment variable collection applies to.
     */
    getScoped(scope: EnvironmentVariableScope): EnvironmentVariableCollection;
}

export type EnvironmentVariableScope = {
    /**
     * Any specific workspace folder to get collection for. If unspecified, collection applicable to all workspace folders is returned.
     */
    workspaceFolder?: WorkspaceFolder;
};
```

**Comment by Tyriar** [comment]
> Each object obtained through this method is isolated and does not impact objects for other scopes, including the global collection.

Should we also call out how it's applied in addition to (and after) the global collection?

Looks good otherwise 👍

**Comment by karrtikr** [comment]
Sure, I have modified the docstrings to append it. I plan to have the implementation ready but only merge and adopt it in Python extension next week to avoid multiple iterations.
