### ISSUE TITLE
VS code claims I am offline, when I'm very much online

### ISSUE THREAD

**Issue by Pomax** [microsoft/vscode#171130]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version:  1.74.3 
- OS Version: macos ventura 

Steps to Reproduce:

If I knew, I'd know how to fix it.

When searching for extensions, VS Code claims that I am offline when I am _absolutely_ not offline. Chrome has the same problem, where `navigator.onLine` says `false` so I suspect your code's using that flag too and _that flag is completely useless_. Don't use it =)

**Comment by sandy081** [comment]
@deepak1556 Is there another reliable alternative?

**Comment by Pomax** [comment]
You can just _actually fetch the marketplace domain URL_ instead of trying to see if there's a network first: if it works, it works. If it doesn't, you handle that in the fetch `catch` clause?

**Comment by deepak1556** [comment]
@sandy081 not that I am aware of.

@Pomax the goal with using `navigator.onLine` was to provide a better notification to users (similar to offline page in browsers) when we are confident that connectivity is offline compared to other network errors we receive from the request API.  Isn't `navigator.onLine` meant to give a pretty confident response about `offline` status. Atleast on macOS, chromium implements this by registering notification via `SCNetworkReachability` api if `0.0.0.0` is reachable by any network connection on the device. Refs https://bugs.chromium.org/p/chromium/issues/detail?id=7469

Is there anything in your network setting that would make the above detection not work ?

**Comment by Pomax** [comment]
I know Slack does something "clever" here, if it detects it's running in a browser that claims `navigator.onLine` is `false` it reports `CONNECTIVITY navigator.onLine appears to be untrustworthy; enabling workaround` so maybe worth asking the Slack folks what they do?

**Comment by deepak1556** [comment]
@sandy081 seems reasonable that we move the offline status check once the request has failed to address these scenarios.
