### ISSUE TITLE
VSCode ssh Remote url

### ISSUE THREAD

**Issue by kzhui125** [microsoft/vscode#171140]
- VS Code Version: 1.74.3 (Universal)
- OS Version: macOS 13.1

When opening link "vscode://file/Users/someuser/Documents", for example: paste this link to Chrome and press enter, it will open VSCode as expected.

But for ssh urls, such as "vscode-remote://ssh-remote+someserver/root", it doesn't work.

Is it a bug or missing feature. Thanks.

**Comment by aeschli** [comment]
Try `vscode://vscode-remote/ssh-remote+someserver/root`
