### ISSUE TITLE
remove duplicated code

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#17117]
The [`extendObject`](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/execution/electron-browser/terminalService.ts#L283) duplicates [`objects.assign`](https://github.com/Microsoft/vscode/blob/master/src/vs/base/common/objects.ts#L146) and should be removed

**Comment by mrmlnc** [comment]
Sorry for question, but why you don't use native `Object.assign`? 🐼

**Comment by jrieken** [comment]
stuff in common is still used in very old browser

**Comment by Tyriar** [comment]
Fixed in https://github.com/Microsoft/vscode/pull/17482
