### ISSUE TITLE
reset

### ISSUE THREAD

**Issue by tharunsrikrishna05** [microsoft/vscode#171169]
Type: <b>Feature Request</b>

i want to reset my visual code studio compeletley as new and clear all data that are related to the programs i done and extensions i installed everything have to be reset plz help me 

VS Code version: Code 1.74.3 (97dec172d3256f8ca4bfb2143f3f76b503ca0534, 2023-01-09T16:59:02.252Z)
OS version: Windows_NT x64 10.0.21996
Modes:
Sandboxed: No

**Comment by roblourens** [comment]
https://code.visualstudio.com/docs/setup/uninstall#:~:text=zip%20contents.-,macOS,and%20select%20Move%20to%20Trash.
