### ISSUE TITLE
`setLanguageConfiguration` throws "$.exec is not a function" in different cirumstances

### ISSUE THREAD

**Issue by brettfo** [microsoft/vscode#171194]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.75.0-insider
- OS Version: Windows 11

Steps to Reproduce:

1. Create an extension with a custom language.
2. Add a command that calls the function `vscode.languages.setLanguageConfiguration(...)` where the language configuration object contains just the `wordPattern` property.

E.g., the language configuration object could look like this:

``` json
{
  "wordPattern": "abc"
}
```

Result:

An exception is thrown with the text "$.exec is not a function" and the language configuration is not applied.

N.b., when this bug was initially encountered, the only language configurations that resulted in this error contained a literal `$` character (e.g., `"wordPattern": "\\$"`), but when digging deeper, I found that this scenario also broken.  It's likely the same underlying issue.

**Comment by brettfo** [comment]
If it helps with debugging, I'm a MSFT employee on the .NET Interactive team (github.com/dotnet/interactive) and I'm free to do a screen share.  My internal alias is `brettfo`.

**Comment by jrieken** [comment]
`"wordPattern": "abc"`

That looks like an invalid data. The spec'd type for `wordPattern` is `RegExp`, not string. See https://insiders.vscode.dev/github/microsoft/vscode/blob/d06d615e33c04a956bf6b7da38908b783197b63e/src/vscode-dts/vscode.d.ts#L5748

**Comment by jrieken** [comment]
closing this as question/invalid

**Comment by brettfo** [comment]
Is there a constructor or factory method to deserialize a language configuration?  Ultimately I'm reading `language-configuration.json` files from disk any dyanmically applying them with `setLanguageConfiguration`.  Looking through this repo, there appear to be different ways to specify the word pattern:

- from JS, [use the `pattern` sub-property](https://github.com/microsoft/vscode/blob/f6382a4112fcab4893c2180f2819f7cf33371f28/extensions/javascript/javascript-language-configuration.json#L110)
- from C++, [use the `wordPattern` directly as a string](https://github.com/microsoft/vscode/blob/fe39ab03db04ef1d010fce0cfd96d920e48285cf/extensions/cpp/language-configuration.json#L27)

**Comment by jrieken** [comment]
Yes, the language configuration files aren't being read via the API but directly in the renderer. There is no automatic deserialise
