### ISSUE TITLE
Allow an extension to control a terminal tab title/description variable

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#171175]
Some extensions create "special" terminals, one way of differentiating them is explicitly setting a title but then that replaces the standard title. What if instead a variable was controlled by an extension which would then default beside the task/local variables as they're similar:

<img width="629" alt="image" src="https://user-images.githubusercontent.com/2193314/212112117-610514de-2eed-4ef4-b5d0-e02bad01e1bd.png">

Context: https://github.com/microsoft/vscode-python/issues/20492#issuecomment-1380587461

**Comment by karrtikr** [comment]
For our use case we would like to apply this to all terminals (even if it's not the one we created).

**Comment by karrtikr** [comment]
Proposal:

- Add non-readonly property "description"
- This is used as the `${extension}` variable in the terminal title/description settings
- Any non-owning extension can contribute to the description. Information will show up on the right without shifting other text:
    <img src="https://user-images.githubusercontent.com/13199757/224848793-c47f850b-c53a-4d0d-834c-0e9ae014bee3.png" width=350 />

**Comment by Tyriar** [comment]
I'm concerned about non-owning extensions clobbering the description, leading to inconsistent behavior. For example an extension may create the terminal, set the description, and Python would overwrite it. Or the opposite, where Python sets it and some other extensions overwrites it.

After thinking about it more, it feels wrong that non-owning extensions have any say in this and we should instead attach this information in a less prominent way using the env var description as proposed in https://github.com/microsoft/vscode/issues/171108. I also think allowing an extension to set text in the description is going to lead to an overly cluttered UI. So we could surface the information in the tooltip where we show shell integration's state:

<img width="193" alt="image" src="https://user-images.githubusercontent.com/2193314/225001084-d71d7760-5018-4a2d-b1e7-b9d79889b88b.png">

Yes this is not as prominent as you might like, but I want to establish this area as how you get information about the particular terminal. We also have a WIP PR to add the process PID/executable/args there for example: https://github.com/microsoft/vscode/pull/171258

**Comment by Tyriar** [comment]
The current plan is to not do this
