### ISSUE TITLE
What is `vs/test`?

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#17110]
In the main folder have some sort of laying and I can no clue what `vs/test` is supposed to be? The current ideas are outlined here https://github.com/Microsoft/vscode/wiki/Code-Organization#layers and it seems like `test` should be moved into `workbench`

**Comment by sandy081** [comment]
@jrieken I created vs/test to have a common/shared test utilities for all our tests. Like 

- test Instantiation service mock that can stub services. Also has stubs for some known services 
- promise utility
- service test utility - This got mixed with too much of utilities. This used to contain utilities mainly for workbench but it grew beyond that.

But I accept that this should not break the layering. I would move them into respective layers as debt work.

Thanks for filing an issue for it.

**Comment by sandy081** [comment]
Moved ServicesTestUtils to under workbench/test folder and renamed it to WorkbenchTestServices as it contains mocked services for workbench. Since it contains references to browser/node and tests from all other layers are depending on it, I am leaving it at root.
