### ISSUE TITLE
Enable specifying installation directories in npm.sh

### ISSUE THREAD

**Issue by JoshStrobl** [Microsoft/vscode#1711]
Hello,

Currently you are unable to specify installation paths for node modules used by Code via `scripts/npm.sh`, only the architecture. This is an issue for package management systems on Linux where specific packages may "own" a set of files or directories, and thus produces conflicts on the system when multiple packages attempt to own the same set of files.

I'm proposing the following options be added to `npm.sh`:

`--installdir=DIR`: This would enable you to specify a general installation directory:
 - Beneficial for build systems that use isolated install directories (where the contents of it are then considered the contents of a binary package) away from the build directories.

`--node-modules=DIR`: This would enable you to specify **the root** of where you want node modules to be installed.
 - Resolves potential file conflicts for packages and pollution of global node_modules.

Examples:

`--installdir=/var/ypkg-root/install/vscode/`: This would be the root of the file system. Installation of binaries such as those placed in `/usr/bin` would begin with the installdir, so it is conceivable that the directory would for the binaries would then be `/var/ypkg-root/install/vscode/usr/bin`.
 - Note: This would only be on the isolated build system, the final contents installed on the user's system would still be /usr/bin, this would just specify where to install things on build-time.
 - Defaults to `/`
 - Sets something like $installdir (used below).

`--node-modules=$installdir/usr/share/vscode/`: This would install node modules to a `node_module` folder in `/usr/share/vscode`. This keeps it isolated from any `npm` or `nodejs` system packages and files. Atom does something similar, with installing things to (*for example*) `/usr/share/atom/resources/...`

Thoughts?

**Comment by jholtiv** [comment]
agreed

**Comment by bpasero** [comment]
@joaomoreno fyi

**Comment by joaomoreno** [comment]
`npm.sh` has zero options. Every argument you give it [is passed along to `npm` itself](https://github.com/Microsoft/vscode/blob/master/scripts/npm.sh#L28), so it supports every argument `npm` supports.
