### ISSUE TITLE
Provide `onDidChangeShell` event which is fired when default terminal profile changes

### ISSUE THREAD

**Issue by karrtikr** [microsoft/vscode#171164]
Python extension is planning to use environment collection API to activate Python environments for a particular shell. Environment variables to use depends on the shell itself, so when the default shell setting changes, we would like to be notified so we could prepare the new set of environment variables to use the next time terminal opens.

As a workaround we could use `onDidOpenTerminal` to detect this change with a delay, however that requires the user to relaunch the terminal once environment collection is updated.

cc/ @Tyriar feel free to close this if this is a dup of https://github.com/microsoft/vscode/issues/160694.

**Comment by gjsjohnmurray** [comment]
It looks like PR #160900 already added that event as proposed API.

**Comment by karrtikr** [comment]
When I attempt to use the proposal it says:
![image](https://user-images.githubusercontent.com/13199757/221057430-54aa5374-babd-48e2-8d07-6111e23cfbf0.png)

Can you please clarify on what is needed to done from extension's end to use this?

**Comment by meganrogge** [comment]
You have to add the proposed API to your package.json like this

![Screenshot 2023-02-24 at 11 09 04 AM](https://user-images.githubusercontent.com/29464607/221243013-3f39f0d2-c8b2-4e16-8a5a-17e2b10b938f.png)

**Comment by karrtikr** [comment]
That is where the screenshot is from in the original pic.

**Comment by karrtikr** [comment]
![image](https://user-images.githubusercontent.com/13199757/221251066-c1331d32-6068-4f8d-8cfe-c046b8dffa59.png)

Should I create a new issue?

**Comment by gjsjohnmurray** [comment]
What version of the vscode engine does your extension declare that it uses?

**Comment by karrtikr** [comment]
It's `1.75.0-20230123`:
![image](https://user-images.githubusercontent.com/13199757/221254523-e76bb888-7559-404e-8fdb-ae4eac7063c3.png)

**Comment by karrtikr** [comment]
> This proposal cannot be used because for this extension the product defines a fixed set of API proposals. You can test your extension but before publishing you MUST reach out to the VS Code team.

Does VSCode have a products file internally which declares which extension gets to use the proposal?
