### ISSUE TITLE
vscode 1.7.4.3 Run and debug function buttons are not in the same style...

### ISSUE THREAD

**Issue by zhouxinghong** [microsoft/vscode#171214]
vscode 1.7.4.3 Run and debug function buttons are not in the same style, so it's easy for newbies to use it and not easy to understand what it really means, so it's difficult to use.
![2023-01-13_073408](https://user-images.githubusercontent.com/54253524/212204354-83e3640b-fa59-4261-940b-c8b1d1ac7dbe.png)

I hope this issue will be fixed in vscode 1.7.5. Thank you very much!
System: Windows 10
code: 1.7.4.3

**Comment by roblourens** [comment]
These are different buttons with different functions and meanings, I think this is appropriate
