### ISSUE TITLE
Cannot use letter "M"

### ISSUE THREAD

**Issue by MitkoVtori** [microsoft/vscode#171255]
# Describe problem

I cannot use the letter **m**. And specially, the small letter **m**, I can use only capital letter (**M**).
When I type small **m** It tells me that's a command keybind, and it is waiting for second command keybind or something.

# Pictures
![Screenshot 2023-01-13 152403](https://user-images.githubusercontent.com/112943652/212331166-10070f83-44a7-414d-8bcb-6f1270321a08.png)
![Screenshot 2023-01-13 152437](https://user-images.githubusercontent.com/112943652/212331170-326bafd9-0494-4c9b-8940-f0a479a182d1.png)

# What you've tried
I tried searching in the command keybind, for the letter **m**, and as much as I remember I didn't find it, or if I find it, I was not able to change it.

For now, It is working by copy-pasting the letter (**m**), but as you know, that is not really optimal, since I have to copy other things to write code, and also it's a little bit difficult to have to click ctrl+v every time instead of directly clicking the letter.

**Comment by gjsjohnmurray** [comment]
Does the issue still occur after you run the Command Palette (F1) command to reload with all extensions disabled?

If it does I suggest you run the command `Preferences: Open keyboard Shortcuts (JSON)` and search that file for a composite keybinding that uses "m" as its first key.

**Comment by MitkoVtori** [comment]
@gjsjohnmurray Thank you for the help. After I clicked (F1) I saw a list with all commands, I found the command that doesn't let me write "m" and just changed the keybind.
