### ISSUE TITLE
Python extension isn't showing up in the extension view search

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#171206]
This is scrolled to the top, the way I found the python extension was to find an extension pack and click the python ext dependency

<img width="447" alt="image" src="https://user-images.githubusercontent.com/2193314/212185448-92ac9bf5-8e3d-44dd-96dd-841122a922a7.png">

**Comment by isidorn** [comment]
Thanks for reporting. This is fixed. Was a problem with the Insiders search service.
