### ISSUE TITLE
Allow for debug settings in `launch.json` without specifying a program script to execute

### ISSUE THREAD

**Issue by mhkeller** [microsoft/vscode#171282]
As raised in [this issue](https://github.com/microsoft/vscode/issues/168924#issuecomment-1347673795), when debugging, I would find it very useful to be able to specify as global or project defaults some of the options that you can put into a `launch.json` file. 

My use case is I find it very convenient to use F5 to run my currently open script. The downside is that [I lose color output](https://github.com/microsoft/vscode/issues/168924) in the debug terminal. The fix for this is to create a `launch.json` file and specified `"console": "integratedTerminal"` but, as far as I know, a `launch.json` file requires a specific script to execute – that is to say, it will not allow me to use F5 to run whatever arbitrary script I have open. It would be nice to get the better output from the `integratedTerminal` option while maintaining the flexibility of running whichever script I have open at the time.

I'm agnostic on how this is implemented.  It could be that you keep everything the same but in the `launch.json` file if `program` is empty, it maintains the behavior of launching the currently open script.

Alternatively, it could be a config file stored in the `.vscode` folder so that a user could change this on a per project basis. It could be a VS Code setting itself or a combination of the two where global VS code settings are superseded by project-specific ones in the `.vscode` folder.

If this is currently possible via some way I am not aware of, please let me know. It seems like all of the features exist, I would just like to use an integrated terminal without being locked into hardcoding the name of the script I am executing in `launch.json`. Thanks for you time.

**Comment by roblourens** [comment]
You can use the `${file}` variable to get the path to the current active file in a launch config, that hopefully addresses this for you.

**Comment by mhkeller** [comment]
Yes thanks so much!
