### ISSUE TITLE
Add preview capability for extension public info panel

### ISSUE THREAD

**Issue by miketalley** [microsoft/vscode#171268]
It is not easy to preview the info panel, that is populated from the extension manifest, which is shown when double-clicking on the extension from the extensions section of the activity bar. (see example image)
![image](https://user-images.githubusercontent.com/6472448/212371331-cf6dbfc8-b1d9-4ff3-9481-87c3cb731669.png)

As far as I can tell, the title does not update even when packaged for testing (`vsce package`). I'm not sure which data comes from the manifest of the installed extension vs the current published extension. Previewing the information in this panel requires a lot of steps...
1. Make changes
2. Run `vsce package`
3. Open extensions section
4. Install from `.vsix`
5. Reload window
6. Back into extensions section
7. Search for extension
8. Open extension info panel

It would be a huge improvement if there was a way to preview the content that populates the live info panel prior to packaging. 

One solution I can think of: When previewing the extension (`f5` extension host), going into the extension section and viewing the extension's info panel would contain the local content.

**Comment by sandy081** [comment]
> One solution I can think of: When previewing the extension (f5 extension host), going into the extension section and viewing the extension's info panel would contain the local content.

Thanks for this solution and I would say this is the recommended.

**Comment by sandy081** [comment]
This shows read me of installed/local extension, hence closing this. If it is not working for you, please reopen the issue with steps to reproduce.
