### ISSUE TITLE
Not all keystrokes recorded when using git bash for Windows as the integrated shell

### ISSUE THREAD

**Issue by dshamilton** [Microsoft/vscode#17122]
- VSCode Version: Code 1.7.2 (7ba55c5860b152d999dda59393ca3ebeb1b5c85f, 2016-11-21T22:06:37.428Z)
- OS Version: Windows_NT ia32 10.0.10586
- Extensions:

|Extension|Author|Version|
|---|---|---|
|EditorConfig|EditorConfig|0.3.4|
|tslint|eg2|0.5.33|
|vscode-JS-CSS-HTML-formatter|lonefy|0.2.1|
|prettify-json|mohsen1|0.0.3|
|vscode-icons|robertohuertasm|1.5.2|
|vim|vscodevim|0.4.2|

---

Steps to Reproduce:

1. Install git for windows (https://git-for-windows.github.io/)
2. Setup the git bash shell as the integrated terminal for vscode (workspace settings: "terminal.integrated.shell.windows": "C:\\progra~1\\Git\\bin\\bash.exe")
3. Type text into the integrated shell window (quickly, typed). 
4. When you press return to send the command, some of the text isn't sent to the command window. I'm not sure if this behavious occurs more frequently when backspace is used.

**Comment by Tyriar** [comment]
Merging into #14613

**Comment by Tyriar** [comment]
This should hopefully be fixed in tomorrow's Insiders build (via https://github.com/Microsoft/vscode/commit/63f1fa66800bf641de5e36027610503ba75085b5). Please let me know if it still reproduces.

See https://github.com/Microsoft/vscode/issues/13625 for more information.
