### ISSUE TITLE
Can not switch from markdown preview back to regular editor

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#17123]
1. Open a markdown file, e.g our docs
2. Open a preview of that file side by side
3. Continue working, after some time only have the preview opened
4. Click on the action to go back to the regular editor

Sorry for not exact steps - can not repro it easily. But it happens 100% after some time working with markdown and previewin.
FYI @joaomoreno since I think you touched some inmemory models

Notice error, also notice that the title of that preview becomes 'preview of 42' so it seems like the preview has lost it's original model

![screen shot 2016-12-13 at 16 59 37](https://cloud.githubusercontent.com/assets/1926584/21147603/dd874f56-c155-11e6-8b5c-423ec698f339.png)

**Comment by joaomoreno** [comment]
Let's try to get some steps.

**Comment by mjbvz** [comment]
I'm unable to reproduce this issue and am also not sure where the `inmemory` schema is coming from. 

@isidorn Please let me know if you are still hitting this or if it was just a transient issue.
