### ISSUE TITLE
Extensions view search is adding a new line when searching on enter

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#171205]
![Recording 2023-01-12 at 13 29 09](https://user-images.githubusercontent.com/2193314/212185145-b86234a9-7fdf-4f06-9a76-d2d41154bf8a.gif)

**Comment by jwshields** [comment]
I am experiencing this issue as well.  
Using the dev console and following network requests, I can see that when I press enter, the search query and text box get a literal `\r\n` inserted into it.

Version info:
```
Version: 1.75.0-insider (system setup)
Commit: 12515569ae440cf7ccc02d4649a25f2c77909557
Date: 2023-01-11T20:01:54.721Z
Electron: 19.1.9
Chromium: 102.0.5005.194
Node.js: 16.14.2
V8: 10.2.154.23-electron.0
OS: Windows_NT x64 10.0.19044
Sandboxed: Yes
```

**Comment by sandy081** [comment]
This shall be fixed in next insiders.
