### ISSUE TITLE
ANSI Handling Expected single sequence operation

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#171271]
Build: https://dev.azure.com/monacotools/a6d41577-0fa3-498e-af22-257312ff0545/_build/results?buildId=199322
Changes: https://github.com/Microsoft/vscode/compare/d61f46d...ca07d07

```
Debug - ANSI Handling Expected single sequence operation (reason: Timeout of 5000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.)
```

**Comment by Tyriar** [comment]
@connor4312 why was I assigned to this one?

**Comment by connor4312** [comment]
oh, I think I probably just scanned the name.

Honestly no idea about this issue. The test isn't `async` and should be entirely deterministic. Current runs also take <50ms for that test (threshold to show the time). This test hasn't failed in the last 30d. Will close unless we see it again.
