### ISSUE TITLE
Scroll shadow appears in extensions view input box

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#171233]
Open the extensions view, type something and press `Enter`. Suddenly a scroll shadow appears. You can actually scroll up, indicating that `Enter` introduced a new line.

![image](https://user-images.githubusercontent.com/22350/212274679-12bfb718-0ec1-4c47-a796-6f347c68c2af.png)

**Comment by sandy081** [comment]
I think caused by this 95ac498b8df19ce5ca7e88cfaff1fcf66f052ce7 - I removed listening to enter as it was not being used by any one. I would bring this back and add a comment.
