### ISSUE TITLE
Code Action Menu Does Not Open At Cursor Location When Clicking On Lightbulb

### ISSUE THREAD

**Issue by hediet** [microsoft/vscode#171260]
Code Action Menu Does Not Open At Cursor Location When Clicking On Lightbulb:

![Code_-_Insiders_E7wCivpZ6x](https://user-images.githubusercontent.com/2931520/212335008-12536d3a-e0bb-490f-a263-edc7f83e340b.gif)

However, when using the shortcut ctrl+., it does:
![Code_-_Insiders_Irm7251vWb](https://user-images.githubusercontent.com/2931520/212335071-137ba7ac-43f3-4272-bdb8-047fdcea51a8.gif)

I would expect the menu to open at the same position in both cases.

**Comment by gjsjohnmurray** [comment]
@hediet if in your first case the menu appears in the same place as shown in the second case, wouldn't that mean I have to move the mouse a (potentially large) distance in order to pick an option with it?

**Comment by hediet** [comment]
>  wouldn't that mean I have to move the mouse a (potentially large) distance in order to pick an option with it?

I agree. However, right now, it is unclear what these code actions refer to, especially as the cursor is hidden when the menu opens.

I'd prefer less confusion over shorter mouse distance, especially since the ligthbulb is (imo) mostly there to make code actions discoverable.

**Comment by mjbvz** [comment]
Yes this is by-design. Open to other ideas for better indicating where the cursor is but not in favor of moving the menu away from the lightbulb
