### ISSUE TITLE
Broken Link - MS Link to Github

### ISSUE THREAD

**Issue by brantzm** [Microsoft/vscode#17127]
I found this broken link:

This:
https://www.microsoft.com/net/core#linuxredhat

Links to this:
https://code.visualstudio.com/B#alt-downloads

Which is broken (404).

Hope this helps.

**Comment by kieferrm** [comment]
@brantzm can you pls provide information about where you encountered those links.

**Comment by brantzm** [comment]
It's exactly where I said in my original post - go to this link:
https://www.microsoft.com/net/core#linuxredhat

Then scroll to the bottom of the page to the "Download Visual Studio Code" button / link and you will be sent to this broken link:
https://code.visualstudio.com/B#alt-downloads

And that page has a "report issue" link which took me to this thread on Github.

Thx.

**Comment by kieferrm** [comment]
@chrisdias can you pls ping the website owners.

**Comment by chrisdias** [comment]
Moved to .NET Core Website
