### ISSUE TITLE
IntelliSense: most relevant result is not revealed

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#1712]
When I have a node.js import for "path" and type "path", the element is not revealed:

![image](https://cloud.githubusercontent.com/assets/900690/12051860/1d20af78-af09-11e5-9433-3c5ab1d35cdd.png)

**Comment by wadeanderson7** [comment]
I am seeing this too.

**Comment by TheColorRed** [comment]
I am seeing this too, It would also be nice for it to be case insensitive (if it is not).
