### ISSUE TITLE
Allow to open problems view without taking keyboard focus

### ISSUE THREAD

**Issue by vvuk** [Microsoft/vscode#17121]
I'm trying to have an extension automatically (with config) open up the Problems panel after it does a syntax check compile.  I can do:
```
vscode.commands.executeCommand("workbench.action.showErrorsWarnings");
```
but this opens the panel *and focuses it*.  This last part is the problem.  Hunting through the code, this is a `ToggleErrorsAndWarningsAction`, which extends `TogglePanelAction`, which ultimately runs:
```
return this.panelService.openPanel(this.panelId, true);
```
That `true` argument is the problem here -- I want to call `panelService.openPanel` with `false` for the focus argument.  I'm not clear on what the extensibility API boundary is, and how I can get to things like the panel service -- is it possible to do that from an extension?

**Comment by isidorn** [comment]
@vvuk this is currently not possible from an extension. And unfrotunetly there is currently no command which you can call from your extension to get the desired behavior.

A proper way to do this is to change the [TogglePanelAction](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/browser/parts/panel/panelPart.ts#L143) to accept a focus boolean as an argument and then this should be propagated via PartService to the PanelService.

**Comment by vvuk** [comment]
Great, thanks! I wasn't sure how porous the core/extension boundary was, was hoping there might be a way to reach into the innards but probably best that there isn't :)

Instead of adding options to TogglePanelAction and modifying associated commands, perhaps there might be a more general solution to focus?  Perhaps there could be some way for extensions to lock focus changes and prevent any from happening until focus is unlocked. It seems like there are two design options:

1. Explicitly allow any command to arbitrarily change focus; or
2. Explicitly disallow focus changes by commands, unless the sole purpose of the command is to change focus.

The first is what seems to be the case now, except that it's an implicit permission.  To make it explicit, focus lock would be needed, say:
```
vscode.pushFocus();
vscode.commands.executeCommand("workbench.action.showErrorsWarnings");
vscode.popFocus();
```

(Maybe an `await` is needed for the `executeCommand`?)  The second would enforce this, at the expense of needing to add explicit focus commands for various elements, e.g.:
```
vscode.commands.executeCommand("workbench.action.showErrorsWarnings");
vscode.commands.executeCommand("workbench.action.focusErrorsWarnings");
```

Doing the work just to modify `TogglePanelAction` seems like a constrained solution to a more general problem.  Also, in the interim, I've found the following workaround:

```
vscode.commands.executeCommand("workbench.action.showErrorsWarnings");
vscode.commands.executeCommand("search.action.focusActiveEditor");
```
:)
