### ISSUE TITLE
Cant access codespaces when on VPN

### ISSUE THREAD

**Issue by madelinesachtler** [microsoft/vscode#171269]
I work for the Department of Veterans Affairs and we need to access Codespaces for a Conference. We have access to Github through our firewall but cannot access Codespaces. In order to access the site, we need to know what is preventing the Codespace from opening up - be it a download, a server issue, a port issue (any other ports besides 443 that we need?) etc. 

I attached a photo below of the error  
![Github_codespace](https://user-images.githubusercontent.com/73665864/212373036-eebc5eff-9a69-4797-aa1e-09c07956a5ec.png)

Version: 1.74.3
Commit: 97dec172d3256f8ca4bfb2143f3f76b503ca0534
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36 Edg/108.0.1462.46
Embedder: codespaces

**Comment by MrTrustFundBaby** [comment]
I was having connectivity issues when connecting via VS Code when connected to VPN. Tried debugging by tinkering with VPN config by switching protocol to OpenVPN (UDP), OpenVPN (UDP), and Wireguard with no luck.

Ended up using a different VPN provider all together and started working. Not sure if the VPN server IPs I was connecting to before were blacklisted... 🤷

**Comment by alexdima** [comment]
Please file an issue in the [Codespaces Discussion Forum](http://aka.ms/ghcs-feedback)
