### ISSUE TITLE
Remote Tunnel Access hangs when connecting from two browser tabs at same time

### ISSUE THREAD

**Issue by chrisdias** [microsoft/vscode#171218]
Insiders on MacOS Big Sur

```
Version: 1.75.0-insider
Commit: 6d40104789d03d41b8866a1e57847dae14c5cf0d
Date: 2023-01-12T05:36:13.961Z
Electron: 19.1.9
Chromium: 102.0.5005.194
Node.js: 16.14.2
V8: 10.2.154.23-electron.0
OS: Darwin x64 20.6.0
Sandboxed: Yes
```

- All on the same machine...
- Turn on Remote Access
- Open a browser (Edge in this case) instance to connect to server
- Leave this browser tab open and turn off Remote Access on the desktop tools
- Turn on Remote Access again
- Copy the URL
- Open a new tab (leaving the existing tab open) and browse to the server

Result: Hangs.  First browser instance will eventually try to reconnect and will hang as well.  

In the dev tools console of the browser lots of 404s.

![image](https://user-images.githubusercontent.com/64658626/212215544-3b421d44-5ec5-4207-a365-45db27f80acf.png)

- Hard quit VS Code on the desktop
- In terminal `ps aux | grep vscode-cli`

![image](https://user-images.githubusercontent.com/64658626/212215720-2a300017-4577-4e1e-98dc-b934228fe18c.png)

Have to kill one or more of these processes to be able to turn on Remote Access again.

**Comment by connor4312** [comment]
Duplicates https://github.com/microsoft/vscode-remote-release/issues/6543
