### ISSUE TITLE
Build fail: Install musl build dependencies

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#171231]
https://monacotools.visualstudio.com/DefaultCollection/Monaco/_build/results?buildId=199368&view=logs&j=48207fd5-012e-56df-443f-66bf436df83d&t=4ca5855a-2db2-5a0c-9867-11d7718314e2&s=a2720dec-461a-5b3d-f007-6e0de7b924c4

**Comment by bpasero** [comment]
Similar: https://monacotools.visualstudio.com/DefaultCollection/Monaco/_build/results?buildId=199368&view=logs&j=9739482b-7183-5d97-1b26-9f97bf1600ab&t=91c497b0-0730-5063-aafd-150c9576b04f&s=a2720dec-461a-5b3d-f007-6e0de7b924c4

Maybe a connection issue, so the task should be retried.

**Comment by bpasero** [comment]
I am not sure who owns this.

**Comment by joaomoreno** [comment]
This was a major outage with Ubuntu: https://status.canonical.com/#/incident/KNms6QK9ewuzz-7xUsPsNylV20jEt5kyKsd8A-3ptQFdhagDnjfaXXVpElWI5MToWkxoAA9XuP4NaRBzB2kxAQ==

**Comment by jahuarcristian** [comment]
Ok
