### ISSUE TITLE
Slow render issue when maximizing/restoring window

### ISSUE THREAD

**Issue by mousetraps** [Microsoft/vscode#17137]
- VSCode Version: Code 1.8.0 (38746938a4ab94f2f57d9e1309c51fd6fb37553d, 2016-12-13T17:45:32.595Z)
- OS Version: Windows_NT ia32 10.0.14965

See below - notice the right and bottom parts of the window take a while (several seconds) to refresh. I was debugging in this case, but the issue occurs regardless of what mode you're in
![2016-12-13_13-00-05](https://cloud.githubusercontent.com/assets/762848/21159016/582ab47c-c134-11e6-8063-f467a4247f22.gif)

**Comment by kieferrm** [comment]
Here is the same scenario on a windows 10 parallel's VM on macOS. Interestingly much faster. Potential differences: touch screen, low on memory, other CPU hogging activities.

![eefh8mwa79](https://cloud.githubusercontent.com/assets/4674940/21166025/cf6b8a2a-c157-11e6-9d14-dbc486dc93f8.gif)

**Comment by bpasero** [comment]
Please comment on Kais performance questions, likely related. Also you can run a chrome profile session to capture where time is spend:

To create a CPU profile using developer tools in VS Code:
* select Help > Toggle Developer Tools
* click on Profiles
* click the start button
* do whatever you need to do to get the CPU spin high
* wait for some time (10-20 seconds should be enough)
* stop the profiling 
* click the save button and attach the output file to this issue

**Comment by bpasero** [comment]
A number of days has past without answer on the questions asked. I am thereby going to close this issue to clean up our backlog of issues. Once you can answer on the questions, the issue can be reopened again. Thanks for understanding this process!
