### ISSUE TITLE
tsconfig extends support jump to definition when using package

### ISSUE THREAD

**Issue by tjx666** [microsoft/vscode#171365]
@mjbvz 

<img width="1050" alt="image" src="https://user-images.githubusercontent.com/41773861/212554074-7f3e275e-b897-4da6-a249-e3783712d479.png">

https://user-images.githubusercontent.com/41773861/212983356-c5a472dd-df18-492a-9ffd-7e6359c6b055.mov

Reproduce:

1. git clone `git@github.com:tjx666/vite-issue-reproduce.git`
2. git checkout vscode-tsconfig-issue
3. `pnpm install`
4. open `apps/app/tsconfig.json`
5. try `CMD + click` to `extends` field

**Comment by mjbvz** [comment]
Please share a minimal project which demonstrates this

**Comment by tjx666** [comment]
@mjbvz just like


https://user-images.githubusercontent.com/41773861/212977073-79bd2671-2c38-4177-96c1-ce476481c27e.mov

**Comment by mjbvz** [comment]
Please share the code. This makes it much faster to investigate issues like this

**Comment by tjx666** [comment]
@mjbvz updated reproduce in issue description

**Comment by mjbvz** [comment]
Where's `@scripts` coming from? I don't see it in that project

Please put together a minimal, self contained example of the issue

**Comment by tjx666** [comment]
The `@scripts/tsconfig` is a workspace package, you can the repro for details: https://github.com/tjx666/vite-issue-reproduce/tree/vscode-tsconfig-issue

![image](https://user-images.githubusercontent.com/41773861/217703134-ec0abeb4-7dfb-4a56-bd19-2da7e458d78c.png)

**Comment by tjx666** [comment]
@mjbvz 

A more simple way to reproduce:

1. open a node project contains tsconfig
2. npm install `@vue/tsconfig`
3. extends in tsconfig.json by `"extends": "@vue/tsconfig/tsconfig.web.json",`

![image](https://user-images.githubusercontent.com/41773861/220237427-999c1644-6f32-400a-adc0-fbab0b799468.png)

**Comment by tjx666** [comment]
@mjbvz still have question about this issue?

**Comment by mjbvz** [comment]
Hm that latest example using `"extends": "@vue/tsconfig/tsconfig.web.json"` works fine for me on MacOS

**Comment by tjx666** [comment]
I find this is a issue of volar.
