### ISSUE TITLE
CompletionProvider not be triggered

### ISSUE THREAD

**Issue by AisonSu** [microsoft/vscode#171349]
This maybe a dev-question, I am developing a VS Code extension of css intellisense in .vue file with languages.registerCompletionItemProvider, and the trigger character is '-', But it does not work at all, and I did some test to make sure it the problem is happened with volar, the extension of vue, But i still need to know which step may change the behavior of triggering the completion provider

All I know is:
1. Only when the volar is enable, it doesn't work, otherwise it works normally in the .vue file.
2. Only does not work in the .vue file, in other files it works normally even volar enable.
3. the completion provider totally not be triggered by typing '-'，if use any other trigger word instead, it works normally.
4. use Ctrl+Space to manually trigger the Intellisense, the provider was triggered normally.

**Comment by jrieken** [comment]
Trigger characters that are also word-characters don't count as word characters. That's because quick suggest comes into play here. It's likely that volar defines a custom word definition for .vue-files and that that word definition includes the - character
