### ISSUE TITLE
Something feels wrong about placeholders replacement on completeFunctionCalls

### ISSUE THREAD

**Issue by vdegenne** [microsoft/vscode#171327]
https://user-images.githubusercontent.com/2827383/212486814-bc1a99bf-7479-448f-ba4f-c0fae6a04daf.mp4

**Behavior**
In the recording, why is `type` not replaced by the expanded single quotes? Instead the keyword `type` will remain inside the quotes.  
But it really wouldn't be a problem if it was just that. Continuing in the example you can see it becomes a problem when the placeholder is inserted inside an expanded `()`.
In JavaScript sometimes we want to just type an arrow function with no params `() => { ... }`, as you can see here it breaks the flow and because the placeholder is not cleared the closing parenthesis I type is replacing the placeholder and an extra closing parenthesis remains in the final result.

The problem seems to be from VSCode wrapping placeholders inside auto-closing elements.

**Expected**
So you can understand the problem I am facing I made another video with what I expect

https://user-images.githubusercontent.com/2827383/212493479-ebe1f522-4e30-4846-9439-7ceb866babc6.mp4

*(To make this demo I am just pressing Escape to remove the placeholder before typing the desired input. But I expect that to be the default)*

Version: 1.74.3
Commit: 97dec172d3256f8ca4bfb2143f3f76b503ca0534
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36
Embedder: vscode.dev

**Comment by jrieken** [comment]
This is the `editor.autoSurround` setting to control this behaviour
