### ISSUE TITLE
Trust

### ISSUE THREAD

**Issue by wieczorek1990** [microsoft/vscode#171370]
Please delete or change this stupid prompt every time to trust when opening.
I fetch from the internet and new Is always no trust.

**Comment by lszomoru** [comment]
@wieczorek1990, thank you very much for the feedback. There are a [set of settings](https://code.visualstudio.com/docs/editor/workspace-trust#_settings) that are documented here that you can use to tweak the workspace trust feature. I will go ahead and close this issue but in case you have any further questions or concerns regarding the settings please feel free to reopen the issue. Thanks!

**Comment by wieczorek1990** [comment]
It is very annoying for new users and they probably do not want to go into
settings when they check fast.
