### ISSUE TITLE
Pasting over autocompleted line create text glitches

### ISSUE THREAD

**Issue by digitarald** [microsoft/vscode#171300]
Type: <b>Bug</b>

Typing `yarn add` showed the `gpt3-tokenizer` as gray preview

![image](https://user-images.githubusercontent.com/8599/212441672-91f17df2-25e9-401e-a26e-5871f5ca4853.png)

Pasting `gpt3-tokenizer` in the terminal leads to the glitched rendering

![image](https://user-images.githubusercontent.com/8599/212441698-a45ec04f-20e0-4850-b73d-a67b79109a36.png)

Hitting space after pasting un-glitches the text

VS Code version: Code - Insiders 1.75.0-insider (243854703b7fa371abb752ec0df7817a615a308b, 2023-01-13T07:49:05.588Z)
OS version: Darwin x64 22.2.0
Modes:
Sandboxed: Yes

**Comment by Tyriar** [comment]
This is fixed, was theme related
