### ISSUE TITLE
Debugger process is closed on Windows

### ISSUE THREAD

**Issue by JaneySprings** [microsoft/vscode#171317]
Hello. I create debugger extension for VSCode. Part of it is the launch android emulator. I create simple .bat file:
<img width="844" alt="image" src="https://user-images.githubusercontent.com/48021947/212471287-bb45f142-546b-459b-b469-f3215b32523a.png">

If you execute bat file manually, all be fine.

I added bat file to debugger section of my extension:
<img width="268" alt="image" src="https://user-images.githubusercontent.com/48021947/212471398-92eb3fdc-bd4c-45e0-a2fd-8b57d62536a3.png">

If you run a debug, emulator started and closed after few seconds without errors. But on Linux and MacOS the same scenario works without problems.

Seems like there is a difference between VSCode environment and manual launch on Windows.

Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 
<img width="347" alt="image" src="https://user-images.githubusercontent.com/48021947/212471668-2efd5aae-b55e-4f3e-9b26-c08402083fc1.png">
- OS Version: 
<img width="450" alt="image" src="https://user-images.githubusercontent.com/48021947/212471688-f35ca961-3a6b-432f-959c-d7457ba8c1a2.png">

**Comment by JaneySprings** [comment]
https://user-images.githubusercontent.com/48021947/212611427-fb1b052c-dcb9-414a-885c-d2f7a57a4eeb.mp4

**Comment by roblourens** [comment]
That `program` field is expected to launch a program that will be able to communicate using the DAP protocol. It's not intended to launch your debuggee. I recommend reading the docs on debugger extensions https://code.visualstudio.com/api/extension-guides/debugger-extension

**Comment by JaneySprings** [comment]
This example demonstrates a bug, I have a DAP implementation where it doesn't work. I specifically gave a minimal example of how this can be reproduced.

At a minimum, this scenario works on Mac OS and Linux.

**Comment by JaneySprings** [comment]
Yes, in the example, I want VSCode to just run the emulator and hang, as it happens with manual run. But for some reason the emulator closes if it is started by VSCode. On MacOS and Linux it works.

I have a debugger extension with DAP (if you want, you can look at it https://github.com/JaneySprings/DotNet.Meteor). At 'launch' event, I also run emulator and when it booted, I send success. But emulator closes. Moreover, if you run debug program without VSCode, emulator will boot successfully.
<img width="1001" alt="image" src="https://user-images.githubusercontent.com/48021947/213372542-79121f73-b066-402f-b5a1-72a14fdeb46d.png">

My example shows that executing a .bat file from VSCode and from Windows manually is different

**Comment by roblourens** [comment]
> Yes, in the example, I want VSCode to just run the emulator and hang, as it happens with manual run

We won't do that in this case, we are expecting the program to be a DAP debug adapter.

> I have a debugger extension with DAP (if you want, you can look at it https://github.com/JaneySprings/DotNet.Meteor). At 'launch' event, I also run emulator and when it booted I send success and start debug (resolve breakpoints and etc.). But emulator closes. 

In this case, since it's being started by your debug adapter, it seems like it must be an issue with the debug adapter.

**Comment by JaneySprings** [comment]
The reason why the emulator is closed is that it's REQUIRED to specify the exec function's cwd property only on Windows. This property must contain a path to the folder that stores the executable file. If I skip this step, the emulator does not work on Windows, although everything works fine on Mac and Linux.

**Comment by roblourens** [comment]
Sorry, I don't understand what you are asking me for
