### ISSUE TITLE
Output channel text model is only updated when output channel is visible

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#171334]
I'm trying to build an extension that listens to text model updates for an output channel, applies some filters, and writes the result to a new output channel. It seems like `onDidChangeTextDocument` is only broadcast for an output channel text model when that channel is visible. Is that by design? Is there any way to work around it?

Example code

```ts
context.subscriptions.push(vscode.commands.registerCommand('extension.helloWorld3', async (arg1, arg55) => {
	const channelA = vscode.window.createOutputChannel('a');
	const channelB = vscode.window.createOutputChannel('b');
	channelB.show();

	vscode.workspace.onDidChangeTextDocument(e => {
		console.log(e.document.uri);
	});

	channelA.appendLine('hello');
	setTimeout(() => {
		console.log('no doc change event yet');
		channelA.show();
		setInterval(() => {
			channelA.appendLine('hello');
		}, 1000);
	}, 1000);
}));
```

Watch the logs and see that the event is not fired until channel A is visible. If I switch away from it, the events stop, if I switch back, they resume.

**Comment by sandy081** [comment]
Yes, this is expected. Non visible/active output editors are disposed. Keeping them alive is non performant and not good.

**Comment by roblourens** [comment]
Is there any way to get the file on disk that is associated with this output channel so I can watch it on the filesystem?

**Comment by sandy081** [comment]
Sorry, there is not.
