### ISSUE TITLE
vs code crashes

### ISSUE THREAD

**Issue by calidion** [Microsoft/vscode#17132]
- VSCode Version: Code 1.7.2 (7ba55c5860b152d999dda59393ca3ebeb1b5c85f, 2016-11-21T22:01:10.756Z)
- OS Version: Darwin x64 16.1.0
- Extensions:

|Extension|Author|Version|
|---|---|---|
|vscode-icons|robertohuertasm|3.0.7|

---

Steps to Reproduce:

1. click help or [帮助]
2. click [switching developer tools] or [切换开发者工具] 
3. repeat 2 for threes times.

vs code will crash.

**Comment by kieferrm** [comment]
Older versions of vscode-icons patched the code of vscode and were known to cause crashed. With version 4.0 vscode-icons uses viscose's official icons support. Pls install a vanilla version of vscode (the one you have is patched) and the latest version of the extension.
