### ISSUE TITLE
Node debugger sometimes continues rather than steps over

### ISSUE THREAD

**Issue by mousetraps** [Microsoft/vscode#17135]
- VSCode Version: Code 1.8.0 (38746938a4ab94f2f57d9e1309c51fd6fb37553d, 2016-12-13T17:45:32.595Z)
- OS Version: Windows_NT ia32 10.0.14965
- Node version: v6.9.0 (64-bit)

![2016-12-13_12-46-39](https://cloud.githubusercontent.com/assets/762848/21158695/1504d9c6-c133-11e6-8eb4-59b99341b388.gif)

Steps to Reproduce:
1. set up project as follows (and npm install twit)
```js
// blah.js
var Twit = require('twit');
console.log('should stop here');
console.log('stops here instead')
```

```json
// launch config
{
            "name": "Launch Node",
            "type": "node",
            "request": "launch",
            "program": "${workspaceRoot}/blah.js",
            "stopOnEntry": true,
            "args": [],
            "cwd": "${workspaceRoot}",
            "preLaunchTask": null,
            "runtimeExecutable": null,
            "runtimeArgs": [
                "--nolazy"
            ],
            "env": {
                "NODE_ENV": "development"
            },
            "console": "internalConsole",
            "sourceMaps": false,
            "outDir": null
        }
```

2. F5 to start debugging, should stop at first breakpoint
3. Wait 5 seconds or so (it's a timing thing, doesn't repro consistently)
3. Press step over button

Expected: stops at first `console.log` statement
Actual: continues until next breakpoint

**Comment by roblourens** [comment]
Haven't been able to repro it, on MacOS or Windows

**Comment by mousetraps** [comment]
Try twit@2.2.3 - just updated, and apparently it doesn't trigger on the latest version (2.2.5) for some reason

**Comment by roblourens** [comment]
I couldn't repro it with that version either. If you see it again, grab me to debug?
