### ISSUE TITLE
Find widget screen cheese

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#171405]
* open code editor
* open find widget
* resize the editor to be very narraw
* 🐛 the find widget wraps and shows screen cheese

https://user-images.githubusercontent.com/1794099/212654260-3a86d133-509d-46b3-80f4-1219f6e2a16b.mov

**Comment by rebornix** [comment]
Reproduced this issue on previous version. The dynamic width check stopped working for the min-width. Will tackle it in debt week.

**Comment by rebornix** [comment]
Fixed via https://github.com/microsoft/vscode/pull/175958 by @mjbvz ❤️
