### ISSUE TITLE
Unable to paste a file into my client folder

### ISSUE THREAD

**Issue by jerkd3** [microsoft/vscode#171459]
Type: <b>Performance Issue</b>

I have copied a folder to paste in my client folder, but I don't have the paste option, it is grayed out. How can I paste my folder into the client folder.

VS Code version: Code 1.74.3 (97dec172d3256f8ca4bfb2143f3f76b503ca0534, 2023-01-09T16:59:02.252Z)
OS version: Windows_NT x64 10.0.19045
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz (4 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|7.88GB (2.62GB free)|
|Process Argv|--crash-reporter-id 33cecf2a-c7f3-4aa5-96c9-a57b941b604e|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    2	   101	  7952	code main
    0	    25	  3632	   crashpad-handler
    0	   174	  5828	   window (Get Started - openai_codex - Visual Studio Code)
    0	    79	  6380	   window (undefined)
    1	   150	 10560	   gpu-process
    0	    38	 11280	   utility-network-service
    0	    79	 13092	   extensionHost
    4	    95	 13352	   issue-reporter
    0	    91	 14460	   shared-process
    0	    72	  9120	     ptyHost
    0	     5	  4372	       winpty-process
    0	     7	  8812	         console-window-host (Windows internal process)
    0	    47	 13456	         C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe
    0	    71	 12852	     fileWatcher
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (Get Started - openai_codex - Visual Studio Code)
|    Folder (openai_codex): 0 files
|      File types:
|      Conf files:;
```

</details>
Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
azure-dev_surveyone:30548225
pyindex848:30577860
nodejswelcome1cf:30587006
282f8724:30602487
f6dab269:30613381
fim-prod:30623723

```

</details>

**Comment by lramos15** [comment]
\duplicate https://github.com/microsoft/vscode/issues/164
