### ISSUE TITLE
Missing dependencies in rpm package

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#17142]
https://github.com/Microsoft/vscode/issues/13089 but for .rpm

Notes:

- Chromium deps: https://cs.chromium.org/chromium/src/chrome/installer/linux/rpm/expected_deps_i386?dr=C&q=libxss.so.1&sq=package:chromium
- `ldd /usr/share/code-insiders/code-insiders` can fetch a list of deps

**Comment by Tyriar** [comment]
To verifier: Please verify installation works fine on both a 32-bit and 64-bit CentOS (I tested using Fedora when implementing).

**Comment by chrmarti** [comment]
@Tyriar Seeing this on CentOS 8.6 64-bit live CD:

![screen shot 2017-01-27 at 2 41 55 pm](https://cloud.githubusercontent.com/assets/9205389/22390273/e8ab4f92-e49e-11e6-94cf-738e7deae8e4.png)

**Comment by chrmarti** [comment]
![screen shot 2017-01-27 at 2 45 32 pm](https://cloud.githubusercontent.com/assets/9205389/22390359/4d43b6f6-e49f-11e6-85f7-92251ecdcabb.png)

**Comment by chrmarti** [comment]
Consistently so for the 32-bit version:

CentOS 8.6 32-bit live CD:
![screen shot 2017-01-27 at 2 59 34 pm](https://cloud.githubusercontent.com/assets/9205389/22390676/51e81d6c-e4a1-11e6-9e32-e813d03af35f.png)

![screen shot 2017-01-27 at 3 00 47 pm](https://cloud.githubusercontent.com/assets/9205389/22390690/70ce1d62-e4a1-11e6-9eac-a3558fffd88a.png)

**Comment by chrmarti** [comment]
CentOS 7 build 1611 64-bit live DVD installs the package, but the crashes on startup of VSCode. --verbose shows:
![screen shot 2017-01-27 at 3 14 56 pm](https://cloud.githubusercontent.com/assets/9205389/22391012/7801a016-e4a3-11e6-9620-07a546be5ce2.png)

And:
![screen shot 2017-01-27 at 3 15 58 pm](https://cloud.githubusercontent.com/assets/9205389/22391042/9c2b0180-e4a3-11e6-9af7-4f3455a43494.png)

Changing the permissions as asked for fixed the problem. Not sure if there is a way to avoid that, but other applications don't seem to require that change in permissions.

**Comment by goanpeca** [comment]
For centos 7 (full) getting

```
error: Failed dependencies:
	libXss.so.1()(64bit) is needed by code-1.19.3-1516876593.el7.x86_64
```

**Comment by Tyriar** [comment]
Another report https://github.com/microsoft/vscode/issues/86437, just needed `libX11-xcb`

**Comment by mMerlin** [comment]
Amend that *only* `libX11-xcb`.  That was enough to get vscode to run, but further usage encountered errors about no icu package on the system.  Installing `libicu` seems to have cleared that up.

**Comment by joaomoreno** [comment]
@Tyriar @deepak1556 Can we close this?

**Comment by deepak1556** [comment]
I haven't looked into this recently but I think we should be good on this. Something I like to eventually setup is a way to update the dependency during runtime version updates.

**Comment by Tyriar** [comment]
This never got fixed and is still a problem afaik. Certain distros don't include some base deps and VS Code will install successfully but not launch without manually installing the deps it complains about.

**Comment by deepak1556** [comment]
@Tyriar is it only `libX11-xcb` mentioned in https://github.com/microsoft/vscode/issues/17142#issuecomment-562813349 ? Do we need to validate the dependency list for the current runtime version ?

**Comment by Tyriar** [comment]
@deepak1556 I don't know how you get the dependency list for a binary but we need to do that and update it, I think there's some commands to do this. I think there's more than just `libX11-xcb`.

**Comment by mMerlin** [comment]
In my case (2 years ago), `liabX11-xcb` plus `libicu` were enough.
