### ISSUE TITLE
Organize Imports is not detecting used imports in svelte files

### ISSUE THREAD

**Issue by skamansam** [microsoft/vscode#171443]
Type: <b>Bug</b>

Steps to Reproduce:
1. Create a new .svelte file usign typescript:
```
<script lang="ts">
  import type { Hst} from '@histoire/plugin-svelte';
  export let Hst: Hst;
</script>

<Hst.Story>
  Hello!
</Hst.Story>
```
2. run "Organize Imports" from the command palette

*Expected Outcome*: 
nothing changes

*Actual Outcome*:
The code gets changes to:
```
<script lang="ts">
  import type { Hst as Histoire } from '@histoire/plugin-svelte';
</script>

<Hst.Story>
  Hello!
</Hst.Story>
```

Special Note:
I thought there may be a type conflict, so I changed the code to be:
```
<script lang="ts">
  import type { Hst as Histoire} from '@histoire/plugin-svelte';
  export let Hst: Histoire;
</script>

<Hst.Story>
  Hello!
</Hst.Story>
```
 But the result was the same.

VS Code version: Code - Insiders 1.75.0-insider (6d40104789d03d41b8866a1e57847dae14c5cf0d, 2023-01-12T05:34:42.226Z)
OS version: Linux x64 6.0.15-300.fc37.x86_64
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3770K CPU @ 3.50GHz (8 x 1642)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|1, 1, 1|
|Memory (System)|15.51GB (1.04GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|gnome-xorg|
|XDG_CURRENT_DESKTOP|GNOME|
|XDG_SESSION_DESKTOP|gnome-xorg|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (40)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|3.0.2
Bookmarks|ale|13.3.1
vulgocode-color-theme|ale|0.6.12
vscode-color|ans|0.4.5
svelte-intellisense|ard|0.7.1
emojisense|bie|0.9.1
vscode-tailwindcss|bra|0.9.5
vscode-toggle-quotes|Bri|0.3.6
gitignore|cod|0.9.0
vscode-quick-select|dba|0.2.9
gitlens|eam|13.2.0
EditorConfig|Edi|0.16.4
prettier-vscode|esb|9.10.4
vscode-diff|fab|1.4.2
vscode-svelte-snippets|fiv|0.5.0
vscode-pull-request-github|Git|0.56.0
grepper|Gre|0.0.7
todo-tree|Gru|0.0.220
vscode-insertdatestring|jsy|2.3.1
vscode-codemetrics|kis|1.26.1
blockman|leo|1.7.1
dotenv|mik|1.0.1
file-downloader|min|1.0.12
test-adapter-converter|ms-|0.1.6
indent-rainbow|ode|8.3.1
svelte-autoimport|piv|1.0.4
material-icon-theme|PKi|4.23.1
svelte-preview|Raf|2.5.5
vscode-yaml|red|1.11.0
vscode-sort-json|ric|1.20.0
partial-diff|ryu|1.4.3
vscode-stable-sort|sgr|1.2.2
code-spell-checker|str|2.14.0
svelte-vscode|sve|107.0.1
vscode-json-stable-stringify|Tra|1.2.1
errorlens|use|3.6.0
intellicode-api-usage-examples|Vis|0.2.6
vscodeintellicode|Vis|1.2.30
vscode-conventional-commits|viv|1.25.0
rainbow-tags|vol|0.4.1

</details>

**Comment by mjbvz** [comment]
Please file this against the svelte extension
