### ISSUE TITLE
When the width of terminal tabs is very small, the close button of Panel disappears

### ISSUE THREAD

**Issue by tamuratak** [microsoft/vscode#171422]
Version: 1.75.0-insider (Universal)
Commit: 8be8d96ab86ed4077df554eb62727484d454699f
Date: 2023-01-16T05:20:55.333Z
Electron: 19.1.9
Chromium: 102.0.5005.194
Node.js: 16.14.2
V8: 10.2.154.23-electron.0
OS: Darwin arm64 20.6.0
Sandboxed: Yes
Steps to Reproduce:

1.  Move terminal to Primary Panel.
2. Make the tab of terminal very small. Then, the trash button move to the header.
3. Make the window small.
4. The close button of Primary Panel disappears.

![panelclose](https://user-images.githubusercontent.com/10665499/212695905-1a24dc2c-239c-4a71-9eb8-619869db0c96.png)

![withclose](https://user-images.githubusercontent.com/10665499/212696688-0df8938f-57dc-4d4a-b16c-724f2f6b7814.png)

We can see the close button moved out of the window.

**Comment by Tyriar** [comment]
Related to general views

**Comment by benibenj** [comment]
Has been fixed since
