### ISSUE TITLE
Auto start watch task

### ISSUE THREAD

**Issue by normalser** [Microsoft/vscode#17147]
- VSCode Version: Code - Insiders 1.8.0-insider (2abfc207828739bd5b10d0bb8dbfea13506cfc69, 2016-12-13T09:48:23.832Z)
- OS Version: Darwin x64 16.3.0

It would be great if VSCode could auto start watch tasks when the project/folder (that has `.vscode/tasks.json` in it) gets opened  - (maybe setting `autoStart: true` in tasks.json) 

Many times (especially being on `insiders` which frequently asks to restart - sometimes more than once a day) I find myself forgetting to start TS Watch task - and scratching my head why the changes made in code are not being reflected.

Combined with watch task indicator would be very helpful - https://github.com/Microsoft/vscode/issues/8513

**Comment by dbaeumer** [comment]
Nice idea.

**Comment by rotemdan** [comment]
For close to a year now I've been using the [Blade Runner](https://marketplace.visualstudio.com/items?itemName=yukidoi.blade-runner) extension that does exactly this. It is very surprising this isn't a function that's provided natively by VS Code. I'm actually at a point I can't even imagine how could I "live"  without this functionality.

**Comment by rotemdan** [comment]
Here's the source code of that extension:

```ts
import * as vscode from 'vscode'; 

export function activate(context: vscode.ExtensionContext) {
	vscode.commands.executeCommand("workbench.action.tasks.build");
}
```

;)

**Comment by calebmer** [comment]
This would be great for providing an awesome experience in project specific workflows.

**Comment by uitgewis** [comment]
It would be preferable if this supports one to specify it per-task for multiple tasks.

**Comment by philfontaine** [comment]
I developed this extension where you can specify the tasks you want to run/debug: [AutoLaunch](https://marketplace.visualstudio.com/items?itemName=philfontaine.autolaunch)

**Comment by DanTup** [comment]
If this is built into Code, it'd be great if this could support contributed tasks too.

**Comment by cyrilletuzi** [comment]
Would be really useful. Do we agree it would allow to launch a command like `npm start`?

**Comment by dbaeumer** [comment]
Yes, it will work for contributed tasks too.

**Comment by cyrilletuzi** [comment]
Will we be able to see the task running? In projects like Angular, it's important to see the compilation running, to see errors reported.

**Comment by dbaeumer** [comment]
The task will be executed in the terminal as all tasks. Whether the task terminal comes to front or not will depend on the presentation setting of the task (which users can customize)

**Comment by mungojam** [comment]
I may have misunderstood, but isn't this a bit of a security risk? I don't expect when I clone a repository off the net for it to be able to automatically run arbitrary tasks when I open it in VS Code.This change seems to enable that attack vector.

It's different if I choose to debug it or run tests on it or something, where I know there is a risk.

**Comment by Zyphrax** [comment]
@mungojam A notification like that would also be a great solution for the typescript.tsdk security concern (see [this comment](https://github.com/Microsoft/vscode/issues/26046#issuecomment-341838312)). Would it be possible to apply it there too?

**Comment by alexr00** [comment]
@mjbvz for FYI. It looks similar.

**Comment by alexr00** [comment]
@markfinlabs, thanks for the suggestion! Can you open a new feature request for it please?

**Comment by markfinlabs** [comment]
Sure, no problem. See https://github.com/Microsoft/vscode/issues/65986.
