### ISSUE TITLE
Feature Request: Hot Key for Clear Results - Interactive Window

### ISSUE THREAD

**Issue by DonJayamanne** [Microsoft/vscode#17141]
_From @drcrook1 on December 13, 2016 15:0_

This would be a pretty slick feature.

Also, changing the red text to a brighter red for VS code folks who use the dark theme :D

_Copied from original issue: DonJayamanne/pythonVSCode#578_

**Comment by kieferrm** [comment]
@DonJayamanne Which one is the "interactive window"?
