### ISSUE TITLE
Calling workbench.action.togglePanel breaks terminal scrollbar

### ISSUE THREAD

**Issue by GuskiS** [microsoft/vscode#171482]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.74.3
- OS Version: Windows_NT x64 10.0.19045

Steps to Reproduce:

1. bind `workbench.action.togglePanel` command to button
2. make sure terminal has scrollbar
3. toggle panel on/off and see that scrollbar disappears

**Comment by meganrogge** [comment]
we only show the scrollbar on hover/focus

**Comment by GuskiS** [comment]
@meganrogge Yes, but scrollbar is not useable anymore after hiding and showing panel, even when hovering terminal.

**Comment by meganrogge** [comment]
https://user-images.githubusercontent.com/29464607/215820042-c4a1b65f-c49d-43b3-ae07-1e907b60c881.mov

**Comment by GuskiS** [comment]
[screen-capture.webm](https://user-images.githubusercontent.com/3505777/216023092-2b1866a7-2dd8-473d-9c58-b917bf22ada2.webm)
As you can see at the end of video, I'm unable to scroll anymore, nor does the actual scrollbar show. Only way to make scrollbar work again is to press enter in terminal to add new line.

**Comment by meganrogge** [comment]
does changing `terminal.integrated.gpuAcceleration` help?

also, at the end of your gif you don't scroll - what happens if scroll with the mouse wheel?

**Comment by GuskiS** [comment]
Changing `terminal.integrated.gpuAcceleration` to `off` or `canvas` fixes the scrollbar issue, but the performance is terrible 😩

At the end of the video I was trying to scroll with mouse wheel - didn't work, then I pointed to the side that scrollbar has disappeared thus preventing any scrolling.

**Comment by meganrogge** [comment]
not sure why this wouldn't work for you and cannot repro so can't investigate. maybe @tyriar has an idea?

**Comment by Tyriar** [comment]
I guess we must not be relaying out something when you toggle the panel. The maximized panel could be playing a role in the repro too?

**Comment by GuskiS** [comment]
If the panel is not maximized, then scrollbar jumpts to top, which I think is incorrect as well (should remain in the same spot as I left it) but it also somehow breaks: I'm unable to scroll to whole bottom of the terminal, unless I again add new line by pressing enter. I can make video tomorrow if needed.

**Comment by GuskiS** [comment]
https://user-images.githubusercontent.com/3505777/216440769-9c21e172-7043-4c7b-a39a-7246f025d55d.mov

Ok, I think I found something useful, let me describe the video a bit:
1. 0 -> 10sec I'm showing that after toggling panel, scrollbar disappears, just like previously
2. after that I'm showing that I maximize panel, and you can see that there is no scrollbar because the content is not enough, so add couple of more lines
3. after that I show that with scrollbar in maximize mode in half mode scrollbar starts to work - opposite what we saw at the begining of video
4. however, it is not fully working (as mentioned in my previous comment). Around ~32sec I'm showing the size of scrollbar and they press enter(insert new line in terminal) and show the scrollbar size again - it has changed

I would suspect that terminal/panel is getting wrong size or number of lines used and then calculates the scrollbar incorrectly, maybe even ignoring that is max/half size 🤷‍♂️ Hope this helps.

**Comment by Tyriar** [comment]
The scroll bar implementation changed since this was reported, can not reproduce this anymore.
