### ISSUE TITLE
Typescript server repetitively "initializing language features" causing high CPU usage at idle

### ISSUE THREAD

**Issue by mpearce-bain** [microsoft/vscode#171448]
Type: <b>Bug</b>

#### Description
When working in a Svelte repository with a TS and Svelte file open, VSCode begins rapidly flashing the "initializing JS/TS language features" notification in the bottom LH bar. I also notice the notification bell in the bottom RH bar flickering on and off with a new notification.  This drives high CPU usage and noticeably slows down intellisense in my repo.

This behavior doesn't appear to be linked to any user input other than opening both `*.svelte` and `*.ts` files concurrently, and it will continue indefinitely until the VSCode instance is restarted. Running the "Typescript: Restart Language Server" command will temporarily halt the behavior, but it resumes within 30s afterward. If TS logging is turned on, the logs will grow indefinitely in size (in one instance I had a 2GB log file in <5 minutes).

Would anyone be able to suggest a potential next troubleshooting step?

#### Troubleshooting Attempts
* Restart TS Language Server
* Restart VSCode
* Clean Install of VSCode
* Update to latest nightly version of TS

#### Versioning
VS Code version: Code 1.74.3 (97dec172d3256f8ca4bfb2143f3f76b503ca0534, 2023-01-09T16:59:02.252Z)
OS version: Windows_NT x64 10.0.19044
Modes:
Sandboxed: No
TypeScript: 4.9.4 and 5.0.0-dev (observed behavior in both versions)

#### Logs
[tsserver.log](https://github.com/typescript-language-server/typescript-language-server/files/10428374/tsserver.log)

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz (8 x 2995)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.71GB (16.00GB free)|
|Process Argv|--folder-uri file:///c%3A/Users/65166/Documents/Code/peg-python-data-automation --crash-reporter-id c471dd02-b8fc-45d0-b70a-bf8322916dc3|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
svelte-vscode|sve|107.0.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscoreces:30445986
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
azure-dev_surveyone:30548225
pyindex848cf:30577861
nodejswelcome1:30587005
3biah626:30602489
f6dab269:30613381
fim-prod:30623723

```

</details>

**Comment by mjbvz** [comment]
If this only happens with the svelte extension enabled, please start by filing this issue against them
