### ISSUE TITLE
CoffeeScript parser error with forward slash

### ISSUE THREAD

**Issue by Simon-Briggs** [Microsoft/vscode#17149]
- VSCode Version: 1.7.2
- OS Version: OS X

Steps to Reproduce:

1. Create a .coffee file
2. Use a forward slash without a trailing space makes the rest of the file turn red.

Possibly assumes it is a  reg exp?

![screen shot 2016-12-14 at 11 12 08](https://cloud.githubusercontent.com/assets/17428768/21167215/3772d33a-c1ee-11e6-93d5-b8bf418bfab7.png)

I see the issue below is exactly the same as this, but closed in April?
https://github.com/Microsoft/vscode/issues/499

**Comment by aeschli** [comment]
Yes, that's the same issue. It has been moved to textmate/coffee-script.tmbundle#8 and is still open
