### ISSUE TITLE
Builtin extension "vscode.javascript" now provides more than it says

### ISSUE THREAD

**Issue by RobbyCBennett** [microsoft/vscode#171433]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.74.3
- OS Version: Windows 10

The description for the extension `vscode.javascript` is "Provides snippets, syntax highlighting, bracket matching and folding in JavaScript files." However, after updating the editor, this extension provides more features which are not described. To me, these features only add clutter and make it hard to see my selections. All I want out of this extension is syntax highlighting.

Some problems which add clutter:
- Put your typing cursor on a token, and it gets hard to read because of a fake highlight.
- Move your mouse cursor on a token (for example, `Promise.all();`), and a giant popup window appears.
- Warnings show up in my code with a dotted underline (for example `require('vscode');`).
- Errors and warnings show up while I'm in the middle of writing a line of code.

Steps to Reproduce:

1. Have the `@builtin javascript` extension with the identifier `vscode.javascript`
2. Open a javascript file

**Comment by RobbyCBennett** [comment]
Proposed solutions:
- Separate the intellisense/linting features from the extension.
- Add some checkbox settings to disable intellisense/linting features.

**Comment by gjsjohnmurray** [comment]
Did you investigate whether any of those features are coming from the builtin extension called "TypeScript and JavaScript Language Features", whose ID is `vscode.typescript-language-features`?

The "Feature Contributions" tab of that extension lists 122 settings that it contributes. Some of these seem to relate to JavaScript files.

**Comment by RobbyCBennett** [comment]
Thank you for the response. I have already disabled that extension. All of the UX clutter issues I'm experiencing go away when I disable JavaScript Language Basics. I only use it for the syntax highlighting. I do not want it to mess up what I'm typing nor do I want it to add visual clutter.

**Comment by RobbyCBennett** [comment]
This was not the solution. I found the solution.

I had installed an Extension called Vue Language Features (Volar) with the `vue.volar` identifier. This was actually the problem, not an update to VSCode. Even though `vscode.typescript-language-features` was disabled in the UI, it was still secretly enabled by `vue.volar`.

The solution is to disable `vue.volar`.

**Comment by johnsoncodehk** [comment]
You can add `"volar.takeOverMode.extension": null` setting to disable it.

**Comment by RobbyCBennett** [comment]
Thanks
