### ISSUE TITLE
No unindent after indentation timeout

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#171466]
Build: https://dev.azure.com/monacotools/a6d41577-0fa3-498e-af22-257312ff0545/_build/results?buildId=199618
Changes: https://github.com/Microsoft/vscode/compare/1379f03...4d88232

```
The followings tests are failing:
 - Inline Completions No unindent after indentation (reason: Timeout of 5000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.)

```

**Comment by hediet** [comment]
This test never failed before. Maybe a weird test running that got stuck in GC.

Let me close this issue, but keep it in mind if it happens again.
