### ISSUE TITLE
Is it possible to have an extension with debugger contribution along with other contribution types

### ISSUE THREAD

**Issue by ivanbuhov** [Microsoft/vscode#1714]
Hi all,
I have a VSCode extension with debugger contribution and I want to add also custom commands to the extension. AFAIK, extension with debug adapter will be loaded in a separate process and will be activated when a debug session is started. 
Is it possible to add custom commands in the extension and configure them also to be activation events? 
Is it possible to call these commands from my debug adapter code?
If yes, I guess I have to set the entry point of my extension spacifying the `main` option in `package.json`, but after doing it VSCode stops recognising my extension as a debugger when trying to generate default `launch.json`.

**Comment by bpasero** [comment]
@weinand @isidorn fyi

**Comment by felixfbecker** [comment]
Doesn't the Go extension do this?

**Comment by weinand** [comment]
A debugger contribution is not special and can coexist with other contributions.
And yes, the Go extension is a good example for this.
But today it is not possible to call into those other contributions from the debug adapter. This is something we want to support in the future.

**Comment by ivanbuhov** [comment]
Thanks :)
