### ISSUE TITLE
VSCode not able to sort import in ascending order

### ISSUE THREAD

**Issue by sanket-bhalerao** [microsoft/vscode#171438]
Type: <b>Bug</b>

on saving file the imports used to get sorted in ascending order, however now its not getting sorted that way

![image](https://user-images.githubusercontent.com/9264813/212731114-39579c93-3e21-488a-8f05-35d4481bb646.png)

I can reproduce this after disabling extensions as well.

VS Code version: Code - Insiders 1.75.0-insider (7ef08adcc620ba1e4fcda7530c8bc907264acae9, 2023-01-16T11:28:36.819Z)
OS version: Windows_NT x64 10.0.19044
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.82GB (2.70GB free)|
|Process Argv|--crash-reporter-id e5294b27-02c9-4438-b8f3-90acb1091b3b|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (24)</summary>

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|15.1.0
atlascode|atl|3.0.0
vscode-markdownlint|Dav|0.49.0
vscode-eslint|dba|2.2.6
githistory|don|0.6.19
gitlens|eam|13.2.0
EditorConfig|Edi|0.16.4
prettier-vscode|esb|9.10.4
vscode-drawio|hed|1.6.4
output-colorizer|IBM|0.1.2
fluent-icons|mig|0.0.18
vscode-scss|mrm|0.10.0
vscode-edge-devtools|ms-|2.1.1
vscode-typescript-next|ms-|5.0.202301100
angular-console|nrw|17.28.0
fabric8-analytics|red|0.3.6
vscode-xml|red|0.24.2023011403
vscode-yaml|red|1.11.0
sonarlint-vscode|Son|3.13.0
code-spell-checker|str|2.14.0
vscode-stylelint|sty|1.2.3
vscodeintellicode|Vis|1.2.30
vscodeintellicode-completions|Vis|1.0.20
codetour|vsl|0.0.58

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vslsvsres303:30308271
pythonvspyl392:30422396
pythontb:30258533
vsc_aacf:30263846
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscod805:30301674
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30404738
cppdebug:30492333
vscaat:30438846
vsclangdf:30492506
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30618038
pylantcb52:30590116
pyindex848:30611229
nodejswelcome1:30587009
pyind779:30611226
pythonsymbol12cf:30622697
fim-prod:30623723

```

</details>

**Comment by mjbvz** [comment]
This sounds like it is either an issue with your settings or with one of your extensions 

Please investigate these first

**Comment by sanket-bhalerao** [comment]
looks like that, 
i am using the typescript nightly extension, and when I switch to vscode typescript version I get this issue.
