### ISSUE TITLE
files.watcherExclude setting does not work without exact path - with multiple node_modules

### ISSUE THREAD

**Issue by yuvalgershon** [microsoft/vscode#171435]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.74.3
- OS Version: Windows_NT x64 10.0.19044

Steps to Reproduce:

1. Connect with microsoft Remote-SSH extension
2.  Using `open Folder` project.
3. Project contains multiple node_modules directories with files.
path is relative to project root.
* ui/my_app/node_modules/ ( file count: 119,000 )  
* ui/my_app/server/app/node_modules/ ( file count: 30,000 ) 
* ui/my_app/client/node_modules/ ( file count: 17,000 )
4.  warning message pops up: `unable to watch for file changes in this large workspace` .
5. I tried adding to `files.watcherExclude` in project level settings, all examples:
* "**/node_modules/**": true,
* "**/node_modules/*/**": true,
* "**/node_modules/": true,
Reloading window would keep throwing warning.
6. fix: edit same settings to include each node_modules relative path individually.
7. reload window, problem fixed, no warning message.

I also verified that there is no links anywhere leading to the node_modules directories.
I cannot include project for reference. 

Remote SSH OS info: Linux my-host 5.4.0-1096-gcp #105~18.04.2-Ubuntu SMP Tue Nov 29 11:33:58 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
![image](https://user-images.githubusercontent.com/71215703/212722316-d11b6b84-d4cc-45bc-934c-703b9d2b7da0.png)

**Comment by bpasero** [comment]
https://github.com/microsoft/vscode/issues/137872 added support to use glob patterns, so it should be fine now, even with the default settings and nested `node_modules` folders. Can you verify using insiders?

You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by yuvalgershon** [comment]
Hi thanks I will give it a try, I think it should be mentioned here [docs](https://code.visualstudio.com/docs/setup/linux#_visual-studio-code-is-unable-to-watch-for-file-changes-in-this-large-workspace-error-enospc), which clearly refers to the native linux problem but uses glob in it's solution.

Also looking at the issue you sent, we can see it "merged" a month ago, but it's actually only merged to the insiders build.
I think it's unnecessarily confusing to a newcomer, and should be better signposted.

**Comment by tcitta** [comment]
This is still not working for me with the latest VSCode released today. 

Local OS: Windows 11
Remote SSH host OS: centOS 7.5

I'm using a multi-root workspace through the Remote SSH extension. My multi-root workspace contains:

- firstDir
- secondDir
- thirdDir

Where the file tree on disk is:

- /home/scratch.tim/repo/rel/firmware/firstDir
- /home/scratch.tim/repo/secondDir
- /home/scratch.tim/repo/resource/thirdDir

This is a client view into a large perforce depot, so opening `.../repo` as a workspace is not an option.

I cannot exclude _secondDir_ using **any** documented glob pattern. I **must** specify the absolute path to the directory, else I receive the `unable to watch for file changes in this large workspace` popup.

- secondDir
- **/secondDir
- **/secondDir/*
- **/secondDir/**
- **/secondDir/*/**
- ${workspaceFolder:secondDir}
- ${workspaceFolder:secondDir}/**
- ${workspaceFolder:secondDir}/*/**

Am I missing something? All the docs and comments on this thread as well as https://github.com/microsoft/vscode/issues/137872 state that at least one of the above patterns should work.
