### ISSUE TITLE
Environment variable collection info not showing in single terminal tab

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#171498]
Repro:

- Activate `terminal-sample` from `vscode-extension-samples`
- Open a terminal
- Type in it
- Run the "Update environment" command

Actual when there is a single terminal tab:

![image](https://user-images.githubusercontent.com/2193314/212909125-794fccfb-2b3c-4fb3-b8b4-0cdc2b1c3b1f.png)

Expected to see this message:

![image](https://user-images.githubusercontent.com/2193314/212909073-9a2f6a79-4a06-479d-a6f1-3c6e6b2cb86c.png)

**Comment by DanTup** [comment]
@Tyriar it's not clear to me from the second screenshot above how the user "fixes" the issue. It says an extension wants to change the environment variables, but it doesn't seem like there's any button/link to click to do that?

**Comment by Tyriar** [comment]
@DanTup looks like we regressed and the actions no longer show up:

![image](https://user-images.githubusercontent.com/2193314/212916984-c46b29e8-28f4-4727-8c97-509f9e229d37.png)

I'll fix in https://github.com/microsoft/vscode/pull/171500

FYI @rzhao271
