### ISSUE TITLE
Add activity bar location settings

### ISSUE THREAD

**Issue by DanDanilyuk** [microsoft/vscode#171462]
The activity bar takes up an huge amount of space in the UI especially when working with the explorer tab open.
Many users were using the [Customize UI Plugin](https://marketplace.visualstudio.com/items?itemName=iocave.customize-ui) to get around the issue with so much joy but it seems to have been Microsoft'd 😿.

Willing to buy a beer, sponsor, or donate to a charity of choice of the contributor that get's this done. Please don't let us down like this Microsoft 🙏 

Is there any way to implement the same solution using something like a `workbench.activityBar.location` with the following options:
  - `default`: Current default location
  - `bottom`: Activity bar located on the bottom for screen real estates on laptops, monitors, etc.

Screenshot for design reference:
![](https://raw.githubusercontent.com/iocave/customize-ui/master/screenshot.png)

**Comment by gjsjohnmurray** [comment]
Did you try this extension?

https://marketplace.visualstudio.com/items?itemName=Gruntfuggly.activitusbar

**Comment by DanDanilyuk** [comment]
> Did you try this extension?
> 
> https://marketplace.visualstudio.com/items?itemName=Gruntfuggly.activitusbar

Just downloaded, installed, and configured it to match my extensions. It's a descent solution but I really think VSCode would be more pleasant with the location option. I wanted to say thank you for a great temporary solution.

**Comment by gjsjohnmurray** [comment]
All kudos to the author @Gruntfuggly

**Comment by sbatten** [comment]
could be merged with https://github.com/microsoft/vscode/issues/141391

**Comment by DanDanilyuk** [comment]
@sbatten I was trying to test the insider build but wasn't able to find anything in [#141391](https://github.com/microsoft/vscode/issues/141391) or related issues that point a "workbench.activityBar.position" setting. I would love to see how it done and would be happy do do some testing but don't see anything related to this.
