### ISSUE TITLE
Menu too thin with WCO on Mac OS

### ISSUE THREAD

**Issue by a-stewart** [microsoft/vscode#171415]
Hi,

When using Mac OS and Chrome, if you install vscode.dev as a PWA and use window controls overlay, the menu bar height is less than that of the window control overlay, which creates a slightly odd disjoint.

![image](https://user-images.githubusercontent.com/150152/212675232-b251f426-a5c0-44f8-be89-cd4d4a9a8504.png)

Looking at the tools, it seems like there is some CSS which uses the browser environment variable, but also in there are some hard coded 35px values.

![image](https://user-images.githubusercontent.com/150152/212677225-0e5c4f5e-c501-4b7f-9ae9-7203a5fba982.png)

**Comment by tomayac** [comment]
You should use the new `env(titlebar-area-*)` variables so the dimensions are right on all platforms. See the screenshot below for how I have done this in the [demo](https://window-controls-overlay.glitch.me/) for the [article](https://web.dev/window-controls-overlay/#moving-content-into-the-title-bar).

![image](https://user-images.githubusercontent.com/145676/217795717-a45d6eb0-a959-45d2-9e11-608d08f5e933.png)

![image](https://user-images.githubusercontent.com/145676/217795864-d4255134-811d-4758-a385-43786de1325e.png)

**Comment by bpasero** [comment]
This seems to look OK for me now?

![image](https://github.com@microsoft/vscode/assets/900690/53901b30-4063-47f2-a324-4d7dbebbb150)

@a-stewart can you check

**Comment by a-stewart** [comment]
It still seems to be broken on insiders.vscode.dev (using Chrome).

![image](https://github.com/microsoft/vscode/assets/150152/432f1b5f-9455-405d-b5d8-5002ee37adcc)

Looking at the code, it still seems to be hard coded at `35px`, rather than using `env(titlebar-area-height, 35px)` which would handle the case where the titlebar is larger.

What is interesting is that the traffic lights seem to be a bit high in your screenshot, implying that the window is trying to compress them into a thinner bar?

What browser are you using in that screenshot?

**Comment by bpasero** [comment]
I was using Edge.

**Comment by a-stewart** [comment]
At a guess, the Edge titlebar is less than 35px then, which explains why the traffic lights aren't vertically centered, but the Chrome titlebar is thicker.

I have an idea for a fix which I'll test and send you a PR tomorrow.

**Comment by a-stewart** [comment]
@bpasero - I've sent a PR for this: https://github.com/microsoft/vscode/pull/211440
