### ISSUE TITLE
Context keys for `resourcePath` and `resourceDirname` need to respect remote OS

### ISSUE THREAD

**Issue by EstherPerelman** [microsoft/vscode#171417]
- VS Code Version: 1.74.3
- system: WSL / Codespaces

The same worked for me on windows and mac

Steps to Reproduce:

1. Install the next [vsix](https://github.com/microsoft/vscode/files/10425823/zip.zip) (which was built according to the example in https://github.com/microsoft/vscode/issues/107725#issuecomment-700909597)
2. open any workspace with `src` folder inside (or create `src` folder yourself)
3. right click the src folder - on windows/mac: you will see on the bottom of the menu - `~~~Test Section~~~` but on remote you won't see anything,
on windows:
![image](https://user-images.githubusercontent.com/71729183/212680597-031b08c6-5813-4068-a08d-059e5258adef.png)

**Comment by bpasero** [comment]
In order to understand if this is a bug on our end, this needs a minimal extension to reproduce and exhibit the issue.

**Comment by EstherPerelman** [comment]
@bpasero I'm not sur what you expect as a minimal extension, but I can tell that I also debugged vscode and found that [when setting the recourceDirname and recourcePath values](https://github.com/microsoft/vscode/blob/ab1a31add4608f484d555e3c791f03321a4dda5f/src/vs/workbench/common/contextkeys.ts#L227-L228) - the value which set is the `fsPath` which is null in case of remote

**Comment by bpasero** [comment]
`URI.fsPath` will always return a `string`, never `null`: 

https://github.com/microsoft/vscode/blob/ab0f89141e701154afd5728aa893ec94704003bf/src/vs/base/common/uri.ts#L585

I think this issue must be something else, not what you debugged.

**Comment by EstherPerelman** [comment]
@bpasero sorry! you are right I missed up with the `_fsPath` which show me null on hover in debug mode, 
so it  looks like an issue with comparing of a path with backward-slashes(the `.fsPath`) to a path with forward-slashes (as I mentioned before when I modified the code to set the `uri.path` it worked perfectly), you can see in the screenshot that `false` is returned for comparing the `item` to the `source` in [ContextKeyInExpr#evaluate](https://github.com/microsoft/vscode/blob/85f62d7aca69bed5315f8354b4bca70031d3ece9/src/vs/platform/contextkey/common/contextkey.ts#L522L535):
![image](https://user-images.githubusercontent.com/71729183/213145571-2241eac7-fd22-4bd0-94c9-694c2c3da6b6.png)

**Comment by bpasero** [comment]
We cannot change the way how these context keys are stored, so they will have to remain at `fsPath`. 

Again, without a minimal repro, nothing I can do here.

**Comment by EstherPerelman** [comment]
I'll try my best for minimal reproducing steps:
1. take any sample extension (you can follow [this](https://code.visualstudio.com/api/get-started/your-first-extension) to generate new one)
2. contribute a command and use it with `when` clause, for example: 
 _*note: modify the `when` clause with an absolute path on your machine:_
  ```
  "contributes": {
    "commands": [
      {
        "title": "~~~Test Section~~~",
        "command": "ext.test2"
      }
    ],
    "menus": {
      "explorer/context": [
        {
          "command": "ext.test2",
          "when": "resourcePath == /home/estherp/samples/test/src"
        }
      ]
    }
  },
  ```
3. you should see the contributed menu item in the explorer context menu for the folder you gave in the `when` clause like here: 
![image](https://user-images.githubusercontent.com/71729183/213154607-3c31681d-4e1d-486a-aa56-4ea2b2d71f7c.png)

4. you won't see this on wsl or codespaces unless you modify the path to be with backword slashes for example
   `"when": "resourcePath == \\home\\estherp\\samples\\test\\src"`
5. this is where it will fail comparing: https://github.com/microsoft/vscode/blob/85f62d7aca69bed5315f8354b4bca70031d3ece9/src/vs/platform/contextkey/common/contextkey.ts#L463L467

**Comment by bpasero** [comment]
@EstherPerelman thanks! Will need to bring in some more people to better understand what to do here.

**Comment by bpasero** [comment]
Looks like @eamodio added this in https://github.com/microsoft/vscode/pull/106093. My feeling is that we should not use `fsPath` but use the path format of the remote OS if the resource is remote.

@eamodio can you maybe chime in, I assume this maybe used in GitLens? To clarify the change here could mean that if you are on Windows and connected to a POSIX remote, slashes would be used. Same, POSIX connected to Windows, backslash would be used?

**Comment by aeschli** [comment]
The context key code is on the renderer and when in a remote window, the resource URI will be something like `vscode-remote://wsl+ubuntu//home/...`. 

- Using `fsPath`is never a good idea if the URI is not a `file` URI.
- Also, I question the usefulness of `resourcePath` and `resourceDirname`. These are machine specific paths, e.g. containing the user's home directory. How would an extension use that in a portable way? It would better be workspace relative path, of course always using forward slashes...

**Comment by bpasero** [comment]
@aeschli in https://github.com/microsoft/vscode/pull/106093#issue-692827490 @eamodio mentions the use of `in` operator so an extension can possibly probe a given `URI` on the value and would not need to hardcode it?

I agree that hardcoding a full absolute path makes little sense, so maybe here its just a matter of using the `in` operator properly the way it was intended?

I like the idea of a relative path, but that is outside of the scope of this issue I think.

**Comment by bpasero** [comment]
@EstherPerelman can you clarify how your extension makes use of the fact that the paths are absolute? How will it work? Or is this a theoretical issue?

**Comment by EstherPerelman** [comment]
@bpasero in my extension I'm looking in the opened workspace folder for folders which includes `<specific-file-name>.json` (this way I detect the folder as a supported project to whom I will add a command menu), I'm getting back absolute paths from `const paths = await vscode.workspace.findFiles("<specific-file-name>.json");`  then I execute "setContext" with (absolute paths) parent folders of the resulted paths: ` vscode.commands.executeCommand("setContext", "ext.supportedFoldersProject", projectsFolders);` 
and in the `when` clause of the command (which adding a menu to the explorer context menu as shown [above](https://github.com/microsoft/vscode/issues/171417#issuecomment-1386885323)) I have this: `resourceDirname in ext.supportedFoldersProject`,

if something not clear please write...

**Comment by eamodio** [comment]
@bpasero sorry for the late reply. I am not using it in GitLens, but I might have in RemoteHub (can't remember for sure). I am using `scmProviderRootUri` with `in` in GitLens FWIW. 

IIRC, the intent of of `resourcePath` and `resourceDirname` were to be used with `in` so that you could have a set of folders or paths to check against to provide commands for. See https://github.com/microsoft/vscode/issues/106088. Here is an example usage: https://github.com/microsoft/vscode/issues/107725#issuecomment-700909597. I originally chose `.path` over `.fsPath` to keep things normalized, but @jrieken made a good argument for otherwise https://github.com/microsoft/vscode/pull/106093#issuecomment-692493704

**Comment by EstherPerelman** [comment]
> For this user I would suggest using `in`, then they can control the value(s) they are checking against.

using `in` is the original case that failed for me, you can see in the example I mentioned on top: https://github.com/microsoft/vscode/issues/107725#issuecomment-700909597

**Comment by jrieken** [comment]
> maybe the in operator could treat slash and backslash the same

Very unsure about that... I am missing context but can't we make `resourcePath` be `fsPath` for file-uris and `path` for other uris?

**Comment by bpasero** [comment]
Yeah we can, but it is a somewhat breaking change for anyone that relied on the current behaviour. Anyway, if we are good with it, I think that is the best change to do.

**Comment by bpasero** [comment]
@EstherPerelman as a workaround for now, can you not use the `resource` context key and set the full `Uri.toString()` as context?

**Comment by EstherPerelman** [comment]
> @EstherPerelman as a workaround for now, can you not use the `resource` context key and set the full `Uri.toString()` as context?
> 
> https://github.com/microsoft/vscode/blob/c4ec4b35467b8958327aaf6951f76c43d5e13f64/src/vs/workbench/common/contextkeys.ts#L153

I'll try, thanks for fixing this bug!
