### ISSUE TITLE
[Accessibility] Diff editor cursor position is not preserved after escaping from F7 diff pane

### ISSUE THREAD

**Issue by jooyoungseo** [microsoft/vscode#171426]
CC @meganrogge and @isidorn

## System Info

Version: 1.75.0-insider (system setup)
Commit: 8be8d96ab86ed4077df554eb62727484d454699f
Date: 2023-01-16T05:21:04.032Z
Electron: 19.1.9
Chromium: 102.0.5005.194
Node.js: 16.14.2
V8: 10.2.154.23-electron.0
OS: Windows_NT x64 10.0.22621
Sandboxed: Yes

## Reproducible Steps

1. Load VSCode-insiders with screen reader.

1. Open any PR commit in diff editor.

1. Press Alt+F5 to go to the next change in diff editor: You will hear audio cues.

1. On the changed line, press F7 to open the special diff pane where you can navigate what's been deleted and added denoted with +/- signs.

1. Press ESC to close the special diff pane once you have figured out the differences: The cursor location has changed. The original cursor line is not preserved in the diff editor.

* Notes: The original cursor location is preserved only when you explicitly press enter on the changed line in F7 diff pane.

## Expected Behaviors

* The original cursor position in the diff editor must be preserved after closing the F7 diff pane via ESC.

## Additional Feature Request

I have already found the amazing usefullness of Alt+F5 and F7 interplays. Alt+F5 is very useful for a general overview of changes (+-) whereas F7 gives the detailed information on changes.

It would be even nicer if we could have a smoother interplay between them like below:

1. In diff editor, press Alt+F5 to go to any next changes.

1. Press F7 to open detailed changes in the special diff pane.

1. As soon as the F7 diff pane  is open, the focus is landed on the specific change denoted with +/- signs: Currently the focus moves to the top of the F7 diff pane so that users need to arrow-down several times to find the specific changes.

**Comment by meganrogge** [comment]
This makes sense to me. The F7 special diff pane feels jumpy to me as it currently is.

**Comment by roblourens** [comment]
I'm not sure if it was fixed or not, here's what I see. The same with or without a screenreader enabled

- alt+F5, the cursor is at the top of a changed block
- F7
- Escape, the cursor is now a couple lines above the changed block

**Comment by alexr00** [comment]
This works well _when I use the arrow keys after F7_, but if I just do F7 and then `esc` then I see the same as Rob.

**Comment by meganrogge** [comment]
@hediet has this been fixed in v2?

**Comment by meganrogge** [comment]
This is working for me.
