### ISSUE TITLE
Should Keep Pressing CMD + DELETE still delete lines?

### ISSUE THREAD

**Issue by alfonsoperez** [microsoft/vscode#17143]
- VSCode Version: 1.7.2 (1.7.2)
- OS Version: OSX El capitan 10.11.5 (15F34)

Steps to Reproduce:

1.  Write some lines
2.  Hold CMD, and press DELETE multiple times

**Result expected:**
Should keep deleting lines after the initial line removal

**Result observed:**
The cursor stops at the beginning of the line.

![image](https://cloud.githubusercontent.com/assets/3578008/21162311/9e41a526-c141-11e6-8c5d-3df5e7b8a62f.png)

**Comment by alexandrudima** [comment]
@alfonsoperez Pressing `ctrl+backspace` on Windows works for me:

![16172](https://cloud.githubusercontent.com/assets/5047891/23474607/a31c72b4-feb4-11e6-98cc-7594cbda060d.gif)

@rebornix Can you please check on OSX?

**Comment by alfonsoperez** [comment]
It doesn't do that on OSX for me :(

**Comment by alfonsoperez** [comment]
Any update on this?

**Comment by alexandrudima** [comment]
I have just tried it on a mac mini in the office.

<kbd>cmd</kbd> + <kbd>delete</kbd> is bound to the command `deleteAllLeft` (i.e. it is not word deletion as I originally thought).

The command is currently implemented to only delete to the left, it doesn't handle in any way the case where the cursor sits at column 1.

**Comment by alfonsoperez** [comment]
Oh, I see... I missed that fact from your example, yes, the equivalent in OSX would be to hold the  `option` key, and the behaviour is the same

**Comment by alfonsoperez** [comment]
@alexandrudima I took at stab at at #28392 , what do you think?

**Comment by alexandrudima** [comment]
@alfonsoperez I've assigned the PR for reviewing to @rebornix , he adopted the `deleteAllLeft` command.

**Comment by BrodaNoel** [comment]
Here I added a duplicated ( :( ) for this one: https://github.com/Microsoft/vscode/issues/53021

**Comment by alfonsoperez** [comment]
@BrodaNoel my PR just got merged last week, so I would expect this feature to be rolled out soon

**Comment by lramos15** [comment]
This appears to be implemented now, so I'm going to close the issue.
