### ISSUE TITLE
Replace-across-files dialog says "1 files", not "1 file", for one file

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [Microsoft/vscode#17146]
- VSCode Version: 1.7.2
- OS Version: Windows 10

Steps to Reproduce:

1. Open a workspace 
2. Find-and-replace a string that exists

Screenshot:
![image](https://cloud.githubusercontent.com/assets/3335181/21165606/371b05e0-c155-11e6-970c-529ce8e2fbd8.png)

**Comment by kieferrm** [comment]
Same for "occurrences".

**Comment by roblourens** [comment]
This is one of those surprisingly hard localization problems... is there anywhere in the UI that we do this correctly?

**Comment by sandy081** [comment]
Why not coming with appropriate messages based on the number of occurrences/files?

@JoshuaKGoldberg Feel free to submit a PR for this if you are interested to fix it. 

Ref -> https://github.com/microsoft/vscode/blob/master/src/vs/workbench/parts/search/browser/searchViewlet.ts#L350

**Comment by roblourens** [comment]
Because it's different for different languages - example: https://developer.mozilla.org/en-US/docs/Mozilla/Localization/Localization_and_Plurals#List_of_Plural_Rules

The only language outside of the norm that we support is Russian though.

**Comment by sandy081** [comment]
@roblourens I am sorry, I did not get what you mean. Why not having separate strings for each variation and let the translation team does the rest. For eg:

- Replace `n` occurrences across `x` files with `replace_value`
- Replace `n` occurrences in `file_name` with `replace_value`
- Replace 1 occurrence in `file_name` with `replace_value`

**Comment by roblourens** [comment]
Just pointing out that other languages don't follow the same pluralization rules as English. But it's already wrong in those languages and we may as well make it better for English :)

**Comment by sandy081** [comment]
Yes, messages cannot be constructed programmatically because of translation. Translation team need to translate these different messages. Hence they need to be string literals.

@JoshuaKGoldberg Thanks for the PR
