### ISSUE TITLE
Auto-sorting imports on file save => disappearing TS errors (red underline)

### ISSUE THREAD

**Issue by feegloo** [microsoft/vscode#171467]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.74.3 
- OS Version: macOS Monterey 12.6.2

Steps to Reproduce:

1. enable sorting imports on file save, in `.vscode/settings.json`

```
{
  "[typescript]": {
    "editor.codeActionsOnSave": {
      "source.sortImports": true
    }
  }
}
```

2. Save .ts file with visible TS error, like on attached screencast
3. TS error disappears, instead of red underline on wrong path, it's now barely visible as short underline under original path, starting just from left side
4. when disabling auto-sorting setting from `1.`, it works fine

https://user-images.githubusercontent.com/7686877/212835377-34cd4d0f-6497-440e-a9c2-1c5bbb31c81a.mov

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

If it does, please share a minimal project which demonstrates the issue so we can investigate

**Comment by feegloo** [comment]
Thank you for reply.

I reproduced bug with following setup:
1. Freshly installed VS Code Insiders from your link - no extensions, no custom configuration, just out-of-the-box VSCode
2. I cloned simple TypeScript "starter project" from https://github.com/stemmlerjs/simple-typescript-starter

I'm attaching starter project  + `.vscode/settings.json` configuration, that I mentioned in issue (with `"source.sortImports": true`)

[simple-typescript-starter-master.zip](https://github.com/microsoft/vscode/files/10437613/simple-typescript-starter-master.zip)

When I'm opening starter project with File -> Open Folder, then go to `src/index.ts`, then save file - I'm seeing same error with "disappearing underline" as on screenshot.

![vscode insiders - fresh install, no extensions](https://user-images.githubusercontent.com/7686877/212965393-66afd6e1-b03b-4048-811c-828e0cf5a012.png)

**Comment by mjbvz** [comment]
I haven't been able to reproduce this but suspect it had the same root cause as #169443

If you're still seeing in the latest insiders build, please share a complete set of steps to reproduce the issue including the contents of `src/index.ts`

**Comment by feegloo** [comment]
I don't see this issue anymore in latest VSCode Insiders build `1.77.0`, but it was an error in `1.75.0` (which I attached on previous screenshot) 👍 

![image](https://user-images.githubusercontent.com/7686877/225869473-6b55efee-b707-4761-ab15-7bfa3cfb6d49.png)
