### ISSUE TITLE
Add file preview while searching.

### ISSUE THREAD

**Issue by TeffenEllis** [Microsoft/vscode#17148]
- VSCode Version: 1.7.2
- OS Version: macOS Sierra

Sublime Text shows file previews live when fuzzy searching. It'd be cool to have this feature in VSCode.

1. Press CMD+P to search for files.
2. While using the arrow keys to move through the entries, the current entry should be visible as a preview tab.

Cheers

**Comment by jbw91** [comment]
Is there some sort of API one would be able to tie into to write an extension providing this functionality? Browsing the docs, I haven't been able to find anything that lets an extension extend the workbench. (i.e. open a file in a preview when moving down with arrow keys while fuzzy searching) If there were an api/contribution point for this I'd be willing to write an extension for it.

**Comment by chrmarti** [comment]
Hi @jbw91, no there is currently no API to do that. You'd need to be able to listen on the current selection in the drop down, which at this point seems unlikely to make it into an API.

**Comment by jbw91** [comment]
I'd contribute a pull request for this myself if I had any idea of where to start. This is a complex project. :)

**Comment by bpasero** [comment]
Please move your votes to: https://github.com/Microsoft/vscode/issues/8939
