### ISSUE TITLE
Word wrap toggle is switched off whenever zoom level is changed

### ISSUE THREAD

**Issue by bad32** [Microsoft/vscode#17155]
- VSCode Version: 1.7.2  (7ba55c5)
- OS Version: Windows 7 x64 / Windows 10 x64
- Extensions: disabled all of them

Steps to Reproduce:
1.  Write text longer than the width of the document
2. Toggle on word-wrap
3. Zoom in / zoom out (using `ctrl` + `=` / `ctrl` + `-` )

**Comment by kieferrm** [comment]
This only happens when you use `Toggle Word Warp` through the menu or command palette. When you explicitly change the `editor.wordWarp` setting in your `settings.json` file word-warp continues to work as expected.

**Comment by ivanoats** [comment]
Word Wrap also gets turned off when "Toggle Render Whitespace" or "Toggle Control Characters" gets toggled.

**Comment by alexandrudima** [comment]
67924dec07b503fafbe6e7128333ae15202e3ef9 fixes this thanks to @bpasero
