### ISSUE TITLE
Show profile contents string has literal

### ISSUE THREAD

**Issue by rzhao271** [microsoft/vscode#171538]
On the latest Insiders, clicking on the profile button reveals the option "Show Profile Contents", which has an unformatted `{0}` in it.

![Profile context menu options, showing the unformatted "Show Profile Contents" entry](https://user-images.githubusercontent.com/7199958/212988303-7cd266f2-9e05-4911-b7be-bdfa03bc6a60.png)

**Comment by TylerLeonhardt** [comment]
@sandy081 this will eventually resolve itself but the recommendation is, if you are removing or adding `{0}` to a string that you should also change the key to ensure that this issue doesn't happen and a new string is displayed properly.
