### ISSUE TITLE
Allow extension to open URI for GitHub Authentication

### ISSUE THREAD

**Issue by digitarald** [microsoft/vscode#171566]
Fresh install of Insiders on Windows 11, I get this when signing in to GitHub for an extension:

<img width="763" alt="image (2)" src="https://user-images.githubusercontent.com/8599/213059151-0cfddc2f-f7a1-4bcf-81e6-359773502451.png">

I'd expect that this should be a trusted operation and not require any additional prompt.

**Comment by TylerLeonhardt** [comment]
@joaomoreno I think this is you since it's about URI handlers? Let me know if this is something for me to do.

@lramos15 this isn't you, right?

**Comment by joaomoreno** [comment]
https://github.com/microsoft/vscode/issues/169458
