### ISSUE TITLE
Tunnel invocations should connect to running tunnels

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode#171520]
There should only be one tunnel server running at a time. So when `code tunnel` is called a second time it should discover the running server and exit again with a success message.

-> Needs a new command to `code tunnel stop` to stop already running services.

**Comment by connor4312** [comment]
This is implemented now

**Comment by connor4312** [comment]
Verification:

- Grab the latest standalone CLI https://code.visualstudio.com/insiders/
- Open at least two terminals, and don't have remote tunnel access turned on in VS Code (or have VS Code closed)
- Run `./code-insiders tunnel --verbose` in terminal.
- Verify `starting as new singleton` is printed in the terminal and the tunnel starts
- Run `./code-insiders tunnel --verbose` in another terminal
- Verify it prints "Connected to an existing tunnel process running on this machine." with control instructions after replaying recent logs from the singleton
- Verify the control commands printed work as expected
- Have the two tunnels running again. Ctrl+C in the singleton terminal. Verify the previous "client" terminal notices that and starts up the tunnel
- Verify the commands `code tunnel status`, `code tunnel restart`, and `code tunnel kill` work. These are alternatives to the "interactive" commands clients normally print. `status` should exit with an error if no tunnel is running.
