### ISSUE TITLE
Source files in MD format are marked KT or Kotlin but not highlighted

### ISSUE THREAD

**Issue by acc8226** [microsoft/vscode#171573]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:  1.74.3
- OS Version: Windows 11 Home 21H2

Steps to Reproduce:

1.  Source files in MD format are marked KT or Kotlin but not highlighted.

expected to be highlighted on the source editing page (currently only supported on the preview page) 

![](https://user-images.githubusercontent.com/10010627/213087030-d755e62f-f290-426a-b2ff-26243de68350.png)

**Comment by mjbvz** [comment]
VS Code does not include Kotlin syntax highlighting for editors out of the box. This can be contributed by the Kotlin extension
