### ISSUE TITLE
Centos Bug

### ISSUE THREAD

**Issue by 18392152392** [microsoft/vscode#171578]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:  1.74.3
- OS Version: 

Steps to Reproduce:

1. I download VSCode in centos
2. I open folder in VSCode, it has no response
3. I open file in VSCode, it has no response
4. I add folder to workspace, It also has no rsponse
5. the bug is as following pictures:
![openFolder](https://user-images.githubusercontent.com/52459655/213095845-317a7cbd-47d6-493e-8f7c-c1e1b7128b73.jpg)

Such a serious bug, can you help to fix? 
Much Thanks!!!

**Comment by JaneySprings** [comment]
I also encountered this on ubuntu, just the dialog is shown outside the VisualStudio window. You can see it on taskbar
<img width="387" alt="image" src="https://user-images.githubusercontent.com/48021947/213100302-bc002e46-b4ad-4d18-954e-f0cae0d280e0.png">

**Comment by 18392152392** [comment]
> Oh my god, this experience is so bad, I totally can not see it, Could this bug be fixed ? we have so many people use it on centos

**Comment by joaomoreno** [comment]
https://github.com/microsoft/vscode/issues/171568
