### ISSUE TITLE
Let notebook renderers fallback to other renderers on failure

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#171562]
Outgrowth from #163973 and follow up from https://github.com/microsoft/vscode-jupyter/issues/8635

Tracks a new API that will let one notebook renderer give up on rendering while telling VS Code to try the next available renderer. This is needed for https://github.com/microsoft/vscode-jupyter/issues/8635

**Comment by DonJayamanne** [comment]
@mjbvz isn't this complete?

**Comment by mjbvz** [comment]
I believe this has been implemented in [#171567](https://github.com/microsoft/vscode/pull/171567)
