### ISSUE TITLE
Searching For Regex Freezes VS Code

### ISSUE THREAD

**Issue by hediet** [microsoft/vscode#171514]
![image](https://user-images.githubusercontent.com/2931520/212937466-123be209-72c0-461d-8968-96ddd214d52a.png)

Reg exp: `:after(.*\n.*)*content:`

When searching for this regexp in 
[bad.txt](https://github.com/microsoft/vscode/files/10436473/bad.txt), VS Code freezes immediately.

**Comment by rebornix** [comment]
oLet's track it in https://github.com/microsoft/vscode/issues/30874. @hediet now we are making more things to be async (off main thread), I wonder if it's a good time to run Find/Search in workers.

**Comment by hediet** [comment]
Async search sounds good! As long as the worker can be killed after some timeout.
