### ISSUE TITLE
Problems with Automatic Updates on Windows

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#17159]
**VSCode Version: 1.8.-insider**

- VS Code insider from yesterday. Run check for Updates and VS Code exits / crashes after ~1 Minute. 
- Updated VS Code by downloading the latest installer and run it
- Executed Update again
- VS Code doesn't exit, however the Menu stays on 'Checking for updates' forever.

![capture](https://cloud.githubusercontent.com/assets/1931590/21176644/f5291990-c1e7-11e6-8a40-1d155996076d.png)

**Comment by joaomoreno** [comment]
Seems to have been a sporadic event.
