### ISSUE TITLE
Constant "White Screen of Death"

### ISSUE THREAD

**Issue by em1382** [microsoft/vscode#171543]
Type: <b>Bug</b>

The application is constantly crashing (white screen of death, waiting for the program to respond is hopeless), seemingly randomly. The most common triggers seem to be tabbing out and back into the application. I also experienced the crash when clicking Help > About to obtain the version number, which made me smile :-)

VS Code version: Code 1.74.3 (97dec172d3256f8ca4bfb2143f3f76b503ca0534, 2023-01-09T16:59:02.252Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 PRO 5850U with Radeon Graphics      (16 x 1896)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|14.83GB (5.65GB free)|
|Process Argv|--crash-reporter-id 6e371af7-ce12-4ba2-b800-7231a140a32a|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (25)</summary>

Extension|Author (truncated)|Version
---|---|---
cform|aws|0.0.24
vscode-markdownlint|Dav|0.49.0
vscode-eslint|dba|2.2.6
gitlens|eam|13.2.0
EditorConfig|Edi|0.16.4
go|gol|0.37.0
rainbow-csv|mec|3.5.0
dotenv|mik|1.0.1
vscode-docker|ms-|1.23.3
vscode-postgresql|ms-|0.3.0
isort|ms-|2022.8.0
pylint|ms-|2022.6.0
python|ms-|2022.20.2
vscode-pylance|ms-|2023.1.20
jupyter|ms-|2022.11.1003412109
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.13
vscode-jupyter-cell-tags|ms-|0.1.6
vscode-jupyter-slideshow|ms-|0.1.5
remote-containers|ms-|0.266.1
powershell|ms-|2022.12.1
vscode-yaml|red|1.11.0
intellicode-api-usage-examples|Vis|0.2.6
vscodeintellicode|Vis|1.2.30
vscode-icons|vsc|12.0.1

(3 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
azure-dev_surveyone:30548225
pyindex848cf:30577861
nodejswelcome1cf:30587006
282f8724:30602487
89544117:30613380
fim-prod:30623723
a9j8j154:30646983

```

</details>

**Comment by gjsjohnmurray** [comment]
Does it also happen if you launch with all extensions disabled, or run the command to reload with all extensions disabled (assuming you have enough time to run that command after a normal startup before VS Code crashes)?

**Comment by em1382** [comment]
I left it open a bit to see if I could reproduce with `--no-extensions`, and it looks like that an extension might be the culprit. I'll re-open this if I experience in this state.

**Comment by gjsjohnmurray** [comment]
The Start Extension Bisect command may prove useful to you.
