### ISSUE TITLE
Add support for Sixels in integrated terminal

### ISSUE THREAD

**Issue by marvinruder** [microsoft/vscode#171666]
I would like the integrated terminal of VS Code to support [Sixels](https://en.wikipedia.org/wiki/Sixel) for displaying graphics. 

Since the integrated terminal is based on [xterm.js](https://github.com/xtermjs/xterm.js), for which a very simple add-on [xterm-addon-image](https://github.com/jerch/xterm-addon-image) exists, this feature can be integrated without much effort. 

(The topic of images in the integrated terminal appears to have been discussed briefly in #65283, but the requested feature there seems to have been related to a different and proprietary image format of iTerm 2. Sixels on the other hand are much more common, having been in existence since the era of [hardware terminals](https://en.wikipedia.org/wiki/VT220) and being supported by terminal emulators such as xterm.)

**Comment by Tyriar** [comment]
Closing in favor of https://github.com/xtermjs/xterm.js/issues/614, see https://github.com/microsoft/vscode/pull/171667#pullrequestreview-1261715602
