### ISSUE TITLE
When clicking on a terminal tab, it should focus the text on the contents of the terminal.

### ISSUE THREAD

**Issue by whiterook6** [microsoft/vscode#171645]
When clicking on a terminal tab, I'd like to be able to type or copy-paste right away. Instead, when clicking on the tab, I then have to click in the text space to bring focus to the contents of the terminal.

<img width="1178" alt="Screen Shot 2023-01-18 at 9 20 46 AM" src="https://user-images.githubusercontent.com/5151965/213253868-3192cd50-2bd9-40de-b184-d63171de0b74.png">

To reproduce:

1. Open multiple terminal tabs.
2. Click on a tab.
3. Start typing.

You'll see the typing won't work because focus is still on the tab itself, not in the text area.

**Comment by meganrogge** [comment]
`terminal.integrated.tabs.focusMode: singleClick` is what you're looking for
