### ISSUE TITLE
How to config terminal.external work with Hyper.is app

### ISSUE THREAD

**Issue by bang88** [Microsoft/vscode#17160]
The settings is below,  vscode can open the Hyper app, but lose the current location. It always use the home location. 
```js
// Place your settings in this file to overwrite the default settings
{
	"terminal.external.windowsExec": "C:\\Users\\bang\\AppData\\Local\\hyper\\app-1.0.0\\Hyper.exe",
	"npm.runInTerminal": false
}
```

**Comment by Tyriar** [comment]
I filed the following upstream issues to follow up with this on their side: #1212, #1213. It should just work out of the box like other terminals.
