### ISSUE TITLE
🚀❤️Add butten to meno bar or settings for delete temp and cache file❤️🚀

### ISSUE THREAD

**Issue by Mohammadev82** [microsoft/vscode#171618]

**Comment by rzhao271** [comment]
Hi, what files are you referring to when you say "temp" and "cache"?

**Comment by Mohammadev82** [comment]
Available files on Localapp folder in Windows and usr/tmp or other where in Linux because node js and JavaScript generate many temp like logs or  some extensions like sonarlint

**Comment by rzhao271** [comment]
For extensions, please file an issue specific to that extension.
For `AppData\Roaming\Code`, I'm wondering why you want to clear out that folder? Does the [Settings profile feature](https://code.visualstudio.com/updates/v1_74#_profiles) work for your use case?

**Comment by Mohammadev82** [comment]
Sometimes I have problems with the program settings because the settings of the deleted extensions remain in the program or there are two items from one extension in the folders. I solved this problem by deleting some temporary folders or previous version of  extensions.  For the normal user, these tasks are very time-consuming

**Comment by sandy081** [comment]
> Sometimes I have problems with the program settings because the settings of the deleted extensions remain in the program

This is know and unfortunately there are no plans to support this.

> there are two items from one extension in the folders. I solved this problem by deleting some temporary folders or previous version of extensions. 

Older versions gets deleted automatically when you restart VS Code. You do not need to clean up manually.
