### ISSUE TITLE
Muli-line strings in JavaScript not colored, code following multi-line string not colored

### ISSUE THREAD

**Issue by KevinSCreative** [Microsoft/vscode#1716]
After the first line, multi-line strings in JavaScript don't get string color. In the following example, only "Hello World" has the string color, and the obj variable declaration is all one color. In the default theme, 'var' is supposed to be blue. I would also expect the rest of the string to be orange in the default theme, not just the first line. 

I am running VSC 0.10.6 and I have no extensions installed.

var test = 'Hello World!\
        &lt;div&gt;\
            &lt;p&gt;Testing&lt;/p&gt;\
        &lt;/div&gt;\
    ';
var obj = $(test);

**Comment by aeschli** [comment]
This issue was moved to Microsoft/TypeScript-TmLanguage#40
