### ISSUE TITLE
Font color is faded/dimmed

### ISSUE THREAD

**Issue by Be3y4uu-K0T** [microsoft/vscode#171632]
Type: <b>Bug</b>

Earlier, due to the same bug (see photo), I rolled back (1.63) the version and stopped updating. But recently I needed to do it, I installed the latest version. And I still have the text faded/dimmed. I checked on VS Code latest Insiders, and the bug is still present with me. I tried to solve the problem myself using methods from [stackoverflow](https://stackoverflow.com/questions/72916668/why-are-there-grey-blocks-of-color-on-the-vs-code-editor-window). But none of the methods helped me. Also, for some reason, when hovering over the field `disable-color-correct-rendering`, an error appears `Property disable-color-correct-rendering is not allowed.`

(left - 1.74.3; right - 1.63.2) 
<img width="1440" alt="Снимок экрана 2023-01-18 в 20 00 19" src="https://user-images.githubusercontent.com/60096074/213213138-2e7418ac-e810-4600-bd33-da7c0bb771ff.png">

VS Code version: Code 1.74.3 (97dec172d3256f8ca4bfb2143f3f76b503ca0534, 2023-01-09T17:05:47.808Z)
OS version: Darwin arm64 22.2.0
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|2, 3, 3|
|Memory (System)|8.00GB (0.29GB free)|
|Process Argv|--crash-reporter-id 9683945e-7fe3-4f0e-a4bf-3e4ebe7ad2af|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (35)</summary>

Extension|Author (truncated)|Version
---|---|---
language-mcfunction|arc|0.18.0
emojisense|bie|0.9.1
glsl-canvas|cir|0.2.15
arm|dan|1.7.4
vscode-test-explorer|hbe|2.21.1
vscode-env|Iro|0.1.0
swift|Kas|0.2.0
vsc-python-indent|Kev|1.18.0
graphql-for-vscode|kum|1.15.3
vscode-python-test-adapter|lit|0.7.1
Kotlin|mat|1.7.1
git-graph|mhu|1.30.0
vscode-language-pack-ru|MS-|1.74.12140931
csharp|ms-|1.25.2
isort|ms-|2022.8.0
python|ms-|2022.20.2
vscode-pylance|ms-|2023.1.20
jupyter|ms-|2022.11.1003412109
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.13
vscode-jupyter-cell-tags|ms-|0.1.6
vscode-jupyter-slideshow|ms-|0.1.5
cmake-tools|ms-|1.12.27
cpptools|ms-|1.14.0
live-server|ms-|0.4.4
test-adapter-converter|ms-|0.1.6
LiveServer|rit|5.7.9
shader|sle|1.1.5
swift-lang|ssw|0.10.0
lua|sum|3.6.6
even-better-toml|tam|0.19.0
cmake|twx|0.0.17
luna-paint|Tyr|0.16.0
vscode-lldb|vad|1.8.1
clang-format|xav|1.9.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscoreces:30445986
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
azure-dev_surveyone:30548225
vscccc:30610679
pyindex848:30577860
nodejswelcome1:30587005
3biah626:30602489
f6dab269:30613381
fim-prod:30623723

```

</details>

**Comment by deepak1556** [comment]
@Be3y4uu-K0T are you using a P3 display ? What color profile are using for the display ?

**Comment by Be3y4uu-K0T** [comment]
I'm using Colour LCD.

**Comment by Be3y4uu-K0T** [comment]
I'm sorry..

**Comment by deepak1556** [comment]
Can you share the display settings from OS and also the font settings from VSCode.

**Comment by Be3y4uu-K0T** [comment]
Font settings: `"editor.fontFamily": "'Fira Code', Menlo", "editor.fontLigatures": "'ss04', 'ss06', 'ss07', 'ss09', 'cv25', 'cv26', 'cv32', 'cv28'"`
Graphics/Displays:
```
Apple M1:

  Chipset Model:	Apple M1
  Type:	GPU
  Bus:	Built-In
  Total Number of Cores:	7
  Vendor:	Apple (0x106b)
  Metal Support:	Metal 3
  Displays:
Colour LCD:
  Display Type:	Built-In Retina LCD
  Resolution:	2560x1600 Retina
  Main Display:	Yes
  Mirror:	Off
  Online:	Yes
  Automatically Adjust Brightness:	No
  Connection Type:	Internal
  ```

**Comment by rzhao271** [comment]
@Be3y4uu-K0T does the issue occur with all themes? If so, is the issue still there on the latest version of VS Code? Also, does the issue occur with extensions disabled?

**Comment by Be3y4uu-K0T** [comment]
@rzhao271 I'm very unsure, but it seems this change only affected Solarized Light. I ran into a problem when I completely reinstalled VS Code. I guess the colors were just changed in one update.

**Comment by rzhao271** [comment]
Yeah, it looks like the default text colour in an untitled file got changed to dark grey.

**Comment by rzhao271** [comment]
I have confirmed that the foreground colour changed
![Newer Solarized Light text foreground colour for the keyword function is grey, whereas the older colour was closer to block](https://github.com/microsoft/vscode/assets/7199958/8225f3e8-7079-4f54-b516-968ad7abc945)

**Comment by rzhao271** [comment]
Seems to be by design&mdash;see https://github.com/microsoft/vscode/pull/142670.
