### ISSUE TITLE
Markdown Preview scroll sync is broken for files with images

### ISSUE THREAD

**Issue by TomeASilva** [microsoft/vscode#171653]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:  1.74.3
- OS Version: 10.0.22621

Steps to Reproduce:

1. Create a markdown file
2. Add text to file
3. Add images

When I had images to markdown the synchronization between the preview and file editor gets broken. In a file with images, in the editor, if I scroll to the end of the page, the preview does not get scrolled to the end page. It is as if the images are counted as just one line, but in reality in the preview 1 image == x amount of lines.  So to have perfect synchronization in a file with images you would have to scroll more in the preview than you would have to scroll in the editor. 

 
![Screenshot 2023-01-18 180720](https://user-images.githubusercontent.com/35806717/213260329-96aa75f4-8b44-40f0-8d9d-d0ae5f9a5efd.png)

You can see from this picture that the editor is at the end of the page and the markdown preview it is not.

**Comment by mjbvz** [comment]
Please share the source text of a file that demonstrates this issue

**Comment by TomeASilva** [comment]
![Screenshot 2023-01-20 095846](https://user-images.githubusercontent.com/35806717/213667891-fd5d2720-cefc-4103-ae59-91ae4c6bac15.png)


[test.md](https://github.com/microsoft/vscode/files/10465221/test.md)

**Comment by mjbvz** [comment]
Scrolling is synchronized to the top of the editor and the preview. In your screenshot, the editor top is one line 1 and the preview top looks to be on line 1 too.

If I've misunderstood, please share more info about the problem (such as a gif showing it in action)

**Comment by TomeASilva** [comment]
So if I'm in the line that says FOO the intended behavior is that I cannot see the word FOO in the preview? My understanding is that if I'm in a particular line I should see the content of that line in the preview...

**Comment by mjbvz** [comment]
The visible top of the editor and preview are synchronized, not the cursor position. In practice we've found this is the most natural feeling approach for scroll sync
