### ISSUE TITLE
Orphaned quote crashes Sass

### ISSUE THREAD

**Issue by spritestack** [Microsoft/vscode#17166]
- VSCode Version: Code 1.7.2 (7ba55c5860b152d999dda59393ca3ebeb1b5c85f, 2016-11-21T22:01:10.756Z)
- OS Version: Darwin x64 15.6.0
- Extensions:

|Extension|Author|Version|
|---|---|---|

---

Steps to Reproduce:

1. Open a new document
2. Set language mode to Sass
3. Type a quote mark " or '  and delete the closing quote if it's auto added.
Any line of text with an orphaned quote mark will do.
4. Move cursor to column 1 (start of the line) and press TAB.

Desired behaviour:
Pressing TAB should indent the text regardless of valid code etc.

The problem:
VSCode seems to freeze.

**Comment by kieferrm** [comment]
The problem is caused by emmet.

**Comment by ramya-rao-a** [comment]
https://github.com/emmetio/emmet/issues/396

**Comment by ramya-rao-a** [comment]
Happens if you press TAB anywhere inside the block

**Comment by ramya-rao-a** [comment]
Closing as duplicate of #8135
