### ISSUE TITLE
settings.json - ${config:...} not expanding properly

### ISSUE THREAD

**Issue by scorpion35** [microsoft/vscode#171675]
Does this issue occur when all extensions are disabled?: n/a

- VS Code Version: 
```
  Version: 1.74.3 (user setup)
  Commit: 97dec172d3256f8ca4bfb2143f3f76b503ca0534
  Date: 2023-01-09T16:59:02.252Z
  Electron: 19.1.8
  Chromium: 102.0.5005.167
  Node.js: 16.14.2
  V8: 10.2.154.15-electron.0
  OS: Windows_NT x64 10.0.19045
  Sandboxed: No
```
- OS Version: 
```
  Edition	Windows 10 Enterprise
  Version	22H2
  Installed on	‎07-‎Jan-‎22
  OS build	19045.2486
  Experience	Windows Feature Experience Pack 120.2212.4190.0
```

Trying to reuse a value declared in one place in `settings.json` . Here is a part of my `settngs.json` file 

```json
"terminal.integrated.env.windows": {
  "python-project": "${workspaceFolder}\\src\\python-project",
},
"terminal.integrated.cwd": "${config:terminal.integrated.env.windows.python-project}",
"python.defaultInterpreterPath": "${config:terminal.integrated.env.windows.python-project}\\.venv\\Scripts\\python.exe",
```

Now when I open a new terminal, it opens in the correct `cwd` I've set in the `settings.json` file
![image](https://user-images.githubusercontent.com/18679225/213299220-93fecfe7-7de8-4bc4-817b-6fbc8c066447.png)

This means it's reading the correct value from `terminal.integrated.env.windows.python-project`

But now when I try to select the python interpreter path, it doesn't expanded properly
<img width="561" alt="image" src="https://user-images.githubusercontent.com/18679225/213299936-ff0b0c8f-8c59-47b3-81a8-46fde4acdfa6.png">

It was working good until yesterday, was using these settings for a week or so. Restarted my machine just now, vscode didn't seem to get any updates as I recall, and the interpreter path is not expanded anymore. 

I am seeing this now 
![image](https://user-images.githubusercontent.com/18679225/213305541-1e254181-91e9-4ca7-a12c-7b70338f2f2c.png)

**Comment by sandy081** [comment]
Using settings are variables inside settings values is not supported.

**Comment by scorpion35** [comment]
> Using settings are variables inside settings values is not supported.

Hey @sandy081 , curious if you closed the issue after **FULLY** understanding it or just closed it to bring the numbers down?

Here is what I am thinking - 

- vscode is a **code** editor
- it's one of the best practices to be as `DRY` as possible
- The issue I opened will potentially help a lot of programmers (maybe including you as well?) to just define a hardcoded string in one place, and **reuse** it elsewhere. Isn't that programming is all about?

I am concerned you might've closed the issue without even understanding it. BTW, I've demonstrated above the reusing variables is **working** within `settings.json` (perhaps due to a bug maybe, if it's not "planned" feature), but it's just that it's a bit wonky - works in some places, and doesn't work in other places.

**Comment by sandy081** [comment]
@scorpion35 Yes, I understood the issue, actually it is very similar to the following issue https://github.com/microsoft/vscode/issues/2809

There is no general support for variables. At present, it is up to each feature or extension to support this feature like mentioned in above issue.

Your example is also similar. Its fortunate that one of the features like terminal is supporting it but other features like python is not supporting it. There are two options

1. Support variables in settings in general which is what above mentioned issue is for
2. You can file an issue against python extension to support similar variables in their settings.
