### ISSUE TITLE
What about to add a fallback file encoding?

### ISSUE THREAD

**Issue by was4444** [Microsoft/vscode#17165]
Hi,
What about to add a fallback file encoding?

**Comment by was4444** [comment]
- VSCode Version: 1.7.2

Seems duplicated with https://github.com/Microsoft/vscode/issues/4958, but still cannot auto select ``gbk`` encoding when ``file.encoding`` is ``utf8``

**Comment by kieferrm** [comment]
You can set `files.encoding` in your `settings.json`.  That is your "fallback".

**Comment by was4444** [comment]
@kieferrm, then my ``utf8`` files will not be rendered properly. :‑(
