### ISSUE TITLE
Allow to move the "Opened Editors" view below the file explorer

### ISSUE THREAD

**Issue by leaxoy** [Microsoft/vscode#17169]
- VSCode Version: Code 1.7.2 **[Unsupported]** (7ba55c5860b152d999dda59393ca3ebeb1b5c85f, 2016-11-21T22:01:10.756Z)
- OS Version: Darwin x64 16.3.0

Now we can hide `opened file folder in siderbar`
It's would be more efficient to have an option to move `opened file folder in sidebar` below `opened dir` since the `opened dir` would not float up-and-down when open new file or close file.

**Comment by Stanzilla** [comment]
additionally, you should be able to disable "opened editors" since it serves the same functionality as tabs. so maybe it should auto disable when tabs are enabled and vice versa?

**Comment by leaxoy** [comment]
In fact， there is a setting `explorer.openEditors.visible` to archive that. @Stanzilla

**Comment by Stanzilla** [comment]
Oh neat, thank you.

**Comment by bpasero** [comment]
Works now.
