### ISSUE TITLE
Potential listview CSS regression

### ISSUE THREAD

**Issue by rzhao271** [microsoft/vscode#171754]
I opened the Settings editor, hovered over a setting, and noticed a new grey line appear to the left of the settings.

This issue occurs with the default light and dark themes.

![New line on the left of the settings](https://user-images.githubusercontent.com/7199958/213546555-8b2c290f-ca82-4d49-9f94-7319904e1bd3.png)

**Comment by rebornix** [comment]
I found that when calling `updateOptions`, if we don't pass in the style override anymore, it will be reset to default 

https://github.com/microsoft/vscode/blob/3fd65671022d863431871a4304a714fc20ca7bab/src/vs/workbench/contrib/preferences/browser/settingsTree.ts#L2303-L2304

I put this fix for notebook https://github.com/microsoft/vscode/commit/6d6d9bd2d05b68e902f54dcfbd8fd896ef97004c but I wonder if it's unexpected @aeschli

**Comment by aeschli** [comment]
Thanks @rebornix for figuring that out. We shouldn't update options that are not set, that a regression. 
I fixed that with https://github.com/microsoft/vscode/pull/171797 and updated your code to back what it was.

@rzhao271 Is different, it's about the indent guides which were disabled by not providing any colors.
https://github.com/microsoft/vscode/pull/171809 is a simple fix.
But I think we should not use the colors for that but the already existing option.
I'm working on a follow up PR, but that needs to be reviewed by @joaomoreno who is out today.
