### ISSUE TITLE
Terminal setting has invalid default

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#171787]
<img width="285" alt="image" src="https://user-images.githubusercontent.com/323878/213610173-17288aa4-c296-4d96-8695-f15b54b77c15.png">

**Comment by meganrogge** [comment]
strange 🤔 

<img width="1060" alt="Screenshot 2023-01-20 at 3 28 32 PM" src="https://user-images.githubusercontent.com/29464607/213808521-9a646caa-6467-4e07-98cc-79d13ab73217.png">

**Comment by meganrogge** [comment]
value is `''` here, not sure why

<img width="1246" alt="Screenshot 2023-01-20 at 3 34 09 PM" src="https://user-images.githubusercontent.com/29464607/213809289-4bebf717-9fa6-4120-9453-c8ba7e472c29.png">

**Comment by meganrogge** [comment]
Oh, changed the default value to 10 and it worked. I think 1000 is viewed as too high somewhere so it gets set to ''

**Comment by meganrogge** [comment]
also tried `type: integer` because some other settings w high default values use that and it still didn't work

**Comment by rzhao271** [comment]
I added some logging and it's because `.toLocaleString('en')` converts it to `1,000`, and then the inputbox doesn't know how to handle the comma 🤦
