### ISSUE TITLE
go to definition not working

### ISSUE THREAD

**Issue by ozergul** [microsoft/vscode#171760]
Type: <b>Bug</b>

after signing with github & syncing settings, go to definition not working.
.tsx files are like .txt file. 
nothing is clickable

VS Code version: Code 1.74.3 (97dec172d3256f8ca4bfb2143f3f76b503ca0534, 2023-01-09T17:05:47.808Z)
OS version: Darwin arm64 21.3.0
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|4, 4, 3|
|Memory (System)|32.00GB (0.24GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|2.2.6
prettier-vscode|esb|9.10.4
vscode-jetbrains-keybindings|isu|0.1.9
intellij-idea-keybindings|k--|1.5.5
terminal-setups|lin|0.1.0
vscode-typescript-next|ms-|5.0.202301180
intellicode-api-usage-examples|Vis|0.2.6
vscodeintellicode|Vis|1.2.30
vscode-icons|vsc|12.0.1

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
azure-dev_surveyone:30548225
vsccc:30610678
pyindex848cf:30577861
nodejswelcome1:30587005
3biah626:30602489
89544117:30613380

```

</details>

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

If it does, please share a code example where it doesn't work

**Comment by ozergul** [comment]
@mjbvz yes, with latest inside build and with all extensions disabled
Go to definition doesn' work even for this

```
const test () => alert('test')

test()
```

Btw this is not related typescript, js, php etc. issue. 

![image](https://user-images.githubusercontent.com/8460954/213629576-937051c4-f4f0-4424-8bd7-a8e74a71c8ed.png)

**Comment by ozergul** [comment]
When I press CMD, while I am clicking a variable, method etc, curspor is not pointer, this is interesting.

**Comment by ozergul** [comment]
I deleted vscode completely with these commands:

```
rm -fr ~/Library/Preferences/com.microsoft.VSCode.helper.plist 
rm -fr ~/Library/Preferences/com.microsoft.VSCode.plist 
rm -fr ~/Library/Caches/com.microsoft.VSCode
rm -fr ~/Library/Caches/com.microsoft.VSCode.ShipIt/
rm -fr ~/Library/Application\ Support/Code/
rm -fr ~/Library/Saved\ Application\ State/com.microsoft.VSCode.savedState/
rm -fr ~/.vscode/
```

Opened frist time. Go to definition works.
Sycned
Reloaded
Go to definition doesn't works...

**Comment by mjbvz** [comment]
That code sample is not valid (there's a missing `=`)

Does it work with valid code?

**Comment by ozergul** [comment]
It is my bad, my example is not valid sorry. 
After sync, go to definition at Vs code doesn't work unfortunately...

I started to use Insider. Everything is okay for 2 days, even with sync :)
I think this problem is related with my github account that I logged in to vscode to sync.
