### ISSUE TITLE
Format Multi-Line Assignment Alignment

### ISSUE THREAD

**Issue by TheColorRed** [Microsoft/vscode#1717]
Add multi-line assignment alignment

So for example, this:

```
public class Test{

    float myFloat = 123f;
    int myInt = 123;
    GameObject obj = new GameObject();

    float another = 234f;
    GameObject obj2 = new GameObject();
}
```

Becomes this (gaps in lines creates a new alignment block):

```
public class Test{

    float myFloat  = 123f;
    int myInt      = 123;
    GameObject obj = new GameObject();

    float another            = 234f;
    GameObject anotherObject = new GameObject();
}
```

**Comment by ctlajoie** [comment]
There is an extension for this: https://marketplace.visualstudio.com/items/steve8708.Align

**Comment by TheColorRed** [comment]
Does this only work with JavaScript? It isn't working in my C# file.

**Comment by TheColorRed** [comment]
It would be nice if I didn't have to select the items I want to align and it just knew which ones to align.

**Comment by mjbvz** [comment]
This a feature that can be provided either by an extension, or should be implemented as a format setting for a given language. Closing since both are extension issues

**Comment by talamaska** [comment]
Well, I tried some extensions, they work, but when I save VS code reformat everything and removes the additional space between assignments, so I would need to tell VS code to not remove this white space on format action.
