### ISSUE TITLE
Allow ctrl-click opening filepaths containing square brackets (Next.js dynamic routes)

### ISSUE THREAD

**Issue by iacobfred** [microsoft/vscode#171790]
Next.js supports dynamic routes using page files like `pages/products/[id].tsx` or `pages/products/[id]/add.tsx`.

When run on these page files, ESLint output might look like the following:
```
/Users/jacob/code/saleor-platform/apps/kwstriping/pages/[channel]/[locale]/pages/gallery.tsx
  39:19  error  Media elements such as <audio> and <video> must have a <track> for captions  jsx-a11y/media-has-caption

/Users/jacob/code/saleor-platform/apps/kwstriping/pages/api/payment-status/[orderId].ts
  15:9  warning  Variable name `StatusEnum` must match one of the following formats: camelCase, UPPER_CASE  @typescript-eslint/naming-convention
```

Normally, you can ctrl-click the filepaths in eslint output to quickly open them in the IDE, but this does not work for paths containing square brackets. 

It would be great if when there are linting errors in pages with filepaths containing square brackets, I could open these files quickly with ctrl-click just like any other file.

**Comment by mjbvz** [comment]
@Tyriar Assigning you to start since I think this is about links in terminal output

**Comment by Tyriar** [comment]
This is actually done for the upcoming version 🎉, see https://github.com/microsoft/vscode/pull/169774
