### ISSUE TITLE
In the debug console, completion doesn't apply when pressing enter

### ISSUE THREAD

**Issue by fbricon** [microsoft/vscode#171700]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.74.3
- OS Version: macOS Ventura 13.0.1

Steps to Reproduce:

1. Create a simple .js file containing
```js
const greeting = "Hello World!";
console.log(greeting);
```
2. put a breakpoint on line 2
3. Debug as a Node application
4. When the breakpoint it, in the Debug console, start typing `gr`, select `greeting` and press enter
5. Completion item was not applied, instead the current `gr` statement is executed, causing an error:
> Uncaught ReferenceError ReferenceError: gr is not defined
    at eval (repl:1:1)

I understand it works as expected when hitting TAB instead, however, this is inconsistent with the editor, where I'm use to selecting the completion item with Enter. It makes the experience pretty frustrating.

**Comment by roblourens** [comment]
<img width="466" alt="image" src="https://user-images.githubusercontent.com/323878/213746692-08490e46-6e42-4c1b-9c2b-1999a6699bd8.png">

**Comment by fbricon** [comment]
Thanks, why isn't it the default?

**Comment by roblourens** [comment]
This often catches me too, but at the same time, it's annoying to type exactly what you mean, then press enter to submit, and accidentally accept an unrelated suggestion.

The suggestions in the debug console don't work exactly the way I'd like them to, there are some issues with history and suggestions combined with certain syntax, so I wouldn't make it the default unless I fix those issues and tweak the suggestion behavior.

**Comment by fbricon** [comment]
I guess I'll try to keep an eye on your improvements. 
So far "debug.console.acceptSuggestionOnEnter": "on", works as expected with Java completion.
