### ISSUE TITLE
Cannot read properties of undefined (reading 'name')

### ISSUE THREAD

**Issue by ArneMeier** [microsoft/vscode#171705]
I know that a MWE is highly anticipated but I am still in the process to create one. I did not succeed so far, but want to explain the issue. Maybe someone has already an idea. 
I have quite a large lecture LaTeX project and work with LaTeX Workshop v9.4.5 under VSCode Version: 1.74.3 (Universal) under Mac OS Ventura 13.1 (22C65). It does happen only with this particular large LaTeX project.

The situation is the following. When I freshly start VSCode and hit Option+Cmd+B for build the LaTeX file is correctly build. In the end I got a VSCode error message "Cannot read properties of undefined (reading 'name')". After that I am not any longer able to build the project. Neither the key shortcut nor the green arrow build button works nor the buttons in the LaTeX Workshop extension. I tried reinstallation of VScode (including deleting the "Code" folder in Library and Application Support as well as the .vscode folder. But the same happens.

Any ideas?

**Comment by mjbvz** [comment]
Please start by filing this against the LaTeX Workshop  extension
