### ISSUE TITLE
Output Panel issues with Telemetry and Extension Telemetry channels

### ISSUE THREAD

**Issue by luabud** [microsoft/vscode#171757]
Does this issue occur when all extensions are disabled?: Yes

Version: 1.75.0-insider (user setup)
Commit: 5ae522f8563fe48b89470923f77a9732f96c0472
Date: 2023-01-19T14:51:00.913Z
Electron: 19.1.9
Chromium: 102.0.5005.194
Node.js: 16.14.2
V8: 10.2.154.23-electron.0
OS: Windows_NT x64 10.0.22621
Sandboxed: Yes

Steps to Reproduce:

1. Set log level to trace 
2. Open the output window 

There are a couple of issues here:
1 - The background of the channel picker seems to be transparent now, which makes it hard to read:
![image](https://user-images.githubusercontent.com/45497113/213548902-930fdd20-0420-4be0-9a7f-7604b7935b4d.png)

2 - The name of the Extension Telemetry channel has changed to the log file path:

![image](https://user-images.githubusercontent.com/45497113/213548493-8edb4f16-6344-460a-b5d8-fe940c2f9346.png)

3 - The Telemetry channel seems to be completely missing

![image](https://user-images.githubusercontent.com/45497113/213548615-be384030-0ff7-4138-a8e1-3a75499d45c3.png)

For contrast, this is how it looks in VS Code 1.74.3:

![image](https://user-images.githubusercontent.com/45497113/213548744-6f2ae080-abe5-44f3-a466-d81a0af8e1ea.png)

**Comment by Tumisang77ll** [comment]
0723796629

**Comment by sandy081** [comment]
I have done some fixes last week and I assume they could have fixed the missing or wrong labels. Can you please try with the latest insiders and let me know if you can still repro?

**Comment by lramos15** [comment]
For me the extension host telemetry log still has a bad path too, I haven't made any changes here so I think this is caused by output channel changes 
<img width="380" alt="image" src="https://user-images.githubusercontent.com/4544166/214095044-18c7d97e-8ace-4deb-883f-10de39f0e6a1.png">

**Comment by sandy081** [comment]
@sbatten Are you not only seeing the telemetry channel, but also extension telemetry channel?

@lramos15 Yours might be a glitch, can you please restart and try?

**Comment by lramos15** [comment]
@sandy081 Restart doesn't seem to do anything. Should I delete the log file from my VS Code install path?

**Comment by sandy081** [comment]
Which version of insiders are you on?

**Comment by lramos15** [comment]
> Which version of insiders are you on?

Version: 1.75.0-insider (Universal)
Commit: f1b09237cd400d92987cf7a9681995e8011ef54c
Date: 2023-01-23T11:52:31.652Z
Electron: 19.1.9
Chromium: 102.0.5005.194
Node.js: 16.14.2
V8: 10.2.154.23-electron.0
OS: Darwin x64 22.2.0
Sandboxed: No

**Comment by sandy081** [comment]
@lramos15 May I know if you can repro it while running out of sources?

**Comment by sandy081** [comment]
I provided a fix for telemetry log not being shown. 

@lramos15 Lets try to track yours separately

**Comment by sandy081** [comment]
Understood the bug and added the fix to the PR.
