### ISSUE TITLE
Different Views of Terminal History

### ISSUE THREAD

**Issue by rescenic** [microsoft/vscode#171780]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.74.3
- OS Version: Windows 10 22H2 (19045.2486)

Steps to Reproduce:

1. Right click on folder
2. Open in Integrated Terminal

I'm using PSReadLine module in my profile PowerShell setting (notepad $PROFILE): Import-Module -Name PSReadLine.

First View: with List History and I can choose one of them.
![listhistory](https://i.ibb.co/CwZ9SQL/20-01-2023-5783-08-10-55.png)

Second View: with no List History and only PSReadLine works.
![nolisthisory](https://i.ibb.co/6BkqjzR/20-01-2023-5784-08-11-19.png)

How can I activate the First View by default. When I open another folder with 'Open in Integrated Terminal', the First View doesn't work anymore.

**Comment by rescenic** [comment]
![no-terminal-history](https://i.ibb.co/y5FX0Jg/psreadline-vscode-insider.png)
Doesn't work in Insiders build.

**Comment by rescenic** [comment]
![f2-terminal-psreadline](https://user-images.githubusercontent.com/9632756/215359583-11bda0c4-42f4-44c6-9a86-48546644f6e6.png)
I found the answer. Press F2 manually to activate history list in every terminal session.
Source: [powershell-intellisense-completion](https://www.poppastring.com/blog/powershell-intellisense-completion)

**Comment by Tyriar** [comment]
@rescenic you can add `Set-PSReadLineOption -PredictionViewStyle ListView` to your $Profile file to enable it for all sessions
