### ISSUE TITLE
Terminal Inline Suggestions Are Not Distinguishable From Text

### ISSUE THREAD

**Issue by hediet** [microsoft/vscode#171712]
![image](https://user-images.githubusercontent.com/2931520/213428320-78329dc8-0a45-4d2c-8afd-27b7ffce7f04.png)

Left of the cursor is text, right is a suggestion.
The color is basically the same, which is really confusing.

**Comment by Tyriar** [comment]
I brought this up with PowerShell. The plan is for them to use dim https://github.com/PowerShell/PSReadLine/issues/3477 and then for xterm.js to special case the dim style to only need 50% of the minimum contrast ratio which is tracked in https://github.com/xtermjs/xterm.js/issues/4262
