### ISSUE TITLE
Upon opening, Render Whitespace is checked in the titlebar menu but not working

### ISSUE THREAD

**Issue by TonyOTI** [microsoft/vscode#171747]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.74.3
- OS Version: 
Windows 10 Home
Version	21H2
OS build	19044.2486

Steps to Reproduce:

1. Open new instance of VS Code
2. Whitespace is not rendered
3. View -> Appearance -> Render Whitespace and see that it is currently checked on my account
4. Uncheck Render Whitespace, re-check Render Whitespace
5. Whitespace is now rendered

**Comment by rzhao271** [comment]
@TonyOTI sorry for the late reply. Are you still seeing this issue on VS Code 1.96?
