### ISSUE TITLE
Explorer window scrollbar size

### ISSUE THREAD

**Issue by avanember** [microsoft/vscode#171795]
Type: <b>Feature Request</b>

Hi there,

Could you add an option for change the explorer window's vertical scrollbar size please?

Thanks, avanember

VS Code version: Code 1.74.3 (97dec172d3256f8ca4bfb2143f3f76b503ca0534, 2023-01-09T16:59:02.252Z)
OS version: Windows_NT x64 10.0.19045
Modes:
Sandboxed: No

**Comment by lramos15** [comment]
\duplicate https://github.com/microsoft/vscode/issues/30191
