### ISSUE TITLE
Angular error logged via a console.log doesn't show as red in debug console

### ISSUE THREAD

**Issue by jpike88** [microsoft/vscode#171732]
on macOS ventura, using Angular 12.

See screenshot.

![Screenshot 2023-01-19 at 10 16 01 pm](https://user-images.githubusercontent.com/9585787/213480163-6e5c5e5e-0bb0-46fd-8f1b-2e9bca422ec1.png)

The line of code below is what causes the above error to be logged:
```console.error(error);```

But the text is grey, and there doesn't seem to be a way around this, which is a problem.

**Comment by connor4312** [comment]
Seems like the `error` class is not applied to stderr output with variablesReferences

**Comment by connor4312** [comment]
Going to steal this since https://github.com/microsoft/vscode/issues/172868 involves fixing that todo
