### ISSUE TITLE
Multiple lines and insert cursors when clicking mouse wheel and scrolling

### ISSUE THREAD

**Issue by ldicker83** [microsoft/vscode#171768]
Type: <b>Bug</b>
This happens specifically when clicking the mouse wheel button a line above the current line, scrolling the wheel and letting go. This results in multiple highlighted lines and multiple insertion cursors at the end of each line. Characters will be inputted at each insertion cursor.

VS Code version: Code 1.74.3 (97dec172d3256f8ca4bfb2143f3f76b503ca0534, 2023-01-09T16:59:02.252Z)
OS version: Windows_NT x64 10.0.19045
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD FX(tm)-8320 Eight-Core Processor            (8 x 3500)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|23.95GB (13.08GB free)|
|Process Argv|--crash-reporter-id 95b192e6-2a16-4bd8-a3be-ae616d6badfe|
|Screen Reader|no|
|VM|50%|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
language-x86-64-assembly|13x|3.0.0
isort|ms-|2022.8.0
python|ms-|2022.20.2
vscode-pylance|ms-|2023.1.30
jupyter|ms-|2022.11.1003412109
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.14
vscode-jupyter-cell-tags|ms-|0.1.6
vscode-jupyter-slideshow|ms-|0.1.5
genesis-code|Zer|1.4.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vscaat:30438848
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
azure-dev_surveyone:30548225
vsccc:30610678
pyindex848:30577860
nodejswelcome1:30587005
2e4cg342:30602488
89544117:30613380

```

</details>

**Comment by alexdima** [comment]
This is intentional, pressing the middle mouse button and dragging allows inserting multiple cursors. See https://code.visualstudio.com/docs/editor/codebasics#_multiple-selections-multicursor

**Comment by ldicker83** [comment]
Did not know that. Thanks for the response!
