### ISSUE TITLE
Accessibility: Disabled Icons appears as Enabled on mouse hover in High Contrast Mode.

### ISSUE THREAD

**Issue by WiproPSAccTest** [Microsoft/vscode#17179]
VS Code Version:1.6.1
OS Version:1607
**Pre-Requisite:**
1.Open visual studio code editor.
2.Using "Ctrl+Shift+P" key Open the command Pallete.
3.Type Theme, Navigate to Preferences: Color Theme and Hit Enter.
4.Navigate to High Contrast and Hit Enter.

**Steps to Reproduce:**
1.Open visual studio code editor.
2. Using "Ctrl+Shift+D", key navigate to the Debug side view bar option.
3. Open the launch.json file under the "Configure or Fix: launch.json"button and select "Node.js" from the drop down list.
4. Start debugging by pressing F5.
5. Observe the Disabled options like "Step Over", "Step Into" and "Step Out" on mouse over.

**Expected Result:**
Disabled Icons should appears as Disabled on mouse hover even in High Contrast Mode.

**Actual Result:**
Disabled Icons appears as Enabled on mouse hover in High Contrast Mode.

**User Impact:**
Low Vision users might not be knowing that these options are disabled and they will be expecting a change after Invoking these options.

![disabled icons appears as enabled on mouse hover in high contrast mode](https://cloud.githubusercontent.com/assets/22956130/21185698/c26b8c9a-c237-11e6-9e4c-0d2b3313781a.jpg)

**Comment by isidorn** [comment]
fyi @bpasero we introduced a wrong rule for hover feedback in hc mode that I removed with this commit - all seems good now.

**Comment by WiproPSAccTest** [comment]
@isidorn The issue is fixed in vs code editor insider build but still able to reproduce in vs code editor 1.8.1

**Comment by isidorn** [comment]
@WiproPSAccTest insider is what matters, that will become stable soon.

**Comment by WiproPSAccTest** [comment]
Title has been changed to a common format to perform data population.
