### ISSUE TITLE
For GitHub Gists, have Copy Link and Import Profile both accept the Gist URI

### ISSUE THREAD

**Issue by TylerLeonhardt** [microsoft/vscode#171775]
Follow up to https://github.com/microsoft/vscode/issues/171192

I wanted to share my gist with someone, so I clicked Copy Link and was surprised to see:
```
vscode-insiders://profile/github/52c822a931ffa00620641fcd49dbffad
```
instead of the Gist link which is:
https://gist.github.com/TylerLeonhardt/52c822a931ffa00620641fcd49dbffad

I understand that the former is the profile link and you could paste that in to the input flow to inport the gist, but why use a different URI for this?

I think it would be nice for Copy Link to give me the Gist link, and then I'm able to send that to a friend, they can open the link in their browser if they want to see what it contains, _and_ they can use the Gist link directly in the VS Code Import flow.

As it exists today, it feels like we're exposing some implementation detail to users rather than letting them use what they're familiar with (GitHub Gist urls).

**Comment by sandy081** [comment]
Thanks for the feedback and your points are totally valid.

Saving in Github Gist is an implementation detail and we would like users to always use VS Code / VS Code Web for opening and previewing the profile. Hence I am more in favour of dropping Open the link in GitHub and focus more on guiding users to VS Code application. The link used in Copy Link is supposed to be entered in the browser URL that opens VS Code Desktop and shows the profile to import. 

Recently I have implemented support for previewing the profile in Web (vscode.dev). I think we shall rename the buttons (after exporting) to following

1. Copy VS Code Link
2. Copy VS Code Web Link

What do you think?

CC @isidorn

**Comment by sandy081** [comment]
How about copy/open link points to vscode.dev, for eg: https://insiders.vscode.dev/profile/github/9b678dc9ff9449de9bfa140ac89c3e8f

![image](https://user-images.githubusercontent.com/10746682/214081908-fdb52c3e-07cd-46a4-b262-6e7c1c784eb6.png)

**Comment by sandy081** [comment]
I think vscode.dev link is smoother and works everywhere. You can also use this link directly in the import flow in desktop. Opening this link in the browser shows vscode.dev and with code:// schema link asks user to open VS Code. But the latter seems more cryptic and the former seems to be a natural link.

> "Open Link" - can we make it more descriptive? For example "Open in vscode.dev", or "Show Profile in vscode.dev"

We do not use vscode.dev name in the product instead we call Visual Studio Code for the Web. Since it is too long, I preferred to simply have Open Link.

**Comment by sandy081** [comment]
Fixed by https://github.com/microsoft/vscode/pull/172054
