### ISSUE TITLE
[Notebooks] - huge amount of space showing up on top of markdown cells

### ISSUE THREAD

**Issue by claudiaregio** [microsoft/vscode#171898]
All of a sudden there appears to be a bunch of added space above markdown cells. (Note the space between the markdown text and the toolbar) 

![image](https://user-images.githubusercontent.com/19276747/213845789-33af1cde-5ed3-4820-8847-46486b2292af.png)

**Comment by mjbvz** [comment]
Please share the source code of that notebook

**Comment by claudiaregio** [comment]
It happens with every new notebooks I create, do you still want me to share the .ipynb file?

**Comment by mjbvz** [comment]
Yes please

I tried and this looks expected given how the toolbar is positioned:

![Screenshot 2023-01-23 at 11 12 47 AM](https://user-images.githubusercontent.com/12821956/214128899-546f7d10-0b6b-47d0-8012-a20c68e7ac79.png)

**Comment by claudiaregio** [comment]
[markdown_space_bug.zip](https://github.com/microsoft/vscode/files/10482940/markdown_space_bug.zip)

![image](https://user-images.githubusercontent.com/19276747/214129571-abe9e40b-a19b-484f-b5f0-fcd73fce0c35.png)

**Comment by mjbvz** [comment]
Can you please share your notebook layout settings too?

Also what does it look like when the toolbar is on the markdown cell at the top?

**Comment by claudiaregio** [comment]
Closing as per our discussion, will reopen if I see it in the newest stable release
