### ISSUE TITLE
Syntax highlighting errors in js code

### ISSUE THREAD

**Issue by hxfdarling** [Microsoft/vscode#17182]
- VSCode Version: 1.7.2
- OS Version: windows10

![2016-12-14_224722](https://cloud.githubusercontent.com/assets/8198794/21186398/7bea6f94-c24f-11e6-9daa-4bd99480eda8.png)

**Comment by mjbvz** [comment]
@hxfdarling Can you please provide the text source for a file that shows this problem. I believe this issue is fixed in VSCode insiders and 1.8, but would like to verify. 

Thanks

**Comment by hxfdarling** [comment]
this is source file
[karma/common/stringify.js](https://github.com/karma-runner/karma/blob/master/common/stringify.js)

I'm tried in VSCode 1.8 ,but  is't fixed

**Comment by aeschli** [comment]
Fixed in 1.9
