### ISSUE TITLE
Focus in terminal when selecting

### ISSUE THREAD

**Issue by davidgs** [microsoft/vscode#171871]
When you have more than one terminal open, selecting one should automatically put the focus in that terminal. 

It takes 2 clicks (one to select the terminal, one to focus it) when it should really only take one: selecting the terminal gives it focus. 
![Kapture 2023-01-20 at 15 15 07](https://user-images.githubusercontent.com/2071898/213797784-96e529d8-2523-4ec1-a316-1de572873416.gif)

**Comment by meganrogge** [comment]
`terminal.integrated.tabs.focusMode: singleClick` should do that
