### ISSUE TITLE
Wrong strings and missing icon in activity bar

### ISSUE THREAD

**Issue by bwateratmsft** [microsoft/vscode#171834]
_Filed based on https://github.com/microsoft/vscode-docker/issues/3783#issuecomment-1397057523 from @Bananas-Are-Yellow_

The user has installed the Docker extension, and on version 1.23.3, none of the strings show up correctly--instead displaying their placeholder IDs for indexing into package.nls.json--and the icon in the activity bar is blank. Installing 1.22.2 fixes it, but uninstalling and reinstalling 1.23.3 does not. This is the only user we're aware of that is affected by this issue.

![image](https://user-images.githubusercontent.com/36966225/213740815-8dde7bbb-d4e3-4010-a97a-b9c14cabbea0.png)

**Comment by bwateratmsft** [comment]
Seems similar to #159485.

**Comment by TylerLeonhardt** [comment]
@bwateratmsft @Bananas-Are-Yellow was there any error in the dev tools (`>Developer: Toggle Developer Tools`) when you saw this?

Maybe something in the `Window` `Shared` or `Main` Output windows (ctrl+shift+o I think on Windows?)

**Comment by Bananas-Are-Yellow** [comment]
In the first section where it says `%VSCODE-DOCKER.VIEWS,DOCKERCONTAINERS%`, I pressed the Refresh icon that appears when I move the mouse over that heading. In the Dev Tools console output, I got this:

![image](https://user-images.githubusercontent.com/5648989/216307448-addabff9-6ae2-4a17-8996-df0e6345b722.png)

Likewise if I refresh any of the other sections.

**Comment by Bananas-Are-Yellow** [comment]
The problem has gone away for me now. See https://github.com/microsoft/vscode-docker/issues/3783#issuecomment-1413580724 for details.

**Comment by TylerLeonhardt** [comment]
Odd... well if you do see it again, I'd love to know more! Closing this since the repro is gone.

**Comment by bwateratmsft** [comment]
Looks like this hit another user: https://github.com/microsoft/vscode-docker/issues/3853

/cc @matteo-bombelli

**Comment by matteo-bombelli** [comment]
> Looks like this hit another user: [microsoft/vscode-docker#3853](https://github.com/microsoft/vscode-docker/issues/3853)
> 
> /cc @matteo-bombelli

an update:

* reinstalling the plugin with version  v1.24.0 does not solve the issue. (issues only on wsl)
* reverting it back to v1.23.3 does solve the issue

I hope this detail could help for future releases.

**Comment by TylerLeonhardt** [comment]
> issues only on wsl

can you elaborate more on this?

**Comment by matteo-bombelli** [comment]
i have ubuntu and debian installed on windows using wsl (windows subsystem for linux). if I use this extension with workspaces on windows I have no issues, instead if I use it with the one that are on the linux subsystem (both ubuntu and debian) I get the issue described here. If I degrade the version to the old one I get no issue on windows but also no issue on wsl linux.

Thank you!

**Comment by TylerLeonhardt** [comment]
@matteo-bombelli when opening the WSL workspaces, are you using [the WSL extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-wsl)?

**Comment by matteo-bombelli** [comment]
yes I'm using the extension

**Comment by TylerLeonhardt** [comment]
@matteo-bombelli can you share the full recursive directory of the docker extension underneath `~/.vscode-server/extensions/`? The directory should be `ms-azuretools.vscode-docker-1.24.0`

**Comment by matteo-bombelli** [comment]
@TylerLeonhardt on windows or wsl?

**Comment by TylerLeonhardt** [comment]
WSL

**Comment by matteo-bombelli** [comment]
on wsl 

/home/matteo/dev/matteobombelli.tk/ms-azuretools.vscode-docker-1.23.3/

**Comment by matteo-bombelli** [comment]
> on wsl
> 
> /home/matteo/.vscode-server/extensions/ms-azuretools.vscode-docker-1.23.3/

just a note, now I downgraded ... It was 1.24 when the problem was showing.... sorry for the confusion

**Comment by TylerLeonhardt** [comment]
Can you run `tree` on the _good_ directory and _bad_ directory?

I'd love to compare their file structure

**Comment by matteo-bombelli** [comment]
```
matteo@MSI:~/.vscode-server/extensions/ms-azuretools.vscode-docker-1.23.3$ tree
.
├── CHANGELOG.md
├── LICENSE.md
├── NOTICE.html
├── README.md
├── SECURITY.md
├── dist
│   ├── 164.js
│   ├── 488.js
│   ├── 939.js
│   ├── 939.js.LICENSE.txt
│   ├── compose-language-service
│   │   └── lib
│   │       ├── server.js
│   │       └── server.js.LICENSE.txt
│   ├── dockerfile-language-server-nodejs
│   │   └── lib
│   │       └── server.js
│   ├── extension.bundle.js
│   ├── extension.bundle.js.LICENSE.txt
│   └── node_modules
│       ├── @microsoft
│       │   └── vscode-azext-azureutils
│       │       └── resources
│       │           ├── azure.svg
│       │           └── azureSubscription.svg
│       └── open
│           └── xdg-open
├── main.js
├── package.json
├── package.nls.json
└── resources
    ├── azureRegistry.svg
    ├── dark
    │   └── docker.svg
    ├── docker.svg
    ├── docker_blue.png
    ├── gitlab.svg
    ├── light
    │   └── docker.svg
    ├── netCore
    │   ├── GetBlazorManifestLocations.targets
    │   ├── GetProjectProperties.targets
    │   └── vsdbg
    ├── python
    │   └── launcher.py
    ├── templates
    │   ├── cpp
    │   │   └── Dockerfile.template
    │   ├── docker-compose.debug.yml.template
    │   ├── docker-compose.yml.template
    │   ├── go
    │   │   └── Dockerfile.template
    │   ├── java
    │   │   ├── Dockerfile.template
    │   │   └── docker-compose.debug.yml.template
    │   ├── netCore
    │   │   ├── Dockerfile.template
    │   │   ├── docker-compose.debug.yml.template
    │   │   └── docker-compose.yml.template
    │   ├── node
    │   │   ├── Dockerfile.template
    │   │   ├── docker-compose.debug.yml.template
    │   │   └── docker-compose.yml.template
    │   ├── other
    │   │   └── Dockerfile.template
    │   ├── python
    │   │   ├── Dockerfile.template
    │   │   ├── docker-compose.debug.yml.template
    │   │   ├── docker-compose.yml.template
    │   │   └── requirements.txt.template
    │   └── ruby
    │       └── Dockerfile.template
    └── walkthroughs
        └── empty.md
```

**Comment by matteo-bombelli** [comment]
now it works even 1.24.0 🤨

**Comment by TylerLeonhardt** [comment]
The bug realized we were on to it, so it decided to hide. @matteo-bombelli are you using VS Code stable or insiders?

**Comment by matteo-bombelli** [comment]
> The bug realized we were on to it, so it decided to hide. @matteo-bombelli are you using VS Code stable or insiders?

stable

**Comment by TylerLeonhardt** [comment]
Ok sounds good. We did have a few smaller fixes in the translation stuff this past month so this might go away... in any case, since we don't have a repro anymore, I'll close this.

When this _does_ happen to someone again, I would love the contents of the `Shared` output channel... and maybe the contents of Dev Tools (`Toggle Developer Tools` in Command Palette) as well
