### ISSUE TITLE
ExtHostLanguageFeatureCommands unit test fail - macos

### ISSUE THREAD

**Issue by andreamah** [microsoft/vscode#171849]
```
 1) ExtHostLanguageFeatureCommands
       Suggest, back and forth:

      
      + expected - actual


  Error: Timeout of 5000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
```
https://dev.azure.com/monacotools/Monaco/_build/results?buildId=200242&view=logs&j=55ac390b-ffb1-50ea-3650-525dd9a3fd80&t=3a692518-c3cf-5f6a-c273-72f71dc185fb

**Comment by jrieken** [comment]
closing because this was likely a fluke. The code/test is around since years and don't do anything special in comparison to the all the other tests in the same suite
