### ISSUE TITLE
Comment widget unreadable with high contrast theme

### ISSUE THREAD

**Issue by laurentlb** [microsoft/vscode#171830]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.74.3
- OS Version: Linux

Steps to Reproduce:

I was able to repro on https://github.dev/:

1. Set theme to `Dark High Contrast`
2. Find a file that has a comment (e.g. with the GitHub Pull Request integration)

Actual:
![image](https://user-images.githubusercontent.com/485572/213718372-cb69da2b-5b13-4a54-9792-2bec7e93918a.png)

Notice that the text "Reply..." and the icons are not readable.

For comparison, here is a screenshot with the default dark theme:

![image](https://user-images.githubusercontent.com/485572/213718780-473fdf28-231b-4ff5-b1ab-9ece7abc4655.png)

**Comment by alexr00** [comment]
I can repro on VS Code stable, but not with VS Code insiders. Seems like this has been fixed.

**Comment by alexr00** [comment]
Fix for the icon bar was here: https://github.com/microsoft/vscode/issues/170024
