### ISSUE TITLE
Terminal accessibility broken

### ISSUE THREAD

**Issue by steverep** [microsoft/vscode#171833]
Type: <b>Bug</b>

On latest insiders, terminal accessibility with NVDA screen reader seems completely broken.  There is now no spoken feedback while typing, nor any spoken output after entering a command.

There is now a new message to press ALT + F1 for accessibility help when switching to the terminal, but pressing those keys seems to do nothing.

VS Code version: Code - Insiders 1.75.0-insider (9ccc2b3b30c122afe45bc6722bef0e3901fb2806, 2023-01-20T05:23:24.298Z)
OS version: Windows_NT x64 10.0.19045
Modes:
Sandboxed: Yes
Remote OS version: Linux x64 5.10.102.1-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3570K CPU @ 3.40GHz (4 x 3400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|7.70GB (1.08GB free)|
|Process Argv|--crash-reporter-id 2264703e-acb2-4e8f-b637-a3dc1f5bd270|
|Screen Reader|yes|
|VM|0%|

|Item|Value|
|---|---|
|Remote|Dev Container: Home Assistant Frontend|
|OS|Linux x64 5.10.102.1-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i5-3570K CPU @ 3.40GHz (2 x 3400)|
|Memory (System)|3.83GB (0.63GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30422396
pythontb:30258533
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscod805cf:30301675
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30404738
cppdebug:30492333
vsclangdf:30492506
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30618038
pylantcb52:30590116
pyindex848:30611229
nodejswelcome1:30587009
pyind779:30611226
pythonsymbol12:30622696
a9j8j154:30646983

```

</details>

**Comment by steverep** [comment]
@meganrogge your commits from yesterday seem like the probable culprit here.

**Comment by meganrogge** [comment]
The issues mentioned in #169853 already have fixes and will be resolved in the next insider's build.
