### ISSUE TITLE
Screen Cheese: `âœ“ Uninstalled` extension action item

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/vscode#171855]
I see `âœ“ Uninstalled` when I have uninstalled an extension:

![Recording 2023-01-20 at 10 23 49](https://user-images.githubusercontent.com/8586769/213777531-d94a601b-341c-4fdc-93e8-51e6a6bd59e2.gif)

Seems to be CSS  in `.action-item.disabled .action-label.extension-status-label:before`'s `content` style that has somehow been corrupted? In sources its a `✓` glyph: https://github.dev/microsoft/vscode/blob/7fe57a2f7a2f5b272fe4c44e97b352dcbba20a88/src/vs/workbench/contrib/extensions/browser/media/extensionActions.css#L132-L135

But when I inspect the element I see the cheese string

Reproduces with extensions disabled, v1.74.3 on macOS.

cc @sandy081 I believe?

**Comment by sandy081** [comment]
Related to codicons

**Comment by daviddossett** [comment]
<img width="284" alt="CleanShot 2023-01-31 at 11 42 33@2x" src="https://user-images.githubusercontent.com/25163139/215865654-2e7086bd-d330-4912-85d8-e7c3f3441e61.png">

Not seeing this anymore. Still an issue?

**Comment by JacksonKearl** [comment]
seems fine now 🤷‍♀️
