### ISSUE TITLE
VS remotely controlled?

### ISSUE THREAD

**Issue by eappatt** [Microsoft/vscode#17184]
I have been working on my projects for a few months. All of a sudden today, while I was making updates in the html and css docs, VS was not following what I type - almost as if my VS was being hacked and remotely controlled.  Then, every time pressed 'return' to go to a new line, it deleted lines of code that I had already typed. Furthermore, it would not allow me to 'undo' the changes that it was making. Thank God I have the codes saved in back up locations. I went onto VS's site to check for any updates and I tried debugging it but nothing worked so far.  Why is VS acting this way all of a sudden? 

- VSCode Version:
- OS Version: mac book pro

Steps to Reproduce:

1. 
2.

**Comment by kieferrm** [comment]
@eappatt weird.  Outside of the editor things are still working fine? Can you pls use `Report Issues` from the Help menu and copy the pre-populated text in the new github issue into this one. Also anything in your console when you use `Toggle Developer Tools` from the Help menu?

**Comment by eappatt** [comment]
Thank you for replying.

"I have been working on my projects for a few months. All of a sudden today, while I was making updates in the html and css docs, VS was not following what I type - almost as if my VS was being hacked and remotely controlled. Then, every time pressed 'return' to go to a new line, it deleted lines of code that I had already typed. Furthermore, it would not allow me to 'undo' the changes that it was making. Thank God I have the codes saved in back up locations. I went onto VS's site to check for any updates and I tried debugging it but nothing worked so far. Why is VS acting this way all of a sudden?” 

I am not sure how other things are working in the editor because I have basically been using it for html and css.  

What exactly should I look for in Toggle Developer Tools?

**Comment by eyalsk** [comment]
@eappatt 

>  Then, every time pressed 'return' to go to a new line, it deleted lines of code that I had already typed. 

If this was an attacker and someone actually controlled VSCode then he didn't have to wait for you to press enter, also, he could just delete or encrypt the project and depends on permissions, maybe the whole drive.

Sounds like a weird bug to me.

> it would not allow me to 'undo' the changes that it was making.

Again, sounds like a bug more than an attacker.

**Comment by eappatt** [comment]
Thank you. The "attacker" comment was to make a comparison as to how VS was acting. I clicked on it's "debug" icon and restated my laptop but it still worked the same way. Any other suggestions? Once again, thank you

-E.Patt

**Comment by bgse** [comment]
Maybe someone playing a prank on you by messing with your shortcut settings?

You could check the keyboard shortcut settings, or maybe look in system tray for any new keyboard shortcut tool.

Just a guess.

**Comment by eyalsk** [comment]
@eappatt 

Yeah, well, just a thought to clarify any assumptions about it if you even had any. :)

Another possibility in addition to what @bgse you may want to check your keyboard, maybe some key got stuck? it's _unlikely_ but still worth checking.

Maybe it's a program that you installed recently like a launcher application of some sort that messes with the input by installing a global keyboard hook.

Check your extensions.

Finally, try to repeat your latest actions in order to reproduce the problem.

**Comment by siegebell** [comment]
@eappatt have you tried to start vscode with `--disable-extensions` yet? If that solves the problem, you should post your installed extensions (`----list-extensions`). If that doesn't work, maybe try `--user-data-dir` to temporarily set your user profile to a new directory.

**Comment by eappatt** [comment]
You might be right because I had to go back & redo a lot of coding in one of my projects... But I don't know how that happened. If I need to, I'll google how to reset the shortcuts. Thank you. 

-E.Patt

**Comment by eappatt** [comment]
Thank you. I couldn't find any of those options but I checked out setting, deleted "auto save: after.delay" or something like that, then it started working the way it had been. Interesting but I will keep a look out. Once again, thank you all for taking the time to read & reply. 

-E.Patt

**Comment by kieferrm** [comment]
@eappatt for clarification. Once you switched off autosave your system started to behave correctly again? It would be helpful if you could share the list of extensions you have installed and the version of code you are using. The easiest is if you go to the `Help` menu and choose `Report Issues` and copy the text from the pre-populated issue into this one. Thanks!

**Comment by egamma** [comment]
@eappatt can you pls answer the question in comment https://github.com/Microsoft/vscode/issues/17184#issuecomment-267667574

**Comment by eappatt** [comment]
So sorry for late reply. I was away for weekend & wanted to wait a while & add more code to REALLY make sure and so far so good. Checking & modifying my settings seemed to have been the solution. 

-E.Patt

**Comment by eappatt** [comment]
So sorry for late reply. I was away for weekend & wanted to wait a while & add more code to REALLY make sure and so far so good. Checking & modifying my settings seemed to have been the solution. 

-E.Patt

**Comment by eyalsk** [comment]
@eappatt It would be nice if you could do this though:

> The easiest is if you go to the Help menu and choose Report Issues and copy the text from the pre-populated issue into this one.

This _might_ help them do some internal testing and maybe reproduce it.

**Comment by egamma** [comment]
@eappatt thanks for getting back to us. Please reopen the issue when you can reproduce it.
