### ISSUE TITLE
'sudo code file' doesn't work.

### ISSUE THREAD

**Issue by ka2rvo** [microsoft/vscode#171878]
Type: <b>Feature Request</b>

Yeah, I know all the reasons why this is a bad idea, but it's my choice to make.

The user-data-dir is a lot of unnecessary typing.

Sometimes you need to edit a file owned by root.

"sudo vim file" works just fine, "sudo code file" should work just as well. At least put an option to disable this check.

VS Code version: Code 1.74.3 (97dec172d3256f8ca4bfb2143f3f76b503ca0534, 2023-01-09T16:57:40.428Z)
OS version: Linux x64 5.15.0-58-generic snap
Modes:
Sandboxed: No

**Comment by bpasero** [comment]
> Sometimes you need to edit a file owned by root

We allow you to save a file as admin by briefly elevating the process, have you tried, or does that not work?

**Comment by ka2rvo** [comment]
That does work, but it is a hassle. If you have a file open, leave it open,
you have to enter a password every time you change it and save it.

This comes up on development virtual machines. These are low value systems,
if I screw them up, just revert the snapshot. I don't care about security
in this case, I just need to get stuff done without having to enter
passwords all over the place. I set the sudo timeout to 8 hours and don't
worry about it all day.

sudo is for the end user to use as they see fit, without application
software second guessing the end user. An option buried in the settings
would be nice, like the option for workspace trust.

**Comment by bpasero** [comment]
If you run `sudo code --no-sandbox --disable-gpu-sandbox file` does it work?

**Comment by ka2rvo** [comment]
If you give it the --user-data-dir it does. That's a lot of verbosity that
'sudo vim my_file" doesn't have, but vim is never my first choice of
editors.

***@***.***:~$ cd /etc/mosquitto/
***@***.***:/etc/mosquitto$ cd conf.d/
***@***.***:/etc/mosquitto/conf.d$ sudo code --no-sandbox
--disable-gpu-sandbox local.conf
[sudo] password for jaustin3:
You are trying to start Visual Studio Code as a super user which isn't
recommended. If this was intended, please add the argument `--no-sandbox`
and specify an alternate user data directory using the `--user-data-dir`
argument.
***@***.***:/etc/mosquitto/conf.d$ sudo code --no-sandbox
--disable-gpu-sandbox --user-data-dir /home/jaustin3/ local.conf
Warning: 'disable-gpu-sandbox' is not in the list of known options, but
still passed to Electron/Chromium.
***@***.***:/etc/mosquitto/conf.d$

**Comment by bpasero** [comment]
This is the only way sorry. We really do not recommend to run VS Code as `sudo`.
