### ISSUE TITLE
HTML Intellisense and snippets not working for HTML in PHP file

### ISSUE THREAD

**Issue by smlombardi** [Microsoft/vscode#17188]
- VSCode Version: Code - Insiders 1.8.0-insider (2abfc207828739bd5b10d0bb8dbfea13506cfc69, 2016-12-13T09:48:23.832Z)
- OS Version: Darwin x64 16.1.0
- Extensions:

|Extension|Author|Version|
|---|---|---|
|material-icon-theme|PKief|1.1.4|
|code-settings-sync|Shan|2.3.8|
|sort-lines|Tyriar|1.1.0|
|html-css-class-completion|Zignd|1.0.3|
|Bookmarks|alefragnani|0.10.1|
|project-manager|alefragnani|0.12.2|
|one-monokai|azemoh|0.2.3|
|vscode-icontheme-nomo-dark|be5invis|1.2.1|
|vscode-eslint|dbaeumer|1.1.0|
|githistory|donjayamanne|0.1.4|
|tslint|eg2|0.7.1|
|vscode-great-icons|emmanuelbeziat|1.1.26|
|Angular2|johnpapa|1.0.2|
|theme-karyfoundation-themes|karyfoundation|10.0.0|
|HTMLHint|mkaufman|0.3.3|
|vscode-stylefmt|mrmlnc|2.2.0|
|Theme-1337|ms-vscode|0.1.2|
|angular2-inline|natewallace|0.0.16|
|nonbreakingspace|smlombardi|0.0.1|
|vscode-icons|robertohuertasm|4.1.0|
|stylelint|shinnn|0.20.4|
|theme-tesla|smlombardi|5.3.9|
|bootstrap-3-snippets|wcwhitehead|0.0.8|
|change-case|wmaurer|1.0.0|

---

Steps to Reproduce:

1. In a PHP file, and HTML block like this:
```html
<div class="row">
     <div class="col-md-6 col-md-offset-6">
                PAST NEWS Archive
       </div>
 </div>
```
2. Although I have the[ Bootstrap 3 snippets extension](https://marketplace.visualstudio.com/items?itemName=wcwhitehead.bootstrap-3-snippets), and it works in HTML files, the above Bootstrap classes are not suggested here.

This is also an issue with built-in Intellisense: add an attribute like "class" and although the word class is suggested, choosing it does not add the usual `=""` as it does in HTML files.

**Comment by roblourens** [comment]
For now you will have to copy the HTML snippets into your PHP snippets file. Discussion for PHP/HTML feature mix/matching has been happening here: https://github.com/Microsoft/vscode/issues/2915
