### ISSUE TITLE
Test: terminal accessibility improvements

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#171862]
Refs #169853, #170977

- [x] Windows @joyceerhl 
- [x] macOS @lszomoru 
- [x] Linux @lramos15

Complexity: 4

Authors: @meganrogge @Tyriar 

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23171862%0A%0A&assignees=meganrogge,Tyriar)

---

We've made 2 improvements to the terminal's accessibility this iteration:
- A terminal accessibility help menu that aligns with the one in the editor (`Show Accessibility Help`)
    - Test with `Terminal: Show Terminal Accessibility Help` and the keybinding with the terminal focused macOS: `alt+f1` linux/windows: `shift+f1`
    - With `editor.accessibilitySupport` enabled and a screen reader attached, verify that when you focus the terminal, you hear the keybinding for this
- A new mode for the terminal that allows screen readers to read the buffer
    - Test with `Toggle Screen Reader Accessibility Mode` and with the keybinding `Shift+Tab`
    - Use a screen reader to verify that you can read the contents of the terminal via arrow keys

**Comment by lszomoru** [comment]
I have tested the new terminal accessibility menu, and I started testing the new mode but I am running into some issues with the VoiceOver on macOS. I have reached out to Isi and I will spend some more time on this first thing tomorrow morning.

**Comment by meganrogge** [comment]
@lszomoru sounds good, feel free to create issues so I can address the problems you're having async
