### ISSUE TITLE
Add markdown code box to extention page vscode🧐

### ISSUE THREAD

**Issue by Mohammadev82** [microsoft/vscode#171823]
sample:
```
https://github.com/git repository link
```
for easier access
Please🙏

**Comment by gjsjohnmurray** [comment]
You mean this, right?
![image](https://user-images.githubusercontent.com/6726799/213774961-d8b644cf-488b-4a70-b929-83b263f6de36.png)

**Comment by Mohammadev82** [comment]
## In addition, display the repository link
----------
![kdfoe](https://user-images.githubusercontent.com/105316207/213799366-7d6829c3-3807-474f-bd12-a790e5e04a4b.png)
## for repository remote in vscode
## There are also many empty spaces
----------
![kdkdk](https://user-images.githubusercontent.com/105316207/213799857-f863c58f-0941-4155-93c5-6de02554aee6.png)

**Comment by chosig** [comment]
@Mohammadev82, there's a link to the repository on the right side `Extension Resourses` > `Repository` already (it's by top of the 3 you painted).
