### ISSUE TITLE
Accessibility:MAS13:Menus and context menu are not zooming in with the rest of the UI

### ISSUE THREAD

**Issue by WiproPSAccTest** [Microsoft/vscode#17180]
VS Code Version:1.6.1
OS Version:1607
**Pre-Requisite:**
1.Open visual studio code editor.
2.Using "Ctrl+" key repeatedly To Zoom to the Maximum

**Steps to Reproduce:**
Scenario 1:
1.Open visual studio code editor.
2.Observe the Menu Bar Visually on Zoom
Scenario 2:
1. Open visual studio code editor.
2. Hit "Ctrl+Shift+G" to view the Git side bar and Navigate to more button and Hit Enter.
3. Observe the options under More button on Zoom
Scenario 3:
1. Open visual studio code editor.
2. Hit "Ctrl+Shift+X" to view the Extensions side bar and Navigate to more button and Hit Enter.
3. Observe the options under More button on Zoom.

**Expected Result:**
Scenario 1:
Menu Bar and options under Menu Bar should Adapt the Zoom feature of VS Code Editor
Scenario 2:
Icons under More in Git Repository  side bar should Adapt the Zoom feature of VS Code Editor
Scenario 3:
Icons under More in Extensions  side bar should Adapt the Zoom feature of VS Code Editor

**Actual Result:**
Scenario 1:
Menu Bar and options under Menu Bar is not adapting the Zoom feature of VS Code Editor
Scenario 2:
Icons under More in Git Repository  side bar are not Adapting the Zoom feature of VS Code Editor
Scenario 3:
Options under More in Extensions side bar are not Adapting the Zoom feature of VS Code Editor

**User Impact:**
Low Vision users will not be able to clearly view these options as they are not adapting the Zoom feature of the application

![scenario 1_menu bar and options under menu bar are not adapting the zoom feature of vs code editor](https://cloud.githubusercontent.com/assets/22956130/21185893/808c3026-c238-11e6-984a-22ee652a4157.jpg)
![scenario 2_options under more button in git side bar is not adapting the zoom feature of vs code editor](https://cloud.githubusercontent.com/assets/22956130/21185895/83a564c6-c238-11e6-8784-b11505d06065.jpg)
![scenario 3_options under more button in extensions side bar is not adapting the zoom feature of vs code editor](https://cloud.githubusercontent.com/assets/22956130/21185898/87b38fb6-c238-11e6-96ff-5924f3ff0a41.jpg)

**Comment by therealkenc** [comment]
I think this is probably a naive question, so apologies in advance for that. This was marked as 'upstream', which I "get" because Electron is responsible for the menu bar. Is it possible, even in a theoretic sense, to do the menubar UX in CSS/HTML rather than depend on Electron? Has this been discussed before? (even in a general Electron programming sense, assuming it's even a well formed question). I tried a quick Google search, but with such common terms like 'menu', and 'electron' to work with the results get swamped with more mundane results as opposed to trying to do something that is at best "unusual" for an Electron app.

**Comment by WiproPSAccTest** [comment]
Title has been changed to a common format to perform data population.

**Comment by bpasero** [comment]
@sbatten I noticed that you prevent zooming of the menu, maybe we should revisit that decision based on this issue.

**Comment by sbatten** [comment]
@bpasero I agree we need to discuss this one. Currently, menus that aren't part of the menubar will zoom, while those associated with the menubar and the menubar itself will not. If we wanted to support this, I think we would need to send the menubar to its own row (its original position) either when zooming or as a setting which would then allow zooming.

**Comment by bpasero** [comment]
> If we wanted to support this, I think we would need to send the menubar to its own row

Or we have a maximum zoom level for it, if space is a problem?

**Comment by sbatten** [comment]
@bpasero could work although the limit may be too little?
![image](https://user-images.githubusercontent.com/6561887/42466164-fe9655e0-8362-11e8-8f6b-489ece872f76.png)

default zoom
![image](https://user-images.githubusercontent.com/6561887/42466247-2ea319f8-8363-11e8-8a30-7679c468a8c9.png)

on new line
![image](https://user-images.githubusercontent.com/6561887/42466635-4cfae916-8364-11e8-9cad-4663cf3dbf8c.png)

with editor color
![image](https://user-images.githubusercontent.com/6561887/42466567-1f634340-8364-11e8-9302-996c1bce91bc.png)

**Comment by bpasero** [comment]
@sbatten did you try keeping the menu on the same line, is that not working with zooming?

**Comment by sbatten** [comment]
@bpasero the first option is keeping it on with zooming. That is about the limit on the amount of zooming before it looks weird...er

**Comment by sbatten** [comment]
@bpasero yes, in the first one, that's about as large as you can get it without making the titlebar bigger or cutting off the text so if you rely on zoom it might be too small.

**Comment by bpasero** [comment]
@sbatten what about allowing to zoom in the entire title div if the custom menu is enabled?

**Comment by sbatten** [comment]
@bpasero here is what that looks like if I understand you correctly. The controls and app icon look the weirdest. (edge in background for reference)
![image](https://user-images.githubusercontent.com/6561887/42650832-5a6bf328-85c2-11e8-80fc-5a9e09157a87.png)

**Comment by bpasero** [comment]
@sbatten seems OK'ish to me, maybe make a branch or PR for me to play with?
