### ISSUE TITLE
Select dropdown has transparent background in VSCode Settings

### ISSUE THREAD

**Issue by lorand-horvath** [microsoft/vscode#171804]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.75.0 Insiders
- OS Version: Win 10

Steps to Reproduce:

Initially discovered in https://github.com/microsoft/vscode/issues/166265#issuecomment-1398024284
The VSCode Settings show select dropdowns having seemingly transparent background, so the options' texts are mixing with the document flow beneath the dropdown. It is probably a CSS regression in 1.75.0 Insiders https://github.com/microsoft/vscode/issues/166265#issuecomment-1398111460 because 1.74.3 doesn't exhibit this problem 

![image](https://user-images.githubusercontent.com/72015221/213643300-afdd4d1d-e952-4083-afc9-8b01d8d82f00.png)

**Comment by gjsjohnmurray** [comment]
See already #171774
