### ISSUE TITLE
Ignore URL params when debugging and following Click to follow links in Debug Console

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#17183]
_From @pjsvis on December 14, 2016 13:34_

1. I use a version param to help with cache busting
2. EG http://localhost:55693/OTS.UTP/scripts/app/SomeFile.js?v=20161114132417363:107:48 
3. When I click in the Debug Console to follow the link it reports Unable to open 'SomeFile.js?v=20161114132417363': File not found (\\localhost:55693\OTS.UTP\scripts\app\SomeFile.js?v=20161114132417363).
4. I guess this is because of the param
5. It would be a nice enhancement if you could ignore the param
6 Otherwise chrome debugger is tons of fun

_Copied from original issue: Microsoft/vscode-chrome-debug#307_

**Comment by roblourens** [comment]
It's also because of the URL. The console is looking for absolute paths, it won't download files.

**Comment by gdh1995** [comment]
+1.

And I find that when I click a link in one opened HTML file (such as `<script src=a.js?v2>`), VSCode also fails to open the correct file, which is so inconvenient.

**Comment by connor4312** [comment]
Linkification was added again recently in https://github.com/microsoft/vscode/pull/80502. It looks like query parameters are now dealt with property.

![image](https://user-images.githubusercontent.com/2230985/66434453-744db180-e9d7-11e9-9f49-d54bc7ece8c2.png)
