### ISSUE TITLE
throng module is not possible to debug

### ISSUE THREAD

**Issue by cherchyk** [Microsoft/vscode#1718]
I started to use throng module to support multi concurrency.

node web.js command from cmd runs application
but f5 in VSC never enters start function

here is sample code

'use strict';

var throng = require('throng');
var config = require('config');
var http = require('http');

// setting server
var server = require('./server');

http.globalAgent.maxSockets = Infinity;
throng(start, {
	workers: config.concurrency,
	lifetime: Infinity
});

function start() {

	process.on('SIGTERM', shutdown);

	// starting server
	server.start();

	function shutdown() {
		process.exit();
	}
}

**Comment by bpasero** [comment]
@cherchyk what node.js version are you trying with?

**Comment by weinand** [comment]
@cherchyk did you try to attach to the correct process? VSCode does not yet support clusters, but it should be possible to attach VSCode to a process within the cluster if you know the debug port of the process. See https://github.com/Microsoft/vscode/issues/865

**Comment by weinand** [comment]
We will cover this in #865
