### ISSUE TITLE
Golang 1.7.4 breaks navigation outside package

### ISSUE THREAD

**Issue by entonio** [Microsoft/vscode#17189]
- VSCode Version: 1.7.2
- OS Version:

Steps to Reproduce:

1. Install go 1.7.4
2. Try to navigate to a symbol outside the current package
3. Doesn't do anything

I've tried going back to Go 1.7.3 and navigation started working again.
I've tried placing `"go.docsTool": "gogetdoc"` in the user settings but found no difference.

**Comment by ramya-rao-a** [comment]
This issue was moved to Microsoft/vscode-go#688
