### ISSUE TITLE
vscode search by page weightage

### ISSUE THREAD

**Issue by deepaksood619** [microsoft/vscode#171977]
Searching for a term/terms should not be taken literarily and exact match, but should find closest match and rank pages by weightage of the search terms, like pages having high number of matches should be on top and descending thereafter.

Use cases - I manage my notes in markdown files using vscode + foam, an alternative to obsidian, so can search for words in pages

Ex - searches in onenote, obsidian, etc

**Comment by andreamah** [comment]
You can set "search.sortOrder": "countDescending" in your settings so that files with more matches will appear first in the search result list view.
