### ISSUE TITLE
Instrument Inline Completions Hover

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#171966]
Currently we are assuming that the Inline Completions Hover is not used by users, but we are in the dark since we do not actually have the numbers to confirm this. Also any changes that we do towards improving this we will not be measureble without telemetry. Due to that I propose we add telemetry events when:
* Inline Completions Hover is shown
* A action is executed from the inline completions hover, ideally it is the usual `workbenchActionExecuted` but the `from` field nicely points to the `InlineCompletionsHover` so we can actually figure out what users are clicking on

fyi @jrieken

**Comment by jrieken** [comment]
> A action is executed from the inline completions hover, ideally it is the usual workbenchActionExecuted but the from

@hediet That just works when using `MenuWorkbenchToolBar` or `WorkbenchToolBar`
