### ISSUE TITLE
Debugging in C not working when math function used

### ISSUE THREAD

**Issue by aarushwagdarikar** [microsoft/vscode#171939]
Type: <b>Bug</b>

I have been having this problem for a while now. I do C programming on VS code and whenever I used any function from Math.h library, the debugging crashed. The program does not compile normally. It gives error launch.jason does not exist. Can anyone help me solve this problem! Thanks a lot. 

VS Code version: Code 1.74.3 (97dec172d3256f8ca4bfb2143f3f76b503ca0534, 2023-01-09T16:57:40.428Z)
OS version: Linux x64 5.15.0-58-generic
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz (4 x 2900)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|0, 0, 0|
|Memory (System)|15.51GB (12.80GB free)|
|Process Argv|--unity-launch --crash-reporter-id 351681da-9578-4595-adb8-9ecafd7d361e|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|wayland|
</details><details><summary>Extensions (26)</summary>

Extension|Author (truncated)|Version
---|---|---
npm-intellisense|chr|1.4.4
path-intellisense|chr|2.8.4
doxdocgen|csc|1.4.0
vscode-eslint|dba|2.2.6
vscode-npm-script|eg2|0.3.29
code-runner|for|0.11.8
vscode-pull-request-github|Git|0.56.0
search-node-modules|jas|1.3.0
better-cpp-syntax|jef|1.17.2
solidity|Jua|0.0.141
vscode-docker|ms-|1.23.3
remote-containers|ms-|0.266.1
remote-ssh|ms-|0.94.0
remote-ssh-edit|ms-|0.84.0
remote-wsl|ms-|0.72.0
cmake-tools|ms-|1.13.40
cpptools|ms-|1.13.9
cpptools-extension-pack|ms-|1.3.0
remote-explorer|ms-|0.0.3
vsliveshare|ms-|1.0.5808
vsliveshare-audio|ms-|0.1.91
open-in-browser|tec|2.0.0
tondev|TON|0.5.0
cmake|twx|0.0.17
nodejs-extension-pack|wad|0.1.9
JavaScriptSnippets|xab|1.8.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
azure-dev_surveyone:30548225
pyindex848:30577860
nodejswelcome1:30587005
282f8724:30602487
89544117:30613380
2i9eh265:30646982

```

</details>

**Comment by roblourens** [comment]
Please file this issue on the cpptools extension, thanks
