### ISSUE TITLE
Extensions: Install Missing Dependencies does not detect dependencies in Extension Development Host

### ISSUE THREAD

**Issue by renamethislater1** [microsoft/vscode#171940]
Does this issue occur when all extensions are disabled?: No, but it's in the gray area

- VS Code Version: 1.74.3
- OS Version: Windows 10 22H2

I've created a stackoverflow question here:
https://stackoverflow.com/questions/75197093/vscode-extension-development-host-does-not-allow-enabling-extension-dependencies

Steps to Reproduce:

1. Create a VS Code extension where there it will get another extension, example below
`await vscode.extensions.getExtension("michaelcurrin.auto-commit-msg"`
2. Place the extension dependency in package.json, example below
```
  "extensionDependencies": [
    "michaelcurrin.auto-commit-msg"
  ],
```
3. Enter the Extension Development Host and attempt to run "Extensions: Install Missing Dependencies" from the Command Palette.
4. There will be an error saying: There are no missing dependencies to install.

Enabling the extension manually cannot be done because the button will be greyed out, and the Extensions: Enable All Extensions does not do anything either.

**Comment by Wesfluegel762** [comment]
> Does this issue occur when all extensions are disabled?: No, but it's in the gray area
> 
> * VS Code Version: 1.74.3
> * OS Version: Windows 10 22H2
> 
> I've created a stackoverflow question here: https://stackoverflow.com/questions/75197093/vscode-extension-development-host-does-not-allow-enabling-extension-dependencies
> 
> Steps to Reproduce:
> 
> 1. Create a VS Code extension where there it will get another extension, example below
>    `await vscode.extensions.getExtension("michaelcurrin.auto-commit-msg"`
> 2. Place the extension dependency in package.json, example below
> 
> ```
>   "extensionDependencies": [
>     "michaelcurrin.auto-commit-msg"
>   ],
> ```
> 
> 3. Enter the Extension Development Host and attempt to run "Extensions: Install Missing Dependencies" from the Command Palette.
> 4. There will be an error saying: There are no missing dependencies to install.
> 
> Enabling the extension manually cannot be done because the button will be greyed out, and the Extensions: Enable All Extensions does not do anything either.

**Comment by renamethislater1** [comment]
I'm not sure what you are trying to say, you've just repeated my post without any additional information.

**Comment by sandy081** [comment]
> Enter the Extension Development Host

After entering Extension Development Host, have you seen any error message?

**Comment by renamethislater1** [comment]
No, it is just when I run the code which tries to get the extension it will say it can't because the dependency extension is disabled.

**Comment by sandy081** [comment]
> No, it is just when I run the code which tries to get the extension it will say it can't because the dependency extension is disabled.

Do you have the dependency extension installed then? May I know how you are running the extension?

**Comment by renamethislater1** [comment]
I just run it using F5, as specified in the documentation.

I can't install the dependency extension, that is the issue I am having. The enable button is greyed out and the commands Extensions: Enable All Extensions and Extensions: Install Missing Dependencies don't do anything.

**Comment by sandy081** [comment]
May be I am missing something here, can you please provide a gif/video of what you are doing?

**Comment by renamethislater1** [comment]
Extensions: Install Missing Dependencies (the command) doesn't work in Extension Development Host. You can't enable the extensions you want manually because the button is greyed out.
Here is the video:

https://user-images.githubusercontent.com/118122811/214938890-3feaa5d3-6e92-4666-a7b3-cefca5464052.mp4

**Comment by sandy081** [comment]
It seems all extensions are temporarily disabled in the extension debugging window. Can you please share your debug launch config?

**Comment by renamethislater1** [comment]
This is the launch config:
```
"args": [
        "--disable-extensions",
        "--extensionDevelopmentPath=${workspaceFolder}"
],
```
I am aware that the dependency would be enabled if I removed the `--disable-extensions` argument but I want only the dependency extension to be enabled and no other extensions to be enabled.
If there is a command-line argument to enable just 1 extension please tell me.

**Comment by sandy081** [comment]
Please use profiles for this scenario - https://code.visualstudio.com/updates/v1_72#_extension-debugging-in-a-clean-environment
