### ISSUE TITLE
VS code doesnot display some UTF-8 characters

### ISSUE THREAD

**Issue by minfuk** [Microsoft/vscode#1719]
I use VS code for Windows, version 0.10.6.
VS code does not display some UTF-8 characters like '⦃' and '⟪'.
(Notepad and editor of VS 2015 Community can display that characters.)

**Comment by bpasero** [comment]
Might depend on the font being used.

**Comment by minfuk** [comment]
I use Consolas.

**Comment by alexandrudima** [comment]
Chromium handles font symbol selection

**Comment by minfuk** [comment]
At version 1.1.0, this problem has fixed.
