### ISSUE TITLE
Test suggest selection mode

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#171988]
Refs: https://github.com/microsoft/vscode/issues/139825

- [x] anyOS @paulacamargo25
- [x] anyOS @sandy081

Complexity: 3

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23171988%0A%0A&assignees=jrieken)

---

There is a new setting that controls if the suggestion widget is active when suggest is triggered automatically. Test that

* the `editor.suggest.selectionMode` exists and that it's properly documented
* select behaviour works for all auto-suggest, trigger character suggest (`console.|`), and quick suggest (use `editor.quickSuggestions` defaults)
* with `never` suggestions show but pressing `Enter` or `Tab` doesn't accept a suggestion
* with `never` suggestions become active when pressing `Ctrl+Space`

**Comment by ArturoDent** [comment]
@jrieken Note the odd description for the `never` option:

```
Never activate the suggest when when triggering Intellisense automatically
```

Version: 1.75.0-insider (user setup)
Commit: f1b09237cd400d92987cf7a9681995e8011ef54c
Date: 2023-01-23T11:53:59.088Z
Electron: 19.1.9
Chromium: 102.0.5005.194
Node.js: 16.14.2
V8: 10.2.154.23-electron.0
OS: Windows_NT x64 10.0.25281
Sandboxed: Yes
