### ISSUE TITLE
extension  wants API proposal 'telemetryLogger' but that proposal DOES NOT EXIST

### ISSUE THREAD

**Issue by sarodz** [microsoft/vscode#171996]
Type: <b>Bug</b>

Open VSCode
Check Developer: Toggle Developer Tools

VS Code version: Code - Insiders 1.75.0-insider (f1b09237cd400d92987cf7a9681995e8011ef54c, 2023-01-23T11:53:59.088Z)
OS version: Windows_NT x64 10.0.19044
Modes:
Sandboxed: Yes
Remote OS version: Linux x64 5.15.0-1031-azure

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.72GB (7.57GB free)|
|Process Argv|--crash-reporter-id 857fed38-4fa8-49ff-b2f3-bbf104e17732|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: devlab.linepulse.ca|
|OS|Linux x64 5.15.0-1031-azure|
|CPUs|Intel(R) Xeon(R) Platinum 8272CL CPU @ 2.60GHz (2 x 2593)|
|Memory (System)|7.76GB (6.11GB free)|
|VM|0%|
</details><details><summary>Extensions (22)</summary>

Extension|Author (truncated)|Version
---|---|---
jupyter-keymap|ms-|1.0.0
remote-containers|ms-|0.271.0
remote-ssh|ms-|0.94.0
remote-ssh-edit|ms-|0.84.0
remote-wsl|ms-|0.72.0
vscode-remote-extensionpack|ms-|0.23.0
remote-explorer|ms-|0.0.3
vscode-eslint|dba|2.3.0
gitlens|eam|13.2.0
vscode-pull-request-github|Git|0.57.2023012309
kite|kit|0.147.0
vscode-docker|ms-|1.23.3
isort|ms-|2022.8.0
python|ms-|2022.20.2
vscode-pylance|ms-|2023.1.30
jupyter|ms-|2022.11.1003412109
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.14
vscode-jupyter-cell-tags|ms-|0.1.6
vscode-jupyter-slideshow|ms-|0.1.5
makefile-tools|ms-|0.6.0
vsliveshare|ms-|1.0.5808

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30422396
pythontb:30258533
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscod805:30301674
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30404738
cppdebug:30492333
vsclangdf:30492506
c4g48928:30535728
dsvsc012:30540252
pynewext54:30618038
pylantcb52:30590116
pyindex848:30611229
nodejswelcome1:30587009
pyind779:30611226
vscrp:30624060
pythonsymbol12:30622696
2i9eh265:30646982

```

</details>

**Comment by sarodz** [comment]
Logs from Console when using 'Developer: Toggle Developer Tools'

```
 INFO Electron sandbox mode is enabled!
log.ts:398  WARN Via 'product.json#extensionEnabledApiProposals' extension 'ms-python.python' wants API proposal 'telemetryLogger' but that proposal DOES NOT EXIST. Likely, the proposal has been finalized (check 'vscode.d.ts') or was abandoned.
log.ts:398  WARN Via 'product.json#extensionEnabledApiProposals' extension 'ms-vscode.azure-repos' wants API proposal 'telemetryLogger' but that proposal DOES NOT EXIST. Likely, the proposal has been finalized (check 'vscode.d.ts') or was abandoned.
log.ts:398  WARN Via 'product.json#extensionEnabledApiProposals' extension 'ms-vscode.remote-repositories' wants API proposal 'telemetryLogger' but that proposal DOES NOT EXIST. Likely, the proposal has been finalized (check 'vscode.d.ts') or was abandoned.
log.ts:398  WARN Via 'product.json#extensionEnabledApiProposals' extension 'github.vscode-pull-request-github' wants API proposal 'commentsResolvedState' but that proposal DOES NOT EXIST. Likely, the proposal has been finalized (check 'vscode.d.ts') or was abandoned.
log.ts:398  WARN Via 'product.json#extensionEnabledApiProposals' extension 'github.remotehub' wants API proposal 'telemetryLogger' but that proposal DOES NOT EXIST. Likely, the proposal has been finalized (check 'vscode.d.ts') or was abandoned.
log.ts:398  WARN Skipping extension /c:/Users/Sami/.vscode-insiders/extensions/ms-vscode-remote.remote-wsl-recommender-0.0.18 in favour of the builtin extension /c:/Program Files/Microsoft VS Code Insiders/resources/app/extensions/ms-vscode-remote.remote-wsl-recommender.
log.ts:398  WARN Skipping extension /c:/Users/Sami/.vscode-insiders/extensions/ms-vscode.js-debug-1.74.0 in favour of the builtin extension /c:/Program Files/Microsoft VS Code Insiders/resources/app/extensions/ms-vscode.js-debug.
log.ts:404   ERR Extension 'vscode.git' wants API proposal 'telemetryLogger' but that proposal DOES NOT EXIST. Likely, the proposal has been finalized (check 'vscode.d.ts') or was abandoned.
log.ts:404   ERR Extension 'vscode.github-authentication' wants API proposal 'telemetryLogger' but that proposal DOES NOT EXIST. Likely, the proposal has been finalized (check 'vscode.d.ts') or was abandoned.
log.ts:404   ERR Extension 'vscode.html-language-features' wants API proposal 'telemetryLogger' but that proposal DOES NOT EXIST. Likely, the proposal has been finalized (check 'vscode.d.ts') or was abandoned.
log.ts:404   ERR Extension 'vscode.json-language-features' wants API proposal 'telemetryLogger' but that proposal DOES NOT EXIST. Likely, the proposal has been finalized (check 'vscode.d.ts') or was abandoned.
log.ts:404   ERR Extension 'vscode.markdown-language-features' wants API proposal 'telemetryLogger' but that proposal DOES NOT EXIST. Likely, the proposal has been finalized (check 'vscode.d.ts') or was abandoned.
log.ts:404   ERR Extension 'vscode.media-preview' wants API proposal 'telemetryLogger' but that proposal DOES NOT EXIST. Likely, the proposal has been finalized (check 'vscode.d.ts') or was abandoned.
log.ts:404   ERR Extension 'vscode.merge-conflict' wants API proposal 'telemetryLogger' but that proposal DOES NOT EXIST. Likely, the proposal has been finalized (check 'vscode.d.ts') or was abandoned.
log.ts:404   ERR Extension 'vscode.microsoft-authentication' wants API proposal 'telemetryLogger' but that proposal DOES NOT EXIST. Likely, the proposal has been finalized (check 'vscode.d.ts') or was abandoned.
log.ts:404   ERR Extension 'vscode.simple-browser' wants API proposal 'telemetryLogger' but that proposal DOES NOT EXIST. Likely, the proposal has been finalized (check 'vscode.d.ts') or was abandoned.
log.ts:404   ERR Extension 'vscode.typescript-language-features' wants API proposal 'telemetryLogger' but that proposal DOES NOT EXIST. Likely, the proposal has been finalized (check 'vscode.d.ts') or was abandoned.
```

**Comment by gjsjohnmurray** [comment]
I think this proposal has been finalized in the latest Insiders build, in preparation for 1.75 release. Endgame for that has started today.

Going forward these extensions should get updated so they no longer ask for this proposed API.

Are the messages causing any problems?

**Comment by sarodz** [comment]
It is causing other extensions to fail, for example the Python extension cannot start

**Comment by lramos15** [comment]
While these error messages are annoying and they will be fixed for tomorrow's insiders release these extensions should still work and activate properly. Are you not seeing that?

**Comment by sarodz** [comment]
It gets stuck at the Python extension loading view. I will manage for a day :)
![image](https://user-images.githubusercontent.com/10802916/214088498-c936336f-8935-4b67-bea8-8b4f92cac6a8.png)

**Comment by Kurzdor** [comment]
The actual solution is to install pre-release version of Python extensions installed in bundle.
Volia, it's working for me without hanging the extension load.
