### ISSUE TITLE
Selecting notification greys out icon

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#171959]
Click on an error:

<img width="595" alt="image" src="https://user-images.githubusercontent.com/900690/213995095-1a8ef748-84af-4558-ad0c-d8d8cf2bd8df.png">

**Comment by aeschli** [comment]
What I see when running from sources:
![image](https://user-images.githubusercontent.com/6461412/214063248-1222d87d-61b2-433d-9471-ff1052cbfc84.png)

**Comment by bpasero** [comment]
@aeschli in insiders. try with "Notification Tester" extension.

**Comment by aeschli** [comment]
The problem is that the css rule that adds the icon color looses against the color from the list. 

![image](https://user-images.githubusercontent.com/6461412/214160371-aef1e7f7-70fd-48dc-b28f-cc02e6a037aa.png)

**Comment by aeschli** [comment]
Fix in

https://github.com/microsoft/vscode/blob/aeschli/updateservers/src/vs/workbench/browser/parts/notifications/media/notificationsToasts.css#L54
```
.monaco-workbench > .notifications-toasts .codicon.codicon-error {
	color: var(--vscode-notificationsErrorIcon-foreground) !important;
}

.monaco-workbench > .notifications-toasts .codicon.codicon-warning {
	color: var(--vscode-notificationsWarningIcon-foreground) !important;
}

.monaco-workbench > .notifications-toasts .codicon.codicon-info {
	color: var(--vscode-notificationsInfoIcon-foreground) !important;
}
```
