### ISSUE TITLE
eslint not following plugin rule changes that override extend

### ISSUE THREAD

**Issue by truckingsim** [Microsoft/vscode#17197]
- VSCode Version: 1.8.0
- OS Version: Ubuntu 16.04

This problem looks like it would be eslint but when running eslint from the command line it doesn't return any errors but eslint in vscode does.  I think the 1.8.0 update broke how it handles override rules from extend.

Steps to Reproduce:

1.  Create a `.eslintrc.js` file with the following code: 

```js
module.exports = {
    "env": {
        "browser": true
    },
    "extends": "airbnb",
    "plugins": [
        "react",
        "jsx-a11y",
        "import"
    ],
    "parser": "babel-eslint",
    "rules": {
        "indent": ["error", 4, {
            SwitchCase: 1
        }],
        "arrow-body-style": ["off"],

        "no-underscore-dangle": ["error", { allowAfterThis: true, allow: ["_source"]}],
        "no-empty": ["error", { "allowEmptyCatch": true }],
        "no-plusplus": ["error", { "allowForLoopAfterthoughts": true }],
        "no-unused-expressions": ["error", { "allowShortCircuit": true }],
        "import/no-named-as-default": ["off"],
        "import/prefer-default-export": ["off"],
    },
};
```

Which requires the follow from your package.json

```js
{
   // .... name and stuff
  devDependencies: {
    "babel-eslint": "^7.1.1",
    "eslint": "^3.11.1",
    "eslint-config-airbnb": "^13.0.0",
    "eslint-plugin-import": "2.1.0",
    "eslint-plugin-jsx-a11y": "2.2.3",
    "eslint-plugin-react": "6.6.0",
  }
}
```

2. Then run eslint over the following code:

```js

// constants/users.js
export const LOGIN_USER = 'LOGIN_USER';

// actions/users.js
import UserConstants from '../constants/users';

export const SuccessfulUserLogin = (response) => {
    return {
        type: UserConstants.LOGIN_USER,
        response,
    };
};
```

You will see that it's listening to the rules that come with eslint (not plugins) but the import plugin rules it's throwing an error on line 5 of `actions/users.js` on `UserConstants` variable: 

```
severity: 'Error'
message: 'Caution: `UserConstants` also has a named export `LOGIN_USER`. Check if you meant to write `import {LOGIN_USER} from '../constants/users'` instead. (import/no-named-as-default-member)'
at: '5,15'
source: 'eslint'
```

If you were to run `./node_modules/.bin/eslint actions/users.js` you would not get that error but you do get it in vscode.

Let me know if there's any more information I can provide for you, I'm loving vscode.

**Comment by dbaeumer** [comment]
@truckingsim would you be able to share your workspace. Makes it easier to reproduce. And which version of the eslint extension are you using. The extension is not bundle with VS Code so the update of VS Code to 1.8 didn't change the version of the eslint extension.

**Comment by truckingsim** [comment]
@dbaeumer closing this.

If you look at:

```js
// constants/users.js
export const LOGIN_USER = 'LOGIN_USER';

// actions/users.js
import UserConstants from '../constants/users';

export const SuccessfulUserLogin = (response) => {
    return {
        type: UserConstants.LOGIN_USER,
        response,
    };
};
```

You can see I was trying to import from a file that doesn't have a default export and that's why the error is happening.  There was no rule change in the eslint for that specific rule `import/no-named-as-default-member` so its working as intended actually.
