### ISSUE TITLE
"next marker" goes to the first error, not the next error after the cursor

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#17191]
Have this code:

```javascript
let x = /foo

// comment

let y = /bar
```

- Place the cursor on the comment
- Press F8 for `editor.action.marker.next`

1.7: The error on `/bar` is highlighted (correct)
1.8: The error on `/foo` is highlighted

If you press F8 again, then it highlights the second error. But the first time you press it, it should always go to the next error after the cursor, not the first one.

**Comment by plievone** [comment]
It is common to have some import related problems at the top of the file during development, and now F8 always jumps to the top of the file when fixing problems down below. I guess this regression is a major one for many, I personally suffer this all the time as I find I'm memorizing how many times F8 needs to be pressed to arrive at the location at hand.
