### ISSUE TITLE
Support native tabs on macOS

### ISSUE THREAD

**Issue by aronasorman** [Microsoft/vscode#17199]
- VSCode Version: 1.8.0
- OS Version: macOS 10.12.1

Steps to Reproduce:

1. Maximize the current VSCode window (fullscreen)
2. Press Cmd+Shift+N

1.7's behaviour is to spawn the window in a new "application tab" (aka as described in Apple's "merge windows" feature [here](https://support.apple.com/kb/PH25079?locale=en_US&viewlocale=en_US))

New behaviour: It just spawns a totally separate window, on another desktop.

The old behaviour was really useful in being able to juggle a lot of projects at once. It would be really awesome if it went back to that! I tried reverting `window.titleBarStyle` to `native` and then restarting, but no dice.

**Comment by PotterDai** [comment]
Same problem here. Really need this function back.

**Comment by bpasero** [comment]
This change came through upstream and is tracked at https://github.com/electron/electron/issues/6124

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/15478
