### ISSUE TITLE
Failure to release new versions

### ISSUE THREAD

**Issue by selfrefactor** [microsoft/vscode#171913]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: stable(latest)
- OS Version: Manjaro(latest)

Steps to Reproduce:
Hard to reproduce as it happens on some of my themes and on others it works well.

1. Release new version
2. Wait for new version to be available
3. Keep waiting as nothing happens

---

I have troubles last few days to make new release of Niketa light and Niketa dark theme. I don't have this trouble if I make release in other themes.

So this is my output with which I make release, but there I cannot see the new version available even after few hours:

```
$ vsce publish patch
v2.80.2
 INFO  Publishing 'selfrefactor.niketa-dark-theme vpatch'...
 INFO  Extension URL (might take a few minutes): https://marketplace.visualstudio.com/items?itemName=selfrefactor.niketa-dark-theme
 INFO  Hub URL: https://marketplace.visualstudio.com/manage/publishers/selfrefactor/extensions/niketa-dark-theme/hub
 DONE  Published selfrefactor.niketa-dark-theme vpatch.
```

These are the two themes I am talking about:

    https://marketplace.visualstudio.com/items?itemName=selfrefactor.niketa-dark-theme
    https://marketplace.visualstudio.com/items?itemName=selfrefactor.Niketa-theme

**Comment by connor4312** [comment]
Please check out https://marketplace.visualstudio.com/manage and check for any errors that the marketplace may have flagged during publishing

**Comment by selfrefactor** [comment]
I am closing the issue as indeed there was error in the dashboard link, that you suggested. Thank you @connor4312 !
