### ISSUE TITLE
Directory does not appear in Explorer if a symlink of the same name exists, on case-sensitive APFS filesystem

### ISSUE THREAD

**Issue by Hugo-Ros** [microsoft/vscode#171980]
Type: <b>Bug</b>

If there is a directory named `foo` and a symbolic link named `FOO` (or any variation of lower/uppercase) in the same folder, VSCode will only show the symlink in the Explorer view.

Steps to reproduce:
Open an empty folder in VSCode. In a terminal run the following commands:
```
$ mkdir foo
$ ln -s random FOO
```
The folder now has the following contents
```
$ ls -l
total 0
lrwxr-xr-x  1 user  admin   6 Jan 23 14:40 FOO -> random
drwxr-xr-x  2 user  admin  64 Jan 23 14:40 foo
```

**Expected**:
Both the directory `foo` and the symlink `FOO` appear in the Explorer tab.

**Actual**:
In Explorer tab, only the symlink `FOO` is displayed.

This was observed on MacOS Big Sur 11.7.2, on a volume formatted with APFS case-sensitive filesystem. On a case-insensitive APFS it would not be possible to create the symlink and directory with the same name in the first place.

> Can you recreate the issue even after [disabling all extensions](https://code.visualstudio.com/docs/editor/extension-gallery#_disable-an-extension)?

Yes

VS Code version: Code 1.74.3 (97dec172d3256f8ca4bfb2143f3f76b503ca0534, 2023-01-09T17:07:18.579Z)
OS version: Darwin x64 20.6.0
Modes:
Sandboxed: No

<details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
gitlens|eam|13.2.0
isort|ms-|2022.8.0
python|ms-|2022.20.2
vscode-pylance|ms-|2023.1.30
cmake-tools|ms-|1.13.40
cpptools|ms-|1.13.9
cpptools-extension-pack|ms-|1.3.0
rust|rus|0.7.9
cmake|twx|0.0.17

(1 theme extensions excluded)

</details>

**Comment by lramos15** [comment]
Filing under the umbrella of https://github.com/microsoft/vscode/issues/94307
