### ISSUE TITLE
1.8 update reduces tab bar element visibility in light theme

### ISSUE THREAD

**Issue by josh-tepper** [Microsoft/vscode#17196]
- VSCode Version: Code 1.8.0 (38746938a4ab94f2f57d9e1309c51fd6fb37553d, 2016-12-13T17:38:28.425Z)
- OS Version: Darwin x64 15.6.0

See screenshot and the notes that follow.  Using the light+ theme (the default light theme), there is a lot more eye strain compared to the previous version.

![screen shot 2016-12-14 at 4 30 35 pm](https://cloud.githubusercontent.com/assets/20231989/21201993/0111727e-c21b-11e6-8856-5fc8002a4365.png)

The updated rendering has two (possibly three) differences that negatively affect visibility:
(1) Previously there were dark, single pixel lines dividing each tab.  Now there are light, single pixel lines dividing each tab.  I can only see them with strain.
(2) There used to be a dark, single pixel line at the bottom of the tab bar dividing it from the editor, in addition to a subtle drop shadow.  Now the drop shadow is the only visible division.  The shadow-only division makes the line between the non-active (gray) tabs and the editor contents just look like a blur.  I find my eyes straining significantly.
(3) I'm not sure, but it feels like the rendering of the text in the tab bar might be a little blurrier; however this likely not the case--it might just be the eye strain/blur from (1), (2) that gives this impression.

By my eye, it seems that the dark themes might have improved (not sure; don't use them typically).  Nonetheless, the light theme seems to have regressed enough to steer me (reluctantly) towards the dark themes.

If anyone has a 1.7 light+ screenshot handy, please post for comparison.

**Comment by josh-tepper** [comment]
> what I perceive to be three negative consequences:

**Comment by stevencl** [comment]
Thanks, we'll work on some refinements to this.

@bgashler1 - we should consider our options. For example, different colours for selected tabs, non selected tabs and background, reintroduce borders/lines for light theme etc.

**Comment by bgashler1** [comment]
Thanks for your feedback.  We will take a look at this.

**Comment by josh-tepper** [comment]
Just wanted to follow up.  Is this still an issue that you're working on?

**Comment by stevencl** [comment]
Sorry for the slow response, we had a change of priorities over the last few weeks and haven't been able to spend time on this. Really sorry about this.

**Comment by josh-tepper** [comment]
No worries.  Thank you for the update

**Comment by bpasero** [comment]
With our theming work all of this is now configurable either as user setting or theme:

![image](https://cloud.githubusercontent.com/assets/900690/26483791/1fcf489a-41ef-11e7-8b52-2e6047f43aec.png)

![image](https://cloud.githubusercontent.com/assets/900690/26483793/238ab73a-41ef-11e7-8af8-f5d49ad738aa.png)
