### ISSUE TITLE
[Accessibility] Ctrl+Shift+O does not close Open Detected Link view

### ISSUE THREAD

**Issue by jooyoungseo** [microsoft/vscode#171916]
CC @meganrogge and @isidorn

## Reproducible Steps

1. Enable accessibility mode.

1. go to terminal input area.

1. Press Ctrl+Shift+O to open detected links.

1. Again, press Ctrl+Shift+O to see if this key closes the view.

## Expected Behavior

Pressing Ctrl+Shift+O inside Open Detected Link needs to close the view instead of triggering opening symbol list.

## System Info

Version: 1.75.0-insider (system setup)
Commit: 9ccc2b3b30c122afe45bc6722bef0e3901fb2806
Date: 2023-01-20T05:23:24.298Z
Electron: 19.1.9
Chromium: 102.0.5005.194
Node.js: 16.14.2
V8: 10.2.154.23-electron.0
OS: Windows_NT x64 10.0.22621
Sandboxed: Yes

**Comment by meganrogge** [comment]
I would expect `Escape` to close this view and it does. Which command gives you this expectation @jooyoungseo ?

**Comment by jooyoungseo** [comment]
@meganrogge  -- You are correct. ESC is the first go-to. However, users may expect pressing the same key would close the view. For example, Ctrl+Shift+M toggles `workbench.actions.view.problems` and Ctrl+Shift+. toggles `breadcrumbs.focusAndSelect`.

**Comment by meganrogge** [comment]
`Open Detected Link` is a quick pick and the standard way to close those is via Escape. The reason for this is quickpicks are popup menus rather than anchored, stationary views like the terminal, problems view, or breadcrumbs. I'll let @Tyriar decide here

**Comment by Tyriar** [comment]
This is a quick pick like go to file, command palette, etc. all of which don't toggle. I think it's actually an intentional design decision so you can switch between modes in the quick pick without closing it (eg. go to symbol followed by command palette switches the `@` prefix to `>`.
