### ISSUE TITLE
If settings search string contains a space, it should be more strict

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#17194]
![image](https://cloud.githubusercontent.com/assets/2193314/21200547/7d8d315e-c1fc-11e6-9718-2e14dbaf06cd.png)

Since the search term is `terminal ar`, I'm explicitly indicating that they are different words so it should not return results matching `/a.+r/`.

**Comment by sandy081** [comment]
Fixed while improving Search for settings
