### ISSUE TITLE
Column selection mode

### ISSUE THREAD

**Issue by Nerexis** [microsoft/vscode#171910]
Type: <b>Feature Request</b>

Please bring back the previous hybrid mode of selection related to column mode selection.

VS Code version: Code 1.74.3 (97dec172d3256f8ca4bfb2143f3f76b503ca0534, 2023-01-09T16:59:02.252Z)
OS version: Windows_NT x64 10.0.22000
Modes:
Sandboxed: No

**Comment by ArturoDent** [comment]
"hybrid mode"?  What was that?

**Comment by Nerexis** [comment]
It was a problem with my keyboard input to VSCode not working properly not to VSCode. Closing.
