### ISSUE TITLE
C# / Unity - Typing "override" does not offer any suggestion based on base class.

### ISSUE THREAD

**Issue by AlexandreFiset** [Microsoft/vscode#17190]
- VSCode Version:1.7.2
- OS Version: Windows 10

Typing "override" does not offer any suggestion based on base class. 

Steps to Reproduce:

1. Install C# extension.
2. Create a class.
3. Create a protected or public virtual, or abstract, method.
4. Create a derived class.
5. Type "override".
6. Notice there is no suggestion based on the base class.

**Comment by kieferrm** [comment]
@AlexandreFiset pls file against https://github.com/OmniSharp/omnisharp-vscode/issues. Thanks!
