### ISSUE TITLE
Markdown Preview Code Block's Text with Bad Contrast

### ISSUE THREAD

**Issue by huacat1017** [microsoft/vscode#171963]
Type: <b>Bug</b>
Does this issue occur when all extensions are disabled?: Yes (without Shiki)
<img width="730" alt="螢幕擷取畫面 2023-01-23 120506" src="https://user-images.githubusercontent.com/57604590/213964134-ad60e8f9-6b02-4502-90c6-94e040eea1b9.png"></img>
The gray text in the picture above has a low contrast with light themes. The element might be .hljs-subst in [highlight.css](https://github.com/microsoft/vscode/blob/main/extensions/markdown-language-features/media/highlight.css)
<img width="161" alt="螢幕擷取畫面 2023-01-23 135205" src="https://user-images.githubusercontent.com/57604590/213974248-c70d68fb-b769-40d9-847b-67b9f80771fd.png"></img>   
The problem is worse in my theme because code blocks are also gray.  
  
Steps to Reproduce:
1.  Create a new Markdown file, then copy these:  
(the code may be not legal, I just simplified it which is from my extension's issue to make it easier to read.)
`````
```bash
echo "deb [arg=$(TabcoDe)]"
```
`````

2. Open the Preview of the file
3. The text is hard to see  
  

See the issue huacat1017/huacat.pink-theme#2

VS Code version: Code 1.74.3 (97dec172d3256f8ca4bfb2143f3f76b503ca0534, 2023-01-09T16:59:02.252Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|7.88GB (2.30GB free)|
|Process Argv|--crash-reporter-id 1984ce79-8f1f-47b0-88ab-e865d36f3187|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (43)</summary>

Extension|Author (truncated)|Version
---|---|---
language-x86-64-assembly|13x|3.0.0
easy-cpp-projects|ACh|2.0.0
fenix|ACh|1.1.5
project-manager|ale|12.7.0
doxdocgen|csc|1.4.0
jquerysnippets|don|0.0.1
vsc-material-theme|Equ|33.6.0
vsc-material-theme-icons|equ|2.5.0
better-cpp-syntax|jef|1.17.2
git-graph|mhu|1.30.0
vscode-language-pack-zh-hant|MS-|1.74.12140936
isort|ms-|2022.8.0
python|ms-|2022.20.2
vscode-pylance|ms-|2023.1.30
jupyter|ms-|2022.11.1003412109
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.14
vscode-jupyter-cell-tags|ms-|0.1.6
vscode-jupyter-slideshow|ms-|0.1.5
remote-ssh|ms-|0.94.0
remote-ssh-edit|ms-|0.84.0
remote-wsl|ms-|0.72.0
cmake-tools|ms-|1.13.40
cpptools|ms-|1.13.9
cpptools-extension-pack|ms-|1.3.0
remote-explorer|ms-|0.0.3
vetur|oct|0.36.1
material-icon-theme|PKi|4.23.1
java|red|1.14.0
swdc-vscode|sof|2.6.42
ayu|tea|1.0.5
open-in-browser|tec|2.0.0
pdf|tom|1.2.2
cmake|twx|0.0.17
windows-terminal|Tyr|0.7.0
intellicode-api-usage-examples|Vis|0.2.6
vscodeintellicode|Vis|1.2.30
vscode-java-debug|vsc|0.47.0
vscode-java-dependency|vsc|0.21.1
vscode-java-pack|vsc|0.25.7
vscode-java-test|vsc|0.37.1
vscode-maven|vsc|0.40.4
material-theme|zhu|3.15.6

(7 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscorecescf:30445987
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
azure-dev_surveyonecf:30548226
vsccc:30610678
pyindex848cf:30577861
nodejswelcome1:30587005
2e4cg342:30602488
89544117:30613380
vscup:30628656

```

</details>

**Comment by mjbvz** [comment]
Closing this in favor of #91279, which I believe would fix this
