### ISSUE TITLE
terminal

### ISSUE THREAD

**Issue by mateobordi1** [microsoft/vscode#171915]
ADD ISSUE DESCRIPTION HERE
mi terminal is workimg bad y see leeters on y am writing 
Version: 1.74.3
Commit: 97dec172d3256f8ca4bfb2143f3f76b503ca0534
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36
Embedder: codespaces

**Comment by HackerDaGreat57** [comment]
Imagine trying to troll ppl on GitHub?!
