### ISSUE TITLE
gutter indicator does not work when openning remote repo with soft link in its path

### ISSUE THREAD

**Issue by Co1lin** [microsoft/vscode#171975]
Does this issue occur when all extensions are disabled?: Yes/No

VS Code & OS Version:

```python
Version: 1.74.3 (Universal)
Commit: 97dec172d3256f8ca4bfb2143f3f76b503ca0534
Date: 2023-01-09T17:07:18.579Z (1 wk ago)
Electron: 19.1.8
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Darwin x64 21.4.0
Sandboxed: No
```

Steps to Reproduce:

1. Open a (SSH) remote git folder with a soft link in its path, e.g., `/home/user/softlink_to_somewhere/proj_repo`.
2. Change a file managed by git in the editor. The gutter indicator showing the difference will not appear as normal.

Related documentation: https://code.visualstudio.com/docs/sourcecontrol/overview#_gutter-indicators

When opening the folder with its original path (without any soft link), it works fine, as the figure below shows.

![normal diff decoration](https://user-images.githubusercontent.com/17642707/214033104-bfdaf576-7b7f-43a1-95e7-ffaa92ae01a0.png)

**Comment by lszomoru** [comment]
At the moment it is known that there are various scenarios that are not working as expected when a repository has a symbolic link on its path. The work to add support for symbolic links is currently tracked here - https://github.com/microsoft/vscode/issues/5970. I will go ahead and close this issue as duplicate, and I would suggest that you subscribe to the linked issue to receive updates when the work is being scheduled. Thank you!
