### ISSUE TITLE
vscode double click not creating new folder

### ISSUE THREAD

**Issue by Mohammadev82** [microsoft/vscode#171948]
# before:
![Screenshot 2023-01-23 002709](https://user-images.githubusercontent.com/105316207/213940082-319136e8-aa3b-4518-b429-f5baae2af464.png)
# after:
![Screenshot 2023-01-23 003056](https://user-images.githubusercontent.com/105316207/213940222-12d0e9da-922a-436b-bceb-a7ba18a4cde1.png)

**Comment by ArturoDent** [comment]
Can you explain the steps you are using to create a new folder more clearly.

**Comment by Mohammadev82** [comment]
yes
1.double left click on explorer space 
2.type folder name + /
3. enter

**Comment by Mohammadev82** [comment]
This should create folders, not files

**Comment by lramos15** [comment]
\duplicate https://github.com/microsoft/vscode/issues/173902
