### ISSUE TITLE
Mac: Auto-update prevents to store settings of session

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#172]
Whenever I install an update (prompted by VS Code) it doesn't open the same file I had opened before.

I think this is caused by a prompt process.exit() that leaves VS Code (or actually Chromium) no chance to persist the local storage to disk. It is reproducible by calling Lifecycle.quit() and from the done handler call process.exit().

Have to follow up with Electron to understand this better.

**Comment by joaomoreno** [comment]
:+1:

**Comment by bpasero** [comment]
Might be fixed with Electron update.

**Comment by bpasero** [comment]
Nope...

**Comment by weinand** [comment]
@bpasero since this is the most annoying problem with VSCode, I have to label this bug as "Important"...

**Comment by bpasero** [comment]
@weinand thats fine, but note that there is nothing we can do until we update to Electron 0.36.x.
