### ISSUE TITLE
Tunnel service is slow/sometimes doesn't work at all (times out)

### ISSUE THREAD

**Issue by HackerDaGreat57** [microsoft/vscode#172088]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.74.3
- OS Version: Ubuntu 22.04 LTS arm64 (raspberry pi 4 8gb) everything fully updated via `sudo apt update && sudo apt upgrade`

Steps to Reproduce:
1. Create a tunnel with `code tunnel --accept-server-license-terms`
2. When connecting to the tunnel, it may take several (10+) seconds to connect or it may time out.

Due to some technical problems I couldn't get the plaintext, but here are screenshots of the server logs. I couldn't connect to the the server a few times when I tried on the 22nd, but it eventually worked when I reloaded the page a few times. Then it completely failed on the 23rd and I couldn't connect even once. All logs after "Opened client on channel 24" may be of use because after it tried to open channel 24 I couldn't connect even once before restarting the server. (`start.sh` is `code tunnel --accept-server-license-terms`)
![Screenshot from 2023-01-23 15-49-11](https://user-images.githubusercontent.com/70416002/214178142-4a673a44-83d2-4648-b30d-230cb3f5a9ce.png)
![Screenshot from 2023-01-23 15-49-22](https://user-images.githubusercontent.com/70416002/214178165-ff390430-8ab0-4fdd-83c0-d15fc0e7f5f6.png)

**Comment by connor4312** [comment]
Can you please run with `--verbose` so I can see more of what's happening?

**Comment by HackerDaGreat57** [comment]
Will do when I'm home. I'll also use `tee` so that log browsing will be made easier for you.

**Comment by HackerDaGreat57** [comment]
The issue is no longer happening when I changed my Ethernet cable; it seems it was a problem unrelated to vscode. Will reopen if this happens again.
