### ISSUE TITLE
Test: `onLanguage` activation event

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode#172037]
Refs: https://github.com/microsoft/vscode/issues/167866

- [x] anyOS @sandy081
- [x] anyOS @roblourens

Complexity: 2

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23172037%0A%0A&assignees=joyceerhl)

---

To test:
- Use the `onLanguage` activation event in an extension and verify that it behaves as expected
- Verify that the Emmet extension only activates on any language and not after startup

**Comment by sandy081** [comment]
For confirmation, you can open extension editor of an extension and go to Runtime Status tab to see on which event an extension is activated

![image](https://user-images.githubusercontent.com/10746682/214339231-ea23178c-6ba0-4b1f-9bf8-2e59ba865dc2.png)
