### ISSUE TITLE
Test: Simplified devcontainer.json for vscode repository

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode#172017]
Refs: https://github.com/microsoft/vscode/issues/170969

- [ ] macOS @kieferrm
- [ ] linux @andreamah
- [x] windows @rzhao271 

Complexity: 3

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23172017%0A%0A&assignees=chrmarti)

---

NOTE: Currently blocked by https://github.com/microsoft/vscode/issues/168655. Please hold off testing until we have fixed that.

Follow https://github.com/microsoft/vscode/blob/main/.devcontainer/README.md to develop VS Code in a dev container.

**Comment by chrmarti** [comment]
Moving to next milestone as we don't have the required fix to test this yet.

**Comment by hediet** [comment]
I chose the "Code - OSS" devcontainer (without WSL) and got a bunch of issues:

"Configuring..." got stuck (or takes more than 10 minutes):
![image](https://user-images.githubusercontent.com/2931520/220359822-716a0a85-49c6-4904-ac67-27e17c35a8a8.png)

"yarn install --force" crashed (after updating docker & wsl it worked though):
![image](https://user-images.githubusercontent.com/2931520/220362069-2da94310-db12-4e98-8c05-f8c87b7c6eba.png)

`yarn watch` failed:
![image](https://user-images.githubusercontent.com/2931520/220370968-75398c88-3567-428c-88e7-539a0a8fef6e.png)

Then I tried to clone vscode in WSL and this time chose "VS Code" devcontainer.

This time, a window opened, but it also crashed:

![image](https://user-images.githubusercontent.com/2931520/220385767-58eb221f-fe2d-4714-ad88-4b70924193a3.png)

**Comment by andreamah** [comment]
> NOTE: Currently blocked by https://github.com/microsoft/vscode/issues/168655. Please hold off testing until we have fixed that.

Does this still apply? I noticed that this might be an old message that was posted before the TPI was assigned for this round of testing.

**Comment by hediet** [comment]
It still applies

**Comment by rzhao271** [comment]
I chose the VS Code devcontainer and got the same loader crash as Henning.
I noticed that the icon's also unaligned:
 
![Code OSS on WSL icon seems to sink halfway into the bottom of the screen](https://user-images.githubusercontent.com/7199958/220475653-2d49f2e6-b3df-4d47-aa8f-0673d124fcb2.png)

**Comment by andreamah** [comment]
I'm a bit confused, are we supposed to be testing this item yet? I had the impression, based on the description, that this was not ready for testing yet.

**Comment by TylerLeonhardt** [comment]
Based on what I'm reading, this test plan does not seem ready yet. @chrmarti can you please advise?

**Comment by chrmarti** [comment]
Sorry, this should not have been assigned as TPI. Closing until the blocking bug is fixed.
