### ISSUE TITLE
Allow to open a file and goto line without -g option (/path/to/file.ex:123)

### ISSUE THREAD

**Issue by idyll** [Microsoft/vscode#17200]
- VSCode Version: 1.8.0
- OS Version: macOS 10.2.2

Steps to Reproduce:

1. Set VSCode to be the default editor for a file type. (for example .ex)
2. Go to the terminal.
3. Command-Click on a URI like /path/to/file.ex:123

It should open to line 123. But it doesn't.

**Comment by idyll** [comment]
This is relevant/important because my test tool spits out line numbers of failures and command clicking on the link to open to that line works in Atom/Sublime.

**Comment by Tyriar** [comment]
Note that we support this via -g but that doesn't work with links. Some more context https://twitter.com/agileanimal/status/809159932033449984

**Comment by idyll** [comment]
I suspect it's not turned on by default because some people might have `:` in a filename???

If it was a setting to just globally enable that would be awesome. :)

**Comment by ccirello** [comment]
possibly a duplicate for https://github.com/Microsoft/vscode/issues/7321

**Comment by Tyriar** [comment]
@idyll do you have example application(s) which feature such links to the file system?

**Comment by idyll** [comment]
Examples: sublime text and atom both do this.

**Comment by bpasero** [comment]
This feature request will not be considered in the next [6-12 months roadmap](https://github.com/Microsoft/vscode/wiki/Roadmap) and as such will be closed to keep the number of issues we have to maintain actionable. Thanks for understanding and happy coding!
