### ISSUE TITLE
The TypeScript language service died unexpectedly 5 times in the last 5 Minutes. Please consider to open a bug report.

### ISSUE THREAD

**Issue by chipaubry** [Microsoft/vscode#17205]
I am repeatedly getting the following warning after installing 1.8:

> The TypeScript language service died unexpectedly 5 times in the last 5 Minutes. Please consider to open a bug report.

- VSCode Version: Code 1.8.0 (38746938a4ab94f2f57d9e1309c51fd6fb37553d, 2016-12-13T17:38:28.425Z)
- OS Version: Darwin x64 15.6.0
- Extensions:

|Extension|Author|Version|
|---|---|---|
|vscode-eslint|dbaeumer|1.0.6|
|python|donjayamanne|0.3.21|
|text-transform|florianloch|0.1.0|
|Python-autopep8|himanoa|1.0.2|
|docthis|joelday|0.3.5|
|cpptools|ms-vscode|0.8.1|
|csharp|ms-vscode|1.4.1|
|autoimport|steoates|1.2.2|
|cordova-tools|vsmobile|1.2.4|

---

Steps to Reproduce:

1. Start VS Code - warning appears after several seconds.

**Comment by mjbvz** [comment]
@chipaubry Can you please share your workspace so that we can investigate? Does this happen for all projects you open or just one?

**Comment by chipaubry** [comment]
@mjbvz Unfortunately I can't share the workspace. It appears to have been an issue with OSX because after a reboot I am no longer seeing the behavior. I didn't make any changes to the workspace.

**Comment by mjbvz** [comment]
@chipaubry Ok. Closing since the issue seem to have been resolved.

Please let us know if you see this issue again so that we can investigate.

Thanks
