### ISSUE TITLE
Variable name maybe shouldn't be mandatory for OutputEvent

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#17204]
If I return multiple objects for an OutputEvent, then only the first is shown, because of this check in debugModel.ts -

`distinct(response.body.variables.filter(v => !!v), v => v.name)`

If I add some unique name, then they are all shown. @isidorn maybe since the name isn't visible, it shouldn't be checked in this case. On the other hand, it's still required on 'Variable' in the protocol, so it could be considered sort of an id. It's easy enough to give them names.

**Comment by isidorn** [comment]
It is required to give them names as we use the names as IDs in the tree, there is not other way around this now. If the name was not mandatory then we would need to generate ids for them on the vscode side. Not to overcomplicate things lets just make the name mandatory so the adapter is in charge of ids

Closing as designed
