### ISSUE TITLE
Adopt implicit activation event generation for `onTaskType`

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode#172065]
If possible we should have the `taskDefinitions` extension point implicitly generate `onTaskType:` events: https://github.com/microsoft/vscode/blob/891a9e53fcc11aebc17e103183b44242c42fb4c1/src/vs/workbench/contrib/tasks/common/taskDefinitionRegistry.ts#L84-L91

**Comment by meganrogge** [comment]
Implicit activation does not make sense, and this has caused issues for people, so I'm going to revert it.

If an extension wants to activate for a specific task type, then we support that.
