### ISSUE TITLE
Test CommentThreadState API

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#172027]
Refs: https://github.com/microsoft/vscode/issues/127473

- [x] anyOS @rzhao271
- [x] anyOS @hediet

Complexity: 5

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23172027%0A%0A&assignees=alexr00)

---

The `CommentThreadState` API has been finalized:

https://github.com/microsoft/vscode/blob/fcb503b296ef379404c851a29e71334c7804b5dd/src/vscode-dts/vscode.d.ts#L15225-L15231

https://github.com/microsoft/vscode/blob/fcb503b296ef379404c851a29e71334c7804b5dd/src/vscode-dts/vscode.d.ts#L15290-L15293

Take a look at the API and verify that the inline documentation makes sense. Then, try out the API. One easy way to try the API is to use the comments extension sample and instead of adding a "pending" label to the comment you could set the comment thread state to `Unresolved`:

https://github.com/microsoft/vscode-extension-samples/blob/8431b4978c73721adb1edb3571063bfada509e7a/comment-sample/src/extension.ts#L46-L48

Verify 
- that you can see a difference in the UI treatment of resolved/unresolved comments in the Comments view.
- that when you update the comment thread state it is reflected in the Comments view.

**Comment by DonJayamanne** [comment]
@alexr00 not sure how I'm supposed to get the latest vscode.d.ts files, 
wont i need to get the proposed API enabled to test this, which means I'm really testing the proposed API at this stage? 
I.e. i cannot really verify whether its stable or not until the npm package has been published (@types/vscode) with the latest bits.

Please could you provide instructions on how I could get the vscode.d.ts files to test this, also, should I be enabling proposed-api in the launch.json?

**Comment by rzhao271** [comment]
It seems to me that the default state of the thread is Unresolved, but can that be clarified in the API docs?

**Comment by alexr00** [comment]
@DonJayamanne I usually just copy the vscode.d.ts file over for testing finalizations. 

@rzhao271 the default state is neither unresolved no resolved so as to preserve the existing behavior for comments.

**Comment by hediet** [comment]
`npx vscode-dts main` does the trick!
