### ISSUE TITLE
Test profiles in portable mode

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#172015]
Refs: https://github.com/microsoft/vscode/issues/165447

- [x] macOS @meganrogge
- [x] linux @lramos15
- [x] windows @aeschli

Complexity: 2

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23172015%0A%0A&assignees=sandy081)

---

To Test:

- Use portable VS Code - https://code.visualstudio.com/docs/editor/portable
- Create some profiles
- Copy/Move the data folder to another location
- Point VS Code to this new location
- Make sure profiles are retained

**Comment by meftunca** [comment]
When will it be available for use? I tried it via VsCode-Insider and it works perfectly

**Comment by lramos15** [comment]
> When will it be available for use? I tried it via VsCode-Insider and it works perfectly

Should be out in the next stable release in about ~1.5 weeks

**Comment by meftunca** [comment]
> > When will it be available for use? I tried it via VsCode-Insider and it works perfectly
> 
> Should be out in the next stable release in about ~1.5 weeks

Thanks

**Comment by meganrogge** [comment]
@sandy081 how do I do this?
>Point VS Code to this new location

**Comment by aeschli** [comment]
@sandy081 How does this work?
`Point VS Code to this new location`. Is it with `--user-data-dir`?

**Comment by aeschli** [comment]
This seems to work: `"VSCode-win32-x64-1.75.0-insider4\Code - Insiders.exe" --user-data-dir=C:\Users\martinae\data\user-data --extensions-dir=C:\Users\martinae\data\extension`

**Comment by aeschli** [comment]
I was only puzzled about the sentences `Copy/Move the data folder to another location` and `Point VS Code to this new location`.

**Comment by aeschli** [comment]
How I understand it now is:
- Set up VS Code in a different folder (by extracting a zip build).
- Copy the data folder from the first build into the new folder
- Start VS code in the new folder and verify that profiles are all there and are the same

**Comment by sandy081** [comment]
> I was only puzzled about the sentences Copy/Move the data folder to another location and Point VS Code to this new location.

Ok, sorry about that. Whatever you said above comment is correct
