### ISSUE TITLE
VSCode crashes when opened from terminal

### ISSUE THREAD

**Issue by matthova** [Microsoft/vscode#17201]
- VSCode Version: 1.8
- OS Version: OSX 10.10.5

Steps to Reproduce:

0. Make sure "Code" is not open
1. Open terminal and navigate to any folder
2. Type "code ."
3. VS Code will open, then crash after ~30 seconds

Crashlog [here](https://gist.github.com/matthova/128acf50017ea55d72d7bc8524a624f4
)

**Comment by joaomoreno** [comment]
Can you try [re-downloading VS Code](https://code.visualstudio.com/)?

**Comment by matthova** [comment]
@joaomoreno I removed VSCode with App Cleaner, restarted my computer, re-downloaded VS Code. Still the same problem. I then removed my symlink to code and made a new one in ~/.bash_profile

'''
code () {
    if [[ $# = 0 ]]
    then
        open -a "Visual Studio Code"
    else
        [[ $1 = /* ]] && F="$1" || F="$PWD/${1#./}"
        open -a "Visual Studio Code" --args "$F"
    fi
}
'''
All good now

**Comment by joaomoreno** [comment]
Good to know.

But that shortcut style is no longer used, please remove it and run the `Shell Command: Install 'code' command in PATH` command from the <kbd>F1</kbd> Command Palette.

**Comment by matthova** [comment]
beautiful. Thanks for your help :)
