### ISSUE TITLE
Test profiles feature for shipping

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#172051]
Refs: https://github.com/microsoft/vscode/issues/116740

- [x] macOS @rebornix
- [x] linux @lramos15
- [x] windows @karthiknadig

Complexity: 4

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23172051%0A%0A&assignees=sandy081)

---

Use unreleased 1.75.0 stable build from our builds page for testing.

As we are planning to ship profiles to stable as GA feature, please do a smoke and bit of exploratory testing of profiles feature.  Try to use all possible functionalities of profiles feature and make sure they are working as expected. You can access all profiles functionality from global activity menu (gear). Provide any UX suggestions you come across while using the feature.

**Comment by rebornix** [comment]
I like how the import/export profile works, great work @sandy081 

I know this has been discussed in UX channel already but I still reached out to the Accounts icon each time I attempt to use profile feature. It's not natural to me to find the profile related feature under the Gear menu. Other than this, it works well.

**Comment by karthiknadig** [comment]
I ran into weird issue with user setup or when using `--user-data-dir` flags. When it did work it worked really well.

**Comment by sandy081** [comment]
> I know this has been discussed in UX channel already but I still reached out to the Accounts icon each time I attempt to use profile feature. It's not natural to me to find the profile related feature under the Gear menu. Other than this, it works well.

Yeah, thanks for the feedback. Its natural to reach to Accounts menu for profiles, but conceptually placing it there is not correct. Also we decided not to sprinkle UI just for the sake of discoverability. Hence we have cleaned up these menus. I think we are also on to cleaning up Accounts menu similarly. CC @isidorn, @aeschli
