### ISSUE TITLE
Test extension contributed keyboard shortcuts in the keyboard shortcuts editor

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#172018]
Refs: https://github.com/microsoft/vscode/issues/121673

- [x] anyOS @meganrogge
- [x] anyOS @aeschli

Complexity: 3

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23172018%0A%0A&assignees=sandy081)

---

To test:

- Install an extension that contributes keyboard shortcuts Eg: `GitHub.vscode-pull-request-github`
- Verify that you can filter keyboard shortcuts contributed by that extension using the action **Extension Keyboard Shortcuts** that is available in the gear context menu (in extension editor and in extension view). This action opens Keyboard shortcuts contributed by this extension in the Keyboard Shortcuts editor
- Verify that you can see the extension in the source column that contributed keyboard shortcuts
- Verify that clicking on the extension opens the extension editor for that extension
- In the keyboard shortcuts editor overflow menu in the title bar, there is an action to see all keyboard shortcuts contributed by extensions **Show Extension Keyboard Shortcuts**. Make sure this work as expected

**Comment by meganrogge** [comment]
cool and useful feature, so would be good to increase discoverability
