### ISSUE TITLE
Set `order` for default (debug) welcomeView content

### ISSUE THREAD

**Issue by rehmsen** [microsoft/vscode#172009]
The debug welcome view registers some default content to be shown:
https://github.com/microsoft/vscode/blob/277ffee01fdcf7fbb235ecfb40798bc3fd2fc128/src/vs/workbench/contrib/debug/browser/welcomeView.ts#L108

Most of these pieces of contents do not set an `order`, meaning they will be shown in the order they are defined. 

There is also an API to specify new pieces of content from within an extension: https://code.visualstudio.com/api/references/contribution-points#contributes.viewsWelcome

Which allows you to provide `order` by passing it in with the `group` string, separated by an `@`:
https://github.com/microsoft/vscode/blob/277ffee01fdcf7fbb235ecfb40798bc3fd2fc128/src/vs/workbench/contrib/welcomeViews/common/viewsWelcomeContribution.ts#L69-L88

We at Google would like to be able to add a new button ("Attach and Debug") below "Run and Debug", but currently we cannot because "Run and Debug" and all others do not set `order`, they are all assumed to have `order=5`, meaning we can only place a new button before all others, or after all.

I am proposing to set `order` for each registered content, allowing extensions to defined where their custom content should be placed.

Thank you for your time.

**Comment by rehmsen** [comment]
I will send a PR setting it only for the one button we need right now, as that is the smaller change that may be easier to merge.

If there is interest, it might be worthwhile to instead of defaulting to 5, defaulting to the registration order. That would then automatically ensure extensions can insert where they see fit on all welcome views, without having to remember to always pass order.

**Comment by bhavyaus** [comment]
Adding @connor4312 for input on the debug UI

**Comment by roblourens** [comment]
I think the order we added is fine, but I don't think there is a general need for other extensions to insert content at any given spot. I'm going to leave the rest without an order.
