### ISSUE TITLE
Test the Redesign of the Inline Suggestions Hover

### ISSUE THREAD

**Issue by hediet** [microsoft/vscode#172029]
Refs: https://github.com/microsoft/vscode/issues/167042

- [x] anyOS @Tyriar
- [x] anyOS @rebornix
- [x] anyOS @isidorn

Complexity: 4

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23172029%0A%0A&assignees=hediet)

---

To test:

- Make sure Copilot is installed
- Use Copilot as usual
    - Make sure accepting inline suggestions with [tab] still works
- Hover on an inline suggestion
    - Explore the hover, make sure all features work
        - Including *accept partial* and *undo accept partial*
- Configure VS Code so that the hover is always shown (ensure it is easy to find out how to do that)
    - Use copilot as usual, make sure everything still works and that the hover is shown all the time.

**Comment by isidorn** [comment]
Great job, I love the new hover ❤️
