### ISSUE TITLE
Test: Tree find history

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#172002]
Refs: https://github.com/microsoft/vscode/issues/155578

- [x] macOS @TylerLeonhardt
- [x] linux @roblourens
- [x] windows @alexr00

Complexity: 2

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23172002%0A%0A&assignees=joaomoreno)

---

Trees which support find (press <kbd>Ctrl/Cmd F</kbd>) now support history by pressing <kbd>UpArrow</kbd>/<kbd>DownArrow</kbd>.

![image](https://user-images.githubusercontent.com/22350/214077321-7de86e5b-dc2c-48d0-b638-b93fe46adc10.png)

Make sure:

- Pressing <kbd>Enter</kbd> moves the focus from the find widget to the widget and _commits_ the find input to history.
- Focusing on the find widget and pressing <kbd>UpArrow</kbd>/<kbd>DownArrow</kbd> to loop through history results works as expected. Pressing <kbd>DownArrow</kbd> when at the end of history should focus the tree.

Note: the history is gone once the workbench gets reloaded.

**Comment by TylerLeonhardt** [comment]
I also noticed that Up and Down arrow or focusing on the file tree (via clicking) ... one of those "commits" the find input to history. That makes sense to me, but I wanted to call it out since it wasn't mentioned in the TPI.
