### ISSUE TITLE
Keybinding wrongly rendered on macOS for inline completions hover

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#172143]
Testing #172029

Accept Part keybinding should not say "super", it should be rendered as it is in the native hover

![Screenshot 2023-01-24 at 12 56 06](https://user-images.githubusercontent.com/1926584/214285517-1fde950b-383e-4803-9886-9babcd3fd4c9.png)

Also the undo accept part

![Screenshot 2023-01-24 at 12 56 37](https://user-images.githubusercontent.com/1926584/214285585-fa3a9385-6848-4af1-8a9b-236a1550bac6.png)

**Comment by isidorn** [comment]
Undo accept word still renders a bad keybinding, but you know I prefer that we just axe that command 🪓

**Comment by hediet** [comment]
What do you mean with a bad keybinding?

**Comment by isidorn** [comment]
I mean this is rendered. What is that black triangle?

![Screenshot 2023-01-27 at 18 57 30](https://user-images.githubusercontent.com/1926584/215160040-0db2f824-a0a8-4d76-875a-a0d73614ac59.png)

**Comment by hediet** [comment]
> What is that black triangle?

Arrow Left. I don't participate in rendering this menu, so if you think this is a bug, please create an issue for whoever owns the context menu.

**Comment by isidorn** [comment]
@hediet ok. It might be just the native way to render arrow left. Sorry for the noise.
