### ISSUE TITLE
Proposal: use ACME chords for VSCode terminal

### ISSUE THREAD

**Issue by ccirello** [Microsoft/vscode#17214]
- VSCode Version: 1.8.0
- OS Version: macOS

Steps to Reproduce:

1. Open terminal
2. Make sure a compile produces an output similar to:
```
go build -i -v
github.com/iron-io/functions
# github.com/iron-io/functions
./main.go:63: expression in go/defer must be function call
```

In this case, instead of relying on linkify, we could use acme's mousechords (http://acme.cat-v.org/mouse)

In this case, highlight while holding right button - or some other acceptable combination - it takes the selected text and take an action, that can be, among possibilities, open the file in the goto address. Thus for the example above, it would open `./main.go:63` in `$PWD`.

**Comment by Tyriar** [comment]
Would #7321 fix your main issue?

My concern with supporting something like this is that it obviously can't be the default as it's quite obscure to many users. #7321 combined with accessible copy and paste seems to be nearly as convenient without needing to build/support an additional concept like this.

**Comment by ccirello** [comment]
> Would #7321 fix your main issue?

Yes. But it seems it is depends on a library that's not going to help to have it implemented anytime soon. Whereas this suggestion is pretty much straight forward - select and open. 

>  #7321 combined with accessible copy and paste

Except that it isn't. At least not currently. In this very example, if I just copy and paste the file's URI into the quick opener, it doesn't work. First, it takes forever to scan all files (ignoring the obvious hint of the open tabs); second, it doesn't quite know what's the relative path (missing the $PWD part).

Up to you guys - #7321 is deal-breaker for me if I wanted to use VSCode internal terminal. And the alternative (copy and pasting) is simply bad.

**Comment by Tyriar** [comment]
I would love to see #7321 happen, it's just a matter of squeezing it in with the other work I'm doing. One of my focuses this iteration is to improve terminal performance in the upstream project which involves rewriting a lot of the code that this feature would depend on, I'll keep it in mind when I look over the terminal refresh code as that's the part that needs to be hooked into.
