### ISSUE TITLE
`Show Terminal Accessibility Help` does nothing if terminal isn't open

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode#172195]
Testing #171862

When invoked from the command palette, should this either
1. create and show a terminal and show the menu
2. not be shown in the command palette unless a terminal is already open

**Comment by meganrogge** [comment]
It shouldn't be shown unless a terminal is open and focused

**Comment by Tyriar** [comment]
The first option might be better? We can just run get active or create like a bunch of other terminal commands.

**Comment by meganrogge** [comment]
My argument against doing so is the command palette is already overloaded and you have to know what to search for to get it to show up, which means it's unlikely to be discovered or increase discoverability.

**Comment by Tyriar** [comment]
@meganrogge my argument is if you search for "accessibility", the results are quite small and this is a valuable addition to discover terminal accessibilty features:

<img width="304" alt="image" src="https://user-images.githubusercontent.com/2193314/214618042-059553e4-21fc-4c96-b9bc-979f6f1e50a3.png">

Up to you, let's do this in Feb though.

**Comment by joyceerhl** [comment]
Should Show Terminal Accessibility Help be showing the dialog inside a terminal that's running a task?

![image](https://user-images.githubusercontent.com/30305945/220757878-61de3b27-c02d-448c-b22c-19f3e62e33af.png)

**Comment by meganrogge** [comment]
Good question, but yes I think we should show it in whatever the active instance is.
