### ISSUE TITLE
"Accept Part" should be called "Accept Word"

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#172145]
Testing #172029

"Part" is a term we use for UI elements.
"Word" is a better term here.
Or is there a reason I am missing for this case?

![Screenshot 2023-01-24 at 12 59 21](https://user-images.githubusercontent.com/1926584/214286104-5579224e-8a4b-4dc8-a962-26111d105923.png)

**Comment by hediet** [comment]
It also accepts non-word parts, e.g. in `if (true)` it would accept `if`, ` (`, `true`, `)`

**Comment by isidorn** [comment]
We also call "navigate word" our word navigation commands, even though they stop at non words.
I think it is expected that "word" in this context means "word separator", and that users will not be surprised by this minor imprecision.

**Comment by rebornix** [comment]
I didn't know what "Accept Part" means at all until I pressed the keyboard shortcut. "Accept Word" with how it behaves in most cases, and for the corner cases like separators, I agree with @isidorn that it's the same as other existing commands.
