### ISSUE TITLE
`onLanguage` is not marked with a squiggles

### ISSUE THREAD

**Issue by karthiknadig** [microsoft/vscode#172115]
Testing #172036

![image](https://user-images.githubusercontent.com/3840081/214237069-c2fb3809-95fa-4888-9753-23ced8453a46.png)

**Comment by lszomoru** [comment]
In am only able to reproduce this if the `package.json` file does not contain a language contribution. As soon as I add the language contribution the squiggles would appear. Not sure if this is expected behaviour.
