### ISSUE TITLE
Wording used is confusing

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#172155]
Testing #172010

In a few places including settings I see this sentence:

<img width="315" alt="image" src="https://user-images.githubusercontent.com/900690/214307213-2811b03d-0c0c-4913-b2f9-5cd73b629f15.png">

I am not a native speaker, but find that the `,` needs to be `or` and `,` should only be used when you have 3 things (as in `x, y, or z`).

**Comment by rzhao271** [comment]
Another way to word the phrase is "A git repository was found in a parent directory of the workspace or open file(s)."

**Comment by lszomoru** [comment]
@rzhao271, thanks for the suggestion.
