### ISSUE TITLE
Javascript files are not being formatted

### ISSUE THREAD

**Issue by andreshg112** [Microsoft/vscode#17213]
- VSCode Version:

Versión 1.8.0
Shell 1.4.6
Representador 53.0.2785.143
Node 6.5.0

- OS Version: Ubuntu 15.04

Steps to Reproduce:

1. Open a Javascript files (AngularJS Controller in my case).
2. Try to format in any way (on save, Ctrl + Shift + I, Second Click -> Format). This is not working on my machine.
I'm having this problem after installing version 1.8.

**Comment by chriswoodle** [comment]
I have the same HTML formatting issue. My JavaScript files are formatted though.
![screen shot 2016-12-14 at 9 19 20 pm](https://cloud.githubusercontent.com/assets/11614325/21209580/2d9c1bfa-c243-11e6-9a42-cd28b4377190.png)

Version 1.8.0 (1.8.0) 38746938a4ab94f2f57d9e1309c51fd6fb37553d
macOS 10.12.1
NodeJS v7.2.0

**Comment by aeschli** [comment]
Please always create separate issues for each bug.
The HTML issue is #17849.

**Comment by waderyan** [comment]
@andreshg112 I'm not seeing this issue. Can you share the code that isn't formatting?

**Comment by andreshg112** [comment]
Thanks!
Now I'm not having that problem.
