### ISSUE TITLE
My hyperdock can't resize the window after i upgraded to vscode 1.8.0

### ISSUE THREAD

**Issue by donnol** [Microsoft/vscode#17215]
- VSCode Version: Code 1.8.0 (38746938a4ab94f2f57d9e1309c51fd6fb37553d, 2016-12-13T17:38:28.425Z)
- OS Version: Darwin x64 16.1.0
- Extensions:

|Extension|Author|Version|
|---|---|---|
|beautify|HookyQR|0.6.2|
|vscode-todo|MattiasPernhult|0.8.0|
|emoji|Perkovec|0.0.3|
|code-settings-sync|Shan|2.3.8|
|comment-snippets|Tobiah|0.2.0|
|vscode-database|bajdzis|1.0.11|
|ftp-simple|humy2833|0.4.14|
|vscode-JS-CSS-HTML-formatter|lonefy|0.2.2|
|Go|lukehoban|0.6.51|
|vscode-fileheader|mikey|0.0.2|
|Theme-MarkdownKit|ms-vscode|0.1.1|
|vscode-icons|robertohuertasm|4.1.0|
|vim|vscodevim|0.4.9|
|Material-theme|zhuangtongfa|1.0.3|

---

Steps to Reproduce:

1. this is the [hyperdock](https://bahoom.com/hyperdock/), which can move & resize windows just by holding down keys and moving your mouse.
2. it can Automatically resize windows when dragging to screen edges before vscode 1.8.0, but now i can't do that.

**Comment by bpasero** [comment]
@donnol what is hyperdock? can you show a video of what fails?

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/18971
