### ISSUE TITLE
Allow to set a background image

### ISSUE THREAD

**Issue by PowerSnail** [Microsoft/vscode#17219]
There has been a plugin for it, but I think it has encountered various problems since VS Code 1.6. Furthermore, I think its method (modifying the CSS file it seems) is too hacky anyway. Is it possible to provide this functionality officially? Or maybe provide a better way for plugin authors, so we can get more stable background image plugins?

Thank you very much!

**Comment by chengyuhui** [comment]
Currently the only correct way to do such a thing is making a theme (maybe forking or copying one from existing sources? )

Is it possible to allow custom CSS injection for users or plugins? (like Atom)

**Comment by THCloud** [comment]
hey，friend， which plugin could allow to set background image？？？

**Comment by PowerSnail** [comment]
@THCloud https://github.com/shalldie/vscode-background

You have to run Code with Admin Privilege, so it can modify the files in VS Code's folder. And it produces an error message every time VS Code starts up because of the modification.

**Comment by cutecycle** [comment]
Running vscode as admin sounds like a good way to get attacked by an extension. perhaps there's a way to change the background css with a base 64 image instead?

**Comment by jens1o** [comment]
CSS is not supported natively by `vscode`. See https://github.com/Microsoft/vscode/issues/459

**Comment by bpasero** [comment]
This feature request will not be considered in the next [6-12 months roadmap](https://github.com/Microsoft/vscode/wiki/Roadmap) and as such will be closed to keep the number of issues we have to maintain actionable. Thanks for understanding and happy coding!
