### ISSUE TITLE
Inline suggest hover overflow hides inline suggest, losing context when undo accepted part is used

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#172188]
Testing #172029

![Recording 2023-01-24 at 07 54 10](https://user-images.githubusercontent.com/2193314/214342160-d734c9cc-f2b2-4a71-bff6-e0cbdb313528.gif)

**Comment by hediet** [comment]
Related: https://github.com/microsoft/vscode/issues/172188

**Comment by Tyriar** [comment]
@hediet you liked this issue?

**Comment by roblourens** [comment]
Wrong milestone?
