### ISSUE TITLE
Limits for remote web are different than for remote desktop

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#172136]
Testing #171743

Desktop remote has 100MB limit, browser remote has only 10MB. Isn't the limit/cost-factor how much data the server needs to send and therefore there is no difference between desktop and web? Technically desktop and web are equal in how they receive the data and therefore the limits should be equal. Or am I missing something.

**Comment by bpasero** [comment]
Will be addressed in https://github.com/microsoft/vscode/pull/172355
