### ISSUE TITLE
Problem importing profile

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode#172157]
Testing #172034

I exported a profile and imported it again. While importing I got the error:
`Error while importing profile: Unable to resolve nonexistent file '/home/martin/.vscode-insiders/extensions/ms-toolsai.jupyter-keymap-1.0.0'`

It seems that as a result the import missed extensions

**Comment by aeschli** [comment]
I wanted to attach my profile here, but it's big and I can't tell if it contains personal info due to the double encoding.
Please make it regular JSON...

**Comment by sandy081** [comment]
Can you please share your profile via slack or email?

**Comment by aeschli** [comment]
I tried to reproduce the issue and was not able to. Closing
