### ISSUE TITLE
Implement large file confirmation for file working copy editors

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#172129]
Testing #171743

* vscode desktop
* have a 2BG file
* in the explorer, right+click and open in HEX editor
* 🐛 no warning

**Comment by bpasero** [comment]
Yeah it will only apply to text editors, I will update the test plan item and maybe the setting should change to `workbench.textEditorLargeFileConfirmation`.

**Comment by jrieken** [comment]
same is true for notebooks (and I guess for any custom editor)

**Comment by bpasero** [comment]
Yeah, it is currently only implemented for text editors, though the underlying logic for file size limits is available to anyone from the file service via the `limits` option:

https://github.com/microsoft/vscode/blob/569f3d11046dd71e3e6ac3246c83bc8cb4bdd564/src/vs/platform/files/common/files.ts#L321

We can probably implement it for notebooks, by adding the limit here:

https://github.com/microsoft/vscode/blob/569f3d11046dd71e3e6ac3246c83bc8cb4bdd564/src/vs/workbench/services/workingCopy/common/storedFileWorkingCopy.ts#L556

But for custom editors that are not text based, the loading of data is not under our control...

**Comment by jrieken** [comment]
+1 for doing this for editors that we ship out of the box /cc @roblourens @rebornix

**Comment by bpasero** [comment]
I can see to add this for notebooks, but custom editors that do file loading on their own will probably never work.

**Comment by rebornix** [comment]
> I can see to add this for notebooks

I was expecting this to auto opt-in feature for working copy but it seems it requires us to handle it in editor input or editor level?

**Comment by bpasero** [comment]
I have not started the investigation yet, but yeah it might be on the editor level and not generic.
