### ISSUE TITLE
Inline suggest actions shouldn't have title attributes

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#172183]
Testing #172029

We shouldn't have tooltips here:

![image](https://user-images.githubusercontent.com/2193314/214340159-207d8c1e-f286-45d5-8169-029672020553.png)

**Comment by hediet** [comment]
@isidorn @jrieken what do you think?

Currently, all toolbar actions have tooltips.

**Comment by jrieken** [comment]
Yeah, unsure. All toolbars/actionbars have it but most have an icon and not the same text as the tooltip

**Comment by isidorn** [comment]
Both options are fine for me. Whatever you prefer.
I am slightly leaning towards no title. So we do not have hover in a hover (feels IDE-ish and heavy).
