### ISSUE TITLE
Accept Word does not work across lines

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#172162]
Testing #172029

Currently my top pain point with using Accept Word in inline suggestions is that it does not go across lines. Once I get to the end of line I can not trigger it anymore to start accepting words from the second line.

fyi @jrieken

**Comment by hediet** [comment]
Fixing this bug requires some re-architecturing:
As soon as the cursor changes the line, the session is being thrown away and new inline completions are asked for the new line.

**Comment by isidorn** [comment]
@hediet would you like to create a test plan item for this, or would you like me to verify it and we add verification-needed here?

**Comment by hediet** [comment]
I'll create a general test plan item to test various sub-features of the inline completion feature, as the rewrite touched everything.

I'll add the label here just to get more coverage.
