### ISSUE TITLE
Installing Dev container extension does not have any impact on Continue Working On picker

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#172192]
Testing #172042

- Install additional development environment options shows Dev Containers, Codespaces and Remote Repositories extension
- I Installed Dev Containers extension and ran Continue Working On command
- I do not see any options for dev container and when I clicked on Install additional development environment options it shows again same extensions list. So I am confused or stuck to understand what I have to do after.

![image](https://user-images.githubusercontent.com/10746682/214347244-06fb3f86-c54f-4649-b48c-4be0748ee802.png)

**Comment by joyceerhl** [comment]
Dev Containers only contributes a Continue On option if you're currently in a remote repository, and it looks like you are in a desktop repo, so this is currently as designed.
