### ISSUE TITLE
Export profile confirmation dialog should be an info dialog

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode#172158]
Testing https://github.com/microsoft/vscode/issues/172034

Version: 1.75.0-insider
Commit: 0a6c277e4faa44a6b6eb82ddca8bfeccf7fecef6
Date: 2023-01-24T05:22:50.699Z
Electron: 19.1.9
Chromium: 102.0.5005.194
Node.js: 16.14.2
V8: 10.2.154.23-electron.0
OS: Linux x64 5.15.0-56-generic
Sandboxed: Yes

- Export a profile to a file
- Confirmation dialog shows a question mark, but there's no question here

![image](https://user-images.githubusercontent.com/6461412/214307131-25cd3e28-033e-4dfa-98a3-05e853045c6e.png)

**Comment by aeschli** [comment]
It's better on Windows:
![image](https://user-images.githubusercontent.com/6461412/214337808-98fe676a-37c6-4e6e-8f12-7cd962a2bbba.png)

**Comment by bpasero** [comment]
We can change all dialogs from `IDialogService.show` to use `info` instead of `question` type. This only seems to have an impact on Linux and changes the icon to an info icon.
