### ISSUE TITLE
Add Labels toolbar item only shown on hover over title bar

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode#172163]
Testing microsoft/vscode-pull-request-github#4433

Makes it hard to discover. I see other views showing toolbar items at all times. Can the PR extension do this too?

**Comment by alexr00** [comment]
@chrmarti We're going to re-design the "create" view and integrate the label selection in there, so this should improve after that.

@mjbvz there's a difference between how webview views and tree views show the title bar actions:
- Tree views show the title actions when the mouse is over anywhere in the view 
- Webview views show the title actions only when the mouse is over the title bar

**Comment by mjbvz** [comment]
Duplicate of #109030
