### ISSUE TITLE
Not convinced Undo Accept Part is needed

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#172153]
Testing #172029

We are teaching users to use Undo Accept Part, while in reality everyone will use Cmd+Z and it will just work.
Why do we think it is important to have this action? Is it bringing something in addition to the regular undo?

We can also see click rates from users and we can then remove it later if needed.

![Screenshot 2023-01-24 at 14 04 25](https://user-images.githubusercontent.com/1926584/214298987-a1d50097-d8bc-4454-8925-3f78f6fff97d.png)

**Comment by hediet** [comment]
This is to advertise the keybinding `Ctrl+Left`.

**Comment by isidorn** [comment]
I am wondering why would a user want to use that one compared to "Ctrl+Z" which is already in their muscle memory?

**Comment by hediet** [comment]
Because Ctrl+Right/Left forms a nice pair. If you think strongly about it, I can remove that keybinding + the menu entry.

**Comment by isidorn** [comment]
No strong preference. I was just wondering out load. Let's just make sure we have telemetry and we see how much users use it :)
Also let's see what @jrieken says since he says he uses it in his daily flow.

**Comment by jrieken** [comment]
I don't mind having it in the menu but the keybinding is unfortunately annoying. At least on mac it overlaps with word navigation and I often see myself undoing changes instead of navigation to the word or line start. I, personally, have the keybinding disabled for that reason

**Comment by isidorn** [comment]
Ok. One more reason to get rid of the whole action :)
If there is no keybindings, there is no need for the menu. Users will just use cmd+Z.
