### ISSUE TITLE
New inline suggest hover uses a 2px border instead of 1px

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#172180]
Testing #172029

![image](https://user-images.githubusercontent.com/2193314/214339324-86c7af59-3114-4702-850e-6706b58e449f.png)

2px has special meaning that it's "locked" while alt is held:

![image](https://user-images.githubusercontent.com/2193314/214339401-8057d4cf-4604-4260-8e2a-aa8e60a00b81.png)

vs

![image](https://user-images.githubusercontent.com/2193314/214339470-5218c6ee-14fa-4146-8f8d-99ea761867e1.png)

**Comment by bhavyaus** [comment]
How do I verify this using a tool? The two hovers (inline suggest hover and terminal hover) look the same to me on my devices.
