### ISSUE TITLE
Close tab does not work

### ISSUE THREAD

**Issue by hediet** [microsoft/vscode#172166]
Testing #172052

![chrome_I08uxqxE49](https://user-images.githubusercontent.com/2931520/214315873-aed2aff7-3852-4dd8-9b4a-8128a18e0d6a.gif)

**Comment by sandy081** [comment]
@bpasero I assume this is coming from you?

https://github.com/microsoft/vscode/blob/c35bf3b3401cef46d2c4dee464adb52c97b81228/src/vs/workbench/browser/window.ts#L217

**Comment by bpasero** [comment]
Looks like this is from @joyceerhl

https://github.com/microsoft/vscode/commit/42aa9d3e999c2a205774a173b98ad4623a53f720

**Comment by joyceerhl** [comment]
I am unable to reproduce this, Close Tab works as expected for me (I'm in Edge). Which browser do you use?

**Comment by hediet** [comment]
I used chrome.

**Comment by joyceerhl** [comment]
I was able to repro on Chrome as well, but I can't see why this would work in Edge and fail in Chrome. The warning that gets printed to the browser console when this happens is:

```
Scripts may close only the windows that were opened by them.
```

**Comment by bpasero** [comment]
Why would we ask to close the VS Code web instance actually? I think when this flow happens it is typically a popup that opens which then triggers the protocol link and then it makes sense to close that. But for VS Code I would not expect to close the tab.

**Comment by joyceerhl** [comment]
I added the Close Tab button because by opening a protocol link from web you are launching the desktop VS Code instance, so the assumption is you don't want to keep VS Code for the Web open also.

**Comment by bpasero** [comment]
I do not think its possible to close a tab unless you opened it via JavaScript.

**Comment by joyceerhl** [comment]
This works in Edge though (which is why I didn't see an issue when first implementing it).

In any case it seems like we can't support it consistently, so I think we should just take this option out.

**Comment by bpasero** [comment]
I will do this as part of https://github.com/microsoft/vscode/issues/170492

**Comment by joyceerhl** [comment]
Thank you @bpasero!
