### ISSUE TITLE
Do not render ?/? in inline completion toolbar

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#172142]
Testing #172029

When the inline hover shows up for a split second you render ?/? or something like that - since you do not know how many completions there will be.
I find this visually noisy, could we improve this? So we say 1/1 initially, or even better we render it only once we know how many completion suggestions there are?

**Comment by isidorn** [comment]
Clicking on Accept Part leads me to this weird 1/? state

![Screenshot 2023-01-24 at 12 57 47](https://user-images.githubusercontent.com/1926584/214285875-1b944cf7-aaf4-41fe-8b98-b863649da79c.png)

**Comment by rebornix** [comment]
I often see `1/?` while deleting characters.
