### ISSUE TITLE
How to hide explorer without activity bar?

### ISSUE THREAD

**Issue by andy-hanson** [Microsoft/vscode#17217]
- VSCode Version: 1.8.0
- OS Version: Linux Mint 17.3

Steps to Reproduce:

1. View -> Hide Activity Bar
2. Ctrl+Shift+E to show the explorer
3. Ctrl+Shift+E again does not hide the explorer
4. Apparently I have to go to View -> Show Activity Bar and use that to hide it.

It would make sense if the command for showing the explorer also hid it. Just like the command for hiding the activity bar also shows it again.

**Comment by wallverb** [comment]
Not sure if the same https://github.com/Microsoft/vscode/issues/15891 but FYI

**Comment by andy-hanson** [comment]
Looks like it. I was expecting "Toggle explorer" instead of "Toggle side bar" so I hadn't noticed that.

**Comment by NN---** [comment]
https://code.visualstudio.com/docs/getstarted/keybindings
```Ctrl+B 	Toggle Sidebar Visibility 	workbench.action.toggleSidebarVisibility```
