### ISSUE TITLE
"-Xfrozen_modules=off" has no effect in debugpy

### ISSUE THREAD

**Issue by goradawid** [microsoft/vscode#172126]
Type: <b>Bug</b>

Even with the appropriate configuration: 
` "configurations": [
        {
            "name": "program",
            "type": "python",
            "request": "launch",
            "module": "uvicorn",
            "args": [
                "src.app:main",
                "--factory",
                "--reload",
                "--host=0.0.0.0",
                "--port=8081",
                "--workers=1"
            ],
            "justMyCode": false,
            "pythonArgs": [
                "-Xfrozen_modules=off"
            ]
        }
]`

Debugger still reports:

0.00s - Debugger warning: It seems that frozen modules are being used, which may
0.00s - make the debugger miss breakpoints. Please pass -Xfrozen_modules=off
0.00s - to python to disable frozen modules.

Exactly the same thing happens, when passing that directly to debugpy:

python -Xfrozen_modules=off -m debugpy --listen localhost:5678 -m uvicorn src.app:main --factory --reload --host=0.0.0.0 --port=8081 --workers=1

VS Code version: Code 1.74.3 (97dec172d3256f8ca4bfb2143f3f76b503ca0534, 2023-01-09T16:57:40.428Z)
OS version: Linux x64 5.15.0-58-generic snap
Modes:
Sandboxed: No

<details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eclipse-keybindings|alp|0.16.1
vscode-postgres|cko|1.4.0
gitlens|eam|13.2.0
vscode-docker|ms-|1.23.3
black-formatter|ms-|2022.6.0
isort|ms-|2022.8.0
python|ms-|2022.20.2
vscode-pylance|ms-|2023.1.30
jupyter|ms-|2022.11.1003412109
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.14
vscode-jupyter-cell-tags|ms-|0.1.6
vscode-jupyter-slideshow|ms-|0.1.5
remote-containers|ms-|0.266.1

</details>

**Comment by roblourens** [comment]
Please file this on the vscode-python extension
