### ISSUE TITLE
Auto publishing: Cancel should stop Continue On flow

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode#172147]
Testing #172030

Choosing Cancel left me with the sign-in QuickPick and "Storing..." progress notification. I expected it to cancel everything.

<img width="264" alt="image" src="https://user-images.githubusercontent.com/9205389/214285867-3282a3ac-257d-46f1-a8dc-88b95d91b6ac.png">

<img width="862" alt="image" src="https://user-images.githubusercontent.com/9205389/214287098-51f4a5dd-730d-4c85-adab-0c09376a3474.png">

**Comment by joyceerhl** [comment]
Consolidating all dialog related feedback into https://github.com/microsoft/vscode/issues/172144#issuecomment-1402785600
