### ISSUE TITLE
Error handler not triggered when triggering an error

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#172132]
Testing #172057

I added this code to my extension:

```ts
vscode.window.createTextEditorDecorationType(null!);

setTimeout(() => {
		throw new Error("HELLO WORLD");
	}, 5000);

const logger = vscode.env.createTelemetryLogger({
	sendEventData: function (eventName: string, data?: Record<string, any> | undefined): void {
		console.log("sendEventData: ", eventName, data);
	},
	sendErrorData: function (error: Error, data?: Record<string, any> | undefined): void {
		console.log("sendErrorData: ", error, data);
	}
}, {});
```

But my error data handler was not triggered.

**Comment by lramos15** [comment]
@jrieken I wonder if this was a case we would expect and want to work? I think right now the way the ext host error handler works is it only captures errors caused by misuse of the extension API and not thrown errors like this. Should the telemetry API capture these?

**Comment by kimadeline** [comment]
From [this comment](https://github.com/microsoft/vscode/issues/45264#issuecomment-1237017329) we (Copilot team) were expecting the `TelemetryLogger` API to provide some support whenever extensions throw errors.

**Comment by jrieken** [comment]
This should work: we have a [catch-all](https://github.com/microsoft/vscode/blob/990a496681948ec274da5503b35cd49a7d06c0a2/src/vs/workbench/api/common/extensionHostMain.ts#L88) error handler that tries to associate any unhandled error with an extension

**Comment by connor4312** [comment]
This works only if Liveshare, Codespaces, and Copilot are not installed
