### ISSUE TITLE
workspaceFolder does not work in settings.json

### ISSUE THREAD

**Issue by W2Q3Q1** [microsoft/vscode#172174]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.74.3
- OS Version: Ubuntu 20.04

Steps to Reproduce:
When configuring auto-compile for protoc compiler, we found that workspaceFolder did not work well, while workspaceRoot worked well.

1. Install ProtoBuf 21.12 for Ubuntu C++ from source code using CMAKE according to [https://github.com/protocolbuffers/protobuf](https://github.com/protocolbuffers/protobuf)
2. Open a new project folder and create .vscode/settings.json, add codes below into the outermost dict of json
```
"protoc":{
    "compile_on_save": true, 
    "options": [
        "--proto_path=${workspaceFolder}/protobuf", 
        "--cpp_out=${workspaceFolder}/protobuf", 
    ]
}
```
3. Create directory protobuf in the workspace, and write some protobuf file inside protobuf
4. Try to save the file using CTRL + S
5. VSCode will give out warning from protoc that the folder does not exist
6. When replace workspaceFolder into workspaceRoot, everything will be OK, and the protobuf file will be compiled normally

**Comment by sandy081** [comment]
I suppose this settings are owned by an extension. Please see which extension is reading this setting and I suppose it is c++ and file issue against the extension. Thanks.
