### ISSUE TITLE
What profile do I import?

### ISSUE THREAD

**Issue by hediet** [microsoft/vscode#172164]
When importing a profile through a profile link (e.g. https://insiders.vscode.dev/profile/github/578a207161ceb28b94a18417bbece68c -> Open in Visual Studio Code - Insiders), I get this screen:

![image](https://user-images.githubusercontent.com/2931520/214312955-63111752-b59d-4e59-b7ab-a3ca2699f2e2.png)

I cannot anticipate what happens when I click on "Import".
* Does this override the current profile with the profile I'm about to import?
* Does this create a new profile? What would be the name of the new profile?

I think an easy fix here would be to show the name of the profile that will be created, for example by labeling the button `Import "demo-profile"` instead of `Import` or showing a label in the sidebar to indicate the name of the profile.

**Comment by sandy081** [comment]
Fixed by 207aafcb194f33b10df5a4d4040346e91cf1824b
