### ISSUE TITLE
A couple more pixels of separation between Accept Tab and Accept Part

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#172152]
Testing #172029

I feel like the Accept Tab and Accept Part are too close. Can we give it 2 more pixel breathing room, so it is clearer these are different actions?

The separation between the other elements is fine. So ideally all other boundaries remain the same

![Screenshot 2023-01-24 at 14 00 03](https://user-images.githubusercontent.com/1926584/214298164-3c1dc4b4-7d09-4a41-90ec-a4b00bf6edc6.png)

**Comment by hediet** [comment]
Before:

![image](https://user-images.githubusercontent.com/2931520/214576552-43481877-97fc-4079-93e3-ea4fa5881563.png)

After:

![image](https://user-images.githubusercontent.com/2931520/214576604-7aa45842-8f7c-40b4-a55f-57aada1ddc99.png)

**Comment by isidorn** [comment]
Hmm did the first Accept move more to the right? Thus it is farther away from >
Also the ... moved farther away.

So overall I think it looks worse. My suggestion was not good. Though I was mostly concerned about the distance between the two accept actions. But I understand that coding only that case is not nice.

**Comment by hediet** [comment]
I think it looks better. The first Accept did not move, there is only more space between `Accept` and `Accept Word` and `...` (4px more).

**Comment by isidorn** [comment]
Ok, great if you changed to 2px. 4px was too much imho :)
