### ISSUE TITLE
registerCompletionItemProvider problem

### ISSUE THREAD

**Issue by DracotMolver** [Microsoft/vscode#17210]
- VSCode Version: 1.7.2
- OS Version: Linux, Solus os

I've created a extension using registerCompletionItemProvider. Before explain everything, this is my code:
```javascript
const selectors = ['html', 'php', 'twig', 'jsp', 'htm'];

const completionItem = {
   provideCompletionItems: () => resolve, // This  is because I'm using a promise function
   resolveCompletionItem: (item, token) => item
}

let action = vscode.languages.registerCompletionItemProvider(selectors, completionItem, '&')
context.subscriptions.push(action);
```
Ok. The code above works fine. When I typing **&**, I get the whole list of items. Obviously, this works in the files extensions that I've predefined. But, the thing is that when I typing something that is insde the list whitout using **&**, I've got the name of the item. Eg.

```
[what I typing] 
cel ------------------> cels;(This is a item insie the whole list) // This should not happend

[when I typing "&"]
& --------------------> a list of all the itmes. // This behavior is right.
```

**Comment by kieferrm** [comment]
@DracotMolver how is code completion being invoked in your first case? It's not automatically triggered.

**Comment by DracotMolver** [comment]
@kieferrm maybe the whole code can be useful
https://github.com/DracotMolver/HTML-Symbols/blob/master/extension.js

it's invoked when I just write the same name as the completition should be showing.
This would be my list.
```
pounds; 
detail;
coins;
```
So when I type **&**, it should appears my list. But it happens the same when I'm typing **po** (shows me pounds;)

(Don't know if I explained right :/)

**Comment by jrieken** [comment]
Assuming you want `&pounds` and `&detail` to be inserted, you should set the label or insertText of the CompletionItem to the those strings, not `pounds`. By default, the editor asks for suggestion all the time, not only when a trigger character is typed. Both can be configured (suggest on type, suggest on trigger character) but you check with the context when computing your list
