### ISSUE TITLE
Inline suggest hover cursor feedback is wrong when there is only 1/1 option

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#172184]
Testing #172029

Hovering this area shows the pointer cursor but it should be disabled and not change the cursor as there is only 1 option.

![image](https://user-images.githubusercontent.com/2193314/214340429-2da2a648-b82e-4274-83ff-972b5c042509.png)

**Comment by Tyriar** [comment]
Do you mean https://github.com/microsoft/vscode/issues/172150, because that's only talking about the number part?

**Comment by hediet** [comment]
Can you verify that the fix of #172150 also fixes this? Thanks!
