### ISSUE TITLE
Go to Previous Change plays cue for current and previous change

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode#172209]
Testing #171860

I have a file like this 

<img width="679" alt="image" src="https://user-images.githubusercontent.com/30305945/214360898-86578597-f9fa-4172-ab7d-0a0a67ee6fd7.png">

When I am on the last change and play Go to Previous Change via the command palette, I hear both the deleted cue and the modified cue.

**Comment by meganrogge** [comment]
I think what you're hearing is actually the `Error on Line` cue, which is because the prior line has an error and is also modified. the sound is quit similar, so I see why that's confusing.
