### ISSUE TITLE
VSCode not open after i upgraded to vscode 1.8.0

### ISSUE THREAD

**Issue by zephiro** [Microsoft/vscode#17228]
- VSCode Version: 1.8
- OS Version: OSX El Captian 10.11.4 (15E65)

Steps to Reproduce:

1. Version 1.7 works, but after updating I stopped opening
2. If I reinstall 1.7 works perfectly, but I can not open it when I install 1.8
3. With version 1.7 deactivate all extensions and update to 1.8 but not open

**Comment by gokhansengun** [comment]
Same here with same configuration.

**Comment by kieferrm** [comment]
@zephiro in step 2, are you saying that you see the same issue when downloading vscode from the website and install it newly?
