### ISSUE TITLE
Support quick outline for PHP?

### ISSUE THREAD

**Issue by bingzheyuan** [Microsoft/vscode#1722]
Is that possible to add a function list panel?
Besides, the "Go to Symbol" function seems not working for php file. I am working with vscode v0.10.6
![bug](https://cloud.githubusercontent.com/assets/5099742/12063466/677bb6f2-afaf-11e5-88e9-be8a61f19b82.jpg)

**Comment by egamma** [comment]
This is currently not implemented but a valid feature request.

**Comment by Ciantic** [comment]
This is duplicate of #132 I think also you should vote this: https://visualstudio.uservoice.com/forums/293070-visual-studio-code/suggestions/7752606-php-intellisense

PHP IntelliSense is required for symbol navigation (e.g. symbols, Go to definition, ...)

**Comment by egamma** [comment]
Closing as a duplicate of #132, thanks @Ciantic
