### ISSUE TITLE
Error renderer "in line" link should include the line number

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#172208]
Testing #172096

It's not clear if this link goes to the active line because of https://github.com/microsoft/vscode/issues/172206, but I think it should and the link should also include the line text, similar to the terminal

![image](https://user-images.githubusercontent.com/2193314/214359441-588a2752-1446-4087-bab4-59f564895beb.png)
![image](https://user-images.githubusercontent.com/2193314/214359698-6a00723b-8cd1-4a17-b536-1f1fa0d40530.png)

**Comment by rebornix** [comment]
Unfortunately the link is from the kernel in the form of html `<a href="$link">link</a> in line 2` so we are not doing another syntax detection to include the `line 2` into the link right now. It's a nice to have feature.
