### ISSUE TITLE
No notification when starting on Linux with a different system language

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#172240]
Testing #171890

- Using Linux with xfce, I changed the language to `es_MX.UTF-8`
- Opened code-insiders, no notification about language

**Comment by TylerLeonhardt** [comment]
We split based on the `.` and not the `_`. Maybe we should do that too. Linux seems to use that a fair bit.

**Comment by rzhao271** [comment]
Another potential issue is that the newer Electron `getPreferredSystemLanguages` API is currently only being used for Windows.

**Comment by TylerLeonhardt** [comment]
From what @rzhao271 was showing me, the `getPreferredSystemLanguages` API should normalize this to `es.MX`

**Comment by rzhao271** [comment]
\closedWith 1001c879c84f67e57dd9e7cb6f408bea022d50ed
