### ISSUE TITLE
TypeScript intellisense does not work correctly for interface properties that can be an interface or an array of interfaces

### ISSUE THREAD

**Issue by chase-smith** [Microsoft/vscode#17229]
- VSCode Version: 1.8.0
- OS Version: Linux Mint 17 Xfce 64-bit

TypeScript intellisense does not work correctly on interface properties that can be an interface or an array of that interface. Intellisense is only present when the property is in the array form. 

Code to reproduce:
```typescript
interface SomeInterface {
    prop1: number;
    prop2: string;
}
interface ComplexInterface {
    fail: SomeInterface | SomeInterface[];
}
let b:ComplexInterface = {
    fail: {}
}
```
Screenshot of what intellisense gives if the property is an object:
![fail_pic_1](https://cloud.githubusercontent.com/assets/18446539/21212118/33a30ee4-c24f-11e6-8ea4-62df3b05a1c4.png)

Screenshot of what intellisense gives if the property is an array of objects:
![fail_pic_2](https://cloud.githubusercontent.com/assets/18446539/21212123/48b88d4a-c24f-11e6-9528-bcb79b2988aa.png)

Expected behavior is that intellisense in the first screenshot would act like the second screenshot, and list properties `prop1` and `prop2`.

Edit: I found that if I use `fail: <SomeInterface>{}`, intellisense works as expected, as shown in the below screenshot. However, this seems like it shouldn't be necessary, given how good TypeScript is at inferring other things.
![fail_pic_3](https://cloud.githubusercontent.com/assets/18446539/21212903/697daa40-c256-11e6-8228-5ceba37aa098.png)

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript#13036
