### ISSUE TITLE
Issues with Localization

### ISSUE THREAD

**Issue by eleanorjboyd** [microsoft/vscode#172228]
Testing: https://github.com/microsoft/vscode/issues/172045

So I think these are bugs and not the desired behavior but I am not totally sure since VS Code does mark them as red but does not say the error or put the red squiggle under it.

in a json
<img width="967" alt="Screenshot 2023-01-24 at 9 39 27 AM" src="https://user-images.githubusercontent.com/26030610/214371839-e698f497-3a98-4daf-8334-d06c8839da4b.png">

<img width="778" alt="Screenshot 2023-01-24 at 9 56 11 AM" src="https://user-images.githubusercontent.com/26030610/214371843-dfeb3da5-595c-493c-8bcc-74cfe88e34f7.png">

in a HMTL file
<img width="578" alt="Screenshot 2023-01-24 at 10 01 46 AM" src="https://user-images.githubusercontent.com/26030610/214372086-e6ef594c-86f7-4057-abf4-b0931f427f02.png">
<img width="600" alt="Screenshot 2023-01-24 at 10 01 17 AM" src="https://user-images.githubusercontent.com/26030610/214372089-96d26e2b-d0e2-4ae3-908d-ee2356536292.png">

**Comment by TylerLeonhardt** [comment]
@aeschli I'm going to defer this to you first since you're most familiar with the code. Let me know if you think this is because of `@vscode/l10n`

**Comment by aeschli** [comment]
@eleanorjboyd Can you paste the code examples as well?

**Comment by eleanorjboyd** [comment]
```
{
    "cars": {
        "Nissan": [
            {"model""Sentra", "doors":4},
            {"model":"Maxima", "doors":["hello", 2},
            {"model":"Skyline", "doors":"hello"}
        ],
        "Ford": [
            {"model":"Taurus", "doors":4},
            {"model":"Escort", "doors":4}
        ]
    }
}

```
(I didn't have the first json file still but here is the same bug in the other json file:
```
{
    "cars": 
        "Nissan": [
            {"model":"Sentra", "doors":4},
            {"model":"Maxima", "doors":["hello", 2]},
            {"model":"Skyline", "doors":"hello"}
        ],
        "Ford": [
            {"model":"Taurus", "doors":4},
            {"model":"Escort", "doors":4}
        ]
    }
}
```

```
<h1 style="color:blue;">A Blue Heading</h1>

<p style"color:green">A red paragraph.</p>

<style>p {color: #33475B; </style>
```


this one seems to be fixed:
![Screenshot 2023-01-25 at 9 19 30 AM](https://user-images.githubusercontent.com/26030610/214635105-27abc16e-2633-44c6-b153-64b4ab33578b.png)

**Comment by aeschli** [comment]
Again I can't reproduce:
![image](https://user-images.githubusercontent.com/6461412/215285106-4d426a13-df97-4a48-9ee0-4e325763a9c2.png)

Please check in the dev tools console whether the JSON language server had problems starting. You can also check the `JSON Language Server` output for information whether the server is up.

What I saw is that it took a long time for the errors to show as an other extension (in may case Python) had problems starting up.
So maybe try with extensions disabled.

On what platform and with which language pack did you test?

**Comment by eleanorjboyd** [comment]
Not sure why but this one is also now looking correct- I am seeing the same errors you are. My insiders was having trouble updating so I wonder if it is an issue relat
![Screenshot 2023-01-30 at 11 25 02 AM](https://user-images.githubusercontent.com/26030610/215575703-8cd71bb4-f5eb-4103-bcad-f9d298fc3598.png)
ed to that. Anyways looks good!
