### ISSUE TITLE
Continuous test run: Two buttons to cancel, only one works

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode#172205]
Testing #172097

The button with square icon does not cancel the token, only the "Continuous" button does:
<img width="371" alt="image" src="https://user-images.githubusercontent.com/9205389/214358274-52912150-9ed6-43dd-8a37-fe041bfe9bd0.png">

**Comment by bhavyaus** [comment]
I found the two buttons confusing as well. 
Also, could we have a better indication that the Continuous Run mode is ON besides just the icon. I might need to change my test code also and might forget that continuous run is ON/OFF. Perhaps an indicator in the Status Bar
Perhaps 
![image](https://user-images.githubusercontent.com/25044782/214435079-b8b3b03c-2b16-4670-b783-d8a54583c8b2.png)

**Comment by chrmarti** [comment]
> The square icon stops the current test run, the eye icon will turn off continuous run mode. They're different actions, maybe we can make this clearer?

I missed that. I see only one cancellation token and that is cancelled when I stop continuous run. Where is the cancellation token for the current test run while we are in continuous run mode?

**Comment by connor4312** [comment]
ah, yea. We don't have a cancellation token there. Will need to tweak the API, and consider how to make that work...

**Comment by connor4312** [comment]
The square cancel button not working was actually a bug in the selfhost test provider.
