### ISSUE TITLE
Import from gist should be possible

### ISSUE THREAD

**Issue by lramos15** [microsoft/vscode#172227]
Testing #172051

If we allow exporting from a gist file, it would be great to allow importing from one to avoid having to download the file etc. Either pasting a URL or having it query your GitHub account. Pasting the URL would be better for sharing.

**Comment by sandy081** [comment]
It shall work, have you tried importing the profile by pasting the URL?

**Comment by lramos15** [comment]
Oh, I just clearly missed this was possible because I didn't read the text and just thought the various entries in the quickpick were ways to import. I didn't see gist as an option so didn't think it was possible. It does work.
