### ISSUE TITLE
Unexpected screen reader announcement

### ISSUE THREAD

**Issue by lramos15** [microsoft/vscode#172264]
Testing #171862

In terminal accessibility mode if you do the command `echo hi`.

This produces the output
```
echo hi
hi
``` 
If you move the cursor back from the h on the second line to the i on the first line, h get's announced twice. It's like the new line is announced as the previous character. Is this expected? It felt like it would be very easy to get confused about what is on the screen, but maybe this is a native behavior.

**Comment by meganrogge** [comment]
see this response, applicable here as well https://github.com/microsoft/vscode/issues/172204#issuecomment-1402484940
