### ISSUE TITLE
Opening a profile preview shows an error

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#172220]
Testing #172052

When opening the link I created I saw this:

<img width="1137" alt="image" src="https://user-images.githubusercontent.com/2193314/214367300-3ff7fca5-a6a5-48a2-83cc-b7437ed178b8.png">

**Comment by sandy081** [comment]
Are there steps to reproduce?

**Comment by Tyriar** [comment]
I just opened the link and saw this, could have been related to previous insiders.vscode.dev state? I don't often hit the insiders endpoint.

**Comment by sandy081** [comment]
So the file that is showing error was opened automatically? Or do you open that file and if so from where?

**Comment by Tyriar** [comment]
Not sure, it was weeks since I touched insiders.vscode.dev

**Comment by sandy081** [comment]
I assume you are not able to repro this and I do not know if I can fix this without any proper steps. Hence closing it.
