### ISSUE TITLE
No Install suggestions with untitled inmemory files

### ISSUE THREAD

**Issue by TylerLeonhardt** [microsoft/vscode#172268]
Testing #172094

Not seeing the "Install suggestion" with an in-memory Untitled file created with `New Jupyter Notebook` command:
<img width="2262" alt="image" src="https://user-images.githubusercontent.com/2644648/214390471-cef6ad48-0aef-4404-b4b9-f51b48b93019.png">

**Comment by DonJayamanne** [comment]
Even with notebooks on disc, we do not display an `install sugegstion`, 
instead we display the same `Browser marketplace for ...` option.
