### ISSUE TITLE
Renaming profile doesn't update profiles view

### ISSUE THREAD

**Issue by lramos15** [microsoft/vscode#172231]
Testing #172051

1. Open the profiles view via `Export` or `Show Contents`. 
2. Rename the profile
3. Press the refresh button
4. 🐛 The name at the top is still the old name

**Comment by sandy081** [comment]
Yeah, it is not a common scenario. Not sure worth fixing it. Mostly we are planning to move away from this sidebar UI to rich editor UI for profiles.
