### ISSUE TITLE
Auto publishing: Required to sign in again

### ISSUE THREAD

**Issue by bamurtaugh** [microsoft/vscode#172265]
Testing #172030

Mentioned in https://github.com/microsoft/vscode/issues/172263 too:

Whether I select Always or Cancel, I'm prompted to sign in again, although I already signed in prior to seeing this notification:

![image](https://user-images.githubusercontent.com/25310137/214390133-f185c9d8-0df4-47ec-bdc2-1a4c0fbfb1ce.png)

**Comment by bamurtaugh** [comment]
Maybe the first sign in was to the GitHub Repositories extension, then the second one is to Codespaces extension?

**Comment by joyceerhl** [comment]
Yeah this is caused by misaligned scopes and is unavoidable without token downscoping sadly, obligatory fyi @tylerleonhardt
