### ISSUE TITLE
offered an expired version

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#172261]
installed an old version, prompted to reload, reloaded, saw this indicating the extension couldn't be installed. instead, we shouldn't show expired versions as options

<img width="477" alt="Screenshot 2023-01-24 at 1 18 37 PM" src="https://user-images.githubusercontent.com/29464607/214387711-890f6546-926d-40e7-ab00-bd0f90eba5f2.png">
Testing #172034

**Comment by gjsjohnmurray** [comment]
This message comes from the extension (see lower left of the notification) so my guess is there's nothing VS Code can do to prevent this. AFAIK Marketplace doesn't have a notion of "expired".

**Comment by sandy081** [comment]
We do not control this. I would recommend to file the issue against gitlens extension.
