### ISSUE TITLE
Confusing button preselected in Inline Suggestion Hover

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#172285]
Testing #172029

<img width="361" alt="image" src="https://user-images.githubusercontent.com/876920/214407590-ee0df2d3-d7f6-457d-9822-46765a89efe1.png">

Inside a nested block like below

```
if (condition) {
    |
}
```

Pressing tab or delete multiple times, the buttons in the toolbar are selected in an unpredictable fashion, sometimes it's "Accept", sometimes it's "Accept Part".,

**Comment by hediet** [comment]
Could this be your mouse cursor randomly being there?

**Comment by rebornix** [comment]
@hediet this is very likely. Good catch.
