### ISSUE TITLE
keybinding tooltip for delete is wrong

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#172248]
Testing microsoft/vscode-jupyter#12508

![Screenshot 2023-01-24 at 12 44 58 PM](https://user-images.githubusercontent.com/29464607/214381210-ede552a4-7d30-4a74-9ed8-2e31d9add810.png)

**Comment by roblourens** [comment]
What's the problem? That's a correct keybinding from the Jupyter keybindings extension right?

**Comment by meganrogge** [comment]
Is `D D` the correct keybinding?

**Comment by roblourens** [comment]
It's _a_ correct keybinding

**Comment by meganrogge** [comment]
ok it looked strange / unexpected to me, but feel free to close this if that's what it should be
