### ISSUE TITLE
Links containing `[` and `]` in filename not correctly rendered

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode#172219]
Testing #172084

In all of the following cases, the bracket-delimited segment is treated as a separate link from the preceding and subsequent links:
<img width="852" alt="image" src="https://user-images.githubusercontent.com/30305945/214367235-84ab78f7-d0c7-407f-8fca-f4007f518852.png">

**Comment by Tyriar** [comment]
I don't think I can repro?
![image](https://user-images.githubusercontent.com/2193314/214369078-7fbff955-3de2-443d-a4ee-d3556bb8bbb2.png)
![image](https://user-images.githubusercontent.com/2193314/214369095-86d534f9-a119-4793-91f5-9dd063b9ca96.png)
![image](https://user-images.githubusercontent.com/2193314/214369251-5bea6adc-6b4e-437f-82c1-2845f18a418f.png)

Are you on a remote? Does changing terminal.integrated.enableFileLinks help?

**Comment by Tyriar** [comment]
Also does the file exist on disk?

**Comment by joyceerhl** [comment]
Ugh, no repro in new terminal, all those cases work now. :/ Sorry about that!
