### ISSUE TITLE
setting descriptions should include caveat

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#172252]
Testing #172034

these should mention that pinning is an exception

<img width="936" alt="Screenshot 2023-01-24 at 1 03 45 PM" src="https://user-images.githubusercontent.com/29464607/214384824-3fdb493b-4f65-4fea-9867-b948b6b88b82.png">

**Comment by meganrogge** [comment]
I don't think this has been released yet...

![Screenshot 2023-01-26 at 10 50 29 AM](https://user-images.githubusercontent.com/29464607/214897584-ac0d6c70-3ef6-4105-8dfe-2e133db7f220.png)

**Comment by sandy081** [comment]
@meganrogge information about skipping updates is added to the options of this setting 

<img width="539" alt="image" src="https://user-images.githubusercontent.com/10746682/215063506-f2bb3008-729f-47b2-b916-4243881228a6.png">
