### ISSUE TITLE
`never` option description has two times when

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#172211]
Testing #171988

<img width="449" alt="image" src="https://user-images.githubusercontent.com/10746682/214363836-7a0d56a7-c840-4c13-a420-f598130cf854.png">

**Comment by ikhtearalamshawonmollah54321** [comment]
> Testing #171988
> 
> <img alt="image" width="449" src="https://user-images.githubusercontent.com/10746682/214363836-7a0d56a7-c840-4c13-a420-f598130cf854.png">

👍
