### ISSUE TITLE
ility: NVDA is not reciting the suggestions in the Command Palette edit box.

### ISSUE THREAD

**Issue by WiproPSAccTest** [Microsoft/vscode#17227]
VS Code Version: 1.6.1
OS Version:1607
NVDA version:-2016.2.1

**Steps to Reproduce:**
Prerequisite: NVDA need to be opened.

1.Open Visual studio code editor.
2.Open the command Pallet by pressing "F1" key and type "Theme"
3.Using Down arrow key select "Preference color Theme" and press enter key to select.
4.Using "Up/Down" arrow key select different available theme.

**Expected Result:**
NVDA should recite the lookup options available for theme in the Command Palette edit box. 

**Actual Result:**
1. NVDA is not reciting the suggestions available in the Command Palette edit box.
Note:-This issue is observed for the all the options available in the command palette.

**User Impact:**
Screen Reader user doesn't get to know the options available in the command pallet and without knowing they can't proceed further.

![inspectinformation_vscodeeditor_quickpickeroption](https://cloud.githubusercontent.com/assets/22956130/21212488/2a6ad596-c2b3-11e6-8a5e-4c5f101fbce8.jpg)

![narratorbuddyinformation_vscodeeditor_quickpickeroption](https://cloud.githubusercontent.com/assets/22956130/21212494/2dfff1c8-c2b3-11e6-9cbc-ae4d0edc5baf.jpg)
![nvda_speechviewerinformation_vscodeeditor_quickpickeroption](https://cloud.githubusercontent.com/assets/22956130/21212497/324ee0e0-c2b3-11e6-82bc-fce2d97f030f.jpg)

**Comment by bpasero** [comment]
This works in 1.8.

**Comment by bpasero** [comment]
@WiproPSAccTest please verify using 1.8 at least.

**Comment by WiproPSAccTest** [comment]
@bpasero This issue is not reproducing in code editor 1.8.1. Issue has been fixed.

**Comment by WiproPSAccTest** [comment]
Title has been changed to a common format to perform data population.
