### ISSUE TITLE
Clicking on the terminal while in accessibility mode exits accessibility mode

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode#172200]
Testing #171862

I would expect that you have to explicitly use shift+tab to exit this mode.

**Comment by meganrogge** [comment]
This was initially by design, but might make sense to change it

**Comment by meganrogge** [comment]
also see https://github.com/microsoft/vscode/issues/172006#issuecomment-1402678261

**Comment by Tyriar** [comment]
Let's do this for Feb as it's low priority for the initial version imo
