### ISSUE TITLE
Inconsistent capitalization of language names

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#172245]
Testing #171890

Some are capitalized (English, Deutsch) some are not (español)

<img width="282" alt="image" src="https://user-images.githubusercontent.com/323878/214381329-f629e118-eeab-442d-aef4-0a469a328887.png">

**Comment by roblourens** [comment]
Poor Korean won't even render, but that is probably my local system font?

**Comment by TylerLeonhardt** [comment]
I have asked folks who speak these languages which is correct.

For example, I know we capitalize English and Deutch, @joaomoreno has informed me that both Portuguese and Italian are lowercased in their language...

so although it's weird from an English speaker's perspective, this is actually correct.

**Comment by roblourens** [comment]
Oh ok TIL 👍
