### ISSUE TITLE
auto-updated

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#172254]
Testing #172034

I have two windows open: vscode & xterm.js

In vscode, I ran `code-insiders --install-extension eamodio.gitlens@13.1.1` in the terminal

I opened xterm.js and saw the extension version was 13.1.1, but it said `reload required` as an option. I reloaded the window. It was updated to 13.2.0, but I expected it to stay the same

**Comment by meganrogge** [comment]
I think this happened bc I had vscode opened in a profile and as indicated in a diff't issue, when you update the extension via code-cli, it doesn't work within there

**Comment by meganrogge** [comment]
actually, reproduces. install via cli, version is correct ✅ , reload window, auto-updated 🐛 


https://user-images.githubusercontent.com/29464607/214389436-dceecf96-241c-43ca-a239-b73b52bb622a.mov

**Comment by sandy081** [comment]
I just tried same steps and it seems I cant repro it. May I know are you on different profile in the VS Code you have opened?

**Comment by meganrogge** [comment]
> May I know are you on different profile in the VS Code you have opened?

What do you mean?

**Comment by sandy081** [comment]
VS Code window in the above window, are you on default profile or different profile?

**Comment by meganrogge** [comment]
different profile I think

**Comment by sandy081** [comment]
I could not reproduce, may be I am not following the steps. Can you please provide me the exact steps ?
