### ISSUE TITLE
Profile gist should be pretty printed

### ISSUE THREAD

**Issue by lramos15** [microsoft/vscode#172226]
Testing #172051

1. Export a profile
2. Click as gist
3. Click open in GitHub
4. 🐛 The gist is impossible to read on GitHub because it's not pretty printed 
See https://gist.github.com/lramos15/fbb6e42256960703bbf6b16e13f2d84f

**Comment by sandy081** [comment]
Yeah it is not supposed to be readable. You can always view it in VS Code Desktop or VS Code Web

**Comment by lramos15** [comment]
So should we change it to be open on gituhb.dev? Instead of open on github.com? Having a link to open a one liner gist that you cannot read feels a bit useless to me.
