### ISSUE TITLE
Overlapping localized text on extension page

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#172251]
Testing #171890

<img width="188" alt="image" src="https://user-images.githubusercontent.com/323878/214383742-afb864c0-d84d-4c2e-a592-0c85e92c7f29.png">

**Comment by luabud** [comment]
Saw the same using the portuguese (BR) pack: 
![image](https://user-images.githubusercontent.com/45497113/214384602-a89db06b-962f-40f4-8c14-670502da15ea.png)
