### ISSUE TITLE
[performance] avoid computing fibonacci numbers

### ISSUE THREAD

**Issue by SimonSiefke** [microsoft/vscode#172239]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.74.3
- OS Version: 22.10

Steps to Reproduce:

1. Open Vscode
2.  Fibonacci numbers are computed, blocking the renderer process for ~130ms

![fibonacci](https://user-images.githubusercontent.com/23744935/214377783-47802db1-076b-4484-98ee-4f133343bf2e.png)

Maybe the computation of fibonacci numbers could be removed alltogether (preferred) or there could be a setting to disable the computation of fibonacci numbers?

The code for computing the fibonacci numbers is here: https://github.com/microsoft/vscode/blob/main/src/vs/workbench/services/timer/browser/timerService.ts#L519-L534

**Comment by connor4312** [comment]
I wonder if the baseline could reliably be computed in a worker

**Comment by jrieken** [comment]
We do that to have a baseline performance number that's comparable across machines. It comes far after startup but does compute with other stuff. I like the idea of moving this to a worker but we can also use a lower value. I have chosen 24th because it's one frame (~15ms) on my laptop

**Comment by jrieken** [comment]
Pushed a change to move this into a worker. I have also experimented with some const-time workload, like SHA1 loops for 15ms but got very varying results between 150 and 800 iterations. Sticking to fib for now but it doesn't block the renderer anymore
