### ISSUE TITLE
Two links rendered for file protocol url

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode#172216]
Testing #172084

With a protocol link like `vscode-insiders://file/C:/Users/huer/path/to/file/that/exists.txt`, I get two links in the terminal:
1. hovering over the `vscode-insisders://` part of the link gets me the protocol link interpretation of the text
2. hovering over the `/Users/huer/path/to/file/that/exists.txt` part of the link gets me the 'Open file in editor' link action

<img width="896" alt="image" src="https://user-images.githubusercontent.com/30305945/214364657-4f870ffe-d78b-4498-b4f5-b149e87ed267.png">

The keybinding for both is ctrl+enter, and clicking on both yields two different editors in the file, one with the drive and one without:

<img width="587" alt="image" src="https://user-images.githubusercontent.com/30305945/214365355-b5b01127-c3df-40e3-bc31-5696017efcfc.png">

**Comment by Tyriar** [comment]
@joyceerhl I don't think it's a valid URI with the `:` in `/C:/` is it?

**Comment by joyceerhl** [comment]
I'm not sure, but our openerService seems happy with it:
![image](https://user-images.githubusercontent.com/30305945/214429756-a023a860-8cfd-4f14-9684-f6ea6a47595c.png)

**Comment by Tyriar** [comment]
The protocol link is working, but this is happening because the local link detector is validating the `/Users/...` part as a validated local link which takes priority.
