### ISSUE TITLE
Sorting selections

### ISSUE THREAD

**Issue by AlexanderEkdahl** [Microsoft/vscode#17222]
Feature Request

When a user has multiple selections selected the command would sort the selections and swap them around between the selections. This is in contrast with sort lines which only swaps the lines.

## Scenario 1
Original: 
![1 - original](https://cloud.githubusercontent.com/assets/1409734/21211506/6d6cf5a4-c2c7-11e6-96ef-edbc5e8c3543.png)

User selects the lines that she wants sorted:
![2 - sort select](https://cloud.githubusercontent.com/assets/1409734/21211513/8c8cb91a-c2c7-11e6-8f5d-2a355f84531f.png)

Uses the command "Sort Lines Ascending" and results in this error:
![3 - error sort](https://cloud.githubusercontent.com/assets/1409734/21211528/add2e2b6-c2c7-11e6-9295-123272fd9d9b.png)

## Solution to scenario 1

User performs a multi-selection either using the `alt` key or using the find command:
![4 - sort multiselect](https://cloud.githubusercontent.com/assets/1409734/21211557/031169be-c2c8-11e6-8243-0782dbcd4a52.png)

Execute "Sort Selections Ascending" which results in a correct output:
![5 - sort correct](https://cloud.githubusercontent.com/assets/1409734/21211566/13c56aa8-c2c8-11e6-98ab-1d7206c1e974.png)

## Scenario 2

This would also work for selection that span multiple lines as seen in the following example: 
![6 - all selection](https://cloud.githubusercontent.com/assets/1409734/21211612/6e98f8f0-c2c8-11e6-9878-dcf717692052.png)

Which would result in the following erroneous output:
![7 - all sort selection wrong](https://cloud.githubusercontent.com/assets/1409734/21211624/7e55223c-c2c8-11e6-9465-8c188ebc04b1.png)

## Solution to scenario 2

![8 - all sort multiselection](https://cloud.githubusercontent.com/assets/1409734/21211635/90ffcc0c-c2c8-11e6-81be-4edefff5a1dd.png)

![9 - all sort correct](https://cloud.githubusercontent.com/assets/1409734/21211637/93fde33a-c2c8-11e6-85a9-7bbb8c930a1b.png)

The command should also work with selections that are not adjacent which simplifies sorting functions.

I could probably implement this myself but I want to hear if this is something that should be part of the core product or an extension.

**Comment by rebornix** [comment]
@AlexanderEkdahl this feature request is definitely valid as we always have to deal with the comma while swapping lines. However the correct behavior of swapping lines depends on Language.

Take the second scenario above, it makes perfect sense that we treat the key and value around `:` together as an atomic item because it's JSON. But for XML it's not the case, in XML we should treat content between an opening and a closing tag as an atomic item.

With above consideration, I'll suggest to implement this feature in an extension. It's not a good idea to implement a feature which works reasonably for a few languages but not most of the popular ones. In an extension, you know what language you are working on and selections in the editor, so there is no blocker. Make sense ? @AlexanderEkdahl

**Comment by AlexanderEkdahl** [comment]
@rebornix The feature would not be language dependant at all actually. It only operates on the user selection. 

I will illustrate with another scenario:

![screen shot 2016-12-16 at 12 28 57 pm](https://cloud.githubusercontent.com/assets/1409734/21250833/99180dd2-c38b-11e6-9ad4-f195218d0f03.png)

Which results in the following after "Sort Selections Ascending" is executed.

![screen shot 2016-12-16 at 12 29 13 pm](https://cloud.githubusercontent.com/assets/1409734/21250835/9aec51b8-c38b-11e6-9e69-1a44428b5ee8.png)

"Sort Lines Ascending" currently does nothing in this case.

**Comment by rebornix** [comment]
I'm stupid but now I see your point :) Extension is still the best place for it, whether it's real extension or contribution part of the editor.

**Comment by AlexanderEkdahl** [comment]
I will make an attempt at implementing this myself.

**Comment by alexandrudima** [comment]
This feature request will not be considered in the next [6-12 months roadmap](https://github.com/Microsoft/vscode/wiki/Roadmap) and as such will be closed to keep the number of issues we have to maintain actionable. Thanks for understanding and happy coding!
