### ISSUE TITLE
Python debugger reports incorrect length of an array/list 

### ISSUE THREAD

**Issue by cbothra123** [microsoft/vscode#172201]
Lets say I create a list of 124 elements. When I run the debugger, the variable is listed as a list with index [0:124]. In my understanding the correct representation should be [0:123]. To be fair, when I look into the list, the indexes are correctly assigned upto 123.

Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.74.3 
- OS Version: Mac OS Catalina

Steps to Reproduce:

1. Create a list in python.
2. Run debugger.
3. Look at the list in the debug variables.

**Comment by roblourens** [comment]
Please file this on the vscode-python. A code snippet or screenshot might help.
