### ISSUE TITLE
step into is not working in case of debug nodejs enviroment

### ISSUE THREAD

**Issue by pranaydutta89** [Microsoft/vscode#17223]
1.8.0- VSCode Version:
win 7- OS Version:

Steps to Reproduce:

1. debug in nodejs env
2. try to do step into by f11 or button, its working like f5

**Comment by kieferrm** [comment]
@pranaydutta89 pls provide concrete steps that allow us to recreate the problem.

**Comment by egamma** [comment]
@pranaydutta89 any update?

**Comment by egamma** [comment]
Closing the issue for now. 

@pranaydutta89 pls reopen the issue when you can reproduce the problem with concrete steps.

**Comment by sfenu** [comment]
Please sede this similari issue: https://github.com/Microsoft/vscode/issues/15253
