### ISSUE TITLE
Better icon for continuous test run

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode#172207]
Testing #172097

The current icon doesn't make me think "continuous":
<img width="366" alt="image" src="https://user-images.githubusercontent.com/9205389/214359122-33a61a92-dc75-4f7e-8579-7cb9763908b4.png">

Maybe there is a "repeat" icon like audio players sometimes use that would work better?

**Comment by connor4312** [comment]
This was a little bit of a placeholder. @daviddossett maybe we can get a play icon with a refresh symbol on it or something?

**Comment by daviddossett** [comment]
We do have this icon, semantic as the name may be:

<img width="211" alt="CleanShot 2023-01-31 at 11 36 11@2x" src="https://user-images.githubusercontent.com/25163139/215864360-286f2057-b1a1-42a3-bc74-3de6a53fa34c.png">

**Comment by connor4312** [comment]
Hmm. I do think that's a good icon for rerun and don't want to 'steal' it to mean continuous test running, in the event that we ever want to use that elsewhere. An eye on a run button instead perhaps?

**Comment by connor4312** [comment]
I think the icon has now been in use for too long to change.
