### ISSUE TITLE
Profile for empty window isn't persisted on restart

### ISSUE THREAD

**Issue by lramos15** [microsoft/vscode#172224]
Testing #172051

1. Create a new profile
2. Switch to the profile
3. Restart VS Code
4. 🐛 Keeps switching me back to the default profile

**Comment by sandy081** [comment]
> Switch to the profile

Are you on empty window?

**Comment by lramos15** [comment]
> > Switch to the profile
> 
> Are you on empty window?

Yes

**Comment by sandy081** [comment]
I assume it works for folders/workspaces

**Comment by lramos15** [comment]
It does seem to work with a folder open, yes.
