### ISSUE TITLE
Link with [ ] doesn't render correctly

### ISSUE THREAD

**Issue by andreamah** [microsoft/vscode#172296]
Testing #172084

[![Image from Gyazo](https://i.gyazo.com/ad34a94d7c1c55ae886e4e17a2c1ebf2.gif)](https://gyazo.com/ad34a94d7c1c55ae886e4e17a2c1ebf2)

This detects as two different links, but `/home/andrea/Documents/python-test/test.py` exists and the terminal link without the brackets works.

**Comment by Tyriar** [comment]
This works fine for me:

<img width="391" alt="Screenshot 2023-01-24 at 3 24 49 pm" src="https://user-images.githubusercontent.com/2193314/214443386-f3e96af5-1084-486f-a235-2308f724752f.png">

Are you sure that's the exact path? Also do you have the enableFileLinks setting set?

**Comment by andreamah** [comment]
[![Image from Gyazo](https://i.gyazo.com/95ed2b14f214a91361bed99e8ca1926e.gif)](https://gyazo.com/95ed2b14f214a91361bed99e8ca1926e)

Yeah, I have enableFileLinks on. I'm on Linux if that helps?

**Comment by Tyriar** [comment]
@andreamah you say `/home/andrea/Documents/python-test/test.py` exists, does `/home/andrea/Documents/python-test/[test].py` exist too?

**Comment by andreamah** [comment]
I think I totally misunderstood what the brackets meant; I thought that the bracketed version also matched the same file. After creating `[test].py`, it works! Thanks for the help!!
