### ISSUE TITLE
Should the profile imported in one user-data instance of vscode be available in another?

### ISSUE THREAD

**Issue by karthiknadig** [microsoft/vscode#172320]
Testing #172034

Repro steps:
1. Ensure settings sync is off.
2. Create a profile and export it as local file.
3. Delete all profiles.
4. Run `code --user-data-dir /home/user/tests/userdata1 --extensions-dir /home/user/tests/extensions1 ./myproject`
5. Import profile, wait for import to complete.
6. Leave this vscode instance as is, start a different instance with  `code --user-data-dir /home/user/tests/userdata2 --extensions-dir /home/user/tests/extensions2 ./myproject`

The second instance will now open with the profile that was imported in the first instance.

![image](https://user-images.githubusercontent.com/3840081/214443413-1dc639cb-4d5f-49cf-ab00-5d17f49918c0.png)

**Comment by karthiknadig** [comment]
This is true for #172051 TPI as well. Since they are both related.

**Comment by karthiknadig** [comment]
This only seems to happen on linux.

**Comment by sandy081** [comment]
> The second instance will now open with the profile that was imported in the first instance.

Are you sure that the second instance was opened with the second user-data and extensions-dir? Can you please double check by running following commands?

- Developer: Open User Data Folder
- Extensions: Open Extensions Folder

**Comment by karthiknadig** [comment]
I tried this again on a clean VM. This does not repro.
