### ISSUE TITLE
Usability: NVDA is not reciting the name for the options in the "Git" side bar area.

### ISSUE THREAD

**Issue by WiproPSAccTest** [Microsoft/vscode#17239]
VS Code Version: 1.6.1
OS Version:1607
NVDA version:-2016.2.1

**Steps to Reproduce:**
Prerequisite: Node.js and git repository need to be installed.
1.Open visual studio code.
2.Using "Ctrl+ Shift+ G", key navigate to the Git button.
3.Using "Tab", key navigate to the "Commit all", "refresh", "more" and "Message box" option.
4.Using "Tab", key navigate to the files present in the "git" sidebar area.

**Expected result:**
1.NVDA should recite the name for the "Commit all", "refresh", "more" and "Message box" option.
2.NVDA should recite the files available in the git sidebar area.

Actual Result:
NVDA is not reciting anything for the options and files available in the sidebar area.

User Impact:
Screen Reader user doesn't get to know the purpose of the control as it's not getting announced

Attachments:
![inspectinformation_visualstudiocodeeditor_gitsidebararea](https://cloud.githubusercontent.com/assets/22956130/21213127/799c5900-c2b8-11e6-8f62-d56899073d72.jpg)
![nvda_speechviewerinformation_vscodeeditor_gitsidebararea](https://cloud.githubusercontent.com/assets/22956130/21213126/79715c50-c2b8-11e6-95cb-7a2324a3aca7.jpg)

**Comment by joaomoreno** [comment]
Can't reproduce

![image](https://cloud.githubusercontent.com/assets/22350/25749154/d2921d24-31ad-11e7-8c7c-2ed60b8ccea6.png)
