### ISSUE TITLE
package.json dependency hover not working

### ISSUE THREAD

**Issue by Stanzilla** [microsoft/vscode#172318]
Type: <b>Bug</b>

~~VSC Used to show the information of packages when you hover the name and the latest version when you hover over the version number in package.json. This seems to be broken now.~~

When `json` files are mapped to `jsonc` (I did this because of comments), the hovers no longer work.

```json
"files.associations": {
    "*.json": "jsonc",
}
```

Not sure if that is still a bug then, should it work with jsonc?

VS Code version: Code 1.74.3 (97dec172d3256f8ca4bfb2143f3f76b503ca0534, 2023-01-09T17:05:47.808Z)
OS version: Darwin arm64 22.3.0
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M2 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|9, 11, 11|
|Memory (System)|24.00GB (2.43GB free)|
|Process Argv|/Users/stan/projects/personal/WeakAuras-Companion --crash-reporter-id 8d0e8889-abad-4d94-80df-9496600ad51f|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vstes627:30244334
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
azure-dev_surveyone:30548225
vscccc:30610679
pyindex848cf:30577861
nodejswelcome1:30587005
2e4cg342:30602488
89544117:30613380
2i9eh265:30646982

```

</details>

**Comment by gjsjohnmurray** [comment]
Works OK for me (on Windows):
```
Version: 1.74.3 (user setup)
Commit: 97dec172d3256f8ca4bfb2143f3f76b503ca0534
Date: 2023-01-09T16:59:02.252Z
Electron: 19.1.8
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.22621
Sandboxed: No
```

**Comment by Stanzilla** [comment]
Broken for me on Windows as well

**Comment by gjsjohnmurray** [comment]
Maybe diagnostic steps in comments on #108605 can help you.

**Comment by Stanzilla** [comment]
> Maybe diagnostic steps in comments on #108605 can help you.

Those only suggest checking for npm being on the path, that is the case here,

![image](https://user-images.githubusercontent.com/75278/214451369-69f429d5-bc59-4264-8fac-2181beb28625.png)

**Comment by aeschli** [comment]
The npm extension which adds the hovers and code completions to `package.json` expects `package.json` do be or language `json`. It will not work if configured to `jsonc`.

Redefining all `json` files to `jsonc` is not correct and not recommended as adding a comment to `package.json` will break it.
Better be more specific:
```
 "files.associations": {
	"foo.json": "jsonc",
	"**/foo/*.json: "jsonc",
	....
}
```
or
```
"files.associations": {
	"*.json": "jsonc",
	"package.json": "json",
}
```

**Comment by aeschli** [comment]
Works as designed
