### ISSUE TITLE
Process explorer doesn't show keybinding in context menu

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#172386]
re https://github.com/microsoft/vscode/issues/119345

* open process explorer
* open context menu for an entry
* :bug: no keybindings are rendered, tho some are bound

<img width="421" alt="Screenshot 2023-01-25 at 14 33 33" src="https://user-images.githubusercontent.com/1794099/214576980-83940680-454a-4122-8752-d05d37da7238.png">

**Comment by cawardjames** [comment]
> re #119345
> 
> * open process explorer
> * open context menu for an entry
> * 🐛 no keybindings are rendered, tho some are bound
> 
> <img alt="Screenshot 2023-01-25 at 14 33 33" width="421" src="https://user-images.githubusercontent.com/1794099/214576980-83940680-454a-4122-8752-d05d37da7238.png">
