### ISSUE TITLE
Terminal Accessibility Help dialog stretches from bottom of terminal panel

### ISSUE THREAD

**Issue by gregvanl** [microsoft/vscode#172344]
Testing #171862

The bottom edge of the Terminal Accessibility Help dialog seems attached to the bottom of the Terminal panel

![image](https://user-images.githubusercontent.com/12818376/214476480-070daabe-5af4-480f-af9f-8502769f6c7f.png)

**Comment by meganrogge** [comment]
Yeah and the top blends with the top of the container as well, obscuring the top/bottom focused borders

**Comment by meganrogge** [comment]
on mac: 
![Screenshot 2023-01-25 at 7 52 10 AM](https://user-images.githubusercontent.com/29464607/214581125-447e3db9-68b3-4f25-931c-e2f23e1f08be.png)

**Comment by meganrogge** [comment]
Better

![Screenshot 2023-01-25 at 9 01 00 AM](https://user-images.githubusercontent.com/29464607/214597663-0f9e1ff4-777e-45f1-bf54-167e12675656.png)
