### ISSUE TITLE
Avoid <MyType>Object.create(null);

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#172317]
Some of our list renderers have code that looks like `<MyType>Object.create(null)`. This is a dangerous pattern because it fools TS into thinking that you have created a valid `MyType` but in practice the properties have not yet been set. It's easy to forget to set these properties. See https://github.com/microsoft/vscode/pull/172315 for an example of a real world issue caused by this

Let's rewrite this code to avoid this pattern. Usually the best fix is to return an object literal instead (see the fix in #172315 for example)

## Users

- [x] `processExplorerMain.ts` @mjbvz

    https://github.com/microsoft/vscode/blob/990a496681948ec274da5503b35cd49a7d06c0a2/src/vs/code/electron-sandbox/processExplorer/processExplorerMain.ts#L167-L168

- [x]  `suggestWidgetRenderer.ts` @jrieken 

    https://github.com/microsoft/vscode/blob/9930b1d65a7708deb6ead51e3b9adffd4797694c/src/vs/editor/contrib/suggest/browser/suggestWidgetRenderer.ts#L104

- [x] `commentsTreeViewer.ts` @alexr00
    https://github.com/microsoft/vscode/blob/c600c105793d31942279de2ad95dbbb61c29715f/src/vs/workbench/contrib/comments/browser/commentsTreeViewer.ts#L95
        https://github.com/microsoft/vscode/blob/c600c105793d31942279de2ad95dbbb61c29715f/src/vs/workbench/contrib/comments/browser/commentsTreeViewer.ts#L121

- [x] `remote.ts` @alexr00 
    https://github.com/microsoft/vscode/blob/9930b1d65a7708deb6ead51e3b9adffd4797694c/src/vs/workbench/contrib/remote/browser/remote.ts#L120

- [x] `simpleSuggestWidgetRenderer.ts` @Tyriar  
    https://github.com/microsoft/vscode/blob/c600c105793d31942279de2ad95dbbb61c29715f/src/vs/workbench/services/suggest/browser/simpleSuggestWidgetRenderer.ts#L57

**Comment by jrieken** [comment]
>  Usually the best fix is to return an object literal instead 

Careful with that. We have been using and recommending the `Object.create` way whenever dealing with a map-like usage of object. That's because `{}` inherits properties, e.g

```
> let a = {}
undefined
> a['hasOwnProperty']
[Function: hasOwnProperty]
> let b = Object.create(null)
undefined
> b['hasOwnProperty']
undefined
>
```

**Comment by mjbvz** [comment]
@jrieken Yes `Object.create(null)` still should be used for those cases. If you're creating an object of a specific shape though, it can easily hide bugs

**Comment by jrieken** [comment]
@mjbvz So, this less about `Object.create` than about the hard cast, right? Like, `let foo: IFoo = {}` is equally bad and the issue is that no cast on any kind of object creation should be done, right?

**Comment by Tyriar** [comment]
I think this is done now
