### ISSUE TITLE
Usability: No intellisense narration by the NVDA screen reader for entering of any class to the editor.

### ISSUE THREAD

**Issue by WiproPSAccTest** [Microsoft/vscode#17237]
VS Code Version: 1.6.1
OS Version:1607
NVDA version:-2016.2.1

**Steps to Reproduce:**
Prerequisite: Node.js and git repository need to be installed.

1.Open Visual studio code editor.
2.Open any file and navigate to the file in the editor.
3.Using keyboard create one class in the editor
Ex:-public class Accessibility
 {
  public string variable1 = "";
  public string prop1 {get;set;}
  public void Func1(){}
 }

**Expected result:**
NVDA should recite the suggestions  given by the vs editor as intellisense.

**Actual Result:**
NVDA is not reciting  the suggestions given by the editor as intellisense.
Note:-The same issue is observed for all the types of vs studio code Intellisense. 

**User Impact:**
Screen Reader user doesn't get to know available options under Intellisense and whether selected option is added or not

**Attachments:**
![nvda_speechviewer_intellisense](https://cloud.githubusercontent.com/assets/22956130/21212969/5a150c7c-c2b7-11e6-9365-5e109c924589.jpg)

**Comment by zersiax** [comment]
If by IntelliSense you mean the suggestions on code completion etc, I'm pretty sure that works reasonably well with NVDA actually. If your comments are more specific, please clarify?

**Comment by joaomoreno** [comment]
Can't reproduce

![image](https://cloud.githubusercontent.com/assets/22350/25749116/ad11aa7e-31ad-11e7-8291-ae168dfca2d7.png)
