### ISSUE TITLE
Pressing ‘Back’ mouse button zooms out the window

### ISSUE THREAD

**Issue by Brawaru** [microsoft/vscode#172389]
Type: <b>Bug</b>

0. Have a mouse that has additional keys that can have functions assigned to them, one of which acts like Navigate back key.
1. Reset zoom with <kbd>Ctrl</kbd>+<kbd>0</kbd>
2. Navigate anywhere at least once (e.g. by going to definition).
3. Click the mouse button that navigates back.

**Expected behaviour**: you navigate back as usual.

**Actual behaviour**: you navigate back, but VS Code zooms out one time.

**Additional context**:
It seems that this zoom is different than the one you'd do with <kbd>Ctrl</kbd>+<kbd>➖︎</kbd>: it zooms out, yes, but it does not save the zoom in settings — there it remains `0`; therefore pressing <kbd>Ctrl</kbd>+<kbd>➕︎</kbd> will change to zoom level `1`, not `0`.

VS Code version: Code 1.74.3 (97dec172d3256f8ca4bfb2143f3f76b503ca0534, 2023-01-09T16:59:02.252Z)
OS version: Windows_NT x64 10.0.19043
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4440 CPU @ 3.10GHz (4 x 3093)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|11.95GB (2.20GB free)|
|Process Argv|. --crash-reporter-id 00f2bb44-44e6-48df-99e8-c8d250a1afbb|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes516:30244333
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
azure-dev_surveyone:30548225
vscccc:30610679
pyindex848cf:30577861
nodejswelcome1cf:30587006
3biah626:30602489
f6dab269:30613381
a9j8j154:30646983

```

</details>

**Comment by Brawaru** [comment]
Okay, I fully restarted VS Code (as you can see from extension: none I tried reloading the window and then reloading without extensions to make sure this is not extensions bug) and somehow this is not anymore reproducible. ~~Perhaps ‘have you tried turning it off and on?’ is not a bad advice~~. Should I keep this open even though I cannot anymore provide information on that or closing is fine and then if someone else has this issue they can open another issue referencing this one?

**Comment by TylerLeonhardt** [comment]
We usually close it in this case.
