### ISSUE TITLE
Underline for terminal links takes a while to process

### ISSUE THREAD

**Issue by andreamah** [microsoft/vscode#172300]
Testing #172084

[![Image from Gyazo](https://i.gyazo.com/ad34a94d7c1c55ae886e4e17a2c1ebf2.gif)](https://gyazo.com/ad34a94d7c1c55ae886e4e17a2c1ebf2)

In this gif, I'm holding down ctrl but the underline doesn't show for the first few hovers. The pointer changes, though.

**Comment by Tyriar** [comment]
Are you connected to a remote here?

**Comment by andreamah** [comment]
I'm in a VM, but the window is local to the VM

**Comment by Tyriar** [comment]
It could just be slow disk access on the VM as several file checks need to be done before links will show up, if you can't reproduce this locally I'd say it's acting as designed

**Comment by andreamah** [comment]
I'd say that makes sense. We can close this issue and reopen if we see it locally.
