### ISSUE TITLE
Breakpoint option "Uncaught Exceptions" is activated automatically

### ISSUE THREAD

**Issue by TTSPhilipp** [microsoft/vscode#172354]
Type: <b>Bug</b>

## Behaviour
Expected:
If I uncheck the breakpoint option "Uncaught Exceptions", it should remain unchecked even after restarting vs code.
Actual:
The option is always activated again.

## Steps to reproduce:
* start vscode
* Uncheck "Uncaught Exceptions"
* Restart vs code
* Start debugging
* -> Option is checked again

_____________________

I originally posted this ticket for the vs code python extension. However, it seems to be a vs code problem: 
 https://github.com/microsoft/debugpy/issues/1174
_____________________
VS Code version: Code 1.74.3 (97dec172d3256f8ca4bfb2143f3f76b503ca0534, 2023-01-09T16:59:02.252Z)
OS version: Windows_NT x64 10.0.19045
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10875H CPU @ 2.30GHz (16 x 2304)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.64GB (22.80GB free)|
|Process Argv|. --enable-proposed-api genuitecllc.codetogether|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (17)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|13.3.1
vscode-svgviewer|css|2.0.0
xml|Dot|2.5.1
vscode-todo-plus|fab|4.19.0
git-graph|mhu|1.30.0
autopep8|ms-|2022.2.0
isort|ms-|2022.8.0
pylint|ms-|2022.6.0
python|ms-|2022.20.2
vscode-pylance|ms-|2023.1.30
remote-ssh|ms-|0.94.0
remote-ssh-edit|ms-|0.84.0
remote-wsl|ms-|0.72.0
remote-explorer|ms-|0.0.3
d2|Ter|0.6.0
errorlens|use|3.6.0
vscode-icons|vsc|12.2.0

</details>

**Comment by roblourens** [comment]
Nice find. I follow these steps

- Debug a .py file
- Uncheck all exception breakpoints
- Reload the window
- Debug it again
- "Uncaught exceptions" gets checked again

We don't restore exception breakpoints from storage properly, so they are not matched to the new breakpoints correctly, so the default overrides your selection again.
