### ISSUE TITLE
window control buttons offside

### ISSUE THREAD

**Issue by andreamah** [microsoft/vscode#172312]
![Recording 2023-01-24 at 14 59 59](https://user-images.githubusercontent.com/31675041/214440465-2b27f0c4-72bf-44cd-8ff3-502a1c9b9dd3.gif)

1. have unsaved notebook file focused.
2. ensure that the window isn't full-screen
3. reload the window
4. notice that the corner buttons are not sized correctly. :bug:

**Comment by rzhao271** [comment]
Unable to repro now.
