### ISSUE TITLE
Usability: NVDA is not announcing the suggestions in the settings.json editor for change in user settings.

### ISSUE THREAD

**Issue by WiproPSAccTest** [Microsoft/vscode#17234]
VS Code Version: 1.6.1
OS Version:1607
NVDA version:-2016.2.1

**Steps to Reproduce:**
Prerequisite: Node.js and git repository need to be installed.
1.Open Visual studio code editor.
2.Open the command Pallet by pressing "F1" key and type "setting".
3.Using down-arrow key select user setting from the option and you will be redirected  to "settings.json"  editor.
4.Type the word "Auto " in the "settings.json"  editor.
 and select one of the suggestion given by the vs code editor.

**Expected result:**
NVDA should recite the suggestions correctly.

**Actual Result:**
NVDA is not announcing the suggestions in the settings. json editor.

**User Impact:**
Screen Reader user doesn't get to know the suggestions available as it's not getting announced.

**Attachments:**

![nvda_speechviewer_usersetting](https://cloud.githubusercontent.com/assets/22956130/21212861/66303c3a-c2b6-11e6-8f21-4972a85ea7c1.jpg)

**Comment by kieferrm** [comment]
Step 2 does not seem to be correct. The screenshot suggests that you triggered intellisense and not the command palette.

**Comment by WiproPSAccTest** [comment]
Step 2 is only to open the command palette. Once you select "User Setting" mentioned in step 3 you will be redirected to "settings.json" editor. Here the issue is related to Intellisense in the "settings.json" editor. Here NVDA is not announcing the suggestions provided by the editor.

**Comment by joaomoreno** [comment]
Can't repro:

![image](https://cloud.githubusercontent.com/assets/22350/25749066/81724e3c-31ad-11e7-9fe4-4f683b0f0f34.png)
