### ISSUE TITLE
Testing terminal link- spaces with "line x col y" not working

### ISSUE THREAD

**Issue by andreamah** [microsoft/vscode#172302]
Testing #172084
I tried the following:
`/home/andrea/Documents/python-test/test.py, line 1, col 2`

And it didn't identify the whole thing as a link. Is this expected?

**Comment by andreamah** [comment]
I also tried 
`"/home/andrea/Documents/python-test/test.py", line 1, col 2` and it didn't work

**Comment by Tyriar** [comment]
![image](https://user-images.githubusercontent.com/2193314/214926592-0c7a56e1-c327-4760-8d1e-45acc1be8dcb.png)

**Comment by Tyriar** [comment]
On a single line works due to the fallback matcher being used:

![image](https://user-images.githubusercontent.com/2193314/214926787-bdb61a54-8d50-42e5-a445-85634b76d7fa.png)
