### ISSUE TITLE
Pasting text in the terminal leads to broken rendering

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#172365]
Testing #172084

macOS, zshell, no terminal settings set (all defaults)

Paste some text in the terminal -> it is badly rendered
As soon as I move the cursor, the rendering gets fixed.

![Screenshot 2023-01-25 at 10 43 24](https://user-images.githubusercontent.com/1926584/214530414-4a6485cf-7fe6-43a6-af42-530b1cf1d17e.png)

**Comment by floooh** [comment]
+1

VSCode 1.75.1, macOS 13.2, zsh 5.8.1 (x86_64-apple-darwin22.0)
