### ISSUE TITLE
User setup 1.75.0 install gets overwritten on restart to 1.74.3

### ISSUE THREAD

**Issue by karthiknadig** [microsoft/vscode#172334]
Testing #172051

1. Install stable 1.74.3 user setup
2. Open some project, and close. Ensure version is 1.74.3
3. Download 1.75.0 user setup and install
4. Open VS Code you will see the gear icon say that you need to restart to update:
![image](https://user-images.githubusercontent.com/3840081/214456735-80e20b53-60d7-431c-8ee6-fa3f78964ecd.png)
![image](https://user-images.githubusercontent.com/3840081/214457099-9c7e481a-39a0-410c-bc34-1615eef8e24c.png)

5. If you restart vscode reverts back to 1.74.3.

**Comment by sandy081** [comment]
Yes it is expected because the 1.75.0 version you downloaded is not a released version and our update service only looks for latest released versions and updates even if it is lower.

CC @joaomoreno

**Comment by joaomoreno** [comment]
Correct, at the time I write this, 1.74.3 is the latest released VS Code version. VS Code will always move to the latest released build, whether that rolls forward or backwards.

If you want to test 1.75.0, disable updates.
