### ISSUE TITLE
tab has to be pressed twice to go back to the terminal buffer from accessibility mode

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#172399]
from  https://github.com/microsoft/vscode/issues/172006#issuecomment-1402678261 @jooyoungseo 

Terminal input -> terminal a11y buffer: only requires one Shift+Tab. However, from terminal a11y back to terminal input requires two tab key press.

**Comment by meganrogge** [comment]
@jooyoungseo, in oss based on the latest main, I press tab once to exit the mode and the normal terminal is focused. do you experience that as well now?

**Comment by jooyoungseo** [comment]
@meganrogge -- This issue has been resolved as tested with the latest main branch.
