### ISSUE TITLE
Usability: NVDA is not reciting the entered code snippet to the program.

### ISSUE THREAD

**Issue by WiproPSAccTest** [Microsoft/vscode#17238]
VS Code Version: 1.6.1
OS Version:1607
NVDA version:-2016.2.1

**Steps to Reproduce:**
Prerequisite: Node.js and git repository need to be installed.
1.Open Visual studio code editor.
2.Using "ctrl+1" key navigate to the first editor.
3.Create an "index.html" file and type "!" + TAB key to create a code snippet with Emmet Syntax.

**Expected result:**
NVDA should recite the entire code snippet that was entered.
Ex:-If we enter the code snippet by typing "!"+TAB, key for html code then NVDA should recite html code  entered.

**Actual Result:**
NVDA is not reciting for the entered code snippet to the program.
Ex:-If we enter the code snippet by typing "!"+TAB, key for html code then NVDA is not reciting anything for the entered code to the program.

**User Impact:**
Screen Reader user doesn't get to know about the Code being added on Hitting "!+Tab" key

**Attachments:**
![nvda_speechviewerinformation_vscodeeditor_codesnippet](https://cloud.githubusercontent.com/assets/22956130/21213046/ee80501a-c2b7-11e6-9996-0014b007aed9.jpg)

**Comment by WiproPSAccTest** [comment]
Verified in Visual Studio Code 1.17.2. Issue is fixed. Hence closing the bug.
![nvda](https://user-images.githubusercontent.com/22956130/33126939-6309c900-cfac-11e7-955d-aa299a9cf2c6.jpg)

**Comment by ramya-rao-a** [comment]
Thanks for getting back to us @WiproPSAccTest
