### ISSUE TITLE
File links in web not correctly linkified

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode#172314]
1. Enable new TS server support in web
2. Shift+click into an absolute filepath in a repo e.g. https://insiders.vscode.dev/github/microsoft/vscode/blob/f2db72909bbc5de082ccb3fd9caf22bee015091b/src/vs/base/common/async.ts#L10
3. :bug: linkified absolute path gets individual path segments linkified, rather than the entire path like in desktop

![image](https://user-images.githubusercontent.com/30305945/214440787-3fbc1b7c-39b5-4f69-bf2d-bbf11eab8003.png)

**Comment by mjbvz** [comment]
This seems to be fixed for me:

<img width="859" alt="Screenshot 2023-12-06 at 11 25 15 AM" src="https://github.com/microsoft/vscode/assets/12821956/a1a62849-5afe-4533-a59e-693fb2489879">

**Comment by joyceerhl** [comment]
Hm, do you know where that `module \"/vscode-vfs/github+...\"` hover text comes from?
