### ISSUE TITLE
Perf: Make output channel logging faster in web

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#172336]
Steps to Reproduce:

1. Set `"typescript.tsserver.log": "verbose"`
2.  On insiders.vscode.dev, open a JS/TS file and type a bunch in the file to trigger TS Server requests
3. Open the output panel and look at the `TypeScript Server log` section

**Bug**
The output log updates slowly and continues updating long after you finish typing

We are using `vscode.OutputChannel`.  I've debugged this and believe that the TS logs all of the information quickly. It seems like the issue is with the display/update of the output channel content in the UI

**Comment by mjbvz** [comment]
I believe the root cause is the `FileLogger`. In particular, every call to the [`FileLogger.log`](https://github.com/microsoft/vscode/blob/9930b1d65a7708deb6ead51e3b9adffd4797694c/src/vs/platform/log/common/fileLog.ts#L47) takes between 150 and 400ms on my machine, and TS makes a large number of log calls per second if you type quickly

**Comment by sandy081** [comment]
Please try this out in tomorrow's insiders.

**Comment by sandy081** [comment]
Fixed by fe8f7385a1b08c01b7d41c7089d346c6b31a0e87

**Comment by mjbvz** [comment]
Thanks. Looking much better now
