### ISSUE TITLE
Terminal follow link hover only shows up when I press cmd

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#172366]
Testing #172084

Hover over the link -> no UI decoration in the terminal.
Only the hover shows when I am holding Cmd.

I am worried that this is undiscoverable, as the only way to figure out that I have to press cmd requires me to already press cmd.
Can we just show this hover on every link hover (not requiring cmd is pressed)

![Screenshot 2023-01-25 at 10 46 52](https://user-images.githubusercontent.com/1926584/214531063-20d14049-9333-43fc-a133-7aa0da1aae62.png)

**Comment by isidorn** [comment]
I was on VS Code Insiders. Should I have used exploration? Did not catch that.

**Comment by Tyriar** [comment]
vscode-insiders will only work on Insiders is what I meant. This should be working, it could be related to the uri format?

**Comment by isidorn** [comment]
Here's the command I run
And this path actually exists (clicking on it opens that folder)
```
echo "vscode-insiders://file/Users/isidor/development/w"
```
