### ISSUE TITLE
Ctrl + C doesn't work anymore (after updating to latest version)

### ISSUE THREAD

**Issue by dehghani-mehdi** [Microsoft/vscode#17232]
- VSCode Version: 1.8.0
- OS Version: Windows 10 x64

In `.html` file when I select some text and hit `ctrl+c`, I got following message, also selected text doesn't copy.

__Update__
Even when `terminal` is closed.

![vscode](https://cloud.githubusercontent.com/assets/9152330/21212710/76f73fc6-c2a4-11e6-8c34-9b7b53b964a7.png)

**Comment by Tyriar** [comment]
I can repro if I select text in the terminal and then close it.

**Comment by Tyriar** [comment]
I've made this a candidate for the recovery build, in the meantime just make sure any selection is gone from the terminal when you close it.

**Comment by Tyriar** [comment]
To verify test these cases on Windows:

- Select text in terminal, close terminal, try copy (ctrl+c) something
- Copy in terminal, paste in terminal
- Copy in terminal, paste in editor

**Comment by dehghani-mehdi** [comment]
You closed this issue, but didn't release the fixed edition.

**Comment by Tyriar** [comment]
This is our process; we assign the issue to a milestone, fix the problem, close the issue and then release the version for that milestone when all the fixes are done.

**Comment by isidorn** [comment]
I can still seldomly repro this

Example steps which always repro for me:
1. Open terminal -> select some text in terminal
2. Focus editor try to ctrl + v in editor -> getting the warning
3. Close the terminal -> still getting the warning

Used win10,  vscode version 5dcb9c5e92029075d86a4f8274dc3af77288abd8

![terminal](https://cloud.githubusercontent.com/assets/1926584/21315216/5866ca04-c5fb-11e6-9a46-34a8c4afd186.gif)
