### ISSUE TITLE
Typing in Italics in the Markup editor causes the text to Jiggle

### ISSUE THREAD

**Issue by bhavyaus** [microsoft/vscode#172486]
Steps to Reproduce:

1. Open a md file
2. Start typing in italics

https://user-images.githubusercontent.com/25044782/214726025-c5bd5bf3-b542-4bf7-b857-ba542bd1670d.mp4

**Comment by mjbvz** [comment]
Unfortunate but it's not clear how you'd reasonably fix this

[Italics can not be closed by space then star](https://spec.commonmark.org/dingus/?text=*a%20b*%0A%0A*a%20b%20*%0A%0A). This means every time you type space, the text is no longer italic. Some markdown editors seem to parse the text like this in a non-conformant way to avoid this but we try to stick to the commonmark spec
