### ISSUE TITLE
Support title bar within native title bar

### ISSUE THREAD

**Issue by TylerLeonhardt** [microsoft/vscode#172464]
Testing #171999

I enabled native tabs and the command center and no command center showed up:
![image](https://user-images.githubusercontent.com/2644648/214697227-adebc5d6-f549-4f22-ab0a-5364f9a07b35.png)

I think the command center should come under the native tabs if it's enabled maybe.

**Comment by bpasero** [comment]
I am not sure about that, there are people that prefer native window title or use native tabs and in those cases we do not have a custom title area to add our controls. Forcing to have yet another row of things (you already have 2 with native tabs I think) seems strange to me.

**Comment by deepak1556** [comment]
Yeah given we cannot draw on the native titlebar, I don't think taking up valuable editor area space for command center seems like a good idea.

**Comment by sbatten** [comment]
Right now command center is not default behaviour so in that case, it could make sense that this was an explicit decision by the user, but if the intent is to have CC as default, I don't think it would be right to show an extra row just for that, especially on macOS where the layout controls are the only other thing in that area.

**Comment by TylerLeonhardt** [comment]
All fair points. I opened this because I predict such an issue, not because I actually want it.

Maybe we revisit if we get other controls in the title bar (like debug).

Or maybe we surface the command center somewhere else. Like an icon to the right of the tabs or something.

**Comment by wesleyboar** [comment]
Related: To deal with this, I opened tabs on macOS VS Code (using a keyboard shortcut while `windows.nativeTabs: false`) and Command Center (via `window.commandCenter: true`), but the UI of tabs and command center overlapped for me (#192801).

**Comment by wesleyboar** [comment]
To avoid adding a new line, could the command center be a tab? When you click on it, instead of opening an editor, your current editor remains open and the command center does what it would have done in another location. The tab could be long enough to hold the layout buttons. But, the more I write this idea, the more I feel it is a misuse of UI patterns...

**Comment by TylerLeonhardt** [comment]
> An alternative would be to implement the tabs in the product itself rather than relying on OS functionality.

We already do this. This issue is specifically about when the user wants to use native tabs. There's a setting to control which tabs experience you get.

**Comment by rickardp** [comment]
> > An alternative would be to implement the tabs in the product itself rather than relying on OS functionality.
> 
> @rickardp We already do this. This issue is specifically about when the user wants to use native tabs. There's a setting to control which tabs experience you get.

I was not aware this functionality existed. I always used native tabs to accomplish this behaviour. How can I group multiple open projects into a single window using tabs, without using native  tabs?

**Comment by TylerLeonhardt** [comment]
> EDIT: It probably goes without saying, but just to clarify: I am not talking about editor tabs, but project tabs, the way the native tabs work

Yep, my bad. This was the clarity I needed. We don't support this today.
