### ISSUE TITLE
Usability: NVDA is not announcing when "Debugging" is started by pressing "F5" key.

### ISSUE THREAD

**Issue by WiproPSAccTest** [Microsoft/vscode#17249]
VS Code Version: 1.6.1
OS Version:1607
NVDA version:-2016.2.1

**Steps to Reproduce:**
Prerequisite: Node.js and git repository need to be installed.
1.Open Visual studio code editor.
2.open any file and using "Ctrl+1" key  navigate to the  first vs code editor.
3.Adding a "breakpoint" to the line of code By pressing  "F9".
4.Start debugging by pressing "F5",key and observe NVDA behavior.

**Expected result:**
NVDA should recite like "Debugging started" when user press "F5" key  to start debugging.

**Actual Result:**
NVDA is not reciting anything when debugging started by pressing "F5" key.
Note:-The same issue is observed when debugging is "Paused" and "Stopped"
Note:-Inconsistent NVDA behavior is observed sometimes.

**User Impact:**
Screen Reader user doesn't get to know whether the Debugging is started or not as no announcement after "Debugging" has been started.

**Attachments:**
![narratorbuddyinformation_visualstudiocodeeditor_debugging](https://cloud.githubusercontent.com/assets/22956130/21214115/c1e10020-c2be-11e6-9ea8-8fe82a9edf7a.jpg)
![nvda_speechviewerinformation_vscodeeditor_debugging](https://cloud.githubusercontent.com/assets/22956130/21214116/c1e801e0-c2be-11e6-9e91-433dbe0c46e9.jpg)

**Comment by isidorn** [comment]
Works for me 
Also similar reasons to https://github.com/Microsoft/vscode/issues/17251

Both of these might be bugs with NVDA and have nothing to do with VSCode.
@WiproPSAccTest do you also see inconsistent NVDA behavior when trying it in other apps - for instance Microsoft Word?

![screen shot 2016-12-20 at 12 17 48](https://cloud.githubusercontent.com/assets/1926584/21348649/635a9fd6-c6ae-11e6-9f89-125316c38da0.png)

**Comment by chrisdias** [comment]
NVDA 2017.2
Insiders 1.13.0-insiders commit 3a6eda (5/31/2017)

Reads "debugging started"

![image](https://user-images.githubusercontent.com/1487073/27307840-9ab86db0-5500-11e7-8638-0f171d5db5b5.png)
