### ISSUE TITLE
macOS using native tabs... there's no keybinding to tab through them

### ISSUE THREAD

**Issue by TylerLeonhardt** [microsoft/vscode#172462]
Testing #171999

Both `ctrl`+`tab` and `cmd`+`shift`+`]` change the tab _inside_ of VS Code but it would be nice if there was a keybinding the change the native tabs.

**Comment by deepak1556** [comment]
We have `workbench.action.showPreviousWindowTab` and `workbench.action.showNextWindowTab` you can configure.
