### ISSUE TITLE
Usability: NVDA is not reciting for the download notification in the https://code.visualstudio.com/Download link.

### ISSUE THREAD

**Issue by WiproPSAccTest** [Microsoft/vscode#17243]
VS Code Version: 1.6.1
OS Version:1607
NVDA version:-2016.2.1

**Steps to Reproduce:**
1.Open the URL https://code.visualstudio.com/Download.
2.Download Visual studio code setup for Windows and save it.

**Expected result:**
NVDA should recite name of the download notification for the vs code editor installer in the https://code.visualstudio.com/Download.

**Actual Result:**
NVDA is not reciting the name of the download notification for the vs code editor installer in the  https://code.visualstudio.com/Download link

**User Impact:**
Screen Reader user doesn't get to know about the Notification appeared for Downloading VS Code Editor and They can't proceed further

**Attachments:**
![narratorbuddyinformation_vscodeeditor_downloadnotification](https://cloud.githubusercontent.com/assets/22956130/21213397/0eff7364-c2ba-11e6-8fd7-097bd5f48fba.jpg)
![nvda_speechviewerinformation_vscodeeditor_downloadnotification](https://cloud.githubusercontent.com/assets/22956130/21213396/0ef82244-c2ba-11e6-98b1-55af4bffcedf.jpg)

**Comment by waderyan** [comment]
thank you for opening this issue. We track website issues in a separate private repo. I am moving this issue to that repo.

**Comment by WiproPSAccTest** [comment]
@waderyan The issue still exist.

**Comment by waderyan** [comment]
@WiproPSAccTest thank you for the follow up. We are gearing up for a large accessibility push next iteration. This issue is on our list.
