### ISSUE TITLE
previous prompt bleeds through in GitHub Issue Notebooks

### ISSUE THREAD

**Issue by TylerLeonhardt** [microsoft/vscode#172417]
Steps:
* Clone VS Code Repo or open with GitHub Repos
* Install GHIN (make sure you haven't logged in to it)
* Open a notebook like the my-endgame.github-issues notebook
* Run
* See "log in" prompt and go through login flow
* Run notebook again

See this:
![image](https://user-images.githubusercontent.com/2644648/214636309-12824e2d-4302-4372-b25b-d47928bde789.png)

Possibly related... further up in the file, I notice some bad formatting of issues:
![image](https://user-images.githubusercontent.com/2644648/214637102-c482a928-601c-47be-825e-f1223b98bfbb.png)

Not sure if this is GHIN or Notebooks issue.

**Comment by TylerLeonhardt** [comment]
![image](https://user-images.githubusercontent.com/2644648/214656702-28b1d92c-b5d2-412f-920b-def070b14262.png)

another example 😅

**Comment by rebornix** [comment]
It looks much worse. It seems we are not even picking the right mime type.

**Comment by rebornix** [comment]
Verifier, with the next Insiders

* Open endgame notebook
* Run all cells from the top toolbar
* On the first cell which has outputs, click the `...` icon -> Change Presentation -> Choose Markdown
* Run all cells again
* Scroll the notebook to the end, there should be no outputs overlapped on each other (or output overlapping with markdown cell )
