### ISSUE TITLE
Allow extension vsix file to be saved

### ISSUE THREAD

**Issue by motobud31** [microsoft/vscode#172494]
I work on an off-line network.  I know that I can download the extension from the marketplace and transfer it to my off-line network and install it into vscode.  It would be easier if I can setup vscode on an internet connected machine with the extensions I also use on my off-line network and allow it to auto-save the vsix file for the extensions that it downloads.  Then all I have to do is copy the newer vsix files to the off-line network verses having to visit each extension page and manually download it.

**Comment by sandy081** [comment]
Extensions VSIXs are downloaded in the following location - 

Open User Data folder where settings are stored. In the parent of that folder you can find `CachedExtensionVSIXs` folder.

**Comment by motobud31** [comment]
Thanks!  I was not aware of this.

**Comment by motobud31** [comment]
Does the cache keep a list of all that are installed, or just the ones that were downloaded for the last time an update was performed?  After some extensions were updated, some of the vsix files for other extensions were removed.  Also, it looks like the ".vsix" extension is removed from the file name.

**Comment by sandy081** [comment]
Yes, this is a temporary cache. If you want a permanent storage VSIXs, I would recommend to download them manually from Marketplace and store them.
