### ISSUE TITLE
My commits don't show up.

### ISSUE THREAD

**Issue by Jhonmacc** [microsoft/vscode#172457]
My Vscode in the Source Control tab my commints never appear or the commints tab is in an infinite hole and never brings the performed commints or history to perform code comparisons.
I already reinstalled and vscode and removed all extensions but unfortunately without success.

- LastVersion vscode 2023-01-25
- SO: Windows 11 

<img width="294" alt="image" src="https://user-images.githubusercontent.com/20972080/214691401-1185c223-adf7-4efe-92ed-743eb4f065b0.png">

**Comment by gjsjohnmurray** [comment]
I think those view panels come from an extension, perhaps GitLens.

One way to confirm is to run the Start Extension Bisect command.

**Comment by lszomoru** [comment]
That is correct. The "Commit" view is being contributed by the GitLens extension. Can you please file an issue in the [extension's repository](https://github.com/gitkraken/vscode-gitlens/issues) in order to get assistance from the authors of the extension. Thanks!

**Comment by Jhonmacc** [comment]
Wonderful! I understand thank you!
