### ISSUE TITLE
in diff view, line selection shouldn't happen on cursor move

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#172458]
Enable screen reader mode, click in a diff view, see that the line is selected. It should only be selected when you navigate changes via `Go to next/previous difference`

https://user-images.githubusercontent.com/29464607/214692483-fa292661-80b7-4855-bac4-be9669a1cca9.mov

**Comment by meganrogge** [comment]
@jooyoungseo, not sure if you've noticed this behavior, but it's unnecessary to select the text because on cursor move, the screen reader does read the correct thing already. it was messing w my ability to edit from within the diff view

**Comment by jooyoungseo** [comment]
@meganrogge -- Yes, indeed. Selection is unnecessary upon standard Up/DownArrow navigation.

**Comment by meganrogge** [comment]
👍🏼 this will be fixed in tomorrow's insider's
