### ISSUE TITLE
Usability: NVDA is not reciting any information when "Rename Symbol" is applied to the any code for changing.

### ISSUE THREAD

**Issue by WiproPSAccTest** [Microsoft/vscode#17247]
VS Code Version: 1.6.1
OS Version:1607
NVDA version:-2016.2.1

**Steps to Reproduce:**
Prerequisite: Node.js and git repository need to be installed.
1.Open Visual studio code editor.
2.open any file and using "Ctrl+1" key  navigate to the  first vs code editor.
3.Select any code and press"F2" to rename the code.

**Expected result:**
NVDA should provide information when rename is done.

**Actual Result:**
NVDA is not announcing  when renaming is completed.

**User Impact:**
Screen Reader user doesn't get to know whether the symbol got Renamed or not as no announcement after "Rename Symbol" has been applied.

**Attachments:**
![nvda_speechviewerinformation_vscodeeditor_renamesymbol](https://cloud.githubusercontent.com/assets/22956130/21213863/3332385e-c2bd-11e6-8996-d6cf4b7466cf.jpg)

**Comment by alexandrudima** [comment]
@jrieken please use:
```
import { alert } from 'vs/base/browser/ui/aria/aria';
```

and invoke that when rename is applied or cancelled.
