### ISSUE TITLE
Usability: NVDA is not announcing when "Breakpoint" is added to the code.

### ISSUE THREAD

**Issue by WiproPSAccTest** [Microsoft/vscode#17248]
VS Code Version: 1.6.1
OS Version:1607
NVDA version:-2016.2.1

**Steps to Reproduce:**
Prerequisite: Node.js and git repository need to be installed.
1.Open Visual studio code editor.
2.open any file and using "Ctrl+1" key  navigate to the  first vs code editor.
3.Adding a "breakpoint" to the line of code By pressing  "F9" and observe the NVDA behavior.

**Expected result:**
NVDA should recite like "breakpoint added to the line of code n".

**Actual Result:**
NVDA is not reciting any information when any breakpoint is added to the line of code.
Note:-Inconsistent NVDA behavior is observed sometimes.

**User Impact:**
Screen Reader user doesn't get to know whether the Breakpoint is added or not as no announcement after "Breakpoint" has been applied.

**Attachments:**
![narratorbuddyinformation_visualstudiocodeeditor_breakpoint](https://cloud.githubusercontent.com/assets/22956130/21214000/f9e70e02-c2bd-11e6-84c6-a7944b13a645.jpg)
![nvda_speechviewerinformation_vscodeeditor_breakpoint](https://cloud.githubusercontent.com/assets/22956130/21213999/f9e572e0-c2bd-11e6-9ab0-a2bef8777853.jpg)

**Comment by isidorn** [comment]
Works for me
Same as my comment here https://github.com/Microsoft/vscode/issues/17249#issuecomment-268218869

![screen shot 2016-12-20 at 12 19 41](https://cloud.githubusercontent.com/assets/1926584/21348703/9dfd3054-c6ae-11e6-8c32-47a143c94664.png)

**Comment by WiproPSAccTest** [comment]
@isidorn  The issue is fixed in vs code editor 1.8.1.
