### ISSUE TITLE
quick fix menu closes immediately

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#172477]
https://user-images.githubusercontent.com/29464607/214711871-3a4a25fb-df53-43a7-a26f-710fd9d39c65.mov

**Comment by meganrogge** [comment]
note that disabling screen reader mode did not help

**Comment by meganrogge** [comment]
note how it's getting called twice for every one time I do `command+.`
https://user-images.githubusercontent.com/29464607/214712266-7b59879b-c865-415e-a162-b648e4efbc60.mov

**Comment by meganrogge** [comment]
cannot repro

**Comment by joaomoreno** [comment]
@meganrogge It's unclear what happened here. If this was closed as "cannot repro", should the `bug` label be removed? It's currently showing up in the `Verifiable Fixes` query.
