### ISSUE TITLE
Notebook diff editor fails to open after clearing cell outputs

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode#172426]
1. Open this notebook https://github.com/microsoft/vscode/blob/6e37e47de072fbf4d47df02a15cfb4c487dac639/extensions/vscode-api-tests/testWorkspace/test.ipynb
2. Clear the cell outputs
3. Open the notebook diff from the SCM viewlet
4. :bug: diff fails to open with the following error

<img width="372" alt="image" src="https://user-images.githubusercontent.com/30305945/214651136-ce0a208c-e1c2-4dda-94ec-9bcc8aaeba1d.png">

**Comment by rebornix** [comment]
@joyceerhl do you reproduce this issue 100% of the time? I didn't reproduce this issue on local macOS or https://insiders.vscode.dev/github/microsoft/vscode. Also can you please share errors from the Dev Tools if there is any. I'd like to know the call stack if it's printed there.

**Comment by joyceerhl** [comment]
I have a consistent repro as follows (not sure if it's minimal)
1. Open that notebook
2. Duplicate the cell so that there are at least 2 changes
3. Clear cell output for first cell
4. Use Show Previous Change and Show Next Change a couple times
5. Revert all notebook changes
6. Clear cell output for the first cell
7. Reopen the diff from SCM view
8. :bug: diff editor doesn't open

**Comment by rebornix** [comment]
@joyceerhl very good reproduce steps. We have this issue for quite some time but randomly, and I had no idea what's going on. From the error thrown directly, we don't have a model for a particular cell, aka out of index issue. The truth is 

> 5. Revert all notebook changes

When this step runs, we failed to send the change event to the web worker as we forgot to convert cell output to dto. Thus the diff result coming back from the web worker is always wrong as the model is not longer up to date.

Kudos to your bug report ❤️  @joyceerhl

**Comment by joyceerhl** [comment]
@rebornix I am now seeing a different problem where the notebook model doesn't update at all after making a change and reverting it from the scm view:

https://user-images.githubusercontent.com/30305945/214960591-08668ea9-a83b-4fdb-937f-d1a8b6a148fc.mp4
