### ISSUE TITLE
${rootNameShort} shows (Workspace) for remote SSH workspaces

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#172429]
Testing https://github.com/microsoft/vscode/issues/145238

<img width="628" alt="image" src="https://user-images.githubusercontent.com/2230985/214655239-ea5f6843-1181-4541-9fa4-bebe746ccebe.png">

**Comment by bpasero** [comment]
@connor4312 you seem to be inside an "Untitled Workspace", please read https://code.visualstudio.com/docs/editor/workspaces. So the suffix I think is expected.

**Comment by connor4312** [comment]
ah, correct. `rootNameShort` works as specified once I save it.
