### ISSUE TITLE
Usability: NVDA is not reciting when "Format Code" is applied to the code.

### ISSUE THREAD

**Issue by WiproPSAccTest** [Microsoft/vscode#17246]
VS Code Version: 1.6.1
OS Version:1607
NVDA version:-2016.2.1

**Steps to Reproduce:**
Prerequisite: Node.js and git repository need to be installed.
1.Open Visual studio code editor.
2.open any file and using "Ctrl+1" key  navigate to the  first vs code editor.
3.Using "Alt+Shift+F", key apply "Format Code" to the existing code. 

**Expected result:**
NVDA should recite the information when "Format Code" is applied to the existing code.
EX:-If we apply by using "Alt+Shift+F" key then nvda should recite like "Format Code" is applied.

**Actual Result:**
NVDA is not announcing any information when format code is being applied.

**User Impact:**
Screen Reader user doesn't get to know whether the code got formatted or not as no announcement after "Format code" has been applied.

**Attachments:**

![nvda_speechviewerinformation_vscodeeditor_formatcode](https://cloud.githubusercontent.com/assets/22956130/21213775/b406e82c-c2bc-11e6-9a23-4f39ad3f8aac.jpg)

**Comment by alexandrudima** [comment]
@jrieken please use:
```
import { alert } from 'vs/base/browser/ui/aria/aria';
```

and invoke that when rename is applied or cancelled. Please LMK if you'd want me to do it.
