### ISSUE TITLE
【Big bug】Every time you copy a large file, it will open! ! !

### ISSUE THREAD

**Issue by CrazyBoyM** [microsoft/vscode#172490]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.74.3
- OS Version: Windows_NT x64 10.0.22621

Steps to Reproduce:

1. copy a large file (>3G) from one folder to another
2. then the file will be default open !!!

I use the vscode on my remote server(network connect is too slow to load such a big file), and it made me crazy, hope to fix it.
Every time I have to restart my vscode.

**Comment by CrazyBoyM** [comment]
有时候我不小心点到了这样一些大文件（通常是神经网络权重），我也不得不重启我的vscode。  
Sometimes I accidentally click on such large files (usually neural network weights), and I have to restart my vscode.

**Comment by gjsjohnmurray** [comment]
See #169433 for information about a change that is coming in 1.75, which is currently Insiders and expected to release as Stable next week.

**Comment by CrazyBoyM** [comment]
> See #169433 for information about a change that is coming in 1.75, which is currently Insiders and expected to release as Stable next week.

thanks~
