### ISSUE TITLE
Emmet problems in PHP (even with all extensions disabled)

### ISSUE THREAD

**Issue by COD3BREAK3R** [microsoft/vscode#172567]
Does this issue occur when all extensions are disabled?: Yes

Versión: 1.74.3 (user setup)
OS: Windows_NT x64 10.0.17763

Steps to Reproduce:

1. Open a PHP file with this structure:

```
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta http-equiv="x-ua-compatible" content="ie=edge" />
    <title>Docuplay</title>
    <!-- Font Awesome -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css" rel="stylesheet" />
    <!-- Google Fonts Roboto -->
    <link rel="stylesheet"
        href="https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;500;700;900&display=swap" />
    <!-- MDB -->
    <link rel="stylesheet" href="/MDB5/css/mdb.min.css" />
    <link rel="stylesheet" href="/MDB5/css/colores/colores.css">

</head>

<body>

    <!-- MDB5 -->
    <script type="text/javascript" src="/MDB5/js/mdb.min.js"></script>
</body>

</html>
```

2. Try to use link:css inside `head `tag and you can see not work, not even pressing tab (also, the autocomplete suggestion does not appear).

2.1. Type an emmet abbreviation like `div` anywhere in the document and you can see that vscode doesn't suggest autocompletion of it, only autocompletes pressing tab, but this example in a html file work fine without problems.

Emmet config:

```
"emmet.excludeLanguages": ["markdown"],
    "emmet.includeLanguages": {
        "php": "php"
    },
    "emmet.showSuggestionsAsSnippets": true,
    "emmet.useInlineCompletions": true,
    "emmet.preferences": {
    
    }
```
Bonus: The only way to get Emmet shortcuts to work in PHP is using the extension: DEVSENSE.profiler-php-vscode. This should not happen and shows that emmet is malfunctioning

I repeat, the emmet problem occurs even with all extensions disabled, so it is not caused by any extensions.

**Comment by rzhao271** [comment]
For the `emmet.includeLanguages` setting, it should say `"php": "html"` if you want HTML completions in PHP files. Let me know if that works for you.

**Comment by COD3BREAK3R** [comment]
> For the `emmet.includeLanguages` setting, it should say `"php": "html"` if you want HTML completions in PHP files. Let me know if that works for you.

Yes, after making that modification everything works correctly, thanks!
