### ISSUE TITLE
`Profiles: delete profile` enter key just closes the quick pick

### ISSUE THREAD

**Issue by amunger** [microsoft/vscode#172558]
Steps to Reproduce:

1. create an empty profile - `Profiles: create an empty profile`
2. run `Profiles: delete profile`
3. use the arrow keys to highlight the newly created profile and press enter
:bug: quick-pick closes, profile is not deleted

**Comment by sandy081** [comment]
Delete profile shows a quick pick with checkboxes and pressing enter in the quick pick without selecting anything will not select any entry. You have to use `space` to select an item and then press enter.

**Comment by TylerLeonhardt** [comment]
Yeah this is to allow a fast keyboard-only experience something that we try to strive for in the quick pick. I wonder if there is room for some visual cues to help. Maybe we could add to the placeholder with `Enter to accept selections. Spacebar to toggle`

**Comment by TylerLeonhardt** [comment]
what do you think @daviddossett?

I suppose we could also change the behavior that ENTER, when highlighting an item in the list, toggles that item instead... but then you'd have to go all the way to the top to hit ENTER (or we'd need to introduce CTRL+ENTER or something).

**Comment by daviddossett** [comment]
Using `space` to toggle checkboxes is a fairly typical—if not standard—behavior. I think this protects people from accidentally hitting enter and deleting a profile.

One thing to think about @TylerLeonhardt: should the multi-select quick picks feature a behavior where the submit button isn't enable until a selection is made? This would bring things closer to a typical form + submit behavior.

**Comment by TylerLeonhardt** [comment]
> Although I suppose there could be cases where nothing is selected and you still want to submit. So perhaps it makes sense as is.

Yeah seems like a reasonable scenario. Selected checkboxes don't equate to acceptance IMO

**Comment by TylerLeonhardt** [comment]
Closing as as designed.
