### ISSUE TITLE
Offer "Expand All" in Comments view

### ISSUE THREAD

**Issue by hermannloose** [microsoft/vscode#172539]
The Comments view provides a **Collapse All** button to collapse all rows in the view so that only filenames remain visible.

<img width="590" alt="Screenshot 2023-01-26 at 16 12 46" src="https://user-images.githubusercontent.com/163766/214872821-43aceb97-ca4a-4c7d-881f-dd26499f6c40.png">

https://github.com/microsoft/vscode/blob/d132035d6b22c80cc78bf3ab50c24f05cb6fbdcc/src/vs/workbench/contrib/comments/browser/commentsView.ts#L452

When all rows are collapsed, there is no corresponding **Expand All** button to see the conversations for each file at a glance; our users are asking for one.

#85428 implemented this kind of functionality for the Search view. For the Comments view, it should be simpler, since there is only a single level of nesting.

We would be happy to contribute a PR if this sounds like a useful addition.

cc @JonasMa @laurentlb

**Comment by alexr00** [comment]
I would accept a PR for this!

**Comment by hermannloose** [comment]
I got started on this in https://github.com/hermannloose/vscode/commit/589452e7ca902ee2297a12f5b43af57932c5358d. I don't see any unit tests for the Comments API overall, not sure if I am looking in the right place, or if I should simply be thorough in running through a few key scenarios manually when running locally?

**Comment by alexr00** [comment]
If you wanted to add tests I would greatly appreciate it. However, since there are currently no tests then yes, simply running through a few key scenarios manually will be enough to verify.
