### ISSUE TITLE
ive always wanted to use VSCode but it has never worked for me. 

### ISSUE THREAD

**Issue by Karan1562** [microsoft/vscode#172579]
<img width="1440" alt="13" src="https://user-images.githubusercontent.com/96478176/214934239-8b40fc5d-c729-43ec-871e-01d3cb670ebd.png">
<img width="1440" alt="14" src="https://user-images.githubusercontent.com/96478176/214934299-d4507e4f-735d-499d-b4b2-dfef0ea15edf.png">

<img width="1440" alt="12" src="https://user-images.githubusercontent.com/96478176/214934101-0ca7861d-2bb3-4840-8548-515a936ab913.png">

Does this issue occur when all extensions are disabled?: Yes/No

Whenever I click on the run button VS code doesnt behave properly and shows this (i have attached photos , pls help and correct this )

**Comment by meganrogge** [comment]
pls create an issue in the c++ extension's repo

**Comment by Karan1562** [comment]
> 

how can you pls explain how to proceed ?
