### ISSUE TITLE
Terminal accessibility - accessibility model rendering issue

### ISSUE THREAD

**Issue by lszomoru** [microsoft/vscode#172513]
Testing #171862

Terminal
<img width="2003" alt="image" src="https://user-images.githubusercontent.com/3372902/214820879-63b878c0-b745-4804-8b11-5fcd50d8576e.png">

Terminal (accessibility mode)
* Scrollbar location seems off
* There is old content on the right side of the scrollbar
<img width="2001" alt="image" src="https://user-images.githubusercontent.com/3372902/214821332-71dc7231-34a8-4615-9c6f-a8bd8e18ebe2.png">

**Comment by Tyriar** [comment]
@meganrogge we might also want to keep the empty new lines?

**Comment by meganrogge** [comment]
don't set the width

**Comment by meganrogge** [comment]
We already don't set the width 🤔

**Comment by Tyriar** [comment]
@meganrogge i removed the width in the linked xterm.js change

**Comment by meganrogge** [comment]
this is fixed with that change
