### ISSUE TITLE
Stick scroll blends into editor contents with high contrast theme

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#172570]
Type: <b>Bug</b>

1. Enable stick scroll
2. Switch to high contrast
3. Scroll down in a file

**Bug**
There is no contrast between the stick scroll content and the normal editor content:

![Screenshot 2023-01-26 at 10 31 17 AM](https://user-images.githubusercontent.com/12821956/214920489-ffc849cc-3c24-479f-8412-15f65a98d62a.png)

Related #157185

VS Code version: Code - Insiders 1.75.0-insider (Universal) (07d6f5b35fac559504dec65e3073d796b2d25a55, 2023-01-26T05:22:17.192Z)
OS version: Darwin x64 22.2.0
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|2, 2, 2|
|Memory (System)|32.00GB (0.02GB free)|
|Process Argv|--crash-reporter-id 48781ca2-1705-4f64-9bab-325055aab55d|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by aiday-mar** [comment]
For verification:

1. Enable sticky scroll, switch to high-contrast and scroll down the file.
2. You should see a border on the bottom of the sticky scroll widget

**Comment by bpasero** [comment]
I see it in dark theme but not light high contrast:



![Image](https://user-images.githubusercontent.com/900690/220365009-e4025da9-a60e-4c18-8a5d-3abe2301db68.png)
