### ISSUE TITLE
Usability: NVDA is not reciting  names for the options available for replace preview results.

### ISSUE THREAD

**Issue by WiproPSAccTest** [Microsoft/vscode#17255]
VS Code Version: 1.6.1
OS Version:1607
NVDA version:-2016.2.1

**Steps to Reproduce:**
Prerequisite: Node.js and git repository need to be installed.
1.Open VS code editor.
2.Navigate to the "Search" side bar area.
3.Enter the  word that need to be searched in the "search" edit box and press "enter" key.
4.Enter the word that need to be replaced in the "Replace" edit box and press "enter" key to show results.

**Expected result:**
1.NVDA should recite the complete word that was entered for search and replace.
2.NVDA should read out the names for all the results available in the replace preview results. 

**Actual Result:**
1.NVDA is not reciting entire word that was  entered for search and replace.
2.NVDA is only reciting the name for the first result and no narration for all other results available in the replace preview results.
Narrator Behavior:
Narrator is properly Reciting the Replace Results (See Screenshot)

**User Impact:**
Screen Reader user doesn't get to know about the available Replace Preview Results.

**Attachments:**
![nvda_speechviewerinformation_vscodeeditor_searchreplace](https://cloud.githubusercontent.com/assets/22956130/21214370/63a424d6-c2c0-11e6-8304-b8e3104a56d7.jpg)

**Comment by rbenson** [comment]
@sandy081 shouldn't this be treated like #17256?
