### ISSUE TITLE
vscode.debug.removeBreakpoint does not work quickly after startup

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#172598]
An edge case to be sure. Found while testing https://github.com/microsoft/vscode/issues/169639

1. Add `vscode.debug.removeBreakpoints(vscode.debug.breakpoints);` to the helloworld extension
2. Debug. Set breakpoints in the window.
3. Reload, and immediately trigger the "Hello World" command
4. Breakpoints are not removed 🐛 

(but they are if I wait a second before triggering the command)

**Comment by connor4312** [comment]
This isn't really fixable with the current API. Sending breakpoints to the extension host is async, where getting breakpoints is sync, so `vscode.debug.breakpoints` is just initially empty. Very much an edge case, not worth dealing with.

**Comment by roblourens** [comment]
Well, it's also https://github.com/microsoft/vscode/issues/169699

**Comment by connor4312** [comment]
Yea, I think we should just sync this eagerly. Breakpoints is not going to be much data.
