### ISSUE TITLE
TelemetrySender.sendEventData must be a function

### ISSUE THREAD

**Issue by andreamah** [microsoft/vscode#172596]
<img alt="image" src="https://user-images.githubusercontent.com/31675041/214976212-68791b38-3eac-4d99-9dfb-1b6ce289170f.png">

When running `Remote Repositories: Open Remote Repository`, I get the above error. I'm on Remote Repositories 
v0.27.2023012601.

**Comment by joyceerhl** [comment]
Are you on prerelease Remote Repositories, GitHub Repositories, and Azure Repos?

**Comment by andreamah** [comment]
Oh, looks like I was not on the prerelease of GH Repos and didn't have Azure Repos installed. Thanks!
