### ISSUE TITLE
Usability: NVDA is not reciting any information when "Integrated Terminal"  is opened.

### ISSUE THREAD

**Issue by WiproPSAccTest** [Microsoft/vscode#17254]
VS Code Version: 1.6.1
OS Version:1607
NVDA version:-2016.2.1

**Steps to Reproduce:**
1.Open Visual studio code editor.
2.Using "Ctrl+`" key open the Integrated Terminals.
3.Write down the command "node " with file name  and run the command.
4.Look at the output for the command

**Expected result:**
NVDA should recite when "Integrated Terminal" is opened and also recite for the output for the command that are executed.

**Actual Result:**
NVDA is not reciting when "Integrated Terminal" is opened and also not reciting the output for the executed command.

**User Impact:**
Screen Reader user doesn't get to know that Integrated Terminal is opened

**Attachments:**
![nvda_speechviewerinformation_vscodeeditor_terminalservices](https://cloud.githubusercontent.com/assets/22956130/21214304/d5ba2878-c2bf-11e6-9e31-2760b138386f.jpg)

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/8339

**Comment by WiproPSAccTest** [comment]
@Tyriar  The issue is still reproducible in both the vs code editor Insider and vs code editor 1.8.1 edition

**Comment by Tyriar** [comment]
Yes, it was reported previously in #8339
