### ISSUE TITLE
Opening settings.json on a new installation results in an error

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#172565]
1. (in my case) make a brand new ubuntu 22.04 VM
2. snap install code-insiders
3. Open Insiders and then go **Open User Settings (JSON)**
4. Notice an error, and lack of completions 🐛 

<img width="606" alt="image" src="https://user-images.githubusercontent.com/2230985/214915437-3490479f-53e8-40d1-81df-d8351b707cd0.png">

**Comment by aeschli** [comment]
I'm not able to reproduce with the given steps.

If you see it again, can you check if there's something in the dev tools console?
Something must have blocked the internal TextModelContentProvoder from being registered or opened.
https://github.com/microsoft/vscode/blob/7a04589c1674774e2a4494497ecce79318fbe85f/src/vs/workbench/contrib/preferences/common/preferencesContribution.ts#L107

**Comment by connor4312** [comment]
It works today 🤷‍♂️
