### ISSUE TITLE
"Run and Debug" button not working properly

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#172550]
Open a folder with no launch.json, open a .js file, click Run and Debug and pick node.js, nothing happens

@connor4312, this is from https://github.com/microsoft/vscode/pull/170652. We are ignoring the `type` parameter and looking at `config.type` only which is empty in this case.

**Comment by TylerLeonhardt** [comment]
![image](https://user-images.githubusercontent.com/2644648/215169129-ea9ad02b-6953-49c0-ba42-940e332d682e.png)
LGTM
