### ISSUE TITLE
Terminal accessibility -  entering accessibility mode scrolls content away

### ISSUE THREAD

**Issue by lszomoru** [microsoft/vscode#172512]
Testing #171862

1. Have a terminal window that has a lot of content so that a scroll bar is shown
2. With the Terminal focused, and the cursor on the last line of the terminal press `Shift+Tab`

Expected: Terminal enters accessibility mode but content is not scrolled
Actual: Terminal enters accessibility mode and the content is scrolled away

**Comment by meganrogge** [comment]
What am I not doing here?

https://user-images.githubusercontent.com/29464607/214889381-95490a43-4170-4bb8-9d9d-57297cf377c2.mov

**Comment by lszomoru** [comment]
https://user-images.githubusercontent.com/3372902/214899300-d5858e91-9ed1-482f-a0c8-23e3f4179f3a.mov

**Comment by meganrogge** [comment]
we now have the accessible view
