### ISSUE TITLE
TS project wide IntelliSense on web is slow due to stat calls

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#172597]
1. With `"typescript.experimental.tsserver.web.enableProjectWideIntellisense": true`
1. Visit https://insiders.vscode.dev/github/microsoft/vscode-markdown-languageservice?vscode-coi=
2. Open a TS file

**Bug**
The repo index downloads quickly but TS initialization takes a long time

From a profile, I noticed that some `stat` calls from the TS Server take between 200 and 400ms:

![Screenshot 2023-01-26 at 4 20 24 PM](https://user-images.githubusercontent.com/12821956/214979627-c46a43b0-dead-4563-9ee8-b76f6891e828.png)

I also noticed that we seem to be making network requests which invoke `getRepository` for a bunch of repos with names that look like file paths.

![Screenshot 2023-01-26 at 4 37 17 PM](https://user-images.githubusercontent.com/12821956/214981298-c2fc24e6-fe6f-4a32-92d9-b1c794480fe8.png)

Following this further, I noticed the `updateOpen` request on JS/TS sends over two copies of every file:

```
/vscode-vfs/github/microsoft/vscode-markdown-languageservice/src/types/range.ts
/github/github/microsoft/vscode-markdown-languageservice/src/types/range.ts
```

Note that these paths are transformed into URIs that look like:

```
vscode-vfs://github/microsoft/vscode-markdown-languageservice/src/types/range.ts
github://github/microsoft/vscode-markdown-languageservice/src/types/range.ts
```

The first one is the correct path AFAIK? Not sure where the second one is coming from, but it seems to be the request that generates the network requests

@joyceerhl Does remote hub have two file system providers, one for `vscode-vfs` and one for `github`? If it does, should JS/TS ignore the open `github:` documents?

**Comment by joyceerhl** [comment]
I consistently see two requests for TS server, is that expected?

<img width="966" alt="image" src="https://user-images.githubusercontent.com/30305945/220972133-b2d4eb68-2022-4da6-a8d4-b9ddd1f1725d.png">

**Comment by mjbvz** [comment]
@joyceerhl Yes, we start two instance of the server: one fast one and one for project wide support. Hopefully with caching though this does not actually result in two network requests
