### ISSUE TITLE
${fileDirname} does not encode spaces with "\ "

### ISSUE THREAD

**Issue by AndreasADL** [microsoft/vscode#172520]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.74.3
- OS Version: Win11

Steps to Reproduce:

1. Make folder including a Space e.g. "My Folder"
2. Reference it using ${fileDirname}
3. run into trouble e.g. by using it in launch.json for C++ gdb debugger

If your User folder has a space in it you're in big trouble...

**Comment by roblourens** [comment]
Can you include the launch.json? It depends on where it is and what the debug adapter is doing. It may be an issue for the extension.

**Comment by AndreasADL** [comment]
Sure!

`{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {       
            "name": "(gdb) Launch",
            "type": "cppdbg",
            "request": "launch",
            "program": "${fileDirname}\\${fileBasenameNoExtension}.exe",
            "args": [],
            "stopAtEntry": false,
            "cwd": "${fileDirname}",
            "environment": [],
            "externalConsole": false,
            "MIMode": "gdb",
            "miDebuggerPath": "C:\\mingw64\\bin\\gdb.exe",
            "setupCommands": [
                {
                    "description": "Enable pretty-printing for gdb",
                    "text": "-enable-pretty-printing",
                    "ignoreFailures": true
                },
                {
                    "description": "Set Disassembly Flavor to Intel",
                    "text": "-gdb-set disassembly-flavor intel",
                    "ignoreFailures": true
                }
            ]
        }

    ]
}`

**Comment by roblourens** [comment]
Please file this on the extension, they can tell us what the message is that they send to vscode to start the terminal

**Comment by AndreasADL** [comment]
> extension

Hi @roblourens yes, you're right, it should be a problem on their part...
Sorry for my noob question here but the extention here would be "C/C++ for Visual Studio Code"?
