### ISSUE TITLE
[Accessibility] Terminal a11y buffer is not automatically updated

### ISSUE THREAD

**Issue by jooyoungseo** [microsoft/vscode#172582]
CC @meganrogge

## Reproducible Steps

1. Load NVDA.
1. Open terminal.
1. Change directory to anywhere having lots of files and sub-directories.
1. Type `ls -1`
1. As soon as typing `ls -1`, press Shift+Tab to focus in the terminal a11y buffer.
1. Press Ctrl+End to go to the end of the buffer and see if it reflects the last file name of the `ls` command: It is not actualy.
1. Press Tab to terminal input and Shift+Tab to come back to a11y output buffer: This time the last line of the buffer reflects the the last item on the screen.

## Expected Behavior

The terminal a11y buffer needs to get updated automatically without manual focus refresh.

## System Info

Version: 1.75.0-insider (system setup)
Commit: 07d6f5b35fac559504dec65e3073d796b2d25a55
Date: 2023-01-26T05:23:05.014Z
Electron: 19.1.9
Chromium: 102.0.5005.194
Node.js: 16.14.2
V8: 10.2.154.23-electron.0
OS: Windows_NT x64 10.0.22621
Sandboxed: Yes

**Comment by Tyriar** [comment]
Performance is a concern but since it's an edge case I think it makes sense to listen for buffer changes and refresh it. We will probably need to append and not replace though

**Comment by jvesouza** [comment]
Another problem encountered is that if I type some text in the accessibility buffer, it is no longer updated. It seems that the problem  only happens if the text is typed very close to the last line of the buffer. I tried to reproduce the problem by typing a text at the beginning of the buffer but I couldn't.
To reproduce try the following steps:
1. Run some commands in the VSCode terminal.
2. Press the shift+tab keys and explore the accessibility buffer using the arrow keys. Note that the executed commands result are present as expected.
3. Move the cursor to the last line of the buffer and type any garbage.
4. Press tab and run more commands in the terminal.
5. Press the shift+tab keys and explore the accessibility buffer.

In my environment the result of the commands executed in step 4 are not present in the accessibility buffer, only the commands executed in step 1 are shown.

**Comment by steverep** [comment]
Please treat this as a significant bug and not an "edge case".  It's currently impossible to review the log of any running task or command until the task completes or the shell prompt is returned.  That eliminates access to many common things like:
- man pages
- python or node in interactive mode
- logs of significant builds or test suites
- development watch tasks

**Comment by meganrogge** [comment]
@steverep this is a plan item for the March iteration IE we plan to tackle it soon

**Comment by meganrogge** [comment]
Repro:

1. Run `while sleep 1; do echo "Hi"; done`
2. Focus the accessible buffer, focus the terminal, focus the accessible buffer again
3. 🐛 it doesn't update

**Comment by joyceerhl** [comment]
This still repros for me on Windows (without Narrator enabled):
1. Enable `"editor.accessibilitySupport"`
2. Run `ls`
3. Shift+Tab while step 2 is running
4. :bug: accessible buffer contents are incomplete 

If I click away from the VS Code window and then click back into it, the accessible buffer updates

**Comment by meganrogge** [comment]
this is `false` when I'm typing in the editor. this should instead check if the accessible buffer is visible, which it did originally

https://github.com/microsoft/vscode/blob/f584ecc7e63975401db1c0a0076f023f559bba3e/src/vs/workbench/contrib/terminalContrib/accessibility/browser/terminalAccessibleBuffer.ts#L119

**Comment by joyceerhl** [comment]
This still repros for me with the latest insiders.

**Comment by meganrogge** [comment]
@joyceerhl a gif would be helpful 

https://user-images.githubusercontent.com/29464607/227318087-eb807fbb-a566-4081-8d35-fa5b4a7f0542.mov

**Comment by joyceerhl** [comment]
https://user-images.githubusercontent.com/30305945/227319300-bc01d522-66e2-4916-9583-7dc6749b7c50.mp4

(in the recording above, at about the 6 second mark I click out of the terminal and back in, and that apparently forces an update)

**Comment by meganrogge** [comment]
can you repro if you start with a new terminal, don't run `clear`? i'm trying exactly what you show and not seeing an issue - in the latest insider's (as of 2 hours ago)

**Comment by Tyriar** [comment]
I can repro but it's quite difficult, there's probably some race condition where output occurs before the listener is registered. I suggest we action this as part of the _getContent testing/refactoring

**Comment by meganrogge** [comment]
Considering this verified because it works in most cases and we will have a TPI next iteration to test the improvements we plan to make
