### ISSUE TITLE
Usability: NVDA is not reciting any information after a file is committed or Undo Last Commit is Invoked.

### ISSUE THREAD

**Issue by WiproPSAccTest** [Microsoft/vscode#17259]
VS Code Version: 1.6.1
OS Version:1607
NVDA version:-2016.2.1

**Steps to Reproduce:**
1.Open Visual studio code editor.
2. Open any file and using "Ctrl+1" key  navigate to the first vs code editor.
3. Using F1 key navigate to the palette, type "git branch" and "refactor-to-promise" as the branch name
4. Make changes to the code by refactoring, adding/deleting new lines
5. Compare the changes between the HEAD and current file by navigating to View Bar ---> Git ; Navigate to changes and hit ENTER to activate "Diff View" 
6. Stage and commit the changes under View Bar ---> Git  ; Navigate to the "Commit Staged" or "commit All"  button and hit ENTER to make a commit and observe NVDA announcement
7. Undo the commit by navigating to the toggle button (same row as commit staged), hit ENTER and use down ARROW to choose "Undo Last Commit" option and observe NVDA announcement.

**Expected result:**
NVDA should provide information after a file is committed or Undo Last Commit is Invoked

**Actual Result:**
NVDA is not reciting any information after a file is committed or Undo Last Commit is Invoked

**User Impact:**
Screen Reader user doesn't get to know whether the file is committed or not and 'Undo Last commit' is successful or not.

**Attachments:**
![nvda is not reciting any information after a file is committed through commit all](https://cloud.githubusercontent.com/assets/22956130/21214883/8d729c86-c2c3-11e6-9f91-9d94e2d7328a.jpg)
![nvda is not reciting any information after a file is committed through commit staged](https://cloud.githubusercontent.com/assets/22956130/21214882/8d70697a-c2c3-11e6-8ba2-59a58266c36a.jpg)
![nvda is not reciting any information after undo last commit is invoked](https://cloud.githubusercontent.com/assets/22956130/21214881/8d6fca4c-c2c3-11e6-9841-fad17be77e26.jpg)

**Comment by isidorn** [comment]
Short description:
Commiting a file or undoing the last commit does not give screen reader feedback.

The issue here is that git is an extension and our extension story currently does not support extensions to read out area labels.

An alternative is to have a general SCM solution which would just read out once a resource is added to a resource group. However looking at the SCM api I am not sure if this is feasable, found a potential [location](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/api/electron-browser/mainThreadSCM.ts#L152) where a group resrouces are updated and where we could add some aria announcing

**Comment by joaomoreno** [comment]
Yeah this can't be supported right now unless there is an _announcing_ API.

**Comment by isidorn** [comment]
Due to the comments above pushing this to June (potentially backlog)

**Comment by joaomoreno** [comment]
To keep the number of issues in our inbox on a manageable level, we're closing issues that have been on the backlog for a long time but haven't gained traction: We look at the number of votes the issue has received and the number of duplicates issues filed.

Thanks for your understanding. Happy coding!
