### ISSUE TITLE
Execution decoration only renders during execution

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#172588]
Type: <b>Bug</b>

* Open endgame github issue notebook
* Run all
* You can see decorations rendered in overview ruler
* Once all execution finishes, they go away
* However if you scroll the notebook, we can still see the checkmark on each time. I would expect us to clear the decoration only when we reopen or re-run.

VS Code version: Code - Insiders 1.75.0-insider (3e4a338c7a90dd11895be84ecbc4b5cdf0fb9117, 2023-01-24T00:17:43.144Z)
OS version: Darwin x64 22.3.0
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|6, 5, 4|
|Memory (System)|32.00GB (0.04GB free)|
|Process Argv|--enable-proposed-api ms-vscode.vscode-notebook-history --enable-proposed-api vscode.notebook-editing --enable-proposed-api vscode.vscode-test-resolver --enable-proposed-api donjayamanne.kusto --enable-proposed-api donjayamanne.jupyterpowertools --enable-proposed-api rebornix.better-jupyter-errors --enable-proposed-api rchiodo.jupyter-tools --crash-reporter-id 1a907bbd-fa02-4595-81e0-63e1648afb31|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (96)</summary>

Extension|Author (truncated)|Version
---|---|---
tsl-problem-matcher|amo|0.6.2
comment-tagged-templates|bie|0.3.1
github-markdown-preview|bie|0.3.0
markdown-emoji|bie|0.3.0
markdown-footnotes|bie|0.1.1
markdown-mermaid|bie|1.17.4
markdown-preview-github-styles|bie|1.0.1
vscode-github-actions|csc|0.24.4
vscode-svgviewer|css|2.0.0
vscode-eslint|dba|2.2.6
prettier-java|dot|0.1.1
gitlens|eam|13.2.0
EditorConfig|Edi|0.16.4
vscode-npm-script|eg2|0.3.29
prettier-vscode|esb|9.10.4
codespaces|Git|1.13.7
copilot|Git|1.70.8099
remotehub|Git|0.48.0
vscode-pull-request-github|Git|0.56.0
go|gol|0.37.1
vscode-graphql|Gra|0.8.5
vscode-graphql-syntax|Gra|1.0.6
vscode-mocha-test-adapter|hbe|2.14.1
vscode-test-explorer|hbe|2.21.1
vscode-drawio|hed|1.6.6
handydandy-notebook|jak|0.1.4
beancount|Len|0.9.1
fluent-icons|mig|0.0.18
vscode-fluent-icons|mig|0.0.1
theme-monokai-pro-vscode|mon|1.2.0
vscode-azurefunctions|ms-|1.9.0
vscode-azureresourcegroups|ms-|0.5.6
vscode-azurestaticwebapps|ms-|0.11.3
vscode-docker|ms-|1.23.3
vscode-language-pack-qps-ploc|MS-|1.75.2023012509
vscode-language-pack-zh-hans|MS-|1.75.2023012510
csharp|ms-|1.25.2
isort|ms-|2022.8.0
python|ms-|2023.1.10241007
vscode-pylance|ms-|2023.1.41
jupyter|ms-|2023.1.2000260354
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.14
notebook-renderers|ms-|0.0.1
vscode-jupyter-cell-tags|ms-|0.1.6
vscode-jupyter-slideshow|ms-|0.1.5
remote-containers|ms-|0.273.0
remote-ssh|ms-|0.95.2023012415
remote-ssh-edit|ms-|0.84.0
azure-account|ms-|0.11.3
azure-repos|ms-|0.24.0
hexeditor|ms-|1.9.11
js-debug-nightly|ms-|2023.1.2317
live-server|ms-|0.5.2023012601
powershell-preview|ms-|2023.1.0
remote-explorer|ms-|0.1.2023012309
remote-repositories|ms-|0.26.0
test-adapter-converter|ms-|0.1.6
vscode-github-issue-notebooks|ms-|0.0.128
vscode-js-profile-flame|ms-|1.0.5
vscode-markdown-notebook|ms-|0.0.26
vscode-notebook-history|ms-|0.0.1
vscode-selfhost-test-provider|ms-|0.3.11
vscode-typescript-tslint-plugin|ms-|1.3.4
vsliveshare|ms-|1.0.5823
debugger-for-chrome|msj|4.13.0
vetur|oct|0.36.1
excalidraw-editor|pom|3.3.4
geo-data-viewer|Ran|2.6.0
vscode-data-preview|Ran|2.3.0
better-jupyter-errors|reb|0.0.1
toggle|reb|0.0.2
typing-practice|reb|0.0.1
vscode-chat-iw|reb|0.0.1
vscode-code-renderer|reb|0.0.2
vscode-jupyter-docker-stack-connect|reb|0.0.1
java|red|1.14.0
vscode-xml|red|0.23.0
kuskus-extensions-pack|ros|1.0.10
kuskus-kusto-language-server|ros|1.0.31
kuskus-kusto-syntax-highlighting|ros|1.1.21
vsc-nwjs|rua|1.0.18
rust-analyzer|rus|0.4.1381
swift-lang|ssw|1.0.0
tldraw-vscode|tld|1.25.2
luna-paint|Tyr|0.16.0
sourcekit-lsp|unp|0.0.1
vscode-lldb|vad|1.8.1
vscode-swiftlint|vkn|1.8.3
vscode-java-debug|vsc|0.47.0
vscode-java-dependency|vsc|0.21.1
vscode-java-pack|vsc|0.25.7
vscode-java-test|vsc|0.37.1
vscode-maven|vsc|0.40.4
notebook-editing|vsc|1.0.0
vscode-test-resolver|vsc|0.0.1

(7 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30422396
pythontb:30258533
pythonptprofiler:30281269
vsdfh931cf:30280410
vshan820:30294714
pythondataviewer:30285072
vscod805:30301674
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30404738
cppdebug:30492333
vsclangdf:30492506
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30618038
pylantcb52:30590116
pyindex848:30611229
nodejswelcome1:30587009
pyind779:30611226
pythonsymbol12:30651887
a9j8j154:30646983

```

</details>

**Comment by roblourens** [comment]
By design, for now these are only trying to show the active running status
