### ISSUE TITLE
i can't run any code

### ISSUE THREAD

**Issue by Mohammad-Rifat-Khan** [microsoft/vscode#172540]
Type: <b>Performance Issue</b>

g++.exe: error: lab-2d: No such file or directory
g++.exe: error: array: No such file or directory
g++.exe: error: memory.cpp: No such file or directory
g++.exe: error: array: No such file or directory
g++.exe: error: memory: No such file or directory
g++.exe: fatal error: no input files
compilation terminated.
NativeCommandExitException: Program "g++.exe" ended with non-zero exit code: 1.                            

whenever i run a code this type of error occurs

VS Code version: Code 1.74.3 (97dec172d3256f8ca4bfb2143f3f76b503ca0534, 2023-01-09T16:59:02.252Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|12th Gen Intel(R) Core(TM) i5-12400 (12 x 2496)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.78GB (8.29GB free)|
|Process Argv|--crash-reporter-id 0f96a2df-e29c-4c17-a032-3f9752538565|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	   124	 11948	code main
    0	   204	  2744	   window (lab-2d array memory.cpp - --Algorithm - Visual Studio Code)
    0	   201	  4228	   gpu-process
    0	    25	  7932	   crashpad-handler
    0	   164	 14232	   extension-host
    0	    70	 14168	     "c:\Users\MD RIFAT KHAN\.vscode\extensions\ms-vscode.cpptools-1.14.0-win32-x64\bin\cpptools.exe"
    0	     3	  7952	       "c:\Users\MD RIFAT KHAN\.vscode\extensions\ms-vscode.cpptools-1.14.0-win32-x64\bin\cpptools.exe"
    0	   193	  1184	         "c:\Users\MD RIFAT KHAN\.vscode\extensions\ms-vscode.cpptools-1.14.0-win32-x64/bin/cpptools-srv.exe" 14168 {386F76BD-6C91-4550-9FBC-9B5FE8C5510E}
    0	    10	 14180	           console-window-host (Windows internal process)
    0	    10	 14860	       console-window-host (Windows internal process)
    0	   107	 14476	   shared-process
    0	    79	  4572	     ptyHost
    0	   103	  6692	       "C:\Program Files\PowerShell\7-preview\pwsh.exe" -noexit -command "try { . \"e:\C++ practice\Microsoft VS Code\resources\app\out\vs\workbench\contrib\terminal\browser\media\shellIntegration.ps1\" } catch {}"
    0	     6	  8092	       console-window-host (Windows internal process)
    0	    84	 15024	     fileWatcher
    0	    42	 15136	   utility-network-service
    0	    88	 16248	   issue-reporter
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (lab-2d array memory.cpp - --Algorithm - Visual Studio Code)
|    Folder (--Algorithm): 6 files
|      File types: cpp(4) md(1)
|      Conf files:;
```

</details>
<details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
path-intellisense|chr|2.8.4
vscode-eslint|dba|2.2.6
gitlens|eam|13.2.0
code-runner|for|0.12.0
c-cpp-runner|fra|5.0.0
vscode-pull-request-github|Git|0.56.0
search-node-modules|jas|1.3.0
cmake-tools|ms-|1.13.42
cpptools|ms-|1.14.0
cpptools-extension-pack|ms-|1.3.0
cmake|twx|0.0.17
vscode-lldb|vad|1.8.1
JavaScriptSnippets|xab|1.8.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
azure-dev_surveyone:30548225
vscccc:30610679
pyindex848:30577860
nodejswelcome1cf:30587006
2e4cg342:30602488
89544117:30613380
vscup:30628656

```

</details>

**Comment by roblourens** [comment]
This is probably an issue with your program, system, or configuration. If you think it's an issue with the C++ extension, please file an issue on that repo with more details.
