### ISSUE TITLE
change to launch.json is not reflected when I press f5

### ISSUE THREAD

**Issue by cherchyk** [Microsoft/vscode#1725]
change to launch.json is not reflected when I press f5

for example I changed from "program": "web.js"   to "program": "server.js"

but when I press f5 Code is still calling web,js

I have to restart Code in order to pick change

**Comment by bpasero** [comment]
@cherchyk what OS? I suspect file events are failing. Does it work when you wait 1 second before pressing F5?

**Comment by cherchyk** [comment]
It was w10 from virtualbox vm
