### ISSUE TITLE
VSCode spews diagnostic logs to the CMD prompt while I am trying to use it.

### ISSUE THREAD

**Issue by Alan-Jowett** [microsoft/vscode#172546]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.74.3
- OS Version: 25286.1001.amd64fre.rs_onecore_liof1.230124-1659

Steps to Reproduce:

1. Open CMD prompt
2. Navigate to root of git repo
3. "code ."

Expected result:
VS Code is launched, and I can continue to use the CMD prompt for other uses.

Actual result:
VS Code spits out random messages while I am using the CMD prompt, making the CMD window unussailable.

![image](https://user-images.githubusercontent.com/20480683/214889766-8f2bc5c6-4857-4c9c-9e89-3a6840f82fb4.png)

**Comment by lszomoru** [comment]
@bpasero, any idea what could have happened here?

**Comment by bpasero** [comment]
This is a setup issue, it looks like `code` here is the actual `Code.exe` and not the command line executable.

//cc @joaomoreno

**Comment by joaomoreno** [comment]
@Alan-Jowett Is this the ZIP distribution? Is `code.exe` in your cwd?

**Comment by Alan-Jowett** [comment]
```
E:\>where code
C:\Users\alanjo\AppData\Local\Programs\Microsoft VS Code\Code.exe
C:\Users\alanjo\AppData\Local\Programs\Microsoft VS Code\bin\code
C:\Users\alanjo\AppData\Local\Programs\Microsoft VS Code\bin\code.cmd
```

This is an MSI install as far as I know.

**Comment by Alan-Jowett** [comment]
It looks like launching ```C:\Users\alanjo\AppData\Local\Programs\Microsoft VS Code\bin\code``` doesn't trigger the issue.

But launching just ```code``` does trigger it. 

![image](https://user-images.githubusercontent.com/20480683/215156825-1efd6ee9-a8e2-49d0-a872-903286a4391b.png)

**Comment by Alan-Jowett** [comment]
After adjusting the order of path variables so that ```Microsoft VS Code\bin\code``` occurs first in the path search. the problem no longer occurs. Thanks for helping me root cause this.
