### ISSUE TITLE
Usability: NVDA is not reciting the names for the errors and warnings present in the errors and warning panel on Navigation.

### ISSUE THREAD

**Issue by WiproPSAccTest** [Microsoft/vscode#17256]
VS Code Version: 1.6.1
OS Version:1607
NVDA version:-2016.2.1

**Steps to Reproduce:**
1.Open VS code editor.
2.Navigate to one of the editor.
3.Press"Ctrl+Shift+M" to open the errors and warnings panel.
4. Using "Down Arrow" navigate to the errors and warnings.
5. Observe the NVDA behavior.
6. Fix the errors and observe visually the status changed in Errors and Warnings panel.
7. observe NVDA behavior.
8. Now Press "Ctrl+Shift+M" twice to reopen the panel and observe the NVDA behavior.

**Expected result:**
1. NVDA should provide information about the errors and warnings present in the panel on Navigation
2. NVDA should recite information regarding the fix of errors as soon as the status is changed in the Errors and Warnings Panel without reopening of panel

**Actual Result**:
Issue1: NVDA is not providing any information about the errors and warnings present in the panel on Navigation. On hitting Ctrl+Shift+M, NVDA  announces as "Problems grouped by Tree file view".
Narrator Behavior:
Narrator announces the Name and Details on Capslock+Arrow key Navigation
Issue 2: NVDA is reciting information regarding the fix of errors unless the panel is reopened
Narrator Behavior:
Narrator is not announcing the message even after reopening the Panel

**User Impact:**
Screen Reader user doesn't get to know about the available Errors and Warnings and doesn't know whether they are fixed or not as no announcement after fixing

**Attachments:**
![nvda is not announcing information when errors are fixed](https://cloud.githubusercontent.com/assets/22956130/21214498/063a5706-c2c1-11e6-94ac-ca5918f16802.jpg)
![nvda is not announcing the error names and details](https://cloud.githubusercontent.com/assets/22956130/21214500/063e2926-c2c1-11e6-98c8-578d23b7d515.jpg)

**Comment by sandy081** [comment]
It works for me while navigating the problems in the panel

![kapture 2017-04-25 at 13 03 51](https://cloud.githubusercontent.com/assets/10746682/25382385/ac7b1fc6-29b7-11e7-9e2a-37fc18908829.gif)
