### ISSUE TITLE
duplicated icons in SCM view

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#172586]
![Screenshot 2023-01-26 at 12 45 32 PM](https://user-images.githubusercontent.com/29464607/214947122-cc9038fc-b633-4853-9ad7-a84146c121a4.png)

**Comment by lszomoru** [comment]
@meganrogge, is that the "Commits" view? Is there a chance that you have both stable and insiders of GitLens installed?

**Comment by meganrogge** [comment]
It's possible
