### ISSUE TITLE
No border on `export profile` button section

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#172572]
Type: <b>Bug</b>

Testing #170734

1. Run `export profile`

**bug**
There's no border or shadow or contrast between the export button section and the list:

 
![Screenshot 2023-01-26 at 11 13 05 AM](https://user-images.githubusercontent.com/12821956/214928583-94697041-d8d1-44a0-a247-bc8c37ced5b0.png)

This looks off to me

VS Code version: Code - Insiders 1.75.0-insider (Universal) (07d6f5b35fac559504dec65e3073d796b2d25a55, 2023-01-26T05:22:17.192Z)
OS version: Darwin x64 22.2.0
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|3, 2, 2|
|Memory (System)|32.00GB (0.02GB free)|
|Process Argv|--crash-reporter-id 48781ca2-1705-4f64-9bab-325055aab55d|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by mjbvz** [comment]
My image was unclear but this still looks broken to me:

![Image](https://github.com/microsoft/vscode/assets/12821956/6598acdc-b69e-4dcc-ae90-31759003f2e0)

Focusing the widget makes it more clear what is going on: 

![Image](https://github.com/microsoft/vscode/assets/12821956/b06cca0f-9c84-46b6-bf86-396791fa5c4f)

Other scrollable elements typically have a shadow here

**Comment by sandy081** [comment]
I closed it as wont fix, hence you did not see the difference.  Can you please share other similar places where we have a shadow. Thanks.

**Comment by mjbvz** [comment]
We usually have borders instead between view sections. However we do use shadows in some of our lists 

![Image](https://github.com/microsoft/vscode/assets/12821956/91b62989-160a-4451-9fab-b4d04a3fd39a)
