### ISSUE TITLE
Terminal accessibility - line selection when holding up/down

### ISSUE THREAD

**Issue by lszomoru** [microsoft/vscode#172511]
Testing #171862

1. Enter accessibility mode in the terminal
2. Press up/down once and line selection is moving one line up/down as expected
3. Hold down up/down so that the cursor is moving multiple lines

**Expected:** the line where the cursor is when you release the up/down key is selected
**Actual:** the line where the cursor is when you release the up/down key is not selected

**Comment by meganrogge** [comment]
I think by "selected", you mean read by the screen reader? It is likely going to first read all of the content from the bottom line to the top before reading the current one.

**Comment by lszomoru** [comment]
The behaviour in the terminal seems to be consistent with the behaviour in the editor. Closing the issue.
