### ISSUE TITLE
terminal quick fixes are not available until next command is entered on Linux

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#172564]
1. Use bash on Ubuntu (brand new setup and profile)
2. Enter `npm audt`
3. See no quickfix bulb  🐛 
4. Hit enter again
5. See there's now a lightbuld

![Kapture 2023-01-26 at 10 04 38](https://user-images.githubusercontent.com/2230985/214914363-174d978e-6a50-4b47-a040-77a76fd41f26.gif)

Maybe similar to https://github.com/microsoft/vscode/issues/143832

**Comment by meganrogge** [comment]
related? https://github.com/microsoft/vscode/issues/167617

**Comment by connor4312** [comment]
Probably!
