### ISSUE TITLE
Split terminal failt if accentuated letter in path

### ISSUE THREAD

**Issue by Sayanel01** [microsoft/vscode#172514]
Type: <b>Bug</b>

Open vscode terminal
$ mkdir Crédit
$ cd Crédit
Then split terminal view `Ctrl + Shift + ()`
Will return "The terminal process failed to launch: Starting directory (cwd) "/home/phil/CrÃ©dit" does not exist."
That's incorrect encoding between UTF-8 and iso-8859-1

Nb: If working folder is already with accent, then oppening a new terminal works.
Nb2: On top right of terminal window, you have displayed the name of current directory. It is also incorectly encoded (see https://i.imgur.com/6y8g5JT.png)

VS Code version: Code 1.74.3 (97dec172d3256f8ca4bfb2143f3f76b503ca0534, 2023-01-09T16:57:40.428Z)
OS version: Linux x64 5.15.0-58-generic
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 2700X Eight-Core Processor (16 x 2200)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|1, 1, 1|
|Memory (System)|31.27GB (25.79GB free)|
|Process Argv|--unity-launch --crash-reporter-id 942109f0-d6a0-4c11-a290-12eee7f17bb8|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|cinnamon|
|XDG_CURRENT_DESKTOP|X-Cinnamon|
|XDG_SESSION_DESKTOP|cinnamon|
|XDG_SESSION_TYPE|x11|
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
azure-dev_surveyone:30548225
vscccc:30610679
pyindex848:30577860
nodejswelcome1:30587005
2e4cg342:30602488
pyind779cf:30647092
f6dab269:30613381

```

</details>

**Comment by meganrogge** [comment]
fixed in insider's /duplicate #168804
