### ISSUE TITLE
[ja] Unnecessary whitespace in debug menu

### ISSUE THREAD

**Issue by yu-miura** [microsoft/vscode#172578]
There's an unnecessary whitespace in "i18n/vscode-language-pack-ja/translations/main.i18n.json".
```
"detectThenRunAndDebug": "[すべての自動デバッグ構成を表示](command: {0})。",
```
The whitespace after "command:" makes the link dead.

![dead_link_on_debug_menu](https://user-images.githubusercontent.com/9346110/207848867-64b8a089-1e01-422e-a423-ba6fc488382c.png)

**Comment by TylerLeonhardt** [comment]
@roblourens you can add a comment to this string like so:
https://github.com/microsoft/vscode/blob/de586eda3fc751012b74a79a374e3eb67534f099/extensions/git/package.nls.json#L199

to ensure that the command never has a problem like this. Notice that the example string has, in the Locked area, a `](` at the start of it. This will make sure there is no whitespace between them.
