### ISSUE TITLE
Source reference in call stack not updated after DAP InvalidatedEvent(['stack']) is issued 

### ISSUE THREAD

**Issue by AHodkinsonIMG** [microsoft/vscode#172544]
When a debug adapter extension sends a DAP InvalidatedEvent with the invalidated area set to 'stacks' we can see that this forces VSCode to reread the stack trace from the debug adapter.  The VSCode call stack window is then updated with the latest stack trace from the debug adapter.  However if the source file at the top of the stack has changed, the file is not opened (or highlighted) until a user clicks on the call stack.

The use case here is when debugging via GDB & single stepping into a library file without source information. VSCode will show an error message "The editor could not be opened because the file was not found".
If a source path substitution is then made which points to the library source code and the InvalidatedEvent(['stacks']) issued, we'd expect the new file to be displayed with the current line highlighted without having to click on the call stack.   

Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.74.3
- OS Version: Darwin arm64 21.6.0

Steps to Reproduce:

1. Clone https://github.com/AHodkinsonIMG/vscode-mock-debug - this is a fork of vscode-mock-debug with an additional custom request handler to change the file at the top of the stack then trigger an InvalidatedEvent(['stacks']) call.
2. yarn install, then run the extension in VSCode
3. In the extension, start debugging "readme.md", the call stack will look like this
![Screenshot 2023-01-26 at 15 48 15](https://user-images.githubusercontent.com/117825447/214882460-b7c25f26-9908-441d-9827-9088115266de.png)
4. Open the command palette and run the command "Mock Debug: Toggle changed call stack".  This function will call the custom request handler to update the top of the stack to point to "subfunction.md", line 0, column 0, and then invalidate the stack
![Screenshot 2023-01-26 at 15 49 10](https://user-images.githubusercontent.com/117825447/214883444-e233c167-82a7-40b4-a6e1-6a5762b78c30.png)
5. The call stack will then show the updated information, but "subfunction.md" will not be opened.
![Screenshot 2023-01-26 at 15 49 31](https://user-images.githubusercontent.com/117825447/214884186-1cd03ce6-6d67-4f13-b2c9-7760bf5858b5.png)
6. Until the user clicks on the call stack window.
![Screenshot 2023-01-26 at 15 49 41](https://user-images.githubusercontent.com/117825447/214884450-8e687a8c-c214-47db-9a31-3300e858daeb.png)

**Comment by AHodkinsonIMG** [comment]
Hi, is there a plan to fix this bug anytime soon?  We're relying on this feature in an extension that we are developing - we need VSCode to process the updated call stack after an InvalidatedEvent has been sent so that updated source code is shown to the user!
Many thanks

**Comment by roblourens** [comment]
I don't have time to work on this in the near future but I would take a PR that calls this code

https://github.com/microsoft/vscode/blob/3cd805aef6dbbba6725b364c912759f12bcd359d/src/vs/workbench/contrib/debug/browser/debugSession.ts#L985-L1023

from here

https://github.com/microsoft/vscode/blob/3cd805aef6dbbba6725b364c912759f12bcd359d/src/vs/workbench/contrib/debug/browser/debugSession.ts#L985-L1023

if that fixes your scenario

**Comment by connor4312** [comment]
This should be fixed in https://github.com/microsoft/vscode/pull/200789; we previously were not handling stack invaliations very well. Please let me know if not.

**Comment by justschen** [comment]
@AHodkinsonIMG could you verify if this has been fixed?
