### ISSUE TITLE
Folding / unfolding is not being read out by screen reader

### ISSUE THREAD

**Issue by WiproPSAccTest** [microsoft/vscode#17257]
VS Code Version: 1.6.1
OS Version:1607
NVDA version:-2016.2.1

**Steps to Reproduce:**
1.Open VS code editor.
2.Navigate to one of the editor.
3. Navigate to a Bracket present in the file and see the matched bracket highlighted and observe NVDA announcement.
4. Navigate to the Name which you want to change and Press Options button or Right Click and select Change all Occurrences and Hit Enter and change the Name to Desired Name and observe NVDA announcement.
(Note- Options key is available only in Personal Computer and Not on Laptops)
5. Press f1 and type "Fold" or "Unfold "command in command pallet and Hit Enter and observe NVDA announcement.

**Expected result:**
NVDA should provide information when two brackets are matched or after changing multiple occurrence or after folding/unfolding

**Actual Result:**
NVDA is not reciting any information when two brackets are matched or after changing multiple occurrence or after folding/unfolding.
Observation: NVDA announces the command written ">fold" in command pallet when Keyboard focus goes to the options Displayed by Command Pallet

**User Impact:**
Screen Reader user doesn't get to know when two brackets are matched or after changing multiple occurrence or after folding/unfolding.

**Attachments:**
![nvda announces the command in the command pallete for all options displayed by command pallete](https://cloud.githubusercontent.com/assets/22956130/21214623/e0092c00-c2c1-11e6-9aab-ef8336e47e6f.jpg)
![nvda is not reciting any information after changing multiple occurance](https://cloud.githubusercontent.com/assets/22956130/21214625/e00faa1c-c2c1-11e6-8973-53b08404b9fd.jpg)
![nvda is not reciting any information after folding a file](https://cloud.githubusercontent.com/assets/22956130/21214626/e012f4ce-c2c1-11e6-9123-b7fdebd1dc72.jpg)
![nvda is not reciting any information after unfolding a file](https://cloud.githubusercontent.com/assets/22956130/21214624/e00a4ea0-c2c1-11e6-9574-26c50fd19abd.jpg)
![nvda is not reciting any information when two brackets are matched](https://cloud.githubusercontent.com/assets/22956130/21214622/e00713c0-c2c1-11e6-9662-b45e1bd915f7.jpg)

**Comment by isidorn** [comment]
Reading every time a bracket gets matched can be too noisy.
However reading something when we fold / unfold I think makes perfect sense 
@aeschli could we do some annoucment when a region folds / unfolds, like the start and end of a region?

Assigning to july, and also to myself (in case you do not have time could you provide some code pointers)

**Comment by aeschli** [comment]
When detecting a screen reader, we enter 'accessibility mode' and turn folding off.
Maybe we also need to disable the commands in the command menu?

**Comment by isidorn** [comment]
@aeschli oh yeah I forgot about that.
Yeah just disable the commands in the command palette via context key.
