### ISSUE TITLE
[regression] dragging a reference onto editor doesn't work anymore

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#172516]
* have references view results
* drag an item onto the editor pane
* 🐛 the file isn't opened anymore

**Comment by jrieken** [comment]
this code is still being executed: https://github.com/microsoft/vscode/blob/990a496681948ec274da5503b35cd49a7d06c0a2/extensions/references-view/src/tree.ts#L206

**Comment by alexr00** [comment]
@mjbvz in case you know of something that changed here. It still looks ok from the tree side and I don't see anything that has changed there.

**Comment by alexr00** [comment]
Found the commit: https://github.com/microsoft/vscode/pull/165768

**Comment by jrieken** [comment]
👏
