### ISSUE TITLE
Unable to input "line break" character in search box

### ISSUE THREAD

**Issue by heqian** [Microsoft/vscode#1726]
OS: Mac OS X 10.10.5
Visual Studio Code version: 0.10.6 (a80232bbcfe8a5cdad1ebc98638673d9dcb02458)

Description:
1. In a file I was editing, I tried to search how many "line break" characters in the file;
2. I was not sure if the "line break" character is CRLF/CR/LF, so I tried to copy & paste the "line break" character I selected to the search box;
3. Failed, unable to paste it to search box.

Related discussion:
http://stackoverflow.com/questions/30351529/find-and-replace-new-line-in-visual-studio-code

**Comment by felixfbecker** [comment]
You can switch to regexp mode and use `\n` and/or `\r`

**Comment by bpasero** [comment]
:+1:

**Comment by felixfbecker** [comment]
Actually, I have to correct myself: this is not possible because the regexps match on a line basis. I used  that trick to match tabs with `\t`, but `\n` or `\r` does not work currently.

**Comment by felixfbecker** [comment]
@bpasero please reopen

**Comment by bpasero** [comment]
I also confused myself, I think we added support to "Replace" with new lines but not to search for new lines. But @alexandrudima would know.

**Comment by felixfbecker** [comment]
Basically to fix this, VS Code needs to match regexps with the multiline flag.

**Comment by alexandrudima** [comment]
Indeed, this is a limitation in the way we find (line-by-line) -- you cannot search for `\r` or `\n`.

Let's track it in #313
