### ISSUE TITLE
Usability: Overlap in integrated terminal

### ISSUE THREAD

**Issue by dianvaltodorov** [Microsoft/vscode#17262]
- VSCode Version: 1.8
- OS Version: OS X El Capitam 10.11.6

Steps to Reproduce:

1. Open integrated terminal

<img width="814" alt="screen shot 2016-12-15 at 9 24 38 am" src="https://cloud.githubusercontent.com/assets/6150700/21215208/555bd576-c2a8-11e6-9384-c54b5abf5808.png">

**Comment by kaiwood** [comment]
Dup of https://github.com/Microsoft/vscode/issues/15420

**Comment by kieferrm** [comment]
Duplicate of #15420.
