### ISSUE TITLE
Contextmenu duplicates `workbenchactionexecuted` events

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#172640]
* enable trace logging
* show telemetry output channel
* from the explorer hide/show NPM view
* :bug: notice that two `workbenchactionexecuted` are send, once with source 'sideBar' and once with source 'contextMenu'

**Comment by jrieken** [comment]
One sender is [here](https://github.com/microsoft/vscode/blob/c600c105793d31942279de2ad95dbbb61c29715f/src/vs/platform/contextview/browser/contextMenuHandler.ts#L151) and the other is [here](https://github.com/microsoft/vscode/blob/990a496681948ec274da5503b35cd49a7d06c0a2/src/vs/workbench/browser/parts/compositePart.ts#L274) - I actually don't know which one should win and it might be that many places with context menu will send double events

**Comment by bpasero** [comment]
@lramos15 thoughts?

**Comment by jrieken** [comment]
IMO a context menu which is actually an overflow menu of a toolbar shouldn't send the event. Toolbars should own their telemetry - which btw is easy via [telemetrySource](https://github.com/microsoft/vscode/blob/77ac5c1467d5a9a0e41fd57a81d38c0aef71f49a/src/vs/platform/actions/browser/toolbar.ts#L58)

**Comment by lramos15** [comment]
> @lramos15 thoughts?

No strong feelings here. Juts we shouldn't duplicate the same data twice as this event is already noisy. Looping in @devinvalenciano and @digitarald since they're the main ones querying these events to know what would be the expected behavior from the consumer side of things

**Comment by bpasero** [comment]
After talking with Jo: this needs a way for the context menu to be configurable to not send telemetry when used by another component such as the toolbar. Today, the context menu logs telemetry for each action invoked, but should probably only do so when it is being used as a standalone thing (i.e. right click) and not when used as part of another component such as the toolbar widget itself.

**Comment by bpasero** [comment]
Ping

**Comment by sbatten** [comment]
@bpasero PR up for that change

**Comment by digitarald** [comment]
Similar to Logan, I think fixing this is good. Given how `workbenchactionexecuted` is instrumented across various parts of the source code, this dupe isn't surprising and its good to have it fixed.
