### ISSUE TITLE
`code-insiders --prof-append-timers --disable-updates` reports: `Not on latest version, updates available`

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#172687]
I noticed this when looking at the macOS perf machine output:

```
1529	Code - Insiders	da0309f251	07175058-344b-4f06-beb0-ec56dda24be71674889558537	NO_standard_start : Not on latest version, updates available	0037ms
```

For some reason, this code seems to return `undefined` or `false`:

https://github.com/microsoft/vscode/blob/b5aa3e0a3d3cdac2c44c022182ca2f238949a444/src/vs/workbench/contrib/performance/browser/startupTimings.ts#L63-L65

**Steps:**
* `code-insiders --user-data-dir /Users/bpasero/Desktop/prof-start-ws --prof-append-timers /Users/name/Desktop/1.txt --disable-updates`

**Comment by bpasero** [comment]
Oh, this is not a regression and seems to be caused by passing `--disable-updates`. Looks like on macOS passing this flag disables the update check entirely. This does not seem to happen on Windows though.

**Comment by bpasero** [comment]
Ah, mistake on my end: I added `--disable-updates` when running perf tests but our Windows perf bot does not. I will see to do a different change then.

**Comment by jrieken** [comment]
Yeah, without the update service enabled you can't know if you are on latest or not
