### ISSUE TITLE
Repo incorrectly detected as created by different user.

### ISSUE THREAD

**Issue by karthiknadig** [microsoft/vscode#172669]
I see this message even though I created the volumes:
![image](https://user-images.githubusercontent.com/3840081/215167607-2f40d7ab-0659-4803-9a4b-b72c1bab842f.png)

_Originally posted by @karthiknadig in https://github.com/microsoft/vscode/issues/167338#issuecomment-1406929164_

**Comment by lszomoru** [comment]
@karthiknadig, can you please run `git status` and share the output?
I am suspecting that the volume was created by you but it is owned by the "Administrators" group.

**Comment by karthiknadig** [comment]
This is what i get:
![image](https://user-images.githubusercontent.com/3840081/215640911-f8cbe453-c494-40bd-96f2-05d6f57f0f32.png)


Once I allow "unsafe repository" how do I unset it?

**Comment by lszomoru** [comment]
@karthiknadig, could you please confirm that this is the output that you get **after** you have marked the repository as safe. I would be interested to know what is the output of `git status` at the time when VS Code shows the repository as being unsafe. 

Whether a repository is safe/unsafe is stored in the git config so you can clear all values using:
```
git config --global --unset-all safe.directory
```

**Comment by karthiknadig** [comment]
Before:
```
D:\>git status
fatal: detected dubious ownership in repository at 'D:/'
'D:/' is on a file system that doesnot record ownership 
To add an exception for this directory, call:

        git config --global --add safe.directory D:/    
```

After:
```
D:\>git status
On branch main

No commits yet

Untracked files:
  (use "git add <file>..." to include in what will be committed)
        .gitignore
        something/

nothing added to commit but untracked files present (use "git add" to track)

```

I think this can be closed since git itself raises the issue with ownership.

**Comment by lszomoru** [comment]
That is correct. VS Code just leverages the output of `git status` to display the welcome view.
