### ISSUE TITLE
keyboard.dispatch: KeyCode no longer prevents key-mapping from recognizing caps lock as ctrl

### ISSUE THREAD

**Issue by thor314** [microsoft/vscode#172600]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.74.3
- OS Version: 
 Static hostname: pop-os
Operating System: Pop!_OS 22.04 LTS
          Kernel: Linux 6.0.6-76060006-generic
    Architecture: x86-64
 Hardware Vendor: System76

Steps to Reproduce:
1. Use Gnome Tweaks  keyboard settings to remap caps-lock to ctrl
2. open VS code keybindings, attempt using remapped capslock

the following is in my config.json
    "keyboard.dispatch": "keyCode", // caps lock as ctrl should work as expected, no longer does

**Comment by ulugbekna** [comment]
Hi @thor314  🙂

Thanks for filing this issue! 

Could you please try the [following](https://github.com/microsoft/vscode/wiki/Keybinding-Issues#basic-troubleshooting):

1. Run the command "Developer: Toggle Keyboard Shortcuts Troubleshooting" (you can, for example, run it from the Command Palette). 

   This will activate logging of dispatched keyboard shortcuts and will open an output panel with the corresponding log file.

2. Press exactly the keybinding you desire
 
3. Check what VS Code detects

If you are having trouble understanding the output, please feel free to paste here and we'll be happy to help ☺️
