### ISSUE TITLE
Simplify profile preview flow

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#172671]
As we discussed, we should

1. Remove text "By default..."
2. Extensions need an ui decoration that shows that they are not applied in Web
3. Default button should be "Import in Visual Studio Code", that button should have a dropdown. And under the dropdown should be "Save Profile in Web"
4. Consider adding telemetry

![Screenshot 2023-01-27 at 21 10 18](https://user-images.githubusercontent.com/1926584/215187558-8882ae83-0d76-4b4b-87ca-05030c200a5a.png)

**Comment by isidorn** [comment]
@cwebster-99 thanks for sharing, this is super insightful.
@sandy081 what are the main benefits of showing vscode.dev here? In theory, could we skip it and go directly to vscode?

fyi @joaomoreno

**Comment by sandy081** [comment]
> In theory, could we skip it and go directly to vscode?

I am not sure it is possible in practical. @joaomoreno is it?

**Comment by sandy081** [comment]
This is fixed with new Profiles UI
