### ISSUE TITLE
Zen mode causes BSOD (blue screen of death) with error driver irql_less_or_not_equal

### ISSUE THREAD

**Issue by shamglam** [Microsoft/vscode#17266]
- VSCode Version: 1.8.0
- OS Version: Windows 10 (10.0.14393)

Steps to Reproduce:

1. Enter zen mode (ctrl-k, ctrl-z)
2.  enjoy blue screen

this is probably limited to a few hardware configurations but making an issue on github in case others experience the same or know how to investigate this issue further.

**Comment by ztamizzen** [comment]
Have you tried hitting F11 in Chrome? Does the same thing happen?
Wondering since it doesn't happen for me and I guess it's the same functionality.

**Comment by shamglam** [comment]
investigated this further by downloading Windows Debugging tools, opening up the dump files which the BSOD had generated. The analysis pointed to a directx faulting module and the video driver was the suspect. 

Found no updates using the Lenovo system update tool but searching on Lenovo website revealed a new driver for Windows 10, and after updating the issue seems to have been resolved.
