### ISSUE TITLE
Screenreader status in cleared on reload

### ISSUE THREAD

**Issue by deepak1556** [microsoft/vscode#172688]
Extracted from https://github.com/microsoft/vscode/issues/167627#issuecomment-1407000299

Steps to Reproduce:

1. Open VSCode Insiders
2. Enable Voice Over
3. Verify that the status bar shows `Screen Reader Optimized`
4. Reload window
5. Status bar indication is cleared

Version: 1.75.0-insider (Universal)
Commit: da0309f2514ac22ac82dcd080cfc764fe2a1f434
Date: 2023-01-27T14:19:56.997Z
Electron: 19.1.9
Chromium: 102.0.5005.194
Node.js: 16.14.2
V8: 10.2.154.23-electron.0
OS: Darwin x64 22.2.0
Sandboxed: Yes

**Comment by isidorn** [comment]
@meganrogge can you investigate? Might be a limitation of the `AccessibilityService`.

**Comment by meganrogge** [comment]
Waiting on @bpasero here as i'm not sure if we can change/fix the root cause of this

**Comment by bpasero** [comment]
I am not sure how I can help here, but:
* we seem to have code to detect screen reader and update the status bar
* after a window reload it seems that the status bar is not reflecting screen reader
* thus, the code that detects screen reader should run when the status bar is created

Does that make sense?
