### ISSUE TITLE
Potential dangerous consequences of using "Run" -> "Start Debugging"

### ISSUE THREAD

**Issue by mabodofutk** [microsoft/vscode#172694]
Type: <b>Bug</b>

**Consequences: the whole workspace could be accidentally deleted**
How it can happen:
* First, create a new folder named "bug_report" and open it in vscode
* In console, type the following commands
  ```
  mkdir a_folder
  echo "print('hello world')" > dummy.py
  ```
* Now, show "dummy.py" in vscode and then use "Run" -> "Start Debugging"
  This will open a new Python Debug Console and then output
  ```
  hello world
  ```
* Do not close the opened debug console and type without press "Enter" key
  ```
  rm -r a_folder
  ```
  Notice: just type in line and do NOT execute
* Now we use "Run" -> "Start Debugging" again and you'll find your whole "bug_report" folder has been deleted

VS Code version: Code 1.74.3 (Universal) (97dec172d3256f8ca4bfb2143f3f76b503ca0534, 2023-01-09T17:07:18.579Z)
OS version: Darwin x64 22.1.0
Modes:
Sandboxed: Yes
Remote OS version: Linux x64 5.4.0-135-generic

**Comment by mabodofutk** [comment]
The reason for this is that vscode directly concatenates its debug command after our `rm -r a_folder`, and the debug command starts with a "cd <workspace>;" command, and this will result `rm -r a_folder cd <workspace>` being executed and then the whole workspace will be deleted.

**Comment by roblourens** [comment]
Indeed, https://github.com/microsoft/vscode/issues/106743. We were trying to fix this but couldn't get it to work as expected
