### ISSUE TITLE
Cannot downoald VS-CODE stable build from the website

### ISSUE THREAD

**Issue by shaanaliyev** [microsoft/vscode#172699]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.74.3
- OS Version: Windows 10 Pro 19045

Steps to Reproduce:

1. Go to https://code.visualstudio.com/
2. Click the Download for Windows Stable Build

Your stable build download link is broken or something else. Because I tried every way to download it but no success. I can download the insiders version but I need the stable one. 

When I click download stable vesion button it redirects me to > https://az764295.vo.msecnd.net/stable/97dec172d3256f8ca4bfb2143f3f76b503ca0534/VSCodeUserSetup-x64-1.74.3.exe 
and then page crashes with _"This site can’t be reached, ERR_TIMED_OUT"_ error.
I have tried everything: phone, different pc, different network, VM, VPN on/off, extensions off still no success. Do you have any other official mirrors or how can I solve this?

**Comment by shaanaliyev** [comment]
I solved this by using VPN inside VM. But why? I still have no idea what's blocking it.

**Comment by joaomoreno** [comment]
Seems to be an issue with your system's network and/or networking environment. I suggest following up with your sysadmin.
