### ISSUE TITLE
Startup timings no longer compute on web

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#172623]
It looks like the move of the fibonacci numbers to a web worker fails on insiders.vscode.dev. In the console I see:

```
Uncaught SyntaxError: Function statements require a function name
```

The code points to this:

<img width="814" alt="image" src="https://user-images.githubusercontent.com/900690/215063968-f086ed7c-a63e-4c63-9777-add37c4ca0f3.png">

I found this only because the web perf bot no longer finishes, waiting for the startup timings console log message that we do here:

https://github.com/microsoft/vscode/blob/1ed7421b6d1edba54e51c7a8fb27201687cd2470/src/vs/workbench/contrib/performance/browser/startupTimings.ts#L97

I cannot step over this method, it seems to throw.

**Comment by jrieken** [comment]
also happens in desktop

**Comment by jrieken** [comment]
Looks like minification removes the function name and therefore it fails

<img width="831" alt="Screenshot 2023-01-27 at 11 45 10" src="https://user-images.githubusercontent.com/1794099/215067827-6ff362ee-ec74-4afc-b63e-09b71876d5b4.png">

**Comment by lorand-horvath** [comment]
I confirm the error `Uncaught SyntaxError: Function statements require a function name` on Windows, for the latest Insiders and Exploration builds.

**Comment by bpasero** [comment]
Works 👍
