### ISSUE TITLE
Extension pane should auto-refresh after importing a profile

### ISSUE THREAD

**Issue by TylerLeonhardt** [microsoft/vscode#172657]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 
- OS Version: 

Steps to Reproduce:

1. open https://insiders.vscode.dev/profile/github/35ae3b10eaffe9c6330e21accd3ac501
2. click on Extension viewlet
3. see that no extensions are installed
4. go back to profile and import it
5. go back to Extension viewlet

It still says no Extensions installed even though I just imported the profile and it installed 3 extensions.

I would expect that it refreshes automatically since we just took an action in vscode that installs extensions.

**Comment by sandy081** [comment]
This is fixed with new Profiles UI
