### ISSUE TITLE
Accept auto-complete suggestion by (almost) any key besides Enter

### ISSUE THREAD

**Issue by sktpin** [microsoft/vscode#172625]
Basically, replicate **Visual Studio** 's behavior.
Currently, in VSCode, one has to press Enter to accept a suggestion. That's completely superfluous and disrupts the flow.
Instead, if the selection bar is on the item in the suggestions list that I want, and I type the first character of what I want to have _after_ the insertion of the suggestion, the suggestion will be inserted _and_ the character will be entered after it.

E.g., I first type this content into the editor:

`flappyBird.`

The '.' causes a list of suggestions to be shown:

- Chirp( float frequency )
- Eat( int amount )
- _**FlapAction( float speed )**_
- Jump( float howHigh )

The highlighted suggestion is selected e.g. by cursor key.
Then I type the '(' character, and the editor will have this content:

`flappyBird.FlapAction(`

No extra pressing of a special key, like Enter, necessary at all.
If I decide that I don't want any of the suggestions, I just press Esc and the suggestions go away, like normal.

**Comment by jrieken** [comment]
Controlled by this setting: `editor.acceptSuggestionOnCommitCharacter` but the extension needs to define (per completion) what characters to use. Unfortunately the extension you are using is mystery
