### ISSUE TITLE
Wrong horizontal scrollbar height calculation with long lines

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#172604]
:bug: When there is a very very long line in a notebook cell, the horizontal scrollbar won't show up and scrolling doesn't work. For example, the first code cell in endgame.github-issues

<img width="1123" alt="image" src="https://user-images.githubusercontent.com/876920/214990658-17175ffe-fb8f-4c12-9879-c220548f0ead.png">

What happens is, in notebook cell, we would listen to the content height change of a cell, and when it updates, we will call `editor.layout` to adjust its height to the content height, so the editor grows with its content height (same pattern used in SCM input). We have been doing this from the beginning.

It works great if the line is short, or slightly wider than the viewport. If the line is very long, like what we have in the first cell in `endgame.github-issues`, we run into this infinite loop

* layout with initial dimension, viewport width: 500
* editor broadcast content size change (e.g., content width: 7000, content height: 112)
* we call `editor.layout({ width: 7000, height: 112})`
* editor broadcast content size change (content width: 302, content height: 100)
* ...
* editor broadcast content size change (content width: 7000, content height: 123)

and it repeats. It's weird that we kept shrinking to a very small content width and then grow. But `302` gave me some hints and I found it's likely caused by https://github.com/microsoft/vscode/commit/3ebfaadb9b856e58eef7d84d177a98dc6c149146. Increasing the constant to 1000 https://github.com/microsoft/vscode/commit/3ebfaadb9b856e58eef7d84d177a98dc6c149146#diff-cd23e0572865d341ade654016683fa9196ce4132180c423f7d687a6c27ce0d7aR394 fixed the scrollbar in the endgame notebook. Reverting the commit also fixes the problem.

@alexdima @hediet suggestions for how to fix this or workaround it in notebook land?

**Comment by rebornix** [comment]
It only happens with proportional font, for example, `Menlo, Monaco, 'Courier New', monospace` on macOS. It doesn't reproduce when using a monospace font.

**Comment by roblourens** [comment]
I wonder if we really want to fix this at this point, since it hasn't been reported in 6 weeks. I also can't get it to repro with the default font family.

**Comment by roblourens** [comment]
To the above point, it always reproes using the default settings, but many settings, like having font ligatures enabled, will make it work correctly.
