### ISSUE TITLE
ctrl+shift select code block   Abnormal behavior affects use

### ISSUE THREAD

**Issue by au-top** [microsoft/vscode#172644]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version:  Version: 1.74.3 (user setup)
Commit: 97dec172d3256f8ca4bfb2143f3f76b503ca0534
Date: 2023-01-09T16:59:02.252Z
Electron: 19.1.8
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.22621
Sandboxed: No
 
- OS Version:  Windows 11

Steps to Reproduce:

1. use ctrl+shift select code block
2. use ctrl + shift + -> or  ctrl + shift + <-

https://user-images.githubusercontent.com/44134842/215122008-c1209bf9-2e89-48f1-beb9-dcce16b99395.mp4

**Comment by au-top** [comment]
any update ?

**Comment by alexdima** [comment]
Let's first try to find out what command executes on your machine, with your settings and your keybindings when pressing `Ctrl+Shift+LeftArrow`. Could you please [try the following](https://github.com/microsoft/vscode/wiki/Keybinding-Issues#basic-troubleshooting):

* Run the command `Developer: Toggle Keyboard Shortcuts Troubleshooting`
* This will activate logging of dispatched keyboard shortcuts and will open an output panel with the corresponding log file.
* Press exactly the keybinding you desire.
* check what VS Code detects and what command is invoked.

If you are having trouble understanding the output, please feel free to paste here and I can try to help.

**Comment by au-top** [comment]
I use the dichotomy query method to debug the discovery settings `"editor.accessibilitySupport": "on" ` caused the problem
