### ISSUE TITLE
No `Show Local` when cloning from remote to local on desktop VS Code

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode#172673]
In virtual workspaces, the file dialog has a `Show Local` button. There's no such dialog in remote windows--the file dialog always shows the remote filesystem. This is an issue for continuing from a GitHub codespace to a local desktop clone when the user is in VS Code desktop.

Suggestion: when in a virtual or remote window on desktop, always have the 'Show Local' option in the file dialog.

**Comment by joyceerhl** [comment]
Oh interesting--there is a Show Local in the Open Folder flow, but not when the git extension invokes the file dialog: 
<img width="671" alt="image" src="https://user-images.githubusercontent.com/30305945/215204864-9a25e7fe-75cf-456d-ae3a-36946517f6e4.png">

**Comment by joyceerhl** [comment]
I see this was an intentional decision for extension access to the simple file dialog in a remote window in https://github.com/microsoft/vscode/commit/addaad3f996244b439de98f3c7c953f62efdec91 for https://github.com/microsoft/vscode/issues/110264

However that makes it hard to go from a remote window to a local one from extension land. Is this something that we can expose to extensions via a new proposed api option for the file dialog?

**Comment by alexr00** [comment]
Duplicate of https://github.com/microsoft/vscode/issues/131138, which is an API request to expose "show local".

**Comment by joyceerhl** [comment]
Reopening this to track adoption of #131138 in the Continue On flow.

**Comment by joyceerhl** [comment]
Steps:

Open a codespace in VS Code desktop
From the remote indicator, choose Continue in Local Clone
Ensure that the repo gets cloned successfully to your local machine
