### ISSUE TITLE
Pylance diagnostics hover word wrap eagerly 

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#172681]
Even though there are still spaces in the hover widget, it seems it still wraps 
<img width="1136" alt="image" src="https://user-images.githubusercontent.com/876920/215226424-e6c20ce5-0cfe-4502-baf5-79dd70c96eba.png">

**Comment by aiday-mar** [comment]
Hi @rebornix do you still see this issue with the latest release of VS Code?

**Comment by aiday-mar** [comment]
This will be closed optimistically. Feel free to comment here if you see this again.
