### ISSUE TITLE
Search results on hover dismiss button can't be unhidden

### ISSUE THREAD

**Issue by arsu-leo** [microsoft/vscode#172631]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.74.3 (user setup)
- OS Version: Windows_NT x64 10.0.19044

Steps to Reproduce:

1. Do a search in files with search from the activity bar (Ctrl-Shift-F)
2. Search any term with existing results within your files/project.
3. Hover mouse over any result and right click the dismiss button that appears on hover.
4. Click "Hide dismiss button"

Can't recover back the "dismiss button" that appeared on hover. You can still dismiss results with right click, but can't dismiss them anymore with a single click as I can't unhide the button.

Actually discovered that you can recover the button activating the Search and Replace, right clicking the replace button that appears on hover to enable the dismiss, but I'm afraid that if I hide that one as well, you may not be able to activate them back.

Other about info:
Commit: 97dec172d3256f8ca4bfb2143f3f76b503ca0534
Date: 2023-01-09T16:59:02.252Z
Electron: 19.1.8
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0

**Comment by ArturoDent** [comment]
The command `View: Reset All Menus` will restore any button that is hidden - but will do that for all buttons in all menus you may have hidden.

Also, right-clicking on the `Replace All` button at the top level of the Search Results has the option to bring the `Dismiss` button.

**Comment by arsu-leo** [comment]
> Also, right-clicking on the Replace All button at the top level of the Search Results has the option to bring the Dismiss button.
I did discover that, as noted on:
> Actually discovered that you can recover the button activating the Search and Replace, right clicking the replace button that appears on hover to enable the dismiss.
My issue was:
> I'm afraid that if I hide that one as well, you may not be able to activate them back.
This solves the issue anyways:
> The command View: Reset All Menus will restore any button that is hidden
I did not expect the command to differ from "Reset Menu" on right click of top buttons.

Thank you, hope this helps someone who lives as afraid as I am to lose options 🤣
