### ISSUE TITLE
Extension development view/item/context menu order is different locally vs published

### ISSUE THREAD

**Issue by miketalley** [microsoft/vscode#172670]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.74.3
- OS Version: Darwin arm64 21.6.0

#### Steps to Reproduce:

1. Create an extension and add the following to package.json
```
"contributes": {
  "menus": {  
    "view/item/context": [
      {
        "command": "config.setDefaultAccount",
        "when": "viewItem == accountTreeItem",
        "group": "view/item/context@997"
      },
      {
        "command": "config.renameAccount",
        "when": "viewItem == accountTreeItem",
        "group": "view/item/context@998"
      },
      {
        "command": "config.deleteAccount",
        "when": "viewItem == accountTreeItem",
        "group": "view/item/context@999"
      },
      {
        "command": "account.viewPersonalAccessKey",
        "when": "viewItem == accountTreeItem",
        "group": "accountTreeItemRightClick@1"
      }
    ]
  }
}
``` 
3. Hit `f5` to test the extension locally and look at the menu
![image](https://user-images.githubusercontent.com/6472448/215184697-8689240e-d957-47d2-915b-e05085814a54.png)

4. Publish the extension and look at the menu
![image](https://user-images.githubusercontent.com/6472448/215184649-139aa083-f115-4c9d-94fc-50ca6c2b5756.png)

#### Expected Result
The menu ordering is consistent between the local version and the published version.

**Comment by sandy081** [comment]
@jrieken Any idea why this can happen?

**Comment by jrieken** [comment]
Looks like the `group` info is getting lost or isn't honoured anymore. @miketalley Can you share the VSIX file or the marketplace link?

**Comment by sandy081** [comment]
Closing this because the requested information is not provided. Please provide the requested information to reopen the issue.
