### ISSUE TITLE
Please allow questions to be asked in the Microsoft Q&A 

### ISSUE THREAD

**Issue by ShervanN** [microsoft/vscode#172622]
Hi,

Why any question for VScode should be asked on the Stackoverflow website? I am not comfortable with  Stackoverflow.
Please allow questions to be asked in the Microsoft Q&A (Microsoft Learn). Like Visual Studio and other Microsoft products.

Thank  you

**Comment by stdedos** [comment]
... or here, in Discussions 😕

**Comment by roblourens** [comment]
This is an issue tracker for bugs and feature requests in vscode. There are other places where questions and discussions can happen, including github discussions https://github.com/microsoft/vscode-discussions/discussions

**Comment by stdedos** [comment]
> including github discussions [microsoft/vscode-discussions/discussions](https://github.com/microsoft/vscode-discussions/discussions)

Not accurate

![image](https://user-images.githubusercontent.com/133706/215152315-cca85d0c-0a41-47d8-b6a6-d6f3c1313968.png)

and

https://github.com/microsoft/vscode-discussions/discussions/5#:~:text=When%20will%20more,consider%20take%20action.
