### ISSUE TITLE
The Notebook cell editor isn't auto-scrolling when highlighting via mouse

### ISSUE THREAD

**Issue by TylerLeonhardt** [microsoft/vscode#172651]
![Recording 2023-01-27 at 09 01 08](https://user-images.githubusercontent.com/2644648/215148706-3e59c8dc-4a81-4025-9dea-7fd9f0741808.gif)

Steps:

* Use your mouse to select some text that is very long (goes off the screen)
* Try to select text off the screen by continuing your mouse to the right

In a notebook cell, it just stops. A normal text editor works fine.

**Comment by TylerLeonhardt** [comment]
I also noticed this in the regular editor: https://github.com/microsoft/vscode/issues/172652

**Comment by richard-fung-db** [comment]
I'm seeing a similar problem. My reproduction steps are:

* Have a ipynb notebook cell with text that is larger than the viewport of VSCode
* Use your mouse to select some text that is very long (goes off the screen)
* Try to select text off the screen by continuing your mouse up or down
* In a notebook cell, it just stops. A normal text editor works fine.

I've included a screen recording from Mac.


https://github.com/microsoft/vscode/assets/69175857/0260d5fa-78cf-4f0a-9fdc-5704bb650be4

**Comment by Yoyokrazy** [comment]
no longer repros
