### ISSUE TITLE
Enable extension signature verification by default in stable

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#172617]
Enable extension signature verification by default in stable

**Comment by bpasero** [comment]
Should be sanity tested on stable next week.

**Comment by sandy081** [comment]
To verify:

- Download the stable build from our builds page
- Open shared log from output view
- Install Gitlens extension
- Make sure the extension signature is verified and extension is installed
- Open settings and set `extensions.verifySignature` to `false`
- Install ESLint extension and make sure the extension signature is not verified and extension is installed.

**Comment by isidorn** [comment]
You can verify if the extension signature is verified by opening the Output - Shared channel and looking for a message like
`[info] Extension signature verification: eamodio.gitlens. Verification status: Verified.`
