### ISSUE TITLE
VSCode not running c++ programs , need guidance pls help 

### ISSUE THREAD

**Issue by Karan1562** [microsoft/vscode#172612]
<img width="1440" alt="12" src="https://user-images.githubusercontent.com/96478176/215037391-8ca1c466-985b-4b6d-b617-5f390142b4db.png">
<img width="1440" alt="13" src="https://user-images.githubusercontent.com/96478176/215037412-e89c5561-d69f-4f7f-b320-a3ca5150aecf.png">
<img width="1440" alt="14" src="https://user-images.githubusercontent.com/96478176/215037426-f0ad217a-7e4e-45ec-8867-4add2ee65467.png">

Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 
- OS Version: 

Whenever I click on run these pics show up with a column on the right side displaying run and debug , pls guide me on how to correct this

**Comment by roblourens** [comment]
I don't really understand the problem, looks like it ran successfully and printed the string? But if there is an issue please file it on the C++ extension repo
