### ISSUE TITLE
Can't launch code installed on network drive

### ISSUE THREAD

**Issue by dseynhae** [microsoft/vscode#172636]
Type: <b>Bug</b>

Take the Windows zip archive from the VS Code Download page, an install it on a Network Drive:

`P:\...\Programs\Microsoft VS Code`

Edit your User `Path` variable to find the `code.cmd` script:

`P:\...\Programs\Microsoft VS Code\bin`

Launch a CMD Terminal, and verify you're using this script:

`where code`

The `code` launch will crash:

```text
7328:0127/052649.784:ERROR:gpu_process_host.cc(974)] GPU process launch failed: error_code=18
[7328:0127/052649.830:ERROR:gpu_process_host.cc(974)] GPU process launch failed: error_code=18
[7328:0127/052649.893:ERROR:gpu_process_host.cc(974)] GPU process launch failed: error_code=18
[7328:0127/052649.895:ERROR:gpu_process_host.cc(974)] GPU process launch failed: error_code=18
[7328:0127/052649.895:ERROR:gpu_process_host.cc(974)] GPU process launch failed: error_code=18
[7328:0127/052650.049:ERROR:gpu_process_host.cc(974)] GPU process launch failed: error_code=18
[7328:0127/052650.054:ERROR:gpu_process_host.cc(974)] GPU process launch failed: error_code=18
[7328:0127/052650.268:ERROR:gpu_process_host.cc(974)] GPU process launch failed: error_code=18
[7328:0127/052650.275:ERROR:gpu_process_host.cc(974)] GPU process launch failed: error_code=18
[7328:0127/052650.275:FATAL:gpu_data_manager_impl_private.cc(450)] GPU process isn't usable. Goodbye.
```

* If I use the `--disable-gpu-sandbox` option, the application still crashes:

   ![image](https://user-images.githubusercontent.com/54114043/215102030-f8a58065-be6b-4c22-a059-efa00d18062a.png)

* If I'm using the `--no-sandbox` option, the problem seems to be resolved.

💡 If I move the `Microsoft VS Code` directory to a local drive (and update the `Path` accordingly), the problem goes away (no options needed to launch VS Code).

VS Code version: Code 1.74.3 (97dec172d3256f8ca4bfb2143f3f76b503ca0534, 2023-01-09T16:59:02.252Z)
OS version: Windows_NT x64 10.0.20348
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-2698 v4 @ 2.20GHz (4 x 2197)|
|GPU Status|2d_canvas: unavailable_software<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>opengl: disabled_off<br>rasterization: disabled_software<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|3.65GB (0.62GB free)|
|Process Argv|--no-sandbox --crash-reporter-id 1c1a2b60-b1a8-4215-9fc2-bc68c9c90187|
|Screen Reader|yes|
|VM|0%|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
oneapi-samples|int|0.0.47
isort|ms-|2022.8.0
python|ms-|2022.20.2
vscode-pylance|ms-|2023.1.40
jupyter|ms-|2022.11.1003412109
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.14
vscode-jupyter-cell-tags|ms-|0.1.6
vscode-jupyter-slideshow|ms-|0.1.5
powershell|ms-|2023.1.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscoreces:30445986
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
azure-dev_surveyone:30548225
vsccc:30610678
pyindex848cf:30577861
nodejswelcome1cf:30587006
2e4cg342:30602488
89544117:30613380
pythonsymbol12:30652348
2i9eh265:30646982
vscsb:30628654

```

</details>

**Comment by KelSolaar** [comment]
Same issue here, we were running 1.68.1 fine but 1.75.1 does not start, unsure when the regression was introduced.

**Comment by deepak1556** [comment]
This is a limitation in the runtime https://bugs.chromium.org/p/chromium/issues/detail?id=103902

You can disable the chromium sandbox following the steps here https://code.visualstudio.com/updates/v1_80#_disable-chromium-sandbox
