### ISSUE TITLE
List drag image no longer has a background

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#172621]
**Steps:**
* start to drag an item from the tree
* see how it does not have any background

`vscode-bisect` shows its this commit range: https://github.com/microsoft/vscode/compare/a0562ccdb202a29ac35da81c2b5482e517158f32...b89923233edbd4ccf38a216bffd8fb84dda72305

![Recording 2023-01-27 at 10 56 38](https://user-images.githubusercontent.com/900690/215058378-3087fbde-4d10-4f9f-88e1-5b1410c0aa73.gif)

**Comment by aeschli** [comment]
Works on Linux, but I can reproduce on WIndows
