### ISSUE TITLE
Copy shortcut not working in editor after making a selection in terminal.

### ISSUE THREAD

**Issue by itsakt** [Microsoft/vscode#17265]
- VSCode Version: 1.8.0 
- OS Version: Windows 10 x64

Steps to Reproduce:

1. Select some text in terminal
2. Select some text in one of opened editor
3. Press CTRL+C

Displays warning message saying 'Cannot copy terminal selection when terminal does not have focus'

**Comment by thenuts** [comment]
Same problem with me.

**Comment by Tyriar** [comment]
Closing as duplicate of https://github.com/Microsoft/vscode/issues/17232
