### ISSUE TITLE
Extension Packs should offer more than 2 rows of included extensions

### ISSUE THREAD

**Issue by a-stewart** [microsoft/vscode#172779]
Feature Request:

When we have an extension pack, we show a limited number of the included extensions, in a scroll container with no obvious scroll mechanism. (Note: the details section below it has a permanent scrollbar, but the extension pack section doesn't.)

![image](https://user-images.githubusercontent.com/150152/215479467-60fee5a2-3a51-4f4f-bbd7-7000d5386435.png)

IMO, for an extension pack, the included extensions are probably the most important part. If a pack includes hundreds of extensions, then a scrollable container makes sense, but I think for regular packs, it would make sense to give more space and show the full set of extensions being installed since that is likely what users care about?

In addition to increasing the number of rows, perhaps we could also make the scrollbar permanently visible.

**Comment by sandy081** [comment]
Extension pack section is scrollable, can you please check and confirm?

**Comment by a-stewart** [comment]
Yes, the section is scrollable, but the scrollbars are invisible by default, you only see that there are scrollbars once you interact with the area. The section below with the details has the scrollbars visible all the time.

**Comment by sandy081** [comment]
> Yes, the section is scrollable, but the scrollbars are invisible by default, 

This is true in general in VS Code UI.

@mjbvz Markdown view showing scrollbar in general is causing inconsistency here. May I know why it is like this?

**Comment by mjbvz** [comment]
@sandy081 Webviews use native scroll bars. We try to match the style of VS Code's scroll bar but can't exactly match their behavior, such as auto hiding them
