### ISSUE TITLE
VSCode freeze at markdown preview page

### ISSUE THREAD

**Issue by King66** [Microsoft/vscode#17272]
- VSCode Version: 1.8.0
- OS Version: Win10

Steps to Reproduce:

1.  open markdown preview page
2.  select text and drag
3.  switch to another tab and return to markdown preview tab
4.  select text and drag, then VSCode freeze
[md-freeze.zip](https://github.com/Microsoft/vscode/files/654129/md-freeze.zip)

**Comment by mjbvz** [comment]
closing as a duplicate of #16113. I'm investigating the issue

Thanks

**Comment by King66** [comment]
This issue seems to still exist on Code 1.10.0
