### ISSUE TITLE
Speaking about There is no translation

### ISSUE THREAD

**Issue by xhonker** [Microsoft/vscode#17276]
- VSCode Version: Code 1.8.0 (38746938a4ab94f2f57d9e1309c51fd6fb37553d, 2016-12-13T17:45:32.595Z)
- OS Version: Windows_NT ia32 10.0.14965
- Extensions:

|Extension|Author|Version|
|---|---|---|
|theme-onedark|azemoh|0.4.0|
|npm-intellisense|christian-kohler|1.1.0|
|path-intellisense|christian-kohler|1.2.0|
|vscode-eslint|dbaeumer|1.1.0|
|jquerysnippets|donjayamanne|0.0.1|
|vscode-babel-coloring|dzannotti|0.0.4|
|vscode-html-css|ecmel|0.0.30|
|auto-rename-tag|formulahendry|0.0.8|
|rest-client|humao|0.11.0|
|docthis|joelday|0.3.5|
|vue|liuji-jim|0.1.5|
|debugger-for-chrome|msjsdiag|2.3.1|
|cssclasshint|nicolasalcaraz|0.0.3|
|indenticator|SirTori|0.2.1|
|jsx|TwentyChung|0.0.1|
|vscode-react-native|vsmobile|0.2.4|
|JavaScriptSnippets|xabikos|1.2.0|
|ReactSnippets|xabikos|1.2.0|

---

Steps to Reproduce:

[1.]Not finished completely
![qq 20161215170022](https://cloud.githubusercontent.com/assets/20201169/21217620/1835fbdc-c2e8-11e6-8d69-fd9aafd3e9d5.png)

2.Previous versions of the problem alt+f12 After viewing Intelligent prompt Is not the  , All tipsIt's gone wild.

**Comment by kieferrm** [comment]
Well ship new translations in a 1.8.x build later.
