### ISSUE TITLE
Auto Guess Encoding not work properly

### ISSUE THREAD

**Issue by Stepan-H** [microsoft/vscode#172798]
Type: <b>Bug</b>

Auto guess encoding are very bad. Even though I write on 1st line in text file a set of specific characters, VS Code are not able to recognize. Specifically, the non-recognition of CP 852 set.

VS Code version: Code 1.74.3 (97dec172d3256f8ca4bfb2143f3f76b503ca0534, 2023-01-09T16:59:02.252Z)
OS version: Windows_NT x64 10.0.19045
Modes:
Sandboxed: No

**Comment by bpasero** [comment]
Please report to https://github.com/aadsm/jschardet with a reproducible example.
