### ISSUE TITLE
Allow to open zip archives in Explorer

### ISSUE THREAD

**Issue by FrenkyBojler** [Microsoft/vscode#17271]
It would be very nice and helpful if i can just click on zip archive in explorer and see all of the beautiful files in it :)

**Comment by minexew** [comment]
Shouldn't this be handled by an extension rather than making the editor even more bloated than it already is?

**Comment by myfairsyer** [comment]
I just saw that there's an extension for that on the marketplace: https://marketplace.visualstudio.com/items?itemName=slevesque.vscode-zipexplorer

Haven't tried it though
