### ISSUE TITLE
Readable and Combinable Profile

### ISSUE THREAD

**Issue by josStorer** [microsoft/vscode#172756]
Related Issue:
- #148829
- #166359

The current exported .code-profile file is defined as follows

```typescript
interface IUserDataProfileTemplate {
	readonly name: string;
	readonly shortName?: string;
	readonly settings?: string;
	readonly keybindings?: string;
	readonly tasks?: string;
	readonly snippets?: string;
	readonly globalState?: string;
	readonly extensions?: string;
}
```

The actual output can be found at https://github.com/microsoft/vscode/issues/148829#issuecomment-1120787767

@sandy081 thinks that editing a .code-profile file is a good candidate for an extension, but I think it would be more beneficial to generate more readable json files directly from vscode

For example, we can create some repos like `awesome-vscode-profiles` by community, or we can build an official profile marketplace to create a more out-of-the-box experience for different development environments

The current workspace approach and Extension Pack approach available in vscode are not good enough for the user experience, and with vscode Profile, we can switch development environments/configurations more easily, but the current .code-profile output file does not facilitate code management, which is not conducive to community development, and I think it is also bad to ask everyone to install a third-party extension for editing

With vscode Profile, community project scaffolding, and automated configuration scripts for different development environments, it would be possible to help users set up a development environment in a split second

In addition, I also suggest that different profiles be enabled at the same time, so that the user can combine them and choose which profile's configuration items to take. And for the item of extensions, we can enable multiple profiles

For example, we can enable a profile, the extensions of which are suitable for general text editing, such as TODO, KeyMap, etc., while for some programming languages (e.g. c#), or specific development environments (e.g. Unity3D), we can enable the special profiles of them at the same time

Maybe profiles are not designed to meet these, but I think it's a useful feature to be able to switch quickly between different environments instead of enabling them all. I don't think there is an elegant solution for vscode to use currently.

**Comment by sandy081** [comment]
Thanks for the feedback.

> @sandy081 thinks that editing a .code-profile file is a good candidate for an extension, but I think it would be more beneficial to generate more readable json files directly from vscode

At that time, VS Code does not have a way to define/preview a profile. Since we have made profile a first class concept in VS Code and one can use VS Code to draft a profile and generate `.code-profile` template out of it. There is no need of an extension to draft or preview a profile now. Please note that the some of the information in the file is cryptic (global state). So I still think there is no strong reason to make the profile template a readable. 

> In addition, I also suggest that different profiles be enabled at the same time,

Interesting thought! Since the feature is still new and fresh. I would wait for more user feedback.

Closing this issue, since there is no action to be taken here.
