### ISSUE TITLE
[Suggestion] [VSC-Web] HTTP request parameters interoperation

### ISSUE THREAD

**Issue by MasterInQuestion** [microsoft/vscode#172736]
Interpreting HTTP GET (provisionally also POST) parameters to enable certain interoperation:
    E.g. "settings" expecting the settings JSON, applying which to modify current settings.
    .
    This should significantly improve the app's portability. [ Via "https://vscode.dev/?settings=${JSON}" alike. ]
\
\
    Some similar but not as critical parameter suggestions:
    /<a href="https://regex101.com/?regex=(?:title|text|file|diff)%5Cd*&flags=">(?:title|text|file|diff)\d*</a>/:
    |&#x2A;| If "\d" (the optional trailing number) doesn't exist: assume 0.
    |&#x2A;| The /<a href="https://regex101.com/?regex=%5Cd%2B&flags=">\d+</a>/ must be unique for each tab. (e.g. no "file0" and "text0" at the same time)
    |&#x2A;| "title", "text": Correspondingly set the new files' title and content (text). [1]
    |&#x2A;| "file": The URI of files [2] to open.
    |&#x2A;| "diff": Diff views comparing the tabs to open (identified by the unique /<a href="https://regex101.com/?regex=%5Cd%2B&flags=">\d+</a>/). Expected input: /<a href="https://regex101.com/?regex=%5Cd%2B,%5Cd%2B&flags=">\d+,\d+</a>/ (comma separated numbers).

[1] When a "title" defined without corresponding "text": assume empty "text".
[2] Perhaps also internal tabs (e.g. "Settings" tab).

**Comment by Tyriar** [comment]
I don't understand what the request is?

**Comment by MasterInQuestion** [comment]
Much similar to what mentioned in [ [https://code.visualstudio.com/updates/v1_75#_profiles](https://code.visualstudio.com/updates/v1_75#_profiles) ].
    But more effective and reliable (for VSC-Web).
