### ISSUE TITLE
Grid: movement to x/y axis not working when split editor horizontal

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#172725]
I like how the sashes are now connected even for diff editor and joined editors, but this does not seem to work when the split editor is split horizontally:

![Recording 2023-01-29 at 13 39 52](https://user-images.githubusercontent.com/900690/215326798-50755a77-8233-4b39-a499-f8e0a306d4d7.gif)

**Comment by joaomoreno** [comment]
I didn't even know this was possible!
