### ISSUE TITLE
Add a setting to disable Auto-Detection of High Contrast

### ISSUE THREAD

**Issue by default0** [Microsoft/vscode#17279]
- VSCode Version: 1.8.0
- OS Version: Windows Version 6.3.9600 (Windows 8.1 Enterprise)

Steps to Reproduce:

1. Enable High Contrast on Windows
2. Start VS Code, look at the glorious High Contrast theme
3. Select a different theme, because you would rather work in that
4. Restart VS Code, your theme choice gets overridden.

Essentially, I'd like to be able to disable the auto-detection of the High Contrast theme I'm using in Windows via some setting, because while I prefer Windows in High Contrast mode, I dislike looking at VS Code's High Contrast theme.

**Comment by geirsagberg** [comment]
I wholeheartedly agree. I'm okay with the default being auto-detection, for the accessibility scenario, but it should definitely be possible to disable this functionality via settings.

**Comment by bpasero** [comment]
An option makes sense to me. If someone wants to provide a PR 👍

**Comment by geirsagberg** [comment]
@bpasero Done, https://github.com/Microsoft/vscode/pull/17394.

**Comment by geirsagberg** [comment]
Could you please re-open this issue?

Unfortunately, my PR only affected the high-contrast swap that occurred when changing Windows theme while VSCode is open, not the initial theme that is set when VSCode starts, or opens a new folder.

I have added a new PR #17832 that completes the fix.

**Comment by bpasero** [comment]
* [ ] **To verify (Windows):** 
Normally VS Code switches to HC mode automatically when windows is running in HC mode. Verify this new setting can be used to prevent this automatic switch from happening (both on startup as well as when Code is running and you change HC mode in Windows).
