### ISSUE TITLE
[File Watcher (parcel)] Unexpected error: No such file or directory

### ISSUE THREAD

**Issue by nosisky** [microsoft/vscode#172724]
Does this issue occur when all extensions are disabled?: Yes/

- VS Code Version: 1.74.3 (Universal)
- OS Version: MacOS Ventura Version 13.0.1

Steps to Reproduce:

1. Start VS code and open any folder tracked with GIT
2. Modify any of the code and the source control won't reflect the changes made in the code

Developer logs > WIndows, shows the below error:

```
2023-01-24 20:03:13.166 [error] [File Watcher (parcel)] Unexpected error: No such file or directory (EUNKNOWN) (path: /Users/UserName/Desktop/folder)
2023-01-24 20:03:13.167 [error] [File Watcher (universal)] restarting watcher after error: No such file or directory
2023-01-24 20:03:13.918 [error] [File Watcher (parcel)] Unexpected error: No such file or directory (EUNKNOWN) (path: /Users/UserName/Desktop/folder)
2023-01-24 20:03:13.919 [error] [File Watcher (universal)] restarting watcher after error: No such file or directory
```

The notifications section shows this error:

<img width="460" alt="hdgdV" src="https://user-images.githubusercontent.com/21035946/215326500-7e799314-b802-49f1-b09c-8a37aa2b2414.png">

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by nosisky** [comment]
Same issue with the insider version @bpasero  
<img width="457" alt="Screenshot 2023-01-30 at 18 41 58" src="https://user-images.githubusercontent.com/21035946/215553109-32e0933a-6df4-4bbd-bc2d-53a64843faad.png">

**Comment by bpasero** [comment]
@nosisky anything special you can share about the file system / hard drives / network shares used?

**Comment by nosisky** [comment]
Nothing special just a regular booted MacOS laptop. It used to work fine the issue just started unexpectedly when I noticed the source control was no longer showing the error. It has to do with the Parcel watcher, somehow it's not seeing any GIT-activated folders on my device.

**Comment by bpasero** [comment]
I wonder if this issue is being caused by an installed extension. Can you try to run VS Code without extensions? From the command line (NOT the integrated terminal in Code), execute: `code --disable-extensions` and try your steps again to see if it reproduces. If you see it is an issue with the extension, please file it against the extension repository itself.

**Comment by nosisky** [comment]
I have tried that, I also disabled all extensions still the same issue. I tried downloading an older version(1.63.0 (Universal)) but the logs show the below error:

```
[File Watcher (parcel)] correcting a path to watch that seems to be a symbolic link (original: /Users/Username/Desktop/App, real: /Users/username/Desktop/App)
```

**Comment by bpasero** [comment]
Hm, so it maybe possible that symbolic links are involved or the casing as it is used is different, does that ring any bells?

To see exactly how parcel operates, some logs would be needed. You can enable verbose logging when you run `code-insiders --verbose` and then from the command palette pick the command "Output: Show output channels" and then pick the "Window" logs. There anything that has "parcel" in the name if of interest.

**Comment by nosisky** [comment]
Thanks, @bpasero  I had two folders with the same name but different casing inside the `/Users` folder. Somehow, The watcher was tracking the `/username` instead of `/Username` which is the currently logged-in user, I had to rename the lowercase home folder and the error seems to disappear for now.
