### ISSUE TITLE
Allow pasting from outside of VSCode

### ISSUE THREAD

**Issue by opuu** [microsoft/vscode#172727]
Allow users to paste images from clipboard, also copying files from windows filesystem then pasting in explorer does not work, adding this feature would be very helpful.

Here you can see, I have an image copied to my clipboard but it is not paste-able.

<img width="348" alt="image" src="https://user-images.githubusercontent.com/77793409/215328872-4c76427c-b080-476d-81c7-678b1a991e47.png">

**Comment by lramos15** [comment]
\duplicate https://github.com/microsoft/vscode/issues/164
