### ISSUE TITLE
code-server's login state is not stable

### ISSUE THREAD

**Issue by ladyrick** [microsoft/vscode#172751]
code-server's login state is not stable.

I use `code-server serve-local` on my dev machine to start a server for me.
Then I open it in my browser.
Now I want to login with github to sync my settings.
Login will success. But after a while, when I refresh the page, the login state is gone.

Everytime I try to login, There is a different IP address as shown below. Is this going right?

![image](https://user-images.githubusercontent.com/10379994/215398242-25d684f5-1109-4141-8a20-33fa7dd64d13.png)

Version: 1.74.3
Commit: 97dec172d3256f8ca4bfb2143f3f76b503ca0534
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36
Embedder: server-distro

**Comment by bamurtaugh** [comment]
Hi there, thanks for opening!

We're glad you've been getting to try out the VS Code Server through the `code-server` CLI. In the November VS Code release, we made some notable changes to how you access the VS Code Server. Now tunneling is built-in to the VS Code `code` CLI, so you should use the `code` CLI instead as the `code-server` CLI is no longer being maintained. There is more information here: https://code.visualstudio.com/blogs/2022/12/07/remote-even-better.

At this time, there isn't a local mode, but we'll be sure to keep everyone updated if that is implemented. Thank you!

**Comment by ladyrick** [comment]
> Hi there, thanks for opening!
> 
> We're glad you've been getting to try out the VS Code Server through the `code-server` CLI. In the November VS Code release, we made some notable changes to how you access the VS Code Server. Now tunneling is built-in to the VS Code `code` CLI, so you should use the `code` CLI instead as the `code-server` CLI is no longer being maintained. There is more information here: https://code.visualstudio.com/blogs/2022/12/07/remote-even-better.
> 
> At this time, there isn't a local mode, but we'll be sure to keep everyone updated if that is implemented. Thank you!

Thank you for you reply.

I tried vscode tunnel before this issue.
And I find vscode tunnel is very slow.
While I can directly connect the target machine, why must I take a tour to vscode.dev?
