### ISSUE TITLE
Open file or Open folder creates dialog behind active window

### ISSUE THREAD

**Issue by 18392152392** [microsoft/vscode#172753]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.75
- OS Version: 

Steps to Reproduce:

1. I download the VSCode insiders on centos
2. when I open folder or open file
3. I found that creates dialog behind active window
4. I was much desired to use VSCode on centos or ubuntu, but this serious bug is deathful，Can you help to fix? I please you! 
5.thank you very very very much

**Comment by deepak1556** [comment]
Merging to https://github.com/microsoft/vscode/issues/146422

**Comment by 18392152392** [comment]
> Merging to #146422

I know it merges, But how to resolve this problem? what can we do?
