### ISSUE TITLE
Build failure: cannot find macro `concatcp` in this scope

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#172773]
https://dev.azure.com/monacotools/Monaco/_build/results?buildId=201258&view=logs&j=3bfe1a4a-5695-5b4a-1570-eeec3af65a6c&t=c71c4749-d8b6-535a-e2de-0f0e8a9b2caa

**Comment by connor4312** [comment]
https://github.com/microsoft/vscode/pull/172712
