### ISSUE TITLE
wired behaviour after switching back from another windows user

### ISSUE THREAD

**Issue by ameaninglessname** [microsoft/vscode#172717]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: Version: 1.74.3
Commit: 97dec172d3256f8ca4bfb2143f3f76b503ca0534
Date: 2023-01-09T16:59:02.252Z
Electron: 19.1.8
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.22621
Sandboxed: No
- OS Version: Edition	Windows 11 Pro
Version	22H2
Installed on	‎12/‎8/‎2022
OS build	22621.1194
Experience	Windows Feature Experience Pack 1000.22638.1000.0

Steps to Reproduce:

1. create two windows user A, B
2. open vscode in user A (minimized , full screen or normal window would behave differently)
3. login into user B
4. login back to user A

Additional information:

I installed the vscode in a path that only A could access.

**Comment by hediet** [comment]
Can you share a screenrecording?

**Comment by deepak1556** [comment]
I am unable to repro the issue with latest stable `1.85`, please confirm if the issue persists.

**Comment by ameaninglessname** [comment]
> I am unable to repro the issue with latest stable `1.85`, please confirm if the issue persists.

Me too, closed
