### ISSUE TITLE
Put VSCode in the background (minimize) when Powershell code starts

### ISSUE THREAD

**Issue by DanielP81** [microsoft/vscode#172737]
I use VSCode to create graphical interfaces with Powershell. A handy feature would be to be able to minimize VSCode as soon as you press F5 so that you can directly see and use the graphical interface. Gladly as an option in the settings.

**Comment by roblourens** [comment]
Usually when you start a program, that program comes to the foreground. Is the powershell window starting in the background when you start debugging? Maybe that can be fixed.

**Comment by DanielP81** [comment]
Yes, the Powershell window starts in background. I have not found any settings in my config.

**Comment by roblourens** [comment]
I think the right solution is figuring out how to get the powershell window to go to the front, because it could be spawned behind any other open windows, not just vscode.
