### ISSUE TITLE
Call Stack: Frame could not be restarted when debugging

### ISSUE THREAD

**Issue by chopin2256** [microsoft/vscode#172820]
Type: <b>Bug</b>

<h2>Description</h2>
When debugging at a breakpoint and using the callstack, restarting a frame no longer works for me, but used to. I've updated my node to latest version and created a simple test which is attached as a video. At the bottom right, you can see the message <i>Frame could not be restarted</i>

[Restart Frame Not Working](https://user-images.githubusercontent.com/5911283/215542184-5e2e39aa-f3c9-4f8a-bcb3-e858d60fdfe7.mp4)

VS Code version: Code 1.74.3 (97dec172d3256f8ca4bfb2143f3f76b503ca0534, 2023-01-09T16:59:02.252Z)
OS version: Windows_NT x64 10.0.19045
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 3800X 8-Core Processor (16 x 3395)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.89GB (16.52GB free)|
|Process Argv|--crash-reporter-id fabd597e-7465-4a75-969f-01937aaa0b28|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-css-formatter|aes|1.0.2
classdiagram-ts|Ale|0.1.67
jsonviewer|cci|1.3.2
javascript-ejs-support|Dig|1.3.1
gitlens|eam|13.2.0
vscode-firefox-debug|fir|2.9.8
debug-visualizer|hed|2.4.0
hexeditor|ms-|1.9.11
php-debug|xde|1.30.0
</details>

**Comment by connor4312** [comment]
V8 removed Restart Frame https://chromium.googlesource.com/v8/v8/+/93f85699e22df958618206dbf94a790cf0bad8c4

They recently brought it back, but the version of Node you're using might not include that.

**Comment by connor4312** [comment]
You can see the commit I linked for their reasoning for removing the feature, as well as the associated bug https://bugs.chromium.org/p/chromium/issues/detail?id=1203606

**Comment by chopin2256** [comment]
Oh, actually my question is around something a bit different. I was never able to understand why VBA / .NET debugging was so much better than VSCode debugging. This is related to moving the "step through arrow" which does not exist in VSCode. The old school VBA editor is fantastic because it allows this. If you aren't sure what I mean, I can do a quick video demo.

**Comment by connor4312** [comment]
I'm not sure what you mean, can you share a recording or link docs (gifcap.dev is useful)

**Comment by chopin2256** [comment]
Please see my vba debugging here, it's been awhile but it came back quickly. I forgot how superior this old editor was! I miss this style of debugging. It's available in Visual Studio as well, where you can move around the arrow pointer to create tests on the fly. If there is any chance this functionality can be brought into VS Code, this would greatly speed up my current work flow!

But is there any reason that you know of, why moving the arrow pointer is not possible in VS Code? Does it have to do with the Javascript language?

https://user-images.githubusercontent.com/5911283/215593913-72ad9db3-6173-4280-9342-9d7d6ee68d78.mp4

**Comment by connor4312** [comment]
The "dragging" experience could be essentially a restart frame call + run to cursor. I suggest opening a new feature request on us for that.

The function editing was previously globally supported in V8, but was heavily restricted earlier (as referenced in the bug I linked too): https://chromium-review.googlesource.com/c/v8/v8/+/2846892 I'm not sure the cost/benefit is good with the restrictions that are in place, especially with how commonly used other ways of reloading code in JS already are, like Nodemon or HMR. And I get a headache thinking about how that would work in TypeScript or other scenarios where compilation is involved 😛

**Comment by chopin2256** [comment]
I'm going to check out Nodemon actually, thanks for that! And I think I will suggest the dragging functionality, however, if V8 doesn't support live edit, there is no point I suppose. You have to admit though, that dragging functionality is really amazing technology! It's too bad that more developers don't see its amazing value.
