### ISSUE TITLE
Merge Editor keyboard shortcuts don't work

### ISSUE THREAD

**Issue by kendonB** [microsoft/vscode#172864]
Type: <b>Bug</b>

My keyboard shortcuts are here and I have noted the current behaviour in caps:

```
    // resolve in merge editor - WORKS
    {
        "key": "ctrl+k ctrl+m",
        "command": "git.openMergeEditor"
    },
    // merge-conflict.accept.incoming - ERROR: Editor cursor is not within a merge conflict
    {
        "key": "ctrl+shift+alt+i",
        "command": "merge-conflict.accept.incoming"
    },
    // merge-conflict.accept.current - ERROR: Editor cursor is not within a merge conflict
    {
        "key": "ctrl+shift+alt+c",
        "command": "merge-conflict.accept.current"
    },
    // next conflict - ERROR: No merge conflicts found in this file
    {
        "key": "ctrl+shift+alt+n",
        "command": "merge-conflict.next"
    },
    // previous conflict - ERROR: No merge conflicts found in this file
    {
        "key": "ctrl+shift+alt+p",
        "command": "merge-conflict.previous"
    },
```
 The accept commands yield the error "Editor cursor is not within a merge conflict" and the next/previous commands yield the error "No merge conflicts found in this file".

VS Code version: Code 1.74.3 (97dec172d3256f8ca4bfb2143f3f76b503ca0534, 2023-01-09T16:57:40.428Z)
OS version: Linux x64 5.18.0-051800-generic
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|12th Gen Intel(R) Core(TM) i7-1270P (16 x 2500)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|1, 1, 1|
|Memory (System)|31.05GB (19.68GB free)|
|Process Argv|/home/kendonb/Scarlatti Dropbox/Kenny Bell/projects/olw_llu_dashboard/ --crash-reporter-id 109ba974-f9f3-4dd2-ae16-615ad0e4b375|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu-xorg|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu-xorg|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (22)</summary>

Extension|Author (truncated)|Version
---|---|---
path-intellisense|chr|2.8.4
copilot|Git|1.71.8269
gc-excelviewer|Gra|4.2.56
path-autocomplete|ion|1.22.1
language-julia|jul|1.38.2
csharp|ms-|1.25.4
isort|ms-|2022.8.0
python|ms-|2022.20.2
vscode-pylance|ms-|2023.1.40
jupyter|ms-|2022.11.1003412109
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.14
vscode-jupyter-cell-tags|ms-|0.1.6
vscode-jupyter-slideshow|ms-|0.1.5
cmake-tools|ms-|1.13.43
cpptools|ms-|1.13.9
cpptools-extension-pack|ms-|1.3.0
quarto|qua|1.59.0
r|REd|2.7.0
tabletopsimulator-lua|rol|1.1.3
lua|sum|3.6.7
cmake|twx|0.0.17

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
azure-dev_surveyone:30548225
pyindex848:30577860
nodejswelcome1:30587005
3biah626:30602489
89544117:30613380

```

</details>

**Comment by hediet** [comment]
Are you in the 3 way merge editor? The `merge-conflict` commands don't  work there.

**Comment by kendonB** [comment]
Yes I'm in the 3 way merge editor. Do any merge-related keyboard shortcuts work there?

**Comment by hediet** [comment]
Unfortunately, not. The 3 way merge editor has separate commands - they don't have a keybinding yet.

**Comment by kendonB** [comment]
What are the names of the commands? I can't see those in there at all (if they are indeed different to what's in my OP).
