### ISSUE TITLE
ENTER after ctrl-shift-f should lead to the first search result.

### ISSUE THREAD

**Issue by guettli** [microsoft/vscode#172894]
I am not happy with ctrl-shift-f.

My steps:

1. I hit ctrl-shift-f
2. I enter the search term
3. I see several search results.
4. I want to go to the first match
5. grrrr: There is no easy way to get to the first search result. After that I want to use up/down keys to go through the search results. The focus should not be in the source code.

Screenshot of state of Step 5:

![image](https://user-images.githubusercontent.com/414336/215702909-4dc26981-ad8e-48f8-87ad-202b17cb482d.png)

Goal:

Up to now I use the mouse and click on the first search result. If I use the mouse, I am at this state:

![image](https://user-images.githubusercontent.com/414336/215703062-4401aaf3-18fe-469e-bd3c-25424c3334bb.png)

# Feature request: ENTER should get to the first match.

After thinking about this some days, I think the best solution would be to map the ENTER to "Go to first search result".

But not like F4, since F4 moves the cursor to the file, and not to the search result list.

The ENTER should give the first item in the search result the focus. Then I can navigate to the matching result, and the next ENTER will bring me to the source code line.

This would be great for all people who can't or don't want to use a mouse.

Related: [Reddit, I am not happy with ctrl-shift-f](https://www.reddit.com/r/vscode/comments/10p24ce/i_am_not_happy_with_ctrlshiftf_search/)

**Comment by andreamah** [comment]
Hi again! I'm just a bit confused on this part:
> But not like F4, since F4 moves the cursor to the file, and not to the search result list.

For me, F4 moves to the first match, not the first file. Is this not what you're seeing?
![Recording 2023-01-31 at 08 27 09](https://user-images.githubusercontent.com/31675041/215821053-d14f1578-528d-4c0d-a362-42fecab0c43d.gif)

**Comment by ArturoDent** [comment]
I think right now this might be the best you can do:

```jsonc
{
  "key": "alt+enter",
  "command": "search.action.focusSearchList",
  "when": "searchInputBoxFocus"
}
```

`search.action.focusSearchList` is a better command to consider than what you were using.  The problem is that <kbd>Enter</kbd> is used to re-run the search if you make any changes to the inputs.

But the above keybinding does focus the first result without moving the cursor, and then <kbd>Enter</kbd> does move the cursor.

**Comment by guettli** [comment]
> I think right now this might be the best you can do:
> 
> ```js
> {
>   "key": "alt+enter",
>   "command": "search.action.focusSearchList",
>   "when": "searchInputBoxFocus"
> }
> ```
> 
> `search.action.focusSearchList` is a better command to consider than what you were using. The problem is that Enter is used to re-run the search if you make any changes to the inputs.
> 
> But the above keybinding does focus the first result without moving the cursor, and then Enter does move the cursor.

@ArturoDent  thank you very much.

If I add they keybinding via "Open Keyboard Shortcuts (JSON)", it works. But not always. After alt+enter I would like to use the up/down arrow keys and see the preview in the files. The strange thing: sometimes up/down shows me the places in the files (and the current entry in the result list is highlighted in blue color), and sometimes up/down does not show me the preview in the files.

We are on the right track, but not there yet. 

Thank you very much for your kind support.

**Comment by guettli** [comment]
> Hi again! I'm just a bit confused on this part:
> 
> > But not like F4, since F4 moves the cursor to the file, and not to the search result list.
> 
> For me, F4 moves to the first match, not the first file. Is this not what you're seeing? 

For me, F4 moves to the first match. If I press up/down keys, the cursor moves in the file. But I would like to move up/down in the search result list and see the preview on the right side (in the window of the source code editor).

**Comment by andreamah** [comment]
Hmm, that's interesting, I'm also seeing that the files aren't previewing after using `focusSearchList`. will look into this more.

**Comment by andreamah** [comment]
I think I can get reproducible steps to the state where the file doesn't open when you have it highlighted in the tree view

1. perform a long search
2. while it is searching, run `Search: Focus List` 
3. when using the up/down arrows to browse the search results, the file preview isn't triggering :bug:
4. the tree node is focused, but not selected :bug:

This bug might be related to #163003
