### ISSUE TITLE
VSCode can't find binaries in my path (eslint)

### ISSUE THREAD

**Issue by victornoel** [Microsoft/vscode#17282]
- VSCode Version: 1.8.0
- OS Version: Archlinux

Hi,

I have some binaries such as eslint, jshint or tslint in a user defined binary directory (`/home/user/.config/yarn/global/node_modules/.bin/`).
This directly is added to the `PATH` at session startup and is visible to vscode.
I checked in the `/proc/pid/environ` file of my running vscode (actually I checked the process that run the jshint server as well as the one for the workspace) that it has the PATH environment variable correctly set.

Still, when I open a `.js` file, I get the following message:
![image](https://cloud.githubusercontent.com/assets/160975/21218484/1ff5b948-c2b1-11e6-8a80-b84be1f166c9.png)

It is the same for eslint:
```
[Info  - 10:21:51] ESLint server is running.
[Info  - 10:21:51] 
Failed to load the ESLint library for the document /home/vnoel/Linagora/Petals/dev/git/petals-cockpit-new/frontend/generate-headers.js

To use ESLint in this workspace please install eslint using 'npm install eslint' or globally using 'npm install -g eslint'.
You need to reopen the workspace after installing eslint.
```

Surprisingly I don't have the problem with tslint even though it is in the same path…

**Comment by kieferrm** [comment]
@dbaeumer for ESLint.

**Comment by kieferrm** [comment]
Created #17464 for jshint.

**Comment by dbaeumer** [comment]
@victornoel the ESLint extension doesn't use ESLint from the path. The extension loads the eslint npm module via require in a running node process and we keep that process alive to not start it after every change of a file. This is why you need to install ESLint either into the workspace folder or globally. Alternatively you can set the eslint.nodePath setting to point to a location that is uncommon. In your case you could set it to `/home/user/.config/yarn/global/node_modules` which should do the trick.

**Comment by victornoel** [comment]
@dbaeumer I see, this wasn't so clear to me, thank you for the clarification!

**Comment by victornoel** [comment]
@dbaeumer just a quick question, when it is installed globally, which path is used to look it up by default?

**Comment by dbaeumer** [comment]
The resolving sequence is as follows: first eslint.nodePath if set, then relative to the file that is validates up the parent directory chain and then globally.

**Comment by victornoel** [comment]
@dbaeumer I meant what is the global path where it is looked up? Is it in all the paths present in NODE_PATH variable?

**Comment by dbaeumer** [comment]
Yes, it looks into all paths present in NODE_PATH. This is what node does by default and we wrote a `script` to reuse Node's resolve algorithm here.

**Comment by victornoel** [comment]
Thanks! So I guess the simplest and most generic solution to my problem is to add `/home/user/.config/yarn/global/node_modules` to NODE_PATH then :)

**Comment by dbaeumer** [comment]
Yes that is correct.
