### ISSUE TITLE
Display problem when running VSCode as Administrator

### ISSUE THREAD

**Issue by Iluvatar63** [microsoft/vscode#172891]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.74.3
- OS Version: Windows 10 Entreprise 21H2 Windows Feature Experience Pack 120.2212.4190.0

Steps to Reproduce:

1. Uninstall VSCode, delete folders %APPDATA%\Code and %USERPROFILE%\.vscode
2. Install VSCode (last version)
3. Run as administrator
4. Try to display release note, it's empty
5. 
![image](https://user-images.githubusercontent.com/8385410/215690517-1065e8e8-9f16-4ca7-9297-c7e0604c0247.png)
6. Go to extension panel, a click on the 1st one, the details panel is empty
7. 
![image](https://user-images.githubusercontent.com/8385410/215690767-5cc1d7a7-9bfe-4fc1-becc-a4934cddae1d.png)
8. You can test it on all extension, it will be the same behavior
9. Close VSCode
10. Launch VSCode without admin privilege
11. Click on release note
12. 
![image](https://user-images.githubusercontent.com/8385410/215691340-7ea82564-3eee-46e7-894f-94e31c83c634.png)
13. Go to extension panel, click on the same extension, information are displayed in details panel
14. 
![image](https://user-images.githubusercontent.com/8385410/215691512-fbea36bf-9478-44b2-a27f-0a22f15a9e28.png)

All render failed when I run VSCode in administrator. I use PlantUML extension and I use preview feature. If I run in Admin I cannot get a working preview (ALT+D), I need to close and launch VSCode without admin privilege.

**Comment by deepak1556** [comment]
Are you running under applocker ?

**Comment by Iluvatar63** [comment]
This is a professional desktop, so I will say yes. 
When I ran Get-AppLockerPolicy -local command i got
![image](https://user-images.githubusercontent.com/8385410/216250207-5a4a396c-17fd-4d87-91db-8af72325bfe6.png)
And when I run Get-AppLockerPolicy -Effective -Xml, I got multiple returns.
Do you need to check a specific one?

**Comment by deepak1556** [comment]
Are you able to run as administrator when launching VSCode with the following command line flags `code.cmd --no-sandbox --disable-gpu-sandbox` ?

**Comment by Iluvatar63** [comment]
When I ran this command from a PowerShell run as administrator, I got
![image](https://user-images.githubusercontent.com/8385410/216254941-084ebc4b-43e7-470e-bf88-e832345cf6a3.png)
But it launch VSCode with Admin privilege
![image](https://user-images.githubusercontent.com/8385410/216255071-d448dd73-bacf-474a-ad1a-4419afdc8814.png)
And I can access to release note
![image](https://user-images.githubusercontent.com/8385410/216255231-74723ad4-29c3-4b82-b9b2-a829e9d6c86b.png)
Or extension details
![image](https://user-images.githubusercontent.com/8385410/216255329-c428ab4e-c095-45b9-b7e7-2d823a51c81b.png)
And I can generate PlantUML diagrams
![image](https://user-images.githubusercontent.com/8385410/216255603-1c7a5199-8473-48de-974b-41395105b03d.png)

**Comment by deepak1556** [comment]
Thanks for confirming, I will merge this to https://github.com/microsoft/vscode/issues/122951 which is already tracking the root cause. Please continue to use the flags as workaround if you need to launch as admin.

**Comment by Iluvatar63** [comment]
Thanks for support :)
