### ISSUE TITLE
error stack is undefined when my extension is activated

### ISSUE THREAD

**Issue by capaj** [Microsoft/vscode#17285]
- VSCode Version: 
Version 1.8.0
Commit 38746938a4ab94f2f57d9e1309c51fd6fb37553d
Date 2016-12-13T18:03:00.506Z
Shell 1.4.6
Renderer 53.0.2785.143
Node 6.5.0
- OS Version: ubuntu 16.04

Steps to Reproduce:

1. checkout https://github.com/capaj/vscode-exports-autocomplete/tree/vs-code-activation-issue
2. install npm deps with yarn or npm
2. run in debug mode

output:
```
Activating extension `capaj.vscode-exports-autocomplete` failed: {1}.
Activating extension `capaj.vscode-exports-autocomplete` failed:  undefined
Here is the error stack:  undefined
```

It really isn't that helpful to print out undefined. I realized that my problem is, I am requiring a package `babel-traverse` which is not in node_modules because I did not specify it in package.json. It would be helpful if these kind of errors were properly shown to the user.

**Comment by jrieken** [comment]
@capaj I am not able to reproduce, neither with the repo mentioned above nor with an extension that throws on activate.

**Comment by capaj** [comment]
I know. I will lock the dependency so it is possible to replicate.

**Comment by jrieken** [comment]
Yeah, did that but it still doesn't repo.

**Comment by alexkrechik** [comment]
Reproduced this error with my app on several PC's - https://github.com/alexkrechik/VSCucumberAutoComplete.
After following steps from https://github.com/alexkrechik/VSCucumberAutoComplete#how-to-install - language server just doesn't work. 

After gclient folder opening and running it in debug mode - u will get error like in description:

```
Activating extension `vscode.cucumberautocomplete-client` failed: {1}.
Activating extension `vscode.cucumberautocomplete-client` failed:  undefined
Here is the error stack:  undefined
```

**Comment by jrieken** [comment]
I could repo this when the `main` property in `package.json` points to a invalid file

**Comment by LaurentTreguier** [comment]
I don't know if this is related, but I have this exact error message when trying to use the [`lzma-native`](https://www.npmjs.com/package/lzma-native) module in VSCode. It works fine with regular Node.js scripts, but not in VSCode... Simply creating a new extension with `yo code`, adding `lzma-native` as dependency and trying to `console.log` it results in
```
Activating extension `dlang-vscode.dlang` failed: {1}.
Activating extension `dlang-vscode.dlang` failed:  undefined
Here is the error stack:  undefined
```

**Comment by jeremyrajan** [comment]
Hi guys,

Not sure if its relevant, but I am also getting similar error here. But while debugging the ext locally works fine. But after I package and install it later. This error shows up. I tried install with npm 2 and npm3, to see if that was the issue as I read about it. But doesn't seem to work:

![image](https://cloud.githubusercontent.com/assets/2890683/22385148/94f1a366-e4f7-11e6-950b-aa7bfeb1d4ee.png)

Version 1.8.1 (1.8.1)

Ext link: https://marketplace.visualstudio.com/items?itemName=jeremyrajan.vscode-lebab

@alexandrudima / @jrieken any idea? :)

Thanks a lot.

Cheers,
Jeremy
