### ISSUE TITLE
Enable remote terminals to be run in systemd, where available

### ISSUE THREAD

**Issue by MarkZuber** [microsoft/vscode#172876]
On remote Linux machines, we'd like to be able to run the VS Code terminals within a systemd slice.  This enables us to be able to set resource usage limits and direct OOM kills to a particular slice so we can manage processes in our infra.  Everything created under a slice parents up to the main slice so the sub-processes (such as large build jobs) can be managed separately while having vscode-server run within a different slice to enable protection for vscode-server and avoid possible connectivity loss.

**Comment by Tyriar** [comment]
Closing off because of decision in https://github.com/microsoft/vscode/pull/172878#pullrequestreview-1327135863
