### ISSUE TITLE
Code navigation in markdown edit mode

### ISSUE THREAD

**Issue by tinganho** [Microsoft/vscode#17288]
It would be awesome if code can support code navigation on edit mode as well. So for instance, `cmd + click` on some of the links below will navigate to the appropriate section. Right now, code navigation is only supported in preview mode. 
```
## Table of Contents
* [Goals](#goals)
* [Non-Goals](#non-goals)
* [Overview](#overview)
```

**Comment by CAtoDC** [comment]
I would love to see a table of contents like that used in StackEdit.   It's a simple [TOC] that captures all the heading tags.
