### ISSUE TITLE
Adopt implicit activation events across all extension points

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode#172869]
- [x] https://github.com/microsoft/vscode/issues/167949
- [x] https://github.com/microsoft/vscode/issues/172065
- [x] https://github.com/microsoft/vscode/issues/167961
- [x] https://github.com/microsoft/vscode/issues/172316

**Comment by joyceerhl** [comment]
Reopening for `onTaskType`.

**Comment by Tyriar** [comment]
Just https://github.com/microsoft/vscode/issues/172065 left, let's track there
