### ISSUE TITLE
"Continue Working On" does nothing if I haven't opened VS Code before

### ISSUE THREAD

**Issue by bamurtaugh** [microsoft/vscode#172831]
I'm testing in a fresh Windows 10 VM.

Steps to Reproduce:

1. Install VS Code in VM, but don't open it
2. Go to https://vscode.dev/github/bamurtaugh/python-tuples in Edge in the VM
3. Continue Working On -> Reopen Remote Repository on the Desktop
4. :bug: Nothing happens
5. If I open VS Code desktop and then try the Continue Working On flow in web again, I am prompted, so I think this has to do with not having opened VS Code before on this VM

**Comment by joyceerhl** [comment]
This sounds like an issue with browsers opening protocol URLs and/or protocol URL handler installation.

**Comment by joyceerhl** [comment]
I believe this is because we use `app.setAsDefaultProtocolClient` to register VS Code as the protocol URL handler for `vscode://` URIs, which requires that the app has been launched first. From GitHub Copilot:

> No, Electron apps cannot register protocol URL handlers without ever having been launched. The registration of the protocol URL handler happens at runtime when the app is launched, using the `app.setAsDefaultProtocolClient(protocol)` function.
> 
> However, you can add protocol handlers to your app's manifest file during the build process, which will register them when the app is installed. This is platform-specific and outside of Electron's API. For example, on Windows, you can add entries to the app's manifest file, and on macOS, you can add entries to the app's Info.plist file.
> 
> For Windows, you might use a tool like [electron-builder](https://www.electron.build/configuration/configuration), which allows you to specify protocol handlers in the build configuration. Here's an example:
> 
> ```json
> "build": {
>   "appId": "your.id",
>   "win": {
>     "target": "nsis"
>   },
>   "protocols": [{
>     "name": "My App Protocol",
>     "schemes": ["myapp"]
>   }]
> }
> ```
> 
> For macOS, you can add entries to the app's Info.plist file:
> 
> ```xml
> <key>CFBundleURLTypes</key>
> <array>
>   <dict>
>     <key>CFBundleURLName</key>
>     <string>myapp</string>
>     <key>CFBundleURLSchemes</key>
>     <array>
>       <string>myapp</string>
>     </array>
>   </dict>
> </array>
> ```
> 
> Remember, these methods are platform-specific and outside of Electron's API. They also require that the app be installed, not just downloaded.
