### ISSUE TITLE
Bug: Snippets using "$" not "${" as tab indexes.

### ISSUE THREAD

**Issue by jonoHawkins** [Microsoft/vscode#17287]
- VSCode Version: Code 1.8.0 (38746938a4ab94f2f57d9e1309c51fd6fb37553d, 2016-12-13T17:38:28.425Z)
- OS Version: Darwin x64 15.6.0
- Extensions:

|Extension|Author|Version|
|---|---|---|
|base16-themes|AndrsDC|1.0.6|
|JSDocTagComplete|HookyQR|0.0.2|
|material-icon-theme|PKief|1.1.4|
|lorem-ipsum|Tyriar|1.0.0|
|theme-toothpaste|aalaap|0.0.1|
|vscode-color|anseki|0.2.2|
|theme-material|bcmarinacci|1.3.0|
|theme-material-neutral|bernardodsanderson|0.9.0|
|htmltagwrap|bradgashler|0.0.3|
|theme-dracula|dracula-theme|1.2.5|
|php-intellisense|felixfbecker|0.0.12|
|spacegray-vscode|ionutvmi|1.1.4|
|markdown-table-formatter|josa|0.0.4|
|theme-material-theme|jprestidge|1.0.1|
|vscode-scss|mrmlnc|0.6.0|
|Theme-TomorrowKit|ms-vscode|0.1.3|
|sublime-keybindings|ms-vscode|1.8.0|
|stylelint|shinnn|0.20.4|
|code-spell-checker|streetsidesoftware|0.12.2|
|gitblame|waderyan|1.3.0|
|change-case|wmaurer|1.0.0|
|Material-theme|zhuangtongfa|1.0.3|

---

Steps to Reproduce:

1. Create PHP snippet:
```
{
	"CDN": {
		"prefix": "cdn",
		"body": [
			"$this->cdn($1)$2"
		],
		"description": "Insert a view->cdn method call."
	}
}
```
2. Open a PHP file and run the snippet. Output is `this->cdn()`  with "this" selected. Should output `$this->cdn()` with caret within the cdn call.

**Comment by xsintill** [comment]
escape the $ sign using \\\

in your case use the following for the body:
"\\\\$this->cdn($1)$2"

**Comment by jonoHawkins** [comment]
Thanks
