### ISSUE TITLE
[Bug] Invisible / non-breakable space are not highlighted depending on the adjacent character

### ISSUE THREAD

**Issue by thom4parisot** [microsoft/vscode#172999]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: vscode.dev / monaco-editor playground
- OS Version: Firefox 109

Steps to Reproduce:

1. Copy paste the following code in an editor (online, playground or Diff in VSCode, as default Markdown settings do not highlight invisible chars):

```
“ coucou ”
" coucou "
« coucou »

---

a“ coucou ”
a" coucou "
a« coucou »
```

All single word in this example are wrapped in non-breakable space (Option + Space on macOS).
BUT, depending on which kind of quote surround them, they are not highlighted.

<img width="108" alt="image" src="https://user-images.githubusercontent.com/138627/215959492-3ca29600-30a4-4eaa-847e-bbc655bd261e.png">

On the first three examples, only the straight quotes enable the highligted quotes to be displayed.

Also, on the last three examples, when the left quote has a word-char before (the `a` char in this example), the non-breakable spaces are then highligted.

The expectations:

- On the first three examples, all the invisible spaces should be highlighted.
- On the last three examples, all the invisible spaces should be highlighted (which is correct).

It sounds like a regex not matching some unicode chars — maybe one of `vs/base/common/strings.ts`? But I'm not fluent enough in Unicode ranges and VSCode to have an idea of what's going on here.

Any help appreciated,
Happy to bring in clarification in case of not being clear enough.

Cheers,

Thom

**Comment by hediet** [comment]
I cannot reproduce:

![image](https://user-images.githubusercontent.com/2931520/216368313-e8f3a411-46fe-470d-87c8-e1731ce628a1.png)

Also, the text of your issue contains no non-breakable space, but GitHub may have removed it.

**Comment by thom4parisot** [comment]
Indeed, GitHub removes the non-breaking spaces in the output. When you edit/get raw message it's fine.

I copy/pasted the above example in the Monarch editor:

![image](https://user-images.githubusercontent.com/138627/216373495-7815dcc5-8019-4ebe-8108-acf5651ee282.png)

What is the output of your IDE when you disable "invalid characters" (they are invalid for coding, but actually used for text editing in scientific writing — the context I'm using Monaco Editor with). I wonder of the outcome when your IDE only displays invisible chars.

**Comment by hediet** [comment]
This has been fixed, this is why I couldn't reproduce.
Please try the nightly monaco-editor/vscode insiders release.

**Comment by thom4parisot** [comment]
Yeah, great thank you 🙂
