### ISSUE TITLE
Feature: allow to have different settings by filename

### ISSUE THREAD

**Issue by ilyub** [microsoft/vscode#172966]
```[tasklist]
### Tasks
- [ ] Allow to have different settings by filename
```

Use case:
I am using a plugin that sorts .json files.
It has "orderOverrideKeys" setting that allows to place certain keys at the top.
For example, you may want to place "name", "description", "keywords" above all other keys.
I am using this plugin to sort files like manifest.json (for mobile apps), composer.json (for PHP projects), and other.
Obviously, it would be much cleaner to have separate "orderOverrideKeys" list for manifest.json, composer.json, and some other json configuration files that have standard name.

**Comment by rzhao271** [comment]
Hi, I can understand wanting different setting values for some specific files, but I think that'd be better implemented as an object setting in the extension you are referring to. For example, the keys of that object setting could be the filenames, and the values could be the ordering of keys to use for a file with that filename.

**Comment by ilyub** [comment]
Actually I mentioned one use case, but I think the feature I suggest can be useful for configuring many extensions and extension owner may not always want to change it. So I would suggest at least to keep this thread open to see if other use cases follow.

**Comment by rzhao271** [comment]
It turns out there are other use cases :eyes:
Duplicate of https://github.com/microsoft/vscode/issues/35350
