### ISSUE TITLE
Git - Can't cancel (husky) pre-commit hook from running in background

### ISSUE THREAD

**Issue by savitris** [microsoft/vscode#172909]
In a project I am working on we have a Husky pre-commit hook but it had a problem because of a missing (NPM) module. The pre-commit hook has been going ever since. It has been running for the past 90 minutes even though we have

- done the commit in the commandline (with noverify)
- tried "developer reload window" from the command pallette
- force quit vscode
- killed the git and vscode processes in activity monitor
- restarted the computer

I am at my wits end as to why this keeps going! 

See a previous poster mention this issue in 2019. @joaomoreno mentioned the `reload window` option but that doesn't fix it. https://github.com/Microsoft/vscode/issues/66821 

```
Version: 1.74.3 (Universal)
Commit: 97dec172d3256f8ca4bfb2143f3f76b503ca0534
Date: 2023-01-09T17:07:18.579Z (3 wks ago)
Electron: 19.1.8
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Darwin arm64 22.2.0
Sandboxed: No
```

Thank you for looking into this.

**Comment by savitris** [comment]
I'm available for further questions :)

**Comment by lszomoru** [comment]
@savitris, sorry for not getting back to you on this. I was wondering if you are still running into this issue. 
If so, would you be able to provide a set of steps that I can try to reproduce and investigate the issue?
