### ISSUE TITLE
File Menu opens on secondary monitor, (Linux/Gnome3/Xorg)

### ISSUE THREAD

**Issue by dacobi** [microsoft/vscode#172935]
I just installed VSCode 1.74.3 in Pop OS 22.04 and found that with some dual screen layouts the File Menu will open on the other screen, when VSCode is maximised/in full-screen.

This is a problem when the second screen is a TV that's not on/on the desk.

Changing the screen order/layout in Gnome Settings will fix the problem.

I'm running Xorg and haven't tested in Wayland.

**Comment by aeschli** [comment]
@dacobi Is this the native file menu or is it our custom menu? (Maybe add a screenshot, if you are not sure)

**Comment by dacobi** [comment]
> @dacobi Is this the native file menu or is it our custom menu? (Maybe add a screenshot, if you are not sure)

![filemenu](https://user-images.githubusercontent.com/7037472/216005669-b0979abe-a6a0-45da-a498-56876a9084fe.png)

**Comment by deepak1556** [comment]
Merging to https://github.com/microsoft/vscode/issues/110162
