### ISSUE TITLE
ProblemMatcher freezes VSCode on multiline problem output

### ISSUE THREAD

**Issue by BenWeedon** [Microsoft/vscode#1729]
Attempt to run a python program using a single line problem matcher. For example, use the tasks.json from http://stackoverflow.com/questions/29987840/how-to-execute-python-code-from-within-visual-studio-code, except make it a test command or build command so you can run with a shortcut. Run on an app.py file containing some error, like it only contains the code `1.foo`.

The problem matcher defined in the task.json only works with single line error output, but Python delivers multiline output. I assume this is what is causing VSCode to freeze. It (at least for me) can't be closed except by killing the process.

I'm running the latest VSCode version on Windows 10.

**Comment by dbaeumer** [comment]
Able to reproduce the hang of VSCode. Will investigate

**Comment by dbaeumer** [comment]
This is a problem with the regular expression matcher. Executing the following line in node makes node end in an endless loop:

```javascript
/^(.*)+s$/.exec('    print "iteration {iteration} is {name}".format(iteration=i, name=name)')
```

**Comment by dbaeumer** [comment]
This is a problem in V8. I opened https://bugs.chromium.org/p/v8/issues/detail?id=4651. For now all I can recommend is to tweak the regular expression used. For example /^(.*)s$/ already works and produces the same matches.

**Comment by dbaeumer** [comment]
Duplicates https://bugs.chromium.org/p/v8/issues/detail?id=4651

**Comment by dbaeumer** [comment]
See http://www.regular-expressions.info/catastrophic.html for why the provided regular expression cause exponential runtime behavior.

**Comment by dbaeumer** [comment]
There is nothing we can do about this. Adding verified label
