### ISSUE TITLE
Comments widget obscures horizontal scrollbar in diff editor

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode#172944]
1. Open a PR with comments
2. Scroll to a comment such that a comment widget renders close to the top of the terminal panel
3. :bug: can't grab the horizontal scrollbar
https://user-images.githubusercontent.com/30305945/215854561-b88688c5-d6b0-4fa6-a11a-15ed18c794fc.mp4

This is particularly annoying if you have multiple comments that are relatively close to each other vertically, such that the horizontal scrollbar is obscured most of the time in the diff editor

**Comment by alexr00** [comment]
This occurs in a non-diff editor too and in other peek views (like the problem peek view).
