### ISSUE TITLE
Allow terminal title/description to use ${env:<VARIABLE>} 

### ISSUE THREAD

**Issue by karankd89** [microsoft/vscode#172998]
Either I would like to add certain directory name out of the workspace path or name of the workspace dir in multiroot workspace settings file, to tell me which terminal (tree) I am working on. 

From the example in https://code.visualstudio.com/docs/editor/multi-root-workspaces
{
  "folders": [
    {
      // Source code
      "name": "Product",
      "path": "vscode"
    },
    {
      // Docs and release notes
      "name": "Documentation",
      "path": "vscode-docs"
    },
    {
      // Yeoman extension generator
      "name": "Extension generator",
      "path": "vscode-generator-code"
    }
  ]
}

I need to extract "name" or a certain dir (dir_A) for example if "path" is like "/home/user/dir_A/dir_B/dir_C"

So for now I could extract that dir_A via linux commands and gets set as env variable by default .cshrc script.

**Comment by meganrogge** [comment]
We don't want to/cannot do this because the environment is not available to us when the terminal launches

**Comment by karankd89** [comment]
Then is it possible to use workspace golder name? As I need to know just by looking at terminal tabs which dir I am in
