### ISSUE TITLE
Suggestion: Expandable objects in the debug console

### ISSUE THREAD

**Issue by Glober777** [Microsoft/vscode#17296]
While going through release notes for VS Code 1.8 I came across [this enhancement](https://github.com/Microsoft/vscode/issues/15796) and thought that it would be really handy if the same would work for objects sent by PowerShell script to the standard output (pipeline) and possibly even for Verbose and Debug channels. What do you think?

**Comment by kieferrm** [comment]
@Glober777 please describe in more detail what you are looking for so that we don't have to guess too much. Thanks!

**Comment by Glober777** [comment]
Sorry, I've only just realized that I opened the issue for the wrong project. Was going to open it for vscode-powershell. Will reopen it there.
