### ISSUE TITLE
Going full screen crashes display driver

### ISSUE THREAD

**Issue by ytimenkov** [Microsoft/vscode#17293]
- VSCode Version: Code 1.8.0 (38746938a4ab94f2f57d9e1309c51fd6fb37553d, 2016-12-13T17:45:32.595Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

|Extension|Author|Version|
|---|---|---|
|bower|donjayamanne|0.0.3|
|python|donjayamanne|0.5.5|
|gitlens|eamodio|1.3.1|
|cpptools|ms-vscode|0.9.3|
|csharp|ms-vscode|1.5.3|
|PowerShell|ms-vscode|0.7.2|
|azurerm-vscode-tools|msazurermtools|0.3.2|
|vscode-icons|robertohuertasm|4.1.0|
|cmake|twxs|0.0.15|

---

Steps to Reproduce:
1. I have Lenovo P50 workstation laptop with docking station (with NVidia Quadro M2000M and Intel 530 graphics adapters)
2. When I enable Zen mode with VS code on external display connected to the docking station display just goes dark with only cursor visible.
3. When I moved VS code window to built-in display and tried to enable Zen mode all displays began flicker and then I've got system notification that display driver crashed, displays went blank).

**Comment by isidorn** [comment]
Can you also reproduce this if you simply enter full screen mode? View menu > Toggle Full Screen?
Do you reproduce this every time you enter zen mode?
Can you still reproduce if you add a setting to your setting file `"window.fullScreenZenMode": false`

**Comment by BagelTheKid** [comment]
I'm experiencing a similar issue. I'm using a Dell 7510. I dock my laptop for my work day, I have two connected to my docking station.

Steps to Reproduce:

  1. Dock laptop
  2. Enable Zen mode, the monitor that VS Code is in goes straight black.
  3. Exiting Zen mode stops the monitor from going straight black.

I have tried to reproduce this with setting `"window.fullScreenZenMode": false`, and I couldn't reproduce the issue. I can reproduce the issue by enabling fullscreen mode via F11. So, it seems like the issue is tied to going fullscreen.

**Comment by ytimenkov** [comment]
> Can you also reproduce this if you simply enter full screen mode? View menu > Toggle Full Screen?

Yes, just going to full screen is the problem.

> Do you reproduce this every time you enter zen mode?

Yes, switching to full screen is 100% reproducible with my setup.

> Can you still reproduce if you add a setting to your setting file "window.fullScreenZenMode": false

No, Zen mode itself works fine.

**Comment by isidorn** [comment]
So this seems to be an electron issue when going to full screen mode
You should be able to also reproduce it with a bare bone [electron app](https://github.com/electron/electron#quick-start) - if yes then you should file this bug to the electron git hub page here https://github.com/electron/electron

Assigning to @bpasero as he might have more ideas

**Comment by ytimenkov** [comment]
Yes, I can confirm that this is an electron issue: same problem with bare bone electron app.
