### ISSUE TITLE
Auto updater is not updating previous version 

### ISSUE THREAD

**Issue by jimtryon** [Microsoft/vscode#17291]
- VSCode Version: Code 1.8.0 (38746938a4ab94f2f57d9e1309c51fd6fb37553d, 2016-12-13T17:38:28.425Z)
- OS Version: Darwin x64 16.3.0
- Extensions:

|Extension|Author|Version|
|---|---|---|
|project-manager|alefragnani|0.12.2|
|vscode-icons|robertohuertasm|4.1.0|

---

Steps to Reproduce:

1. Code > Check For Updates
2. Launch Visual Studio Code from dock

**Comment by philburger** [comment]
Experienced a similar issue today with the most recent auto update that went so far as to corrupt the VSC install to the point of requiring a reinstall. Womp womp.

**Comment by kieferrm** [comment]
@jimtryon you created the issue from within 1.8. On what version did you perform step 1? That was the result of step 2?

**Comment by roblourens** [comment]
I might be seeing the same thing... when I click "Restart to update", Code quits and doesn't start install the update or start up again. Someone tell me how to debug it.

**Comment by jimtryon** [comment]
@kieferrm I was performing step 1 updating from 1.7 to 1.8. The result of step 2 did not update the app when I launched it again and the version was showing 1.7 and downloading the update again... my temporary solution was to download 1.8 from the website since I wasn't able to get the auto update to work.

**Comment by joaomoreno** [comment]
@roblourens There is always something in OSX's Console.app. Also, if you launch Code by doing

```
/Applications/Visual\ Studio\ Code.app/Contents/MacOS/Electron
```

you will definitely see something spill out to the console when it happens.

Let me know what you find.

**Comment by roblourens** [comment]
The whole output is

```
robmac:Application Support roblou$ /Applications/Visual\ Studio\ Code.app/Contents/MacOS/Electron
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
2016-12-16 08:39:15.458 Electron[49288:1049057] Download completed to: file:///Users/roblou/Library/Caches/com.microsoft.VSCode.ShipIt/update.6783NLe/VSCode-darwin-stable.zip
```

When I go to that directory, the .zip is unzipped and the 1.8 .app is there. In the folder above, there is a `ShipIt_stderr.log` file but it hasn't been updated since Nov 2.

**Comment by caibirdme** [comment]
met with the same problem.
* click check-for-update
* after downloading finished, click the restart
* vscode closed and nothing happened
* reopen the vscode by my own and the version is still 1.7.x

-----
I have no choice but to download a new version from ur website.but things even get worse.
when I click the check-for-update in 1.8, it reported an error: `could not create temporary directory: access denied`

**Comment by joaomoreno** [comment]
This seems to be a Squirrel update issue.

@caibirdme Can you find a `ShipIt_stderr.log` file?

**Comment by caibirdme** [comment]
@joaomoreno it maybe because of my moving `vscode` to `~/Application` folder.then I moved it from `~/Application` to `~/Downloads`, everything will be ok

**Comment by joaomoreno** [comment]
@jimtryon Does this work for you too?

**Comment by joaomoreno** [comment]
Definitely #7426
