### ISSUE TITLE
`ExtHostDocumentSaveParticipant` unit test failure

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode#172926]
From https://github.com/microsoft/vscode/commit/a8b389f38bd538f70357ba1a0b1f9878ece555d6

https://dev.azure.com/monacotools/Monaco/_build/results?buildId=201611&view=logs&j=55ac390b-ffb1-50ea-3650-525dd9a3fd80&t=3a692518-c3cf-5f6a-c273-72f71dc185fb&l=10146

```
1) ExtHostDocumentSaveParticipant
       event delivery, overall timeout:

      
      + expected - actual

       [
         1
         2
      -  3
       ]
      
  AssertionError [ERR_ASSERTION]: Expected values to be strictly deep-equal:
  + actual - expected
  
    [
      1,
      2,
  +   3
    ]
      at Context.<anonymous> (file:///Users/runner/work/1/s/out-build/vs/workbench/api/test/browser/extHostDocumentSaveParticipant.test.js:125:20)

```

**Comment by jrieken** [comment]
Obsolete - we added this to investigate an issue which turns out to be caused by an extension. No need for this logging after all
