### ISSUE TITLE
`createFileSystemWatcher` is not working correctly with a pattern of `FOLDER_NAME\**` or `FOLDER_NAME\**\*`

### ISSUE THREAD

**Issue by julieg18** [microsoft/vscode#172939]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.75.0-insider (user setup)
- OS Version: Windows_NT x64 10.0.22621

Steps to Reproduce:

1. Create a simple vscode extension and make a watcher with `workspace.createFileSystemWatcher`, using a RelativePattern with a pattern of `FOLDER_NAME\**`
2. Run the extension
3. Edit files inside of FOLDER_NAME
4. The listener should fire for every file altered inside of the FOLDER_NAME, but it will only fire for files directly in the root folder (`FOLDER_NAME\text.txt` will cause the listener to fire but not `FOLDER_NAME\texts\text.txt`). 

Code that demonstrates the issue:

```
	if (workspace.workspaceFolders && workspace.workspaceFolders[0]) {
		const relPattern = new RelativePattern(workspace.workspaceFolders[0], 'src\\**');
		if (relPattern) {
			console.log('relPattern', relPattern);
			const fileSystemWatcher = workspace.createFileSystemWatcher(relPattern);
			fileSystemWatcher.onDidChange((uri) => {
				console.log(uri.fsPath);
			});
		}
	}
```
If I ran the above code, then altered `src\python.py`, `src\scripts\python.py`, and `src\scripts\tests\python.py`, the debug console would show:
```
relPattern ei {e: f, c: 'c:\Users\MY_USERNAME\workspace\example-get-started', pattern: 'src\**'}
c:\Users\MY_USERNAME\workspace\example-get-started\src\python.py
```
The code does work correctly on my Mac, but not my windows computer. I'm also able to replicate the issue on VSCode `1.74.3`.

**Comment by bpasero** [comment]
The docs make it clear that `\` is not a valid segment in a glob pattern:

https://github.com/microsoft/vscode/blob/e0afad1f19ee81c76cf24af38d0ec7458b193f47/src/vscode-dts/vscode.d.ts#L2121-L2138

**Comment by julieg18** [comment]
> The docs make it clear that \ is not a valid segment in a glob pattern:

Apologies, I misunderstood the documentation due to a minor typo in code.visual.com:

<img width="774" alt="image" src="https://user-images.githubusercontent.com/43496356/215860974-a9cd23b0-03d8-4f83-ac06-aa40275bcf7a.png">

I'll be sure to read docs stored in github instead of the site and read things more thoroughly next time. Thanks for much for the help!

**Comment by bpasero** [comment]
@gregvanl fyi on the vscode-docs issue above, can we address that?
