### ISSUE TITLE
When I set "diffEditor.renderSideBySide": false in setting.json, the red part of the Diff cannot be copied.

### ISSUE THREAD

**Issue by kotu-kotuo** [microsoft/vscode#172996]
- VS Code Version: 1.74.3
- OS Version: 13.0.1（22A400）

Steps to Reproduce:

1. Setting "diffEditor.renderSideBySide": false in setting.json

![段落テキスト](https://user-images.githubusercontent.com/52486487/215955192-759350d5-ec1d-4079-9f80-9e364f606413.png)

thank you

**Comment by lszomoru** [comment]
@kotu-kotuo, if you right click on the deleted content you will have options in the context menu to copy the deleted lines.
Reassigning to @hediet in case you have any further questions or concerns.

**Comment by kotu-kotuo** [comment]
Oh, I didn't know that, thanks for letting me know.
I had thought that I could select a range by drag-and-drop, but I see that the specification is to copy by right-clicking.
I love VSCode 👍
