### ISSUE TITLE
Unable to open terminal with linux arm and arm64 servers on qemu

### ISSUE THREAD

**Issue by deepak1556** [microsoft/vscode#172992]
Sanity testing `1.75` on linux servers following the steps at https://github.com/microsoft/vscode-remote-release/wiki/Sanity-Check-VS-Code-Servers#linux-platforms and attempting to open a terminal throws the following error.

<img width="571" alt="Screenshot 2023-02-01 at 11 47 03" src="https://user-images.githubusercontent.com/964386/215932968-f0af2873-cd6e-470f-b786-2beb16966c0d.png">

Issue is from the pty module, following snippet can trigger the error on any of the containers

```
> var ptyProcess = pty.spawn('bash', [], {cwd: process.env.HOME});
Unsupported ioctl: cmd=0x5441
Uncaught Error: chdir() failed: Not a directory
    at new UnixTerminal (/root/.vscode-server/bin/e8bf7514f31cef005c988b206c61948e56aab9cb/node_modules/node-pty/lib/unixTerminal.js:106:24)
    at Object.spawn (/root/.vscode-server/bin/e8bf7514f31cef005c988b206c61948e56aab9cb/node_modules/node-pty/lib/index.js:29:12)
```

**Comment by deepak1556** [comment]
The bug seems to be localized to qemu environment, if I open arm64 container from arm64 host the terminal launches fine inside the container.

**Comment by bpasero** [comment]
Talked in standup to not take as candidate.

**Comment by deepak1556** [comment]
I will try to sum-up my findings here:

- The issue only affects when running on top of qemu
- The way https://github.com/hypriot/qemu-register works is that it ships docker image with qemu [built](https://github.com/hypriot/qemu-register/blob/d27018091bee985f9edf4db0599a9564bc1a631d/Dockerfile#L26-L32) for certain architectures and during run it installs the qemu binaries as [interpreters](https://github.com/hypriot/qemu-register/blob/d27018091bee985f9edf4db0599a9564bc1a631d/register.sh#L30-L35) for the relevant architectures via the `binfmt_misc` kernel feature https://docs.kernel.org/admin-guide/binfmt-misc.html 
- The default behavior of `binfmt_misc` is to override the `argv[0]` with the full path to the binary that is being executed. For our case, the spawn-helper gets the following `argv[]` under qemu
```
["absolute-path-to-helper-binary", "uid_value", "gid_value"] -> see how `cwd` value at 0 is replaced
```
- This affects our expected positional [argument](https://github.com/microsoft/node-pty/blob/55282709d627107dec1f2668a94ce732c46feb80/src/unix/spawn-helper.cc#L39)
- Couple of solutions, 
(i) When launching the helper executable, always set an environment variable [QEMU_ARGV0](https://github.com/microsoft/node-pty/blob/55282709d627107dec1f2668a94ce732c46feb80/src/unix/pty.cc#L290) set to the `argv[0]` value [we expect](https://github.com/microsoft/node-pty/blob/55282709d627107dec1f2668a94ce732c46feb80/src/unix/pty.cc#L188) in the child process. This would force qemu to use this as [argv[0]](https://github.com/qemu/qemu/blob/13356edb87506c148b163b8c7eb0695647d00c2a/linux-user/main.c#L848-L854) in the child process.
(ii) Alternatively, [we align the argument array](https://github.com/microsoft/node-pty/blob/55282709d627107dec1f2668a94ce732c46feb80/src/unix/pty.cc#L187-L193) to have the first position as path to the program that is being executed since that is what is expected in the unix platforms. So we would basically launch the helper executable with the following arguments

```
["absolute-path-to-helper-binary", "cwd", "uid_value",....] -> see how we are explicitly passing the first argument as the program name
```

I am inclined to solution (ii) as it aligns with unix expectations and also avoids using any environment particular to a platform.

**Comment by rzhao271** [comment]
Opening the terminal works when sanity testing Linux server with the current instructions, though I noticed instead of getting qemu, it seems to get `tonistiigi/binfmt`

**Comment by deepak1556** [comment]
Yeah the server instructions were changed to use `tonistiigi/binfmt` that comes with newer qemu version that also addresses this issue. You can test with `hypriot/qemu` to see if the flow still works.

> The terminal name says qemu-aarch64 on the arm64v8/ubuntu container, though.

This hasn't changed.
