### ISSUE TITLE
Difference in debug console output when running and debugging launch configuration

### ISSUE THREAD

**Issue by ChrisBuchholz** [Microsoft/vscode#17299]
- VSCode Version: Version 1.9.0-insider
- OS Version: macOS 10.12.11

Steps to Reproduce:

1: Have the following launch configuration set up which start a flask server:

```json
        {
            "name": "Server",
            "type": "python",
            "request": "launch",
            "stopOnEntry": false,
            "pythonPath": "${config.python.pythonPath}",
            "program": "${workspaceRoot}/flask/run.py",
            "cwd": "${workspaceRoot}",
            "internalConsoleOptions": "openOnSessionStart",
            "debugOptions": [
                "WaitOnAbnormalExit",
                "WaitOnNormalExit",
                "RedirectOutput"
            ]
        }
```

1.  Run the launch configuration with command `workbench.action.debug.run`.
2. See all the output in the debug console that you would see in a normal shell.
3. Start a debugging session with command `workbench.action.debug.start`.
4. Only seeing some (every other) line that is otherwise visible when *running* the configuration just before as it starts up, and things logged to stdout as the python script is running, and is outputtet when *running* the configuration or in a shell, is also not outputtet in debug mode as the script continues running at all.

How come the output in debug mode is not the same as in run mode?

**Comment by isidorn** [comment]
The content of the output is coming from the python debug extension, can you please file this issue here https://github.com/DonJayamanne/pythonVSCode

Sorry for the slow reponse, this issue somehow fall through the cracks
