### ISSUE TITLE
Javascript debugger not working

### ISSUE THREAD

**Issue by AlCalzone** [microsoft/vscode#172906]
Does this issue occur when all extensions are disabled?: Yes, but this needs the JS debugger

- VS Code Version: 1.74.3
- OS Version: Ubuntu 22.04.1 LTS

Steps to Reproduce:

```js
// file: test.js
debugger;
console.log("after debugger"); // put breakpoint here
```

1. execute `node test.js` in Javascript debug console
2. notice that "after debugger" is logged, debugger does not attach

alternatively add this launch config:
```
		{
			"name": "Test Program",
			"program": "${workspaceFolder}/test.js",
			"request": "launch",
			"skipFiles": ["<node_internals>/**"],
			"type": "node"
		},
```

1. run it
2. debugger does not launch, program exits at the end

**Comment by AlCalzone** [comment]
I'm starting to think this may be system or configuration related. I went all the way back to 1.66.2 (and I've definitely debugged this way last summer), yet the debugger does not attach.

**Comment by AlCalzone** [comment]
Even with auto-attach set to "always", nothing happens here:
![grafik](https://user-images.githubusercontent.com/17641229/215771084-eb3f1842-e8c3-42b6-854b-739abab658a3.png)

**Comment by AlCalzone** [comment]
Tested on a different machine with Windows 10 instead of Ubuntu, here it works.

**Comment by connor4312** [comment]
What is the result of `echo $NODE_OPTIONS` in the JavaScript Debug Terminal?

**Comment by AlCalzone** [comment]
**Devcontainer (working)**:
```
--require /vscode/vscode-server/bin/linux-x64/97dec172d3256f8ca4bfb2143f3f76b503ca0534/extensions/ms-vscode.js-debug/src/bootloader.bundle.js --inspect-publish-uid=http
```

**Ubuntu (not working)**:
```
--require /home/dominic/.config/Code/User/workspaceStorage/1105c7239453d4769738c85e86d192fa/ms-vscode.js-debug/bootloader.js
```

**Comment by connor4312** [comment]
What version of Node.js are you using in the "not working" sample?

**Comment by AlCalzone** [comment]
16.19.0

The devcontainer is on 18.13.0 and the Windows machine on 12.x or 14.x

**Comment by connor4312** [comment]
Do you have any capabilities set on your Node binary? You may be hitting https://github.com/nodejs/node/issues/37588

**Comment by AlCalzone** [comment]
```
sudo getcap $(which node)
/usr/bin/node cap_net_bind_service,cap_net_admin,cap_net_raw=eip
```
that might be it

**Comment by AlCalzone** [comment]
That was it! Thanks for the pointers, removing the capabilities fixed it.
