### ISSUE TITLE
extension startup time is very different between activationEvent onCommand and onStartupFinished

### ISSUE THREAD

**Issue by tjx666** [microsoft/vscode#172933]
I use activationEvent `onStartupFinished`, my extension startup time: 800+ms

<img width="373" alt="image" src="https://user-images.githubusercontent.com/41773861/215830287-4753e1bc-734f-4eac-bbd2-9c78ecf27549.png">

After I change the activationEvent to `onCommand:clipboardMaster.smartCopy`, and call this command

<img width="378" alt="image" src="https://user-images.githubusercontent.com/41773861/215830554-bbd7076a-9d4d-46a0-96a7-08bb2a031d4a.png">

Reproduce:

1. install extension `YuTengjing.clipboard-master`, you can see startup time cost several hundreds.
2. `git clone git@github.com:tjx666/vscode-clipboard-master.git`
3. `pnpm install`
4. change activeEvent to `onCommand:clipboardMaster.smartCopy`
5. debug extension anc call command `Clipboard Master: Smart Copy`
6. you will see the startup time only costs several dozens

**Comment by DonJayamanne** [comment]
@tjx666 thanks for filing this issue.
I believe this is expected as the event `onStartupFinished` (based on the docs) files early on and there could be other extensions that are getting activated at the same time, i.e. the node runtime might be busy with other extensions or the like.
Hence it seems that the clipboard master is slightly slower.

However when you change the activation to the command, then what could be happening is that most of vscode and other extensions have loaded, and you are using the command much later in the time line to activate your extension. At this point the node runtime might not be as busy, hence activation of the code is faster.

I would not recommend using `onStartupFinished` unless you want the extension to always be active.

**Comment by DonJayamanne** [comment]
@joyceerhl /cc

**Comment by tjx666** [comment]
@DonJayamanne Is vscode support activate extension when specific setting value is true?

**Comment by tjx666** [comment]
@DonJayamanne Maybe It's time to set your extension: https://github.com/DonJayamanne/gitHistoryVSCode activationEvent to `onStartupFinished`
