### ISSUE TITLE
JSON parsing doesn't like URLs, affects formatting

### ISSUE THREAD

**Issue by pcolmer** [Microsoft/vscode#17295]
- VSCode Version: 1.8.0
- OS Version: Windows 10 1607 (14393.576)

Steps to Reproduce:

1.  Load a JSON file that has a URL in single quotes. The file starts off in red but then turns green at the // in the URL.

![image](https://cloud.githubusercontent.com/assets/1979931/21223068/3c040f66-c2bd-11e6-9eb1-63b0d7de3fe0.png)

2.  If you go right-click, Format Document, the JSON formatting only gets as far as the end of the red text. Also, a space gets introduced between https: and the rest of the URL.

![image](https://cloud.githubusercontent.com/assets/1979931/21223090/4a59fb84-c2bd-11e6-93e3-a19d1c38a549.png)

Manually changing the // to a single / results in a completely red file and formatting then words, but there seems to be something wrong with the parsing.

**Comment by ChristianRuigrok** [comment]
In JSON only double quotes are valid. (View the standard on http://json.org/)

**Comment by pcolmer** [comment]
Thanks. My apologies for the noise - I had a bug in my code that was emitting the data in the wrong format.
