### ISSUE TITLE
Run `code --install-extension id@version` fail on Github Codespace (Web)

### ISSUE THREAD

**Issue by zanminkian** [microsoft/vscode#172917]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.74.3
- OS Version: linux

Steps to Reproduce:

1. Open a codespace on github in Web (browser), and uninstall golang.go extension if it installed.
2. Run `code --install-extension golang.go@0.37.0` in terminal. It will be fail. (What I expect is success.)
3. Run `code --install-extension golang.go` in terminal. It will be success.

**Comment by zanminkian** [comment]
<img width="762" alt="image" src="https://user-images.githubusercontent.com/35495628/215782391-76ea4705-e4e8-4b26-8fbe-eaf4522c6999.png">

**Comment by sandy081** [comment]
It works for me - I mean I can install the extension in codespace `code --install-extension golang.go@0.37.0`. Can you please provide a sample codespace where I can repro this?

**Comment by zanminkian** [comment]
@sandy081 Thanks for your reply! I going to provide 2 ways to reproduce this bug.

## First way
1. Open `https://github.com/antfu/eslint-config` in browser.
2. Click `Create codespace on main`.
3. Run `code --install-extension golang.go@0.37.0`. It will be fail.
<img width="1447" alt="image" src="https://user-images.githubusercontent.com/35495628/220843980-ff3e7880-ef27-4785-86aa-c8fdcae31714.png">
<img width="665" alt="image" src="https://user-images.githubusercontent.com/35495628/220844224-d8c492dd-858e-4bec-946c-f199c764885a.png">

## Second way
We can reproduce by running this [command](https://github.com/gitpod-io/openvscode-server#docker), because this repo is fork from vscode. 
1. Run `docker run -it --init -p 3000:3000 -v "$(pwd):/home/workspace:cached" gitpod/openvscode-server` in the terminal of your computer.
2. Open `http://localhost:3000` in your browser.
3. Run `code --install-extension golang.go@0.37.0`. It will be fail.
<img width="697" alt="image" src="https://user-images.githubusercontent.com/35495628/220844947-801bcb7b-d1f8-4fa3-98e5-000a2589305f.png">

**Comment by zanminkian** [comment]
@sandy081 If `@version` begins with `0`, such as `code --install-extension donjayamanne.githistory@0.6.19`, it will be fail. If `@version` not begins with `0`, such as `code --install-extension esbenp.prettier-vscode@9.9.0`, it will be success.
<img width="686" alt="image" src="https://user-images.githubusercontent.com/35495628/220849792-b31512c9-1c35-4a92-adfc-082098affea3.png">

**Comment by sandy081** [comment]
This seems to happen when you open codespace in web
