### ISSUE TITLE
OSX El Capitan: Code crashes on quit when in split full-screen mode

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#173]
1. Go full screen
2. Split it with another app (eg iTerm2), El Capitan style
3. Quit Code

Crash reporter comes up. Couldn't repro with barebones Electron.

**Comment by joaomoreno** [comment]
[crash.txt](https://github.com/Microsoft/vscode/files/38766/crash.txt)

**Comment by bpasero** [comment]
@joaomoreno repros with Atom 1.2.0?

**Comment by joaomoreno** [comment]
No. 🌧

**Comment by bpasero** [comment]
Likely https://github.com/atom/atom/issues/9584 which is fixed in 0.34.5 which I plan to consume next week.

**Comment by bpasero** [comment]
I think this is fixed with latest Electron we use.
