### ISSUE TITLE
focus jumps close tag on another line

### ISSUE THREAD

**Issue by gcamana** [Microsoft/vscode#17308]
- VSCode Version: Code 1.8.0 (38746938a4ab94f2f57d9e1309c51fd6fb37553d, 2016-12-13T17:38:28.425Z)
- OS Version: Darwin x64 15.2.0
- Extensions:

|Extension|Author|Version|
|---|---|---|
|stylus|Alan|0.0.4|
|output-colorizer|IBM|0.0.8|
|stylus|buzinas|0.1.0|
|jquerysnippets|donjayamanne|0.0.1|
|python|donjayamanne|0.4.2|
|color-highlight|naumovs|1.2.1|
|trailing-spaces|shardulm94|0.2.11|
|language-stylus|sysoev|1.6.0|
|twig|whatwedo|1.0.1|

---

Steps to Reproduce:

1.When I type any html tag, and followed the class, the focus jumps to the next causing it to be separated from the closing tag in another line
2.
Happens in html

**Comment by kieferrm** [comment]
@gcamana can you pls provide an animated gif of what you are doing or explain it in more detail. Thanks!

**Comment by egamma** [comment]
Closing the issue for now.

@gcamana pls reopen the issue when you can provide an animated gif to illustrate the problem.
