### ISSUE TITLE
Add API or command to open a DAP source in-editor

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#173057]
Inspired by https://github.com/microsoft/vscode-js-debug/issues/1539#issuecomment-1412451690

It'd be nice if I could pass a debug session + DAP `Source` to have that source opened in editor. Then I could do what I need to do for pretty printing. Debug source documents do have URIs, but these are fairly inscrutable and not "API" I want to directly depend upon by generating them in js-debug.

**Comment by rzhao271** [comment]
Hi Connor, what are some verification steps for this issue?

**Comment by connor4312** [comment]
closed this because I no longer needed it, doesn't require verification
