### ISSUE TITLE
Breakpoint and test gutter icon colors get mixed up

### ISSUE THREAD

**Issue by TylerLeonhardt** [microsoft/vscode#173063]
Don't think this a new bug but finally tracked it down.

Steps to Reproduce:

* place a breakpoint right before a test (in a line that's empty):
<img width="182" alt="image" src="https://user-images.githubusercontent.com/2644648/216144407-797b81ef-0ffc-4781-bd4a-179c742dfff4.png">
* debug the test. it becomes:
<img width="189" alt="image" src="https://user-images.githubusercontent.com/2644648/216144635-bef96f8e-c271-41c3-9075-eb48a5e0495a.png">
and then
<img width="171" alt="image" src="https://user-images.githubusercontent.com/2644648/216144183-4a7356d7-9878-42c4-9c06-b3cb671af5e1.png">

Then I hit step over and saw this:
<img width="269" alt="image" src="https://user-images.githubusercontent.com/2644648/216144220-f8979978-4c78-4f7b-954a-004ca5dcabaa.png">
(the arrow should be green)

**Comment by connor4312** [comment]
Duplicates https://github.com/microsoft/vscode/issues/114776
