### ISSUE TITLE
SWC errors are not emitted well

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#173074]
In this build output, there's some error in SWC, but it's not emitted https://dev.azure.com/vscode/VSCode/_build/results?buildId=84924&view=logs&j=a8a6689c-5a84-59c0-482a-7dd9f21eb2d8&t=f7eec8ea-1df6-5330-14df-c74a97d41c4e

I'm _guessing_ it's because I use the `satisfies` operation and they don't support that yet, or our version of TS doesn't.

**Comment by jrieken** [comment]
Please don't use `satisfies` for the time being

**Comment by jrieken** [comment]
Please don't use `satisfies` for the time being
