### ISSUE TITLE
Test Explorer: 0/0 tests passed after running all tests

### ISSUE THREAD

**Issue by hediet** [microsoft/vscode#173014]
When I run all tests, the label resets back to `0/0 tests passed` after all tests were run.
This is very confusing.

![gif](https://user-images.githubusercontent.com/2931520/216012399-8442d991-ae04-4760-bd22-67d13a70b3a8.gif)

**Comment by connor4312** [comment]
This was a result of a bad filter function that caused all test runs to be treated extension-triggered. The "real" test run would then never have results, or get any output. More importantly, this results in "show test output" usually showing nothing. Taking this as a candidate.
