### ISSUE TITLE
更新版本之后，代码智能提示总是会出问题

### ISSUE THREAD

**Issue by ruancheng77** [Microsoft/vscode#17307]
- VSCode Version: Code 1.8.0 (38746938a4ab94f2f57d9e1309c51fd6fb37553d, 2016-12-13T17:45:32.595Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions:

|Extension|Author|Version|
|---|---|---|
|html-snippets|abusaidm|0.0.18|
|vscode-javascript-snippet-pack|akamud|0.1.5|
|jquerysnippets|donjayamanne|0.0.1|
|python|donjayamanne|0.5.5|
|vscode-html-css|ecmel|0.0.30|
|vscode-JS-CSS-HTML-formatter|lonefy|0.2.2|
|MagicPython|magicstack|0.6.1|
|prettify-json|mohsen1|0.0.3|
|language-vscode-javascript-angular2|nwallace|0.0.11|
|python|tht13|0.2.3|
|python-extended-snippets|tushortz|0.0.1|

---

Steps to Reproduce:

1.
2.

**Comment by mjbvz** [comment]
Title Translation: 

>After you update the version of code IntelliSense will always go wrong

Can you please provide a list of steps to reproduce this, the expected behavior, and the actual behavior. Thanks.

**Comment by mjbvz** [comment]
Closing as more info is needed to investigate. 

@ruancheng77 Please provide: a list of steps to reproduce this, the expected behavior, and the actual behavior.

Thanks
