### ISSUE TITLE
Test Explorer: Jumping icon on hover when item is empty

### ISSUE THREAD

**Issue by hediet** [microsoft/vscode#173010]
Notice how the icon jumps when the mouse is on top of it:

![Code_-_Insiders_YAF3vJlGSR](https://user-images.githubusercontent.com/2931520/216005663-653c705f-3e54-467e-be9c-85fc60f14eed.gif)

**Comment by andreamah** [comment]
Could someone provide a test snippet to simulate the empty test list item?

**Comment by connor4312** [comment]
top level doesn't matter, thanks!
