### ISSUE TITLE
Provide a diagnostic warning for * activation

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#173084]
We want to discourage extension authors from using `*` activation. We should consider adding a diagnostic warning similar to the one we have for implicit events.

**Comment by usernamehw** [comment]
Is it not enough that `vsce` provides the same prompt in terminal when packaging/publishing an extension?

**Comment by TylerLeonhardt** [comment]
@usernamehw at that stage in the development lifecycle, authors are more likely to just ignore the warning from vsce. Additionally, they might be publishing in CI and might not see it there either.

**Comment by TylerLeonhardt** [comment]
verification:
* in an extension, put `"*"` in activation events
* see this:
![image](https://user-images.githubusercontent.com/2644648/219729733-ffd82da2-5369-445f-aac0-0a3fc4db3e6e.png)
