### ISSUE TITLE
Opening a from quick pick keeps spinning

### ISSUE THREAD

**Issue by digitarald** [microsoft/vscode#173097]
Only sees one file but I can not open my ipynb file:

![image](https://user-images.githubusercontent.com/8599/216223061-efce777b-997f-4641-a9d6-99154a208b70.png)

Version: 1.75.0-insider
Commit: e2816fe719a4026ffa1ee0189dc89bdfdbafb164
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36 Edg/109.0.1518.70
Embedder: codespaces

**Comment by roblourens** [comment]
Everything else working? Could the EH be stuck? Do you see this consistently?

**Comment by digitarald** [comment]
Seems like my wifi was in some weird state when I tried this. After fixing my internet, this worked again as expected.
