### ISSUE TITLE
No API call to determine if Source View or Disassembly View is in effect

### ISSUE THREAD

**Issue by gareth-rees** [microsoft/vscode#173025]
In the VSCode API, there does not seem to be a way of determining which of Source View or Disassembly View is currently in effect for a debug session.

The reason for wanting this is that when debugging, the behaviour of toolbar buttons changes depending on which view is currently in effect. In particular, these buttons have different behaviour in the two views:

| Toolbar button | Behaviour in Source View | Behaviour in Disassembly View |
| ------ | ------ | ------ |
| Step Over | Step program, proceeding through subroutine calls. | Step one instruction, but proceed through subroutine calls. |
| Step Into | Step program until it reaches a different source line. | Step one instruction exactly. |

In the [Time Travel Debug for C/C++](https://marketplace.visualstudio.com/items?itemName=Undo.udb) extension we have reverse equivalents of the Step Over and Step Into buttons, which need to behave like this:

| Toolbar button | Behaviour in Source View | Behaviour in Disassembly View |
| ------ | ------ | ------ |
| Reverse Step Over | Step program backward (not counting subroutine calls). | Step program backward one instruction (not counting subroutine calls). |
| Reverse Step Into | Execute program backward until it reaches a different source line. | Step program backward exactly one instruction. |

It would therefore be helpful if there were a method or property, for example, on the [`DebugSession` class](https://code.visualstudio.com/api/references/vscode-api#DebugSession), that we could use to select the appropriate behaviour.

**Comment by roblourens** [comment]
We have SteppingGranularity to cover this, but it is not adopted in the UI: https://github.com/microsoft/vscode/issues/102236

**Comment by gareth-rees** [comment]
@roblourens You've closed the issue as completed, but I don't see how to get the current stepping granularity via the [VS Code API](https://code.visualstudio.com/api/references/vscode-api). There's no mention of stepping granularity there.

**Comment by roblourens** [comment]
Like I said, it's not implemented in vscode. That's what the linked issue is for. Sorry, the "as completed" thing is just github and not useful
