### ISSUE TITLE
Bug after update for cs50 harvard codespace (stopped working)

### ISSUE THREAD

**Issue by gnswin** [microsoft/vscode#173029]
ADD ISSUE DESCRIPTION HERE
Hello! Since yesterday,  my code space from cs50( Harvard free computer sci course)has stopped working and does not allow cs50 libraries to be used even though I downloaded the cs50 extensions for it, could u please advice or help me in any way possible? Thank you.
Version: 1.74.3
Commit: 97dec172d3256f8ca4bfb2143f3f76b503ca0534
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.5414.75 Safari/537.36
Embedder: codespaces

**Comment by joyceerhl** [comment]
cc @jkeech

**Comment by GideonCheruiyot** [comment]
Hey @gnswin  👋🏿 , thanks for reporting. Could you make a post on [Codespaces Discussions](https://github.com/community/community/discussions/categories/codespaces) with either the browser url for the codespace if on the browser or if using the Codespaces Extension, press F1 -> Details and add the Codespace ID to the discussion post. The team will take a look and help take a look there.

**Comment by GideonCheruiyot** [comment]
Hi @gnswin, thanks for reaching out, for help with this account specific issue, could you open a [support](https://support.github.com/request) ticket and include either your codespace url from the browser, or if using the codespaces desktop extension, the Codespace ID (Press F1 -> Details to see it). A member of the codespaces team should be able to investigate further.
