### ISSUE TITLE
Test Explorer Jumps Too Much When Running VS Code Test Suite

### ISSUE THREAD

**Issue by hediet** [microsoft/vscode#173015]
![gif](https://user-images.githubusercontent.com/2931520/216012896-099a516c-5926-450b-9e8e-83bfd5c32896.gif)

This scrolling doesn't provide any value in this situation and looks broken.

Please add a (higher?) debounce and limit scrolling distance.

**Comment by connor4312** [comment]
This came in with other improvements necessary for snapshot tests
