### ISSUE TITLE
color of pairs of parentheses, brackets, and braces

### ISSUE THREAD

**Issue by Ezecordoba** [microsoft/vscode#173099]
Type: <b>Performance Issue</b>

I can't get different pairs of parentheses, brackets, and braces to have different colors. In addition, the app does not show me where the parentheses, brackets and braces are closed when I put the cursor over it. I already configured everything so that these things could work. But they don't work
VS Code version: Code 1.74.3 (97dec172d3256f8ca4bfb2143f3f76b503ca0534, 2023-01-09T16:59:02.252Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-10110U CPU @ 2.10GHz (4 x 2592)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|7.79GB (2.29GB free)|
|Process Argv|--crash-reporter-id 75b91bfb-6f03-41ec-bde6-939b1544ce00|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	    93	 21876	code main
    0	    27	  3272	   crashpad-handler
    0	   146	  3804	   window (Eze (área de trabajo) - Visual Studio Code)
    0	   110	  9508	   shared-process
    0	    75	 14948	     fileWatcher
    0	    74	 20960	     ptyHost
    0	   107	 12404	   extensionHost
    1	    82	 18176	   issue-reporter
    0	    40	 19384	   utility-network-service
    0	   128	 19584	   gpu-process
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (Eze (área de trabajo) - Visual Studio Code)
|    Folder (Eze): 1404 files
|      File types: pdf(326) jpg(214) xpm(144) png(140) py(111) mp4(52) txt(41)
|                  dat(41) pyc(34) svg(32)
|      Conf files: settings.json(1);
```

</details>
<details><summary>Extensions (22)</summary>

Extension|Author (truncated)|Version
---|---|---
arepl|alm|2.0.4
vscode-django|bat|1.10.0
python-environment-manager|don|1.0.4
python-extension-pack|don|1.7.0
code-runner|for|0.12.0
vsc-python-indent|Kev|1.18.0
vscode-simple-icons|Lau|1.16.0
theme-monokai-pro-vscode|mon|1.2.0
vscode-language-pack-es|MS-|1.74.12140936
isort|ms-|2022.8.0
python|ms-|2022.20.2
jupyter|ms-|2022.11.1003412109
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.14
vscode-jupyter-cell-tags|ms-|0.1.6
vscode-jupyter-slideshow|ms-|0.1.5
autodocstring|njp|0.6.1
python-extended-snippets|tus|0.0.1
intellicode-api-usage-examples|Vis|0.2.7
vscodeintellicode|Vis|1.2.30
jinja|who|0.0.8
material-theme|zhu|3.15.6

(3 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
azure-dev_surveyone:30548225
vsccc:30610678
pyindex848cf:30577861
nodejswelcome1cf:30587006
3biah626:30602489
f6dab269:30613381

```

</details>

**Comment by gjsjohnmurray** [comment]
Please use the Start Extension Bisect command to investigate whether the problem is being caused by one of your extensions.

**Comment by Ezecordoba** [comment]
> Please use the Start Extension Bisect command to investigate whether the problem is being caused by one of your extensions.

I just did it. And found no extension caused the problem.

**Comment by hediet** [comment]
Can you share a screenrecording/screenshot? Thanks!
