### ISSUE TITLE
Notify user of background jobs

### ISSUE THREAD

**Issue by dfroze** [Microsoft/vscode#17300]
- VSCode Version: 1.8.0
- OS Version: Linux

![img](https://cloud.githubusercontent.com/assets/7603482/21224422/cb47af54-c2d4-11e6-8d66-3fb18021b6a2.jpg)
There are 3 things that I want to point out:
  1. For new user and old as well, it will be great if there was a better and easier way to display that vscode is doing something in the background and you should wait a bit. And not only that, there are times when it isn't red and I see vscode with 100% process usage and have no idea what is he trying to do. Being red means that there is a problem.

  2. When i see it red, I click it to get more info.. what i get is select between linux/win/mac ?! I believe that some improvements will be needed for this, cause this is confusing

  3. It is a bit related to the 1-st point. It would be great if there was a shortcut to Developer Tools->Console . My point is that if the user has a problem, it should have a fast way to find out what it is. The information displayed in the console (log) should be for normal users as well and not only vscode developers. I only found out that you can view this log after 2 months and it would have helped a lot if it was somewhere more obvious/intuitive for normal users.

**Comment by kieferrm** [comment]
FYI @egamma

**Comment by bpasero** [comment]
@dfroze is this still an issue for you?
