### ISSUE TITLE
Test Explorer: Inconsistent UI State

### ISSUE THREAD

**Issue by hediet** [microsoft/vscode#173012]
I ran all tests and then reloaded VS Code.
I guess the states of each test are persisted, but it still says `0/0 tests passed`.

I suggest to either persist both states or none, I find the current state confusing.

![image](https://user-images.githubusercontent.com/2931520/216006270-42487f3c-d263-421c-aae0-9697ec77a761.png)

**Comment by connor4312** [comment]
Same as https://github.com/microsoft/vscode/issues/173014
