### ISSUE TITLE
Python3.10 debug  unusual behavior!

### ISSUE THREAD

**Issue by blakeliu** [microsoft/vscode#173003]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:
Version: 1.74.3 (user setup)
Commit: 97dec172d3256f8ca4bfb2143f3f76b503ca0534
Date: 2023-01-09T16:59:02.252Z
Electron: 19.1.8
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.19044
Sandboxed: No
- OS Version: 
Ubuntu 18.04.6 LTS \n \l   or win10
Steps to Reproduce:
1. create python3.10 env
```bash
conda create -n py310 python=3.10
conda activate py310 
```
```shell
(py310) tf@tf:~$ conda list python
# packages in environment at /home/tf/miniconda3/envs/py310:
#
# Name                    Version                   Build  Channel
ipython                   8.8.0                    pypi_0    pypi
python                    3.10.9               h7a1cb2a_0  
```

3.  python code:
```python
for key in ("phase", "seed", "project_dir", "load_checkpoint",):
    a = False
    if a:
        print("True")
```
4.  debug and raise unusual behavior, but terminal print nothing.
![err](https://user-images.githubusercontent.com/9639933/215974212-cae1ab98-a23e-4d50-81af-82b54e7fdf0d.png)

**Comment by blakeliu** [comment]
**python 3.8 , 3.9 and 3.11 show no problem!**
```shell
# Name                    Version                   Build  Channel
python                    3.8.13               h12debd9_0
```

```shell 
# Name                    Version                   Build  Channel
python                    3.9.16               h7a1cb2a_0
```

```shell
# Name                    Version                   Build  Channel
python                    3.11.0               h7a1cb2a_2
```

**Comment by roblourens** [comment]
Please file this on the python extension repo, thanks
