### ISSUE TITLE
PHP Snippets are not being summoned by IntelliSense

### ISSUE THREAD

**Issue by noquierouser** [Microsoft/vscode#17313]
- VSCode Version: Code 1.8.0 (38746938a4ab94f2f57d9e1309c51fd6fb37553d, 2016-12-13T17:38:28.425Z)
- OS Version: Darwin x64 14.5.0
- Extensions:

|Extension|Author|Version|
|---|---|---|
|beautify|HookyQR|0.6.2|
|code-settings-sync|Shan|2.3.8|
|toml|be5invis|0.0.3|
|LogFileHighlighter|emilast|1.0.1|
|php-intellisense|felixfbecker|0.0.12|
|Theme-MaterialKit|ms-vscode|0.1.1|
|stylelint|shinnn|0.20.4|
|pasteandformat|spoeken|0.0.5|
|Align|steve8708|0.2.0|
|Material-theme|zhuangtongfa|1.0.3|

---

Steps to Reproduce:

1. Create a custom PHP Snippet.
2. Create a new PHP file, or edit an existing one.
3. Try to invoke a snippet using its prefix.
4. Press <kbd>⌘</kbd>+<kbd>Space</kbd>.
5. Your custom snippet is not showing in the list.

**Comment by noquierouser** [comment]
Ok, it seems that snippets **do kick in**, but only when the `<?` tag is written. As a consequence, I get a duplicate `<?` because of the snippet. This didn't happen in the previous version.

![capturfiles-15-44-2016_12 44 31](https://cloud.githubusercontent.com/assets/463168/21230651/5d535594-c2c4-11e6-8aa9-f210c382d9fd.png)
![capturfiles-15-44-2016_12 44 54](https://cloud.githubusercontent.com/assets/463168/21230650/5d4f86f8-c2c4-11e6-8822-fe2e43535f48.png)
![capturfiles-15-45-2016_12 45 03](https://cloud.githubusercontent.com/assets/463168/21230649/5d4ed0aa-c2c4-11e6-87b0-c7edfdf86bf2.png)

**Comment by felixfbecker** [comment]
Outside of `<?php` is just HTML...

**Comment by noquierouser** [comment]
@felixfbecker I understand. Is this related to the fact that I'm running your IntelliSense plugin? Because, as I said, this didn't happen in the 1.7.x version.

**Comment by felixfbecker** [comment]
I don't know, why don't you try disable it first

**Comment by noquierouser** [comment]
@felixfbecker Ok, I tried disabling the extension, but the problem persists. Actually, IntelliSense is providing PHP code completion whether or not there's a `<?php` tag, but snippets, even built-in ones, are only shown if there's a `<?` or `<?php` tag.

![capturfiles-15-14-2016_01 14 08](https://cloud.githubusercontent.com/assets/463168/21232014/fcd1bff8-c2c8-11e6-96f5-7623604469a7.png)

**Comment by roblourens** [comment]
Still the case - the snippet portion is by design. The intellisense is just because the builtin portion is not very smart. But probably not going to fix it.

**Comment by TomTheBert** [comment]
So I basically worked this out. A .php file is basically treated as an html file since everything outside the php code block is html. Put the snippet to open/close the php tags in the html.json snippet file. Then if you want an html snippet available within a block of php code, you need to put that snippet in the php.json file.
