### ISSUE TITLE
Keyboard editor color

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#173107]
<img width="958" alt="image" src="https://user-images.githubusercontent.com/900690/216242468-9b86c9a3-8096-46fe-a718-fe55fa6461d4.png">

Color seems off when input is opened.

**Comment by bpasero** [comment]
I think I ran out of sources.

//cc @sandy081

**Comment by aeschli** [comment]
@bpasero can no longer reproduce, closing
