### ISSUE TITLE
Allow editing "files to include" / "files to exclude" pattern lists

### ISSUE THREAD

**Issue by nsh-ableton** [microsoft/vscode#173129]
I have an ever-growing list of patterns in "files to include". Some of these patterns are one-off filters that I would like to discard. I can't find where this list is saved, to manually edit it. I would like to at least be able to edit a file where these patterns are saved; even more awesome would be a UI-based capability to do the same.

**Comment by andreamah** [comment]
If you use the Search Editor (command: `Search Editor: Open Search Editor`), then you can make searches and save the queries for later.

**Comment by ArturoDent** [comment]
Are you talking about the history (up/down arrows) for the `files to include` and `files to exclude` input boxes?  And then you want to remove some of those I take it.

**Comment by andreamah** [comment]
I believe that this would be included in #23099

**Comment by andreamah** [comment]
Oh, I just noticed that this request is similar to https://github.com/microsoft/vscode/issues/47583, which was linked back to https://github.com/microsoft/vscode/issues/23099. Sorry for the lack of clarity. If I remember correctly, the history input boxes are all backed by the same code, so implementing a dropdown for one *should* carry over to the others.
