### ISSUE TITLE
Perf web worker fails in our server (fibonacci numbers)

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#173104]
**Steps:**
* from command line run `vscode-bisect -c latest -r web --perf`
* it stalls

```
(Refused to create a worker from 'blob:http://localhost:8000/2faf00e9-f705-4f30-8a71-cc3dba3edeb5' because it violates the following Content Security Policy directive: "worker-src 'self' data:".)
```

We maybe missing a web worker related directive in our HTML files?

https://github.com/microsoft/vscode/blob/12d2e0bfa6cceb129c2fb6491035cc6976956cf2/src/vs/server/node/webClientServer.ts#L342-L354

//cc @sandy081

**Comment by jrieken** [comment]
Yeah, looks like `worker-src` needs to allow-list `blob`

**Comment by jrieken** [comment]
May candidate? But I am unsure when/where/how the CSP are into effect. @bpasero where do you see this? I have checked

* insiders.vscode.dev ✅ CSP allows blob as worker-src
* codespaces ✅ CSP allows blob as worker-src
* ????

**Comment by bpasero** [comment]
@jrieken I saw it with our web bits from our server, so basically:
* download server
* run it
* access the web UI

I am not sure this would be a candidate for today, but maybe recovery and only if we see an actual issue from it. So far this is only an issue for perf testing, but we do not perf test our server, only insiders.vscode.dev atm.
