### ISSUE TITLE
Ability to configure the default log level from VS Code

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#173120]
Ability to configure the default log level from VS Code

**Comment by sandy081** [comment]
To verify:

1. F1 > Set Log Level...
2. Set the default log level using the action available on the log level. 
3. Make sure the default log level is updated and also the current log level if the current log level is not default log level
4 Restart VS Code and make sure the default log level is updated.
5. Try 2-5 steps for updating the default log level of extensions

**Comment by jrieken** [comment]
@sandy081 would the double checkmark (`check-all`) be a better icon for this?

**Comment by sandy081** [comment]
Yeah, will change the icon.
