### ISSUE TITLE
Connect to Azure MLStudio from VSCode (via proxy) - Invalid response: 407 authenticationrequired

### ISSUE THREAD

**Issue by prasiyer** [microsoft/vscode#173171]
Does this occur consistently? Yes
Repro steps:

Start Azure MLStudio Compute instance
Click on VSCode icon to connect from VSCode
Action: Resolver.resolve
Error type: 70
Error Message: Invalid response: 407 authenticationrequired

Version: 0.22.0
OS: win32
OS Release: 10.0.19044
Product: Visual Studio Code
Product Version: 1.74.3
Language: en

s extension.js:2:1926253
extension.js:2:1959307extension.js:2:1959307

**Comment by chrmarti** [comment]
Tracking in https://github.com/microsoft/vscode/issues/12588. Also see if https://github.com/microsoft/vscode/issues/12588#issuecomment-937324160 helps.
