### ISSUE TITLE
Inconsistent Markdown Preview behavior with nested lists and code blocks

### ISSUE THREAD

**Issue by abergerSRS** [microsoft/vscode#173185]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.74.3
- OS Version: Windows 11

I'm finding inconsistent behavior with Markdown preview for nested lists that are interrupted by code block.

Source code:
```md
1. First item  
  a. first sub-item  
  b. second sub-item  

    ```python
    print("Hello World")
    ```

  c. third sub-item
```

Note that in the markdown source, (c.) is aligned with (a.) and (b.). However, in the VS Code Markdown preview, bullet (c.) is aligned with (1.).  This is undesired and different behavior from that obtained at [markdownlivepreview](https://markdownlivepreview.com/).

Compare that to the following:
Source code:
```md
1. First item  
  a. first sub-item  
  b. second sub-item  

    ```python
    print("Hello World")
    ```

    c. third sub-item
```

Here, (c.) has been indented by two additional spaces relative to (a.) and (b.). Surprisingly, in the VS Code Markdown preview, this results in bullet (c) aligned with (a) and (b), as desired. This is consistent with [stackedit.io](https://stackedit.io/app#). 

Which is the correct behavior per Markdown spec?

**Comment by mjbvz** [comment]
We try to align with the common mark spec with our built-in markdown support. [Here's their standard of this markdown](https://spec.commonmark.org/dingus/?text=1.%20First%20item%20%20%0A%20%20a.%20first%20sub-item%20%20%0A%20%20b.%20second%20sub-item%20%20%0A%0A%20%20%20%20%60%60%60python%0A%20%20%20%20print(%22Hello%20World%22)%0A%20%20%20%20%60%60%60%0A%0A%20%20c.%20third%20sub-item%0A%0A---%20%0A%0A1.%20First%20item%20%20%0A%20%20a.%20first%20sub-item%20%20%0A%20%20b.%20second%20sub-item%20%20%0A%0A%20%20%20%20%60%60%60python%0A%20%20%20%20print(%22Hello%20World%22)%0A%20%20%20%20%60%60%60%0A%0A%20%20%20%20c.%20third%20sub-item%0A%0A)

I believe this matches how VS Code renders this in the builtin markdown preview:

![Screenshot 2023-02-02 at 5 59 10 PM](https://user-images.githubusercontent.com/12821956/216493649-65d13f2d-8835-4594-9f4c-3d7a108a4cb7.png)


Let me know if I overlooked something here
