### ISSUE TITLE
terminal (pwsh) cannot print color

### ISSUE THREAD

**Issue by mozhuanzuojing** [microsoft/vscode#173103]
Does this issue occur when all extensions are disabled?: No

Version: 1.74.3 (system setup)
OS: Windows_NT x64 10.0.22621
Sandboxed: No

Steps to Reproduce:

1.  install PowerShell 7.3.2
2.  write a method main in ConsoleColorTest .java
```java
public class ConsoleColorTest {
    public static void main(String[] args) {
        System.err.println("output red color");
    }
}
```

Screen 

![image](https://user-images.githubusercontent.com/63572041/216237756-92b8b1d7-aadc-4451-92b6-48bce6c2dd2f.png)

**Comment by meganrogge** [comment]
does this work in an external pwsh terminal?

**Comment by mozhuanzuojing** [comment]
> does this work in an external pwsh terminal?

no, it is not work in external pwsh terminal

**Comment by mozhuanzuojing** [comment]
@meganrogge  Thank you, I kind of understand my question.
