### ISSUE TITLE
Mac multiple workspace presence

### ISSUE THREAD

**Issue by shadab005** [microsoft/vscode#173105]
Type: <b>Bug</b>

Hi Team

This is an issue of vscode with mac (using MacOS Ventura 13.2 but the issue can be present on different version).

On switching the workspace on mac the vscode even it it is not supposed to be on every workspace it keeps on showing in foreground. This is not the case with other apps.

VS Code version: Code 1.74.3 (Universal) (97dec172d3256f8ca4bfb2143f3f76b503ca0534, 2023-01-09T17:07:18.579Z)
OS version: Darwin x64 22.3.0
Modes:
Sandboxed: No

**Comment by shadab005** [comment]
Steps:
1. Suppose you have 2 workspace on mac. Keep all the apps closed to start with
2. Open first workspace, open vscode on mac (using MacOS Ventura 13.2 but the issue can be present probably on different version). A
3. Switch to the second workspace in mac. You will notice the vscode in foreground in the second workspace as well.
4. If I do the same steps from step 1 to step 3 with any other app, the app remains in the first workspace and doesn't come in foreground in the second workspace. This has always been the ideal behavior on mac and expecting the same with vscode.

**Comment by bpasero** [comment]
I cannot reproduce, for me on the second workspace VS Code is not in foreground (though it is showing up in the dock as running).

So I suspect a configuration issue on your end and not something VS Code can address.

**Comment by shadab005** [comment]
Not sure. Because VSCode is the only app that is behaving in this way on my system. Anyway, if you think it could be specific to my system and also checked on few other machines feel free to close this issue.

**Comment by shadab005** [comment]
Found the solution here: https://github.com/microsoft/vscode/issues/56845#issuecomment-416243880
