### ISSUE TITLE
Vs code not working for inputting values

### ISSUE THREAD

**Issue by n0a-h** [microsoft/vscode#173151]
Type: <b>Performance Issue</b>

I've installed mingw alongwith the extensions, but still VScode is not scanning value, it is printing the values tho.

VS Code version: Code 1.74.3 (97dec172d3256f8ca4bfb2143f3f76b503ca0534, 2023-01-09T16:57:40.428Z)
OS version: Linux x64 5.15.0-58-generic
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 3 3200U with Radeon Vega Mobile Gfx (4 x 1400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|1, 1, 1|
|Memory (System)|5.74GB (3.36GB free)|
|Process Argv|--unity-launch --crash-reporter-id b2999d72-9260-41b5-9b8a-b108e1291d5d|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|pantheon|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|pantheon|
|XDG_SESSION_TYPE|x11|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	   159	  1606	code main
    0	    41	  1612	   zygote
    0	   141	  1643	     gpu-process
    0	    41	  1613	   zygote
    0	    12	  1615	     zygote
    1	   235	  1688	       window (● #include<iostream> • Untitled-1 - nw - Visual Studio Code)
    0	    88	  9612	       issue-reporter
    0	    59	  1660	   utility-network-service
    0	   165	  1724	   extension-host
    0	    53	  1831	     /home/n0ah/.vscode/extensions/ms-vscode.cpptools-1.13.9-linux-x64/bin/cpptools
    0	    71	  1853	     /usr/share/code/code --ms-enable-electron-run-as-node /usr/share/code/resources/app/extensions/json-language-features/server/dist/node/jsonServerMain --node-ipc --clientProcessId=1724
    0	   135	  1740	   shared-process
    0	    76	  1753	     ptyHost
    0	     0	  1906	       /usr/bin/bash
    0	    71	  1801	     fileWatcher
    0	     0	  9630	     /bin/sh -c /usr/bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0	     0	  9631	       /usr/bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (● #include<iostream> • Untitled-1 - nw - Visual Studio Code)
|    Folder (nw): 8 files
|      File types: json(4) cpp(1)
|      Conf files: launch.json(1) settings.json(1) tasks.json(1)
|      Launch Configs: cppdbg;
```

</details>
<details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
code-runner|for|0.12.0
cmake-tools|ms-|1.13.45
cpptools|ms-|1.13.9

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscorecescf:30445987
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
azure-dev_surveyone:30548225
vsccc:30610678
pyindex848cf:30577861
nodejswelcome1cf:30587006
282f8724:30602487
f6dab269:30613381
vscsb:30628654

```

</details>

**Comment by sbatten** [comment]
This issue is not caused by VS Code. I recommend you look to stackoverflow for assistance.
