### ISSUE TITLE
Expand Selection less useful on XML

### ISSUE THREAD

**Issue by msafi** [microsoft/vscode#173123]
Given this XML file

```xml
<?xml version="1.0" encoding="utf-8"?>
<odoo>
  <data>
    <menuitem id="estate_menu_root" name="Real Estate">
      <menuitem id="estate_menu_first_level" name="Advertisements">
        <!-- CURSOR HERE --> <menuitem id="estate_model_menu_action" action="estate_action"/>
      </menuitem>

      <menuitem id="estate_type_menu_first_level" name="Settings">
        <menuitem id="estate_type_model_menu_action" action="estate_type_action"/>
        <menuitem id="estate_tags_model_menu_action" action="estate_tags_action"/>
      </menuitem>
    </menuitem>
  </data>
</odoo>
```

If my cursor is where it says `<!-- CURSOR HERE -->`, and I trigger an `Expand Selection` command, I expect to select just the line where the cursor is. Then expand to the immediate surrounding tag. Then the next tag, etc. 

However, in reality, what happens is, it selects the entire document from top to bottom. That's not very useful.

Is that the intended behavior?

**Comment by jrieken** [comment]
This issue lacks

* mentioning of extensions that provide these results or the lack of therefore

**Comment by msafi** [comment]
Hi @jrieken. This issue is about the built-in smart select feature in VSCode. No extension needed.

<img width="1179" alt="image" src="https://user-images.githubusercontent.com/4027731/216551279-89f0cdd4-6eae-4422-bfeb-7dee56a0479c.png">

**Comment by jrieken** [comment]
I know but that feature only comes with a default, best-effort solution and needs extension support to really shine.

**Comment by jrieken** [comment]
Closing this as extension-candidate

**Comment by msafi** [comment]
@jrieken Sorry, I don't understand. The Smart Select feature works great in React's JSX files. Does it work so well there because of some extension? Does that mean I have to look for some extension that enhances Smart Select for XML files?

**Comment by jrieken** [comment]
Yes - that's what it means

**Comment by msafi** [comment]
@jrieken You're right. I installed [XML language support](https://marketplace.visualstudio.com/items?itemName=redhat.vscode-xml) and now it works much better. Thanks for your time!
