### ISSUE TITLE
JavaScript IntelliSense not working in 1.8.0

### ISSUE THREAD

**Issue by bargeruns** [Microsoft/vscode#17317]
With this latest update, Intellisense no longer works in the project I was working on prior to the update.  When attempting to invoke IS or when hovering over a symbol or variable in the project, all I see is "loading". Sometimes I will see the "configure excludes" message, but these are already configured and haven't changed since the update. This is a fairly large Node project with many sub-apps, but Intellisense always worked fine prior to the update. I checked a smaller project, and everything is working as expected there.

- VSCode Version: Code 1.8.0 (38746938a4ab94f2f57d9e1309c51fd6fb37553d, 2016-12-13T17:38:28.425Z)
- OS Version: Darwin x64 16.1.0
- Extensions:

|Extension|Author|Version|
|---|---|---|
|vscode-markdownlint|DavidAnson|0.6.0|
|beautify|HookyQR|0.6.2|
|material-icon-theme|PKief|1.1.4|
|indenticator|SirTori|0.2.1|
|html-snippets|abusaidm|0.0.18|
|amvim|auiworks|1.20.0|
|npm-intellisense|christian-kohler|1.1.0|
|path-intellisense|christian-kohler|1.2.0|
|vscode-eslint|dbaeumer|1.2.1|
|githistory|donjayamanne|0.1.4|
|theme-dracula|dracula-theme|1.2.5|
|RelativePath|jakob101|0.11.0|
|vscode-pugbeautify|mrmlnc|1.0.2|
|js-atom-grammar|ms-vscode|0.1.10|
|preview-vscode|searKing|1.1.1|
|stylelint|shinnn|0.13.0|
|html2jade|wmaurer|0.2.0|

---

Steps to Reproduce:

1. Upgrade to 1.8.0 from 1.7.1
2. Open large Node/ReactJS project and attempt to use Intellisense.

**Comment by waderyan** [comment]
I'm not seeing this issue. Can you share your workspace? Also try running VS Code without any extensions `--disable-extensions` to isolate the extensions out.

**Comment by mjbvz** [comment]
Closing as we need more information to investigate this.

@bargeruns, please try using `--disable-extensions` and seeing if the problem still occurs. If it does, please share your workspace so that we can investigate.

Thanks
