### ISSUE TITLE
Dulicate messsage warning

### ISSUE THREAD

**Issue by MrAmericanMike** [microsoft/vscode#173152]
Type: <b>Bug</b>

On any .js file with this code

console.log("eff 󠀀".trim().length);

When you hover over the invisible character after eff there is a popup that shows 2 times the same warning.

VS Code version: Code 1.74.3 (97dec172d3256f8ca4bfb2143f3f76b503ca0534, 2023-01-09T16:59:02.252Z)
OS version: Windows_NT x64 10.0.22623
Modes:
Sandboxed: No

**Comment by MrAmericanMike** [comment]
![Screenshot 2023-02-02 105443](https://user-images.githubusercontent.com/8037559/216345907-343c10c1-a387-4acf-a741-f10244d7a4fa.png)

Sorry VSCode created the issue, but didn't allow to attach a screenshot, so here it is.

**Comment by hediet** [comment]
The reason there are two messages is that there are actually two characters:

![image](https://user-images.githubusercontent.com/2931520/217013078-cbc8787f-d6f8-49e7-bebd-4791e255c371.png)

(backspace deletes both at once though)

**Comment by MrAmericanMike** [comment]
> The reason there are two messages is that there are actually two characters:

Oh, missed that, I though it was 1 space and then that character.
