### ISSUE TITLE
Add setting to disable prompt for auto publishing branches when using Continue On

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode#173163]
The "fix" for this is more problematic for me.

I used to have this in my settings:

```json
  "git.publishBeforeContinueOn": "never"
```

Now every time I quit VS Code (I'm on Mac if it makes a difference), I see the dialog and I have to press "Cancel". Even worse, pressing "Cancel" seems to only close the dialog and reopen it again.

@joyceerhl, can we reopen this issue and restore the setting at least?
That'd be highly appreciated. Thanks.

_Originally posted by @Meligy in https://github.com/microsoft/vscode/issues/172144#issuecomment-1413569170_

**Comment by joyceerhl** [comment]
@meligy do you have the following setting configured: `"workbench.experimental.cloudChanges.autoStore"`? If you do not, then this dialog should not be impacting your workflow.

**Comment by Meligy** [comment]
Good point. I actually did, playing with something before I guess!
Thanks a lot. Removing it solves it.
