### ISSUE TITLE
Crash reported by Visual Studio

### ISSUE THREAD

**Issue by bduhbya** [microsoft/vscode#173177]
Type: <b>Bug</b>

The studio was idle and I was working on other things. When I returned to the IDE, I had a notification of JavaScript language feature crashes.

VS Code version: Code 1.74.3 (97dec172d3256f8ca4bfb2143f3f76b503ca0534, 2023-01-09T16:59:02.252Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|12th Gen Intel(R) Core(TM) i9-12900H (20 x 2918)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|63.68GB (41.66GB free)|
|Process Argv|--crash-reporter-id 50ef1968-1076-48ac-8377-07081b05c51d|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (51)</summary>

Extension|Author (truncated)|Version
---|---|---
project-manager|ale|12.7.0
tsl-problem-matcher|amo|0.6.2
markdown-mermaid|bie|1.17.4
npm-intellisense|chr|1.4.4
path-intellisense|chr|2.8.4
gitignore|cod|0.9.0
doxdocgen|csc|1.4.0
vscode-eslint|dba|2.2.6
githistory|don|0.6.19
gitlens|eam|13.2.0
vscode-npm-script|eg2|0.3.29
prettier-vscode|esb|9.10.4
vscode-jest-runner|fir|0.4.60
better-cpp-syntax|jef|1.17.2
graphql-for-vscode|kum|1.15.3
vscode-language-babel|mgm|0.0.36
git-graph|mhu|1.30.0
csharp|ms-|1.25.4
isort|ms-|2022.8.0
python|ms-|2022.20.2
vscode-pylance|ms-|2023.2.10
sarif-viewer|MS-|3.3.5
jupyter|ms-|2022.11.1003412109
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.14
vscode-jupyter-cell-tags|ms-|0.1.6
vscode-jupyter-slideshow|ms-|0.1.5
remote-containers|ms-|0.266.1
remote-wsl|ms-|0.72.0
cmake-tools|ms-|1.13.45
cpptools|ms-|1.13.9
cpptools-extension-pack|ms-|1.3.0
makefile-tools|ms-|0.6.0
powershell|ms-|2023.1.0
remote-explorer|ms-|0.2.0
debugger-for-chrome|msj|4.13.0
java|red|1.14.0
markdown-preview-enhanced|shd|0.6.7
teams-dyson|tea|0.0.2023010501
cmake|twx|0.0.17
alphabetical-sorter|ue|2.0.1
intellicode-api-usage-examples|Vis|0.2.7
vscodeintellicode|Vis|1.2.30
vscode-gradle|vsc|3.12.6
vscode-java-debug|vsc|0.48.0
vscode-java-dependency|vsc|0.21.1
vscode-java-pack|vsc|0.25.7
vscode-java-test|vsc|0.37.1
vscode-maven|vsc|0.40.4
vim|vsc|1.24.3
vscode-open-in-github|ziy|1.3.6

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
azure-dev_surveyone:30548225
vsccc:30610678
pyindex848:30577860
nodejswelcome1cf:30587006
282f8724:30602487
f6dab269:30613381
pythonsymbol12:30652348
a9j8j154:30646983

```

</details>

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

**Comment by bduhbya** [comment]
I am unsure.  If I understood the Error message correctly, it was with the
javascript and type script features. I'm unsure if these are extensions.

 It's only happened once and the IDE suggested I report the bug. At this
time I do not have the bandwidth 2 test further. You may close the bug if
it seems like it should not be an issue.

Regards,

Brent
