### ISSUE TITLE
same shortkey for next match and replace.

### ISSUE THREAD

**Issue by florenso** [microsoft/vscode#173133]
while searching the shortkey for "next match" is <enter>. When i press "toggle replace" i see that the button "replace" has the same sortkey as "next match".

different shortkey actions for the same hotkey based on focus feels kinda strange.

i think changing the shortkey for "next match" while in replace mode is a valid option, but might cause some shortkey configuration issues....

With the current implementation i can't audit my replacements quickly with shortcuts.

**Comment by andreamah** [comment]
Are you talking about the global search in the sidebar? or file find (ctrl+f in editor)?

**Comment by florenso** [comment]
> Are you talking about the global search in the sidebar? or file find (ctrl+f in editor)?

the file find
