### ISSUE TITLE
`Event.accumulate()` looses events

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#173111]
https://github.com/microsoft/vscode/pull/163845 was an attempt to defer events for history service processing but it caused https://github.com/microsoft/vscode/issues/173109.

This issue is to see how we can bring the debouncing back without causing regressions.

**Comment by bpasero** [comment]
This seems to be a bug with `Event.accumulate` introduced by https://github.com/microsoft/vscode/commit/c99fef2210f7a5f7adfb9f14cf1871f414578a3f. In my testing, instead of buffering the events as they come, the first one is dropped.

I see 3 users that maybe are now broken (well 2, after I have reverted the use for history service).

I suggest to write a test for this and ensure it works that no events are dropped.

**Comment by bpasero** [comment]
Updating this issue to reflect the `Event` part that is hard to digest for history service as it works today. However there is a bigger issue for history service in general and that is captured in https://github.com/microsoft/vscode/issues/173411

**Comment by Tyriar** [comment]
Fixed in https://github.com/microsoft/vscode/pull/173341
