### ISSUE TITLE
Guide users when signature verification fails due to unmet dependencies

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#173172]
Owner: @dtivel and @isidorn 

Currently when a user has unmet dependencies for `vsce-sign` we silently fail and allow the extension to be installed. Instead of this we should guide the users to install these unmet dependencies. So I propose we:
1. Keep these errors as non blocking
2. On error show a warning notification
3. The warning notification would have a text about "unmet dependencies" and will have a "Learn More" button
4. The "Learn More" button would be an `aka.ms` link that points to VS Code docs
5. In the VS Code docs we would add a new section around https://code.visualstudio.com/docs/supporting/FAQ#_vs-code-gets-unresponsive-right-after-opening-a-folder

fyi @joaomoreno @sandy081

**Comment by isidorn** [comment]
This looks great to me.

To clarify "Offer to install anyway" would show a modal dialog with an "Install Anyway" button - image below.
"Block and redirect" would also show a modal dialog but with a more scary message and a "More Info" button (without the "Install Anyway" button).

If the action is not user initiated (for example extension auto update) - then we would not show the modal dialog but a notification.

@sandy081 what do you think? I know you started work on this, is there a PR or it is on your local machine?

![image](https://user-images.githubusercontent.com/1926584/225650008-da5dd188-825c-46dc-a20c-f9a2a6c767ea.png)

**Comment by isidorn** [comment]
After discussing with @sandy081 we think that we should push the changes such that for every signature verification error we show the above dialog. This includes invalid package, unknown error, tampered package and all the other errors. We need to make it easier for users to install if an error happens which might be more common due to Marketplace CDN inconsistencies. This also helps us to not turn off signature verification by default.

Going forward we will ONLY show this dialog for the Unable to launch `vsce-sign` and error in `vsce-sign`. As @dtivel suggest above. And we will show another dialog with a "Learn More" button for cases as @dtivel suggests.

**Comment by joaomoreno** [comment]
@dtivel Those are some serious graph skills.

**Comment by isidorn** [comment]
https://vscode.download.prss.microsoft.com/dbazure/download/stable/eaa41d57266683296de7d118f574d0c2652e1fc4/VSCode-darwin.zip

**Comment by isidorn** [comment]
https://vscode.download.prss.microsoft.com/dbazure/download/stable/eaa41d57266683296de7d118f574d0c2652e1fc4/VSCode-darwin-universal.zip

**Comment by isidorn** [comment]
Closing as done
