### ISSUE TITLE
Cannot read properties of undefined (reading 'cell')

### ISSUE THREAD

**Issue by siman4457** [microsoft/vscode#173180]
Does this issue occur when all extensions are disabled?: (Yes)/No

- VS Code Version: 1.74.3
- OS Version: MacOS Ventura 13.1

Steps to Reproduce:

1. Open a new terminal
2. An error message appears: Cannot read properties of undefined (reading 'cell')

I've tried reinstalling vscode, deleting contents of settings.json, and disabling all my extensions. None of these resolved the issue.

**Comment by joyceerhl** [comment]
I cannot repro, is this still an issue @siman4457?

**Comment by siman4457** [comment]
Outdated
