### ISSUE TITLE
importmap syntax highlight support

### ISSUE THREAD

**Issue by tjx666** [microsoft/vscode#173158]
<img width="1004" alt="image" src="https://user-images.githubusercontent.com/41773861/216364020-f8a857d1-10c9-426a-afc7-d0932b9ca883.png">

I find there had been an extension implements this: [VSCode Extension json-in-html](https://github.com/bahrus/json-in-html)
But I think this should be a builtin feature.

Ref: [MDN importmap](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/script/type/importmap)

@aeschli

**Comment by alexr00** [comment]
Upstream issue: https://github.com/textmate/html.tmbundle/issues/103
