### ISSUE TITLE
Don't group debug console output

### ISSUE THREAD

**Issue by felixfbecker** [Microsoft/vscode#17314]
- VSCode Version: 1.9.0-insiders

Expected:

![image](https://cloud.githubusercontent.com/assets/10532611/21231352/40ba75d8-c2e8-11e6-926d-c69a57298964.png)

Actual:

![image](https://cloud.githubusercontent.com/assets/10532611/21231302/1702ccc2-c2e8-11e6-8a71-e0fd5ec2e375.png)

**Comment by weinand** [comment]
@isidorn it doesn't make sense to group single characters like this.
