### ISSUE TITLE
Icons in problems view show black when not focused

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#173148]
<img width="306" alt="image" src="https://user-images.githubusercontent.com/900690/216332563-c418e8f0-550e-4bda-b3da-4783b204c5a1.png">

compared to stable:

<img width="380" alt="image" src="https://user-images.githubusercontent.com/900690/216332838-3a00d383-e925-419a-99e9-e68200573ff6.png">

**Comment by bpasero** [comment]
@aeschli I am still seeing this in light theme:

![image](https://user-images.githubusercontent.com/900690/218950739-2e5455db-d682-484a-9e2e-703da7c7508c.png)

**Comment by aeschli** [comment]
Fixed by https://github.com/microsoft/vscode/pull/174487
