### ISSUE TITLE
Disable double click in file tree list to create new file

### ISSUE THREAD

**Issue by heroboy** [microsoft/vscode#173261]
Currently, if you double click the empty area of tree list(include the scrollbar area), it will act like to click the "New File..." button. It show a input control and scroll to.

In the recent 1.75 release, there's a new setting ["workbench.list.scrollByPage"](https://code.visualstudio.com/updates/v1_75#_list-scroll-by-page), this setting let you click the scrollbar area to scroll by page not scroll to.

When this setting is true, you may need rapidly click the scrollbar to scroll many pages. And vscode will recognize it as double click. Then the scrollbar jump back.

**Comment by heroboy** [comment]
[aa.webm](https://user-images.githubusercontent.com/54468/216549852-79c0b4b6-6451-4e28-a0a1-2265075c1fce.webm)

**Comment by lramos15** [comment]
So this really only needs to be fixed in the case where scroll by page is enabled because otherwise you wouldn't be spamming mouse click?

**Comment by heroboy** [comment]
Shall I recreate this as a bug, not feature request?

**Comment by lramos15** [comment]
> Shall I recreate this as a bug, not feature request?

No worries, I can label it as a bug just trying to understand the scope of the problem. It's only for scroll by page right?

**Comment by heroboy** [comment]
Yes. I never know this, unless scroll by page introduced.
