### ISSUE TITLE
Terminal Scroll bar option to autoscroll to bottom

### ISSUE THREAD

**Issue by maverickfalcon** [Microsoft/vscode#17325]
- VSCode Version: 1.8
- OS Version: Win 10

Steps to Reproduce:

1. Upgrade to 1.8
2. The terminal will no longer scroll to the bottom when it receives output if you have scrolled up
Please add an option to re-enable this.  I want it to auto scroll to the bottom of the page.

**Comment by eamodio** [comment]
Or at least have it re-autoscroll if you've scrolled the terminal back to the end

**Comment by Tyriar** [comment]
@eamodio if it's not auto scrolling again once you're at the bottom that's definitely a bug.

**Comment by eamodio** [comment]
@Tyriar sorry just went to check again and I apparently got confused -- the terminal works fine! It is the output pane that doesn't auto-scroll when you are at the bottom. I'll open another issue for that.
