### ISSUE TITLE
Inline suggestions support for line-by-line acceptance

### ISSUE THREAD

**Issue by njiang747** [microsoft/vscode#173209]
I saw that the word-by-word acceptance feature for inline suggestions was released in the 1.75 release (though it seems there is still a bug https://github.com/microsoft/vscode/issues/172162).

I think it would be great if we could also have line-by-line suggestion acceptance with default keybindings of `Ctrl+DownArrow` and `Ctrl+UpArrow`.

**Comment by hediet** [comment]
You can bind a keybinding:
```json
    {
        "key": "shift+tab",
        "command": "editor.action.inlineSuggest.acceptNextLine",
        "when": "inlineSuggestionVisible"
    }
```

Or use the hover:
![Code_-_OSS_f5nDDdSpcS](https://user-images.githubusercontent.com/2931520/233639617-afb37cef-2b74-48b2-81b0-77209b2ec36e.png)
