### ISSUE TITLE
vs code auto update is not working for me

### ISSUE THREAD

**Issue by Skyrioca** [microsoft/vscode#173207]
Type: <b>Bug</b>

vs code auto update is not working for me
I need download from site every time
I dont know how to reproduce
the only diference that I think is that I configure the code.exe in properties to always run as administrator

VS Code version: Code 1.75.0 (e2816fe719a4026ffa1ee0189dc89bdfdbafb164, 2023-02-01T15:23:45.584Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 5700G with Radeon Graphics          (16 x 3800)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|59.80GB (50.06GB free)|
|Process Argv|C:\\Projetos\\SKYRIOCA\\Ticket\\ticket-backend --crash-reporter-id 965585d9-b562-43c1-b3a2-390c3e567a98|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (19)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|3.0.2
npm-intellisense|chr|1.4.4
vscode-eslint|dba|2.2.6
gitlens|eam|13.2.0
auto-rename-tag|for|0.1.10
git-graph|mhu|1.30.0
remote-wsl|ms-|0.75.1
vsliveshare|ms-|1.0.5828
reload|nat|0.0.6
material-icon-theme|PKi|4.23.1
LiveServer|rit|5.7.9
vue-vscode-snippets|sdr|3.1.1
code-settings-sync|Sha|3.4.3
sonarlint-vscode|Son|3.14.0
unique-window-colors|stu|1.0.51
vscode-icons|vsc|12.2.0
volar|Vue|1.0.24
vscode-import-cost|wix|3.3.0
php-debug|xde|1.31.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
azure-dev_surveyone:30548225
vscccc:30610679
pyindex848:30577860
nodejswelcome1cf:30587006
282f8724:30602487
f6dab269:30613381
pythonsymbol12cf:30657549
a9j8j154:30646983

```

</details>

**Comment by IllusionMH** [comment]
What do you mean under "not working for me"?

It is hidden for user installs when running as administrator.
See #157624 and related issues.

If you run as administrator you should consider using system installation or running user installation in non-elevated mode.

**Comment by Skyrioca** [comment]
means that the functionality is not working for me ;-) I did the system installation that you recommended and now the update option reappeared. thanks for the help and sorry for not knowing

**Comment by IllusionMH** [comment]
"not working" is very broad term. It can mean that opdate option hidden, errors during check, download, or installation etc.
Therefore you should try to provide exact problem description/steps and expectation in future.

Glad that system installation work for you
