### ISSUE TITLE
Suboptimal hotkey workflow for "find in files"

### ISSUE THREAD

**Issue by gianlucaborello** [Microsoft/vscode#17324]
- VSCode Version: 1.9.0-insider
- OS Version: macOS 10.12.2

First of all, I love this editor, it's making me switch away from Sublime and vim.

However, working on a very large code base (the Linux kernel), I have a workflow that is suboptimal. I heavily rely on the "find in files" feature, as the C/C++ intellisense can't go far enough to solve all the things I usually look for (think: nested macros and such), which is totally ok.

So, this is my typical workflow:

1) CMD+Shift+F, enter the text to search and press enter
2) I get many matches, and usually I need to scan through the matching occurrences (in preview mode in an editor) in order to fully understand the one I need (the line shown in the side bar is usually not enough). In Sublime (or vim), I can quickly open an editor showing the matching occurrences using F4/Shift-F4.

In Code, using the keyboard the two only options I can find are:

- In the search side bar, press "down" until I highlight a match, and then I can open the file pressing "enter". However, this makes me lose the focus in the side bar, so it becomes super inefficient if I want to switch to the next matching file.

- If, at the previous step, I press "space" instead of "enter", the file gets opened but I don't lose the focus, which is already much better, but less than ideal because to go to the next occurrence I still have to press first "down" twice and then "space" again, and the fact that it's not documented makes me a bit uncomfortable, as I heavily rely on this hotkey.

It seems like having hotkeys to jump to the next occurrence while in the side bar is definitely a common case for relatively power users. It's literally an operation I do hundreds of times a day, so every bit of efficiency I can gain is huge (and it's standard in Sublime and of course customizable in vim).

Thanks!

**Comment by roblourens** [comment]
Thanks for the suggestion. I didn't know about F4 in Sublime. That would be easy for us to implement.

How do you feel about this option?

When you press "down" to focus a search result, that result is automatically shown in the editor. This is like what you're doing with "space" except that you can just keep pressing the down arrow to navigate results.

**Comment by gianlucaborello** [comment]
What you are proposing sounds ideal, I'll be eagerly waiting for it in the Insiders :)

As food for thought for your team, I am leaving you another suggestion as to why a pure "F4" approach might still be better, although at this point we are just nitpicking: most of the times you need to press "down" twice (the first press highlights the file name containing the number of matches, whereas the second press actually highlights the first occurrence of that file), whereas the F4 function in Sublime (emulated in vim as well) directly jumps to the next occurrence, even across files, so that slightly more efficient where search occurrences are scattered around many files.

That being said, thank you very much @roblourens for considering my request, I highly appreciate your work, you guys are doing a killer product, I haven't been that excited about an editor in a long time :)

**Comment by roblourens** [comment]
I totally get why pressing down over each file name is annoying - that solution also brings in some other complications which make me inclined to simply do the F4 solution.

Thanks for your kind feedback :)

**Comment by jcbarton** [comment]
I've been looking for this in VS Code for a long time now - and tbh I assumed I just hadn't found the right name for the action! It is the one "pain point" for me usability wise - as it's the only point where I find myself reaching for the mouse to jump between results.

Great to know you are considering this. This feature is available in the "full" Visual Studio, and as @gianlucaborello  points out, it's available in sublime as well.

The ability to do a search across files, and quickly get the cursor on each of them with a single F4 click would be amazing (and shift-F4 to go to previous of course!). It is just about the only time where I find myself having to reach for the mouse to do this.

@gianlucaborello - thanks for pointing out how you operate at the moment - I hadn't even realised I could press down to jump between the results!

Oh, and @roblourens I also want to thank you and the team for the amazing work - and again, I've not been as excited about an editor in a long time either :)

**Comment by hesher** [comment]
Same issue as this: https://github.com/Microsoft/vscode/issues/13570
