### ISSUE TITLE
Resizing the files area / main area causes flickering and inaccurate resizing

### ISSUE THREAD

**Issue by kvoth3** [Microsoft/vscode#17321]
- VSCode Version: 1.8.0
- OS Version: Win10

Steps to Reproduce:

1.  Open a vscode project
2.  Resize the files section

![image](https://i.gyazo.com/55d00e11a28a83f081473402fd9f39f5.gif)

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/16985

**Comment by bpasero** [comment]
@kvoth3 does it reproduce when not having the terminal open?

**Comment by kvoth3** [comment]
Nope, only occurs with terminal open. Also, when the terminal is open and you resize, the flickering causes the terminal window to scroll down and down depending on how much to resize the window. It also makes the terminal unresponsive after a while.
