### ISSUE TITLE
SnippetString escaping doesn't work as documented for opening braces

### ISSUE THREAD

**Issue by DanTup** [Microsoft/vscode#17327]
- VSCode Version: 1.8
- OS Version: Windows 10

Let's say I want to complete the string (literally): `some text with $0 ${0:stuff} and \ LOL`. According to [the snippet docs](http://code.visualstudio.com/docs/customization/userdefinedsnippets#_creating-your-own-snippets), we should escape `$`, `{` and `}` with backslashes. In order to do this in a literal string, we need to use double-backslashes (to avoid the following characters being interpreted as control characters), so we have this:

```ts
completion.insertText = new SnippetString("some text with \\$0 \\$\\{0:stuff\\} and \\ LOL");
```

However, if you commit this completion, you will end up with:

```text
some text with $0 $\{0:stuff} and \ LOL
```

I believe the first backslash (before the opening brace) should not have appeared.

**Comment by jrieken** [comment]
When having `\\$\\{0:stuff\\}` only escape the `$`, like so `\\${0:stuff}`. More shouldn't be needed

**Comment by jrieken** [comment]
So, opening bracket doesn't need escaping according to http://code.visualstudio.com/docs/customization/userdefinedsnippets#_grammar. This might just need better doc as a 'fix'

**Comment by DanTup** [comment]
OK, so do braces every need escaping, or only when not after a `$`? (If conditional, it makes escaping more complicated than a simple `.replace`; maybe if that's the case you could add a helper to escape a string correctly?)

**Comment by jrieken** [comment]
You can use the `builder` methods on `SnippetString` to help you escape things, like `new SnippetString().appendText('${0:stuff}')`

**Comment by DanTup** [comment]
Ah, opening brace isn't in the docs. Either I misread or you already fixed. I'll update my code, thanks!

**Comment by jrieken** [comment]
k. I am closing this as question then

**Comment by DanTup** [comment]
Aha, didn't see those methods. That's great, thanks, think this is a non-issue now :+1
