### ISSUE TITLE
Poor contrast for Markdown/HTML code elements in V2 themes

### ISSUE THREAD

**Issue by ffried** [microsoft/vscode#173255]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.75.0 (Universal)
- OS Version: macOS 13.2
- About Window Contents:
```
Version: 1.75.0 (Universal)
Commit: e2816fe719a4026ffa1ee0189dc89bdfdbafb164
Date: 2023-02-01T15:24:42.903Z
Electron: 19.1.9
Chromium: 102.0.5005.194
Node.js: 16.14.2
V8: 10.2.154.23-electron.0
OS: Darwin arm64 22.3.0
Sandboxed: No
```

Steps to Reproduce:

1. Use new v2 themes.
2. Open a rendered HTML file with Code segments in it (e.g. the Releases notes for 1.75.0)
3. The markdown segments have a poor contrast compared to the other text. The contrast was a lot better in the old dark/light themes.

<img width="905" alt="dark mode" src="https://user-images.githubusercontent.com/1689782/216536323-94a03bd4-5dca-4f60-978d-f8085adb5f6a.png">
<img width="899" alt="light mode" src="https://user-images.githubusercontent.com/1689782/216536434-d386a8ec-8efd-4749-9e17-6013d4fd3ba8.png">

**Comment by Shinigami92** [comment]
I wanted to report the exact same issue 👍
