### ISSUE TITLE
In Dark+ V2 terminal display strange colouring

### ISSUE THREAD

**Issue by samir-jorge-araujo** [microsoft/vscode#173281]
Type: <b>Bug</b>

When running tests on the integrated terminal using ZSH and PowerLevel10k, sometimes the colour get a little strange as it can be seen on the print:
![Screenshot 2023-02-03 at 10 58 56](https://user-images.githubusercontent.com/24610866/216587497-35952920-57e4-4006-a3a6-dafcba4ec005.jpg)

VS Code version: Code 1.75.0 (Universal) (e2816fe719a4026ffa1ee0189dc89bdfdbafb164, 2023-02-01T15:24:42.903Z)
OS version: Darwin arm64 22.1.0
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Max (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|3, 2, 2|
|Memory (System)|64.00GB (3.68GB free)|
|Process Argv|--crash-reporter-id 2bfc91a0-bd54-4aa9-be81-30416a41de56|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (60)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|3.0.2
vscode-sql-formatter|adp|1.4.4
project-manager|ale|12.7.0
sort-imports|ama|6.3.1
laravel-extra-intellisense|ami|0.6.2
jest-snippets|and|1.9.1
vscode-intelephense-client|bme|1.9.4
turbo-console-log|Cha|2.6.2
laravel-goto-view|cod|1.3.8
hex-to-rgba|dak|1.0.0
mussumipsum|Dav|1.0.0
vscode-eslint|dba|2.2.6
vscode-faker|dee|2.0.0
vscode-new-file|dku|4.0.2
gitlens|eam|13.2.0
vsc-material-theme|Equ|33.6.0
vsc-material-theme-icons|equ|2.5.0
prettier-vscode|esb|9.10.4
codespaces|Git|1.13.7
vscode-graphql|Gra|0.8.5
vscode-graphql-execution|Gra|0.1.7
vscode-graphql-syntax|Gra|1.0.6
output-colorizer|IBM|0.1.2
nginx-log-highlighter|jak|1.1.0
react-jest-vscode-snippets|jal|0.0.3
lorem-whatever|job|1.0.2
svg|joc|1.5.0
vscode-peacock|joh|4.2.2
vscode-random|jre|1.11.0
php-cs-fixer|jun|0.3.8
php-add-property|kot|1.1.0
better-pest|m1g|0.1.0
php-namespace-resolver|Meh|1.1.9
dotenv|mik|1.0.1
vscode-docker|ms-|1.23.3
remote-containers|ms-|0.276.0
remote-ssh|ms-|0.96.0
remote-ssh-edit|ms-|0.84.0
remote-explorer|ms-|0.2.0
sublime-keybindings|ms-|4.0.10
color-highlight|nau|2.5.0
php-docblocker|nei|2.7.0
laravel-blade|one|1.32.0
laravel5-snippets|one|1.15.0
material-icon-theme|PKi|4.23.1
typescript-hero|rbb|3.0.0
vscode-xml|red|0.24.0
vscode-yaml|red|1.11.0
synthwave-vscode|Rob|0.1.15
px-to-rem|sai|1.3.1
vscode-blade-formatter|shu|0.20.8
gitconfig|sid|2.0.1
mdx|sil|0.1.1
indenticator|Sir|0.7.0
vscode-fileutils|sle|3.10.0
code-spell-checker|str|2.16.0
vscode-icons|vsc|12.2.0
vscode-nginx|wil|0.7.2
markdown-all-in-one|yzh|3.5.0
material-theme|zhu|3.15.6

(6 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263cf:30335440
vscoreces:30445986
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vscaat:30438848
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
azure-dev_surveyone:30548225
pyindex848cf:30577861
nodejswelcome1:30587005
282f8724:30602487
89544117:30613380
pythonsymbol12cf:30657549
vscsb:30628654

```

</details>

**Comment by senyai** [comment]
Fedora user here.
![image](https://user-images.githubusercontent.com/76137/216593516-f94e3714-2ab1-447f-abd3-a043603a65dd.png)

**Comment by marcin-zajac** [comment]
I have the same issue when pasting text into terminal and move between folders by Tab key.
Issue occurs only when canvas renderer is on (terminal.integrated.gpuAcceleration)

MacBook m1, zsh and powerlevel10k

![image](https://user-images.githubusercontent.com/57039654/216655465-a855ae57-8944-4268-93c0-58cb9e5fa18a.png)

![image](https://user-images.githubusercontent.com/57039654/216655744-9c8995b6-0562-4b91-9f9c-ff8c983b4166.png)

![image](https://user-images.githubusercontent.com/57039654/216655954-28ba31f2-fe8a-4c60-b8b6-9c2f2e76c38f.png)

**Comment by daviddossett** [comment]
This smells like it isn't related to the theme. @Tyriar or @meganrogge could confirm.

**Comment by samir-jorge-araujo** [comment]
Just to add to the thread, this does not occur with any other theme (Dark+ V1 included).
If there are any other tests that I can run, just let me know!

**Comment by jeremiahsnapp** [comment]
I'm also seeing this with the experimental Dark+ V2 theme. I specifically notice it when pasting text into the terminal or when viewing certain command line tools such as `top` and `atop` because they highlight some text the same way as pasting text into the terminal. The text looks fuzzy but as soon as I switch back to Dark+ V1 it becomes clean and crisp again.

I workaround this by adding the following to my settings. It is the same `terminal.foreground` value that is used in the [experimental Dark+ V2](https://github.com/microsoft/vscode/blob/b1dc961b977c3c4417b3ba3bd87a5d1dcb71c2bb/extensions/theme-defaults/themes/dark_plus_experimental.json#L122) but for some reason restating it in my settings fixes the theme.

```
{
  "workbench.colorCustomizations": {
     "terminal.foreground": "#cccccc",
  }
}
```

Dark+ V2 with fuzzy looking pasted text
<img width="459" alt="image" src="https://user-images.githubusercontent.com/430911/219769096-d1e2b3f1-fa1b-4a1d-b425-e2166b5fb85a.png">


Dark+ V2 with workaround and clean looking pasted text
<img width="459" alt="image" src="https://user-images.githubusercontent.com/430911/219771089-cae678e8-433e-47f6-becd-d46c35724fd4.png">

**Comment by daviddossett** [comment]
@jeremiahsnapp are you trying this in the stable release or Insiders? Insiders will reflect the recently updated foreground value and the issue should be fixed. Stable will still have the bug until we release the new version next week.

**Comment by jeremiahsnapp** [comment]
@daviddossett i'm using the stable release. i didn't know this was fixed in the insiders release. thanks for the good news!
