### ISSUE TITLE
Manual Download link generated is invalid

### ISSUE THREAD

**Issue by notatallshaw-gts** [microsoft/vscode#173215]
Does this issue occur when all extensions are disabled?: It requires at least the remote SSH extension to be enabled due to the nature of the bug, all other extensions can be disabled/uninstalled.

- VS Code Version: 1.75.0
- OS Version: Local Windows 10 21H2 / Remote Fedora 29

Steps to Reproduce:

1. Set-up VS Code with Remote SSH
2. Install Python Extension in to Remote SSH
3. Get error message and get asked to download manually
4. Browser opens link: https://marketplace.visualstudio.com/_apis/public/gallery/publishers/ms-python/vsextensions/python/2023.2.0/vspackage?targetPlatform=linux-x64 
5. Shows the following error text:
```
{"$id":"1","innerException":null,"message":"Version 2023.2.0 for extension ms-python.python has no support for targetPlatform linux-x64","typeName":"Microsoft.VisualStudio.Services.Gallery.WebApi.ExtensionVersionHasNoSupportForRequestedTargetPlatformsException, Microsoft.VisualStudio.Services.Gallery.WebApi","typeKey":"ExtensionVersionHasNoSupportForRequestedTargetPlatformsException","errorCode":0,"eventId":3000}
```
6. Assume it's because the extension hasn't been published for 2023.2.0 for Linux yet so try installing older version
7. Get same error and browser instead opens this link: https://marketplace.visualstudio.com/_apis/public/gallery/publishers/ms-python/vsextensions/python/2022.20.2/vspackage?targetPlatform=linux-x64
8. With very similar error text:
```
{"$id":"1","innerException":null,"message":"Version 2022.20.2 for extension ms-python.python has no support for targetPlatform linux-x64","typeName":"Microsoft.VisualStudio.Services.Gallery.WebApi.ExtensionVersionHasNoSupportForRequestedTargetPlatformsException, Microsoft.VisualStudio.Services.Gallery.WebApi","typeKey":"ExtensionVersionHasNoSupportForRequestedTargetPlatformsException","errorCode":0,"eventId":3000}
```

I have had to revert to 1.74.3 where I am not getting this error so can I continue to work, but if you need me to test things again I can install 1.75.0 again and retest.

**Comment by schlunma** [comment]
I am having the same issue since upgrading to VSCode 1.75.0. When trying to update the Python extension on the remote server I get an


```
Error while updating 'Python' extension. Please check the log for more details.
```

with the log

```
2023-02-03 09:54:13.643 [error] Signature: Untrusted
    at Pn.download (~/.vscode-server/bin/e2816fe719a4026ffa1ee0189dc89bdfdbafb164/out/vs/server/node/server.main.js:113:1922)
    at async U.h (~/.vscode-server/bin/e2816fe719a4026ffa1ee0189dc89bdfdbafb164/out/vs/server/node/server.main.js:149:90589)
2023-02-03 09:54:13.663 [error] Untrusted: Signature: Untrusted
    at Pn.download (~/.vscode-server/bin/e2816fe719a4026ffa1ee0189dc89bdfdbafb164/out/vs/server/node/server.main.js:113:1922)
    at async U.h (~/.vscode-server/bin/e2816fe719a4026ffa1ee0189dc89bdfdbafb164/out/vs/server/node/server.main.js:149:90589)
```

Trying to download manually brings me to the [same page](https://marketplace.visualstudio.com/_apis/public/gallery/publishers/ms-toolsai/vsextensions/jupyter/2023.1.2000312134/vspackage?targetPlatform=linux-x64) as reported above. I am getting the same errors for the Jupyter extension.

I could successfully update the extensions locally.

- VSCode: 1.75.0
- OS: local openSUSE Tumbleweed / remote Red Hat Enterprise Linux 8.5 (Ootpa)

**Comment by zouquan741** [comment]
I have the same problem.

**Comment by inh3** [comment]
Same issue.  Downgraded VSCode to 1.74.3 to restore functionality.

* VS Code Version: 1.75.0
* OS Version:
  * Local: macOS Monterey 12.6.3
  * Remote: Amazon Linux 2 w/ Kernel 5.4

**Comment by eleanorjboyd** [comment]
Triaging this issue I am unsure if the initial post with the error message of `{"$id":"1","innerException":null,"message":"Version 2023.2.0 for extension ms-python.python has no support for targetPlatform ...` is the same as the error with the message `Untrusted: Signature`. Therefore all conversation on the `Untrusted: Signature` issue should be moved to this other issue: https://github.com/microsoft/vscode/issues/173327. Thanks

**Comment by sandy081** [comment]
**This issue is related to target platform and not related to sign verification.**

**Comment by notatallshaw-gts** [comment]
> Triaging this issue I am unsure if the initial post with the error message of `{"$id":"1","innerException":null,"message":"Version 2023.2.0 for extension ms-python.python has no support for targetPlatform ...` is the same as the error with the message `Untrusted: Signature`. Therefore all conversation on the `Untrusted: Signature` issue should be moved to this other issue: #173327. Thanks

Yes, I am initial poster, I also get the signature untrusted error. 

I _assumed_ the two errors had the same underlying cause, i.e. when VS Code made the webrequest it got the above error which does not have the signature of the extension, and then when VS Code prompts you to download it manually you can actually see the error.

This is why I posted the latter error and the former error. But if you are convinced they are two separate errors then it makes sense to track them separately. But be aware I got both of them, not just one of them, and it seems everyone else who has posted this seems to have said the same.

**Comment by sandy081** [comment]
Thanks for the info @notatallshaw-gts. It seems that the root cause is signature error for you too. Being said that the manual download shall work. Can you please share the link you are using to download the VSIX?

**Comment by zouquan741** [comment]
> Thanks for the info @notatallshaw-gts. It seems that the root cause is signature error for you too. Being said that the manual download shall work. Can you please share the link you are using to download the VSIX?

From the marketplace web page.
https://marketplace.visualstudio.com/items?itemName=ms-python.python

Version History -> 2023.3.10341119 -> Download
https://marketplace.visualstudio.com/_apis/public/gallery/publishers/ms-python/vsextensions/python/2023.3.10341119/vspackage

**Comment by notatallshaw-gts** [comment]
> Thanks for the info @notatallshaw-gts. It seems that the root cause is signature error for you too. Being said that the manual download shall work. Can you please share the link you are using to download the VSIX?

As per my original post the link that VS Code to manually download the extension is:  https://marketplace.visualstudio.com/_apis/public/gallery/publishers/ms-python/vsextensions/python/2023.2.0/vspackage?targetPlatform=linux-x64

Which gives this error:

```
{"$id":"1","innerException":null,"message":"Version 2023.2.0 for extension ms-python.python has no support for targetPlatform linux-x64","typeName":"Microsoft.VisualStudio.Services.Gallery.WebApi.ExtensionVersionHasNoSupportForRequestedTargetPlatformsException, Microsoft.VisualStudio.Services.Gallery.WebApi","typeKey":"ExtensionVersionHasNoSupportForRequestedTargetPlatformsException","errorCode":0,"eventId":3000}
```

**Comment by sandy081** [comment]
It seems VS Code is generating an invalid download link. Updating this issue for fixing the update link. For signing related, please refer to https://github.com/microsoft/vscode/issues/173327.

**Comment by connor4312** [comment]
> Get error message and get asked to download manually

I'm not sure how to get this, @sandy081 are there repro steps?

**Comment by sandy081** [comment]
To verify

- Open extensions view
- Browse for eslint extension (any non platform specific extension)
- Disable network connection
- Click on install, you shall see a prompt to Download Manually
- Enable network connection and click on that Download Manually button
- Make sure the VSIX is downloaded/
