### ISSUE TITLE
Python Interpreter unable to run the shell command for Mac

### ISSUE THREAD

**Issue by SiddharthGanguli** [microsoft/vscode#173279]
I am having a python interpreter of version v3.11.1. My issue is about the python interpreter is not able to run the shell command which it's supposed to be running in Mac versions. For example, The interpreter should write "python3 hello.py", but instead it runs the file as "python hello.py". This is the reason, I am not able to run the python file as expected. Please find the required  screenshot for duplication of the issue.

<img width="1205" alt="Screenshot 2023-02-03 at 4 12 40 PM" src="https://user-images.githubusercontent.com/120368671/216581306-f4c665f5-0b70-429c-a38f-a9fcecab871c.png">

Requesting to solve this issue as soon as possible. 

Thanks...

**Comment by roblourens** [comment]
Please file this on the python extension repo.
