### ISSUE TITLE
vscode 1.74 new shellscript syntax highlight has bug

### ISSUE THREAD

**Issue by ladyrick** [microsoft/vscode#173246]
Type: <b>Bug</b>

This bug is introduced in this new version of vscode.
Just use this script to reproduce the bug:
```shell
#!/bin/bash
function run_args() {
	args=("date" "--utc")
	"${args[@]}"
	echo 'use "quota" here'
}
run_args
```

![image](https://user-images.githubusercontent.com/10379994/216523720-afd6b85b-6ed6-4159-9fde-dd6b2502a10d.png)

VS Code version: Code 1.75.0 (e2816fe719a4026ffa1ee0189dc89bdfdbafb164, 2023-02-01T15:24:42.903Z)
OS version: Darwin x64 22.3.0
Modes:
Sandboxed: No
Connection to 'ssh-remote+10.128.66.167' could not be established
Remote OS version: Linux x64 5.15.0-52-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|1, 2, 2|
|Memory (System)|16.00GB (0.32GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

Connection to 'ssh-remote+10.128.66.167' could not be established

|Item|Value|
|---|---|
|Remote|SSH: vm|
|OS|Linux x64 5.15.0-52-generic|
|CPUs|Intel(R) Xeon(R) Platinum 8260 CPU @ 2.40GHz (32 x 2399)|
|Memory (System)|62.80GB (54.37GB free)|
|VM|0%|
</details><details><summary>Extensions (23)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-language-pack-zh-hans|MS-|1.75.2023020109
jupyter-keymap|ms-|1.0.0
remote-ssh|ms-|0.96.0
remote-explorer|ms-|0.2.0
material-icon-theme|PKi|4.23.1
vscode-eslint|dba|2.2.6
gitlens|eam|13.2.0
prettier-vscode|esb|9.10.4
code-runner|for|0.12.0
shell-format|fox|7.2.2
go|gol|0.37.1
vscode-language-pack-zh-hans|MS-|1.75.2023020109
isort|ms-|2022.8.0
python|ms-|2023.2.0
vscode-pylance|ms-|2023.2.10
jupyter|ms-|2023.1.2000312134
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.14
vscode-jupyter-cell-tags|ms-|0.1.6
vscode-jupyter-slideshow|ms-|0.1.5
material-icon-theme|PKi|4.23.1
datetime|rid|2.2.2
code-spell-checker|str|2.16.0

</details>

**Comment by alexr00** [comment]
Moved to the upstream repo: https://github.com/jeff-hykin/better-shell-syntax/issues/32

**Comment by mattmc3** [comment]
For anyone else running into this, the solution for now appears to be to install the Better Shell Syntax extension: https://marketplace.visualstudio.com/items?itemName=jeff-hykin.better-shellscript-syntax
