### ISSUE TITLE
Unit test failure: EditorService openEditor() - untyped, typed

### ISSUE THREAD

**Issue by deepak1556** [microsoft/vscode#173286]
Refs https://dev.azure.com/monacotools/Monaco/_build/results?buildId=202116&view=logs&j=55ac390b-ffb1-50ea-3650-525dd9a3fd80&t=3a692518-c3cf-5f6a-c273-72f71dc185fb

```
1) EditorService
       openEditor() - untyped, typed:

      
      + expected - actual


  Error: Timeout of 5000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
```

**Comment by bpasero** [comment]
Looks like a unhealthy CI machine to me. normally unit tests on macOS take 2 mins:

<img width="357" alt="image" src="https://user-images.githubusercontent.com/900690/216634202-fa993253-0e2a-439f-b4e9-970945ff198b.png">

Here I see almost 13 minutes

<img width="336" alt="image" src="https://user-images.githubusercontent.com/900690/216634253-46da102a-200d-4d64-b040-82c93d6032e4.png">
