### ISSUE TITLE
Background panel has weird characters behind text

### ISSUE THREAD

**Issue by ferreteleco** [microsoft/vscode#173296]
Type: <b>Bug</b>

Since today's upgrade, when there is no tabs opened, the normal background panel (sorry if that is not the name) has some weird symbols behind the normal Shortcuts description.

![image](https://user-images.githubusercontent.com/3154366/216606874-f02e02e6-3663-40f2-a63b-5a07179bfb73.png)

VS Code version: Code 1.75.0 (e2816fe719a4026ffa1ee0189dc89bdfdbafb164, 2023-02-01T15:29:17.766Z)
OS version: Linux x64 5.15.0-58-generic
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz (8 x 2782)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|18, 16, 10|
|Memory (System)|15.42GB (5.42GB free)|
|Process Argv|--unity-launch --crash-reporter-id 6a7732dc-b4a0-4b2d-ae5a-89e8e9ea37a5|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (169)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-openapi|42C|4.15.16
calculate|aca|2.1.0
vscode-javascript-repl|ach|0.7.3
matlab-formatter|Aff|2.10.41
cppincludeguard|aki|1.6.0
Bookmarks|ale|13.3.1
project-manager|ale|12.7.0
arepl|alm|2.0.4
cpp-helper|ami|0.3.1
snippets-geojson|ana|1.0.0
snippets-plotly|ana|1.0.5
ascii-tree-generator|apr|1.2.4
Doxygen|bbe|1.0.0
vscode-log-viewer|ber|0.12.2
vscode-doxygen-runner|bet|1.8.0
vscode-linux-binary-preview|bet|2.4.0
color-info|bie|0.7.2
docs-view|bie|0.0.11
github-markdown-preview|bie|0.3.0
lit-html|bie|1.11.1
markdown-checkbox|bie|0.4.0
markdown-emoji|bie|0.3.0
markdown-footnotes|bie|0.1.1
markdown-mermaid|bie|1.17.4
markdown-preview-github-styles|bie|1.0.1
markdown-shiki|bie|0.1.1
markdown-yaml-preamble|bie|0.1.0
better-toml|bun|0.3.2
simple-react-snippets|bur|1.2.7
path-intellisense|chr|2.8.4
gitignore|cod|0.9.0
vscode-test-explorer-status-bar|con|1.2.0
vscode-github-actions|csc|0.24.4
doxdocgen|csc|1.4.0
freemind|DaC|0.1.8
vscode-markdownlint|Dav|0.49.0
vscode-eslint|dba|2.2.6
quicktype-refresh|dog|1.0.2
githistory|don|0.6.19
python-environment-manager|don|1.0.4
es7-react-js-snippets|dsz|4.4.3
gitlens|eam|13.2.0
clipboard-manager|Edg|1.4.2
LogFileHighlighter|emi|2.16.0
json-tools|eri|1.0.2
vscode-diff|fab|1.4.2
vscode-todo-plus|fab|4.19.1
matlab|Gim|2.3.1
codespaces|Git|1.13.7
remotehub|Git|0.50.0
vscode-pull-request-github|Git|0.58.0
go|gol|0.37.1
cpp-reference|Guy|0.2.3
timing|Haa|2.7.2
vscode-nginx-conf-hint|han|0.3.0
vscode-systemd-support|han|1.0.1
CppSnippets|har|0.0.15
vscode-test-explorer|hbe|2.21.1
vscode-drawio|hed|1.6.6
asciidecorator|hel|0.3.0
vscode-sort|hen|0.2.5
output-colorizer|IBM|0.1.2
StrSplt|Inn|1.0.0
latex-workshop|Jam|9.6.1
vscode-edit-csv|jan|0.7.2
better-cpp-syntax|jef|1.17.2
snipped|jef|1.3.0
Angular2|joh|13.0.0
changelog-and-markdown-snippets|jos|1.2.1
cmake-language-support-vscode|jos|0.0.9
language-julia|jul|1.38.2
vscode-smart-split-into-lines|Jul|0.0.1
octaveexecution|Luc|0.7.3
vscode-swissknife|lui|1.7.0
bash-ide-vscode|mad|1.33.0
vscode-catch2-test-adapter|mat|4.3.10
vscode-cookierunner|Mat|1.0.0
caddyfile-support|mat|0.2.3
rainbow-csv|mec|3.5.0
feather-vscode|mel|1.0.1
git-graph|mhu|1.30.0
dotenv|mik|1.0.1
mongodb-vscode|mon|0.10.0
vscode-docker|ms-|1.23.3
vscode-dotnet-runtime|ms-|1.6.0
black-formatter|ms-|2022.6.0
gather|ms-|2022.3.2
isort|ms-|2023.9.10341117
python|ms-|2023.2.0
vscode-pylance|ms-|2023.2.10
jupyter|ms-|2023.1.2000312134
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.14
vscode-jupyter-cell-tags|ms-|0.1.6
vscode-jupyter-powertoys|ms-|0.0.6
vscode-jupyter-slideshow|ms-|0.1.5
remote-containers|ms-|0.275.0
remote-ssh|ms-|0.96.0
remote-ssh-edit|ms-|0.84.0
remote-wsl|ms-|0.75.1
azure-repos|ms-|0.26.0
cmake-tools|ms-|1.13.45
cpptools|ms-|1.13.9
hexeditor|ms-|1.9.11
remote-explorer|ms-|0.2.0
remote-repositories|ms-|0.28.0
test-adapter-converter|ms-|0.1.6
vscode-react-native|msj|1.10.0
vscode-sanddance|msr|4.0.4
sqltools|mtx|0.27.1
sqltools-driver-mysql|mtx|0.5.1
sqltools-driver-pg|mtx|0.5.1
sqltools-driver-sqlite|mtx|0.5.0
vs-sequential-number|nep|1.1.0
gremlins|nho|0.26.0
autodocstring|njp|0.6.1
incrementor|nms|1.0.3
vs-qalc|nor|0.1.11
fix-json|oli|0.1.2
docthis|oou|0.8.2
OPEN-RPC|OPE|1.2.7
vscode-print|pdc|0.10.20
markdown-markmap|pho|1.4.6
material-icon-theme|PKi|4.23.1
platformio-ide|pla|3.0.0
psi-header|psi|1.21.0
text-power-tools|qcz|1.38.0
sqlite-viewer|qwt|0.1.5
geo-data-viewer|Ran|2.6.0
vscode-thunder-client|ran|2.3.4
fabric8-analytics|red|0.3.6
vscode-xml|red|0.24.0
vscode-yaml|red|1.11.0
bash-debug|rog|0.3.9
color-manager|roy|0.7.5
vsmqtt|rpd|1.4.7
rust-analyzer|rus|0.3.1386
codeui|rya|1.1.0
partial-diff|ryu|1.4.3
glassit|s-n|0.2.5
jinjahtml|sam|0.20.0
crates|ser|0.5.10
vscode-fileutils|sle|3.10.0
sonarlint-vscode|Son|3.14.0
vscode-taskexplorer|spm|2.13.2
code-spell-checker|str|2.16.0
code-spell-checker-spanish|str|2.1.5
geojson-io-for-vscode|swa|0.5.2
vscode-rust-test-adapter|Swe|0.11.0
teroshdl|ter|2.0.8
vscode-fontawesome-gallery|tom|0.0.7
octave-formatter|tus|2.9.1
cmake|twx|0.0.17
luna-paint|Tyr|0.16.0
windows-terminal|Tyr|0.7.0
tiff-preview|uco|0.0.1
errorlens|use|3.6.0
vscode-lldb|vad|1.8.1
intellicode-api-usage-examples|Vis|0.2.7
vscodeintellicode|Vis|1.2.30
vscodeintellicode-completions|Vis|1.0.20
vscode-conventional-commits|viv|1.25.0
vscode-icons|vsc|12.2.0
codetour|vsl|0.0.58
vscode-surround|yat|1.5.0
licenser|ymo|1.9.0
open-in-external-app|YuT|0.9.1
markdown-pdf|yza|1.4.4
markdown-all-in-one|yzh|3.5.0

(3 theme extensions excluded)

</details>

**Comment by deepak1556** [comment]
Are you only seeing the issue for the empty window or does it happen in editors as well ?

**Comment by ferreteleco** [comment]
Only for the empty window, at least for now.

**Comment by deepak1556** [comment]
Merging to https://github.com/microsoft/vscode/issues/171367
