### ISSUE TITLE
Refresh rate during mouse over on menu

### ISSUE THREAD

**Issue by MythicAngel** [Microsoft/vscode#17329]
- VSCode Version: 1.8.0
- OS Version: Windows 8 (64-bit)

**Steps to Reproduce:**
I just upgraded to 1.8.0 and the floating effect on menu (i.e. refresh rate) is very annoying to my eyes. To repeat, follow these steps:

1. Click on Help menu
2. Move mouse to left side menus (e.g. File/Edit) very fast.
3. Notice the refresh rate and how it appear to your eye.

**Comment by bpasero** [comment]
@MythicAngel can you clarify what you mean with "refresh rate"?

**Comment by MythicAngel** [comment]
In outlook, switching over menus, destination menu appears lets say after 500 milisecond. So, there is a smoothing effect.
In VSCode, it appears after 20 second, so the effect is gone and the flash of UI element change is problematic.

**Comment by bpasero** [comment]
There are no plans currently to change this.
