### ISSUE TITLE
Workspace auto shell command executed to change node version

### ISSUE THREAD

**Issue by maxrks** [microsoft/vscode#173237]
There be many node versions on the computer, everytime vscode workspace open, I have to change the node version by certain cmd like `nvm use 16.17.0`, could be there a setting or `shell script automation` in `settings.json` of `.vscode` folder under the workspace? let the shell open from command center or context menu of folder and a script executed to change the node version. node. python, go, rust etc.

A setting in settings.json could be: 
**shellOpenScript: nvm use 16.17.0**

**Comment by meganrogge** [comment]
I don't think we want to / can change your nvm version for you. I think you can configure that globally though

**Comment by maxrks** [comment]
There were serveral projects progressing with different node versions, though a global version can be set by `nvm`, I had to remember which version of node used when a project open and try `nvm use xx.xx.xx` in the console, or might forget `node_modules`  was installed in which node version after `npm start` executed but errors caught.

**Comment by maxrks** [comment]
Good solutions on `.nvmrc` were found.

According to ` link 1.`  append zsh script  at first.

`vim ~/.zshrc` and put the code into `~/.zshrc`
```
# place this after nvm initialization!
autoload -U add-zsh-hook
load-nvmrc() {
  local node_version="$(nvm version)"
  local nvmrc_path="$(nvm_find_nvmrc)"

  if [ -n "$nvmrc_path" ]; then
    local nvmrc_node_version=$(nvm version "$(cat "${nvmrc_path}")")

    if [ "$nvmrc_node_version" = "N/A" ]; then
      nvm install
    elif [ "$nvmrc_node_version" != "$node_version" ]; then
      nvm use
    fi
  elif [ "$node_version" != "$(nvm version default)" ]; then
    echo "Reverting to nvm default version"
    nvm use default
  fi
}
add-zsh-hook chpwd load-nvmrc
load-nvmrc
```

and `source ~/.zshrc` 

then exec `touch .nvmrc && node -v .nvmrc` under the project root folder.

when zsh `open` in vscode or other, it shall change the node version on `.nvmrc` automatically.

`link 2.` works too.

1. https://stackoverflow.com/questions/57110542/how-to-write-a-nvmrc-file-which-automatically-change-node-version

2. https://stackoverflow.com/questions/49020714/how-to-automatically-activate-specific-node-version-when-vs-code-integrated-term
