### ISSUE TITLE
Terminals moved from an editor to the panel don't update "terminalEditorFocus"

### ISSUE THREAD

**Issue by akbyrd** [microsoft/vscode#173240]
Type: <b>Bug</b>

These context keys are set when a terminal editor is open and focused and the panel is not open
```
activeEditor: "terminalEditor"
activePanel: ""
focusedView: ""
panelFocus: false
terminalEditorActive: true
terminalEditorFocus: true
terminalFocus: true
```

And these context keys are set when the terminal view in the panel is open a focused and no editor is present
```
activeEditor: null
activePanel: "terminal"
focusedView: "terminal"
panelFocus: true
terminalEditorActive: false
terminalEditorFocus: false
terminalFocus: true
```

And these are the context keys after a terminal editor is moved to the panel
```
activeEditor: null
activePanel: "terminal"
focusedView: "terminal"
panelFocus: true
terminalEditorActive: false
terminalEditorFocus: true    <-- Misbehaving
terminalFocus: true
```

In this last case notice that all the context keys match the expected values for a normal terminal in the panel except terminalEditorFocus. This ends up stuck to true. If you create a new terminal tab in the panel terminalEditorFocus will be set to false as expected. Returning to the terminal that was move will again set terminalEditorFocus to true.

Steps to repro:
* Create a terminal editor (workbench.action.createTerminalEditor)
* Move the terminal editor to the panel (workbench.action.terminal.moveToTerminalPanel)
* Inspect context keys (workbench.action.inspectContextKeys)
* Notice terminalEditorFocus is true

VS Code version: Code - Insiders 1.75.0-insider (e2816fe719a4026ffa1ee0189dc89bdfdbafb164, 2023-02-01T15:16:18.248Z)
OS version: Windows_NT x64 10.0.19045
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 9 5950X 16-Core Processor             (32 x 3400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.92GB (20.48GB free)|
|Process Argv|--crash-reporter-id 22cf4e37-a96e-4ad9-82f0-8715f8e2bf6e|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30422396
pythontb:30258533
pythonptprofiler:30281269
vsdfh931cf:30280410
vshan820:30294714
pythondataviewer:30285072
vscod805cf:30301675
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30404738
cppdebug:30492333
vsclangdf:30492506
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30618038
pylantcb52:30590116
pyindex848:30611229
nodejswelcome1:30587009
pyind779:30611226
pythonsymbol12:30651887
2i9eh265:30646982
showlangstatbar:30657381

```

</details>

**Comment by akbyrd** [comment]
Related: terminalEditorActive is not always set when a terminal editor is active.

Context keys when a terminal editor is open and the terminal view of the panel is focused:
```
activeEditor: "terminalEditor"
activePanel: "terminal"
panelFocus: true
terminalEditorActive: false
terminalEditorFocus: false
terminalFocus: true
```

We end up in a weird state where the activeEditor is "terminalEditor" yet terminalEditorActive is false. My understanding is the "active" object is the thing that would be focused if that part of the workbench were focused.

Looking at context keys when the extensions view is focus seems to back this up.
```
activeEditor: "terminalEditor"
activePanel: "terminal"
panelFocus: false
terminalEditorActive: true
terminalEditorFocus: false
terminalFocus: null
```

**Comment by akbyrd** [comment]
The first half of this was fixed, but the second half was not. A terminal in the panel still stomps `terminalEditorActive` when a terminal is also in an editor.

Request to re-open this issue.

**Comment by akbyrd** [comment]
The first half of this was fixed, but the second half was not. A terminal in the panel still stomps terminalEditorActive when a terminal is also in an editor.

@Tyriar Request to re-open this issue.

**Comment by Tyriar** [comment]
@akbyrd I did this and `termianlEditorActive` is false and activeEditor is `workbench.editors.files.textFileEditor` after moving it?

![image](https://github.com/microsoft/vscode/assets/2193314/40cafdd3-b914-40cf-80ad-b58932766572)

Can you clarify what the second half is?

**Comment by akbyrd** [comment]
Based on `workbench.editors.files.textFileEditor` I assume you're testing with a panel editor and a regular text file editor. The scenario I'm looking at is a terminal in both an editor and the panel.

![image](https://github.com/microsoft/vscode/assets/484784/2007836b-078e-438d-85c2-2113aa296ec5)

In this scenario `terminalEditorActive` changes based on which terminal is focused, but it should always be true.

When the terminal editor is focused I see these context keys
```
// From the terminal panel
"panelFocus": false,
"focusedView": "",

// From the terminal editor
"activeEditor": "terminalEditor",
"terminalEditorActive": true,
"terminalEditorFocus": true,
```

When the terminal panel is focused I see these context keys
```
// From the terminal panel
"panelFocus": true,
"focusedView": "terminal",

// From the terminal editor
"activeEditor": "terminalEditor",
"terminalEditorActive": false, // Should be true, but focusing the panel has overwritten it
"terminalEditorFocus": false,
```

It's not technically related to _moving_ the terminal from an editor to the panel, but since it seemed so closely related that it didn't warrant a separate issue. I can open one if that makes more sense.

**Comment by Tyriar** [comment]
Ah I see, yes `terminalEditorActive` should be true in that case. That would be great if you could open a new issue for clarity

**Comment by akbyrd** [comment]
Done: https://github.com/microsoft/vscode/issues/182979
