### ISSUE TITLE
Git doesn't recognise repositories in workspace

### ISSUE THREAD

**Issue by parsley72** [microsoft/vscode#173206]
Type: <b>Bug</b>

This was working fine until I upgraded to 1.75.0. When I open the workspace and view the Source Control tab I get "The workspace currently open doesn't have any folders containing git repositories".

VS Code version: Code 1.75.0 (e2816fe719a4026ffa1ee0189dc89bdfdbafb164, 2023-02-01T15:29:17.766Z)
OS version: Linux x64 5.15.0-58-generic
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 3464)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|1, 1, 2|
|Memory (System)|30.82GB (17.87GB free)|
|Process Argv|--unity-launch --crash-reporter-id 22a8c568-a07b-4695-aea0-fb576273baf5|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (23)</summary>

Extension|Author (truncated)|Version
---|---|---
systemd-unit-file|coo|1.0.6
doxdocgen|csc|1.4.0
gitlens|eam|13.2.0
bitbake|Eug|1.1.2
shell-format|fox|7.2.2
go|gol|0.37.1
todo-tree|Gru|0.0.223
better-cpp-syntax|jef|1.17.2
isort|ms-|2022.8.0
python|ms-|2023.2.0
vscode-pylance|ms-|2023.2.10
jupyter|ms-|2023.1.2000312134
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.14
vscode-jupyter-cell-tags|ms-|0.1.6
vscode-jupyter-slideshow|ms-|0.1.5
cmake-tools|ms-|1.13.45
cpptools|ms-|1.13.9
cpptools-extension-pack|ms-|1.3.0
vscode-xml|red|0.24.0
shellcheck|tim|0.29.3
cmake|twx|0.0.17
clang-format|xav|1.9.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
azure-dev_surveyonecf:30548226
pyindex848cf:30577861
nodejswelcome1cf:30587006
3biah626:30602489
89544117:30613380
pythonsymbol12:30657548
vscup:30628656

```

</details>

**Comment by laralimabilly** [comment]
I had the same issue. 1.75 is broken. I've lost my color theme and all my Git repositories. The only way around was to install 1.74.3. My color theme still broken though.

**Comment by MattBussing** [comment]
I'm also having this issue.

**Comment by vjekob** [comment]
The same here. When I open from a workspace file, VS Code 1.75 doesn't recognize the git repository. When I open the folder directly, then it does. It used to work fine until 1.75.

**Comment by mityaua** [comment]
Git works only your project's root directory. When you open the subfolder, VSC and Git can't understand that those files were already indexed.

**Comment by lszomoru** [comment]
Apologies for the inconvenience. VS Code `1.75` includes some changes related to repository discovery when the git repository is outside the workspace folder. Are you still able to reproduce the problem if you set `git.openRepositoryInParentFolders` to `always` and reload the window?

**Comment by parsley72** [comment]
> Are you still able to reproduce the problem if you set `git.openRepositoryInParentFolders` to `always` and reload the window?
I don't even need to reload the window - I change the setting and it works.

**Comment by lszomoru** [comment]
I believe I was able to track down [the root cause](https://github.com/microsoft/vscode/issues/173226#issuecomment-1416394268). The fix should be included in Monday's VS Code Insiders release.

**Comment by lszomoru** [comment]
Today's Insiders release contains the fix for this issue. 
I would really appreciate if you would try it out and confirm that it resolves this issue. Thank you!

```
Version: 1.76.0-insider (Universal)
Commit: c9e3ef865539061b5602c6b9ac6030332aa1ce70
Date: 2023-02-06T05:24:10.821Z
Electron: 19.1.9
Chromium: 102.0.5005.194
Node.js: 16.14.2
V8: 10.2.154.23-electron.0
OS: Darwin arm64 22.3.0
Sandboxed: Yes
```

**Comment by parsley72** [comment]
Working fine now.

**Comment by vjekob** [comment]
Yes, a couple of latest insiders builds work fine with this.
