### ISSUE TITLE
problem with tasks.json and typescript compiler under Ubuntu 14.04

### ISSUE THREAD

**Issue by lucianFXD** [Microsoft/vscode#1732]
I have typescript installed globally but after editing tasks.json  and  try to run tsc command from vscode it doesn't appear in the list.If I run tsc commands from the terminal it works.

**Comment by dbaeumer** [comment]
@lucianFXD this works for me using release 0.10.6. Attached a screen shot showing the command in the 
![capture](https://cloud.githubusercontent.com/assets/1931590/12086225/3f265268-b2c8-11e5-9ba6-035e95c4b8ae.png)
command palette. Can you provide more info about what is not working in your case.

**Comment by lucianFXD** [comment]
Here is what I get in my case:
![vs_code](https://cloud.githubusercontent.com/assets/16511061/12100980/0d4dcac8-b33b-11e5-8d6d-20550c76129a.png)

**Comment by dbaeumer** [comment]
@lucianFXD you need now select Tasks: Run Task. This should give you the same picture I see.

**Comment by lucianFXD** [comment]
Yes now it's working.Thank you !

**Comment by dbaeumer** [comment]
Closing.
