### ISSUE TITLE
On Ubuntu 22.04 Wayland session, assigning Focus Terminal to "Ctrl + $" assigns to "Ctrl + Y" instead

### ISSUE THREAD

**Issue by why-not-try-calmer** [microsoft/vscode#173271]
Type: <b>Bug</b>

On Ubuntu 22.04 Wayland session, assigning Focus Terminal to "Ctrl + $" assigns to "Ctrl + Y" instead. 

1. Assign 'Focus Terminal' to "Ctrl + $". Press "Enter".
2. Observe that 'Focus Terminal' has been in fact assigned to "Ctrl + Y".

VS Code version: Code 1.75.0 (e2816fe719a4026ffa1ee0189dc89bdfdbafb164, 2023-02-01T15:29:17.766Z)
OS version: Linux x64 6.0.12-76060006-generic
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz (8 x 3262)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|2, 1, 1|
|Memory (System)|15.53GB (9.03GB free)|
|Process Argv|--ozone-platform-hint=auto|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|pop-wayland|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|pop-wayland|
|XDG_SESSION_TYPE|wayland|
</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
githistory|don|0.6.19
vscode-language-pack-fr|MS-|1.75.2023020109
isort|ms-|2022.8.0
python|ms-|2023.2.0
vscode-pylance|ms-|2023.2.10
vscode-yaml|red|1.11.0
material-theme|zhu|3.15.6

(12 theme extensions excluded)

</details>

**Comment by Domkeykong** [comment]
This seems to be a regression from: 1.74.3-1673284829
Another combination i noticed is: ctrl+# (ctrl+[Backslash]) which is parsed correctly but then ctrl+Y is assigned instead.

**Comment by Domkeykong** [comment]
this seems to be related, if not the same as #173280

**Comment by Domkeykong** [comment]
I did a quick bisect and it seems the error was introduced in: 275bc8456ea520659a6878b8e7d111d5e3bd2508

**Comment by CreatorSiSo** [comment]
I have the same issue when assigning "ctrl + #" to the "toggle line comment" action.
(german keyboard layout)

**Comment by alexdima** [comment]
Let's track in #173325

**Comment by why-not-try-calmer** [comment]
Thanks for the fix!
