### ISSUE TITLE
runSelectedText jumping to terminal instead of staying in editor

### ISSUE THREAD

**Issue by davidcrossey** [microsoft/vscode#173247]
Type: <b>Bug</b>

This was working in the previous version, now when running lines of code from the editor with 

"key": "ctrl+enter",
"command": "workbench.action.terminal.runSelectedText"

The cursor automatically snaps to the terminal which is extremely annoying. Please fix this ASAP.

VS Code version: Code 1.75.0 (e2816fe719a4026ffa1ee0189dc89bdfdbafb164, 2023-02-01T15:23:45.584Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: No
Remote OS version: Linux x64 5.15.0-1031-azure

<details><summary>Extensions (25)</summary>

Extension|Author (truncated)|Version
---|---|---
better-cpp-syntax|jef|1.17.2
jupyter-keymap|ms-|1.0.0
vscode-ai-remote|ms-|0.22.0
remote-containers|ms-|0.275.0
remote-ssh|ms-|0.96.0
remote-ssh-edit|ms-|0.84.0
remote-wsl|ms-|0.75.1
vscode-remote-extensionpack|ms-|0.23.0
remote-explorer|ms-|0.2.0
material-icon-theme|PKi|4.23.1
vscode-kdb-q-forked|Ale|1.2.2
unique-lines|bib|1.0.0
gitlens|eam|13.2.0
json-tools|eri|1.0.2
isort|ms-|2022.8.0
python|ms-|2023.2.0
vscode-pylance|ms-|2023.2.10
jupyter|ms-|2023.1.2000312134
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.14
vscode-ai|ms-|0.24.0
vscode-jupyter-cell-tags|ms-|0.1.6
vscode-jupyter-slideshow|ms-|0.1.5
azure-account|ms-|0.11.3
code-spell-checker|str|2.16.0

(2 theme extensions excluded)

</details>

**Comment by davidcrossey** [comment]
Temporary work around is to use `CTRL+1`, however that's not really effective for long periods of time.

**Comment by meganrogge** [comment]
in order to run text in the terminal, we need to focus it. this is working as designed

**Comment by davidcrossey** [comment]
@meganrogge this wasn't the case on the previous version. You could execute lines of code from the editor with e.g. ctrl+enter without shifting focus to the terminal.

Please advise further.

**Comment by anderswe** [comment]
@davidcrossey ran into the same issue as you. Suspect you've already done this, but a quick fix is to add a new keybinding in ```keybindings.json``` with the multi-command extension installed:

```
{
        "key": "cmd+enter",                           // or ctrl+enter
        "command": "extension.multiCommand.execute",
        "args": {
          "sequence": [
            "workbench.action.terminal.runSelectedText", // run line
            "workbench.action.focusActiveEditorGroup", // shift focus back to editor
            "cursorDown" // jump to next line so you can spam cmd+enter
          ]
        },
        "when": "editorTextFocus"  
}
```

**Comment by davidcrossey** [comment]
> @davidcrossey ran into the same issue as you. Suspect you've already done this, but a quick fix is to add a new keybinding in `keybindings.json` with the multi-command extension installed:
> 
> ```
> {
>         "key": "cmd+enter",                           // or ctrl+enter
>         "command": "extension.multiCommand.execute",
>         "args": {
>           "sequence": [
>             "workbench.action.terminal.runSelectedText", // run line
>             "workbench.action.focusActiveEditorGroup", // shift focus back to editor
>             "cursorDown" // jump to next line so you can spam cmd+enter
>           ]
>         },
>         "when": "editorTextFocus"  
> }
> ```

Thank you so much @anderswe for this workaround!

**Comment by Tyriar** [comment]
This was caused by 305de596d216fb925e3cc298c0b67ad99ad0b6c2 where it changed from just revealing to focusing

**Comment by davidcrossey** [comment]
> This was caused by [305de59](https://github.com/microsoft/vscode/commit/305de596d216fb925e3cc298c0b67ad99ad0b6c2) where it changed from just revealing to focusing

Thanks @Tyriar !

**Comment by Tyriar** [comment]
@robinpecha it will come in 1.76 which should get releases in about 3 weeks time.
