### ISSUE TITLE
find match highlight border color

### ISSUE THREAD

**Issue by yoshioka-naoki** [microsoft/vscode#173262]
when i typed on find widget and hit enter, white color dotted border appears around matched words.
I want to change color of this with  "workbench.colorCustomizations".

- today i updated vscode to version 1.75. (everyday, I apply update if available). it haven't happened by yesterday.
- my setting is "workbench.colorTheme": "Default High Contrast"

![image](https://user-images.githubusercontent.com/55611674/216549477-d61758ae-05a4-492c-bd26-8e5ca24a72c8.png)

**Comment by yoshioka-naoki** [comment]
I uncommented settings above (e.g. editor .findMatchHighlightBorder), but nothing changed

**Comment by yoshioka-naoki** [comment]
actually, I want to make dotted border transparent or erase, rather than changing color of it

**Comment by soulshined** [comment]
I would agree this should be an opt-in. Was there a reason disseminated to users why this would be coerced? If it's a good reason I'd understand but for the worlds most customizable editor it feels strange for this not to have a configuration or opt-in. 
 
My issue is not that it occurs on find and replace or find matching symobls, you could sell me on that if it stays within the bounds of the current symbol. My issue is that it additionally shows the border on *unfocused* and ***not active*** editors. This has made me think I'm editing a file my cursor is not actually in on multiple occasions; like when I Alt + Tab applications.   

For example, just simply focusing on editor group one (picture left) and then focusing on editor group 2 (picture right) the border populates. It's very misleading and confusing on what the purpose of it is in my opinion.

![Capture](https://user-images.githubusercontent.com/11242654/219511119-832beb00-639a-4e86-b800-efb5eef826b4.PNG)

 
 Given that I would second the request to have a configuration or way to disable it.

**Comment by alexdima** [comment]
This can be turned off via `"editor.occurrencesHighlight": false`. The root cause is an incorrect CSS rule.

**Comment by soulshined** [comment]
> This can be turned off via `"editor.occurrencesHighlight": false`. The root cause is an incorrect CSS rule.

@alexdima Thanks so much, I looked for a setting for hours! Looks like I tried everyone but that one!!
