### ISSUE TITLE
[folding] Collapsed block should expand if match found with addSelectionToNextFindMatch

### ISSUE THREAD

**Issue by jansensan** [Microsoft/vscode#17326]
- VSCode Version: Version 1.8.0 (1.8.0)
- OS Version: 10.10.5 (14F1912)

Steps to Reproduce:

1. Have a Javascript file (although I guess it applies to all types) with a few methods and enough code  to exceed screen/viewport height.
2. In these methods, have a common variable name (`index` for example)
3. Collapse methods that are not the ones in use.
4. Use the keyboard shortcut associated with `editor.action.addSelectionToNextFindMatch` (`cmd+d` by default on Mac)
5. See the editor struggle (jumping screen) when matching a value in a collapsed block.

Expected behavior:
Collapsed block should expand to show selection, rather than remaining collapsed and have the cursor jump randomly in file.

**Comment by aeschli** [comment]
![image](https://cloud.githubusercontent.com/assets/6461412/22441783/1c4771ae-e739-11e6-89d9-fe69aab5aa14.png)

**Comment by aeschli** [comment]
![jan-30-2017 22-12-25](https://cloud.githubusercontent.com/assets/6461412/22441816/41118bc8-e739-11e6-8ab6-4a4cdf90812d.gif)

Cmd+d expands a collapsed region to highlight the next match. This works for me.
Do you have more information on what's different in your scenario?

**Comment by jansensan** [comment]
@aeschli Your GIF seems to use the search overlay, whereas CMD-D doesn't. Either, at the time I reported the issue it was not behaving as expected, and now it is. Maybe an update resolved it? Thanks for following up.
