### ISSUE TITLE
terminal (pwsh) cannot output `ANSI` color

### ISSUE THREAD

**Issue by mozhuanzuojing** [microsoft/vscode#173241]
Does this issue occur when all extensions are disabled?: No

Version: 1.75.0 (system setup)
OS: Windows_NT x64 10.0.22621
Sandboxed: No

Steps to Reproduce:

1. install PowerShell 7.3.2
2. write below
```java
public class ANSIColorTest {
    public static void main(String[] args) {
        // SGR color
        System.out.println(" \u001b[38;2;255;255;0m  should output yellow  \u001b[0m ");
    }
}
```
3. execute `main`

#### expect
output `yellow` font

#### actual
output `white` font

#### screen

![image](https://user-images.githubusercontent.com/63572041/216518641-ddbf71cf-6b3e-4f13-a0a3-ca82f6df3000.png)

#### additional
refer https://notes.burke.libbey.me/ansi-escape-codes/#SGR

**Comment by Tyriar** [comment]
This works in plain pwsh so it's some problem between pwsh and java:

<img width="526" alt="image" src="https://user-images.githubusercontent.com/2193314/216707407-a8d5f536-500d-4897-b73c-dcc4bbccd55b.png">
