### ISSUE TITLE
Filter and sort on variable list

### ISSUE THREAD

**Issue by APerricone** [microsoft/vscode#173270]
Hello, for my extension I have a feature request for the variables view: sort and filter https://github.com/APerricone/harbourCodeExtension/issues/89. I see there is already a filter:
https://github.com/microsoft/vscode/issues/13201#issuecomment-539433752 but it does not work on my extension, I need to activate something? 

After this would be fantastic If I can activate or create a button on variables list to select if show the variables on declaration order or in alphabetical order, but I think it is not possible at this time

**Comment by roblourens** [comment]
This is supported, it just works a little differently now- you will have to focus the variables view, press cmd+F or ctrl+F, and type in the widget that appears. Let me know if it doesn't work for you

**Comment by APerricone** [comment]
Hi, Yes the CTRL+F works. Any hint about the sorting? I would like add the possibility to select between 2 kind of sort

**Comment by roblourens** [comment]
Just off the top of my head, I believe vscode shows variables in the order in which they are provided by the debug adapter, is that not the case?

**Comment by APerricone** [comment]
Sure, VSCode shows the variables in the same order they are provided by the adapter, my problem is that I want allow the user to decide if get the variables in alphabetical order or in declaration order, better if he can switch during the debugging.

**Comment by roblourens** [comment]
The best way to do that for now would be a setting or button that is implemented by your extension. No plans to implement have vscode change the sorting currently.
