### ISSUE TITLE
Support for hiding suggested commands in the startup page

### ISSUE THREAD

**Issue by fabiospampinato** [microsoft/vscode#173295]
I see the following in my startup page:

<img width="722" alt="Screen Shot 2023-02-03 at 12 38 37" src="https://user-images.githubusercontent.com/1812093/216605678-f52d63a7-ac27-4002-bfd4-91d2f4d06e08.png">

And I find the suggested commands quite ugly, the ruin the minimalism of the interface and force the logo to be off-center.

It's probably something that nobody cares about, but I'd really like a setting for hiding those suggested commands and centering the logo.

**Comment by bhavyaus** [comment]
You can turn disable the watermark by setting
`"workbench.tips.enabled": false`

Thank you.

**Comment by fabiospampinato** [comment]
It looks so much better now 😍

Thank you!
