### ISSUE TITLE
Open folder broken from a new window selected

### ISSUE THREAD

**Issue by rajinder-yadav** [Microsoft/vscode#17322]
Open code, from the File menu select `New Window`.
Click on open folder, select a folder, click open, nothing happen!

![screen shot 2016-12-15 at 11 43 23 am](https://cloud.githubusercontent.com/assets/439226/21233039/c45b9624-c2bb-11e6-89e7-a8771b50bada.png)

- VSCode Version: Code 1.8.0 (38746938a4ab94f2f57d9e1309c51fd6fb37553d, 2016-12-13T17:38:28.425Z)
- OS Version: Darwin x64 16.1.0
- Extensions:

|Extension|Author|Version|
|---|---|---|
|vscode-markdownlint|DavidAnson|0.6.0|
|EditorConfig|EditorConfig|0.3.4|
|jslint|ajhyndman|1.2.1|
|jshint|dbaeumer|0.10.15|
|vscode-eslint|dbaeumer|1.2.1|
|tslint|eg2|0.7.1|
|cpptools|ms-vscode|0.9.3|
|debugger-for-chrome|msjsdiag|2.4.0|
|Spell|seanmcbreen|0.9.1|
|vim|vscodevim|0.4.9|

---

Steps to Reproduce:

1.
2.

**Comment by kieferrm** [comment]
@rajinder-yadav this works without a problem for me. What happens on `Open` from the command palette? Anything in console when you open dev tool: Help>Toggle Developer Tools

**Comment by rajinder-yadav** [comment]
@kieferrm  Did you test this on MacOS? On Linux it works for me too.

On Mac I get the open dialog, I select the folder, click on the open(ok) button. The dialog closes, yet I keep seeing that image I post earlier, I am unable to open a folder.

I'll report back tomorrow when I get into the office about trying what you suggested.

**Comment by rajinder-yadav** [comment]
I closed vscode from the macos taskbar and opened a fresh instance, I am no longer seeing this problem. Closing since I can't repro.
