### ISSUE TITLE
Links don't have the right CSS cursor value in feature contributions

### ISSUE THREAD

**Issue by usernamehw** [microsoft/vscode#173208]
1. Have an extension with `markdownDescription` with a link
2. When hovering over it - cursor is not `pointer`

![link_cursor](https://user-images.githubusercontent.com/9638156/216452198-228c7653-1ee4-4577-a686-711bede5b9eb.png)

**Comment by ronelgazar** [comment]
Hi, I would love to work on this. Can you please assign it to me?

**Comment by PiyushNegi1703** [comment]
I would like to work on this issue and would try to fix it.

**Comment by Souvik2376** [comment]
I very much like to work on this issue

**Comment by maski07** [comment]
@usernamehw 
I am unable to verify this issue. 
May I know which operating system you are using?

**Comment by usernamehw** [comment]
Windows 10 / Web.

**Comment by Souvik2376** [comment]
Windows 10

**Comment by tripathics** [comment]
I would like to work on this issue

**Comment by usernamehw** [comment]
Fixed in **1.76.0**?

**Comment by Aperezpe** [comment]
Unable to replicate the issue in Windows 11. Has this issue been fixed?
