### ISSUE TITLE
Nested json settings

### ISSUE THREAD

**Issue by cojua8** [microsoft/vscode#173303]
I'd like to have a more organized settings json file, and I think one way to achieve this is to nest settings with same root. Right now, settings files are like this:
```json
{
    "editor.mouseWheelZoom": true,
    "editor.minimap.enabled": false,
    "editor.suggest.snippetsPreventQuickSuggestions": false,
    "editor.guides.bracketPairs": "active",
    "editor.showFoldingControls": "always",
}
```

And I think it would be cleaner to have something like this:
```json
{
    "editor": {
        "mouseWheelZoom": true,
        "minimap.enabled": false,
        "suggest.snippetsPreventQuickSuggestions": false,
        "guides.bracketPairs": "active",
        "showFoldingControls": "always",
    }
}
```

This is specially usefull when you have a highly populated settings file, with many extensions and so.

Thank you!

**Comment by Dpschu2** [comment]
This is much needed. Please reopen feature request!

**Comment by Dillxn** [comment]
Agreed. I would love to have this.

**Comment by Zosoled** [comment]
Please reconsider this feature request. This would make it much easier to manage `settings.json`, especially when there are still configurations which require manual editing, e.g. `editor.rulers`.

**Comment by joshwarren** [comment]
I agree this would be a really helpful feature. The settings file is difficult to maintain at the moment, especially when you have a particularly large tech stack (and therefore quite a lot of settings that apply differently in different contexts).

**Comment by detuur** [comment]
The one thing I can suggest for people who are in this situation like me is to use the "JSON: Sort document" command. This will at least group the different settings already. Additionally, vscode's JSON variant permits for comments (`jsonc` language tag). Indent things a bit sensibly and you can make things significantly more readable.

@sandy081 would you guys be open to a community PR for this feature?
