### ISSUE TITLE
January 2023 Recovery 1 Endgame

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#173317]
- [x] Create a milestone `January 2023 Recovery 1` **@roblourens**
- [x] Bump the version number **@roblourens**
- [x] [🔖candidate issues](https://github.com/issues?q=is%3Aissue%20label%3Acandidate%20repo%3Amicrosoft%2Fvscode%20repo%3Amicrosoft%2Fvscode-internalbacklog%20repo%3Amicrosoft%2Fvscode-remote-release%20repo%3Amicrosoft%2Fvscode-pull-request-github%20milestone%3A%22January%202023%20Recovery%201%22)
- [x] Assign candidate issues to the recovery milestone **team**
- [x] Review the `candidate` issues, and if they pass the review assign them to the recovery milestone **team**
- [x] All `candidate` fixes are peer reviewed and pushed to `main` and then cherry-picked into the release branch **team**
- [x] Initiate `insiders` build from `main`
- [x] Issues are tested in the `insiders` **team**
- [x] Build `stable` for all platforms from release branch **@roblourens**
- [x] Issues are verified on `stable` build and the `verified` label is added **@roblourens**
- [x] Check `https://github.com/Microsoft/vscode/compare/release/1.75` to ensure no other commits have been made in the release branch **@roblourens**
- [x] Update the release notes and include a link to a query for the fixed issues **@gregvanl**
- [x] Sanity check of installable bits ([server instructions](https://github.com/microsoft/vscode-remote-release/wiki/Sanity-Check-VS-Code-Servers))
  - [x] Windows 32 bit 
    - [x] signed installer 32-bit @roblourens
    - [x] signed user installer 32-bit @roblourens
    - [x] zip 32-bit @roblourens
    - [x] server 32-bit @roblourens
  - [x] Windows 64 bit **owner**
    - [x] signed installer 64-bit @joyceerhl 
    - [x] signed user installer 64-bit @joyceerhl 
    - [x] zip 64-bit @joyceerhl 
    - [x] server 64-bit @roblourens
    - [x] cli 64-bit @joyceerhl 
  - [x] Windows ARM64 **owner**
    - [x] signed installer ARM64
    - [x] signed user installer ARM64
    - [x] zip ARM64
    - [x] cli ARM64
  - [x] macOS
    - [x] Intel + Universal @TylerLeonhardt 
    - [x] cli Intel @TylerLeonhardt 
    - [x] Apple Silicon + Universal @kieferrm 
    - [x] cli Silicon @kieferrm 
  - [x] Linux x64 @rzhao271
    - [x] deb 
    - [x] rpm 
    - [x] archives
    - [x] snap (`sudo snap install --classic --dangerous <file>.snap`)
    - [x] cli
  - [x] Linux server **owner**
    - [x] x64 @roblourens
    - [x] x64 Alpine @roblourens
    - [x] ARM32 @roblourens 
    - [x] ARM64 @roblourens
    - [x] ARM64 Alpine @roblourens
- [x] Publish website **@gregvanl**
- [x] Publish stable build **@roblourens**
- [x] Create an official release **@roblourens**
  - [x] Create a tag (make sure you pull the release branch first): `git tag 1.75.1 release/1.75`
  - [x] Push the tag: `git push origin 1.75.1`
  - [x] Create a GitHub release: [Open the GitHub tags](https://github.com/microsoft/vscode/tags), and click far right `... > Create Release`. Use the correct title and description from our release notes. [Example](https://github.com/microsoft/vscode/releases/tag/1.39.1)
- [x] Close the milestone on [GitHub](https://github.com/microsoft/vscode/milestones) **@roblourens**

**Comment by gjsjohnmurray** [comment]
Candidate issues link uses a incorrect search.

**Comment by dlschmidt** [comment]
Can you please take https://github.com/microsoft/vscode/issues/173475 into consideration for the first recovery? It affects terminals across all platforms.

**Comment by PhilippeVienne** [comment]
Can you include https://github.com/microsoft/vscode/pull/173682 in the recovery ? It affects any webview opened in a Firefox browser (also Github Codespace).
