### ISSUE TITLE
Errors appear even when files HTML are closed

### ISSUE THREAD

**Issue by vizzale** [microsoft/vscode#173316]
Does this issue occur when all extensions are disabled?: I can't disable the extension in this case to reproduce the error.

- VS Code Version: **1.75.0**
- OS Version: **macOS 10.15.7**

Steps to Reproduce:

1. Opening an HTML file the extension **vscode-htmlhint** show any errors in the "Errors" panel.
2. Closing the same HTML file in the "Errors" panel the identified errors remain.

Before asking here I asked the same question to the team of the extension, but I didn't get any response.
Thanks in advance to anyone who wants to help me.

**Comment by gjsjohnmurray** [comment]
AFAIK this can only be solved by the extension author.

**Comment by vizzale** [comment]
> AFAIK this can only be solved by the extension author.

@gjsjohnmurray Hi John, I guess you're right, but I'm trying everything because I'm not getting any feedback.

**Comment by aeschli** [comment]
Yes, sorry, needs to be fixed by the extension.
