### ISSUE TITLE
Cannot disable switching focus to terminal after executing "Terminal: Run Selected Text in Active Terminal"

### ISSUE THREAD

**Issue by szymonos** [microsoft/vscode#173379]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: v1.75
- OS Version: Windows 11, remote WSL.

Steps to Reproduce:

1. Go to the shell command in the editor.
2. Open command palette and execute: "Terminal: Run Selected Text in Active Terminal"

In previous versions of the VSCode the focus was being kept inside the editor pane, and you could navigate to another command and execute it again. Right now the focus switches to the terminal, so first you have to bring back focus to editor pane to run another command.

**Comment by WillKoehrsen** [comment]
I started having this problem with version 1.75 of VSCode as well. 

* OS Version: MacOS Venture 13.1

**Comment by GuiSeSanz** [comment]
I'm also having this issue ... :(
