### ISSUE TITLE
Warn - "The TypeScript language service died unexpectedly 5 times in the last 5 Minutes. Please consider to open a bug report."

### ISSUE THREAD

**Issue by bargeruns** [Microsoft/vscode#17335]
Seeing this alongside constant prompting to Configure Excludes. I had a project open while I was reading some docs, so I wasn't actively working in the editor when this started appearing.

- VSCode Version: Code 1.8.0 (38746938a4ab94f2f57d9e1309c51fd6fb37553d, 2016-12-13T17:38:28.425Z)
- OS Version: Darwin x64 16.3.0
- Extensions:

|Extension|Author|Version|
|---|---|---|
|vscode-markdownlint|DavidAnson|0.6.0|
|beautify|HookyQR|0.6.2|
|material-icon-theme|PKief|1.1.4|
|indenticator|SirTori|0.2.1|
|html-snippets|abusaidm|0.0.18|
|amvim|auiworks|1.20.0|
|npm-intellisense|christian-kohler|1.1.0|
|path-intellisense|christian-kohler|1.2.0|
|vscode-eslint|dbaeumer|1.2.1|
|githistory|donjayamanne|0.1.4|
|theme-dracula|dracula-theme|1.2.5|
|RelativePath|jakob101|0.11.0|
|vscode-pugbeautify|mrmlnc|1.0.2|
|js-atom-grammar|ms-vscode|0.1.10|
|preview-vscode|searKing|1.1.1|
|stylelint|shinnn|0.13.0|
|html2jade|wmaurer|0.2.0|

---

Steps to Reproduce:

1.
2.

**Comment by mjbvz** [comment]
Can you please provide information about your workspace so that we can investigate?

**Comment by bargeruns** [comment]
@mjbvz I don't have any custom workspace settings. Here are my user settings:

`// Place your settings in this file to overwrite the default settings
{
    "files.autoSave": "onFocusChange",
    "editor.cursorStyle": "underline",
    "editor.cursorBlinking": "blink",
    "editor.acceptSuggestionOnEnter": false,
    "editor.fontFamily": "Inconsolata-g, mono",
    "editor.fontSize": 13,
    "window.openFilesInNewWindow": false,
    "workbench.editor.openPositioning": "right",
    "workbench.editor.enablePreview": false,
    "window.reopenFolders": "none",
    "explorer.autoReveal": false,
    "search.exclude": {
        "**/bower_components": true
    },
    "eslint.options": {
        "semi": ["warn","always"]
    },
    "workbench.editor.showTabs": true,
    "npm-intellisense.scanDevDependencies": true,
    "editor.tabSize": 2,
    "editor.quickSuggestions": true,
    "editor.quickSuggestionsDelay": 5,
    "editor.snippetSuggestions": "top",
    "editor.wordBasedSuggestions": true,
    "terminal.external.osxExec": "iTerm.app",
    "window.zoomLevel": 0
  }`

And my jsconfig.json:

`{
	// See https://go.microsoft.com/fwlink/?LinkId=759670
	// for the documentation about the jsconfig.json format
	"compilerOptions": {
		"target": "es5",
		"module": "commonjs",
		"allowSyntheticDefaultImports": true
	},
	"exclude": [
		"node_modules",
		"bower_components",
		"jspm_packages",
		"tmp",
		"temp",
		"apps/accounts/resources/ppv/bundle.js"
	]
}
`

**Comment by waderyan** [comment]
Thank you for this information. There is nothing obvious from looking at those files. Can you share your entire project so we can clone it on our end?

**Comment by bargeruns** [comment]
@waderyan I really can't, it's my company's main back-end application. It is a large node project with about 22 sub-apps within it. Prior to this update, things were working great (but I realize that really isn't helpful).

**Comment by waderyan** [comment]
Hmm.. if there is anyway to isolate it and share a smaller repo that would be helpful... Let's see if others run into the problem. I'm not seeing it in my test repos.

**Comment by mjbvz** [comment]
@bargeruns Can you also try:

* Add the setting  `"typescript.tsserver.trace": "verbose"`
* Restart VSCode
* reproduce the issue.
* Go to the `TypeScript` tab in the output pane and share the results from there.

These logs will help us investigate what may be going wrong.

**Comment by bargeruns** [comment]
@mjbvz Here you go!

```
[Info  - 3:58:41 PM] Using tsserver from location: /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/typescript/node_modules/typescript/lib/tsserver.js
[Trace - 3:58:41 PM] Sending request: configure (0). Response expected: yes. Current queue length: 0
Arguments: {}
[Trace - 3:58:41 PM] Response received: configure (0). Request took 188 ms. Success: true 
[Trace - 3:58:41 PM] Sending request: compilerOptionsForInferredProjects (1). Response expected: yes. Current queue length: 1
Arguments: {}
[Trace - 3:58:41 PM] Response received: compilerOptionsForInferredProjects (1). Request took 189 ms. Success: true 
Result: true
[Trace - 3:58:41 PM] Sending request: open (2). Response expected: no. Current queue length: 0
Arguments: {}
[Trace - 3:58:41 PM] Sending request: geterr (3). Response expected: no. Current queue length: 0
Arguments: {}
[Trace - 3:58:42 PM] Sending request: quickinfo (4). Response expected: yes. Current queue length: 0
Arguments: {}
[Trace - 3:58:45 PM] TypeScript Service: tried to cancel request with sequence number 4. But request got already delivered.
[Trace - 3:58:49 PM] Event received: projectLanguageServiceState (0).
Data: {}
[Trace - 3:58:56 PM] TypeScript Service: canceled request with sequence number 5
[Trace - 3:58:58 PM] Event received: configFileDiag (0).
Data: {}
[Trace - 3:58:58 PM] Response received: quickinfo (4). Request took 15714 ms. Success: false . Message: No content available.
[Trace - 3:58:58 PM] Sending request: definition (6). Response expected: yes. Current queue length: 2
Arguments: {}
[Error - 3:59:36 PM] TSServer exited with code: unknown
[Error - 3:59:36 PM] 'definition' request failed with error.
Error: Service died.
    at /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/typescript/out/typescriptServiceClient.js:442:46
    at Array.forEach (native)
    at TypeScriptServiceClient.serviceExited (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/typescript/out/typescriptServiceClient.js:441:37)
    at ChildProcess.<anonymous> (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/typescript/out/typescriptServiceClient.js:362:35)
    at emitTwo (events.js:111:20)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
[Info  - 3:59:36 PM] Using tsserver from location: /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/typescript/node_modules/typescript/lib/tsserver.js
```

**Comment by waderyan** [comment]
Hmm... @mhegazy can you peak at this?

**Comment by bargeruns** [comment]
This issue seems to be resolved in the Insiders build v1.9.0, so I may just switch to Insiders full-time for now.

**Comment by Aditya-Sh** [comment]
I have same issue as well. VsCode version 1.8.1. 
My user settings are as below
`{
    "files.autoSave": "off",
    "workbench.statusBar.visible": true,
    "workbench.activityBar.visible": true,
    "window.zoomLevel": 0
}`

I don't have any settings in jsonconfig.js

**Comment by PooLP** [comment]
Hi,

I have the same problem (Warn - "The TypeScript language service died unexpectedly 5 times in the last 5 Minutes. Please consider to open a bug report.") with 1.9.0-insider on simple .JS file 

```
[Info  - 08:58:17] Using tsserver from location: c:\Program Files (x86)\Microsoft VS Code Insiders\resources\app\extensions\typescript\node_modules\typescript\lib\tsserver.js
[Error - 08:58:17] TSServer exited with code: 3221226356
```

**Comment by mhegazy** [comment]
@PooLP  and @Aditya-Sh can you share a sample project we can look at?

**Comment by Aditya-Sh** [comment]
@mhegazy 
I'll check if I can create a sample project to reproduce this issue.
I started getting this issue when I installed typings, maybe I made a mistake somewhere while configuring. I deleted typings and reinstalled it properly, I haven't faced this issue again.
Still I'll try to recreate this issue so that we can find th cause for this.
Thank you

**Comment by waderyan** [comment]
Closing this until we can recreate the issue reliably.
