### ISSUE TITLE
Cannot be Updated

### ISSUE THREAD

**Issue by Chiu-Ping** [microsoft/vscode#173344]
Hello,

When I updated the extension from VSCode in remote host, it always showed the error: **This extension is disabled in this workspace because it is defined to run in the Remote Extension Host.**. Does anyone tell me how to fix it? thanks a lot.

Best regards
Qiuping

**Comment by sandy081** [comment]
How are you updating the extension? Can you please provide steps to reproduce?

**Comment by Chiu-Ping** [comment]
I just updated from VS code extension window.

**Comment by Chiu-Ping** [comment]
Now It was solved by removing those files in remote cluster

**Comment by Jacobify** [comment]
Hello all, I cannot update my vs code , following is my network log
![image](https://user-images.githubusercontent.com/39615077/218291432-0ef01c14-7b85-41c2-8193-35a6c7b197eb.png)
