### ISSUE TITLE
open multiple editors from terminal

### ISSUE THREAD

**Issue by rajinder-yadav** [Microsoft/vscode#17332]
Unable to open multiple editors from the terminal, focus goes back to the one already open.
Make it default to open a new editor, please. 

FYI: menu to open a new editor has a bug so I opened a separate bug for it.

- VSCode Version: Code 1.8.0 (38746938a4ab94f2f57d9e1309c51fd6fb37553d, 2016-12-13T17:38:28.425Z)
- OS Version: Darwin x64 16.1.0
- Extensions:

|Extension|Author|Version|
|---|---|---|
|vscode-markdownlint|DavidAnson|0.6.0|
|EditorConfig|EditorConfig|0.3.4|
|jslint|ajhyndman|1.2.1|
|jshint|dbaeumer|0.10.15|
|vscode-eslint|dbaeumer|1.2.1|
|tslint|eg2|0.7.1|
|cpptools|ms-vscode|0.9.3|
|debugger-for-chrome|msjsdiag|2.4.0|
|Spell|seanmcbreen|0.9.1|
|vim|vscodevim|0.4.9|

---

Steps to Reproduce:

1.
2.

**Comment by kieferrm** [comment]
@rajinder-yadav Pls provides steps to reproduce so that we better understand what you get and what you expect.

**Comment by rajinder-yadav** [comment]
This happen on MacOS, I tired on Linux, it open a new editor each time.

1. Open terminal like (iterm2)
1. From terminal type, `code .`
1. Cd into another folder from the terminal
1. From terminal type `code .`

2nd time around, it will not open a new editor, focus is returned to the previous and editor.

**Comment by kieferrm** [comment]
@rajinder-yadav if I understand you correctly, the result of step 4 is that the folder you cd'ed to in step 3 is not opened. Instead, the window that was opened in step 2 regains focus. I can't reproduce the problem.

**Comment by rajinder-yadav** [comment]
Yes look like vscode got into an odd state last night. I closed all vscode instance running on macos from the taskbar and today everything is working, so closing this issue.
