### ISSUE TITLE
Trouble logging in to export Profile to gist

### ISSUE THREAD

**Issue by bamurtaugh** [microsoft/vscode#173380]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 
Version: 1.76.0-insider (user setup)
Commit: c4a609f94329b17d91cd13a4fd113d1abfe5ec1f
Date: 2023-02-03T05:23:17.202Z
Electron: 19.1.9
Chromium: 102.0.5005.194
Node.js: 16.14.2
V8: 10.2.154.23-electron.0
OS: Windows_NT x64 10.0.25281
Sandboxed: Yes
- OS Version: Windows 11

Steps to Reproduce:

1. Export a Profile
2. Brought to browser to grant VS Code auth access, accept it and return to VS Code
3. I'm prompted there was trouble and to try another way
4. I try the other way, but I'm presented the same toast
5. I try another way for a second time, and this time I'm provided a code `To finish authenticating, navigate to GitHub and paste in the above one-time code.`
6. It ultimately succeeded on the third try

I'm logged into other extensions with GitHub, and I didn't see this flow today for other fresh logins (nor have I seen it in the past).

I'm including my GitHub Auth output logs. It looks like I got `[error] FetchError: request to http://localhost:3000/codeExchangeProxyEndpoints/github/login/oauth/access_token failed, reason: connect ECONNREFUSED 127.0.0.1:3000` twice.

[GH-log-feb-3.txt](https://github.com/microsoft/vscode/files/10583135/GH-log-feb-3.txt)

**Comment by TylerLeonhardt** [comment]
🤦‍♂️ nice find. I was typing too fast.

**Comment by joyceerhl** [comment]
@TylerLeonhardt is it an issue that we hardcode a reference to stable vscode.dev even when we are running VS Code Insiders: https://github.com/microsoft/vscode/pull/173428/files
