### ISSUE TITLE
'New Terminal' displays a wrong working directory path

### ISSUE THREAD

**Issue by KzJules** [microsoft/vscode#173393]
Type: <b>Bug</b>

Before this update (version: 1.75.0), 'New Terminal' displays the right working directory path as below: 
C:\Users\USER\Documents\GitHub\q-valoris-dev>

But after the update (version: 1.75.0), 'New Terminal' displays a very obscure path of the working directory as below:
←]633;P;IsWindows=←]633;A←]633;P;Cwd=C:\x5cUsers\x5cUSER\x5cDocuments\x5cGitHub\x5cq-valoris-devPS C:\Users\USER\Documents\GitHub\q-valoris-dev> ←]633;B

That brings me back to use windows cmd again

VS Code version: Code 1.75.0 (e2816fe719a4026ffa1ee0189dc89bdfdbafb164, 2023-02-01T15:23:45.584Z)
OS version: Windows_NT x64 6.3.9600
Modes:
Sandboxed: No

**Comment by Yernartem** [comment]
←]633;P;IsWindows=←]633;A←]633;P;Cwd=C: How to fix this bag? Please help me, i am working with react project

**Comment by KzJules** [comment]
> The 'New Terminal' in VSCode helps us go straight into the project directory in the PowerShell.
It does not work well now. Before fixing this bug, a workaround is to use CMD (Command Prompt) or PowerShell to go to our project directory.
For Windows users, type **cmd** in the windows search bar, which opens the command prompt.
When the command prompt is open, you have to navigate into your React project directory.
Read this article to navigate into the directories.
[https://www.digitalcitizen.life/command-prompt-how-use-basic-commands/](url)
When you are in your project directory with something like that in the command prompt
**C:\Users\USER\Documents\GitHub\Your_Project_Directory>**
Type **npm build** to build your React project
Type **npm start** to start your React project
