### ISSUE TITLE
Shell Script syntax coloring wrong after 1.75.0 update (macOS)

### ISSUE THREAD

**Issue by bland328** [microsoft/vscode#173336]
Type: <b>Bug</b>

This short, simple _(and mostly nonsensical)_ Bash script demonstrates broken Shell Script syntax coloring I'm seeing after updating to `1.75.0`:

```bash
#!/usr/bin/env bash
cmd=( 'ls' '-la' )
if (( ${#cmd[@]} )); then
	"${cmd[@]}"
	printf '%s' "${cmd[@]}"
fi
```

Here's the incorrect coloring under `1.75.0`:

<img width="263" alt="Screenshot 2023-02-03 at 10 37 29 AM" src="https://user-images.githubusercontent.com/8441277/216660157-549d7f5f-42da-4d2b-936d-f07a5548c3c5.png">

And here's the same code displayed properly under `1.74.3`:

<img width="257" alt="Screenshot 2023-02-03 at 11 07 24 AM" src="https://user-images.githubusercontent.com/8441277/216664166-6c0b17a8-e004-4c9f-b617-a0efe7f23c73.png">

VS Code version: Code 1.75.0 (e2816fe719a4026ffa1ee0189dc89bdfdbafb164, 2023-02-01T15:26:31.005Z)
OS version: Darwin arm64 22.2.0
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M2 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|5, 4, 4|
|Memory (System)|16.00GB (0.16GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by bland328** [comment]
Note that the code above is indented using tabs. I've now observed that indenting with spaces instead can influence Shell Script syntax coloring.

**Comment by philipmiesbauer** [comment]
I can confirm the same on Ubuntu. Makes working on bash files much more difficult.

**Comment by babaric-dev** [comment]
Same here.

**Comment by ValShaped** [comment]
Also present on Windows.

**Comment by alexr00** [comment]
For the recovery release I'll revert the update to the grammar. 

In VS Code Insiders I'll keep the new grammar and add some more tests to see which of these issues still exist there.

**Comment by aiday-mar** [comment]
verification succeeded
