### ISSUE TITLE
terminal crash 

### ISSUE THREAD

**Issue by DritanProgriIT** [microsoft/vscode#173390]
Type: <b>Bug</b>

## This error occurred when try to open terminal 
> exception occurred during launch (posix_spawn failed: Permission denied).

VS Code version: Code 1.75.0 (e2816fe719a4026ffa1ee0189dc89bdfdbafb164, 2023-02-01T15:29:17.766Z)
OS version: Linux x64 6.1.8-gentoo-x86_64
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 3548)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|0, 1, 0|
|Memory (System)|31.24GB (26.48GB free)|
|Process Argv|--enable-features=UseOzonePlatform --ozone-platform=wayland --unity-launch --crash-reporter-id 3f80b246-7b4d-44ab-8cfc-9092f30c9c6b|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|gnome|
|XDG_CURRENT_DESKTOP|GNOME|
|XDG_SESSION_DESKTOP|gnome|
|XDG_SESSION_TYPE|wayland|
</details><details><summary>Extensions (35)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|2.2.6
gitlens|eam|13.2.0
vscode-html-css|ecm|1.13.1
prettier-vscode|esb|9.10.4
rest-client|hum|0.25.1
solidity|Jua|0.0.141
vscode-language-babel|mgm|0.0.36
vscode-language-pack-it|MS-|1.75.2023020109
isort|ms-|2022.8.0
python|ms-|2023.2.0
vscode-pylance|ms-|2023.2.10
jupyter|ms-|2023.1.2000312134
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.14
vscode-jupyter-cell-tags|ms-|0.1.6
vscode-jupyter-slideshow|ms-|0.1.5
cmake-tools|ms-|1.13.45
cpptools|ms-|1.13.9
cpptools-extension-pack|ms-|1.3.0
vscode-typescript-next|ms-|5.0.202302020
platformio-ide|pla|3.0.0
fabric8-analytics|red|0.3.6
java|red|1.14.0
cmake|twx|0.0.17
intellicode-api-usage-examples|Vis|0.2.7
vscodeintellicode|Vis|1.2.30
vscode-boot-dev-pack|vmw|0.2.1
vscode-spring-boot|vmw|1.44.0
vscode-java-debug|vsc|0.48.0
vscode-java-dependency|vsc|0.21.1
vscode-java-pack|vsc|0.25.7
vscode-java-test|vsc|0.37.1
vscode-maven|vsc|0.40.4
vscode-spring-boot-dashboard|vsc|0.10.1
vscode-spring-initializr|vsc|0.11.2

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
azure-dev_surveyone:30548225
pyindex848:30577860
nodejswelcome1cf:30587006
282f8724:30602487
f6dab269:30613381
pythonsymbol12cf:30657549
2i9eh265:30646982

```

</details>

**Comment by chrismurtagh** [comment]
Same issue here 



CPUs | Intel(R) Core(TM) i7-10875H CPU @ 2.30GHz (16 x 4252)
-- | --
GPU Status | 2d_canvas: enabled canvas_oop_rasterization: disabled_off direct_rendering_display_compositor: disabled_off_ok gpu_compositing: enabled multiple_raster_threads: enabled_on opengl: enabled_on rasterization: enabled raw_draw: disabled_off_ok skia_renderer: enabled_on video_decode: disabled_software video_encode: disabled_software vulkan: disabled_off webgl: enabled webgl2: enabled webgpu: disabled_off
Load (avg) | 1, 1, 0
Memory (System) | 15.49GB (10.30GB free)
Process Argv | --crash-reporter-id 345e9aa9-4768-4085-99a7-8ba0a740978d
Screen Reader | no
VM | 0%



Extension | Author (truncated) | Version
-- | -- | --
better-comments | aar | 3.0.2
vscode-intelephense-client | bme | 1.9.4
vscode-tailwindcss | bra | 0.9.7
multi-cursor-case-preserve | Car | 1.0.5
npm-intellisense | chr | 1.4.4
vscode-markdownlint | Dav | 0.49.0
vscode-eslint | dba | 2.2.6
composer-php-vscode | DEV | 1.29.12304
phptools-vscode | DEV | 1.29.12304
profiler-php-vscode | DEV | 1.29.12304
es7-react-js-snippets | dsz | 4.4.3
gitlens | eam | 13.2.0
vscode-html-css | ecm | 1.13.1
prettier-vscode | esb | 9.10.4
auto-rename-tag | for | 0.1.10
copilot | Git | 1.71.8269
solidity | Jua | 0.0.141
mongodb-vscode | mon | 0.10.0
vscode-docker | ms- | 1.23.3
vscode-kubernetes-tools | ms- | 1.3.11
isort | ms- | 2022.8.0
python | ms- | 2023.2.0
vscode-pylance | ms- | 2023.2.10
jupyter | ms- | 2023.1.2000312134
vscode-jupyter-cell-tags | ms- | 0.1.6
vscode-jupyter-slideshow | ms- | 0.1.5
remote-ssh | ms- | 0.96.0
remote-ssh-edit | ms- | 0.84.0
cpptools | ms- | 1.13.9
makefile-tools | ms- | 0.6.0
remote-explorer | ms- | 0.2.0
vscode-jest | Ort | 5.2.2
vscode-thunder-client | ran | 2.3.4
ansible | red | 1.1.34
vscode-yaml | red | 1.11.0
LiveServer | rit | 5.7.9
vscode-icons | vsc | 12.2.0
vscode-import-cost | wix | 3.3.0
php-debug | xde | 1.31.0


AB
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscorecescf:30445987
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
azure-dev_surveyone:30548225
vsccc:30610678
pyindex848cf:30577861
nodejswelcome1:30587005
2e4cg342:30602488
89544117:30613380
pythonsymbol12cf:30657549
vscsb:30628654

**Comment by yvesh** [comment]
Same issue on 1.7.5 for me on Linux. 1.7.4 is working fine. Renderer Log is not really helping.

```
2023-02-04 10:51:19.364 [trace] CommandService#executeCommand workbench.action.terminal.new
2023-02-04 10:51:19.364 [trace] terminalInstance#ctor (instanceId: 2) {}
2023-02-04 10:51:19.399 [trace] Webgl was loaded
2023-02-04 10:51:19.436 [debug] terminalInstance added capability 1
2023-02-04 10:51:19.445 [debug] Terminal process exit (instanceId: 2) with code undefined
2023-02-04 10:51:19.445 [debug] Terminal process exit (instanceId: 2) state 2
2023-02-04 10:51:19.445 [trace] terminalInstance#dispose (instanceId: 2)
```

**Comment by DritanProgriIT** [comment]
same log for me 
`2023-02-04 13:40:18.531 [trace] CommandService#executeCommand workbench.action.terminal.new
2023-02-04 13:40:18.531 [trace] terminalInstance#ctor (instanceId: 8) {}
2023-02-04 13:40:18.590 [trace] Webgl was loaded
2023-02-04 13:40:18.710 [debug] terminalInstance added capability 1
2023-02-04 13:40:18.717 [debug] Terminal process exit (instanceId: 8) with code undefined
2023-02-04 13:40:18.718 [debug] Terminal process exit (instanceId: 8) state 2
2023-02-04 13:40:18.718 [trace] terminalInstance#dispose (instanceId: 8)`

I tried this version with Debian on the same machine and there are no problems, only in Gentoo this bug happens

**Comment by zeule** [comment]
Gentoo removes executable permission from all the package files and then set that for selected ones. This time it is resources/app/node_modules.asar.unpacked/node-pty/build/Release/spawn-helper who is left without the permission.

**Comment by DritanProgriIT** [comment]
@zeule i have this bug only with new version `app-editors/vscode-1.75.0` with old version `app-editors/vscode-1.74.3` everything works fine

**Comment by zeule** [comment]
> @zeule i have this bug only with new version `app-editors/vscode-1.75.0` with old version `app-editors/vscode-1.74.3` everything works fine

This file probably appeared in 1.75, but do we have to discuss Gentoo bugs here?

**Comment by zeule** [comment]
https://bugs.gentoo.org/893208

**Comment by DritanProgriIT** [comment]
> https://bugs.gentoo.org/893208

@zeule  Thank you i solved
