### ISSUE TITLE
Expand/collapse icon

### ISSUE THREAD

**Issue by majidkoohjani** [microsoft/vscode#173347]
Type: <b>Feature Request</b>

Hello dear vscode developers :)

As a developer I think the expand/collapse icon is very terrible. I will be so nice to change it to a plus/mius icon.
Thank you veeeeeeery much.

VS Code version: Code 1.75.0 (e2816fe719a4026ffa1ee0189dc89bdfdbafb164, 2023-02-01T15:23:45.584Z)
OS version: Windows_NT x64 10.0.19045
Modes:
Sandboxed: No

**Comment by aeschli** [comment]
You can do that by using a different product icon theme.
E.g. https://marketplace.visualstudio.com/items?itemName=davidbwaters.macos-modern-theme
