### ISSUE TITLE
Debugger in notebook: the debugger runs the whole cell regardless of breakpoints

### ISSUE THREAD

**Issue by vpvinc** [microsoft/vscode#173320]
Type: <b>Bug</b>

I have  a cell that contains a loop that references variables defined in previous cells.

If I place breakpoints in the loop and run the debugger (not the line by line debugger), it works fine for the first breakpoints and then ignores the rest. Even if I restart the kernel, the debugger keeps ignoring the breakpoints, even those that were taken into account during the first run.

VS Code version: Code 1.75.0 (e2816fe719a4026ffa1ee0189dc89bdfdbafb164, 2023-02-01T15:23:45.584Z)
OS version: Windows_NT x64 10.0.19042
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.82GB (6.26GB free)|
|Process Argv|--crash-reporter-id f4d1dc29-4d78-48c7-9639-5cca74781ff2|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (17)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-sql-formatter|adp|1.4.4
docs-view|bie|0.0.11
dscodegpt|Dan|1.0.15
githistory|don|0.6.19
todo-tree|Gru|0.0.223
git-graph|mhu|1.30.0
black-formatter|ms-|2022.6.0
isort|ms-|2022.8.0
python|ms-|2023.2.0
vscode-pylance|ms-|2023.2.10
jupyter|ms-|2023.1.2000312134
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.14
vscode-jupyter-cell-tags|ms-|0.1.6
vscode-jupyter-slideshow|ms-|0.1.5
autodocstring|njp|0.6.1
markdown-all-in-one|yzh|3.5.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
azure-dev_surveyone:30548225
pyindex848:30577860
nodejswelcome1cf:30587006
3biah626:30602489
f6dab269:30613381
pythonsymbol12cf:30657549
vscsbc:30628655

```

</details>

**Comment by roblourens** [comment]
Could you

- Share some code to repro this
- Set `"jupyter.logging.level": "verbose"`, reproduce this again, and share the log from the Jupyter output channel?

**Comment by vpvinc** [comment]
I could not reproduce the issue, it works fine ! If I get the issue again I will share the code and and the log. 
Thanks for your time
