### ISSUE TITLE
TypeScript JSX should have been named TypeScript TSX

### ISSUE THREAD

**Issue by haugerbr** [microsoft/vscode#173332]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.75.0
- OS Version: Any

Steps to Reproduce:

1. Look at VSCode [Release Notes for 1.75.0](https://code.visualstudio.com/updates/v1_75#_languages)
2. Look at VSCode Language Selector

The release notes state Typescript React has been renamed to Typescript TSX however in VSCode it is Typescript JSX. Given the file extension is .tsx for Typescript, I agree with the release notes that it should be TSX.

# Release Notes
![image](https://user-images.githubusercontent.com/660975/216658951-3ddf8945-3732-4410-a4b6-5da4adf62988.png)

# Language Selector
![image](https://user-images.githubusercontent.com/660975/216659126-1a88ef82-1d89-423e-a05b-5e73d7df1ada.png)

**Comment by mjbvz** [comment]
See https://github.com/microsoft/vscode/pull/173333 Will fix release notes
