### ISSUE TITLE
Peek view content is overlapping due to sticky scroll

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#173331]
No background on sticky scroll overlay?

<img width="1572" alt="image" src="https://user-images.githubusercontent.com/2193314/216659240-b84662b8-752a-460a-a682-d4f975f2813d.png">
<img width="765" alt="image" src="https://user-images.githubusercontent.com/2193314/216659314-ba51ef60-59f5-4a40-9201-c2477c71bc48.png">

Happens on all themes

**Comment by jrieken** [comment]
version?

**Comment by jrieken** [comment]
theme?

**Comment by Tyriar** [comment]
All themes, latest insiders, consistent repro. gifcap isn't working for some reason but here's some samples using the following settings.json:

```json
{
	"editor.stickyScroll.enabled": true
}
```

Dark v2:

<img width="540" alt="image" src="https://user-images.githubusercontent.com/2193314/216673615-51607e10-7ac2-4856-af46-3dbeb5e2f637.png">

Light+:

<img width="483" alt="image" src="https://user-images.githubusercontent.com/2193314/216673650-068646f2-3c18-4b72-b81f-2cb07aefa48b.png">

Abyss:

<img width="419" alt="image" src="https://user-images.githubusercontent.com/2193314/216673680-06e536fb-1d0c-4256-8471-be90bbbc7e0f.png">

Sapphire:

<img width="470" alt="image" src="https://user-images.githubusercontent.com/2193314/216673591-38364fde-4468-44d5-aa29-96ff167c84a2.png">


Version: 1.76.0-insider (user setup)
Commit: c4a609f94329b17d91cd13a4fd113d1abfe5ec1f
Date: 2023-02-03T05:23:17.202Z
Electron: 19.1.9
Chromium: 102.0.5005.194
Node.js: 16.14.2
V8: 10.2.154.23-electron.0
OS: Windows_NT x64 10.0.22621
Sandboxed: Yes

**Comment by rebornix** [comment]
I'm on macOS 13.2 (22D49), latest 1.76 Insiders (c4a609f94329b17d91cd13a4fd113d1abfe5ec1f). Disabled all settings and only enable sticky scroll, and can reproduce this with Peek -> Peek Call Hierarchy with all builtin themes.

**Comment by jrieken** [comment]
@roblourens this is a regression from https://github.com/microsoft/vscode/commit/0d6eb738273b35cd1c490cf32398f954f676f0fe

**Comment by jrieken** [comment]
Yeah, since the popularity of CSS variables these strings have become more important. Some tooling or checking would be nice. I glanced at playwright if there is a way to get notified about undefined CSS variable usages but couldn't find anything
