### ISSUE TITLE
right click menu in wrong position with sidebar on the right

### ISSUE THREAD

**Issue by advisor-gazes** [microsoft/vscode#173348]
Does this issue occur when all extensions are disabled?: Yes/No

Steps to Reproduce:

1. Move sidebar to the right
2. Set titlebar to native
3. rightclick in profiles or settings as in recording

https://user-images.githubusercontent.com/124391091/216675070-c17327d4-0c9f-4ce0-9490-ffb142ba1ce3.mp4

**Comment by rzhao271** [comment]
Confirmed that the accounts menu still opens up and covers the account menu icon.
