### ISSUE TITLE
Keyboard shortcut to switch to between file and corresponding test file

### ISSUE THREAD

**Issue by joshua-rh** [microsoft/vscode#173375]
It's cool that we can nest test files in the explorer (e.g. `Form.test.tsx` is nested under `Form.tsx`).

Many times, I'd like to quickly switch from `Form.tsx` to the corresponding test file `Form.test.tsx`. Today, this would mean opening the Explorer, and clicking on the nested test file. It would be great to be to assign a keyboard shortcut to this.

The keyboard should also be able to go from test file to file. If there is no corresponding test file, it should just show a notification that a test file doesn't exist.

**Comment by connor4312** [comment]
https://github.com/microsoft/vscode/issues/126932
