### ISSUE TITLE
The color decoration in Color Theme Extension json file do not appear in "semanticTokenColors"

### ISSUE THREAD

**Issue by Michaelzhouisnotwhite** [microsoft/vscode#173399]
- VS Code Version: 1.75.0
- OS Version: Windows_NT x64 10.0.22623

Steps to Reproduce:

1. Open An Vscode Theme Project.

![image](https://user-images.githubusercontent.com/52443370/216748123-a84d1437-84d9-4145-9dc0-d77fcdc85120.png)

2. open xxx-color-theme.json

You can see color decorator "semanticTokenColors" doesn't appear while it is good in "tokenColors".

Bad in  "semanticTokenColors":
![image](https://user-images.githubusercontent.com/52443370/216748173-6801140f-77cf-402d-9b13-62c7e0999251.png)

Good in "tokenColors"

![image](https://user-images.githubusercontent.com/52443370/216748189-24a2b348-1f3f-4375-904c-848f84ed97f9.png)

**Comment by aeschli** [comment]
You are hitting the limit for maximum number of color decorators rendered. 

You can increase that limit with `editor.colorDecoratorsLimit`, but note that this might impact the rendering performance.

**Comment by aeschli** [comment]
I created https://github.com/microsoft/vscode/issues/173541 to give give visual feedback when the limit is hit

**Comment by Michaelzhouisnotwhite** [comment]
ok. Change the "editor.colorDecoratorsLimit" do solve my problem. I thought the decorators was dynamic display.
