### ISSUE TITLE
Update to 1.75.0 delayed commit => push workflow by disabling push button

### ISSUE THREAD

**Issue by skelouse** [microsoft/vscode#173371]
- VS Code Version: 1.75.0
- OS Version: Ubuntu 22.04.1

Steps to Reproduce:

1. Click commit check
2. Click ... menu and see that "push" is disabled

[vscode issue.webm](https://user-images.githubusercontent.com/42463301/216707550-cd44f53c-fa55-4d68-8cde-f9d547db648c.webm)

**Comment by lszomoru** [comment]
@skelouse, thank you very much fort he feedback. This is a change in behaviour that has been introduced in `1.75` and documented in our [release notes](https://code.visualstudio.com/updates/v1_75#_command-disablement). I will go ahead and close this issue "as designed" but please don't hesitate to reopen it in case you have any further questions or concerns. Thanks!

**Comment by skelouse** [comment]
@lszomoru 

If it's by design then the issue is that the buttons remain disabled if the context menu is open.

Thanks for the speedy reply!

**Comment by lszomoru** [comment]
I believe that this is a limitation of the context menu. @jrieken please correct me if I am wrong.
