### ISSUE TITLE
Terminix support

### ISSUE THREAD

**Issue by TheAifam5** [Microsoft/vscode#17338]
- VSCode Version: VIsual Code Insiders 1.9.0 89bdb7c35a89535612d386199ee33e6bd74ee068
- OS Version: ArchLinux

Steps to Reproduce:

1. Install Terminix (https://github.com/gnunn1/terminix)
2. Change default value for `terminal.external.linuxExec` to `terminix`

Debug console:
```
Running executable
undefinedError opening terminal: unknown.
[Inferior 1 (process 15814) exited with code 01]
Program exited with code 01
```

**Comment by weinand** [comment]
No plans to support Terminix
