### ISSUE TITLE
Overlapping text in settings window

### ISSUE THREAD

**Issue by kamalteja** [microsoft/vscode#173335]
When you search for something in the settings windows, the titles that appear on the left pane are displayed with overlapping text. See the picture below. Hovering mouse over these text will make it visible and once the mouse is removed over the text, the overlapping behaviour is back. This is pretty annoying to read through the titles.

![Screenshot from 2023-02-03 17-50-38](https://user-images.githubusercontent.com/15894677/216660850-bc171bf7-8f0a-4112-82b6-d3e2520a523f.png)

**Comment by rzhao271** [comment]
What version of VS Code are you using, and what OS?

**Comment by jonagoldman** [comment]
Same issue here, 

VS Code details:
```
Version: 1.75.0
Commit: e2816fe719a4026ffa1ee0189dc89bdfdbafb164
Date: 2023-02-01T15:29:17.766Z
Electron: 19.1.9
Chromium: 102.0.5005.194
Node.js: 16.14.2
V8: 10.2.154.23-electron.0
OS: Linux x64 6.1.9-1-MANJARO
Sandboxed: No
```

![image](https://user-images.githubusercontent.com/1297559/217431479-62086372-a24b-447c-8f8f-a7b48e1f552b.png)

**Comment by kamalteja** [comment]
> What version of VS Code are you using, and what OS?

Following are my environment details.

VS code:
```bash
$ code --version
1.75.0
e2816fe719a4026ffa1ee0189dc89bdfdbafb164
x64
```
OS: Fedora 37

**Comment by rzhao271** [comment]
Does the issue still occur when you run code with the `--disable-gpu` flag?

**Comment by kamalteja** [comment]
I don’t see the issue when I run code with `--disable-gpu` flag
