### ISSUE TITLE
Align behaviour when user presses `Esc` while in search bar between online editor and desktop client

### ISSUE THREAD

**Issue by bsun94** [microsoft/vscode#173361]
On the client application, whenever you press `Ctrl + F` to search from something, while the focus is still in the search bar, if you press `Esc`, the search bar is closed and the focus is returned to the editor area (where you were last editing).

On the web client (https://vscode.dev/), the behaviour is different. While the focus is in the search bar (after `Ctrl + F`), if you press `Esc`, focus is lost altogether - it's neither in the search bar nor in the editing area. The user then has to perform extra steps to return focus to the editor.

I'm not sure if this is a bug or should be a "new feature," but aligning the above behaviour to what we're used to from the client application would be quite a quality-of-life improvement to my experience using VSCode.

**Comment by amunger** [comment]
seems to be working correctly now
