### ISSUE TITLE
Network Errors On Startup and Extension Load

### ISSUE THREAD

**Issue by geauxtigers** [microsoft/vscode#173464]
Type: <b>Bug</b>

It occurs when vscode is started.

VS Code version: Code 1.75.0 (e2816fe719a4026ffa1ee0189dc89bdfdbafb164, 2023-02-01T15:23:45.584Z)
OS version: Windows_NT x64 10.0.19044
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2808)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.83GB (8.10GB free)|
|Process Argv|--crash-reporter-id ae69abb5-4aca-4c3f-a2fa-985d71d21800|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
pythonvspyt678:30270856
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30322572
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805cf:30301675
pythonvspyt200:30340761
vscextlangct:30333562
binariesv615:30325510
pythonvssor306:30344512
bridge0708:30335490
vstre464cf:30346473
bridge0723cf:30346311

```

</details>

[vscode-app-1675575956545.log](https://github.com/microsoft/vscode/files/10610298/vscode-app-1675575956545.log)

I cannot get vscode to properly load.  The attached log shows the errors from the developer console.  I have uninstalled and reinstalled vsc.  I also renamed my user .vscode directory to attempt to have a blank slate at startup without extensions.  This issue has persisted across several versions.  I have disabled my firewall, reset dns and winsock, and rebooted my router and modem.

I was also having issues connecting to github.com (and github.com only) via any installed browser.  After a several months trying to resolve with no luck, I disabled WSL and the problem magically cleared up in the browser.  I was hoping it would clear up issues in vsc but problems still remain even after uninstalling and reinstalling.

The logs above were generated when starting in a directory with a .vscode directory.  I did not find any issue that I thought was directly related.  Any idea the cause of the issue?

Thanks

**Comment by sandy081** [comment]
May I know exactly what feature of VS Code is not working for you? It would be great if you can provide a screenshot.

**Comment by geauxtigers** [comment]
I am sorry, it is the Extension Warehouse.  When I simply click on the Extension icon, the following is shown after several seconds.  I cannot search extensions or install fresh extensions.

![image](https://user-images.githubusercontent.com/8951542/216986843-a115c3b2-0d55-4ea9-a69c-98ede5d7505f.png)

The Developer Console displays this ...

![image](https://user-images.githubusercontent.com/8951542/216987192-7a127265-fa32-42d7-b835-57d82690bd98.png)

Thanks!

**Comment by geauxtigers** [comment]
Just as a note, I can connect to the resources in the above screenshot with the browser.  I get the response:

`{"count":1,"value":{"Message":"The requested resource does not support http method 'GET'."}}`

So, I can connect to the resource without an error in the browser.  On other items which fail prior to the extension errors such as https://vscodeexperiments.azureedge.net/experiments/vscode-experiments.json, I do get .json back when accessing from the browser.

**Comment by deepak1556** [comment]
Can you check if the issue happens with our [exploration build](https://az764295.vo.msecnd.net/exploration/7f9964a09b02ea9b8f6f2f588486d719af390374/VSCodeUserSetup-x64-1.76.0-exploration.exe) that comes with a newer version of the runtime.

**Comment by geauxtigers** [comment]
The exploration build works.  I can search extensions and install with no errors.  Does this give any clue or provide other tools to help in answering why the regular releases have not been working?

Thanks!

**Comment by deepak1556** [comment]
Thanks for confirming, insiders and stable will have the fix once we update to Electron 22. Please continue to use the exploration builds as alternative.

**Comment by geauxtigers** [comment]
Ok, thanks!  Is there a set release date for the version having Electron 22?

**Comment by deepak1556** [comment]
We are targeting the update for v1.77

**Comment by geauxtigers** [comment]
Ok. Thanks for your help!
