### ISSUE TITLE
Feature Req: https://github.com/microsoft/vscode/issues/172214

### ISSUE THREAD

**Issue by the-moog** [microsoft/vscode#173420]
I reference the issue https://github.com/microsoft/vscode/issues/172214 which was closed - even though I was trying out a suggestion.

I think my suggestion is still valid, as the proposed solution does not meet the requirements. Further windows get the same colour even if you are on an entirely different systems.  This is because profiles follow the user not the repo.

Please either re-open [172214](https://github.com/microsoft/vscode/issues/172214) or copy paste.

**Comment by DonJayamanne** [comment]
Duplicate of https://github.com/microsoft/vscode/issues/172214

**Comment by DonJayamanne** [comment]
@the-moog sorry for that, i have re-opened that issue.
