### ISSUE TITLE
The Menu Bar Cannot be Expanded

### ISSUE THREAD

**Issue by WYC-M** [microsoft/vscode#173459]
Type: <b>Bug</b>

In VSCODE 1.75.0, when the **screen resolution is 1366x768**, **the position of the command center is centered** (not centered before), which makes the menu bar located on the left side of the command center lack space. When VSCODE is in English, you'll notice that **the "terminal" and "help" options are collapsed**. When the language of vscode is Chinese Simplified, you can see that **the entire menu bar is collapsed**, and if you want to display the menu bar in its entirety, you must uncheck the command center.       

!(https://github.com/WYC-M/Pic/blob/main/pic%20about%20vscode.png?raw=true)

**How to reproduce the problem**: Install VSCODE **version 1.75.0**, set the **screen resolution to 1366x768**, and then **install the Chinese Simplified extension** to reproduce the problem of **the menu bar being collapsed**.  _(Machine translation, may not be accurate)_

Thank you!

VS Code version: Code 1.75.0 (e2816fe719a4026ffa1ee0189dc89bdfdbafb164, 2023-02-01T15:23:45.584Z)
OS version: Windows_NT x64 10.0.19045
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4210U CPU @ 1.70GHz (4 x 2394)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|7.70GB (3.92GB free)|
|Process Argv|--crash-reporter-id 5bd9e4c0-e3a3-4c7f-82a7-366a36d28731 --crash-reporter-id 5bd9e4c0-e3a3-4c7f-82a7-366a36d28731 --crash-reporter-id 5bd9e4c0-e3a3-4c7f-82a7-366a36d28731|
|Screen Reader|no|
|VM|25%|
</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-language-pack-zh-hans|MS-|1.75.2023020109
isort|ms-|2022.8.0
python|ms-|2023.2.0
vscode-pylance|ms-|2023.2.10
jupyter|ms-|2023.1.2000312134
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.14
vscode-jupyter-cell-tags|ms-|0.1.6
vscode-jupyter-slideshow|ms-|0.1.5
cmake-tools|ms-|1.13.45
cpptools|ms-|1.13.9
cpptools-extension-pack|ms-|1.3.0
cmake|twx|0.0.17
markdown-pdf|yza|1.4.4

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vstes516:30244333
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
azure-dev_surveyone:30548225
vsccc:30610678
pyindex848:30577860
nodejswelcome1cf:30587006
282f8724:30602487
pyind779:30657576
89544117:30613380
pythonsymbol12cf:30657549

```

</details>

**Comment by sbatten** [comment]
@jrieken maybe we could do 2 things here. Reduce the size of the command center. It takes up more space than it needs in that photo. And secondly, tweak the hamburger-ification of the main menu threshold.

**Comment by WYC-M** [comment]
Sorry for not responding to your message in a timely manner. I think you're _right,_ but I think we can **move the command center a bit to the right** so that _the blank space on both sides of the command center is the same size_
