### ISSUE TITLE
Invalid value when you point the mouse at a variable

### ISSUE THREAD

**Issue by scootpl** [microsoft/vscode#173492]
Does this issue occur when all extensions are disabled?: No, but the problem occurs in various extensions (Go, C/C++)

- VS Code Version:

Version: 1.75.0 (Universal)
Commit: e2816fe719a4026ffa1ee0189dc89bdfdbafb164
Date: 2023-02-01T15:24:42.903Z
Electron: 19.1.9
Chromium: 102.0.5005.194
Node.js: 16.14.2
V8: 10.2.154.23-electron.0
OS: Darwin x64 22.2.0
Sandboxed: No

- OS Version: macOS Ventura 13.1

Steps to Reproduce:

1. Define a variable or constant and comment it out
2. Redefine the same variable with different value line below
3. Use variable in your app
4. When you point the mouse at a variable, you will see an invalid value

<img width="826" alt="vsc-issue" src="https://user-images.githubusercontent.com/22987898/216848178-4ce5c690-3df5-4fe0-b881-06378fe20e7b.png">

**Comment by roblourens** [comment]
Please file this on the go extension repo, thanks
