### ISSUE TITLE
The "Strat Debugging" toolbar cannot be enabled.

### ISSUE THREAD

**Issue by slgxmh** [microsoft/vscode#173405]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.75.0 (Universal)
- OS Version: Darwin arm64 22.3.0

Steps to Reproduce:

1. Right-click the toolbar and select 'Hide Start Debugging'
<img width="356" alt="image" src="https://user-images.githubusercontent.com/13213238/216753174-2bd703e8-aa17-4e99-9c9e-91b8a807a025.png">
2. The menu bar does not have an option turned on and I can't find any way to turn it on.
<img width="400" alt="image" src="https://user-images.githubusercontent.com/13213238/216753468-a9a2e482-d051-4ef6-b4f6-27100ff755da.png">

**In this case, it will be difficult to switch between different debugs.**

**Comment by roblourens** [comment]
It's still there, you can find "Start Debugging" under the `...` menu or right click it to re-show the menu item. In general if you are stuck you can run the "Reset all menus" option.

**Comment by slgxmh** [comment]
<img width="456" alt="image" src="https://user-images.githubusercontent.com/13213238/217167084-a163a15f-16a8-490c-8d46-b4c0e7c2b9f3.png">
Thanks for your help. However, it is not convenient to switch between different debugging.
