### ISSUE TITLE
Add `.markdownlintignore` file association

### ISSUE THREAD

**Issue by thernstig** [microsoft/vscode#173419]
The language mode should be set to `ignore`

**Comment by thernstig** [comment]
I realize this probably should rather be done in https://github.com/DavidAnson/vscode-markdownlint

**Comment by unional** [comment]
I think this should goes to vscode directly instead of markdownlint?

Because the vscode detects it to be markdown even with all extensions disabled.

**Comment by thernstig** [comment]
@unional but markdownlint is very specific. It is not markdown, but a linter for markdown.

But I am not completely opposed to adding it here but if so I think some of VS Code's main developers has to comment if that is a good idea or not (and getting them to notice this issue might be hard).

**Comment by unional** [comment]
No problem. It just feel odd that it is detected as markdown. 

It is not detected by content as the content is not markdown. And it is not detected by file extension either. 

So I am guessing there is some code here explicitly set it to markdown, which then the fix should be simple.
