### ISSUE TITLE
ENOENT when spawning a process in MacOS

### ISSUE THREAD

**Issue by we-taper** [microsoft/vscode#173480]
## Information
I am encountering an issue with VSCode on MacOS where the program is unable to spawn new processes with proper `PATH` environment variables. This results in the `ENOENT` error message below.

The issue occurs when the [Latex-workshop](https://github.com/James-Yu/LaTeX-Workshop) plugin tries to spawn relevant latex processes to compile the source code. I have [confirmed with the author](https://github.com/James-Yu/LaTeX-Workshop/discussions/3459#discussioncomment-4841137) of the extension that they have not manipulated the PATH.

From the error message, I noticed that the PATH environment variable is properly initialized. On the other hand, even within VSCode's built-in terminal, the PATH has been properly initialized and the related executable can be found.

Also worth noting:
- the issue only occurs when the project is opened from the "Recent" list inside VSCode's welcome page. If the project is opened from the terminal via `code PROJECT_FOLDER`, the issue disappears.
- The relevant latex executable are installed via `brew`, which uses the `path_helper` to setup the environment variables. Related issue is the #13701.

## Steps to Reproduce

1. Install the latex-workshop project. Create a new Latex project and open it. Close it for now.
2. Then, open the same project from the "Recent" list inside VSCode's welcome page.
3. Try to build the project. Observe the issue where VSCode fails to spawn a new process with proper PATH environment variables.

## Error message

```
[15:10:50][Builder] LaTeX build process spawned with PID undefined.
[15:10:50][Builder] LaTeX fatal error on PID undefined. Error: spawn pdflatex ENOENT
[15:10:50]Error: spawn pdflatex ENOENT
    at Process.ChildProcess._handle.onexit (node:internal/child_process:283:19)
    at onErrorNT (node:internal/child_process:478:16)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
[15:10:50][Builder] Does the executable exist? $PATH: /usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin, $Path: undefined, $SHELL: /bin/zsh
[15:10:50][Builder] 
```

## Envrionment

- Mac OS 13.1 on Apple M1
- VSCode Version: 1.74.3. No A/B experiment involved.

**Comment by bpasero** [comment]
Take note of https://code.visualstudio.com/docs/supporting/faq#_resolving-shell-environment-fails, you might be hitting an issue with VS Code trying to resolve the shell environment.

**Comment by we-taper** [comment]
Just an update that, VSCode `1.75.0` released recently seems to have resolved the problem. I will test for a few more days, and if nothing happened again, I will close this issue.
Thanks.
