### ISSUE TITLE
Deleting cell should have confirmation before removing cell

### ISSUE THREAD

**Issue by fonnesbeck** [microsoft/vscode#173481]
Having just accidentally deleted a cell that had been running for over 4 hours, I'd like to suggest that there be a confirmation popup for running Jupyter cells to be deleted. Ideally there should be an option to confirm for *all* cells, but should be a default for cells that are currently executing.

**Comment by roblourens** [comment]
Would take a PR to add a confirmation dialog to delete running cells, with a setting to disable this confirmation step

**Comment by jzyrobert** [comment]
> Would take a PR to add a confirmation dialog to delete running cells, with a setting to disable this confirmation step

Should this check happen in the action [runWithContext](https://github.com/microsoft/vscode/blob/720985f2c68cadb5e375d9ec671476c548f61769/src/vs/workbench/contrib/notebook/browser/controller/editActions.ts#L155) or in the [action](https://github.com/microsoft/vscode/blob/720985f2c68cadb5e375d9ec671476c548f61769/src/vs/workbench/contrib/notebook/browser/controller/cellOperations.ts#L122) itself?

**Comment by roblourens** [comment]
Looks like that's just a function that's called in one place, and I think changing either is fine

**Comment by weartist** [comment]
i will go and deal this
