### ISSUE TITLE
Can't launch .NET file

### ISSUE THREAD

**Issue by GenocideJoker420** [microsoft/vscode#173439]
Type: <b>Bug</b>

First I could run my .NET file normaly but now it just shows errors when I press f5:

-------------------------------------------------------------------
You may only use the Microsoft .NET Core Debugger (vsdbg) with
Visual Studio Code, Visual Studio or Visual Studio for Mac software
to help you develop and test your applications.
-------------------------------------------------------------------

It goes to debug console and that pops up. Also the .NET file opens and immediately closes EVEN WITH CONSOLE.READKEY.

I also changed Console: InternalConsole to Console: externalTerminal in the launch.json file.

VS Code version: Code 1.75.0 (e2816fe719a4026ffa1ee0189dc89bdfdbafb164, 2023-02-01T15:23:45.584Z)
OS version: Windows_NT x64 10.0.22000
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i5-1155G7 @ 2.50GHz (8 x 2496)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|7.65GB (0.85GB free)|
|Process Argv|--crash-reporter-id 190d6e5f-e370-4d5d-b951-ecf891524a62|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
code-runner|for|0.12.0
Ionide-fsharp|Ion|7.4.0
csharp|ms-|1.25.4
vscode-dotnet-pack|ms-|1.0.12
vscode-dotnet-sdk|ms-|0.8.0
jupyter|ms-|2023.1.2000312134
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.14
vscode-jupyter-cell-tags|ms-|0.1.6
vscode-jupyter-slideshow|ms-|0.1.5
vscode-icons|vsc|12.2.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscorecescf:30445987
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vscaat:30438848
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
azure-dev_surveyone:30548225
pyindex848:30577860
nodejswelcome1cf:30587006
282f8724:30602487
pyind779:30657576
f6dab269:30613381
pythonsymbol12:30657548
a9j8j154:30646983
vscsbc:30628655

```

</details>

**Comment by GenocideJoker420** [comment]
I'm using windows

**Comment by GenocideJoker420** [comment]
Does [roblourens](https://github.com/roblourens) have the solution?

**Comment by GenocideJoker420** [comment]
Well... no programming anymore than

**Comment by roblourens** [comment]
Sorry for the trouble, please file this on the dotnet extension repo

**Comment by GenocideJoker420** [comment]
Where can I find that?

**Comment by GenocideJoker420** [comment]
Is that in VS CODE?

**Comment by GenocideJoker420** [comment]
See I cant do anything with this I need an answer NOW!
