### ISSUE TITLE
Consider removing `New Text File` in favor of `New File...` in file menu bar

### ISSUE THREAD

**Issue by karrtikr** [microsoft/vscode#173479]
<img src="https://user-images.githubusercontent.com/13199757/216828079-674d48b0-063c-4681-890a-37313812d19e.png" width=300 />

Just clicking `New File...` opens a picker to open text file:

<img src="https://user-images.githubusercontent.com/13199757/216828139-b7dd30fc-4f7e-413b-9c1d-81ecacf85d1d.png" width=500 />
so the former seems very redundant.

**Comment by lramos15** [comment]
The reason we kept it is for mouse users who want to keep the same old untitled file experience they can always go and do File -> New Text File.

cc @daviddossett on thoughts

**Comment by daviddossett** [comment]
I think it makes sense to keep text files as a standalone entry to avoid burdening a smaller % of users who are looking for one of the other types.

I'm sure this was discussed quite a lot at the time, but were there any alternatives to the "New File" label? I.e. something that described them as other/alternate/ in some way?

**Comment by bpasero** [comment]
I also suggest to keep this.

**Comment by karrtikr** [comment]
I see, feel free to close this in that case.
