### ISSUE TITLE
"Toggle Terminal" has blank shortcut tip in empty window

### ISSUE THREAD

**Issue by coreh** [Microsoft/vscode#17340]
- VSCode Version: 1.8.0
- OS Version: macOS 10.12

Steps to Reproduce:

1. Start a new empty window, with no files
2. Look at the keyboard shortcut tips: "Toggle Terminal" has no shortcut listed. (But ctrl-` works as usual to open it)

<img width="577" alt="screen shot 2016-12-15 at 17 09 42" src="https://cloud.githubusercontent.com/assets/418473/21238316/b4f3158a-c2e9-11e6-8f41-fb8946a66ee6.png">

**Comment by chrmarti** [comment]
@coreh What does the command palette (Shift+Cmd+P) show as the shortcut for Toggle Terminal? (Trying to figure out if this is a problem specific to the watermark.)

**Comment by coreh** [comment]
It doesn't show anything, but I don't have any custom key bindings set on `keybindings.json`

<img width="600" alt="screen shot 2016-12-19 at 18 29 04" src="https://cloud.githubusercontent.com/assets/418473/21328031/0ac8e9c6-c619-11e6-8551-fb383db28766.png">

**Comment by chrmarti** [comment]
@coreh What kind of keyboard layout are you using? Is it different from US English?

**Comment by coreh** [comment]
Oh. That seems to be it!

I'm using **U.S. International – PC**. Switching it to the regular U.S. English keyboard, and reopening the VS Code window does make the shortcut text appear.

Under this layout, \`, ', ^, ", and ~ are dead/combining keys to type accented characters like é ã ô ü ç à. This special handling could probably be what's causing it?

**Comment by chrmarti** [comment]
Yes, I guess so.

**Comment by alexandrudima** [comment]
I have validated that we now (i.e. after PR #22894 aka #17521 -- in today's upcoming Insiders build) appear to behave correctly for this keyboard layout and the welcome screen correctly renders the keybinding and pressing it does toggle the terminal. As an added bonus, the welcome screen updates itself as I switch keyboard layouts live :).

![screen shot 2017-03-24 at 10 39 25](https://cloud.githubusercontent.com/assets/5047891/24288567/2b47d478-107e-11e7-9800-5951e4cbae3b.png)
