### ISSUE TITLE
Missing `TERM_PROGRAM` variable at launch time

### ISSUE THREAD

**Issue by stefanistrate** [microsoft/vscode#173438]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.75.0
- OS Version: macOS Ventura 13.2

Steps to Reproduce:

1. Add the following line to `~/.zshrc` (or the equivalent `~/.bashrc`):
```bash
echo "TERM=$TERM_PROGRAM" >> ~/Desktop/debug.txt
```
2. When launching VS Code, the variable `TERM_PROGRAM` is not set properly (i.e. the output of the text file I write to is `TERM=`).
3. When opening the TERMINAL tab in VS Code afterwards, a new line is added to my output file with the correct `TERM_PROGRAM` (i.e. `TERM=vscode`).

Why is `TERM_PROGRAM` missing initially? This behaviour is stopping me from using `TERM_PROGRAM` to decide when to launch `tmux` automatically (i.e. I don't want to launch it when the terminal belongs to VS Code).

Any workarounds?

Thanks,
Ștefan

**Comment by meganrogge** [comment]
maybe related #173277

**Comment by Tyriar** [comment]
This is by design, TERM_PROGRAM is only set when a _terminal_ launches. You might be looking for the new environment variable `VSCODE_RESOLVING_ENVIRONMENT` that we just added in 1.75 https://code.visualstudio.com/updates/v1_75#_new-vscoderesolvingenvironment-environment-variable
