### ISSUE TITLE
asWebviewUri causes 401 when using run-in-browser

### ISSUE THREAD

**Issue by strowk** [microsoft/vscode#173448]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.75.0
- OS Version: Windows 10

Steps to Reproduce:

1. create new web extension using standard generator (yo code)
2. create js file in folder "external"
3. load that file into webview using f.e.
```
      const onDiskPath = vscode.Uri.file(
        path.join(context.extensionPath, "external", "myscript.js")
      );
```
and then 
`const scriptPath = panel.webview.asWebviewUri(onDiskPath);` 
, passing result within html like this `<script src="${scriptPath}"></script>` 
4. Run extension using f5, and webview would work
5. Run extension via browser using `yarn run-in-browser`
6. When trying to load the script webview logs error 401

<img width="343" alt="image" src="https://user-images.githubusercontent.com/25692644/216793367-c7a9c20e-10b0-4a9c-a7d9-77fd1ddaa576.png">

Note: I have followed instructions from here: https://code.visualstudio.com/api/extension-guides/webview#loading-local-content

**Comment by strowk** [comment]
Hm, I suspect there is a mistake in the guide. Instead of 
```
vscode.Uri.file(
        path.join
```
suggested there, one should use `vscode.Uri.joinPath` . That made it work. So this is a documentation mistake IMO

**Comment by mjbvz** [comment]
Note for verification: this was a docs only change
