### ISSUE TITLE
502 Bad Gateway when using `ng serve` from Codespace

### ISSUE THREAD

**Issue by WileEJeff** [microsoft/vscode#173432]
Steps to reproduce:
In a (nearly) empty repository I created a codespace and then ran:

```
$ npm install -g @angular/cli
...
$ ng new $PROJECT_NAME
...
$ cd $PROJECT_NAME
$ ng serve
```

`ng serve` eventually spits out:
```
Build at: 2023-02-04T15:10:51.587Z - Hash: 85fe228ed9a82164 - Time: 7298ms
** Angular Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200/ **
✔ Compiled successfully.
```

When I ctrl-click to open the link, `localhost:4200` is converted to `wileejeff-upgraded-space-train-76499pvw59xcj54-4200.preview.app.github.dev` which seems correct-ish.

However instead of that link opening the Angular sample app, I get a page that says
```
502 Bad Gateway
nginx
```

Is this a bug in codespaces, or do I need to do something in order for this to work correctly?

Version: 1.75.0
Commit: e2816fe719a4026ffa1ee0189dc89bdfdbafb164
User Agent: Mozilla/5.0 (X11; CrOS x86_64 15236.80.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36
Embedder: codespaces

**Comment by aeschli** [comment]
Yes, this is something the codespaces team needs to look at. 
Please check https://docs.github.com/en/support/learning-about-github-support/about-github-support

**Comment by Ashk3000** [comment]
Are there any workarounds? Having this too.

**Comment by lambdaFun94** [comment]
I am having a similar problem when trying to run a vite app. Any workaround would be great. Running `npm run dev -- --host 0.0.0.0` recommended from another post did not solve this problem

**Comment by Lazzaretti** [comment]
For me, it works with `npm run ng serve -- --host=0.0.0.0 --disable-host-check` 
However, in addition, I needed to change the port visibility from private to public

**Comment by jandresboyaca** [comment]
> For me, it works with `npm run ng serve -- --host=0.0.0.0 --disable-host-check` However, in addition, I needed to change the port visibility from private to public

It works!

**Comment by dperuo** [comment]
The modified command also works without using npm:

```bash
ng serve --host=0.0.0.0 --disable-host-check
```

**Comment by WileEJeff** [comment]
--host=0.0.0.0 --public-host=${CODESPACE_NAME}-4200.preview.app.github.dev

also works for me, with presumably less security issues than
--disable-host-check
