### ISSUE TITLE
Visual rendering glitch in terminal with V2 themes

### ISSUE THREAD

**Issue by dlschmidt** [microsoft/vscode#173475]
Does this issue occur when all extensions are disabled?: Yes

Version: 1.75.0 (Universal)
Commit: e2816fe719a4026ffa1ee0189dc89bdfdbafb164
Date: 2023-02-01T15:24:42.903Z
Electron: 19.1.9
Chromium: 102.0.5005.194
Node.js: 16.14.2
V8: 10.2.154.23-electron.0
OS: Darwin arm64 22.3.0
Sandboxed: No

Steps to Reproduce:

1. Open nano in the terminal

<img width="521" alt="vscode_glitch" src="https://user-images.githubusercontent.com/20640295/216820925-899ac130-ca8d-4c3f-8855-2b2bc2f94d0f.png">

I have already checked, when using the macOS Terminal, the bug will not occur.

**Comment by dlschmidt** [comment]
This could probably be a regression from "[Powerline triangle and diagonal line custom glyphs](https://code.visualstudio.com/updates/v1_75#_powerline-triangle-and-diagonal-line-custom-glyphs)".

**Comment by dlschmidt** [comment]
I have to add that this is a problem with terminal in general, not restricted to macOS.

**Comment by dfarley1** [comment]
I'm observing this as well on remote Linux workspaces connected via MacOS. VSCode 1.75.0, MacOS Monterey 12.6

![image](https://user-images.githubusercontent.com/5204693/217363879-09bc89de-f9e4-4157-a5b8-c65d1f67f164.png)

**Comment by GitMensch** [comment]
Does anyone know which commits have broken that?

**Comment by dlschmidt** [comment]
I have found the origin of this bug. It is the new theme "Dark+ V2 (Experimental)"

![image](https://user-images.githubusercontent.com/20640295/217532879-4fd9b70f-b0bb-49dd-838f-82cbb2379f8f.png)
![image](https://user-images.githubusercontent.com/20640295/217532977-b389cec9-7bf8-4975-8d2c-e20d8f894fb9.png)

That explains why it was also visible at Windows.

**Comment by GitMensch** [comment]
So work-around: just don't use the new themes for now, right?

**Comment by dlschmidt** [comment]
It gets more strange, when using transparency with `terminal.foreground`, as the new theme does, then the visuals get broken.

Workaround: Don't use transparency:
```json
"workbench.colorCustomizations": {
        "terminal.foreground": "#cccccc"
}
```

**Comment by Tyriar** [comment]
Reopening to prevent this from happening even when xterm.js is handed a transparent color: https://github.com/xtermjs/xterm.js/issues/4408
