### ISSUE TITLE
markdown extension: Kotlin code block syntax highlighting is broken

### ISSUE THREAD

**Issue by hojongs** [microsoft/vscode#173404]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.75.0
- OS Version: macOS 12.1

Steps to Reproduce:

1. Write code block including the word "kotlin"

For example:

```kotlin
println("kotlin")
println("hello")
println("kotlin")
println("kotlin")
```

2. See the incorrectly highlighted syntax result after the word "kotlin"

<img width="159" alt="image" src="https://user-images.githubusercontent.com/15096588/216753267-71b0a28b-78ef-4efb-80cc-1ef600151c5c.png">

<img width="148" alt="image" src="https://user-images.githubusercontent.com/15096588/216753330-ac3cf853-1e2a-468a-81e5-4086ed492707.png">

<img width="244" alt="image" src="https://user-images.githubusercontent.com/15096588/216753366-f1b24996-eac1-4184-921b-824459b80b7b.png">

<img width="239" alt="image" src="https://user-images.githubusercontent.com/15096588/216753372-5a10dd50-f3b5-41d9-8e93-cf9497cf6119.png">

I expect like this:

<img width="197" alt="image" src="https://user-images.githubusercontent.com/15096588/216753282-6237fdfb-6291-4992-82ad-2b2399dfa224.png">

**Comment by mjbvz** [comment]
I don't think VS Code includes a built-in kotlin grammar. Please start by filling this against the kotlin extension so they can investigate
