### ISSUE TITLE
Issue with saving files on mounted drive: "Could not resolve any model with provided uri"

### ISSUE THREAD

**Issue by amandajh** [Microsoft/vscode#17345]
- VSCode Version: 1.8.0
- OS Version: Mac OS X El Capitan

This issue seems to happen only for mounted drives (e.g. SSHFS a remote server to access files, and open the mounted folder with VSC). 

Steps to Reproduce:

1. Open Visual Studio Code with the folder of the mounted drive. 
2. Edit and save a file (unfortunately, I can I only get this to happen sporadically. Sometimes it works, sometimes it doesn't... and I can't seem to find a pattern for it)
3. The following error messages show up:
"Failed to save 'examplefile.js': The content on disk is newer. Click on Compare to compare your version with the one on disk."

And then when I click "Compare":
"Unable to open 'examplefile.js (on disk) ↔ examplefile.js (in Visual Studio Code)': Could not resolve any model with provided uri.."

I hope this was helpful, and if there is currently any resolution to this, I would like to know. It has only been happening since I updated to 1.8.0. It has made VSC unusable for me on my current project (and I really love VSC, its been great).

EDIT: I included a couple of screenshots. It seems to happen with any type of files, but I gave this one as an example.

![screen shot 2016-12-15 at 4 50 48 pm](https://cloud.githubusercontent.com/assets/7053830/21243397/aad50ce6-c2e6-11e6-8c45-9fa6006c5fe6.png)
![screen shot 2016-12-15 at 4 50 56 pm](https://cloud.githubusercontent.com/assets/7053830/21243401/afadff98-c2e6-11e6-97a4-7e67b5b05405.png)

**Comment by rick4470** [comment]
Same issue here on OSX from a Remote ubuntu machine via samba share.

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/13665 for the issues with network drives but the exception here is definitely a bad regression we must fix in 1.8.

**Comment by bpasero** [comment]
To verify: 
* open a file and make it dirty
* change it meanwhile with another editor
* try to save
* you should get an error and a way to resolve the error (you can either accept your changes or revert to the changes on disk)

**Comment by amandajh** [comment]
That was fast! Thank you.
