### ISSUE TITLE
Allow to install extension in all of profiles at once.

### ISSUE THREAD

**Issue by waleedrana777** [microsoft/vscode#173489]
I have 5,6 profiles and 200+ extensions. If I want to install a common extension to all profiles, I have to do manually!
Allow to install extension in all profiles at once. One by one takes a lot of time.

**Comment by 283375** [comment]
+1 for this. Maybe we could make profiles "inheritable" (or "extendable"? I've seen this in some `tsconfig.json`s), such as

`common.json`
```json
{
  "workbench.colorTheme": "My Favorite Theme",
  "editor.fontFamily": "FiraCode NF, monospace",
  "editor.fontLigatures": true,
  "extensions": ["copilot", "git graph", "indent rainbow", "other useful exts", "..."]
  "...": "..."
}
```

then we could make `python.json`, `web.json`, ..., to inherit `common.json`, like

`python.json`
```json
{
  "extends": "common.json",
  "editor.tabSize": 4,
  "extensions": ["pylance", "docstring generator", "..."]
}
```

`web.json`
```json
{
  "extends": "common.json",
  "editor.tabSize": 2,
  "extensions": ["prettier", "eslint", "volar", "..."]
}
```

and thus we could only modify `common.json` to update all other profiles.

Maybe this is hard to implement, but I think it's a good idea for this issue. Would love to see this feature if possible😇

**Comment by ldelossa** [comment]
+1 

It's often that I use profiles just to separate user configs between environments. 

I usually want the same extensions to exist in different profiles, and I'll disable/enable them for a particular workspace. 

Right now, there is no way of syncing settings after a profile has been created. Some type of sync/cascading settings would be super useful.

**Comment by sandy081** [comment]
/duplicate

https://github.com/microsoft/vscode/issues/157492
