### ISSUE TITLE
selectionMode "always" is not working in snippets

### ISSUE THREAD

**Issue by vdegenne** [microsoft/vscode#173412]
It seems that selectionMode "always" has no effect in snippets

https://user-images.githubusercontent.com/2827383/216760353-aa92ac73-e1bf-4335-a80b-402a72b1f91c.mp4

In this demo you can see (after I trigger the function call) that it doesn't select any items in the suggestion box (I hit Enter, which normally would autocomplete the selected item, but here because nothing is selected it just breaks a new line).

Version: 1.75.0
Commit: e2816fe719a4026ffa1ee0189dc89bdfdbafb164
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36
Embedder: vscode.dev

**Comment by vdegenne** [comment]
Sorry It's preventive by default, had to use `"editor.suggest.snippetsPreventQuickSuggestions": false,`

**Comment by virtuallyunknown** [comment]
> Sorry It's preventive by default, had to use `"editor.suggest.snippetsPreventQuickSuggestions": false,`

This was driving me insane, thanks a lot for the fix!
