### ISSUE TITLE
code --list-extensions doesn't list all extensions

### ISSUE THREAD

**Issue by techeverri** [Microsoft/vscode#17343]
- VSCode Version:
1.8.0
38746938a4ab94f2f57d9e1309c51fd6fb37553d
- OS Version:
Microsoft Windows 8.1 Pro
6.3.9600 N/A Build 9600

Steps to Reproduce:

1. Open the command line and type `code --list-extensions`

Observed:

<img width="320" alt="2016-12-15 15_11_53-cmd" src="https://cloud.githubusercontent.com/assets/3720424/21240336/e40e3b80-c2d8-11e6-9053-f0ddfb5b8e8b.png">

Expected:

<img width="209" alt="2016-12-15 15_12_55-sfe-client-app - visual studio code" src="https://cloud.githubusercontent.com/assets/3720424/21240361/fe7dc90e-c2d8-11e6-95da-6f42178293bc.png">

**Comment by joaomoreno** [comment]
This is rather strange. You see no error? The command line simply returns after printing out `alefragnani.Bookmarks`?

**Comment by techeverri** [comment]
@joaomoreno I see no error.
![code-list-extensions](https://cloud.githubusercontent.com/assets/3720424/21245367/02b59ecc-c2f0-11e6-8fb9-881c852793fd.gif)

**Comment by joaomoreno** [comment]
What do you get with `code --help`?

**Comment by techeverri** [comment]
<img width="479" alt="2016-12-15 18_00_48-cmd" src="https://cloud.githubusercontent.com/assets/3720424/21245446/739e60ce-c2f0-11e6-87ed-3a866df361cb.png">

**Comment by joaomoreno** [comment]
And what's inside your `.vscode/extensions` folder in your home directory?

**Comment by techeverri** [comment]
<img width="472" alt="2016-12-15 18_18_09-cmd" src="https://cloud.githubusercontent.com/assets/3720424/21245832/ded7caf4-c2f2-11e6-8554-163aba1be877.png">

**Comment by gstewart** [comment]
I am seeing the same with both 1.8.0 and 1.9.0-insider versions on Windows 7.

It only returns the first extension in alphabetical order.

I have a different set of extensions on both versions and they each only show 1st extension they have installed.

**Comment by rezen** [comment]
I'm also experiencing the same issue on Windows 10.

```
Windows 10 Version 1607 Build 14393.576
VSCode Version 1.8.1
```

**Comment by joaomoreno** [comment]
I could reproduce this.

**Comment by kflu** [comment]
Same thing here with this vscode version:

```
1.8.1
ee428b0eead68bf0fb99ab5fdc4439be227b6281
```

I'm on Windows 10

**Comment by nizulzaim** [comment]
Yeah same problem here. I am using Visual Studio Code - Insiders 1.9.0-insider
