### ISSUE TITLE
Docs not pass down through Partial<T>

### ISSUE THREAD

**Issue by unional** [Microsoft/vscode#17357]
- VSCode Version: 1.8.0

```ts
interface Foo {
  /**
   * x is your name
   */
  x: string
}

function foo(f: Foo) {}
function boo(b: Partial<Foo>) {}

foo({})
boo({})
```
![image](https://cloud.githubusercontent.com/assets/3254987/21246397/4feaff4c-c2dd-11e6-8bb8-1e31e0e54bf4.png)
![image](https://cloud.githubusercontent.com/assets/3254987/21246403/5c6d6458-c2dd-11e6-90fd-a2badcc72c35.png)

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript#12966
