### ISSUE TITLE
[Insiders] TypeScript language server keeps crashing

### ISSUE THREAD

**Issue by nguerrera** [microsoft/vscode#173582]
Type: <b>Bug</b>

## Repro steps
1. Open VS Code Insiders (fresh new window, no workspace)
2. File -> New Text File
3. Select Language -> TypeScript

## Expected
Everything works as usual.

## Actual 
1. Warning popup: `"The JS/TS language service crashed."`
2. Error popup (sometimes): `"TypeScript language server exited with error. Error message is: write EPIPE"`
3. TypeScript output pane:
```
[Info - 15:51:30.603] Using tsserver from: c:\Users\nicholg\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js
[Info - 15:51:30.605] <syntax> Log file: [object Object]
[Info - 15:51:30.605] <syntax> Trace directory: file:///c%3A/Users/nicholg/AppData/Roaming/Code%20-%20Insiders/logs/20230206T095121/window1/exthost/vscode.typescript-language-features/tsserver-log-4xysch
[Info - 15:51:30.605] <syntax> Forking...
[Info - 15:51:30.616] <syntax> Starting...
[Info - 15:51:30.617] <semantic> Log file: [object Object]
[Info - 15:51:30.617] <semantic> Trace directory: file:///c%3A/Users/nicholg/AppData/Roaming/Code%20-%20Insiders/logs/20230206T095121/window1/exthost/vscode.typescript-language-features/tsserver-log-e1jTYn
[Info - 15:51:30.617] <semantic> Forking...
[Info - 15:51:30.630] <semantic> Starting...
[Error - 15:51:31.5] TSServer exited. Code: 1. Signal: null
```

This gets repeated over and over again, and lots of tsserver-log-xxxxx directories are being created in rapid succession, but they are all empty. I tried setting `"typescript.tsserver.log": "verbose"` and restarting but the log directories are still empty.

VS Code version: Code - Insiders 1.76.0-insider (c9e3ef865539061b5602c6b9ac6030332aa1ce70, 2023-02-06T05:24:33.398Z)
OS version: Windows_NT x64 10.0.22623
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz (12 x 3192)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|63.85GB (47.92GB free)|
|Process Argv|-n --crash-reporter-id fe512df2-6a31-4087-9145-8f60a2db5339|
|Screen Reader|no|
|VM|33%|
</details><details><summary>Extensions (31)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-openapi|42C|4.15.16
vscode-eslint|dba|2.4.0
EditorConfig|Edi|0.16.4
prettier-vscode|esb|9.10.4
copilot|Git|1.71.8269
vscode-pull-request-github|Git|0.59.2023020609
vscode-mocha-test-adapter|hbe|2.14.1
vscode-test-explorer|hbe|2.21.1
Lisp|mat|0.1.12
cadl-vscode|Mic|0.39.0
vscode-edge-devtools|ms-|2.1.1
isort|ms-|2022.8.0
python|ms-|2023.2.0
vscode-pylance|ms-|2023.2.10
jupyter|ms-|2023.1.2000312134
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.14
vscode-jupyter-cell-tags|ms-|0.1.6
vscode-jupyter-slideshow|ms-|0.1.5
remote-wsl|ms-|0.75.1
hexeditor|ms-|1.9.11
live-server|ms-|0.4.5
powershell|ms-|2023.1.0
test-adapter-converter|ms-|0.1.6
vscode-js-profile-flame|ms-|1.0.5
vsliveshare|ms-|1.0.5828
vscode-commons|red|0.0.6
vscode-yaml|red|1.11.0
vscode-sort-json|ric|1.20.0
rewrap|stk|1.16.3
code-spell-checker|str|2.16.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vslsvsres303:30308271
pythonvspyl392:30422396
pythontb:30258533
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscod805cf:30301675
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30404738
cppdebug:30492333
vsclangdf:30492506
c4g48928:30535728
dsvsc012:30540252
pynewext54:30618038
pylantcb52:30590116
pyindex848:30611229
nodejswelcome1:30587009
pyind779:30611226
vscrpc:30624061
pythonsymbol12:30651887
showlangstatbar:30657381

```

</details>

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

**Comment by nguerrera** [comment]
Yes. 
<img width="433" alt="image" src="https://user-images.githubusercontent.com/75470/217350693-5c6402c9-6d7a-4d63-b420-5d46b2bf9f0c.png">

**Comment by nguerrera** [comment]
Duplicate of #173258
