### ISSUE TITLE
Explorer not updating file list

### ISSUE THREAD

**Issue by brendandixon** [Microsoft/vscode#17354]
- VSCode Version: Code 1.8.0 (38746938a4ab94f2f57d9e1309c51fd6fb37553d, 2016-12-13T17:38:28.425Z)
- OS Version: Darwin x64 16.1.0
- Extensions:

|Extension|Author|Version|
|---|---|---|
|xml|DotJoshJohnson|1.6.0|
|vscode-docker|PeterJausovec|0.0.10|
|code-settings-sync|Shan|2.3.8|
|githistory|donjayamanne|0.1.4|
|python|donjayamanne|0.5.5|
|haml|groksrc|0.0.2|
|Go|lukehoban|0.6.51|
|csharp|ms-vscode|1.5.3|
|Ruby|rebornix|0.10.4|

---

Steps to Reproduce:

1. Make changes to the directory from a command line
2. Note it does not appear in the Explorer

**Comment by kieferrm** [comment]
@brendandixon Code does not auto-refresh file changes that are made externally or through the built-in terminal. You need to you use the explorer's `Refresh` action for that.

<img width="428" alt="screen shot 2016-12-15 at 5 29 03 pm" src="https://cloud.githubusercontent.com/assets/4674940/21248468/204dbd2e-c2ec-11e6-802b-00b4504640a6.png">

**Comment by bpasero** [comment]
@kieferrm that is very much not true, the explorer updates from any file event in the same way as a lot of other UI components react to file changes.

However, our file watcher can fail in some cases e.g. when there are too many events happening at the same time or for example when working with network drives on windows.

@brendandixon does this reproduce every time for you? Can you provide more detailed steps for me to reproduce?

**Comment by brendandixon** [comment]
@bpasero I'll keep my eyes open. Unfortunately, it's seems to be working again. (Go figure.)

**Comment by brendandixon** [comment]
@bpasero I think I have more detail. I often switch Git branches "under the covers" from VSCode. That is, using the command line, I'll bounce between branches to see different versions. It is this scenario where, occasionally, the explorer fails to see the changes.

**Comment by langdonx** [comment]
> However, our file watcher can fail in some cases e.g. when there are too many events happening at the same time or for example when working with network drives on windows.

@bpasero This happens fairly consistent for me when building my app using grunt.  My grunt script shuffles around a lot of files (app -> dist-temp -> dist) and often times explorer gets into a state where dist will appear empty even though it's not, and the manual refresh button will have no effect.

Interestingly enough, if I drag in a file in dist/ manually, it will trigger an update (the same thing I'd expect the refresh button to do).  I can make an animated GIF of it all if that would help.

**Comment by langdonx** [comment]
Seems related: https://github.com/Microsoft/vscode/issues/15744

**Comment by bpasero** [comment]
@langdonx which OS?

**Comment by langdonx** [comment]
Windows 10, sorry.

**Comment by bpasero** [comment]
This is very likely https://github.com/Microsoft/vscode/issues/19377
