### ISSUE TITLE
Restore ctrl-click on window-title feature on macOS

### ISSUE THREAD

**Issue by MacGritsch** [microsoft/vscode#173563]
If you command-click on a window-title (the filename), on every macOS-Application it allows you to reveal the file in the Finder. This was possible also in vscode in older versions, but starting with version 1.75.0 it seems not to work.
Can you restore that or is that an Electron-bug?

**Comment by bpasero** [comment]
Try with `window.titleBarStyle` set to `native`

**Comment by MacGritsch** [comment]
Works, but why has this changed?
I have not changed the settings before - so I was in custom (default) mode - and it worked (till last update).

**Comment by penx** [comment]
`window.titleBarStyle: native` works but the title doesn't have the theme colours so doesn't look great.

Pretty sure this was working fine with themed title bars a few weeks ago, without needing to change this setting.

**Comment by JulianGaibler** [comment]
I want to add that the menu should not only open when command-clicking the file name in the title bar but also by right-clicking it, and for some reason, this is not working in the native titleBarStyle either.

Both command-click and right-click used to work on the default title bar before 1.75.0.

**Comment by bpasero** [comment]
We used to have a context menu showing all segments of the path of the opened file up to the root that you could use to reveal that segment in the native explorer. This menu got lost, a while ago.

Bringing it back now via https://github.com/microsoft/vscode/pull/199503

![Recording 2023-11-29 at 09 49 51](https://github.com/microsoft/vscode/assets/900690/74f222fe-20d2-4f74-8ca4-b4f4c71fc774)

**Comment by bpasero** [comment]
I am updating the title because I think its `Ctrl-click` to open the context menu, not `Command-click`, but please let me know if I am wrong.

**Comment by MacGritsch** [comment]
Its COMMAND+Click.
Its a System-Feature on macOS.
And there you get the chance to open the finder at that listed folders which is very helpful.

**Comment by bpasero** [comment]
Got it. We never supported `Cmd-click` as far as I can recall. Since we are not drawing a native title control on macOS, I think going via the context menu is a good compromise.

**Comment by MacGritsch** [comment]
Not sure what the gif above shows, but its not the native window titlebar and also does not look like my vscode (it has no searchbar and so on).

**Comment by bpasero** [comment]
This is only an issue when custom title is enabled (which is on by default on macOS).

**Comment by bpasero** [comment]
Sorry, I take it back. Even with custom menu we want to support `Cmd-click` for this feature. I am able to restore it but only when `Cmd-click` on the command center:

![Recording 2023-11-29 at 11 06 54](https://github.com/microsoft/vscode/assets/900690/fb2fc24a-ca2e-4a8d-9ffc-fb736db9c63b)

**Comment by penx** [comment]
VSCode 1.82.2 on the left,  1.74.3 on the right (November 2022)

https://github.com/microsoft/vscode/assets/1027024/0c425040-774c-49dc-80ac-9fc98581d6f9

**Comment by bpasero** [comment]
**Verification:**
* be on macOS with custom title and command center enabled
* open a file from your disk
* right-click into command center
* ensure you see path segments of the active file and can click to reveal in OS
* ensure you also see config options (e.g. hide command center)
* right-click over empty space left or right of command center
* verify you only get the config options
* right-click over layout control buttons
* verify you only get config options and button options

**Comment by penx** [comment]
>  I am able to restore it but only when Cmd-click on the command center

I guess this means you can't restore it on window title yet?

Can this be kept open to restore it on window title in future? (to reflect standard macos behaviour, which previously worked0

Or is there something that will prevent this from being reintroduced?

**Comment by bpasero** [comment]
@penx the command center is actually the window title in VS Code:

![image](https://github.com/microsoft/vscode/assets/900690/5692836f-1978-4a60-bc6a-788ecf41f0aa)

Are you explicitly disabling command center?

**Comment by penx** [comment]
I disabled it to record the video above and kept it off. I only access command centre via keyboard so preference would be to keep it disabled, but tbh not a big deal if I need to keep it enabled to access this feature, now that I _know_ that's what I need to do.

**Comment by penx** [comment]
Cool, thanks for trying and explaining :)

**Comment by bpasero** [comment]
One idea we could try is to add an icon next to the title, similar to what native titles do on macOS:

![image](https://github.com/microsoft/vscode/assets/900690/72dbd02f-f39f-49cb-b687-5955ea100684)

And then allow to click on that icon to bring up the menu. We would have to disable window dragging for this area though, not sure if it would annoy people.
