### ISSUE TITLE
Git Source Control does on work on RAM disks

### ISSUE THREAD

**Issue by kostya253** [microsoft/vscode#173526]
Type: <b>Bug</b>

Source Control stopped detecting Git repositories on Ram disk, could be related to the use of tryRealpath function, which does not handle RAM drives(IMDisk) properly.

Degradation from previous releases

Contact information: kostya253@gmail.com

VS Code version: Code 1.75.0 (e2816fe719a4026ffa1ee0189dc89bdfdbafb164, 2023-02-01T15:23:45.584Z)
OS version: Windows_NT x64 10.0.19042
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 9 5950X 16-Core Processor             (32 x 3394)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|127.95GB (106.37GB free)|
|Process Argv|. --crash-reporter-id 1da8ec55-6127-4ac2-918d-53e1505ba312|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
aws-toolkit-vscode|ama|1.62.0
dscodegpt|Dan|1.0.15
vscode-eslint|dba|2.2.6
gitlens|eam|13.2.0
prettier-vscode|esb|9.10.4
vscode-drawio|hed|1.6.6
vscode-peacock|joh|4.2.2
vscode-docker|ms-|1.23.3
quicktype|qui|12.0.46
code-spell-checker|str|2.16.0
intellicode-api-usage-examples|Vis|0.2.7
vscodeintellicode|Vis|1.2.30

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
azure-dev_surveyone:30548225
vscccc:30610679
pyindex848cf:30577861
nodejswelcome1cf:30587006
3biah626:30602489
pyind779cf:30657577
f6dab269:30613381
pythonsymbol12:30657548
2i9eh265:30646982

```

</details>

**Comment by lszomoru** [comment]
@kostya253, could you please download the latest Insiders release and see if that resolves the problem? Thank you!

```
Version: 1.76.0-insider (Universal)
Commit: c9e3ef865539061b5602c6b9ac6030332aa1ce70
Date: 2023-02-06T05:24:10.821Z
Electron: 19.1.9
Chromium: 102.0.5005.194
Node.js: 16.14.2
V8: 10.2.154.23-electron.0
OS: Darwin arm64 22.3.0
Sandboxed: Yes
```

**Comment by kostya253** [comment]
Hello Ladislau,

Thanks for quick response, I installed 

Version: 1.76.0-insider (user setup)
Commit: c9e3ef865539061b5602c6b9ac6030332aa1ce70
Date: 2023-02-06T05:24:33.398Z
Electron: 19.1.9
Chromium: 102.0.5005.194
Node.js: 16.14.2
V8: 10.2.154.23-electron.0
OS: Windows_NT x64 10.0.19042
Sandboxed: Yes

The issue still persists.

**Comment by lszomoru** [comment]
@kostya253, thank you very much for trying out Insiders. 
Could you please try the following so that we can narrow down the issue:
1. Start VS Code Insiders and open the folder/workspace
2. Open settings, and set the `git.openRepositoryInParentFolders` setting to `always`
3. Reload the window, and let me know if the git repository is being discovered 
4. Close all windows of VS Code Insiders
5. From the terminal run `code-insiders --log trace`
6.  Open the folder/workspace containing the git repository
7. Share the contents of the [git output window](https://code.visualstudio.com/docs/sourcecontrol/overview#_git-output-window)

**Comment by lramos15** [comment]
Marking verified based off author comment.
