### ISSUE TITLE
Better completion support for generics extending interface with optional fields

### ISSUE THREAD

**Issue by unional** [Microsoft/vscode#17351]
- VSCode Version: 1.8.0

```ts
interface X {
  a?: string
}

function boo(x: X): any
function foo<T extends X>(x: T): any
```
![image](https://cloud.githubusercontent.com/assets/3254987/21245098/87fb743c-c2d5-11e6-86c3-5d1ff5236955.png)

![image](https://cloud.githubusercontent.com/assets/3254987/21245105/906a3018-c2d5-11e6-88de-f1dcdef107f3.png)

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript#12968
