### ISSUE TITLE
Aarch64 Direct Download Link broken

### ISSUE THREAD

**Issue by nathanblair** [microsoft/vscode#173550]
Does this issue occur when all extensions are disabled?: N/A

- VS Code Version: N/A
- OS Version:
```
> cat /etc/alpine-release
3.17.0
```

Steps to Reproduce:

1. `curl -i https://code.visualstudio.com/sha/download?build=stable&os=cli-alpine-arm64`

The direct download link given at the VS Code Downloads page (`https://code.visualstudio.com/sha/download?build=stable&os=cli-alpine-arm64`) returns a 404:

```
HTTP/2 404
date: Mon, 06 Feb 2023 11:59:53 GMT
content-type: text/plain; charset=utf-8
content-length: 9
etag: W/"9-0gXL1ngzMqISxa6S1zx3F4wtLyg"
x-frame-options: SAMEORIGIN
x-xss-protection: 1; mode=block
x-content-type-options: nosniff
x-content-type-options: nosniff
x-powered-by: ASP.NET
strict-transport-security: max-age=31536000
x-azure-ref: 20230206T115953Z-tpx60yz2b13g5egszh5fguv48g00000002g000000000ckrq
x-cache: CONFIG_NOCACHE

Not Found
```

The link works if clicked manually through a browser - but then that sort of defeats the purpose of a direct download link (I should be able to copy that link and use it in my actual Alpine machine to get it to download).

**Comment by joaomoreno** [comment]
You need to quote that URL and to follow redirects:

```
curl --location --remote-name --remote-header-name "https://code.visualstudio.com/sha/download?build=stable&os=cli-alpine-arm64"
```
