### ISSUE TITLE
Whitespace padding for multiple cursors

### ISSUE THREAD

**Issue by Ambr051us** [microsoft/vscode#173554]
Type: <b>Feature Request</b>

I'd love to see an "extend all lines to furthest cursor" editor command, which would supercharge the multi-cursor feature for whitespace-based formatting.
What it should do is find the cursor that's the furthest from the beginning of the line it's in, and insert the correct number of tabs/spaces (preferably 2 different commands) before all the other cursors to bring them all exactly the same character distance from the start of the line. (If there's a line with more than 1 cursor in it, do nothing.)

VS Code version: Code 1.75.0 (e2816fe719a4026ffa1ee0189dc89bdfdbafb164, 2023-02-01T15:23:45.584Z)
OS version: Windows_NT x64 10.0.19044
Modes:
Sandboxed: No
Remote OS version: Linux x64 3.10.0-1160.25.1.el7.x86_64
Remote OS version: Linux x64 3.10.0-1160.25.1.el7.x86_64

**Comment by Ambr051us** [comment]
Illustration of what I mean:
Before
![image](https://user-images.githubusercontent.com/44926503/216974093-74b85ee1-9d2f-4f09-80b9-74337c18f2dd.png)
After
![image](https://user-images.githubusercontent.com/44926503/216973992-d5f815f1-d462-48f6-9560-a2a988affe40.png)

**Comment by ArturoDent** [comment]
There are a few `Align` extensions out there, where, for example, you could align on the `=` and it will pad with spaces.

**Comment by Ambr051us** [comment]
Oh, I haven't realized there already is an extension doing exactly this.
For future reference, it's [Cursor Align](https://marketplace.visualstudio.com/items?itemName=yo1dog.cursor-align)
