### ISSUE TITLE
JavaScript/TypeScript Debug Console treats warnings as errors

### ISSUE THREAD

**Issue by ShtibsDev** [microsoft/vscode#173545]
When debugging, the color of warnings is the same color of errors.
Even when trying to specify warning color, it will use the error color.
- Changing color theme doesn't fix it.
- Disabling all extensions doesn't fix it.

![image](https://user-images.githubusercontent.com/89642985/216956731-13c33cfe-12f3-4c1e-b883-93c1f7160759.png)

- VS Code Version: 1.75.0
- OS Version: Windows 11 Pro 22H2

Steps to Reproduce:

1. Open any JavaScript/TypeScript project
2. Start debug mode.
3. Generate a console warning in any way (`console.warn()` for example).

**Comment by roblourens** [comment]
There is actually no concept of warning-level output in the debug adapter protocol or the vscode debug console. That color token is misleading, it actually gets applied to internal messages and informational messages from debug extensions.
