### ISSUE TITLE
Video Wake Lock caused by release notes

### ISSUE THREAD

**Issue by maffe** [microsoft/vscode#173586]
I started VS code and went away. To my surprise the monitor was still on when I returned (it should turn off after a few minutes).

powercfg showed this was caused by VS Code:

```
powercfg /requests
DISPLAY:
[PROCESS] \Device\HarddiskVolume3\Users\…\AppData\Local\Programs\Microsoft VS Code\Code.exe
Video Wake Lock
```

I checked VS Code and noticed it was updated and showing the release notes which contain short videos. I think those should not cause the computer to stay unlocked and waste energy.

After closing the tab with the release notes, the video wake lock was gone.

Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.75.0 (user setup)
- OS Version: Windows_NT x64 10.0.19045

Steps to Reproduce:

1. Install VS Code via Microsoft Store
2. Receive an update (which will display the release notes automatically)
4. Scroll down until a video is displayed

**Comment by joaomoreno** [comment]
@deepak1556 Any chance we can disable this _Video Wake Lock_ from Electron?

**Comment by rct** [comment]
I just ran into this -- came back to my desk after 2 hours to all three monitors still on.

Anyway to bump this?

**Comment by deepak1556** [comment]
Wake lock is requested for the page when video is audible https://source.chromium.org/chromium/chromium/src/+/main:content/browser/media/media_web_contents_observer.cc;l=224-236;, if we were to mute the release notes page which is possible via https://github.com/electron/electron/blob/main/docs/api/web-contents.md#contentssetaudiomutedmuted then we can avoid requesting a wake lock.

**Comment by tobbi** [comment]
I'd like to give it a shot. Is there a way to get the `webContents` instance from within `ReleaseNotesManager`?

**Comment by deepak1556** [comment]
You would expose it as a helper from https://github.com/microsoft/vscode/blob/main/src/vs/platform/native/electron-main/nativeHostMainService.ts

**Comment by tobbi** [comment]
I think I may have a solution. I'll test it later if all the dependencies built.

Can you assign this issue to me, please?

**Comment by tobbi** [comment]
I seem to have hit a layers violation, at least that's why the CI build fails. Can you tell me what I need to do to fix the issue.

**Comment by tobbi** [comment]
If you guys want people to fix things for you, *maybe* it would be a good idea to have someone follow up. Especially for things marked as "good first issue".
