### ISSUE TITLE
Modified date not changed when saving existing file

### ISSUE THREAD

**Issue by sir-oliver** [microsoft/vscode#173553]
Type: <b>Bug</b>

I'm working on some files on our webserver that is connected to my Mac using SSHFS (mountainduck.io).

When i open a file, edit and save again, the contents of the file are updated correctly but the file modification timestamp is not updated.

When I use other software (Sublime Text, Textedit) to edit, the modification timestamp is updated correctly.

Of course I also tried an insider build to verify the problem.

VS Code version: Code 1.75.0 (Universal) (e2816fe719a4026ffa1ee0189dc89bdfdbafb164, 2023-02-01T15:24:42.903Z)
OS version: Darwin arm64 22.3.0
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M2 Pro (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|1, 1, 1|
|Memory (System)|32.00GB (14.04GB free)|
|Process Argv|--crash-reporter-id c1525acc-ccf4-456c-af83-dbaf257c91d6|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by bpasero** [comment]
From the description the issue sounds like a setup / configuration problem outside of VSCode and nothing VSCode itself could fix.

VSCode is built on top of a large number of components that are not maintained by the VSCode team directly. This includes:
* [Electron](https://github.com/electron/electron) as the cross platform UI framework
* [node.js](https://github.com/nodejs/node) for most integration into the OS
* [Chromium](https://bugs.chromium.org/p/chromium/issues/list) as runtime and rendering engine (HTML, CSS, JS)
* and after all, the operating system VSCode is running on

We also have a large community over at https://stackoverflow.com/questions/tagged/visual-studio-code to ask for advice.

Happy Coding!

**Comment by sir-oliver** [comment]
It is strange that the other editors update the file modification date correctly.
The problem happens just with VSCode.

**Comment by bpasero** [comment]
There is no VS Code remote involved here but a third party file system driver to connect via SSH right? So is it possible after all it could be related to that third party software in combination with the library we use for file writing (node.js)?

**Comment by sir-oliver** [comment]
thanks @bpasero for pointing that out.
i will contact iterate gmbh in bern.

**Comment by bpasero** [comment]
👍

**Comment by sir-oliver** [comment]
changing the configuration of the SSH file system driver i was ably to solve the problem.
thanks again @bpasero
