### ISSUE TITLE
VSCode not show `Not all code paths return a value.(7030) ` bug

### ISSUE THREAD

**Issue by xgqfrms** [microsoft/vscode#173524]
Does this issue occur when all extensions are disabled?: Yes/No
Yes

- VS Code Version: `1.75.0`
- OS Version:  macOS `13.1 (22C65)`

```md
Version: 1.75.0
Commit: e2816fe719a4026ffa1ee0189dc89bdfdbafb164
Date: 2023-02-01T15:24:42.903Z
Electron: 19.1.9
Chromium: 102.0.5005.194
Node.js: 16.14.2
V8: 10.2.154.23-electron.0
OS: Darwin x64 22.2.0
Sandboxed: No

```

Steps to Reproduce:

1. open vscode
2. create `test.ts` with belows codes

```ts
type Arr = number[][];

const arr: Arr = [[-1,0,1],[-1,-1,2]];

function test(arr: Arr) {
  arr.sort((a, b) => {
    if(a[0] !== b[0]) {
      return a[0] - b[0] > 0 ? 1 : -1
    } else if(a[0] === b[0] && a[1] !== b[1]) {
      return a[1] - b[1] > 0 ? 1 : -1
    } else if(a[0] === b[0] && a[1] === b[1]) {
      return a[2] - b[2] > 0 ? 1 : -1;
    }
    // fix: Not all code paths return a value.(7030) ❌
    // return a[2] - b[2] > 0 ? 1 : -1;
  });
  return arr;
}

test(arr);

```

## env

```sh
$ npx ts-node -vvv
ts-node v10.9.1 /Users/xgqfrms-mm/.npm/_npx/1bf7c3c15bf47d04/node_modules/ts-node
node v18.12.0
compiler v4.9.4 /Users/xgqfrms-mm/.npm/_npx/1bf7c3c15bf47d04/node_modules/typescript/lib/typescript.js
```

## compare screenshots

vscode ❌

<img width="1099" alt="image" src="https://user-images.githubusercontent.com/7291672/216913496-8eae5192-d343-4852-8638-52eb05af8bf5.png">

playground ✅ 

<img width="686" alt="image" src="https://user-images.githubusercontent.com/7291672/216910842-ad8de496-824c-4cb8-b8bd-dd6b96e3edb5.png">

https://www.typescriptlang.org/play

**Comment by mjbvz** [comment]
This is because you have different tsconfig settings between VS Code and the playground, specifically the `noImplicitReturns` setting

**Comment by xgqfrms** [comment]
After I enabled `noImplicitReturns`, it still does not work.

<img width="1321" alt="image" src="https://user-images.githubusercontent.com/7291672/217327834-469cd94b-a214-4a6d-9405-d5a9c58614ac.png">

https://www.typescriptlang.org/tsconfig#noImplicitReturns

**Comment by mjbvz** [comment]
Your file likely isn't part of that `tsconfig` project then.. Try running `TypeScript: go to project configuration` from the open file to check

**Comment by xgqfrms** [comment]
@mjbvz Thanks for your time!

I'm very Sorry for that, it's my config problem.

## solution 

> including the `src` folder in the `tsconfig.json` file

```json 
{
  "include": [
    // include folder ✅
    "src/**/*",
    "test/**/*"
  ],
}

```

<img width="1195" alt="image" src="https://user-images.githubusercontent.com/7291672/217435248-52a523e3-d050-48bd-83a6-80be37e4d3ce.png">
