### ISSUE TITLE
TS highlight issue with standard-js style

### ISSUE THREAD

**Issue by unional** [Microsoft/vscode#17352]
- VSCode Version: 1.8.0

![image](https://cloud.githubusercontent.com/assets/3254987/21245164/d2db9a2c-c2d5-11e6-9fcd-274eb2927a10.png)

Second "declare" highlight is wrong. Putting in ";" on the line above fixes this:
![image](https://cloud.githubusercontent.com/assets/3254987/21245177/f052f87a-c2d5-11e6-9d49-651c0acfb116.png)

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript-TmLanguage#384
