### ISSUE TITLE
Adding a trailing newline in format-on-type causes editor to scroll down unnecessarily

### ISSUE THREAD

**Issue by DanTup** [microsoft/vscode#173540]
When I type a semicolon at the end of this import statement, the editor unexpected scrolls down, making it seem like my code vanished:

![Feb-06-2023 10-48-01](https://user-images.githubusercontent.com/1078012/216952472-39d3eeae-dc82-4d1d-9d20-9aa1f6e4f241.gif)

The trigger for this seems to be that format-on-save adding a trailing newline:

```
 # type semicolon
 ==> {"jsonrpc":"2.0","method":"textDocument/didChange","params":{"textDocument":{"uri":"file:///Users/danny/Desktop/dart_samples/dart_many_parts/lib/many_parts.dart","version":70},"contentChanges":[{"range":{"start":{"line":0,"character":18},"end":{"line":0,"character":18}},"rangeLength":0,"text":";"}]},"clientRequestTime":1675680344883}
 
 # editor sends onTypeFormatting and the formatter returns a trailing newline for the file
 ==> {"jsonrpc":"2.0","id":292,"method":"textDocument/onTypeFormatting","params":{"textDocument":{"uri":"file:///Users/danny/Desktop/dart_samples/dart_many_parts/lib/many_parts.dart"},"position":{"line":0,"character":19},"ch":";","options":{"tabSize":2,"insertSpaces":true,"trimTrailingWhitespace":true,"insertFinalNewline":true}},"clientRequestTime":1675680344885}
 <== {"id":292,"jsonrpc":"2.0","result":[{"newText":"\n","range":{"end":{"character":19,"line":0},"start":{"character":19,"line":0}}}]}

 # editor adds the newline
 ==> {"jsonrpc":"2.0","method":"textDocument/didChange","params":{"textDocument":{"uri":"file:///Users/danny/Desktop/dart_samples/dart_many_parts/lib/many_parts.dart","version":71},"contentChanges":[{"range":{"start":{"line":0,"character":19},"end":{"line":0,"character":19}},"rangeLength":0,"text":"\n"}]},"clientRequestTime":1675680344893}
```

I don't think there's anything wrong with the formatter adding the trailing newline and I agree it's slightly ambiguous about where the cursor should end up when there's an insert at its offset, but I don't see any reason for the editor to scroll here, it's just confusing and in this case 95% of the screen is blank space that isn't part of the document content anyway.

**Comment by n0hack** [comment]
I'm having the same problem.

**Comment by mikemklee** [comment]
Did you every figure this out?
I noticed this happening after setting up a WSL environment from scratch.

**Comment by thomaskvnze** [comment]
I have the same issue with formatOnSave. Whenever I hit cmd+s on macos, the view scrolls one line down.

**Comment by shinebayar-g** [comment]
> I have the same issue with formatOnSave. Whenever I hit cmd+s on macos and the formatter inserts a new line, the view scrolls one line down.

This is exactly what is happening with me. https://github.com/prettier/prettier-vscode/issues/2880

**Comment by jrieken** [comment]
Using a fake dart formatter (below) doesn't allow me to reproduce this. @DanTup Does this still happen in the wild?

```ts
vscode.languages.registerOnTypeFormattingEditProvider('dart', new class implements vscode.OnTypeFormattingEditProvider {
		provideOnTypeFormattingEdits(document: vscode.TextDocument, position: vscode.Position, ch: string, options: vscode.FormattingOptions, token: vscode.CancellationToken): vscode.ProviderResult<vscode.TextEdit[]> {
			const pos = document.lineAt(position.line).range.end
			return [vscode.TextEdit.insert(pos, '\n')]
		}
	}, ';')
```

**Comment by LucasOe** [comment]
The editor still scrolls for me when final newlines are inserted by a formatter. When newlines are inserted using the `"files.insertFinalNewline": true` setting, for example in a plain text file, the editor doesn't scroll. But when a formatter is used this behaviour changes. I tested this with Prettier and Markdownlint.

**Comment by DanTup** [comment]
That's odd, I tested it again and it's definitely no longer happening for me:

Uploading format.mp4…

I checked the LSP traffic to ensure the newline came from the formatter, and it did:

```
==> {"jsonrpc":"2.0","id":123,"method":"textDocument/onTypeFormatting","params":{"textDocument":{"uri":"file:///C%3A/Dev/Google/dart-sdk/sdk/pkg/dds/test/dap/integration/danny.dart"},"position":{"line":0,"character":12},"ch":";","options":{"tabSize":2,"insertSpaces":true,"trimTrailingWhitespace":true,"insertFinalNewline":true}},"clientRequestTime":1705401121098}
<== {"id":123,"jsonrpc":"2.0","result":[{"newText":"\n","range":{"end":{"character":12,"line":0},"start":{"character":12,"line":0}}}]}
```

**Comment by LucasOe** [comment]
Okay, I figured out that this only happens when you are scrolled past the last line. If you set `editor.padding.bottom` to a high number, or if you set `editor.scrollBeyondLastLine` to true and scroll down, the editor scrolls if a newline is inserted by a formatter.
