### ISSUE TITLE
"No symbols found" for Markdown files

### ISSUE THREAD

**Issue by geestarr** [microsoft/vscode#173589]
Since v 1.74.x I have not been able to view outlines of Markdown files.

Steps to reproduce:

- Open Markdown file.
- Look at Outline panel

Expected behavior

- Outline appears in Outline Panel

Actual behavior

- Panel shows message "No symbols found in document [DOCNAME]"

VS Code: v 1.75.0 
Mac OS: Ventura 13.1 running on Apple M1

(Same issue using Universal and Apple Silicon versions)

Note that this issue does not occur when using the "Visual Studio Code -- Insiders" version. But has been happening for me on the "production" branch for months.

**Comment by mjbvz** [comment]
I suspect you've disabled the built-in markdown extension that provides these. Search `@builtin markdown`  in the extensions view to check  that `Markdown Language Features` is enabled

**Comment by geestarr** [comment]
@mjbvz your suspicion was spot on. Enabling that setting solved the issue straightaway. Thanks much for this!
