### ISSUE TITLE
Support format for handlebars file

### ISSUE THREAD

**Issue by sulhome** [Microsoft/vscode#1735]
although VS Code recognize that the markup is indeed handlebars, it is unable to format it. 
So format code option does nothing

**Comment by bpasero** [comment]
It is currently just not implemented.

**Comment by sulhome** [comment]
@bpasero thank you

**Comment by gpluta** [comment]
@bpasero is it on the roadmap though?

**Comment by egamma** [comment]
@gpluta not on the immediate roadmap and it depends on contributions from the community.

**Comment by gpluta** [comment]
@egamma Thanks for clarifying!

**Comment by v3ss0n** [comment]
Ember Handlebar templates are having very bad format in VSCode , that is only one thing i am going back to atom.
All the existing extensions can't do it well too. Would be very nice vscode look into it. Over a year now.

**Comment by mjbvz** [comment]
Duplicate of #7011 / #32916 (I know this issue is older, but those two issue seem to have more relevant information on them)
