### ISSUE TITLE
Hide sidebars first and then go to full screen when toggle Zen mode

### ISSUE THREAD

**Issue by rebornix** [Microsoft/vscode#17353]
- VSCode Version: 1.9.0-Insiders
- OS Version: macOS

Currently when we toggle Zen mode, the window goes to Full Screen mode first, which means the editor, activity bar and side bar become slightly larger in this period. Then we'll hide activity bar and side bar, then activity bar and side bar shrink to zero width and the editor becomes slightly larger again. IMHO, hiding activity bar and sidebars first and then go to Full Screen mode may make it more smooth as it looks like that the editor is becoming larger and eats all other parts of VS Code and the desktop.

**Comment by isidorn** [comment]
@rebornix ok I changed the order in the code. Let me know if it feels smoother now :)
