### ISSUE TITLE
Test: show me the trace of the failure

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#173533]
Maybe I am missing something, but when a test fails in a helper method where we do assertions, it is impossible for me to figure out where it failed from.

Here is an example:
* open `dialog.test.ts`
* make any change in the `massageMessageBoxOptions` test that will cause an assertion failure
* run the test via the test decoration
* you end up here:

<img width="1429" alt="image" src="https://user-images.githubusercontent.com/900690/216937638-becc22c0-448b-451f-8b72-0d1ce1a42866.png">

I wish I could navigate from here to the stack above where the method was called from.

**Comment by gjsjohnmurray** [comment]
Perhaps #159339 is related

**Comment by connor4312** [comment]
Yea, I think I'll merge into there
