### ISSUE TITLE
Sometimes Interactive Window doesn't display the input code.

### ISSUE THREAD

**Issue by forestGoroli** [microsoft/vscode#173590]
### Applies To

- [ ] Notebooks (.ipynb files)
- [X] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

Simplified reproduction method for my own use.

1. Prepare many cells (more than 5?) and Run from "Jupyter: Run All Cells."
2. Run the code from the interactive cell a few times (around  5).
3. Sometimes window doesn't display the input code. (Output is still showing.)

The attached image is an example of this bug.

1. I prepared the code consisting of 9 cells (1 for markdown, 8 for dummy code).
2. Then I typed "print('aa')" into the interactive window 5 times.
3. 3 / 5 of the input cells don't display my code.
![2023-02-04 161940](https://user-images.githubusercontent.com/51478433/216755273-f8cc8225-99d1-42c8-bab8-be195ef72612.jpg)
![2023-02-04 162048](https://user-images.githubusercontent.com/51478433/216755278-281e7eab-6c22-44d0-968e-649890b48726.jpg)

I've also used the interactive window for debugging the short code, so not displaying my input code is a little unusable.

### VS Code Version

Version: 1.75.0 (user setup) Commit: e2816fe719a4026ffa1ee0189dc89bdfdbafb164 Date: 2023-02-01T15:23:45.584Z Electron: 19.1.9 Chromium: 102.0.5005.194 Node.js: 16.14.2 V8: 10.2.154.23-electron.0 OS: Windows_NT x64 10.0.19045 Sandboxed: No

### Jupyter Extension Version

v2023.1.2000312134

### Running Jupyter locally or remotely?

Local

**Comment by rebornix** [comment]
The fix will be available in tomorrow's Insiders and also the next Stable recovery build (in a couple of days).
