### ISSUE TITLE
Feature Request: Auto-trigger tasks before Git commit

### ISSUE THREAD

**Issue by travislaynewilson** [Microsoft/vscode#17355]
- VSCode Version: 1.8.0
- OS Version: Windows 10

We've always needed the ability to run predetermined tasks before a Git commit automatically. If we could auto-run tasks like this, we could automate build processes and other vital tasks when using client-side bundling tools like Webpack or other systems that we can't run in CI.

**Comment by kaiwood** [comment]
You might want to take a look at Git hooks, what you describe is exactly the use case for them.

As a starting point:

https://git-scm.com/docs/githooks
https://git-scm.com/book/en/v2/Customizing-Git-Git-Hooks

**Comment by dbaeumer** [comment]
@travislaynewilson actually VS Code dev team does exactly this: we use Git hooks to run code before commits which check our source code for hygiene things.

**Comment by joaomoreno** [comment]
@kaiwood Is exactly right. This is a git feature, not VS Code. What happens to your developers that don't use VS Code for development?
