### ISSUE TITLE
VS Code for android

### ISSUE THREAD

**Issue by BhJaipal** [microsoft/vscode#173516]
Can you please try to make a version of VS Code for android. I don't have any problem if it have less features than that of Linux, Mac and Windows version. 
I know it would be hard for you to create such a powerful Code editor for android. 
But if it is possible please give it a little try.

Thank you

**Comment by gintominto5329** [comment]
It wont be a tough task, as VSC is a JavaScript application, just a new compilation target, just the problem could be screen size, but tablets are also android devices, so no problem,

good suggestion

**Comment by BhJaipal** [comment]
Thank you
So, should I close this issue as complete?

**Comment by gintominto5329** [comment]
No,

Im not a member of VSCode team, 

but suggestion is good, and not very tough, but quite easy, because of JavaScript
