### ISSUE TITLE
[json] Inconsistency between files.insertFinalNewline and Format Document

### ISSUE THREAD

**Issue by andrewmthomas87** [microsoft/vscode#17359]
- VSCode Version: Code 1.8.0 (38746938a4ab94f2f57d9e1309c51fd6fb37553d, 2016-12-13T17:38:28.425Z)
- OS Version: Darwin x64 15.6.0
- Extensions:

|Extension|Author|Version|
|---|---|---|
|RelativePath|jakob101|0.8.0|
|copy-relative-path|alexdima|0.0.1|
|Theme-Dracula|gerane|0.0.2|
|Theme-TomorrowKit|ms-vscode|0.1.3|

---

Steps to Reproduce:

1. Set `files.insertFinalNewline` to `true`
2. Format Document on JSON file (likely several file types)--this removes the trailing newline
3. Save file--this adds back trailing newline

Format Document should take into consideration the `insertFinalNewline` option

**Comment by kieferrm** [comment]
//cc @aeschli FYI

**Comment by jonathansimmons** [comment]
This issue is not just a json problem. It exists in ruby, scss, and others. Bummer this has just been ignored for two years.

**Comment by philwilliammee** [comment]
I have this issue too. With php files using phpintelliphense the issue seams to be coming from format on save
