### ISSUE TITLE
Extension Untrusted

### ISSUE THREAD

**Issue by anubhav9454** [microsoft/vscode#173551]
Does this issue occur when all extensions are disabled?: No

- VS Code Version: 1.75
- OS Version: RHEL 7

Steps to Reproduce:

1. Behind the corporate firewall, install any extension manually, i.e., using .vsix file.
2. The vsix file is downloaded from official Visual Studio Marketplace.
3. Here I am trying to install Python and Pylance extension.
4. We are installing the extension on the remote server using Remote-SSH 
5. The error throwing is Untrusted, Untrusted, Untrusted.
![image](https://user-images.githubusercontent.com/104710170/216966010-7a0148e9-0fc3-483f-85a2-2380119900ed.png)

**Comment by anubhav9454** [comment]
I am currently using latest VS code only!

**Comment by roblourens** [comment]
https://github.com/microsoft/vscode/issues/173327
