### ISSUE TITLE
Github Education - VSCode API rate limiting issue

### ISSUE THREAD

**Issue by Krithika-suri** [microsoft/vscode#173645]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: NA
- OS Version: NA

Steps to Reproduce:

The github education team sees about [85k+](https://data.githubapp.com/sql/share/d647ed34) calls from Visual-studio-code in an hour for api/user. This is quite unusual and since we are rate limiting anyway, it is not an immediate issue.  

From initial discussions with @TylerLeonhardt I understand that the call is made only for telemetry and has no impact on the user. So, raising this bug, if we can find a better way to do telemetry without having to rate limit.  This [issue](https://github.com/github/education-web/issues/7783) here shows some more details.

**Comment by Krithika-suri** [comment]
@TylerLeonhardt , can you please help me understand what is the likelihood of this work getting prioritised and by when can we expect to resolve this issue.

**Comment by TylerLeonhardt** [comment]
@Krithika-suri I wasn't able to get to it this week during our allocated debt time so I will try again to make time early April.
