### ISSUE TITLE
vscode ignores `editor.formatOnSave = false` set for language

### ISSUE THREAD

**Issue by soredake** [microsoft/vscode#173689]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.75.0
- OS Version: Windows 11 Pro

Steps to Reproduce:

1. Add this to your user settings:
```
"editor.formatOnSave": true,
  "[properties]": {
    "editor.defaultFormatter": "foxundermoon.shell-format",
    "editor.formatOnSave": false
  },
```
2. Create file.conf, put this code in this file:
```
profile-cond=p["estimated-vf-fps"]<50
```
4. Press ctrl+s
5. It will format it to this despite format on save is turned off:
![изображение](https://user-images.githubusercontent.com/5204968/217281891-04de89e5-668e-4cb9-bf73-a08abd00e1b7.png)

**Comment by jrieken** [comment]
This is a problem with the extension. It doesn't register itself as formatter but just hooks into saving (and happens to run a formatting operation as part of that). We all the APIs to do it right, I have blogged about this (https://code.visualstudio.com/blogs/2016/11/15/formatters-best-practices) but the knowledge hasn't spread yet
