### ISSUE TITLE
Poor contrast for workspace search and errors in notebooks in the Light+ V2 theme

### ISSUE THREAD

**Issue by yy0931** [microsoft/vscode#173663]
Type: <b>Bug</b>
In addition to https://github.com/microsoft/vscode/issues/173255, https://github.com/microsoft/vscode/issues/173238, these elements are also hard to see in the Light+ V2 theme.

- [ ] Active (focused) workspace search results on methods:
![image](https://user-images.githubusercontent.com/54441600/217204736-3c99fd74-ce91-4c6c-a57f-a29c0ebb7e39.png)

- [x] ~~Error messages in Jupyter notebooks:~~ Fixed
![image](https://user-images.githubusercontent.com/54441600/217205360-4856562a-67e8-4aa8-8c2b-5672912e7538.png)

![image](https://user-images.githubusercontent.com/54441600/217205432-7ef00f20-0a40-46af-b97f-e586b3f71985.png)

VS Code version: Code - Insiders 1.76.0-insider (c9e3ef865539061b5602c6b9ac6030332aa1ce70, 2023-02-06T05:24:21.999Z)
OS version: Linux x64 5.15.0-58-generic
Modes:
Sandboxed: Yes

**Comment by daviddossett** [comment]
@rebornix do you know what the notebook output token would be? I don't think I changed anything specific to notebooks in these new themes.

**Comment by daviddossett** [comment]
Perfect, thanks for checking. Feel free to close if it looks all good in the next Insiders update.

**Comment by rebornix** [comment]
@daviddossett as @yy0931 pointed out we are using terminal colors.

**Comment by UncleGoogle** [comment]
Even worse for unsued python imports
![image](https://user-images.githubusercontent.com/12197825/220347091-520fc9be-9006-4086-82d6-26f43eec6000.png)

**Comment by daviddossett** [comment]
Yep, this ended up just being a bad color assignment. Should be fixed now.
