### ISSUE TITLE
VSCode incorrectly assumes that it's running under an administrator when it's not

### ISSUE THREAD

**Issue by montoner0** [microsoft/vscode#173698]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.75.0 (user setup)
- OS Version: Windows 10 22H2

Steps to Reproduce:

1. Run VSCode under an unprivileged user with UAC disabled
2. VSCode detects the user as an administrator thus effectively disables updates

I'm working under an unprivileged user account and can't elevate it because UAC is disabled, though VSCode shows that it's running under admin.
I cannot reproduce this behavior on a clean VM with disabled UAC so it's probably some issue with my current machine. I also tried to remove `%userprofile%\.vscode` folder but it didn't help.

**Comment by joaomoreno** [comment]
@bpasero How is admin detection done?

**Comment by bpasero** [comment]
@joaomoreno via a native module: https://github.com/arkon/native-is-elevated

**Comment by montoner0** [comment]
I've just checked the code from the module on my machine and it falsely shows that the process is elevated.

**Comment by joaomoreno** [comment]
@montoner0 I suggest you file an issue on https://github.com/arkon/native-is-elevated, thanks!
