### ISSUE TITLE
typings.json schema is not working on vscode

### ISSUE THREAD

**Issue by unional** [Microsoft/vscode#17363]
- VSCode Version: 1.8.0

From https://github.com/SchemaStore/schemastore/issues/257

![image](https://cloud.githubusercontent.com/assets/3254987/21248288/dd54a72c-c2ea-11e6-9bcb-efe52bd1bac6.png)

Could it because of `$schema` is ahead of `title`?
https://github.com/SchemaStore/schemastore/blob/master/src/schemas/json/typings.json#L2

Compare to others, (e.g. tsconfig.json), it's the other way around:
https://github.com/SchemaStore/schemastore/blob/master/src/schemas/json/tsconfig.json#L2

I understand that it's json and order should not matter, but I can't see other reason for it.
Can I make a PR to give it a try? Or do you know how to get a local copy and try it out?

**Comment by mjbvz** [comment]
As far as I know, we do not specify a schema for `typings.json` files at all. The `$schema` completion that you see is just a generic completion that we provide for any json file without an associated schema.

Given that, I believe this issue would be a request for us to defined the schema for `typings.json` files.
