### ISSUE TITLE
Theme Issue - White on Light Gray

### ISSUE THREAD

**Issue by hediet** [microsoft/vscode#173679]
![image](https://user-images.githubusercontent.com/2931520/217260757-e91a6542-efcf-455e-8c7a-37461dafc1db.png)

Happens when something else has focus and hovering on a selected item.

**Comment by andreamah** [comment]
Hmm.. I can't seem to repro. My steps are (in :
1. search something
2. click on a result
3. focus the editor
4. hover the result that I selected in step 2

Am I missing something?

**Comment by hediet** [comment]
Happens all the time for me:

![Code_-_Insiders_lvBZLQWMyc](https://user-images.githubusercontent.com/2931520/217504490-bd505785-0515-4dda-a40c-ff91173d6af3.gif)

**Comment by andreamah** [comment]
Is it happening in the latest insiders? Might have been fixed by #173832
