### ISSUE TITLE
"Auto Detect Color Scheme" not working properly

### ISSUE THREAD

**Issue by jelitter** [microsoft/vscode#173670]
Type: <b>Bug</b>

Having the setting "Auto Detect Color Scheme" checked, and then restarting Visual Studio Code, will result in the wrong scheme being selected.

For instance, my OS (Windows 11) is set to Light theme. When I restart Visual Studio Code, it defaults to dark mode. Then I have to uncheck and check that setting again, to get VS Code to Light mode as expected.

The same thing happens in the afternoon when my OS is set to dark mode.

This issue was also described by other users,  and closed with a fix, but issue persists: https://github.com/microsoft/vscode/issues/126823

Thanks!

VS Code version: Code 1.75.0 (e2816fe719a4026ffa1ee0189dc89bdfdbafb164, 2023-02-01T15:23:45.584Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: No

**Comment by Lapsusone** [comment]
I have the same issue on macOS on multiple machines with Settings Sync enabled. I have to uncheck and recheck the auto detect color scheme checkbox to make it see there was a change.

**Comment by hamirmahal** [comment]
> I have the same issue on macOS on multiple machines with Settings Sync enabled. I have to uncheck and recheck the auto detect color scheme checkbox to make it see there was a change.

I have the same issue, and what you mentioned is how I resolve it.

**Comment by hamirmahal** [comment]
This might be related to https://github.com/microsoft/vscode/issues/173770.

**Comment by hamirmahal** [comment]
This might also be related to https://github.com/microsoft/vscode/issues/180023.

**Comment by hamirmahal** [comment]
I'm on Windows 10 and I use https://github.com/AutoDarkMode/Windows-Auto-Night-Mode.

![image](https://github.com/microsoft/vscode/assets/43425812/2e274802-fb79-4e3c-989e-747de7003d0e)
