### ISSUE TITLE
Please change Setting Up Visual Studio Code Mac OSX Section

### ISSUE THREAD

**Issue by mindcool** [Microsoft/vscode#1736]
To start code from terminal you should edit ~/.bash_profile and add the following line of code to that file

function code () { VSCODE_CWD="$PWD" open -n -b "com.microsoft.VSCode" --args $*; }

Please add to this document

to make those changes effective you should either write
source ~/.bash_profile or just . ~/.bash_profile

**Comment by bpasero** [comment]
:+1:

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode-docs/blob/master/docs/editor/setup.md
