### ISSUE TITLE
这个版本的lint根本用不了了,es6的拓展符号开始报错,单词也莫名其妙报错...我要退回上一个版本了

### ISSUE THREAD

**Issue by kooboo-chenhai** [Microsoft/vscode#17367]
- VSCode Version: Code 1.8.0 (38746938a4ab94f2f57d9e1309c51fd6fb37553d, 2016-12-13T17:45:32.595Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

|Extension|Author|Version|
|---|---|---|
|vscode-eslint|dbaeumer|1.2.1|
|vscode-babel-coloring|dzannotti|0.0.4|

---

Steps to Reproduce:

1.
2.

**Comment by kieferrm** [comment]
@rebornix ?

**Comment by rebornix** [comment]
He is saying eslint doesn't work and he can't use es6 symbols. The version he is using is 1.8.0.

**Comment by rebornix** [comment]
@kooboo-chenhai 请问你可以提供一个截图吗？

> es6的拓展符号开始报错,单词也莫名其妙报错

你是指 eslint 提示这些符号有错误？

**Comment by kooboo-chenhai** [comment]
@rebornix 是的,不过今天倒是没有报错了,不知道是因为我更新了最新版本的lint还是说我重启电脑后就好了.后面有情况我会@你们的
