### ISSUE TITLE
After update cannot open terminal on remote host

### ISSUE THREAD

**Issue by jordangarrison** [microsoft/vscode#173600]
Type: <b>Bug</b>

I have been using a nixos server for well over a year to do remote developement. After the latest update I cannot open the terminal. I recieve a rather vague message and can't find any related logs: The terminal process failed to launch: A native exception occurred during launch (posix_spawn failed: No such file or directory).

VS Code version: Code 1.75.0 (e2816fe719a4026ffa1ee0189dc89bdfdbafb164, 2023-02-01T15:26:31.005Z)
OS version: Darwin arm64 22.2.0
Modes:
Sandboxed: No
Remote OS version: Linux x64 5.15.85

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|6, 4, 4|
|Memory (System)|32.00GB (0.05GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: endeavour|
|OS|Linux x64 5.15.85|
|CPUs|AMD Ryzen 9 3900X 12-Core Processor (12 x 3799)|
|Memory (System)|39.19GB (38.14GB free)|
|VM|0%|
</details><details><summary>Extensions (28)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|3.0.2
nestjs|ash|1.4.2
emojisense|bie|0.9.1
systemd-unit-file|coo|1.0.6
javascript-ejs-support|Dig|1.3.1
file-icons|fil|1.0.29
auto-close-tag|for|0.5.14
remotehub|Git|0.50.0
crontab-syntax-highlight|hog|0.0.2
output-colorizer|IBM|0.1.2
fuzzy-search|jac|0.0.3
dotenv|mik|1.0.1
jupyter-keymap|ms-|1.0.0
remote-containers|ms-|0.275.1
remote-ssh|ms-|0.96.0
remote-ssh-edit|ms-|0.84.0
remote-wsl|ms-|0.75.1
vscode-remote-extensionpack|ms-|0.23.0
azure-repos|ms-|0.26.0
remote-explorer|ms-|0.2.0
remote-repositories|ms-|0.28.0
vcl|tho|0.1.2
errorlens|use|3.6.0
vim|vsc|1.24.3
vspacecode|VSp|0.10.13
whichkey|VSp|0.11.3
propertylist|zho|0.0.2
material-theme|zhu|3.15.6

(5 theme extensions excluded)

</details>

**Comment by jordangarrison** [comment]
I was able to restore functionality by downgrading back to the previous release 1.74.x

**Comment by tals** [comment]
Same issue here

**Comment by tals** [comment]
Same issue here.
Seems like the [typical hacks NixOS users apply](https://nixos.wiki/wiki/Visual_Studio_Code#Remote_SSH) started breaking

**Comment by CHENGY12** [comment]
Same, cannot add new terminals. A sudden issue.

**Comment by computercam** [comment]
Same issue in nixos

Downgrading to 1.74.x resolves the issue

**Comment by Maxwell2022** [comment]
after downgrading to 1.74 vscode is not detecting my devcontainer configuration :/

**Comment by deepak1556** [comment]
It would be great if you can provide a minimal nixOS container configuration that would help us repro the issue. Thanks!

**Comment by davystrong** [comment]
I had the same issue when attempting to connect to an Ubuntu Apptainer container on a remote service.

**Comment by farcaller** [comment]
To make the issue worse, if the secondary side bar had the terminal tab in focus, it will hide immediately, not allowing to switch to any other tab.

**Comment by libjared** [comment]
For setups that use `nixos-vscode-server`, see msteen/nixos-vscode-server#41

**Comment by senyai** [comment]
Me pressing `ctrl+~` after vscode update (Funtoo linux):
![pyminimg-1676227279346](https://user-images.githubusercontent.com/76137/218330405-a4089f59-2ec8-4edd-a62e-200f0f649ba8.gif)

**Comment by libjared** [comment]
@senyai
The offender might be `~/.vscode-server/bin/*/node_modules/node-pty/build/Release/spawn-helper`.
1. Does that binary have the correct +x permissions?
2. What happens when you run that binary?
3. What is the output of `ldd` against that binary?

**Comment by senyai** [comment]
@libjared you are exactly right! +x fixed the issue. Will report to os maintainers. Anyway, a message saying what command gave us "permission denied"/"No such file or directory" would be appreciated.

**Comment by Weathercold** [comment]
On NixOS it seems that the permissions are right, yet the issue still occurs.
```fish
> ls -l /nix/store/yby98z02cbc703wqi9i9vch7fj3xxnfy-vscode-insiders-1.76.0-insider/lib/vscode/resources/app/node_modules/node-pty/build/Release/spawn-helper 
.r-xr-xr-x 40k root 31 Dec  1969 /nix/store/yby98z02cbc703wqi9i9vch7fj3xxnfy-vscode-insiders-1.76.0-insider/lib/vscode/resources/app/node_modules/node-pty/build/Release/spawn-helper
                                                                                                                                                          
> ls -l /nix/store/yby98z02cbc703wqi9i9vch7fj3xxnfy-vscode-insiders-1.76.0-insider/lib/vscode/resources/app/node_modules.asar.unpacked/node-pty/build/Release/spawn-helper 
.r-xr-xr-x 40k root 31 Dec  1969 /nix/store/yby98z02cbc703wqi9i9vch7fj3xxnfy-vscode-insiders-1.76.0-insider/lib/vscode/resources/app/node_modules.asar.unpacked/node-pty/build/Release/spawn-helper
                                                                                                                                                             
> ls -l /nix/store/yby98z02cbc703wqi9i9vch7fj3xxnfy-vscode-insiders-1.76.0-insider/lib/vscode/resources/app/node_modules.asar/node-pty/build/Release/spawn-helper 
.r-xr-xr-x 40k root 31 Dec  1969 /nix/store/yby98z02cbc703wqi9i9vch7fj3xxnfy-vscode-insiders-1.76.0-insider/lib/vscode/resources/app/node_modules.asar/node-pty/build/Release/spawn-helper
```

**Comment by Weathercold** [comment]
Nevermind, https://github.com/NixOS/nixpkgs/pull/214666 fixed it.

**Comment by libjared** [comment]
I think the fault ultimately lies with the node-pty package for assuming an ELF interpreter would always be present at `/lib64/ld-linux-x86-64.so.2`.
VSCode devs may be able to detect/report/workaround the error in `ptyHostMain.js` around where `spawn()` is called.

**Comment by deepak1556** [comment]
Given this is addressed in nixos-vscode-server, closing as resolved.
