### ISSUE TITLE
Washed Out screen after update

### ISSUE THREAD

**Issue by reignwestry** [microsoft/vscode#173608]
Type: <b>Bug</b>

Editor flickers between washed out and clear on typing and focus

VS Code version: Code - Insiders 1.76.0-insider (c9e3ef865539061b5602c6b9ac6030332aa1ce70, 2023-02-06T05:24:33.398Z)
OS version: Windows_NT x64 10.0.22623
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.83GB (6.64GB free)|
|Process Argv|--crash-reporter-id 211dc24a-5223-4d72-831b-bb34ecc0a488|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (79)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|3.0.2
genymotion|ABe|1.1.0
project-manager|ale|12.7.0
code-gnu-global|aus|0.2.2
color-info|bie|0.7.2
markdown-emoji|bie|0.3.0
vscode-intelephense-client|bme|1.9.5
npm-intellisense|chr|1.4.4
path-intellisense|chr|2.8.4
dartsass|cod|0.9.2
gitignore|cod|0.9.0
oregator|csa|1.0.8
dart-code|Dar|3.58.0
flutter|Dar|3.58.0
vscode-eslint|dba|2.4.0
npm-browser|den|1.1.4
githistory|don|0.6.19
java-debug|DSn|0.0.2
es7-react-js-snippets|dsz|4.4.3
gitlens|eam|13.2.0
vscode-npm-script|eg2|0.3.29
prettier-vscode|esb|9.10.4
git-project-manager|fel|1.8.2
vscode-firefox-debug|fir|2.9.8
auto-close-tag|for|0.5.14
auto-rename-tag|for|0.1.10
dirtyswp|for|0.9.6
kotlin|fwc|0.2.26
html-slim-scss-css-class-completion|gen|1.7.8
live-sass|gle|5.5.1
vscode-drawio|hed|1.6.6
rest-client|hum|0.25.1
open-in-browser|igo|1.0.2
vscode-browser-sync|jas|1.3.1
browsersync|jer|2.2.2
vscode-wordpress-hooks|joh|1.1.0
vscode-sshfs|Kel|1.25.0
Kotlin|mat|1.7.1
vscode-language-babel|mgm|0.0.36
vscode-scss|mrm|0.10.0
csharp|ms-|1.25.4
remote-containers|ms-|0.277.0
remote-ssh|ms-|0.97.2023020215
remote-ssh-edit|ms-|0.84.0
remote-wsl|ms-|0.75.1
vscode-remote-extensionpack|ms-|0.23.0
powershell-preview|ms-|2023.2.0
remote-explorer|ms-|0.3.2023020609
color-highlight|nau|2.5.0
vscode-drawio-plugin-mermaid|nop|0.1.5
vscode-drawio-plugin-rtl|nop|0.0.7
vscode-drawio-plugin-wavedrom|nop|0.0.1
prettier-standard-vscode|num|1.0.2
material-icon-theme|PKi|4.23.1
java|red|1.14.0
LiveServer|rit|5.7.9
vs-code-prettier-eslint|rve|5.0.4
glassit|s-n|0.2.5
vscode-java-debug-ext|san|1.0.7
prettier-vscode|Sim|2.0.7
vsc-quokka-statusbar|ske|1.3.6
shell-launcher|Tyr|0.4.1
intellicode-api-usage-examples|Vis|0.2.7
vscodeintellicode|Vis|1.2.30
vscode-java-debug|vsc|0.48.0
vscode-java-dependency|vsc|0.21.1
vscode-java-pack|vsc|0.25.7
vscode-java-test|vsc|0.37.1
vscode-maven|vsc|0.40.4
quokka-vscode|Wal|1.0.524
cors-browser|Wsc|1.0.11
JavaScriptSnippets|xab|1.8.0
ReactSnippets|xab|2.4.0
php-debug|xde|1.31.0
php-pack|xde|1.0.3
blade-runner|yuk|1.0.0
markdown-all-in-one|yzh|3.5.0
vscode-plugin-drawio|zhf|1.0.18
php-intellisense|zob|1.0.13

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30422396
pythontb:30258533
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscod805:30301674
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30404738
cppdebug:30492333
vsclangdf:30492506
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30618038
pylantcb52:30590116
pyindex848:30611229
nodejswelcome1:30587009
pyind779:30611226
pythonsymbol12:30651887
showlangstatbar:30657381

```

</details>

**Comment by reignwestry** [comment]
![image](https://user-images.githubusercontent.com/18231550/217076048-0054af69-3d82-4c90-a3aa-cf191d23544f.png)

**Comment by deepak1556** [comment]
Merging to https://github.com/microsoft/vscode/issues/124226

Please disable hw acceleration as a workaround https://code.visualstudio.com/updates/v1_40#_disable-gpu-acceleration
