### ISSUE TITLE
${selectedText} resloved as a normal string in workbench.action.findInFiles

### ISSUE THREAD

**Issue by PeterYangTW** [microsoft/vscode#173653]
I try to add a keybinding `workbench.action.findInFiles`  with ${selectedText}.
but it will resloved as a normal string.

Steps to Reproduce:

![A](https://user-images.githubusercontent.com/33244172/217187468-6c57263d-e17f-4fa5-94d9-8f4d0ae1aa3e.gif)

Version: 1.75.0 (user setup)
Commit: e2816fe719a4026ffa1ee0189dc89bdfdbafb164
OS: Windows_NT x64 10.0.19045
Sandboxed: No

**Comment by andreamah** [comment]
What does your keybinding look like?

**Comment by andreamah** [comment]
@alexr00 would you happen to know why the variable isn't resolving to a value here? Is there something that the command must contain to resolve variables?

**Comment by alexr00** [comment]
The decision for whether variables should be resolved in a command needs to be made on a per command bases. If you want, you can run your commands arguments through the variable resolve when your command is called. 

For example, the terminal uses the variable resolver here: 

https://github.com/microsoft/vscode/blob/6ee9724963da3a48c48dee97540ed9c5856c26b7/src/vs/workbench/contrib/terminal/browser/terminalActions.ts#L2720-L2721

**Comment by ArturoDent** [comment]
From https://code.visualstudio.com/docs/editor/variables-reference

> Visual Studio Code supports variable substitution in [Debugging](https://code.visualstudio.com/docs/editor/debugging) and [Task](https://code.visualstudio.com/docs/editor/tasks) configuration files as well as some select settings. Variable substitution is supported inside some key and value strings in launch.json and tasks.json files using ${variableName} syntax.

It would be great if more variable resolution was achieved in keybindings - I think it has been requested many times.

**Comment by andreamah** [comment]
verif steps:

1. Create a keybinding for `workbench.action.findInFiles`:
```
    {
        "key": "ctrl+shift+g",
        "command": "workbench.action.findInFiles",
        "args": {
            "filesToInclude": "${relativeFileDirname}",
        }
    },
```
2. Verify that the keybinding correctly sets `filesToInclude` to the current path.
