### ISSUE TITLE
.ogg extension file error

### ISSUE THREAD

**Issue by sonivraj82** [microsoft/vscode#173680]
Type: <b>Bug</b>

Okay this is not actually an error but... 
I was working with a video file and it's name is video.ogg. ".ogg" is a video and audio file format/extension.  In the explorer's tab the VS Code app says its an audio file, but it is not. The working of the file is proper in the browser but when you try to open it from VS Code itself it shows an error as "An error occurred while loading the audio file. Open file using VS Code standard text/binary editor?". According to me the app VS Code is not able to distinguish between if the file is an audio file of a video one. Lookng forward to this conversation, and hoping it gets fixed in the next VS Code update.

Thank You in advance.
- Vishnu Soni

VS Code version: Code 1.75.0 (e2816fe719a4026ffa1ee0189dc89bdfdbafb164, 2023-02-01T15:23:45.584Z)
OS version: Windows_NT x64 10.0.19045
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|7.91GB (3.47GB free)|
|Process Argv|--crash-reporter-id a11aa8c0-ee10-49c8-bdab-a98bdc6a192e|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
LiveServer|rit|5.7.9

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
azure-dev_surveyone:30548225
pyindex848cf:30577861
nodejswelcome1cf:30587006
2e4cg342:30602488
pyind779:30657576
f6dab269:30613381
pythonsymbol12cf:30657549

```

</details>

**Comment by mjbvz** [comment]
Although `.ogg` is a general container file format, I think `.ogg` is now recommended for audio content (or the more explicit `.oga`).

If you want though, you can configure `workbench.editorAssociations` so that `ogg` opens with the video preview instead of the audio one:

```
	"workbench.editorAssociations": {
		"*.ogg": "vscode.videoPreview"
	},
```

**Comment by sonivraj82** [comment]
Reply
