### ISSUE TITLE
Filename filter not working: Click on the explorer and start typing.

### ISSUE THREAD

**Issue by hgabor47** [microsoft/vscode#173652]
Click on the explorer and start typing

_Originally posted by @isidorn in https://github.com/microsoft/vscode/issues/72376#issuecomment-483545012_

**Comment by gjsjohnmurray** [comment]
The UI has changed since that comment was written. To start filtering or highlighting in a tree or list, first press Ctrl+F (or Cmd+F on macOS).

**Comment by gjsjohnmurray** [comment]
See https://code.visualstudio.com/docs/getstarted/userinterface#_advanced-tree-navigation

**Comment by isidorn** [comment]
Closing as @gjsjohnmurray answered
