### ISSUE TITLE
URI.parse query decoding is broken

### ISSUE THREAD

**Issue by samdenty** [microsoft/vscode#173687]
Steps to Reproduce:

1. In an extension / somewhere in vscode codebase write:

```js
console.log(vscode.Uri.parse(`https://test.com/?a%26&b`).query)
```

2. Get the unexpected output of `?a&&b`

**Comment by jrieken** [comment]
Yeah, that's unfortunate but something we cannot fix/change anymore. Too much code exists that depends on this broken behaviour and we decided to keep things the way they are

**Comment by jrieken** [comment]
See https://github.com/microsoft/vscode/issues/83645 for more details
