### ISSUE TITLE
Select Language mode isn't showing python

### ISSUE THREAD

**Issue by MrPotatoHead-Dev** [microsoft/vscode#173629]
Type: <b>Bug</b>

Every other language is there except python. Even when I have python installed, python extension installed and all my environment variables setup. Idk what has happened

VS Code version: Code 1.75.0 (e2816fe719a4026ffa1ee0189dc89bdfdbafb164, 2023-02-01T15:23:45.584Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-10200H CPU @ 2.40GHz (8 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|7.79GB (2.13GB free)|
|Process Argv|--crash-reporter-id e10577eb-115a-4197-b8a6-cf968a42665c|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
isort|ms-|2022.8.0
python|ms-|2023.3.10371010
vscode-pylance|ms-|2023.2.10
jupyter|ms-|2023.1.2000312134
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.14
vscode-jupyter-cell-tags|ms-|0.1.6
vscode-jupyter-slideshow|ms-|0.1.5
powershell|ms-|2023.1.0
slither-vscode|tra|0.0.7

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vscaat:30438848
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
azure-dev_surveyone:30548225
vscccc:30610679
pyindex848:30577860
nodejswelcome1:30587005
282f8724:30602487
f6dab269:30613381
pythonsymbol12cf:30657549

```

</details>

**Comment by aeschli** [comment]
Can you check that the basic python extension is not disabled?
![image](https://user-images.githubusercontent.com/6461412/217198430-848b2f99-d8b0-4333-9537-6e83032d95b1.png)

**Comment by MrPotatoHead-Dev** [comment]
![image](https://user-images.githubusercontent.com/121565225/217249152-4d49c173-cde0-4e9a-b310-f27e1b7f96a5.png)

I cant find that extension in the extension tab. 
The 2 extensions I have related with python are Python, Pylance and isort. All on the released version, not the released (I tried switching them).
Right now my scripts are in Plain text. I did switch them to Batch and could still use the python debugger.
To get the python logo on my .py files I had to change something in a .json file.
I dont really want to but Later today if I can't figure it out ill reset everything again

Thank you for your time

**Comment by aeschli** [comment]
In the extension view' filter box, did you enter `@builtin python` as shown in the screenshot?

**Comment by MrPotatoHead-Dev** [comment]
[image: image.png]

**Comment by MrPotatoHead-Dev** [comment]
![image (1)](https://user-images.githubusercontent.com/121565225/217283179-475e192a-89cc-4cd7-8578-824300eb1ee9.png)

Just my luck. Its not there. I see all the languages but python

**Comment by aeschli** [comment]
That's very strange. @sandy081 Any idea how that can be?

**Comment by MrPotatoHead-Dev** [comment]
@aeschli. I did a full reset and it appeared. I didn't have to search for anything, or download anything new. Just uninstalled and reinstalled VS from the same file that I downloaded the other day.

Thank you very much for your time.
