### ISSUE TITLE
Editor Controller autoClosingPairs - open parens: whitespace test timeout

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode#173628]
https://dev.azure.com/monacotools/Monaco/_build/results?buildId=202421&view=logs&j=55ac390b-ffb1-50ea-3650-525dd9a3fd80&t=3a692518-c3cf-5f6a-c273-72f71dc185fb&l=10333

```
 1) Editor Controller
       autoClosingPairs - open parens: whitespace:

      
      + expected - actual


  Error: Timeout of 5000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.

```

**Comment by alexdima** [comment]
This test takes 43ms on my machine and it has no async/await code, so it is all CPU bound. For this test to timeout at 5000ms, it means the build machine was 100x slower than my local machine. I believe this was an intermittent problem on the build machine, perhaps one of these -- https://learn.microsoft.com/en-us/troubleshoot/azure/virtual-machines/troubleshoot-high-cpu-issues-azure-windows-vm#common-factors
