### ISSUE TITLE
remote: error: GH001: Large files detected.

### ISSUE THREAD

**Issue by toddrgarner** [microsoft/vscode#173609]
Type: <b>Bug</b>

I continue to receiv the message below even though I erased all large files from my project. I realized the issue when I tried to git push origin main:

remote: error: File public/videos/video-1.mp4 is 589.28 MB; this exceeds GitHub's file size limit of 100.00 MB

Please advise how clear eveything in order for me to continue working.

VS Code version: Code 1.75.0 (Universal) (e2816fe719a4026ffa1ee0189dc89bdfdbafb164, 2023-02-01T15:24:42.903Z)
OS version: Darwin x64 20.6.0
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz (8 x 2500)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (0.28GB free)|
|Process Argv|--crash-reporter-id e2175819-a738-4ab0-8a8d-48b09ac0c190|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|3.0.2
gitlens|eam|13.2.0
prettier-vscode|esb|9.10.4
vscode-graphql-syntax|Gra|1.0.6
elmmet|nec|1.0.1
indent-rainbow|ode|8.3.1
vscode-thunder-client|ran|2.3.4
es7-react-js-snippets|rod|1.9.3
open-in-browser|tec|2.0.0
pdf|tom|1.2.2

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
azure-dev_surveyone:30548225
vsccc:30610678
pyindex848:30577860
nodejswelcome1cf:30587006
2e4cg342:30602488
f6dab269:30613381
pythonsymbol12:30657548

```

</details>

**Comment by bpasero** [comment]
> this exceeds GitHub's file size limit of 100.00 MB

Please report to GitHub.
