### ISSUE TITLE
'Beak' on CommentThreadZoneWidget is always placed at start of line

### ISSUE THREAD

**Issue by gjsjohnmurray** [microsoft/vscode#173690]
Type: <b>Bug</b>

I am developing an extension which uses the comments API. I would like the 'beak' at the top edge of the zone widget to point to the entity indicated by the thread's range. At the moment all the `this.show()` calls made by the ReviewZoneWidget class in commentThreadZoneWidget.ts specify `column: 1`.

I am willing to prepare a PR.

VS Code version: Code - Insiders 1.76.0-insider (25514d899f4bd877803defb213719f8af3d997d3, 2023-02-07T05:22:19.428Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: Yes

**Comment by alexr00** [comment]
@gjsjohnmurray I would accept a PR for this. Would you put the beak at the beginning of the range or the middle of the range? It looks like "Peek all references" goes for the middle of the range.

**Comment by alexr00** [comment]
> It looks like "Peek all references" goes for the middle of the range.

For multiline comment ranges we'd probably still want the current behavior where the beak is at the start of the last line.

**Comment by alexr00** [comment]
To verify:
1. Clone microsoft/vscode-extension-samples and open comment-sample
2. Modify comment thread range here to not be the start of the line: https://github.dev/microsoft/vscode-extension-samples/blob/f1df8faee789ed72a42010a42e10bc9baf624929/comment-sample/src/extension.ts#L136
3. Run the sample and add a comment. Verify that the beak shows in the middle of your range, not at the beginning of the line.
4. Revert your change, run again, and add a comment. Verify that the beak shows at the beginning of the line.
