### ISSUE TITLE
Terminal tab colors don't look correct in Light+

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#173611]
![Recording 2023-02-06 at 15 41 26](https://user-images.githubusercontent.com/323878/217080558-eda17480-3e3b-49ea-adf0-2b5922f0af22.gif)

No clue whether this has changed, I just wasn't sure this was correct. Should there be a background color on all tabs? When hovering the active tab, the text and icon color is white which makes it hard to read

**Comment by Tyriar** [comment]
Do you have color customizations? This is what it looks like for me:

![image](https://user-images.githubusercontent.com/2193314/217112240-132212d7-cf22-44af-8542-8999e95ef52f.png)

**Comment by roblourens** [comment]
I get the blue highlight when it's focused, but in my gif it's not focused

**Comment by Tyriar** [comment]
Ah, I can repro this in Light+ v2:

<img width="193" alt="image" src="https://user-images.githubusercontent.com/2193314/217312651-4587a9f4-dc04-41b1-9a10-2100a323cdd3.png">

Not sure how to get the text to go white though

**Comment by daviddossett** [comment]
I think this is all related to https://github.com/microsoft/vscode/pull/172668

**Comment by Tyriar** [comment]
Should be fixed as part of https://github.com/microsoft/vscode/issues/173238
