### ISSUE TITLE
Configuration name is overriden in "startDebugging" request

### ISSUE THREAD

**Issue by int19h** [microsoft/vscode#173655]
(VSCode 1.75.0)

When using "startDebugging" reverse request, if the specified "configuration" has a "name" property in it, it is overwritten with the name of the parent session:

https://github.com/microsoft/vscode/blob/fccbc488eac662a9e80b5ec17161746012c1d6d6/src/vs/workbench/contrib/debug/browser/rawDebugSession.ts#L664-L674

However, unlike "request" which can be set via the property on the "startDebugging" request itself, there's no equivalent for "name", making it impossible for the debug adapter to give meaningful names to subprocesses.  

Request:
```json5
            {
                 "seq": 17,
                 "type": "request",
                 "command": "startDebugging",
                 "arguments": {
                     "request": "attach",
                     ...
                     "configuration": {
                         "name": "Subprocess 2824",
                         ...
                     }
                 }
            }
```

Desired UX:
![image](https://user-images.githubusercontent.com/1175142/217195125-53a12fdc-c383-41cd-bbf1-b5852d192c9a.png)

Actual UX:
![image](https://user-images.githubusercontent.com/1175142/217194897-3879321b-4282-400f-a608-9b3dbe1b68f8.png)

**Comment by roblourens** [comment]
Just an oversight, thanks
