### ISSUE TITLE
"supportsStartDebuggingRequest" is unset

### ISSUE THREAD

**Issue by int19h** [microsoft/vscode#173654]
(VSCode 1.75.0)

Per DAP specification and [release notes for 1.73](https://github.com/microsoft/vscode-docs/blob/vnext/release-notes/v1_73.md#new-startdebugging-reverse-request), the adapters should only be using the "startDebugging" reverse request if the client advertises that it's capable of handling it by setting "supportsStartDebuggingRequest" to true during initialization. However, VSCode does not advertise this capability at all despite supporting the feature:
```json5
             {
                 "seq": 1,
                 "type": "request",
                 "command": "initialize",
                 "arguments": {
                     "clientID": "vscode",
                     "clientName": "Visual Studio Code",
                     "adapterID": "python",
                     "pathFormat": "path",
                     "linesStartAt1": true,
                     "columnsStartAt1": true,
                     "supportsVariableType": true,
                     "supportsVariablePaging": true,
                     "supportsRunInTerminalRequest": true,
                     "locale": "en",
                     "supportsProgressReporting": true,
                     "supportsInvalidatedEvent": true,
                     "supportsMemoryReferences": true,
                     "supportsArgsCanBeInterpretedByShell": true,
                     "supportsMemoryEvent": true
                 }
             }
```
Since conforming adapters have to assume the default to be false in practice for backwards compatibility, it makes the reverse request unusable in practice.

**Comment by roblourens** [comment]
Another oversight, thanks
