### ISSUE TITLE
Unable to use command line of VSCode

### ISSUE THREAD

**Issue by fabioz** [microsoft/vscode#173718]
I'm trying to use the VSCode command line to check version/list/install extension but instead of executing the command line it seems to just open VSCode instead of executing the command line (I tried both in stable and insiders version):

See .gif below.

Versions checked:
```
Version: 1.75.0-insider (user setup)
Commit: b229eb5fa2ecadb8a5238ccb9f6f49f7ccba9d2b
Date: 2023-01-27T22:17:10.413Z
Electron: 19.1.9
Chromium: 102.0.5005.194
Node.js: 16.14.2
V8: 10.2.154.23-electron.0
OS: Windows_NT x64 10.0.22621
Sandboxed: Yes
```

```
Version: 1.75.0 (user setup)
Commit: e2816fe719a4026ffa1ee0189dc89bdfdbafb164
Date: 2023-02-01T15:23:45.584Z
Electron: 19.1.9
Chromium: 102.0.5005.194
Node.js: 16.14.2
V8: 10.2.154.23-electron.0
OS: Windows_NT x64 10.0.22621
Sandboxed: No
```

![issue_vscode_cmdline](https://user-images.githubusercontent.com/117621/217338025-cc304577-42eb-4a4e-9d3a-08957e5efdfb.gif)

**Comment by aeschli** [comment]
You need to run the `code` which is inside `bin`. That's the `code` that is normally on the PATH and that support command line arguments.
