### ISSUE TITLE
Dark+ V2: hard to distinguish title bar from tab bar

### ISSUE THREAD

**Issue by jasonwilliams** [microsoft/vscode#173706]
This is a nice theme, good job.
There is a UX issue I face though since I've switched. When trying to drag the VSCode window somewhere on my screen I accidently click the wrong section, I click the bar which holds the files opened instead of the title bar.

This is due to the "tab" bar being the same color as the "title" bar and now it's difficult to differentiate between them.

There's now no contrast between the title section and the filename section meaning I click and drag my mouse in the wrong place and end up trying to drag a tab instead of the window itself.
![2bars](https://user-images.githubusercontent.com/936006/217308636-4cce94ea-5030-4354-9f3e-a9aa50491839.png)

When going back to Dark+ I noticed they're given a slightly different shading so you can tell them apart.
![2barsOld](https://user-images.githubusercontent.com/936006/217309399-29f149fa-2ef2-43d2-84c0-e23441af81e5.png)

Maybe its just a case of me needing to get used to his theme and over time it will happen less, but I did think it was worth feeding back as others may be hitting the same issue.

**Comment by jasonwilliams** [comment]
I wonder if you allow dragging from the tab bar when you're mouse isn't directly on a tab. I can imagine this would be ok as I can't see a reason to ever drag in that space when not on a tab.  This is closer aligned to the UX of a browser like chrome

**Comment by daviddossett** [comment]
I'll take a look at how things look if we made the titlebar a slightly different color. The trade off here is that we break the general spirit of the theme which was to have minimal shades of gray (in this case, 2). Which may be ok.

> I wonder if you allow dragging from the tab bar when you're mouse isn't directly on a tab. I can imagine this would be ok as I can't see a reason to ever drag in that space when not on a tab. This is closer aligned to the UX of a browser like chrome

Interesting point. Browsers are maybe slightly different in that that tab bar and title bar are often on the same row. It seems like today when you drag, it's as if you were dragging the tab around. But I could see a case for that moving the window instead.

**Comment by benibenj** [comment]
You can customize he color by adding the following to your settings

```
"workbench.colorCustomizations": {
        "titleBar.border": "#fff"
    },
```
