### ISSUE TITLE
Cannot using `git stash` on the dash of source control

### ISSUE THREAD

**Issue by jason19970210-senao** [microsoft/vscode#173760]
Does this issue occur when all extensions are disabled?:
  Not sure, due to I worked remotely with SSH to the server side, it cannot be test without the SSH remote extension

```
## Client Side
- Version: 1.75.0
- Commit: e2816fe719a4026ffa1ee0189dc89bdfdbafb164
- Date: 2023-02-01T15:29:17.766Z
- Electron: 19.1.9
- Chromium: 102.0.5005.194
- Node.js: 16.14.2
- V8: 10.2.154.23-electron.0
- OS: Linux x64 5.15.0-58-generic
- Sandboxed: No
```

Steps to Reproduce:

1. Open a project with git includes
2. Modify the code
3. Go to the left panel, select `Source Control`
4. On the top right of the `Source Control` panel, open the menu bar which the icon is 3 dots ( ... )
5. Select `Stash` option
6. Once click, a message prompt pop up, then insert `test` or any strings else
7. Next press `Enter`, it will pop a error window with command options

the command output:
```
> git stash push -m test
usage: git stash list [<options>]
   or: git stash show [<stash>]
   or: git stash drop [-q|--quiet] [<stash>]
   or: git stash ( pop | apply ) [--index] [-q|--quiet] [<stash>]
   or: git stash branch <branchname> [<stash>]
   or: git stash [save [--patch] [-k|--[no-]keep-index] [-q|--quiet]
		       [-u|--include-untracked] [-a|--all] [<message>]]
   or: git stash clear
```

Please help to confirm the issue and hopefully fix as soon as possible.

**Comment by lszomoru** [comment]
@jason19970210-senao, apologies for not getting back to you on this until now. What is the version of git that you are using? It looks like you might be running an old version of git that does not support `git stash push`. Please upgrade to the latest version of git in order to resolve this issue. Thanks!
