### ISSUE TITLE
Tab double click to maximize editor of the tab

### ISSUE THREAD

**Issue by matteopasqualin** [Microsoft/vscode#17373]
- VSCode Version: 1.8
- OS Version: Mac OS Sierra

Hello,

if I'm not wrong, by double clicking the tab it pins the file . Personally, I would prefer to expand the file editor / collapsing the menu on the left. It would be same behaviour as the File Explorer button on the top left. Is it possible? Or, can people customize the tab double click? 
People could set a pin option on each tab and the double click expands the file editor window.
Or, if simpler, set the option in a right click context menu on each tab. Isn't it?

Thanks a lot

Matteo

**Comment by itamark** [comment]
Hi Matteo!
There is the option in your settings.json to disable quick previews. Is that the functionality that's problematic for you?
`  "workbench.editor.enablePreviewFromQuickOpen": true,
`

**Comment by matteopasqualin** [comment]
Hello itamark,
well, it isn't. However good to know about the editor setting.
The setting I'd like is toggling the left menu panel by a double click on the current file Tab.
In settings, it could be something like: "workbench.editor.toggleLeftbarOnDblClickTab"... or something better!
I checked in the menus to get the desired result and the equivalent command is (with Mac): CMD+B.

Is it possible to implement it?

Thanks

Matteo
