### ISSUE TITLE
open quickfix view shouldn't trigger auto save

### ISSUE THREAD

**Issue by tjx666** [microsoft/vscode#173791]
https://user-images.githubusercontent.com/41773861/217510486-2325b941-2c9e-44a7-ab0c-a97915c6bf41.mov

steps:

1. modify code, editor enter modified state
2. click `quick fix` to open quickfix view
3. click editor, will trigger auto save

```
Version: 1.74.3 (Universal)
Commit: 97dec172d3256f8ca4bfb2143f3f76b503ca0534
Date: 2023-01-09T17:07:18.579Z
Electron: 19.1.8
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Darwin x64 22.3.0
Sandboxed: No
```

@mjbvz @alexdima

**Comment by Balastrong** [comment]
Hello!

I tried to reproduce the issue with the mentioned steps, but in my case the editor does not trigger autosave.
Could it be due to some extensions or settings active in your case?

**Comment by tjx666** [comment]
@Balastrong I can still reproduce in 1.75.1

**Comment by tjx666** [comment]
Semms fixed in latest version
