### ISSUE TITLE
"Windows: Auto Detect Color Scheme" doesn't work with setting sync

### ISSUE THREAD

**Issue by Serock3** [microsoft/vscode#173770]
Type: <b>Bug</b>

If I switch between two PCs with different color schemes, then the color scheme in vs code will not change to match the OS of the new PC, but be stuck in the mode of the previous one.

Toggling the "Windows: Auto Detect Color Scheme" will cause the scheme to reset to the correct mode.

Suggested solution: Check the OS color scheme on launch when "Windows: Auto Detect Color Scheme" is enabled.

VS Code version: Code 1.75.0 (e2816fe719a4026ffa1ee0189dc89bdfdbafb164, 2023-02-01T15:23:45.584Z)
OS version: Windows_NT x64 10.0.19044
Modes:
Sandboxed: No
Remote OS version: Linux x64 5.10.102.1-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz (8 x 2419)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.69GB (5.37GB free)|
|Process Argv|--remote=wsl+Ubuntu --crash-reporter-id 2e666b31-8660-4ae2-a0ea-cee97ad0edfa|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 5.10.102.1-microsoft-standard-WSL2|
|CPUs|11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz (8 x 2419)|
|Memory (System)|12.23GB (11.08GB free)|
|VM|0%|
</details><details><summary>Extensions (26)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|3.0.2
jupyter-keymap|ms-|1.0.0
remote-wsl|ms-|0.75.1
errorlens|use|3.7.0
vscode-markdownlint|Dav|0.49.0
gc-excelviewer|Gra|4.2.56
git-graph|mhu|1.30.0
vscode-dotnet-runtime|ms-|1.6.0
isort|ms-|2022.8.0
python|ms-|2023.2.0
vscode-pylance|ms-|2023.2.10
jupyter|ms-|2023.1.2010391206
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.14
vscode-jupyter-cell-tags|ms-|0.1.6
vscode-jupyter-slideshow|ms-|0.1.5
cpptools|ms-|1.13.9
vsliveshare|ms-|1.0.5828
autodocstring|njp|0.6.1
rust-analyzer|rus|0.3.1394
crates|ser|0.5.10
code-spell-checker|str|2.16.0
even-better-toml|tam|0.19.0
vscode-lldb|vad|1.8.1
vscode-capnp|xmo|1.0.0
vscode-proto3|zxh|0.5.5

(2 theme extensions excluded)

</details>

**Comment by hamirmahal** [comment]
I have the same issue. I'm on Windows 10 and I use https://github.com/AutoDarkMode/Windows-Auto-Night-Mode.

![image](https://github.com/microsoft/vscode/assets/43425812/2e274802-fb79-4e3c-989e-747de7003d0e)

**Comment by hamirmahal** [comment]
I ran into this issue again today. Here's a screen recording. I'm using Ubuntu via WSL2 on Windows 10. As far as I'm aware, I just have 1 VSCode profile, although I am synchronizing VSCode settings between multiple devices.

```
Version: 1.81.1 (user setup)
Commit: 6c3e3dba23e8fadc360aed75ce363ba185c49794
Date: 2023-08-09T22:22:42.175Z
Electron: 22.3.18
ElectronBuildId: 22689846
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Windows_NT x64 10.0.19045
```

@aeschli let me know if there's any debugging commands I can run that would make troubleshooting easier.

https://github.com/microsoft/vscode/assets/43425812/4098b866-e775-492d-8149-3b74ecaca535

**Comment by hamirmahal** [comment]
I'm happy to look into this if someone wants to point me in the general direction of the source files or code that probably needs changing.

**Comment by Frozen-hc** [comment]
> I ran into this issue again today. Here's a screen recording. I'm using Ubuntu via WSL2 on Windows 10. As far as I'm aware, I just have 1 VSCode profile, although I am synchronizing VSCode settings between multiple devices.
> 
> ```
> Version: 1.81.1 (user setup)
> Commit: 6c3e3dba23e8fadc360aed75ce363ba185c49794
> Date: 2023-08-09T22:22:42.175Z
> Electron: 22.3.18
> ElectronBuildId: 22689846
> Chromium: 108.0.5359.215
> Node.js: 16.17.1
> V8: 10.8.168.25-electron.0
> OS: Windows_NT x64 10.0.19045
> ```
> 
> @aeschli let me know if there's any debugging commands I can run that would make troubleshooting easier.
> 
> https://github.com/microsoft/vscode/assets/43425812/4098b866-e775-492d-8149-3b74ecaca535

The bug that happened to me was a little different than yours. 
As far as I know, VS Code achieves the effect of changing the theme by changing the workbench.colorTheme setting in the settings.json, and switching the light/dark theme of Windows only changes the workbench.colorTheme of the currently used profiles, so when I then switch to other, the theme display error occurs.

**Comment by mboiman** [comment]
I have it too on mac

**Comment by quedicesebas** [comment]
Not working setting `"window.autoDetectColorScheme": true`, VSCode doesn't switch the theme based on OS color theme.

**Comment by aeschli** [comment]
This works better now with the recent changes on how `"window.autoDetectColorScheme": true` works:
See https://code.visualstudio.com/updates/v1_89#_auto-detect-system-color-mode-improvements

`"workbench.colorTheme"` is no used and updated when autoDetectColorScheme is on.
