### ISSUE TITLE
Workspace scoped TaskProvider

### ISSUE THREAD

**Issue by hyangah** [microsoft/vscode#173700]
I wanted to create workspace-level tasks, that is running `go test` with `${fileDirname}` as `cwd`.
In a multi-root workspace with folder1 and folder2, 

```
{
	"folders": [ {"path": "/Users/u1/folder1"}, {	"path": "/Users/u1/folder2"	}],
	"tasks": {
		"version": "2.0.0",
		"tasks": [
			{
				"label": "My Task",
				"command": "pwd",
				"type": "shell",
				"options": {
					"cwd": "${fileDirname}"
				},
			}
		]
	}
}
```

In the task execution terminal, I see confusing echo messages "Executing task in folder folder1".  No matter what cwd is actually used, the message uses the first workspace folder.

```
 *  Executing task in folder folder1: pwd 

/Users/u1/Library/Application Support/Code/Workspaces/1675780932373
 *  Terminal will be reused by tasks, press any key to close it. 

 *  Executing task in folder folder1: pwd 

/Users/u1/folder2/subfolder
 *  Terminal will be reused by tasks, press any key to close it. 
```
I hope this is a cosmetic issue that needs massaging the echo message.

--
Working with TaskProvider API when multi root workspace is more confusing (discussed in  https://github.com/microsoft/vscode/issues/155149 but closed without resolution). It seems like the API does not recognize multi-root workspaces (e.g. the quick picks presented by "Tasks: Run Task" attempts to associate the task with the first folder if Workspace scope is used), nor does not make sense for more recent no-folder workspace mode. However, I think the revision/clarification of the current misleading TaskProvider API deserves a separate issue (or reopen #155149)

**Comment by meganrogge** [comment]
I believe this is already fixed, can you see if you can reproduce in the [Insiders build](https://code.visualstudio.com/insiders)?
/label info-needed
