### ISSUE TITLE
Screencast Mode: Only Keyboard Shortcuts still shows command names

### ISSUE THREAD

**Issue by gregvanl** [microsoft/vscode#173752]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.75.0 Stable, 1.76.0 Insiders
- OS Version: Windws 11

Steps to Reproduce:

1. Enable Screencast Mode: Only Keyboard Shortcuts ("screencastMode.onlyKeyboardShortcuts": true)
2. Toggle Screencast Mode
3. Try keyboard shortcuts such as Ctrl+P and Ctrl+Shift+P

Both keybindings still show "Go to File..." and "Show All Commands"

**Comment by sankeerth125** [comment]
Hi @joaomoreno, is anyone working on this? if not can I do this?

**Comment by nikdmello** [comment]
Hi @gregvanl, what is the expected behavior? When I click Ctrl+P in Screencast Mode, should it say "Go to File... Ctrl+P" or "Go to File..." or just "Ctrl+P"

**Comment by gregvanl** [comment]
Hi @nikdmello My understanding is that with the Screencast Mode: Only Keyboard Shortcuts setting checked (value `true`), in screencast mode, you should only see the keyboard shortcuts (Ctrl+P) without any text for the command name.

**Comment by nikdmello** [comment]
@gregvanl Thanks! It's my first time contributing to VS Code. How do I make changes and test it out locally? Is there some resource you can point me to?

**Comment by nikdmello** [comment]
Simple fix here. In developerActions.ts I updated the code for the Screencast Mode behavior, particularly for the Only Keyboard Shortcuts option. When the box is not checked (hence false), only then do we want the action names printed out. So, I added this Boolean check to the if statement to only print out the action names when the box is checked (true).

**Comment by gregvanl** [comment]
@nikdmello I'm curious, do you know why this feature regressed and stopped working? Looking through history for the culprit should help you have confidence in your fix.

**Comment by nikdmello** [comment]
@gregvanl hmm, are you sure if this feature was working before? I will look through history soon but perhaps it was just faulty logic from the beginning.

**Comment by gregvanl** [comment]
@nikdmello I played around with some earlier versions of VS Code, for example 1.38 when the `screencastMode.onlyKeyboardShortcuts` setting was announced, and actually couldn't see the command names displayed.
I'll leave it to @joaomoreno to confirm that the setting did work at one point and to review your PR.
Thanks
