### ISSUE TITLE
Terminal Window CLS does not clear full screen

### ISSUE THREAD

**Issue by Denisjc** [microsoft/vscode#173799]
Type: <b>Bug</b>

The cls command in terminal does not clear the screen completely, it just clears some of the terminal as older items further up the screen are not cleared

VS Code version: Code 1.75.0 (e2816fe719a4026ffa1ee0189dc89bdfdbafb164, 2023-02-01T15:23:45.584Z)
OS version: Windows_NT x64 10.0.19042
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|63.76GB (37.88GB free)|
|Process Argv|--folder-uri file:///d%3A/Dev.Ure/mras.ure.qa --crash-reporter-id e7b05ea8-1ff5-4ee9-9240-1b1546c91cfd|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (50)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-pull-request-azdo|ank|0.0.25
featurehighlight|Blo|1.8.0
githistory|don|0.6.19
gitlens|eam|13.2.0
vscode-diff|fab|1.4.2
vscode-solution-explorer|fer|0.7.5
azure-storage-explorer|for|0.1.2
dotnet-test-explorer|for|0.7.8
gc-excelviewer|Gra|4.2.56
vscode-test-explorer|hbe|2.21.1
githd|hui|2.3.3
rest-client|hum|0.25.1
loginspector|Log|1.6.3
git-graph|mhu|1.30.0
azure-pipelines|ms-|1.208.0
azure-dev|ms-|0.3.0
vscode-apimanagement|ms-|1.0.5
vscode-azureappservice|ms-|0.24.5
vscode-azurefunctions|ms-|1.10.1
vscode-azureresourcegroups|ms-|0.5.6
vscode-azurestaticwebapps|ms-|0.11.4
vscode-azurestorage|ms-|0.15.0
vscode-cosmosdb|ms-|0.19.2
vscode-docker|ms-|1.23.3
vscode-logicapps|ms-|1.2.0
csharp|ms-|1.25.4
vscode-edge-devtools|ms-|2.1.1
data-workspace-vscode|ms-|0.4.0
mssql|ms-|1.17.1
sql-bindings-vscode|ms-|0.3.0
sql-database-projects-vscode|ms-|0.21.0
remote-containers|ms-|0.275.1
azure-account|ms-|0.11.3
azurecli|ms-|0.5.0
powershell|ms-|2023.1.0
test-adapter-converter|ms-|0.1.6
pester-test|psp|2023.1.0
fabric8-analytics|red|0.3.6
java|red|1.14.0
vscode-xml|red|0.24.0
vscode-uppercase|rui|1.0.1
vscode-pester-test-adapter|Tyl|0.0.23
intellicode-api-usage-examples|Vis|0.2.7
vscodeintellicode|Vis|1.2.30
vscode-java-debug|vsc|0.48.0
vscode-java-dependency|vsc|0.21.1
vscode-java-pack|vsc|0.25.7
vscode-java-test|vsc|0.37.1
vscode-maven|vsc|0.40.4
delete-node-modules|Wsc|1.0.6

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vscaat:30438848
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
azure-dev_surveyonecf:30548226
pyindex848cf:30577861
nodejswelcome1cf:30587006
2e4cg342:30602488
f6dab269:30613381
pythonsymbol12:30657548
vsctsb:30659830

```

</details>

**Comment by Ramin-RX7** [comment]
This has been an issue for a long time. Duplicate of #134448

**Comment by Denisjc** [comment]
wth how is this a duplicate ?  And then close without even reading or commenting about it.





> /duplicate #134448

This is not a duplicate of the issue above.

**Comment by meganrogge** [comment]
I receive > 100 notifications a day. Thank you for your issue and you are correct this is actually a duplicate of this one. 

/duplicate #134448
