### ISSUE TITLE
Add the ability to assign a workspace to a profile

### ISSUE THREAD

**Issue by DreamShaded** [microsoft/vscode#173768]
Hello! Developing several projects with different technologies make developer to switch the current profile to other. It would be cool to be able to assign a certain profile to a workspace settings

**Comment by sandy081** [comment]
Associating a profile to a workspace is remembered. May I know the purpose of assigning the profile in workspace settings?

**Comment by henry-js** [comment]
It is not mentioned in the release notes so I've just spent 30 mins trying to figure out how to do it until I saw this GitHub issue.
I would guess OP is in a similar situation to me. Much appreciated feature, but the docs could be clearer :)

**Comment by DreamShaded** [comment]
yes, maybe the docs will be the solution)) for now it's really remember the profile with workspace or visited directory, so the one case when the property need is syncing with different device

**Comment by sandy081** [comment]
We are working on the docs and will make sure this info is updated. The docs will come soon.
