### ISSUE TITLE
Worktree is no longer recognised but the Source Control pane.

### ISSUE THREAD

**Issue by holmes-mike** [microsoft/vscode#173748]
- VS Code Version: 1.75.0
- OS Version: Windows 10

I just got the new update and my worktrees are no longer recognised in the source control pane. I am assuming the that `.git` file in the root of the workspace is not being recognised.

I have also tested with a fresh workspace and the same behaviour. (all extensions disabled)
![image](https://user-images.githubusercontent.com/56387624/217416495-a1b8bbc1-8d2b-4d76-a371-7edff395c86c.png)

![image](https://user-images.githubusercontent.com/56387624/217416824-1d8e48ea-ec7a-415c-813b-5abcf3833cbb.png)

**Comment by ctarn** [comment]
My comment in #173753 may help

**Comment by gjsjohnmurray** [comment]
Probably #173226 which is fixed in the upcoming recovery release.

**Comment by holmes-mike** [comment]
Can confirm, fixed in insiders.
