### ISSUE TITLE
Version 1.8 Import completion displays multiple versions of the same package

### ISSUE THREAD

**Issue by wonbyte** [Microsoft/vscode#17375]
- VSCode Version: 1.8.0 (1.8.0)
- OS Version: macOS Sierra 10.12.2

Steps to Reproduce:

1. Install react via npm to a local folder and open the project in vscode.
2.  use ES6 import syntax to import the react component.
3. The autocomplete will display multiple versions of react. 
4. It does this for numerous packages.
5. See attached screen shot.

<img width="1114" alt="screen shot 2016-12-16 at 1 18 13 am" src="https://cloud.githubusercontent.com/assets/681965/21254867/03ac6b4c-c32e-11e6-958c-6d55da90cbb1.png">

I would expect it to only display one match for each package in the node_modules folder.

**Comment by wonbyte** [comment]
This seems to be something related to the way npm does dependency management as I switched to yarn and now I am seeing this (which is the correct behavior I would expect):

<img width="1114" alt="screen shot 2016-12-17 at 12 50 42 am" src="https://cloud.githubusercontent.com/assets/681965/21285033/f21266be-c3f2-11e6-9db8-ce93efed31f0.png">

**Comment by mjbvz** [comment]
I'm not able to repo this using npm`3.10.9`. It sounds like you found a workaround, but if you run into this again, please let us know.

Thanks
