### ISSUE TITLE
Hack Nerd Font Stop to rendering correctly after 1.75 version update

### ISSUE THREAD

**Issue by ghost** [microsoft/vscode#173746]
Today my **VSCode** version updated to 1.75, and the integrated terminal which I use with the `Hack Nerd Font` configuration, and with the **Integrated GPU Acceleration** setting with the value `on`, display my terminal in this way: 

![Screenshot from 2023-02-07 20-13-57](https://user-images.githubusercontent.com/108949339/217411230-c1d1f22d-333c-40f7-a28d-762fa31268ac.png)

Anyone could give me a solution about that change in the rendering? I'll be very grateful if someone could help me with that.

**Comment by rzhao271** [comment]
Does running with GPU acceleration off fix the issue?
If not, what shell are you using, and what operating system?

**Comment by JesFragoso** [comment]
No, it doesn't fix that, I'm using `zsh` shell, on Ubuntu 20.04.5 LTS

**Comment by JesFragoso** [comment]
I've tried with all the type of GPU options.

**Comment by Tyriar** [comment]
Account was deleted and it's not clear what the problem is
