### ISSUE TITLE
Native dialogs are broken, flickering and not readable

### ISSUE THREAD

**Issue by martgut** [microsoft/vscode#173727]
Type: <b>Bug</b>

When running vscode on Ubuntu 2204 in a VirtualBox all native dialogs are broken. They are flickering and the text is not readable.

For testing purpose, I have disabled all extensions and the problem still exists.

Steps to reproduce:
1. Start code without extensions: code --disable-extensions
2. Open a native system dialog: File > Open File...
-> The dialog is broken?!

Expected:
The dialog should be well rendered as it does when using any other application

VS Code version: Code 1.75.0 (e2816fe719a4026ffa1ee0189dc89bdfdbafb164, 2023-02-01T15:29:17.766Z)
OS version: Linux x64 5.15.0-58-generic
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz (4 x 2112)|
|GPU Status|2d_canvas: unavailable_software<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>opengl: disabled_off<br>rasterization: disabled_software<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software<br>webgpu: disabled_off|
|Load (avg)|1, 1, 1|
|Memory (System)|7.76GB (5.53GB free)|
|Process Argv|--disable-extensions . --crash-reporter-id 183dedb0-3400-4024-abf1-1d53c51a75b0|
|Screen Reader|no|
|VM|100%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|wayland|
</details>Extensions disabled<details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
azure-dev_surveyone:30548225
pyindex848:30577860
nodejswelcome1:30587005
2e4cg342:30602488
89544117:30613380
pythonsymbol12:30657548
2i9eh265:30646982

```

</details>

![Screenshot from 2023-02-07 21-46-01](https://user-images.githubusercontent.com/10495275/217363406-7a3a3671-5363-4d2e-9f45-4d465e212efe.png)

**Comment by deepak1556** [comment]
Are the native dialogs rendering fine when you launch from other applications on this VM ? Does the issue repro when you launch with `--disable-gpu` ?

**Comment by martgut** [comment]
1) Yes native dialogs are rendering correctly when I launch them from other applications. Tested with "meld" and the open file dialog. Again with disabled extensions
2) Disabling the gpu as suggested shows the same "broken" dialogs

Note: Interestingly, when I launch "meld" from the integrated terminal in code, also then native dialogs are broken in meld. Launching meld from a standard gnome-terminal, or from the system works fine.

**Comment by deepak1556** [comment]
Are you running on wayland or xorg ? If on wayland, can you try running with `--ozone-platform=wayland --disable-gpu`

**Comment by martgut** [comment]
Yes, I'm running wayland and the additional arguments mentioned above solves the problem :-)
Many Thanks for this workaround!
