### ISSUE TITLE
Shell task error: The term 'x86' is not recognized

### ISSUE THREAD

**Issue by JaneySprings** [microsoft/vscode#173719]
Hello! I want to create a task that uses a path containing 'Program Files (x86)' and that it works independently of the user's terminal. But that's not possible right now.

I created a simple shell task that print a message in the terminal:
```json
{
	"version": "2.0.0",
	"tasks": [
		{
			"type": "shell",
			"label": "Shell task",
			"command": "dir",
			"args": [
				"\"C:\\Program Files (x86)\""
			]
		}
	]
}
```
If you run this task you will get an error:
```
Executing task: dir "C:\Program Files (x86)" 

x86 : The term 'x86' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path 
was included, verify that the path is correct and try again.
```
But on Windows PowerShell it works:
<img width="627" alt="image" src="https://user-images.githubusercontent.com/48021947/217338727-909bc70c-2985-4f1f-b300-9b842c7f644d.png">

You can add single quotes to the path and it will work:
```json
"args": [
    "'C:\\Program Files (x86)'"
]
```
But if you use CMD.exe, then you will get an error:
```
Executing task: dir "'C:\Program Files (x86)'" 

The filename, directory name, or volume label syntax is incorrect.
```

---
Does this issue occur when all extensions are disabled?: Yes
<img width="369" alt="image" src="https://user-images.githubusercontent.com/48021947/217338336-d1190ccd-d210-4db9-af65-683434546d61.png">

**Comment by scriptBoris** [comment]
any updates?

**Comment by Dragonashes** [comment]
I am not too knowledgeable, looks like "" denotes tring which may mean when vscode passes it to terminal the '' tags for spaces be lost, you might try the following though, i think you only need it where spacing is an issue: 
`
"args": [
"C:\\'Program Files (x86)'""
]
`

**Comment by meganrogge** [comment]
Closing as there's a workaround
