### ISSUE TITLE
Hoping that you could add .icns files for Perl and R

### ISSUE THREAD

**Issue by YongLiedu** [microsoft/vscode#173769]
Hoping that you could add `.icns` files for `Perl` and `R`?
Thanks!

**Comment by roblourens** [comment]
Not sure what you are talking about, sorry

**Comment by YongLiedu** [comment]
Files like these:
https://github.com/microsoft/vscode/blob/main/resources/darwin/python.icns
https://github.com/microsoft/vscode/blob/main/resources/darwin/shell.icns

**Comment by roblourens** [comment]
Not sure who owns this but @digitarald looks like you touched these, I'm guessing that Perl and R aren't used in vscode enough for us to add these?
