### ISSUE TITLE
Format code not working for Javascript files

### ISSUE THREAD

**Issue by komorebi-san** [Microsoft/vscode#17374]
- VSCode Version:1.8.0
- OS Version: 10.12.1

Steps to Reproduce:

1. Open Javascript File
2. Right click in editor window, select "Format Code"

**Comment by itamark** [comment]
Windows/Mac?

**Comment by komorebi-san** [comment]
Mac

**Comment by kieferrm** [comment]
@komorebi-san  You choose "Format Document" correct? Or do you actually see a "Format Code" action in the context menu? If so, pls add let us know which extensions you have installed:

`code --list-extensions`

**Comment by komorebi-san** [comment]
Yes, I tried both "Format Document" and also "Format Code" action using both short cuts and command palette. I did not have any extensions at all. 

However, it is working now after I reinstall visual studio code. 

Thanks!
