### ISSUE TITLE
Add option to view default settings in single plain text file

### ISSUE THREAD

**Issue by garfieldbanks** [Microsoft/vscode#17371]
Pretty self explanatory. I don't have anything against the new UI or anything but I don't like that I can no longer see the default settings in a single plain text file.

**Comment by garfieldbanks** [comment]
I'd also like an option to view the user settings as a raw file, (without the little pencils).

**Comment by bpasero** [comment]
@garfieldbanks `"workbench.settings.openDefaultSettings": false`

**Comment by garfieldbanks** [comment]
@bpasero 
That's not quite what I'm looking for. I want to actually see the default settings, but I don't want any dropdowns or anything. Just a raw text file.

**Comment by bpasero** [comment]
Got it 👍

**Comment by sandy081** [comment]
@garfieldbanks Thanks for filing an issue for this. May I know if you do not want `edit` icon or you also do not like to new Grouping and Search bar in default settings? Also, may I know the reason/use case of why you want to see Default settings old way? This will help us in filling the gaps and finding the right balanced solution. 

Thanks

**Comment by garfieldbanks** [comment]
@sandy081
How about a button at the very bottom that opens a new tab with the raw file? Kind of like when you preview something.

**Comment by sandy081** [comment]
@garfieldbanks I can definitely do that or have a command to show the raw file. 
But, I am kind of more interested to know why you would like to need it in first place which the current thing is not doing?

**Comment by sandy081** [comment]
Disabling Quick outline/Go to Symbol/Go to line/Find/Folding was done in favour of new rich functionality in Default Settings.
- Advanced Search and filtering
- Rich Grouping

I would be more interested to know what is missing in new Default settings that is there in Old one and how is it being helpful? So that I can look in bringing the new default settings on par with old one or have an option to show the raw file.

Thanks

**Comment by pierredewilde** [comment]
Thanks for the new Defaults Settings UI. 

With the new integrated search, it's fast to find what we are looking for. 

The old UI was useful to get offline documentation of all settings.

Keybindings UI still uses the old UI. For coherence, both defaults settings and keybindings should have a similar UI.

**Comment by garfieldbanks** [comment]
@sandy081
I don't see any way the new UI could be changed or even that it needs to be changed to be on par with the old one. I actually think it's good.
But a button or command to view the raw file would definitely be nice.

**Comment by sandy081** [comment]
@pierredewilde May I know what you mean by offline documentation? 

>The old UI was useful to get offline documentation of all settings.

@garfieldbanks Definitely, I will provide a command to view default settings as raw file

**Comment by pierredewilde** [comment]
I mean a documented list of all settings to print. Raw (json) file is OK for that purpose.

**Comment by sandy081** [comment]
Added a new command to open Default settings as raw `workbench.action.openRawDefaultSettings`
