### ISSUE TITLE
Quick pick items warning/error handling

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#173716]
Here are three common scenarios in notebooks where we want to present warning/error messages to users and improve the UX

* ~Empty results from a quick pick item entry. This usually happens when users pick a quick pick item, which goes to the next quick pick step, but at the end there is no result in that step. We currently show a placeholder quick pick item there but~
  * ~It might be too late to show this option~
  * ~The quick pick item is not actionable and also doesn't look like a warning/error message, compared to the validation message we usually show in quick picks.~
Dupe of https://github.com/microsoft/vscode/issues/173716

* ~Input validation. When users try to connect VS Code to a remote Jupyter, we would show an error message to users if the server is not available. A common error in browsers is CORS and currently we only show a plain text message to users. It would be helpful if we could show some useful links that users can visit to get the server CORS enabled themselves~ Dupe of https://github.com/microsoft/vscode/issues/82112

<img width="598" alt="image" src="https://user-images.githubusercontent.com/876920/217335650-fbce4c58-4381-4f9e-997e-1dd3e03c0488.png">

* ~Invalid Python environment in the kernel selection list. This usually happens when users have a partially broken Python environment. Jupyter or Python extension might be able to fix it, so we still present it to users (we don't automatically fix it for users, as it requires user consent). Currently, we put a warning codicon in the quick pick item title, but users don't know what the reason behind the "warning" is.~ Dupe of https://github.com/microsoft/vscode/issues/174473

<img width="605" alt="image" src="https://user-images.githubusercontent.com/876920/217336879-775fabce-cd42-4bbe-b3c7-4cacd63fb711.png">

**Comment by daviddossett** [comment]
Seems like there are three different concepts going on here. Some ideas from the hip:

- Input validation: probably makes sense to look like your screenshot above
- Inline warnings: this one looks like it could be more obvious—maybe warning text on the second line could work here?)

<img width="1429" alt="CleanShot 2023-02-08 at 10 25 49@2x" src="https://user-images.githubusercontent.com/25163139/217619151-5890ac82-0fb9-4007-a468-96e4d7e9f0e2.png">

- Empty states: it could be as simple as a diabled item with the option to customize the message? Else it falls back to a sensible default e.g.

<img width="1016" alt="CleanShot 2023-02-08 at 10 26 55@2x" src="https://user-images.githubusercontent.com/25163139/217619477-ad4732a0-ab4d-487e-ae83-a3235dea25e8.png">

**Comment by rebornix** [comment]
Thanks @daviddossett, the proposals above look neat. here is a real world example for scenario 3.

https://user-images.githubusercontent.com/876920/217687409-081fdfd5-57ea-44b7-91e9-8c393c8abb34.mov

On startup, we have two remote servers stored in cache, and we present both of them to users. Only when users pick them, we will attempt to fetch kernels from the server. For the second one, since the server is already dead, we won't get any kernels back but only an error message, which can potentially explain why it fails.

**Comment by TylerLeonhardt** [comment]
This issue captures a lot of different use-cases and now that the dust has settled we should move these into smaller issues.

**Comment by TylerLeonhardt** [comment]
Linked each idea with a respective issue
