### ISSUE TITLE
Increase file structure indentation for subdirectories

### ISSUE THREAD

**Issue by sakgoyal** [microsoft/vscode#173731]
Can there be a way to increase the amount of 'indentation' for the files inside a folder? for me it is hard to tell which files are where because its a little close for me. I was able to use the web version of vscode to modify the html to make it easier to understand what I mean. I feel it would be a good accessibility feature to add this so its much more visually distinct and easier to see. 

I understand its a very small difference, but to me when I used it, it was a significant improvement. 

This is what it currently looks like:
![image](https://user-images.githubusercontent.com/19929553/217381955-7ed210b4-32c2-4529-bcbf-9d8d7134f956.png)

This is what I would like it to be:
![image](https://user-images.githubusercontent.com/19929553/217382024-b349f5bb-f697-4006-bdc5-69721b39227f.png)

I went to the html and edited the indent by changing the `<div class="monaco-tl-twistie" style="padding-left: 16px;">` to `<div class="monaco-tl-twistie" style="padding-left: 26px;">`
Is there a way to do this permanently or add a toggle/slider to increase it?

**Comment by gjsjohnmurray** [comment]
Please see https://github.com/microsoft/vscode/issues/161706#issuecomment-1257229296 and subsequent suggestions on that issue.

**Comment by sakgoyal** [comment]
Oh I see. I didnt realize it was already a thing. I changed the `tree.indent` from 8 -> 17.
