### ISSUE TITLE
automatically show test output

### ISSUE THREAD

**Issue by mfulton26** [microsoft/vscode#173740]
After running tests via the Test Explorer View it was difficult to find the test output at first. Even though I've found it now I have to invoke "Show Output" after each run. I would much rather have it automatically pop up the console output if my tests output anything.

I'm currently using Deno. Running the tests and viewing pass/fail works great but viewing output whenever the test(s) pass isn't. I want to see the test output, open file links logged for more details (HTTP request/response payloads, image files, etc.).

**Comment by connor4312** [comment]
We now have a Test Results view that should cover this
