### ISSUE TITLE
Markdown "shell" code fence language not recognized by Markdown Preview

### ISSUE THREAD

**Issue by redactedscribe** [microsoft/vscode#173735]
Type: <b>Bug</b>

[Shell language](https://github.com/github/linguist/blob/c1c34e5260797b4d598f5ec76f19723bfc5a1894/lib/linguist/languages.yml#L6204).

` ```sh `:
![sh](https://user-images.githubusercontent.com/25013746/217386418-85694790-fddc-4c7a-917a-37a4a7d1f636.png)

` ```shell `:
![shell](https://user-images.githubusercontent.com/25013746/217386419-214ac290-3626-4e51-a777-4b812f9eca1e.png)

` ```plaintext ` (for comparison):
![c3](https://user-images.githubusercontent.com/25013746/217387000-33d66715-fbaf-442b-aee8-b07ba64e0dc8.png)

VS Code version: Code - Insiders 1.76.0-insider (25514d899f4bd877803defb213719f8af3d997d3, 2023-02-07T05:22:19.428Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: Yes

Extensions: none

**Comment by mjbvz** [comment]
See 934e0ee5d87ba5d4b6f5ceb6914d1fbacced8532 for a very similar fix

**Comment by Aravindh-Raju** [comment]
I can work on this if that’s ok.

**Comment by maski07** [comment]
@mjbvz 
I submitted a pull request. If it looks good, would you please consider merging it?

**Comment by maski07** [comment]
Sorry, I made a mistake with the issue number of pull request's title.
I corrected the title of the pull request

**Comment by Aravindh-Raju** [comment]
> I am working on this.

Opened a PR: [Update shell code markdown (Fixes #173735)](https://github.com/microsoft/vscode/pull/174523). Have a look at it!
