### ISSUE TITLE
Add git push button and shortcut

### ISSUE THREAD

**Issue by tinganho** [Microsoft/vscode#17380]
Could you add a git push button to this bar?

<img width="184" alt="screen shot 2016-12-16 at 09 59 46" src="https://cloud.githubusercontent.com/assets/1324476/21257102/6449d2c6-c376-11e6-8d33-4dc5e65904a4.png">

And probably add a shortcut?

I think having to click the dropdown is to much effort everytime I need to push. Using the command palette is also not very effortless.

**Comment by Yayuro** [comment]
+1

**Comment by coreh** [comment]
Would also be nice to have the *Pull* option, and holding down option/alt could change it into *Pull (Rebase)*.

I wonder what good icons for Push / Pull / Pull (Rebase) would be?

**Comment by kieferrm** [comment]
@tinganho have you tried clicking the area I highlighted on the status bar?
<img width="217" alt="screen shot 2016-12-17 at 7 08 30 am" src="https://cloud.githubusercontent.com/assets/4674940/21287752/e8dce68e-c427-11e6-88f4-7ab1ee9cbaf3.png">

**Comment by tinganho** [comment]
Lots of hidden features in VSCode 😄 

Though, I think it still would be good with a shortcut.

**Comment by joaomoreno** [comment]
The action is in the overflow menu: 

![image](https://cloud.githubusercontent.com/assets/22350/21605149/6a852ee4-d1a7-11e6-9c7b-a975c131a688.png)
