### ISSUE TITLE
zsh terminal's prompt customization shows weird behaviour with an added function

### ISSUE THREAD

**Issue by sokratis95** [microsoft/vscode#173864]
Type: <b>Bug</b>

Hi,

I have customized the terminal's prompt (zsh terminal) adding some different colors and a function that shows me the current git branch (in case I am in a directory that is actually git managed, otherwise it does not show any information about git branch)

Here you can see the custom part of the zshrc file:

# Find and set branch name var if in git repository.
function git_branch_name()
{
  branch=$(git symbolic-ref HEAD 2> /dev/null | awk 'BEGIN{FS="/"} {print $NF}')
  if [[ $branch == "" ]];
  then
    :
  else
    echo '('$branch')'
  fi
}

setopt PROMPT_SUBST

#   Change Prompt
#   ------------------------------------------------------------
    export PS1='%F{green}%n@M-LP4PWGY0G1 %f%F{blue}%B%~%b%f %F{red$(git_branch_name)%f$ '

The outcome of this customization is to see the below specified prompt both in Apple's default Terminal and in iTerm apps (the directory is not git managed) (the colors are not visible in this reporting form)
sokratis@M-LP4PWGY0G1 /etc $ 

Opening the zsh terminal in VSC (is set to be the default option for MacOS) seems to face an issue with the created function and has the following prompt:
sokratis@M-LP4PWGY0G1 /etc 

As you may see the $ symbol is omitted and afterwards the characters typed have red color (the one that should the not existent git branch name have). 

Could it be an issue that VSC has with the use of custom functions in zsh terminal, since the other customizations work flawlessly in VSC's terminal.

*In bash terminal, which I use in a linux enviroment there is no problem with the prompt in VSC.

Thanks for your time!
BRs,
Sokratis

VS Code version: Code 1.75.0 (e2816fe719a4026ffa1ee0189dc89bdfdbafb164, 2023-02-01T15:26:31.005Z)
OS version: Darwin arm64 21.6.0
Modes:
Sandboxed: No
Remote OS version: Linux x64 3.10.0-1160.62.1.el7.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|2, 3, 3|
|Memory (System)|16.00GB (0.11GB free)|
|Process Argv|--crash-reporter-id 10286c9c-dfc6-4589-bc94-d1f2e1d60084|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: goudousi|
|OS|Linux x64 3.10.0-1160.62.1.el7.x86_64|
|CPUs|Intel(R) Xeon(R) CPU E5-2620 v4 @ 2.10GHz (32 x 1200)|
|Memory (System)|62.65GB (26.55GB free)|
|VM|0%|
</details><details><summary>Extensions (24)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-intelephense-client|bme|1.9.5
doxdocgen|csc|1.4.0
docs-markdown|doc|0.2.117
githistory|don|0.6.19
gitlens|eam|13.2.0
prettier-vscode|esb|9.10.4
vscode-pull-request-github|Git|0.58.0
better-cpp-syntax|jef|1.17.2
git-graph|mhu|1.30.0
vscode-docker|ms-|1.23.3
jupyter-keymap|ms-|1.0.0
remote-containers|ms-|0.275.1
remote-ssh|ms-|0.96.0
remote-ssh-edit|ms-|0.84.0
remote-wsl|ms-|0.75.1
cmake-tools|ms-|1.13.45
cpptools|ms-|1.13.9
cpptools-extension-pack|ms-|1.3.0
remote-explorer|ms-|0.2.0
vsliveshare|ms-|1.0.5828
vsliveshare-audio|ms-|0.1.93
cmake|twx|0.0.17
vscode-icons|vsc|12.2.0
php-debug|xde|1.31.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
azure-dev_surveyone:30548225
pyindex848:30577860
nodejswelcome1:30587005
282f8724:30602487
89544117:30613380
pythonsymbol12cf:30657549
a9j8j154:30646983
vscodedisable:30660115

```

</details>

**Comment by meganrogge** [comment]
disabling shell integration will probably fix this `terminal.integrated.shellIntegration.enabled`
