### ISSUE TITLE
Error: the "file" argument must be of type string. received an instance of Object. (when spawning an electron child process)

### ISSUE THREAD

**Issue by doradsoft** [microsoft/vscode#173809]
**Type:** regression

**System Information:**
```
CPUs | Intel(R) Core(TM) i7-9850H CPU @ 2.60GHz (12 x 2592)
GPU Status | 2d_canvas: enabled canvas_oop_rasterization: disabled_off direct_rendering_display_compositor: disabled_off_ok gpu_compositing: enabled multiple_raster_threads: enabled_on opengl: enabled_on rasterization: enabled raw_draw: disabled_off_ok skia_renderer: enabled_on video_decode: enabled video_encode: enabled vulkan: disabled_off webgl: enabled webgl2: enabled webgpu: disabled_off
Memory (System) | 15.73GB (2.79GB free)
Screen Reader | no
VM | 0%
```

**Enabled extensions:**
`Extensions: none`

**Version with bug:**
Version: 1.75.0 (system setup)
Commit: e2816fe719a4026ffa1ee0189dc89bdfdbafb164
Date: 2023-02-01T15:23:45.584Z
Electron: 19.1.9
Chromium: 102.0.5005.194
Node.js: 16.14.2
V8: 10.2.154.23-electron.0
OS: Windows_NT x64 10.0.19044
Sandboxed: No

and

Version: 1.76.0-insider (system setup)
Commit: a7d49b0f35f50e460835a55d20a00a735d1665a3
Date: 2023-02-08T05:24:04.744Z
Electron: 19.1.9
Chromium: 102.0.5005.194
Node.js: 16.14.2
V8: 10.2.154.23-electron.0
OS: Windows_NT x64 10.0.19044
Sandboxed: Yes

**Latest version without bug:**
```
Version: 1.74.3 (system setup)
Commit: 97dec172d3256f8ca4bfb2143f3f76b503ca0534
Date: 2023-01-09T16:59:02.252Z
Electron: 19.1.8
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.19044
Sandboxed: No
```

Steps to reproduce:
1. install [1.74.3](https://update.code.visualstudio.com/1.74.3/win32-x64/stable) version
2. clone [reproduce repository](https://github.com/doradsoft/vscode-issue-173809-reproduce). TL;DR of it is: `spawnSync(electron);`
3. open repository folder
4. install dependencies using `npm i`
5. run "Run Extension" configuration
![Run Extension](https://user-images.githubusercontent.com/5598420/217538373-e8b0773d-c923-4465-a28b-18a129e462eb.png)
6. open command palette (ctrl+shift+p)
![command palette](https://user-images.githubusercontent.com/5598420/217535960-52fef0a0-507e-420e-bdb5-6c4b63581748.png)
7. choose Hello World
8. on latest working version, a window would open: 
![image](https://user-images.githubusercontent.com/5598420/217537740-55297c38-be85-4167-a16f-dca6b4dc2f3d.png)
9. install [1.75.0](https://update.code.visualstudio.com/1.75.0/win32-x64/stable) version
10. repeat 5-7
11. an error message appears:
![error message](https://user-images.githubusercontent.com/5598420/217539661-1ea9b698-0b28-42cd-8ea5-821fb340d15e.png)

**Comment by doradsoft** [comment]
Any help would be greatly appreciated since we have been unable to find a workaround. @deepak1556

**Comment by doradsoft** [comment]
Problem persists in 1.76.0

**Comment by jsebrd** [comment]
I am also seeing this error in VSCode when opening a folder with a C# .sln file.  It started after a recent update and was never present before.

```
Error!
The "file" argument must be of type string. Received an instance of Object
```

```
Version: 1.81.0-insider (Universal)
Commit: 02d3b49d8035a9b30db3b0ae706796af9b1a4260
Date: 2023-07-17T05:33:53.966Z
Electron: 22.3.14
ElectronBuildId: 21893604
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Darwin arm64 22.6.0
```

.NET Runtimes

```
Microsoft.AspNetCore.App 3.1.32 [/home/jesse/.dotnet/shared/Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 6.0.19 [/home/jesse/.dotnet/shared/Microsoft.AspNetCore.App]
Microsoft.NETCore.App 3.1.32 [/home/jesse/.dotnet/shared/Microsoft.NETCore.App]
Microsoft.NETCore.App 6.0.19 [/home/jesse/.dotnet/shared/Microsoft.NETCore.App]
```

.NET SDKs

```
3.1.426 [/home/jesse/.dotnet/sdk]
6.0.411 [/home/jesse/.dotnet/sdk]
```

OS

```
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.2 LTS
Release:        22.04
Codename:       jammy
```

**Comment by deepak1556** [comment]
This changed with our move to use [utility process](https://github.com/electron/electron/blob/main/docs/api/utility-process.md) for the extension host which now has a builtin `electron` module https://github.com/electron/electron/blob/main/lib/utility/api/exports/electron.ts that conflicts when resolving the npm package. You can either fork a process from the extension and perform the electron application launch from there or use absolute path to workaround this issue.


```patch
diff --git a/extension.js b/extension.js
index e79557e..b1bb371 100644
--- a/extension.js
+++ b/extension.js
@@ -1,8 +1,7 @@
 // The module 'vscode' contains the VS Code extensibility API
 // Import the module and reference it with the alias vscode in your code below
 const vscode = require("vscode");
-const electron = require("electron");
-const { spawnSync } = require("child_process");
+const { fork } = require("child_process");
 
 // this method is called when your extension is activated
 // your extension is activated the very first time the command is executed
@@ -23,10 +22,7 @@ function activate(context) {
   let disposable = vscode.commands.registerCommand(
     "extension.helloWorld",
     () => {
-      // The code you place here will be executed every time your command is executed
-      const spawn_env = JSON.parse(JSON.stringify(process.env));
-      delete spawn_env.ELECTRON_RUN_AS_NODE;
-      spawnSync(electron, [`${__dirname}/main.js`], { env: spawn_env });
+      fork(`${__dirname}/child.js`);
     }
   );
```

```js
// child.js

const electron = require("electron");
const { spawnSync } = require("child_process");

const spawn_env = process.env;
delete spawn_env.ELECTRON_RUN_AS_NODE;
spawnSync(electron, [`${__dirname}/main.js`], { env: spawn_env });
```
