### ISSUE TITLE
List items get rules for quick picks or suggest lists

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#173805]
I see this from time to time, it is not just happening reproducible. I wonder if it could be caused by more CSS getting loaded:

![image](https://user-images.githubusercontent.com/900690/217539291-6213953b-15be-4218-9516-e2c9e5745c9a.png)

**Comment by Tyriar** [comment]
Related: https://github.com/microsoft/vscode/issues/173611, https://github.com/microsoft/vscode/pull/172668

**Comment by aeschli** [comment]
While trying to reproduce today, I also came to strange scenarios where the stylesheet for a list would contain rules for the suggest widget list.

**Comment by aeschli** [comment]
Ok, found the problem 🤭
