### ISSUE TITLE
Markdown preview: Allow copying images an opening image in a new editor

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#173876]
It would be great if we had a custom context menu in markdown preview now that webviews can support that:

![image](https://user-images.githubusercontent.com/2193314/217637687-2542d4d7-3271-40e6-858d-fa3c1bad3213.png)

**Comment by weartist** [comment]
I would like to solve this problem, maybe someone would like to provide some advice?

**Comment by MeghanKulkarni** [comment]
[Copy Image has been implemented
](https://github.com/microsoft/vscode/pull/184432#user-content-fn-1-c0f76e1daaa971d8147c5ce6f536e197)[Open Image still needs to be implemented
](https://github.com/microsoft/vscode/issues/184553)
