### ISSUE TITLE
vscode always crashes on first startup with error code: 5

### ISSUE THREAD

**Issue by RobPellowski** [microsoft/vscode#173822]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.75.0 (Universal)
- OS Version: MacOS Ventura Version 13.1

Steps to Reproduce:

1. Run `vscode` (with or without extensions disabled)
2. `vscode` tries to run a script (`MPLABX-v5.50-linux-installer.sh`)
    The named self-installer bundle exists but I'm already on v6.0
    I deleted the `.vscode` directory with no change
3. `vscode` crashes with exit code 5

`vscode --verbose` started from the command line shows this and similar lines, but there seems no way to modify the behavior:

`[History stack global-default]: notifyNavigation() not ignoring (editor: file:///Users/rob/Downloads/MPLABX-v5.50-linux-installer.sh, event: <none>)", source: vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js (616)
`

**Comment by deepak1556** [comment]
Does the crash repro with a new profile ? From the vscode command palette run `Profiles: Create a Temporary Profile`

**Comment by RobPellowski** [comment]
Can't repro this. The issue can be closed.
