### ISSUE TITLE
Explorer collapse all button doesn't work in insiders

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#173837]
Explorer as secondary side bar:

<img width="372" alt="image" src="https://user-images.githubusercontent.com/2193314/217596409-26c6bb03-5918-4e2d-9f24-0bad29fbfaf6.png">

<img width="406" alt="image" src="https://user-images.githubusercontent.com/2193314/217596531-d25a50c5-59f1-424f-a291-d8f7c6be4bfd.png">

Dragging it back to side bar and back made it work though

**Comment by lramos15** [comment]
I can't seem to repro this? Do you have any repro steps that hit this all the time? I've moved the explorer around a bunch and tried the collapse all button.

**Comment by Tyriar** [comment]
This might have been when I downgraded vscode, will reopen if I see it again
