### ISSUE TITLE
Dark+ V2 (Experimental) feedback

### ISSUE THREAD

**Issue by sheikhlimon** [microsoft/vscode#173899]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.75.0
- OS Version: Zorin OS 16.2

Steps to Reproduce:

1. IntelliSense options are hard to understand due to similar color schemes

![Screenshot from 2023-02-08 14-33-19](https://user-images.githubusercontent.com/76746201/217736532-63668013-8a27-4b33-8379-305c3bd9f0eb.png)

**Comment by daviddossett** [comment]
Thanks @sheikhlimon. Just to clarify, is this about the background color of the currently selected list item?

**Comment by sheikhlimon** [comment]
> Thanks @sheikhlimon. Just to clarify, is this about the background color of the currently selected list item?

Yes

**Comment by daviddossett** [comment]
Ok, thanks. I can explore some options here. Will leave this open to collect more feedback in the meantime.

**Comment by ddbrierton** [comment]
I’m rather pleased @sheikhlimon created this issue. This is something that has mildly bugged me for a long time. It seems to be an issue with most themes, not just the default ones shipped with VS Code. I’m not sure what the official VS Code terminology is for these sorts of transient popovers, but all of them seem to have the same background-colour as the editor and as a result can be sometimes (depending on context) rather hard to read and create a sense of visual  confusion. Here are a few more examples.

<img width="606" alt="Screenshot 2023-02-25 at 04 00 02" src="https://user-images.githubusercontent.com/7255543/221332801-f54a1700-a42b-4934-9eaf-35fdaad9dba3.png”>

<img width="606" alt="Screenshot 2023-02-25 at 04 00 15" src="https://user-images.githubusercontent.com/7255543/221332827-a84e138e-eaec-4c5a-aa48-c14aae674c67.png">

<img width="606" alt="Screenshot 2023-02-25 at 04 00 37" src="https://user-images.githubusercontent.com/7255543/221332833-429b4f8e-e218-48af-9968-4898260aadc5.png">

**Comment by sheikhlimon** [comment]
> I’m rather pleased @sheikhlimon created this issue. This is something that has mildly bugged me for a long time. It seems to be an issue with most themes, not just the default ones shipped with VS Code. I’m not sure what the official VS Code terminology is for these sorts of transient popovers, but all of them seem to have the same background-colour as the editor and as a result can be sometimes (depending on context) rather hard to read and create a sense of visual confusion. Here are a few more examples.
> 
> <img alt="Screenshot 2023-02-25 at 04 00 02" width="606" src="https://user-images.githubusercontent.com/7255543/221332905-6861a3b6-b501-4e7d-9535-c5e87a9cb6da.png">
> 
> <img alt="Screenshot 2023-02-25 at 04 00 15" width="606" src="https://user-images.githubusercontent.com/7255543/221332827-a84e138e-eaec-4c5a-aa48-c14aae674c67.png">
> 
> <img alt="Screenshot 2023-02-25 at 04 00 37" width="606" src="https://user-images.githubusercontent.com/7255543/221332833-429b4f8e-e218-48af-9968-4898260aadc5.png">

Yeah it's been bugging me for a long time to the point where I was looking to turn it off. Specifically when opening brackets it automatically pops up and I can't even see what I'm writing. It's drives me nuts sometimes. 😅

**Comment by robcaldecott** [comment]
I am seeing a strange issue with the new theme when pasting text into a `zsh` terminal window when running VS Code on my second monitor. I am using a MacBook M2 running Ventura 13.2.1. It looks like an aliasing issue of some kind.

**Dark+ V2**
![image](https://user-images.githubusercontent.com/796702/221511298-8c235465-47a8-43fc-9d30-6e158684e00c.png)

**Dark V1**
![image](https://user-images.githubusercontent.com/796702/221511495-a1d0f568-e657-44bd-823a-e1e386528e7b.png)

I have tried other popular dark themes (GitHub, Night Owl, etc.) and none of them exhibit this behaviour.

I am using a relatively simple custom prompt (using the one supplied [here](https://gist.github.com/reinvanoyen/05bcfe95ca9cb5041a4eafd29309ff29#install).)

Any ideas are welcome.

**Comment by ddbrierton** [comment]
> @ddbrierton I hear you. Since this isn't about the list items and their hover/selected/etc. behavior, rather the background color itself, could you open a separate issue so I can keep track of it?

Done. #175551

**Comment by zm-cttae** [comment]
This seems like a good chance to adjust syntax colors much further.
Basically giving the syntax a similar hue and contrast vs the background.

Colors that seem distinctly "ugly" or an A11Y hazard like the green of the comments can get updated entirely too.

**Comment by daviddossett** [comment]
@zm-cttae that's something I'll probably look at as a next step once the themes officially ship. Feel free to open up a new issue if you have thoughts about what it could look like 👍

**Comment by daviddossett** [comment]
Hey folks, just getting around to this. Here are the fixes from #189591 

The basic idea is that widgets on a higher z-index will use slightly brighter background colors to simulate them being brought closer to the light source. Hopefully that helps distinguish between the widgets and their background.

I also reverted my changes to the list selection background so they will be closer to Dark+ in behavior for now. Will tweak based on feedback.

<img width="862" alt="CleanShot 2023-08-03 at 15 57 33@2x" src="https://github.com/microsoft/vscode/assets/25163139/d7c435b1-55c5-4b2c-b943-b6b7f9f0f734">
<img width="871" alt="CleanShot 2023-08-03 at 15 57 44@2x" src="https://github.com/microsoft/vscode/assets/25163139/94e54acf-32fe-4d3c-a6af-aadf93a1e389">
<img width="713" alt="CleanShot 2023-08-03 at 16 02 29@2x" src="https://github.com/microsoft/vscode/assets/25163139/03fba704-9e91-492a-853b-1b4eef83ad41">
<img width="692" alt="CleanShot 2023-08-03 at 16 02 36@2x" src="https://github.com/microsoft/vscode/assets/25163139/2e69fbfa-aed2-4dbf-948d-7b1cefc6d37f">
