### ISSUE TITLE
Enabling tracing causes TS Server to crash repeatedly on windows

### ISSUE THREAD

**Issue by sanket-bhalerao** [microsoft/vscode#173854]
Type: <b>Bug</b>

typescript server keeps crashing after the latest update VSCODE
![image](https://user-images.githubusercontent.com/9264813/216545222-080a03e1-c68a-472d-8d9c-6b5b96f9f10f.png)

I can reproduce this with all the extensions disabled.

LOG: 
![image](https://user-images.githubusercontent.com/9264813/216608706-6b1bd415-a2b9-4503-bef2-98f430e91107.png)

VS Code version: Code - Insiders 1.76.0-insider (c4a609f94329b17d91cd13a4fd113d1abfe5ec1f, 2023-02-03T05:23:17.202Z)
OS version: Windows_NT x64 10.0.19044
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.82GB (4.69GB free)|
|Process Argv|--crash-reporter-id e5294b27-02c9-4438-b8f3-90acb1091b3b|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|15.1.0
atlascode|atl|3.0.1
vscode-markdownlint|Dav|0.49.0
vscode-eslint|dba|2.2.6
githistory|don|0.6.19
gitlens|eam|13.2.0
prettier-vscode|esb|9.10.4
vscode-yaml|red|1.11.0
sonarlint-vscode|Son|3.14.0
code-spell-checker|str|2.16.0
vscode-stylelint|sty|1.2.3

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vslsvsres303:30308271
pythonvspyl392:30422396
pythontb:30258533
vsc_aacf:30263846
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscod805:30301674
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30404738
cppdebug:30492333
vscaat:30438846
vsclangdf:30492506
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30618038
pylantcb52:30590116
pyindex848:30611229
nodejswelcome1:30587009
pyind779:30611226
pythonsymbol12:30651887
showlangstatbar:30657381

```

</details>

**Comment by nguerrera** [comment]
Yay, thank you @mjbvz and @sanket-bhalerao!
