### ISSUE TITLE
Icons in Explorer Panel messed up

### ISSUE THREAD

**Issue by polatengin** [Microsoft/vscode#17388]
After updating to 1.9.0 Insider version, icon's in Explorer Panel seems off.

![explorer-panel](https://cloud.githubusercontent.com/assets/118744/21259316/8241b402-c389-11e6-8ae5-5f86e77734a8.png)

- VSCode Version: Code - Insiders 1.9.0-insider (89bdb7c35a89535612d386199ee33e6bd74ee068, 2016-12-15T07:11:14.563Z)
- OS Version: Windows_NT ia32 10.0.14986
- Extensions:

|Extension|Author|Version|
|---|---|---|
|path-intellisense|christian-kohler|1.2.0|
|python|donjayamanne|0.5.5|
|cpptools|ms-vscode|0.9.3|
|csharp|ms-vscode|1.5.3|
|typescript-javascript-grammar|ms-vscode|0.0.12|
|debugger-for-edge|msjsdiag|0.4.1|
|vscode-docker|PeterJausovec|0.0.10|
|autoimport|steoates|1.2.2|
|unity-debug|Unity|1.1.0|
|cordova-tools|vsmobile|1.2.4|
|vscode-react-native|vsmobile|0.2.4|

---

Steps to Reproduce:

1. Open VS Code latest Insider version
2. Use Seti as File Icon Theme
3. Add files to folder

**Comment by bpasero** [comment]
#17277
