### ISSUE TITLE
hash of url parsed as hex color

### ISSUE THREAD

**Issue by wayou** [microsoft/vscode#173891]
Type: <b>Bug</b>

- the hash part of a url is incorrectly parsed as hex color

VS Code version: Code - Insiders 1.76.0-insider (a7d49b0f35f50e460835a55d20a00a735d1665a3, 2023-02-08T05:37:09.370Z)
OS version: Darwin arm64 22.2.0
Modes:
Sandboxed: Yes

<img width="283" alt="image" src="https://user-images.githubusercontent.com/3783096/217703952-07c1ee7a-5534-47be-b80f-ca2d42880a1e.png">

**Comment by aeschli** [comment]
In which language is this?

**Comment by wayou** [comment]
javascript

**Comment by aeschli** [comment]
Does this reproduce with extensions disabled?

**Comment by wayou** [comment]
Not reproduce with extension disabled. Thx!
