### ISSUE TITLE
TS language service seems to ignore the tsconfig.json in the open workspace

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode#173882]
The TypeScript language service doesn't seem to be respecting the tsconfig.json; I'm always getting completions for browser APIs even if I specify `noLib: true` or manually specify the `lib` array in the `compilerOptions`. I'm also not getting completions from other flies in the `include` array.

For testing, I'm using projects that I imported via the MakeCode Arcade extension. The completions/language service works fine in this scenario in desktop VS code.

Reported by @riknoll

**Comment by mjbvz** [comment]
Falls under #170920
