### ISSUE TITLE
Minimap slider position not updated correctly when scrolling all the way to the top.

### ISSUE THREAD

**Issue by Dromantor** [microsoft/vscode#173858]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.75.0
- OS Version: W10 22H2
```
Version: 1.75.0 (system setup)
Commit: e2816fe719a4026ffa1ee0189dc89bdfdbafb164
Date: 2023-02-01T15:23:45.584Z
Electron: 19.1.9
Chromium: 102.0.5005.194
Node.js: 16.14.2
V8: 10.2.154.23-electron.0
OS: Windows_NT x64 10.0.19045
Sandboxed: No
```

Steps to Reproduce:

![miniscroll](https://user-images.githubusercontent.com/1822013/217622460-46ec6f75-3f26-490c-97d8-9b1cebe39431.gif)

If you scroll to the top end of a file via the minimap slider it isn't correctly positioned at the top after reaching the top end of the file. Instead it gets stuck (one frame/update interval?) below. Boundary check issue?
This doesn't happen on the bottom end.

Edit: Also happens when using the normal scrollbar instead of the minimap's slider; the minimap slider just stays behind. Didn't check that yesterday.

**Comment by infacto** [comment]
I can confirm this bug. In the video below you can see that the minimap never scrolls to top. Even if you scroll slow or navigate in text editor. The first line is never included in the minimap editor view. This is maybe the reason for the weird behavior on faster scroll.

[demo.webm](https://user-images.githubusercontent.com/60390085/227483331-e1c3fde7-4650-4047-9e5e-37615e38e533.webm)

Tested with latest insider version with all extentions disabled and default settings. But I recommend to set the following setting for better visibility of the minimap:

```json
{
    "editor.minimap.showSlider": "always"
}
```

Download: [test.txt](https://github.com/microsoft/vscode/files/11060559/test.txt)

VSCode 1.77.0-insider

**Comment by Tinynja** [comment]
Can confirm this issue is still present in 1.77.3

**Comment by infacto** [comment]
Still waiting...
Workaround: Set setting `editor.padding.top` to > 0.

```json
{
  "editor.padding.top": 1
}
```

**Comment by Dromantor** [comment]
I mean, not even proposing a solution helped, so I expect this to be broken for another ... hmm ... 10 months?
