### ISSUE TITLE
Feature: Add terminal.integrated.startPath

### ISSUE THREAD

**Issue by unional** [Microsoft/vscode#17387]
- VSCode Version: 1.8.0

This allows better support for fixed folder structure repository / multiple packages repositories.

For example, a repo look like this:

```sh
depot
- main
  - management
    - ui
      - frontend
        - web-portal
      - mobile
  - backend
  - tools
  - scripts
  - test
```

I need to open the "main" folder in code so I can access other codes, but my main focus of work is in "web-portal"

Currently, when I open the terminal, it starts in "/depot/main" and I have to "cd management/ui/frontend/web-portal" every time before I can do my work e.g. `npm test` or `npm i -D typescript`.

It would be nice to add a workspace setting `terminal.integrated.startPath` which take a relative or absolute path (in my case "./management/ui/frontend/web-portal").

**Comment by Tyriar** [comment]
I created an extension to solve this issue https://marketplace.visualstudio.com/items?itemName=Tyriar.vscode-terminal-here

**Comment by unional** [comment]
Thanks for sharing.
That is nice but does not have the feature I am looking for.
Will open an issue there.

**Comment by Tyriar** [comment]
I actually skimmed and  misunderstood the request. I think this would actually fit best in vscode rather than the extension when you consider workspace settings.

**Comment by Tyriar** [comment]
@unional this is coming in 1.9 as you wanted by called `terminal.integrated.cwd` instead.

**Comment by Tyriar** [comment]
To verifier please test the following:

- New terminals start at workspace root when `terminal.integrated.cwd` is not set
- New terminals start at `terminal.integrated.cwd` when a valid absolute path is used
- New terminals start at `terminal.integrated.cwd` relative to workspace root when a valid relative path is used
- Terminals launched by the API should *always* launch at the workspace root like before

Note that this is a known issue #17450
