### ISSUE TITLE
debugger disconnects after setting a breakpoint

### ISSUE THREAD

**Issue by Let0s** [Microsoft/vscode#17389]
- VSCode Version: 1.8.0 (also tested on 1.7.2)
- OS: Windows 7

Steps to Reproduce:
1.  Set a breakpoint on 2nd line;
2. Run node debugger;
3. press F10 (Step Over);
4. press F9 (set a breakpoint on current paused line [3rd line])

Note 1: it seems to be a floating bug, because sometimes it can't be reproduced on 4th step, and then we need to unset breakpoint and set it again (maybe even many times).

Note 2: if after 3rd step remove a breakpoint on 2nd line (then no one active breakpoints left) then 4th step will not cause this bug.

My sample filename is 'Файл.js' (it's important to make filename with cyrillic symbols, because i can't reproduce it in file with latin name)
My sample code is
```
let a = 34;
a += 23;
console.log(a);
```

my log with 'trace: all' option is

node --debug-brk=20583 --nolazy Файл.js 
9948: _attach: address: 127.0.0.1 port: 20583
Debugger listening on [::]:20583
9948: _attach: connected
9948: _stopped: got break event from node
9948: _stopped: new ref cache
9948: _analyzeBreak: suppressed stop-on-entry event
9948: _initialize: got process id 9688 from node
9948: _injectDebuggerExtensions: frame based code injection successful
9948: _startInitialize: stopped: true
9948: _startInitialize: got break on entry event after 0 retries
9948: _startInitialize2: fire initialized event
9948: _startInitialize2: remember to do a 'Continue' later
9948: setBreakPointsRequest: {"path":"d:\\Temp\\Файл.js","name":"Файл.js"} [{"line":2}]
9948: _setBreakpoint: {"type":"scriptRegExp","target":"^(.*[\\/\\\\])?[dD]:\\\\Temp\\\\Файл\\.js$","line":1,"column":0}
9948: _updateBreakpoints: result [{"verified":true,"line":2,"column":1}]
9948: setFunctionBreakPointsRequest: result []
9948: setExceptionBreakPointsRequest: ["uncaught"]
9948: configurationDoneRequest: do a 'Continue'
9948: _stopped: got break event from node
9948: _stopped: new ref cache
9948: stackTraceRequest: vscode_backtrace 0 20
9948: NodeV8Protocol hook: ref cache size: 20
9948: __readFile: d:\Temp\Файл.js
9948: _loadScript: 63
9948: NodeV8Protocol hook: ref cache size: 21
9948: scopesRequest: scope 0
9948: NodeV8Protocol hook: ref cache size: 24
9948: _resolveToCache: vscode_lookup 4 handles
9948: NodeV8Protocol hook: ref cache size: 32
9948: _resolveToCache: vscode_lookup 1 handles
9948: _resolveToCache: vscode_lookup 2 handles
9948: NodeV8Protocol hook: ref cache size: 57
9948: _stopped: got break event from node
9948: _stopped: new ref cache
9948: stackTraceRequest: vscode_backtrace 0 20
9948: NodeV8Protocol hook: ref cache size: 20
9948: scopesRequest: scope 0
9948: NodeV8Protocol hook: ref cache size: 23
9948: _resolveToCache: vscode_lookup 4 handles
9948: NodeV8Protocol hook: ref cache size: 31
9948: _resolveToCache: vscode_lookup 1 handles
9948: _resolveToCache: vscode_lookup 2 handles
9948: NodeV8Protocol hook: ref cache size: 56
9948: setBreakPointsRequest: {"name":"d:\\Temp\\Файл.js","path":"d:\\Temp\\Файл.js","sourceReference":0} [{"line":2},{"line":3}]
9948: _terminated: socket end
9948: _terminated: node v8protocol close
9948: shutdown: kill debugee and sub-processes
9948: disconnectRequest: send response
9948: _terminated: target exited
9948: _terminated: target closed

**Comment by Let0s** [comment]
P.S. I could reproduce this without 3rd step

**Comment by weinand** [comment]
@Let0s does this problem no longer occur?

**Comment by Let0s** [comment]
This issue was mistakenly reported here because actual problem belongs to Node.js. This problem should be resolved once this PR https://github.com/nodejs/node/pull/11841 will be merged

**Comment by weinand** [comment]
@Let0s great, thanks for the info!
