### ISSUE TITLE
Flickering and weird color blocks in editor

### ISSUE THREAD

**Issue by fbnlsr** [Microsoft/vscode#17385]
- VSCode Version: 1.8
- OS Version: MacOS Sierra 10.12.1

Steps to Reproduce:

1. Open the command palette and start typing or click a line anywhere
2. Blocks either start to flicker (when typing) or are just present

This behavior is particularly visible when using themes. For instance, here's a screenshot using Solarized Dark:

![screen shot 2016-12-16 at 10 59 36](https://cloud.githubusercontent.com/assets/1923346/21258783/df7a7574-c37e-11e6-9277-00ac15effa47.JPG)

And here, using Atom One Dark:

![screen shot 2016-12-16 at 10 49 52](https://cloud.githubusercontent.com/assets/1923346/21258729/99174710-c37e-11e6-97a1-68036fbccdd6.JPG)

It's also present when using Code's default theme, but a bit more subtle.

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/12473
