### ISSUE TITLE
Autocompletion deleting script reference in HTML

### ISSUE THREAD

**Issue by Syrev** [Microsoft/vscode#17383]
- VSCode Version: Code 1.8.0 (38746938a4ab94f2f57d9e1309c51fd6fb37553d, 2016-12-13T17:45:32.595Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

|Extension|Author|Version|
|---|---|---|

---

Steps to Reproduce:

1. Creating an HTML project 
2. Add script reference in it including type as first attribute and then the src with existing
- Like this one:   <script type="text/javascript" src="test.js"> </script> 
- Or just incliding the src like this :  <script src="test.js"> </script> 
3. The use auto-completion ( Maj+alt+F) and all script reference are remplaced by:  </script>
N.B.: if  only one script as the type attributes after src like this <script src="test.js" type="text/javascript" > </script> and is not the first referenced there is no more problem. If the reference script doesn't exists the reference isn't delede

**Comment by aeschli** [comment]
I'm confused, autocompletion is 'Ctrl+Space'. Where in the code snippet is the cursor when you do this?

**Comment by aeschli** [comment]
Closing due to lack of information.
