### ISSUE TITLE
Extension with proposed API can be published using arg --noVerify

### ISSUE THREAD

**Issue by Eskibear** [microsoft/vscode#173810]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.75.0
- OS Version: ALL

Steps to Reproduce:

1. create a new vscode extension
2. enable proposed api `treeItemCheckbox` in package.json
```
	"enabledApiProposals": [
		"treeItemCheckbox"
	],
```
3. implement a tree view, provide tree items with checkboxes using the api
4. publish it using command `vsce publish --noVerify`

Current behavior:
- The extension with proposed API enabled can be successfully published to marketplace.
- In both stable & insiders version, `treeItemCheckbox` api is availble and works well.

The behavior seems to be against the [docs about proposed API](https://code.visualstudio.com/api/advanced-topics/using-proposed-api). Two questions:
- Should we block such publish in vsce?
- In vscode stable versions, should we make proposed APIs `undefined`, or throw a dedicated error when calling them?

@isidorn

**Comment by isidorn** [comment]
@alexr00 should the tree throw an exception in this case?
@joaomoreno should the `--noVerify` still verify in this case :) Why do we have that flag?

**Comment by alexr00** [comment]
I didn't try the publish step, but I am (correctly) not able to use the `treeItemCheckbox` API. @Eskibear can you share which extension you're using `treeItemCheckbox` in?

**Comment by gjsjohnmurray** [comment]
I guess @Eskibear has added an `argv.json` entry to allow the extension to use the proposed APIs it declares in its `package.json`.

**Comment by Eskibear** [comment]
FYI, corresponding code as below. 

https://github.com/Eskibear/vscode-extension-sample/blob/ab9b572200b479a622865a9d6384aa8c861c1669/src/extension.ts#L21-L46

Some context infomation: 
After knowing I can publish it using `--noVerify`, I was expecting to show checkbox in insiders and fallback to show normal tree item in stable, by checking whether the api is defined. (though there's a minor bug that I didn't check whether `TreeItem2` is defined) The possibility of "easily previewing features in insiders" was in my mind at that time.

**Comment by alexr00** [comment]
@Eskibear thank you for the example. I can reproduce the checkboxes being permitted. I've opened https://github.com/microsoft/vscode/issues/174064 to track just that issue.

**Comment by joaomoreno** [comment]
>  @joaomoreno should the `--noVerify` still verify in this case :) Why do we have that flag?

`--noVerify` was added exactly - and only - for overriding this rule.
