### ISSUE TITLE
vscode extension webview cannot load resources: ERR_UNKNOWN_URL_SCHEME

### ISSUE THREAD

**Issue by Arichy** [microsoft/vscode#173812]
Does this issue occur when all extensions are disabled?: Yes
This is about extension, so I must reserve at least one extension. 

- VS Code Version: 1.75.0
- OS Version: macos 13.1

Steps to Reproduce:

1. install my extension: vscode-ast-explorer
2. open a js/ts file, and then exec command: `show ast`
3. it will open a webview, but the webview failed to load any css/js resources
<img width="1850" alt="image" src="https://user-images.githubusercontent.com/29599723/217550489-f36b0447-2643-431d-8283-e3c47ae01606.png">
<img width="2525" alt="image" src="https://user-images.githubusercontent.com/29599723/217551081-5ed34519-b240-438c-a7b8-c422c93cda6f.png">

It worked before vscode@1.72 (2022.09), not works from vscode@1.73(2022.10)

**Comment by Arichy** [comment]
And this is resource url on my local development environment
<img width="1009" alt="image" src="https://user-images.githubusercontent.com/29599723/217552148-89e6b574-9816-44d5-921b-22471595a477.png">

**Comment by mjbvz** [comment]
See https://github.com/microsoft/vscode/issues/166003#issuecomment-1310820357

Extensions that target somewhat recent versions of VS Code can no longer use `vscode-resource` uris. Instead you should use `asWebviewUri`, which works correctly across environments and handles cases  `vscode-resource:` did not

**Comment by Arichy** [comment]
It works, thx😊
