### ISSUE TITLE
shellscript syntax highlighting incorrect on quotes inside curly braces

### ISSUE THREAD

**Issue by mhshph** [microsoft/vscode#173898]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version:  1.75 and 1.76.0-insider
- OS Version:  macos, and  Linux x64 6.1.7-200.fc37.x86_64

Steps to Reproduce:

1. open the attached bash script text in code and observe the highlighting
[issue.txt](https://github.com/microsoft/vscode/files/10693925/issue.txt)

2. compare with screenshot attached
![quoting-problem-linux2](https://user-images.githubusercontent.com/93323705/217729395-ecec6be8-275b-4a27-ba9f-9a5b54287b48.png)

**Comment by alexr00** [comment]
Opened issue in upstream repo: https://github.com/jeff-hykin/better-shell-syntax/issues/42

Assigning to February to check back and see if the issue gets fixed.

**Comment by svenlowrybjss** [comment]
Seeing the same thing after updating to 1.75 this afternoon.
Everything after this content is coloured as if it's string content, when it's not.
![image](https://user-images.githubusercontent.com/95080230/217890316-6e854812-fdbd-46aa-a04a-3f0f8d9339b8.png)

**Comment by tacooper** [comment]
> I can't provide specifics at the moment, but I'm seeing a similar issue (which wasn't there until the latest monthly update; I'm at 1.75.0 on Windows now). Not sure if this should be a separate issue, but you can see how the coloring is broken in this example:
> 
> ![image](https://user-images.githubusercontent.com/489334/217848305-4c26ec06-c01a-4e32-97e8-cf0fb4194466.png)

just now updated 1.75.1, and my issue is fixed!

**Comment by alexr00** [comment]
All new-to-1.75 shellscript syntax highlighting issues should be fixed in 1.75.1: https://github.com/microsoft/vscode/issues/173336

**Comment by mhshph** [comment]
I confirm that 1.75.1 fixed all my issues - less than 1 day after the bug report.  
VScode support truly is **top notch**.
thank you very much!
