### ISSUE TITLE
Windows 11: Context menu entry to open folder in VSCode Insiders vanished.

### ISSUE THREAD

**Issue by derkallevombau** [microsoft/vscode#173879]
The title says it all.

I uninstalled and reinstalled VSCode insiders, but the entry remains vanished.

As a workaround, I created a link in SendTo, but I would appreciate if this issue could be solved.

**Comment by deepak1556** [comment]
Merging to https://github.com/microsoft/vscode/issues/171911

**Comment by ITSURENXD** [comment]
To solve this, I modified the registries of the stable vs code and made it open vs code-insiders. It works great and the icon is also there so yeah, you need to add 4 files to the registry in different locations so HKEY_CLASSES_ROOT so I will just send you the file that will do it for you. Paste the codes to the file names and be sure to add the **.reg** extension next to it.

1.  name: all.reg. This will add it to the * in the HKEY_CLASSES_ROOT 

`Windows Registry Editor Version 5.00

[HKEY_CLASSES_ROOT\*\shell\VSCode]
@=hex(2):4f,00,70,00,65,00,6e,00,20,00,77,00,26,00,69,00,74,00,68,00,20,00,43,\
  00,6f,00,64,00,65,00,20,00,49,00,6e,00,73,00,69,00,64,00,65,00,72,00,73,00,\
  00,00
"Icon"=hex(2):43,00,3a,00,5c,00,50,00,72,00,6f,00,67,00,72,00,61,00,6d,00,20,\
  00,46,00,69,00,6c,00,65,00,73,00,5c,00,4d,00,69,00,63,00,72,00,6f,00,73,00,\
  6f,00,66,00,74,00,20,00,56,00,53,00,20,00,43,00,6f,00,64,00,65,00,20,00,49,\
  00,6e,00,73,00,69,00,64,00,65,00,72,00,73,00,5c,00,43,00,6f,00,64,00,65,00,\
  20,00,2d,00,20,00,49,00,6e,00,73,00,69,00,64,00,65,00,72,00,73,00,2e,00,65,\
  00,78,00,65,00,00,00

[HKEY_CLASSES_ROOT\*\shell\VSCode\command]
@=hex(2):22,00,43,00,3a,00,5c,00,50,00,72,00,6f,00,67,00,72,00,61,00,6d,00,20,\
  00,46,00,69,00,6c,00,65,00,73,00,5c,00,4d,00,69,00,63,00,72,00,6f,00,73,00,\
  6f,00,66,00,74,00,20,00,56,00,53,00,20,00,43,00,6f,00,64,00,65,00,20,00,49,\
  00,6e,00,73,00,69,00,64,00,65,00,72,00,73,00,5c,00,43,00,6f,00,64,00,65,00,\
  20,00,2d,00,20,00,49,00,6e,00,73,00,69,00,64,00,65,00,72,00,73,00,2e,00,65,\
  00,78,00,65,00,22,00,20,00,22,00,25,00,31,00,22,00,00,00
`
2.  name: directory shell.reg. This will add it to the Directory>Shell
`Windows Registry Editor Version 5.00

[HKEY_CLASSES_ROOT\Directory\shell\VSCode]
@=hex(2):4f,00,70,00,65,00,6e,00,20,00,77,00,26,00,69,00,74,00,68,00,20,00,43,\
  00,6f,00,64,00,65,00,20,00,49,00,6e,00,73,00,69,00,64,00,65,00,72,00,73,00,\
  00,00
"Icon"=hex(2):43,00,3a,00,5c,00,50,00,72,00,6f,00,67,00,72,00,61,00,6d,00,20,\
  00,46,00,69,00,6c,00,65,00,73,00,5c,00,4d,00,69,00,63,00,72,00,6f,00,73,00,\
  6f,00,66,00,74,00,20,00,56,00,53,00,20,00,43,00,6f,00,64,00,65,00,20,00,49,\
  00,6e,00,73,00,69,00,64,00,65,00,72,00,73,00,5c,00,43,00,6f,00,64,00,65,00,\
  20,00,2d,00,20,00,49,00,6e,00,73,00,69,00,64,00,65,00,72,00,73,00,2e,00,65,\
  00,78,00,65,00,00,00

[HKEY_CLASSES_ROOT\Directory\shell\VSCode\command]
@=hex(2):22,00,43,00,3a,00,5c,00,50,00,72,00,6f,00,67,00,72,00,61,00,6d,00,20,\
  00,46,00,69,00,6c,00,65,00,73,00,5c,00,4d,00,69,00,63,00,72,00,6f,00,73,00,\
  6f,00,66,00,74,00,20,00,56,00,53,00,20,00,43,00,6f,00,64,00,65,00,20,00,49,\
  00,6e,00,73,00,69,00,64,00,65,00,72,00,73,00,5c,00,43,00,6f,00,64,00,65,00,\
  20,00,2d,00,20,00,49,00,6e,00,73,00,69,00,64,00,65,00,72,00,73,00,2e,00,65,\
  00,78,00,65,00,22,00,20,00,22,00,25,00,56,00,22,00,00,00
`
3. name: directory background shell. This will add it to the Directory>Background> Shell
`Windows Registry Editor Version 5.00

[HKEY_CLASSES_ROOT\Directory\Background\shell\VSCode]
@=hex(2):4f,00,70,00,65,00,6e,00,20,00,77,00,26,00,69,00,74,00,68,00,20,00,43,\
  00,6f,00,64,00,65,00,20,00,49,00,6e,00,73,00,69,00,64,00,65,00,72,00,73,00,\
  00,00
"Icon"=hex(2):43,00,3a,00,5c,00,50,00,72,00,6f,00,67,00,72,00,61,00,6d,00,20,\
  00,46,00,69,00,6c,00,65,00,73,00,5c,00,4d,00,69,00,63,00,72,00,6f,00,73,00,\
  6f,00,66,00,74,00,20,00,56,00,53,00,20,00,43,00,6f,00,64,00,65,00,20,00,49,\
  00,6e,00,73,00,69,00,64,00,65,00,72,00,73,00,5c,00,43,00,6f,00,64,00,65,00,\
  20,00,2d,00,20,00,49,00,6e,00,73,00,69,00,64,00,65,00,72,00,73,00,2e,00,65,\
  00,78,00,65,00,00,00

[HKEY_CLASSES_ROOT\Directory\Background\shell\VSCode\command]
@=hex(2):22,00,43,00,3a,00,5c,00,50,00,72,00,6f,00,67,00,72,00,61,00,6d,00,20,\
  00,46,00,69,00,6c,00,65,00,73,00,5c,00,4d,00,69,00,63,00,72,00,6f,00,73,00,\
  6f,00,66,00,74,00,20,00,56,00,53,00,20,00,43,00,6f,00,64,00,65,00,20,00,49,\
  00,6e,00,73,00,69,00,64,00,65,00,72,00,73,00,5c,00,43,00,6f,00,64,00,65,00,\
  20,00,2d,00,20,00,49,00,6e,00,73,00,69,00,64,00,65,00,72,00,73,00,2e,00,65,\
  00,78,00,65,00,22,00,20,00,22,00,25,00,56,00,22,00,00,00
`
4. name: drive.reg. This will add it to the Drive in it
`Windows Registry Editor Version 5.00

[HKEY_CLASSES_ROOT\Drive\shell\VSCode]
@=hex(2):4f,00,70,00,65,00,6e,00,20,00,77,00,26,00,69,00,74,00,68,00,20,00,43,\
  00,6f,00,64,00,65,00,20,00,49,00,6e,00,73,00,69,00,64,00,65,00,72,00,73,00,\
  00,00
"Icon"=hex(2):43,00,3a,00,5c,00,50,00,72,00,6f,00,67,00,72,00,61,00,6d,00,20,\
  00,46,00,69,00,6c,00,65,00,73,00,5c,00,4d,00,69,00,63,00,72,00,6f,00,73,00,\
  6f,00,66,00,74,00,20,00,56,00,53,00,20,00,43,00,6f,00,64,00,65,00,20,00,49,\
  00,6e,00,73,00,69,00,64,00,65,00,72,00,73,00,5c,00,43,00,6f,00,64,00,65,00,\
  20,00,2d,00,20,00,49,00,6e,00,73,00,69,00,64,00,65,00,72,00,73,00,2e,00,65,\
  00,78,00,65,00,00,00

[HKEY_CLASSES_ROOT\Drive\shell\VSCode\command]
@=hex(2):22,00,43,00,3a,00,5c,00,50,00,72,00,6f,00,67,00,72,00,61,00,6d,00,20,\
  00,46,00,69,00,6c,00,65,00,73,00,5c,00,4d,00,69,00,63,00,72,00,6f,00,73,00,\
  6f,00,66,00,74,00,20,00,56,00,53,00,20,00,43,00,6f,00,64,00,65,00,20,00,49,\
  00,6e,00,73,00,69,00,64,00,65,00,72,00,73,00,5c,00,43,00,6f,00,64,00,65,00,\
  20,00,2d,00,20,00,49,00,6e,00,73,00,69,00,64,00,65,00,72,00,73,00,2e,00,65,\
  00,78,00,65,00,22,00,20,00,22,00,25,00,56,00,22,00,00,00
`

AFter saving these to the names. click and run these files which will add it automatically for you.
