### ISSUE TITLE
Stepping in code always tries to center the current line vertically

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#17384]
- VSCode Version: 1.9 Insiders
- OS Version: macOS

Steps to Reproduce:

1. start debugging on a program that has a loop and about 40 lines before and after the loop
2. step through the loop

Observe: the source is always scrolled so that the current line (yellow) stays at the same position vertically.

This is a regression from the stable build.

**Comment by isidorn** [comment]
Dup of #17364
