### ISSUE TITLE
Problem with Installing Extensions in Remote SSH Extension

### ISSUE THREAD

**Issue by timhdesilva** [microsoft/vscode#173949]
Hi,

I've managed to connect with my SSH key using the VSCode Remote SSH extension to a Linux machine. However, whenever I attempt to install an extension, I get the following error in the bottom right of my screen: "UnhandledException". I get no other information as to what's going wrong. Any help debugging this issue would be much appreciated!

**Comment by sandy081** [comment]
Can you please share following logs while you reproduce the issue

- F1 > Open View... > Remote Server

**Comment by timhdesilva** [comment]
Hi @sandy081,

Thanks for the response! Nothing was printed to the log. However, I was able to fix the problem. Previously, when VS Code did not connect to the server of interest, I had disabled Remote.SSH Use Flock setting in order to get it to connect. Now after reenabling Remote.SSH Use Flock and enabling Remote.SSH Lockfiles in Tmp, I can connect and install extensions.

Any chance you could provide me of an explanation of what's going on here? No worries if not, but I'm quite curious to understand and avoid in the future. Thanks!
