### ISSUE TITLE
Merge conflict codelens not clickable

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode#173974]
1. Create a standard git merge conflict
2. :bug: Open File via SCM resource group inline menu shows option to Resolve in Merge Editor but no codelenses
3. :bug: closing and reopening the file by clicking on the resource from the SCM view (not the inline menu action), I get the codelenses, but they are not clickable

https://user-images.githubusercontent.com/30305945/217898589-599a6d00-2812-4418-9d39-583f0965c257.mp4

**Comment by jrieken** [comment]
@chrmarti that's no extension has registered the commands

**Comment by joyceerhl** [comment]
I cannot repro, I'll close for now and reopen if I see it again.
