### ISSUE TITLE
Explorer: auto create folder when file path ends with `/`

### ISSUE THREAD

**Issue by zardoy** [microsoft/vscode#173902]
For now on `explorer.newFile` vscode doesn't distinguish wether inputbox has trailing `/` or not. It would create file instead of folder in that case, which can be handy.

For now if you run `explorer.newFile` had an idea to create new file within new folder `test/integration/etc` and then forgot test name to create or decided to do it later you cannot just create folder from typed value. You have either:

- Create dummy file at end eg: `test/integration/etc/a` and then remove just created file
- Select all & copy typed value, run `explorer.newFolder` and paste value

I want clean and fast way to switch between creating file or folder. Please see my implementation for desired behavior: https://github.com/microsoft/vscode/pull/173901

**Comment by eleanorjboyd** [comment]
it works from the file explorer but I was wondering about the `create file` command from the command palette. Should the same action be possible? Currently, it was not and when trying to do a nested file in a folder it did not work. Thanks!
<img width="947" alt="image" src="https://user-images.githubusercontent.com/26030610/226707420-b9582cc9-23c7-42ac-addc-692cff21929e.png">
<img width="485" alt="Screenshot 2023-03-21 at 11 32 03 AM" src="https://user-images.githubusercontent.com/26030610/226707494-fcb02e25-cf3d-4c67-97c1-3cbb0abb40c1.png">
