### ISSUE TITLE
Debug variable peak shows no scrollbar on initial render

### ISSUE THREAD

**Issue by lramos15** [microsoft/vscode#173980]
1. Peak an object that has many long property values
2. 🐛 There is no scrollbar
3. Open the prototype
4. 🎉 There is a scrollbar

![Recording 2023-02-09 at 11 34 52](https://user-images.githubusercontent.com/4544166/217906191-a0986d2f-bb9b-4132-9155-a56432d8c840.gif)

**Comment by roblourens** [comment]
Probably only with the horizontalscrolling setting enabled? I know that's a bit tricky

**Comment by lramos15** [comment]
> Probably only with the horizontalscrolling setting enabled? I know that's a bit tricky

What's the setting for that? I don't have any scroll setting that appears debug related enabled. Just sticky scroll for the editor.

**Comment by roblourens** [comment]
`workbench.list.horizontalScrolling`?

**Comment by lramos15** [comment]
> I think you have `workbench.list.horizontalScrolling` set, right?

No I do not.
