### ISSUE TITLE
وصف المشكله#

### ISSUE THREAD

**Issue by alrashdy25** [microsoft/vscode#173975]
_**### [ADD ISSUE DESCRIPTION HERE]

```[tasklist]
### Tasks
- [ ] Add a draft title or issue reference here
```
)**الإصدار: 1.75.0_ الالتزام: e2816fe719a4026ffa1ee0189dc89bdfdbafb164 وكيل المستخدم: Mozilla/5.0 (Macintosh؛ Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML، مثل أبو بريص) الإصدار/16.3 Safari/605.1.15 التضمين: مساحات الكود

**Comment by alrashdy25** [comment]
ADD ISSUE DESCRIPTION HERE ###

**Comment by aeschli** [comment]
Closing as incomplete. Please add a issue description.
