### ISSUE TITLE
Unit Test Timeout: ExtensionEnablementService Test

### ISSUE THREAD

**Issue by alexdima** [microsoft/vscode#173986]
https://dev.azure.com/monacotools/Monaco/_build/results?buildId=202792&view=logs&j=55ac390b-ffb1-50ea-3650-525dd9a3fd80&t=3a692518-c3cf-5f6a-c273-72f71dc185fb&l=10326
```
  8535 passing (2m)
  55 pending
  1 failing

  1) ExtensionEnablementService Test
       "before each" hook for "test enable an extension globally return truthy promise":

      
      + expected - actual


  Error: Timeout of 5000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.

```

**Comment by sandy081** [comment]
I really do not have any clue why this is failing. It would be great if the error stack provides info where the execution hangs. Anyway, I changed the format of the test to use async and also the check slightly.
