### ISSUE TITLE
Psuedo targets are added to the "Select Debug Console" dropdown when an attached JS target is restarted 

### ISSUE THREAD

**Issue by metalmarker** [microsoft/vscode#173993]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.75.1
- OS Version: MacOS Ventura 13.2 (22D49)

I'm using VS Code to debug an attached Node app. The problem is that each time that I restart the Node app, new pseudo targets are added to the "Select Debug Console" dropdown of the debug console.

Problem started in 1.75.0. In prior versions, only the "Server" target would appear after restarts (I'm debugging in multiple target environment, so the dropdown is always visible). Since 1.75.0 (and .1), two new targets are added to this list (webpack + server.bundle.js) after each restart. Here's how this dropdown looks like after 3 restarts:

<img width="431" alt="Screenshot 2023-02-09 at 12 39 52 PM" src="https://user-images.githubusercontent.com/106110899/217933237-042edde1-2202-41a0-8a30-d7a0a5d13c42.png">

A similar issue happens when attempting to debug a React app - each reattach adds a new pseudo target to the list.

The targets that are added to the debug dropdown are "stale" - switching to one of these pseudo items shows an empty debug console.

Steps to Reproduce:

1. Start debugging a JS app that is connected via the attach debug mode
2. Open the debug console
3. Restart the app using the "restart" icon on the debug panel
4. Click on the Select Debug Console dropdown, and observe new pseudo targets have been added to the list (and on each subsequent restart)

I tested the same configuration with VSCode 1.74.3, and the problem does not appear.

**Comment by roblourens** [comment]
I noticed this, I haven't looked into it at all but wondering whether it's related somehow to https://github.com/microsoft/vscode/pull/169074 @connor4312

**Comment by jpike88** [comment]
This is a pain, I often restart my server process and I just see this slowly building list of old server processes. I don't need to keep their logs behind, it just clogs the doprdown.

<img width="309" alt="Screenshot 2023-02-22 at 8 48 24 pm" src="https://user-images.githubusercontent.com/9585787/220624004-3d3c2d4b-f9c4-4457-933a-1fe9f077f83c.png">

**Comment by jpike88** [comment]
ignore my last comment... I found the setting Debug › Console: Close On End was 'off' by default. Turning it on resolved the problem

**Comment by connor4312** [comment]
Yea this looks expected since we have a process ID as part of the session name, so they get unique terminals. Could argue we shouldn't... but we do, and I've found it handy on more than one occasion

**Comment by metalmarker** [comment]
@connor4312 @jpike88 The problem persists after turning on Debug › Console: Close On End (on version 1.75.1). When the said option is on, the terminal/console pane indeed closes when debug stops, but when I restart the process, the pane re-shows with the "select debug console" dropdown populated with the terminated processes.

In any case, the problem surfaced in 1.75.0 so I still think there's a bug (or undocumented fix) that contributes to this issue. May I suggest to re-open the issue?

**Comment by metalmarker** [comment]
@connor4312 @roblourens following up - this is still an issue, there's no fix nor a workaround that I'm aware of. Can you please re-open the issue so that someone can give it a second look?

**Comment by connor4312** [comment]
Yep, thanks for the ping. This was hanging out in my notification queue but forgot to reopen it
