### ISSUE TITLE
Zen mode bugs?

### ISSUE THREAD

**Issue by dfroze** [Microsoft/vscode#17392]
- VSCode Version: 1.8
- OS Version: linux Mint

Hello,
Was just glad about the new zen mode when noticed 2 possible bugs.

**First bug:** file focus is reset
_Steps to reproduce_:
 - open some files from project
 - open key unofficial file (such as Preferences->User settings, or something similar)
 - focus on the settings.json
 - zen mode triggered
 - 2x Esc
 - the focus jumps to another file

Note, I noticed that after some time (or maybe after I have done something), this couldn't be reproduce anymore until restarted.

Edited: Same goes for toggle sidebar (the problem is probably from here). If I focus on the settings.json and then hit toggle sidebar ... :boom:,  jumps to the first non settings.json tab

**Second bug**: stuck in zen :D
_Steps to reproduce_:
 - i set the shortcut for zen as F11
 - hold F11 - yeah... took like 30s and got stuck in something like full screen (no window or menu bar, just sidebar and editor

**Comment by bpasero** [comment]
First thing is already covered in https://github.com/Microsoft/vscode/issues/16616

**Comment by bpasero** [comment]
...and #16616 is fixed 💥

**Comment by dfroze** [comment]
Any news regarding the second bug? If possible, can I take this task and fix it?

**Comment by isidorn** [comment]
@dfroze we frist have to try to reproduce that issue - let me do that right now

If you are looking for tasks to help with a good idea is to go through our open issues and search for a tag 'help wanted' - https://github.com/Microsoft/vscode/labels/help%20wanted

**Comment by isidorn** [comment]
Tried reproducing the second issue -> by holding F11 you are basically juming in and out of zen mode all the time but I still could not get into a broken state like you describe. 
Even if the bug could be reproduced it is very random and would not happen in a real life scenario - why would a user hold F11 for 30 seconds?

Anywas closing as designed, does not repro
