### ISSUE TITLE
Word wrap doesn't affect the text of the base in the merge editor

### ISSUE THREAD

**Issue by xiaoxi-david** [microsoft/vscode#173969]
Does this issue occur when all extensions are disabled?: Yes

Word wrap doesn't affect the text of the base in the merge editor, regardless of whether the base is displayed in the center or at the top.

Steps to reproduce:
1. Merge a branch with a conflict
2. Open the merge editor
3. Select word wrap

Base in the center
![image](https://user-images.githubusercontent.com/24303680/217885960-17e6ea34-98d9-4d7f-92ac-a8180304dcb3.png)

Base at the top
![image](https://user-images.githubusercontent.com/24303680/217886633-e95eae80-8429-4788-89c0-08a6df92868b.png)

Version: 1.76.0-insider (system setup)
Commit: 853b32bad26ed5ffe2d29b95be45adc7f753e35a
Date: 2023-02-09T05:23:28.458Z
OS: Windows_NT x64 10.0.19045
Sandboxed: Yes

**Comment by EliiseS** [comment]
I'll pick this up 😄
