### ISSUE TITLE
Disable intellisense for comments

### ISSUE THREAD

**Issue by mfrost66** [Microsoft/vscode#17390]
- VSCode Version:1.8
- OS Version:Windows 10

Intellisense offers suggestions when typing comments.  Besides making "intellisense" an oxymoron, it interfers with my ability to type as I can't use the tab,up,down keys without cancelling the suggestion popup.

**Comment by Mkayxx** [comment]
+1 this have been bothering me for a while

**Comment by mjbvz** [comment]
@mfrost66 What languages are you working in?

The intelliSense you are seeing is probably coming from word based suggestions. You can disable this with the setting `"editor.wordBasedSuggestions": false`. Let me know if this setting fixes the behavior for you

**Comment by mfrost66** [comment]
Yes, problem solved!

I was going to whine about lack of documentation regarding this, but I just
checked and the intellisense/customizing section is both well written and
covers this exact setting.  Apologies for failing to RTFM.

I might suggest adding the intellisense keyword (or other) to the settings
& key bindings so that they are more discoverable

**Comment by kieferrm** [comment]
Opened #17426.
