### ISSUE TITLE
Scroll hijacked on notebook cell text selection

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/vscode#173982]
New in v1.75 as far as I can tell. Scroll gets reset to the top of the selection when shift-clicking on a location far enough down that the top of the selection goes out of view. See how when I'm attempting to incrementally add more code to the selection I have to re-scroll to my old position each click. First example in recording is 1.74, next is 1.75. 

![Recording 2023-02-09 at 11 00 26](https://user-images.githubusercontent.com/8586769/217911841-88fe7475-2fe0-4f8d-857c-eca647a9fc86.gif)

Only happens in notebooks, but all notebook I tested are affected (including the the builtin Jupyter one).

**Comment by rebornix** [comment]
@JacksonKearl thanks for the report man

**Comment by JacksonKearl** [comment]
Thanks for the product! :)

**Comment by JacksonKearl** [comment]
Verified!

**Comment by jrieken** [comment]
Marking as `verified` based on @JacksonKearl comment above
