### ISSUE TITLE
TestRun.appendOutput does not show output in the Test Output panel

### ISSUE THREAD

**Issue by dgozman** [microsoft/vscode#173994]
Does this issue occur when all extensions are disabled?: No

- VS Code Version: 1.75.0
- OS Version: Darwin arm64 21.6.0

---

API Steps to Reproduce:
1. ```js
    const testController = vscode.tests.createTestController('pw.extension.testController', 'Playwright');
    testController.createRunProfile('dummy', vscode.TestRunProfileKind.Run, testRunRequest => {
      // ... upon receiving TestRunRequest
      const testRun = testController.createTestRun(testRunRequest);
      testRun.appendOutput('some text');
      testRun.end();
    }, true, 'tag');
   ```
2. Often times, there is no output in the Test Output panel.

---

Manual Steps to Reproduce:

1. Install https://marketplace.visualstudio.com/items?itemName=ms-playwright.playwright
2. ```bash
    git clone https://github.com/microsoft/playwright.git
    cd playwright
    npm install
    npm run build
    code .
    ```
3. Open file `examples/todomvc/tests/integration.spec.ts` in the editor.
4. Press "run test" button on line 20.
5. Open the Test Output panel.
6. Observe some output, e.g. `Running 1 test with 1 worker`
7. Press "run test" button on line 20 again.
8. Observe `The test run did not record any output.` However, there should be the same output as in the previous run.

---

https://github.com/microsoft/playwright/issues/20719 has some videos illustrating the problem.

**Comment by dgozman** [comment]
Seems to be fixed in 1.75.1, as a part of #173014. Thank you, @VSCodeTriageBot  😄

**Comment by dgozman** [comment]
This happens to me again with 1.76.0.

**Comment by connor4312** [comment]
This seems to work for me just on the released version of the extension and stable. Can you confirm that you're still on 1.76, and if so are there any additional steps that I didn't take in this case?


https://user-images.githubusercontent.com/2230985/222791218-c6beaaf0-0054-4823-b0b6-b492c1a6a138.mp4

**Comment by dgozman** [comment]
@connor4312 Thank you for trying it out! Indeed, I cannot reproduce the issue with v1.0.7 extension. However, I can reproduce with unreleased v1.0.8 extension. Let me dig a bit more, I'll get back.
