### ISSUE TITLE
macOS 10.9: VS Icon overlays title in title bar

### ISSUE THREAD

**Issue by jeffschwartz** [Microsoft/vscode#17391]
- VSCode Version: Code 1.8.0 (38746938a4ab94f2f57d9e1309c51fd6fb37553d, 2016-12-13T17:38:28.425Z)
- OS Version: Darwin x64 13.4.0
- Extensions:

|Extension|Author|Version|
|---|---|---|
|vscode-eslint|dbaeumer|1.2.2|
|view-in-browser|qinjia|0.0.3|
|vim|vscodevim|0.4.9|

---

Steps to Reproduce:

1. Start VS Code and the VS Code icon will overlay the file name in the title bar. 

In the screenshot below, the VS Code icon can be seen overlaying the file name in the title bar. 
![screen shot 2016-12-16 at 7 48 40 am](https://cloud.githubusercontent.com/assets/271288/21263454/e1a518b4-c364-11e6-94ff-84f4c4a77d84.png)

If no file is open in the editor, the VS Code icon does not display in the title bar.

![screen shot 2016-12-16 at 7 59 01 am](https://cloud.githubusercontent.com/assets/271288/21263574/a0a026b4-c365-11e6-81dc-232d9a77b826.png)

**Comment by bpasero** [comment]
@jeffschwartz looks like an upstream issue with the custom title bar style. You can go back to native style by setting: `"window.titleBarStyle": "native"`

**Comment by jeffschwartz** [comment]
Thank you for @bpasero

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/24217
