### ISSUE TITLE
Passing Augments with Escaping Character

### ISSUE THREAD

**Issue by linjlpp** [microsoft/vscode#173900]
- VS Code Version: 1.75.0
- OS Version:  Darwin arm64 22.3.0
- Shell: zsh

**Problem**
I am using VS Code to debug a C++ program, and I want to add arguments to the program. The project is built with CMake, and I add this to the _**settings.json**_ under _.vscode_ folder:

"args": [
"-a=\*bcd\*",
]

The argument (and command line) I **expect** to make is:
`/path/to/myprogram -a=*bcd*`

But the actual run command I see (after I click run) is:
`/path/to/myprogram "-a=*bcd*"`

I tried some solution like: `"argsExpansion": "none"`, `"console": "internalConsole"`. But they do not help. So how should I get the  double quote characters removed?

**Comment by roblourens** [comment]
Please file this on the C++ debug extension repo
