### ISSUE TITLE
Editor selection is broken in SCM editor

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#173920]
Here's a recording demonstrating Insiders (left) and previous Stable 1.74 (right):

https://user-images.githubusercontent.com/22350/217783637-c155d3fe-7c8d-424f-b06c-4f2c16ed9b0a.mp4

Steps:

1. Open the SCM view and add a long line
2. Shorten the width of the side bar such that the text wraps

🐛 Notice how:

- When selecting the entire buffer, the selection expands beyond the text
- When selecting a subrange, sometimes the start position of the selection moves
- The rounded corners is generally broken: not all corners are rounded any more. This applies even for 1.74.

**Comment by alexdima** [comment]
`vscode-bisect` points to https://github.com/microsoft/vscode/compare/44531ffc7b7477dbe82750040d8ed69bae2bb140...edc432e920c3ec2c2af5e8a99b8e4b782633d298 and a manual bisect points to aefa7eaf19557e102b9bcc9068ec5b0518e76beb being the first bad commit

**Comment by alexdima** [comment]
Reverting [this one line](https://github.com/microsoft/vscode/commit/aefa7eaf19557e102b9bcc9068ec5b0518e76beb#diff-87e0ff1d8aa33251109869f70c4b40afdb62f995035b783765095726c7137118L404) from the change fixes the rendering problem.

This diff fixes the rendering problem:
```diff
diff --git a/src/vs/workbench/contrib/scm/browser/media/scm.css b/src/vs/workbench/contrib/scm/browser/media/scm.css
index 83f6688bb64..22b980f3efe 100644
--- a/src/vs/workbench/contrib/scm/browser/media/scm.css
+++ b/src/vs/workbench/contrib/scm/browser/media/scm.css
@@ -371,7 +371,7 @@
 .monaco-workbench .part.basepanel > .content .scm-view .scm-editor-container .monaco-editor .margin,
 .monaco-workbench .part.basepanel > .content .scm-view .scm-editor-container .monaco-editor .monaco-editor-background {
 	color: inherit;
-	background-color: unset
+	background-color: var(--vscode-input-background);
 }
 
 .scm-view .scm-editor-container .mtk1 {
```

The root problem here is that it is not supported that the editor background color is transparent. The class name ".monaco-editor-background" is used to render rounded corners and that stops working if it is transparent.

**Comment by lszomoru** [comment]
Thank you @alexdima. Tested the changes the created a PR.
