### ISSUE TITLE
tree setting to automatically expand single-item subitems

### ISSUE THREAD

**Issue by generateui** [microsoft/vscode#173927]
https://github.com/microsoft/vscode/issues/88219 describes programmatically expanding/collapsing tree items. I noticed that my implementation is combining subitems when only one subitem is present for usability (less clicking). So in case of
```
rootnode
├─ child1
├─ child2
│  ├─ child2.1
│  │  ├─ child2.1.1
│  │  ├─ child2.1.2
```

I'd like child2.1.1 and child 2.1.2 expanded as soon as child2.1 is expanded. This is useful in scenarios where there is typically only one subitem present, but multiple may be present (but are less common). In such case you're typically always intesrested in expanding the single first subitem.

**Comment by alexr00** [comment]
@generateui VS Code doesn't know that your subtree only has one element until the tree has been expanded. This would need to be implemented by the extension that provides the tree, as that's the only source that knows whether the subtree is only one element.
