### ISSUE TITLE
[Suggestion] add DocBlock snippet functions for many languages

### ISSUE THREAD

**Issue by MrMashy** [Microsoft/vscode#17398]
I know it is very easy to create your own snippet for it but I'd prefer the automatic creation of DocBlocks

This package for Atom.IO called [DocBlockr](https://atom.io/packages/docblockr) is a perfect idea of what I want. It's a shame there is no plugins for this on VSCode but i'm sure a lot of people would love this feature!

At the moment I'm having to use Atom to write up my API Documentation and it's a pain having to switch between editors

If you don't know what docblocks are look up JavaDoc or [phpDocumentor](https://www.phpdoc.org/)

To clarify: No this is not just creating snippets, It's reading the below function and automatically creating a document block

**Comment by MrMashy** [comment]
Or if anyone could create a plugin for this, It would be great!

**Comment by BillDenton** [comment]
It looks like that DocBlockr has been ported to VS Code: https://github.com/shardulm94/vscode-docblockr
I've not tested it, and don't know if it is in the market.

**Comment by BillDenton** [comment]
Its not in the market, but there is https://marketplace.visualstudio.com/items?itemName=joelday.docthis. ""Document This" is a Visual Studio Code extension that automatically generates detailed JSDoc comments for both TypeScript and JavaScript files."
I'm using C and C++, so I'm not sure that it is much use. Not tested yet.

**Comment by michaelperrin** [comment]
@BillDenton But the Document This extension for VS Code only works for JavaScript and TypeScript, contrary to DocBlockr, which works for many languages (see https://github.com/spadgos/sublime-jsdocs).

**Comment by BillDenton** [comment]
I know :-(. Also there's nothing in https://github.com/shardulm94/vscode-docblockr.

**Comment by cesar-pa** [comment]
I need this for C/C++. It's the only thing stopping me to move from Sublime.

**Comment by snaker95** [comment]
在试用vscode的过程中, 发现有关一些操作上的问题:
1. 块注释, 默认是`ctrl+shift+a`(osx), 本人改为`commod+alt+/`, 这个不算问题, 主要是希望空注释时显示`/**/`而不是`/*  */`, (中间有两个空格, 光标定位在中间), 因为有时候习惯使用该注释展示不同的使用效果;例如:`/*---- xxxxxx ----*/`, 就需要删除空格操作
2. 关于**DocBlockr**, 希望能有一个通用的,多语言的, 例如**sublime**中[DocBlockr](https://packagecontrol.io/packages/DocBlockr), 这样用过`/**[enter]`或者`/**[enter]*/`来展示快注释, 并且有关于`function` or `class` 中`@params`,`@return`, 方便注释
