### ISSUE TITLE
Use Chrome's network stack for installing extensions

### ISSUE THREAD

**Issue by rfc791** [Microsoft/vscode#17397]
- VSCode Version: 1.8.0
- OS Version: Ubuntu 16.04.1 LTS

With 1.7 extensions worked fine.  Now on 1.8 it is ignoring the environment variables.  Doing a packet capture you can see it going direct.  I tried adding the setting for proxy in user settings still not working. It also says that https_proxy is not a setting.  My setting for the proxy are with authentication.

Steps to Reproduce:

1. Environment Variable set for http_proxy and https_proxy. 
2. Extension tries going direct instead of proxy.
3. Doing 'Check for Updates' goes through proxy.

**Comment by fazouane-marouane** [comment]
Hi
It seems that the issue is related to https://github.com/electron/electron/pull/7577
So now when searching for extensions vscode uses chromium's network stack however installation of those extensions seems to use node's net stack.

**Comment by fazouane-marouane** [comment]
I think that what's best is to always use chromium's net stack since it's more proxy-friendly

**Comment by joaomoreno** [comment]
I will hijack this issue to move all network code to the Chrome's network stack.

Related to #17786

**Comment by joaomoreno** [comment]
Removing important, as it's crucial we decide on the right approach, which at the moment is not clear: #18103

**Comment by joaomoreno** [comment]
Done.

**Comment by fazouane-marouane** [comment]
Great job @joaomoreno
