### ISSUE TITLE
Cancelling a remote source picker while it's searching doesn't work

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#173941]
1. Run `Git: Clone`
2. Choose `Clone from GitHub`
3. Type a search term
4. Immediately close quick pick with <kbd>Escape</kbd>

🐛 Search results appear eventually.

![Recording 2023-02-09 at 14 17 44](https://user-images.githubusercontent.com/22350/217823700-2f5cd7a3-c85b-46df-9c03-654bf196d756.gif)

**Comment by lszomoru** [comment]
@joyceerhl, could this be a regression introduced with https://github.com/microsoft/vscode/commit/9fed2f7eb336339038ae713b81bc5e1ef2238af1? Thanks!
