### ISSUE TITLE
Trying to erase the empty volumes do not work

### ISSUE THREAD

**Issue by M6rc0sp** [microsoft/vscode#173956]
Type: <b>Bug</b>

Just to be using the docker extension by SSH, the VS Code is in my PC Windows and the docker is running in my server Debian, when  I try to clean volumes unuseds this functions do not work (The Prune... button on Volumes section of Docker extension)

VS Code version: Code 1.75.0 (e2816fe719a4026ffa1ee0189dc89bdfdbafb164, 2023-02-01T15:23:45.584Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: No
Remote OS version: Linux x64 5.10.0-21-amd64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i5-11400T @ 1.30GHz (12 x 1296)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.37GB (9.58GB free)|
|Process Argv|--crash-reporter-id 084234ea-3c34-419f-b35e-e9d3cba252bc|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: 10.3.5.252|
|OS|Linux x64 5.10.0-21-amd64|
|CPUs|Intel(R) Core(TM) i3-10100T CPU @ 3.00GHz (8 x 800)|
|Memory (System)|7.18GB (5.59GB free)|
|VM|0%|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
remote-ssh|ms-|0.96.0
remote-ssh-edit|ms-|0.84.0
remote-explorer|ms-|0.2.0
material-icon-theme|PKi|4.23.1
vscode-docker|ms-|1.23.3

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
azure-dev_surveyone:30548225
pyindex848:30577860
nodejswelcome1:30587005
2e4cg342:30602488
f6dab269:30613381
pythonsymbol12:30657548
2i9eh265:30646982

```

</details>

**Comment by chrmarti** [comment]
/causedByExtension

This is caused by the Docker extension. Please file a new issue for it: https://github.com/microsoft/vscode-docker/issues
