### ISSUE TITLE
"Ctrl + K V" shortcut does not open Markdown preview to the side

### ISSUE THREAD

**Issue by CornOnACob** [microsoft/vscode#173917]
Type: <b>Bug</b>

The "Ctrl + K V" shortcut does not seem to work. I tried holding Ctrl and pressing K, then letting go of K and pressing V, but it does not do anything. (It should open the markdown preview to the side)

However, doing it manually through the Ctrl + Shift + P menu works for me.

VS Code version: Code 1.75.0 (e2816fe719a4026ffa1ee0189dc89bdfdbafb164, 2023-02-01T15:23:45.584Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: No
Remote OS version: Linux x64 5.15.79.1-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 9 3950X 16-Core Processor             (32 x 3500)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.92GB (16.95GB free)|
|Process Argv|--folder-uri=vscode-remote://wsl+Ubuntu-Preview/home/challenger/demos/twitterbio --remote=wsl+Ubuntu-Preview --crash-reporter-id 3197f738-afac-49ac-b5de-7e247f92906e|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-Preview|
|OS|Linux x64 5.15.79.1-microsoft-standard-WSL2|
|CPUs|AMD Ryzen 9 3950X 16-Core Processor (32 x 3500)|
|Memory (System)|15.58GB (14.18GB free)|
|VM|0%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
jupyter-keymap|ms-|1.0.0
remote-containers|ms-|0.275.1
remote-wsl|ms-|0.75.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30660299
azure-dev_surveyone:30548225
pyindex848cf:30577861
nodejswelcome1:30587005
3biah626:30602489
pyind779:30657576
89544117:30613380
pythonsymbol12:30657548
vsccsb:30659829

```

</details>

**Comment by gjsjohnmurray** [comment]
Did you get a message in the status bar?

![image](https://user-images.githubusercontent.com/6726799/217796243-bb102efe-931c-4180-bb1e-ad4dc554577d.png)

After pressing Ctrl+K release both keys and then press V on its own.

**Comment by CornOnACob** [comment]
You are correct! That message did appear in the status bar. Pressing Ctrl+K and V on its own executes the shortcut properly. That was my bad... I will close the ticket
