### ISSUE TITLE
C# dotnet not running

### ISSUE THREAD

**Issue by Uber-Man** [microsoft/vscode#173939]
Type: <b>Bug</b>

error code:
dotnet : The term 'dotnet' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try 
again.

```
At line:1 char:66
+ ... rs\Elev\Desktop\PROG\diagnos 2\diagnos 2\" ; if ($?) { dotnet run dia ...
+                                                            ~~~~~~
    + CategoryInfo          : ObjectNotFound: (dotnet:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
```

VS Code version: Code 1.75.0 (e2816fe719a4026ffa1ee0189dc89bdfdbafb164, 2023-02-01T15:23:45.584Z)
OS version: Windows_NT x64 10.0.19044
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-8145U CPU @ 2.10GHz (4 x 2304)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|7.85GB (2.74GB free)|
|Process Argv|C:\\Users\\Elev\\Desktop\\PROG\\diagnos 2\\diagnos 2\\diagnos2.cs --crash-reporter-id a0b34036-36d4-4a66-afba-07df8236d116|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-languagetool|ada|3.8.0
TabOut|alb|0.2.2
code-runner|for|0.12.0
vscode-indent-on-paste|gaz|2.4.0
indent-to-bracket|LAK|1.2.2
dotnet|leo|1.3.0
nc-gcode|ML|0.13.0
csharp|ms-|1.25.4
one-dark-theme|msk|1.14.2
LiveServer|rit|5.7.9
vscode-paste-and-indent|Rub|0.0.8
indenticator|Sir|0.7.0
code-spell-checker|str|2.16.0
code-spell-checker-swedish|str|1.1.3
vscode-pets|ton|1.22.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
azure-dev_surveyone:30548225
pyindex848:30577860
nodejswelcome1cf:30587006
3biah626:30602489
pyind779cf:30657577
f6dab269:30613381
pythonsymbol12:30657548
2i9eh265:30646982

```

</details>

**Comment by roblourens** [comment]
Sounds like you may not have the dotnet cli installed or on your path. If you think there is an issue with the dotnet vscode extension, please file an issue on that repo
