### ISSUE TITLE
Error while turning on Settings Sync. No authentication providers are available.

### ISSUE THREAD

**Issue by necrogami** [microsoft/vscode#174019]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.75.1
- OS Version: Windows_NT x64 10.0.2262

Version: 1.75.1 (user setup)
Commit: 441438abd1ac652551dbe4d408dfcec8a499b8bf
Date: 2023-02-08T21:32:34.589Z
Electron: 19.1.9
Chromium: 102.0.5005.194
Node.js: 16.14.2
V8: 10.2.154.23-electron.0
OS: Windows_NT x64 10.0.22621
Sandboxed: No

Steps to Reproduce:

1. Download VS Code from Microsoft Website
2. Install on Windows 11
3. Open VS Code
4. Click account
5. Click settings sync
6. Receive Error
```Error while turning on Settings Sync. No authentication providers are available.```

**Comment by sandy081** [comment]
Can you please check if following extensions are enabled?

- Open extensions view and look for these extensions `@builtin github auth` and `@builtin microsoft account`

**Comment by necrogami** [comment]
When i run @builtin it returns nothing adding more variables also returns nothing.

**Comment by necrogami** [comment]
And by that i mean `@builtin` shows nothing in extensions, themes or features

**Comment by sandy081** [comment]
Can you please provide a screenshot of what you are seeing?

**Comment by necrogami** [comment]
https://i.imgur.com/2lGjimq.png

**Comment by necrogami** [comment]
As i needed this working i ended up uninstalling, deleting %APPDATA%\Code and %USERPROFILE%\.vscode and then new download and install it worked after that.

**Comment by sandy081** [comment]
/duplicate

https://github.com/microsoft/vscode/issues/174695

**Comment by Oguidan** [comment]
> 
> 
> 
> 
> 
> 
> 
> Does this issue occur when all extensions are disabled?: Yes
> 
> 
> 
> - VS Code Version: 1.75.1
> - OS Version: Windows_NT x64 10.0.2262
> 
> Version: 1.75.1 (user setup)
> Commit: 441438abd1ac652551dbe4d408dfcec8a499b8bf
> Date: 2023-02-08T21:32:34.589Z
> Electron: 19.1.9
> Chromium: 102.0.5005.194
> Node.js: 16.14.2
> V8: 10.2.154.23-electron.0
> OS: Windows_NT x64 10.0.22621
> Sandboxed: No
> 
> Steps to Reproduce:
> 
> 1. Download VS Code from Microsoft Website
> 2. Install on Windows 11
> 3. Open VS Code
> 4. Click account
> 5. Click settings sync
> 6. Receive Error
> ```Error while turning on Settings Sync. No authentication providers are available.```

Have you try to reinstall and restart your computer
