### ISSUE TITLE
debuggee is killed when computer sleeps

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#174033]
* vscode project
* select F5 to run `VS Code` launch config
* put computer to sleep
* resume computer
* 🐛 the debuggee has been killed

This seems minor but has ruined many demos, e.g walking to a meeting with a prepared demo just find out that it has been killed or getting a demo killed live because long discussions made the computer go to sleep etc pp

**Comment by jrieken** [comment]
Still seeing this. @dbaeumer also mentioned seeing this

@connor4312 what logs do you need to fix this?

**Comment by connor4312** [comment]
Can you please double check that you are in fact on js-debug nightly? I used to see this as well, but have never seen it since my fix...

**Comment by jrieken** [comment]
> Can you please double check that you are in fact on js-debug nightly?

js-debug is built-in and I assume that vscode insiders comes with latest, isn't that that case?

**Comment by connor4312** [comment]
That's not the case, the nightly build is released every day and there's not a mechanism for using pre-release versions of built-in extensions. But in the next Insiders, js-debug will be updated in preparation for endgame.

**Comment by jrieken** [comment]
Isn't this one you, updating `product.json#builtinExtensions` either by hand or have some automation? I am really surprised by this and would say insiders should always be up-to-date with what we will ship assuming we ship stable the next day

**Comment by connor4312** [comment]
I do this by hand, but I don't do it manually each day. Maybe some automation would help now that we have better pipelines and such...

Re-closing this issue so it can get verified

**Comment by jrieken** [comment]
> Re-closing this issue so it can get verified

Without a milestone that won't happen...

Anyways, after the nightly-install-trouble, I can happily mark this as `verified`
