### ISSUE TITLE
Search does not work in UTF-16 LE encoded files

### ISSUE THREAD

**Issue by garfieldbanks** [Microsoft/vscode#17408]
- VSCode Version: 1.8.0
- OS Version: Windows 10

Steps to Reproduce:

1. Create and open a test_folder in VSCode.
![image](https://cloud.githubusercontent.com/assets/12904270/21273630/b495707c-c381-11e6-8465-4e191be8b989.png)

2. Add an XML file encoded in UTF-16 LE.
![image](https://cloud.githubusercontent.com/assets/12904270/21273728/1f9af342-c382-11e6-8cdf-76a55ecc9c5e.png)

3. Add a javascript file encoded in UTF-8.
![image](https://cloud.githubusercontent.com/assets/12904270/21273749/399b4134-c382-11e6-9471-a2bc6fcf2543.png)

4. Make sure both files are closed. Then search for text that can be found in both files. Note that only the javascript file is actually listed in the results.
![image](https://cloud.githubusercontent.com/assets/12904270/21273826/9dc13592-c382-11e6-8fb7-cb1e58169400.png)

Note: The XML file encoded in UTF-16 LE _is_ found only if it is currently open in VSCode.

**Comment by bpasero** [comment]
@garfieldbanks I assume the file contains a UTF-16 LE BOM?

**Comment by garfieldbanks** [comment]
Wow. That was fast.

I don't know. I just used VSCode to open an old file in with a new encoding, and then I and put in the text with the tag.

**Comment by bpasero** [comment]
I can reproduce after saving a file within VS Code in UTF-16 LE.
