### ISSUE TITLE
Cannot type polish letter 'ż'

### ISSUE THREAD

**Issue by mikchmie** [Microsoft/vscode#17406]
- VSCode Version: Code 1.8.0 (38746938a4ab94f2f57d9e1309c51fd6fb37553d, 2016-12-13T17:38:28.425Z)
- OS Version: Darwin x64 16.3.0
- Extensions:

|Extension|Author|Version|
|---|---|---|
|swift|Kasik96|0.0.2|
|vscode-theme-onedark|akamud|0.2.14|
|python|donjayamanne|0.5.5|
|Kotlin|mathiasfrohlich|1.2.0|
|cpptools|ms-vscode|0.9.3|
|csharp|ms-vscode|1.5.3|
|java|redhat|0.0.7|

---

Steps to Reproduce:

1. On macOS choose Polish programmer keyboard layout in System Preferences
2. Create new file or open existing one
3. Press Alt+z - nothing happeans, instead of typing 'ż'

**Comment by coreh** [comment]
There seems to be a keyboard shortcut bound to this key combination:

```json
{ "key": "alt+z",                 "command": "editor.action.toggleWordWrap",
                                     "when": "editorTextFocus" },
```

Go to **Preferences > Keyboard Shortcuts** and try adding the following rule:

```json
{ "key": "alt+z",                 "command": "-editor.action.toggleWordWrap" }
```

With that added I'm able to type with that key combination (in my keyboard layout it produces `Ω`)

Oddly enough, Word Wrap still gets toggled.

**Comment by kieferrm** [comment]
Closing. As @coreh described `alt+z` is bound to word-wrap. Created #17420 to address the "cannot unbind case".
