### ISSUE TITLE
Styling differences between logged object and evaluated object

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#17404]
![image](https://cloud.githubusercontent.com/assets/323878/21271665/b7b8aed8-c370-11e6-8fad-00b671cd928b.png)

Log messages have an indent and slightly smaller font size.

**Comment by ramya-rao-a** [comment]
@roblourens Cannot repro in 1.8.1

**Comment by roblourens** [comment]
You would need to use 1.8.1 with an up to date debug adapter.

You can build and run node2, then attach to it with `"debugServer": 4712` (or I can just verify)

**Comment by ramya-rao-a** [comment]
@roblourens I'll let you verify :)
