### ISSUE TITLE
No hover effect for extensions' icons in sidebar

### ISSUE THREAD

**Issue by niccolomineo** [microsoft/vscode#174031]
Does this issue occur when all extensions are disabled?: No, but that's because this issue pertains to the extensions themselves.

- VS Code Version: 1.75.1
- OS Version: MacOs Ventura 13.2

Steps to Reproduce:

1. Open VSCode
2. Ascertain the hover on extensions' icons in the sidebar lack hover effect

**Comment by sandy081** [comment]
> Ascertain the hover on extensions' icons in the sidebar lack hover effect

I am sorry that I do not understand. Can you please explain what do you mean by this? If possible please provide a gif or screenshot.

**Comment by niccolomineo** [comment]
Sure, here you go.

This is what the hover on a sidebar icon normally looks like:

![Screenshot 2023-02-10 alle 09 50 22](https://user-images.githubusercontent.com/5409469/218056442-31ae9bf2-6245-4102-91e2-a65e480b8f3f.png)

This is what it looks like when the icon belongs to an extension:

![Screenshot 2023-02-10 alle 09 50 32](https://user-images.githubusercontent.com/5409469/218056596-17d1fe63-02ab-465b-9b29-66334c866310.png)

As you can see, there is no hover effect in this case. This seems consistently happening with other extensions too.

Is it just my setup for some reason?

**Comment by sandy081** [comment]
Ok, this is because of the icons contributed by these extensions and the color of these icons cannot be changed dynamically.

CC @daviddossett

**Comment by niccolomineo** [comment]
> Ok, this is because of the icons contributed by these extensions and the color of these icons cannot be changed dynamically.
> 
> CC @daviddossett

Ain't this something with the potential of being addressed in a future VSCode release?

**Comment by daviddossett** [comment]
My guess is that the challenge here is that they are hardcoded SVGs. I don't know how feasible it would be to dynamically change the `fill` values. @aeschli might have more context here.
