### ISSUE TITLE
Execute entire gulpfile without tasks

### ISSUE THREAD

**Issue by TheColorRed** [Microsoft/vscode#17403]
- VSCode Version: 1.8.0
- OS Version: Ubuntu

Is there a way to execute the entire `gulpfile.js` without adding tasks to it?

I have the following **tasks.json** file:

```json
{
    "version": "0.1.0",
    "command": "gulp",
    "isShellCommand": true,
    "args": [],
    "showOutput": "always"
}
```

I was able to execute it a few times using <kbd>ctrl+shift+B</kbd>. But then suddenly it stopped working and I started getting this message:

>No task is marked as a build task in the tasks.json. Mark a task with 'isBuildCommand'.

I am assuming that this isn't the correct way to do this since it suddenly stopped.

I am using Laravel Elixir, and for some reason if you put it within a gulp task it does not work (even from a terminal). When you execute the file on it's own without tasks (from the terminal) it does work.

`gulp` works from the terminal:

```js
elixir(mix => {
    mix.sass('app.scss')
        .webpack('app.js');
});
```

`gulp build` doesn't work from the terminal:

```js
gulp.task('build', () => {
    elixir(mix => {
        mix.sass('app.scss')
            .webpack('app.js');
    });
});
```

**Comment by dbaeumer** [comment]
@TheColorRed actually that should work. Could you share your project so that I can investigate why this fails after a while

**Comment by TheColorRed** [comment]
Here is the code:

https://github.com/TheColorRed/tmp-ezel

This should be the commands to run before you run the gulpfile:

```
$ composer install
$ npm install
```

**Comment by dbaeumer** [comment]
@TheColorRed thanks. I cloned the project and Ctrl+Shift+B works nicely for me. Here is what I see:

![capture](https://cloud.githubusercontent.com/assets/1931590/21311303/cd3ac890-c5e6-11e6-834b-3169dd877a5e.png)

Even repeatedly. Anything special when this fails. What do you see in the Output panel when it fails.

**Comment by TheColorRed** [comment]
Nothing outputs to the **output console**, or to the **developer tools console**.

I have tried on both Windows/Ubuntu. Is there a way to run without extensions? I could try that...

![isbuildcommand](https://cloud.githubusercontent.com/assets/1571806/21318331/63d5ff5e-c5ce-11e6-8eb4-469ae4216202.png)

**Comment by dbaeumer** [comment]
Looks like you are trying to execute a task with Ctrl+Shift+B but no task is marked as a build task in the tasks.json.

**Comment by dbaeumer** [comment]
Without additional information about the problem we can't work on this issue. Please ping when the information is available and we will reopen the issue. The last screen shot simply indicated that no build tasks is defined (property `isBuildCommand`)
