### ISSUE TITLE
Esc twice to enter zen mode?

### ISSUE THREAD

**Issue by coreh** [Microsoft/vscode#17405]
I really like pressing Esc twice to leave Zen mode. But the shortcut to enter, ⌘K, Z, is kinda cumbersome.

I'd like to suggest that maybe we could make esc twice a default to _enter_ Zen mode as well? (Not sure if it would interfere with VIM emulation plugins or not.)

**Comment by mjbvz** [comment]
You can already enable this with a custom key binding:

```
{
    "key": "escape escape",
    "command": "workbench.action.toggleZenMode"
}
```

The request here would be to make this the default keybinding, correct?

**Comment by coreh** [comment]
Yeah, that's correct.

But thanks for the tip about the custom key binding! 🙇

**Comment by isidorn** [comment]
Thank you for the suggestion but this is configurarble and we do not want to make people accidentely end up in zen mode and be confused what is going on.

Closing as designed
