### ISSUE TITLE
TypeScript Language Mode give errors of module not found

### ISSUE THREAD

**Issue by rajeevkumarsharma** [Microsoft/vscode#1740]
This happens when we have definitelytyped within npm package

vc code should not only see for definitelytyped in typings folder it should also see in npm package (i.e. node_modules).
This is caused when i am using angular2 and definitelytyped for angular2 are provided in npm package instead separate  definitelytyped, so make TypeScript IntelliSense so it also load from npm packages as well

Looking for active action on this issue

Thanks
Rajeev Kumar Sharma

**Comment by dbaeumer** [comment]
Using .d.ts files from the the node_modules folder is supported in 0.10.6. However you need to tell the TypeScript language server to look into the node_modules folder by specifying 
```json
		"moduleResolution": "node"
```
in the tsconfig.json. 

For more information please look at the TypeScript documentation.

**Comment by rajeevkumarsharma** [comment]
Hi Dirk,

It still persist with 0.10.6 on Linux. Here are some screenshots attacked.

Thanks
![screenshot from 2016-01-07 12 16 13](https://cloud.githubusercontent.com/assets/8169482/12164062/7cf1c592-b538-11e5-87fd-f688d5969a6f.png)

**Comment by rajeevkumarsharma** [comment]
Hi Dirk,

Here is my package.json file.

Thanks
![screenshot from 2016-01-07 12 17 02](https://cloud.githubusercontent.com/assets/8169482/12164086/a5e73da6-b538-11e5-911e-0131f5bb66aa.png)

**Comment by dbaeumer** [comment]
@rajeevkumarsharma the problem is that you list app/app.ts in the tsconfig.json file. So the settings defined in the tsconfig.json file only apply to that file. However the code is on app/lib/rest.ts. You either need to list that file as well or don't list any files at all. If you go with the second I recommend to exclude the node_modules folder. Something like:
```json
{
    "compilerOptions": {
        "module": "commonjs",
        "moduleResolution": "node"
    },
    "exclude": [
        "node_modules"
    ]
}
```

**Comment by rajeevkumarsharma** [comment]
Hi Dirk,'

Now it is fine with exclude property.

Thanks for helping
Rajeev Kumar Sharma
