### ISSUE TITLE
Keep filtering suggestModel.ts after space

### ISSUE THREAD

**Issue by dennisfrostlander** [Microsoft/vscode#17400]
- VSCode Version: 1.8.0
- OS Version: any

Imagine you have a language where you can have identifiers with spaces (for example T-SQL). 
Identifiers with spaces are quoted, for example "My Table".

I have a language server with code completion capabilities. When code completion is triggered, my language server returns a list of quoted identifiers, for example "My Table", "Other Table", etc.

Then the user starts typing:
- My -> completion list is narrowed down to one entry. This is done automatically by vscode in suggestModel.ts
- Space -> completion is now cancelled by the suggest model. isDifferentContext returns true because it detects a space, [shouldRetrigger](https://github.com/Microsoft/vscode/blob/6090d4b8ff89eefc91bdbec78dbd432a18a3562e/src/vs/editor/contrib/suggest/common/suggestModel.ts#L118-L121) returns false because it thinks it's a different line. But even if this line passes, re-triggering will happen only in automatic mode, but not in manual.
As a result, suggestion list is cancelled altogether and there is nothing one can do about it.

@jrieken, what do you think about this scenario? Would it be possible to resolve this somehow? I can send more information from the language server, for example if "My is typed, I know it's the part of identifier, so a subsequent space should keep filtering. Otherwise, if only My is typed, then space should probably cancel the suggestions as it does today. Then this would be similar to how Management Studio intellisense works.

This issue is quite annoying for our users because half of the identifiers in the codebase contains spaces :)

**Comment by jrieken** [comment]
You describe a valid scenario. Does your extension define what a [word is](https://github.com/Microsoft/vscode/blob/master/src/vs/vscode.d.ts#L2714)? We should work with that, but I am unsure if we actually do...

**Comment by dennisfrostlander** [comment]
@jrieken No, we don't actually use wordPattern. It seems to be left out in [LanguageConfigurationFileHandler](https://github.com/Microsoft/vscode/blob/b70ce7919ff8dc939604228e63a73800745e98b2/src/vs/editor/node/languageConfigurationExtensionPoint.ts#L67-L83). Not sure though on purpose or not.

I played around with wordPattern and it can solve a number of problems. However, it would be tricky to define a word in the most common case when you type:
```
var table : "My<space>
```
After the space you would expect code completion to filter to "My Table", but you have typed just a part of the word including the starting quote. But that would be already a step forward, maybe I can come up with a regex to handle this case properly as well.

**Comment by dennisfrostlander** [comment]
Auto-inserting the second quote could also be a solution.

**Comment by dennisfrostlander** [comment]
Could you also consider if the following scenario would be addressed by using the word pattern?

This time, it is the opposite case. Identifiers are not quoted (e.g. Table, OtherTable), but the user types it with quotes.
1. The user types the following and triggers the code completion as shown:
```
var table : "Table^"
```
Note: character ^ is for illustration purposes only and shows where code completion is triggered.
2. The language server returns two identifiers without quotes: Table, OtherTable
3. The suggestModel should not filter them out even though "Table does not start with Table, etc.

**Comment by jrieken** [comment]
Your extension can control that - either by setting the [`CompletionItem.range`](https://github.com/Microsoft/vscode/blob/master/src/vs/vscode.d.ts#L2429) and/or [`CompletionItem.filterText`](https://github.com/Microsoft/vscode/blob/master/src/vs/vscode.d.ts#L2411)

**Comment by aeschli** [comment]
verified with a sample extension
