### ISSUE TITLE
Go to definition is broken on recusive function references

### ISSUE THREAD

**Issue by waderyan** [Microsoft/vscode#17409]
_From @zhengbli on October 15, 2016 8:8_

**TypeScript Version:** nightly (2.1.0-dev.20161014)

**Code**

``` ts
function tttt() {
    /*cursor position*/tttt(); // <- "go to definition" doesn't go to the function declaration
}
```

_Copied from original issue: Microsoft/TypeScript#11657_

**Comment by waderyan** [comment]
_From @vladima on October 15, 2016 17:22_

I can repro this one and I suspect that this might be issue in VSCode:

``` ts
function tttt() {
    /*1*/tttt();
}

/*2*/tttt()
```

Go to definition does not work if cursor is positioned on marker `/*1*/` and works if cursor is on /_2_/. Interestingly enough for both cases server sends identical responses (modulo response specific fields)

```
// cursor on /*1*/
[Trace - 10:20:16 AM] Sending request: definition (119). Response expected: yes. Current queue length: 0
Arguments: {
    "file": "/home/vladima/sources/git/TypeScript/a.ts",
    "line": 2,
    "offset": 10
}
[Trace - 10:20:16 AM] Response received: definition (119). Request took 2 ms. Success: true 
Result: [
    {
        "file": "/home/vladima/sources/git/TypeScript/a.ts",
        "start": {
            "line": 1,
            "offset": 1
        },
        "end": {
            "line": 3,
            "offset": 2
        }
    }
]

// cursor is on /*2*/
[Trace - 10:21:03 AM] Sending request: definition (121). Response expected: yes. Current queue length: 0
Arguments: {
    "file": "/home/vladima/sources/git/TypeScript/a.ts",
    "line": 5,
    "offset": 6
}
[Trace - 10:21:03 AM] Response received: definition (121). Request took 2 ms. Success: true 
Result: [
    {
        "file": "/home/vladima/sources/git/TypeScript/a.ts",
        "start": {
            "line": 1,
            "offset": 1
        },
        "end": {
            "line": 3,
            "offset": 2
        }
    }
]
```

@dbaeumer can it be the case that VSCode ignores the response if initial cursor position is in range returned in response?

**Comment by waderyan** [comment]
@mjbvz can you take a look at this? I have confirmed the behavior with the latest insider build.

**Comment by mjbvz** [comment]
@waderyan Yes, the bug is that we do not go the definition if the cursor is already inside the definition range. This the same problem we saw with #17083. See @jrieken's comment about this here: https://github.com/Microsoft/vscode/issues/17083#issuecomment-266974778

The TS issue for fixing this is https://github.com/Microsoft/TypeScript/issues/8808
