### ISSUE TITLE
Container pty host process is unresponsive?

### ISSUE THREAD

**Issue by Kitrini-Alepou** [microsoft/vscode#174017]
Type: <b>Bug</b>

I just updated today on Fedora 37 and this thing started to happen when trying to connect to container terminal from vscode"The connection to the terminal's pty host process is unresponsive, the terminals may stop working."

VS Code version: Code 1.75.1 (441438abd1ac652551dbe4d408dfcec8a499b8bf, 2023-02-08T21:35:30.018Z)
OS version: Linux x64 6.1.9-200.fc37.x86_64
Modes:
Sandboxed: No
Remote OS version: Linux x64 6.1.9-200.fc37.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-2320 CPU @ 3.00GHz (4 x 3188)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|2, 2, 2|
|Memory (System)|7.45GB (2.79GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|gnome|
|XDG_CURRENT_DESKTOP|GNOME|
|XDG_SESSION_DESKTOP|gnome|
|XDG_SESSION_TYPE|wayland|

|Item|Value|
|---|---|
|Remote|Container debian (dazzling_hoover)|
|OS|Linux x64 6.1.9-200.fc37.x86_64|
|CPUs|Intel(R) Core(TM) i5-2320 CPU @ 3.00GHz (4 x 3184)|
|Memory (System)|7.45GB (2.79GB free)|
|VM|0%|
</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
icons-carbon|ant|0.2.6
beardedicons|Bea|1.4.0
node-snippets|chr|1.3.3
rust-syntax|dus|0.6.1
flippidippi-theme|fli|0.0.8
theme-monokai-pro-vscode|mon|1.2.0
jupyter-keymap|ms-|1.0.0
remote-containers|ms-|0.275.1
remote-ssh|ms-|0.96.0
remote-ssh-edit|ms-|0.84.0
remote-explorer|ms-|0.2.0
errorlens|use|3.7.0

(3 theme extensions excluded)

</details>

**Comment by jenschurchill** [comment]
I had this happen to me last week after updating to 1.75. 

The terminal would eventually come up, but taking so long as to make it usable.  

I installed an update today, hoping to see an improvement, but instead the terminal now outright never comes up.  

Developing has become useless in devcontainers, as neither python or anything else requiring a terminal will connect.  

I've finally resorted to downgrading using  `sudo dnf install code-1.74.3`  

Everything works as expected again now.
