### ISSUE TITLE
Ctrl-L incorrectly clears the terminal after history is restored

### ISSUE THREAD

**Issue by Rillian-Grant** [microsoft/vscode#174065]
Does this issue occur when all extensions are disabled?: Yes

Version: 1.75.1 (user setup)
Commit: 441438abd1ac652551dbe4d408dfcec8a499b8bf
Date: 2023-02-08T21:32:34.589Z
Electron: 19.1.9
Chromium: 102.0.5005.194
Node.js: 16.14.2
V8: 10.2.154.23-electron.0
OS: Windows_NT x64 10.0.19044
Sandboxed: No

Steps to Reproduce:

1. Use the terminal then close vscode leaving the terminal open.
2. Reopen vscode. Once the terminal loads and displays your activity from the previous session press Ctrl-L

Issue:
The first press of Ctrl-L move the cursor to the first line in the terminal but will not clear the screen. If you press Ctrl-L a second time it will work as intended.

The `cls` command does not experience this issue.

**Comment by Tyriar** [comment]
We don't control what ctrl+l does, it's up to the shell you're using and conpty. VS Code's terminal just does what it's told here.
