### ISSUE TITLE
[Feature Request] When only one "Quick Fix" is available, use it when user clicks "Quick Fix..." instead of opening the dropdown with a single action

### ISSUE THREAD

**Issue by lk0001** [microsoft/vscode#174035]
### Context

- [X] This issue is not a bug report. *(please use a different template for reporting a bug)*
- [X] This issue is not a duplicate of an existing issue. *(please use the [search](https://github.com/microsoft/monaco-editor/issues) to find existing issues)*

### Description

When the "Quick Fix..." menu has only one available action, would it be possible to just use that action when the user clicks "Quick Fix..." link rather than open the dropdown with a single action?
Perhaps it could be an editor option, so you can choose current (open the list of actions with a single action) or proposed behavior (just do the action).

#### Screenshot
![Zrzut ekranu z 2022-11-24 17-53-47](https://user-images.githubusercontent.com/145405/203835708-045a5f99-c9db-4fef-a499-8c12c6a631cf.png)

**Comment by mjbvz** [comment]
You can use the `auto fix` command for this (it also has a default keybinding). Auto fix will automatically apply quick fixes that have been marked as "preferred" by the extension that contributes them (and so long as there is only a single "preferred" code action available)
