### ISSUE TITLE
Restart in a Multitarget Debugging rotates targets in the dropdown list

### ISSUE THREAD

**Issue by Spown** [Microsoft/vscode#17401]
- VSCode Version: 1.8
- OS Version: Win10x64

First of all thank you for this feature! No longer need I to nest projects and open multiple windows. But there is an inconvenience problem...

![](https://dl.dropboxusercontent.com/u/105338698/ShareX/2016-12/2016-12-16_17-10-28.gif)

Steps to Reproduce:

1. Have a compound launch config with ['server', 'client']
2. launch it
3. restart 'server'

Desired behavior: 'server' is still selected in target dropdown option list.

What actually happens: 'client' gets selected

Why? Because the dropdown list removes the 'server' from the stack ->'client' becomes the only item so it gets selected -> new 'server' instance gets pushed into the list, but doesn't get reselected. If you restart once more - the same happens only with roles switched. They start to rotate.

So, if I'm used to restart via a hotkey - I normally don't look at what launch config is currently running - I just know it. If I'm now focused on the server-side development I probably want the selected target stay selected in the list because I want to restart it often. Without reselecting it manually every time.

Thank you.

**Comment by Spown** [comment]
If I may suggest, the optimal behavior would be not to remove the list item when the debug session is terminated, but rather when/if the restart has failed (and maybe after a timeout). If it succeeded - the new instance would be bound to the list item.

**Comment by isidorn** [comment]
@Spown thanks for the suggestion, however went with the other approach of restarting refocusing the process on finish if the process was focussed before. This makes sense in general imho

Glad you like multi process debugging. Feedback welcome and writing concise issues is also appreciated :)

**Comment by jrieken** [comment]
For it doesn't focus the restarted process but the other one

![jan-27-2017 15-00-27](https://cloud.githubusercontent.com/assets/1794099/22373307/63a43860-e4a1-11e6-8db7-4e55bff19917.gif)

**Comment by isidorn** [comment]
@jrieken nice find! I accidently broke this when doing some refactoring of process ids.

**Comment by Spown** [comment]
so, another month to wait?

**Comment by isidorn** [comment]
@Spown no, you can use the vscode insiders to have it right now. If you want to use stable, then yes you have to wait - sorry about that.

**Comment by Spown** [comment]
you could've snuck it in 1.9.1...  can you move it in some other milestone in case 1.9.2 comes out before 1.10?

**Comment by isidorn** [comment]
No. In recovery builds we are carefuly about only picking critical fixes and bad regressions. Since this is neither I recommend that you use the VS Code insiders.
Sorry about that.

**Comment by chrmarti** [comment]
- VSCode Version: Code - Insiders 1.10.0-insider (f02f9930255b5804166bd26c804de474ebb96799, 2017-02-24T07:04:53.237Z)
- OS Version: Darwin x64 15.6.0
- Extensions: None

The launch drop-down in the debug widget switches to the second launch when the first is restarted (and vice-versa), but subsequent restarts (or any other action on the debug widget) still target the first one.

![17401](https://cloud.githubusercontent.com/assets/9205389/23313494/cb66bee6-fa72-11e6-840e-de4be46318bb.gif)

**Comment by chrmarti** [comment]
The debug widget not targeting the process shown in the drop-down is a regression from 1.9.1.

**Comment by chrmarti** [comment]
Tricky: FocusProcessActionItem gets the newly selected item (the restarted process) before it gets the new list of items containing that item. (Suspending my investigation.)

**Comment by chrmarti** [comment]
Verified that the drop-down and the call stack selection restore the previously selected process after that restarted, the correct process is targeted afterwards and the call stack selection follows the drop-down's selection.

The drop-down doesn't follow the call stack's selection, but I assume that is expected. Marking verified.

**Comment by Spown** [comment]
Thank you.
