### ISSUE TITLE
Recent change to link detection in the terminal is a regression

### ISSUE THREAD

**Issue by jribbens** [microsoft/vscode#174009]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.75.1
- OS Version: Windows 11

Steps to Reproduce:

1. Display a link in the terminal of the form `https://example.com/path(abc,def)`
2. Previously the link would be automatically detected correctly and made clickable (although in the debug tab, by contrast, it was not detected properly).
3. Since version 1.75.0, the link detection wrongly terminates at the `,` so the link cannot be easily clicked to open it.

I appreciate that you can never please all the people all the time with URL guessing, but I thought it was worth mentioning given that it used to work fine, and to be fair all the characters `(`, `,` and `)` are standard normal URL code points and always have been.

**Comment by Tyriar** [comment]
Can repro after, not before:

![image](https://user-images.githubusercontent.com/2193314/218176198-5247b340-06cf-4723-b7f4-781118bd57ce.png)

**Comment by Tyriar** [comment]
This is actually a regression in monaco's link detection which the terminal leverages for uris:

1.74:
<img width="259" alt="image" src="https://user-images.githubusercontent.com/2193314/218176525-b63ad641-08a0-4d96-a45e-93c98fbebf2b.png">



1.75:

![image](https://user-images.githubusercontent.com/2193314/218176470-542e91b0-d777-409b-8a6a-0e7ff0ec7bca.png)

So this was unrelated to the recent terminal link improvements which focused on file detection

**Comment by hediet** [comment]
[This PR](https://github.com/microsoft/vscode/pull/168752) introduced this change to fix [this issue](https://github.com/microsoft/vscode/issues/119696)

**Comment by Tyriar** [comment]
Commas are used pretty often in certain links, not sure how advanced the detection is but it could be improved by only treating it as a separator if after a / or if the word before has a period?

**Comment by hediet** [comment]
GitHub also doesn't split at comma:
https://github.com/microsoft/vscode,https://github.com/microsoft/vscode

I'd probably revert the fix, but I'm fine with either. Up to you @alexdima.

**Comment by Ruler90** [comment]
The same issue applies for .js and .md files.

VS Code Version: 1.75.1
OS Version: Windows 11 

Steps to reproduce:
1. Create a .js file and paste the following code into it:
`const url = "https://www.empik.com/samsung-galaxy-sm-s918bzedeuedm3-8-gb-ram-256-gb-bezowy-samsung,p1360111382,elektronika-p";`
2. Create an .md file and paste the following url into it:
`https://www.empik.com/samsung-galaxy-sm-s918bzedeuedm3-8-gb-ram-256-gb-bezowy-samsung,p1360111382,elektronika-p`.
3. In both cases the link detection wrongly terminates at the `,` so the link cannot be easily clicked to open it.

**Comment by alexdima** [comment]
:+1: I'm OK to revert.
