### ISSUE TITLE
Allow JSON files to be mapped to a TypeScript interface instead of a JSON schema

### ISSUE THREAD

**Issue by stabai** [microsoft/vscode#174097]
When adding configuration files, it's often times preferable to use a `.ts` file to enforce strong typing of the configuration data from TypeScript. This allows you to reuse a TypeScript interface that will work the config data when actually storing the config, but it creates a problem of requiring the TypeScript tooling to read the file.

Conversely, a JSON file can be read by just about anything, but then we lose a lot of that strong typing. We could use something like [ts-json-schema-generator](https://github.com/vega/ts-json-schema-generator) to convert the TypeScript interface into a JSON schema, but that conversion is lossy and requires a not-insignificant amount of extra work.

What would be ideal is if we could use the existing methods of letting the editor know the schema of a JSON file (e.g. [the `$schema` attribute](https://code.visualstudio.com/docs/languages/json#_mapping-in-the-json)) to instead specify a TypeScript file and interface to use for IntelliSense and validation.

For example, if we had the following file:

`configs.ts`
```typescript
export interface ServiceConfig {
  name: string;
  secureUrl: `https://${string}`;
  hostName: string;
  hostPort: number;
}
```

We could do something like the following to use it in our JSON file:
```typescript
{
  "$schema": "./configs.ts#ServiceConfig",
  "name": "MyServer",
  "secureUrl": "https://myserver.myorg.com",
  "hostName": "myserver",
  "hostPort": 80
}
```

In this example, `./configs.ts#ServiceConfig` is used as a possible way of identifying the type to be used as the basis for this schema:
- `./configs.ts` refers to the location of the type declaration (possibly a remote URL too?)
- `#ServiceConfig` refers to the name of the type to be used for this object (possibly limited to exported symbols?)

I think this would be majorly useful for many cases. Having some way to enforce this in the `tsc` compiler would also be highly desirable, but even just the simple case of allowing the user to know the data is valid would be great.

**Comment by aeschli** [comment]
That's an interesting idea. 
But maybe it's something an extension could experiment with? For VS Code we normally focus on integrating existing linters/compiles and established specs like the JSON schema specification.

Closing as 'out of scope'.
