### ISSUE TITLE
Terminal is slow when running programs that produce a lot of output

### ISSUE THREAD

**Issue by yuxqiu** [microsoft/vscode#174070]
Type: <b>Performance Issue</b>

Steps to Reproduce:

1. Use `cc out.c -o out -std=c99` to compile the following code snippet

    ```c
    #include <stdio.h>
    
    int main(void) {
      const int len = 1e7;
      for (int i = 0; i < len; ++i) {
        putchar('-');
      }
    }
    ```

2. Run `time ./out` in vscode terminal and other terminals (e.g. Terminal.app). Get the following output.

    external terminal
    
    ```
    (A bunch of '-' printed by the program)...
    ./out  0.22s user 0.03s system 69% cpu 0.351 total
    ```
    
    vscode terminal
    ```
    (A bunch of '-' printed by the program)...
    ./out  0.22s user 0.05s system 38% cpu 0.690 total
    ```

3. By using different `len`, we can see that the vscode terminal is always ~1x slower than the external terminal.

4. The problem persists even if `terminal.integrated.shellIntegration.enabled` is set to false.

---

VS Code version: Code 1.75.1 (441438abd1ac652551dbe4d408dfcec8a499b8bf, 2023-02-08T21:34:01.965Z)
OS version: Darwin arm64 22.3.0
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.26GB free)|
|Process Argv|--crash-reporter-id fa7ca1a0-e8f5-4af6-b863-18b89d2f1ab3|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
   14	   229	 39652	code main
    0	    98	 39653	   gpu-process
    0	    49	 39654	   utility-network-service
    1	   229	 39701	   shared-process
    0	    98	 39703	     ptyHost
    0	    16	 40649	       /opt/homebrew/bin/zsh -l
    0	    66	 39880	     fileWatcher
    0	     0	 41778	     /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0	   606	 39874	   window (out.c — Testing Area)
    0	   180	 39879	   extension-host
    0	   115	 39882	     /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Plugin).app/Contents/MacOS/Code Helper (Plugin) --ms-enable-electron-run-as-node /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/json-language-features/server/dist/node/jsonServerMain --node-ipc --clientProcessId=39879
    0	    82	 41769	   issue-reporter
```

</details>
Extensions: none

**Comment by meganrogge** [comment]
This is expected as we deal with overhead that external terminals do not.
