### ISSUE TITLE
Markdown preview mode, doesn't show(update) modifies images.

### ISSUE THREAD

**Issue by rajinder-yadav** [Microsoft/vscode#17410]
- VSCode Version: Code 1.8.0 (38746938a4ab94f2f57d9e1309c51fd6fb37553d, 2016-12-13T17:38:28.425Z)
- OS Version: Darwin x64 16.1.0
- Extensions:

|Extension|Author|Version|
|---|---|---|
|vscode-markdownlint|DavidAnson|0.6.0|
|EditorConfig|EditorConfig|0.3.4|
|jslint|ajhyndman|1.2.1|
|jshint|dbaeumer|0.10.15|
|vscode-eslint|dbaeumer|1.2.2|
|tslint|eg2|0.7.1|
|cpptools|ms-vscode|0.9.3|
|debugger-for-chrome|msjsdiag|2.4.0|
|Spell|seanmcbreen|0.9.1|
|vim|vscodevim|0.4.9|

---

Steps to Reproduce:

1. Open markdown file with an image
2. Open preview
3. Go to split view (or not) one side with markdown file, the other in preview mode
4. Edit a image file referenced by the markdown.

* Expect to see the updated image in Preview.
* Also there is no way to manually refresh Preview.

![screen shot 2016-12-16 at 1 56 50 pm](https://cloud.githubusercontent.com/assets/439226/21274716/8ffc3df2-c397-11e6-93d2-c12d636e7e8c.png)

**Comment by mjbvz** [comment]
Trying to determine when images change on disk will be complicated but I like the idea or adding a way to manually refresh the markdown preview

Marking as help wanted if anyone wants to look into this

**Comment by mjbvz** [comment]
Rolling this into #32111, which tracks adding a refresh command to the markdown preview
