### ISSUE TITLE
Can't create directory in github.dev

### ISSUE THREAD

**Issue by acdiost** [microsoft/vscode#174182]
When I create a new folder in github.dev like this: 

`view/{book,article,`  the input was not completed, and I accidentally pressed the Enter key
or 
`view/{book,article}`

after pressing Enter, this directory is not displayed and the view directory cannot be created anymore.

Actually I want to implement a command similar to Linux like this: 
 `mkdir -p folder/{foo,bar}`

This is notice:
> Unable to resolve nonexistent file 'vscode-vfs://github+7b2276223a312c22726566223a7b2274797065223a362c226964223a226d6173746572227d7d/mycodespace/Application/Runtime/Data/view'

Version: 1.75.1
Commit: 441438abd1ac652551dbe4d408dfcec8a499b8bf
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36   
Embedder: github.dev

**Comment by lramos15** [comment]
Is https://github.com/microsoft/vscode/pull/162893 what you're looking for?

**Comment by acdiost** [comment]
Yes.

**Comment by lramos15** [comment]
Closing as duplicate
