### ISSUE TITLE
Some menus fade-in despite "Show animations in Windows" is turned off

### ISSUE THREAD

**Issue by theNestruo** [microsoft/vscode#174135]
Type: <b>Bug</b>

Steps to reproduce:
1. Windows 10, with Settings &rArr; Display &rArr; Show animations in Windows turned off
2. Right click in Visual Studio Code
3. Some menus (editor, inputs, scroll bar, ...) appear instantly as expected. Some other menus (activity bar, file explorer, tabs, status bar, ...) show a fade-in animation.

VS Code version: Code 1.75.1 (441438abd1ac652551dbe4d408dfcec8a499b8bf, 2023-02-08T21:32:34.589Z)
OS version: Windows_NT x64 10.0.19045
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 3 2200U with Radeon Vega Mobile Gfx   (4 x 2495)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|11.55GB (6.66GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by meganrogge** [comment]
You can use `workbench.reduceMotion` in your VS Code settings to reduce animation. We don't have access to OS settings.
