### ISSUE TITLE
Notebook diff - minimap or hide unchanged cells

### ISSUE THREAD

**Issue by matangover** [microsoft/vscode#174152]
When viewing git diff for large notebooks, it's impossible to know what changed, since there is no visual indication where a change occurred. One option to solve this is showing a diff minimap like when diffing normal files. Another option is a checkbox to hide unchanged cells, as in the following picture (from Deepnote):

<img width="896" alt="image" src="https://user-images.githubusercontent.com/5028956/218198728-9e64e590-5f5a-4046-89ed-7b5f4d099f3f.png">

**Comment by DonJayamanne** [comment]
* [ ] 
```[tasklist]
### Tasks
- [ ] NotebookTextDiffEditor.previousChange & NotebookTextDiffEditor.nextChange
Re-hide hidden cells that were expanded
(accessible)
```
