### ISSUE TITLE
Debugger weird completions

### ISSUE THREAD

**Issue by talks2much** [microsoft/vscode#174126]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.76.0-insider
- OS Version: macOS

Its really hard to use completions from debugger when debugging TS files, they are even misleading sometimes, for example when you first time complete property access, names of completions are correct, but when you start typing after completion widget was dropped - global completions are suggested 😑.

<img width="519" alt="Screenshot 2023-02-11 at 09 40 04" src="https://user-images.githubusercontent.com/78976241/218244605-be8578fe-36d8-4034-a837-f6b1b9827f2c.png">

(trying to complete `at` method of array)

I wonder why is this happening and where they coming from (and can I fix them somehow? this is really annoying):

<img width="536" alt="Screenshot 2023-02-11 at 09 14 53" src="https://user-images.githubusercontent.com/78976241/218244322-726516b7-17d3-4a54-a828-43a5e4fabf7e.png">
 
Since provider is undefined, I wonder what API is used (eg so I can bring copilot completions here for example)

Also in case of TS I wonder why don't they show type information (would be really handy on methods).

<img width="327" alt="Screenshot 2023-02-11 at 09 15 20" src="https://user-images.githubusercontent.com/78976241/218244561-b68e542e-ebcc-40f9-ad33-144e426f8592.png">

So I'm saying in this issue is that quality of completions should be improved in TS files by showing the same details (especially important for methods to see names of arguments) and documentation (jsdoc). As I can understand there is lack of API from vscode side. Is that right?

**Comment by roblourens** [comment]
Yes, got https://github.com/microsoft/vscode/issues/168021 tracking this

**Comment by talks2much** [comment]
> Yes, got #168021 tracking this

Yeah, I know I opened that 😆 #168021 is bug about global completions showing after dot was typed. But here I wanted to request better quality of completions such as better displaying documentation and details from TS. I'm using debugger on daily basis and I feel there is a huge gap between editor and debugger completions.

On the other hand I currently have no idea how TS server can help with giving intellisense from contents of not actual file 🤔

**Comment by roblourens** [comment]
Oops, thanks. I think it's not the right solution to try to mix in TS knowledge, since that can also lead to incorrect suggestions. Really we just need to fix the data that comes from the runtime.

**Comment by talks2much** [comment]
> Oops, thanks. I think it's not the right solution to try to mix in TS knowledge, since that can also lead to incorrect suggestions. Really we just need to fix the data that comes from the runtime.

Absolutely can't agree with you. Do you use TS knowledge in your codebase when writing code? Probably yes. Are they incorrect? Probably no. I think if you have incorrect typings there might be a problem with your codebase then. So introducing TS knowledge into debugger completions would push debugger DX into the space. There are a few examples:

- Getting documentation, details from TS knowledge. For example any method displays something like `fn(?, ?)` which isn't really useful (especially if it has overload with only one argument)
- Getting *absolutely no completions* if invoking function has side-effects or on proxy object:
```ts
const getPos = () => {
        console.log('side-effect!')
        return new vscode.Position(0, 0)
}
debugger; // no completions in debugger after getPos().

const someObj = new Proxy({} as Type, {...})
debugger; // no useful completions in debugger after someObj().
```

Using some kind of enum to either use only TS knowledge or integrate it with current debugger suggestions or disable would be cool.

And I really would like to investigate supporting this, but again I think there is hard technical limitation. 😞
