### ISSUE TITLE
debug50 isn't working

### ISSUE THREAD

**Issue by chrismiley87** [microsoft/vscode#174105]
ADD ISSUE DESCRIPTION HERE
Everytime I try to run debug50 it says that the connection failed. 
Version: 1.75.1
Commit: 441438abd1ac652551dbe4d408dfcec8a499b8bf
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36
Embedder: codespaces

**Comment by roblourens** [comment]
This is probably an issue with your code or configuration, please file this against the debug extension that you're using
