### ISSUE TITLE
Revert menu layout

### ISSUE THREAD

**Issue by SetTrend** [microsoft/vscode#174176]
In VSCode version:

```
Version: 1.75.1 (user setup)
Commit: 441438abd1ac652551dbe4d408dfcec8a499b8bf
Datum: 2023-02-08T21:32:34.589Z
Electron: 19.1.9
Chromium: 102.0.5005.194
Node.js: 16.14.2
V8: 10.2.154.23-electron.0
Betriebssystem: Windows_NT x64 10.0.19044
Sandkasten: No
```

… you changed the title bar to prefer the program/document name over the menu:

![Menu minimized](https://user-images.githubusercontent.com/9283914/218437381-8f1c37bb-69b8-49f8-992e-3f1defbc129c.png)

Very often, I rather find my self interacting with the menu bar than with the – to me unimportant – VS Code program or document name.

The new design very much decreases accessibility to the menu items by rendering them awkward to handle.

Please add an option to revert to the old design, prefering displaying the menu bar in full size over displaying the current document title and application name.

**Comment by sbatten** [comment]
dupelicate https://github.com/microsoft/vscode/issues/173862
