### ISSUE TITLE
Commit Amend doesn't load previous commit title

### ISSUE THREAD

**Issue by gabrielw007** [microsoft/vscode#174172]
Type: <b>Bug</b>

Trying to do Commit Staged / Amend
it opens a file in vcode showing my git status and when i close it, messages that the commit was cancelled due to empty commit message...
but i'm amending the prev commit!

VS Code version: Code 1.75.1 (441438abd1ac652551dbe4d408dfcec8a499b8bf, 2023-02-08T21:32:34.589Z)
OS version: Windows_NT x64 10.0.19044
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz (8 x 3600)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.71GB (12.42GB free)|
|Process Argv|--folder-uri file:///c%3A/Git/eLab/eLab%20Clients/eLabWebClient --crash-reporter-id 545f7d30-02f6-458d-a1ad-cfbc04d24c08|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (27)</summary>

Extension|Author (truncated)|Version
---|---|---
csharp-to-typescript|adr|1.12.1
Bookmarks|ale|13.3.1
ng-template|Ang|15.1.0
All-Autocomplete|Ati|0.0.26
vscode-typescript-refactors|can|0.0.22
gitignore|cod|0.9.0
vscode-eslint|dba|2.4.0
gitlens|eam|13.2.0
toggle-upper-case|epr|0.0.1
lintlens|ghm|7.0.0
todo-tree|Gru|0.0.224
vscode-essentials|jab|1.6.0
hungry-delete|jas|1.7.0
refactorix|kri|0.3.6
Angular-BeastCode|Mik|10.0.3
csharp|ms-|1.25.4
npm-outdated|msk|2.2.0
abracadabra|nic|6.19.0
vscode-jscpd|pau|0.3.4
vscode-versionlens|pfl|1.4.1
material-icon-theme|PKi|4.24.0
toggle-case|Pra|0.1.2
subtle-brackets|raf|3.0.0
rewrap|stk|1.16.3
control-snippets|svi|1.9.1
intellicode-api-usage-examples|Vis|0.2.7
vscodeintellicode|Vis|1.2.30

(4 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscoreces:30445986
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
azure-dev_surveyone:30548225
vsccc:30610678
pyindex848:30577860
nodejswelcome1:30587005
3biah626:30602489
f6dab269:30613381
pythonsymbol12cf:30657549
a9j8j154:30646983

```

</details>

**Comment by gabrielw007** [comment]
make the amend like in visual studio - there is a checkbox of Amend and when you check it, it loads the prev commit message

**Comment by lszomoru** [comment]
@gabrielw007, are you able to reproduce the same behaviour in the latest version of VS Code? When I invoke the commit amend command, the editor is opened with the previous commit message so that the commit message can be modified. When the editor is closed the commit operation completes. If that is not what you are seeing please feel free to reopen the issue. Thanks!
