### ISSUE TITLE
prefix profile folder name with profile name

### ISSUE THREAD

**Issue by tjx666** [microsoft/vscode#174185]
In order to recogonize the profile by it's folder name

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/41773861/218313857-b943f597-63ee-48cd-9056-aadc8e697cd9.png">

@sandy081

**Comment by sandy081** [comment]
I am not sure it is a good idea as the name can be renamed.

**Comment by tjx666** [comment]
@sandy081 Or we can add some description like:

![image](https://user-images.githubusercontent.com/41773861/218436413-d9ae8647-3c13-4aea-a79e-dd4933462c53.png)

**Comment by sandy081** [comment]
May I know the purpose?

**Comment by tjx666** [comment]
In order to identify current profile easily

**Comment by tjx666** [comment]
For now, there is no way to extend the profile. When I need to change a setting, I may open multiple setting in different profile:

![image](https://user-images.githubusercontent.com/41773861/218438372-3e8d557a-ff5a-468b-b697-0e725b0c7ae5.png)

**Comment by sandy081** [comment]
Why not switch the profile and update it from UI?

**Comment by tjx666** [comment]
I'm one of those who like use json to adjust settings🥲

**Comment by tjx666** [comment]
I'm one of those who like use json to adjust settings🥲

**Comment by sandy081** [comment]
I see. May I know the purpose of updating settings in other profiles? Are you missing something in profiles feature?

**Comment by tjx666** [comment]
For now, profile doesn't support extend, when I change a base setting, I need switch all profile to change that setting. I have 6 profiles

**Comment by sandy081** [comment]
Please subscribe to this issue for that support - https://github.com/microsoft/vscode/issues/156144
