### ISSUE TITLE
VS code is blurry if the right most (or second?) monitor is scaled, while the left most (or first?) is not

### ISSUE THREAD

**Issue by Rasive** [microsoft/vscode#174155]
Does this issue occur when all extensions are disabled?: Yes/No
Yes

- VS Code Version: 
1.76.0-insider

- OS Version: 
Ubuntu 20.04 LTS:
`$ uname -a
Linux HOSTNAME 5.15.0-60-generic #66-Ubuntu SMP Fri Jan 20 14:29:49 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux`

Fresh install of code-insiders, running on wayland with following command line:
`$ /usr/bin/code-insiders --enable-features=UseOzonePlatform --ozone-platform=wayland`

Steps to Reproduce:

When opening vscode it seems that the text is blurry depending on which monitor is scaled. Here are a couple of screenshots to show what I mean, and how to reproduce it:

1. Left (monitor 1) 100%. Right (monitor 2) 150%:
![Screenshot from 2023-02-11 20-45-21](https://user-images.githubusercontent.com/1022792/218278885-a0621eb1-ab7f-4d62-bd2d-5979b17cd74f.png)
Here the text is blurry, and it is only vscode that is, the electron wrapper scales fine

2. Left (monitor 2) 150%. Right (monitor 1) turned off:
![Screenshot from 2023-02-11 20-44-17](https://user-images.githubusercontent.com/1022792/218278780-3a9e9467-f4ce-4a94-a7c4-77e0937a8305.png)
Here the text is rendered fine

3.  Left (monitor 2) 150%. Right (monitor 1) 100:
![Screenshot from 2023-02-11 20-46-11](https://user-images.githubusercontent.com/1022792/218278849-5b8eed2d-692c-41d9-ace2-fdf763f3ad68.png)
Here it is also fine

**Comment by zanemarkel** [comment]
I'm getting a similar error. Fractional scaling works fine if I only use the display with fractional scaling, but when I use an additional display without scaling, it's blurry.

I'm on Fedora 37 and using 1.75.1. More specifically:

```
$ uname -a
Linux fedora.tail8f479.ts.net 6.1.10-200.fc37.x86_64 #1 SMP PREEMPT_DYNAMIC Mon Feb  6 23:56:48 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
$ code --version
1.75.1
441438abd1ac652551dbe4d408dfcec8a499b8bf
x64
```

This is how I'm trying to run code:

```
$ code --enable-features=UseOzonePlatform --ozone-platform=wayland
Warning: 'enable-features' is not in the list of known options, but still passed to Electron/Chromium.
Warning: 'ozone-platform' is not in the list of known options, but still passed to Electron/Chromium.
```

I get the same warnings in all cases, even though fractional scaling works when (and only when) I only use the one display with fractional scaling.

If I just run `code` without the wayland flags, then it is blurry in all cases.

**Comment by zanemarkel** [comment]
I'm getting a similar error. Fractional scaling works fine if I only use the display with fractional scaling, but when I use an additional display without scaling, it's blurry. The arrangement of the displays does not appear to matter.

I'm on Fedora 37 and using code 1.75.1. More specifically:

```
$ code --version
1.75.1
441438abd1ac652551dbe4d408dfcec8a499b8bf
x64
```

This is how I'm trying to run code:

```
$ code --enable-features=UseOzonePlatform --ozone-platform=wayland
Warning: 'enable-features' is not in the list of known options, but still passed to Electron/Chromium.
Warning: 'ozone-platform' is not in the list of known options, but still passed to Electron/Chromium.
```

I get the same warnings in all cases, even though fractional scaling works when (and only when) I only use the one display with fractional scaling.

If I just run `code` without the wayland flags, then it is blurry in all cases.

**Comment by victariox** [comment]
I think this is related with https://github.com/microsoft/vscode/issues/161231. Which was linked with something unrelated and closed down. 

Regardless of arrangement if not all displays are scaled vscode starts blurry and you can fix it by running "Developer: Reload window".

**Comment by zanemarkel** [comment]
You're right, same issue for me. Reloading the window it fixes the blurriness. Thank you!

**Comment by 9Morello** [comment]
I have the same issue, but reloading the window does not fix it.

**Comment by matejcik** [comment]
looks like this is back: https://github.com/microsoft/vscode/issues/174876

I can reproduce this on both current insiders and current stable:
```
Version: 1.83.0-insider
Commit: 5a400e53e985dc5e24f6ee574b07ab23943841c5
Date: 2023-09-07T17:35:22.926Z
Electron: 25.8.0
ElectronBuildId: 23503258
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Linux x64 6.0.19-060019-generic
```

scaling 175%, single display:
![Screenshot from 2023-09-08 09-51-46](https://github.com/microsoft/vscode/assets/596073/4ed46fae-b5a5-4907-9d92-83eb129548a6)

scaling 175%, second display connected with 100%:
![Screenshot from 2023-09-08 09-52-15](https://github.com/microsoft/vscode/assets/596073/9b9dad50-e6a1-4b4d-8eba-575708ba5514)

curiously enough, using x11 instead of wayland, the result is fuzzier in full-res, but much nicer visually on the high density display

**Comment by deepak1556** [comment]
Thanks for the update @matejcik, it seems to have regressed with Chromium 114 that enables fractional scaling experiment by default on wayland. Issue is tracked in https://github.com/microsoft/vscode/issues/192590, I will merge this to it.
