### ISSUE TITLE
IME input window jumping around

### ISSUE THREAD

**Issue by kieferrm** [Microsoft/vscode#17411]
- VSCode Version: Code 1.8.0 (38746938a4ab94f2f57d9e1309c51fd6fb37553d, 2016-12-13T17:38:28.425Z)
- OS Version: Darwin x64 15.6.0
- Extensions:

|Extension|Author|Version|
|---|---|---|
|theme-toothpaste|aalaap|0.0.1|
|regex|chrmarti|0.0.6|
|tslint|eg2|0.5.39|
|to-data-uri|kieferrm|0.1.1|
|typescript-javascript-grammar|ms-vscode|0.0.2|
|gitblame|waderyan|1.3.0|

---

Steps to Reproduce:

1. use Cangjie as input method on the Mac
2. start typing
-> on first keystroke IME jumps to top left, on next keystroke it goes to the cursor position

Disclamer: **I don't know what I wrote.** :
![3xodmnht7t](https://cloud.githubusercontent.com/assets/4674940/21275376/57f06994-c381-11e6-9197-c5144b898edf.gif)

**Comment by rebornix** [comment]
Dup of #356.

**Comment by rebornix** [comment]
Close it and let's track in #356
