### ISSUE TITLE
PowerShell terminal weird prompt

### ISSUE THREAD

**Issue by neolib** [microsoft/vscode#174188]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.75.1
- OS Version: Windows 8.1 Pro

Steps to Reproduce:

1. Start Visual Studio Code
2. Press CTRL+` to activate console

I get weird prompt like this:
`←]633;P;IsWindows=←]633;A←]633;P;Cwd=C:\x5cUsers\x5cUSERPS C:\Users\USER> ←]633;B`
And at the same time I also hear bell sound.

I tried this version in a new Windows 8.1 Pro, but cannot reproduce this problem.

**Comment by meganrogge** [comment]
You need to update your powershell version. If you cannot do that, disable shell integration via terminal.integrated.shellIntegration.enabled: false

**Comment by neolib** [comment]
I don't think it's caused by PowerShell version. It had been working without any problem before 1.75.1.

BTW, can you tell me how VSCode changes this prompt so that I can fix it myself?

**Comment by neolib** [comment]
Please see my post on SO: https://stackoverflow.com/questions/75428157/weird-powershell-prompt. There are other people having this similar problem.

**Comment by neolib** [comment]
Okay, I found it myself. I commented out the Prompt() function in C:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\contrib\terminal\browser\media\shellIntegration.ps1. Now the PS terminal prompt comes back, but it still shows some code for the first start:

←]633;P;IsWindows=PS C:\Build\test\vscode\test>
