### ISSUE TITLE
Release Notes goes blank when (anchor?) link is clicked

### ISSUE THREAD

**Issue by neminovno** [Microsoft/vscode#17417]
- VSCode Version: November 2016 (version 1.8)
- OS Version: Windows 7 64bit

Steps to Reproduce:
When new version is installed, top bar appears with view Release Notes button:
1. click to see Release notes
2. click any link for example in key highlights list
3. editors screen is blank / no text visible

_Animated preview_
![vscode_releasenotes_onclicknotvisible](https://cloud.githubusercontent.com/assets/1468887/21278401/3bd2d80a-c3db-11e6-94de-7987edd0fe02.gif)

**Comment by kieferrm** [comment]
Can't reproduce on Win10 or macOS.

**Comment by mjbvz** [comment]
@kieferrm This looks similar to #16337 which we fixed. I also cannot repo this on the 1.8 release on windows or mac

**Comment by neminovno** [comment]
Now it is OK, after actual update executed. Here is what happened:
- I thought wrong that when app is closed then opened = restart (and update), but it looks one have to click "restart" button in notification bar to do the update
- preview animation shows app viewing Release Notes of 1.8.0 although that version was not yet installed, I think I had 1.7.(0 or 1) when animation was created

So that makes this issue equal to #16337.
