### ISSUE TITLE
activity bar icon flashing when startup

### ISSUE THREAD

**Issue by tjx666** [microsoft/vscode#174144]
https://user-images.githubusercontent.com/41773861/218261071-890d62ec-1338-4c6e-aaa9-9bc31ef6e558.mov

<img width="801" alt="image" src="https://user-images.githubusercontent.com/41773861/218262604-5f4d58bc-d077-41f7-a92b-e169032d2d43.png">

```
Version: 1.75.1 (Universal)
Commit: 441438abd1ac652551dbe4d408dfcec8a499b8bf
Date: 2023-02-08T21:34:59.000Z
Electron: 19.1.9
Chromium: 102.0.5005.194
Node.js: 16.14.2
V8: 10.2.154.23-electron.0
OS: Darwin x64 22.3.0
Sandboxed: No
```

**Comment by nimcomputing** [comment]
I see the same, but figured it was down to the selected VS Code profile being enabled for that workspace?
