### ISSUE TITLE
TypeScript symbols is empty inside closure (like jQuery plugins)

### ISSUE THREAD

**Issue by Ciantic** [Microsoft/vscode#1741]
I tried developing basic jQuery plugin with TS, looks like the symbols list is totally empty if I use following code:

```
/// <reference path="./typings/tsd.d.ts" />
(function ($: JQueryStatic) {

    interface Anything {
        something : string
    }

    function func() {
    }

})(jQuery);
```

I think it should recgonize the whole file spanning closure and not let it ruin the symbols listing.

**Comment by felixfbecker** [comment]
I also think this is annoying. Symbols view only shows symbols in the global scope, also for Javasript. If you use class expressions for Angular, like `.controller('MyController', class MyController { ... })` you will never get any methods of that class show up in the symbol view.

**Comment by paramquery** [comment]
+1

much needed feature.

**Comment by jrieken** [comment]
This is an issue with TypeScript. For JavaScript this actually works a lot better then for TypeScript...

**Comment by jrieken** [comment]
This issue was moved to Microsoft/TypeScript#8218
