### ISSUE TITLE
Sticky-scroll is handling mouse releases inadvertently (e.g. from text selections) 

### ISSUE THREAD

**Issue by kristiker** [microsoft/vscode#174205]
Does this issue occur when all extensions are disabled?: Yes.

- VS Code Version: 1.75.1 and the one before that
- OS Version: W10

Sticky-scroll is handling mouse releases inadvertently. This causes unintended and confusing jumps.

Steps to Reproduce:

1. Select text from within the find/replace widget.
2. Hold LMB.
3. Move cursor outside widget, position it over the sticky-scroll lines.
4. Release LMB.
5. Editor will take it as if you clicked on the sticky-scroll lines.

![image](https://user-images.githubusercontent.com/26466974/218342666-d577eefb-2ff2-4c59-a016-e305147f1f14.png)

**Comment by Clarkkkk** [comment]
Agreed. The jump action should be triggered by a `click` event rather than a `mouseup` event.

**Comment by kristiker** [comment]
That's right, thank you for the helpful keywords. Makes me wonder if the fix for this issue is a simple attribute swap.

**Comment by Clarkkkk** [comment]
I think it is resolved in 1.82.0. Maybe you can close the issue now.

**Comment by aiday-mar** [comment]
Grea thanks!
