### ISSUE TITLE
Please release a new version of `ripgrep-prebuilt`, it saved ~33 MiB in vscode

### ISSUE THREAD

**Issue by kkocdko** [microsoft/vscode#174294]
The issue https://github.com/microsoft/ripgrep-prebuilt/issues/15 reported this problem and it's fixed, but no versions released after that fix. So **until now the ripgrep binary in vscode still so big:**

```
[kkocdko@klf vscode-linux-x64]$ ls -lh ./node_modules/@vscode/ripgrep/bin/rg 
-rwxr-xr-x. 1 kkocdko kkocdko 38M Oct 27  2021 ./node_modules/@vscode/ripgrep/bin/rg
[kkocdko@klf vscode-linux-x64]$ strip ./node_modules/@vscode/ripgrep/bin/rg 
[kkocdko@klf vscode-linux-x64]$ ls -lh ./node_modules/@vscode/ripgrep/bin/rg 
-rwxr-xr-x. 1 kkocdko kkocdko 5.4M Feb 14 07:13 ./node_modules/@vscode/ripgrep/bin/rg
[kkocdko@klf vscode-linux-x64]$ 
```

Please, please release a new version of [ripgrep-prebuilt](https://github.com/microsoft/ripgrep-prebuilt/) and [vscode-ripgrep](https://github.com/microsoft/vscode-ripgrep).

**Comment by andreamah** [comment]
done in https://github.com/microsoft/vscode/pull/177109#event-8746120419

**Comment by andreamah** [comment]
Hi @kkocdko! Can you verify that you see a smaller ripgrep executable in the insiders version? Thanks!

**Comment by connor4312** [comment]
```
$ du -h bin/*/rg
3.2M    bin/aarch64-apple-darwin/rg
3.9M    bin/aarch64-unknown-linux-musl/rg
3.5M    bin/arm-unknown-linux-gnueabihf/rg
3.8M    bin/i686-unknown-linux-musl/rg
4.3M    bin/powerpc64le-unknown-linux-gnu/rg
4.9M    bin/s390x-unknown-linux-gnu/rg
3.9M    bin/x86_64-apple-darwin/rg
4.9M    bin/x86_64-unknown-linux-musl/rg
```

**Comment by kkocdko** [comment]
> ed this problem and it's fixed, but no versions released after that fix. So **until now the ripgrep binary in vscode still so big:**

It's fine now, thanks to every contributors!
