### ISSUE TITLE
"Go to test" shortcut not working

### ISSUE THREAD

**Issue by mahmoudsalah1993** [microsoft/vscode#174241]
Type: <b>Bug</b>

1- Open a test file.
2- Click on a specific test. 
3- Check the go to test button is assigned (Alt + Enter) shortcut.
4- Hit Alt+Enter.

Expected:
Navigates to test.

Actual:
Nothing happens.

VS Code version: Code 1.75.1 (Universal) (441438abd1ac652551dbe4d408dfcec8a499b8bf, 2023-02-01T15:24:42.903Z)
OS version: Darwin x64 22.3.0
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (0.08GB free)|
|Process Argv|--crash-reporter-id 908a9053-caf1-4cd5-8e77-87f61654caf8|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (18)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|2.4.0
EditorConfig|Edi|0.16.4
gitpod-desktop|git|0.0.74
go|gol|0.37.1
isort|ms-|2022.8.0
python|ms-|2023.2.0
vscode-pylance|ms-|2023.2.20
jupyter|ms-|2023.1.2010391206
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.14
vscode-jupyter-cell-tags|ms-|0.1.6
vscode-jupyter-slideshow|ms-|0.1.5
remote-containers|ms-|0.275.1
remote-ssh|ms-|0.96.0
remote-ssh-edit|ms-|0.84.0
remote-wsl|ms-|0.75.2
vscode-remote-extensionpack|ms-|0.23.0
remote-explorer|ms-|0.2.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
azure-dev_surveyone:30548225
pyindex848:30577860
nodejswelcome1cf:30587006
282f8724:30602487
pyind779cf:30657577
89544117:30613380
pythonsymbol12:30657548
vscodedisable:30660115

```

</details>

<img width="2148" alt="image" src="https://user-images.githubusercontent.com/13228044/218457455-f60760f7-2280-4495-a8be-48abb6dcbd32.png">

**Comment by mahmoudsalah1993** [comment]
Updated to Version: 1.75.1 (Universal)
Commit: 441438abd1ac652551dbe4d408dfcec8a499b8bf

The issue is still reproducible.

**Comment by connor4312** [comment]
Possibly duplicates https://github.com/microsoft/vscode/issues/131538

**Comment by mahmoudsalah1993** [comment]
This seems like it, changing the shortcut to alt + 5 or other keybinding didn't help in my case too.
