### ISSUE TITLE
VSCode deletes all my changes! Again!

### ISSUE THREAD

**Issue by unional** [microsoft/vscode#174203]
This is the same issue as: https://github.com/microsoft/vscode/issues/168003

It just happens again. Again I was renaming a folder: `tests/test-nodejs` to `tests/nodejs` from the vscode explorer.

It got stucked, and then many other files are deleted, from other folders: `packages/*`, `test-plugins/*`.

Clearly something is corrupted in memory.

Again, it's not something that can be reproduced...

**Comment by lramos15** [comment]
So far you're the only user report we've gotten of this and I cannot repro so it makes it difficult to track down what happens. Does this happen to all programming language types? Have you tried disabling extensions?

**Comment by unional** [comment]
I understand. Both time it happens to be when I'm working on TypeScript repo (two different repos). But I don't think that is related to TypeScript at all as the action involved are Explorer folder rename/move.

Both time it happens when I worked on the repo for a few hours. So there is not much of a chance to just "repro" it, or try disabling the extensions.

I can help by listing the extensions that I was using for those repo. is there a way to list them easily? There is a `Developer: Show running extensions` but I can't copy the result.

**Comment by lramos15** [comment]
> I can help by listing the extensions that I was using for those repo. is there a way to list them easily? There is a `Developer: Show running extensions` but I can't copy the result.

Help -> Report issue should have all your extensions listed at the bottom

**Comment by unional** [comment]
> Help -> Report issue should have all your extensions listed at the bottom

Thx. here it is:


<html>
<body>


Extension | Author (truncated) | Version
-- | -- | --
better-comments | aar | 3.0.2
codesnap | adp | 1.3.4
emojisense | bie | 0.9.1
vscode-markdownlint | Dav | 0.48.1
vscode-eslint | dba | 2.2.6
gitlens | eam | 13.1.1
EditorConfig | Edi | 0.16.4
prettier-vscode | esb | 9.10.4
vscode-pull-request-github | Git | 0.54.1
vscode-advanced-open-file | jit | 0.3.0
vscode-random | jre | 1.11.0
color-the-tag-name | jzm | 0.19.8
vs-color-picker | lih | 1.0.0
git-graph | mhu | 1.30.0
vscode-filesize | mkx | 3.1.0
prettify-json | moh | 0.0.3
remote-wsl | ms- | 0.66.3
vscode-versionlens | pfl | 1.0.10
material-icon-theme | PKi | 4.22.0
vscode-sort-json | ric | 1.20.0
vscode-open | san | 0.1.0
code-spell-checker | str | 2.14.0
vscode-markdown-paste-image | tel | 0.19.3
pdf | tom | 1.2.2
sort-lines | Tyr | 1.9.1
vscode-mdx | uni | 1.0.3
vscode-sort-package-json | uni | 1.3.0
quokka-vscode | Wal | 1.0.477
markdown-all-in-one | yzh | 3.5.0


</body>
</html>

**Comment by lramos15** [comment]
What are your system specs? Do you have many other applications open?

**Comment by unional** [comment]
Here is my system info:

<html>
<body>


CPUs | AMD Ryzen 7 5800X 8-Core Processor (16 x 3800)
-- | --
GPU Status | 2d_canvas: enabled canvas_oop_rasterization: disabled_off direct_rendering_display_compositor: disabled_off_ok gpu_compositing: enabled multiple_raster_threads: enabled_on opengl: enabled_on rasterization: enabled raw_draw: disabled_off_ok skia_renderer: enabled_on video_decode: enabled video_encode: enabled vulkan: disabled_off webgl: enabled webgl2: enabled webgpu: disabled_off
Load (avg) |  
Memory (System) | 63.92GB (36.49GB free)
Process Argv | D:\code\mocktomata\mocktomata --crash-reporter-id c07ca3ac-e26f-4cb9-a87e-8b28232d5810
Screen Reader | no
VM | 0%


</body>
</html>

It is recorded now, so the memory usage is of course not reflecting when the problem occurs.

I have some browser instances/tabs (probably less than 10), Docker Desktop, discord, and slack opened at the time.

There are about 2~3 instances of VSCode opened at the time.

Others are not that significant such as PowerToy, Box Drive, etc.

**Comment by lramos15** [comment]
I would say without disabling extensions we won't get to the bottom of this. Something is occurring during your rename operation. Nobody else is experiencing such issues and it seems like your machine is plenty powerful. I wish I had a better answer or solution.

**Comment by unional** [comment]
Yes. I understand. Just adding this issue for reference.

**Comment by lramos15** [comment]
Will close for now, but keep me posted if you come across any additional information
