### ISSUE TITLE
share class constructor documentations in others files

### ISSUE THREAD

**Issue by djmisterjon** [microsoft/vscode#174229]
if i mouse hover a ->**imported**<-  class (alias), i cant get documentation when mouse hover!
![image](https://user-images.githubusercontent.com/24865815/218419350-88c16a39-4b92-4a33-8f4d-b516d71bb69a.png)

it work only if we are in same file !
![image](https://user-images.githubusercontent.com/24865815/218419918-04fb7a4b-5a0c-4eb3-a076-16669b1f4153.png)

It there a options or features to share documentations on imported class ?

**Comment by mjbvz** [comment]
This feature is powered by the TypeScript project. Please [file an issue upstream](https://github.com/microsoft/TypeScript/issues/new?template=Feature_request.md)
