### ISSUE TITLE
Write of large buffer in WebSocketNodeSocket can hold NodeJS thread too long

### ISSUE THREAD

**Issue by MarkZuber** [microsoft/vscode#174277]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 
- OS Version: 

In node/ipc.net.ts, a write of a large buffer during remoting can hang the NodeJS thread since the call is synchronous.  There should be a cap on the size of a particular message, and if the buffer is larger then the buffer is sent in chunks.

**Comment by alexdima** [comment]
@MarkZuber How could I reproduce this? Here is what I have tried directly in nodejs:
* `server.js`:
```js
const net = require('net');
net.createServer((socket) => {
	console.log(`new socket received`);
	socket.on('data', (data) => {
		console.log(`received ${data.byteLength} bytes.`);
	});
	socket.on('close', () => {
		console.log(`socket closed`);
	});
}).listen(8686);
```
* `client.js`:
```js
const net = require('net');
const socket = net.connect(8686, () => {
	socket.setNoDelay(true);
	const data = new Uint8Array(100 * 1024 * 1024);
	const start = performance.now();
	socket.write(data);
	console.log(`.write took: ${performance.now() - start} ms.`);
	socket.on('drain', () => {
		console.log(`draining took: ${performance.now() - start} ms.`);
		socket.end();
	});
});
```
And I get the following times:
```
.write took: 0.3226669728755951 ms.
draining took: 83.85174998641014 ms.
```

**Comment by MarkZuber** [comment]
The difference is this isn't just socket traffic, this goes through the zlib layer.   FlowManager.writeMessage() calls this.deflateMessage().  This is also over variable network quality levels (speed, latency, etc).  We have timing on the deflateMessage call (see delayMs in the code below) to see if it takes more than one second to flush the zlibDeflateStream() and we get single digit millions of hits per day even with the 10mb chunking.  Because we've chunked it up the times are usually 1.2-1.5 seconds for the instances we hit it.  And that code isn't async so it can block the node thread.  

We do have some extensions that send large amounts of data so breaking this up helps us out.   We've also tried doing stack traces around this to assign blame to an extension but haven't as yet figured out the right way to collect and aggregate that so we can point fingers to see if we can fix the large transfers at the source.


```
private _deflateMessage(zlibDeflateStream: ZlibDeflateStream, buffer: VSBuffer): Promise<VSBuffer> {
		return new Promise<VSBuffer>((resolve, reject) => {
			const start = performance.now();
			zlibDeflateStream.write(buffer);

			zlibDeflateStream.flush(data => {
				const end = performance.now();
				if (end - start > 1000) {
					this._telemetryCallback('ipc.zlibFlushDelay', { delayMs: end - start, bufferSize: buffer.byteLength });
				}
				resolve(data);
			});
		});
	}
```

**Comment by alexdima** [comment]
Thanks a lot for the extra information! I couldn't reproduce the event loop freezes you mention with a quick test, but I agree, we should cap websocket message sizes because we're not using websocket messages as logical entities, we are sending and consuming these messages as part of a stream and we shouldn't have very large chunks. Mostly notes for myself why reducing the websocket messages sizes would be a good idea:

> I think there's a problem if one side writes many logical messages (let's say 1000 messages of 100KB) during a single process tick. We do this thing where we install a process.nextTick timer and group all of them together and we then issue a single `WebSocketNodeSocket.write` with a 100MB buffer. The first problem is that the actual writing to the underlying node socket will only happen after all of the 100MB have been deflated (due to [waiting on zlib flush](https://github.com/microsoft/vscode/blob/492e7d5e337826bd241b2a4727ed9bf042a4ff3f/src/vs/base/parts/ipc/node/ipc.net.ts#L539)). The second problem is on the reading side, where we will get a single `WebSocketNodeSocket.onData` event fired when all the 100MB have arrived, delaying processing the 1000 received messages until all have arrived, instead of processing them as each one arrives.

Here's what I tried to do in order to reproduce a freeze on the event loop, but I was not successful. I've created the following patch which adds a test where it sends 100MB from one WebSocketNodeSocket to another :

```diff
diff --git a/src/vs/base/parts/ipc/test/node/ipc.net.test.ts b/src/vs/base/parts/ipc/test/node/ipc.net.test.ts
index ed797697982..5c8d729d55c 100644
--- a/src/vs/base/parts/ipc/test/node/ipc.net.test.ts
+++ b/src/vs/base/parts/ipc/test/node/ipc.net.test.ts
@@ -5,7 +5,7 @@
 
 import * as assert from 'assert';
 import { EventEmitter } from 'events';
-import { createServer, Socket } from 'net';
+import { AddressInfo, connect, createServer, Server, Socket } from 'net';
 import { tmpdir } from 'os';
 import { Barrier, timeout } from 'vs/base/common/async';
 import { VSBuffer } from 'vs/base/common/buffer';
@@ -706,4 +706,60 @@ suite('WebSocketNodeSocket', () => {
 			assert.deepStrictEqual(actual, 'Helloworld');
 		});
 	});
+
+	test.only('Sending very large messages', async () => {
+
+		const server = await listenOnRandomPort((socket) => {
+			const webSocketNodeSocket = new WebSocketNodeSocket(new NodeSocket(socket), true, null, false);
+			webSocketNodeSocket.onData((data) => {
+				console.log(`received ${data.byteLength} bytes.`);
+			});
+			socket.on('close', () => {
+				console.log(`socket closed`);
+			});
+		});
+
+		const socket = connect({
+			host: '127.0.0.1',
+			port: (<AddressInfo>server.address()).port
+		});
+
+		const buff = generateRandomBuffer(100 * 1024 * 1024);
+
+		console.profile('sample');
+
+		const nodeSocket = new NodeSocket(socket);
+		const webSocketNodeSocket = new WebSocketNodeSocket(nodeSocket, true, null, false);
+
+		const start = performance.now();
+		webSocketNodeSocket.write(buff);
+		console.log(`.write() took ${performance.now() - start}ms.`);
+
+		const start2 = performance.now();
+		await webSocketNodeSocket.drain();
+		console.log(`.drain() took ${performance.now() - start2}ms.`);
+
+		webSocketNodeSocket.dispose();
+		console.profileEnd('sample');
+	});
+
+	function generateRandomBuffer(size: number): VSBuffer {
+		const buff = VSBuffer.alloc(size);
+		for (let i = 0; i < size; i++) {
+			buff.writeUInt8(Math.floor(256 * Math.random()), i);
+		}
+		return buff;
+	}
+
+	function listenOnRandomPort(handler: (socket: Socket) => void): Promise<Server> {
+		return new Promise((resolve, reject) => {
+			const server = createServer(handler).listen(0);
+			server.on('listening', () => {
+				resolve(server);
+			});
+			server.on('error', (err) => {
+				reject(err);
+			});
+		});
+	}
 });
```
The test can be executed with `./scripts/test.sh --run src/vs/base/parts/ipc/test/node/ipc.net.test.ts --dev` which will then automatically create a JS CPU profile (you might need to reload once with dev tools opened to get the CPU profile calls working):

Here's the console output I see:
<img width="262" alt="image" src="https://user-images.githubusercontent.com/5047891/220474412-d11406d9-68c8-4393-af40-d089bcbb67c5.png">

And here is the CPU profile:
<img width="1227" alt="image" src="https://user-images.githubusercontent.com/5047891/220474492-41011a90-e430-4bf5-9026-b86f220b9fea.png">
<img width="1227" alt="image" src="https://user-images.githubusercontent.com/5047891/220474537-982072fc-5e83-4530-a699-5596dc251a27.png">

---

After applying the proposed changes from #174278:

```diff
diff --git a/src/vs/base/parts/ipc/node/ipc.net.ts b/src/vs/base/parts/ipc/node/ipc.net.ts
index 455caa3efeb3c..2a10bca0d57e5 100644
--- a/src/vs/base/parts/ipc/node/ipc.net.ts
+++ b/src/vs/base/parts/ipc/node/ipc.net.ts
@@ -300,7 +300,17 @@ export class WebSocketNodeSocket extends Disposable implements ISocket, ISocketT
 	}
 
 	public write(buffer: VSBuffer): void {
-		this._flowManager.writeMessage(buffer);
+		const maxSendChunkSize = 10 * 1024 * 1024;
+
+		if (buffer.byteLength <= maxSendChunkSize) {
+			this._flowManager.writeMessage(buffer);
+		} else {
+			let start = 0;
+			while (start < buffer.byteLength) {
+				this._flowManager.writeMessage(buffer.slice(start, Math.min(start + maxSendChunkSize, buffer.byteLength)));
+				start += maxSendChunkSize;
+			}
+		}
 	}
 
 	private _write(buffer: VSBuffer, compressed: boolean): void {
```

<img width="1226" alt="image" src="https://user-images.githubusercontent.com/5047891/220476200-30a50f87-0833-4e7f-a8ea-6f218c8912eb.png">

<img width="1224" alt="image" src="https://user-images.githubusercontent.com/5047891/220476299-f3034bdd-720d-4de1-9f19-2b48d105c4dc.png">

**Comment by alexdima** [comment]
After running the CPU profiler manually, I do see that time is spent in [concatenating the deflated bytes on the writing side](https://github.com/microsoft/vscode/blob/492e7d5e337826bd241b2a4727ed9bf042a4ff3f/src/vs/base/parts/ipc/node/ipc.net.ts#L682-L683)

<img width="1228" alt="image" src="https://user-images.githubusercontent.com/5047891/220479447-965ce413-05dd-49ef-aeda-e246cfe74b18.png">
