### ISSUE TITLE
What format setting is responsible for this?

### ISSUE THREAD

**Issue by cesarvarela** [Microsoft/vscode#17427]
- VSCode Version: 1.8.0
- OS Version: Sierra

Sorry if this is the wrong place but can't find anything about this.

What format option is reponsable for this?

![image](https://cloud.githubusercontent.com/assets/1172479/21280585/9ebe3c22-c3c5-11e6-802b-04814f57df68.png)

**Comment by mjbvz** [comment]
I do not think we expose any option to control this formatting option currently. Formatting always seems to insert a space.

Is this a formatting option that you would find useful? If so, would you also expect this option to apply to other block statements and before function bodies?

**Comment by cesarvarela** [comment]
YES PLEASE!

it should be something like `insertSpaceBetweenClosingParenthesisAndOpeningBraces` 

`while(something) {`, `function() {`, `if(something) {`, etc.

**Comment by mjbvz** [comment]
Tracking this on the TypeScript side with https://github.com/Microsoft/TypeScript/issues/13038

Thanks
