### ISSUE TITLE
editor.renderWhitespace: "boundary" toggles back to "all"

### ISSUE THREAD

**Issue by olzaragoza** [Microsoft/vscode#17421]
- VSCode Version: 1.8.0
- OS Version: win 10 1607

Steps to Reproduce:

1.  add "editor.renderWhitespace": "boundary" to settings.json
2.  close and reopen vscode
3. open existing document (doc whitespace shown: boundary)
4. Toggle Render Whitespace (doc whitespace shown: none)
5. Toggle Render Whitespace (doc whitespace shown: all) <--- should toggle back to boundary

- Simply closing and reopening the file keeps the whitespace the same as before closing (either none or all)
- closing then reopening vscode resets whitespace shown to boundary
- I would like either a 3-way whitespace toggle (none, boundary, or all) or make the toggle work between render none and render user-specified

**Comment by kieferrm** [comment]
`Toggle Render Whitespace` goes from `not off` to `off` and then toggles between `off` and `all` no matter what is specified in the `settings.json`.

**Comment by olzaragoza** [comment]
is there a way to toggle between `off` and `boundary` without closing and reopening vscode?

**Comment by rebornix** [comment]
It's a good extension candidate and you can follow https://medium.com/hack-visual-studio-code/toggle-any-setting-in-vs-code-using-keyboard-shortcut-arguments-cdb5ddc56955 to get your preferred extension to archive that.

**Comment by alexandrudima** [comment]
This feature request will not be considered in the next [6-12 months roadmap](https://github.com/Microsoft/vscode/wiki/Roadmap) and as such will be closed to keep the number of issues we have to maintain actionable. Thanks for understanding and happy coding!
