### ISSUE TITLE
editor.action.insertLineBefore does not fire onDidChangeTextEditorSelection

### ISSUE THREAD

**Issue by xconverge** [Microsoft/vscode#17429]
The VsCodeVim plugin uses insert line before and insert line after commands.

`editor.action.insertLineBefore` 
`editor.action.insertLineAfter`

We then wait for the onDidChangeTextEditorSelection to fire to know that the operation was completed.

Now after running insertLineBefore, the event is NOT fired. As soon as you move the cursor from here it is, but not just when running the action, even though the cursor position changed

1. Is there a reason why this event stopped firing for these commands?
2. Is there a better way for us to know a command completed, we await and then how do we know the actual change occurred.

**Comment by rebornix** [comment]
Just played around with it and find that when you run `editor.action.insertLineBefore`, we put a line above current line and move the cursor to the new line. If you compare the selection before and after, it does not change indeed. The only changed thing about the cursor is now the cursor is between new markers.
