### ISSUE TITLE
help immediately

### ISSUE THREAD

**Issue by noobswitgunz96** [microsoft/vscode#174219]
ADD ISSUE DESCRIPTION HERE

Version: 1.76.0-insider
Commit: c7930ca55d072608625ba76c13b5f9baaf9a2136
User Agent: Mozilla/5.0 (X11; CrOS x86_64 14541.0.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36
Embedder: codespaces

Ivebeen hacked for two years. after coming close to discovering the identity of the attacker, my settings were being changed and reset while Io was trying to lock the person who remotely accessed my code space out of the space. help

**Comment by gjsjohnmurray** [comment]
I suggest you use https://support.github.com/contact/account

**Comment by bhavyaus** [comment]
If you have any issues with vscode, please let us know.
