### ISSUE TITLE
Merge #157920

### ISSUE THREAD

**Issue by gregorybleiker** [microsoft/vscode#174228]
Is there any reason this hasn't been merged into main, @bpasero? Seems like an obvious feature...

**Comment by gjsjohnmurray** [comment]
Apparently @Pospelove who authored PR https://github.com/microsoft/vscode/pull/157920 closed it unmerged. Maybe @bpasero will unlock it and review.

**Comment by bpasero** [comment]
Feel free to create a new PR working on that task.

Be patient with feedback on PRs though: for me this is limited to issue grooming iterations (December each year).
