### ISSUE TITLE
Typescript, vscode can't find react module without reference.

### ISSUE THREAD

**Issue by MartynasZilinskas** [Microsoft/vscode#1742]
I have encountered problems with Visual Studio Code that I haven't with Visual Studio. Is there any way to prevent this without using reference?  

Without reference:
![image](http://i.imgur.com/JIOmEAH.png)
With reference:
![image](http://i.imgur.com/8S9Okvc.png)

**Comment by felixfbecker** [comment]
I don't have this problem

**Comment by jrieken** [comment]
@MartynasZilinskas Is this with JS or TS files?

**Comment by MartynasZilinskas** [comment]
@jrieken it's with Typescript files.

**Comment by dbaeumer** [comment]
@MartynasZilinskas pls see https://code.visualstudio.com/docs/languages/typescript. In VSCode you can either use /// references or tsconfig.json to describe your project scope. If you want to avoid /// references you need to define the project using a tsconfig.json file.

**Comment by rjrudman** [comment]
This still happens, even with the correct setting in tsconfig.json. tsc compiles without an issue (as does webpack).

Here's my tsconfig.json (located in the root directory)

```
{
    "compilerOptions": {
        "outDir": "./dist/",
        "sourceMap": true,
        "noImplicitAny": true,
        "module": "commonjs",
        "target": "es5",
        "jsx": "react"
    },
    "files": [
        "./typings/index.d.ts"
    ],
    "include": [
        "./typings/*.ts",
        "./scripts/**/*.ts"
    ]
}
```

Here's index.tsx (located in /scripts/index.tsx)
```
/// <reference path="../typings/index.d.ts" />

import * as React from "react";
import * as ReactDOM from "react-dom";

import { Hello } from "./components/Hello";

ReactDOM.render(
    <Hello compiler="TypeScript" framework="React" />,
    document.getElementById("example")
);
```


Removing the /// reference causes errors on the two imports. Interestingly, it also affects Hello.tsx (located in /scripts/components/Hello.tsx)

```
import * as React from "react";

export interface HelloProps { compiler: string; framework: string; }

export class Hello extends React.Component<HelloProps, {}> {
    render() {
        return <h1>Hello from {this.props.compiler} and {this.props.framework}!</h1>;
    }
}
```

Showing errors on this.props and the import statement. This is frustrating as adding that /// reference line breaks the source map (the debugger is offset by one executable line)
