### ISSUE TITLE
CSS variable missing in Dark High Contrast theme

### ISSUE THREAD

**Issue by eronnen** [microsoft/vscode#174204]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.75.1
- OS Version: Ubuntu

The CSS variable `--vscode-button-background` is not defined in `Dark High Contrast` theme

**Comment by aeschli** [comment]
Yes, that's correct: https://github.com/microsoft/vscode/blob/main/src/vs/platform/theme/common/colorRegistry.ts#L277

But that's not a bug. Colors can be undefined. Likely the Dark High Contrast only want to show a border.
