### ISSUE TITLE
Release notes display

### ISSUE THREAD

**Issue by glittle** [Microsoft/vscode#17425]
- VSCode Version: Code 1.8.0 (38746938a4ab94f2f57d9e1309c51fd6fb37553d, 2016-12-13T17:45:32.595Z)
- OS Version: Windows_NT ia32 6.3.9600
- Extensions:

|Extension|Author|Version|
|---|---|---|
|Theme-Flat|gerane|0.0.2|
|easy-less|mrcrowl|1.2.5|
|csharp|ms-vscode|1.5.3|
|vs-keybindings|ms-vscode|0.1.1|
|sass-indented|robinbentley|1.2.1|

---

Steps to Reproduce:

1.  View the release notes (November 2016)
2.  Scroll down as you read them
3.  Switch to another tab to view some code
4.  Switch back to the release notes
5.  The release notes reload and are at the top of the display.

This makes it very hard to read, as it continually reverts to the top of the long document and reloads every time the tab is switched.

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/15214
