### ISSUE TITLE
Selfhost test-provider output diff uninformative

### ISSUE THREAD

**Issue by ulugbekna** [microsoft/vscode#174249]
Does this issue occur when all extensions are disabled?: Yes/No

## Description

The diff for `undefined` and `"[undefined]"` is not informative. Example: 

<img width="974" alt="image" src="https://user-images.githubusercontent.com/16353531/218473560-dd026427-33d4-45f6-a561-2443914910b4.png">

Note how both the actual and expected outputs look the same in the diff editor.

Looking at the hover reveals the real problem.

## Steps to Reproduce:

Run

```
suite('Foo suite', () => {
	test('foo', () => {
		assert.deepStrictEqual({ bar: undefined }, { bar: "[undefined]" });
	});
});
```

## VS Code info

```

Version: 1.76.0-insider (Universal)
Commit: f718f1ace394dba4255774ac3f1c9321f629f8ff
Date: 2023-02-13T05:27:04.434Z (8 hrs ago)
Electron: 19.1.9
Chromium: 102.0.5005.194
Node.js: 16.14.2
V8: 10.2.154.23-electron.0
OS: Darwin arm64 22.3.0
Sandboxed: Yes
```

## Extension info: 

```
Name: VS Code Selfhost Test Provider
Id: ms-vscode.vscode-selfhost-test-provider
Description: Test provider for the VS Code project
Version: 0.3.13
Publisher: Microsoft
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=ms-vscode.vscode-selfhost-test-provider
```

**Comment by connor4312** [comment]
This is because the expected/actual values are stringified to JSON when reported by the test runner, and is what is shown in the diff. JSON has no representation of "undefined", so the `[undefined]` marker is used instead. We'd have to use some different serialization format through the stack.

**Comment by connor4312** [comment]
I don't plan to fix this issue. The alternative is either (a) not using JSON, or (b) using something other than the string `"[undefined]"`. Since we already never expect the string `"[undefined]"` in our tests, I don't think a change is warranted. But I do want to make a small change in the test provider so that it's actually displayed as `undefined` (even though that's not JSON)
