### ISSUE TITLE
Functionality for dropping files from a file system into a custom view in vscode extension API?

### ISSUE THREAD

**Issue by Luke-Callaghan23** [microsoft/vscode#174351]
Hi, I'm wondering if it's possible to get some sort of functionality for handling dropped files from some external source (a file system window) into a custom view, kind of like how in the Explorer view of default vscode, you can drop files from your OS's file system and they will get copied into the workspace of vscode. The extension I'm developing has a custom file explorer and it would be helpful for me to be able to drop files from the file system into that view and handle copying those files from their source location onto my custom file system.

As far as I can tell, the only thing that allows similar functionality right now is vscode.languages.registerDocumentDropEditProvider, but this only provides for a rather niche use-case of dropping files into the editor window when shift is held down. I'd like some API for handling when a file is dropped into the tree view I am creating, without the need for shift to be held down.

Any help would be great.

Thanks

**Comment by mjbvz** [comment]
Sounds like you want `TreeDragAndDropController` for this

See the tree view sample: https://github.com/microsoft/vscode-extension-samples/blob/main/tree-view-sample/src/testViewDragAndDrop.ts

**Comment by Luke-Callaghan23** [comment]
> As far as I can tell, the only thing that allows similar functionality right now is vscode.languages.registerDocumentDropEditProvider, but this only provides for a rather niche use-case of dropping files into the editor window when shift is held down. I'd like some API for handling when a file is dropped into the tree view I am creating, without the need for shift to be held down.

As far as I'm aware the tree drag and drop controller only words for dragging items between tree views.  I was looking to be able to drag items from a file system (outside of VSCode) into a tree view.  Does tree drag and drop controller word for this?

**Comment by mjbvz** [comment]
@Luke-Callaghan23   It should work using the `text/uri-list` mime type. Give it a try

**Comment by Luke-Callaghan23** [comment]
Okay I'll check it out, thanks
