### ISSUE TITLE
Broken layout when changing profiles

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#174345]
I have a default profile and one more profile.
When I switch between the two the layout gets completely broken.

I just started reproducing this the last couple of days.
Please let me know what logs or details I should provide that can help here.

![Screenshot 2023-02-14 at 15 44 27](https://user-images.githubusercontent.com/1926584/218771588-03f34ce8-7968-4217-bb45-39db5cdef615.png)

**Comment by sandy081** [comment]
May be share those two profiles to reproduce.

@sbatten Please start with checing if there are issues with the layout

**Comment by isidorn** [comment]
Here are the two profiles:
https://insiders.vscode.dev/profile/github/b186fa58693a8afe7c06bc613c9baa85
https://insiders.vscode.dev/profile/github/a59ca292cca6530fd646b18ee7af58e5

I still can repro. In case somebody wants to debug on my machine.

**Comment by rzhao271** [comment]
Unable to repro now
