### ISSUE TITLE
Search in Settings editor - not standard search

### ISSUE THREAD

**Issue by glittle** [Microsoft/vscode#17436]
- VSCode Version: Code 1.8.0 (38746938a4ab94f2f57d9e1309c51fd6fb37553d, 2016-12-13T17:45:32.595Z)
- OS Version: Windows_NT ia32 6.3.9600
- Extensions:

|Extension|Author|Version|
|---|---|---|
|Theme-Flat|gerane|0.0.2|
|intellij-idea-keybindings|k--kato|0.2.7|
|easy-less|mrcrowl|1.2.5|
|csharp|ms-vscode|1.5.3|
|vs-keybindings|ms-vscode|0.1.2|
|sass-indented|robinbentley|1.2.1|

---

Steps to Reproduce:

1. In Settings editor, search with the word "color"
2. Most matches have nothing to do with color... they are matching on subsections of letters!

![image](https://cloud.githubusercontent.com/assets/85186/21281489/7f057b22-c3aa-11e6-8cfd-ae09da6050fb.png)

**Comment by bpasero** [comment]
I am seeing this too as an issue, the fuzzy matching is totally fine but what needs to happen is a better sorting algorithm that puts exact matches to the top.
