### ISSUE TITLE
"No suggestions" persists while typing if the completion helper is set to return an empty list for empty content.

### ISSUE THREAD

**Issue by clairewu0218** [microsoft/vscode#174385]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 
- OS Version: 

Steps to Reproduce:

Background: We use Monaco to build our own editor, with our own language server underlying.
1. Set the completionProvider to return no suggestions when the content is empty.
2. In an empty editor, hit Ctrl+Space to trigger Monaco suggestions - there should be "No suggestions"
![image](https://user-images.githubusercontent.com/104450101/218820842-a5668241-7499-422d-90a8-52b9b7a5c425.png)
3. Begin typing. It won't trigger the completionProvider until you hit a trigger character.
![image](https://user-images.githubusercontent.com/104450101/218820900-d741fc4e-af82-46b7-a70d-51f23ad80cb2.png)
It only happens after you hit Ctrl+Space in an empty editor.
Normally it works like this:
![image](https://user-images.githubusercontent.com/104450101/218821049-0ea60462-1132-4fd1-bb56-71a683e7b547.png)

We believe the issue is in this line: https://github.com/microsoft/vscode/blob/main/src/vs/editor/contrib/suggest/browser/suggestModel.ts#L672
It checks if the user has started typing new character by comparing the end of last word with a start of new word. It does that comparison by checking if end is less than the start of the new word. This gets tricky when you type the "i" and the previous value was an empty string. This prevents it from triggering it.

**Comment by hediet** [comment]
What are the reproduction steps to get this behavior in VS Code?

**Comment by clairewu0218** [comment]
We are using Monaco to build our own editor so technically we didn't reproduce it in VS Code. We found this issue in https://github.com/microsoft/vscode/blob/main/src/vs/editor/contrib/suggest/browser/suggestModel.ts#L672, which is under vscode repo so I think I should file it here.

**Comment by hediet** [comment]
> technically we didn't reproduce it in VS Code

Closing as it does not to surface in VS Code.
