### ISSUE TITLE
Add IHoverWidget.onDidHideHover

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#174363]
This is one of the things that `setupCustomHover` gives that `IHoverService.showHover` doesn't easily.

A reason in the event would also be useful.

cc @TylerLeonhardt

**Comment by TylerLeonhardt** [comment]
`setupCustomHover` also triggers the `IHoverDelegate#onDidHideHover()` function which would be great if mirroring that was included in this work.

**Comment by Tyriar** [comment]
Covered in https://github.com/microsoft/vscode/issues/204965

/duplicate
