### ISSUE TITLE
Disable the new javascript IntelliSense in html...

### ISSUE THREAD

**Issue by gplume** [Microsoft/vscode#17433]
- VSCode Version: 1.8
- OS Version: Ubuntu 16.04/Windows-10
I know lots of users were waiting for it but in my case it breaks because I tend to fill some JS Global vars (mostly for i18n use) with server side code templating system for html (with Golang and personalized delimiters).
```
(*.html file)
<script>
var Globals = {
    someVar: [[T "translated"]]
}
</script>
```
... breaks awfully.
I've tried settings.json:
```
    "html.format.unformatted": "script",
    "javascript.format.enable": false,
    "html.format.enable": false,
    "typescript.validate.enable": false,
    "javascript.validate.enable": false,
    "files.associations": {
         "*.html": "html"
    }
```
without success..
Is there any way?
Thanks and sorry if it's the wrong place to ask but if not possible then tag it with "feature-request" please!

**Comment by Spown** [comment]
I have the same problem. my templates are .html files that are actually a nunjucks templates. I use TWIG-Pack extension that I assume uses HTML lang internally. So after the 1.8 update I see a bunch on of new warnings
![](https://dl.dropboxusercontent.com/u/105338698/ShareX/2016-12/Code_2016-12-17_12-18-27.png)
However I think a level of control is needed here. For example if a syntax coloring extension uses HTML internally - it should decide weather to use or suppress javascript linting/Intellisense in HTML. The same goes for css inside ``style`` properties.
![](https://dl.dropboxusercontent.com/u/105338698/ShareX/2016-12/Code_2016-12-17_12-24-21.png)

**Comment by acdha** [comment]
I ran into the same issue with a Django template. Normally it's fine since I'm passing in string values but I have a few cases where I'm passing in numbers or JSON (e.g. `<script>var foo = {{ pile-o-data|json }};</script>`) and it'd be nice if there was a clean way to allow that.

**Comment by aeschli** [comment]
I added two settings
```json

          "type": "boolean",
          "default": true,
          "description": "%html.validate.scripts%"
        },
        "html.validate.styles": {
          "type": "boolean",
          "default": true,
          "description": "%html.validate.styles%"
        },
```
that let you disable the validation of embedded css and javascript.

The issue title talks about intellisense (code completion) which is not configurable. I thought that's less of an issue as it would just return less proposals, which should not block the user.

**Comment by Spown** [comment]
shouldn't these options be placed under [lang-specific](https://code.visualstudio.com/updates/v1_9#_language-specific-settings) from now on? under ``"[html]": {...}``?

**Comment by aeschli** [comment]
@Spown  "[html]": {...} settings lets you override **editor** settings for when an editor has a certain language mode selected.

"html.validate.scripts" configures the built-in html language support.

**Comment by Spown** [comment]
and that's how entropy levels rise... I'm not arguing, just saying.
