### ISSUE TITLE
"Toggle panel visibility" binding causes scroll up in integrated terminal

### ISSUE THREAD

**Issue by thatDudo** [microsoft/vscode#174380]
Type: <b>Bug</b>

1. Close integrated terminal either through button top right or key shortcut
2. Press the key shortcut for "toggle panel visibility" -> Opens integrated terminal
3. Scroll from before is still there, looks normal (BUT scrollbar is on TOP not where it should be!)
4. Try to scroll up on mouse wheel -> Doesnt react
5. Try to scroll down on mouse wheel -> Terminal scrolls up to top (where scrollbar is)

Key binding for "toggle panel visibility":
![Screenshot from 2023-02-14 19-17-47](https://user-images.githubusercontent.com/58403773/218823376-18b82060-6828-4811-bfa2-0d0f972926d1.png)

Demo:

[out.webm](https://user-images.githubusercontent.com/58403773/218828621-3946ac70-d663-4255-b113-2b85bb61e3c5.webm)

Opening through View > Terminal doesnt produce this bug.

VS Code version: Code 1.75.1 (441438abd1ac652551dbe4d408dfcec8a499b8bf, 2023-02-08T21:35:30.018Z)
OS version: Linux x64 5.15.0-60-generic snap
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen ...|
|GPU Status|2d_canvas: unavailable_software<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>opengl: disabled_off<br>rasterization: disabled_software<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software<br>webgpu: disabled_off|
|Load (avg)|0, 0, 0|
|Memory (System)|15.54GB (7.56GB free)|
|Process Argv|--no-sandbox --force-user-env --unity-launch --crash-reporter-id 392f9146-9e25-4213-ae87-df29ad8c5378|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
url-encode|fle|1.1.0
vscode-pull-request-github|Git|0.58.1
beautify|Hoo|1.5.0
ecdc|mit|1.8.0
isort|ms-|2022.8.0
python|ms-|2023.2.0
vscode-pylance|ms-|2023.2.20
notepadplusplus-keybindings|ms-|1.0.7
tyranosyntax|oru|0.15.0
markdown-pdf|yza|1.4.4

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
azure-dev_surveyone:30548225
vscccc:30610679
pyindex848cf:30577861
nodejswelcome1:30587005
282f8724:30602487
pyind779:30657576
f6dab269:30613381
pythonsymbol12cf:30657549
2i9eh265:30646982
vsctsb:30662444

```

</details>

**Comment by wise0704** [comment]
To add, it doesn't scroll all the way down to the input line.
It skips a whole page.

![capture2](https://user-images.githubusercontent.com/13545633/223231670-e22b4b18-be3c-42d0-b60f-93e1056e7eb9.gif)

**Comment by thatDudo** [comment]
It also only seems to happen on the second opening. On the first opening it is scrolled down correctly for some reason...

**Comment by brianhu-tw** [comment]
Same issue here.

> It also only seems to happen on the second opening. On the first opening it is scrolled down correctly for some reason...

It seems that it only works fine on the first terminal.

**Comment by brianhu-tw** [comment]
I am encountering the same issue. All terminals have the same issue.

https://user-images.githubusercontent.com/9028425/227915801-7d834de7-c078-4f7e-a210-28cc5edb4a27.mov

**Comment by wise0704** [comment]
> I am encountering the same issue. All terminals are affected by this problem. The issue arose after hiding and reopening the panel. As you can see in the video, the scroll bar becomes shorter after reopening the terminal.
> 
> Could it be that this only happens with ZSH?

Same issue with mine above. I'm using cmd, so the problem is not specific to a terminal type.

**Comment by Tyriar** [comment]
Related: https://github.com/microsoft/vscode/issues/176299
