### ISSUE TITLE
variable hover debug info incorrect

### ISSUE THREAD

**Issue by markchagers** [microsoft/vscode#174328]
Type: <b>Bug</b>

start debug session
create breakpoint on a line with object variables
trigger the breakpoint
hover over variable containing an object reference

The info displayed is not the object, but one of it's properties. It's unclear to me which property get 'chosen' in theis scenario, but it makes it sometimes impossible to see all properties of an object.

VS Code version: Code 1.75.1 (441438abd1ac652551dbe4d408dfcec8a499b8bf, 2023-02-08T21:34:59.000Z)
OS version: Darwin x64 22.2.0
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7500 CPU @ 3.40GHz (4 x 3400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (1.58GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (20)</summary>

Extension|Author (truncated)|Version
---|---|---
path-intellisense|chr|2.8.4
vscode-mac-color-picker|dae|1.1.0
vscode-eslint|dba|2.4.0
gitlens|eam|13.2.0
EditorConfig|Edi|0.16.4
prettier-vscode|esb|9.10.4
vscode-firefox-debug|fir|2.9.8
todo-tree|Gru|0.0.224
svg|joc|1.5.0
angular-essentials|joh|13.0.0
Angular2|joh|13.0.0
vscode-simple-icons|Lau|1.16.0
fluent-icons|mig|0.0.18
dotenv|mik|1.0.1
vscode-versionlens|pfl|1.5.0
sonarlint-vscode|Son|3.14.0
volar|Vue|1.0.24
vscode-typescript-vue-plugin|Vue|1.0.25
vscode-import-cost|wix|3.3.0
markdown-all-in-one|yzh|3.5.0

</details>

**Comment by leafsnow** [comment]
me too！！！！
![image](https://user-images.githubusercontent.com/6291246/218908538-e38470b5-b9eb-46c9-bf8d-a821a994f685.png)
![image](https://user-images.githubusercontent.com/6291246/218908646-ef09b557-480c-4475-bcd5-72b6c10ba931.png)

and in async function，this key show error info
![image](https://user-images.githubusercontent.com/6291246/218908752-5a602e43-7fd2-40f7-94be-2e7f065d8bd5.png)

**Comment by roblourens** [comment]
https://github.com/microsoft/vscode-js-debug/issues/1561
