### ISSUE TITLE
Editors opened from the menu bar should not open in preview mode

### ISSUE THREAD

**Issue by kieferrm** [Microsoft/vscode#17431]
Steps to Reproduce:
1. From menu... File / Preferences / Workplace Settings
2. From menu... Help / Release Notes
-> Settings are closed

Editors opened from the menu bar should not open in preview mode so that they stay open.

See also #17428.

**Comment by bpasero** [comment]
That is true and I think we used to open them pinned before but we no longer do. Moving to @sandy081, settings and keybindings I argue should all open pinned.
