### ISSUE TITLE
"Select a language" should be a command that can be invoked with the command palette

### ISSUE THREAD

**Issue by birgersp** [microsoft/vscode#174340]
When creating a new file, I have the option to "Select a language" for the file. AFAIK the only way for me to select a language at this stage, is to use my mouse to click the "Select a language" link (button) in the empty document. See screenshot:

![image](https://user-images.githubusercontent.com/5260237/218762709-338bd2af-7692-46c5-b031-c3cb739be827.png)

(How do I invoke this, except clicking it with my mouse?)

I want to be able to do this **without** using the mouse. If it was a command that I could execute from the palette, it would be fine. Then I could open the command palette and enter "select lang" or something and trigger the language selector:

![image](https://user-images.githubusercontent.com/5260237/218763371-262bd02c-e6d3-4a26-87c8-dfd78d569e38.png)

Please 🙏

**Comment by smbkr** [comment]
You can already do this, it's just called "Change language mode" not "Select language" in the command palette.

**Comment by birgersp** [comment]
Thank you dearly!
