### ISSUE TITLE
"Reload this window to activate the extension X" - wording

### ISSUE THREAD

**Issue by glittle** [Microsoft/vscode#17432]
- VSCode Version: Code 1.8.0 (38746938a4ab94f2f57d9e1309c51fd6fb37553d, 2016-12-13T17:45:32.595Z)
- OS Version: Windows_NT ia32 6.3.9600
- Extensions:

|Extension|Author|Version|
|---|---|---|
|Theme-Flat|gerane|0.0.2|
|intellij-idea-keybindings|k--kato|0.2.7|
|easy-less|mrcrowl|1.2.5|
|csharp|ms-vscode|1.5.3|
|vs-keybindings|ms-vscode|0.1.2|
|sass-indented|robinbentley|1.2.1|

---

Steps to Reproduce:

1.  Install more than one extension and/or uninstall one or more extensions.
2. Click the "reload" button
3. The popup confirmation asks to reload the window to activate/deactivate the extension that was just clicked. However, all other pending activations will also be done.

Should change the wording to indicate that all pending changes will be done.

**Comment by joaomoreno** [comment]
We could maybe say `Reload this window to activate all extensions.`

**Comment by sandy081** [comment]
Makes sense, but if there are some disabled extensions, is not this message misleading?

**Comment by joaomoreno** [comment]
`Reload this window to activate this extension (and possibly others)?` 😆

**Comment by glittle** [comment]
How about `Reload this window to apply pending changes`, or simply `Reload now?`

**Comment by sandy081** [comment]
Marking this as a dup as it is listed in UX improvement item #18354
