### ISSUE TITLE
Error renderer keeps appending output when there are no changes

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode#174393]
* Open VS Code insiders
* Open the following ipynb file in vscode
<details>
  <summary>ipynb</summary>
  
```json
{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 6,
   "metadata": {},
   "outputs": [
    {
     "ename": "NameError",
     "evalue":
	  "name 'ccc' is not defined",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mNameError\u001b[0m                                 Traceback (most recent call last)",
      "Cell \u001b[0;32mIn[6], line 1\u001b[0m\n\u001b[0;32m----> 1\u001b[0m ccc\n",
      "\u001b[0;31mNameError\u001b[0m: name 'ccc' is not defined"
     ]
    }
   ],
   "source": [
    "ccc"
   ]
  }
 ],
 "metadata": {
  "language_info": {
   "name": "python"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}

```
</details>

* Open the same notebook sideways (on the right) in a text editor
* Now set focus to the text editor (on the right) and hit the save key (CTRL+S)
* Watch how the error output in the notebook (on the left) gets duplicated

![Screenshot 2023-02-15 at 06 20 56](https://user-images.githubusercontent.com/1948812/218836252-fb611bd4-0cad-4478-b3ea-a2b5a2dabb24.png)

**Comment by rebornix** [comment]
The reproduce steps are very impressive 👍
