### ISSUE TITLE
Only auto-open walkthroughs for extensions a user choose to install

### ISSUE THREAD

**Issue by digitarald** [microsoft/vscode#174304]
Top extension packages right now trigger a storm of walkthroughs opening and fighting for attention, which doesn't help do user onboard but causes confusion.

How might we scope down whatever opens to the users intent?

If multiple extensions are competing for showing a walkthrough:

1. Only the walk-through for the extension that the user hit _install_ on is allowed to open.
2. For extension packs, only show walk-through when defined in the main package.

If each is deemed important, then the main walk-through could also link to the other walk-throughs in context.

cc @bhavyaus @luabud

**Comment by bhavyaus** [comment]
This is fixed.
We only open the walkthrough from the main package if we don't already have a walkthrough open. All additional walkthroughs are not opened.
