### ISSUE TITLE
Auto Save periodically does not seem to be working

### ISSUE THREAD

**Issue by JWess** [Microsoft/vscode#17430]
- VSCode Version: Code - Insiders 1.9.0-insider (c5df118575aebc2e28a4addd4d4a29b899a514c5, 2016-12-16T11:29:57.289Z)
- OS Version: Windows_NT ia32 6.3.9600
- Extensions:

|Extension|Author|Version|
|---|---|---|
|jshint|dbaeumer|0.10.15|
|vscode-jasmine-es5|deerawan|1.0.1|
|python|donjayamanne|0.3.18|
|auto-close-tag|formulahendry|0.3.5|
|vscode-auto-open-markdown-preview|hnw|0.0.3|
|beautify|HookyQR|0.4.0|
|docthis|joelday|0.3.4|
|markdown-shortcuts|mdickin|0.4.1|
|csharp|ms-vscode|1.2.1|
|guides|spywhere|0.5.1|
|gitblame|waderyan|1.3.0|

---

Steps to Reproduce:

I don't have any specific steps to reproduce, as I can't find any pattern as to when auto-save will/won't work. I have "files.autoSave": "onFocusChange" set in my config, as it has been for several months. Yesterday is the first time I ever noticed this not working. If I restart my editor, it seems to start working again, but eventually it breaks again several minutes later.

**Comment by bpasero** [comment]
@JWess there was indeed some changes in 1.9 around this feature, specifically the way it used to work in 1.8 and before is to save whenever focus changes inside the editor, that is it would even save when you clicked into the find widget of the editor. We found this a little bit too aggressive, so we changed it that it would save only if the entire editor area is left. Clicking into the find widget will no longer save the editor, but clicking anywhere outside the editor should.

Maybe you could find the pattern where it does not work for you and report back.

**Comment by JWess** [comment]
Ohhh, thanks for the explanation! Would it be possible to make it configurable so that one option saves when focus leaves the editor and one option saves when focus leaves the file? Personally, I prefer when focus leaves the file.

**Comment by bpasero** [comment]
@JWess can you explain your use case better? where do you "leave the file" and expect it to save?

**Comment by JWess** [comment]
Well, if I have two tab groups open (split screen), and I switch focus from one tab group to the other. Or, like you said, if I go to the find widget. Basically I liked that the saving happened frequently, because it triggered my project to build the new changes (we run a "watch" task that watches for changes to the project files).

**Comment by JWess** [comment]
Also, I thought both options were already supported: onFocusChange, onWindowChange ??

https://code.visualstudio.com/docs/editor/codebasics#_save-auto-save

**Comment by bpasero** [comment]
@JWess to be clear it should work when you move focus from one editor to another as long as focus moves out of the editor. 

Here is how it used to work in 1.8
* `onFocusChange`: saved when any other focusable thing gets focus even if this thing is within the editor (like the find widget)
* `onWindowChange`: saved when entire windows looses focus

Here is how it works in 1.9:
* `onFocusChange`: saved when any focusable thing gets focused that is visually outside of the editor that is dirty
* `onWindowChange`: saved when entire windows looses focus (unchanged from 1.8)

I think the 1.9 behaviour is more natural. People might not want the save to kick in when using the find widget because they are still in the middle of editing.

Have you thought about just enabling the auto save after delay?

**Comment by JWess** [comment]
I appreciate the explanation. I originally misunderstood and thought you were referring to the "Search Whole Solution" area (Ctrl + Shift + F), but you were referring to the (Ctrl + F) search, which I agree should not save the file. At any rate, I will continue to observe to see if I can figure out a pattern to mine not working... I just downloaded the latest (5 mins ago), and it still seems to not save sometimes when the editor loses focus....and when that happens, it doesn't even save when the whole window loses focus...nothing triggers a save besides a (Ctrl + S).

**Comment by bpasero** [comment]
Ok great, that means we can settle on the fact that what you see is an actual bug and might well be a regression from my changes.

When this bug happens, does it help to move focus into the editor and out to another editor in the same window?

**Comment by JWess** [comment]
Switching between files in the same tab group doesn't help, nor switching between tab groups.

**Comment by JWess** [comment]
Update (with 'onFocusChange' active):

If I make a change to 'File A' located in 'Tab Group X', then click on 'File B' in 'Tab Group Y', 'File A' remains unsaved. But, when I click back on any file in 'Tab Group X', 'File A' is immediately saved.

**Comment by bpasero** [comment]
I cannot reproduce that behaviour, see this video what I do:

![view-picker](https://cloud.githubusercontent.com/assets/900690/21339730/ba4a7064-c681-11e6-9c80-3ca500c57e74.gif)

Does it reproduce for you all the time in that setup?

**Comment by JWess** [comment]
It does not always reproduce. When I restart VSCode, it doesn't happen for a while.

![vscodeautosavedemo](https://cloud.githubusercontent.com/assets/8697891/21360471/0825350e-c6ae-11e6-802c-f4828b6672a3.gif)

**Comment by JWess** [comment]
I have just encountered a different bad behavior. This time, I have a "never-before-saved" file open at the same time. I have no idea if that is why, but that's the only thing I see that is different.

![autosavefailure](https://cloud.githubusercontent.com/assets/8697891/21401577/e61e1036-c782-11e6-9e91-35e0ec4e0354.gif)

**Comment by bpasero** [comment]
@JWess very hard to see whats going on in that gif. Btw I do not think any dirty state would make a difference, the way auto save works here is by relying on an event the editor emits whenever focus is lost. 

I wonder if maybe an extension could have an impact on the saving. Can you try to run VS Code without extensions? From the command line (NOT the integrated terminal in Code), execute: `code --disable-extensions` and try your steps again to see if it reproduces. If you see it is an issue with the extension, please file it against the extension repository itself.

**Comment by wulftone** [comment]
I'm experiencing the same thing.  How do I get enough info to inform you for a fix?

**Comment by alexandrudima** [comment]
@bpasero I wanted to verify, but was unsure how. Can you please extract some clear repro steps?

**Comment by bpasero** [comment]
Yeah, not much other than verifying that clicking somewhere outside of the editor should save the file if dirty.
