### ISSUE TITLE
Search with "Ignore Case" doesn't find results when search string has uppercase letters

### ISSUE THREAD

**Issue by Twoleeland** [microsoft/vscode#174452]
Type: <b>Bug</b>

Search with "Ignore Case" doesn't find results when search string has uppercase letters. See attached screenshots:

<img width="313" alt="2023-02-15--12h39m42s--w626-h305--Welcome_-_VSCodeTest_-_Visual_Studio_Code" src="https://user-images.githubusercontent.com/1656150/219020334-291e6c3d-95f7-402a-8502-cfa92c457c12.png">

<img width="315" alt="2023-02-15--12h39m07s--w630-h601--Welcome_-_VSCodeTest_-_Visual_Studio_Code" src="https://user-images.githubusercontent.com/1656150/219020352-c734ec89-69cf-4841-858c-da26ac624a1f.png">

VS Code version: Code 1.75.1 (441438abd1ac652551dbe4d408dfcec8a499b8bf, 2023-02-08T21:32:34.589Z)
OS version: Windows_NT x64 10.0.19045
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-1620 0 @ 3.60GHz (8 x 3591)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.93GB (17.88GB free)|
|Process Argv|D:\\Temp\\VSCodeTest --crash-reporter-id 0b6b7092-1f42-4618-a950-4c04b77b794c|
|Screen Reader|no|
|VM|25%|
</details><details><summary>Extensions (102)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|3.0.2
Bookmarks|ale|13.3.1
vscode-sqlite|ale|0.14.1
html-class-suggestions|And|1.1.1
SecurityIntelliSense|azs|0.8.0
docs-view|bie|0.0.11
markdown-mermaid|bie|1.17.4
vscode-tailwindcss|bra|0.9.7
vscode-markdownlint|Dav|0.49.0
jshint|dba|0.11.0
vscode-eslint|dba|2.4.0
vscode-faker|dee|2.0.0
githistory|don|0.6.19
xml|Dot|2.5.1
gitlens|eam|13.2.0
vscode-html-css|ecm|1.13.1
prettier-vscode|esb|9.10.4
comment-anchors|Exo|1.10.3
vscode-solution-explorer|fer|0.7.5
vscode-firefox-debug|fir|2.9.8
cshtml-tm|fir|1.0.0
code-runner|for|0.12.0
go|gol|0.37.1
todo-tree|Gru|0.0.224
textusm|har|0.11.1
vscode-drawio|hed|1.6.6
rest-client|hum|0.25.1
prettier-sql-vscode|inf|1.5.0
plantuml|jeb|2.17.5
vscode-gutter-preview|kis|0.30.0
vscode-dbml|mat|0.3.5
vscode-language-babel|mgm|0.0.36
git-graph|mhu|1.30.0
vscode-azureresourcegroups|ms-|0.5.6
vscode-devskim|MS-|0.7.102
data-access-migration-toolkit|ms-|0.3.3
csharp|ms-|1.25.4
dotnet-interactive-vscode|ms-|1.0.4102020
data-workspace-vscode|ms-|0.4.0
mssql|ms-|1.17.1
sql-bindings-vscode|ms-|0.3.0
sql-database-projects-vscode|ms-|0.21.0
playwright|ms-|1.0.7
gather|ms-|2022.3.2
isort|ms-|2022.8.0
python|ms-|2023.2.0
vscode-pylance|ms-|2023.2.20
sarif-viewer|MS-|3.3.5
jupyter|ms-|2023.1.2010391206
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.14
vscode-jupyter-cell-tags|ms-|0.1.6
vscode-jupyter-slideshow|ms-|0.1.5
remote-containers|ms-|0.275.1
remote-ssh|ms-|0.96.0
remote-ssh-edit|ms-|0.84.0
remote-wsl|ms-|0.75.2
azure-account|ms-|0.11.3
hexeditor|ms-|1.9.11
live-server|ms-|0.4.5
powershell|ms-|2023.1.0
remote-explorer|ms-|0.2.0
remote-server|ms-|1.0.0
vs-keybindings|ms-|0.2.1
vscode-js-profile-flame|ms-|1.0.5
vscode-markdown-notebook|ms-|0.0.26
vsliveshare|ms-|1.0.5828
vscode-react-native|msj|1.10.0
vscode-sanddance|msr|4.1.0
abracadabra|nic|6.19.0
vscode-drawio-plugin-mermaid|nop|0.1.5
indent-rainbow|ode|8.3.1
material-icon-theme|PKi|4.24.0
vscode-powerquery|Pow|0.1.52
vscode-css-peek|pra|4.2.0
prettyxml|Pra|3.0.1
inline-html|pus|0.3.5
sql-transformer|Qua|0.3.17
vscode-xml|red|0.24.0
vscode-yaml|red|1.11.0
LiveServer|rit|5.7.9
rust-analyzer|rus|0.3.1402
sql-snippets|sad|0.0.4
runme|sta|0.6.5
code-spell-checker|str|2.16.0
code-spell-checker-french|str|0.2.6
code-spell-checker-german|str|2.1.2
code-spell-checker-italian|str|1.0.0
vscode-styled-components|sty|1.7.5
msbuild-project-tools|tin|0.4.9
vscode-status-bar-format-toggle|tom|3.1.1
vscode-mermaid-editor|tom|0.17.1
intellicode-api-usage-examples|Vis|0.2.7
vscodeintellicode|Vis|1.2.30
vscodeintellicode-completions|Vis|1.0.21
vscode-conventional-commits|viv|1.25.0
vscode-icons|vsc|12.2.0
volar|Vue|1.0.24
WebTemplateStudio-dev-nightly|WAS|0.7.2117301
vscode-todo-highlight|way|1.0.5
vscode-import-cost|wix|3.3.0
JavaScriptSnippets|xab|1.8.0

(3 theme extensions excluded)

</details>

**Comment by andreamah** [comment]
Do you have the `search.smartCase` setting enabled?

**Comment by Twoleeland** [comment]
Indeed! 😅 I forgot about this setting when I activated it. My fault! 🙈😁
But it would be helpful, if some info could be displayed in the search panel/tab that this setting is enabled, like you do, when exclusion filters are disabled/enabled. Maybe with a tri-state "Aa"-button instead of the dual-state button? Just an idea... 😉

Anyway, thanks for help and have a nice weekend! 😊
