### ISSUE TITLE
Can't make a clean install of VS code

### ISSUE THREAD

**Issue by Juanc179** [microsoft/vscode#174490]
Type: <b>Feature Request</b>

There is no way of uninstalling the program that clears all files and configs. I want to make a clean install and the program automatically opens just as i left it. Even uninstalling it from its own client doesn't work. 

VS Code version: Code 1.75.1 (441438abd1ac652551dbe4d408dfcec8a499b8bf, 2023-02-08T21:32:34.589Z)
OS version: Windows_NT x64 10.0.22000
Modes:
Sandboxed: Yes

**Comment by joaomoreno** [comment]
https://code.visualstudio.com/docs/setup/uninstall#_clean-uninstall
