### ISSUE TITLE
Report Issue for Remote extensions doesn't work

### ISSUE THREAD

**Issue by sbatten** [microsoft/vscode#174404]
I ran across this while trying to create report issue markdown links for notebooks. Clicking the report issue item in the help section of the remote explorer does nothing and I believe its because of improper arguments format for the report issue command here: https://github.com/microsoft/vscode/blob/bb920e844b66ab77ae502f648bf1577e931b055f/src/vs/workbench/contrib/remote/browser/remote.ts#L411

The correct argument is an object with an extensionId property.

**Comment by alexr00** [comment]
@sbatten this works fine for me on desktop.  Were you on web? It looks like that command is implemented differently for web. 

@bpasero do you own issue.contribution.ts and issue.web.contribution.ts?

**Comment by alexr00** [comment]
Looks like @TylerLeonhardt might own this.
These are the parts that I would expect to be the same:
https://github.com/microsoft/vscode/blob/550fdeb89906b1671c0a5a8fbbb729c46f7c46a1/src/vs/workbench/contrib/issue/electron-sandbox/issue.contribution.ts#L23-L29 
https://github.com/microsoft/vscode/blob/550fdeb89906b1671c0a5a8fbbb729c46f7c46a1/src/vs/workbench/contrib/issue/browser/issue.web.contribution.ts#L26-L37

**Comment by TylerLeonhardt** [comment]
It was me all along 😱 I will change Web to be more like Desktop.

**Comment by TylerLeonhardt** [comment]
I just debugged this and my issue reporter command is never fired. I think is an issue somewhere in this:
https://github.com/microsoft/vscode/blob/7570fadcce237041ff737fd334f30a8c0a918d95/src/vs/workbench/contrib/remote/browser/remote.ts#L317-L370

The repro steps:
* don't have a remote workspace open or any workspace open for that matter
* open the remote explorer -> help and feedback -> Report Issue

nothing happens.

**Comment by alexr00** [comment]
To verify:
- Install at least 2 remote extension
- Reload, and make sure you don't have a remote or virtual workspace open
- Click "Report Issue" from the Remote "Help & Feedback"
- Verify that you get a quick pick.

**Comment by alexr00** [comment]
Sorry for the false alarm there @TylerLeonhardt !

**Comment by TylerLeonhardt** [comment]
![Image](https://user-images.githubusercontent.com/2644648/227001349-12338fa1-f640-4063-acb8-f5bb087363ee.png)

In the Remote Explorer at the bottom.
