### ISSUE TITLE
Open filesystem provider urls from the command line

### ISSUE THREAD

**Issue by arcanis** [microsoft/vscode#174459]
Consider the [ZipFS extension](https://marketplace.visualstudio.com/items?itemName=arcanis.vscode-zipfs), which allows you to open files from their zip files through the [`registerFilesystemProvider` call](https://github.com/yarnpkg/berry/blob/master/packages/vscode-zipfs/sources/index.ts#L45-L47). Running `code zip:/absolute/path/to/file.zip/README.txt` doesn't work today (it opens an empty page).

The CLI (and perhaps the [`vscode://` urls](https://github.com/microsoft/vscode/issues/4883) too) should be able to detect the presence of a non-standard filesystem protocol, and wait for the extension to have loaded before trying to open the file.

**Comment by jrieken** [comment]
@aeschli We do support this, right?

**Comment by arcanis** [comment]
What's supposed to be the syntax? Assuming the ZipFS extension is installed, and the following setup:

```
cd $(mktemp -d)
yarn init -2
yarn add lodash
```

The following two commands open empty files:

```
code $(pwd)/.yarn/cache/lodash-*.zip/node_modules/lodash/package.json
```

```
code zip:$(pwd)/.yarn/cache/lodash-*.zip/node_modules/lodash/package.json
```

Despite:

```
$ unzip -l .yarn/cache/lodash-*.zip | grep package
      578  06-22-1984 21:50   node_modules/lodash/package.json
```

**Comment by aeschli** [comment]
Yes, this is supported. You have to use the `--file-uri` argument:
`code-insiders --file-uri zip:///home/martin/Downloads/VSCode-win32-x64-1.76.0.zip/bin/code`

for folders it's `--folder-uri`
