### ISSUE TITLE
how should I do to pin the position of "the open file tab"? 

### ISSUE THREAD

**Issue by RaySunWHUT** [microsoft/vscode#174424]
Does this issue occur when all extensions are disabled?: Yes/No

Version: 1.75.1 (Universal)
Commit: 441438abd1ac652551dbe4d408dfcec8a499b8bf
Date: 2023-02-08T21:34:59.000Z (6 days ago)
Electron: 19.1.9
Chromium: 102.0.5005.194
Node.js: 16.14.2
V8: 10.2.154.23-electron.0
OS: Darwin x64 22.1.0
Sandboxed: No

Steps to Reproduce:
the steps to Reproduce is very easy.
1. open 2 or 3 files at the same time.
2. as normal, they will show as a default order. But if I click one of the files, the clicked file will jump to the first place on the tab list.
3. my question is how should I do to keep the open file tab position ? 
4. the ideal result is every open file will forever stay on the position where it showed.

**If I click the file named "luogu.cpp" as show below the figure, **
<img width="924" alt="image" src="https://user-images.githubusercontent.com/42628912/218928016-069d818c-3cde-466d-866a-78c15b4cd9ea.png">

the file named "luogu.cpp" doesn't stay its original position, it jump to the first place!!! And the file order is changed.
<img width="866" alt="image" src="https://user-images.githubusercontent.com/42628912/218928521-9c468b3d-f75d-4b90-a81f-bb698d131ed3.png">

I want to the open file stay on the position where it showed first time, rather than jump to the first place when I click it.

looking forward to your reply. thanks.

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by gjsjohnmurray** [comment]
Maybe also use the Start Extension Bisect command on your 1.75.1 to investigate whether the problem is being caused by an extension you have installed.

**Comment by jahuarcristian** [comment]
Clave ..para trasfer

**Comment by RaySunWHUT** [comment]
I'm so sorry to bother you with this problem without checking the installed extension list. The problem has been located, this problem occurs because I casual installed a terrible extension named "**Tab Cycle**".
I have solved this problem. Thanks for the tips. 
I'm sorry to take up your valuable time. 
thanks.
