### ISSUE TITLE
Visual Studio Code unable to launch default browser on Linux Mint Vera.

### ISSUE THREAD

**Issue by Goldflipflop** [microsoft/vscode#174468]
Type: <b>Bug</b>

Install  Visual Studio on Linux Mint Vera.
Select Help/Documentation.  
 Then   Message:  "failed to execute default Web Browser" appears.    
Detailed message:
  Failed to execute child process "/usr/share/bash-completion/completion/chrome" (Permission denied).

ls -l   /usr/share/bash-completion/completion/chrome  shows
lrwxrwxrwx 1 root root 16 Dec 31 09:36 /usr/share/bash-completion/completions/chrome -> chromium-browser

Workaround is  to change the symlink target to /usr/bin/chromium

VS Code version: Code 1.75.1 (441438abd1ac652551dbe4d408dfcec8a499b8bf, 2023-02-08T21:35:30.018Z)
OS version: Linux x64 5.15.0-60-generic
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Pentium(R) Dual-Core CPU       T4300  @ 2.10GHz (2 x 2095)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: disabled_off<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|0, 0, 0|
|Memory (System)|3.79GB (1.55GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|xfce|
|XDG_CURRENT_DESKTOP|XFCE|
|XDG_SESSION_DESKTOP|xfce|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
gitlens|eam|13.2.0
csharp|ms-|1.25.4

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
azure-dev_surveyone:30548225
pyindex848:30662994
nodejswelcome1cf:30587006
3biah626:30602489
pyind779:30662992
89544117:30613380
pythonsymbol12:30657548
vsccsb:30662443

```

</details>

**Comment by deepak1556** [comment]
Closing as out of scope, the runtime invokes `xdg-open` to open the default browser and it is unlikely for us to configure it.
