### ISSUE TITLE
TypeScript: "Go to definition" stopped working after the latest update

### ISSUE THREAD

**Issue by crisz** [microsoft/vscode#174449]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.75.1
- OS Version: MacOS Montrey 12.6 (21G115)

Steps to Reproduce:

1. Start a TypeScript project
2. Configure a tsconfig and install a local version of TypeScript (I'm using the 2.6.2)
3. Click on `{}` in the bottom-right corner, then select the TypeScript working area version (the bug is not present with the TypeScript vscode version)
4. Right click a method call (or any TypeScript object) and select "go to the definition"
5. (alternative) `CMD + click` on a method call

However, the IntelliSense results correctly working as it completes the method names, and leaving the mouse over a method it shows me the signature. But "go to definition" doesn't work and if I hover the method while pressing `CMD` the method name is not underlined.

<img width="633" alt="Schermata 2023-02-15 alle 11 34 49" src="https://user-images.githubusercontent.com/8181922/219003776-1d153230-065a-4c04-8e04-d497b9b3aae3.png">

<img width="396" alt="Schermata 2023-02-15 alle 11 34 02" src="https://user-images.githubusercontent.com/8181922/219003866-24b547ae-e8ca-4013-9766-b06f7a27143c.png">

**Comment by mjbvz** [comment]
Closing as that TS version is very old and no longer being actively supported for our tooling

It sounds like everything is working with VS Code's TS version, so you either can use that for editor tooling or update your workspace version of TS to a more modern version
