### ISSUE TITLE
无法安装插件

### ISSUE THREAD

**Issue by koaqiu** [microsoft/vscode#174478]
![image](https://user-images.githubusercontent.com/542287/219106440-c752c2fc-8bdd-4043-92aa-52d2e41b1533.png)

Version: 1.75.1 (user setup)
Commit: 441438abd1ac652551dbe4d408dfcec8a499b8bf
Date: 2023-02-08T21:32:34.589Z
Electron: 19.1.9
Chromium: 102.0.5005.194
Node.js: 16.14.2
V8: 10.2.154.23-electron.0
OS: Windows_NT x64 10.0.22621
Sandboxed: Yes

**Comment by sandy081** [comment]
Looks like you have network issues connecting to the internet. Please fix them to resolve this issue.
