### ISSUE TITLE
Can't turn on setting sync

### ISSUE THREAD

**Issue by drafting-dreams** [microsoft/vscode#174479]
Type: <b>Bug</b>

Newly installed vscode can not turn on Settings Sync. (No accounts requested yet)
Error while turning on Settings Sync. No authentication providers are available.

VS Code version: Code 1.75.1 (441438abd1ac652551dbe4d408dfcec8a499b8bf, 2023-02-08T21:32:34.589Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 9 5900HX with Radeon Graphics         (16 x 3294)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.86GB (25.05GB free)|
|Process Argv|--crash-reporter-id f86230a1-001f-4543-b79f-3d0031a7dc6f|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vscaac:30438847
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
pynewext54:30660299
azure-dev_surveyone:30548225
pyindex848:30662994
nodejswelcome1:30587005
282f8724:30602487
pyind779cf:30662993
f6dab269:30613381
pythonsymbol12:30657548
vsccsb:30662443

```

</details>

**Comment by drafting-dreams** [comment]
My issue is similar to https://github.com/microsoft/vscode/issues/151434 

I googled around, only found this happening on linux distros, so no solution for Windows.

**Comment by sandy081** [comment]
Can you please check if the following extensions are enabled? Go to Extensions view and look for

- `@builtin github auth`
- `@builtin microsoft account`

**Comment by drafting-dreams** [comment]
Nope, it's just installed, very clean. BTW, I found I couldn't even install extensions.

**Comment by sandy081** [comment]
/duplicate

https://github.com/microsoft/vscode/issues/174046

To recover, can you please do following?

- F1 > Open Extensions Folder...
- Delete `extensions.json` file

**Comment by drafting-dreams** [comment]
It's working now. Thank you very much! All fixed. But I still wonder the root cause what could be the possible reason that made this happened?

**Comment by sandy081** [comment]
Do not know why you have an empty extensions.json file. May be some extension has created this file.

**Comment by drafting-dreams** [comment]
Here's the thing. I installed vscode on windows. But the firt time I opened it was in WSL. I'm thinking maybe this is related.

**Comment by sandy081** [comment]
Hmm interesting. Are you able to reproduce so that you end up having empty extensions.json file?

**Comment by drafting-dreams** [comment]
Do I just uninstall vscode and install it again, and repeat the steps? Any other files I need to clean before I reproduce?

**Comment by sandy081** [comment]
Delete the extensions folder if you do not have any extensions or if you can install them again.

**Comment by drafting-dreams** [comment]
I deleted the `code` folder in the `AppData\Roaming`, deleted `.vscode` folder in my own user file deleted `.vscode-server` folder in WSL.

The vscode WSL server download is not triggered, which it should be when I opened the vscode for the first time in WSL. 

And yes, it could be reproduced. (I also didn't close the wizard window with the "finish" button when installation was completed. Though I think this doesn't matter, but comment here in in case it does.)

**Comment by sandy081** [comment]
Great. So it reproduces even without connecting to WSL? After installation have you just opened VS Code empty window?

**Comment by drafting-dreams** [comment]
OK, here's the step.

1. Install vscode on windows without opening it.
2. Open WSL command line (Ubuntu 22.04 LTS)
3. Go to a random project, in my case, it's a newly created nestjs project with the nest CLI
4. run `code .`

**Comment by drafting-dreams** [comment]
> Great. So it reproduces even without connecting to WSL? After installation have you just opened VS Code empty window?

So it's not an empty window. Though I can see the files in the folder tree, but without a WSL server? No it's not connected to WSL.

**Comment by sandy081** [comment]
Great. If you are able to reproduce, can you please share following log when this happens

- F1 > Open View... > Window
- F1 > Open View... > Shared

**Comment by drafting-dreams** [comment]
Yesterday I already fix it again. So I had to uninstall it again. However I couldn't reproduce it this time.

**Comment by sandy081** [comment]
@drafting-dreams Thanks for sharing lot of information. I filed a separate issue - https://github.com/microsoft/vscode/issues/174695 - that creates an empty extensions.json file.
