### ISSUE TITLE
Cannot maximize terminal panel

### ISSUE THREAD

**Issue by SetTrend** [microsoft/vscode#174411]
Type: <b>Bug</b>

With the advent of the latest VS Code version, the toolbar icon for maximizing the terminal window isn't available anymore:

![No Terminal Maximize Toolbar Button](https://user-images.githubusercontent.com/9283914/218891353-fc05beb3-a25d-48a6-b0d7-9c2a5e3dc93d.png)

VS Code version: Code 1.75.1 (441438abd1ac652551dbe4d408dfcec8a499b8bf, 2023-02-08T21:32:34.589Z)
OS version: Windows_NT x64 10.0.19044
Modes:
Sandboxed: No

<details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-language-pack-de|MS-|1.75.2023020809
remote-containers|ms-|0.275.1
remote-ssh|ms-|0.96.0
remote-ssh-edit|ms-|0.84.0
remote-wsl|ms-|0.75.2
vscode-remote-extensionpack|ms-|0.23.0
remote-explorer|ms-|0.2.0

</details>

**Comment by gjsjohnmurray** [comment]
What is your "Align Panel" setting?

![image](https://user-images.githubusercontent.com/6726799/218915819-e79b2e66-a3e4-44b0-b368-f553702b48b4.png)

Maximizing is only available when you have selected "Center" alignment.

**Comment by SetTrend** [comment]
Thanks, John, for enlightening me!

This change of behaviour doesn't seem documented. Neither Release Notes nor VS Code documentation provide this information.

May I humbly suggest to improve usability by either …

- instead of hiding the icon (leaving the user uninformed and clueless) disable it and provide a corresponding tool-tip to the icon, explaining why the icon is disabled.

- keep the icon visiable and enabled, and switch to "center" layout when activated.

**Comment by Tyriar** [comment]
There was no change in behavior, it was always like this with center panel alignment. cc @sbatten
