### ISSUE TITLE
Setting Sync Requiring Repeated Sign In

### ISSUE THREAD

**Issue by ErisFletcher** [microsoft/vscode#174425]
Type: <b>Bug</b>

Over the last few weeks, vscode an multiple devices has kept forcing me to sign in to my microsoft account to sync my settings over and over again. Now, everytime I reload it requires my to sign in again.

VS Code version: Code 1.75.1 (441438abd1ac652551dbe4d408dfcec8a499b8bf, 2023-02-08T21:32:34.589Z)
OS version: Windows_NT x64 10.0.19045
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10700F CPU @ 2.90GHz (16 x 2904)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.93GB (2.31GB free)|
|Process Argv|--crash-reporter-id 91c1b5af-9e16-4c2b-948a-a9766f0682f3|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (23)</summary>

Extension|Author (truncated)|Version
---|---|---
doxdocgen|csc|1.4.0
vscode-html-css|ecm|1.13.1
better-cpp-syntax|jef|1.17.2
cmake-language-support-vscode|jos|0.0.9
vscode-docker|ms-|1.23.3
csharp|ms-|1.25.4
vscode-dotnet-runtime|ms-|1.6.0
isort|ms-|2022.8.0
python|ms-|2023.2.0
vscode-pylance|ms-|2023.2.20
remote-containers|ms-|0.275.1
remote-ssh|ms-|0.96.0
remote-ssh-edit|ms-|0.84.0
remote-wsl|ms-|0.75.2
cmake-tools|ms-|1.13.45
cpptools|ms-|1.14.3
cpptools-extension-pack|ms-|1.3.0
remote-explorer|ms-|0.2.0
markdown-preview-enhanced|shd|0.6.7
vscode-pets|ton|1.22.0
cmake|twx|0.0.17
vscode-icons|vsc|12.2.0
material-theme|zhu|3.15.6

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscorecescf:30445987
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vscaat:30438848
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
azure-dev_surveyone:30548225
vsccc:30610678
pyindex848:30662994
nodejswelcome1cf:30587006
282f8724:30602487
pyind779cf:30662993
89544117:30613380
pythonsymbol12:30657548
2i9eh265:30646982

```

</details>

**Comment by M1Screw** [comment]
Same problem here on Windows 11 x86_64.

Version: 1.75.1 (system setup)
Commit: 441438abd1ac652551dbe4d408dfcec8a499b8bf
Date: 2023-02-08T21:32:34.589Z
Electron: 19.1.9
Chromium: 102.0.5005.194
Node.js: 16.14.2
V8: 10.2.154.23-electron.0
OS: Windows_NT x64 10.0.22621
Sandboxed: No

**Comment by NullList** [comment]
Same issue here, but solved. 
Following Tyler's recommendation, I removed all credentials related to VS Code in Windows Credential Manager, and that resolved the issue. Btw, the Credential Manager is indeed full of invalid credentials.

**Comment by ErisFletcher** [comment]
> Likely a duplicate of [#130893 (comment)](https://github.com/microsoft/vscode/issues/130893#issuecomment-1432203847) can you confirm if your Windows Credential Manager is full of stuff?

Yeah it was, I cleared out all of Microsoft related entries and it's fixed.

**Comment by ErisFletcher** [comment]
> Same issue here, but solved. Following Tyler's recommendation, I removed all credentials related to VS Code in Windows Credential Manager, and that resolved the issue. Btw, the Credential Manager is indeed full of invalid credentials.

Yeah I just removed all of the Microsoft entries in Credential Manager and it's fixed now.
