### ISSUE TITLE
SQL Linter

### ISSUE THREAD

**Issue by aaronsteers** [Microsoft/vscode#17441]
- VSCode Version: feature request (future)
- OS Version: n/a

Steps to Reproduce:

1. Open a valid .SQL file
2. No linting or hinting appears for syntax errors or formatting issues

Full request details:

I'd like to have a custom linter and formatter for the SQL language - similar to what is available for the python language via plugin support. I found sample code for a simple formatter [here](https://code.visualstudio.com/blogs/2016/11/15/formatters-best-practices), but the approach has two limitations: (1) the editing is somewhat "brute force" and does not use any standard grammar, and (2) there is no way in that approach to surface linting tips or syntax issues via underlining ("squigglies").

Is support for SQL coming in the near future, and/or are there any frameworks that could be used to apply grammars/rules without rewriting the core parsing/linting engine from scratch? I'm willing and able to contribute code, but I couldn't find any sample linting projects in the docs and it seems prohibitively error prone and time consuming to completely build this functionality from scratch.

**Comment by Spown** [comment]
have you searched extensions? If you did and found nothing you probably should set a bounty or DIY...

**Comment by kieferrm** [comment]
Pls see: https://marketplace.visualstudio.com/search?term=SQL&target=VSCode&sortBy=Relevance
