### ISSUE TITLE
Explorer hover should use same font size

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#174498]
The hover uses a smaller font. If we use the same font size, the whole thing could be nicely pixel aligned.

![Recording 2023-02-15 at 21 09 16](https://user-images.githubusercontent.com/22350/219141695-07660ed7-8f61-413c-884f-930aa7252011.gif)

**Comment by bpasero** [comment]
The hover does not go beyond the element anymore:

![image](https://user-images.githubusercontent.com/900690/220654100-40dce5a9-9f7c-43a9-89ea-ccbd67af6709.png)
