### ISSUE TITLE
After VSCode update: Interactive Window "Run selection/line in Interactive Window" stopped working

### ISSUE THREAD

**Issue by jahangirli** [microsoft/vscode#174426]
The command "Shift + Enter" just stopped working in full all of a sudden. It runs for a **single line** selected, but not for **multiple**. I cannot find why.

I face the same problem as [VS Code "Run selection/line in Python interactive window" not working at all](https://stackoverflow.com/q/59678010/14976775), yet using Bisect to disable and detect the reasons through extensions didn't help. For me the problem started after VScode itself was updated yesterday.

VS Code version: 1.75.1 
Python version: 3.9.13 
Python VS Code extension: 2023.2.0

It is just time consuming to copy and paste the same code in the interactive code to run it. Any ideas how I can fix it?

**Comment by amunger** [comment]
I can't seem to repro this with any combination of core/extension versions.

Can you check you keybindings to make sure jupyter.execSelectionInteractive is still bound correctly?
Do you see any errors in the dev tools when trying to run that command? (developer: toggle developer tools)
Does running the command directly through the palette work? (Jupyter: Run Selection/Line in Interactive Window)

**Comment by amunger** [comment]
Also make sure the `jupyter.sendSelectionToInteractiveWindow` setting is true.
it might be `jupyter.interactiveWindow.textEditor.executeSelection` if you're using pre-release

**Comment by jahangirli** [comment]
All the pre-requisites were satisfied. Just looking into the dev tools I recognized the problem. I had for whatever reason a package installed `googleapis_common_protos` which was blocking the implementation. After uninstalling that package, the problem is resolved. 

Now I can run again a selection in interactive Jupyter window. Thanks a lot!
