### ISSUE TITLE
macOS dock: cannot distinguish projects with the same name.

### ISSUE THREAD

**Issue by calidion** [Microsoft/vscode#17449]
- VSCode Version: Code 1.8.0 (38746938a4ab94f2f57d9e1309c51fd6fb37553d, 2016-12-13T17:38:28.425Z)
- OS Version: Darwin x64 16.1.0
- Extensions:

|Extension|Author|Version|
|---|---|---|
|tslint|eg2|0.7.1|
|vscode-icons|robertohuertasm|4.1.0|

---

Steps to Reproduce:

1.  have two projects located in abcd/proj and  dcba/proj
2. click the vscode button on mac dock, only one proj will be shown.

**Comment by kieferrm** [comment]
@calidion can you pls provide a screenshot? I'm guessing you talk about the macOS menu that pops up when you long press an icon in the dock.

**Comment by calidion** [comment]
@kieferrm yes.

**Comment by kieferrm** [comment]
@bpasero is that electron or us?

**Comment by bpasero** [comment]
Electron, and I would even say native behaviour. We use the API in https://github.com/electron/electron/blob/master/docs/api/app.md#appaddrecentdocumentpath-macos-windows

**Comment by bpasero** [comment]
@calidion can you share a screenshot of what you mean?
