### ISSUE TITLE
bash script syntax highlighting broken after `#` inside `if`

### ISSUE THREAD

**Issue by Yelmond** [microsoft/vscode#174415]
Type: <b>Bug</b>

Bash script syntax highlighting broken for `if` statement containing `#` inside the condition statement (`#` wrongly treated like the start of a comment).
![image](https://user-images.githubusercontent.com/178878/218906382-bd59ef7c-8213-4631-a112-5f65fb6f18d0.png)

VS Code version: Code 1.75.1 (441438abd1ac652551dbe4d408dfcec8a499b8bf, 2023-02-08T21:32:34.589Z)
OS version: Windows_NT x64 10.0.19045
Modes:
Sandboxed: No

<details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
phpserver|bra|3.0.2
gitlens|eam|13.2.0
cmake-language-support-vscode|jos|0.0.9
vscode-dotnet-runtime|ms-|1.6.0
isort|ms-|2022.8.0
python|ms-|2023.2.0
vscode-pylance|ms-|2023.2.20
shader|sle|1.1.5
cmake|twx|0.0.17
php-debug|xde|1.31.1

</details>

**Comment by alexr00** [comment]
This does not reproduce in VS Code insiders, where we're using a new shell script grammar.
