### ISSUE TITLE
[Search settings] F3 editor search should be disabled

### ISSUE THREAD

**Issue by hun1ahpu** [Microsoft/vscode#17458]
- VSCode Version:1.8.0
- OS Version:Windows 10

Steps to Reproduce:

1. Open Code default settings file settings.json
2. Try to search for something in 'Search default settings' textbox
3. Click F3

Expected: Editor search should not open as it becomes confusing to have 2 different searches at the same time.

![settingseditortwosearches](https://cloud.githubusercontent.com/assets/4397796/21286824/db57dcda-c45e-11e6-8d7f-1e82c22d1fa2.gif)

**Comment by sandy081** [comment]
Agreed. It was disabled in the beginning but got broke in between.
