### ISSUE TITLE
"editor.referenceInfos" setting marked as "Unknown configuration setting"

### ISSUE THREAD

**Issue by nick-korsakov** [Microsoft/vscode#17452]
- VSCode Version: 1.8.0
- OS Version: Windows 10 x86-64

Steps to Reproduce:

1. Open `settings.json`.
2. Place next option inside it.
```json
"editor.referenceInfos": false
```
3. Save `settings.json`.

Actual Results:
- It will be squiggled with the tooltip "Unknown configuration setting".
![referenceinfos](https://cloud.githubusercontent.com/assets/15720243/21285596/0ea1b8ce-c44e-11e6-8ea1-411a82381011.gif)

Expected Results:
- No squiggles and tooltip have to be shown.
- `editor.referenceInfos` setting should be known.

**Comment by sandy081** [comment]
`editor.referenceInfos` is deprecated and is replaced by `editor.codeLens` and hence warnings are shown. Please use `editor.codeLens`.
