### ISSUE TITLE
Warns that the private variables in the dart file are not in use even if they are used

### ISSUE THREAD

**Issue by SerdarYildiz06** [microsoft/vscode#174593]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 
- OS Version: 

Steps to Reproduce:

1. 
2.

**Comment by SerdarYildiz06** [comment]
Although I use the _getChildModel and loading variables in the getChild function, it warns that these variables are not in use.

<img width="698" alt="Screenshot 2023-02-16 at 19 42 12" src="https://user-images.githubusercontent.com/72278145/219430904-3ca032bf-9977-41d8-9f5f-862be1c07e47.png">

**Comment by roblourens** [comment]
This would come from the dart extension, please file an issue on their repo
