### ISSUE TITLE
WatchingProblemCollector - Problem matcher memory leak

### ISSUE THREAD

**Issue by zachhardesty7** [microsoft/vscode#174511]
Type: <b>Performance Issue</b>

## VSCode `WatchingProblemCollector` memory leak

[Source code for the class with the issue](https://github.com/microsoft/vscode/blob/main/src/vs/workbench/contrib/tasks/common/problemCollectors.ts#L404)

### Explanation (from what I can tell)
Every time `this.modelService.onModelRemoved` is called,
https://github.com/microsoft/vscode/blob/dc619de8d9efdabd781fc5658d0051813c347055/src/vs/workbench/contrib/tasks/common/problemCollectors.ts#L435
every line in the terminal is processed.
https://github.com/microsoft/vscode/blob/dc619de8d9efdabd781fc5658d0051813c347055/src/vs/workbench/contrib/tasks/common/problemCollectors.ts#L446-L448
Since there are no problem matches, `this.tryBegin` **never** wipes the lines stored in `this.lines` to `[]`.
https://github.com/microsoft/vscode/blob/dc619de8d9efdabd781fc5658d0051813c347055/src/vs/workbench/contrib/tasks/common/problemCollectors.ts#L506
Then `this.tryBegin` & `this.tryFinish` return false and we **don't** abort.
https://github.com/microsoft/vscode/blob/dc619de8d9efdabd781fc5658d0051813c347055/src/vs/workbench/contrib/tasks/common/problemCollectors.ts#L468
Then, one-by-one, each line is pushed to `this.lines`, despite already existing in it.
https://github.com/microsoft/vscode/blob/dc619de8d9efdabd781fc5658d0051813c347055/src/vs/workbench/contrib/tasks/common/problemCollectors.ts#L471
The amount of memory used by these arrays grows exponentially until `this.modelService.onModelRemoved` is called again and either
1. reading every line takes too long and VS Code stalls and crashes
2. the `WatchingProblemCollector` fails to add another line to `this.lines` and VS Code crashes

### Steps to reproduce
1. Run a shell task that doesn't end and has `"isBackground": true, "problemMatcher": [],`. `problemMatcher` may also be excluded entirely.
3. Generate a lot of output from that shell task
4. Keep opening and closing files with at least 1 problem in them to duplicate the number of lines stored in the problem collector
5. VSCode gets slower and slower at closing files until it eventually crashes the `window` process

https://user-images.githubusercontent.com/20326398/219228328-6998ffc9-2ee8-4b91-af3f-f96d84f2a988.mov

### Minimal reproduction repo
It includes instructions on how to specifically trigger the issue.
https://github.com/zachhardesty7/vscode-problem-matcher-memory-leak

### Build information
**All extensions disabled**
VS Code version: Code - Insiders 1.76.0-insider (af4a70d991053dcbf64d9a86c76a02dced81d9c4, 2023-02-14T05:34:56.983Z)
OS version: Darwin arm64 21.6.0
Modes:
Sandboxed: Yes

### Note
I spent forever trying to debug what was wrong with my setup, combing thru extensions, debug logs, performance traces, memory dumps, etc. Hopefully this helps! To me, it seems like the problem collection shouldn't be created if there's no problem matchers, regardless of what `isBackground` is set to. Side note, the `tasks.json` schema indicates that the default for `isBackground` is `true`, but this issue does not occur without manually setting it to `true`.

**Comment by zachhardesty7** [comment]
I added reproduction steps, a minimal reproduction repo, and a video demonstrating the crash using that repo!

**Comment by meganrogge** [comment]
Thanks for the detailed investigation. I'll look into this next week
