### ISSUE TITLE
HTML - external script

### ISSUE THREAD

**Issue by Mlocik97** [Microsoft/vscode#17456]
- VSCode Version: 1.8.0
- OS Version: Win8.1

Steps to Reproduce:

1.  create a html document with external script
2.  continue write to html document

![screenshot_112](https://cloud.githubusercontent.com/assets/21063534/21286909/7593ea4a-c460-11e6-8440-6304c4bdf920.png)

http://s22.postimg.org/hxkhobwv5/screenshot_111.png

hints continue JS, no HTML tag </script>

**Comment by kieferrm** [comment]
@Mlocik97 since the script element is not closed intellisense considers the position to be inside a script tag.

**Comment by Mlocik97** [comment]
but how I can fix it? Can "You" (programmers) add exception "don't use JS hints but "</script>" hint when tag "<script>" contains " src="" " ?

(sry for my English, I use google translator)

**Comment by mrmlnc** [comment]
Temporary solution:

![2016-12-17_17-48-55](https://cloud.githubusercontent.com/assets/7034281/21287632/1e0c7348-c481-11e6-9fdf-3d0a356b1f57.gif)

**Comment by Spown** [comment]
I don't think there is something to fix. Just close the ``<script>`` tag before you do anything that is supposed to be inside it. I know it would require changing your coding style, but that's the way to go honestly. I don't know if you know it, but there is [emmet](https://code.visualstudio.com/Docs/languages/html#_emmet-snippets) support in HTML. Meaning you type "script", hit TAB, and it's already closed
![](https://dl.dropboxusercontent.com/u/105338698/ShareX/2016-12/2016-12-17_16-33-41.gif)

**Comment by Mlocik97** [comment]
UP

**Comment by aeschli** [comment]
See https://developer.mozilla.org/en/docs/Web/HTML/Element/script:
> Tag omission:	None, both the starting and ending tag are mandatory.

**Comment by Mlocik97** [comment]
Open
