### ISSUE TITLE
Add `workbench.action.togglePinEditor` command

### ISSUE THREAD

**Issue by MisterFISHUP** [microsoft/vscode#174506]
There are currently two commands `workbench.action.pinEditor` and `workbench.action.unpinEditor` and I would like to have `workbench.action.togglePinEditor` so that one can easily toggle the edtior's state between pinned and unpinned using a single key binding.

I tried to send a PR myself but quickly found it's not as easy as I thought. Hope somebody can implement this or guide me on how to do it.

Thank you :)

**Comment by gjsjohnmurray** [comment]
I think you can use the `activeEditorIsPinned` [context key ](https://code.visualstudio.com/api/references/when-clause-contexts) (once as a negated test) to bind the same keycombo to the two commands. A `when` clause would make only one of them active at a time.

**Comment by DonJayamanne** [comment]
Closing this issue based on the response, if that does not address the issue, please ping here and i will re-open this
Or please feel free to create a new issue.
