### ISSUE TITLE
Walkthrough images flicker randomly

### ISSUE THREAD

**Issue by daviddossett** [microsoft/vscode#174595]
I often see these SVGs flickering either instantly or seconds after loading:

https://user-images.githubusercontent.com/25163139/219430302-00f0eb71-59e2-4e2d-832b-11e5ffc49470.mp4

**Comment by bpasero** [comment]
Who owns this?

**Comment by daviddossett** [comment]
I'm actually not sure anymore. @lramos15 do you know who took over after Jackson?

**Comment by daviddossett** [comment]
Oh, duh!

**Comment by bhavyaus** [comment]
This should be fixed with: https://github.com/microsoft/vscode/pull/177966
I'll leave this as verification needed for the next milestone.
