### ISSUE TITLE
Support local project-specific settings

### ISSUE THREAD

**Issue by ansidev** [microsoft/vscode#174536]
# Problem

Currently, project-specific settings will be saved into `.vscode/settings.json`.

However, some settings depend on the machine.

For example:

```
{
  "yaml.schemas": {
    "https://json.schemastore.org/github-workflow.json": "file:///Users/github/projects/github-actions/.github/workflows/deploy.yaml"
  }
}
```

**Note**: `/Users/github/projects/github-actions` is the path to project.

Because of settings that look like this, I can commit this file to the git repository for sharing across developers.

IMO, it would be better if VS Code supports local project-specific settings.

**Comment by gjsjohnmurray** [comment]
You can already do this if you first use `Save Workspace As...` on the `File` menu to create `myProject.code-workspace`. After doing this you get an extra tab in Settings Editor. Use that to store settings in the code-workspace file (which is JSON format).

**Comment by ansidev** [comment]
> You can already do this if you first use `Save Workspace As...` on the `File` menu to create `myProject.code-workspace`. After doing this you get an extra tab in Settings Editor. Use that to store settings in the code-workspace file (which is JSON format).

@gjsjohnmurray

Thank you for your guide. It works, at least.

However, I created a new issue #174548.

**Comment by sandy081** [comment]
/duplicate

https://github.com/microsoft/vscode/issues/40233
