### ISSUE TITLE
Find All References jumps to a result

### ISSUE THREAD

**Issue by NetDwarf** [microsoft/vscode#174592]
Does this issue occur when all extensions are disabled?: Impossible (You need a reference provider)

- VS Code Version: 1.75(.1)
- OS Version: Fedora Silverblue 37

Steps to Reproduce:
1. Install C# extension
2. "Find All References" for a class that is used in another file

**Expected:** Just show results in the references pane.

https://user-images.githubusercontent.com/14839491/219426932-9da68ece-94e0-454f-8c24-baee9e3c3b95.mp4

(this is with 1.74.3 everything else being equal)

**Actual:** It shows the results in the references pane *and* jumps to a result

https://user-images.githubusercontent.com/14839491/219426248-4f75b8ba-a12a-4378-bbc4-4fbb19ab2b8e.mp4

(this is with 1.75.0, but also happens with 1.75.1)

**Comment by jrieken** [comment]
This can be controlled via `editor.gotoLocation.multipleReferences` and similar settings

**Comment by NetDwarf** [comment]
![image](https://user-images.githubusercontent.com/14839491/220109269-93248ec1-1073-49cd-9558-4cfd24d60fe0.png)

I am not even sure this is the right setting, since I explicitly wanted to *Find* the reference and not *Go to* it.

Please reopen!

**Comment by jrieken** [comment]
So, what exact command to you run and how do you trigger it?

**Comment by NetDwarf** [comment]
It's just "Find All References" on a C# method or class. The behavior for this changed from 1.74.3->1.75.0. 

To rule out any user settings I actually did the screencaps on a fresh install, which is:
1. Install VSCode
2. Install C# extension
3. Do what is in the video

Both videos are done the same, but once with version 1.74.3 and once with 1.75.0. You notice that it jumps to a reference when you press "Find all references", when it actually shouldn't. It does break my workflow because it jumps to a (from my perspective) random file I didn't mean to open. You can jump back, but it's heavily irritating.

**Comment by jrieken** [comment]
Sorry, I don't see a video, just two screen capture. Please skip the video and write down simple steps. That's faster for everyone

**Comment by NetDwarf** [comment]
> Sorry, I don't see a video, just two screen capture. Please skip the video and write down simple steps. That's faster for everyone

1. Install VSCode
2. Install C# Extension in VSCode
3. Clone https://github.com/NetDwarf/NetTest
4. File->Open Folder: NetTest
5. Navigate to Foobar.cs
6. Right-click `Bar` method
7. Select "Find All References"

**Expected:** Show results in the references pane and do nothing else
**Actual:** Shows the results and jumps to a reference.

**Comment by De-Panther** [comment]
That bug annoyed me as well.
Reading your comments, I noticed it happens only in C#, so I downgraded the C# extension and found that on version 1.25.1 it doesn't happen, but 1.25.2 has the bug.

**Comment by De-Panther** [comment]
I was thinking that it might be related to the C# extension, and when downgrading it seems to solve the issue, but I didn't test it well. Even on older C# extension versions the bug happens

**Comment by NetDwarf** [comment]
Yeah as you rightly noticed it also happens with C# Extension 1.25.1 and you can fix it by downgrading VSCode to 1.74.3 (or likely anything prior). I also tried to do this in golang, but I couldn't trigger it the same way, but it misbehaves as well. It switches to a result and then back to the definition.

Because it is easier to see, trigger/reproduce I picked C#, but it is likely affecting more languages.

**Comment by Zaggy1024** [comment]
I can confirm that this is occurring for me with the C/C++ extension from Microsoft and the clangd extension both. The only difference is that on my experience the match is always the same as the starting point of the reference search so it just jumps back to the current line. This is still very distracting and undesirable.

**Comment by cengels** [comment]
It affects TypeScript projects as well.

Additionally, what I've noticed is that, if Find References finds references in multiple files, just clicking on the file name (to collapse or expand the results) also jumps the editor to the first result in that file. This didn't used to happen. All I want to do is expand the other files' references so I can see them, I don't want to jump to anything yet.

Interestingly, after you click on a file (let's call it File_A) and the editor jumps, you can then navigate the editor away from the line it jumped you to or even change editor tabs entirely. Clicking again on File_A in the References window does _not_ jump the editor back to that result. It only jumps you back if you click on a different reference in the References window and then back on File_A.

**Comment by NetDwarf** [comment]
We're on 1.77(.1) and the issue persists. At this point we might assume it is not gonna fix itself. I am still on 1.74(.3).

**Comment by cangyin** [comment]
experiencing same behavior on version 1.78.0
