### ISSUE TITLE
extension warning: outDir deprecationMessage

### ISSUE THREAD

**Issue by goessner** [Microsoft/vscode#17459]
- VSCode Version: 1.8.0
- OS Version: Windows 10

New warnings since vscode update to 1.8. with my extension "Markdown+Math"
![grafik](https://cloud.githubusercontent.com/assets/4902746/21286841/5784f054-c45f-11e6-96d1-9c7fe3428cbe.png)

Not sure if `launch.json` is of interest here ...
![grafik](https://cloud.githubusercontent.com/assets/4902746/21286906/71e35610-c460-11e6-9f5e-ccc97b10ad40.png)

thanks ...

**Comment by kieferrm** [comment]
@roblourens This is saying that the message for key <outdir.deprecationsMessage> was not found. I guess that the incomplete translation causes the warnings. If that's the case, we should  show the English text.

**Comment by goessner** [comment]
hmm ... will I get the English message then .. and why. Or will everything be fine with complete translation ?

Thanks ...

**Comment by mikemakepen** [comment]
I add some items into translation file, there warnings are gone.
