### ISSUE TITLE
Inconsistent behavior while changing Code Workspace settings

### ISSUE THREAD

**Issue by ansidev** [microsoft/vscode#174548]
Does this issue occur when all extensions are disabled?: Yes/No

### Environment Information

```
Version: 1.75.1
Commit: 441438abd1ac652551dbe4d408dfcec8a499b8bf
Date: 2023-02-08T21:34:59.000Z
Electron: 19.1.9
Chromium: 102.0.5005.194
Node.js: 16.14.2
V8: 10.2.154.23-electron.0
OS: Darwin x64 21.6.0
Sandboxed: No
```

This issue is related to #174536.

### Steps to Reproduce

1. Project structure

```
.
├── .github
│   └── workflows
│       └── deploy.yaml // GitHub Action workflow
├── .vscode
│   └── settings.json
└── ws.code-workspace   // VSCode workspace
```
`ws.code-workspace`

```
{
  "folders": [
    {
      "path": "."
    }
  ],
  "settings": {}
}
```

2. Open the project in VSCode using `ws.code-workspace`.
3. Install extension https://marketplace.visualstudio.com/items?itemName=redhat.vscode-yaml
4. Open the `Settings` tab.
5. Switch to the tab `<Folder>`.
6. Change font size => Setting will be saved to `.vscode/settings.json`.
7. Open `.github/workflows/deploy.yaml`
8. Click the `Select JSON Schema` button in the bottom right corner and change the value. => Setting will be saved to `ws.code-workspace`.

### Expectation

IMO, the font size setting should be saved to `ws.code-workspace`.

**Comment by gjsjohnmurray** [comment]
In step 5 you explicitly told Settings Editor that you wanted to change a value in the `.vscode/settings.json` file. If you wanted to change it in `ws.code-workspace` you should have switched to the "Workspace" tab.

The hover tip on those tabs tells you which file they affect.
