### ISSUE TITLE
[settings] show setting item default in hover tooltip

### ISSUE THREAD

**Issue by tjx666** [microsoft/vscode#174532]
For now, If I want to see the default value of a setting item, I need to delete the value I set, which is too complex.

![image](https://user-images.githubusercontent.com/41773861/219292165-c6f9db1d-dd52-4318-bdd9-f7f8d9112283.png)

**Comment by sandy081** [comment]
These hovers are contributed by JSON extension, hence assigning to @aeschli

**Comment by sandy081** [comment]
@aeschli I believe it is not correct for me to update the description of a setting. It can be error prone, what if the setting description already mentioned about the default value.

`json.schemas` is a setting contributed by the json extension. It would be up to the owner of the setting to provide the default value in the description or not. So, I would leave it to you.

**Comment by aeschli** [comment]
@sandy081 I believe `json.schemas` was just an example, The user wants this for all settings. 

Maybe the default should even aware of the setting hierarchy (e.g.. would show the current user setting value if this were for a workspace settings).

This can only be done in the settings where the schema is prepared, or with a custom hover provider.

If there are no plans to do this on the settings side, closing the issue 'won't fix'.
