### ISSUE TITLE
'View' menu is preventing me from choosing 'Go' or 'Help' menu

### ISSUE THREAD

**Issue by hun1ahpu** [Microsoft/vscode#17457]
- VSCode Version: 1.8.0
- OS Version:Windows 10

Steps to Reproduce:

1. Mouse hover over the 'View' menu.
It opens the long list of sub-menus which on my screen (1920x1080 with 150% zoom factor) takes the whole height of the screen and blocks me from choosing the menu options on the right: 'Go' and 'Help'.

![menuheight](https://cloud.githubusercontent.com/assets/4397796/21286706/77e0a2fc-c45b-11e6-81e9-dadb53a204e1.gif)

**Comment by Tekbr** [comment]
Similar #16826 ?

**Comment by bpasero** [comment]
Duplicate of https://github.com/Microsoft/vscode/issues/16826
