### ISSUE TITLE
Clicking on Refactor shows Surround With

### ISSUE THREAD

**Issue by bberman3** [microsoft/vscode#174588]
Type: <b>Bug</b>

In a server side .js file for a function within a Class
Select a block of text
Right click and go to Refactor... or click on the lightbulb
The Surround With block shows up instead of Refactor

VS Code version: Code 1.75.1 (441438abd1ac652551dbe4d408dfcec8a499b8bf, 2023-02-08T21:34:59.000Z)
OS version: Darwin x64 20.6.0
Modes:
Sandboxed: No

**Comment by jrieken** [comment]
> The Surround With block shows up instead of Refactor

Why is that bad? The surround with feature is a kind of a refactoring so I need to be convinced why it shouldn't be there

**Comment by bberman3** [comment]
```
module.exports = class UrlRenderer {

  endOfInternalDomain(originalUrl) {
    const startOfDomain = originalUrl.indexOf('//www');
    if (startOfDomain > -1 && startOfDomain < 7) {
// --- start refactor
      const endOfDomain = originalUrl.indexOf('/', startOfDomain + 2);
      if (endOfDomain > -1 && originalUrl.length > endOfDomain) {
        const lastPeriod = originalUrl.lastIndexOf('.', endOfDomain),
              secondToLastPeriod = originalUrl.lastIndexOf('.', lastPeriod - 1),
              domain = originalUrl.substring(secondToLastPeriod < 0 ? startOfDomain + 2 : secondToLastPeriod + 1, lastPeriod);
        if (domain && this.urlRewriteSiteKeys.includes(domain)) {
          return endOfDomain;
        }
      }
// --- end refactor
    }
    return -1;
  }
  
  }
```

**Comment by bberman3** [comment]
Also, it isn't bad that Surround with is there. It's that Refactor isn't

**Comment by mjbvz** [comment]
@bberman3 That's likely because there are no refactoring available for your current selection. Try clicking `show disabled` to show refactorings that have been disabled

Closing as by-design based on @jrieken's comments
