### ISSUE TITLE
terminal readability is lost when gpu acceleration is enabled

### ISSUE THREAD

**Issue by yilmazdurmaz** [microsoft/vscode#174508]
Does this issue occur when all extensions are disabled?: Yes (new profile with no extension)

- VS Code Version: 1.75.1
- OS Version: W10 21H2

I do not know how exactly this bug comes up. For the last few years, I was having this problem after my laptop woke up from sleep mode if the terminal was open before putting it to sleep. Usually, killing it and re-opening a new one was my solution.

This time, the trick did not work. I checked the setting and find this GPU acceleration relation. I screen captures that show the loss in readability of the terminal. It is like scaling 1080p picture down to a 180p one. Video shows instant transformation while the shots emphasis the difference. the size of the main window or terminal panel does not matter.

Steps to Reproduce:
1. open settings and find "@feature:terminal gpu"
2. open a terminal and experiment by changing it to "on" and "off"

[video-convert-1676499005293.webm](https://user-images.githubusercontent.com/1812105/219192751-54a796ac-a2c5-49b9-9934-4971a49eeb0f.webm)

---
Maybe the problem was always here, and then someone decided to enable GPU acceleration with this 1.17.x series thus came this report. I am not sure though. I hope you can find the cause.

gpu acceleration is off
![gpu-off](https://user-images.githubusercontent.com/1812105/219204863-228a8efc-38b1-460d-9a0c-f52510d00991.png)

gpu acceleration is off
![gpu-on](https://user-images.githubusercontent.com/1812105/219204858-841161f8-89d9-42e5-aba7-833d0b4ee8b3.png)

**Comment by j4k0xb** [comment]
> Since there haven't been any comments saying this still happens since April I'm going to close this off. Let me know if you see this, and if so run the new Show Terminal Texture Atlas command and upload the image is puts in your workspace root:
> 
> ![image](https://user-images.githubusercontent.com/2193314/207088985-7605d9b6-61e5-4ef4-ac31-8d9d67ae9e50.png)
> 
> _Originally posted by @Tyriar in https://github.com/microsoft/vscode/issues/69665#issuecomment-1346748326_

This command outputs an image for normal terminals but doesn't do anything for the broken one:
![image](https://github.com/microsoft/vscode/assets/55899582/1e1f9a68-0e65-4237-ad31-376c47100438)

**Comment by yilmazdurmaz** [comment]
@Tyriar Thanks for checking this again after so long.

Unfortunately I am not dev area for quite sometime, so do not have a dev setup. In the future, if I return and see same issue, rest assured I will post again :)

Cheers
