### ISSUE TITLE
Add a way to organise INSTALLED extensions.

### ISSUE THREAD

**Issue by Reun85** [microsoft/vscode#174587]
## Summary
Create a way to add "flags" to installed extensions on my machine.
These "flags" should, 
 - allow us to search for them in the extensions tab like: `@installed @flag:basic-cpp17`
 - allow us to enable all extensions that has been found in said search
 - be available regardless of chosen workspace (maybe even synced between computers)

This would allow to us flag extension based on which work environments we want them enabled. Because of this extensions should be allowed to have multiple flags.
 
## Reason
As a student I have to work in many different work environments: ANSI C, C++11, C++17, Python, Web(React, Vue, Ang),Haskell, Clean.
Because of this I have 90+ extensions which my laptop is just unable to handle reasonably well. And its too much of a pain to switch between sets of extensions manually so I just deal with the abismal performance. But lately I have encountered multiple really useful extensions which conflict when using different languages and make VSCode unusable. Please save me.

**Comment by sandy081** [comment]
You can use Profiles feature for your usecase - https://code.visualstudio.com/updates/v1_75#_profiles
