### ISSUE TITLE
Too-eager hovers in Explorer impede use of context menu

### ISSUE THREAD

**Issue by gjsjohnmurray** [microsoft/vscode#174570]
Type: <b>Bug</b>

![junk](https://user-images.githubusercontent.com/6726799/219357494-21880804-70c6-4f10-8acb-456fe9816751.gif)

VS Code version: Code - Insiders 1.76.0-insider (dc619de8d9efdabd781fc5658d0051813c347055, 2023-02-16T05:23:44.671Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: Yes

/assign @lramos15

**Comment by lramos15** [comment]
Thanks! This is also a regression because we are only supposed to show it on files with decorations (such as source control) or overflowing text (such as `superlongname...`).

**Comment by jrieken** [comment]
@lramos15 I don't get this custom hover ever. Can you please add steps to verify?

**Comment by lramos15** [comment]
@jrieken These custom hovers have been removed from product due to being too buggy at the moment. I will just mark this as verified as this feature isn't ready for testing yet.
