### ISSUE TITLE
Wrong Doxygen syntax highlighting @copydetails

### ISSUE THREAD

**Issue by MKHen** [microsoft/vscode#174535]
Does this issue occur when all extensions are disabled?: Don't know

- VS Code Version: 1.75.1
- OS Version: Windows 10

Steps to Reproduce:

1. Enter @copydetail it is highlighted but not working with Doxygen
2. Enter @copydetails which is not highlighted but is the correct command

**Comment by mjbvz** [comment]
What language is this for?

**Comment by MKHen** [comment]
You can use it for C/C++.
