### ISSUE TITLE
VS Code in Browser, when webview is active: F1, F5: default is not prevented

### ISSUE THREAD

**Issue by hediet** [microsoft/vscode#174569]
## Reproduction steps
* Open a webview in VS Code browser (e.g. markdown preview in github.dev, you can go to https://github.com/hediet/slideo for that and press ".", the readme should open automatically)
* Focus the webview
* press F1

## Expected behavior
The command palette opens.

## Actual behavior
The chrome help opens.

**Comment by balaji-sivasakthi** [comment]
@hediet it's working fine. Please check once again (maybe your focus on `browser URL`)

**Comment by hediet** [comment]
It still reproduces. Did you focus the REAMDE.md webview?

**Comment by a-stewart** [comment]
I can reproduce with F1 and F5 on Chrome/Linux. Created a PR to fix

**Comment by mjbvz** [comment]
Fixed by https://github.com/microsoft/vscode/pull/204499 I believe

**Comment by alexr00** [comment]
I can't repro the original issue with stable. @hediet are you able to verify?
