### ISSUE TITLE
Extention not appearing after instllation

### ISSUE THREAD

**Issue by ValueITTechnology** [microsoft/vscode#174590]
Type: <b>Bug</b>

I tried many extentions but no one appear in left bar after instllations.  I tried both Windows and Mac.

I dont see any error also while installations.  All extentions are installed correctly.  

When I start VS Code, the icons appear for few seconds and tehn go away.  Because of this i cant use any extentions.  I tried SFTP , Simple FTP, VIM and all has same issue.

VS Code version: Code 1.75.1 (441438abd1ac652551dbe4d408dfcec8a499b8bf, 2023-02-08T21:34:59.000Z)
OS version: Darwin x64 21.6.0
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz (4 x 2700)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|3, 5, 11|
|Memory (System)|8.00GB (0.09GB free)|
|Process Argv|--crash-reporter-id c71b0604-b434-4fe9-bb69-e21ce4f094e9|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-intelephense-client|bme|1.9.5
ftp-simple|hum|0.7.6
atom-keybindings|ms-|3.3.0
sftp|Nat|1.16.1
simple-ftp|Ous|0.0.1
vscode-sftp|sun|1.1.1
vim|vsc|1.24.3

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
azure-dev_surveyone:30548225
vscccc:30610679
pyindex848:30662994
nodejswelcome1cf:30587006
3biah626:30602489
pyind779cf:30662993
f6dab269:30613381
pythonsymbol12cf:30657549
a9j8j154:30646983
vsccsb:30662443

```

</details>

**Comment by sandy081** [comment]
Can you please share following log

- F1 > Open View... > Window

**Comment by ValueITTechnology** [comment]
Hello Sandy, I found that some extensions not appearing in left side bar, they can be accessed using command line terminal.  I dont think it is bug in VS Code.  Thank you for your reply.  I will close this thread.
