### ISSUE TITLE
URL: Use new session when open vscode with urls

### ISSUE THREAD

**Issue by filbe** [microsoft/vscode#174582]
When using vscode:// links, it always opens in an existing window. That strictly limits use cases of the feature.
It would be good if one can specify some arguments to use a new window.

My use case: On a remote development platform there is "Open in VSCode" links. However, opening multiple remote ssh environments from web browser (when vscode already has another codebase open) is not possible due to limitations of the vscode:// link features. If one environment (codebase, session, vscode window etc you want to call it) is already opened, there is no way to open a second one because it always goes to the same window. vscode:// should have option to first open an empty window (session) and then do whatever the link says. Or it could be done in vscode-remote/ssh-remote level, when it could check if one existing session has the code already opened, and if not, opens it up in a new window.

This is previously closed feature request, trying to find more support to this over 4 years later:
https://github.com/microsoft/vscode/issues/62119

**Comment by bpasero** [comment]
If you set `windowId=_blank` as query parameter to the URL, it should work?

**Comment by filbe** [comment]
That worked, thank you very much! But this feature is not yet documented anywhere, and it absolutely should be, e.g. here:
https://github.com/Microsoft/vscode-docs/blob/master/docs/editor/command-line.md#opening-vs-code-with-urls

**Comment by bpasero** [comment]
Yeah, fyi @joaomoreno
