### ISSUE TITLE
For PHP writing $this used to autocomplete to $this-> now it removes the dollar sign

### ISSUE THREAD

**Issue by ukjadoon** [Microsoft/vscode#17453]
- VSCode Version: Code 1.8.0 (38746938a4ab94f2f57d9e1309c51fd6fb37553d, 2016-12-13T17:45:32.595Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

|Extension|Author|Version|
|---|---|---|
|theme-atom-one-dark|andischerer|0.0.1|
|Theme-FlatlandMonokai|gerane|0.0.4|
|format-indent|Kasik96|1.3.0|
|php-symbols|linyang95|0.1.2|
|Theme-MaterialKit|ms-vscode|0.1.1|
|theme-hackershaze|Nuuf|1.3.1|
|Seti-theme|TsumiNa|0.0.1|
|Material-theme|zhuangtongfa|1.0.3|

---

Steps to Reproduce:

1. While writing code in a PHP file, type $this to see the autocomplete to $this-> option and press Enter.
2. Instead of seeing it autocomplete to $this-> it removes the '$' sign and instead writes this-> which is incorrect.

**Comment by mousetraps** [comment]
@ukjadoon thx for reporting! Unfortunately I can't seem to reproduce this problem at all. 
![image](https://cloud.githubusercontent.com/assets/762848/21711151/08b59454-d3a2-11e6-8f4f-2679fefb15f9.png)

Are you still running into it? Does it happen in all files, or just sometimes?

**Comment by ukjadoon** [comment]
Thank you so much for looking into this issue (and apologies for the late response).
 
In order to get it to show your autocomplete option with the text “Refers to the current object”. I have to write
 
`$this` (a dollar sign followed by this keyword)
 
![image](https://cloud.githubusercontent.com/assets/549181/22248123/6ba9e2fa-e23d-11e6-9673-1917d3ea4dbf.png)

In order to get my reported autocomplete option, you just have to write this (without the dollar sign) inside a PHP file.

![image](https://cloud.githubusercontent.com/assets/549181/22248098/5586f6ac-e23d-11e6-8866-87ebfaeab60a.png)

 
In the previous versions of visual studio code, for PHP files, writing "this" without the dollar sign would autocomplete to `$this->` (it would automatically add the dollar sign to the “this” keyword followed by `->` which saves some time). Now it still adds the `->` symbol but no dollar sign (when I write this without the dollar sign and autocomplete). That just makes the whole experience annoying as I have to go back to the beginning of the word to manually add a dollar sign, it should work as it did before.

If I write `$this` and autocomplete, it does not add the `->` symbol at the end.
 
I hope that helps clarify the issue.

**Comment by roblourens** [comment]
#18778
