### ISSUE TITLE
VSC doesn't support git in MSYS2 ?

### ISSUE THREAD

**Issue by xialvjun** [Microsoft/vscode#17461]
- VSCode Version: Code 1.8.0 (38746938a4ab94f2f57d9e1309c51fd6fb37553d, 2016-12-13T17:45:32.595Z)
- OS Version: Windows_NT ia32 10.0.14986
- Extensions:

|Extension|Author|Version|
|---|---|---|
|clojure|avli|0.4.2|
|toml|be5invis|0.0.3|
|vscode-eslint|dbaeumer|1.2.2|
|python|donjayamanne|0.5.5|
|EditorConfig|EditorConfig|0.3.4|
|tslint|eg2|0.7.1|
|vscode-npm|fknop|3.3.0|
|Go|lukehoban|0.6.51|
|partial-diff|ryu1kn|0.2.0|
|RustyCode|saviorisdead|0.19.1|
|Align|steve8708|0.2.0|
|language-stylus|sysoev|1.6.0|
|debug|webfreak|0.14.0|
|ReactSnippets|xabikos|1.2.0|

---

Steps to Reproduce:

1. install MSYS2 and pacman -S git.
2. add %MSYS@_HOME%/usr/bin to Path.
3. install VSCode and open a project versioned by git.
4. open the git panel.

**Comment by mrmlnc** [comment]
Maybe https://github.com/Microsoft/vscode/issues/4651?

**Comment by xialvjun** [comment]
Yeah, that's it. Sorry for didn't notice it.
