### ISSUE TITLE
vscode debugger stops on reject()

### ISSUE THREAD

**Issue by a8775** [microsoft/vscode#1746]
Node 4.5.103.35, vscode: 0.10.6

``` TypeScript
'use strict';

class MyClass {
    f(f: boolean): Promise<void> {
        return new Promise<void>((resolve: () => void, reject: () => void) => {
                if(f===true) reject();
                else resolve();
            });
    }
}

var c = new MyClass();
c.f(true).then(()=> console.log('OK')).catch(()=>console.log('ERR'));
```

Debuger stops on `reject()`, with message "Paused on exception" without exception details, no breakpoints are set except "uncaught exception".

**Comment by weinand** [comment]
I've verified that node.js sends indeed a break event with and 'undefined' exception for the reject(), so the behavior is correct.
I will investigate whether VS Code could try to swallow the event and continue.

**Comment by DryRuskFromLS** [comment]
Any advance in this?

**Comment by pflannery** [comment]
I'm having the same issue in vscode v1.6.
vscode debugger always stops regardless of the promise rejection being handled correctly


if I run the below code using the cmd line `$ node debug app.js` I'm not given a break event when a rejected the promise is handled by the code. 
If I comment out the `catch` code I then get a UnhandledPromiseRejectionWarning exception


```js
// app.js
function test(shouldReject) {
  return new Promise((resolve, reject) => {
    shouldReject ? reject("rejected") : resolve("resolved")
  })
}

let shouldReject = true
test(shouldReject)
  .then(result => console.log(result))
  .catch(err => console.log(err)); // commenting this line will cause nodejs to throw UnhandledPromiseRejectionWarning
```

Would be nice if vscode debugger replicated the same behaviour as `node debug` and not break on a handled promise rejection.

**Comment by weinand** [comment]
@pflannery please try to use our new experimental node debugger by setting the debug type to "node2" (and you will have to use a node.js version >= 6.3).

**Comment by weinand** [comment]
@roblourens when trying the snippet from above with node2, I stop in line 4 on a "debugger statement" (whereas node-debug stops on an exception).

![2016-10-21_13-20-50](https://cloud.githubusercontent.com/assets/1898161/19596913/727c9ede-9791-11e6-8a4f-155705ee475c.png)

**Comment by weinand** [comment]
VS Code 1.7 tries to identify exceptions that result from rejects() and skips them if the 'All Exceptions' checkbox is not set.

/cc @roblourens

**Comment by roblourens** [comment]
Hm, I see the problem, but I'd rather keep Chrome DevTools' behavior here. I think it's something that would have to be addressed on the runtime side.

With this change, you could have a false positive and skip a line just because it happens to have the word 'reject' on it. You could also have the callback named something other than 'reject'. And at that point, you don't know whether the rejection is handled, so you could be skipping an unhandled promise rejection.

**Comment by weinand** [comment]
@roblourens fair points... I will disable this feature for now.
However, I noticed that node-debug2 reports the information for rejected promises as "debugger statement". This sounds wrong. Is this really intended? (see screenshot above).
In addition in the CDP a "paused" event has a reason "promiseRejection" so node-debug2 could easily introduce a new exception filter for promise rejections that would not suffer from the 'false positive' problem.

@a8775 @DryRuskFromLS @pflannery 
node's v8 debugger protocol does not return any information to distinguish 'promise reject' exceptions from other exceptions. So I cannot offer a reliable mechanism to automatically skip rejected promises but still stop on other uncaught exceptions.
Node-debug2 night be able to add this feature in a robust way.

I will leave this feature request closed since there is already a way to prevent the debugger from stopping on reject() by means of the 'uncaught Exceptions' checkbox (and I cannot do more with the limitations of the now obsolete v8 debugger protocol).

**Comment by roblourens** [comment]
Good points @weinand, I filed an issue to look at that in node-debug2

**Comment by linvi** [comment]
Hello there. I am still facing this issue. My VSCode is 1.7.2 and if I have `Uncaught Exceptions` I received reject as being an exception.

If I unselect it I no longer receive it.

But obviously I do not want `reject` to break but I do want to receive all `Uncaught Exceptions`.

Am I doing some thing wrong?

Here is a screenshot of vscode with a break happening on a reject without having a specified breakpoint for it.

![image](https://cloud.githubusercontent.com/assets/6107439/20859177/2e37e6c2-b94f-11e6-9e57-dea39a39c3c1.png)

**Comment by weinand** [comment]
@linvi what you are seeing is the native node.js behavior. Please read my comment https://github.com/Microsoft/vscode/issues/1746#issuecomment-255617404.

**Comment by pflannery** [comment]
@weinand does that mean node is overriding its own native behaviour when running `$ node debug` from a terminal?

**Comment by weinand** [comment]
`node debug` is node's own debug UI that has access to more runtime internals than VS Code has through the v8 debugger protocol.

**Comment by kaefert** [comment]
I think I'm observing the same issue here. VS Code stops here on every page load. When I step over the marked line the fetchPromise has the status  "rejected".
![screenshot from 2016-12-19 10-06-22](https://cloud.githubusercontent.com/assets/1448723/21306747/d7fdcc50-c5d2-11e6-82f1-caf13685a639.png)

I'm running VS Code 1.8.0, Commit 38746938a4ab94f2f57d9e1309c51fd6fb37553d, Shell 1.4.6, Renderer 53.0.2785.143, Node 6.5.0

**Comment by vwzhang** [comment]
I am having this problem too with 1.9.1, zonejs 0.7.6. I tried to all the combination of put empty string into the fetch and/or toggle chrome pause on caught exception with no luck. I don't understand such a simple thing cannot be resolved. Either fixing zonejs.fetch or ignore it from vscode. Is this because both are free open source stuff?

**Comment by weinand** [comment]
@vwzhang what debugger are you using?

**Comment by weinand** [comment]
By analysing the screenshot it looks like that you are using the 'node2' debugger.

@roblourens any suggestions?

**Comment by roblourens** [comment]
I have https://github.com/Microsoft/vscode-node-debug2/issues/46 to look at this. I may be able to add an exception filter for it, but I don't think I can distinguish between handled promise rejections and unhandled promise rejections. And I'm inclined to stick with the runtime/chrome devtools' behavior.

**Comment by weinand** [comment]
copied @roblourens comment from Microsoft/vscode-node-debug2#46:

> If a promise is rejected before an error handler is attached, the debugger will break, even if only "uncaught exceptions" is checked. If it's rejected after the error handler is attached, it works as expected. [...] And really the problem is the way the promise doesn't know whether its rejection will be handled or not.

**Comment by davisshaver** [comment]
This seems fine for now, but it'd be very nice to have granular controls in the future! Glad to see the discussion!

**Comment by Olian04** [comment]
Have the same (or similar) issue: 

```
function failingFunc() {
    let undef = undefined;
    return undef.nope();
}
let promise = new Promise((resolve, reject) => {
   resolve(failingFunc()); // Explodes when run from vscode
});
promise.then(v => {}).catch((e: Error) => {
    console.log(e.message); // Prints when run from the terminal
});
```

__vscode about page:__ <br>
Version 1.14.2
Commit cb82febafda0c8c199b9201ad274e25d9a76874e
Date 2017-07-19T23:26:08.116Z
Shell 1.6.6
Renderer 56.0.2924.87
Node 7.4.0

**Comment by Olian04** [comment]
For anyone having issues with this, a temporary solution can be found [here](https://stackoverflow.com/questions/45282653/why-does-vs-code-break-on-handled-exception-from-reject-in-promise/).

**Comment by errorx666** [comment]
I want to break on rejected promises but not all exceptions.

I am trying to debug a gulp build that is failing with a (nondescript) promise rejection.  If I set the debugger to break on Uncaught Exceptions, it never breaks.  If I set the debugger to break on All Exceptions, it breaks every time the build tries to stat a file (1000s of times).

There appears to be no way to break on promise rejections.

**Comment by electrotype** [comment]
I have this issue using `mongodb-download@2.2.4`: when I launch a debug session, VSCode breaks because of [this line](https://github.com/winfinit/mongodb-download/blob/master/src/mongodb-download.ts#L489).

My question : is there a _project setting_ I can use to disable the `Breakpoints - Uncaught Exception` checkbox in VSCode by default? This break is so annoying.

I tried using `skipFiles` in my launch config :

```
"skipFiles": [
    "${workspaceFolder}/node_modules/**/*.js"
 ]
```

But VSCode still breaks when `Breakpoints - Uncaught Exception` is checked.

Is there a way/workaround/anything other than manually uncheck `Breakpoints - Uncaught Exception` to prevent VSCode to break on this line?

**Comment by Olian04** [comment]
@electrotype take a look at [this SO question](https://stackoverflow.com/questions/45282653/why-does-vs-code-break-on-handled-exception-from-reject-in-promise/)

**Comment by electrotype** [comment]
Thanks @Olian04 . Sadly, I don't want to disable debugging on this project.... I need to start it in debug mode.

I really wish there was a project setting to disable `Breakpoints - Uncaught Exception` by default!

**Comment by roblourens** [comment]
@electrotype If you uncheck "Uncaught Exceptions", it should stay unchecked in that workspace until you check it again.

`skipFiles` unfortunately won't work here because it doesn't apply to uncaught exceptions - same as "blackbox script" in chrome devtools.

**Comment by electrotype** [comment]
Thanks for the info @roblourens . But We are a big team : people checkout the project and run it as adviced... That "error" doesn't look good at all! I now have to ask them to uncheck `Breakpoints - Uncaught Exception` by themselves, in the documentation?

**Comment by roblourens** [comment]
@weinand @isidorn - Chrome and FF devtools don't break on any exceptions by default. I think I should change the default for "Uncaught Exceptions" to 'false'. Thoughts?

**Comment by roblourens** [comment]
Another possibility would be continuing automatically from files in skipFiles (like smartStep) so we can skip uncaught exceptions which aren't really, since Chrome still pauses there even in blackboxed scripts.

**Comment by weinand** [comment]
Let's investigate this in December.

**Comment by roblourens** [comment]
I changed the "uncaught exceptions" default to `false` for now at least.

**Comment by jeffmcaffer** [comment]
I have this problem as well using Node's `util.promisify` (in v 8.9.4). Using the sample below and running from vscode, you would expect "just cause" to pop out on the console. Instead, the debugger stops with "Exception has occurred: Error" (see screenshot below). Continuing the execution works just fine but it means you have to run with `Uncaught Exceptions` turned off which of course, is a challenge in scenarios where you are trying to deal with real uncaught exceptions.

```javascript
const { promisify } = require('util')

function bar(callback) {
  callback(new Error('just cause'))
}

async function foo() {
  try {
    await promisify(bar)()
  } catch (error) {
    console.log(error.message)
  }
}

foo()
```

![image](https://user-images.githubusercontent.com/10070956/46320653-42b83400-c594-11e8-903a-ebf8ab7736dc.png)

**Comment by roblourens** [comment]
Unfortunately I don't have any better solution here. The 'undefined' mentioned in the OP is technically correct for that case. The issue of node sending the wrong pause reason has been fixed, so now the call stack label is correct. My investigation in https://github.com/microsoft/vscode-node-debug2/issues/46 is another explanation of what's happening.

My suggestion of 

> Another possibility would be continuing automatically from files in skipFiles (like smartStep) so we can skip uncaught exceptions which aren't really, since Chrome still pauses there even in blackboxed scripts.

I would consider out of scope for now.

I think we will have to wait for better support from the runtime regarding "break on exception" for async-handled exceptions.
