### ISSUE TITLE
Scrollable notebook output does not reveal find results correctly

### ISSUE THREAD

**Issue by amunger** [microsoft/vscode#174633]
1. set `notebook.experimental.outputScrolling` to true
2. create a long output and scroll to the top of the output
3. search for something at the bottom of the output and turn the `search in output` filter
:bug: found match is not revealed

**Comment by isidorn** [comment]
None of the find matches in the output get found for me.

**Comment by amunger** [comment]
@isidorn you need to explicitly enable output search: https://github.com/microsoft/vscode/issues/174969

**Comment by amunger** [comment]
![search](https://user-images.githubusercontent.com/2019016/226024483-b3771994-54e4-4147-a618-036c371cf653.gif)
still see some weird behavior when the search string is at the bottom and there are enough cells above and below.
