### ISSUE TITLE
SCSS validation inside html <style> tags

### ISSUE THREAD

**Issue by ugros** [Microsoft/vscode#17460]
Recently, css validation has been added to html style tags, which is a cool feature, especially for Vue.js developers (that use .vue single file components).

But most Vue.js developers use css preprocessor inside their .vue files, using for example <style lang="scss"> tags.

Unfortunately, as far as I know, only css validation is supported inside <style> tags, resulting in many unnecessary errors.

Is there any workaround to this? If not, it would be nice to have this.
Either support "lang" attribute inside <style> tags or let us change <style> language type globally.

Thanks! 
PS.: Since Vue.js is getting more and more popular, I think it would be nice to have more Vue.js integrations with VS code in general, similar to React or Angular.

**Comment by aeschli** [comment]
The best would be if there were a vue extension that provides proper support for vue files.
Using html for vue files will lead to incompatibilities, as you observe.

**Comment by aeschli** [comment]
https://marketplace.visualstudio.com/items?itemName=octref.vetur had implemented intellisense for vue.
As mentioned I think having real vue support in an extension is the way to go. Closing this issue.
