### ISSUE TITLE
'Focus Default Settings Search' should not show in command bar if invalid context.

### ISSUE THREAD

**Issue by CoenraadS** [Microsoft/vscode#17468]
- VSCode Version: 1.8
- OS Version: Windows 10

In VSCode 1.7, to get to settings you just type:
ctrl+shift+p
sett...
Enter

Now in 1.8, if you type 'sett', or even full 'settings', the top result is 'Focus Default Settings Search', which then throws an error about being in the wrong context.

**Comment by bpasero** [comment]
We cannot control this easily, but I would just suggest to remove this command from F1, I see no good reason to have it in there and see the same problem about making it harder to open preferences from F1.
