### ISSUE TITLE
Integrated terminal sends wrong keystrokes when CTRL+SPACE is pressed

### ISSUE THREAD

**Issue by sewbacca** [microsoft/vscode#174618]
I have installed clink and want to use it inside the integrated terminal. [Clink](https://mridgers.github.io/clink/) supports autocompletion with `CTRL+SPACE`. Inside a normal console window, it reacts just fine, within VSCode wrong keys are sent. When running `clink echo --verbose` and hitting `CTRL+SPACE` I should get:
```
key event:  _C_ __  flags=0x00000028  char=0x0020  vk=0x0020  scan=0x0039  "Space"
"\e[27;5;32~"
```
Instead I get:
```
key event:  SC_ __  flags=0x00000018  char=0x0000  vk=0x0032  scan=0x0003  "2"
"\C-@"
```
- The SC means that both Shift and Ctrl are pressed.
- `"2"` means that the key "2" was pressed.
Both are inaccurate.
I tried with the setting `terminal.integrated.allowChords` both `true` and `false`.
Also I removed any keybindings covering `CTRL+SPACE`, to no avail.

Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.75.1
- OS Version: Windows_NT x64 10.0.19045

Steps to Reproduce:

1.  Install clink
2.  Open integrated terminal with clink
3. Run `clink echo --verbose`
4. Press `CTRL+SPACE`
5. See difference in normal console window.

**Comment by meganrogge** [comment]
tracked in https://github.com/xtermjs/xterm.js/issues/2357
