### ISSUE TITLE
Enhance `CommentThread` so extension can create vertically-scrollable threads

### ISSUE THREAD

**Issue by gjsjohnmurray** [microsoft/vscode#174629]
An extension I have created uses the comments API to create threads that display documentation. In some cases the documentation is lengthy. I would like to be able to set a height limit on the comments-container div.

I experimented by modifying this code:

https://github.com/microsoft/vscode/blob/56ba527736cc5c2ccc5073464923990840ed1049/src/vs/workbench/contrib/comments/browser/commentThreadBody.ts#L70-L74

adding this line to hard-wire a maximum height and vertical scrolling:

```ts
this._commentsElement.setAttribute('style', 'max-height: 15em; overflow-y: auto;');
```

It seemed to work.

> ![image](https://user-images.githubusercontent.com/6726799/219501649-aa2f8766-2b33-43b6-a037-2f64a6824ba3.png)

Would you be open to a proper implementation of this as proposed API?

**Comment by alexr00** [comment]
@gjsjohnmurray I'll discuss with the UX and API folks and let you know. It might makes sense to just have a max height without API.

**Comment by alexr00** [comment]
@gjsjohnmurray do you want to make individual comments scrollable or the whole comment thread scrollable?

**Comment by gjsjohnmurray** [comment]
For my case thread level is sufficient. My extension adds single comment threads.

**Comment by gjsjohnmurray** [comment]
@alexr00 now 1.76 has shipped please let me know if I can help progress this.
