### ISSUE TITLE
Displaying incorrect values in watch window

### ISSUE THREAD

**Issue by serich5** [microsoft/vscode#174641]
Type: <b>Bug</b>

When debugging the values in the watch window are not correct.

See full detials at: 
https://stackoverflow.com/questions/75478657/vscode-debug-showing-incorrect-variable-values

Switching back to version 1.74.3 does not have the same issue

VS Code version: Code 1.75.1 (441438abd1ac652551dbe4d408dfcec8a499b8bf, 2023-02-08T21:32:34.589Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|13th Gen Intel(R) Core(TM) i7-13700KF (24 x 3418)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|63.82GB (43.07GB free)|
|Process Argv|--crash-reporter-id 9410d975-e490-43b4-bf83-a5568c324136|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (26)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|13.3.1
copy-relative-path|ale|0.0.2
npm-intellisense|chr|1.4.4
vue-peek|dar|1.0.2
vscode-eslint|dba|2.4.0
gitlens|eam|13.2.0
EditorConfig|Edi|0.16.4
prettier-vscode|esb|9.10.4
auto-rename-tag|for|0.1.10
gc-excelviewer|Gra|4.2.56
todo-tree|Gru|0.0.224
beautify|Hoo|1.5.0
vscode-edge-devtools|ms-|2.1.1
vscode-js-profile-flame|ms-|1.0.5
color-highlight|nau|2.5.0
vetur|oct|0.36.1
vscode-css-peek|pra|4.2.0
vue-vscode-extensionpack|sdr|0.2.0
code-spell-checker|str|2.16.0
language-stylus|sys|1.16.0
vscode-status-bar-format-toggle|tom|3.1.1
volar|Vue|1.1.2
vscode-jumpy|wma|0.3.1
better-align|wwm|1.1.6
JavaScriptSnippets|xab|1.8.0
linecount|yyc|0.1.7

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
azure-dev_surveyone:30548225
pyindex848:30662994
nodejswelcome1cf:30587006
2e4cg342:30602488
pyind779:30662992
f6dab269:30613381
pythonsymbol12:30657548
2i9eh265:30646982
showlangstatbar:30664136
vsccsb:30662443
vscodeenable:30660116

```

</details>

**Comment by roblourens** [comment]
This is likely the same as https://github.com/microsoft/vscode-js-debug/issues/1561
