### ISSUE TITLE
The connection to the terminal's pty host process is unresponsive

### ISSUE THREAD

**Issue by devorient** [microsoft/vscode#174698]
Type: <b>Bug</b>

As of 1.75.0 (including 1.75.1) I get the following error when I launch a remote containers session:
"The connection to the terminal's pty host process is unresponsive, the terminals may stop working."
When I press the "Restart pty host" button, I get the same error message again.
Integrated terminal works well outside the remote container session.

I have not observed this issue in version 1.74.3. Downgrading fixes the issue.

VS Code version: Code 1.75.1 (441438abd1ac652551dbe4d408dfcec8a499b8bf, 2023-02-08T21:35:30.018Z)
OS version: Linux x64 6.1.11-200.fc37.x86_64
Modes:
Sandboxed: No
Remote OS version: Linux x64 6.1.11-200.fc37.x86_64
Remote OS version: Linux x64 6.1.11-200.fc37.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7500 CPU @ 3.40GHz (4 x 3698)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|4, 4, 2|
|Memory (System)|15.58GB (6.50GB free)|
|Process Argv|--unity-launch --crash-reporter-id 0d4a4e1e-81ee-4def-ac2c-c37094063126|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|gnome-xorg|
|XDG_CURRENT_DESKTOP|GNOME|
|XDG_SESSION_DESKTOP|gnome-xorg|
|XDG_SESSION_TYPE|x11|

|Item|Value|
|---|---|
|Remote|Dev Container: Ubuntu|
|OS|Linux x64 6.1.11-200.fc37.x86_64|
|CPUs|Intel(R) Core(TM) i5-7500 CPU @ 3.40GHz (4 x 3600)|
|Memory (System)|15.58GB (6.50GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|Dev Container: Existing Dockerfile|
|OS|Linux x64 6.1.11-200.fc37.x86_64|
|CPUs|Intel(R) Core(TM) i5-7500 CPU @ 3.40GHz (4 x 3599)|
|Memory (System)|15.58GB (6.51GB free)|
|VM|0%|
</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
jupyter-keymap|ms-|1.0.0
remote-containers|ms-|0.275.1
remote-ssh|ms-|0.96.0
remote-ssh-edit|ms-|0.84.0
remote-wsl|ms-|0.75.3
vscode-remote-extensionpack|ms-|0.24.0
remote-explorer|ms-|0.2.0
remote-server|ms-|1.0.0
pdf|tom|1.2.2
dart-code|Dar|3.58.0
flutter|Dar|3.58.0
code-spell-checker|str|2.16.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
azure-dev_surveyone:30548225
vscccc:30610679
pyindex848:30662994
nodejswelcome1:30587005
282f8724:30602487
pyind779cf:30662993
89544117:30613380
pythonsymbol12:30657548
a9j8j154:30646983
6233i204:30664135

```

</details>

**Comment by devorient** [comment]
Issue seems to be solved in
Version: 1.76.0-insider
Commit: dc619de8d9efdabd781fc5658d0051813c347055
Date: 2023-02-16T05:24:15.383Z
Electron: 19.1.9
Chromium: 102.0.5005.194
Node.js: 16.14.2
V8: 10.2.154.23-electron.0
OS: Linux x64 6.1.11-200.fc37.x86_64
Sandboxed: Yes

**Comment by ulrichSchreiner** [comment]
hi,

exactly same problem, downgrading helps. did not try insiders.
