### ISSUE TITLE
Install failing with Access denies; windows 11 enterprise; Redmond domain.

### ISSUE THREAD

**Issue by simontonmark** [microsoft/vscode#174692]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: x64-1.75.1
- OS Version: Windows 11, 22H2, 22621.1265

Steps to Reproduce:

1. setup new computer with windows 11
2. install visual studio (works fine)
3. attempt to install visual studio Code; either from downloaded exe or from windows app store
4. Result Access denied, see attached bmp.
5. I would include an install log, if I knew where it was stored.

**Comment by simontonmark** [comment]
![vs-code-install-fail-access-denied-20230217_082415](https://user-images.githubusercontent.com/125680862/219709993-b3f8ff54-7035-4db3-a3b8-414f59e1e7c5.png)
System Information report written at: 02/17/23 08:19:28
System Name: DESKTOP-FT75519
[System Summary]

Item	Value	
OS Name	Microsoft Windows 11 Enterprise	
Version	10.0.22621 Build 22621	
Other OS Description 	Not Available	
OS Manufacturer	Microsoft Corporation	
System Name	DESKTOP-FT75519	
System Manufacturer	HP	
System Model	HP ZBook Fury 15 G7 Mobile Workstation	
System Type	x64-based PC	
System SKU	9VS26AV	
Processor	Intel(R) Core(TM) i7-10850H CPU @ 2.70GHz, 2712 Mhz, 6 Core(s), 12 Logical Processor(s)	
BIOS Version/Date	HP S92 Ver. 01.11.00, 10/14/2022	
SMBIOS Version	3.2	
Embedded Controller Version	22.76	
BIOS Mode	UEFI	
BaseBoard Manufacturer	HP	
BaseBoard Product	8783	
BaseBoard Version	KBC Version 16.4C.00

**Comment by simontonmark** [comment]
I am not sure why this was the case.  I went to uninstall visual studio and saw that vs code  was at least partially installed, so I uninstalled it and then tried the install and it worked.  I still don't have a root cause of why the install failed  multiple times this week but it worked once today.

Thanks

**Comment by joaomoreno** [comment]
Happy to know you're unblocked.
