### ISSUE TITLE
Comments API - How can `author.iconPath` reference a file bundled with the extension?

### ISSUE THREAD

**Issue by gjsjohnmurray** [microsoft/vscode#174690]
At https://github.com/gjsjohnmurray/vscode-extension-samples/tree/show-iconpath I have created a branch in which the comment-sample example has been amended to set the `author` property of the comments it adds.

Here are the lines that create the `author` object:

https://github.com/gjsjohnmurray/vscode-extension-samples/blob/e0da92cfdf830988616b7f5f2a905ae0054fa4f4/comment-sample/src/extension.ts#L23-L27

![image](https://user-images.githubusercontent.com/6726799/219707721-2de25f2b-38fe-4011-aa29-71a4d2857efd.png)

The commented-out one was my original, but when running on Desktop the console of devtools reported that the `file:` resource wasn't allowed. After digging through sources I found how to make it work on that platform by using the `vscode-file` scheme.

But this doesn't work when running on Codespaces.

What must I set `iconPath` to so the icon appears when running on that platform too?

Version: 1.76.0-insider
Commit: dc619de8d9efdabd781fc5658d0051813c347055
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/110.0
Embedder: codespaces

**Comment by alexr00** [comment]
Thanks for finding this! Full details on the bug are in https://github.com/microsoft/vscode/pull/174751#issuecomment-1443790117.
