### ISSUE TITLE
Node

### ISSUE THREAD

**Issue by tonywatson-github** [microsoft/vscode#174642]
Type: <b>Bug</b>

Hello, when I try to console.log i get the error code 'node' is not recognized as an internal or external command, operable program or batch file."

How do I fix this? Thank you

VS Code version: Code 1.75.1 (441438abd1ac652551dbe4d408dfcec8a499b8bf, 2023-02-08T21:32:34.589Z)
OS version: Windows_NT x64 10.0.19044
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-3240 CPU @ 3.40GHz (4 x 3392)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: unavailable_off<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: unavailable_off<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|7.94GB (4.51GB free)|
|Process Argv|--crash-reporter-id 91c44100-5040-42f6-9423-3cab0293ccda|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (44)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-javascript-snippet-pack|aka|0.1.6
java-run|cao|1.1.4
vscode-standardjs-snippets|cap|0.9.0
vscode-standardjs|che|1.4.1
npm-intellisense|chr|1.4.4
path-intellisense|chr|2.8.4
vscode-eslint|dba|2.4.0
javadebugger|don|0.1.5
java-debug|DSn|0.0.2
gitlens|eam|13.2.0
EditorConfig|Edi|0.16.4
vscode-npm-script|eg2|0.3.29
code-runner|for|0.12.0
copilot|Git|1.73.8685
npm|ide|1.3.0
search-node-modules|jas|1.3.0
node-module-intellisense|jhe|1.6.0
vscode-npm-scripts|jia|0.2.4
node-module-intellisense|lei|1.5.0
nodejs-repl|los|0.5.15
vscode-language-babel|mgm|0.0.36
vscode-exec-node|mir|0.5.5
vscode-docker|ms-|1.23.3
isort|ms-|2022.8.0
python|ms-|2023.2.0
vscode-pylance|ms-|2023.2.30
jupyter|ms-|2023.1.2010391206
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.14
vscode-jupyter-cell-tags|ms-|0.1.6
vscode-jupyter-slideshow|ms-|0.1.5
js-atom-grammar|ms-|0.1.14
indent-rainbow|ode|8.3.1
vscode-javascript-booster|sbu|14.0.1
code-spell-checker|str|2.16.0
vscode-npm-scripts|tra|0.2.1
vscode-java-debug|vsc|0.48.0
vscode-java-dependency|vsc|0.21.1
vscode-java-test|vsc|0.37.1
vscode-maven|vsc|0.40.4
nodejs-extension-pack|wad|0.1.9
Javascript-extension-pack|wal|1.0.0
JavaScriptSnippets|xab|1.8.0
vscode-java-saber|You|0.1.2

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vscaac:30438847
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
azure-dev_surveyone:30548225
vscccc:30610679
pyindex848:30662994
nodejswelcome1cf:30587006
282f8724:30602487
pyind779cf:30662993
f6dab269:30613381
pythonsymbol12:30657548
vsccsb:30662443
vscodedisable:30660115

```

</details>

**Comment by roblourens** [comment]
You need to make sure that node is installed and is on your path
