### ISSUE TITLE
Process explorer window state is not restored properly

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#174660]
When you open process explorer, change its size, close it and then reopen, the size is not properly restored (tested on a macBookPro laptop).

![Recording 2023-02-22 at 08 58 23](https://user-images.githubusercontent.com/900690/220558101-335c9727-2707-4eec-b2b4-4af177f33d59.gif)

**Comment by bpasero** [comment]
This really annoys me a ton having to use the process explorer. I suggest to revert the change that introduced this.

**Comment by bpasero** [comment]
I figured this was due to the scale factor division and opened https://github.com/microsoft/vscode/pull/175085 to remove that. We do not use this for normal workbench windows, so I doubt we need to use this at all.

However, seeing through the code, I notice that the code in `windowImpl` for dealing with window state should be extracted into something the process explorer can reuse to ensure the window never falls out of the visible display.

**Comment by Tyriar** [comment]
Closing as #175085 fixed the problem for @bpasero and bounds are already checked here:

https://github.com/microsoft/vscode/blob/1135225e4da567ecb8b8543c6ea8f5b98bdf0f3c/src/vs/platform/issue/electron-main/issueMainService.ts#L420-L447

The dimensions of the window do change for me, but only when the process explorer changes monitors that differ in density once, which isn't a big deal.
