### ISSUE TITLE
Scrollable notebook output

### ISSUE THREAD

**Issue by amunger** [microsoft/vscode#174637]
Refs: https://github.com/microsoft/vscode-jupyter/issues/4406

- [x] anyOS @isidorn
- [x] anyOS @joyceerhl
- [x] anyOS @connor4312

Complexity: 4

[create issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23174637%0A%0A&assignees=amunger)

---

There are a few known issues already, but we are looking for any feedback on the look and feel of this feature before introducing it more broadly.

known issues:
[Scrollable notebook output does not reveal find results correctly](https://github.com/microsoft/vscode/issues/174633)
[notebook Error output is not scrollable](https://github.com/microsoft/vscode/issues/174634)
[maximum limit message should not be within the scrollable region](https://github.com/microsoft/vscode/issues/174635)
[scrollable output region keeps resetting scroll position](https://github.com/microsoft/vscode/issues/174636)

1. set `"notebook.experimental.outputScrolling": true`
2. Create a new notebook file
3. Run a few cells with large outputs
4. Play around with different combinations of related settings (might require reloading vs code): `notebook.output.textLineLimit`, `notebook.output.wordWrap`, `notebook.outputLineHeight`

Try on insiders.vscode.dev as well by either:
re-opening that same noteboook with output
or
Start up a jupyter server from a command prompt to provide kernels
    1. `python -m pip install jupyter`
    2. `python -m jupyter notebook --no-browser --NotebookApp.allow_origin=*`
    3. copy the URL that the previous command provides and
    4. open a notebook -> select kernel -> existing Jupyter Server -> paste the URL from step 3

**Comment by Linusnie** [comment]
great that this is being implemented! One feature I'm missing from jupyterlab is being able to toggle scrolling no/off for a specific cell using a keyboard shortcut

Specifically, for jupyterlab I have the following in the keyboard shortcuts json:
```
        {
            "args": {},
            "command": "notebook:enable-output-scrolling",
            "keys": [
                "S"
            ],
            "selector": ".jp-Notebook:focus"
        },
        {
            "args": {},
            "command": "notebook:disable-output-scrolling",
            "keys": [
                "Alt S"
            ],
            "selector": ".jp-Notebook:focus"
        },
```
example when using it:
![scrolling](https://user-images.githubusercontent.com/12471058/219864991-f2186a3c-f8b1-4b9b-9382-fc4bd88ad58e.gif)

**Comment by isidorn** [comment]
Nice job. Feels like we are moving in the right direction. I would be happy to try it out again once we address some of the bugs :) Thanks
