### ISSUE TITLE
Cannot run task of type "process"

### ISSUE THREAD

**Issue by cathalmchale** [microsoft/vscode#174674]
Type: <b>Bug</b>

I can see the warning:
"Warning: process tasks are unavailable in the current environment"

I have no doubt that this is some stupid security policy introduced by my organization that is causing this (and if I run VSCode as an Administrator, I no longer get this warning and process tasks run fine).

However, the reason I'm reporting the issue is that I'm finding that if I run another task e.g. a task of type "docker-build", that's sufficient to get VSCode to launch the "tasks" terminal process. And once this is launched, then the tasks of type "process" will run fine (even when I'm not running as an Administrator).
So I wonder if VSCode executed things in a different order or front-loaded the tasks terminal window in some way, could this avoid the issue for Windows users with similar organization security policies in place?

VS Code version: Code 1.75.1 (441438abd1ac652551dbe4d408dfcec8a499b8bf, 2023-02-08T21:32:34.589Z)
OS version: Windows_NT x64 10.0.19044
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.85GB (2.29GB free)|
|Process Argv|C:\\dev\\ccace\\Microservices --crash-reporter-id 6b6f5016-4aed-4bb2-96fe-2e0bcbbf0bff|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (20)</summary>

Extension|Author (truncated)|Version
---|---|---
clipboard-history|Anj|1.0.7
vscode-csharp-snippets|jor|1.1.0
rainbow-csv|mec|3.5.0
dotenv|mik|1.0.1
azure-pipelines|ms-|1.208.0
vscode-azurefunctions|ms-|1.10.2
vscode-azureresourcegroups|ms-|0.5.6
vscode-docker|ms-|1.23.3
csharp|ms-|1.25.4
isort|ms-|2022.8.0
python|ms-|2023.2.0
vscode-pylance|ms-|2023.2.30
vscode-jupyter-cell-tags|ms-|0.1.6
vscode-jupyter-slideshow|ms-|0.1.5
remote-wsl|ms-|0.75.3
azure-account|ms-|0.11.3
powershell|ms-|2023.1.0
vscode-octopusdeploy|Oct|0.1.4
vscode-nuget-gallery|pat|0.0.24
code-spell-checker|str|2.16.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
azure-dev_surveyone:30548225
pyindex848:30662994
nodejswelcome1:30587005
282f8724:30602487
pyind779cf:30662993
f6dab269:30613381
pythonsymbol12:30657548
a9j8j154:30646983
vsccsb:30662443
vscodeenable:30660116

```

</details>

**Comment by Spitfire1900** [comment]
I also get "Warning: process tasks are unavailable in the current environment."

Sometimes my User defined tasks are not listed, other times they are. Usually my workspace tasks are not listed.

Commenting and uncommentating tasks inside the workspaces tasks.json will resolve the issue until the next reload of VSCode and listings of both workspace and user tasks are restored.

**Comment by rstackhouse** [comment]
> Commenting and uncommentating tasks inside the workspaces tasks.json will resolve the issue until the next reload of VSCode and listings of both workspace and user tasks are restored.

Thanks, you're a genius. This got me unstuck this morning.

**Comment by Spitfire1900** [comment]
Good to hear @rstackhouse . Unfortunately my technique is a hacky workaround and does not fix things like tasks that you want to run consistently at workspace activation.

**Comment by auspex** [comment]
Interestingly, I think, the only time I've seen this (on Ubuntu Linux 22.04, Code 1.77.1) was after reopening a workspace after reboot, in which I had previously had a temp file opened (so, of course, the file no longer existed). This would seem likely to match @cathalmchale 's belief that it's their security policy — some file is not openable either because of permissions or just non-existence.

**Comment by Spitfire1900** [comment]
I've reproduced this on Windows:

1. Have a valid file open,
2. Confirm User defined tasks are showing up correctly
3. `Ctrl+Shift+P` -> `Developer: Reload Window`

Expected outcome: User defined tasks appear in list when running `Ctrl+Shift+P` ->`Tasks: Run Task`

Actual outcome: User defined tasks are missing and the message `Warning: process tasks are unavailable in the current environment.` appears in the `Tasks` Output log.

Hacky workaround:

1. `Ctrl+Shift+P` -> `Tasks: Open User Tasks`
2. `Ctrl+A`  to select all, `Ctrl+/` to comment out all; then Save.
3. `Ctrl+Z` to Undo; then Save. Task list is restored

**Comment by cathalmchale** [comment]
Bit of a mess this one. VSCode becomming a bit of a hindrance to development at the minute.
Other issues that I've notice that appear to be related:

Always getting this warning in Output (Tasks):
"Warning: process tasks are unavailable in the current environment."

When I attempt to Launch a dotnetclr debugger, which has a preLaunchTask that looks like this:

{
	"label": "build",
	"command": "dotnet",
	"type": "process",
	"args": [
		"build",
		"${workspaceFolder}/services/MySolution.sln",
		"/property:GenerateFullPaths=true",
		"/consoleloggerparameters:NoSummary"
	],
	"problemMatcher": "$msCompile"
}

I can see the task terminal spit out the command:

Executing task: dotnet build /property:GenerateFullPaths=true /consoleloggerparameters:NoSummary

So clearly it's struggling with the arg "${workspaceFolder}/services/MySolution.sln" and just skips it. So not resolving ${workspaceFolder}?

So I manually execute the build tasks in a terminal myself (dotnet clean, restore, build etc.), then Launch the debugger and choose "Launch anyway" when it reports an error, and I can see the following in the Debug Console:

Unable to submit event Now listening on: {address}
Unable to submit event Application started. Press Ctrl+C to shut down.
Unable to submit event Hosting environment: {envName}
Unable to submit event Content root path: {contentRoot}

**Comment by Spitfire1900** [comment]
@meganrogge is there documentation or additional logging we can enable to interrogate why the message `"Warning: process tasks are unavailable in the current environment."` is appearing?

**Comment by cathalmchale** [comment]
> Bit of a mess this one. VSCode becomming a bit of a hindrance to development at the minute. Other issues that I've notice that appear to be related:
> 
> Always getting this warning in Output (Tasks): "Warning: process tasks are unavailable in the current environment."
> 
> When I attempt to Launch a dotnetclr debugger, which has a preLaunchTask that looks like this:
> 
> { "label": "build", "command": "dotnet", "type": "process", "args": [ "build", "${workspaceFolder}/services/MySolution.sln", "/property:GenerateFullPaths=true", "/consoleloggerparameters:NoSummary" ], "problemMatcher": "$msCompile" }
> 
> I can see the task terminal spit out the command:
> 
> Executing task: dotnet build /property:GenerateFullPaths=true /consoleloggerparameters:NoSummary
> 
> So clearly it's struggling with the arg "${workspaceFolder}/services/MySolution.sln" and just skips it. So not resolving ${workspaceFolder}?
> 
> So I manually execute the build tasks in a terminal myself (dotnet clean, restore, build etc.), then Launch the debugger and choose "Launch anyway" when it reports an error, and I can see the following in the Debug Console:
> 
> Unable to submit event Now listening on: {address} Unable to submit event Application started. Press Ctrl+C to shut down. Unable to submit event Hosting environment: {envName} Unable to submit event Content root path: {contentRoot}

UPDATE so that it doesn't cause confusion. I was wrong about the tasks.json not picking up the ${workspaceFolder}. I was getting caught out by [Task auto-detection](https://code.visualstudio.com/docs/editor/tasks#_task-autodetection) here. But the rest of it is valid - the debugger is failing to "launch externally" because of the error reported in the debug console:

Unable to submit event Now listening on: {address} 
Unable to submit event Application started. Press Ctrl+C to shut down. 
Unable to submit event Hosting environment: {envName} 
Unable to submit event Content root path: {contentRoot}

I can't say whether the issues are related, but two startements that are true:

1. This all used to work just fine.
2. Running VSCode as an administrator removes the warning: "Warning: process tasks are unavailable in the current environment."

**Comment by Spitfire1900** [comment]
@meganrogge , I've reproduced part of this issue with version 1.80.1

Continuing to see the warning in the `Tasks Output`:
> "Warning: process tasks are unavailable in the current environment"

and process tasks specified in `%APPDATA%\Code\User\tasks.json` are not appearing when selecting `Tasks: Run Task` from the "Show All Command" panel until you perform the workaround specified here https://github.com/microsoft/vscode/issues/174674#issuecomment-1520560613

**Comment by meganrogge** [comment]
Not surprising that you've reproduced with that version. Pls try insider's, where this issue should be fixed @Spitfire1900

**Comment by Spitfire1900** [comment]
Thanks @meganrogge. Is there docs on how to check whether a commit is in insiders vs GA vs not yet released?
