### ISSUE TITLE
Opening vscode.dev should not require a browser reload to update marketplace built-in extensions

### ISSUE THREAD

**Issue by alexdima** [microsoft/vscode#174682]
* visit `vscode.dev`
* (wait 1 month)
* visit `vscode.dev` again
* all extensions should be up-to-date and they should not require a browser reload

![image](https://user-images.githubusercontent.com/5047891/219692337-1317f000-e748-49f0-b192-36ef4ef31cf7.png)

**Comment by sandy081** [comment]
Implemented this support for additional builtin extensions.

**Comment by eamodio** [comment]
@sandy081 this issue affects all extensions, but it sounds like the fix is this only for built-in extensions? Is that true?
