### ISSUE TITLE
“contains emphasized items " Suspended on the folder, unable to right-click and open the right-click menu

### ISSUE THREAD

**Issue by itzj86** [microsoft/vscode#174647]
“contains emphasized items " Suspended on the folder, unable to right-click and open the right-click menu 
![image](https://user-images.githubusercontent.com/5669477/219537224-d195ac0d-881a-48b6-a6c2-d7a53c8091b9.png)

![image](https://user-images.githubusercontent.com/5669477/219537426-c1d0025f-9cc6-41cd-ac48-3dd45ac951db.png)

**Comment by gjsjohnmurray** [comment]
A fix in the Explorer tooltip area will be coming in today’s Insiders. When that lands please retest your scenarios.

**Comment by aurelienbobenrieth** [comment]
@gjsjohnmurray 
Was the update released ?

I have the same issue and just re-downloaded vs code insiders.

I have many tooltip as the one described above and it is really a pain. I cannot scroll, I cannot right-clikc etc... 
I dont not only have the "contains emphaiszed items" I have others tooltip as well.

Basically I would like to disable them all as they are completly useless and a pain in my daily use.

**Comment by gjsjohnmurray** [comment]
I understand there have been build problems today, and the team hasn't yet managed to publish a new Insiders. It's being worked on.

**Comment by Dovernh** [comment]
Agreed, it is more than just the emphasized tooltip. I have been running into it trying to rename/move/delete files.

**Comment by aurelienbobenrieth** [comment]
It's been some days I guess.
And it is more present in some repos than others.
For example I have tooltip for files or directories containing eslint issues and such so it can be really bothering.

**Comment by lramos15** [comment]
Is today's insiders working properly for you now?

**Comment by aurelienbobenrieth** [comment]
@lramos15 It seems the issues disappeared ! 
Thank you very much !
