### ISSUE TITLE
Test: terminal accessible buffer improvements

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#174625]
Refs https://github.com/microsoft/vscode/issues/174079

- [x] Windows @devinvalenciano 
- [x] macOS @aiday-mar 
- [x] Linux @roblourens 

Complexity: 3

Authors: @meganrogge, @Tyriar 

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23174625%0A%0A&assignees=meganrogge,Tyriar)

---

Last iteration, we introduced the terminal accessible buffer for screen reader users (`editor.accessibilitySupport: on`). 

We've improved upon this by using a `monaco-editor` element. Test via the keybinding `Shift+Tab` with and without accessibility support on. Use a screen reader to verify that you can read the contents of the terminal via arrow keys.

**Comment by roblourens** [comment]
I'm not sure how this is expected to be used, but it seems like it could do something to indicate output vs the command. I just have a flat editor and I might not know exactly where each command is.

Also, this is totally unrelated, but the setting `editor.accessibilitySupport` used to be specific to the editor, then we started using it in other places, now it feels like it should be `workbench.accessibilitySupport` or something instead

**Comment by meganrogge** [comment]
@roblourens we have deferred that #174079 and yeah that's a good point, but could really mess with people to change it
