### ISSUE TITLE
Test: QuickPickItem tooltip

### ISSUE THREAD

**Issue by TylerLeonhardt** [microsoft/vscode#174699]
Refs: #174473

- [x] anyOS: @DonJayamanne (or give to @rebornix... either way, please test from an extension)
- [x] anyOS @hediet (using Core quickpick API)

Complexity: 4

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23174699%0A%0A&assignees=TylerLeonhardt)

---

This iteration we have introduced the ability for quick pick items to have tooltips:
![image](https://user-images.githubusercontent.com/2644648/219719524-f27300e3-cb54-4457-9761-bcdf99a4fb90.png)
> A make believe usecase of the Command Palette showing the extension that contributed the command

#### Prereqs

* If you're testing from an extension, pull in the proposed API: https://github.com/microsoft/vscode/blob/0b89e361f50d959448b99943af827ea30e0f6205/src/vscode-dts/vscode.proposed.quickPickItemTooltip.d.ts#L14 
* If you're testing from Core, find a place in the code that already uses the `IQuickInputService` and just add some code there to play around with the API

For the _Steps_ section below, I want you to try it out in both the "simple" and "complex" API:
* Simple in Core is the [pick](https://github.com/microsoft/vscode/blob/0b89e361f50d959448b99943af827ea30e0f6205/src/vs/platform/quickinput/common/quickInput.ts#L529) API
* Complex in Core is the [createQuickPick](https://github.com/microsoft/vscode/blob/0b89e361f50d959448b99943af827ea30e0f6205/src/vs/platform/quickinput/common/quickInput.ts#L541) API
* Simple in Ext is the `vscode.window.showQuickPick` API
* Complex in Ext is the `vscode.window.createQuickPick` API

#### Steps

Really just play around with the API AND the UX shown... but specifically test out:
* Does the API make sense?
* Does hovering over an item with your mouse show the tooltip?
* Does ctrl+space show the tooltip? - this works similarly to the suggest widget so try that out
* Add a markdown link in the tooltip. Can you tab over to it?

Have ideas of where this could be used? Open issues on that so we collect ideas!

**Comment by hediet** [comment]
Does not seem to work with monaco editor:

https://microsoft.github.io/monaco-editor/playground.html?source=v0.36.0-dev.20230221#XQAAAALvAgAAAAAAAABBqQkHQ5NjdMjwa-jY7SIQ9S7DNlzs5W-mwj0fe1ZCDRFc9ws9XQE0SJE1jc2VKxhaLFIw9vEWSxW3yscw2oTw2fdL6lWdZifSWhc9gCAnQP7m4UuZTiIrIS9pAX04f3NkJ4AQau3w4ptki3gIWzH16T25difg-USIlgIuHWaQW4UjFBxI-jBU9CCZvEu13dcLUzxHa2RS-cZPn3SUFjJ7GMRNa5TRRLvbbknTUUPnGnxar4EkxtMcz3UWzcPw7gwPrXA2ETDLZD6pzubVK4cRDgrJ-nQDGEGSznsdtWADDS76FtsSvadmrN2k6HKqxxAJifVZ9_y18H8iBaHxJeXQIlCfrGMw4UcJLViU6ZOWTXo2r5jcGb6eBiWWzHQkbRWLgLpEeGEEX2mMNqXcX66uxk6kXUMbzHaazjocZTM48Yb0ghedAGBgg8MBo7-my6v31YX-oznM2BHhLx4xcXvZt-Er7NN6AfB4eVUFXikzJnyQkRObpprGjjsT7VGpm4nnjz7-yY8jQy3GXiKxfETPEHA8xDoP5VCuJRF9r3jrsGpDAVlLPBFDRZM17BR1t39a-I5DbygpV9e4DMS2OceRGge4dtGFH7aSJMLV7_fmZHcJDxxfKP-34NC2

**Comment by DonJayamanne** [comment]
Found one issue https://github.com/microsoft/vscode/issues/175004
