### ISSUE TITLE
Fresh install of VS Code in windows is creating an empty extensions.json file in extensions dir

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#174695]
Extracted from https://github.com/microsoft/vscode/issues/174479#issuecomment-1433434792

1. Install vscode on windows without opening it.
2. Open WSL command line (Ubuntu 22.04 LTS)
3. Go to a random project, in my case, it's a newly created nestjs project with the nest CLI
4. run `code .`

I can repro it but not consistently.

**Comment by sandy081** [comment]
@bpasero Can I please have your help here. I am not able to figure out who is creating this `extensions.json` file with empty content in our product.

**Comment by bpasero** [comment]
I am not sure how I could help, I am not even aware of what the file `extensions.json` does? Did you try full text search who creates it? Does it reproduce out of sources? Then you could throw or add a breakpoint in the disk file system provider.

**Comment by sandy081** [comment]
> I am not even aware of what the file extensions.json does?

It is the file that contains the list of installed extensions. VS Code reads this file to know what are the installed extensions for the default profile.

> Did you try full text search who creates it? 

Yes and in those places where it is being used, they are not creating the file with empty contents. During the start up, this file is initialised in the following code

https://github.com/microsoft/vscode/blob/b1dc961b977c3c4417b3ba3bd87a5d1dcb71c2bb/src/vs/platform/extensionManagement/common/extensionsScannerService.ts#L297

But before running this code, I record some log statements. When I repro this, I do not see these log statement implying that this code is not running.

> Does it reproduce out of sources? 

Not in MacOS. I did not try it in windows. I could repro it only in Windows with insider bits.

**Comment by sandy081** [comment]
I can reproduce only with stable bits and only with WSL. 
With insiders, I cant repro.

**Comment by bpasero** [comment]
Btw from the standup discussion, what could explain an empty file is if somehow the write fails half-way: that is, if the `truncate` succeeds but then the following `write` fails. I am not aware of how this issue could happen though unless there is literally a native crash or OS shutdown right in the middle of the operation. Maybe its more likely if multiple processes write to the same file at the same time, but even that I have never seen so far as an issue.

Windows has a nice tool to log all file operations and even allows to filter by path: https://learn.microsoft.com/en-us/sysinternals/downloads/procmon
