### ISSUE TITLE
[Feature request] SSH Integrated terminal

### ISSUE THREAD

**Issue by JMCA2** [Microsoft/vscode#17466]
It would be very useful if VS Code included a SSH terminal.

It would make remote developing easier.

This was one of the most requested features on [UserVoice with ~500 votes](https://visualstudio.uservoice.com/forums/293070-visual-studio-code/suggestions/8589946-add-ftp-sftp-and-ssh-file-transfer-capability-to).

Related to: #13643

**Comment by schelhorn** [comment]
Just install the new OpenSSH for Windows and call its `ssh` binary from the integrated terminal in VS Code. That works just fine.

**Comment by cleidigh** [comment]
@kieferrm 
Working on a related SS each issue, saw this.  Assuming it is unlikely to include a separate client, and the above suggestion works, would this be a good candidate for a recipe?

**Comment by mklemarczyk** [comment]
Regarding the call for outside program. VS Code not support remote ssh session in that matter. It starts the terminal shell at beginning of each task so it is always called locally. There is workaround to create i it script for shell app but it need to be modified each time to change remote machine.

**Comment by Tyriar** [comment]
We just announced remote development with VS Code, check out the blog post for details https://code.visualstudio.com/blogs/2019/05/02/remote-development
