### ISSUE TITLE
[bug] Weird text rendering issues on Ubuntu

### ISSUE THREAD

**Issue by mrnossiom** [microsoft/vscode#174613]
Hi there,
My VS Code app behaves weird for rendering any character in certain circumstances, it mainly happens when I edit a filename. Usually, the whole file explorer is glitching, but when I tried today it only glitched a few filenames. Moreover, is seems to glitch out only git tracked files (one with a color for adding, deleting or modifying a file)
I have no idea why this is happening. I've tried searching the GitHub repository for similar issues, but can't find any.
I'm running the latest VS Code (1.75.0), installed via the official Microsoft apt repository.

I'm at your disposal to provide any further information that might help, and will be grateful to anyone who responds.

Thanks

NB: I've attached a screenshot where the visual glitch is clearly visible, as you can see on the two files in the examples' folder.

![image](https://user-images.githubusercontent.com/43814157/219464082-ab38fe84-2b91-4eb7-82f6-16ba308cbe9f.png) ![image](https://user-images.githubusercontent.com/43814157/219464100-9dbdc9f5-cf10-462b-b48f-07acf0351336.png) ![image](https://user-images.githubusercontent.com/43814157/219464126-3a1e92c1-87ea-47ea-9be3-d1c18b945ec1.png)

Does this issue occur when all extensions are disabled?: Yes

VS Code version: Code 1.75.1 (441438abd1ac652551dbe4d408dfcec8a499b8bf, 2023-02-08T21:35:30.018Z)
OS version: Linux x64 5.19.0-31-generic
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|12th Gen Intel(R) Core(TM) i7-1260P (16 x 997)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|2, 2, 2|
|Memory (System)|15.26GB (8.08GB free)|
|Process Argv|--unity-launch --crash-reporter-id 639b817d-9a19-4ab4-a721-8b89c47d08b7|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|regolith|
|XDG_CURRENT_DESKTOP|Regolith:GNOME-Flashback:GNOME|
|XDG_SESSION_DESKTOP|regolith|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (58)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-ron|a5h|0.10.0
better-comments|aar|3.0.2
retypewriter|ant|0.1.3
slidev|ant|0.4.1
where-am-i|ant|0.2.0
language-mcfunction|arc|0.18.0
shell-syntax|bma|1.0.3
vscode-fish|bma|1.0.31
vscode-github-actions|csc|0.24.4
doxdocgen|csc|1.4.0
gitlens|eam|13.2.0
prettier-vscode|esb|9.10.4
codespaces|Git|1.13.8
copilot|Git|1.73.8685
copilot-labs|Git|0.9.668
vscode-pull-request-github|Git|0.58.1
vscode-graphql-syntax|Gra|1.0.6
todo-tree|Gru|0.0.224
dummytextgenerator|gur|1.0.1
discord-vscode|icr|5.8.0
language-julia|jul|1.38.2
tera|kar|0.0.9
vrl-vscode|luc|0.1.4
caddyfile-support|mat|0.2.4
template-string-converter|meg|0.6.0
remote-containers|ms-|0.275.1
remote-ssh|ms-|0.96.0
remote-ssh-edit|ms-|0.84.0
hexeditor|ms-|1.9.11
remote-explorer|ms-|0.2.0
vsliveshare|ms-|1.0.5831
vscode-ebnf|OMK|1.0.5
subtitles-editor|pep|1.1.7
prisma|Pri|4.10.1
vscode-commons|red|0.0.6
vscode-xml|red|0.24.0
vscode-yaml|red|1.11.0
rust-analyzer|rus|0.3.1402
bash-beautify|sha|0.1.1
markdown-preview-enhanced|shd|0.6.7
vscode-spotify|shy|3.2.1
svg-preview|Sim|2.8.3
just|ske|2.0.0
code-spell-checker|str|2.16.0
code-spell-checker-french|str|0.2.6
vscode-stylelint|sty|1.2.4
even-better-toml|tam|0.19.0
tldraw-vscode|tld|1.27.0
pdf|tom|1.2.2
vscode-mdx|uni|1.2.1
errorlens|use|3.7.0
vscodeintellicode|Vis|1.2.30
vscode-icons|vsc|12.2.0
gistfs|vsl|0.4.1
vscode-wakatime|Wak|24.0.6
quokka-vscode|Wal|1.0.525
vscode-import-cost|wix|3.3.0
markdown-all-in-one|yzh|3.5.0

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vscaat:30438848
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
pynewext54:30660299
azure-dev_surveyone:30548225
vscccc:30610679
pyindex848:30662994
nodejswelcome1:30587005
3biah626:30602489
pyind779:30662992
89544117:30613380
pythonsymbol12:30657548
2i9eh265:30646982
vsctsb:30662444

```

</details>

**Comment by tpacent** [comment]
Having this bug as well on a fresh VSCode install.  
Seen some corrupted text in Settings, though I cannot find/reproduce it right now.

VSCode: 1.77.0 Commit: 7f329fe6c66b0f86ae1574c2911b681ad5a45d63 Date: 2023-03-29T10:05:35.165Z  
Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Code/1.77.0 Chrome/102.0.5005.196 Electron/19.1.11 Safari/537.36

<details><summary>System</summary>
Ubuntu 22.10<br>
Ubuntu 5.19.0-38.39-generic 5.19.17<br>
11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz
</details> 

<details><summary>Screenshot</summary>
<img alt="Screenshot from 2023-04-02 01-07-03" src="https://user-images.githubusercontent.com/76945699/229316535-e89aa76f-0cfb-4995-8642-0f0041ebbcd6.png">
</details>

**Comment by MrNossiom** [comment]
Yes, `@tag:sync` in settings does reproduce for me

**Comment by deepak1556** [comment]
This should get addressed as we update runtime, please disable hardware acceleration in the application as a workaround https://code.visualstudio.com/updates/v1_40#_disable-gpu-acceleration
