### ISSUE TITLE
Map JSON schema URLs to local file

### ISSUE THREAD

**Issue by oliver** [microsoft/vscode#174672]
Is there a way to map some JSON schema URL to a local file?

I have a JSON schema file in my project, and I want VSCode to automatically use that for validating other JSON data files in the same project. I don't want to list all the JSON data files in `fileMatch` entries in my settings.json (because that would be hard to maintain), and rather want to add something like `"$schema": "http://thecompany.com/schemas/foo_project/bar_schema.json"` to each JSON data file.  
But I cannot make that URL resolvable (I cannot put files onto our website); so I'd like to specify somewhere that JSON schema URL `http://thecompany.com/schemas/foo_project/bar_schema.json` should resolve to the `./schemas/bar_schema.json` file in the current project. Is something like this possible?

Or can I specify some catalog file or "catalog service" where the mapping for such schema URLs is configured?

**Comment by IllusionMH** [comment]
> I don't want to list all the JSON data files in fileMatch entries in my settings.json

`fileMatch` already supports wildcards and exclusions. Do you have a lot of different patterns where wildcards won't work?

**Comment by aeschli** [comment]
You can do this:
![image](https://user-images.githubusercontent.com/6461412/220654133-e038a634-a660-486a-bdb7-c8c5aafff2e4.png)

If the file needs to be on disk, you try to use a `$ref``:
```
{
    "json.schemas": [
        {
            "url": "http://foo/bar",
            "schema": {
                "$ref": "file:///c/Users/martin/bar.schema.json"
            }
        }
    ]
}
```

**Comment by oliver** [comment]
@aeschli : nice, thank you very very much! This is exactly what I was looking for!

I guess the key point that I had been missing all the time was that the `$ref` URL must start with `file:///` to reference a local file.

@IllusionMH : I have a few schemas and several JSON files in the project, and the JSON files don't have a naming convention that is useful here. So it would be tedious to maintain the `filesMatch` list.
