### ISSUE TITLE
Taskbar won't show on windows when is set to hide automatically and VS code is full screen

### ISSUE THREAD

**Issue by AbdesamedBendjeddou** [microsoft/vscode#174600]
Type: <b>Bug</b>

The Taskbar won't show up when I'm working on VS code in full screen and the Taskbar is set to hide automatically. When I move the cursor down to where the Taskbar is supposed to show up, it doesn't, I have to switch to another window for it to show up. 

VS Code version: Code 1.75.1 (441438abd1ac652551dbe4d408dfcec8a499b8bf, 2023-02-08T21:32:34.589Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-10600K CPU @ 4.10GHz (12 x 4104)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|23.75GB (11.52GB free)|
|Process Argv|--crash-reporter-id 5999bdf0-2ec2-4b17-9a6a-51568db6db9d|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (21)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|3.0.2
codesnap|adp|1.3.4
project-manager|ale|12.7.0
markdown-preview-github-styles|bie|1.0.1
fastcompare|Dav|1.1.1
font-switcher|eva|4.1.0
vscode-pull-request-github|Git|0.58.1
isort|ms-|2022.8.0
python|ms-|2023.2.0
vscode-pylance|ms-|2023.2.30
remote-wsl|ms-|0.75.3
cmake-tools|ms-|1.13.45
cpptools|ms-|1.14.3
cpptools-extension-pack|ms-|1.3.0
sqltools|mtx|0.27.1
rust-analyzer|rus|0.3.1402
even-better-toml|tam|0.19.0
cmake|twx|0.0.17
vscode-lldb|vad|1.8.1
vscode-icons|vsc|12.2.0
markdown-all-in-one|yzh|3.5.0

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
azure-dev_surveyone:30548225
vsccc:30610678
pyindex848:30662994
nodejswelcome1cf:30587006
3biah626:30602489
pyind779:30662992
89544117:30613380
pythonsymbol12:30657548
vsctsb:30662444

```

</details>

**Comment by meganrogge** [comment]
Not sure what you mean, pls attach a gif

**Comment by AbdesamedBendjeddou** [comment]
I'm unable to replicate the issue, it seems like it resolved after a restart
