### ISSUE TITLE
Windows crash during integration tests

### ISSUE THREAD

**Issue by alexdima** [microsoft/vscode#174661]
https://dev.azure.com/monacotools/Monaco/_build/results?buildId=203401&view=logs&j=0304f796-6596-5b42-8573-3d5da85bc4a5&t=574b17c2-b1f1-5e41-960d-bfabab7a10d6&l=1988

There is a crash dump available.

**Comment by bpasero** [comment]
+ Raymond, since Deepak will be out

**Comment by rzhao271** [comment]
[symbolicated-output.log](https://github.com/microsoft/vscode/files/10771844/symbolicated-output.log)

**Comment by deepak1556** [comment]
Addressed in https://github.com/microsoft/vscode/pull/174808
