### ISSUE TITLE
Can no longer find and replace in selection

### ISSUE THREAD

**Issue by ImadYIdrissi** [microsoft/vscode#174696]
Type: <b>Bug</b>

Cannot use Find and replace **In selection**, `Alt + L` and the button to use the selection isn't here anymore.

![image](https://user-images.githubusercontent.com/19647868/219715999-7157a207-9212-4813-bd8d-77662d800178.png)

In ~any file~ `.ipynb` files (jupyter notebook-like), press `Ctrl + H` and try to find Replace within selection.

VS Code version: Code 1.75.1 (441438abd1ac652551dbe4d408dfcec8a499b8bf, 2023-02-08T21:32:34.589Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: No
Remote OS version: Linux x64 5.15.79.1-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|12th Gen Intel(R) Core(TM) i7-12700H (20 x 2688)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.73GB (0.31GB free)|
|Process Argv|--folder-uri=vscode-remote://wsl+Ubuntu-20.04/home/iyid/workspaces/continuity --remote=wsl+Ubuntu-20.04 --crash-reporter-id d3c39b7c-1458-4d17-80e7-2be632fe62ad|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-20.04|
|OS|Linux x64 5.15.79.1-microsoft-standard-WSL2|
|CPUs|12th Gen Intel(R) Core(TM) i7-12700H (20 x 2688)|
|Memory (System)|15.49GB (12.59GB free)|
|VM|0%|
</details><details><summary>Extensions (37)</summary>

Extension|Author (truncated)|Version
---|---|---
jupyter-keymap|ms-|1.0.0
remote-containers|ms-|0.275.1
remote-ssh|ms-|0.96.0
remote-ssh-edit|ms-|0.84.0
remote-wsl|ms-|0.75.3
sql-bigquery|shi|1.9.0
pdf|tom|1.2.2
vscode-sql-formatter|adp|1.4.4
google-cloud-platform-ssh|and|1.0.0
file-tree-to-text-generator|d-k|1.4.0
vscode-markdownlint|Dav|0.49.0
gitlens|eam|13.2.0
prettier-vscode|esb|9.10.4
selected-lines-count|gur|1.4.0
terraform|has|2.25.2
vscode-dbt-power-user|inn|0.11.5
latex-workshop|Jam|9.7.0
git-graph|mhu|1.30.0
vscode-docker|ms-|1.23.3
vscode-dotnet-runtime|ms-|1.6.0
flake8|ms-|2023.2.0
python|ms-|2023.2.0
vscode-pylance|ms-|2023.2.30
jupyter|ms-|2023.1.2010391206
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.14
vscode-jupyter-cell-tags|ms-|0.1.6
vscode-jupyter-slideshow|ms-|0.1.5
sqltools|mtx|0.27.1
autodocstring|njp|0.6.1
vscode-yaml|red|1.11.0
partial-diff|ryu|1.4.3
jinjahtml|sam|0.20.0
file-tree-generator|Shi|1.1.1
reveal|smu|1.2.7
markdown-all-in-one|yzh|3.5.0
project-tree|zhu|0.3.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
pynewext54:30660299
azure-dev_surveyone:30548225
pyindex848:30662994
nodejswelcome1cf:30587006
3biah626:30602489
pyind779:30662992
f6dab269:30613381
pythonsymbol12cf:30657549
a9j8j154:30646983

```

</details>

**Comment by ArturoDent** [comment]
What is the filter icon doing in your Find widget?  I don't see that in the Insiders or Stable.

**Comment by ImadYIdrissi** [comment]
@ArturoDent, good question.

I just realized this behavior only happens in `.ipynb` files (Jupyter notebook like). The filters you see and the missing` replace in selection` are not an issue in files such as `.md` or `.py`.

**Comment by Yoyokrazy** [comment]
Feature has been shipped in the past, and the in selection button can be used to scope searches to either a cell selection or text selection,
