### ISSUE TITLE
Nested git repository ignored, just treated as part of parent

### ISSUE THREAD

**Issue by ByteEater-pl** [microsoft/vscode#174686]
Does this issue occur when all extensions are disabled?: Yes

I haven't installed any extensions yet. It's a newly installed instance of VS Code. From Microsoft's `deb` repository, not Snap.

- VS Code Version: 1.75.1
- OS Version: Ubuntu Unity 22.04 in VirtualBox

Steps to Reproduce:

1. Have a git repository and another git repository in its subdirectory (not a submodule).
2. Open the parent directory in VS Code.

I see `master` as the branch all the time, regardless of the location of the file I'm trying to edit: the parent directory or the subdirectory. The parent directory is indeed on `master`, but the subdirectory is on `development`. I suspect the `master` branch name shown by VS Code in the status bar refers to the parent directory's branch of that name, not the subdirectory's (which also has one named `master` (more specifically, `origin/master`)), and the fact that the subdirectory also contains a git repository is ignored by VS Code when it has seen an ancestor containing a subdirectory named `.git`.

The solution described in [this comment](https://github.com/microsoft/vscode/issues/37947#issuecomment-1209988677) seems to work, i.e. removing (I changed its name and then changed it back) the parent directory's `.git` subdirectory when none of the directories are opened in VS Code, then opening the parent directory in VS Code (it's then able to find the `.git` subdirectories of subdirectories (presumably multiple, though I believe there's only one in my case)), finally restoring the parent directory's `.git` subdirectory. But I'd like it to be hadled by VS Code. That's what the feature added in 1.72 is supposed to do, IIUC. That way it would be more convenient and reassuring. I feel anxious relying on an officially undocumented workaround, it may be brittle, it sometimes (e.g. starting tomorrow, unbeknownst to me) may also do something else than I think.

**Comment by ByteEater-pl** [comment]
The solution has turn out, unfortunately, to work only temporarily. I shut down the virtual machine, started it again, opened the parent directory in VS Code and what I see is `master` as the branch also in the subdirectory.

**Comment by ByteEater-pl** [comment]
And as for the extensions (there was a question in the template), I've still got 0 installed, but I fathomed maybe I should disable the built-in ones as well. So I did, but the one handling git is among them, so now it doesn't show any branch in the status bar. The more precise question is thus: No.

But maybe you'd better just clarify the template on whether reporters should disable those as well to check.

**Comment by lszomoru** [comment]
@ByteEater-pl, apologies for not getting back to you on this until now. VS Code added support for nested git repositories, even though you might have to adjust the `git.repositoryScanMaxDepth` setting depending on the folder structure of the folder/workspace that you are opening. Could you please share the value of this setting, as well as the exact folder structure? Thanks!

**Comment by ByteEater-pl** [comment]
The value was 1. I've just changed it to -1.

However, the problem was gone a few days after reporting this issue. I don't know if it fixed itself somehow or an update of VS Code did it.

**Comment by lszomoru** [comment]
@ByteEater-pl, apologies for not getting back to you on this until now. Glad to hear that the issue has been resolved. I will go ahead and close this issue but please feel free to reopen it in case it resurfaces. Thanks!
