### ISSUE TITLE
If diffEditor.insertedLineBackground or removedLineBackground is overriden, then you cannot see the cursor selection

### ISSUE THREAD

**Issue by Skarvion** [microsoft/vscode#174644]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.75.1
- OS Version: Windows 10 Pro 21H2

Steps to Reproduce:

1. Go to settings.json and override either insertedLineBackground or removedLineBackground
2. Open a file within a git repository and check the diff
3. Make any changes by adding or removing line
4. Select a removed text or added text. While the cursor selection work, you cannot see the highlighted text

I've tested with both the default and other custom color theme, it seems to occur in all situation. You can see the cursor selection when the color is not overriden

![Screenshot 2023-02-17 130550](https://user-images.githubusercontent.com/17715991/219531029-177a0632-5d82-481e-b453-bb8e273d6fe3.png)

This is another comparison when nothing is selected. The diff lines still have the same color, making it harder to distinguish
![image](https://user-images.githubusercontent.com/17715991/219531231-f6c9898f-9756-4167-89a2-34caccbb3b41.png)

**Comment by alexdima** [comment]
This is because the colors are defined without any transparency. The solution is to use opacity in the colors you define. e.g. `#08310088`. @aeschli Could there be a way to show a squiggle if opacity is not used in some colors?

**Comment by Skarvion** [comment]
Thanks @alexdima . I can confirm setting the opacity lower would show the cursor selection. I can also see the squiggle if opacity is not set.
