### ISSUE TITLE
Incorrect color highlighting for parameter expansion in shell script

### ISSUE THREAD

**Issue by pwalker-mbari** [microsoft/vscode#174627]
Type: <b>Bug</b>

When working on a shell script, if I use parameter expansion to trim content from the front of a variable's value, the color highlighting shows incorrectly.
![Screenshot from 2023-02-16 14-03-31](https://user-images.githubusercontent.com/103715402/219497550-fd9e7bc4-3f79-4798-8e2c-4392f8c86235.png)
When I use parameter expansion like...
```bash
v="${othervar##*foo}"
```
... I would expect VS Code to format my opening and closing curly braces with the same color, and to format any text that follows the variable reference as normal.
Github's code block seems to show the code in a format closer to what I am expecting.

<details>
<summary>VS Code Info</summary>
VS Code version: Code 1.75.1 (441438abd1ac652551dbe4d408dfcec8a499b8bf, 2023-02-08T21:35:30.018Z)<br>
OS version: Linux x64 5.17.0-1027-oem<br>
Modes:<br>
Sandboxed: No<br>
Remote OS version: Linux x64 4.18.0-425.10.1.el8_7.x86_64<br>
</details>
<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|12th Gen Intel(R) Core(TM) i7-1260P (16 x 2500)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|2, 2, 2|
|Memory (System)|31.07GB (16.20GB free)|
|Process Argv|--unity-launch --crash-reporter-id 631f6ba6-2603-4849-931e-13ebb7e3a73f|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|wayland|

|Item|Value|
|---|---|
|Remote|SSH: guardian-pwalker|
|OS|Linux x64 4.18.0-425.10.1.el8_7.x86_64|
|CPUs|Intel(R) Xeon(R) Gold 6142 CPU @ 2.60GHz (14 x 2593)|
|Memory (System)|19.39GB (18.09GB free)|
|VM|100%|
</details><details><summary>Extensions (30)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|3.0.2
systemd-unit-file|coo|1.0.6
auto-close-tag|for|0.5.14
auto-rename-tag|for|0.1.10
vscode-systemd-support|han|1.0.1
compare-helper|kee|1.1.0
eml|lei|0.4.0
jupyter-keymap|ms-|1.0.0
remote-containers|ms-|0.275.1
remote-ssh|ms-|0.97.2023021615
remote-ssh-edit|ms-|0.84.0
remote-wsl|ms-|0.75.3
vscode-remote-extensionpack|ms-|0.23.0
atom-keybindings|ms-|3.3.0
remote-explorer|ms-|0.2.0
material-icon-theme|PKi|4.24.0
material-product-icons|PKi|1.4.1
shellman|Rem|5.6.0
highlight-matching-tag|vin|0.10.1
markdown-checkbox|bie|0.4.0
multi-cursor-case-preserve|Car|1.0.5
gitignore|cod|0.9.0
dakara-foldplus|dak|1.5.2
githistory|don|0.6.19
powershell|ms-|2023.1.0
highlight-counter|ram|1.6.0
partial-diff|ryu|1.4.3
trailing-spaces|sha|0.4.1
shellcheck|tim|0.29.4
sort-lines|Tyr|1.9.1

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
azure-dev_surveyone:30548225
vsccc:30610678
pyindex848:30662994
nodejswelcome1cf:30587006
3biah626:30602489
pyind779:30662992
89544117:30613380
pythonsymbol12cf:30657549

```

</details>

**Comment by alexr00** [comment]
This is fixed in VS Code insiders, where we've adopted a new shell script syntax highlighting grammar.
