### ISSUE TITLE
Font weight, spacing and line height in different than windows terminal

### ISSUE THREAD

**Issue by pwsandoval** [microsoft/vscode#174604]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:  1.75.1
- OS Version: Windows 11 Pro (OS Build 22000.1574)

Steps to Reproduce:

1. Instalé Windows terminal y VS code
2. Uso la terminal bash y powershell en ambos

En Windows terminal solo tengo estas configuraciones básicas

```json
"font": {
    "face": "JetBrainsMono NF",
    "size": 10,
    "weight": "medium",
}
```

Result Windows terminal:

![font wt bash](https://user-images.githubusercontent.com/15174704/219441522-707d05fc-8703-4e29-9c2c-466a5b4a265e.png)
[full image size](https://user-images.githubusercontent.com/15174704/219442868-6c075f1c-d522-442b-921c-52f359d1d530.png)

In vscode with the same settings (font size in px instead of pt):

```json
{
    "terminal.integrated.fontFamily": "JetBrainsMono NF",
    "terminal.integrated.fontSize": 14,
    "terminal.integrated.fontWeight": "normal" //100 is same
}
```

Result VS code:

![font vs bash](https://user-images.githubusercontent.com/15174704/219441532-983f21af-8906-456b-bead-14ddbeefe89c.png)
[full image size](https://user-images.githubusercontent.com/15174704/219442842-3164876d-b728-40a7-ab8b-fff7e57191d8.png)

**The main difference is the font weight, I can't get them to look the same even setting the fontWeight to the minimum**

The letter height and spacing is also a bit different with the default values, but I think I can display it like in Windows Terminal to playing around with the values of terminal.integrated.letterSpacing and terminal.integrated.lineHeight (not sure if this will help you). gives a higher height to the source or just the separation).

But my big problem is that the weight is displayed very differently in VS code (I like how it is displayed in Windows Terminal, that is, I don't want it to be bold) and I don't know how to modify it.

Note. The theme used is similar in both, however the same error happens using default themes.

**Comment by Tyriar** [comment]
VS Code has the `terminal.integrated.fontWeight` and `terminal.integrated.fontWeightBold` settings to tweak this, but we're not aiming to match rendering identically with WT or anything. I believe WT uses a Windows-only engine to render the text, we defer to Chromium to do it by just passing on the font settings to a 2D canvas context.
