### ISSUE TITLE
Automatic loading of Profile per Folder

### ISSUE THREAD

**Issue by jackHedaya** [microsoft/vscode#174620]
Hi! I think it would be a really great supporting feature to allow an option in the `.vscode` folder to automatically enable a VSCode Profile. This would let me open my "Java" Profile when I'm opening on my Java project and my "Web" Profile when I'm working on some JavaScript.

**Comment by sandy081** [comment]
Profiles are associated to the workspace, when you associate them manually to a workspace they stick to them. In addition to this what is your expectation to have an option in .vscode folder?
