### ISSUE TITLE
tooltips in EXLOERER stop nav scrolling

### ISSUE THREAD

**Issue by mindon** [microsoft/vscode#174648]
Type: <b>Bug</b>

1. open EXPLORER
2. scroll with wheel
3. scroll stop if cursor pointer is hover the tooltips "Contains emphasized items"

VS Code version: Code - Insiders 1.76.0-insider (Universal) (dc619de8d9efdabd781fc5658d0051813c347055, 2023-02-16T05:24:03.557Z)
OS version: Darwin arm64 22.3.0
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|2, 3, 3|
|Memory (System)|16.00GB (0.12GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (35)</summary>

Extension|Author (truncated)|Version
---|---|---
xd|ado|1.2.3
zls-vscode|Aug|1.1.8
t-extension|bkd|0.0.4
better-toml|bun|0.3.2
dart-code|Dar|3.58.0
flutter|Dar|3.58.0
vscode-eslint|dba|2.4.0
vscode-deno|den|3.17.0
prettier-vscode|esb|9.10.4
linter-gfortran|for|3.4.2023020701
go|gol|0.37.1
vscode-docker|ms-|1.23.3
vscode-language-pack-zh-hans|MS-|1.75.2023021509
isort|ms-|2022.8.0
python|ms-|2023.2.0
vscode-pylance|ms-|2023.2.30
jupyter|ms-|2023.2.1000481019
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.15
vscode-jupyter-cell-tags|ms-|0.1.6
vscode-jupyter-slideshow|ms-|0.1.5
cpptools|ms-|1.14.3
vscode-react-native|msj|1.10.0
vetur|oct|0.36.1
quantum-devkit-vscode|qua|0.27.253010
ruby|reb|0.28.1
lit-plugin|run|1.2.4
rust-analyzer|rus|0.4.1405
twind-intellisense|sas|0.2.1
markdown-preview-enhanced|shd|0.6.7
just|ske|2.0.0
vscode-ruby|win|0.28.0
wolfram|Wol|1.7.0
vscode-caddyfile-syntax|zam|1.0.4
vscode-proto3|zxh|0.5.5

</details>

**Comment by chrisarts** [comment]
Same for me its very annoyng.

**Comment by yamachu** [comment]
Same for me.
For example, if you focus on a file that is git ignore, the scrolling will be interrupted
<img width="209" alt="スクリーンショット 2023-02-17 14 00 19" src="https://user-images.githubusercontent.com/1955233/219553427-a0eb2993-bbd6-45a9-ab51-ec7acdcca5bb.png">
Also, long file names seem to cause similar problems
<img width="236" alt="スクリーンショット 2023-02-17 14 00 37" src="https://user-images.githubusercontent.com/1955233/219553499-0b64c975-7187-4581-b529-5e45a86de13f.png">

**Comment by gjsjohnmurray** [comment]
A fix in the Explorer tooltip area will be coming in today’s Insiders. When that lands please retest your scenarios.

**Comment by mindon** [comment]
@gjsjohnmurray appreciated it. can't wait for it 👍

**Comment by rzhao271** [comment]
Related issue:
I just tried right-clicking on an entry to create a new folder under it, but then got blocked by the tooltip.

**Comment by lramos15** [comment]
All of these are fixed in the new insiders build that will go out today. However, the new hover is going behind a flag `explorer.experimental.hover` as it still has other issues not mentioned here to work out.
