### ISSUE TITLE
Switching OS appearence should give me respective theme, even if im on an experimental theme

### ISSUE THREAD

**Issue by prophet1996** [microsoft/vscode#174756]
Type: <b>Bug</b>

I'm on experimental theme of VS code and have synced the theme on VScode with OS. When i switch OS theme although it toggles the theme but not to the respective theme.
Expected behaviour - 
Dark Theme --> Light Theme
Dark ThemeV2 --> Light ThemeV2
Current Behaviour - 
Dark Theme --> Light Theme
Dark ThemeV2 --> Light Theme

VS Code version: Code 1.75.1 (441438abd1ac652551dbe4d408dfcec8a499b8bf, 2023-02-08T21:34:01.965Z)
OS version: Darwin arm64 22.2.0
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Max (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|7, 8, 7|
|Memory (System)|32.00GB (3.83GB free)|
|Process Argv|--crash-reporter-id 2e44c56f-e4c9-4369-a8ba-d33bfcbd38b2|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (17)</summary>

Extension|Author (truncated)|Version
---|---|---
zls-vscode|Aug|1.1.8
vscode-tailwindcss|bra|0.9.7
better-toml|bun|0.3.2
npm-intellisense|chr|1.4.4
vscode-eslint|dba|2.4.0
gitlens|eam|13.2.0
prettier-vscode|esb|9.10.4
remote-containers|ms-|0.275.1
vscode-typescript-next|ms-|5.0.202302170
vsliveshare|ms-|1.0.5831
vscode-twoslash-queries|Ort|1.1.0
rust-analyzer|rus|0.3.1402
zig|tie|0.2.6
errorlens|use|3.7.0
vscode-lldb|vad|1.8.1
incredibly-in-your-face|Vir|1.0.2
vscode-import-cost|wix|3.3.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vscaat:30438848
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
azure-dev_surveyone:30548225
pyindex848:30662994
nodejswelcome1cf:30587006
2e4cg342:30602488
pyind779cf:30662993
f6dab269:30613381
pythonsymbol12:30657548

```

</details>

**Comment by aeschli** [comment]
It switches to the theme that is configured as 'preferred' theme.
Check out the settings `workbench.preferredDarkColorTheme` and `workbench.preferredLightColorTheme`.
(there are also separate settings for high contrast themes)
