### ISSUE TITLE
VSCode click F5  can't create /.vscode/launch.json by swich the nodejs  environment  or node.js v6.3+ 

### ISSUE THREAD

**Issue by wencaiHong** [Microsoft/vscode#17471]
- VSCode Version:1.8
- OS Version:Ubuntu-16.04.1-desktop-amd64

Steps to Reproduce:

1. can not create /.vscode/launch.json by swich the nodejs  environment  or node.js v6.3+

**Comment by isidorn** [comment]
@wencaiHong I can not seem to repro this, you can see in the attached gif how this works for me
If you do file > preferences > workspace settings - does the `settings.json` get created in your .vscode folder?

Does your launch.json get created if you choose regular node.js?
Can you simple create a new launch.json and then using the blue `add configurations` button to fill the content?

![ubuntu](https://cloud.githubusercontent.com/assets/1926584/21345709/89bb13ca-c6a1-11e6-9dd3-fb7293ced066.gif)

**Comment by isidorn** [comment]
Will reopen once more details are provided
