### ISSUE TITLE
strange characters appear when disable extension

### ISSUE THREAD

**Issue by tjx666** [microsoft/vscode#174739]
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/41773861/219846442-02255a80-7795-418d-8098-797534d8c46d.png">

@aeschli I see you fixed it in https://github.com/microsoft/vscode/issues/146660, but still happen in extensions list view

**Comment by IllusionMH** [comment]
Should only happen if you have DevTools open. Is it the case or it can be reproduced without DevTools?

**Comment by tjx666** [comment]
I can't find a way to stablely reproduce it @IllusionMH

**Comment by sandy081** [comment]
@tjx666 Can you please try our insiders and let us know if you can still reproduce it - https://code.visualstudio.com/insiders/

**Comment by tjx666** [comment]
I will reopen if I can reproduce it stably
