### ISSUE TITLE
Output tab does not auto scroll down. I have to use the mouse. Reducing productivity.

### ISSUE THREAD

**Issue by Abdallah-Ragab** [microsoft/vscode#174780]
This is more of an issue than a feature request as it doesn't make sense not to have it in any code editor
when I run a python script whether by clicking or using the keyboard shortcut, the output tab does not scroll down to the recent output.
so I have to get to the mouse and scroll down in order to see the output of my code which compromises the productivity

**Comment by sandy081** [comment]
This is because of smart scrolling feature. This is enabled by default using setting `output.smartScroll.enabled`

<img width="995" alt="image" src="https://user-images.githubusercontent.com/10746682/220137396-d992d641-8513-4cfa-af9a-437cfe23b7ef.png">

Please disable it if you do not want.

**Comment by Abdallah-Ragab** [comment]
The behavior is a bit confusing but the feature is useful
