### ISSUE TITLE
Format code doesnt work anymore

### ISSUE THREAD

**Issue by NikosEfthias** [Microsoft/vscode#17478]
- VSCode Version: Code 1.8.0 (38746938a4ab94f2f57d9e1309c51fd6fb37553d, 2016-12-13T18:03:00.506Z)
- OS Version: Linux x64 4.8.0-30-generic
- Extensions:

|Extension|Author|Version|
|---|---|---|
|aessoft-class-autocomplete|AESSoft|0.1.0|
|calc|BorisA|0.0.1|
|vscode-qrcode|Compulim|0.2.0|
|format-php|Kasik96|1.1.2|
|vscode-docker|PeterJausovec|0.0.10|
|ActiveFileInStatusBar|RoscoP|1.0.2|
|code-settings-sync|Shan|2.3.8|
|vscode-wakatime|WakaTime|1.0.6|
|vscode-file-peek|abierbaum|1.0.1|
|Bookmarks|alefragnani|0.10.1|
|code-gnu-global|austin|0.2.1|
|path-intellisense|christian-kohler|1.2.0|
|regex|chrmarti|0.0.7|
|vscode-simpler-icons|davidbabel|1.3.0|
|vscode-stylesheet-formatter|dbalage|0.2.0|
|vscode-hasher|deerawan|1.0.1|
|githistory|donjayamanne|0.1.4|
|javadebugger|donjayamanne|0.0.2|
|code-runner|formulahendry|0.6.3|
|RelativePath|jakob101|0.11.0|
|Go|lukehoban|0.6.51|
|font-awesome-codes-html|medzhidov|0.0.3|
|gitignore|michelemelluso|1.0.1|
|prettify-json|mohsen1|0.0.3|
|easy-less|mrcrowl|1.2.5|
|cpptools|ms-vscode|0.9.3|
|java|redhat|0.0.7|
|bash-debug|rogalmic|0.0.2|
|partial-diff|ryu1kn|0.2.0|
|mixliveserver|varomix|0.0.1|

---

After the latest update I can no longer format my c and go code I get the error `Cannot read property 'substring' of undefined`

**Comment by baslr** [comment]
Same, If I issue formating via context menu I get a Error, via shortcut I get a warning. #17424

**Comment by kieferrm** [comment]
@roblourens pls have a look using the go extension.

**Comment by roblourens** [comment]
Yeah this is #17424
