### ISSUE TITLE
Overlapping text on startup screen

### ISSUE THREAD

**Issue by rzhao271** [microsoft/vscode#174721]
Overlapping text on startup screen. This is persistent even when used with --disable-gpu flag.
![Screenshot from 2023-02-17 16-18-36](https://user-images.githubusercontent.com/15894677/219694184-7585506d-21c3-4385-9c03-40cc3aa57fea.png)

_Originally posted by @kamalteja in https://github.com/microsoft/vscode/issues/171367#issuecomment-1434796075_

**Comment by bpasero** [comment]
@kamalteka do you reproduce also on https://insiders.vscode.dev/ ?

**Comment by kamalteja** [comment]
![Screenshot from 2023-02-22 10-59-52](https://user-images.githubusercontent.com/15894677/220587079-fb3c6de5-ea62-4531-93d2-ec68c72c4f14.png)
This is from [insiders.vscode.dev/](https://insiders.vscode.dev/)

**Comment by bpasero** [comment]
Thanks a lot for trying, I think this hints to an issue with your machine and or an issue with Chrome itself. Not something we have control over. 

As for VS Code: when you run from the command line `code --disable-gpu`, does that address the issue?

**Comment by kamalteja** [comment]
I think there a miss-understanding. Just to make myself clear, from my perspective, there are 2 issues with overlapping text.

1. The issue in the question "Overlapping text in **startup screen**" is persistent even when vscode is run with `--disable-gpu` flag.
2. The issue with overlapping text in the search results under settings window is not present with used with `--disable-gpu` flag.

This ticket tackles the first one.

**Comment by bpasero** [comment]
I am just trying to figure out if something with your GPU could cause these rendering artefacts and I think it is related, so moving to Electron category.

**Comment by kamalteja** [comment]
@bpasero  **A small update**.

When I run `code --disable-gpu`, there is no overlapping text on the start page either.

I'm guessing, the last time I tried this, I had another instance of code running (without `--disable-gpu`) flag and opening starting a new instance of code with `--disable-gpu` won't honour the disable gpu flag on the new instance. The same applies on the other way round. If I start code (the first instance of code) with `--disable-gpu` flag, then I don't need to use this flag for subsequent instances of code. Somehow this property is inherited from the first code execution. There's a different process for each vscode instance.

**Comment by bpasero** [comment]
Yes, it needs a full restart 👍

**Comment by lasp73** [comment]
I am having this issue in vscode 1.78.2. When I run "code --disable-gpu", there is no overlaping text, as reported by @kamalteja. And... I had the same issue using Chrome Browser. I was able to fix by disabling extension "Avira Browser Safety". I am not sure if this info could help with vscode.

**Comment by Av1nag** [comment]
does anyone found the permanent solution for text overlapping

**Comment by lasp73** [comment]
> does anyone found the permanent solution for text overlapping

I have disabled GPU as discussed above.
See this: https://code.visualstudio.com/updates/v1_40#_disable-gpu-acceleration

**Comment by rzhao271** [comment]
Closing as out of scope considering this is most likely an upstream issue.
