### ISSUE TITLE
Allow to hide "Open Editors" section when not opening a folder

### ISSUE THREAD

**Issue by StyloBill** [Microsoft/vscode#17473]
- VSCode Version: Code 1.8.0 (38746938a4ab94f2f57d9e1309c51fd6fb37553d, 2016-12-13T17:38:28.425Z)
- OS Version: Darwin x64 15.6.0
- Extensions:

|Extension|Author|Version|
|---|---|---|
|material-icon-theme|PKief|1.1.4|
|theme-onedark|azemoh|0.4.0|
|vscode-dash|deerawan|1.1.2|
|vscode-great-icons|emmanuelbeziat|1.1.28|
|code-runner|formulahendry|0.6.3|
|vs-color-picker|lihui|0.3.2|
|vscode-flow|rtorr|276.3.0|
|ayu|teabyii|0.2.1|

---

Steps to Reproduce:

1. set "explorer.openEditors.visible": 0 in user settings
2. the setting does not work as expected

**Comment by bpasero** [comment]
@StyloBill is this when you have a folder opened in VS Code or when using VS Code empty?

**Comment by StyloBill** [comment]
Empty VS Code. When a folder is opened, the setting is working as expected.

**Comment by bpasero** [comment]
ok, this is as designed. when no folder is opened you cannot hide the open editors view.

**Comment by Rhywun** [comment]
This seems non-intuitive. Why should I need a folder open in order to hide this section that I don't need?

**Comment by bpasero** [comment]
@Rhywun what is the scenario here? what remains in the "Explorer" when you are not opening a folder and you want to hide the "Open Editors" view?

**Comment by sandy081** [comment]
@bpasero Agreed. I would also interested to know the usecase from @Rhywun. 

Also is that the user is missing anything if we do not show "Open Editors" (when user is opted to) during no folder scenario?

**Comment by bpasero** [comment]
No I think it is fine to allow this, but that makes the explorer basically just 1 button to open a folder. Now, with extensions support, it is a different story that makes more sense to me if you have an extension view showing up.

**Comment by Rhywun** [comment]
@bpasero @sandy081 OK, I see what you're getting at. Without a project open, what's the point of having the Explorer open at all. I think I use vscode more often to open single files rather than projects, and after I applied that setting it just seemed weird that the section was still visible.

Maybe a change to consider for the future like you suggest.

**Comment by sandy081** [comment]
Related to #27823

**Comment by bpasero** [comment]
@sandy081 isn't this done?

**Comment by sandy081** [comment]
Yes.. now you can hide Open Editors section in any (no) workspace.

**Comment by weinand** [comment]
Discussed in standup meeting: this has been already verified.

**Comment by AntonBramsen** [comment]
How do you get the Open Editors section back after removing it from the sidebar?

**Comment by sandy081** [comment]
@AntonBramsen You can right click on the viewlet header area to get it back

![image](https://user-images.githubusercontent.com/10746682/29857954-9a343aa2-8d5b-11e7-8c53-ae108c74ff95.png)
