### ISSUE TITLE
Keyboard shortcuts don't scroll view as far as necessary

### ISSUE THREAD

**Issue by elias6** [microsoft/vscode#174710]
Type: <b>Bug</b>

I have been using VS Code for ~4 years, and I like it overall. But there is an annoying bug that I've started noticing in the last 1-2 weeks.

If I try to go to the top of the file I have open by pressing command+up, it scrolls up, but not all the way. It seems like the cursor moves to the top of the file, but I can't actually see it unless I scroll up some more using my trackpad.

Similar things happen if I try to go to the bottom of the file using command+down, or if I try to search for text using command+G.

VS Code version: Code 1.75.1 (Universal) (441438abd1ac652551dbe4d408dfcec8a499b8bf, 2023-02-08T21:34:59.000Z)
OS version: Darwin x64 20.6.0
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|5, 4, 4|
|Memory (System)|16.00GB (0.18GB free)|
|Process Argv|--crash-reporter-id 8546bdc4-919c-427c-bd8c-2a7b47b5943e|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (21)</summary>

Extension|Author (truncated)|Version
---|---|---
Nix|bbe|1.0.1
gitlens|eam|13.2.0
prettier-vscode|esb|9.10.4
pyformat|giy|1.0.2
vscode-graphql|Gra|0.8.5
vscode-graphql-execution|Gra|0.1.7
vscode-graphql-syntax|Gra|1.0.6
vscode-docker|ms-|1.23.3
isort|ms-|2022.8.0
python|ms-|2023.2.0
vscode-pylance|ms-|2023.2.30
jupyter|ms-|2023.1.2010391206
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.14
vscode-jupyter-cell-tags|ms-|0.1.6
vscode-jupyter-slideshow|ms-|0.1.5
color-highlight|nau|2.5.0
fish-vscode|sky|0.2.1
language-stylus|sys|1.16.0
jest-snapshot-language-support|tle|1.1.1
selectline-statusbar|tom|0.0.2

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscoreces:30445986
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
azure-dev_surveyone:30548225
pyindex848:30662994
nodejswelcome1cf:30587006
3biah626:30602489
pyind779cf:30662993
89544117:30613380
pythonsymbol12cf:30657549

```

</details>

**Comment by drbr** [comment]
I've been noticing this too, especially when jumping to a particular line, or instances of a string found using Command-F.

But I can't get a consistent repro: sometimes it scrolls the desired line into view, sometimes it doesn't.

**Comment by drbr** [comment]
Found related issue https://github.com/microsoft/vscode/issues/173487; I did have `editor.smoothScrolling` enabled. Disabling that setting to see if it helps.

**Comment by elias6** [comment]
I disabled smooth scrolling, and this no longer happens. That is a good enough workaround for me. Thanks @drbr.

**Comment by alexdima** [comment]
Let's continue tracking in #173487. @elias6 I am not able to reproduce this on a vanilla vscode with only the smooth scrolling setting turned on. I would love to find out if this reproduces for you after disabling extensions.
