### ISSUE TITLE
Central VS Code server installer across multiple remotes

### ISSUE THREAD

**Issue by eccentricOrange** [microsoft/vscode#174759]
I'm in a university with a very slow network, and I primarily develop on Docker or other WSL systems. As such, many times when I launch VS Code, it begins to update the server and takes half an hour to complete.

I *always* use Debian-like distros on the x64 architecture, so I can use the same installer for all these server instances. Is there a way I can stop it from downloading the same file again and again for each remote machine?

I want to unify just the download process that uses the internet; I'm happy to move the file around on my computer and install it separately in each distro (but I should at least be able to hack together a script to do this, if not make this supported directly by the editor).

**Comment by eccentricOrange** [comment]
Using the flags `--exec bash -c` worked.

Example of a full line in the shell script:
```cmd
wsl -u root -d Ubuntu-22.04 --exec bash -c "apt-get update && apt-get upgrade -y && apt-get install curl -y"
```

Source: https://www.reddit.com/r/bashonubuntuonwindows/comments/1163wm0/comment/j94yu63/?context=3

**Comment by aeschli** [comment]
We don't share the server binaries between the Dev Containers and WSL extensions. But both extensions reuse the server download across distros and containers.
You should be able to see this in the WSL log. 

The server always needs to match the client, so whenever the client is updates, we also need a new server. Are you maybe working with VS Code insiders? There you get a new build every day.

**Comment by eccentricOrange** [comment]
> But both extensions reuse the server download across distros and containers.

Yeah, this is all I was looking for, and my above comment seems to work for this (I copy-pasted completely the wrong comment as I was dealing with two issues simultaneously; will fix).


> The server always needs to match the client, so whenever the client is updates, we also need a new server. Are you maybe working with VS Code insiders?

No, I'm on stable. But the first time during the day launch VS Code is often in class, I really can't afford to wait for a 30-minute download there.
