### ISSUE TITLE
Follow HTTP redirects when importing code profiles.

### ISSUE THREAD

**Issue by agilesteel** [microsoft/vscode#174755]
As a user I need vscode to follow HTTP redirects when importing code profiles.

I am a content creator (mostly YouTube). I often create resources for my viewers and when I do I create short (usually) subdomains on my website to redirect to the real content.

I created a starter code-profile here https://code-profile.devinsideyou.com/ which redirects to https://raw.githubusercontent.com/DevInsideYou/code-profile/main/DevInsideYou.code-profile.

However a profile import only succeeds with the longer direct url.

It's probably just a limitation as opposed to a bug and as such I created this issue as a feature request.

`XHR failed` is all I see in the logs:
```
2023-02-18 11:56:16.444 [error] RequestService#request (browser) - error https://code-profile.devinsideyou.com/ {}
2023-02-18 11:56:16.447 [error] XHR failed: Error: XHR failed
    at v.onerror (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:72:1428)
```

**Comment by sandy081** [comment]
@agilesteel I am seeing CORS error. It seems the server `https://code-profile.devinsideyou.com/` is not accepting CORS requests. You would need to enable CORS on the server.
