### ISSUE TITLE
Functions are showing in output when I run code

### ISSUE THREAD

**Issue by tonywatson-github** [microsoft/vscode#174742]
![issue](https://user-images.githubusercontent.com/124740465/219847494-d8057cbb-647c-4f2b-b190-86754c02a569.PNG)
Type: <b>Bug</b>

Hello,

Node was installed and now I can run code for certain lines of code but for functions everytime I run code, the fucntion won't create an output in the Output tab or in Terminal 

VS Code version: Code 1.75.1 (441438abd1ac652551dbe4d408dfcec8a499b8bf, 2023-02-08T21:33:31.852Z)
OS version: Windows_NT ia32 10.0.19044
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-3240 CPU @ 3.40GHz (4 x 3392)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: unavailable_off<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: unavailable_off<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|7.94GB (3.44GB free)|
|Process Argv|--crash-reporter-id 64ae5a58-ab49-4d7e-8430-7b97dc11a2ce|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (17)</summary>

Extension|Author (truncated)|Version
---|---|---
es7-javascript-class-snippets|abr|0.4.0
vscode-node-readme|ben|3.0.2
java-run|cao|1.1.4
vscode-npm-source|dku|1.0.0
javadebugger|don|0.1.5
auto-node|dud|0.0.7
EditorConfig|Edi|0.16.4
code-runner|for|0.12.0
search-node-modules|jas|1.3.0
vsc-python-indent|Kev|1.18.0
python-path|mge|0.0.14
vscode-exec-node|mir|0.5.5
js-debug-nightly|ms-|2023.2.317
node-modules-resolve|nau|1.0.2
indent-rainbow|ode|8.3.1
vs-code-node-require|tgr|1.10.2
python-extended-snippets|tus|0.0.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vscaac:30438847
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
azure-dev_surveyone:30548225
vscccc:30610679
pyindex848:30662994
nodejswelcome1cf:30587006
282f8724:30602487
pyind779cf:30662993
f6dab269:30613381
pythonsymbol12:30657548
vsccsb:30662443
vscodedisable:30660115

```

</details>

**Comment by roblourens** [comment]
This is an issue with your code, you are not calling that function
