### ISSUE TITLE
Terminal command suggestion does not complete properly by 'Enter'

### ISSUE THREAD

**Issue by anazar2001** [microsoft/vscode#174723]
Type: <b>Bug</b>

Hi,

Trying to  execute command 'kill -9 pid' in integrated Terminal. Start entering pid, the list pops up. I select the pid using the keybord in the list, press Enter but the selected process id is not chosen - I am left with the first initial digits I entered manually.

It all works if I use mouse to select pid from the list.

Could you please check.

Thanks,
Andrei.

VS Code version: Code 1.75.1 (441438abd1ac652551dbe4d408dfcec8a499b8bf, 2023-02-08T21:34:01.965Z)
OS version: Darwin arm64 22.2.0
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|8, 9, 10|
|Memory (System)|32.00GB (0.07GB free)|
|Process Argv|--crash-reporter-id ca77d4d7-a862-4b3b-a666-ca0626efb457|
|Screen Reader|yes|
|VM|0%|
</details><details><summary>Extensions (42)</summary>

Extension|Author (truncated)|Version
---|---|---
cucumberautocomplete|ale|2.15.2
vscode-eclipse-keybindings|alp|0.16.1
format-json|Cle|1.0.3
generator-java-unit-test-file|den|0.0.12
java-decompiler|dgi|0.0.3
javadebugger|don|0.1.5
gitlens|eam|13.2.0
copilot|Git|1.73.8685
gc-excelviewer|Gra|4.2.56
compareit|in4|0.0.2
java-test|jav|0.0.2
auto-comment-blocks|kev|1.0.1
vscode-docker|ms-|1.23.3
vscode-dotnet-runtime|ms-|1.6.0
remote-containers|ms-|0.275.1
remote-ssh|ms-|0.96.0
remote-ssh-edit|ms-|0.84.0
remote-explorer|ms-|0.2.0
vscode-thunder-client|ran|2.4.1
fabric8-analytics|red|0.3.6
java|red|1.14.0
vscode-community-server-connector|red|0.25.7
vscode-rsp-ui|red|0.23.13
vscode-xml|red|0.24.0
multi-command|ryu|1.6.0
sonarlint-vscode|Son|3.14.0
tabnine-vscode|Tab|3.6.38
vscodeintellicode|Vis|1.2.30
vscode-boot-dev-pack|vmw|0.2.1
vscode-spring-boot|vmw|1.44.0
vscode-java-debug|vsc|0.48.0
vscode-java-dependency|vsc|0.21.1
vscode-java-pack|vsc|0.25.7
vscode-java-test|vsc|0.37.2023021404
vscode-lombok|vsc|1.1.0
vscode-maven|vsc|0.40.4
vscode-spring-boot-dashboard|vsc|0.10.1
vscode-spring-initializr|vsc|0.11.2
vscode-icons|vsc|12.2.0
vscode-icons-mac|way|7.25.3
fig|wit|0.0.7
familiar-java-themes|zer|0.1.7

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
azure-dev_surveyone:30548225
vscccc:30610679
pyindex848:30662994
nodejswelcome1cf:30587006
3biah626:30602489
pyind779cf:30662993
f6dab269:30613381
pythonsymbol12:30657548

```

</details>

**Comment by anazar2001** [comment]
<img width="1728" alt="Screenshot 2023-02-17 at 21 02 09" src="https://user-images.githubusercontent.com/13858727/219793330-1d95c65a-6585-4e41-81d4-e1b21d824b8c.png">
<img width="1728" alt="Screenshot 2023-02-17 at 21 01 58" src="https://user-images.githubusercontent.com/13858727/219793338-183cb51b-c669-4aeb-a5d4-12ed15cfca19.png">

**Comment by meganrogge** [comment]
that autocomplete is coming from a custom configuration you have or an extension - not VS Code core
