### ISSUE TITLE
`list.collapseAll` leaves selection in a broken state

### ISSUE THREAD

**Issue by akbyrd** [microsoft/vscode#174768]
Type: <b>Bug</b>

When pressing `ctrl+left` to collapse all nodes in a list view it leaves selection in such a state that you cannot expand nodes with `right` until you do something to change the selection.

![list collapseAll](https://user-images.githubusercontent.com/484784/219903859-68d4fb77-4614-4801-94ca-7da84b4a7d06.gif)

I believe what's happening is `list.collapseAll` is leaving the originally selected node selected. So after executing the command you end up with 2 selections, your original selection plus the last root node in the list. The original selection is the primary selection, and if it has no children `right` does not have anything to expand and is a no-op.

As a user it looks like you have the root node selected, which has children to expand, but pressing `right` does nothing.

Pressing `down` then expands the list to reveal your original selection and you see that you unexpectedly have multiple selections.

The current behavior of `list.collapseAll` appears to be:
* Leave the originally selected node selected
* Add a second selection to the last root node in the list

The expected behavior here is:
* Move selection to the root node of your currently selected node
* Ideally this also retains multiple selection: each selection is moved to the root node of that selection.

VS Code version: Code - Insiders 1.76.0-insider (c7930ca55d072608625ba76c13b5f9baaf9a2136, 2023-02-10T16:22:19.445Z)
OS version: Windows_NT x64 10.0.19045
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 9 5950X 16-Core Processor             (32 x 3400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.92GB (20.54GB free)|
|Process Argv|--crash-reporter-id 22cf4e37-a96e-4ad9-82f0-8715f8e2bf6e|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30422396
pythontb:30258533
pythonptprofiler:30281269
vsdfh931cf:30280410
vshan820:30294714
pythondataviewer:30285072
vscod805cf:30301675
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30404738
cppdebug:30492333
vsclangdf:30492506
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30618038
pylantcb52:30590116
pyindex848:30611229
nodejswelcome1:30587009
pyind779:30611226
pythonsymbol12:30651887
2i9eh265:30646982
showlangstatbar:30659908
pythonb192cf:30661257

```

</details>

**Comment by akbyrd** [comment]
Looking at this again in the File Explorer it looks like the selection highlight is left on the `row` where the original selection was despite the fact that the _node_ is now in a different position. However, the "real" selection is still on the node.

This means it looks like one thing is highlighted and pressing `enter` opens a different thing.

**Comment by babakks** [comment]
@joaomoreno Just submitted a PR for this. Could you please review it?

**Comment by alexr00** [comment]
What is the behavior supposed to be? Here's what I see:
1. Use keyboard to focus a tree node that has a parent
2. `ctrl+left` to collapse all
3. Focus moves to the whole tree and arrow down takes me to the first tree element. Right arrow does nothing.

**Comment by joaomoreno** [comment]
I agree, feel free to send an issue for it. 👌 

@alexr00 Your observations are the fixed state. Here's the entire story: https://github.com/microsoft/vscode/pull/182601#issuecomment-1864545683. Marking it as verified.
