### ISSUE TITLE
ssh processes linger after Close Remote Connection Selected

### ISSUE THREAD

**Issue by DavidGietka-NOAA** [microsoft/vscode#174708]
Does this issue occur when all extensions are disabled?: No
No - The remote ssh extension is required for this scenario

- VS Code Version: 
- Version: 1.76.0-insider (user setup)
Commit: c4a609f94329b17d91cd13a4fd113d1abfe5ec1f
Date: 2023-02-03T05:23:17.202Z
Electron: 19.1.9
Chromium: 102.0.5005.194
Node.js: 16.14.2
V8: 10.2.154.23-electron.0
OS: Windows_NT x64 10.0.19044
Sandboxed: Yes
- OS Version: Windows_NT x64 10.0.19044

Steps to Reproduce:

1. Open VSCode. In the lower left click remote connection, then Connect to Host. Select a Host to connect to.
2.  Run ps -ef | grep username on remote system and note processes
3.  Select File, Close Remote Connection
4.  Run ps -ef | grep username on remote system and note processes

Thanks for your assistance. Please let me know if you need additional information.

![vscode_processes1_20230217](https://user-images.githubusercontent.com/82125179/219760295-b2480ab7-533c-45e6-b6b1-14a3392903b7.png)
![vscode_processes2_20230217](https://user-images.githubusercontent.com/82125179/219760300-d07052bc-188d-4e52-b7b3-36d859ff4641.png)

**Comment by roblourens** [comment]
Are you still seeing this?

How long do the processes stick around for? There is a certain timeout after which processes will shut down. For the server I think that is a few hours by default.

**Comment by roblourens** [comment]
What you should see is that the server process should shut down about 10 minutes after the last window disconnects. 

If that's not happening, can you share the log from the server, which should be here: `~/.vscode-server/.<version hash>.log`

**Comment by DavidGietka-NOAA** [comment]
Hi Rob,
It looks like the vscode server process did terminate but the shell
processes did not.  See ps outputs below. I also included the vsserver.log
file. Please let me know what you think.

Regards,
David Gietka


***@***.*** ~]# ps -ef | grep dgietka
root     15059 15026  0 15:38 pts/0    00:00:00 grep --color=auto dgietka
***@***.*** ~]# date
Thu Apr 13 15:38:12 EDT 2023
***@***.*** ~]# ps -ef | grep dgietka
root     15076 29181  0 15:38 ?        00:00:00 sshd: dgietka [priv]
dgietka  15087 15076  0 15:38 ?        00:00:00 sshd: ***@***.***
dgietka  15088 15087  0 15:38 ?        00:00:00 bash
dgietka  15196 15088  0 15:39 ?        00:00:00 sh
/home/dgietka/.vscode-server-insiders/bin/079272e4a37ceecd22dcebc3566bb46c8580a13c/bin/code-server-insiders
--start-server --host=127.0.0.1 --accept-server-license-terms
--enable-remote-auto-shutdown --port=0 --telemetry-le
vel all --connection-token-file
/home/dgietka/.vscode-server-insiders/.079272e4a37ceecd22dcebc3566bb46c8580a13c.token
dgietka  15208 15196  0 15:39 ?        00:00:01
/home/dgietka/.vscode-server-insiders/bin/079272e4a37ceecd22dcebc3566bb46c8580a13c/node
/
home/dgietka/.vscode-server-insiders/bin/079272e4a37ceecd22dcebc3566bb46c8580a13c/out/server-main.js
--start-server --host=127.0.0.1 --ac
cept-server-license-terms --enable-remote-auto-shutdown --port=0
--telemetry-level all --connection-token-file
/home/dgietka/.vscode-server-insiders/.079272e4a37ceecd22dcebc3566bb46c8580a13c.token
dgietka  15253 15208  0 15:39 ?        00:00:00
/home/dgietka/.vscode-server-insiders/bin/079272e4a37ceecd22dcebc3566bb46c8580a13c/node
/
home/dgietka/.vscode-server-insiders/bin/079272e4a37ceecd22dcebc3566bb46c8580a13c/out/bootstrap-fork
--type=ptyHost --logsPath /home/dgie
tka/.vscode-server-insiders/data/logs/20230413T153909
dgietka  15283 15208  0 15:39 ?        00:00:01
/home/dgietka/.vscode-server-insiders/bin/079272e4a37ceecd22dcebc3566bb46c8580a13c/node
/
home/dgietka/.vscode-server-insiders/bin/079272e4a37ceecd22dcebc3566bb46c8580a13c/out/bootstrap-fork
--type=extensionHost --transformURIs --useHostProxy=false
dgietka  17060 15088  0 15:48 ?        00:00:00 sleep 180
root     17065 15026  0 15:48 pts/0    00:00:00 grep --color=auto dgietka
***@***.*** ~]# date
Thu Apr 13 15:48:16 EDT 2023
***@***.*** ~]# ps -ef | grep dgietka
root     15076 29181  0 15:38 ?        00:00:00 sshd: dgietka [priv]
dgietka  15087 15076  0 15:38 ?        00:00:00 sshd: ***@***.***
dgietka  15088 15087  0 15:38 ?        00:00:00 bash
dgietka  15196 15088  0 15:39 ?        00:00:00 sh
/home/dgietka/.vscode-server-insiders/bin/079272e4a37ceecd22dcebc3566bb46c8580a13c/bin/code-server-insiders
--start-server --host=127.0.0.1 --accept-server-license-terms
--enable-remote-auto-shutdown --port=0 --telemetry-le
vel all --connection-token-file
/home/dgietka/.vscode-server-insiders/.079272e4a37ceecd22dcebc3566bb46c8580a13c.token
dgietka  15208 15196  0 15:39 ?        00:00:01
/home/dgietka/.vscode-server-insiders/bin/079272e4a37ceecd22dcebc3566bb46c8580a13c/node
/
home/dgietka/.vscode-server-insiders/bin/079272e4a37ceecd22dcebc3566bb46c8580a13c/out/server-main.js
--start-server --host=127.0.0.1 --ac
cept-server-license-terms --enable-remote-auto-shutdown --port=0
--telemetry-level all --connection-token-file
/home/dgietka/.vscode-server-insiders/.079272e4a37ceecd22dcebc3566bb46c8580a13c.token
dgietka  15253 15208  0 15:39 ?        00:00:00
/home/dgietka/.vscode-server-insiders/bin/079272e4a37ceecd22dcebc3566bb46c8580a13c/node
/
home/dgietka/.vscode-server-insiders/bin/079272e4a37ceecd22dcebc3566bb46c8580a13c/out/bootstrap-fork
--type=ptyHost --logsPath /home/dgie
tka/.vscode-server-insiders/data/logs/20230413T153909
dgietka  17060 15088  0 15:48 ?        00:00:00 sleep 180
root     17112 15026  0 15:48 pts/0    00:00:00 grep --color=auto dgietka
***@***.*** ~]# date
Thu Apr 13 15:48:55 EDT 2023
***@***.*** ~]# ps -ef | grep dgietka
root     15076 29181  0 15:38 ?        00:00:00 sshd: dgietka [priv]
dgietka  15087 15076  0 15:38 ?        00:00:00 sshd: ***@***.***
dgietka  15088 15087  0 15:38 ?        00:00:00 bash
dgietka  18093 15088  0 16:00 ?        00:00:00 sleep 180
root     19118 15026  0 16:01 pts/0    00:00:00 grep --color=auto dgietka
***@***.*** ~]# date
Thu Apr 13 16:02:02 EDT 2023
***@***.*** ~]# ps -ef | grep dgietka
root     15076 29181  0 15:38 ?        00:00:00 sshd: dgietka [priv]
dgietka  15087 15076  0 15:38 ?        00:00:00 sshd: ***@***.***
dgietka  15088 15087  0 15:38 ?        00:00:00 bash
dgietka  27267 15088  0 16:57 ?        00:00:00 sleep 180
root     27427 27411  0 16:59 pts/0    00:00:00 grep --color=auto dgietka
***@***.*** ~]# date
Thu Apr 13 16:59:38 EDT 2023

########################################
-bash-4.2$ cat
~/.vscode-server/.97dec172d3256f8ca4bfb2143f3f76b503ca0534.log
*
* Visual Studio Code Server
*
* By using the software, you agree to
* the Visual Studio Code Server License Terms (
https://aka.ms/vscode-server-license) and
* the Microsoft Privacy Statement (
https://privacy.microsoft.com/en-US/privacystatement).
*
Server bound to 127.0.0.1:42011 (IPv4)
Extension host agent listening on 42011

[22:34:04] Extension host agent started.
[22:34:04] [127.0.0.1][bf53c960][ManagementConnection] New connection
established.
[22:34:04] [127.0.0.1][f663b4fa][ExtensionHostConnection] New connection
established.
[22:34:04] [127.0.0.1][f663b4fa][ExtensionHostConnection] <32383> Launched
Extension Host Process.
[IPC Library: Pty Host]  WARN Shell integration cannot be enabled for
executable "/bin/sh" and args [
  '-c',
  'wget --version > /dev/null\n' +
    'if [ $? -eq 0 ]\n' +
    'then\n' +
    "\twget --connect-timeout=7 --tries=1 --dns-timeout=7 -q
--header='Metadata:true' -O -
http://169.254.169.254/metadata/instance?api-version=2019-03-11\n" +
    'else\n' +
    '\tcurl --version > /dev/null\n' +
    '\tif [ $? -eq 0 ]\n' +
    '\tthen\n' +
    "\t\tcurl --connect-timeout 7 -s --header='Metadata:true'
http://169.254.169.254/metadata/instance?api-version=2019-03-11\n" +
    '\tfi\n' +
    'fi\n' +
    'exit 0'
]
[IPC Library: Pty Host]  WARN Shell integration cannot be enabled for
executable "/bin/sh" and args [
  '-c',
  'wget --version > /dev/null\n' +
    'if [ $? -eq 0 ]\n' +
    'then\n' +
    '\twget --connect-timeout=7 --tries=1 --dns-timeout=7 -q  -O -
http://169.254.169.254/latest/meta-data/instance-id\n' +
    'else\n' +
    '\tcurl --version > /dev/null\n' +
    '\tif [ $? -eq 0 ]\n' +
    '\tthen\n' +
    '\t\tcurl --connect-timeout 7 -s
http://169.254.169.254/latest/meta-data/instance-id\n' +
    '\tfi\n' +
    'fi\n' +
    'exit 0'
]
[IPC Library: Pty Host]  WARN Shell integration cannot be enabled for
executable "/bin/sh" and args [
  '-c',
  'wget --version > /dev/null\n' +
    'if [ $? -eq 0 ]\n' +
    'then\n' +
    '\twget --connect-timeout=7 --tries=1 --dns-timeout=7 -q  -O -
http://169.254.169.254/metadata/v1/id\n' +
    'else\n' +
    '\tcurl --version > /dev/null\n' +
    '\tif [ $? -eq 0 ]\n' +
    '\tthen\n' +
    '\t\tcurl --connect-timeout 7 -s
http://169.254.169.254/metadata/v1/id\n' +
    '\tfi\n' +
    'fi\n' +
    'exit 0'
]
[IPC Library: Pty Host]  WARN Shell integration cannot be enabled for
executable "/bin/sh" and args [
  '-c',
  'wget --version > /dev/null\n' +
    'if [ $? -eq 0 ]\n' +
    'then\n' +
    "\twget --connect-timeout=7 --tries=1 --dns-timeout=7 -q
--header='Metadata-Flavor:Google' -O -
http://metadata.google.internal/computeMetadata/v1/instance/id\n" +
    'else\n' +
    '\tcurl --version > /dev/null\n' +
    '\tif [ $? -eq 0 ]\n' +
    '\tthen\n' +
    "\t\tcurl --connect-timeout 7 -s --header='Metadata-Flavor:Google'
http://metadata.google.internal/computeMetadata/v1/instance/id\n" +
    '\tfi\n' +
    'fi\n' +
    'exit 0'
]
[22:38:57] [127.0.0.1][bf53c960][ManagementConnection] The client has
disconnected gracefully, so the connection will be disposed.
[22:38:57] [127.0.0.1][f663b4fa][ExtensionHostConnection] <32383> Extension
Host Process exited with code: 0, signal: null.
Last EH closed, waiting before shutting down
[22:38:57] Last EH closed, waiting before shutting down
Last EH closed, shutting down
[22:43:57] Last EH closed, shutting down
############################################

**Comment by roblourens** [comment]
This is different- now the server has gone down but the sshd process and the bash script that we run are still running.

What's _supposed_ to happen is that when the ssh connection is closed, the sshd process and its child script should be automatically shut down. In my experience, that's what happens on linux, and I'm not sure why it's not happening for you. 

Something you can try is adding the setting `"remote.SSH.useLocalServer": true` in your settings.json file. This will connect in a different mode that may avoid the issue (or you may run into other issues which is why it's disabled by default on windows)

**Comment by DavidGietka-NOAA** [comment]
Hi Rob,
I already had remote.SSH.useLocalServer enabled as a part of my previous
debugging efforts. The biggest issue was that the VSCode processes were
taking up large amounts of memory on our small virtual instances and they
were hanging around. Now that they terminate within 10 minutes of closing
the connection that should help.

I will inform my developers to update to the latest version of VSCode and
have them test whether remote.SSH.useLocalServer makes a difference in the
amount of connections that stay open.

You can close the ticket. I appreciate you looking into it. Have a good
night.

Regards,
David Gietka
