### ISSUE TITLE
C++ Build Error "The system cannot find the path specified"

### ISSUE THREAD

**Issue by jfraschilla** [microsoft/vscode#174776]
Type: <b>Bug</b>

Here is the main program:
```
#include <iostream>
#include <vector>
#include <string>

using namespace std;

int main()
{
    vector<string> msg {"Hello", "C++", "World", "from", "VS Code", "and the C++ extension!"};

    for (const string& word : msg)
    {
        cout << word << " ";
    }
    cout << endl;
}
```

Here is the tasks.json:

```
    "tasks": [
        {
            "type": "cppbuild",
            "label": "C/C++: g++.exe build active file",
            "command": "D:\\msys64\\mingw64\\bin\\g++.exe",
            "args": [
                "-fdiagnostics-color=always",
                "-g",
                "${file}",
                "-o",
                "${fileDirname}\\${fileBasenameNoExtension}.exe"
            ],
            "options": {
                "cwd": "${fileDirname}"
            },
            "problemMatcher": [
                "$gcc"
            ],
            "group": {
                "kind": "build",
                "isDefault": true
            },
            "detail": "Task generated by Debugger."
        }
    ],
    "version": "2.0.0"
}
```

Error message:
Executing task: C/C++: g++.exe build active file 

Starting build...
D:\msys64\mingw64\bin\g++.exe -fdiagnostics-color=always -g D:\dev\vscode_helloworld\helloworld.cpp -o D:\dev\vscode_helloworld\helloworld.exe
The system cannot find the path specified.

Build finished with error(s).

 *  The terminal process failed to launch (exit code: -1). 

When I execute the following command in a cmd or pwsh window it works:
D:\msys64\mingw64\bin\g++.exe -fdiagnostics-color=always -g D:\dev\vscode_helloworld\helloworld.cpp -o D:\dev\vscode_helloworld\helloworld.exe

Why doesn't it work when selecting "Run Build Tasks..." from the Terminal menu?

VS Code version: Code - Insiders 1.76.0-insider (96a795cc0b1cd62f9ff66c347637f917c6dde3da, 2023-02-17T22:22:55.538Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-10900X CPU @ 3.70GHz (20 x 3696)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|127.69GB (113.34GB free)|
|Process Argv|--crash-reporter-id 605b6737-c90d-42ce-99a9-881c56bb28b1|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (53)</summary>

Extension|Author (truncated)|Version
---|---|---
emojisense|bie|0.9.1
markdown-emoji|bie|0.3.0
LinkCheckMD|bla|0.3.1
vscode-markdownlint|Dav|0.49.0
docs-article-templates|doc|0.2.13
docs-authoring-pack|doc|0.1.18
docs-build|doc|0.4.0
docs-images|doc|0.0.10
docs-linting|doc|0.0.13
docs-markdown|doc|0.2.117
docs-metadata|doc|1.0.9
docs-preview|doc|0.3.60
docs-scaffolding|doc|0.0.16
docs-yaml|doc|0.2.9
gitlens|eam|2023.2.1804
mdmath|goe|2.7.4
todo-tree|Gru|0.0.224
vscode-drawio-insiders-build|hed|1.6.606
Ionide-fsharp|Ion|7.4.2
vscode-dashboard|kru|2.6.0
vscode-azurefunctions|ms-|1.10.2
vscode-azureresourcegroups|ms-|0.5.6
vscode-azurestaticwebapps|ms-|0.11.4
csharp|ms-|1.25.4
dotnet-interactive-vscode|ms-|1.0.4116081
vscode-dotnet-pack|ms-|1.0.12
isort|ms-|2022.8.0
python|ms-|2023.2.0
vscode-pylance|ms-|2023.2.30
sarif-viewer|MS-|3.3.5
jupyter|ms-|2023.2.1000491010
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.15
vscode-jupyter-cell-tags|ms-|0.1.6
vscode-jupyter-slideshow|ms-|0.1.5
remote-containers|ms-|0.279.0
remote-wsl|ms-|0.76.0
azure-account|ms-|0.11.3
cmake-tools|ms-|1.13.45
cpptools|ms-|1.14.3
cpptools-extension-pack|ms-|1.3.0
powershell-preview|ms-|2023.2.1
vsliveshare|ms-|1.0.5831
vscode-yaml|red|1.11.0
trailing-spaces|sha|0.4.1
markdown-preview-enhanced|shd|0.6.7
code-spell-checker|str|2.16.0
cmake|twx|0.0.17
intellicode-api-usage-examples|Vis|0.2.7
vscodeintellicode|Vis|1.2.30
vscode-icons|vsc|12.2.0
vscode-todo-highlight|way|1.0.5
markdown-all-in-one|yzh|3.5.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30422396
pythontb:30258533
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscod805cf:30301675
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30404738
cppdebug:30492333
vsclangdf:30492506
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30618038
pylantcb52:30590116
pyindex848:30611229
nodejswelcome1:30587009
pyind779:30611226
pythonsymbol12:30651887
a9j8j154:30646983
showlangstatbar:30659908
pythonb192:30661256

```

</details>

**Comment by jfraschilla** [comment]
If I change the type to shell everything works. 
```
 "type": "shell" 
```
 Why is this not documented or the default when VS Code creates the build task?

**Comment by meganrogge** [comment]
when you set `type:cppbuild`, we expect that the task will be contributed via the c++ extension. since it isn't, the above won't work. when you set `shell` as the type, that means you're providing the command and args that will be run as the task

**Comment by jfraschilla** [comment]
I do not understand your answer.  I followed the instruction given here:
https://code.visualstudio.com/docs/cpp/config-mingw
and it did not work.
