### ISSUE TITLE
save position&compacted css file error

### ISSUE THREAD

**Issue by vowless** [Microsoft/vscode#17477]
- VSCode Version: Code 1.8.0 (38746938a4ab94f2f57d9e1309c51fd6fb37553d, 2016-12-13T17:38:28.425Z)
- OS Version: Darwin x64 16.3.0
- Extensions:

|Extension|Author|Version|
|---|---|---|
|autofilename|JerryHong|0.1.3|
|theme-itgdark|chriscarrick|0.2.0|

---

Steps to Reproduce:

1.default save position can not keep your last time saved place.
![2016-12-18 09 34 52](https://cloud.githubusercontent.com/assets/13657938/21290896/d01b2e78-c506-11e6-9d30-7901eda5cede.png)

2.when open with compact css file editor does't work
![2016-12-18 09 47 56](https://cloud.githubusercontent.com/assets/13657938/21290902/1849f878-c507-11e6-885d-de92fab6f2e7.png)

**Comment by aeschli** [comment]
For performance reasons, we don't do tokenization if a line is longer than 20k characters.
