### ISSUE TITLE
Test: tab focus mode settlings 

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#174707]
Refs https://github.com/microsoft/vscode/issues/173451

- [x] Windows @cwebster-99 
- [x] macOS @sbatten 
- [x] Linux @alexr00 

Complexity: 3

Authors: @meganrogge 

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23174707%0A%0A&assignees=meganrogge)

---

The command `editor.action.toggleTabFocusMode` toggles tab moving focus vs executing in a normal way in a terminal or editor. 

We've added settings for this so that a user can dictate how it should behave in each area on window open / reload. 

Verify that you can toggle still, the settings take effect, and the status bar item reflects the current state.

**Comment by alexr00** [comment]
@meganrogge are these the only settings?

- `terminal.integrated.tabFocusMode`
- `editor.tabFocusMode`

**Comment by meganrogge** [comment]
Yes @alexr00 👍🏼
