### ISSUE TITLE
VS Code auto suggestion stopped working

### ISSUE THREAD

**Issue by rishabhmehta** [microsoft/vscode#174789]
Type: <b>Bug</b>

I work extensively with next.js alongside Tailwind.

And until yesterday, VSCode intellisense was working for tailwind and next.js config files where VS code would suggest all the available properties in tailwind.config.js & next.config.js.

But as of today, it has stopped working. In my VS code "javascript.suggest.enabled": true 
is already present but the problem still remains! 

VS Code version: Code 1.75.1 (Universal) (441438abd1ac652551dbe4d408dfcec8a499b8bf, 2023-02-08T21:34:59.000Z)
OS version: Darwin arm64 22.2.0
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M2 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|5, 4, 3|
|Memory (System)|8.00GB (0.08GB free)|
|Process Argv|--crash-reporter-id d89279ec-e567-4e70-be65-fc73ec3500ef|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (35)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|3.0.2
tailwind-docs|aus|2.0.0
vscode-tailwindcss|bra|0.9.7
npm-intellisense|chr|1.4.4
path-intellisense|chr|2.8.4
vscode-eslint|dba|2.4.0
es7-react-js-snippets|dsz|4.4.3
vscode-html-css|ecm|1.13.1
vscode-npm-script|eg2|0.3.29
prettier-vscode|esb|9.10.4
auto-rename-tag|for|0.1.10
vscode-mysql|for|0.4.1
live-sass|gle|6.0.2
headwind|hey|1.7.0
search-node-modules|jas|1.3.0
vscode-gutter-preview|kis|0.30.0
dotenv|mik|1.0.1
vsliveshare|ms-|1.0.5831
color-highlight|nau|2.5.0
indent-rainbow|ode|8.3.1
material-icon-theme|PKi|4.24.0
prisma|Pri|4.10.1
shellman|Rem|5.6.0
LiveServer|rit|5.7.9
code-settings-sync|Sha|3.4.3
html-to-css-autocompletion|sol|1.1.2
autoimport|ste|1.5.4
vscode-styled-components|sty|1.7.5
html-preview-vscode|tht|0.2.5
shellcheck|tim|0.29.4
nodejs-extension-pack|wad|0.1.9
vscode-nextjs-snippets|wil|0.3.0
vscode-import-cost|wix|3.3.0
JavaScriptSnippets|xab|1.8.0
vscode-preview-server|yui|1.3.0

(4 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
azure-dev_surveyone:30548225
vscccc:30610679
pyindex848:30662994
nodejswelcome1cf:30587006
2e4cg342:30602488
pyind779:30662992
89544117:30613380
pythonsymbol12cf:30657549
vsctsb:30662444

```

</details>

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

If it does, please share steps to reproduce the issue

**Comment by rishabhmehta** [comment]
@mjbvz Issue has been resolved.

Thanks!
