### ISSUE TITLE
Version numbers in extensions makes them difficult to backup

### ISSUE THREAD

**Issue by daniporr** [microsoft/vscode#174767]
Having version numbers in the folder name of each extension has several drawbacks.
First of all, it makes very difficult to backup them because you always need to copy everything even if only a single small file changed.

Moreover, even the update of the extension is quite expensive since you have to copy all the files (even the unchanged ones).

And I do not see any benefits in having the version numbers there.

Is this something you want to change in the future?
Or, are there reasons why you want to keep them?

**Comment by sandy081** [comment]
It is an implementation detail and will remain like this. It is easy to get a unique folder name during updates. We can replace the existing extension during update because it might be used by VS Code extension host process.
