### ISSUE TITLE
Test file watcher running as utility process

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#174785]
Refs: https://github.com/microsoft/vscode/issues/154050

- [x] macOS @lramos15 
- [x] linux @karthiknadig
- [x] windows @dbaeumer

Complexity: 3

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23174785%0A%0A&assignees=bpasero)

---

A new setting `files.experimental.watcherUseUtilityProcess` can be set to run the file watcher process from an Electron utility process and not in the shared process. Make sure you have this enabled and restart to test this. You can verify that you run the watcher from the utility process via the process explorer: hover over the file watcher event and look for "type=utility":

<img width="454" alt="image" src="https://user-images.githubusercontent.com/900690/219937589-37da7ba0-ee33-47a5-ac95-26ecea357d95.png">

You can always get watcher information when you run with `--verbose` and filter the console to `parcel`:

<img width="537" alt="image" src="https://user-images.githubusercontent.com/900690/219937672-fa83cfb9-3407-402d-83c8-b27a1e44cecc.png">

**Basic Watcher Testing**
Do some basic watcher smoke testing: Make sure that changes to files and folders of the workspace are still reflected by components such as the file explorer, git changes view or the active editor. 

**Note:** best to test this with external tools or a secondary window doing changes while observing the VS Code window in the background. We do refresh explorer and active editor when the window receives focus, making it harder to actually test file changes specifically.

**Watcher Process Lifecycle Testing**
Each window has exactly 1 `file-watcher` process associated. The watcher is terminated and started when the window reloads or changes to a different workspace. Ensure you never have more than 1 `file-watcher` per window.

Kill the file watcher (e.g. from the process explorer) and ensure the watcher automatically restarts and is functional again.

Ensure there are no stray file watcher processes hanging around when you quit VS Code or kill it.

**Comment by lramos15** [comment]
Works great, I did notice that file events don't update besides for visible views when VS Code doesn't have focus, but they do update if you kill the process externally and it reboots. However, this seems to be intended behavior regardless of utility process

**Comment by karthiknadig** [comment]
I am assuming that the process started externally is this one:
![image](https://user-images.githubusercontent.com/3840081/220444162-7087a155-f347-480d-b3aa-908d386ff0a2.png)

**Comment by bpasero** [comment]
@lramos15 

> I did notice that file events don't update besides for visible views when VS Code doesn't have focus

Can you clarify what you mean? What are the steps to see this behaviour?

@karthiknadig yes!
