### ISSUE TITLE
[Accessibility] Remove redundant 4-5 blank lines from the terminal a11y buffer

### ISSUE THREAD

**Issue by jooyoungseo** [microsoft/vscode#174798]
CC @meganrogge

* Note: the following issue is only found in `cmd Command Prompt` terminal profile. Other shells may or may not have the same issue.

## Reproducible Steps

1. Load NVDA.

1. Run `Terminal: Create New Terminal (With Profile)`.

1. Choose `cmd Command Prompt`.

1. Type the following in the cmd.exe and hit enter:

``` bash
echo hello
```

1. Press Shift+Tab to focus in the a11y terminal buffer.

1. Press Ctrl+End key to go to the bottom of the buffer.

## Current Behavior

After the last terminal content, redundant 4-5 blank lines are added so users will have to press UpArrow keys multiple times to reach the last content.

## Expected Behavior

The redundant blanks need to be removed.

## System Info

Version: 1.76.0-insider (system setup)
Commit: 96a795cc0b1cd62f9ff66c347637f917c6dde3da
Date: 2023-02-17T22:22:55.538Z
Electron: 19.1.9
Chromium: 102.0.5005.194
Node.js: 16.14.2
V8: 10.2.154.23-electron.0
OS: Windows_NT x64 10.0.22621
Sandboxed: Yes

**Comment by jooyoungseo** [comment]
I have noticed that there are more blank lines produced when you use `Terminal: Create New Terminal in Editor Area`. I assume that this is because the a11y buffer size reflects Monaco editor size and pressing Ctrl+End key thus puts your cursor at the end of the editor buffer. This makes sense, but it would be nice if we could trim out the blank lines after the actual terminal content.

**Comment by connor4312** [comment]
On macOS, end and cmd+end does nothing, while ctrl+end or alt+end both focus the vscode window rather than anything in the terminal (or, when screencast mode is on, they focus the screencast hint)

**Comment by meganrogge** [comment]
@connor4312 this is just an issue about not having empty lines in the accessible terminal buffer.

**Comment by connor4312** [comment]
👍  no empty lines to be seen
