### ISSUE TITLE
Da

### ISSUE THREAD

**Issue by lildaddy423** [microsoft/vscode#174774]
ADD ISSUE DESCRIPTION HERE

Version: 1.75.1
Commit: 441438abd1ac652551dbe4d408dfcec8a499b8bf
User Agent: Mozilla/5.0 (Linux; Android 13; SM-G981V) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Mobile Safari/537.36
Embedder: codespaces

**Comment by DonJayamanne** [comment]
Closing this issue due to lack of information
