### ISSUE TITLE
Overflow Tabs and Refined Completion

### ISSUE THREAD

**Issue by DaelinL** [microsoft/vscode#174763]
Type: <b>Bug</b>

1) It's really challenging that the overflow menu is inside another menu.  The ... should pull down open editors automatically.  It would also be nice if the tab order updated when you selected or "reopened" a tab at the top to avoid excessive use of the overflow menu.  Switching back and forth between the first and last tab in the order is really time consuming.  I understand that this one is probably a feature and not a bug, but the second issue I had probably is a bug.

2) I had to completely disable code completion because many of the toggles don't work and there are a lot.  It was confusing to use and I tried for several hours before giving up and completely disabling it.  There should be <b>an easy way to enable exact matching only</b>.  All the other stuff VSCode suggested was completely unrelated to what I was doing most of the time.  It wasn't one example.  It plain just doesn't work most of the time and caused a lot of errors and wasted time.  When I type in ".get" and it gives me be back "dEleGaTeobject" at the top when I have plenty of get methods, something is wrong.

Thank you for your time and all your hard work.

VS Code version: Code 1.75.1 (441438abd1ac652551dbe4d408dfcec8a499b8bf, 2023-02-08T21:32:34.589Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|12th Gen Intel(R) Core(TM) i7-12700F (20 x 2112)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.86GB (26.50GB free)|
|Process Argv|--crash-reporter-id ad2448d8-8ec4-4d7b-a62a-60972c8f327b|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
pascal|ale|9.6.0
ruby|reb|0.28.1
vscode-ruby|win|0.28.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
azure-dev_surveyone:30548225
vscccc:30610679
pyindex848:30662994
nodejswelcome1cf:30587006
282f8724:30602487
pyind779:30662992
89544117:30613380
pythonsymbol12cf:30657549
vsccsb:30662443

```

</details>

**Comment by jrieken** [comment]
@DaelinL please file two separate issues for this
