### ISSUE TITLE
OpenFile doesn't receive focus after first attempt.

### ISSUE THREAD

**Issue by Jakjm** [microsoft/vscode#174758]
Type: <b>Bug</b>

1. Open Code - OSS. 
2. Use the "File->Open File" menu to open the page for selecting a file.
Either open a file or close the page.
3. Use "File->Open File" again in order to open a new prompt for selecting a file.
4. The page for selecting a file does not receive focus on the second attempt or subsequent attempts.

VS Code version: Code - OSS 1.75.1 (441438abd1ac652551dbe4d408dfcec8a499b8bf, 2023-02-09T20:16:38.064Z)
OS version: Linux x64 6.1.12-arch1-1
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 3400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|1, 1, 1|
|Memory (System)|15.52GB (11.82GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|cinnamon|
|XDG_CURRENT_DESKTOP|X-Cinnamon|
|XDG_SESSION_DESKTOP|cinnamon|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-antlr4|mik|2.3.1

</details>

**Comment by deepak1556** [comment]
Merging to https://github.com/microsoft/vscode/issues/146422
