### ISSUE TITLE
Status bar doesn't reflect tab moves focus for editor

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#174702]
Set `editor.tabFocusMode: true` and focus an editor. 🐛 the status bar item doesn't show up

**Comment by bpasero** [comment]
I can reproduce still:
![Recording 2023-02-22 at 15 39 28](https://user-images.githubusercontent.com/900690/220655325-c2102a8a-da93-4905-b56d-f5db86f605c5.gif)
