### ISSUE TITLE
[Accessibility] Consider adding a setting to preserve focus in a11y terminal buffer

### ISSUE THREAD

**Issue by jooyoungseo** [microsoft/vscode#174793]
CC @meganrogge

There are many use cases where you want to open an editor and terminal side by side. This strategy is very useful for screen reader users since current terminal input area is not fully accessible, including auto-suggestion popup, etc.

so basically, you can input your code in the editor, send the code to terminal via the following commands: `Terminal: Run Selected Text In Active Terminal` and/or `Terminal: Run Active File In Active Terminal`.

In this case, screen reader users may want to quickly check executed output results through a11y terminal buffer as soon as they land in the terminal area. Currently, the default focus is set to terminal input when switched from another buffer.

## Suggested Solutions

I suggest the following:

1. Add a command, such as "Focus in accessibility terminal buffer" so that users can quickly jump into the terminal output area.

1. Add a user setting to choose the default landing point of terminal. Possible options are  "input" (default), "output" and "last position" (this remembers the last focus position before user leaves the terminal area).

## System Info

Version: 1.76.0-insider (system setup)
Commit: 96a795cc0b1cd62f9ff66c347637f917c6dde3da
Date: 2023-02-17T22:22:55.538Z
Electron: 19.1.9
Chromium: 102.0.5005.194
Node.js: 16.14.2
V8: 10.2.154.23-electron.0
OS: Windows_NT x64 10.0.22621
Sandboxed: Yes

**Comment by meganrogge** [comment]
> Add a command, such as "Focus in accessibility terminal buffer" so that users can quickly jump into the terminal output area.

We have a command that goes directly to the accessible buffer `Terminal: Focus 
Accessible Buffer`.
