### ISSUE TITLE
Getting errors when there aren't any?

### ISSUE THREAD

**Issue by Legitgamer264** [Microsoft/vscode#17470]
- VSCode Version: Insiders 1.9.0
- OS Version: Windows 10 Insider 14986

Whenever I open the source for ReditEnhancementSuite, I get this http://i.imgur.com/qufXOEj.png
I get "errors" when there aren't any. What is the issue? Here is what my folder looks like with the files http://i.imgur.com/7nweQfx.png

And here is what the red underline says - http://i.imgur.com/kRQQ2nA.png
How can I fix this?

**Comment by CoenraadS** [comment]
Try installing https://marketplace.visualstudio.com/items?itemName=rtorr.vscode-flow

**Comment by Legitgamer264** [comment]
@CoenraadS Thank you so much!
