### ISSUE TITLE
[wsl] VScode doesn't boot properly from "code ." in WSL

### ISSUE THREAD

**Issue by christophe-leblanc** [microsoft/vscode#174766]
- VS Code Version: 1.75.1
- OS Version: Microsoft Windows 10.0.19045.2486,

When using VScode opened via `code .`  with WSL, some features don't work automaticaly (i.e.: inline syntax checking and filename coloring based on github status).

The features are enabled in settings.json but they just don't work after booting VScode from the powershell.

The following trick makes it work though: going `WSL:Ubuntu` > `Reopen folder in Windows` then switching back to WSL.

Additional informations:
I don't have that problem if I open VScode on windows (no need to switch, features works directly).

I'm using GCC / Valgrind / CUnit.  

I have C/C++ extension properly installed for WSL.

Settings of my setting.json file are the default ones (the exact same has mentioned here: https://code.visualstudio.com/docs/getstarted/settings) plus those two lines: 

```
"C_Cpp.errorSquiggles": "enabled",
"C_Cpp.default.compilerPath": "C:\\msys64\\mingw64\\bin\\gcc.exe",
```

Content of my c_cpp_properties.json file: 
```
{
    "configurations": [
        {
            "name": "Linux",
            "includePath": [
                "${workspaceFolder}/**"
            ],
            "defines": [],
            "compilerPath": "/usr/bin/gcc",
            "cStandard": "c17",
            "cppStandard": "gnu++17",
            "intelliSenseMode": "linux-gcc-x64"
        }
    ],
    "version": 4
}
```

**Comment by xandora** [comment]
This is something I have also been experiencing on Windows 11 (22H2, 22621.1265) with the Insiders version. It appears that VSCode is no longer launching directly into WSL mode.

Additionally, the application is causing the terminal to get held up, much like launching a regular GUI application on a normal Ubuntu system (prompt pauses while waiting for application exit code). Whereas previously, it would correctly spawn the application as a separate process, and not a child of the shell.

Doing a bit of "live testing" while I write this post, it may be an issue with the 0.76.0 version of the VSCode WSL extension. Rolling it back to 0.75.3 appears to resolve the problem with launching VSCode in WSL mode directly. However, it stays resolved after updating again... 

So... possible solution for OP, roll the extension back, and the update it again?

**Comment by christophe-leblanc** [comment]
Thank you for the answer. I am not using Insiders and the last version of WSL available to me is already 0.75.3 though. Just to be sure, I tried rolling the extension back even to previous versions, but that didn't fix the problem, unfortunately.

**Comment by aeschli** [comment]
@christophe-leblanc Can you check that the extension are also installed in WSL? 

@xandora To find out why code doesn't open in a WSL window, can you run `VSCODE_WSL_DEBUG_INFO=true code-insiders.`

Whether the code command blocks the terminal depends on whether it starts the very first instance of VS Code. If VS Code is already open, it return to the prompt.

**Comment by christophe-leblanc** [comment]
@aeschli I have C/C++ Extension and C/C++ Extension Pack installed on both local and WSL. I'm also using Error Lens which doesn't have the option to be installed explicitly on WSL but it displayed: "This extension is enabled globally" (and I can use all features _on WSL_ after switching to windows then back to windows).

**Comment by christophe-leblanc** [comment]
I found the problem. This happens when I open VScode with `code .` from a symbolic link to a folder, when I open it directly from the folder I don't have the problem. Any idea how to fix this ?

**Comment by aeschli** [comment]
> I found the problem. This happens when I open VScode with code . from a symbolic link to a folder

Can you give more information? This is what I tried:

In a WSL terminal: 
- `ln -s ~/workspaces/vscode/ vscode`
- `cd vscode`, `code .`

This correctly opens VS Code on the `vscode` folder which is a link to `workspaces/vscode`
