### ISSUE TITLE
Test: builtin error render improvements

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#174728]
Refs: https://github.com/microsoft/vscode-jupyter/issues/12285

- [x] anyOS @aiday-mar
- [x] anyOS @TylerLeonhardt 

Complexity: 3

Authors: @rebornix @amunger 

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23174728%0A%0A&assignees=rebornix,amunger)

---

This iteration we improved the builtin notebook error renderer and removed the Jupyter error renderer, all users will get the Jupyter error renderer by default. To ensure users get a smooth transition from the Jupyter error renderer to the builtin one, we make following improvements:

* `notebook.outputLineHeight` polishes
* `notebook.output.wordWrap` to support line wrapping in text or error outputs
* Link detection improvements https://github.com/microsoft/vscode-jupyter/issues/9879

To test above changes, you would need to have a working Python/Jupyter environment. You can use the Dev Container for this test, for example:

* Install Dev Container remote extension
* From the remote picker, choose "Create Dev Container...". From the docker container images, choose Jupyter Data Science Notebook, or Anaconda.
* Once connected to the Container, install the Prerelease version of Jupyter and Python extensions
* Create an ipynb file to start testing. 

---

Note that currently we don't support hot reload of renderers when the settings change, so when testing above settings, please reload the window.

A very simple code snippet to test is

```python
print(x)
```

**Comment by bhavyaus** [comment]
@rebornix  I am unable to verify this since opening the remote connection gets stuck on: 
<img width="638" alt="image" src="https://user-images.githubusercontent.com/25044782/220474592-20bfb9ab-a1cb-438c-a1f8-2d241705178e.png">

Is there a specific setup configuration I need to get past this?

**Comment by TylerLeonhardt** [comment]
![image](https://user-images.githubusercontent.com/2644648/220494849-da33125d-c405-4fb5-b6fe-7328a2867704.png)

looks like link detection works nicely
