### ISSUE TITLE
Add option to hide view bar on focus change

### ISSUE THREAD

**Issue by CrafterKolyan** [microsoft/vscode#174796]
Can you please add feature to hide view bar on focus change?
It seems that usually you work either with files or with activity + view bars. It would be really nice for view bar to close when you start working with files or write code

To be sure we know what we are talking about
![image](https://user-images.githubusercontent.com/9883873/219964176-3820f40b-76d9-46cd-a391-5d3cd50db01e.png)

It would work something like this:
1. Working in activity + view bar area
![image](https://user-images.githubusercontent.com/9883873/219964353-c0e578b8-ba98-4dfa-b1ce-1cecc16dc208.png)
2. Clicking on an editor automatically closes view bar
![image](https://user-images.githubusercontent.com/9883873/219964393-2910b7bc-22e4-4cfa-b116-2eb4f105f045.png)

Other people also want this:
https://stackoverflow.com/questions/46676007/vs-code-setting-to-collapse-activity-bar-on-focus-change

**Comment by gjsjohnmurray** [comment]
See #3742
