### ISSUE TITLE
postCSS mixins are underlined by red squiggly lines 

### ISSUE THREAD

**Issue by Maryanos** [microsoft/vscode#174794]
Type: <b>Bug</b>

Hi,
I'm using PostCSS as my CSS compiler and can't get rid of those underlined errors VS code is serving me. 
All the mixins are working fine so this must be an issue with VS Code that is not recognise the postCSS mixin defining syntax. 
For Sass VS code is working perfect but when comes to the post CSS there must be something not right I guess.
Please see attached photo but you can also see more about my setup here where postCSS creators closed the thread already. 

https://github.com/postcss/postcss-mixins/issues/154

![Screenshot_18](https://user-images.githubusercontent.com/51508760/219960752-c653ed7c-6ce7-4de9-8c6d-f1095c6d5704.jpg)

VS Code version: Code 1.75.1 (441438abd1ac652551dbe4d408dfcec8a499b8bf, 2023-02-08T21:32:34.589Z)
OS version: Windows_NT x64 10.0.19044
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770K CPU @ 3.50GHz (8 x 3510)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.93GB (18.06GB free)|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (37)</summary>

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|15.1.0
vscode-django|bat|1.10.0
custom-window-zoom|cra|1.1.4
vscode-eslint|dba|2.4.0
vscode-faker|dee|2.0.0
python-environment-manager|don|1.0.4
python-extension-pack|don|1.7.0
gitlens|eam|13.2.0

vsc-material-theme|Equ|33.6.0
vsc-material-theme-icons|equ|2.5.0
live-sass|gle|6.0.2
vsc-python-indent|Kev|1.18.0
isort|ms-|2022.8.0
python|ms-|2023.2.0
vscode-pylance|ms-|2023.2.30
jupyter|ms-|2023.1.2010391206
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.14
vscode-jupyter-cell-tags|ms-|0.1.6
vscode-jupyter-slideshow|ms-|0.1.5
cpptools|ms-|1.14.3
color-highlight|nau|2.5.0
autodocstring|njp|0.6.1
vetur|oct|0.36.1
advanced-new-file|pat|1.2.2
vscode-gitignore-generator|pio|1.0.3
material-icon-theme|PKi|4.24.0
vscode-css-peek|pra|4.2.0
toggle|reb|0.0.2
LiveServer|rit|5.7.9
snippet-creator|rya|0.1.3
vscode-fileutils|sle|3.10.0
intellicode-api-usage-examples|Vis|0.2.7
vscodeintellicode|Vis|1.2.30
vscode-todo-highlight|way|1.0.5
jinja|who|0.0.8
html-css-class-completion|Zig|1.20.0

(5 theme extensions excluded)

</details>

**Comment by Maryanos** [comment]
Solved - PostCSS extension installed

**Comment by aeschli** [comment]
The built-in CSS extension only knows about what's in the CSS standard.

But you can configure the warning for unknown at-rules with the settings `css.lint.unknownAtRules`
