### ISSUE TITLE
Profiles indicator

### ISSUE THREAD

**Issue by andywillis** [microsoft/vscode#174727]
At the moment it's not very clear what profile is currently being used. An indicator (i.e. its name) on the status bar would be very useful.

**Comment by gjsjohnmurray** [comment]
This is coming, and can already be seen in Insiders.

![image](https://user-images.githubusercontent.com/6726799/219855201-c41cdf42-fecc-455b-959b-cf56960adc2c.png)

**Comment by isidorn** [comment]
Thanks. Closing as duplicate of https://github.com/microsoft/vscode/issues/166983
fyi @sandy081
