### ISSUE TITLE
Scrolling with the mouse pad changes the position of the cursor instead of scrolling the window

### ISSUE THREAD

**Issue by jacobmcgowan** [Microsoft/vscode#17476]
- VSCode Version: Code 1.8.0 (38746938a4ab94f2f57d9e1309c51fd6fb37553d, 2016-12-13T17:45:32.595Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

|Extension|Author|Version|
|---|---|---|
|vscode-npm-script|eg2|0.1.2|
|vscode-react-native|vsmobile|0.2.4|

---

Steps to Reproduce:

1. Open a file with multiple lines.
2. Scroll using the mouse pad.

Scrolling with the mouse wheel works as usual. Tried uninstalling and re-installing but the issue persists.

**Comment by rebornix** [comment]
@jacobmcgowan Speaking of `mouse pad`, are you referring to touch pad on your PC?

**Comment by jacobmcgowan** [comment]
Yes.

**Comment by alexandrudima** [comment]
I would report this against Chromium. Scrolling via trackpad or mouse wheel is all abstracted away for us by Chromium -- https://bugs.chromium.org/p/chromium/issues/list

**Comment by BladeMF** [comment]
Reported here:
https://bugs.chromium.org/p/chromium/issues/detail?id=784329&can=2&q=touchpad%20scroll&colspec=ID%20Pri%20M%20Stars%20ReleaseBlock%20Component%20Status%20Owner%20Summary%20OS%20Modified

**Comment by alexandrudima** [comment]
This is an upstream issue (possibly within Chromium), and there are no known workarounds that we could implement on our side. This means there is no possible code change for us to do in VS Code sources to improve things. 

To keep the number of issues in our inbox at a manageable level, we’re closing issues that have been on the backlog for a long time but haven’t gained traction or that are not actionable. Thank you for your time and understanding.
