### ISSUE TITLE
Profile export does not work on Windows in WSL

### ISSUE THREAD

**Issue by Yves-air** [microsoft/vscode#174865]
Type: <b>Bug</b>

**To Reproduce**
1.  Open VSCode WSL window
2.  Open a folder/worspace
3.  File::Preferences::Profiles::Export Profile
4.  Side bar with option "Export"/"Close" only (no selection of what to export). Click on Export
5. Text box "Name the profile", enter whatever name then Enter
6. Nothing (i.e. no selection for github/local, no popup for location, no saving, back to the editor like normal)

**Expected behavior**
Step 4: Show the settings to export (with selection)
Step 6: Offer option  for "Github" or "Local", then popup for location

VS Code version: Code 1.75.1 (441438abd1ac652551dbe4d408dfcec8a499b8bf, 2023-02-08T21:32:34.589Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: No
Remote OS version: Linux x64 5.15.79.1-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|12th Gen Intel(R) Core(TM) i7-12700H (20 x 2688)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.68GB (1.85GB free)|
|Process Argv|--file-uri vscode-remote://wsl%2Bubuntu-20.04/home/xxx/src/yyy.code-workspace --crash-reporter-id 11e04c7d-c6a6-46d6-8e98-de8116bb444c|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-20.04|
|OS|Linux x64 5.15.79.1-microsoft-standard-WSL2|
|CPUs|12th Gen Intel(R) Core(TM) i7-12700H (20 x 2688)|
|Memory (System)|7.60GB (4.93GB free)|
|VM|0%|
</details><details><summary>Extensions (18)</summary>

Extension|Author (truncated)|Version
---|---|---
remote-containers|ms-|0.275.1
remote-wsl|ms-|0.75.3
vim|vsc|1.24.3
vscode-markdownlint|Dav|0.49.0
go|gol|0.37.1
vscode-docker|ms-|1.23.3
isort|ms-|2022.8.0
python|ms-|2023.2.0
vscode-pylance|ms-|2023.2.30
jupyter|ms-|2023.1.2010391206
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.14
vscode-jupyter-cell-tags|ms-|0.1.6
vscode-jupyter-slideshow|ms-|0.1.5
cmake-tools|ms-|1.13.45
cpptools|ms-|1.14.3
cpptools-extension-pack|ms-|1.3.0
cmake|twx|0.0.17

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vscaac:30438847
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
azure-dev_surveyone:30548225
pyindex848:30662994
nodejswelcome1cf:30587006
2e4cg342:30602488
pyind779:30662992
f6dab269:30613381
pythonsymbol12cf:30657549

```

</details>

**Comment by sandy081** [comment]
May I know if following extensions are enabled in Extensions View

- `@builtin GitHub Authentication`
- `@builtin Configuration Editing`

**Comment by Yves-air** [comment]
I'm not sure how to check that.

**Comment by tapr00t** [comment]
I'm having a similar issue.  Export seems to work fine when I have VSCode opened on a local workspace.  But when I'm connected to a remote SSH VScode, the export contents are just empty/missing.  My goal is to share user+remote profile settings with team members.

**Comment by sandy081** [comment]
> I'm not sure how to check that.

In VS Code, Please open Extensions View

<img width="47" alt="image" src="https://user-images.githubusercontent.com/10746682/220656271-b9ccf733-8dc1-4ad4-93dc-526f7dc7e32d.png">

Please Type  `@builtin GitHub Authentication` in the search box at the top and let us know what it shows. Also do same for `@builtin Configuration Editing`.

Type `F1` > Type `Open View...` > Type `Window` - Share us the content in the window log

**Comment by sandy081** [comment]
Can you please try to reproduce with the insiders and let us know if you still see the issue - https://code.visualstudio.com/insiders/

**Comment by Yves-air** [comment]
With Insider and only the WSL extension, it seems to work.

**Comment by sandy081** [comment]
Thanks for confirming. I believe this is fixed in insiders as we started supporting profiles in remote workspaces. Hence closing this. Please try this out in the next stable release. Thanks.
