### ISSUE TITLE
Extension Page doesn't show repository info

### ISSUE THREAD

**Issue by tjx666** [microsoft/vscode#174883]
Reproduce:

1. search extension `husky-lang.husky-analyzer`
2. open it in vscode

![image](https://user-images.githubusercontent.com/41773861/220235470-ff6a3454-ab39-4b13-861f-ccb04b8153b9.png)

```
Version: 1.75.1 (Universal)
Commit: 441438abd1ac652551dbe4d408dfcec8a499b8bf
Date: 2023-02-08T21:34:59.000Z
Electron: 19.1.9
Chromium: 102.0.5005.194
Node.js: 16.14.2
V8: 10.2.154.23-electron.0
OS: Darwin x64 22.3.0
Sandboxed: No
```

**Comment by sandy081** [comment]
It seems the extension does not has Read Me and hence the details tab is not shown

**Comment by isidorn** [comment]
Leaving this open as it seems like a low-hanging fix. We could render the details tab even if the readme is not there.
Feel free to close as out of scope.
