### ISSUE TITLE
this.testRun.passed(test, duration) should also take messages.

### ISSUE THREAD

**Issue by ioquatix** [microsoft/vscode#174802]
@connor4312 

Tests can sometimes generate informational output, e.g. "iterations per second" or "total data transferred" or "warnings" are some examples I can think of, but I'm sure there are more.

I don't see why a passed test can't also have messages.

Can we add support for this?

Thanks.

**Comment by connor4312** [comment]
The recommended way to do this is use `appendOutput` and pass the `test` argument. Is there something different you're after?

**Comment by ioquatix** [comment]
I want to add messages to specific lines.

**Comment by connor4312** [comment]
`appendOutput` also has a location argument 🙂

**Comment by ioquatix** [comment]
Ohhh, I didn't know that. Thanks, I will try it.

Does it matter that the messages aren't attached to a specific test run?

**Comment by ioquatix** [comment]
When you use `testRun.failed(test, messages, ...)` are those messages attached to the test itself or just the testrun in general?

**Comment by connor4312** [comment]
They're associated to the test in that test run. Tests themselves don't "own" any state outside of what's given in the `TestItem` class; all states, messages, and output are in test runs.

**Comment by ioquatix** [comment]
I am okay with using `appendOutput`. I will simply process the messages in the same way and call `appendOutput` if the test passes, or use the existing arguments for messages if the test fails. I still think this method should take a list of messages, but that might be hard to change. So, it's up to you, if you want to close this issue, that's fine by me.

**Comment by connor4312** [comment]
yea, the messages on the failed state are a little different in that (a) they're richer and can have things like markdown and diffs, and (b) they signal the reason 'why' a test failed, where there isn't something as analogous for success.

**Comment by ioquatix** [comment]
I'm not sure why the same formatted output isn't valid for success too, basically. Certainly, `appendOutput` could take markdown.
