### ISSUE TITLE
Zoom level other than 0 causes blurriness in headless browser previews in extensions

### ISSUE THREAD

**Issue by henrikvilhelmberglund** [microsoft/vscode#174873]
Does this issue occur when all extensions are disabled?: No

- VS Code Version: 1.75.1
- OS Version: Win10 64bit

While this is not an issue when not running extensions since there's not really a browser in VSCode (simple browser didn't work for me at all), this issue is present in **all** extensions running headless browser instances to preview servers.

I first noticed the issue with the VSCode edge devtools where my zoom level was slightly zoomed in because I was on a laptop. Here's the issue reported in that repo: https://github.com/microsoft/vscode-edge-devtools/issues/1190

As you can notice in the images when zoomed in there's apparent aliasing of fonts and general blurriness. 

Steps to Reproduce:

1. Install an extension with a headless browser preview such as VSCode edge devtools.
2. Open a live server of a page with some text.
3. Change the zoom level to 3 or something very zoomed in.
Result: Text in VSCode preview is very blurry.
Expected: Text in VSCode preview is still sharp.
4. Change the zoom level to 0.
Result: Text in the VSCode is sharp(er).

**Comment by mjbvz** [comment]
Please start by filing this against the effected extension: edge dev tools

**Comment by henrikvilhelmberglund** [comment]
The problem is that this happens in every extension using headless browser previews, for example
[vscode-edge-devtool](https://github.com/microsoft/vscode-edge-devtools/issues/1190)
[vscode-browse-lite](https://github.com/antfu/vscode-browse-lite/issues/1)
[vscode-browser-preview](https://github.com/auchenberg/vscode-browser-preview/issues/75)

so if it is up to the extension authors to fix it it will likely never get fixed as it seems to be an issue within VSCode itself.

**Comment by mjbvz** [comment]
Headless browsers previews are not a built-in VS Code concept. File an issue against the relevant extensions. They can follow up with us if they determine VS Code is the root cause
