### ISSUE TITLE
Documentation: Extension Manifest doesn't exist

### ISSUE THREAD

**Issue by SetTrend** [Microsoft/vscode#1748]
The FAQ in the [Customize Visual Studio Code](https://code.visualstudio.com/docs/customization/overview) page points to a non-existing [Extension Manifest](https://code.visualstudio.com/docs/extensions/extension-manifest) page.

Clicking the link yields a 404.

**Comment by bpasero** [comment]
@chrisdias fyi

**Comment by chrisdias** [comment]
@gregvanl can you take a look?

**Comment by gregvanl** [comment]
Fixed in vscode-docs repo commit https://github.com/Microsoft/vscode-docs/commit/a0091326a57d770f032dd8210f5de9078136d868
