### ISSUE TITLE
The "Run and Debug" pane should have an option to open in a new tab/panel

### ISSUE THREAD

**Issue by PoignardAzur** [microsoft/vscode#174851]
I like to have a split editor with two active panes, and a rather small side gutter.

This is fine for most purposes, since I don't use the file explorer and the git ui that often, and when I do they need fairly little space because they're displaying fairly dense information.

The only exception is the "Run and Debug" pane. When you're in a debugging session, that pane suddenly has lots of very dense information: breakpoint lists, watchpoint lists, the call stack, and variable values. That last one in particular can get pretty rich, with multi-level container hierarchies and arrays and stuff.

Obviously, I can always increase the size of my left gutter when I'm debugging, and that's my current workaround. But I don't want my gutter to take half the screen space, whereas I *do* want all that debug info to take half the screen space. So what I would really like is for the debug info to be displayed in a separate tab, like the search results with the `"search.mode": "newEditor"` setting.

So what I would like would be some kind of `"debug.mode"` setting with a `"newPane"` option so I can really have that pane take lots of room.

**Comment by roblourens** [comment]
The best option for our current UX would be to move it into the bottom panel, but this is not currently supported: https://github.com/microsoft/vscode/issues/143264

**Comment by PoignardAzur** [comment]
I don't agree that putting Debug in a bottom panel would solve this. I want the debug pane to take a lot of space, more than you usually expect the bottom pane to take.

**Comment by roblourens** [comment]
I'm talking about the pane that takes the full remaining width of your window

**Comment by PoignardAzur** [comment]
Yes, but it usually takes very little height.

For comparison, I use `"search.mode": "newEditor"` because, when I opened search results into the bottom panels, I would either have a small bottom-pane and only see a few results at a time, or have a large bottom pane and hide contents for my open tabs. Having the search results displayed into a separate tab gave me more customization.

**Comment by PoignardAzur** [comment]
I still think this should be re-opened. The other issue this is marked as duplicating doesn't cover the same functionality I would want (an equivalent of `"search.mode": "newEditor"`)
