### ISSUE TITLE
looping

### ISSUE THREAD

**Issue by Joyman430** [microsoft/vscode#174890]
ADD ISSUE DESCRIPTION HERE

Version: 1.75.1
Commit: 441438abd1ac652551dbe4d408dfcec8a499b8bf
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36
Embedder: codespaces

**Comment by DonJayamanne** [comment]
Closing this issue due to lack of information
