### ISSUE TITLE
Test New Monaco Editor Playground

### ISSUE THREAD

**Issue by hediet** [microsoft/vscode#174870]
Refs: https://github.com/microsoft/monaco-editor/issues/3483

- [x] win @bhavyaus
- [x] mac @eleanorjboyd
- [x] linux @chrmarti

Complexity: 4

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23174870%0A%0A&assignees=hediet)

---

* The entire website at https://microsoft.github.io/monaco-editor/ is new, except the monarch page
* Try out the website, focus on the playground
    * Verify there is a bug in https://microsoft.github.io/monaco-editor/playground.html?source=v0.35.0-dev.20230206#example-creating-the-editor-hello-world when opening the quick pick (F1)
        * Try to find the last working version using the bisect buttons
* Try out [VS Code](https://github.com/microsoft/vscode) and [Monaco Editor](https://github.com/microsoft/monaco-editor) Launch Configs ("Monaco Editor Playground") in VS Code Desktop to develop and debug the monaco editor in the playground
    * verify breakpoints work (e.g. put a breakpoint in bracket pair colorization code or for monaco editor, typescript auto-complete code)
    * verify code changes work (reload the playground and make sure your changes are picked up)

**Comment by chrmarti** [comment]
@hediet Not sure if this is a coincidence, but when I use the launch config in VS Code the network goes down in my Linux VM on Parallels and when using a Linux VM on Azure with Remote-SSH the Remote-SSH connection drops. Is that launch config doing something specific with the network?

**Comment by bhavyaus** [comment]
Some of the examples from the example drop down list in the website do not work. Example: Hover Provider Example - The hover over the text is a no-op

**Comment by TylerLeonhardt** [comment]
Just wanted to say that I also gave this a try on my Ubuntu laptop, but unfortunately it's not powerful enough to run VS Code's build 😅

**Comment by chrmarti** [comment]
I couldn't get the Monaco Editor Playground launch config in the VS Code repo to work on any of my Linux VMs and I'm not sure if it's an issue with my setups or the launch config itself (thanks @TylerLeonhardt for giving this a try!), otherwise tested it for Linux.

**Comment by chrmarti** [comment]
Got the launch config in the VS Code repo working inside WSL (running VS Code inside WSL). Tested for Linux. 👍

**Comment by hediet** [comment]
> Not sure if this is a coincidence, but when I use the launch config in VS Code the network goes down in my Linux VM on Parallels and when using a Linux VM on Azure with Remote-SSH the Remote-SSH connection drops. Is that launch config doing something specific with the network?

I'm just launching an http server on port 5001 (VS Code) and 5002 (monaco-editor).

**Comment by hediet** [comment]
> Secondly, I ran the Monaco editor playground launch config and got the port for my localhost but when I loaded it into my browser it was unformatted and I didn't know where to go from there. What is the editor supposed to look like on load and any ideas where mine might have gone wrong if this behavior was unexpected?

The playground should show up and load the sources from monaco-editor/vscode:

![image](https://user-images.githubusercontent.com/2931520/220599869-d0d1a7a3-2ab4-49bb-8293-baa28d916ef2.png)

I pushed a fix to tweak the http server task config. Maybe it works better now.

**Comment by bhavyaus** [comment]
Got it going after Chrome install. Tested for windows.
