### ISSUE TITLE
Extension README markdown code block renders correctly in preview but not in published extension

### ISSUE THREAD

**Issue by sophodoros** [microsoft/vscode#174838]
Does this issue occur when all extensions are disabled?: No, because the issue is in an extension.

- VS Code Version: 1.75.1; 1.76.0-insider (4e321968)
- OS Version: Windows 11 (10.0.22621 Build 22621); Mac Ventura 13.1

When HTML is included in an extension's README.md file in a block of text indented with tabs to escape it, it is rendered correctly when viewed in VS Code's markdown preview window. By "correctly", this means that the text is rendered as-is so the escape characters are shown in the view. (That is also how they are shown in this bug ticket).

However, when the same block of text is viewed in an installed extension in VS Code via the extension's "Details" tab, the HTML escape sequences are processed and the resulting text is rendered as if the text had not been escaped. This is true whether the extension is installed from a local build of the extension via a .vsix file or whether the extension is installed from the Microsoft Marketplace. 

When the README is viewed in an extension's Details tab in the Microsoft Marketplace, it does NOT have this issue. 

There's more to this issue. In both VS Code's markdown preview and in the Marketplace, the text is rendered like this:

![image](https://user-images.githubusercontent.com/9784164/220122631-fbdd13c8-9b74-418d-a9ce-dc3e0f95f046.png)

However, in the extension's "Details" tab, it looks like this:

![image](https://user-images.githubusercontent.com/9784164/220122815-557170ab-5b1e-4605-ac8e-c895b8863faa.png)

As can be seen, in the "Details" tab's version not only is the "After" text rendered incorrectly, but the entire block is missing the gray background that denotes a code block in markdown.

Steps to Reproduce:

1. Add the text starting with "__Example:__" at the bottom of this ticket to an extension's README file. Note that the text following "__Example__" is indented by tabs to tell markdown to treat it as code. (The text has also been included in an attachment, since copying-and-pasting rendered markdown from the browser can be an issue).
2. View the README in VS Code's markdown preview window. The text after the "After escape" label is rendered as-is.
3. Use "vsce package" to build a .vsix file for the extension.
4. Install the .vsix file as an extension in VS Code.
5. View the installed extension's Details tab. 
6. If the problem exists, the gray background will be missing and the lines following the "Before escape" and "After escape" labels will be identical. If the problem is fixed, the gray background will be added and the text after the "After escape" label will be rendered as-is.
7. WORKAROUND: A workaround for this issue is to add 3 backticks on the lines before and after the section that is indented by tabs. 

__Example:__

	Before:
	Here's the test: a < b && b < c

	After escape:
	Here&apos;s the test: a &lt; b &amp;&amp; b &lt; c

[Example for ticket 174838.md](https://github.com/microsoft/vscode/files/10784653/Example.for.ticket.174838.md)

**Comment by Irvingouj** [comment]
Would you be more specific on what you mean by the "Details" tab?

**Comment by sophodoros** [comment]
Clicking "View" > "Extensions" on VS Code's toolbar (at least on the Mac) will show a list of installed extensions. If you select an extension, VS Code will display information about the extension. At the top of the screen of most extensions there are 4 tabs labeled "DETAILS", "FEATURE CONTRIBUTIONS", "CHANGELOG", and "RUNTIME STATUS". (A screenshot of Microsoft's C# extension is shown below.)

The "DETAILS" tab is what I was referring to in the repro steps. It displays the text from the extension's README.md file.

    
   
<img width="595" alt="Screenshot 2023-02-24 at 10 30 56 PM" src="https://user-images.githubusercontent.com/9784164/221334204-eb4e797f-ffed-4345-a4b8-0a53e0c46918.png">
