### ISSUE TITLE
Add `currentProfile` getter to API

### ISSUE THREAD

**Issue by nvlang** [microsoft/vscode#174806]
Add an analog of the [`${profileName}`](https://github.com/microsoft/vscode/blob/e3da120e0808f36e45e6783b611cc943d7fdd61c/src/vs/workbench/browser/workbench.contribution.ts#L505) variable from the [`window.title`](https://github.com/microsoft/vscode/blob/e3da120e0808f36e45e6783b611cc943d7fdd61c/src/vs/workbench/browser/workbench.contribution.ts#L518) setting to the Extension API, e.g. via a public getter to [`IUserDataProfileService.currentProfile`](https://github.com/microsoft/vscode/blob/d4237bd8d548a45e2759f3b3fe4fb75dfeb677a9/src/vs/workbench/services/userDataProfile/common/userDataProfile.ts#L32).

**Comment by sandy081** [comment]
Can you please be clear about what API you are asking for and why?

**Comment by nvlang** [comment]
I'm trying to write an extension that reads from- and writes to the `Code/User/snippets` directory. For writing, in particular, the usual [`globalStorage`](https://code.visualstudio.com/api/references/vscode-api#ExtensionContext.globalStorageUri) won't do, because the files written should be synced by VSCode's [Settings Sync](https://code.visualstudio.com/docs/editor/settings-sync) feature alongside all other snippets. For the default profile, this is no issue, but for all other profiles, that snippets directory is found at `Code/User/profiles/PROFILE_LOCATION/snippets`, where `PROFILE_LOCATION` is a (randomly generated?) string identifying a specific user profile. To write to such folders in accordance with the profile currently in use, an extension would need a way to know which profile is currently in use (and, ideally, its associated `PROFILE_LOCATION`).

I hope this clarifies my request, otherwise please let me know. Thank you so much for your time!

**Comment by sandy081** [comment]
> I'm trying to write an extension that reads from- and writes to the Code/User/snippets directory. For writing, in particular, the usual [globalStorage](https://code.visualstudio.com/api/references/vscode-api#ExtensionContext.globalStorageUri) won't do, because the files written should be synced by VSCode's [Settings Sync](https://code.visualstudio.com/docs/editor/settings-sync) feature alongside all other snippets.

May I know what you are writing into this folder? And why do you want them to synced?

**Comment by nvlang** [comment]
The idea would be to write snippets files in a different format, to be read by the extension itself (a snippet engine of sorts), rather than the built-in snippet controller. But since these files would still just be containers for snippets, it would be nice to have them synced alongside all other snippets, for the same reasons of convenience that might've compelled the user to sync their snippets in the first place.

**Comment by sandy081** [comment]
> The idea would be to write snippets files in a different format, to be read by the extension itself (a snippet engine of sorts), rather than the built-in snippet controller. 

It seems, you are wrongly using snippets folder for the purpose that we sync them. I am sorry that I cannot expose the API for this purpose. What you would need is this - https://github.com/microsoft/vscode/issues/113774

**Comment by nvlang** [comment]
> It seems, you are wrongly using snippets folder for the purpose that we sync them. I am sorry that I cannot expose the API for this purpose. What you would need is this - https://github.com/microsoft/vscode/issues/113774

[From that issue](https://github.com/microsoft/vscode/issues/113774#issuecomment-754540073):
>Extensions can now synchronize state in globalStorage, please file an issue against them.

I'm confused, did I miss something and `globalStorage` _is_ synced? I thought only `globalState` was. Would these fall under the "extensions" option of Settings Sync's "what to sync" question, or are they synced by a different process?

**Comment by sandy081** [comment]
Global Storage is not synced and the above issue is meant for the same purpose as yours to sync additional resources from extensions which are not in global state. But we have closed it for now as out of scope.
