### ISSUE TITLE
left and right arrow keys are not working in terminal

### ISSUE THREAD

**Issue by dev-phantom** [microsoft/vscode#174871]
Does this issue occur when all extensions are disabled?: Yes/No
yes

- VS Code Version: 1.75.1
- OS Version:  Linux x64 5.15.0-56-generic snap

Steps to Reproduce:

1. go to vscode terminal 
2. press the left arrow key

screenshot:
 
![Screenshot from 2023-02-21 00-11-02](https://user-images.githubusercontent.com/72051159/220212119-3f1b3f46-f720-4cbd-9ced-6437237a6618.png)

**Comment by dev-phantom** [comment]
> What do you expect the left arrow key to do here?

when i type a text in the terminal and i try to move left it trows that error

**Comment by meganrogge** [comment]
what's the error that's thrown?

**Comment by dev-phantom** [comment]
> what's the error that's thrown?

![image](https://user-images.githubusercontent.com/72051159/220467434-ec321cb0-37fd-44b7-b937-cb3e70f8960c.png)

**Comment by meganrogge** [comment]
That isn't an error -just information to tell you that left arrow doesn't do anything in the workbench because you haven't configured a keybinding for it

**Comment by dev-phantom** [comment]
> That isn't an error -just information to tell you that left arrow doesn't do anything in the workbench because you haven't configured a keybinding for it

Why do I have to configure it I thought by default the pointer ought to move left 🤔
