### ISSUE TITLE
problem with Linter installation

### ISSUE THREAD

**Issue by DMahmoodi** [Microsoft/vscode#17484]
- VSCode Version: Code 1.7.2 (7ba55c5860b152d999dda59393ca3ebeb1b5c85f, 2016-11-21T22:06:37.428Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

|Extension|Author|Version|
|---|---|---|
|python|donjayamanne|0.5.5|
|Spell|seanmcbreen|0.9.1|
|indenticator|SirTori|0.2.1|

---

Steps to Reproduce:

1.
2.
I am not sure about how to reproduce the error. It says at the top Linter in not installed. However, when I click install pylint. it gives me the following : 

D:\Coding\pythonCod>@python -m pip install pylint
Requirement already satisfied: pylint in c:\python27\lib\site-packages
Requirement already satisfied: astroid<1.5.0,>=1.4.5 in c:\python27\lib\site-packages (from pylint)
Requirement already satisfied: mccabe in c:\python27\lib\site-packages (from pylint)
Requirement already satisfied: configparser; python_version == "2.7" in c:\python27\lib\site-packages (from pylint)
Requirement already satisfied: backports.functools-lru-cache; python_version == "2.7" in c:\python27\lib\site-packages (from pylint)
Requirement already satisfied: six in c:\python27\lib\site-packages (from pylint)
Requirement already satisfied: colorama; sys_platform == "win32" in c:\python27\lib\site-packages (from pylint)
Requirement already satisfied: isort>=4.2.5 in c:\python27\lib\site-packages (from pylint)
Requirement already satisfied: wrapt in c:\python27\lib\site-packages (from astroid<1.5.0,>=1.4.5->pylint)
Requirement already satisfied: lazy-object-proxy in c:\python27\lib\site-packages (from astroid<1.5.0,>=1.4.5->pylint)

So it is installed but the error does not go away and keeps on coming back !!! 

Thanks

**Comment by mrmlnc** [comment]
Hello, @DMahmoodi,

If you look at the error, I'm not sure that this related to VS Code. In any case, this is not relevant to this repository and you need to create this question here: https://github.com/DonJayamanne/pythonVSCode

**Comment by kieferrm** [comment]
@DMahmoodi pls file the issue as described in the previous comment. Thanks!
