### ISSUE TITLE
Test: Sorting JSONC files

### ISSUE THREAD

**Issue by aiday-mar** [microsoft/vscode#174842]
Refs: https://github.com/microsoft/vscode/issues/155312

- [x] anyOS @sbatten 
- [x] anyOS @dbaeumer
- [x] anyOS @lramos15

Complexity: 2

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23174842%0A%0A&assignees=aiday-mar)

---

It is now possible to sort JSONC files. 

1. Open a JSONC document with no errors
2. Add block and line comments in the document
3. Select `JSON: Sort document` in the command palette
4. Check that the JSONC document is sorted as expected

**Comment by dbaeumer** [comment]
Works as advertised

**Comment by tjx666** [comment]
test failed here:

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/41773861/220979026-53940021-e45e-43cb-a037-0e74db08258f.png">

```
Version: 1.76.0-insider (Universal)
Commit: d0acdbff1f30eac7cc68930013485276d1bae0ec
Date: 2023-02-23T05:23:14.565Z
Electron: 19.1.10
Chromium: 102.0.5005.196
Node.js: 16.14.2
V8: 10.2.154.26-electron.0
OS: Darwin x64 22.3.0
Sandboxed: Yes
```

[settings.json.txt](https://github.com/microsoft/vscode/files/10816241/settings.json.txt)

**Comment by aiday-mar** [comment]
@tjx666 Thanks for filing the bug, there is a fix for this issue, that should be in the next release. Let me know if you continue seeing errors.
