### ISSUE TITLE
code not found in windows terminal

### ISSUE THREAD

**Issue by bckelley** [microsoft/vscode#174805]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 
Version: 1.75.1 (user setup)
Commit: 441438abd1ac652551dbe4d408dfcec8a499b8bf
Date: 2023-02-08T21:32:34.589Z
Electron: 19.1.9
Chromium: 102.0.5005.194
Node.js: 16.14.2
V8: 10.2.154.23-electron.0
OS: Windows_NT x64 10.0.19045
Sandboxed: Yes

- OS Version: 10.0.19045 Build 19045
- Windows Terminal Version: 1.16.10261.0

Steps to Reproduce:

![image](https://user-images.githubusercontent.com/15696431/219983846-3ec8a451-df0b-4f0c-9e06-a7ae84dc7895.png)

When I test the command it says True, but when I use the command says not recognized.

**Comment by meganrogge** [comment]
this means it's not on your `PATH` which you can verify via `echo $PATH`

**Comment by bckelley** [comment]
> this means it's not on your `PATH` which you can verify via `echo $PATH`

well that doesn't work and it is indeed in my $PATH, ok oops it was in the sys path not user path i don't know how that happened
