### ISSUE TITLE
Odd empty UI if there is no message on the test item?

### ISSUE THREAD

**Issue by ioquatix** [microsoft/vscode#174821]
![image](https://user-images.githubusercontent.com/30030/220047202-281e58d6-a740-4652-add8-46b9a5fee7f2.png)

It appears when providing test run messages, if there is no message for the test line itself, you end up with an empty box? Or maybe when using the error callback???

The JSON RPC between the test host and the extension:

```json
{"started":"test/utopia/content/links.rb:191"}
{"errored":"test/utopia/content/links.rb:191","messages":[{"text":"wrong number of arguments (given 1, expected 2..3)","location":{"path":"/home/samuel/Projects/socketry/utopia/test/utopia/content/links.rb","line":192}}],"duration":0.015189987607300282}
```

Where it gets mapped to vscode test run methods: https://github.com/ioquatix/sus-vscode/blob/96f5c46238488cd404269ef1008eb76e07d128c4/src/sus.ts#L379-L399

cc @connor4312

**Comment by ioquatix** [comment]
Honestly, these boxes just popping up is pretty annoying when editing the document, hitting save, they steal focus, etc. Can we have a discussion about how to improve the UI? Can we chat some time and I can screen share how it's all coming together if that's helpful?

**Comment by connor4312** [comment]
Configuring whether the view automatically opens can be done with the `testing.automaticallyOpenPeekView` setting. Is there behavior not expressed in that setting's options that you're looking for?

**Comment by ioquatix** [comment]
I didn't know about that option, I'll try it out and see if it can make the editing experience better.

**Comment by connor4312** [comment]
Hm, I'm not able to repro this very readily. Do you still hit it, and if so, are you able to extract a nice case in for example the [test provider sample](https://github.com/microsoft/vscode-extension-samples/tree/main/test-provider-sample)?

**Comment by ioquatix** [comment]
I can try to reproduce it again.

**Comment by connor4312** [comment]
Hey, haven't heard from this in a while. Going to close it for now, please let me know if you see it again / have a reproduction
