### ISSUE TITLE
Highlight code blocks in Markdown files

### ISSUE THREAD

**Issue by sryze** [microsoft/vscode#174813]
Multi-line code blocks need to be highlighted in different color inside Markdown, because right now they have the same color as regular text, and it's hard to tell at a glance where a code block begins and ends and it's easy to make a mistake.

Screenshot:
![image](https://user-images.githubusercontent.com/4525736/220018912-feaad157-af08-4c8b-9c80-86c08c52a732.png)

This is how the same code looks in GEdit, for example:
![image](https://user-images.githubusercontent.com/4525736/220018975-c28d23fa-d053-4758-ac8a-e3c9292ba23e.png)

**Comment by mjbvz** [comment]
Individual themes can chose to add colors for these code blocks. The relevant textmate scope is `markup.fenced_code.block.markdown`

You can also add colorization yourself using the `editor.tokenColorCustomizations` setting

**Comment by sryze** [comment]
It would make sense to add support for this to the default themes then, e.g. Dark+.
