### ISSUE TITLE
quick diff is showing wrong source

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#174896]
Testing #174853

- Checked out a PR. I used this https://github.com/microsoft/vscode/pull/164085
- Opened `src/vs/platform/request/browser/requestService.ts`
- Add a new line of text
- Click on the quick diff gutter indicator
 
🐛 Source is shown as GitHub Pull Request

<img width="1032" alt="image" src="https://user-images.githubusercontent.com/10746682/220307250-1f3c27fb-6345-4e99-83b1-cc7ca6c83450.png">

**Comment by alexr00** [comment]
This is by design. The GitHub pull request source shows diffs between your current file state and the PR base.

**Comment by sandy081** [comment]
In that case, how does Git diff option helps here? I mean to ask, will there be any diffs that git provider has but not the PR extension?

**Comment by alexr00** [comment]
The git provider will always be a subset of the PR provider. This is probably true of other extensions that could provide diffs in the future. For example, maybe Gitlens would let you set a specific commit to comapre against. Then you would always compare the current file state to the specified commit.

 The diff is always of this format:
- Base is provided by extension
- Modified is your current file state.
