### ISSUE TITLE
Please allow to change color theme of primary side bar, thanks

### ISSUE THREAD

**Issue by yulin0517** [microsoft/vscode#174831]
I  would like to change color theme of primary side bar.
 I don't like black primary sider bar, but I cannot change it now.

**Comment by gjsjohnmurray** [comment]
What about these?

https://code.visualstudio.com/api/references/theme-color#side-bar

**Comment by yulin0517** [comment]
Thanks John for your help. I tried this . it seems only to change the color of right panel( explorer) of primary side bar, but cannot change the color of left panel of primary side bar.

**Comment by gjsjohnmurray** [comment]
Are you talking about the Activity Bar? If so, see https://code.visualstudio.com/api/references/theme-color#activity-bar

**Comment by aeschli** [comment]
Thanks @gjsjohnmurray!
Closing the issue. @yulin0517, speak up if this isn't what you meant.
