### ISSUE TITLE
[Code - OSS] Right clicking on the code goes directly to the top menu options, thus triggering an unintentional event

### ISSUE THREAD

**Issue by st1vms** [microsoft/vscode#174897]
Type: <b>Bug</b>

When right clicking on code, the menu sometimes pop up (when "top" options should be behind the cursor), right behind the cursor... Basically firing the option right when i release the right mouse button. 

VS Code version: Code - OSS 1.75.1 (441438abd1ac652551dbe4d408dfcec8a499b8bf, 2023-02-09T20:16:38.064Z)
OS version: Linux x64 6.1.12-1-MANJARO
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 9 7950X 16-Core Processor (32 x 4478)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|1, 0, 0|
|Memory (System)|46.70GB (43.65GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|gnome|
|XDG_CURRENT_DESKTOP|GNOME|
|XDG_SESSION_DESKTOP|gnome|
|XDG_SESSION_TYPE|wayland|
</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
insert-unicode|bru|0.14.0
vscode-pull-request-github|Git|0.58.1
vscode-language-pack-it|MS-|1.75.0
cmake-tools|ms-|1.13.45
cpptools|ms-|1.14.1
hexeditor|ms-|1.9.11
ayu|tea|1.0.3
cmake|twx|0.0.17
vscode-icons|vsc|12.2.0

</details>

**Comment by deepak1556** [comment]
Merging to https://github.com/microsoft/vscode/issues/113175
