### ISSUE TITLE
New Window Behaviour broke

### ISSUE THREAD

**Issue by philXYZ1** [Microsoft/vscode#17485]
- VSCode Version: 1.8.0 (1.8.0)
- OS Version: macOS Sierra 10.12.2

For me, the last months when working VSCode,
spawning a new window with Shift + CMD + n has openened a new window as a 'tab' above the editor,
but in the same instance.

I found this incredibly useful for working with multiple projects in the same VSCode window.

However, this was removed in 1.8, now a new window is openened.
Was this removed, or can i somehow enable this behaviour again?
I've read through the docs & the settings but couldn't find anything related.

thanks in advance

**Comment by mrmlnc** [comment]
Please, provide more detailed information (steps to reproduce, screenshots, gif/video, etc).

**Comment by philXYZ1** [comment]
sorry for the empty post, I accidentally hit enter before writing anything - now the post is updated.

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/17199
