### ISSUE TITLE
remain focus on editor after "Run Selected Text in Active Terminal"

### ISSUE THREAD

**Issue by dongzhuoer** [microsoft/vscode#174814]
Type: <b>Bug</b>

`settings.json`
```json
{
    "terminal.integrated.defaultProfile.windows": "Git Bash"
}
```
`keybindings.json`
```
[
{
"key": "ctrl+enter",
"command": "workbench.action.terminal.runSelectedText",
"when": "editorTextFocus"
},
]
```
`Untitled-1`
```
# test
ls ~/Downloads
```
move cursor to 2nd line, press `Ctrl+Enter`, then `Arrow Up`

VS Code version: Code - Insiders 1.76.0-insider (96a795cc0b1cd62f9ff66c347637f917c6dde3da, 2023-02-17T22:22:55.538Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 5600U with Radeon Graphics          (12 x 2296)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.35GB (7.07GB free)|
|Process Argv|--crash-reporter-id 25b1e70e-d4e9-425f-9d63-5152a73e085b|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (17)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-quick-select|dba|0.2.9
gitlens|eam|13.2.0
html-preview-vscode|geo|0.2.5
rainbow-csv|mec|3.5.0
git-graph|mhu|1.30.0
python|ms-|2023.2.0
vscode-pylance|ms-|2023.2.30
jupyter|ms-|2023.1.2010391206
jupyter-keymap|ms-|1.0.0
remote-ssh|ms-|0.96.0
remote-ssh-edit|ms-|0.84.0
remote-explorer|ms-|0.2.0
r|REd|2.7.1
markdown-preview-enhanced|shd|0.6.7
pdf|tom|1.2.2
vscodeintellicode|Vis|1.2.30
vscode-ruby|win|0.28.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30422396
pythontb:30258533
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscod805:30301674
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30404738
cppdebug:30492333
vsclangdf:30492506
c4g48928:30535728
dsvsc012:30540252
pynewext54:30618038
pylantcb52:30590116
pyindex848:30611229
nodejswelcome1:30587009
pyind779:30611226
vscrpc:30624061
pythonsymbol12:30651887
6233i204:30659907
pythonb192cf:30661257

```

</details>

**Comment by dongzhuoer** [comment]
I made a GIF with VSCode Insider v1.76.0 (commit: c9e3ef865539061b5602c6b9ac6030332aa1ce70), and VSCode v1.75.0 behaved the same.
![insider](https://user-images.githubusercontent.com/15871952/217123713-f6543a4e-c7da-483a-9cb8-83eb87e39803.gif)

**Comment by dongzhuoer** [comment]
Here's the behavior of VSCode v1.74.0
![code](https://user-images.githubusercontent.com/15871952/217124116-eb651725-301c-40af-b6b2-d1c3a15219a3.gif)

**Comment by pirfalt** [comment]
I also want the v1.74.0 behaviour back.

I want to _keep editor focus_ when running commands.
Or frased differently, I would like to _not loose focus_.

`{"terminal.integrated.defaultLocation": "editor"}` is sort of cool, but does not help me.

**Comment by marcinnajder** [comment]
Hi, I encountered the same issue :( losing editor focus is very annoying, REPL programming cannot be used at all because of it, please restore previews behaviour, thanks

**Comment by Tyriar** [comment]
This is already fixed, it'll be released in the upcoming version (probably tomorrow or the day after)
