### ISSUE TITLE
F11 (step into) when debugging always triggers the Full Screen command

### ISSUE THREAD

**Issue by PeterFromSweden** [microsoft/vscode#174832]
Does this issue occur when all extensions are disabled?: Yes/No
No

- VS Code Version: 1.75.1
- OS Version: Ubuntu 20.04.5 LTS

Steps to Reproduce:

1. Extension C/C++ and cmake
2. Set breakpoint on call
3. Press F11
4. Fullscreen toggles.
5. This happens even when deleting setting fro fullscreen F11 via File > Preferences > Keyboard shortcuts

**Comment by roblourens** [comment]
This has been reported before on Linux. It seems like there might be some OS-level override for F11? You might check that for Ubuntu, or you will have to use a different key for "step in".

You can verify that it isn't vscode by running the command "Toggle keyboard shortcut troubleshooting" and checking whether a vscode command actually runs when pressing F11

**Comment by PeterFromSweden** [comment]
Hi
You are of course right. I use Lubuntu desktop and remapped F11 according
to:
http://openbox.org/wiki/Help:Bindings

Den tis 11 apr. 2023 kl 19:34 skrev Rob Lourens ***@***.***>:
