### ISSUE TITLE
Opening a new README.md file spawns an editor tab with an empty package.json

### ISSUE THREAD

**Issue by raggi** [microsoft/vscode#174888]
Type: <b>Bug</b>

* Close all editor windows/processes
* In any arbitrary directory that does not contain README.md, start vscode to create README.md, e.g. `code --disable-extensions README.md`

Objserve that an empty tag named package.json is also opened.

VS Code version: Code 1.75.1 (441438abd1ac652551dbe4d408dfcec8a499b8bf, 2023-02-08T21:32:34.589Z)
OS version: Windows_NT x64 10.0.22621
Modes: Restricted
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 9 3950X 16-Core Processor             (32 x 3493)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|63.95GB (46.60GB free)|
|Process Argv|--disable-extensions README.md --crash-reporter-id 758ab3e3-554b-42be-bf3e-fc90d9d92702|
|Screen Reader|no|
|VM|0%|
</details>Extensions disabled<details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
azure-dev_surveyone:30548225
pyindex848:30662994
nodejswelcome1cf:30587006
2e4cg342:30602488
pyind779:30662992
f6dab269:30613381
pythonsymbol12cf:30657549
2i9eh265:30646982
6233i204:30664135
vsccsb:30662443

```

</details>

**Comment by bpasero** [comment]
This originates from here:

https://github.com/microsoft/vscode/blob/aa1006552fbd1640f3a7586737a4a190feade60f/extensions/extension-editing/src/extensionLinter.ts#L343-L354

The editor just makes sure that dirty documents are made visible.
