### ISSUE TITLE
C# IntelliSense Hints are unreadable (new lines are missing)

### ISSUE THREAD

**Issue by marekadamczyk** [Microsoft/vscode#17487]
- VSCode Version: Code 1.8.0 (38746938a4ab94f2f57d9e1309c51fd6fb37553d, 2016-12-13T17:45:32.595Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

|Extension|Author|Version|
|---|---|---|
|csharp|ms-vscode|1.5.3|
|mono-debug|ms-vscode|0.12.0|
|unity-debug|Unity|1.1.0|

---

Steps to Reproduce:

1. Open any C# project containing sln and csproj file so full IntelliSense will be working.
2. Hover your mouse over any function containing C# XML Comments with summary, more than one parameter, and return tags.

Below example code and the IntelliSense hint containing parsed XML documentation. If it contains more than one tag (ex. few function parameters + returns) all are **displayed in one line therefore it is unreadable**. It seems that new lines are missing between `<param>` and `<returns>` tags.

![code](https://cloud.githubusercontent.com/assets/8941375/21294525/eef2a1cc-c53e-11e6-8e81-7f11b6bf5c7b.png)
![hint](https://cloud.githubusercontent.com/assets/8941375/21294605/eef7288a-c540-11e6-8f4a-150e822195a6.png)

**Comment by kieferrm** [comment]
@marekadamczyk pls file the issue with the C# extension. They track their issues here: https://github.com/OmniSharp/omnisharp-vscode/issues  Thanks!
