### ISSUE TITLE
Scrollable notebook output is not keyboard shortcut-friendly

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode#174984]
Testing #174637

There's no way to use keyboard shortcuts to
    - move focus to the notebook output editor when focus is on the notebook cell list, notebook cell container, or notebook cell input editor    
    - scroll through the notebook output editor contents
    - select sections in the output for Windows Narrator to read

**Comment by amunger** [comment]
still need to fix scrolling with keyboard - re-opening

**Comment by amunger** [comment]
screen reader issues still need work but are covered elsewhere.

**Comment by joyceerhl** [comment]
I still do not see a way to move focus from the cell container or the cell editor into the cell output:

1. If I have focus on a cell container and hit tab once, focus is immediately set to the cell editor contents, and subsequent tabs insert tab literals in the cell editor
2. If I click into the notebook cell output and hit enter, focus is set to the cell editor contents

**Comment by amunger** [comment]
you can either use ctrl+m to enable `tab moves focus` in order to tab there, or the command `Notebook: focus in cell output` to go there directly from the input or the container.

**Comment by joyceerhl** [comment]
:clap: works as expected!
