### ISSUE TITLE
Search results don't refresh when opening notebook from Explorer or File picker

### ISSUE THREAD

**Issue by TylerLeonhardt** [microsoft/vscode#174963]
Testing #174724

Steps to repro:
* open VS Code repo
* search for `repo:microsoft/vscode` (see results)
* open `api.github-issues` either from the Explorer or `cmd/ctrl`+`p` file picker

Search results don't refresh to the rich search:
![image](https://user-images.githubusercontent.com/2644648/220421592-7864dfed-498b-41be-9511-fe11f07fab64.png)

**Comment by andreamah** [comment]
Strange, I can't seem to repro. Am I doing this correctly?
![Recording 2023-02-21 at 13 37 33](https://user-images.githubusercontent.com/31675041/220464299-8aea2632-353f-4ff9-b95d-9bfd63eb860a.gif)

**Comment by TylerLeonhardt** [comment]
That's exactly what I'm doing on macOS.

**Comment by andreamah** [comment]
that's so strange... I just tried on Linux too and I'm not seeing this bug. Is it happening with other notebook types?
