### ISSUE TITLE
clicking on a locally changed line should open that view

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#174983]
Testing #174853

`// my change` is a local change. I click on that line and i'd expect to see the selected dropdown item `Git local working changes` but instead it's the PR one

https://user-images.githubusercontent.com/29464607/220427675-bcd1f900-a073-4301-8501-e092401096dc.mov

**Comment by meganrogge** [comment]
even when it's a deletion and I select that, it does not show me the expected one 


https://user-images.githubusercontent.com/29464607/220428546-71be6541-3d67-4bec-9b08-645f84341636.mov

**Comment by meganrogge** [comment]
I think the dropdown is hard to discover, which is why I think it's important to set the selection based on which line was clicked.

**Comment by meganrogge** [comment]
guessing this is not working because the local change is within the remotely changed lines

**Comment by alexr00** [comment]
> I think the dropdown is hard to discover, which is why I think it's important to set the selection based on which line was clicked.

The diff is always between the extension provided base and your current file state. So, for lines that you have changed locally, there's a diff for "GitHub Pull Request #" and for "Git local working changes". Both are correct if you click on a locally changed line.

**Comment by alexr00** [comment]
I could give priority to diffs from scm if the line you click on has more than one provider. Would you expect that?

**Comment by alexr00** [comment]
Making the change to prefer the SCM provided diff here: https://github.com/microsoft/vscode/issues/174950

**Comment by meganrogge** [comment]
@alexr00 I think this can be closed and just verified it now works as expected
