### ISSUE TITLE
"Tab Moves Focus" shown in the status bar even when it's only applicable to the terminal

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#174925]
Testing #174707

1.
```
	"terminal.integrated.tabFocusMode": true,
	"editor.tabFocusMode": false
```
2. Focus into the editor.
3. The status bar still says "Tab Moves Focus". I think I'd only expect it to say that when I'm focused in the terminal.

**Comment by meganrogge** [comment]
If you toggled it to on in the editor before focusing the terminal, then this is expected. We remember the toggled state for each context

**Comment by alexr00** [comment]
I never toggled it at all, this was just using the settings.
