### ISSUE TITLE
Terminal links in a pwsh session using OSC 8 on Windows are not clickable

### ISSUE THREAD

**Issue by TylerEich** [microsoft/vscode#174981]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.75.1
- OS Version: Windows_NT x64 10.0.19044

Steps to Reproduce:

1. Open the Integrated Terminal to a pwsh session
2. Run the two commands: `sh -c "printf '\x1b]8;;https://github.com\x07GitHub\x1b]8;;\x07'"` and `sh -c "printf '\e]8;;http://example.com\e\\This is a link\e]8;;\e\\'"`
3. See this output 
![VS Code Terminal](https://user-images.githubusercontent.com/3460063/220427332-121cd1a8-0750-4780-9841-1db65ee1bd66.png)
4. Compare to Windows Terminal for the same steps
![Windows Terminal](https://user-images.githubusercontent.com/3460063/220427564-5bb2af87-e614-45e4-81a0-54eb0bb38624.png)

**Comment by Tyriar** [comment]
This is because of conpty which is shipped with Windows, support will eventually come when you upgrade Windows (provided it's supported in conpty, I can't remember the status).
