### ISSUE TITLE
bugg

### ISSUE THREAD

**Issue by SilchuGabs** [microsoft/vscode#174944]
Type: <b>Bug</b>

bug

VS Code version: Code 1.75.1 (Universal) (441438abd1ac652551dbe4d408dfcec8a499b8bf, 2023-02-08T21:34:59.000Z)
OS version: Darwin x64 22.1.0
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-1068NG7 CPU @ 2.30GHz (8 x 2300)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|7, 6, 6|
|Memory (System)|32.00GB (5.31GB free)|
|Process Argv|--crash-reporter-id 80f11b15-0b42-4ffa-bf6f-98987cf3fbbe --crash-reporter-id 80f11b15-0b42-4ffa-bf6f-98987cf3fbbe|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (88)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|3.0.2
emmet-keybindings|agu|1.2.1
react-vsc-essentials|agu|1.0.0
TabOut|alb|0.2.2
Bookmarks|ale|13.3.1
html-class-suggestions|And|1.1.1
jest-faster|ano|0.0.3
html-end-tag-labels|ant|0.10.0
file-browser|bod|0.2.11
htmltagwrap|bra|0.0.7
vscode-toggle-quotes|Bri|0.3.6
emmet-jss|car|1.0.0
directory-files|cas|0.0.5
npm-intellisense|chr|1.4.4
path-intellisense|chr|2.8.4
gitignore|cod|0.9.0
vscode-eslint|dba|2.4.0
javascript-vue|Dig|0.3.2
vscode-new-file|dku|4.0.2
githistory|don|0.6.19
es7-react-js-snippets|dsz|4.4.3
Vue2|duc|0.1.3
gitlens|eam|2023.2.2004
vscode-html-css|ecm|1.13.1
EditorConfig|Edi|0.16.4
vscode-npm-script|eg2|0.3.29
prettier-vscode|esb|9.10.4
comment-anchors|Exo|1.10.3
mithril-emmet|Fal|0.7.7
vscode-jest-runner|fir|0.4.60
auto-close-tag|for|0.5.14
auto-rename-tag|for|0.1.10
code-runner|for|0.12.0
copilot-nightly|Git|1.73.8842
vscode-pull-request-github|Git|0.58.2
vscode-graphql|Gra|0.8.5
vscode-graphql-syntax|Gra|1.0.6
vscode-test-explorer|hbe|2.21.1
vue-snippets|hol|1.0.4
html-tag-wrapper|hwe|0.2.3
easy-snippet|inu|0.6.3
hungry-delete|jas|1.7.0
polacode-2019|jef|0.6.1
vscode-jest-test-adapter|kav|0.8.1
vscode-cfn-lint|kdd|0.24.2
vue-beautify2|ker|0.0.3
auto-comment-blocks|kev|1.0.1
vue-format-markdoyle|mar|0.1.9
vscode-language-babel|mgm|0.0.36
git-graph|mhu|1.30.0
vscode-checkpoints|mic|1.3.3
dotenv|mik|1.0.1
goto-next-previous-member|mis|0.0.6
vscode-duplicate|mrm|1.2.1
vscode-docker|ms-|1.23.3
remote-containers|ms-|0.275.1
test-adapter-converter|ms-|0.1.6
vscode-typescript-tslint-plugin|ms-|1.3.4
vsliveshare|ms-|1.0.5831
vscode-react-native|msj|1.10.0
abracadabra|nic|7.0.0
copy-json-path|nid|0.3.0
prettier-standard-vscode|num|1.0.2
vetur|oct|0.37.2
indent-rainbow|ode|8.3.1
vscode-jest|Ort|5.2.3
advanced-new-file|pat|1.2.2
emoji|Per|1.0.1
prettier-now|rem|1.4.9
vscode-sort-json|ric|1.20.0
LiveServer|rit|5.7.9
es7-react-js-snippets|rod|1.9.3
vs-code-prettier-eslint|rve|5.0.4
partial-diff|ryu|1.4.3
vscode-javascript-booster|sbu|14.0.1
vue-vscode-snippets|sdr|3.1.1
comment-divider|sta|0.4.0
autoimport|ste|1.5.4
code-spell-checker|str|2.17.1
vscode-stylelint|sty|1.2.4
sort-lines|Tyr|1.9.1
errorlens|use|3.7.0
volar|Vue|1.1.5
vscode-typescript-vue-plugin|Vue|1.1.5
quokka-vscode|Wal|1.0.526
vscode-todo-highlight|way|1.0.5
JavaScriptSnippets|xab|1.8.0
vscode-surround|yat|1.5.0

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
azure-dev_surveyone:30548225
vscccc:30610679
pyindex848:30662994
nodejswelcome1cf:30587006
3biah626:30602489
pyind779cf:30662993
f6dab269:30613381
pythonsymbol12:30657548
a9j8j154:30646983
vsctsb:30662444

```

</details>

**Comment by DonJayamanne** [comment]
Closing this issue due to lack of information.
