### ISSUE TITLE
Moving explorer restores NPM script view

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#174904]
Testing #174718

* primary sidebar on the right, secondary sidebar on the left
* the primary sidebar has just the explorer and all other views hidden
* secondary sidebar has outline and open editor
* drag the explorer to the secondary sidebar
* :bug: the explorer _and_ npm script view show in the secondary sidebar

https://user-images.githubusercontent.com/1794099/220326459-6ba35734-fca5-447b-a393-036512a14f99.mp4

**Comment by lramos15** [comment]
Assigning to @sbatten as this happens to any view. Tried with search for example.
