### ISSUE TITLE
terminal does not respond?!

### ISSUE THREAD

**Issue by Abdulrahman-Samir041** [microsoft/vscode#174989]
ADD ISSUE DESCRIPTION HERE

Version: 1.75.1
Commit: 441438abd1ac652551dbe4d408dfcec8a499b8bf
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36 Edg/110.0.1587.50
Embedder: codespaces

Hi,
I have an issue with VS code space recently.
Sometimes when I try to type on terminal, it doesn't respond or show what I have typed.
Also VS code space lags from time to time with no reason, although I keep it updated as possible

**Comment by meganrogge** [comment]
disable `terminal.integrated.gpuAccleration` as it's not supported on certain versions of safari

/duplicate #165416
