### ISSUE TITLE
Python3 support?

### ISSUE THREAD

**Issue by HankB** [Microsoft/vscode#17498]
- VSCode Version: Code 1.7.2 (7ba55c5860b152d999dda59393ca3ebeb1b5c85f, 2016-11-21T22:14:18.217Z)
- OS Version: Linux x64 4.4.0-47-generic
- Extensions:

|Extension|Author|Version|
|---|---|---|
|python|donjayamanne|0.5.4|
|Go|lukehoban|0.6.50|

---

Steps to Reproduce:

1. Edit a Python 3 file with a bang path '#!/usr/bin/env python3'
2.Type '<ctrl>s' to save
3. Click the button that offers to install pylint. It will run the command 

    python -m pip install pylint

If that command succeeds, it will install the Python 2 version of pylint.

Some systems install Python 3 and related commands with '3' tacked on to the end. VS code can examine the bang path to determine if this is necessary and if so, the '3' can be tacked on to most, if not all other commands.  Ubuntu 16.04 is a Linux distro that tacks a '3' on to the end of every command. Manjaro does not.

**Comment by kieferrm** [comment]
Pls file the issue against the python extension: https://github.com/DonJayamanne/pythonVSCode/issues

Thanks!
