### ISSUE TITLE
Integrated terminal - View: Toggle Maximized Panel - leads to duplicate the first letter written in terminal after each toggle

### ISSUE THREAD

**Issue by pjtallon** [microsoft/vscode#174943]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.75.1
- OS Version: Windows_NT x64 10.0.19044

Steps to Reproduce:

1. Configure the "View: Toggle Maximized Panel" as "Alt + `"
2. Configure an integrated terminal
3. open an integrated terminal in VSCode
4. Write first letter in terminal -> no disruption.
5. toggle maximized panel
6. Write one letter in the terminal -> notice a single stroke puts two characters which are effectively passed to the terminal.

As additional information, I am using mainly cygwin terminal integrated in VSCode, however I noticed the same issue using ubuntu on windows (WSL2) and Powershell.

I made some research for duplicates, but I haven't been able to find one.

Best,
Julien

**Comment by meganrogge** [comment]
Thanks for the issue, a gif would be helpful

**Comment by pjtallon** [comment]
Hello @meganrogge,
I have the gif file, but my corporate laptop prevents me from uploading files in github for security reasons.
I have sent you an email at [merogge@microsoft.com](mailto:merogge@microsoft.com) with the gif attached and a reference to this record.
Best,
Julien

**Comment by meganrogge** [comment]
Thanks for the gif, seems similar to https://github.com/microsoft/vscode/issues/143103#issuecomment-1210661038

**Comment by meganrogge** [comment]
![output](https://user-images.githubusercontent.com/29464607/220419708-838aaa44-2a16-43e3-919b-a853550867c0.gif)
