### ISSUE TITLE
Raw search gives me a search result I want while rich search does not

### ISSUE THREAD

**Issue by TylerLeonhardt** [microsoft/vscode#174968]
Testing #174724

Possibly related to #174966

Raw search has results from the output of a cell:
![image](https://user-images.githubusercontent.com/2644648/220422585-e2a2a1ed-7584-43ac-aed3-20aa925953e7.png)

Rich search does not (I expected two "hello 2"s):
![image](https://user-images.githubusercontent.com/2644648/220422894-f1271664-f15f-4cc7-aadb-446411eb42f7.png)

Find widget doesn't have this result: 
![image](https://user-images.githubusercontent.com/2644648/220422971-bfbb2812-9632-4898-a202-0bcf8aad5e42.png)

**Comment by andreamah** [comment]
Rich doesn't support outputs yet, it'll be added in the second part of https://github.com/microsoft/vscode/issues/164926
