### ISSUE TITLE
Scroll position in large cell not preserved on editor close 

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#174918]
Testing #174637

`"notebook.experimental.outputScrolling": true`

Have the following code in an notebook cell. Run the code
```python
for i in range(1000):
    print(i)
```

Scroll the output.

Close the whole notebook editor. Open it again.
Notice how the whole notebook editor remembered the scroll position. But the output cell is scrolled back to the top 🐛 
I would expect the output cell to also preserve scroll position.

**Comment by amunger** [comment]
tracking this as part of https://github.com/microsoft/vscode/issues/174636
