### ISSUE TITLE
Notebook output scrollbar is sticky

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode#174990]
Testing #174637

Elsewhere in VS Code we have a pattern that we flash the scrollbar briefly before it fades out when a scrollable region first receives focus. The notebook output editor is currently inconsistent in that the output scrollbar is always shown.

**Comment by r3m0t** [comment]
With the editor there is some knowledge from the user about where they are in the document, and it doesn't update itself. With notebook output that isn't the case as it depends how long the cell's been running, etc so the scrollbar needs to remain visible.

Unless this can be turned off - as requested in #66000

**Comment by amunger** [comment]
From what I can tell, the implementation is too complex to be worth doing here
