### ISSUE TITLE
notebook.output.textLineLimit, notebook.output.wordWrap, notebook.outputLineHeigh should not require VS Code reload

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#174908]
Testing #174637

Currently the settings `notebook.output.textLineLimit`, `notebook.output.wordWrap` and `notebook.outputLineHeigh` are very hard to use because they require a reload.
Can we fix this so they do not require a reload? For example, the notebook could listen on these setting changes and re-render when needed?
If this is not possible, we should at least mark it in settings description that a reload is required.

**Comment by rebornix** [comment]
@amunger `notebook.output.textLineLimit`, `notebook.output.wordWrap` and `notebook.outputLineHeight` are applied to the renderers when they are modified. The only one left is output scrolling setting.

**Comment by amunger** [comment]
made a new issue for output scrolling specifically https://github.com/microsoft/vscode/issues/175780
