### ISSUE TITLE
Testing links in Quick Input Box: No underline

### ISSUE THREAD

**Issue by bamurtaugh** [microsoft/vscode#174962]
Testing #174700 in a simple test extension.

I can click on the link (which I've named `link` below), but it isn't underlined:

![image](https://user-images.githubusercontent.com/25310137/220418687-d6aa0e2d-62a5-46da-aa6b-c225f63b9b30.png)

The toast displays the hyperlink in blue, but there is also no underline (though I think that's expected here):

![image](https://user-images.githubusercontent.com/25310137/220419087-b40be513-3c60-417d-bfed-cb15d8d67e57.png)

This is the piece of code I added:
```
const result = vscode.window.showInputBox({
		value: 'abcdef',
		valueSelection: [2, 4],
		placeHolder: 'For example: fedcba. But not: 123',
		prompt: 'Please enter a value and [link](https://github.com)',
		validateInput: text => {
			vscode.window.showInformationMessage(`Validating [link](https://github.com): ${text}`);
			return text === '123' ? 'Not 123!' : null;
		}
	});
	vscode.window.showInformationMessage(`Got: ${result}`);
```

**Comment by bamurtaugh** [comment]
I also don't see a link when using `vscode.window.createInputBox`. Example of a clickable and tab-able link in the validation message, just no underline:

![image](https://user-images.githubusercontent.com/25310137/220422671-ddc0343e-904a-4df7-8569-66644fdadf03.png)

Code:

```
const inputBox = vscode.window.createInputBox();
inputBox.title = vscode.l10n.t('Create new title');
inputBox.placeholder = vscode.l10n.t('New placeholder');
inputBox.prompt = vscode.l10n.t('Please enter a value and [link](https://github.com)');
inputBox.validationMessage = vscode.l10n.t('This is my [link](https://github.com)');
inputBox.show();
```

**Comment by TylerLeonhardt** [comment]
It looks like there is a global stylesheet that gets applied when building the product. In any case, I have a fix out.
