### ISSUE TITLE
markdown.suggest.paths.includeWorkspaceHeaderCompletions default should be onSingleOrDoubleHash

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#174920]
Testing #174884

Could we change the default of `markdown.suggest.paths.includeWorkspaceHeaderCompletions` to be `onSingleOrDoubleHash`?

Can we influence the sorting in the suggest widget such that the current file suggestions are sorted to the top?
Or at least that they have a different icon?

My concern is that with the other default this cool feature will be very undiscoverable.

What do you think?

**Comment by mjbvz** [comment]
There’s a cost to computing these suggestions, especially the first time before we have cached them. These suggestions can also result in a lot of extra suggestion item 
 that may confuse users if they aren’t expecting them

That’s why we require a more explicit trigger of these completions by default, while also giving users a setting to enable them more easily
