### ISSUE TITLE
Emoji keyboard not working

### ISSUE THREAD

**Issue by cesarvarela** [Microsoft/vscode#17499]
#- VSCode Version: 1.8
- OS Version: macOS Sierra

Steps to Reproduce:

1. Bring the emoji keyboard
2. Try to insert an emoji either by clicking on it or by moving the arrow keys as pressing enter

**Comment by bpasero** [comment]
Seems to work fine for me:

![dec-19-2016 20-31-07](https://cloud.githubusercontent.com/assets/900690/21326269/26dc5f9c-c62a-11e6-8fa3-4f7f1fc2d686.gif)

**Comment by cesarvarela** [comment]
I think it depends on the context,

This is a .ts file, I trigger the panel with `ctrl+cmd+space`, and now it works but does some random shit:

![dec-19-2016 16-39-28](https://cloud.githubusercontent.com/assets/1172479/21326510/c6799c84-c609-11e6-81ad-2b4bf1201cd0.gif)

**Comment by mjbvz** [comment]
The text corruption looks like a duplicate of #16562 

The panel showing in the wrong location is being tracked by #13093

**Comment by cesarvarela** [comment]
Oh yes this is definitively a duplicate of #16562
