### ISSUE TITLE
"window.openFilesInNewWindow": false||true  = true. This setting is not valid.

### ISSUE THREAD

**Issue by Harris-Aaron** [Microsoft/vscode#17493]
- VSCode Version: 1.8.0 (1.8.0)
- OS Version: macOS 10.12.1

Steps to Reproduce:

1.  Set this operation `"window.openFilesInNewWindow": false,` or  `"window.openFilesInNewWindow": true,`  Is invalid.
2. I think that opening a single file independently opens a new window.
    Open multiple files at the same time only open a window.
    Allows multiple folders (items) to exist in the same window or tab for easy switching and easy editing.
3. Thanks for providing such excellent vscode.

**Comment by kieferrm** [comment]
@Harris-Aaron when you have `"window.openFilesInNewWindow": true` and you open a file from the Finder than a new window is opened. When you have `"window.openFilesInNewWindow": false` and you open a file from the Finder the file is opened in an existing window.
