### ISSUE TITLE
Find widget not finding results

### ISSUE THREAD

**Issue by TylerLeonhardt** [microsoft/vscode#174966]
Testing #174724

* Open `endgame.github-issues`
* Search for a word in one of the GitHub Issue Notebooks results:

![image](https://user-images.githubusercontent.com/2644648/220422101-bb344824-33f9-40a2-82b4-73b05127dfef.png)

No results even though I can see the word.

**Comment by andreamah** [comment]
That's technically a cell output (read-only), which isn't supported yet.
