### ISSUE TITLE
I tried to open my codespace but nothing loads

### ISSUE THREAD

**Issue by rashika-k** [microsoft/vscode#174911]
I tried to open my codespace but nothing loads

Version: 1.75.1
Commit: 441438abd1ac652551dbe4d408dfcec8a499b8bf
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36
Embedder: codespaces

**Comment by chrmarti** [comment]
Please report issues for GitHub Codespaces at https://github.com/community/community/discussions/categories/codespaces-feedback. Thanks.
