### ISSUE TITLE
Links to files with spaces in name aren't linkified when spaces are escaped

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode#174998]
Testing #174884

```md
<!-- Good -->
[foo](foo%20bar.md#a-header)
 <!-- Bad --> 
[foo](<foo bar.md#a-header)
```

<img width="300" alt="image" src="https://user-images.githubusercontent.com/30305945/220439008-2d627bb4-b1d7-4175-a45a-50bf5b57b7ad.png">

**Comment by mjbvz** [comment]
@joyceerhl Sorry my example was a bit misleading. In this case the entire link needs to be wrapped by `<...>`. It should work once you add the closing `>` at the end:

<img width="493" alt="Screenshot 2023-02-21 at 10 23 32 PM" src="https://user-images.githubusercontent.com/12821956/220521502-3ed5a2cb-0e4b-4f9d-a88a-2e913b3c6bd5.png">
