### ISSUE TITLE
File search - navigate history with arrow keys, and fields with tabs?

### ISSUE THREAD

**Issue by fabiospampinato** [Microsoft/vscode#17492]
Sublime gives us the ability to cycle through the previous search queries using the arrow keys, the same way as when using a terminal.

Would be cool to have this features also in VSC.

**Comment by roblourens** [comment]
This actually exists, using alt+up/down. The arrow keys alone move focus around, which I think is more commonly used.

**Comment by roblourens** [comment]
I think it probably works this way because 'tab' goes to the option buttons (maybe an accessibility requirement). I personally like the current behavior but I'll leave this issue open for any other opinions on changing it so that arrow keys navigate history and tab goes through the fields.

**Comment by fabiospampinato** [comment]
I think this way it's fine, those shortcuts should probably be advertised a little more though.

If the behavior of the tab key changes than people can't toggle anymore the buttons, which assuming somebody does would make the change break things for them.

**Comment by allancm** [comment]
Weird I have installed version 1.10.1 and I can only move in the history of search by Alt+Up or Alt+Down in the search of the file but not in the "Find in files" or "Replace in files".  I think when the feature is enabled it should be easy to know actually it's present in a combo as it is implemented in Visual Studio 2015.

**Comment by umpirsky** [comment]
Would be cool to be able to navigate files to include the same way. Atom can.

**Comment by megatux** [comment]
This feature is not complete. You can navigate through your search term history but you _can't_ do the same with file include/exclude patterns.

**Comment by roblourens** [comment]
That should be fixed in 1.15, actually

**Comment by roblourens** [comment]
I noticed that we have https://github.com/Microsoft/vscode/issues/12645 tracking this
