### ISSUE TITLE
Add option to delete files to the trash can instead of unrestorable delete

### ISSUE THREAD

**Issue by velara3** [microsoft/vscode#174975]
When deleting a file from the Source Control panel, the dialog does a great job of explaining that the file will be permantly deleted. Well done. But, is there an option in vscode to have the deleted file sent to the trash can instead? 

Here is the current dialog: 

<img width="269" alt="image" src="https://user-images.githubusercontent.com/1084127/220426425-17540f89-f374-4037-a944-70a8cadafead.png">

**Comment by lszomoru** [comment]
@velara3, apologies for not getting back to you on this. When you click "Delete file" VS Code will shell out to git.exe and run `git clean -f -q`. Unfortunately git.exe is not able to place these items into the trash can.
