### ISSUE TITLE
Double Cancel Buttons Mac Native Dialog Box

### ISSUE THREAD

**Issue by eleanorjboyd** [microsoft/vscode#174995]
Testing #174784

Testing with the native dialog on mac and seeing two cancel buttons when I am asked for workspace trust. This occurred when I did the following steps

1. Opened a trusted workspace
2. used the command palette to change to change that workspace to untrusted
3. reloaded the window

<img width="1521" alt="Screenshot 2023-02-21 at 10 59 05 AM" src="https://user-images.githubusercontent.com/26030610/220435410-0aaeb2e5-3cb6-4613-9a30-e71b88d80d91.png">

after clicking "cancel" it then showed this error prompt:
<img width="1728" alt="Screenshot 2023-02-21 at 10 59 21 AM" src="https://user-images.githubusercontent.com/26030610/220435448-bf938d68-1603-4624-b703-ef56c5d3f444.png">

**Comment by eleanorjboyd** [comment]
Ok I tried to reproduce this issue again following the steps I outlined above and it didn't work so feel free to close the issue if it doesn't come up for you.

**Comment by bpasero** [comment]
Good catch, looking at the code I see that this might happen.
