### ISSUE TITLE
Hard to tell that there are completions from other files if current file has many headers

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode#174994]
Testing #174884

When I typed `##` for a text link in https://github.com/microsoft/vscode-docs/blob/main/release-notes/v1_54.md#L12, it wasn't immediately clear to me that there were completions from other files, because the completions from the current file occupied the visible entries. Could we consider only showing completions from other files when in the `##` mode? It seems like it would be easy for users to toggle between the two modes.

<img width="1022" alt="image" src="https://user-images.githubusercontent.com/30305945/220434929-a15acc25-3f87-428c-a929-0f50294da98f.png">

**Comment by mjbvz** [comment]
I felt it would be strange that if you are searching for a specific header by name, headers in the current file don't show up. We also allow showing these project wide suggestions on a single `#` using the setting
 
---

In the completion list, completions to headers in other files have a label on the right side of the completion item and details in the expanded suggest widget that explain these are links to other files:

<img width="1563" alt="Screenshot 2023-02-21 at 10 07 50 PM" src="https://user-images.githubusercontent.com/12821956/220519516-2c285bcb-984a-4cfa-a583-67fd847cb989.png">

We don't include the additional label for links on the current file (the text for the currently selected item in the screenshot is populated automatically)

Let me know if you have other ideas to make this difference even more obvious (I'd like a custom suggest item icon, but none of the existing ones are good fits)
