### ISSUE TITLE
Quick Diff - Unexpected peek render in added file

### ISSUE THREAD

**Issue by lramos15** [microsoft/vscode#174950]
Testing #174853

1. Have a file that was added
2. Make some local changes
3. Click the quick quick diff gutter
4. 😮 The range is correct but it renders at the bottom of the file rather than where I selected.

It is especially weird in a large file because then scrolling to the place in the gutter you clicked before and clicking it again is hiding the peek, but you actually don't see that. Instead it appears nothing is happening.

**Comment by alexr00** [comment]
The peek opening at the end of the range is how quick diff has always worked as far as I know. It looks like it might be most useful to open the SCM provided diff though when a range has both an SCM and non-SCM diff (https://github.com/microsoft/vscode/issues/174983), which should help with this. 

I'll make the change to prefer opening the SCM diff.
