### ISSUE TITLE
Tasks are not showing up every other time I open VSC

### ISSUE THREAD

**Issue by pierrewtLanca** [microsoft/vscode#174932]
Type: <b>Bug</b>

Hi,
Since some new updates, Visual Studio code doesn't work well on one thing and it gets me upset as it makes me waste time.
My project contains a tasks.json file that lives in .vscode folder, and before when I opened the editor, I could just run the listed tasks from the Terminal menu > "Run task....", they'd be listed there.
Now, when I open the editor this isn't showing any longer, and need to restart the editor so they get loaded the second time.
Please fix...
Thanks,
Pierre

VS Code version: Code 1.75.1 (441438abd1ac652551dbe4d408dfcec8a499b8bf, 2023-02-08T21:32:34.589Z)
OS version: Windows_NT x64 10.0.19044
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4700HQ CPU @ 2.40GHz (8 x 2394)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: unavailable_off<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.89GB (7.29GB free)|
|Process Argv|--crash-reporter-id e2390edc-396d-4b01-be73-e46830edef65|
|Screen Reader|no|
|VM|50%|
</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-yarn-script|car|0.0.1
vscode-eslint|dba|2.4.0
gitlens|eam|13.2.0
rest-client|hum|0.25.1
git-graph|mhu|1.30.0
isort|ms-|2022.8.0
python|ms-|2023.2.0
vscode-pylance|ms-|2023.2.30
jupyter|ms-|2023.1.2010391206
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.14
vscode-jupyter-cell-tags|ms-|0.1.6
vscode-jupyter-slideshow|ms-|0.1.5
js-debug-nightly|ms-|2023.2.317
vetur|oct|0.37.2

</details>

**Comment by pierrewtLanca** [comment]
Hi Megan,

Thanks for your answer.  As it seems, the problem has not occured again
today, maybe I needed to wait that something else loads before reaching the
tasks.
Or restarting my laptop solved something.

Best,
Pierre

Le mar. 21 févr. 2023 à 15:39, Megan Rogge ***@***.***> a
écrit :

**Comment by capc0** [comment]
same issue appeared here. Tasks defined in `tasks.json` stopped showing in the command palette. After reloading all windows they appeared again.

No idea how to reproduce atm.

macOS with M2 chip.
