### ISSUE TITLE
delete call in API does not call autoClosingPairDelete

### ISSUE THREAD

**Issue by xconverge** [Microsoft/vscode#17490]
I am trying to invoke the autoClosingPairDelete function from the api

In the source code I see:
```
public static deleteLeft(config: CursorConfiguration, model: ICursorSimpleModel, cursor: SingleCursorState): EditOperationResult {
let r = this.autoClosingPairDelete(config, model, cursor);
```

So then I call vscode.window.activeTextEditor.edit with an edit.delete for one char to the left. It does not seem that this snippet of code is executed.

Is there an API call to be able to use the autoClosingPairDelete functionality?

**Comment by rebornix** [comment]
Right now the function @xconverge mentioned is bind to command `deleteLeft`. When you press backspace in vanilla Code, Code will actually execute command `deleteLeft`. That's why `TextEditorEdit.delete` doesn't share the same logic.

**Comment by alexandrudima** [comment]
This is by design. Doing edits via `textEditor.edit` does not include any magic, it simply applies those edits.
