### ISSUE TITLE
User settings (JSON) open with `file` scheme when previously opened with `vscode-userdata` scheme

### ISSUE THREAD

**Issue by amunger** [microsoft/vscode#174971]
Steps to Reproduce:

1. Open a workspace and create a new file
2. run command `Preferences: Open user settings (JSON)`
3. go the new untitled file and ctrl+s to open the save as dialog
:bug: dialog is in the user settings folder rather than the workspace folder

does not repro in stable

**Comment by bpasero** [comment]
This works as expected, we have logic to suggest a path that is either derived from the last active file you had opened or the workspace:

<img width="853" alt="image" src="https://user-images.githubusercontent.com/900690/220710170-306ea7e0-8665-473c-bb69-6b4cbca42554.png">

Code is here:

https://github.com/microsoft/vscode/blob/b438c3854c2541f349b99e94411f1d91186827ae/src/vs/workbench/services/dialogs/browser/abstractFileDialogService.ts#L59-L76

As such, when a file is opened from user data folder, we suggest to save it there. I am reluctant to change that.

**Comment by lramos15** [comment]
> As such, when a file is opened from user data folder, we suggest to save it there. I am reluctant to change that.

Maybe I don't understand the use case enough, but I agree with the last active file *if* it is inside the workspace, but otherwise I assume most files I save would be workspace related and I would not want to be suggested a random directory to a one off file I opened outside the workspace, but I would probably need to understand more how many people are saving in vs out of workspace files.

**Comment by amunger** [comment]
I'm talking about saving an untitled file here, I have to imagine that in the vast majority of cases, a user will want to save a new file into their workspace. 
If I happen to open user settings at some point before trying to save an untitled file, that doesn't really change where I would prefer to save that file.

**Comment by bpasero** [comment]
Yes, the user settings file case is not a good real world scenario I would assume. But if you open loose files outside of the workspace and want to add another one there, it might come in handy.

To be fair, no user has complained so far, at least as far as I can remember. Though we have https://github.com/microsoft/vscode/issues/115730 for the case where we just fallback to user home dir when no file was opened.

**Comment by amunger** [comment]
The same repro case does not occur for me in stable

**Comment by bpasero** [comment]
@sandy081 I see a behavioural change between stable and insiders. When opening user settings (JSON) the `URI` used to be with scheme `vscode-userdata` and it is now `file`. As such, we actually consider it when proposing a folder path for the untitled file.

Can you confirm this was an intended change?

**Comment by sandy081** [comment]
This was not intended and it seems slipped in this PR - https://github.com/microsoft/vscode/pull/174392.

Thanks for catching this. Fixed - https://github.com/microsoft/vscode/pull/175212 

But I do not know if this fixes this scenario.

**Comment by bpasero** [comment]
Yes it will because we have a scheme filter.
