### ISSUE TITLE
Esc not working on trusted workspace dialog

### ISSUE THREAD

**Issue by eleanorjboyd** [microsoft/vscode#174996]
Testing #174784

This might just be a desired workflow since the window was just opened but wanted to identify it anyways.

1. Open a new workspace (done via the open new folder dialog on a new vscode window)
2. see the workspace trust dialog
3. esc key doesn't work

<img width="1111" alt="Screenshot 2023-02-21 at 10 40 54 AM" src="https://user-images.githubusercontent.com/26030610/220435998-006795c0-8011-45da-bb5c-0f96d3c7bb78.png">

**Comment by bpasero** [comment]
Yes, I should have been explaining this better in the TPI: very few dialogs actually prevent cancellation. For trust you must make a decision, there is no alternative. So great that we validated this is still the case!
