### ISSUE TITLE
Markdown snippets not appearing 

### ISSUE THREAD

**Issue by rahji** [microsoft/vscode#174974]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version:  1.75.1
- OS Version: Windows 11 Education 10.0.22621 Build 22621

Steps to Reproduce:

1. Open a new or existing Markdown file
2. Type "code" - the "Insert inline code" snippet (and other snippets matching that pattern, eg: "fenced codeblock") should appear near the cursor.
3. Pressing tab will insert the snippet, but the dropdown never appears. "Insert Snippet" from the Command Palette also works.

* I have made no changes to my settings since this worked earlier this week
* I have tried starting with all extensions off.
* I have tried VS Code Insiders. 
 
Snippets are working as expected with other languages (eg: javascript)

<img width="333" alt="image" src="https://user-images.githubusercontent.com/442495/220428324-12c5d1f2-6f08-4a2e-af37-43400fc6584c.png">

Considering the latest version of VS Code included changes related to issues regarding snippets, I believe a bug may have been introduced.

**Comment by rahji** [comment]
In Insiders, I am trying all possible combinations of settings that I can think of. Like I said, I have not changed my settings in my normal installation of VS Code.

```json
{
    "editor.inlineSuggest.enabled": true,
    "editor.snippetSuggestions": "top",
    "editor.tabCompletion": "onlySnippets",
    "editor.quickSuggestions": {
        "other": "off",
        "comments": "off",
        "strings": "off"
    },
    "editor.suggest.snippetsPreventQuickSuggestions": true

}
```

**Comment by mjbvz** [comment]
See https://stackoverflow.com/questions/43639841/how-to-set-markdown-snippet-trigger-automatically

**Comment by rahji** [comment]
Thank you for this. I still have no idea why this occurred all of a sudden. This brought the behavior back to where it was, though.
