### ISSUE TITLE
Scroll slowly when extension section visible

### ISSUE THREAD

**Issue by strrchr** [Microsoft/vscode#17497]
- VSCode Version: Code 1.8.0 (38746938a4ab94f2f57d9e1309c51fd6fb37553d, 2016-12-13T17:45:32.595Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions:

|Extension|Author|Version|
|---|---|---|
|xml|DotJoshJohnson|1.6.0|
|auto-close-tag|formulahendry|0.3.6|
|auto-rename-tag|formulahendry|0.0.8|
|green-theme|vscode|0.1.0|
|beautify|HookyQR|0.6.2|
|cpptools|ms-vscode|0.9.3|
|vscode-icons|robertohuertasm|4.2.0|

---

Steps to Reproduce:

1. Ctrl+Shift+X
2. For the main area, click and hold the vertical scroll bar, drag upward and downward, it responses slowly.
3. There is no problem when explore section, search section, git section, or debug section visible.

**Comment by kieferrm** [comment]
Not an issue on macOS.

**Comment by joaomoreno** [comment]
What are your machine specs?
