### ISSUE TITLE
Deleting an added line shows weird quickdiff

### ISSUE THREAD

**Issue by lramos15** [microsoft/vscode#174952]
Testing #174853

1. Have a PR that adds a line
2. Delete that line locally
3. 🐛 The GHPR changes don't show the added line anymore in the diff

**Comment by alexr00** [comment]
This is expected. The diff is always the current file state compared with the extension provided base. In this case:
- Base: PR base
- Modified: Current file on disk

Neither have the line, so there is no diff.
