### ISSUE TITLE
Explorer: Does not sort files and folders with numerical values accordingly

### ISSUE THREAD

**Issue by AStodgyGuy** [Microsoft/vscode#17495]
- VSCode Version: Code 1.8.0 (38746938a4ab94f2f57d9e1309c51fd6fb37553d, 2016-12-13T17:45:32.595Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

|Extension|Author|Version|
|---|---|---|
|python|donjayamanne|0.5.5|
|java-debug|DSnake|0.0.2|
|cpptools|ms-vscode|0.9.3|
|csharp|ms-vscode|1.5.3|
|java|redhat|0.0.7|

---

Steps to Reproduce:

1. Create 3 folders called "Folder 1" , "Folder 2" and "Folder 10"
2. Folder 10 appears in between Folder 1 and Folder 2. 

![image](https://cloud.githubusercontent.com/assets/22627577/21296369/0e56db32-c562-11e6-8238-40c3295dd7a2.png)

**Comment by kieferrm** [comment]
The macOS Finder, for example, handles this case correctly.

**Comment by bpasero** [comment]
@joaomoreno do you recall any reason why we are not using the `comparers.compareFileNames` for folders in https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/files/browser/views/explorerViewer.ts#L654 ?

**Comment by bpasero** [comment]
This actually happens for files and folders. A good area for a PR 👍

**Comment by gulshan** [comment]
@bpasero As related, can #5222 also be included in February Milestone?

**Comment by bpasero** [comment]
Unlikely.
