### ISSUE TITLE
Error in the tokenization on Mac

### ISSUE THREAD

**Issue by paulacamargo25** [microsoft/vscode#175002]
Testing #174869

As you can see the tokenization works fine, but when I get to a line or scroll to a certain part, it totally disappears.

https://user-images.githubusercontent.com/17892325/220441689-48fae80d-7425-4b3e-bcfe-3508c1928cce.mov

**Comment by hediet** [comment]
Can you try this again? We no longer tokenize excessively long lines.

**Comment by hediet** [comment]
Should be fixed now.
