### ISSUE TITLE
Refused to set unsafe header proxyAuthorization

### ISSUE THREAD

**Issue by PaulRijkes** [Microsoft/vscode#17502]
- VSCode Version: 1.8.0
- OS Version: Windows 7 Professional Service Pack 1
- Installed Chrome version: 55.0.2883.87 m

I'm having trouble to configure Visual Code to use the local proxy here.
Settings wise I think I'm doing everything OK, but Visual Code won't load extensions or do a version update check. In both cases no message or error is displayed, so I've no idea what I'm doing wrong.

When I open the Developer Tools, I do see errors (on opening Visual Code):
```
Refused to set unsafe header "Proxy-Authorization"
  o @ workbench.main.js:132
https://marketplace.visualstudio.com/_apis/public/gallery/extensionquery Failed to load resource: net::ERR_TUNNEL_CONNECTION_FAILED
```

On opening the Extensions tab (View -> Extensions)
````
×＞Refused to set unsafe header "Proxy-Authorization"
  o @ workbench.main.js:132
  (anonymous function) @ workbench.main.js:132
  n.Class.derive._oncancel @ workbench.main.js:32
  t.xhrRequest @ workbench.main.js:132
  e.request @ workbench.main.js:132
  n.request @ workbench.main.js:132
  (anonymous function) @ workbench.main.js:132
  then @ workbench.main.js:32
  e.queryGallery @ workbench.main.js:132
  e.query @ workbench.main.js:132
  e.queryGallery @ workbench.main.js:91
  t.query @ workbench.main.js:129
  t.doSearch @ workbench.main.js:128
  (anonymous function) @ workbench.main.js:128
  e.queue @ workbench.main.js:32
  (anonymous function) @ workbench.main.js:32
  (anonymous function) @ workbench.main.js:32
  g @ workbench.main.js:32
  enter @ workbench.main.js:32
  _run @ workbench.main.js:32
  _completed @ workbench.main.js:32
  (anonymous function) @ workbench.main.js:32
×＞POST https://marketplace.visualstudio.com/_apis/public/gallery/extensionquery net::ERR_TUNNEL_CONNECTION_FAILED
  (anonymous function) @ workbench.main.js:132
  n.Class.derive._oncancel @ workbench.main.js:32
  t.xhrRequest @ workbench.main.js:132
  e.request @ workbench.main.js:132
  n.request @ workbench.main.js:132
  (anonymous function) @ workbench.main.js:132
  then @ workbench.main.js:32
  e.queryGallery @ workbench.main.js:132
  e.query @ workbench.main.js:132
  e.queryGallery @ workbench.main.js:91
  t.query @ workbench.main.js:129
  t.doSearch @ workbench.main.js:128
  (anonymous function) @ workbench.main.js:128
  e.queue @ workbench.main.js:32
  (anonymous function) @ workbench.main.js:32
  (anonymous function) @ workbench.main.js:32
  g @ workbench.main.js:32
  enter @ workbench.main.js:32
  _run @ workbench.main.js:32
  _completed @ workbench.main.js:32
  (anonymous function) @ workbench.main.js:32
×＞An unknown error occurred. Please consult the log for more details.
  e.doShow	@	workbench.main.js:94
  e.show	@	workbench.main.js:94
  t.onError	@	workbench.main.js:129
  (anonymous function)	@	workbench.main.js:128
  done	@	workbench.main.js:32
  v	@	workbench.main.js:32
  enter	@	workbench.main.js:32
  _run	@	workbench.main.js:32
  _chainedError	@	workbench.main.js:32
  n	@	workbench.main.js:32
  v	@	workbench.main.js:32
  enter	@	workbench.main.js:32
  _run	@	workbench.main.js:32
  _error	@	workbench.main.js:32
  (anonymous function)	@	workbench.main.js:32
  done	@	workbench.main.js:32
  v	@	workbench.main.js:32
  enter	@	workbench.main.js:32
  _run	@	workbench.main.js:32
  _error	@	workbench.main.js
````
Same issue as #6480? (closed with commit df2bf8b)

Steps to Reproduce:

1. Open user settings (File -> Preferences -> User Settings)
2. Set the following settings:
- http.proxy (http://server:port/)
- http.proxyAuthorization (Basic encoded-base64-username:password-string)
- http.proxyStrictSSL (false)
3. Restart Visual Studio Code
4. Open the Developer Tools (Help -> Toggle Developer Tools)
5. Open the Console tab within the Developer Tools

**Comment by abargstaedt** [comment]
We have exactly the same problem here since they have introduced the new configuration parameter "http.proxyAuthorization".
`Refused to set unsafe header "Proxy-Authorization"
Failed to load resource: net::ERR_TUNNEL_CONNECTION_FAILED`

**Comment by joaomoreno** [comment]
cc @jrieken

**Comment by jrieken** [comment]
I'd say it needs another case here: https://github.com/Microsoft/vscode/blob/master/src/vs/platform/request/electron-browser/requestService.ts#L75

**Comment by joaomoreno** [comment]
Wow, is that a GOTO statement?

**Comment by jrieken** [comment]
You gotta use what a programming language offers ;-)

**Comment by joaomoreno** [comment]
```
(m => `are ${(w => `you ${m} about`)``} that`)`sure`
```

**Comment by jrieken** [comment]
Well, at least for labels we have *mark occurrences* 

![screen shot 2017-01-04 at 09 55 34](https://cloud.githubusercontent.com/assets/1794099/21636697/f3c0689c-d263-11e6-9fd4-b7dd17f464d0.png)

**Comment by joaomoreno** [comment]
👍  Set

I still don't understand what that `outer` is doing. Wouldn't omitting it result in the same behaviour?

**Comment by jrieken** [comment]
I think I started with `break` and needed that, but then I also like it being explicit

**Comment by tolot27** [comment]
I do get the same error message. If I don't use `http.proxyAuthorization` and provide the username and password in `http.proxy`, I get the following error:
```
[4764:0329/135059:WARNING:http_network_transaction.cc(311)] Blocked proxy response with status 407 to CONNECT request for marketplace.visualstudio.com:443.
[4764:0329/135059:INFO:CONSOLE(103)] "Ein unbekannter Fehler ist aufgetreten. Weitere Details dazu finden Sie im Protokoll.", source: file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js (103)
```
Where do I find this protocol?

**Comment by henriquedesousa** [comment]
So what's the solution then?!

**Comment by hfishere** [comment]
This bug still on concern?

**Comment by joaomoreno** [comment]
Proxy authentication comes with #22369.

Documentation with #27838.
