### ISSUE TITLE
position the cursor at the end of the accessible buffer by default

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#175011]
run a command in the terminal, run `Terminal: Focus accessible buffer`, 🐛  cursor is at the top of the buffer

mentioned by @jooyoungseo

we'd want it to initially be at the bottom

**Comment by jvesouza** [comment]
It would be great if there was the possibility of not changing the position of the cursor during the buffer update, preserving the position of the last access.
I believe that this would help in identifying the beginning of the response of the last executed command.

**Comment by meganrogge** [comment]
Yes, the plan is to only set the initial position to be the bottom of the buffer if possible. Subsequently, we won't alter it

**Comment by meganrogge** [comment]
For terminals with shell integration, we will set the cursor position to be on the last line, first column whenever a command finishes. So it will be on the last line of output.

For terminals without shell integration, we will set the cursor position only initially and it will be on the line where the cursor is in the normal buffer.

**Comment by meganrogge** [comment]
What's tricky is we also want to position the cursor when the text content changes.

**Comment by meganrogge** [comment]
verify that:

- when you add content by running a command with or without shell integration enabled, the cursor is positioned at the bottom of the last command's output
- when you change the cursor position but do not change / add output, the cursor position is retained when you toggle in and out of the buffer

**Comment by meganrogge** [comment]
@jooyoungseo, @jvesouza I'm about to merge a PR which fixes these issues. Can you pls test and confirm this is the behavior you'd want/ expect? I debated about landing the cursor on the prompt line (one line below), but don't think that would be useful.

**Comment by jvesouza** [comment]
@meganrogge I tested and confirmed that now the cursor always goes to the end of the accessibility buffer, regardless of the previous position. At the beginning of the tests I had the impression that the position of the cursor was affected by the size of the response of the executed command, but I could not confirm this.

**Comment by meganrogge** [comment]
@jvesouza what I experience on mac:

focus the accessible buffer, the cursor is on the last line, move the cursor up, exit the accessible buffer, focus the accessible buffer, the cursor is above the last line where I had it

focus the accessible buffer, the cursor is on the last line, exit the accessible buffer, run a command, focus the accessible buffer, the cursor is on the last line

**Comment by jvesouza** [comment]
@meganrogge   It seems the behavior is the same in my linux environment. Every time I execute a command and access the accessible buffer, the cursor is always on the last line of the executed command response, even if before executing the command I move the cursor to another position.

**Comment by meganrogge** [comment]
This is working for me on Windows, macOS, and linux via WSL. I'm not sure why it's not working for you @jvesouza . Would it be possible to record a gif?
