### ISSUE TITLE
How to configure the colors in command palette?

### ISSUE THREAD

**Issue by strrchr** [Microsoft/vscode#17509]
- VSCode Version: Code 1.8.0 (38746938a4ab94f2f57d9e1309c51fd6fb37553d, 2016-12-13T17:45:32.595Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions:

|Extension|Author|Version|
|---|---|---|
|xml|DotJoshJohnson|1.6.0|
|auto-close-tag|formulahendry|0.3.6|
|auto-rename-tag|formulahendry|0.0.8|
|green-theme|vscode|0.1.0|
|beautify|HookyQR|0.6.2|
|theme-material-theme|jprestidge|1.0.1|
|cpptools|ms-vscode|0.9.3|
|vscode-icons|robertohuertasm|4.2.0|

---

Steps to Reproduce:

1. Ctrl+Alt+P
2. Press something, for example: rel
3. The gray text and navy highlight is hard to distinguish in dark theme.
4. I cannot find the setting entry in settings.json and tmTheme.

**Comment by kieferrm** [comment]
@strrchr are you asking how to change individual colors in vscode?

**Comment by strrchr** [comment]
Can I configure the foreground and background colors in command palette's auto completetion box?
![default](https://cloud.githubusercontent.com/assets/8603093/21301733/1b6153d2-c5eb-11e6-8f32-fbf900078325.png)

**Comment by bpasero** [comment]
#3112
