### ISSUE TITLE
Remote walkthrough polish entrypoint steps

### ISSUE THREAD

**Issue by lramos15** [microsoft/vscode#175029]
Testing #175022

We mention the remote picker and the remote explorer. I wonder if we can condense this into one step or one way to enter. This walkthrough has quite a few steps which may make completion unlikely. I feel the remote picker is more in line with accessing remote repos. Or maybe we teach remote explorer / remote indicator as the one stop shop for all things remote. I get a feeling that some of these steps might be viewed as redundant.

**Comment by bhavyaus** [comment]
I believe we explicitly call out the Remote Indicator to help with discoverability.
@joyceerhl @bamurtaugh We could rework the first step call out `remote repositories` capabilities and also call out the remote indicator  as one way to get to those capabilities? The artwork could be the remote indicator.

**Comment by bamurtaugh** [comment]
> We could rework the first step call out remote repositories capabilities and also call out the remote indicator as one way to get to those capabilities? The artwork could be the remote indicator.

That sounds fine to me 👍
