### ISSUE TITLE
Terminal accessible buffer shows resolved aliases

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#175043]
Testing #174625

<img width="236" alt="image" src="https://user-images.githubusercontent.com/323878/220484963-2e0ed2c2-2f3a-4609-999f-3c9a61d7134b.png">

This is what I ran 

<img width="230" alt="image" src="https://user-images.githubusercontent.com/323878/220484987-c9239a9c-cf31-4815-8954-27b779f05ce1.png">

<img width="533" alt="image" src="https://user-images.githubusercontent.com/323878/220485011-d38fff82-76bd-4b00-9c12-1c5ddd57548e.png">

**Comment by meganrogge** [comment]
blocked by #166501

**Comment by Tyriar** [comment]
We're moving to showing the full raw buffer in a monaco instance which will fix this.
