### ISSUE TITLE
Symbol search doesn't work

### ISSUE THREAD

**Issue by Mosho1** [Microsoft/vscode#17500]
- VSCode Version: 1.8
- OS Version: windows 10

Steps to Reproduce:

1.  Hit ctrl+t
2.  Enter anything

There is a loading indication and nothing happens after more than a minute.

**Comment by kieferrm** [comment]
@Mosho1 pls provide more details steps for how to reproduce the problem. Do you open a folder? What files did you open in the editor? Which editor had the focus when you invoked `ctrl+t`? Which extension have you installed? Thanks!

**Comment by Mosho1** [comment]
I closed all the open files and opened just one and it's working. If I encounter this again I'll reopen. Thanks for the quick response!
