### ISSUE TITLE
Quick diff source drop down does not show on the mac

### ISSUE THREAD

**Issue by bhavyaus** [microsoft/vscode#175083]
Testing #174853

I don't see a drop down widget to select source:

<img width="1050" alt="Screenshot 2023-02-21 at 10 56 50 PM" src="https://user-images.githubusercontent.com/25044782/220546257-84076782-aa4c-4fa3-983f-2365626fc721.png">

Also, after clicking on the gutter for local changes, the quick diff does not appear in line with the gutter position for local change. Also seen the screenshot above.

**Comment by alexr00** [comment]
Did you modify any files locally (not just in the PR)? You'll only get the drop down when there are multiple providers, so if you only have pull request changes and no git changes then you wont see it.

> Also, after clicking on the gutter for local changes, the quick diff does not appear in line with the gutter position for local change. Also seen the screenshot above.

@bhavyaus which line did you click on? It should appear on the line that you clicked on.

**Comment by bhavyaus** [comment]
I did modify the file locally. I cant seem to repro this any more. closing.
