### ISSUE TITLE
`notebook.output.wordWrap` only updates after a reload

### ISSUE THREAD

**Issue by TylerLeonhardt** [microsoft/vscode#175051]
Testing #174728

* run `print('asdf asfed asdf asdf asdf asdf asdf asdf asdf asdf asdf asdf asdf asdf asdf')`
* change setting
* go back to notebook and adjust window size

The setting change does not take affect.

**Comment by amunger** [comment]
dupe of https://github.com/microsoft/vscode/issues/174908
