### ISSUE TITLE
Error when enabling settings synchronization

### ISSUE THREAD

**Issue by ofay11** [microsoft/vscode#175019]
Error when enabling settings synchronization. 
`{"error":"invalid_grant","error_description":"AADSTS500202: User account '{EmailHidden}' from external identity provider 'live.com' is not supported for API version '2.0'. Microsoft account pass-thru users and guests are not supported by the tenant-independent endpoint.\r\nTrace ID: bb23aab0-471d-4f11-b915-b41e9ea12700\r\nCorrelation ID: d9b1364c-1650-4ef5-8d98-a6c5fe490c1c\r\nTimestamp: 2023-02-21 21:34:22Z","error_codes":[500202],"timestamp":"2023-02-21 21:34:22Z","trace_id":"bb23aab0-471d-4f11-b915-b41e9ea12700","correlation_id":"d9b1364c-1650-4ef5-8d98-a6c5fe490c1c"}`

Version: 1.75.1
Commit: 441438abd1ac652551dbe4d408dfcec8a499b8bf
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36
Embedder: github.dev

**Comment by Tyriar** [comment]
I think we just never supported that account type, should we close this @lszomoru?
