### ISSUE TITLE
Async tokenizations for large files stops working sporadically

### ISSUE THREAD

**Issue by digitarald** [microsoft/vscode#175060]
Testing #174869

STR: Opened a large compressed file, like Bootstrap's CSS

Scrolling first and syntax is highlighted. But syntax colors keep flashing as I scroll up down. Once scrolling all the way it stops working.

https://user-images.githubusercontent.com/8599/220496181-c864bf44-5bde-4590-a14d-8a195ae59ab6.mp4

**Comment by hediet** [comment]
Can you share the file you tested this on?

**Comment by digitarald** [comment]
Tried the website again and it seems fine now.
