### ISSUE TITLE
Copy line behavior

### ISSUE THREAD

**Issue by aewnrd** [microsoft/vscode#175036]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.75.1
- OS Version: Windows 11 Home, 22H2

Steps to Reproduce:

1. Copy line with `Ctrl+C`
2. Paste line with `Ctrl+V`

I do not understand the behavior of the copy/cut and paste line shortcuts.

I get that the final newline **might** be copied with my text (depends on how I copy). But I don't know why text is inserted the way it is when I use `Ctrl+C` and `Ctrl+V`. It seems like some characters are added in front of the text, or it is modified in some other way.

In general, I expect text w/o any newline or other whitespace characters in front to be pasted **after** the cursor, not on a separate line.

This is what I get

![what_i_get](https://user-images.githubusercontent.com/126025530/220475977-cae0b4d9-b0fb-412b-b475-3da2869feec2.gif)

This is what I **expect** to get

![what_i_expect_to_get](https://user-images.githubusercontent.com/126025530/220477223-4578a984-4967-436a-b67c-0d16ccaaafdb.gif)

**Comment by alexdima** [comment]
Ctrl+C without a selection places the entire copied line in the clipboard. When pasting such a special copied line, it is never inserted where the cursor is, it is always inserted as a complete line, above the cursor. This feature can be turned off using `"editor.emptySelectionClipboard": false` and its current behavior is implemented like this to match other code editors.

**Comment by aewnrd** [comment]
@alexdima Thank you!
