### ISSUE TITLE
VS Code doesn't remember find settings (actions.find)

### ISSUE THREAD

**Issue by azlan** [Microsoft/vscode#17505]
- VSCode Version:
1.8.0

- OS Version:
Windows 10

Steps to Reproduce:

1.  Press Ctrl+F, then Alt+C, Alt+W, Alt+R to toggle the options
2.  Restart VSCode
3. Ctrl+F to inspect the settings again

Sublime, Notepad++ will keep the settings by default, at least we can get the option to save the settings in vscode.

**Comment by azlan** [comment]
I'm bringing this issue because of https://github.com/Microsoft/vscode/issues/8869, Ctrl+D behavior is  linked to these settings.

**Comment by rebornix** [comment]
Let's track the setting persistence in #6158
