### ISSUE TITLE
Problems Opening Multiple Editors

### ISSUE THREAD

**Issue by claytoncarney** [Microsoft/vscode#17508]
- VSCode Version: Code 1.8.0 (38746938a4ab94f2f57d9e1309c51fd6fb37553d, 2016-12-13T17:45:32.595Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

|Extension|Author|Version|
|---|---|---|
|vscode-eslint|dbaeumer|1.2.2|
|python|donjayamanne|0.5.5|
|MagicPython|magicstack|1.0.0|
|csharp|ms-vscode|1.5.3|
|python|tht13|0.2.3|

---

I'm fairly certain this problem began after updating to 1.8.0. Before that I often had four or five editors open at the same time. After 1.8.0, single clicking files in the Explorer will only open one editor. Clicking another file simply replaces the last file opened. After double clicking a file (even the same that's open) a new editor will open. And after that, single clicking seems to work again (sometimes). Once all editors are closed, the pattern begins again.

This issue does not occur through the menu (File->Open FIle), only in the VS Code Explorer.

[Screencast](https://mega.nz/#!p9BFCYCJ!yp0Ex555DzHc9UmnMUfU4XSqOCmcjfLP24huhS8VO5M)

**Comment by kieferrm** [comment]
@claytoncarney What happens on single click in the explorer and what happens on `Ctrl+P` is controlled by the following two settings in your workspace or user settings:

>// Controls if opened editors show as preview. Preview editors are reused until they are kept (e.g. via double click or editing).
>
>"workbench.editor.enablePreview": true,
>
> // Controls if opened editors from Quick Open show as preview. Preview editors are reused until they are kept (e.g. via double click or editing).
>
>"workbench.editor.enablePreviewFromQuickOpen":true

**Comment by claytoncarney** [comment]
@kieferrm Thanks. Changing those settings restored previous behavior. Just did not see any mention of this change in the release notes. Up to this, I had never made any changes to settings.
