### ISSUE TITLE
clicking outside dropdown doesn't escape

### ISSUE THREAD

**Issue by eleanorjboyd** [microsoft/vscode#175031]
Testing #175022

When I was on the `get started with a remote repository` section of the walkthrough I clicked on "open remote repository" and it had the dropdown. I noticed that I couldn't just click outside the dropdown (back on the welcome page) to make the dropdown disappear and instead had to use the "esc" button. From my experience with other dropdowns if you click away from the dropdown it disappears and think that behavior would make sense here.

**Comment by bhavyaus** [comment]
@joyceerhl does the quick pick come from https://github.com/microsoft/vscode/blob/720985f2c68cadb5e375d9ec671476c548f61769/extensions/git-base/src/api/api1.ts#L28 ? If yes, who should I direct this issue to?

**Comment by joyceerhl** [comment]
Yes that's where the quickpick comes from. @lszomoru owns the desktop git extension.

**Comment by bhavyaus** [comment]
@lszomoru could you please help with this? Thanks.

**Comment by rzhao271** [comment]
![Bug still happens on latest Insiders with the original steps](https://user-images.githubusercontent.com/7199958/234668843-2046826a-fd1c-4d67-8372-2e9a02c46fd6.gif)

**Comment by lszomoru** [comment]
It turns out that the "Remote Repositories" extension does not leverage the picker from the git-base extension so the fix that I made is not relevant. To verify this, please download the latest pre-release version of the "Remote Repositories" extension.
