### ISSUE TITLE
'Explorer: Exclude Git Ignore' ignores negates in .gitignore

### ISSUE THREAD

**Issue by plause** [microsoft/vscode#175066]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.75.1
- OS Version: Ubuntu 22.04

Steps to Reproduce:

1. Enable 'Explorer: Exclude Git Ignore' option in settings;
1. Create files:

    touch a.txt
    touch b.txt

1. Create .gitignore with negates inside:

    \*
    !a.txt

1. Check if `a.txt` shows up in Explorer;

**Comment by lramos15** [comment]
\duplicate https://github.com/microsoft/vscode/issues/134415
