### ISSUE TITLE
Unable to click links in the tooltip of quickpick items

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode#175004]
Testing #174699

The tooltip vanishes when moving the mouse across the quick pick to the tooltip,
I believe this is because of the presence of the scroll bar
see image below

![Screenshot 2023-02-22 at 06 44 00](https://user-images.githubusercontent.com/1948812/220443355-5612503e-dee7-40c7-813a-aebf4f5283b8.png)

**Comment by TylerLeonhardt** [comment]
The common practice with vscode tooltips is that you need to hold Alt to be able to mouse over to them.

Cc @Tyriar

**Comment by Tyriar** [comment]
This is by design currently, the extensions view does the same.
