### ISSUE TITLE
Closing and opening explorer viewlet via sash will change the active editor if it's keybindings.json

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#17501]
- VSCode Version: Code 1.8.0 (38746938a4ab94f2f57d9e1309c51fd6fb37553d, 2016-12-13T17:45:32.595Z)
- OS Version: Windows_NT ia32 10.0.14931
- Extensions:

|Extension|Author|Version|
|---|---|---|
|vscode-theme-onedark|akamud|0.2.5|
|vscode-theme-fruity|Tyriar|0.1.0|
|csharp|ms-vscode|1.1.5|

---

Steps to Reproduce:

1. Open a file
2. Open keybindings.json

    ![image](https://cloud.githubusercontent.com/assets/2193314/21298525/2a77f4ba-c547-11e6-96ae-bb76d89c80f8.png)

3. Pull viewlet sash so it closes

    ![image](https://cloud.githubusercontent.com/assets/2193314/21298539/49d8a5fc-c547-11e6-89c6-e5b87cb24350.png)

4. Pull viewlet sash back, weirdness ensues:

    ![image](https://cloud.githubusercontent.com/assets/2193314/21298545/59054cec-c547-11e6-88f0-f2fa1caeb974.png)

It appears to open the last focused file. If the file is still open it will focus it (and keep keybindings.json around), if not it will replace the keybindings.json editor with a preview of the last focused file.

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/16616
