### ISSUE TITLE
Unable to download extensions

### ISSUE THREAD

**Issue by lramos15** [microsoft/vscode#175023]
Cannot download any extensions from the marketplace. Manual downloading works
<img width="946" alt="image" src="https://user-images.githubusercontent.com/4544166/220467159-af10b2e0-667a-4e75-af11-096e1757dd1a.png">

**Comment by sandy081** [comment]
What does share process log say?

**Comment by lramos15** [comment]
> What does share process log say?

```
2023-02-22 07:44:13.404 [error] Failed to install extension. beardedbear.beardedtheme
2023-02-22 07:44:13.404 [error] Error: net::ERR_FAILED
    at SimpleURLLoaderWrapper.<anonymous> (node:electron/js2c/browser_init:105:7047)
    at SimpleURLLoaderWrapper.emit (node:events:526:28)
```

**Comment by lramos15** [comment]
Hmm, I just updated my VS Code client and am not seeing this anymore. I guess maybe I received a bad update or something.

**Comment by sandy081** [comment]
Hmm network issue. Can you please open shared process window - using `Toggle Shared Process` command and see what the network tab and console tab says?

@deepak1556 @bpasero Given that we are making shared process a utility process, we have to build tooling infrastructure for network diagnosing. Current requests logging in the logs are not good enough. We used to get more information for network requests in the shared process console/network tab. It would be great if we can create a separate log file where we log all network requests with necessary info.

**Comment by bpasero** [comment]
That makes good sense to me, maybe central from the request service and only when tracing is enabled.

**Comment by bpasero** [comment]
Btw for this issue: we recently configured `developer.sharedProcess.redirectRequestsToMain` to be enabled by default, so it may have an impact here.

**Comment by bpasero** [comment]
Oh nevermind, for insiders it was always enabled!
