### ISSUE TITLE
File watcher doesn't always respawn after being killed

### ISSUE THREAD

**Issue by lramos15** [microsoft/vscode#175003]
Testing #174785

1. Open process explorer
2. Kill file watcher
3. It restarts
4. Forecefully kill it again
5. 🐛 It stays dead

**Comment by bpasero** [comment]
I was only able to reproduce once but not anymore. I suspect maybe its possible to get into this state when you kill the process too quickly.

Can you reproduce reliably?

**Comment by lramos15** [comment]
Yes I can pretty reliably reproduce this. Today I killed it just once and it didn't even respawn.

**Comment by bpasero** [comment]
How exactly do you kill it?

**Comment by bpasero** [comment]
I have no real clue why this happens, seems to not reproduce running out of sources. And even in insiders, only reproduces sometimes. 

We do track utility process crashes here:

https://github.com/microsoft/vscode/blob/cd6a0795cfdaf93067861622c86a5cd215c1ad1e/src/vs/platform/utilityProcess/electron-main/utilityProcess.ts#L317-L318

And fire an event that will eventually reach here:

https://github.com/microsoft/vscode/blob/cd6a0795cfdaf93067861622c86a5cd215c1ad1e/src/vs/platform/utilityProcess/electron-main/utilityProcessWorkerMainService.ts#L111

And then bubbles up to here:

https://github.com/microsoft/vscode/blob/cd6a0795cfdaf93067861622c86a5cd215c1ad1e/src/vs/platform/utilityProcess/electron-main/utilityProcessWorkerMainService.ts#L61-L64

To complete a promise from the `createWorker` call, which then should end up here:

https://github.com/microsoft/vscode/blob/cd6a0795cfdaf93067861622c86a5cd215c1ad1e/src/vs/workbench/services/files/electron-sandbox/watcherClient.ts#L44-L52

Which will cause the watcher to restart from here:

https://github.com/microsoft/vscode/blob/cd6a0795cfdaf93067861622c86a5cd215c1ad1e/src/vs/platform/files/common/watcher.ts#L184-L187

Maybe I can add more logging around this to see where it falls apart.

**Comment by lramos15** [comment]
Yeah it's probably not a huge deal because 95% of the time the first kill causes a restart, so I believe this would only affect users who's watcher is very prone to crashing often.

**Comment by bpasero** [comment]
Yup, and in the cases where it matters, it is not going to be a `SIGTERM` or `SIGKILL` as the process explorer triggers...

**Comment by bpasero** [comment]
Additional logging shows that the utility process seems to receive an `exit` code of `0` and thus we refuse to restart because we think it is a normal exit:

```
[info] [UtilityProcess id: 1, type: fileWatcher, pid: 47737]: received exit event with code 0
```

I would leave it as a quirk of how process explorer kills for now and close.
