### ISSUE TITLE
Quick diff does not show local file changes for new files introduced in a PR

### ISSUE THREAD

**Issue by bhavyaus** [microsoft/vscode#175082]
Testing #174853

I was able to see the local diff over the pull request diff for existing files. If the PR added a new file, then the gutter does not show the local diff.

<img width="826" alt="Quickdiff" src="https://user-images.githubusercontent.com/25044782/220545593-f6c3172f-339e-4bc6-bdfd-ca6ebe58f002.png">

**Comment by alexr00** [comment]
@bhavyaus can you share you steps? I'm not able to reproduce with the following:
1. Make a PR that adds a file
2. Open the file. 
3. ✅ there is no quick diff 
4. Add a line to the file.
5. ✅ quick diff shows. Clicking on it I can see that it's for "Git local working changes"

**Comment by bhavyaus** [comment]
https://user-images.githubusercontent.com/25044782/220720793-7ebf0b16-fef8-4de9-906c-210ddd4195b5.mov

**Comment by alexr00** [comment]
We can only show one quick diff gutter decoration at a time, so it is by design that the git added line is no longer visible in the gutter. 

With https://github.com/microsoft/vscode/issues/174950, the quick diff peek should show the git change first and not scroll to the bottom.
