### ISSUE TITLE
Provides a command to change the cursor position while maintaining cursor selection

### ISSUE THREAD

**Issue by phommy** [microsoft/vscode#175080]
Type: <b>Feature Request</b>

I can create an extension to do this:
```
    vscode.commands.registerCommand('ph.invertSelection', function () {
        const selection = vscode.window.activeTextEditor.selection;
        vscode.window.activeTextEditor.selection = new vscode.Selection(selection.active, selection.anchor);
    });
```
But it seems too "heavy" for a single simple command. (or is there something like tampermonkey for browsers? )
<img width="398" alt="11" src="https://user-images.githubusercontent.com/24478780/220540886-182fc7ec-cf09-423f-bd44-c3ebce0faa45.png">

VS Code version: Code 1.75.1 (441438abd1ac652551dbe4d408dfcec8a499b8bf, 2023-02-08T21:32:34.589Z)
OS version: Windows_NT x64 10.0.19042
Modes:
Sandboxed: No

**Comment by alexdima** [comment]
I personally think that is fine. You can totally have an extension which does a single command. If it's useful, others will use it. I also publish a couple extensions that are doing very small, specific things.
