### ISSUE TITLE
Remote walkthrough explorer pic is incorrect

### ISSUE THREAD

**Issue by lramos15** [microsoft/vscode#175024]
Testing #175022

Shows the file explorer and not the remote explorer

**Comment by bhavyaus** [comment]
I can't seem to repro this. Both insiders.vscode.dev and desktop open the remote explorer view for me.

**Comment by lramos15** [comment]
I was merely pointing out that the artwork is for the file explorer and not the remote explorer.

**Comment by bhavyaus** [comment]
My bad! Removed this step in the recent polishing of the walkthrough content.
