### ISSUE TITLE
Render markdown titles like XCode

### ISSUE THREAD

**Issue by dlschmidt** [microsoft/vscode#175035]
![image](https://user-images.githubusercontent.com/20640295/220478237-9f1b2ebc-435a-4eae-8bda-d1d2ae058282.png)
I think XCode does a pretty good job on rendering titles in markdown pages and I think this feature could probably be a good extension to the markdown renderer. 

Making the headers more higher improves readability of markdown pages drastically in my opinion. This could eliminate the need for a second panel which consumes some display space and forces you to look constantly at two points the same time.

**Comment by mjbvz** [comment]
Falls under #36512
