### ISSUE TITLE
Tensorflow (.tflite) File Icon

### ISSUE THREAD

**Issue by charlieforward9** [microsoft/vscode#175073]
I figure this is a very minor change after reading [this](https://code.visualstudio.com/api/extension-guides/file-icon-theme), but I am short on time to learn how to create an extension right now. 

Just looking for a .tflite file icon implementation, nothing fancy.

<img width="153" alt="Screen Shot 2023-02-22 at 12 46 04 AM" src="https://user-images.githubusercontent.com/62311337/220533846-075591bc-f5f0-4393-aafb-9bb08bd534a6.png">
<img width="153" alt="Tensorflow Icon" src="https://user-images.githubusercontent.com/62311337/220533889-0a6b45d7-5951-4e50-9d33-537744f5e7da.png">

**Comment by aeschli** [comment]
I suggest to file an issue against the https://github.com/jesseweed/seti-ui to add such an icon.
