### ISSUE TITLE
can't stop at the breakpoint

### ISSUE THREAD

**Issue by andychen2016** [Microsoft/vscode#17518]
- VSCode Version: Code 1.7.2 (7ba55c5860b152d999dda59393ca3ebeb1b5c85f, 2016-11-21T22:14:18.217Z)
- OS Version: Linux x64 4.4.0-53-generic
- Extensions:

|Extension|Author|Version|
|---|---|---|
|makeRunner|alexnesnes|0.1.1|
|code-gnu-global|austin|0.2.1|
|vscode-instant-markdown|dbankier|0.2.1|
|python|donjayamanne|0.5.5|
|CppSnippets|hars|0.0.5|
|MagicPython|magicstack|0.6.1|
|vscode-clang|mitaki28|0.2.1|
|cpptools|ms-vscode|0.9.3|
|Spell|seanmcbreen|0.9.1|
|python|tht13|0.2.3|

---

Steps to Reproduce:

1.launch.json set as below:
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "C++ Launch",
            "type": "cppdbg",
            "request": "launch",
            "program": "${workspaceRoot}/build/tools/caffe.bin",
            "args": ["train","--solver=examples/mnist/lenet_solver.prototxt"],
            "stopAtEntry": false,
            "cwd": "${workspaceRoot}",
            "environment": [],
            "externalConsole": true,
            "preLaunchTask": "build",
            "linux": {
                "MIMode": "gdb",
                "setupCommands": [
                    {
                        "description": "Enable pretty-printing for gdb",
                        "text": "-enable-pretty-printing",
                        "ignoreFailures": true
                    }
                ]
            },
            "osx": {
                "MIMode": "lldb"
            },
            "windows": {
                "MIMode": "gdb",
                "setupCommands": [
                    {
                        "description": "Enable pretty-printing for gdb",
                        "text": "-enable-pretty-printing",
                        "ignoreFailures": true
                    }
                ]
            }
        },
2.make caffe project there is no error;
3.Add break point in  main function, press "F5" run caffe.bin, but VS code not stop at the breakpoint!

**Comment by egamma** [comment]
This issue was moved to Microsoft/vscode-cpptools#416
