### ISSUE TITLE
Add a command that accepts a notification's default action 

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#175140]
> @meganrogge -- Very recently, I encountered accessibility issue with merge editor when trying to sync my VSCode setting conflicts between local and remote ones. It would be so nice if this editor could provide similar experience to the diff editor audio cues, etc.

It would be even nicer if some frequently used buttons, such as Accept, had their default accelerator shortcut key (e.g., Alt+A) so that users can quickly activate the buttons without having to leave their current editor focus.

_Originally posted by @jooyoungseo in https://github.com/microsoft/vscode/issues/159029#issuecomment-1437504899_

**Comment by Tyriar** [comment]
To clarify, this is accelerators for notification actions, not a command? Are accelerators in the menu bar (anywhere else?) accessible currently? I'm curious how Windows natively does this if at all.

**Comment by meganrogge** [comment]
From @bpasero , 

> We could add a command that simply triggers the primary button.

**Comment by meganrogge** [comment]
Have we ever considered having a tag or something for commands so they could be filtered?
