### ISSUE TITLE
Built-in issue reporter not working

### ISSUE THREAD

**Issue by lumaxis** [microsoft/vscode#175108]
Does this issue occur when all extensions are disabled?: Yes

Version: 1.75.1 (Universal)
Commit: 441438abd1ac652551dbe4d408dfcec8a499b8bf
Date: 2023-02-08T21:34:59.000Z
Electron: 19.1.9
Chromium: 102.0.5005.194
Node.js: 16.14.2
V8: 10.2.154.23-electron.0
OS: Darwin arm64 22.3.0
Sandboxed: Yes

Ironically, when reporting https://github.com/microsoft/vscode/issues/175107, I was trying to issue the built-in "Report issue" functionality but it did not work.

Steps to Reproduce:

1. Help > Report Issue
2. Fill out the form
3. Click "Create on GitHub" button
4. Nothing happens

<img width="700" alt="image" src="https://user-images.githubusercontent.com/406937/220622783-f3c09d5c-9e22-46ce-8ff7-65d3e773b110.png">

**Comment by TylerLeonhardt** [comment]
I'm not able to repro (created [this](https://github.com/microsoft/vscode/issues/175392))

While you have the issue reporter open, can you open the dev tools (cmd+alt+i) and tell me if there's anything interesting in there.

**Comment by lumaxis** [comment]
I had checked the dev tools when this happened and hadn't noticed anything interesting.
Seems like this is indeed working now though, not sure what was up. Still, thanks for taking the time to look into it!
