### ISSUE TITLE
restart app 

### ISSUE THREAD

**Issue by aditya23573** [microsoft/vscode#175153]
Type: <b>Performance Issue</b>

so plz restsrt the app my mistake in wrong system in a intal so yo 
can restart the app

VS Code version: Code 1.75.1 (441438abd1ac652551dbe4d408dfcec8a499b8bf, 2023-02-08T21:32:34.589Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 5500U with Radeon Graphics          (12 x 2096)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|7.33GB (2.78GB free)|
|Process Argv|--crash-reporter-id ebeb9755-b3b8-4f39-a1a5-38bd5c07b374|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	   122	  2236	code main
    1	   135	  6688	   gpu-process
    0	    40	  8748	   utility-network-service
    0	   108	 14800	   shared-process
    0	    80	  3980	     ptyHost
    0	    64	  2676	       C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe -noexit -command "try { . \"c:\Users\Aditya\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\contrib\terminal\browser\media\shellIntegration.ps1\" } catch {}"
    0	     6	 14848	       console-window-host (Windows internal process)
    0	    80	 17456	     fileWatcher
    0	    27	 15812	   crashpad-handler
    0	    90	 17132	   issue-reporter
    0	     6	 17644	   "C:\Program Files\Google\Drive File Stream\70.0.2.0\crashpad_handler.exe" --database=C:\Users\Aditya\AppData\Local\Google\DriveFS\Crashpad --url=https://clients2.google.com/cr/report --annotation=application=Code.exe --annotation=prod=DriveFS --annotation=ver=70.0.2.0 --initial-client-data=0x1490,0x1494,0x1498,0x148c,0x14a0,0x7ff812b55db0,0x7ff812b55dc0,0x7ff812b55dd0
    0	   228	 18208	   window (Untitled-2.txt - Untitled (Workspace) - aditya - Visual Studio Code)
    0	   192	 18440	   extension-host
    0	    42	 10452	     C:\Users\Aditya\AppData\Local\Programs\Python\Python311\python.exe completion.py
    0	    10	  2844	       console-window-host (Windows internal process)
    0	    14	 17960	     c:\Users\Aditya\.vscode\extensions\ms-vscode.cpptools-1.14.3-win32-x64\bin\cpptools.exe
    0	    10	  9560	       console-window-host (Windows internal process)
    0	    42	 18824	     C:\Users\Aditya\AppData\Local\Programs\Python\Python311\python.exe completion.py
    0	    10	  8588	       console-window-host (Windows internal process)
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (Untitled-2.txt - Untitled (Workspace) - aditya - Visual Studio Code)
|    Folder (Documents): 2236 files
|      File types: json(526) png(518) jpg(50) ini(49) m3u(49) xml(41)
|                  essentialsound(41) vdjsample(27) m4a(20) ttf(19)
|      Conf files:
|    Folder (Desktop): 8 files
|      File types: pdf(3) json(1) ini(1) txt(1) lnk(1)
|      Conf files: launch.json(1)
|      Launch Configs: python(6);
```

</details>
<details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
pythoncpp-debug|ben|0.3.0
geecode-python|gee|2019.5.10
python-resource-monitor|kai|0.2.0
isort|ms-|2022.8.0
python|ms-|2023.3.10531009
vscode-pylance|ms-|2023.2.30
jupyter|ms-|2023.1.2010391206
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.14
vscode-jupyter-cell-tags|ms-|0.1.6
vscode-jupyter-slideshow|ms-|0.1.5
cpptools|ms-|1.14.3
python-extended-snippets|tus|0.0.1
livecode|xir|1.3.10

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscoreces:30445986
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vscaat:30438848
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
azure-dev_surveyone:30548225
pyindex848:30662994
nodejswelcome1:30587005
2e4cg342:30602488
pyind779:30662992
89544117:30613380
pythonsymbol12:30657548
a9j8j154:30646983
pythonb192:30669360

```

</details>

**Comment by aditya23573** [comment]
so fast restrat the app

**Comment by KenSharp** [comment]
What?
