### ISSUE TITLE
Disable automatic scrolling in Explorer pane when switching editor windows

### ISSUE THREAD

**Issue by jessicah** [Microsoft/vscode#17512]
- VSCode Version: 1.8
- OS Version: Windows 10

Steps to Reproduce:

1. Scroll the Explorer view a little or a lot
2. Focus on another open editor window
3. Explorer scrolls so that currently selected file is in view and centered vertically (if possible)

This is very annoying. I scroll to a different part of my source tree for a reason, switching between windows should have no effect on the Explorer view. Makes it entirely pointless. I need to work in differing parts of my source tree at once. I shouldn't have my actions overridden like this.

**Comment by kieferrm** [comment]
@jessicah you can change `explorer.autoReveal` to `false` in your user or workspace settings.
