### ISSUE TITLE
Resize "Open Editors" pane in Explorer

### ISSUE THREAD

**Issue by jessicah** [Microsoft/vscode#17511]
- VSCode Version: 1.8
- OS Version: Windows 10

Steps to Reproduce:

1. Open a large number of documents
2. Need to scroll to see all documents in Open Editors pane

I work on a very large repository, 20,000 files, 2000 directories, so I like to open all the documents I want to jump between; then minimise the directory tree view, and use the Open Editors pane to jump between documents.

I find using the Open Editors pane easier to navigate than scrolling through tabs, etc. However, this pane appears to be fixed in size, limiting the use of the vertical real estate that's available.

**Comment by kieferrm** [comment]
@jessicah you can control the behavior and appearance of the Open Editors section with the following two settings: `explorer.openEditors.visible` and `explorer.openEditors.dynamicHeight` in your user or workspace settings.

**Comment by jessicah** [comment]
I set `explorer.openEditors.dynamicHeight` to true, but this hasn't had any effect. I even restarted vscode to ensure it didn't need reloading.

**Comment by jessicah** [comment]
Oh, I see visible is a number... that's a confusingly named setting.

**Comment by jekson** [comment]
I had the same problem.
"explorer.openEditors.visible": 30,
"explorer.openEditors.dynamicHeight": true
But open editors pane not changing height. Only scroll appears.
OS version: windows 7, VS version:1.10.2

**Comment by summivox** [comment]
It makes no sense to me that all other accordion groups can be resized, but only Open Editors cannot.
