### ISSUE TITLE
Prevent users from filing TS Server crash issues without first disabling global TS Server plugins

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#175184]
In my effort to catch TS Server bugs, I've made it easy to file issues when a TS Server crash occurs. This was great initially but over the years we are seeing more and more low quality/low effort TS Server crash issues coming in. Despite my best efforts (and lots of ❗ in the issue template!)  very few reporters actually fill in issue template, check for duplicate issues, or follow up after I ask a question on their issue. In short we no longer get a lot of value from these reports for the issue triaging cost

In addition, the majority of these TS Server crash issues are now caused by TS Server plugins. These issues should be filed against these plugins/extensions instead. Again I've tried to make this clear to users with warnings both in the product and in the issue template, but we still got 50 low effort issue reports like this last week, all of which were root caused by a plugin and not VS Code itself

Given all this, I'm going to prevent users from filing issues if they have a global TS Server plugin enabled. We will still provide help text for these crashes, and if they disable extensions and a crash still occurs we will still them them easily file the issue

**Comment by joaomoreno** [comment]
Unsure how to verify this. All I get is this notification when I manually exit the TS process using Process Hacker:

![image](https://user-images.githubusercontent.com/22350/220961746-1a24d412-1372-4f3f-a697-3eb7a53ebd71.png)

I tried doing that 5+ times in a row, I still only get that notification.

**Comment by joaomoreno** [comment]
Repro steps?

**Comment by mjbvz** [comment]
Thanks for testing. Try installing an extension that includes a plug-in and then causing a crash using the same steps. For example: https://marketplace.visualstudio.com/items?itemName=svelte.svelte-vscode

**Comment by joaomoreno** [comment]
![image](https://user-images.githubusercontent.com/22350/221128690-3321e0b7-be43-48fe-ac47-879bb98db594.png)
