### ISSUE TITLE
cmd+[IntlBackslash] key shortcut becomes cmd+NumPad_Subtract on MacOS

### ISSUE THREAD

**Issue by Chyzhykal** [microsoft/vscode#175126]
- VS Code Version: 1.75.0
- OS Version: 12.2 Monterey
- Keyboard language : Swiss french

I have line comment shortcut for cmd+[IntlBackslash]. When i save it, it becomes cmd+NumPad_Subtract for some unknown reason. In keybindings.json it's marked as IntlBackslash, but works only with subtract numpad. Error appeared after todays (22.02.2023) update

**Comment by gjsjohnmurray** [comment]
Please update to 1.75.1 and re-test.
