### ISSUE TITLE
[Bug] Can't disable code suggestions

### ISSUE THREAD

**Issue by wenfangdu** [microsoft/vscode#175113]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.75.1
- OS Version: macOS 13

Steps to Reproduce:

1. Add the following settings to `settings.json`:
   ```json
   {
     "javascript.suggestionActions.enabled": false,
     "typescript.suggestionActions.enabled": false
   }
   ```
2. Code suggestions still show up:
<img width="766" alt="image" src="https://user-images.githubusercontent.com/28700378/220628577-23aa35ff-9753-4390-94bb-da3b37aba9f0.png">

**Comment by jrieken** [comment]
what you are looking at is the hover. to disable that use this setting `editor.hover.enabled`

**Comment by jrieken** [comment]
Oh, you mean "hint" diagnostics. Forwarding to @mjbvz for comment

**Comment by wenfangdu** [comment]
@jrieken Thanks for fowarding, I got the term from the [docs](https://code.visualstudio.com/docs/languages/javascript#_code-suggestions):

![image](https://user-images.githubusercontent.com/28700378/220814470-a01d202c-9742-404d-b5d6-184cafd72966.png)
