### ISSUE TITLE
Notebook rendered in wrong spot with centered editor layout

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#175179]
Type: <b>Bug</b>

1. With sidebar open
1. Enable centered editor layout
1. Open notebook

**Bug**
The notebook is rendered over the sidebar

VS Code version: Code - Insiders 1.76.0-insider (Universal) (7b6b6869e8f5b71b5e9cdbd3f590b10964f89607, 2023-02-22T05:24:36.668Z)
OS version: Darwin x64 22.3.0
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|2, 2, 2|
|Memory (System)|32.00GB (0.01GB free)|
|Process Argv|--crash-reporter-id 48781ca2-1705-4f64-9bab-325055aab55d|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by karrtikr** [comment]
![image](https://user-images.githubusercontent.com/13199757/221005571-d4a601cd-c5cb-46db-a526-1d0dfc8c483e.png)
