### ISSUE TITLE
Groovy fast jump

### ISSUE THREAD

**Issue by BelalH** [Microsoft/vscode#17516]
- VSCode Version:
- OS Version:
- groovy language
Steps to Reproduce:

1. write function or variable 
2. call the function or variable later in code 
3. press command and the press on the function call 
4. the cursor doesn't jump to that function

**Comment by egamma** [comment]
This is the expected behaviour. Currently there is only coloring support for Groovy provided by VS Code.

**Comment by adrianescat** [comment]
It would be great coloring support for Groovy/Grails  `.gsp` files too. Comments show as code for example.

**Comment by mjbvz** [comment]
Closing as extension-canidate. We don't provide built-in intellisense for Groovy. Please see [this guide](https://code.visualstudio.com/docs/extensions/overview) for information about writing a language extension
