### ISSUE TITLE
unbound breakpoints

### ISSUE THREAD

**Issue by eleanorjboyd** [microsoft/vscode#175171]
Testing #174870

tried to hit breakpoints in the Monaco editor repo and was getting unbound breakpoints. The steps I did to run were `npm install` then I tried both with and without `npm run release` as suggested [here](https://github.com/microsoft/monaco-editor/blob/main/CONTRIBUTING.md). Then finally I ran the Monaco editor playground. Apologies if the issue is just my setup or if I forgot to install something before building.

Thanks
<img width="1299" alt="Screenshot 2023-02-22 at 12 46 06 PM" src="https://user-images.githubusercontent.com/26030610/220755399-072a0cc5-7d4f-4fd8-82b6-ebb3056b3902.png">

**Comment by hediet** [comment]
I'm just noticing now, the monaco editor playground enables you to debug the monaco editor, not the website.
You set a breakpoint in the website!
