### ISSUE TITLE
Snippets show in inline suggestions even though they are turned off

### ISSUE THREAD

**Issue by TheColorRed** [microsoft/vscode#175190]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: Windows 11
- OS Version: 1.75.1

Steps to Reproduce:

Using the following settings:
![image](https://user-images.githubusercontent.com/1571806/220792553-02456d7a-4e96-4d05-9578-b5c062db1d78.png)
![image](https://user-images.githubusercontent.com/1571806/220792593-26697018-7fda-4821-b75a-fc4c8aae149e.png)

1. open a typescript file
2. type `fo` within a method/function
3. the following gets output (might have to navigate through some of the suggestions) even though snippets are off:

![image](https://user-images.githubusercontent.com/1571806/220793522-9dff1bdd-7a8b-42da-8572-ad216a8a2381.png)

**Comment by jrieken** [comment]
Thanks for the patience. I cannot reproduce, please share you more settings that might influence this. Also share data in a copy-paste friendly way (text over images)

**Comment by TheColorRed** [comment]
@jrieken Here are the minimum settings that I am using to reproduce (all extensions disabled):

```json
{
    "editor.inlineSuggest.enabled": true,
    "editor.snippetSuggestions": "none",
    "editor.quickSuggestions": {
        "other": "inline",
        "comments": "inline",
        "strings": "inline"
    },
    "editor.inlineSuggest.showToolbar": "always"
}
```

Once typing `fo` and going to the 3rd suggestion, I get this as a suggestion:

![image](https://github.com/microsoft/vscode/assets/1571806/22707be3-f1e6-4c8a-a19a-2c662e8c3949)

**Comment by amunger** [comment]
I can't figure out how to get that ghost text to show up for suggestions to verify this. I've never seen that ghost text for anything but copilot completions
Do I need a suggestion provider extension?

**Comment by jrieken** [comment]
You are right. I made a refactoring after this fix and that broke this feature 😨 Thanks for the diligence on this one!

**Comment by jrieken** [comment]
To verify, use the steps from https://github.com/microsoft/vscode/issues/175190#issuecomment-1845534585. Make sure no snippets completions are ghost-texted with `"editor.snippetSuggestions": "none"` and that they are when the setting is set accordingly

**Comment by meganrogge** [comment]
I still cannot get snippet completions to show up @jrieken

**Comment by jrieken** [comment]
@meganrogge You need to say what you are trying because I do see them working just fine

<img width="922" alt="Screenshot 2024-01-26 at 18 14 32" src="https://github.com/microsoft/vscode/assets/1794099/f666b8f9-889a-4c94-8de5-94416aaf4e08">

**Comment by amunger** [comment]
This works correctly for me now, no snippets with `"editor.snippetSuggestions": "none",`, and they do show up without it.

**Comment by jrieken** [comment]
Bang on. The whole point is that the `editor.snippetSuggestions ` is honored also for ghost suggestions

**Comment by meganrogge** [comment]
`editor.snippetSuggestions`:`inline`

<img width="1792" alt="Screenshot 2024-01-26 at 9 19 47 AM" src="https://github.com/microsoft/vscode/assets/29464607/5c2794d6-f2e1-476b-8316-7129b3df8c26">

**Comment by jrieken** [comment]
@meganrogge this is about ghost test, please see https://github.com/microsoft/vscode/issues/175190#issuecomment-1911676841 and the comment linked from there

**Comment by meganrogge** [comment]
🤦🏼‍♀️ there was a syntax error in my settings.json file, so the settings did not get applied. Now it works 👍🏼
