### ISSUE TITLE
lint 的es6省略号语法又报错了... (the automatically expand syntax of es6 in vscode report errors again)

### ISSUE THREAD

**Issue by kooboo-chenhai** [Microsoft/vscode#17519]
see in the pic:
![1](https://cloud.githubusercontent.com/assets/13828467/21305509/2561cfbc-c607-11e6-9b38-747d9239eddf.png)
- VSCode Version: Code 1.8.0 (38746938a4ab94f2f57d9e1309c51fd6fb37553d, 2016-12-13T17:45:32.595Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

|Extension|Author|Version|
|---|---|---|
|vscode-eslint|dbaeumer|1.2.2|
|vscode-babel-coloring|dzannotti|0.0.4|

---

@rebornix @kieferrm
Steps to Reproduce:

1. install vue.js

2. add a component ,has :"
computed: {
      ...mapGetters({
        faqs: SEARCHED_FAQS
}),"
3. it says the "..." is not expected!

**Comment by kooboo-chenhai** [comment]
而且,之前还有一种更奇怪的报错,
某些单词下面的某一两个字母会出现一条红色的波浪号,但是现在重现不了,因为似乎重启后就正常了,至少今天是的.
( too long ,lazy to translate...)

**Comment by egamma** [comment]
@rebornix can you help with the translation of https://github.com/Microsoft/vscode/issues/17519#issuecomment-267907723

**Comment by kooboo-chenhai** [comment]
@rebornix 
![2](https://cloud.githubusercontent.com/assets/13828467/21310239/7094e284-c61c-11e6-9e88-2e47f9a78baa.png)
@egamma : I means that sometimes it report errors like this picture,it says "property assignment expected", but the code run well in my program.

**Comment by kooboo-chenhai** [comment]
It appear again now ,  it was well until this vscode version

**Comment by waderyan** [comment]
@kooboo-chenhai thank you for opening this. Can you share your workspace so we can recreate this on our end?

**Comment by guilhermewaess** [comment]
Same here! very simple to reproduce, just use a .vue component with es6 syntax like this:

`import { mapGetters } from 'vuex';`

![image](https://cloud.githubusercontent.com/assets/5339165/21332438/8032853a-c62f-11e6-9f80-e612a57ef88f.png)

**Comment by kooboo-chenhai** [comment]
I give you a simple example without the second bug ,  because the second bug can't be reappeared in it .
![qq 20161220134811](https://cloud.githubusercontent.com/assets/13828467/21339526/fab83b70-c6ba-11e6-95dd-43169aa442b1.png)
![qq 20161220134846](https://cloud.githubusercontent.com/assets/13828467/21339535/0e4bf3fc-c6bb-11e6-96f6-244c645bbbaf.png)
[website.zip](https://github.com/Microsoft/vscode/files/662888/website.zip)

**Comment by mjbvz** [comment]
I'm unable to reproduce this issue. 


```js
import { mapGetters } from 'vuex';

export default {
    name: 'Main',
    computed: {
        ...mapGetters({
            appBodyClass: 'fsanu'
        })
    }
}
```

![screen shot 2017-01-04 at 5 37 46 pm](https://cloud.githubusercontent.com/assets/12821956/21666110/95dc94c6-d2a4-11e6-97f0-f10253f78c75.png)


@kooboo-chenhai iIf you are still setting this error, please provide a small example project so that we can investigate.

Thanks

**Comment by transtone** [comment]
"html.validate.scripts": false
