### ISSUE TITLE
Add history of commit messages to commit message text box

### ISSUE THREAD

**Issue by tobyash86** [microsoft/vscode#175102]
It would be very helpful to have a history for let's say 10 to 20 last commit messages to quickly pick one of them and fine-tune it instead of rewriting the same message for similar commits (TortoiseGit has such feature).

**Comment by jahuarcristian** [comment]
Ok

**Comment by gjsjohnmurray** [comment]
@tobyash86 did you try pressing the UpArrow key while in the field?

**Comment by tobyash86** [comment]
Now I did... Works fine, thanks!
