### ISSUE TITLE
Hard to unfocusing selected folder when children of root folder is maximum the explorer window

### ISSUE THREAD

**Issue by yosualb** [Microsoft/vscode#17514]
- VSCode Version: Code 1.8.0 (38746938a4ab94f2f57d9e1309c51fd6fb37553d, 2016-12-13T17:45:32.595Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

|Extension|Author|Version|
|---|---|---|
|Go|lukehoban|0.6.51|
|sublime-keybindings|ms-vscode|1.8.0|

---

Steps to Reproduce:

1. Give extra space on root (project) folder explorer for unfocusing selected folder for creating new folder in root folder
2. Or, give a command to create new folder in root folder

**Comment by kieferrm** [comment]
@yosualb, you can unselect an item in the file explorer by pressing `ESC` twice.

**Comment by yosualb** [comment]
the double `ESC` helps me a lot, thanks.
