### ISSUE TITLE
Notebook rendering doesn't update after cell is run

### ISSUE THREAD

**Issue by TylerLeonhardt** [microsoft/vscode#175173]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 
- OS Version: 

Steps to Reproduce:

1. run all cells in: https://insiders.vscode.dev/github/microsoft/vscode/blob/cd6a0795cfdaf93067861622c86a5cd215c1ad1e/.vscode/notebooks/my-endgame.github-issues
2. wait for some issues to be closed
3. run all cells again
4. sometimes I notice this:
![image](https://user-images.githubusercontent.com/2644648/220756072-ec11b221-a33a-4a09-b7cc-6c150a3247b4.png)

0 results but yet there is still one in the renderer.

Something is fishy... I opened this issue in the vscode repo since I'm suspicious of a change there.

workaround: run a cell directly to have the renderer update.

thought: could this have something to do with cells being off screen not updating their rendering?

**Comment by rebornix** [comment]
This is not a regression thus moving to March. The catch here is it's an output update optimization to allow us reuse output container to avoid output flicker. However GitHub Issue Notebook renderer probably doesn't clear output container when re-using the output container.

**Comment by rebornix** [comment]
Should be fixed now in Insiders.

**Comment by TylerLeonhardt** [comment]
I haven't seen this recently so marking as verified.
