### ISSUE TITLE
keyboard shortcut for Save prompt

### ISSUE THREAD

**Issue by mathurk29** [microsoft/vscode#175124]
Can we have keyboard shortcuts for Save prompt on Mac - like  Cmd+S for Save, Cmd+N for Don't Save and Cmd+C for cancel?

Also if the automatic focus can go to prompt and one can use <Tab> to navigate inside the prompt would be lovley.

Right now, one has to remove his hand from keyboard and move to mouse interact with the prompt.

<img width="257" alt="image" src="https://user-images.githubusercontent.com/11696863/220654279-f56cbbbf-fb42-41c4-a0a1-4cf861961265.png">

**Comment by gjsjohnmurray** [comment]
I'd expect Esc to cancel, Enter to Save, and Tab followed by Enter to be the equivalent of clicking "Don't Save".

**Comment by mathurk29** [comment]
> I'd expect Esc to cancel, Enter to Save, and Tab followed by Enter to be the equivalent of clicking "Don't Save".

Thanks. I was able to Esc to cancel, Enter to Save -- however Tab doesn't work - so Tab + Enter would effectively becomes `Enter` i.e. Save and would again open up Command Palette for putting in FileName.

**Comment by mathurk29** [comment]
A button highlight and underscore suggestion might make it intuitive for users.

**Comment by bpasero** [comment]
I should get payed by Apple for the macOS support I have given so far...

![Screenshot 2023-02-22 at 16 47 28](https://user-images.githubusercontent.com/900690/220677274-007b0c25-31d8-4c47-b589-df41a79f482f.png)
