### ISSUE TITLE
Some possible improvements to the accessibility buffer

### ISSUE THREAD

**Issue by jvesouza** [microsoft/vscode#175133]
Type: <b>Feature Request</b>

CC: @meganrogge  @isidorn 
At least in my environment, whenever I access the terminal's accessibility buffer, the focus is always moved to the beginning of it. This causes us to lose some time to find the begin of the response of the last command executed, especially if the response is long.
Would it be possible to update the accessibility buffer without changing the focus? The focus position would remain the same since the last access.

When executing a long-running command in the terminal, there seems to be no easy way to find out its status, since the accessibility buffer is only updated at the end of the command.
If, for example, the command being executed asks me for some intervention and if for some reason I have not heard this request, there would be no easy way to repeat it.

VS Code version: Code - Insiders 1.76.0-insider (7b6b6869e8f5b71b5e9cdbd3f590b10964f89607, 2023-02-22T05:27:34.124Z)
OS version: Linux x64 6.1.12-200.fc37.x86_64
Modes:
Sandboxed: Yes
Remote OS version: Linux x64 4.14.146-93.123.amzn1.x86_64

**Comment by meganrogge** [comment]
Thank you for the issue. We're tracking those here:

/duplicate #175011  and #172582
