### ISSUE TITLE
Notebook unable to close when creating profile

### ISSUE THREAD

**Issue by rzhao271** [microsoft/vscode#175156]
On the latest Insiders,

1. Have the default profile open.
2. Open a Jupyter notebook with a few cells.
3. Edit a cell but leave the notebook unsaved.
4. Create a new empty profile, save if prompted. For me, the notebook seems to autosave and close.
5. Repeat steps 2 and 3 with the same notebook and same cell.
6. Create a new empty profile. Don't save if prompted.
7. :bug: Try closing the notebook, pressing "don't save" when prompted. The notebook doesn't close.

During step 6, I get a save dialog and a "failed to save notebook" notification at the same time.
![Screenshot of dialog and notification](https://user-images.githubusercontent.com/7199958/220725068-4c274688-fded-4adb-8802-ce8662e304c5.png)

**Comment by rebornix** [comment]
It should always save and also the save logic should be able to pick up serializer from the new profile.
