### ISSUE TITLE
Language Server Crashes and Non-functioning elements

### ISSUE THREAD

**Issue by AGoh2019** [microsoft/vscode#175199]
Type: <b>Bug</b>

I am not happy that C code, and perhaps C++ code cannot run on VS Code.  Have VS IDE with C/C++ installed. The Perl and Java Language Servers also crash on startup of VS Code. Why can't Microsoft fix all these issues and stop leaving them around.

VS Code version: Code 1.75.1 (441438abd1ac652551dbe4d408dfcec8a499b8bf, 2023-02-08T21:32:34.589Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz (8 x 2419)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.77GB (7.52GB free)|
|Process Argv|--crash-reporter-id 878a6b85-9049-465e-849e-1cc9b3b95d57|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by dbaeumer** [comment]
@AGoh2019 this repository is about VS Code core. The language support comes from extensions so can you please open issue against the following repositories:

- C/C++: https://github.com/microsoft/vscode-cpptools
- Java: https://github.com/Microsoft/vscode-java-pack

For perl you need to identify the perl extension you are using and report the error to that extension.
