### ISSUE TITLE
Align touchscreen restore button behaviour with Edge

### ISSUE THREAD

**Issue by rzhao271** [microsoft/vscode#175144]
Ref https://github.com/microsoft/vscode/issues/159851#issuecomment-1438404208

On Windows 11 on Insiders using a touchscreen device:

Steps to Reproduce:

1. Press the maximize button.
2. Press the restore button.
3. :bug: Unable to restore.

This behaviour occurs because Electron has restore functionality disabled when WCO and "touch mode" are enabled.

**Comment by deepak1556** [comment]
Closing as there weren't any follow-up asks on this behavior and not something we will work on anytime soon.
