### ISSUE TITLE
[Accessibility] Redundant read-only terminal buffer needs to be removed from the tab focus cycle.

### ISSUE THREAD

**Issue by jooyoungseo** [microsoft/vscode#175111]
CC @meganrogge

1. Load NVDA.

1. Open terminal.

1. Shift+Tab to the monaco terminal buffer editor.

1. Shift+Tab again: you will be landed in another (redundant) terminal read-only area.

## Expected Behavior

The redundant read-only terminal buffer needs to be removed from the tab focus.

## System Info

Version: 1.76.0-insider (system setup)
Commit: 7b6b6869e8f5b71b5e9cdbd3f590b10964f89607
Date: 2023-02-22T05:24:32.270Z
Electron: 19.1.10
Chromium: 102.0.5005.196
Node.js: 16.14.2
V8: 10.2.154.26-electron.0
OS: Windows_NT x64 10.0.22621
Sandboxed: Yes

**Comment by jvesouza** [comment]
This is confirmed using orca.

**Comment by jvesouza** [comment]
It would be great if there was the possibility of not changing the position of the cursor during the buffer update, preserving the position of the last access.
I believe that this would help in identifying the beginning of the response of the last executed command.
