### ISSUE TITLE
build config not working for vscode repo

### ISSUE THREAD

**Issue by eleanorjboyd** [microsoft/vscode#175167]
Testing #174870

So I tried this TPI both on the vscode and the monaco repo. The monaco one worked seamlessly on build directly popping up a window in chrome with the editor. The same was not true for vscode- the build stalled at `Executing task: node_modules/.bin/http-server --cors --port 5001 -a 127.0.0.1 -s -c-1`. Since the vscode repo uses yarn I think that could be a problem and Rob noted that the Launch HTTP Server task definition might not work because pattern.regexp is empty.

**Comment by hediet** [comment]
Thanks for testing!
Fixed in https://github.com/microsoft/vscode/pull/175147
