### ISSUE TITLE
Wrong active tab title background in dark theme with "uiTheme": "vs"

### ISSUE THREAD

**Issue by strrchr** [Microsoft/vscode#17510]
- VSCode Version: Code 1.8.0 (38746938a4ab94f2f57d9e1309c51fd6fb37553d, 2016-12-13T17:45:32.595Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions:

|Extension|Author|Version|
|---|---|---|
|xml|DotJoshJohnson|1.6.0|
|auto-close-tag|formulahendry|0.3.6|
|auto-rename-tag|formulahendry|0.0.8|
|green-theme|vscode|0.1.0|
|beautify|HookyQR|0.6.2|
|theme-material-theme|jprestidge|1.0.1|
|cpptools|ms-vscode|0.9.3|
|vscode-icons|robertohuertasm|4.2.0|

---

Steps to Reproduce:

1. Active tab title background should be controlled by uiTheme, should not follow the background of tmTheme.
2. Inactive tab title background does not have the problem.

**Comment by bpasero** [comment]
@strrchr can you share a screenshot what you mean?

**Comment by strrchr** [comment]
![default](https://cloud.githubusercontent.com/assets/8603093/21305658/e878b678-c607-11e6-87ab-25795422649b.png)
My thTheme is a dark theme.
I set its uiTheme to "vs".
Then the active tab title's background color is black. It seems the color is follow my thTheme. I think it should be controlled by uiTheme.
			{
				"label": "Green V3 Theme",
				"uiTheme": "vs",
				"path": "./GreenV3Theme.tmTheme"
			},

**Comment by bpasero** [comment]
I think in this case the UI theme has to be set to vs-dark. Moving to @aeschli to confirm.

**Comment by aeschli** [comment]
If your theme is a dark theme then you have to set `"uiTheme": "vs-dark",`
