### ISSUE TITLE
Configured default shell not used when reconnecting to Codespace

### ISSUE THREAD

**Issue by lumaxis** [microsoft/vscode#175107]
Does this issue occur when all extensions are disabled?: Yes

Version: 1.75.1 (Universal)
Commit: 441438abd1ac652551dbe4d408dfcec8a499b8bf
Date: 2023-02-08T21:34:59.000Z
Electron: 19.1.9
Chromium: 102.0.5005.194
Node.js: 16.14.2
V8: 10.2.154.23-electron.0
OS: Darwin arm64 22.3.0
Sandboxed: Yes

When reconnecting to an existing Codespace, my `"terminal.integrated.defaultProfile.linux"` configuration is ignored. Instead of `zsh`, the terminal always starts `bash`.

The same/a similar issue used to exist in early 2022 but was presumably fixed with https://github.com/microsoft/vscode/pull/154290, however this appears to have regressed over the last weeks/months.

Steps to Reproduce:

1. Configure `"terminal.integrated.defaultProfile.linux": "zsh"`
2. Create a Codespace & stop it
3. Reconnect to the Codespace
4. See that the terminal opens using `bash`

**Comment by meganrogge** [comment]
can reproduce

<img width="628" alt="Screenshot 2023-02-22 at 2 35 56 PM" src="https://user-images.githubusercontent.com/29464607/220752819-8544842a-9eab-4dee-925d-7c87427e67c8.png">

**Comment by jeanp413** [comment]
PR fixing it https://github.com/microsoft/vscode/pull/175844

**Comment by Tyriar** [comment]
Repro in OSS:

1. Set `"terminal.integrated.defaultProfile.windows": "Command Prompt"` (or whatever the platform is)
2. Open a test resolver window
3. Open the panel
4. Reload, :bug: it's not the shell defined in step 1

**Comment by lumaxis** [comment]
Thanks everyone! _So_ glad this is fixed now ❤️

**Comment by alexr00** [comment]
I can still repro this issue:
1. Set `"terminal.integrated.defaultProfile.linux": "zsh"`
2. From within VS Code desktop (on Windows, if it matters), create a Codespace
3. Open a terminal in the new Codespace and run `ps`. See that `zsh` is one of the processes ✅
4. Command "Codespaces: Stop Current Codespace"
5. Open the Remote Explorer and connect to the Codespace from steop 2
6. On a terminal in the Codespace and run `ps`. No `zsh` processes are listed.

**Comment by jeanp413** [comment]
Seems it's only for the above case only now, using codespaces extension which I cannot test from sources :sweat_smile:, before I could repro easily with my SSH extension too which is working properly now
