### ISSUE TITLE
Windows7 : unable to update

### ISSUE THREAD

**Issue by ecxod** [microsoft/vscode#175183]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.75.1
- OS Version:  Windows 7 Professional

Steps to Reproduce:

1. tried toUpdate on Windows 7
2. it does not work. 

What dependency do I need to install ?

**Comment by gjsjohnmurray** [comment]
See https://code.visualstudio.com/docs/supporting/faq#_can-i-run-vs-code-on-windows-7
