### ISSUE TITLE
Any way to show the number of open files?

### ISSUE THREAD

**Issue by elias6** [microsoft/vscode#175280]
Is there any (easy and practical) way to show the number of files I have open in a given window?

This might sound silly, but I would like to see this number, so if it gets too high, I can use it as a reminder to close some files I no longer need to have open, to reduce the amount of clutter in the "open editors" section and make it easier to find the open files I need.

I can see the number of open files by clicking in the "open editors" section, pressing command+A, and using my trackpad to drag the selection to the side slightly so it shows the number. But this is obviously a hacky and inelegant solution that most people probably won't discover. And if I accidentally click one of the "X"s next to the files, it will [close all my open files](https://github.com/microsoft/vscode/issues/143970), which I think is annoying.

I wish there was an easy way to just see a number that shows how many open files I have.

**Comment by lramos15** [comment]
An extension can do this. Here's a sample of a tab cleaner https://github.com/microsoft/vscode-extension-samples/tree/main/tabs-api-sample

**Comment by elias6** [comment]
What? I still want to manually decide whether to close my tabs, not have something close them automatically.

**Comment by lramos15** [comment]
> Why was this closed? I still want to manually decide which tabs to close, not have something close them automatically.

It was closed because you can write an extension that provides you the info for how many editors you have open and put that in the status bar or wherever you'd like. This extension could then let the user pick which tabs to close. My sample was just one way of doing it to show you how the API works.
