### ISSUE TITLE
Different configuration levels to support profiles.

### ISSUE THREAD

**Issue by DiegoBM** [microsoft/vscode#175235]
The same way that there are "User" and "Workspace" settings, now that we have "profiles" it would be really useful to include a new level of settings for profiles as well, so that we can have overrides common to all profiles and overrides specific for certain profiles.

My particular use case is that I have multiple profiles, 10 approximately, and there are some customizations/overrides that I'd like to have in all of them and some that I'd like to have in specific profile. For example, for keyboard shortcuts, there are keyboard shortcuts like one for expanding the terminal that I'd like to have in all of them, and other keyboard shortcuts like "search in unreal documentation", that I'd like to have in the "Unreal" profile only. At the moment, every time that I figure out a new "global"-ish shortcut that I'd like to have in all profiles, I need to switch to all of them and manually insert/copy it, which is incredibly inconvenient, specially since sometimes I'm not fully settled on that shortcut yet and some time later I realise that another one would suit it better.

Another possible alternative would be to be able to export just the shortcuts from a given profile (which can be done currently), and import that exported data into another profile with some degree of diffing or merging capabilities

**Comment by sandy081** [comment]
/duplicate

https://github.com/microsoft/vscode/issues/156144

**Comment by DiegoBM** [comment]
Apologies, I can see in your issue that it's mentioned a few times. Thank you for the reference
