### ISSUE TITLE
Investigate recent insiders performance regression

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#175275]
Over the last days insiders startup performance has regressed... This can be narrowed down to two markers below and needs investigation

```
 let compare1 = "code/willConnectSharedProcess";
 let compare2 = "code/willHandleExtensionPoints";
```

<img width="1291" alt="Screenshot 2023-02-23 at 19 29 59" src="https://user-images.githubusercontent.com/1794099/220998155-be55d0d9-f78c-4cb6-a747-9ed2bab3352d.png">

A suspect could be e9229a18805fdb9baf7356ddc31bd216da5842ef. Tho, that changes makes us start a process (a little) sooner right after startup (`Ready` phase) and I would be surprised if that has an impact...

@bpasero other ideas?

**Comment by bpasero** [comment]
I need to check the commits that went in in that time where it happened, can do that later today.

As for spawning processes earlier: I remember we had a major perf regression when I spawned the utility process without delay from the renderer, which then made me add this race:

https://github.com/microsoft/vscode/blob/720985f2c68cadb5e375d9ec671476c548f61769/src/vs/workbench/services/sharedProcess/electron-sandbox/sharedProcessService.ts#L42

So this could have an impact, maybe we could use exploration builds to measure the difference, since now the 2 are showing similar performance? That way we would not have to go to `main`. Exploration builds are from the https://github.com/microsoft/vscode/tree/electron-22.x.y branch.

//cc @deepak1556

**Comment by jrieken** [comment]
@bpasero nice idea. I have pushed a revert to `electron-22.x.y` and I am kicking off a new build

**Comment by bpasero** [comment]
I did a quick scan over the commits that went in after `4e32196835 ` and until `7b6b6869e8 ` and here are some that may contribute to slowness, but to be honest, the EH one sounds  like the most likely one to me:
* context keys are now parsed and lexed: https://github.com/microsoft/vscode/pull/174471 @ulugbekna @alexdima 
* we set `en` as fallback language which may trigger NLS bundle lookup? https://github.com/microsoft/vscode/pull/175039 @rzhao271 @TylerLeonhardt 
* we send large RPC messages in chunks of max `256kb` https://github.com/microsoft/vscode/pull/174278 @alexdima

**Comment by bpasero** [comment]
Interestingly, the mac perf bot regression appeared on the same day on a later build on Monday:

<img width="915" alt="Screenshot 2023-02-24 at 10 42 34" src="https://user-images.githubusercontent.com/900690/221145997-22e0786f-fe74-4762-af2b-d33ad6933b07.png">

**Comment by jrieken** [comment]
Testing locally (reverting 21718a1e56b98ae9642471dae4b855ccdcf14a7c) shows a difference in the sequence of marker, esp the `willLoadExtensions`-marker is now happing sooner and therefore "impacting" sooner with restoring of the workbench. 

<img width="1457" alt="Screenshot 2023-02-24 at 10 45 54" src="https://user-images.githubusercontent.com/1794099/221146768-66b65664-bf50-49b1-8a80-bac462c212b9.png">


This must not be bad but it doesn't change what we measure (the bot takes the `didStartWorkbench` as its finish mark) and therefore I'll revert the change for now and I propose to make this an informed decision early next milestone.

**Comment by ulugbekna** [comment]
The new parser for context keys isn't used for parsing yet, so it shouldn't affect the startup performance

**Comment by alexdima** [comment]
The chunking of large websocket messages can only impact remote scenarios, so it shouldn't affect the local startup performance

**Comment by TylerLeonhardt** [comment]
> we set en as fallback language which may trigger NLS bundle lookup? https://github.com/microsoft/vscode/pull/175039 @rzhao271 @TylerLeonhardt

I doubt it would be this change as this change only affected runs in an alternate language to English

**Comment by bpasero** [comment]
<img width="581" alt="image" src="https://user-images.githubusercontent.com/900690/221351338-f8559271-a32f-4d8d-b69c-091c66c41e2d.png">

A lot better with latest insiders that includes the revert.
