### ISSUE TITLE
'catch-all' error handler is easily confused by source-map-support library

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#175288]
Many extensions, including Github's, [use the source-map-support library](https://github.com/github/codespaces/issues/12468#issuecomment-1442426516), which overwrites `Error.prepareStackTrace` and breaks error telemetry collection for the _entire_ extension host.

This obviously is not a nice way for the library to behave, but we should try to find a less-fragile way to correlate errors than overriding `prepareStackTrace`. For example, we could parse the stacktrace once the error is caught instead/as a fallback, or `Object.defineProperty(Error, 'prepareStackTrace', ...)` to make it a getter/setter that ensures the tracking function is called.

https://github.com/microsoft/vscode/blob/89781185b9b78834f2e032cf611397b87bcae836/src/vs/workbench/api/common/extensionHostMain.ts#L72

**Comment by jrieken** [comment]
> and breaks error telemetry collection for the entire extension host.

I think it's not that dramatic since this is only used for unhandled errors, eg those from event listener or timeout/interval calls. Other errors, like when calling a provider, should be caught in-place and already be handled. 

Nevertheless, I like the idea of using a getter/setting for this.
