### ISSUE TITLE
Executing `vscode.executeFormatDocumentProvider` with HTML files can return end range exceeding file length

### ISSUE THREAD

**Issue by allisonchou** [microsoft/vscode#175298]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.76.0-insider
- OS Version: Windows 11

Using the built-in command `vscode.executeFormatDocumentProvider` (spec'd [here](https://code.visualstudio.com/api/references/commands)) using an HTML URI can return a range that exceeds the length of the source file.

For example, invoking the above command on a completely empty HTML file will return a range of (startPosition: (0, 0); endPosition: (1, 0)) despite there only being one line in the file. This has caused several bugs to be filed on the Razor team. We've implemented a workaround for now, but we hope to have this issue formally fixed in the near future.

**Comment by jrieken** [comment]
These commands return the data mostly as provided by extensions - no much cleanup or other tweaks. The editor, before applying, sanitises and minimises edits only later

**Comment by allisonchou** [comment]
@jrieken From my understanding, the HTML experience in VS Code is built-in and is not provided by a specific extension. Is that assumption incorrect?

**Comment by jrieken** [comment]
Yes and no. HTML is also an extension but it is bundled with the product (that's the only special thing about it)

**Comment by allisonchou** [comment]
@jrieken Gotcha, thanks for the clarification. I think perhaps this issue should be moved to the microsoft/vscode-html-languageservice repo then? Would you be able to transfer it?

**Comment by allisonchou** [comment]
I ended up just creating another issue in the microsoft/vscode-html-languageservice repo - https://github.com/microsoft/vscode-html-languageservice/issues/153. I'll close this one out, thanks!
