### ISSUE TITLE
Language problem in vscode.dev 

### ISSUE THREAD

**Issue by BhJaipal** [microsoft/vscode#175238]
For some time I have not used vscode Dev, I use mobile
But I opened it, its language was in Japanese and I know English but not Japanese.
Please help

**Comment by BhJaipal** [comment]
> For some time I have not used vscode Dev, I use mobile
> But I opened it, its language was in Japanese and I know English but not Japanese.
> Please help

how do I change language, help

**Comment by TylerLeonhardt** [comment]
@BhJaipal I noticed you closed this. Did you figure it out? You can run `Configure Display Language` in the Command Palette to change the language.

**Comment by BhJaipal** [comment]
> @BhJaipal I noticed you closed this. Did you figure it out? You can run `Configure Display Language` in the Command Palette to change the language.

Let me try

**Comment by BhJaipal** [comment]
I am using vscode dev, and I don't the option  in it
It's language is in Japanese and I don't know that is this written

**Comment by TylerLeonhardt** [comment]
Here's a video:

https://user-images.githubusercontent.com/2644648/221256319-fcb93e3a-4328-4d03-84cc-99ded83c99b2.mp4

* Open the Command Palette
* Run Configure Display Language
* English
* ENTER

**Comment by BhJaipal** [comment]
> Here's a video:
> 
> https://user-images.githubusercontent.com/2644648/221256319-fcb93e3a-4328-4d03-84cc-99ded83c99b2.mp4
> 
> * Open the Command Palette
> * Run Configure Display Language
> * English
> * ENTER
> 

@TylerLeonhardt 
thank you so much, It worked 
And thanks for giving time to help me
