### ISSUE TITLE
Has OutputEvent changed in VSCode 1.8?

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#17526]
_From @dibyendumajumdar on December 16, 2016 18:7_

Hi @weinand ,

After upgrading to VS Code 1.8 I notice that the debug adapter output is getting messed up. Specifically it seems new lines are being added after every output event? This means that if the debug adapter sends following sequence the result is displayed broken up in multiple lines:

```
{"type":"event","seq":15,"event":"output","body":{"category":"stdout","output":"expected "}}
{"type":"event","seq":16,"event":"output","body":{"category":"stdout","output":"\t"}}
{"type":"event","seq":17,"event":"output","body":{"category":"stdout","output":"1.0"}}
{"type":"event","seq":18,"event":"output","body":{"category":"stdout","output":"\t"}}
{"type":"event","seq":19,"event":"output","body":{"category":"stdout","output":"-1.0"}}
{"type":"event","seq":20,"event":"output","body":{"category":"stdout","output":"\t"}}
{"type":"event","seq":21,"event":"output","body":{"category":"stdout","output":"1.0"}}
{"type":"event","seq":22,"event":"output","body":{"category":"stdout","output":"\n"}}
```

_Copied from original issue: Microsoft/vscode-debugadapter-node#92_

**Comment by isidorn** [comment]
We need to improve this such that vscode does not add any fake line endings on output events. In the past we have tried this out however this was breaking link detection.
Since all these things are tightly coupled I am not comfortable changing it in the last day of the sprint, will do it in debt week since we have already shipped one stable with this -> feb

**Comment by keshwaa** [comment]
Hello, 

Appreciate the support in trying to get this fixed. Do we have an ETA on this issue or a workaround? 

Thanks, 
Kesh

**Comment by isidorn** [comment]
@keshwaa this issue is currently assigned to March which means we plan to investigate into fixing it in march. If all works out as planned it should hit stable release some time start of April

**Comment by keshwaa** [comment]
Thanks mate

**Comment by isidorn** [comment]
@keshwaa you can try this out in the insiders build tomorrow and let me know if it fixes the issue for you. We are still not handling the output perfectly but it should be improved as to previous behavior

**Comment by keshwaa** [comment]
Thank you Isidor. I'm new to github are you able to direct me to a link or
location to the new build.

Appreciate your support.

**Comment by isidorn** [comment]
@keshwaa we have a special VS Code insiders builds which updates every day. You can download it from here https://code.visualstudio.com/insiders

**Comment by keshwaa** [comment]
Thank you Isidor. Appreciate your help

**Comment by keshwaa** [comment]
Hi Isidor

Thank you very much. The print function is showing up perfectly in the
debug console. Now I am at peace :))

Appreciate your help.

Best Regards,
Kesh

**Comment by isidorn** [comment]
Glad to hear this is fixed -> adding verified label.
