### ISSUE TITLE
SCM decorations don't go away after committing

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#175259]
- Have some changes, commit in the git view
- The scm gutter decorations are still present in open editors
- If I close and reopen the editor, they go away

Here you can see that there are no changes in this file but the decorations are present

<img width="1176" alt="image" src="https://user-images.githubusercontent.com/323878/220968282-0912ff7c-4873-4854-a921-710b9c3e84f3.png">

**Comment by roblourens** [comment]
I'm also having an issue with the decorations not showing up when there are changes

**Comment by alexr00** [comment]
@roblourens is there anything in the developer console? I gotten maybe 3 reports of behavior like this but I can't reproduce it.

**Comment by roblourens** [comment]
I didn't see any errors
