### ISSUE TITLE
Icons and Badges are white on Light V2

### ISSUE THREAD

**Issue by esonnino** [microsoft/vscode#175204]
![image](https://user-images.githubusercontent.com/113370447/220825119-3f5df9f0-08b0-4e79-9a6f-d9c63a0aabea.png)

When selected, the icons on extension rows are white on white instead of dark grey

@daviddossett

**Comment by daviddossett** [comment]
Is this stable? I think this was fixed in Insiders some time ago.

<img width="289" alt="CleanShot 2023-02-24 at 10 16 38@2x" src="https://user-images.githubusercontent.com/25163139/221258093-b053f9d1-c0ef-4b64-abac-0d912551671d.png">

**Comment by esonnino** [comment]
True! I thought it regressed after the last badges fixes :) Closing here Thanks @daviddossett
