### ISSUE TITLE
Sticky Scroll (Ubuntu with Python)

### ISSUE THREAD

**Issue by theProcrastinatr** [microsoft/vscode#175237]
Does this issue occur when all extensions are disabled?: No, but with one specific extension

- VS Code Version: 1.75.1 -- 441438abd1ac652551dbe4d408dfcec8a499b8bf -- x64
- OS Version: Ubuntu 20.04

Steps to Reproduce:

1. Enable Sticky Scroll. Loops and conditionals also stick to the top along with class and functions.
2. Install Python IntelliSense (Microsoft). Only class and functions stick to the top. Loops and conditionals don't.
3. Uninstall or disable Python IntelliSense and it goes back to normal.

**Comment by gjsjohnmurray** [comment]
Maybe #174958 will help.

**Comment by aiday-mar** [comment]
Hi, thanks for your message. As @gjsjohnmurray was suggesting, once the PR is in, you will be able to define the folding model as the default model to use for sticking the lines. The folding model is based on the indentation and will therefore stick also the for loops.

**Comment by aiday-mar** [comment]
Closing since the PR has been merged
