### ISSUE TITLE
Jump to last position via context menu or application menu (eg edit)

### ISSUE THREAD

**Issue by plaetzchen79** [Microsoft/vscode#17527]
- VSCode Version: 1.7.2
- OS Version: 

I would like to jump directly to the last (cursor) position and last edited page via the context (right mouse) oder application menu. I know that there is a keyboard shortcut. But i am more familiar with mouse navigation.

This is common in visual studio express. 

Ist there a way to achieve this?

**Comment by egamma** [comment]
We want to keep the context menu short and there are corresponding actions in the `Go` pull down menu (`Back`, `Forward`). We have no plans to add them to the context menu.

You can achieve this by an extension that contributes to the editor context menu. If this is a common expectation for VS users then this could be provided by the https://github.com/rebornix/vscode-vs-keybindings extension.
