### ISSUE TITLE
Enter should dismiss dialogs by running the primary button

### ISSUE THREAD

**Issue by SetTrend** [Microsoft/vscode#1752]
Commonly, the [ENTER] and [ESC] keys on the keyboard serve as confirmation and cancel actions, resp., in message boxes.

It looks like Code is currently [lacking prerequisites to denominate a button to be the default button](https://github.com/Microsoft/vscode/blob/e1b4ade218dffd94ba4da3a1ef2d213af41cf7dd/src/typings/atom-renderer.d.ts#L121).

I suggest to add a `confirmId?: number` property to the `IMessageBoxOptions` interface and to add corresponding handlers to the implementation.

**Comment by bpasero** [comment]
Have to follow up with Electron if this is possible. Might require changes there.

**Comment by bpasero** [comment]
@SetTrend on what OS do you see this not working? Looks ok for me on Mac and Win 10.

**Comment by SetTrend** [comment]
Your observation is absolutely right when you are referring to the Save on Close dialog box (which I actually did, too ;) ). This dialog surely works as expected.

But, in fact, that dialog works only by coincidence. It looks like the first button gets focus by default, and, thus, is triggered when pressing [ENTER].

Problems will occur when the first button is *not* supposed to be the default, like in this example:

```
|----------------------------------|
|          Sure to delete?         |
|                                  |
|     [  Yes  ]     [[  No  ]]     |
|                   ----------     |
|----------------------------------|
```

The [Save on Close dialog code](https://github.com/Microsoft/vscode/blob/6319a1e050de957531595511c6999aea653a5c21/src/vs/workbench/parts/files/electron-browser/textFileServices.ts#L193) shows that the Cancel button is determined according to program requirements. Yet, the same functionality is lacking for the Save button.

**Comment by bpasero** [comment]
Right, but this is really something that should be reported against Electron and in fact I did so recently: https://github.com/atom/electron/issues/3810
