### ISSUE TITLE
Unsaved changes for freshly opened files (nothing was changed)

### ISSUE THREAD

**Issue by Tarpsvo** [Microsoft/vscode#17525]
- VSCode Version: Code 1.8.0 (38746938a4ab94f2f57d9e1309c51fd6fb37553d, 2016-12-13T17:45:32.595Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

|Extension|Author|Version|
|---|---|---|
|html-snippets|abusaidm|0.0.18|
|vscode-theme-onedark|akamud|0.2.14|
|aurelia|AureliaEffect|0.1.12|
|Aurelia|behzad88|1.1.0|
|path-intellisense|christian-kohler|1.2.0|
|vscode-eslint|dbaeumer|1.2.2|
|EditorConfig|EditorConfig|0.3.4|
|JavaScriptSnippets|xabikos|1.2.0|
|html-css-class-completion|Zignd|1.0.3|

---

I was unable to produce a reliably reproducable set of steps. It happens for some files in my project, not all. After saving them, they also show up as 'changed' in Git, but when doing a diff on the two, no changes are present. When I try stage the file, the file no longer appears as 'changed' in Git. When I open it again in VSCode, it has unsaved changes again.

I need some guidance in providing you with useful information, for I failed to find anything useful.

**Comment by egamma** [comment]
@Tarpsvo what file types (e.g. JS) showed this behaviour? 
When this happens again can do a `git status` on the command line, does it also show the file as changed?

**Comment by Tarpsvo** [comment]
Yes. File types that showed this behaviour are for example .html, .js and .scss.

I can easily reproduce it in my project. I suspected it has something to do with line-endings, but they all seem to be consistently LF, since I've used the same `.editorconfig` file and plugin ever since I started the project.

**Comment by egamma** [comment]
>Command-line git status also shows the file as modified.

This means that VS Code shows the git status correctly and you need to find out what causes the change to the file. 

First suspicion is that this could be caused by an extension you have installed.  Can you reproduce this when you have disabled all the extensions. This can be done using  `--disable-extensions` command line option or you disable the extensions in the extensions viewlet.

**Comment by Tarpsvo** [comment]
Whoops, turned out to be an issue caused by `editorconfig` plugin indeed. Not a VSCode issue. Thank you for your help, I'll report the same problem in their repository instead.
