### ISSUE TITLE
Error: Make sure to edit the README.md file before you publish your extension.

### ISSUE THREAD

**Issue by chris-miner** [microsoft/vscode#175292]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: not relevant
- OS Version: not relevant

Steps to Reproduce:

1. Create an extension
2. install vsce (npm install -g @vscode/vsce)
3. run vsce package at the command line
4. notice error => ERROR  Make sure to edit the README.md file before you package or publish your extension.
5. edit README.md
6. run vsce package again

found:
the same error is produced

expected:
the error would not be produced.

extra info:
I'm just trying to create a local package of my extension for use on my local machine in my local development environment.  I'd rather not guess what vsce needs to see in my README.md before it will not announce errors.  This seems related to #14730

workaround:
Deleting the contents of my README.md remedied the error message.  I now have a completely empty README.md file. The vsce tool has no issues with that.

**Comment by ulugbekna** [comment]
I faced the same problem today. Would this message be more helpful: "It seems the README.md still contains template text. Make sure to edit the README.md file before you package or publish your extension." ?

**Comment by chris-miner** [comment]
Or perhaps leave it as a warning rather than an error.  I can see that if I was actually publishing it I would want to not publish boiler-plate.  Or maybe don't provide the boiler-plate.  I don't really see any good solutions to the issue.  However, If the complaint expressed in the error is that the README.md was not edited, and the README.md was edited, then the 'error' doesn't make a lot of sense.
