### ISSUE TITLE
MAC: search not working => Visual Studio Code.app/Contents/Resources/app/node_modules.asar.unpacked/@vscode/ripgrep/bin/rg EMFILE

### ISSUE THREAD

**Issue by anuj1873** [microsoft/vscode#175201]
Does this issue occur when all extensions are disabled?: Not specific.

Error: When I search in vscode. Getting the issue given in snapshot

<img width="1792" alt="image" src="https://user-images.githubusercontent.com/15086942/220823040-9f52269c-25f7-44c9-984b-3b28ca9e73b0.png">

VS code details:

Version: 1.75.1 (Universal)
Commit: 441438abd1ac652551dbe4d408dfcec8a499b8bf
Date: 2023-02-08T21:34:59.000Z (1 wk ago)
Electron: 19.1.9
Chromium: 102.0.5005.194
Node.js: 16.14.2
V8: 10.2.154.23-electron.0
OS: Darwin x64 22.3.0
Sandboxed: No

- OS Version:  MAC -  Ventura, 13.2.1

**Error:** 

1: workbench.desktop.main.js:2020 Error: listen EACCES: permission denied /extbin/basctlSocket
	at Server.setupListenHandle [as _listen2] (node:net:1313:21)
	at listenInCluster (node:net:1378:12)
	at Server.listen (node:net:1476:5)
	at createBasctlServer (/Users/I322952/.vscode/extensions/saposs.app-studio-toolkit-1.8.4/dist/extension.js:90657:14)
	at /Users/I322952/.vscode/extensions/saposs.app-studio-toolkit-1.8.4/dist/extension.js:90666:13
	at FSReqCallback.oncomplete (node:fs:198:21)

2:  spawn /Applications/Visual Studio Code.app/Contents/Resources/app/node_modules.asar.unpacked/@vscode/ripgrep/bin/rg EMFILE**
  log.ts:404   ERR [Extension Host] Error: spawn /Applications/Visual Studio           Code.app/Contents/Resources/app/node_modules.asar.unpacked/@vscode/ripgrep/bin/rg EMFILE
   at ChildProcess._handle.onexit (node:internal/child_process:283:19)
  at onErrorNT (node:internal/child_process:478:16)
  at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
enter image description here enter image description here

Read the link given below for this error however does not able to understand to proceed.

https://github.com/microsoft/vscode/issues/9872

Please help. Thanks in advance. 

Regards, 
Anuj

**Comment by andreamah** [comment]
This is likely an OS problem with too many open files on your machine. Please try to increase the limit on open files.
