### ISSUE TITLE
Kernel picker shows up when pressing run button even when there is only one suggested option

### ISSUE THREAD

**Issue by rzhao271** [microsoft/vscode#175272]
Testing microsoft/vscode-jupyter#12874

On insiders.vscode.dev with Microsoft Edge and the latest Jupyter and Python pre-install extensions, I noticed that when I run a notebook by pressing the run notebook button, I get prompted to select a kernel, but that there's only one recommended kernel anyway. I'm wondering whether the kernel picker should just pick that kernel in this case?
![Kernel picker with only one suggested option](https://user-images.githubusercontent.com/7199958/220441854-a04f0824-3411-49b9-bae6-7f39f9137c4e.png)

**Comment by DonJayamanne** [comment]
Thank you for filing this issue, unfortunately we do not have any plans on resolving this issue.
