### ISSUE TITLE
Segmentation fault core dump

### ISSUE THREAD

**Issue by O-ekiri** [microsoft/vscode#175274]
ADD ISSUE DESCRIPTION HERE
I am currently encountering segmentation fault each time I try to run a program.
Version: 1.75.1
Commit: 441438abd1ac652551dbe4d408dfcec8a499b8bf
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36
Embedder: codespaces

**Comment by roblourens** [comment]
This sounds like an issue with your code or project config. If you think vscode is doing something wrong, please give much more detail
