### ISSUE TITLE
Typo, easy fix

### ISSUE THREAD

**Issue by kingbonio** [Microsoft/vscode#17529]
- VSCode Version: 1.7.2
- OS Version: Debian 8.6

Steps to Reproduce:

1. ctrl+shift+f
2. Toggle search details

Settings appears as "files excluded through set tings"

**Comment by rohmanhm** [comment]
Try to use the new version of [vscode](https://code.visualstudio.com/)

**Comment by egamma** [comment]
This fixed in 1.8.0
