### ISSUE TITLE
Windows Accessibilty feature 'text cursor indicator' shows up at wrong position in VSC?

### ISSUE THREAD

**Issue by TLorenzPH** [microsoft/vscode#175236]
Type: <b>Bug</b>

Hi

The cursor shows up some some lines above or below the currently beeing edited one...

Regards
Thomas Lorenz
tlorenz@parker.com

VS Code version: Code 1.75.1 (441438abd1ac652551dbe4d408dfcec8a499b8bf, 2023-02-08T21:32:34.589Z)
OS version: Windows_NT x64 10.0.19045
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10850H CPU @ 2.70GHz (12 x 2712)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.75GB (14.78GB free)|
|Process Argv|--crash-reporter-id 9055ffe6-90e7-4597-a541-4e0379131a14|
|Screen Reader|yes|
|VM|44%|
</details><details><summary>Extensions (26)</summary>

Extension|Author (truncated)|Version
---|---|---
doxdocgen|csc|1.4.0
vscode-pull-request-github|Git|0.58.2
iar-build|iar|1.20.3
iar-debug|iar|1.20.1
c-cpp-flylint|jbe|1.13.0
better-cpp-syntax|jef|1.17.2
dupchecker|jia|0.1.7
vscode-undo-buttons|kco|1.1.1
letmeplaythemusic|lan|2.0.0
vscode-language-pack-de|MS-|1.75.2023021509
remote-containers|ms-|0.275.1
remote-ssh|ms-|0.96.0
remote-ssh-edit|ms-|0.84.0
remote-wsl|ms-|0.75.3
cmake-tools|ms-|1.13.45
cpptools|ms-|1.14.3
cpptools-extension-pack|ms-|1.3.0
remote-explorer|ms-|0.2.0
vscode-embedded-tools|ms-|0.6.0
vsliveshare|ms-|1.0.5831
vsliveshare-audio|ms-|0.1.93
back-n-forth|nic|3.1.1
day-night-touch|oli|0.0.1
vscode-task-buttons|spe|1.1.0
scm-buttons-vscode|tom|0.1.1
cmake|twx|0.0.17

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
pynewvextcfv2:30669238
azure-dev_surveyone:30548225
pyindex848:30662994
nodejswelcome1:30587005
3biah626:30602489
pyind779cf:30662993
89544117:30613380
pythonsymbol12cf:30657549
a9j8j154:30646983
pythonb192:30669360

```

</details>

**Comment by TLorenzPH** [comment]
![image](https://user-images.githubusercontent.com/112183749/220918298-945daa50-5ab9-4dee-a992-8d1cdc71612f.png)

**Comment by roblourens** [comment]
Sorry, I don't understand, what is that screenshot showing?

**Comment by TLorenzPH** [comment]
Hi

Normal cursor and windows accessibility feature text cursor.

***@***.***

https://www.tenforums.com/tutorials/137349-turn-off-text-cursor-indicator-windows-10-a.html

Mit freundlichen Grüßen / Best Regards
Thomas Lorenz

Thomas Lorenz - R&D Senior Engineer | Software & Drives
Phone: +49 781 509 0 - Fax: +49 (0781) 509 98129
E-Mail: ***@***.******@***.***>
Parker Hannifin Manufacturing Germany GmbH & Co. KG
Electric Motion & Pneumatic Division, EMPD
Robert-Bosch-Str. 22
77656 Offenburg (Germany)
Tel.: + 49 (0)781 509-0
Fax: + 49 (0)781 509 98176
Parker Hannifin Manufacturing Germany GmbH & Co. KG - Sitz: Bielefeld - Amtsgericht: Bielefeld HRA 15699
Persönlich haftende Gesellschafterin: Parker Hannifin GmbH - Sitz Bielefeld - Amtsgericht Bielefeld HRB 35489
Geschäftsführung: Ulrich Jochem, Achim Kohler, Kirsten Stenvers, Andreas Paulsen.
Vorsitzender des Aufsichtsrates: Dr.-Ing. Gerd Scheffel
www.parker.com/eme<http://www.parker.com/eme>

***@***.***<https://twitter.com/parkerhannifin>  ***@***.*** <https://www.linkedin.com/company/parker-hannifin>    ***@***.***  <http://blog.parker.com/electromechanical>   ***@***.***  <https://www.youtube.com/channel/UCVkctrKqfUjDrbWN0ule7fA>
***@***.***

Von: Rob Lourens ***@***.***>
Gesendet: Freitag, 24. Februar 2023 14:36
An: microsoft/vscode ***@***.***>
Cc: Thomas Lorenz ***@***.***>; Author ***@***.***>
Betreff: [EXT] Re: [microsoft/vscode] Windows Accessibilty feature 'text cursor indicator' shows up at wrong position in VSC? (Issue #175236)


Sorry, I don't understand, what is that screenshot showing?
