### ISSUE TITLE
Move keybinding dispatching off e.keyCode

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#17521]
## Intro

VS Code dispatches keyboard shorcuts to commands by listening to [`keydown`](https://www.w3.org/TR/uievents/#event-type-keydown) events.

At the time VS Code was first released, we shipped with Chromium version 45. It did not support `KeyboardEvent.key`, nor `KeyboardEvent.code` (see the current spec [here](https://www.w3.org/TR/uievents/#interface-keyboardevent)).

It supported `KeyboardEvent.keyCode`, `KeyboardEvent.charCode`, `KeyboardEvent.which` and `KeyboardEvent.keyIdentifier`:
* `KeyboardEvent.charCode` is often not set for `keydown` events, therefore unreliable.
* `KeyboardEvent.which` was, from my testing, always equal to `KeyboardEvent.keyCode`.
* `KeyboardEvent.keyIdentifier` was known to be severely flawed already at that time, and it was marked as deprecated (it got removed in Chromium version 54).
* we were therefore stuck with using `KeyboardEvent.keyCode` for dispatching keyboard shortcuts.

## What is wrong with `KeyboardEvent.keyCode` and why is it deprecated?

The w3c spec is dry (which is a good thing in general, maybe not in this case), and does not explain what went wrong or why it is now deprecated.
In this section, after having browsed through Chromium's source code, I will try to explain what **I think** is wrong with it.

To understand the shortcomings of `KeyboardEvent.keyCode`, we must first understand what its value means and where it comes from. The only reasonable explanation I could find is that it must be rooted in how Windows does keyboard input.

I've found a good explanation about keyboard input in Windows [here](https://msdn.microsoft.com/en-us/library/windows/desktop/ms646267(v=vs.85).aspx).

> Assigned to each key on a keyboard is a unique value called a scan code, a device-dependent identifier for the key on the keyboard. A keyboard generates two scan codes when the user types a key—one when the user presses the key and another when the user releases the key.

> The keyboard device driver interprets a scan code and translates (maps) it to a virtual-key code, a device-independent value defined by the system that identifies the purpose of a key.

... and a hint to how keyboard layouts work:

> A keyboard layout not only specifies the physical position of the keys on the keyboard but also determines the character values generated by pressing those keys. Each layout identifies the current input language and determines which character values are generated by which keys and key combinations.

**So a keyboard layout on Windows consists of two mappings**. The first one maps scan codes to virtual keys and the second one maps virtual keys and modifiers combinations to generated characters. The list of Virtual Key Codes is defined [here](https://msdn.microsoft.com/en-us/library/windows/desktop/dd375731(v=vs.85).aspx).

Since this is pretty abstract, let's pick an example where we compare the US standard keyboard layout with the GER (Germany) keyboard layout, as it can exemplify both mappings:

| Standard US | GER (Germany) |
|-------------|---------------|
| ![image](https://cloud.githubusercontent.com/assets/5047891/21293882/fba6b994-c52f-11e6-8a69-e8cec9195709.png) | ![image](https://cloud.githubusercontent.com/assets/5047891/21293884/0b3677aa-c530-11e6-87c2-25e5a81ce4f6.png) |

<table>
  <tr>
    <td rowspan="2">Physical Key</td>
    <td rowspan="2">Scan Code</td>
    <td colspan="2">US layout</td>
    <td colspan="2">GER layout</td>
    <td rowspan="2">Notes</td>
  </tr>
  <tr>
    <td>Key&nbsp;Code</td>
    <td>Char</td>
    <td>Key&nbsp;Code</td>
    <td>Char</td>
  </tr>
  <tr>
    <td><kbd>Y</kbd></td>
    <td>21</td>
    <td>89&nbsp;(0x59)</td>
    <td>y</td>
    <td><b>90&nbsp;(0x5A)</b></td>
    <td>z</td>
    <td rowspan="2">The first mapping (scan code -> key code) is changed, and the second mapping (key code -> character) is identical.</td>
  </tr>
  <tr>
    <td><kbd>Z</kbd></td>
    <td>44</td>
    <td>90&nbsp;(0x5A)</td>
    <td>z</td>
    <td><b>89&nbsp;(0x59)</b></td>
    <td>y</td>
  </tr>
  <tr>
    <td><kbd>7</kbd></td>
    <td>8</td>
    <td>55&nbsp;(0x37)</td>
    <td>7</td>
    <td>55&nbsp;(0x37)</td>
    <td>7</td>
    <td rowspan="2">The first mapping (scan code -> key code) is identical, and the second mapping (key code -> character) is changed.</td>
  </tr>
  <tr>
    <td><kbd>Shift</kbd>+<kbd>7</kbd></td>
    <td>8</td>
    <td>55&nbsp;(0x37)</td>
    <td>&amp;</td>
    <td>55&nbsp;(0x37)</b></td>
    <td><b>/</b></td>
  </tr>
</table>

Turns out the indirection through Virtual Key Codes is quite helpful, e.g. one can write an application and simply look for <kbd>Ctrl</kbd>+<kbd>0x5A</kbd> (i.e. <kbd>Ctrl</kbd>+<kbd>Z</kbd>) keydown events and this will work as expected on keyboards where keys are moved around, e.g. QWERTZ or AZERTY keyboards, etc.

By looking for [`KeyboardCodeFromNative`](https://cs.chromium.org/search/?q=KeyboardCodeFromNative&sq=package:chromium&type=cs) in Chromium's sources we can confirm that **under Windows, `KeyboardEvent.keyCode` is simply equal to the Windows Virtual Key Code**:

```C++
KeyboardCode KeyboardCodeFromNative(const base::NativeEvent& native_event) {
  return KeyboardCodeForWindowsKeyCode(static_cast<WORD>(native_event.wParam));
}
// ...
KeyboardCode KeyboardCodeForWindowsKeyCode(WORD keycode) {
  return static_cast<KeyboardCode>(keycode);
}
```

### The problem: Linux and Mac

AFAICT keyboard input and keyboard layouts on Linux and Mac do not work through this double indirection (from scan code to key code, and from key code and modifiers to character), **apparently keyboard input on Linux and Mac goes straight from scan code and modifiers to characters**.

This raises the question, what then is the value of `KeyboardEvent.keyCode` on Linux and Mac?

By looking for the Linux and Mac equivalents of `KeyboardCodeForWindowsKeyCode` (i.e. `KeyboardCodeFromXKeyEvent` and `KeyboardCodeFromNSEvent`) we can conclude that **nobody really knows**.

On Linux:

```c++

// Get an ui::KeyboardCode from an X keyevent
KeyboardCode KeyboardCodeFromXKeyEvent(const XEvent* xev) {
  // Gets correct VKEY code from XEvent is performed as the following steps:
  // 1. Gets the keysym without modifier states.
  // 2. For [a-z] & [0-9] cases, returns the VKEY code accordingly.
  // 3. Find keysym in map0.
  // 4. If not found, fallback to find keysym + hardware_code in map1.
  // 5. If not found, fallback to find keysym + keysym_shift + hardware_code
  //    in map2.
  // 6. If not found, fallback to find keysym + keysym_shift + keysym_altgr +
  //    hardware_code in map3.
  // 7. If not found, fallback to find in KeyboardCodeFromXKeysym(), which
  //    mainly for non-letter keys.
  // 8. If not found, fallback to find with the hardware code in US layout.
  // ...
}

```
On Mac:

```c++

KeyboardCode KeyboardCodeFromNSEvent(NSEvent* event) {
  // ...
  NSString* characters = [event characters];
  if ([characters length] > 0)
    code = KeyboardCodeFromCharCode([characters characterAtIndex:0]);
  // ...
  characters = [event charactersIgnoringModifiers];
  if ([characters length] > 0)
    code = KeyboardCodeFromCharCode([characters characterAtIndex:0]);
  // ...
}

// Translates from character code to keyboard code.
KeyboardCode KeyboardCodeFromCharCode(unichar charCode) {
  switch (charCode) {
    // ...
    // U.S. Specific mappings.  Mileage may vary.
    case ';': case ':': return VKEY_OEM_1;
    case '=': case '+': return VKEY_OEM_PLUS;
    case ',': case '<': return VKEY_OEM_COMMA;
    case '-': case '_': return VKEY_OEM_MINUS;
    case '.': case '>': return VKEY_OEM_PERIOD;
    case '/': case '?': return VKEY_OEM_2;
    case '`': case '~': return VKEY_OEM_3;
    case '[': case '{': return VKEY_OEM_4;
    case '\\': case '|': return VKEY_OEM_5;
    case ']': case '}': return VKEY_OEM_6;
    case '\'': case '"': return VKEY_OEM_7;
  }

  return VKEY_UNKNOWN;
}
```

The way `KeyboardEvent.keyCode` is computed leads to some weird situations, such as the one documented in issue #1302:

> Given the German (Swiss) keyboard layout, ... it is very difficult to figure out what actual physical key was pressed. E.g.:
> - when pressing <kbd>7</kbd>, the `keydown` event we receive has `keyCode:55`
> - this is OK
> - when pressing <kbd>Shift</kbd>+<kbd>7</kbd>, the `keydown` we receive has `shiftKey:true` and `keyCode: 191`
> - this is unexpected, we should receive `shiftKey:true` and `keyCode:55`

Here are the values observed in `KeyboardEvent`:

<table>
  <tr>
    <td>Physical Key</td>
    <td>US layout Win</td>
    <td>US layout Mac</td>
    <td>GER layout Win</td>
    <td>GER layout Mac</td>
  </tr>
  <tr>
    <td><kbd>Y</kbd></td>
    <td><pre>shift: false<br/>keyCode: 89</pre></td>
    <td><pre>shift: false<br/>keyCode: 89</pre></td>
    <td><pre>shift: false<br/>keyCode: 90</pre></td>
    <td><pre>shift: false<br/>keyCode: 90</pre></td>
  </tr>
  <tr>
    <td><kbd>Z</kbd></td>
    <td><pre>shift: false<br/>keyCode: 90</pre></td>
    <td><pre>shift: false<br/>keyCode: 90</pre></td>
    <td><pre>shift: false<br/>keyCode: 89</pre></td>
    <td><pre>shift: false<br/>keyCode: 89</pre></td>
  </tr>
  <tr>
    <td><kbd>7</kbd></td>
    <td><pre>shift: false<br/>keyCode: 55</pre></td>
    <td><pre>shift: false<br/>keyCode: 55</pre></td>
    <td><pre>shift: false<br/>keyCode: 55</pre></td>
    <td><pre>shift: false<br/>keyCode: 55</pre></td>
  </tr>
  <tr>
    <td><kbd>Shift</kbd>+<kbd>7</kbd></td>
    <td><pre>shift: true<br/>keyCode: 55</pre></td>
    <td><pre>shift: true<br/>keyCode: 55</pre></td>
    <td><pre>shift: true<br/>keyCode: 55</pre></td>
    <td><pre>shift: true<br/>keyCode: <b>191</b></pre></td>
  </tr>
</table>

This is probably the case from above where "mileage may vary". We have tried to workaround this on our side, but the workaround is limited and only functions for a subset of these key codes (i.e. does not work, perhaps it is even making things worse for DVORAK).

Issues that possibly all share the same root cause (the fuzzyness of `keyCode` on Linux and Mac and/or our workaround not working or making things worse):
* #1492
* #4712
* #4619
* #15624
* #13417
* #6020
* #17106
* #17023
* #16157
* #15887
* #15711
* #14984
* #4084

## The path forward

We can now use `KeyboardEvent.code` and `KeyboardEvent.key` (see the current spec [here](https://www.w3.org/TR/uievents/#interface-keyboardevent)). The simplified explanation is that `KeyboardEvent.code` is a string representation of the scan code, and `KeyboardEvent.key` is the produced character (skipping entirely the Virtual Keys hop on Windows). This has a chance to work correctly because all Operating Systems have these concepts.

<table>
  <tr>
    <td>Physical Key</td>
    <td>US layout Win</td>
    <td>US layout Mac</td>
    <td>GER layout Win</td>
    <td>GER layout Mac</td>
  </tr>
  <tr>
    <td><kbd>Y</kbd></td>
    <td><pre>shift: false<br/>code: "KeyY"<br/>key: "y"</pre></td>
    <td><pre>shift: false<br/>code: "KeyY"<br/>key: "y"</pre></td>
    <td><pre>shift: false<br/>code: "KeyY"<br/>key: "z"</pre></td>
    <td><pre>shift: false<br/>code: "KeyY"<br/>key: "z"</pre></td>
  </tr>
  <tr>
    <td><kbd>Z</kbd></td>
    <td><pre>shift: false<br/>code: "KeyZ"<br/>key: "z"</pre></td>
    <td><pre>shift: false<br/>code: "KeyZ"<br/>key: "z"</pre></td>
    <td><pre>shift: false<br/>code: "KeyZ"<br/>key: "y"</pre></td>
    <td><pre>shift: false<br/>code: "KeyZ"<br/>key: "y"</pre></td>
  </tr>
  <tr>
    <td><kbd>7</kbd></td>
    <td><pre>shift: false<br/>code: "Digit7"<br/>key: "7"</pre></td>
    <td><pre>shift: false<br/>code: "Digit7"<br/>key: "7"</pre></td>
    <td><pre>shift: false<br/>code: "Digit7"<br/>key: "7"</pre></td>
    <td><pre>shift: false<br/>code: "Digit7"<br/>key: "7"</pre></td>
  </tr>
  <tr>
    <td><kbd>Shift</kbd>+<kbd>7</kbd></td>
    <td><pre>shift: true<br/>code: "Digit7"<br/>key: "&amp;"</pre></td>
    <td><pre>shift: true<br/>code: "Digit7"<br/>key: "&amp;"</pre></td>
    <td><pre>shift: true<br/>code: "Digit7"<br/>key: "/"</pre></td>
    <td><pre>shift: true<br/>code: "Digit7"<br/>key: "/"</pre></td>
  </tr>
</table>

**Comment by alexandrudima** [comment]
We have discussed this in detail in our today's daily standup and we are in agreement to go forward with Option 2).

**Comment by ottonascarella** [comment]
using visual code with a japanese layout has been madness for me.
i would LOVE to see that change, thanks!

**Comment by Gozala** [comment]
Any chance a setting to use new keybinding dispatch could be either released as an add-on or a setting until the support for multiple shortcut syntax can be implemented and shipped. With non US layout on non-windows editor just behaves extremely odd. For example on dvorak `cmd+,` closes the the editor instead of opening preferences.

**Comment by Kobold** [comment]
Dvorak on mac is rough, I edited the raw js to disable the custom mac keycode handler. Cheering y'all on to get this resolved!
