### ISSUE TITLE
Add hover pop-up for remote connections

### ISSUE THREAD

**Issue by donchuru** [microsoft/vscode#175205]
I noticed that the Hover feature(the bubble that shows the documentation of the object hovered on) does not work when using remote connections. It would be nice to have the bubble pop up when remoting to another machine. 

This post on Stack shows how it currently works: https://stackoverflow.com/questions/70277022/vs-code-hover-does-not-show-on-remote-connections

**Comment by roblourens** [comment]
It is supported - if you aren't seeing it, there might be an extension that you need to install onto the remote machine, like the python extension for example
