### ISSUE TITLE
warn when (Ctrl+C) in file (after select text in terminal)

### ISSUE THREAD

**Issue by alarcl** [Microsoft/vscode#17523]
- VSCode Version: Code 1.8.0 (38746938a4ab94f2f57d9e1309c51fd6fb37553d, 2016-12-13T17:45:32.595Z)
- OS Version: Windows_NT ia32 6.3.9600
- Extensions:

|Extension|Author|Version|
|---|---|---|
|theme-karyfoundation-themes|karyfoundation|10.1.0|
|Go|lukehoban|0.6.51|
|vscode-terminal-here|Tyriar|0.0.5|
|language-1c-bsl|xDrivenDevelopment|1.8.6|

---

Steps to Reproduce:

1. Open terminal (Ctrl+`)
2. Select some text in terminal (don't do Ctrl+C)
3. Return to file (terminal lose focus)
4. Select some text in file
4. Ctrl+C

get:
"WARN cannot copy terminal selection when terminal does not have focus"

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/17232
