### ISSUE TITLE
File type gets changed for untitled files once you start typing 

### ISSUE THREAD

**Issue by luabud** [microsoft/vscode#175279]
Type: <b>Bug</b>

1. Create a new file with File > New File...
1. Click on "select a language" and select something (e.g. C, Java, Python, etc)
1. Type something: e.g. for Python you can write `print("Hello")`
1. Save the file
1. Notice file type changed to Text File. 

If you don't type anything (i.e. skip the 3rd step), the file type is preserved. It only changes if you start typing something  

VS Code version: Code 1.75.1 (441438abd1ac652551dbe4d408dfcec8a499b8bf, 2023-02-08T21:32:34.589Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz (8 x 2995)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.71GB (12.91GB free)|
|Process Argv|--crash-reporter-id 0bfbbb7e-a06e-4093-9e04-3516e97ba07f|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (21)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-pytest|Cam|0.1.1
vscode-eslint|dba|2.4.0
python-environment-manager|don|1.0.4
prettier-vscode|esb|9.10.4
azure-dev|ms-|0.3.0
isort|ms-|2022.8.0
python|ms-|2023.2.0
vscode-pylance|ms-|2023.2.40
jupyter|ms-|2023.1.2010391206
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.14
vscode-jupyter-cell-tags|ms-|0.1.6
vscode-jupyter-slideshow|ms-|0.1.5
remote-containers|ms-|0.275.1
remote-ssh|ms-|0.96.0
remote-ssh-edit|ms-|0.84.0
remote-wsl|ms-|0.75.3
azure-account|ms-|0.11.3
cpptools|ms-|1.14.3
powershell|ms-|2023.1.0
remote-explorer|ms-|0.2.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
azure-dev_surveyone:30548225
pyindex848:30662994
nodejswelcome1cf:30587006
3biah626:30602489
pyind779:30671433
f6dab269:30613381
pythonsymbol12:30671437
2i9eh265:30646982
vsctsb:30662444

```

</details>

**Comment by TylerLeonhardt** [comment]
@luabud does the language get set to, literally, "Text File"? Or does it change to "Plain Text"?

**Comment by TylerLeonhardt** [comment]
When you save the file, do you get the `.py` file extension?:


![Image](https://user-images.githubusercontent.com/2644648/222785271-ea20c7ca-b975-496d-8c6d-825dbe4cc46c.png)

**Comment by luabud** [comment]
The suggested file extension was set to text file despite the language in VS Code being set to Python, if that makes sense. However, I can no longer reproduce this in 1.76. @cwebster-99 -- can you confirm if this is no longer happening on your machine as well?

**Comment by cwebster-99** [comment]
It is no longer reproduced on my machine (1.76) either

**Comment by TylerLeonhardt** [comment]
okay! I'll close this then!
