### ISSUE TITLE
Improve network requests logging

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#175258]
Currently we are logging network requests with basic information. Given that shared process is being made utility process, we will loose the ability to see network requests by opening the shared process window in network tab or console tab. To compensate this, we shall improve our network requests logging to make it as similar to dev tools. 

Also lets log all network requests from all processes (renderer/window/shared) in to a separate and single requests log file.

**Comment by IllusionMH** [comment]
Duplicate? #175258 has same labels, assignment, and milestone.

**Comment by bpasero** [comment]
I was not able to get a HTTP status code from a failing request when `net.Request` is used in Electron. @deepak1556 can maybe advise.

**Comment by deepak1556** [comment]
DIscussed offline, it was a case where there was not HTTP connection got established but rather request failed client side checks and got aborted.

**Comment by bpasero** [comment]
👍 , logging the status code now in https://github.com/microsoft/vscode/pull/175325/files#diff-26f940932d2ed8106ecf175750560c8e4790293d95320921f7fd8b2a9bcddfa0R111
