### ISSUE TITLE
Hot Exit: Remember File Language mode

### ISSUE THREAD

**Issue by sidewinder94** [Microsoft/vscode#17520]
- VSCode Version: 1.8.0
- OS Version: Windows Server 2012 R2

Steps to Reproduce:

1. Open VS Code
2. Create a new file (don't save)
3. Change language mode (i.e. to SQL)
4. Type some text
5. Exit
6. Launch VS Code Again

The language mode selected before closing is lost.

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/16803
