### ISSUE TITLE
Ability to artificially collapse project root files in File Explorer

### ISSUE THREAD

**Issue by NazCodeland** [microsoft/vscode#175398]
It would be nice if we had the ability to collapse all config files in root of the File Explorer. From what I understand, it's either 
not easy or not possible to move all config files in the root of your project into a config folder. Just like how we have 

```<!-- #region -->```
```<!-- #endregion -->```

for collapsing code within the editor. If we could have something similar that 'artificially' collapses all the files in the root of the project in the File Explorer without actually changing the physical lookup resolution of the files. That would be nice.

**Comment by lramos15** [comment]
I think https://code.visualstudio.com/updates/v1_67#_explorer-file-nesting should make this possible for your use case to at least make all the config files appear as one. Try it out!
