### ISSUE TITLE
"Collapse Folders In Explorer" button in explorer pane missing & no settings option to enable

### ISSUE THREAD

**Issue by joseph-skupniewicz-sp** [microsoft/vscode#175302]
There used to be a button immediately visible in the Explorer pane, but now you must click the ellipses > "Collapse Folders In Explorer".

<img width="312" alt="image" src="https://user-images.githubusercontent.com/97310001/221096549-41d4c4d0-e6a8-4791-b64c-e11f49884884.png">

I haven't been able to find any Settings option to re-enable this feature.

**Comment by joseph-skupniewicz-sp** [comment]
This was implemented back in https://github.com/microsoft/vscode/issues/34972

**Comment by gjsjohnmurray** [comment]
I think you hid it. Please try right-clicking on the `...` and setting a checkmark on the option.

**Comment by joseph-skupniewicz-sp** [comment]
doh....that worked! Thanks!
