### ISSUE TITLE
Profile Badge background color issue

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode#175359]
Version: 1.76.0-insider
Commit: 720985f2c68cadb5e375d9ec671476c548f61769
Date: 2023-02-24T06:17:56.357Z
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 12_6_3) AppleWebKit/537.36 (KHTML, like Gecko) Code-Insiders/1.76.0-insider Chrome/102.0.5005.196 Electron/19.1.10 Safari/537.36

Since merging of https://github.com/microsoft/vscode/pull/174961 my profile badge looks like 
<img width="109" alt="image" src="https://user-images.githubusercontent.com/4674940/221236069-fd01efec-6829-45bd-b76a-7d0e1e12de43.png">

It seems a new theme setting was introduced, but I get this in the settings editor when trying to define it:

<img width="616" alt="image" src="https://user-images.githubusercontent.com/4674940/221235831-916bbef3-13a0-4f8e-9586-3f983e3d0e6e.png">

**Comment by daviddossett** [comment]
Interesting, I'm able to customize this in my settings.json for both default and new profiles. Does this only repro when overriding for a specific theme? 

<img width="586" alt="CleanShot 2023-02-24 at 09 16 29@2x" src="https://user-images.githubusercontent.com/25163139/221244747-16e233a7-7a0d-4a10-98d1-106a453c9a28.png">

cc @aeschli in case this is a familiar problem.

**Comment by daviddossett** [comment]
Oh, I see the difference now. `profile.badgeBackground` vs. `profileBadge.background`.

**Comment by kieferrm** [comment]
That worked. Thank you!
