### ISSUE TITLE
Polyglot Notebooks: keyboard shortcuts prevent using  HTML input fields in cell outputs 

### ISSUE THREAD

**Issue by PawelStadnicki** [microsoft/vscode#175387]
I can not use input fields in HTML being displayed as a notebook cell output (red rectangles below).
For these input fields, notebook keyboard shortcuts are applied when I try to type a text.
As a result, many letters are not taken into account or even break the whole cell (M will change it to markdown, and X will cut off).

It looks like `!inputFocus` _when clause_ that should prevent such keyboard shortcuts is targeted only for cell input but not for cell output.
I think a new clause should be introduced that makes HTML input fields be usable in notebook cell outputs.

![image](https://user-images.githubusercontent.com/56049414/221302576-396fddc2-c422-4890-8449-36b3d6b39cda.png)

![image](https://user-images.githubusercontent.com/56049414/221303516-ff39c493-0c7a-4884-904c-5e2e194d8d4c.png)

**Comment by rebornix** [comment]
@PawelStadnicki the latest Jupyter Keymap extension 1.1.0 should have it fixed, you can type A inside the output without triggering cell insertion.
