### ISSUE TITLE
markdown preview: trouble with <details> blocks 

### ISSUE THREAD

**Issue by sethp** [microsoft/vscode#175353]
Type: <b>Bug</b>

When editing a document with `<details>` blocks, I observe ~two~three issues (third in a comment below):

1. every refresh, the details blocks are closed (they lose their `open` attribute). I think I would find it more helpful if they retained their open/closed state between refreshes
2. the synchronized scrolling between the editor and the preview is a little off. I can fully expand my (so far, two) `<details>` blocks and the scrolling seems to be in sync again, so I suspect the sync operates as if the details blocks are always fully expanded, when they are not. Unfortunately, due to the first problem, this isn't really tenable and so I've had to disable the sync for now.

For the second, I suspect the trouble is in `getCodeLineElements`: https://github.com/microsoft/vscode/blob/5b79b91838e7f7cd7b1fef48e2c6934027198a52/extensions/markdown-language-features/preview-src/scroll-sync.ts#L24-L39

`codeLineClass` here appears to be `'code-line'`, which I think will grab the contents of a closed `<details>`, as the DOM looks like this (note the difference between the two `<details>` blocks, the one with the `open` attribute is expanded):

![image](https://user-images.githubusercontent.com/241129/221232002-794b0098-0616-4b7d-a031-2245e4c12148.png)

And there doesn't appear to be any filtering to exclude elements that aren't visible (e.g. the parent is a `<details>` missing an `open`, as in my case).

Sorry if this should be two issues, they seemed related enough to at least start here.

Example document:

```markdown
# document

some introductory text that gives the rough outline of what the thing should do

<details>
<summary>my very long aside, including a code block that spans a dozen lines or so, on how the thing actually works</summary>

<pre>
line 1
line 2
line 3
line 4
line 5
line 6
line 7
line 8
line 9
line 10
</pre>

</details>

Some more text that follows the aside.
```

VS Code version: Code - OSS 1.75.1 (441438abd1ac652551dbe4d408dfcec8a499b8bf, 2023-02-09T20:16:38.064Z)
OS version: Linux x64 5.15.94-1-MANJARO
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 3700X 8-Core Processor (16 x 2200)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|1, 1, 1|
|Memory (System)|62.74GB (47.06GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|plasma|
|XDG_CURRENT_DESKTOP|KDE|
|XDG_SESSION_DESKTOP|KDE|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (37)</summary>

Extension|Author (truncated)|Version
---|---|---
troff|ban|1.0.24
calva|bet|2.0.334
vscode-postgres|cko|1.4.0
vscode-eslint|dba|2.4.0
EditorConfig|Edi|0.16.4
prettier-vscode|esb|9.10.4
go|gol|0.37.1
test-adapter-converter|hbe|0.1.2
vscode-test-explorer|hbe|2.21.1
jsonnet|hep|0.1.0
jq-syntax-highlighting|jq-|0.0.2
vscode-jest-test-adapter|kav|0.8.1
vscode-clangd|llv|0.1.23
shfmt|mkh|1.2.0
vscode-docker|ms-|1.24.0
vscode-kubernetes-tools|ms-|1.3.11
isort|ms-|2022.8.0
python|ms-|2023.2.0
vscode-pylance|ms-|2023.2.40
remote-containers|ms-|0.275.1
cmake-tools|ms-|1.13.45
cpptools|ms-|1.14.3
cpptools-extension-pack|ms-|1.3.0
test-adapter-converter|ms-|0.1.6
vscode-selfhost-test-provider|ms-|0.3.13
vsliveshare|ms-|1.0.5832
vsliveshare-audio|ms-|0.1.93
vsliveshare-pack|ms-|0.4.0
vscode-commons|red|0.0.6
vscode-yaml|red|1.11.0
rust-analyzer|rus|0.3.1410
shopify-liquid|sis|3.2.2
even-better-toml|tam|0.19.0
tilt|Tch|1.0.9
shellcheck|tim|0.29.4
cmake|twx|0.0.17
vscode-proto3|zxh|0.5.5

(1 theme extensions excluded)

</details>

**Comment by sethp** [comment]
Nevermind all of this if it's barking up the wrong tree, these are at least half notes for myself if I get the time to come back around and revisit this some day.

I took a look around the [preview tree ](https://github.com/microsoft/vscode/tree/59f6d520621048779f0c94c6066edb7c57a8f369/extensions/markdown-language-features/src/preview) to see if I could find any examples of preserving DOM state across multiple renders, and the `MarkdownPreview` class has a [`getState`](https://github.com/microsoft/vscode/blob/59f6d520621048779f0c94c6066edb7c57a8f369/extensions/markdown-language-features/src/preview/preview.ts#L219) that seems promising, but I'm left with at least these questions:

1. How to register e.g. an "onDocumentChange" listener to notice when `<details>` elements gain & lose an `open` attribute so as to, say, store a list of the (persistent) attributes on a `MarkdownPreview` object, since there seems to be ~one of those per DOM element?
2. How to feed that back in to the rendering process; I suspect the `code-line` handling will offer some pointers here, since I suspect the preview state is driving that. Still, there's at least three contexts that it seems like state management/rendering is happening in:
    1. "incremental" re-render once everything's open and typing is ongoing
    2. "full" re-renders (on document open?)
    3. whatever happens when code is reloaded / closed and re-launched; things like scroll position seem to be stored across those edges, is there a particular way to store state that the `<details>` blocks so their open-ness gets persisted across re-launches? It's not the end of the world if closing and re-opening the editor also collapses the `<details>` blocks, but there seems to be some facility there that might be easy to use.

**Comment by sethp** [comment]
One more thing I've run into so far: the code folding for `<details>` blocks doesn't seem to work across multiple lines:

![a details block with a summary, a new line, the text 'some words', a new line, and the end of the block](https://user-images.githubusercontent.com/241129/221633312-3be796d9-5238-48b2-be24-b7882f14ba75.png)

gets folded to

![a screenshot showing just the details tag and summary collapsed, leaving the newlines/"some words"/end tag visible](https://user-images.githubusercontent.com/241129/221633368-85903008-f13e-4c68-8980-ac0a9e0de0cc.png)

What I expected was more like what happens with all of the text glommed together:

![the details block with no newlines spacing out the summary/text/end tag](https://user-images.githubusercontent.com/241129/221633621-0e3d1f78-08dc-44f4-91c3-35d796c6d6ef.png)

folds to

![a details tag followed by an ellipsis that covers everything through the closing tag](https://user-images.githubusercontent.com/241129/221633778-6e85efb8-6cb2-4f15-b46b-a1f8297182d5.png)

**Comment by mjbvz** [comment]
Extracted folding issue to: https://github.com/microsoft/vscode-markdown-languageservice/issues/119

**Comment by sethp** [comment]
Thanks @mjbvz for the quick turnaround on preserving the open attribute!  I'm still a little curious about the scrolling sync: I don't see anything in #176330 that looks like it would address the issue I'm seeing "scrolling past" a collapsed `<details>` block where the code cursor makes the preview act as if it's much further down, seemingly by about as much as the length of the expanded `<details>`. 

I can now leave my `<details>` expanded to re-enable sync'd scrolling, but I was wondering if the intent was to not change the behavior when they're closed? Or, would it be helpful if I broke that part out into a new issue?

**Comment by sethp** [comment]
Also, I should mention: I think I've got a pretty solid guess on how to skip the collapsed blocks (described in the original issue). I'm happy to take on giving that a try and getting it into a PR-able shape if it works, but I strongly suspect you'll beat me to the finish line if we end up racing each other :)
