### ISSUE TITLE
.NET MAUI iOS can't debug or publish arm-64 without iossimulator-x64

### ISSUE THREAD

**Issue by rolfbjarne** [microsoft/vscode#175317]
_From @rstolpe on Wed, 28 Dec 2022 21:21:07 GMT_

### Description

you can't debug or publish iOS-arm-64 without the folder iossimulator-x64.

![image](https://user-images.githubusercontent.com/76907327/209873341-a3f9d49f-55f8-4a2a-ba70-ec04591a004d.png)

### Steps to Reproduce

1. delete all the folders inside the Debug folder both the one that are located in obj and bin.
2. In the .csproj file add the following as debug and release, make sure that you delete the other enteries.
````
	<PropertyGroup Condition="$(TargetFramework.Contains('-ios')) and '$(Configuration)' == 'debug'">
		<RuntimeIdentifier>ios-arm64</RuntimeIdentifier>
		<CodesignEntitlement>Entitlements.plist</CodesignEntitlement>
		<ArchiveOnBuild>true</ArchiveOnBuild>
		<BuildIpa>true</BuildIpa>
		<IpaPackageName>Mvi</IpaPackageName>
	</PropertyGroup>
	<PropertyGroup Condition="$(TargetFramework.Contains('-ios')) and '$(Configuration)' == 'Release'">
		<RuntimeIdentifier>ios-arm64</RuntimeIdentifier>
		<CodesignEntitlement>Entitlements.plist</CodesignEntitlement>
		<ArchiveOnBuild>true</ArchiveOnBuild>
		<BuildIpa>true</BuildIpa>
		<IpaPackageName>Mvi</IpaPackageName>
	</PropertyGroup>
````
3. Now try to debug or build you will get an error that it's not possible.

### Link to public reproduction project repository

don't have

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 16

### Did you find any workaround?

Yes,
1. Run the debug or build without the `<RuntimeIdentifier>ios-arm64</RuntimeIdentifier>` line.
2. Now add `<RuntimeIdentifier>ios-arm64</RuntimeIdentifier>` back and then run the build or debug again and now it will work.

> VS bug [#1748626](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1748626)

_Copied from original issue dotnet/maui#12323_

**Comment by rolfbjarne** [comment]
_From @KSemenenko on Fri, 30 Dec 2022 21:30:48 GMT_

Yah this is annoying one

**Comment by rolfbjarne** [comment]
_From @rstolpe on Sat, 31 Dec 2022 08:27:26 GMT_

It's the same for Mac Catalyst

**Comment by rolfbjarne** [comment]
_From @mattleibow on Fri, 06 Jan 2023 15:28:43 GMT_

@rolfbjarne thoughts?

**Comment by rolfbjarne** [comment]
_From @msftbot[bot] on Fri, 06 Jan 2023 15:28:58 GMT_

Hi @rstolpe. We have added the "s/needs-repro" label to this issue, which indicates that we require steps and sample code to reproduce the issue before we can take further action. Please try to create a minimal sample project/solution or code samples which reproduce the issue, ideally as a GitHub repo that we can clone. See more details about creating repros here: https://github.com/dotnet/maui/blob/main/.github/repro.md

This issue will be closed automatically in 7 days if we do not hear back from you by then - please feel free to re-open it if you come back to this issue after that time.

**Comment by rolfbjarne** [comment]
_From @rstolpe on Fri, 06 Jan 2023 16:11:48 GMT_

Why? You have everything above. No need for any code Mr. boot :)

**Comment by rolfbjarne** [comment]
_From @rstolpe on Sat, 07 Jan 2023 19:28:21 GMT_

> Hi @rstolpe. We have added the "s/needs-repro" label to this issue, which indicates that we require steps and sample code to reproduce the issue before we can take further action. Please try to create a minimal sample project/solution or code samples which reproduce the issue, ideally as a GitHub repo that we can clone. See more details about creating repros here: https://github.com/dotnet/maui/blob/main/.github/repro.md
> 
> This issue will be closed automatically in 7 days if we do not hear back from you by then - please feel free to re-open it if you come back to this issue after that time.

You have everything you need above

**Comment by rolfbjarne** [comment]
_From @rolfbjarne on Mon, 09 Jan 2023 09:09:30 GMT_

> 1. Run

How? Are you using VS for Mac? VS for Windows? Command line? VSCode?

**Comment by rolfbjarne** [comment]
_From @rstolpe on Mon, 09 Jan 2023 10:22:48 GMT_

> > 1. Run
> 
> How? Are you using VS for Mac? VS for Windows? Command line? VSCode?

In this I was using vscode on MacOS

**Comment by rolfbjarne** [comment]
_From @rolfbjarne on Mon, 09 Jan 2023 11:53:46 GMT_

This is an issue in VSCode then (or an extension) - @mattleibow do you know where this should go?

**Comment by rolfbjarne** [comment]
_From @mattleibow on Thu, 12 Jan 2023 19:39:53 GMT_

Before we move the issue to VSCode, @rstolpe can you run this app using the command line?

@rolfbjarne  what would be the commands to use in order to determine if the launch is failing because the build did not happen properly for some reason?

**Comment by rolfbjarne** [comment]
_From @rstolpe on Thu, 12 Jan 2023 20:16:30 GMT_

@mattleibow  I can try that tomorrow.

**Comment by rolfbjarne** [comment]
_From @rolfbjarne on Fri, 13 Jan 2023 11:05:48 GMT_

> @rolfbjarne what would be the commands to use in order to determine if the launch is failing because the build did not happen properly for some reason?

I'm not sure I understand, if the app wasn't built properly, there should have been a build error. The only real way to ensure a build happened properly (if there were no build errors), is to run the actual app to see if it works.

**Comment by rolfbjarne** [comment]
_From @rstolpe on Fri, 13 Jan 2023 19:32:11 GMT_

> Before we move the issue to VSCode, @rstolpe can you run this app using the command line?
> 
> 
> 
> @rolfbjarne  what would be the commands to use in order to determine if the launch is failing because the build did not happen properly for some reason?

Everything work from terminal.
Vs2022 for Mac are throwing many false positiv errors. Can I report them somewhere?

**Comment by rolfbjarne** [comment]
_From @rolfbjarne on Fri, 13 Jan 2023 20:54:22 GMT_

> Vs2022 for Mac are throwing many false positiv errors. Can I report them somewhere?

Yes: menu "Help" -> "Report a Problem"

**Comment by rolfbjarne** [comment]
_From @msftbot[bot] on Thu, 16 Feb 2023 19:26:48 GMT_

Thanks for the issue report @rstolpe! This issue appears to be a problem with Visual Studio, so we ask that you use the VS feedback tool to report the issue. That way it will get to the routed to the team that owns this experience in VS.

If you encounter a problem with Visual Studio, we want to know about it so that we can diagnose and fix it. By using the Report a Problem tool, you can collect detailed information about the problem, and send it to Microsoft with just a few button clicks.

1. Go to the [Visual Studio for Windows feedback tool](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio?view=vs-2022) or [Visual Studio for Mac feedback tool](https://learn.microsoft.com/en-us/visualstudio/mac/report-a-problem?view=vsmac-2022) to report the issue
2. Close this bug, and consider adding a link to the VS Feedback issue so that others can follow its activity there.

**Comment by rolfbjarne** [comment]
_From @rolfbjarne on Fri, 24 Feb 2023 10:23:48 GMT_

This seems like an issue in VSCode, so I'm moving the issue [there](https://github.com/microsoft/vscode).

**Comment by roblourens** [comment]
Sorry, the error message is showing an error thrown from dotnet or a dotnet extension, can you tell me how this is a VS Code issue?

**Comment by rolfbjarne** [comment]
@akoeplinger would you happen to know if this should be in https://github.com/microsoft/vscode-mono-debug instead? (or if there's a better place for it)

**Comment by akoeplinger** [comment]
Debugging .NET MAUI apps in VSCode is not yet officially supported so there's not really any better place for this.

**Comment by akoeplinger** [comment]
Yeah I think you can close it.
