### ISSUE TITLE
red color in the find widget is not going with the design

### ISSUE THREAD

**Issue by abhijit-chikane** [microsoft/vscode#175316]
- VS Code Version: 1.75.1
- OS Version: Windows 11

![image](https://user-images.githubusercontent.com/50770619/221150530-c004b62b-62c5-45ca-b7bf-989e44647dd5.png)
this is red color is not going with the design.

**Comment by daviddossett** [comment]
I think the color is intended to draw attention to the fact that there are no results. What would you expect to see here?

**Comment by connor4312** [comment]
This was tweaked slightly to align with contrast minimums
