### ISSUE TITLE
After importing a profile a Login view gets shown in the explorer

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#175354]
1. https://insiders.vscode.dev/profile/github/9d9d96cebfb64cb3fe456bf26828aa8a
2. Import that profile to local VS Code Insiders
3. The Login view gets shown in the explorer

I have no clue what this view is. But on reload it goes away.
I can repro all the time

![Screenshot 2023-02-24 at 17 12 22](https://user-images.githubusercontent.com/1926584/221229902-c46805e1-98c1-40a5-9440-575ec6813fc1.png)

**Comment by sandy081** [comment]
Strange, I cannot reproduce it. You can repro it consistently?

**Comment by isidorn** [comment]
No, I can no longer repro. But I think that LOGIN view was coming from GH PR extension wanting to login. In the default profile I have moved that view in the explorer. But the issue here is that view becomes visible, and the profile I am applying does not have the GH PR profiles. 
Might it be somehow connected that view is coming from the built-in GH auth extension, and somehow new Profile reset the view sizes to the default and visibility to true. But did not reset the location of the view (so it is in the GH PR viewlet)?

**Comment by sandy081** [comment]
I see that view is coming from GHPRI extension. I tried to repro it by moving the login view to explorer and import the profile. But the attempt is unsuccessful. I see from the screenshot that this can happen but trying to repro when and how it can happen so that we can find the root cause. It would be great if you can get it repro.

**Comment by isidorn** [comment]
What I can reproduce is the following:
1. Default profile, Hide the GitHub Login view
2. Import that profile (it does not have any GitHub extension)
3. The Login view is visible 🐛

**Comment by sandy081** [comment]
@isidorn Can you please check if you are still able to reproduce this?
