### ISSUE TITLE
[Request] Possibility to mix light and dark theme

### ISSUE THREAD

**Issue by Yayuro** [microsoft/vscode#17533]
It would be nice if we can combine light and dark theme together.
For example light for file explorer and dark for code.
I think you cannot do that properly right now.

IMO both feels more separated.
It's just a thought.

![vscode_mixed-theme](https://cloud.githubusercontent.com/assets/9949969/21314525/7efe4ad6-c5ef-11e6-99e1-2d219eafd10e.png)

**Comment by egamma** [comment]
This will be possible once we add more support to theme the workbench and you can also define the background color of the sidebar.

**Comment by eduardonunesp** [comment]
Is there any idea when the broad support for theme will be added ? is there any milestone, I'm curious about it.

**Comment by bpasero** [comment]
We do support a lot of colors now in our theming story, however I see two missing things:
* we have no support to set the foreground color individually per component, only across the workbench
* our icons are not scoped to the background color per component but only globally (either dark or light theme)
