### ISSUE TITLE
Preferences: cannot find "cssempty" or "css empty"

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#17536]
Steps to Reproduce:

1. follow the smoke test and try to find the setting `"css.lint.emptyRules"`
2. neither typing "cssempty" nor "css empty" finds it :(

**Comment by sandy081** [comment]
It's unfortunate that this was not shown. Setting (Description, key, value) does not contain `css` and `empty` together. Currently search is fuzzy only on description and normal on keys and values. I have a plan to improve search and efficient this milestone.  This is one case where I should do split word search in complete setting.

**Comment by bpasero** [comment]
I would say this is a very common thing our fuzzy search should support.
