### ISSUE TITLE
Terminal: sometimes the top of the terminal is cropped

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#17538]
I am sometimes seeing the prompt being scrolled to the top. I just saw this on Linux but also seen this on macOS:

![image](https://cloud.githubusercontent.com/assets/900690/21315047/8d0c0400-c5fa-11e6-93d9-992fe82b235d.png)

**Comment by thekalinga** [comment]
I have faced this issue with default settings in my Ubuntu 14.04 aswell

**Comment by bpasero** [comment]
Btw I am using VS Code with a zoom level of 1, not sure if that is related.

**Comment by Tyriar** [comment]
Yes it's to do with zoom, duplicate of https://github.com/Microsoft/vscode/issues/14479
