### ISSUE TITLE
Javascript type inference problem for classes if constructor argument number doesn't match

### ISSUE THREAD

**Issue by chanep** [Microsoft/vscode#17539]
- VSCode Version: 1.8.0
- OS Version: Any

VScode doesn't detect correctly instance type if class constructor is called with different number of arguments. 

Example:

```js
class Person{
    constructor(arg){
        this.arg = arg;
    }
}

let p1 = new Person(null);      //OK, p1 is type Person
let p2 = new Person();           //WRONG, p2 is type "any"
```

I think it is a little annoying to have to put null's all over the place

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript#13032

**Comment by mjbvz** [comment]
I've moved this to the TypeScript repo as it appears to be a problem on their side. Until this is fixed, you can workaround this by explicitly calling out that `arg` is optional:

```js
class Person{
    constructor(arg = null) {
        this.arg = arg;
    }
}
```

**Comment by chanep** [comment]
Thanks, Yes, I thought on optional argument but I'm using nodeJs 4.5 which doesn't have that ES6 feature
