### ISSUE TITLE
ending TCPSVR *SSHD and starting *sshd in debug 

### ISSUE THREAD

**Issue by Drp2thehill** [microsoft/vscode#175375]
Type: <b>Bug</b>

When TCPSVR *SSHD is started normally, my Code for IBM i does not connect. When I ENDTCPSVR *SSHD, and start *SSHD in debug mode "QSH CMD('/QOpenSys/usr/sbin/sshd -d -d -d')" it works! what the heck is going on? As soon as I end the *SSHD debug session, CODE for IBM i loses connection. Please help!

VS Code version: Code 1.75.1 (441438abd1ac652551dbe4d408dfcec8a499b8bf, 2023-02-08T21:32:34.589Z)
OS version: Windows_NT x64 10.0.19045
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2208)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.86GB (7.96GB free)|
|Process Argv|--crash-reporter-id 3985ea38-0811-485d-b43e-c98932e770ee|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (23)</summary>

Extension|Author (truncated)|Version
---|---|---
ibmi-languages|bar|0.6.10
vscode-rpgfree|Bri|0.0.25
vscode-firefox-debug|fir|2.9.8
code-coverage-ibmi|hal|0.1.7
code-for-ibmi|hal|1.7.4
ibm-i-development-pack|hal|0.1.0
vscode-db2i|hal|0.2.9
vscode-displayfile|hal|0.0.10
vscode-ibmi-walkthroughs|hal|0.3.1
vscode-rpgle|hal|0.17.6
ibmidebug|IBM|1.0.0
vscode-clle|IBM|1.1.0
notepadplusplus-keybindings|ms-|1.0.7
java|red|1.15.0
errorlens|use|3.7.0
intellicode-api-usage-examples|Vis|0.2.7
vscodeintellicode|Vis|1.2.30
vscode-java-debug|vsc|0.48.0
vscode-java-dependency|vsc|0.21.1
vscode-java-pack|vsc|0.25.7
vscode-java-test|vsc|0.37.1
vscode-maven|vsc|0.40.4
vscode-todo-highlight|way|1.0.5

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vscaat:30438848
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
azure-dev_surveyonecf:30548226
pyindex848:30662994
nodejswelcome1cf:30587006
2e4cg342:30602488
pyind779:30671433
f6dab269:30613381
pythonsymbol12:30671437
vsctsb:30662444
vscodeenable:30660116

```

</details>

**Comment by roblourens** [comment]
Sorry, I don't quite understand, but this sounds like an issue with an IBM extension, so please file an issue on their repo with more detail
