### ISSUE TITLE
Adopt utility process in terminal/pty host

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#175335]
Follow up from https://github.com/microsoft/vscode/issues/154050

We now have sufficient infrastructure in place to easily fork a `UtilityProcess` with support of message port communication to other processes:

https://github.com/microsoft/vscode/blob/ed6bb0790b236b6732dba147021a2eefe7d94a13/src/vs/platform/utilityProcess/electron-main/utilityProcess.ts#L121

Currently the PTY agent is still running as child process in the shared process housing all terminals:

https://github.com/microsoft/vscode/blob/ed6bb0790b236b6732dba147021a2eefe7d94a13/src/vs/code/node/sharedProcess/sharedProcessMain.ts#L386-L399

We should consider moving the PTY agent out into a standalone utility process to reduce pressure on the shared process (and actually vice versa, reduce pressure on terminals).

**Comment by bpasero** [comment]
Here are some pointers how it works today with the shared process which I think is very similar to the PTY-Host, because:
* there is only 1 shared process (there is only 1 PTY-Host)
* every window connects to the shared process (and PTY-Host)
* to avoid startup perf issues, we want the process to spawn only on demand after editors have restored, triggered from the window [1]
* shared process and PTY-Host are leveraging `bootstrap-fork` to come alive as AMD module

### 1.) `electron-sandbox`: Workbench Shared process service

Any client in the workbench window that needs a `channel` from the shared process does so via the [`SharedProcessService`](https://github.com/microsoft/vscode/blob/b0b73ee333534add58d2fe48dc48b46b3533a221/src/vs/workbench/services/sharedProcess/electron-sandbox/sharedProcessService.ts#L15). This service will:
* await the `LifecyclePhase.Restored` phase ([here](https://github.com/microsoft/vscode/blob/b0b73ee333534add58d2fe48dc48b46b3533a221/src/vs/workbench/services/sharedProcess/electron-sandbox/sharedProcessService.ts#L42))
* use the [`acquirePort()`](https://github.com/microsoft/vscode/blob/b0b73ee333534add58d2fe48dc48b46b3533a221/src/vs/base/parts/ipc/electron-sandbox/ipc.mp.ts#L16) utility method to ask the main process for a `MessagePort` exchange
* create a `MessagePortClient` with the result

The utility method `acquirePort` does all the heavy lifting of passing a `MessagePort` over from the main process through the preload script and into the sandboxed window. It expects the `vscode:createSharedProcessMessageChannel` to be listened on from the main process via Electron IPC mechanics. The main process will respond to the `vscode:createSharedProcessMessageChannelResult`.

👉 For the PTY-Host I would pretty much take the workbench shared process service code as is and rename it to PTY specifics. I am not sure if the service has to be so generic to return `IChannel`. This is more meant for a process that exposes many things, but if the PTY Host only exposes fixed set of methods, I would probably only expose those.
👉 If there is sufficient overlap, we can extract a common base class and reuse the code

### 2.) `electron-main`: Shared Process Starter

The [`SharedProcess`](https://github.com/microsoft/vscode/blob/b0b73ee333534add58d2fe48dc48b46b3533a221/src/vs/platform/sharedProcess/electron-main/sharedProcess.ts#L34) in `electron-main` is the listener to the `vscode:createSharedProcessMessageChannel` Electron IPC request from any window and is responsible for spawning the process and exchanging message ports. This class will:
* spawn the [`UtilityProcess`](https://github.com/microsoft/vscode/blob/b0b73ee333534add58d2fe48dc48b46b3533a221/src/vs/platform/sharedProcess/electron-main/sharedProcess.ts#L280) upon first workbench window connection with some [`payload`](https://github.com/microsoft/vscode/blob/b0b73ee333534add58d2fe48dc48b46b3533a221/src/vs/platform/sharedProcess/electron-main/sharedProcess.ts#L331) and the AMD `entryPoint`
* calls [`UtilityProcess.connect()`](https://github.com/microsoft/vscode/blob/b0b73ee333534add58d2fe48dc48b46b3533a221/src/vs/platform/utilityProcess/electron-main/utilityProcess.ts#L364) to obtain a `MessagePort` and send that back to the requesting window via the `vscode:createSharedProcessMessageChannelResult` Electron IPC channel

👉 you can ignore the `workerXY` methods, they are for when the deprecated hidden window is used
👉 For the PTY-Host I would again think that a lot of the code can be reused, so we can think about a common super type here

### 3.) `node`: Shared Process Main

The [`SharedProcessMain`](https://github.com/microsoft/vscode/blob/b0b73ee333534add58d2fe48dc48b46b3533a221/src/vs/code/node/sharedProcess/sharedProcessMain.ts#L123) is the actual module that runs as utility process. This module will:
* listen to the [`payload`](https://github.com/microsoft/vscode/blob/b0b73ee333534add58d2fe48dc48b46b3533a221/src/vs/code/node/sharedProcess/sharedProcessMain.ts#L535-L537) to come in to instantiate itself
* send some [lifecycle events](https://github.com/microsoft/vscode/blob/b0b73ee333534add58d2fe48dc48b46b3533a221/src/vs/code/node/sharedProcess/sharedProcessMain.ts#L518-L531) back to the main process via `postMessage` to signal ready state
* create a `IPCServer` to accept `MessagePort` connections leveraging [`ipc.mp.ts`](https://github.com/microsoft/vscode/blob/b0b73ee333534add58d2fe48dc48b46b3533a221/src/vs/base/parts/ipc/node/ipc.mp.ts#L40) helper
* [exposes](https://github.com/microsoft/vscode/blob/b0b73ee333534add58d2fe48dc48b46b3533a221/src/vs/code/node/sharedProcess/sharedProcessMain.ts#L412) services as `IChannel` to the clients

👉 I think for the PTY-Host, you already do most of this, the only new thing is to check for the PTY-Host running from a utility process or a bare node.js process and then instantiating the right `IPCServer` and using the right methods for message communications. We provide a `IPCServer` for node.js as well via [`ipc.cp.ts`](https://github.com/microsoft/vscode/blob/b0b73ee333534add58d2fe48dc48b46b3533a221/src/vs/base/parts/ipc/node/ipc.cp.ts#L24)

[1] Possible solution to that is covered in: https://github.com/microsoft/vscode/issues/175959

**Comment by Tyriar** [comment]
How it currently works:

<img width="964" alt="image" src="https://user-images.githubusercontent.com/2193314/228903369-9110676a-ed77-4441-bc18-8dc23708977c.png">

Proposed after pic coming...

**Comment by Tyriar** [comment]
Source: [pty-host-20230330.tldr.txt](https://github.com/microsoft/vscode/files/11114199/pty-host-20230330.tldr.txt)

**Comment by bpasero** [comment]
Actually the file watcher is similar: it exists both in desktop and on the server. On desktop we use a utility process to fork it from the main process and on the server we use a traditional node.js `fork`, but the code is the same in the end that gets to run. There is an if-else check to see if we run from utility process or node:

https://github.com/microsoft/vscode/blob/efbdef291af6f5c0de76b5f50cd8222f7e3e3653/src/vs/platform/files/node/watcher/watcherMain.ts#L12-L20

**Comment by Tyriar** [comment]
Having some problems atm while trying to move the pty host service to the main process, the process it creates (still a regular node proc) fails to import node-pty. Not sure why yet

**Comment by Tyriar** [comment]
It does import node-pty, and it works fine if I break where the `WindowsPtyAgent` is instantiated the step through the remaining lines in `WindowsTerminal.ctor`. But if I don't do that, the heartbeats stop and I never get any data from node-pty 😕

**Comment by Tyriar** [comment]
Something that does happen immediately that is split up when stepping through is seamless relaunch due to extensions activating.

**Comment by Tyriar** [comment]
Disabling seamless relaunch doesn't fix the problem

**Comment by Tyriar** [comment]
I cannot break on this line:

https://github.com/microsoft/node-pty/blob/fdbeaa116aa112c43e381d674c2af1d4360d0108/src/windowsPtyAgent.ts#L140

I can break on the line above:

https://github.com/microsoft/node-pty/blob/fdbeaa116aa112c43e381d674c2af1d4360d0108/src/windowsPtyAgent.ts#L139

**Comment by bpasero** [comment]
Curious, did you end up having a `MessagePort` per terminal or is the `ptyHost` multiplexing?
