### ISSUE TITLE
Test messages without a location should be visible

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#175377]
See https://github.com/microsoft/vscode-test-adapter-converter/pull/33

> I think I'd like to have "Test Results" view in the bottom panel, which would be nice in general for users who prefer a consistent view to the transient peek peek view.

**Comment by joyceerhl** [comment]
@connor4312 For verification, do we just install the selfhost test provider extension, run tests in `microsoft/vscode`, and verify that a Test Results view displays test results in the output panel area?

**Comment by connor4312** [comment]
Yep, that's good
