### ISSUE TITLE
Add a keyword for profiles (like terminals have) in Ctrl+P palette

### ISSUE THREAD

**Issue by xiaoxi-david** [microsoft/vscode#175468]
I would like to manage profiles in the Ctrl+P palette by typing a keyword as I can do now with terminals.

**Comment by sandy081** [comment]
Can you please elaborate more like what keyword you mean and what you expect?

**Comment by xiaoxi-david** [comment]
Currently, you can select and create new terminals by typing `term`.
![image](https://user-images.githubusercontent.com/24303680/221659954-0e22dba2-28da-4880-a8a2-29503c127938.png)
 
At least, I would expect to be able to create and switch profiles by typing `prof`.

**Comment by sandy081** [comment]
It is supported in latest release

<img width="626" alt="image" src="https://user-images.githubusercontent.com/10746682/222375838-541d74a0-bcf8-463f-bf9f-8b849c78f5b9.png">
