### ISSUE TITLE
Not exact to find with regex

### ISSUE THREAD

**Issue by tgr-9** [microsoft/vscode#175465]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.75.1
- OS Version: Windows_NT x64 10.0.19044

Steps to Reproduce:
Find in Regex

Text:

```
Cat
cat
bat
Bat
hat
That
That
that
```

Tried to find to match to start with lowercase `^[a-z]`

Expected Result:
```
cat
bat
hat
that
```

Actual Result:
![image](https://user-images.githubusercontent.com/122168360/221422316-d8f7e4aa-c8bf-42b1-a961-00390e86fdb2.png)

**Comment by ulugbekna** [comment]
Hi @tgr-9, 

I think this is the intended behavior -- you can achieve the behavior you want by enabling "Match Case" (1 icon left of the Regex search icon)

**Comment by tgr-9** [comment]
Hi @ulugbekna,

Thanks.

I think the regular expression is case sensitive too. So I thought it should be matched without to enable "Match Case".

**Comment by AnrDaemon** [comment]
The regular expression is just one of the search options. None of them is special. If you want case-sensitive matching, enable it.

**Comment by tgr-9** [comment]
Thank you @AnrDaemon
