### ISSUE TITLE
Unify Webview and WebviewView APIs

### ISSUE THREAD

**Issue by AllanOricil** [microsoft/vscode#175455]
`WebviewView` is a really bad name because people often confuse it with `Webview`. So, couldn't `WebviewView` and `Webview` APIs be unified into a single one called `Webview`? You could add a factory layer wich will automatically handle the creation of the right "type" based on the contribution the view is rendered at. This change simplifies the API because it removes an extra type (which has a really bad name), and increases DX since developers will no longer get confused about which one they should use.

Developers just need to know how to display/render/expose a Web Page inside vscode and where they can render it.

````shell
web page -> Webview (factory) -> if contribution = A -> choose `webview`
                               |-> if contribution = B -> choose `webview view`
                                       ...
````

look at this documentation, it doesn't even highlight that they are totally different things...

![image](https://user-images.githubusercontent.com/55927613/221409798-3e272124-0aa1-47cb-89b3-10d30e3379ca.png)
source: https://code.visualstudio.com/api/extension-guides/webview

**Comment by gjsjohnmurray** [comment]
I doubt that the APIs will be changed, but perhaps the title of the documentation section you refer to should be changed to "Webview APIs" (plural), with an equivalent change in its first sentence.

**Comment by AllanOricil** [comment]
> I doubt that the APIs will be changed, but perhaps the title of the documentation section you refer to should be changed to "Webview APIs" (plural), with an equivalent change in its first sentence. 

It won't help that much, I believe. People could still think that the plural refers to number of methods a `Wbview` has. 

Improving docs would be good. But I still think that there should not exist 2 APIs doing the same thing.

**Comment by mjbvz** [comment]
Changes welcome to the docs but these apis are already unified as much as reasonable:  at the top level there's `WebviewPanel` and `WebviewView`, and then both of these types have a `Webview` that they own
