### ISSUE TITLE
Proxy support in a UI Extension for remote connections 

### ISSUE THREAD

**Issue by shsuman** [microsoft/vscode#175494]
This is Shantnu from Azure ML - Remote Extension team

One of our customers is trying to use proxy support in VSCode by setting the field "http.proxy" in the VSCode settings

But, when he is trying to open up a remote connection, it doesn't work

Upon inspecting the settings in the remote window, we couldn't find the setting "http.proxy" under user settings and the Remote settings were empty

Do you know how we can use the proxy settings for a UI extension ?

**Comment by chrmarti** [comment]
@sandy081 Should the `http.proxy` setting be available in user and remote settings? I seem to remember that you made this a special case to support different values in local and remote extension hosts.

**Comment by sandy081** [comment]
This setting is machine scoped unless the remote says to use host proxy. This means, in remote this setting is read from remote machine unless the remote says not to.

> Upon inspecting the settings in the remote window, we couldn't find the setting "http.proxy" under user settings and the Remote settings were empty

So in this case, it is available in remote machine settings.

**Comment by shsuman** [comment]
@sandy081 I understand that the proxy settings for the remote machine is under remote machine settings and that can be used by a workspace extension but my question is:
_How does a UI extension deal with proxy setup on the host machine when making HTTP/Websocket calls from inside the resolver ?_

My understanding is for workspace extensions, VSCode takes care of the proxy settings in the background by patching the HTTP library, but does it also work for UI extensions ?

**Comment by sandy081** [comment]
> My understanding is for workspace extensions, VSCode takes care of the proxy settings in the background by patching the HTTP library, but does it also work for UI extensions ?

@chrmarti Can you please reply to this?

**Comment by chrmarti** [comment]
This should work with all extensions (it is a feature the extension host implements). Which Remote extension are you looking at?

**Comment by shsuman** [comment]
vscode-ai.azureml-remote

**Comment by shsuman** [comment]
@chrmarti Just a quick update:

* The step which is failing does not make a _HTTP_ request but rather uses . [@jupyterlab/services](https://www.npmjs.com/package/@jupyterlab/services) npm package to open a _Websocket_ connection.
* An  another step which is making  _HTTP_ request is completed successfully.

Is there anything special about _Websockets_ that we need to do on our side or is it the same behavior like _HTTP_ when behind a proxy ?

**Comment by chrmarti** [comment]
How is the websocket connection set up? The proxy support only patches the `http/s` modules.

**Comment by shsuman** [comment]
I am not really sure how [@jupyterlab/services](https://www.npmjs.com/package/@jupyterlab/services) does it but most of the services use npm's [ws](https://www.npmjs.com/package/ws) package

**Comment by shsuman** [comment]
@chrmarti This was a customer issue that came a long time ago. We haven't heard from the customer or for that matter any other customer, so I am assuming the issue was resolved. You can close this now :)
