### ISSUE TITLE
Files in "files.exclude" are still appearing

### ISSUE THREAD

**Issue by Spareo** [Microsoft/vscode#17541]
- VSCode Version: 1.8.0
- OS Version: Windows 10

Steps to Reproduce:

1.  Set files.exclude to ignore .pyc files 
```
      "files.exclude": {
        ".vscode/": true,
        "**/._*": true,
        "*.pyc": true
    },
```

2.  Run a python program to generate the pyc files and see if they appear in the file side bar.

I have tried setting the files.exclude setting in both user and workspace setting and the files still appear. It worked before the most recent update.

**Comment by egamma** [comment]
This works fine for me, notice that the `*.pyc' only matches pyc files in the top level workbench folder. If you want to exclude them in all folders then use `**/*.pyc'. Can you please try with this setting.

**Comment by Spareo** [comment]
Oops, my fault. Works fine. Closing the issues.
