### ISSUE TITLE
在安装新插件重启后之前打开的文件又要重新打开了

### ISSUE THREAD

**Issue by lemontree2000** [Microsoft/vscode#17547]
- VSCode Version: Code 1.8.0 (38746938a4ab94f2f57d9e1309c51fd6fb37553d, 2016-12-13T17:45:32.595Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions:

|Extension|Author|Version|
|---|---|---|
|vscode-new-file|dkundel|2.1.0|
|debugger-for-chrome|msjsdiag|2.3.2|
|view-in-browser|qinjia|0.0.3|
|vscode-icons|robertohuertasm|4.1.0|

---

Steps to Reproduce:

1.在安装新插件重启后之前打开的文件又要重新打开了
2.

**Comment by egamma** [comment]
@rebornix translation support pls

**Comment by rebornix** [comment]
@lemontree2000 你是说，安装插件重启 vscode 后，需要重新打开之前正在编辑的文件吗？

**Comment by egamma** [comment]
Closing for now since no additional information was provided.

@lemontree2000 pls reopen the issue when you have added more information.
