### ISSUE TITLE
Show original english command names next to translated ones for extension (vscode-nls) command names

### ISSUE THREAD

**Issue by WebFreak001** [Microsoft/vscode#17549]
Right now it doesn't seem to be possible to show the grayed out english command names next to the translated ones for extensions. I want to achieve the same effect as the built-in commands like in this picture:

![https://i.webfreak.org/fcTnES.png](https://i.webfreak.org/fcTnES.png)
(Top command is how it currently looks, bottom command is the kind of style I want to achieve)

I checked the markdown extension because it has internationalization too but on there it's only the translated command too.

**Comment by dbaeumer** [comment]
Currently we replace the %...% place holder with the translated string when reading the package.json file. To implement this we would need to read the package.nls.json file as well and add an additional property to the literal to store the English version of the strings as well. Something like `_${key}_original_value`. Then the code that processes the command contributions could look for the original value and store it with the command object.

@alexandrudima this sounds a little hacky but I have no other idea how to pass the information to the actual place were we process a contribution. Do you have a better idea?

**Comment by WebFreak001** [comment]
Maybe add another value? Like keeping title in english and then adding a separate `"translated_title": "%...%"`

**Comment by dbaeumer** [comment]
The code to look at is \src\vs\platform\extensionManagement\node\extensionManagementService.ts

@michelkaporin do you want to take a step at it when we are done with the translation work (xlf)

**Comment by michelkaporin** [comment]
@dbaeumer Yes, I think I can take it after xlf work.

**Comment by dbaeumer** [comment]
Cool.

**Comment by isidorn** [comment]
Seems to work fine -> verified
![screen shot 2017-03-30 at 15 23 00](https://cloud.githubusercontent.com/assets/1926584/24506149/cf350ef6-155c-11e7-80df-de0d562254c4.png)
