### ISSUE TITLE
Suggestion navigation is broken when selectionMode = never and there is only one suggestion in the list

### ISSUE THREAD

**Issue by UR3IQO** [microsoft/vscode#175460]
Type: <b>Bug</b>

Open new document. Set **`editor.suggest.selectionMode = never`**. Type `test ` now start typing `tes` the editor will show suggestion (with only one `test` in the list). Now pressing _`down arrow`_ should select the available suggestion, but it can not be done.

On the other hand if you type `test test1` and then start typing `tes` the list will contain two items and selection works as expected - when you press _`down arrow`_ the first item is selected and you can navigate the list with _`down arrow`_ and _`up arrow`_

VS Code version: Code 1.75.1 (441438abd1ac652551dbe4d408dfcec8a499b8bf, 2023-02-08T21:32:34.589Z)
OS version: Windows_NT x64 10.0.19044
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz (8 x 2803)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.70GB (20.47GB free)|
|Process Argv|--disable-extensions .|
|Screen Reader|no|
|VM|0%|
</details>Extensions disabled

**Comment by meganrogge** [comment]
@jrieken with the setting set to "never" is it expected that there is one selected by default? I didn't have to arrow down for this to happen 🤔 

![Recording 2023-03-22 at 10 45 40](https://user-images.githubusercontent.com/29464607/226992637-8a886c62-2675-4add-abb4-945ace8267c7.gif)
