### ISSUE TITLE
Typescript export default not colored

### ISSUE THREAD

**Issue by felixfbecker** [Microsoft/vscode#1754]
`export` should be blue

![image](https://cloud.githubusercontent.com/assets/10532611/12079178/11c97b26-b230-11e5-8480-4af05c13305c.png)

**Comment by AlexanderMattoni** [comment]
I also have run into a problem where when using `export default class Foo{}`, and then subsequently trying to re-export via "import.ts": `export * from "./foo";`, I was unable to get the class definition from a file  importing "import.ts", and node would also fail trying to run it.

**Comment by felixfbecker** [comment]
@AlexanderMattoni you should open a seperate issue for that

**Comment by aeschli** [comment]
This issue was moved to Microsoft/TypeScript-TmLanguage#35
