### ISSUE TITLE
Quick fix light bulb disappears before it can be clicked

### ISSUE THREAD

**Issue by daviwil** [Microsoft/vscode#17540]
- VSCode Version: 1.8.0
- OS Version: Windows 10

Steps to Reproduce:

1. Open a file which triggers a quick fix light bulb
2. Hover the mouse over the light bulb
3. Before you click, the light bulb disappears and switches to a breakpoint icon

Filing this on behalf of @wsmelton who filed the issue originally here: https://github.com/PowerShell/vscode-powershell/issues/392

Sometimes the quick fix light bulb isn't clickable in the gutter:

![quickfixissue](https://cloud.githubusercontent.com/assets/11204251/21283288/ae28cb00-c3c5-11e6-8a50-7dcc441503bb.gif)

It seems there may be some conflict between the hover handlers of the breakpoint gutter and the lightbulb that should be showing up.  Using <kbd>Ctrl+.</kbd> on the line invokes the quick fix menu correctly even though the lightbulb isn't clickable.

**Comment by alexandrudima** [comment]
I could still reproduce on Linux

**Comment by jrieken** [comment]
@isidorn We need to sync on this. We both want to use the gutter for additional commands/menus and we should invent something like a editor gutter menu

**Comment by isidorn** [comment]
@jrieken I am open for suggestions

**Comment by jrieken** [comment]
@sandy081 sits in the same boot and should also join the party... <img width="103" alt="screen shot 2017-03-08 at 15 17 05" src="https://cloud.githubusercontent.com/assets/1794099/23707386/75cc57a8-0412-11e7-8cdb-47b710e2d6c8.png">

**Comment by sandy081** [comment]
These edit icons are shown only on settings files.. Not sure if we can add break points there

**Comment by jrieken** [comment]
There is a setting that allows breakpoints everywhere, then hit F9 while the edit icon show and screen cheese. Long story short: There are 3 custom ways to get a context menu and primary command with an icon in the gutter (breakpoints, settings, quick fix) and we should have something real, like a gutter-menu

**Comment by jrieken** [comment]
My proposal is to add a new menu ala `editor/gutter/context` to which we register commands. That menu will always show in the gutter of the active line and preview to first (most important) command in the gutter. Other command will be in the context menu, like break points do it today.

**Comment by isidorn** [comment]
@jrieken your proposal makes sense to me. We can look into this tomorrow in the office, or some time next week when it suits you.

**Comment by jrieken** [comment]
After understanding the whole richness and complexity of the debug glyph margin decoration we figured it's too much for the menu-story... Instead the light bulb uses the same implementation approach debug uses and therefore conflicts don't happen. Also, debug must check if a line has already a glyph margin decoration before adding one on mouse move, similar check before clicking... 

My old code to check if the glyph margin has space. fyi @isidorn 

```ts
private _hasSpaceInGlyphMargin(line: number): boolean {
	if (!this._editor.getRawConfiguration().glyphMargin) {
		return false;
	}
	const decorations = this._editor.getLineDecorations(line);
	if (decorations) {
		for (const {options} of decorations) {
			if (options.glyphMarginClassName) {
				return false;
			}
		}
	}
	return true;
}
```

**Comment by sandy081** [comment]
@jrieken Do I need to do the same for Settings?

**Comment by isidorn** [comment]
@sandy081 for now we can survive without that. Breakpoints will hide if there are any other decoarions on the line including yours

**Comment by jrieken** [comment]
> Breakpoints will hide if there are any other decoarions on the line including yours

Given @sandy081 uses a decoration to get wrench-icon into the glyph margin

**Comment by isidorn** [comment]
@sandy081 ok so at least you should use an editor decoration with the glyp margin options to align with the rest of us

**Comment by sandy081** [comment]
Ok. Will adopt. Reopening it.

**Comment by sandy081** [comment]
Adopted to use decorations. Closing it.

**Comment by alexandrudima** [comment]
Works nicely now. Nice job!
