### ISSUE TITLE
Turkish to English 

### ISSUE THREAD

**Issue by cptbau** [microsoft/vscode#175449]
Type: <b>Feature Request</b>

i couldn't switch the language turkish to english could you help me?

VS Code version: Code 1.75.1 (441438abd1ac652551dbe4d408dfcec8a499b8bf, 2023-02-08T21:32:34.589Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: No

**Comment by TylerLeonhardt** [comment]
Does this doc help you out? https://code.visualstudio.com/docs/getstarted/locales

**Comment by cptbau** [comment]
yes thank you

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
