### ISSUE TITLE
Visual Studio Code's ambiguous name has ruined search engine results for Visual Studio

### ISSUE THREAD

**Issue by doubledgedboard** [microsoft/vscode#175408]
I'm purely posting this to get it into the historical record, because the only other thing I could find about this was https://github.com/microsoft/vscode/issues/2150

VSCode was an absolutely awful decision for a product name. It's now 2023 and due to vscode's popular adoption rate, it's now abysmally hard to search the internet for help with problems specific to VISUAL STUDIO (as in NOT VSCODE). This is because an overwhelming majority of search results for "visual studio" are people actually talking about VSCODE.

The above mentioned issue was due to the opposite problem, back in 2016 it was hard to find vscode search results that weren't actually for Visual Studio. The "solution" then was to search for "visual studio code" or "vscode".

Well, guess what? There's no solution for searching for visual studio.

**Comment by zm-cttae** [comment]
`visual studio -code` possibly?

**Comment by doubledgedboard** [comment]
No... Believe me, I already tried all versions of mangling the search input. That's the entire problem here, people on the internet use the phrase "visual studio" when referring to VSCode now, and because the search engines are more 'algorithmic' they will 'guess' what you wanted more than give you exactly what you asked for.

There is no way to singularly identify "visual studio" results from "code" results unless you're searching for something specific to an exact version, and that person happened to qualify the name completely in their post (e.g. "Visual Studio 2022")

As an example, check the results for these searches and notice how they are overwhelmingly specific to VSCode:

`visual studio go to definition new tab`
https://www.google.com/search?q=visual+studio+go+to+definition+new+tab

``visual studio go to definition new tab``
https://www.google.com/search?q=%22visual+studio%22+go+to+definition+new+tab

`"visual studio" go to definition new tab -code`
https://www.google.com/search?q=%22visual+studio%22+go+to+definition+new+tab+-code

`"visual studio" go to definition new tab -code -vscode`
https://www.google.com/search?q=%22visual+studio%22+go+to+definition+new+tab+-code+-vscode

The problem, which hopefully is quickly apparent, is that once you start applying the negation keywords (like `-code` and `-vscode`) it ends up excluding the majority of forum/stackoverflow type posts, because they have a high chance of someone mentioning "code" or "vscode" on them, even if it's still a discussion about Visual Studio.

As another popular example: when NVIDIA released the GTX 1080, they similarly made search results extremely ambiguous because "1080" was often used to reference 1080p resolution, and there's a huge overlap between searches about resolution/1080p and video cards, so when trying to search for issues related to the GTX 1080, it involved an excessive amount of needle-in-the-stack hunting.

**Comment by zm-cttae** [comment]
Visual Studio documentation and support isn't so extensive to be honest. Jetbrains has taken its crown.

**Comment by zm-cttae** [comment]
What could help Visual Studio community grow is an initiative like #137194.
