### ISSUE TITLE
Watermark badly aligned in this case

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#175413]
This is likely a regression from https://github.com/microsoft/vscode/commit/dfcf5c1528b7de7b3e7664f9183a5f9d1e4508cd

Split a group down and notice how the watermark is badly aligned:

![Screenshot 2023-02-25 at 07 06 18](https://user-images.githubusercontent.com/900690/221341717-69fa5f52-ba1a-4953-a9b5-8a07a04ab86e.png)

Whereas it should be:

![Screenshot 2023-02-25 at 07 07 05](https://user-images.githubusercontent.com/900690/221341721-4e3179cd-3cf6-4e26-ab16-83f1e1b318e8.png)

**Comment by bpasero** [comment]
There is also something else with the size adjustment we used to have missing now I think.

**Old**
![Recording 2023-02-25 at 07 11 54](https://user-images.githubusercontent.com/900690/221341841-6de32c43-c396-4aa8-a895-ae5978c62f32.gif)

**New**
![Recording 2023-02-25 at 07 12 18](https://user-images.githubusercontent.com/900690/221341849-dbf46380-7b2f-475f-bb61-0bbe7e71dc06.gif)

**Comment by joaomoreno** [comment]
> Split a group down and notice how the watermark is badly aligned:

The problem is the editor title bar. I'll introduce some fake spacing at the bottom to be centered.

> There is also something else with the size adjustment we used to have missing now I think.

I don't see any problem with the current state, other than it's different. Is this really an issue?
