### ISSUE TITLE
Huge number of decorations created by extensions leads to UI freezes

### ISSUE THREAD

**Issue by sqnkov** [Microsoft/vscode#17542]
- VSCode Version: 1.8.1 (November)
- OS Version: Windows 10 Home

Extension list:

auto-close-tag - Version :0.3.7 
auto-rename-tag - Version :0.0.8 
beautify - Version :0.6.2 
Bookmarks - Version :0.10.1 
code-settings-sync - Version :2.3.8 
color-highlight - Version :1.3.0 
githistory - Version :0.1.4 
gitignore - Version :0.5.0 
guides - Version :0.5.1 
html-css-class-completion - Version :1.0.3 
html-snippets - Version :0.0.18 
htmltagwrap - Version :0.0.3 
indenticator - Version :0.2.1 
JavaScriptSnippets - Version :1.2.0 
jquerysnippets - Version :0.0.1 
jshint - Version :0.10.15 
lorem-ipsum - Version :1.0.0 
path-intellisense - Version :1.2.0 
php-intellisense - Version :0.0.12 
sass-indented - Version :1.3.0 
stylelint - Version :0.21.0 
terminal - Version :0.0.5 
Theme-Easyballs - Version :0.0.2 
vscode-autoprefixer - Version :2.0.0 
vscode-color - Version :0.2.2 
vscode-csscomb - Version :4.0.0 
vscode-gutter-preview - Version :0.8.2 
vscode-scss - Version :0.6.0 
vscode-simple-icons - Version :0.7.4 
vscode-svgviewer - Version :1.3.0 

[CPU-20161220T164825.zip](https://github.com/Microsoft/vscode/files/663974/CPU-20161220T164825.zip)

While working in horizontal split mode with two files opened in each pane, at random times, VS code begins to slow down while typing fast, adding new lines, copy/paste, saving, switching tabs etc.

Upon removal of the second pane and getting back to one pane/one tab view everything is running snappy and smoothly.

Git is listening for file changes.

Steps to Reproduce:

1. Open a web project in VS Code with two large HTML/CSS files in two horizontal panes
2. Observe performance degradation while working further and further

**Comment by egamma** [comment]
@sqnkov can you pls check whether your scenario is somehow related to #17208? 

This issue will be fixed in 1.8.1 that goes out later today.

**Comment by sqnkov** [comment]
@egamma , sorry to inform, but my problem is not scroll related. Hitting tab(emmet expand and autocompletion no matter the language), typing fast etc. When I switch to a solo pane everything gets faster.

**Comment by sqnkov** [comment]
I will upload a ***.gif** as soon as the degradation start.

**Comment by sqnkov** [comment]
![vs code gif](http://g.recordit.co/5XpHGG5B3F.gif)

As I focus the ".widget-matrix" object and hit enter to open a new line and start typing there is a serious delay which You can see from the gif. The time in which the line stays blank is the delay I am referring to.

**Comment by jrieken** [comment]
Can you ask you to create a profile for us? It goes like this

* open developer tools via *F1 > Toggle Developer Tools*
* select *Profiles* > *Record JavaScript CPU Profile* and press *Start*
* now produce the hang/slowness
* stop profiling (press *Stop* or the read button), save the profile, and share it with us

**Comment by sqnkov** [comment]
It stopped doing it after I opened the devtools. This is awkward. I will be doing some more work today, so let me hit a road-block again and I will save a test sample.

**Comment by sqnkov** [comment]
Here is the CPU profile:

[CPU-20161220T164825.zip](https://github.com/Microsoft/vscode/files/663974/CPU-20161220T164825.zip)

P.S. I am currently  at my day job , I am having the exact same problem on my laptop at home.

**Comment by jrieken** [comment]
Thanks - looks like the editor is busy managing decorations. 

![screen shot 2016-12-20 at 15 56 12](https://cloud.githubusercontent.com/assets/1794099/21355080/eec4dd02-c6cc-11e6-9c52-93eab21fb277.png)

Is this a large file and are you using folding? Or do you have a special extension installed that add editor decorations, like the color boxes or other inline renderings/decorations?

**Comment by sqnkov** [comment]
How can I print-out a list of my extensions?

**Comment by alexandrudima** [comment]
@sqnkov One of the installed extensions is spamming us with possibly tens of thousands of decorations. We do not limit the amount of decorations we accept because we thought we should give as much freedom as possible to extensions, but freezes of that length indicate tens of thousands of decorations coming in at every keystroke.

**Comment by sqnkov** [comment]
@alexandrudima , I am glad you've found the source. Now we hope that everyone developing extensions will be aware of this.

**Comment by alexandrudima** [comment]
Decorations in the editor have been reimplemented via PR #36410
