### ISSUE TITLE
workbench.editor.showTabs does not show tabs anymore

### ISSUE THREAD

**Issue by eliprand** [Microsoft/vscode#17546]
- VSCode Version: 1.8.0
- OS Version: Mac OS Sierra (10.12.1)

Steps to Reproduce:

1. open VS Code
2. open a project
3. open a new window (&#x21E7; &#x2318; + N)

You can see that the window opens as a new window, not as a new tab in the workbench.
Changing the `workbench.editor.showTabs` seems to have no effect whatsoever.

**Comment by bpasero** [comment]
#15478
