### ISSUE TITLE
[JavaScript] intellisense is incorrect while value get overwrited inside function member

### ISSUE THREAD

**Issue by jarvan-jiang** [microsoft/vscode#175491]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.71.2
- OS Version: Windows_NT x64 10.0.19045

Steps to Reproduce:

1. The following code correctly show intellisense of the variable 'rootVariable'
![image](https://user-images.githubusercontent.com/4934690/221499784-1f8a772e-5998-4ce7-b263-a9e96c36b136.png)

2. After changing the value of this variable, the scope is changed in intellisense, shows the value became a member of 'rootFunction',  actually it is not change, the value still belongs the JSON itself.
![image](https://user-images.githubusercontent.com/4934690/221500754-35c3d3f5-fe57-44e3-b0a1-52d3e0fa2f0d.png)

code text:
```
var test={
    rootVariable: "a",
    rootFunction : function(){
        console.log("print inside root function",this.rootVariable);
        Promise.all([]).then(()=>{
            console.log("print inside promise arrow function",this.rootVariable);
        });
        console.log(this.rootVariable);
        //with following code the intellisense displayed wrong
        //this.rootVariable = "b";
        console.log(test.rootVariable);
    }
};
test.rootFunction();
```

**Comment by jarvan-jiang** [comment]
> Please share the text of that code

Edited.

**Comment by mjbvz** [comment]
Thanks. However this seems to work for me in the latest VS Code insiders:

![Screenshot 2023-03-14 at 1 34 39 PM](https://user-images.githubusercontent.com/12821956/225130016-9bb76b0b-3022-4e4b-bee1-5c3ae99e32bc.png)

I suspect this bug was already fixed since you were on an old VS Code version

**Comment by jarvan-jiang** [comment]
> Thanks. However this seems to work for me in the latest VS Code insiders:
> 
> ![Screenshot 2023-03-14 at 1 34 39 PM](https://user-images.githubusercontent.com/12821956/225130016-9bb76b0b-3022-4e4b-bee1-5c3ae99e32bc.png)
> 
> I suspect this bug was already fixed since you were on an old VS Code version

Sorry for making misunderstanding, please uncomment the assign value line `//this.rootVariable = "b";`.
My intention is to highlight the different behaviors, maybe the comment is not clear enough.
