### ISSUE TITLE
Find/replace case sensitive not working

### ISSUE THREAD

**Issue by chadbr** [Microsoft/vscode#17544]
- VSCode Version: Version 1.8.0 (1.8.0)
38746938a4ab94f2f57d9e1309c51fd6fb37553d
2016-12-13T17:36:16.206Z

--> same problem in Version 1.9.0-insider (1.9.0-insider)

- OS Version: Mac OSX Sierra

Steps to Reproduce:

1. Search for text
2. Click the case button
3. Previously found text is not found anymore...

![anim14](https://cloud.githubusercontent.com/assets/3179452/21319716/fa2f2d72-c5d3-11e6-902a-dc58f7c4e3ca.gif)

**Comment by chadbr** [comment]
this one is killing me - please fix asap :)

**Comment by sandy081** [comment]
@chadbr Looks like you are toggling`Match Whole Word`option instead `Match Case` option. Hence you do not see results. First option is for `Match case`. Please hover on the options to know details.

**Comment by chadbr** [comment]
Ahahahaha, I'm killing myself ... 😂

Sorry about that
