### ISSUE TITLE
[Accessibility] Pressing Ctrl+M key (toggle tabFocusMode) should save separate boolean value for terminal and editor.

### ISSUE THREAD

**Issue by jooyoungseo** [microsoft/vscode#175432]
CC @meganrogge

Now there are two tabFocus settings: `{"terminal.integrated.tabFocusMode"}` and `{"editor.tabFocusMode"}`.

However, there is one keybinding that only seems to control editor tab focus: `{editor.action.toggleTabFocusMode}`.

The default keybinding (Ctrl+M on Windows) toggles on and off the tab focus mode, but it does not seem to separate terminal tab focus and editor tab focus.

## Reproducible Steps

1. Create one editor and one terminal.

1. In editor, press Ctrl+M to toggle off tab focus mode.

1. In terminal input, press Ctrl+M to toggle on tab focus mode.

1. Now go back to editor and see if editor's tabFocusMode state is still off: It is turned on. It follows terminal tabFocusMode.

* Notes: Screen reader users may frequently toggle on and off the terminalFocusMode State when using auto-completion.

## Expected Behavior

Pressing Ctrl+M key (toggle tabFocusMode) should save separate boolean value for terminal and editor.

## System Info

Version: 1.76.0-insider (system setup)
Commit: ead95b4a7014d12ddcb2dd6ddcb16e73f1e4cd67
Date: 2023-02-24T21:55:13.530Z
Electron: 19.1.10
Chromium: 102.0.5005.196
Node.js: 16.14.2
V8: 10.2.154.26-electron.0
OS: Windows_NT x64 10.0.22621
Sandboxed: Yes

**Comment by meganrogge** [comment]
these are managed separately and I cannot repro with your steps above

https://github.com/microsoft/vscode/blob/a22b77d5e1c7441e106887056b76400cae512d4b/src/vs/editor/browser/config/tabFocus.ts#L14-L15

**Comment by meganrogge** [comment]
can you see if the described steps here are what you'd expect? 

https://github.com/microsoft/vscode/issues/174924#issuecomment-1442049159

**Comment by meganrogge** [comment]
for you, what are those setting values?
