### ISSUE TITLE
editorHoverWidgets are often hard to distinguish from editor pane in default themes

### ISSUE THREAD

**Issue by ddbrierton** [microsoft/vscode#175551]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.75.1
- OS Version: macOS 13.2.1

Steps to Reproduce:

1. Enable one of the default themes, e.g. Dark+ V2 (Experimental)
2. Mouse over code in editor pane until elements such as the ones in the screenshots below appear, and note that they can be rather difficult to read sometimes.

I don’t know what the official VS Code terminology for these UI elements is — please feel free to change “Transient popovers” in the issue title with the correct term. I am referring to things like the three examples below:

<img width="606" alt="221332905-6861a3b6-b501-4e7d-9535-c5e87a9cb6da" src="https://user-images.githubusercontent.com/7255543/221623491-b124d657-7251-4d31-b347-3f72ccebc885.png">

<img width="606" alt="221332827-a84e138e-eaec-4c5a-aa48-c14aae674c67" src="https://user-images.githubusercontent.com/7255543/221623958-964d58d2-5d8d-4084-bca3-dd3c7ddd5fc0.png">

<img width="606" alt="221332833-429b4f8e-e218-48af-9968-4898260aadc5" src="https://user-images.githubusercontent.com/7255543/221623588-275c467e-3866-40d3-b1cb-ab0ad54ef29b.png">

All of them seem to have the same background-colour as the editor and as a result can be sometimes (depending on context) rather hard to read and create a sense of visual confusion.

**Comment by ddbrierton** [comment]
Also see #185044

**Comment by daviddossett** [comment]
See https://github.com/microsoft/vscode/issues/173899#issuecomment-1664745602
