### ISSUE TITLE
formatting of HTML code when using style attribute

### ISSUE THREAD

**Issue by christianmenz** [Microsoft/vscode#17551]
- VSCode Version: Code 1.8.0 (38746938a4ab94f2f57d9e1309c51fd6fb37553d, 2016-12-13T17:45:32.595Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

|Extension|Author|Version|
|---|---|---|

---

Steps to Reproduce:

1. write some simple HTML code like 
&lt;div&gt;
    &lt;div style="color:red"&gt;
    &lt;/div&gt;
&lt;/div&gt;

2. format the code -> the HTML formatting is different when you don't add the style attribute

**Comment by egamma** [comment]
Duplicate  #17637
