### ISSUE TITLE
VSCode freezes/crashes on Windows 11 when switching user

### ISSUE THREAD

**Issue by jsgonsette** [microsoft/vscode#175533]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.75.1
- OS Version: Windows 11 22H2

Visual Studio Code freezes when switching to another session and launching an application using the GPU.

Steps to Reproduce:

1. Launch Visual Studio
2. Lock the session and switch to some other user
3. Launch Roblox (or maybe anything using the GPU. But in my case, this is the typical scenario with my children)
4. Close the session and come back to the original one
5. --> Visual Studio is frozen in some completely unresponsive state, as well as Microsoft Teams that suffers exactly the same problem.

**Comment by deepak1556** [comment]
Merging to https://github.com/microsoft/vscode/issues/172717
