### ISSUE TITLE
old version of python extension can not load

### ISSUE THREAD

**Issue by gjm-anban** [microsoft/vscode#175524]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.75.1
- OS Version: unbuntu 20.04 

Steps to Reproduce:

1.  I installed python extension v2021.5
![image](https://user-images.githubusercontent.com/73465248/221543574-e6b6d3e1-a86d-4bf7-bc24-a2f6f5399694.png)

2、and try to debug my python project,but python extension can not load
![image](https://user-images.githubusercontent.com/73465248/221543779-b469a773-3e11-4bae-a5ed-45716fb005c7.png)

**Comment by GitMensch** [comment]
Do you mind to change the display language to English so that others can have a more educated guess what is happening?
Ideally you could also post the log output from this extension and/or the extension host and/or the common log if it says anything about this.

**Comment by roblourens** [comment]
Does it work with the latest version of the python extension? Why are you trying to install an old version?

**Comment by gjm-anban** [comment]
> Does it work with the latest version of the python extension? Why are you trying to install an old version?

I used another version 2020.5 and it worked. I used it because when I try to debug sqlmap the latest version's info shows I should install an old  version.

**Comment by gjm-anban** [comment]
select another version
