### ISSUE TITLE
Allow to dock the panel to the right hand side vertically

### ISSUE THREAD

**Issue by acdha** [Microsoft/vscode#17556]
- VSCode Version: 1.8.0
- OS Version: macOS 10.12.2

My monitor is almost twice as wide as it is tall. It'd be really nice to have the option to display the list on the side of the display similar to the way the panels work since the right half of my display is often almost entirely empty.

**Comment by bpasero** [comment]
@acdha to be clear, you want to be able to dock the panels to the right hand side of the editors instead of below the editors?

**Comment by acdha** [comment]
@bpasero Correct: I used that for years with TextMate where validation messages & previews lived on the right side, and it works really well on a wide display.

**Comment by isidorn** [comment]
Dup of #2806
