### ISSUE TITLE
Software dev is easy and for dumb kids.

### ISSUE THREAD

**Issue by ghost** [microsoft/vscode#175561]
I have not done a search for similar discussions

 ⚠️⚠️ Death to you microsoft [TRASHrosoft] devs and employees, you cheap loser shills. Death to you for openly promoting donkeys who work for the garbage & useless so called "health" "sector". Death to you for being such stupid slaves and praising those daft morons. Death to you for promoting those stupid childish ego pigs, who work for such a garbage "sector". Death to every moron who works for or supports that dumpster "sector". Death to you for promoting those dumb clowns in your trashy office 365 calendar app and your garbage OS. 
Death to you microsoft clown employees, you donkey scums Death to you for openly promoting and praising "universities" and praising those disgusting 2/6 letter stupid "titles" those monkeys use. Death to you and death to every loser donkey who uses that disgusting & racist 6 letter donkey word used by the trasholes ["univeristies"]. Death to you for openly promoting donkeys who work for the garbage  & useless so called "health" "sector". Death to you for being such stupid mainstream shills and praising those daft morons. Death to you for promoting those stupid childish ego pigs, who work for such a garbage "sector". Death to you for openly praising and promoting the UK's ugly & useless & trashhole "national" clown "service". Death to EVERY donkey who supports those donkeys. You're all nothing but useless slaves, you TRASHrosoft scumbags. Microsoft is utter trash, and so is windows and every garbage trashware that those monkey micorsoft devs have ever touched or made. 

Microsoft has absolutely no potential, and is a complete and utter laughable failure. Death to you stupid microTRASH script kiddos. Death to your trashy software. Death to every idiot who uses the stupid 6-letter "prefixes" when mentioning first names. Death to all "universities" [DUMPSTERversities]. 
Death to you microsoft [microGARBAGE] devs and employees. Have a sad life and painful death, microsoft workers, you clown slaves.
And one other thing....
Death to you scums for being disrespectful to engineering and claiming to be engineers. None of you microsoft devs/employees are engineers, never were and you'll never be close. Microsoft knows ABSOLUTELY NOTHING about what engineering is or what it entails. You microsoft scriptkiddos clowns are just scummy wannabes who will never even come close to an engineer. There is no such thing as "software" "engineering". That is the stupidest and most pathetic lie ever. Quit being disrespectful to Engineering, you dirty rats. You know nothing about what Engineering entails. Engineering means designing, building and producing real mechanical systems, like turbojets and vehicular engines. It has nothing to do with scriptkiddies like you microsoft [TRASHrosoft] monkeys sitting behind a keyboard and writing code. 

Software dev is easy and for dumb kids. And it has absolutely nothing to do with a serious and real subject like Engineering (Mechanical Engineering is the ONLY Engineering). Quit making false claims against engineering. And stop being disrespectful to real Engineers (Mechanical Engineering is the ONLY Engineering). Death to you dumb kids for making lies against engineering.
Hope your dirty and cheap throats get slit, microsoft loser employees and devs.
@MicrosoftIsGarbage

**Comment by Khazbs** [comment]
Whoever wrote this needs serious medical help
