### ISSUE TITLE
Cannot drag custom mime from tree view into editor

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#175589]
Type: <b>Bug</b>

See https://stackoverflow.com/questions/75578954/how-to-drag-a-treeview-item-and-drop-into-jupyter-notebook-within-a-jupyter-edit for repo steps

VS Code version: Code - Insiders 1.76.0-insider (Universal) (3c8099c659099d3af89a66f9635b4700a887f177, 2023-02-27T16:09:10.493Z)
OS version: Darwin x64 22.3.0
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|3, 3, 3|
|Memory (System)|32.00GB (3.13GB free)|
|Process Argv|--crash-reporter-id 48781ca2-1705-4f64-9bab-325055aab55d|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by joyceerhl** [comment]
Marking verified based on https://stackoverflow.com/questions/75578954/how-to-drag-a-treeview-item-and-drop-into-jupyter-notebook-within-a-jupyter-edit#comment134236766_75586066
