### ISSUE TITLE
Inconsistent keyboard shortcuts between Windows and Linux

### ISSUE THREAD

**Issue by NCC1701M** [Microsoft/vscode#17550]
- VSCode Version: Code 1.8.0 (38746938a4ab94f2f57d9e1309c51fd6fb37553d, 2016-12-13T18:03:00.506Z)
- OS Version: Linux x64 4.4.0-53-generic
- Extensions:

|Extension|Author|Version|
|---|---|---|
|vscode-markdownlint|DavidAnson|0.6.0|
|xml|DotJoshJohnson|1.6.0|
|code-settings-sync|Shan|2.3.8|
|html-snippets|abusaidm|0.0.18|
|Bookmarks|alefragnani|0.10.1|
|vscode-svgviewer|cssho|1.3.0|
|tslint|eg2|0.7.1|
|vscode-guid|heaths|1.0.0|
|docomment|k--kato|0.0.9|
|mssql|ms-mssql|0.2.0|
|PowerShell|ms-vscode|0.8.0|
|csharp|ms-vscode|1.5.3|
|debugger-for-chrome|msjsdiag|2.4.1|
|view-in-browser|qinjia|0.0.3|
|sass-indented|robinbentley|1.2.1|
|yo|samverschueren|0.9.3|
|MDTools|seanmcbreen|1.0.0|
|change-case|wmaurer|1.0.0|

---

Steps to Reproduce:

1. Open File -> Preferences -> Keyboard Shortcuts
2. Set focus on default key bindings
3. Search for *editor.action.formatDocument*

As you can see on Windows the key is **shift+alt+f** while on Linux it is **ctrl+shift+i**

Please make the default keybinding for both systems the same.

**Comment by egamma** [comment]
@NCC1701M There are different constraints on each platform when it comes to the available keybindings, we therefore cannot use the same keybindings on Windows and Linux.

**Comment by NCC1701M** [comment]
On Ubuntu 16.04 I didn't noticed any side effects while using shift+alt+f
