### ISSUE TITLE
F# interactive shows random characters when editing a line

### ISSUE THREAD

**Issue by basvdlinden** [Microsoft/vscode#17557]
- VSCode Version: Code 1.8.0 (38746938a4ab94f2f57d9e1309c51fd6fb37553d, 2016-12-13T17:45:32.595Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

|Extension|Author|Version|
|---|---|---|
|Ionide-fsharp|Ionide|2.13.2|
|csharp|ms-vscode|1.5.3|

---

Steps to Reproduce:

1. Type a few characters
2. Press backspace a few times

or

1. Type a few characters
2. Use mouse to select a character in the middle
3. Type a few characters

**Comment by egamma** [comment]
This issue was moved to ionide/ionide-vscode-fsharp#315
