### ISSUE TITLE
Git push to Overlead requires double sign in

### ISSUE THREAD

**Issue by ttoommxx** [microsoft/vscode#175569]
Type: <b>Bug</b>

Whenever I try to git push to a repository hosted by Overleaf, VScode asks for my user name and password twice. If I do it separately via terminal then this does not happen, I only get asked once.
On a side note, it still works correctly after entering my creditials correctly, the second time

VS Code version: Code 1.75.1 (441438abd1ac652551dbe4d408dfcec8a499b8bf, 2023-02-08T21:35:30.018Z)
OS version: Linux x64 5.10.147-20137-gfa8e6d1d4794
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7300U CPU @ 2.60GHz (4 x 2711)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|1, 1, 1|
|Memory (System)|2.75GB (2.23GB free)|
|Process Argv|--unity-launch --crash-reporter-id 3e8a2f93-c19a-4816-be9c-04140cdb0eda|
|Screen Reader|no|
|VM|100%|
|DESKTOP_SESSION|undefined|
|XDG_CURRENT_DESKTOP|X-Generic|
|XDG_SESSION_DESKTOP|undefined|
|XDG_SESSION_TYPE|undefined|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
latex-workshop|Jam|9.7.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
pynewext54:30669237
azure-dev_surveyone:30548225
pyindex848:30662994
nodejswelcome1cf:30587006
282f8724:30602487
pyind779:30671433
f6dab269:30613381
vscrpc:30673769
pythonsymbol12:30671437
vscodedisable:30660115
pythonb192cf:30669361

```

</details>

**Comment by lszomoru** [comment]
@ttoommxx, are you able to reproduce this every time you try to push?

**Comment by ttoommxx** [comment]
> @ttoommxx, are you able to reproduce this every time you try to push?

Actually I can't reproduce it anymore, after the few updates of Git and VScode that happened in between then and now, and after adding the option to store email and password, it hasn't been asking anything anymore, which is the expected behaviour. Sorry I should have closed this myself. Thanks for following up though!

**Comment by lszomoru** [comment]
@ttoommxx, thank you very much for the update.
