### ISSUE TITLE
Join lines should be comment block aware

### ISSUE THREAD

**Issue by mfrost66** [Microsoft/vscode#17553]
Join lines should be comment aware, and remove leading comment text from joined line.
For me specifically, this is very useful as applied to javascript jsdoc style comments, as they have a leading '*'.  I suspect this applies equally to other lanagues with similar doc comments (c#, java, etc)

### Comment   

```javascript
//Line 1
//Line 2
```
Joined
```javascript
//Line 1 Line 2
```

### Comment block   

```javascript
/** Function description
 * @param arg1 {string} blah
 *    blah blah
 * @param arg2 {Object}
 */
```
Join arg1 lines
```javascript
/** Function description
 * @param arg1 {string} blah blah blah
 * @param arg2 {Object}
 */
```

**Comment by rebornix** [comment]
I like your idea! Right now this command is not language-aware, it means it has no idea about whether the lines are comments, brackets, strings, etc and it has no idea about how to handle them. The case you mentioned is one of them.

As the behavior might vary in different languages, it would be great to put it in an extension.

**Comment by alexandrudima** [comment]
This feature request will not be considered in the next [6-12 months roadmap](https://github.com/Microsoft/vscode/wiki/Roadmap) and as such will be closed to keep the number of issues we have to maintain actionable. Thanks for understanding and happy coding!
