### ISSUE TITLE
Cannot connect to IBMi

### ISSUE THREAD

**Issue by emhill57** [microsoft/vscode#175549]
Type: <b>Bug</b>

When I try to connect to our IBMi I get the following:

Not connected to -ipaddress-! connect ECONNREFUSED -ipaddress-:22, where "ipaddress" is our IBMi's IP.  Has been working but now am getting this error.  We are at version:

==================
Version: 1.75.1 (user setup)
Commit: 441438abd1ac652551dbe4d408dfcec8a499b8bf
Date: 2023-02-08T21:32:34.589Z
Electron: 19.1.9
Chromium: 102.0.5005.194
Node.js: 16.14.2
V8: 10.2.154.23-electron.0
OS: Windows_NT x64 10.0.19045
Sandboxed: No
==================

VS Code version: Code 1.75.1 (441438abd1ac652551dbe4d408dfcec8a499b8bf, 2023-02-08T21:32:34.589Z)
OS version: Windows_NT x64 10.0.19045
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD A8-6500B APU with Radeon(tm) HD Graphics    (4 x 3493)|
|GPU Status|2d_canvas: unavailable_software<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>opengl: disabled_off<br>rasterization: disabled_software<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.20GB (8.34GB free)|
|Process Argv|--crash-reporter-id 43ca463e-544a-4541-8705-ba3cd49cecc8|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
ibmi-languages|bar|0.6.10
vscode-rpgfree|Bri|0.0.25
code-for-ibmi|hal|1.7.4
vscode-ibmi-walkthroughs|hal|0.3.1
rpg|Nie|0.2.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
pynewext54:30669237
azure-dev_surveyone:30548225
vscccc:30610679
pyindex848:30662994
nodejswelcome1cf:30587006
2e4cg342:30602488
pyind779:30671433
f6dab269:30613381
pythonsymbol12:30671437
showlangstatbar:30672706

```

</details>

**Comment by ulugbekna** [comment]
Hi @emhill57 ,

Thanks for the issue. 

Some questions to get idea of what's happening:

1. How are you trying to connect to IBMi? Are you using some extension for it? 
2. Are you sure this isn't the problem on the server-side because ECONNREFUSED is "connection refused by server", as far as I know
