### ISSUE TITLE
Cannot scroll through terminal. Scroll wheel instead will scroll through command history

### ISSUE THREAD

**Issue by samd1993** [microsoft/vscode#175586]
Using v.1.74.1 on MacOS Monterey v12.4 on Macbook Air M1

I cannot scroll up or down in Terminal. Using zsh shell. I saw there were previous problems but none of the alternative solutions have worked.
I've tried every combo of Ctrl+Up etc. or Shift+Fn+Up but nothing works. The scroll bar is also not visible.
Everytime I scroll it instead just moves up my command history as if I was doing UpArrow or DownArrow. Same with the Ctrl and Shift modifiers. It will just move up my command history. Shift Up and Shift down weirdly gives me A and B in the command line...

Update: When I change to bash terminal problem is fixed for 10 minutes and then the same behavior returns where I cannot scroll through terminal

Any help would be greatly appreciated!
Cheers,
Sam

PS: as you can see in the gif, my cursor is still because I am scrolling and instead of scrolling up or down, the command history is getting cycled. Then I mouseover to where the scroll bar should show up and it is gone.

![Recording 2023-02-27 at 15 36 16](https://user-images.githubusercontent.com/22188081/221691973-75c84509-e261-4649-90ed-9788692e0257.gif)

**Comment by meganrogge** [comment]
It looks like you've entered a subshell there - does this repro in just plain `zsh`?

**Comment by samd1993** [comment]
So I went up to the zsh tab (the one you can see in the gif) and the scroll bar was there and scrolling worked. Then when I ssh into my server the scroll bar disappears and the weird scroll behavior returns. And when I make a new zsh terminal the issue remains until I restart vscode. So not sure if it happens because of the ssh because the issue persists in a new zsh tab

**Comment by meganrogge** [comment]
Does it happen if you disable all extensions?

**Comment by samd1993** [comment]
Good point. I disabled all but issue persisted. Logged out of server and started new terminal and issue is gone. SShed into it and still everything fine. THEN when I do "screen -R screenid" the issue returned. And then when I exit screen the scrollbar returns. So it seems to be when i use the screen command?

**Comment by meganrogge** [comment]
We do not have control of subshells/ their key handling. So yeah when you enter that command and thus a subshell, it makes sense that the mousewheel etc is handled differently.

**Comment by eengstrom** [comment]
@meganrogge - I appreciate that you don't have control over the subshells, but something did change recently.  I too would like to return to the ability to scroll through the terminal history (of the subshell), be that `ssh`, `mosh`, or a `screen` or `tmux`. 

Where is the behavior defined (and documented) as to the translation of mouse wheel events?
