### ISSUE TITLE
Revert change no longer possible inline

### ISSUE THREAD

**Issue by DFelten** [microsoft/vscode#175535]
Type: <b>Bug</b>

It's no longer possible to revert changes inline. The dialog appears, but when selecting revert change nothing happens.

<img width="159" alt="CleanShot 2023-02-27 at 14 46 33@2x" src="https://user-images.githubusercontent.com/1169185/221580158-a4ecd7a4-15c5-4c00-a882-a98d1e77e9ec.png">

VS Code version: Code - Insiders 1.76.0-insider (ead95b4a7014d12ddcb2dd6ddcb16e73f1e4cd67, 2023-02-24T22:20:45.098Z)
OS version: Darwin arm64 22.3.0
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Max (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|8, 8, 8|
|Memory (System)|32.00GB (1.18GB free)|
|Process Argv|--crash-reporter-id 511166e9-0c5e-4225-a6af-efd2d90c3f8d|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (78)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|3.0.2
codesnap|adp|1.3.4
vscode-m3u|af4|1.0.0
TabOut|alb|0.2.2
Bookmarks|ale|13.3.1
project-manager|ale|12.7.0
flutter-snippets|ale|3.0.0
toggle-excluded-files|eam|1.7.0
clipboard-history|Anj|1.0.7
melos-code|bla|0.6.0
vscode-intelephense-client|bme|1.9.5
ccs-flutter-color|cir|1.0.2
gitignore|cod|0.9.0
php-namespace-resolver|ctf|0.4.3
vscode-mysql-client2|cwe|6.2.2
vscode-mac-color-picker|dae|1.1.0
markdown-table-prettify|dar|3.6.0
dart-code|Dar|3.59.20230214
flutter|Dar|3.58.0
vscode-markdownlint|Dav|0.49.0
githistory|don|0.6.19
gitlens|eam|13.3.1
bloc|Fel|6.6.2
mason|Fel|0.1.10
flutter-coverage|flu|0.0.4
shell-format|fox|7.2.5
copilot|Git|1.75.8985
copilot-labs|Git|0.11.742
vscode-pull-request-github|Git|0.58.2
gitlab-workflow|Git|3.60.0
todo-tree|Gru|0.0.224
terraform|has|2.25.4
json-to-dart|hir|3.5.8
rest-client|hum|0.25.1
monkey-patch|ioc|0.1.23
pubspec-assist|jer|2.3.2
shortcut-menu-bar|jer|3.0.4
intellij-idea-keybindings|k--|1.5.5
indent-to-bracket|LAK|1.2.2
flutter-intl|loc|1.19.1
syntax-project-pbxproj|mar|0.1.3
flutter-snippets|Mar|1.0.5
Kotlin|mat|1.7.1
rainbow-csv|mec|3.5.0
git-graph|mhu|1.30.0
dart-barrel-file-generator|miq|6.0.0
diff-merge|mos|0.7.0
vscode-docker|ms-|1.24.0
vscode-language-pack-de|MS-|1.76.2023022209
remote-containers|ms-|0.281.0
live-server|ms-|0.4.5
vsliveshare-pack|ms-|0.4.0
vscode-flutter-freezed-helper|mth|0.1.0
sqltools|mtx|0.27.1
sqltools-driver-mysql|mtx|0.5.1
awesome-flutter-snippets|Nas|4.0.1
vscode-yaml-sort|Pas|6.4.1
vscode-versionlens|pfl|1.5.0
material-icon-theme|PKi|4.24.0
remove-comments|pli|1.2.2
vscode-thunder-client|ran|2.4.3
vscode-yaml|red|1.11.0
vscode-sort-json|ric|1.20.0
command-variable|rio|1.49.1
flutter-riverpod-snippets|rob|1.2.1
vscode-coverage-gutters|rya|2.10.3
lcov-lang|Ser|1.0.1
swift-lang|ssw|1.1.0
freezed-model-gen|Sus|1.0.1
better-search|tra|0.0.6
errorlens|use|3.7.0
vscode-lldb|vad|1.8.1
vscode-wakatime|Wak|24.0.7
vscode-todo-highlight|way|1.0.5
php-debug|xde|1.32.0
vscode-surround|yat|1.5.0
markdown-all-in-one|yzh|3.5.0
material-theme|zhu|3.15.6

(3 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256198
vslsvsres303:30308271
pythonvspyl392:30422396
pythontb:30258533
vsc_aa:30263845
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscod805cf:30301675
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30404738
cppdebug:30492333
vsclangdf:30492506
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30618038
pylantcb52:30590116
pyindex848:30611229
nodejswelcome1:30587009
pyind779:30611226
pythonsymbol12:30651887
showlangstatbar:30659908
pythonb192cf:30661257
pythonms35:30671666

```

</details>

**Comment by ssoft-wankun** [comment]
when you are using a workspace this may happens.

**Comment by larshp** [comment]
I've been having similar issues, not using workspaces. With different file types

**Comment by hakula139** [comment]
In my case, instead of nothing happens, it repeats the last change (but not the expected one).

Before reverting:

<img width="719" alt="image" src="https://user-images.githubusercontent.com/9496568/222718645-96f2b9c9-acac-40a6-b65a-b1e4f911207a.png">

After reverting:

<img width="732" alt="image" src="https://user-images.githubusercontent.com/9496568/222718708-6dc9efce-e3d0-4757-a491-5fc502dfcc51.png">

**Comment by StefanBrand** [comment]
Workaround if you install VSCode on Ubuntu with `snap`: `sudo snap revert code`.

**Comment by DFelten** [comment]
@lszomoru Issue is still there on the latest version of VSCode.
