### ISSUE TITLE
Use display:none instead of opacity:0 to hide term a11y buffer

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#175685]
I noticed that opacity: 0 is the only thing preventing the buffer from displaying:

<img width="166" alt="image" src="https://user-images.githubusercontent.com/2193314/221944261-bc313450-58dd-47d8-8d06-18cca32056dd.png">

This is bad because it means that any resize to the container will still cause the monaco editor to layout, despite the user not being able to see it.

**Comment by Tyriar** [comment]
This might be part or all in xterm.js

**Comment by Tyriar** [comment]
Actually we need opacity so it can take the focus event 🤔, whatever we do we want to make sure monaco doesn't need to process a resize when it's hidden

**Comment by meganrogge** [comment]
could make a class that extends `CodeEditorWidget` for `_bufferEditor` with an `override` for `layout` that checks `opacity` and only then calls `super.layout`

**Comment by meganrogge** [comment]
wouldn't layout always get called with the right dimensions? why would we have to cache them? 

also wouldn't have to track opacity change because we could just call layout when the accessible buffer gets focused

**Comment by Tyriar** [comment]
If we're suppressing layouts, we would need to store the last suppressed one so we can call layout when it's shown. Unless this is already happening?

**Comment by meganrogge** [comment]
we know the size of the container, so couldn't we just use those dimensions and call layout ourselves when needed IE when it's focused/becomes visible?

**Comment by meganrogge** [comment]
> This is bad because it means that any resize to the container will still cause the monaco editor to layout

this doesn't get hit until I focus the accessible buffer
https://github.com/microsoft/vscode/blob/d4d02122bec716c1a86bdb02fe4b69a29c94629c/src/vs/editor/browser/config/elementSizeObserver.ts#L82

**Comment by Tyriar** [comment]
If it's only hit once that's good enough. I also noticed the editor is created eagerly on terminal startup which isn't great, but I'm assuming it's fast enough so let's tackle that if it becomes a problem.
