### ISSUE TITLE
Adding a property to tasks.json (without warning)

### ISSUE THREAD

**Issue by GuardRex** [Microsoft/vscode#17566]
- VSCode Version: 1.8.1
- OS Version: Win10

Steps to Reproduce:

1. Add a custom property to `tasks.json`.

Expected:

Allows custom properties to be set in the file. Custom properties are just ignored by VSC when it consumes/configures the tasks.

Actual:

Complains that the property isn't allowed.

![capture](https://cloud.githubusercontent.com/assets/1622880/21331171/be075530-c606-11e6-84b0-99046819badb.PNG)

Questions
1. Is there a schema at play that I can modify on the clients's machine to get rid of the warning?
2. If not, Is there some other way around the warning?
3. If not, any harm in ignoring this warning (i.e., VSC will run just fine and ignore the property)? I'll note it to my extension users in the README then.

**Comment by GuardRex** [comment]
Catching on ... looks like it's in an interface `BaseTaskConfiguration` according to http://code.visualstudio.com/docs/editor/tasks_appendix. Can you provide guidance on how I can put something into the extension that would add a property (`showInStatusBar`) to the interface?

**Comment by dbaeumer** [comment]
@aeschli is this possible. I know that extensions can contribute JSON schemas however I am not sure if they can modify existing once.

**Comment by aeschli** [comment]
Your extension can also add a schema for task.json. 
	"contributes": {
		"jsonValidation": [
			{
				"fileMatch": "/.vscode/tasks.json",
				"url": "./custom-tasks-schema.json"
			}
		]
	}
In that schema you only describe the extra new property.

**Comment by GuardRex** [comment]
@dbaeumer @aeschli :point_up: that looks good, but I need a bit of help to implement it.

Your example shows a JSON schema file, but the schema for VS Code seems to be in TypeScript ... along the lines of ...
```TypeScript
export interface TaskDescription {
  /**
    * Whether this task shows up in the status bar.
  */
  showInStatusBar?: boolean;
}
```
Once I understand how you get to a JSON schema file `custom-tasks-schema.json` ...
```json
"contributes": {
  "jsonValidation": [
    {
      "fileMatch": "/.vscode/tasks.json",
      "url": "./custom-tasks-schema.json"
    }
  ]
}
```
... which file am I adding that to?

**Comment by dbaeumer** [comment]
@aeschli can you help him. You know a lot more about JSON schema than I do :-)

**Comment by GuardRex** [comment]
@dbaeumer He must be busy/OOF. Is there anyone else who might know? ... or ... is this even really a VS Code team question? ... Is that squiggle actually being produced by Omnisharp? (i.e., should I move this over to `OmniSharp/omnisharp-vscode` issues?)

**Comment by dbaeumer** [comment]
@GuardRex he is in. I will ping him again. 

The squiggle is produced by VS Code's JSON language server based on the schema VS Code defines for tasks.json files.

**Comment by aeschli** [comment]
@GuardRex Looks like this is an issue in the JSON language support. The problem is that we combine all schemes with 'allOf'. So each schema needs to be valid. That doesn't work well with 'additionalProperties: true' where there is always one schema that doesn't contain the properties.

Please file a bug against the JSON support, but I must say its a tricky issue to solve.

**Comment by GuardRex** [comment]
Thanks ... What repo covers "JSON support" where I should file the issue?

**Comment by aeschli** [comment]
It's this repo. I created #20193 for you.

**Comment by GuardRex** [comment]
Thank you @aeschli for all of your help here.
