### ISSUE TITLE
Debug Julia in VS code ("Some Julia code in the VS Code extension crashed")

### ISSUE THREAD

**Issue by 123liziqi** [microsoft/vscode#175658]
Several months ago, everthing was running with Julia (version 1.3) in VS code by clicking "Run and Debug". 

However, with the same code, the following error appeared while running the code and I haven't found any solution so far. 

**"Error: Some Julia code in the VS Code extension crashed
ERROR: KeyError: key 0 not found"**

Either updating the latest version (the other problem related to the packages occured so I reset the version of julia 1.3) or change launch.json as following :

    "configurations": [

    {
        "type": "julia",
        "request": "launch",
        "name": "Launch Julia tests",
        "program": "${workspaceFolder}/XXXXX.jl",
        "stopOnEntry": true
    },

Could anybody help me out ? Thank you in advance.

**Comment by roblourens** [comment]
This probably is an issue for the Julia extension, please file it there, thanks
