### ISSUE TITLE
Show suggest widget on trigger characters

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#175656]
Refs: https://github.com/microsoft/vscode/issues/131940

Let's change the default of 
`"editor.inlineSuggest.allowSuggestOnTriggerCharacters": true`

Let's keep` "editor.inlineSuggest.allowQuickSuggestions": false`

After we do that let's double check if Copilot is returning `null` when we ask them for inline completions after a focused suggest item changes.

**Comment by hediet** [comment]
> After we do that let's double check if Copilot is returning null when we ask them for inline completions after a focused suggest item changes.

I just checked, this seems to be the case.
