### ISSUE TITLE
How i can désactive this ?

### ISSUE THREAD

**Issue by Thom-93** [microsoft/vscode#175661]
![Capture d’écran 2023-02-28 164437](https://user-images.githubusercontent.com/108375234/221905348-6de62b4f-37cc-4ca0-b31e-568c80bef191.png)

hi,

when i code the vs code show what is inside in grey but i dont now how i can desactive this ?

thanks

**Comment by lramos15** [comment]
You can turn inlay hints off via the `editor.inlayHints.enabled` setting.
