### ISSUE TITLE
VS Code target closes under WSL when debugging extension

### ISSUE THREAD

**Issue by dbaeumer** [microsoft/vscode#175636]
Version: 1.76.0-insider (user setup)
Commit: 3c8099c659099d3af89a66f9635b4700a887f177
Date: 2023-02-27T16:09:39.596Z
Electron: 19.1.11
Chromium: 102.0.5005.196
Node.js: 16.14.2
V8: 10.2.154.26-electron.0
OS: Windows_NT x64 10.0.22623
Sandboxed: Yes

Steps to reproduce:

- start WSL 
- clone  https://github.com/microsoft/vscode-extension-samples.git
- checkout branch `dbaeumer/xenial-moth-chocolate`
- cd `lsp-sample`
- `npm install`
- `npm run compile`
- code-insiders .
- go to debug viewlet
- select Lauch client
- Debug

Observe: Target VS Code opens and closes again.

![cast](https://user-images.githubusercontent.com/1931590/221827415-2f274d78-5130-4f03-a8a6-f0217a09eb35.gif)

**Comment by dbaeumer** [comment]
@aeschli FYI

**Comment by dbaeumer** [comment]
Actually debugging works for me for another extension. So seems to be related to my lsp-sample. Will close for now.

**Comment by dbaeumer** [comment]
OK, the problem is the following setting in the launch config:

`"autoAttachChildProcesses": true`

Reopening the issue since such a setting should not make the target close.

**Comment by connor4312** [comment]
Duplicates https://github.com/microsoft/vscode-js-debug/issues/1503
