### ISSUE TITLE
hi, my files in the folder java-0074 are missing

### ISSUE THREAD

**Issue by sumanth321123** [microsoft/vscode#175612]
ADD ISSUE DESCRIPTION HERE

Version: 1.75.1
Commit: 441438abd1ac652551dbe4d408dfcec8a499b8bf
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36
Embedder: codespaces

**Comment by joyceerhl** [comment]
@sumanth321123 do you have additional information to reproduce this issue?

**Comment by sumanth321123** [comment]
My files in the folder java-0074 in which I stored my java files are
missing

**Comment by joyceerhl** [comment]
@sumanth321123 Is this in a GitHub Codespace?

**Comment by sumanth321123** [comment]
Yes, it is.

**Comment by joyceerhl** [comment]
Looping in @jkeech for Codespaces support

**Comment by sumanth321123** [comment]
Thank you!

**Comment by jkeech** [comment]
@sumanth321123, please open a GitHub Support ticket with details about your codespace (name/url) for the support team to investigate. Thanks!
