### ISSUE TITLE
Quick fix does not work in Source Control Message area

### ISSUE THREAD

**Issue by ctsstc** [microsoft/vscode#175613]
Type: <b>Bug</b>

With an extension installed like spell checker:
https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker

The quick fix option does not do anything.

This seems to be related to this closed issue that wasn't finished:
https://github.com/microsoft/vscode/issues/155282 

VS Code version: Code 1.75.1 (Universal) (441438abd1ac652551dbe4d408dfcec8a499b8bf, 2023-02-08T21:34:59.000Z)
OS version: Darwin arm64 22.3.0
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|4, 4, 4|
|Memory (System)|16.00GB (0.06GB free)|
|Process Argv|--crash-reporter-id 70026821-dffa-44d0-829d-9cbf64e429ea|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (95)</summary>

Extension|Author (truncated)|Version
---|---|---
terraform|4op|0.2.5
better-comments|aar|3.0.2
vscode-javascript-repl|ach|0.7.4
commit-message-editor|ada|0.22.1
vscode-css-formatter|aes|1.0.2
jest-snippets|and|1.9.1
atlascode|atl|3.0.2
tailwind-docs|aus|2.0.0
markdown-preview-github-styles|bie|1.0.1
vscode-intelephense-client|bme|1.9.5
vscode-tailwindcss|bra|0.9.7
phpserver|bra|3.0.2
better-toml|bun|0.3.2
vscode-opennewinstance|chr|0.0.12
path-intellisense|chr|2.8.4
vscode-css-modules|cli|0.4.2
gitignore|cod|0.9.0
dart-code|Dar|3.58.0
flutter|Dar|3.58.0
vscode-eslint|dba|2.4.0
githistory|don|0.6.19
gitlens|eam|13.3.1
EditorConfig|Edi|0.16.4
prettier-vscode|esb|9.10.4
html-slim-scss-css-class-completion|gen|1.7.8
copilot|Git|1.76.9071
vscode-pull-request-github|Git|0.58.2
gc-excelviewer|Gra|4.2.56
vscode-graphql|Gra|0.8.5
vscode-graphql-execution|Gra|0.1.7
vscode-graphql-syntax|Gra|1.0.6
todo-tree|Gru|0.0.224
terraform|has|2.25.4
vscode-git-tags|how|1.4.4
dart-data-class-generator|hzg|0.5.4
discord-vscode|icr|5.8.0
reg|ion|1.1.0
vscode-env|Iro|0.1.0
vscode-edit-csv|jan|0.7.3
hungry-delete|jas|1.7.0
svg|joc|1.5.0
cmake-language-support-vscode|jos|0.0.9
workspace-terminals|jos|0.3.2
blockman|leo|1.7.1
flutter-intl|loc|1.19.1
go-to-spec|Lou|0.1.3
call-graph|Luo|1.1.2
rainbow-csv|mec|3.5.0
vscode-language-babel|mgm|0.0.36
git-graph|mhu|1.30.0
import-sorter|mik|3.3.1
dotenv|mik|1.0.1
vscode-scss|mrm|0.10.0
vscode-docker|ms-|1.24.0
vscode-dotnet-runtime|ms-|1.6.0
remote-ssh|ms-|0.96.0
remote-ssh-edit|ms-|0.84.0
remote-wsl|ms-|0.75.3
cmake-tools|ms-|1.13.45
live-server|ms-|0.4.5
remote-explorer|ms-|0.2.0
test-adapter-converter|ms-|0.1.6
vsliveshare|ms-|1.0.5832
vsliveshare-pack|ms-|0.4.0
sqltools|mtx|0.27.1
php-docblocker|nei|2.7.0
gremlins|nho|0.26.0
react-proptypes-intellisense|OfH|1.0.3
docthis|oou|0.8.2
vscode-jest|Ort|5.2.3
vscode-versionlens|pfl|1.5.0
excalidraw-editor|pom|3.4.0
prisma|Pri|4.10.1
vscode-thunder-client|ran|2.5.0
typescript-hero|rbb|3.0.0
vscode-yaml|red|1.11.0
LiveServer|rit|5.7.9
flutter-riverpod-snippets|rob|1.2.1
vscode-coverage-gutters|rya|2.10.3
vscode-scss-formatter|sib|2.4.5
code-spell-checker|str|2.18.0
vscode-stylelint|sty|1.2.4
svelte-vscode|sve|107.1.2
sass-indented|syl|1.8.25
vscode-open-in-github|sys|1.17.1
vscode-status-bar-format-toggle|tom|3.1.1
cmake|twx|0.0.17
errorlens|use|3.7.0
vscode-icons|vsc|12.2.0
volar|Vue|1.2.0
vscode-todo-highlight|way|1.0.5
change-case|wma|1.0.0
markdown-pdf|yza|1.4.4
markdown-all-in-one|yzh|3.5.0
php-intellisense|zob|1.1.2

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
azure-dev_surveyone:30548225
pyindex848:30662994
nodejswelcome1cf:30587006
282f8724:30602487
pyind779:30662992
89544117:30613380
pythonsymbol12:30657548
a9j8j154:30646983
6233i204:30664135

```

</details>

![image](https://user-images.githubusercontent.com/416814/221742659-83154f7c-5c58-497d-8b4d-2f974d001a48.png)

**Comment by lszomoru** [comment]
This has been fixed recently. Please feel free to reopen if you are able to reproduce with the latest VS Code release.
