### ISSUE TITLE
Unable to remove statically forwarded ports

### ISSUE THREAD

**Issue by GreyWinds** [microsoft/vscode#175642]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.75.1
- OS Version: MacOS Ventura 13.2.1

Steps to Reproduce:

1.  Run a service inside a devcontainer
2.  From the devcontainer try to run a server on port localhost:8181
3.  Check the ports tab

There seems to be some automatic port forwarding happening on my machine. I am unable to hit localhost:8181 on which the service is actually supposed to be running. Besides that, there seems to be no option to remove the statically forwarded ports.
I have set Remote : Auto Forward ports to off in the settings, so the auto port forwarding shouldn't ideally be happening. If it is, there should be an option to remove these. 
![Untitled](https://user-images.githubusercontent.com/50285787/221849881-d09aa57d-d7e0-4971-9987-40f41192fde0.png)

Also, my devconatiner.json has "forwardPorts": [], I am not even sure where this port forwarding his happening from, but there should definitely be an option to edit this or remove them completely

**Comment by alexr00** [comment]
Statically forwarded ports come from the Dev Containers extension. IIRC, they are ports that are forwarded by docker.

**Comment by chrmarti** [comment]
These ports must be published in your `devcontainer.json` or `docker-compose.yml`. Once you remove them there, you will have to rebuild the container because these forwardings are static (this is a Docker feature, not something Dev Containers introduces).
