### ISSUE TITLE
Open In Code - context menu button in Explorer panel 

### ISSUE THREAD

**Issue by pechovic** [Microsoft/vscode#17568]
It would be very handy to have something like "Open In Code" button in the context menu in the Explorer panel in the VS Code to open selected folder in new instance of VS Code Editor.

_Case:_ When I have VS Code open for a folder that contains many subfolders each of which has another git repository set up and way too many files. I need sometimes open a subfolder quickly in another instance of VS Code for 2 main reasons:
* to have git support for particular repository
* to improve performance by running VS Code on smaller subset of files

I am aware that this could be at the moment accomplished by clicking on "Open In Terminal" button and then typing "code ." However, having a dedicated button "Open In Code" for this would be much better.

**Comment by bpasero** [comment]
@pechovic what about this: https://marketplace.visualstudio.com/items?itemName=chrisdias.vscode-opennewinstance ?

**Comment by pechovic** [comment]
@bpasero yes, this is what I was looking for. Thanks!
