### ISSUE TITLE
TODO: Word distance in `simpleCompletionModel.ts`

### ISSUE THREAD

**Issue by EyadTamer999** [microsoft/vscode#175645]
An unresolved TODO in file [src/vs/workbench/services/suggest/browser/simpleCompletionModel.ts](https://github.com/microsoft/vscode/blob/df931c994b402be615cb9fdf5ce20fde9dbfe8ad/src/vs/workbench/services/suggest/browser/simpleCompletionModel.ts) at  [Line 177](https://github.com/microsoft/vscode/blob/df931c994b402be615cb9fdf5ce20fde9dbfe8ad/src/vs/workbench/services/suggest/browser/simpleCompletionModel.ts#L177)

**Comment by Tyriar** [comment]
Please don't create issues like this.
