### ISSUE TITLE
Can't open, seems to have something to do with vscode

### ISSUE THREAD

**Issue by xxxiaoluo** [microsoft/vscode#175616]
![AM679 ((9DOCF{~8$7 YYK](https://user-images.githubusercontent.com/91597195/221755321-23a4fad2-756e-4cb8-8bea-aaf0328be916.png)

Version: 1.75.1
Commit: 441438abd1ac652551dbe4d408dfcec8a499b8bf
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36
Embedder: github.dev

**Comment by joyceerhl** [comment]
@xxxiaoluo Can you please provide the logs from the developer console when this happens?
