### ISSUE TITLE
python list output in Jupyter notebooks does not appear

### ISSUE THREAD

**Issue by jmagosta** [microsoft/vscode#175608]
Type: <b>Bug</b>

Jupyter notebook cells do not output lists. 

steps:
1. Create a new notebook x.ipynb
     Kernel Python 3.9.5
2. Enter list(range(5)) in the first cell and evaluate
3. The output pane is empty.  
4. Running the same at the terminal prompt returns the proper result. 

![image](https://user-images.githubusercontent.com/87355/221725579-8c1c3eae-0387-4e72-8077-1c72aa39ea84.png)

VS Code version: Code 1.75.1 (441438abd1ac652551dbe4d408dfcec8a499b8bf, 2023-02-08T21:32:34.589Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: No
Remote OS version: Linux x64 5.10.102.1-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz (8 x 2995)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|47.71GB (26.91GB free)|
|Process Argv|--crash-reporter-id b075abe4-909f-4851-8db8-f53aa02e8181|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 5.10.102.1-microsoft-standard-WSL2|
|CPUs|11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz (8 x 2995)|
|Memory (System)|23.33GB (19.31GB free)|
|VM|0%|
</details><details><summary>Extensions (30)</summary>

Extension|Author (truncated)|Version
---|---|---
vsc-python-indent|Kev|1.18.0
jupyter-keymap|ms-|1.0.0
vscode-ai-remote|ms-|0.24.0
remote-wsl|ms-|0.75.3
pdf|tom|1.2.2
vim|vsc|1.24.3
jinja|who|0.0.8
vscode-django|bat|1.10.0
databricks|dat|0.3.2
python-environment-manager|don|1.0.4
python-extension-pack|don|1.7.0
gc-excelviewer|Gra|4.2.56
vsc-python-indent|Kev|1.18.0
rainbow-csv|mec|3.5.0
isort|ms-|2022.8.0
python|ms-|2023.2.0
vscode-pylance|ms-|2023.2.40
jupyter|ms-|2023.1.2010391206
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.14
vscode-ai|ms-|0.26.0
vscode-jupyter-cell-tags|ms-|0.1.6
vscode-jupyter-slideshow|ms-|0.1.5
azure-account|ms-|0.11.3
autodocstring|njp|0.6.1
vscode-data-table|Ran|1.12.0
r|REd|2.7.1
intellicode-api-usage-examples|Vis|0.2.7
vscodeintellicode|Vis|1.2.30
jinja|who|0.0.8

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
azure-dev_surveyone:30548225
vscccc:30610679
pyindex848:30662994
nodejswelcome1cf:30587006
2e4cg342:30602488
pyind779:30671433
f6dab269:30613381
pythonsymbol12:30671437

```

</details>

**Comment by jmagosta** [comment]
Update:  This is caused by the "Data Table Renderers" Extension.  The grid renderer does not display list objects.

**Comment by rebornix** [comment]
@amunger is this possible affected by the scrollable output (I'm guessing by the screenshot)

**Comment by jmagosta** [comment]
I don't think there's any scrolling output here.
______________
John Mark Agosta
Palo Alto, CA
***@***.***

**Comment by amunger** [comment]
yeah that's how the Data Table Renderers renders output. 
It looks like that renderer just doesn't like arrays in plain text output.

Nothing we can do on this side though, that's the output that we receive from the kernel. If you click the three dot menu (on the left side of your screenshot) you can switch the renderer to the built-in one.
