### ISSUE TITLE
VSCode freezes up on Linux LXDE

### ISSUE THREAD

**Issue by faludigabor** [Microsoft/vscode#1756]
I seem to have a constant issue w/ Code since I updated to 0.10.6. 
What happens that the Code suddenly stops responding and the window never comes back to "maximised" state. 

I run in it on Linux LXDE , all I noticed that if Code is started in the background it exists back to the shell w/o any idication why. 

Where can I get it to tell me more what the issue is ? 

tx,
Gabor

**Comment by bpasero** [comment]
@faludigabor can you run code from the command line with "--verbose" and see if any output is printed and attach it here?

**Comment by mariusa** [comment]
Continuing discussion in #1940
