### ISSUE TITLE
Enable "find in selection" by default when replace executed against a multi-line selection

### ISSUE THREAD

**Issue by mfrost66** [Microsoft/vscode#17560]
When doing a replace (in current file) and there is a selection that spans lines, the "find in selection" ought to be enabled by default.

1.  I believe this is standard behavior in most other programmer's editors (visual studio, intellij, textpad++)
2.  Ignoring the current context (multiple line selection) when doing a search makes no sense - why else would the use have made the selection then pressed replace?
3. For me at least, its pretty rare that I want to do a global search/replace.  This is certainly the least likely use case

**Comment by rebornix** [comment]
We have a bunch of users who don't want to have this by default but we definitely can have a setting to define the default behavior, maybe named as `autoFindInSelection` or so. Let's track it in https://github.com/Microsoft/vscode/issues/15148.
