### ISSUE TITLE
provide commad to run last task again

### ISSUE THREAD

**Issue by tjx666** [microsoft/vscode#175614]
I think there should also be a context menu item.

![image](https://user-images.githubusercontent.com/41773861/221748139-c808fcfb-9dc8-485e-bf75-f83f1c8e0f40.png)

@Tyriar @meganrogge

**Comment by Tyriar** [comment]
That context menu only contains actions for the terminal currently, not tasks. I don't think this is a good enough reason to change that, especially since the context menu doesn't work sometimes (by design) depending on your OS
