### ISSUE TITLE
Changing working of  terminal.integrated.cwd setting

### ISSUE THREAD

**Issue by paragkatoch** [microsoft/vscode#175627]
The default behaviour of terminal in Vscode is that when we open the terminal its path will be as follows:-
1. No folder is open in editor: `~/`
2. Folder is open in editor: `path-to-folder/`

Now Vscode recently added a feature of `profiles` which is a great feature.

I want to setup a `work` profile and a `work` folder which contains all the stuff related to my work.

I also want my terminal location in `case 1` (mentioned above) to be `~/work`. This can be achieved using `terminal.integrated.cwd` setting.

But by using this, my terminal location in `case 2` will also be overridden to `terminal.integrated.cwd` value

What I want is that my terminal path should be as follows:-
1. No folder is open in editor: `value-of-terminal.integrated.cwd/`
2. Folder is open in editor: `path-to-folder/`

I didn't found any way to achieve this using existing settings, so some changed to the `terminal.integrated.cwd` working could make this behaviour possible.

Thanks for the help :)

**Comment by meganrogge** [comment]
this is currently not possible and is behaving as designed. @Tyriar any thoughts here?

**Comment by Tyriar** [comment]
Yes this is acting as designed and don't see a nice way to support this generally that would be discoverable and useful to most people. Here are some ideas you could try to get what you're after:

- Use ctrl+r "~/w" enter to quickly navigate to your work dir
- Create a profile that runs a subshell with its cwd set to `~/work` via the profile's `args`, optionally assign a keybinding to launch that specific profile
- Check if `$TERM_PROGRAM` is `vscode` in your `.bashrc` (or equivalent) and cd into `~/work` if needed
