### ISSUE TITLE
Tooltip breaks off and sticks around

### ISSUE THREAD

**Issue by digitarald** [microsoft/vscode#175669]
Seen during a live demo using Codespaces, a tooltip got stuck while the Codespace still initialized. Didn't have time or the opportunity to debug; but grabbed a screenshot:

![image](https://user-images.githubusercontent.com/8599/221911478-823cb99a-166e-43c7-b9c8-3287e94042e8.png)

**Comment by roblourens** [comment]
I feel like I have seen this once or twice too, but it would probably just be an electron/browser issue. No idea where to send this. Do you know anything about it @deepak1556?

**Comment by deepak1556** [comment]
Tooltip behavior comes from chromium, we had a similar issue which got addressed in upstream a while back https://bugs.chromium.org/p/chromium/issues/detail?id=1146981. If there is a reliable repro I can move this forward.
