### ISSUE TITLE
Add split box to Visual Studio Code

### ISSUE THREAD

**Issue by dgolub** [microsoft/vscode#175671]
It would be great if the scroll bar in Visual Studio Code had a split box that could be used to split the window into panes, like what exists in regular Visual Studio or various other Windows applications.
![Split Box](https://user-images.githubusercontent.com/5299/221917539-360248db-3c24-4388-971d-ffd9a5d6c9a9.png)

**Comment by bpasero** [comment]
We have this:

<img width="778" alt="image" src="https://user-images.githubusercontent.com/900690/221929767-6f60a4f4-5594-438f-bc58-2e5fd200880e.png">

**Comment by dgolub** [comment]
It's not the same thing.  Selecting that menu item open a second pane to the side, not below, which is very inconvenient when working with code that involves long lines.  Also, the split box is much more convenient than having to dig through the context menus.

**Comment by bpasero** [comment]
The split direction is configurable in settings:

<img width="800" alt="image" src="https://user-images.githubusercontent.com/900690/221949754-d40b5628-3743-4758-92fd-b8701cc3caf4.png">

You can assign a keybinding to the command to have it fast: `workbench.action.splitEditorOrthogonal`
