### ISSUE TITLE
Hovering info on the file item disables mouse action

### ISSUE THREAD

**Issue by junAtABQ** [microsoft/vscode#175691]
Type: <b>Feature Request</b>

When mouse pointer is on a file item, there is hovering info to tell if this item is tracked or not, or something containing emphasized items. That is fine, and not a problem in the VSC.
However, in the VSC Insider version, when this hovering info shows up, the mouse pointer action is prevented. So I cannot scroll, I cannot right click on that file item. I have to move the pointer to somewhere else and let the hovering info disappear and then scroll or right click on that file item.

VS Code version: Code - Insiders 1.76.0-insider (dc619de8d9efdabd781fc5658d0051813c347055, 2023-02-16T05:23:44.671Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: Yes
Remote OS version: Linux x64 5.15.0-60-generic

**Comment by lramos15** [comment]
Please update your insiders, you're on a version from February 16th.
