### ISSUE TITLE
light+ v2 - colors and contrast

### ISSUE THREAD

**Issue by ulugbekna** [microsoft/vscode#175696]
Since v2 is marked as experimental, I thought maybe we could discuss some color aspects, but feel free to close the issue if these things are settled, or if people don't share my opinion. 

I like how light+ v2 looks more modern than v1, but at the same time v2 seems less practical than v1: 

1. In v1, colors of menus offer easier navigation for eyes - status bar is blue and the sidebar menu is black, while currently things seem to blend together. May be this was intended for these menus to take less attention, then the 2nd point.
2. v2 seems "too bright" and seems to offer less contrast between text & background 

Thanks for a new modern light+ ! :-)

**Comment by li1234yun** [comment]
Personally, I think the color boundary is more natural than the line boundary.
Each favorite theme is different. Should v1 and v2 evolve at the same time?

Thanks for your work!

**Comment by ijager** [comment]
There is an issue in `Light+ V2` when search highlights a function. The text is not readable anymore due to low contrast.

![Screenshot 2023-03-31 at 16 06 41](https://user-images.githubusercontent.com/1840357/229143522-db6ceade-4df5-4154-83fd-49ade7b0fdb7.png)

**Comment by daviddossett** [comment]
@ijager that should have been fixed via https://github.com/microsoft/vscode/pull/175372. Are you on the latest version of VS Code?
