### ISSUE TITLE
XHR failed Unable to download and update plugins I have uninstalled and reinstalled

### ISSUE THREAD

**Issue by plume-cat** [microsoft/vscode#175630]
![image](https://user-images.githubusercontent.com/28625121/221796720-34a91957-ca53-47f7-8f10-34255250f13a.png)

![image](https://user-images.githubusercontent.com/28625121/221797153-b9dc2251-15c7-4369-a939-9f0dbc346ac5.png)

![image](https://user-images.githubusercontent.com/28625121/221797505-7155cb03-6c1d-4f50-a63e-f7ba2b9fe32e.png)

I don't know how to deal with it, it's completely unusable, it was still fine before

**Comment by sandy081** [comment]
Can you please open developer tools console and let us know what errors are you seeing for these requests?

- F1 > Developer: Toggle Developer Tools

**Comment by plume-cat** [comment]
thank you  , it woking when i close the proxy。
