### ISSUE TITLE
editor quick fix suggested when my focus is in the terminal

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#175672]
I'd expect these to hide when my focus is not in the editor

![Screenshot 2023-02-28 at 10 42 06 AM](https://user-images.githubusercontent.com/29464607/221919533-ce8bea71-5dda-4a3e-a100-0d88b3eaa5b4.png)

**Comment by mjbvz** [comment]
I think the current behavior makes sense since we still show the selection even when the editor is not focused. With this you can click on the lightbulb directly instead of having to focus back into the editor first
