### ISSUE TITLE
Spacebar button not working!!!!

### ISSUE THREAD

**Issue by CooderSky** [microsoft/vscode#175637]
Type: <b>Bug</b>

Tomorrow update my vscode and then my space button not working . 
it is show that - (space) was pressed. waiting for second kye of chord....
please microsoft team you can fix my problem fast . 

VS Code version: Code 1.75.1 (441438abd1ac652551dbe4d408dfcec8a499b8bf, 2023-02-08T21:32:34.589Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 3 5300U with Radeon Graphics          (8 x 2595)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|7.33GB (3.05GB free)|
|Process Argv|--crash-reporter-id 54b227d1-5982-428e-96b1-c5ffd55ff58b|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (18)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-html-css|ecm|1.13.1
el-vsc-product-icon-theme|ElA|0.1.8
vsc-material-theme-icons|equ|2.6.1
auto-close-tag|for|0.5.14
auto-rename-tag|for|0.1.10
code-runner|for|0.12.0
python|ms-|2023.2.0
jupyter|ms-|2023.1.2010391206
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.14
vscode-jupyter-cell-tags|ms-|0.1.6
vscode-jupyter-slideshow|ms-|0.1.5
cmake-tools|ms-|1.13.45
cpptools|ms-|1.14.3
cpptools-extension-pack|ms-|1.3.0
material-icon-theme|PKi|4.24.0
LiveServer|rit|5.7.9
cmake|twx|0.0.17

(5 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
azure-dev_surveyone:30548225
vscccc:30610679
pyindex848:30662994
nodejswelcome1:30587005
2e4cg342:30602488
pyind779:30671433
89544117:30613380
pythonsymbol12:30671437
vsctsb:30662444
vscodeenable:30660116
pythonb192:30669360

```

</details>

**Comment by IllusionMH** [comment]
Have you checked `keybindings.json` or all Keybinding settings to see if it has unintended bindings added? Remove them if exist.

Otherwise follow steps from https://github.com/microsoft/vscode/wiki/Keybinding-Issues

**Comment by CooderSky** [comment]
Thanks My Problem is solved.......❤️

**Comment by CooderSam** [comment]
Use Shift + Space for space on that time & after that reinstall your VSCode then I hope your bug will fix. Have a nice day.

**Comment by CooderSky** [comment]
> Use Shift + Space for space on that time & after that reinstall your VSCode then I hope your bug will fix. Have a nice day.

Thanks My Love... You are the only one solution for my all Problem ❤️😘😘😘😘

**Comment by CooderSam** [comment]
> > Use Shift + Space for space on that time & after that reinstall your VSCode then I hope your bug will fix. Have a nice day.
> 
> Thanks My Love... You are the only one solution for my all Problem ❤️😘😘😘😘

And you are my solution of every bug 😘❤️😋🥰😎😍🤩

**Comment by CooderSam** [comment]
> > Use Shift + Space for space on that time & after that reinstall your VSCode then I hope your bug will fix. Have a nice day.
> 
> Thanks My Love... You are the only one solution for all Problem ❤️😘😘😘😘
love you 2
