### ISSUE TITLE
SSH session content or WSL session content is not being recognized in the accessible terminal buffer

### ISSUE THREAD

**Issue by akash07k** [microsoft/vscode#175679]
Does this issue occur when all extensions are disabled?: Yes/No
Yes

- VS Code Version: 1.76.0-insider
- Commit: 92da9481c0904c6adfe372c12da3b7748d74bdcb
- Date: 2023-02-28T11:50:30.886Z
- OS Version: Windows 11 22.621.1265

Steps to Reproduce:

1. Open VS Code.
2. Open a terminal via `Control+` or Control+Shift+`.
3. create a SSH session or type "wsl" in the terminal editor (Make sure WSL is installed)
4. Type any command such as `ls` or `mkdir test` as soon as the SSH session or WSL instance opens up.
5. Notice, the output will be announced
6. Now move to the accessible terminal buffer by using Shift+Tab keystroke.
7. Try to navigate/read the content
8. Notice, the content of the SSH session or WSL will not be read out.

**Comment by akash07k** [comment]
I hope a fix for this lands soon.

**Comment by Tyriar** [comment]
@meganrogge I'm guessing this is already fixed.

**Comment by meganrogge** [comment]
yes, very old version. pls update VS Code
