### ISSUE TITLE
Implement copy and paste of whole files across workspaces

### ISSUE THREAD

**Issue by mrapczynski** [Microsoft/vscode#17564]
Platform: `OSX 10.11.6`
Version of Code: `1.8.1`

Often when I bootstrap new projects, I like to grab existing files like `.eslintrc` and `.gitignore` from other projects. I've noticed that I cannot right-click a file in one workspace, and paste it into a different directory tree in another workspace.

It would be great to have a cut, copy, and pasting of files across the clipboard in a future update. Particularly because getting hidden files to show up in OSX Finder is a pain.

**Comment by pageborn** [comment]
+1 , i also hope so, it would be useful, pasting files from local.

**Comment by foxundermoon** [comment]
+1 
 and global  drag drop to copy or move. 
make it configurable

**Comment by bpasero** [comment]
I think with the introduction of multi root workspaces this will become much easier. You can add multiple folders to a workspace and drag/drop or copy/paste files via explorer between all folders.
