### ISSUE TITLE
Previous state upon startup not restored

### ISSUE THREAD

**Issue by TheColorRed** [Microsoft/vscode#1757]
Have the ability to remember the previous state of the editor upon startup.

I used this with electron:

storage.js

    var app = require('app');
    var fs = require('fs');
    var path = require('path');
    var data = null;
    var dataFilePath = path.join(app.getPath('userData'), 'data.json');

    function load() {
        if (data !== null) {
            return;
        }

        if (!fs.existsSync(dataFilePath)) {
            data = {};
            return;
        }

        data = JSON.parse(fs.readFileSync(dataFilePath, 'utf-8'));
    }

    function save() {
        fs.writeFileSync(dataFilePath, JSON.stringify(data));
    }

    exports.set = function (key, value) {
        load();
        data[key] = value;
        save();
    }

    exports.get = function (key) {
        load();
        var value = null;
        if (key in data) {
            value = data[key];
        }
        return value;
    }

    exports.unset = function (key) {
        load();
        if (key in data) {
            delete data[key];
            save();
        }
    }

Then do something like this:

    var storage = require('storage');

    app.on('ready', function () {
        // Create the browser window.
        var lastWindowState = storage.get("lastWindowState");
        if (lastWindowState === null) {
            lastWindowState = {
                width: 1024,
                height: 768,
                maximized: false
            }
        }

        mainWindow = new BrowserWindow({
            x: lastWindowState.x,
            y: lastWindowState.y,
            width: lastWindowState.width,
            height: lastWindowState.height,
            minWidth: 800,
            minHeight: 600
        });

        mainWindow.on('close', function () {
            var bounds = mainWindow.getBounds();
            storage.set("lastWindowState", {
                x: bounds.x,
                y: bounds.y,
                width: bounds.width,
                height: bounds.height,
                maximized: mainWindow.isMaximized()
            });
        });
    });

**Comment by bpasero** [comment]
Please be specific what does not restore atm.

**Comment by TheColorRed** [comment]
@bpasero,

When editor starts it starts in what looks like 800x600. If I resize it to say 1280x762, then do my work and then close the editor, the next time it restarts it should load at 1280x762 and not 800x600. The same goes for fullscreen.

**Comment by bpasero** [comment]
@TheColorRed code keeps the size of the window including maximized state, but not full screen. If you can tell me some steps how to reproduce this, please update this bug.

**Comment by TheColorRed** [comment]
Ahh yes you are right, it is just when opening a window `File -> New Window`, there it doesn't open up to the previous state.

**Comment by bpasero** [comment]
@TheColorRed yes, if you want to restore multiple windows you can set `window.reopenFolders` to all. I am closing this one.
