### ISSUE TITLE
Stop 'Smart/Expand Selection' from selecting the surrounding quotes immediately

### ISSUE THREAD

**Issue by 0xNeu** [microsoft/vscode#175734]
This is a duplicate of #175605 because that one was prematurely closed since the contributor concluded it was an extension issue while it was not (see later comments in that issue)!

Users create issues here and they are best suited to determine if they are resolved, if you're going to close the issue they created at least run it through with them! I expected a little more professionalism from a multi-billion dollar company!

**Comment by jrieken** [comment]
Please don't duplicate issues. You still comment on closed issues and we still those comments. Thanks for keeping the overhead lean
