### ISSUE TITLE
How do I cancel the wavy line warning

### ISSUE THREAD

**Issue by pptfz** [microsoft/vscode#175738]
- VS Code Version:  1.75.1
- OS Version:  macOS ventura

How do I cancel the wavy line warning here

![iShot_2023-03-01_16 20 39](https://user-images.githubusercontent.com/44946546/222083300-ec8e4c9a-360e-4231-aa84-6b69de61636f.png)

**Comment by gjsjohnmurray** [comment]
Please use the Start Extension Bisect command to investigate whether the diagnostic is being contributed by one of your extensions. If it is, contact the extension author for advice.

**Comment by pptfz** [comment]
> Please use the Start Extension Bisect command to investigate whether the diagnostic is being contributed by one of your extensions. If it is, contact the extension author for advice.
Ok, thank you.
