### ISSUE TITLE
Not auto completing emmet

### ISSUE THREAD

**Issue by AbdullahAR-1904** [microsoft/vscode#175775]
Type: <b>Bug</b>

when i press cntl + space, it shows me the suggestions but then i press enter to auto complete the code, it moves to the next line instead of re writing the suggestion. Although it used to work fine before and some times it still does but not always. Also i am new to this IDE so i didnot change any settings at all. please help me. 

VS Code version: Code 1.75.1 (441438abd1ac652551dbe4d408dfcec8a499b8bf, 2023-02-08T21:32:34.589Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-10210U CPU @ 1.60GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|7.84GB (1.60GB free)|
|Process Argv|--crash-reporter-id a476e115-ee22-4e7e-a6b7-d0a9e43718ed|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (23)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-intelephense-client|bme|1.9.5
exe-runner|bra|0.2.1
composer-php-vscode|DEV|1.30.12484
phptools-vscode|DEV|1.30.12484
profiler-php-vscode|DEV|1.30.12484
vscode-html-css|ecm|1.13.1
prettier-vscode|esb|9.10.4
auto-rename-tag|for|0.1.10
code-runner|for|0.12.0
vscode-chatgpt|gen|3.8.2
live-server|ms-|0.4.5
java|red|1.15.0
LiveServer|rit|5.7.9
bootstrap4-vscode|the|6.1.0
vscode-java-debug|vsc|0.49.0
vscode-java-dependency|vsc|0.21.1
vscode-java-pack|vsc|0.25.8
vscode-java-test|vsc|0.38.1
vscode-maven|vsc|0.40.4
php-debug|xde|1.32.0
php-pack|xde|1.0.3
html-css-class-completion|Zig|1.20.0
php-intellisense|zob|1.1.2

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
pynewext54:30669237
azure-dev_surveyone:30548225
vsccc:30610678
pyindex848:30662994
nodejswelcome1cf:30587006
2e4cg342:30602488
pyind779:30671433
89544117:30613380
pythonsymbol12:30671437
showlangstatbar:30672706
vsctsb:30662444
pythonb192:30669360

```

</details>

**Comment by rzhao271** [comment]
It could be due to an extension. Let me know if [extension bisect](https://code.visualstudio.com/blogs/2021/02/16/extension-bisect) helps identify an extension causing the issue.
