### ISSUE TITLE
Find/replace: Keyboard shortcuts for "whole word" and "case" toggles only work in the search field

### ISSUE THREAD

**Issue by atombender** [Microsoft/vscode#17577]
Cmd-Alt-W (toggle whole word) and Cmd-Alt-C (toggle case sensitivity) only work in the editor and when the "Find" field has focus. They do not work in the "Replace" input, for example.

Which is annoying when you've typed what to find, have already tabbed to the "Replace" input, realize that the "whole word" toggle is on, and then try to toggle it back with Cmd-Alt-W, which doesn't work.

The keyboard shortcuts should work in _all_ of the panel's inputs.

**Comment by alexandrudima** [comment]
@atombender This works for me on Linux (where the keybinding is `alt+c`). Can you please search for `cmd+alt+c` in the keybindings and report here what entries there are. The command in question is `toggleFindCaseSensitive` and the entry should look like this:

```
{ "key": "alt+c",                 "command": "toggleFindCaseSensitive",
                                     "when": "editorFocus" },
```

i.e. when any editor is focused it should toggle.

**Comment by atombender** [comment]
I'm referring to the "Search" sidebar panel, not the little find box that pops up on `Cmd+F`. `Alt+Cmd+C` works fine in the latter. The former is defined as:


```
{ "key": "alt+cmd+c",             "command": "toggleSearchCaseSensitive",
                                     "when": "searchInputBoxFocus && searchViewletVisible" },
```

It would seem that `searchInputBoxFocus` is blocking it from working except in the first input box in that panel.
