### ISSUE TITLE
No audio cue when Terminal Command Failed set to on

### ISSUE THREAD

**Issue by roa-nyx** [microsoft/vscode#175799]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.76.0
- OS Version: Windows_NT x64 10.0.19045

Steps to Reproduce:

1. Go to settings, set `Audio Cues: Terminal Command Failed` to `on` instead of `auto`.
2. (optional) restart VS Code. (I don't think this is necessary but I thought I'd try it anyway when it didn't work immediately).
3. Open terminal (CMD) and type `ping a.xf.wef.wef.f` (or any other similarly invalid domain)

No audio cue is heard.

Note that I also tried `ping a.xf.wef.wef.f || echo FAILED` to ensure that `ping` does return a non-zero result (it echo'd "FAILED" to the console).

Maybe I'm missing something else?

[EDIT]

Forgot to mention that I did go to `Help: List Audio Cues` in the command palette and could hear the audio cues when I navigated between them. So it's not an issue with my speakers being muted or anything like that.

**Comment by meganrogge** [comment]
I'm not sure why this wouldn't work for you as it's working for me. You should hear the `error in line` audio cue - are you able to hear that in the `List Audio Cues` command quick pick?

**Comment by roa-nyx** [comment]
Yep, in the List Audio cues I can hear it. I don't have any screenreader attached. I assume you don't either in your testing.. Weird.. I'll try on another machine.

**Comment by roa-nyx** [comment]
Confirmed not working on another computer with 1.76.0 installed:

Version: 1.76.0 (user setup)
Commit: 92da9481c0904c6adfe372c12da3b7748d74bdcb
Date: 2023-03-01T10:22:44.506Z
Electron: 19.1.11
Chromium: 102.0.5005.196
Node.js: 16.14.2
V8: 10.2.154.26-electron.0
OS: Windows_NT x64 10.0.19044
Sandboxed: Yes

**Comment by meganrogge** [comment]
Strange. If you hover the command decoration, does it say the exit code?

**Comment by roa-nyx** [comment]
Sorry @meganrogge what is the "command decoration"?

**Comment by roa-nyx** [comment]
Hey @meganrogge so I decided to try the powershell terminal today, and it worked there!

Is it possible that the cmd terminal is simply not supported yet? In your testing were you maybe running the powershell terminal?

**Comment by meganrogge** [comment]
Yes we don't have shell integration support for command prompt
