### ISSUE TITLE
Configure default log level can't persisted across restarts

### ISSUE THREAD

**Issue by tjx666** [microsoft/vscode#175787]
https://user-images.githubusercontent.com/41773861/222246151-1fd14214-3589-4b36-aaab-3d64e1e41a62.mov

@sandy081 

Versions:

```
Version: 1.76.0 (Universal)
Commit: 92da9481c0904c6adfe372c12da3b7748d74bdcb
Date: 2023-03-01T10:23:45.993Z
Electron: 19.1.11
Chromium: 102.0.5005.196
Node.js: 16.14.2
V8: 10.2.154.26-electron.0
OS: Darwin x64 22.3.0
Sandboxed: No
```

**Comment by sandy081** [comment]
<img width="735" alt="default-log-level" src="https://user-images.githubusercontent.com/10746682/222361842-d86b54c8-c62f-4889-853b-147afc85c548.png">

You have to use the button on the right to change the default log level.
