### ISSUE TITLE
Setting --max-memory does not increase the heap size extensions can use

### ISSUE THREAD

**Issue by c3-kaspesi** [microsoft/vscode#175792]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 
- OS Version: 

Steps to Reproduce:

1.  Launch vscode with code --max-memory=8192 .
2. Printing the results of `v8.getHeapStatistics().heap_size_limit` in an extension process shows 4096 instead of 8192.

This seems to be the only way vscode exposes to increase the heap size but does not seem to work.

**Comment by c3-kaspesi** [comment]
In addition, how does VSCode allocate memory to extensions?  I am seeing loading a ~200MB file into an in memory buffer and then stringifying it is causing my extension to crash vscode due to running out of heap memory.

**Comment by c3-kaspesi** [comment]
Looking into this further, it seems that VSCode cannot allocate more than 4096Mb of heap space due to Electrons pointer compression.  Is this correct, and if so why isn't there a notification similar to when you try to set `--max-memory` < 2048Mb

**Comment by deepak1556** [comment]
> Looking into this further, it seems that VSCode cannot allocate more than 4096Mb of heap space due to Electrons pointer compression

Not Electron but V8 pointer compression, V8 heap size in a process is capped to 4GB https://v8.dev/blog/v8-release-92#shared-pointer-compression-cage. However, you can allocate off the heap buffers (TypedArrays) which can be upto 8-10GB (might be more in recent versions depending on the platform).

>  if so why isn't there a notification similar to when you try to set --max-memory < 2048Mb

Agreed, but I am also not sure if the flag serves purpose when the upper limit cannot be changed. @alexdima should we remove the flag instead ?

**Comment by phillipb** [comment]
@deepak1556, would this mean that things like tsserver are not currently able to use more than 4GB of memory?

**Comment by deepak1556** [comment]
`max-memory` option has been removed with https://github.com/microsoft/vscode/commit/6d5b85427d99e77092a3621dbace765247b5271a

@phillipb I would suggest to open an issue against the TS server extension for any UI changes.
