### ISSUE TITLE
AI-powered code formatter that learns from our existing codebase

### ISSUE THREAD

**Issue by martinszeltins** [microsoft/vscode#175730]
Code formatting has always been a challenging and a controversial topic. Prettier for example is a very "opinionated" formatter that you have to configure.

But what if we could use the power of AI to automatically scan our code and format the code according to what the rest of our codebase looks like? What if AI could learn in an intelligent way the way in which we prefer to format our code by looking at our existing codebase and then the AI could make up its rules based on that context?

That would mean that we do not have to create all these formatter rules (besides it is not always possible to use rules to tell the formatter exactly how I want to format the code, it needs to be "felt") and we could simply start formatting our code the way we want and allow the AI to learn from it and apply the exact same formatting style as we have been using throughout our codebase.

I think it's time for AI to redefine code formatting. This would be a great feature.

**Comment by jrieken** [comment]
We are on the same page here but the question is if this is something that should be built-in to VS Code or come via an extension. Given that most powerful AI models use some (paid) external service it's best to have this as extension. Better: our formatter API should allow for this already. In the end it is just a matter of analysing (fs.readFile) a workspace and providing formatting edits when being asked so. 


Hence, closing this as extension-candidate and eager to see this happening
