### ISSUE TITLE
The code helper occupies too much CPU

### ISSUE THREAD

**Issue by cuihaoweb** [microsoft/vscode#175749]
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/58589917/222151415-2d242b9c-53d2-4fc5-88c0-c9555be2ebf3.png">

**Version information is as follows:**
- vscode: 1.75.1
- system: MacBook Pro (13-inch, M1, 2020)

Each time occupies too high memory, resulting in vscode is very slow, slow。Even slower than webstorm。I forced the code helper process to shut down, but it would immediately reopen, still using a lot of cpu。

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

**Comment by cuihaoweb** [comment]
@mjbvz vscode's high cpu usage was definitely resolved when I disabled all the plugins, but I also lost the ability to use vscode plugins. I would like to see if there is a mechanism to help developers automatically block resource consuming plugins and notify the corresponding authors to fix them.

**Comment by cuihaoweb** [comment]
<img width="1170" alt="image" src="https://user-images.githubusercontent.com/58589917/222306373-c39207e7-5fa8-4ddf-9fb1-c420240c8723.png">

I seem to have found a plug-in that uses too much cpu memory. When I open the `Vue Language Features (Volar)` official vue plug-in, code helper's memory usage immediately spikes, which makes me question the official capabilities of vue

**Comment by mjbvz** [comment]
Great. Please start by filing an issue against that extension
