### ISSUE TITLE
Need VSCode for Web to expose a FIXED proxy endpoints which can let extensions sent request through this, rather than a dynamic domain

### ISSUE THREAD

**Issue by realDuang** [microsoft/vscode#175735]
I'm trying to build an vscode web extension which needs send requests on vscode.dev, but I found that the request are always from a dynamic cdn domain, like: 'https://xxx.vscode-cdn.net'.

In some services, It may not support a pan-domain origins in their CORS whitelist due to security considerations.

So I wonder is there any way to expose a Fixed Proxy Endpoints​, so that when the extension sends requests, it can also be sent through this endpoint, not just from a cdn domain.

**Comment by realDuang** [comment]
Kindly ping. 
I think it make sense to expose a fixed proxy domain to send requests, like vscode's auth feature, it use proxy to access aad login. Or if you have more consideration, please share with me.

**Comment by joaomoreno** [comment]
Sadly, no. We purposefully want a dynamic origin at all times. I suggest following up on the 3rd party service and have them implement wildcard CORS support.
