### ISSUE TITLE
Terminal first line is broken after scale

### ISSUE THREAD

**Issue by Meeeeow** [Microsoft/vscode#17579]
- VSCode Version: 1.8.1
- OS Version: Windows 10 Version 1607

Steps to Reproduce:

1.  A Hi-DPI screen with 125% scale
2.  Press Ctrl + "+" to zoom VSCode
3.  Open terminal

![snipaste20161220_113022](https://cloud.githubusercontent.com/assets/19658647/21337469/6db2b6f4-c6a8-11e6-876b-6986f6cf3ed8.png)

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/14479
