### ISSUE TITLE
Hot exit causes VSCode reopened

### ISSUE THREAD

**Issue by ZCShou** [Microsoft/vscode#17572]
- VSCode Version: Code - Insiders 1.9.0-insider (95fa5500ee397c21be13581b9a987f0b644c0be5, 2016-12-19T07:11:43.094Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

|Extension|Author|Version|
|---|---|---|
|githistory|donjayamanne|0.1.4|
|output-colorizer|IBM|0.0.8|
|cpptools|ms-vscode|0.9.3|
|vscode-icons|robertohuertasm|4.2.0|

---
Steps to Reproduce:

1.  change an file and don't save, then close vscode
2.  open another exsited file
![1](https://cloud.githubusercontent.com/assets/8591065/21334518/3b353914-c693-11e6-8a5b-30e85939e59e.gif)

**Comment by bpasero** [comment]
This works as designed, we restore your previous work when you restart.
