### ISSUE TITLE
Improve import complete messaging and discoverability for Profiles 

### ISSUE THREAD

**Issue by cwebster-99** [microsoft/vscode#175776]
In user studies, we received feedback from participants that they were "confused where the profile went" once they imported it as the profile content and tab would disappear from the activity bar and explore panel. They also struggled to identify if the profile had been successfully installed and whether or not they were currently using it. In some cases, the user would import the profile a second time and receive a message to overwrite the already existing profile, at which point they knew it was imported. Participants resolved to trying to  write and run a Python file in order to test if the profile was imported and being used. 

User studies were done on version 1.75 of VS Code.

**Comment by isidorn** [comment]
@cwebster-99 thanks for running that user study and thanks for providing this feedback.

We have added badges to the Settings gear. Do you think that would help?
Apart from that are there other things that you think we could do to improve the user experience here?

**Comment by isidorn** [comment]
We have done some work that should help here. Closing for now, and if we hear more user feedback we can reconsider our options.
@cwebster-99 also let us know if there are still some things we can do here. thank you
