### ISSUE TITLE
Intellisense with TypeScript : too many unrelated suggestions.

### ISSUE THREAD

**Issue by electrotype** [Microsoft/vscode#17573]
- VSCode Version: 1.8.1
- OS Version: Windows 7

Steps to Reproduce:

1. From a first module, export an instance of a TypeScript class which contains getters and methods.
2. Import this instance in another module.
3. Also import 4-5 other unrelated modules.
4. Use a dot to trigger intellisense on the instance from the first module.

Result : too many unrelated suggestions are displayed.

Intellisense doesn't help enough. When using it on the instance of a class, I want to see _the getters and the methods of this instance first_. I don't care about available imports that are unrelated to the object.

For example :
![](http://i.imgur.com/ZcY8k3v.png)

Here, I'd like to see the `dir` and `humanReadableInConsole` getters _first_. Those are defined on the class `configs.logging` is an instance of. In fact, I'd only like to see those! All the other suggestion before those two getters are unrelated to the object.

Is there a configuration to tweak this?

**Comment by electrotype** [comment]
Sorry, this is a false alarm. The "problem" (feature??) was in fact introduced by an extension, [auto-import](https://marketplace.visualstudio.com/items?itemName=steoates.autoimport).

Please close this issue!

**Comment by waderyan** [comment]
No problem. Thank you for letting us know.
