### ISSUE TITLE
`Settings Sync: Show Log` doesn't show settings sync log

### ISSUE THREAD

**Issue by andreamah** [microsoft/vscode#175779]
1. Run `Settings Sync: Show Log` 
2. Goes to `Docker` output channel. :bug:
![Recording 2023-03-01 at 10 41 34](https://user-images.githubusercontent.com/31675041/222234775-a9921068-556a-4c7c-8864-6929d925c4cc.gif)

**Comment by sandy081** [comment]
It is working for me. 

- Which version of VS Code are you on?
- Is the Settings Sync log exists in the output view?

**Comment by andreamah** [comment]
Hmm, it seems to be working for me now. I'll re-open if I see it again.
