### ISSUE TITLE
[scss] don't offer html tags inside rule sets.

### ISSUE THREAD

**Issue by leighkendell** [Microsoft/vscode#17578]
- VSCode Version: 1.8.1
- OS Version: macOS 10.12.2

Steps to Reproduce:

1. Edit a SCSS file
2. Observe quick suggestions when typing a CSS property

When typing a property in a SCSS file the suggestions shown also include HTML elements like "h1, h2, p" etc. This is not the same behaviour as when editing CSS or LESS files.

**CSS File**
![image](https://cloud.githubusercontent.com/assets/765486/21336580/5761ef52-c6a1-11e6-9889-3cdec2fa1473.png)

**SCSS File**
![image](https://cloud.githubusercontent.com/assets/765486/21336629/98327704-c6a1-11e6-8b67-1d2ecab91d4e.png)

Is it possible to prevent this behaviour in SCSS files?

**Comment by aeschli** [comment]
That's because of nested rulesets in SCSS.
```
div {
  span {
     color: red;
  }
}
```
selects all spans inside divs.

There's currently no way of blocking such proposals.

**Comment by leighkendell** [comment]
I understand that @aeschli but I still find it weird that it's offering quick suggestions for elements at all inside an SCSS file. I actually thought Atom didn't do this but it turns out it does, perhaps it would make more sense to change the ordering so that all CSS properties show before element suggestions?
