### ISSUE TITLE
Appearence - centered

### ISSUE THREAD

**Issue by superchrisho** [microsoft/vscode#175824]
Type: <b>Bug</b>

With latest update:
View > Appearence > Centered Layout

No code is visible. Turn off centered layout, code reappears.

VS Code version: Code 1.76.0 (Universal) (92da9481c0904c6adfe372c12da3b7748d74bdcb, 2023-03-01T10:23:45.993Z)
OS version: Darwin x64 22.3.0
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz (8 x 3600)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|3, 5, 4|
|Memory (System)|16.00GB (0.03GB free)|
|Process Argv|--crash-reporter-id 7f212924-c5e8-4f60-b633-c93bd7f0ac28|
|Screen Reader|yes|
|VM|0%|
</details><details><summary>Extensions (82)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|3.0.2
codesnap|adp|1.3.4
TabOut|alb|0.2.2
Bookmarks|ale|13.3.1
swagger-viewer|Arj|3.1.2
vscode-icontheme-nomo-dark|be5|1.3.6
markdown-preview-github-styles|bie|1.0.1
blackbox|Bla|0.10.34
npm-intellisense|chr|1.4.4
path-intellisense|chr|2.8.4
regex|chr|0.4.0
codesandbox-projects|Cod|0.2.71
vscode-eslint|dba|2.4.0
denigma|den|0.0.15
gitlens|eam|13.3.1
vscode-html-css|ecm|1.13.1
vsc-material-theme|Equ|33.6.0
vsc-material-theme-icons|equ|2.6.1
prettier-vscode|esb|9.10.4
auto-close-tag|for|0.5.14
auto-rename-tag|for|0.1.10
remotehub|Git|0.52.0
todo-tree|Gru|0.0.224
terraform|has|2.25.4
vscode-drawio|hed|1.6.6
vscode-auto-open-markdown-preview|hnw|0.0.4
vscode-codemetrics|kis|1.26.1
auto-insert-comma|Leo|0.0.4
json-to-ts|Mar|1.7.5
markdown-shortcuts|mdi|0.12.0
template-string-converter|meg|0.6.0
git-graph|mhu|1.30.0
dotenv|mik|1.0.1
document|min|2.2.1
vscode-scss|mrm|0.10.0
vscode-edge-devtools|ms-|2.1.1
isort|ms-|2022.8.0
python|ms-|2023.4.0
vscode-pylance|ms-|2023.2.40
jupyter|ms-|2023.2.1000592019
jupyter-keymap|ms-|1.1.0
jupyter-renderers|ms-|1.0.15
vscode-jupyter-cell-tags|ms-|0.1.6
vscode-jupyter-slideshow|ms-|0.1.5
remote-ssh|ms-|0.96.0
remote-ssh-edit|ms-|0.84.0
azure-repos|ms-|0.28.0
remote-explorer|ms-|0.2.0
remote-repositories|ms-|0.30.0
vscode-react-native|msj|1.10.0
color-highlight|nau|2.5.0
indent-rainbow|ode|8.3.1
material-icon-theme|PKi|4.24.0
material-product-icons|PKi|1.5.0
vscode-react-refactor|pla|1.1.3
vscode-css-peek|pra|4.2.0
vscode-yaml|red|1.11.0
LiveServer|rit|5.7.9
synthwave-vscode|Rob|0.1.15
color-manager|roy|0.7.5
svg-preview|Sim|2.8.3
music-time|sof|2.2.43
autoimport|ste|1.5.4
code-spell-checker|str|2.18.0
tabnine-vscode|Tab|3.6.41
sapling|tea|1.2.0
open-in-browser|tec|2.0.0
dotenv-intellisense|tem|0.0.4
pdf|tom|1.2.2
highlight-matching-tag|vin|0.10.1
intellicode-api-usage-examples|Vis|0.2.7
vscodeintellicode|Vis|1.2.30
codetour|vsl|0.0.58
quokka-vscode|Wal|1.0.527
footsteps|Wat|0.2.0
fig|wit|0.0.7
vscode-import-cost|wix|3.3.0
codesandbox|yes|0.0.8
markdown-all-in-one|yzh|3.5.0
json|Zai|2.0.2
material-theme|zhu|3.15.6
html-css-class-completion|Zig|1.20.0

(17 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
azure-dev_surveyone:30548225
vsccc:30610678
pyindex848:30662994
nodejswelcome1:30587005
3biah626:30602489
pyind779:30671433
f6dab269:30613381
pythonsymbol12:30671437
a9j8j154:30646983
pythonb192:30669360

```

</details>

**Comment by sbatten** [comment]
duplicate #175795
