### ISSUE TITLE
Built in webview incompatible with zoom

### ISSUE THREAD

**Issue by Meeeeow** [Microsoft/vscode#17580]
- VSCode Version: 1.8.1
- OS Version: Windows 10 Version 1607

Steps to Reproduce:

1. May require a Hi-DPI screen with 125% scale?
2. Press Ctrl + "+" zoom Code
3. Open release note or markdown preview

![snipaste20161220_120835](https://cloud.githubusercontent.com/assets/19658647/21338049/833593ac-c6ad-11e6-9ab0-1d176833639f.png)

**Comment by jrieken** [comment]
dupe #5745
