### ISSUE TITLE
Unable to run multiple Java files with Red Hat Java extension

### ISSUE THREAD

**Issue by GregoryLi360** [microsoft/vscode#175887]
- VS Code Version: 1.76.0
- OS Version: MacOS 13.1

Steps to Reproduce:

1. Install Red Hat Java extension
2. Click the run button in the top right
3. Select which Java file to run
4. Click the run button again

Current Behavior:
The same selected file runs over and over again, even when running in a file with a main method.

Expected Behavior (pre-update): 
You are allowed to select which file to run again, or if the current file has a main method, it is ran instead.

**Comment by roblourens** [comment]
Please file this issue on the Java extension
