### ISSUE TITLE
Scroll by wheel breaks after scroll by mmb click

### ISSUE THREAD

**Issue by drLemis** [microsoft/vscode#175877]
Does this issue occur when all extensions are disabled?: **Yes**

- VS Code Version: 1.76.0 and 1.76.0-insiders
- OS Version: Windows 10

Steps to Reproduce:

1. Start scroll mode by clicking middle mouse button
2. Move mouse to scroll
3. End scroll mode by clicking middle mouse button (left mouse button will not trigger bug)
4. **Not moving mouse after that**, start middle mouse click scroll mode and end it immediately without moving mouse
5. Usual scroll by using scroll wheel rotation will not work after that, unless you move mouse, use PgUp/PgDn or arrows, open palette, or in any way change or refresh page

Reproduced with and without extensions. Insiders install is fresh and clean, made for this bugreport only.

Here is two videos. Yellow circle is left mouse button click, blue circle - middle mouse button click. Scrollwheel rotation is unfortunately invisible, but I've put giant red text where I'm using it and it's not working.

Bug in usual VSCode:

https://user-images.githubusercontent.com/5266332/222414773-c5239243-b350-4aee-9128-02f63c0ea816.mp4

Bug in VSCode Insiders:

https://user-images.githubusercontent.com/5266332/222414780-73effbfd-1958-4499-b240-f7172a76e6ed.mp4

**Comment by drLemis** [comment]
Update: Sometimes it's not updating cursor visual. In [this video](https://user-images.githubusercontent.com/5266332/222421800-c45d5af0-a7f4-4107-b9b0-33ea9a5a2692.mp4) scroll mode is disabled after second click, but cursor icon says otherwise.

**Comment by alexdima** [comment]
The editor doesn't scroll when holding the middle mouse button and moving the mouse. That is tracked at https://github.com/microsoft/vscode/issues/6302 . From the screen recordings, this looks to be about scrolling in webviews.

**Comment by csicky** [comment]
> The editor doesn't scroll when holding the middle mouse button and moving the mouse. That is tracked at #6302 . From the screen recordings, this looks to be about scrolling in webviews.

Any plans on fixing #6302 ... ever?
