### ISSUE TITLE
Changes in file are not tracked

### ISSUE THREAD

**Issue by vamshi9172** [microsoft/vscode#175854]
Type: <b>Bug</b>

Open vs code .
select a Folder and open any file
start making changes.
Changes are not tracked (blue line when modified, green when a line added)
previously it was working fine, I havent changed any settings nor installed anything. It suddenly stopped working

VS Code version: Code 1.76.0 (92da9481c0904c6adfe372c12da3b7748d74bdcb, 2023-03-01T10:22:44.506Z)
OS version: Windows_NT x64 10.0.22000
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz (8 x 1805)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.73GB (19.35GB free)|
|Process Argv|--crash-reporter-id 330ae306-d6b8-4cf6-aea1-d38c0abf2ffc|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (23)</summary>

Extension|Author (truncated)|Version
---|---|---
filewatcher|app|1.1.7
vscode-perforce|bam|1.1.3
vscode-perforce-simple|cal|1.0.1
vscode-eslint|dba|2.4.0
githistory|don|0.6.19
xml|Dot|2.5.1
gitlens|eam|2023.3.204
SuiteSnippets|eri|2020.2.0
prettier-vscode|esb|9.10.4
perforce|mjc|4.15.5
live-server|ms-|0.4.5
suitecloud-vscode-extension|Ora|1.3.2
java|red|1.15.0
LiveServer|rit|5.7.9
vscode-coverage-gutters|rya|2.10.3
openinperforce|san|1.0.7
intellicode-api-usage-examples|Vis|0.2.7
vscodeintellicode|Vis|1.2.30
vscode-java-debug|vsc|0.49.0
vscode-java-dependency|vsc|0.21.1
vscode-java-pack|vsc|0.25.8
vscode-java-test|vsc|0.38.1
vscode-maven|vsc|0.40.4

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627cf:30244335
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
azure-dev_surveyone:30548225
pyindex848:30662994
nodejswelcome1cf:30587006
3biah626:30602489
pyind779:30671433
89544117:30613380
pythonsymbol12:30671437
a9j8j154:30646983
vsctsb:30662444
pythonb192:30669360
funwalk2cf:30676044

```

</details>

**Comment by lszomoru** [comment]
This is something that we have addressed in upcoming recovery releases - 1.76.1, 1.76.2. I will go ahead and optimistically close this issue, but please feel free to reopen it in case you are still able to reproduce the problem. Thanks!
