### ISSUE TITLE
vscode-server crashes, if there is no network interface with a valid mac address present

### ISSUE THREAD

**Issue by weberdigital** [microsoft/vscode#175878]
Type: <b>Bug</b>

I am trying to connect to a container running on one of our servers. The server is running AlmaLinux release 8.7 (Stone Smilodon). On the server, we use container virtualization using Virtuozzo release 7.5.4 (465).

If I try to connect directly to the container using the remote-ssh package, I have no success. This worked before the update to VSC 1.76.0.

I found out, that the vscode-server process crashed. I found this log in the container: /var/www/vhosts/dev3.weber.digital/.vscode-server/data/logs/20230302T090301/remoteagent.log
```
2023-03-02 09:03:01.655 [info] Extension host agent started.
2023-03-02 09:03:01.677 [error] Error: Unable to retrieve mac address (unexpected format)

Error: Unable to retrieve mac address (unexpected format)
    at I (/var/www/vhosts/dev3.weber.digital/.vscode-server/bin/441438abd1ac652551dbe4d408dfcec8a499b8bf/out/vs/server/node/server.main.js:63:3450)
    at y (/var/www/vhosts/dev3.weber.digital/.vscode-server/bin/441438abd1ac652551dbe4d408dfcec8a499b8bf/out/vs/server/node/server.main.js:74:8267)
    at async /var/www/vhosts/dev3.weber.digital/.vscode-server/bin/441438abd1ac652551dbe4d408dfcec8a499b8bf/out/vs/server/node/server.main.js:74:8124
    at Timeout._onTimeout (/var/www/vhosts/dev3.weber.digital/.vscode-server/bin/441438abd1ac652551dbe4d408dfcec8a499b8bf/out/vs/server/node/server.main.js:8:12)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
```

The first entry in the stack trace corresponds to this line: https://github.com/microsoft/vscode/blob/main/src/vs/base/node/macAddress.ts#L32

The cause of this issue is, that Virtuozzo container do not have a valid mac address. They have a loopback network interface with the mac address 00:00:00:00:00:00 and an interface "venet0", which does not have a mac address. This is normal, because the network traffic is handled by the host and not by the container itself.

Because of this, the function `getMac` in https://github.com/microsoft/vscode/blob/main/src/vs/base/node/macAddress.ts throws the exception 'Unable to retrieve mac address (unexpected format)'. The function `getMac` gets called by the function `getMacMachineId` in https://github.com/microsoft/vscode/blob/main/src/vs/base/node/id.ts#L96. There the exception is catched, but the function `errors.onUnexpectedError` throws an exception itself, which does not get catched, I guess.

After patching this if statement in the minified javascript code on our server, to always evaluate to true, I was able to successfully connect to and use the vscode-server: https://github.com/microsoft/vscode/blob/main/src/vs/base/node/macAddress.ts#L25 . This is of course not the solution to this bug, but just a workaround for us, that we will use, until this bug is fixed.

VS Code version: Code 1.76.0 (92da9481c0904c6adfe372c12da3b7748d74bdcb, 2023-03-01T10:22:44.506Z)
OS version: Windows_NT x64 10.0.19045
Modes:
Sandboxed: No
Connection to 'SSH: dev3.weber.digital' could not be established  WebSocket close with status code 1006

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4570 CPU @ 3.20GHz (4 x 3193)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: unavailable_off<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.94GB (8.65GB free)|
|Process Argv|. --crash-reporter-id 755bb794-523c-4fa1-9a88-9392b71f1a53|
|Screen Reader|no|
|VM|0%|

Connection to 'SSH: dev3.weber.digital' could not be established  WebSocket close with status code 1006
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscoreces:30445986
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vscaac:30438847
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
pynewvextcfv2:30669238
azure-dev_surveyone:30548225
vscccc:30610679
pyindex848:30662994
nodejswelcome1:30587005
2e4cg342:30602488
pyind779:30671433
89544117:30613380
pythonsymbol12:30671437
a9j8j154:30646983
vsccsb:30662443
vscodeenable:30660116

```

</details>

**Comment by kamopeter** [comment]
Hello there!
Similar issue here.
I use macOS and also use 1.76.0
Since yesterday I can't connect remotely to one of my vps.
A half years ago everyday used this remote host, but yesterday evening (here in Hungary), all broke down.
I can connect, but after I type password, it's ask another password, and another...
It is so confusing, 'cause this tool what I use every day.
Plese help me with that.

**Comment by kamopeter** [comment]
s

> And sorry where can I find this file, where I can modify to work?

**Comment by kamopeter** [comment]
It works! 👍 
Thanks [weberdigital](https://github.com/weberdigita), you saved my life.

**Comment by combssm** [comment]
This worked for me.  Was experiencing the exact same issue on a similar environment.

**Comment by TheItsNameless** [comment]
Got the same issue, solved for me as well! 

Is there a fix to be expected?

**Comment by aeschli** [comment]
@sandy081 I don't see any other changes than https://github.com/microsoft/vscode/commit/11fcbd051ad22bde4f7b22ebee8e0158d77cb7c9 that could have caused that

**Comment by aeschli** [comment]
Thanks @weberdigital for the analysis. Here's what I think happend

`getMachineId` uses `errors.onUnexpectedError` if there's a problem. It throws the error in a timeout.
The unexpected error handler is only set after the first invocation of `getMachineId`:
 - when the telemetry service is initialised
 - again after all the services are set.

The change https://github.com/microsoft/vscode/commit/11fcbd051ad22bde4f7b22ebee8e0158d77cb7c9 moved the code that evaluates the machine id a few statements up inside a `Proises.all`. That must have surfaced that problem.

The fix is to set the unexpected error handler as a first thing. First it uses `console.error and collects all errors`. then it uses the log service, once available

**Comment by aeschli** [comment]
1.75 candidate fix: https://github.com/microsoft/vscode/pull/176368

**Comment by sandy081** [comment]
Thanks @aeschli for the fix

**Comment by rzhao271** [comment]
PR LGTM. I verified that remote SSH works, but I'm not sure how to set up a config that triggers the error handler.
