### ISSUE TITLE
Let Profile badges be formatted in user config (not only theme)

### ISSUE THREAD

**Issue by davidsneighbour** [microsoft/vscode#175889]
The new [profile badge feature](https://code.visualstudio.com/updates/v1_76#_profile-badge) is nice, but it turns out, the design is only configurable from within a theme. It would be very nice to configure it independent of the theme in the user config. This could let me have a red button for certain projects (commercial) and a green one for others (private?) or even more differentiation of the current setup.

**Comment by gjsjohnmurray** [comment]
Can't you use the information at https://code.visualstudio.com/api/references/theme-color to customize it in the profile?

**Comment by davidsneighbour** [comment]
Oh. I completely blanked that out and registered it as "it needs to be it's own theme". That obviously is not an issue then, sorry ;)
