### ISSUE TITLE
VS Code 1.76.0 release notes have broken images and videos

### ISSUE THREAD

**Issue by TomasHubelbauer** [microsoft/vscode#175855]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.76.0
- OS Version: macOS Ventura 13.2.1

Steps to Reproduce:

1. Update VS Code to the currently latest version 1.76.0
2. View the release notes once VS Code installs the update and restarts
3. Notice some of the videos and images in the release notes that pop up are boken:

- Profile Badge section image
- Configure default log level section image
- Verified publisher domain in Extension editor section image
- VS Code for the web section video
- Extensions section "Before" image
- Python section video

Note that on the web (https://code.visualstudio.com/updates/v1_76) the release notes seem to have the same issue.

**Comment by gjsjohnmurray** [comment]
These are all working for me. Which browser did you view the we copy in?

**Comment by TomasHubelbauer** [comment]
Firefox 110.0 in terms of the desktop browser experience, but the same exact assets are missing in VS Code as the browser.

**Comment by gjsjohnmurray** [comment]
Maybe a transient problem with getting images/videos? I used the same FF version (though on Windows) and it worked, but did seem slow to serve the page initially.

**Comment by gjsjohnmurray** [comment]
With FF DevTools open and on the Network tab, Ctrl+F5 of the web copy sometimes reports NS_BINDING_ABORTED on a few of the .mp4 files, but they subsequently load successfully.

**Comment by TomasHubelbauer** [comment]
Looks like you're right, I checked the web version again and it seems to work now. I closed the release notes in VS Code and used Help > Show Release Notes to reload it and from a quick glance it seems okay there as well now.
