### ISSUE TITLE
Could you create an undo close tab?

### ISSUE THREAD

**Issue by soljohnston777** [Microsoft/vscode#17582]
Just like in web browsers for that current session.  Could you create an undo close tab to reopen the file you just closed?

**Comment by bpasero** [comment]
It exists: 

![image](https://cloud.githubusercontent.com/assets/900690/21340404/813270a6-c686-11e6-872a-61c0de1d842c.png)

**Comment by soljohnston777** [comment]
Thanks! I am glad it exists!  Is there any way that could be added as a right click option on the tab bar?
