### ISSUE TITLE
Terminal name autocomplete (with TAB) shifts the completed string to left

### ISSUE THREAD

**Issue by ionut17** [Microsoft/vscode#17586]
- VSCode Version: Code 1.8.1 (ee428b0eead68bf0fb99ab5fdc4439be227b6281, 2016-12-19T14:49:23.350Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

|Extension|Author|Version|
|---|---|---|
|html-snippets|abusaidm|0.0.18|
|vscode-javascript-snippet-pack|akamud|0.1.5|
|vscode-theme-onedark|akamud|0.2.14|
|vscode-eslint|dbaeumer|1.1.0|
|javadebugger|donjayamanne|0.0.2|
|jquerysnippets|donjayamanne|0.0.1|
|python|donjayamanne|0.5.5|
|beautify|HookyQR|0.6.2|
|vscode-icons|robertohuertasm|4.0.5|
|sass-indented|robinbentley|1.2.1|

---

Steps to Reproduce:

1. Open a terminal
2. Write a command with autocomplete (e.g cd To) and when you press TAB it autocompletes (to cd Today), but it shifts the string to the left in the path string making it almost unreadable.

**Comment by Tyriar** [comment]
Merging into https://github.com/Microsoft/vscode/issues/14613 as I believe they share the same root cause.

**Comment by Tyriar** [comment]
This should hopefully be fixed in tomorrow's Insiders build (via https://github.com/Microsoft/vscode/commit/63f1fa66800bf641de5e36027610503ba75085b5). Please let me know if it still reproduces.

See https://github.com/Microsoft/vscode/issues/13625 for more information.
