### ISSUE TITLE
Allow use origin name(English) to match in "view" picker command

### ISSUE THREAD

**Issue by Meeeeow** [Microsoft/vscode#17581]
- VSCode Version: 1.8.1
- OS Version: Windows 10 Version 1607

Steps to Reproduce:

1. Switch language to Chinese
2. Press Ctrl + P open command panel
2. Type "view " with things you want to open.

But, if i type "term" it will show nothing match, i think type "term" is more easy and quick than switch input method then type "zhongduan" and choose which text is correct.

**Comment by egamma** [comment]
@bpasero This suggests that we should offer the same matching approach in the 'Quick View' menu as we provide in the command palette.

Quick View
![image](https://cloud.githubusercontent.com/assets/172399/21348031/91b1bf48-c6ab-11e6-8b05-dbf7cb8019a5.png)

Command Palette
![image](https://cloud.githubusercontent.com/assets/172399/21348084/cf0a4b58-c6ab-11e6-909c-934182a9136a.png)

**Comment by Meeeeow** [comment]
Any progress?

**Comment by bpasero** [comment]
This feature request will not be considered in the next [6-12 months roadmap](https://github.com/Microsoft/vscode/wiki/Roadmap) and as such will be closed to keep the number of issues we have to maintain actionable. Thanks for understanding and happy coding!
