### ISSUE TITLE
Invalid signature during installation on Fedora 38 Beta

### ISSUE THREAD

**Issue by straurob** [microsoft/vscode#175842]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.76.0
- OS Version: Fedora 38 Beta

Steps to Reproduce:
On a system with Fedora 38 Beta, run `sudo dnf https://packages.microsoft.com/keys/microsoft.asc` as mentioned in the [installation instructions](https://code.visualstudio.com/docs/setup/linux#_rhel-fedora-and-centos-based-distributions).

This results in the following error message:

```
error: Certificate EB3E94ADBE1229CF:
  Policy rejects EB3E94ADBE1229CF: No binding signature at time 2023-03-02T07:20:11Z
error: https://packages.microsoft.com/keys/microsoft.asc: key 1 import failed.
```

**Comment by teohhanhui** [comment]
The (unsafe) workaround is to set `gpgcheck=0` and comment out `gpgkey` in `/etc/yum.repos.d/vscode.repo`

**Comment by r100pa** [comment]
Looks like it is solved, just manged to install it without hiccups. First upgraded without code  `sudo dnf upgrade -x code` )then sudo dnf upgrade.
