### ISSUE TITLE
Add function of printing and replace in selected range

### ISSUE THREAD

**Issue by guid2002** [Microsoft/vscode#17587]
- VSCode Version: 1.8.1
- OS Version: Windows 7 64bits

Please add the following function for coming new update:

1) Printing function 
2) Option to replace text in selected range

Thx

**Comment by egamma** [comment]
@guid2002 thanks for your feature requests. In general please try to follow our guidelines and file a separate issue per feature request.

> Printing function

duplicates #11922

>Option to replace text in selected range

This is already supported, you can select the option to just find in the selection
![image](https://cloud.githubusercontent.com/assets/172399/21345264/d2e4e1d6-c69f-11e6-9c26-7e569a20f5b6.png)
