### ISSUE TITLE
Consider to increase the time  to get a response to a disconnect and terminate request

### ISSUE THREAD

**Issue by QuocDoBV** [microsoft/vscode#175850]
Can we increase the time to get a response to a [disconnect ](https://github.com/microsoft/vscode/blob/e9229a18805fdb9baf7356ddc31bd216da5842ef/src/vs/workbench/contrib/debug/browser/rawDebugSession.ts#L572)and [terminate ](https://github.com/microsoft/vscode/blob/e9229a18805fdb9baf7356ddc31bd216da5842ef/src/vs/workbench/contrib/debug/browser/rawDebugSession.ts#L310)request? Some things I need to do on these methods and they need more times than 2s to can complete. It would be nice if the time was increased to 4s.

**Comment by roblourens** [comment]
Discussed in https://github.com/microsoft/vscode/issues/172284
