### ISSUE TITLE
Download VS Code Insiders quick pick should be low priority

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#175815]
<img width="602" alt="image" src="https://user-images.githubusercontent.com/876920/222292231-270774a8-0ead-4bf2-87a7-32b1cc7270d4.png">

IMHO it's very unlikely that users install VS Code through the remote picker, so we probably want to move it down to the bottom.

**Comment by meganrogge** [comment]
It's still not at the bottom of the list, but has moved to be below the codespace option, so considering this verified.

![image](https://user-images.githubusercontent.com/29464607/226988976-3a4c8c63-c0c0-4b2f-a3df-6613f0f931b9.png)

**Comment by joyceerhl** [comment]
Yeah that's the intended behavior, we still suffix the list with Install Additional Remote Extensions so that entry should always be last if it is shown.
