### ISSUE TITLE
terminal links always open in editor group 1

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#175875]
* have terminal output with file links
* have side by side editors
* focus on the second (non primary) editor
* select a link in the terminal
* :bug: it opens in the first editor group

**Comment by Tyriar** [comment]
This works fine for me now:

![Recording 2023-03-29 at 12 37 44](https://user-images.githubusercontent.com/2193314/228649051-948a21c9-66a2-4874-8093-3ad8bac63106.gif)
