### ISSUE TITLE
[scss] scss map syntax showing as an error

### ISSUE THREAD

**Issue by gregornoriskin** [Microsoft/vscode#1758]
If I add a map to a scss file, e.g. "$map: (key1: value1, key2: value2, key3: value3);" it shows as an error. Red squiggly appears under the ":" after the first key and hover message reads ") expected". Despite the error in editor node-sass evaluates map-get correctly over it.

**Comment by aeschli** [comment]
We don't support the map syntax yet

**Comment by basvandenheuvel** [comment]
Any roadmap on when this will be solved?

**Comment by egamma** [comment]
It is not on top of our backlog currently, sorry. 

As a workaround you can disable the built-in validation using
```json
    "sass.validate": true
```

and install extension like [stylelint](https://marketplace.visualstudio.com/items?itemName=shinnn.stylelint).

**Comment by rob3c** [comment]
Thanks for the pointer to `stylelint`. I'm guessing that should be `"sass.validate": false` instead of `true` to disable the built-in validation to allow stylelint to work without conflict?

**Comment by basvandenheuvel** [comment]
Any info on this topic :)?

**Comment by senseiweb** [comment]
bumping this, check to see the current pulse - thanks.

**Comment by VishalGulati** [comment]
any update on this one? I made the setting in settings.json i.e. "sass.validate": false as suggested  but still got the same error.

**Comment by VishalGulati** [comment]
update: **"scss.validate": false** worked!!

**Comment by jwatkin** [comment]
Is there a way to vote this up? The basic template provided in a Foundation 6 project contains maps assigned to variables in the default _settings.scss file. I'm new to Sass and Visual Studio Code but so far this seems like a common use case. Thank you.

**Comment by gizm0bill** [comment]
there's also a validation error when trying to declare a rule with a variable in its name
For example: `.#{$color-type} { ...` warns: `[scss] at-rule or selector expected`

**Comment by Aarilight** [comment]
@aeschli @egamma Do you accept pull requests for this? And if so what do I need to do? I have the multi-arg `@each` working, trying to get the map assignment done atm but that's harder cause it seems to parse w/ cssParser, and it'd probably be silly to have map parsing in that

**Comment by egamma** [comment]
@Aarilight

>Do you accept pull requests for this?

In general yes, but I defer to @aeschli whether he has specific concerns. @Aarilight pls keep in mind that we are slower to respond over the holidays and most of the team is on vacation.

**Comment by Aarilight** [comment]
@aeschli that doesn't add map support to `@each`, does it? `@each` can get a comma-separated list of variables from either map entries (two vars, one for prop and one for val), or lists within lists (in which case you can get a var for each sub-list item). Without `@each` support maps are still kinda annoying to work with in vscode. [My fork adds in support for multi-var `@each`](https://github.com/Microsoft/vscode-css-languageservice/compare/master...Aarilight:master#diff-8af5bdca6434a07153f7ab3020ed388e), for reference.

**Comment by aeschli** [comment]
Thanks for pointing that out. I added support for multiple variables.
