### ISSUE TITLE
VS Code 1.76 starts *all* onTaskType extensions when debugging

### ISSUE THREAD

**Issue by 50Wliu** [microsoft/vscode#175821]
Type: <b>Bug</b>

1. Open the "Remote Extension Host" output window
2. Start Debugging (F5)
3. Note that every extension with an `onTaskType:something` activation event activates.

Pre 1.76, no extensions with `onTaskType` would activate, unless you were actually running that task.

![vs-code-debug-all-task-types](https://user-images.githubusercontent.com/2766036/222298882-3dd99ce2-eea2-4ee5-bf7f-7853f7d95d07.gif)

VS Code version: Code 1.76.0 (92da9481c0904c6adfe372c12da3b7748d74bdcb, 2023-03-01T10:22:44.506Z)
OS version: Windows_NT x64 10.0.23405
Modes:
Sandboxed: No
Connection to 'SSH: one_click' could not be established  Connecting with SSH timed out
Remote OS version: Windows_NT x64 10.0.22000

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz (12 x 3696)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.78GB (14.22GB free)|
|Process Argv|--crash-reporter-id d2ee1b87-344a-4fdd-bf7b-2ab4787239c4|
|Screen Reader|no|
|VM|0%|

Connection to 'SSH: one_click' could not be established  Connecting with SSH timed out

|Item|Value|
|---|---|
|Remote|SSH: wave_analysis|
|OS|Windows_NT x64 10.0.22000|
|CPUs|Intel(R) Xeon(R) Platinum 8272CL CPU @ 2.60GHz (8 x 2594)|
|Memory (System)|32.00GB (24.03GB free)|
|VM|0%|
</details><details><summary>Extensions (27)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-toggle-quotes|Bri|0.3.6
remotehub|Git|0.52.0
wavework|Mic|1.2023.216002
blazorwasm-companion|ms-|1.1.4
vscode-edge-devtools|ms-|2.1.1
remote-containers|ms-|0.275.1
remote-ssh|ms-|0.96.0
remote-ssh-edit|ms-|0.84.0
vscode-remote-extensionpack|ms-|0.24.0
azure-repos|ms-|0.28.0
remote-explorer|ms-|0.2.0
remote-repositories|ms-|0.30.0
remote-server|ms-|1.0.0
material-theme|zhu|3.15.6
midl3-language-server|Ale|0.0.31
vscode-eslint|dba|2.4.0
vscode-research|dev|1.2022.1111005
vulnerability-extension|dev|1.2023.217002
copilot|Git|1.76.9071
vscode-azdo-codereview|Mic|1.2022.722003
vscode-nmake-tools|Mic|4.0.220809006
wavespace-remote-companion|Mic|1.2022.317002
azure-pipelines|ms-|1.208.0
vscode-dotnet-runtime|ms-|1.6.0
sarif-viewer|MS-|3.3.5
azure-account|ms-|0.11.3
cpptools|ms-|1.14.4

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
pynewvextcfv2:30669238
azure-dev_surveyone:30548225
pyindex848:30662994
nodejswelcome1cf:30587006
2e4cg342:30602488
pyind779:30671433
f6dab269:30613381
pythonsymbol12:30671437
showlangstatbar:30672706

```

</details>

**Comment by adam-fowler** [comment]
This also occurs when calling `Run Build Task...`

**Comment by meganrogge** [comment]
Probably caused by https://github.com/microsoft/vscode/issues/172065

**Comment by 50Wliu** [comment]
Yeah, seems like #172065 is suspicious, because I don't see `onTaskType:` defined for the extension that made me discover this bug...

However, even if it was defined, VS Code still shouldn't be activating every single `onTaskType` extension on a normal debug session, right?

**Comment by nomyTx** [comment]
When will this be fixed? It's really annoying to have random extensions start up when I launch a Live Share session.

**Comment by 50Wliu** [comment]
@meganrogge I'm not sure this is a duplicate. I'll use WAVE as the example here just because I happen to be on the same team as #176006.

Pre 1.76.0, debugging a _TypeScript_ VS Code extension would not activate the WAVE extension.
On 1.76.0 _and_ 1.76.1, debugging that same extension activates WAVE.

While #176248 and 1.76.1 fixed the hanging issue reported in #176006, I still think it's unexpected (and incorrect) behavior that debugging a TypeScript codebase activates an extension exclusively meant for Windows C++ developers.
The rust-analyzer extension also seems to be getting bug reports about this same unexpected behavior:
* rust-lang/rust-analyzer#14231
* rust-lang/rust-analyzer#14253

**Comment by samfundev** [comment]
I'm seeing this in 1.76.2 and build tasks never seem to finish fetching:
![bug](https://user-images.githubusercontent.com/6759716/225515398-b24cb576-658a-455e-89bb-2d34d3569018.gif)

**Comment by meganrogge** [comment]
When you debug, if there's a prelaunch task, we will `getTask` -> `tryResolveTask` -> `_activateTaskProviders(type)`

There, we wait for all extensions to be registered. In 1.76, we now implicitly activate `onTaskType`, thus what you are seeing. 

https://github.com/microsoft/vscode/blob/6b85f1cfcf849e4a50185addc769a084a4c30eaf/src/vs/workbench/contrib/tasks/browser/abstractTaskService.ts#L575-L577

The fix would be to revert that change or to not wait for installed extensions to be registered, but that would break other things. @alexdima looks like you added that here. https://github.com/microsoft/vscode/commit/51d7dd1a7319cca932d2db8bb6560e2fc8dc3c03#diff-f77e08d48fa5a43f6cd385c0bac2c04ee2123565ead5f0f4b60e23c8af821b76R511-R514 

do you have thoughts related to this?

> still think it's unexpected (and incorrect) behavior that debugging a TypeScript codebase activates an extension exclusively meant for Windows C++ developers.

**Comment by alexdima** [comment]
@meganrogge I don't remember the specifics, I'm just reading the code:
```
	private _getActivationEvents(type: string | undefined): string[] {
 		const result: string[] = [];
 		result.push('onCommand:workbench.action.tasks.runTask');
 		if (type) {
 			// send a specific activation event for this task type
 			result.push(`onTaskType:${type}`);
 		} else {
 			// send activation events for all task types
 			for (const definition of TaskDefinitionRegistry.all()) {
 				result.push(`onTaskType:${definition.taskType}`);
 			}
 		}
 		return result;
 	}

 	private async _activateTaskProviders(type: string | undefined): Promise<void> {
 		// We need to first wait for extensions to be registered because we might read
 		// the `TaskDefinitionRegistry` in case `type` is `undefined`
 		await this.extensionService.whenInstalledExtensionsRegistered();

 		await Promise.all(
 			this._getActivationEvents(type).map(activationEvent => this.extensionService.activateByEvent(activationEvent))
 		);
 	}
```

Is it possible that we call `_activateTaskProviders(undefined)`? That seems to result in all task providers getting activated. Do you know why `type` would be `undefined`?

**Comment by 50Wliu** [comment]
Aha, here's a clue. It looks like this only happens when trying to debug something that depends on _a default build task_.
In safe mode (`--disable-extensions`) on 1.76.2, I see the following behavior:
* Running a launch configuration with a `preLaunch` task of `${defaultBuildTask}` **does** start all extensions that contribute tasks
* Running a launch configuration that specifies an explicit `preLaunch` task does **NOT** start task extensions (other than the expected ones)

I can provide both my launch.json & tasks.json if necessary, though they're both pretty standard. (`defaultBuildTask` goes to a task of type `npm` and script `compile:dev`)

https://user-images.githubusercontent.com/2766036/225780360-3c60f107-72d5-490a-97e1-8e0cb5ec0eb3.mp4

**Comment by 50Wliu** [comment]
> Is it possible that we call _activateTaskProviders(undefined)?

The configuration resolver service for `defaultBuildTask` calls `_getTasksForGroup(TaskGroup.Build)` which calls `_getGroupedTasks()` (notice NO argument) which calls `_activateTaskProviders(undefined)` which activates all task provider extensions.

https://github.com/microsoft/vscode/blob/143d94ae0dfed656d43fe211ffb7c7d69a27f87f/src/vs/workbench/contrib/tasks/browser/abstractTaskService.ts#L305-L306 ⬇️
https://github.com/microsoft/vscode/blob/143d94ae0dfed656d43fe211ffb7c7d69a27f87f/src/vs/workbench/contrib/tasks/browser/abstractTaskService.ts#L1374-L1375 ⬇️
https://github.com/microsoft/vscode/blob/143d94ae0dfed656d43fe211ffb7c7d69a27f87f/src/vs/workbench/contrib/tasks/browser/abstractTaskService.ts#L1960-L1963

Thanks to [this tip](https://github.com/microsoft/vscode/wiki/How-to-Contribute#using-the-chrome-developer-tools) in your wiki that mentioned being able to debug release versions of VS Code using the builtin dev tools! :D

**Comment by 50Wliu** [comment]
Yeah sorry, I didn't mean to imply that something had changed with the call stack - just that that was the code path of interest.

But at the same time, how debugging has also always worked was that I never had to deal with unrelated extensions activating and hanging VS Code, cluttering my status bar, or throwing unasked-for update prompts in my face before 1.76 😉. So even if the call stack is the same, there's definitely a new side effect.

**Comment by nomyTx** [comment]
Any update on a fix coming? This bug makes Live Share basically unusable as it will launch unrelated extensions unless you uninstall every extension with an `onTaskType`.

**Comment by 50Wliu** [comment]
Thanks for the clarification! I just have two more questions then:

1. Is it expected behavior that starting a launch configuration that has a `preLaunchTask` of `${defaultBuildTask}` will activate _all_ extensions with an (explicit or implicitly added) `onTaskType` activation event?
2. If it isn't expected, can this bug be reopened? If it is expected, would you be open to accepting a PR that tries to change the behavior back to pre-1.76 behavior without affecting the new implicit onTaskType events? (I don't know how feasible this is, but just putting it out there)

**Comment by meganrogge** [comment]
Yes, #1 is expected behavior

**Comment by Mai-Lapyst** [comment]
Digged in the sourcecode an managed to find the culprit and a workaround (for now).

The workaround is to set the setting `task.saveBeforeRun` to `never`.

The bug exists because `AbstractTaskService._executeTask` calls `_saveBeforeRun`,
and if editors where saved, it tries to reload the the task by calling `AbstractTaskService.getTask`:

https://github.com/Mai-Lapyst/vscode/blob/0d5e948d863153807cfe07ecd20dc10374eea6d2/src/vs/workbench/contrib/tasks/browser/abstractTaskService.ts#L1832-L1850

The `getTask` method, first trys to search the task inside the workspace and if that files calls `_getGroupedTasks()`:

https://github.com/Mai-Lapyst/vscode/blob/0d5e948d863153807cfe07ecd20dc10374eea6d2/src/vs/workbench/contrib/tasks/browser/abstractTaskService.ts#L765

`_getGroupedTasks` normaly takes one parameter, a filter, to only activate a certain type of task providers:

https://github.com/Mai-Lapyst/vscode/blob/0d5e948d863153807cfe07ecd20dc10374eea6d2/src/vs/workbench/contrib/tasks/browser/abstractTaskService.ts#L1960-L1963

**Comment by Mai-Lapyst** [comment]
Opened a PR that fixes this issue.

**Comment by meganrogge** [comment]
Re

> As far as I can tell, this is how it has always worked

While this is true, it would be good if we can improve upon it. Thanks for the PR

**Comment by meganrogge** [comment]
to verify, have an extension with activation event `onTaskType:X` set. Before, it would get activated immediately upon invoking `Tasks: run task`. Verify that now it only gets activated if you select a task of type `X`.

**Comment by gluxon** [comment]
Appreciate the fix @meganrogge! Thank you. I've been confused for a few weeks why rust-analyzer kept trying to start in my frontend-only projects.
