### ISSUE TITLE
More usage insights for extensions

### ISSUE THREAD

**Issue by JonasMa** [microsoft/vscode#175874]
As the creators of a comments extension we're interested in how users interact with comments throughout the UI. To fully understand our users’ journeys we're currently missing some information that is not available to extensions:

- users clicking on comment icons in the line gutter, to expand / collapse comments
- users clicking on the collapse buttons of individual comments in the editor
- users clicking on comments in the comments panel, to reveal them in the editor

Would making this information available be an option?

We don’t necessarily need it to be an API for extensions, since we would have access to it in our particular installation if it was part of core VS Code telemetry for usage data.

cc @alexr00 @hermannloose @laurentlb @gkatja

**Comment by alexr00** [comment]
@JonasMa are you just looking for new telemetry to be added for the above bullet points?

**Comment by hermannloose** [comment]
I noticed this doesn't have `label:comments` yet, making it a bit harder to find.

**Comment by JonasMa** [comment]
@alexr00 Yes that's correct. For now that's all we're missing. In general we're interested in all interactions related to comments so all new functionality in this direction would be interesting for us to have stats about as well.

**Comment by poucet** [comment]
Would love to see this prioritized in April.

**Comment by alexr00** [comment]
@poucet and @JonasMa we've decided not to add any telemetry for when comments are expanded/collapsed. We try not to add telemetry that we aren't going to use, and telemetry for comments expand/collapse falls under this category.

**Comment by JonasMa** [comment]
I understand. So this means you implemented option 3 (`users clicking on comments in the comments panel`) only, right? Can you please link the according PR? Thanks!

**Comment by Aburupa1389** [comment]
أرسل gasem alotef إليك رسالة إلكترونية في وضع الحفاظ على السرّية في Gmail:

[image: شعار Gmail]Re: [microsoft/vscode] More usage insights for extensions (Issue #175874) <https://confidential-mail.google.com/msg/AA2T6Pa4Swb1XhUeER5EpNglXQbtHRQDgH22h2_tXYrqzGGDNUHaeQ3olQ7cYGRmOSzt94xj7isUd-IOtkbmQCX1r0FJ9QHXhcB3kMFEyyoAU0SW0p1vGEZVWfVZnmXLZcVUTyhF454An82M-QDHu2VrvBUYewjpw6ZTAqJJCxErT3FoHnZ0a_c7zk8clCs9PCegKaYgU9X40aG9Ey_2>

تم إرسال هذه الرسالة يوم 11‏/05‏/2023 الساعة 1:15:57 م غرينتش-7
يمكنك فتحه بالنقر على الرابط أدناه. ولا يعمل هذا الرابط إلا مع ***@***.***

عرض الرسالة الإلكترونية <https://confidential-mail.google.com/msg/AA2T6Pa4Swb1XhUeER5EpNglXQbtHRQDgH22h2_tXYrqzGGDNUHaeQ3olQ7cYGRmOSzt94xj7isUd-IOtkbmQCX1r0FJ9QHXhcB3kMFEyyoAU0SW0p1vGEZVWfVZnmXLZcVUTyhF454An82M-QDHu2VrvBUYewjpw6ZTAqJJCxErT3FoHnZ0a_c7zk8clCs9PCegKaYgU9X40aG9Ey_2>

يمنحك "الوضع السري في Gmail" مزيدًا من التحكُّم في الرسائل التي تُرسِلها. ربما اختار المُرسِل تحديد وقت انتهاء الصلاحية أو إيقاف الطباعة أو إعادة توجيه رسالة أو تتبّع الوصول إلى هذه الرسالة. مزيد من المعلومات <https://support.google.com/mail/answer/7674059>
Gmail: خدمة بريد إلكتروني مُقدَّمة من Google
يخضع الاستخدام لـ سياسة خصوصية Google <https://myaccount.google.com/privacypolicy?hl=ar>
Google LLC, 1600 Amphitheatre Parkway, Mountain View, CA 94043, USA
لقد استلمت هذه الرسالة لأن أحدهم أرسل إليك رسالة إلكترونية في وضع الحفاظ على السرّية في Gmail.
[image: شعار Google]
