### ISSUE TITLE
Remote explorer terminal output says ssh-agent: Error connecting to agent: No such file or directory

### ISSUE THREAD

**Issue by gopiextrahop** [microsoft/vscode#175806]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.76
- OS Version: 

Version: 1.76.0
Commit: 92da9481c0904c6adfe372c12da3b7748d74bdcb
Date: 2023-03-01T10:23:06.752Z (11 hrs ago)
Electron: 19.1.11
Chromium: 102.0.5005.196
Node.js: 16.14.2
V8: 10.2.154.26-electron.0
OS: Darwin arm64 22.3.0
Sandboxed: No

My remote host is a Ubuntu box.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.5 LTS
Release:        20.04
Codename:       focal

Steps to Reproduce:

1. I have multiple remote (SSH) projects/workspace on the same remote host. 
2. When I open the terminal in one of the remote workspace/projects from the remote explorer tab, some of the workspace/projects complain that `ssh-agent` is not running. Some workspace/projects don't have this issue.
3. In my .bashrc I have the following lines printed ( `echo $SSH_AUTH_SOCK` and output of `ssh-add -l`)
 ```bash
#  vscode terminal: failure in a workspace/projects
Printing SSH_AUTH_SOCK /run/user/1000/vscode-ssh-auth-sock-483324580
Error connecting to agent: No such file or directory
```

```bash
# vscode terminal: success in a workspace/projects
Printing SSH_AUTH_SOCK /run/user/1000/vscode-ssh-auth-sock-571790363
3072 SHA256:xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx gopi@remotehost (RSA)
2048 SHA256:xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx gopi@host (RSA)
```

In each workspace/project terminal the `SSH_AUTH_SOCK` value is different. While in my remote host bash terminal the output of `SSH_AUTH_SOCK` is a temp file,  `/tmp/ssh-9d6BgICVtI/agent.103608`. This started happening with 1.75.1 of vscode. I have been using the same workflow with no issues before 1.75.1

```bash
# this is result on my non-vscode terminal on my remote host
Printing SSH_AUTH_SOCK /tmp/ssh-boFEVa3H7k/agent.131282
3072 SHA256:xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx gopi@remotehost (RSA)
2048 SHA256:xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx gopi@host (RSA)
```
This is preventing me from doing git pull/push since there is no ssh-agent as far as the terminal is concerned in the failing workspace/project. I can do git commands in the successful workspace/project. There is no difference between the succeeding and failing workspace/project. They are just different git repos that are cloned on my remote host.

**Comment by roblourens** [comment]
Sorry, this is probably https://github.com/microsoft/vscode/issues/168202. Disabling `remote.ssh.useLocalServer` or `remote.SSH.enableAgentForwarding` may work around it

**Comment by gopiextrahop** [comment]
Thanks, disabling both has helped.

**Comment by eleanorjboyd** [comment]
@thibaut-lo does disabling just one work? Currently, local server mode is not working as intended and this could be related to your problem here and we are in the process of fixing that.
