### ISSUE TITLE
Crash the Vs code 

### ISSUE THREAD

**Issue by adityagourhealthandglow** [microsoft/vscode#175864]
Type: <b>Bug</b>

 it suddenly coming and effect the VS code settings

VS Code version: Code 1.76.0 (Universal) (92da9481c0904c6adfe372c12da3b7748d74bdcb, 2023-03-01T10:23:45.993Z)
OS version: Darwin x64 22.1.0
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz (8 x 1400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|7, 8, 8|
|Memory (System)|8.00GB (0.64GB free)|
|Process Argv|--crash-reporter-id db8ccee2-d9ac-42a8-90d9-4f7a3561b676|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|2.4.0
githistory|don|0.6.19
es7-react-js-snippets|dsz|4.4.3
gitlens|eam|13.3.1
react-native-react-redux|EQu|2.0.6
prettier-vscode|esb|9.10.4
git-graph|mhu|1.30.0
vscode-typescript-tslint-plugin|ms-|1.3.4
vscode-react-native|msj|1.10.0
vscode-open-iterm2|mus|0.0.4
run-external|nac|0.1.3
vscode-versionlens|pfl|1.5.0
vs-code-prettier-eslint|rve|5.0.4
errorlens|use|3.7.0
omi-snippets|Wsc|2.2.8

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
azure-dev_surveyone:30548225
pyindex848:30662994
nodejswelcome1:30587005
282f8724:30602487
pyind779:30671433
89544117:30613380
pythonsymbol12:30671437
a9j8j154:30646983
funwalk2cf:30676044

```

</details>

**Comment by rzhao271** [comment]
Could you try generating a crash report and sending it over to us?
Instructions: https://github.com/microsoft/vscode/wiki/Native-Crash-Issues
