### ISSUE TITLE
'hot exit' and 'open with code' causes funny bug when trying to open an hot exited file

### ISSUE THREAD

**Issue by ahmadalli** [Microsoft/vscode#17585]
- VSCode Version: 1.8.1
- OS Version: Windows 10 ver 1607

Steps to Reproduce:

1. in user settings, add `"window.openFilesInNewWindow": false`
2. open a file
3. modify it
4. close code without saving (hot exit feature must be enabled)
5. right click on the file and click on 'open with code'
6. two instances of vs code will be created. one with two tabs: 'untitled1' and the hot exited file in one instance and the old file (not modified file) in another instance.

since I've disabled `openFilesInNewWindow` I think code must open just the first instance (with the opened file's tab having focus) or at least have an option for this behaviour.

**Comment by bpasero** [comment]
Is this https://github.com/Microsoft/vscode/issues/16820 ?

**Comment by ahmadalli** [comment]
yes. sorry for duplication
