### ISSUE TITLE
Breakpoints grouped by file

### ISSUE THREAD

**Issue by dimateos** [microsoft/vscode#175884]
I saw #154110, and I would like a bit more breakpoint management too.

IMO a simple grouping by file seems to be an interesting feature that could be added to vscode direclty.

Right now the list shows `filename`, `path`, `line`. Grouping by file would render the first two redundant, so I suggest that the breakpoint previews a bit of the text present in the line of code.

This second feature seems quite more complex but pretty useful, it would allow the user to disable specific breakpoints at a glance, and even use them for code navigation.

Nonetheless, even with redundant info shown, I feel like grouping by file and being able to toggle all breakpoint from the same file at once is useful too.

**Comment by roblourens** [comment]
I think the reply to that closed issue still holds
