### ISSUE TITLE
Avoid extra data copies when using copy/paste or drop APIs with workspace edits

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#175800]
From 169137

Using the copy or drop APIs, it's common for extensions to write the copied file back into the workspace with a workspace edit. However this currently result in a lot of data being copied back and forth to the extension host:

1. Copy event. We read the `File` from the event into a `UInt8Array`
2. Copy api is triggered
3. Extension host, we read the file data. This requires transferring that data from the main process to the ext host
4. Extension host, we create a new workspace edit using the file data
5. We transfer the workspace edit back to the main process

This means that we end up transferring a potentially large `Uint8Array` to the ext host and back for no real reason since the data is never changed. It would be better to keep all this in the main thread

**Comment by mjbvz** [comment]
To verify:

1. Check the docs for this new option https://github.com/microsoft/vscode/blob/2c51b3de329d48f45eabe80316f099f46fd3a5cc/src/vscode-dts/vscode.d.ts#L3713
2. Use the drop into editor provider sample with a new drop provider:


```ts
class CreateFileDropProvider implements vscode.DocumentDropEditProvider {
	async provideDocumentDropEdits(
		_document: vscode.TextDocument,
		position: vscode.Position,
		dataTransfer: vscode.DataTransfer,
		token: vscode.CancellationToken
	): Promise<vscode.DocumentDropEdit | undefined> {
		const dataTransferItem = dataTransfer.get('image/png');
		if (!dataTransferItem) {
			return undefined;
		}

		const additionalEdit = new vscode.WorkspaceEdit();
		additionalEdit.createFile(vscode.Uri.joinPath(vscode.workspace.workspaceFolders![0].uri, 'test.png'));

		return { insertText: 'inserted', additionalEdit };
	}
}
```

3. Confirm that dropping a png from outside of VS Code into the editor creates a file called `test.png`

**Comment by joaomoreno** [comment]
The very nice sample threw me off since it's missing this critical part:

```ts			additionalEdit.createFile(vscode.Uri.joinPath(vscode.workspace.workspaceFolders![0].uri, 'test.png'), {
				contents: dataTransferItem.asFile()
			});
```

Also, this was missing from the steps, took me a few minutes of digging to find I had to choose this from the content widget menu:

<img width="476" alt="image" src="https://user-images.githubusercontent.com/22350/235152315-bedb8a68-0b5b-4e25-ac16-eb588c475af4.png">
