### ISSUE TITLE
Make file dialogs remember last selection per window and not globally

### ISSUE THREAD

**Issue by khaled-hossain-code** [Microsoft/vscode#17593]
- VSCode Version: 1.8.1
- OS Version: win 10

Steps to Reproduce:

1. open vs code open a folder "myFolder"
2. open vs code in new terminal and select "yourFolder" folder to open
3. go to window 1 and open folder you will end up in "yourFolder" path rather than "myFolder" path.

**Comment by bpasero** [comment]
@khaled-hossain-code having trouble to understand the steps, can you maybe add screenshots or best a video?

**Comment by khaled-hossain-code** [comment]
step 1
[url=https://postimg.org/image/dqi94uvo1/][img]https://s24.postimg.org/dqi94uvo1/step_1.png[/img][/url]
step 2
[url=https://postimg.org/image/eu2dgtgb5/][img]https://s24.postimg.org/eu2dgtgb5/step_2.png[/img][/url]
step 3
[url=https://postimg.org/image/p5eq9h80h/][img]https://s24.postimg.org/p5eq9h80h/step_3.png[/img][/url]
bug
[url=https://postimg.org/image/8qkswwq1d/][img]https://s24.postimg.org/8qkswwq1d/bug.png[/img][/url]

**Comment by bpasero** [comment]
@khaled-hossain-code ah, this is about which folder is selected in the windows file dialog?

**Comment by khaled-hossain-code** [comment]
yes it is. window forgets its last opening state.

**Comment by bpasero** [comment]
This should work a lot better with 1.18.
