### ISSUE TITLE
Shell and npm tasks are unavailable on vscode desktop

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#175976]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 
- OS Version: 

Steps to Reproduce:

1. Try to debug monaco-editor, or any project with a launch.json that uses a preLaunch task
2. Tons of extensions (every extension that provides a task?) activate

<img width="504" alt="image" src="https://user-images.githubusercontent.com/2230985/222576700-38792df3-781a-4b22-9650-fb62dfbead6e.png">

I also notice at this point that the "Run Tasks" list doesn't have any of the tasks that are defined in the tasks.json, so I think debug is just trying to activate all of them to see if they might provide that task that is apparently missing

<img width="1171" alt="image" src="https://user-images.githubusercontent.com/2230985/222576846-221ddd5a-4ed8-4ae3-9002-77ef044cccd2.png">

Tasks output for some reason indicates shell and npm tasks are unavailable, even though I'm running on vscode desktop

<img width="601" alt="image" src="https://user-images.githubusercontent.com/2230985/222577116-00915114-7890-4802-aeb1-5fa8b573b13d.png">

I hit this a few times over the last few weeks, but forgot to file an issue after I got back from vacation, apologies

**Comment by meganrogge** [comment]
The only thing that's changed in tasks within the last milestone was the implicit activation, so likely same root cause

**Comment by connor4312** [comment]
Would that have caused the "shell tasks are unavailable" issue as well?
