### ISSUE TITLE
Sticky scroll renders above right-click context menus

### ISSUE THREAD

**Issue by ErrorGamer2000** [microsoft/vscode#175966]
Does this issue occur when all extensions are disabled?: No (because the context menu is not tall enough, so it's not really an extension bug)

- Version: 1.76.0 (user setup)
- Commit: 92da9481c0904c6adfe372c12da3b7748d74bdcb
- Date: 2023-03-01T10:22:44.506Z
- Electron: 19.1.11
- Chromium: 102.0.5005.196
- Node.js: 16.14.2
- V8: 10.2.154.26-electron.0
- OS: Windows_NT x64 10.0.22621
- Sandboxed: No

Steps to Reproduce:

1. enable sticky scroll
2. Right click where the menu overlaps the sticky area
Screenshot:

![image](https://user-images.githubusercontent.com/70162741/222550461-babbdb52-ce87-4df4-b3d4-f722c6492e62.png)

**Comment by r3m0t** [comment]
Maybe #160620

**Comment by aiday-mar** [comment]
Hi, I am testing on the latest insiders release (https://code.visualstudio.com/insiders/) and the issue appears to be fixed as @bpasero said. Let me know if the problem persists.

**Comment by ErrorGamer2000** [comment]
Cool, thanks
