### ISSUE TITLE
Bug navigating Tamil script letters

### ISSUE THREAD

**Issue by psankar** [microsoft/vscode#17594]
- VSCode Version: Code 1.8.1 (ee428b0eead68bf0fb99ab5fdc4439be227b6281, 2016-12-19T14:42:49.304Z)
- OS Version: Darwin x64 15.6.0

---

Steps to Reproduce:

While editing Tamil language words in VSCode, the navigation keys do not work correctly.

For example:

`புன்சிரிப்போடு` is a tamil word that I am trying to navigate with the left/right arrow keys. The cursor should stop at: `பு`, `ன்`, etc. but I cannot keep the cursor after the second literal character, ன் instead, I am able to move only multiple characters together (`ன்சி` ) together in one keypress. At times, this is worse and the cursor does not move at all.

If you want I can record a video too (if my above explanation is not clear).

**Comment by alexandrudima** [comment]
Let's track in #15622

**Comment by arulrajnet** [comment]
With a smile 

https://code.visualstudio.com/updates/v1_40#_better-handling-for-unicode-combining-characters
