### ISSUE TITLE
Tree view uses inverse icons on High contrast light theme.

### ISSUE THREAD

**Issue by aasimkhan30** [microsoft/vscode#175923]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 
- OS Version: 

Steps to Reproduce:

1. Use any extension that uses tree view 
2. Dark icons are used on high contrast light theme making them invisible.

![image](https://user-images.githubusercontent.com/6816294/222498209-16b2c789-aeea-42cf-ab77-9eaec1399bb3.png)
![image](https://user-images.githubusercontent.com/6816294/222498353-9f1bec85-589f-4135-8a86-bbaa3845988a.png)

**Comment by alexr00** [comment]
The current behavior appears to be consistent between the Explorer and custom trees: if it's a light theme we use the light theme icons, if it's a dark theme we use the dark theme icons, regardless of whether it's a high contrast theme. 

@daviddossett, does it seem reasonable to use the "opposite" file icons when using a high contrast theme? I don't think we have any guarantee that they will actually provide more contrast than the current, matching, icons.

@lramos15, depending on @daviddossett's answer would you adopt the same in the Explorer?

**Comment by alexr00** [comment]
Let's leave it as is.
