### ISSUE TITLE
Feature Request: Terminal Tabs

### ISSUE THREAD

**Issue by Cordoha** [Microsoft/vscode#17599]
# Feature Request
## Terminal Tabs
There's already a plug-in worth mentioning which enables tabs in the blue bar below the terminal but they are merely just small icons. 

## Suggestions
- Tabs Located Beside "Terminal" That Are Actually Tabs.
  - Or Include The "Terminal" Name as a Tab(Which Can Be Renamed), And A (+) Icon To Add More Tabs Which Can Be Renamed.
- Optional Coloured Tabs
- Quick Switching Between Tabs (alt 1-9)
- Ability To Name, and Rename, Close Button
- Save Tabs For Better Workflow

### A Way To Autostart A Command When VSCode has started.

**Example**: -- I'd like to automate sass starting within a tab

Running From A Directory
>  sass --watch example.scss example.css

Watching A Directory Where SCSS Files Are:
> sass --watch /example/to/watch/directory

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/10546
