### ISSUE TITLE
Web Dev: Twitter Card Feature Request

### ISSUE THREAD

**Issue by Cordoha** [Microsoft/vscode#17597]
# Feature Request

It would be nice to have Twitter Card meta data enabling the various types of Twitter Cards available since it's a lengthy process to enable them. You have to memorize every meta tag **per** card, there's different code for each.

## Summary of the types of Twitter Cards available:
- Summary Card: Title, description, thumbnail, and Twitter account attribution.
- Summary Card with Large Image: Similar to a Summary Card, but with a prominently featured image.
- App Card: A Card to detail a mobile app with direct download.
- Player Card: A Card to provide video/audio/media.
- Mobile Developers Cards

## Some Ideas: 
- Would be nice to have a Twitter boilerplate per template
- Or possibly a window pop up suggesting meta data form for import to format into the page where meta data would be
  - This would enable a suggestion of Cards to use, examples of what data would be inclusive(ghosted text before writing into form)
- If pop up suggested: Also link to Validator Page to validate the template on Twitter site. 

## My Suggestion & Links:
I'd much rather a **boilerplate** suggesting which template to use so the meta data tags appear but either way is fine.
- [Twitter Cards](https://dev.twitter.com/cards/types) meta data page.
- [Validator Page](https://cards-dev.twitter.com/validator)

**Comment by egamma** [comment]
This looks like a nice candidate for an extension.
You can contribute snippets from an extension.

**Comment by mjbvz** [comment]
Closing as extension-canidate. Please see [this guide](https://code.visualstudio.com/docs/extensions/overview) for information about writing an extension
