### ISSUE TITLE
Profiles setting didn't migrate properly

### ISSUE THREAD

**Issue by eccentricOrange** [microsoft/vscode#175942]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: Version: 1.77.0-insider (system setup), commit 155cd6db223feb1f8c734ca70e108b9efec7b054
- OS Version: Windows_NT x64 10.0.22621 (Win 11 Pro 22H2)

When I created a new profile, it didn't pick up all the settings from the `Default` profile.

Steps to Reproduce:

1. Install VS Code
2. Create your `settings.json` file (user a.k.a. `Default` profile)
3. Create a new profile (say C++) from the settings, from `Default`.
4. Open a workspace using the new profile.
5. Inspect the profile settings file.

### User settings
```json
{
    "editor.inlineSuggest.enabled": true,
    "files.autoSave": "onFocusChange",
    "window.restoreWindows": "none",  // didn't migrate
    "editor.multiCursorModifier": "ctrlCmd",
    "remote.downloadExtensionsLocally": true,
    "remote.SSH.localServerDownload": "always",
    "[python]": {
        "editor.formatOnType": true
    },
    "dev.containers.defaultExtensions": [
        "GitHub.copilot",
        "GitHub.vscode-pull-request-github",
        "VisualStudioExptTeam.vscodeintellicode",
        "VisualStudioExptTeam.intellicode-api-usage-examples",
        "mutantdino.resourcemonitor"
    ],  // didn't migrate
    "git.enableCommitSigning": true,
    "git.autofetch": true,
    "git.fetchOnPull": true,
    "git.autoStash": true,
    "editor.wordWrap": "on",
}
```

### Profile settings
```json
{
    "editor.inlineSuggest.enabled": true,
	"files.autoSave": "onFocusChange",
    "editor.multiCursorModifier": "ctrlCmd",
	"remote.downloadExtensionsLocally": true,
    "[python]": {
        "editor.formatOnType": true
	},
    "git.enableCommitSigning": true,
    "git.autofetch": true,
    "git.fetchOnPull": true,
    "git.autoStash": true,
    "editor.wordWrap": "on",
    "C_Cpp.clang_format_fallbackStyle": "\"{ BasedOnStyle: Google, IndentWidth: 4 }\"",  // I added this manually, this is expected behavior
}
```

**Comment by sandy081** [comment]
This is expected as they are application scoped settings - https://code.visualstudio.com/docs/editor/profiles#_why-are-some-settings-not-exported-when-exporting-a-profile

**Comment by eccentricOrange** [comment]
@sandy081 is there a list of what counts as "machine-specific settings"?

**Comment by sandy081** [comment]
Good question, actually I dont think so. @rzhao271 Is it possible to query for machine scoped settings in UI?

**Comment by rzhao271** [comment]
It's possible. `git.path` is a machine-scoped setting, and it shows up in the Settings UI with a "not synchronized" indicator.

**Comment by eccentricOrange** [comment]
@rzhao271 I always assumed this meant that it won't be synchronised to the cloud, and not that it's saying anything about profiles.

Can y'all clarify (in the UI or in some form of documentation):
* Which settings will/won't sync online
* Which settings will/won't "inherit" when I create a new profile
* Which settings will/won't apply to remotes (like WSL, Docker Devcontainers, SSH targets, Codespaces)

**Comment by eccentricOrange** [comment]
Also, can you please explain the rationale behind making something like `window.restoreWindows` a scoped setting? To me this seems like functionality that would be available in all the platforms for which you build VS Code.
