### ISSUE TITLE
Automated download patterns part deux

### ISSUE THREAD

**Issue by mwpowellhtx** [microsoft/vscode#175963]
[Following on](https://github.com/microsoft/vscode/issues/109329), but apparently closed issue. Following up on my [vscode downloader](https://github.com/mwpowellhtx/vscode-downloader), interested in the pattern(s) for _CLI_.

i.e. for win32-x64-user (stable), https://update.code.visualstudio.com/1.76.0/win32-x64-user/stable

Among the following:
* _Windows CLI x64, x86, arm64_
* _Linux CLI x64, arm32, arm64_
* _Mac CLI Intel chip, Apple silicon_

Thanks...

**Comment by joaomoreno** [comment]
https://code.visualstudio.com/docs/supporting/faq#_previous-release-versions

**Comment by mwpowellhtx** [comment]
Nice thank you.
