### ISSUE TITLE
Can't locate tsconfig.json path in a wsl directory

### ISSUE THREAD

**Issue by xTye** [microsoft/vscode#175967]
Type: <b>Bug</b>

Open VS Code.
Open Node project located in WSL directory.
Notice: Cannot find module '<dependency>' or its corresponding type declarations.ts(2307).

VS Code version: Code 1.76.0 (92da9481c0904c6adfe372c12da3b7748d74bdcb, 2023-03-01T10:22:44.506Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: No
Remote OS version: Linux x64 5.15.90.1-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 9 3900XT 12-Core Processor            (24 x 3793)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.95GB (18.87GB free)|
|Process Argv|--crash-reporter-id bb044126-3a02-41aa-8ffe-bf0bdcec9b6a|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 5.15.90.1-microsoft-standard-WSL2|
|CPUs|AMD Ryzen 9 3900XT 12-Core Processor (24 x 3792)|
|Memory (System)|15.59GB (14.35GB free)|
|VM|0%|
</details><details><summary>Extensions (47)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|3.0.2
vscode-tailwindcss|bra|0.9.7
c-cpp-compile-run|dan|1.0.43
vscode-eslint|dba|2.4.0
gitlens|eam|13.3.1
prettier-vscode|esb|9.10.4
codespaces|Git|1.13.9
copilot|Git|1.77.9225
vscode-graphql|Gra|0.8.6
vscode-graphql-syntax|Gra|1.1.0
better-cpp-syntax|jef|1.17.2
firebase-explorer|jsa|0.3.3
vscode-docker|ms-|1.24.0
csharp|ms-|1.25.4
isort|ms-|2022.8.0
python|ms-|2023.4.0
vscode-pylance|ms-|2023.3.10
jupyter|ms-|2023.2.1000592019
jupyter-keymap|ms-|1.1.0
jupyter-renderers|ms-|1.0.15
vscode-jupyter-cell-tags|ms-|0.1.6
vscode-jupyter-slideshow|ms-|0.1.5
remote-containers|ms-|0.282.0
remote-wsl|ms-|0.76.1
cmake-tools|ms-|1.13.45
cpptools|ms-|1.14.4
cpptools-extension-pack|ms-|1.3.0
live-server|ms-|0.4.5
vscode-serial-monitor|ms-|0.8.0
vscode-typescript-next|ms-|5.1.20230301
vsliveshare|ms-|1.0.5832
reload|nat|0.0.6
prisma|Pri|4.11.0
java|red|1.15.0
rust-analyzer|rus|0.3.1418
cmake|twx|0.0.17
intellicode-api-usage-examples|Vis|0.2.7
vscodeintellicode|Vis|1.2.30
vscode-arduino|vsc|0.5.0
vscode-java-debug|vsc|0.49.0
vscode-java-dependency|vsc|0.21.1
vscode-java-pack|vsc|0.25.8
vscode-java-test|vsc|0.38.1
vscode-maven|vsc|0.40.4
vscode-icons|vsc|12.2.0
volar|Vue|1.2.0
vscode-typescript-vue-plugin|Vue|1.2.0

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
azure-dev_surveyone:30548225
pyindex848:30662994
nodejswelcome1cf:30587006
282f8724:30602487
pyind779:30671433
f6dab269:30613381
pythonsymbol12:30671437
2i9eh265:30646982
pythonms35:30676800

```

</details>

**Comment by xTye** [comment]
![vscodepng](https://user-images.githubusercontent.com/77994279/222552489-288cfb2c-ae42-46ea-a7a6-1cc283f9bf73.png)

**Comment by xTye** [comment]
I might add that my VSCode is on my `E:` drive and WSL is on my `C:` drive.
For diagnosing the problem, when I click on `No tsconfig` button a .json file is created it on my `E:` drive via the path:
``E:\wsl$\Ubuntu\home\<user>\path\to\project``

**Comment by mjbvz** [comment]
Can you please share a minimal example project that demonstrates this issue?

**Comment by rere252** [comment]
Having the same troubles. Project located in WSL gives the "No tsconfig" error but project located in Windows works fine. This happens with VS Code 1.76.0. Tried reinstalling and it didn't help. Downgraded to VS Code 1.75.1 and the project located in WSL correctly resolves the tsconfig again.

**Comment by Alsdrouf** [comment]
I found a working workaround install the extensions https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-wsl
Than you should be able to launch when with the notification.
If the notification doesn't work (my case) you should go in wsl and use `code .` where you need to use it.
Probably need to reboot wsl/pc after install.
source: https://code.visualstudio.com/docs/remote/wsl

**Comment by xTye** [comment]
> I found a workaround install the extensions https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-wsl Than you should be able to launch when with the notification. If the notification doesn't work (my case) you should go in wsl and use `code .` where you need to use it. Probably need to reboot wsl/pc after install. source: https://code.visualstudio.com/docs/remote/wsl

This is actually how I've been developing for a while. You don't even need to use `code .`. You can just click on the bottom left corner and open vs code in WSL, then VS Code saves your setting for next launch. However, WSL VSCode doesn't save preferences between remote windows. So you have to export and import VSCode profiles. Would prefer to still have my old setup back though.

**Comment by xTye** [comment]
> Can you please share a minimal example project that demonstrates this issue?

https://github.com/xTye/minimal 

This is the minimal version. I will note, when I closed my remote connection to WSL and opened this project I recieved a notification:

`When working on folders in \\wsl, we recommend to use a WSL window. In a WSL window, all commands, extensions and the terminal run in the Linux subsystem. To switch to a WSL window, use [Reopen Folder in WSL](command:remote-wsl.reopenFromRecommendation).`

So it seems like editing in a WSL folder has been deprecated. I don't think it should be though, because doesn't it save another VSCode program on my `C:` drive?

**Comment by kadoshmt** [comment]
Same problem here! This week tha import of all my Angular projects is not found (like the image) posteed by xTye. The unique solution for now is a downgrade of VS Code Version??

**Comment by xTye** [comment]
> Same problem here! This week tha import of all my Angular projects is not found (like the image) posteed by xTye. The unique solution for now is a downgrade of VS Code Version??

That or use the WSL Remote window per @Alsdrouf (s) reply

**Comment by mjbvz** [comment]
@xTye So you are opening a wsl directory from a normal VS Code window, not a remote wsl one? Does it work when you use the remote wsl extension?

**Comment by xTye** [comment]
> @xTye So you are opening a wsl directory from a normal VS Code window, not a remote wsl one? Does it work when you use the remote wsl extension?

Yes, the issue describes opening WSL directory from normal VS Code window. It does work when opening the directory with the remote WSL extension.
![Screenshot 2023-03-09 115830](https://user-images.githubusercontent.com/77994279/224100325-99093ecc-a111-4aaf-bebd-e36c1308f340.png)

**Comment by kadoshmt** [comment]
@xTye yes! I'm using a installation of VS Code on Windows and open a directory on wsl. But this worked until version 1.75.1. I install the wsl extention and now works fine! I had other WSL I had another WSL extension installed (WSL:Recommender from Microsoft publisher) and whenever I activated it, my VS Code crashed. That's why I used it on Windows even without Remote WSL. Now I'm using the official Microsoft Extension called "WSL".

**Comment by mjbvz** [comment]
Thanks for clarifying 

If you're working with code on WSL, we only officially support doing so with the wsl extension.  This makes VS Code understand that you are workin in a linux environment instead of a normal windows environment. Although I'm not sure what changed in the past few releases, using a normal Windows window to open a wsl folders has the potential to cause all sorts of issues (which is why we show that information popup suggesting to use wsl)

Please try using the WSL extension to open the code instead. Let me know if there are any issues when using it

**Comment by epiphanizer** [comment]
Wow. This thread is a big deal and IMO should remain an open issue.

I lost hours of productivity because none of my imports worked overnight.

-Sean
