### ISSUE TITLE
Accessible buffer does not show currently running command output

### ISSUE THREAD

**Issue by Majin-Buu611** [microsoft/vscode#175981]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 
1.76.0
92da9481c0904c6adfe372c12da3b7748d74bdcb
x64
- OS Version: 
Ubuntu 18.04, codespaces (so vscode web)

Steps to Reproduce:

0. Create a new codespace and enter the terminal. We have screen reader optimization enabled 
1. Run `echo hello` and switch to accessibility buffer (shift+tab) and you will see hello as expected
2. Run `python` and you can see the expected version output and `>>>` but when switching to the accessibility buffer, only the last command output is there. Apparently the buffer is not updating for commands that are currently running. This is not just for python, but for any command that shows output but does not stop running.

Apparently this bug started happening around the February 23rd 2023 update for vscode web being shipped to codespaces.
We can't use insiders because that is not an option on github codespaces.

Thanks for your time (:

**Comment by meganrogge** [comment]
same issue as #174797

we are planning to show all of the buffer contents this iteration - you can track that here

https://github.com/microsoft/vscode/issues/174079
