### ISSUE TITLE
Add "join line" keyboard shortcut

### ISSUE THREAD

**Issue by jkup** [Microsoft/vscode#1759]
This is a feature request! I'm hoping I have the right repository.

Other editors like Sublime Text and Atom have a keyboard shortcut for joining lines. In these editors, you can hit cmd+j ( or ctrl+j on Windows ) to append the following line to the current line. It would be really great to add this to Code!

Loving the editor so far!

**Comment by waderyan** [comment]
:+1: I find this feature very handy.

**Comment by fhelwanger** [comment]
There's already a extension for that: https://github.com/wmaurer/vscode-join-lines

But I agree that it should be in the core.

**Comment by leikind** [comment]
I had to install this extension, but this is such a basic operation, I believe it should be in the  core, too

**Comment by kabirbaidhya** [comment]
I think this is a very useful feature +1 along with other missing commands from atom & sublime. Vscode would be a lot better if it has all the commands available in both sublime & atom.

**Comment by subhaze** [comment]
Looks like it (with a few other commands from ST) landed https://code.visualstudio.com/updates#_sublime-text-compatibility

**Comment by waderyan** [comment]
Correct! Closed in 1.8

**Comment by theredpea** [comment]
Broken link to the release notes that included this feature, please try this link to see November 2016, header "Sublime Text compatibility" , which introduced this action: Join Lines - editor.action.joinLines https://code.visualstudio.com/updates/v1_8#_sublime-text-compatibility
