### ISSUE TITLE
Simple but useful features that every developer expects at first glance

### ISSUE THREAD

**Issue by ghominejad** [Microsoft/vscode#17598]
- VSCode Version: 1.8.0
- OS Version: Windows 10

1- Building selected file without installing and configuring tasks
    basic extensions : - scss  -less -typescript

2- Html live preview without needs for installing third-party webservers

vscode should support these features internally.

Currently i have to install these tools in every simple test projects and each of them have to be contained over 50mb  in size and 6000 nod-module files and configuring them is also time-consuming job

Thanks

**Comment by egamma** [comment]
@ghominejad thanks for your feature requests, pls try to follow the issue reporting guidelines and file a separate issue per feature request https://github.com/Microsoft/vscode/wiki/Submitting-Bugs-and-Suggestions#writing-great-issues-and-suggestions


>1- Building selected file without installing and configuring tasks

we do not plan to bundle transpilers for LESS and SASS. Support for transpiling typescript is tracked in #17587 973

>2- Html live preview without needs for installing third-party webservers

Duplicates #16081
