### ISSUE TITLE
Auto indent for most popular language

### ISSUE THREAD

**Issue by GNXB** [Microsoft/vscode#17596]
- VSCode Version: 1.8.1
- OS Version: macOS Sierra 10.12.2

Steps to Reproduce:

1. **Auto indent** features for most popular language such as PHP, CSS, etc.
2. **Hotkey** for performing auto indent when highlighting _some part_ of document or _whole document_

**Comment by egamma** [comment]
>Auto indent features for most popular language such as PHP, CSS, etc.

Auto indent is supported for many languages including CSS and PHP. Please file specific issues when auto indent doesn't work as expected.

>Hotkey for performing auto indent when highlighting some part of document or whole document

This is tracked in https://github.com/Microsoft/vscode/issues/4039

**Comment by borekb** [comment]
@egamma How is auto-indent supported now? All I see is auto-format which is a richer operation and can do transformations I am not interested in. Maybe I'm just overlooking something, having a standalone auto-indent feature would be awesome.

**Comment by egamma** [comment]
@borekb pls see this issue #17868
