### ISSUE TITLE
cannot scroll down to select (long) cell content

### ISSUE THREAD

**Issue by yuuuxt** [microsoft/vscode#175927]
### Applies To

- [X] Notebooks (.ipynb files)
- [ ] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

1. create a cell with contents that exceeds the length of screen;
2. try to use mouse to select the cell content (left click on top then drag & scroll down)

which is not working - vscode is trying to keep the position of the first click visible, so you cannot scroll down.

![temp](https://user-images.githubusercontent.com/3153534/217452289-44219698-82dc-4021-963c-c47ab569d17e.gif)

3. left click on top, then shift + left click at the end of selection - selection works, but it jumps back to show the first click position

4. start from button to select and scroll up works fine.

### VS Code Version

1.75.0

### Jupyter Extension Version

v2023.1.2010391206

### Jupyter logs

```shell
(NA)
```

### Running Jupyter locally or remotely?

Local

**Comment by yuuuxt** [comment]
Sorry, I meant this issue no longer exists on my side after I upgrade vscode to 1.76.0 along with extension upgrades (including Jupyter). I meant "it seems to be fixed, is that true?"

Also, I just tested on another machine, and the issue disappears after upgrading to 1.76.0, and before reloading new extensions.

**Comment by amunger** [comment]
ah, good to hear. I'll close since I haven't seen any other reports, but please re-open if you see it again.
