### ISSUE TITLE
Vs code not use terminal host and account !

### ISSUE THREAD

**Issue by DevWorking** [microsoft/vscode#176047]
Type: <b>Bug</b>

Vs code not use terminal host and account !

VS Code version: Code 1.76.0 (92da9481c0904c6adfe372c12da3b7748d74bdcb, 2023-03-01T10:22:44.506Z)
OS version: Windows_NT x64 10.0.19044
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Celeron(R) N4020 CPU @ 1.10GHz (2 x 1094)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: disabled_off<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|3.81GB (1.14GB free)|
|Process Argv|--crash-reporter-id d2707004-2228-4691-af24-e5d69bcd2206|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (50)</summary>

Extension|Author (truncated)|Version
---|---|---
bootstrap5-vscode|Anb|0.4.2
All-Autocomplete|Ati|0.0.26
blackbox|Bla|0.10.34
vscode-intelephense-client|bme|1.9.5
vscode-tailwindcss|bra|0.9.7
path-intellisense|chr|2.8.4
vscode-eslint|dba|2.4.0
javascript-ejs-support|Dig|1.3.3
es7-react-js-snippets|dsz|4.4.3
gitlens|eam|13.3.1
vscode-npm-script|eg2|0.3.29
react-native-react-redux|EQu|2.0.6
vsc-material-theme-icons|equ|2.6.1
prettier-vscode|esb|9.10.4
auto-close-tag|for|0.5.14
auto-complete-tag|for|0.1.0
auto-rename-tag|for|0.1.10
code-runner|for|0.12.0
vscode-google-translate|fun|1.4.13
google-translate|han|1.2.7
beautify|Hoo|1.5.0
reactnextjssnippets|iJS|1.6.0
vue|jcb|0.1.5
react-native-snippet|jun|0.5.6
google-fonts|lio|0.0.1
document|min|2.2.1
vscode-dotnet-runtime|ms-|1.6.0
vscode-react-native|msj|1.10.0
html-meta-tags-hero|nad|1.0.2
vscode-json-editor|nic|0.3.0
material-icon-theme|PKi|4.24.0
vscode-thunder-client|ran|2.5.0
live-sass|rit|3.0.0
LiveServer|rit|5.7.9
rocketseatreactnative|roc|3.0.1
es7-react-js-snippets|rod|1.9.3
mongo-snippets-for-node-js|roe|1.3.12
js-jsx-snippets|sky|11.0.1
autoimport|ste|1.5.4
sass-indented|syl|1.8.25
icons|tal|3.6.2
todo-list|Tza|1.6.0
intellicode-api-usage-examples|Vis|0.2.7
vscodeintellicode|Vis|1.2.30
vscode-icons|vsc|12.2.0
vscode-todo-highlight|way|1.0.5
JavaScriptSnippets|xab|1.8.0
ReactSnippets|xab|2.4.0
php-debug|xde|1.32.0
todo-highlighter|zer|1.0.1

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
pynewvextcfv2:30669238
azure-dev_surveyone:30548225
vsccc:30610678
pyindex848:30662994
nodejswelcome1:30587005
282f8724:30602487
pyind779:30671433
f6dab269:30613381
pythonsymbol12:30671437
a9j8j154:30646983
pythonb192:30669360
funwalk2cf:30676044

```

</details>

**Comment by LHF0608** [comment]
Do you mean that the account in the terminal is not used when opening from the terminal?
