### ISSUE TITLE
[FR] Ability to provide custom icons in QuickPickItem

### ISSUE THREAD

**Issue by a-stewart** [microsoft/vscode#176049]
Would it be possible to allow for extensions to provide icons in `QuickPickItem`s?

At the moment we can use `ThemeIcons` via the `$(icon)` syntax, but if we want to provide a custom icon that is more complex (perhaps we can do that be providing a font and a partial product icon theme?).

With a `TreeItem`, we can pass in an optional icon path:  
```
iconPath?: string | Uri | { light: string | Uri; dark: string | Uri } | ThemeIcon;
```

Could we add this to QuickPickItem too?

Based on the quick open input, there is already space afforded in the UI for the icon, so it would be useful if extensions to provide one.

**Comment by a-stewart** [comment]
Related to #59826 which asks for the ability to specify filetype icons.

**Comment by alexr00** [comment]
For anyone curious, circles are possible by using data URIs:

Example 
https://github.com/microsoft/vscode-pull-request-github/blob/9ae4772d821c37d7acb7a9c1d0aa3ebbece0be0c/src/common/uri.ts#L156-L177 and copied here for reference:

```typescript
export function asImageDataURI(contents: Buffer): vscode.Uri {
	return vscode.Uri.parse(
		`data:image/svg+xml;size:${contents.byteLength};base64,${contents.toString('base64')}`
	);
}

export async function circleAsImageDataUri(imageSourceUrl: string | undefined, height: number, width: number): Promise<vscode.Uri | undefined> {
	if (imageSourceUrl === undefined) {
		return undefined;
	}

	const response = await fetch(imageSourceUrl);
	const buffer = await response.arrayBuffer();
	const innerImageContents = Buffer.from(buffer);
	const innerImageEncoded = `data:image/jpeg;size:${innerImageContents.byteLength};base64,${innerImageContents.toString('base64')}`;
	const contentsString = `<svg width="${width}" height="${height}" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
	<image href="${innerImageEncoded}" width="${width}" height="${height}" style="clip-path: inset(0 0 0 0 round 50%);"/>
	</svg>`;
	const contents = Buffer.from(contentsString);
	const finalDataUri = asImageDataURI(contents);
	return finalDataUri;
}
```
