### ISSUE TITLE
Latest release of VSCode (1.76.0) breaks first party extensions including "WAVE for Windows"

### ISSUE THREAD

**Issue by matt-desai** [microsoft/vscode#176006]
looks related to "I cannot build my VSCode extension project in VSCode after update to 1.76"  Issue #175833 

•	Our first party Extensions such as "WAVE", which is required by Windows developers to write and compile their code, have been broken for developers on the latest VSCode release (1.76.0), starting with c4a609f94329b17d91cd13a4fd113d1abfe5ec1f

Typically, when a dev opens a folder in the OS repo, the Wave extension is activated and begins to initialize and 'restore dependencies', by running a few scripts, setting up the build environment.  in >= 1.76.0, we briefly see "Activating extensions..." in the status bar then it abruptly stops. 

•	Windows developers on release 1.76.0 have been unable to do their work in VSCode since the release 
•	When users revert to version 1.75, the issues don't happen anymore; the extension is activated, scripts run, and the environment is properly prepared.

What we know so far: 
•	Our WAVE extension is loaded, at least momentarily and initialization begins, but fails and exits fairly early on
o	Per the comment from the GitHub issue above, we listened for error messages in devtools (Help > Toggle Developer Tools)
o	VSCode output has very few details in the log, and not very helpful to debug
o	Our wave extension architect tried debugging and noticed that the build does not complete. VSCode attempts to launch WAVE but then sharply exits the process with no indication in the debugger for what is happening under the hood.
 No log info in debugger that indicates why the “Activating extensions” process quits.

Results of npx vscode-bisect:
    √ Is c4a609f94329b17d91cd13a4fd113d1abfe5ec1f good or bad? » **Bad**
    ...
    √ Is 9a1ee564ee63315b690670ed68b9d3fe37e3b291 good or bad? » **Good**

    **c4a609f94329b17d91cd13a4fd113d1abfe5ec1f** is the first bad commit after 
    9a1ee564ee63315b690670ed68b9d3fe37e3b291.

[Comparing 9a1ee564ee63315b690670ed68b9d3fe37e3b291...c4a609f94329b17d91cd13a4fd113d1abfe5ec1f · microsoft/vscode · GitHub](https://github.com/microsoft/vscode/compare/9a1ee564ee63315b690670ed68b9d3fe37e3b291...c4a609f94329b17d91cd13a4fd113d1abfe5ec1f)

**Comment by matt-desai** [comment]
I built and ran git bisect which narrowed it down to this commit:

Bisecting: 0 revisions left to test after this (roughly 0 steps)
[1108c31f0d0b4852786db42904a135acb56209a5] Adopt `activationEventsGenerator` for `onTaskType` (#173192)

**Comment by bpasero** [comment]
Just wanted to say 👏 for doing the bisecting even down to the committ.

**Comment by gjsjohnmurray** [comment]
Looks related to #175821

**Comment by GabeDeBacker** [comment]
I can confirm that if I remove the task definitions from our extension, that I am able to load our WAVE extension and hit breakpoints in the debugger (obviously with limited functionality). Our Mocha tests also start whereas they did not start before with 1.76.

**Comment by alexdima** [comment]
The commit https://github.com/microsoft/vscode/commit/1108c31f0d0b4852786db42904a135acb56209a5 will add the `onTaskType:X` activation event to the activation event array for extensions contributing a specific task type `X`.

The only way I can imagine this could backfire:
* the extension contributes a task of type `X`
* the extension did not have `onTaskType:X` as an activation event so far
* the extension has a bug where its `activate()` method returns a promise which never completes
* we will now wait with launching debugging and tasks on `activateByEvent(onTaskType:X)`. That means to wait on all extensions that want to activate on this event to activate. If the extension never activates (its returned promise never completes), things will stall indefinitely.

Could you please check that the promise you return from the `activate()` function resolves?

**Comment by GabeDeBacker** [comment]
Can you clarify:
_The extension did not have "onTaskType:X" as an activation event_ ?

I can confirm that we do not have "onTaskType:X" in our package.json, but we also never have. 

In the meantime, I'll step through our activate() promise and see if it completes.

**Comment by GabeDeBacker** [comment]
I've added onTaskType: to our package.json activation events, and that had no affect. But, yes, our activate() promise is never completing because it is performing:

``ts
const tasks = await vscode.tasks.fetchTasks();
```

during the activation and it **never completes**.

I'm going to change this to not "await" and report back.

**Comment by alexdima** [comment]
> Is it possible that because our extension is activating AND provides tasks AND is calling fetch tasks during its activation that it causes some sort of "hang" inside VSCode?

Yes! It looks like a dead-lock. Most likely:
* the extension `activate()` waits on `vscode.tasks.fetchTasks()`
* `vscode.tasks.fetchTasks()` waits on `activateByEvent(onTaskType:X)`
* `activateByEvent(onTaskType:X)` waits on the extension `activate()`

**Comment by microhobby** [comment]
I'm using `const tasks = await vscode.tasks.fetchTasks();` in my extension and this does not resolve only when I have some other extensions, that maybe provide tasks, crashing during the activation. If I uninstall the "crashing" extension this resolves and fix the issue. This behavior started with `v1.76.0`

**Comment by GabeDeBacker** [comment]
@alexr00 any chance we can diagnose and fix soon?

**Comment by GabeDeBacker** [comment]
Typed that last comment from my phone :) Let me clarify my concern. While we can work around this in our extension because we understand the issue, it appears that if any other extension has similar code that it may block extension startup. Thank you @microhobby for looking into this.

**Comment by meganrogge** [comment]
I can reproduce this issue even when I revert the change that was made last iteration, so I believe this has been a bug for some time. Was there a change made in the wave extension within the past month @GabeDeBacker ?

**Comment by meganrogge** [comment]
I cannot reproduce in 1.75 though, which makes me wonder if something else changed in VS Code that could explain this

**Comment by Tyriar** [comment]
Since an extension can literally break tasks this probably should be a candidate, even though the root cause is an (easy to cause) extension bug.

**Comment by meganrogge** [comment]
Yes I agree, though this is reproducible in earlier versions. @Tyriar

**Comment by meganrogge** [comment]
Repro was an extension contributes tasks or uses `onTaskType:X` as an `activationEvent` and has `await vscode.fetchTasks()` in its `activate` method.

Try to run a task of type `X`. 🐛  the progress bar loads forever and extension activation status bar item spins forever.

**Comment by microhobby** [comment]
Hmmm, using the new `1.76.1` but the `await vscode.fetchTasks()` continues not returning ...

Is needed some changes on the extension level?
