### ISSUE TITLE
terminal link hover state still exists after clear terminal

### ISSUE THREAD

**Issue by tjx666** [microsoft/vscode#176037]
Reproduce:

1. run `pwd` util the output take one screen
2. click and hover to the link
3. clear terminal with shortcut
4. you can see the hover link still exists

```
Version: 1.76.0 (Universal)
Commit: 92da9481c0904c6adfe372c12da3b7748d74bdcb
Date: 2023-03-01T10:23:45.993Z
Electron: 19.1.11
Chromium: 102.0.5005.196
Node.js: 16.14.2
V8: 10.2.154.26-electron.0
OS: Darwin x64 22.3.0
Sandboxed: No
```

https://user-images.githubusercontent.com/41773861/222714797-e28f2fc0-bd8d-4b4f-a43d-1b3bc9ac7af1.mov

**Comment by tjx666** [comment]
@Tyriar What's your opinion about it?

**Comment by Tyriar** [comment]
It's a bug, tracked in https://github.com/microsoft/vscode/issues/187137 and https://github.com/xtermjs/xterm.js/issues/4586

/duplicate
