### ISSUE TITLE
Weird Tab Intendation Issue on Mac OS

### ISSUE THREAD

**Issue by oborchers** [microsoft/vscode#176061]
I have an extremely weird behavior of my Tab Key on MacOS. Somehow it is intending using spaces but somehow not?

- VS Code Version: Version: 1.76.0
Commit: 92da9481c0904c6adfe372c12da3b7748d74bdcb
Date: 2023-03-01T10:23:45.993Z
Electron: 19.1.11
Chromium: 102.0.5005.196
Node.js: 16.14.2
V8: 10.2.154.26-electron.0
OS: Darwin x64 21.5.0
Sandboxed: No
- OS Version: macOS Monterey 12.4

Steps to Reproduce: I don't know.

https://www.icloud.com/iclouddrive/081V5v_nvBBtAczX6pSoIk0OA#Bildschirmaufnahme_2023-03-03_um_16.53
https://www.icloud.com/iclouddrive/00chvyt3evrD1Of6n_pRjOBNQ#Bildschirmaufnahme_2023-03-03_um_16.49
https://www.icloud.com/iclouddrive/0927VHRmjKCCZHKWIc8qahu3A#Bildschirmaufnahme_2023-03-03_um_16.48

**Comment by hediet** [comment]
Thanks for sharing the screenrecordings! Could you please upload them to GitHub?

**Comment by oborchers** [comment]
@hediet https://github.com/oborchers/vscode-error-report

**Comment by hediet** [comment]
Unfortunately I don't understand what is going on in your screenrecordings.

Does it reproduce when you disable all extensions?

**Comment by oborchers** [comment]
@hediet: Basically what happens is the following: This is Pyhton, indentation is always 4 spaces for me. The code in there is all correctly formatted by autoformatting.

For some weird reason, or some key combination, it seems the "size" of my indentation using the Tab key changed. If you watch carefully, in one video I am unindenting the decorator `@patch(pathidir + ...)` and re-indenting it next but the indentation is wrong. Despite that fact, that vscode shows me four `....` transparent blobs.

It seems the size of my indentation whitespace magically changed somehow, vscode still registers `....` but I am unable to compile the code because of an indentation issue.

I was only able to solve this by copying some other whitespace whenever I needed a tab. I was unable to reproduce this, nor am I able to tell you how to get there. It just happened out of the blue for some weird reason and is gone now.

**Comment by hediet** [comment]
Unfortunately, we cannot do much without reproduction steps (it might even be caused by an extension).
Please create a new issue if you run into this consistently!
