### ISSUE TITLE
Release notes do not use full windows area when zooming

### ISSUE THREAD

**Issue by ralfkret** [Microsoft/vscode#17602]
- VSCode Version: Code 1.8.1 (ee428b0eead68bf0fb99ab5fdc4439be227b6281, 2016-12-19T14:49:23.350Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

|Extension|Author|Version|
|---|---|---|
|vim|vscodevim|0.4.9|

---

Maybe duplicate of #17580. Sorry should have searched before posting.

Steps to Reproduce:

1. Open Release Notes
2. Zoom with ctrl-+
3. When zooming further the effect is more prominent.

**Comment by egamma** [comment]
This is known issue with the webviews. 

@jrieken I suspect that this is a dupe, but I could not find one.

**Comment by jrieken** [comment]
dupe #5745
