### ISSUE TITLE
*.txt file save and open bug

### ISSUE THREAD

**Issue by GameHoo** [Microsoft/vscode#17601]
- VSCode Version: Code 1.8.0 (38746938a4ab94f2f57d9e1309c51fd6fb37553d, 2016-12-13T17:45:32.595Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

|Extension|Author|Version|
|---|---|---|
|vscode-babel-coloring|dzannotti|0.0.4|
|vscode-great-icons|emmanuelbeziat|1.1.25|
|cpptools|ms-vscode|0.9.2|

---

Steps to Reproduce:

1.Create a txt file ,
2.type some thing and don't save.
3.click the close button
4.doubleclick the file ,open it
5.now VSCode open the file twice(two windows),but it should be one.

**Comment by bpasero** [comment]
Is this https://github.com/Microsoft/vscode/issues/16820 ?

**Comment by GameHoo** [comment]
yes sorry
