### ISSUE TITLE
Code Window does not show the different open projects in the menu.How can i rollback?

### ISSUE THREAD

**Issue by stefanaerts** [Microsoft/vscode#17605]
- VSCode Version:Version 1.8.1 (1.8.1)
- OS Version:MAC OS X 10.9.5

Steps to Reproduce:

1. open 2 projects at the same time
2. go to window menu

![image](https://cloud.githubusercontent.com/assets/3684599/21349842/807b1432-c6b4-11e6-8eb7-41e4665a68db.png)

**Comment by egamma** [comment]
On OS X opened windows are shown in the Dock menu for VS Code.
On all platforms there is the 'Switch Windows' command provided in the Command palette.

**Comment by stefanaerts** [comment]
so how can i rollback? I like to a list with open projects and switch with 1 or 2 clicks

**Comment by egamma** [comment]
@stefanaerts 

There are two options:

>so how can i rollback? 

If you do not like the history list provide by the menu in the dock, there are several other options:

- `File>Open Recent` which is bound to ^R, see the attached recording. This is the recommended way.
![open-recent](https://cloud.githubusercontent.com/assets/172399/21483566/a3f250ea-cb84-11e6-87e3-54d20c5c5741.gif)

- `Switch Windows` which can be bound to a key if desired
![switch-windows](https://cloud.githubusercontent.com/assets/172399/21483576/e98a46bc-cb84-11e6-990e-710ad18dedd0.gif)

**Comment by stefanaerts** [comment]
before i had the list in dock also,but also a list with open projects in window next to help on top of the screen

**Comment by egamma** [comment]
@stefanaerts this list is already shown in the `Windows` menu, isn't it?

![image](https://cloud.githubusercontent.com/assets/172399/21496737/edf6acf8-cc20-11e6-9e37-edbe0cba948e.png)

Another quick way to switch among the open windows is command+`

**Comment by stefanaerts** [comment]
Hi,since my last update it's not showing the list in the menu any more

Op 27 dec. 2016 10:43 a.m. schreef "Erich Gamma" <notifications@github.com>:
