### ISSUE TITLE
CMake Intel DPC++ compiler support

### ISSUE THREAD

**Issue by SergMariaDB** [microsoft/vscode#176055]
Please, consider adding  Intel DPC++ compiler support to CMake kits detection.

Here is some info https://www.intel.com/content/www/us/en/develop/documentation/oneapi-dpcpp-cpp-compiler-dev-guide-and-reference/top/compiler-setup/use-the-command-line/use-cmake-with-the-compiler.html

The one may be downloaded here:
 https://www.intel.com/content/www/us/en/develop/documentation/oneapi-dpcpp-cpp-compiler-dev-guide-and-reference/top/compiler-setup/use-the-command-line/use-cmake-with-the-compiler.html

**Comment by deepak1556** [comment]
Are you using https://github.com/microsoft/vscode-cmake-tools extension ? If so, please open an issue in that repository.

**Comment by SergMariaDB** [comment]
Thanks, the issue created https://github.com/microsoft/vscode-cmake-tools/issues/3045
