### ISSUE TITLE
Extensions editor: color clash with tabs

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#17603]
This looks as if the contents of the editor belong to Position.js:

![image](https://cloud.githubusercontent.com/assets/900690/21349308/89245ad8-c6b1-11e6-877b-c99a253bd5ce.png)

**Comment by joaomoreno** [comment]
Unfortunately it's a huge coincidence, which seems to happen to the Dark theme family. Can't really fix this unless you add a horizontal line. All other themes look perfect.

![image](https://cloud.githubusercontent.com/assets/22350/21610313/85bc9f38-d1c7-11e6-995c-a90b6a79e9c5.png)

![image](https://cloud.githubusercontent.com/assets/22350/21610318/8ebc9926-d1c7-11e6-8321-e6705aebb7eb.png)

![image](https://cloud.githubusercontent.com/assets/22350/21610321/977f1ff2-d1c7-11e6-94bb-5b091a6e19b3.png)

**Comment by R3V07T** [comment]
Difficult to explain how  to stop but I can show you

Sent from Mail for Windows 10

**Comment by bpasero** [comment]
We used to have a separator line but we removed it after @bgashler1 suggestion (which I still like). Maybe he has an idea how to solve this particular case better.

**Comment by bgashler1** [comment]
Yeah, that doesn't look quite right.  I probably need to play around with this one a little bit.  Just a quick idea I had (did it really fast, but will spend more time on this later).
![screen shot 2017-01-03 at 4 01 13 pm](https://cloud.githubusercontent.com/assets/11839736/21627609/e3659b52-d1cd-11e6-8158-ff70088dd0be.png)

I made the header to have `background: hsla(0,0%,50%,.25); border-top: 1px solid #252526;`

**Comment by joaomoreno** [comment]
Won't fix.
