### ISSUE TITLE
When debugging NodeJS code, can not step into functions

### ISSUE THREAD

**Issue by foogao** [Microsoft/vscode#17600]
- VSCode Version: 1.8.1
- OS Version: macOS Sierra

Steps to Reproduce:

1. Open project
2. Setup breakpoint
3. Click "Start Debugging" button
4. Code stop at the breakpoint
5. Click the "Step Into" button, the code will execute until next breakpoint.

Anyone meet this issue?

**Comment by weinand** [comment]
@foogao do you have a watch expression? If yes, please delete them and see whether problem disappears.

**Comment by foogao** [comment]
@weinand yes, i have some watch expressions, just remove them, works now. thanks

But why? "Watch expression" should be a common scenario, right? Is this a bug?

**Comment by weinand** [comment]
@foogao yes, this is a bug. Dup of https://github.com/Microsoft/vscode/issues/15253

**Comment by foogao** [comment]
@weinand OK, got it, thanks
