### ISSUE TITLE
Format document does not work at least on xml files

### ISSUE THREAD

**Issue by christianarg** [Microsoft/vscode#17604]
- VSCode Version: Code 1.8.1 (ee428b0eead68bf0fb99ab5fdc4439be227b6281, 2016-12-19T14:49:23.350Z)
- OS Version: Windows_NT ia32 6.3.9600
- Extensions:

|Extension|Author|Version|
|---|---|---|
|vs-code-xml-format|fabianlauer|0.1.4|
|ColdFusion|ilich8086|0.0.4|
|csharp|ms-vscode|1.5.3|

---

Steps to Reproduce:

1. Open Xml File
2. Format Document
3. You'll get the WARN Cannot read property 'substring' of undefined.

Just updated to this version 1.8.1 worked fine a minute ago before updating

**Comment by NikIvan** [comment]
It seems that format document also doesn't work in CSS.

- VSCode Version: Code 1.8.1 (ee428b0eead68bf0fb99ab5fdc4439be227b6281, 2016-12-19T14:49:23.350Z)
- OS Version: Windows_NT ia32 6.3.9600
- Extensions:

|Extension|Author|Version|
|---|---|---|
|theme-atom-one-dark|andischerer|0.0.1|
|theme-material-neutral|bernardodsanderson|0.9.0|
|vscode-eslint|dbaeumer|1.2.2|
|vscode-babel-coloring|dzannotti|0.0.4|
|autofilename|JerryHong|0.1.3|
|theme-oceanicnext|naumovs|0.0.4|
|view-in-browser|qinjia|0.0.3|
|jsx|TwentyChung|0.0.1|

---

Steps to Reproduce:

1. Open unformatted CSS file
2. Press Shift+Alt+F ( Or your key combination to format code)
3. Nothing happens

P.S. Thanks for awesome code editor :)

**Comment by egamma** [comment]
@christianarg formatting of XML is not provided by VS Code but by  an extension. I see that you have the `vs-code-xml-format` extension installed pls report the issue against the repository of this extension https://github.com/FabianLauer/vs-code-xml-format.

**Comment by egamma** [comment]
@NikIvan glad you like the editor.

Actually VS Code doesn't support formatting of CSS out of the box, but there are extension that support this. A popular one is [Beautify](https://marketplace.visualstudio.com/items?itemName=HookyQR.beautify)
