### ISSUE TITLE
VScode git revert line multiplies reverted changes in the file

### ISSUE THREAD

**Issue by weeTike** [microsoft/vscode#176051]
Type: <b>Bug</b>

Since the 1.76.0 release, when multiple git repositories in your working folder structure and you open the 'git local working changes' UI and click 'revert changes', your changes will be copied into the current file, multiple times.
- One git repo: works fine
- two git repos: nothing happens
- three+ git repos: changes are copied multiple times, seemingly related to the number of git repositories.

As you can see, only one file with one change exists yet the window lists 6
![image](https://user-images.githubusercontent.com/78800409/222756561-12d80acc-70a4-4ea7-b732-ad79a3c2df81.png)

When revert changes is clicked, the line with the change is then copied many times in the file.
![image](https://user-images.githubusercontent.com/78800409/222756768-e68a308f-1c5d-4502-9367-cd3ea78f9930.png)

### Steps to reproduce:
1. Create a folder of any name
2. Inside this folder create three additional folders
3. Git init all three folders
4. Open the initial folder in vscode so the three git folders are visible
5. Create a file in one of these folders, write any text, and save.
6. Git add the file you made the changes to.
7. Make more changes to the file, then try to revert them.

VS Code version: Code 1.76.0 (92da9481c0904c6adfe372c12da3b7748d74bdcb, 2023-03-01T10:25:16.105Z)
Also tested on 1.77.0-insider
OS version: Linux x64 5.19.0-32-generic snap
Also tested on windows _NT x64 10.0.19045
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|12th Gen Intel(R) Core(TM) i9-12900 (24 x 3117)|
|GPU Status|2d_canvas: unavailable_software<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>opengl: disabled_off<br>rasterization: disabled_software<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software<br>webgpu: disabled_off|
|Load (avg)|1, 1, 1|
|Memory (System)|31.05GB (2.70GB free)|
|Process Argv|--no-sandbox --crash-reporter-id 0b531465-88ca-41be-adc7-4346a7bd507f|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|undefined|
|XDG_CURRENT_DESKTOP|undefined|
|XDG_SESSION_DESKTOP|awesome|
|XDG_SESSION_TYPE|x11|
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
pynewvextcfv2:30669238
azure-dev_surveyonecf:30548226
pyindex848:30662994
nodejswelcome1cf:30587006
3biah626:30602489
pyind779:30671433
f6dab269:30613381
vscrp:30673768
pythonsymbol12:30671437

```

</details>

**Comment by ahejlsberg** [comment]
I'm seeing this issue too.

**Comment by bugo-nordic** [comment]
This critically affects me as well. My workspaces have multiple git repositories and submodules. Currently builtin source control is unusable for me

**Comment by gangefors** [comment]
This affected me as well in a workspace with multiple submodules.

**Comment by larshp** [comment]
also see https://github.com/microsoft/vscode/issues/175535

**Comment by gayanper** [comment]
I can confirm this issue, the diff editor revert is totally broken. Not sure if this is isolated only to multi module workspaces.

**Comment by gayanper** [comment]
Seems to be this is a issue with inline diff editor, 
1. In editor from vcs gutter, revert doesn't work
2. from version control if I use the diff editor, I can revert changes, But I cannot revert added lines from inline editor, But if i use the side by side editor, it works fine.

**Comment by j-lakeman** [comment]
Can confirm for
```
Version: 1.76.0
OS: Darwin x64 20.6.0
```

**Comment by microhobby** [comment]
Same here

```
Version: 1.76.0
Commit: 92da9481c0904c6adfe372c12da3b7748d74bdcb
Date: 2023-03-01T10:22:44.506Z (4 days ago)
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) 
AppleWebKit/537.36 (KHTML, like Gecko) Code/1.76.0 
Chrome/102.0.5005.196 Electron/19.1.11 Safari/537.36
```

**Comment by gjsjohnmurray** [comment]
@alexr00 could this have been caused by the recent QuickDiffProvider changes?

**Comment by alexr00** [comment]
Yes, it could be caused by the quick diff changes. Thank you for the @ mention @gjsjohnmurray!

**Comment by joyceerhl** [comment]
@alexr00 with the latest stable build, I initially did not see the gutter indicator after making a local change. A reload fixed things though.

**Comment by natashaganjoo** [comment]
Seeing this issue since last week.

**Comment by DFelten** [comment]
Issue is still there on the latest version of VSCode :( Therefore, I cannot currently use the Insider version.

**Comment by DFelten** [comment]
> Can you tell me the version?
> I think it was fixed in version 1.76.2

Version: 1.77.0-insider
Commit: c97d5812f10c28efbcdb1fd404bc25afae873312
Date: 2023-03-16T05:37:57.680Z
Electron: 19.1.11
Chromium: 102.0.5005.196
Node.js: 16.14.2
V8: 10.2.154.26-electron.0
OS: Darwin arm64 22.3.0
Sandboxed: Yes

**Comment by alexr00** [comment]
@DFelten can you provide exact steps to reproduce your issue?

**Comment by DFelten** [comment]
I already created a ticket for this issue here: https://github.com/microsoft/vscode/issues/175535

On a new project with small changes it's working. But on a large project there is still this issue.

Example video:

https://user-images.githubusercontent.com/1169185/225607453-4fd73cb2-9393-43b1-b325-0ec379d8ad3a.mp4

**Comment by alexr00** [comment]
@DFelten I'm not able to reproduce your issue. Can you provide exact steps (as in https://github.com/microsoft/vscode/issues/176051#issue-1608823294, where the steps make it easy to reproduce the issue every time)?

**Comment by DFelten** [comment]
@alexr00 I can't send you steps to reproduce for the moment because we work with private repositories.

However, I have found out what the problem is. We use a git project and a submodule within it. In the submodule it is not possible to undo changes. But in the main repository it is possible.

**Comment by DFelten** [comment]
> I can reproduce the problem with sub-modules.

Should I create a new issue or will this ticket be reopened here and continue to be used for this?

**Comment by alexr00** [comment]
A new issue would better. I wouldn't expect the original fix to have anything to do with submodules.

**Comment by DFelten** [comment]
> A new issue would better. I wouldn't expect the original fix to have anything to do with submodules.

Ok, I've created a new issue here https://github.com/microsoft/vscode/issues/177453

**Comment by lamnguyenx** [comment]
> @alexr00 I created a ticket for this issue here: #175535
> 
> On a new project with small changes it's working. But on a large project there is still this issue.
> 
> Example video:

I'm having the same issue. This is really annoying since I'm working with multiple submodules and constantly use "revert changes" once the refactoring fails.
