### ISSUE TITLE
Can't use terminal to full capabilities. Default shortcuts are getting in the way.

### ISSUE THREAD

**Issue by HackerDaGreat57** [microsoft/vscode#176009]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.76.0
- OS Version: Ubuntu 22.10 x64

Steps to Reproduce:
1. Open the terminal. Any shell (bash, zsh, Windows CMD, etc)
2. Try to pass <kbd>Alt</kbd> + <kbd>V</kbd> (for example) to a program
3. Watch the menu pop up when nobody asked

<kbd>Alt</kbd> + <kbd>V</kbd> is not passed to the program and it really throws off my flow. Is it possible to implement a "zen terminal" mode, perhaps, that disables all keyboard shortcuts so they can be passed to the terminal?

VS Code's built in terminal is the best one available to me (full ASCII RGB color support, what more could I ask for?!). I'd like it even more if I could use all my programs without having to change their bindings, like the one that uses <kbd>Alt</kbd> + <kbd>V</kbd>.

**Comment by Tyriar** [comment]
See https://code.visualstudio.com/docs/terminal/advanced#_keybinding-and-the-shell

You can set `terminal.integrated.sendKeybindingsToShell` to false to prefer the terminal which I think is what you're after. There's also fine tuning you can do with `terminal.integrated.commandsToSkipShell`, `terminal.integrated.allowMnemonics` and `terminal.integrated.allowChords`

**Comment by HackerDaGreat57** [comment]
Oh that's interesting. Thanks.
