### ISSUE TITLE
Progress-indicator for tasks

### ISSUE THREAD

**Issue by JensLykkeBrandt** [microsoft/vscode#17607]
Tasks that runs often when editing details in html/css/js can be better integrated into VS Code.
A tiny, simple progress-indicator in the status-bar or in the left bar would be cool.

Calculating the progress can be estimated from previous run:  first run can be the endless-progress-animation.
A click somewhere can pull the output into the editor-window for inspection (with 'markup' for grunt/gulp/webpack-output)

**Comment by dbaeumer** [comment]
Hmm, there is a progress indicator for tasks. The spinning / in the left corner of the status bar next to the error indicator. Are you suggesting a % progress indicator?

**Comment by JensLykkeBrandt** [comment]
Yes. 

The spinning wheel is... well... a bit dated. In a nostalgic ASCII-kind of way :-)
A progress-indicator is less stressful if its reliable: the spinning doesn’t tell me if a sub-task is hanging or not – all I can do is wait patiently. Not a typical programmer-skill close to a deadline.

But creating a progress-indicator is hard. Often the output is almost identical to the last run, but what if it’s not? And creating something like the task-problem-matcher is not the best idea: it’s too cumbersome for many (or just me anyway).
Progress done the way the task-problem-matcher works could be easier though: define steps in task-output via regex. And animate from time consumed at last run.

Or throw some deep-learning after it: shouldn’t be hard to decipher a build-script :-)

**Comment by jlk** [comment]
I've never seen the spinning / which dbaeumer speaks of. When I'm waiting on a build to see if there's errors or not, would be very handy to know if the build is complete, or no...

**Comment by dbaeumer** [comment]
The ASCII spinner got replaced by a 'Building..' string. However note that this is only show if a building task is executed. Normal task simply show up with the task status icon (the tools icon in the lower left part of the status bar)
