### ISSUE TITLE
Explorer Missing from Primary Side Bar

### ISSUE THREAD

**Issue by RatnadeepSimhadri** [microsoft/vscode#176136]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: Version: 1.76.0 (Universal)
- OS Version: macOS Monterey

Steps to Reproduce:
![image](https://user-images.githubusercontent.com/9788837/222923381-63e40c04-9211-40f1-8991-28210051cfc6.png)

**Comment by gjsjohnmurray** [comment]
Does https://github.com/microsoft/vscode/issues/176030#issuecomment-1454008617 help you find it?

**Comment by godoyLeonardo** [comment]
> Does [#176030 (comment)](https://github.com/microsoft/vscode/issues/176030#issuecomment-1454008617) help you find it?

Not OP, but currently having the same problem. It is like if the whole explorer was uninstalled. 

![image](https://user-images.githubusercontent.com/40327729/223226548-f1805a17-ba15-4cd6-80f0-5208c176708c.png)

but as soon as it finishes loading git/settings and everything important, it disappears.

I can't activate it with the left context menu either.

**Comment by sbatten** [comment]
Please try the command "Reset View Locations"
