### ISSUE TITLE
Too big system resources (RAM, CPU) usage by the editor

### ISSUE THREAD

**Issue by mdziczkowski** [microsoft/vscode#176184]
Type: <b>Bug</b>

### Description:
The editor has a too huge system resources (CPU, RAM) usage and memory fotprint.

The minimal declared Virtual Memory usage is over 32 GB and (currently) maximal one is over 54 GB. The average CPU usage of one core is keept thru long period of time at about 100%

### Environment
- **VS Code version**: Code 1.76.0 (92da9481c0904c6adfe372c12da3b7748d74bdcb, 2023-03-01T10:25:16.105Z)
- **OS version**: Debian 10
- **OS arch**: amd64
- **Modes**:
- **Sandboxed**: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD C-60 APU with Radeon(tm) HD Graphics (2 x 800)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: disabled_off<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|2, 1, 1|
|Memory (System)|15.30GB (10.35GB free)|
|Process Argv|--no-sandbox --crash-reporter-id df0f6290-96eb-47cb-a727-4098ba22fb34|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|undefined|
|XDG_CURRENT_DESKTOP|LXQt|
|XDG_SESSION_DESKTOP|undefined|
|XDG_SESSION_TYPE|undefined|
</details>

**Comment by bpasero** [comment]
Can you follow this wiki and post the results back here to understand more about why performance is so bad for you: https://github.com/Microsoft/vscode/wiki/Performance-Issues

Thanks!

**Comment by mdziczkowski** [comment]
I will check it as soon as I can. I'll message you again when I get the info
