### ISSUE TITLE
Wrong autocomplete popup opened with shortcut

### ISSUE THREAD

**Issue by ccarcaci** [microsoft/vscode#176173]
The suggestion menu is different when triggered automatically by the editor and when triggered using keyboard shortcut.

Does this issue occur when all extensions are disabled?: Yes

- VS Code Version:
```
% code --version
1.76.0
92da9481c0904c6adfe372c12da3b7748d74bdcb
x64
```
- OS Version: 
```
% system_profiler SPSoftwareDataType
Software:

    System Software Overview:

      System Version: macOS 13.2.1
      Kernel Version: Darwin 22.3.0
      Boot Volume: Macintosh HD
```

Steps to Reproduce:

1. Set `"typescript.suggest.enabled": false` in `settings.json`
2. Open a typescript file and in a var module reference enter dot `.` and trigger the suggestion menu with the shortcut `Ctrl+Space` (`^+Space` on OSX)
3. The suggestion menu is different than the one shown when `"typescript.suggest.enabled": true`

A walkthrough record is attached.

The same issue occurs also with Java code (and [related extension](https://marketplace.visualstudio.com/items?itemName=redhat.java) enabled).

https://user-images.githubusercontent.com/7973726/222965959-b81b37c6-0742-4b78-be5d-be2a17dc7c24.mov

**Comment by IllusionMH** [comment]
Don't see how it's different. You just have text based suggestions instead of language specific that have icons corresponding to their type (and other additional data on the right).

Not sure what you expect to see when you disable language specific suggestions.

**Comment by jrieken** [comment]
@ccarcaci please clarify what you expect? For now this seems like "works as designed": you disable a contributor to a feature and observe that

**Comment by ccarcaci** [comment]
Ok, that's clear, I was thinking that disabling the suggestion meant "don't show them on typing but let the user recall them with keyboard shortcut or right-click menu".

I'd like to maintain language-specific suggestions but recall them when needed using keyboard shortcut or right-click contextual menu.

**Comment by ccarcaci** [comment]
Found it!
`"editor.suggestOnTriggerCharacters": true,`

Sorry for bothering you, I didn't read very careful all the settings (even though they are many).

**Comment by jrieken** [comment]
Ok, thanks for coming back to us
