### ISSUE TITLE
Consider adopting a new XML grammar: XML comment bug due to deprecated atom/language-xml grammar

### ISSUE THREAD

**Issue by tobil4sk** [microsoft/vscode#176193]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.76.0
- OS Version: Windows 11/Linux

Steps to Reproduce:

1. Create a new xml document
2. Paste the following xml, or any xml which contains a comment ending in `--->` with more than 2 dashes
```xml
<test>
<!-- comment --->
</test>
```
3. View the broken xml highlighting:
![image](https://user-images.githubusercontent.com/41230637/222994553-d6e322e9-9450-445d-8ed5-98fa7ff41604.png)

This issue was previously reported here: in #58076 and #62221, however, the bug reports were moved to the atom/language-xml repository. Over there, a PR was eventually opened to solve the issue: https://github.com/atom/language-xml/pull/101. However, since Atom is now discontinued, the PR will never be merged into the atom/language-xml repository.

To fix this bug, VSCode will have to switch to a different XML grammar, like for PHP (see #162707) and all the other grammars it uses from Atom.

**Comment by alexr00** [comment]
Looks like the example is not well-formed xml: https://www.w3.org/TR/REC-xml/#sec-comments

**Comment by tobil4sk** [comment]
It is not well formatted and the error is marked with a red highlight as expected, however, it would still be nice if this error being present didn't completely break syntax highlighting in the rest of the file. Other xml syntax highlighters (like the one built into github) are able to recover from this error and still highlight the rest of the file correctly.
