### ISSUE TITLE
Update fails without error, asks again at restart.

### ISSUE THREAD

**Issue by rafalou38** [microsoft/vscode#176128]
Type: <b>Bug</b>

I opened this issue some time ago (#168782), and reinstalling vscode did fix the issue, but now the same bug is back.

Steps:
Click on "update now"

Vscode restarts

The same message appears again.

VS Code version: Code - Insiders 1.75.0-insider (b229eb5fa2ecadb8a5238ccb9f6f49f7ccba9d2b, 2023-01-27T22:17:10.413Z)
OS version: Windows_NT x64 10.0.22623

Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 3700X 8-Core Processor              (16 x 3600)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.95GB (16.44GB free)|
|Process Argv|--crash-reporter-id c0dee863-465c-4d99-9326-0a6c96d09a48|
|Screen Reader|no|
|VM|50%|
</details><details><summary>Extensions (91)</summary>

Extension|Author (truncated)|Version
---|---|---
overtype|ada|0.2.0
teleplot|ale|1.0.8
tsl-problem-matcher|amo|0.6.2
iconify|ant|0.5.1
astro-vscode|ast|0.28.2
ti-basic-autocomplete|bea|1.0.1
procfile|ben|1.1.7
vscode-tailwindcss|bra|0.9.7
rona|Bru|1.0.9
better-toml|bun|0.3.2
js-auto-backticks|cha|0.1.4
path-intellisense|chr|2.8.4
glsl-canvas|cir|0.2.15
codesandbox-projects|Cod|0.2.71
systemd-unit-file|coo|1.0.6
doxdocgen|csc|1.4.0
postcss|css|1.0.9
vscode-eslint|dba|2.4.0
vscode-deno|den|3.17.0
githistory|don|0.6.19
gitlens|eam|2023.3.404
prettier-vscode|esb|9.10.4
vscode-todo-plus|fab|4.19.1
vscode-svelte-snippets|fiv|0.5.0
auto-rename-tag|for|0.1.10
shell-format|fox|7.2.5
codespaces|Git|1.13.10
todo-tree|Gru|0.0.224
headwind|hey|1.7.0
htext|Hun|1.4.1
discord-vscode|icr|5.8.0
reg|ion|1.1.0
vscode-env|Iro|0.1.0
vscode-edit-csv|jan|0.7.3
better-cpp-syntax|jef|1.17.2
vscode-graphviz|joa|0.0.6
svg|joc|1.5.0
text-transformer|joh|0.1.0
json2csv|kha|0.0.1
vscode-gutter-preview|kis|0.30.0
lldb-vscode|lan|0.2.3
easy-timer|Lor|1.0.0
smalise|Loy|0.0.12
Lisp|mat|0.1.12
dotenv|mik|1.0.1
vscode-duplicate|mrm|1.2.1
vscode-docker|ms-|1.24.0
csharp|ms-|1.25.4
dotnet-interactive-vscode|ms-|1.0.4102020
vscode-edge-devtools|ms-|2.1.1
jupyter|ms-|2023.2.1000541047
jupyter-keymap|ms-|1.1.0
jupyter-renderers|ms-|1.0.14
vscode-jupyter-cell-tags|ms-|0.1.6
vscode-jupyter-slideshow|ms-|0.1.5
remote-ssh|ms-|0.99.2023030315
remote-ssh-edit|ms-|0.84.0
remote-wsl|ms-|0.75.3
cmake-tools|ms-|1.13.45
cpptools|ms-|1.14.4
cpptools-extension-pack|ms-|1.3.0
hexeditor|ms-|1.9.11
remote-explorer|ms-|0.3.2023021509
remote-server|ms-|1.1.2023022709
vscode-serial-monitor|ms-|0.8.0
vsliveshare|ms-|1.0.5832
vscode-progressive-increment|nar|1.0.5
material-icon-theme|PKi|4.24.0
svelte-preview|Raf|2.6.1
twop|raf|2.0.1
vscode-thunder-client|ran|2.5.0
vscode-xml|red|0.24.0
nunjucks|ron|0.3.1
rust|rus|0.7.9
glassit|s-n|0.2.6
mdx|sil|0.1.1
shader|sle|1.1.5
default-keys-windows|smc|0.0.9
swdc-vscode|sof|2.6.48
code-spell-checker|str|2.18.0
code-spell-checker-french|str|0.3.0
apklab|Sur|1.6.1
svelte-vscode|sve|107.1.2
ayu|tea|1.0.5
cmake|twx|0.0.17
luna-paint|Tyr|0.16.0
unity-debug|Uni|3.0.2
vscode-lldb|vad|1.8.1
vscode-arduino|vsc|0.5.0
markdown-all-in-one|yzh|3.5.0
material-theme|zhu|3.15.6

(7 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30422396
pythontb:30258533
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscod805:30301674
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30404738
cppdebug:30492333
vsclangdf:30492506
c4g48928:30535728
dsvsc012:30540252
pynewext54:30618038
pylantcb52:30590116
pyindex848:30611229
nodejswelcome1:30587009
pyind779:30611226
vscrpc:30624061
pythonsymbol12:30651887
2i9eh265:30646982
6233i204:30659907
pythonb192cf:30661257
funwalk2cf:30676044
pythonms35:30671666

```

</details>

**Comment by rafalou38** [comment]
I don't know if that's related but I also don't have open with vscode in my context menu even after reinstalling and checking it.
![image](https://user-images.githubusercontent.com/58974586/223773467-5d2d0259-26dd-4e9f-ad45-0b5f372e3afa.png)

**Comment by rafalou38** [comment]
Here it is, I reinstalled it the other day,
**Current version status:**
```
Version: 1.77.0-insider
Commit: b60db78000bfa99d1b290194ed4651c4ceef02cc
Date: 2023-03-10T05:24:23.805Z (6 days ago)
```


Now that a new update is available, the restart popup appears, and it won't update.
![image](https://user-images.githubusercontent.com/58974586/225709136-ef24d4a6-e313-429f-a334-3ffa14eb055a.png)

So that means uninstalling and reinstalling did not fix the issue.

Is there update logs somewhere to check ?

**Comment by joaomoreno** [comment]
Does it reproduce if you try the System Setup?

**Comment by rafalou38** [comment]
By system setup, you mean the latest installer from the website ?
If so, yes I reinstalled like this various times and it does not fix the issue as it doesn't automatically install the next version.

**Comment by joaomoreno** [comment]
No, I mean this setup package: https://code.visualstudio.com/docs/?dv=win64

**Comment by rafalou38** [comment]
I installed with your link, and it works, I now have classic code installed and of course, no issue as I have the latest version. But on the next update available, it will probably fail again as it did before.

I installed like this many times the insiders version and the issue always comes back.

**Comment by joaomoreno** [comment]
@rafalou38 Did the issue occur with the March release?

**Comment by rafalou38** [comment]
**On insiders:**
update to "April 2023 (version 1.78)" is not working
Current version:
- Version: 1.77.0-insider
- Commit: b60db78000bfa99d1b290194ed4651c4ceef02cc
- Date: 2023-03-10T05:24:23.805Z
- Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Code-Insiders/1.77.0-insider Chrome/102.0.5005.196 Electron/19.1.11 Safari/537.36



**On normal VS Code:**
Updated from to 1.76.2 to 1.77 successfully.

**Comment by joaomoreno** [comment]
Did you enable the "Add to Context Menu" option in the setup, when you first installed Insiders?

**Comment by rafalou38** [comment]
Yes, I did and that did not work:
![image](https://user-images.githubusercontent.com/58974586/234976350-6319f5e5-99b9-4d43-893d-aba20d1a6eb4.png)

I first installed VS Code with Windows 10.
Reinstalling does not register the context-menu actions.

**Comment by joaomoreno** [comment]
Could you maybe try this?

1. Uninstall VS Code
2. Reinstall, unchecking that option

And then wait for the next update to see if the same happens.

**Comment by rafalou38** [comment]
I noticed I had vscode insiders installed as User (broken) and classic vscode installed as system (working) so I tried installing insiders as system, the item now appears in the context menu 👍.

I'll come back on the next update to see if it worked.

**Comment by rafalou38** [comment]
It successfully updated from 1.7**8**.0-insider to 1.7**9**.0-insider 🎉 

So yes, that was it, to fix:
- Broken context menu
- Broken Update

\> Install the administrator version.
