### ISSUE TITLE
Cannot automatically remove the warning: `Files stored in install folder may be deleted at update time`

### ISSUE THREAD

**Issue by RedCMD** [microsoft/vscode#176164]
I am using the portal `.zip` vscode install

I have added the extension folder to the workspace for easy access to my extensions
but ever since an update (`1.70.0`??), a warning has popped up saying I shouldn't use the folder
I can click the `[x]` to close it, but everytime I restart vscode, it shows up again
![image](https://user-images.githubusercontent.com/33529441/222951861-16c3d27c-5f4f-4b13-beb9-e03a47ec5b88.png)

**Comment by bpasero** [comment]
The warning indicates that you have the installation folder opened as a workspace. We do not want to provide a way to ignore this issue because it is a potential source of data loss.
