### ISSUE TITLE
Bad PHP syntax highlight when using a SQL string with "["

### ISSUE THREAD

**Issue by nunoperalta** [microsoft/vscode#176194]
Type: <b>Bug</b>

Please see these screenshots:

Minimal:
<img width="461" alt="image" src="https://user-images.githubusercontent.com/487079/222998015-cb67ccae-e547-44ef-8c95-3989d6fc7bcb.png">

A bit more complex:
<img width="788" alt="image" src="https://user-images.githubusercontent.com/487079/222998038-da6ae479-91aa-47ec-ac0e-0f45e5f7909c.png">

This is the code (just split the 3rd and 4th lines into two different screenshots to make it easier to see the syntax highlight issue):

```
		$test = mysqli_iquery('test1 ['.mysqli_ireal_escape_string($_POST['var1']));

		$test = mysqli_iquery('UPDATE test1 '.mysqli_ireal_escape_string($_POST['var1']));

		$test = mysqli_iquery('UPDATE test1 ['.mysqli_ireal_escape_string($_POST['var1']));

		$test = mysqli_iquery('UPDATE test1 SET `question` = REGEXP_REPLACE(`question`, " \\['.mysqli_ireal_escape_string($_POST['var1']).'\\]$", "")');
```

As you see, the PHP code is perfectly valid, but once we add `[` in a string that starts with `UPDATE` (and, I assume, any other SQL keyword), the string concatenation doesn't seem to be recognized by the syntax highlight.

`mysqli_ireal_escape_string($_POST['var1'])` is not appearing with the correct colors.

VS Code version: Code 1.76.0 (92da9481c0904c6adfe372c12da3b7748d74bdcb, 2023-03-01T10:22:44.506Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8400 CPU @ 2.80GHz (6 x 2808)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.94GB (14.15GB free)|
|Process Argv|--disable-extensions|
|Screen Reader|no|
|VM|0%|
</details>Extensions disabled

**Comment by roblourens** [comment]
Please file this upstream at https://github.com/KapitanOczywisty/language-php, thanks
