### ISSUE TITLE
Size grip on the main window

### ISSUE THREAD

**Issue by mika76** [Microsoft/vscode#17611]
- VSCode Version:1.8.1
- OS Version: Windows 10 x64

I think a sizing grip on the main window would be great. I'm not sure where this great usability feature has disappeared lately with apps, but it's so much easier to grip a block then a corner...

**Comment by bpasero** [comment]
This feature request will not be considered in the next [6-12 months roadmap](https://github.com/Microsoft/vscode/wiki/Roadmap) and as such will be closed to keep the number of issues we have to maintain actionable. Thanks for understanding and happy coding!
