### ISSUE TITLE
`CompletionItem` with `additionalTextEdits` makes `Code - Insiders Helper (Renderer)` fall into an infinite loop

### ISSUE THREAD

**Issue by tamuratak** [microsoft/vscode#176154]
Version: 1.77.0-insider (Universal)
Commit: 06ce7933733b1ab05e410e46a6a622dfffb31927
Date: 2023-03-03T05:23:13.637Z
Electron: 19.1.11
Chromium: 102.0.5005.196
Node.js: 16.14.2
V8: 10.2.154.26-electron.0
OS: Darwin arm64 20.6.0
Sandboxed: Yes

ProductName:	macOS
ProductVersion:	11.7.4
BuildVersion:	20G1120

Does this issue occur when all extensions are disabled?: Yes

Steps to Reproduce:

1. Execute the following extension sample: https://github.com/tamuratak/vscode-extension-samples/tree/09c5089567c25d3cd196adb77ff8e8b47de29553/completions-sample

```typescript
import * as vscode from 'vscode';

export function activate(context: vscode.ExtensionContext) {

	const provider = {
			provideCompletionItems(document: vscode.TextDocument, position: vscode.Position, token: vscode.CancellationToken, context: vscode.CompletionContext): vscode.CompletionItem[] {

				const additionalEditsCompletion = new vscode.CompletionItem('\\Z\\\\\\\\\\\\{');
				additionalEditsCompletion.kind = vscode.CompletionItemKind.Issue;
				additionalEditsCompletion.insertText = '';
				const edit = vscode.TextEdit.replace(
					new vscode.Range(
						new vscode.Position(position.line, position.character - 2),
						new vscode.Position(position.line, position.character + 2)
					),
					'\\Z\\\\\\\\\\\\{'
				);
				const edit2 = vscode.TextEdit.replace(
					new vscode.Range(
						new vscode.Position(position.line, position.character - 2 + 20),
						new vscode.Position(position.line, position.character + 2 + 20)
					),
					'\\Z\\\\\\\\\\\\}'
				);
				additionalEditsCompletion.additionalTextEdits = [edit, edit2];
				const item = {
					"label": "\\aaa",
				}
				// return all completion items as array
				return [
					additionalEditsCompletion,
					item
				];
			}
		}
	const dispo = vscode.languages.registerCompletionItemProvider({ language: 'plaintext' }, provider, '\\');

	context.subscriptions.push(dispo);
}
``` 
3. Open a text document.
4. Type `\`
5. Select `\\Z\\\\\\\\\\\\{` and type `Enter`
6. `Code - Insiders Helper (Renderer)` falls into an infinite loop

https://user-images.githubusercontent.com/10665499/222938086-fce9aebd-8317-4a0e-a19e-a785b3841430.mov

**Comment by jrieken** [comment]
I can reproduce. Thanks for reporting this, looking into this asap

**Comment by jrieken** [comment]
To reproduce

* use completion provider from above
* have a text file with `
123456789\ 123456789 123456789 123456789 123456789 123456789 123456789`
* type \ after the existing \ and select the second option
* 🥶 

The issue is computing alternative suggestions (for tab complete). That trips on an invalid state because the chosen (start) index doesn't exist anymore. That's because the model updated in response to applying the additional edits.
