### ISSUE TITLE
Release Notes causes VS Code window to suddenly get much brighter

### ISSUE THREAD

**Issue by Quxxy** [microsoft/vscode#176159]
Type: <b>Bug</b>

Expected: scroll through the February 2023 (1.76) release notes without weird visual glitching.

Actual: when I scroll past certain elements of the release notes, the contents of the VS Code window gets brighter.

Normally, the release notes background is #1E1E1E.  When it gets brighter, it becomes #3D3E3E.  I determined this by using Snip & Sketch to take a screenshot of the two states, opening them in Paint.NET, and inspecting the colour of the background.

In particular, this seems to happen when the following images are visible in the window: the "Profile Badge" example image, the "Configure default log level" example image, and the "Improved extension search relevance" images (I can't tell whether it's both, or only one of them).

As soon as any of these images become visible, the window gets brighter.  As soon as they scroll out of the visible area, it goes back to normal.  Smells like some kind of HDR or colour space issue.

My monitor supports HDR, and Windows is set to use HDR on the desktop.  No other windows get brighter.  The window decorations on the VS Code window do not get brighter.  This does not appear to happen in any of the code files I tested.

Here are some screenshots of the normal and bright states.  Note how in the second screenshot, the "Profile Badge" image has just scrolled into view at the bottom.

- ![VS Code Brightness Bug - 1, Normal](https://user-images.githubusercontent.com/23474483/222945085-4079cb91-2931-4654-9d17-e8f7cc7c34f8.png)
- ![VS Code Brightness Bug - 2, Bright](https://user-images.githubusercontent.com/23474483/222945088-d4b41e23-7b5c-4d47-ac77-0e174170597b.png)

Here is a video of scrolling through the release notes.  Please note that although the video shows *where* the problem occurs, it does not accurately represent what it looks like.  The video starts out at the correct brightness, gets dark where I see over-bright, then is even darker when I see it go back to normal brightness.  So the absolute brightness of the video is misleading, but where the changes happen is accurate.

https://user-images.githubusercontent.com/23474483/222945189-ea2fb9f0-93a7-4d5c-9826-0f7a02906839.mp4

VS Code version: Code 1.76.0 (92da9481c0904c6adfe372c12da3b7748d74bdcb, 2023-03-01T10:22:44.506Z)
OS version: Windows_NT x64 10.0.19045
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 5700X 8-Core Processor              (16 x 3400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.93GB (14.87GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (54)</summary>

Extension|Author (truncated)|Version
---|---|---
language-x86-64-assembly|13x|3.0.0
vscode-sqlite|ale|0.14.1
git-tools|ank|1.0.0
language-mcfunction|arc|0.18.0
spellright|ban|3.0.112
toml|be5|0.6.0
search-crates-io|bel|1.2.1
unique-lines|bib|1.0.0
dart-code|Dar|3.60.1
flutter|Dar|3.60.0
dlang|dla|0.10.0
xml|Dot|2.5.1
gitlens|eam|13.3.1
retroassembler|Eng|1.3.6
godot-tools|gee|1.3.1
item-filter-code|Gle|1.14.4
vscode-ebnf|igo|1.0.3
vscode-ansi|ili|1.1.5
sdlang|Lau|0.1.2
gnuplot|Mar|1.0.11
rainbow-csv|mec|3.5.0
csharp|ms-|1.25.4
isort|ms-|2022.8.0
python|ms-|2023.4.0
vscode-pylance|ms-|2023.3.10
jupyter|ms-|2023.2.1000592019
jupyter-keymap|ms-|1.1.0
jupyter-renderers|ms-|1.0.15
vscode-jupyter-cell-tags|ms-|0.1.6
vscode-jupyter-slideshow|ms-|0.1.5
remote-ssh|ms-|0.98.0
remote-ssh-edit|ms-|0.84.0
cpptools|ms-|1.14.4
hexeditor|ms-|1.9.11
remote-explorer|ms-|0.2.0
sublime-keybindings|ms-|4.0.10
vsliveshare|ms-|1.0.5832
prettier-vscode-with-tabs|pas|1.1.0
prolog|reb|0.0.4
llvm|RRe|0.1.1
rust-analyzer|rus|0.4.1424
crates|ser|0.5.10
shader|sle|1.1.5
vscode-autohotkey|sle|0.2.2
datapack-language-server|SPG|3.4.7
vscode-nushell-lang|The|1.0.0
graphviz-interactive-preview|tin|0.3.5
unity-debug|Uni|3.0.2
errorlens|use|3.7.0
expand-selection-to-scope|vit|0.2.0
vscode-icons|vsc|12.2.0
wavetrace|wav|1.1.2
change-case|wma|1.0.0
markdown-all-in-one|yzh|3.5.0

</details>

**Comment by Quxxy** [comment]
Some additional hardware details:

My GPU is an nVidia GeForce GTX 1070, running driver 516.94.  My monitor is an LG G-Sync compatible display that supports HDR, running at 143.923 Hz.

**Comment by Quxxy** [comment]
Updated the graphics driver to 531.18, and I no longer observe the above behaviour.  The release notes look fine now.

I'll leave this issue open in case you want to try and find the underlying issue.  Otherwise, please feel free to close.

**Comment by deepak1556** [comment]
Closing per https://github.com/microsoft/vscode/issues/176159#issuecomment-1455006833
