### ISSUE TITLE
why dose the play button disappear and i could not make it appear? (edit)

### ISSUE THREAD

**Issue by RXL9** [microsoft/vscode#176112]
Does this issue occur when all extensions are disabled?: Yes/No yes

- VS Code Version: 1.76.0
- OS Version: windows 10

Steps to Reproduce:   (didn't understand this sorry)

1. 
2.

![‏‏لقطة الشاشة (2)](https://user-images.githubusercontent.com/126627762/222008939-944610ec-e228-4984-9382-77c6d7c2aa7b.png)

it happind after i pressed run and debug 

i tried to solve the problem and i couldn't i tried everything you said on the first post and more i couldn't make it appear please help
sorry if my english is bad

**Comment by PerssonBrown** [comment]
It seems that you even did not save your code. You are trying to run a blank file using python.
Please save your file first. (Press `ctrl` + `s`)

**Comment by RXL9** [comment]
> It seems that you even did not save your code. You are trying to run a blank file using python. Please save your file first. (Press `ctrl` + `s`)

even if i saved the file the play button don't appear again

**Comment by roblourens** [comment]
If you are using the Code Runner extension please file the issue on that repo. Otherwise you need to be more specific. Maybe this helps https://code.visualstudio.com/docs/python/python-tutorial
