### ISSUE TITLE
Search TypeScript symbols in workspace takes 7-10 seconds for 2000 lines-of-code project without many dependencies in Windows.

### ISSUE THREAD

**Issue by 2bam** [microsoft/vscode#176172]
Does this issue occur when all extensions are disabled?: Yes/No
Yes

- VS Code Version: 
Version: 1.76.0 (user setup)
Commit: 92da9481c0904c6adfe372c12da3b7748d74bdcb
Date: 2023-03-01T10:22:44.506Z
Electron: 19.1.11
Chromium: 102.0.5005.196
Node.js: 16.14.2
V8: 10.2.154.26-electron.0
OS: Windows_NT x64 10.0.19044
Sandboxed: No

- OS Version: 
OS Name:                   Microsoft Windows 10 Home Single Language
OS Version:                10.0.19044 N/A Build 19044
OS Manufacturer:           Microsoft Corporation

Steps to Reproduce:

1.  _Ctrl+T_ or through Menu _Go -> Go To Symbol In Workspace..._
2.  Write something

It takes around 7-10 seconds to respond on a 12GB ram / i7 (Intel64 Family 6 Model 94 Stepping 3 GenuineIntel ~2592 Mhz).
In my experience it seems to take way longer in Windows than Linux.

The internal list seems to be populated from here (as a lot of entries appear):
`C:\Users\xxx\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\`

It would be great to be able to exclude those paths as requested in this locked issue https://github.com/microsoft/vscode/issues/46718

**Comment by 2bam** [comment]
Because the definition of _not many_ may vary, here's the list
(webpack, typescript, prettier, lodash and a RNG lib)

```
  "devDependencies": {
    "@webpack-cli/generators": "^3.0.1",
    "css-loader": "^6.7.3",
    "html-webpack-plugin": "^5.5.0",
    "prettier": "^2.8.4",
    "style-loader": "^3.3.1",
    "ts-loader": "^9.4.2",
    "typescript": "^4.9.5",
    "webpack": "^5.75.0",
    "webpack-cli": "^5.0.1",
    "webpack-dev-server": "^4.11.1"
  },
  "dependencies": {
    "@types/lodash": "^4.14.191",
    "@types/mersenne-twister": "^1.1.2",
    "lodash": "^4.17.21",
    "mersenne-twister": "^1.1.0"
  },
```

**Comment by mjbvz** [comment]
Please try collecting the TS Server log:

1. Set `"typescript.tsserver.log": "verbose",`
1. Restart VS Code and reproduce the problem
1. In VS Code, run the `TypeScript: Open TS Server log` command
1. This should open a large log file called `tsserver.log` 

This should have performance information about what is taking so long

 > **⚠️Warning:** The TypeScript log may include information from your workspace, including file paths and source code. If you have any concerns about posting this publicly on Github, just let me know and we can arrange something else. On our side, we only use these logs to investigate issues like this

**Comment by 2bam** [comment]
Will do, but I currently have no time at all to devote to this, sorry. Please don't close it if I take until next week.

**Comment by mjbvz** [comment]
@2bam Did you have a chance to collect the logs?

**Comment by 2bam** [comment]
Sorry for the delay. I just tried it and from request to response in the logs I read a response under 80-200ms, but still the UI takes ~3 seconds to show the results.
It got better though, maybe restarting did clean up some state? I'll keep the verbose logging on in case it gets worse again after I have vscode open for some hours/days.

* Is there a way to log UI related things? Maybe from Electron itself? Let me know if I can help with that.
* If I can't find anything in a couple of week we can close the issue.

Log snippet and gif:
```
Info 338  [23:59:57.113] request:
    {
      "seq": 65,
      "type": "request",
      "command": "navto",
      "arguments": {
        "searchValue": "Evt_Impact",
        "maxResultCount": 256
      }
    }
Perf 339  [23:59:57.179] 65::navto: elapsed time (in milliseconds) 66.1210
Info 340  [23:59:57.179] response:
```
![DV5cauYHLL](https://user-images.githubusercontent.com/8461554/228677716-1bb5901f-5ed2-41bb-8517-3f41cb001e1e.gif)

**Comment by mjbvz** [comment]
Do you have other extensions installed which could be slowing this down?

Try testing in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)

**Comment by 2bam** [comment]
I disabled all extensions as the guide in your link
Restarted vscode and the TS server.
Then enabled them one by one. Couldn't repro.
Restarted vscode and the TS server.
**Can't reproduce it anymore.**

So I think it may be solved!

Did it on my current version:
> Version: 1.77.3 (user setup)
> Commit: 704ed70d4fd1c6bd6342c436f1ede30d1cff4710
> Date: 2023-04-12T09:16:02.548Z
> Electron: 19.1.11
> Chromium: 102.0.5005.196
> Node.js: 16.14.2
> V8: 10.2.154.26-electron.0
> OS: Windows_NT x64 10.0.19044
> Sandboxed: No
 

Extensions (all up to date):
> vsciot-vscode.vscode-arduino
> ms-vscode.cpptools
> ms-vscode.cpptools-extension-pack
> ms-vscode.cpptools-themes
> twxs.cmake
> ms-vscode.cmake-tools
> streetsidesoftware.code-spell-checker
> dbaeumer.vscode-eslint
> esbenp.prettier-vscode
> rvest.vs-code-prettier-eslint
> ms-vscode.vscode-serial-monitor
> ms-vscode.vs-keybindings
> ms-vscode-remote.remote-wsl
