### ISSUE TITLE
Forward slash character in profile name causes unexpected behaviour

### ISSUE THREAD

**Issue by dylmye** [microsoft/vscode#176103]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.76.0
- OS Version: macOS 11.6.2

Version: 1.76.0
Commit: 92da9481c0904c6adfe372c12da3b7748d74bdcb
Date: 2023-03-01T10:23:45.993Z
Electron: 19.1.11
Chromium: 102.0.5005.196
Node.js: 16.14.2
V8: 10.2.154.26-electron.0
OS: Darwin x64 20.6.0
Sandboxed: No

**Summary**

When creating a profile with a name such as "Typescript / Javascript", the following happens:

* When exporting as a Gist, no result dialog shows ("there was trouble" / "created profile successfully") and a validation error is outputted in the logs
* When exporting to a local file, the text after the last forward slash is set as the filename. With the above example, it'd be " Javascript.json"

**To reproduce:**

0. Select a profile: Settings cog -> "Profile ([...])"
0. Export the profile: Select "Export Profile..." -> "Export"
0. In the "name the profile" step, enter a name with a forward slash in like so: "Typescript / Javascript"
0. Select either method for exporting: gist or local

**Expected results:**

* If you select local: a system save prompt with the name you entered pre-set in the filename field
* If you select gist: A success dialog with a link to the vscode.dev website prefilled with your config

**Actual results:**

* If you select local: only the text after the last forward slash is in the filename field
* If you select gist: No dialog shows. The following error is in the "output" window, under "Window":
```
[error] Validation Failed: {"resource":"Gist","code":"invalid","field":"files"}: HttpError: Validation Failed: {"resource":"Gist","code":"invalid","field":"files"}
    at /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/configuration-editing/dist/configurationEditingMain.js:2:25686
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at Object.saveProfile (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/configuration-editing/dist/configurationEditingMain.js:2:408941)
```

I can only test this on a macOS device, I haven't tried this on a Windows or other Linux device and I feel like (with the area in mind - filesystems etc) these issues could manifest differently or not even be an issue there.

I'm assuming validation on the inputbox for the name will be required because filesystems (and Gist? not sure) don't typically support forward slashes in file names.

Thanks and if you're reading this, have a great weekend :)

**Comment by sandy081** [comment]
Gists do no accept `/` in the name.

Replaced `\` with `-`.
