### ISSUE TITLE
Change the name suggestion to the bottom of the list

### ISSUE THREAD

**Issue by easyfrog** [microsoft/vscode#176229]
In all kinds of the suggestion types, The `name suggestion` will be the **lowest priority**.
But it always on the top of the suggestion list.

It's there a way the change them to bottom?

<img width="598" alt="image" src="https://user-images.githubusercontent.com/10724325/223096468-b1ab4229-363e-4cf7-9431-9d5ce8c85c99.png">

**Comment by jrieken** [comment]
This issue lacks

* mentioning of the language and extension providing completions
* copy-paste friendly source code sample

**Comment by easyfrog** [comment]
> 

* It is a old project write by javascript and AMD module

and I know AMD is not support well by vscode

**Comment by jrieken** [comment]
@easyfrog your reply doesn't help me in reproducing this issue
