### ISSUE TITLE
Notify screen reader users that a VS Code update is available

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#176242]
Sighted users can notice there's a badge on the settings gear which indicates an update of VS Code is available. Should we notify via aria-alert or aria-status when this becomes available? 

@jooyoungseo and @jvesouza would appreciate your thoughts here

**Comment by aitor-gomila** [comment]
I want to work on this. How would it be notified?

**Comment by meganrogge** [comment]
Thanks for your interest @aitor-gomila, I want to discuss this before we consider the approach here

**Comment by jvesouza** [comment]
> Sighted users can notice there's a badge on the settings gear which indicates an update of VS Code is available. Should we notify via aria-alert or aria-status when this becomes available?
> 
> @jooyoungseo and @jvesouza would appreciate your thoughts here

I usually update vscode through the fedora package manager, but it's always useful to know that a new version is available. Perhaps the notification mechanism already existing in vscode could be used when VSCode is started.

**Comment by meganrogge** [comment]
Yes good idea, in particular when we have improved notification accessibility https://github.com/microsoft/vscode/issues/175140

**Comment by isidorn** [comment]
If we introduce a notification we should do it only when screen reader is attached. Since otherwise, it would be too noisy for non screen reader users.

**Comment by meganrogge** [comment]
100% agree @isidorn, the badge is sufficient for sighted users

**Comment by meganrogge** [comment]
We haven't received any more feedback on this, so closing.
