### ISSUE TITLE
notebook cell complete audio cue didn't play if kernel was selected in same execution action

### ISSUE THREAD

**Issue by amunger** [microsoft/vscode#176284]
1. enable audio cues for notebook cell completion
2. open a notebook without a kernel selected and run a cell
3. select the kernel so that the cell runs successfully
🐛 cell completes, but audio cue doesn't play

**Comment by meganrogge** [comment]
to be clear, @amunger, you were using `run by line` here to do this, correct? As you can see here, there's no run button when i haven't selected a kernel. 
![Screenshot 2023-04-04 at 1 42 46 PM](https://user-images.githubusercontent.com/29464607/229915878-ca984a73-b16e-463b-9dcb-ea9c57932559.png)

**Comment by amunger** [comment]
shift+enter should also trigger the cell to run. Do you have any kernels available in that screenshot? I can still see a run button without a kernel selected.

**Comment by meganrogge** [comment]
shift + enter adds a new line to the cell and no I don't have any kernels available by design, as it seems it gets auto selected. 

what were your more specific repro steps for the above? I've been disabling the python extension to simulate no kernel selected then pressing `run by line`

**Comment by meganrogge** [comment]
I was hoping one of these would allow me to reset it such that there are no kernels, but no luck
![Screenshot 2023-04-04 at 1 55 00 PM](https://user-images.githubusercontent.com/29464607/229918662-4966778e-4867-4b43-924f-2cd5ff285b6b.png)

**Comment by meganrogge** [comment]
oh figured it out- just creating a new notebook

**Comment by meganrogge** [comment]
nice, here's the issue

![Screenshot 2023-04-04 at 1 58 30 PM](https://user-images.githubusercontent.com/29464607/229919497-73b2fddd-8770-480b-b01c-db2fbbd6e28f.png)

**Comment by meganrogge** [comment]
looks like there's a chrome / maybe chromium flag that allows you to bypass this policy:

`--autoplay-policy=no-user-gesture-required `
