### ISSUE TITLE
Make "Tip" text available via extension API.

### ISSUE THREAD

**Issue by Austinauth** [microsoft/vscode#176244]
Certain extension Getting Started flows are able to utilize "tip text", a more subtle variation of the standard `description` field currently available. Ideally "tip text" formatting would be available to all via the extension API.

See discussion below for more context:

![image](https://user-images.githubusercontent.com/6994218/223156807-43fc96dc-5e99-4fb0-9e83-b10147a8c1ed.png)

<hr>

cc: @daviddossett (I'm not able to assign in this repo).

**Comment by bhavyaus** [comment]
This should already be available to use if your command has an existing key binding.

**Comment by bhavyaus** [comment]
There is no API. We handle it here: https://github.com/microsoft/vscode/blob/7b39d0e24ae473beb9d1d28d8372e960681ddda9/src/vs/workbench/contrib/welcomeGettingStarted/browser/gettingStarted.ts#L1310

If you've added a command in the walkthrough description,  and that command has a key binding, we pull it out and show it as `Tip...`

**Comment by daviddossett** [comment]
Perfect, thanks! I'll close this one then assuming that offers what he needs 👍
