### ISSUE TITLE
Read only/read write indicator in status bar

### ISSUE THREAD

**Issue by BillDenton** [Microsoft/vscode#17621]
- VSCode Version: 1.8.1
- OS Version: Window 7 Professional

Request to add a RW/RO indicator to right side of the status bar. Clicking on the indicator could offer the option to change the status of the file disk. If accepted would read/write status of file on disk, if declined would just allow the file to be edited. Similar to SlickEdit.
Similar is already implemented in extension https://marketplace.visualstudio.com/items?itemName=alefragnani.read-only-indicator, but appears on the left and isn't built in as standard.

**Comment by egamma** [comment]
CC @bpasero

**Comment by alefragnani** [comment]
Hi @BillDenton ,

I just added both enhancements in the extension repo, as you suggested. 

Stay tuned

**Comment by BillDenton** [comment]
Thanks. I think this issue can be closed as requested functionality is requested in the extension ( [https://github.com/alefragnani/vscode-read-only-indicator/issues/4](url) and [https://github.com/alefragnani/vscode-read-only-indicator/issues/3](url)) and #17670.

**Comment by alefragnani** [comment]
@BillDenton the _location_ enhancement has just been released.

**Comment by BillDenton** [comment]
Closing this issue as feature is implemented as an extension.
What is criteria for deciding what should be an extension vs built in?
