### ISSUE TITLE
parameterHints text blurs on scroll when editor zoom level is non-default

### ISSUE THREAD

**Issue by Invincibear** [Microsoft/vscode#17622]
- VSCode Version: Code 1.8.1 (ee428b0eead68bf0fb99ab5fdc4439be227b6281, 2016-12-19T14:49:23.350Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

|Extension|Author|Version|
|---|---|---|
|PowerShell|ms-vscode|0.7.2|

---

Steps to Reproduce:

1. Zoom out from default/reset zoom level (Ctrl + -)
2. In a .psm1 PowerShell file, type a command, begin typing an argument with a hyphen (eg: Write-host -)
3. The suggestion box will show, scroll down any amount and observe the text is no longer sharp but is now blurry
![vscode suggestion box normal](https://cloud.githubusercontent.com/assets/6895337/21362769/9aa0cd18-c69e-11e6-9114-703f7ad0c798.png)
![vscode suggestion box blurry](https://cloud.githubusercontent.com/assets/6895337/21362768/9a996474-c69e-11e6-83e9-7f7191855a51.png)

**Comment by joaomoreno** [comment]
#5154
