### ISSUE TITLE
"Restart Window" option for extension updates does not restart all  instances of VS Code

### ISSUE THREAD

**Issue by viertaxa** [Microsoft/vscode#17624]
- VSCode Version: 1.8.1
- OS Version: Windows 10 Enterprise

Steps to Reproduce:

1. Update Extension
2. Click "Restart" button
3. Only the active window of VS Code restarts, leaving other windows loaded with old plugin versions

**Comment by alefragnani** [comment]
I think this is a duplicate of https://github.com/Microsoft/vscode/issues/3268
