### ISSUE TITLE
Git Pull fails in VS Code but works in GH Desktop

### ISSUE THREAD

**Issue by digitarald** [microsoft/vscode#176274]
Type: <b>Bug</b>

Manually pulling in VS Code in my local vscode checkout failed twice with:

```
[info] error: cannot lock ref 'refs/remotes/origin/main': is at c6bec3b789d1fc55f7f428c6caf8da29eab8fa0f but expected d912e6c92514b3dd524fe6ff1332a06c5f1d5534
```

Doing a pull in GitHub Desktop worked.

For reference, GitHub Desktop used

```bash
git -c credential.helper= -c rebase.backend=merge pull --ff --recurse-submodules --progress origin
```

VS Code failed with
```bash
> git fetch --all --prune
error: cannot lock ref 'refs/remotes/origin/main': is at c6bec3b789d1fc55f7f428c6caf8da29eab8fa0f but expected d912e6c92514b3dd524fe6ff1332a06c5f1d5534
From github.com:microsoft/vscode
```

VS Code version: Code - Insiders 1.77.0-insider (06ce7933733b1ab05e410e46a6a622dfffb31927, 2023-03-03T05:23:13.637Z)
OS version: Darwin x64 22.3.0
Modes:
Sandboxed: Yes

**Comment by lszomoru** [comment]
@digitarald, is there a repo that I could use to reproduce this?

**Comment by digitarald** [comment]
@lszomoru sorry, have not seen it since. Not sure how my local repo got into this state. Closing for now.
