### ISSUE TITLE
Scrollbar jump in font increase

### ISSUE THREAD

**Issue by rajinder-yadav** [Microsoft/vscode#17620]
- VSCode Version: Code 1.8.1 (ee428b0eead68bf0fb99ab5fdc4439be227b6281, 2016-12-19T14:41:20.664Z)
- OS Version: Linux x64 4.4.0-53-generic
- Extensions:

|Extension|Author|Version|
|---|---|---|
|vscode-markdownlint|DavidAnson|0.6.0|
|EditorConfig|EditorConfig|0.3.4|
|jslint|ajhyndman|1.2.1|
|jshint|dbaeumer|0.10.15|
|vscode-eslint|dbaeumer|1.2.2|
|tslint|eg2|0.7.1|
|cpptools|ms-vscode|0.9.3|
|Spell|seanmcbreen|0.9.1|
|vim|vscodevim|0.4.9|

---

Steps to Reproduce:

1. Open preview on a markdown file
2. Press CTRL + to increase font size

Notice the scrollbar has moved considerably from where it was.
![jump](https://cloud.githubusercontent.com/assets/439226/21362437/5b79e580-c6b6-11e6-8a25-299a2a8ac32a.png)

**Comment by rajinder-yadav** [comment]
Also please add the ability to only increase the font of preview or edit window independently.

1. If a edit window has focus, pressing 'ctrl +' should increase the fonts for all **edit** windows.
2. If a preview windows has focus, then only increase it's font size on key press 'ctrl +'

**Comment by egamma** [comment]
Duplicates #5745
