### ISSUE TITLE
Can't run or debug Kotlin application

### ISSUE THREAD

**Issue by xetra11** [microsoft/vscode#176228]
When I click the Run/Debug and select Kotlin or Java as Debugger - nothing happens. No error message etc.

I also installed Spring Boot Extension. Same here. Nothing happens

Version: 1.76.0
Commit: 92da9481c0904c6adfe372c12da3b7748d74bdcb
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36
Embedder: codespaces

**Comment by roblourens** [comment]
This sounds like https://github.com/microsoft/vscode/issues/176006
