### ISSUE TITLE
consider default keybindings for go to next / previous cell input

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#176290]
@jooyoungseo suggested `ctrl+pageUp/pageDown` would be good for this

**Comment by jooyoungseo** [comment]
FYI, I have customized `keybindings.json` like below:

``` json
[
  // Custom keybindings for Jupyter Notebook
  {
    "key": "ctrl+pagedown",
    "command": "notebook.focusNextEditor",
    "when": "notebookEditorFocused"
  },
  {
    "key": "ctrl+pageup",
    "command": "notebook.focusPreviousEditor",
    "when": "notebookEditorFocused"
  }
]
```

**Comment by meganrogge** [comment]
@amunger feel free to close if we already support this now.

**Comment by amunger** [comment]
We do not have a default keybinding that works along with the screen reader being enabled, though ctrl+pagedown/pageup are currently bound to next/previous editor, so I don't think we can use that one without breaking current workflows.

**Comment by meganrogge** [comment]
Maybe ctrl+alt+pagedown/pageup?
