### ISSUE TITLE
Extensions not installing in vs code

### ISSUE THREAD

**Issue by melsonic** [microsoft/vscode#176268]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.76.0
- OS Version: Linux x64 5.19.0-35-generic

Steps to Reproduce:

1. Try to install any vs code extension

<br>

![image](https://user-images.githubusercontent.com/88551650/223178833-57f19051-e132-4e9e-81a3-6adb15b54829.png)

**Comment by sandy081** [comment]
Can you please provide following log while you reproduce it?

- F1 > Open View... > Shared

**Comment by melsonic** [comment]
> 
Hey thanks for your concern but it started working again when I tried it next morning. Could this be because of slow internet connection that it shows the above error?

**Comment by sandy081** [comment]
Yeah may or may not be. When you see this again comment in this issue with requested log. Closing this until then.

**Comment by melsonic** [comment]
> 

sure @sandy081

**Comment by melsonic** [comment]
```

[error] RequestService#request (browser) - error https://marketplace.visualstudio.com/_apis/public/gallery/extensionquery {"name":"Canceled"}
2023-03-13 17:11:43.198 [error] Error: net::ERR_INVALID_ARGUMENT
    at SimpleURLLoaderWrapper.<anonymous> (node:electron/js2c/browser_init:105:7047)
    at SimpleURLLoaderWrapper.emit (node:events:526:28)

```

I guess this happends when i set `http.proxyAuthorization` to `true` or `false`. When I comment that like it works well. But when i commented that like I was not able to sign in using my github account.
