### ISSUE TITLE
Extension host terminated

### ISSUE THREAD

**Issue by Elsen1983** [microsoft/vscode#176223]
Type: <b>Bug</b>

Extension host terminated unexpectedly n times within last 5 minutes.

VS Code version: Code 1.76.0 (92da9481c0904c6adfe372c12da3b7748d74bdcb, 2023-03-01T10:22:44.506Z)
OS version: Windows_NT x64 10.0.19045
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10700K CPU @ 3.80GHz (16 x 3792)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.92GB (19.17GB free)|
|Process Argv|E:\\Work\\Verifact\\Projects\\BitBucket\\FIS\\fis-uk-portal --crash-reporter-id de80968e-816f-465c-905f-bbc1bdf98c5c|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (66)</summary>

Extension|Author (truncated)|Version
---|---|---
rainbow-brackets|2gu|0.0.6
better-comments|aar|3.0.2
vscode-laravel-goto|abs|4.7.0
codesnap|adp|1.3.4
project-manager|ale|12.7.0
cucumberautocomplete|ale|2.15.2
vscode-phpstorm-formatter|ani|0.0.6
atlascode|atl|3.0.2
lit-html|bie|1.11.1
blackbox|Bla|0.10.34
phpserver|bra|3.0.2
turbo-console-log|Cha|2.7.1
vscode-better-align|cho|1.4.1
npm-intellisense|chr|1.4.4
regex|chr|0.4.0
laravel-blade|cjh|1.1.2
laravel-goto-view|cod|1.3.8
vscode-svgviewer|css|2.0.0
vscode-mysql-client2|cwe|6.2.4
EditorConfig|Edi|0.16.4
vscode-npm-script|eg2|0.3.29
vsc-material-theme|Equ|33.6.0
vsc-material-theme-icons|equ|2.6.1
prettier-vscode|esb|9.10.4
vscode-firefox-debug|fir|2.9.8
auto-close-tag|for|0.5.14
auto-rename-tag|for|0.1.10
rest-client|hum|0.25.1
composer|ika|0.8.0
vscode-peacock|joh|4.2.2
vscode-phpfmt|kok|1.0.31
blockman|leo|1.7.1
php-constructor|Meh|0.1.2
php-namespace-resolver|Meh|1.1.9
vscode-edge-devtools|ms-|2.1.1
live-server|ms-|0.4.6
color-highlight|nau|2.5.0
php-docblocker|nei|2.7.0
vscode-vue-custom-editor|nik|0.3.0
vetur|oct|0.37.3
indent-rainbow|ode|8.3.1
laravel-blade|one|1.32.0
vscode-php-getters-setters|php|1.2.3
material-icon-theme|PKi|4.24.0
vscode-css-peek|pra|4.2.0
quicktype|qui|12.0.46
vscode-yaml|red|1.11.0
live-sass|rit|3.0.0
LiveServer|rit|5.7.9
code-settings-sync|Sha|3.4.3
vscode-blade-formatter|shu|0.20.12
vscode-scss-formatter|sib|2.4.5
html5-boilerplate|sid|1.1.1
sonarlint-vscode|Son|3.15.1
es6-mocha-snippets|spo|0.2.2
laravel-goto-controller|ste|0.0.15
code-spell-checker|str|2.19.0
sass-indented|syl|1.8.25
add-only|ub1|1.2.1
vscode-icons|vsc|12.2.0
volar|Vue|1.2.0
vscode-todo-highlight|way|1.0.5
JavaScriptSnippets|xab|1.8.0
php-debug|xde|1.32.0
html-css-class-completion|Zig|1.20.0
php-intellisense|zob|1.1.2

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscoreces:30445986
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
pynewext54:30669237
azure-dev_surveyone:30548225
pyindex848:30662994
nodejswelcome1:30587005
3biah626:30602489
pyind779:30671433
89544117:30613380
pythonsymbol12:30671437
vscodeenable:30660116
pythonb192cf:30669361
funwalk2:30676043

```

</details>

**Comment by aitor-gomila** [comment]
Does this happen with all extensions disabled & fresh VSCode profile?
If not, you need to disable/enable them one by one to see which extension is causing the issue.

**Comment by bpasero** [comment]
Can you please follow the steps in https://github.com/Microsoft/vscode/wiki/Native-Crash-Issues to get at more details around the crash and attach the result here? Thanks!

**Comment by isidorn** [comment]
No Copilot installed. Assigning to @deepak1556 
@Elsen1983 can you please answer @bpasero question from above?

**Comment by Elsen1983** [comment]
The issue never happened again after that day I reported the problem. I did not disabled any plugin or update any extension. But on that day it was anoying. Next day (and since that day) the issue never happened again.

**Comment by isidorn** [comment]
Thank you. For now I am closing this and if you see it again do let us know with steps and we can reopen it.
