### ISSUE TITLE
Auto-close brackets before commas

### ISSUE THREAD

**Issue by mrmlnc** [Microsoft/vscode#17626]
- VSCode Version: Code 1.8.1 (ee428b0eead68bf0fb99ab5fdc4439be227b6281, 2016-12-19T14:49:23.350Z) + 1.9.0 latest Insiders build
- OS Version: Windows_NT ia32 10.0.14393

### Disclaimer

I tried to find similar issues, but couldn't. I'm sorry if this issue already exists.

### Steps to Reproduce:

1. Create TS document
2. Create multiple cursors after `=` before semi
3. Press <kbd>[</kbd>

### Expected behavoiur:

All brackets must be closed.

### Actual behaviour:

Only the last pair of brackets will be closed.

```ts
private makeSymbols(variables: IVariable[]=, mixins: IMixin[]=, imports: IImport[]=): ISymbols {
	return {
		variables,
		mixins,
		imports
	};
}
```

![2016-12-20_22-23-34](https://cloud.githubusercontent.com/assets/7034281/21364701/fa435b0a-c702-11e6-907c-6f286fc2b238.gif)

**Comment by alexandrudima** [comment]
This has been fixed in the meantime. In the multicursor case, all cursors now do the same thing. In this case, all the cursors now **do not** auto-close the bracket.
