### ISSUE TITLE
Prefer SVG renderers for image output to improve screen reader fidelity

### ISSUE THREAD

**Issue by amunger** [microsoft/vscode#176293]
SVG images can provide richer features for screen readers over png, so we should consider how to prioritize that renderer when it is available.

cc @jooyoungseo

**Comment by amunger** [comment]
with screen reader accessibility mode, images should still be shown when available, e.g.

```
import matplotlib.pyplot as plt
import numpy as np

x = np.linspace(0, 10, 100)
y = np.sin(x)
plt.plot(x, y)
```

**Comment by jooyoungseo** [comment]
@amunger Does it work for a normal Python repl or only in Jupyter Notebook? Doesn't seem to work in Python repl.

**Comment by amunger** [comment]
@jooyoungseo - just notebooks. The REPL is contributed by the python extension, and it looks like that behavior doesn't depend on the accessibility mode. Running `plt.plot([1, 2, 3, 4])` will always print a text description of the plot, however `plt.show()` seems to launch a plot viewer application

**Comment by amunger** [comment]
> The current implementation is still recognized as <img> instead of SVG object. Do you have any plans for users to choose graphic device? As we discussed before, SVG has more accessibility capabilities.

It's up to the kernel to provide the different output formats, and if SVG is included, it will be prioritized over other image types.
There is also a "More Actions..." in front of the output that contains "change presentation. That lets the user select from the available mime types.

> Is it possible to provide any default alt text for this image element? Currently, it is read as a random data

Thanks for the feedback here, yes, we will try to improve this in https://github.com/microsoft/vscode/issues/180970.
