### ISSUE TITLE
JSON formatter removes newline at end of file

### ISSUE THREAD

**Issue by Chlumsky-Ceros** [microsoft/vscode#176246]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.76.0
- OS Version: Windows 10

Steps to Reproduce:

1. Open a JSON file
2. Right click the editor window and press "Format Document"
3. There is no newline at the end of the file

All text files are supposed to end with a newline character.

**Comment by aeschli** [comment]
This is controlled by the setting `files.insertFinalNewline`. Set it to `true` if you want text files to end with a newline character.

**Comment by Chlumsky-Ceros** [comment]
No, that's completely different. I don't want any changes to happen at the time of saving the file. The formatter actually **removes** the newline if it was previously present. Reopen.

**Comment by aeschli** [comment]
The setting is not only used on save, but also observed by formatters.
If you want the JSON formatter to not remove the new line, enable this setting.

**Comment by Chlumsky-Ceros** [comment]
Ok, it's nice that the formatter observes `files.insertFinalNewline` but using that option removes my ability to ever generate a file without a final newline if I need to do so.

Enabling `json.format.keepLines` breaks the formatter for me - it literally doesn't do anything then.

In any case, a text file without a final newline is malformed and I don't believe that in the default configuration, the JSON formatter should output a malformed document.

**Comment by Chlumsky-Ceros** [comment]
Then, the `json.format.keepLines` setting is irrelevant to this. A JSON being valid without a final newline is also irrelevant, I am not arguing about that (and it's because JSON ignores all whitespace). What I am saying is that **all text files** are supposed to have a final newline, it's not just a guideline and I don't understand how you can not know that, see for example https://stackoverflow.com/a/729795.

None of the settings you suggested solved the issue, as I explained. Even if we pretended that whether or not there should be newline at the end is a guideline (it's not), the formatter doesn't have to add it, but it **definitely** shouldn't remove it, which it does. So why are you so insistent on not fixing this bug? It would probably be a one-line fix.

How about this: instead of the formatter deciding whether to add it based on the `files.insertFinalNewline` setting, it would instead use the inverse of `files.trimFinalNewlines`, I think that would be a nice compromise.
