### ISSUE TITLE
[Bug]: Cannot select by drag using `--enable-wayland-ime` wayland natively

### ISSUE THREAD

**Issue by littlewu2508** [microsoft/vscode#176235]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.76.0
- OS Version: Debian GNU/Linux bookworm, KDE Plasma 5.27.2

Steps to Reproduce:

1. running with `--disable-extensions --enable-features=UseOzonePlatform --ozone-platform=wayland --enable-wayland-ime`, I cannot select text in editor by dragging my mouse. Double click to select word or using shift key to select is OK.
2. Open a text file and drag to select

 I cannot select text in editor by dragging my mouse. Double click to select word or using shift key to select is OK.

Running with `--disable-extensions --enable-features=UseOzonePlatform --ozone-platform=wayland`, or running under X11(Xwayland), there's no issue.

I also tried to run `chromium --enable-features=UseOzonePlatform --ozone-platform=wayland --enable-wayland-ime` and other electron apps, there's no issue for them. So I guess this has something to do with VSCode itself.

**Comment by Yesterday17** [comment]
It seems that selection is not available only in the editor. It does not affect the search box on my machine.

**Comment by czg-sci-42ver** [comment]
> It seems that selection is not available only in the editor. It does not affect the search box on my machine.
> 
> And vscode-web works fine without any issue.

I was the same situation, and I used vscode-insiders and disabled all extensions , problem sticks.

here is debug console log in `Developer Tools` in code-insider
```bash
$ code-insiders --version
1.77.0-insider
fa13bf16fd237afef07f4df0648da026f43e3963
x64
```
log
```java
 INFO Electron sandbox mode is enabled!
workbench.desktop.main.js:sourcemap:620  WARN Via 'product.json#extensionEnabledApiProposals' extension 'ms-vscode.vscode-selfhost-test-provider' wants API proposal 'testContinuousRun' but that proposal DOES NOT EXIST. Likely, the proposal has been finalized (check 'vscode.d.ts') or was abandoned.
workbench.desktop.main.js:sourcemap:620  WARN Via 'product.json#extensionEnabledApiProposals' extension 'ms-vscode.remote-repositories' wants API proposal 'contribEditorGutterMenu' but that proposal DOES NOT EXIST. Likely, the proposal has been finalized (check 'vscode.d.ts') or was abandoned.
workbench.desktop.main.js:sourcemap:620  WARN Via 'product.json#extensionEnabledApiProposals' extension 'github.vscode-pull-request-github' wants API proposal 'contribEditorGutterMenu' but that proposal DOES NOT EXIST. Likely, the proposal has been finalized (check 'vscode.d.ts') or was abandoned.
workbench.desktop.main.js:sourcemap:620  WARN Via 'product.json#extensionEnabledApiProposals' extension 'ms-toolsai.jupyter' wants API proposal 'notebookControllerKind' but that proposal DOES NOT EXIST. Likely, the proposal has been finalized (check 'vscode.d.ts') or was abandoned.
workbench.desktop.main.js:sourcemap:620  INFO [perf] Render performance baseline is 153ms
```

based on this [link](https://github.com/microsoft/vscode-pull-request-github/issues/4518#issuecomment-1429933009), the warnings above maybe can be ignored, I don't know whether they caused my problem.

**Comment by deepak1556** [comment]
Is this issue still present with latest insiders ?

**Comment by littlewu2508** [comment]
> Is this issue still present with latest insiders ?

I'm using 1.84.2 know and the issue disappears. Not sure which commit fix this issue.

**Comment by deepak1556** [comment]
Thanks for confirming. VSCode does not control this behavior, very likely runtime update addressed it.
