### ISSUE TITLE
[Errno 2] No such  file or directory

### ISSUE THREAD

**Issue by YaseminIbryam** [microsoft/vscode#176250]
- Type: <b>Bug</b>
![Screenshot 2023-03-06 175635](https://user-images.githubusercontent.com/96294909/223163400-0e5c986f-a925-4416-affc-532a7c9d8dd6.jpg)

None of my code works in VS Code. I thought I had a mistake in the codes but I tried the print function and it didn't work. I watched videos on the internet telling me to try python manage.py runserver. But again the code doesn't work for me and always gives me [Errno 2] No such file or directory. I have the python language installed.

VS Code version: Code 1.76.0 (92da9481c0904c6adfe372c12da3b7748d74bdcb, 2023-03-01T10:22:44.506Z)
OS version: Windows_NT x64 10.0.19045
Modes:
Sandboxed: Yes

<details>
![Screenshot 2023-03-06 175635](https://user-images.githubusercontent.com/96294909/223163137-b65f6e24-cb4b-4343-8316-64a471c03984.jpg)

<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Celeron(R) N4500 @ 1.10GHz (2 x 1114)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: disabled_off<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|3.71GB (0.62GB free)|
|Process Argv|--crash-reporter-id 1aee7a86-714d-4e33-9ff6-c3fc19d2661d|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
code-runner|for|0.12.0
isort|ms-|2022.8.0
python|ms-|2023.4.0
vscode-pylance|ms-|2023.3.10
jupyter|ms-|2023.2.1000592019
jupyter-keymap|ms-|1.1.0
jupyter-renderers|ms-|1.0.15
vscode-jupyter-cell-tags|ms-|0.1.6
vscode-jupyter-slideshow|ms-|0.1.5

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
azure-dev_surveyone:30548225
pyindex848:30662994
nodejswelcome1cf:30587006
3biah626:30602489
pyind779:30671433
89544117:30613380
pythonsymbol12:30671437
vsctsb:30677850

```

</details>

**Comment by roblourens** [comment]
Please open this on the python extension repo, thanks
