### ISSUE TITLE
vs code extenions uninstalling on their own

### ISSUE THREAD

**Issue by Andreas898434** [microsoft/vscode#176240]
Type: Bug

I don't know how it happend nor do I know how to explain how to reproduce it. When i download an extension and make sure that it was indeed installed and close vscode. When i reopen vscode the extension is gone.

VS Code version: Code 1.76.0 (92da9481c0904c6adfe372c12da3b7748d74bdcb, 2023-03-01T10:22:44.506Z)
OS version: Windows_NT x64 10.0.19045
Modes:
Sandboxed: No

**Comment by aitor-gomila** [comment]
Can you reproduce this in a fresh VSCode install? (rename .vscode folder under your user folder)
