### ISSUE TITLE
set git-error-xxx file language to log

### ISSUE THREAD

**Issue by tjx666** [microsoft/vscode#176222]
if we mark git-error-xxx file log language, we can get syntax highlight and path jump.

![image](https://user-images.githubusercontent.com/41773861/223083337-a706dcb0-da3d-447b-a617-d5c91115b8e4.png)

in log file:

![image](https://user-images.githubusercontent.com/41773861/223083426-f0208d60-d1ff-4190-b260-f02ee32300bd.png)

@lszomoru

**Comment by tjx666** [comment]
@lszomoru What's your opinion about it?

**Comment by lszomoru** [comment]
@tjx666, apologies for not getting back to you on this until now. We have had further discussions on this and we came to the conclusion that the git output is not necessarily a log file, and while marking it as such, will provide some highlighting but it also opens the doors for bugs as to why some tokens are not highlighted while other are. In light of that, we think that this is a perfect candidate for an extension, which you have already implemented. I will go ahead and close this issue but please feel free to reach out to me in case you have any questions or concerns. Thanks!
