### ISSUE TITLE
Jupyter template not working

### ISSUE THREAD

**Issue by janpfeifer** [microsoft/vscode#176218]
I just tried Codespaces for the first time. I clicked on Codespaces, and then I started my first Jupyter template.

Then I opened one of the included notebooks (`matplotlib.ipynb`). The window opened is empty and it loops forever (small moving blue line moving from left to right on top of window).

It also opens the following notifications:

"
Error loading webview: Error: Could not register service workers: NotSupportedError: Failed to register a ServiceWorker for scope ('https://1pvulns9h30c6i2c38d0d0dmih5124tmd0rrgmk5934qicaco55d.vscode-cdn.net/stable/92da9481c0904c6adfe372c12da3b7748d74bdcb/out/vs/workbench/contrib/webview/browser/pre/') with script ('https://1pvulns9h30c6i2c38d0d0dmih5124tmd0rrgmk5934qicaco55d.vscode-cdn.net/stable/92da9481c0904c6adfe372c12da3b7748d74bdcb/out/vs/workbench/contrib/webview/browser/pre/service-worker.js?v=4&vscode-resource-base-authority=vscode-resource.vscode-cdn.net&remoteAuthority=codespaces+janpfeifer-fantastic-space-eureka-gv49p57g79cpgrw'): The user denied permission to use Service Worker..
"

There seems to be an option for "Insiders Version". I tried that as well, but to no avail, same error.

I also tried the latest version of the Jupyter extension plugin by Microsoft, still the same error.

The demo/jupyter template seems to be broken.

Also any advise on how to try it out ?

cheers

ADD ISSUE DESCRIPTION HERE

Version: 1.76.0
Commit: 92da9481c0904c6adfe372c12da3b7748d74bdcb
User Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36
Embedder: codespaces

**Comment by mjbvz** [comment]
What browser are you using? Are you in private mode?

**Comment by janpfeifer** [comment]
hi @mjbvz, thanks for the follow up.

I'm not sure what "private mode" means, but I was using a standard Chrome browser in a linux laptop.

chrome://version ==> 110.0.5481.177 (Official Build) (64-bit)

**Comment by mjbvz** [comment]
In chrome it's called incognito mode. Are you using it or any other privacy type settings, specifically around cookies?

**Comment by janpfeifer** [comment]
Oh, apologies. No, I was not using incognito mode.

I don't have any special cookies settings, or using any extension in that direction. Pretty vanilla set up, as far as I know.

**Comment by janpfeifer** [comment]
Also I tried from 2 different computers, both using Chrome, and Linux 22.04.

**Comment by janpfeifer** [comment]
Oh, ok, today I tried once again. And this time I noticed that Chrome is configured to block third-party cookies -- I hadn't noticed before because that only kicks in later, once I open the jupyter notebooks.

Once I clicked on the little icon to enable it, it works!

**Comment by janpfeifer** [comment]
Maybe worth finding a way to communicate this to the user ?

**Comment by mjbvz** [comment]
Thanks for confirming. Discussed in https://github.com/orgs/community/discussions/26316

AFAIk we can't actually track that this setting is causing the error, but I'll see if we can add some suggestion text to the error message we show
