### ISSUE TITLE
Certain Shift +key produce two character when using --enable-wayland-ime in integrated terminal

### ISSUE THREAD

**Issue by wengxt** [microsoft/vscode#176338]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.76.1 5e805b79fcb6ba4c2d23712967df89a089da575b x64

- OS Version: Arch Linux wayland with weston compositor

Steps to Reproduce:
1. Use weston
2. Use fcitx5 by adding following content to  ~/.config/weston.ini
```
[input-method]
path=/usr/bin/fcitx5
```

3. launch vscode with 
```code --enable-features=UseOzonePlatform --ozone-platform=wayland  --enable-wayland-ime```
4. Focus into integrated terminal
5. Press shift + A, two "A" show up in the terminal. On the contrary, non latin character like Shift+1 to produce "!" doesn't produce two "!".

https://user-images.githubusercontent.com/259684/223308118-53923efc-c846-4e79-a92a-eec0ce512464.mp4

**Comment by deepak1556** [comment]
Thanks for the detailed repro steps, this depends on https://github.com/microsoft/vscode/issues/167757. Please follow that issue for updates.
