### ISSUE TITLE
Relocation of workspace .vscode folder from project root

### ISSUE THREAD

**Issue by DatStorm** [microsoft/vscode#176354]
Hey.

Thanks for producing a great tool! At our organization we are trying to keep a clean folder structure and would like to move `.vscode` folder (red arrow) into the settings folder (green arrow). Though when we do this VS-Code no longer picks it up and the settings is lost. 

The feature wanted is a way to specify the workspace path to the `.vscode` folder.  

![image](https://user-images.githubusercontent.com/23613201/223391476-3ca15120-c0e5-439a-8ee7-758f68576b04.png)

**Comment by sandy081** [comment]
@gjsjohnmurray Thanks for the suggestion
