### ISSUE TITLE
Newest update breaks remote-ssh logins

### ISSUE THREAD

**Issue by dandrep** [microsoft/vscode#176341]
Type: <b>Bug</b>

Version: 1.76.0 (system setup)
Commit: 92da9481c0904c6adfe372c12da3b7748d74bdcb
Date: 2023-03-01T10:22:44.506Z
Electron: 19.1.11
Chromium: 102.0.5005.196
Node.js: 16.14.2
V8: 10.2.154.26-electron.0
OS: Windows_NT x64 10.0.22621
Sandboxed: Yes

Use previous version, connect to a SSH server open directories.  Update VSCode, try again, see a login loop.

VS Code version: Code 1.76.0 (92da9481c0904c6adfe372c12da3b7748d74bdcb, 2023-03-01T10:22:44.506Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|12th Gen Intel(R) Core(TM) i7-1280P (20 x 1997)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.61GB (19.23GB free)|
|Process Argv|--crash-reporter-id a52365b5-c84a-43ad-9a02-f422ddcf76a2|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
windows-explorer-context-menu|ele|3.2.1
vscode-firefox-debug|fir|2.9.8
rainbow-csv|mec|3.5.0
vscode-docker|ms-|1.24.0
remote-containers|ms-|0.282.0
remote-ssh|ms-|0.98.0
remote-ssh-edit|ms-|0.84.0
remote-wsl|ms-|0.76.1
vscode-remote-extensionpack|ms-|0.24.0
remote-explorer|ms-|0.2.0
remote-server|ms-|1.0.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30669237
azure-dev_surveyone:30548225
pyindex848:30662994
nodejswelcome1cf:30587006
2e4cg342:30602488
pyind779:30671433
89544117:30613380
pythonsymbol12:30671437
2i9eh265:30646982
vsctsb:30677850
pythonb192:30669360

```

</details>

**Comment by bvv400** [comment]
#metoo...   No Code-server connection after update of vsc to 1.76 with Remote-ssh  to Strato V Linux server.  In Code server logging in /home/<user>/.vcode a reference is made to the unknown MAC address format.  When I do IP ADDR or IP LINK no MAC address is shown.. Something to do with the Strato V Linux   In the doc of Code Server there is a reference that the MAC address now is used to tackle the hijack cross-site hack..  Options?   The VSC downgrade does not help.

**Comment by roblourens** [comment]
Can you include the log from the Remote-SSH output channel?

@bvv400 I don't understand what you are describing, need more detail or a log thanks

**Comment by bvv400** [comment]
@roblourens   

Issue is solve with https://github.com/microsoft/vscode-remote-release/issues/8149

**Comment by McSneaky** [comment]
All my remotes went missing after update and can't add new ones. It just keeps redirecting me back to extension. Tried reinstall too, but that didn't work. Happy to provide any other info (might need guidance how to provide it tho)

https://github.com/microsoft/vscode/assets/6796697/c39d7eec-a116-488a-971c-724b33a861dc

**Comment by roblourens** [comment]
It looks like you just need to expand the SSH tree node in the explorer to see your remotes?

I will close this since the OP didn't respond and @bvv400 says their issue is fixed. @McSneaky you can open a new issue if you need a followup.

**Comment by McSneaky** [comment]
Aah no, expand button does nothing either

But I'll open separate issue 👍
