### ISSUE TITLE
No account button

### ISSUE THREAD

**Issue by Jiang-Hongbo** [microsoft/vscode#176377]
Type: <b>Feature Request</b>

There is no account button on the side function bar

VS Code version: Code 1.76.0 (92da9481c0904c6adfe372c12da3b7748d74bdcb, 2023-03-01T10:22:44.506Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: No

**Comment by TylerLeonhardt** [comment]
/duplicate https://github.com/microsoft/vscode/issues/176381

You filed that other one too, right? Let's keep it in one issue.
