### ISSUE TITLE
Support Open on vscode.dev from the branch picker

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode#176333]
In https://github.com/microsoft/vscode/issues/175676, we're adding the ability to checkout a PR on vscode.dev in addition to being able to checkout locally. The motivation for this is to allow reviewing PRs in the VS Code UI and benefit from multifile viewing/editing and workbench customizations in VS Code without blowing away your local checkout. 

For similar reasons, it would be helpful to support opening a branch or tag on vscode.dev via the ref picker, e.g. if you want to view the state of the world at a particular ref and compare it side by side to a PR that you're working on locally.

This is pretty straightforward to implement for Remote Repos. Unfortunately one challenge for the deskop git extension is that today we only support viewing GitHub and Azure Repos repositories in vscode.dev, while the ref picker from the desktop git extension doesn't know about vscode.dev at the moment. We do have the GitHub remote source provider from the builtin GitHub extension which is capable of enriching the options we offer in the quickpick. I'm envisioning a `${globe}` quickpick item button which would directly open the branch on vscode.dev if we support opening that provider type and if the branch is already published to a remote of a supported provider type.

**Comment by lszomoru** [comment]
@joyceerhl, is this something that you would like to stab at? Let me know if you need any help from me. Thanks!

**Comment by joyceerhl** [comment]
@lszomoru yes, it would require a new api for the Git Base extension that is implemented by the GitHub extension.
