### ISSUE TITLE
when press ctrl + C it report this... and can't do copy action

### ISSUE THREAD

**Issue by kooboo-chenhai** [Microsoft/vscode#17636]
- VSCode Version: Code 1.8.0 (38746938a4ab94f2f57d9e1309c51fd6fb37553d, 2016-12-13T17:45:32.595Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

|Extension|Author|Version|
|---|---|---|
|vscode-eslint|dbaeumer|1.2.2|
|vscode-babel-coloring|dzannotti|0.0.4|

---

Steps to Reproduce:
![image](https://cloud.githubusercontent.com/assets/13828467/21376143/a0c72fb4-c76d-11e6-8a32-b934d7b746cf.png)

1.
2.

**Comment by egamma** [comment]
@kooboo-chenhai can you please describe the steps you did before this message appeared? Can you provide an animated gif please?

**Comment by kooboo-chenhai** [comment]
@egamma  Software to use an hour later will be that.
 Uh,maybe i opened the translation software namded "youdao" (http://cidian.youdao.com/index.html)  at that time

**Comment by egamma** [comment]
@kooboo-chenhai are you saying this is now working for you and the issue can be closed?

**Comment by kooboo-chenhai** [comment]
no, i means the copy function always not work well when vscode has run some hours

**Comment by egamma** [comment]
@kooboo-chenhai thanks for your reply. 

@peng what does the error message in the screenshot say, can you pls help to translate.

**Comment by King66** [comment]
"WARN cannot copy terminal selection when terminal does not have focus"
#17232

**Comment by Tyriar** [comment]
Updating to v1.8.1 will fix the issue.
