### ISSUE TITLE
`getMachineId` should not use `errors.onUnexpectedError`

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode#176380]
When `getMachineId` fails to get a mac address it still returns a generated mac id, but uses `errors.onUnexpectedError` to log the error.

https://github.com/microsoft/vscode/blob/12a101cee19691869239eaf32642dbb03834bd03/src/vs/base/node/id.ts#L99

That's a bit risky as it rely on VS Code to already have installed a `unexpectedErrorHandler`. The default handler throws an exception in a timeout that can crash the process. (see  issue https://github.com/microsoft/vscode/issues/175878)

IMO the better way would be to pass a logger to  `getMachineId`, e.g. the `ILogService`

-> move `id` to `platform`
-> add `ILogService` to `getMachineId`

**Comment by aeschli** [comment]
@sbatten if you support the idea I can provide a PR

**Comment by sbatten** [comment]
@aeschli that all sounds fine to me, thanks for looking into this. I didn't know this could cause a crash since it had been in desktop for so long.
