### ISSUE TITLE
Turn off colorful syntax highlight at compare

### ISSUE THREAD

**Issue by ljhm** [microsoft/vscode#176305]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 
- OS Version: 

Steps to Reproduce:

1. Turn off colorful syntax highlight at compare
2. Use colorful font for diffs only

**Comment by hediet** [comment]
Can you explain your feature request?

**Comment by ljhm** [comment]
There are some colors are too close. It's hard to see the diffs. Is there an option to turn off color for font at comparison? Just show the color for diffs.

1. Line 28 on the left, the bgcolor for the deletion and the font color for content: , $( .
2. Line 4 on the right, the bgcolor for addition and the font color for content.

![Screen Shot 2023-03-09 at 3 12 43 AM](https://user-images.githubusercontent.com/9011764/223821397-48fe9e2b-769d-4c38-81de-65bc5f9f61db.png)

**Comment by RedCMD** [comment]
you can set the document language to `plaintext` to disable syntax highlighting

**Comment by ljhm** [comment]
> you can set the document language to `plaintext` to disable syntax highlighting

Thanks, It works
