### ISSUE TITLE
Display exception after executing clear terminal

### ISSUE THREAD

**Issue by tisilent** [microsoft/vscode#176397]
![企业微信截图_16782020196574](https://user-images.githubusercontent.com/48614781/223465375-039f411a-8b8c-4ac4-b572-c26e382995b4.png)

1.  new terminal
2.  input echo "1"
3.  clear terminal
4.  input echo

Make up a video tomorrow

**Comment by meganrogge** [comment]
Thanks for the issue, yes a gif would be helpful

**Comment by tisilent** [comment]
![20230308_204022](https://user-images.githubusercontent.com/48614781/223716578-ade34cfb-3874-4ce9-88c1-3f169f77ca2a.gif)
