### ISSUE TITLE
Untitled notebook will prompt to save on window reload or close

### ISSUE THREAD

**Issue by amunger** [microsoft/vscode#176311]
Steps to Reproduce:

1. close any open workspace
2. set "files.hotExit": "onExitAndWindowClose" to not be prompted about saving on close
3. Create a new notebook and add some code
4. reload the window
:bug: save prompt is shown, clicking 'save' doesn't do anything

**Comment by bpasero** [comment]
This is triggered from the following code in notebook land, so sending back to you:

https://github.com/microsoft/vscode/blob/bbc87d8ec2453f12c0066e1c30b41cd5bd2aa021/src/vs/workbench/contrib/notebook/browser/notebook.contribution.ts#L566-L572

**PS:** you do not need to change the hot-exit setting. A window reload will never ask to save.

**Comment by bpasero** [comment]
This is really bad btw...

**Comment by bpasero** [comment]
I think you can close https://github.com/microsoft/vscode/issues/156459 as well.
