### ISSUE TITLE
Add a 3rd option to `editor.suggest.insertMode` such as "languageDefined"

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode#176324]
The current `editor.suggest.insertMode` setting only has 2 options "insert" and "replace", but some extensions have completion behavior that sometimes replaces and sometimes inserts depending on the context (e.g. C++ in VS does replace except when at the beginning of an identifier) -- can a "languageDefined" ("extensionDefined", "implementationDefined", etc.) or equivalent setting be added so users have a 3rd option. Currently, the C/C++ extension "insert" mode behaves like this "languageDefined" option, but it is confusing to users and they don't have the option to choose an "insert" (only) mode.

The previous thread on this is at https://github.com/microsoft/vscode/issues/173940 , but the original issue is different, so I created this new issue.

UPDATE: It's also possible I'm mistaken about this behavior being "extensionDefined", and it's possible this is an expected behavior with the VS Code completion implementation with the "insert" setting when an extension sends certain completion results, in which case it might make more sense to name it something like "insertAtStartOtherwiseReplace" and maybe "insert" could be forced to always "insert"? Or maybe the "insert" enum setting description text just needs to be updated to explain when it switches to replace behavior instead of just saying "Note that this depends on extensions opting into this feature", which our team does not understand.

**Comment by jrieken** [comment]
> but it is confusing to users and they don't have the option to choose an "insert" (only) mode.

The extension is controlling that, it should return a rich range, e.g. one with insert _and_ replace range, whenever possible. E.g there is no reason not to return an insert range when within a word even it if the resulting token isn't an existing symbol name. It's up to the user to decide and the extension should empower, not constraint them. 

So, assuming you have insert and replace range in all cases then the setting works because the user can express their preference. I don't really see what a 3rd option can do here because there is only 2 way to insert a suggestion

**Comment by sean-mcmanus** [comment]
Our extension is returning https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textEdit and VS Code is deciding to do a replace instead of an insert (so the 3rd option would be to mimic that behavior), but I'm guessing that it would be changed to do an insert if we were to change to return a https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#insertReplaceEdit instead, so that is what you'd recommend instead?

**Comment by jrieken** [comment]
> Our extension is returning https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textEdit and VS Code is deciding to do a replace instead of an insert when the mode is insert 

VS Code isn't making any decisions, we simply take the data from the extension as given. That means when a simple range (LSP text edit) is given there is just replace or insert but no choice. Extensions do need to opt into this feature with the extra API provided. 

From the description of the setting

> [...] Note that this depends on extensions opting into this feature.

> but I'm guessing that it would be changed to do an insert if we were to change to return a https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#insertReplaceEdit instead, so that is what you'd recommend instead?

Yes, you definitely need to give both ranges for this to work.

**Comment by jrieken** [comment]
Closing this without action because this depends on extensions
