### ISSUE TITLE
Regression: shellscript subshell functions no longer highlighting

### ISSUE THREAD

**Issue by 1480c1** [microsoft/vscode#176340]
Type: <b>Bug</b>

Write out a .sh file containing a subshell function, example
```shell
#!/usr/bin/bash

function funcfunc() {
    laaa=1
    echo "$laaa"
}

bracefunc() {
    laaa=1
    echo "$laaa"
}

subshellfunc() (
    laaa=1
    echo "$laaa"
)

```
expected result is similar coloration for `subshellfunc()` as `bracefunc()`, actual result is `subshellfunc()`'s body is just normal text color (white in my case)

Expected:
![image](https://user-images.githubusercontent.com/8345542/223309480-927bebed-b377-43d4-a1bc-2e0a067765e2.png)

Actual:
![image](https://user-images.githubusercontent.com/8345542/223309571-f1757a70-7ba0-431a-8afc-48e96d552058.png)

I have tested a fresh installation of VSCode insiders and my normal installation of vscode with extensions disabled.

Upstream issue: https://github.com/jeff-hykin/better-shell-syntax/issues/45

VS Code version: Code - Insiders 1.77.0-insider (0cab3cc3cbe4d4ac2cbf30e8c30351d9db6dcfb4, 2023-03-06T07:17:59.254Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) W-11955M CPU @ 2.60GHz (16 x 2611)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|63.20GB (36.19GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30422396
pythontb:30258533
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscod805cf:30301675
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30404738
cppdebug:30492333
vsclangdf:30492506
c4g48928:30535728
dsvsc012:30540252
pynewext54:30618038
pylantcb52:30590116
pyindex848:30611229
nodejswelcome1:30587009
pyind779:30611226
pythonsymbol12:30651887
a9j8j154:30646983
6233i204:30659907
pythonb192:30661256
pythonms35:30671666
0bg3d529:30676703

```

</details>

**Comment by 1480c1** [comment]
Fixed upstream in https://github.com/jeff-hykin/better-shell-syntax/commit/5e90b2744b5e745a3362fcf7a54a208ac89d915d with v1.4.3

**Comment by alexr00** [comment]
Issue will also be fixed in the next VS Code insiders build.
