### ISSUE TITLE
Telemetry Output channel is missing 

### ISSUE THREAD

**Issue by luabud** [microsoft/vscode#176331]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.77.0-insider
- OS Version: Windows 11

Steps to Reproduce:

1. Set log level to Trace
2. Open the output window. Notice there's no `Telemetry` channel (`Extension Telemetry` is there, just not `Telemetry`)

![image](https://user-images.githubusercontent.com/45497113/223294810-c9cc0f7e-0cc1-4de7-bc34-2580dc0134b6.png)

**Comment by luabud** [comment]
cc @sandy081

**Comment by luabud** [comment]
@sandy081 I'm seeing this again but only in GitHub Codespaces. Should I open an issue on the codespaces repo or a new issue here?

**Comment by sandy081** [comment]
Please open a new issue here with steps to repro. Thanks.
