### ISSUE TITLE
PHP geschweifte Klammern

### ISSUE THREAD

**Issue by schweizerindeutsch** [microsoft/vscode#176364]
Type: <b>Feature Request</b>

Hallo zusammen,
Ich arbeite schon sehr lange mit VSC und bin bis gerstern auch sehr zufreiden damit, seit gestern funktioieren allerdings plötzlich die Klammernfarben und dessen verbindungen nicht mehr.
Also nicht mehr stimmt so nicht ganz, wenn ich einen reinen PHP Code habe stimmen sie, sobald allerdings php unterbrochen wird ( mit ?> html <?php ) verschwinden die Farben, Verhältnisse und Markierungen der geschweiften Klammern.
Beim öffnen des Files stimmen die Farben auch noch ganz kurz bevor sie nach 1sek verschwinden.

Ich habe weder Zeit noch Lust mich stunden mit dem neu Konfigurieren bestehender Software auseinander zu setzten, darum bin ich darüber sehr genervt.
Kennt sich hier jemand mit dem Thema aus? - Die Artikel darüber bei Google haben mir leider nichts gebracht!

Habe schon alles versucht, von Neuinstallation über deaktivieren aller Erweiterungen und Reseten aller Setting einträge.....ich weiss nicht mehr weiter.

Danke für Eure Antworten

VS Code version: Code 1.76.0 (92da9481c0904c6adfe372c12da3b7748d74bdcb, 2023-03-01T10:22:44.506Z)
OS version: Windows_NT x64 10.0.19044
Modes: Restricted
Sandboxed: No

**Comment by schweizerindeutsch** [comment]
Was genau heisst das?

**Comment by lramos15** [comment]
Should be fixed later this week see https://github.com/microsoft/vscode/issues/175797
