### ISSUE TITLE
Manually Set Custom Path to Resolve Shell Environment Settings

### ISSUE THREAD

**Issue by seasonedgeek** [microsoft/vscode#176321]
### Issue

I always observe the "Unable to reslove your shell environment in a reasonable time." dialog box after starting VS Code by UI gesture. Upon clicking the "Configure" button, I can only reset the `application.shellEnvironmentResolutionTimeout` setting to a value greater than 10.

According to the [Resolving Shell Environment Fails](https://code.visualstudio.com/docs/supporting/faq#_resolving-shell-environment-fails) page, I quote: "...VS Code will start a small process to run (or "resolve") the shell environment (as) defined in your .zshrc file...".

The issue is that my shell's environmental settings are found in `~/.zshrc.d/zshenv.zsh`, not in `~/.zshrc`.

Would it be possible to provide an additional configuration setting (such as `application.shellEnvironmentResolutionPath`) to set a custom path to help VS Code resolve environmental settings?

For example, I'd like to manually set `application.shellEnvironmentResolutionPath` to `~/.zshrc.d/zshenv.zsh`.

Thank you!

**Comment by Tyriar** [comment]
We recently added docs to help fix this sort of problem https://code.visualstudio.com/docs/editor/command-line#_how-do-i-detect-when-a-shell-was-launched-by-vs-code

I'm not sure what you mean by the script location being wrong, but the error means the shell we launched is not finishing in a reasonable time. The typical way to fix this is to check if it's vscode's env resolving in your shell scripts and special casing it via `VSCODE_RESOLVING_ENVIRONMENT` if needed
