### ISSUE TITLE
Bracket highlighting does not work properly in VSCode

### ISSUE THREAD

**Issue by qwq0** [microsoft/vscode#176303]
![image](https://user-images.githubusercontent.com/82009862/177005301-9db448d6-e295-4597-a2b8-066a10bb5b36.png)

_Originally posted by @qwq0 in https://github.com/microsoft/vscode/issues/153980#issuecomment-1172909552_

**Comment by hediet** [comment]
Can you share the code so I can paste it and try to reproduce?

**Comment by qwq0** [comment]
> Can you share the code so I can paste it and try to reproduce?

```javascript
let testElement = tag`
    ${new NStyle("color", "red")}

    ${tag`

        ${new NStyle("color", "black")}
    `}

    ${tag`

        ${new NEvent("click", () => console.log("onclick"))}
    `}

    ${tag`

        ${tagName("video")`
        `}
    `}
`;
```

The "tag" above is the tag function for the template literals.

**Comment by hediet** [comment]
The issue is that this is marked as "String":
![image](https://user-images.githubusercontent.com/2931520/223694258-24275967-d728-4814-912c-60758b014b35.png)

**Comment by qwq0** [comment]
Close this issue because it has been fixed.
