### ISSUE TITLE
add suppor for codefixes in TypeScript

### ISSUE THREAD

**Issue by aleksey-bykov** [Microsoft/vscode#17633]
per https://github.com/Microsoft/TypeScript/issues/13068#issuecomment-268406440

**Comment by mjbvz** [comment]
We just merged in #16299 which adds basic support for TS code fixes. The only fixes TS currently supports are adding missing super calls however. We will pick up other fixes as they become available.

**Comment by aleksey-bykov** [comment]
There are imports and unused identifiers fixes already available, please include.

**Comment by mjbvz** [comment]
@aleksey-bykov You can already try those out once TS supports by installing `typescript@next` but we're not planning to pick up TS 2.2 as the bundled version until next year.
