### ISSUE TITLE
Decorations Shift On Enter

### ISSUE THREAD

**Issue by hediet** [microsoft/vscode#176388]
Notice the unused parameter `t` and its flickering decoration:

![Code_-_OSS_f2qH1z7c7W](https://user-images.githubusercontent.com/2931520/223446979-45c3cc46-913d-4be9-9437-a9045bebd084.gif)

Notice how the decoration jumps to the next/previous line (compare parameter `t` and `c` in `strict`):

![image](https://user-images.githubusercontent.com/2931520/223447178-34ca7688-9dd9-453c-a2ac-177679bd28d1.png)

![image](https://user-images.githubusercontent.com/2931520/223447215-182d0850-5a06-40c6-ae8d-cbccc6f44db9.png)

```js
    var __webpack_modules__ = {
        17600: (e, t, r) => {
          "use strict";
          const n = r(50366),
            i = global.Date;
          class a extends i {
            constructor(e) {
              super(e), (this.isDate = !0);
            }
            toISOString() {
              return `${this.getUTCFullYear()}-${n(
                2,
                this.getUTCMonth() + 1
              )}-${n(2, this.getUTCDate())}`;
            }
          }
          e.exports = (e) => {
            const t = new a(e);
            if (isNaN(t)) throw new TypeError("Invalid Datetime");
            return t;
          };
        },
```

**Comment by hediet** [comment]
Not sure, because this time I don't have any extensions installed

![image](https://user-images.githubusercontent.com/2931520/223450720-ee50e0ff-e9e3-4eff-85e5-9ff9b9134fe4.png)

**Comment by mjbvz** [comment]
These faded areas are actually just diagnostics. VS Code handles creating the decorations for them

Based on the recording, I do think this is #159555. Here it looks like we end up showing the stale diagnostic at the wrong position
