### ISSUE TITLE
Extension panel is blur in Hi-DPI screen

### ISSUE THREAD

**Issue by Meeeeow** [Microsoft/vscode#17638]
- VSCode Version: 1.8.1
- OS Version: Windows 10 Version 1607

Steps to Reproduce:

1. A screen with 125% scale
2. Open 'Extension' panel, scroll down, extension name and introduce text is blur, but first one will not blur

![snipaste20161221_115340](https://cloud.githubusercontent.com/assets/19658647/21377018/0e5c3b4e-c775-11e6-9fa2-2a3046a3f916.png)

**Comment by joaomoreno** [comment]
Is this still an issue for you @Meeeeow ?

**Comment by Meeeeow** [comment]
@joaomoreno It should fixed by translate3d detect feature
