### ISSUE TITLE
Different behavior when reinstalling compared with uninstalling

### ISSUE THREAD

**Issue by realaslam786** [microsoft/vscode#176352]
Type: <b>Bug</b>

While working on developing an extension, I often need to reinstall the same version of extension through a .vsix file. However, this reinstall process is failing after taking a time of around 5 minutes. After about 5 minutes, an error message appears with the following text: Command: 'Extensions: Install from VSIX...' resulted in an error. Please restart VS Code before reinstalling ... . 

However, when uninstalling the same extension, the process completes much quickly and without any error messages. Similarly, reinstalling a different version of the same extension also succeeds much quickly and without any issues. Why is the reinstall process behaving differently than the uninstall process? Further, I am also unable to reproduce this issue when trying to Debug the extension, since in that case the control flow is different - with the extension being debugged directly available in the Extension Host. Moreover, I am also unable to use the Developer: Reinstall Extension command, since it is supposed to ónly work for the extensions installed through the Market Place. Searching through the list of issues, this current issue seems somewhat similar to the issue #47164.

PS. After the latest update, the issue seems to have been fixed when installing locally, however, still occurs when doing a remote installation through Remote SSH.

VS Code version: Code 1.76.0 (92da9481c0904c6adfe372c12da3b7748d74bdcb, 2023-03-01T10:22:44.506Z)
OS version: Windows_NT x64 10.0.19044
Modes:
Sandboxed: No
Remote OS version: Linux x64 6.1.12-200.fc37.x86_64
Remote OS version: Linux x64 6.1.12-200.fc37.x86_64

**Comment by sandy081** [comment]
Reinstalling an extension in your case will have to replace the existing extension. Replacing the existing extension might not work if your VS Code window is still using that extension meaning loaded that extension. Therefore replacing the extension fails. Whereas in uninstall, we will just mark it as uninstall and we wont remove it immediately. Hence debugging an extension using extension debugger is recommended.

**Comment by realaslam786** [comment]
When uninstalling, VS Code is able to handle the case even when other windows maybe using parts of the extension. However, why should this failure be regarded as an expected behavior when doing the reinstallation of the same version. VS Code should also gracefully handle this use-case.

**Comment by sandy081** [comment]
> When uninstalling, VS Code is able to handle the case even when other windows maybe using parts of the extension.

As I said, during then we will not remove the extension from disk. But during reinstallation we have to replace the existing extension in the disk.
