### ISSUE TITLE
Indentation detection doesn't work with 3-spaces

### ISSUE THREAD

**Issue by jiggak** [Microsoft/vscode#17639]
- VSCode Version: 1.8.1
- OS Version: any

Steps to Reproduce:

1. Set the following settings:
```json
{
   "editor.tabSize": 3,
   "editor.insertSpaces": true,
   "editor.detectIndentation": true
}
```
2. Open source file that uses 3-space indentation
3. Notice guessed indentation is not 3-spaces (typically guesses 4)

After attempting to debug this it became clear pretty quickly. The `indentationGuesser` is designed to work with [2, 4, 6, and 8 spaces](https://github.com/Microsoft/vscode/blob/1.8.1/src/vs/editor/common/model/indentationGuesser.ts#L90).

So is it feasible to make the indentation guesser work with odd-number space indentation? If not there should probably be something somewhere to tell you the indent detection only works with 2, 4, 6, 8 spaces.

**Comment by jiggak** [comment]
After being more conscience of this issue while working with my code base I noticed sometimes files with 3-space indent do infact have correct indent settings, despite what I described in the issue description.

Here is a source file that consistently opens with incorrect indent settings for testing.

https://gist.github.com/jiggak/ebe980e4cd209381f2b8c0f8f922344c

**Comment by kscharlund** [comment]
I'm also encountering this problem regularly, would love for it to be fixed.

**Comment by holive** [comment]
I'm encountering this problem too..

**Comment by nupanick** [comment]
Happening for me in JavaScript. I set tabs to 3 spaces, and let VSCode auto-format the whole file. Then I set tabs to auto-detect, and it detected 4 spaces. Something's screwy.
