### ISSUE TITLE
Search in all files Discovered by a plugin

### ISSUE THREAD

**Issue by mickae1** [microsoft/vscode#176300]
Currently, when the cmake plugin discover files, we cant search a text in those files:
 
https://github.com/microsoft/vscode-cmake-tools/issues/3033

"The VS Code team owns the search engine. We would need a feature from VS Code to search additional locations outside of the workspace folder"

**Comment by andreamah** [comment]
For search targeting a set of files, please discuss this in https://github.com/microsoft/vscode/issues/20530

/duplicate https://github.com/microsoft/vscode/issues/20530
