### ISSUE TITLE
Problem with debugging 

### ISSUE THREAD

**Issue by ImikeTheFighter** [microsoft/vscode#176385]
Type: <b>Bug</b>

When I press Start debugging, i get the following response: Unable to start debugging, unexpected GDB output from command "-environment-cd ...

I don't know what the issue is, since I have used VS Code many times before and it really bothers me because I can't us it for school like this anymore.
I just updated Windows 11, maybe that's the problem, but I would really liek a solution to this.
![image](https://user-images.githubusercontent.com/63739235/223439062-9b82d8e9-f341-41ae-8e14-80d1b42b69d2.png)

VS Code version: Code 1.76.0 (92da9481c0904c6adfe372c12da3b7748d74bdcb, 2023-03-01T10:22:44.506Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i5-11400H @ 2.70GHz (12 x 2688)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|7.77GB (0.68GB free)|
|Process Argv|--crash-reporter-id 886f482c-6617-4758-b5dc-b95e86fb7f3c|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
c-compiler|bra|0.0.4
vscode-language-pack-hu|MS-|1.48.3
isort|ms-|2022.8.0
python|ms-|2023.4.0
jupyter|ms-|2023.1.2010391206
jupyter-keymap|ms-|1.1.0
jupyter-renderers|ms-|1.0.14
vscode-jupyter-cell-tags|ms-|0.1.6
vscode-jupyter-slideshow|ms-|0.1.5
cpptools|ms-|1.14.4

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
pynewvextcfv2:30669238
azure-dev_surveyonecf:30548226
pyindex848:30662994
nodejswelcome1cf:30587006
282f8724:30602487
pyind779:30671433
89544117:30613380
pythonsymbol12:30671437
2i9eh265:30646982
vsctsb:30677850
vscodeenable:30660116
pythonb192:30669360
funwalk2:30676043

```

</details>

**Comment by roblourens** [comment]
Please file on the c++ debug extension repo
