### ISSUE TITLE
How to add a new action to the editor that replaces editor content and maintains Undo stack ?

### ISSUE THREAD

**Issue by tomitrescak** [Microsoft/vscode#17632]
Hi, I have implemented a java code beautifier which I want to plug into the VS Code editor.
When I call 'setValue' or 'setModel' actions of the monaco editor the text is replaced yet undo stack is destroyed and I cannot undo this action.

Any help is greatly appreciated. Thanks.

**Comment by tomitrescak** [comment]
Just in case anyone stumbles on the same issue, I'm sure it can be handled more graciously, so I'll leave this open for now:

```js
// remove breakpoints
oldDecorations = activeEditor.deltaDecorations(oldDecorations, []);

activeEditor.executeEdits('beautifier', [{ identifier: 'delete' as any, range: new monaco.Range(1, 1, 10000, 1), text: '', forceMoveMarkers: false }]);
activeEditor.executeEdits('beautifier', [{ identifier: 'insert' as any, range: new monaco.Range(1, 1, 1, 1), text: text, forceMoveMarkers: false }]);
activeEditor.setSelection(new monaco.Range(0, 0, 0, 0));
activeEditor.setPosition(currentPosition);

// add breakpoints
oldDecorations = activeEditor.deltaDecorations(oldDecorations, breakPoints);
```

**Comment by egamma** [comment]
Rather than implementing the beautifer as a command that replaces the entire editor contents you should implement a Code formatter as defined by the VS Code API. Please see the [formatter best practices blog](https://code.visualstudio.com/blogs/2016/11/15/formatters-best-practices) from @jrieken
