### ISSUE TITLE
Default profile does not show File Explorer

### ISSUE THREAD

**Issue by yobyot** [microsoft/vscode#176446]
Type: <b>Bug</b>

In VS Code 1.76.0 on macOS Ventura 13.2.1, the default profile hides the File Explorer.

I have found no way to reset the view. I have tried:
1. Uninstalling and reinstalling VS Code and all settings.
2. Removing all extensions.
3. Exporting a working profile and trying to rename it "default" (that's apparently impossible).

Since one apparently cannot overwrite the Default profile, I am at a loss on how to restore the file explorer.

VS Code version: Code 1.76.0 (92da9481c0904c6adfe372c12da3b7748d74bdcb, 2023-03-01T10:23:06.752Z)
OS version: Darwin arm64 22.3.0
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Max (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|2, 2, 2|
|Memory (System)|32.00GB (2.20GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

Here are some screenshots showing the issue, along with an animated .gif showing that removing all settings does not restore the file explorer.

1. Default profile with no installed extensions does not show file explorer

<img width="1095" alt="noexp" src="https://user-images.githubusercontent.com/14332263/223559721-60bf8ebe-179e-40b7-92e2-b0cab56c878d.png">

2. Other profiles _do_ show file explorer, also with no installed extensions

<img width="956" alt="exp1" src="https://user-images.githubusercontent.com/14332263/223560698-d4a39f0d-f9dd-4cfb-b8ff-27d2a3aa957d.png">

4. Animation showing default profile and removing all settings does not restore file explorer.

![2023-03-07_16-41-17 (1)](https://user-images.githubusercontent.com/14332263/223560123-c2634217-0919-4422-89a7-21c4fe9108af.gif)

**Comment by gjsjohnmurray** [comment]
Does https://github.com/microsoft/vscode/issues/176030#issuecomment-1454008617 help you?

**Comment by yobyot** [comment]
Thanks, @gjsjohnmurray.

But, no, that's not it.

<img width="930" alt="nope" src="https://user-images.githubusercontent.com/14332263/223567884-c61d2359-9e7d-4e9d-9f05-ded32dbade44.png">

**Comment by gjsjohnmurray** [comment]
How about https://github.com/microsoft/vscode/issues/176046#issuecomment-1453689195?

**Comment by yobyot** [comment]
Thanks, @gjsjohnmurray.

`Reset View Locations` did the trick.
