### ISSUE TITLE
Shell task opens dual terminals

### ISSUE THREAD

**Issue by macbeth-112358** [microsoft/vscode#176471]
Type: <b>Bug</b>

Normal behavior for a shell task (using the below example config in the workspace tasks.json file) when run will cause a Terminal Panel to open and perform the configured command.

Problem behavior, post-February VS Code update. Running the task will cause the Terminal Panel to open (but NOT execute any commands), and additionally open another Terminal tab in the main editor group (which does run the configured command).

Unfortunately the close=true argument causes only the main group Terminal tab to close, leaving the Terminal Panel open, with it having done nothing.

Sample task in workspace tasks.json:
{
	"label": "Upload Website Scripts",
	"type": "shell",
	"command": ". sync-remote.sh",
	"presentation": { "reveal": "always", "focus": true, "close": true },
	"problemMatcher": []
},

VS Code version: Code 1.76.0 (92da9481c0904c6adfe372c12da3b7748d74bdcb, 2023-03-01T10:23:06.752Z)
OS version: Darwin arm64 21.5.0
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.13GB free)|
|Process Argv|--crash-reporter-id af3733cd-5a3e-4498-b5f5-28820ea082ee|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
render-crlf|med|1.6.1

</details>

**Comment by meganrogge** [comment]
can you provide me with your `settings.json` file?

**Comment by meganrogge** [comment]
maybe related? https://github.com/microsoft/vscode/pull/175376

**Comment by macbeth-112358** [comment]
I don't think it's related to https://github.com/microsoft/vscode/pull/175376, but I'm not sure.

As for the settings file, I was able to isolate a specific setting that prompts the issue:

- `"terminal.integrated.defaultLocation": "editor",`

It looks as though the task `presentation.reveal` and `presentation.focus` apply to the Terminal Panel even with the above setting, at the same time that `presentation.close` applies to the main editor Terminal tab separately.

It seems that updates are trying to respect the above `defaultLocation` setting better, however in the process it butchers the task settings processing by applying them inconsistently.

As it stands currently with latest updates, VS Code no longer supports the ability to allow general new Terminals to be opened in the main editor group (with `defaultLocation=editor`) AND allow Tasks to run solely in the Terminal Panel.

Suggestion: either undo recent code changes causing this issue, or add some isolation logic between general terminal settings and task specific settings, or provide an override configuration option to allow the user to specify one behavior or the other explicitly. -- Either way, current code applies task `presentation` settings inconsistently and needs to be resolved.

**Comment by meganrogge** [comment]
works for me, so I believe this has been fixed 

https://github.com/microsoft/vscode/assets/29464607/d677239a-22b5-420a-89f8-2983948919e7
