### ISSUE TITLE
Settings sync: sync extensions by category

### ISSUE THREAD

**Issue by TheBicPen** [microsoft/vscode#176478]
I like to sync my settings, but syncing extensions takes a long time and I end up with extensions that I don't need. However, I want to sync my theme extensions so I can have the same themes to choose from on all my machines. 

Adding a setting to the settings sync to choose which extension categories to sync would allow me to do this. Alternatively, having an option to only sync extensions under the "Themes" category would also work, but doesn't seem as clean.

**Comment by sandy081** [comment]
You can disable individual extensions to sync

![image](https://user-images.githubusercontent.com/10746682/223731583-5ad513b2-f3be-4fd6-8c4f-57952fe61efc.png)

**Comment by TheBicPen** [comment]
I know I can disable individual extensions to sync. But disabling ~20 extensions on each machine is quite annoying.

**Comment by sandy081** [comment]
I understand your concern but Sorry that this feature might not be in our near time plans based on our priorities.
