### ISSUE TITLE
Profile duplicates when importing using GitHub link 

### ISSUE THREAD

**Issue by cwebster-99** [microsoft/vscode#176442]
- VS Code Version:  1.76

Steps to Reproduce:
Exported a user profile using the GitHub gist link [example](https://vscode.dev/profile/github/91a15b1df5a84d28e91bab5279bb4bed). The user navigates to the link in their browser, where they enter vscode.dev, and the profile opens in the explore view. At the same time, the profile badge is added to the settings icon prior to importing the profile. If the user clicks "Import Profile", they are prompted to overwrite an existing profile. The user has never imported a profile prior to this experience. 

![profileImport](https://user-images.githubusercontent.com/60238438/223557449-0c310dd7-ab2c-4808-af1b-b5cb40be8f80.gif)

**Comment by isidorn** [comment]
@cwebster-99 thanks for great repro steps. I can nicely reproduce.
Assigning to @sandy081

**Comment by sandy081** [comment]
> however the profile badge gets added to the Settings icon and to the Profiles list prior to importing the profile

Yes. This is to indicate user that the profile is applied in preview mode.
