### ISSUE TITLE
Cmd-G should work in Explorer

### ISSUE THREAD

**Issue by atombender** [Microsoft/vscode#17642]
- VSCode Version: 1.8.1

Steps to Reproduce:

1. Search for something
2. Hit Cmd-Shift-E to activate explorer
3. Hit Cmd-G
4. Nothing happens

Cmd-F still works.

I found this out when I was looking for something in some specific files. I clicked on the file, hit Cmd-G and expected matches in that file to be highlighted.

**Comment by rebornix** [comment]
The reason that `cmd+f` works while `cmd+g` doesn't is simple

```
{
  "key": "cmd+g",
  "command": "editor.action.nextMatchFindAction",
  "when": "editorFocus"
}
```

```
{
  "key": "cmd+f",
  "command": "actions.find"
}
```

`cmd+g` only works when `editorFocus` is `true` while when the focus is on the explorer, the value is `false`. To make it meet your need, you just need to add one single keybinding to your settings:

{
  "key": "cmd+g",
  "command": "editor.action.nextMatchFindAction"
}
```

**Comment by atombender** [comment]
Sure, but it would be sensible to make this the default binding.
