### ISSUE TITLE
Says Build task not found

### ISSUE THREAD

**Issue by bdlawrence13** [microsoft/vscode#176452]
Type: <b>Bug</b>

When I go to Run -> Debug, I get an error that says "Could not find the task 'build'". When I go to Configure Task, it opens tasks.json and positions itself on the build task. 

Also, get an error when I hit configure task - the error is: Unable to write to Folder Settings because no resource is provided.

I can run dotnet build from the command line and it works fine. 

VS Code version: Code 1.76.0 (92da9481c0904c6adfe372c12da3b7748d74bdcb, 2023-03-01T10:22:44.506Z)
OS version: Windows_NT x64 10.0.19044
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9850H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.34GB (3.14GB free)|
|Process Argv|--crash-reporter-id 827b3f61-90c9-48d7-9691-b81e84784b6b|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (43)</summary>

Extension|Author (truncated)|Version
---|---|---
armview|ben|0.4.6
cxvscode|Che|2022.3.3
csharpextensions|jch|1.3.1
vscode-nuget-package-manager|jmr|1.1.6
csharpextensions|kre|1.7.3
vscode-azureappservice|ms-|0.24.7
vscode-azurefunctions|ms-|1.10.3
vscode-azureresourcegroups|ms-|0.6.1
vscode-azurestorage|ms-|0.15.1
vscode-cosmosdb|ms-|0.19.3
csharp|ms-|1.25.4
vscode-dotnet-runtime|ms-|1.6.0
vscode-kubernetes-tools|ms-|1.3.11
data-workspace-vscode|ms-|0.4.0
mssql|ms-|1.17.1
sql-bindings-vscode|ms-|0.3.0
sql-database-projects-vscode|ms-|0.21.0
isort|ms-|2022.8.0
python|ms-|2023.4.0
vscode-pylance|ms-|2023.3.10
jupyter|ms-|2023.2.1000592019
jupyter-keymap|ms-|1.1.0
jupyter-renderers|ms-|1.0.15
vscode-jupyter-cell-tags|ms-|0.1.6
vscode-jupyter-slideshow|ms-|0.1.5
remote-containers|ms-|0.282.0
remote-ssh|ms-|0.98.0
remote-ssh-edit|ms-|0.84.0
remote-wsl|ms-|0.76.1
vscode-remote-extensionpack|ms-|0.24.0
azure-account|ms-|0.11.3
cpptools|ms-|1.14.4
js-debug-nightly|ms-|2023.3.617
powershell|ms-|2023.2.1
remote-explorer|ms-|0.2.0
remote-server|ms-|1.0.0
azurerm-vscode-tools|msa|0.15.8
vscode-yaml|red|1.11.0
azure-iot-edge|vsc|1.25.11
azure-iot-toolkit|vsc|2.17.1
azure-iot-tools|vsc|0.3.0
vscode-iot-device-cube|vsc|0.3.0
vscode-iot-workbench|vsc|0.16.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
pynewext54:30669237
azure-dev_surveyone:30548225
vsccc:30610678
pyindex848:30662994
nodejswelcome1cf:30587006
3biah626:30602489
pyind779:30671433
f6dab269:30613381
pythonsymbol12:30671437
a9j8j154:30646983
vsccsb:30677849
pythonb192:30669360
funwalk2:30676043

```

</details>

**Comment by meganrogge** [comment]
Does this always repro? What's your tasks.json file look like?

**Comment by bdlawrence13** [comment]
Yes, reproducible every time. 
Here's my tasks.json
{
    "version": "2.0.0",
    "tasks": [
        {
            "label": "build",
            "command": "dotnet",
            "type": "process",
            "args": [
                "build",
                "${workspaceFolder}/mwhmockserviceui.csproj",
                "/property:GenerateFullPaths=true",
                "/consoleloggerparameters:NoSummary"
            ],
            "problemMatcher": "$msCompile"
        },
        {
            "label": "publish",
            "command": "dotnet",
            "type": "process",
            "args": [
                "publish",
                "${workspaceFolder}/mwhmockserviceui.csproj",
                "/property:GenerateFullPaths=true",
                "/consoleloggerparameters:NoSummary"
            ],
            "problemMatcher": "$msCompile"
        },
        {
            "label": "watch",
            "command": "dotnet",
            "type": "process",
            "args": [
                "watch",
                "run",
                "${workspaceFolder}/mwhmockserviceui.csproj",
                "/property:GenerateFullPaths=true",
                "/consoleloggerparameters:NoSummary"
            ],
            "problemMatcher": "$msCompile"
        },
        {
            "label": "clean",
            "command": "dotnet",
            "type": "process",
            "args": [
                "clean",
                "${workspaceFolder}",
                "/property:GenerateFullPaths=true",
                "/consoleloggerparameters:NoSummary"
            ],
            "problemMatcher": "$msCompile"
        },
        {
            "label": "publish-release",
            "command": "dotnet",
            "type": "process",
            "args": [
                "publish",
                "${workspaceFolder}",
                "--configuration",
                "Release",
                "/property:GenerateFullPaths=true",
                "/consoleloggerparameters:NoSummary"
            ],
            "problemMatcher": "$msCompile",
            "dependsOn": "clean"
        }
    ]
}

**Comment by meganrogge** [comment]
what happens if you run this command?

![Screenshot 2023-03-08 at 9 34 59 AM](https://user-images.githubusercontent.com/29464607/223757372-58729695-9cf2-40ec-a4a7-c8a6831ad157.png)

**Comment by bdlawrence13** [comment]
I typed ctrl+shift+p, then typed in Default Build. It shows me Configure Default Build Task. Selecting that, gives me the option to Open tasks.json file. When I open the file, it then gives me options to select from: Select a task template: MSBUILD, Maven, .NET Core, Others. If I select either MSBUILD or .NET Core, it opens the tasks.json file I sent you and positions on:
 "label": "build",
            "command": "dotnet",
            "type": "process",
            "args": [
                "build",
                "${workspaceFolder}/mwhmockserviceui.csproj",
                "/property:GenerateFullPaths=true",
                "/consoleloggerparameters:NoSummary"
            ],
            "problemMatcher": "$msCompile"

at the args: build,

**Comment by meganrogge** [comment]
you need this for it to be considered the default build task 

```
"group": {
				"kind": "build",
				"isDefault": true
			},
```

![Screenshot 2023-03-08 at 11 10 39 AM](https://user-images.githubusercontent.com/29464607/223781880-b14f28b8-26a1-4e51-813b-95607e770b41.png)

**Comment by bdlawrence13** [comment]
Thanks, that resolved it. Any reason why that changed or disappeared? All I've done is upgrade when told new version available.

**Comment by MSqrl** [comment]
I just encountered the same problem.
It was working fine then it was not working fine and I get: "Unable to write to Folder Settings because no resource is provided."
No changes to tasks.json
