### ISSUE TITLE
i need a comments section in extention

### ISSUE THREAD

**Issue by Chengyanzhao** [Microsoft/vscode#17647]
- VSCode Version:1.8.1
I need a comments section in extension!
it's can help me learn more skills by other users.

**Comment by egamma** [comment]
@Chengyanzhao not clear what you mean, can you please add a screenshot where you would like to have a `comments` section?

**Comment by egamma** [comment]
@Chengyanzhao any update?

**Comment by egamma** [comment]
@Chengyanzhao please reopen the issue once you have added more information as requested above.
