### ISSUE TITLE
rg.exe is pegging my Core i9 CPU at 100% on moderately large repos

### ISSUE THREAD

**Issue by GaryCaldwell** [microsoft/vscode#176420]
Type: <b>Bug</b>

On multiple medium to large sized projects rg.exe from ripgrep is using 100% of my CPU when I edit any file.

VS Code version: Code 1.76.0 (92da9481c0904c6adfe372c12da3b7748d74bdcb, 2023-03-01T10:22:44.506Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9900 CPU @ 3.10GHz (16 x 3096)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|127.80GB (97.19GB free)|
|Process Argv|--crash-reporter-id 01342746-1234-41d4-8362-d71462200349|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (49)</summary>

Extension|Author (truncated)|Version
---|---|---
midl3-language-server|Ale|0.0.31
alexa-skills-kit-toolkit|ask|2.12.1
togglehs|bbe|0.1.2
doxdocgen|csc|1.4.0
vscode-markdownlint|Dav|0.49.0
vscode-eslint|dba|2.4.0
vscode-instant-markdown|dba|1.4.7
xml|Dot|2.5.1
EditorConfig|Edi|0.16.4
prettier-vscode|esb|9.10.4
vscode-mojom|Goo|0.1.4
better-cpp-syntax|jef|1.17.2
ftp-sync|luk|0.3.9
git-graph|mhu|1.30.0
prettify-json|moh|0.0.3
vscode-docker|ms-|1.24.0
csharp|ms-|1.25.4
isort|ms-|2022.8.0
python|ms-|2023.4.0
vscode-pylance|ms-|2023.3.10
sarif-viewer|MS-|3.3.5
jupyter-keymap|ms-|1.1.0
jupyter-renderers|ms-|1.0.15
vscode-jupyter-cell-tags|ms-|0.1.6
vscode-jupyter-slideshow|ms-|0.1.5
remote-containers|ms-|0.282.0
remote-ssh|ms-|0.98.0
remote-ssh-edit|ms-|0.84.0
remote-wsl|ms-|0.76.1
azure-account|ms-|0.11.3
azurecli|ms-|0.5.0
cmake-tools|ms-|1.13.45
cpptools|ms-|1.14.4
cpptools-extension-pack|ms-|1.3.0
powershell|ms-|2023.2.1
remote-explorer|ms-|0.2.0
vscode-jest|Ort|5.2.3
proto|pet|0.0.2
annotator|ryu|1.0.0
pin-up|sae|1.4.1
rewrap|stk|1.16.3
code-spell-checker|str|2.19.0
ms-teams-vscode-extension|Tea|4.2.4
cmake|twx|0.0.17
intellicode-api-usage-examples|Vis|0.2.7
vim|vsc|1.25.2
vscode-bond|yiw|0.0.10
markdown-all-in-one|yzh|3.5.0
json|Zai|2.0.2

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
azure-dev_surveyone:30548225
pyindex848:30662994
nodejswelcome1cf:30587006
2e4cg342:30602488
pyind779:30671433
f6dab269:30613381
pythonsymbol12:30671437
a9j8j154:30646983
6233i204:30672705
vsccsb:30677849
vscodedisable:30660115
pythonb192:30669360
funwalk2:30676043
pythonms35:30676800

```

</details>

**Comment by AriESQ** [comment]
This is a well known issue on Windows and Linux, please fix.

**Comment by andreamah** [comment]
Apologies for getting to this so late; it looks like I overlooked it when triaging issues. Have you tried this with all extensions disabled?

**Comment by GaryCaldwell** [comment]
I did and it was one of the extensions I had.   I tore them down completely and re-added what I needed and the problem went away.   Don't know the culprit but the problem is gone.


Sent from Outlook<http://aka.ms/weboutlook>

________________________________
