### ISSUE TITLE
extension host terminated unexpectedly

### ISSUE THREAD

**Issue by TeddyCr** [microsoft/vscode#176449]
Type: <b>Bug</b>

When starting VS Code I suddently started receiving `extension host terminated unexpectedly` error

VS Code version: Code 1.76.0 (92da9481c0904c6adfe372c12da3b7748d74bdcb, 2023-03-01T10:23:06.752Z)
OS version: Darwin arm64 22.2.0
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Max (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|9, 11, 9|
|Memory (System)|32.00GB (1.49GB free)|
|Process Argv|--crash-reporter-id 475f586b-fe23-4166-ae70-922048074e82|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (34)</summary>

Extension|Author (truncated)|Version
---|---|---
gitlens|eam|13.3.2
copilot|Git|1.77.9225
vscode-pull-request-github|Git|0.60.0
vscode-test-explorer|hbe|2.21.1
vscode-python-test-adapter|lit|0.7.1
rainbow-csv|mec|3.5.0
vscode-docker|ms-|1.24.0
isort|ms-|2022.8.0
python|ms-|2023.4.0
vscode-pylance|ms-|2023.3.10
remote-containers|ms-|0.282.0
remote-ssh|ms-|0.98.0
remote-ssh-edit|ms-|0.84.0
cmake-tools|ms-|1.13.45
cpptools|ms-|1.14.4
cpptools-extension-pack|ms-|1.3.0
live-server|ms-|0.4.6
makefile-tools|ms-|0.6.0
remote-explorer|ms-|0.2.0
test-adapter-converter|ms-|0.1.6
autodocstring|njp|0.6.1
fabric8-analytics|red|0.3.6
java|red|1.15.0
vscode-xml|red|0.24.0
vscode-yaml|red|1.11.0
cmake|twx|0.0.17
intellicode-api-usage-examples|Vis|0.2.7
vscodeintellicode|Vis|1.2.30
vscode-java-debug|vsc|0.49.0
vscode-java-dependency|vsc|0.21.1
vscode-java-pack|vsc|0.25.8
vscode-java-test|vsc|0.38.1
vscode-maven|vsc|0.40.4
material-theme|zhu|3.15.6

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
pynewvextcfv2:30669238
azure-dev_surveyonecf:30548226
pyindex848:30662994
nodejswelcome1cf:30587006
282f8724:30602487
pyind779:30671433
89544117:30613380
pythonsymbol12:30671437
a9j8j154:30646983
vsctsb:30677850
pythonb192cf:30669361
pythonms35cf:30676801

```

</details>

**Comment by bpasero** [comment]
Can you please follow the steps in https://github.com/Microsoft/vscode/wiki/Native-Crash-Issues to get at more details around the crash and attach the result here? Thanks!

**Comment by TeddyCr** [comment]
Sounds good. Will share more info once I get the crash report.

**Comment by TeddyCr** [comment]
@bpasero, I followed the instruction in the link you shared, but can't find any `*.dmp` file.
![Screenshot 2023-03-09 at 10 24 42 PM](https://user-images.githubusercontent.com/13626425/224163293-1867a5ed-37dd-4f38-be3f-658c31e8f83e.png)
![Screenshot 2023-03-09 at 10 25 08 PM](https://user-images.githubusercontent.com/13626425/224163300-7b54f928-95b0-46de-9c51-a225b661e95a.png)

**Comment by starball5** [comment]
Possibly related: #176562

**Comment by TeddyCr** [comment]
Thanks I'll track the update it over there 🙂
