### ISSUE TITLE
A missing problem matcher results in the debugger not launching

### ISSUE THREAD

**Issue by alexdima** [microsoft/vscode#176496]
When having a launch config for debugging extensions which uses a task which uses a missing problem matcher (like `$ts-webpack-watch`), the extension host development window no longer pops up. This used to work in the past. 

This apparently used to work until recently.

cc @hstaudacher @jrieken

**Comment by meganrogge** [comment]
> which uses a missing problem matcher

I'm not sure what a missing problem matcher is - if you mean `[]` as the problem matcher, we used to create the `WatchingProblemCollector` even when there was no problem matcher provided and that changed here

https://github.com/microsoft/vscode/pull/175376

@alexr00 wasn't around for that change, so it's possible I broke this then

**Comment by alexr00** [comment]
I think @alexdima means that if your task refers to a problem matcher that isn't installed.

**Comment by hstaudacher** [comment]
In our case it was:

```json
        {
            "type": "shell",
            "problemMatcher": "$ts-webpack-watch",
            "label": "watch",
            "command": "make",
            "args": [
                "watch"
            ],
            "group": "build",
            "isBackground": true
        },
```

**Comment by meganrogge** [comment]
@hstaudacher thanks for that info. Pretty sure the cause is #175376. 

Did this repro in insider's for you?

**Comment by hstaudacher** [comment]
Not sure what you mean here. I haven't installed the mentioned extension (watcher), used insiders, our run stoped working.

**Comment by meganrogge** [comment]
I cannot repro - I can run tasks with invalid problem matchers and can debug/launch the extension

**Comment by meganrogge** [comment]
I can reproduce - have a `preLaunchTask` with a `problemMatcher` that's either invalid or non-existent IE `[]`. Debug and the windows doesn't open

**Comment by hstaudacher** [comment]
Thanks a lot!
