### ISSUE TITLE
Git Bash opening from vs code

### ISSUE THREAD

**Issue by khaled-hossain-code** [Microsoft/vscode#17641]
- VSCode Version: 1.8.1
- OS Version: win 10

Request for feature:-
Each time I have to install a npm package I have to open my git bash terminal, as it is the only one which does not give any error while I am installing. can you please add any shortcut so that I can open git Bash in the present directory from vscode.

**Comment by egamma** [comment]
Some options:
- use the integrated terminal `View>Integrated Termnial`

- use the 'Open Command Prompt' command that is available when you select a folder in the explorer?  Pls see below:
![image](https://cloud.githubusercontent.com/assets/172399/21394526/3c8452b2-c799-11e6-9f4f-2083c7437954.png)

**Comment by egamma** [comment]
@khaled-hossain-code does the answer above cover your feature request?

**Comment by khaled-hossain-code** [comment]
not actually, I know that I can open command prompt but now a days npm gives error while trying to install npm package inside vscode or command prompt but It does not happen with git bash. So I wanted a quick way to access git bash command Prompt from vs code may be just a shortcut key.

**Comment by egamma** [comment]
@khaled-hossain-code thanks for following up

>npm gives error while trying to install npm package inside vscode or command prompt but It does not happen with git bash.

Can you please add a screenshot that illustrates the problem. I'm regularly running `npm install` inside the integrated terminal and do not have this problem. If there is an issue then we should address it.

**Comment by khaled-hossain-code** [comment]
@egamma sorry my bad, there was one but it is solved now. yes you can close this request.
