### ISSUE TITLE
Provide a way to manually reload an opened file

### ISSUE THREAD

**Issue by Jai1122** [Microsoft/vscode#17643]
- VSCode Version:1.8.1
- OS Version:Windows 7 64 bit

I am trying to analyze the log files. It would be very helpful if i have a feature like a button click or a command to reload a file from disk. I can see the file being reloaded automatically but i am expecting a command to reload the file manually/only when needed. 

Any suggestion or help on this feature please?

Thanks,
Jai.

**Comment by bpasero** [comment]
`File > Revert File` allows to do so. It will fetch the contents of the file from disk even if not dirty.
