### ISSUE TITLE
Search: `list.focusDown` and `list.focusUp` don't work after opening again when the fields are filled

### ISSUE THREAD

**Issue by RobbyCBennett** [microsoft/vscode#176438]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.76.0 (system setup)
- OS Version: Windows 11

Steps to Reproduce:

1. `workbench.action.replaceInFiles` to search all files
2. Type in something that results in multiple results
3. `search.action.focusSearchList` to go down to the results
4. Move up and down and see that files open when focusing on them for about half a second
5. `workbench.action.closeAuxiliaryBar` to close the search panel
6. `workbench.action.replaceInFiles` to search all files again
7. The search bar is still filled
8. `search.action.focusSearchList` to go down to the results
9. Move up and down and see that files no longer open

https://user-images.githubusercontent.com/22121365/223552188-06a21103-8ba0-4b89-87a8-67585e56df94.mp4

**Comment by andreamah** [comment]
Hmm, I can't seem to reproduce this. Do you have any search-related settings that are non-default?

**Comment by RobbyCBennett** [comment]
No. I still have the problem with all extensions disabled with `code --disable-extensions` and no settings whatsoever (I cleared settings.json for User settings, and there were no settings for Workspace).

**Comment by RobbyCBennett** [comment]
Here I show that I have no settings, no extensions and I can reproduce the issue.

https://user-images.githubusercontent.com/22121365/225795286-89c1533f-29a5-4f9a-a728-e2d3ef52abbc.mp4

**Comment by RobbyCBennett** [comment]
I've also noticed a related issue with the UX with the search sidebar. The focused input is the replace field, even though I would expect it to be the search field for consistency.

**Comment by andreamah** [comment]
Does this still happen on vscode insiders? I made a fix a few weeks ago that had to do with `focusSearchList`. https://github.com/microsoft/vscode/issues/172894

**Comment by RobbyCBennett** [comment]
That fixed it. Thank you very much.
