### ISSUE TITLE
User task that specifies dependsOn property fail to run

### ISSUE THREAD

**Issue by frankshrestha** [microsoft/vscode#176469]
Type: <b>Bug</b>

Add the following in the user tasks.json and run the Language Mode task.

```json
{
    "version": "2.0.0",
    "tasks": [
        {
            "label": "New File",
            "command": "${command:workbench.action.files.newUntitledFile}",
            "problemMatcher": []
        },
        {
            "label": "Language Mode",
            "command": "${command:workbench.action.editor.changeLanguageMode}",
            "problemMatcher": [],
            "dependsOn": ["New File"]
        }
    ]
}
```

# Actual Result:

Nothing happens.

# Expected Result:

Create a new file and open Language Mode selection.

VS Code version: Code 1.76.0 (Universal) (92da9481c0904c6adfe372c12da3b7748d74bdcb, 2023-03-01T10:23:45.993Z)
OS version: Darwin arm64 22.1.0
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|2, 2, 2|
|Memory (System)|8.00GB (0.06GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by frankshrestha** [comment]
Never mind. Started working again automagically.

**Comment by frankshrestha** [comment]
Occasionally works.

**Comment by meganrogge** [comment]
did this just start not working? 

if so, could be related to https://github.com/microsoft/vscode/pull/175376

**Comment by meganrogge** [comment]
This is working for me
https://user-images.githubusercontent.com/29464607/224399656-3e154a18-4ed0-4f37-8337-18c12ee2c282.mov

**Comment by frankshrestha** [comment]
It is only working in the insiders version.
