### ISSUE TITLE
The result of automatic language recognition is wrong

### ISSUE THREAD

**Issue by willhancn** [microsoft/vscode#176487]
Type: <b>Bug</b>

After creating a new file (not saved, thus the file has no extension), enter 25 empty lines, then enter some Chinese in the first and 10th lines, the Chinese sequence is like: "${some Chinese}${Chinese semicolon}${some other Chinese}" (Note that it is not an English semicolon) , VS Code will automatically identify the programming language as 'docker', which is very wrong, because there is no English semicolon and comma in the entire text, which does not conform to the docker syntax at all. 

In addition to the Chinese semicolon that lead to identification as Docker language, Chinese comma will often be recognized as INI language. This error occurs so often, that I frequently want to smash the computer. Most of the time, I just write a note, I don't need any grammar correction and highlight at all.

VS Code version: Code 1.76.0 (92da9481c0904c6adfe372c12da3b7748d74bdcb, 2023-03-01T10:22:44.506Z)
OS version: Windows_NT x64 10.0.19044
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.76GB (9.99GB free)|
|Process Argv|--crash-reporter-id 72a97d7a-0980-4276-8b2a-fbc1b7aac086|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-language-pack-zh-hans|MS-|1.76.2023030109

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
pynewvextcfv2:30669238
azure-dev_surveyone:30548225
pyindex848:30662994
nodejswelcome1:30587005
282f8724:30602487
pyind779:30671433
89544117:30613380
pythonsymbol12:30671437
2i9eh265:30646982
showlangstatbar:30672706
vsccsb:30677849
vscodedisable:30660115
funwalk2:30676043
pythonms35:30680984

```

</details>

**Comment by TylerLeonhardt** [comment]
This is a challenging one to fix, so I want to say if you really don't like the language detection feature, you can disable it with this setting:
```
"workbench.editor.languageDetection": false
```

**Comment by prinsss** [comment]
I'm facing the same issue here. Here is a text sample that falsely detected as `ini` (Code 1.80.0).

```
参数
target
要使用 Proxy 包装的目标对象（可以是任何类型的对象，包括原生数组，函数，甚至另一个代理）。

handler
一个通常以函数作为属性的对象，各属性中的函数分别定义了在执行各种操作时代理 p 的行为。
```

<img width="940" alt="Snipaste_2023-07-14_11-55-38" src="https://github.com/microsoft/vscode/assets/11206497/bed3f1bc-88d0-41af-b075-e963ef3a4ff3">

**Comment by TylerLeonhardt** [comment]
Linking this to the mega thread for follow up https://github.com/microsoft/vscode/issues/172573
