### ISSUE TITLE
run

### ISSUE THREAD

**Issue by IgorStrauss** [microsoft/vscode#176416]
Type: <b>Bug</b>

when running the application with: python main.py or another script, it returns -u, plugins, kwargs = u._instantiate_plugins(kwargs).
when executing with the top menu, run/start debugging button the system works.

VS Code version: Code 1.76.0 (92da9481c0904c6adfe372c12da3b7748d74bdcb, 2023-03-01T10:25:16.105Z)
OS version: Linux x64 5.15.0-67-generic
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-2400 CPU @ 3.10GHz (4 x 3247)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|1, 1, 1|
|Memory (System)|7.65GB (2.38GB free)|
|Process Argv|. --crash-reporter-id 92858755-51a4-422b-af79-c6796f6290c4|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|budgie-desktop|
|XDG_CURRENT_DESKTOP|Budgie:GNOME|
|XDG_SESSION_DESKTOP|budgie-desktop|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (47)</summary>

Extension|Author (truncated)|Version
---|---|---
rainbow-brackets|2gu|0.0.6
vscode-css-formatter|aes|1.0.2
vscode-sqlite|ale|0.14.1
vscode-apollo|apo|1.19.11
vscode-django|bat|1.10.0
vscode-postgres|cko|1.4.0
vscode-eslint|dba|2.4.0
python-environment-manager|don|1.0.4
python-extension-pack|don|1.7.0
gitlens|eam|13.3.2
vscode-html-css|ecm|1.13.1
EditorConfig|Edi|0.16.4
code-runner|for|0.12.0
vscode-mysql|for|0.4.1
vscode-pull-request-github|Git|0.60.0
todo-tree|Gru|0.0.224
github-copilot-with-context|Jer|0.1.2
vscode-colorize|kam|0.11.1
vsc-python-indent|Kev|1.18.0
git-graph|mhu|1.30.0
language-gettext|mro|0.2.2
vscode-docker|ms-|1.24.0
vscode-language-pack-pt-BR|MS-|1.76.2023030109
vscode-postgresql|ms-|0.3.0
flake8|ms-|2023.4.0
isort|ms-|2022.8.0
python|ms-|2023.4.0
vscode-pylance|ms-|2023.3.10
jupyter|ms-|2023.2.1000592019
jupyter-keymap|ms-|1.1.0
jupyter-renderers|ms-|1.0.15
vscode-jupyter-cell-tags|ms-|0.1.6
vscode-jupyter-slideshow|ms-|0.1.5
remote-containers|ms-|0.282.0
makefile-tools|ms-|0.6.0
reload|nat|0.0.6
autodocstring|njp|0.6.1
om-extension-pack|omt|0.0.2
material-icon-theme|PKi|4.24.0
vscode-yaml|red|1.11.0
LiveServer|rit|5.7.9
sourcery|sou|1.0.6
code-spell-checker|str|2.19.0
code-spell-checker-portuguese-brazilian|str|2.0.11
intellicode-api-usage-examples|Vis|0.2.7
vscodeintellicode|Vis|1.2.30
jinja|who|0.0.8

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30669237
azure-dev_surveyone:30548225
pyindex848:30662994
nodejswelcome1:30587005
282f8724:30602487
pyind779:30671433
f6dab269:30613381
pythonsymbol12:30671437
2i9eh265:30646982
6233i204:30672705
vsctsb:30677850
vscodeenable:30660116
pythonb192:30669360
funwalk2cf:30676044

```

</details>

**Comment by roblourens** [comment]
If there is an issue, it sounds like an issue with the python extension. Please file on their repo but include much more detail
