### ISSUE TITLE
`'view.workbench.panel.repl.view.visible'` context appears to always be `false`

### ISSUE THREAD

**Issue by zachsiegel-capsida** [microsoft/vscode#176443]
Does this issue occur when all extensions are disabled?: Yes/No
Yes

- VS Code Version: 1.76.0
- OS Version: 
Windows 11 Insider Preview (10.0.22621.1391) (KB5023011)

Steps to Reproduce:

1. Reference `view.workbench.panel.repl.view.visible` in the "when" clause of a keyboard shortcut. It will always be `false`. Open developer tools and "Inspect Context Keys" to confirm that it is always `false`.

I believe this context key should be set to `true` when there is an open editor pane/tab that contains a terminal (what you get after "Terminal: Move Terminal into Editor Area"). **If that's not what this context key means, I would greatly appreciate it if [the documentation about contexts](https://code.visualstudio.com/api/references/when-clause-contexts) was updated to clarify, and if a context was added to detect whether a terminal is open in an editor area**.

Thank you very much!

**Comment by roblourens** [comment]
`repl` is the debug console. There is probably another key with "terminal" in the name

**Comment by Tyriar** [comment]
Yes there is: https://code.visualstudio.com/api/references/when-clause-contexts#visiblefocused-view-when-clause-context

**Comment by zachsiegel-capsida** [comment]
Thank you, @roblourens @Tyriar for your responses and for maintaining this wonderful software.
