### ISSUE TITLE
github signin eveytime on linux

### ISSUE THREAD

**Issue by aurkaxi** [microsoft/vscode#176486]
I googled and view couple of issues but they were in macos. I do have installed gnome-keyring, git-credential-manager.
all git commands work fine doesn't require signin everytime. but github copilot, settings sync account etc asks to login everytime i open vscode.
fresh install of archlinux.

**Comment by lszomoru** [comment]
This seems to be related to the GitHub auth extension. @TylerLeonhardt, could you please take a look?

**Comment by aurkaxi** [comment]
well it is working again  i don't know why, didn't do anything.
