### ISSUE TITLE
Extension host terminated unexpectedly 3 times within the last 5 minutes.

### ISSUE THREAD

**Issue by Zuhaily98** [microsoft/vscode#176455]
Type: <b>Bug</b>

Extension host terminated unexpectedly 3 times within the last 5 minutes.

VS Code version: Code 1.76.0 (Universal) (92da9481c0904c6adfe372c12da3b7748d74bdcb, 2023-03-01T10:23:45.993Z)
OS version: Darwin x64 20.6.0
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4578U CPU @ 3.00GHz (4 x 3000)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|7, 5, 6|
|Memory (System)|16.00GB (6.72GB free)|
|Process Argv|--crash-reporter-id 9a892b25-2739-445e-aeb4-6b2054749019|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (22)</summary>

Extension|Author (truncated)|Version
---|---|---
laravel-extra-intellisense|ami|0.6.2
laravel-blade-spacer|aus|2.1.3
shell|bbe|0.3.0
npm-intellisense|chr|1.4.4
path-intellisense|chr|2.8.4
vscode-eslint|dba|2.4.0
vscode-html-css|ecm|1.13.1
copilot|Git|1.77.9225
vue-snippets|hol|1.0.4
php-cs-fixer|jun|0.3.9
php-namespace-resolver|Meh|1.1.9
laravel-intellisense|moh|0.2.0
vetur|oct|0.37.3
indent-rainbow|ode|8.3.1
laravel-blade|one|1.32.0
laravel5-snippets|one|1.15.0
material-icon-theme|PKi|4.24.0
format-html-in-php|rif|1.7.0
vscode-blade-formatter|shu|0.20.12
gitblame|wad|10.1.0
JavaScriptSnippets|xab|1.8.0
php-debug|xde|1.32.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
pynewvextcfv2:30669238
azure-dev_surveyonecf:30548226
vscccc:30610679
pyindex848:30662994
nodejswelcome1:30587005
282f8724:30602487
pyind779:30671433
89544117:30613380
vscrp:30673768
pythonsymbol12:30671437
2i9eh265:30646982
showlangstatbar:30672706
vsccsb:30677849
funwalk2:30676043
pythonms35:30676800

```

</details>

**Comment by phoique** [comment]
I have that same problem

**Comment by coffenbacher** [comment]
I have the same problem, somehow it's only when editing new/unsaved files for me 🤔 the extension host chokes immediately. 

2023-03-08 13:15:26.391 [info] ExtensionService#_doActivateExtension GitHub.copilot, startup: false, activationEvent: 'onStartupFinished'
2023-03-08 13:15:26.435 [info] ExtensionService#_doActivateExtension GitHub.copilot-labs, startup: false, activationEvent: 'onStartupFinished'
2023-03-08 13:15:26.935 [error] SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at /Users/coffenbacher/.vscode/extensions/vscodevim.vim-1.25.2/out/extension.js:2:670352
2023-03-08 13:15:27.006 [error] Error: ENOENT: no such file or directory, open 'Untitled-1'
2023-03-08 13:15:27.018 [error] Error: ENOENT: no such file or directory, open 'Untitled-1'
2023-03-08 13:15:27.030 [error] Error: ENOENT: no such file or directory, open 'Untitled-1'

**Comment by bpasero** [comment]
Can you please follow the steps in https://github.com/Microsoft/vscode/wiki/Native-Crash-Issues to get at more details around the crash and attach the result here? Thanks!

**Comment by Zuhaily98** [comment]
I think it has something to do with my GitHub copilot extension

**Comment by phoique** [comment]
> I think it has something to do with my GitHub copilot extension

I agree with that. Today I turned off the github copilot plugin. I didn't get any errors. When I turn it on and try it crashes after a few minutes.

**Comment by bpasero** [comment]
Does it improve anything if you configure `window.experimental.useSandbox` to `true` in settings and restart?

**Comment by phoique** [comment]
> Does it improve anything if you configure `window.experimental.useSandbox` to `true` in settings and restart?

I tried for you. I used GitHub copilot extension turned off all day. There is no problem. After activating the setting you mentioned, I also activated the GitHub copilot extension. Same thing a few minutes later.

**Comment by bpasero** [comment]
Can you please follow the steps in https://github.com/Microsoft/vscode/wiki/Native-Crash-Issues to get at more details around the crash and attach the result here? Thanks!

**Comment by isidorn** [comment]
Thank you very much for opening this issue. We are currently investigating Copilot causing crashes and we are consolidating all the findings in https://github.com/microsoft/vscode/issues/176562
It would be super helpful if you follow steps in https://github.com/Microsoft/vscode/wiki/Native-Crash-Issues to get more details and then comment on https://github.com/microsoft/vscode/issues/176562

Due to the consolidation I am closing this as a duplicate.
