### ISSUE TITLE
comments API issue when `addComment` called too early

### ISSUE THREAD

**Issue by alexandruavadanii** [microsoft/vscode#176498]
Type: <b>Bug</b>

1. Create a `CommentController` and a `commentingRangeProvider` using the comments API
2. Call the inbuilt vscode command `workbench.action.addComment` (or try to manually add a comment via the gutter decorator as soon as possible, but that's a bit harder to manually reproduce)

Expected behavior:
- `addComment` does nothing before the `commentingRangeProvider` is in full effect (gutter decorations are shown);
- `addComment` opens the comment editor after the gutter decorations are visible;

Actual behavior:
- `addComment` called as soon as possible (i.e. before the gutter decorations are rendered) will prevent further comments from being added via either the `addComment` inbuilt command called directly from an extension or from the gutter;
- delaying the first call to `addComment` for a while (e.g. 1 second is overkill, but a safe enough delay) works fine;
- having a previously opened (even untitled and empty) document seems to somehow bypass this, at least in the minimalistic code I used to reproduce it;

To reproduce the issue in the below GIF, I added [a simple commit](https://github.com/alexandruavadanii/vscode-extension-samples/commit/dd96420f5ea2359729cbfa2dfdc92a0c695e27b5) to the `comment-sample` extension.
![addComment_0ms](https://user-images.githubusercontent.com/11544783/223689753-937d6fd6-a1d8-43cd-9445-1df49e484d74.gif)

[With a 1 second delay](https://github.com/alexandruavadanii/vscode-extension-samples/commit/d3fb48102d53e9486a9c21eef7d62b3ab045a826), everything works as expected:
![addComment_1000ms](https://user-images.githubusercontent.com/11544783/223690640-8fce730e-04bb-4987-a6c4-d86631fb39f5.gif)

Also, without a delay, but with an untitled document open from a previous run, everything still works as expected:
![addComment_0ms_2nd_doc](https://user-images.githubusercontent.com/11544783/223690816-96c832bc-fbcf-4b03-b540-296e86fe1088.gif)

`comment-sample` fork used to reproduce:
https://github.com/alexandruavadanii/vscode-extension-samples/tree/comments-sample-addComment-without-delay/comment-sample

VS Code version: Code - Insiders 1.77.0-insider (bbc87d8ec2453f12c0066e1c30b41cd5bd2aa021, 2023-03-07T05:23:49.023Z)
OS version: Windows_NT x64 10.0.18362
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.81GB (7.10GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by alexandruavadanii** [comment]
For the record, the samples mentioned above will fail to reproduce the issue in the latest release, since https://github.com/microsoft/vscode/issues/179610 manifests first (with or without the delay).

**Comment by TylerLeonhardt** [comment]
![Recording 2023-04-27 at 11 57 07](https://user-images.githubusercontent.com/2644648/234964462-44c200a0-9b8b-4f97-a899-d3f10bea798f.gif)

I feel like there's still an issue here... but I'm not sure... so the gif shows that the comment does open up... but I can't get the `+` sign to show up unless I add a newline in this file, or I switch to a different editor and back to the one that didn't show the `+` sign. Let me know if that makes sense...

**Comment by alexr00** [comment]
That seems to be an issue with commenting range providers. Let's call it a separate issue: https://github.com/microsoft/vscode/issues/181099
