### ISSUE TITLE
Syntax highlighting of switch-case in C breaks when using Duff's device

### ISSUE THREAD

**Issue by kenbyte** [microsoft/vscode#176572]
Does this issue occur when all extensions are disabled? Yes

- VS Code Version: Version: 1.76.0
- OS Version: Ubuntu 22.04

**Steps to Reproduce:** Write a switch-case statement and put the `case` labels inside any contained compound statement, like in [Duff's device](https://en.m.wikipedia.org/wiki/Duff%27s_device).

**Behavior:** `case` labels inside nested blocks aren't highlighted.

**Expected:** All `case` labels should be highlighted uniformly, wherever they may be inside the switch statement. There probably isn't any reason ever to not highlight the `case` keyword; after all, we also highlight `break` everywhere (and the compiler will get angry when the syntax isn't correct anyway).

**Logical error that caused this:** In C/C++, the language spec on the switch statement is pretty lax and makes it more of a set of goto statements operated by an if-else block than pure if-else syntax sugar. This is why the case labels closely match the syntax for normal labels to be jumped to directly using `goto`.

**Comment by alexr00** [comment]
Moved to the upstream repo that we get our C syntax highlighting grammar from: https://github.com/jeff-hykin/better-c-syntax/issues/8
