### ISSUE TITLE
Notebook Search leaves text decoration on dismiss

### ISSUE THREAD

**Issue by andreamah** [microsoft/vscode#176548]
1. enable `search.experimental.notebookSearch` 
2. Make a search in an open notebook
3. Dismiss a result in the notebook
4. the text decoration for that match is still there :bug:

**Comment by andreamah** [comment]
related: #177536

**Comment by sandy081** [comment]
This can also be reproduced at step 3 enabling case sensitive option

<img width="551" alt="image" src="https://user-images.githubusercontent.com/10746682/226606144-c14a53a9-80d7-4b44-a66f-52b9afefb8b3.png">
