### ISSUE TITLE
Zoom Out hotkey not working on macOS and Italian layout

### ISSUE THREAD

**Issue by lorthirk** [Microsoft/vscode#17656]
- VSCode Version: 1.8.1
- OS Version: macOS Sierra 10.12.2

Steps to Reproduce:

1. Set Italian layout in macOS
2. Start VSCode
3. Zoom in with cmd+= hotkey (maps to cmd+ì in Italian), see it works
4. Zoom out with cmd+- hotkey (maps to cmd+' in Italian), see it doesn't works

**Comment by alexandrudima** [comment]
I have validated that we now (i.e. after PR #22894 aka #17521 -- in today's upcoming Insiders build) appear to behave correctly for this keyboard layout

![image](https://cloud.githubusercontent.com/assets/5047891/24287784/50813c8c-107b-11e7-8aee-6e299cc0774e.png)

---
### Analysis of default keybinding for `workbench.action.zoomIn`
* `workbench.action.zoomIn` is bound by default to the following three key code binding `` cmd+= ``, `` cmd+shift+= `` and `` cmd+numpad_add ``
* `` = `` can be produced through one scan code combination: `` Shift+[Digit0] ``. i.e.
![image](https://cloud.githubusercontent.com/assets/5047891/24287993/06f4b46c-107c-11e7-82f9-f17b82182fdc.png)
* `` shift+=`` or `` + `` can be produced through one scan code: `` [BracketRight] ``. i.e.
![image](https://cloud.githubusercontent.com/assets/5047891/24287879/a98f7c1c-107b-11e7-8288-d143f758aadf.png)
* `` numpad_add `` is mapped transparently to the scan code `` [NumpadAdd] ``. i.e.
![image](https://cloud.githubusercontent.com/assets/5047891/24288168/a4e8b678-107c-11e7-98b4-57b30d77ca7b.png)
* therefore, the action is bound by default to: ``Shift+Cmd+[Digit0] ``, `` Cmd+[BracketRight] `` and `` Cmd+[NumpadAdd] ``
* This might be unfortunate, but correct. We don't ship with keyboard layout specific default keybindings, that is something you can upvote in #1240

---
### Analysis of default keybinding for `workbench.action.zoomOut`
* `workbench.action.zoomOut` is bound by default to the following three key code binding `` cmd+- ``, `` cmd+shift+- `` and `` cmd+numpad_subtract ``
* `` - `` can be produced through one scan code: ``[Slash] ``. 
* `` shift+-`` or `` _ `` can be produced through one scan code combination: `` Shift+[Slash] ``. i.e.
![image](https://cloud.githubusercontent.com/assets/5047891/24288290/13ccb18e-107d-11e7-88d0-2346bd4a6969.png)
* `` numpad_subtract `` is mapped transparently to the scan code `` [NumpadSubtract] ``. i.e.
![image](https://cloud.githubusercontent.com/assets/5047891/24288330/3b9229f6-107d-11e7-96a5-c245709b61e3.png)
* therefore, the action is bound by default to: ``Cmd+[Slash] ``, `` Shift+Cmd+[Slash] `` and `` Cmd+[NumpadSubtract] ``
---
All in all:
![screen shot 2017-03-24 at 10 33 40](https://cloud.githubusercontent.com/assets/5047891/24288364/67c55a16-107d-11e7-8942-e6c66e413ff1.png)
![screen shot 2017-03-24 at 10 37 11](https://cloud.githubusercontent.com/assets/5047891/24288489/dfff511c-107d-11e7-8b84-f54f55caf8f3.png)

---

---
This makes me believe the fix in PR #22894 aka #17521 resolves this issue.

**Comment by lorthirk** [comment]
Yes, absoluetly. I just tried Insiders build and I can confirm the issue is fixed.
