### ISSUE TITLE
Reinstalling vsix extension fails on overlayfs

### ISSUE THREAD

**Issue by joshheinrichs-shopify** [microsoft/vscode#176571]
As of 1.76.0, when trying to reinstall a vsix extension via the cli when the existing extension is on a lower overlayfs layer we see this:
```console
% /usr/share/code/bin/code --extensions-dir=/path/to/extension/dir --install-extension=<extension>.vsix --verbose
...
TRACE Deleting existing extension from disk <extension> <extension_dir>/<extension>
  ERR Error while installing the extension: <extension>
Please restart VS Code before reinstalling <extension>.
Failed Installing Extensions: file:///path/to/<extension>.vsix
```

Looks like this is due to https://github.com/microsoft/vscode/blob/745aa79d73e203211ba8ae24c16d7fb796eec448/src/vs/platform/extensionManagement/node/extensionManagementService.ts#L535 from https://github.com/microsoft/vscode/pull/173484

stracing the above command we can see where things go wrong
```console
[pid 15661] write(1, "TRACE Deleting existing extensio"..., 136) = 136
TRACE Deleting existing extension from disk <extension> /path/to/extension/dir/<extension>
...
[pid 15671] rename("/path/to/extension/dir/<extension>", "/path/to/extension/dir/.19c0cbb2-2f34-4a2f-a14c-0753f245e322" <unfinished ...>
[pid 15661] read(9, "\1\0\0\0\0\0\0\0", 1024) = 8
[pid 15671] <... rename resumed>)       = -1 EXDEV (Invalid cross-device link) 
```

[From the kernel docs](https://www.kernel.org/doc/Documentation/filesystems/overlayfs.txt#:~:text=Enabled%20with%20the%20mount%20option%20or%20module%20option%3A%20%22redirect_dir%3Don%22%20or%20with%0Athe%20kernel%20config%20option%20CONFIG_OVERLAY_FS_REDIRECT_DIR%3Dy.%0A%0AIf%20this%20feature%20is%20disabled%2C%20then%20rename(2)%20on%20a%20lower%20or%20merged%20directory%0Awill%20fail%20with%20EXDEV%20(%22Invalid%20cross%2Ddevice%20link%22).) it sounds like `rename` isn't necessarily supported by overlayfs unless `redirect_dir` is enabled 

>1) "redirect_dir"
>
>Enabled with the mount option or module option: "redirect_dir=on" or with
>the kernel config option CONFIG_OVERLAY_FS_REDIRECT_DIR=y.
>
>If this feature is disabled, then rename(2) on a lower or merged directory
>will fail with EXDEV ("Invalid cross-device link").

**Comment by sandy081** [comment]
> As of 1.76.0, when trying to reinstall a vsix extension via the cli when the existing extension is on a lower overlayfs layer we see this:

Are you saying this was working before?

**Comment by joshheinrichs-shopify** [comment]
Yeah, previously old extension directories were just deleted, not renamed and deleted.

**Comment by joshheinrichs-shopify** [comment]
For what it's worth I can rename directories on lower overlayfs layers in vscode's file explorer, so maybe the logic handling renaming in there could be reused?

**Comment by sandy081** [comment]
> Yeah, it looks like previously extension directories were just deleted, not renamed and deleted.

That's right. We do not want to delete directly because it is causing partial removals and thereby causing issues. I am wondering if it is possible to enable rename?

**Comment by joshheinrichs-shopify** [comment]
Yeah we ended up adjusting our mount options. `redirect_dir` isn't necessarily supported by older kernels / containers, but that's probably a pretty niche case.
