### ISSUE TITLE
Extension Host Keeps Crashing

### ISSUE THREAD

**Issue by bmonish** [microsoft/vscode#176584]
Type: <b>Bug</b>

I was just editing a bunch of JS files and the extension hosts keeps shutting down.

VS Code version: Code 1.76.0 (92da9481c0904c6adfe372c12da3b7748d74bdcb, 2023-03-01T10:22:44.506Z)
OS version: Windows_NT x64 10.0.22623
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.88GB (4.35GB free)|
|Process Argv|. --crash-reporter-id 6a4defd4-67c5-40f8-bcfc-1064f94b07eb|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (54)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-sqlite|ale|0.14.1
arepl|alm|2.0.5
icons-carbon|ant|0.2.6
markdown-emoji|bie|0.3.0
path-intellisense|chr|2.8.4
vscode-eslint|dba|2.4.0
es7-react-js-snippets|dsz|4.4.3
gitlens|eam|13.3.2
react-native-react-redux|EQu|2.0.6
vsc-material-theme|Equ|33.6.0
vsc-material-theme-icons|equ|2.6.1
prettier-vscode|esb|9.10.4
auto-rename-tag|for|0.1.10
code-runner|for|0.12.0
copilot|Git|1.77.9225
remotehub|Git|0.52.0
vscode-pull-request-github|Git|0.60.0
live-sass|gle|6.0.3
rest-client|hum|0.25.1
kite|kit|0.147.0
graphql-for-vscode|kum|1.15.3
vscode-language-babel|mgm|0.0.37
isort|ms-|2022.8.0
python|ms-|2023.4.0
vscode-pylance|ms-|2023.3.10
remote-wsl|ms-|0.76.1
cpptools|ms-|1.14.4
remote-repositories|ms-|0.30.0
vscode-typescript-next|ms-|5.1.20230307
vsliveshare|ms-|1.0.5834
vscode-react-native|msj|1.10.2
emoji|Per|1.0.1
material-icon-theme|PKi|4.24.0
vscode-css-peek|pra|4.2.0
fabric8-analytics|red|0.3.6
java|red|1.15.0
vscode-xml|red|0.24.0
LiveServer|rit|5.7.9
stepsize|Ste|1.0.13
intellicode-api-usage-examples|Vis|0.2.7
vscodeintellicode|Vis|1.2.30
vscode-boot-dev-pack|vmw|0.2.1
vscode-spring-boot|vmw|1.44.0
vscode-java-debug|vsc|0.49.0
vscode-java-dependency|vsc|0.21.1
vscode-java-pack|vsc|0.25.8
vscode-java-test|vsc|0.38.1
vscode-maven|vsc|0.40.4
vscode-spring-boot-dashboard|vsc|0.11.1
vscode-spring-initializr|vsc|0.11.2
vscode-wakatime|Wak|24.0.7
vscode-todo-highlight|way|1.0.5
vscode-import-cost|wix|3.3.0
material-theme|zhu|3.15.6

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vscaat:30438848
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
pynewext54:30681850
azure-dev_surveyone:30548225
pyindex848:30662994
nodejswelcome1:30587005
282f8724:30602487
pyind779:30671433
89544117:30613380
pythonsymbol12:30671437
vsccsb:30677849
pythonb192:30669360

```

</details>

**Comment by harold-sn** [comment]
I just had the same problem when editing python code, also using GitHub Copilot extension (1.77.9225); I have reverted to the previous version of the GitHub Copilot extension (1.76.9071) and the problem no longer occurs.

**Comment by bmonish** [comment]
For me it was Kite and Stepsize. After I uninstalled both of them it worked!
