### ISSUE TITLE
Argument 'locale' is not working on 1.76.0 and insiders

### ISSUE THREAD

**Issue by EzioLi01** [microsoft/vscode#176532]
Hey expert, I'm project owner for [microsoft/vscode-react-native](https://github.com/microsoft/vscode-react-native), we're using vscode-test for the extension localization testing. The test is running in latest stable version of vscode as below. 

`runTests({
            extensionDevelopmentPath,
            extensionTestsPath,
            launchArgs: ["--locale", "zh-cn"],
            version: "stable",
        });`

Recently we found our locale tests is failed in pipeline, after investigation, the test is working well on vscode 1.75.0, but failed both on 1.76.0 and insiders.

Not sure if it have some changes on module or vscode, can anyone guide me on this? Thanks!

**Comment by connor4312** [comment]
@TylerLeonhardt did anything change regarding this CLI argument during the last release?

**Comment by TylerLeonhardt** [comment]
I have reverted that changes that changed this behavior... this should be fixed now with: https://github.com/microsoft/vscode/pull/177426
