### ISSUE TITLE
Add context menu in vscode extension

### ISSUE THREAD

**Issue by Anastasiia-Yukhno** [microsoft/vscode#176516]
It's suggestion to add the ability to add context menu item to search results in the **_search bar_**.

There is no configuration for this section in the [official documentation](https://code.visualstudio.com/api/references/contribution-points#contributes.menus). 
![image](https://user-images.githubusercontent.com/85406971/223730604-64e926b0-8d61-4cd1-8f54-c24bab128073.png)

Is it possible to add this context menu?

**Comment by roblourens** [comment]
https://github.com/microsoft/vscode/issues/107996
