### ISSUE TITLE
Message box is cramped

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode#17652]
- VSCode Version: Code - Insiders 1.9.0-insider (04f541160e0d41be95df9a964b1b570aec549157, 2016-12-20T07:05:16.928Z)
- OS Version: Darwin x64 15.6.0
- Extensions:

|Extension|Author|Version|
|---|---|---|
|vscode-eslint|dbaeumer|1.2.2|
|debugger-for-chrome|msjsdiag|2.4.1|
|vetur|octref|0.1.2|
|language-stylus|sysoev|1.6.0|
|vim|vscodevim|0.4.9|

---

At half screen size:

![image](https://cloud.githubusercontent.com/assets/4033249/21383260/c45f155e-c79f-11e6-88b9-a3c315aa6ad3.png)

**Comment by bpasero** [comment]
Let's move into https://github.com/Microsoft/vscode/issues/5454
