### ISSUE TITLE
[Bug] Error spam in the console when hovering the command palette

### ISSUE THREAD

**Issue by CGNonofr** [microsoft/vscode#176533]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: vscode.dev 1.76.0

Steps to Reproduce:

1. Open the browser devtools
2. Open the command palette
3. Hover the items
4. There is a lot of errors in the console:
![image](https://user-images.githubusercontent.com/23257479/223785850-ec48efeb-835c-46df-8d57-ea04030f3027.png)

**Comment by TylerLeonhardt** [comment]
I'm not seeing this anymore... Can you confirm @CGNonofr?

**Comment by TylerLeonhardt** [comment]
Actually I can repro this only in vscode.dev and not insiders.vscode.dev... odd
