### ISSUE TITLE
Enable inline suggestions in the SCM input

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#176565]
Tracks enabling inline suggestions in the scm input widget. This would allow copilot to suggest commit messages:

https://github.com/community/community/discussions/19564
https://github.com/community/community/discussions/13110
https://github.com/community/community/discussions/45800
https://github.com/community/community/discussions/48690

**Comment by hediet** [comment]
Copilot could actually try to read the staged git files to suggest a clever message

**Comment by hackf5** [comment]
![image](https://user-images.githubusercontent.com/48881437/224667176-58f8fdc0-9151-4f96-8dae-437602d951b6.png)
 How do I disable this?
