### ISSUE TITLE
Allow modal dialog to show on focus (don't show when window is inactive)

### ISSUE THREAD

**Issue by emchristiansen** [microsoft/vscode#176542]
First, thanks for VSCode - it's by far my favorite code editor!

# The problem
I use multiple VSCode windows, all connected to the same remote host, each dedicated to a different task.
When I lose connection to my dev remote host, all these windows pop up and steal focus, complaining that they've lost the connection.
If I'm on a different MacOS Desktop when I lose the connection, the VSCode app in my Dock starts to bounce and doesn't stop until I click on it.

I find this all very annoying.
It's even more annoying because I mostly work from my laptop at various cafes, etc, with intermittent internet access, so I'm constantly getting these pop-ups.

Also, focus-stealing in this context defies logic.
I.e. if I'm _not_ using VSCode, then I don't care that I lost the connection, so no notification is needed.
If I _am_ using VSCode, then you don't need to steal focus to tell me that I've lost the connection.
In neither case does focus-stealing help.

# Proposed solution
Please add an option to blanket-disable all focus-stealing in VSCode.
This should also prevent the Dock icon from bouncing.

Thanks!

**Comment by sbatten** [comment]
@bpasero @alexdima I'm not doing anything special from the dialog side that I am aware of to cause this to happen. Are either of you aware of us intentionally causing the windows to demand attention?

**Comment by bpasero** [comment]
Can you debug who is calling to focus?

**Comment by sbatten** [comment]
perhaps OP can, I did not reproduce this issue. I opened several windows with codespaces and focused a local window and then disconnected my wifi. The local window remained focus with no visual noise or focus stealing

**Comment by sbatten** [comment]
@emchristiansen what type of remote are you using?

**Comment by emchristiansen** [comment]
Thanks for the quick response y'all.
I've replicated the experience, with screenshots, so you can see what happened.
Note there are blacked-out bits in the last screenshot - I've got some work stuff open and don't think I can share it.

FYI I'm using an SSH remote host into a Linux VM on AWS.

# Issue replication (with screenshots)

First, I go to Desktop 6 and minimize all my VSCode windows except for one.
I swiped up with 4 fingers to enter Mission Control so you can see the state.
Note the minimized VSCode instances in the red box in the lower right:

<img width="1728" alt="Screenshot 2023-03-09 at 9 34 34 AM" src="https://user-images.githubusercontent.com/225668/224078317-b290900b-757c-4776-8ece-798d86b88fed.png">

Now I go to Desktop 7 and stop the remote host on AWS.
(Note, I just tried to reproduce via turning off the Wifi, but it didn't immediately work - I think maybe there's a timeout.)

<img width="1728" alt="Screenshot 2023-03-09 at 9 37 29 AM" src="https://user-images.githubusercontent.com/225668/224078758-689e48a4-ce65-4234-94a0-3d027eb64792.png">

Within a few seconds, the VSCode icon starts to bounce on the Dock - note the red box:

<img width="1728" alt="Screenshot 2023-03-09 at 9 38 09 AM" src="https://user-images.githubusercontent.com/225668/224078941-984a9a11-dd5a-4acb-9cba-9145ce46e9cc.png">

Now I switch from Desktop 7 back to Desktop 6.
Note that all the windows I previously minimized have brought themselves into the foreground:

<img width="1728" alt="Screenshot 2023-03-09 at 9 38 38 AM" src="https://user-images.githubusercontent.com/225668/224079357-deb01a98-b988-4441-92e3-022b5aabf557.png">

It is _not possible_ to minimize the windows.
I must either reconnect to the remote instance or click "Cancel", which drops all my state.
Practically, this means I'm keeping foreground windows cluttering up my Desktop until I re-establish the connection.

**Comment by sbatten** [comment]
Ah I see, this isn't the reconnection progress dialog but the final alert dialog. @emchristiansen at least one interim workaround I can suggest though it may not be preferred, is to enable custom dialogs with `"window.dialogStyle": "custom"` This will make that final dialog use an html element which is much less intrusive. You may not prefer this however as the setting replaces all dialogs in vs code with this.

@bpasero maybe we should wait until windows have focus to pop up a message dialog?

**Comment by bpasero** [comment]
Is that clever though? What if user is in a setup where simply multiple apps are showing on a large monitor, wouldnt it be weird to hide the dialog until you focus the window?

**Comment by emchristiansen** [comment]
> Ah I see, this isn't the reconnection progress dialog but the final alert dialog. @emchristiansen at least one interim workaround I can suggest though it may not be preferred, is to enable custom dialogs with `"window.dialogStyle": "custom"` This will make that final dialog use an html element which is much less intrusive. You may not prefer this however as the setting replaces all dialogs in vs code with this.
> 
> @bpasero maybe we should wait until windows have focus to pop up a message dialog?

Thanks, I'll try that.

**Comment by emchristiansen** [comment]
> > Ah I see, this isn't the reconnection progress dialog but the final alert dialog. @emchristiansen at least one interim workaround I can suggest though it may not be preferred, is to enable custom dialogs with `"window.dialogStyle": "custom"` This will make that final dialog use an html element which is much less intrusive. You may not prefer this however as the setting replaces all dialogs in vs code with this.
> > @bpasero maybe we should wait until windows have focus to pop up a message dialog?
> 
> Thanks, I'll try that.

So far, so good - I haven't experienced any of that annoying behavior!

**Comment by sbatten** [comment]
@bpasero even in that case, the user doesn't really need to act immediately on the reconnection. without the window focused, they are essentially in readonly mode. the reconnection dialog is meant to prevent users from feeling like they can make edits safely when they won't be sync'd to the remote. In this case, without window focus, we are protected from that mistake. At least that's my argument for this behavior.

**Comment by jmusiel** [comment]
This should really be changed.
