### ISSUE TITLE
Allow proposed API `contribEditorContentMenu` usage from python extension

### ISSUE THREAD

**Issue by karthiknadig** [microsoft/vscode#176547]
Changes required:
* update distro to `87f5dc260a1c22f39604fc9e5382dac71335cff5`

**Comment by karrtikr** [comment]
@karthiknadig I think you forgot to close it?

**Comment by karthiknadig** [comment]
Verification steps:
Same as this https://github.com/microsoft/vscode-python/issues/20812#issuecomment-1476497404
If https://github.com/microsoft/vscode-python/issues/20812 is verified then this is verified and vice versa,
