### ISSUE TITLE
Tag HTML with style attribute

### ISSUE THREAD

**Issue by salcam** [Microsoft/vscode#17659]
- VSCode Version: Code 1.8.1 (ee428b0eead68bf0fb99ab5fdc4439be227b6281, 2016-12-19T14:42:49.304Z)
- OS Version: Darwin x64 16.3.0
- Extensions:

|Extension|Author|Version|
|---|---|---|
|angular-material-snippets|4tron|0.3.1|
|crane|HvyIndustries|0.2.2|
|format-indent|Kasik96|1.3.0|
|Bookmarks|alefragnani|0.10.1|
|python|donjayamanne|0.5.5|
|php-debug|felixfbecker|1.10.0|
|Angular1|johnpapa|0.1.16|
|Material-theme|zhuangtongfa|1.0.3|

---

Steps to Reproduce:

1. create tag html with attribute style
2. Format code

The code is unformatted after this tag.

**Comment by egamma** [comment]
duplicates #17637
