### ISSUE TITLE
ctrl+shift+b sometimes doesn't run default build task in this repo

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode#176536]
1. open a clone of `microsoft/vscode`
2. ctrl+shift+b
3. :bug: shortcut resolves to `workbench.actions.tasks.build` but instead of running the default task I get a quickpick asking me to choose a task to run
<img width="1620" alt="image" src="https://user-images.githubusercontent.com/30305945/223794836-0988b071-ce8c-46f0-8f1c-6a72cbfae1ec.png">

This doesn't always repro (window reload fixed it this time), but I have seen this every 2 weeks or so hence filing an issue.

**Comment by gjsjohnmurray** [comment]
Sounds like #173184

**Comment by joyceerhl** [comment]
Thanks @gjsjohnmurray, this is indeed a duplicate.
