### ISSUE TITLE
PHP open tag in red color when not closed

### ISSUE THREAD

**Issue by Firiks** [microsoft/vscode#176535]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.76.0
- OS Version: Windows 10 x64

Steps to Reproduce:

1. All php files have opening < in red when not using ?>, I tested it also with all extensions disabled but issue still persists

![img](https://user-images.githubusercontent.com/23382187/223791567-76d4efa8-1bd2-4f9f-903c-a5ccffa6318a.png)

**Comment by RedCMD** [comment]
https://github.com/microsoft/vscode/issues/176329
https://github.com/microsoft/vscode/issues/176310
https://github.com/microsoft/vscode/issues/175797

**Comment by roblourens** [comment]
I don't see this, please include a full file that demonstrates the issue
