### ISSUE TITLE
Indicate click target when invoking editor line number context menu

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode#176557]
In our tree and list widgets as well as in our editor breadcrumbs, we visually distinguish between:
1. the active element
2. the element that's being hovered
3. the element that a context menu was invoked for via right click (and maybe ctrl+click on mac)

https://user-images.githubusercontent.com/30305945/223830415-8a1ad289-de38-4f63-bed7-e2a463b5d613.mp4

https://user-images.githubusercontent.com/30305945/223830445-fdb2de6d-3d7f-4705-b4f3-483071784d11.mp4

We now have a context menu for editor line numbers, but the editor line number only reflects where the cursor currently is, so:
1. there is no highlight when you hover over an editor line number which is different than the one relating to the editor selection
2. there is no focus indicator when you right click on an editor line number

This makes it difficult to visually verify which line number you are right clicking on, e.g. if you are trying to copy a link.

**Comment by joyceerhl** [comment]
Kai had the suggestion that we should select the whole line corresponding to the line number context menu target to reduce ambiguity about which line is going to be selected. This does align with what happens on github.com and is not a breaking change since we never enabled right click context menus on the line number in the first place. Looping in @daviddossett for UX and @hediet for editor feedback

**Comment by joyceerhl** [comment]
Explored this, seems pretty reasonable and does address the problem of ambiguous context, the only thing I'm wondering about is whether it also makes sense to have this selection behavior when right clicking in the editor gutter, as it would be a behavior change for the debug/test context menus, and it would not preserve your in-editor selection (which could be bad if the user has multiple selections going). Any feedback @connor4312?

https://user-images.githubusercontent.com/30305945/224114877-748d007f-f7dc-4848-a897-a1cdb918ed48.mp4

**Comment by connor4312** [comment]
Hm, I'm honestly not a fan of selecting the line when right clicking on test decorations or working with breakpoints. In both cases you aren't "switching contexts" away from what you were doing, and selecting the line is never going to be a desired outcome of right-clicking a gutter

**Comment by joyceerhl** [comment]
Yea maybe we have this selection behavior only for a right click on the line number specifically then.

**Comment by eleanorjboyd** [comment]
To clarify how to test this you just right-click in the gutter and an option should pull up which says : `copy vscode id"? Is this in vscode desktop and are there parameters on which types of files it works for?

**Comment by joyceerhl** [comment]
Steps:
1. Right click on a line number with no existing selection in the editor
2. Verify that the target line is selected
3. Have an existing selection in the editor (test both single line and multiple line selections)
4. Verify that the selection changes appropriately when right clicking on a line number

**Comment by eleanorjboyd** [comment]
seeing this on two different file types:

https://user-images.githubusercontent.com/26030610/226709492-25f50a63-b5f4-4ede-a92a-89b486f25d9c.mov

**Comment by joyceerhl** [comment]
@eleanorjboyd are you pointing out that there's a context menu for .py but not .json? That is by design since you cannot set breakpoints in a json file so none of your available actions apply to the .json file. The active selection seems to be changing correctly based on your mp4 (which is the scope for this issue).

**Comment by eleanorjboyd** [comment]
Is it supposed to have a related context menu or am I supposed to see the "open in vscode.dev" menu item come up for a json like it did in yours? If that looks correct then I just misunderstood the issue I was verifying. Sorry!

**Comment by joyceerhl** [comment]
You'll only see the Copy vscode.dev link action in a GitHub repo. There are other actions if you install the GitHub Pull Requests extension for copying GitHub links. If this is a GitHub repo then that's a bug.
