### ISSUE TITLE
terminal processes not killed on exit and new one created at startup

### ISSUE THREAD

**Issue by ejkreboot** [microsoft/vscode#176583]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.76.0 (Universal)
- OS Version: MacOS 12.6.3

Steps to Reproduce:

1. Start VS Code
2. Open a terminal window via Terminal --> New Terminal
3. Enter `ps` and note the number of zsh processes.
4. Quit VS Code
5. Reopen VS Code.
6. Type `ps` and note previous zsh process was not killed, and there is now one more zsh process than there was when you quit VS Code previously.

Note that as a side effect, processes (such as development servers) that were started in the terminal session are not killed when quitting VS Code and will continue running--which in at least some cases is not desirable.

**Comment by rsodre** [comment]
I noticed this started happening in the past week.
Same OS / VS Code versions
