### ISSUE TITLE
[jade] Incorrect highlighting in strings with inline tags

### ISSUE THREAD

**Issue by mrmlnc** [Microsoft/vscode#1765]
**VS Code version**:
0.10.6

**Code**:
```jade
p #[code samp] — Regular text. #[samp This is sample text] more text.
```

**Description**:
If you try to write a dot in a inline tag (tag Interpolation), text highlighting changes.

**Gif:**
![2016-01-04_15-44-32](https://cloud.githubusercontent.com/assets/7034281/12089842/1cc9f378-b2fa-11e5-8645-2928e9938e16.gif)

**Comment by aeschli** [comment]
This issue was moved to davidrios/jade-tmbundle#67

**Comment by mrmlnc** [comment]
@aeschli, as I understand it, this issue is related to the bug in [vscode-textmate](https://github.com/Microsoft/vscode-textmate)?

I ask this because I can fix Jade tmLanguage in VS Code. Does it make sense to do it?

**Comment by mrmlnc** [comment]
@aeschli, you can see demo extension in VS Code 1.5.0

https://github.com/mrmlnc/vscode-jade-syntax

**Comment by aeschli** [comment]
We should fix that in https://github.com/Microsoft/vscode-textmate

**Comment by aeschli** [comment]
This issue was moved to Microsoft/vscode-textmate#22

**Comment by ramya-rao-a** [comment]
Moving to next milestone, as this cannot be verified at the moment

**Comment by Tyriar** [comment]
Removing bug to get it out of the verification queue
