### ISSUE TITLE
[loc][query][VSCode] Please clarify localizability

### ISSUE THREAD

**Issue by mkyjakova** [Microsoft/vscode#17665]
Hi, we have a question from our translator. Can you help please? Thanks!

Source:
Controls if turning on Zen Mode also puts the workbench into full screen mode.
Hot Exit is now enabled by default
Hot Exit remembers any unsaved files between sessions, so you don't have to save your files before you exit. You can disable this feature with the 'files.hotExit' setting.

File Name:
src\vs\workbench\electron-browser\main.contribution.nls.resx
src\vs\workbench\services\textfile\electron-browser\textFileService.nls.resx
src\vs\workbench\services\textfile\electron-browser\textFileService.nls.resx

Resource ID:
".resx", 0; "fullScreenZenMode"
".resx", 0; "hotExitEducationalMessage"
".resx", 0; "hotExitEducationalDetail"

Query:
Zen Mode and Hot Exit seem to be new features for VSO. Can you please let us know whether their names are translatable or not? I've only seen "hot exit" in lowercase on your page (https://code.visualstudio.com/blogs/2016/11/30/hot-exit-in-insiders)

**Comment by egamma** [comment]
>Zen Mode and Hot Exit seem to be new features for VSO

This is correct.

> Can you please let us know whether their names are translatable or not?

Zen Mode - recommend to not translate Zen Mode (which also stands for 'distraction free mode'

Hot Exit - recommend to not translate
