### ISSUE TITLE
macOS: Support proxy icon in custom title bar

### ISSUE THREAD

**Issue by ivancuric** [microsoft/vscode#17664]
I love the new dark titlebar, but since the only way to move files in the explorer tab was via the proxy icon I kinda miss the functionality now. Is there any way to bring back the behaviour or improvise it some other way?

- VSCode Version: 1.8.1
- OS Version: MacOS Sierra

**Comment by bpasero** [comment]
@ivancuric can you be more specific what a "proxy icon" is?

**Comment by ivancuric** [comment]
https://developer.apple.com/library/content/documentation/UserExperience/Conceptual/OSXHIGuidelines/Art/document_window_parts_2x.png

**Comment by bpasero** [comment]
Thanks. I think we need proper API from upstream electron to get this right. Meanwhile to get back to the native title bar, you can configure `"window.titleBarStyle": "native"`

**Comment by RikkiGibson** [comment]
Thanks for the tip about `"window.titleBarStyle": "native"`. I frequently run files by dragging them to the terminal, so it would be great to have this with the new default title bar at some point.

**Comment by jrz** [comment]
I get a proxy icon in the september release when setting: "window.nativeTabs": true

**Comment by ivancuric** [comment]
![image](https://user-images.githubusercontent.com/2827047/31879815-de6b888a-b7de-11e7-8c49-8cef54249cc4.png)
Not working here.

**Comment by jrz** [comment]
I see the proxy icon in your titlebar left of settings.json.

But it doesn't behave like normal.
Rightclicking works (path list)
Dragging is not possible.



Ahhhh this issue is for proxy icons in the custom titlebar
