### ISSUE TITLE
"Show or focus hover" possibly breaking behaviour

### ISSUE THREAD

**Issue by ulugbekna** [microsoft/vscode#176640]
Triggering the new "show or focus hover" (`editor.action.showHover`) twice will first show the hover and then switch focus to it. 

I am afraid such new behaviour may break existing extensions and users' workflows. 

Just to take as an example, one of the feature requests for the OCaml extension is on each subsequent hover at the same position, show a different hover with the type of the symbol expanded (basically, unwrapping type aliases). 

I feel since `editor.action.showHover` is such a fundamental and long-existing command, it may be better to not alter its behaviour. 

What do people think?

**Comment by aiday-mar** [comment]
Hey thanks for taking interest in the editor-hover. In order to better understand the breakage, would it be possible to have a link to the feature request for the OCaml extension? It would help to better understand the problem.

**Comment by ulugbekna** [comment]
Let me outline the problem in more detail because reading the ocaml issue wouldn't help without more context: 

In short, my proposal: triggering `editor.action.showHover` remains stateless, i.e., the behaviour of this command should not depend on the number of times it has been triggered. It should every time just ask hoverProviders for what to display on the hover. Moving focus to the hover widget should be a separate command. 

In more detail of the OCaml case: 

A user can trigger hover twice on the same cursor position and get different type shown in the hover: 

A user triggers hover using `cmd+k cmd+I` on a symbol `foo`, they see hover with the type of the symbol, e.g., `module M`. That's not a helpful type, so they press `cmd+k cmd+I` once again without moving the cursor and the language server this time serves 

```ocaml
module M : sig 
  val fib : x -> x 
end
```

to show in the hover. 

Does this help? 

----

It's not OCaml-only issue, of course. There may be others who depend on the old behaviour.

**Comment by aiday-mar** [comment]
I see, thank you for the details. It makes sense. This change is easy to do. Wondering what @alexdima and @jrieken think about it?

**Comment by ulugbekna** [comment]
thanks! maybe we could have a separate command (with kb `cmd+option+k cmd+I` ?) that would either bring focus to existing hover or show hover and bring focus to it

**Comment by alexdima** [comment]
> A user can trigger hover twice on the same cursor position and get different type shown in the hover

I disagree. IMHO returning different results from a hover provider based on if a request was already made for the same document and the same position would cause much more problems. For example, when moving the mouse and stopping for some time at a position, we end up making a request; then, if the user moves the mouse again, we could cancel that request; then, if the mouse moves back, we could make the same request again, etc. Getting different results based on subtle mouse movements would be IMHO a very annoying feature and would part ways with the LSP.

I think perhaps users want that the hover providers can be invoked in two modes: default (current) or verbose. Once a hover is rendered, it could have an action to refetch with more detail if the provider supports that; this could also be implemented as an argument to `editor.action.showHover`, so users which want to bind that directly have a chance to do so, etc.
