### ISSUE TITLE
Switching terminal tabs does not set the focus on the terminal line

### ISSUE THREAD

**Issue by esonnino** [microsoft/vscode#176696]
https://user-images.githubusercontent.com/113370447/224167230-e8ded457-0771-4aa8-bb48-a3bf4a102b41.mp4

When switching terminal tabs, I would expect the focus to go to the terminal line so I can type right away.
Now the focus is nowhere :)

@Tyriar 
@daviddossett

**Comment by gjsjohnmurray** [comment]
Try `"terminal.integrated.tabs.focusMode": "singleClick"`

**Comment by esonnino** [comment]
Thanks @gjsjohnmurray !

Would it make sense to make this the default? Is there security concerns?

**Comment by Tyriar** [comment]
It's not the default because they behave like a list everywhere and there are accessibility problems with singleClick.
