### ISSUE TITLE
Allow variables to be displayed in a different base during debugging

### ISSUE THREAD

**Issue by adelphes** [Microsoft/vscode#17668]
Integer variables are always displayed in decimal format in Locals, Watches and on hover.

It would be nice to have a context menu option to allow the values to be displayed in binary, octal or hexadecimal format, perhaps with a "debug.displayBase" option for a default configuration value.

**Comment by egamma** [comment]
fyi @weinand

**Comment by weinand** [comment]
duplicate of #28025
