### ISSUE TITLE
keybindings.json linter showing spurious warnings

### ISSUE THREAD

**Issue by ulugbekna** [microsoft/vscode#176629]
Does this issue occur when all extensions are disabled?: Yes/No

`keybindings.json` linter is showing incorrect/spurious listing: 

- `args` is optional, so we shouldn't show this? 

<img width="648" alt="image" src="https://user-images.githubusercontent.com/16353531/224015652-7da158fa-aa2b-4b5b-93ae-d6ee91710c5f.png">

- don't make sense:

<img width="683" alt="image" src="https://user-images.githubusercontent.com/16353531/224015786-edaf6888-064a-42da-b292-ecf8761d0ecc.png">

<img width="726" alt="image" src="https://user-images.githubusercontent.com/16353531/224015834-b5ae2307-a894-43bd-abc6-3645c934fc7d.png"

Version: 1.77.0-insider (Universal)
Commit: 502ac5b213e373026527efdbcea4e669d930d9e1
Date: 2023-03-09T05:22:33.512Z
Electron: 19.1.11
Chromium: 102.0.5005.196
Node.js: 16.14.2
V8: 10.2.154.26-electron.0
OS: Darwin arm64 22.3.0
Sandboxed: Yes

**Comment by ulugbekna** [comment]
cc @aeschli

**Comment by aeschli** [comment]
When defining a command, it's also possible to provide a description and a schema for the arguments:
https://github.com/microsoft/vscode/blob/9ca779d59799d0aa335e771d413519c09e579256/src/vs/workbench/contrib/extensions/browser/extensions.contribution.ts#L287
Is an example.

These argument schemas are collected and included in the generated keybinding schema.

**Comment by mjbvz** [comment]
Still warns me about `kind`:

 
![Image](https://user-images.githubusercontent.com/12821956/226753212-c80bdb72-cd79-4e1c-a469-d392636d0849.png)


May be coming from the code actions commands so I'll take a look

**Comment by mjbvz** [comment]
@ulugbekna In my case, I hadn't added a `command` yet. Here's the keybinding I was using:

```json
{
	"key": "cmd+alt+i",
	"args": {}
},
```

**Comment by ulugbekna** [comment]
Oh, indeed, you're right, thanks!

**Comment by sandy081** [comment]
I am not seeing any warning / error for following. Is not the `command` property mandatory like `key` property?

<img width="404" alt="image" src="https://user-images.githubusercontent.com/10746682/226946843-64319248-53b1-4b60-aa19-0ec51873696b.png">

**Comment by bhavyaus** [comment]
> I am not seeing any warning / error for following. Is not the `command` property mandatory like `key` property?
> 
> <img alt="image" width="404" src="https://user-images.githubusercontent.com/10746682/226946843-64319248-53b1-4b60-aa19-0ec51873696b.png">

Verified the scenarios described above.  I'm not seeing a warning for empty command values but I expect one.
`
	{
		"key":"ctrl+q",
		"command":""
	}`

**Comment by rzhao271** [comment]
I'm thinking the empty command and no command scenarios can go into another issue together. I marked this one as verified.

**Comment by alexdima** [comment]
> @alexdima should know why "command" field in a keybinding is not mandatory.

The idea is that you can immediately unbind all commands bound to a key by using e.g. `{ "key": "cmd+f" }` and allow that it falls through to the default browser behavior. This is useful if there's a key combination needed for typing a character, but the key combination is bound by default (either by the core, or by an extension). e.g. https://github.com/microsoft/vscode/issues/14641 , https://github.com/microsoft/vscode/issues/106386 .
