### ISSUE TITLE
[loc][Query][VSCode] Please clarify the placeholders

### ISSUE THREAD

**Issue by mkyjakova** [Microsoft/vscode#17663]
Hi, we have a question from our translator. Can you help please? Thanks!

Source:
Showing {0} of {1} Settings

File Name:
src\vs\workbench\parts\preferences\browser\preferencesWidgets.nls.resx

Resource ID:
".resx", 0; "showCount"

Query:
{0} of {1} will be replaced with numbers? Thanks!	AL-PC5	12/14/2016 11:36:07 AM

**Comment by egamma** [comment]
yes the placeholders will be replaced with numbers, pls see the attached screenshot:

![image](https://cloud.githubusercontent.com/assets/172399/21393845/76cb26ec-c796-11e6-9abf-00c6820864fc.png)
