### ISSUE TITLE
Reloading without extensions disables color themes

### ISSUE THREAD

**Issue by kisasexypantera94** [microsoft/vscode#176637]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: Version: 1.76.0 (Universal)
Commit: 92da9481c0904c6adfe372c12da3b7748d74bdcb
Date: 2023-03-01T10:23:45.993Z
Electron: 19.1.11
Chromium: 102.0.5005.196
Node.js: 16.14.2
V8: 10.2.154.26-electron.0
OS: Darwin arm64 22.1.0
Sandboxed: No
- OS Version: 

Steps to Reproduce:

1. Just reload without extensions

Problem occurred after update to latest version

**Comment by aeschli** [comment]
Is the color theme part of an extension?

**Comment by kisasexypantera94** [comment]
Yes, and in fact this update seems to be more of a fix for the wrong behavior that was before (but which I was counting on 😄). It would be nice though to have an option of disabling everything except some of extensions (like color themes, vim). My case is disabling extensions when I need extra RAM during a build

**Comment by aeschli** [comment]
You could use a profile for that: https://code.visualstudio.com/docs/editor/profiles
-> create a profile that doesn't contain the 'expensive' extensions

The main use case for `Reloading without extensions` is to run VS Code in it's original form, so we can find out if an installed extension causes a problems you see.

Closing the issue as 'works as expected'
