### ISSUE TITLE
Cannot Debug React Code

### ISSUE THREAD

**Issue by allan-rosner** [microsoft/vscode#176649]
Type: <b>Bug</b>

Was able to debug react code up until yesterday. 

Process is
1) Start the development server with the command "BROWSER=CHROME PORT=3001 npm start"
2) Execute Run->Start Debugging
3) Chrome starts  and hangs

Run->Run Without Debugging works fine.

launch.json
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "type": "chrome",
            "request": "launch",
            "name": "Launch Chrome against localhost",
            "url": "http://localhost:3001/vertucciindustries",
            "webRoot": "${workspaceFolder}/src",
            "trace": true
        }
    ]
}

After I added the "trace": true attribute, I seee the following error in the VS Code Debug Console:

objc[15098]: Class WebSwapCGLLayer is implemented in both /System/Library/Frameworks/WebKit.framework/Versions/A/Frameworks/WebCore.framework/Versions/A/Frameworks/libANGLE-shared.dylib (0x7ffa567e33f0) and /Applications/Google Chrome.app/Contents/Frameworks/Google Chrome Framework.framework/Versions/111.0.5563.64/Libraries/libGLESv2.dylib (0x112b30850). One of the two will be used. Which one is undefined.

VS Code version: Code 1.76.0 (92da9481c0904c6adfe372c12da3b7748d74bdcb, 2023-03-01T10:23:45.993Z)
OS version: Darwin x64 22.3.0
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz (16 x 2300)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|4, 3, 3|
|Memory (System)|16.00GB (0.05GB free)|
|Process Argv|--crash-reporter-id c8ee3f37-2ca7-4941-bc80-8b75c89f3905|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
npm-intellisense|chr|1.4.4
copilot|Git|1.77.9225
ruby-rubocop|mis|0.8.6
vscode-docker|ms-|1.24.0
remote-containers|ms-|0.282.0
vscode-react-native|msj|1.10.2
ruby|reb|0.28.1
vscode-ruby|win|0.28.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
pynewext54:30681850
azure-dev_surveyone:30548225
vscccc:30610679
pyindex848:30662994
nodejswelcome1cf:30587006
2e4cg342:30602488
pyind779:30671433
f6dab269:30613381
pythonsymbol12:30671437
a9j8j154:30646983
vsctsb:30677850
pythonb192cf:30669361
pythonms35:30680984

```

</details>

**Comment by edvinv** [comment]
I have the same problem with angular application. It looks like the problem is new version of chrome 111. I downgraded chrome to previous version and it works fine. Probably connected with [this.](https://groups.google.com/g/chromedriver-users/c/xL5-13_qGaA?pli=1)

**Comment by chopin2256** [comment]
I think this is the same issue as [this](https://github.com/microsoft/vscode/issues/176690). It's completely broken and this took up 2 hours of my time since this happened out of nowhere.

I will have to use Firefox for now.

**Comment by connor4312** [comment]
See https://github.com/microsoft/vscode-js-debug/issues/1600#issuecomment-1461073532
