### ISSUE TITLE
showHover command is gone

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#176654]
I noticed that this command disappeared, which I have keybindings for. If you want to change the name I think it’s better to keep the old ID because it might be referenced in places and just change the name, or add a new command.

<img width="419" alt="image" src="https://user-images.githubusercontent.com/323878/224088047-96e1ffdd-48c0-41ad-8894-e1b1edd8cf49.png">

**Comment by aiday-mar** [comment]
Hi @roblourens, thanks for filing the issue. I changed today the id back to the old one: https://github.com/microsoft/vscode/pull/176633. Let me know if you continue seeing this issue after the new insiders build.
