### ISSUE TITLE
Chrome Debugger Hangs on Any Breakpoint, Even breakpoints that don't hit

### ISSUE THREAD

**Issue by chopin2256** [microsoft/vscode#176690]
Type: <b>Bug</b>

I'm using latest version of Chrome and NodeJS on Windows 10.

When I put a breakpoint anywhere in the source code, even breakpoints that never get hit, chrome hangs. Please note that the Firefox debugger does not exhibit this behavior. I even uninstalled and reinstalled Chrome to ensure it wasn't a corrupt browser issue.

This is my barebones setup that I tested on for your reference: [Node JS Barebones](https://github.com/chopin2256/nodejs_barebones)

### And here is a video

https://user-images.githubusercontent.com/5911283/224156465-ed87077e-089c-4d38-a9a1-fcd65e17dcca.mp4

VS Code version: Code 1.76.1 (5e805b79fcb6ba4c2d23712967df89a089da575b, 2023-03-08T16:32:00.131Z)
OS version: Windows_NT x64 10.0.19045
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 3800X 8-Core Processor              (16 x 3395)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.89GB (19.76GB free)|
|Process Argv|--crash-reporter-id fabd597e-7465-4a75-969f-01937aaa0b28|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-css-formatter|aes|1.0.2
classdiagram-ts|Ale|0.1.67
jsonviewer|cci|1.3.2
javascript-ejs-support|Dig|1.3.3
gitlens|eam|13.3.2
vscode-firefox-debug|fir|2.9.8
debug-visualizer|hed|2.4.0
hexeditor|ms-|1.9.11
js-debug-nightly|ms-|2022.12.1417
php-debug|xde|1.32.0

</details>

**Comment by rwollgar** [comment]
Also happens in vscode insiders.
Also happens when there are no breakpoints and breakpoint is set after chrome has started and loaded the app.
Any subsequent refresh hangs.
Using msedge 110.xxx works.

**Comment by connor4312** [comment]
See https://github.com/microsoft/vscode-js-debug/issues/1600#issuecomment-1461073532
