### ISSUE TITLE
Extensions details have "scroll to top" always visible

### ISSUE THREAD

**Issue by esonnino** [microsoft/vscode#176692]
![image](https://user-images.githubusercontent.com/113370447/224158267-d9e56a5a-b1ba-4ea6-9682-5a2b604c0abe.png)
![image](https://user-images.githubusercontent.com/113370447/224158487-84420e2a-bede-42f6-99d6-2506ac888256.png)

When reading through the details of an extensions, there's a button on the bottom right corner to scroll to top.
That Button should only be visible when the scroll viewer is scrolled down

**Comment by sandy081** [comment]
@mjbvz This is from markdown editor, is there way if this can be configurable?

**Comment by mjbvz** [comment]
@sandy081 This UI is actually from core and is part of our built-in extension readmes / release notes: https://github.com/microsoft/vscode/blob/5e26b3d7c31d690f19d6e83886a81d5943ab3b28/src/vs/workbench/contrib/extensions/browser/extensionEditor.ts#L872

**Comment by mjbvz** [comment]
Closing as this is a polish item that hasn't gotten any additional upvotes since it was opened. We'd still consider a PR if the change is simple enough but will not be prioritizing this ourselves
