### ISSUE TITLE
Performance issues when using several "code parsing" plugins

### ISSUE THREAD

**Issue by vfloyd6** [Microsoft/vscode#17661]
- VSCode Version:1.8.1
- OS Version:windows 7 Enterprise 64bits

Hello,

I have a big project with a lot of source code files and several languages used (c/c++, java, python).

I'm very interested in the autocomplete and code parsing features. I first tried to install the extension "C/C++" from Microsoft. It works great and the performances are good. You don't have to wait when ctrl clicking a symbol to go to the definition.

The problem comes when I try to install another language support. I've tried with "Language Support for Java(TM) by Red Hat". As soon as more than 1 extension is installed next to "c/c++", the performances become incredibly slow. 

From what I could see, the .db file created in the .vscode directoy grows more and more if you install more code parsing plugins. When I install only "C/c++", my DB file size is aroung 40MB. If I install Java support, it goes to 80MB and if I add the support for python it goes higher again. 

It looks that the slowdown is not related to the DB file size, but to the fact that more than 1 language support is enabled. 

Feel free to ask if you need more informations.

**Comment by egamma** [comment]
@vfloyd6 

>As soon as more than 1 extension is installed next to "c/c++", the performances become incredibly slow.

What exactly becomes slow? 
- Does autocomplete in C/C++  become slow 
- Does autocomplete in Java become slow?
- How does your folder look like? Does your folder include both Java and C++?

**Comment by vfloyd6** [comment]
The ctrl click on a symbol becomes very slow. When I have only c/c++ installed it takes less than 1second to jump to the definition. When I have more than 1 language support enabled it can take up to 10-15 seconds. I didn't test for the autocomplete but I guess this is the same since it is long to find the definition it should be even longer to find the related members/functions. I will confirm that later on. 

Yes my directory contains c/cpp/java/Python files.

**Comment by egamma** [comment]
@vfloyd6 thank you for clarifying. Still more questions:

>The ctrl click on a symbol becomes very slow. 

In what file types are you observing this slowness. In C++ only or in all languages?

While having the same folder open, Can you try to selectively disable an extension (in the extension viewlet (see below)  and narrow down who is the culprit for the slowness

![image](https://cloud.githubusercontent.com/assets/172399/21394044/40eeedb4-c797-11e6-961e-8cee5ff6857d.png)

**Comment by vfloyd6** [comment]
Hello,

I'm sorry but I can't reproduce the issue anymore ... I've tried to make the tests you asked but contrary to what I had yesterday, my .db file doesn't grow that much (max 40MB so that it could go u to 270MB yesterday) and the ctrl click is now reactive in all file types ...

**Comment by vfloyd6** [comment]
Ok and now it's slow again ... I can't find what is messing the things up. But I tried to look a bit deeper and I can see that the process Microsoft.VSCode.CPP.Extension.exe is loading a bit the CPU when I ctrl-click a symbol. It takes about 13% of the CPU which indicates that it is well this process who work. I've watched the file handles opened by this process when I ctrl-click a symbol and it looks that he is trying to search through a lot of folders that I've exculded from the search via the rules files.watcherExclude, files.exclude and files.exclude. I've excluded folders such as .svn, .git etc etc and I'm wondering why the parser is trying to search inside those folders when I ctrl-click a symbol so that those folders are not even shown in the files tree. They are not listed in my includePath either.

**Comment by egamma** [comment]
@vfloyd6 thanks for following up. I'm trying to narrow this down to a particular extension that is causing the slow down. We the VS Code team always work with many extensions that provide rich language support and that run in separate processes (.js, .css, .json, .html) and we do not experience this slow down.

When the slow down happened the last time, did you exclusively work with C++? 

> I've exculded from the search via the rules files.watcherExclude, files.exclude and files.exclude.

Notice that these settings only apply to the VS Code explorer, these excludes are not used by the language service specific extensions.

**Comment by vfloyd6** [comment]
> When the slow down happened the last time, did you exclusively work with C++?

I was working with 3 plugins enabled : C/C++, Language cupport for Java by redhat and Python.

The problem is that sometimes the ctrl click is very reactive and sometimes not. Even if I don't change the configuration, the plugins enabled etc etc ...

> Notice that these settings only apply to the VS Code explorer, these excludes are not used by the language service specific extensions.

Yes that's what I thought. I have maybe an idea why the slow down doesn't happen when I have only C/C++ installed. C/C++ bases his search on the includePath so the number of file to search in is limited. But there is no such includePath notion for other plugins (Python and java). So they have to search in .svn, .m2 etc etc that's maybe why it takes longer to show the result. That being said, it should not impact a cltrl-click in a C or C++ file but it does impact a lot...

**Comment by egamma** [comment]
@vfloyd6 

It is still not possible to act on this issue given the information we currently have. Therefore some more question:

>I was working with 3 plugins enabled : C/C++, Language cupport for Java by redhat and Python.

Did you observe a slow down when you 'ctrl+click'/go to definition in all of these 3 languages?

The python and Java extension are only activated when you work on python or java files respectively, that is you have them opened in the editor. When the slow down happens do you remember whether you were actively working on all 3 languages?

When the slow down occurs in a particular file type, e.g., C++, can you disable the other extensions and restart and see whether there is still a slow down.

**Comment by sean-mcmanus** [comment]
The C++ extension shouldn't be impacted by the other language extensions. We currently do processing on all the files under the ${workspaceRoot} (in addition to the includePath), unless it's part of the files.exclude or search.exclude, but we don't currently handle files.watcherExclude.

**Comment by egamma** [comment]
Closing, pls reopen if issue still exists.
