### ISSUE TITLE
Wrong "edt" order in action bar guide

### ISSUE THREAD

**Issue by lorthirk** [Microsoft/vscode#17660]
- VSCode Version: 1.8.1
- OS Version: macOS 10.12.2

Steps to Reproduce:

1. Open the action bar with cmd+p
2. Type ? to show the guide
3. See that the three edt commands are in the wrong order (probably alphabetical, screenshot attached)

<img width="670" alt="schermata 2016-12-21 alle 10 59 18" src="https://cloud.githubusercontent.com/assets/8140139/21384868/90dee3ae-c76c-11e6-813a-5d7523c5d2db.png">

**Comment by egamma** [comment]
I agree `edt one`, `edt two`, ``edt three` would look more natural.

![image](https://cloud.githubusercontent.com/assets/172399/21386928/9773634e-c775-11e6-813f-f82a6079bf3e.png)

**Comment by yajiex** [comment]
1. Will there be 'edt four', 'edt five' and etc in the future?
2. If there were a prefix 'edt think`, what's the expected order for `edt three` and `edt think`?

**Comment by hun1ahpu** [comment]
For these commands what was the reason for not using 'edt 1/2/3' ?

**Comment by lorthirk** [comment]
@hun1ahpu I guess they're just listed in alphabetical order
