### ISSUE TITLE
How to return to the local terminal after ssh connection lost?

### ISSUE THREAD

**Issue by hamad12a** [microsoft/vscode#176620]
Does this issue occur when all extensions are disabled?: Yes/No
Always

- VS Code Version: 
- OS Version: 

Steps to Reproduce:

1. Connecting to ssh works fine
2. After period of time of losing connection to the ssh server the terminal hangs and completely frozen
3. I tried to type but not responding.

I prefer not to kill the terminal because I already created multiple terminals in the spot they look comfortable to me.
I am trying to see if there is key combination I can press to exit the remote session and return to the local session without killing the terminal itself.

**Comment by Tyriar** [comment]
@hamad12a when you say SSH, are you running `ssh` in the terminal or connecting to VS Code via the remote-ssh extension?

**Comment by hamad12a** [comment]
@Tyriar Yes, it is running `ssh` within the built-in terminal of vscode. It gets stuck after losing internet or after wakeup from sleep. I have to kill the terminal and then create a new one but this looks practically cumbersome for frequent usage.

**Comment by Tyriar** [comment]
This is how ssh works, to get a more persistent connection you will need to use something like mosh or the [Remote-SSH](https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-ssh) extension

**Comment by Tyriar** [comment]
It's not clear what the problem could be, I'm assume external terminals behave differently to us under the same circumstances?

**Comment by Tyriar** [comment]
Oh I've been informed that other terminals do this so we're behaving as expected. You can try ctrl+\ which may work, otherwise this is a general ssh question, not vscode.
