### ISSUE TITLE
Extension debugging not working in devcontainer

### ISSUE THREAD

**Issue by andreamah** [microsoft/vscode#176687]
Steps:
1. Launch extension debug from an extension's repository locally (ie: I'm using Live Preview)
2. Open a folder in a devcontainer in the `Extension Development` window (I was using a Debian container).
3. Try looking for commands or settings associated with the extension
4. They don't show :bug:

**Comment by andreamah** [comment]
Hmm, I seem to not see it anymore; might have been an issue with my activation event configs in the extension.

**Comment by andreamah** [comment]
Actually, I think that I was running the copy from the marketplace by accident, so this is still an issue when I'm debugging the extension from the source.

**Comment by chrmarti** [comment]
You need to have the extension's source checked out in the remote filesystem for it to run in the remote extension host. Could you try that?

**Comment by andreamah** [comment]
Ah ok, I thought that might be the case. It works if I have the source on the remote; thanks!
