### ISSUE TITLE
VS Code issues with Git decorators and going to definition, when using a virtual drive

### ISSUE THREAD

**Issue by szepeu** [microsoft/vscode#176652]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: Version: 1.76.0 (user setup)
Commit: 92da9481c0904c6adfe372c12da3b7748d74bdcb
Date: 2023-03-01T10:22:44.506Z
Electron: 19.1.11
Chromium: 102.0.5005.196
Node.js: 16.14.2
V8: 10.2.154.26-electron.0
OS: Windows_NT x64 10.0.19042
Sandboxed: No
- OS Version: Windows 10 Enterprise, 10.0.19042

Steps to Reproduce:

0. I have a large repository of code (~40GB), so some problems might be caused by that...
1. Create a directory structure like so:
  a. Create a git repository in `C:\_WORKSPACE\Project`, having at least one directory: `C:\_WORKSPACE\Project\Code`,
  b. Create a virtual drive `V:` with `subst` pointing to `C:\_WORKSPACE`,
  c. Place some code in the `Code` directory,
2. Launch VS Code in V:\Project\Code,
3. Observe that the Git decorators (normally visible to the left of the changed line) are missing (Git tab is showing changes properly), ctrl+click to go to definition works okay,
4. Launch VS Code in C:\_WORKSPACE\Project\Code,
5. Observe that the decorators are working properly, but cannot go to definition with ctrl+click, unless you open the file that contains the definition you're searching for.

Details:

My directory structure and mapped drives look like so:
1. C:\ is my main (and only) drive
2. I have a C:\_WORKSPACE\Project\Code directories
3. D:\ is a virtual drive mapped to C:\WORKSPACE
4. V:\ is a virtual drive mapped to D:\Project

**Comment by gjsjohnmurray** [comment]
See #100274

**Comment by szepeu** [comment]
Okay, I see I made a duplicate. No fix available though... 🦄
