### ISSUE TITLE
Linux: Watcher fails sometimes

### ISSUE THREAD

**Issue by edotassi** [Microsoft/vscode#1766]
Code: 0.10.6
Os: Linux 4.2.0-22-generic #27-Ubuntu SMP Thu Dec 17 22:57:08 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

It would seem to happen randomly.

**Comment by edotassi** [comment]
![schermata del 2016-01-04 14-06-12](https://cloud.githubusercontent.com/assets/3192179/12090143/5b43a472-b2ec-11e5-8bf5-0ee318ce9250.png)

**Comment by bpasero** [comment]
Will be addressed in https://github.com/Microsoft/vscode/issues/3998
