### ISSUE TITLE
Sticky Scroll doesn't work for some cases.

### ISSUE THREAD

**Issue by subratkatiyar** [microsoft/vscode#176735]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.76.1 (user setup)
- Commit: ee2b180d582a7f601fa6ecfdad8d9fd269ab1884
- Date: 2023-03-08T16:32:00.131Z
- Electron: 19.1.11
- Chromium: 102.0.5005.196
- Node.js: 16.14.2
- V8: 10.2.154.26-electron.0
- OS: Windows_NT x64 10.0.19045
- Sandboxed: No

Steps to Reproduce:

1.  Create a temp.js file with the following code:
```
// Example 1: Simple Call back function. [Sticky Scroll doesn't work]
client.connect({ port: port, host: host }, function() {
    // If there is no error, the server has accepted the request and created a new 
    // socket dedicated to us.
    console.log('TCP connection established with the server.');

    // The client can now send data to the server by writing to its socket.
    client.write('Hello, server.');
});

// Example 2 :Simple Call Back Function. [Sticky Scroll Works].
client.on('data', function(chunk) {
    console.log(`Data received from the server: ${chunk.toString()}.`);
    
    // Request an end to the connection after the data has been received.
    // client.end();
});
```
2. For Example 1, Sticky Scroll doesn't work. 

### **Update: 1** 
- Sticky Scroll works for Example 1, for a few seconds after launching VS Code.
![image](https://user-images.githubusercontent.com/43543908/224257849-f59e9e3b-eae2-49e1-ad14-47f9d3e7ffd8.png)

- After 3-5 seconds, it stops working. [Only for Example 1]
![image](https://user-images.githubusercontent.com/43543908/224258012-c45778e7-ea0a-4311-932a-a140fc66dde8.png)
  

### **Update: 2** 
- Updated Commit hash.
  - Commit: 5e805b79fcb6ba4c2d23712967df89a089da575b to ee2b180d582a7f601fa6ecfdad8d9fd269ab1884

**Comment by gjsjohnmurray** [comment]
Please use the Start Extension Bisect command to investigate whether the problem is being caused by any extensions you may have installed.

**Comment by subratkatiyar** [comment]
I did Extension Bisect: no particular extension was found.
![image](https://user-images.githubusercontent.com/43543908/224275245-c2a6839a-7d92-4e44-8b95-5b6d437b1d5c.png)
I also tried disabling all extensions `code --disable-extension .` 
Still the issue persists.

**Comment by aiday-mar** [comment]
Hi, thank you for commenting. The sticky-scroll uses by default the outline model to generate a sticky model. The outline model is generated using the DocumentSymbolProvider of your installed extensions. Could you check what is the output in the Outline View for the examples you mentioned?

**Comment by subratkatiyar** [comment]
Here's the outline view for the above example.

![image](https://user-images.githubusercontent.com/43543908/230832075-89229732-978c-4589-bf3c-c179c81de949.png)

**Comment by aiday-mar** [comment]
Hi thank you for the help. Could you post the entire example you have used in the updated image? Could you also inform us of the value under the setting `editor.stickyScroll.defaultModel`?

**Comment by subratkatiyar** [comment]
Version: 1.80.1 (user setup)
Commit: 74f6148eb9ea00507ec113ec51c489d6ffb4b771
editor.stickyScroll.defaultModel: **outlineModel**


There are 2 callback functions here, sticky scroll doesn't work for the first one. 
The issue occurs only when defaultModel is set to outlineModel. Indentation and FoldingProivider Model works just fine.
FileName:  **test.js**
```
client.connect({ port: port, host: host }, function () {
  console.log("TCP connection established with the server.");
  client.write("Hello, server.");
});

client.on("data", function (chunk) {
  console.log(`Data received from the server: ${chunk.toString()}.`);
});

```


The Python example works fine now, with all 3 models
https://github.com/microsoft/vscode/issues/176735#issuecomment-1497444640
