### ISSUE TITLE
vscode.dev: Mixed language in the remote command menu

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode#176790]
Version : 1.76.1
Commit : 5e805b79fcb6ba4c2d23712967df89a089da575b
Date : 2023-03-08T16:32:15.546Z
Navigateur : Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.4985.0 Safari/537.36 Edg/102.0.1235.1

vscode.dev with the `Remote Repositores` extension installed (stable)
- switch the display language to French, reload VS Code
- switch the display language to English, reload VS Code
- open the remote menu, see that there's still a French menu entry in there

![image](https://user-images.githubusercontent.com/6461412/224356299-23d71b70-44e4-4cdc-ae55-3e6be0d6081b.png)

Open the extension view
![image](https://user-images.githubusercontent.com/6461412/224356449-99af4c2e-3783-4445-a48c-86efeb54acb7.png)

I also see it the other way around:
![image](https://user-images.githubusercontent.com/6461412/224357159-a434cc22-ad77-47d4-959f-f0edf97859bf.png)

**Comment by TylerLeonhardt** [comment]
Ahhh so it looks like this is returning remote-repositories extension:
[https://github.com/microsoft/vscode/blob/83fe8e03fbeef59a32e71f4dad43d9ba19857c70/[…]ices/extensionManagement/browser/webExtensionsScannerService.ts](https://github.com/microsoft/vscode/blob/83fe8e03fbeef59a32e71f4dad43d9ba19857c70/src/vs/workbench/services/extensionManagement/browser/webExtensionsScannerService.ts#L536)
with the old german manifest. What’s odd to me is that remote-repositories is being returned by `this.readCustomBuiltinExtensions` and `this.scanInstalledExtensions`... but even still, I don't know much about this code, but I would expect that the cache would cache the manifest in its raw form with the `%foo%` placeholders and then allow the runtime to translate the manifest (which could be optimized to cache both raw and translated form and only re-compute when language changes)

**Comment by TylerLeonhardt** [comment]
@sandy081 I'm giving this one to you since it seems like a issue from the caching changes.

**Comment by sandy081** [comment]
It seems we are translating the manifest always even if it is cached. But, I observed that some how (I do not know, may be in the old code), cache is having the already translated manifest. Therefore, while translating nothing gets translated. We do update cache every time but it seems if the version has not changed, we reuse the entry from the cache. There is no reason we have to reuse the entry from the cache. So fixed it by recomputing the cache entry always while updating the cache.
