### ISSUE TITLE
codefix key-chord doesn't work when  the caret is at the end of the 

### ISSUE THREAD

**Issue by aleksey-bykov** [Microsoft/vscode#17677]
- VSCode Version: 1.9.x insider's preview
- OS Version: Windows 10

Steps to Reproduce:

1. create a situation for a codefix
2. observe a piece of code with a wiggly line and a codefix icon
3. place the caret at the very end of the wiggly line
4. hit `Ctrl + .` (current combination for engaging codefixes)
5. observe nothing happens

expected: a popup with codefix choices should be displayed

**Comment by egamma** [comment]
@aleksey-bykov 

I cannot reproduce given the steps above, see the attached recording. 

Can you pls attach a recording as well? 
Does the popup appear when you are not at the end of the warning? 

![quickfix](https://cloud.githubusercontent.com/assets/172399/21392489/69629f2c-c790-11e6-9f6e-407001155db2.gif)

**Comment by aleksey-bykov** [comment]
here, it's typescript import codefix

![codefix-key-chord-not-working](https://cloud.githubusercontent.com/assets/937933/21393440/6a1cbd9a-c762-11e6-9255-31ba6383a698.gif)

**Comment by aleksey-bykov** [comment]
here is a better screen cast
![codefix-key-chord-not-working](https://cloud.githubusercontent.com/assets/937933/21393516/c81298d4-c762-11e6-9625-e744bd983c3e.gif)

**Comment by aleksey-bykov** [comment]
i can't really show how it's not working in the video, because, well, when i try nothing is going on

**Comment by egamma** [comment]
@aleksey-bykov thanks this helps. 

Actually I can still not reproduce since I do not get a quick fix at all. I suspect this feature is contributed by an extension. Can you attach the list of extensions you have installed? To get list execute `Help>Report Issues` and copy the table into this issue.

**Comment by aleksey-bykov** [comment]
it's the latest typescript (2.2.0-dev.20161221 as of writing this)

which you can get by running:
```
npm install typescript@next
```

with 
```
    "typescript.tsdk": "./node_modules/typescript/lib",
```

in the `.vscode/settings.json`

per https://github.com/Microsoft/vscode/issues/17633

**Comment by mjbvz** [comment]
Closing as duplicate of #17569
