### ISSUE TITLE
Change extension order for Diff language id

### ISSUE THREAD

**Issue by JimiC** [Microsoft/vscode#17672]
Currently the order is:
- `.patch`
- `.diff`
- `.rej`

This creates a visual issue when using different images for `diff` and `patch`.

Currently we on [vscode-icons](https://github.com/robertohuertasm/vscode-icons) do so and although the associated files get the correct image, in the `Language Mode` selection it shows the `patch` image and not the `diff` image.

Changing the order to:
- `.diff`
- `.patch`
- `.rej`

or
- `.diff`
- `.rej`
- `.patch`

should fix the issue.

**Comment by egamma** [comment]
The issue refers to this https://github.com/Microsoft/vscode/blob/master/extensions/diff/package.json#L11

**Comment by JimiC** [comment]
Submitted #17680
