### ISSUE TITLE
Debug start doesn't rebuild after a source change

### ISSUE THREAD

**Issue by francotiveron** [microsoft/vscode#176718]
Type: <b>Bug</b>

Since the last update, after a modification int he source code, starting the debugger (F5) doesn't rebuild the project (F#, .NET 6)

VS Code version: Code - Insiders 1.77.0-insider (502ac5b213e373026527efdbcea4e669d930d9e1, 2023-03-09T05:22:23.670Z)
OS version: Windows_NT x64 10.0.19044
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-10885H CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|63.73GB (35.09GB free)|
|Process Argv|--crash-reporter-id 069701b0-35c0-493b-b96d-091de8b8f40e|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (54)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-template-fsharp-highlight|alf|1.7.0
k8s-snippets|dog|0.4.2
gitlens|eam|13.3.2
vscode-open-in-application|fab|1.0.6
remotehub|Git|0.52.0
flux|inf|1.0.4
Ionide-fsharp|Ion|7.5.1
base64|m4n|0.0.3
bash-ide-vscode|mad|1.35.0
file-downloader|min|1.0.12
mindaro|min|2.0.120230216
ecdc|mit|1.8.0
azure-pipelines|ms-|1.208.0
azure-dev|ms-|0.4.0
vscode-azureappservice|ms-|0.24.7
vscode-azurefunctions|ms-|1.10.4
vscode-azureresourcegroups|ms-|0.6.1
vscode-azurestaticwebapps|ms-|0.11.4
vscode-azurestorage|ms-|0.15.1
vscode-azurevirtualmachines|ms-|0.6.4
vscode-bicep|ms-|0.15.31
vscode-cosmosdb|ms-|0.19.3
vscode-dapr|ms-|0.7.0
vscode-docker|ms-|1.24.0
csharp|ms-|1.25.4
vscode-dotnet-runtime|ms-|1.6.0
vscode-aks-tools|ms-|1.3.11
vscode-kubernetes-tools|ms-|1.3.11
isort|ms-|2022.8.0
python|ms-|2023.4.1
vscode-pylance|ms-|2023.3.20
jupyter|ms-|2023.2.1200692131
jupyter-keymap|ms-|1.1.0
jupyter-renderers|ms-|1.0.15
vscode-jupyter-cell-tags|ms-|0.1.6
vscode-jupyter-slideshow|ms-|0.1.5
remote-containers|ms-|0.283.0
remote-wsl|ms-|0.76.1
azure-account|ms-|0.11.3
azure-repos|ms-|0.29.2023030801
azurecli|ms-|0.5.0
hexeditor|ms-|1.9.11
powershell|ms-|2023.2.1
remote-repositories|ms-|0.31.2023030901
vscode-node-azure-pack|ms-|1.1.1
azurerm-vscode-tools|msa|0.15.8
debugger-for-chrome-nightly|msj|2020.2.15300
vscode-thunder-client|ran|2.5.1
vscode-yaml|red|1.12.1
bash-debug|rog|0.3.9
kubernetesapply|Sha|1.4.1
azure-event-hub-explorer|Sum|0.1.1
large-file|yy0|1.0.12
k8s-snippets|yzd|0.1.6

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30422396
pythontb:30258533
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscod805:30301674
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30404738
cppdebug:30492333
vsclangdf:30492506
c4g48928:30535728
dsvsc012:30540252
pynewext54:30618038
pylantcb52:30590116
pyindex848:30611229
nodejswelcome1:30587009
pyind779:30611226
pythonsymbol12:30651887
a9j8j154:30646983
6233i204:30659907
vscodedisable:30660115
pythonb192:30661256
funwalk2cf:30682975
pythonms35:30671666
cai9j608:30680470
ecj1e332:30677316

```

</details>

**Comment by roblourens** [comment]
I'm not sure how your project is set up, do you have a preLaunchTask? Is it not running? If there is an issue, it sounds like an issue with the extension, but I need more details

**Comment by francotiveron** [comment]
@roblourens 
First of all, note that it has been working correctly for months, then it stopped without any change in the configuration.
Launch configuration

```
        {
            "name": "Api (daprd)",
            "type": "coreclr",
            "env": {
                "DAPR_HTTP_PORT": "3506",
                "DAPR_GRPC_PORT": "50006"
            },
            "request": "launch",
            "preLaunchTask": "daprd-debug-api",
            "program": "${workspaceFolder}/Yatp.Api/bin/Debug/net6.0/Yatp.Api.dll",
            "args": [],
            "cwd": "${workspaceFolder}/Yatp.Api",
            "stopAtEntry": false,
            "console": "externalTerminal",
            "postDebugTask": "daprd-down-api"
        },
```

pre launch task

```
        {
            "label": "daprd-debug-api",
            "type": "daprd",
            "config": ".dapr/localhost/config.yaml",
            "componentsPath": ".dapr/localhost/components",
            "appId": "yatp-api",
            "appPort": 5166,
            "httpPort": 3506,
            "grpcPort": 50006,
            "metricsPort": 9096,
            "dependsOn": "build-api"
        },
```

**Comment by francotiveron** [comment]
It starts immediately the debug, without building, even if I made changes on the source code. I have to manually run dotnet build before launching the debugger

**Comment by roblourens** [comment]
So that means it didn't run the task? Or the task didn't work?

**Comment by francotiveron** [comment]
I've found the issue:

Before, on F5, a new terminal instance was created and the tasks were all processed.
Now, if the terminal instance of the last launch is not closed manually, it is used and as the build task has already been processed, it skips it.
Unfortunately the settings presentation.close="true" doesn't work for daprd task, but this has to do with DAPR
