### ISSUE TITLE
Debug Console repl unexpected variable name when empty

### ISSUE THREAD

**Issue by suzmue** [microsoft/vscode#176798]
Does this issue occur when all extensions are disabled?:No

- VS Code Version:
reproductible on both:
```
$ code -v
1.76.0
92da9481c0904c6adfe372c12da3b7748d74bdcb
x64
$ code-insiders -v
1.77.0-insider
bbc87d8ec2453f12c0066e1c30b41cd5bd2aa021
x64
```

- OS Version: macOS 13.2.1 (22D68)

This issue was originally filed in the Go extension repo as golang/vscode-go#2686 

I suspect this is related to the handling of variables without names. The variables that appear to have randomly selected names, have `name=""` in the DAP response.

Steps to Reproduce:

1. Create a go project with the following.
main_test.go:
```golang
package main 

import (
	"testing"
)

type A struct {
	a string
}

func TestPointer(t *testing.T) {
	data := &A{a: "hello"}
	if data == nil {
		t.Error("no")
	}
}

```
go.mod:
```
module example

go 1.18
```

2. Start debugging with the following launch configuration:
launch.json:
```json
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387

    "version": "0.2.0",
    "configurations": [
        {
            "name": "Launch test function",
            "type": "go",
            "request": "launch",
            "mode": "test",
            "program": "${workspaceFolder}",
            "args": [
                "-test.run",
                "TestPointer"
            ],
        }
    ],
}

``` 
<img width="399" alt="Screenshot 2023-03-10 at 11 20 42 AM" src="https://user-images.githubusercontent.com/6634754/224368740-074421f4-be69-414f-8e37-dc915508481e.png">

Expand `data` in the variable pane:
<img width="445" alt="Screenshot 2023-03-10 at 11 23 21 AM" src="https://user-images.githubusercontent.com/6634754/224369051-c04e4ff3-2724-46f3-85b9-e7050c45f96b.png">

Evaluate `data in repl, and expand the result once:
<img width="983" alt="Screenshot 2023-03-10 at 11 23 26 AM" src="https://user-images.githubusercontent.com/6634754/224368946-b56f969c-1969-480a-a582-eefef4da15fc.png">

The result in repl also should not have a name. In the DAP result the name is an empty string.

**Comment by roblourens** [comment]
cc @connor4312 this is from https://github.com/microsoft/vscode/pull/172880, I think it's this simple fix, lmk if you think this isn't right https://github.com/microsoft/vscode/pull/178704

**Comment by connor4312** [comment]
Looks sensible 👍
