### ISSUE TITLE
Multiple close in source control is not working

### ISSUE THREAD

**Issue by ivanbarsukov** [microsoft/vscode#176717]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 
Version: 1.74.3
Commit: 97dec172d3256f8ca4bfb2143f3f76b503ca0534
Date: 2023-01-09T16:57:40.428Z
Electron: 19.1.8
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Linux x64 6.2.2-arch1-1
Sandboxed: No
- OS Version: Arch Linux

Steps to Reproduce:
1. Open folder with multiple repositories 
2. Choose several repos
3. Choose 'Close Repository' in context menu
4. See that only one repo was deleted

![Screenshot_20230310_093433](https://user-images.githubusercontent.com/14816075/224218004-a4c70c7c-23ab-4469-9bd9-2f7f93166b3f.png)
![Screenshot_20230310_093447](https://user-images.githubusercontent.com/14816075/224218013-f5454625-7cef-4421-9e3d-d6c4cf37a999.png)

**Comment by WhiteCoffee9834** [comment]
What theme are you using?
Thanks.

**Comment by ivanbarsukov** [comment]
> What theme are you using?

Monokai Pro

**Comment by irgendwr** [comment]
Here is a PR that implements this: #201073

**Comment by lszomoru** [comment]
Implemented in https://github.com/microsoft/vscode/pull/202512 and https://github.com/microsoft/vscode/pull/202521
