### ISSUE TITLE
Enable/disable viewlet contributions per language

### ISSUE THREAD

**Issue by gruvw** [microsoft/vscode#176739]
@sandy081 marked the "community approved" issue #124031 as duplicate, the use of the profiles feature should solve the use case described.

However, I don't see how the profiles feature is supposed to solve the issue ?

In #124031 I described the ability to hide/show "viewlet contributions" (or what I called activity bar icons) per language (not per workspace or per "profile", but based on the current edited language document).

I think there has been a confusion: the issue was not about disabling extensions, just hiding the following UI icons automatically based on the programming language currently in use.
<img src="https://user-images.githubusercontent.com/63407038/224265863-a10d71df-daa6-48d4-88a3-c1fdc9803926.png" height="400">

Could someone show me how to use the profiles feature to solve the described use case ?  
And if this is not solved by the profile feature, reopen #124031.

Thanks

**Comment by sandy081** [comment]
- Create a profile say A
- Hide the activity bar icons you want in this profile
- Create a profile say B
- Hide the activity bar icons you want in this profile

You can switch between the profiles and the visible views state is stored and restored accordingly.

Please check this guide for any help - https://code.visualstudio.com/docs/editor/profiles

**Comment by gruvw** [comment]
Thank you, I had already checked the linked guide.

The purpose of hiding icons is to declutter the sidebar and only display relevant extensions for easy access. However, having to manually switch between profiles for each file can defeat this purpose.

Is there a way to automatically switch profiles based on the document language ?  
It feels a bit intense for such an easy UI operation.  
As I understand this, profiles are much more deep and more meaningful across different workspaces.
They were not introduced as a way to customize the UI behavior based on editing language.

Switching back and forth between two files of different languages can occur frequently (multiple times per minute), and I feel like this use case may not be adequately covered by the profiles feature.

Overall, it would be beneficial for the VSCode team to consider implementing a solution that allows for easy switching between files of different languages within polyglot projects while maintaining a clutter-free sidebar.

**Comment by sandy081** [comment]
Reopening the original feature request because I think profiles is not the right approach for your usecase.
