### ISSUE TITLE
Cannot install extensions installed on host into dev container 

### ISSUE THREAD

**Issue by daniel-pledge-io** [microsoft/vscode#176759]
Type: <b>Bug</b>

I cannot install extensions that are already installed on my host into dev containers.

Installing extensions which are not already installed on the host _fails_ with the same error, but I am presented the option to download manually and I can install directly into the container from VSIX without issue.

Occurs on VS Code and VS Code insiders.

Take ESLint (`dbaeumer.vscode-eslint`) as an example. I have it installed on my host, vs code in my dev container tells me `This extension is disabled in this workspace because it is defined to run in the Remote Extension Host. Please install the extension in 'Container node:14 ([container name])' to enable.` as expected.

Clicking `install in container`, fails with a pop up `RequiredArgumentMissing`.
<img width="967" alt="Screenshot 2023-03-10 at 11 23 47" src="https://user-images.githubusercontent.com/125913742/224309703-7da2b0f6-72ea-4d0c-8f68-ba395b13afda.png">

On vscode, the `Window` logs contain:
```
2023-03-10 11:27:16.165 [error] RequiredArgumentMissing: Signature: RequiredArgumentMissing
    at Pi.download (/root/.vscode-server/bin/5e805b79fcb6ba4c2d23712967df89a089da575b/out/vs/server/node/server.main.js:150:468)
    at async ee.x (/root/.vscode-server/bin/5e805b79fcb6ba4c2d23712967df89a089da575b/out/vs/server/node/server.main.js:150:20845)
    at async ee.h (/root/.vscode-server/bin/5e805b79fcb6ba4c2d23712967df89a089da575b/out/vs/server/node/server.main.js:150:18978)
```
This log error is the exact same as the one that appears when I try and install an extension that is not on the host.

On vs code insiders, when trying to install copilot, the `Server` logs show:
```
2023-03-10 11:50:03.278 [info] Getting Manifest... github.copilot
2023-03-10 11:50:03.326 [info] Installing extension: github.copilot
2023-03-10 11:50:04.373 [error] Error while installing the extension: github.copilot
2023-03-10 11:50:04.374 [error] Failed to install extension. github.copilot
2023-03-10 11:50:04.374 [error] Signature: RequiredArgumentMissing
    at ki.download (/root/.vscode-server-insiders/bin/b60db78000bfa99d1b290194ed4651c4ceef02cc-insider/out/vs/server/node/server.main.js:153:468)
    at async z.y (/root/.vscode-server-insiders/bin/b60db78000bfa99d1b290194ed4651c4ceef02cc-insider/out/vs/server/node/server.main.js:153:21026)
    at async z.h (/root/.vscode-server-insiders/bin/b60db78000bfa99d1b290194ed4651c4ceef02cc-insider/out/vs/server/node/server.main.js:153:19090)
```

About VS Code output from the dev container:
```
Version: 1.76.1 (Universal)
Commit: 5e805b79fcb6ba4c2d23712967df89a089da575b
Date: 2023-03-08T16:32:09.831Z (1 day ago)
Electron: 19.1.11
Chromium: 102.0.5005.196
Node.js: 16.14.2
V8: 10.2.154.26-electron.0
OS: Darwin arm64 21.3.0
Sandboxed: Yes
```

and for vs code insiders
```
Version: 1.77.0-insider (Universal)
Commit: b60db78000bfa99d1b290194ed4651c4ceef02cc
Date: 2023-03-10T05:27:21.183Z (6 hrs ago)
Electron: 19.1.11
Chromium: 102.0.5005.196
Node.js: 16.14.2
V8: 10.2.154.26-electron.0
OS: Darwin arm64 21.3.0
Sandboxed: Yes
```

VS Code version: Code 1.76.1 (Universal) (5e805b79fcb6ba4c2d23712967df89a089da575b, 2023-03-08T16:32:09.831Z)
OS version: Darwin arm64 21.3.0
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Max (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|15, 7, 5|
|Memory (System)|32.00GB (0.22GB free)|
|Process Argv|--crash-reporter-id aa2f6769-6768-49e1-9725-0ee294f51a49|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (24)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|13.3.1
quitcontrol-vscode|art|4.0.0
vscode-eslint|dba|2.4.0
eslint-disable-snippets|drK|1.3.0
es7-react-js-snippets|dsz|4.4.3
copilot|Git|1.77.9225
copilot-labs|Git|0.12.791
vscode-graphql|Gra|0.8.6
vscode-graphql-execution|Gra|0.1.8
vscode-graphql-syntax|Gra|1.1.0
todo-tree|Gru|0.0.224
hcl|has|0.3.2
terraform|has|2.25.4
vscode-peacock|joh|4.2.2
vsc-python-indent|Kev|1.18.0
vscode-scss|mrm|0.10.0
vscode-docker|ms-|1.24.0
remote-containers|ms-|0.282.0
vscode-twoslash-queries|Ort|1.1.0
vscode-yaml|red|1.12.1
trailing-spaces|sha|0.4.1
vscode-stylelint|sty|1.2.4
jinja|who|0.0.8
markdown-all-in-one|yzh|3.5.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vscaat:30438848
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
pynewvextcfv2:30681851
azure-dev_surveyone:30548225
pyindex848:30662994
nodejswelcome1cf:30587006
3biah626:30602489
pyind779:30671433
f6dab269:30613381
pythonsymbol12:30671437
2i9eh265:30646982
vsctsb:30677850
pythonb192:30669360
funwalk2cf:30682975

```

</details>

**Comment by sandy081** [comment]
CC @dtivel

**Comment by shrkw** [comment]
Thank you @sfc-gh-dsada !
I copied it to `.devcontainer/devcontainer.json` and it works on my side too!

```
{
	"name": "foobar",
	"customizations": {
		"vscode": {
			"settings": {
				"extensions.verifySignature": false
			}
		}
	}
}
```

**Comment by isidorn** [comment]
Closing as dup of https://github.com/microsoft/vscode/issues/175705
