### ISSUE TITLE
Status message string contains {0}

### ISSUE THREAD

**Issue by rzhao271** [microsoft/vscode#176701]
I tried running `code --status` without having an instance of Code open and got the following message with a literal `{0}` in it:
```
./code.exe status

[main 2023-03-09T17:20:57.011Z] Warning: The --status argument can only be used if Code is already running. Please run it again after {0} has started.
```

**Comment by rzhao271** [comment]
\closedWith 099b866cfbf940496681f4562dcab03a5d5202a3

**Comment by mjbvz** [comment]
Still seeing this with 833ac685084e2028b09753392b82c641c7025bbc:



```bash
matb@mjbmbp16 ~ % code-insiders --status
[main 2023-03-21T20:49:03.374Z] Warning: The --status argument can only be used if {0} is already running. Please run it again after {0} has started. Code - Insiders
[71863:0321/134903.406350:WARNING:pref_notifier_impl.cc(60)] Init observer found at shutdown.
```

**Comment by rzhao271** [comment]
I'm unable to see the message now unless `--verbose` is used.
While running `code-insiders --status --verbose`, I don't see `{0}` show up for it on either macOS or Windows.
