### ISSUE TITLE
C execution problem

### ISSUE THREAD

**Issue by BharathThatha** [microsoft/vscode#176728]
Type: <b>Feature Request</b>

There is a problem in running C language program and also when I open VS code Dev c++ is stated and it pop-up's a dialoug box that something is not found and error.

VS Code version: Code 1.76.1 (5e805b79fcb6ba4c2d23712967df89a089da575b, 2023-03-08T16:32:00.131Z)
OS version: Windows_NT x64 10.0.19044
Modes:
Sandboxed: Yes

**Comment by roblourens** [comment]
It sounds like you are having an issue with an extension, please file this on the extension's repo
