### ISSUE TITLE
Large file support and hex binary file display

### ISSUE THREAD

**Issue by MeteorKepler** [Microsoft/vscode#17673]
- VSCode Version:1.8.1
- OS Version: macOS Sierra 10.12.2

I'm using vs code as my first choice when editing code and multiple types of files. But there are two issues annoying me:
* Large file support. 
It can't open large data file like json or logging files that are important in my projects. It's not too large, just 50MB-200MB.
* Hex display of binary file. 
When I need to handle raw binary file it shows that VScode doesn't support this decode style. I don't need VSCode to decode the file, just show me binary number in hex or binary. Many web stream files are binary and I need to extract them. 

Thanks if you consider my suggestions.

**Comment by egamma** [comment]
@MeteorKepler  thanks for your enhancement requests, pls follow our guidelines https://github.com/Microsoft/vscode/wiki/Submitting-Bugs-and-Suggestions#writing-great-issues-and-suggestions when submitting feature requests and file one issue per request.

>Hex display of binary file.
pls try this extension https://marketplace.visualstudio.com/items?itemName=slevesque.vscode-hexdump

**Comment by MeteorKepler** [comment]
Thank you very much!


————————————————————
Tsinghua University, Beijing, China
Electronic Engineering Department
Bo Zihao
tel：13051875837
E-mail：bzh13@mails.tsinghua.edu.cn<http://mails.tsinghua.edu.cn>




在 2016年12月21日，22:24，Erich Gamma <notifications@github.com<mailto:notifications@github.com>> 写道：


Closed #17673<https://github.com/Microsoft/vscode/issues/17673>.
