### ISSUE TITLE
Git Clone: Default clone into /tmp folder

### ISSUE THREAD

**Issue by altern8tif** [Microsoft/vscode#17671]
Feature suggestion:  To default git clone into the `/tmp` folder, or to at least allow settings for a default folder...

I typically use this to dig deeper into Github repos on Atom/VS Code, rather than browsing through their web interface.  So setting up `git clone` like this saves a lot of time and automatically purges my repos when I restart my comp.

This replicates the feature set for the [git-clone Atom package](https://github.com/brianchung808/git-clone).

**Comment by egamma** [comment]
fyi @joaomoreno

**Comment by joaomoreno** [comment]
PR welcome, for the setting.

**Comment by yossi-eynav** [comment]
@joaomoreno I would like to make my first contribution

**Comment by lifez** [comment]
@yossi-eynav Are you working on this issue ?

If not. Would you mind if i take this ?

cc @joaomoreno

**Comment by yossi-eynav** [comment]
@gagangupt16 already created a PR for this issue.
see https://github.com/Microsoft/vscode/pull/18567

**Comment by ihalip** [comment]
I see that the old PR was closed - is this still needed? I see that the git extension defaults to `os.homedir()` when cloning.
