### ISSUE TITLE
vs coad is not running

### ISSUE THREAD

**Issue by Aravindh0359** [microsoft/vscode#176761]
Type: <b>Feature Request</b>

where as i was new to coading  and i want to learn html so i research and notised that VS COAD is the best way for it.
so i have installed vs coad from microsoft store but it is stil no working.
again i have downloaded from chrome also and installed but same problume i am facing . so PLEASE solve me this issue

VS Code version: Code 1.76.1 (5e805b79fcb6ba4c2d23712967df89a089da575b, 2023-03-08T16:32:00.131Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: Yes

**Comment by gjsjohnmurray** [comment]
You appear to have opened the root of your D: drive, then asked VS Code to show you what is inside the special "System Volume Information" folder.

I suggest you create an ordinary folder on your D drive, then open that in VS Code.

**Comment by DonJayamanne** [comment]
@Aravindh0359 
* Please could you create a folder named `d:\temp`
* Go into VS Code and select `File -> Open Folder`
* Select the above folder and click ok
* That shoudl work

Closing as this should fix it, if you still run into issues, please let us know and we'll re-open this issue or please feel free to re-open this issue or crteate a new one.
