### ISSUE TITLE
Cannot see my folder in my explorer tab

### ISSUE THREAD

**Issue by ariansergi95** [microsoft/vscode#176757]
Type: <b>Bug</b>

Hi, today I saw that I cannot see any folders on explorer on the left hand side when I open a new folder I uninstall all extension and uninstall the VS code and install it again but the the isuue is still there

VS Code version: Code 1.76.1 (5e805b79fcb6ba4c2d23712967df89a089da575b, 2023-03-08T16:32:00.131Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|12th Gen Intel(R) Core(TM) i5-1235U (12 x 2496)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.68GB (8.12GB free)|
|Process Argv|--crash-reporter-id d81877ea-75a2-49ce-a3b1-efe5d2d6df7c|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
pynewvextcfv2:30681851
azure-dev_surveyone:30548225
vsccc:30610678
pyindex848:30662994
nodejswelcome1:30587005
2e4cg342:30602488
pyind779:30671433
89544117:30613380
pythonsymbol12:30671437
a9j8j154:30646983
showlangstatbar:30672706
vsctsb:30677850
pythonb192:30669360
funwalk2cf:30682975

```

</details>

**Comment by AlesyaPolik** [comment]
Have some issue, it started just ~30-40 minutes ago.

**Comment by AlesyaPolik** [comment]
@ariansergi95 looks like so, we both faced it at the same time

**Comment by ariansergi95** [comment]
I just installed the version 1.75.0, the bug did not resolved. Please let me know if you find anything

**Comment by ariansergi95** [comment]
after you open the folder you need to click on the file and then click on add folder to the workspace

**Comment by AlesyaPolik** [comment]
Just tried, did not work, it just does nothing

**Comment by AlesyaPolik** [comment]
![Recording 2023-03-10 at 16 40 21](https://user-images.githubusercontent.com/66110997/224359324-eede3c71-bf72-4ea2-bcc6-1c5807fb68ae.gif)
the folder I'm trying to open is not empty
![image](https://user-images.githubusercontent.com/66110997/224359435-a2cf5f9d-0c7d-4c95-b804-5533a3d1303a.png)

**Comment by gjsjohnmurray** [comment]
Your screenshot shows the OPEN EDITORS view within the Explorer view container. It looks like your FOLDERS view has been hidden or moved somewhere else.

When you right-click on EXPLORER: OPEN EDITORS what options does the context menu offer you?

**Comment by AlesyaPolik** [comment]
![image](https://user-images.githubusercontent.com/66110997/224365771-f4f87e03-6d96-4adf-8c46-cf009f0e646e.png)

**Comment by gjsjohnmurray** [comment]
Can you run a `View: Show Explorer` command from Command Palette (F1)?

**Comment by gjsjohnmurray** [comment]
OK, I guess you accidentally dragged it off its default position as a view within the EXPLORER view container, and dropped it onto the Activity Bar where it became a second entry. Now you have found it, right-click on its Activity Bar icon and choose `Reset Location`.

**Comment by AlesyaPolik** [comment]
The reset location worked, thank you very much!

**Comment by gjsjohnmurray** [comment]
That's good. Please close the issue.

**Comment by ariansergi95** [comment]
Thanks you save me today!

**Comment by lramos15** [comment]
> That's good. Please close the issue.

It's surprising how many people lose their explorer now that it's moveable when all other views are moveable and we don't see them getting lost as much. I wonder if there's a way we can improve this experience.
