### ISSUE TITLE
Mouse Right Click on file at Right Primary Sidebar: Context Menu was Too close to Cursor 

### ISSUE THREAD

**Issue by nityam01** [microsoft/vscode#176853]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.76.1
- OS Version: Fedora 37 | Linux x64 6.1.14-200.fc37.x86_64

Steps to Reproduce:

1.  Right Click on any files which are below half of the Menu at the Right Primary Sidebar
2. Menu was Too close to Curson which led to clicking on any Action on the Context menu
[Screencast from 2023-03-11 20-21-34.webm](https://user-images.githubusercontent.com/90498771/224491698-ca110845-1e61-4c6c-bea4-3fe8bdf2d519.webm)

**Comment by gjsjohnmurray** [comment]
Related to  #167941
