### ISSUE TITLE
Configurable behavior of page-up (cursorPageUp) and page-down (cursorPageDown)

### ISSUE THREAD

**Issue by kobalicek** [Microsoft/vscode#17686]
I haven't found a way how to change the behavior of page-up and page-down to the following:

  * when I hit page-up / page-down, the cursor won't visually move the line, but the content scrolls up or down.
  * this basically means, that hitting page-up and then page-down brings me to the same "view" as it was before (unless I hit start / end of document)

Currently when I press page-up / page-down the page doesn't scroll, but the cursor moves up or down first (then after hitting page-up / page-down again it scrolls finally). I'm not used to this behavior and would like to change that.

Not sure I expressed this correctly, I just would like to have the option to control this.

**Comment by alexandrudima** [comment]
There are two commands that do what you wish, but they need to be bound to a key combination:
In your keybindings.json
```
{ "key": "ctrl+pagedown",          "command": "scrollPageDown",
                                     "when": "editorTextFocus" },
{ "key": "ctrl+pageup",            "command": "scrollPageUp",
                                     "when": "editorTextFocus" }

```

**Comment by kobalicek** [comment]
It's not the same, what you suggest is to just scroll without moving the cursor, I wanted the behavior that is in Visual Studio and all other IDEs, when I press PageUp/Down it scrolls and moves the cursor as well.
