### ISSUE TITLE
F#

### ISSUE THREAD

**Issue by wgrs** [microsoft/vscode#176859]
Type: <b>Bug</b>

Everytime I open VSCode, the F# icon on the left is shown even though it deselected to show. I am not using F#. Its very annoying because it comes back everytime I open the IDE.  Also, when making a new file, I keep getting an error saying the new file is duplicated. Its not.

VS Code version: Code 1.76.1 (5e805b79fcb6ba4c2d23712967df89a089da575b, 2023-03-08T16:31:31.010Z)
OS version: Linux x64 5.19.0-35-generic
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-2350M CPU @ 2.30GHz (4 x 2294)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|1, 0, 0|
|Memory (System)|7.68GB (5.27GB free)|
|Process Argv|--unity-launch --crash-reporter-id be0bf7cc-f375-4e34-8dce-d531441594d2|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|plasma|
|XDG_CURRENT_DESKTOP|KDE|
|XDG_SESSION_DESKTOP|KDE|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (44)</summary>

Extension|Author (truncated)|Version
---|---|---
namespace|adr|1.1.2
nugetpackagemanagergui|ali|2.0.6
addfileextension|bgs|0.1.4
htmltagwrap|bra|0.0.7
vscode-tailwindcss|bra|0.9.7
path-intellisense|chr|2.8.4
gitignore|cod|0.9.0
vscode-markdownlint|Dav|0.49.0
vscode-eslint|dba|2.4.0
es7-react-js-snippets|dsz|4.4.3
EditorConfig|Edi|0.16.4
prettier-vscode|esb|9.10.4
auto-rename-tag|for|0.1.10
dotnet-test-explorer|for|0.7.8
rest-client|hum|0.25.1
Ionide-fsharp|Ion|7.5.1
nuget-reverse-package-search|jes|0.1.68
jwt-decoder|jfl|1.2.0
vscode-nuget-package-manager|jmr|1.1.6
vscode-csharp-snippets|jor|1.1.0
roslynator|jos|4.2.0
theme-monokai-pro-vscode|mon|1.2.0
csharp|ms-|1.25.4
dotnet-interactive-vscode|ms-|1.0.4152020
vscode-dotnet-pack|ms-|1.0.12
jupyter|ms-|2023.2.1200692131
jupyter-keymap|ms-|1.1.0
jupyter-renderers|ms-|1.0.15
vscode-jupyter-cell-tags|ms-|0.1.6
vscode-jupyter-slideshow|ms-|0.1.5
remote-containers|ms-|0.282.0
powershell|ms-|2023.2.1
test-adapter-converter|ms-|0.1.6
vs-browser|Phu|2.0.10
sqlite-viewer|qwt|0.2.3
LiveServer|rit|5.7.9
markdown-preview-enhanced|shd|0.6.8
markdown|sta|2.0.1
vscode-styled-components|sty|1.7.5
sapling|tea|1.2.0
vscode-icons|vsc|12.2.0
ReactSnippets|xab|2.4.0
markdown-all-in-one|yzh|3.5.0
material-theme|zhu|3.15.8

(4 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
pynewext54:30681850
azure-dev_surveyone:30548225
vscccc:30610679
pyindex848:30662994
nodejswelcome1:30587005
2e4cg342:30602488
pyind779:30671433
89544117:30613380
pythonsymbol12:30671437
2i9eh265:30646982
vsctsb:30677850
funwalk2cf:30682975

```

</details>

**Comment by gjsjohnmurray** [comment]
I suggest you uninstall the extension that is contributing this, probably Ionide-fsharp
