### ISSUE TITLE
Git file history temp file is lost after switching

### ISSUE THREAD

**Issue by anothergituser** [Microsoft/vscode#17689]
- VSCode Version:  1.8.1
- OS Version: Fedora 22

Steps to Reproduce:

In file explorer, right click and Git: view file history then select a commit and View file contents. This will open a temp file with that revision, but if you switch to another file it is lost and an error is shown prompting to create the file because it does not exist.

I was hoping it would keep the file in the Opened editors top pane, because i can perfectly create a new empty file with Ctrl-n and not save it to disk and be able to switch to it after opening another file.

Thanks.

**Comment by shyang7526** [comment]
@jslee1301 @shyang7526 @jhsmedia2

**Comment by egamma** [comment]
The command 'Git: view file history' is provided by an extension. I suspect https://marketplace.visualstudio.com/items?itemName=donjayamanne.githistory, Please file the issue against this extension.
