### ISSUE TITLE
Display file while moving with arrows in the explorer

### ISSUE THREAD

**Issue by dfroze** [Microsoft/vscode#17682]
- VSCode Version: 1.8.1
- OS Version: Linux

There is a feature from sublime, when selecting a file in the sidebar (click only once) and then by using the arrows to navigate to the next file displayed in the sidebar, the content of the file changes the next instant. In vscode you need to press enter after focusing on the file.
This is really helpful when wanting to check small thing in many files. Especially in git diff, if there are small changes you can navigate fast just with the arrows.

**Comment by mlewand** [comment]
If you implement this feature make sure it's an opt-in. I can see how someone can like this feature, but for me as keyboard-only user this feature is very distracting.
