### ISSUE TITLE
How do I specify a debugger if there are multiple debuggers of the same type?

### ISSUE THREAD

**Issue by thqby** [microsoft/vscode#176887]
If you have multiple debuggers installed, but they are of the same type `package.json contributes.debuggers[0].type`, how do you specify to run one?

**Comment by roblourens** [comment]
I think the contributions would actually be merged. Is this a real problem that you're running into?

**Comment by thqby** [comment]
Yes, I installed two extensions for the language I'm currently using, one that includes language support and a debugger, and one that is just a debugger. Because both debuggers have the same type, one is overwritten. Although the current situation is what I want, I want to know if it can be avoided.

**Comment by roblourens** [comment]
If those debuggers are intended to be independent, then maybe the extension authors can coordinate between themselves. I don't have a better answer unfortunately.
