### ISSUE TITLE
VS Code on Mac OS ARM fails to debug Angular Apps (SWA)

### ISSUE THREAD

**Issue by Arash-Sabet** [microsoft/vscode#176850]
Does this issue occur when all extensions are disabled?: Yes/No (does not apply)

- VS Code Version: 1.76.1 - Commit: 5e805b79fcb6ba4c2d23712967df89a089da575b
- OS Version: Darwin arm64 22.3.0

Steps to Reproduce:

1. Create an angular app and use the following launch.json file:

```json
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "type": "chrome",
            "request": "launch",
            "name": "Launch Chrome against localhost",
            "url": "http://localhost:8080",
            "webRoot": "${workspaceFolder}"
        },
        {
            "name": "SWA: Run MyNgApp",
            "request": "launch",
            "type": "pwa-chrome",
            "url": "http://localhost:4280",
            "preLaunchTask": "swa: start MyNgApp",
            "webRoot": "${workspaceFolder}/",
            "timeout": 30000
        }
    ]
}
```
2. Start debugging the application in VS Code, and you will see that Chrome launches, but the application fails to load in Chrome, and hence the app cannot be debugged.

The output pane shows the following error message:

> Error: the task 'swa: start MyNgApp' neither specifies a command nor a dependsOn property. The task will be ignored. Its definition is:
{
    "type": "shell",
    "id": "shell,swa,start,http://localhost:4200,--run,npm start,--devserver-timeout=90000,",
    "problemMatcher": [
        "$swa-watch"
    ],
    "label": "swa: start MyNgApp"
}

The terminal displays the following information:

> ** Angular Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200/ **
[run] 
[run] 
[run] ✔ Compiled successfully.
[swa] GET http://localhost:4280/ - 304
[swa] GET http://localhost:4200/assets/forms.css (proxy)
[swa] GET http://localhost:4200/styles.css (proxy)
[swa] GET http://localhost:4200/runtime.js (proxy)
[swa] GET http://localhost:4200/vendor.js (proxy)
[swa] GET http://localhost:4200/main.js (proxy)
[swa] GET http://localhost:4200/polyfills.js (proxy)
[swa] GET http://localhost:4280/assets/forms.css - 304
[swa] GET http://localhost:4280/styles.css - 304
[swa] GET http://localhost:4280/runtime.js - 304
[swa] GET http://localhost:4280/vendor.js - 304
[swa] GET http://localhost:4280/main.js - 304
[swa] GET http://localhost:4280/polyfills.js - 304
[swa] GET http://localhost:4200/styles.js (proxy)
[swa] GET http://localhost:4280/styles.js - 304
[swa] GET http://localhost:4200/runtime.js.map (proxy)
[swa] GET http://localhost:4280/runtime.js.map - 200

---
Further details:

- The latest version of SWA installed.
- This issue does not happen on Windows 11

**Comment by teamoo** [comment]
Having the same problem with an existing app that could be launched before.

**Comment by negyxo** [comment]
I have the same issue but it is react app on M1. If I use debug for Firefox (launch it) it works. Seems something broke debugger.

**Comment by connor4312** [comment]
Duplicates https://github.com/microsoft/vscode/issues/167353. Passing `--host=127.0.0.1` to `ng serve` should fix the issue.

**Comment by Roitr** [comment]
@connor4312 I also have this issue, and i was already passing the --host=127.0.01 parameter before the issue started. 
On Thursday it was working fine, and today (Sunday) i'm no longer able to debug.

I can still debug with chrome devtools so althoug it's not as comforatble, I can still work untill the issue is resolved.

**Comment by Arash-Sabet** [comment]
> @connor4312 I also have this issue, and i was already passing the --host=127.0.01 parameter before the issue started. 
> 
> On Thursday it was working fine, and today (Sunday) i'm no longer able to debug.
> 
> 
> 
> I can still debug with chrome devtools so althoug it's not as comforatble, I can still work untill the issue is resolved.

Could you please share the details on how you made it work using chrome devtools? I tried it but no luck?

**Comment by crechberger** [comment]
Same issue, the workaround does not solve it.

**Comment by Roitr** [comment]
@Arash-Sabet A configuration that works for me (i had to switch to use edge instead of chrome):
in my launch.json => configurations i have this:
```
{
      "name": "Launch Edge",
      "request": "launch",
      "type": "msedge",
      "preLaunchTask": "npm: start",
      "url": "http://localhost:4200/#",
      "webRoot": "${workspaceFolder}"
    },
```

In tasks.json i have this task:
  ```
{
        "type": "npm",
        "isBackground": true,
        "script": "start",
        "problemMatcher": [
          {
            "pattern": [
              {
                "regexp": ".",
                "file": 1,
                "location": 2,
                "message": 3
              }
            ],
            "background": {
              "activeOnStart": true,
              "beginsPattern": ".",
              "endsPattern": ".",
            }
          }
        ]
      },
```
notice the  `"script": "start"` - this is a script defined in `"Scripts"` section of the  `package.json`, which is:

`"start": "npm run ng -- serve --host=127.0.0.1",`

Now I can simply press F5 (or the green arrow button), and it immediately launches Edge, and runs the script at the same time. When it finishes compiling and serving, the browser refreshes, and the debugger is attached.

**Comment by Arash-Sabet** [comment]
Thank you very much @Roitr! Your post helped a lot!

**Comment by Arash-Sabet** [comment]
@Roitr Everything is now broken with the recent release of Azure Static Web App CLI (ver 1.1.0). No longer able to debug the app in Edge too.
