### ISSUE TITLE
Using the define keybinding button breaks in conjnction with \ character

### ISSUE THREAD

**Issue by cdodge89** [Microsoft/vscode#17688]
- VSCode Version: 1.8.1
- OS Version: OSX El Capitan

Steps to Reproduce:

1. On Mac open Code>Preferences>Keyboard Shortcuts
2. Click the Blue "Define Keybinding" Button in the bottom right hand corner
3. Define a keybinding that ends with the \ character such as ctrl+alt+cmd+\
4. Notice that the \ character is not properly escaped, and instead escapes the last " character in the object that is added to keybindings.json, causing the strings to not be recognized correctly.

**Comment by alexandrudima** [comment]
Fixed via PR #21969

**Comment by jrieken** [comment]
When binding <kbd>Cmd+\</kbd> via the UI I end up with an invalid keybinding because the backslash seems to be double espaced

```json
    {
        "key": "cmd+\\\\",
        "command": "editor.emmet.action.incrementNumberByTen"
    }
```
![mar-30-2017 12-07-58](https://cloud.githubusercontent.com/assets/1794099/24499319/8f9eb14a-1541-11e7-9b77-ab427a3e1e5e.gif)

**Comment by alexandrudima** [comment]
This works in the "classic" experience:

![slash](https://cloud.githubusercontent.com/assets/5047891/24500182/a73f63aa-1544-11e7-8c0c-c93c6696719c.gif)
