### ISSUE TITLE
Explorer missing

### ISSUE THREAD

**Issue by iUnstable0** [microsoft/vscode#176886]
Does this issue occur when all extensions are disabled?: Yes/No
Yes

- VS Code Version: Both latest vscode stable and vscode insiders (Mac arm64)
- OS Version: Latest ventura 

Steps to Reproduce:

1. Just open vscode?
2. Explorer missing from the sidebar

My vscode file explorer is missing
![CleanShot 2023-03-12 at 13 26 10](https://user-images.githubusercontent.com/46888825/224528244-646f286e-6878-49ea-9490-0810962a5867.png)

I tried reinstalling, still missing.
Even on the insiders build still missing (after i turned on settings sync)
its missing on my laptop aswell

**Comment by gjsjohnmurray** [comment]
Please see #176757 or #176446 for suggestions.

**Comment by iUnstable0** [comment]
THank you so much! It was hiding under source control and reset location fixed it ❤️
