### ISSUE TITLE
package description should skip badges in package.json

### ISSUE THREAD

**Issue by tjx666** [microsoft/vscode#176838]
Does this issue occur when all extensions are disabled?: Yes/No

Yes.

Note, this issue only happen with package which has not `description` field in package.json, seems in this case, vscode will read README first head to get description.

Steps to Reproduce:

1. open package.json
2. hover on `@vscode/test-electron`

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/41773861/224470337-65081e58-9a7d-44ab-9ea8-56a9897ca29d.png">

```
Version: 1.76.1 (Universal)
Commit: 5e805b79fcb6ba4c2d23712967df89a089da575b
Date: 2023-03-08T16:32:09.831Z
Electron: 19.1.11
Chromium: 102.0.5005.196
Node.js: 16.14.2
V8: 10.2.154.26-electron.0
OS: Darwin x64 22.3.0
Sandboxed: No
```

**Comment by meganrogge** [comment]
Lmk if this still reproduces
