### ISSUE TITLE
Remote - SSH doesn't connect

### ISSUE THREAD

**Issue by prager** [microsoft/vscode#176809]
Type: <b>Bug</b>

Cannot connect remotely using VS Code via SSH in Linux Mint. Connecting to the remote server via SSH using Terminal works.

I am using Remote-SSH extension.

At first I tried to connect the same way as in terminal providing the host and password and also as per the VS Code docs [Connect Using SSH.](https://code.visualstudio.com/docs/remote/ssh-tutorial#_connect-using-ssh) 

That didn't work in VS Code, the green status box on bottom left would spin with "Opening Remote..." message while the left pane displayed "Connected to remote" with blue button "Open Folder", which would not do anything. The only way to get out of the infinite "Opening Remote..." mode would be to "Close remote connection" when clicking the green status box.

Then followed this article [How Using VSCode SSH Key to connect to remote Linux host ?](https://www.linkedin.com/pulse/how-using-vscode-ssh-key-connect-remote-linux-host-soheil-amiri)

...and it didn't fix it either resulting in the same blue button in the left pane and asking for a password in infinite loop. Only closing remote connection would stop this.

More here:  https://stackoverflow.com/questions/75690520/ssh-remote-connection-in-vs-code-will-not-connect

VS Code version: Code 1.76.1 (5e805b79fcb6ba4c2d23712967df89a089da575b, 2023-03-08T16:31:31.010Z)
OS version: Linux x64 5.15.0-67-generic
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 5500 (12 x 4249)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|0, 0, 0|
|Memory (System)|62.59GB (55.25GB free)|
|Process Argv|--unity-launch --crash-reporter-id a5c163b8-cc6a-4625-bddd-62c844217833|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|cinnamon|
|XDG_CURRENT_DESKTOP|X-Cinnamon|
|XDG_SESSION_DESKTOP|cinnamon|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-pull-request-github|Git|0.60.0
remote-ssh|ms-|0.98.0
remote-ssh-edit|ms-|0.84.0
remote-explorer|ms-|0.2.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
pynewext54:30681850
azure-dev_surveyone:30548225
vscccc:30610679
pyindex848:30662994
nodejswelcome1cf:30587006
3biah626:30602489
pyind779:30671433
f6dab269:30613381
pythonsymbol12:30671437
a9j8j154:30646983
showlangstatbar:30672706
vsctsb:30677850
funwalk2:30682974

```

</details>

**Comment by prager** [comment]
I edited my original entry for better accuracy after I went back and tried to connect again with the same result.

**Comment by roblourens** [comment]
Please file this on https://github.com/microsoft/vscode-remote-release/issues/new?assignees=eleanorjboyd&labels=ssh&template=a_remote_ssh_bug_form.yml&title=%5BRemote-SSH+Bug%5D%3A+, following the template. It has some helpful troubleshooting steps or will at least help you collect logs for us, thanks
