### ISSUE TITLE
Terminal should linkify line numbers for TypeScript errors.

### ISSUE THREAD

**Issue by prideout** [microsoft/vscode#176867]
Error messages of the following format are linkified, but the line and column numbers are not honored when doing ⌘+Click.  This is surprising because TypeScript is supported extremely well out of the box.

```
Foo.bar.stories.tsx(78,5): error TS2741: Property 'opacity' is missing in type '{ hello: number; }'
```

**Comment by Tyriar** [comment]
Looks like this was fixed in the link changes coming in the next version:

![image](https://user-images.githubusercontent.com/2193314/227658458-8e7e6f45-effa-4292-8f73-3759c9f0a503.png)
