### ISSUE TITLE
Auto-update disabling is not working

### ISSUE THREAD

**Issue by jimhucksly** [microsoft/vscode#176888]
- VS Code Version:  1.76.1
- OS Version:  Windows 10 Pro 21H2 build 19044.2604

Steps to Reproduce:

1. install any previously version, for example - 1.75
2.  set parameter in settings.json - "update.mode": "none"
3. close application
4. open application
5. vs code is updating to last version 1.76.1

**Comment by urucoder** [comment]
This issue is also affecting version 1.74.3

**Comment by joaomoreno** [comment]
Once you start VS Code with `update.mode` set to `none`, what's the `Main` output first lines? This is what I see:

<img width="809" alt="image" src="https://user-images.githubusercontent.com/22350/224750578-b0a8296e-ac91-45d3-9f5a-578699a26c60.png">

**Comment by urucoder** [comment]
In my case, I'm using update.mode = "manual", the output is the following:

> [info] update#ctor - manual checks only; automatic updates are disabled by user preference

**Comment by jimhucksly** [comment]
i confirm, terminal outputs the following line:
`2023-03-13 22:47:58.315 [info] update#ctor - updates are disabled by user preference`
but, auto-updates actually is enabled, besause after restart of vs code, i see window with release notes by version 1.76

**Comment by joaomoreno** [comment]
Something else in your system must be updating VS Code. The log indicate that updates are disabled from within the app.

**Comment by urucoder** [comment]
@joaomoreno It would be nice if you could help us to determine what is updating vs code anyway, given we're at least 2 different users facing the same issue and I didn't configure anything specific for that. Could you suggest where we can take a look? any log or something that could hint at what is causing the issue? thanks

**Comment by joaomoreno** [comment]
Is this an enterprise managed machine? If so, reach out to your systems administrator.

**Comment by jimhucksly** [comment]
Beatifull! You've close issue without a solution

**Comment by jimhucksly** [comment]
> Is this an enterprise managed machine? If so, reach out to your systems administrator.

No! its my home machine
