### ISSUE TITLE
curl latest VSCodeSetup-x64.exe and VSCode-darwin-arm64.zip file

### ISSUE THREAD

**Issue by kgfly** [microsoft/vscode#176847]
(Similar to question in https://github.com/Microsoft/vscode/issues/15529)

This is not a bug but more a question of how to download the latest VSCodeSetup-x64.exe via command line in Windows, using curl

I think the command should be: curl -L -O http://go.microsoft.com/fwlink/?LinkID=XXXXX

But where to find XXXXX? Thanks.

**Comment by AnrDaemon** [comment]
The command should be
`wget --content-disposition 'https://code.visualstudio.com/sha/download?build=stable&os=win32-x64'`
But the back-end is not available right now, it seems.

**Comment by kgfly** [comment]
wget is not avaiable on Win11 by default. May you please share the link which works with curl?

_curl -L -O https://code.visualstudio.com/sha/download?build=stable&os=win32-x64_

does not work for me

**Comment by AnrDaemon** [comment]
curl does not read the content-disposition header. The results would not be useful.

**Comment by AnrDaemon** [comment]
https://update.code.visualstudio.com/latest/win32-x64/stable

**Comment by kgfly** [comment]
Thanks. Above works.

One more Q: may you please also provide the download link of VSCode-darwin-arm64.zip which works curl on Macbook arm ?

Thanks

**Comment by joaomoreno** [comment]
https://code.visualstudio.com/docs/supporting/faq#_previous-release-versions

You can use `latest` where there is `{version}`.
