### ISSUE TITLE
Webviews are not clickable in insiders.vscode.dev

### ISSUE THREAD

**Issue by TylerLeonhardt** [microsoft/vscode#176807]
Steps to Reproduce:

1. open a PR in insiders.vscode.dev or open a Notebook and run some cells
2. try to interact with the webview or output

I can't click on anything inside.

I only have these extensions activated:
![image](https://user-images.githubusercontent.com/2644648/224387255-030729f9-3b5e-41d5-a9cd-88f25c002686.png)

**Comment by mjbvz** [comment]
What browser and OS?

**Comment by TylerLeonhardt** [comment]
Edge Dev, macOS... can't seem to repro anymore. A restart fixed it. It felt like this happened after the 1.76 release

**Comment by mjbvz** [comment]
If this happens again, please try inspecting the iframe area first to make sure there is no invisible element on top of it

If it still isn't working, try disabling the sleeping tabs feature in Edge. I wonder if that could be putting the iframe to sleep and then failing to revive it

**Comment by harbin1053020115** [comment]
I have same issue. I added a webview next to the explorer view, and the webview cannot be clickable. I have inspect the dom Elements, and there is no elements on top of it.
![image](https://user-images.githubusercontent.com/2869750/225303749-3c741c62-3658-4315-a925-8de28fa96122.png)
![cannot-click-webview-in-vscode](https://user-images.githubusercontent.com/2869750/225304305-c022a2fe-c750-4fb5-add5-d6a14da315d7.gif)

**Comment by ilovejcm** [comment]
same to me. on Chrome 111.0.5563.64 , macOS.  restart  browser may help and there is no invisible element on top of it

**Comment by harbin1053020115** [comment]
Even cannot use chrome's inspect tool to inspect the webview element:
![Mar-15-2023 20-12-54](https://user-images.githubusercontent.com/2869750/225305874-d1455d87-1bf0-4947-874a-0fc8c5bf1fe6.gif)

**Comment by yiliang114** [comment]
By the way, when the problem occurs, after the browser is completely exited and then reopen it, there is a certain probability to solve the problem. @mjbvz

**Comment by ilovejcm** [comment]
this may happen when vscode itself on one domain (like https://www.a.com) but extension's  iframe on another domain( both extension and webview,  like https://www.b.com). @mjbvz
