### ISSUE TITLE
WSL 2 Permission Denied even as Administrator on Windows 11

### ISSUE THREAD

**Issue by bionicles** [microsoft/vscode#176815]
Type: <b>Bug</b>

1. Create an Ubuntu WSL 2 Drive on a clean install of windows 11
2. Run VS Code
3. Try to create a folder / file on your own WSL drive
*permission denied*
4. Run VS Code as Administrator (shouldn't be necessary)
5. Try to create a folder / file on your own WSL drive
*permission denied*

Solutions attempted: I chown'd the files in WSL to be owned by my user and not by root. Still doesnt work. What gives? Why can't VS Code and WSL 2 *JUST WORK* in 2023?

Windows 11 is literally unusable for dev work if I can't use VS Code with WSL... How the heck does VS Code work better on Linux and Mac than it does on Windows? This is ridiculous

VS Code version: Code 1.76.1 (5e805b79fcb6ba4c2d23712967df89a089da575b, 2023-03-08T16:32:00.131Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: Yes
Remote OS version: Linux x64 5.15.90.1-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|13th Gen Intel(R) Core(TM) i9-13900K (32 x 2995)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|63.78GB (38.87GB free)|
|Process Argv|--crash-reporter-id 755bcb5f-6bc6-4e68-9204-16b6fb042aa3|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 5.15.90.1-microsoft-standard-WSL2|
|CPUs|13th Gen Intel(R) Core(TM) i9-13900K (32 x 2995)|
|Memory (System)|31.23GB (30.14GB free)|
|VM|0%|
</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
jupyter-keymap|ms-|1.1.0
remote-wsl|ms-|0.76.1
atom-keybindings|ms-|3.3.0
vscode-autohotkey-plus-plus|mar|3.2.0
python|ms-|2023.4.1
vscode-pylance|ms-|2023.3.20
jupyter|ms-|2023.2.1200692131
jupyter-keymap|ms-|1.1.0
jupyter-renderers|ms-|1.0.15
vscode-jupyter-cell-tags|ms-|0.1.6
vscode-jupyter-slideshow|ms-|0.1.5
google-search|Rav|1.0.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscorecescf:30445987
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
pynewvextcfv2:30681851
azure-dev_surveyone:30548225
vscccc:30610679
pyindex848:30662994
nodejswelcome1:30587005
2e4cg342:30602488
pyind779:30671433
f6dab269:30613381
pythonsymbol12:30671437
6233i204:30672705
vsctsb:30677850
funwalk2cf:30682975
pythonms35:30680984

```

</details>

**Comment by bionicles** [comment]
Also, unclear why there are 2 different Ubuntu options to choose from when I only installed WSL 2 once. 
![Screenshot 2023-03-10 131034](https://user-images.githubusercontent.com/24532336/224393630-75397396-68ae-4e11-9c92-8ea31efab7ae.png)
![Screenshot 2023-03-10 130732](https://user-images.githubusercontent.com/24532336/224393640-becfea51-0624-41f6-b32f-b4ba50b4d85f.png)

**Comment by bionicles** [comment]
Also tried running `code .` from both versions of ubuntu in terminal, still can't do CRUD on WSL from Code

**Comment by bionicles** [comment]
Hmm, maybe i'm just too smooth-brain, i guess i missed a spot with chown-ing everything in WSL from root to my user.  I went back and did `chown bion hax` on my `hax` folder and subfolders and now it works. Weird because I already did that -- not sure why I needed to redo it. Could the file system re-assign ownership of WSL2 data to root for some reason?

**Comment by aeschli** [comment]
The WSL extension just runs the `wsl` command with the default user to run the VS Code back-end in it. It doesn't do anything with permissions etc.
This looks like a WSL setup issue. Can you file an issue against https://github.com/microsoft/WSL ?
