### ISSUE TITLE
Hot Exit forgets language mode for unsaved files

### ISSUE THREAD

**Issue by technomaz** [Microsoft/vscode#17681]
- VSCode Version: 1.8.1
- OS Version: Windows 10

Steps to Reproduce:

1. File > New File
2. Select Language Mode > Change to HTML (or whatever)
3. Make any edits to file
4. Quit VSCode
5. Open VSCode

The Untitled-1 file reopens, but the Language Mode is reset to Plain Text.  VSCode should remember the Language Mode that was set.

**Comment by egamma** [comment]
Duplicates #16803
