### ISSUE TITLE
Freezing on update / install

### ISSUE THREAD

**Issue by db001** [Microsoft/vscode#17683]
- VSCode Version: 1.6.1
- OS Version: Win 10 pro

Steps to Reproduce:

1.  New Install from download
2.  Click "Update Now" on pop up in program

When I click the update now pop up it takes me to the 'Preparing to Install' dialog box and freezes.  No dialog appears in the box and hovering over it only shows the windows loading cursor.  Only way to close the box is through task manager.  The same happens if I download the latest version and try to install that way.

**Comment by joaomoreno** [comment]
Do you have any antivirus installed? Does it reproduce if you disable it temporarily?

**Comment by db001** [comment]
Apologies for the delay in replying.  Yes I have Panda Global Protection installed and disabling it enabled the update to work without a problem.  Thanks.
