### ISSUE TITLE
Saving files is so slow

### ISSUE THREAD

**Issue by IchinoseMeguri** [microsoft/vscode#176896]
Type: <b>Performance Issue</b>

When I finish a file and I press down "Ctrl+S", it always takes about 1 second to save the file. It is so slow, and the problem appears recently.

VS Code version: Code 1.76.1 (5e805b79fcb6ba4c2d23712967df89a089da575b, 2023-03-08T16:32:00.131Z)
OS version: Windows_NT x64 10.0.22624
Modes: Unsupported
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.85GB (8.22GB free)|
|Process Argv|--crash-reporter-id fae90c69-b428-49de-979b-db1c52303a0e|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	   146	  7640	code main
    0	   128	  1764	   shared-process
    0	    93	  3656	     fileWatcher
    0	    84	 17520	     ptyHost
    0	    46	  5392	   utility-network-service
    0	   275	  5908	   window (Register.vue - frontend - Visual Studio Code)
    0	   154	 16840	   gpu-process
    0	    27	 18052	   crashpad-handler
    0	    98	 19212	   issue-reporter
    0	   165	 19236	   utility-process
    0	   126	  8880	     electron-nodejs ("D:\Microsoft VS Code\Code.exe" --ms-enable-electron-run-as-node c:\Users\1577719837\.vscode\extensions\vue.volar-1.2.0-win32-x64\server.js --node-ipc --clientProcessId=19236)
    0	   193	 10220	     electron-nodejs ("D:\Microsoft VS Code\Code.exe" --ms-enable-electron-run-as-node c:\Users\1577719837\.vscode\extensions\vue.volar-1.2.0-win32-x64\server.js --node-ipc --clientProcessId=19236)
    0	   111	 11532	     electron-nodejs ("D:\Microsoft VS Code\Code.exe" --ms-enable-electron-run-as-node c:\Users\1577719837\.vscode\extensions\streetsidesoftware.code-spell-checker-2.19.0\packages\_server\dist\main.js --node-ipc --clientProcessId=19236)
    0	    88	 15520	     electron-nodejs ("D:\Microsoft VS Code\Code.exe" --ms-enable-electron-run-as-node c:\Users\1577719837\.vscode\extensions\formulahendry.auto-rename-tag-0.1.10\packages\server\dist\serverMain.js --node-ipc --clientProcessId=19236)
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (Register.vue - frontend - Visual Studio Code)
|    Folder (frontend): 19 files
|      File types: json(3) svg(2) vue(2) js(2) gitignore(1) html(1) md(1)
|                  css(1)
|      Conf files: package.json(1);
```

</details>
<details><summary>Extensions (41)</summary>

Extension|Author (truncated)|Version
---|---|---
project-manager|ale|12.7.0
vscode-eclipse-keybindings|alp|0.16.1
auto-rename-tag|for|0.1.10
code-runner|for|0.12.0
better-cpp-syntax|jef|1.17.2
eclipse-new-java-project|mel|1.0.1
vscode-language-pack-zh-hans|MS-|1.76.2023030809
csharp|ms-|1.25.4
isort|ms-|2022.8.0
python|ms-|2023.4.1
vscode-pylance|ms-|2023.3.20
remote-containers|ms-|0.282.0
remote-ssh|ms-|0.98.0
remote-ssh-edit|ms-|0.84.0
remote-wsl|ms-|0.76.1
cmake-tools|ms-|1.13.45
cpptools|ms-|1.14.4
cpptools-extension-pack|ms-|1.3.0
remote-explorer|ms-|0.2.0
korofileheader|OBK|4.9.3
material-icon-theme|PKi|4.24.0
java|red|1.15.0
code-spell-checker|str|2.19.0
cmake|twx|0.0.17
intellicode-api-usage-examples|Vis|0.2.7
vscodeintellicode|Vis|1.2.30
vscode-boot-dev-pack|vmw|0.2.1
vscode-spring-boot|vmw|1.44.0
vscode-java-debug|vsc|0.49.0
vscode-java-dependency|vsc|0.21.1
vscode-java-pack|vsc|0.25.8
vscode-java-test|vsc|0.38.1
vscode-maven|vsc|0.40.4
vscode-spring-boot-dashboard|vsc|0.11.2023030400
vscode-spring-initializr|vsc|0.11.2
volar|Vue|1.2.0
vscode-typescript-vue-plugin|Vue|1.2.0
vue|Wsc|1.0.26
JavaScriptSnippets|xab|1.8.0
markdown-all-in-one|yzh|3.5.0
material-theme|zhu|3.15.8

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vscaac:30438847
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30681850
azure-dev_surveyone:30548225
pyindex848:30662994
nodejswelcome1cf:30587006
282f8724:30602487
pyind779:30671433
89544117:30613380
pythonsymbol12:30671437
a9j8j154:30646983
vsccsb:30677849
pythonb192cf:30669361
funwalk2:30682974
pythonms35cf:30680985

```

</details>

**Comment by gjsjohnmurray** [comment]
Please use the Start Extension Bisect command to investigate whether the issue is being caused by one of your extensions.

**Comment by duanlvxin** [comment]
This may be helpful for you:
https://github.com/vuejs/vetur/issues/3650

**Comment by IchinoseMeguri** [comment]
Problem is solved. There is something wrong with a extension.
