### ISSUE TITLE
Debugger seems to have issues with the last character in locals

### ISSUE THREAD

**Issue by yuheng305** [microsoft/vscode#176892]
I'm using VS Code and encountering an issue with debugging. In the local section of the variables, it seems that every string is missing its last character. I've tried several approaches, such as reinstalling VS Code, disabling extensions, or checking the configuration, but none of them seem to solve the issue.

Can someone help me identify what this problem is and suggest a way to fix it? Any help would be greatly appreciated.
![image](https://user-images.githubusercontent.com/118244757/224543832-6e89fca6-9373-47e8-bef7-fd0861269dd0.png)

**Comment by roblourens** [comment]
Please file this on the c++ debug extension, thanks
