### ISSUE TITLE
Feature Request: Preview changes of CodeAction before applying them

### ISSUE THREAD

**Issue by Krzysztof-Cieslak** [Microsoft/vscode#17695]
VS provides preview panel for its CodeActions showing diff of the file. Here's the sample:

![](https://cloud.githubusercontent.com/assets/873919/21400336/a97b90d4-c7c0-11e6-9002-39cb972d1bf3.gif)

I wonder if we could get something like that in Code :)

**Comment by forki** [comment]
:kiss:

**Comment by tamizhvendan** [comment]
+1

**Comment by egamma** [comment]
FYI @jrieken

**Comment by jrieken** [comment]
Tricky - in our API a code action is just any command and not necessarily a text edit, like fetch `d.ts` file etc. We should extend the API to return something more specific, like a WorkspaceEdit with a label. That would allow us to show a preview then

**Comment by jrieken** [comment]
This feature request will not be considered in the next [6-12 months roadmap](https://github.com/Microsoft/vscode/wiki/Roadmap) and as such will be closed to keep the number of issues we have to maintain actionable. Thanks for understanding and happy coding!
