### ISSUE TITLE
Large file working copy handling on web

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode#176993]
In the latest pre-release of GitHub Repositories, we support committing files via LFS: https://github.com/microsoft/vscode-remote-repositories-github/issues/7. This means GitHub Repositories (and soon vscode.dev) will become a zero-configuration Git LFS-capable client, which will make it easier to edit and commit to e.g. `microsoft/vscode-docs` without error (forgetting to install and set up LFS locally).

Currently, the likely workflows that users will use are:
1. the `Upload...` action from the explorer context menu to upload a file, then commit via SCM view
2. paste from clipboard into a markdown file, rename file if necessary, then commit via SCM view

In both these workflows, the user must first create a working copy in the workspace (managed by GitHub Repositories as an entry in IndexedDB via the extension context's global storage location and VS Code FS APIs) before committing. The problem with this is that we would store the full working copy of the file in the browser, and browsers are subject to unknown and potentially severe [storage limitations](https://developer.mozilla.org/en-US/docs/Web/API/IndexedDB_API/Browser_storage_limits_and_eviction_criteria#storage_limits). It seems quite likely that a user might unintentionally exhaust their browser storage limit in this way. Specifically:
- FireFox browsers are limited to 50% of disk storage
    - a domain group (both vscode.dev and insiders.vscode.dev are one group) may use 20% of this global limit
- There are [separate limits](https://chromium.googlesource.com/chromium/src/+/refs/heads/master/storage/browser/quota/quota_settings.cc#68) for Chrome and it is possible to have a quota of 0

Note that this problem also occurs if a user happens to be editing a large file in vscode.dev with GitHub Repositories that is not LFS-tracked, so the problem is not LFS-specific and already exists today.

----------------------------------

One suggestion was to implement some form of streaming upload gesture in the SCM view which would immediately commit and push an LFS file to the remote repository, bypassing having to write an LFS file to browser storage and only then commit it to the remote. However, this is incompatible with workflow number 2 above, which is a smooth workflow for adding both an image and a markdown link reference in one gesture, and is less natural as well. There are also UX issues, e.g. we would prompt the user for a commit message before making the commit.

I'm filing this issue to discuss how we can ensure that users who edit large files in vscode.dev with GitHub Repositories do not accidentally run out of browser storage. In particular:
- Do we need a special setting on web for file size limits that is more conservative than the limit in desktop?
- Do we handle the `QuotaExceededError` which is thrown when an origin exhausts the group origin policy even after group origin eviction has occurred? At minimum we should provide an error message, we can also suggest Reopen in Desktop with GitHub Repos which will at least circumvent the browser-imposed limit
    > Note: If the group limit is exceeded, or if origin eviction couldn't free enough space, the browser will throw a QuotaExceededError.

**Comment by joyceerhl** [comment]
Ben, I assigned you to start because I see you are involved in related discussions https://github.com/microsoft/vscode/issues/172129 and https://github.com/microsoft/vscode/issues/167719, please let me know if I should reach out to someone else!

**Comment by sandy081** [comment]
Yes this has to be handled by the FSP. 

@bpasero May I know what is expected when there is not enough space on the disk for the FSP to write. For eg., what does node does in this cas?

**Comment by bpasero** [comment]
Node.js will throw an error, probably directly passing it through from the lower level OS call. It is up to the caller of the method how to deal with the error.

**Comment by joyceerhl** [comment]
@bpasero that setting is only observed for opening files today, would it make sense to observe it in the `Upload` action as well?

**Comment by bpasero** [comment]
I am not sure, the setting is really only for editors opening, not so much general file IO transfer limitations. The original intent was to limit the possible network cost opening a large editor could have by accident because we immediately open a file when you click it. The setting is also called `workbench.editorLargeFileConfirmation`.

I think the file system provider should stat the file and refuse to do the operation if the available space is known to be exceeded

**Comment by joyceerhl** [comment]
That makes sense. I think we can use [`navigator.storage.estimate`](https://developer.mozilla.org/en-US/docs/Web/API/StorageManager/estimate)--sadly Safari does not support. I am not sure how the performance of this API holds up though.

https://github.com/microsoft/vscode/blob/549d31a5d58387f68c38e053eb8e99e4288006bd/src/vs/platform/files/browser/indexedDBFileSystemProvider.ts#L284-L295

would instead be
```ts
async writeFile(resource: URI, content: Uint8Array, opts: IFileWriteOptions): Promise<void> {
	try {
		const existing = await this.stat(resource).catch(() => undefined);
		const estimated = await navigator?.storage?.estimate?.();
		const memoryLimit = (estimated?.quota ?? 0) - (estimated?.usage ?? 0);
		if (existing?.type === FileType.Directory) {
			throw ERR_FILE_IS_DIR;
		} if ((existing?.size ?? 0) > memoryLimit) {
			throw ERR_FILE_EXCEEDS_MEMORY_LIMIT;
		}
		await this.bulkWrite([[resource, content]]);
	} catch (error) {
		this.reportError('writeFile', error);
		throw error;
	}
}
```

**Comment by bpasero** [comment]
Sure, feel free to open a PR, maybe consult with @sandy081 who I think owns this provider.
