### ISSUE TITLE
Extensions need a proper way to retrieve the current language setting, to be used where `vscode-nls-dev` cannot be

### ISSUE THREAD

**Issue by Colengms** [microsoft/vscode#176995]
A good explanation of the problem can be found here: https://github.com/microsoft/vscode-cpptools/issues/10632

In the C/C++ extension, we need to be able to retrieve the current language ID to use for localization, for scenarios in which `vscode-nls-dev` and `vscode-nls` are not an option.  Two examples include:
 * To select localized strings in existing native components with their own localization system, such as the IntelliSense engine used in the C/C++ Extension.
 * To use [the recommended approach](https://github.com/microsoft/vscode/issues/78737) for localizing the content of schema files.
 
Previously this value could be retrieved from `VSCODE_NLS_CONFIG`, but that is no longer supported: https://github.com/microsoft/vscode/issues/78392

**Comment by TylerLeonhardt** [comment]
Yeah we basically changed the meaning of that to be:

* `locale`: the locale of the machine
* `availableLanguages['*']`: the language the client is _actually_ using

**Comment by TylerLeonhardt** [comment]
Also, `vscode.env.language` is the correct way of getting it in the extension host... which can then be passed down to sub processes

**Comment by Colengms** [comment]
Note that we are currently using the exact same logic used by `vsscode-nls`, and expecting the exact same format that of locale identifiers.  If `vscode.env.language` does not match that exactly, then we will see a difference between the languages used by the components of our extension that are able to use `vscode-nls`, and the ones that are not.  The primary reason we clarifying the officially supported approach, is to make it squarely the responsibility of VS Code when these languages do not match.  Though, users currently experiencing this issue are likely experiencing existing issues with VS Code itself - such providing us a locale ID that we have strings for but for which the language pack is missing.  (resulting in us using the 'correct' language, while VS Code does not.)

**Comment by TylerLeonhardt** [comment]
I have reverted that changes that changed this behavior... this should be fixed now with: https://github.com/microsoft/vscode/pull/177426
