### ISSUE TITLE
[Windows] Shift+click in task bar does not open new window

### ISSUE THREAD

**Issue by AshleyScirra** [Microsoft/vscode#17694]
- VSCode Version: Code 1.8.1 (ee428b0eead68bf0fb99ab5fdc4439be227b6281, 2016-12-19T14:49:23.350Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

On Windows 10 64-bit.

1. Open VS Code
2. Hold shift and click VS Code in the task bar

Expected result: new VS Code window opens (as per usual Windows shortcut)
Observed result: nothing happens

This is annoying if you have a folder open in one window, and another window showing another file (e.g. to compare/for reference). If you close the folder-based window, you can't open it again until you close all other windows, or replace the existing window, which you then have to open again afterwards.

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/13905
