### ISSUE TITLE
Test gutter icons are duplicated across lines when new content is added

### ISSUE THREAD

**Issue by DanTup** [microsoft/vscode#176951]
Using the test-provider-sample, adding newlines on a line marked as a test duplicates the test icon:

![Mar-13-2023 10-50-07](https://user-images.githubusercontent.com/1078012/224680686-ef418937-9ce7-494f-9450-9ce9761cac97.gif)

It sorts itself out on the next update (at least in the sample, I'm still investigating https://github.com/Dart-Code/Dart-Code/issues/4384 to figure out if there's another issue, or that's in my extension). But it still looks bad - especially if a language is debouncing edits and/or discovery may be slow..

You can make the issue more pronounced (as I did for the GIF) by updating the test-provider-sample to have a delay in its updates:

```
		// simulate a delay
		setTimeout(() => data.updateFromContents(ctrl, e.getText(), file), 5000);
```

**Comment by DanTup** [comment]
@connor4312 I was able to repro the full issue I'm seeing in Dart (where the icons never disappear) using the sample too:

![Mar-13-2023 11-34-29](https://user-images.githubusercontent.com/1078012/224690703-6d6da200-d9ba-45c1-a8f9-71370602bcda.gif)

My changes to the sample are here:

https://github.com/DanTup/vscode-extension-samples/commit/e1d76880293091995f8896e898f35789fd21b21c

I changed it so that tests can span multiple lines (since the original code split on lines then searched each line) and use the full range as the `range` for the test. Now when pressing `<enter>` in the test, the original issue (VS Code duplicate the icons) still occurs, but also after the updates, since the range computed by the provider doesn't change from the range VS Code currently has (at least that's my guess), there's no update to the gutter icons so they no longer get cleaned up.

**Comment by connor4312** [comment]
@alexdima for testing decorations, I already set `stickiness: NeverGrowsWhenTypingAtEdges`, but is there a similar option to avoid extending the range over lines when edited? Reference:

https://github.com/microsoft/vscode/blob/b51e2f36135cf30856610102be7e8c95d2f5d1bd/src/vs/workbench/contrib/testing/browser/testingDecorations.ts#L565-L580
