### ISSUE TITLE
cmd + B doesn't toggle sidebar visibility

### ISSUE THREAD

**Issue by VrajPandya** [microsoft/vscode#176977]
Type: <b>Bug</b>

1. open any directory
2. open explorere
3. Try performing cmd + B

VS Code version: Code 1.76.1 (5e805b79fcb6ba4c2d23712967df89a089da575b, 2023-03-08T16:48:08.231Z)
OS version: Darwin arm64 22.3.0
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M2 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.28GB free)|
|Process Argv|--disable-extensions|
|Screen Reader|no|
|VM|0%|
</details>Extensions disabled

**Comment by VrajPandya** [comment]
I see that the key binding is there 
<img width="929" alt="Screenshot 2023-03-13 at 9 10 07 AM" src="https://user-images.githubusercontent.com/6143041/224760368-3b13e013-e4f0-4e12-af03-520b5755fd58.png">

**Comment by lramos15** [comment]
Closing due to lack of info, please feel free to re-open if you disagree.

**Comment by VrajPandya** [comment]
The issue still persists in March release of VS code.

**Comment by lramos15** [comment]
Please follow the steps here to file useful keybindings issues https://github.com/microsoft/vscode/wiki/Keybinding-Issues
