### ISSUE TITLE
No debugger attached when running npm run script with debug button

### ISSUE THREAD

**Issue by p-iknow** [microsoft/vscode#176947]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 
Version: 1.76.1
Commit: 5e805b79fcb6ba4c2d23712967df89a089da575b
Date: 2023-03-08T16:48:08.231Z
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 12_6_1) AppleWebKit/537.36 (KHTML, like Gecko) Code/1.76.1 Chrome/102.0.5005.196 Electron/19.1.11 Safari/537.36
- OS Version:  macOs Monterey

Steps to Reproduce: 
already all extension --disabled 
1. Go to package.json  
2. Click debug button 

https://user-images.githubusercontent.com/35516239/224672994-6a281e7d-8d42-42d0-8c7a-075d39f59969.mov

expected 
- npm run with debugger attached 

result 
- debugger don't attached

**Comment by connor4312** [comment]
Please check that you don't override the `NODE_OPTIONS` environment variable in e.g. your bashrc/zshrc. You can check the contents by running the "Create JavaScript Debug Terminal" command and running `echo $NODE_OPTIONS`

**Comment by p-iknow** [comment]
> Please check that you don't override the `NODE_OPTIONS` environment variable in e.g. your bashrc/zshrc. You can check the contents by running the "Create JavaScript Debug Terminal" command and running `echo $NODE_OPTIONS`

Wow you were right on the money, I can finally solve the problem, thanks for the reply.
![image](https://user-images.githubusercontent.com/35516239/229325561-6d032441-56bb-4915-a81b-ce1c4f701d0c.png)
