### ISSUE TITLE
Unable to show terminal upon open for Profile 

### ISSUE THREAD

**Issue by cwebster-99** [microsoft/vscode#176975]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.76
- OS Version: 

Steps to Reproduce:

1. Created a profile and had the terminal explicitly open when the profile was exported 
2.  Users that import the profile do not see the terminal after the profile is imported/loaded 

Examples of profiles: 
- https://insiders.vscode.dev/profile/github/b00353b96014a77b2a541f62d696b910
- https://vscode.dev/profile/github/91a15b1df5a84d28e91bab5279bb4bed

cc/ @luabud

**Comment by isidorn** [comment]
@cwebster-99 thanks for opening this issue.
@sandy081 I can reproduce. After I import the profile the Terminal is not visible.

**Comment by sandy081** [comment]
/designed

View/Panel 's expand/collapse state is workspace specific. Hence profile does not capture it.

**Comment by isidorn** [comment]
@sandy081 this sucks :'(
