### ISSUE TITLE
Scope to folder

### ISSUE THREAD

**Issue by mbeckenbach** [Microsoft/vscode#17696]
- VSCode Version: 1.8.1
- OS Version: Win10

It would be cool if you could right click on a folder and move the file list scope to that. In that case everything else will be hidden. Very usefull in angular2 or ionic projects. So you would only see files, that you are using at the moment.

![image](https://cloud.githubusercontent.com/assets/6654388/21401804/f01d9f42-c7b5-11e6-8f08-2cf0c57baaa2.png)

**Comment by jschraub** [comment]
This is one of my favorite features in Visual Studio.  Here is a link to a blog post describing and praising the Visual Studio feature.  Would love to see something similar in VS Code.

http://www.dotnetjalps.com/2014/07/scope-to-this-solution-explorer-visual-studio.html
