### ISSUE TITLE
Race condition when installing extensions which depend on the Python extension

### ISSUE THREAD

**Issue by brettcannon** [microsoft/vscode#176985]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: latest vscode.dev + GitHub Codespaces
- OS Version: GitHub Codespaces universal image (so Ubuntu)

I have had multiple people report to me (including myself and @kieferrm  ) that they are getting notifications when trying to use a new GitHub Codespaces of various extensions which rely on the Python extension that the Python extension itself isn't installed. My guess is that while the VS Code server is launching and installing various extensions, it is installing extensions like Pylint before the Python extension (has either started or completed), and that's causing VS Code to claim the Python extension isn't installed.

An example screenshot:

<img width="409" alt="MicrosoftTeams-image (2)" src="https://user-images.githubusercontent.com/54418/224781580-70bb10de-bb69-4af3-8783-7f7e48bfa3a8.png">

And the line from the Pylint extention that declares the Python extension dependency: https://github.com/microsoft/vscode-pylint/blob/b52e0f980b7103fbea9b223e9ac13e50de1cbe2e/package.json#L39 .

**Comment by sandy081** [comment]
May I know how are these extensions getting installed? Is it by codespaces server or manually by user?

**Comment by brettcannon** [comment]
By Codespaces automatically when opening a repo containing a Python project (e.g. I ran into it when creating a Codespace for https://github.com/brettcannon/microvenv , although it may have been before I added the `extensions.json`).

**Comment by sandy081** [comment]
I just tried creating the codespace from the above repo and it is not installing any python extensions for me. Is it may be you have python extension synced and it is being installed by settings sync?

**Comment by brettcannon** [comment]
It could also be coming in via Settings Sync. I also know people who have complained when they have listed the extensions in a `devcontainer.json` and found it order-sensitive to avoid the prompt.

**Comment by sandy081** [comment]
/duplicate

https://github.com/microsoft/vscode/issues/165202
