### ISSUE TITLE
No File Explorer in activity bar after Open folder project

### ISSUE THREAD

**Issue by cmioci** [microsoft/vscode#176944]
Version: 1.76.1 (system setup)
Commit: 5e805b79fcb6ba4c2d23712967df89a089da575b
Date: 2023-03-08T16:32:00.131Z
Electron: 19.1.11
Chromium: 102.0.5005.196
Node.js: 16.14.2
V8: 10.2.154.26-electron.0
OS: Windows_NT x64 10.0.19045
Sandboxed: Yes

Hi,
the steps:

lunch VSC, the File Explorer is present in Activity Bar
![Explorer](https://user-images.githubusercontent.com/5063017/224651255-7410017c-3c19-4063-8886-4349250578ff.PNG)

open my project and the File Explorer disappears from Activity Bar (Ctrl+Shift+E not work and item Explorer is not present in the menu) 
![NoExplorer](https://user-images.githubusercontent.com/5063017/224652315-21d38a53-b73c-40a2-9022-17dea8218187.PNG)

thx cm

**Comment by gjsjohnmurray** [comment]
Maybe you somehow dragged Explorer into another view, or moved it to Panel or Secondary Side Bar.

See https://github.com/microsoft/vscode/issues/176046#issuecomment-1453689195 for advice.

**Comment by cmioci** [comment]
Thanks for the answer I solved:

Ctrl + Shift + P

![Resolve](https://user-images.githubusercontent.com/5063017/224681693-b9fabfaa-70c8-49f2-83fb-cc32e6e90321.PNG)

cm
