### ISSUE TITLE
changes not tracking

### ISSUE THREAD

**Issue by ilhamMuham** [microsoft/vscode#176998]
Type: <b>Bug</b>

my changes not tracking on vs code, so i must scroll up & down to know where my changes

VS Code version: Code 1.76.1 (5e805b79fcb6ba4c2d23712967df89a089da575b, 2023-03-08T16:32:00.131Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz (8 x 2419)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|11.74GB (2.31GB free)|
|Process Argv|. -n --crash-reporter-id 87ba994f-9994-428d-b4eb-b1ebc19a7adc|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
flutter-snippets|ale|3.0.0
dart-code|Dar|3.60.1
flutter|Dar|3.60.0
gitlens|eam|13.3.2
prettier-vscode|esb|9.10.4

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vscaac:30438847
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30681850
azure-dev_surveyone:30548225
pyindex848:30662994
nodejswelcome1cf:30587006
282f8724:30602487
pyind779:30671433
89544117:30613380
pythonsymbol12:30671437
vsccsb:30677849
pythonb192:30669360
funwalk2cf:30682975

```

</details>

**Comment by lszomoru** [comment]
@ilhamMuham, could you please download the latest Insiders release and see if you are still able to reproduce? Thanks!

**Comment by ilhamMuham** [comment]
@lszomoru where i can download the latest Insiders release?

**Comment by lszomoru** [comment]
@ilhamMuham, you can download it from https://code.visualstudio.com/insiders/

**Comment by ilhamMuham** [comment]
@lszomoru that's working, thank you very much
