### ISSUE TITLE
Cannot read properties of undefined (reading 'getCollaboratorCount')

### ISSUE THREAD

**Issue by kdnguy95** [microsoft/vscode#176980]
Type: <b>Bug</b>

Partner created liveshare and sent link. Clicked link to open VSCode. Never was able to join session and received the following error 'Cannot read properties of undefined (reading 'getCollaboratorCount')'

VS Code version: Code 1.76.1 (5e805b79fcb6ba4c2d23712967df89a089da575b, 2023-03-08T16:32:00.131Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: No
Remote OS version: Linux x64 5.15.90.1-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.73GB (4.23GB free)|
|Process Argv|--open-url --crash-reporter-id b273c45a-eac9-4726-96a3-69634028fe34 -- vscode://ms-vsliveshare.vsliveshare/join?vslsLink=https://vscode.dev/liveshare/0E3AF7962F2B98F792E63A6A5DD1E3DE0A58|
|Screen Reader|no|
|VM|20%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 5.15.90.1-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2592)|
|Memory (System)|7.62GB (6.70GB free)|
|VM|0%|
</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
codespaces|Git|1.14.0
vsc-python-indent|Kev|1.18.0
remote-containers|ms-|0.282.0
remote-ssh|ms-|0.98.0
remote-ssh-edit|ms-|0.84.0
remote-wsl|ms-|0.76.1
vscode-remote-extensionpack|ms-|0.24.0
remote-explorer|ms-|0.2.0
remote-server|ms-|1.0.0
jinja|who|0.0.8
vsliveshare|ms-|1.0.5834
vscode-wakatime|Wak|24.0.7

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
pynewext54:30681850
azure-dev_surveyone:30548225
pyindex848:30662994
nodejswelcome1:30587005
282f8724:30602487
pyind779:30671433
89544117:30613380
pythonsymbol12:30671437
a9j8j154:30646983
pythonb192:30669360
funwalk2cf:30682975
pythonms35cf:30680985

```

</details>

**Comment by lszomoru** [comment]
Could you please file an issue in [the extension's git repository](https://github.com/MicrosoftDocs/live-share/issues?utf8=%E2%9C%93&q=is:issue+is:open+sort:reactions-%2B1+)? Thank you!
