### ISSUE TITLE
No Intellisense with package.json

### ISSUE THREAD

**Issue by SetTrend** [Microsoft/vscode#1769]
I have created a `package.json` file using `npm`. When opening it in VS Code I don't get any Intellisense whatsoever.

What's wrong?

![code](https://cloud.githubusercontent.com/assets/9283914/12092981/a27578e8-b300-11e5-8b94-9468e1aaa372.png)

**Comment by aeschli** [comment]
fix delivered

**Comment by SetTrend** [comment]
Excellent :clap:
