### ISSUE TITLE
Format snippet help text

### ISSUE THREAD

**Issue by mark-wiemer** [microsoft/vscode#176934]
The current snippet help text is bad

From the current code: 

https://github.com/microsoft/vscode/blob/95ee78fd9ada5361edb97a51122cb84e8b46c243/src/vs/workbench/contrib/snippets/browser/commands/configureSnippets.ts#L177-L192

- beyond 120 cols
- hard to read as sentences start mid-line
- says "id" instead of "ID" (that's just a pet peeve, of course)

**Comment by jrieken** [comment]
no change planned
