### ISSUE TITLE
macOS: Closing a native tab window closes the whole app

### ISSUE THREAD

**Issue by elf-is** [microsoft/vscode#176945]
Type: <b>Bug</b>

I am using multi tab option of MacOS and recently when I try to close a tab the app shuts down and when I reopen it the window is still there.

Edit: Now I tried closing it while being on another tab and it worked correctly, the problem only surfaces when I am trying to close the active tab.

VS Code version: Code 1.76.1 (Universal) (5e805b79fcb6ba4c2d23712967df89a089da575b, 2023-03-08T16:32:09.831Z)
OS version: Darwin x64 22.3.0
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz (16 x 2300)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|2, 4, 5|
|Memory (System)|16.00GB (0.41GB free)|
|Process Argv|--crash-reporter-id d1bbc3d8-eb9c-4d35-ba33-3efa29683562|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (62)</summary>

Extension|Author (truncated)|Version
---|---|---
namespace|adr|1.1.2
ng-template|Ang|15.2.0
smarty-template-support|asw|2.1.0
vscode-intelephense-client|bme|1.9.5
vscode-tailwindcss|bra|0.9.7
tpl|cdp|1.0.1
cssrem|cip|3.1.0
gitignore|cod|0.9.0
systemd-unit-file|coo|1.0.6
doxdocgen|csc|1.4.0
vscode-office|cwe|2.9.6
vscode-eslint|dba|2.4.0
composer-php-vscode|DEV|1.31.12740
phptools-vscode|DEV|1.31.12740
profiler-php-vscode|DEV|1.31.12740
jquerysnippets|don|0.0.1
xml|Dot|2.5.1
gitlens|eam|13.3.2
vscode-html-css|ecm|1.13.1
prettier-vscode|esb|9.10.4
auto-using|Fud|0.7.15
html-preview-vscode|geo|0.2.5
copilot|Git|1.77.9225
live-sass|gle|6.0.3
gc-excelviewer|Gra|4.2.56
openvpn|idl|0.3.1
Ionide-fsharp|Ion|7.5.1
vscode-nuget-package-manager|jmr|1.1.6
Angular2|joh|13.0.0
svn-scm|joh|2.15.7
roslynator|jos|4.2.0
intellij-idea-keybindings|k--|1.5.7
vscode-gutter-preview|kis|0.30.0
csharpextensions|kre|1.7.3
vscode-format-context-menu|lac|1.0.4
vscode-language-babel|mgm|0.0.37
vscode-docker|ms-|1.24.0
csharp|ms-|1.25.4
vscode-dotnet-pack|ms-|1.0.12
vscode-kubernetes-tools|ms-|1.3.11
python|ms-|2023.4.1
vscode-pylance|ms-|2023.3.20
remote-containers|ms-|0.282.0
remote-ssh|ms-|0.98.0
remote-explorer|ms-|0.2.0
vscode-typescript-next|ms-|5.1.20230312
vsliveshare|ms-|1.0.5834
material-icon-theme|PKi|4.24.0
remove-comments|pli|1.2.2
quicktype|qui|12.0.46
rcore-unused-css-classes|rco|0.1.7
vscode-yaml|red|1.12.1
vscode-javascript-booster|sbu|14.0.1
autoimport|ste|1.5.4
sass-indented|syl|1.8.26
open-in-browser|tec|2.0.0
assistant|tom|0.17.0
sort-lines|Tyr|1.9.1
vscode-todo-highlight|way|1.0.5
color-vision|wil|0.1.0
JavaScriptSnippets|xab|1.8.0
save-as-root|yy0|1.6.0

(3 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
pynewvextcfv2:30681851
azure-dev_surveyone:30548225
pyindex848:30662994
nodejswelcome1:30587005
3biah626:30602489
pyind779:30671433
89544117:30613380
pythonsymbol12:30671437
a9j8j154:30646983
showlangstatbar:30672706
vsccsb:30677849
funwalk2:30682974

```

</details>

**Comment by bpasero** [comment]
This sounds to me that there maybe a native crash going on.

Can you please follow the steps in https://github.com/Microsoft/vscode/wiki/Native-Crash-Issues to get at more details around the crash and attach the result here? Thanks!

**Comment by elf-is** [comment]
@bpasero I followed the steps on that link but the crash didn't happen this time, does that flag stay on in case I got the crash later?

**Comment by bpasero** [comment]
@elf-is yes it does, at least as long as you do not restart the app without the flag.

**Comment by bpasero** [comment]
There must be specific steps or specific settings, as I can not reproduce:

![Recording 2023-03-20 at 14 54 17 (1)](https://user-images.githubusercontent.com/900690/226361125-93043f8a-af29-4b92-a38a-2a44321d2efd.gif)

**Comment by elf-is** [comment]
That's probably the case as it didn't occur again in my instance. I'll close the issue and post an update if it happens again.

**Comment by rzhao271** [comment]
Symbolicated
[symbolicated.log](https://github.com/microsoft/vscode/files/11105828/symbolicated.log)

**Comment by deepak1556** [comment]
Merging to https://github.com/microsoft/vscode/issues/167936
