### ISSUE TITLE
Feature request: Inline Diffs

### ISSUE THREAD

**Issue by johannesegger** [microsoft/vscode#176969]
*This is a feature request, please excuse that I don't use the issue template you provide.*

I would like to see a feature similar to Google Docs' edit suggestions:

![dwn1hwr6bv](https://user-images.githubusercontent.com/237707/52181040-87c3cf80-27ed-11e9-937e-fa0aed534829.gif)

I.e. besides *normal editor* and *diff editor* I would like to have a *suggestion editor*, where you can't directly change the existing content, but only *suggest* edits (remove, insert). This is useful for exercise correction (my use case), but maybe also for small GitHub pull requests (either contributors suggesting changes, but also maintainers suggesting changes of a PR).

I know this is *almost* what the diff editor does, but I found that an automatic diffing algorithm often shows diffs not how I want. And a standard diff editor is line-based, which is not optimal if the diff is only minimal (e.g. only white-space added, single character changed).

I tried to implement this feature myself, but failed miserably. Here's how far I got:

![m9qrq9dvea](https://user-images.githubusercontent.com/237707/52181152-2997ec00-27ef-11e9-884f-970b7d05f6d1.gif)

The above only contains the scenarios that work, but there are a lot more that don't work, so I massively burnt my fingers when trying to implement this.

Could you imagine such editor mode to be useful to a broader range of developers or is it just useful for me as a teacher?

**Comment by hediet** [comment]
Verification steps:
* Set `"diffEditor.experimental.useTrueInlineView": true,`
* Set `"diffEditor.renderSideBySide": false,`
* Open a diff where only some words changed
* Notice the inline diff view
