### ISSUE TITLE
createOutputChannel languageId param should use `log` instead of `Log`

### ISSUE THREAD

**Issue by tjx666** [microsoft/vscode#176902]
Disable Extensions:

Yes

Documentation:

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/41773861/224564162-0edb0358-4b06-4298-8bd7-7b77ede77ce7.png">

When use `Log`:

```typescript
let outputChannel: OutputChannel | undefined;
export const logger = {
    log(message: string, active: boolean): void {
        if (outputChannel === undefined) {
            outputChannel = vscode.window.createOutputChannel('Neo File Utils', 'Log');
        }
        outputChannel.append(`${message}\n`);
        if (active) {
            outputChannel.show();
        }
    },
    dispose(): void {
        outputChannel?.dispose();
    },
};
```

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/41773861/224564199-314be51c-d8ca-4aa5-a821-782d67b3298a.png">

When use `log`:

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/41773861/224564257-d8164ae8-4875-464d-90ea-db6aa0c44c0d.png">

Versions:

```
Version: 1.76.1 (Universal)
Commit: 5e805b79fcb6ba4c2d23712967df89a089da575b
Date: 2023-03-08T16:32:09.831Z
Electron: 19.1.11
Chromium: 102.0.5005.196
Node.js: 16.14.2
V8: 10.2.154.26-electron.0
OS: Darwin x64 22.3.0
Sandboxed: No
```

@sandy081

**Comment by sandy081** [comment]
This is correct that the normal output channels use `Log` as the default language id and hence they are not colored by default. `log` language id is used for the logging output channels.
