### ISSUE TITLE
Crash when opening 50mb YAML file

### ISSUE THREAD

**Issue by flammard** [Microsoft/vscode#177]
Version 0.10.1

As the subject says, When I attempt to open a 55MB YAML file, VS Code crashes.

Opening smaller files seems to work fine (5mb).  The larger one makes it blow up every time.

Let me know if I can provide any more information.

**Comment by bpasero** [comment]
@flammard can you attach the file zipped?

**Comment by flammard** [comment]
@bpasero Github won't let me upload a zipped file.

Unfortunately, we don’t support that file type.  Choose Files Try again with a PNG, GIF, JPG, DOCX, PPTX, XLSX, TXT, or PDF.

Is there some other way of getting it to you?  It's about 3.5MB zipped with 7Zip.

**Comment by bpasero** [comment]
@flammard in those cases I simply create a new repository on GitHub and upload it there via git :)

**Comment by flammard** [comment]
Here it is: https://github.com/flammard/data

Thanks very much for looking at this.

**Comment by alexandrudima** [comment]
Brought back the following behaviour:
* files over 5MB don't get synced to web workers
* files over 20MB don't get any mode supports (coloring, intellisense, etc.)

These changes relieve the memory pressure and I can now open & edit this file fine.
