### ISSUE TITLE
Keep Language mode when reload window after update plugin

### ISSUE THREAD

**Issue by renzors** [Microsoft/vscode#17702]
- VSCode Version: Code 1.8.1 (ee428b0eead68bf0fb99ab5fdc4439be227b6281, 2016-12-19T14:49:23.350Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

|Extension|Author|Version|
|---|---|---|
|xml|DotJoshJohnson|1.6.1|
|vscode-coffeescript-preview|drewbarrett|0.1.3|
|vscode-great-icons|emmanuelbeziat|1.1.30|
|csharp|ms-vscode|1.6.0|
|PowerShell|ms-vscode|0.8.0|
|view-in-browser|qinjia|0.0.3|
|coffeescript-snippets|ronaldloyko|0.1.3|
|vscode-coffeelint|slb235|0.0.2|
|Material-theme|zhuangtongfa|1.0.3|

---

Steps to Reproduce:

1. Create new file, write some code and set a language mode (in my case Batch file). The file is unsaved.
2. Update any plugin (in my case C#)
3. Click in reload label and accept message
4. The file is kept but language mode is missed when window reload

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/16803
