### ISSUE TITLE
Paths to included files gets messed up in MVC 

### ISSUE THREAD

**Issue by JerkerPihl** [Microsoft/vscode#17704]
- VSCode Version: Code 1.8.1 (ee428b0eead68bf0fb99ab5fdc4439be227b6281, 2016-12-19T14:49:23.350Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

|Extension|Author|Version|
|---|---|---|
|aessoft-class-autocomplete|AESSoft|0.1.0|
|githistory|donjayamanne|0.1.4|
|jquerysnippets|donjayamanne|0.0.1|
|vscode-html-css|ecmel|0.0.30|
|csharp|ms-vscode|1.6.0|
|mono-debug|ms-vscode|0.12.0|
|debugger-for-chrome|msjsdiag|2.4.1|
|vscode-docker|PeterJausovec|0.0.10|

---

Steps to Reproduce:

1. Create asp.net MVC with auth project from yo with aspnet generator
2. Run project with dotnet run (works great, all path to jquery and stuff is correct)
3. Exit and Open it in Code
4. Run debugger, no paths to included javascript/jquery are correct

**Comment by egamma** [comment]
This issue was moved to OmniSharp/omnisharp-vscode#1083
