### ISSUE TITLE
Javascript imports not found for code on samba

### ISSUE THREAD

**Issue by Wapax** [microsoft/vscode#177083]
Type: <b>Bug</b>

I'm currently working on Windows 10 but all my code is on a Debian 10 Virtualbox VM powered by Vagrant. I connect to the VM via SMB (samba). I've had errors since yesterday on each TypeScript imports (packages, modules, paths...) : ts(2307). I don't have these problems when I use the local machine storage.

VS Code version: Code 1.76.1 (5e805b79fcb6ba4c2d23712967df89a089da575b, 2023-03-08T16:32:00.131Z)
OS version: Windows_NT x64 10.0.19044
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz (8 x 1498)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by mjbvz** [comment]
How are exactly you connecting? Just a network drive?

Can you use [Remote ssh](https://code.visualstudio.com/docs/remote/ssh) instead?

**Comment by Parziphal** [comment]
I have the same problem: I have code in a VM and connect through it via Samba. February update broke the connection somehow (it works fine in `1.75.1` so I'll just be using that version).

I've noticed this: when I right click an import declaration (that is marked as not found) and choose "Go to definition", VSCode attempts to open the file at `/192.168.1.xx/path/to/file`. Notice that the path starts with a single slash, when it should be 2 slashes (i.e. `//192.168.1.xx/path/to/file`). That seems suspicious.

**Comment by Wapax** [comment]
@mjbvz I connect by using simple smb connection by typing `\\192.168.55.100\dev` into the Windows file explorer nav bar. I didn't mount this point as a drive. I've never tried Remote SSH, I gonna take a look at it soon.

**Comment by Wapax** [comment]
@Parziphal @mjbvz I mounted the smb share as a drive and I don't have no longer this problem.

**Comment by mjbvz** [comment]
Can you please test this on the latest VS Code insiders: https://code.visualstudio.com/insiders/ This generally should be working again but TypeScript itself doesn't always play nicely with samba directories (UNC paths)

Using the remote ssh extension  or a mounted drive should avoid all of these issues
