### ISSUE TITLE
run button broken

### ISSUE THREAD

**Issue by DevilMusic2028** [microsoft/vscode#177031]
Type: <b>Bug</b>

yk how theres a run button on top right beside split editor well its gone now and idk what happened, I tried researching and only way i found was installing code runner, even after that it gves me error saying "Code language not supported or defined." idk what to do 

I have checked that my file reconizable in correct language, and all the extentions have been removed in caluse if that was effecting it

VS Code version: Code 1.76.1 (5e805b79fcb6ba4c2d23712967df89a089da575b, 2023-03-08T16:32:00.131Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|12th Gen Intel(R) Core(TM) i7-1255U (12 x 2611)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.70GB (6.52GB free)|
|Process Argv|--crash-reporter-id 857b5f6e-1859-464a-8572-a4a2aefd96b6|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
pynewvextcfv2:30681851
azure-dev_surveyone:30548225
vsccc:30610678
pyindex848:30662994
nodejswelcome1:30587005
282f8724:30602487
pyind779:30671433
89544117:30613380
pythonsymbol12:30671437
6233i204:30672705
vsctsb:30677850
vscodedisable:30660115
pythonb192cf:30669361
funwalk2cf:30682975
pythonms35cf:30680985

```

</details>

**Comment by gjsjohnmurray** [comment]
AFAIK that top right Run button is not a built in feature of VS Code, it's contributed by an extension.

VS Code"s built in feature is on the Run & Debug view which can be selected from the Activity Bar.

**Comment by DevilMusic2028** [comment]
well it was there when I first downloaded it without any extension and even with the extension code runner it gives me an error "Code language not supported or defined".

**Comment by roblourens** [comment]
That error doesn't come from vscode. That button and error are likely coming from the extension. You can file an issue on the extension with more details, such as which language you are actually trying to run
