### ISSUE TITLE
Save As...dialog should also include a choice to save as administrator/root

### ISSUE THREAD

**Issue by rhires** [Microsoft/vscode#17707]
This is a feature request :-)

VSCode Version 1.8.1
Commit ee428b0eead68bf0fb99ab5fdc4439be227b6281
Date 2016-12-19T14:41:20.664Z
Shell 1.4.6
Renderer 53.0.2785.143
Node 6.5.0
- OS Version: Ubuntu 14.04

When saving a file, I get a "Failed to save 'default': A system error occured (EACCES: permission denied, open '/etc/nginx/sites-available/default')" because I'm saving the file as a regular user, rather than admin/root. This is as it should be. But I should also get a prompt that allows me to enter root/pw so that I can go ahead and save. 

I think it makes sense to put that in the "Save As..." dialog, because I think to myself "Yeah, save as root". As for details of the process of that...I'm not sure. Maybe once you hit save and you get the permission denied, it can prompt w/ username/pw for whatever user (generally root) is needed to save in that spot.

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/1614
