### ISSUE TITLE
Extension host terminated unexpectedly

### ISSUE THREAD

**Issue by andrelinos** [microsoft/vscode#177077]
Does this issue occur when all extensions are disabled?: No

- VS Code Version:  1.76.1
- OS Version:  Linux x64 5.15.0-67-generic

System information:
CPUs | AMD Ryzen 5 4600G with Radeon Graphics (12 x 1400)
-- | --
GPU Status | 2d_canvas: enabled canvas_oop_rasterization: disabled_off direct_rendering_display_compositor: disabled_off_ok gpu_compositing: enabled multiple_raster_threads: enabled_on opengl: enabled_on rasterization: enabled raw_draw: disabled_off_ok skia_renderer: enabled_on video_decode: disabled_software video_encode: disabled_software vulkan: disabled_off webgl: enabled webgl2: enabled webgpu: disabled_off
Load (avg) | 1, 1, 1
Memory (System) | 31.22GB (25.90GB free)
Process Argv | . --crash-reporter-id c4dcb7de-a527-4cad-b030-31f44568b010
Screen Reader | no
VM | 0%

**Extensions**:

Extension | Author (truncated) | Version
-- | -- | --
vscode-sqlite | ale | 0.14.1
iconify | ant | 0.5.1
vscode-apollo | apo | 1.19.11
emojisense | bie | 0.9.1
blackbox | Bla | 0.10.38
vscode-tailwindcss | bra | 0.9.8
vscode-expo | byC | 0.9.2
npm-intellisense | chr | 1.4.4
path-intellisense | chr | 2.8.4
vscode-css-modules | cli | 0.4.2
split-html-attributes | dan | 1.0.10
vscode-markdownlint | Dav | 0.49.0
vscode-eslint | dba | 2.4.0
githistory | don | 0.6.20
gitlens | eam | 13.3.2
vscode-html-css | ecm | 1.13.1
EditorConfig | Edi | 0.16.4
prettier-vscode | esb | 9.10.4
auto-close-tag | for | 0.5.14
auto-rename-tag | for | 0.1.10
vscode-pull-request-github | Git | 0.60.0
live-sass | gle | 6.0.3
vscode-graphql-execution | Gra | 0.1.8
vscode-graphql-syntax | Gra | 1.1.0
svg | joc | 1.5.1
vscode-wordpress-hooks | joh | 1.1.0
vscode-colorize | kam | 0.11.1
node-module-intellisense | lei | 1.5.0
vscode-simple-readme | mau | 1.0.2
fluent-icons | mig | 0.0.18
symbols | mig | 0.0.9
dotenv | mik | 1.0.1
mongodb-vscode | mon | 0.10.0
vscode-docker | ms- | 1.24.0
vscode-dotnet-runtime | ms- | 1.6.0
remote-containers | ms- | 0.282.0
vscode-typescript-next | ms- | 5.1.20230313
vsliveshare | ms- | 1.0.5834
vscode-react-native | msj | 1.10.2
nativebase-v3-vscode-extension | Nat | 0.1.3
material-icon-theme | PKi | 4.24.0
tsimporter | pmn | 2.0.1
prisma | Pri | 4.11.0
prisma-insider | Pri | 31.0.1991
vscode-thunder-client | ran | 2.5.1
format-html-in-php | rif | 1.7.0
LiveServer | rit | 5.7.9
vscode-scss-formatter | sib | 2.4.5
code-spell-checker | str | 2.19.0
code-spell-checker-portuguese-brazilian | str | 2.0.11
move-ts | str | 1.12.0
vscode-styled-components | sty | 1.7.5
tabnine-vscode | Tab | 3.6.42
wordpress-snippet | tun | 1.1.5
vscode-mdx | uni | 1.2.5
errorlens | use | 3.8.0
highlight-matching-tag | vin | 0.11.0
intellicode-api-usage-examples | Vis | 0.2.7
vscodeintellicode | Vis | 1.2.30
console-ninja | Wal | 0.0.85
quokka-vscode | Wal | 1.0.528
wordpress-toolbox | wor | 1.3.15
php-debug | xde | 1.32.0
markdown-all-in-one | yzh | 3.5.0
material-theme | zhu | 3.15.8
html-css-class-completion | Zig | 1.20.0

**Experiment info**:
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vscaat:30438848
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30681850
azure-dev_surveyone:30548225
pyindex848:30662994
nodejswelcome1cf:30587006
2e4cg342:30602488
pyind779:30671433
f6dab269:30613381
pythonsymbol12:30671437
a9j8j154:30646983
showlangstatbar:30672706
vsctsb:30677850
funwalk2cf:30682975

<span style="color: rgb(205, 204, 206); font-family: system-ui, Ubuntu, &quot;Droid Sans&quot;, sans-serif; font-size: 12px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(21, 20, 27); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; display: inline !important; float: none;">(5 theme extensions excluded)</span>

Steps to Reproduce:

Error appears frequently, not for any specific action in use.

**Comment by gjsjohnmurray** [comment]
Please use the Start Extension Bisect command to investigate.

**Comment by isidorn** [comment]
Not Copilot related, assigning to @deepak1556 
@andrelinos extension bisect + following these steps would be great https://github.com/microsoft/vscode/wiki/Native-Crash-Issues
