### ISSUE TITLE
Deleting a file edited in hex editor shows incorrect notification

### ISSUE THREAD

**Issue by herjiict** [microsoft/vscode#177079]
Type: <b>Bug</b>

1. open a folder in VSCode
2. create a file (e.g. `echo a > a.txt`)
3. edit the file in hex editor and save (ctrl+s)
4. right click the file in explorer and select "delete permanently"
5. A notification shows up ask the user to "overwrite" or "close the editor"
6. If "overwrite", nothing happens; If "close the editor", whatever current open editor will be closed

VS Code version: Code 1.76.1 (5e805b79fcb6ba4c2d23712967df89a089da575b, 2023-03-08T16:32:00.131Z)
OS version: Windows_NT x64 10.0.22000
Modes:
Sandboxed: Yes
Remote OS version: Linux x64 5.15.90.1-microsoft-standard-WSL2
Remote OS version: Linux x64 5.15.90.1-microsoft-standard-WSL2
Remote OS version: Linux x64 5.15.90.1-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz (8 x 3600)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.85GB (2.92GB free)|
|Process Argv|--crash-reporter-id 21c6bf78-6673-416a-881d-48bfe6d35e00|
|Screen Reader|no|
|VM|27%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 5.15.90.1-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz (8 x 3600)|
|Memory (System)|7.68GB (1.91GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 5.15.90.1-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz (8 x 3600)|
|Memory (System)|7.68GB (1.91GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 5.15.90.1-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz (8 x 3600)|
|Memory (System)|7.68GB (1.91GB free)|
|VM|0%|
</details><details><summary>Extensions (47)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|3.0.2
auto-rename-tag|for|0.1.10
better-cpp-syntax|jef|1.17.2
jupyter-keymap|ms-|1.1.0
remote-ssh|ms-|0.98.0
remote-ssh-edit|ms-|0.84.0
remote-wsl|ms-|0.76.1
material-icon-theme|PKi|4.24.0
vscode-nginx-conf|ahm|0.1.3
astro-vscode|ast|0.28.2
vscode-tailwindcss|bra|0.9.8
turbo-console-log|Cha|2.7.1
gitignore|cod|0.9.0
doxdocgen|csc|1.4.0
vscode-markdownlint|Dav|0.49.0
vscode-eslint|dba|2.4.0
gitlens|eam|13.3.2
prettier-vscode|esb|9.10.4
shell-format|fox|7.2.5
go|gol|0.38.0
svg|joc|1.5.1
bash-ide-vscode|mad|1.35.0
vscode-docker|ms-|1.24.0
black-formatter|ms-|2022.6.0
isort|ms-|2022.8.0
python|ms-|2023.4.1
vscode-pylance|ms-|2023.3.20
jupyter|ms-|2023.2.1200692131
jupyter-keymap|ms-|1.1.0
jupyter-renderers|ms-|1.0.15
vscode-jupyter-cell-tags|ms-|0.1.6
vscode-jupyter-slideshow|ms-|0.1.5
cmake-tools|ms-|1.13.45
cpptools|ms-|1.14.4
hexeditor|ms-|1.9.11
prisma|Pri|4.11.0
vscode-xml|red|0.24.0
vscode-yaml|red|1.12.1
LiveServer|rit|5.7.9
code-spell-checker|str|2.19.0
vscode-styled-components|sty|1.7.5
even-better-toml|tam|0.19.0
es6-string-html|Tob|2.12.1
cmake|twx|0.0.17
intellicode-api-usage-examples|Vis|0.2.7
vscodeintellicode|Vis|1.2.30
markdown-all-in-one|yzh|3.5.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30681850
azure-dev_surveyone:30548225
pyindex848:30662994
nodejswelcome1cf:30587006
282f8724:30602487
pyind779:30671433
89544117:30613380
pythonsymbol12:30671437
2i9eh265:30646982
showlangstatbar:30672706
vsctsb:30677850
funwalk2:30682974

```

</details>

**Comment by josephofthebread** [comment]
Same issue, but it seems like Hex editor versions below 1.9.8 are stable (at least on my mac).
Maybe someone would give this issue a go ?
