### ISSUE TITLE
Questioning the impact of modification on translation of Editor and Extensions in VsCode

### ISSUE THREAD

**Issue by AlencarGabriel** [microsoft/vscode#177081]
Ref PR #174733

@TylerLeonhardt / @sbatten / @Octacat1 
Should this modification impact the translation of the entire Editor, or just the extensions?

I ask this because when updating to version 1.76, I started noticing strange behavior in my extension. My language/location on the OS is Portuguese/Brazil, and I use VsCode in English. In the last version my extension is in Portuguese, but when I use 1.75.1 it respects the 'display language' and is in English.

From what I noticed when debugging the vscode-nls project, it is considering the VSCODE_NLS_CONFIG environment variable, which, as shown in the image below, works differently between these versions:

v1.76.0
![image](https://user-images.githubusercontent.com/10109480/223729478-b5e80289-4b0a-4462-b0eb-ce29b19cf541.png)

v1.75.1
![image](https://user-images.githubusercontent.com/10109480/223729955-efe0eb05-1431-4ff9-958c-02f7d869613b.png)

Note: My extension is packaged via webpack with gulp.

_Originally posted by @AlencarGabriel in https://github.com/microsoft/vscode/issues/174733#issuecomment-1460184468_

**Comment by TylerLeonhardt** [comment]
I have reverted that changes that changed this behavior... this should be fixed now with: https://github.com/microsoft/vscode/pull/177426
