### ISSUE TITLE
Updating Code loses unsaved documents

### ISSUE THREAD

**Issue by TeaDrivenDev** [Microsoft/vscode#17705]
- VSCode Version: 1.8.0 -> 1.8.1
- OS Version: Windows 7

Steps to Reproduce:

1. Have one never-saved document tab in 1.8.0 (that has been there through several exit/restart cycles)
2. Update to 1.8.1 via the update notification bar
3. Code restarts with the change log in a single tab; the previously existing unsaved tab is gone.

**Comment by bpasero** [comment]
@TeaDrivenDev that should really not happen and I just tried exactly this scenario and cannot reproduce:

![view-picker](https://cloud.githubusercontent.com/assets/900690/21418164/7c30a83a-c81f-11e6-9cf5-3c4e703a03aa.gif)

How is your behaviour different?
