### ISSUE TITLE
How to get all parameter info when filling in a function param list in Python

### ISSUE THREAD

**Issue by horserma** [Microsoft/vscode#17709]
- VSCode Version:1.8.1 
- OS Version:MAC OS

Hi guys, I am using vscode for writing python code. I found when I tried to fill in a function with parameters, the hint will be shown one by one instead of all. For example, if the function has 3 parameters, the hint will show the first one first and after I fill in it and write a comma, the second will be triggered. I just want to show them all to get clear what parameters I am going to fill in. Any suggestions?

**Comment by egamma** [comment]
@horserma thanks for your issue report, python support is provided by an extension. Please file the issue report against the repository of the extension https://github.com/DonJayamanne/pythonVSCode/issues.
