### ISSUE TITLE
VS Code uses global types from typescript extension which leads to bugs

### ISSUE THREAD

**Issue by gentlee** [microsoft/vscode#177062]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 
Version: 1.76.1 (Universal)
Commit: 5e805b79fcb6ba4c2d23712967df89a089da575b
Date: 2023-03-08T16:32:09.831Z
Electron: 19.1.11
Chromium: 102.0.5005.196
Node.js: 16.14.2
V8: 10.2.154.26-electron.0
OS: Darwin arm64 22.2.0
Sandboxed: Yes

- OS Version: 
MacOS 13.1

Steps to Reproduce:

1. Create TS or JS file
2. Write `const a = length + 1`
3. No errors shown though length doesn't exist.
4. CMD + Click on length -> it shows 
![Screenshot 2023-03-14 at 12 42 03](https://user-images.githubusercontent.com/2361140/224960484-68072548-6768-4572-851a-f0096e4cf793.png)

How should be:

It should show error that length doesn't exist.

**Comment by mjbvz** [comment]
This matches what you see if you run `tsc`. Unfortunately there really is a `window` global variable called `length`

If you aren't using the dom types, try changing the `lib` option to exclude it: https://www.typescriptlang.org/tsconfig#lib
