### ISSUE TITLE
Promote built in javascript and typescript to external extension

### ISSUE THREAD

**Issue by Alphapage** [Microsoft/vscode#1770]
Hello,

For now, javascript and typescript are built within vscode.
I think those are the only languages integrated. It would be better to provide them as external extensions available in the marketPlace to make vscode universal. For now, vscode can be considered as a javascript typescript editor with extensions available for other languages (but with poor support which is not the case)

Moreover, typescript extension is using all the features that vscode provides for an extension. This could be a wonderful example on how to implement a full language extension.
Of course you can provide default packages during install.

Hope this could contribute to others too.

**Comment by chrisdias** [comment]
Thanks for the suggestion!  

There are really two things here - one is factoring our language services out as extensions and the second is what we build into the core distribution of VS Code.

We do build the TypeScript language service as an extension which you can find here: https://github.com/Microsoft/vscode/tree/master/extensions/typescript.  As you say, it is an excellent example of a fully featured language service that anyone can review and learn from.

Today the JavaScript language service is built into VS Code but not as an extension.  Our plan is to [adopt the Salsa project](https://github.com/Microsoft/vscode/wiki/Roadmap#javascript) from the TypeScript team that will enable one language service for both JavaScript and TypeScript.  This will be an extension to VS Code as well which everyone will be able to reference.

Regarding packaging, our current plan is to continue to include the TypeScript/JavaScript language services in the core VS Code distribution. The primary reason for this is that we want people to be productive with building web applications and extensions to VS Code without having to go through the trouble of downloading multiple packages. We consider these two scenarios core to VS Code, so we include them in the distribution.  

What we hope to also provide in the future is the ability to download newer versions of this language service from the gallery. For example, let's say there is a new version of the Salsa language service that supports "cool new feature X" but it is not in VS Code yet.  You should be able to download the new version from the gallery and update your installation of VS Code to get the new functionality.

I hope this helps explain our thinking, thanks again for the suggestion.

Chris

**Comment by masaeedu** [comment]
@chrisdias Is there a workflow right now for using a newer version of TypeScript than the one bundled into VSCode? I want to work with TS 1.8 features, but the editor seems to be tied to 1.7.5. 

Regarding the argument of users being productive, I don't see why you couldn't factor these into external packages and simply have them installed by default. This would still allow users who want to play with newer features to fork and edit the packages providing these language features (and heck, even feed this back as a PR), breaking the coupling between the version of TypeScript and the version of the editor.

**Comment by chrisdias** [comment]
@masaeedu Yes, you can use newer versions of typescript by setting the `typescript.tsdk` setting, see [here for more information](https://code.visualstudio.com/updates/v0_8_0#_languages-typescript-16-support).

putting the javascript/typescript language service in its own repo is something that we can consider. its not a problem for packaging the VS Code distro, but it becomes more cumbersome when you want to clone, build, and run the `vscode` repository as you would need to grab the core language service from elsewhere.  

@egamma thoughts?

**Comment by masaeedu** [comment]
@chrisdias Awesome, thanks! Regarding the other issue, does the rest of the code have build time dependencies on the typescript extension?

**Comment by egamma** [comment]
>Regarding the other issue, does the rest of the code have build time dependencies on the typescript extension?

No, there are no build time dependencies on the TS extension and we had experimented with TS in a separate repo. The dogfooding setup is a little less convenient (you have to use symlinks so that TS is in the target Code instanceetc.) this is the reason why we reverted back. Now that we are in transition to Salsa I don't want to change it again. We can consider it again after the migration to Salsa.

**Comment by SetTrend** [comment]
@chrisdias : I'd also like to use TS 1.8, yet I can't find information on *where* to set the `typescript.tsdk` option. Which configuration file do I need to add this option to?

**Comment by masaeedu** [comment]
@SetTrend Open the VSCode command prompt (`Ctrl+Shift+P`), type in user settings and select the option from the dropdown, then add a `"typescript.tsdk"` key to the JSON file on the right, with the value being the path to whichever tsdk you want to use.

**Comment by SetTrend** [comment]
Thanks for helping me out on this, Asad.

Great help, thanks!

**Comment by egamma** [comment]
@SetTrend just checked we have this document in the docs: https://code.visualstudio.com/Docs/languages/typescript#_using-newer-typescript-versions

**Comment by SetTrend** [comment]
@egamma : Thanks a lot for helping.

I agree with you, but not to one regard: The document doesn't say *where* to set this setting. I was assuming that this setting would be resident in an external "technical" compiler settings file (believing that TSC and TSC configuration was something external, like OP proposes) rather than in the intrinsic user preferences settings file. It didn't came to me to look at "File > Preferences > User/Workspace Settings".

**Comment by egamma** [comment]
I see, then we should clarify this in the docs. Moving to vscode-docs.

**Comment by egamma** [comment]
This issue was moved to Microsoft/vscode-docs#135
