### ISSUE TITLE
Integrated terminal context menu should trigger via contextmenu event not mousedown

### ISSUE THREAD

**Issue by hun1ahpu** [Microsoft/vscode#17701]
- VSCode Version: 1.8.0
- OS Version: Windows 10

Steps to Reproduce:

1. Open Integrated terminal
2. Click and hold right mouse button

Expected: nothing happens yet and the context menu shows up on when the user releases the button
Actual: context menu shows up

**Comment by Tyriar** [comment]
Any reason you believe this to be the wrong behavior? This is how the editor and explorer work, in addition to chromium's default context menu.

**Comment by hun1ahpu** [comment]
For both editor and explorer I see context menu on mouse up. Not sure what i'm missing. Some settings probably?

**Comment by Tyriar** [comment]
Maybe that's only on Windows then as I was testing on Linux.

**Comment by hun1ahpu** [comment]
Do you think it would be possible to use 'contextmenu' instead of 'mousedown'?

**Comment by Tyriar** [comment]
Good idea, then the context menu key would work too :+1:

**Comment by Tyriar** [comment]
Pull request that will resolve this https://github.com/Microsoft/vscode/pull/18980

**Comment by jrieken** [comment]
verified via code review, mac behaviour is mousedown and we are consistent there
