### ISSUE TITLE
"A server with the specified hostname could not be found." Random error message

### ISSUE THREAD

**Issue by danielnieto** [Microsoft/vscode#17708]
- VSCode Version: Version 1.8.1 (1.8.1)
- OS Version: OSx El Capitan, 10.11.6

Steps to Reproduce: Unknown.

While using VScode an error message saying ""A server with the specified hostname could not be found." randomly appears, it can get dismissed when clicking on "Close", might reappear later.

![screen shot 2016-12-21 at 1 08 31 pm](https://cloud.githubusercontent.com/assets/2120107/21410881/bb4f20bc-c7a9-11e6-8fea-3b7ddfeeb0e2.png)

**Comment by egamma** [comment]
@danielnieto this is not a message from VS Code and it must come from an extension. Suggest that you selectively disable the extensions you have installed to find the extension and then report the issue against this extension.

You can disable and extension from the Extensions Viewlet:
![image](https://cloud.githubusercontent.com/assets/172399/21458156/888f5a34-c934-11e6-84ad-347dc1bef6a3.png)

**Comment by danielnieto** [comment]
thank you, I will try that
