### ISSUE TITLE
自动排版

### ISSUE THREAD

**Issue by Goc-yan** [Microsoft/vscode#17714]
- VSCode Version: Code 1.8.1 (ee428b0eead68bf0fb99ab5fdc4439be227b6281, 2016-12-19T14:49:23.350Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions:

|Extension|Author|Version|
|---|---|---|

---

Steps to Reproduce:

1.行内写style和onclick会自动排版后，该行以下内容会顶格，不会有缩进

**Comment by ywmail** [comment]
duplicates #17637

**Comment by egamma** [comment]
Thanks @ywmail
