### ISSUE TITLE
Allow comparing files that are not saved

### ISSUE THREAD

**Issue by EFanZh** [Microsoft/vscode#17716]
- VSCode Version: 1.8.1
- OS Version: Windows 7

Steps to Reproduce:

1. Create a new file without saving it.
2. Execute “File: Compare Active File With...” command.
3. The editor shows “Open a file first to compare it with another file.”.

**Comment by bpasero** [comment]
This issue has already been reported. Please use the search function next time before reporting an issue and/or this time if you are curious about the progress of the issue.

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/14501
