### ISSUE TITLE
Add a search box to Run and Debug view for searching launch configurations

### ISSUE THREAD

**Issue by schwartx** [microsoft/vscode#177158]
it will be inconvenient if you have many launch configurations. have to look for each items in drop down list painfully. 

would it be nice to have a  search box for it?
![image](https://user-images.githubusercontent.com/39881118/225185660-75074400-382a-4400-a12b-227d08a9808c.png)

**Comment by dimateos** [comment]
That would be almost the same as the command `Debug: Select and Start Debugging` _`(workbench.action.debug.selectandstart)`_ but without starting. It might be good enough for you tho.

A version of the same command without starting would be good enough for me and nice to have in the meantime.
