### ISSUE TITLE
debug console: entries remain in process list box

### ISSUE THREAD

**Issue by docwarems** [microsoft/vscode#177189]
Does this issue occur when all extensions are disabled?: Yes (only MS default Extensions + MS Extension for remote dev enabled)

- VS Code Version: 1.76.1
- OS Version: Windows_NT x64 10.0.22621

Steps to Reproduce:

1. launch a process defined launch.json
2. stop the process using the VSC red stop button

Now the process shows up twice in the list as seen in the screenshot. Each time you repeat the start/stop cycle, an entry is added. After a while you can't find anything in the box. The problem becomes worse when you launch a multi-process configuration which I usually do.

Maybe this a  feature which I activated without intention. At least I cannot find a setting for this, and noone from our team knows about this problem.

![image](https://user-images.githubusercontent.com/29914148/225250943-9eba0daf-44c4-48c7-aa2d-a132ced175d3.png)

**Comment by zack09holland** [comment]
Im noticing this issue now as well on v1.76.1. I didnt have this issue previously and downgraded to 1.72.1. So somewhere from the September release to the latest release is when it started happening as there have been updates to the debugger.

- https://code.visualstudio.com/updates/v1_73#_debug-adapter-protocol
- https://code.visualstudio.com/updates/v1_74#_debugging
- https://code.visualstudio.com/updates/v1_75#_debugging

**Comment by roblourens** [comment]
Can you actually check whether this is still in the latest Insiders build? This may have been fixed

**Comment by zack09holland** [comment]
Latest insiders build seems to have fixed the issue! When does the insiders version get merged into the main release?

**Comment by roblourens** [comment]
Around the end of the month
