### ISSUE TITLE
Can not open files with spaces in their file names using command line on Linux

### ISSUE THREAD

**Issue by EFanZh** [Microsoft/vscode#17713]
- VSCode Version: 1.8.1
- OS Version: Arch Linux - Latest Version (2016-12-22)

Steps to Reproduce:

1. Type `code 'a b.txt'` in your terminal.
2. Enter.
3. File “a” and “b.txt” are opened.

I think this is related to c2935f2.

Also, this was once fixed in b6095e9.

**Comment by Tyriar** [comment]
This got fixed in https://github.com/Microsoft/vscode/pull/17853
Which reintroduced https://github.com/Microsoft/vscode/issues/15435 and that got fixed again in https://github.com/Microsoft/vscode/commit/289dbf77e32bd44604d6deeb2bd0bc4cb9300e8c
