### ISSUE TITLE
Explorer View replaced with Folders

### ISSUE THREAD

**Issue by jeengbe** [microsoft/vscode#177190]
Type: <b>Bug</b>

Yesterday, I accidentally dragged the exploerer view, which utterly messed up my layout. Dragging all views back to where they belong, I find my shortcut for Open Explorer View is no longer working, worse even, the Explorer view is entirely gone. Where is used to be, there is now something called "Folders".

What happened? How do I get it back?

Bonus points if you know of a way to lock my views so that I don't accidentally drag my views again.

VS Code version: Code 1.76.1 (5e805b79fcb6ba4c2d23712967df89a089da575b, 2023-03-08T16:32:00.131Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: Yes
Remote OS version: Linux x64 5.15.90.1-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 9 3900XT 12-Core Processor            (24 x 3993)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|63.91GB (44.95GB free)|
|Process Argv|--folder-uri vscode-remote://wsl%2Bubuntu/home/jeengbe/data/prisjakt-frontend-app --crash-reporter-id c721b6b5-1c80-4cc5-855f-0423ec59e89a|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 5.15.90.1-microsoft-standard-WSL2|
|CPUs|AMD Ryzen 9 3900XT 12-Core Processor (24 x 3992)|
|Memory (System)|19.53GB (17.20GB free)|
|VM|0%|
</details><details><summary>Extensions (63)</summary>

Extension|Author (truncated)|Version
---|---|---
mermaid-markdown-syntax-highlighting|bpr|1.5.1
codespaces|Git|1.14.0
vscode-graphql-syntax|Gra|1.1.0
fluent-icons|mig|0.0.18
dotenv|mik|1.0.1
vscode-aql|mon|1.7.0
jupyter-keymap|ms-|1.1.0
remote-ssh|ms-|0.98.0
remote-ssh-edit|ms-|0.84.0
remote-wsl|ms-|0.76.1
remote-explorer|ms-|0.2.0
material-icon-theme|PKi|4.24.0
material-product-icons|PKi|1.5.0
swdc-vscode|sof|2.6.50
errorlens|use|3.8.0
vscode-lcov|ale|0.2.0
markdown-mermaid|bie|1.17.7
markdown-preview-github-styles|bie|1.0.1
vscode-intelephense-client|bme|1.9.5
better-toml|bun|0.3.2
path-intellisense|chr|2.8.4
vscode-eslint|dba|2.4.0
gitlens|eam|13.3.2
prettier-vscode|esb|9.10.4
vscode-chatgpt|gen|3.9.5
copilot|Git|1.77.9225
copilot-labs|Git|0.12.791
vscode-pull-request-github|Git|0.60.0
gitlab-workflow|Git|3.60.0
vscode-graphql|Gra|0.8.6
vscode-graphql-syntax|Gra|1.1.0
vscode-env|Iro|0.1.0
gitlab-mr|jas|1.4.3
vscode-colorize|kam|0.11.1
git-graph|mhu|1.30.0
language-gettext|mro|0.2.2
vscode-docker|ms-|1.24.0
python|ms-|2023.4.1
vscode-pylance|ms-|2023.3.20
jupyter|ms-|2023.2.1200692131
jupyter-keymap|ms-|1.1.0
jupyter-renderers|ms-|1.0.15
vscode-jupyter-cell-tags|ms-|0.1.6
vscode-jupyter-slideshow|ms-|0.1.5
hexeditor|ms-|1.9.11
vsliveshare|ms-|1.0.5834
gremlins|nho|0.26.0
vscode-jest|Ort|5.2.3
vscode-twoslash-queries|Ort|1.1.0
markdown-github-dark|oza|0.1.0
restart-ts-server-button|qcz|1.0.1
vscode-yaml|red|1.12.1
datetime|rid|2.2.2
LiveServer|rit|5.7.9
vs-code-prettier-eslint|rve|5.1.0
trailing-spaces|sha|0.4.1
code-spell-checker|str|2.20.0
code-spell-checker-german|str|2.2.0
vscode-styled-components|sty|1.7.5
tabnine-vscode|Tab|3.6.42
codetour|vsl|0.0.58
gitblame|wad|10.1.0
quokka-vscode|Wal|1.0.528

(4 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30681850
azure-dev_surveyone:30548225
pyindex848:30662994
nodejswelcome1cf:30587006
3biah626:30602489
pyind779:30671433
f6dab269:30613381
pythonsymbol12:30671437
2i9eh265:30646982
vsctsb:30677850
funwalk2cf:30682975
pythonms35:30686772

```

</details>

**Comment by gjsjohnmurray** [comment]
If the right-click context menu on "FOLDERS" doesn't help I suggest you run the `View: Reset View Locations` command.

I'm not aware of there being a way to lock view positions.

**Comment by jeengbe** [comment]
Yes, resetting it did it. I wonder where the view went. Thank you!
