### ISSUE TITLE
The DEBUG shows no color and tip , but Function is normal 

### ISSUE THREAD

**Issue by Insane-neal** [Microsoft/vscode#17715]
- VSCode Version: Code 1.8.1 (ee428b0eead68bf0fb99ab5fdc4439be227b6281, 2016-12-19T14:41:20.664Z)
- OS Version: Linux x64 4.4.0-57-generic
- Extensions:

|Extension|Author|Version|
|---|---|---|
|docthis|joelday|0.3.5|
|cpptools|ms-vscode|0.9.3|
|java|redhat|0.0.7|
|cmake|twxs|0.0.15|
|cmake-tools|vector-of-bool|0.8.6|
|debug|webfreak|0.15.0|

---

Steps to Reproduce:

1.
2.

**Comment by egamma** [comment]
@Insane-neal can you please add a screenshot that illustrates the problem?

**Comment by egamma** [comment]
@Insane-neal any update?

**Comment by egamma** [comment]
@Insane-neal please reopen the issue with additional information as requested above.
