### ISSUE TITLE
Support local install gulp during gulp task autodetection

### ISSUE THREAD

**Issue by SetTrend** [Microsoft/vscode#1771]
I don't seem to be able to run tasks.

I followed the [description in the docs](https://code.visualstudio.com/docs/languages/typescript#_transpiling-typescript-into-javascript). However, the `tsc` task apparently isn't found:

![can t run tasks](https://cloud.githubusercontent.com/assets/9283914/12093963/3b7605c6-b306-11e5-8786-cec375f50aaa.gif)

**Comment by SetTrend** [comment]
I just noticed that I didn't have a corresponding task defined in the gulpfile.js.

This approach of maintaining a task using two different files seems more pain than necessary to me. May I suggest a few improvements to the way projects are administered in VS Code:
<br/>
### Add `npm install` context menu to package.json file

When cloning a project from GitHub and opening it in VS Code, no Node module is getting downloaded. So currently it's required to leave VS Code and execute `npm install` in a command prompt.

I suggest to add a context menu item to `package.json` that automates this task, i.e. runs `npm install` from the directory of the `package.json` file:

![package](https://cloud.githubusercontent.com/assets/9283914/12097398/d07d5402-b31b-11e5-961a-c3cb0e03769d.png)
<br/>
### Use `pragma comment` for running tasks in VS Code:

Maintaining two distinct files to have tasks get run in VS Code seems more administration pain than necessary.

I suggest to support a pragma comment preceeding a task, fulfilling the same purpose as the `tasks.json` file does:

```javascript
var gulp = require("gulp");
var ts = require("gulp-typescript");

//# task { isShellCommand: true, isWatching: true, problemMatcher: "$tsc" }
gulp.task("tsc", function () { gulp.src().pipe(ts).pipe(gulp.dest()); })
```
<br/>
### Add `Run Task` context menu to any `.js` file containing a `# task` pragma comment

Currently, running a task requires much typing.

I suggest to add a context menu to any `.js` file containing a `# task` pragma comment so tasks can easily be browsed for and a task can simply be started by two clicks:

![run task](https://cloud.githubusercontent.com/assets/9283914/12098333/f1cc0666-b321-11e5-8f50-cfc10fae09db.png)

The tasks in the list should be alphabetically sorted and the first task name letter should be used for the mnemonic, so starting a task could be as easy as `CTXT, T, L` for "less" or `CTXT, T, T` for "tsc" in the above screen shot.
<br/>
### Add option to automatically start tasks
Whenever a project is opened in VS Code, which is indicated by the following preconditions:
  * a folder gets opened which contains one or more `.json` files
  * any of those `.json` files contains one or more `# task` pragma comments
  * any of those `# task` pragma comments comes with an `autoStart: true` property set

... then the task marked with `autoStart: true` should automatically be executed.

Here's a screenshot depicting how the `autoStart: true` property should be applied:

![auto run 1](https://cloud.githubusercontent.com/assets/9283914/12098517/2161e340-b323-11e5-854d-c4357cef5c60.png)
<br/>
Depending on user/workspace settings, a confirmation dialog might be displayed before the tasks are getting automatically started:

![auto run 2](https://cloud.githubusercontent.com/assets/9283914/12098540/3f001566-b323-11e5-8381-5af2a884aacc.png)

**Comment by SetTrend** [comment]
This is also true for tasks defined in `gulpfile.js`:

![can t run tasks 2](https://cloud.githubusercontent.com/assets/9283914/12104803/37fabe3e-b34f-11e5-9515-08ac012f99f1.gif)
<br/>
What's wrong here?

**Comment by dbaeumer** [comment]
Regarding tsc: you need to install the tsc compiler on your system. To do so run npm install -g typescript and validate the install using tsc --version. It should print 1.7.5

**Comment by dbaeumer** [comment]
In the second case you defined an alias for gulp via a npm script. This is currently not supported. To be able to autodetect gulp task gulp must be installed globally as well.

**Comment by dbaeumer** [comment]
Updating title to reflect this.

**Comment by SetTrend** [comment]
Thanks für helping me out on this!

Shouldn't these important prerequisites better be mentioned in the docs?

I'm running Visual Studio 2015/1 on my system. That's what made me believe that TSC was already installed on my machine, too.

May I suggest to have intellisense for the tasks that are available to `tasks.json` at `"command": "..."`?

**Comment by felixfbecker** [comment]
Basically Code should look in `node_modules/.bin` aswell for _all_ commands, even when individual commands for individual tasks get added as a feature. This allows projects to specifiy specific versions of their compilers or task runners in devDependencies.

**Comment by masaeedu** [comment]
@dbaeumer Is there anything I need to do to update vscode after upgrading my global TypeScript? I'm testing out a TypeScript 1.8 feature that allows type parameters to reference other type parameters like so:

    interface A<T, U extends T> {
    }

But the editor complains about this, even though tsc doesn't:

> main.ts(1,16): error TS2313: Constraint of a type parameter cannot reference any type parameter from the same type parameter list.

**Comment by dbaeumer** [comment]
@masaeedu if you want to use TypeScript@next you need to tell VSCode where to find the corresponding tsserver. Assuming you have installed TypeScript@next into the workspace folder you can set the typescript.tsdk setting as follows:
```json
{
    "typescript.tsdk":"node_modules/typescript/lib"
}
```

**Comment by kylecordes** [comment]
Things are changed a lot since this item went by, but I think the following is still true that I encountered today:

Currently Code once a global Gulp to run a build when it sees a gulpfile. I believe this is fundamentally incorrect. If my application already has a local dependency on gulp, that specific nailed down version is the one that should be executed. It shouldn't matter whether I have a global gulp installed, and even if installed it should not run that global install which is possibly the wrong version. Ideally it would not even look for the global install at all, but actually require that I have a project-specific, version-specified Gulp.

**Comment by dbaeumer** [comment]
@kylecordes agree that we should honor a local installed gulp, grunt, ... in autodetection.

**Comment by dbaeumer** [comment]
[Addressed in new terminal runner]

The auto detection for grunt and gulp for the terminal runner is honoring local installed grunt and gulp packages.

**Comment by javidcf** [comment]
Maybe obvious, but my personal workaround for this on Linux (I guess it could be adapted to other platforms) is to launch VSCode through a `vscode.sh` script like:

```
#!/bin/bash
# Reliably get the script path (according to StackOverflow...)
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
# Launch VSCode with modified PATH
PATH="${DIR}/node_modules/.bin:${PATH}" exec code
```

(assuming `code` is an executable in your path launching VSCode, which is the case for .deb installations...)

**Comment by dbaeumer** [comment]
Closing based on https://github.com/Microsoft/vscode/issues/1771#issuecomment-297442218
