### ISSUE TITLE
February 2023 Recovery 2

### ISSUE THREAD

**Issue by TylerLeonhardt** [microsoft/vscode#177119]
- [x] Create a milestone `<Month> <Year> Recovery <1|2|3>` @TylerLeonhardt
- [x] Bump the version number @TylerLeonhardt
- [x] [🔖candidate issues](https://github.com/issues?q=is%3Aissue%20label%3Acandidate%20repo%3Amicrosoft%2Fvscode%20repo%3Amicrosoft%2Fvscode-remote-release%20repo%3Amicrosoft%2Fvscode-js-debug%20repo%3Amicrosoft%2Fvscode-pull-request-github%20repo%3Amicrosoft%2Fvscode-github-issue-notebooks%20repo%3Amicrosoft%2Fvscode-internalbacklog%20repo%3Amicrosoft%2Fvscode-dev%20repo%3Amicrosoft%2Fvscode-unpkg%20repo%3Amicrosoft%2Fvscode-references-view%20repo%3Amicrosoft%2Fvscode-anycode%20repo%3Amicrosoft%2Fvscode-hexeditor%20repo%3Amicrosoft%2Fvscode-extension-telemetry%20repo%3Amicrosoft%2Fvscode-livepreview%20repo%3Amicrosoft%2Fvscode-remotehub%20repo%3Amicrosoft%2Fvscode-settings-sync-server%20repo%3Amicrosoft%2Fvscode-remote-repositories-github%20repo%3Amicrosoft%2Fmonaco-editor%20repo%3Amicrosoft%2Fvscode-vsce%20repo%3Amicrosoft%2Fvscode-dev-chrome-launcher%20repo%3Amicrosoft%2Fvscode-emmet-helper%20repo%3Amicrosoft%2Fvscode-livepreview%20repo%3Amicrosoft%2Fvscode-livepreview%20repo%3Amicrosoft%2Fvscode-python%20repo%3Amicrosoft%2Fvscode-jupyter%20repo%3Amicrosoft%2Fvscode-jupyter-internal%20repo%3Amicrosoft%2Fvscode-github-issue-notebooks%20repo%3Amicrosoft%2Fvscode-l10n%20repo%3Amicrosoft%2Fvscode-remote-tunnels%20milestone%3A%22February%202023%20Recovery%202%22)
- [x] Assign candidate issues to the recovery milestone **team**
- [x] Review the `candidate` issues, and if they pass the review assign them to the recovery milestone **team**
- [x] All `candidate` fixes are peer reviewed and pushed to `main` and then cherry-picked into the release branch **team**
- [x] Initiate `insiders` build from `main`
- [x] Issues are tested in the `insiders` **team**
- [x] Build `stable` for all platforms from release branch @TylerLeonhardt
- [x] Issues are verified on `stable` build and the `verified` label is added @TylerLeonhardt
- [x] Check `https://github.com/Microsoft/vscode/compare/release/<x.y>` to ensure no other commits have been made in the release branch @TylerLeonhardt
- [x] Update the release notes and include a link to a query for the fixed issues **@gregvanl**
- [x] Sanity check of installable bits ([server instructions](https://github.com/microsoft/vscode-remote-release/wiki/Sanity-Check-VS-Code-Servers))
  - [x] Windows 32 bit @TylerLeonhardt 
    - [x] signed installer 32-bit
    - [x] signed user installer 32-bit
    - [x] zip 32-bit
    - [x] server 32-bit
    - [x] cli 32-bit
  - [x] Windows 64 bit
    - [x] signed installer 64-bit @joyceerhl
    - [x] signed user installer 64-bit @joyceerhl
    - [x] zip 64-bit @joyceerhl
    - [x] server 64-bit @TylerLeonhardt 
    - [x] cli 64-bit @joyceerhl
  - [x] Windows ARM64 @TylerLeonhardt
    - [x] signed installer ARM64
    - [x] signed user installer ARM64
    - [x] zip ARM64 @deepak1556 
    - [x] cli ARM64
  - [x] macOS @TylerLeonhardt 
    - [x] Intel + Universal 
    - [x] server Intel 
    - [x] cli Intel
    - [x] Apple Silicon + Universal
    - [x] server Silicon
    - [x] cli Silicon
  - [x] Linux x64 @rzhao271 
    - [x] deb 
    - [x] rpm
    - [x] archives
    - [x] snap (`sudo snap install --classic --dangerous <file>.snap`)
    - [x] cli
  - [x] Linux server @rzhao271
    - [x] x64
    - [x] ARM32
    - [x] ARM64
    - [x] x64 Alpine
    - [x] ARM64 Alpine
- [x] Publish website **@gregvanl**
- [x] Publish stable build @TylerLeonhardt
- [ ] Create an official release @TylerLeonhardt
  - [x] Create a tag (make sure you pull the release branch first): `git tag <x.y.z> release/<x.y>`
  - [x] Push the tag: `git push origin <x.y.z>`
  - [x] Create a GitHub release: [Open the GitHub tags](https://github.com/microsoft/vscode/tags), and click far right `... > Create Release`. Use the correct title and description from our release notes. [Example](https://github.com/microsoft/vscode/releases/tag/1.39.1)
- [ ] Close the milestone on [GitHub](https://github.com/microsoft/vscode/milestones) @TylerLeonhardt

**Comment by gjsjohnmurray** [comment]
Please fix the candidate issues link on this issue.
