### ISSUE TITLE
Allow hiding buttons in secondary source control toolbars

### ISSUE THREAD

**Issue by RJWadley** [microsoft/vscode#177134]
In the source control menu, you can hide buttons you don't want to see. 
Here's what the menu looks like uncustomized for me:

<img width="500" alt="Uncustomized toolbar with several buttons" src="https://user-images.githubusercontent.com/25678876/225131867-0bb5cb3a-1099-40fe-8003-aa0e6ac5224f.png">

You can right-click on the buttons in the top right to hide them. I like to keep mine pretty minimal:

<img width="500" alt="Customized toolbar with only a few buttons" src="https://user-images.githubusercontent.com/25678876/225132058-1a5faac9-7ae6-42c0-8c31-ae02d546da35.png">

When you have more than one repository open, like when working with a submodule, most of these buttons are moved into secondary toolbars and can no longer be hidden:

<img width="500" alt="Two separate toolbars with several buttons" src="https://user-images.githubusercontent.com/25678876/225132204-a8c826f6-b566-4928-864d-bd0e424bdf6c.png">

I think these buttons should be hideable too. If it's possible, these two views should also remain in sync. (e.g. if I hide the refresh button, it's hidden regardless of whether I currently have a submodule open)

**Comment by pecopeco** [comment]
anyone have a temporary solution before the update？too many buttons blocking the project name

**Comment by lszomoru** [comment]
This is now available in VS Code 1.86.
