### ISSUE TITLE
OCaml Platform throw exception just after installation

### ISSUE THREAD

**Issue by fr0ster** [microsoft/vscode#177184]
We have written the needed data into your clipboard because it was too large to send. Please paste.
Type: <b>Bug</b>

Just install OCAML Platform

VS Code version: Code 1.76.1 (5e805b79fcb6ba4c2d23712967df89a089da575b, 2023-03-08T16:31:31.010Z)
OS version: Linux x64 5.10.0-21-amd64
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i9-11900K @ 3.50GHz (16 x 4970)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|1, 1, 1|
|Memory (System)|31.23GB (21.78GB free)|
|Process Argv|. --crash-reporter-id 6de90322-77d8-4733-bb9d-bea082a31b64|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|gnome|
|XDG_CURRENT_DESKTOP|GNOME|
|XDG_SESSION_DESKTOP|gnome|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (186)</summary>

Extension|Author (truncated)|Version
---|---|---
language-x86-64-assembly|13x|3.0.0
rust-bundle|1Yi|1.0.0
ada|Ada|23.0.14
commonlisp-vscode|ail|0.3.2
golangwithdidi|ald|0.0.1
laravel-extra-intellisense|ami|0.6.2
ng-template|Ang|15.2.0
browse-lite|ant|0.3.1
vite|ant|0.2.5
atlascode|atl|3.0.2
vscode-django|bat|1.10.0
calva|bet|2.0.337
stm32-for-vscode|bmd|3.2.3
advanced-abap-snippet-generator|Bra|1.2.8
sqltools-athena-driver|bru|0.3.0
better-toml|bun|0.3.2
make-task-provider|car|2.4.2
ui5-tools|car|2.2.0
unity-code-snippets|cem|0.1.1
digital-ocean-manager|chi|0.0.2
pioasm|chr|1.0.0
npm-intellisense|chr|1.4.4
vscode-postgres|cko|1.4.0
laravel-goto-view|cod|1.3.8
doxdocgen|csc|1.4.0
sqltools-databricks-driver|dat|0.4.1
vscode-eslint|dba|2.4.0
githistory|don|0.6.20
python-environment-manager|don|1.0.4
python-extension-pack|don|1.7.0
xml|Dot|2.5.1
micropython-ide-vscode|dph|0.0.1
rust-syntax|dus|0.6.1
ada-snippets|Ent|0.3.0
prettier-vscode|esb|9.10.4
vscode-fold|fel|1.4.3
git-project-manager|fel|1.8.2
vscode-solution-explorer|fer|0.8.1
vscode-firefox-debug|fir|2.9.8
auto-close-tag|for|0.5.14
auto-complete-tag|for|0.1.0
auto-rename-tag|for|0.1.10
code-runner|for|0.12.0
abap-snippets|fre|0.1.0
kotlin|fwc|0.2.26
vscode-chatgpt|gen|3.9.5
codespaces|Git|1.14.0
copilot|Git|1.77.9225
copilot-labs|Git|0.12.791
remotehub|Git|0.52.0
vscode-pull-request-github|Git|0.60.0
gitlab-workflow|Git|3.60.0
go|gol|0.38.0
google-cloud-spanner-driver|goo|0.4.1
guilhermestella-clojure-ext|gui|0.0.1
vscode-icf-syntax|Gui|0.0.2
vs-code-runner|Har|2.0.1
haskell|has|2.2.2
vscode-test-explorer|hbe|2.21.1
vue-snippets|hol|1.0.4
cds|hud|0.7.2
sqltools-oracle-driver|hur|0.1.6
vscode-lisp-formatter|imj|1.1.3
sqltools-intersystems-driver|int|0.1.1
Ionide-fsharp|Ion|7.5.1
cortex-debug-dp-stm32h7|jea|1.0.0
better-cpp-syntax|jef|1.17.2
sqltools-cassandra|Jor|0.2.3
cmake-language-support-vscode|jos|0.0.9
language-julia|jul|1.38.2
language-haskell|jus|3.6.0
vsc-python-indent|Kev|1.18.0
sqltools-driver-redshift|kj|0.0.4
unity-code-snippets|kle|1.3.0
snowflake-driver-for-sqltools|kos|0.5.0
vscode-abap|lar|0.5.7
vscode-abaplint|lar|0.6.206
unity-snippets-modified|lio|0.4.0
vscode-python-test-adapter|lit|0.7.1
inifmt|lkr|0.1.5
bash-ide-vscode|mad|1.35.0
autoconf|mae|0.2.0
cortex-debug|mar|1.10.0
cortex-debug-dp-stm32f1|mar|1.0.0
cortex-debug-dp-stm32f4|mar|1.0.0
cortex-debug-dp-stm32l4|mar|1.0.0
Kotlin|mat|1.7.1
Lisp|mat|0.1.12
debug-tracker-vscode|mcu|0.0.14
memory-view|mcu|0.0.20
rtos-views|mcu|0.0.6
ninja-syntax|mel|1.0.0
git-graph|mhu|1.30.0
embedded-development-pack|mis|0.1.0
vscode-docker|ms-|1.24.0
csharp|ms-|1.25.4
vscode-dotnet-runtime|ms-|1.6.0
isort|ms-|2022.8.0
python|ms-|2023.4.1
vscode-pylance|ms-|2023.3.20
remote-containers|ms-|0.282.0
remote-ssh-edit|ms-|0.84.0
remote-wsl|ms-|0.76.1
vscode-remote-extensionpack|ms-|0.24.0
azure-repos|ms-|0.28.0
cmake-tools|ms-|1.13.45
cpptools|ms-|1.14.4
cpptools-extension-pack|ms-|1.3.0
makefile-tools|ms-|0.6.0
remote-explorer|ms-|0.2.0
remote-repositories|ms-|0.30.0
remote-server|ms-|1.0.0
test-adapter-converter|ms-|0.1.6
vscode-serial-monitor|ms-|0.8.0
sqltools|mtx|0.27.1
sqltools-driver-mssql|mtx|0.4.1
sqltools-driver-mysql|mtx|0.5.1
sqltools-driver-pg|mtx|0.5.1
sqltools-driver-sqlite|mtx|0.5.0
vuejs-extension-pack|mub|1.9.0
vscode-abap-remote-fs|mur|1.6.2
winregistry|mur|0.0.1
gradle-language|nac|0.2.3
gremlins|nho|0.26.0
autodocstring|njp|0.6.1
stack-scopes|nov|1.4.1
ocaml-platform|oca|1.12.2
indent-rainbow|ode|8.3.1
docker-compose|p1c|0.3.5
phoityne-vscode|pho|0.0.29
unity-toolbox|pix|3.0.0
unity-code|Pra|0.0.2
gotestexplorer|pre|0.1.13
quicktype|qui|12.0.46
duckdb-sql-tools|Ran|1.0.2
fabric8-analytics|red|0.3.6
java|red|1.15.0
vscode-yaml|red|1.12.1
sqltools-trino-driver|reg|0.2.9
vscode-gradle-extension-pack|ric|0.0.4
nas-vscode|rig|0.0.1
bash-debug|rog|0.3.9
rust-analyzer|rus|0.3.1435
sap-hana-driver-for-sqltools|SAP|0.2.1
scala|sca|0.5.6
metals|sca|1.22.0
sqltools-teradata-driver|Scr|0.3.8
vue-vscode-snippets|sdr|3.1.1
crates|ser|0.5.10
kotlin-on-vscode|set|0.0.1
bash-beautify|sha|0.1.1
vscode-il|sol|0.0.1
avro|str|0.5.0
ninja|sur|0.0.1
rust-pack|Swe|0.3.3
unity-docs|Teg|0.3.1
vscode-status-bar-format-toggle|tom|3.1.1
cortex-debug-dp-efm32xg1|tri|1.0.0
gnu-mapfiles|tro|1.1.0
cmake|twx|0.0.17
sort-lines|Tyr|1.9.1
sqltools-clickhouse-driver|ult|0.2.5
vscode-lldb|vad|1.9.0
haskell-spotlight|vis|0.0.3
intellicode-api-usage-examples|Vis|0.2.7
vscodeintellicode|Vis|1.2.30
vscode-arduino|vsc|0.5.0
vscode-gradle|vsc|3.12.6
vscode-java-debug|vsc|0.49.0
vscode-java-dependency|vsc|0.21.1
vscode-java-pack|vsc|0.25.9
vscode-java-test|vsc|0.38.1
vscode-maven|vsc|0.40.4
vim|vsc|1.25.2
volar|Vue|1.2.0
vscode-typescript-vue-plugin|Vue|1.2.0
debug|web|0.26.1
jinja|who|0.0.8
JavaScriptSnippets|xab|1.8.0
php-debug|xde|1.32.0
php-pack|xde|1.0.3
cortex-debug-dp-stm32wl|zfi|1.0.0
vitest-explorer|Zix|0.2.39
linkerscript|Zix|1.0.3
php-intellisense|zob|1.1.2
vscode-proto3|zxh|0.5.5

(4 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vscaac:30438847
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
pynewext54:30681850
azure-dev_surveyone:30548225
pyindex848:30662994
nodejswelcome1:30587005
3biah626:30602489
pyind779:30671433
f6dab269:30613381
pythonsymbol12:30671437
a9j8j154:30646983
showlangstatbar:30672706
vsccsb:30677849
pythonb192:30669360
funwalk2:30682974
pythonms35cf:30686773

```

</details>

**Comment by ulugbekna** [comment]
Hi @fr0ster,

Thanks for filing the issue, but extension-specific issues should be reported to extensions. Here's the repository you want to report your problem to: https://github.com/ocamllabs/vscode-ocaml-platform/
