### ISSUE TITLE
terminal close, task not stop

### ISSUE THREAD

**Issue by cuifn** [microsoft/vscode#177163]
Type: <b>Bug</b>

after close terminal, the task trigger in the terminal is still run;

VS Code version: Code 1.76.1 (5e805b79fcb6ba4c2d23712967df89a089da575b, 2023-03-08T16:32:09.831Z)
OS version: Darwin x64 21.6.0
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|4, 4, 4|
|Memory (System)|16.00GB (0.18GB free)|
|Process Argv|--crash-reporter-id 9537647b-81b4-4e3c-810a-da50719f82e6|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (28)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|3.0.2
html-snippets|abu|0.2.1
jsx-html-tags|ang|1.0.1
cloudui|bla|0.0.12
vscode-css-modules|cli|0.4.2
miniprogram-vscode-extension|cra|1.4.15
doxdocgen|csc|1.4.0
vscode-markdownlint|Dav|0.49.0
vscode-eslint|dba|2.4.0
githistory|don|0.6.20
es7-react-js-snippets|dsz|4.4.3
gitlens|eam|13.3.2
prettier-vscode|esb|9.10.4
svg|joc|1.5.1
vscode-docker|ms-|1.24.0
vscode-language-pack-zh-hans|MS-|1.76.2023030809
remote-containers|ms-|0.282.0
vetur|oct|0.37.3
minapp-vscode|qiu|2.4.8
LiveServer|rit|5.7.9
vue-vscode-snippets|sdr|3.1.1
markdown-preview-enhanced|shd|0.6.8
vscode-stylelint|sty|1.2.4
svelte-vscode|sve|107.2.5
sass-indented|syl|1.8.26
js-annotation|wan|0.1.4
wx-snippets|wux|1.0.6
JavaScriptSnippets|xab|1.8.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
pynewvextcfv2:30681851
azure-dev_surveyone:30548225
vscccc:30610679
pyindex848:30662994
nodejswelcome1cf:30587006
2e4cg342:30602488
pyind779:30671433
f6dab269:30613381
pythonsymbol12:30671437
2i9eh265:30646982
showlangstatbar:30672706
funwalk2cf:30682975
pythonms35cf:30686773

```

</details>

**Comment by meganrogge** [comment]
A gif would be helpful to be sure I understand what you mean
