### ISSUE TITLE
Integrated Terminal Failed to Lanuch

### ISSUE THREAD

**Issue by StudyingFather** [microsoft/vscode#177161]
Does this issue occur when all extensions are disabled?: Yes

After upgrading to the latest version of VS Code, I found the integrated terminal failed to lanuch.

When I try to lanuch the terminal, an error message reported:

```plain
The terminal process failed to launch: A native exception occurred during launch (/usr/lib/code/node_modules.asar.unpacked/node-pty/build/Release/pty.node: undefined symbol: _ZN2v88internal20CanHaveInternalFieldEi).
```

(Sorry not to report the issue using 'Report Issue' from. When I try to use it, VS Code tells me "Activating extensions", with nothing happened later.)

- VS Code Version: 1.76.1 (5e805b7)
- OS Version: Arch Linux

Steps to Reproduce:

1. Launch VS Code with all extensions disabled.
2. Try to open the integrated terminal.
3. The terminal failed to start, with the error message mentioned above.

**Comment by neonmoe** [comment]
Probably an Arch Linux-specific issue: I had this exact issue, and it disappeared by updating my packages.

**Comment by StudyingFather** [comment]
After updating my packages again, this problem disappeared and everything works now.

Something went wrong during the packaging progress ([Arch Linux FS#77856](https://bugs.archlinux.org/task/77856)), and it was fixed in a short time (https://github.com/archlinux/svntogit-community/commit/b78bc23570af49b44f85f110ad34080144750d15).

I think it's time to close this issue.
