### ISSUE TITLE
error host

### ISSUE THREAD

**Issue by luisPabloDRM** [microsoft/vscode#177102]
Type: <b>Bug</b>

TODO EL RATO ME INUTILIZA LAS EXTENSIONES

VS Code version: Code 1.76.1 (5e805b79fcb6ba4c2d23712967df89a089da575b, 2023-03-08T16:32:00.131Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 5600G with Radeon Graphics          (12 x 3893)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.87GB (12.10GB free)|
|Process Argv|--crash-reporter-id bb8f4768-7292-4bc6-b3c8-e2f8650a934e|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (47)</summary>

Extension|Author (truncated)|Version
---|---|---
jsx-html-tags|ang|1.0.1
markdown-preview-github-styles|bie|1.0.1
vscode-intelephense-client|bme|1.9.5
simple-react-snippets|bur|1.2.7
discord-vscode|icr|5.6.4
vscode-eslint|dba|2.4.0
es7-react-js-snippets|dsz|4.4.3
vscode-html-css|ecm|1.13.1
vscode-npm-script|eg2|0.3.29
vsc-material-theme|Equ|33.6.0
vsc-material-theme-icons|equ|2.6.1
prettier-vscode|esb|9.10.4
auto-close-tag|for|0.5.14
copilot|Git|1.77.9225
activitusbar|Gru|0.0.47
rest-client|hum|0.25.1
path-autocomplete|ion|1.23.1
Angular2|joh|13.0.0
vscode-peacock|joh|4.2.2
twig-language-2|mbl|0.9.2
vscode-exec-node|mir|0.5.5
theme-monokai-pro-vscode|mon|1.2.0
vscode-language-pack-es|MS-|1.76.2023030809
python|ms-|2023.4.1
vscode-pylance|ms-|2023.3.20
vsliveshare|ms-|1.0.5834
sqltools|mtx|0.27.1
sqltools-driver-mysql|mtx|0.5.1
color-highlight|nau|2.5.0
prettier-vscode-with-tabs|pas|1.1.0
vscode-versionlens|pfl|1.5.0
vscode-php-getters-setters|php|1.2.3
material-icon-theme|PKi|4.24.0
vs-code-prettier-eslint|rve|5.1.0
js-jsx-snippets|sky|11.0.1
autoimport|ste|1.5.4
vscode-styled-components|sty|1.7.5
prettier-plus|svi|4.2.2
sass-indented|syl|1.8.26
errorlens|use|3.8.0
highlight-matching-tag|vin|0.11.0
vscode-import-cost|wix|3.3.0
php-debug|xde|1.32.0
php-pack|xde|1.0.3
material-theme|zhu|3.15.8
html-css-class-completion|Zig|1.20.0
php-intellisense|zob|1.1.2

(3 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscorecescf:30445987
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
pynewvextcfv2:30681851
azure-dev_surveyone:30548225
pyindex848:30662994
nodejswelcome1:30587005
2e4cg342:30602488
pyind779:30671433
89544117:30613380
pythonsymbol12:30671437
6233i204:30672705
funwalk2:30682974
pythonms35:30680984

```

</details>

**Comment by K2adir** [comment]
same issue, started to happen after the latest update
