### ISSUE TITLE
No problem in code but showing error on debug console

### ISSUE THREAD

**Issue by Myskar** [microsoft/vscode#177276]
Type: <b>Performance Issue</b>

1. Target kernel_snapshot failed
2. Build failed with an exception
3. where(Script 'C:\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 1153)
4. What went wrong:(Execution failed for task ':app:compileFlutterBuildDebug'.)
5. process(> Process 'command 'C:\flutter\bin\flutter.bat'' finished with non-zero exit value 1)

VS Code version: Code 1.76.2 (ee2b180d582a7f601fa6ecfdad8d9fd269ab1884, 2023-03-14T17:55:54.936Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz (8 x 1382)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|7.73GB (1.38GB free)|
|Process Argv|--crash-reporter-id 89daaef5-200b-48d6-b45c-1beecae88a75|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	   118	  4576	code main
    0	   174	  2996	   window (Untitled-1 - Login Page - Visual Studio Code)
    0	   128	  9948	   utility-process
    0	     4	  8380	     C:\WINDOWS\system32\cmd.exe /d /s /c ""C:\flutter\bin\cache\dart-sdk\bin\dart.exe" "language-server" "--protocol=lsp" "--client-id=VS-Code" "--client-version=3.60.1""
    0	    10	 14744	       console-window-host (Windows internal process)
    0	   330	 15296	       "C:\flutter\bin\cache\dart-sdk\bin\dart.exe"  "language-server" "--protocol=lsp" "--client-id=VS-Code" "--client-version=3.60.1"
    0	   124	 15272	         C:\flutter\bin\cache\dart-sdk\bin\dart.exe pub outdated --show-all --json
    0	    10	  8448	           console-window-host (Windows internal process)
    0	     5	  8464	     C:\WINDOWS\system32\cmd.exe /d /s /c ""C:\flutter\bin\flutter.bat" "daemon""
    0	   102	 11356	       electron-nodejs (config.js )
    0	    10	 14460	       console-window-host (Windows internal process)
    0	     4	  9600	     C:\WINDOWS\system32\cmd.exe /d /s /c ""C:\flutter\bin\cache\dart-sdk\bin\dart.exe" "devtools" "--machine" "--try-ports" "10" "--allow-embedding""
    0	    74	  2480	       "C:\flutter\bin\cache\dart-sdk\bin\dart.exe"  "devtools" "--machine" "--try-ports" "10" "--allow-embedding"
    0	    10	  5312	       console-window-host (Windows internal process)
    0	   139	 10044	   gpu-process
    0	    23	 11960	   crashpad-handler
    0	    94	 12540	   issue-reporter
    0	    38	 13232	   utility-network-service
    0	    90	 14532	   shared-process
    0	    50	  6588	     ptyHost
    0	    84	 11476	     fileWatcher
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (Untitled-1 - Login Page - Visual Studio Code)
|    Folder (Login Page): 266 files
|      File types: png(35) xml(12) xcconfig(10) h(9) json(7) properties(7)
|                  plist(7) gitignore(6) lock(6) swift(6)
|      Conf files: cmake(2) launch.json(1);
```

</details>
<details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
blackbox|Bla|0.10.39
dart-code|Dar|3.60.1
flutter|Dar|3.60.0
cpptools|ms-|1.14.4
material-icon-theme|PKi|4.24.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscoreces:30445986
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
pynewext54:30681850
azure-dev_surveyone:30548225
pyindex848:30662994
nodejswelcome1:30587005
282f8724:30602487
pyind779:30671433
89544117:30613380
vscrp:30673768
pythonsymbol12:30671437
vsccsb:30677849
pythonb192:30669360
funwalk2cf:30682975
pythonms35cf:30686773

```

</details>

**Comment by roblourens** [comment]
It seems like this might be an issue with your configuration/system/project setup
