### ISSUE TITLE
Extension recommendation occurs after extension has already been installed

### ISSUE THREAD

**Issue by bwateratmsft** [microsoft/vscode#177249]
Does this issue occur when all extensions are disabled?: N/A

_Originally from @v-ruizh in https://github.com/microsoft/vscode-docker/issues/3863_

**OS:** Windows 10
**Build Version:** 20230309.12
**Regression:** Not a Regression

**Repro Steps:**
1. Make sure there is Docker extension installed.
2. Open a Go project in VS Code.
3. Add docker files to this project and open Dockerfile.
4. Close and reopen VS Code.
5. Check whether there is no extra notification "Do you want to install the recommended extensions for Dockerfile?".

**Expect:**
There is no notification "Do you want to install the recommended extensions for Dockerfile?".

**Actual:**
There is an extra notification "Do you want to install the recommended extensions for Dockerfile?". 
![image](https://user-images.githubusercontent.com/45614674/225193301-eb696eea-38c4-46a2-941f-d23cb5e1b41c.png)
Click "Show Recommendations" button, it navigates to Docker extension page.
![image](https://user-images.githubusercontent.com/45614674/225193444-a5dcf5d9-cac9-4ea5-b388-6c9927ddf5bb.png)

**More Info:**
1. This issue also reproduces on the previous released Docker extension v1.24.0.
2. This issue does not reproduce for MVC/Express/Flask projects with Dockerfile opening.

**Comment by sandy081** [comment]
I am not able to reproduce the issue. Is it happening on a specific project? Can you please share the project if possible? Can you please try our [insiders](https://code.visualstudio.com/insiders) and see if you can repro?

**Comment by bwateratmsft** [comment]
@v-ruizh can you try these steps from @sandy081?

**Comment by v-ruizh** [comment]
@sandy081 This bug also reproduces on the latest VS Code Insiders 1.77.0. You can get the detailed info from below.
This is the project I used. [dockergo.zip](https://github.com/microsoft/vscode/files/10998493/dockergo.zip)

![test](https://user-images.githubusercontent.com/45614674/225830981-59ec8465-1f8b-49fc-9cf0-4a148b3bc815.gif)

**Comment by sandy081** [comment]
Very weird, I tried to repro it in Mac and Windows with the provided repo and I could not. Added some code to wait until installed extensions are known to the system. Please try with tomorrow's insiders and let me know if you are still seeing the issue. Thanks.

**Comment by v-ruizh** [comment]
Verified this issue on the latest VS Code Insiders build, it is no longer reproduce.

**Comment by sandy081** [comment]
Awesome. Thanks for confirmation!
