### ISSUE TITLE
Feature Request: add "when" clause contexts to Git

### ISSUE THREAD

**Issue by doronbrikman** [Microsoft/vscode#17722]
Feature request for adding a when clause contexts to Git.

It will enable the possibility to create simpler and shorter keyboard shortcuts when you are on the Git panel, like push or publish, instead of finding unique combination to every action like this.

**Comment by joaomoreno** [comment]
Fixed by adding an `activeViewlet` context key. It will take the `workbench.view.scm` value, when the SCM viewlet is visible.

**Comment by jrieken** [comment]
verified by code review
