### ISSUE TITLE
Won't work in W10 tablet mode split screen

### ISSUE THREAD

**Issue by lypanov** [Microsoft/vscode#17725]
- VSCode Version: 1.8.1
- OS Version: Windows 10 Anniversary Update

Steps to Reproduce:

1. Switch laptop to tablet mode.
2. Split screen Visual Studio Code together with for example powershell.

Expected result:
  vscode should be visible together with powershell in split screen.

Actual result:
  vscode maximizes thereby hiding the powershell window.

**Comment by jchadwick** [comment]
Is this still an issue?  I can't reproduce.

**Comment by lypanov** [comment]
@jchadwick Still able to reproduce alas. But... not 100% of the time. 2 days ago it was working fine again suddenly. This morning, it's broken again. Every time I try to split with Code it displays as half of the screen for a couple of hundred milliseconds and then switches me to full screen.

I see the same behavior in Task Manager today (yet Friday it was working!). MS Edge for example does not behave like this, nor do many other "classical" applications such as HeidiSQL. Exactly what differs between all this applications is beyond me.

In case it's of relevance Powershell/conhost also had this bug a long while back but that's been since fixed.

**Comment by bpasero** [comment]
@lypanov does it still reproduce with our 1.12 release?

**Comment by lypanov** [comment]
Yes still able to reproduce trivially.
