### ISSUE TITLE
Feature Request: Support for Jsonnet

### ISSUE THREAD

**Issue by dewdad** [Microsoft/vscode#17723]
There is a wonderful language by the name of [Jsonnet ](http://jsonnet.org) from Google. It is language for modeling JSON data with features like inheritance, variables, mixins. It is by far the best solution for templating that I have found for JSON as well.

**Comment by mrmlnc** [comment]
Sounds like a good idea for Extension.

**Comment by hausdorff** [comment]
Just as an FYI, I've put a first cut at a vscode extension for Jsonnet here: https://marketplace.visualstudio.com/items?itemName=heptio.jsonnet

I'm a complete extension noob, but I've tried my best to make it at least somewhat solid. Feedback welcome! :)

**Comment by mjbvz** [comment]
Closing as extension candidate. Please try  @hausdorff's extension
