### ISSUE TITLE
Extension installation: Error: "value" required in setHeader("X-Market-User-Id", value)

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#17721]
- VSCode Version: todays insider build
- OS Version: macOS

Steps to Reproduce:

1. try to install an extension
2. => Error: "value" required in setHeader("X-Market-User-Id", value)

I am also seeing quite some warnings in the dev console:

![image](https://cloud.githubusercontent.com/assets/900690/21420970/cae5e18c-c830-11e6-8559-54af971c2f4f.png)

**Comment by jrieken** [comment]
The warning message are unrelated, the details about them is explained here: https://github.com/Microsoft/vscode/issues/16508#issuecomment-268467591

The missing http header is a regression from using telemetry info which apparently lacks a machine id in the main process (fyi @joaomoreno). I have pushed a fix for the latter issue
