### ISSUE TITLE
checking for non-Latin characters in the selection

### ISSUE THREAD

**Issue by shtoormanSam** [microsoft/vscode#177215]
It happens that in the variable name there is a non-Latin character that looks exactly like Latin, but has a different code. Such errors (typos) are very difficult to catch visually.

It would be nice to have a hotkey to check the selection for non-Latin characters and highlight them.

**Comment by sbatten** [comment]
@shtoormanSam Does this setting help? `editor.unicodeHighlight.ambiguousCharacters`

**Comment by shtoormanSam** [comment]
Yes! Good feature, thanks!

**Comment by hediet** [comment]
> continues with Cyrillic, in this case ambiguous Latin characters are not highlighted:

This is by design. Our heuristic uses `к` as indicator for non ASCII characters being present. If you delete it, you get a warning.
