### ISSUE TITLE
HOME / END key navigation for list selection pop up menus (e.g. command palette)

### ISSUE THREAD

**Issue by dimateos** [microsoft/vscode#177201]
**It would be nice to be able to use `HOME` / `END` to go to the first / last item in a list pop up menu such as the command palette.** Right now an `UP` input loops to the end of the list (there could also be an option to disable that).

This feature would help keeping consistency with other UI elements, e.g. the explorer panel has no looping and works with `HOME` / `END`.

Here are some use cases:
* After moving down in the command palette you want to go back to the beginning. Manually hitting `UP` takes time and can easily overshoot and loop to the end.
* Go to the beginning of the `Select Color Theme` menu to hit the option to Browse additional community themes.
* _Same as the first but for different menus:_ input variable in a launch configuration, task launch list, insert snippets list, etc

> Also feel free to rename the issue, I could not think of a better way to reference the menus

**Comment by TylerLeonhardt** [comment]
Based on the code:
https://github.com/microsoft/vscode/blob/b9c2df39d16fc1f18654a07f476e05c9506952e2/src/vs/platform/quickinput/browser/quickInput.ts#L857-L868

`Ctrl`/`Cmd`+`Home`/`End` should do what you want. Can you confirm that that is true?

**Comment by dimateos** [comment]
Yep it does exaclty what I described. Thanks for taking the time and letting me know!

Okay I see now that `HOME`/`END` is reserved to move the cursor to the beginning/end of the input text BOX, like in a command line. Likewise, in a command line `Ctrl`+`HOME`/`END` usually scrolls to the beginning/end of the whole scrolling region.

Both things considered, I would leave it as it is. Seems clearly intended and consistent enough. The list selection at first glance looks like a list, but indeed this behavior makes sense.

**Comment by TylerLeonhardt** [comment]
I'm going to dupe this to https://github.com/microsoft/vscode/issues/98479 which will allow overriding these keybindings to be whatever the user wants. It feels like the right next step to enable any user preference for these keybindings.

/duplicate https://github.com/microsoft/vscode/issues/98479
