### ISSUE TITLE
CTRL + H

### ISSUE THREAD

**Issue by dncproduction** [microsoft/vscode#177224]
Type: <b>Performance Issue</b>

Dear Visual Studio Team

Thank you very much and congratulations for your beautiful work

I would like to purpose an enhancement, 

when the programmer selects lines, then press CTRL + F or CTRL+H, this is because he wants to search or replace something, so maybe, after discussion between members of your team, you may conclude that the FIND IN SELECTION must be automatically activated

What do you think ?

Sometimes, I make wrong actions because it's not automaticaly selected and it's very tiring cancel, and to take the mouse and click on this small button and reopérate the correct operation.

Thank you for your interest

Best regards

VS Code version: Code 1.76.1 (5e805b79fcb6ba4c2d23712967df89a089da575b, 2023-03-08T16:32:00.131Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: No

**Comment by ArturoDent** [comment]
There is a setting you might "find" helpful:

```
Editor > Find: Auto find in Selection
```

The default is `never`, sounds like you want the `multiline` or `always` option.
