### ISSUE TITLE
Error trying to sync settings

### ISSUE THREAD

**Issue by yunusemreaksu** [microsoft/vscode#177214]
I get the following error when trying to sync settings at https://github.dev/github/dev:

Ayarları Eşitleme etkinleştirilirken hata oluştu. {"error":"invalid_grant","error_description":"AADSTS500202: User account '{EmailHidden}' from external identity provider 'live.com' is not supported for API version '2.0'. Microsoft account pass-thru users and guests are not supported by the tenant-independent endpoint.

Version: 1.76.1
Commit: 5e805b79fcb6ba4c2d23712967df89a089da575b
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36 Edg/111.0.1661.41
Embedder: github.dev

**Comment by TylerLeonhardt** [comment]
@yunusemreaksu does this work for you in vscode.dev?

**Comment by yunusemreaksu** [comment]
@TylerLeonhardt  Yes, I'm not having any problems with vscode.dev.

**Comment by TylerLeonhardt** [comment]
Thanks for confirming. Since this seems scoped to github.dev, can you file this feedback over here?:
https://github.com/community/community/discussions/categories/codespaces

Thanks!
