### ISSUE TITLE
VScode auto-import not working in JSX

### ISSUE THREAD

**Issue by sentend** [microsoft/vscode#177225]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.76.1
- OS Version: Darwin arm64 22.3.0

When we write jsx code in return statement React vscode doesn't suggest current imported components, or new components which could be auto-imported, except if Component will be parent

1. 
<img width="503" alt="image" src="https://user-images.githubusercontent.com/95025705/225324489-94c58cea-cb24-44f3-aff5-5f9af211ac1b.png">
when we're usin component as a Parent

2. 
<img width="427" alt="image" src="https://user-images.githubusercontent.com/95025705/225324664-e16f7be3-3578-4555-b0bd-a19704fd2b35.png">
when we're using component in jsx statement

**Comment by mjbvz** [comment]
Looks like the second example is inside the body of jsx tag. This is just text content so auto imports are not expected to work here. They will work if you are inside a tag or embedded jsx expression

The one suggestion you see in the second case is coming from emmet
