### ISSUE TITLE
The ability to create global file templates of any type (as long as it's editable)

### ISSUE THREAD

**Issue by u84six** [microsoft/vscode#177248]
I'd like to be able to create file templates with boilerplate content. For example, I should be able to add a yaml template with content and then generate one in a project by selecting "create file from template", and then choosing my yaml template to generate a new file. This could be for all languages and property files (json, sonar-project.properties, toml, etc). I know there's a snippets feature, but I'd like to see this extended to a file template for more convenience.

**Comment by jrieken** [comment]
This exists as concept of snippets, they need to marked as `isFileTemplate` and will do exactly this. See https://github.com/microsoft/vscode/blob/3cd16d0d72bcd5d45547b9bc0059394a5094646a/extensions/html/snippets/html.code-snippets#L3 for a simple sample

**Comment by u84six** [comment]
Thanks for the info. I've added the "isFileTemplate" prop but not sure how to generate the file with the template body. I read the snippet documentation and it says there's a command "Snippets: Populate File from Snippet" but can't seem to find it. The only way I could find doing this is by creating a new file and then populating it with the snippet. But I don't see how I can generate a new file with the template already part of the doc (i.e. my original feature request)

**Comment by u84six** [comment]
> This exists as concept of snippets, they need to marked as `isFileTemplate` and will do exactly this. See
> 
> https://github.com/microsoft/vscode/blob/3cd16d0d72bcd5d45547b9bc0059394a5094646a/extensions/html/snippets/html.code-snippets#L3
> 
> for a simple sample

Thanks for the info. I've added the "isFileTemplate" prop but not sure how to generate the file with the template body. I read the snippet documentation and it says there's a command "Snippets: Populate File from Snippet" but can't seem to find it. The only way I could find doing this is by creating a new file and then populating it with the snippet. But I don't see how I can generate a new file with the template already part of the doc (i.e. my original feature request)

**Comment by jrieken** [comment]
The comment recently got renamed. It's now called "Fill File with Snippet". 

<img width="1261" alt="Screenshot 2023-03-16 at 14 53 46" src="https://user-images.githubusercontent.com/1794099/225638937-84512640-e10d-4dd7-88eb-2d52438d60b5.png">
