### ISSUE TITLE
VSCode URI scheme

### ISSUE THREAD

**Issue by tinganho** [Microsoft/vscode#17728]
It would be awesome if VSCode can support URI scheme:

```ts
code://path/to/file?line=1col=2
```

So if you click on any link on your computer it can open a file on VSCode and position the cursor on the correct line and column. 

I used this on sublime https://github.com/asuth/subl-handler before together with SASS debug info before sourcemaps was supported to jump back to Sublime Text for debugging CSS.

There is still some good use cases, except for the outdated SASS debug info. I for instance want to run:
```ts
tsc -w --pretty --uri-scheme code
```
And see errors and be able to jump back to VSCode to correct my code.

There are similar URI schemes developed for TextMate and Emcas:
https://github.com/purcell/emacs-handler

**Comment by joaomoreno** [comment]
It's

```
code://file/FULL/PATH/TO/FILE:1:2
```
