### ISSUE TITLE
Tunnel names are case sensitive but remoteAuthorities are not

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode#177222]
Currently, the tunnel name is case sensitive, and you can have two tunnels that differ only by casing.

This is problematic as the tunnel name is used in the remote authority `vscode-remote://tunnel+tunnelName/..`

URI-authorities are case insensitive. `vscode-remote://tunnel+foo/` is equal to `vscode-remote://tunnel+FOO/`.

We would have to encode the tunnel name in the authority, or we define that tunnel names are also case insensitive.
I suggest we do the latter.

**Comment by aeschli** [comment]
This doesn't yet seem to work for already persisted servers. 
The persisted settings are `{"name":"AESCHLI-SURFACE","id":"dgm3ggl2","cluster":"uks1"}`

After loading, the name should be lowercased, so that
https://github.com/microsoft/vscode/blob/efe37734ebbb492f02ae686cf605ec5b6343776a/cli/src/tunnels/dev_tunnels.rs#L388
will update the server name

**Comment by aeschli** [comment]
I wonder if we should still store the name in the original casing so we can use it for labels

![image](https://user-images.githubusercontent.com/6461412/227049920-b4d8a9da-657b-475f-a8d6-e1b078d58ee6.png)

**Comment by roblourens** [comment]
How does this work? On machine A I ran `code-insiders tunnel` and it gave me the name `vibrant-weaver`. On machine B I ran `code-insiders tunnel rename VIBRANT-weaver` and that succeeded

<img width="774" alt="image" src="https://user-images.githubusercontent.com/323878/235033811-6c7e2527-7f6c-4597-b5a0-c106de94d5b8.png">

But when I go to https://insiders.vscode.dev/tunnel/VIBRANT-weaver/ it connects to machine A, is that expected?

**Comment by rzhao271** [comment]
Step 2 fails for me. I need to use the exact casing, otherwise it says the tunnel isn't found. After I use the exact casing, it says I have an auth mismatch.

I start the tunnel foo-bar using the dedicated Insiders CLI on Windows in a Windows Terminal tab. I can connect to it just fine from Edge using any casing. Then, I create a new Windows Terminal tab and rename the tunnel to bar-FOO while it's still running. Then, I try opening a URL such as insiders.vscode.dev/tunnel/BAR-FOO or  insiders.vscode.dev/tunnel/bar-FOO and get the error above.

**Comment by aeschli** [comment]
Testing on Version: 1.78.0-insider
Commit: 657bb89984f37b810b250955570593cde0cd62eb
Date: 2023-05-02T11:22:37.024Z
Electron: 22.4.8
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Linux x64 5.14.0-1048-oem
Sandboxed: Yes

I see the same, exact csing is needed when connecting with the browser

- open VS Code desktop
- open the setting, set `"remote.tunnels.access.hostNameOverride": "KapitalT"`
- start the remote tunnel access using the Accounts menu: `Turn on Remote Server Access`
- from the popup, click in the vscode.insiders.dev link
- browser opens correcly
- in the browser URL change the casing and reopen:
https://insiders.vscode.dev/tunnel/KAPITALT/home/aeschli/workspaces/vscode-distro

Error dialog:
```
An unexpected error occurred that requires a reload of this page.
The workbench failed to connect to the server (Error: Could not find a tunnel named KAPITALT. Please make sure you are logged into the correct account. You can reloading, logging in, then running 'Connect to Remote Server'.)
```

**Comment by rzhao271** [comment]
I can't get past GitHub auth on insiders.vscode.dev when opening a tunnel link. Letting someone else verify this issue in case it's a misconfiguration on my end.
