### ISSUE TITLE
Revert change doesn't revert deleted/added lines anymore

### ISSUE THREAD

**Issue by Arxareon** [microsoft/vscode#177200]
Type: <b>Bug</b>

The `diffEditor.renderMarginRevertIcon` button no longer* copies deleted or added lines from left to right in the compare editor. In-line changes can be copied (or "reverted" as it's called - _not applicable name for all scenarios but that's besides the point_) from left to right but whole line changes (removed/added lines) cannot.

*It definitely worked before but I didn't catch which version broke it exactly.

I've tried disabling extensions but it's broken in the base app.

---

VS Code version: Code 1.76.1 (5e805b79fcb6ba4c2d23712967df89a089da575b, 2023-03-08T16:32:00.131Z)
OS version: Windows_NT x64 10.0.19045
Modes:
Sandboxed: No

**Comment by alexdima** [comment]
@Arxareon Were you perhaps using word wrapping? I recently fixed an issue there related to word wrapping -- https://github.com/microsoft/vscode/issues/179114

**Comment by Arxareon** [comment]
Yes I did!

I searched for duplicates but didn't think of trying in arrows I guess, but it does seem like the same issue. I will check.
Although, I couldn't add empty single lines from left to right either, but it could be related.

If the fix is live, I'll check if it's working.
Thanks for the response.

**Comment by alexdima** [comment]
:+1: VS Code Insiders contains now the fix. Please try it out there! Thank you!
