### ISSUE TITLE
Vertically split window is removed in full screen zen mode after moving tab

### ISSUE THREAD

**Issue by semsion** [microsoft/vscode#177255]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.76.2
- OS Version: Ubuntu 22.04.2 LTS

Steps to Reproduce:

1. Open an empty VSCode instance
2. Open x4 blank editor tabs
3. Drag tabs 3 and 4 to a right hand side vertically split window
4. Go full screen
5. Enter zen mode
6. Drag tab 3 or 4 to the left hand window split
7. Exit full screen 
8. The vertically split window has been removed

**Comment by semsion** [comment]
Version updated and the issue remains.

**Comment by rzhao271** [comment]
Unable to repro now. Let us know if the issue still occurs for you on VS Code 1.96.
