### ISSUE TITLE
Question regarding interoperability with an external C# service

### ISSUE THREAD

**Issue by JosephWoodward** [Microsoft/vscode#17730]
I'm currently building an extension to support .NET Core development (via Roslyn) in VS Code that needs to talk to a .NET Core service I've created and I have a few questions around the best approach given VS Code's extension capabilities.

First of all, what kind of model does VS Code provide to support such a task. I see VS Code has a concept of a language server. In my scenario would I create a language server that would interface between VS Code and my service, or are language servers strictly for enabling VS Code to provide multiple language support?

Also, given the use of OmniSharp in VS Code, could or should this be used for C# related tasks?

Many thanks

**Comment by DustinCampbell** [comment]
@JosephWoodward: You could certainly implement the language server protocol to provide language support for C# if that's your goal. For OmniSharp, take a look at the C# extension at https://github.com/OmniSharp/omnisharp-vscode. OmniSharp does not yet implement the language server protocol, so the C# extension must communicate with it via OmniSharp's protocol.

On a different note, we're always happy to have help in making the C# extension as good as possible for .NET Core developer. Please feel free to stop by the repo if you're interested in getting involved!

* The C# extension for Visual Studio Code: https://github.com/OmniSharp/omnisharp-vscode
* The OmniSharp server: https://github.com/OmniSharp/omnisharp-roslyn

**Comment by egamma** [comment]
Thanks @DustinCampbell for chiming in. I think this covers the question and I'm closing the issue.
