### ISSUE TITLE
Don't Show TSC Version Warning When Editing JS Files

### ISSUE THREAD

**Issue by sqnkov** [Microsoft/vscode#17736]
- VSCode Version: 1.8.1 (November Recovery)
- OS Version: Windows 10 Home

Steps to Reproduce:

1. Write javascript (not TS, just vanilla JS) for a random period of time.
2. Save your work occasionally.
3. Watch the error info with amusement.

I have been coding for like a full workday now and I just got an error stating the following:

![vscd](https://cloud.githubusercontent.com/assets/9406520/21431026/5793a334-c86e-11e6-80db-1c93cd971bb3.PNG)

And when I click the more information link, it routes me to [this section of the TypeScript information](https://code.visualstudio.com/docs/languages/typescript#_using-newer-typescript-versions):

I went on and updated my typescript version using **```npm install -g typescript@latest```** , I presume this the issue.

**Comment by egamma** [comment]
@sqnkov you have a globally installed version of typescript that doesn't match the typescript version that we bundle with VS Code. VS Code ships with the last official version of VS Code therefore `npm install typescript` would have been sufficient.

Having said this, the error message is confusing when you are editing a `.js` file where you typically do not use `tsc` and do not have TypeScript on our mind.

We should not show this warning when editing `.js` files.

**Comment by mjbvz** [comment]
@egamma Thanks for the clarification. I've updated the title of the issue to track not showing version warnings when editing js files.

**Comment by mjbvz** [comment]
I've scoped this check to only run when editing TypeScript files. Should be in the next insiders build
