### ISSUE TITLE
Breakpoint is unbound when deloveoping Vue application

### ISSUE THREAD

**Issue by lucasguo** [microsoft/vscode#177317]
Does this issue occur when all extensions are disabled?: Yes/No

Version: 1.76.2 (user setup)
Commit: ee2b180d582a7f601fa6ecfdad8d9fd269ab1884
Date: 2023-03-14T17:55:54.936Z
Electron: 19.1.11
Chromium: 102.0.5005.196
Node.js: 16.14.2
V8: 10.2.154.26-electron.0
OS: Windows_NT x64 10.0.22621
Sandboxed: Yes

I'm developing a vue application under vscode with extension "Mircosoft Edge Tools for VS code" installed.
Here is my launch.json

`{
  "version": "0.2.0",
  "configurations": [{
    "trace": true,
    "type": "msedge",
    "request": "launch",
    "name": "vue:edge",
    "url": "http://localhost:9527",
    "webRoot": "${workspaceFolder}",
    "sourceMaps": true
  }]
}`

When running this target, Edge browser opens up as expected.
Then I set a breakpoint in vscode, 
![image](https://user-images.githubusercontent.com/1881412/225521368-849dcc83-d6f0-45ea-b5de-39c236f3d55d.png)
the break point is unbound, then a new breakpoint is set automatically in the template section.
![image](https://user-images.githubusercontent.com/1881412/225521721-c8b7995d-49f4-4d98-88a6-8bb2b113d637.png)
And the breakpoint is not working as expected (the code is not stopped at that breakpoint).

The strange thing is, if I set the breakpoint in the Edge's Devtools as below, this breakpoint can be hit, and also automatically jump to vs code at the correct location.
![image](https://user-images.githubusercontent.com/1881412/225522355-326e20ab-157a-4ad1-8941-2bf44d90a43b.png)
![image](https://user-images.githubusercontent.com/1881412/225522542-37be1c12-4617-4391-bd27-9d8e1c072054.png)

The log file is attached here.
[vscode-debugadapter-a065570d.json.gz](https://github.com/microsoft/vscode/files/10986447/vscode-debugadapter-a065570d.json.gz)

Any help is appreciated.

**Comment by BinarySpike** [comment]
I'm having a similar issue with vite + `"serverReadyAction": { "action": "debugWithChrome",... } "`

**Comment by connor4312** [comment]
Thanks for the issue. It's currently not possible for us to set breakpoints in Vue apps correctly in many cases; please lend your support to https://github.com/vuejs/vue/issues/11023 to get this fixed.

**Comment by BinarySpike** [comment]
@conner4312

Something broke in chrome around the time this issue was opened and seems to have been patched.  You can see similar reports here: https://stackoverflow.com/questions/75740738/chrome-hangs-when-debugging-in-visual-studio-2022

I believe the original issue is related to vuejs/vue#11023 but want to make sure it's clear there is also an ongoing issue with chrome as well.

**Comment by connor4312** [comment]
Your comment refers to https://github.com/microsoft/vscode-js-debug/issues/1604
