### ISSUE TITLE
Can't open markdown preview and Develop Tools under Administrator

### ISSUE THREAD

**Issue by airmelt-ms** [microsoft/vscode#177323]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version:
  Version: 1.76.2 (user setup)
  Commit: ee2b180d582a7f601fa6ecfdad8d9fd269ab1884
  Date: 2023-03-14T17:55:54.936Z
  Electron: 19.1.11
  Chromium: 102.0.5005.196
  Node.js: 16.14.2
  V8: 10.2.154.26-electron.0
  OS: Windows_NT x64 10.0.22621
  Sandboxed: No
- OS Version: 
  Edition	Windows 11 Enterprise
  Version	22H2
  Installed on	‎09/‎16/‎2022
  OS build	22621.1413
  Experience	Windows Feature Experience Pack 1000.22639.1000.0

Steps to Reproduce:

1. Open VS Code by `Run as administrator`: 
  ![image](https://user-images.githubusercontent.com/110365725/225535413-837fb6a2-2d31-4103-96a7-6c79abc92f35.png)
2. Open any folder
3. Press `ctrl + shift + V` to show the preview of a md file: 
  ![image](https://user-images.githubusercontent.com/110365725/225535928-6910ed7d-af9b-4d98-85cc-3dd1ef2528a4.png)
4. Press `ctrl + shift + I` to show the `Toggle Develop Tools`, nothing happened

**Comment by deepak1556** [comment]
Merging to https://github.com/microsoft/vscode/issues/122951
