### ISSUE TITLE
k is not working in vscode

### ISSUE THREAD

**Issue by PolishettyAnanya** [microsoft/vscode#177355]
Type: <b>Feature Request</b>

please tell me how to use k as alphabet in vs code
when i am pressing k in vs code it is showing command not found

VS Code version: Code 1.76.2 (ee2b180d582a7f601fa6ecfdad8d9fd269ab1884, 2023-03-14T17:55:54.936Z)
OS version: Windows_NT x64 10.0.19045
Modes:
Sandboxed: No

**Comment by gjsjohnmurray** [comment]
Please open the Keyboard Shortcuts editor (Ctrl+K Ctrl+S is one way to do this), then search for an entry that has bound the K key to a command.

**Comment by PolishettyAnanya** [comment]
Tq sir
