### ISSUE TITLE
"Duplicate function implementation." Error underlining

### ISSUE THREAD

**Issue by gesslerpd** [Microsoft/vscode#1773]
When a JavaScript function is defined and committed to git, vscode takes further changes to the file and incorrectly notifies the user of a duplicate function implementation because of the older git version of the code and the edited version are thought to be different functions by vscode. After the change to the file is committed to git, the incorrect error underlining goes away.

**Comment by joaomoreno** [comment]
Can you provide a screen recording of the behaviour you mention?

**Comment by gesslerpd** [comment]
Error shows up when a change was made to the function while committed to git:

![bug](https://cloud.githubusercontent.com/assets/11217948/12125194/a0f33d2a-b3af-11e5-88f7-a564063abfc2.PNG)

Error persists when viewing the file not in the git difference view mode:

![image](https://cloud.githubusercontent.com/assets/11217948/12125211/b696f5f4-b3af-11e5-9e93-590e65d04cd1.png)

The red underlining "Duplicate function implementation" warning goes away after the change is committed to git:

![image](https://cloud.githubusercontent.com/assets/11217948/12125221/c9521354-b3af-11e5-849a-3c1ab212944a.png)

After Change is Committed:

![image](https://cloud.githubusercontent.com/assets/11217948/12125252/05bc14ac-b3b0-11e5-8e89-a9c36a2a2c74.png)


I'm thinking vscode somehow is taking the git difference version and not recognizing they are the same function and then incorrectly indicating there is an function duplication.

**Comment by gesslerpd** [comment]
The change doesn't even have to be made within the same function for this to occur, just the same file has to be edited, I just edited the function directly in this example.

**Comment by joaomoreno** [comment]
I can't seem to reproduce.

![image](https://cloud.githubusercontent.com/assets/22350/12140685/1d9e04b2-b46a-11e5-83f9-2c46638da393.png)

Which version of Code are you at?

**Comment by gesslerpd** [comment]
Version 

![image](https://cloud.githubusercontent.com/assets/11217948/12149297/934f09b0-b468-11e5-908c-90427f5c917a.png)

Also you typed `return params` but `params` doesn't exist in your function, so that javascript error may be possibly preventing you from reproducing the bug

**Comment by joaomoreno** [comment]
Absolutely, I can now reproduce. Steps:

- Create a `bug.js` file with the following contents:

```
function duplicateFunction(param) {
    
}
```

- Commit that.
- Reload Code.
- Add `return param;` to the body of that function.
- Open the file in the Git viewlet. The error will show up and stay around.

The `return` statement changes the function's signature and confuses the language service.

@jrieken I thought the read-only buffers were ignored from the language service.

**Comment by jrieken** [comment]
Closed with the adoption of Salsa (https://code.visualstudio.com/Updates#_languages-javascript).

**Comment by ilbonte** [comment]
Still have this bug in the latest version (1.12.1)

To reproduce 
1. create a new .ts file with a trivial function
2. compile the file (`tsc yourfile.ts`)
3. open the COMPILED .JS file (`yourfile.js`) in the same editor window (e.g. in another tab)
4. go back to the typescript tab and resume coding (e.g. add another few lines)
5. now you should see the error 

TO FIX

as mentioned before do `tsc -init` to initialize a `tsconfig.json` file in the same subfolder
