### ISSUE TITLE
Opening command palette doesn't work when go to file palette is open

### ISSUE THREAD

**Issue by drKnoxy** [Microsoft/vscode#17737]
- VSCode Version: 1.9.0-insiders
- OS Version: mac 10.12.1

Steps to Reproduce:

1. open vscode
2. open go to file palette with `cmd+p`
3. type `cmd+shift+p` to open the command palette 
4. *expect* opens command pallete
5. *err* opens the last file in the go-to file palette

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/10957
