### ISSUE TITLE
Cannot set break point from the sidebar

### ISSUE THREAD

**Issue by bartmao** [Microsoft/vscode#17733]
- VSCode Version: 1.8.1
- OS Version: Ubuntu 16.04.1 LTS

Steps to Reproduce:

1. Upgrade my VSCode to 1.8.1 or uninstall the order one and reinstall the newest. Both tried. 
2. The code window sidebar become narrower and cannot set break point anymore. See the snapshot attached below.
![untitled](https://cloud.githubusercontent.com/assets/4489728/21428776/ba536e50-c896-11e6-96a0-ff4cd29a3278.png)

**Comment by isidorn** [comment]
Open your settings and remove 
`"editor.glyphMargin": false`

**Comment by bartmao** [comment]
> "editor.glyphMargin": true

 is the default setting, right? I didn't change overwrite it and checked it's true currently. However the break point still cannot be inserted.

**Comment by bartmao** [comment]
I changed to 1.7.2 still having this issue. While changed back to my last version 1.4, everything goes back to normal:)

**Comment by isidorn** [comment]
@bartmao please check also your user and workspace settings. Probably you have a workspace setting which is overwriting your user setting.

Yes, true is the default.

**Comment by bartmao** [comment]
@isidorn, thanks for your patience and you're right, I just checked my workspace settings before and forgot to check my user settings, it shows a lot of overwritten setting after the upgrading. I don't know where do they come from, but the `"editor.glyphMargin": false` is included. Things going well after changing it:)
