### ISSUE TITLE
code tunnel asks to accept the server license terns 

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode#177351]
- install VS Code insiders on a new machine
- in a terminal run `code-insiders tunnel service install`
- you are prompted to authorise
- command terminates with
```
[2023-03-16 12:03:40] error Run this command again with --accept-server-license-terms to indicate your agreement.
```

Is that really necessary? The CLI is part of VS Code Desktop and my understanding is that by downloading/installing VS Code I agreed to license terms.

Also I just wanted to start the tunnel service, and the [code server license terms](https://code.visualstudio.com/license/server) seem to be unrelated (unless I know the internals of our remote architecture)

None of our other remote dev experiences asks for such agreement from the user.

If this is necessary, then we should ask for `--accept-server-license-terms` before asking to authorise

@bamurtaugh FYI

**Comment by aeschli** [comment]
```
[aeschli@kyrian-fedora-vm ~]$ code-insiders tunnel service install --accept-server-license-terms
error: Found argument '--accept-server-license-terms' which wasn't expected, or isn't valid in this context

	If you tried to supply `--accept-server-license-terms` as a value rather than a flag, use `-- --accept-server-license-terms`
```

**Comment by connor4312** [comment]
I will fix that arg not being present in `service install`. But asking is "by design" right now, pending any updates from Brigit or legal folks
