### ISSUE TITLE
VSCode Jupyter: "The editor could not be opened because the file was not found."

### ISSUE THREAD

**Issue by sabetAI** [microsoft/vscode#177388]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.75.0-insider
- OS Version: Ubuntu 20.04.5 LTS
- Jupyter Extension Version: v2023.2.1000541047 (pre-release)

Steps to Reproduce:
1. `bug.py`
```
def generate_bug():
    raise Exception
```
2. From a vscode jupyter cell, run 
```
from bug import generate_bug
generate_bug()
```
3. Click on link to file in stack trace.
<img width="261" alt="image" src="https://user-images.githubusercontent.com/28828395/225719161-a6e72907-e619-4ecb-b2ec-16445bbce3eb.png">

**Comment by amunger** [comment]
can you check what versions of ipython and ipykernel you're using?

```
import IPython
import ipykernel
print('ipykernel version: ', ipykernel.__version__)
print('IPython version: ', IPython.__version__)
```

this works for me with
ipykernel version:  6.21.2
IPython version:  8.10.0

**Comment by rebornix** [comment]
@sabetAI can you please update to latest Insiders to see if it works for you? it's working for me in 1.77-Insiders.

**Comment by sabetAI** [comment]
> 8.10.0

Upgraded to 
```
Version: 1.77.0-insider (Universal)
Commit: c97d5812f10c28efbcdb1fd404bc25afae873312
Date: 2023-03-16T05:22:31.950Z
Electron: 19.1.11
Chromium: 102.0.5005.196
Node.js: 16.14.2
V8: 10.2.154.26-electron.0
OS: Darwin arm64 21.6.0
Sandboxed: Yes
```

still getting the same issue.

**Comment by sabetAI** [comment]
> can you check what versions of ipython and ipykernel you're using?
> 
> ```
> import IPython
> import ipykernel
> print('ipykernel version: ', ipykernel.__version__)
> print('IPython version: ', IPython.__version__)
> ```
> 
> this works for me with ipykernel version: 6.21.2 IPython version: 8.10.0

Where do I set the kernel versions?

**Comment by amunger** [comment]
It's a package that is installed into your python environment, so it's controlled by whatever package manager you're using. You can check the version by just running that code I provided in a cell.

**Comment by sabetAI** [comment]
> It's a package that is installed into your python environment, so it's controlled by whatever package manager you're using. You can check the version by just running that code I provided in a cell.

I figured that's what you meant. Changed it but still got the same issue.

<img width="408" alt="image" src="https://user-images.githubusercontent.com/28828395/225973486-38d96845-659c-4355-be31-971731eeed53.png">

with this build of vscode

```
Version: 1.77.0-insider
Commit: c97d5812f10c28efbcdb1fd404bc25afae873312
Date: 2023-03-16T05:37:57.680Z (1 day ago)
Electron: 19.1.11
Chromium: 102.0.5005.196
Node.js: 16.14.2
V8: 10.2.154.26-electron.0
OS: Darwin arm64 21.6.0
Sandboxed: Yes
```

**Comment by amunger** [comment]
what does the link look like in the stack trace is it pointing to the correct place and end with a :[line number] 
e.g.
c:\src\test\7\bug.py:2

**Comment by sabetAI** [comment]
@amunger yes the link itself is correct. I can verify the path is correct by opening with vim from the command line.

**Comment by sabetAI** [comment]
@amunger actually, the file path is correct, but the line number isn't, says 252 but is actually 422:

<img width="1052" alt="image" src="https://user-images.githubusercontent.com/28828395/226123401-49b2a00f-9048-4cc0-ba54-22fbe1c8cb4f.png">

<img width="889" alt="image" src="https://user-images.githubusercontent.com/28828395/226123428-cc06b5d6-3f31-4817-a1df-d0da0f7cff16.png">

**Comment by sabetAI** [comment]
@amunger @rebornix any other thoughts? 😭

**Comment by amunger** [comment]
My suspicion is that the home alias `~` doesn't work correctly. Could you try printing a link each way and confirm if only the full filepath works (using a file that exists):

```
print('home/username/file.txt')
print('~/file.txt')
```

I don't know about the wrong line number, but we don't make any modifications to stack traces that come from the kernel, so that might be an issue with the kernel library.

**Comment by sabetAI** [comment]
Still doesn't work when I replace the ~ alias with `home/my_username`. However if I use `cmd+p` and paste the filename, it takes me to the source.

**Comment by amunger** [comment]
I think we just have some issues with linking from cell output on linux. From an ssh connection, I get some pretty inconsistent behavior:

![image](https://user-images.githubusercontent.com/2019016/227271693-490b2afa-641c-4a69-b3f9-2f248493f2ec.png)

So I can't even get full filepaths to register as links and clicking that `~` prefixed link will try to open a file in /aamunger/script.py, rather than the correct home location.

**Comment by sabetAI** [comment]
Cool. How to patch?

**Comment by mankiddyman** [comment]
have this issue too

**Comment by CatEek** [comment]
Any updates on this ?

**Comment by mankiddyman** [comment]
> Any updates on this ?

I switched to neovim

**Comment by amunger** [comment]
I believe this was fixed with https://github.com/microsoft/vscode/pull/196043, let us know if something still isn't working.
