### ISSUE TITLE
tunnel service not starting on fedora

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode#177356]
Fedora 29
Version 3.30.2

- install `code-insiders` from rpm
- in a 
- in a terminal run `code-insiders tunnel --accept-server-license-terms service install` (see #177351 for the need of `--accept-server-license-terms`)
- authorise 
command fails with 
```
[aeschli@kyrian-fedora-vm ~]$ code-insiders tunnel --accept-server-license-terms service install
...
[2023-03-16 13:24:30] info Successfully registered service...
[2023-03-16 13:24:30] info Successfully enabled unit files...
[2023-03-16 13:24:30] error error starting service: org.freedesktop.systemd1.NoSuchUnit: Unit code-insiders-tunnel.service not found.

```

I'm not expereinced with `systemd`. How can I debug this? Where should `code-insiders-tunnel.service` be?
`ls /etc/systemd/system/` does not show `code-insiders-tunnel.service`

No additional info in the log:
```
[aeschli@kyrian-fedora-vm ~]$ code-insiders tunnel service log
Unit code-insiders-tunnel.service could not be found.
-- Logs begin at Tue 2019-01-15 15:34:47 GMT. --

```

**Comment by connor4312** [comment]
From discussion: may have been on an old version of Fedora. I verified this works on the latest Fedora release.
