### ISSUE TITLE
`code-insiders tunnel service install` message should use `code-insiders`

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode#177344]
- Have a VSCode desktop insiders install
- in the Command prompt run `code-insiders tunnel service install`
Message is printed
```
Service successfully installed! You can use `code tunnel service log` to monitor it, and `code tunnel service uninstall` to remove it.`
```
should be  `code-insiders tunnel service log` and `code-insiders tunnel service uninstall`

**Comment by rzhao271** [comment]
Looks like the first half of the message has been fixed. On Insiders it now says

Service successfully installed! You can use `code-insiders tunnel service log` to monitor it, and `code tunnel service uninstall` to remove it.
