### ISSUE TITLE
FullScreen and mouse hover on debian jessie 8.6

### ISSUE THREAD

**Issue by paulovlobato** [Microsoft/vscode#17732]
- VSCode Version: Code 1.8.1 (ee428b0eead68bf0fb99ab5fdc4439be227b6281, 2016-12-19T14:41:20.664Z)
- OS Version: Linux x64 3.16.0-4-amd64 (Debian Jessie 8.6)
- Extensions:

|Extension|Author|Version|
|---|---|---|
|format-indent|Kasik96|1.3.0|

---

Bug on Debian Jessie 8.6 while on fullscreen and mouse hover.
On fullscreen, when hovering the mouse in any option such as the language selector on the taskbar, the the Go To Line selector, Indentation selector, Encoding Selector, Feedback, and many others, return a blue full screen just like the BSOD from Windows.

Steps to Reproduce:

1. Open Visual Studio on FullScreen using Debian 8.6
2. Hover the mouse on any option while on fullscreen.

**Comment by Tyriar** [comment]
Cannot repro in Ubuntu, are you able to take a screenshot or gif of this happening?

**Comment by paulovlobato** [comment]
Yep. I'll try making a gift of it as soon as I get back to work.

Regards

Enviado do meu dispositivo móvel

**Comment by paulovlobato** [comment]
Hey. Sorry about the late. I generated a GIF showing the issue. Don't know about the quality (recorded with my phone), but if wanted, I've the original video too

http://giphy.com/gifs/l0Exktm8DZFBK3CuY

**Comment by Tyriar** [comment]
Looks like an electron (or OS) issue /cc @bpasero

**Comment by paulovlobato** [comment]
Considering you couldn't reproduce it on Ubuntu, that's probably it. Any
way that I can confirm it's not a software issue?

Enviado do meu dispositivo móvel

**Comment by bpasero** [comment]
@paulovlobato still happening with 1.12?

**Comment by paulovlobato** [comment]
Version 1.12.2 seems fixed!

**Comment by Tyriar** [comment]
🎉
