### ISSUE TITLE
alt+click on directory should recursively collapse directories

### ISSUE THREAD

**Issue by cherealnice** [Microsoft/vscode#17743]
- VSCode Version: 1.8.0
- OS Version: OSX 10.12.2

Steps to Reproduce:

1. Open several directories within a project
2. alt+click on parent does not collapse them all

I know this is a minor issue, but it is very difficult to navigate larger projects with all directories displaying as open.

**Comment by bpasero** [comment]
This issue has already been reported. Please use the search function next time before reporting an issue and/or this time if you are curious about the progress of the issue.

**Comment by cherealnice** [comment]
Found it.  The title of the other issue seemed like it was just for expanding, but I see it's for both now.  Thanks!
