### ISSUE TITLE
TS Crash message

### ISSUE THREAD

**Issue by duranmla** [microsoft/vscode#177451]
Type: <b>Bug</b>

Not much to say I am using ts + react official template and it seems that it is crashing. Also, I can't format on save, I am using the browser to do so.

VS Code version: Code 1.76.2 (Universal) (ee2b180d582a7f601fa6ecfdad8d9fd269ab1884, 2023-03-14T17:54:09.061Z)
OS version: Darwin arm64 22.3.0
Modes:
Sandboxed: No
Remote OS version: Linux x64 5.15.63

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M2 Max (12 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|4, 5, 6|
|Memory (System)|64.00GB (0.60GB free)|
|Process Argv|--crash-reporter-id 8b06035a-0a03-4140-a3f6-9f89e97baa98|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: sandbox.4bvj4y.csb|
|OS|Linux x64 5.15.63|
|CPUs|AMD EPYC (2 x 2495)|
|Memory (System)|1.63GB (0.21GB free)|
|VM|0%|
</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
codesandbox-projects|Cod|0.2.72
mustache|daw|1.1.1
vscode-glimmer-syntax|lif|1.0.7
procfile-support|log|0.0.1
dotenv|mik|1.0.1
remote-containers|ms-|0.282.0
remote-ssh|ms-|0.98.0
remote-ssh-edit|ms-|0.84.0
remote-explorer|ms-|0.2.0
material-icon-theme|PKi|4.25.0
code-settings-sync|Sha|3.4.3
mdx|sil|0.1.1
vscode-ruby|win|0.28.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscorecescf:30445987
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vscaat:30438848
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
pynewvextcfv2:30681851
azure-dev_surveyone:30548225
vsccc:30610678
pyindex848:30662994
nodejswelcome1:30587005
282f8724:30602487
pyind779:30671433
f6dab269:30613381
vscrp:30673768
pythonsymbol12:30671437
vsccsb:30677849
pythonb192:30669360
defaultazurewalk:30687958
pythonms35cf:30686773

```

</details>

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

**Comment by duranmla** [comment]
I was able to run if I close VSCode and then let it open when I click the link on the browser, instead having VSCode already opened.
