### ISSUE TITLE
API documentation difficult to read due to bad heading hierarchy

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#1774]
Under the [workspace section in the API documentation](https://code.visualstudio.com/Docs/extensionAPI/vscode-api#_workspace), all headings seem to be `h3` which makes it difficult to determine which methods/properties headers belong to which section since all header text sizes are the same. It would be even worse when trying to navigate the document using a screen reader.

**Comment by egamma** [comment]
CC @gregvanl I think this belongs to vscode-docs

**Comment by bgashler1** [comment]
Assigning this to @jrieken who wrote the original gulp task that compiles the API docs: could you take a look at enabling H4 tags (one level deeper for H3s that have children)?  Let me know if you need help :)

Thanks!

**Comment by jrieken** [comment]
@SofianHn, @gregvanl I believe there was a reason why we did it that way. Is it that only then they show up in the right hand side navigation?

**Comment by SofianHn** [comment]
As far as I know there is no reason for it to be h3. We have the constrains for H2 in order to show in the right side navigation. I am looking with @bgashler1 to make the subs h4 and fix the styling to make it more readable.

**Comment by SofianHn** [comment]
@bgashler1 see the change in https://github.com/Microsoft/vscode/docs/commit/a2a1d3e8e208fdb06e36f75b0748b7adb5312b5d

this should introduce h4, assigning this to you for some css love.

**Comment by Tyriar** [comment]
Thanks for actioning this!

Fixed link: https://github.com/Microsoft/vscode-docs/commit/a2a1d3e8e208fdb06e36f75b0748b7adb5312b5d

**Comment by bgashler1** [comment]
![image](https://cloud.githubusercontent.com/assets/11839736/12252160/99140c18-b889-11e5-9800-2abad94189bd.png)
Added some margin on top (d9e90745f0d6008b5a34ee549737a67d01d7fd74) and it looks much better to me.  What do you think?  This isn't live yet (want feedback first).

**Comment by bgashler1** [comment]
It appears this issue has been resolved for a while.  If anyone still has problems, please feel free to reopen.
