### ISSUE TITLE
Compile x86_64-pc-windows-msvc

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#177436]
In almost every build since 2 days (?):

```
Generating script.
Script contents: shell
cargo build --release --target x86_64-pc-windows-msvc --bin=code
========================== Starting Command Output ===========================
"C:\Windows\system32\cmd.exe" /D /E:ON /V:OFF /S /C "CALL "D:\a\_work\_temp\7974daff-7b3c-4fd1-b2c6-f9610ca05368.cmd""
    Updating git repository `[https://github.com/microsoft/vscode-russh`](https://github.com/microsoft/vscode-russh%60)
error: failed to load source for dependency `russh`

Caused by:
  Unable to update https://github.com/microsoft/vscode-russh?branch=main#d22cf71d

Caused by:
  failed to clone into: C:\Users\cloudtest\.cargo\git\db\vscode-russh-68eec0b74a709420

Caused by:
  process didn't exit successfully: `git fetch --force --update-head-ok https://github.com/microsoft/vscode-russh +refs/heads/main:refs/remotes/origin/main` (exit code: 128)
  --- stderr
  fatal: unable to access 'https://github.com/microsoft/vscode-russh/': Could not resolve host: github.com
```

**Comment by aeschli** [comment]
`Could not resolve host: github.com` was very common in the builds from yesterday, at various stages in the WindowsX64 pipeline.

- checking out vscode repo: https://dev.azure.com/monacotools/Monaco/_build/results?buildId=206965&view=logs&j=c1b9e296-ed80-5b99-a0bc-c695b04e640a&t=131b7e5d-187d-5168-a61a-a3878ce24def

- checking out vscode-distro: https://dev.azure.com/monacotools/Monaco/_build/results?buildId=206959&view=logs&j=c1b9e296-ed80-5b99-a0bc-c695b04e640a&t=549496bb-69bd-50ab-4b4d-e63c9ca2a1cd

**Comment by connor4312** [comment]
Yea, this is a transient network thing it looks like. Per Lad, there is an ICM ticket about this for the builds folks, so I will close this issue.
