### ISSUE TITLE
When I save the file the cursor goes to the end of the file.

### ISSUE THREAD

**Issue by NirmalAswath003** [microsoft/vscode#177459]
Type: <b>Bug</b>

Have lots of code and press save at the top. The cursor automatically moves to the end of the page.

I need to again come back to the original point where I saved the file.(In javascript extenstion file)

At first it was working as it was supposed to  but after updating the VS code this happens.

VS Code version: Code 1.76.2 (ee2b180d582a7f601fa6ecfdad8d9fd269ab1884, 2023-03-14T17:55:54.936Z)
OS version: Windows_NT x64 10.0.19045
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.90GB (5.27GB free)|
|Process Argv|--crash-reporter-id c0bff344-ead9-4d10-9cdc-47244643637d|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (17)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-tailwindcss|bra|0.9.8
githistory|don|0.6.20
python-environment-manager|don|1.0.4
vscode-html-css|ecm|1.13.1
prettier-vscode|esb|9.10.4
json|Mee|0.1.2
isort|ms-|2022.8.0
python|ms-|2023.4.1
vscode-pylance|ms-|2023.3.20
jupyter|ms-|2023.2.1200692131
jupyter-keymap|ms-|1.1.0
jupyter-renderers|ms-|1.0.15
vscode-jupyter-cell-tags|ms-|0.1.7
vscode-jupyter-slideshow|ms-|0.1.5
LiveServer|rit|5.7.9
rust-analyzer|rus|0.3.1435
json|Zai|2.0.2

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vscaac:30438847
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
pynewvextcfv2:30681851
azure-dev_surveyone:30548225
vsccc:30610678
pyindex848:30662994
nodejswelcome1:30587005
3biah626:30602489
pyind779:30671433
89544117:30613380
pythonsymbol12:30671437
vsccsb:30677849
defaultazurewalk:30687958
pythonms35cf:30686773

```

</details>

**Comment by gjsjohnmurray** [comment]
Please use the `Start Extension Bisect` command to check whether this is being caused by one of your extensions.

**Comment by NirmalAswath003** [comment]
> Please use the `Start Extension Bisect` command to check whether this is being caused by one of your extensions.

Hi, you are right I am using Prettier code formatter that's what causing the cursor to go to the last line. Thanks for the identifying the issue.
