### ISSUE TITLE
Remove Install Extension and Do not Sync action

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#177481]
Look at telemetry and if not a lot of users are using the Install and Do not Sync extension action remove the action to simplify the Extension Install flow.

`extensions.install` is the action name.

fyi @sandy081 @esonnino

**Comment by sandy081** [comment]
> we keep it somewhere but not so prominent.

Any suggestions?

**Comment by isidorn** [comment]
We already have the "Sync Extension" check in the Extension context menu when it is installed - this is great.

![Screenshot 2023-06-06 at 11 58 12](https://github.com/microsoft/vscode/assets/1926584/5446ba10-2430-4318-99ee-13cbdd7f3849)

And we already have the "Sync Extension" check in the same context menu when it is not installed.
Just currently if I click this, there is no effect.

So ideally the experience would be that I can uncheck this before installing the extension.
And thus we need no new actions.

![Screenshot 2023-06-06 at 11 59 11](https://github.com/microsoft/vscode/assets/1926584/4c302a9b-0455-437b-9bab-8dd034988d9f)

**Comment by sandy081** [comment]
Lets try this in insiders already and see if we get any hit back.

**Comment by isidorn** [comment]
Awesome - thanks!
