### ISSUE TITLE
Scrolling issues with precision touchpad.

### ISSUE THREAD

**Issue by pandhersaab27** [Microsoft/vscode#17747]
- VSCode Version: Code 1.8.1 (ee428b0eead68bf0fb99ab5fdc4439be227b6281, 2016-12-19T14:49:23.350Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

|Extension|Author|Version|
|---|---|---|
|csharp|ms-vscode|1.6.0|

---

Steps to Reproduce:

1. Open file from a VS project.
2. Scrolling of file is very jittery.

Steps to resolve:
1. Resize window by any means full screen using maximize button or just resize using corner dragging and it works fine.

**Comment by dahnny012** [comment]
Thanks for the resolution I almost had to use Atom.

**Comment by alexandrudima** [comment]
Indeed, let's track in those issues. These were introduced when we adopted the current version of Electron. Hopefully they will go away once we update again next milestone. Known workarounds: resize (restore) and then maximize VS Code back. Let's track in the other issues.

**Comment by bpasero** [comment]
Todays VS Code insider build comes with Electron 1.6.x, would be interesting to hear if this update solves this issue for anyone: http://code.visualstudio.com/Download#insiders

**Comment by GJGMFB** [comment]
Is not solved on 1.12.0-insider (9530cf6e2b804c4b986d97f105f88d40ee4d2c47, 2017-04-14T11:59:40.760Z). Resizing the window, then maximizing still fixes delayed scrolling. Running on a Surface Book i5 w/ dGPU.

**Comment by Devanist** [comment]
@pandhersaab27 thanks for the tip with resizing, much better than restarting vsc.

problem occurring on Dell Inspiron 7567 i5 with GTX 1050

**Comment by alexandrudima** [comment]
Let's merge this issue into #13612

There is now a wiki page that documents a summary of the presented workarounds -- https://github.com/Microsoft/vscode/wiki/Known-issues
