### ISSUE TITLE
Rendering becomes rough

### ISSUE THREAD

**Issue by H3Chr** [microsoft/vscode#177466]
Type: <b>Bug</b>

Every window in VSCode draws rough.
Includes editor, menu bar and issue reporting window.
When I click on the window the problem disappears.

<img width="612" alt="image" src="https://user-images.githubusercontent.com/59731381/225909551-0a0c7d7a-4752-4d92-a7c9-e9dc6b8b4ba6.png">

![image](https://user-images.githubusercontent.com/59731381/225909363-42d4f1f3-cd27-4c06-ad24-de51840344e6.png)

VS Code version: Code 1.76.0 (92da9481c0904c6adfe372c12da3b7748d74bdcb, 2023-03-01T10:22:44.506Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-11700K @ 3.60GHz (16 x 3600)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.84GB (15.91GB free)|
|Process Argv|D:\\SteamLibrary\\steamapps\\common\\assettocorsa\\content\\cars\\mazda_cx60_e-skyd_2022\\skins\\02_soul_red_crystal_metalic\\ext_config.ini --crash-reporter-id b99b969c-b3fd-417f-b81d-314015c6e73f|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (35)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-twitter|aus|0.8.3
systemd-unit-file|coo|1.0.6
doxdocgen|csc|1.4.0
c-cpp-runner|fra|5.1.2
language-hsp3|hon|1.1.1
better-cpp-syntax|jef|1.17.2
cmake-language-support-vscode|jos|0.0.9
vscode-language-pack-ja|MS-|1.76.2023031509
vscode-dotnet-runtime|ms-|1.6.0
isort|ms-|2022.8.0
python|ms-|2023.4.1
vscode-pylance|ms-|2023.3.20
jupyter|ms-|2023.2.1200692131
vscode-jupyter-cell-tags|ms-|0.1.7
vscode-jupyter-slideshow|ms-|0.1.5
remote-containers|ms-|0.282.0
remote-ssh|ms-|0.98.0
remote-wsl|ms-|0.76.1
cmake-tools|ms-|1.13.45
cpptools|ms-|1.14.4
cpptools-extension-pack|ms-|1.3.0
makefile-tools|ms-|0.6.0
powershell|ms-|2023.2.1
remote-explorer|ms-|0.2.0
vscode-3dviewer|sle|0.2.2
lua|sum|3.6.17
pdf|tom|1.2.2
cmake|twx|0.0.17
language-hsp3-constant|UMA|2.0.1
language-hsp3-ex|UMA|1.0.1
assetto-corsa-csp-api-for-vscode|und|0.7.3
vscode-lldb|vad|1.9.0
hsp3-analyzer-mini|vai|0.4.0
hsp3-debug-window-adapter|vai|0.5.0
hsp3-vscode-syntax|vai|0.3.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscoreces:30445986
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
pynewext54:30681850
azure-dev_surveyone:30548225
pyindex848:30662994
nodejswelcome1cf:30587006
282f8724:30602487
pyind779:30671433
89544117:30613380
pythonsymbol12:30671437
vsctsb:30677850
funwalk2cf:30682975
pythonms35cf:30680985

```

</details>

**Comment by rzhao271** [comment]
Does launching Code from the terminal with `code --disable-gpu` help?

**Comment by deepak1556** [comment]
You can continue to disable hardware acceleration via the following setting https://code.visualstudio.com/updates/v1_40#_disable-gpu-acceleration. This might get addressed with future runtime updates.
