### ISSUE TITLE
Add Git Autocomplete to terminal

### ISSUE THREAD

**Issue by ReganRyanNZ** [Microsoft/vscode#17748]
Pressing tab to autocomplete works for terminal commands like `cd` etc, but not for git commands (or git branches). This would be a great addition to VS code.

**Comment by stealthybox** [comment]
Hi,

This is an issue with how you've configured your shell -- not VSCode.
(my tab-completion works in VSCode)

It sounds like you're on a UNIX system -- git normally comes with a bash-completion file,
You need to tell your system to source it for it to work.

Please close this issue -- Thanks!

**Comment by egamma** [comment]
@stealthybox thanks for chiming, closing.
