### ISSUE TITLE
Incorrect prints within error statements (Jupyter notebook Python)

### ISSUE THREAD

**Issue by Jako-K** [microsoft/vscode#177405]
Does this issue occur when all extensions are disabled?: Yes

VS Version: 1.76.2
OS: Windows_NT x64 10.0.22621

Jupyter notebook within VScode fail to display certain strings within error statements. A simple case is provided below. By the way, this prints correctly when I use jupyer notebook in the browser.

```python 
def test(name):
    if not isinstance(name, str):
        error = f"Expected type `str`, but received type `{type(name)}`"
        print(error) # Works fine
        raise TypeError(error) # Incorrect print
test(1)

```
![vs_bug_out](https://user-images.githubusercontent.com/78201238/225746800-7295c166-7639-4659-96c8-83bd0f130c57.png)

**Comment by amunger** [comment]
We need to treat the stack as HTML so we can correctly display links when we are able to provide them, but we should be escaping any HTML tags before we inject the generated links.

**Comment by eleanorjboyd** [comment]
still seeing this:
![Screenshot 2023-04-27 at 08 56 49](https://user-images.githubusercontent.com/26030610/234918854-1072c549-1c8b-4b16-87e9-e4612ea945bd.png)

**Comment by amunger** [comment]
yeah I don't think @rebornix's change actually fixed this, it was just related but only affects untrusted workspaces.
