### ISSUE TITLE
When filtering the Explorer, can't always expand the highlighted directory using the keyboard

### ISSUE THREAD

**Issue by bruno-brant** [microsoft/vscode#177444]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.77.0-insider
- OS Version: Windows 10

Steps to Reproduce:

- Select the Explorer tab and filter it by a file name, `foo.bar`, by clicking CTRL+F and typing the file name, then selecting the filter icon (three horizontal lines). 
- The explorer don't immediately filters out directories that don't contain the required file. To "clean" the list, one could use the keyboard by repeatedly pressing arrow left to expand the directory and arrow down to select the next directory
- Pressing arrow left on a directory that don't contain the required file will remove it from the list. The selection/highlight immediately moves to the next directory in the list. However, if you press again the left arrow nothing happens. 

You can solve the isse above by simply pressing arrow down or up to select another directory and then again use the arrow keys to return to the previous selected directory.

Personally, I would prefer that VSCode would automatically filter out directories that are empty, but I'm guessing this might involve scanning the file system and was avoided for performance reasons.

**Comment by xc1427** [comment]
I reported the same issue. Making a search in expanded `node_modules` in Explorer is almost unusable.

I noticed the old version vscode does filter out directories that don't contain the requested file. See https://code.visualstudio.com/updates/v1_70#_tree-find-control

Maybe we can add a new option to let users select the desired behavior.

**Comment by gjsjohnmurray** [comment]
> I noticed the old version vscode does filter out directories that don't contain the requested file.

I think a previous version would filter out an **unresolved** directory whose name didn't match the filter. An unresolved directory is one that hasn't ever been expanded during the current session.

What @bruno-brant reports is a bug with the behaviour I implemented in #167047. I am able to reproduce it. Pinging @joaomoreno who handled that PR.

**Comment by xc1427** [comment]
I've got the motivation behind [#167047](https://github.com/microsoft/vscode/pull/167047) . However, the new behavior makes searching in expanded node_modules in Explorer almost unusable. Maybe we could add an option between "filter out unresolved directory" or "retain unresolved directory".

**Comment by gjsjohnmurray** [comment]
@xc1427 I don't understand what you mean, but it **does** seem clear to me that your issue isn't the same as the one @bruno-brant opened here. I suggest you open a new issue for yours, with exact repro steps and perhaps also a short screen recording.

**Comment by xc1427** [comment]
@gjsjohnmurray Sure. My issue is not related to this bug. I will open another issue for clarity. Thank you

**Comment by joaomoreno** [comment]
> Pressing arrow left on a directory that don't contain the required file will remove it from the list. The selection/highlight immediately moves to the next directory in the list. However, if you press again the left arrow nothing happens.

I'm guessing you mean the right arrow.

**Comment by gjsjohnmurray** [comment]
I have submitted a PR to fix this.
