### ISSUE TITLE
Enter to rename file in explorer no longer works

### ISSUE THREAD

**Issue by heswell** [microsoft/vscode#177455]
Type: <b>Bug</b>

Having selected a file in Explorer, ENTER should display the filename in editable mode so I can rename the file. The context menu 'rename' menu item still suggests that this is expected behaviour (shows ENTER as the shortcut).

As of latest upgrade, no longer works. Instead of entering edit mode on the Explorer tree item, focus is shifted to the editor. 

Either this is an intentional change and the context menu shortcut-key hint is now wrong, ot its a bug in behaviour.

I hope its the latter (and will be fixed, obviously) as I use this behaviour a lot.

thanks

VS Code version: Code 1.76.1 (5e805b79fcb6ba4c2d23712967df89a089da575b, 2023-03-08T16:48:08.231Z)
OS version: Darwin arm64 21.6.0
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M2 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|2, 2, 2|
|Memory (System)|24.00GB (0.71GB free)|
|Process Argv|--crash-reporter-id df07a87b-7b60-48a3-9c25-d9d554787ab6|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|2.4.0
gitlens|eam|13.4.0
prettier-vscode|esb|9.10.4
vscode-peacock|joh|4.2.2
l13-diff|L13|1.1.0
git-graph|mhu|1.30.0
vscode-antlr4|mik|2.3.1
svg-preview|Sim|2.8.3
vscode-lezer|tam|0.14.0
vscode-todo-highlight|way|1.0.5
jar-viewer|wma|1.2.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
pynewvextcfv2:30681851
azure-dev_surveyonecf:30548226
pyindex848:30662994
nodejswelcome1:30587005
3biah626:30602489
pyind779:30671433
f6dab269:30613381
vscrpc:30673769
pythonsymbol12:30671437
showlangstatbar:30672706
vsctsb:30677850
vscodeenable:30660116
defaultazurewalk:30687958
pythonms35:30686772

```

</details>

**Comment by heswell** [comment]
Updated to 1.76.2, no difference in behaviour described above

**Comment by heswell** [comment]
Interesting, I've done neither to my knowledge , although I've been using this behaviour for as long as I can remember, so I might have set something long ago and forgotten,
If I disable all extensions , the behaviour remains the same. I don't have anything relevant in my local settings.json.
What would I look for to spot a Keyboard shortcut override ?

In any case, something has changed . I use this functionality so frequently that I noticed immediately that it now behaves differently. I haven't installed or updated any extensions recently.

**Comment by gjsjohnmurray** [comment]
When you search for `renamefile` in keyboard Shortcuts editor what do you get? Mine is like this:

![image](https://user-images.githubusercontent.com/6726799/225917597-4ba7a4e8-56bd-4f1b-ac1a-ef1f7e920b7d.png)

**Comment by lramos15** [comment]
> The standard shortcut key for `Rename...` on the context menu of a file in Explorer is `F2`.
> 
> Have you installed an extension to make this become `Enter`? Or have you used the Keyboard Shortcuts editor?

It's enter on macOS

**Comment by lramos15** [comment]
@heswell Can you try entering doing `CMD + SHIFT + P` and entering `Reset View Locations`. My guess is your explorer context keys got messed up.

**Comment by heswell** [comment]
Reset View Locations has fixed the problem for me. Thank you very much. And just to clarify - the keybinding that the Shortcut Keys editor shows me for `renamefile` is `ENTER` and enter does now work again as previously.

I still do not recall ever having manually set this keybinding, but I'll keep it the way it is, I use rename a lot from the explorer and enter is more convenient than F2.

thanks again.
