### ISSUE TITLE
"Could not find pty on pty host" when install extensions on ssh remote 

### ISSUE THREAD

**Issue by PeterWang-dev** [microsoft/vscode#177460]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.76.2 (system setup) submit: ee2b180d582a7f601fa6ecfdad8d9fd269ab1884
- OS Version:  Windows 11 Home Edition 22H2 22621.1413
- Remote OS: Linux ArchLinux 6.2.6-zen1-1-zen ZEN SMP PREEMPT_DYNAMIC x86_64 GNU/Linux

Steps to Reproduce:

1. Connect to a remote ssh host.
2. Install an extension such as 'ms-ceintl.vscode-language-pack-zh-hans'.
3. Remote extension host crash.

**Comment by PeterWang-dev** [comment]
Is there any one dealing this issue?

**Comment by PeterWang-dev** [comment]
I have located the issue. I ran bin/code-server on my remote machine, finding out that the port 8000 for Extension Host was occupied. After closing the process, everything works well.
BTW, is there any way to change the port Extension Host listening?

**Comment by alexdima** [comment]
@PeterWang-dev I cannot reproduce:


https://user-images.githubusercontent.com/5047891/226492355-0acee749-5aeb-439f-8b6c-289b2cb15a39.mp4

**Comment by PeterWang-dev** [comment]
> @PeterWang-dev I cannot reproduce:

The problem is the port extension host listening has been occupied., not a problem of vscode.
I will close this issue and open a new feature request if needed.
