### ISSUE TITLE
vim stops working

### ISSUE THREAD

**Issue by calam1** [Microsoft/vscode#17741]
- VSCode Version:1.8.1
- OS Version:osx 10.12.2

Steps to Reproduce:

1. I have installed different versions of the vim plugin vim and amvim
2. I use the command line to open vim , i,e, code .
3. After interacting with a file, and typically moving around the file using the h, j, k, and l keys the editor no longer allows me to edit.  I can still move around using the arrow keys, but I can no longer enter text in the edit pane, or in the sidebar, i.e. extensions.  I always have to kill code to get it working again.  This behavior is inconsistent, at first it was happening all the time, then it didn't happen for a couple of days, now it is happening all the time again.

**Comment by egamma** [comment]
Please file the issue against the VIM extension that shows the problem. Our recommended VIM extension to use is https://marketplace.visualstudio.com/items?itemName=vscodevim.vim.
