### ISSUE TITLE
Revert change no longer possible inline within submodules

### ISSUE THREAD

**Issue by DFelten** [microsoft/vscode#177453]
Type: <b>Bug</b>

It's no longer possible to revert changes inline within a submodule. The dialog appears, but when selecting revert change nothing happens. In the submodule it is not possible to undo changes. But in the main repository it is possible.

I already created an issue here, but the fix did not affect the submodules: https://github.com/microsoft/vscode/issues/175535 and https://github.com/microsoft/vscode/issues/176051

<details>
<summary>Example video</summary>

https://user-images.githubusercontent.com/1169185/225607453-4fd73cb2-9393-43b1-b325-0ec379d8ad3a.mp4
</details>

### Steps to reproduce:

1. Open a Git repository with a submodule with VSCode
2. Change something within the submodule
3. Try to revert the change inline

Inside this folder create three additional folders

VS Code version: Code - Insiders 1.77.0-insider (c97d5812f10c28efbcdb1fd404bc25afae873312, 2023-03-16T05:37:57.680Z)
OS version: Darwin arm64 22.3.0
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Max (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|2, 3, 4|
|Memory (System)|32.00GB (0.23GB free)|
|Process Argv|--crash-reporter-id 511166e9-0c5e-4225-a6af-efd2d90c3f8d|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (88)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|3.0.2
codesnap|adp|1.3.4
vscode-m3u|af4|1.0.0
TabOut|alb|0.2.2
Bookmarks|ale|13.3.1
project-manager|ale|12.7.0
flutter-snippets|ale|3.0.0
toggle-excluded-files|amo|2.0.0
clipboard-history|Anj|1.0.7
melos-code|bla|0.6.0
vscode-intelephense-client|bme|1.9.5
ccs-flutter-color|cir|1.0.2
gitignore|cod|0.9.0
vscode-mysql-client2|cwe|6.2.7
vscode-mac-color-picker|dae|1.1.0
markdown-table-prettify|dar|3.6.0
dart-code|Dar|3.61.20230307
flutter|Dar|3.60.0
vscode-markdownlint|Dav|0.49.0
githistory|don|0.6.20
gitlens|eam|13.4.0
bloc|Fel|6.6.3
mason|Fel|0.1.10
flutter-coverage|flu|0.0.4
shell-format|fox|7.2.5
vscode-chatgpt|gen|3.9.7
copilot|Git|1.78.9758
copilot-labs|Git|0.12.791
vscode-pull-request-github|Git|0.60.0
gitlab-workflow|Git|3.60.0
todo-tree|Gru|0.0.224
terraform|has|2.25.4
json-to-dart|hir|3.5.8
rest-client|hum|0.25.1
monkey-patch|ioc|0.1.23
pubspec-assist|jer|2.3.2
shortcut-menu-bar|jer|3.0.4
intellij-idea-keybindings|k--|1.5.7
indent-to-bracket|LAK|1.2.2
flutter-intl|loc|1.19.1
syntax-project-pbxproj|mar|0.1.3
flutter-snippets|Mar|1.0.5
Kotlin|mat|1.7.1
rainbow-csv|mec|3.5.0
git-graph|mhu|1.30.0
dart-barrel-file-generator|miq|6.0.0
diff-merge|mos|0.7.0
vscode-docker|ms-|1.24.0
vscode-language-pack-de|MS-|1.76.2023030809
remote-containers|ms-|0.284.0
live-server|ms-|0.4.7
vsliveshare|ms-|1.0.5834
vsliveshare-pack|ms-|0.4.0
vscode-flutter-freezed-helper|mth|0.1.0
sqltools|mtx|0.27.1
sqltools-driver-mysql|mtx|0.5.1
awesome-flutter-snippets|Nas|4.0.1
vscode-streamdeck|nic|4.1.6
vscode-yaml-sort|Pas|6.5.0
vscode-versionlens|pfl|1.5.0
material-icon-theme|PKi|4.25.0
remove-comments|pli|1.2.2
vscode-thunder-client|ran|2.5.1
java|red|1.16.2023031504
vscode-yaml|red|1.12.1
vscode-sort-json|ric|1.20.0
command-variable|rio|1.49.1
flutter-riverpod-snippets|rob|1.2.2
vscode-coverage-gutters|rya|2.10.3
lcov-lang|Ser|1.0.1
swift-lang|ssw|1.1.0
freezed-model-gen|Sus|1.0.1
better-search|tra|0.0.6
errorlens|use|3.8.0
vscode-lldb|vad|1.9.0
intellicode-api-usage-examples|Vis|0.2.7
vscodeintellicode|Vis|1.2.30
vscode-java-debug|vsc|0.49.2023022723
vscode-java-dependency|vsc|0.21.2023030900
vscode-java-pack|vsc|0.25.2023031705
vscode-java-test|vsc|0.38.2023030203
vscode-maven|vsc|0.40.2023031703
vscode-wakatime|Wak|24.0.7
vscode-todo-highlight|way|1.0.5
php-debug|xde|1.32.0
vscode-surround|yat|1.5.0
markdown-all-in-one|yzh|3.5.0
material-theme|zhu|3.15.8

(3 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256198
vslsvsres303:30308271
pythonvspyl392:30422396
pythontb:30258533
vsc_aa:30263845
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscod805cf:30301675
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30404738
cppdebug:30492333
vsclangdf:30492506
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30618038
pylantcb52:30590116
pyindex848:30611229
nodejswelcome1:30587009
pyind779:30611226
pythonsymbol12:30651887
showlangstatbar:30659908
pythonb192cf:30661257
functionswalk:30687959
pythonms35:30671666
03d35959:30680466
ecj1e332:30687743

```

</details>

**Comment by lszomoru** [comment]
@odeialba, are you using Stable or Insiders? The fix for this is currently only available in Insiders. It will be included in the March stable release that is scheduled for later this week.

**Comment by oltolm** [comment]
This is still broken for me.

```
Version: 1.77.1 (user setup)
Commit: b7886d7461186a5eac768481578c1d7ca80e2d21
Date: 2023-04-04T23:21:11.906Z
Electron: 19.1.11
Chromium: 102.0.5005.196
Node.js: 16.14.2
V8: 10.2.154.26-electron.0
OS: Windows_NT x64 10.0.19045
Sandboxed: No
```

**Comment by lszomoru** [comment]
@oltolm, could you please try the latest Stable/Insiders release? Thank you!
