### ISSUE TITLE
High CPU usage when doing nothing

### ISSUE THREAD

**Issue by liuqian98** [microsoft/vscode#177422]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 
- OS Version: 
- Copied from About
Version: 1.76.2 (user setup)
Commit: ee2b180d582a7f601fa6ecfdad8d9fd269ab1884
Date: 2023-03-14T17:55:54.936Z
Electron: 19.1.11
Chromium: 102.0.5005.196
Node.js: 16.14.2
V8: 10.2.154.26-electron.0
OS: Windows_NT x64 10.0.19045
Sandboxed: Yes

laptop is Dell Vostro 15 5510. CPU : i7-11370H, RAM : 16G

Steps to Reproduce:

1.  Start Code by "code --disable-extensions"
2.  Only a "hello.c" opened
3.  There are 10 "Code" in Task Manger, one of it uses around 50% CPU. Fan is running fast and noisy.
4.  When click Extensions icon, the process bar under "EXTENSIONS:INSTALLED" run for about 20 seconds to load installed extensions.  
![Screenshot 2023-03-17 105656](https://user-images.githubusercontent.com/39250300/225777910-82620456-2b33-4e2c-844d-e9107f17db8b.png)

**Comment by char990** [comment]
Following up:

Uninstall vscode totally. Uninstall, delete all file in install directory, delete all files in user/aaa/.vscode/

Reinstall Code Version: 1.76.2.

Then install some extensions: Remote-SSH, Remote -SSH: Editing cfg, Remote Explorer, C/C++, C/C++ Themes, GitLens, markdownlint, Markdown All in One, learn-markdown.

Now CPU usage is 2%. All good.

**Comment by liuqian98** [comment]
Following up:

Uninstall vscode totally. Uninstall, delete all file in install directory, delete all files in user/aaa/.vscode/

Reinstall Code Version: 1.76.2.

Then install some extensions: Remote-SSH, Remote -SSH: Editing cfg, Remote Explorer, C/C++, C/C++ Themes, GitLens, markdownlint, Markdown All in One, learn-markdown.

Now CPU usage is 2%. All good.

**Comment by mjbvz** [comment]
Closing as it sounds like the issue has been resolved after after reinstall
