### ISSUE TITLE
JUST STOP MAKING CHANGES

### ISSUE THREAD

**Issue by nileio** [microsoft/vscode#177438]
I am really so sick and tired of every update to VSCode introduces a bug..
CAN WE just request to keep the thing AS IS !! just make the software stable ! 

Tasks suddenly stop working - 
now Debugger is not connecting.
the other day an update also missed up something.

I am just frustrated.. hours get wasted with every update. 
How do I opt out of any updates and keep my older working version of VSCode?

**Comment by ulugbekna** [comment]
We care about stability of VS Code across versions _a lot_. We go to great lengths to guarantee the quality we deliver, it's just making large software with new features that our users want is a non-trivial task. 

You could stick to the version that works well for you - https://code.visualstudio.com/docs/supporting/FAQ#_how-do-i-opt-out-of-vs-code-autoupdates
