### ISSUE TITLE
Save new file without extension fails

### ISSUE THREAD

**Issue by ntravis** [Microsoft/vscode#17744]
- VSCode Version: 1.8.1
- OS Version: Windows 10 Version 1607 OS Build 14393.576) (as up-to-date as is reasonable)

Steps to Reproduce:
1. create a new file
2. go to save dialog
3. change the `Save as type:` to `All Files (*.*)` and ensure that the name has no extension following it
4. click save
Results in "the file name is not valid" error.

Desired behavior is that you will be allowed to save the file without an extension in the first pass instead of rename workaround.
Workaround: However, VSCode does allow you to rename a file to a no-extension name. If you proceed after the above error and name the file Untitled-1.txt or any other extension, you can then use the right-click -> rename dialog to remove the extension and it will behave as otherwise expected. 

What other details can I capture to help with this? I'm not a dev, but work around code and sometimes debug, so I can be given technical instructions 😄 I did not see anything in dev tools that appeared to capture the save file work flow and error state, but that was also my first time looking through there. 

Thanks for the great editor and great community of extension writers!

**Comment by egamma** [comment]
NotePad handles this case by automatically adding a `.txt` suffix.

**Comment by bpasero** [comment]
Please use the "No Extension" option:

![image](https://cloud.githubusercontent.com/assets/900690/21587078/803c548a-d0d8-11e6-80a3-db7f9aac0bc9.png)
