### ISSUE TITLE
Hover feedback on extensions list is off

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#177442]
The extension name becomes non-opaque as I hover over each extension name.

https://user-images.githubusercontent.com/22350/225852058-c13d3c96-6ffd-49d3-ac02-008a227148bd.mov

cc @aeschli @daviddossett

**Comment by daviddossett** [comment]
Seems like we've been playing whack-a-mole with the disabled state styles recently. @sandy081 any idea what's going on here?

**Comment by sandy081** [comment]
It seems we have different ways to set the disabled color. Fixed it to use the defined disabled color that is already being used for description.
