### ISSUE TITLE
Extension pack for Java recommended to a JS project

### ISSUE THREAD

**Issue by ulugbekna** [microsoft/vscode#177488]
Does this issue occur when all extensions are disabled?: Yes/No

# Description 

I keep seeing "Extension pack for Java is recommended for this repository" in JS/TS projects. There must be something wrong. 

(I'm reporting here and not with the extension because of the recent work there was with extension recommendations -- maybe it's an extension issue)

<img width="521" alt="image" src="https://user-images.githubusercontent.com/16353531/225944677-28a622b1-1386-47a3-a54c-5bcce7ce16da.png">

# How to reproduce: 

I cloned https://github.com/microsoft/vscode-json-languageservice, opened it in insiders and got this recommendation. 

To try another project, I cloned the react repo (https://github.com/facebook/react) and opened with insiders, again the same problem. 

# Version info

Version: 1.77.0-insider (Universal)
Commit: c97d5812f10c28efbcdb1fd404bc25afae873312
Date: 2023-03-16T05:22:31.950Z
Electron: 19.1.11
Chromium: 102.0.5005.196
Node.js: 16.14.2
V8: 10.2.154.26-electron.0
OS: Darwin arm64 22.3.0
Sandboxed: Yes

**Comment by melMass** [comment]
This is the case for any projects since the insider from 2 days ago, it recommends both dev container and java for any workspace you open
