### ISSUE TITLE
Self hosted VSCode server no longer available

### ISSUE THREAD

**Issue by SuhasHebbar** [microsoft/vscode#177432]
As per the resolution of https://github.com/microsoft/vscode/issues/135856, self hosted VSCode server for personal use was available via the `code-server` preview.

But as of recently the [documentation](https://code.visualstudio.com/docs/remote/vscode-server) has been updated to refer to the new `code tunnel` that no longer has this capability and [this](https://code.visualstudio.com/blogs/2022/12/07/remote-even-better) blog post  seems to indicate that `code-server` will probably be deprecated.

Is there any Microsoft blessed way to achieve this functionality?

**Comment by connor4312** [comment]
Here: https://github.com/microsoft/vscode/issues/168492
