### ISSUE TITLE
Bad UI

### ISSUE THREAD

**Issue by DmitriyShepelev** [microsoft/vscode#177470]
Type: <b>Bug</b>

1. Open Settings tab.
2. Have lower pane (containing "PROBLEMS", "OUTPUT", "DEBUG CONSOLE", etc.) open.
3. Click on gear icon on bottommost setting.
4. Observe that the dialog box is partially obstructed by said lower pane.

Example:
![image](https://user-images.githubusercontent.com/22891379/225919349-a37f8883-f092-4c05-b0ea-ceec47bc6a3a.png)

VS Code version: Code - Insiders 1.77.0-insider (c97d5812f10c28efbcdb1fd404bc25afae873312, 2023-03-16T05:21:54.024Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i9-11950H @ 2.60GHz (16 x 2611)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|63.73GB (48.53GB free)|
|Process Argv|--crash-reporter-id 7796017b-12c7-45ce-8ccd-b6003e23b8e1|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
dscript|Bui|0.1.159125
EditorConfig|Edi|0.16.4
azure-pipelines|ms-|1.208.0
vscode-docker|ms-|1.24.0
csharp|ms-|1.25.4
remote-containers|ms-|0.284.0
azure-account|ms-|0.11.3
cpptools|ms-|1.15.0
powershell|ms-|2023.3.1
msbuild-project-tools|tin|0.4.9
vscode-proto3|zxh|0.5.5

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30422396
pythontb:30258533
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscod805:30301674
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30404738
cppdebug:30492333
vsclangdf:30492506
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30618038
pylantcb52:30590116
pyindex848:30611229
nodejswelcome1:30587009
pyind779:30611226
pythonsymbol12:30651887
a9j8j154:30646983
showlangstatbar:30659908
pythonb192cf:30661257
defaultazurewalk:30687958
pythonms35:30671666
j16hj152:30680472
57b77579:30687741
pythonclientmv:30689206

```

</details>

**Comment by tisilent** [comment]
I want to try
