### ISSUE TITLE
VS code becomes very slow and memory eater

### ISSUE THREAD

**Issue by samiulalimsaad** [microsoft/vscode#177477]
Type: <b>Bug</b>

I can't do my job while I open the vs code it always hangs my pc 

VS Code version: Code 1.76.2 (ee2b180d582a7f601fa6ecfdad8d9fd269ab1884, 2023-03-14T17:57:21.103Z)
OS version: Linux x64 5.15.0-67-generic
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-10400 CPU @ 2.90GHz (12 x 2900)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|7, 12, 12|
|Memory (System)|15.46GB (10.89GB free)|
|Process Argv|--unity-launch --crash-reporter-id 549508c5-562b-49c6-9158-a0e4222f7444|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|cinnamon|
|XDG_CURRENT_DESKTOP|X-Cinnamon|
|XDG_SESSION_DESKTOP|cinnamon|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (31)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|3.0.2
vscode-tailwindcss|bra|0.9.8
npm-intellisense|chr|1.4.4
path-intellisense|chr|2.8.4
postcss|css|1.0.9
vscode-markdownlint|Dav|0.49.0
vscode-eslint|dba|2.4.0
es7-react-js-snippets|dsz|4.4.3
gitlens|eam|13.4.0
vscode-html-css|ecm|1.13.1
prettier-vscode|esb|9.10.4
auto-close-tag|for|0.5.14
auto-complete-tag|for|0.1.0
auto-rename-tag|for|0.1.10
netbeans-keybindings|gro|0.0.7
headwind|hey|1.7.0
svg|joc|1.5.1
vscode-gutter-preview|kis|0.30.0
fluent-icons|mig|0.0.18
dotenv|mik|1.0.1
color-highlight|nau|2.5.0
material-icon-theme|PKi|4.25.0
svg-preview|Sim|2.8.3
autoimport|ste|1.5.4
code-spell-checker|str|2.20.1
intellicode-api-usage-examples|Vis|0.2.7
vscodeintellicode|Vis|1.2.30
vscode-icons|vsc|12.2.0
vscode-import-cost|wix|3.3.0
JavaScriptSnippets|xab|1.8.0
ReactSnippets|xab|2.4.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
pynewext54:30681850
azure-dev_surveyone:30548225
vsccc:30610678
pyindex848:30662994
nodejswelcome1:30587005
282f8724:30602487
pyind779:30671433
f6dab269:30613381
pythonsymbol12:30671437
a9j8j154:30646983
vsccsb:30677849
vscodeenable:30660116
defaultazurewalk:30687958
pythonms35:30686772

```

</details>

**Comment by meganrogge** [comment]
Please see https://github.com/Microsoft/vscode/wiki/Performance-Issues for creating actionable performance problem issues.
/label info-needed

**Comment by samiulalimsaad** [comment]
I think one or many Extension causes hang but I can't get the Extension. if I face a hanging issue again then I will share a screenshot
I think one or many Extension causes hang but I can't get the Extension. if I face a hanging issue again then I will share a screenshot

**Comment by meganrogge** [comment]
`Help: start extension bisect` can help to pinpoint a problematic extension. You can do that via the command palette via `ctrl/cmd+shift+p`

**Comment by samiulalimsaad** [comment]
Thank you very much. by the bisect process I found the culprit. 

The [auto-import](https://marketplace.visualstudio.com/items?itemName=steoates.autoimport) extension was causing a slowdown and memory eater.

Again Thank you so much.
