### ISSUE TITLE
Save Dialogues Show Up Before Editor Switch

### ISSUE THREAD

**Issue by Jonatino** [Microsoft/vscode#17749]
- VSCode Version: 1.9.0-insiders
- OS Version: Windows 10 Pro x64

Steps to Reproduce:

1.  Replace your doHandleDirty function inside of editorPart.ts with the following

```nodejs
	private doHandleDirty(identifier: EditorIdentifier, ignoreIfOpenedInOtherGroup?: boolean): TPromise<boolean /* veto */> {
		if (!identifier || !identifier.editor || !identifier.editor.isDirty() || (ignoreIfOpenedInOtherGroup && this.countEditors(identifier.editor) > 1 /* allow to close a dirty editor if it is opened in another group */)) {
			return TPromise.as(false); // no veto
		}

		const {editor} = identifier;

		return this.openEditor(editor, null, false).then(result => {
			const res = editor.confirmSave();
			switch (res) {
				case ConfirmResult.SAVE:
					return editor.save().then(ok => !ok);

				case ConfirmResult.DONT_SAVE:
					return editor.revert().then(ok => !ok);

				case ConfirmResult.CANCEL:
					return TPromise.as(true); // veto
			}
		});
	}
```
2. Build code and get unsaved change prompt
3. You will notice the save changes prompt is opened before it switches editors

Gif of issue: https://dl.dropboxusercontent.com/u/91292881/ShareX/2016/12/2016-12-22_17-20-14.gif

**Comment by bpasero** [comment]
I think opening a dialog is really stopping "the world" inside the renderer so you would need a timeout or so to make it work. I noticed this before.

Closing as this is not actually an issue in the product currently.
