### ISSUE TITLE
Get current profile name for custom extensions

### ISSUE THREAD

**Issue by tech-meppem** [microsoft/vscode#177463]
When making custom extensions, we should be able to get the profile name that is currently in use in the window, as well as other details about it, such as the id.

It would help for managing external storage and interactions when making custom extensions, as you could do things differently based on profile.

As for the reason specific why I want that:
We have a custom extension I make for the office. It's an internal and really specific one for our company's office setup, so it's not public.
But it interacts with vscode via the command line.

But now, we need to pass in the `--profile "Profile Name"` argument to the cli, for better usability. However, I cannot find any way to get which profile is currently being used in the window the commands are being run in.
The only use case I can find of any sort of way of getting the profile name is that there is an undocumented variable called `profileName`, use in the window.title `${profileName}`, however, I do not know how to resolve this for use internally in the extension.

Also, as a second thing, it would be useful if we could specify something like `--profile "*"` to specific activating on all profiles, but that's not necessary.

**Comment by JamyDev** [comment]
@isidorn We're running into a similar issue at Uber. This seems like a relatively simple fix/feature, would it be able to get some api or template string that we can use outside the title bar for the profile name?

**Comment by isidorn** [comment]
I think this request makes sense. However we are very careful when introducing new API, and the API currently has no concept of Profiles. 
Thus we will keep this issue open to hear more requests from extension author and then potentially add it in the future.

**Comment by JamyDev** [comment]
I think we'd be okay with just a proposed API at this point in time

**Comment by tech-meppem** [comment]
It's not like the whole API needs a concept of profiles.
Just something like `window.getCurrentProfile()` that would return information about the profile for the current vscode window, like it's unique id & display name.
That way things can be stored / applied differently per-profile, but nothing about the API is fundamentally changed.

For example, maybe an extension connects to an external DB / API, and you want it to do different things based on the selected profile?
Or like my use case where I want to interact with the vscode cli, but cannot because it requires the profile name to do anything.

**Comment by dailyboo** [comment]
You can refer to the practice of this plug-in https://marketplace.visualstudio.com/items?itemName=robole.profile-status

https://github.com/robole/vscode-profile-status

**Comment by dailyboo** [comment]
You can refer to the practice of this plug-in
https://github.com/robole/vscode-profile-status

**Comment by sandy081** [comment]
/duplicate

https://github.com/Microsoft/vscode/issues/211890
