### ISSUE TITLE
Diff editor "revert selected lines"

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#17750]
There's probably already a feature request for this but I can't find it.

I want to be able to select a change in the diff editor and revert it, same as how I can stage it. In SourceTree this is called "discard selected lines" although "revert" seems better, unless it's "discard selected changes".

I'm working on a PR for this.

**Comment by aspirisen** [comment]
I think it is connected with [this feature request](https://github.com/Microsoft/vscode/issues/17655)
