### ISSUE TITLE
Expose API to listen to performed commands 

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#1775]
Similar to [`atom.commands.onWillDispatch` and `atom.commands.onDidDispatch`](https://atom.io/docs/api/v1.3.2/CommandRegistry). This would be useful for extensions wanting to perform some action before or after a command is performed.

Being able to determine the source of the event would be useful in such an API (mouse vs keyboard vs command palette).

**Comment by jrieken** [comment]
duplicate of #1431
