### ISSUE TITLE
Bug Report – Issue with Go-to-Definition and Back feature causing incorrect cursor positioning

### ISSUE THREAD

**Issue by coolbit-in** [microsoft/vscode#177598]
Type: <b>Bug</b>

Description:
After using the Go-to-Definition and Back feature in VS Code, the cursor positioning for j, k, and arrow keys (with vim plugin) is inaccurate and sometimes jumps to the beginning of the file. This bug occurs after a certain amount of usage and it is unclear whether it is a problem with the vim plugin or VS Code itself. I have tried installing an older version of the vim plugin, but the issue persists.

Steps to reproduce:
1. Open a file in VS Code with vim plugin installed
2. Use the Go-to-Definition and Back feature multiple times 
3. Use j, k, or arrow keys to move the cursor and observe the positioning

Expected result:
The cursor moves according to the intended commands without jumping to the beginning of the file.

Actual result:
The cursor jumps to the beginning of the file or has incorrect positioning.

Workaround:
Currently, restarting VS Code resolves the issue temporarily.

VS Code version: Code 1.76.2 (Universal) (ee2b180d582a7f601fa6ecfdad8d9fd269ab1884, 2023-03-14T17:54:09.061Z)
OS version: Darwin x64 20.6.0
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4258U CPU @ 2.40GHz (4 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|4, 4, 4|
|Memory (System)|8.00GB (0.13GB free)|
|Process Argv|--crash-reporter-id 5066f93d-78bc-4ec9-ab1e-d7dcbb27893c|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (19)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-database|baj|2.2.3
gitlens|eam|13.4.0
copilot|Git|1.78.9758
copilot-labs|Git|0.12.791
go|gol|0.38.0
gop|gop|0.7.8
vscode-power-mode|hoo|3.0.2
vscode-language-pack-zh-hans|MS-|1.76.2023030809
remote-containers|ms-|0.282.0
remote-ssh|ms-|0.98.0
remote-ssh-edit|ms-|0.84.0
remote-wsl|ms-|0.76.1
vscode-remote-extensionpack|ms-|0.24.0
cpptools|ms-|1.14.4
sqltools|mtx|0.27.1
sqltools-driver-mysql|mtx|0.5.1
platformio-ide|pla|3.1.1
vim|vsc|1.24.3
markdown-all-in-one|yzh|3.5.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30681850
azure-dev_surveyonecf:30548226
pyindex848:30662994
nodejswelcome1cf:30587006
282f8724:30602487
pyind779:30671433
f6dab269:30613381
pythonsymbol12:30671437
a9j8j154:30646983
pythonb192:30669360
azdwalk:30687957
pythonms35cf:30686773

```

</details>

**Comment by jrieken** [comment]
@coolbit-in Please check that this isn't an issue with the vim-extension. So, please try built-in navigation commands and if those work please file an issue against vim

**Comment by coolbit-in** [comment]
Thank you. I have tried many ways to avoid this problem, but in the end, I
had to stop using the system's 'go to definition' and 'back' and instead
use(or remap) the vim-extension's 'gd' and 'ctrl+o' for navigation. It
seems to be working fine now, and it appears to be an issue of the
vim-extension.

Johannes Rieken ***@***.***> 于2023年3月20日周一 15:50写道：
