### ISSUE TITLE
Intra-document links in extension Readme are broken.

### ISSUE THREAD

**Issue by vadimcn** [Microsoft/vscode#17754]
- VSCode Version: 1.8.1
- OS Version: OSX

Steps to Reproduce:
1. Find an extension that uses intra-document links in its Readme (e.g. 'vscode-lldb').
2. Click on one such link.

Instead of taking you to the link destination, VSCode displays HTML source of "webview.html".

-----

Related: https://github.com/Microsoft/vscode-vsce/issues/118

**Comment by joaomoreno** [comment]
Duplicate of Microsoft/vscode-vsce#118

**Comment by vadimcn** [comment]
Wait, this one is about VSCode itself, not the website.

**Comment by joaomoreno** [comment]
It's the same underlying issue.
