### ISSUE TITLE
Test: `editor/lineNumber/context` API proposal

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode#177521]
Refs: https://github.com/microsoft/vscode/issues/175945

- [x] anyOS @ulugbekna
- [x] anyOS @karthiknadig 

Complexity: 3

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23177521%0A%0A&assignees=joyceerhl)

---

Background:
This milestone we've added an API proposal for a context menu anchored to the editor line number/gutter area. The initial motivation is to allow extension-contributed sharing links in this menu, but this also satisfies a longstanding feature request for a context menu in the gutter.

Testing:
Please create an extension which contributes a command to the `editor/lineNumber/context` menu and verify the usability of this context menu for extension-contributed commands. Today we expose the target line number in an argument passed to the extension command, as well as in a context key `editorLineNumber` which can be referenced in the contribution's when clause.

**Comment by karthiknadig** [comment]
Good work!!!
