### ISSUE TITLE
Error Squiggles not working

### ISSUE THREAD

**Issue by vivekreddysripathi** [microsoft/vscode#177501]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 
- OS Version: 

Steps to Reproduce:

1.  Just writing random things in editor. It doesn't show any errors.  
<img width="470" alt="Screenshot 2023-03-17 at 12 50 03 PM" src="https://user-images.githubusercontent.com/98629420/225980833-a048a960-2453-4760-9988-56c92bde1dae.png">

2.  All this while error squiggles is still enabled. I have tried disabling and then enabling, uninstalling extensions and reinstalling. Nothing worked.
<img width="703" alt="Screenshot 2023-03-17 at 12 51 20 PM" src="https://user-images.githubusercontent.com/98629420/225981330-47cf6b22-3100-4ab4-aeb5-2bbfbb1e682a.png">

**Comment by alexdima** [comment]
@vivekreddysripathi To get squiggles for java programs, you need to install an extension that provides Java validation. Have you already done so?

**Comment by vivekreddysripathi** [comment]
I don't remember installing any extension separately.  I just downloaded coding pack for java in  vscode website and installed it. All was good for more than a year and all of a sudden it stopped a week ago.

**Comment by alexdima** [comment]
Do errors appear in the Problems panel? (`View > Problems`)

**Comment by vivekreddysripathi** [comment]
No, they are not. I can see them only when I try to run them.
<img width="815" alt="Screenshot 2023-03-23 at 9 45 46 PM" src="https://user-images.githubusercontent.com/98629420/227411311-256e2fdb-83a7-4c4c-97e0-929128fb2a33.png">
<img width="416" alt="Screenshot 2023-03-23 at 9 46 02 PM" src="https://user-images.githubusercontent.com/98629420/227411314-9d93a4b6-9640-4859-8c66-1e831c6b70c8.png">

**Comment by vivekreddysripathi** [comment]
No error aren't appearing. They show up in terminal only when I try to run it
<img width="416" alt="Screenshot 2023-03-23 at 9 46 02 PM" src="https://user-images.githubusercontent.com/98629420/227411629-5996966e-8031-4d40-b7b9-7b855156251a.png">
<img width="560" alt="Screenshot 2023-03-23 at 9 47 49 PM" src="https://user-images.githubusercontent.com/98629420/227411631-63499146-af80-4d11-b8f3-1d44a11abc13.png">

**Comment by vivekreddysripathi** [comment]
Hello? Can I get a reply?
