### ISSUE TITLE
grayscale intellisense codicons in jupyter notebooks

### ISSUE THREAD

**Issue by mich2k** [microsoft/vscode#177503]
Does this issue occur when all extensions are disabled?: Yes (also tried with vscode & insiders fresh install)

- VS Code Version: 1.76.2
- OS Version:  WIN11 22621.1413

Steps to Reproduce:

1. Use both (as of today) latest version of vscode or vscode insiders
2. Check into a dev container (in this example is a nvidia one)
3. Wait for intellisense suggestions showing up

Similiar to #107276 or #107264 , same behaviour but regarding containers

![image](https://user-images.githubusercontent.com/13397578/225981190-6e46577f-a8ac-44c8-b3d9-dd39191c9dea.png)

**Comment by jrieken** [comment]
@mich2k Does this still reproduce for you? We did have an issue here in the past but that should be fixed and I am not seeing this happening anymore

**Comment by mich2k** [comment]
![immagine](https://github.com/microsoft/vscode/assets/13397578/7f438ea9-9448-42fe-8c9f-c6664ddd6b15)
really still happening today, shall I move this to vscode-jupyter?

**Comment by mich2k** [comment]
Since my comment got marked as spam and doesn't seem to be a solution for this I'll just close this as not planned (but existent)

**Comment by mich2k** [comment]
![immagine](https://github.com/microsoft/vscode/assets/13397578/ca4f7a32-6376-46de-9663-d9f967132d2e)
fresh empty installation of code-insiders
