### ISSUE TITLE
Add language identifier `clojure` to https://code.visualstudio.com/docs/languages/identifiers

### ISSUE THREAD

**Issue by PEZ** [microsoft/vscode#177574]
`clojure` is not recognized as a known language identifier here: https://code.visualstudio.com/docs/languages/identifiers

That wouldn't be so bad if it wasn't that it seems to have implications for defining VIM keybindings which should only be active in Clojure files. This doesn't work:

```json
    {
      "before": ["x"],
      "commands”: [
        {
          "command": "paredit.deleteForward"
        }
      ],
      "when": "editorLangId == clojure",
    }
```

**Comment by gjsjohnmurray** [comment]
Have you already installed an extension that contributes that language?

**Comment by PEZ** [comment]
Yes, I'm a maintainer of Calva, which contributes it. Regular keybindings can use the language id for when clauses.

**Comment by gjsjohnmurray** [comment]
I don't understand your original message. The page you linked to already includes `clojure` in its table.

**Comment by PEZ** [comment]
Oh, yes it is. We were two here that missed it. I'm sorry. Will ask the VIM extension folks instead.

**Comment by usernamehw** [comment]
Maybe it's just invalid json (closing quote on "command")?

**Comment by PEZ** [comment]
I think that's just an artifact of it being pasted in slack without code fences. I had to change all quotes when pasting here and must have missed that one.

**Comment by PEZ** [comment]
I think it is as simple as that `when` contexts are not available for VIM keymappings (plus me reading that list very sloppily).
