### ISSUE TITLE
Debug Console Search

### ISSUE THREAD

**Issue by ehabelnahas** [microsoft/vscode#177579]
In debug console, sometimes i need to find some word between the long debug rows.
When searching for the word, it clears (filters) the debug text and only shows the line contains the word. But most of the time i need to read the next or previous lines of that word which can't be achieved using filter, and will back again to find it manually scrolling the large number of rows.

I suggest to make the filter just highlight the rows containing the search word, and may be go to the first result keeping the other rows visible (not filtered).

**Comment by roblourens** [comment]
https://github.com/microsoft/vscode/issues/4338
