### ISSUE TITLE
lines like " float depth = -0.00fg1f;" are not generating obvious syntax errors

### ISSUE THREAD

**Issue by Guedez** [Microsoft/vscode#17756]
- VSCode Version: Code 1.8.1 (ee428b0eead68bf0fb99ab5fdc4439be227b6281, 2016-12-19T14:41:20.664Z)
- OS Version: Linux x64 4.8.10-040810-generic
- Extensions:

|Extension|Author|Version|
|---|---|---|
|unity-tools|Tobiah|0.1.9|
|unity-debug|Unity|1.1.0|
|unity-snippets|YclepticStudios|0.1.2|
|vscode-astyle|chiehyu|0.4.0|
|cs-syntax-visualizer|itn3000|0.0.2|
|csharpextensions|jchannon|1.1.0|
|docomment|k--kato|0.0.9|
|csharp|ms-vscode|1.6.1|
|omnisharp|ms-vscode|0.3.3|
|vscode-format|ryannaddy|0.0.6|

---

Steps to Reproduce:

1. write: "float depth = -0.00fg1f;"
2. no errors are generated, where it should complain about the "fg" inside the number

**Comment by egamma** [comment]
@Guedez what is the language are you using when writing the snippet `float depth = -0.00fg1f;`

**Comment by egamma** [comment]
@Guedez any update?

**Comment by egamma** [comment]
Moving to omnisharp-vscode for further investigation.

**Comment by egamma** [comment]
This issue was moved to OmniSharp/omnisharp-vscode#1094
