### ISSUE TITLE
Java extension pack being suggested when opening a Python Flask app with nodeJS front end  

### ISSUE THREAD

**Issue by luabud** [microsoft/vscode#177527]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.77.0-insider
- OS Version: Windows 11

Steps to Reproduce:

1. Open a clean VS Code 
2. Install the Python extension
3. Clone and open this repo: https://github.com/luabud/thecatsaidno
4. See the extension pack for Java being suggested 

Not sure why Java is being suggested for this repo? Couldn't see anything Java related there

**Comment by luabud** [comment]
It's also being suggested when I open this folder for the first time in VS Code: https://github.com/luabud/pycascades2023-msft/tree/main/titanic

**Comment by gjsjohnmurray** [comment]
And for me when I open my local copy of the microsoft/vscode repo itself.

**Comment by 343max** [comment]
It's suggested on most projects I open. When I pick "Don't show again" that only seems to apply for the same workspace. Pretty annoying.
