### ISSUE TITLE
Ranges where `additionalTextEdits` are applied are not appropriate when characters are typed

### ISSUE THREAD

**Issue by tamuratak** [microsoft/vscode#177591]
Does this issue occur when all extensions are disabled?: Yes

Version: 1.77.0-insider (Universal)
Commit: 2a6bd78f745d3e6330c8ff7db5282dc582e117fd
Date: 2023-03-17T21:00:47.582Z
Electron: 19.1.11
Chromium: 102.0.5005.196
Node.js: 16.14.2
V8: 10.2.154.26-electron.0
OS: Darwin arm64 20.6.0
Sandboxed: Yes 

Steps to Reproduce:

1.  Execute the following extension example: https://github.com/tamuratak/vscode-extension-samples/tree/53ccfff2cb3a0cf8fda62018af47ae0e960839a3/completions-sample

```ts
import * as vscode from 'vscode';

export function activate(context: vscode.ExtensionContext) {

	const provider1 = vscode.languages.registerCompletionItemProvider('plaintext', {

		provideCompletionItems(document: vscode.TextDocument, position: vscode.Position, token: vscode.CancellationToken, context: vscode.CompletionContext) {
			const item01 = new vscode.CompletionItem('aaa');
			item01.additionalTextEdits = [vscode.TextEdit.insert(position.translate(0, 10), 'aaa')];
			return [
				item01
			];
		}
	});

	context.subscriptions.push(provider1);
}
```
3. Open a text file
4. Type `Ctrl-space` and select a completion item
5. Type `Ctrl-space`, type `aa`, and select a completion item
6. The results are different

https://user-images.githubusercontent.com/10665499/226150839-269a34aa-5b02-4af1-b5ab-3a358078bef7.mov

**Comment by jrieken** [comment]
This is specific to additional edits that are after and on the same line as the suggestion. The newly typed characters (type after return the list of item and before selecting one) aren't taken into account
