### ISSUE TITLE
File Explorer Icon missing

### ISSUE THREAD

**Issue by cchow33** [microsoft/vscode#177516]
[](url)
My file explorer icon has completed disappeared from the Activity bar. How do I restore it?
![Explorer icon](https://user-images.githubusercontent.com/109078860/226014696-7061e716-244b-478a-9f48-f5ad1c98acf3.png)

Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 
- OS Version: 

Steps to Reproduce:

1. 
2.

**Comment by cchow33** [comment]
File explorer icon missing

**Comment by ArturoDent** [comment]
Try `View: Reset View Locations`

**Comment by absane** [comment]
Just curious how this happened since it happened to me 4 days ago and drove me crazy. Was an update pushed to VSCode or maybe another extension that caused it? Odd. `View: Reset View Locations` fixed it for me.
