### ISSUE TITLE
cannot find command workbench.action.tasks.runTask/taskName

### ISSUE THREAD

**Issue by wikinee** [Microsoft/vscode#17757]
- VSCode Version:
    1.8
- OS Version:
    Ubuntu 16.04 LTS

Steps to Reproduce:

I check https://github.com/Microsoft/vscode/issues/981 from @danielschmitz says:
    { "key": "ctrl+shift+alt+o",          "command": "workbench.action.tasks.runTask/taskName" }
but not worked

**Comment by dbaeumer** [comment]
This is not implemented yet and requires: https://github.com/Microsoft/vscode/pull/10676.
