### ISSUE TITLE
search highlight in notebook persists

### ISSUE THREAD

**Issue by andreamah** [microsoft/vscode#177536]
1. enable `search.experimental.notebookSearch`
2. Search something that appears in an open notebook
3. Search something else 
4. Notice that both results are still highlighted

**Comment by andreamah** [comment]
The approach was not quite correct, will revert the PR

**Comment by andreamah** [comment]
Hmm, it seems fixed to me. Are you on the very latest of insiders?

**Comment by sandy081** [comment]
Yeah I do

**Comment by andreamah** [comment]
Could you share the notebook and the search queries that you used?

**Comment by sandy081** [comment]
Here are steps:

- Open VS Code sources
- Search for `milestone:` - gives github-issues notebooks as results.
- Open the first result which is `api.github-issues` for me. See that `milestone:` is selected
- Now change the search term to `March 2023` and search
🐛 In the opened notebook both terms are highlighted.

**Comment by andreamah** [comment]
Ah I see, you were talking about the white "current result" highlight. I originally created this issue with the orange highlight in mind (the one that all matches get), but I can probably fix the current result highlight as part of this issue too.
