### ISSUE TITLE
Cursor

### ISSUE THREAD

**Issue by Eleke79** [microsoft/vscode#177608]
[Type:](![vlc_cursor_issue001](https://user-images.githubusercontent.com/70367324/226185443-e5231d5a-a864-4540-8a16-834b192fa9a0.png)) <b>Performance Issue</b>

Everytime the cursor takes thick shape and it becomes impossible to type or to code. 

file:///home/elbrus/Pictures/vlc_cursor_issue001.png

VS Code version: Code 1.76.2 (ee2b180d582a7f601fa6ecfdad8d9fd269ab1884, 2023-03-14T17:57:21.103Z)
OS version: Linux x64 5.15.0-56-generic
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Pentium(R) CPU B970 @ 2.30GHz (2 x 2294)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: disabled_off<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|2, 2, 2|
|Memory (System)|3.73GB (1.28GB free)|
|Process Argv|--unity-launch --crash-reporter-id d1b12c0e-dce9-43ac-854d-d5563503e4a9|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|cinnamon|
|XDG_CURRENT_DESKTOP|X-Cinnamon|
|XDG_SESSION_DESKTOP|cinnamon|
|XDG_SESSION_TYPE|x11|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    1	   157	 13854	code main
    0	    42	 13859	   zygote
   10	   115	 13895	     gpu-process
    0	    42	 13860	   zygote
    0	     8	 13862	     zygote
    3	    84	 15156	       issue-reporter
    0	    57	 13911	   utility-network-service
    2	   229	 13921	   window (chatgpt_bot.py - Telegram_Bot - Visual Studio Code)
    0	   138	 13954	   shared-process
    0	    73	 13984	     ptyHost
    0	     4	 14998	       /usr/bin/bash --init-file /usr/share/code/resources/app/out/vs/workbench/contrib/terminal/browser/media/shellIntegration-bash.sh
    0	    69	 14175	     fileWatcher
    0	     0	 15175	     /bin/sh -c /usr/bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0	     0	 15176	       /usr/bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0	   206	 14173	   utility-process
    0	   195	 14236	     electron-nodejs (/usr/share/code/code --ms-enable-electron-run-as-node /home/elbrus/.vscode/extensions/ms-python.vscode-pylance-2023.3.20/dist/server.bundle.js --cancellationReceive=file:192548160752a77ee8a17fac23cd695cec9225fb9f --node-ipc --clientProcessId=14173)
    0	    61	 15052	     electron-nodejs (/usr/share/code/code --ms-enable-electron-run-as-node /home/elbrus/.vscode/extensions/ms-azuretools.vscode-docker-1.24.0/dist/dockerfile-language-server-nodejs/lib/server.js --node-ipc --node-ipc --clientProcessId=14173)
    0	    61	 15053	     electron-nodejs (/usr/share/code/code --ms-enable-electron-run-as-node /home/elbrus/.vscode/extensions/ms-azuretools.vscode-docker-1.24.0/dist/compose-language-service/lib/server.js --node-ipc --node-ipc --clientProcessId=14173)
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (chatgpt_bot.py - Telegram_Bot - Visual Studio Code)
|    Folder (Telegram_Bot): 0 files
|      File types:
|      Conf files:;
```

</details>
<details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
copilot|Git|1.78.9758
vscode-docker|ms-|1.24.0
python|ms-|2023.4.1
vscode-pylance|ms-|2023.3.20
jupyter|ms-|2023.2.1200692131
jupyter-keymap|ms-|1.1.0
jupyter-renderers|ms-|1.0.15
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-slideshow|ms-|0.1.5
cpptools|ms-|1.14.4
vim|vsc|1.25.2

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30681850
azure-dev_surveyonecf:30548226
vscccc:30610679
pyindex848:30662994
nodejswelcome1cf:30587006
3biah626:30602489
pyind779:30671433
89544117:30613380
pythonsymbol12:30671437
2i9eh265:30646982
6233i204:30672705
vsccsb:30677849
vscodedisable:30660115
pythonb192cf:30669361
azdwalk:30687957
pythonms35cf:30686773

```

</details>

**Comment by gjsjohnmurray** [comment]
Please copy/paste your screenshot into a response at the GitHub website (not as an attachment to an email response), or use the toolbar on the response editor there to add it.

**Comment by IllusionMH** [comment]
Is it the case with Vim extension? Do you see this behavior if you disable it?

**Comment by alexdima** [comment]
It sounds like you have installed the vim extension and you perhaps don't want to use the vim input mode. Please disable or uninstall the vim extension.
