### ISSUE TITLE
Test file content based recommendations

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#177675]
Refs: https://github.com/microsoft/vscode/issues/176768

- [x] win @Tyriar 
- [x] mac @DonJayamanne
- [x] linux @connor4312 

Complexity: 4

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23177675%0A%0A&assignees=sandy081)

---

**Note:** Use fresh user data dir and extensions dir - Start from CLI using args `--user-data-dir` and `--extensions-dir`.

### File based recommendations

Test following recommendations when a file is opened. Make sure following recommendations are shown only when the recommended extension is not installed.

- Docker extension is recommended for `Dockerfile`
- Java extension pack is recommended for `sample.java` file

### File content based recommendations

Test following recommendation is shown based on the content of the file
 - Start with fresh user data dir or fresh profile
 - Install Python extension and Uninstall Jupyter Extension because it is included in Python extension.
 - Open a python file with following contents
```py
print("HI")
#%%
print("cell")
#%%
print("something else")
```
- Make sure Jupyter extension is recommended.
- Make sure Jupyter extension is not recommended when
  - Python extension is not installed or
  - Python file does not contain text `#%%`
  - Jypyter extension is already installed

### Workspace config based recommendations

Test following recommendations when a folder is opened

- Open a folder that has `.devcontainer/devcontainer.json` file
  - Make sure workspace recommendation prompt is shown and the workspace recommendations has `ms-vscode-remote.remote-containers` extension
- Open a repo from GitHub (make sure it does not has the file in the repo - `.vscode/extensions.json`.
  - Open recommendations in the extensions viewlet and make sure `GitHub.vscode-pull-request-github` and `eamodio.gitlens` extensions are recommended in the view.

**Comment by alexr00** [comment]
I'm blocked on testing "File content based recommendations" on https://github.com/microsoft/vscode/issues/177781.

**Comment by sandy081** [comment]
@alexr00 Thanks for filing the bug, if you use fresh user data directory or a different profile and install python extension before opening the python file, you can verify file content based recommendations.

**Comment by DonJayamanne** [comment]
Tested, works well except with remote repos
