### ISSUE TITLE
Hover for method signatures too aggressive

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#17765]
1. debugViews.ts: 316, start typing the following line

 ```javascript	
this.toDispose.push(this.debugService.getViewModel
```

Notice how the hover help appears for push and never goes away. I understand that I am still in the arguments of the push method but for me as a user this is very irritiating - especially since I know how to use the push method of an array.
Not sure how to best improve this - but I would be happy if I could at least disable this hover help which never helps me but alwasy gets in my way.
We could maybe hide it when intelli-sense appears - since that is a clear signal that the user is being focussed on something else atm.

![screen shot 2016-12-23 at 10 44 18](https://cloud.githubusercontent.com/assets/1926584/21451165/2df78844-c8fd-11e6-9a52-555f46301ab1.png)

**Comment by joaomoreno** [comment]
This is a TypeScript issue, file it there. We don't understand the syntax but just ask the language service whether there should be parameter hints at each position.

**Comment by isidorn** [comment]
Filed https://github.com/Microsoft/TypeScript/issues/13268
