### ISSUE TITLE
PHP 7.X.X SUPPORT

### ISSUE THREAD

**Issue by JDPT93** [Microsoft/vscode#17762]

**Comment by egamma** [comment]
@JDPT93 thanks for the feature requests pls follow our [issue reporting guide lines](https://github.com/Microsoft/vscode/wiki/Submitting-Bugs-and-Suggestions#writing-great-issues-and-suggestions) and report one feature request per issue.

>Drag & Drop Text

Duplicates #1046

**Comment by JDPT93** [comment]
PHP7.X.X Support? @egamma

**Comment by egamma** [comment]
@JDPT93 

>PHP7.X.X Support?

Can you elaborate what you mean by support? VS Code supports linting with PHP7, this has been discussed in  #15447. There are several extension that provide additional PHP support and you should try one of them https://marketplace.visualstudio.com/search?term=php&target=VSCode&sortBy=Relevance.

**Comment by mousetraps** [comment]
Closing as we haven't received a more detailed response that would help us take action on the issue, but will be happen to re-open if you could provide any more info.
