### ISSUE TITLE
Editor scrolls to the top of the page when switching files

### ISSUE THREAD

**Issue by robbertstevens** [Microsoft/vscode#17766]
- VSCode Version: 1.8.1
- OS Version: Windows 10

Steps to Reproduce:

1. Open editor
2. Open multiple files
3. Scroll down
4. Switch file
5. Switch back to first file

**Comment by egamma** [comment]
@robbertstevens I cannot reproduce this issue given the above steps, , see the animated gif below, can you please add an animated gif that illustrates the problem.

![scroll](https://cloud.githubusercontent.com/assets/172399/21458479/f8360372-c936-11e6-9fb5-f4ddcf169dc6.gif)

**Comment by egamma** [comment]
@robbertstevens can you pls provide more information for how to reproduce this issue?

**Comment by robbertstevens** [comment]
@egamma I think it's an error in the ftp-simple addon. Because when I use two local files I don't have this issue. I think this one can be closed.

BTW. how to make an animated gif like that?

**Comment by egamma** [comment]
Closing this issue as suggested.

@robbertstevens I'm using LICEcap on both Windows and OS X.
