### ISSUE TITLE
Debug command with runtimeVersion not waiting for terminal load 

### ISSUE THREAD

**Issue by LeoLfL** [microsoft/vscode#177685]
- VS Code Version: 1.76.2 (latest)
- OS Version: MAC OS 13.2.1 (Ventura)

### Steps to Reproduce:

1. add vscode launch command 
```
{
      "type": "node",
      "request": "launch",
      "name": "Test",
      "runtimeVersion": "18",
      "program": "${workspaceFolder}/node_modules/.bin/jest",
      "console": "integratedTerminal",
    },
```
2. also I use **zsh** with **oh-my-szh** 
3. inside .**zshrc** I autoset node version using nvm preload script 
```
# Auto load .nvmrc file
# place this after nvm initialization!
autoload -U add-zsh-hook
load-nvmrc() {
  local node_version="$(nvm version)"
  local nvmrc_path="$(nvm_find_nvmrc)"

  if [ -n "$nvmrc_path" ]; then
    local nvmrc_node_version=$(nvm version "$(cat "${nvmrc_path}")")

    if [ "$nvmrc_node_version" = "N/A" ]; then
      nvm install
    elif [ "$nvmrc_node_version" != "$node_version" ]; then
      nvm use
    fi
  elif [ "$node_version" != "$(nvm version default)" ]; then
    echo "Reverting to nvm default version"
    nvm use default
  fi
}
add-zsh-hook chpwd load-nvmrc
load-nvmrc 
```

it works fine and each time when I open projects it's auto load node version 

<img width="775" alt="image" src="https://user-images.githubusercontent.com/22210892/226409704-a8dfb072-b938-42f7-b74a-dd965a99fecf.png">

### Error 
but when I run **Test** debug command using **integratedTerminal** it is somehow not waiting until the terminal is loaded. so it mixed the script code with nvm switching info 
<img width="1169" alt="image" src="https://user-images.githubusercontent.com/22210892/226410693-5e8427c5-aef8-4009-a04b-a573ab3f8cec.png">

It just can't start the debugger =(

### How it works 
When I run debug command without   **"console": "integratedTerminal",** then it works. 

Also, it works if I comment preload nvm script  inside **.zshrc** (doesn't looks like a good solution)

Looks like debug command can't wait until zsh finishes hooks and I guess we should somehow fix it

**Comment by Tyriar** [comment]
I also wouldn't expect the echo to cause any problems, my guess is nvm is swallowing some input. Currently for new terminals they are given 1 second to initialize so you could maybe speed up start up to get it to work again? Though my experience with nvm is it's really slow.

I don't think there is anything we can do apart from debug to use some shell integration hooks for when the shell is initialized, that's a bigger feature though and depends https://github.com/microsoft/vscode/issues/145234
