### ISSUE TITLE
WSL extension development host windows keeps crashing

### ISSUE THREAD

**Issue by aseemr** [microsoft/vscode#177684]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.76.2, commit: ee2b180d582a
- OS Version: Windows 11, version 22H2 with remote as WSL2 ubuntu 22.04

Steps to Reproduce:

1. Following the steps here: https://code.visualstudio.com/api/advanced-topics/remote-extensions#debugging-using-wsl with the extension here: https://github.com/FStarLang/fstar-vscode-assistant. I have the git clone of this extension repo in WSL. And I can open the folder in a WSL vscode window.
2. Ctrl+Shift+B (compiling the extension) succeeds in the WSL vscode window.
3. On launch config (pressing the ▷ button), the extension host window opens, it initializes, I also see in the pane below "Activating extensions", but then it exits. No messages are printed on the main window.

Things that I have tried:

1. Making a package for the extension (vsce package) and then installing .vsix file in WSL remote window works.
2. I have tried playing with package.json:extensionKind but doesn't make a difference.
3. I tried extension bisect also. The only extension I have is WSL itself, so it didn't help either.

Thanks in advance for your help!

**Comment by aseemr** [comment]
An update: In step 3 of "Steps to reproduce", just doing "Run Without Debugging" opens the Extension Development Host window, in which I can use the extension (though no debugging messages).

So the "crash" happens only with "Run and Debug".

**Comment by aseemr** [comment]
The launch.json for the extension looks like this:

```
{
	"version": "0.2.0",
	"configurations": [
		{
			"type": "extensionHost",
			"request": "launch",
			"name": "Launch Client",
			"runtimeExecutable": "${execPath}",
			"args": [
				"--extensionDevelopmentPath=${workspaceRoot}"
			],
			"outFiles": [
				"${workspaceRoot}/client/out/**/*.js"
			],
			"preLaunchTask": {
				"type": "npm",
				"script": "watch"
			}
		},
```

If I remove the "autoAttachChildProcess" property, it works, as in even with "Run and Debug" the extension development host window doesn't crash.

**Comment by connor4312** [comment]
Duplicates https://github.com/microsoft/vscode-js-debug/issues/1503
