### ISSUE TITLE
Test: terminal accessible buffer improvements

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#177674]
Refs #174079, #175765, #177310

- [x] Windows @bhavyaus 
- [x] macOS @DonJayamanne 
- [x] Linux @karthiknadig 

Complexity: 4

Authors: @meganroge, @tyriar

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23177674%0A%0A&assignees=meganrogge,meganroge,tyriar)

---

We've made improvements to the terminal's accessible buffer, which can be accessed via `Terminal:
 Focus Accessible Buffer` or `Shift+Tab` (in screen reader mode) including:
- When `tabFocusMode` is on via `Ctrl+M` 
![Screenshot 2023-03-20 at 8 42 49 AM](https://user-images.githubusercontent.com/29464607/226392372-3abbc0a5-86ff-40f5-b643-fffaca7bd669.png)
the accessible buffer becomes visible when tabbing around the workbench. Pressing `Tab` one more time will focus the terminal.
- The accessible buffer remains focused until `Tab` or `Escape` are pressed within that element
- Content is presented correctly when the scrollback is filled. For example:
   -  run `ls -lR ~`
   - check what your scrollback is set to
   - copy and paste the content of the accessible buffer into an editor
   - confirm that the number of lines and the content are correct
- `workbench.action.terminal.navigateAccessibleBuffer` works as expected when in screen reader mode - note that we want to align the feel of this with the editor's `Go to symbol` functionality - note that sometimes this does not work so well, #177697

**Comment by DonJayamanne** [comment]
> workbench.action.terminal.navigateAccessibleBuffer works as expected when in screen reader mode - note that we want to align the feel of this with the editor's Go to symbol functionality - note that sometimes this does not work so well, https://github.com/microsoft/vscode/issues/177697

What do you mean by `works as expected when in screen reader mode `
I haven't used screen reader mode, hence do not know what the expected behaviour is here
