### ISSUE TITLE
yo-generated extension should not generate package.json with warnings

### ISSUE THREAD

**Issue by ulugbekna** [microsoft/vscode#177665]
Does this issue occur when all extensions are disabled?: Yes/No

Generating a typescript-based extension with `yo code` produces a `package.json` with warnings:

<img width="1010" alt="image" src="https://user-images.githubusercontent.com/16353531/226374791-495f1c3e-e5f4-4378-b950-1b9186a39304.png">

**Comment by aeschli** [comment]
@ulugbekna Are you on the latest version of generator-code (1.7.4)? 

Run `npm update --global generator-code`
