### ISSUE TITLE
Increase javascript files limit

### ISSUE THREAD

**Issue by Codemaverick** [Microsoft/vscode#1776]
I work on a project that at last count uses just a little over 2000 js files - excluding compiled/generated files and third party (vendor) files like jquery, etc.  No matter how I configure jsconfig.json, I always get the too many files error.

```"Sorry, but there are too many JavaScript source files for VS Code. Consider using the exclude-property in jsconfig.json"```. 

I use Brackets on a daily basis for my projects and occasionally Sublime text, and neither of those two choke on the number of files in my project, granted neither implement intellisense. Is there anyway this can be adjusted or the limit increased?

On the off chance I'm just not configuring jsconfig.json correctly, I'm open to suggestions

**Comment by jrieken** [comment]
We will move to project Salsa this month so that this request becomes obsolete

**Comment by ig16022** [comment]
Can we suppress that warning for now?

**Comment by jrieken** [comment]
only at the risk of crashing VS Code...

**Comment by ig16022** [comment]
But with that warning popping up every 10 seconds the IDE is simply unusable. Is there no workaround at the moment, other than telling it to ignore parts of the solution?

**Comment by egamma** [comment]
@ig16022 Your setup will be a great test case for the new Salsa JS infrastructure that will become available as preview early next week. I'll include instructions here once a preview build is available.

**Comment by ig16022** [comment]
I'm looking forward to it.

**Comment by egamma** [comment]
@ig16022 it is now available, please give it a try.

See https://blogs.msdn.microsoft.com/vscode/2016/02/01/introducing-insiders-builds/ for how to get the insider bits

See https://github.com/Microsoft/vscode-docs/blob/vnext/release-notes/latest.md for how to enable Salsa.
