### ISSUE TITLE
Test: Change the provider used for defining the sticky lines in sticky-scroll

### ISSUE THREAD

**Issue by aiday-mar** [microsoft/vscode#177649]
Refs: https://github.com/microsoft/vscode/issues/177338

- [x] anyOS @mjbvz
- [x] anyOS @dbaeumer

Complexity: 2

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23177649%0A%0A&assignees=aiday-mar)

---

It is now possible to configure the provider which defines the lines to sticky. As of now there are three possibilities: the outline model provider, the folding model provider and the indentation model provider. Below you may find the fallbacks for each choice of provider:

outline model provider -> folding model provider -> indentation model provider
folding model provider -> indentation model provider
indentation model provider

To test this works, follow these steps:

1. Enable sticky scroll in the settings. Enable the folding ranges (for visualization purposes). 
2. You may choose the provider by going into the settings and choosing a default provider from `Editor > Sticky Scroll: Default Model`.
3. Choose the outline model provider as the default. Open a file for which there is an outline model (indicated by a non empty outline panel in the explorer). Verify the sticky lines follow closely the outline model. 
4. Choose the outline model provider as the default. Open a file for which there is no outline (indicated by an empty outline panel in the explorer). You may have to disable certain extensions that provider an outline model in VS Code. Verify that the sticky lines follow closely the folding ranges. 
5. Choose the folding model provider or the indentation model provider as the default and open a file with an outline model. Verify that the sticky lines follow closely the folding ranges, not the outline model.

**Comment by mjbvz** [comment]
Works great!
