### ISSUE TITLE
Kotlin error

### ISSUE THREAD

**Issue by RobFosterNYC** [microsoft/vscode#177656]
I am constantly getting this line of code 30 times in the output section of the taskbar.

**The process tried to write to a nonexistent pipe.**

I tried 4 different Kotlin extensions, and its just errors after errors.
I can't find dates of last updates on extensions to make sure if an extension is being currently maintained 
or just sitting there collecting dust with no updates.

**Comment by gjsjohnmurray** [comment]
See below for pointers:

![image](https://user-images.githubusercontent.com/6726799/226335192-ac1ca947-92e0-4441-9777-7be04d466b83.png)

Visiting the repository associated with an extension can give you a sense of how active (or not) it is. That is also usually the right place to report extension-specific issues.

**Comment by DonJayamanne** [comment]
Thanks for digging into this.
Closing this issue as its related to a 3rd party (external) extension
