### ISSUE TITLE
Inline suggestion is read twice by the screen reader

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#177696]
reported by @jooyoungseo

1. trigger an inline suggestion
2. 🐛 it is read twice

**Comment by meganrogge** [comment]
@hediet maybe related to https://github.com/microsoft/vscode/commit/b7df1f86dd8e829bec6bf53f2db10995cb56f8b2?

**Comment by meganrogge** [comment]
@jooyoungseo has reported that this is no longer reproducing. However, there's a long delay between the audio cue and the inline suggestion being read - to the extent that he has turned it off. 

This is because the audio cue takes some time to load. Is there anything we can do about this @hediet ? https://github.com/microsoft/vscode/blob/a0ff19a2cd52ff079400e977a39c5bafb193a81b/src/vs/editor/contrib/inlineCompletions/browser/ghostTextWidget.ts#L161-L170

**Comment by meganrogge** [comment]
this reproduces when the audio cue plays. 

@jooyoungseo has disabled it because of the delay. @hediet is there anything we can do to play the audio cue immediately or is that impossible because it needs to be loaded every time?

**Comment by meganrogge** [comment]
@jooyoungseo could you pls let us know if this is now working as expected - even when you enable the audio cue?

**Comment by jooyoungseo** [comment]
@meganrogge -- I have confirmed that this issue was resolved in today's insiders. Also, the delay issue has been addressed! Many thanks.
