### ISSUE TITLE
WorkspaceConfiguration.update doesn't works inside deactivate method

### ISSUE THREAD

**Issue by MaxfieldWalker** [Microsoft/vscode#17767]
I'm developing an extension for vscode.

I want to save configuration value when vscode closed.
I tried to call `WorkspaceConfiguration.update` inside `deactivate()` of `extension.ts`, but the value seems not to be updated.

Is this a bug, or in the specifications?
Is there any other way to handle vscode closed event?

```typescript
// this method is called when your extension is deactivated
export function deactivate() {
    vscode.workspace.getConfiguration().update("configuration-key", value, true)
}
```

- VSCode Version: 1.8
- OS Version: Windows 10 Anniversarry Update

**Comment by jrieken** [comment]
The API still calls in to the configuration service. Unsure tho if that is still alive

**Comment by bpasero** [comment]
In https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/node/extensionHostProcess.ts#L46 we stop sending to the main side from the extension host when we are terminating. This was added via https://github.com/Microsoft/vscode/pull/13774 and I added my concern in https://github.com/Microsoft/vscode/pull/13774#issuecomment-254031946.

Moving to @alexandrudima

**Comment by alexandrudima** [comment]
`deactivate()` is good for clearing up system resources (i.e. kill processes, close file handles, close network sockets, etc.).

VS Code is possibly long dead when `deactivate()` gets called.
