### ISSUE TITLE
code --install-extension someext.vsix gives an exception, If the extension is already installed.

### ISSUE THREAD

**Issue by buzzzzer** [Microsoft/vscode#17768]
- VSCode Version: Code 1.8.1 (bac373f977096223c816e4342be3cd685e1c94d1, 2016-12-21T13:27:08.976Z)
- OS Version: Windows_NT ia32 10.0.14393
---
```
code --install-extension someext.vsix 
```
gives an exception, If the extension with same package version is already installed.

Steps to Reproduce:

1. code --install-extension anyext.vsix 
2. code --install-extension anyext.vsix 
```
WARNING: Promise with no error callback:39
{ exception: null,
  error: [ , , , , , , , , [ [Object] ] ],
  promise:
   Promise_ctor {
     _oncancel: null,
     _nextState: null,
     _state:
      { name: 'error',
        enter: [Function: enter],
        cancel: [Function: _],
        done: null,
        then: null,
        _completed: [Function: _],
        _error: [Function: _],
        _notify: [Function: notifyError],
        _progress: [Function: _],
        _setCompleteValue: [Function: _],
        _setErrorValue: [Function: _] },
     _listeners: null,
     _value: [ , , , , , , , , [Object] ],
     _isException: false,
     _errorId: 39,
     done: [Function: ErrorPromise_done],
     then: [Function: ErrorPromise_then] },
  handler: undefined,
  id: 39,
  parent: undefined }
```

**Comment by joaomoreno** [comment]
I can't repro this in Windows or OSX:

![image](https://cloud.githubusercontent.com/assets/22350/22293612/9907a38a-e310-11e6-8b43-e17a1a42df86.png)

![image](https://cloud.githubusercontent.com/assets/22350/22293620/9ee59adc-e310-11e6-8753-e510158c42a0.png)

Care to try to reproduce it? Maybe give me the exact command line you are running?

**Comment by buzzzzer** [comment]
@joaomoreno 
I install vsix file from hdd (build with vsce), not in marketplace.
![image](https://cloud.githubusercontent.com/assets/1981785/22320351/abda3f04-e39c-11e6-83eb-12b246a463f6.png)

**Comment by joaomoreno** [comment]
Can you send me that vsix?

**Comment by buzzzzer** [comment]
@joaomoreno yyyep.
[stack-1.0.4.vsix.zip](https://github.com/Microsoft/vscode/files/732023/stack-1.0.4.vsix.zip)

**Comment by gwicksted** [comment]
Would be nice if it overwrote the current version when authoring extensions/themes.  Potentially a `--force` flag that is mentioned when receiving this error.

**Comment by RangerDjanger** [comment]
@joaomoreno I have this same issue installing via CLI with VsCode 1.11.1. Is there a fix for this?

**Comment by joaomoreno** [comment]
The fix is in `master`. Will come out with `1.12`.
