### ISSUE TITLE
Drop support for windows 8 and 8.1

### ISSUE THREAD

**Issue by deepak1556** [microsoft/vscode#177676]
Refs https://www.electronjs.org/blog/windows-7-to-8-1-deprecation-notice

**March milestone:**

- [x] Push EOL message via top status bar and notification
- [x] @isidorn to help with updating requirements and FAQ section in the website

**May milestone:**

- [ ] Flip switch in update server to disable updates

**Comment by isidorn** [comment]
@deepak1556 we do this in April?

**Comment by deepak1556** [comment]
We can push the client side notification for March release. Or you mean do we make April release `v1.78` as the last release ?

**Comment by isidorn** [comment]
I meant the notification. So let's assign this to March so we do not lose track :)

**Comment by deepak1556** [comment]
Steps for the `March 2023` milestone are complete.
