### ISSUE TITLE
Integration Tests of an extension test are failing

### ISSUE THREAD

**Issue by mohseenrm** [Microsoft/vscode#17763]
- VSCode Version: vscode@1.0.3
- OS Version: 10.12.3 and Ubuntu 12.04.5 LTS

Steps to Reproduce:

1. npm install && npm run vscode:prepublish

npm@3.10.9
node@v6.9.2
nvm@0.32.0

Repo: https://github.com/mohseenrm/lit-it
Travis: https://travis-ci.org/mohseenrm/lit-it/jobs/186272789

Issue: 
Tests run locally and pass. Same error on local machine though (mentioned MAC OS).
`npm ERR! Failed at the lit-it@1.2.10 vscode:prepublish script 'node ./node_modules/vscode/bin/compile'.`
[Travis Raw Log](https://s3.amazonaws.com/archive.travis-ci.org/jobs/186272789/log.txt)

**Comment by bpasero** [comment]
This issue was moved to Microsoft/vscode-extension-vscode#47
