### ISSUE TITLE
Test impacted extensions with Electron 22 and custom memory allocator

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#177645]
Refs: https://github.com/microsoft/vscode/issues/177338

- [x] macOS: @rzhao271 
- [x] linux: @deepak1556 @isidorn 
- [x] windows: @bpasero

Complexity: 5

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23177645%0A%0A&assignees=bpasero)

---

The new custom memory allocator in VS Code with Electron 22 should be tested to ensure:
* our top extensions continue to work as before
* extensions with known problematic native modules continue to work as before and do not crash VS Code

###  Prerequisites
Testing has to be done on (orange) VS Code exploration builds with Electron 22. Downloads:
* macOS: [`c49c0f16`](https://builds.code.visualstudio.com/builds/exploration?commit=c49c0f1617b7a783fd8a3823ee5a7d45f846d79f)
* Windows: [`c49c0f16`](https://builds.code.visualstudio.com/builds/exploration?commit=c49c0f1617b7a783fd8a3823ee5a7d45f846d79f)
* Linux: [`c49c0f16`](https://builds.code.visualstudio.com/builds/exploration?commit=c49c0f1617b7a783fd8a3823ee5a7d45f846d79f)

### Test Strategy
* do exploratory smoke testing of the extension triggering some of its functionality to verify it works
* see the native module the extension depends on to try to explicitly trigger the native code if possible
* limit testing to 5 minutes max, since there are many extensions to test
* watch out for extension host crashes or crashes in general

### Test Problematic Extensions
All of the below extensions depend on a native module with a problematic memory allocation. Pick 1-3 extensions per native module to ensure coverage. Skip those that are obscure to test.

* [samundrak.esdoc-mdn](https://marketplace.visualstudio.com/items?itemName=samundrak.esdoc-mdn)
    * [`uws`](https://www.npmjs.com/package/uws)
* [litleleprikon.socket-io-vscode](https://marketplace.visualstudio.com/items?itemName=litleleprikon.socket-io-vscode)
    * [`uws`](https://www.npmjs.com/package/uws)
* [sasxa-net.angular-gui](https://marketplace.visualstudio.com/items?itemName=sasxa-net.angular-gui)
    * [`uws`](https://www.npmjs.com/package/uws)
* [appcandev.appcanmaswin](https://marketplace.visualstudio.com/items?itemName=appcandev.appcanmaswin) <- seems like an account is needed
    * [`uws`](https://www.npmjs.com/package/uws)
* [lucasbento.react-native-actions](https://marketplace.visualstudio.com/items?itemName=lucasbento.react-native-actions)
    * [`uws`](https://www.npmjs.com/package/uws)
* [samundrak.esdoc-mdn](https://marketplace.visualstudio.com/items?itemName=samundrak.esdoc-mdn)
    * [`uws`](https://www.npmjs.com/package/uws)
* [dkupco.viewx](https://marketplace.visualstudio.com/items?itemName=dkupco.viewx)
    * [`uws`](https://www.npmjs.com/package/uws)
* [litleleprikon.socket-io-vscode](https://marketplace.visualstudio.com/items?itemName=litleleprikon.socket-io-vscode)
    * [`uws`](https://www.npmjs.com/package/uws)
* [lereenadem.pascalabcnet](https://marketplace.visualstudio.com/items?itemName=lereenadem.pascalabcnet)
    * [`tree-sitter`](https://www.npmjs.com/package/tree-sitter)
* [appresso.navigateto](https://marketplace.visualstudio.com/items?itemName=appresso.navigateto)
    * [`tree-sitter`](https://www.npmjs.com/package/tree-sitter)
* [polarmutex.beancount-langserver](https://marketplace.visualstudio.com/items?itemName=polarmutex.beancount-langserver)
    * [`tree-sitter`](https://www.npmjs.com/package/tree-sitter)
* [CJDNS.safepkt-verifier](https://marketplace.visualstudio.com/items?itemName=CJDNS.safepkt-verifier)
    * [`tree-sitter`](https://www.npmjs.com/package/tree-sitter)
* [ganezdragon.perl-language-server](https://marketplace.visualstudio.com/items?itemName=ganezdragon.perl-language-server)
    * [`tree-sitter`](https://www.npmjs.com/package/tree-sitter)
* [GuanceCloud.platypus-vscode](https://marketplace.visualstudio.com/items?itemName=GuanceCloud.platypus-vscode)
    * [`tree-sitter`](https://www.npmjs.com/package/tree-sitter)
* [Elmtooling.elm-ls-vscode](https://marketplace.visualstudio.com/items?itemName=Elmtooling.elm-ls-vscode)
    * [`tree-sitter`](https://www.npmjs.com/package/tree-sitter)
* [PenguinCabinet.writer-stock](https://marketplace.visualstudio.com/items?itemName=PenguinCabinet.writer-stock) <- doesn't seem to work even on Insiders
    * [`canvas`](https://www.npmjs.com/package/canvas)
* [manhen.latex-workshop-2](https://marketplace.visualstudio.com/items?itemName=manhen.latex-workshop-2)
    * [`canvas`](https://www.npmjs.com/package/canvas)
* [gregk.botbuilder](https://marketplace.visualstudio.com/items?itemName=gregk.botbuilder)
    * [`canvas`](https://www.npmjs.com/package/canvas)
* [NourEldeen.LiteGraph](https://marketplace.visualstudio.com/items?itemName=NourEldeen.LiteGraph) <- has a bunch of CSP problems
    * [`canvas`](https://www.npmjs.com/package/canvas)
* [FastAutomate.FastAutomateVisualise](https://marketplace.visualstudio.com/items?itemName=FastAutomate.FastAutomateVisualise)
    * [`canvas`](https://www.npmjs.com/package/canvas)
* [mdk.vega-preview](https://marketplace.visualstudio.com/items?itemName=mdk.vega-preview) 
    * [`canvas`](https://www.npmjs.com/package/canvas)
* [mrakgr.spiral-lang-vscode](https://marketplace.visualstudio.com/items?itemName=mrakgr.spiral-lang-vscode)
    * [`zeromq`](https://www.npmjs.com/package/zeromq)
* [data-chimp.data-chimp](https://marketplace.visualstudio.com/items?itemName=data-chimp.data-chimp)
    * [`zeromq`](https://www.npmjs.com/package/zeromq)
* [njpipeorgan.wolfram-language-notebook](https://marketplace.visualstudio.com/items?itemName=njpipeorgan.wolfram-language-notebook)
    * [`zeromq`](https://www.npmjs.com/package/zeromq)
* [appcandev.appcanmaswin](https://marketplace.visualstudio.com/items?itemName=appcandev.appcanmaswin)
    * [`odbc`](https://www.npmjs.com/package/odbc)
* [ElbekVejrup.ev-business-central-dev-tool](https://marketplace.visualstudio.com/items?itemName=ElbekVejrup.ev-business-central-dev-tool)
    * [`odbc`](https://www.npmjs.com/package/odbc)
* [aliprodfmir.dfmir2](https://marketplace.visualstudio.com/items?itemName=aliprodfmir.dfmir2)
    * [`odbc`](https://www.npmjs.com/package/odbc)
* [zdldove.font-spider](https://marketplace.visualstudio.com/items?itemName=zdldove.font-spider)
    * [`ttf2woff2`](https://www.npmjs.com/package/ttf2woff2)
* [george.svg2font-extension](https://marketplace.visualstudio.com/items?itemName=george.svg2font-extension) <- on macOS, there's the console error "Invalid asm.js: Invalid member of stdlib"
    * [`ttf2woff2`](https://www.npmjs.com/package/ttf2woff2)
* [algo-sh.algo-sh](https://marketplace.visualstudio.com/items?itemName=algo-sh.algo-sh)
    * [`libpq`](https://www.npmjs.com/package/libpq)
* [uniquevision.vscode-plpgsql-lsp](https://marketplace.visualstudio.com/items?itemName=uniquevision.vscode-plpgsql-lsp)
    * [`libpq`](https://www.npmjs.com/package/libpq)
* [zat.vartrace](https://marketplace.visualstudio.com/items?itemName=zat.vartrace)
    * [`better-sqlite3`](https://www.npmjs.com/package/better-sqlite3)
* [widyhu.cpptips](https://marketplace.visualstudio.com/items?itemName=widyhu.cpptips)
    * [`better-sqlite3`](https://www.npmjs.com/package/better-sqlite3)
* [gustavofsantos.dat-dir](https://marketplace.visualstudio.com/items?itemName=gustavofsantos.dat-dir)
    * [`sodium-native`](https://www.npmjs.com/package/sodium-native)
* [m417z.regedit](https://marketplace.visualstudio.com/items?itemName=m417z.regedit)
    * [`native-reg`](https://www.npmjs.com/package/native-reg)

**Comment by rzhao271** [comment]
A bunch of the extensions don't seem to work, but I never had the entire exthost or Code - Exploration crash.

**Comment by isidorn** [comment]
I suggest to skip all extensions that have less < 500 installs.

**Comment by bpasero** [comment]
Had a hard time getting most of the extensions to work. RegEdit was really nice on Windows though ✔️

**Comment by rzhao271** [comment]
> @rzhao271 to confirm, did you test with exploration build based on `v22.4.2` ? the version in the screenshot above is invalid.

I tested with the linked commit.

**Comment by deepak1556** [comment]
Thanks for confirming!
