### ISSUE TITLE
Testing findTextInFiles: TextSearchResult is always an array: Range[] and never just a Range

### ISSUE THREAD

**Issue by ArturoDent** [microsoft/vscode#177618]
I see that 

    vscode.workspace.findTextInFiles(searchQuery, async (result: vscode.TextSearchResult) => {

callback gives a `vscode.TextSearchResult` type which has this shape:

```jsonc
export interface TextSearchMatch {
		/**
		 * The uri for the matching document.
		 */
		uri: Uri;

		/**
		 * The range of the match within the document, or multiple ranges for multiple matches.
		 */
		ranges: Range | Range[];

		/**
		 * A preview of the text match.
		 */
		preview: TextSearchMatchPreview;
	}
```

But in my testing `ranges` is always `Range[]` even if there is only one match in that file.  

Is that correct?  It makes typescript finicky to work with, I need to do this: 

```typescript
vscode.workspace.findTextInFiles(searchQuery, async (result: vscode.TextSearchResult) => {
  if (result) {
    resultsSet.add(result);
  }
})
.then(async (data: vscode.TextSearchComplete) => {

  const wse: vscode.WorkspaceEdit = new vscode.WorkspaceEdit();

  resultsSet.forEach(result => {
    const textEdits: Array<vscode.TextEdit> = [];

    if ("ranges" in result && Array.isArray(result.ranges)) {               // to appease typescript
      result.ranges.forEach(range => textEdits.push(vscode.TextEdit.replace(range, `${result.uri.fsPath}`)));

    wse.set(result.uri, textEdits);
  });

  await vscode.workspace.applyEdit(wse);
});
```

Specifically, the `Array.isArray(result.ranges)` "narrowing" because by the spec `ranges` could be simply a `Range` (and not necessarily an array).

What would cause the result to be a simple non-array `Range`?

@andreamah 

-------
Version: 1.77.0-insider
Commit: 2a6bd78f745d3e6330c8ff7db5282dc582e117fd
Date: 2023-03-17T21:01:31.900Z
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Code-Insiders/1.77.0-insider Chrome/102.0.5005.196 Electron/19.1.11 Safari/537.36

**Comment by andreamah** [comment]
> What would cause the result to be a simple non-array Range?

It could be very true that it never returns just a `Range`. I'd need to double-check the code, since offerring a `Range | Range[]` type seems quite common in the internal implementation.

**Comment by eleanorjboyd** [comment]
Hi! Is this still causing an issue for you?
