### ISSUE TITLE
[Feature Request] The command palette doesn't support Ctrl-n/Ctrl-p key binding for navigation.

### ISSUE THREAD

**Issue by ugoa** [Microsoft/vscode#17761]
- VSCode Version: 1.8.1
- OS Version: macOS Sierra

I love the Emacs keybindings on macOS, and the Ctrl-n/p for going up/down works almost everywhere on Mac, however the VSCode command palette doesn't support it, so everytime I have to use that tiny up/down keys to choose, which is quite inconvenient.
Please add this tiny feature and I will love VSCode much more! :1st_place_medal: 
Cheers!

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/7876
