### ISSUE TITLE
Show extension display name instead of extension id

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#177776]
Testing #177735

Show extension display name instead of extension id. You can also make them links to open the extension editor.

<img width="522" alt="image" src="https://user-images.githubusercontent.com/10746682/226570520-3ae6f7ac-b2c3-492e-b67f-309fd0393b11.png">

**Comment by Tyriar** [comment]
@sandy081 what's the right way to do this? I had a look and could only see async methods to do this which seemed odd to me (and would require some refactoring to get the tooltip to work with async).

**Comment by eleanorjboyd** [comment]
+ 1 I see this as well

**Comment by Tyriar** [comment]
@sandy081 thanks will use that. You don't have an id -> name map to avoid iterating over it multiple times though?

**Comment by sandy081** [comment]
There exists one, but it is async

https://github.com/microsoft/vscode/blob/2ea2c80d633f93f10b3bbe1ad6571a5468d4a7c5/src/vs/workbench/services/extensions/common/extensions.ts#L398
