### ISSUE TITLE
Hover opens at wrong place when triggered via keyboard

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#177775]
Testing #177735

<img width="1103" alt="image" src="https://user-images.githubusercontent.com/10746682/226569777-433cc6c5-e45c-4325-a947-3cc39e7cd71d.png">

**Comment by Tyriar** [comment]
This was actually intentional and doesn't seem like a big deal to me. I'll have a look to see if it's easy to do.

**Comment by Tyriar** [comment]
I think the HTML element of the action is internal to the view code so closing as out of scope since it's not that important.
