### ISSUE TITLE
Bug: running yarn berry (3.5) requires sudo access

### ISSUE THREAD

**Issue by danialdezfouli** [microsoft/vscode#177742]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.76.2 arm64
- OS Version: macOS 13.2.1

Steps to Reproduce:

calling yarn without sudo in vscode causes `Segmentation fault` error.
everything is fine in the mac Terminal app.
reinstalling it with `brew install yarn` and `npm i -g yarn` didn't help.

vscode terminal:
```bash
bash-3.2$ yarn -v
Segmentation fault: 11
bash-3.2$ yarn
Segmentation fault: 11
bash-3.2$ sudo yarn -v
3.5.0
bash-3.2$ 
```

 System:
    OS: macOS 13.2.1
    CPU: (10) x64 Apple M1 Pro
  Binaries:
    Node: 18.15.0 - /private/var/folders/j3/xxx/T/xfs-yyy/node
    Yarn: 3.5.0 - /private/var/folders/j3/xxx/T/xfs-yyy/yarn
    npm: 9.6.2 - /usr/local/bin/npm
  npmPackages:
    jest: ^29.5.0 => 29.5.0

**Comment by lramos15** [comment]
Are you saying calling yarn in an external terminal doesn't seg fault? We just pass the commands forward to the terminal, their execution doesn't change

**Comment by danialdezfouli** [comment]
when I install it via Terminal, it works on vscode and has an error on Terminal
when I install it via vscode, it works on Terminal and has an error on vscode

maybe it's more from yarn than vscode
strangest bug I have ever seen

**Comment by meganrogge** [comment]
just noticed this in your issue details:

> Binaries:
Yarn: 3.5.0 - /private/var/folders/j3/xxx/T/xfs-yyy/yarn

could it be that this install location requires permissions that VS Code cannot access?

**Comment by danialdezfouli** [comment]
I tried both zsh and bash, also clearing settings.json didn't change anything.

actual yarn is in `/usr/local/bin/yarn` that's how the yarn berry shows the path

<img width="1084" alt="image" src="https://user-images.githubusercontent.com/12775482/226635690-4d80ce79-c275-4c3a-b6a4-bfa4145303b6.png">

**Comment by meganrogge** [comment]
> are you using a login shell in VS Code? Can you provide me with your settings.json file?

**Comment by danialdezfouli** [comment]
the problem was with Node `18.15.0 LTS` upgrading to the latest `19.8.1` fixed the issue.
the weird part was it was only happening in vscode...
