### ISSUE TITLE
Workbench screen cheese

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#17774]
Not yet sure how it happens, but today I ended up a couple of times with a workbench that looks as shown below. The last time it happened after expanding `OPEN EDITORS` but it doesn't repo just like that...

![screen shot 2016-12-23 at 14 54 52](https://cloud.githubusercontent.com/assets/1794099/21455362/f67a6da0-c91f-11e6-97a7-c52b94b74f93.png)

**Comment by bpasero** [comment]
@jrieken next time it happens would be interesting to know if any element is overflowing the workbench container. It almost looks like an element is going beyond the size of the workbench. Though the screenshot is really weird because things move below the status bar...

**Comment by isidorn** [comment]
@jrieken is regularly using zen mode so my hunch is that going in/out of full screen and then relayouting the workbench maybe has some timiing issues. Do you have zen mode setup to go into fullscreen?

There were no recent changes in the open editors layouting area thus I suspect zen mode

**Comment by bpasero** [comment]
Yes, zen mode is a very good catch. The overflow looks like the exact same size the title bar typically consumes.

**Comment by isidorn** [comment]
@joaomoreno caught this. The issue was that the layout call was not being called at the end of setSideBarHidden but at the beggining. Another issue was that toggleZenMode was not forcing a style recompute when doing a workbench layout

**Comment by jrieken** [comment]
Didn't see this in a long time anymore
