### ISSUE TITLE
Numbering and Cross-referencing equations in Markdown doesn't work.

### ISSUE THREAD

**Issue by thangckt** [microsoft/vscode#177717]
Example:
Enter this text in a markdown cell:
```
\begin{align}  \label{eq1}
    g &= \int_a^b f(x)dx  \\
    a &= b + c 
\end{align}
```
See (\ref{eq1})

Then,
- The `\label{}` option cannot be used
- The equation number is reset in a new cell

More detail is described [here](https://stackoverflow.com/questions/61884029/equation-numbering-between-cells-in-jupyter-resets-to-1)

How to make the equation number continue on the new cell? 

Thank

**Comment by mjbvz** [comment]
Tracked upstream by https://github.com/KaTeX/KaTeX/issues/2003

**Comment by mjbvz** [comment]
Closing as upstream
