### ISSUE TITLE
Change appearance of line cursor in terminal panel when terminal loses focus

### ISSUE THREAD

**Issue by rben01** [microsoft/vscode#177736]
## Relevant settings:
* `"terminal.integrated.cursorBlinking": true`
* `"terminal.integrated.cursorStyle": "line"`

## Description
With the above settings in effect and a terminal open in the bottom panel:
* If the terminal has focus, the cursor blinks
* If the terminal doesn't have focus, then the cursor remains visible without blinking

Unlike the block-shaped cursor, which becomes hollow when the terminal loses focus, the line-shaped cursor doesn't change appearance when the terminal loses focus; it merely stops blinking. This makes it hard to tell at a glance whether the terminal has focus.

## Feature Request
So that it's easier to tell whether the terminal has focus, I would like an option to customize how the line-shaped cursor appears in the terminal when it doesn't have focus. Possible options (not exhaustive):
* Hide the cursor altogether
* Keep it visible, but make it (say) 50% opacity
* Show the same hollow block that's used with the block-shaped cursor

**Comment by Tyriar** [comment]
I actually thought it showed the hollow block in this case, I think that makes the most sense 👍 https://github.com/xtermjs/xterm.js/issues/4441

**Comment by tisilent** [comment]
try try

**Comment by Tyriar** [comment]
We're going back on the decision made in https://github.com/microsoft/vscode/issues/67410 and making unfocused show the rectangle regardless of cursor style. Discussion: https://github.com/xtermjs/xterm.js/pull/4443#pullrequestreview-1352650136
