### ISSUE TITLE
Copy links to vscode.dev & GitHub are shown for files that don't exist on that remote repo

### ISSUE THREAD

**Issue by ulugbekna** [microsoft/vscode#177793]
Testing #177486

One can copy links to vscode.dev & github & azure repos even though I just created the file and copying such a link will result in empty vscode.dev or 404 on GH. 

Seeing links to just created file `foo.ml`: 

<img width="451" alt="image" src="https://user-images.githubusercontent.com/16353531/226594258-7d4e3834-ee23-48f1-8be5-0686d0ba4cfc.png">

**Comment by joyceerhl** [comment]
No progress on this one yet, but @ulugbekna would you expect the actions to be hidden, or would you want to be prompted to commit the file to the remote when the command is invoked?

**Comment by ulugbekna** [comment]
I think users could be confused if the actions wouldn't appear (eg they might've forgotten the file isn't pushed), so the latter sounds better.

But I wonder whether checking whether the file is available on remote slow 🤔
