### ISSUE TITLE
Stash commands don't return the result of the action

### ISSUE THREAD

**Issue by robertohuertasm** [microsoft/vscode#177726]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.76.2
- OS Version: All

While developing a vscode extension I've needed to execute the `git stash` command but unfortunately, even though the common [_stash](https://github.com/microsoft/vscode/blob/d62b013f2d8f0a53a8f540d648972ab34e868769/extensions/git/src/commands.ts#L3036) method returns a `boolean` indicating if the stash succeeded or not (because of an error or a user cancellation), all the [public `stash`](https://github.com/microsoft/vscode/blob/d62b013f2d8f0a53a8f540d648972ab34e868769/extensions/git/src/commands.ts#L3111) commands are not returning that boolean, thus making it impossible to understand if the stash took place or not.

It would be nice to have this information so we could redirect the flow in case the stash fails or the user cancels it.

**Comment by lszomoru** [comment]
Verification steps:
1. Review the PR that implemented the change - https://github.com/microsoft/vscode/commit/62a957135be92a710e037fd127c9c75cce60206c
