### ISSUE TITLE
Test: Notebook format on save and onWillSaveNotebookDocument

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#177746]
Refs: https://github.com/microsoft/vscode/issues/91473

- [x] anyOS @aiday-mar
- [x] anyOS @amunger

Complexity: 4

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23177746%0A%0A&assignees=rebornix)

---

We added save participant support for notebook documents. They are hooked up in two different places

* format on save, which can be turned on by `notebook.formatOnSave.enabled`
  * To test this, install both Jupyter and Python extension prereleases
  * Create a new ipynb file, turn on format on save, press ctrl/cmd+s to trigger format on save
  * Python extension will prompt for installing formatter, you can pick black and it auto installs
  * Please test the cells are all formated
* onWillSaveNotebookDocument
  * You can try build interesting extension for the API but you can also play around with the sample https://github.com/rebornix/notebook-will-save

**Comment by amunger** [comment]
the performance of the format action is pretty concerning, I can close the window long before the save actually finishes.
