### ISSUE TITLE
提交失败

### ISSUE THREAD

**Issue by Youngyang888** [Microsoft/vscode#17778]
- VSCode Version: Code 1.8.1 **[Unsupported]** (ee428b0eead68bf0fb99ab5fdc4439be227b6281, 2016-12-19T14:42:49.304Z)
- OS Version: Darwin x64 16.3.0
- Extensions:

|Extension|Author|Version|
|---|---|---|
|mithril-emmet|FallenMax|0.5.1|
|html-snippets|abusaidm|0.0.18|
|vscode-html-css|ecmel|0.0.30|
|vscode-JS-CSS-HTML-formatter|lonefy|0.2.2|
|code-beautifier|michelemelluso|1.6.2|
|debugger-for-chrome|msjsdiag|2.4.1|
|view-in-browser|qinjia|0.0.3|
|vscode-icons|robertohuertasm|4.2.0|
|background|shalldie|1.1.9|

---

Steps to Reproduce:

1.
2.

**Comment by egamma** [comment]
>VSCode Version: Code 1.8.1 **[Unsupported]** (ee428b0, 2016-12-19T14:42:49.304Z)

@Youngyang888 you are reporting an issue for an unsupported version of VS Code, that is a version of VS Code that has an extension installed that patches VS Code.  We cannot provide support for patched versions.

Please reopen the issue when you can reproduce it with all extensions disabled.
