### ISSUE TITLE
Double scrollbars

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode#177792]
Testing #177719

The editor and the cells have scrollbars which is confusing to look at and difficult to use.

Maybe instead of adding scrollbars to cells, let them show a 'Show More' button at the bottom when the content grows too large and let that expand the cell to show all content? (Maybe then show a 'Show Less' button at the bottom of a fully expanded cell to go back.)

**Comment by Tyriar** [comment]
I also find it a little strange that we decided to go with a scrollable region here, but not for the actual editor. The UX of a scrollable region in a scrollable region is pretty bad, mouse wheel down in the gif below shows that scrolling down will get "caught" on an output cell:

![Recording 2023-03-21 at 10 56 33](https://user-images.githubusercontent.com/2193314/226699295-ac352f85-c929-45df-967c-2e98ea030ec7.gif)

**Comment by rebornix** [comment]
> Maybe instead of adding scrollbars to cells, let them show a 'Show More' button at the bottom when the content grows too large and let that expand the cell to show all content? (Maybe then show a 'Show Less' button at the bottom of a fully expanded cell to go back.)

@chrmarti @Tyriar thanks for the feedback. The original design is what you described, we don't show scrollable output at all but it's not how most Jupyter users use streaming and error outputs. They expect a scrollable output which contains enough text that they can search. That's why we experimented the scrollable output support and also considering making it the default experience.

**Comment by amunger** [comment]
sounds like this request that we received pretty early on https://github.com/microsoft/vscode/issues/174951, which I liked quite a bit.

That way we could have both view types easily available and reduce the drawbacks of having so many scrollable sub-regions

**Comment by chrmarti** [comment]
https://github.com/microsoft/vscode/issues/174951 sounds like it would still show double scrollbars. Couldn't these be avoided by having a button to go from capped to full output size? This would preserve the editor's behavior as a "single large document" that can be scrolled.

**Comment by amunger** [comment]
This was a very popular request, which is why it was implemented this way. Expanding to show the full output might look strange when the output is very large. We'll keep gathering feedback from users to try and improve though.
