### ISSUE TITLE
Hover is shown as plain markdown

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#177774]
Testing #177735

🐛 Terminal hover is shown as plain markdown text and I am not able to move my cursor into the hover as it is disappearing immediately.

<img width="671" alt="image" src="https://user-images.githubusercontent.com/10746682/226567097-c246ff8c-be84-4eaf-8c65-cb7fb58e755e.png">

**Comment by hediet** [comment]
![image](https://github.com/microsoft/vscode/assets/2931520/270b56e6-ffd3-407b-97c0-0d0258648eba)

I think the text in the top could use more markdown formatting. E.g. formatting the propery names as italic and formatting the command line string as code using backticks.

**Comment by Tyriar** [comment]
@hediet command line was in a code block initially and it looks pretty awful. I'll be revisiting that in https://github.com/microsoft/vscode/issues/187853

@daviddossett any thoughts on general improvements to the terminal hover design?

**Comment by daviddossett** [comment]
To clarify, this specific hover's markdown? Or do you mean terminal hovers in general?

**Comment by Tyriar** [comment]
@daviddossett just the terminal tab one
