### ISSUE TITLE
Security by least privilege

### ISSUE THREAD

**Issue by MartinMcCaulley** [microsoft/vscode#177734]
Type: <b>Bug</b>

You should not be remembering terminal sessions. It is taking longer and longer for the bash terminal to restore itself. It is unnecessary and a security issue. Let .bashrc do the heavy lifting and stop trying to do too much in the vscode shell.

VS Code version: Code 1.76.2 (ee2b180d582a7f601fa6ecfdad8d9fd269ab1884, 2023-03-14T17:55:54.936Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: No

**Comment by Tyriar** [comment]
You can disable the terminal restoration features and shell integration. I believe the main slowdown actually came when we changed the process architecture to enable reconnection and prevent a crashed terminal proc from taking down VS Code. We'll be improving this soon in https://github.com/microsoft/vscode/issues/175335
