### ISSUE TITLE
Copy/Cut and Paste are broken

### ISSUE THREAD

**Issue by lmmfranco** [Microsoft/vscode#17772]
- VSCode Version: 1.8.1
- OS Version: Windows 10 / Ubuntu 14

Steps to Reproduce:

1. Type some lines of text:
```
aaaaa
bbbbb
ccccc
```
2. Select `bbbbb` and copy/cut it
3. Delete all lines with `shift+del` _(arrow up, shift+del x3)_
4. Paste what you got on clipboard

Found result:
```
ccccc

```

Expected result:
```
bbbbb
```

This is so frustrating while coding.

**Comment by lmmfranco** [comment]
Just realized `shift+delete` is tagged as "Cut". I feel dumb now.
Gonna remap my keys.

**Comment by egamma** [comment]
@lmmfranco just to confirm, then it is OK to close this issue?

**Comment by lmmfranco** [comment]
Oh yeah, sorry.
