### ISSUE TITLE
Import intellisense bug for some packages

### ISSUE THREAD

**Issue by emilekberg** [Microsoft/vscode#17770]
- VSCode Version: Code 1.8.1 (ee428b0eead68bf0fb99ab5fdc4439be227b6281, 2016-12-19T14:49:23.350Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

|Extension|Author|Version|
|---|---|---|
|tslint|eg2|0.7.1|
|csharp|ms-vscode|1.6.1|
|debugger-for-chrome|msjsdiag|2.4.1|
|vscode-format|ryannaddy|0.0.6|
|shader|slevesque|0.2.2|
|shader-toy|stevensona|0.1.8|

---

Steps to Reproduce:

1. Install pixi.js from npm with typings
2. Try to import a relative path downwards( import Person from '../person' for instance ). The import will suggest "pixi.js" as it includes a '.' character or something.

**Comment by egamma** [comment]
@emilekberg in general please include snippets and screenshots that illustrate the problem and provide precise steps with snippets,  screenshots that illustrates a problem (see our [issue reporting guidelines](https://github.com/Microsoft/vscode/wiki/Submitting-Bugs-and-Suggestions)). 

Please confirm that this is the issue you intend to report:

- npm install pixi.js
- create a file test.js
- create a file person.js
- add the following import `import * from '<intellisense>'
Notice that 'pixi.js' is suggested (see the screenshot below).

![image](https://cloud.githubusercontent.com/assets/172399/21456591/8dd7d5b2-c929-11e6-8499-57a8c7d052bf.png)

**Comment by emilekberg** [comment]
Sorry, i provided a video now, it includes full editor and you can see the structure there. 
The tsconfig.json is standard, so is package.json with saved pixi.js and @types/pixi.js

https://www.youtube.com/watch?v=oSgdPsbaEO0

Steps to reproduce is: 

1. npm init
2. npm install pixi.js @types/pixi.js
3. tsc --init
4. create file1.ts in a folder, (./src/file1.ts) containing a class: 
```
export default class File1 {
    constructor() {

    }
}
```
5. create file2.ts in a subfolder 
6. try to import a relative path to File1. When you're going to type a relative step back (../), it will autocorrect to "pixi.js" instead of ".." as shown in the video. 

If anything more is needed, please let me know. hope this make things a bit clearer

**Comment by egamma** [comment]
@emilekberg thanks for the additional info.

**Comment by emilekberg** [comment]
Short update, it does not seem to happen when running js. i thought it might due to the automatic type acquisition, but it works as intended, for me at least.

**Comment by winpzs** [comment]
me too

**Comment by waderyan** [comment]
@mjbvz this looks like an issue we've seen before...

**Comment by joaomoreno** [comment]
Fix reverted 31997b32c354b0531f296379cec364b094ee362d, #18063

**Comment by mjbvz** [comment]
Picked up improved fix with #18380
