### ISSUE TITLE
Source control repos hidden after adding (cloning) a new one

### ISSUE THREAD

**Issue by entenbein** [microsoft/vscode#177794]
Type: <b>Bug</b>

Hi there,

I got one folder which holds all my git repos (> 90). I ususally open this folder in source control to get an overview over all my repos. When cloning a new repo all "alphabetically lower" repo folder are hidden/get deselected.
Let's say I got folders starting with A - Z. Now I clone a new repo which starts with T. After that all folders from A to that new repo (starting with) T are not selected for source control. In other words all folders above/before the newly cloned repo are not shown.

I can include them again via ... -> View & Sort -> Repositories -> ticking every single repo (which is not an option).

Thanks and Regards

entenbein

VS Code version: Code 1.76.2 (ee2b180d582a7f601fa6ecfdad8d9fd269ab1884, 2023-03-14T17:57:21.103Z)
OS version: Linux x64 5.4.0-144-generic
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-7100 CPU @ 3.90GHz (4 x 3900)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|7, 6, 5|
|Memory (System)|7.67GB (1.11GB free)|
|Process Argv|--no-sandbox --unity-launch --crash-reporter-id ddabf673-eae9-4d99-992e-073bee82200b|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|xubuntu|
|XDG_CURRENT_DESKTOP|XFCE|
|XDG_SESSION_DESKTOP|xubuntu|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (20)</summary>

Extension|Author (truncated)|Version
---|---|---
ActiveFileInStatusBar|Ros|1.0.3
markdown-preview-github-styles|bie|1.0.1
githistory|don|0.6.20
vscode-docker|ms-|1.24.0
vscode-language-pack-de|MS-|1.76.2023030809
isort|ms-|2022.8.0
python|ms-|2023.4.1
vscode-pylance|ms-|2023.3.20
remote-containers|ms-|0.282.0
remote-ssh|ms-|0.98.0
remote-ssh-edit|ms-|0.84.0
remote-wsl|ms-|0.76.1
vscode-remote-extensionpack|ms-|0.24.0
remote-explorer|ms-|0.2.0
remote-server|ms-|1.0.0
material-icon-theme|PKi|4.25.0
bash-beautify|sha|0.1.1
scm-buttons-vscode|tom|0.1.1
sort-lines|Tyr|1.9.1
material-theme|zhu|3.15.8

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263cf:30335440
vscorecescf:30445987
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
pynewext54:30681850
azure-dev_surveyone:30548225
pyindex848:30662994
nodejswelcome1cf:30587006
282f8724:30602487
pyind779:30671433
89544117:30613380
pythonsymbol12:30671437
vsctsb:30677850
vscodedisable:30660115
defaultazurewalk:30687958
pythonms35:30686772

```

</details>

**Comment by kszonek** [comment]
I have the same (similar) issue.

Also multiple repositories in one folder, I have workspace file to have them nicely sorted in Explorer, labels are also used in source control view. After some changes in repos (clone/delete), some of them are hidden. I need to manually tick availability, which is annoying for 10, but painful for 50+.

Is there a file that keeps info which repos are hidden and which are shown? I am thinking about working around with some script. Also another **great option** would be `Show All` under `Source Control -> View and Sort -> Repositories`

**Comment by lszomoru** [comment]
Could you try the following: 
* Open the command palette and execute the "Source Control: Focus on Source Control Repositories view" command
* Click on the first repository in the list
* Shift+Click on the last repository in the list which should result in all repositories being selected in the Source Control Repositories view, and visible in the Source Control view

**Comment by kszonek** [comment]
> Could you try the following:
> 
> * Open the command palette and execute the "Source Control: Focus on Source Control Repositories view" command
> * Click on the first repository in the list
> * Shift+Click on the last repository in the list which should result in all repositories being selected in the Source Control Repositories view, and visible in the Source Control view

Genius move!
Worked perfectly, all selected, all visible below.
This solution is not really user friendly, but will definitely save some time next time, when new repo is added.

Thanks so much!
