### ISSUE TITLE
No way to use `runCommands` with `editor.action.triggerSuggest`

### ISSUE THREAD

**Issue by zardoy** [microsoft/vscode#177750]
I want to build action with using completion lists (suggest widget - e.g. accept first/second completion and so on)

STR:

```json
[
    {
        "key": "alt+c",
        "command": "runCommands",
        "args": {
            "commands": [
                "editor.action.triggerSuggest",
                "acceptSelectedSuggestion"
            ]
        }
    }
]
```

*(optionally add `"selectNextSuggestion"` in between)*

Doesn't work, widget is shown, but suggestion not accepted.

And... I ideally have a fix for this in https://github.com/microsoft/vscode/pull/166094/, it works so well that even suggest widget blinking is not visible.

Mentioning @ulugbekna as I believe you added this wonderful command (at least I saw #177722)

**Comment by ulugbekna** [comment]
Hi @zardoy ,

Thanks for filing the issue.

I'm afraid, it's not a `runCommands` problem, as you pointed out yourself -- it's `editor.action.triggerSuggest`.
