### ISSUE TITLE
openFolderButton code duplication

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#17776]
There are 3 duplicates of creation of a `openFolderButton`
Can we move this code to some helper method so we do not have the same code duplicated 3 times?

![screen shot 2016-12-23 at 15 20 12](https://cloud.githubusercontent.com/assets/1926584/21455780/5db54bc2-c923-11e6-9205-65876c56ee40.png)

**Comment by isidorn** [comment]
Though we might not need this for debug soon since we might support no folder debugging

**Comment by bpasero** [comment]
Looks like we are down to one.
