### ISSUE TITLE
Make the space for tabs configurable (min, max, normal)

### ISSUE THREAD

**Issue by DavidBabel** [Microsoft/vscode#17775]
When i am using vscode with file icons activated on my 13' Macbook, i quickly get a problem with the number of tabs actually visibles.

<img width="1381" alt="capture d ecran 2016-12-23 14 16 08" src="https://cloud.githubusercontent.com/assets/5599375/21454811/bf9ae4f8-c91b-11e6-8f30-0e2d9bd52e54.png">

Especially for long file names in my project :

<img width="1084" alt="capture d ecran 2016-12-23 14 29 54" src="https://cloud.githubusercontent.com/assets/5599375/21454896/54b4b9d8-c91c-11e6-9ce6-4ffaa2c435e9.png">

This is annoying for angular projects with every file named "file.**component**.ts" or "file.**service**.ts".

What i suggest is two things : 

# **First**

it could be great to adding a config in settings.json to allow the display of tabs another potential way, here is a suggestion when the screen is not split :

<img width="1384" alt="capture d ecran 2016-12-23 14 11 01" src="https://cloud.githubusercontent.com/assets/5599375/21455614/f9e0b7e0-c921-11e6-85bf-4f9ce1725612.png">

By moving this bar just behind after the code of the title bar : 

<img width="1385" alt="capture d ecran 2016-12-23 14 06 02" src="https://cloud.githubusercontent.com/assets/5599375/21454835/e9d6ace8-c91b-11e6-8365-1df8791ddae8.png">

I could be awesome, and i'm not sur we can do thing like that with an extension.

# **Second**

It could be possible to add a filter on text size for tabs, or a way to limit the size with a [css ellipsis](https://css-tricks.com/snippets/css/truncate-string-with-ellipsis/).

Thanks to consider.

David B.

**Comment by bgashler1** [comment]
@DavidBabel if I understand your concern right, you want more tabs visible by either truncating the filenames or expanding the tab well's size.

I like your truncation idea.  Another editor does that.Since the differentiating and important part of a filename can vary in its position (i.e. whether it's in the beginning, middle or end), it seems we would want to use some smart behavior if we went with this approach.

Another idea, which I like less, is we could add a setting to allow more than one row of tabs in the tab well, or perhaps you could drag-resize the tab well to make room for another row of tabs.

**Comment by DavidBabel** [comment]
You get the idea.

**Comment by bgashler1** [comment]
Great.  Do you horizontally scroll the tab well much to see the hidden tabs?  Or are you using any other workarounds?  Just curious to see how you're currently using the tool in the absence of this feature.

**Comment by DavidBabel** [comment]
When i am on my Mac laptop i use to use the horizontal scroll indeed. 
But on Windows OS i mostly spam the ctrl-tab to find my file.

To be honest, when i'm working on angular2 projects, i hide completely the tab bar, letting only the current file name visible. That force me to use more efficient way to switch between files than searching it in the tabs. And that frustrate me less :) But it's a workaround.

**Comment by bpasero** [comment]
@DavidBabel if you agree I would close this one as duplicate of https://github.com/Microsoft/vscode/issues/15048
