### ISSUE TITLE
macOS: Gutter TestExplorer Ctrl-Click does not open contextual menu

### ISSUE THREAD

**Issue by Leland** [microsoft/vscode#177748]
Hiya! Originally filed in https://github.com/jest-community/vscode-jest/issues/1010, and was directed to recreate hither. 

![223150914-5717d348-2bc4-4ff4-ae5a-e13b76d7e316](https://user-images.githubusercontent.com/714017/226490701-fe3c2be3-4632-4d35-95f8-b4fd621b85d5.png)

Does this issue occur when all extensions are disabled?: N/A

- VS Code Version: Version: 1.76.2
- OS Version: macOS 13.2.1

Steps to Reproduce:

1. In a test file, <kbd>Ctrl</kbd>-click a test icon in the TestExplorer gutter while using e.g. the [vscode-jest extension](https://github.com/jest-community/vscode-jest).
2. Expect a contextual menu to appear (on macOS, <kbd>Ctrl</kbd>-click is equivalent to a right click)
3. Instead, a left click is interpreted

**Comment by connor4312** [comment]
Duplicates https://github.com/microsoft/vscode/issues/176492
