### ISSUE TITLE
Test: Scrollable notebook output

### ISSUE THREAD

**Issue by amunger** [microsoft/vscode#177719]
Refs: https://github.com/microsoft/vscode/issues/175778

- [x] anyOS @chrmarti 
- [x] anyOS @joyceerhl 
- [x] anyOS @Tyriar

Complexity: 5

Authors: @amunger, @rebornix 

[create issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23177719%0A%0A&assignees=amunger)

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23177719%0A%0A&assignees=amunger,rebornix)

---

1. Ensure `"notebook.output.scrolling": true`
2. Create a new notebook file
3. Run a few cells with large outputs, examples below
4. Play around with different combinations of related settings (might require reloading vs code): `notebook.output.textLineLimit`, `notebook.output.wordWrap`, `notebook.outputLineHeight`
5. ~~Search for terms within the output~~ different test item
6. Set `notebook.experimental.outputScrolling` to false, reload the notebook, then change it back to true (a link should appear to refresh each output)

Try on insiders.vscode.dev as well by either:
re-opening that same noteboook with output
or
Start up a jupyter server from a command prompt to provide kernels
    1. `python -m pip install jupyter`
    2. `python -m jupyter notebook --no-browser --NotebookApp.allow_origin=*`
    3. copy the URL that the previous command provides and
    4. open a notebook -> select kernel -> existing Jupyter Server -> paste the URL from step 3

### Two scrollable output elements for one cell

install pandas first `%pip install pandas` within a cell

```
import pandas as pd

for i in range(100):
    print(i)

data = {'A': [1, 2], 'B': [3, 4]}
df = pd.DataFrame(data)

# This line will generate a KeyError because column 'C' does not exist in the DataFrame
print(df['C'])
```

### Streaming output

the scroll bar should stick to the bottom unless it is scrolled up, also notice that the decorations change as it becomes a scrollable element.
```
import time
for i in range(200):
    time.sleep(.1)
    print(i)
```

### Longer than the hard limit of 5000 lines
```
for i in range(5005):
    print(i)
```

## Known issues

[clicking output that contains a link will scroll to that link](https://github.com/microsoft/vscode/issues/177720) 
[can't drag scrollbar while output is being updated](https://github.com/microsoft/vscode/issues/177721) 
[wrong cursor type when hovering scrollbar](https://github.com/microsoft/vscode/issues/177724) 
[Notebook output has no focus border when setting focus to it](https://github.com/microsoft/vscode/issues/174987)
[Notebook output scrollbar should fade away](https://github.com/microsoft/vscode/issues/174990)

**Comment by chrmarti** [comment]
The experimental setting keeps updating to `"notebook.output.scrolling"`. I guess that replaces it and it is good to test with that?

**Comment by Tyriar** [comment]
I could only install jupyter by changing `python` to `python3` as 2.7 is on my PATH, then I try to start it and get this:

<img width="634" alt="image" src="https://user-images.githubusercontent.com/2193314/226698308-591caf3e-83a6-4e15-8df9-f6956c2a2e9a.png">
