### ISSUE TITLE
Files don't open on double click

### ISSUE THREAD

**Issue by vijayaraghavanramanan** [Microsoft/vscode#17779]
- VSCode Version: Code 1.8.1 (ee428b0eead68bf0fb99ab5fdc4439be227b6281, 2016-12-19T14:49:23.350Z)
- OS Version: Windows_NT ia32 6.2.9200
- Extensions:

|Extension|Author|Version|
|---|---|---|

---

Steps to Reproduce:

1. Double click a php/css/js file 
2. Observe that the program opens with "untitled.text"

Although the program opens via right click - both folders and individual files and also using "Control-O",  double-clicking a file in Windows file-manager doesn't open a file and instead just opens "untitled.txt". This is useful to have if I need to edit a remote file using an FTP manager such as Filezilla.

**Comment by egamma** [comment]
This is the expected behaviour, we intentionally do not register VS Code as the default open handler. You as a user can configure this using `Open With>Choose Another App`. 

![image](https://cloud.githubusercontent.com/assets/172399/21457390/4653d55a-c92f-11e6-902d-cf2ab89fdcbf.png)

@joaomoreno pls correct me if needed.

**Comment by vijayaraghavanramanan** [comment]
This was not the case some versions back ... don't remember which. 

![vs code](https://cloud.githubusercontent.com/assets/13736892/21457993/3d19d24e-c959-11e6-9acb-a66f3b610875.png)


This is what I see. Why can I assign any editor to open it that way but not VS Code?

**Comment by joaomoreno** [comment]
Try to associate them with another app, and then to Code again.

**Comment by vlaloggia** [comment]
joaomoreno's suggestion solved the issue for me.

**Comment by tvjw03** [comment]
- not working Windows 10 Education ( or Windows 10 Home) 
-- setting to other editors and returning still opens Untitled-1 ( both right click, and double click) 
-- drag and drop onto shortcut works correctly, command line works correctly.
ideas?  also note that vscode wont allow default open of files in .zip ( doesn't even start code as untitled)

**Comment by joaomoreno** [comment]
@tvjw03 Can you reinstall Code, and then reset it?

**Comment by tvjw03** [comment]
Perhaps something happened to the first attempt at Feb update. Searched for updates and it came up with the same one again. Installed it ( still nothing) then restarted the PC and it works again.
