### ISSUE TITLE
wrong cursor type when hovering a scrollbar in the scrollable notebook output

### ISSUE THREAD

**Issue by amunger** [microsoft/vscode#177724]
create a notebook with a cell that produces long output:

```
for i in range(1000):
    print(i)
```

hover over the scrollbar within the output, it should be the pointer, but it is text

**Comment by rebornix** [comment]
https://github.com/microsoft/vscode/blob/a11d69c12959cd9ef1f1782bd0d056d7afa78854/extensions/notebook-renderers/src/index.ts#L339-L340

The scrollbar inherits the cursor style from this container and a `important` override in `::-webkit-scrollbar` doesn't seem to work.
