### ISSUE TITLE
Focus sticky scroll is not preserved when sticky lines disappear and reapper

### ISSUE THREAD

**Issue by dbaeumer** [microsoft/vscode#177770]
Testing #177642

- have a couple of lines in sticky scroll
- Focus sticky scroll
- scroll inside the file to a place that sticky scroll lines disappear
- scroll to a place that has sticky scroll lines again

Observe: focus is lost. I would have expected that focus is kept.

**Comment by dbaeumer** [comment]
I am actually reopening it since I think the behavior is not good when scrolling using the scroll bar / minimap

**Comment by dbaeumer** [comment]
Do the following:

- focus sticky scroll
- use the minimap to scroll to the top of the file whithout releasing the mouse
- Observe: sticky scroll disappears and focus is gone
- Scroll into the file again 
- Observe: sticky scroll apprears without focus. 

I would have expected in this case that the focus is preserved since I never released the mouse button.

**Comment by aiday-mar** [comment]
For the person who will be doing the verification, a regression has been found relating to the incorrect focusing of the sticky scroll which has already been fixed in the following PR: https://github.com/microsoft/vscode/pull/178009. Please test once the other PR is released on insiders.
