### ISSUE TITLE
editor/lineNumber/context: pass URI as a string to extension command

### ISSUE THREAD

**Issue by ulugbekna** [microsoft/vscode#177782]
Testing #177521

Since URI can be easily de/serialized, it would be great if the command would get the URI as a string rather than an object. The command would be friendlier to being bound by keybindings with specific arguments, e.g., in `keybindings.json`: 

```
[

{ "key": "tab", "command": "myLineNumberContextCommand", "args": { "lineNumber": 1, "uri": "..." } } 

]
```

**Comment by joyceerhl** [comment]
@ulugbekna that is doable but seems a little unusual, I think for command args we usually pass an actual URI object, at least that is the context that we pass for other context menus AFAICT. Do you have a use case for copying links for a specific file?

**Comment by ulugbekna** [comment]
I don't have a specific use-case in mind, just a suggestion. Let's close if this decision just follows the suite as other similar commands. Thanks! :-)
