### ISSUE TITLE
Sticky scroll lines are clipped

### ISSUE THREAD

**Issue by dbaeumer** [microsoft/vscode#177771]
Testing #177642

Not sure how I got there but I had focus on sticky scroll and scrolled inside the file

<img width="579" alt="image" src="https://user-images.githubusercontent.com/1931590/226550354-b6dd1194-7ee1-4486-a62d-d6fb06d8439b.png">

**Comment by aiday-mar** [comment]
I have not seen this issue since. I will close this issue optimistically. Feel free to reopen it, if you see it again
