### ISSUE TITLE
$TM_FILENAME_BASE does not pick up file rename changes

### ISSUE THREAD

**Issue by MartinP-C** [microsoft/vscode#177796]
Type: <b>Bug</b>

After renaming a file, the filename variables in snippets still use the old filename.
- Create a new file such as "test.tsx"
- Rename the file to "Test.tsx"
- Insert snippet using a filename variable
- Old filename "test.tsx" is used

The snippet in the example uses `TM_FILENAME_BASE` but this also occurs with `TM_FILENAME`.
This bug **does not** reproduce on WSL (Remote OS version: Linux x64 5.10.102.1-microsoft-standard-WSL2)

![Recording 2023-03-21 at 11 57 00](https://user-images.githubusercontent.com/8778016/226600215-8e92401b-5943-498c-9223-aca259af3ee0.gif)

VS Code version: Code 1.76.2 (ee2b180d582a7f601fa6ecfdad8d9fd269ab1884, 2023-03-14T17:55:54.936Z)
OS version: Windows_NT x64 10.0.19045
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz (8 x 1805)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.73GB (19.50GB free)|
|Process Argv|-n|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by python-nerd-3** [comment]
I had this same bug happen to me. I accidentally capitalized my file names wrong and had to rename it to different text, push, rename it back, and push again.
