### ISSUE TITLE
Improvements to terminal hover

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#177735]
Refs: #170580, #177078 

- [ ] macOS @eleanorjboyd
- [x] linux @rzhao271
- [x] windows @sandy081

Complexity: 3

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23177735%0A%0A&assignees=Tyriar)

---

There have been several improvements to the terminal hover, please test each of the following. UX feedback is welcome.

- The "stale environment" indicator no longer lists the actual environment changes which used to be a wall of text, but instead lists the extensions that want to contribute. The extension will eventually contribute a description that we will put next to the extension ID. You can test this by opening a terminal, typing in it and changing auto attach in the `Toggle Auto Attach` command
  <img width="507" alt="image" src="https://user-images.githubusercontent.com/2193314/226480945-e984fc60-6af4-4685-b29a-4630ded8140a.png">
  The relaunch terminal action should still work
  ![image](https://user-images.githubusercontent.com/2193314/226481759-3e634be2-9c5b-41cd-ada1-c00ba5a80bb5.png)
- There is a new environment changes active message, this includes an action in the hover's "status bar" that allows displaying the changes
  <img width="587" alt="image" src="https://user-images.githubusercontent.com/2193314/226481048-e80a8140-fe6e-4572-bb15-bd232e49feee.png">
- You can see the exact process ID of the shell and the command line used:
  <img width="587" alt="image" src="https://user-images.githubusercontent.com/2193314/226481144-fbb6f020-4961-4d85-938e-c94bb64b9f02.png">
- The hover is keyboard accessible via `ctrl+k, ctrl+i` (or `cmd+k, cmd+i`) when either the terminal or the terminal tab is focused

**Comment by Tyriar** [comment]
@eleanorjboyd oh sorry, on Mac it's special because cmd+k is used for clear so no chords work. Try enabling screen reader mode to get the key binding working.

**Comment by eleanorjboyd** [comment]
yes, I have that in the status bar- I used `toggle screen reader accessibility mode` to turn it on but this was the only step I took. Do I need to do anything else?
