### ISSUE TITLE
Improve notebook.output.fontFamily wording

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#177844]
Testing #177719

This doesn't read well to me:

<img width="643" alt="image" src="https://user-images.githubusercontent.com/2193314/226688410-67f52c22-ea59-4d15-8b9f-92a33b1223b7.png">

Suggestion:

> The font family of the output text within notebook cells. When unset, #editor.fontFamily# is used.

**Comment by Tyriar** [comment]
Similar improvements could be made to the other settings. The "for...for" in particular:

<img width="265" alt="image" src="https://user-images.githubusercontent.com/2193314/226688952-ffdba3e5-03a5-470a-8416-7daa1eb3c817.png">

**Comment by rebornix** [comment]
Thanks for the feedback, the suggestion looks good.
