### ISSUE TITLE
Unnecessary space between badge and action

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#177809]
Testing #177709

<img width="452" alt="Screenshot 2023-03-21 at 13 54 59" src="https://user-images.githubusercontent.com/10746682/226612618-072f9d5e-c110-4e20-ae0b-6a45ace01d0a.png">

**Comment by andreamah** [comment]
<img width="239" alt="image" src="https://user-images.githubusercontent.com/31675041/226975118-181e1364-9a77-4809-ad19-e047541c1844.png">
This was preexisting, and I believe it's this way so that people don't mistaken the file decoration as a button (it's in its own grouping).
