### ISSUE TITLE
Arrow key navigation always targets editor scroll position

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode#177800]
Testing #177719

Up / down, go to top / bottom always targets the editor's scroll position, not the cell's scroll position. (Related: https://github.com/microsoft/vscode/issues/177792)

**Comment by Tyriar** [comment]
I also see this, page up/down, ctrl+home/end act strangely

**Comment by rebornix** [comment]
We didn't update when clauses for arrow keys and page down/ups so when the focus is inside the scrollable output, it scrolls both the output and the editor.
