### ISSUE TITLE
Action bars should use the custom hover

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#177825]
![image](https://user-images.githubusercontent.com/2193314/226646250-c27d9e27-3119-4d43-9e5c-165ec7c34d99.png)

<img width="150" alt="image" src="https://user-images.githubusercontent.com/2193314/226646059-40d10035-ed74-48bf-bd2c-9116803c7836.png">

<img width="684" alt="image" src="https://user-images.githubusercontent.com/2193314/226646092-b55f9cc9-1ed2-47a7-9102-61e98f5dc193.png">

etc.

**Comment by Tyriar** [comment]
cc @TylerLeonhardt who also looked into this

**Comment by bpasero** [comment]
That happened.
