### ISSUE TITLE
Accessible buffer feature can trap focus and prevent tab navigation from working

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#177886]
Not sure how to get into this state but pretty sure I've seen it before. The gif shows shift+tab and typing repeatedly which:

1. Shift+tab: Focuses the accessible buffer :bug: but does not show it
2. Shift+tab: 🐛 Focuses the terminal again
3. Repeat

![Recording 2023-03-21 at 13 14 54](https://user-images.githubusercontent.com/2193314/226730223-11f53d04-84ec-4050-892a-733d2a58482d.gif)

This is the focused element when the accessible buffer is focused:

<img width="1443" alt="image" src="https://user-images.githubusercontent.com/2193314/226730621-f08a4856-577f-44ee-b74b-edbeff4fc33f.png">

**Comment by meganrogge** [comment]
You don't have tab moves focus mode on in that gif, so it's expected imo that focus is trapped there
