### ISSUE TITLE
EveryThing Is Good Except Live Preview

### ISSUE THREAD

**Issue by suryanu** [Microsoft/vscode#17788]
- VSCode Version: Code 1.8.1 (ee428b0eead68bf0fb99ab5fdc4439be227b6281, 2016-12-19T14:49:23.350Z)
- OS Version: Windows_NT ia32 10.0.14986
- Extensions:

|Extension|Author|Version|
|---|---|---|
|vscode-livescript-preview|eheitherd|1.0.1|
|mithril-emmet|FallenMax|0.5.1|
|live-html-previewer|hdg|0.0.1|
|vscode-angular2-emmet|jakethashi|1.0.9|
|Angular2|johnpapa|1.0.2|
|html5-boilerplate|sidthesloth|1.0.1|
|mixliveserver|varomix|0.0.1|
|JavaScriptSnippets|xabikos|1.2.0|

---

Steps to Reproduce:
Not a issue But a request.
1.Need to Add a little server for live preview code in a browser for web Developers.

**Comment by egamma** [comment]
Duplicates #12080

**Comment by waderyan** [comment]
Hi @suryanu - I am doing a short user research study on this issue. If you have time tomorrow or Tuesday can you sign up? https://calendly.com/waderyan/try-vscode
