### ISSUE TITLE
Links in cell output aren't working

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#177854]
Testing #177719

Running this:

```py
%pip install pandas

import pandas as pd

for i in range(100):
    print(i)

data = {'A': [1, 2], 'B': [3, 4]}
df = pd.DataFrame(data)

# This line will generate a KeyError because column 'C' does not exist in the DataFrame
print(df['C'])
```

Resulted in:

<img width="938" alt="image" src="https://user-images.githubusercontent.com/2193314/226697331-43ae0389-6060-44b9-9786-4112a2287908.png">

None of these links work:

`[C:\Users\Daniel\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\python.exe](file:///C:/Users/Daniel/AppData/Local/Microsoft/WindowsApps/PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0/python.exe)`

<img width="436" alt="image" src="https://user-images.githubusercontent.com/2193314/226697456-99e8de5b-a4cd-4e2a-8dc4-322de49539a3.png">

`[c:\users\daniel\appdata\local\packages\pythonsoftwarefoundation.python.3.9_qbz5n2kfra8p0\localcache\local-packages\python39\site-packages](file:///C:/users/daniel/appdata/local/packages/pythonsoftwarefoundation.python.3.9_qbz5n2kfra8p0/localcache/local-packages/python39/site-packages)`

<img width="790" alt="image" src="https://user-images.githubusercontent.com/2193314/226697418-3622c605-9691-4ecc-8820-4e4afeb1a064.png">

`[~\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\pandas\core\frame.py:3807](https://file+.vscode-resource.vscode-cdn.net/c%3A/Github/Tyriar/xterm.js/~/AppData/Local/Packages/PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0/LocalCache/local-packages/Python39/site-packages/pandas/core/frame.py:3807)`:

<img width="451" alt="image" src="https://user-images.githubusercontent.com/2193314/226697510-4061916c-cca1-4cc0-9430-91f639be58e4.png">

**Comment by rebornix** [comment]
We will track this in https://github.com/microsoft/vscode/issues/236113
