### ISSUE TITLE
Jupyter crashes EH

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#177814]
Testing #177646

1. Use exploration build on macOS
2. Install Jupyter Notebook extension (not pre-release)
3. Create a new Jupyter notebook with the following content `print("hello there")`
4. Run the Notebook -> EH crash in dev tools

```
[Extension Host] Starting WebSocket: RAW/api/kernels/1ecaf549-4d63-4748-be6d-53b9e4beb348 (at console.<anonymous> (/private/var/folders/2l/y9q26fj16v77c_sq0mdrpv6w0000gn/T/AppTranslocation/8576F41C-FEF6-4D2E-9BF8-37472F95B41A/d/Visual Studio Code - Exploration.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:98:155800))
localProcessExtensionHost.ts:293 Extension Host
abstractExtensionService.ts:604 Extension host (LocalProcess) terminated unexpectedly. Code: 11, Signal: unknown
mb @ abstractExtensionService.ts:604
mb @ nativeExtensionService.ts:163
lb @ abstractExtensionService.ts:596
(anonymous) @ abstractExtensionService.ts:574
invoke @ event.ts:723
deliver @ event.ts:936
fire @ event.ts:892
M @ localProcessExtensionHost.ts:509
(anonymous) @ localProcessExtensionHost.ts:303
invoke @ event.ts:723
deliver @ event.ts:936
fire @ event.ts:892
_ @ ipc.ts:672
t @ ipc.ts:740
s @ ipc.ts:729
(anonymous) @ ipc.ts:549
invoke @ event.ts:723
deliver @ event.ts:936
fire @ event.ts:892
te @ event.ts:457
emit @ VM227 sandbox_bundle:2
onMessage @ VM227 sandbox_bundle:2
log.ts:441   ERR Extension host (LocalProcess) terminated unexpectedly. No extensions were activated.
log.ts:421  INFO Automatically restarting the extension host.
```

**Comment by deepak1556** [comment]
The older version of Zeromq does not handle the error thrown by the NAPI https://github.com/nodejs/node/blob/f5eedf480ce9abed019deed3a44edb647c722d5b/src/node_api.cc#L986 that comes with Electron 22 leading to the above crash.

One option is we revert the NAPI error patch in Electron and instead rely on the allocator patch, downside is that newer native modules built for Electron >= 22 should not rely on runtime detection of this error. Seems like something we can document.

**Comment by bpasero** [comment]
Quick thought on this: we should not update to Electron 22 and have a known EH crash from a native module, irrespective if that module could do it better by reading our docs. In other words, we should update to Electron 22 only if we can avoid a crash of the extension host.

**Comment by deepak1556** [comment]
We cannot avoid all cases of crashes that comes with V8 sandbox, for ex: we have no way forward for stack allocated array buffer regions, so we would need to live with certain cases of crashes. But for this case, we can improve the patch to only throw an error if the data is not inside the sandbox, I will update the patch.

**Comment by deepak1556** [comment]
Addressed in https://github.com/microsoft/vscode/pull/177600/commits/05cafd67cf6a466f90b7c559f489242893e85338

**Comment by deepak1556** [comment]
Steps for Verifications:

* Use exploration build based on Electron `v22.4.3`
* Install Jupyter Notebook extension (not pre-release)
* Create a new Jupyter notebook with the following content print("hello there")
* Extension host should not crash

**Comment by isidorn** [comment]
Works great -> verified

**Comment by deepak1556** [comment]
@isidorn did you use https://builds.code.visualstudio.com/builds/exploration?commit=377200797bdf4ec624bfc90c9bcd8439861c9c42 for testing, just want to make sure since I haven't released `v22.4.3` but it is available on the builds page.

**Comment by isidorn** [comment]
Correct. I used that version.

**Comment by deepak1556** [comment]
Great, thanks!
