### ISSUE TITLE
Could not read project.json, please try again.

### ISSUE THREAD

**Issue by wellrootedmedia** [Microsoft/vscode#17783]
- VSCode Version: 1.8.1 (1.8.1)
- OS Version: 10.12.2

Steps to Reproduce (on mac):

1. cmd + p
2. &gt; nuget: add new package
3. type "mongo" and select "mongocsharpdriver" 
4. select the version
5. error displays "Could not read project.json, please try again."

I do have a "project.json" file in the project too.

screenshots:
project.json - https://imgur.com/a/QC5P9
video of error - https://youtu.be/f2MtbW0GySo

**Comment by wellrootedmedia** [comment]
I found this solution, http://stackoverflow.com/questions/40558718/how-to-access-nuget-repository-from-net-core-using-visual-studio-code/40558979#answer-40558979 but doesn't seem complete...

**Comment by egamma** [comment]
The issue is related to the C# extension, moving the issue to this repository.

**Comment by egamma** [comment]
This issue was moved to OmniSharp/omnisharp-vscode#1087

**Comment by DustinCampbell** [comment]
The command "nuget: add nuget package" doesn't come from the C# extension. What extensions do you have installed? It's likely that the error is coming from this extension: https://marketplace.visualstudio.com/items?itemName=ksubedi.net-core-project-manager.
