### ISSUE TITLE
match not working in when clause

### ISSUE THREAD

**Issue by eleanorjboyd** [microsoft/vscode#177830]
Testing #177738

Given
```
{
          "command": "ctxkey-extension.helloWorld3",
          "when": "!(editorLangId =~ /json/)"
        },
```

the expected behavior is to not see present 3 on a `.py` file but this still appeared.

<img width="1757" alt="Screenshot 2023-03-21 at 8 25 01 AM" src="https://user-images.githubusercontent.com/26030610/226656831-580bf3a4-1cfd-422e-bfe5-03a32772dd5a.png">

**Comment by ulugbekna** [comment]
Oh, I'm really sorry, the instruction should've said "it shows in anything that's NOT json - so this works as intended.
