### ISSUE TITLE
Occurrences highlighting broken in JS/TS on windows

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#177823]
![Code_-_Insiders_5dwZBuY350](https://user-images.githubusercontent.com/2193314/226643185-47d2de3a-ae1d-4dcd-93d5-9f2571a2082b.gif)

`_tooltip` should be highlighted:

![image](https://user-images.githubusercontent.com/2193314/226643244-408b8ecf-7b60-4c89-8024-dc475417f061.png)

Version: 1.77.0-insider (user setup)
Commit: 833ac685084e2028b09753392b82c641c7025bbc
Date: 2023-03-21T05:22:13.879Z
Electron: 19.1.11
Chromium: 102.0.5005.196
Node.js: 16.14.2
V8: 10.2.154.26-electron.0
OS: Windows_NT x64 10.0.22621
Sandboxed: Yes

**Comment by Tyriar** [comment]
cc @mjbvz for TS

**Comment by alexdima** [comment]
I cannot reproduce, semantic occurrences seem to work fine for me. @hediet can you reproduce running from source?

![image](https://user-images.githubusercontent.com/5047891/226651664-44fadedd-d13f-4a6c-8151-2f74fb070a0b.png)

**Comment by Tyriar** [comment]
I can repro out of sources as well

**Comment by hediet** [comment]
Looks like a windows specific issue:

![image](https://user-images.githubusercontent.com/2931520/226680707-3175f998-ce83-435d-854a-07333417e403.png)

![image](https://user-images.githubusercontent.com/2931520/226680865-028ca3dd-d63f-47c1-a28c-65296f0c4dde.png)

(in TypeScriptDocumentHighlightProvider.provideDocumentHighlights)

**Comment by mjbvz** [comment]
Hm I don't think this was caused by cdbe59519b9c6e1c8283cfcef4ae810d94312fba. Instead I suspect it was 54921d717321771911c136397342a65eda2673df
