### ISSUE TITLE
Navigateto fails to activate

### ISSUE THREAD

**Issue by rzhao271** [microsoft/vscode#177889]
Testing #177645

Activating extension 'appresso.navigateto' failed: The module '/Users/raymondzhao/.vscode-exploration/extensions/appresso.navigateto-1.0.1/node_modules/tree-sitter-python/build/Release/tree_sitter_python_binding.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 75. This version of Node.js requires
NODE_MODULE_VERSION 110. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`)..

**Comment by deepak1556** [comment]
Modules that need recompilation is not in the scope.
