### ISSUE TITLE
Code output is not decorated

### ISSUE THREAD

**Issue by lramos15** [microsoft/vscode#177828]
Testing #177709

1. Have a code cell with `help(range)` in it.
2. Search for `range`
3. 🐛 Clicking the results in the rendered output doesn't render decorations making it hard to find the matches

**Comment by lramos15** [comment]
I toggled the filter to rendered markdown and then back to source and that caused decorations to appear. Odd.

**Comment by andreamah** [comment]
Yes, I think that a last-minute change that I merged ended up introducing a race condition with highlights. Will need to fix.

**Comment by andreamah** [comment]
Fixed by https://github.com/microsoft/vscode/pull/177911
