### ISSUE TITLE
Insert key during screen reader not aligned correctly

### ISSUE THREAD

**Issue by eleanorjboyd** [microsoft/vscode#177855]
Testing #177735

When testing the above item I used cmd+i and it brought up this box with the hover. If I did it quickly the hover ended up floating in the terminal and not going away when other lines crossed over it.

<img width="898" alt="Screenshot 2023-03-21 at 10 50 32 AM" src="https://user-images.githubusercontent.com/26030610/226698666-1a5a32e1-8985-4572-b85f-1338a3bdfc75.png">

**Comment by meganrogge** [comment]
can you still reproduce this @eleanorjboyd ?

**Comment by eleanorjboyd** [comment]
so I have enabled screen reader and then tried all 4 key bindings and none of them bring up the hover still. When I do "cmd+i" it jumps into the editor from the terminal and opens inline chat.

**Comment by meganrogge** [comment]
oh, the keybinding for this is `cmd+k+cmd+i`
