### ISSUE TITLE
Variables specified in "environment" in launch.json is not applied for debugging

### ISSUE THREAD

**Issue by sbobko** [microsoft/vscode#177857]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.76.1
- OS Version: Ubuntu 22.04

Steps to Reproduce:

1. Сreate a launch.json containing the setting of environment variables
2. Start debugging
Expected: Created terminal contains the specified environment variables
Actual: does not contain

My launch.json:
`{
    "configurations": [
        
        {
            "comments": [
                "Full launch.json configuration details can be found here:",
                "https://code.visualstudio.com/docs/cpp/launch-json-reference"
            ],
            "name": "(gdb-oneapi) array-transform Launch",
            "type": "cppdbg",
            "request": "launch",
            "preLaunchTask": "",
            "postDebugTask": "",
            "program": "${workspaceFolder}/src/array-transform",
            "args": [
                "gpu"
            ],
            "stopAtEntry": false,
            "cwd": "${workspaceFolder}",
            "environment": [
                {
                    "name": "ZET_ENABLE_PROGRAM_DEBUGGING",
                    "value": "1"
                },
                {
                    "name": "IGC_EnableGTLocationDebugging",
                    "value": "1"
                },
                {
                    "name": "SYCL_DEVICE_FILTER",
                    "value": "level_zero"
                }
            ],
            "externalConsole": false,
            "MIMode": "gdb",
            "miDebuggerPath": "gdb-oneapi",
            "setupCommands": [
                {
                    "description": "Enable pretty-printing for gdb",
                    "text": "-enable-pretty-printing",
                    "ignoreFailures": true
                },
                {
                    "description": "Disable target async",
                    "text": "set target-async off",
                    "ignoreFailures": true
                }
            ]
        }
    ]
}`

**Comment by roblourens** [comment]
Please file an issue on the debug extension that you're using
