### ISSUE TITLE
Keyword exception is not highlighted for F# files

### ISSUE THREAD

**Issue by hanpari** [Microsoft/vscode#17784]
- VSCode Version:
1.8.1
- OS Version:
Win10
Steps to Reproduce:

1. open *.fs or *.fsx
2. write 
    exception MyError of string

[see here](https://docs.microsoft.com/cs-cz/dotnet/articles/fsharp/language-reference/exception-handling/exception-types)

Type exception should be highlighted as in reference page

**Comment by egamma** [comment]
This issue was moved to ionide/ionide-atom-fsharp#255

**Comment by egamma** [comment]
We are using the grammar from https://github.com/ionide/ionide-atom-fsharp. Moving the issue to this repository.

CC @aeschli
