### ISSUE TITLE
Cannot preview media files in remote azure repo

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#177819]
Testing #177535

This doesn't work for me when I click the file from the explorer or in the markdown preview

![Screenshot 2023-03-21 at 7 28 16 AM](https://user-images.githubusercontent.com/29464607/226637718-f7d6716e-f8ee-4898-b523-38184d7530f5.png)

https://user-images.githubusercontent.com/29464607/226638076-a5136d63-4508-48b8-bbcf-9f04ff712cbc.mov

**Comment by joyceerhl** [comment]
The mp4 link needs to be `video` tag syntax, but for the gif and png I cannot repro, are you on the latest pre-release of Azure Repos? If you right click on the file and select reopen with text editor what do you see?

**Comment by meganrogge** [comment]
Here's the gif if you want to see if it reproduces for you with this

![Recording 2023-03-21 at 07 12 20](https://user-images.githubusercontent.com/29464607/226648868-e1858fdd-bc4b-4a5c-8ba4-8263945021f6.gif)

**Comment by joyceerhl** [comment]
@meganrogge that is the pre-release of Remote Repos, can you also provide the version number of the Azure Repos extension please?

**Comment by joyceerhl** [comment]
Hm that gif works exactly as expected for me (both opening the file directly and as a referenced artifact in markdown preview in an Azure Repos repo). I saved it under filepaths with and without spaces in the path and it works as expected both ways, so I'm not sure what's going on, are there any errors in the logs?

Not that it should matter, but it looks like you're editing a repo that doesn't have LFS tracking enabled. Were you able to confirm that committing LFS files works in Azure Repos for a repo that does have LFS tracking set up?

**Comment by meganrogge** [comment]
How do I enable LFS tracking for that repo or check whether that's enabled?

![Screenshot 2023-03-21 at 8 55 49 AM](https://user-images.githubusercontent.com/29464607/226666222-43ee21f1-de98-43c9-83c5-d5aec6a5eb0c.png)

**Comment by meganrogge** [comment]
I set up my own Azure org, imported the vscode-docs repo, opened the remote repository, committed LFS-tracked files, and that worked
