### ISSUE TITLE
JSON validation not very obvious

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#177801]
Testing #177722

* edit keybindings.json
* have config below (lacks args)
* 😕 the validation warning is very subtle, why not squiggle the whole object?

```
  {
    "key": "cmd+k 3",
    "command": "runCommands",
  }
```

<img width="258" alt="Screenshot 2023-03-21 at 13 34 15" src="https://user-images.githubusercontent.com/1794099/226607327-46f34f9e-0bfa-48f5-87db-2f1bb6cdfa04.png">

**Comment by ulugbekna** [comment]
AFAIU, the range for the diagnostic is reported by vscode-json-languageservice. 

I would also argue that the missing field in an object should be reported for the object - ie highlight the object here: 

<img width="341" alt="image" src="https://user-images.githubusercontent.com/16353531/226623589-c09ba83f-40f4-4820-99f9-d15fc36edd13.png">

cc @aeschli 


----


Meanwhile, I would like to show off the linting rule we added that hints a user who wants to bind several commands with `"command": [ ... ]`:

<img width="1391" alt="image" src="https://user-images.githubusercontent.com/16353531/226628070-9af0eee7-e033-4743-9fe0-2f3ac506d1b5.png">

And the completion & linting working for commands within `runCommands`'s "args" 

<img width="908" alt="image" src="https://user-images.githubusercontent.com/16353531/226628350-c0103562-8f66-4dba-99e5-cc3d933f40ce.png">
