### ISSUE TITLE
Link to rerender output after enabling scrollable output is weird

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode#177836]
Testing #177719

After enabling scrollable output and reopening a notebook, I would expect all the notebook cell outputs to automatically rerender as scrollable rather than requiring me to manually go through and click to refresh each individual output.

**Comment by rebornix** [comment]
Maybe we should reset all streaming/text outputs when the scrollable output setting changes like what you did now on clicking the refresh command @amunger

**Comment by rebornix** [comment]
Sharing the same root cause as https://github.com/microsoft/vscode/issues/177803 .
