### ISSUE TITLE
Editor focus lost after selecting from Sticky Scroll

### ISSUE THREAD

**Issue by gregvanl** [microsoft/vscode#177874]
Testing #177642

1. In a Markdown file with headers up to H3, enable Sticky Scroll and scroll up and down in the editor.
2. Focus Stick Scroll
3. Select a header leve and press `Enter`.

Try to scroll up and down with the arrow keys. Unclear where the cursor focus is. 
Try typing, the editor doesn't have focus

Focus should should probably go to the editor on the selected header. That is the behavior with breadcrumb navigation

**Comment by gregvanl** [comment]
This is the general behavior of Sticky Scroll and also reproduces if you select a level via the mouse

**Comment by bhavyaus** [comment]
Verified on OSS
