### ISSUE TITLE
Hover: Can break editor keyboard navigation

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#177806]
Testing #177651

1. Press <kbd>Cmd K, Cmd I</kbd> twice on a symbol which has a hover.
2. Press <kbd>Escape</kbd>
3. Press <kbd>UpArrow</kbd> or <kbd>DownArrow</kbd>

🐛 Nothing happens, since focus didn't return to the editor after pressing <kbd>Escape</kbd>.

**Comment by bhavyaus** [comment]
Verified on OSS
