### ISSUE TITLE
Recommendation source not showing for Notepad++ extension

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#177891]
Testing #177675

I see the recommendation source when I hover Kubernetes:

![image](https://user-images.githubusercontent.com/2193314/226738293-4693aeb4-a072-47d4-9c4f-3ae020c9cc08.png)

Not when I hover the Notepad++ one though:

![image](https://user-images.githubusercontent.com/2193314/226738403-3ae91579-aa0d-4b86-b497-ac82bf7e150f.png)

I believe it's doing this because it's installed so it should say that.

**Comment by isidorn** [comment]
Long term I think we should get rid of the reason. Since recommendations will be ML model powered and the nit is not clear why each recommendation is shown.

**Comment by Tyriar** [comment]
Why would it only recommend the notepad++ keymap though? Seems pretty random.

@isidorn transparency is good, why not add a generic ML source for the future ones?

**Comment by isidorn** [comment]
I am not sure if the ML model supports that.
@digitarald might you know?

**Comment by Tyriar** [comment]
@isidorn as in something like: "This extension was recommended by an ML model analysing your workspace"

**Comment by isidorn** [comment]
@Tyriar too general imho, I am not sure if that brings user value. Also there are other signal the model uses apart from workspace so not sure how long that description would be?
Also I am not sure how many other products show why they recommend something?

**Comment by Tyriar** [comment]
Personally I appreciate being told why something was recommended, this helps avoid users being paranoid about what data we're accessing to make the recommendation.

> Also I am not sure how many other products show why they recommend something?

Nothing stopping us from being more transparent than other products

**Comment by digitarald** [comment]
ML models usually need extra work to be "explainable", so this isn't easy.

With the current systems, those recommendations can all have a source.
