### ISSUE TITLE
Recommended extensions should only show once per window load per extension

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#177897]
Testing #177675

Testing the "File content based recommendations", the following flow can happen

1. Open a file
2. See a recommendation and dismiss it
3. Do other work, close the file or whatever
4. Open the file again
5. See the same recommendation a second time

I know there's the ⚙️ option to "Don't Show Again", but imo we should be less noisy about it by default, only recommending once per file or per extension.

**Comment by sandy081** [comment]
> but imo we should be less noisy about it by default, only recommending once per file or per extension.

We do this. Can you please provide concrete steps to reproduce, like what kind of file you opened and what contents it has?

**Comment by connor4312** [comment]
This was after doing the following steps:

Test following recommendation is shown based on the content of the file
 - Start with fresh user data dir or fresh profile
 - Install Python extension and Uninstall Jupyter Extension because it is included in Python extension.
 - Open a python file with following contents
```py
print("HI")
#%%
print("cell")
#%%
print("something else")
```
