### ISSUE TITLE
Opening a devcontainer.json file recommends the JSON with comments extension

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#177894]
Testing #177675

This should be dev containers, not json with comments:

<img width="556" alt="image" src="https://user-images.githubusercontent.com/2193314/226740600-99f511ff-3c60-4eef-a499-0f11ca4e13f7.png">

Show Recommendations shows:

<img width="217" alt="image" src="https://user-images.githubusercontent.com/2193314/226740682-cb6f388c-4b19-48fd-9174-aab3f3cfeee2.png">

Version: 1.77.0-insider (user setup)
Commit: 833ac685084e2028b09753392b82c641c7025bbc
Date: 2023-03-21T05:22:13.879Z
Electron: 19.1.11
Chromium: 102.0.5005.196
Node.js: 16.14.2
V8: 10.2.154.26-electron.0
OS: Windows_NT x64 10.0.22621
Sandboxed: Yes

**Comment by connor4312** [comment]
I agree this is pretty unexpected
