### ISSUE TITLE
Add a close button to conditional breakpoint UI

### ISSUE THREAD

**Issue by mohsen1** [Microsoft/vscode#17782]
- VSCode Version: 1.8.1
- OS Version: macOS

Steps to Reproduce:

<img width="979" alt="screen shot 2016-12-23 at 9 38 47 am" src="https://cloud.githubusercontent.com/assets/543633/21459509/a28fd1f2-c8f3-11e6-9de8-0d9223427af8.png">

After opening add conditional breakpoint dialog, the only way to close it is to focus in the text input and hit escape key. 

It would be nice if there  was a little x button for closing it.

**Comment by isidorn** [comment]
You do not have to focus the input, hitting escape anywhere will just close it
