### ISSUE TITLE
Remote Repositories doesn't allow tracking ignored files in git

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#177866]
Testing #177534

There is this kind of dumb edge case in git where you are allowed to have a file to gitignore but add it anyway. If it's tracked in git, then it should show changes even if it matches a pattern in gitignore. This works in a normal local folder git repo, but not in Remote Repositories

Example:

<img width="198" alt="image" src="https://user-images.githubusercontent.com/323878/226708351-1de828af-efe3-44bb-9c01-19de77f3ad6d.png">

<img width="520" alt="image" src="https://user-images.githubusercontent.com/323878/226708447-7a1ef925-05d8-402e-b103-5eddd1ca11f1.png">

<img width="197" alt="image" src="https://user-images.githubusercontent.com/323878/226708397-acfff75c-8aca-4013-86ed-0a8007eb2616.png">

---

Then in Remote Repositories

<img width="292" alt="image" src="https://user-images.githubusercontent.com/323878/226708715-8eef28ab-938f-4db8-adef-3c9b7e288ab7.png">
<img width="300" alt="image" src="https://user-images.githubusercontent.com/323878/226708747-74c67637-1eb3-42f0-90af-f5d7cb9cda86.png">
<img width="250" alt="image" src="https://user-images.githubusercontent.com/323878/226708775-a22cc5a9-973f-4134-a52d-030e53e20c5b.png">

**Comment by joyceerhl** [comment]
Maybe I need an 'Untrack File' action in the explorer context menu. I'll wait for additional feedback before I go this route though, since the original motivation for implementing gitignore support in web was to hide gitignored files (e.g. build artifacts for the MakeCode extension) from the SCM view), so I think this use case isn't very common at the moment.

**Comment by joyceerhl** [comment]
Closing as out of scope since nobody else has requested this functionality
