### ISSUE TITLE
Cell in edit mode does not match

### ISSUE THREAD

**Issue by karrtikr** [microsoft/vscode#177893]
Testing #177709

Not sure whether it's expected but the third cell in this picture which is currently being edited:

![image](https://user-images.githubusercontent.com/13199757/226739948-6314bc75-20dd-45ca-9790-85daf837298c.png)

is not reflected in the search.

**Comment by andreamah** [comment]
This might have been a byproduct of a fix for https://github.com/microsoft/vscode/issues/177536, which has been reverted. Does this still happen in the latest insiders?

**Comment by karrtikr** [comment]
Nope it doesn't seem to happen when using "Markdown Source":

![image](https://user-images.githubusercontent.com/13199757/227324353-35a8a0fe-321c-44f5-8589-f5362eef31da.png)

But it happens when using "Rendered Markdown", but I guess that's expected as editable cell is not rendered yet?

**Comment by andreamah** [comment]
Yes, `Rendered Markdown` only searches cells that are in `preview` mode.

**Comment by andreamah** [comment]
If you're not seeing it anymore, I'm going to assume that it's fixed :)
