### ISSUE TITLE
Strange setting name `notebook.formatOnSave.enabled`

### ISSUE THREAD

**Issue by amunger** [microsoft/vscode#177863]
Testing #177746

Should probably just be notebook.formatOnSave to be consistent.

<img width="294" alt="image" src="https://user-images.githubusercontent.com/2019016/226707066-03eff4c4-69f8-42f0-9e8d-fc7c6c30afc4.png">

**Comment by rebornix** [comment]
We will add more settings to format on save, for example, `notebook.formatOnSave.mode` to support formatting modified ranges only or full document. That's why we didn't follow the naming pattern of Editor formatting.

**Comment by amunger** [comment]
I like `Enable` better in that case, but there are a lot of existing settings that use both 'Enable' and 'Enabled', so it's fine to leave this as is.
