### ISSUE TITLE
Highlight code using mouse

### ISSUE THREAD

**Issue by snchrisman** [microsoft/vscode#177847]
Type: <b>Bug</b>

Use the mouse, click the left button and hold, move from left to right and then down to highlight code.  Keep going down toward to the bottom of the page and the page should scroll and continue highlighting.  It does not do that anymore and it has been working just fine for many years of using this VS Studio. 

VS Code version: Code 1.76.2 (ee2b180d582a7f601fa6ecfdad8d9fd269ab1884, 2023-03-14T17:55:54.936Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2208)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.74GB (7.16GB free)|
|Process Argv|--crash-reporter-id 9d77ab9c-7bb7-4de6-89a7-3c2ed9fb142b|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
apacheconf-snippets|eim|1.3.0
prettier-vscode|esb|9.10.4
auto-close-tag|for|0.5.14
vscode-apache|mrm|1.2.0
es6-css-minify|olb|3.3.3
live-sass|rit|3.0.0
LiveServer|rit|5.7.9
php-ci|sma|0.4.2
vscode-icons|vsc|12.2.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vscaac:30438847
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
pynewvextcfv2:30681851
azure-dev_surveyone:30548225
vscccc:30610679
pyindex848:30662994
nodejswelcome1cf:30587006
3biah626:30602489
pyind779:30671433
f6dab269:30613381
vscrpc:30673769
pythonsymbol12:30671437
2i9eh265:30646982
showlangstatbar:30672706
vsccsb:30677849
functionswalk:30687959
pythonms35:30686772

```

</details>

**Comment by hediet** [comment]
I cannot reproduce. Can you share a screenrecording?

**Comment by snchrisman** [comment]
I have tried to attach an mp4 in the email and it came back file size has
exceeded.  See if this link works for you.

https://clipchamp.com/watch/LsSx4ysUrLn

**Comment by hediet** [comment]
Did you try with default settings?

**Comment by snchrisman** [comment]
Yep.  I just discovered something here.  When I had this window maximized
on my laptop main screen, it worked just fine.  When I maximized it on the
second large monitor, it did not work there.  Same way on my 3rd monitor.
Weird.

**Comment by hediet** [comment]
I notice there is no taskbar. I guess the window is bigger than the screen, thus preventing scrolling to work.

**Comment by snchrisman** [comment]
I was able to make this work by turning on the status bar from the View >
Appearance menu.  Now I was able to highlight and scroll with the mouse.
Thank you!
