### ISSUE TITLE
Problems panel lightbulb shifts problems around

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#177881]
Type: <b>Bug</b>

1. With a TS file:

```ts
const abcdefg = 123;
abcdef;
```

2. Open the problems panel and hover over the error about `abcdef`

**Bug**
On hover, the entire error message shifts over when the lightbulb is shown

<img width="350" alt="Screenshot 2023-03-21 at 12 46 23 PM" src="https://user-images.githubusercontent.com/12821956/226724587-d09e254f-85ae-49fb-a28c-1b0a7066c43b.png">

previously I believe the lightbulb replaced the error icon to avoid this shift

VS Code version: Code - Insiders 1.77.0-insider (Universal) (833ac685084e2028b09753392b82c641c7025bbc, 2023-03-21T05:26:40.905Z)
OS version: Darwin x64 22.3.0
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|3, 3, 3|
|Memory (System)|32.00GB (2.32GB free)|
|Process Argv|--crash-reporter-id 48781ca2-1705-4f64-9bab-325055aab55d|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by sandy081** [comment]
Caused by https://github.com/microsoft/vscode/commit/dc619de8d9efdabd781fc5658d0051813c347055
