### ISSUE TITLE
Telemetry questions

### ISSUE THREAD

**Issue by BarryWheeler** [Microsoft/vscode#17790]
Hi!

I have a few questions related with telemetry, embedded into VSCode:

1. We know that VSCode have telemetry, but when disabled, is it stays completely silent or sends "opt-out" signal to servers? Atom works like this, until telemetry package is completely removed (as they says, not tested by myself).

2. May be it will be a good idea to ask user about "opt-in" for telemetry, instead of "opt-out" by default? When VSCode starts for first time?

3. Is packages have ability to gather data and send it to devs? May be it will be good idea to have ability to completely mute ANY telemetry communications between VSCode/Packages and dev servers? For those, who concerned about their privacy?

4. What exactly telemetry gathers and sends?

**Comment by seanmcbreen** [comment]
Hi @BarryWheeler 

These are good questions - we use the telemetry from VS Code to help understand issues customers run into and make the product better.  But we also want to be fully respect our users wishes and be transparent about the process.

I'll respond to each question:

1. We recently made a change to our Opt-Out telemetry story (just leading up to the holidays) that makes this answer easy.  If you opt out via our settings we send **no** telemetry.  In the past we used to send an event saying you had opted out.  I need to update our FAQ to reflect this.

2. We made an explicit decision when designing VS Code to let the user get to the editor ASAP post install.  This actually is closely related to your other question #17809.  As a result our 'installer' opens VS Code with an Editor in focus ready to type (I use quotes for 'installer' as we really don't have an installer on Mac and Linux - for Windows we do).  We have no additional prompts for the EULA or Telemetry as a result, these are instead covered off in the download button on the website.

3. Packages for VS Code have full access to NodeJS and relevant modules like HTTP - as a result it's not possible for us to prevent them from recording and sending telemetry.  Packages are in many ways just another piece of software you are installing on your machine with many of the same capabilities.  So the the best practice is to ensure that you are comfortable with the transparency of any package you install. 

4. We send telemetry for two broad categories - stability (performance characteristics, crash data) and usage (feature use, package use) we use this data to improve the product and ensure that we are resolving the most pressing issues and improving the most popular features.  Listing out the full details but it's all in the code base - thats likely not very satisfying as a response so here is a quick example...

For instance to understand why we may have a slow start-up time we send detains to diagnose the bottleneck this can include (Time to start, OS, VS Code Version, Number of CPUs, CPU Model, Memory,Free Memory, Extensions Loaded, Time to load each segment of the start-up sequence e.g. editor active, ...) the list is pretty detailed but it's all there to help us make the product better for all users.

OK, Hope that helps, I'll go and update our FAQ with the details around opt-out == no telemetry as I think thats a really important gap in our docs today.

Happy Coding,
Sean

p.s. again closing the issue but feel free to re-open if the context above does not provide enough background on how we got to where we are today.
