### ISSUE TITLE
The remote host may not meet VS Code Server's prerequisites for glibc and libstdc++

### ISSUE THREAD

**Issue by zydxhs** [microsoft/vscode#177963]
VSCode Version: 1.76.2
OS Version: Windows 10 LTSC 21H2 19044.2546
Remote OS: Debian 11.6
ldd --version 2.31
kernel version: 5.10.0-21-amd64
strings /lib/x86_64-linux-gnu/libstdc++.so.6 | grep GLIBCXX
GLIBCXX_3.4
GLIBCXX_3.4.1
GLIBCXX_3.4.2
GLIBCXX_3.4.3
GLIBCXX_3.4.4
GLIBCXX_3.4.5
GLIBCXX_3.4.6
GLIBCXX_3.4.7
GLIBCXX_3.4.8
GLIBCXX_3.4.9
GLIBCXX_3.4.10
GLIBCXX_3.4.11
GLIBCXX_3.4.12
GLIBCXX_3.4.13
GLIBCXX_3.4.14
GLIBCXX_3.4.15
GLIBCXX_3.4.16
GLIBCXX_3.4.17
GLIBCXX_3.4.18
GLIBCXX_3.4.19
GLIBCXX_3.4.20
GLIBCXX_3.4.21
GLIBCXX_3.4.22
GLIBCXX_3.4.23
GLIBCXX_3.4.24
GLIBCXX_3.4.25
GLIBCXX_3.4.26
GLIBCXX_3.4.27
GLIBCXX_3.4.28

I noticed [104743](https://github.com/microsoft/vscode/issues/104743) , but it didn't suit me. My remote host has enough free space:
```text
$ df -h
文件系统        容量  已用  可用 已用% 挂载点
udev            7.8G     0  7.8G    0% /dev
tmpfs           1.6G  1.6M  1.6G    1% /run
/dev/sdb2        38G   14G   23G   38% /
tmpfs           7.8G     0  7.8G    0% /dev/shm
tmpfs           5.0M  4.0K  5.0M    1% /run/lock
/dev/sdb3        82G   53G   29G   65% /home
/dev/sdb1       285M  5.8M  279M    3% /boot/efi
tmpfs           1.6G   60K  1.6G    1% /run/user/117
tmpfs           1.6G   72K  1.6G    1% /run/user/1000
```

**Comment by zydxhs** [comment]
I use Remote-SSH plugin.

**Comment by zydxhs** [comment]
The content of`~/.vscode-server/.ee2b180d582a7f601fa6ecfdad8d9fd269ab1884.log` is:
```text
   1   │ *
   2   │ * Visual Studio Code Server
   3   │ *
   4   │ * By using the software, you agree to
   5   │ * the Visual Studio Code Server License Terms (https://aka.ms/vscode-server-license) and
   6   │ * the Microsoft Privacy Statement (https://privacy.microsoft.com/en-US/privacystatement).
   7   │ *
   8   │ Server bound to 127.0.0.1:33641 (IPv4)
   9   │ Extension host agent listening on 33641
  10   │
  11   │ [11:07:59]
  12   │
  13   │
  14   │
  15   │
  16   │ [11:07:59] Extension host agent started.
  17   │ [11:08:01] Error: read ECONNRESET
  18   │     at TLSWrap.onStreamRead (node:internal/stream_base_commons:217:20) {
  19   │   errno: -104,
  20   │   code: 'ECONNRESET',
  21   │   syscall: 'read'
  22   │ }
  23   │ Last EH closed, shutting down
  24   │ [11:12:59] Last EH closed, shutting down
```

**Comment by 2656657838** [comment]
Hello! Have you solved your problem?
I had the same problem.

**Comment by nakabonne** [comment]
I'm also running into this issue

**Comment by pedrofzero** [comment]
I just had this issue for the first time, on a machine that has always worked.

**Comment by y10ab1** [comment]
Same here.

**Comment by jusstol** [comment]
same for me with january 2024 release, when connecting to a remote Centos 7 machine that worked fine before

**Comment by chuahaoyan** [comment]
same. is it a VScode issue?

**Comment by mariosconsta** [comment]
By the recent activity on this thread I think VS Code has a problem.

**Comment by TechNyquist** [comment]
Almost certain it's a problem with January 2024 update. I updated yesterday and my remote dev stopped to work with VSCode saying `The remote host may not meet vs code server's prerequisites for glibc and libstdc++`.

"Remote - SSH" log connects correctly to remote machine, then hangs after `Spawned remote CLI: 6479` trying to `Waiting for server log...`, then after 15 seconds it echoes the following output and dies:
```
[10:14:33.036] > 306917d9dc65: start
> SSH_AUTH_SOCK====
> DISPLAY====
> listeningOn====
> osReleaseId==ubuntu==
[10:14:33.038] > arch==x86_64==
> vscodeArch==x64==
> bitness==64==
> tmpDir==/run/user/1001==
> platform==linux==
> unpackResult====
> didLocalDownload==0==
> downloadTime====
> installTime====
> serverStartTime==14595==
> execServerToken==8b57115601c5==
[10:14:33.070] > 306917d9dc65: end
[10:14:33.071] Received install output: 
SSH_AUTH_SOCK====
DISPLAY====
listeningOn====
osReleaseId==ubuntu==arch==x86_64==
vscodeArch==x64==
bitness==64==
tmpDir==/run/user/1001==
platform==linux==
unpackResult====
didLocalDownload==0==
downloadTime====
installTime====
serverStartTime==14595==
execServerToken==8b57115601c5==
[10:14:33.072] Failed to parse remote port from server output
[10:14:33.072] Terminating local server
[10:14:33.074] Exec server for ssh-remote+7b22686f73744e616d65223a224b616c6569646f2d564d2d72656d6f7465227d failed: Error
[10:14:33.074] Error opening exec server for ssh-remote+7b22686f73744e616d65223a224b616c6569646f2d564d2d72656d6f7465227d: Error
[10:14:33.084] Local server exit: 15
```

In my company me and a colleague are experiencing this problem and we are the only two that have updated VSCode yesterday. Nothing happened to the other mates and we are using identical VMs on office VMWare server.

Furthermore, downgrading to previous version isn't of any help.

Ubuntu 18.04.5 LTS (GNU/Linux 4.15.0-128-generic x86_64)
ldd (Ubuntu GLIBC 2.27-3ubuntu1.4) 2.27
libstdc++.so.6 (libc6,x86-64)

**Comment by michaelgfeldman** [comment]
same problem here

**Comment by YYuanAnyVision** [comment]
same problem here..

**Comment by jaeyson** [comment]
my vscode auto updates and encountered the same issue.

Version: 1.86.0 (Universal)
Commit: 05047486b6df5eb8d44b2ecd70ea3bdf775fd937
Date: 2024-01-31T10:29:15.765Z
Electron: 27.2.3
ElectronBuildId: 26495564
Chromium: 118.0.5993.159
Node.js: 18.17.1
V8: 11.8.172.18-electron.0
OS: Darwin arm64 23.2.0

**Comment by mariosconsta** [comment]
Just to update: https://github.com/microsoft/vscode/issues/203375

**Comment by Atanu443** [comment]
The remote host may not meet VS Code Server's prerequisites for glibc and libstdc++ 
i am facing the same issue also. 
if anyone got the solution please help me

**Comment by siboy** [comment]
i got the same problem, how to solve this issue, anyone knows??

**Comment by guillermofernandezmartinez** [comment]
Just uninstall your current VS Code (v1.86) and install the previous version (v1.85)... and make sure you disable the automatic updates in the settings file!

**Comment by jromerodiaz** [comment]
> Just uninstall your current VS Code (v1.86) and install the previous version (v1.85)... and make sure you disable the automatic updates in the settings file!

I was literally about to comment this, it does work

**Comment by SihamAmarouche** [comment]
Same problem here I think something relate to the new update.

**Comment by SihamAmarouche** [comment]
Same problem here I think something related to the new update.

**Comment by lucasoal** [comment]
Same here, folks.
As @TechNyquist said, this error started after the 'January 2024 (version 1.86)' update.

The solution is downgrade the version to [1.85](https://code.visualstudio.com/updates/v1_85) or earlier.

**Comment by iamprakashom** [comment]
Yes, it is due to a new update.

**Comment by bossmantfrank** [comment]
Noo I just need to find out my trusted phone number 


Sent from Yahoo Mail for iPhone


On Thursday, February 1, 2024, 8:30 PM, Tommy ***@***.***> wrote:




Hello! Have you solved your problem?
I had the same problem.

**Comment by aidahalitaj** [comment]
I have the same issue

**Comment by mrhoang18** [comment]
same problem here..

**Comment by mrhoang18** [comment]
I uninstalled VSCode 1.86 (I use Ubuntu) by:
+ sudo snap remove code
Then download and install VSCode version 1.85.2:
+ sudo dpkg -i code_1.85.2-1705561292_amd64.deb
I have solved the problem

**Comment by adrhem** [comment]
Experiencing this issue. Rolling back to 1.85 worked for me.

**Comment by neocamel** [comment]
> Experiencing this issue. Rolling back to 1.85 worked for me.

I'd be willing to roll back, but I'm worried I'm going to lose all my configurations. Did you have to reinstall/reconfigure all your extensions and stuff?

**Comment by adrhem** [comment]
> > Experiencing this issue. Rolling back to 1.85 worked for me.
> 
> I'd be willing to roll back, but I'm worried I'm going to lose all my configurations. Did you have to reinstall/reconfigure all your extensions and stuff?

All my configuration remains. Just to clarify I am using mac and replaced the .app file. I also sync my config using my github account.

**Comment by neocamel** [comment]
> > > Experiencing this issue. Rolling back to 1.85 worked for me.
> > 
> > 
> > I'd be willing to roll back, but I'm worried I'm going to lose all my configurations. Did you have to reinstall/reconfigure all your extensions and stuff?
> 
> All my configuration remains. Just to clarify I am using mac and replaced the .app file. I also sync my config using my github account.

Syncing your config to github is a great idea! I'm on Windows :-(

I've been doing this long enough that I know if I uninstall, I'm looking at a week's worth of work to get back to where I was yesterday... Automatic Updates FTW!

**Comment by Jhin3433** [comment]
> Just uninstall your current VS Code (v1.86) and install the previous version (v1.85)... and make sure you disable the automatic updates in the settings file!

This works for me!!!!!! THANKS!!!!

**Comment by Masarmiento04** [comment]
> Just uninstall your current VS Code (v1.86) and install the previous version (v1.85)... and make sure you disable the automatic updates in the settings file!

Dosen't works for me. Got this messege "Extension is not compatible with Code 1.85.2. Extension requires: ^1.86.0"

**Comment by 935077727** [comment]
> > Just uninstall your current VS Code (v1.86) and install the previous version (v1.85)... and make sure you disable the automatic updates in the settings file!
> 
> Dosen't works for me. Got this messege "Extension is not compatible with Code 1.85.2. Extension requires: ^1.86.0"

Hi,  the same with me, but you can click the remote extension's botton "Switch to Pre-Release Version", it it work for me. luck to o u

**Comment by shezhangzhang** [comment]
same problem!

**Comment by birenjack** [comment]
> VSCode Version: 1.76.2 OS Version: Windows 10 LTSC 21H2 19044.2546 Remote OS: Debian 11.6 ldd --version 2.31 kernel version: 5.10.0-21-amd64 strings /lib/x86_64-linux-gnu/libstdc++.so.6 | grep GLIBCXX GLIBCXX_3.4 GLIBCXX_3.4.1 GLIBCXX_3.4.2 GLIBCXX_3.4.3 GLIBCXX_3.4.4 GLIBCXX_3.4.5 GLIBCXX_3.4.6 GLIBCXX_3.4.7 GLIBCXX_3.4.8 GLIBCXX_3.4.9 GLIBCXX_3.4.10 GLIBCXX_3.4.11 GLIBCXX_3.4.12 GLIBCXX_3.4.13 GLIBCXX_3.4.14 GLIBCXX_3.4.15 GLIBCXX_3.4.16 GLIBCXX_3.4.17 GLIBCXX_3.4.18 GLIBCXX_3.4.19 GLIBCXX_3.4.20 GLIBCXX_3.4.21 GLIBCXX_3.4.22 GLIBCXX_3.4.23 GLIBCXX_3.4.24 GLIBCXX_3.4.25 GLIBCXX_3.4.26 GLIBCXX_3.4.27 GLIBCXX_3.4.28
> 
> I noticed [104743](https://github.com/microsoft/vscode/issues/104743) , but it didn't suit me. My remote host has enough free space:
> 
> ```
> $ df -h
> 文件系统        容量  已用  可用 已用% 挂载点
> udev            7.8G     0  7.8G    0% /dev
> tmpfs           1.6G  1.6M  1.6G    1% /run
> /dev/sdb2        38G   14G   23G   38% /
> tmpfs           7.8G     0  7.8G    0% /dev/shm
> tmpfs           5.0M  4.0K  5.0M    1% /run/lock
> /dev/sdb3        82G   53G   29G   65% /home
> /dev/sdb1       285M  5.8M  279M    3% /boot/efi
> tmpfs           1.6G   60K  1.6G    1% /run/user/117
> tmpfs           1.6G   72K  1.6G    1% /run/user/1000
> ```

1. download VSCodeUserSetup-x64-1.85.2
2. change Remote SSH version to last version ( which you used before )
3. connect again~

that is my way, hope can help you

**Comment by npurson** [comment]
Check the workaround here: https://github.com/npurson/vscode-server-toolchain-workaround.

**Comment by muhssamy** [comment]
same error here on all my servers :(

**Comment by fygy10** [comment]
same error. is downgrade versions the current work around? any update from vs code?

**Comment by house40105** [comment]
I had the same problem and fixed it by going back to an older version. Here's what I did:
1.Download the previous version from https://code.visualstudio.com/updates/v1_85.
2.Install it directly; it will replace the new version.
3.In the Extensions section (especially for Remote-SSH, which I use for connections), click 'Switch to Release Versions.'
4.Restart VSCode.
These steps kept my previous VSCode settings intact. Hope the official team can fix this soon.

**Comment by davidlin504** [comment]
thanks @house40105 
Mac silicon Version: 1.85.2 works

**Comment by Ariza-Sun** [comment]
same problem  2024/2/5

**Comment by knowledge-llz** [comment]
same problem 2024/2/7

**Comment by gravity22** [comment]
same problem 2024/2/7
downgrading to the previous version (v1.85) has solved the problem temporarily as mentioned some people here.

**Comment by sevi221** [comment]
Same problem :(

**Comment by TechNyquist** [comment]
Recovery release expected tomorrow #203375 ([claim comment](https://github.com/microsoft/vscode/issues/203375#issuecomment-1932156865)).

**Comment by Wei3Xue1** [comment]
Uninstalling VS Code v1.86 and then installing VS Code v1.85.2 following @house40105 's method worked for me.

**Comment by muhssamy** [comment]
new release fixes my issue
![image](https://github.com/microsoft/vscode/assets/49695385/375f2428-2e0a-42cf-bb00-e2cf0bf48d1f)
