### ISSUE TITLE
Opening from CLI (code <file>) opens last session without new file on fresh start

### ISSUE THREAD

**Issue by lroellin** [Microsoft/vscode#17793]
- VSCode Version: 1.8.1
- OS Version: macOS 10.12.2

Steps to Reproduce:

1. Make sure, Visual Studio Code is stopped completely (Quit)
2. Type `code <file>`
3. Observe that
  * Your last session is opened
  * `file`is not part of that session
4. Type `code <file>`again (don't quit Visual Studio ode)
5. Your file is now opened
 
What should happen:
1. Regardless if quit or not
2. Type `code <file>
3. Your last session is opened and `file` is part of that session.

**Comment by egamma** [comment]
@lroellin I'm unable to reproduce the behaviour you describe in steps 1-3. Please the attached recording. The recording starts by shutting down VS Code completely. Also notice that when you open a single file the VS Code will open in single file mode, which is indicated by the purple status bar.

Please provide more detailed steps to reproduce this issue.

![open](https://cloud.githubusercontent.com/assets/172399/21471852/c4932ad2-cac0-11e6-8573-2eff6d5fe3dc.gif)

**Comment by lroellin** [comment]
Hi @egamma 

Thanks for your time in testing this issue! It seems that I can't reproduce it for now myself. I don't know what went wrong, maybe something with my setup. I'll keep an eye on it though and will check if it happens again.

I'll close this issue for now.
