### ISSUE TITLE
'Connect to' incorrectly prompts me to install an extension that I've disabled 

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#177939]
Testing #177702

1. Disable remote ssh
2. Open `connect to` quick input from welcome view

**bug**
I see an option to install the `remote ssh` extension:

![Screenshot 2023-03-21 at 5 46 10 PM](https://user-images.githubusercontent.com/12821956/226773456-d740932f-b3a5-48a8-b0ba-2c524a59ed3c.png)

Clicking this button does not fix the issue because the extension remains disabled. Instead we should likely show an option to enable the extension

**Comment by bhavyaus** [comment]
Fixed. 
1. Use the remote picker to install a remote extension if you do not have one installed.
2. Verify that the relevant commands for that remote extension show up in the remote picker next time around.
3. Disable the remote extension
4. Verify that the commands do not show up in the remote picker.
