### ISSUE TITLE
Allow to preview theme on mouse hover

### ISSUE THREAD

**Issue by hun1ahpu** [Microsoft/vscode#17799]
It would be nice to be able to preview Color Theme on hover before choosing. The name of the theme doesn't always speak for itself and the user have to go through the menus again to try another theme or go back to previous one.
UPDATE: As mentioned by @dfroze it is possible with the keyboard though i still think it will be much easier with the mouse.

**Comment by dfroze** [comment]
Hello @hun1ahpu, there is already something like this, you just need to use up/down arrows. 
After you press Color Theme, it already focus the current theme, just use the arrows and it will auto update the theme

**Comment by hun1ahpu** [comment]
Huh nice! It's not very discoverable though. Mouse hover would be much easier i believe.
Renaming issue to 'Theme preview on mouse hover'.
Thanks @dfroze !

**Comment by aeschli** [comment]
We're using the quick picker here. Either we'd need a mouse over event, or the selection changes on mouse over.

**Comment by bpasero** [comment]
Personally I like the way it works now and would find the preview on mouse hover too hectic.

**Comment by mjbvz** [comment]
Closing as this issue was filed almost a year ago and there has not be significant interest since. You can already preview themes when navigating the theme list with arrow keys
