### ISSUE TITLE
`syncStatus` event is fired too many times on startup

### ISSUE THREAD

**Issue by bhavyaus** [microsoft/vscode#177937]
Repro steps:

1. Ensure settings sync is ON. 
2. Run Developer: Reset Welcome Page Walkthrough Progress
3. Open `Get Started with VS Code walkthrough`
4. Open step One shortcut to access everything or Quickly navigate between your files
5. Hit the button

🐛 Quick pick closes right after clicking and image flashes.

Try same repro steps with settings sync OFF and everything works fine.

See https://github.com/microsoft/vscode/issues/176539#issuecomment-1478765637

**Comment by bhavyaus** [comment]
Yes.We collect all the contexts which affect steps in a walkthrough and listen to their changes. 
One of the steps is listening to syncStatus:
https://github.com/microsoft/vscode/blob/2e954c8b2d71db71362425c8ba07840aa4642f41/src/vs/workbench/contrib/welcomeGettingStarted/common/gettingStartedContent.ts#L186

**Comment by sandy081** [comment]
`syncStatus` is being triggered whenever there is change in status. The consumer of this has to handle it appropriately. I am not sure it is a good idea to restrict the event firing even if there is change in status. You can always debounce on the consumer side.

Can you please let me know your use case?

**Comment by bhavyaus** [comment]
> `syncStatus` is being triggered whenever there is change in status. The consumer of this has to handle it appropriately. I am not sure it is a good idea to restrict the event firing even if there is change in status. You can always debounce on the consumer side.
> 
> Can you please let me know your use case?

Use case: We collect all the context keys in a walkthrough and use it to toggle walkthrough step visibility based on the specific context becoming active. 

This issue has only been happening in the last few weeks and I was wondering what changed which causes this behavior? 
We had previously made no changes on our end w.r.t. to listening/reacting to context key changes for it to have this effect. 
Having said that, I handled this on our end with https://github.com/microsoft/vscode/pull/177966 which fixes the issue but wasn't sure if there was a larger issue with so many sync status events being fired.

**Comment by sandy081** [comment]
Ah ok, thanks for the context. I will try to repro and investigate.
