### ISSUE TITLE
Keyboard esc does not close replace window

### ISSUE THREAD

**Issue by GJSK-Novice** [microsoft/vscode#177946]
Type: <b>Feature Request</b>

After I opened "find & replace" window with Ctrl+H in a Jupyter notebook by vscode, I can't close it with "esc" button.
It does work with "find" window opened with Ctrl+F.

VS Code version: Code 1.76.2 (ee2b180d582a7f601fa6ecfdad8d9fd269ab1884, 2023-03-14T17:55:54.936Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: No

**Comment by j824h** [comment]
I can't get this reproduced as of 1.78.2 release.
I guess it was fixed with #179900?

**Comment by GJSK-Novice** [comment]
I retried and it works now. Maybe it's fixed with https://github.com/microsoft/vscode/pull/179900
