### ISSUE TITLE
Code Text Editor Scattered

### ISSUE THREAD

**Issue by petatemarvin26** [microsoft/vscode#177947]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.76.2 - x64
- OS Version: Ubuntu 22.04.1 LTS - Jammy

Steps to Reproduce:

1. Open split editor with code text
2. put the cursor with a comment code 

NOTE:
- When the cursor blink, the scattered text also happening at the same time

![image](https://user-images.githubusercontent.com/46154422/226780171-e3492053-eddb-4df5-a8af-0fdd1fd67b61.png)

**Comment by deepak1556** [comment]
Please disable hardware acceleration following the steps at https://code.visualstudio.com/updates/v1_40#_disable-gpu-acceleration
