### ISSUE TITLE
TypeScript realtime lint for all files

### ISSUE THREAD

**Issue by Llorx** [Microsoft/vscode#17794]
- VSCode Version:
1.8.1
- OS Version:
Windows 7

Simply, when I make breaking changes to my files, VScode do not detects at all the erros on other files until I open those files. I would like for VScode to check for problems on all files (including closed ones, if possible) when I make changes.

For example, if I have a module called `mod` and other files import something from the `mod`, if I rename `mod` to `mod2`, VScode do not shows error on all the files, but some of them, and sometimes after some time has passed.

And if I rename it back to `mod`, the errors are still shown and I have to reedit the file for the error to dissapear.
![](http://i.imgur.com/fVfaHTG.gif)

Seems that the checker is kinda chunky.

I do not compile my .ts files when I save them, as I load them directly with `ts-node`.

**Comment by egamma** [comment]
Duplicates #973

**Comment by Llorx** [comment]
Don't get how this is a duplicate of an integrated compiler

**Comment by egamma** [comment]
@Llorx 

>Don't get how this is a duplicate of an integrated compiler

Issue #973 is about *transpiling/building* and not about an integrated compiler. Currently the typescript language service checks only the files that are opened and not all files in the project, This is a known limitation and issue #973 is about removing this restriction.

**Comment by Llorx** [comment]
Oh, nice.

And what about the check problems I also noted? Should I open a different
issue for that?
