### ISSUE TITLE
Settings Sync menu wont go away

### ISSUE THREAD

**Issue by abhay-ahirkar** [microsoft/vscode#177973]
- VS Code Version: 
- OS Version: 

Steps to Reproduce:

![image](https://user-images.githubusercontent.com/127684179/226825191-ec8f3f18-5e55-4532-a410-90e633039e10.png)

**Comment by gjsjohnmurray** [comment]
Do you mean the quickpick at top centre with chechboxes? Did you try pressing the Escape key?

**Comment by abhay-ahirkar** [comment]
> Do you mean the quickpick at top centre with chechboxes? Did you try pressing the Escape key?

it did work after pressing the escape key
thanks

**Comment by sandy081** [comment]
That is expected to be sticky.
