### ISSUE TITLE
'connect to' prompt should likely say `Workspace` instead of window

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#177936]
Testing #177702

1. Open `connect to` quick pick from welcome view

**bug**
The current prompt says `connect to remote window`:

![Screenshot 2023-03-21 at 5 39 56 PM](https://user-images.githubusercontent.com/12821956/226772787-af8341d6-a32c-4576-9115-a6a486cddeab.png)

I found this confusing. It should likely say `workspace` instead of `window`

**Comment by bhavyaus** [comment]
@bamurtaugh I was keeping this consistent with the remote indicator. Please let me know if you agree that we need to change the wording.

**Comment by bamurtaugh** [comment]
This feedback is a good point @mjbvz, and I agree @bhavyaus that we should be consistent, so either use "window" or "workspace" in both this prompt and the remote indicator.

I'm fine with either term; I haven't seen user confusion here, so I'm open to what others think feels the most consistent and logical too. cc @aeschli and @joyceerhl for thoughts.

**Comment by aeschli** [comment]
I think it's 'window'. It's the current window that is reused to open a (remote) workspace.

That said, shouldn't `Connect to Host...` already do that? I thought we agreed that `Connect to` should follow the `window.openFoldersInNewWindow` setting

![image](https://user-images.githubusercontent.com/6461412/227145001-d61ad00f-a6a4-4f76-835a-5dcad7256667.png)

That's what I have changed WSL to follow.
IMO we want to remove the `Connect Current Window to Host` command. It would be cool if we could have modifier key that forces a new window.

@joyceerhl FYI

**Comment by joyceerhl** [comment]
In the remote indicator we say `open a remote window`, in this remote start picker we say `connect to a remote workspace`.

@aeschli yes we discussed that the current windowing behavior is inconsistent across remotes, I think the right approach is probably to add support for `alt` actions in the `statusBar/remoteIndicator` menu item, which is also what most remotes offer in the remote explorer. If we do this then the remote start picker should also adopt that. Let me know what you think @bhavyaus.

**Comment by aeschli** [comment]
Oh, now I see the `connect to a remote window`. I thought his is about `SSH: Connect Current Window to Host...`

yes, given that we don't open new Windows anymore, `Connect to a remote workspace` makes sense. Same for the hover on the remote indicator.

**Comment by bhavyaus** [comment]
> In the remote indicator we say `open a remote window`, in this remote start picker we say `connect to a remote workspace`.
> 
> @aeschli yes we discussed that the current windowing behavior is inconsistent across remotes, I think the right approach is probably to add support for `alt` actions in the `statusBar/remoteIndicator` menu item, which is also what most remotes offer in the remote explorer. If we do this then the remote start picker should also adopt that. Let me know what you think @bhavyaus.

The remote picker also currently says `open a remote window`. 
Is the idea with the `alt` actions that remote picker would borrow from the `alt` statusBar/remoteIndicator items? 
For now, I think its simpler to share a string for both to use. And for that string to read `Connect to a remote workspace`.

**Comment by joyceerhl** [comment]
`Remote workspace` is misleading for cases like `Connect to SSH` and `Connect to WSL`, because in these cases we do not in fact open to a specific folder or workspace (we can't do that without first establishing the remote connection) and must instead open an empty window.

**Comment by sandy081** [comment]
Moving this to next milestone as part of issue tracking and cleaning for the current milestone as we are close to the release.

**Comment by bhavyaus** [comment]
The text in the quick pick now reads `Select an option to connect`.
