### ISSUE TITLE
[Feature Request]: Filters

### ISSUE THREAD

**Issue by ToxiCore** [Microsoft/vscode#17795]
Please add the feature to add **filters for directories** inside the editor.

It may be done by creating some _meta file_ (thats also not listed in the file-tree) which contains the information what type of files to show and what not:
For **example** I want to exclude files from showing up by the suffix. When I am writing TypeScript code for example only ".ts" files and not ".js" files should be shown. Or when I am coding in Python ".pyc" files should be excluded from view because those don't matter to the user but the interpreter.

**Comment by mrmlnc** [comment]
Hello, @ToxiCore,

Have you tried to use `settings.json` for workspace? 

```
File -> Preferences -> Workspace Settings
```

For example,

![image](https://cloud.githubusercontent.com/assets/7034281/21466772/33fbf42a-c9e6-11e6-9cdf-7e8d29d590d2.png)

**Comment by egamma** [comment]
This is already supported as explained by @mrmlnc above.
