### ISSUE TITLE
Show progress while installing extensions

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#177956]
Testing #177702

I think I am wrongly being asked to install extensions now, but when I do need to install an extension, it would be nice to show a progress bar somewhere while this runs

<img width="642" alt="image" src="https://user-images.githubusercontent.com/323878/226787136-631848ff-d865-4dab-afe5-7bd0f9f33bf5.png">

Or if I am going to be waiting for a bit, you might run the progress in a modal dialog or non-modal notification instead of a quickpick

**Comment by luabud** [comment]
somewhat related: https://github.com/microsoft/vscode/issues/177950

FWIW I did see a progression bar while the extension was installing on Windows
