### ISSUE TITLE
Activating extension 'njpipeorgan.wolfram-language-notebook' failed

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#177997]
Testing #177645

1. Use vscode-exploration
2. Install https://marketplace.visualstudio.com/items?itemName=njpipeorgan.wolfram-language-notebook
3. F1 > Wolfram Language Notebook: Create New Wolfram Language Notebook
4. Error in console

```
Activating extension 'njpipeorgan.wolfram-language-notebook' failed: /lib64/libc.so.6: version `GLIBC_2.33' not found (required by /home/parallels/.vscode-exploration/extensions/njpipeorgan.wolfram-language-notebook-0.1.1/node_modules/zeromq/prebuilds/linux-x64/node.napi.glibc.node).
```

I am opening this issue because it mentions `napi` here and I thought this might be useful.

**Comment by deepak1556** [comment]
This is an issue with the native module being compiled with newer gcc toolchain making it unable to load on CentOS.
