### ISSUE TITLE
Decline in processor throughput following loss of connection/sync with remote repository

### ISSUE THREAD

**Issue by TheCrowbill** [microsoft/vscode#177964]
Type: <b>Performance Issue</b>

Whatever is causing this issue, from the time it first appears, processor throughput declines until halts or is stopped by user.

VS Code version: Code 1.76.2 (ee2b180d582a7f601fa6ecfdad8d9fd269ab1884, 2023-03-14T17:55:54.936Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 3 3200U with Radeon Vega Mobile Gfx   (4 x 2595)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|3.44GB (0.40GB free)|
|Process Argv|C:\\Users\\Hall.Barnett\\Repositories\\testorg\\FundItETC --crash-reporter-id 8a3109a1-8b22-42ff-b3a7-7ab94a33f672|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	    45	 13500	code main
    0	    11	  6672	   utility-network-service
    0	   100	  8064	   window (README.md - FundItETC - Visual Studio Code)
    0	    51	 10760	   shared-process
    0	     3	 11232	     fileWatcher
    0	    12	 15712	     ptyHost
    0	     0	 13432	       console-window-host (Windows internal process)
    0	     8	 15932	       C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe -noexit -command "try { . \"c:\Users\Hall.Barnett\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\contrib\terminal\browser\media\shellIntegration.ps1\" } catch {}"
    0	     3	 12448	   crashpad-handler
    0	    51	 13868	   issue-reporter
    0	    44	 15740	   gpu-process
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (README.md - FundItETC - Visual Studio Code)
|    Folder (FundItETC): 12 files
|      File types: md(2) json(2) gitignore(1) sol(1) js(1)
|      Conf files: package.json(1);
```

</details>
<details><summary>Extensions (40)</summary>

Extension|Author (truncated)|Version
---|---|---
npm-intellisense|chr|1.4.4
vscode-markdownlint|Dav|0.49.0
testapi2|doa|0.0.18
gitlens|eam|13.4.0
prettier-vscode|esb|9.10.4
codespaces|Git|1.14.0
copilot|Git|1.78.9758
vscode-pull-request-github|Git|0.60.0
vs-code-runner|Har|2.0.1
solidity-debugger|hos|0.2.1
solidity-solhint|idr|1.1.4
plantuml|jeb|2.17.5
solidity|Jua|0.0.149
vscode-docker|ms-|1.24.0
isort|ms-|2022.8.0
python|ms-|2023.4.1
vscode-pylance|ms-|2023.3.20
jupyter|ms-|2023.2.1200692131
jupyter-keymap|ms-|1.1.0
jupyter-renderers|ms-|1.0.15
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-slideshow|ms-|0.1.5
remote-containers|ms-|0.282.0
cpptools|ms-|1.14.4
mythxvsc|Myt|0.7.21
vscode-debug-adapter-apache-camel|red|0.5.0
vs-code-prettier-eslint|rve|5.1.0
partial-diff|ryu|1.4.3
code-spell-checker|str|2.20.3
ethereum-security-bundle|tin|0.0.7
graphviz-interactive-preview|tin|0.3.5
solidity-metrics|tin|0.0.22
solidity-visual-auditor|tin|0.1.5
vscode-ethover|tin|0.0.7
vscode-inline-bookmarks|tin|0.1.0
vscode-LLL|tin|0.0.7
vscode-solidity-flattener|tin|0.0.11
vscode-solidity-language|tin|0.0.7
vscode-vyper|tin|0.0.15
markdown-editor|zaa|0.1.10

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vscaac:30438847
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30681850
azure-dev_surveyone:30548225
pyindex848:30662994
nodejswelcome1cf:30587006
2e4cg342:30602488
pyind779:30671433
f6dab269:30613381
pythonsymbol12:30671437
a9j8j154:30646983
vsccsb:30677849
defaultazurewalk:30687958
pythonms35cf:30686773

```

</details>

**Comment by joyceerhl** [comment]
Please try using extension bisect to identify whether an extension is causing this problem.

**Comment by TheCrowbill** [comment]
> Please try using extension bisect to identify whether an extension is causing this problem.

I have attempted to use the extension bisect tool as suggested. I have no new information at this time because I have become unable to reproduce my original issue whether using the bisect tool or not.

I suggest closing this issue until such time as I can reproduce the problem and provide more information. If I have some additional info in the future, I can reopen it.

Thanks for the attention already given to this.
