### ISSUE TITLE
Connect to Codespaces options under "Connect to..."

### ISSUE THREAD

**Issue by luabud** [microsoft/vscode#177957]
Testing #177702

Once I installed the codespaces extension and clicked on "Connect To", I was a bit confused as to why I saw "Delete Codespaces" there, given I was trying to connect to one. Is the idea here to improve discoverability of the command?

**Comment by bhavyaus** [comment]
Yes. Codespaces wants that command shown.  The remote indicator in an empty workspace also has the same behavior. You can still choose that command and delete a Codespace you may have previously created.
