### ISSUE TITLE
Wrong path when opening integrated terminal

### ISSUE THREAD

**Issue by zeyangl** [Microsoft/vscode#17798]
- VSCode Version: 1.8.1
- OS Version: macOS 10.12.2

Steps to Reproduce:

1. Click open integrated termianl
2. I get this error: 
The terminal process command `/opt/local/bin/bash` failed to launch (exit code: 1)

VSCode appears to find the wrong bash. I do not have a bash in /opt/local/bin/bash

**Comment by zeyangl** [comment]
A follow up on this issue. It appears that vscode launched from non-terminal also does not have the correct environment variable.

**Comment by Tyriar** [comment]
On `/opt/local/bin/bash`: The setting defaults to `$SHELL` which defines the default terminal shell, if his is a work computer it's likely an issue with how your org set it up.

On the env: You are probably setting your environment variables in `.bashrc`, this defines your env only when running through bash. This is why it runs fine through the terminal as it's already executed `.bashrc`. You can try:

- Move the env variables to `.profile`
- Run bash as a login shell using: `"terminal.integrated.shellArgs.osx": ["-l"]`

See https://code.visualstudio.com/docs/editor/integrated-terminal#_linux-os-x for more info
