### ISSUE TITLE
Search keybindings activating outside of search

### ISSUE THREAD

**Issue by andreamah** [microsoft/vscode#177906]
repro steps (only on macOS):
1. Have search results
2. Focus the editor
3. `F4` to focus on search results (which doesn't focus the tree)
4. Use `cmd`+`down`
5. Focuses on first line of search results and opens it.

// cc @roblourens 

edit: 
alternate repro in otherOS's:
1. Have search results
2. Focus the editor
3. `F4` to focus on search results (which doesn't focus the tree)
4. Try to copy a selection in the editor using `ctrl`+`c`
5. Should copy your selection to your clipboard. (you can check by pasting)

**Comment by meganrogge** [comment]
For the first case, not sure what was expected but `cmd+down` moved me to the end of the file, assuming that's correct

**Comment by andreamah** [comment]
Since you're not focused on the tree view (focused on the editor), you should just see that editor scrolling. I believe that's what you saw, so that's sufficient for verification.
