### ISSUE TITLE
[Feature Request]: if we can support paste file or folder which copied from Desktop 

### ISSUE THREAD

**Issue by RookieDay** [Microsoft/vscode#17791]
- VSCode Version: Code 1.8.1 (ee428b0eead68bf0fb99ab5fdc4439be227b6281, 2016-12-19T14:49:23.350Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions:

|Extension|Author|Version|
|---|---|---|
|html-snippets|abusaidm|0.0.18|
|vscode-html-css|ecmel|0.0.30|
|format-php|Kasik96|1.1.2|
|vscode-JS-CSS-HTML-formatter|lonefy|0.2.2|
|debugger-for-chrome|msjsdiag|2.4.1|

---

Steps to Reproduce:
1. open vsc
2. copy file or folder from desktop
3. it can`t paste to vsc, it seems only support copy/paste from vsc to vsc
4. maybe this case is not a issue ? it`s from vsc design that only support copy/paste from vsc to vsc ? 

![01](https://cloud.githubusercontent.com/assets/19630825/21466213/fef06dea-c9fb-11e6-93dc-0818f6acaedc.gif)

Thank u.

**Comment by egamma** [comment]
Duplicates #17564
