### ISSUE TITLE
The open detected link keybinding is being overwritten by navigate accessible buffer

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#178059]
This makes the terminal links feature unavailable to screen reader users via the previously announced keybinding. So they would need to go via the command palette for an inconvenient option or know how to configure keybindings to get the convenience back.

I know we discussed this at some point but I think we should only bind it when the accessible buffer is up.

**Comment by meganrogge** [comment]
> I think we should only bind it when the accessible buffer is up.

Sighted users trigger `Open detected link` when they see there's a link in the terminal output they'd like to open.

Screen reader users do not get this information in the normal terminal buffer, so I'm not sure why they'd use this command before reviewing the output - via the accessible terminal buffer.

**Comment by Tyriar** [comment]
Before you could run a server, assume it outputs a link to localhost or something and open it via ctrl+shift+o. Links are one of the most powerful features in the terminal so we shouldn't hide it for a subset of users.

This is what we landed on only a couple of months ago and changing that would be very frustrating as a user who has become used to it: https://code.visualstudio.com/updates/v1_75#_new-default-keybindings

**Comment by Tyriar** [comment]
Not released yet but verified in OSS since it's a simple fix.
