### ISSUE TITLE
Git - Missing remote causes pull error, while pull actually worked

### ISSUE THREAD

**Issue by digitarald** [microsoft/vscode#178024]
Type: <b>Bug</b>

One of my remotes, probably added during a PR review, no longer exists and causes modal errors that indicate the fetch failed; while actually all other remotes got fetched.

Maybe this can be more fine-grained or just a notification when the remote isn't used atm, as it is easy to pull in remotes over time that later vanish?

![image](https://user-images.githubusercontent.com/8599/226953922-0306a07a-5010-4e45-bf96-c18de1352db0.png)

```
> git fetch --all --prune
ERROR: Repository not found.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
error: could not fetch bytemain
From github.com:mjbvz/vscode
 * [new branch]              appalling-goose      -> mjbvz/appalling-goose
 * [new branch]              automatic-koi        -> mjbvz/automatic-koi
 * [new branch]              corresponding-vicuna -> mjbvz/corresponding-vicuna
 * [new branch]              gothic-cobra         -> mjbvz/gothic-cobra
 + afc9daf636d...a1e193d3196 hilarious-jay        -> mjbvz/hilarious-jay  (forced update)
 * [new branch]              obnoxious-koala      -> mjbvz/obnoxious-koala
 * [new branch]              obnoxious-mink       -> mjbvz/obnoxious-mink
 * [new branch]              plain-whippet        -> mjbvz/plain-whippet
 * [new branch]              selective-chinchilla -> mjbvz/selective-chinchilla
 * [new branch]              slimy-butterfly      -> mjbvz/slimy-butterfly
 * [new branch]              special-panther      -> mjbvz/special-panther
 * [new branch]              uptight-firefly      -> mjbvz/uptight-firefly
 * [new branch]              xenacious-cockroach  -> mjbvz/xenacious-cockroach
 * [new branch]              youthful-harrier     -> mjbvz/youthful-harrier
From github.com:gjsjohnmurray/vscode
 - [deleted]                 (none)     -> gjsjohnmurray/fix-174690v2
   2e34c9a884d..c9594ae65cc  main       -> gjsjohnmurray/main
Auto packing the repository in background for optimum performance.
See "git help gc" for manual housekeeping.
```

VS Code version: Code - Insiders 1.77.0-insider (833ac685084e2028b09753392b82c641c7025bbc, 2023-03-21T05:26:40.905Z)
OS version: Darwin x64 22.3.0
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|4, 5, 4|
|Memory (System)|64.00GB (1.80GB free)|
|Process Argv|--enable-proposed-api donjayamanne.kusto --log trace --crash-reporter-id 4cf0a6f0-aaf8-4da3-9b2b-81f6c639c12b|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by lszomoru** [comment]
@digitarald, was this really a pull or a "Fetch from All Remotes" as that it's what it looks like from the git command being run?

**Comment by lszomoru** [comment]
Closing as I was unable to repro this one.
