### ISSUE TITLE
Convert width of space indentation

### ISSUE THREAD

**Issue by OliverJAsh** [microsoft/vscode#17802]
I frequently receive content indented using 2 spaces and need to change it to 4. The steps for converting to one space indentation width to another are as so:

1. Detect indentation from contents
2. Convert space indentations to tabs
3. Change tab indentation width to desired, e.g. 4 ("indent using tabs" command)
4. Convert tab indentations to spaces

Could we possibly make this a one command process?

**Comment by isidorn** [comment]
You should also be able to do this via
1. Indent using spaces - choose 4
2. Format document

While designing this feature it was difficult to find a balance between making it easy to use and supporting all the scenarios people expect from indentation.

**Comment by BirkhoffLee** [comment]
Where's the format document option?

**Comment by OliverJAsh** [comment]
The format commands are only available for languages with supported formatters. It would be nice if this worked independent of formatters.
