### ISSUE TITLE
Improve terminal find behavior when there are more than 1000 results

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#178017]
Currently find in the terminal behaves a little strangely when there are more than 1000 results. The result count may not show up at all or it may say "0 of -1":

![image](https://user-images.githubusercontent.com/2193314/226929324-eede87fc-c4b9-4882-9b65-8c1e645ee717.png)
![image](https://user-images.githubusercontent.com/2193314/226929345-d0a1ef1d-3dc6-4690-ab1a-1422352a1614.png)

We should behave more like the editor does:

<img width="335" alt="image" src="https://user-images.githubusercontent.com/2193314/226929505-b6184b7b-4db8-49d0-b71a-47fab43c532e.png">

**Comment by Tyriar** [comment]
Upstream: https://github.com/xtermjs/xterm.js/issues/4444

**Comment by jeanp413** [comment]
Created a PR upstream https://github.com/xtermjs/xterm.js/pull/4504

**Comment by jeanp413** [comment]
Continuation PR https://github.com/microsoft/vscode/pull/182917
