### ISSUE TITLE
code off screen isn't rendered when scrolled to

### ISSUE THREAD

**Issue by TylerLeonhardt** [microsoft/vscode#178072]
Does this issue occur when all extensions are disabled?: Yes/No

Vërsïøñ: 1.77.0-insider
Çømmït: a5bd844beddef8ca5f9ccfdb1bb7b3b4f8e5204e
Ðætë: 2023-03-22T10:40:07.604Z
ßrøwsër: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36 Edg/112.0.0.0

Steps to Reproduce:
1. go to https://insiders.vscode.dev/github.com/microsoft/vscode/blob/700f9aca908288cd25ffeb8b934e156aac773daa/.vscode/notebooks/my-endgame.github-issues
2. scroll to the right on a cell using the scroll bar

See this:
<img width="427" alt="image" src="https://user-images.githubusercontent.com/2644648/227035196-5e958863-8528-415d-a563-98bd056cde39.png">

and then changing focus seems to cause the missing text to show:
<img width="367" alt="image" src="https://user-images.githubusercontent.com/2644648/227035304-211a038f-4b29-407d-ac3f-fce413a59c30.png">

**Comment by TylerLeonhardt** [comment]
<img width="781" alt="image" src="https://user-images.githubusercontent.com/2644648/227039738-80cffccc-bf68-4f51-b5da-f58a7cf7e712.png">
looks like this is also happening in the text editor

**Comment by hediet** [comment]
Cannot reproduce:

![chrome_JCG38jE2PQ](https://user-images.githubusercontent.com/2931520/227912630-62043f9f-f17f-42ae-bc2c-0b8a00566204.gif)

**Comment by TylerLeonhardt** [comment]
Neither can I 🤷
