### ISSUE TITLE
Can't focus on the terminal view when the terminal accessible buffer is enabled

### ISSUE THREAD

**Issue by amunger** [microsoft/vscode#178055]
1. Focus the terminal and press shift+tab to open terminal accessible buffer
2. Focus somewhere else
3. run `Focus on Terminal View`
:bug: focus does not change

also found that pressing `alt+f1` from the accessible buffer and then escape to close the help menu will lose terminal focus.

**Comment by meganrogge** [comment]
No, I tested in oss and the first bug you described still reproduces. We should focus the terminal editor when you run `Focus on terminal view`
