### ISSUE TITLE
Navigate accessible buffer should preview the position similar to go to symbol in the editor

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#178056]
Currently when you use navigate accessible buffer you get a quick pick with the options, I expected changing these to scroll to the position without accepting it, and escape to revert to the original scroll position.

**Comment by Tyriar** [comment]
As part of this, providing ~1/3 of the viewport of context above would also be good

**Comment by meganrogge** [comment]
Oh I understand now - you mean on change of the active quick pick item, reveal the line and on enter, focus that line (as it already does)

**Comment by Tyriar** [comment]
Yep

**Comment by roblourens** [comment]
Works but I opened https://github.com/microsoft/vscode/issues/180899
