### ISSUE TITLE
code tunnel access: only connect to existing tunnel process when quality is the same

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode#178089]
I run a tunnel on my VS Code insiders but I also want to run a different one from Code OSS for testing. 
I use different tunnel names.

This no longer works as the second tunnel process attaches to the first process.

We should use separate `.vscode-cli` folders per quality. `.vscode-cli, `.vscode-cli-insiders`, `.vscode-cli-oss-dev`, ..

The name of the data folder should come from product.json, see `dataFolderName`, `serverDataFolderName`

https://github.com/microsoft/vscode/blob/de2660f51909af2289fe805380a90f87a8d31f2f/product.json#L13

**Comment by aeschli** [comment]
Thanks @connor4312!

Note that we still use the same data folder `.vscode-cli`. The `code_tunnel.json` file is overwritten by each quality,

A `code_tunnel.json` per quality would be a possibility, but I still think we should follow the example of VS Code and keep qualities as separate products, each with its own data folder.

Also we could think of putting the `vscode-cli folder` inside the vscode data folder
`.vscode-insiders/.vscode-cli`

**Comment by aeschli** [comment]
Verified that I can run two tunnels now, from oss and from insiders, but the two are reusing the same name and tunnel id (and auth?!) from `code_tunnel.json`

I created https://github.com/microsoft/vscode/issues/181017

**Comment by connor4312** [comment]
Thanks, yea. Having separate data dirs would solve that
