### ISSUE TITLE
Missing Nested folder from explorer view.

### ISSUE THREAD

**Issue by diegonzls** [microsoft/vscode#178054]
Type: <b>Bug</b>

Having a folder with this structure:

ParentFolder
 -->  NestedFolder

When opening a folder which contains a nested folder called "**CVS**" then the **CVS** folder is missing from the explorer window.

It only happends when the NestedFolder is called **CVS** Upper case and nothing more.

![2023-03-22_18h23_01](https://user-images.githubusercontent.com/773913/227001338-8d57e013-c9a4-4bd9-b884-f75dd8088d13.gif)

VS Code version: Code 1.76.2 (ee2b180d582a7f601fa6ecfdad8d9fd269ab1884, 2023-03-14T17:55:54.936Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz (8 x 2995)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.71GB (3.04GB free)|
|Process Argv|. --crash-reporter-id 19c929b2-ea4f-4568-930b-f05f480f72b3|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (24)</summary>

Extension|Author (truncated)|Version
---|---|---
eml|lei|0.4.0
azure-pipelines|ms-|1.208.0
vscode-docker|ms-|1.24.0
csharp|ms-|1.25.4
vscode-kubernetes-tools|ms-|1.3.11
isort|ms-|2022.8.0
python|ms-|2023.4.1
vscode-pylance|ms-|2023.3.20
jupyter|ms-|2023.2.1200692131
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-slideshow|ms-|0.1.5
remote-containers|ms-|0.282.0
remote-wsl|ms-|0.76.1
azure-account|ms-|0.11.3
powershell|ms-|2023.2.1
java|red|1.16.0
vscode-yaml|red|1.12.2
intellicode-api-usage-examples|Vis|0.2.7
vscodeintellicode|Vis|1.2.30
vscode-java-debug|vsc|0.49.0
vscode-java-dependency|vsc|0.21.1
vscode-java-pack|vsc|0.25.9
vscode-java-test|vsc|0.38.1
vscode-maven|vsc|0.40.4

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscoreces:30445986
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
pynewvextcfv2:30681851
azure-dev_surveyone:30548225
vscccc:30610679
pyindex848:30662994
nodejswelcome1:30587005
2e4cg342:30602488
pyind779:30671433
f6dab269:30613381
vscrp:30673768
pythonsymbol12:30671437
vsctsb:30677850
azdwalk:30687957
pythonms35:30686772

```

</details>

**Comment by aweshchoudhary** [comment]
Yes, I also tried to create the **UPPERCASE** letter folder and it disappears but it exists in the file explorer.
I also try to refresh the folder tree by clicking the refresh button.
I also try to restart my vs code but it didn't show the **UPPERCASE** Folder.
My Operating System is Linux Mint
Using The Latest Version Of VS Code

**Comment by gjsjohnmurray** [comment]
Open the Settings Editor from Command Palette or via the gearwheel menu. Search for `files.exclude` and remove the default entry `**/CVS`

**Comment by diegonzls** [comment]
@gjsjohnmurray That did the trick, thank you.

I was wondering why **/CVS is a default value on that list. I am familiar with the other default values but no for **CVS**.
