### ISSUE TITLE
No terminal access

### ISSUE THREAD

**Issue by JoeyHernandez92** [microsoft/vscode#178087]
Type: <b>Bug</b>

once wal terminal opened, no ability to type commands of any kind and no way of running programs

VS Code version: Code 1.76.2 (ee2b180d582a7f601fa6ecfdad8d9fd269ab1884, 2023-03-14T17:55:54.936Z)
OS version: Windows_NT x64 10.0.22624
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-1035G7 CPU @ 1.20GHz (8 x 1498)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|7.60GB (0.83GB free)|
|Process Argv|--crash-reporter-id 521f2664-61a5-47c9-bd3e-6fff5190ad38|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (55)</summary>

Extension|Author (truncated)|Version
---|---|---
jdk-setter|And|1.0.1
vscode-django|bat|1.10.0
CPP-Compiler|ble|1.5.5
doxdocgen|csc|1.4.0
c-cpp-compile-run|dan|1.0.44
jshint|dba|0.11.0
phptools-vscode|DEV|1.31.12821
profiler-php-vscode|DEV|1.31.12821
vscode-terminal-for-ubuntu|Doc|0.0.2
python-environment-manager|don|1.0.4
python-extension-pack|don|1.7.0
vscode-javac|geo|0.2.45
classroom|git|0.0.3
vscode-pull-request-github|Git|0.60.0
img-contextual|gre|0.2.8
better-cpp-syntax|jef|1.17.2
vsc-python-indent|Kev|1.18.0
wsl-path|kgr|0.1.0
vscode-github|Kni|0.30.7
vscode-wsl-workspacefolder|lfu|1.1.2
vscode-docker|ms-|1.24.0
csharp|ms-|1.25.4
isort|ms-|2022.8.0
python|ms-|2023.4.1
vscode-pylance|ms-|2023.3.30
jupyter|ms-|2023.2.1200692131
jupyter-keymap|ms-|1.1.0
jupyter-renderers|ms-|1.0.15
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-slideshow|ms-|0.1.5
remote-containers|ms-|0.282.0
remote-ssh|ms-|0.98.0
remote-wsl|ms-|0.76.1
vscode-remote-extensionpack|ms-|0.24.0
cmake-tools|ms-|1.13.45
cpptools|ms-|1.14.5
cpptools-extension-pack|ms-|1.3.0
makefile-tools|ms-|0.6.0
remote-explorer|ms-|0.2.0
remote-server|ms-|1.0.0
vsliveshare|ms-|1.0.5834
autodocstring|njp|0.6.1
java|red|1.16.0
sonarlint-vscode|Son|3.16.0
cmake|twx|0.0.17
intellicode-api-usage-examples|Vis|0.2.7
vscodeintellicode|Vis|1.2.30
vscode-java-debug|vsc|0.49.0
vscode-java-dependency|vsc|0.21.1
vscode-java-pack|vsc|0.25.9
vscode-java-test|vsc|0.38.1
vscode-maven|vsc|0.40.4
vscode-spring-initializr|vsc|0.11.2
jinja|who|0.0.8
json|Zai|2.0.2

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vscaat:30438848
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
pynewvextcfv2:30681851
azure-dev_surveyone:30548225
pyindex848:30662994
nodejswelcome1cf:30587006
3biah626:30602489
pyind779:30671433
89544117:30613380
pythonsymbol12:30671437
a9j8j154:30646983
showlangstatbar:30672706
vsccsb:30677849
pythonb192cf:30669361
functionswalk:30687959
pythonms35cf:30686773

```

</details>

**Comment by meganrogge** [comment]
It looks like your report is missing some important information, See [this wiki page](https://github.com/microsoft/vscode/wiki/Terminal-Issues) for more info on how to report actionable terminal issues.
/label info-needed terminal
