### ISSUE TITLE
Error: Debug adapter process has terminated unexpectedly

### ISSUE THREAD

**Issue by shashi-netra** [Microsoft/vscode#17804]
- VSCode Version:V 1.8.1
- OS Version: macOS Sierra 10.12.2

> "Error: Debug adapter process has terminated unexpectedly"

Steps to Reproduce:

1. Trying to build any file gives me the above error. It was working fine earlier.
2. I have the following extensions installed: MagicPython,Python, Python for VSCode and SublimeText Keymap.

**Comment by egamma** [comment]
@shashi-netra 

>Trying to build any file gives me the above error. It was working fine earlier.

Can you explain what you mean by `build any file`. The error message comes from a debugger, so do you see the message when debugging?

What files are you working on when this happens? From the list of extensions you have installed it looks like you are using VS Code for Python development?

**Comment by shashi-netra** [comment]
I get the error when I try to run any python script even a simple one as shown in this screencast. I see the error message in a message box at the top.
http://g.recordit.co/O0VSOnZzJl.gif

**Comment by egamma** [comment]
@shashi-netra thanks for the recording it helps to clarify the issue. Python debugging is contributed by the Python extension and I'm moving the issue to corresponding issues repository.

**Comment by egamma** [comment]
This issue was moved to DonJayamanne/pythonVSCode#603
