### ISSUE TITLE
Python console prints

### ISSUE THREAD

**Issue by tamirgz** [Microsoft/vscode#17803]
When running python program that prints to the console and also uses table printing module, the output is cut out and does not display the whole line.

- VSCode Version: Code 1.8.1 (ee428b0eead68bf0fb99ab5fdc4439be227b6281, 2016-12-19T14:49:23.350Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

|Extension|Author|Version|
|---|---|---|
|python|donjayamanne|0.5.5|
|beautify|HookyQR|0.6.2|
|MagicPython|magicstack|1.0.3|
|cpptools|ms-vscode|0.9.3|
|sublime-keybindings|ms-vscode|1.8.1|
|python|tht13|0.2.3|

---

Steps to Reproduce:

1.
2.

**Comment by egamma** [comment]
@tamirgz this looks like an issue with the python extension, please file it against the corresponding repository https://github.com/DonJayamanne/pythonVSCode/issues
