### ISSUE TITLE
Drag and drop text from another app

### ISSUE THREAD

**Issue by sitnikovme** [Microsoft/vscode#17800]
- VSCode Version: Version 1.8.1 (1.8.1)
- OS Version: os x 10.11.6 (15G1108)

Steps to Reproduce:

1. Drag and drop text from some app (e.g. Google Chrome browser) to some file in VSCode

Expected:
Dragged text will be inserted into file opened in VSCode

Actual:
Nothing happens

**Comment by egamma** [comment]
There is no support for Drag&Drop.  
Duplicates #1046.
