### ISSUE TITLE
Cython extension issue, under Ubuntu only.

### ISSUE THREAD

**Issue by lalvarezguillen** [Microsoft/vscode#17817]
- VSCode Version: Code 1.8.1 (ee428b0eead68bf0fb99ab5fdc4439be227b6281, 2016-12-19T14:41:20.664Z)
- OS Version: Linux x64 4.4.0-57-generic
- Extensions:

|Extension|Author|Version|
|---|---|---|
|python|donjayamanne|0.5.5|
|Go|lukehoban|0.6.51|
|cpptools|ms-vscode|0.9.3|
|cython|tcwalther|0.1.0|

---

Steps to Reproduce:
1. Open Visual Studio Code
2. Make sure the extension tcwalther.cython is installed and activated
3. Create a new Cython file (.pyx)
4. Insert some basic text that complies with Cython's syntax, eg: "int"

Expected output:
The text that complies with Cython's syntax should be highlighted

Actual output:
Under this environment(see system, VSC and extension details above), with tcwalther.cython extension activated (yes, seriously), the text is not highlighted.

Notes:
I've tried those steps in a Windows7 environment, and it works fine.

**Comment by egamma** [comment]
@lalvarezguillen this looks like an issue of the cython extension, please file the extension against this extension.
