### ISSUE TITLE
Code editor becomes unresponsive after updating some extension. Reload works after trying to close window. Then dialog becomes visible.

### ISSUE THREAD

**Issue by ph-dev-2016** [Microsoft/vscode#17811]
- VSCode Version: Code 1.8.1 (ee428b0eead68bf0fb99ab5fdc4439be227b6281, 2016-12-19T14:49:23.350Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions:

|Extension|Author|Version|
|---|---|---|
|html-snippets|abusaidm|0.0.18|
|django-html|bibhasdn|1.2.0|
|githistory|donjayamanne|0.1.4|
|jquerysnippets|donjayamanne|0.0.1|
|python|donjayamanne|0.5.5|
|xml|DotJoshJohnson|1.6.1|
|EditorConfig|EditorConfig|0.3.4|
|vscode-npm-script|eg2|0.1.5|
|CppSnippets|hars|0.0.5|
|format-indent|Kasik96|1.3.0|
|vscode-JS-CSS-HTML-formatter|lonefy|0.2.2|
|cpptools|ms-vscode|0.9.3|
|csharp|ms-vscode|1.6.2|
|debugger-for-chrome|msjsdiag|2.4.1|
|sass-indented|robinbentley|1.3.0|
|Angular2|UVBrain|0.3.5|
|cordova-tools|vsmobile|1.2.4|
|JavaScriptSnippets|xabikos|1.2.0|
|ReactSnippets|xabikos|1.2.0|

---

Steps to Reproduce:

1. Code shows that some extension has an upgrade pending. Press Upgrade button
2. Once this is done, Code shows Reload button next to the upgraded extension.
3. Press Reload button -> nothing happens.
4. Click x-button to close Code from the top right corner (maybe restarting it also reloads the extension)
   -> now the extension's reload "are you sure?" dialog becomes visible and I can reload the extension. No need to restart whole program.
So is the dialog behind some other windows or why wasn't it shown first?

**Comment by joaomoreno** [comment]
Do you mind recording a screencast?
