### ISSUE TITLE
Update the issue guidelines with the new support for disabling extensions

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode#17816]
Please update https://github.com/Microsoft/vscode/blob/master/CONTRIBUTING.md with the new support for updating extensions. Currently we only describe the `--disable-extensions` command line option.

![image](https://cloud.githubusercontent.com/assets/172399/21472074/f7dabe20-cac8-11e6-941d-e8b337400138.png)

I suggest to add a screenshot/animated gif

![image](https://cloud.githubusercontent.com/assets/172399/21472069/c5da26ea-cac8-11e6-8e52-d83f5ce5da22.png)

**Comment by waderyan** [comment]
Solved with PR https://github.com/Microsoft/vscode/pull/18119

**Comment by egamma** [comment]
Issue was closed through PR
