### ISSUE TITLE
the file is not displayed in the editor because it is either binary or uses an unsupported code

### ISSUE THREAD

**Issue by JustLok** [microsoft/vscode#178146]
When i try to open this file it just says this 
![sdgdGGFGGFFGDGDFA](https://user-images.githubusercontent.com/128099086/227262329-1167191c-e17b-4bf1-861a-6445f6b7fa96.png)
and when i open it this is what i see 
![FGDfgdfgeRGFwregfWE](https://user-images.githubusercontent.com/128099086/227262397-0f390a53-c41b-46ea-afd9-38f9da15ca31.png)

**Comment by lramos15** [comment]
This means the file you're opening is not a text file it is encoded in some way. Where did you get this file from / what is it?
