### ISSUE TITLE
VS Code sources build task stops after restarting VS Code

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#178115]
Steps to Reproduce:

1. In VS Code Development setup, run the build task using command cmd+shift+b
2. It builds VS Code core and extensions
3. Restart VS Code

Following is shown in the build task terminal 

```
[deemon] Attached to running build daemon. Press Ctrl-C to detach, Ctrl-D to kill.
```

**Comment by joaomoreno** [comment]
Not sure I understand. I added that log message for clarity since new team members were surprised that the build was still running after restarting VS Code.

The message says that it attached to the running build daemon... but the issue's title says the build task stops... What is the issue?

**Comment by sandy081** [comment]
Ok! My bad, I misinterpreted that I have to kill and restart. Closing.
