### ISSUE TITLE
Bug in multi-cursor text selection when expanding selection by word

### ISSUE THREAD

**Issue by criddell** [microsoft/vscode#178149]
Type: <b>Bug</b>

1. Paste the following into a text buffer:

DebugUtils.cpp(87) : atlTraceGeneral - 0 - line from (0, 0, 0) to (18.625, 0, 0)
DebugUtils.cpp(87) : atlTraceGeneral - 1 - line from (18.625, 0, 0) to (18.625, 0, 0.1875)
DebugUtils.cpp(87) : atlTraceGeneral - 2 - line from (18.625, 0, 0.1875) to (20.3125, 0, 0.1875)
DebugUtils.cpp(87) : atlTraceGeneral - 3 - line from (20.3125, 0, 0.1875) to (20.3125, 0, 1.9162)
DebugUtils.cpp(87) : atlTraceGeneral - 4 - line from (20.3125, 0, 1.9162) to (18.625, 0, 1.9162)
DebugUtils.cpp(87) : atlTraceGeneral - 5 - arc r=0.375, from (19, 0, 2.2912) to (18.625, 0, 2.6662), center=(18.625, 0, 2.2912)
DebugUtils.cpp(87) : atlTraceGeneral - 6 - line from (18.625, 0, 2.6662) to (18.625, 0, 3.0412)
DebugUtils.cpp(87) : atlTraceGeneral - 7 - line from (18.625, 0, 3.0412) to (18.375, 0, 3.0412)
DebugUtils.cpp(87) : atlTraceGeneral - 8 - line from (18.375, 0, 3.0412) to (18, 0, 2.2912)
DebugUtils.cpp(87) : atlTraceGeneral - 9 - arc r=0.375, from (18, 0, 2.2912) to (17.625, 0, 1.9162), center=(17.625, 0, 2.2912)
DebugUtils.cpp(87) : atlTraceGeneral - 10 - line from (17.625, 0, 1.9162) to (0, 0, 1.9162)
DebugUtils.cpp(87) : atlTraceGeneral - 11 - line from (0, 0, 1.9162) to (0, 0, 0)

2. Select the word *DebugUtils* and then type ctrl-shift-L to select all instances of that word.

3. Pres ctrl-shift-right arrow and the initial cursor will correctly highlight words but all of the other instances do not.

4. Pres escape to cancel the operation and once again select the word *DebugUtils* and then type ctrl-shift-L to select all instances.

5. This time type shift-right arrow to expand the selection one letter at a time and notice that all of the cursors are highlighting.

I believe the behavior in step 3 is broken and in step 5 is working.

VS Code version: Code 1.76.2 (ee2b180d582a7f601fa6ecfdad8d9fd269ab1884, 2023-03-14T17:55:54.936Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) W-2255 CPU @ 3.70GHz (20 x 3696)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|71.69GB (43.14GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (26)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-better-align|cho|1.4.1
doxdocgen|csc|1.4.0
vscode-autohotkey-plus|cwe|2.7.1
vscode-eslint|dba|2.4.0
better-cpp-syntax|jef|1.17.2
svn-scm|joh|2.15.7
vscode-format-context-menu|lac|1.0.4
isort|ms-|2022.8.0
python|ms-|2023.4.1
vscode-pylance|ms-|2023.3.30
jupyter|ms-|2023.2.1200692131
jupyter-keymap|ms-|1.1.0
jupyter-renderers|ms-|1.0.15
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-slideshow|ms-|0.1.5
remote-containers|ms-|0.282.0
remote-ssh|ms-|0.98.0
remote-ssh-edit|ms-|0.84.0
remote-wsl|ms-|0.76.1
cmake-tools|ms-|1.13.45
cpptools|ms-|1.14.5
cpptools-extension-pack|ms-|1.3.0
powershell|ms-|2023.2.1
remote-explorer|ms-|0.2.0
cmake|twx|0.0.17
rc-script|wil|1.0.0

(1 theme extensions excluded)

</details>

**Comment by alexdima** [comment]
I cannot reproduce. I believe that perhaps one of your installed extensions is overriding `ctrl+shift+right arrow` or perhaps you have a customization in your `keybindings.json` file. 
Does this reproduce when disabling all extensions? Press `F1` and then choose `Developer: Reload Window with Extensions Disabled`

![Kapture 2020-07-20 at 15 28 23](https://user-images.githubusercontent.com/5047891/87943040-c3b02a80-ca9d-11ea-847d-5f850fae8f05.gif)

**Comment by criddell** [comment]
It still happens after reloading without extensions. My keybindings.json file is the default file with nothing in the list.

If I try the exact same sequence in Sublime Text 3 (using alt-f3 rather than ctrl-alt-L to select all occurrances), it works.

**Comment by alexdima** [comment]
Let's first try to find out what command executes on your machine, with your settings and your keybindings when pressing `ctrl+shift+right arrow`. Could you please [try the following](https://github.com/microsoft/vscode/wiki/Keybinding-Issues#basic-troubleshooting):

* Run the command `Developer: Toggle Keyboard Shortcuts Troubleshooting`
* This will activate logging of dispatched keyboard shortcuts and will open an output panel with the corresponding log file.
* Press exactly the keybinding you desire.
* check what VS Code detects and what command is invoked.

If you are having trouble understanding the output, please feel free to paste here and I can try to help.

**Comment by criddell** [comment]
I really appreciate your help with this. Below is the log. I removed the timestamps and the duplicate events.

<pre>
[warning] Via 'product.json#extensionEnabledApiProposals' extension 'ms-vscode.vscode-selfhost-test-provider' wants API proposal 'testContinuousRun' but that proposal DOES NOT EXIST. Likely, the proposal has been finalized (check 'vscode.d.ts') or was abandoned.
[warning] Via 'product.json#extensionEnabledApiProposals' extension 'ms-vscode.remote-repositories' wants API proposal 'contribEditorGutterMenu' but that proposal DOES NOT EXIST. Likely, the proposal has been finalized (check 'vscode.d.ts') or was abandoned.
[warning] Via 'product.json#extensionEnabledApiProposals' extension 'github.vscode-pull-request-github' wants API proposal 'contribEditorGutterMenu' but that proposal DOES NOT EXIST. Likely, the proposal has been finalized (check 'vscode.d.ts') or was abandoned.
[warning] Via 'product.json#extensionEnabledApiProposals' extension 'ms-toolsai.jupyter' wants API proposal 'notebookControllerKind' but that proposal DOES NOT EXIST. Likely, the proposal has been finalized (check 'vscode.d.ts') or was abandoned.
[warning] [twxs.cmake]: Cannot register 'cmake.cmakePath'. This property is already registered.
[info] [perf] Render performance baseline is 32ms
[warning] Via 'product.json#extensionEnabledApiProposals' extension 'ms-vscode.vscode-selfhost-test-provider' wants API proposal 'testContinuousRun' but that proposal DOES NOT EXIST. Likely, the proposal has been finalized (check 'vscode.d.ts') or was abandoned.
[warning] Via 'product.json#extensionEnabledApiProposals' extension 'ms-vscode.remote-repositories' wants API proposal 'contribEditorGutterMenu' but that proposal DOES NOT EXIST. Likely, the proposal has been finalized (check 'vscode.d.ts') or was abandoned.
[warning] Via 'product.json#extensionEnabledApiProposals' extension 'github.vscode-pull-request-github' wants API proposal 'contribEditorGutterMenu' but that proposal DOES NOT EXIST. Likely, the proposal has been finalized (check 'vscode.d.ts') or was abandoned.
[warning] Via 'product.json#extensionEnabledApiProposals' extension 'ms-toolsai.jupyter' wants API proposal 'notebookControllerKind' but that proposal DOES NOT EXIST. Likely, the proposal has been finalized (check 'vscode.d.ts') or was abandoned.
[info] [perf] Render performance baseline is 31ms
[info] [KeybindingService]: / Soft dispatching keyboard event
[info] [KeybindingService]: \ Keyboard event cannot be dispatched
[info] [KeybindingService]: / Received  keydown event - modifiers: [shift], code: ShiftLeft, keyCode: 16, key: Shift
[info] [KeybindingService]: | Converted keydown event - modifiers: [shift], code: ShiftLeft, keyCode: 4 ('Shift')
[info] [KeybindingService]: \ Keyboard event cannot be dispatched in keydown phase.
[info] [KeybindingService]: / Soft dispatching keyboard event
[info] [KeybindingService]: \ Keyboard event cannot be dispatched
[info] [KeybindingService]: / Received  keydown event - modifiers: [ctrl,shift], code: ControlLeft, keyCode: 17, key: Control
[info] [KeybindingService]: | Converted keydown event - modifiers: [ctrl,shift], code: ControlLeft, keyCode: 5 ('Ctrl')
[info] [KeybindingService]: \ Keyboard event cannot be dispatched in keydown phase.
[info] [KeybindingService]: / Soft dispatching keyboard event
[info] [KeybindingService]: \ Keyboard event cannot be dispatched
[info] [KeybindingService]: / Received  keydown event - modifiers: [ctrl,shift], code: ControlLeft, keyCode: 17, key: Control
[info] [KeybindingService]: | Converted keydown event - modifiers: [ctrl,shift], code: ControlLeft, keyCode: 5 ('Ctrl')
[info] [KeybindingService]: \ Keyboard event cannot be dispatched in keydown phase.
[info] [KeybindingService]: / Soft dispatching keyboard event
[info] [KeybindingService]: | Resolving ctrl+shift+L
[info] [KeybindingService]: \ From 3 keybinding entries, matched editor.action.selectHighlights, when: editorFocus, source: built-in.
[info] [KeybindingService]: / Received  keydown event - modifiers: [ctrl,shift], code: KeyL, keyCode: 76, key: L
[info] [KeybindingService]: | Converted keydown event - modifiers: [ctrl,shift], code: KeyL, keyCode: 42 ('L')
[info] [KeybindingService]: | Resolving ctrl+shift+L
[info] [KeybindingService]: \ From 3 keybinding entries, matched editor.action.selectHighlights, when: editorFocus, source: built-in.
[info] [KeybindingService]: + Invoking command editor.action.selectHighlights.
[info] [KeybindingService]: + Ignoring single modifier shift due to it being pressed together with other keys.
[info] [KeybindingService]: / Soft dispatching keyboard event
[info] [KeybindingService]: \ Keyboard event cannot be dispatched
[info] [KeybindingService]: / Received  keydown event - modifiers: [ctrl], code: ControlLeft, keyCode: 17, key: Control
[info] [KeybindingService]: | Converted keydown event - modifiers: [ctrl], code: ControlLeft, keyCode: 5 ('Ctrl')
[info] [KeybindingService]: \ Keyboard event cannot be dispatched in keydown phase.
[info] [KeybindingService]: / Soft dispatching keyboard event
[info] [KeybindingService]: \ Keyboard event cannot be dispatched
[info] [KeybindingService]: / Received  keydown event - modifiers: [ctrl,shift], code: ShiftLeft, keyCode: 16, key: Shift
[info] [KeybindingService]: | Converted keydown event - modifiers: [ctrl,shift], code: ShiftLeft, keyCode: 4 ('Shift')
[info] [KeybindingService]: \ Keyboard event cannot be dispatched in keydown phase.
[info] [KeybindingService]: / Soft dispatching keyboard event
[info] [KeybindingService]: \ Keyboard event cannot be dispatched
[info] [KeybindingService]: / Received  keydown event - modifiers: [ctrl,shift], code: ShiftLeft, keyCode: 16, key: Shift
[info] [KeybindingService]: | Converted keydown event - modifiers: [ctrl,shift], code: ShiftLeft, keyCode: 4 ('Shift')
[info] [KeybindingService]: \ Keyboard event cannot be dispatched in keydown phase.
[info] [KeybindingService]: / Soft dispatching keyboard event
**[info] [KeybindingService]: | Resolving ctrl+shift+RightArrow
[info] [KeybindingService]: \ From 1 keybinding entries, no when clauses matched the context.
[info] [KeybindingService]: / Received  keydown event - modifiers: [ctrl,shift], code: ArrowRight, keyCode: 39, key: ArrowRight
[info] [KeybindingService]: | Converted keydown event - modifiers: [ctrl,shift], code: ArrowRight, keyCode: 17 ('RightArrow')
[info] [KeybindingService]: | Resolving ctrl+shift+RightArrow
[info] [KeybindingService]: \ From 1 keybinding entries, no when clauses matched the context.
[info] [KeybindingService]: + Ignoring single modifier shift due to it being pressed together with other keys.
[info] [KeybindingService]: / Soft dispatching keyboard event
[info] [KeybindingService]: \ Keyboard event cannot be dispatched
[info] [KeybindingService]: / Received  keydown event - modifiers: [ctrl], code: ControlRight, keyCode: 17, key: Control
[info] [KeybindingService]: | Converted keydown event - modifiers: [ctrl], code: ControlRight, keyCode: 5 ('Ctrl')
[info] [KeybindingService]: \ Keyboard event cannot be dispatched in keydown phase.
[info] [KeybindingService]: / Soft dispatching keyboard event**
</pre>

Is this the key part? 

    + Ignoring single modifier shift due to it being pressed together with other keys.

It looks like it's dispatching ctrl-right arrow instead of ctrl-shift-right arrow.

**Comment by alexdima** [comment]
The relevant part is:
```
[info] [KeybindingService]: / Received  keydown event - modifiers: [ctrl,shift], code: ArrowRight, keyCode: 39, key: ArrowRight
[info] [KeybindingService]: | Converted keydown event - modifiers: [ctrl,shift], code: ArrowRight, keyCode: 17 ('RightArrow')
[info] [KeybindingService]: | Resolving ctrl+shift+RightArrow
[info] [KeybindingService]: \ From 1 keybinding entries, no when clauses matched the context.
```

Here is the default keybinding we ship with:
```
{ "key": "ctrl+shift+right",      "command": "cursorWordEndRightSelect",
                                     "when": "textInputFocus && !accessibilityModeEnabled" },
```

Do you by any chance have accessibility mode turned on? Are you using a screen reader to operate VS Code? If not, could you try configuring `""editor.accessibilitySupport": "off"`?

**Comment by criddell** [comment]
I do have accessibility mode on. I turned it on to fix some other problem and now I don't recall what that was. Turning it off does fix this problem so thank you for your help tracking it down. I'm going to work with it accessibility mode off and maybe I'll encounter the first problem again and will have to find a different solution.

Do you happen to know why multiple cursor word select is incompatible with accessibility mode? Single cursor word select works just fine with accessibility mode enabled.

**Comment by criddell** [comment]
I'm closing this because @alexdima provided me with a solution. Multiple-cursor word select is not compatible with accessibility mode. Turning accessibility mode off solves this problem.
