### ISSUE TITLE
Sticky run button doesn't appear in GitHub issues notebooks

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode#178169]
In ipynb files the run button renders at the top of the cell even if the top of the cell is outside the current viewport. This doesn't appear to be the case with the GitHub issues notebooks. Maybe it's only implemented if you have the consolidated run menu (i.e. more than one run action)?

**Comment by roblourens** [comment]
I see this behavior in both types of notebooks which is what I expect. Can you share any notebook-related settings you have?

**Comment by joyceerhl** [comment]
🤦 I was expecting the sticky run button to travel past the cell editor and into the output area as well. I don't suppose that's possible?

**Comment by roblourens** [comment]
Oh I see, yeah we had discussed that originally, but there are other buttons in that area for outputs and I didn't think it would work nicely so I just want to leave it in the editor margin for now
