### ISSUE TITLE
Git delete branch fails when branch name has double quotes in it

### ISSUE THREAD

**Issue by stevef51** [microsoft/vscode#178102]
Type: <b>Bug</b>

Reproduce:  
1. Click on VScodes bottom status bar Git branch segment, then click "Create new branch...", enter branch named

This branch has "double quotes"

Note, this creates a branch called (via escaping)

This-branch-has-"double-quotes"

2. Switch to a different branch (eg master)

3. On VScode git branch panel, right click on the test branch just created and select "Delete Branch...", then confirm the branch deletion - the following output appears in the VScode terminal showing the delete failed

> git -C "/myproject" -c "core.editor=code -- wait --reuse-window" branch --delete This-branch-has-"double-quotes"
error: branch 'This-branch-has-double-quotes' not found.

4. Manually editing the above shell command to escape the quotes works, ie

> git -C "/myproject" -c "core.editor=code -- wait --reuse-window" branch --delete This-branch-has-\\"double-quotes\\"
Deleted branch This-branch-has-"double-quotes" (was 9495762d).

VS Code version: Code 1.76.2 (ee2b180d582a7f601fa6ecfdad8d9fd269ab1884, 2023-03-14T17:54:09.061Z)
OS version: Darwin x64 22.3.0
Modes:
Sandboxed: No
Connection to 'dev-container+7b22686f737450617468223a222f55736572732f53746576652f7265706f732f6c7563696665722f666173742d6465762d636f6e7461696e6572732f666173742e706f7274616c222c22636f6e66696746696c65223a7b22246d6964223a312c22667350617468223a222f55736572732f53746576652f7265706f732f6c7563696665722f666173742d6465762d636f6e7461696e6572732f666173742e706f7274616c2f2e646576636f6e7461696e65722f646576636f6e7461696e65722e6a736f6e222c2265787465726e616c223a2266696c653a2f2f2f55736572732f53746576652f7265706f732f6c7563696665722f666173742d6465762d636f6e7461696e6572732f666173742e706f7274616c2f2e646576636f6e7461696e65722f646576636f6e7461696e65722e6a736f6e222c2270617468223a222f55736572732f53746576652f7265706f732f6c7563696665722f666173742d6465762d636f6e7461696e6572732f666173742e706f7274616c2f2e646576636f6e7461696e65722f646576636f6e7461696e65722e6a736f6e222c22736368656d65223a2266696c65227d7d' could not be established
Remote OS version: Linux x64 5.15.49-linuxkit
Connection to 'dev-container+7b22686f737450617468223a222f55736572732f53746576652f7265706f732f6c7563696665722f666173742d6465762d636f6e7461696e6572732f666173742e737061222c22636f6e66696746696c65223a7b22246d6964223a312c22667350617468223a222f55736572732f53746576652f7265706f732f6c7563696665722f666173742d6465762d636f6e7461696e6572732f666173742e7370612f2e646576636f6e7461696e65722f646576636f6e7461696e65722e6a736f6e222c2265787465726e616c223a2266696c653a2f2f2f55736572732f53746576652f7265706f732f6c7563696665722f666173742d6465762d636f6e7461696e6572732f666173742e7370612f2e646576636f6e7461696e65722f646576636f6e7461696e65722e6a736f6e222c2270617468223a222f55736572732f53746576652f7265706f732f6c7563696665722f666173742d6465762d636f6e7461696e6572732f666173742e7370612f2e646576636f6e7461696e65722f646576636f6e7461696e65722e6a736f6e222c22736368656d65223a2266696c65227d7d' could not be established

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz (16 x 2300)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|4, 4, 4|
|Memory (System)|64.00GB (2.85GB free)|
|Process Argv|--crash-reporter-id 30a098bd-a960-4180-b1ce-56b74d95c381|
|Screen Reader|no|
|VM|0%|

Connection to 'dev-container+7b22686f737450617468223a222f55736572732f53746576652f7265706f732f6c7563696665722f666173742d6465762d636f6e7461696e6572732f666173742e706f7274616c222c22636f6e66696746696c65223a7b22246d6964223a312c22667350617468223a222f55736572732f53746576652f7265706f732f6c7563696665722f666173742d6465762d636f6e7461696e6572732f666173742e706f7274616c2f2e646576636f6e7461696e65722f646576636f6e7461696e65722e6a736f6e222c2265787465726e616c223a2266696c653a2f2f2f55736572732f53746576652f7265706f732f6c7563696665722f666173742d6465762d636f6e7461696e6572732f666173742e706f7274616c2f2e646576636f6e7461696e65722f646576636f6e7461696e65722e6a736f6e222c2270617468223a222f55736572732f53746576652f7265706f732f6c7563696665722f666173742d6465762d636f6e7461696e6572732f666173742e706f7274616c2f2e646576636f6e7461696e65722f646576636f6e7461696e65722e6a736f6e222c22736368656d65223a2266696c65227d7d' could not be established

|Item|Value|
|---|---|
|Remote|Dev Container: Lucifer Git DevContainer|
|OS|Linux x64 5.15.49-linuxkit|
|CPUs|Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz (6 x 2300)|
|Memory (System)|31.36GB (22.30GB free)|
|VM|0%|

Connection to 'dev-container+7b22686f737450617468223a222f55736572732f53746576652f7265706f732f6c7563696665722f666173742d6465762d636f6e7461696e6572732f666173742e737061222c22636f6e66696746696c65223a7b22246d6964223a312c22667350617468223a222f55736572732f53746576652f7265706f732f6c7563696665722f666173742d6465762d636f6e7461696e6572732f666173742e7370612f2e646576636f6e7461696e65722f646576636f6e7461696e65722e6a736f6e222c2265787465726e616c223a2266696c653a2f2f2f55736572732f53746576652f7265706f732f6c7563696665722f666173742d6465762d636f6e7461696e6572732f666173742e7370612f2e646576636f6e7461696e65722f646576636f6e7461696e65722e6a736f6e222c2270617468223a222f55736572732f53746576652f7265706f732f6c7563696665722f666173742d6465762d636f6e7461696e6572732f666173742e7370612f2e646576636f6e7461696e65722f646576636f6e7461696e65722e6a736f6e222c22736368656d65223a2266696c65227d7d' could not be established
</details><details><summary>Extensions (22)</summary>

Extension|Author (truncated)|Version
---|---|---
Angular-BeastCode|Mik|10.0.3
vscode-azurevirtualmachines|ms-|0.6.4
remote-containers|ms-|0.282.0
remote-ssh|ms-|0.98.0
remote-ssh-edit|ms-|0.84.0
remote-ssh-explorer|ms-|0.56.0
remote-wsl|ms-|0.76.1
vscode-remote-extensionpack|ms-|0.24.0
remote-explorer|ms-|0.2.0
remote-server|ms-|1.0.0
debugger-for-chrome|msj|4.13.0
material-icon-theme|PKi|4.25.0
pdf|tom|1.2.2
vscode-icons|vsc|12.2.0
vscode-eslint|dba|2.4.0
githistory|don|0.6.20
gitlens|eam|13.4.0
vscode-pull-request-github|Git|0.60.0
git-graph|mhu|1.30.0
vscode-docker|ms-|1.24.0
csharp|ms-|1.25.4
vscode-zipexplorer|sle|0.3.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30681850
azure-dev_surveyone:30548225
vsccc:30610678
pyindex848:30662994
nodejswelcome1:30587005
2e4cg342:30602488
pyind779:30671433
89544117:30613380
pythonsymbol12:30671437
azdwalk:30687957
pythonms35cf:30686773

```

</details>

**Comment by OrTab** [comment]
On it :)

**Comment by OrTab** [comment]
Hi @stevef51 , are you using any extension? gitLens maybe? 
if you trying to delete this branch from this view , is it also failed? 
<img width="836" alt="Screen Shot 2023-03-27 at 0 25 00" src="https://user-images.githubusercontent.com/74709655/227805487-7bb73e77-39c0-49aa-889e-aa9df0e945f2.png">

**Comment by OrTab** [comment]
Hi @stevef51 , how are you?
i dived into the code related to the bug and i would like to know , do you use an extension for this action? gitLens maybe?
can you please try to delete this branch from this view (in the picture below) and see if it still failed? it will help me understand if I'm right about the reason its happening.

<img width="855" alt="Screen Shot 2023-03-27 at 1 48 27" src="https://user-images.githubusercontent.com/74709655/227809624-2f11beaf-d78e-4d4c-a7c0-224753e7d6b3.png">

**Comment by stevef51** [comment]
Hi @OrTab,
Shows how used to Gitlens I am, after temporarily removing Gitlens extension those expandable panels disappear and to be honest I have never even used the 3dot menu as I always used Gitlens panels (which I didn't realise was part of Gitlens) - so, yes you are correct, if I delete the branch using 3dot menu -> Branch -> Delete Branch... then it works, although I can't find the Git logs related to the deletion.
I will resubmit this bug to the Gitlens extension
Thanks

**Comment by OrTab** [comment]
Great, yes after diving into the code I realized it related to gitLens, I even explored gitLens source code and it made me understand that the bug is there. :)
