### ISSUE TITLE
Keyboard shortcuts for "Copy line down/up" doesn't work in ubuntu 16.04

### ISSUE THREAD

**Issue by mahmoudmy** [Microsoft/vscode#17815]
- VSCode Version: Code 1.8.0 (38746938a4ab94f2f57d9e1309c51fd6fb37553d, 2016-12-13T18:03:00.506Z)
- OS Version: Linux x64 4.4.0-57-generic
- Extensions:

|Extension|Author|Version|
|---|---|---|
|code-beautifier|michelemelluso|1.6.2|

---

Steps to Reproduce:
1. When I use (Ctrl + Shift + Alt + ↑ / ↓)  for "Copy line down/up" nothing happens in ubuntu 16.04!

**Comment by rebornix** [comment]
`ctrl+shift+alt+up/down` happens to be hot key for moving windows across windows on vanilla Ubuntu. Personally I'll suggest either bind another key to these two commands, or unbind them from system by https://blogs.oracle.com/geertjan/entry/alt_shift_up_in_the
