### ISSUE TITLE
VS code suddenly stopped generating .js after .ts changes. 2 hours have gone, still can't figure out why.

### ISSUE THREAD

**Issue by ChmHsm** [Microsoft/vscode#17819]
- VSCode Version: Code 1.8.1 (ee428b0eead68bf0fb99ab5fdc4439be227b6281, 2016-12-19T14:49:23.350Z)
- OS Version: Windows_NT ia32 6.2.9200
- Extensions:

|Extension|Author|Version|
|---|---|---|
|debugger-for-chrome|msjsdiag|2.4.1|

---

Steps to Reproduce:

1. Cloned angular 2 quickstart
_____
2. settings.json:
{
    "typescript.tsdk": "./node_modules/typescript/lib"
}
____
3.  tasks.json:
// A task runner that calls the Typescript compiler (tsc) and
// Compiles a HelloWorld.ts program
{
  "version": "0.1.0",
  // The command is tsc. Assumes that tsc has been installed using npm install -g typescript
  "command": "tsc",
  // The command is a shell script
  "isShellCommand": true,
  // Show the output window only if unrecognized errors occur.
  "showOutput": "silent",
  // args is the HelloWorld program to compile.
  "args": [],
  // use the standard tsc problem matcher to find compile problems
  // in the output.
  "problemMatcher": "$tsc"
}
____
4. tsconfig.json:
{
  "compilerOptions": {
  "target": "es5",
  "module": "system",
  "moduleResolution": "node",
  "sourceMap": true,
  "emitDecoratorMetadata": true,
  "experimentalDecorators": true,
  "removeComments": false,
  "noImplicitAny": false,
  "watch": true
 },
  "exclude": [
    "node_modules"
  ]
}

**Comment by egamma** [comment]
@ChmHsm the built-in TypeScript does not transpile typescript files to javascript files. This is done by the angular setup and how it defines a `tasks.json` and a `tsconfig,json`. I suspect that the `tsc watch` task started by the `task.json` file stopped running. You should be able to restart the task and all should be fine. 

There is nothing we can do for this on the VS Code side. If you can reproduce this behaviour with steps I suggest to file an issue against the TypeScript project.
