### ISSUE TITLE
Terminal: Unable to delete characters after accepting autocomplete suggestion 

### ISSUE THREAD

**Issue by bhavyaus** [microsoft/vscode#178162]
In the video you can observe me attempting to delete (backspace) after I accidentally accepted a suggestion by hitting Tab 

https://user-images.githubusercontent.com/25044782/227297271-70a88612-910b-4d4f-a372-67777a180901.mp4

**Comment by Tyriar** [comment]
This is actually a powershell feature, some context on the contrast of the text though: https://github.com/xtermjs/xterm.js/issues/4262
