### ISSUE TITLE
Typing on the folder area is disabled after placing the folder area to terminal area

### ISSUE THREAD

**Issue by h4l-yup** [microsoft/vscode#178132]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.76.2 (Universal)
                   commit: ee2b180d582a7f601fa6ecfdad8d9fd269ab1884
- OS Version: Darwin arm64 22.2.0

Steps to Reproduce:

1. Drag `Folder Button` on the top right to `Terminal Area` as the folder area place in the terminal area.
<img width="1897" alt="image" src="https://user-images.githubusercontent.com/28913065/227198249-5f02a6f3-74c3-4f64-a421-87d694b8f7ed.png">

2. Drag back all the components that was included in the folder area to right tool bar.
<img width="1272" alt="image" src="https://user-images.githubusercontent.com/28913065/227198466-a7502dd1-11b5-46b6-bba6-5d69b9c5397e.png">

3. Now you can not copy files by CMD+C & CMD+V or type to find files in the file area.
I think after this process, typing in the folder area is disabled somehow.

**Comment by sbatten** [comment]
@h4l-yup Workaround is to right click and reset each view that you dragged

**Comment by lramos15** [comment]
This is fixed in insiders and 1.78.0 which will be released next week. As stated `CTRL + SHIFT + P` -> `Reset View Locations` should fix it.
