### ISSUE TITLE
Debug Console tab disappears when I switch to another tab

### ISSUE THREAD

**Issue by sarimarton** [microsoft/vscode#178104]
Type: <b>Bug</b>

1. Start a debugging session in Javascript
2. Open the Debug Console
3. Switch to "Terminal"

Expected:
Debug Console tab stays in the lower panel

Actual:
Debug Console tab disappears

VS Code version: Code 1.76.2 (Universal) (ee2b180d582a7f601fa6ecfdad8d9fd269ab1884, 2023-03-14T17:54:09.061Z)
OS version: Darwin arm64 22.3.0
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|7, 7, 7|
|Memory (System)|16.00GB (0.03GB free)|
|Process Argv|--crash-reporter-id fb6dbd0a-4d68-44cf-8388-37bbf87275b5|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
pynewvextcfv2:30681851
azure-dev_surveyone:30548225
pyindex848:30662994
nodejswelcome1:30587005
3biah626:30602489
pyind779:30671433
f6dab269:30613381
pythonsymbol12:30671437
vsctsb:30677850
azdwalk:30687957
pythonms35cf:30686773

```

</details>

**Comment by roblourens** [comment]
Sometimes when the panel is narrow, a tab might go into the `...` overflow menu when not focused. Is that what's happening here?

**Comment by sarimarton** [comment]
No, there's plenty of space, wide screen...

**Comment by sarimarton** [comment]
![CleanShot 2023-03-25 at 01 12 06](https://user-images.githubusercontent.com/2169043/227665704-73a68807-dacb-4ca9-81be-062273812e10.gif)

**Comment by roblourens** [comment]
If you right click the panel tab title area, is Debug Console unchecked? It's possible to hide panel items when they are inactive

**Comment by sarimarton** [comment]
Ugh, that was it. I suggest to add an italic style + dblclick-to-lock behavior to it just like with the editor tabs to make it clear.
