### ISSUE TITLE
Create workbench.action.terminal.copyLastCommand to match Shell Integrations Tooltip Menu

### ISSUE THREAD

**Issue by 0x303** [microsoft/vscode#178154]
The options available in the Shell Integrations tooltip menu are not consistent with those available within VScode Settings. This discrepancy is bothersome because you can not use keybinds on the options available in the Shell Integrations tooltip menu (but you can use them with any of the `workbench.action`'s in VScode).

![image](https://user-images.githubusercontent.com/107429937/227278260-0e06f1f6-86cb-4320-8665-b16f8e29b36a.png)

![image](https://user-images.githubusercontent.com/107429937/227278496-6daf5e41-1d0d-4ce8-8e84-485d777140ca.png)

Specifically, there is no option available in VScode settings  to simply **"Copy Last Command"**, which would take the last command you ran and put it in your clipboard. This option is available in the tooltip menu though. I believe the shell integrations tooltip options are defined within the `_getCommandActions` function on line 346 within this file ( link: <https://github.com/microsoft/vscode/blob/main/src/vs/workbench/contrib/terminal/browser/xterm/decorationAddon.ts> ).

There already exists an option for copying the output of the last command `workbench.action.terminal.copyLastCommandOutput` and an equivalent option exists in the tooltip menu, so I do not know why there isn't an equivalent option built into VScode called `workbench.action.terminal.copyLastCommand`. I think this feature would be a nice addition. 

Furthermore, I also think it would be nice to see a combination of `workbench.action.terminal.copyLastCommandOutput` and `workbench.action.terminal.copyLastCommand` (perhaps called `workbench.action.terminal.copyLastCommandBlock` that would copy the last command you ran as the first line and then the output of said command in the subsequent lines that are stored in your clipboard. This would enable you to bind this to a keybind and copy a whole command and its output for use elsewhere (helpful when writing documentation for example).

**Comment by 0x303** [comment]
Any update on this? Does what I described make sense? I can try and provide more information if necessary.

**Comment by 0x303** [comment]
Reaching out again regarding an update on this issue.

**Comment by 0x303** [comment]
Following up on this issue. Would love an update. Thank you.

**Comment by hamirmahal** [comment]
@0x303 #197098 might duplicate this.
