### ISSUE TITLE
https://code.visualstudio.com/ completely blocked in china now

### ISSUE THREAD

**Issue by amsterdamharu** [Microsoft/vscode#17813]
- VSCode Version: any 
- OS Version: any

Steps to Reproduce:

1. Try to download vs code in China

it is still impossible to download vs code in china. Is it possible to host the binaries on a site that is not blocked?

**Comment by smallp** [comment]
I'm in China, and I can download VSCode. So just try again, or use 迅雷 or something else.

**Comment by seanmcbreen** [comment]
Closing this issue for now as I think we are in good shape.  If not please do let us know.
