### ISSUE TITLE
onDidChangeActiveTextEditor is not called when switching to a CustomTextEditorProvider

### ISSUE THREAD

**Issue by jogibear9988** [microsoft/vscode#178198]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: Nightly
- OS Version: Windows

Steps to Reproduce:

1. Attach a callback to onDidChangeActiveTextEditor
2. Create a new VSCode Extension with a CustomTextEditorProvider
3. Switch to the editor wich is created by the CustomTextEditorProvider
4. The callback maybe called (if a editor was active before), but the CustomTextEditorProvider is not provided in the callback

I have a own TreeView in VSCode and need to know when my editor is active, but so it does not work.

**Comment by mjbvz** [comment]
`onDidChangeActiveTextEditor` is only for `TextEditors`, not custom editors. You can use the tabs api to check when your custom editor is active

**Comment by jogibear9988** [comment]
is a customTextEditor not a TextEditor?

**Comment by mjbvz** [comment]
It is not. Check the types in `vscode.d.ts`

**Comment by JYC-99** [comment]
Having the same issue. @mjbvz could you help link more details about tabs api here?

**Comment by JYC-99** [comment]
Any samples about listen to the active tab changes inside CustomEditorProvider?

**Comment by jogibear9988** [comment]
I also asked a question here: https://github.com/microsoft/vscode-discussions/discussions/558
