### ISSUE TITLE
Refresh button in search

### ISSUE THREAD

**Issue by sant123** [Microsoft/vscode#17818]
- VSCode Version: 1.8.1
- OS Version: Windows 10

The refresh button in search should be always enabled instead of an empty entry.

Steps to Reproduce:

1. Select the `Search Tab`
2. Write something
3. The refresh button is disabled

![image](https://cloud.githubusercontent.com/assets/7959437/21472428/23faef9c-caa7-11e6-8ad2-49e9d9adb0f4.png)

It only gets enabled when you hit enter, after that you can reproduce the steps below and it'll work. However if you clear the search result, the refresh button will be disabled until you hit enter again.

Thanks.

**Comment by roblourens** [comment]
I'm not sure about this, it doesn't seem like 'refresh' should trigger a search from an empty page. Like how in a web browser, I can't 'refresh' until I've loaded something.

**Comment by sant123** [comment]
Exactly, when not empty it should enable the button as you can see in the image.
