### ISSUE TITLE
Output error with Python

### ISSUE THREAD

**Issue by SirUnit-y** [microsoft/vscode#178192]
**Bullet list version:** 
• Despite multiple attempts to install Python, VS Code keeps outputting the message: "Bullet list version: 
• Despite multiple attempts to install Python, VS Code keeps outputting the message: "/bin/sh: python: command not found [Done] exited with code=127 in 0.016 seconds."
• Tried installing Python through Homebrew and other sources, but the issue persists. My device is a M1 Mac Mini. 
• Even simple code like "print("Hello World")" is not functioning properly giving me the same output.
• Please do not make me switch to Pycharm.
• Seeking assistance to troubleshoot and resolve the issue online in forums and videos has led to no progress.
________________________________________________________________
To Whom It May Concern,

I am writing to express my frustration with the output on VS Code. Despite my repeated attempts to install Python on my M1 Mac Mini, I keep receiving the following message when attempting to run code in the terminal: "/bin/sh: python: command not found [Done] exited with code=127 in 0.016 seconds."

I have tried installing Python multiple times, including through Homebrew, but to no avail. I have also searched for advice on various forums and sources, but none of the solutions have worked for me. Even code as simple as "print("Hello World")" is not functioning correctly.

I find it extremely frustrating that I cannot use VS Code properly despite my efforts to install Python. This is hindering my ability to work efficiently and is causing me undue stress. I do not want to resort to using Pycharm as I am used to working with VS Code.

I would appreciate any assistance in resolving this issue as soon as possible. Please let me know if there is anything I can do to help troubleshoot this problem.
"

**Comment by roblourens** [comment]
It sounds like python is not on your PATH in your terminal. This isn't a vscode-specific issue and you will have to configure it yourself depending on your environment setup. However the article here might help https://code.visualstudio.com/docs/python/python-tutorial
