### ISSUE TITLE
Update occurred and lost PowerShell Extension and Theme

### ISSUE THREAD

**Issue by trboomer** [microsoft/vscode#178193]
Type: <b>Bug</b>

I allowed an update which I should not have done because this same issue occurred the last time. Now I am wasting time trying to fix it again. 

Version: 1.76.2 (user setup)
Commit: ee2b180d582a7f601fa6ecfdad8d9fd269ab1884
Date: 2023-03-14T17:55:54.936Z
Electron: 19.1.11
Chromium: 102.0.5005.196
Node.js: 16.14.2
V8: 10.2.154.26-electron.0
OS: Windows_NT x64 10.0.22621
Sandboxed: No

My powershell theme was completely gone after the upgrade. Now I have this default ugly white scheme. Not real happy with the updates for this. 

VS Code version: Code 1.76.2 (ee2b180d582a7f601fa6ecfdad8d9fd269ab1884, 2023-03-14T17:55:54.936Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-9500 CPU @ 3.00GHz (6 x 3000)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|63.62GB (36.61GB free)|
|Process Argv|--crash-reporter-id c8df1ae9-fe3b-4f6d-be45-031b0c9a4741|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-azureresourcegroups|ms-|0.6.2
vscode-azurestaticwebapps|ms-|0.11.4
vscode-dotnet-runtime|ms-|1.6.0
azure-account|ms-|0.11.3
powershell|ms-|2023.2.1
azurerm-vscode-tools|msa|0.15.10
vscode-inline-values-powershell|Tyl|0.0.7

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vscaat:30438848
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30681850
azure-dev_surveyone:30548225
pyindex848:30662994
nodejswelcome1cf:30587006
2e4cg342:30602488
pyind779:30671433
f6dab269:30613381
pythonsymbol12:30671437
2i9eh265:30646982
pythonb192cf:30669361
defaultazurewalk:30687958
pythonms35:30686772

```

</details>

**Comment by DonJayamanne** [comment]
@trboomer 
I'm very sorry for missing this issue and never getting back to you on this. 
Please could you advice whether you are still running into this issue.
