### ISSUE TITLE
node.dll is out of date

### ISSUE THREAD

**Issue by NotepadPlusUser** [Microsoft/vscode#17812]
- VSCode Version: 1.8.1
- OS Version: OS1607 V10.0.14393.576

Secunia informs me that "C:\Program Files (x86)\Microsoft VS Code\node.dll" is insecure, and gives it a threat rating of 3/5.  The Secunia message says, `The version detected of Node.js 6.x was 6.5.0.0 while the latest version including one or more security fixes is 6.9.0.'

I already had the 64-bit node.msi version 7.3.0.0 installed in "C:\Program Files\nodejs\node.exe".  I then installed the 32-bit node.msi V7.3.0.0 as well, but as one would expect, "C:\Program Files (x86)\Microsoft VS Code\node.dll" was not updated.  (The LTS version is 6.9.2, which would be enough to satisy Secunia.)

* Neither the 64-bit nor the 32-bit installation directories of node has any file called node.dll.
* The node.js website has no mention of node.dll.

QUESTIONS:
1.  How do I update the insecure node.dll file?
2.  Why is VSCode incorporating an out-of-date and insecure node.dll file into its VSCode installation directory, rather than relying on an independent installation of node?

**Comment by NotepadPlusUser** [comment]
CORRECTION:  I have just run a full scan with Secunia, and Secunia now gives me 100% score — that is, it is no longer reporting the problem.

Nevertheless, I would still like to know what an out-of date node.dll file is doing within the VSCode installation directories, and how I can update it?

**Comment by bpasero** [comment]
This requires us to update Electron when they have moved on from node.js 6.5.0. Currently such a release does not exist, so we can only wait for them to do the move.
