### ISSUE TITLE
Will vscode support vue.js component file?

### ISSUE THREAD

**Issue by yeluoqiuzhi** [Microsoft/vscode#17823]
This is vue component file spec:

<https://vue-loader.vuejs.org/en/start/spec.html>

**Comment by sean-clayton** [comment]
This sounds like a good use-case for an extension 😸 

In fact, @seanwash already made one here: https://marketplace.visualstudio.com/items?itemName=seanwash.vue

**Comment by yeluoqiuzhi** [comment]
@sean-clayton  It is just highlighting! I need auto complete and type checked for typescript.

**Comment by egamma** [comment]
@yeluoqiuzhi I agree with @sean-clayton that this is best done in an extension. 

>I need auto complete and type checked for typescript.

An extension can do this.

As a workaround you can set the language mode in the bottom right corner to `html` then you some Intellisense.

**Comment by rwatts3** [comment]
Is there anyway to instruct the intellisense module to treat the vue component as an html or the same logic html uses to intellisense javascript ? 

May be better to just update the package to leverage the intellisense capabilities in the manner that the html language does.

**Comment by sean-clayton** [comment]
@yeluoqiuzhi does this extension solve some of your needs? https://github.com/octref/vetur
