### ISSUE TITLE
Copy Line Down or Up Shortcut - Not Working

### ISSUE THREAD

**Issue by azizsaboor** [Microsoft/vscode#1782]
The copy line down or up shortcuts are not working on Linux (currently using mint 17)

**Comment by alexandrudima** [comment]
@azizsaboor It is difficult to find out of the box default shortcuts that work on all Linux distributions. We have focused on making good default keybindings work in Ubuntu. I'm guessing mint uses <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>Alt</kbd>+<kbd>Up/Down</kbd> at the OS level to perform some window management actions.

Please feel free to edit your `keybindings.json` and define new rules for `editor.action.copyLinesDownAction` and `editor.action.copyLinesUpAction`.

Alternatively, I am open to changing the default keybinding to something else, but at this time, we need to change it for all linux distros, so we need to find something that still works on Ubuntu (the majority of our Linux users).

**Comment by cdekok** [comment]
They are not working with me either on ubuntu 17.04 vscode 1.16.0.
