### ISSUE TITLE
file / folder renaming by pressing ENTER does not work

### ISSUE THREAD

**Issue by MaxAlter** [microsoft/vscode#178228]
at some point I noticed that through the ENTER button I can not rename the file and folder

after some update! I can not say exactly ! took corrective steps in the form of: 

1- completely removed the editor (all files + cache) 
2- reboot the account 
3- disable all dependencies 
4- reinstall

macbook Air M1
macOS : Ventura 13.2.1
Версия Vs Code : 1.76.2 (Universal)
Node : 16.14.2

**Comment by MaxAlter** [comment]
> Это будет исправлено в 1.78.0, а пока `CMD + SHIFT + P`-> `Reset view locations`исправим,

Thank you . it worked for me)

**Comment by Hugo-Pereira-98** [comment]
Thank you, for me to :)

**Comment by akizora** [comment]
Thank you for your help as I have been suffering from the same phenomenon for several days. Thank you very much.
In my case, I could not even copy and paste files, etc.
