### ISSUE TITLE
[css] boxModel rule not respecting box-sizing property

### ISSUE THREAD

**Issue by BeniaminoBaggins** [Microsoft/vscode#17824]
- VSCode Version: 1.8.1
- OS Version: MacOS Sierra 10.12.1

Steps to Reproduce:

1. Enter `"scss.lint.boxModel": "warning"` into `settings.json`.
2. Enter code below into a .scss file
```
.form-page {
   box-sizing: border-box;
   padding-top: 103px;
   height: 100%;
}
```
3. Notice the warning which should not be there because the box-sizing property should satisfy scss.lint.boxModel rule:

> [scss] Do not use width or height when using padding or border

<img width="273" alt="screen shot 2016-12-26 at 8 28 59 pm" src="https://cloud.githubusercontent.com/assets/24772895/21477783/fb3c7ad6-cba9-11e6-93b9-aa87af7e9b55.png">

**Comment by aeschli** [comment]
See https://github.com/CSSLint/csslint/wiki/Beware-of-box-model-size

**Comment by aeschli** [comment]
To verify: The rule warns when it finds:

- width being used with border, border-left, border-right, padding, padding-left, or padding-right
- height being used with border, border-top, border-bottom, padding, padding-top, or padding-bottom

If the box-sizing property is specified, then the rule does not emit any warnings for the above conditions as it assumes you know what you're doing.
