### ISSUE TITLE
open vscode in lite mode

### ISSUE THREAD

**Issue by mhsfh** [microsoft/vscode#178277]
Hello everyone, 
first of all thanks to everyone who contribute on this amazing project.
sometimes i want to open vscode in lite mode without eslint sever or ts server and without autocomplete just i want view the code with less cost, i think it will be great if we can do this with command line, pass it as argument 
``` bash 
code ./path/to/project --lite-mode
```
thanks

**Comment by jrieken** [comment]
you can use ` --disable-extensions` or ` --disable-extension <ext-id>` for this

**Comment by mhsfh** [comment]
> you can use ` --disable-extensions` or ` --disable-extension <ext-id>` for this

@jrieken  thanks for this handy solution, but the ts server will keep running, is there any way to stop ?
