### ISSUE TITLE
Test Explorer waiting on test provider

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode#178232]
Type: <b>Bug</b>

The Mocha Test Explorer Extension brings up a notification that needs the user's input. If the user doesn't react the notification is hidden automatically. Then the Test Explorer shows the "Busy" badge forever for no apparent reason for the user.

<img width="625" alt="image" src="https://user-images.githubusercontent.com/4674940/227552738-0daeaee2-fa63-4160-ab2a-d4fcce803f97.png">

After a while...

<img width="621" alt="image" src="https://user-images.githubusercontent.com/4674940/227552851-c7a85d99-f76a-41d0-a8e4-089ed7bbd93e.png">

VS Code version: Code - Insiders 1.77.0-insider (deedbd33f5dc57795e11da7c2a26b5a05a93485b, 2023-03-23T21:21:32.849Z)
OS version: Darwin arm64 21.6.0
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|3, 5, 5|
|Memory (System)|16.00GB (0.23GB free)|
|Process Argv|--enable-proposed-api lszomoru.lszomoru-proposed-api-sample --enable-proposed-api donjayamanne.kusto --crash-reporter-id ef10dfea-3602-4c74-ba1a-109ce7da7825|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (59)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-track-build-errors|aes|0.0.3
git-branch|ale|1.7.0
tsl-problem-matcher|amo|0.6.2
github-markdown-preview|bie|0.3.0
markdown-checkbox|bie|0.4.0
markdown-emoji|bie|0.3.0
markdown-footnotes|bie|0.1.1
markdown-mermaid|bie|1.17.7
markdown-preview-github-styles|bie|1.0.1
markdown-yaml-preamble|bie|0.1.0
vscode-svgviewer|css|2.0.0
vscode-eslint|dba|2.4.0
typescript-notebook|don|2.0.6
vsc-material-theme|Equ|33.7.0
vsc-material-theme-icons|equ|2.7.3
graphviz-markdown-preview|gee|0.0.8
codespaces|Git|1.14.1
copilot-nightly|Git|1.78.10293
remotehub|Git|0.53.2023032301
vscode-pull-request-github|Git|0.61.2023032309
mdmath|goe|2.7.4
vscode-mocha-test-adapter|hbe|2.14.1
vscode-test-explorer|hbe|2.21.1
Kotlin|mat|1.7.1
rainbow-csv|mec|3.5.1
theme-monokai-pro-vscode|mon|1.2.0
compare-folders|mos|0.22.3
vscode-docker|ms-|1.24.0
isort|ms-|2022.8.0
python|ms-|2023.5.10821737
vscode-pylance|ms-|2023.3.30
jupyter|ms-|2023.3.1000830504
jupyter-keymap|ms-|1.1.0
jupyter-renderers|ms-|1.0.15
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-slideshow|ms-|0.1.5
remote-containers|ms-|0.287.0
remote-ssh|ms-|0.99.2023032315
remote-ssh-edit|ms-|0.84.0
remote-wsl|ms-|0.77.0
azure-repos|ms-|0.29.2023032301
hexeditor|ms-|1.9.11
js-debug-nightly|ms-|2023.3.2117
remote-explorer|ms-|0.3.2023032309
remote-repositories|ms-|0.31.2023032201
remote-server|ms-|1.1.2023032309
test-adapter-converter|ms-|0.1.6
vscode-github-issue-notebooks|ms-|0.0.128
vscode-js-profile-flame|ms-|1.0.5
vscode-markdown-notebook|ms-|0.0.26
vsliveshare|ms-|1.0.5834
material-icon-theme|PKi|4.25.0
excalidraw-editor|pom|3.4.1
ruby|reb|0.28.1
vscode-commons|red|0.0.6
vscode-xml|red|0.24.0
code-spell-checker|str|2.20.3
codetour|vsl|0.0.58
vscode-ruby|win|0.28.0

(4 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vslsvsres303:30308271
pythonvspyl392:30422396
pythontb:30258533
vsc_aacf:30263846
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscod805cf:30301675
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30404738
cppdebug:30492333
vsclangdf:30492506
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30618038
pylantcb52:30590116
pyindex848:30611229
nodejswelcome1:30587009
pyind779:30611226
pythonsymbol12:30651887
2i9eh265:30646982
6233i204:30659907
pythonb192:30661256
defaultazurewalk:30687958
pythonms35:30671666
cai9j608:30680470
ecj1e332:30687743

```

</details>

**Comment by connor4312** [comment]
We'll now just time out the "busy" indicator after 30s, which is about when the notification will auto-hide

**Comment by eleanorjboyd** [comment]
Having trouble getting the notification from the mocha test explorer extension to pop up on a workspace with mocha tests where I disabled the extension. Thanks

**Comment by roblourens** [comment]
Is this the loading state? It never goes away for me

<img width="469" alt="image" src="https://user-images.githubusercontent.com/323878/235236693-d2021cac-1e8a-41b4-b902-f129d92bbed1.png">

**Comment by connor4312** [comment]
Oh, sorry, forgot I solved this in the test-adapter-converter, not in core 😛 

So the process is:

1. Install https://marketplace.visualstudio.com/items?itemName=hbenl.vscode-mocha-test-adapter
2. Open a workspace that uses things that look like mocha tests. This must be a repo that uses things that look like mocha tests, but that the extension can't definitively confirm are mocha tests. @kieferrm may be able to hint which repo he was in that was able to trigger this.
3. If you found a repo that works, you should get a notification that mocha tests are available in the repo. Ignore it and verify the progress state goes away after 30s
