### ISSUE TITLE
Please do NOT autocomplete the TypeScript module name when ".." is typed.

### ISSUE THREAD

**Issue by infinnie** [Microsoft/vscode#17825]
- VSCode Version: 1.8.1
- OS Version: Windows 10.0.10586

Steps to Reproduce:

1. Create a project that references at least one module with name(s) containing the character “.”, like `zone.js`, in package.json.
2. Run `npm install`.
3. Create a TypeScript file.
4. Type `import {} from ".."` in the created file.
5. While I was trying to reference a module from the parent folder of the one the created file is within, what is automatically completed, instead, is something like `import {} from "zone.js"`.

**Comment by mjbvz** [comment]
I agree this is pretty annoying and will see what we can do here.

As a workaround, you can unbind `.` for `acceptSelectedSuggestion`:

```json
    { "key": ".", "command": "-acceptSelectedSuggestion" }
```

**Comment by infinnie** [comment]
Duplicate of #17770

**Comment by joaomoreno** [comment]
Fix reverted 31997b32c354b0531f296379cec364b094ee362d, #18063

**Comment by mjbvz** [comment]
Picked up improved fix with #18380
