### ISSUE TITLE
[Feature request] Alt+click on a tab should trigger "Reveal in explorer view"

### ISSUE THREAD

**Issue by PoignardAzur** [microsoft/vscode#178221]
**Proposed feature:**

Performing `Alt+click` on a tab should be equivalent to right-clicking the tab and selecting the "Reveal in explorer view" submenu.

**Rationale:**

This is something I want to do very often, when I'm trying to find a file in a very large workspace. Having a faster way to do it would be helpful.

Design-wise, this feels like a natural extension of the `Alt+click` "verb" being "jump to wherever this thing you're clicking is defined".

**Comment by lramos15** [comment]
You can bind a keybinding to `workbench.files.action.showActiveFileInExplorer`
Mouse keybindings are tracked here https://github.com/microsoft/vscode/issues/3130
