### ISSUE TITLE
Welcome page: Improve connect to command labels

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode#178203]
Testing #177702

- clean profile with no remote extensions installed
- open the welcome page
- click on `Connect to...`
- quick pick opens
   
![image](https://user-images.githubusercontent.com/6461412/227463783-1d12f62a-c241-4641-b9e3-42c79249abe6.png)

`Remote - SSH` is the extension name and can be a bit confusing to use it with `Connect to`,
What about `Connect with Remote - SSH`? or `Connect to workspace via Remote - SSH` 

We can also add a property `connectCommandLabel` to the `remoteExtensionTips` so we could write
`Connect to workspace on SSH` 

Or we can also use the quick item description or category and write
`Connect to Host...`   `Remote - SSH`

**Comment by sandy081** [comment]
Moving this to next milestone as part of issue tracking and cleaning for the current milestone as we are close to the release.
