### ISSUE TITLE
Please add options for sorting and choosing which file type to view in the Explorer panel

### ISSUE THREAD

**Issue by phcloc** [Microsoft/vscode#17828]
- VSCode Version: 1.8.1
- OS Version: Windows 10

I'm working on an big project. I view my current folder by the Explorer panel in the left. My current folder have a lot of file of many type. And I only want to show files of a specific type. Please add some option for viewing and sorting file!

**Comment by bpasero** [comment]
@phcloc can you not use the files.exclude setting to filter unwanted files out of view?

**Comment by bpasero** [comment]
I think everything is covered.
