### ISSUE TITLE
Welcome page Connect to: Name the command to run in `remoteExtensionTips`

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode#178205]
Testing #177702

- new profile with not remote extensions installed
- click on `Connect to`
- command show up, click on one

This will run the first command found in the `'statusBar/remoteIndicator' menu

I suggest adding a new property `connectCommand` to the `remoteExtensionTips`. That is less fragile and allows the remote extension to use a tailored command

**Comment by sandy081** [comment]
Moving this to next milestone as part of issue tracking and cleaning for the current milestone as we are close to the release.
