### ISSUE TITLE
js-debug code translations in wrong place of language pack

### ISSUE THREAD

**Issue by TylerLeonhardt** [microsoft/vscode#178282]
This results in js-debug not being translated in full.

**Comment by TylerLeonhardt** [comment]
Fixed with latest release of language packs.

**Comment by TylerLeonhardt** [comment]
verification:
* Get the latest language pack
* set the language to that language pack
* make sure JS debug commands in the command palette are localized (thus ensuring static strings are localized)
* make sure some string coming from JS debug code is localized

**Comment by connor4312** [comment]
It doesn't look like strings coming from js-debug are localized. "process id:" and the placeholder should both be localized

![image](https://user-images.githubusercontent.com/2230985/228070580-31037a56-934e-41af-aa4b-ea4d5c669f4e.png)

This is coming from here https://github.com/microsoft/vscode-js-debug/blob/a83fdb1e5c498af29ed6d89041f449b7b932335b/src/ui/processPicker.ts#L140-L176

**Comment by TylerLeonhardt** [comment]
![Image](https://user-images.githubusercontent.com/2644648/228389374-fedf2d4d-9350-45fa-90bf-585824a11a25.png)

verified!
