### ISSUE TITLE
Inline hints don't look great on Dark+ V2 (Can the background be off by default?)

### ISSUE THREAD

**Issue by jasonwilliams** [microsoft/vscode#178274]
Does this issue occur when all extensions are disabled?: Yes/No

Version: 1.77.0-insider (user setup)
Commit: fa13bf16fd237afef07f4df0648da026f43e3963
Date: 2023-03-20T05:25:30.711Z
Electron: 19.1.11
Chromium: 102.0.5005.196
Node.js: 16.14.2
V8: 10.2.154.26-electron.0
OS: Windows_NT x64 10.0.22000
Sandboxed: Yes

Steps to Reproduce:

1. Open any Rust Project witth the theme set to `Dark+ V2`
2. Install Rust Analyzer and let it show hints

By default hints look like this:
<img width="1216" alt="beforeNew" src="https://user-images.githubusercontent.com/936006/227634521-3d974b5c-871c-43d1-b71c-48d297706ae4.png">

The boxes around the hints are a bit jarring and really catch your eye more than the code does (which isn't really what hints are meant to do), I was hoping they would be more subtle (like in other IDE/editors)

After messing with the settings I was able to get the hints to look much better:
```
  "workbench.colorCustomizations": {
    "[Default Dark+ Experimental]": {
      "editorInlayHint.background": "#00000000",
      "editorInlayHint.typeBackground": "#00000000"
    },
  }
```

<img width="895" alt="afterNew" src="https://user-images.githubusercontent.com/936006/227634663-6ca86391-ce78-4c5c-aef6-90df2166e81c.png">

Should it not be like the latter by default?

**Comment by hediet** [comment]
Generally I agree, but in your second screenshot it is really hard to tell that the inlay hints are not part of the code.

**Comment by jasonwilliams** [comment]
That's fair @hediet, It doesn't have to look exactly like my alternative. But what I have is still a big improvement over what was there before.

**Comment by jasonwilliams** [comment]
Since 1.79 I've needed to update the settings to:
```json
  "workbench.colorCustomizations": {
    "[Default Dark Modern]": {
      "editorInlayHint.background": "#00000000",
      "editorInlayHint.typeBackground": "#00000000"
    }
  },
```

@daviddossett do you have any thoughts on this?

**Comment by rzhb** [comment]
The inlay hint should blend with the normal code, while being slightly less prominent. My solution is make the fontsize smaller.

Here is my seetings:
```json
{
    "editor.fontSize": 16,
    "editor.inlayHints.fontSize": 14,
    "workbench.colorCustomizations": {
        "[Default Light Modern]": {
            "editorInlayHint.background": "#8b949e00",
            "editorInlayHint.foreground": "#8b949e",
            "editorInlayHint.parameterBackground": "#8b949e00",
            "editorInlayHint.parameterForeground": "#8b949e",
            "editorInlayHint.typeBackground": "#8b949e00",
            "editorInlayHint.typeForeground": "#8b949e"
        }
    }
}
```

**Comment by jasonwilliams** [comment]
@daviddossett did you mean to make [the changes](https://github.com/microsoft/vscode/commit/a3231fc857c16cfca2674dfadedc71454f3a9566) you did to `Dark Modern`? The colors look much worse than before. It looks like you removed the `"editorInlayHint.typeForeground"` line which means its defaulting to white.

For [e.g](https://github.com/boa-dev/boa/blob/main/boa_runtime/src/console/mod.rs#L163-L199) (this is default settings)
The hints here are *far* too prominent, they end up being brighter than the code itself which is distracting.
![image](https://github.com/microsoft/vscode/assets/936006/e0e9c55d-bbfb-4994-b5f0-f4e75760bea9)

I was able to change it back with some settings to get this:
```
    "workbench.colorCustomizations": {
        "[Default Dark Modern]": {
            "editorInlayHint.background": "#00000000",
            "editorInlayHint.typeBackground": "#00000000",
            "editorInlayHint.foreground": "#8b949e"
        }
    }
``` 
![image](https://github.com/microsoft/vscode/assets/936006/702ad915-5bb7-4781-b6c1-1fc4ab9a1b13)
^ This style more in line with other IDE's when it comes to inline hinting

**Comment by daviddossett** [comment]
Made further changes in https://github.com/microsoft/vscode/pull/189498 to make these less prominent as well as fixing issues in the high contrast themes along the way.

https://github.com/microsoft/vscode/assets/25163139/09edeecb-d962-4f4f-936a-ac70b8828a2a

**Comment by jasonwilliams** [comment]
I haven't noticed an issue with this lately so I think the fixes above have sorted it, I will close this issue, thanks for fixing @daviddossett
