### ISSUE TITLE
Sync stops when switching profile

### ISSUE THREAD

**Issue by dvyas1** [microsoft/vscode#178233]
Type: <b>Bug</b>

- Configure sync
- Switch profile
- You will see an error stating VSCode failed sync. and it disables sync automatically.

VS Code version: Code 1.76.2 (ee2b180d582a7f601fa6ecfdad8d9fd269ab1884, 2023-03-14T17:55:54.936Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: Yes
Remote OS version: Linux x64 5.15.0-1028-aws
Remote OS version: Linux x64 5.15.0-1031-aws

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 9 5900HX with Radeon Graphics         (16 x 3294)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|

|Item|Value|
|---|---|
|Remote|gml-prod-new|
|OS|Linux x64 5.15.0-1028-aws|
|CPUs|Intel(R) Xeon(R) CPU E5-2686 v4 @ 2.30GHz (2 x 2300)|
|Memory (System)|3.83GB (2.94GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|vscode-remote|
|OS|Linux x64 5.15.0-1031-aws|
|CPUs|Intel(R) Xeon(R) CPU E5-2676 v3 @ 2.40GHz (1 x 2400)|
|Memory (System)|0.94GB (0.40GB free)|
|VM|0%|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
remote-containers|ms-|0.282.0
remote-ssh|ms-|0.98.0
remote-ssh-edit|ms-|0.84.0
remote-wsl|ms-|0.76.1
vscode-remote-extensionpack|ms-|0.24.0
remote-explorer|ms-|0.2.0
remote-server|ms-|1.0.0
terraform|has|2.25.4

(1 theme extensions excluded)

</details>

**Comment by sandy081** [comment]
Where do you see this error? Can you please provide a screenshot? Can you also please share following logs?

- F1 > Open View... > Window
- F1 > Open View... > Shared

**Comment by dvyas1** [comment]
I can't replicate the issue anymore! I was happening consistently for two days. Closing the issue.
