### ISSUE TITLE
Allow configuring the editor for better rename detection in Source Control view

### ISSUE THREAD

**Issue by ugultopu** [microsoft/vscode#178265]
Using Git, when you both rename and modify a file, the Source Control dropdown under the Source Control view sometimes shows your modifications as indeed renames with modifications. However, at other times, it shows your modifications as if the original file has been deleted and a completely new file has been added. This makes it difficult to understand exactly what type of modifications has been performed on the file. It would be nice if the Source Control view would always show your modifications correctly, or at least gave you an option to configure its behavior.

Upon further investigation, the behavior seems to be influenced by the [similarity threshold feature in Git](https://git-scm.com/docs/git-diff#Documentation/git-diff.txt---find-renamesltngt). If there was a way to configure this value, the user could tell VSCode when to consider a rename and modification as a rename and when to consider it as a deletion of an existing file and addition of a new file.

[This issue created in GitLens](https://github.com/gitkraken/vscode-gitlens/issues/1469) is relevant.

**Comment by lszomoru** [comment]
Verification steps:
1. Open a folder/workspace in VS Code Insiders that contains a git repository
2. Open settings and set the `git.similarityThreshold` setting is set to `100`
3. Add a new file to the git repository called `foo.txt` with the following content:
    ```
    1
    2
    3
    4
    5
    6
    7
    8
    9
    10
    ```
4. Commit the new file to the repository
5. Rename the file from `foo.txt` to `bar.txt`, and stage the change
    Confirm that the staged change appears with the `R` modifier
6. Change the file line of the file from `1` to `1.`, and stage the change
    Confirm that now two resource appear: one with `D` and one with `A` modifier

**Comment by roblourens** [comment]
Does this just affect the editor/scm view or does it affect git too?

**Comment by lszomoru** [comment]
@roblourens, this setting is being passed in to the `git status` call as the `--find-renames` option. The output of the `git status` command is what the git extension is using the update its model that drives the "Source Control" view. The setting does not impact any of the git commands that are being executed through the integrated terminal. Does this answer your question?
