### ISSUE TITLE
[Feature Request] Add grouped by folder view to git

### ISSUE THREAD

**Issue by italomaia** [Microsoft/vscode#17822]
- VSCode Version: 1.8.1
- OS Version: Ubuntu 16.10

It would be nice to have a grouped by folder visualization mode for the git pane. It is quite useful when you're verifying what you're gonna pack in a commit.

**Comment by egamma** [comment]
// CC @joaomoreno

**Comment by leonardochaia** [comment]
I'd love this!

**Comment by joaomoreno** [comment]
#14582
