### ISSUE TITLE
Update the f# grammar

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode#17820]
The latest version of the f# grammar is now maintained in https://github.com/ionide/ionide-fsgrammar  and we should update the one we bundle to it.

For background pls see https://github.com/ionide/ionide-atom-fsharp/issues/255#issuecomment-269098830

It turns out that the F# extension bundles this grammar, so we should discuss whether we want to continue bundle a grammer and other language support with VS Code.

**Comment by aeschli** [comment]
I'd suggest that we continue to bundle just the grammar as to give a good out-of-the-box experience.  
I filed OSS approvals and updated the grammar to the latest from https://github.com/ionide/ionide-fsgrammar
