### ISSUE TITLE
All copilot command palette items are duplicated

### ISSUE THREAD

**Issue by eleanorjboyd** [microsoft/vscode#178260]
reproduce steps:
1. open command palette, type "copilot"
2. see the below screen, all copilot items appear twice
3. when you select one and then load command prompt again the most recently selected item is now the copilot item and again it is duplicated here.
<img width="783" alt="Screenshot 2023-03-24 at 12 16 44 PM" src="https://user-images.githubusercontent.com/26030610/227619756-aa9c1178-36e4-4d40-9bae-7c1330071665.png">
<img width="780" alt="Screenshot 2023-03-24 at 12 19 03 PM" src="https://user-images.githubusercontent.com/26030610/227619793-b3a419cf-6b7c-47e3-a044-0da583a140e9.png">

**Comment by TylerLeonhardt** [comment]
Sounds like you have GitHub Copilot and GitHub Copilot Nightly installed at the same time

**Comment by eleanorjboyd** [comment]
yep- my bad sorry haha

**Comment by eleanorjboyd** [comment]
so I disabled the GitHub Copilot to just keep the GitHub Copilot Nightly and now when I search for copilot it only shows up with one item- is this expected?
<img width="713" alt="Screenshot 2023-03-24 at 12 56 11 PM" src="https://user-images.githubusercontent.com/26030610/227626965-0c17575b-24c3-413e-b279-67a5285ee719.png">

**Comment by TylerLeonhardt** [comment]
![Image](https://user-images.githubusercontent.com/2644648/227637049-d39e1488-2284-4620-ab3b-a90b42e2f61b.png)

hmmm I see a few more... did you reload your window after disabling?

**Comment by eleanorjboyd** [comment]
closing since I now see the full range of options
