### ISSUE TITLE
VS Code Integrated Terminal displays 'UTF-8 Tamil Characters' in an overlapped manner

### ISSUE THREAD

**Issue by Surya-NarayananS** [microsoft/vscode#178345]
Type: <b>Bug</b>

Run the following python3 code:
print("தமிழ்")

Expected Output:
தமிழ்

Actual output in VS Code Integrated Terminal:
![Screenshot 2023-03-26 091504](https://user-images.githubusercontent.com/38600702/227754170-4503d832-d075-4833-bae7-feac496c0685.png)

VS Code version: Code 1.76.2 (ee2b180d582a7f601fa6ecfdad8d9fd269ab1884, 2023-03-14T17:55:54.936Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 4500U with Radeon Graphics          (6 x 2371)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|7.40GB (2.30GB free)|
|Process Argv|--crash-reporter-id 9773666c-4159-4a28-80bc-29f43bc79876|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (19)</summary>

Extension|Author (truncated)|Version
---|---|---
code-runner|for|0.12.0
isort|ms-|2022.8.0
python|ms-|2023.4.1
vscode-pylance|ms-|2023.3.30
jupyter|ms-|2023.2.1200692131
jupyter-keymap|ms-|1.1.0
jupyter-renderers|ms-|1.0.15
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-slideshow|ms-|0.1.5
cpptools|ms-|1.14.5
material-icon-theme|PKi|4.25.0
java|red|1.16.0
intellicode-api-usage-examples|Vis|0.2.7
vscodeintellicode|Vis|1.2.30
vscode-java-debug|vsc|0.49.0
vscode-java-dependency|vsc|0.21.1
vscode-java-pack|vsc|0.25.9
vscode-java-test|vsc|0.38.1
vscode-maven|vsc|0.40.4

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
pyindex848:30662994
nodejswelcome1cf:30587006
2e4cg342:30602488
pyind779:30671433
f6dab269:30613381
pythonsymbol12:30671437
6233i204:30672705
vsctsb:30677850
vscodedisable:30660115
pythonb192:30669360
defaultazurewalk:30687958
pythonms35cf:30686773

```

</details>

**Comment by Tyriar** [comment]
This depends on ligatures coming to the terminal first https://github.com/microsoft/vscode/issues/34103

**Comment by Surya-NarayananS** [comment]
Any way to work around this?

**Comment by Tyriar** [comment]
Let's track upstream https://github.com/xtermjs/xterm.js/issues/4867, related: https://github.com/xtermjs/xterm.js/issues/2668
