### ISSUE TITLE
Support hiding cursor in inactive terminal

### ISSUE THREAD

**Issue by ryuukk** [microsoft/vscode#178379]
Sometimes it is hard to tell what terminal is active, so i suggest adding an option to automatically hide the cursor from the inactive terminal

```json
    "terminal.displayCorsor": "onlyActive"
```

- ``always``: always render render cursor - this is the default
- ``onlyActive``: only render cursor of the active terminal (with user input focus)

![image](https://user-images.githubusercontent.com/44361234/227813280-fd91b6ed-5ccc-4f55-affc-2a9d375e231d.png)

As you can see, there is no way to tell wich one is currently active..

Related : #178378

**Comment by meganrogge** [comment]
You can use a `block` cursor and cursor blinking to help with this 

https://user-images.githubusercontent.com/29464607/228019496-4f45f632-7d1f-47b2-8946-ce6fbc0f9703.mov
