### ISSUE TITLE
Searching for file names: Error parsing glob '**/[/**': unclosed character class; missing ']'

### ISSUE THREAD

**Issue by justanotheranonymoususer** [microsoft/vscode#178397]
Does this issue occur when all extensions are disabled?: Yes/No

Version: 1.76.2 (user setup)
Commit: ee2b180d582a7f601fa6ecfdad8d9fd269ab1884
Date: 2023-03-14T17:55:54.936Z
Electron: 19.1.11
Chromium: 102.0.5005.196
Node.js: 16.14.2
V8: 10.2.154.26-electron.0
OS: Windows_NT x64 10.0.22621
Sandboxed: No

Steps to Reproduce:

1. Search with file name containing `[`
2. See error

![image](https://user-images.githubusercontent.com/5781692/227896336-d41e01dd-4d94-4f04-8b97-9e9050b7ea98.png)

**Comment by andreamah** [comment]
Your path for in the `files to include` field needs a closing bracket to accompany your opening bracket. The error there is intentional.
