### ISSUE TITLE
[Bug] lodash types weird intellisense output

### ISSUE THREAD

**Issue by Luchillo** [Microsoft/vscode#17831]
- VSCode Version: 1.8.1
- OS Version: OSX Sierra

This is the output of VSCode with the `@types/lodash` package:

![image](https://cloud.githubusercontent.com/assets/9698639/21484318/855756b0-cb5e-11e6-8b78-bb8e38d91ea0.png)

I expected to see at least `map` intellisense, and most likely `flatMap` and a few others.

tsconfig file:

```ts
{
  "compilerOptions": {
    "target": "es5",
    "module": "commonjs",
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "allowSyntheticDefaultImports": true,
    "sourceMap": true,
    "noEmitHelpers": true,
    "strictNullChecks": false,
    "baseUrl": "./src",
    "paths": {},
    "lib": [
      "dom",
      "es6"
    ],
    "types": [
      "hammerjs",
      "jasmine",
      "node",
      "selenium-webdriver",
      "source-map",
      "uglify-js",
      "webpack",
      "lodash"
    ]
  },
  "exclude": [
    "node_modules",
    "dist"
  ],
  "awesomeTypescriptLoaderOptions": {
    "forkChecker": true,
    "useWebpackText": true
  },
  "compileOnSave": false,
  "buildOnSave": false,
  "atom": { "rewriteTsconfig": false }
}
```

Steps to Reproduce:

1. Install with `npm i -D lodash @types/lodash`.
2. Create ts file and try to import lodash map function, it will not even show `map`, nor `flatMap` nor others.

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript#13374
