### ISSUE TITLE
Create Scope For `activeGuide` In Custom Themes

### ISSUE THREAD

**Issue by johndugan** [Microsoft/vscode#17834]
- VSCode Version: 1.8.1
- OS Version: Windows 10

I read through the [VSCode theme scopes](https://code.visualstudio.com/Docs/customization/themes#_creating-a-custom-theme). I'd like a way to target the active guide, ie:

```
<key>guide</key>
<string>#3A3A39</string>
<key>activeGuide</key>
<string>#5D5D5D</string>
```
Additionally, a setting to choose `line`, `dotted`, or `dashed` for the guide style would be welcomed... perhaps a string could be passed to the `"editor.renderIndentGuides"` property instead of a boolean.

**Comment by mjbvz** [comment]
Covered by the `"editorIndentGuide.activeBackground"` themable property I believe
