### ISSUE TITLE
run symbol not visble

### ISSUE THREAD

**Issue by rex-alan** [microsoft/vscode#178346]
Type: <b>Feature Request</b>

in top right corner run symbol is not visible i tried uninstalling and reinstall vs code but still it is not visible

VS Code version: Code 1.76.2 (ee2b180d582a7f601fa6ecfdad8d9fd269ab1884, 2023-03-14T17:55:54.936Z)
OS version: Windows_NT x64 10.0.19045
Modes:
Sandboxed: No

**Comment by roblourens** [comment]
Maybe you're expecting this from the "Code Runner" extension? That isn't necessary to run and debug code, but if that's what you want then make sure that extension is installed. Otherwise, I need more details.

**Comment by rex-alan** [comment]
I'm not sure whether it is from 'Code Runner' Extension. But I also install that extension still that run symbol(play button symbol) is not visible but i can able to run my code by pressing ctrl+f5. But previously i have not installed "Code Runner" and that symbol is visible but now even after i install that extension that symbol is not visible.Please provide me solution.

**Comment by roblourens** [comment]
I can't debug the code runner extension for you. It sounds like you are able to run your code though. If you are debugging python code, the python extension also contributes to that button. It's really not clear what the issue is but it sounds like there isn't an issue with vscode itself here.
