### ISSUE TITLE
Expose the ability to replace an Output even before the output is rendered/added to the Notebook Model

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode#178307]
In the Jupyter extension there is a need to replace an existing output.
Unfortunately for this to work today, we have to wait for the previous output operations to be completed so that the outputs haver been added to the Notebook model.

However there are cases where the Jupyter extension gets data and needs to replace outputs even before they might be added to the model. Awaiting for the output to be added to the model will reduce the performance of displaying outputs and will undo the work done in the past that improves handling of large outputs (by not keeping in anything in memory).

Note: This functionality exists today and kind of works. It works by chance as the model has been updated by the time the second message comes in).
However there are scenarios where this might not always happen (i.e. we get another message even before the output is added to the Model), as a result outputs are not displayed correctly.

**Meaning todays implementation is broken**

# Proposed Solution (same API as today, no new API changes)

```typescript
const task = this.controller.createNotebookCellExecution(cell);
task.start();
const output1 = new NotebookCellOutput([....]);
await task.appendOutput(output1);
const output2 = new NotebookCellOutput([....]);
await task.appendOutput(output2);

// At this point the first output needs to be replaced with something else new
// This is an existing API.
task.replaceOutputItems(newOutputItems, output1);

```

There is absolutely no difference to the underlying API, however the only difference is the second argumen of `replaceOutputItems`
The description of that is `@param output Output object that already exists.`

I'm proposing that we change this to be able to pass an Output object that doesn't necessarily yet exist, but one that was previously passed into VS Code API for appending/replacing, .

We can achieve this by adding an `id` property to the NotebookOutput object (such a property existed and was removed, we could make it internal to VS Code or we could maintain some internal weakmap mapping between the two models).

@roblourens /cc We can possibly chat about this some time next week.

**Comment by roblourens** [comment]
I don't remember all the details of this but I guess I don't understand why it doesn't already work? Also, these updates are already driven by an internal output ID. It still exists, I think it was only removed from the extension API. Happy to chat some more about it

**Comment by DonJayamanne** [comment]
> Also, these updates are already driven by an internal output ID

Oh ok, let me have a look then

**Comment by DonJayamanne** [comment]
the problem is with the metadata, will create a separate issue
