### ISSUE TITLE
Prevent build while debugging

### ISSUE THREAD

**Issue by andreujuanc** [Microsoft/vscode#17833]
- VSCode Version: 1.8.1
- OS Version: Windows 10.0.14393

Steps to Reproduce:

1. Debug session (F5). In my case I have tried NodeJs and cordova.
2. Press F6 

It woudn't hurt anyone to prevent build while there is a debugging session going on.

Maybe this is posible already via settings?

Thanks

**Comment by isidorn** [comment]
Please file this issue against the cordova extension here https://github.com/Microsoft/vscode-cordova

As the cordova extension is contributing that keybinding, they should add a when not in debug mode clause to their keybinding, example

```
{ "key": "f5",                    "command": "workbench.action.debug.start",
                                     "when": "!inDebugMode" },
```

**Comment by andreujuanc** [comment]
Done, thanks.

https://github.com/Microsoft/vscode-cordova/issues/222
