### ISSUE TITLE
Hope to improve the input experience: text overlaps when typing (non-English)

### ISSUE THREAD

**Issue by IOLOII** [microsoft/vscode#178365]
When entering text (non-English), the code will overlap with the preview text content.
Pay attention to the area circled by the mouse when typing is paused:
> Translate:
输入文本（非英文）时，代码会与预览文本内容重叠。
注意暂停输入时鼠标圈出的区域：

![CleanShot 2023-03-26 at 23 30 17](https://user-images.githubusercontent.com/34856171/227786748-8032cbcd-3e06-43bc-bd21-6479fb028fea.gif)

This doesn't happen when I use google translate.
> Translate:
当我使用谷歌翻译时不会发生这种情况.

![CleanShot 2023-03-26 at 23 40 08](https://user-images.githubusercontent.com/34856171/227786890-baacd346-7024-4f82-b802-7e3624b2ea4a.gif)

**Comment by alexdima** [comment]
Let's track in https://github.com/microsoft/vscode/issues/143167
