### ISSUE TITLE
Name a tunnel by session or process instead of machine

### ISSUE THREAD

**Issue by AdvCh** [microsoft/vscode#178327]
I'm using two GPU servers that share one file system. I want to set up two tunnels correspondingly for them. However, when I rename the name of the tunnel, the other tunnel's name will change too. If tunnel could support naming a tunnel by process instead of a machine or based on config in the total file system?

**Comment by aeschli** [comment]
Similar issue: https://github.com/microsoft/vscode/issues/178089

**Comment by aeschli** [comment]
Similar issue: https://github.com/microsoft/vscode/issues/178089

**Comment by aeschli** [comment]
Similar issue: https://github.com/microsoft/vscode/issues/178089

**Comment by aeschli** [comment]
Similar issue: https://github.com/microsoft/vscode/issues/178089

Do you run two instances of VS Code on the same VS Code user data dir?

**Comment by connor4312** [comment]
You can pass a different `--cli-data-dir` to one of the CLI instances to fix this.

**Comment by AdvCh** [comment]
what if I want to use the same dir? But actually, if I run one CLI instance, I can access all dir. I will try it.
