### ISSUE TITLE
Agent admitted failure to sign using the key.

### ISSUE THREAD

**Issue by jadupl2** [Microsoft/vscode#17838]
- VSCode Version: Code 1.8.1 (ee428b0eead68bf0fb99ab5fdc4439be227b6281, 2016-12-19T14:41:20.664Z)
- OS Version: Linux x64 3.10.0-514.2.2.el7.x86_64
- Extensions:

|Extension|Author|Version|
|---|---|---|
|format-php|Kasik96|1.1.2|
|material-icon-theme|PKief|1.1.5|
|python|donjayamanne|0.5.5|
|php-debug|felixfbecker|1.10.0|
|Theme-1337|ms-vscode|0.1.2|

---

Steps to Reproduce:

1.define git remote using ssh
 jacques@holmes:/sadmin$ git remote -v
gogs	ssh://git@centos7.maison.ca:32/jacques/sadmin.git (fetch)
gogs	ssh://git@centos7.maison.ca:32/jacques/sadmin.git (push)

2. But pass phrase is blank , password is always ask and refuse blank.
Keep popping up screen asking fore password, and cannot give password because they are none.
Could it be change so a blank pass-phrase is valid ?

**Comment by joaomoreno** [comment]
Try setting the URL as:

```
ssh://git:@centos7.maison.ca:32/jacques/sadmin.git
```

Notice the colon after `git`.

**Comment by joaomoreno** [comment]
#10064
