### ISSUE TITLE
Error while installing extensions.

### ISSUE THREAD

**Issue by Mehdi-Dehghan** [microsoft/vscode#178306]
Does this issue occur when all extensions are disabled?: Yes

  - VS Code Version: 
  - 1.76.2
  ee2b180d582a7f601fa6ecfdad8d9fd269ab1884
  x64
- OS Version: 
  Edition	Windows 10 Enterprise
  Version	22H2
  Installed on	‎3/‎20/‎2023
  OS build	19045.2728
  Experience	Windows Feature Experience Pack 120.2212.4190.0

Steps to Reproduce:

1. Open VS Code
2. Go to extensions Tab
3. Choose any extension to install
4. After a while Vscode showed "Error while installing 'name of Extension' extension. Please check the [log] for more details."
5. log:
  [error] CorruptZip: end of central directory record signature not found 
  ...
  [error] end of central directory record signature not found: CorruptZip: end of central directory record signature not found
  ...
6. After download manually and try to install from .vsix, vscode showed "end of central directory record signature not found"

**Comment by Kyle83420** [comment]
8

**Comment by sandy081** [comment]
May I know if you are able to reproduce the issue consistently? If so, can you please shared the downloaded VSIX from following location

- Open User Data Folder using command `F1 > Developer: Open User Data Folder`
- Go to `CachedExtensionVSIXs` folder

share the VSIX that is getting downloaded and installed

**Comment by flyguolai** [comment]
Hello, I have the same issue in 1.76.2

the reason,i guess, is my computer has a security program. this program will encode most file in my computer, to keep the doc/files sending only in company network/computer(any other computer install this programe can decode it).

I find the file from sandy's way, i found the files which downloading from marketplace in vscode didn't have any ext.

So i try to install the file download from marketplace with changing it's ext to .vsix, it can successfully installed without any decoding action.

Mybe this information is supported, maybe these information is supported to resolve this issue

**Comment by sandy081** [comment]
> I found the file from sandy's way, and the files which downloading from marketplace in vscode didn't have any ext.

Have you tried using the downloaded file in that folder to install?

**Comment by sandy081** [comment]
Glad that it worked for you. Please share the VSIX next time you see the issue. Thanks.
