### ISSUE TITLE
exclude "<" and ">" from file path detection

### ISSUE THREAD

**Issue by nicolasparada** [microsoft/vscode#178326]
Exclude both `<` at the start and `>` at the end from filepath detection.

See this screenshot.

<img width="2560" alt="Screenshot 2023-03-25 at 15 01 58" src="https://user-images.githubusercontent.com/7969166/227733949-3966a634-a9c1-4e28-85dd-3f8cf822ed8f.png">

The file path is detected but includes the surrounding angle brackets. Doing a `Ctrl+click` to go to the file causes it to not be found. If one removes the angle brackets from the search manually, then it finds the file.

**Comment by nicolasparada** [comment]
Weird... 🤔
Yes, it is.
I'm using latest version of vscode (1.76.2) and the integrated terminal is running zsh, on macOS.

**Comment by Tyriar** [comment]
Can you try using the Insiders build here? https://code.visualstudio.com/insiders

**Comment by nicolasparada** [comment]
Sure. Just for completeness, even if I pass the actual relative path, it doesn't work. See the screenshot (still using stable).
<img width="2560" alt="Screenshot 2023-03-27 at 16 17 20" src="https://user-images.githubusercontent.com/7969166/228044247-82073c76-567d-4e54-8994-407004a42b39.png">

**Comment by Tyriar** [comment]
Can repro on macOS 👍 

<img width="226" alt="Screenshot 2023-03-27 at 12 58 16 pm" src="https://user-images.githubusercontent.com/2193314/228052692-e7e512a6-86e6-4fad-9663-5a66d24c44b8.png">
