### ISSUE TITLE
Emoji width calculated incorrectly for line wrapping when ZWJ are used.

### ISSUE THREAD

**Issue by edent** [microsoft/vscode#178360]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: Version: 1.76.2
OS: Ubuntu 20.04 Linux x64 6.2.6-76060206-generic

Steps to Reproduce:

1.  Create a line consisting only of ZWJ emoji. e.g. 👨‍🦲 (`U+1F468` + `U+200D` + `U+1F9B2`)
2.  Notice that the line wraps far too early compared to regular text:
3.   ![Screenshot showing a line of emoji wrapping earlier than a line of text.](https://user-images.githubusercontent.com/837136/227776806-a5f51b2e-2c33-4926-804e-57bb6cc1818e.png)
4. The same can be seen if you mix ZWJ emoji with regular text:
5.  ![Screenshot showing a line of mixed emoji and text wrapping early](https://user-images.githubusercontent.com/837136/227776818-41adca20-5bd2-4bb0-852c-29ace2da53f8.png)

**Comment by alexdima** [comment]
Please configure `"editor.wrappingStrategy": "advanced"`. The default is `simple`:

```js
  // Controls the algorithm that computes wrapping points. Note that when in accessibility mode, advanced will be used for the best experience.
  //  - simple: Assumes that all characters are of the same width. This is a fast algorithm that works correctly for monospace fonts and certain scripts (like Latin characters) where glyphs are of equal width.
  //  - advanced: Delegates wrapping points computation to the browser. This is a slow algorithm, that might cause freezes for large files, but it works correctly in all cases.
  "editor.wrappingStrategy": "simple",
```
