### ISSUE TITLE
HTML Script Tag Scope Bug

### ISSUE THREAD

**Issue by johndugan** [Microsoft/vscode#17835]
- VSCode Version: 1.8.1
- OS Version: Windows 10

The initial `<` bracket in the opening `<script>` tag _does not_ have the proper scope attached to it, neither does the `>` bracket in the closing `</script>` tag.

Also, it would be nice to have _specific_ scopes to target javascript attributes in html tags, ie: `onclick`, as well as the `style` attribute in html tags. Because those attributes are deal with to presentation and behavior (not just DOM markup), it would be nice to have the _possibility_ to customize them in themes.

Below is a screenshot showing the issue.

![scopes](https://cloud.githubusercontent.com/assets/1389303/21487026/3c435a10-cb85-11e6-8b11-5e18716b868e.png)

**Comment by aeschli** [comment]
We use the textmate grammar from https://github.com/textmate/html.tmbundle and don't want to have our own fork.
@johndugan Please specify what you expect as scopes for `<` and `>`
