### ISSUE TITLE
all of sudden Vs code is starting very slot 

### ISSUE THREAD

**Issue by rajeshsingh520** [microsoft/vscode#178382]
1. :warning: We have copied additional data to your clipboard. Make sure to **paste** here. :warning:
2. ## System Info

* Code: 1.76.2 (ee2b180d582a7f601fa6ecfdad8d9fd269ab1884)
* OS: win32(10.0.22621)
* CPUs: AMD Ryzen 5 2600 Six-Core Processor            (12 x 3394)
* Memory(System): 15.95 GB(11.27GB free)
* Memory(Process): 205.17 MB working set(162.52MB private, 0.99MB shared)
* VM(likelihood): 0%
* Initial Startup: true
* Has 0 other windows
* Screen Reader Active: false
* Empty Workspace: false

## Performance Marks

| What                                                            | Duration | Process                   | Info                                                        |
| --------------------------------------------------------------- | -------- | ------------------------- | ----------------------------------------------------------- |
| start => app.isReady                                            | 4168     | [main]                    | initial startup: true                                       |
| nls:start => nls:end                                            | 0        | [main]                    | initial startup: true                                       |
| require(main.bundle.js)                                         | 173      | [main]                    | initial startup: true                                       |
| start crash reporter                                            | 4111     | [main]                    | initial startup: true                                       |
| serve main IPC handle                                           | 3        | [main]                    | initial startup: true                                       |
| create window                                                   | 45       | [main]                    | initial startup: true, state: 0ms, widget: 14ms, show: 26ms |
| app.isReady => window.loadUrl()                                 | 289      | [main]                    | initial startup: true                                       |
| window.loadUrl() => begin to require(workbench.desktop.main.js) | 12165    | [main->renderer]          | NewWindow                                                   |
| require(workbench.desktop.main.js)                              | 866      | [renderer]                | cached data: NO, node_modules took 0ms                      |
| wait for window config                                          | 0        | [renderer]                | -                                                           |
| init storage (global & workspace)                               | 26       | [renderer]                | -                                                           |
| init workspace service                                          | 44       | [renderer]                | -                                                           |
| register extensions & spawn extension host                      | 387      | [renderer]                | -                                                           |
| restore viewlet                                                 | 25       | [renderer]                | workbench.view.explorer                                     |
| restore panel                                                   | 0        | [renderer]                | -                                                           |
| restore & resolve visible editors                               | 345      | [renderer]                | 1: workbench.editors.files.fileEditorInput                  |
| overall workbench load                                          | 611      | [renderer]                | -                                                           |
| workbench ready                                                 | 18160    | [main->renderer]          | -                                                           |
| renderer ready                                                  | 1557     | [renderer]                | -                                                           |
| shared process connection ready                                 | 0        | [renderer->sharedprocess] | -                                                           |
| extensions registered                                           | 18409    | [renderer]                | -                                                           |

## Raw Perf Marks: main

```
Name	Timestamp	Delta	Total
code/timeOrigin	1679880271550.671	0	0
code/didStartMain	1679880271686	135.3291015625	135.3291015625
code/willStartCrashReporter	1679880271706	20	155.3291015625
code/didStartCrashReporter	1679880275817	4111	4266.3291015625
code/mainAppReady	1679880275854	37	4303.3291015625
code/willGenerateNls	1679880275855	1	4304.3291015625
code/didGenerateNls	1679880275855	0	4304.3291015625
code/willLoadMainBundle	1679880275855	0	4304.3291015625
code/fork/willLoadCode	1679880275876	21	4325.3291015625
code/registerFilesystem/file	1679880276009	133	4458.3291015625
code/didLoadMainBundle	1679880276028	19	4477.3291015625
code/willStartMainServer	1679880276043	15	4492.3291015625
code/didStartMainServer	1679880276046	3	4495.3291015625
code/willCreateCodeWindow	1679880276094	48	4543.3291015625
code/willRestoreCodeWindowState	1679880276095	1	4544.3291015625
code/didRestoreCodeWindowState	1679880276095	0	4544.3291015625
code/willCreateCodeBrowserWindow	1679880276096	1	4545.3291015625
code/didCreateCodeBrowserWindow	1679880276110	14	4559.3291015625
code/willMaximizeCodeWindow	1679880276111	1	4560.3291015625
code/didMaximizeCodeWindow	1679880276137	26	4586.3291015625
code/didCreateCodeWindow	1679880276139	2	4588.3291015625
code/willOpenNewWindow	1679880276143	4	4592.3291015625
```
## Raw Perf Marks: renderer

```
Name	Timestamp	Delta	Total
code/timeOrigin	1679880276148	0	0
code/didStartRenderer	1679880288289	12141	12141
code/willWaitForWindowConfig	1679880288290	1	12142
code/didWaitForWindowConfig	1679880288290	0	12142
code/willShowPartsSplash	1679880288290	0	12142
code/didShowPartsSplash	1679880288292	2	12144
code/willLoadWorkbenchMain	1679880288308	16	12160
code/didLoadWorkbenchMain	1679880289174	866	13026
code/registerFilesystem/file	1679880289181	7	13033
code/registerFilesystem/vscode-userdata	1679880289181	0	13033
code/willInitWorkspaceService	1679880289185	4	13037
code/willInitStorage	1679880289187	2	13039
code/willInitUserConfiguration	1679880289194	7	13046
code/didInitStorage	1679880289213	19	13065
code/didInitUserConfiguration	1679880289218	5	13070
code/willInitWorkspaceConfiguration	1679880289218	0	13070
code/didInitWorkspaceConfiguration	1679880289229	11	13081
code/didInitWorkspaceService	1679880289229	0	13081
code/willStartWorkbench	1679880289235	6	13087
code/LifecyclePhase/Ready	1679880289239	4	13091
code/willCreateWorkbenchContributions/1	1679880289304	65	13156
code/didCreateWorkbenchContributions/1	1679880289344	40	13196
code/willCreateWorkbenchContributions/2	1679880289344	0	13196
code/registerFilesystem/trustedDomains	1679880289347	3	13199
code/registerFilesystem/vscode-interactive	1679880289349	2	13201
code/registerFilesystem/vscode-local-history	1679880289353	4	13205
code/didCreateWorkbenchContributions/2	1679880289356	3	13208
code/willCreatePart/workbench.parts.titlebar	1679880289361	5	13213
code/didRemovePartsSplash	1679880289371	10	13223
code/didCreatePart/workbench.parts.titlebar	1679880289394	23	13246
code/willCreatePart/workbench.parts.banner	1679880289394	0	13246
code/didCreatePart/workbench.parts.banner	1679880289394	0	13246
code/willCreatePart/workbench.parts.activitybar	1679880289394	0	13246
code/didCreatePart/workbench.parts.activitybar	1679880289398	4	13250
code/willCreatePart/workbench.parts.sidebar	1679880289398	0	13250
code/didCreatePart/workbench.parts.sidebar	1679880289400	2	13252
code/willCreatePart/workbench.parts.editor	1679880289400	0	13252
code/willSetInputToTextFileEditor	1679880289432	32	13284
code/didCreatePart/workbench.parts.editor	1679880289466	34	13318
code/willCreatePart/workbench.parts.panel	1679880289466	0	13318
code/didCreatePart/workbench.parts.panel	1679880289468	2	13320
code/willCreatePart/workbench.parts.auxiliarybar	1679880289468	0	13320
code/didCreatePart/workbench.parts.auxiliarybar	1679880289468	0	13320
code/willCreatePart/workbench.parts.statusbar	1679880289469	1	13321
code/didCreatePart/workbench.parts.statusbar	1679880289471	2	13323
code/willRestoreEditors	1679880289501	30	13353
code/willRestoreViewlet	1679880289511	10	13363
code/didRestoreViewlet	1679880289536	25	13388
code/willRegisterExplorerViews	1679880289536	0	13388
code/willResolveExplorer	1679880289625	89	13477
code/didRegisterExplorerViews	1679880289627	2	13479
code/willLoadExtensions	1679880289708	81	13560
code/didSetInputToTextFileEditor	1679880289826	118	13678
code/didRestoreEditors	1679880289846	20	13698
code/didStartWorkbench	1679880289846	0	13698
code/LifecyclePhase/Restored	1679880289846	0	13698
code/willCreateWorkbenchContributions/3	1679880289846	0	13698
code/willConnectSharedProcess	1679880289847	1	13699
code/willHandleExtensionPoints	1679880289893	46	13745
code/willHandleExtensionPoint/configurationDefaults	1679880289893	0	13745
code/didHandleExtensionPoint/configurationDefaults	1679880289894	1	13746
code/willHandleExtensionPoint/configuration	1679880289894	0	13746
code/didHandleExtensionPoint/configuration	1679880289956	62	13808
code/willHandleExtensionPoint/jsonValidation	1679880289956	0	13808
code/didHandleExtensionPoint/jsonValidation	1679880289958	2	13810
code/willHandleExtensionPoint/debuggers	1679880289958	0	13810
code/didHandleExtensionPoint/debuggers	1679880289958	0	13810
code/willHandleExtensionPoint/breakpoints	1679880289958	0	13810
code/didHandleExtensionPoint/breakpoints	1679880289958	0	13810
code/willHandleExtensionPoint/notebooks	1679880289958	0	13810
code/didHandleExtensionPoint/notebooks	1679880289959	1	13811
code/willHandleExtensionPoint/notebookRenderer	1679880289959	0	13811
code/didHandleExtensionPoint/notebookRenderer	1679880289961	2	13813
code/willHandleExtensionPoint/problemPatterns	1679880289961	0	13813
code/didHandleExtensionPoint/problemPatterns	1679880289962	1	13814
code/willHandleExtensionPoint/problemMatchers	1679880289962	0	13814
code/didHandleExtensionPoint/problemMatchers	1679880289964	2	13816
code/willHandleExtensionPoint/taskDefinitions	1679880289964	0	13816
code/didHandleExtensionPoint/taskDefinitions	1679880289967	3	13819
code/willHandleExtensionPoint/terminal	1679880289967	0	13819
code/didHandleExtensionPoint/terminal	1679880289967	0	13819
code/willHandleExtensionPoint/terminalQuickFixes	1679880289967	0	13819
code/didHandleExtensionPoint/terminalQuickFixes	1679880289967	0	13819
code/willHandleExtensionPoint/walkthroughs	1679880289967	0	13819
code/didHandleExtensionPoint/walkthroughs	1679880289967	0	13819
code/willHandleExtensionPoint/commands	1679880289967	0	13819
code/didHandleExtensionPoint/commands	1679880289974	7	13826
code/willHandleExtensionPoint/submenus	1679880289974	0	13826
code/didHandleExtensionPoint/submenus	1679880289975	1	13827
code/willHandleExtensionPoint/menus	1679880289975	0	13827
code/didHandleExtensionPoint/menus	1679880289996	21	13848
code/willHandleExtensionPoint/authentication	1679880289996	0	13848
code/didHandleExtensionPoint/authentication	1679880289996	0	13848
code/willHandleExtensionPoint/languages	1679880289996	0	13848
code/didHandleExtensionPoint/languages	1679880290016	20	13868
code/willHandleExtensionPoint/customEditors	1679880290016	0	13868
code/didHandleExtensionPoint/customEditors	1679880290016	0	13868
code/willHandleExtensionPoint/codeActions	1679880290016	0	13868
code/didHandleExtensionPoint/codeActions	1679880290016	0	13868
code/willHandleExtensionPoint/viewsWelcome	1679880290016	0	13868
code/didHandleExtensionPoint/viewsWelcome	1679880290016	0	13868
code/willHandleExtensionPoint/resourceLabelFormatters	1679880290016	0	13868
code/didHandleExtensionPoint/resourceLabelFormatters	1679880290016	0	13868
code/willHandleExtensionPoint/grammars	1679880290016	0	13868
code/didHandleExtensionPoint/grammars	1679880290023	7	13875
code/willHandleExtensionPoint/colors	1679880290023	0	13875
code/didHandleExtensionPoint/colors	1679880290025	2	13877
code/willHandleExtensionPoint/icons	1679880290025	0	13877
code/didHandleExtensionPoint/icons	1679880290028	3	13880
code/willHandleExtensionPoint/semanticTokenScopes	1679880290028	0	13880
code/didHandleExtensionPoint/semanticTokenScopes	1679880290028	0	13880
code/willHandleExtensionPoint/snippets	1679880290028	0	13880
code/didHandleExtensionPoint/snippets	1679880290028	0	13880
code/willHandleExtensionPoint/keybindings	1679880290028	0	13880
code/didHandleExtensionPoint/keybindings	1679880290042	14	13894
code/willHandleExtensionPoint/themes	1679880290042	0	13894
code/didHandleExtensionPoint/themes	1679880290043	1	13895
code/willHandleExtensionPoint/iconThemes	1679880290043	0	13895
code/didHandleExtensionPoint/iconThemes	1679880290044	1	13896
code/willHandleExtensionPoint/continueEditSession	1679880290044	0	13896
code/didHandleExtensionPoint/continueEditSession	1679880290044	0	13896
code/willHandleExtensionPoint/viewsContainers	1679880290044	0	13896
code/didHandleExtensionPoint/viewsContainers	1679880290068	24	13920
code/willHandleExtensionPoint/views	1679880290068	0	13920
code/didHandleExtensionPoint/views	1679880290085	17	13937
code/didHandleExtensionPoints	1679880290085	0	13937
code/didLoadExtensions	1679880290095	10	13947
code/didResolveExplorer	1679880290522	427	14374
```

### cached data created (lazy, might need refreshes)

1. :warning: Make sure to **attach** these files from your *home*-directory: :warning:
-`prof-P0jkItyC.main.cpuprofile.txt`
-`prof-P0jkItyC.renderer.cpuprofile.txt`
[prof-P0jkItyC.main.cpuprofile.txt](https://github.com/microsoft/vscode/files/11073710/prof-P0jkItyC.main.cpuprofile.txt)
[prof-P0jkItyC.renderer.cpuprofile.txt](https://github.com/microsoft/vscode/files/11073711/prof-P0jkItyC.renderer.cpuprofile.txt)

**Comment by rajeshsingh520** [comment]
I found the issue it was slowing down due to McAfee  antivirus software

**Comment by Tasin5541** [comment]
> I found the issue it was slowing down due to McAfee antivirus software

Same for me. Have you found any solution (other than turning off Real-Time Scanning) or why this is happening suddenly?
