### ISSUE TITLE
The order number display incorrectly in Markdown files when from pasting

### ISSUE THREAD

**Issue by awxiaoxian2020** [microsoft/vscode#178350]
Type: <b>Bug</b>

1. create a Markdown file in vscode.
2. copy the [raw](https://raw.githubusercontent.com/reactjs/react.dev/main/README.md).
3. paste it in the file
4. you will see the incorrect order:
![bug1](https://user-images.githubusercontent.com/69554233/227767330-265e1a52-5924-49f5-bc7c-34b4d5cf364d.png)

VS Code version: Code 1.76.2 (ee2b180d582a7f601fa6ecfdad8d9fd269ab1884, 2023-03-14T17:55:54.936Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-10210U CPU @ 1.60GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.83GB (3.22GB free)|
|Process Argv|E:\\zh-hans.reactjs.org --crash-reporter-id 1d6bc69b-4e51-4186-aa86-5d367fa7ba04|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-language-pack-zh-hans|MS-|1.76.2023030809

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vscaat:30438848
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
vsccc:30610678
pyindex848:30662994
nodejswelcome1cf:30587006
282f8724:30602487
pyind779:30671433
89544117:30613380
pythonsymbol12:30671437
a9j8j154:30646983
azdwalk:30687957
pythonms35cf:30686773

```

</details>

**Comment by mjbvz** [comment]
What's incorrect about the order?

**Comment by awxiaoxian2020** [comment]
> What's incorrect about the order? 

please see my snapshot.

all are '1'

I don't know whether you could re produce it.

**Comment by mjbvz** [comment]
The original file you linked to also only uses `1`. You can use the same number for lists markdown. The numbers are correct when the markdown is rendered
