### ISSUE TITLE
no selection char count on bottom ~ yes, the 'Editor Selection' is checked

### ISSUE THREAD

**Issue by 1m1-github** [microsoft/vscode#178332]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 
- OS Version: 

Version: 1.76.2 (Universal)
Commit: ee2b180d582a7f601fa6ecfdad8d9fd269ab1884
Date: 2023-03-14T17:54:09.061Z (1 wk ago)
Electron: 19.1.11
Chromium: 102.0.5005.196
Node.js: 16.14.2
V8: 10.2.154.26-electron.0
OS: Darwin arm64 22.3.0
Sandboxed: Yes

Steps to Reproduce:

1. no selection char count on bottom
2. yes, the 'Editor Selection' is checked

**Comment by lramos15** [comment]
What do you mean editor selection is checked?
