### ISSUE TITLE
View container visibility not preserved when switching profiles

### ISSUE THREAD

**Issue by ToBoMi** [microsoft/vscode#178406]
Type: <b>Bug</b>

1. Move outline view to a new view container in secondary side bar
2. Create an empty profile
3. 🐛 Observe the empty secondary sidebar view container stay open

**edit:** I expect the view container to be closed in the empty profile and reopened and filled with the outline view in the previous profile. More generally speaking: I expected profiles to remember the view container positions, layout and sizes.

Might help to fix https://github.com/microsoft/vscode/issues/95182 by using profiles.

VS Code version: Code 1.76.2 (ee2b180d582a7f601fa6ecfdad8d9fd269ab1884, 2023-03-14T17:55:54.936Z)
OS version: Windows_NT x64 10.0.19044
Modes:
Sandboxed: Yes

**Comment by sandy081** [comment]
> Observe the empty secondary sidebar view container stay open

Views / View Containers collapsed state is stored in workspace and therefore they are respected across profiles for the same workspace.

**Comment by ToBoMi** [comment]
What are the advantages to save this for a workspace rather than a profile? I sthis the place to ask those questions?

**Comment by sandy081** [comment]
It does not makes sense to expand / collapse a view in all windows when you do it in one view, hence it is stored in workspace.

**Comment by ToBoMi** [comment]
Sorry I don't understand this.

>in all windows when you do it in one view

What do you mean by windows and what do you mean by view in your last comment?

**Comment by sandy081** [comment]
By windows I mean, VS Code instances say if you open multiple instances each instance opening a different folder. By view, I mean a view in the side bar of VS Code, eg: Explorer view or Search view. When you toggle the state is not synced across other VS Code instances.

**Comment by sandy081** [comment]
You are right, but this nothing to do with profiles. View container or views expansion/collapsed state is per workspace. If you open a view in one workspace (say Folder 1) the same view need not be opened in another workspace (say Folder 2)

**Comment by ToBoMi** [comment]
>You are right

Thanks for confirming.

> but this nothing to do with profiles

I know and I didn't say that it has to do with profiles. I expect(ed) it to be associated with profiles.

> View container or views expansion/collapsed state is per workspace

I know. This is the current state.
I do not really understand the advantage of having layouts per workspace.
The reason is that I want to be able to reuse my nicely crafted view layout from one workspace to another. It is my work. Why do I have to recreate it by hand again in every new workspace that I open and which has the same view requirements? I am doing code editing and database editing there, too.
I think that discussion leads to having perspectives (issue #95182). I'll follow that one.

About the problem you proposed:
I think the problem you describe can be solved using profiles, too:

When a view container state is changed (right hand side bar opened and filled with outline for example) in one workspace (folder1) and it is saved (to the currently selected profile this time) this change would affect a second workspace (folder2) when it uses the same profile - yes. But:
If one doesn't like that layout in the second workspace, because the work there has different view layout requirements, one can create another profile, which doesn't has that view container open and fits the needs of the process in that workspace better.

So that problem can be solved, but one needs to change profiles then. That might be not in focus of the current UI without having perspectives.
