### ISSUE TITLE
support vbscript

### ISSUE THREAD

**Issue by xarthx** [Microsoft/vscode#17842]
- VSCode Version:
- OS Version:windows
hello
i hope vscode support **# vbscript** , and debugger

**Comment by chrisdias** [comment]
Thanks for the suggestion.  We don't have plans to build a vbscript extension for VS Code, but if the community would like to they should start here: https://code.visualstudio.com/docs/extensions/example-language-server

**Comment by Luncher91** [comment]
Just for everyone which finds this issue:

There is Syntax Highlighting by 
https://marketplace.visualstudio.com/items?itemName=luggage66.VBScript
https://marketplace.visualstudio.com/items?itemName=Darfka.vbscript

and I am working on a project which provides symbols and maybe at some point a debugger as well.
https://marketplace.visualstudio.com/items?itemName=andreaslenzen.vbscript-language-server-client
