### ISSUE TITLE
TS syntax highlighting broken for (1 / 1) * (1 / (1 + 1))

### ISSUE THREAD

**Issue by voltrevo** [Microsoft/vscode#17848]
- VSCode Version: 1.7.2
- OS Version: macOS Sierra 10.12

### Steps to Reproduce:
1. Open a new .ts file, all default settings
2. Type `console.log((1 / 1) * (1 / (1 + 1)));`

### Expected output:
Syntax highlighting should resemble the output when replacing `(1 + 1)` with `2`:
<img width="246" alt="screen shot 2016-12-27 at 9 03 09 pm" src="https://cloud.githubusercontent.com/assets/9291586/21497265/e5f6d670-cc77-11e6-9cde-eab57c284e98.png">

### Actual output:
Syntax highlighting breaks and highlights all following code in red and orange:
<img width="297" alt="screen shot 2016-12-27 at 9 03 46 pm" src="https://cloud.githubusercontent.com/assets/9291586/21497274/f9e06958-cc77-11e6-835e-83c5493303fa.png">

**Comment by aeschli** [comment]
Seems to be fixed with the latest grammar.
