### ISSUE TITLE
ProtoPie prototyping - Interactive components library

### ISSUE THREAD

**Issue by esonnino** [microsoft/vscode#178430]
A lot of design teams at Microsoft and across the industry started using ProtoPie as a tool for rapid design prototyping and ideation.
We are starting to build a small ProtoPie VSCode library of interactive components to go along with our Figma toolkit as one more resource for Design teams to make things more productive

We are currently talking to the ProtoPie team on how to publish those components in a Open Source way that we can maintain and update frequently

Let me know if you're interested in knowing more or getting a sneak peek! 
![CleanShot 2023-03-27 at 08 14 39](https://user-images.githubusercontent.com/113370447/227984261-714bf889-ba9d-4878-9608-408396bedf75.png)

**Comment by rzhao271** [comment]
I believe this one is out of scope. Closing for housekeeping.
