### ISSUE TITLE
Visual code window crashed

### ISSUE THREAD

**Issue by Vips120** [Microsoft/vscode#17846]
My visual code was working fine last night but now when i am trying to open visual code. 
I am getting a windows stating that "windows is crashed try reopen " 
I also tried installing in other drive but its not working.
Please find attachment below.
![err](https://cloud.githubusercontent.com/assets/15245230/21496722/902f08ba-cc46-11e6-86cf-cb52e9097e3b.png)

**Comment by dbaeumer** [comment]
It crashes whenever you open VS Code? When you open it from a command line via code on an empty folder `code .` does it crash as well?

**Comment by Vips120** [comment]
i resolved the problem , i format ma laptop now its working ..... !!

**Comment by dbaeumer** [comment]
I am happy it is working now but it is strange to here that formatting the laptop made it work. Since you can't reproduce anymore I will close the issue. If you see it again please ping.

**Comment by dbaeumer** [comment]
@Vips120 please open a separate issue with steps describing the problem you have with Angular 2 & TypeScript
