### ISSUE TITLE
"yield" is not highlighting

### ISSUE THREAD

**Issue by IgorNovozhilov** [Microsoft/vscode#17844]
- VSCode Version: 
![image](https://cloud.githubusercontent.com/assets/3082812/21495729/6b2d1c6c-cc2a-11e6-945a-471e6122b1d0.png)

- OS Version: Linux Mint 18

Steps to Reproduce:

![image](https://cloud.githubusercontent.com/assets/3082812/21495747/834a6872-cc2a-11e6-8eb9-0952c99c4b31.png)

1. write code:
```js
/* jshint esnext:true */
let it = require('./it');
it.execute(function* builder(options) {
   let metaData = yield it.read(option.metaFile);
   it.meta = yield it.parse(metaData, {
      ICON: yield it.read(options.icon),
      ICON64: (yield it.read(options.icon64)).base64()
   });
});
```
2. key word not highlighted in all cases

**Comment by dbaeumer** [comment]
Looks like a TS/JS grammar problem.

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript-TmLanguage#396
