### ISSUE TITLE
Debugger not working for files loaded over ssh in the extension development host 

### ISSUE THREAD

**Issue by iulia-codes** [microsoft/vscode#178423]
Hi,

when debugging a VS Code Extension and launching the Extension Development Host for a file that is loaded over ssh, the debugger is not working.

- VS Code Version: 1.76.0
- OS Version: Darwin arm64

Steps to Reproduce:

1.  Open a sample jasmine extension for development purposes such as the sample one: https://code.visualstudio.com/api/get-started/your-first-extension#:~:text=Debugging%20the%20extension,to%20check%20a%20variable's%20value.
2. Start debugging your extension
3. VS Code starts in a new window over the Extension Development Host
4. Go to remote explorer
5. Open any file over ssh
6. Run the extension 

**Actual**

- breakpoints are ignored

**Expected**

- I can debug an extension for files loaded over ssh

**Comment by iulia-codes** [comment]
The issue is VS Code Version independent.

**Comment by roblourens** [comment]
What is a "sample jasmine extension"

**Comment by connor4312** [comment]
To debug an extension running on the remote, you'll want to have the debugger running on the remote as well. That is, clone and open your extension in a directory _on the remote_, and then F5 from there. The new window will be connected to the remote, and you can run and debug it at that point.

**Comment by iulia-codes** [comment]
> To debug an extension running on the remote, you'll want to have the debugger running on the remote as well. That is, clone and open your extension in a directory _on the remote_, and then F5 from there. The new window will be connected to the remote, and you can run and debug it at that point.

That sounds like the missing part, I will try it, thanks!

**Comment by iulia-codes** [comment]
Solution confirmed.
