### ISSUE TITLE
Bugs in updated version of VSCode

### ISSUE THREAD

**Issue by foxnorth228** [microsoft/vscode#178413]
Type: <b>Bug</b>

Today I upgdaded program (system Linux/Ubuntu) to version 1.76 using .deb
Now VSCode work with a lot of bugs. I have problems with "git push". "remote: fatal error in commit_refs".  Maybe this problem has another reason. But also older version of VSCode update git changes in its file system quickly, and now program update git changes with delay. And the biggest problem is that if I finish VSCode with working process in vscode's terminal, this process continues to work, so I need to kill the process myself. In previous version VSCode killed this process itself. It's so annoying.

VS Code version: Code 1.76.2 (ee2b180d582a7f601fa6ecfdad8d9fd269ab1884, 2023-03-14T17:57:21.103Z)
OS version: Linux x64 5.19.0-35-generic
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz (8 x 2807)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|2, 2, 2|
|Memory (System)|7.65GB (1.40GB free)|
|Process Argv|--unity-launch --crash-reporter-id 2c5a6596-282d-47d1-8288-2fcc8705b1e4|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|wayland|
</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|2.4.0
vscode-html-css|ecm|1.13.1
vscode-jest-runner|fir|0.4.60
webpack|jer|3.0.2
svg|joc|1.5.2
easy-less|mrc|2.0.0
LiveServer|rit|5.7.9
vs-code-prettier-eslint|rve|5.1.0
sass-indented|syl|1.8.26
jestRunIt|ves|0.6.0
JavaScriptSnippets|xab|1.8.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
pyindex848:30662994
nodejswelcome1cf:30587006
282f8724:30602487
pyind779:30671433
f6dab269:30613381
pythonsymbol12:30671437
vsccsb:30677849
pythonb192:30669360
defaultazurewalk:30687958
pythonms35:30686772

```

</details>

**Comment by deepak1556** [comment]
I am not sure about the git issues but the leaked terminal process will be addressed in tomorrow's insiders, refs https://github.com/microsoft/vscode/issues/174956
