### ISSUE TITLE
multiple yamls within one file with '---' splitter will cause syntax warning

### ISSUE THREAD

**Issue by iamzhout** [Microsoft/vscode#17845]
- VSCode Version: 1.8.1
- OS Version: Windows 7

Steps to Reproduce:

1.  open [this mysql-deployment file](https://github.com/kubernetes/kubernetes/blob/master/examples/mysql-wordpress-pd/mysql-deployment.yaml)  in vscode
2.  it will show syntax warning like below picture.

Is this kind of file can be treated as normal yaml files seperately, and will not prompt error message?

![mysql-deployment-yaml](https://cloud.githubusercontent.com/assets/14846203/21495939/ad5bc0ae-cc55-11e6-829b-0d14bcbd2e8a.png)

**Comment by dbaeumer** [comment]
@iamzhout I can't reproduce this using a plain VS Code version 1.8.x.  Do you have any additional extension installed ? Does this reproduce if you start VS Code from a terminal with `--disable-extensions`

**Comment by iamzhout** [comment]
@dbaeumer Yes, it is just ok with --disable-extensions. 
I have checked all my installed extensions one by one, and it turns out that [extension: vscode-yaml-validation](https://marketplace.visualstudio.com/items?itemName=djabraham.vscode-yaml-validation) caused this problem, so I will just remove this extension to resolve this problem.

Thanks!
Tao
