### ISSUE TITLE
Git `Revert Change` causes code duplication

### ISSUE THREAD

**Issue by evillique** [microsoft/vscode#178407]
**Version info:**
```
Version: 1.76.0 (Universal)
Commit: 92da9481c0904c6adfe372c12da3b7748d74bdcb
Date: 2023-03-01T10:23:45.993Z
Electron: 19.1.11
Chromium: 102.0.5005.196
Node.js: 16.14.2
V8: 10.2.154.26-electron.0
OS: Darwin arm64 21.1.0
Sandboxed: No
```
**Device:**
```
MacBook Pro (16-inch, 2021), M1 Pro, macOS Monterey version 12.0.1
```
**Problem:**

In the editor when there is some modified code fragment and I open `Git local working changes`, then press `Revert Change` not only does it not revert the changes, but duplicates both new and old versions 10 times:

1. <img width="660" alt="image" src="https://user-images.githubusercontent.com/43110995/227908717-30dbae25-a367-4dd6-bdf2-b546b998f2d6.png">
2. <img width="704" alt="image" src="https://user-images.githubusercontent.com/43110995/227908896-c5ef9266-6f3b-4e86-b475-4eff5f4fd71b.png">
3. <img width="660" alt="image" src="https://user-images.githubusercontent.com/43110995/227908997-5513f0df-47f1-43c4-b225-0cd9996e5eef.png">

If I repeat this process the result only becomes worse:

<img width="790" alt="image" src="https://user-images.githubusercontent.com/43110995/227909120-420662d1-4571-4f98-8464-b683a5263bf4.png">

**Comment by lszomoru** [comment]
@evillique, I noticed that you have filed this issue while running `1.76`. There have been multiple recovery releases since then, that included multiple fixes to quick diff. Could you please upgrade to the latest version, `1.76.2` and reopen this issue in case you are still able to reproduce the problem. Thanks!

**Comment by adriangzz** [comment]
I have 1.76.2 and can confirm this is still happening.
