### ISSUE TITLE
How to prevent completion List UI hide when click an button on one item?

### ISSUE THREAD

**Issue by BleyChen** [Microsoft/vscode#1784]
I have changed the vscode source and add an button in each completion item ,but when I click the button "show sample" as following ,it will hide the completion list UI, what I want is when I click show sample it will show the sample and don't hide the UI, anyone can help me ?
![20160105aaa](https://cloud.githubusercontent.com/assets/15098626/12112151/aa99c026-b3d5-11e5-818c-0e235b6416c8.png)

**Comment by joaomoreno** [comment]
Check the [blur event listener in suggestWidget.ts](https://github.com/Microsoft/vscode/blob/master/src/vs/editor/contrib/suggest/browser/suggestWidget.ts#L458).
