### ISSUE TITLE
Auto-enclose text in an HTML tag

### ISSUE THREAD

**Issue by BenjaminTGa** [microsoft/vscode#178448]
I want to be able to select text, then type an HTML tag  (eg. h2 and have VS Code enclose the selected text with it.  Is it possible to add this as a feature?

**Comment by mosesfawole** [comment]
You can use the Emmet plugin to do this,
- install Emmet plugin in VS code
- Select the text you want to enclose with an HTML tag
- Type the abbreviation for the tag you want to enclose the text in e.g to add a paragraph tag, select the text, type "p" and press the tab key.

If you have any issue with this feature, you can check Emmet documentation

**Comment by aeschli** [comment]
Thanks @mosesfawole !
The Emmet extension is a built-in extension, so no need to install anything.
- select the text
- Run the command `Emmet: Wrap with Abbreviation`

**Comment by BenjaminTGa** [comment]
Thanks so much! It's working now.
