### ISSUE TITLE
Option to turn off ALL tooltips

### ISSUE THREAD

**Issue by allan-bonadio** [microsoft/vscode#178455]
Type: <b>Bug</b>

I'm always trying to click or type, and there's some stupid box that comes up in front.  They are always underfoot and a nuisance, like flying insects.  I don't know what they're saying and I don't care, I've got work to do.  I've turned off litterally EVERYTHING in suggestions, and everything else that seemed to have something to do with them.  Somewhere there was a setting for how long to wait before putting up a tooltip; I set it to an astronomically high number.  But still they keep on popping up.  I've been programming in JavaScript for 15 years, I don't need a 14 square inch box explaining console.log(), obstructing where I want to click.  Is there some setting I can use to just turn them all off?  Is there some setting that must still be on that I've missed?
![annoying tooltips](https://x.tactileint.org/AnnoyingTooltips2.png)

VS Code version: Code 1.76.2 (ee2b180d582a7f601fa6ecfdad8d9fd269ab1884, 2023-03-14T17:55:54.936Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 PRO 5850U with Radeon Graphics      (16 x 1896)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|27.83GB (14.22GB free)|
|Process Argv|/home/v-abonadio/.profile /home/v-abonadio/.profile_common /home/v-abonadio/.profile_common~ /home/v-abonadio/.profile_cygwin /home/v-abonadio/.profile_cygwin~ /home/v-abonadio/.profile_linux /home/v-abonadio/.profile_linux.ojibwe /home/v-abonadio/.profile_linux.owikeno /home/v-abonadio/.profile_mac /home/v-abonadio/.bashrc /home/v-abonadio/.bashrc_common /home/v-abonadio/.bashrc_common~ /home/v-abonadio/.bashrc_cygwin /home/v-abonadio/.bashrc_linux /home/v-abonadio/.bashrc_linux.ojibwe /home/v-abonadio/.bashrc_mac --crash-reporter-id b1a29340-5506-4d99-90c3-927dd01918a0|
|Screen Reader|yes|
|VM|0%|
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscorecescf:30445987
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
pyindex848:30662994
nodejswelcome1:30587005
282f8724:30602487
pyind779:30671433
89544117:30613380
vscrp:30673768
pythonsymbol12:30671437
a9j8j154:30646983
vsccsb:30677849
vscodedisable:30660115
defaultazurewalk:30687958
pythonms35cf:30686773

```

</details>

**Comment by Tyriar** [comment]
You can turn off the editor hover by setting `"editor.hover.enabled": false`, parameter hints that call out what arguments do can be turned off with `"editor.parameterHints.enabled": false`

**Comment by allan-bonadio** [comment]
wow, thanks for the personal response!

My settings.json has no editor.hover anything, the only hover is css.hover.documentation,which is false.  

Also no parameterHints, only editor.suggest.showTypeParameters, which is set to false.

I'm using vs code "1.77.3 (user setup)".  I'd copy & paste the whole version block but it's on a different machine and I don't know how to copy/paste between mac & windows 🙄
and this seems to be AppData/Roaming/Code/User/settings.json


Allan Bonadio j
***@***.***

**Comment by Tyriar** [comment]
You need to add the setting if you want to disable them, they're definitely there as part of the core editor:

![image](https://user-images.githubusercontent.com/2193314/235937994-188df7d1-7ab3-48f0-889d-c2e1bc8260ce.png)
![image](https://user-images.githubusercontent.com/2193314/235938031-25df2bea-d9cd-464f-a21b-268e54ed8246.png)

Or via the settings editor:

![image](https://user-images.githubusercontent.com/2193314/235938106-9175b761-01de-45c9-bc47-147d2e50fc98.png)
![image](https://user-images.githubusercontent.com/2193314/235938188-7acbc9a4-b2bb-4464-a1a4-beb8b1dca910.png)
