### ISSUE TITLE
Syntaxfehler wird angezeigt obwohl kein Fehler da ist. 

### ISSUE THREAD

**Issue by Gilt22** [microsoft/vscode#178422]
Type: <b>Bug</b>

Hi! So i try in english.

I develop in PHP and use Composer to install various requires. However, there seems to be a syntax error in one of the packages. At least that's what visual studio code says. I haven't found one and everything works. The name of class 1 may have been chosen a bit unfavorably, but I think that this shouldn't be displayed as a syntax error.

`class 1 implements ModelInterface, ArrayAccess { .... }`

VS Code version: Code 1.76.2 (ee2b180d582a7f601fa6ecfdad8d9fd269ab1884, 2023-03-14T17:55:54.936Z)
OS version: Windows_NT x64 10.0.22000
Modes:
Sandboxed: No
Remote OS version: Linux x64 5.4.0-1104-azure

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-9600K CPU @ 3.70GHz (6 x 3696)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.94GB (7.37GB free)|
|Process Argv|--crash-reporter-id 65619781-adfa-4052-9624-638c71d7aa17|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|Codespaces|
|OS|Linux x64 5.4.0-1104-azure|
|CPUs|Intel(R) Xeon(R) Platinum 8370C CPU @ 2.80GHz (2 x 2793)|
|Memory (System)|3.84GB (2.42GB free)|
|VM|0%|
</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
codespaces|Git|1.14.1
discord-vscode|icr|5.8.0
vscode-language-pack-de|MS-|1.76.2023030809
vscode-languagetool|ada|3.8.0
vscode-languagetool-de|ada|3.8.0
composer-php-vscode|DEV|1.31.12821
phptools-vscode|DEV|1.31.12876
profiler-php-vscode|DEV|1.31.12821
prettier-vscode|esb|9.10.4
chatgpt-vscode|gen|0.0.3
codespaces|Git|1.14.1
vscode-pull-request-github|Git|0.60.0
vscode-language-pack-de|MS-|1.76.2023030809
prettier-plus|svi|4.2.2

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
vscccc:30610679
pyindex848:30662994
nodejswelcome1:30587005
2e4cg342:30602488
pyind779:30671433
f6dab269:30613381
pythonsymbol12:30671437
vsccsb:30677849
vscodeenable:30660116
pythonb192cf:30669361
azdwalk:30687957
pythonms35cf:30686773
f8hc8238:30694864

```

</details>

**Comment by Gilt22** [comment]
Hi! So i try in english.

I develop in PHP and use Composer to install various requires. However, there seems to be a syntax error in one of the packages. At least that's what visual studio code says. I haven't found one and everything works. The name of class 1 may have been chosen a bit unfavorably, but I think that this shouldn't be displayed as a syntax error.

`class 1 implements ModelInterface, ArrayAccess
{
....
}`

**Comment by roblourens** [comment]
I think that error is correct, it seems like that isn't a valid name in php

<img width="936" alt="image" src="https://user-images.githubusercontent.com/323878/228022136-72c542e2-c5cd-4e7c-9f31-1d5f98bb75e7.png">

The builtin php validation just comes from invoking php on a file and asking it whether there are syntax errors.

You also have a php extension installed which might do smarter validation and the error might be coming from there.
