### ISSUE TITLE
extensions host crashing 5 times in few seconds

### ISSUE THREAD

**Issue by TheNolle** [microsoft/vscode#178489]
Type: <b>Bug</b>

Load visual studio code, open a project, crash any extesnions

VS Code version: Code 1.76.2 (ee2b180d582a7f601fa6ecfdad8d9fd269ab1884, 2023-03-14T17:55:54.936Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.81GB (9.71GB free)|
|Process Argv|--crash-reporter-id 24bd5419-0567-474b-9780-01741376e422|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (63)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|3.0.2
codesnap|adp|1.3.4
clock|ang|1.0.1
ejs-snippets-and-color-highlighting|Ayu|0.0.5
ejs-eta-beautify|bes|1.0.6
better-toml|bun|0.3.2
gitignore|cod|0.9.0
javascript-ejs-support|Dig|1.3.3
python-environment-manager|don|1.0.4
xml|Dot|2.5.1
es7-react-js-snippets|dsz|4.4.3
github-status-presence|eri|1.0.3
auto-rename-tag|for|0.1.10
pythonsnippets|frh|1.0.2
copilot-labs|Git|0.12.791
copilot-nightly|Git|1.78.10395
discord-vscode|icr|5.8.0
vscode-setting-export|jef|0.0.6
shortcut-menu-bar|jer|3.0.4
color-the-tag-name|jzm|0.19.8
vsc-python-indent|Kev|1.18.0
add-to-gitignore|mac|1.0.0
marp-vscode|mar|2.5.0
rainbow-csv|mec|3.6.0
python-path|mge|0.0.14
fluent-icons|mig|0.0.18
scss-snippet|Mil|0.0.2
mongodb-vscode|mon|0.10.0
vscode-apache|mrm|1.2.0
vscode-scss|mrm|0.10.0
vscode-dotnet-runtime|ms-|1.6.0
isort|ms-|2022.8.0
python|ms-|2023.4.1
vscode-pylance|ms-|2023.3.30
vsliveshare|ms-|1.0.5834
sftp|Nat|1.16.1
color-highlight|nau|2.5.0
autodocstring|njp|0.6.1
indent-rainbow|ode|8.3.1
material-icon-theme|PKi|4.25.0
java|red|1.16.0
vscode-sort-json|ric|1.20.0
bash-beautify|sha|0.1.1
vscode-scss-formatter|sib|2.4.5
ejs-snippets|Tao|0.1.0
ejs-snippets|The|0.7.0
scm-buttons-vscode|tom|0.1.1
pdf|tom|1.2.2
python-extended-snippets|tus|0.0.1
errorlens|use|3.8.0
highlight-matching-tag|vin|0.11.0
intellicode-api-usage-examples|Vis|0.2.7
vscodeintellicode|Vis|1.2.30
vscodeintellicode-completions|Vis|1.0.21
vscodeintellicode-insiders|Vis|1.1.10
vscode-java-debug|vsc|0.49.1
vscode-java-dependency|vsc|0.21.2
vscode-java-test|vsc|0.38.2
vscode-maven|vsc|0.41.0
vscode-css-variables|vun|2.6.3
gitblame|wad|10.1.0
twig|wha|1.0.2
five-server|yan|0.1.12

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
vsccc:30610678
pyindex848:30662994
nodejswelcome1cf:30587006
282f8724:30602487
pyind779:30671433
89544117:30613380
pythonsymbol12:30671437
vsccsb:30677849
vscodedisable:30660115
functionswalk:30687959
pythonms35cf:30686773

```

</details>

**Comment by bpasero** [comment]
Please run the command `Start Extension Bisect` and follow the instructions to find the extension that is causing this issue.

<img width="631" alt="image" src="https://user-images.githubusercontent.com/900690/228760008-d5790ad1-74da-46a2-917f-e1bd26281ca8.png">

**Comment by TheNolle** [comment]
It seems to be Intellicode Insiders & Github Copilot Nightly together, but i wanna use both so i don't know what to do (i know i could use the default one but i love beta testing things)

**Comment by bpasero** [comment]
What versions are you on?

**Comment by TheNolle** [comment]
I am on:

1. Github Copilot Nightly -> 1.80.6
2. Intellicode Insiders -> 1.1.10
3. VSCode:
    -   Version: 1.77.1
    -   Commit: b7886d7461186a5eac768481578c1d7ca80e2d21
    -   Date: 2023-04-04T23:21:11.906Z
    -   Electron: 19.1.11
    -   Chromium: 102.0.5005.196
    -   Node.js: 16.14.2
    -   V8: 10.2.154.26-electron.0
    -   OS: Windows_NT x64 10.0.23424
    -   Sandboxed: No

**Comment by alexdima** [comment]
I'm also using GitHub Copilot Nightly but I never observe an extension host crash. Can you please follow the steps in https://github.com/Microsoft/vscode/wiki/Native-Crash-Issues to get at more details around the crash

**Comment by TheNolle** [comment]
I updated vscode to vscode insiders and i don't have this issue anymore, i don't know what caused this but yeah.
Maybe i corrupted something ?
Vscode is installed on an external drive (portable) sooo
