### ISSUE TITLE
Mouse cursor lagging on Linux - Wayland

### ISSUE THREAD

**Issue by major-mayer** [microsoft/vscode#178484]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 
```
- Version: 1.77.0-insider
Commit: 06ce7933733b1ab05e410e46a6a622dfffb31927
Date: 2023-03-03T06:18:58.532Z
Electron: 19.1.11
Chromium: 102.0.5005.196
Node.js: 16.14.2
V8: 10.2.154.26-electron.0
OS: Linux x64 6.1.19-1-MANJARO
Sandboxed: Yes
```

- OS Version: 
```
Operating System: Manjaro Linux
KDE Plasma Version: 5.26.5
KDE Frameworks Version: 5.103.0
Qt Version: 5.15.8
Kernel Version: 6.1.19-1-MANJARO (64-bit)
Graphics Platform: Wayland
Processors: 6 × Intel® Core™ i5-8600K CPU @ 3.60GHz
Memory: 31.3 GiB of RAM
Graphics Processor: AMD Radeon RX 6800
Manufacturer: Micro-Star International Co., Ltd.
Product Name: MS-7B46
System Version: 1.0
```
Steps to Reproduce:

1.  Open Visual Studio Code
2. Move the mouse cursor (maybe a bit faster than usual)

It always lags a bit behind and stutters quite heavily.
This doesn't happen when I don't launch VSCode without the `--ozone-platform=wayland` flag.
And it only occured in the last versions. Back then (maybe a month or two ago) I didn't have this issue.

I tried to create a screencast using Kooha, but it introduces much more CPU load (normally when I use VSCode it's at about 20%) and makes the stuttering much worse, but the video doesn't really show this.

**Comment by major-mayer** [comment]
Yes, I've just downloaded this version and tried both the native Wayland and the XWayland mode:
```
Version: 1.78.0-insider
Commit: 1e774371f2ca5f6618b4f40fdc72ce7518443014
Date: 2023-04-17T05:27:45.204Z
Electron: 22.4.5
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Linux x64 6.1.23-1-MANJARO
Sandboxed: Yes
```

The mouse cursor lag of the native Wayland mode is way higher than with XWayland.

**Comment by deepak1556** [comment]
This would be an issue in the runtime, can you please check again with latest insiders that has updated runtime versions. If the issue persists, can you try to repro with https://vscode.dev/ in Chrome or Edge browser.

**Comment by major-mayer** [comment]
I do not experience this issue anymore, so I will close it.
