### ISSUE TITLE
Save All menu is disabled if you do changes and quickly click on File menu

### ISSUE THREAD

**Issue by ggdaltoso** [microsoft/vscode#178414]
Does this issue occur when all extensions are disabled?: Yes

Version: 1.76.2 (user setup)
Commit: ee2b180d582a7f601fa6ecfdad8d9fd269ab1884
Date: 2023-03-14T17:55:54.936Z
Electron: 19.1.11
Chromium: 102.0.5005.196
Node.js: 16.14.2
V8: 10.2.154.26-electron.0
OS: Windows_NT x64 10.0.22621
Sandboxed: Yes

Steps to Reproduce:

1. Go to whichever file you want
2. quick change it and
3. click in File menu
4. Save All should be enabled

https://user-images.githubusercontent.com/6536985/227950732-eb28fa53-3f35-45dd-bb16-a65eb556257b.mp4

**Comment by sbatten** [comment]
There is some delay in the menu updating and menus do not update when they are opened.
