### ISSUE TITLE
[html] format not work correctly in html file when which has style property in tag

### ISSUE THREAD

**Issue by Ben07** [Microsoft/vscode#17849]
- VSCode Version:1.8.0
- OS Version:win 10

Steps to Reproduce:

1. In html file,when a tag has style property.It's will influence format

for example 
when I press shift+alt+f to format code
```
<div>
    <p style="font-size: 16px;">hello world</p>
    <p>xxxholic</p>
</div>
```
will become
```
<div>
    <p style="font-size: 15px;">hello world</p>
<p>xxxholic</p>
</div>
```

**Comment by aeschli** [comment]
fixed by e9f15e6495cbe91e30186410b9c5885c12da22f0

**Comment by donnygunawan93** [comment]
go release please

**Comment by andreshg112** [comment]
I still have this problem.

**Comment by aeschli** [comment]
@andreshg112 Using a new insider build? If yes, please file a new issue with the vscode version you are using. Please attach the example code that doesn't format.

**Comment by simonmurdock** [comment]
This is fixed for my simple issue (#18969) in the latest windows insider build 1.9.0

**Comment by andreshg112** [comment]
`<input type="button" onclick="app.checkSMSPermission()" value="Send SMS" />`
The same is happening with option tag.

**Comment by transtone** [comment]
not work in the latest Insiders version.
