### ISSUE TITLE
Allow for floating windows

### ISSUE THREAD

**Issue by AuracleTech** [microsoft/vscode#178449]
Floating windows option for:

Terminal
Debug console
Problems
Output
Tabs
Explorer / search / debug / git / extensions

https://github.com/microsoft/vscode/issues/10121
We cannot even like the thread anymore because you closed it
More than 10k people requested this feature, we ***want*** this feature

**Comment by Tyriar** [comment]
/duplicate

It's the highest rated issue, we didn't forget about it. It was closed because it's just noise at this point so don't create more noise.

**Comment by kian25** [comment]
> /duplicate
> 
> It's the highest rated issue, we didn't forget about it. It was closed because it's just noise at this point so don't create more noise.

Was searching the same thing, but has there been any info from VSCode team about progress, timeline, issues?

**Comment by Tyriar** [comment]
It's still a hard problem to do in a performant way due to the way vscode was architected and how resources can't be shared across windows. These issues are explained somewhere in that issue and they are still relevant unfortunately.
