### ISSUE TITLE
Feature Request: Mark settings as overridden when they are

### ISSUE THREAD

**Issue by fadeevab** [Microsoft/vscode#17847]
- VSCode Version: 1.8.1
- OS Version: Ubuntu 14

I'm new to VS Code, and what situation I have. One day I redefined the setting **extensions.autoUpdate** by **true** value (**extensions.autoUpdate = true**). I forgot about after some time. Soon I looked for the current state of extensions.autoUpdate setting. So, what I've done - I went to Workspace Settings and what I see:
![autoupdate1](https://cloud.githubusercontent.com/assets/5967447/21497348/102293d0-cc2d-11e6-8a79-7272582fca09.png)

**extensions.autoUpdate = false**

Ok. But what we see in the User Settings:

![autoupdate2](https://cloud.githubusercontent.com/assets/5967447/21497357/1797d5f8-cc2d-11e6-8270-c71c8b80b8fd.png)

At the left pane **extensions.autoUpdate = false** again, but then we look to the right pane and there is **extensions.autoUpdate = true**.

**Request**: there should be the way to display current settings value at the **left pane** in the case when the option is overwritten.

Thank you!

**Comment by fadeevab** [comment]
I fixed the description: I meant the **left pain** to see current overwritten option state. Because now I should find the current option value "manually" at the right pain at some of User Settings (as I understand, options could be overwritten by Workspace Settings as well).

**Comment by sandy081** [comment]
I do not think this feature will be implemented in near future and we have built a new richer settings UI. So closing this in favour of the new UI.
