### ISSUE TITLE
Inconsistent profiles behavior

### ISSUE THREAD

**Issue by igorskyflyer** [microsoft/vscode#178421]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.76.2
- OS Version: Windows 10, 22H2 (19045.2788)

Little backstory: since the launch of Profiles inside VS Code, I had to switch machines and I exported the profile (the default one) of my old machine and imported it into the new machine.

Okay, the imported profile was a named one, since there is no option to import it as the default one (or did I miss something? 😯) which is fine I guess. I assumed once I select the profile it would always use that profile unless another is selected (?). The workaround that I found online was to pass a parameter of "`--profile <profileName>`" to the VS Code executable, so my Desktop shortcut looks like:

>> "C:\Users\SkyFlyer\AppData\Local\Programs\Microsoft VS Code\Code.exe" "--profile igorskyflyer"

but the inconsistent thing here is that, this method sometimes works, sometimes it doesn't. My VS Code is set to always launch fresh (no reopened windows, folders, etc.) and sometimes the default profile is selected sometimes the one I want to use.

Did I mess up something or is this the expected behavior - if not then it's a bug. 🐛

**Comment by sandy081** [comment]
Here is the documentation for this arg

```
Opens the provided folder or workspace with the given profile and associates the profile with the workspace. If the profile does not exist, a new empty one is created. A folder or workspace must be provided for the profile to take effect.
```

This works only if you pass the workspace/folder.
