### ISSUE TITLE
code.sh parses argument incorrectly

### ISSUE THREAD

**Issue by mrdrogdrog** [Microsoft/vscode#17852]
- VSCode Version: 1.8.1 - ee428b0eead68bf0fb99ab5fdc4439be227b6281
- OS Version: Arch Linux up to date

Steps to Reproduce:

1. Install Visual Studio Code via AUR
2. open terminal
3. input 'code a\ b\ c.txt' or 'code "a b c.txt"'
4. vscode opens and creates the tabs "a" "b" and "c.txt"

**Comment by mrdrogdrog** [comment]
See Pull Request https://github.com/Microsoft/vscode/pull/17853

**Comment by joaomoreno** [comment]
Fixed by #17853

**Comment by Tyriar** [comment]
Duplicates https://github.com/Microsoft/vscode/issues/17713 (already verified)
