### ISSUE TITLE
Strip trailing whitespace when using `Copy as HTML` in TERMINAL on Windows 

### ISSUE THREAD

**Issue by kdheepak** [microsoft/vscode#178547]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 

```
$ code --version
1.76.2
ee2b180d582a7f601fa6ecfdad8d9fd269ab1884
x64
```

- OS Version: 

![image](https://user-images.githubusercontent.com/1813121/228419631-37e59bb7-2387-49b1-97d1-2ff56ebd0b89.png)

Steps to Reproduce:

1. Run anything in VSCode's terminal:

![image](https://user-images.githubusercontent.com/1813121/228421750-33a35aff-eec8-43e7-8306-69c52e0eaf55.png)

2. Select Text and Copy as HTML
3. Paste in Word
4. Go to File -> Options -> Display -> Check the box for Spaces. You'll see the following in Word:

![image](https://user-images.githubusercontent.com/1813121/228420238-12544495-e60b-496b-9e53-64df6087a9d1.png)

The issue is that this makes it not practical to copy and paste code output into emails because when the recipient gets the email, their email is line wrapped, and it is printed all weird some times. Here's an example of the same output from earlier when I sent it as an email to myself:

![image](https://user-images.githubusercontent.com/1813121/228421060-842a7e48-7403-49d1-a7eb-88934cca67af.png)

I highlighted the text in the email to show the whitespaces. Basically it adds a new line because there's so much trailing whitespace.

This makes it not practical to share any kind of table or ascii output from the terminal in emails to coworkers.

**Comment by Tyriar** [comment]
I don't think we should do this, the more hacks we put on top of conpty the more complicated it will get, trialing whitespace may be desirable as well. Let's just wait for an eventual fix to land in conpty and until then deal with the whitespace, it's easy to remove it

**Comment by kdheepak** [comment]
Thanks for the comment and clarification that it is out of scope. Can you explain how it is easy to remove it though? If I paste the content in VSCode to strip the whitespace on save, it just pastes without any HTML formatting. Is this even possible to do programmatically?

**Comment by Tyriar** [comment]
You could do it by search and replacing a regex (\s+$) or via a formatter

**Comment by JohnEricson** [comment]
If I'm not mistaken this feature is implemented in Windows Terminal so I'm guessing it's implemented in conpty as well as that is what Windows Terminal uses?
I can enable and disable this behavior in WT like this:
![image](https://github.com/user-attachments/assets/c47b780c-f73e-4191-900d-63782e2a36cc)

It would be nice to have the same option in VS Code.

**Comment by Tyriar** [comment]
@JohnEricson coming soon (https://github.com/microsoft/vscode/issues/224488) conpty will mostly use a "passthrough" mode which will avoid all the screen reprints which cause this whitespace. So I expect this issue to be mostly gone after that issue is done.
