### ISSUE TITLE
Extensions panel is completely blank - error:  we.show is not a function 

### ISSUE THREAD

**Issue by 99snowleopards** [microsoft/vscode#178537]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.76.2
- OS Version: Windows 11

Hello,

 The Extensions panel has gone completely blank - some of the extensions are still working though.

 when I click on the refresh on the top of the Extensions panel, I get the error: `we.show is not a function` 

On running Extension Bisect - it says `this might be a problem with Code`

I'd greatly appreciate any help to resolve this, thank you

**Comment by sandy081** [comment]
Can you please share the error from the console - `F1 > Developer: Toggle Developer Tools` ?

**Comment by 99snowleopards** [comment]
thank you for replying - here it is

![dt_err_1](https://user-images.githubusercontent.com/19656808/228573087-0a111c84-7d39-4aaa-a5c4-b2c74a0de5a2.png)

please let me know if you'd like any further information, thank you

**Comment by 99snowleopards** [comment]
Hi @sandy081  - please let me know if you'd like any further information or have any suggestions to fix this issue, thank you

**Comment by 99snowleopards** [comment]
updating VSCode to the latest version changed the error a bit 

![vsc_err_2](https://user-images.githubusercontent.com/19656808/228953648-35f35b45-7ee6-465a-9b57-ad7813e7c50b.png)

**Comment by 99snowleopards** [comment]
Hi @sandy081  - hate to be bothering you about this, but do you have any feedback to fix the issue, or could you tag someone who might have some suggestions - thank you

**Comment by sandy081** [comment]
Can you please try updating to our latest version 1.77.0 and see if you can still reproduce it?  If you are able to reproduce, can you please provide steps from the step how you opened VS Code until you repro it?

**Comment by 99snowleopards** [comment]
no - since, I reinstalled VSCode, it's been working fine - not sure what caused the original issue though

**Comment by sandy081** [comment]
Hmm glad that it got fixed and sad that we cant repro it anymore. Without repro steps I am unsure if we can diagnose it. I would close this for now and lets reopen it if you see it again.

**Comment by drisspg** [comment]
I think a similiar error is happening to me. I have deleted the entire extensions folder and all that remains is argv in .vscode and still blank extenions window. When I click the panel an empty extension folder with the empty json is created. Still not changes to the window though
