### ISSUE TITLE
failed to format Python with yapf

### ISSUE THREAD

**Issue by tianxingyang** [Microsoft/vscode#17855]
- VSCode Version: Code 1.8.1 (ee428b0eead68bf0fb99ab5fdc4439be227b6281, 2016-12-19T14:49:23.350Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

|Extension|Author|Version|
|---|---|---|
|python|donjayamanne|0.5.5|
|cpptools|ms-vscode|0.9.3|
|vscode-icons|robertohuertasm|4.3.0|

---

In fact, I'm new to python and visual studio code. But I really cannot figure it out why I could use shift + alt + f to format my code in python when my vs code was still 1.6.0 and after upgrading my us code to 1.8.1 it fails to work.

**Comment by rebornix** [comment]
@tianxingyang can you check this issue with the python extension you are using? Maybe it's an known issue there so let's start with https://github.com/DonJayamanne/pythonVSCode

**Comment by dbaeumer** [comment]
This issue was moved to DonJayamanne/pythonVSCode#612
