### ISSUE TITLE
Hot-close changes line breaks from CRLF to LF

### ISSUE THREAD

**Issue by rogierschouten** [Microsoft/vscode#17857]
- VSCode Version: Code 1.8.1 (ee428b0eead68bf0fb99ab5fdc4439be227b6281, 2016-12-19T14:49:23.350Z)
- OS Version: Windows_NT ia32 10.0.10586
- Extensions:

|Extension|Author|Version|
|---|---|---|
|vscode-nsp|adambaldwin|1.0.1|
|vscode-markdownlint|DavidAnson|0.6.0|
|tslint|eg2|0.7.1|
|sass-lint|glen-84|0.0.3|
|vscode-guid|heaths|1.0.0|
|typescript-javascript-grammar|ms-vscode|0.0.13|
|debugger-for-chrome|msjsdiag|2.4.1|
|sass-indented|robinbentley|1.3.0|
|require-complete|sensourceinc|0.0.3|
|sort-lines|Tyriar|1.1.0|

---

Steps to Reproduce:

1. On Windows, open a TypeScript file with CRLF line breaks. Make a change (add a space) and close VSCode without saving
2. Open VSCode. All line breaks in the file are now linux line breaks, as indicated by my TSLint plugin.

**Comment by Tyriar** [comment]
Duplicate #17162, fixed in Insiders
