### ISSUE TITLE
[css] add coloring of @apply support

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode#17850]
_From @philippelesaux on December 16, 2016 18:9_

It looks like themes are not respecting the new @apply rules, at least in regards to color-coding.

Using 1.8.0 stable

![screen shot 2016-12-16 at 9 58 51 am](https://cloud.githubusercontent.com/assets/13442851/21273215/81c83eae-c390-11e6-8587-db99f0308e1f.png)

edit: This is the default dark theme, but I see the issue in Dracula, Light+, Monokai, and others

_Copied from original issue: Microsoft/vscode-css-languageservice#19_

**Comment by aeschli** [comment]
Syntax coloring is not provided by vscode-css-languageservice but by a text mate grammar.

**Comment by philippelesaux** [comment]
Thank you @aeschli for moving this to the appropriate project!

**Comment by aeschli** [comment]
This issue was moved to atom/language-css#130
