### ISSUE TITLE
Allow to configure the entries of the editor toolbar

### ISSUE THREAD

**Issue by alanbuchanan** [Microsoft/vscode#17854]
- VSCode Version: 1.9.0-insider
- OS Version: OSX El Capitan 10.11.4

Steps to Reproduce:

1. Open a file when the editor is open

<img width="842" alt="screenshot 2016-12-27 at 13 16 08" src="https://cloud.githubusercontent.com/assets/10364894/21500496/4f25ce12-cc37-11e6-8fb1-5661571306c5.png">

I personally never use these buttons and they take up valuable room for tabs.

**Comment by leaxoy** [comment]
looks a good idea , I didn't use it too

**Comment by bpasero** [comment]
Dupe.

**Comment by alanbuchanan** [comment]
@bpasero what was this a duplicate of please?

**Comment by bpasero** [comment]
@alanbuchanan https://github.com/Microsoft/vscode/issues/9378
