### ISSUE TITLE
typescript.preferences.importModuleSpecifierEnding

### ISSUE THREAD

**Issue by priyanshuagrawal** [microsoft/vscode#178586]
Type: <b>Bug</b>

Setting this preference to 'js' does not append .js to module imports

was working before the latest update

VS Code version: Code 1.76.2 (ee2b180d582a7f601fa6ecfdad8d9fd269ab1884, 2023-03-14T17:55:54.936Z)
OS version: Windows_NT x64 10.0.19045
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4460  CPU @ 3.20GHz (4 x 3200)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: unavailable_off<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: unavailable_off<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|19.85GB (12.31GB free)|
|Process Argv|--crash-reporter-id 0a93d2fb-4b17-491a-bae5-b0453abc72fb|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
copilot|Git|1.78.9758
vscode-edge-devtools|ms-|2.1.1
powershell|ms-|2023.2.1
pwa-studio|PWA|1.3.3
LiveServer|rit|5.7.9
markdown-all-in-one|yzh|3.5.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscoreces:30445986
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
nodejswelcome1cf:30587006
2e4cg342:30602488
pyind779:30671433
f6dab269:30613381
pythonsymbol12:30671437
2i9eh265:30646982
vsccsb:30677849
defaultazurewalk:30687958
pythonms35:30686772

```

</details>

**Comment by mjbvz** [comment]
Seems to work for me. Please provide steps to reproduce the issue

**Comment by priyanshuagrawal** [comment]
I have created a new windows user on the same machine, and tried to reproduce the bug, but the feature seems to work correctly.
I think that there must be some bad config file on the user the bug is occuring, could you point me to specific config files/folders, which i can delete, because reinstalling vscode did not work.

**Comment by priyanshuagrawal** [comment]
I have tried deleting all the folders i can locate in the appdata directory of the affected user, but the preference is not taking effect.

**Comment by MauroVinicius** [comment]
The same here, after the last update the automatic import of ts files ignore js extension, typescript not detect this import without js as error, the settings in vscode take no effect, i should delete some internal file or cache?

![image](https://user-images.githubusercontent.com/32529671/229259577-0777eacd-33f8-4e58-b957-d3238155d6c7.png)

![image](https://user-images.githubusercontent.com/32529671/229259606-671bf74b-8d2b-4d0a-a6f6-0b6b672b97c8.png)

**Comment by priyanshuagrawal** [comment]
@MauroVinicius Did you find a way to make it work, i have already tried deleting all the folders i could find for vscode in the appdata directory of the affected user on windows 10, but it is still not working.

**Comment by MauroVinicius** [comment]
unfortunately I didn't find the solution, I'm in the same situation as you needing help, I didn't reinstall vscode because that's a little more difficult for me, I have deadlines to meet with some urgency

**Comment by MauroVinicius** [comment]
> @MauroVinicius This setting is only about the preferred import style added for auto imports. It will not causes TS to show those imports as errors
> 
> @priyanshuagrawal Please share detailed steps to reproduce the problem so we can investigate

I understand, in this case there is some typescript configuration to point this as an error? I looked but I didn't find

**Comment by priyanshuagrawal** [comment]
@mjbvz you are correct in regard to your earlier comment that this setting is about preferred import style, but could you guide me if possible, what can i do to assist you, because i don't see any way that could help, you trace this issue. i am new to vscode i primarily use vs2019, but i have tried some features of vscode, like workspace splitting to new window, but at the time of writing i am unable to locate such option

**Comment by priyanshuagrawal** [comment]
@mjbvz have a look, this is the setting i have set in preferences,

![Screenshot 2023-04-04 172538](https://user-images.githubusercontent.com/5511131/229784295-7a1e4db7-9f5e-4f47-81fd-0309c456089a.png)

and even with that setting i am not getting modules imported with js extension

![Screenshot 2023-04-04 172628](https://user-images.githubusercontent.com/5511131/229784646-142eab50-9e5a-4c57-8292-e7ace89b4e1a.png)

but before it was working correctly

**Comment by priyanshuagrawal** [comment]
> I have created a new windows user on the same machine, and tried to reproduce the bug, but the feature seems to work correctly. I think that there must be some bad config file on the user the bug is occuring, could you point me to specific config files/folders, which i can delete, because reinstalling vscode did not work.

I have mentioned before that, this issue is specific for the windows user i am currently using.
Issue does not occur on a new user of the same windows machine, with the same vscode.

**Comment by mjbvz** [comment]
Please try collecting the TS Server log:

1. Set `"typescript.tsserver.log": "verbose",`
1. Restart VS Code and reproduce the problem
1. In VS Code, run the `TypeScript: Open TS Server log` command
1. This should open a large log file called `tsserver.log` 

This should show if the setting is being set properly

 > **⚠️Warning:** The TypeScript log may include information from your workspace, including file paths and source code. If you have any concerns about posting this publicly on Github, just let me know and we can arrange something else. On our side, we only use these logs to investigate issues like this

**Comment by MauroVinicius** [comment]
I generated this log on my pc and hid some sensitive information but my log has about 60,000 lines, even so it would be nice if I didn't have to make it completely public, is there any more private way to send it?

Anyway I looked at the log here and maybe these parts will help you guys a little, screenshots below

![image](https://user-images.githubusercontent.com/32529671/229973939-7a3496e1-7426-49ba-b7f2-a52b352a79d9.png)
![image](https://user-images.githubusercontent.com/32529671/229973991-79f1ba53-d581-4a23-b2a5-e55f96674ebe.png)
![image](https://user-images.githubusercontent.com/32529671/229974129-eb4bb5f6-087a-4a4a-aea8-5baf1b20b687.png)
![image](https://user-images.githubusercontent.com/32529671/229974291-52fc4d04-925c-486d-8227-ddbd7d9f01b6.png)




> Please try collecting the TS Server log:
> 
> 1. Set `"typescript.tsserver.log": "verbose",`
> 2. Restart VS Code and reproduce the problem
> 3. In VS Code, run the `TypeScript: Open TS Server log` command
> 4. This should open a large log file called `tsserver.log`
> 
> This should show if the setting is being set properly
> 
> > **⚠️Warning:** The TypeScript log may include information from your workspace, including file paths and source code. If you have any concerns about posting this publicly on Github, just let me know and we can arrange something else. On our side, we only use these logs to investigate issues like this

**Comment by MauroVinicius** [comment]
Good news, i changed my typescript version in vscode by config `typescript.tsdk`, my pc use 4.9.4 and my vscode was using 5.02, after i change vscode to 4.9.4 by this config and restart the software the problem was resolved, @priyanshuagrawal try this solution

**Comment by priyanshuagrawal** [comment]
> Good news, i changed my typescript version in vscode by config `typescript.tsdk`, my pc use 4.9.4 and my vscode was using 5.02, after i change vscode to 4.9.4 by this config and restart the software the problem was resolved, @priyanshuagrawal try this solution

@mjbvz @MauroVinicius many thanks, that helped and i have resolved this issue.
