### ISSUE TITLE
Please add the option to remove the blobs on the right hand side scrollbar

### ISSUE THREAD

**Issue by alanbuchanan** [Microsoft/vscode#17858]
VSCode Version: 1.9.0-insider
OS Version: OSX El Capitan 10.11.4

Steps to Reproduce:

1. Open a file when the editor is open
2. Click on some text that also appears in another part of the file

In the below example, I have clicked on a `<ul>` tag. 

![image](https://cloud.githubusercontent.com/assets/10364894/21504250/1baeeb90-cc55-11e6-93c0-c3c2e266ad0a.png)

There are two other parts of the file where this text occurs; the closing `</ul>` tag, and a completely unrelated word, `default`, which just happens to also contain the text `ul`.

It's not useful for this to be highlighted. In fact, it's confusing and distracting.

Please add the option to toggle the appearance of these blobs.

**Comment by vorov2** [comment]
Word highlighting is controlled by the search settings. Alt+W will force it to highlight only the whole words which makes more sense IMO.

**Comment by alanbuchanan** [comment]
@vorov2 That sounds useful, I can't find it though. `Alt + W` inserts a ∑ for me. What's the name of the command?

**Comment by vorov2** [comment]
@alanbuchanan Not sure what the command name is, can't find it in palette. You can, however, open a search popup and hover over a small "Match whole word" icon in the input. It would show you a shortcut for your system in the tooltip.

**Comment by rebornix** [comment]
@alanbuchanan @vorov2 the command is `Alt+C / R / W Toggle case-sensitive / regex / whole word`, you can see that in https://code.visualstudio.com/shortcuts/keyboard-shortcuts-windows.pdf
