### ISSUE TITLE
Missing File Explorer in the activity bar and Windows Menu Item

### ISSUE THREAD

**Issue by hari201909** [microsoft/vscode#178543]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.76.2
- OS Version: Windows 10 Pro 10.0.19045 Build 19045

The File Explorer button is missing from the activity bar, right clicking on the activity does not list Explorer as an option either. Secondly the windows menu in the tool bar is missing when this happens. Both the file explorer and the windows menu are present if I open visual studio code from the windows search bar instead of right-clicking on the workspace folder and selecting the "Open with Code" option. But they disappear as soon as a folder is opened.

I have attached the image of the issue below

Things I have attempted to fix the problem with no success
1) Tried to create the project in a new folder, as soon as I open a folder in visual studio code the icon dissapears
2) Tried to uninstall and reinstall visual studio code, this has no impact on the issue.

Thanks!

Steps to Reproduce:

1.  I am unable to bring back either the file explorer icon or the windows menu item to reproduce the steps.

![image](https://user-images.githubusercontent.com/129242476/228410162-14934c04-e86c-48b4-9574-113273f662fb.png)

**Comment by lramos15** [comment]
`CTRL + SHIFT + P` -> `Reset View Locations`

**Comment by hari201909** [comment]
Thank you. I appreciate the response, I didn't realize there was a way to reset.
