### ISSUE TITLE
Paths in terminal from C++ output are not properly detected as links when spaces are present in path. 

### ISSUE THREAD

**Issue by sebastien-ssdc** [microsoft/vscode#178584]
Does this issue occur when all extensions are disabled?: Yes/No
Yes

Version: 1.76.2 (user setup)
Commit: ee2b180d582a7f601fa6ecfdad8d9fd269ab1884
Date: 2023-03-14T17:55:54.936Z
Electron: 19.1.11
Chromium: 102.0.5005.196
Node.js: 16.14.2
V8: 10.2.154.26-electron.0
OS: Windows_NT x64 10.0.22621
Sandboxed: No

Problem:

There are some situations where the a path cannot be completely be detected as a link when spaces are contained in the path. This can be easily be reproduced when a compilation error/warning is reported from a file in Program Files (Windows).

Here are some example of file paths not being detected properly with different compilers.

Visual Studio (CL)
![image](https://user-images.githubusercontent.com/84924001/228572875-ebafb367-a72e-40d6-905c-a37b9b9f2dcf.png)

Clang:
![image](https://user-images.githubusercontent.com/84924001/228571097-58f33517-1c49-4932-8099-cf9e71f41578.png)

nvcc (NVIDIA CUDA compiler)
![image](https://user-images.githubusercontent.com/84924001/228573872-d0467c86-421d-4071-832b-9a6005697ff1.png)

Surprisingly, this use case works (nvcc):
![image](https://user-images.githubusercontent.com/84924001/228573331-c520f32e-b96f-4b30-af37-f8055e8db441.png)

Steps to Reproduce:

1. Create a C++ file in a folder that contains a space
2. Compile that file in the terminal (I am launching the compiler as a task)

**Comment by meganrogge** [comment]
I believe this is already fixed, can you see if you can reproduce in the [Insiders build](https://code.visualstudio.com/insiders)?
/label info-needed

**Comment by Tyriar** [comment]
The link improvements that cover this were in 1.75: https://code.visualstudio.com/updates/v1_75#_link-improvements

This is why the 4th case is working. Will look into it

**Comment by sebastien-ssdc** [comment]
> I believe this is already fixed, can you see if you can reproduce in the [Insiders build](https://code.visualstudio.com/insiders)? /label info-needed

I am reproducing the same behavior with the Insider build :

Version: 1.77.0-insider (user setup)
Commit: 7f329fe6c66b0f86ae1574c2911b681ad5a45d63
Date: 2023-03-29T09:56:00.839Z
Electron: 19.1.11
Chromium: 102.0.5005.196
Node.js: 16.14.2
V8: 10.2.154.26-electron.0
OS: Windows_NT x64 10.0.22621
Sandboxed: Yes

**Comment by sebastien-ssdc** [comment]
Thank you for your quick response!
