### ISSUE TITLE
Improve notebook accessibility

### ISSUE THREAD

**Issue by amunger** [microsoft/vscode#178630]
* [x] https://github.com/microsoft/vscode/issues/174984 
* [ ] https://github.com/microsoft/vscode/issues/176292
* [x] https://github.com/microsoft/vscode/issues/176293
* [x] https://github.com/microsoft/vscode/issues/176284
* [x] https://github.com/microsoft/vscode/issues/176286
* [x] https://github.com/microsoft/vscode/issues/180970

**Comment by rebornix** [comment]
Some relevant issues https://github.com/microsoft/vscode/issues/90408 https://github.com/microsoft/vscode/issues/111255

**Comment by r3m0t** [comment]
#161925

**Comment by amunger** [comment]
there are still some big accessibility issues as noted in https://github.com/microsoft/vscode/issues/176292#issuecomment-1563457608, but I'll call this first pass complete so we can organize the next set of work to tackle.
