### ISSUE TITLE
Backspace takes about 20 seconds to execute most of the time

### ISSUE THREAD

**Issue by Dan-yelp** [microsoft/vscode#178646]
Type: <b>Bug</b>

Some keys take a long time to work (~1-20 seconds). Specifically, backspace takes about 20 seconds most of the time, ctrl+c and ctrl+v take about 10 seconds each. Return is sometimes immediate and sometimes delayed by about 2 seconds. I've reset all my settings to factory, and completely removed VS code drom my machine and reinstalled it to no avail.

VS Code version: Code 1.76.2 (ee2b180d582a7f601fa6ecfdad8d9fd269ab1884, 2023-03-14T17:55:54.936Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 4700U with Radeon Graphics          (8 x 1996)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.37GB (5.03GB free)|
|Process Argv|--crash-reporter-id 2fcc4f4d-62f9-4e03-8797-356c252a81fe|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (68)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|13.3.1
project-manager|ale|12.7.0
All-Autocomplete|Ati|0.0.26
codestream|Cod|14.17.0
gitignore|cod|0.9.0
doxdocgen|csc|1.4.0
macros|ctf|0.1.0
arm|dan|1.7.4
c-cpp-compile-run|dan|1.0.44
gitlens|eam|13.4.0
code-runner|for|0.12.0
vscode-pull-request-github|Git|0.60.0
todo-tree|Gru|0.0.224
vscode-settings-cycler|hoo|1.0.1
output-colorizer|IBM|0.1.2
easy-snippet|inu|0.6.3
customize-ui|ioc|0.1.65
monkey-patch|ioc|0.1.23
vscode-essentials|jab|1.6.0
search-editor-apply-changes|jak|0.1.1
hungry-delete|jas|1.7.0
better-cpp-syntax|jef|1.17.2
vscode-text-pastry|jkj|1.3.1
vscode-peacock|joh|4.2.2
chat|kar|0.35.0
vscode-format-context-menu|lac|1.0.4
vsls-whiteboard|los|0.0.12
metago|met|4.3.1
MetaJump|met|1.4.0
MetaWord|met|1.3.0
git-graph|mhu|1.30.0
vscode-checkpoints|mic|1.3.3
dotenv|mik|1.0.1
isort|ms-|2022.8.0
python|ms-|2023.4.1
vscode-pylance|ms-|2023.3.40
jupyter|ms-|2023.2.1200692131
jupyter-keymap|ms-|1.1.0
jupyter-renderers|ms-|1.0.15
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-slideshow|ms-|0.1.5
remote-containers|ms-|0.282.0
remote-ssh|ms-|0.98.0
remote-ssh-edit|ms-|0.84.0
remote-wsl|ms-|0.76.1
cmake-tools|ms-|1.13.45
cpptools|ms-|1.14.5
cpptools-extension-pack|ms-|1.3.0
remote-explorer|ms-|0.2.0
vsliveshare|ms-|1.0.5834
vsliveshare-audio|ms-|0.1.93
gremlins|nho|0.26.0
polacode|pnp|0.3.4
explorer-exclude-vscode-extension|Red|1.2.2
code-settings-sync|Sha|3.4.3
vscode-multiclip|sle|0.1.5
rewrap|stk|1.16.3
code-spell-checker|str|2.20.3
control-snippets|svi|1.9.1
best-dark-themes-pack|the|1.0.2
python|tht|0.2.3
pdf|tom|1.2.2
cmake|twx|0.0.17
intellicode-api-usage-examples|Vis|0.2.7
vscodeintellicode|Vis|1.2.30
gistfs|vsl|0.4.1
local-history|xyz|1.8.1
material-theme|zhu|3.15.8

(10 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vscaat:30438848
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
vsccc:30610678
nodejswelcome1:30587005
282f8724:30602487
pyind779:30671433
f6dab269:30613381
pythonsymbol12:30671437
a9j8j154:30646983
6233i204:30672705
vsctsb:30677850
defaultazurewalk:30687958
pythonms35cf:30686773

```

</details>

**Comment by alexdima** [comment]
Does this reproduce when disabling all extensions? Press `F1` and then choose `Developer: Reload Window with Extensions Disabled`

![Kapture 2020-07-20 at 15 28 23](https://user-images.githubusercontent.com/5047891/87943040-c3b02a80-ca9d-11ea-847d-5f850fae8f05.gif)

**Comment by Dan-yelp** [comment]
Good afternoon Alexandru, Disabling all extensions, then re-enabling only the ones I used fixed the issue. Do you know what extension causes this issue? Sincerely, Daniel J. ***@***.***@vcu.edu(804-605-4233 From: Alexandru DimaSent: Thursday, March 30, 2023 8:34 PMTo: microsoft/vscodeCc: Dan-yelp; AuthorSubject: Re: [microsoft/vscode] Keyboard Issues (Issue #178646) Does this reproduce when disabling all extensions? Press F1 and then choose Developer: Reload Window with Extensions Disabled—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by alexdima** [comment]
@Dan-yelp Since this no longer reproduce after disabling extensions, this indicates that this was a problem caused by one of your installed extensions. You can use extension bisect to narrow down the possible problematic extension:
* run `F1 > Help: Start Extension Bisect`
* (this will restart VS Code with half of your extensions disabled)
* try to do the steps which reproduce the problem
* if the problem reproduces, click "This is bad" (this narrows down the problematic extension to the half which was enabled)
* if the problem does not reproduce, click "Good now" (this narrows down the problematic extension to the half which was disabled)
* these steps will repeat until the problematic extension is found

| initial | step | final |
|---|---|---|
| ![image](https://user-images.githubusercontent.com/5047891/101918658-e9170f80-3bc9-11eb-9977-857baa291937.png) | ![image](https://user-images.githubusercontent.com/5047891/101918683-ef0cf080-3bc9-11eb-9f9e-98b0177991b2.png) | ![image](https://user-images.githubusercontent.com/5047891/101918706-f502d180-3bc9-11eb-8c86-e56355958bd4.png) |
