### ISSUE TITLE
Rust Tools Missing

### ISSUE THREAD

**Issue by htory327** [Microsoft/vscode#17866]
- VSCode Version: 1.8.1
- OS Version: OS X El Capitan 10.11.5

Steps to Reproduce:

1. Rust tool is missing, (Racer not found)x2 
2. All the tools are already installed
`cargo install racer && cargo install rustfmt && cargo install rustsym
[uacfw@uacfw ~/Desktop/Rust/projects/guessing_game]$ cargo install racer && cargo install rustfmt && cargo install rustsym
    Updating registry `https://github.com/rust-lang/crates.io-index`
error: binary `racer` already exists in destination as part of `racer v2.0.2`
Add --force to overwrite
[uacfw@uacfw ~/Desktop/Rust/projects/guessing_game]$`

**Comment by rebornix** [comment]
@htory327 I don't see anything related to VS Code, can you help understand what's your expected behavior of Code?

**Comment by Frederick888** [comment]
So just install them with `--force`, e.g. `cargo install racer --force`. It's none of VSC's business...

And you have to ensure the `PATH` environment variable is correctly set. Test it with `type racer`. I once used OS X for a while and the env vars of BASH was correctly read by VSC, however, if you've changed your (login) shell, make sure you don't mess it up.

**Comment by rebornix** [comment]
@Frederick888 thanks for your help!
