### ISSUE TITLE
Don't ship signing debug logs on Windows

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#1786]
My install dir is full with these:

![image](https://cloud.githubusercontent.com/assets/5047891/12112857/84dcef1a-b39f-11e5-854a-8776e70dfcd6.png)

**Comment by joaomoreno** [comment]
I have no idea how these are in there.

**Comment by alexandrudima** [comment]
I guess it's the signing step...? Each zip contains such a file

**Comment by joaomoreno** [comment]
They are surely signing logs. I just don't see them during the build step...

**Comment by joaomoreno** [comment]
Debt week.

**Comment by joaomoreno** [comment]
Closing as *don't see it anymore*.
