### ISSUE TITLE
Local extensions keep deleted 

### ISSUE THREAD

**Issue by surfinzap** [microsoft/vscode#178667]
Does this issue occur when all extensions are disabled?: Yes/No → I cannot check it because I cannot determine the precise STR.

- VS Code Version: 1.76.2
- OS Version: Windows 11 Pro

While this issue seems a bit similar to issues [#174238] or [#174401], I'm under the impression that it is a bit different. I have many extensions installed in VS Code, and I have no problem with them. Besides the installed extensions, I have one local extension (a VS Code theme) that I'm actively developing and using. By local extension, I mean an extension that is not installed, but I have it stored in `~\.vscode\extenstions\` folder. For the past few weeks, my local extension keeps being deleted from the VS code folder of extensions; see the screenshot from `shared`:
![image](https://user-images.githubusercontent.com/1387798/228790524-6ddd9465-9a5b-40f9-af88-acacb200eb9d.png)

Unfortunately, I cannot give you exact steps to reproduce, as it seems to me the deletion of local extension happens randomly. Some deletions happened after I restarted the PC and opened VS Code. Let me know what other info I can share to help you resolve this issue.

**Comment by sandy081** [comment]
> By local extension, I mean an extension that is not installed, but I have it stored in `~\.vscode\extenstions\` folder. 

I would recommend to use the command `Developer: Install Extension from Location` for this use case.

**Comment by surfinzap** [comment]
Thanks @sandy081 for the workaround. It seems like I need to `Install Extension from Location` every time I open the VS Code. Is there an option to keep the local extension installed even when I close/open the VS Code?

**Comment by sandy081** [comment]
You do not have to do that if you use this command. Are you seeing otherwise?

**Comment by surfinzap** [comment]
Yes, every time I close the VS Code, the extension I installed locally (using `Developer: Install Extension from Location`) gets uninstalled, and I have to install it again.

**Comment by sandy081** [comment]
Can you please share the following log when you close and reopen VS Code

- F1 > Open View... > Shared

**Comment by surfinzap** [comment]
That's the shared output after I open VS Code and `Install Extension from location`:
![image](https://user-images.githubusercontent.com/1387798/231280234-9b44009d-059a-4d14-bb88-f3985fa4d7ee.png)

When I close and reopen the VS Code, my Shared output is empty:
![image](https://user-images.githubusercontent.com/1387798/231279850-d69cc2ec-2805-48c4-ba77-20d1b316e1b1.png)

**Comment by sandy081** [comment]
In the extensions folder, can you see a file named `.obsolete` and let me know what that file contains?

**Comment by surfinzap** [comment]
sure, this is contents of the `obsolete` file:
```
{"ms-vscode.references-view-0.0.86":true,"ms-vscode.js-debug-companion-1.0.16":true,"ms-vscode.js-debug-companion-1.0.15":true,"brano.b-theme-0.3.0":true}
```

**Comment by sandy081** [comment]
Can you please remove `"brano.b-theme-0.3.0":true` from this file. This is causing the extension not to be shown again. I will reopen the issue to get this fixed.

**Comment by sandy081** [comment]
Can you please share the `package.json` of the extension you are installing?

**Comment by pwaller** [comment]
Per the above nix home-manager issue: I just observed all my extensions aside from (one newly installed one) being added to `.obsolete`. Removing the `.obsolete` file and running `code --list-extensions` seems to have set things back to normal.

(Context: home-manager sets up symlinks from `$HOME/.vscode/extensions/[extenson]` for configured extensions to a read-only store elsewhere on the filesystem. I recently added a single extension and observed all extensions becoming unavailable in vscode aside from the one added until I removed the .obsolete file and deleted the `.vscode/extensions/extensions.json`. Subsequently re-running fixed things).

**Comment by surfinzap** [comment]
hi @sandy081, I've removed `"brano.b-theme-0.3.0":true` from the obsolete.json file, the issue still persists. here's the extension's [package.json](https://github.com/surfinzap/b-theme-vscode/blob/main/package.json)

**Comment by sandy081** [comment]
If I understand correctly, you have this entry that is pointing to the location that does not exist and which is not getting cleaned up. If so it is a dup of https://github.com/microsoft/vscode/issues/175070

**Comment by surfinzap** [comment]
Yeah, you're correct.
