### ISSUE TITLE
Support API to get the debug console for a specific debug session

### ISSUE THREAD

**Issue by ono-max** [microsoft/vscode#178655]
This is almost the same request as https://github.com/microsoft/vscode/issues/104208.

I'm a contributor for [Ruby debugger for VS Code extension](https://github.com/ruby/vscode-rdbg), and we currently have a problem such as https://github.com/ruby/vscode-rdbg/issues/111. All stdout/stderr are sent to only one of the "Debug Console" when we have multiple debug sessions. 

We can use [output event](https://github.com/microsoft/vscode/blob/eebfafcc96523075cdca0e033a28ef3b5346af5e/src/vs/workbench/contrib/debug/common/debugProtocol.d.ts#L206) to fix this problem, but it's hard to maintenance [the implementation](https://github.com/ruby/vscode-rdbg/pull/188/files#diff-04bba6a35cad1c794cbbe677678a51de13441b7a6ee8592b7b50be1f05c6f626R325-R365).

Could you reconsider introducing API to fix this problem? Thank you.

**Comment by roblourens** [comment]
Sorry, I don't understand why this happens

> All stdout/stderr are sent to only one of the "Debug Console" when we have multiple debug sessions.

Can you explain some more? Are these two independent debug sessions or are there child processes/child sessions involved?

**Comment by ono-max** [comment]
> Are these two independent debug sessions or are there child processes/child sessions involved?

These are independent debug sessions. Here is a scenario.

Basically, all stdout/stderr are sent to "Debug Console" in our debugger as follows. We implement this feature using `vscode.debug.activeDebugConsole`(FYI: https://github.com/ruby/vscode-rdbg/blob/master/src/extension.ts#L851).

https://user-images.githubusercontent.com/59436572/229045999-98cc522f-4377-4fe7-8940-1226f1ab89af.mov

However, there is a problem when users want to have multiple debug sessions in a single window. The problem is that all logs go to active debug console as follows:

https://user-images.githubusercontent.com/59436572/229057237-03e55bc0-cad4-4d79-a0e9-13d847797d58.mov

In this example, the following logs should be outputted to the DebugConsole in the second debug session, but it's not.

```
DEBUGGER: Debugger can attach via UNIX domain socket (/var/folders/5j/z2c9zm7124q81f_py4xmd3scp7w9j7/T/ruby-debug-sock-746464807/ruby-debug-s15236-7857)
DEBUGGER: wait for debugger connection...
```

Does it make sense?

**Comment by roblourens** [comment]
Sure, but why isn't the output being sent back via DAP so that it's associated with the correct debug session?

**Comment by ono-max** [comment]
We don't implement the logic of capturing stdout/stderr in the debugger. To send back stdout/stderr via DAP, we have some ways:

1. Create a custom request to send back stdout/stderr to VS Code
For example, we can define the custom request such as "returnBackOutput".  We currently use [child_process.spawn](https://nodejs.org/api/child_process.html#child_processspawncommand-args-options) and capture all stdout/stderr. When something is outputted in stdout/stderr, we send the custom request to the debugger, and the debugger sends back [output event](https://github.com/microsoft/vscode/blob/eebfafcc96523075cdca0e033a28ef3b5346af5e/src/vs/workbench/contrib/debug/common/debugProtocol.d.ts#L206).
This implementation is easy, but it isn't the intelligent way.

2. Create a new process to capture all stdout/stderr in the debugger.
We may capture all stdout/stderr by wrapping debugging process in another process. However, there is a possibility of affecting performance problems because of running a new process. Also, it's hard to implement the logic in our current architecture.

As you can see, some ways support multiple debug sessions without API exist. However, they are workarounds, in my opinion. VScode extension for Go has the logic to fix the problem, such as [here](https://github.com/golang/vscode-go/blob/master/src/goDebugFactory.ts#L144-L232).

**Comment by roblourens** [comment]
Sorry, I still don't understand the problem. 

1. You don't need a "custom" request- you just need to send a normal OutputEvent. That is how debug adapters are designed to work

For 3, you are pointing at some generic code in vscode-go that transfers messages from the debug adapter stream to vscode. I don't think there is anything special to handle output there.

**Comment by ono-max** [comment]
> You don't need a "custom" request- you just need to send a normal OutputEvent. That is how debug adapters are designed to work.

To send stdout/stderr to DebugConsole, we have the following ways:

* Capture output in stdout/stderr in debugger, and send it to DebugConsole.
* Capture output in stdout/stderr in VS Code extension, and send it to DebugConsole.

Currently, we select the latter (Capture output in stdout/stderr in VS Code extension). We run a debugger in [child_process.spawn](https://nodejs.org/api/child_process.html#child_processspawncommand-args-options) and connector to the debugger in [vscode.DebugAdapterServer](https://code.visualstudio.com/api/references/vscode-api#DebugAdapterServer). Then, we send a message to DebugConsole in [DebugConsole.appendLine](https://code.visualstudio.com/api/references/vscode-api#DebugConsole) when something is outputted in stdout/stderr. We can't send OutputEvent to VS Code from VS Code extension in this plan (Capture output in stdout/stderr in VS Code extension) because we use [vscode.DebugAdapterServer](https://code.visualstudio.com/api/references/vscode-api#DebugAdapterServer) and there is no way to send OutputEvent to VS Code from VS Code extension.

That's why we need a "custom" request in this case. Does it make sense?

> And in 2 I don't understand what creating a "new process" has to do with anything.

2 is the the former approach (Capture output in stdout/stderr in the debugger, and send it to DebugConsole). Ruby has a similar method to [child_process.spawn](https://nodejs.org/api/child_process.html#child_processspawncommand-args-options). To capture all stdout/stderr in the debugger, we can run a debugger with a method such as [child_process.spawn](https://nodejs.org/api/child_process.html#child_processspawncommand-args-options).

> For 3, you are pointing at some generic code in vscode-go that transfers messages from the debug adapter stream to vscode. I don't think there is anything special to handle output there.

vscode-go uses the latter (Capture output in stdout/stderr in VS Code extension) approach. I think it's easy to understand the approach in [this commit](https://github.com/golang/vscode-go/commit/93ee1d22ac928171e045acabe97e4e91a850a716). Instead of using [vscode.DebugAdapterServer](https://code.visualstudio.com/api/references/vscode-api#DebugAdapterServer), they implement the logic in DAP such as [here](https://github.com/golang/vscode-go/blob/master/src/goDebugFactory.ts#L198-L232). If we use [vscode.DebugAdapterServer](https://code.visualstudio.com/api/references/vscode-api#DebugAdapterServer), we don't need to implement it.

**Comment by roblourens** [comment]
Thanks, but I guess I still don't understand why the debugger that you spawned produces other DAP messages but doesn't produce OutputEvents, and OutputsEvents have be tacked on separately through special vscode-only API.

One problem with implementing your debug adapter using special vscode API is that it will only work in vscode, not in other DAP clients. This defeats the purpose of DAP at all to some extent.

You might also be interested in just running your debuggee in the terminal, that way its stdout/err will always be captured there

**Comment by ono-max** [comment]
> One problem with implementing your debug adapter using special vscode API is that it will only work in vscode, not in other DAP clients. This defeats the purpose of DAP at all to some extent.

Thank you for your explanation. It makes sense, but let me explain why we need this feature one last time.

We have the following options to debug programs:

* [Terminal](https://code.visualstudio.com/api/references/vscode-api#Terminal) mode
* [DebugConsole](https://code.visualstudio.com/api/references/vscode-api#DebugConsole) mode

The reason why we have [DebugConsole](https://code.visualstudio.com/api/references/vscode-api#DebugConsole) mode
is faster than [Terminal](https://code.visualstudio.com/api/references/vscode-api#Terminal) mode when starting the debugger. Thus, we'd like to use [DebugConsole](https://code.visualstudio.com/api/references/vscode-api#DebugConsole) mode as a default. To use it easily it would be great to introduce a new API to get the debug console for a specific debug session.

**Comment by roblourens** [comment]
I think my answer for this is just that DAs should try to do a proper DAP implementation that sends OutputEvents over DAP. Sorry if I am not understanding why that is impossible.

**Comment by ono-max** [comment]
@roblourens 
I'd appreciate it if you keep in mind that capturing stdout/stderr in the debugger is hard (although it depends on the programming language). Thank you.
