### ISSUE TITLE
Have terminal support Unicode version 14

### ISSUE THREAD

**Issue by erf** [microsoft/vscode#178677]
I'm working on a terminal app and i noticed that the width of some characters e.g. the red heart emoji "❤️" is only one character, whilst in Unicode 14 it takes up 2 columns, and this messes up the cursor position for me as I'm using a package to calculate the character width based on the latest standard.

I can read in the settings that you only support Unicode version 6 and 11 and would like to suggest that you also support Unicode version 14 (or even 15?).

Relevant setting:
```
terminal.integrated.unicodeVersion
```

**Comment by luv-deluxe** [comment]
@erf 
In powershell console I have
![image](https://user-images.githubusercontent.com/51136646/232792532-cb661ea2-9803-4d2b-ae29-2650535f84c3.png)

but in integrated VS one I see
![image](https://user-images.githubusercontent.com/51136646/232792714-a6fde638-fc23-4e5b-a22e-f97f883439d4.png)

Is there a chance it is connected with this issue?

**Comment by Tyriar** [comment]
Unicode v15 support is likely coming with https://github.com/xtermjs/xterm.js/pull/4519

@luv-deluxe the unicode version only determines the width of the characters, your issue is tracked in https://github.com/xtermjs/xterm.js/issues/2693

**Comment by Tyriar** [comment]
Let's track this upstream: https://github.com/xtermjs/xterm.js/issues/2693

/duplicate
