### ISSUE TITLE
can't duplicate

### ISSUE THREAD

**Issue by JonathanCramer** [Microsoft/vscode#17862]
- VSCode Version: 1.7.1 (1.7.1)
- OS Version: macOS Sierra 10.12.2

well i can't duplicate so it's not for me, i'll be back in case you add this function...

**Comment by mrmlnc** [comment]
What you don't can duplicate? What are you talking about?

**Comment by rebornix** [comment]
Are you saying split window?

**Comment by Hotkajun** [comment]
nova-tmtheme

**Comment by sandy081** [comment]
I do not understand what you mean by not duplicate nova-tmtheme. Please provide what exactly the  issue / feature you are looking for. Thanks.
