### ISSUE TITLE
Colors in gutter that track changes do not appear on specific files

### ISSUE THREAD

**Issue by armin-164** [microsoft/vscode#178604]
I'm having an issue where my VSCode doesnt track changes. So as you know, when you add code that is different to your recent commit, it adds a color next to the line number. I've had no issues with these colors and been using VSCode for a while now.

The colors still work but not on specific files. 

I did reinstall VSCode (I removed it completely and then reinstalled it), and that seemed to fix the issue regarding that file. But now I created another file and it doesn't work anymore. So it doesnt seem like a setting issue. All files created from now on don't track changes (and yes they are pushed to github).

In this pic, I have two js files, both are on my github but as you can see, the createMainSection.js doesnt show the colors. I can solve this by reinstalling again but the issue would appear for a file created after this. 

![image](https://user-images.githubusercontent.com/120616165/228621055-3526d56f-8aa8-4239-8e06-2c624f51e884.png)

I do not know how to recreate this issue. I've looked since yesterday for help but nothing works, no setting change, reset, reinstall etc.

Version: 1.76.2 (user setup)
OS: Windows_NT x64 10.0.19045

Extension: ESLint, Prettier, Live Server, Material Icon Theme (Ive always had these)

**Comment by lszomoru** [comment]
@armin-164, apologies for not getting back to you on this until now. I was wondering if you are still able to reproduce this issue with the latest version of VS Code? If you are still able to reproduce the issue please let me know and I will share steps to collect further information so that we can track down the root cause. Thanks!
