### ISSUE TITLE
Add line number text property

### ISSUE THREAD

**Issue by Gilgamesh22** [Microsoft/vscode#17867]
Currently there is no way to change the line number text in vscode. the reason I am asking for this is because I would like to create a relative line number extension. This is helpful for vim users, who would like to know the number of lines from current selected.

**Comment by schmuli** [comment]
From the `settings.json` UI (formatted):

```js
   // Controls the display of line numbers. 
   // Possible values are 'on', 'off', and 'relative'. 
   // 'relative' shows the line count from the current cursor position.
  "editor.lineNumbers": "on",
```

Can you please check if that solves your issue?

**Comment by Gilgamesh22** [comment]
i don't want to turn it off i comply want to change the text displayed.

**Comment by rebornix** [comment]
We implemented `"editor.lineNumbers": "relative"` just for Vim users.

**Comment by Gilgamesh22** [comment]
thank you very much this is exactly what i wanted.
