### ISSUE TITLE
Can't debug C++ code in Vscode on Windows 10 with gdb [Cause found]

### ISSUE THREAD

**Issue by Shadoware** [microsoft/vscode#178641]
The debug in vscode was not working. When I press debug a c/c++ file in code runner button option or in the menu, the process seems to start and finish without the debug panel show variable, watchs and anything. I had no apparent error message.
In debug console, at botton the message was:
"please start a debug session to evaluate"
 
The problem was much alike this: https://github.com/microsoft/vscode-cpptools/issues/2842

I change the compiler from cygwin64 to mingW64 version from winlibs.com and reinstalled vscode. (removed all configs before)
I finally had an error message saying the file "Herança.exe" does no exist (but it actually exists and was compiled correctly)
**I replaced the "ç" to "c" in the file name and it worked.**

- VS Code Version: 1.76.2 (user setup)
Commit: ee2b180d582a7f601fa6ecfdad8d9fd269ab1884
Date: 2023-03-14T17:55:54.936Z
Electron: 19.1.11
Chromium: 102.0.5005.196
Node.js: 16.14.2
V8: 10.2.154.26-electron.0
OS: Windows_NT x64 10.0.19045
Sandboxed: Yes

- OS Version: Windows 10 -64bit 22H2

Steps to Reproduce:

1.  Create a c++ source file with non english only characters, like "Herança.cpp"
2. Try to debug with gdb in vscode.

**Comment by roblourens** [comment]
Please file this on the c++ debug extension, thanks
