### ISSUE TITLE
Shell script code highlighting broken again in 1.76.2 rom #173336 is back

### ISSUE THREAD

**Issue by philipmiesbauer** [microsoft/vscode#178672]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.76.2
- OS Version: Ubuntu 22.04

Steps to Reproduce:

1. Write a shell script with the following line "echo ${PWD}"
2. The variable using the expansion braces, does not get highlighted as shell script.

This is not a duplicate to #173336, but has returned with this release.

**Comment by alexr00** [comment]
Should be fixed in 1.77, which was released yesterday.

**Comment by philipmiesbauer** [comment]
Almost, but not quite.

The behaviour is better, not as I would expect it, or as it was. Also there is an inconsistency between using expansion and not using it, where without expansion the $ is highlighted in the variable colour, but with expansion it is not.

![image](https://user-images.githubusercontent.com/13796773/229081709-c8000127-ea48-4241-a104-4851e6ba662c.png)

The variable name gets highlighted in blue, but not the expansion or the `$` and the braces, can we update the strategy to highlight the whole expansion,as there inconsistency between using expansion and not using it now.

**Comment by alexr00** [comment]
I think this color difference is intentional and is a feature, but @jeff-hykin should be able to confirm this.

**Comment by jeff-hykin** [comment]
@phillipj it will depend on the theme.

By default the `$` in $VAR is tagged as both a variable and punctuation to try to try and not break existing theme choices. The `${}` in `${VAR:substituation/type/stuff}` is tagged as `punctuation.definition.variable`.

Even without changing themes though, you can pick for them to be any color you want.
I wrote a tutorial for it [over here](https://medium.com/@jeffhykin/how-to-customize-your-vs-code-text-colors-c0191155f41a)

**Comment by philipmiesbauer** [comment]
Thank you very much!
