### ISSUE TITLE
Failed to save 'myfile.html': The content on disk is newer. Click on Compare to compare your version with the one on disk.

### ISSUE THREAD

**Issue by DanZeuss** [Microsoft/vscode#17861]
- VSCode Version: 1.8.1
- OS Version: Microsoft Windows [Version 10.0.14393]

Steps to Reproduce:
1. Open a **Network Shared** folder (I'm using a Virtual Machine where the project has its folder shared)
2. Select a file and try to edit it;
3. Press CTRL+S twice quickly.

There is no Steps to Reproduce, however, it's the most common procedure to get this error.

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/13665

**Comment by bpasero** [comment]
@DanZeuss thanks for the steps btw, I am finally seeing the issue when working against network shares and think I can provide a fix for it.

**Comment by DanZeuss** [comment]
Thank you so much for paying attention @bpasero. I appreciate the work that you are doing and I'd love to fix this problem, however, I don't know where to start.

**Comment by bpasero** [comment]
No worries, I am on it 👍

**Comment by bpasero** [comment]
@DanZeuss  does it still reproduce with our latest insider builds? You can give our preview releases a try from: http://code.visualstudio.com/Download#insiders

**Comment by DanZeuss** [comment]
Hi @bpasero. The problem was fixed to me. Thanks
