### ISSUE TITLE
a few kbd shortcuts not working inside sidebar

### ISSUE THREAD

**Issue by sohamkorade** [microsoft/vscode#178671]
Type: <b>Bug</b>

1. Click on any file in sidebar
2. Press `F2` (the shortcut for rename file)

Expected result: an edit box appears to input new filename
Actual result: nothing happens

Notes:
`F3` (search) works
`Del` (delete file) doesn't work

VS Code version: Code 1.76.2 (ee2b180d582a7f601fa6ecfdad8d9fd269ab1884, 2023-03-14T17:57:21.103Z)
OS version: Linux x64 5.15.0-69-generic
Modes:
Sandboxed: No
Extensions: none

**Comment by sohamkorade** [comment]
Hi @ulugbekna,
It is working correctly now. Thanks!

By the way, what was the problem exactly?

**Comment by lramos15** [comment]
> By the way, what was the problem exactly?

You moved the explorer at one point even accidentally causing the context key expressions to get messed up. The fix allows the context key expressions to properly listen to the explorer moving around.
