### ISSUE TITLE
Right click menu displays as a horizontal list instead of a vertical list

### ISSUE THREAD

**Issue by papabryce** [microsoft/vscode#178749]
Type: <b>Bug</b>

Right click anywhere in the editor.

Expected Result:
Right clicking should produce a vertical context menu.

Current Result:
![image](https://user-images.githubusercontent.com/99450073/228997585-7280e490-a117-493a-8923-dc4e8486afb4.png)

VS Code version: Code - Insiders 1.78.0-insider (b1ad3f934ca87b76dac5cf3533fb172d1c30e6ba, 2023-03-30T18:30:01.170Z)
OS version: Windows_NT x64 10.0.22624
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|12th Gen Intel(R) Core(TM) i7-1260P (16 x 2496)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.61GB (14.58GB free)|
|Process Argv|--crash-reporter-id b26ffe13-222b-468a-a92b-945426c7f184|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (47)</summary>

Extension|Author (truncated)|Version
---|---|---
rust-bundle|1Yi|1.0.0
svelte-intellisense|ard|0.7.1
search-crates-io|bel|1.2.1
vscode-tailwindcss|bra|0.9.11
better-toml|bun|0.3.2
simple-react-snippets|bur|1.2.7
npm-intellisense|chr|1.4.4
vscode-eslint|dba|2.4.0
rust-syntax|dus|0.6.1
vscode-html-css|ecm|1.13.1
EditorConfig|Edi|0.16.4
prettier-vscode|esb|9.10.4
copilot|Git|1.78.9758
latex-workshop|Jam|9.8.2
rust-doc-viewer|JSc|3.0.4
vsc-python-indent|Kev|1.18.0
vscode-docker|ms-|1.24.0
vscode-edge-devtools|ms-|2.1.1
black-formatter|ms-|2022.6.0
isort|ms-|2022.8.0
python|ms-|2023.6.0
vscode-pylance|ms-|2023.3.40
jupyter|ms-|2023.3.1000892223
jupyter-keymap|ms-|1.1.0
jupyter-renderers|ms-|1.0.15
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-slideshow|ms-|0.1.5
remote-containers|ms-|0.289.0
remote-wsl|ms-|0.77.0
cpptools|ms-|1.14.5
vscode-typescript-next|ms-|5.1.20230329
autodocstring|njp|0.6.1
paste-and-indent|par|0.1.0
vscode-paste-and-indent|Rub|0.0.8
rust-analyzer|rus|0.3.1451
crates|ser|0.5.10
markdown-preview-enhanced|shd|0.6.8
code-spell-checker|str|2.20.3
svelte-vscode|sve|107.2.5
tauri-vscode|tau|0.2.6
errorlens|use|3.8.0
vscode-lldb|vad|1.9.0
intellicode-api-usage-examples|Vis|0.2.7
vscodeintellicode|Vis|1.2.30
vscode-icons|vsc|12.2.0
markdown-all-in-one|yzh|3.5.1
material-theme|zhu|3.15.8

(4 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythontb:30258533
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscod805cf:30301675
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30404738
cppdebug:30492333
vscaac:30438845
vsclangdf:30492506
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30618038
pylantcb52:30590116
nodejswelcome1:30587009
pyind779:30611226
pythonsymbol12:30651887
2i9eh265:30646982
6233i204:30659907
pythonb192cf:30661257
functionswalk:30687959
pythonms35:30671666
j16hj152:30680472
24365598:30687740
pythonclientmv:30700173

```

</details>

**Comment by jaekook** [comment]
Mine too.

**Comment by asvishnyakov** [comment]
Mine looing the same

**Comment by papabryce** [comment]
Closing the issue. This is a duplicate of [#178730](https://github.com/microsoft/vscode/issues/178730)
