### ISSUE TITLE
an AI based  build-in vscode-usage-helper

### ISSUE THREAD

**Issue by heartacker** [microsoft/vscode#178770]
user can ask the question about vocode usage and question only

**Comment by jrieken** [comment]
https://code.visualstudio.com/blogs/2023/03/30/vscode-copilot

**Comment by heartacker** [comment]
I think the ai just for vscode usage and user can use it without a subscription
Github Copilot just for coding and
What I say is just about vscode usage

SO I think you misunderstood my perpose
