### ISSUE TITLE
Workbench keyboard shortucts not consistently working

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#17877]
- VSCode Version: insiders
- OS Version: os x

Steps to Reproduce:

1. `cmd+k w`
2. Action gets ignored -> not all editors get closed in the group
3. When i trigger "close all editors in group" via command pallete all works as expected

**Comment by isidorn** [comment]
Also seems to happen for cmd + 1, cmd + 2 for opening editor groups side by side.
Adding important as this is making my development flow painful

fyi @jrieken

**Comment by jrieken** [comment]
this might be a dupe of #17874

**Comment by bpasero** [comment]
Caused by https://github.com/Microsoft/vscode/commit/bc46e789ac57f327f409260fb8cc1f6e40e62a7b

**Comment by isidorn** [comment]
Fixrd by revertign commit
