### ISSUE TITLE
explorer display folder is symbolic incorrectly

### ISSUE THREAD

**Issue by tjx666** [microsoft/vscode#178723]
https://user-images.githubusercontent.com/41773861/228953537-db765845-7f47-41e1-978d-56eda8199f0e.mov

reproduce steps:

1. git clone git@github.com:tjx666/module-resolution.git
2. git reset --hard 126808cb72b1cfa5d1f0d0c6a3f25ed69491f536
3. pnpm install
4. open apps/esm-app/node_modules, you can see vscode show the folder `commonjs` is a symbolic link
5. delete folder apps/esm-app/node_modules/commonjs
6. copy packages/commonjs to folder apps/esm-app/node_modules/commonjs
7. the vscode still show folder apps/esm-app/node_modules/commonjs is a symbolic link, but actually not

<img width="920" alt="image" src="https://user-images.githubusercontent.com/41773861/228955043-c91f59bf-7f12-4d25-8758-732e3fd5b542.png">

**Comment by lramos15** [comment]
Does it stay that way after a reload? I know we have some refreshing issues surrounding symbolic links

**Comment by tjx666** [comment]
> Does it stay that way after a reload? I know we have some refreshing issues surrounding symbolic links

After reload, vscode show correctlly

**Comment by lramos15** [comment]
\duplicate https://github.com/microsoft/vscode/issues/167146


There's a PR that the user is working on but there seems to be some perf questions.
