### ISSUE TITLE
Weird behavior in syntax highlighting

### ISSUE THREAD

**Issue by iMasoud** [Microsoft/vscode#17879]
- VSCode Version: 1.8.1 (Commit ee428b0eead68bf0fb99ab5fdc4439be227b6281)
- OS Version: LinuxMint 18 KDE

Steps to Reproduce:

1. Create a new .js file in vscode
2. Paste content of attached file

Then here is how the syntax highlighting looks like:
![screenshot_ _](https://cloud.githubusercontent.com/assets/9999208/21525805/def77538-cd34-11e6-96ab-57ead320d248.png)

As you can see syntax highlighting of line 18 is wiered. Now:

3. Move 18th-line up
And you will see that the weird syntax highlighting is fixed:
![screenshot_ _](https://cloud.githubusercontent.com/assets/9999208/21525876/423ce90c-cd35-11e6-8ff7-b0ce61b029ba.png)

[vscode.txt](https://github.com/Microsoft/vscode/files/675833/vscode.txt)

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript-TmLanguage#391
