### ISSUE TITLE
[Terminal][macOS] Lost terminal output after clearing screen using `ctrl+l`

### ISSUE THREAD

**Issue by sridhargopinath** [microsoft/vscode#178743]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: Version: 1.77.0 (Universal)
- OS Version: macOS Ventura 13.3

Steps to Reproduce:

1. Print something to fill the entire screen
2. `ctrl+l`
3. Scroll up to see the previous output missing.

**Does not reproduce on iTerm2**

I have seen multiple issues around this topic but mostly on Windows and not on MacOS. I tried to reproduce on an iTerm2 terminal but doesn't reproduce. So something directly related to VSCode's integrated terminal.

https://user-images.githubusercontent.com/8598560/228989911-d30a4df3-6beb-4fd7-a929-2e087ba7e9cf.mov

**Comment by meganrogge** [comment]
works for me on macOS in insider's
https://user-images.githubusercontent.com/29464607/229181906-5911735c-f6f5-4bc8-b819-9f105469bf85.mov

**Comment by yamachu** [comment]
I met same issue.

```sh
$ for x in {1..50}; do print $x;done
```

The output seems to disappear after about 20 lines.

**Comment by sridhargopinath** [comment]
Yes, continues to be an issue even on Insider's build. Here's the screen capture:

https://user-images.githubusercontent.com/8598560/229244156-de3ca19a-d675-459e-a104-296de19890cf.mov

**Comment by sridhargopinath** [comment]
@Tyriar Could you please take a look?
