### ISSUE TITLE
Blue cell running spinner bar not visible sometimes

### ISSUE THREAD

**Issue by 2-5** [microsoft/vscode#178737]
### Applies To

- [X] Notebooks (.ipynb files)
- [ ] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

When you run a cell, a blue moving bar appears at the top of the cell indicating activity.

If you partially scroll the running cell out of view, so that the top of the cell is not visible, only the bottom, the blue moving bar is not shown anymore.

It will be shown at the top of the notebook if the cell is completely out of view, but not if only the top out of view.

https://user-images.githubusercontent.com/3753822/226939177-a848770c-209c-482e-a469-8099badf351d.mp4

### VS Code Version

Version: 1.76.2 (user setup) Commit: ee2b180d582a7f601fa6ecfdad8d9fd269ab1884 Date: 2023-03-14T17:55:54.936Z Electron: 19.1.11 Chromium: 102.0.5005.196 Node.js: 16.14.2 V8: 10.2.154.26-electron.0 OS: Windows_NT x64 10.0.19045 Sandboxed: No

### Jupyter Extension Version

 v2023.2.1200692131

### Running Jupyter locally or remotely?

Local

**Comment by roblourens** [comment]
There is a small dead spot where the cell progress bar is scrolled away but the editor one has not been shown yet. I pushed a change to adjust this, however, your gif seems to show a much larger dead spot than what I see. You can try this in the next VS Code Insiders build and let me know whether that helps, if not, please share all your notebook settings with me.

**Comment by 2-5** [comment]
Here are my notebook settings:

```json
"notebook.globalToolbar": false,
"notebook.consolidatedRunButton": true,
"notebook.consolidatedOutputButton": false,
"notebook.showCellStatusBar": "hidden",
"notebook.showFoldingControls": "always",
"notebook.insertToolbarLocation": "hidden",
"notebook.cellToolbarLocation": { "default": "hidden" },
```

There is another issue I sometimes encounter - the editor spinner can be shown on the wrong pane. I do not have clear reproduction steps:

https://user-images.githubusercontent.com/3753822/229101471-96d27926-7bde-4cfb-9905-a4ef870897b6.mp4

**Comment by roblourens** [comment]
Good finds - the offset comes from disabling the cell toolbarbar with `"notebook.cellToolbarLocation": { "default": "hidden" }`, and the progress bar shows in the wrong editor after moving the notebook editor between groups. Both should be fixed in my PR now.
