### ISSUE TITLE
Rename Jinja language to HTML

### ISSUE THREAD

**Issue by OliverJAsh** [Microsoft/vscode#17876]
When I'm changing language mode, I search for HTML and no results come up. It appears the language is instead called Jjina. Could we populate an entry in the list for HTML, to avoid confusion here?

**Comment by mrmlnc** [comment]
VS Code have no built-in support for Jjina. You can provide steps to reproduce your problem?

**Comment by OliverJAsh** [comment]
Apologies, it seems I had installed the Jinja extension, which removes HTML
from the list.

**Comment by OliverJAsh** [comment]
Apologies, it seems I had installed the Jinja extension, which removes HTML from the list.
