### ISSUE TITLE
Explorer is not listing Folders

### ISSUE THREAD

**Issue by venkat-8822** [microsoft/vscode#178777]
Type: <b>Bug</b>

Explorer is not listing Folders

VS Code version: Code 1.77.0 (7f329fe6c66b0f86ae1574c2911b681ad5a45d63, 2023-03-29T10:02:16.981Z)
OS version: Windows_NT x64 10.0.19045
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz (8 x 2995)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.66GB (18.41GB free)|
|Process Argv|--crash-reporter-id 597d8541-08ba-4b3d-80c3-c4c6e91e634a|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (38)</summary>

Extension|Author (truncated)|Version
---|---|---
project-manager|ale|12.7.0
jsonviewer|cci|1.3.2
npm-intellisense|chr|1.4.4
path-intellisense|chr|2.8.4
gitignore|cod|0.9.0
cucumber-official|Cuc|1.7.0
vscode-eslint|dba|2.4.0
git-extension-pack|don|0.1.3
githistory|don|0.6.20
gitlens|eam|13.4.0
vscode-npm-script|eg2|0.3.29
git-project-manager|fel|1.8.2
guilhermestella-java-ext|gui|0.0.5
search-node-modules|jas|1.3.0
shortcut-menu-bar|jer|3.0.4
karate|kar|0.6.0
karate-runner|kir|1.2.3
notepadplusplus-keybindings|ms-|1.0.7
gradle-language|nac|0.2.3
fabric8-analytics|red|0.3.6
java|red|1.16.0
vscode-xml|red|0.24.0
vscode-checkstyle|she|1.4.2
intellicode-api-usage-examples|Vis|0.2.7
vscodeintellicode|Vis|1.2.30
vscode-spring-boot|vmw|1.45.0
vscode-gradle|vsc|3.12.7
vscode-java-debug|vsc|0.49.1
vscode-java-dependency|vsc|0.21.2
vscode-java-pack|vsc|0.25.2023032708
vscode-java-test|vsc|0.38.2
vscode-maven|vsc|0.41.0
vscode-spring-boot-dashboard|vsc|0.12.0
vscode-spring-initializr|vsc|0.11.2
nodejs-extension-pack|wad|0.1.9
JavaScriptSnippets|xab|1.8.0
json|Zai|2.0.2
vscode-open-in-github|ziy|1.3.6

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263cf:30335440
vscorecescf:30445987
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
nodejswelcome1:30587005
2e4cg342:30602488
pyind779:30671433
89544117:30613380
pythonsymbol12:30671437
2i9eh265:30646982
6233i204:30672705
vsctsb:30677850
defaultazurewalk:30687958
pythonms35:30701012

```

</details>

**Comment by lramos15** [comment]
`CTRL + SHIFT + P` -> `Reset View Locations`
