### ISSUE TITLE
Unable to launch browser: "(void 0) is not a constructor"

### ISSUE THREAD

**Issue by proidit** [microsoft/vscode#178794]
Type: <b>Bug</b>

After update to 1.77.0 version, the chrome debug not starting with this error:

Unable to launch browser: "(void 0) is not a constructor"

i'm developing in angular

this  is the launch configuration:
{
  "version": "0.2.0",
  "configurations": [
    {
      "name": "Launch Chrome",
      "request": "launch",
      "type": "chrome",
      "url": "http://localhost:4206",
      "webRoot": "${workspaceFolder}"
    }
  ]
}

VS Code version: Code 1.77.0 (7f329fe6c66b0f86ae1574c2911b681ad5a45d63, 2023-03-29T10:02:16.981Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: Yes
Remote OS version: Linux x64 4.19.0-6-amd64
Remote OS version: Linux x64 4.19.0-6-amd64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz (8 x 2304)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.84GB (2.93GB free)|
|Process Argv|--crash-reporter-id 980a7598-8b1d-4740-ac85-4a1dcf232bcc|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: vm.vb.deb.10-50.2-FIDO.IW|
|OS|Linux x64 4.19.0-6-amd64|
|CPUs|Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz (4 x 2304)|
|Memory (System)|6.64GB (4.25GB free)|
|VM|100%|

|Item|Value|
|---|---|
|Remote|SSH: vm.vb.deb.10-50.2-FIDO.IW|
|OS|Linux x64 4.19.0-6-amd64|
|CPUs|Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz (4 x 2304)|
|Memory (System)|6.64GB (4.25GB free)|
|VM|100%|
</details><details><summary>Extensions (20)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|13.3.1
numbered-bookmarks|ale|8.3.1
vscode-firefox-debug|fir|2.9.8
auto-close-tag|for|0.5.14
output-colorizer|IBM|0.1.2
remote-ssh|ms-|0.98.0
remote-ssh-edit|ms-|0.84.0
remote-explorer|ms-|0.2.0
highlight-matching-tag|vin|0.11.0
ng-template|Ang|15.2.0
npm-intellisense|chr|1.4.4
path-intellisense|chr|2.8.4
vscode-eslint|dba|2.4.0
vscode-html-css|ecm|1.13.1
EditorConfig|Edi|0.16.4
vscode-duplicate|mrm|1.2.1
indent-rainbow|ode|8.3.1
vscode-fileutils|sle|3.10.1
vscode-status-bar-format-toggle|tom|3.1.1
rainbow-tags|vol|0.4.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
nodejswelcome1cf:30587006
2e4cg342:30602488
pyind779:30671433
89544117:30613380
pythonsymbol12:30671437
vsctsb:30677850
defaultazurewalk:30687958
pythonms35:30701012

```

</details>

**Comment by og900aero** [comment]
I have the same problem.

**Comment by proidit** [comment]
Only Launch firefox working
Not starting Launch Chrome and Launch Edge

**Comment by Wroud** [comment]
same here

**Comment by raulidavid** [comment]
Help me I upgrade the last version I have the same problem!!!

**Comment by stefhorst** [comment]
I get back to the version 1.7.6 for a quick solution, which is running well,  this was this only way for today ...

**Comment by OneCyrus** [comment]
I have this issue as well. Though only with remoting features. Local only it works. 
I reported it here as well: https://github.com/microsoft/vscode-remote-release/issues/8302

**Comment by connor4312** [comment]
Duplicates https://github.com/microsoft/vscode/issues/178786

**Comment by connor4312** [comment]
This is now fixed in the [nightly build](https://github.com/microsoft/vscode-js-debug#nightly-extension). Note that you will need to install that _in the remote workspace_. I will also propose it for a recovery release next week.

**Comment by junyorff12** [comment]
> This is now fixed in the [nightly build](https://github.com/microsoft/vscode-js-debug#nightly-extension). Note that you will need to install that _in the remote workspace_. I will also propose it for a recovery release next week.

It works fine. tks man!

**Comment by pbrns** [comment]
this kind of bugs are serious.. is like we need to stop and pause are development process because the tool has broken.
this is a very serious bug.

**Comment by wangf1978** [comment]
same issue hit, a sad day.

**Comment by Alia5** [comment]
> This is now fixed in the [nightly build](https://github.com/microsoft/vscode-js-debug#nightly-extension). Note that you will need to install that _in the remote workspace_. I will also propose it for a recovery release next week.

Does not work for me...  
Yes, the extension is installed in the remote-workspace.

**Comment by pbrns** [comment]
Because to attach to browser is very important for me with an ongoing project, and because the night build didn't work for me, I first set off all auto updates for VS code and extensions and secondly I installed the previous version of the VS Code (v1.76.2(I am on MacOS). Next I remove the js-debug extension and install the previous one manually from file (v1.76.1) to work again as it was.

**Comment by dugufu** [comment]
> This is now fixed in the [nightly build](https://github.com/microsoft/vscode-js-debug#nightly-extension). Note that you will need to install that _in the remote workspace_. I will also propose it for a recovery release next week.

U save my life bro thx
