### ISSUE TITLE
Add a Undo option in vscode 

### ISSUE THREAD

**Issue by kumarankit999** [microsoft/vscode#178792]
There should be a option of undo in this Vscode , because by chance if we delete the code mistakenly ,we have to write a rewrite the whole code .And why it is not there still today because in all Microsoft apps this feature is available.

**Comment by sontaimnt** [comment]
@kumarankit999 There is an undo option in Visual Studio Code which you can use by

- Pressing Ctrl+Z
- Edit -> Undo

**Comment by kumarankit999** [comment]
Is there only one tap option

**Comment by sontaimnt** [comment]
You mean a tool listing undoes and others?

**Comment by aeschli** [comment]
@kumarankit999 Please describe for which operation you are missing undo.

**Comment by kumarankit999** [comment]
There Should be Single Tap Icon in Vs Code for Undo Function Property

**Comment by aeschli** [comment]
What is a `Tap` icon?

**Comment by kumarankit999** [comment]
It means ,There will be a icon for Undo operation

**Comment by aeschli** [comment]
There are extensions that add such buttons. E.g.
https://marketplace.visualstudio.com/items?itemName=Hectoralvf.undo-redo-buttons
