### ISSUE TITLE
Split editor does not work

### ISSUE THREAD

**Issue by Gucin** [Microsoft/vscode#17871]
- VSCode Version: Code - Insiders 1.9.0-insider (58ab5ecdd9e54643e3ae9ae188021844329c0854, 2016-12-28T07:05:13.856Z)
- OS Version: Darwin x64 16.3.0
- Extensions:

|Extension|Author|Version|
|---|---|---|
|vscode-instant-markdown|dbankier|0.2.1|
|php-intellisense|felixfbecker|0.0.12|
|Angular1|johnpapa|0.1.16|
|vscode-apielements|vncz|0.6.0|

---

Steps to Reproduce:

1. Update to latest insider version and relaunch (version: 58ab5ecdd9e54643e3ae9ae188021844329c0854)
2. Split Editor using "Command+\\" or "View"->"Split Editor" does not work

The split button in the editor top-right corner can split the editor horizontally.

**Comment by bpasero** [comment]
Caused by https://github.com/Microsoft/vscode/commit/bc46e789ac57f327f409260fb8cc1f6e40e62a7b

**Comment by isidorn** [comment]
Reverted that commit
