### ISSUE TITLE
PHP Language Basics overrides Emmet.

### ISSUE THREAD

**Issue by kuyawayne** [microsoft/vscode#178750]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: Version: 1.77.0 (system setup)
- OS Version: Windows_NT x64 10.0.22621

Steps to Reproduce:

1. Add a new HTML tag with a class.
2. Hit tab.

PHP Language Basics automatically overrides Emmet selecting the wrong command instead of using Emmet. I know I could just uninstall/disable PHP Language Basics but that would mean I would lose all my PHP Syntax Highlighting. I want to keep both if possible as they are already vital to my workflow. Thank you.

https://user-images.githubusercontent.com/39961928/228997821-be5d336c-448d-4d29-8bde-0d51a48c3107.mp4

**Comment by roblourens** [comment]
I don't think you can use emmet inside a php string, because it is a string, not html code. If it works when disabling the php extension, that's probably because the whole file is treated as html, not php. I don't think it's really possible for us to support  this as you expect, sorry
