### ISSUE TITLE
GitHub Copilot but for VSCode Terminal

### ISSUE THREAD

**Issue by tigerinus** [microsoft/vscode#178747]
It'd be nice to give the copilot ability to the integrated terminal.

Specifically,

- shell agnostic copilot - suggestions are prompted while typing the command.
- auto explains last error message and potential actions to take
- give examples of the typed command
...

**Comment by Tyriar** [comment]
We're planning on doing this soon, an exploration was tracked in https://github.com/microsoft/vscode/issues/170485. Closing off as we're tracking it internally
