### ISSUE TITLE
Merge conflict resolution in requirements.txt has no "Finish" button

### ISSUE THREAD

**Issue by sethgilchrist** [microsoft/vscode#178758]
Type: <b>Bug</b>

Create a merge conflict in a requirements.txt file. When you go to merge them and resolve conflicts, the blue button in that is typically in the bottom right that completes the merge iis replaced by a "create environment" button.  It is not possible to resovle conflicts and complete the merge.

VS Code version: Code 1.77.0 (7f329fe6c66b0f86ae1574c2911b681ad5a45d63, 2023-03-29T10:02:16.981Z)
OS version: Windows_NT x64 10.0.22000
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 9 5950X 16-Core Processor             (32 x 3394)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|127.90GB (66.47GB free)|
|Process Argv|--crash-reporter-id b48be22d-ddb5-4328-af2e-4ae237431584|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (29)</summary>

Extension|Author (truncated)|Version
---|---|---
ruff|cha|2023.12.0
ini-for-vscode|Dav|0.0.4
githistory|don|0.6.20
vscode-pull-request-github|Git|0.62.0
gc-excelviewer|Gra|4.2.57
vsc-python-indent|Kev|1.18.0
git-graph|mhu|1.30.0
regexsnippets|Mon|1.0.2
vscode-docker|ms-|1.24.0
playwright|ms-|1.0.9
flake8|ms-|2023.4.0
isort|ms-|2022.8.0
python|ms-|2023.6.0
vscode-pylance|ms-|2023.3.40
jupyter|ms-|2023.3.1000892223
jupyter-keymap|ms-|1.1.0
jupyter-renderers|ms-|1.0.15
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-slideshow|ms-|0.1.5
remote-containers|ms-|0.288.0
remote-wsl|ms-|0.77.0
autodocstring|njp|0.6.1
sqlite-viewer|qwt|0.2.3
vscode-yaml|red|1.12.2
rust-analyzer|rus|0.3.1451
markdowntable|Tak|0.10.4
even-better-toml|tam|0.19.0
gitblame|wad|10.1.0
local-history|xyz|1.8.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vscaac:30438847
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
vsccc:30610678
nodejswelcome1cf:30587006
2e4cg342:30602488
pyind779:30671433
f6dab269:30613381
pythonsymbol12:30671437
showlangstatbar:30672706
vsctsb:30677850
pythonb192:30669360
defaultazurewalk:30687958
pythonms35:30701012

```

</details>

**Comment by sethgilchrist** [comment]
![image](https://user-images.githubusercontent.com/4625551/229019881-958e1a5c-658f-42f0-91fa-0f61db958fe0.png)

**Comment by hediet** [comment]
I think this is an extension issue. It shouldn't use that button.

**Comment by hediet** [comment]
Actually, this is caused by the Python extension, lets track in https://github.com/microsoft/vscode/issues/179306.
