### ISSUE TITLE
Decoration disappeared after switching editor

### ISSUE THREAD

**Issue by XuJiandong** [Microsoft/vscode#17872]
- VSCode Version: 1.8.1
- OS Version: Window 7

Steps to Reproduce:
1. use the following code to mark some word,e.g.:
```
MarkWord(vscode.window.activeTextEditor, "hello", "hover message", 1, 10)

export function MarkWord(editor: vscode.TextEditor, word: string, hover: string, startLine: number, endLine: number) {
    let decorationType = vscode.window.createTextEditorDecorationType({
        outline: '1px dotted red'
	});
    let regEx = /\w+/g;
    let decoratedWords : vscode.DecorationOptions[] = [];
    for (let i = startLine; i <= endLine; i++) {
        let lineText = editor.document.lineAt(i).text;
        let match;
        while (match = regEx.exec(lineText)) {
            if (match[0] == word) {
                let startPos = new vscode.Position(i, match.index);
                let endPos = new vscode.Position(i, match.index + match[0].length);
                let rg = new vscode.Range(startPos, endPos);
                decoratedWords.push({ range: rg, hoverMessage: hover});
            }
        }
    }
    editor.setDecorations(decorationType, decoratedWords);
}
```
2. Switch to another editor tab, then switch back, all decorations disappeared

**Comment by rebornix** [comment]
We dispose model bind to an editor when it's no longer active, whether the editor is closed or inactive. You'd better update the decorations in event handler for active editor change.

**Comment by rebornix** [comment]
When an editor becomes invisible, whether it's inactive or closed, we'll always remove all decorations bind to the model of the editor. You may want to register a handler to active editor change event and add decorations when the editor is active.

**Comment by XuJiandong** [comment]
thank you rebornix. Hope it can be added into the document.

**Comment by rebornix** [comment]
@XuJiandong sorry for the misleading, we'll write documentation to explain things under the hood.
