### ISSUE TITLE
Pleas help to restore my notebook, accidentally overwritten

### ISSUE THREAD

**Issue by rrmehdi** [microsoft/vscode#178732]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 
- OS Version: 

Steps to Reproduce:

1. Approximately at 4.45 PM CST I have accidentally overwritten my notebook by coping the other notebook over the lost one. Unfortunately, you,  guys, do not use "cp -I", so, I was not careful enough that I have the earlier make notebook with the same name, I have this code reference   code-391ff5ac-6576-460f-ba4d-7e03433c68b6.  I have had this notebook PC_Pipelines_Gensim.ipynb  I am wondering and very hopeful you could restore this notebook with this morning version of it. Otherwise, I would need to restore it manually,, and that would take some time. The version is what that code above is referenced to, has a new file, that was copied over to the morning version of it. Please HELP!!! Please contact me with the path to the lost notebook in my account. Thank you!

**Comment by rebornix** [comment]
If you are using VS Code to edit the notebook file, you can open Explorer -> Timeline View and find previous copies

<img width="1648" alt="image" src="https://user-images.githubusercontent.com/876920/228992223-f0687781-4724-4cea-b3e6-cdfb9357a25e.png">
