### ISSUE TITLE
Title Pane is blue after update

### ISSUE THREAD

**Issue by skks1212** [microsoft/vscode#178762]
Does this issue occur when all extensions are disabled?: Yes 

- VS Code Version: 1.77.0
- OS Version: Windows_NT x64 10.0.22621 (Win 11)

After updating vscode, I am seeing a blue title pane. I am using Dark+ v2 theme which does not have this and was working perfectly fine until yesterday. Restarting and resetting the theme does not work either. It is the same in all themes

Steps to Reproduce:

1. No steps to reproduce, the title pane is bugged after update

Screenshot:
![image](https://user-images.githubusercontent.com/23238460/229023740-05341f9f-9efa-4ac9-a19d-3a0bf6e2dea5.png)

![image](https://user-images.githubusercontent.com/23238460/229024352-4c1c3d4e-0e23-4ce2-b2a6-e5292b007acf.png)

**Update**
Looks like it is only happening for one specific project folder. Opening another folder solves the issue. Still weird.

**Comment by daviddossett** [comment]
@skks1212 can you verify you don't have anything manually overriding this color in your settings.json file? I'm not able to repro this on my end.

cc @sbatten for titlebar knowledge

**Comment by skks1212** [comment]
@daviddossett looks like it was a problem on my side. There was a .vscode folder with settings.json that overrode my settings. 🙃

**Comment by daviddossett** [comment]
Ah, glad it was a simple fix 👍
