### ISSUE TITLE
incorrect formatting on javascript

### ISSUE THREAD

**Issue by calidion** [Microsoft/vscode#17887]
- VSCode Version: Code 1.8.1 (ee428b0eead68bf0fb99ab5fdc4439be227b6281, 2016-12-19T14:42:49.304Z)
- OS Version: Darwin x64 16.3.0
- Extensions:

|Extension|Author|Version|
|---|---|---|
|tslint|eg2|0.7.1|
|code-beautifier|michelemelluso|1.6.2|
|vscode-icons|robertohuertasm|4.1.0|

---

Steps to Reproduce:

1.  for code:
```
return MessageFriend.update({
            id: found.id
          }, 
 {
              processed: true
})
```

expected:
```
return MessageFriend.update({
  id: found.id
}, {
  processed: true
});
```
got:
```
return MessageFriend.update({
  id: found.id
}, 
  {
    processed: true
  });
```

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript#13205
