### ISSUE TITLE
Add npm install context menu to package.json file

### ISSUE THREAD

**Issue by SetTrend** [Microsoft/vscode#1788]
When cloning a project from GitHub or after editing the `package.json` file in VS Code, no _npm_ package is getting downloaded. So currently it's required to leave VS Code and execute `npm install` in a command prompt.

I suggest to add a context menu item to the Explorer when a `package.json` file is selected to simplify this task. The context menu item is suggested to run `npm install` from the directory of the `package.json` file:

![package](https://cloud.githubusercontent.com/assets/9283914/12114307/0dd6ca62-b3a9-11e5-8150-5ef323fad950.png)

**Comment by mjbvz** [comment]
An extension can provide this functionality. Please check the marketplace to see if any already offer it. If you are writing an extension, please see our [extension authoring docs](https://code.visualstudio.com/docs/extensions/overview)

Closing as extension-candidate
