### ISSUE TITLE
Terminal windows not closing on VS Code close

### ISSUE THREAD

**Issue by computiotion** [microsoft/vscode#178888]
Type: <b>Bug</b>

1. Open a terminal window in VS Code
2. Close (Command + Q) VS Code
3. Open Activity Monitor
**Expected Result:**
Terminal closed, and is no longer running
**Actual Result:**
Terminal is still running, even on VS Code re-open.

VS Code version: Code 1.77.0 (Universal) (7f329fe6c66b0f86ae1574c2911b681ad5a45d63, 2023-03-29T09:57:11.797Z)
OS version: Darwin x64 22.3.0
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-1000NG4 CPU @ 1.10GHz (4 x 1100)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|19, 15, 15|
|Memory (System)|8.00GB (0.03GB free)|
|Process Argv|--crash-reporter-id bee90713-ec67-4eed-a7db-faa2f8637142|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (42)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|3.0.2
tailwind-docs|aus|2.0.0
spaghettify|BCA|0.1.2
vscode-tailwindcss|bra|0.9.11
npm-intellisense|chr|1.4.4
codesandbox-projects|Cod|0.2.72
vscode-eslint|dba|2.4.0
prettier-vscode|esb|9.10.4
auto-rename-tag|for|0.1.10
rest-client|hum|0.25.1
jsdoc-generator|kim|0.0.4
mcjson|Lev|0.4.1
mongodb-vscode|mon|0.11.1
vscode-edge-devtools|ms-|2.1.1
isort|ms-|2022.8.0
python|ms-|2023.6.0
vscode-pylance|ms-|2023.3.40
jupyter|ms-|2023.3.1000892223
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-slideshow|ms-|0.1.5
remote-ssh|ms-|0.98.0
remote-ssh-edit|ms-|0.84.0
remote-wsl|ms-|0.77.0
vscode-remote-extensionpack|ms-|0.24.0
azure-repos|ms-|0.30.0
remote-explorer|ms-|0.2.0
remote-repositories|ms-|0.32.0
remote-server|ms-|1.0.0
vsliveshare|ms-|1.0.5834
material-icon-theme|PKi|4.25.0
prisma|Pri|4.12.0
LiveServer|rit|5.7.9
wikitext|Row|3.7.0
salesforce-vscode-slds|sal|1.4.8
salesforcedx-vscode|sal|57.7.0
salesforcedx-vscode-core|sal|57.7.0
salesforcedx-vscode-soql|sal|57.7.0
salesforcedx-vscode-visualforce|sal|57.7.0
svelte-vscode|sve|107.2.5
intellicode-api-usage-examples|Vis|0.2.7
volar|Vue|1.2.0
quokka-vscode|Wal|1.0.529

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyonecf:30548226
vscccc:30610679
nodejswelcome1cf:30587006
3biah626:30602489
pyind779:30671433
f6dab269:30613381
pythonsymbol12:30671437
vsctsb:30677850
pythonb192:30669360
functionswalk:30687959
pythonms35:30701012

```

</details>

**Comment by computiotion** [comment]
After further review, this seems to be an issue with vercel/next

**Comment by computiotion** [comment]
After further review, this seems to be an issue with vercel/next.js

**Comment by shanuflash** [comment]
@computiotion did u find whats wrong?

**Comment by computiotion** [comment]
Unfortunately, no. I assume Next.JS escapes that terminal and creates another one outside of VS code, but I wouldn't know.
