### ISSUE TITLE
editorError.border doesn't apply a border

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#178800]
When I set this:

```json
  "workbench.colorCustomizations": {
    "editorError.border": "#ff0000",
  }
```

<img width="194" alt="image" src="https://user-images.githubusercontent.com/2193314/229117862-261c752f-5580-4464-aa2e-f1796c67266a.png">

I see this:

<img width="71" alt="image" src="https://user-images.githubusercontent.com/2193314/229117650-a8397845-dde5-49e9-b9e6-da903f3d6626.png">

I was expecting:

![image](https://user-images.githubusercontent.com/2193314/229117727-6209c389-a63c-4f56-b7f2-f1192b6374de.png)

Version: 1.78.0-insider (user setup)
Commit: f31dffc7f9b93a1cdef21243ec30dea7d489a615
Date: 2023-03-31T01:47:17.818Z
Electron: 19.1.11
Chromium: 102.0.5005.196
Node.js: 16.14.2
V8: 10.2.154.26-electron.0
OS: Windows_NT x64 10.0.22621
Sandboxed: Yes

**Comment by aeschli** [comment]
Looks like we didn't think much when choosing his name.

**Comment by Tyriar** [comment]
Should we iust change the description and leave the key name as is then?

**Comment by unikitty37** [comment]
It looks like the implemented fix just changes the description and still leaves VSCode with no way of drawing a nice, noticeable box around the errant code.

This doesn't seem like a fix to me — just labelling it "it's not a bug, it's a feature". Ideally, the key name for this feature should be changed to `editorError.secondUnderline` (or similar) and `editorError.border` should _actually produce a border around the whole code_.

This seems to be what the OP wanted, and it's certainly what _I_ want — I'm trying to migrate from RubyMine, and RubyMine can do this, and it's _extremely helpful_, as the underlines are too easy to miss, especially when the Stylelint plugin seems to only want to highlight the first character of a line and not the whole line.

Please could we have a way of actually drawing a border around the whole of the code?

**Comment by Tyriar** [comment]
@unikitty37 I would have liked a border, but that would be a new feature (not sure if there's an issue discussing this). The change just corrects the description to what it actually does, without changing the key which would break themes that already use it.

**Comment by Tyriar** [comment]
If we actually added a border, I would guess we would just use the .border key there and add a new double underline one. Kind of a soft breaking change as opposed to a theme color just not getting used all together.
