### ISSUE TITLE
feedback popup is missing gear to select "Don't show again"

### ISSUE THREAD

**Issue by scottlawsonabc** [microsoft/vscode#178832]
In 1.77.0 (universal), I'm no longer able to click the gear and select "Don't show again" for the feedback popup.
<img width="437" alt="image" src="https://user-images.githubusercontent.com/60241526/229192503-83cb9fda-7a9c-45f8-b70e-c21d4ff9c068.png">

The answer in this issue https://github.com/Microsoft/vscode/issues/51353 was that you should be able to click the gear, but the gear does not appear for me at all.

**Comment by bpasero** [comment]
Thanks for tracking down that PR. I am not sure, moving to @digitarald to close as designed.

**Comment by digitarald** [comment]
Just closing it has the same effect as never show again, yes.
