### ISSUE TITLE
OSX: german keyboard shortcut not recognized

### ISSUE THREAD

**Issue by marvinhagemeister** [Microsoft/vscode#17884]
- VSCode Version: 1.9.0-insider 58ab5ecdd9e54643e3ae9ae188021844329c0854
- OS Version: MacOS Sierra

Since recently (sometimes after christmas, haven't done much coding this week), the shortcut to split the editor views doesn't work anymore. By default it is assigned to `cmd+\` and the tooltip correctly maps it to `⌘+#`. But it doesn't split the editor anymore. The devtools don't print any error.

Steps to Reproduce:

1. open vscode
2. press `⌘+#` on a german keyboard layout
3. nothing happens

**Comment by life1347** [comment]
In System Preference -> keyboard -> Keyboard -> click Restore Default.
It works for me, though my problem is "shift+cmd+left". It seems that MacOS bug.

**Comment by marvinhagemeister** [comment]
This is fixed with the latest insider build of today c6a320c4f9c53b809a9615324a5b563eeb217984. Not sure which particular commit solved it, though.
