### ISSUE TITLE
Terminal crashing before open

### ISSUE THREAD

**Issue by dalisoft** [microsoft/vscode#178810]
Type: <b>Bug</b>

Example of error

Inappropriate ioctl for device

<img width="453" alt="Screenshot 2023-03-31 at 18 48 03" src="https://user-images.githubusercontent.com/3511344/229138647-d685743c-c428-4aa0-970d-ccea1bd140be.png">

https://user-images.githubusercontent.com/3511344/229139432-3351afa5-793b-481f-83af-85b67539659d.mp4

VS Code version: Code - Insiders 1.78.0-insider (f31dffc7f9b93a1cdef21243ec30dea7d489a615, 2023-03-31T01:49:42.343Z)
OS version: Darwin arm64 22.4.0
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Max (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|5, 6, 6|
|Memory (System)|64.00GB (19.24GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (73)</summary>

Extension|Author (truncated)|Version
---|---|---
svgo|100|3.0.0
vscode-nginx-conf|ahm|0.1.3
vscode-fish|bma|1.0.33
vscode-intelephense-client|bme|1.9.5
npm-intellisense|chr|1.4.4
vscode-css-modules|cli|0.4.2
gitignore|cod|0.9.0
vscode-markdownlint|Dav|0.49.0
vscode-eslint|dba|2.4.0
gitlens|eam|13.4.0
EditorConfig|Edi|0.16.4
LogFileHighlighter|emi|2.16.0
prettier-vscode|esb|9.10.4
code-runner|for|0.12.0
platformio|for|0.3.0
shell-format|fox|7.2.5
vscode-github-actions|git|0.25.3
vscode-pull-request-github|Git|0.62.0
go|gol|0.38.0
todo-tree|Gru|0.0.224
terraform|has|2.25.4
vscode-htmlhint|HTM|1.0.4
output-colorizer|IBM|0.1.2
r-pack|Iku|0.0.2
reason-vscode|jar|1.7.13
svg|joc|1.5.2
vscode-phpfmt|kok|1.0.31
bash-ide-vscode|mad|1.36.0
rainbow-csv|mec|3.6.0
vscode-language-babel|mgm|0.0.38
git-graph|mhu|1.30.0
dotenv|mik|1.0.1
vscode-apache|mrm|1.2.0
vscode-scss|mrm|0.10.0
vscode-docker|ms-|1.24.0
gather|ms-|2022.3.2
isort|ms-|2022.8.0
python|ms-|2023.6.0
vscode-pylance|ms-|2023.3.40
jupyter|ms-|2023.3.1000892223
jupyter-keymap|ms-|1.1.0
jupyter-renderers|ms-|1.0.15
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-slideshow|ms-|0.1.5
remote-containers|ms-|0.288.0
remote-ssh|ms-|0.98.0
remote-ssh-edit|ms-|0.84.0
cpptools|ms-|1.14.5
remote-explorer|ms-|0.2.0
sftp|Nat|1.16.1
color-highlight|nau|2.5.0
proto|pet|0.0.2
material-icon-theme|PKi|4.25.0
polacode|pnp|0.3.4
gitlink|qez|1.2.4
inline-sql-syntax|quf|2.16.0
quick-lint-js|qui|2.12.0
quicktype|qui|12.0.46
java|red|1.16.0
vscode-commons|red|0.0.6
vscode-yaml|red|1.12.2
r|REd|2.7.2
shellman|Rem|5.6.1
postcss|ric|2.0.0
rome|rom|0.22.0
rust-analyzer|rus|0.3.1451
gitconfig|sid|2.0.1
vscode-styled-components|sty|1.7.5
vscode-stylelint|sty|1.2.4
svelte-vscode|sve|107.2.5
hlsltools|Tim|1.1.303
vscodeintellicode|Vis|1.2.30
viml|Xad|2.1.2

</details>

**Comment by psobolewskiPhD** [comment]
I'm also getting this on my macOS 13.2.1, arm64, fish after auto-update to insiders 1.78.0

**Comment by meganrogge** [comment]
can you reproduce this with all extensions disabled?

**Comment by psobolewskiPhD** [comment]
> can you reproduce this with all extensions disabled?

Yup, all extensions disabled results in the same issue.

**Comment by meganrogge** [comment]
does setting `terminal.integrated.shellIntegration.enabled:false` fix it?

**Comment by psobolewskiPhD** [comment]
I added 
`"terminal.integrated.shellIntegration.enabled": false,`
to the end of my `settings.json`. Relaunched, no difference.

**Comment by dalisoft** [comment]
@meganrogge I am googled a little and found this [comment](https://github.com/fish-shell/fish-shell/issues/9605#issuecomment-1438478842), maybe helps

**Comment by cideM** [comment]
I have the same issue. Also using Fish, version `3.6.0` and Visual Studio Code Insiders version
```
Version: 1.78.0-insider (Universal)
Commit: f31dffc7f9b93a1cdef21243ec30dea7d489a615
Date: 2023-03-31T01:49:03.052Z
Electron: 19.1.11
Chromium: 102.0.5005.196
Node.js: 16.14.2
V8: 10.2.154.26-electron.0
OS: Darwin arm64 22.3.0
Sandboxed: Yes
```

**Comment by Armorine86** [comment]
Having the same issue. Fish ain't working anymore since last update. Bash and Zsh seems to work normally...

**Comment by danmackinlay** [comment]
@dalisoft @meganrogge in particular this bit?

>The basic issue is that fish checks if stdin is a tty via `isatty`; after confirming it is fish attempts to activate job control via the `tc{get,set}pgrp` family of functions and here receives `ENOTTY`: stdin is not a tty.

**Comment by MariaSolOs** [comment]
`nushell` has the same issue.

**Comment by dalisoft** [comment]
Currently workaround is using `tmux + fish`. On Terminal tab, click to **+** and choose `tmux` and you can use as workaround

**Comment by ehagerty** [comment]
NB, csh also warns of the problem but will start.

**Comment by dalisoft** [comment]
On latest Insider version it works on macOS. Try upgrade both **fish** and **VSCode Insider** to latest. Thank you to all team who worked on this fix

Info:
```
Version: 1.78.0-insider
Commit: cbf35328c8357175b9cd747823f39ade987c3d3c
Date: 2023-04-04T19:09:48.072Z (8 hrs ago)
Electron: 22.4.3
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Darwin arm64 22.4.0
Sandboxed: No
```

**Comment by ehagerty** [comment]
For anyone interested, my linked and expanded writeup for this issue is here https://github.com/microsoft/vscode/issues/178999
