### ISSUE TITLE
Unable to access Extensions via Market/install framework via terminal

### ISSUE THREAD

**Issue by itsdhairya** [microsoft/vscode#178841]
Type: <b>Bug</b>

Good Afternoon,

My name is Dhairya Brahmbhatt. I have been using VSCode for a while now. I needed assistance with this application due to bugs/errors such as being unable to download extensions from the marketplace (directly from the app) or being able to install frameworks from the terminal. 

moreover, I am unable to install frameworks such as tailwind/bootstrap via the terminal (code install yarn). 
Also, if I install extensions from VSIX I cannot log in (example is the Github authentication extension) 

![image](https://user-images.githubusercontent.com/99156657/229209182-a94b533a-3842-481d-a756-624b545f4e15.png)

![WhatsApp Image 2023-03-30 at 20 28 44](https://user-images.githubusercontent.com/99156657/229209666-a42a47c2-1134-4f65-a8c1-df5108f8ebcf.jpg)

Please assist me as soon as possible due to this I am unable to finish my projects. 

VS Code version: Code 1.77.0 (7f329fe6c66b0f86ae1574c2911b681ad5a45d63, 2023-03-29T10:02:16.434Z)
OS version: Windows_NT ia32 10.0.22621

Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 5600H with Radeon Graphics          (12 x 3294)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.35GB (22.36GB free)|
|Process Argv|--crash-reporter-id 9f0fac68-60a3-44e7-b7d9-713d62d0a95d|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
tabnine-vscode|Tab|3.6.43

</details>

**Comment by sandy081** [comment]
There seems to be an issue with your network connection, so please diagnose it and hopefully it gets fixed. Thanks.

**Comment by itsdhairya** [comment]
There seems to be an issue with your network connection, so please diagnose it and hopefully it gets fixed. Thanks.



My Wifi, WLAN everything works fine. I was not expecting such a resolution which by the way did not even solve it.
