### ISSUE TITLE
link to command:vscode.open URI does not honor second argument in webview

### ISSUE THREAD

**Issue by bolinfest** [microsoft/vscode#178868]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 

Version: 1.77.0
Commit: 7f329fe6c66b0f86ae1574c2911b681ad5a45d63
Date: 2023-03-29T09:57:11.797Z (2 days ago)
Electron: 19.1.11
Chromium: 102.0.5005.196
Node.js: 16.14.2
V8: 10.2.154.26-electron.0
OS: Darwin x64 22.3.0
Sandboxed: Yes

- OS Version: macOS 13.2.1 (22D68)

Steps to Reproduce:

1. Clone the code for the webview sample: https://github.com/microsoft/vscode-extension-samples/blob/main/webview-sample/src/extension.ts
2. Under this option https://github.com/microsoft/vscode-extension-samples/blob/98346fc4fa81067e253df9b32922cc02e8b24274/webview-sample/src/extension.ts#L40 add `enableCommandUris: true`
3. Add some code like this using a file on your local disk:
```ts
		const thisEditorParams = [vscode.Uri.parse('file:///Users/mbolin/.gitconfig')];
		const besideEditorParams = [
			vscode.Uri.parse('file:///Users/mbolin/.gitconfig'),
			vscode.ViewColumn.Beside,
		];
```
4. Add the following to the multiline string of HTML content returned by `_getHtmlForWebview()` to introduce some links into the webview:
```ts
			<p>
		  <a href="command:vscode.open?${encodeURIComponent(
				JSON.stringify(thisEditorParams)
			)}">open in this editor</a>
			</p>
			<p>
		  <a href="command:vscode.open?${encodeURIComponent(
				JSON.stringify(besideEditorParams)
			)}">open beside</a>
			</p>
```
5. Run the extension and open the webview. Split your window so there is a pane to the right.

**Expected:** clicking `open in this editor` should open the file in the same group as the webview while clicking `open beside` should open the file in the group to the right.

**Observed:** clicking `open beside` also opens in the same editor group. I have tried all sorts of ways of declaring the second argument, but nothing seems to have an effect.

I'm really not sure what is going on. Based on this code, I thought this should be straightforward, but perhaps there is something special about webviews somewhere that I am missing:

https://github.com/microsoft/vscode/blob/350ca13b5aba678105c84bef71a693ba4162b8f1/src/vs/workbench/api/common/extHostApiCommands.ts#L394-L405

I saw this issue, but I am not sure if it is related:

https://github.com/microsoft/vscode/issues/154993

I discovered that I can create my own custom command that I hyperlink to in the webview and I can take the args and call `commands.executeCommand('vscode.open', /* args */)` myself, but I was hoping to avoid that and get `vscode.open` to "just work."

**Comment by bolinfest** [comment]
I was curious to see what the full-editor search pane uses and I see:

    <span class="mtk11 detected-link">

so I guess it isn't using `command:`?

**Comment by ArturoDent** [comment]
Try making your open options into an object.  So instead of 

```js
		const besideEditorParams = [
			vscode.Uri.parse('file:///Users/mbolin/.gitconfig'),
			vscode.ViewColumn.Beside,
		];

```

try this:

```js
		const besideEditorParams = [
			vscode.Uri.parse('file:///Users/mbolin/.gitconfig'),
			{viewColumn: vscode.ViewColumn.Beside}
		];
```

I haven't tested that but I know that `vscode.open` is expecting an object as the second argument with keys.

**Comment by mjbvz** [comment]
Thanks for the detailed repo steps! This is same problem as https://github.com/microsoft/vscode/issues/154993

For somewhat convoluted reasons, the `vscode.open` command you are running here isn't the API version of the command. #154993 has more info. This causes the second argument to be silently ignored

To workaround this, the best fix is to introduce a your own proxy command. This command can simply call `vscode.open` with all of the arguments it is passed. This ensures that the correct version of `vscode.open` is always used

**Comment by bolinfest** [comment]
The workaround is fine, though is there a good way to capture this in the end-user docs? Are there other commands with similar limitations? I spent a lot of time investigating this.
