### ISSUE TITLE
Intellisense has stopped working/auto detect language

### ISSUE THREAD

**Issue by BrandonRivas** [microsoft/vscode#178863]
Type: <b>Bug</b>

I have multiple lines of JS but for some reason when styling in the same sheet at the bottom, the auto sugguestion isn't showing up. 

VS Code version: Code 1.77.0 (Universal) (7f329fe6c66b0f86ae1574c2911b681ad5a45d63, 2023-03-29T09:57:11.797Z)
OS version: Darwin arm64 22.3.0
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|1, 2, 3|
|Memory (System)|8.00GB (1.07GB free)|
|Process Argv|--crash-reporter-id b2656c39-0319-4697-b084-df11cdecc157|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
prettier-vscode|esb|9.10.4
marp-vscode|mar|2.5.0
vsliveshare|ms-|1.0.5834
indent-rainbow|ode|8.3.1
material-icon-theme|PKi|4.25.0
LiveServer|rit|5.7.9
code-spell-checker|str|2.20.3
vscode-styled-components|sty|1.7.5
pdf|tom|1.2.2

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vstes627:30244334
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vscaac:30438847
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
nodejswelcome1:30587005
2e4cg342:30602488
pyind779:30671433
89544117:30613380
pythonsymbol12:30671437
a9j8j154:30646983
vsctsb:30677850
defaultazurewalk:30687958
pythonms35:30701012

```

</details>

**Comment by mjbvz** [comment]
What is the language mode of the file?

**Comment by BrandonRivas** [comment]
It's set to autodetect which is currently on Javascript 
![Screenshot 2023-04-03 at 12 36 25 PM](https://user-images.githubusercontent.com/89816116/229572696-f93506d8-85bb-4ff1-b8ca-04ebef321ab0.png)

**Comment by mjbvz** [comment]
And what isn't working? Please share steps to reproduce or a screen recording of the problem

**Comment by mjbvz** [comment]
Thanks. This is caused by the styled-components extension, not VS Code. Please follow up with them
