### ISSUE TITLE
Improve discoverability of well-known source actions by including the language name in the command palette/filter

### ISSUE THREAD

**Issue by DanTup** [microsoft/vscode#178875]
In Dart, there are a number of supported "Source" CodeActions:

- Organize Imports
- Fix All
- Sort Members

In the past, VS Code didn't have first-class support for these, so they were added to the command palette by the Dart extension, having:

- Dart: Organize Imports
- Dart: Sort Members

When VS Code added first-class support, I removed these additional commands because I felt it was confusing to have an "Organize Imports" command and a "Dart: Organize Imports" command because it's not clear to a user whether these are just the same, or whether the Dart version might be better because it's Dart-specific.

However, this now means that there's an inconsistency with prefixes of Dart source-level actions in the palette:

- Dart: Sort Members
- Fix All
- Organize Imports

If a user types "dart" into the command palette to see what functionality is available, the would never see "Fix All" and Organize Imports" because they don't match the "Dart" filter, even though they are being shown because an extension is contributing them for the Dart language.

I had a request at https://github.com/Dart-Code/Dart-Code/issues/4446 to add Dart-prefixed versions of these commands, but I'm reluctant because of the potential confusion mentioned above (for example it's not clear whether "Dart: Fix All" contributed by the Dart extension would apply only fixes from the Dart LSP server, or any extension contributing Dart fixes like the unprefixed "Fix All" command).

I think this could be better handled by VS Code. For example:

- VS Code prefixing the commands that are for Source actions with the name of the Language of the document (so it would show up as "Dart: Fix All" in a Dart file, and "TypeScript: Fix All" in a TypeScript file)
- VS Code including the language name in the "filter text" of such a command, so typing "dart fix" would still show the unprefixed "Fix All" command

From user feedback, I think discoverability of features in VS Code is definitely a concern. I'm often asked for things that already exist, because most things are in the command palette where it's difficult for a user to "browse" them. I think surfacing language features when the user is typing the name of the active language could be helpful in this area.

**Comment by mjbvz** [comment]
I think there are  going to be better ways to improve discoverability. The well known source action types like `organize imports` or `fix all` work across languages. This is similar to other editor operations. We don't have a `TypeScript: Go to definition` for example, just a single `Go to definition` command which works in many different languages

For language specific source actions, having the language prefix is fine IMO because that command comes from that language extension and will only work in that language

Open to other ideas but I don't think this is something we'd want to do in core VS Code (and I also advise against introducing aliases for the existing built-in commands in the Dart extension )

**Comment by DanTup** [comment]
> I think there are going to be better ways to improve discoverability. 

Do you have any ideas or are there any other issues I can direct people to?


> For language specific source actions, having the language prefix is fine IMO

This issue was less about having unprefixed versions of language-specific commands, and more about making the not-language-specific commands easier to find if you don't know that they're not language-specific.

Before VS Code had Organize Imports, Dart had a _language-specific_ command for this. This may happen in future - languages may implement language-specific commands that later become adopted by VS Code. Your suggestion is that languages shouldn't leave these "duplicate" commands, but if users are _used_ to typing the language name to see these types of commands, they will fail to find the VS Code ones.

Commands like Organize Imports are still provided by languages. They are not universally available (for example in a Plain Text file, there is no "Organize Imports" command). It seems a little awkward to expect users to understand that some language-provided features are not prefixed with a language.

**Comment by DanTup** [comment]
FWIW, I'm also thinking about adding another version of "Fix All" that performs only a subset of these fixes (to be more suitable for on-save, because it won't remove imports for code you've just temporarily commented out - for example). If we add a command for that (not just the code action), then having "Dart: Fix Simple Issues" show up when searching for "Dart Fix" and not the normal "Fix All" would definitely be odd, which might add to the argument of adding an alias for "Dart: Fix All".
