### ISSUE TITLE
Horizontal Menus?

### ISSUE THREAD

**Issue by tonyb983** [microsoft/vscode#178813]
Type: <b>Bug</b>

My VSCode Insiders updated last night and this morning all of my menus (right clicking in the file explorer AND opening the menus from the top toolbar) display horizontally.

VS Code version: Code - Insiders 1.78.0-insider (b1ad3f934ca87b76dac5cf3533fb172d1c30e6ba, 2023-03-30T18:30:01.170Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 5500U with Radeon Graphics          (12 x 2096)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|9.86GB (3.11GB free)|
|Process Argv|.\\.vscode\\one-more.code-workspace --crash-reporter-id b42d8257-dea7-47a3-a3ac-7f5f38a65ce4|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (20)</summary>

Extension|Author (truncated)|Version
---|---|---
emojisense|bie|0.9.1
markdown-checkbox|bie|0.4.0
markdown-emoji|bie|0.3.0
markdown-footnotes|bie|0.1.1
markdown-preview-github-styles|bie|1.0.1
gitlens|eam|13.4.0
EditorConfig|Edi|0.16.4
copilot|Git|1.78.9758
vscode-pull-request-github|Git|0.63.2023033019
vscode-test-explorer|hbe|2.21.1
live-server|ms-|0.4.7
test-adapter-converter|ms-|0.1.7
material-icon-theme|PKi|4.25.0
material-product-icons|PKi|1.5.0
vscode-coverage-gutters|rya|2.10.4
code-spell-checker|str|2.20.3
errorlens|use|3.8.0
gistfs|vsl|0.4.1
vscode-todo-highlight|way|1.0.5
licenser|ymo|1.9.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythontb:30258533
vsc_aa:30263845
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscod805cf:30301675
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30404738
cppdebug:30492333
vsclangdf:30492506
c4g48928:30535728
dsvsc012:30540252
pynewext54:30618038
pylantcb52:30590116
nodejswelcome1:30587009
pyind779:30611226
pythonsymbol12:30651887
showlangstatbar:30659908
pythonb192cf:30661257
azdwalk:30687957
pythonms35:30671666
0bg3d529:30680467
57b77579:30687741
pythonclientmv:30700173

```

</details>

**Comment by tonyb983** [comment]
![vscode horizontal right click context menu](https://user-images.githubusercontent.com/42479219/229144230-b1d3a4eb-a42f-48de-b7aa-d30715ed3b30.png)

![horizontal toolbar menu](https://user-images.githubusercontent.com/42479219/229144376-9b58e899-48d1-4b74-9eb1-120e83715059.png)

**Comment by ArturoDent** [comment]
I just got an update to Insiders - there is a command in the Command Palette, restart to update once you have the little `1` badge on your Gear icon.  And it fixed the menu problem for me.

**Comment by amritpal2489** [comment]
> ArturoDent, that resolved mine.
> 
> Command Palette search for update allowed me to check for updates again and then another Command Palette search on "install" ran the installer.
> 
> And, the horizontal menus are gone. Back to the way it was.
> 
> Thank you ArturoDent!!!

Can you please inform step by step how you did it?
