### ISSUE TITLE
RangeFormattingAdapter passes internal IRange objects to extensions with proposed formatMultipleRanges

### ISSUE THREAD

**Issue by c-claeys** [microsoft/vscode#178827]
Does this issue occur when all extensions are disabled?: No

- VS Code Version: 
- OS Version: 

Steps to Reproduce:

1. Use the new `formatMultipleRanges` proposed API in an extension to format multiple ranges at once, such that the provider `canFormatMultipleRanges`.
2. Trigger range formatting e.g. via the `FormatModifiedLines` command.

The `IRange` passed in as `range` is [converted](https://github.com/microsoft/vscode/blob/f6d3226adea51882c0edca902c7174a1e4280376/src/vs/workbench/api/common/extHostLanguageFeatures.ts#L574) to the type known to extensions on the public API as `ran` before being sent to `provideDocumentRangeFormattingEdits`. Meanwhile, `options` is cast as `<any>` and passed in as well, with an array full of internal `IRange`s.

Adding a line like `if (options.ranges) options.ranges = options.ranges.map(typeConvert.Range.to) as any;`will fix this issue, but I'm not sure if a more full-featured `typeConvert` for `options` would be preferred.

**Comment by jrieken** [comment]
> Adding a line like if (options.ranges) options.ranges = options.ranges.map(typeConvert.Range.to) as any;will fix this issue, but I'm not sure if a more full-featured typeConvert for options would be preferred.

Maybe a full-featured typeConvert for the sake of re-usability (api commands) but no more complex the outlines in the first part of the sentense

**Comment by jrieken** [comment]
This will be fixed by the API refinement, see https://github.com/microsoft/vscode/pull/179166
