### ISSUE TITLE
Julia terminal crashes with exit code 3, new_time >= loop->time

### ISSUE THREAD

**Issue by zznidar** [microsoft/vscode#178881]
Type: <b>Bug</b>

When executing Julia code that takes a bit longer to complete (more than a few minutes), the terminal crashes.

First, the following is shown in the terminal:
```
Assertion failed: new_time >= loop->time, file src/win/core.c, line 110

signal (22): SIGABRT
```

A fraction of a second later, the terminal disappears, and a notification message is shown saying
`The terminal process "julia.exe '-i', '--banner=no', '--project=C:\Users\user\.julia\environments\v1.8', 'c:\Users\user\.vscode\extensions\julialang.language-julia-1.38.2\scripts\terminalserver\terminalserver.jl', '\\.\pipe\vsc-jl-repl-bd8a44ff-5fd1-4e2a-a9a8-2b040da8bf96', '\\.\pipe\vsc-jl-cr-6aac475e-2f91-4d6f-a01e-19ccbef6d345', 'USE_REVISE=true', 'USE_PLOTPANE=true', 'USE_PROGRESS=true', 'ENABLE_SHELL_INTEGRATION=true', 'DEBUG_MODE=false'" terminated with exit code: 3.`

If I run the file through cmd -> julia -> include("myfile.jl"), it works without problems.

VS Code version: Code 1.77.0 (7f329fe6c66b0f86ae1574c2911b681ad5a45d63, 2023-03-29T10:02:16.981Z)
OS version: Windows_NT x64 10.0.19045
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 4800H with Radeon Graphics          (16 x 2895)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.37GB (3.05GB free)|
|Process Argv|--crash-reporter-id e7c475cd-b99d-4fb4-aa11-c2f8d5aa7e58|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (17)</summary>

Extension|Author (truncated)|Version
---|---|---
htmlplay|bia|0.0.10
xml|Dot|2.5.1
copilot|Git|1.78.9758
language-julia|jul|1.38.2
vscode-map-preview|jum|0.5.9
formate|Mik|1.2.1
python|ms-|2023.6.0
vscode-pylance|ms-|2023.3.40
jupyter-keymap|ms-|1.1.0
jupyter-renderers|ms-|1.0.15
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-slideshow|ms-|0.1.5
live-server|ms-|0.4.7
geo-data-viewer|Ran|2.5.0
LiveServer|rit|5.7.9
vscode-autohotkey|sle|0.2.2
in-your-face-incredible|TTO|1.1.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscorecescf:30445987
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
nodejswelcome1cf:30587006
3biah626:30602489
pyind779:30671433
89544117:30613380
pythonsymbol12:30671437
2i9eh265:30646982
vsctsb:30677850
vscodedisable:30660115
functionswalk:30687959
pythonms35:30701012

```

</details>

Screenshot of the terminal just before it disappears:
![image](https://user-images.githubusercontent.com/20877556/229289342-35a8ec4c-3911-4729-8ae5-2341488222ec.png)

**Comment by meganrogge** [comment]
does setting `terminal.integrated.shellIntegration.enabled:false` fix it?

**Comment by zznidar** [comment]
Disabling `terminal.integrated.shellIntegration.enabled` appears to indeed fix it after some quick testing – thanks for the suggestion!

**Comment by zznidar** [comment]
The crash is back. I couldn't catch the screenshot of the terminal, but it was still signal (22): SIGABRT.

The popup error now: `The terminal process "julia.exe '-i', '--banner=no', '--project=C:\Users\user\.julia\environments\v1.8', 'c:\Users\user\.vscode\extensions\julialang.language-julia-1.38.2\scripts\terminalserver\terminalserver.jl', '\\.\pipe\vsc-jl-repl-aa5ffdba-cfee-4b3f-a0ea-0d457889c43c', '\\.\pipe\vsc-jl-cr-e435307f-4196-4224-a3c4-2d6356ee6b3a', 'USE_REVISE=true', 'USE_PLOTPANE=true', 'USE_PROGRESS=true', 'ENABLE_SHELL_INTEGRATION=false', 'DEBUG_MODE=false'" terminated with exit code: 3.`

**Comment by zznidar** [comment]
After further stress-testing, I have come to a point where Julia run from cmd also crashes. So apparently the issue lies somewhere else.
Closing as not related to VS Code.
