### ISSUE TITLE
Command history missing for Bash Integrated Terminal on Windows

### ISSUE THREAD

**Issue by PleasedSkin** [Microsoft/vscode#17882]
- VSCode Version: Code 1.8.1 (ee428b0eead68bf0fb99ab5fdc4439be227b6281, 2016-12-19T14:49:23.350Z)
- OS Version: Windows_NT ia32 10.0.14393

---

Steps to Reproduce:

1. In the user settings, set "terminal.integrated.shell.windows": "C:\\Windows\\sysnative\\bash.exe"
2. Restart VS Code
3. Toggle integrated terminal
4. Type a command in the integrated terminal
5. Unlike cmd (or Powershell), command history is not available (whereas it is outside of VS Code)

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/10163
