### ISSUE TITLE
Feature request: highlight trailing whitespace

### ISSUE THREAD

**Issue by wavebeem** [Microsoft/vscode#17883]
I'm currently using Trailing Spaces (`shardulm94.trailing-spaces`) for highlighting trailing spaces in my code, but this seems common enough to be a built-in feature.

Ideally the trailing whitespace would highlight in red so it's easy to see, like the extension, but another solution could be adding another value to `editor.renderWhitespace`, like `trailing` or something.

**Comment by BillDenton** [comment]
It is also availabe as https://marketplace.visualstudio.com/items?itemName=ybaumes.highlight-trailing-white-spaces. This extension has fewer options, but may be adequate for most use cases.
