### ISSUE TITLE
vscode extension api, custom ctrl+click link functionality.

### ISSUE THREAD

**Issue by Natejoestev** [microsoft/vscode#178817]
there is this game i mod for, and they have custom link types (`${NAME}/dir/file.txt`).

I'm working on an extension for this and would like to know how to add this feature.
basically when i `ctrl+click` on this format of link it would open that file in vscode, if it was a folder it would open in wfe

**Comment by rebornix** [comment]
What you need is a link provider, and here is some sample code https://github.com/microsoft/vscode-extension-samples/blob/98346fc4fa81067e253df9b32922cc02e8b24274/contentprovider-sample/src/extension.ts#L16

**Comment by Natejoestev** [comment]
is there documentation?

**Comment by Natejoestev** [comment]
k, I've looked over the files many times. it kind of makes sense. but i want the thing like URLs where if you hover it, it says `follow link (ctrl+click)`

i want to be able to give a regex or smth to match the link, and run a function when you press `ctrl+click` or the text.
the function i pass will be called when someone `ctrl+click`s the right regex pattern and it will pass the text itself to the function.

example:
```ts
const reg = `\$(?:AA|BB|CC)\/(.+).txt`
function f(txt: String) {
  vscode.window.showInformationMessage(`you tried to open link '${txt}'`);
}
```

is there any docs or anything like this?

**Comment by Natejoestev** [comment]
@rebornix could you expound?
