### ISSUE TITLE
vscode.dev share urls with whitespace

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode#178948]
For gh.com links we support perma link and head urls. For vscode.dev we only support perma links but I observe myself to need head links more than permalinks. We should add those. 

Also, for file and folders with whitespace, the whitespace should be encoded, just like we do for the gh.com links we generate.

**Comment by joyceerhl** [comment]
IMO vscode.dev links should be head links rather than permalinks. We could support both but I want to avoid clutter if possible.

Also, I do not see that we encode the whitespace for either github.com or vscode.dev links that we generate--will look into fixing for all our link code.

**Comment by joyceerhl** [comment]
Verification:
1. Have pre-release of GitHub Pull Requests extension on desktop
2. Open a desktop git clone of a GitHub repository on desktop
3. Open a file 
4. Copy a vscode.dev link 
5. Verify that the link is a HEAD link (i.e. does not point to a specific commit sha)
6. Open a GitHub repository on web (e.g. https://insiders.vscode.dev/github/microsoft/vscode)
7. Repeat steps 2-4
