### ISSUE TITLE
[FR][Terminal] clear method

### ISSUE THREAD

**Issue by farfromrefug** [Microsoft/vscode#17895]
Would be nice to have a ```clear``` method.

Related discussion: https://github.com/Microsoft/vscode/issues/17678

**Comment by Tyriar** [comment]
This was added a while ago: `workbench.action.terminal.clear`

**Comment by farfromrefug** [comment]
thanks @Tyriar will have to take a look and try to use it.

**Comment by NumberX** [comment]
I have two terminals when  i execute this commands ,just one terminal are clear it .
i would like to apply to all terminals.

**Comment by NumberX** [comment]
I have two terminal, when i use it just clear one terminal.
i would like to clear all terminals,, how can i do it? .
thanks.

**Comment by Tyriar** [comment]
@NumberX no way currently, via the API you would need https://github.com/Microsoft/vscode/issues/13267

**Comment by NumberX** [comment]
thanks for replay ,how we can use it?

2017-04-26 19:31 GMT+01:00 Daniel Imms <notifications@github.com>:

**Comment by Tyriar** [comment]
@NumberX `vscode.commands.executeCommand` should work https://code.visualstudio.com/docs/extensionAPI/vscode-api

**Comment by NumberX** [comment]
I would like to add textbox and button to the top of terminal in debug mode
.

2017-05-03 2:59 GMT+01:00 Daniel Imms <notifications@github.com>:
