### ISSUE TITLE
Integrated Terminal 's Right click menu disappeared!

### ISSUE THREAD

**Issue by ZCShou** [Microsoft/vscode#17899]
- VSCode Version: Code - Insiders 1.9.0-insider (9486bf472c5c558e4f1793e0e746da88d071b1cc, 2016-12-29T07:11:17.628Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

|Extension|Author|Version|
|---|---|---|
|githistory|donjayamanne|0.1.4|
|output-colorizer|IBM|0.0.8|
|cpptools|ms-vscode|0.9.3|
|vscode-icons|robertohuertasm|4.3.0|

---
Steps to Reproduce:

1. 
2.

**Comment by Tyriar** [comment]
This was intentional, it now behaves similar to cmd.exe where right click when you have a selection will copy (and drop the selection), and right click without a selection will paste. You can turn it off with `"terminal.integrated.rightClickCopyPaste": false`. See #14202.
