### ISSUE TITLE
ENAMETOOLONG error when searching in files

### ISSUE THREAD

**Issue by avroemans** [microsoft/vscode#178975]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: Latest
- OS Version: Windows 10

Steps to Reproduce:

1. Search for something

Note that the error only occurs when I search for a string longer than 17 characters.

![image](https://user-images.githubusercontent.com/113425946/229455992-ba683319-712a-45ff-b1ea-bcede19a5fb2.png)
![image](https://user-images.githubusercontent.com/113425946/229455924-704ccb4b-757a-45e5-b4ad-1ed59e1e79fc.png)

**Comment by roblourens** [comment]
Likely due to having a long list of search exclude patterns, long workspace folder name, etc

**Comment by avroemans** [comment]
Still feels like an issue though, or at least a more accurate error message would be nice.

Are there any ways to debug this? I don't have any weird directory names, and no search patterns either as far as I know. Also, I've been working on this project without any problems for months and this occured randomly now.
