### ISSUE TITLE
Continuous run for ONLY selected tests

### ISSUE THREAD

**Issue by matepek** [microsoft/vscode#178973]
Currently all the explored tests are rerun when one of them are changed.
My users would like to run a set of tests only sometime. Currently there are o option for that.
There is a plan for adding that to the [UI](https://github.com/microsoft/vscode/issues/134941#issuecomment-1382158269).
Would be great to see that feature soon. Thanks.

(First maybe just the filtering could work. That's probably smaller change, then an advanced UI with advanced configuration would be the final solution.)

**Comment by connor4312** [comment]
First pass:

https://user-images.githubusercontent.com/2230985/229942845-1595a678-a678-47e6-9a7e-5fd828dd958c.mp4

**Comment by connor4312** [comment]
Closing this to mark as done. Please let me know if anyone has additional feedback.

**Comment by connor4312** [comment]
You can verify at an API or UI level starting with the [selfhost test provider](https://github.com/microsoft/vscode-selfhost-test-provider).

Verify continuous runs [are requested](https://github.com/microsoft/vscode-selfhost-test-provider/blob/6cc5ffdc6f4a7bc23aa87b1919be6485259dd2b2/src/extension.ts#L83) and cancelled as you enable and disable continuous test running for specific tests in the vscode repo. If continuous test run is enabled for its tests, the icon should be always show and the test should be pinned as in my demo video above. Continuous test run cannot be toggled for subtests of a parent test.

**Comment by roblourens** [comment]
1. I think I'm not a fan of the fact that setting the top level test file to continuous run pins it to the top and shows the 👁️ but if I do that on a child item and collapse the parent, it is not pinned to the top and there is no way to tell that there is another continuous run item there. It feels inconsistent to be setting aside some 👁️ items, but only some of them.
2. That should be easy with the extra options I added for Jupyter Run By Line, if you add debugging
