### ISSUE TITLE
vs code take too much time to open 

### ISSUE THREAD

**Issue by NirmalJT** [microsoft/vscode#178946]
Type: <b>Bug</b>

vs code is running smothly since i install it but suddenly from tommorow performance issue is appear its take to much time to load/open and after waiting so long  its shows a popop that  shows the window is not reponding and three option were given reopen ,close ,keep waiting thats the problem i did what ever i can do to resolve this problem like install it again and deleting extension and  runing windows troublshoter my others apps are running smothly and pc is also goods a i5 10gen procesor and hvaing gtx1650  ....................

VS Code version: Code 1.77.0 (7f329fe6c66b0f86ae1574c2911b681ad5a45d63, 2023-03-29T10:02:16.981Z)
OS version: Windows_NT x64 10
![problem](https://user-images.githubusercontent.com/129684450/229370727-021fa937-5cc4-4977-b063-dec33b6a0f18.jpeg)
.0.22621
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-10200H CPU @ 2.40GHz (8 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|7.84GB (3.51GB free)|
|Process Argv|--crash-reporter-id ee2b6a89-cff7-488e-87ab-e46cf0aa13b2|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
LiveServer|rit|5.7.9

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
nodejswelcome1:30587005
3biah626:30602489
pyind779:30671433
89544117:30613380
pythonsymbol12:30671437
2i9eh265:30646982
6233i204:30672705
vsccsb:30677849
azdwalk:30687957
pythonms35:30701012

```

</details>

**Comment by Kathund** [comment]
Run `code . --disable-extensions` in your terminal to test with extenstions disabled. this will help us detect if its extention related or not

**Comment by NirmalJT** [comment]
I did already but nothing change

**Comment by NirmalJT** [comment]
I did but nothing change

**Comment by NirmalJT** [comment]
> Run `code . --disable-extensions` in your terminal to test with extenstions disabled. this will help us detect if its extention related or not

I did but nothing change

**Comment by yaswantkumar33** [comment]
I do have the same issue , I completely reset my pc but still getting the same issue

**Comment by yaswantkumar33** [comment]
can anyone give solution for this !!!!!

**Comment by deepak1556** [comment]
Merging to https://github.com/microsoft/vscode/issues/178962

Please follow the workaround mentioned in https://github.com/microsoft/vscode/issues/178733#issuecomment-1500812938 until the issue is resolved.

**Comment by NirmalJT** [comment]
Thanks for your reply my problem is solve now it was  happen because of my antivirus
