### ISSUE TITLE
Proposal: Use "pragma comment" for running tasks in VS Code

### ISSUE THREAD

**Issue by SetTrend** [microsoft/vscode#1789]
Running tasks in VS Code seems more administration/execution pain than necessary to me.

I suggest to support a `pragma comment` preceding a task, serving as a tag for the IDE to be able to recognize and run tasks of different task runners.

The name of the suggested pragma comment is: `//# task`. It may be followed by an optional options object literal:

``` javascript
var gulp = require("gulp");
var ts = require("gulp-typescript");

//# task { problemMatcher: "$tsc" }
gulp.task("scripts", function () { gulp.src().pipe(ts).pipe(gulp.dest()); })
```

**Comment by alexr00** [comment]
This could be done in an extension! You can write an extension that looks for lines like this in a file, create a task, and run it.
