### ISSUE TITLE
Add "Break" button to "Syncrhonizing changes" process in Source Control panel

### ISSUE THREAD

**Issue by MurzNN** [microsoft/vscode#178966]
Sometimes when we click on the "Sync Changes" button in the Source Control panel and the remote is not available for some reason (wrong remote is selected, wrong host is configured, server is down, no internet connection, no VPN connection, etc), the syncing process hangs for a pretty long time. And we have no ways to stop it, only have to wait and wait! 

So, we have to wait for **several minutes** to see something like "Connection timed out" and only after this - can fix the error and try again.

To resolve this issue will be good to add a button "Stop" that will forcibly stop the hanged syncing process.

**Comment by lszomoru** [comment]
You can enable cancellation for the "Sync Changes" command using the `git.supportCancellation` setting.
