### ISSUE TITLE
Missing highlight and code hints

### ISSUE THREAD

**Issue by Graptos** [microsoft/vscode#178976]
Type: Bug

Good afternoon, code selection highlighting is gone, for example, part of the library (selenium, aiogram...) is not highlighted. 
Methods are called without libraries, and also do not highlight colors and do not recognize auto-suggestions.
The problem appeared on two different devices. Possibly related to the latest update.

VS Code version: Code 1.76.2 (https://github.com/microsoft/vscode/commit/ee2b180d582a7f601fa6ecfdad8d9fd269ab1884, 2023-03-14T17:55:54.936Z)
OS version: Windows_NT x64 10.0.19044
Modes:
Sandboxed: Yes

**System Info:**

CPUs    AMD Ryzen 5 5500U with Radeon Graphics (12 x 2096)
GPU Status	2d_canvas: enabled
                        canvas_oop_rasterization: disabled_off
                        direct_rendering_display_compositor: disabled_off_ok
                        gpu_compositing: enabled
                        multiple_raster_threads: enabled_on
                        opengl: enabled_on
                        rasterization: enabled
                        raw_draw: disabled_off_ok
                        skia_renderer: enabled_on
                        video_decode: enabled
                        video_encode: enabled
                        vulkan: disabled_off
                        webgl: enabled
                        webgl2: enabled
                        webgpu: disabled_off
Load (avg)	undefined
Memory (System)	7.33GB (2.40GB free)
Process Argv	E:\Tests\spybot\spybot.py --crash-reporter-id ed2bbd6b-10e4-46bd-86d7-7d5a797349af --crash-reporter-id ed2bbd6b-10e4-46bd-86d7-7d5a797349af --crash-reporter-id ed2bbd6b-10e4-46bd-86d7-7d5a797349af
Screen Reader	no
VM	0%

**Extensions (7)**
Extension	Author (truncated)	Version
vscode-language-pack-ru	MS-	1.76.2023031509
isort	ms-	2022.8.0
python	ms-	2023.4.1
vscode-pylance	ms-	2023.3.30
jupyter	ms-	2023.2.1200692131
jupyter-keymap	ms-	1.1.0
vscode-jupyter-cell-tags	ms-	0.1.8

**A/B Experiments**
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
vscccc:30610679
pyindex848:30662994
nodejswelcome1:30587005
282f8724:30602487
pyind779:30671433
89544117:30613380
pythonsymbol12:30671437
2i9eh265:30646982
6233i204:30672705
vsctsb:30677850
defaultazurewalk:30687958
pythonms35:30686772

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

**Comment by Graptos** [comment]
> Спасибо за создание этой проблемы! Похоже, вы используете старую версию VS Code, последняя стабильная версия 1.77.0. Пожалуйста, попробуйте выполнить обновление до последней версии и проверьте, сохраняется ли эта проблема.
> 
> Счастливого кодирования!

Установлена последняя актуальная версия, 1.77.1

**Comment by Graptos** [comment]
> Воспроизводится ли это в [последней сборке VS Code insiders](https://code.visualstudio.com/insiders/) со всеми отключенными [расширениями](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

If all extensions are disabled, then in general all libraries do not have highlighting and support for "insiders"

**Comment by mjbvz** [comment]
What programming language are you working in?

**Comment by QuellaZhang** [comment]
The same problem happened when I am using Python. Selenium module is installed and can be used, but it is not highlighted and can't go to definition, intellisense is gone.

VSCode v1.77.2 + Python v3.10.11

![image](https://user-images.githubusercontent.com/36754348/231671995-23773148-d1ca-4558-92e8-5d6aa526a511.png)

**Comment by mjbvz** [comment]
@QuellaZhang Please feel your issue against the python extension

**Comment by mjbvz** [comment]
Closing as we need more info from the original poster to investigate
