### ISSUE TITLE
Alt+Cmd+T does not close other opened tabs on editor

### ISSUE THREAD

**Issue by mbarzeev** [Microsoft/vscode#17898]
- VSCode Version: Code - Insiders 1.9.0-insider (9486bf472c5c558e4f1793e0e746da88d071b1cc, 2016-12-29T07:05:11.443Z)
- OS Version: Darwin x64 14.5.0
- Extensions:

|Extension|Author|Version|
|---|---|---|
|Handlebars|andrejunges|0.2.0|
|vscode-eslint|dbaeumer|1.2.2|
|githistory|donjayamanne|0.1.4|
|LogFileHighlighter|emilast|1.0.1|
|vscode-firefox-debug|hbenl|0.7.7|
|gitblame|waderyan|1.3.0|

---

Steps to Reproduce:

1. Open several files on a single editor
2. Press Alt+Cmd+T to close all but the one you're on

Nothing happens. All files remain open.
Thanks

**Comment by bpasero** [comment]
Caused by https://github.com/Microsoft/vscode/commit/bc46e789ac57f327f409260fb8cc1f6e40e62a7b
