### ISSUE TITLE
Long delay when trying to open a file or folder

### ISSUE THREAD

**Issue by qobus** [Microsoft/vscode#17893]
- VSCode Version: Code 1.8.1 (ee428b0eead68bf0fb99ab5fdc4439be227b6281, 2016-12-19T14:49:23.350Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions:

|Extension|Author|Version|
|---|---|---|
|html-snippets|abusaidm|0.0.18|
|php-intellisense|felixfbecker|0.0.12|
|rest-client|humao|0.11.2|
|vs-color-picker|lihui|0.3.2|
|vscode-icons|robertohuertasm|4.3.0|
|code-settings-sync|Shan|2.3.8|

---

Since last update to 1.8.1 it takes certain minutes (> 10) to open a file or folder.
I normally start the editor and open a folder using "File -> Open Folder".
The exporer window does'nt even appear.

I've also disabled all of the above mentioned plugin and tried to reinstall VS Code but that led to no success.

Any other editor action is fast and does not cause a delay. If i run "code ." in my cmd it'll open my current folder immediately.

**Comment by bpasero** [comment]
@qobus so you say the native windows file dialog takes 10 minutes to show? this sounds like a problem with windows itself. does it reproduce in other applications (e.g. notepad)?
