### ISSUE TITLE
Debugger: Function Names not Visible in the Call Stack View

### ISSUE THREAD

**Issue by walles** [microsoft/vscode#178964]
Does this issue occur when all extensions are disabled?: N/A The issue is with the bundled call stack view (see attached movie clip), but I have to have the Go extension enabled to demo it with Go code and show the issue.

- VS Code Version: 1.77.0
- OS Version: macOS Big Sur 11.7.3

Steps to Reproduce:

1. Load a Go project
2. Set a breakpoint
3. Launch the program and have it stop in the debugger

I would prefer if function names were visible in the call stack view without having to make the side bar really really wide.

# Demo

https://user-images.githubusercontent.com/158201/229415502-941c4bee-cc7f-4190-8599-58c9f538e08a.mov

**Comment by walles** [comment]
Tagging @roblourens since this is close to #178308.

**Comment by roblourens** [comment]
Please file this on the repo for the Go extension. I think that the extension should either change what it is sending as the frame name (I'm not a Go expert so I'm not sure how to interpret what I see in your screenshot) or they can suggest a helpful way for us to truncate stack frame names in the UI that would preserve the most helpful info.

**Comment by walles** [comment]
> screenshot

Just to avoid any mistakes, this is a 22s video, can you confirm that you saw what the stack trace looked like towards the end, when the Call Stack View was much wider?

Either way, I now passed this on to what I believe might be the right place: https://github.com/go-delve/delve/issues/3323

**Comment by roblourens** [comment]
I see it, but vscode only displays what the extension sends us, and it sent us a really long name

**Comment by aarzilli** [comment]
>  or they can suggest a helpful way for us to truncate stack frame names in the UI that would preserve the most helpful info.

Is there a way in the protocol to do this?
