### ISSUE TITLE
Not auto complete for grammar only languages like C++, Python, CoffeeScript...

### ISSUE THREAD

**Issue by RafaeI** [Microsoft/vscode#179]
no more auto completions? vscode doesn't give me suggestions to auto complete as I type.

**Comment by chucongqing** [comment]
same issue, but it could be triggered by ctrl + space

**Comment by RafaeI** [comment]
Thanks ;)

**Comment by RafaeI** [comment]
thanks :+1:

**Comment by jrieken** [comment]
@RafaeI In what language do you see that?

**Comment by RafaeI** [comment]
@jrieken python and c++

**Comment by kravchenkodev** [comment]
I have the same issue in CoffeeScript and React (JSX) files.

**Comment by riquito** [comment]
Just installed version 0.10.1, in a PHP project if I write a variable in a line and in the next line I try to autocomplete it via CTRL+SPACE a "Loading..." message appears, and the variable is never autocompleted.

**Comment by chucongqing** [comment]
@jrieken just reinstall it ,still don't work. could only see the suggestions by ctrl+space

**Comment by Krzysztof-Cieslak** [comment]
By @egamma in preview repo:

>This is intentional, we only enable eager 7x24 Intellisense when the suggestion are 'intelligent'. When you only get word based completions we do not enable 7x24.

Maybe that's issue?

**Comment by jrieken** [comment]
Yes, for languages like TypeScript and C# we have extensions that provide smart completions, for other we do a textual completion. Those we make show less aggressive

**Comment by maritz** [comment]
@Krzysztof-Cieslak It works fine in Typescript, so I assume it is related to that.
Still: when pressing CTRL+Space I just get perpetual "Loading..." as well. (in javascript)

**Comment by kravchenkodev** [comment]
@jrieken Please, could you provide solution to make vscode behave same way as previous version did? Quick suggestion really helps to save time.

**Comment by ojss** [comment]
@jrieken Same issue here. IntelliSense is working fine for JS but not showing any suggestions for C# file.

**Comment by zsxawerdu** [comment]
I am having the same issue.  My work laptop (OS X 10.10.5) it works fine on all languages.  My personal laptop ( OS X 10.11.1 ) some languages it works fine, some not.  I tried uninstall / reinstall still the same issues.

**Comment by ojss** [comment]
For now I have reverted to an older version.

**Comment by tominon** [comment]
PHP is also affected. See #161

**Comment by DerTolleEmil** [comment]
@riquito autocomplete seems to be rather broken in php in general in this build, either not giving any hints at all or even completely freezing, see issue #160

**Comment by tangshi** [comment]
@ojss where can I download the older version?

**Comment by A2C013** [comment]
I just got the same issue. in the previous version (0.9.1), when I was writing Python scripts, the word completion works fine, though it is textual. But now the functionality is gone. I tried to reinstall it, but nothing changed. Hope can recover this function soon. Thanks:)

**Comment by ojss** [comment]
Sorry cant help with that. I had the zip for the previous version lying around.

**Comment by DerTolleEmil** [comment]
@tangshi @ojss The old version (plus how to disable the auto update) can be found in issue #160, comment https://github.com/Microsoft/vscode/issues/160#issuecomment-158093149

**Comment by ojss** [comment]
Wow thats great! Thank you.

**Comment by tnaseem** [comment]
I'm experience the same issues in C# - no autocompletion.

However, hitting ctrl-space brings it up. Bit annoying to have to do this though. I thought there may have been a new option to switch on the 'auto' bit of completing, but can't find it!

**Comment by ojss** [comment]
For me ctrl+space doesn’t help.

**Comment by DGideas** [comment]
Same issue

**Comment by lzantal** [comment]
Yep, same here

**Comment by egamma** [comment]
This issue only tracks the problem that there is no more auto complete for languages which only support tokenization using a textmate grammar. Issues with PHP, TypeScript are separate issues.
