### ISSUE TITLE
Take around 10 seconds to startup

### ISSUE THREAD

**Issue by NareshChinnusamy** [microsoft/vscode#179044]
Type: <b>Bug</b>

I installed the latest version, when i try to open it takes about 10 seconds to start in windows 11

VS Code version: Code 1.77.0 (7f329fe6c66b0f86ae1574c2911b681ad5a45d63, 2023-03-29T10:02:16.981Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz (8 x 2419)|
|GPU Status|2d_canvas: unavailable_software<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>opengl: disabled_off<br>rasterization: disabled_software<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.77GB (5.14GB free)|
|Process Argv|--crash-reporter-id dbf926cf-f547-443b-ad10-962bd612378f|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vscaac:30438847
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
vscccc:30610679
nodejswelcome1:30587005
2e4cg342:30602488
pyind779:30671433
89544117:30613380
vscrpc:30673769
pythonsymbol12:30671437
2i9eh265:30646982
vsccsb:30677849
pythonb192:30669360
functionswalk:30687959
pythonms35:30701012

```

</details>

**Comment by deepak1556** [comment]
Can you attach the startup timers following the steps at https://github.com/microsoft/vscode/wiki/Performance-Issues#read-the-startup-timers

**Comment by NareshChinnusamy** [comment]
## System Info

* Code: 1.77.0 (7f329fe6c66b0f86ae1574c2911b681ad5a45d63)
* OS: win32(10.0.22621)
* CPUs: 11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz(8 x 2419)
* Memory(System): 15.77 GB(8.44GB free)
* Memory(Process): 191.90 MB working set(140.49MB private, 18.20MB shared)
* VM(likelihood): 0%
* Initial Startup: true
* Has 0 other windows
* Screen Reader Active: false
* Empty Workspace: false

## Performance Marks

| What                                                            | Duration | Process                   | Info                                                       |
| --------------------------------------------------------------- | -------- | ------------------------- | ---------------------------------------------------------- |
| start => app.isReady                                            | 1497     | [main]                    | initial startup: true                                      |
| nls:start => nls:end                                            | 0        | [main]                    | initial startup: true                                      |
| require(main.bundle.js)                                         | 90       | [main]                    | initial startup: true                                      |
| start crash reporter                                            | 1450     | [main]                    | initial startup: true                                      |
| serve main IPC handle                                           | 2        | [main]                    | initial startup: true                                      |
| create window                                                   | 37       | [main]                    | initial startup: true, state: 0ms, widget: 36ms, show: 0ms |
| app.isReady => window.loadUrl()                                 | 165      | [main]                    | initial startup: true                                      |
| window.loadUrl() => begin to require(workbench.desktop.main.js) | 4265     | [main->renderer]          | NewWindow                                                  |
| require(workbench.desktop.main.js)                              | 263      | [renderer]                | cached data: YES, node_modules took 0ms                    |
| wait for window config                                          | 0        | [renderer]                | -                                                          |
| init storage (global & workspace)                               | 14       | [renderer]                | -                                                          |
| init workspace service                                          | 25       | [renderer]                | -                                                          |
| register extensions & spawn extension host                      | 129      | [renderer]                | -                                                          |
| restore viewlet                                                 | 11       | [renderer]                | workbench.view.explorer                                    |
| restore panel                                                   | 0        | [renderer]                | -                                                          |
| restore & resolve visible editors                               | 154      | [renderer]                | 1: workbench.editors.files.fileEditorInput                 |
| overall workbench load                                          | 414      | [renderer]                | -                                                          |
| workbench ready                                                 | 6639     | [main->renderer]          | -                                                          |
| renderer ready                                                  | 720      | [renderer]                | -                                                          |
| shared process connection ready                                 | 0        | [renderer->sharedprocess] | -                                                          |
| extensions registered                                           | 6712     | [renderer]                | -                                                          |

## Extension Activation Stats

| Extension                               | Eager | Load Code | Call Activate | Finish Activate | Event                             | By                                      |
| --------------------------------------- | ----- | --------- | ------------- | --------------- | --------------------------------- | --------------------------------------- |
| vscode.git                              | true  | 27        | 16            | 193             | *                                 | vscode.git                              |
| vscode.git-base                         | true  | 4         | 0             | 0               | *                                 | vscode.git                              |
| vscode.github                           | true  | 5         | 0             | 0               | *                                 | vscode.github                           |
| vscode.configuration-editing            | false | 5         | 0             | 0               | onLanguage:jsonc                  | vscode.configuration-editing            |
| vscode.debug-auto-launch                | false | 3         | 0             | 0               | onStartupFinished                 | vscode.debug-auto-launch                |
| vscode.emmet                            | false | 8         | 4             | 0               | onLanguage                        | vscode.emmet                            |
| vscode.extension-editing                | false | 8         | 0             | 0               | onLanguage:markdown               | vscode.extension-editing                |
| vscode.github-authentication            | false | 18        | 1             | 2               | onAuthenticationRequest:github    | vscode.github-authentication            |
| vscode.json-language-features           | false | 16        | 0             | 2785            | onLanguage:jsonc                  | vscode.json-language-features           |
| vscode.merge-conflict                   | false | 13        | 2             | 1               | onStartupFinished                 | vscode.merge-conflict                   |
| vscode.microsoft-authentication         | false | 15        | 0             | 2534            | onAuthenticationRequest:microsoft | vscode.microsoft-authentication         |
| ms-vscode-remote.remote-wsl-recommender | false | 9         | 6             | 2               | onStartupFinished                 | ms-vscode-remote.remote-wsl-recommender |
| vscode.typescript-language-features     | false | 11        | 12            | 8               | onLanguage:jsonc                  | vscode.typescript-language-features     |

## Raw Perf Marks: main

```
Name	Timestamp	Delta	Total
code/timeOrigin	1680576828295.644	0	0
code/didStartMain	1680576828376	80.35595703125	80.35595703125
code/willStartCrashReporter	1680576828393	17	97.35595703125
code/didStartCrashReporter	1680576829843	1450	1547.35595703125
code/mainAppReady	1680576829873	30	1577.35595703125
code/willGenerateNls	1680576829874	1	1578.35595703125
code/willLoadMainBundle	1680576829878	4	1582.35595703125
code/fork/willLoadCode	1680576829893	15	1597.35595703125
code/registerFilesystem/file	1680576829959	66	1663.35595703125
code/didLoadMainBundle	1680576829968	9	1672.35595703125
code/willStartMainServer	1680576829975	7	1679.35595703125
code/didStartMainServer	1680576829977	2	1681.35595703125
code/willCreateCodeWindow	1680576830000	23	1704.35595703125
code/willRestoreCodeWindowState	1680576830000	0	1704.35595703125
code/didRestoreCodeWindowState	1680576830000	0	1704.35595703125
code/willCreateCodeBrowserWindow	1680576830001	1	1705.35595703125
code/didCreateCodeBrowserWindow	1680576830037	36	1741.35595703125
code/didCreateCodeWindow	1680576830037	0	1741.35595703125
code/willOpenNewWindow	1680576830038	1	1742.35595703125
```
## Raw Perf Marks: renderer

```
Name	Timestamp	Delta	Total
code/timeOrigin	1680576830039	0	0
code/didStartRenderer	1680576834295	4256	4256
code/willWaitForWindowConfig	1680576834296	1	4257
code/didWaitForWindowConfig	1680576834296	0	4257
code/willShowPartsSplash	1680576834296	0	4257
code/didShowPartsSplash	1680576834296	0	4257
code/willLoadWorkbenchMain	1680576834303	7	4264
code/didLoadWorkbenchMain	1680576834566	263	4527
code/registerFilesystem/file	1680576834571	5	4532
code/registerFilesystem/vscode-userdata	1680576834571	0	4532
code/willInitWorkspaceService	1680576834573	2	4534
code/willInitStorage	1680576834574	1	4535
code/willInitUserConfiguration	1680576834579	5	4540
code/didInitStorage	1680576834588	9	4549
code/didInitUserConfiguration	1680576834590	2	4551
code/willInitWorkspaceConfiguration	1680576834590	0	4551
code/didInitWorkspaceConfiguration	1680576834598	8	4559
code/didInitWorkspaceService	1680576834598	0	4559
code/willStartWorkbench	1680576834601	3	4562
code/LifecyclePhase/Ready	1680576834603	2	4564
code/willCreateWorkbenchContributions/1	1680576834651	48	4612
code/didCreateWorkbenchContributions/1	1680576834672	21	4633
code/willCreateWorkbenchContributions/2	1680576834672	0	4633
code/registerFilesystem/trustedDomains	1680576834675	3	4636
code/registerFilesystem/vscode-interactive	1680576834676	1	4637
code/registerFilesystem/vscode-local-history	1680576834678	2	4639
code/didCreateWorkbenchContributions/2	1680576834681	3	4642
code/willCreatePart/workbench.parts.titlebar	1680576834781	100	4742
code/didRemovePartsSplash	1680576834788	7	4749
code/didCreatePart/workbench.parts.titlebar	1680576834810	22	4771
code/willCreatePart/workbench.parts.banner	1680576834810	0	4771
code/didCreatePart/workbench.parts.banner	1680576834810	0	4771
code/willCreatePart/workbench.parts.activitybar	1680576834810	0	4771
code/didCreatePart/workbench.parts.activitybar	1680576834814	4	4775
code/willCreatePart/workbench.parts.sidebar	1680576834814	0	4775
code/didCreatePart/workbench.parts.sidebar	1680576834815	1	4776
code/willCreatePart/workbench.parts.editor	1680576834815	0	4776
code/willCreateTextFileEditorControl	1680576834826	11	4787
code/didCreateTextFileEditorControl	1680576834832	6	4793
code/willSetInputToTextFileEditor	1680576834833	1	4794
code/didCreatePart/workbench.parts.editor	1680576834846	13	4807
code/willCreatePart/workbench.parts.panel	1680576834846	0	4807
code/didCreatePart/workbench.parts.panel	1680576834847	1	4808
code/willCreatePart/workbench.parts.auxiliarybar	1680576834847	0	4808
code/didCreatePart/workbench.parts.auxiliarybar	1680576834848	1	4809
code/willCreatePart/workbench.parts.statusbar	1680576834848	0	4809
code/didCreatePart/workbench.parts.statusbar	1680576834849	1	4810
code/willRestoreEditors	1680576834861	12	4822
code/restoreEditors/editorGroupsReady	1680576834865	4	4826
code/willRestoreViewlet	1680576834865	0	4826
code/willResolveTextFileEditorModel	1680576834875	10	4836
code/restoreEditors/editorsToOpenResolved	1680576834876	1	4837
code/didRestoreViewlet	1680576834876	0	4837
code/willRegisterExplorerViews	1680576834876	0	4837
code/willResolveExplorer	1680576834921	45	4882
code/didRegisterExplorerViews	1680576834923	2	4884
code/willLoadExtensions	1680576834959	36	4920
code/didResolveTextFileEditorModel	1680576834992	33	4953
code/didSetInputToTextFileEditor	1680576835010	18	4971
code/restoreEditors/editorGroupsRestored	1680576835015	5	4976
code/didRestoreEditors	1680576835015	0	4976
code/didStartWorkbench	1680576835015	0	4976
code/LifecyclePhase/Restored	1680576835015	0	4976
code/willCreateWorkbenchContributions/3	1680576835015	0	4976
code/willConnectSharedProcess	1680576835016	1	4977
code/willHandleExtensionPoints	1680576835032	16	4993
code/willHandleExtensionPoint/configurationDefaults	1680576835032	0	4993
code/didHandleExtensionPoint/configurationDefaults	1680576835033	1	4994
code/willHandleExtensionPoint/configuration	1680576835033	0	4994
code/didHandleExtensionPoint/configuration	1680576835046	13	5007
code/willHandleExtensionPoint/jsonValidation	1680576835046	0	5007
code/didHandleExtensionPoint/jsonValidation	1680576835046	0	5007
code/willHandleExtensionPoint/debuggers	1680576835046	0	5007
code/didHandleExtensionPoint/debuggers	1680576835046	0	5007
code/willHandleExtensionPoint/breakpoints	1680576835046	0	5007
code/didHandleExtensionPoint/breakpoints	1680576835046	0	5007
code/willHandleExtensionPoint/notebooks	1680576835046	0	5007
code/didHandleExtensionPoint/notebooks	1680576835047	1	5008
code/willHandleExtensionPoint/notebookRenderer	1680576835047	0	5008
code/didHandleExtensionPoint/notebookRenderer	1680576835047	0	5008
code/willHandleExtensionPoint/problemPatterns	1680576835047	0	5008
code/didHandleExtensionPoint/problemPatterns	1680576835048	1	5009
code/willHandleExtensionPoint/problemMatchers	1680576835048	0	5009
code/didHandleExtensionPoint/problemMatchers	1680576835048	0	5009
code/willHandleExtensionPoint/taskDefinitions	1680576835048	0	5009
code/didHandleExtensionPoint/taskDefinitions	1680576835050	2	5011
code/willHandleExtensionPoint/terminal	1680576835050	0	5011
code/didHandleExtensionPoint/terminal	1680576835050	0	5011
code/willHandleExtensionPoint/terminalQuickFixes	1680576835050	0	5011
code/didHandleExtensionPoint/terminalQuickFixes	1680576835050	0	5011
code/willHandleExtensionPoint/walkthroughs	1680576835050	0	5011
code/didHandleExtensionPoint/walkthroughs	1680576835050	0	5011
code/willHandleExtensionPoint/commands	1680576835050	0	5011
code/didHandleExtensionPoint/commands	1680576835052	2	5013
code/willHandleExtensionPoint/submenus	1680576835052	0	5013
code/didHandleExtensionPoint/submenus	1680576835053	1	5014
code/willHandleExtensionPoint/menus	1680576835053	0	5014
code/didHandleExtensionPoint/menus	1680576835058	5	5019
code/willHandleExtensionPoint/authentication	1680576835058	0	5019
code/didHandleExtensionPoint/authentication	1680576835058	0	5019
code/willHandleExtensionPoint/languages	1680576835058	0	5019
code/didHandleExtensionPoint/languages	1680576835068	10	5029
code/willHandleExtensionPoint/customEditors	1680576835068	0	5029
code/didHandleExtensionPoint/customEditors	1680576835068	0	5029
code/willHandleExtensionPoint/codeActions	1680576835068	0	5029
code/didHandleExtensionPoint/codeActions	1680576835068	0	5029
code/willHandleExtensionPoint/viewsWelcome	1680576835068	0	5029
code/didHandleExtensionPoint/viewsWelcome	1680576835068	0	5029
code/willHandleExtensionPoint/grammars	1680576835068	0	5029
code/didHandleExtensionPoint/grammars	1680576835072	4	5033
code/willHandleExtensionPoint/colors	1680576835072	0	5033
code/didHandleExtensionPoint/colors	1680576835073	1	5034
code/willHandleExtensionPoint/semanticTokenScopes	1680576835073	0	5034
code/didHandleExtensionPoint/semanticTokenScopes	1680576835073	0	5034
code/willHandleExtensionPoint/snippets	1680576835073	0	5034
code/didHandleExtensionPoint/snippets	1680576835074	1	5035
code/willHandleExtensionPoint/keybindings	1680576835074	0	5035
code/didHandleExtensionPoint/keybindings	1680576835079	5	5040
code/willHandleExtensionPoint/themes	1680576835079	0	5040
code/didHandleExtensionPoint/themes	1680576835080	1	5041
code/willHandleExtensionPoint/iconThemes	1680576835080	0	5041
code/didHandleExtensionPoint/iconThemes	1680576835080	0	5041
code/willHandleExtensionPoint/continueEditSession	1680576835080	0	5041
code/didHandleExtensionPoint/continueEditSession	1680576835080	0	5041
code/willHandleExtensionPoint/viewsContainers	1680576835080	0	5041
code/didHandleExtensionPoint/viewsContainers	1680576835083	3	5044
code/willHandleExtensionPoint/views	1680576835083	0	5044
code/didHandleExtensionPoint/views	1680576835085	2	5046
code/didHandleExtensionPoints	1680576835085	0	5046
code/didLoadExtensions	1680576835088	3	5049
code/didResolveExplorer	1680576835224	136	5185
```
## Raw Perf Marks: localExtHost

```
Name	Timestamp	Delta	Total
code/timeOrigin	1680576836517.439	0	0
code/fork/start	1680576836586	68.56103515625	68.56103515625
code/fork/willLoadCode	1680576836605	19	87.56103515625
code/extHost/willConnectToRenderer	1680576836758	153	240.56103515625
code/extHost/didConnectToRenderer	1680576836759	1	241.56103515625
code/extHost/didWaitForInitData	1680576836785	26	267.56103515625
code/extHost/didCreateServices	1680576836786	1	268.56103515625
code/extHost/willWaitForConfig	1680576836799	13	281.56103515625
code/extHost/didWaitForConfig	1680576836805	6	287.56103515625
code/extHost/didInitAPI	1680576836841	36	323.56103515625
code/extHost/didInitProxyResolver	1680576836843	2	325.56103515625
code/extHost/ready	1680576836843	0	325.56103515625
code/extHost/willLoadExtensionCode/vscode.emmet	1680576836845	2	327.56103515625
code/extHost/didLoadExtensionCode/vscode.emmet	1680576836853	8	335.56103515625
code/extHost/willLoadExtensionCode/vscode.configuration-editing	1680576836853	0	335.56103515625
code/extHost/didLoadExtensionCode/vscode.configuration-editing	1680576836858	5	340.56103515625
code/extHost/willLoadExtensionCode/vscode.json-language-features	1680576836859	1	341.56103515625
code/extHost/didLoadExtensionCode/vscode.json-language-features	1680576836875	16	357.56103515625
code/extHost/willLoadExtensionCode/vscode.typescript-language-features	1680576836876	1	358.56103515625
code/extHost/didLoadExtensionCode/vscode.typescript-language-features	1680576836887	11	369.56103515625
code/extHost/willLoadExtensionCode/vscode.github-authentication	1680576836888	1	370.56103515625
code/extHost/didLoadExtensionCode/vscode.github-authentication	1680576836906	18	388.56103515625
code/extHost/willActivateExtension/vscode.emmet	1680576836907	1	389.56103515625
code/extHost/didActivateExtension/vscode.emmet	1680576836911	4	393.56103515625
code/extHost/willActivateExtension/vscode.configuration-editing	1680576836912	1	394.56103515625
code/extHost/didActivateExtension/vscode.configuration-editing	1680576836912	0	394.56103515625
code/extHost/willActivateExtension/vscode.json-language-features	1680576836913	1	395.56103515625
code/extHost/willActivateExtension/vscode.typescript-language-features	1680576836913	0	395.56103515625
code/extHost/didActivateExtension/vscode.typescript-language-features	1680576836939	26	421.56103515625
code/extHost/willActivateExtension/vscode.github-authentication	1680576836940	1	422.56103515625
code/extHost/didActivateExtension/vscode.github-authentication	1680576836945	5	427.56103515625
code/extHost/willLoadExtensionCode/vscode.microsoft-authentication	1680576836965	20	447.56103515625
code/extHost/didLoadExtensionCode/vscode.microsoft-authentication	1680576836980	15	462.56103515625
code/extHost/willActivateExtension/vscode.microsoft-authentication	1680576836989	9	471.56103515625
code/extHost/didActivateExtension/vscode.microsoft-authentication	1680576839523	2534	3005.56103515625
code/extHost/willLoadExtensionCode/vscode.git-base	1680576839529	6	3011.56103515625
code/extHost/didLoadExtensionCode/vscode.git-base	1680576839533	4	3015.56103515625
code/extHost/willActivateExtension/vscode.git-base	1680576839535	2	3017.56103515625
code/extHost/didActivateExtension/vscode.git-base	1680576839535	0	3017.56103515625
code/extHost/willLoadExtensionCode/vscode.git	1680576839537	2	3019.56103515625
code/extHost/didLoadExtensionCode/vscode.git	1680576839563	26	3045.56103515625
code/extHost/willLoadExtensionCode/vscode.github	1680576839564	1	3046.56103515625
code/extHost/didLoadExtensionCode/vscode.github	1680576839568	4	3050.56103515625
code/extHost/willActivateExtension/vscode.git	1680576839569	1	3051.56103515625
code/extHost/willActivateExtension/vscode.github	1680576839593	24	3075.56103515625
code/extHost/didActivateExtension/vscode.github	1680576839593	0	3075.56103515625
code/extHost/didActivateExtension/vscode.json-language-features	1680576839699	106	3181.56103515625
code/extHost/didActivateExtension/vscode.git	1680576839778	79	3260.56103515625
```

## Node Cached Data Stats


### cached data used


### cached data missed


### cached data rejected


### cached data created (lazy, might need refreshes)

**Comment by deepak1556** [comment]
Do you have McAfee antivirus installed, we had reports https://github.com/microsoft/vscode/issues/178733 , https://github.com/microsoft/vscode/issues/177570 with the AV slowing down startup with recent update.

**Comment by NareshChinnusamy** [comment]
Yes @deepak1556. I have been using macafee for malware protection.

**Comment by NareshChinnusamy** [comment]
But when I added theCode.exe in the MacAfee real-time scanning in the excluded files section. It works fine. Than you for your suggestions @deepak1556 .

**Comment by deepak1556** [comment]
Thanks for confirming, tracked under https://github.com/microsoft/vscode/issues/179044
