### ISSUE TITLE
Visual Studio Code strange bug in extensions GUI

### ISSUE THREAD

**Issue by galinkyuchukov** [Microsoft/vscode#17909]
- VSCode Version: 1.8.1
- OS Version: Ubuntu 14.04

Suddenly VSCode started to show the extensions as follows:

![111111](https://cloud.githubusercontent.com/assets/177999/21550689/9287928e-ce04-11e6-95c7-be633cc49657.png)

And this is how extension panel looks normaly:
![extension-gallery_extensions-popular](https://cloud.githubusercontent.com/assets/177999/21550752/0af1da90-ce05-11e6-97d5-1d702c07b553.png)

You can see - no extension image, no downloaded count icon, no rating stars!!! Just yesterday it was normal. No settings added/removed/edited, no new extensions installed.

Also i did VSCode uninstall and ~/.vscode and ~/.config/Code removed. Then install again with Ubuntu Software Center ... the problem is still there.

Is there any VS Code bug?

**Comment by rebornix** [comment]
@galinkyuchukov this is because the extension viewlet in that situation is not wide enough, if you drag right boundary of the viewlet and you can see the images or so when the viewlet is wide enough. It's kind of `responsive`.
