### ISSUE TITLE
Multi File Diff Editor

### ISSUE THREAD

**Issue by lszomoru** [microsoft/vscode#179000]
Explore creating a custom editor that would show a list of diff editor widget.

**Comment by 7rulnik** [comment]
@lszomoru do I understand it correctly that basically, it's a one-long list of diffs like in GitHub PRs?

**Comment by jacekkopecky** [comment]
@lszomoru do you mean something similar to my extension [Whole Diff](https://marketplace.visualstudio.com/items?itemName=JacekKopecky.whole-diff) ?

**Comment by hediet** [comment]
See [here](https://github.com/microsoft/vscode/issues/185647) for how virtualization could be achieved.

**Comment by Igorgro** [comment]
@hediet what do you think about extension mentioned above?

**Comment by eamodio** [comment]
@hediet Loving where this is going so far, but I've noticed some issue, but also would love to see additions/changes to the new `vscode.changes` command. How should I best report those? I didn't see a specific issue for the `vscode.changes` command.

**Comment by hediet** [comment]
The `vscode.changes` command is experimental and subject to change. Feel free to create individual issues! But we cannot commit on stable API yet.
