### ISSUE TITLE
add "terminal-fish" icon

### ISSUE THREAD

**Issue by ognevnydemon** [microsoft/vscode#179085]
add terminal-fish icon in vscode

**Comment by Tyriar** [comment]
@ognevnydemon When I looked into adding this I could only see an ascii logo which doesn't translate to the small icon well, is there another official logo I'm not aware of?

**Comment by ognevnydemon** [comment]
@Tyriar ok. I'll try to find out later

**Comment by ognevnydemon** [comment]
@Tyriar can't this be used as icon?
https://avatars.githubusercontent.com/u/1828073?s=200&v=4

**Comment by Tyriar** [comment]
Yeah that's the one, we would need something that looks good and is identifiable in like 16x16 pixels. That icon has too much detail

**Comment by ognevnydemon** [comment]
![image](https://user-images.githubusercontent.com/119937608/235298315-00708fe3-c115-405b-a8e6-c7c8dc7cea50.png)
could be used

**Comment by Tyriar** [comment]
That's not the official logo though so it's ambiguous. Plus it's not particularly attractive compared to the default imo.

If you're just looking to differentiate it, you can add a custom icon (from the existing set of codicons) to your fish profile.
