### ISSUE TITLE
Syntax Highlighting Error

### ISSUE THREAD

**Issue by Wang-Yile** [microsoft/vscode#179043]
Type: <b>Bug</b>

When I wrote a HTML text in VS Code with Python extension,
I found this line:
```
<span class="comment"># Python 3</span>
```
has some problems in highlighting syntax.

It **expects red** because it is in a **read-only** string.
But, **in fact, it is green**.
That means the extension thinks it is notes.

I am using _Python 3.11.2 (64-bits)_

This my code:
```python3
_html = r"""
        <!DOCTYPE html>
        <html>
            <head><meta charset="utf-8"></head>
            <body>
                    <span class="comment"># Python 3</span>
            </body>
        </html>
"""
```
You should copy it into VS Code to see its effect.

Extension version: 2023.7.10901017
VS Code version: Code 1.77.0 (7f329fe6c66b0f86ae1574c2911b681ad5a45d63, 2023-03-29T10:02:16.981Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|12th Gen Intel(R) Core(TM) i5-12400F (12 x 2496)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.79GB (3.91GB free)|
|Process Argv|--crash-reporter-id fc004f5b-7ef2-45d0-a18a-09e9d61149a2|
|Screen Reader|no|
|VM|50%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vstes627:30244334
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
vscccc:30610679
nodejswelcome1cf:30587006
2e4cg342:30602488
pyind779:30671433
f6dab269:30613381
pythonsymbol12:30671437
vsctsb:30677850
functionswalk:30687959
pythonms35:30701012

```

</details>

**Comment by alexr00** [comment]
We get our Python syntax highlighting grammar from https://github.com/MagicStack/MagicPython. I've opened https://github.com/MagicStack/MagicPython/issues/257 for this issue.
