### ISSUE TITLE
Project-wide search is terrible and unreliable

### ISSUE THREAD

**Issue by no3rdw** [microsoft/vscode#179016]
Type: <b>Bug</b>

I cannot believe how terrible VSCode's project-wide search is when working on project files on a remote server.  I write a regular expression, begin the search and wait and wait and wait as the progress bar scrolls and no results are returned.  I have a feeling I know what file contains the thing I'm searching for, so I open that file.  Yup - there's the bit of code I'm searching for, and it matches my regular expression.  Still no search results found...

The search never completes and there is no indication that anything is even happening or any progress is being made.  I eventually give up and open Sublime Text to the same remote folder, copy my exact same regular expression to search in Sublime, and have complete results in seconds.  I'm forced to use VSCode for development and it's extremely frustrating that I need to use a second text editor just for the purpose of searching!  

VS Code version: Code 1.77.0 (7f329fe6c66b0f86ae1574c2911b681ad5a45d63, 2023-03-29T10:02:16.981Z)
OS version: Windows_NT x64 10.0.19042
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2208)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.81GB (17.29GB free)|
|Process Argv|--crash-reporter-id 15092105-6d58-4293-9640-7c911549bea1|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|15.2.0
auto-close-tag|for|0.5.14
live-sass|gle|6.0.4
vscode-cfml|Kam|0.5.4
html5-boilerplate|sid|1.1.1
sass-indented|syl|1.8.26

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscoreces:30445986
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
vsccc:30610678
nodejswelcome1:30587005
282f8724:30602487
pyind779:30671433
f6dab269:30613381
pythonsymbol12:30671437
vscodeenable:30660116
functionswalk:30687959
pythonms35:30701012

```

</details>

**Comment by andreamah** [comment]
I'm sorry to hear about that. Ideally, the search shouldn't be taking so long to finish. You can see [here](https://github.com/microsoft/vscode/wiki/Search-Issues#slow-search-rg-running-for-a-long-time-or-consuming-lots-of-cpumemory) to try to debug why it's taking so long. Just based on your description, this could *perhaps* be an issue with having a very large workspace or an issue with antivirus.
