### ISSUE TITLE
Add commands to get current selected tests/profiles

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#179065]
Expose API commands to get the currently selected tests and profiles

- `vscode.commands.executeCommand('testing.getSelectedProfiles')` -> `{ controllerId: string, kind: TestrunProfileKind, label: string }[]`
- `vscode.commands.executeCommand('testing.getExplorerSelection')` -> `{ include: TestItem[], exclude: TestItem[] }` (like a TestRunRequest)

**Comment by MDcod** [comment]
@connor4312 Hello! 
I found unexpected behavior for new command `testing.getExplorerSelection`. If I run tests using the "Run tests" button from menu header, I get this object from command:
```
exclude: (0) []
include: (1) [{…}]
  0: {items: {…}, label: <accessor>, refreshHandler: <accessor>, id: <accessor>, createRunProfile: ƒ, …}
      createRunProfile: (Ee,he,fe,x,B,Z)=>{let pe=(0,D.hash)(Ee);for(;_.has(pe);)pe++;return new M(this.f,_,z,pe,Ee,he,fe,x,B,Z)}
      createTestItem: ƒ createTestItem(Ee,he,fe){return new v.TestItemImpl(z,Ee,he,fe)}
      createTestRun: (Ee,he,fe=!0)=>this.g.createTestRun(z,Y,Ee,he,fe)
      dispose: ()=>{$.dispose()}
      id: ƒ id(){return z}
      items: {size: <accessor>, forEach: ƒ, replace: ƒ, add: ƒ, delete: ƒ, …}
      label: ƒ label(){return G}
      refreshHandler: ƒ refreshHandler(){return F}
      resolveHandler: ƒ resolveHandler(){return Y.resolveHandler}
```
That is, in the include, I always get an array from one TestController object. This is fine?

**Comment by MDcod** [comment]
The second point, which completely prevents the use of this task as a workaround for [this bug](https://github.com/microsoft/vscode/issues/173017)
