### ISSUE TITLE
Syntax highlighting broken following ES6 spread operator

### ISSUE THREAD

**Issue by jamietre** [Microsoft/vscode#17905]
- VSCode Version: 1.9.0-insider commit 9486b4
- OS Version: Windows 10

Steps to Reproduce:

1. Create an ES6 class using `extends` and add `super(...args)`
2. Observe lack of highlighting after `super(...args)`
3. Profit

Just noticed it this morning on insider build.

Update  - affects any use of spread operator

![image](https://cloud.githubusercontent.com/assets/573056/21546518/3c45a28c-cdad-11e6-9c76-fc41eba35cab.png)

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript-TmLanguage#393
