### ISSUE TITLE
Broken syntax highlighting in TS if no semicolon I used after type

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#179068]
Creating tracking issue for https://github.com/microsoft/TypeScript-TmLanguage/issues/971

Repo:

```ts
let x: number
try {
} catch (err) {}
```

Bad syntax highlighting after `try `

**Comment by einarpersson** [comment]
Do I need to get Visual Studio Code Insiders in order to apply this fix? Right now I cannot even save my files since this seem to interfere with format-on-save 😑

**Comment by TylerLeonhardt** [comment]
@einarpersson a new VS Code stable will be released today.

**Comment by einarpersson** [comment]
@TylerLeonhardt
I am still experiencing this, using VSCode `1.77.3` (Windows 10 / WSL2)

![image](https://user-images.githubusercontent.com/6043691/232480235-1a4cf966-8979-433b-88c2-9c364361b6a3.png)
![image](https://user-images.githubusercontent.com/6043691/232480273-a19e7e8f-153b-4e1d-b13c-20d9b12cb557.png)

**Comment by TylerLeonhardt** [comment]
@mjbvz can you check in with the typescript folks about this?

**Comment by mjbvz** [comment]
@einarpersson  That looks like vue or some other framework. Start by filing the issue against them
