### ISSUE TITLE
VS Code opens in the background when starting from the command line

### ISSUE THREAD

**Issue by dragos** [microsoft/vscode#179098]
Type: <b>Bug</b>

Install the command line tool, then type `code <path>` to open a file or directory. The VS Code window opens but it is behind the current window (Terminal). The same thing happens when I disable extensions (`code --disable-extensions .`).

![Recording 2023-04-04 at 09 49 21](https://user-images.githubusercontent.com/133742/229724925-c37ca6f5-2970-4cdc-aa97-2a885c350763.gif)

VS Code version: Code 1.77.0 (Universal) (7f329fe6c66b0f86ae1574c2911b681ad5a45d63, 2023-03-29T09:57:11.797Z)
OS version: Darwin arm64 22.3.0
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Max (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|2, 3, 4|
|Memory (System)|64.00GB (3.32GB free)|
|Process Argv|. --crash-reporter-id f9c79d5f-4921-4a2a-9321-4a96a8d03e64|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
rest-client|hum|0.25.1
remote-ssh|ms-|0.98.0
remote-ssh-edit|ms-|0.84.0
remote-explorer|ms-|0.2.0
scala|sca|0.5.6
metals|sca|1.22.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
vscccc:30610679
nodejswelcome1cf:30587006
2e4cg342:30602488
pyind779:30671433
f6dab269:30613381
pythonsymbol12:30671437
vsccsb:30677849
defaultazurewalk:30687958
pythonms35:30701012

```

</details>

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by dragos** [comment]
Same thing using

```
Version: 1.78.0-insider (Universal)
Commit: d317fbf2970b8f28bd7c59f545c59532cd5b293c
Date: 2023-04-04T09:42:44.509Z
Electron: 22.4.3
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Darwin arm64 22.3.0
Sandboxed: Yes
```

**Comment by bpasero** [comment]
First time I hear about this, possibly anything on macOS installed that could impact this? Why would no other user see this?

**Comment by dragos** [comment]
Code was one of the first tools to install on my work Mac and it behaved this way from day one. I don't know what it could be, I don't have a lot of software running except fairly standard development tools (IDEA, Terminal, 1Password, Docker...). I'm imagining whatever software interferes would need to be more than a simple "App". How would you go about finding the culprit?

I googled before filing this ticket, and it looks like similar issues happened in the past. Not sure if I'm the only one impacted, hopefully others will land here if I'm not alone :)

**Comment by bpasero** [comment]
Something that integrates into the OS, window managers, mouse drivers, etc.

**Comment by dragos** [comment]
You have a good point, there must be something else playing a role, but I have no idea what it is. But I notice the same behavior when opening the Finder window via the command line (`open .`), so it's not VS Code specific. Closing.

**Comment by dragos** [comment]
For others having the same issue: Disable "Secure Keyboard Entry" from the Terminal menu ([source](https://discussions.apple.com/thread/253635465)) to fix it.
