### ISSUE TITLE
TypeScript doesn't replace half overwrite properly anymore

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#17906]
* open a TypeScript file
* type `cConsole`
* trigger IntelliSense, select `console`
* 🐛 text turns int `cconsole` instead of `console`, debugger shows that the suggestion isn't overwriting enough (`overwriteBefore: 6`)

<img width="1232" alt="screen shot 2016-12-29 at 16 01 10" src="https://cloud.githubusercontent.com/assets/1794099/21546633/5ff125e8-cde0-11e6-9a6a-6e0d5f671b8b.png">

**Comment by mjbvz** [comment]
Thanks for reporting this.

This regression  was introduced by my work to support completions with spaces or other special characters in them. I'll look into a fix for this while still allowing those string completions. My current thought is to compute the replacement range using the current logic plus the old word based range  logic and take whichever is the longer of the two. We could also check the replacement to see if it contains any spaces/special characters when computing the replacement range.

**Comment by jrieken** [comment]
Thanks. The fix makes sense, nit - you could have used [`Range.union`](https://github.com/Microsoft/vscode/blob/master/src/vs/vscode.d.ts#L447)
