### ISSUE TITLE
Opt

### ISSUE THREAD

**Issue by MC-1One** [microsoft/vscode#179072]
Type: <b>Feature Request</b>

I clicked "Check for Updates" and I don't want to be prompted to confirm before closing. It would be better if the window could be closed automatically after the update information is displayed.

By the way, I have a question about managing the enablement status of extensions across multiple workspaces. Can you provide a button to enable or disable extensions in the workspace, and display it in the top-level menu to minimize the number of clicks?

Could you please help me with this?

VS Code version: Code 1.77.0 (7f329fe6c66b0f86ae1574c2911b681ad5a45d63, 2023-03-29T10:02:16.981Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: Yes

**Comment by IllusionMH** [comment]
But it would restart editor "randomly" (based on download/unpack) speed which is definitely not expected behavior for 99% of cases.

As for extension - check docs on Profiles

**Comment by MC-1One** [comment]
#![image](https://user-images.githubusercontent.com/93844898/229700311-b12b2903-96e8-40d0-a7cc-61cd3c13a809.png)
I mean this when no update
I just now found that ESC can do it
Thank you very much
