### ISSUE TITLE
vscode crashes on Ubuntu 18.04 when pressing "Save As" for file or when I want to open directory with the "Open Folder" command

### ISSUE THREAD

**Issue by psimek12** [microsoft/vscode#179009]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.77.0
Version: 1.77.0
Commit: 7f329fe6c66b0f86ae1574c2911b681ad5a45d63
Date: 2023-03-29T10:05:35.165Z
Electron: 19.1.11
Chromium: 102.0.5005.196
Node.js: 16.14.2
V8: 10.2.154.26-electron.0
OS: Linux x64 5.4.0-144-generic snap
Sandboxed: Yes
- OS Version: Ubuntu 18.04.6 LTS

Steps to Reproduce:

1. Open vscode
2. Hit the "Open Folder"

**Comment by deepak1556** [comment]
Merging to https://github.com/microsoft/vscode/issues/178780
