### ISSUE TITLE
Feature request: show only folded region

### ISSUE THREAD

**Issue by kristiandupont** [Microsoft/vscode#17904]
I use [this](http://tibleiz.net/code-browser/index.html) editor because it supports folding in a unique way that I haven't seen elsewhere: it allows you to see only a specific fold, basically making it look like it's the only thing in the entire file.

I would *love* to have this ability in vscode and I'd like to write an extension that allows it. I have been looking at the docs but I am not sure where to start so I thought I'd ask in here if it seems at all possible with the currently exposed APIs and architecture? And if so, what would be some pointers as to where I should start?

**Comment by aeschli** [comment]
I wouldn't call this folding, it's more a differerent way of code browsing, like Smalltalk or the Eclipse browsing perspective had it.
I'm afraid I don't know how to integrate such a browse view to VSCode. (a) we don't allow the contribution of custom viewlets, and (b) our editors are not built to handle such partial file contents.
