### ISSUE TITLE
Add folder in wokspace option doesn't work in last version 1.77.0

### ISSUE THREAD

**Issue by miki018** [microsoft/vscode#179007]
Type: <b>Bug</b>

 When you click on Add folder in wokspace, VSCODE crashes!

VS Code version: Code 1.77.0 (7f329fe6c66b0f86ae1574c2911b681ad5a45d63, 2023-03-29T10:05:35.165Z)
OS version: Linux x64 5.4.0-146-generic snap
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4460  CPU @ 3.20GHz (4 x 2859)|
|GPU Status|2d_canvas: unavailable_software<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>opengl: disabled_off<br>rasterization: disabled_software<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software<br>webgpu: disabled_off|
|Load (avg)|2, 1, 1|
|Memory (System)|7.64GB (3.59GB free)|
|Process Argv|--no-sandbox --disable-gpu|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (128)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-openapi|42C|4.16.4
go-quickly-generator|474|1.1.3
better-comments|aar|3.0.2
vscode-javascript-snippet-pack|aka|0.1.6
Bookmarks|ale|13.3.1
copy-relative-path|ale|0.0.2
git-add-commit-push|alf|0.13.0
json-to-constants|Alm|1.0.0
vscode-eclipse-keybindings|alp|0.16.1
vscode-color|ans|0.4.5
swagger-viewer|Arj|3.1.2
go-restart|art|0.0.2
structify|ash|0.0.1
jar-builder|asl|1.1.1
vsc-export|asl|1.2.0
color-info|bie|0.7.2
vscode-tailwindcss|bra|0.9.11
java-run|cao|1.1.4
gotemplate|cas|0.4.0
path-intellisense|chr|2.8.4
vscode-faker|dee|2.0.0
vscode-springboot-developer-pack|dev|1.0.3
vscode-springboot-snippets|dev|1.2.0
maven-dependency-explorer|dhr|1.0.13
workspace-gitignore|dom|0.0.2
githistory|don|0.6.20
jquerysnippets|don|0.0.1
xml|Dot|2.5.1
redis|Dun|1.4.0
vscode-msgraph-autocomplete|eli|1.2.0
html-to-javascript-string|evi|0.0.6
json2java|fel|1.2.2
auto-close-tag|for|0.5.14
auto-rename-tag|for|0.1.10
code-runner|for|0.12.0
go|gol|0.38.0
vscode-test-explorer|hbe|2.21.1
randomeverything|hel|0.0.3
rest-client|hum|0.25.1
java-properties|ith|0.0.2
mysql-syntax|jak|1.3.1
markdown-extended|jeb|1.1.3
plantuml|jeb|2.17.5
golang-tdd|joa|0.0.9
vscode-codeception|joe|1.2.0
vscode-ext-import-export|jos|0.0.9
thymeleaf|juh|1.0.5
go-struct-tag|liu|0.2.1
regexp-preview|Lou|0.1.5
javadoc-tools|mad|1.6.0
workspace-cacheclean|Mam|0.0.2
go-immutable|Mar|0.0.9
code-groovy|mar|0.1.2
git-stash-viewer|mat|0.1.11
go-struct-tag-autogen|max|1.1.1
plantumlpreviewer|Meb|0.6.0
git-graph|mhu|1.30.0
gitignore|mic|1.0.1
go-method|min|0.4.0
goto-next-previous-member|mis|0.0.6
ecdc|mit|1.8.0
vs-rest-api|mkl|3.0.1
vscode-filesize|mkx|3.1.0
vscode-apache|mrm|1.2.0
vscode-docker|ms-|1.24.0
test-adapter-converter|ms-|0.1.7
gradle-language|nac|0.2.3
reload|nat|0.0.6
color-highlight|nau|2.5.0
go-boost|nei|0.0.5
gotools|neo|0.0.7
vs-html-to-css|nep|1.0.0
vscode-json-editor|nic|0.3.0
vscode-groovy-lint|Nic|2.0.0
kill-process|nir|0.2.0
advanced-new-file|pat|1.2.2
quicktype|qui|12.0.46
htmlescape-vscode-extension|ray|0.0.7
fabric8-analytics|red|0.3.6
java|red|1.16.0
vscode-commons|red|0.0.6
vscode-xml|red|0.24.0
vscode-yaml|red|1.12.2
git-commit-plugin|red|1.1.2
gotomanual|rha|0.2.32
java-sysout|ric|1.2.1
vscode-go-impl-methods|ric|1.1.1
vscode-gradle-extension-pack|ric|0.0.4
LiveServer|rit|5.7.9
vscode-workspace-switcher|sad|1.15.3
vscode-javascript-booster|sbu|14.0.1
workspace-label|Sce|0.0.5
vscode-checkstyle|she|1.4.2
vscode-taskkill|Shy|0.0.65
skaberen-code-generator|Ska|1.0.8
java-generate-setters-getters|soh|7.4.0
spring-code-generator|Son|1.1.0
vscode-buttons|stu|0.0.4
go-run|Tea|0.1.0
umlet|the|15.1.0
scm-buttons-vscode|tom|0.1.1
selectline-statusbar|tom|0.0.2
git-commit-helper-vscode|tre|1.0.1
go-to-method|tri|0.2.0
autocomplate-shell|tru|0.1.1
java-imports-snippets|tus|0.0.1
errorlens|use|3.8.0
gitflow|vec|1.2.1
intellicode-api-usage-examples|Vis|0.2.7
vscodeintellicode|Vis|1.2.30
vscode-boot-dev-pack|vmw|0.2.1
vscode-spring-boot|vmw|1.45.0
vscode-gradle|vsc|3.12.7
vscode-java-debug|vsc|0.49.1
vscode-java-dependency|vsc|0.21.2
vscode-java-pack|vsc|0.25.10
vscode-java-test|vsc|0.38.2
vscode-lombok|vsc|1.1.0
vscode-maven|vsc|0.41.0
vscode-spring-boot-dashboard|vsc|0.12.0
vscode-spring-initializr|vsc|0.11.2
ddl-2-go-struct|wan|0.0.2
vscode-go-autotest|win|1.6.0
jar-viewer|wma|1.2.0
licenser|ymo|1.9.0
current-file-path|Yos|3.1.0
go-snippets|zsh|0.0.4
vscode-proto3|zxh|0.5.5

(1 theme extensions excluded)

</details>

**Comment by ormont** [comment]
I am having the same problem.  After Extension Bisect, I am getting "Extension Bisect is done but no extension has been identified. 
 This might be a problem with Code".
