### ISSUE TITLE
Add possibility to disable "Launch VS Code" after interactive installation

### ISSUE THREAD

**Issue by michael-buchner** [microsoft/vscode#179017]
We are using Microsoft Intune and Company Portal for deploying applications. VS Code is packaged as a semi-automated package to enable the user to configure the installation. System-wide VS Code installer runs with system permissions by default leading to the issue that the user is able to launch VS Code with system permissions. That's a security issue!

Please add a setup parameter switch to prevent the setup from launching VS Code after completion in interactive mode. Inno Setup setup switch /MERGETASKS=!runcode works only with /silent or /verysilent.

**Comment by joaomoreno** [comment]
It's strange to me that you can fully automate installing VS Code via Intune and Company Portal yet you're not using `/silent` or `/verysilent`. Why is that? Isn't the user going to see the installation wizard?

**Comment by michael-buchner** [comment]
> It's strange to me that you can fully automate installing VS Code via Intune and Company Portal yet you're not using `/silent` or `/verysilent`. Why is that? Isn't the user going to see the installation wizard?

As I wrote the user shall be able to configure the options. Meanwhile we have changed our process - we are using /silent and are using the default settings like Explorer Shell integration, PATH variable etc. So we can close this issue.
