### ISSUE TITLE
pip is not recognised

### ISSUE THREAD

**Issue by cp-sam** [microsoft/vscode#179060]
Type: <b>Bug</b>

Hi, please I am a novice at programming and will appreciate any help I can get to sort this issue. I have checked stackoverflow but I can't seem to find the help that can sort this issue for me specifically.

PS C:\Users\hp laptop> pip
pip : The term 'pip' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was 
included, verify that the path is correct and try again.
At line:1 char:1
+ pip
+ ~~~
    + CategoryInfo          : ObjectNotFound: (pip:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

VS Code version: Code 1.77.0 (7f329fe6c66b0f86ae1574c2911b681ad5a45d63, 2023-03-29T10:02:16.981Z)
OS version: Windows_NT x64 10.0.19044
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6300U CPU @ 2.40GHz (4 x 2496)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|7.88GB (1.20GB free)|
|Process Argv|--crash-reporter-id 79e84415-8a2c-4b28-856b-c5fedab112ac|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
chatgpt-vscode|gen|0.0.7
vsc-python-indent|Kev|1.18.0
chatgptplus|mol|2.0.0
python|ms-|2023.6.0
vscode-pylance|ms-|2023.3.40
jupyter|ms-|2023.3.1000892223
jupyter-keymap|ms-|1.1.0
jupyter-renderers|ms-|1.0.15
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-slideshow|ms-|0.1.5

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263cf:30335440
vscoreces:30445986
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vscaat:30438848
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
vscccc:30610679
nodejswelcome1cf:30587006
3biah626:30602489
pyind779:30671433
89544117:30613380
pythonsymbol12:30671437
a9j8j154:30646983
vsctsb:30677850
azdwalk:30687957
pythonms35:30701012

```

</details>

**Comment by Prakash251299** [comment]
Install pip then add the path to the system variable as:
![IMG_20230404_161151](https://user-images.githubusercontent.com/88026044/229769597-f1d9523c-317b-432b-8b19-7240557d97d3.jpg)
![IMG_20230404_161207](https://user-images.githubusercontent.com/88026044/229769624-f6affc66-ca29-4960-89be-aa646e95077e.jpg)
![IMG_20230404_161434](https://user-images.githubusercontent.com/88026044/229769646-14041dd5-ea4f-4c97-8965-673ef895e276.jpg)
![IMG_20230404_161516](https://user-images.githubusercontent.com/88026044/229769656-90503453-9c53-4d65-b8ad-7fe32ad3c03d.jpg)
![IMG_20230404_161549](https://user-images.githubusercontent.com/88026044/229769665-36bb899b-0e39-4250-a3a5-81f7771fa8c3.jpg)

**Comment by Prakash251299** [comment]
1.Just install python in your pc, pip will automatically be downloaded and you can easily use it.
2 If you have installed pip then just add its path to system environment variables i think it will work. 
First method will work definitely.
