### ISSUE TITLE
unable to verify the first certificate

### ISSUE THREAD

**Issue by Robot72** [Microsoft/vscode#17903]
- VSCode Version: Code 1.8.1 (ee428b0eead68bf0fb99ab5fdc4439be227b6281, 2016-12-19T14:49:23.350Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions:

|Extension|Author|Version|
|---|---|---|
|crane|HvyIndustries|0.2.0|
|format-indent|Kasik96|1.3.0|
|ftp-sync|lukasz-wronski|0.3.1|
|twig|whatwedo|1.0.1|

---

Steps to Reproduce:

1. I try intall a extension. I entered "ext vim" to extensions input. 
2. Next. I clicked "Intall" button.
3. VSC output message: "unable to verify the first certificate".

**Comment by joaomoreno** [comment]
Documentation on how to fix this comes with #27838
