### ISSUE TITLE
http.proxySupport setting lost after vscode restart

### ISSUE THREAD

**Issue by yuuuxt** [microsoft/vscode#179092]
Does this issue occur when all extensions are disabled?: (not checked yet)

- VS Code Version: 1.77.0
- OS Version: win 10 22H2

Steps to Reproduce:

1. Today I found this setting is not there so I added it, then it was synced:
![image](https://user-images.githubusercontent.com/3153534/229708563-b6040ea0-fa49-4007-9ce8-c036da8cfd86.png)
2. Then I installed an extension which required a restart:
![image](https://user-images.githubusercontent.com/3153534/229708946-49c11bad-8011-45bb-a9b4-c8d13de8ce66.png)
3. After restart the setting gets lost:
![image](https://user-images.githubusercontent.com/3153534/229709082-dc9247ee-1788-498d-b3e7-8ed3071957e9.png)

**Comment by sandy081** [comment]
Can you please disable all extensions and reproduce this?

**Comment by yuuuxt** [comment]
haven't met it since then.

**Comment by sandy081** [comment]
Ok. I am not sure if this can be diagnosed and fixed without information as you are not seeing this anymore. I am closing this for now. Please comment when you see it again and try to reproduce with extensions disabled. Thanks.
