### ISSUE TITLE
cannot read property 'api' of undefined

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#17902]
1. Add a watch expression foo()
2. Start a `node2` debug session, notice exception in console

![screen shot 2016-12-29 at 14 31 09](https://cloud.githubusercontent.com/assets/1926584/21544925/95e7d9ec-cdd3-11e6-82bb-01b6a72ef5bc.png)

**Comment by roblourens** [comment]
In this case the 'evaluate' request is sent before the launch completes. Notice that the error shows up before the launch command is printed to the console. Is that a case that a debug adapter should handle?

**Comment by isidorn** [comment]
What makes sense to me is that if the `initialize` responded with a success it means the debug adapter is `intialized` and is able to handle requests.
Since we do not specify in our protocol what requests have potential preconditions I think that the debug adapter should silently ignore this evalute request - with the asumption it properly sent the `initialize` one.

**Comment by roblourens** [comment]
That sounds like a good standard. In this case, the evaluate request actually comes before the initialize request. It doesn't make a difference to my code whether it's before or after though, so I'll add a check to make it safe.

**Comment by roblourens** [comment]
And it should call evaluate again at some point after we're attached, or the watch will say 'not connected to runtime' until a breakpoint is hit. The watch can be for some global.
