### ISSUE TITLE
Opening file in folder of active document

### ISSUE THREAD

**Issue by djmills64** [microsoft/vscode#179080]
Type: <b>Feature Request</b>

I've just changed computers. On my old one when I clicked open file it opened a dialog that started in the folder of the document I was in when I pressed open. But on the new machine it goes to my home folder every time. How can I change this? I can't find any suitable settings .

VS Code version: Code 1.77.0 (7f329fe6c66b0f86ae1574c2911b681ad5a45d63, 2023-03-29T10:05:35.165Z)
OS version: Linux x64 5.15.0-69-generic snap
Modes:
Sandboxed: No

**Comment by aeschli** [comment]
This seems to work for me, no setting needed. The default file folder path comes from the history. It should take the parent folder of currently active editor.

**Comment by alexr00** [comment]
It works for me to.
