### ISSUE TITLE
Allow to extend default signature help for the language

### ISSUE THREAD

**Issue by alenakhineika** [microsoft/vscode#179120]
The contextual signature help for `find` thinks that any `find` keyword is the `Array.find()` method. This is confusing for MongoDB users of the [MongoDB VSCode extension](https://marketplace.visualstudio.com/items?itemName=mongodb.mongodb-vscode), because MongoDB has its own usage and syntax the [find](https://www.mongodb.com/docs/manual/reference/method/db.collection.find/) method.

<img width="784" alt="Screenshot 2023-04-03 at 11 48 25" src="https://user-images.githubusercontent.com/16307679/229765116-019f3c19-0d66-41ba-9188-132f1e7a7ff4.png">

I tried to use the [Method Signatures](https://code.visualstudio.com/api/language-extensions/programmatic-language-features#help-with-function-and-method-signatures) API to extend the current behavior, but I did not find a way to support both the default JavaScript signatures and custom ones for the same language.

The `vscode.languages.registerSignatureHelpProvider` allows to add custom signatures to the JavaScript language, but the JavaScript signatures always have a priority and overwrite the custom options, they are not merged into a single list where users could see all of the possible options.

```typescript
this._context.subscriptions.push(
      vscode.languages.registerSignatureHelpProvider({ language: 'javascript' }, new MongodbHelpProvider(), {
        triggerCharacters: MongodbHelpProvider.triggerCharacters,
        retriggerCharacters: MongodbHelpProvider.retriggerCharacters
      })
    );
```

Another option I have tried is to overwrite the existing SignatureHelpProvide in the language server with `connection.onSignatureHelp`. But it also didn't work as I expected. We do something similar with `connection.onCompletion`, and in case we don't have anything to suggest we return an empty array. In this case, vscode shows the native JavaScript completion items. The `onSignatureHelp` method returns `SignatureHelp | undefined | null`. In case of the missing result, it does not return default JavaScript signatures.

```typescript
connection.onSignatureHelp((params: SignatureHelpParams) => {
  return {
    activeSignatureHelp: params.context?.activeSignatureHelp,
    signatures: [{
      label: 'Collection.find(query, projection, options) : Cursor',
      documentation: undefined,
      parameters: []
    }]
  };
});
```

Not sure what would be the right curse of action here, but either one of those would solve the issue for us:
- Smarter parsing of the text document content, to not assume that any `find` is the `Array.find()` method.
- Merge native signatures with custom signatures. If the `onSignatureHelp` method returns empty signatures `{ signatures: [] }` the empty array will be merged with default values for the current language and only default values will be returned.
- Provide the `vscode.languages.getSignatureHelp(document.uri)` API to access default values and merge them with custom values manually (similarly to Diagnostics API).

**Comment by jrieken** [comment]
We don't allow extensions to change the results of other extensions but you can write a typescript server plugin for this

**Comment by alenakhineika** [comment]
A TypeScript plugin should be added to a user's `tsconfig.json`, right? We want our playgrounds to work for all users out of the box, without requiring an additional setup on their side.

You are saying that you don't allow extensions to change the results of other extensions. But it looks like if we specify the custom results via `connection.onSignatureHelp()`, vscode has some kind of race condition and randomly shows either custom results or default JavaScript signatures.

[typeScriptService](https://github.com/mongodb-js/vscode/blob/VSCODE-403-extend-typescript-help-signatures/src/language/server.ts#L240-L252)

Sometimes the program enters the `connection.onSignatureHelp` method and triggers our completions, but sometimes it never gets there and probably the equivalent internal method of vscode JS extension is being called.

<img width="1109" alt="Screenshot 2023-04-07 at 17 42 59" src="https://user-images.githubusercontent.com/16307679/230637961-d6b5bf40-dfe0-4dec-b372-d8a38c458267.png">

<img width="1080" alt="Screenshot 2023-04-07 at 17 43 29" src="https://user-images.githubusercontent.com/16307679/230637964-723cfa80-76fd-4e92-b588-93f9ea722b72.png">

Is there a way to set a priority to custom results or disable the default JavaScript suggestions completely?
