### ISSUE TITLE
Clear terminar not works

### ISSUE THREAD

**Issue by MrCalamitus** [microsoft/vscode#179180]
Type: <b>Bug</b>

Hi in the last vesion I can´t clear my integrate terminal  with CMD+K 

VS Code version: Code 1.77.0 (Universal) (7f329fe6c66b0f86ae1574c2911b681ad5a45d63, 2023-03-29T09:57:11.797Z)
OS version: Darwin arm64 22.3.0
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|1, 2, 3|
|Memory (System)|16.00GB (0.32GB free)|
|Process Argv|--crash-reporter-id a88e7788-038b-436f-a0d4-eade2f76941f|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (58)</summary>

Extension|Author (truncated)|Version
---|---|---
atlascode|atl|3.0.3
mermaid-markdown-syntax-highlighting|bpr|1.5.1
vscode-eslint|dba|2.4.0
githistory|don|0.6.20
xml|Dot|2.5.1
gitlens|eam|2023.4.405
prettier-vscode|esb|9.10.4
vs-code-xml-format|fab|0.1.5
code-runner|for|0.12.0
shell-format|fox|7.2.5
copilot|Git|1.79.10634
go|gol|0.38.0
latex-workshop|Jam|9.8.2
plantuml|jeb|2.17.5
vscode-oracle-format|mp|0.1.5
vscode-docker|ms-|1.24.0
data-workspace-vscode|ms-|0.4.0
mssql|ms-|1.18.0
sql-bindings-vscode|ms-|0.3.0
sql-database-projects-vscode|ms-|0.21.0
isort|ms-|2022.8.0
python|ms-|2023.6.0
vscode-pylance|ms-|2023.3.40
jupyter|ms-|2023.3.1000892223
jupyter-keymap|ms-|1.1.0
jupyter-renderers|ms-|1.0.15
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-slideshow|ms-|0.1.5
remote-containers|ms-|0.288.0
vsliveshare|ms-|1.0.5834
sqltools|mtx|0.27.1
nativescript|Nat|0.12.3
nativescript-vue-extend|nuo|0.0.2
vetur|oct|0.37.3
nativescript-extend|Pau|2.12.0
java|red|1.16.0
vscode-yaml|red|1.12.2
LiveServer|rit|5.7.9
vscode-hexdump|sle|1.8.1
sonarlint-vscode|Son|3.16.0
stately-vscode|sta|1.13.0
python|tht|0.2.3
in-your-face-incredible|TTO|1.1.0
intellicode-api-usage-examples|Vis|0.2.7
vscodeintellicode|Vis|1.2.30
vscode-gradle|vsc|3.12.7
vscode-java-debug|vsc|0.49.1
vscode-java-dependency|vsc|0.21.2
vscode-java-pack|vsc|0.25.10
vscode-java-test|vsc|0.38.2
vscode-maven|vsc|0.41.0
vscode-icons|vsc|12.2.0
vscode-mermaid-preview|vst|1.6.3
volar|Vue|1.2.0
vscode-typescript-vue-plugin|Vue|1.2.0
plantuml|wel|2.17.6
change-case|wma|1.0.0
local-history|xyz|1.8.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
nodejswelcome1:30587005
282f8724:30602487
pyind779:30671433
f6dab269:30613381
pythonsymbol12:30671437
a9j8j154:30646983
6233i204:30672705
azdwalk:30687957
pythonms35:30701012

```

</details>

**Comment by meganrogge** [comment]
I believe this is already fixed, can you see if you can reproduce in the [Insiders build](https://code.visualstudio.com/insiders)?
/label info-needed

**Comment by MrCalamitus** [comment]
Hi, is perfect in the "insiders build" works. When will be available on production version? 

I add image to message appears when I type **cmd+K** . only show this message but not works 
<img width="387" alt="image" src="https://user-images.githubusercontent.com/7023270/229939297-d6943bbd-b59e-452c-aae0-2ad9008aff6c.png">
