### ISSUE TITLE
Clicking the arrows in diffs on deleted lines doesn't work

### ISSUE THREAD

**Issue by jespertheend** [microsoft/vscode#179114]
Does this issue occur when all extensions are disabled?: Yes

Version: 1.76.2
Commit: ee2b180d582a7f601fa6ecfdad8d9fd269ab1884
Date: 2023-03-14T17:57:21.103Z
Electron: 19.1.11
Chromium: 102.0.5005.196
Node.js: 16.14.2
V8: 10.2.154.26-electron.0
OS: Linux x64 5.19.0-38-generic
Sandboxed: No

Steps to Reproduce:

1. Open a git diff view and delete one of the lines.
2. Click the right pointing arrow in the diff view.

https://user-images.githubusercontent.com/2737650/229758804-10e2c3f0-c61e-429a-a9c7-67ca675b21f0.mp4

**Comment by alexdima** [comment]
I cannot reproduce this. Do you see any errors in developer tools? Does this reproduce with any file and with any change or is it specific to this particular file?

**Comment by jespertheend** [comment]
I can't reproduce it anymore either. I just updated to 1.77.0. Maybe it just happened to get fixed in that version? I can still reproduce #179115 though.

**Comment by jespertheend** [comment]
Hmm no I can still reproduce it in 1.77.0.

**Comment by jespertheend** [comment]
Found it! Seems like the issue only occurs after line 99

**Comment by jespertheend** [comment]
Hmm and another requirement is that the file has 1000 lines in total or more I think.

**Comment by jespertheend** [comment]
@alexdima I don't think the devtools console contains anything of interest:
>  WARN Via 'product.json#extensionEnabledApiProposals' extension 'ms-vscode.vscode-selfhost-test-provider' wants API proposal 'testContinuousRun' but that proposal DOES NOT EXIST. Likely, the proposal has been finalized (check 'vscode.d.ts') or was abandoned.
log.ts:431  WARN Via 'product.json#extensionEnabledApiProposals' extension 'ms-vscode.remote-repositories' wants API proposal 'contribEditorGutterMenu' but that proposal DOES NOT EXIST. Likely, the proposal has been finalized (check 'vscode.d.ts') or was abandoned.
log.ts:431  WARN Via 'product.json#extensionEnabledApiProposals' extension 'github.vscode-pull-request-github' wants API proposal 'contribEditorGutterMenu' but that proposal DOES NOT EXIST. Likely, the proposal has been finalized (check 'vscode.d.ts') or was abandoned.
log.ts:431  WARN Via 'product.json#extensionEnabledApiProposals' extension 'ms-toolsai.jupyter' wants API proposal 'notebookControllerKind' but that proposal DOES NOT EXIST. Likely, the proposal has been finalized (check 'vscode.d.ts') or was abandoned.
log.ts:441   ERR Extension 'github.copilot-nightly' appears in product.json but enables LESS API proposals than the extension wants.
package.json (LOSES): inlineCompletionsAdditions, interactive
product.json (WINS): inlineCompletionsAdditions
log.ts:421  INFO [perf] Render performance baseline is 62ms

I've found that the line 100 rule doesn't completely hold for me either, when make the right panel very big it becomes clickable again.

**Comment by jespertheend** [comment]
So far my hypothesis is that you need a long word wrapped line above the one you're trying to reset. But honestly I'm not sure anymore at this point.

https://user-images.githubusercontent.com/2737650/230144475-cb4fa9ea-5cce-44cc-ab88-1683bd12b592.mp4

**Comment by alexdima** [comment]
Hooray, this reproduces when using word wrapping! The root cause is that some properties on the mouse event are not converted from view coordinates to model coordinates.

This reproduces with the following word wrapped .txt file:

```
very long line very long line very long line very long line very long line very long line very long line very long line very long line very long line very long line very long line very long line very long line very long line very long line very long line very long line 

short line
short line
short line

short line
short line
short line
```

**Comment by ulugbekna** [comment]
Seems like I can still reproduce: 

https://user-images.githubusercontent.com/16353531/234816110-84ba7a89-27cb-4f23-9501-93d5a780e6c7.mov

**Comment by alexdima** [comment]
I ran git bisect and I had to skip a few commits due to build problems, but I believe this is caused by https://github.com/microsoft/vscode/pull/179130

The first bad commit could be any of:
5132503728f30e7248f987a892679e195a366aec
c420cbd6220f1eefd41a55b8203a593258d394d9
bdf6efedc54105a51f2cf9f012987e038625bfab

**Comment by roblourens** [comment]
So merging the PR will make the arrows work but will also bring back the issue of also setting breakpoints? That is unfortunate but I think I'd rather have the arrows working.

**Comment by alexdima** [comment]
:+1: I think it's better to go back to the state we had in 1.77 and the risk is minimal as it is a simple revert.
