### ISSUE TITLE
Add babelrc schema

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode#17910]
The json extension defines .bablerc as an extension for JSON file.

Since there also is a schema for .babelrc (schemastore/src/schemas/json/babelrc.json) the JSON extension should also define the schema for .bablerc files.

**Comment by aeschli** [comment]
Schema associations are typically done in the extension that 'owns' the file. E.g. the schema association for .eslintrc is done in the es lint extension.

Also for babel there exists https://marketplace.visualstudio.com/items?itemName=waderyan.babelrc.

I realize that it would be convenient to just have this built-in and we can make an exception for babelrc if you think we should. @egamma ?

**Comment by egamma** [comment]
>Schema associations are typically done in the extension that 'owns' the file. E.g. the schema association for .eslintrc is done in the es lint extension.

This makes good sense. 

@waderyan since the babel extension exists then we should add it to the extension tips when a user opens .bablerc file. Assigning the issue to @waderyan

**Comment by waderyan** [comment]
Done with PR https://github.com/Microsoft/vscode-distro/pull/69
