### ISSUE TITLE
not sure what happened?

### ISSUE THREAD

**Issue by sh471** [microsoft/vscode#179154]
ADD ISSUE DESCRIPTION HERE

Version: 1.78.0-insider
Commit: d317fbf2970b8f28bd7c59f545c59532cd5b293c
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36 Edg/111.0.1661.62
Embedder: codespaces

**Comment by lramos15** [comment]
Please open an issue with the description filled out and a more detailed title
