### ISSUE TITLE
Move cursor X amount of lines to the top or the bottom

### ISSUE THREAD

**Issue by nschurmann** [Microsoft/vscode#17913]
If we use the key cmd+up or cmd+down the cursor will go to the top or the bottom of the file, is there a way to move the cursor X amount of lines to the top or the bottom?, like go up 5 lines or 10 lines.

**Comment by Spown** [comment]
![](http://i207.photobucket.com/albums/bb299/topbird_photos/product%20pics/page_up_page_down_computer_cuffl-1.jpg)

**Comment by rebornix** [comment]
@nschurmann this amazing feature is already implemented by @sandy081 . It's `editorScroll` and you can see its definition from https://github.com/Microsoft/vscode/issues/9609

**Comment by nschurmann** [comment]
@rebornix great!, how do I actually use this amazing feature?
