### ISSUE TITLE
Cannot load vscode jupyter notebbok after recent update. 

### ISSUE THREAD

**Issue by Uddiptaatwork** [microsoft/vscode#179104]
Vscode updated to 1.77.0 and after the update:
- Adding the url to the jupyter kernel server list does not render the option to choose 'ipykernel'
- I use this feature constantly since I use GPU powered notebooks on a cluster

**Comment by DonJayamanne** [comment]
@Uddiptaatwork 
Thank you for filling this issue and sorry you are running into this

* does the url contain the Jupyter token 
* Is the Jupyter server setup without a password and also without a token
* When you reload vscode and wait for a minute or two, does the url appear (after waiting) in the list of the existing Jupiter servers, I think it will
