### ISSUE TITLE
Allow to create untitled document with specific language id

### ISSUE THREAD

**Issue by llali** [Microsoft/vscode#17917]
Is it possible to create an untitled document using 'workbench.action.files.newUntitledFile' command for specific language id? I'm using openTextDocument passing the vscode.Uri.parse('untitled:' + filePath) which filePath has the extension I want but I have to give it a full path which is different than the Untitled documents using the newUntitledFile command.

**Comment by bpasero** [comment]
No, currently not possible.

**Comment by bpasero** [comment]
@llali I am not sure I understand the use case actually, if I look at https://github.com/Microsoft/vscode-mssql/blob/dev/src/controllers/untitledSqlDocumentService.ts#L29 you seem to create a untitled resource and open it with a path. Why can you not set the extension of that path in a way that maps to the mode you want? Once you save the file and open it, the mode is also picked based on the extension, so I find it weird to set a different mode first for the untitled and then later you would get a different mode.

**Comment by llali** [comment]
@bpasero the path I created the untitled resource for has an extension which is .sql, so the mode changes to what I want and that's the scenario I needed. Now user can use a command "New SQL query" to create a new untitled document with SQL language mode. I couldn't do that with the untitled document command. Not sure if I did the right way but that was the solution I came up with. Please let me know if there's a better way for it.

**Comment by bpasero** [comment]
@llali no I think what you do is totally fine, the command you are pointing to is not even an official supported command. I am closing this since you seem to have found a working solution.

**Comment by llali** [comment]
@bpasero  my solution works but the result is different than VS code untitled documents, the first difference is that I have to specify a valid path but vs code untitled document doesn't have a path and user can specify the path to save it later. Also I have to do the same logic as vs code does to figure out the name of the file. it would be nice it there's an open API which both can use.

**Comment by bpasero** [comment]
Got it, valid request.

**Comment by bpasero** [comment]
After discussion in https://github.com/Microsoft/vscode/pull/18591 one idea is to:
* allow to open an untitled file without path by calling `openTextDocument(Uri.parse('untitled:'))`
* add a new optional options bag to the method that allows to set a language to use for the document to open (e.g. `openTextDocument(uri, options?: { language?: string })`)

**Comment by bpasero** [comment]
Continues in https://github.com/Microsoft/vscode/issues/12283
