### ISSUE TITLE
Co-pilot dissapears, not working after last update

### ISSUE THREAD

**Issue by Kunlesanni** [microsoft/vscode#179116]
Type: <b>Bug</b>

Co-pilot dissapears, not working after last update

VS Code version: Code 1.77.0 (7f329fe6c66b0f86ae1574c2911b681ad5a45d63, 2023-03-29T10:02:16.981Z)
OS version: Windows_NT x64 10.0.19045
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-1068NG7 CPU @ 2.30GHz (8 x 2304)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.81GB (10.33GB free)|
|Process Argv|--crash-reporter-id 31662cc4-175a-48ef-99be-eea7acafe9ea|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (17)</summary>

Extension|Author (truncated)|Version
---|---|---
azapi|aza|1.4.0
copilot|Git|1.79.10634
terraform|has|2.25.4
azure-dev|ms-|0.4.2
vscode-azureappservice|ms-|0.24.8
vscode-azurefunctions|ms-|1.10.4
vscode-azureresourcegroups|ms-|0.7.0
vscode-azurestaticwebapps|ms-|0.12.0
vscode-azurestorage|ms-|0.15.1
vscode-azureterraform|ms-|0.3.2
vscode-azurevirtualmachines|ms-|0.6.4
vscode-cosmosdb|ms-|0.19.3
azure-account|ms-|0.11.3
powershell|ms-|2023.3.3
vscode-node-azure-pack|ms-|1.1.1
terraform-doc-snippets|run|0.6.0
vscode-readme-pattern|tho|1.3.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vscaac:30438847
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
vscccc:30610679
nodejswelcome1cf:30587006
2e4cg342:30602488
pyind779:30671433
f6dab269:30613381
pythonsymbol12:30671437
a9j8j154:30646983
6233i204:30672705
vsccsb:30677849
pythonb192cf:30669361
functionswalk:30687959
pythonms35:30701012

```

</details>

**Comment by ozonep** [comment]
Confirming, same issue. Latest Insider's Build + latest Copilot Nightly.

**Comment by znagy82** [comment]
Same here.

Version: 1.78.0-insider
Commit: d317fbf2970b8f28bd7c59f545c59532cd5b293c
Date: 2023-04-04T09:42:03.345Z
Electron: 22.4.3
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Darwin arm64 22.1.0
Sandboxed: Yes

I've try to re authenticate Github copilot extension (first I think that cause the problem but it do nothing)
The output console is empty when Copilot is selected
![Screenshot 2023-04-04 at 16 20 00](https://user-images.githubusercontent.com/26006932/229823108-fef4e76e-a107-496a-9287-2b82436bea3c.png)

**Comment by eseglem** [comment]
Seems to be something **very** recent for me. On one computer it no longer works: 
```
Version: 1.78.0-insider (user setup)
Commit: d317fbf2970b8f28bd7c59f545c59532cd5b293c
Date: 2023-04-04T09:32:52.453Z
Electron: 22.4.3
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Windows_NT x64 10.0.22621
Sandboxed: Yes
```

But on the other it still works:
```
Version: 1.78.0-insider (user setup)
Commit: 2da5a0024fe2ca407f741f19340f1a10f4d692af
Date: 2023-04-03T05:21:34.222Z
Electron: 19.1.11
Chromium: 102.0.5005.196
Node.js: 16.14.2
V8: 10.2.154.26-electron.0
OS: Windows_NT x64 10.0.19045
Sandboxed: Yes
```

Spent a bunch of time fighting with settings as well as uninstalled / reinstalled copilot. No luck. 

Ctrl + Enter will still provide suggestions, but its not nearly as usable that way. 

Possibly related to #131940 ?

**Comment by CARL-Bouvet** [comment]
...and not findable in the extentions marketplace.

OS: Arch Linux
Kernel: x86_64 Linux 6.2.9-arch1-1
Shell: bash 5.1.16

$code --version:
1.77.0

**Comment by roblourens** [comment]
Fix on the way https://github.com/microsoft/vscode/pull/179171
