### ISSUE TITLE
Proposal: Add option to automatically start task runners' tasks

### ISSUE THREAD

**Issue by SetTrend** [Microsoft/vscode#1791]
In #1789 I suggested to add a `//# task` pragma comment to precede task runner tasks so the IDE will be able to recognize task runner tasks. This proposal here augments the mentioned proposal.
<br/>
Whenever a project is opened in VS Code, which is indicated by the following preconditions:
- a folder gets opened which contains one or more `.js` files
- any of those `.js` files contains one or more `//# task` pragma comments
- any of those `# task` pragma comments comes with an `autoStart: true` property set

... then the tasks marked with `autoStart: true` should automatically be executed.

Here's a screenshot depicting how the `autoStart: true` property is suggested to be applied:

![auto run 1](https://cloud.githubusercontent.com/assets/9283914/12098517/2161e340-b323-11e5-854d-c4357cef5c60.png)
<br/>
Depending on user/workspace settings, a confirmation dialog might be displayed before the tasks are automatically getting started:

![auto run 2](https://cloud.githubusercontent.com/assets/9283914/12098540/3f001566-b323-11e5-8381-5af2a884aacc.png)
<br/>
Browsing for the `//# task` pragma comment in all `.js` files within the current project root folder might become time consuming, given that there may be many large `.js` files in the project folder. So browsing should be performed asynchronously.
<br/>
#### The following behaviour is suggested:
1. Browsing `.js` files in the current project root folder for containing `//# task { autoStart: true [, ...]}` should be performed asynchronously after the folder has been opened in Code.
2. A user/workspace setting should be introduced to control whether the confirmation dialog box should be displayed and whether automatic execution of tasks should be performed anyway. The setting should come with the following enumeration:
   - `always`  // always run autostart tasks without showing the confirmation dialog box
   - `confirm`  // as soon as the first `//# task { autoStart: true [, ...] }` pragma comment is parsed by the browser after the folder has been opened in Code, a confirmation dialog is getting displayed to the user. Depending on user selection, any autostart task found in the folder will be getting executed - or none.
   - `never`  // never run autostart tasks
3. Autostart tasks should be run for each file containing one or more `//# task { autoStart: true [, ...] }` pragma comments separately. Tasks defined in different task runners won't depend on each other.
   <br/>
   _(The screenshot montage above mentions the text "Do you want to run the autostart tasks stored in gulpfile.js". This text is only a suggested visualization. Mentioning a file name in the text is actually not correct when there is more than one single task runner file about to be scanned and executed, which is the suggested behaviour.)_

**Comment by SetTrend** [comment]
Hi @alexr00: I don't get it ... Is it built into VS Code now? How would I use it? #17147 doesn't get clear about this.

Thanks for enlightening me 👍 😄

**Comment by alexr00** [comment]
Documentation for running tasks automatically is here: https://code.visualstudio.com/Docs/editor/tasks#_run-behavior
