### ISSUE TITLE
incorrect auto-formatting of parentheses after the arguments on a new line

### ISSUE THREAD

**Issue by IgorNovozhilov** [Microsoft/vscode#17914]
- VSCode Version:
![image](https://cloud.githubusercontent.com/assets/3082812/21553487/922daa34-ce19-11e6-9f00-356205b4afd9.png)

- OS Version: Linux Mint 18

Steps to Reproduce:

1. Write code:
```js
/* jshint esnext:true */

/**
 * @param {function} f1
 * @param {function} f2
 */
(function myFunc(a1, a2) {
   //...
})(
   function f1() {
      //...
   },
   function f2() {
      //...
   }
);

/**
 * @param {string} s1
 * @param {string} s2
 */
(function myFunc(a1, a2) {
   //...
})(
   'qwerty-qwerty-qwerty-qwerty-qwerty-qwerty',
   'qwerty-qwerty-qwerty-qwerty-qwerty-qwerty'
);
```

2. Press `Ctrl+Shift+I`
![image](https://cloud.githubusercontent.com/assets/3082812/21553540/e61478a8-ce19-11e6-9f92-2902d7a8f36e.png)

3. See that
![image](https://cloud.githubusercontent.com/assets/3082812/21553611/42538316-ce1a-11e6-8042-e35497bd5328.png)

**Comment by marcinkurek** [comment]
Very supportive of changing this - I also noticed this problem when writing JSX. Whenever i hit Alt+Shift+F to auto-format the whole document, this:

```
<foo
    bar="baz"
/>
```

gets changed to this:

```
<foo
    bar="baz"
    />
```

and my linter doesn't like it.

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript#13479
