### ISSUE TITLE
Terminal profile smoke test flake

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode#179181]
I've seen this three times this week on unrelated PRs:

https://dev.azure.com/vscode/VSCode/_build/results?buildId=90208&view=logs&j=15f6beb8-c39c-5fa4-f1fe-6e73c89d1002&s=96ac2280-8cb4-5df5-99de-dd2da759617d&t=dbbd50b8-230f-51ca-3be4-852e1fd323c1&l=169

**Comment by Tyriar** [comment]
Related to the js-debug extension not getting setup correctly

**Comment by eleanorjboyd** [comment]
@joyceerhl does this require verification if it is testing related?

**Comment by joyceerhl** [comment]
I haven't seen this failure lately so will mark as verified for now.
