### ISSUE TITLE
Enter stops working

### ISSUE THREAD

**Issue by Ahmedbenkhalifa** [microsoft/vscode#179110]
Key Enter randomly stop working.

 i try to reinstall VSCode but the problem still there

( Ctr+Enter and Shift+Enter work correctly)

**Comment by TylerLeonhardt** [comment]
In the editor? In the Command Palette? Where does ENTER stop working?

Also, do you use a screen reader?

**Comment by gjsjohnmurray** [comment]
Are you using the vscode-styled-components extension? If so, try disabling it.

**Comment by Ahmedbenkhalifa** [comment]
> Are you using the vscode-styled-components extension? If so, try disabling it.

yes, thank you very much that work again
