### ISSUE TITLE
Highlighting text in Find field can move cursor into document instead

### ISSUE THREAD

**Issue by erinknight242** [Microsoft/vscode#17916]
- VSCode Version: 1.8.1
- OS Version: Windows 10

I noticed that typing search terms sometimes appear in my editor instead of the "Find" window, depending on where I release the mouse button when selecting the text.

Steps to Reproduce:

1. Open the Find input box (ctrl-F)
2. Enter text in the Find input box
3. Click and drag to select the text, releasing the mouse button when hovering the open document tab bar
4. Selection in the Find box is cleared and cursor is placed in the document, so if you start typing, you are typing in the editor, not the find box

Screen cap:
1. Release mouse button hovering editor window: works
2. Release mouse button hovering outside of VSCode: works
3. Release mouse button hovering menu bar: works
4. **Release mouse button hovering the current document bar: loses the selection, drops cursor into document**

![vscode-find](https://cloud.githubusercontent.com/assets/3969554/21555610/2da4d82e-cddf-11e6-80a0-a81226971645.gif)

**Comment by Spown** [comment]
can't reproduce

![](https://dl.dropboxusercontent.com/u/105338698/ShareX/2016-12/2016-12-31_05-52-28.gif)

**Comment by rebornix** [comment]
@erinknight242 you may want to provide detailed reproduce steps or a gif :)

@Spown thanks for your verification !

**Comment by erinknight242** [comment]
This is reproducible on my end, if you have the following user setting:

`"workbench.editor.showTabs": false`

**Comment by alexandrudima** [comment]
Looks like the tab title area listens to mouse up and decides to focus the editor
