### ISSUE TITLE
Clicking the arrows in diff views on created lines adds a breakpoint

### ISSUE THREAD

**Issue by jespertheend** [microsoft/vscode#179115]
Does this issue occur when all extensions are disabled?: Yes

Version: 1.76.2
Commit: ee2b180d582a7f601fa6ecfdad8d9fd269ab1884
Date: 2023-03-14T17:57:21.103Z
Electron: 19.1.11
Chromium: 102.0.5005.196
Node.js: 16.14.2
V8: 10.2.154.26-electron.0
OS: Linux x64 5.19.0-38-generic
Sandboxed: No

Steps to Reproduce:

1. Open a git diff view and add a new line of code.
2. Click the right pointing arrow in the diff view.

Related/possibly the same root cause: #179114

https://user-images.githubusercontent.com/2737650/229759706-0dc971ea-56d1-4b4e-ab0c-60956fd15724.mp4

**Comment by maxmmyron** [comment]
Hey @hediet, I was wondering if this is still open for a PR? I've got a fix for this that may work, pending discussion.
