### ISSUE TITLE
JSDoc syntax highlight. Not supported 'Array of Arrays'

### ISSUE THREAD

**Issue by IgorNovozhilov** [Microsoft/vscode#17912]
- VSCode Version: 
![image](https://cloud.githubusercontent.com/assets/3082812/21553116/8514a250-ce17-11e6-9bd2-217cd2c7fd4c.png)

- OS Version: Linux Mint 18

Steps to Reproduce:

1. Write code:
```js
/* jshint esnext:true */

/**
 * @param {Array<string>} a1
 * @param {Array<Array<string>>} a2
 */
function myFunc(a1, a2) {

}
```
2. See that:
![image](https://cloud.githubusercontent.com/assets/3082812/21552987/80c6fef6-ce16-11e6-82f9-c59be5d9fc60.png)

3. Yes, it's correct
https://github.com/google/closure-compiler/wiki/Types-in-the-Closure-Type-System#types-in-javascript
![image](https://cloud.githubusercontent.com/assets/3082812/21553061/17c4a088-ce17-11e6-980e-0829946039bc.png)

**Comment by mjbvz** [comment]
Looks like a syntax highlighting issue on our side. Hovering over `a2`, I see it has the  correct `string[][]` type.

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript-TmLanguage#392
