### ISSUE TITLE
Allow inline providers to opt in to showing inline completions at the same time as completions

### ISSUE THREAD

**Issue by hediet** [microsoft/vscode#179134]

**Comment by roblourens** [comment]
I think this works but I'm a little confused about how this sample works, am I supposed to see something different in each group? I think I see the exact same result after each `----`

<img width="546" alt="image" src="https://user-images.githubusercontent.com/323878/234432940-08560b8a-2a20-4ceb-b23d-ed686a7321de.png">

**Comment by hediet** [comment]
You should see this:

![02ulP83JFC](https://user-images.githubusercontent.com/2931520/234526094-1659724e-8d76-4dde-be8a-79fd673d12c2.gif)

**Comment by roblourens** [comment]
That's exactly what I see today. Not sure what changed
