### ISSUE TITLE
Highlighted text from search needs extra click for text selection + bad default color

### ISSUE THREAD

**Issue by hansu** [microsoft/vscode#179238]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.77.0
- OS Version:  Windows 10

When searching across files (but also in an editor window), the hit which is selected in the sidebar is highlighted different than the other hits. When I want to select that text, I have to click on that text first and then I can select it. I perceive this as a bit annoying. If I remember correctly, that was different in earlier versions.
Also the default setting for  "editor.findMatchBackground" is a bit sub-optimal as the subsequent selection is not visible. I suggest a lower alpha belnding value.

![vscode-search-mark](https://user-images.githubusercontent.com/67957916/230020399-02197d1e-e984-4e1e-94e4-9ff4ce9306a2.gif)

**Comment by andreamah** [comment]
If you right-click on the currently-selected element, you should be able to copy/paste as if it's selected. What are you trying to do such that you need to re-select it?

**Comment by andreamah** [comment]
Ah, I see. It seems that's hard to partially highlight the current search match because you can hardly see which part is highlighted.
