### ISSUE TITLE
current terminal session not saved in the history

### ISSUE THREAD

**Issue by Abdullah-Shamhan** [microsoft/vscode#179284]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.77.1 universal 
- OS Version: Mac OS Ventura

Steps to Reproduce:

1.  type any command in the terminal such as "npm run script"
2.  close vscode and re-open it again
3. click arrow up to get latest command
4. no command history is found

the commands in the current session not saved when closing the terminal or vscode.

I tried both zsh and bash and still facing the same issue.
I tried writing the commend using the terminal window and it was saved and restored in vscode.

**Comment by meganrogge** [comment]
this works for me, can you add a gif?

**Comment by Abdullah-Shamhan** [comment]
> this works for me, can you add a gif?

Here is an example in vscode where i wrote a command then when i closed the terminal and open it again i did not find the command i wrote :
[https://ibb.co/HrJ1JvP](url)

and this is another example to show that the commands i write from terminal app are saved and restored in vscode
[https://ibb.co/LzhdzNq](url)

I aslo tried bash and i got the same issue

**Comment by jaakkom** [comment]
Same here! vscode 1.77.1

**Comment by petteri-hakala** [comment]
Exactly the same problem here too. v1.77.1

**Comment by jdgalani** [comment]
1.77.3 still i can reproduce the issue

**Comment by petteri-hakala** [comment]
> 1.77.3 still i can reproduce the issue

Same problem
