### ISSUE TITLE
Texts look blurry with Nvidia proprietary GL library

### ISSUE THREAD

**Issue by Frederick888** [Microsoft/vscode#17926]
- VSCode Version: 1.8.1
- OS Version: ArchLinux (KDE 5.8.5)
- GPU: Nvidia GTX980M

Driver and GL:

1. `nvidia` + `nvidia-libgl`
![vscode-nvidia-libgl](https://cloud.githubusercontent.com/assets/4507647/21559905/9889058c-cea9-11e6-98ab-2c2fab47a15b.png)

2. `nvidia` + `nvidia-libgl` with `--disable-gpu` switch
![vscode-disable-gpu](https://cloud.githubusercontent.com/assets/4507647/21559910/ac0e100c-cea9-11e6-8a8e-08a131fcf922.png)

3. `nvidia` + `mesa-libgl`
![vscode-mesa-libgl](https://cloud.githubusercontent.com/assets/4507647/21559912/b88a7640-cea9-11e6-9ac8-2c0750861ef1.png)

I'm not sure whether this is a driver issue or not. All other applications do not have this issue including Chrome.

**Comment by Frederick888** [comment]
![screenshot_20161230_234341](https://cloud.githubusercontent.com/assets/4507647/21565431/d2475ac0-ceeb-11e6-864e-3a50c410728a.png)

It looks better after I've changed the *System Settings -> Display and Monitor -> Compositor -> Rendering backend* from `OpenGL 2.0` to `OpenGL 3.1`. It's much better than the first snapshot in the thread but yet not ideal.

Chrome is using the latest APIs (from chrome://gpu/):
```
GL_VENDOR	NVIDIA Corporation
GL_RENDERER	GeForce GTX 980M/PCIe/SSE2
GL_VERSION	4.5.0 NVIDIA 375.26
```
`glxinfo` output:
```
$ glxinfo | grep "OpenGL"
OpenGL vendor string: NVIDIA Corporation
OpenGL renderer string: GeForce GTX 980M/PCIe/SSE2
OpenGL core profile version string: 4.5.0 NVIDIA 375.26
OpenGL core profile shading language version string: 4.50 NVIDIA
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile
OpenGL core profile extensions:
OpenGL version string: 4.5.0 NVIDIA 375.26
OpenGL shading language version string: 4.50 NVIDIA
```

**Comment by bpasero** [comment]
VS Code is currently using Electron with Chrome 53. Until we update to a newer Electron version, we are using whatever Chrome 53 decides to use here.

**Comment by Frederick888** [comment]
@bpasero I downloaded a Chrome 53 and it was using `GL 4.5.0` as well. I remember that Chrome will try using the highest version possible, and this is why they provided a `--create-default-gl-context` switch.

But it seems that VSC is using the same version that I chose for KDE. Is it a feature of Electron?

**Comment by bpasero** [comment]
Might be, not sure. Best to ask them if possible (https://github.com/atom/electron)

**Comment by Frederick888** [comment]
https://github.com/electron/electron/issues/8323 @bpasero

**Comment by Frederick888** [comment]
Fixed by adding argument `--force-device-scale-factor=1`
