### ISSUE TITLE
screen view error

### ISSUE THREAD

**Issue by Abhimishra2424** [microsoft/vscode#179226]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 
- OS Version: 

Steps to Reproduce:

1. 
2.

**Comment by Abhimishra2424** [comment]
#/
![Screenshot from 2023-03-30 10-34-19](https://user-images.githubusercontent.com/47156246/229978423-161c837c-442d-4953-a180-ef424e740985.png)
look this

**Comment by Kathund** [comment]
@Abhimishra2424 Please explain the problem, the steps to reproduce and what version your on

**Comment by Abhimishra2424** [comment]
> @Abhimishra2424 Please explain the problem, the steps to reproduce and what version your on

version 1.77.0
This problem comes in when I open vs code i got this screen view error if i close vs code then it is fixed but aft some time i got same think in vs code application

**Comment by Abhimishra2424** [comment]
![Screenshot from 2023-04-05 11-46-45](https://user-images.githubusercontent.com/47156246/229996838-ff28c0af-e787-4bdf-abcb-8080d966bbd8.png)

**Comment by deepak1556** [comment]
Please disable hw acceleration following the steps at https://code.visualstudio.com/updates/v1_40#_disable-gpu-acceleration
