### ISSUE TITLE
Undefined Symbol Error while trying to launch GUI Apps from a Snap Installed VSCode Built-in Terminal

### ISSUE THREAD

**Issue by AmeyaVS** [microsoft/vscode#179274]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.77.0
- OS Version: Fedora 37

Steps to Reproduce:

1. Open VSCode Built-in Terminal
2. Try and Launch GIMP from the command line.

```sh
(gimp:83023): Gtk-WARNING **: 21:08:31.563: Unable to locate theme engine in module_path: "pixmap",

(gimp:83023): Gtk-WARNING **: 21:08:31.564: Unable to locate theme engine in module_path: "pixmap",

(gimp:83023): Gtk-WARNING **: 21:08:31.564: Unable to locate theme engine in module_path: "adwaita",
gimp: symbol lookup error: /snap/core20/current/lib/x86_64-linux-gnu/libpthread.so.0: undefined symbol: __libc_pthread_init, version GLIBC_PRIVATE
```
Similar issue reported on Stackoverflow and AskUbuntu:

1. https://stackoverflow.com/questions/75921414/java-symbol-lookup-error-snap-core20-current-lib-x86-64-linux-gnu-libpthread
2. https://askubuntu.com/questions/1462295/ubuntu-22-04-both-eye-of-gnome-and-gimp-failing-with-undefined-symbol-error

I tried checking LD_LIBRARY_PATH and that does not seems to fix this.

**Comment by deepak1556** [comment]
Merging to https://github.com/microsoft/vscode/issues/179086

**Comment by Apisteftos** [comment]
Try to install the gtk4-1 and set the path

**Comment by AmeyaVS** [comment]
This seems to be an issue within the VSCode. As I do have the GTK-4.0 libraries installed.
I think it is better to say that GTK_* environment should not be updated within the VSCode terminal.
Overriding the environment variable within the terminal seems to be a workaround.
I would be better if such environment configurations can be notified and probably a setting to disable such configuration for the VSCode built-in terminal.
For now, this solution is not scalable.

**Comment by AmeyaVS** [comment]
I can workaround this issue by unsetting the `GTK_PATH` environment variable for now.

**Comment by bonsairobo** [comment]
I can reproduce this issue.

@deepak1556 Can you explain why this was merged with #179086 which has a different failure mode?

**Comment by bonsairobo** [comment]
Some info I have from my own debugging:

```
Version: 1.77.1
Commit: b7886d7461186a5eac768481578c1d7ca80e2d21
Date: 2023-04-04T23:20:37.202Z
Electron: 19.1.11
Chromium: 102.0.5005.196
Node.js: 16.14.2
V8: 10.2.154.26-electron.0
OS: Linux x64 5.19.0-38-generic snap
Sandboxed: Yes
```

A) I've been running a binary that opens a file dialog from within a snap-installed VSCode, which fails with:

```
file_dialog: symbol lookup error: /snap/core20/current/lib/x86_64-linux-gnu/libpthread.so.0: undefined symbol: __libc_pthread_init, version GLIBC_PRIVATE
```

B) However when I first run `unset GTK_PATH` as suggested by @AmeyaVS the crash goes away.

I've tried running with `LD_DEBUG=libs` and noticed a difference between A and B.

A)

```
     63417:     find library=libpthread.so.0 [0]; searching
     63417:      search path=/snap/code/124/usr/lib/x86_64-linux-gnu/gtk-3.0/modules/../..:/snap/core20/current/lib/x86_64-linux-gnu            (RPATH from file /snap/code/124/usr/lib/x86_64-linux-gnu/gtk-3.0/modules/libcanberra-gtk-module.so)
     63417:       trying file=/snap/code/124/usr/lib/x86_64-linux-gnu/gtk-3.0/modules/../../libpthread.so.0
     63417:       trying file=/snap/core20/current/lib/x86_64-linux-gnu/libpthread.so.0

...

     63417:     calling init: /snap/core20/current/lib/x86_64-linux-gnu/libpthread.so.0
```

B) 

```
     78220:     find library=libpthread.so.0 [0]; searching
     78220:      search path=/home/duncan/.rustup/toolchains/1.65.0-x86_64-unknown-linux-gnu/lib                (LD_LIBRARY_PATH)
     78220:       trying file=/home/duncan/.rustup/toolchains/1.65.0-x86_64-unknown-linux-gnu/lib/libpthread.so.0
     78220:      search path=/home/duncan/.rustup/toolchains/1.65.0-x86_64-unknown-linux-gnu/bin/../lib         (RUNPATH from file /home/duncan/.rustup/toolchains/1.65.0-x86_64-unknown-linux-gnu/bin/cargo)
     78220:       trying file=/home/duncan/.rustup/toolchains/1.65.0-x86_64-unknown-linux-gnu/bin/../lib/libpthread.so.0
     78220:      search cache=/etc/ld.so.cache
     78220:       trying file=/lib/x86_64-linux-gnu/libpthread.so.0

...

     78220:     calling init: /lib/x86_64-linux-gnu/libpthread.so.0
```

**Comment by deepak1556** [comment]
@bonsairobo the root issue is same for both, the env variables we set for our snap package https://github.com/microsoft/vscode/blob/main/resources/linux/snap/electron-launch are inherited by the terminal process and causes undesired behavior for external applications launched from the terminal.

**Comment by chatziko** [comment]
I have the same issue, the `unset GTK_PATH` workaround works for me, and can be automated by adding the following to `settings.json`:

```
    "terminal.integrated.env.linux": {
        "GTK_PATH": null
    },
```
