### ISSUE TITLE
Auth loop when connecting to tunnel with vscode.dev

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#179245]
1. Run `code tunnel`
2. Follow the auth steps
3. Open the vscode.dev link

🐛 There's an auth loop:

https://user-images.githubusercontent.com/22350/230055098-94df033e-77f0-4dd1-bb80-90d4d0613ce5.mov

**Comment by connor4312** [comment]
Duplicates https://github.com/microsoft/vscode-remote-release/issues/8323
