### ISSUE TITLE
when i run C or C++ files it is raising error

### ISSUE THREAD

**Issue by Rithesh-2005** [microsoft/vscode#179231]
Type: <b>Performance Issue</b>

It's been a month since this issue has occured.
It araises when i run C or C++ files.

VS Code version: Code 1.77.0 (7f329fe6c66b0f86ae1574c2911b681ad5a45d63, 2023-03-29T10:02:16.981Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz (8 x 2419)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|11.80GB (3.63GB free)|
|Process Argv|--crash-reporter-id 541b9c1a-3cb4-4050-bcc0-eaaed9b0baa6|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	    93	 15256	code main
    0	    79	  7592	fileWatcher [1]
    0	    98	 17384	shared-process
    0	    79	   760	     ptyHost
    0	    64	 18416	       C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe
    0	     6	 24220	       console-window-host (Windows internal process)
    0	    26	 19080	   crashpad-handler
    0	   206	 21992	extensionHost [1]
    0	   478	 23380	     electron-nodejs ("C:\Users\cheem\AppData\Local\Programs\Microsoft VS Code\Code.exe" --ms-enable-electron-run-as-node c:\Users\cheem\.vscode\extensions\ms-python.vscode-pylance-2023.3.40\dist\server.bundle.js --cancellationReceive=file:0352570c7d2f1ac6b031484979d798c9dbd5f585ba --node-ipc --clientProcessId=21992)
    0	    38	 25676	     c:\Users\cheem\AppData\Local\Microsoft\WindowsApps\python3.10.exe c:\Users\cheem\.vscode\extensions\ms-python.isort-2022.8.0\bundled\tool\server.py
    0	    10	 23100	       console-window-host (Windows internal process)
    0	    18	 33176	       c:\Users\cheem\AppData\Local\Microsoft\WindowsApps\python3.10.exe c:\Users\cheem\.vscode\extensions\ms-python.isort-2022.8.0\bundled\tool\runner.py
    0	   104	 31752	     electron-nodejs ("C:\Users\cheem\AppData\Local\Programs\Microsoft VS Code\Code.exe" --ms-enable-electron-run-as-node c:\Users\cheem\.vscode\extensions\visualstudioexptteam.intellicode-api-usage-examples-0.2.7\dist\server\server.js --node-ipc --clientProcessId=21992)
    0	   165	 29632	window [1] (python.py - Programming (Workspace) - Visual Studio Code)
    0	    39	 31116	   utility-network-service
    0	    85	 31952	window [2] (Issue Reporter)
    0	   273	 32028	   gpu-process
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (python.py - Programming (Workspace) - Visual Studio Code)
|    Folder (python): 19 files
|      File types: py(8) txt(3) dest(1) file1(1) file2(1) file3(1) file4(1)
|                  rihtu(1) rithu(1) source(1)
|      Conf files:;
```

</details>
<details><summary>Extensions (27)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-django|bat|1.10.0
python-environment-manager|don|1.0.4
python-extension-pack|don|1.7.0
code-runner|for|0.12.0
copilot|Git|1.79.10634
vsc-python-indent|Kev|1.18.0
vscode-docker|ms-|1.24.0
isort|ms-|2022.8.0
python|ms-|2023.6.0
vscode-pylance|ms-|2023.3.40
jupyter|ms-|2023.3.1000892223
jupyter-keymap|ms-|1.1.0
jupyter-renderers|ms-|1.0.15
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-slideshow|ms-|0.1.5
cpptools|ms-|1.14.5
autodocstring|njp|0.6.1
java|red|1.16.0
vscode-lldb|vad|1.9.0
intellicode-api-usage-examples|Vis|0.2.7
vscodeintellicode|Vis|1.2.30
vscode-java-debug|vsc|0.49.1
vscode-java-dependency|vsc|0.21.2
vscode-java-pack|vsc|0.25.10
vscode-java-test|vsc|0.38.2
vscode-maven|vsc|0.41.0
jinja|who|0.0.8

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
nodejswelcome1:30587005
2e4cg342:30602488
pyind779:30671433
f6dab269:30613381
pythonsymbol12:30671437
vsctsb:30705553
functionswalk:30687959
pythonms35:30701012

```

</details>

**Comment by roblourens** [comment]
You can file this with much more detail on the C++ extension repo
