### ISSUE TITLE
TS Object literal scoped incorrectly

### ISSUE THREAD

**Issue by smlombardi** [Microsoft/vscode#17921]
- VSCode Version: Code - Insiders 1.9.0-insider (9486bf472c5c558e4f1793e0e746da88d071b1cc, 2016-12-29T07:05:11.443Z)
- OS Version: Darwin x64 16.3.0
- Extensions:

|Extension|Author|Version|
|---|---|---|
|material-icon-theme|PKief|1.1.5|
|code-settings-sync|Shan|2.4.0|
|sort-lines|Tyriar|1.1.0|
|html-css-class-completion|Zignd|1.0.3|
|Bookmarks|alefragnani|0.10.1|
|project-manager|alefragnani|0.12.2|
|one-monokai|azemoh|0.2.4|
|vscode-icontheme-nomo-dark|be5invis|1.2.1|
|vscode-eslint|dbaeumer|1.2.2|
|githistory|donjayamanne|0.1.4|
|tslint|eg2|0.7.1|
|vscode-great-icons|emmanuelbeziat|1.1.35|
|Angular2|johnpapa|1.0.2|
|theme-karyfoundation-themes|karyfoundation|10.2.0|
|ftp-sync|lukasz-wronski|0.3.2|
|HTMLHint|mkaufman|0.3.3|
|vscode-csscomb|mrmlnc|4.0.0|
|vscode-postcss-sorting|mrmlnc|2.1.0|
|vscode-stylefmt|mrmlnc|2.2.0|
|Theme-1337|ms-vscode|0.1.2|
|angular2-inline|natewallace|0.0.16|
|nonbreakingspace|smlombardi|0.0.1|
|vscode-icons|robertohuertasm|4.3.0|
|stylelint|shinnn|0.21.1|
|darcula-extended|smlombardi|1.0.0|
|theme-tesla|smlombardi|5.3.10|
|bootstrap-3-snippets|wcwhitehead|0.0.9|
|change-case|wmaurer|1.0.0|

---

Steps to Reproduce:

1. see attached:
<img width="429" alt="screen shot 2016-12-29 at 9 36 23 pm" src="https://cloud.githubusercontent.com/assets/835148/21558866/209bd94a-ce0f-11e6-9fd7-6bd77ad0afc0.png">

2.  both of the items pointed out by red arrows should be scoped the same, except the ones that are purple are correctly scoped as 
`token meta ts decorator objectliteral object member object-literal key` but for some reason `template:` and the entire contents of `template` key are scoped as:
`token meta ts decorator objectliteral object member`

3. therefore, it's impossible to correctly color the key name in a theme

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript-TmLanguage#395
