### ISSUE TITLE
Crash in macOS smoke tests

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#179264]
Found this crash dump in a macOS smoke test run from https://dev.azure.com/monacotools/Monaco/_build/results?buildId=208985&view=logs&j=260a512b-e5ca-5cf1-3f8e-20c0fa41efc9&t=82df682a-a732-590f-d041-2bbd067871c9&l=109

[3cca2b50-6aa7-431c-a125-0745f5a890aa.dmp.zip](https://github.com/microsoft/vscode/files/11159285/3cca2b50-6aa7-431c-a125-0745f5a890aa.dmp.zip)

**Comment by deepak1556** [comment]
Merging to https://github.com/microsoft/vscode-internalbacklog/issues/3552
