### ISSUE TITLE
font size is  too small

### ISSUE THREAD

**Issue by loulanlvzhou** [Microsoft/vscode#17924]
- VSCode Version:1.8.1
- OS Version:win 7

Steps to Reproduce:

1. see red rectangle to attached:
![fontsize](https://cloud.githubusercontent.com/assets/24835538/21559167/222b29f0-ce82-11e6-86b2-241a55a7c715.png)

2. my eyesight is not so good. i hope i can reset font size of vscode resx manager view.

**Comment by Frederick888** [comment]
Try zooming in?

**Comment by saravanaj** [comment]
More specifically, you can set the `"window.zoomLevel": {int}` property in your user settings.
