### ISSUE TITLE
Windows insert emoji will erase 2 characters in front of cursor and insert the selected emoji twice

### ISSUE THREAD

**Issue by wilson-shen** [microsoft/vscode#179222]
Type: <b>Bug</b>

1. type any sting, and move the cursor front
2. `win + .`
3. Select any emoji

Before: "foo ba|r baz"

After: "foo 😲😲|r baz"

Expected: "foo ba😲|r baz"

VS Code version: Code 1.77.0 (7f329fe6c66b0f86ae1574c2911b681ad5a45d63, 2023-03-29T10:02:16.981Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10870H CPU @ 2.20GHz (16 x 2208)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|39.82GB (22.53GB free)|
|Process Argv|--crash-reporter-id 38d2dd25-1ad5-47bb-ba34-d820e2246445|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (37)</summary>

Extension|Author (truncated)|Version
---|---|---
overtype|ada|0.2.0
laravel-model-snippets|ahi|2.0.0
laravel-extra-intellisense|ami|0.6.2
svelte-intellisense|ard|0.7.1
laravel-blade-spacer|aus|2.1.3
vscode-intelephense-client|bme|1.9.5
vscode-tailwindcss|bra|0.9.11
laravel-goto-view|cod|1.3.8
dart-code|Dar|3.62.0
flutter|Dar|3.62.0
gitlens|eam|13.4.0
EditorConfig|Edi|0.16.4
prettier-vscode|esb|9.10.4
auto-close-tag|for|0.5.14
auto-rename-tag|for|0.1.10
vscode-pull-request-github|Git|0.63.2023040409
todo-tree|Gru|0.0.224
prettier-sql-vscode|inf|1.6.0
php-cs-fixer|jun|0.3.9
template-string-converter|meg|0.6.0
php-namespace-resolver|Meh|1.1.9
git-graph|mhu|1.30.0
dotenv|mik|1.0.1
phpstorm-parameter-hints-in-vscode|MrC|1.1.0
test-adapter-converter|ms-|0.1.7
laravel-goto-components|nao|1.2.0
awesome-flutter-snippets|Nas|4.0.1
php-docblocker|nei|2.7.0
laravel-blade|one|1.34.0
laravel-extension-pack|one|1.1.0
laravel5-snippets|one|1.17.0
material-icon-theme|PKi|4.25.0
vscode-phpunit|rec|3.0.31
flutter-riverpod-snippets|rob|1.2.2
laravel-artisan|rya|0.0.28
vscode-blade-formatter|shu|0.20.14
svelte-vscode|sve|107.3.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
vsccc:30610678
nodejswelcome1:30587005
3biah626:30602489
pyind779:30671433
89544117:30613380
pythonsymbol12:30671437
a9j8j154:30646983
vsctsb:30705553
pythonb192cf:30669361
defaultazurewalk:30687958
pythonms35:30701012
pythonclientmv:30705673

```

</details>

**Comment by Kathund** [comment]
@wilson-shen can you please provide a video of you doing this because i cant seam to reproduce it. Can you also confirm if this is extention related or not by running `code --disable-extensions`

**Comment by wilson-shen** [comment]
After disabled all extensions, the issue no longer happen. I will report the issue to respective extension. Sorry for wrong issue opened. Thanks for your time to investigate.
