### ISSUE TITLE
[html] Auto-complete entity names (&lt, &gt ...)

### ISSUE THREAD

**Issue by PassTheMayo** [Microsoft/vscode#17928]
How about an ability to auto-complete [entities in HTML code](http://www.w3schools.com/html/html_entities.asp)? For example, if I were to write & in HTML code, it would be neat to see a drop-down with all the entity names and examples, maybe names on the left and the symbol to the right?

**Comment by aeschli** [comment]
Good idea. If you're interested in giving tis a try, pull requests at https://github.com/Microsoft/vscode-html-languageservice are welcome.

**Comment by JacobGunther12** [comment]
@aeschli I would do a pull request, but I think that requires for me to edit the code and create forks and stuff, but I'm not that good at GitHub, yet.
