### ISSUE TITLE
Submenu flyouts render under menu scrollbar and have unlimited width

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode#179206]
1. Open a file with an exceptionally long filename in VS Code
2. Open a new window
3. File > Open Recent
4. :bug: the Open Recent submenu width accommodates the entire filename, also the Open Recent submenu appears to render under the scrollbar for the File menu. If I happen to have VS Code resized to be smaller than the submenu, then the Open Recent submenu takes over the whole window and there's no way to dismiss it

<img width="774" alt="image" src="https://user-images.githubusercontent.com/30305945/229931523-c90e4b96-cdb0-46b1-ac28-39f18aba73c7.png">

Should we set a max width for the submenu flyout?

**Comment by NriotHrreion** [comment]
dup with #174350
