### ISSUE TITLE
Force Touch Trackpad > Peek Definition (or other)

### ISSUE THREAD

**Issue by JacobZwang** [microsoft/vscode#179279]
On all modern MacBooks you can push hard on the trackpad to force click. VSCode seems to do nothing with this functionality right now. Having force click activate Peek Definition seems intuitive to me but even better would be allowing users to customize the behavior of force clicking as a keyboard shortcut.

https://support.apple.com/en-us/HT204352
https://developer.apple.com/documentation/appkit/nspressurebehavior
https://developer.apple.com/documentation/appkit/nshapticfeedbackperformer

Unfortunately it doesn't look like Electron has native support for this :(
https://github.com/electron/electron/issues/7994

**Comment by roblourens** [comment]
I would like to use it, but it looks like it's not going to be supported by Chrome/Electron
