### ISSUE TITLE
incorrect accessible buffer contribution is accessed when there are several 

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#179273]
https://user-images.githubusercontent.com/29464607/230130129-b7669a63-a7d4-46e1-b632-04697a158b12.mov

**Comment by meganrogge** [comment]
This is because the active instance isn't updated when the editor is clicked

**Comment by joyceerhl** [comment]
Now I get an empty picker when there are multiple terminals, regardless of whether I'm in the accessible buffer: 
![image](https://user-images.githubusercontent.com/30305945/235006870-6d586726-b691-4e2d-903c-bdc293077129.png)

**Comment by meganrogge** [comment]
when you are not in the accessible buffer, `open detected link` will be invoked. that could be what you're seeing

**Comment by meganrogge** [comment]
@joyceerhl could you pls provide a gif with screen cast mode on? I'm trying to reproduce in the meantime

**Comment by meganrogge** [comment]
https://user-images.githubusercontent.com/29464607/235008293-2a2f4efd-7c04-4b94-a133-48403819b5de.mov

**Comment by joyceerhl** [comment]
https://user-images.githubusercontent.com/30305945/235012500-e67f4e4a-2870-440d-b545-1acb6a5a26c5.mp4

**Comment by joyceerhl** [comment]
Oh, it's an off-by-one in the accessible buffer I think. If I run some other command, then that command shows up (but not the `ls)

**Comment by meganrogge** [comment]
yes, will investigate that in https://github.com/microsoft/vscode/issues/178173. thanks
