### ISSUE TITLE
VSCode installation time has increased

### ISSUE THREAD

**Issue by sbaid** [Microsoft/vscode#17922]
- VSCode Version: 1.8.1
- OS Version: windows 10 14383

Steps to Reproduce:

1. I have been using the VScode on xlab VM for reading code and quick edits. Since xlab VM are often created - I install vscode as well often. Have been using it over couple of months and more. I don't have concrete numbers but felt that the installation time has increased over period of time. Anything to keep it slim with optional features & lowering the installation time - will help.

Xlab VM config - large, 4 core, 7 GB

**Comment by dbaeumer** [comment]
@jrieken because you are looking into performance right now

**Comment by bpasero** [comment]
@sbaid you are talking about the time it takes for the installer to run through? or the startup of code?

**Comment by bpasero** [comment]
A number of days has past without answer on the questions asked. I am thereby going to close this issue to clean up our backlog of issues. Once you can answer on the questions, the issue can be reopened again. Thanks for understanding this process!

**Comment by sbaid** [comment]
@bpasero sorry I missed the notification. saw the closed notification now. yes I am active user of vscode & was talking about the vscode install time.

**Comment by sbaid** [comment]
@bpasero  thanks

**Comment by joaomoreno** [comment]
I suggest to just use the zip archive releases, if you're trying to optimize the time it takes from download to use.
