### ISSUE TITLE
Intellisense does not work for properties that are added after declaration

### ISSUE THREAD

**Issue by saravanaj** [Microsoft/vscode#17923]
- VSCode Version: 1.8.1
- OS Version: Windows 8.1 Home

I am running code with `--disable-extensions` flag.

Steps to Reproduce:

1. Write some code where properties are added to objects added after declaration. Intellisense does not work:
![actual](https://cloud.githubusercontent.com/assets/1573565/21559060/019b5f46-ce6b-11e6-8417-5766805f5c33.png)

2. If the properties are defined during declaration it works:
![expected](https://cloud.githubusercontent.com/assets/1573565/21559067/315cbfc2-ce6b-11e6-8d7d-8ada87b7999a.png)

**Comment by Spown** [comment]
I think it is a proper behavior. If you had something like this:
```js
var obj = {};
if (someGlobalVariable) {
  obj.test = {
    one: 1
  }
}

obj
```
then Intellisense wouldn't really know whether the obj variable always has this ``test`` property. Intellisense doesn't evaluate your code - it only makes assumptions where it can. Thats why you still have  word suggestions:
![](https://dl.dropboxusercontent.com/u/105338698/ShareX/2016-12/firefox_2016-12-31_05-12-58.png)
as a compromise.

**Comment by saravanaj** [comment]
@Spown  I agree it is impossible to autocomplete properties that are added conditionally, but the example I posted does not add any properties conditionally. The same code gives intellisense in Visual Studio.

The major use case where this type of intellisense is needed is when I namespace methods and properties like below:

**In VS Code:**
![2016-12-31_115010](https://cloud.githubusercontent.com/assets/1573565/21576316/ff2fdfee-cf4f-11e6-9fbe-b1b29c1ca9fd.png)

**In Visual Studio:** (which handles this perfectly)
![vs](https://cloud.githubusercontent.com/assets/1573565/21576317/1a1cc236-cf50-11e6-906e-61a6b598c2e3.png)

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript#13271
