### ISSUE TITLE
[typescript] syntax highlighting:  wrong precedence rule

### ISSUE THREAD

**Issue by npenin** [Microsoft/vscode#17929]
- VSCode Version: 1.9.0-insider
- OS Version: Windows 10

Steps to Reproduce:

1. write a code like this:
```ts
 gulp.add('watch-' + (asset.name || asset.route), function ()
        {
            gulp.watch('./modules/*' + asset.moduleRelativePath, ['build-' + (asset.name || asset.route)]);
        });
```
2. See the wrong colorization happening:
![image](https://cloud.githubusercontent.com/assets/1405160/21561832/78c11708-ce72-11e6-938c-ce774a660412.png)

**Comment by aeschli** [comment]
This issue was moved to Microsoft/TypeScript-TmLanguage#394
