### ISSUE TITLE
gdb “-enable-pretty-printing” lose efficacy 

### ISSUE THREAD

**Issue by Kiris-z** [microsoft/vscode#179260]
Type: <b>Bug</b>

When C++ is debugging, only the address can be seen in the monitoring STL container, but the value cannot be seen

VS Code version: Code 1.77.0 (7f329fe6c66b0f86ae1574c2911b681ad5a45d63, 2023-03-29T10:02:16.981Z)
OS version: Windows_NT x64 10.0.22000
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-10300H CPU @ 2.50GHz (8 x 2496)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.87GB (9.28GB free)|
|Process Argv|D:\\ACM.code-workspace --crash-reporter-id b67f8543-af6c-4f22-a368-35dc60b24d67|
|Screen Reader|no|
|VM|40%|
</details><details><summary>Extensions (58)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|3.0.2
y86-vscode|abh|0.0.3
codeforcesbot-ext|avi|1.0.6
vscode-django|bat|1.10.0
exe-runner|bra|0.2.1
doxdocgen|csc|1.4.0
vscode-office|cwe|3.0.1
c-cpp-compile-run|dan|1.0.44
c-cpp-project-generator|dan|1.2.11
python-environment-manager|don|1.0.4
python-extension-pack|don|1.7.0
prettier-vscode|esb|9.10.4
vscode-open-in-github|fab|1.3.0
code-runner|for|0.12.0
matlab|Gim|2.3.1
codespaces|Git|1.14.3
gc-excelviewer|Gra|4.2.57
hcl|has|0.3.2
latex-workshop|Jam|9.8.2
better-cpp-syntax|jef|1.17.2
cmake-language-support-vscode|jos|0.0.9
vscode-codeforces|Kau|0.0.1
vsc-python-indent|Kev|1.18.0
wsl-path|kgr|0.1.0
vscode-wsl-workspacefolder|lfu|1.1.2
vscode-docker|ms-|1.24.0
vscode-language-pack-zh-hans|MS-|1.77.2023040509
csharp|ms-|1.25.4
vscode-dotnet-runtime|ms-|1.6.0
python|ms-|2023.6.0
vscode-pylance|ms-|2023.3.40
jupyter|ms-|2023.3.1000892223
jupyter-keymap|ms-|1.1.0
jupyter-renderers|ms-|1.0.15
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-slideshow|ms-|0.1.5
remote-containers|ms-|0.288.0
remote-ssh|ms-|0.98.0
remote-ssh-edit|ms-|0.84.0
remote-wsl|ms-|0.77.0
vscode-remote-extensionpack|ms-|0.24.0
cmake-tools|ms-|1.13.45
cpptools|ms-|1.14.5
cpptools-extension-pack|ms-|1.3.0
hexeditor|ms-|1.9.11
remote-explorer|ms-|0.4.0
remote-server|ms-|1.0.0
autodocstring|njp|0.6.1
ruby|reb|0.28.1
wsl-path-tools|rob|1.0.1
qtvsctools|ton|0.11.0
cmake|twx|0.0.17
intellicode-api-usage-examples|Vis|0.2.7
vscodeintellicode|Vis|1.2.30
vscode-icons|vsc|12.2.0
chatgpt-china|Whe|5.4.1
jinja|who|0.0.8
vscode-ruby|win|0.28.0

(6 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vscaac:30438847
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
vsccc:30610678
nodejswelcome1cf:30587006
282f8724:30602487
pyind779:30671433
89544117:30613380
pythonsymbol12:30671437
a9j8j154:30646983
vscodeenable:30660116
defaultazurewalk:30687958
pythonms35:30701012
pythonclientmvcf:30705674

```

</details>

**Comment by roblourens** [comment]
Please file this on the C++ debug extension with more detail
