### ISSUE TITLE
Explore support for `notebook.codeActionsOnSave`

### ISSUE THREAD

**Issue by Yoyokrazy** [microsoft/vscode#179213]
- list of user adjustable actions that happen just before save
- integrate alongside `formatOnSave`
- features:
	- notebook specific features
		- move all imports to top
		- delete empty cells
	- language server has things?
	- linting?

**Comment by Yoyokrazy** [comment]
merge all code with `%pip install ...` to a new top cell?

**Comment by jrieken** [comment]
* rule: source action can only modify its file (text document or notebook) @mjbvz 
* code action kind for notebooks: `source.notebook.xyz` or `notebook.source.xyz` or `notebook.xyz` @Yoyokrazy 
* register code action provider for `notebookType` @Yoyokrazy 
* notebook on save: (1) call notebook-provider with first cell (2) call code providers for documents @Yoyokrazy

**Comment by Yoyokrazy** [comment]
#182799 adds support for standard CodeAction providers to supply actions for notebook cells, also ensures that edits only apply to the given cell via a check between the TextEdit's resource and the model URI. Existing providers and extensions may need a document selector/filter capable of selecting notebook cells.

> notebook on save: (1) call notebook-provider with first cell (2) call code providers for documents

Part (2) of this statement is now completed. [This](https://github.com/microsoft/vscode/blob/milively/nb_ca/src/vs/workbench/contrib/notebook/browser/contrib/saveParticipants/saveParticipants.ts#L140) CodeAction sorting will need to be revised to prioritize the Notebook CodeAction type, rather than source.fixAll. Current thinking is that this should take priority over the parallel cell actions, as Notebook types will likely restructure the contents of multiple cells.

> code action kind for notebooks: source.notebook.xyz or notebook.source.xyz or notebook.xyz

Current thought is to adopt `notebook.xyz` for actions affecting the entire notebook. Actively working on an extension to experiment with functionality

**Comment by Yoyokrazy** [comment]
#183457 adds in the proper `notebook` kind into the SaveParticipants for notebooks. Currently upon save, CodeActions are applied as follows:

- Actions are gathered from settings and split into cell CodeActions and notebook CodeActions
  - the prior group contains everything not starting with `notebook.xyz`. The latter contains ONLY actions starting with `notebook.xyz`
- Notebook level codeactions are applied sequentially, calling providers against only the first cell in the notebook. It is the responsibility of the provider to iterate over the notebook and apply edits in a performant manner, and construct NotebookEdits that alter the desired cells.
  - note: if you are linking your provider to a selector that only runs against code cells, this will likely break functionality, as markdown cells are often the leading cell in notebooks. This behavior will be explored during next debt week.
- Cell level codeactions are applied to each cell in parallel. this includes all source.fixAll, quickfix, and other existing CodeAction kinds. 
  - note: the edits returned by these providers are restricted to only touching the passed in resource (the cell's TextDocument) when in the context of saving notebooks. outside of this, the restriction is not applied.

An example extension with a basic notebook CodeAction provider can be found [here](https://github.com/Yoyokrazy/clean-nb-imports-ext). This is still a personal wip, and currently only adds imports to a new top cell, rather than also removing them from throughout the notebook. The SaveParticipant handling CodeActions on save can be found [here](https://github.com/microsoft/vscode/blob/main/src/vs/workbench/contrib/notebook/browser/contrib/saveParticipants/saveParticipants.ts#L98).

**Comment by Yoyokrazy** [comment]
Notebook CodeActions are now in a good state of useability, and are no longer invasive in every lightbulb of every code cell in a notebook. Fixed by the above PR. They can only be leveraged via the `notebook.codeActionsOnSave` setting rather than a lightbulb in the cell. 

Todo:
- [ ] Add better logging to help developers troubleshoot (#184027)
- [ ] Finish example extension to demo Notebook CodeActionKind to new users and show functionality.
- [ ] Explore way to surface notebook CodeActions outside of the save context. Kai liked the idea of a lightbulb potentially in the new toolbar. (related to #161119)
