### ISSUE TITLE
searching the command palette or for files no longer automatically focuses the first result

### ISSUE THREAD

**Issue by ahicks92** [microsoft/vscode#179281]
Does this issue occur when all extensions are disabled?: yes

- VS Code Version: 1.777.0
- OS Version: Windows 10

Steps to Reproduce:

1. Open the command palette with a screen reader (maybe this also happens without one but I'm blind so I wouldn't know)
2. Type "about"which, for me, only finds "help: about"
3. You can no longer just press enter, and the screen reader doesn't announce this, just that there's 1 result.  You must now press down arrow and review manually.

I used to be able to memorize small snippets of text for commands I use infrequently enough that binding them to keys wasn't worth it but frequently enough that I remember what they are, and that combined with the functionality whereby it remembers the most recently used thing allowed for hitting commands quickly.

I also used to be able to remember a file name in our quite large codebase (httpd.c for example), ctrl+p, type httpd.c, enter before it even announces the result.  But I can no longer do that.

This is, for lack of a better word, clunky.  The old experience was perhaps surprising but had the advantage that you could get used to it and move quickly.  The new experience is less surprising, but I'm not going to be able to regain that speed: the lower bound is at minimum having to move my right hand over to the arrow keys, but in practice worse than that because it's no longer possible to tell if you've typed enough to find what you want, when you already know what you want.  This has gone from one of the most ergonomic and convenient parts of vscode with a  screen reader to one of the least, at least for me.  I'd not be saying that except that the command palette and file search are kinda core to being able to move around quickly, so what otherwise may sound like a somewhat minor inconvenience in a still accessible control to the sighted is something that I have to deal with multiple times per minute.

**Comment by meganrogge** [comment]
this is fixed in the latest insider's build
/duplicate https://github.com/microsoft/vscode/issues/177476
