### ISSUE TITLE
Nested beginCaptures results in tmLanguage failing to load

### ISSUE THREAD

**Issue by Sainan** [microsoft/vscode#179362]
Minimal tmLanguage to reproduce: https://gist.github.com/Sainan/66ded7b29bb905cd61149b0a360d523d

Note that I have commented out the problematic section, so you can see it doing some highlighting:

![image](https://user-images.githubusercontent.com/63328889/230306044-8e142937-e9e7-4a34-939b-655835ef393a.png)

Uncommenting it and reloading VS Code causes it to fail:
![image](https://user-images.githubusercontent.com/63328889/230306298-c09b6c63-bfea-446a-8596-7e6ccaaa4d1e.png)

I've tried working around this by adding the 'default-arguments' part to the repository and using include, but it also doesn't work.

**Comment by aeschli** [comment]
See [my comment in the gist](https://gist.github.com/Sainan/66ded7b29bb905cd61149b0a360d523d?permalink_comment_id=4533028#gistcomment-4533028)

**Comment by Sainan** [comment]
Ah yeah, you are indeed correct. It didn't even occur to me that I fumbled the XML since it loaded fine in Sublime Text. I suppose a tmLanguage with incorrect XML failing to load works as expected.
