### ISSUE TITLE
Git log

### ISSUE THREAD

**Issue by tonka3000** [Microsoft/vscode#17936]
- VSCode Version: 1.8.1
- OS Version: MacOS X

VSCode has many nice git features, but one is really missing `git log`. It would be great if i could display the `git log` directly in VSCode instead of switch to the terminal or another application.

**Comment by lennylxx** [comment]
Try this https://marketplace.visualstudio.com/items?itemName=donjayamanne.githistory

**Comment by rebornix** [comment]
It's a good extension candidate and there are quite a few git log extensions in the marketplace.

**Comment by tonka3000** [comment]
Thx. I will check out the extensions.
