### ISSUE TITLE
JS scripts in html should respect js/ts.implicitProjectConfig.strictNullChecks

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#179331]
**bug**
1. Set `js/ts.implicitProjectConfig.strictNullChecks`
2. Create a script block in html with:

```
navigator.serviceWorker.controller
```

**bug**
`controller` doesn't show as nullable

**Comment by eleanorjboyd** [comment]
What is the best way to test that "controller doesn't show as nullable"?

**Comment by mjbvz** [comment]
Just over over the types. You can also see this in the suggest widget for controller

**Comment by eleanorjboyd** [comment]
<img width="875" alt="image" src="https://user-images.githubusercontent.com/26030610/234998095-de819a91-79f4-49f9-95e7-7bd60d5d989a.png">
This looks right so listing it as verified!
