### ISSUE TITLE
`activationEvents` `"onView:workbench.explorer.emptyView"` does not work

### ISSUE THREAD

**Issue by microhobby** [microsoft/vscode#179382]
Does this issue occur when all extensions are disabled?: Not applicable (because I cannot test if my extension will be activated, it is impossible)

- VS Code Version: 
- OS Version: 

Steps to Reproduce:

1. Create an extension
2. Add in the `activationEvents` array an entry `"onView:workbench.explorer.emptyView"`

**Comment by alexr00** [comment]
By design, we don't have activation events for built in views.

https://github.com/microsoft/vscode/issues/176805 would add activation events for some views, but not all (also by design). `workbench.explorer.emptyView` is one of the views that will never have an activation event.
