### ISSUE TITLE
File compare not retaining position, when swapping between tabs

### ISSUE THREAD

**Issue by MullinsN** [Microsoft/vscode#17938]
- VSCode Version 1.8.1 :
- OS Version Win 10 Version 1607 (Build 14393.576) :

Steps to Reproduce:

1. Compare 2 files (Using "Select to Compare" - Useful if this was available in the tab - not just folder explorer).
2. Move down the comparison of the two files, change position.
3. Swap to another file within VSCode, one another tab.
4. Move back to the comparison of the two files.

Expected result: The position within the comparison is maintained.

Actual result: The user is moved to the first line of the comparision, each time they are return to the comparison view.

As I move down the comparision to look at the differences between two files, I expect the position to be maintained.

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/10663
