### ISSUE TITLE
Configuration resolution seems at least square in number of language? overrides

### ISSUE THREAD

**Issue by mueheg** [microsoft/vscode#179369]
nb: I can't reopen #168869 but it still reproduces exactly as outlined in my original report.

Does this issue occur when all extensions are disabled?: Yes
- VS Code Version:  1.77.1
- OS Version: vscode.dev

Steps to Reproduce:

Open settings.json
Paste a large number of per language overrides, for instance generated by running this JS snippet:

```
let overrides='';
for (let i = 0; i<500; ++i) { 
  overrides+= `    "[julia${i}]": { "editor.defaultFormatter": "vscode.typescript-language-features" },`;
}
```
*paste contents of overrides into settings.json*

At a very first glance, it looks like the code starting from https://github.com/microsoft/vscode/blob/main/src/vs/platform/configuration/common/configurationModels.ts#L697 is at least square in the number of overrides.

I put a counter in the code and with ~130 overrides I see getContentsForOverrideIdentifer being invoked 150000 times when I load settings / switch between user and workspace within the settings UI.

**Comment by sandy081** [comment]
Assigning to current milestone for investigation

**Comment by sandy081** [comment]
@mueheg Can you please let me know if this happens with and without opening Settings UI?
