### ISSUE TITLE
[Extension Api] when executing command "revealLine" with little delay, second action sometimes dont trigger with smoothScrolling

### ISSUE THREAD

**Issue by geril2207** [microsoft/vscode#179368]
Type: <b>Bug</b>

I found this problem in Vim extension when using half page scroll with centered view and smoothScrolling, and reproduce this bug in test clean extension. Without smoothScrolling it works fine.
When executing command `revealLine` two times with ~150ms delay second action dont trigger (view stay in position by first `revealLine`). U can see it on this video, when view in some cases not returned to 31 line from 39.

https://user-images.githubusercontent.com/62308020/230312420-c6603d11-8022-42d6-a276-2c48c6ea7b11.mp4

Reproduce: 
1. For reproducing i set interval with two timeouts to create delay between two executions and set smoothScrolling.
![image](https://user-images.githubusercontent.com/62308020/230309467-ce440417-e942-4733-8dcb-c81c702a24da.png)

VS Code version: Code 1.76.2 (ee2b180d582a7f601fa6ecfdad8d9fd269ab1884, 2023-03-14T17:55:54.936Z)
OS version: Windows_NT x64 10.0.19045
Modes: Unsupported
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 5500U with Radeon Graphics          (12 x 2096)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.31GB (4.39GB free)|
|Process Argv|--crash-reporter-id 5a09c3ba-43e1-4df4-8946-bce498209f98|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (35)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|3.0.2
astro-vscode|ast|0.28.2
vscode-tailwindcss|bra|0.9.11
path-intellisense|chr|2.8.4
vscode-css-modules|cli|0.4.2
vscode-database-client2|cwe|6.3.4
vscode-eslint|dba|2.4.0
es7-react-js-snippets|dsz|4.4.3
vsc-material-theme-icons|equ|2.7.4
prettier-vscode|esb|9.10.4
auto-close-tag|for|0.5.14
auto-rename-tag|for|0.1.10
code-runner|for|0.12.0
geril-vim|ger|1.25.2
go|gol|0.38.0
vscode-graphql|Gra|0.8.7
vscode-graphql-syntax|Gra|1.1.0
code-background|Kat|2.5.4
vscode-docker|ms-|1.24.0
remote-wsl|ms-|0.76.1
remote-explorer|ms-|0.4.0
remote-server|ms-|1.0.0
material-icon-theme|PKi|4.25.0
prisma|Pri|4.12.0
LiveServer|rit|5.7.9
rust-analyzer|rus|0.3.1463
vscode-styled-components|sty|1.7.8
svelte-vscode|sve|107.3.0
errorlens|use|3.8.0
intellicode-api-usage-examples|Vis|0.2.7
vscodeintellicode|Vis|1.2.30
vscode-icons|vsc|12.2.0
JavaScriptSnippets|xab|1.8.0
material-theme|zhu|3.15.8
vscode-proto3|zxh|0.5.5

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscoreces:30445986
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
nodejswelcome1cf:30587006
3biah626:30602489
pyind779:30671433
89544117:30613380
pythonsymbol12:30671437
a9j8j154:30646983
vscodedisable:30660115
defaultazurewalk:30687958
pythonms35:30701012
pythonclientmvcf:30705674

```

</details>

**Comment by geril2207** [comment]
After update to 1.77.1 bug still exists

**Comment by alexdima** [comment]
@geril2207 Thank you for the repro! The root cause is this particular call - https://github.com/microsoft/vscode/blob/efd550c86ef31aecfcacb1972467f2f57f6cfca2/src/vs/editor/contrib/inlayHints/browser/inlayHintsController.ts#L577 introduced via https://github.com/microsoft/vscode/commit/1476d6fa71732dd601ba5ca31a228c2988703845 cc @jrieken 

That code runs even when the inlayHintsController doesn't do anything and it ends up interrupting the current editor scroll animation.
