### ISSUE TITLE
Unknown property: 'container-type'

### ISSUE THREAD

**Issue by OOPS-Studio** [microsoft/vscode#179312]
Visual Studio Code does not recognize these CSS properties.

`Unknown property: 'container-type'`
`Unknown property: 'container-name'`
`Unknown property: 'container'`

https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Container_Queries

**Comment by aeschli** [comment]
Duplicate of https://github.com/microsoft/vscode/issues/170589
