### ISSUE TITLE
Error received from starting extension host (kind: Remote)

### ISSUE THREAD

**Issue by Tabll** [microsoft/vscode#179371]
Does this issue occur when all extensions are disabled?: `Yes`

- VS Code Version: 1.77.1
- OS Version: Windows 11 and remote server is linux

Steps to Reproduce:

1. Configure the ./ssh/config file and connect to the remote host through SSH.
2. All extensions on the remote host are not available (can be installed, but cannot be used)，like python extension: unable to use any of the provided commands
    ![image](https://user-images.githubusercontent.com/19689327/230309954-73743163-15fb-488e-81bc-3ff19264cc92.png)

### Logs in Developer Tools
```php
ERR Error received from starting extension host (kind: Remote)
workbench.desktop.main.js:620 
ERR The remote extension host took longer than 60s to send its ready message.
```
![image](https://user-images.githubusercontent.com/19689327/230310757-6ae9c861-759f-446d-aef9-16365f783f99.png)

### The Process Manager
![image](https://user-images.githubusercontent.com/19689327/230310989-b64919a1-2b70-419d-bca9-08b22157b121.png)

i've tried to delete the entire ./vscode-server folder on the remote server, However, the preceding error persists after the vscode server is reconnected and reinstalled.
i'm not sure if the 60s connection timeout is too short to cause the problem, or if it's something else.
i can provide more logs if needed.

**Comment by alexdima** [comment]
@Tabll Is your `$HOME` directory on the linux machine you are connecting to mapped to a local disk on that machine? I've recently seen a case where the `$HOME` directory on the remote machine was mapped from a network share, which made filesystem operations very slow, which caused the remote extension host a very long time to start up. You can try configuring `remote.SSH.serverInstallPath` to use a different location on the remote linux machine.

**Comment by Tabll** [comment]
> @Tabll Is your `$HOME` directory on the linux machine you are connecting to mapped to a local disk on that machine? I've recently seen a case where the `$HOME` directory on the remote machine was mapped from a network share, which made filesystem operations very slow, which caused the remote extension host a very long time to start up. You can try configuring `remote.SSH.serverInstallPath` to use a different location on the remote linux machine.

@alexdima Thank you for your prompt reply. As for what you mentioned, i haven't tried to modify the configuration `remote.SSH.serverInstallPath` yet. Because the problem disappeared after i uninstalled the local extension called '[Chinese (Simplified) Language Pack for Visual Studio Code](https://marketplace.visualstudio.com/items?itemName=MS-CEINTL.vscode-language-pack-zh-hans)'.
The ssh connection became very fast after removing the extension. ☺

Here are some of the configurations i modified at the same time, hoping to help users who encounter the same problem:
```php
Remote.SSH: Local Server Download: always
Remote.SSH: Connect Timeout: 300
Remote.SSH: Lockfiles In Tmp: √
Remote.SSH: Remote Server Listen On Socket：√
Remote.SSH: Use Local Server：×
```
