### ISSUE TITLE
git changes show in file but not show in source control panel

### ISSUE THREAD

**Issue by tjx666** [microsoft/vscode#179308]
One thing must note this file is a symbolic link:

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/41773861/230188702-9d6cd908-ad53-42df-beeb-db3c2f74d1ea.png">

Reproduce:

1. git clone git@github.com:rollup/plugins.git
2. open with vscode
3. open file `packages/node-resolve/tsconfig.json`

```
Version: 1.77.1 (Universal)
Commit: b7886d7461186a5eac768481578c1d7ca80e2d21
Date: 2023-04-04T23:23:33.779Z
Electron: 19.1.11
Chromium: 102.0.5005.196
Node.js: 16.14.2
V8: 10.2.154.26-electron.0
OS: Darwin x64 22.4.0
Sandboxed: No
```

**Comment by lszomoru** [comment]
@tjx666, thank you very much for filing this issue. There are various known issues with the git extension related to symbolic links. The work to fully support symbolic links is tracked with this issue - https://github.com/microsoft/vscode/issues/5970. I would suggest that you subscribe to it to be notified when progress is made.
