### ISSUE TITLE
URLs with parens not recognized as full URL

### ISSUE THREAD

**Issue by nfdevil** [Microsoft/vscode#17939]
- VSCode Version: 1.8.1
- OS Version: Windows 8.1

Steps to Reproduce:

1. Create a new .ts file
2. Type `let url = <backtick>http://***/_api/web/lists/GetByTitle('Teambuildingaanvragen')/items<backtick>;` where the <backtick> is the symbol ` (github uses this for code, so I can't include it)

![image](https://cloud.githubusercontent.com/assets/7434048/21565581/1c9e9f18-ce9a-11e6-9f2c-5520d75e23aa.png)

This example should be ctrl+click-able and blue from the http to the items.

**Comment by mjbvz** [comment]
This is not js/ts specific as far as I can tell. It repos for other languages as well so this seems to be the behavior of the default VSCode document link detector.

@jrieken or @alexandrudima any thoughts on this issue or where to start investigating?

**Comment by jrieken** [comment]
It is a generic problem with the [`LinkComputer`](https://github.com/Microsoft/vscode/blob/master/src/vs/editor/common/modes/linkComputer.ts#L168). Unsure how owns that these days...
