### ISSUE TITLE
Remote installes wrong version on Rasberry 4b

### ISSUE THREAD

**Issue by Soleg06** [microsoft/vscode#179384]
Type: <b>Bug</b>

Since an recent update my RaberryPi  reports it has aarch64 architecture but it really has the 32 bit operating system installed. This causes Visual Studio Code to install the arm64 version instead of the armhf version.
Downloading and installing the armhf version works but the automated install Visual Studio does occasionally doesn't.

On rasberry pi the command 
"uname -m"
reports aarch64 (wrong if that is what the automated install reads, only indicates that it is 64-bit capable)

but the command
"dpkg --print-architecture" reports armhf (right 32-bit operating system installed)

I think the installationsscript are looking in the wrong place and therefore installs the wrong not working version.

VS Code version: Code 1.77.1 (b7886d7461186a5eac768481578c1d7ca80e2d21, 2023-04-04T23:21:11.906Z)
OS version: Windows_NT x64 10.0.19045
Modes:
Sandboxed: Yes
Remote OS version: Linux arm 6.1.21-v8+

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7300HQ CPU @ 2.50GHz (4 x 2496)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|7.89GB (2.48GB free)|
|Process Argv|--crash-reporter-id 3e9dc588-4554-40a5-9445-7ed23b40ae52|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: sune|
|OS|Linux arm 6.1.21-v8+|
|CPUs|unknown (4 x 1500)|
|Memory (System)|1.81GB (1.26GB free)|
|VM|0%|
</details><details><summary>Extensions (28)</summary>

Extension|Author (truncated)|Version
---|---|---
project-manager|ale|12.7.0
better-cpp-syntax|jef|1.17.2
vsc-python-indent|Kev|1.18.0
jupyter-keymap|ms-|1.1.0
remote-ssh|ms-|0.98.0
remote-ssh-edit|ms-|0.84.0
remote-explorer|ms-|0.4.0
python-extended-snippets|tus|0.0.1
jinja|who|0.0.8
vscode-django|bat|1.10.0
python-environment-manager|don|1.0.4
python-extension-pack|don|1.7.0
vsc-python-indent|Kev|1.18.0
python-path|mge|0.0.14
autopep8|ms-|2022.2.0
isort|ms-|2022.8.0
python|ms-|2023.6.0
vscode-pylance|ms-|2023.4.10
jupyter|ms-|2023.3.1000892223
jupyter-keymap|ms-|1.1.0
jupyter-renderers|ms-|1.0.15
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-slideshow|ms-|0.1.5
autodocstring|njp|0.6.1
vscode-yaml|red|1.12.2
intellicode-api-usage-examples|Vis|0.2.7
vscodeintellicode|Vis|1.2.30
jinja|who|0.0.8

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
vscccc:30610679
nodejswelcome1cf:30587006
3biah626:30602489
pyind779:30671433
f6dab269:30613381
vscrpc:30673769
pythonsymbol12:30671437
showlangstatbar:30672706
vsctsb:30705553
defaultazurewalk:30687958
pythonms35:30701012
pythonclientmvcf:30705674

```

</details>

**Comment by roblourens** [comment]
https://github.com/microsoft/vscode-remote-release/issues/2947
