### ISSUE TITLE
Jupyter notebook text/html has problem displaying pandas.DataFrame values

### ISSUE THREAD

**Issue by matoxxx** [microsoft/vscode#179379]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 

Version: 1.77.0
Commit: 7f329fe6c66b0f86ae1574c2911b681ad5a45d63
Date: 2023-03-29T10:05:35.165Z
Electron: 19.1.11
Chromium: 102.0.5005.196
Node.js: 16.14.2
V8: 10.2.154.26-electron.0
OS: Linux x64 6.2.8-arch1-1
Sandboxed: Yes

Steps to Reproduce:

1.  Generate df with very small values
```
data = {'MmCART': ('RVT-CRISPR-G5', 1.4e-65, 71, 274, 203),
 'MzCART': ('RVT-GII-II', 5e-62, 69, 270, 201),
 'GlCART': ('RVT-GII-II', 1.2e-54, 6, 199, 193),
 'CaCART': ('RVT-GII-II', 6.6e-32, 27, 197, 170),
 'FsCART': ('RVT-GII-II', 6.4e-51, 69, 272, 203),
 'LINE1_RT': ('RVT-CRISPR-G2', 4.4e-20, 9, 223, 214),
 'Ty3_RT': ('RVT-GII-II', 3.5e-07, 113, 177, 64),
 'GsRT': ('RVT-GII-I', 1.7e-63, 4, 210, 206),
 'LlltrA_RT': ('RVT-GII-I', 2e-68, 19, 290, 271),
 'HIV_RT': ('RVT-Retrons', 0.00011, 129, 221, 92),
 'TcTERT_RT': ('RVT-CRISPR-G2', 1.6e-09, 62, 148, 86),
 'HsTERT_RT': ('RVT-CRISPR-G5', 9.7e-13, 207, 295, 88)}
```
2. Inline view shows wrong values, **scientific notation limited to E-24**

| MmCART | MzCART | GlCART | CaCART | FsCART | LINE1_RT | Ty3_RT | GsRT | LlltrA_RT | HIV_RT | TcTERT_RT | HsTERT_RT |
| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |
| RVT-CRISPR-G5 | RVT-GII-II | RVT-GII-II | RVT-GII-II | RVT-GII-II | RVT-CRISPR-G2 | RVT-GII-II | RVT-GII-I | RVT-GII-I | RVT-Retrons | RVT-CRISPR-G2 | RVT-CRISPR-G5 |
| 0.00000E-24 | 0.00000E-24 | 0.00000E-24 | 0.00000E-24 | 0.00000E-24 | 44.00000E-21 | 350.00000E-09 | 0.00000E-24 | 0.00000E-24 | 110.00000E-06 | 1.60000E-09 | 970.00000E-15 |
| 71 | 69 | 6 | 27 | 69 | 9 | 113 | 4 | 19 | 129 | 62 | 207 |
| 274 | 270 | 199 | 197 | 272 | 223 | 177 | 210 | 290 | 221 | 148 | 295 |
| 203 | 201 | 193 | 170 | 203 | 214 | 64 | 206 | 271 | 92 | 86 | 88 |

**Comment by rebornix** [comment]
@matoxxx sorry for reaching out late, may I ask how did you get the table in step 2?

**Comment by matoxxx** [comment]
> @matoxxx sorry for reaching out late, may I ask how did you get the table in step 2?

Hi, its from my data science project. These are probability values (E-value) from a database search.

**Comment by matoxxx** [comment]
Hi,
I have returned to some of my data science projects. I have figured the problem lies in pandas.DataFrame inferring dtype to object (because is of a mixed type), which turns off the scientific notation and rounds the numbers.
By forcing 
`pd.set_option('display.float_format', '{:.2E}'.format)
`
the inline table view shows correct values.

MmCART | MzCART | GlCART | CaCART | FsCART | LINE1_RT | Ty3_RT | GsRT | LlltrA_RT | HIV_RT | TcTERT_RT | HsTERT_RT
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
RVT-CRISPR-G5 | RVT-GII-II | RVT-GII-II | RVT-GII-II | RVT-GII-II | RVT-CRISPR-G2 | RVT-GII-II | RVT-GII-I | RVT-GII-I | RVT-Retrons | RVT-CRISPR-G2 | RVT-CRISPR-G5
1.40E-65 | 5.00E-62 | 1.20E-54 | 6.60E-32 | 6.40E-51 | 4.40E-20 | 3.50E-07 | 1.70E-63 | 2.00E-68 | 1.10E-04 | 1.60E-09 | 9.70E-13
71 | 69 | 6 | 27 | 69 | 9 | 113 | 4 | 19 | 129 | 62 | 207
274 | 270 | 199 | 197 | 272 | 223 | 177 | 210 | 290 | 221 | 148 | 295
203 | 201 | 193 | 170 | 203 | 214 | 64 | 206 | 271 | 92 | 86 | 88

**Comment by amunger** [comment]
sounds like this was just a pandas config issue. I believe the same behavior exists on jupyter notebooks.

**Comment by andreamah** [comment]
I will remove the milestone from this issue since it doesn't need verification.
