### ISSUE TITLE
Wrong save on lost focus

### ISSUE THREAD

**Issue by yuyuki** [Microsoft/vscode#17932]
- VSCode Version: Code 1.8.1 (ee428b0eead68bf0fb99ab5fdc4439be227b6281, 2016-12-19T14:49:23.350Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

|Extension|Author|Version|
|---|---|---|
|Bookmarks|alefragnani|0.10.1|
|vscode-color|anseki|0.2.2|
|path-intellisense|christian-kohler|1.2.0|
|gitignore|codezombiech|0.5.0|
|jshint|dbaeumer|0.10.15|
|EditorConfig|EditorConfig|0.3.4|
|tslint|eg2|0.7.1|
|vscode-npm-script|eg2|0.1.5|
|auto-rename-tag|formulahendry|0.0.9|
|docthis|joelday|0.3.6|
|net-core-project-manager|ksubedi|0.3.6|
|vscode-JS-CSS-HTML-formatter|lonefy|0.2.2|
|HTMLHint|mkaufman|0.3.3|
|prettify-json|mohsen1|0.0.3|
|csharp|ms-vscode|1.6.2|
|tsimporter|pmneo|1.2.13|
|vscode-icons|robertohuertasm|4.3.0|
|sass-indented|robinbentley|1.3.0|
|code-settings-sync|Shan|2.3.8|
|stylelint|shinnn|0.21.1|
|autoimport|steoates|1.2.2|
|change-case|wmaurer|1.0.0|
|html-css-class-completion|Zignd|1.0.3|

---

Steps to Reproduce:

1. set  "files.autoSave": "onFocusChange" in your setting
2. open two files in split windows
3. make some modification on one file without saving
4. click on the second file in the second window
5. the code of the first file is save in place of the code in the second file

**Comment by rebornix** [comment]
I think it's expected as `focus change` event is occurred on the first file so the content of first file is saved.

**Comment by yuyuki** [comment]
I'm not agree with you. 

I think when the first window lost focus the new content MUST BE SAVE ON THE FIRST WINDOW. 

The problem is that the content of the first window is save on the second window. 

Sorry for insist but I do not meet the problem with webstorm. 

Thank you and happy new year ☺

⁣Jaufré Devosse 

Envoyé par BlueMail ​

Le 30 déc. 2016 19:41, à 19:41, Peng Lyu <notifications@github.com> a écrit:

**Comment by rebornix** [comment]
@yuyuki sorry that I might misread the description you put it there. Are you saying the content of first window is saved into the second window? If so then it's a valid bug.

**Comment by yuyuki** [comment]
It's exactly that. 

Thank you to understand and I wish you the best for next year 

⁣Jaufré Devosse 

Envoyé par BlueMail ​

Le 30 déc. 2016 20:01, à 20:01, Peng Lyu <notifications@github.com> a écrit:

**Comment by rebornix** [comment]
Thank you for your patience and happy new year! I'd like to ask just one more question, when you `open two files in split windows`, are you editing the same file in two split windows or two different files in different windows?

Right now from what I tell, editing the same file in two split windows with `onFocusChange` is ruined but I don't run into any issue if I'm editing two different files in different windows. Hope you can help confirm.

**Comment by rebornix** [comment]
@yuyuki thanks for the video, it shows how the problem goes great!

However I still can't reproduce this issue even with the same files you are using. Could you please disable all extensions and see if you can still reproduce this?

**Comment by rebornix** [comment]
This issue was moved to Lonefy/vscode-JS-CSS-HTML-formatter#44

**Comment by rebornix** [comment]
I just found that it's caused by `vscode-JS-CSS-HTML-formatter`
