### ISSUE TITLE
VSCode Crash when viewing Output Window

### ISSUE THREAD

**Issue by mreeve** [microsoft/vscode#179305]
Type: <b>Bug</b>

Follow the steps on tutorial https://code.visualstudio.com/docs/nodejs/nodejs-tutorial

Actual Results: Crashing on MacOS Ventura 13.3 everytime I try to switch to the output window after running `node app.js' from the tutorial 

Expected: The results output to the window so you can read "Hello World"

VS Code version: Code 1.77.1 (b7886d7461186a5eac768481578c1d7ca80e2d21, 2023-04-04T23:22:38.708Z)
OS version: Darwin arm64 22.4.0
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M2 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|3, 3, 3|
|Memory (System)|8.00GB (0.08GB free)|
|Process Argv|--crash-reporter-id 45255bf8-7861-41da-b6a7-9e03d0aa59dc|
|Screen Reader|yes|
|VM|0%|
</details><details><summary>Extensions (53)</summary>

Extension|Author (truncated)|Version
---|---|---
extendscript-debug|Ado|2.0.3
markdown-emoji|bie|0.3.0
markdown-preview-github-styles|bie|1.0.1
vscode-eslint|dba|2.4.0
githistory|don|0.6.20
dotenv-vscode|dot|0.23.0
xml|Dot|2.5.1
gitlens|eam|13.4.0
vscode-html-css|ecm|1.13.1
EditorConfig|Edi|0.16.4
prettier-vscode|esb|9.10.4
auto-close-tag|for|0.5.14
auto-rename-tag|for|0.1.10
vscode-yarn|gam|2.1.0
copilot|Git|1.79.10634
vscode-github-actions|git|0.25.3
vscode-pull-request-github|Git|0.62.0
gitlab-workflow|Git|3.60.0
terraform|has|2.25.4
vscode-mocha-test-adapter|hbe|2.14.1
vscode-test-explorer|hbe|2.21.1
jsx|Hen|1.3.0
intellij-idea-keybindings|k--|1.5.9
vscode-docker|ms-|1.24.0
csharp|ms-|1.25.4
vscode-kubernetes-tools|ms-|1.3.11
isort|ms-|2022.8.0
python|ms-|2023.6.0
vscode-pylance|ms-|2023.3.40
jupyter|ms-|2023.3.1000892223
jupyter-keymap|ms-|1.1.0
jupyter-renderers|ms-|1.0.15
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-slideshow|ms-|0.1.5
remote-containers|ms-|0.288.0
remote-ssh|ms-|0.98.0
remote-ssh-edit|ms-|0.84.0
remote-wsl|ms-|0.77.0
live-server|ms-|0.4.7
powershell|ms-|2023.3.3
remote-explorer|ms-|0.4.0
test-adapter-converter|ms-|0.1.7
batch-runner|Nil|1.0.1
vscode-yaml|red|1.12.2
LiveServer|rit|5.7.9
terraform-doc-snippets|run|0.6.0
partial-diff|ryu|1.4.3
ddev|Sim|1.7.2
autoimport|ste|1.5.4
html-preview-vscode|tht|0.2.5
shellcheck|tim|0.31.1
pdf|tom|1.2.2
vscode-import-cost|wix|3.3.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
nodejswelcome1:30587005
3biah626:30602489
pyind779:30671433
89544117:30613380
pythonsymbol12:30671437
6233i204:30672705
pythonb192:30669360
azdwalk:30687957
pythonms35:30701012

```

</details>

**Comment by bpasero** [comment]
Can you please follow the steps in https://github.com/Microsoft/vscode/wiki/Native-Crash-Issues to get at more details around the crash and attach the result here? Thanks!
