### ISSUE TITLE
Feature Request: Collapse All for find results

### ISSUE THREAD

**Issue by RichardShephard** [Microsoft/vscode#17935]
- VSCode Version: 1.7.2
- OS Version: Windows 10

Steps to Reproduce:

1. Search for something with 1 or 2 hits (e.g. A C# Reference Include) in a large project folder
2. Search results display as expected but if you only want to see the folder/files view you have to manually collapse the view of each file. With 90+ hits, this becomes tiresome.

We routinely have projects that have thousand of files and a few hundred VS solutions/projects. Searching for something like an included reference can result in a large number of hits of 1 to 3 lines.

It would be a nice feature to be able to collapse all the find results in a single click (or key shortcut) rather than selecting them individually.

**Comment by roblourens** [comment]
You mean this kind of search right?

![image](https://cloud.githubusercontent.com/assets/323878/21600441/edeaa20e-d130-11e6-896c-3956a86f7256.png)

That middle button on the right will collapse all the results

**Comment by RichardShephard** [comment]
:flushed: I totally missed that...

Apologies - thanks for pointing this out. 😃  This was what I was looking for.

Thanks.

**Comment by sshmyg** [comment]
Is there some option, which can help do it by default?
