### ISSUE TITLE
About the use of the terminal

### ISSUE THREAD

**Issue by zhanglizhao** [Microsoft/vscode#17934]
- VSCode Version: 0.11.18

How to use vscode is used to implement the following:

·Open the terminal.
·automatic input to execute commands
·type the command execution

I use the method of vscode.com mands. ExecuteCommand ('workbench.action.terminal.new')  opened the terminal but made I don't know how to perform the command I print to the terminal, and execute it

**Comment by Tyriar** [comment]
You need to create a terminal via the terminal api using `window.createTerminal` https://code.visualstudio.com/Docs/extensionAPI/vscode-api#_window and then call show and sendText on the object it returns https://code.visualstudio.com/Docs/extensionAPI/vscode-api#Terminal

**Comment by zhanglizhao** [comment]
According to what you said I have successfully achieved.thank you
