### ISSUE TITLE
I can't debug code with "ReadKey()" line.

### ISSUE THREAD

**Issue by Neogamezzz** [microsoft/vscode#179378]
Type: <b>Bug</b>

dotnet new console --framework net7.0

In Program.cs add line "Console.ReadKey();" at the bottom.
Save
Run Debag

Error: "Exception has occurred: CLR/System.InvalidOperationException
An unhandled exception of type 'System.InvalidOperationException' occurred in System.Console.dll: 'Cannot read keys when either application does not have a console or when console input has been redirected. Try Console.Read.'
   at System.ConsolePal.ReadKey(Boolean intercept)
   at Program.<Main>$(String[] args) in D:\Desktop\Hello\Program.cs:line 3"

VS Code version: Code 1.77.1 (b7886d7461186a5eac768481578c1d7ca80e2d21, 2023-04-04T23:21:11.906Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 PRO 4650G with Radeon Graphics (12 x 3693)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|59.89GB (50.40GB free)|
|Process Argv|--crash-reporter-id a6c93f93-2ba9-4a59-8e65-bbbc98201528|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
csharp|ms-|1.25.4

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
nodejswelcome1cf:30587006
3biah626:30602489
pyind779:30671433
89544117:30613380
pythonsymbol12:30671437
6233i204:30672705
vsctsb:30705553
pythonb192:30669360
azdwalk:30687957
pythonms35:30701012
pythonclientmv:30705673

```

</details>

**Comment by roblourens** [comment]
This sounds like a problem with your system/configuration or with dotnet.

**Comment by Neogamezzz** [comment]
> This sounds like a problem with your system/configuration or with dotnet.
"closed this as completed"
WAT?! Are you kidding me?

I found the answer on Stackoverflow:
Change "console: internalConsole" to "console: integratedTerminal" in launch.json file.
Done.
