### ISSUE TITLE
[VS Code 1.8] Second bug of contentChanges of TextDocumentChangeEvent

### ISSUE THREAD

**Issue by formulahendry** [Microsoft/vscode#17937]
- VSCode Version: 1.8.x ONLY
- OS Version: All

This is the second bug related to contentChanges of TextDocumentChangeEvent in VS Code 1.8. The first one is #17444 

Steps to Reproduce:

1. Open a folder in VS Code
2. Create two files: a.html and b.html
3. Put focus on a.html and write any content into a.html
4. Run `git init` then `git add`
5. Switch to b.html
6. Switch to a.html

**Actual**:
The `vscode.workspace.onDidChangeTextDocument` is triggered and `event.contentChanges[0].text` returns the whole content of a.html
More seriously,`event.contentChanges[0].text` **always returns the same html string** (after tab change) before making changes using `git add a.html`
**Expect**:
`vscode.workspace.onDidChangeTextDocument` should not be triggered

As a result, this makes [my extension](https://marketplace.visualstudio.com/items?itemName=formulahendry.auto-close-tag) not work normally:
![auto-close-tag-bug](https://cloud.githubusercontent.com/assets/8117458/21478765/afdef162-cb5f-11e6-9663-66c6c803ad2e.gif)
Automatic close tag should not be added after tab switch.

**Comment by lsharir** [comment]
This happens on my machine as well. `event.contentChanges[0].text` returns the same html string that was committed instead of the current html string.

**Comment by dbaeumer** [comment]
@jrieken FYI.

**Comment by jrieken** [comment]
@formulahendry @lsharir Please paste the **full uri**  of the document in question. That is because when adding a file to the index an immutable copy of that current version is created in addition to the file in question. They differ in the `scheme`, like `FILE:///foobar.text` and `GIT-INDEX:///foobar.text`

**Comment by formulahendry** [comment]
Hi @jrieken , it is `GIT-INDEX`. Wonder why the event will be triggered when switching files.

![vscode](https://cloud.githubusercontent.com/assets/1050213/21607411/d2378bc4-d1f0-11e6-80f1-6b596346a5bc.gif)

**Comment by jrieken** [comment]
The previous `git-index` model is disposed and a new one is created. Because we only use the index file for inline dirty decoration, we don't need other models (one per editor column) staying around.

**Comment by jrieken** [comment]
Closing this bug as question because the behaviour is the designed behaviour and nothin unexpected
