### ISSUE TITLE
Click between terminal and his header removes styles

### ISSUE THREAD

**Issue by seanghay** [microsoft/vscode#179360]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 
```
Version: 1.77.1
Commit: b7886d7461186a5eac768481578c1d7ca80e2d21
Date: 2023-04-04T23:23:33.779Z
Electron: 19.1.11
Chromium: 102.0.5005.196
Node.js: 16.14.2
V8: 10.2.154.26-electron.0
OS: Darwin x64 22.3.0
Sandboxed: No
```
- OS Version: `Darwin Macbook.local 22.3.0 Darwin Kernel Version 22.3.0: Mon Jan 30 20:42:11 PST 2023; root:xnu-8792.81.3~2/RELEASE_X86_64 x86_64`

Steps to Reproduce:

https://user-images.githubusercontent.com/15277233/230294889-cc443bd1-9bb3-4470-90e9-8b6e87661f53.mov

**Comment by iamandrewluca** [comment]
A title that would describe what is happening in video will be better.

**Comment by seanghay** [comment]
> A title that would describe what is happening in video will be better.

Describe it for me please, I don't know how to describe that

**Comment by iamandrewluca** [comment]
> Click between terminal and his header removes styles

**Comment by tamuratak** [comment]
Duplicate of #179020

**Comment by seanghay** [comment]
release asap 👍
