### ISSUE TITLE
loop complete Source objects through debugger UI 

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#1793]
If a debug adapter wants to support breakpoints in non-standard source like 'inlined source maps', it has to add additional data to the Source object returned to the debug UI and it expects that this data will arrive intact when the UI passes the Source back to the debug adapter. In addition the front-end has to persist this data across sessions.

I've added an optional attribute 'adapterData' to the Source class. VSCode debug UI should leave the data intact and persist it across sessions. VSCode debug UI should not interpret the data.

**Comment by isidorn** [comment]
Please note that I verified that this does not break anything but I did not verify if the `adapterData` gets passed through. Though it should work 😇

**Comment by weinand** [comment]
@isidorn the adapterData is correctly passed within a session, but not across different sessions. So it does not seem to be persisted in breakpoints.

**Comment by felixfbecker** [comment]
@weinand out of curiosity, what kind of data would that be? Isn't there `sourceReference` for virtual sources?

**Comment by weinand** [comment]
@felixfbecker node-debug supports setting breakpoints in inlined source (that is source that lives in the source map which again might be inlined in the generated source). In order to restore these breakpoints on session start, node-debug needs to have enough information in the Source object to find the source map. The  'sourceReference' in Source is only valid for a session and cannot be used to persist 'virtual sources' (see comment in debugProtocol.d.ts).

**Comment by felixfbecker** [comment]
@weinand thanks, seems logical.

**Comment by weinand** [comment]
@isidorn for breakpoints persisted in a previous session I do not get the 'adapterData' back in the setBreakpointsRequest.
