### ISSUE TITLE
mention go to next/previous command in terminal accessibility help widget

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#179470]

**Comment by rzhao271** [comment]
Adding the verification steps I took for Aiday.

1. Turn the `editor.accessibilitySupport` setting to `auto` or `on`.
2. Focus on the terminal with a screenreader. There's a prompt to use Alt+F1 to access the help widget.
3. Press Alt+F1 to access the help widget, and then use the up/down arrow keys to confirm that the go to next/previous commands are mentioned.
