### ISSUE TITLE
Better line wrapping for markdown files (and other relevant file types)

### ISSUE THREAD

**Issue by axefrog** [Microsoft/vscode#17948]
- VSCode Version: 1.8.1
- OS Version: Windows 10

Not sure if this is possible, but it'd make the markdown editing experience better. Line wrapping currently only considers indentation. Is there any way to adjust the wrapping indent level based on additional contextual information? It'd mean that rather than wrapping like this (current behaviour):

```md
- Item 1
  - Item 2
  - lorem ipsum dolor sit amet lorem ipsum dolor sit amet lorem ipsum dolor sit
  amet lorem ipsum dolor sit amet lorem ipsum dolor sit amet
  - Item 3
- Item 4
```

... it could instead wrap like this:

```md
- Item 1
  - Item 2
  - lorem ipsum dolor sit amet lorem ipsum dolor sit amet lorem ipsum dolor sit
    amet lorem ipsum dolor sit amet lorem ipsum dolor sit amet
  - Item 3
- Item 4
```

**Comment by mjbvz** [comment]
@alexandrudima I believe that this is something that the core editor would have implement, perhaps with another language configuration option. Let me know if you have any thoughts

**Comment by alexandrudima** [comment]
The wrapping indent computation is indeed at this time language agnostic and simply indents at the same indentation level. This can be somewhat configured via `editor.wrappingIndent`, but it would still be unaware of the syntactic meaning of `-`.

**Comment by trajano** [comment]
I was wondering if we can just have word wrap enabled or disabled by type.  It would generally just be for markdown files where I would enable word wrap though.

**Comment by mjbvz** [comment]
@trajano That sounds like a separate problem. With VSCode 1.9, you have have language specific settings such as:

```json
"[markdown]": {
   "editor.wordWrap": "on",
   "editor.lineNumbers": "off"
}
```

**Comment by trajano** [comment]
@mjbvz thanks I found it too, it took a bit for me because I was using `[md]` rather than `[markdown]` and was wondering why it didn't work.  I wish there was an example but that's another problem.

**Comment by axefrog** [comment]
I wonder if this could also be applied when wrapping jsdoc comments, e.g. - use virtual (uneditable) characters on wrapped lines to visualise the indent; e.g.

```js
/**
 * Here is a really long text with many, many, many, many, many, many, many, many, many, many, many, many, many words
 **/
```

Could wrap like so:

```js
/**
 * Here is a really long text with many, many, many, many, many, many, many, many, many, many,
 * many, many, many words
 **/
```
The indent and asterisk on the second line of the description would be a virtualised result of the wrapping, with the specific wrapping behaviour defined by the language mode.

**Comment by alexandrudima** [comment]
To keep the number of issues in our inbox at a manageable level, we're closing issues that have been on the backlog for a long time but haven't gained traction: we look at the number of votes the issue has received and the number of duplicate issues filed. Thank you for your time and understanding.

If you disagree and feel that this issue is crucial: we're happy to listen and to reconsider.
