### ISSUE TITLE
Add Customizable Sidebar Feature

### ISSUE THREAD

**Issue by Swapnil-2503** [microsoft/vscode#179440]
Currently, the sidebar in vscode provides quick access to different files and directories, but it can become cluttered for some users. I propose adding a customizable sidebar feature that allows users to organize the content based on their preferences. This could include options such as collapsing or expanding directories, hiding or showing certain files or directories, and customizing the order of files and directories in the sidebar. A customizable sidebar would provide a more personalized user experience and make it easier for users to navigate large projects.

**Comment by Swapnil-2503** [comment]
what i can do new in this design as you think will look good ,any suggestions.

**Comment by lramos15** [comment]
Do you have an example of a product that already does this?

**Comment by Swapnil-2503** [comment]
examples 
Windows file explorer: In Windows, the file explorer provides a sidebar that allows users to quickly access different files and directories. Users can customize the sidebar by sorting folders and files according to name, size, type, or date modified. They can also pin frequently accessed items to the top of the sidebar for quick access.
Atom text editor: Atom is a popular text editor that provides a customizable sidebar where users can organize content based on their preferences. The sidebar can be collapsed or expanded, and users can hide or show certain files or directories. Users can also sort items in the sidebar by name, type, or recent use, and can customize the order of items.
Sublime Text: Sublime Text is another popular text editor that provides a customizable sidebar. Users can collapse or expand directories, and can hide or show certain files or directories. They can also sort items in the sidebar by name, type, or usage frequency, and can customize the order of items.

isnt it will be better feature if its in vscode

**Comment by lramos15** [comment]
\duplicate https://github.com/microsoft/vscode/issues/27286 https://github.com/microsoft/vscode/issues/164033
