### ISSUE TITLE
C Syntax Highlighting Bug

### ISSUE THREAD

**Issue by brewsto** [Microsoft/vscode#17942]
- VSCode Version: Code 1.8.1 (ee428b0eead68bf0fb99ab5fdc4439be227b6281, 2016-12-19T14:42:49.304Z)
- OS Version: Darwin x64 16.1.0
- Extensions:

|Extension|Author|Version|
|---|---|---|
|theme-monokai-dark-soda|AdamCaviness|0.0.5|
|solidity|JuanBlanco|0.0.20|
|code-gnu-global|austin|0.2.1|
|latexcompile|mathiasfrohlich|0.7.0|
|cpptools|ms-vscode|0.9.3|
|latex|ms-vscode|0.1.3|
|Spell|seanmcbreen|0.9.1|

---

Steps to Reproduce:

1. Use ternary operator in C
2. Put function in the "then" part
3. Syntax highlighting is wrong for that function (appears as a var)

**Comment by rebornix** [comment]
@brewsto can you try to disable c related extensions and then reload the window to see if it's caused by an extension?

**Comment by pietz** [comment]
(this is brewsto)

its not caused by any extenstions, i disabled them all and checked again. same result. functions are not highlighted within the "then" part of a ternary operator.

**Comment by aeschli** [comment]
This issue was moved to atom/language-c#192
