### ISSUE TITLE
History navigation doesn't let me escape

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#179488]
- Focus an input box that has history
- Press up, get the last history item
- Press down- nothing happens! Here I expect it to clear the input

![Recording 2023-04-07 at 11 37 51](https://user-images.githubusercontent.com/323878/230660440-8c493d96-8539-45c4-9fa7-72705d3bdd5e.gif)

**Comment by roblourens** [comment]
Relevant: https://github.com/microsoft/vscode/issues/52961

That should not regress as part of this, but verifier please try it too

**Comment by roblourens** [comment]
This impacts

- Debug console
- Testing view
- Keyboard shortcuts editor
- All inputs in the search view
- Chat view

**Comment by isidorn** [comment]
Great change imho!
