### ISSUE TITLE
NVDA announces "language x was automatically detected and set as the language mode" once a second when autodetecting languages, even when the language doesn't change

### ISSUE THREAD

**Issue by ahicks92** [microsoft/vscode#179427]
Does this issue occur when all extensions are disabled?: yes

- VS Code Version: 1.77.1
- OS Version: Windows 10

Steps to Reproduce:

1. For some reason this is fine on documents which are already open when VSCode starts, so start by making a new file.  Don't save it: once it has an extension, autodetection stops kicking in.
2. Type some markdown. Eventually the screen reader announces that the language was autodetected.
3. Type a single letter, pause, and the screen reader will announce that the language was autodetected as markdown again.  Continue typing single characters and waiting and it continues to do the same.

This also does the same if you just type normally, but the above is a repro that's likely to work even with typing echo on.  I'd expect it to announce it only when it changes.

**Comment by meganrogge** [comment]
@isidorn do you know who owns language detection?

**Comment by isidorn** [comment]
@TylerLeonhardt owns it :)

Good catch - it seems like we should announce only if the Detected Language changes.
