### ISSUE TITLE
TS v5 and a new option for importModuleSpecifierEnding - 'ts'

### ISSUE THREAD

**Issue by MWhite-22** [microsoft/vscode#179499]
With TS v5, there is an option to set the tsconfig module resolution as "bundler" which then allows TS ESM files to import from '*.ts' extensions, as the runtime code is passed through another bundler. 

As such, can typescript.preferences.importModuleSpecifierEnding be given an additional option of 'ts'?

**Comment by mjbvz** [comment]
This feature is powered by the TypeScript project. Please [file a feature request upstream](https://github.com/microsoft/TypeScript/issues/new?template=Feature_request.md)
