### ISSUE TITLE
Can not see output history in console .

### ISSUE THREAD

**Issue by ichynul** [microsoft/vscode#179443]
Type: <b>Bug</b>

can not see output history in console .

VS Code version: Code 1.77.1 (b7886d7461186a5eac768481578c1d7ca80e2d21, 2023-04-04T23:21:11.906Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 5600H with Radeon Graphics          (12 x 3294)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|12.92GB (4.98GB free)|
|Process Argv|--crash-reporter-id 8f88cd1b-3c2c-43c2-ac6a-48db7e06a14c|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (18)</summary>

Extension|Author (truncated)|Version
---|---|---
html-end-tag-labels|ant|0.11.0
vscode-intelephense-client|bme|1.9.5
vscode-eslint|dba|2.4.0
composer-php-vscode|DEV|1.33.12924
phptools-vscode|DEV|1.33.12924
githistory|don|0.6.20
codespaces|Git|1.14.4
githd|hui|2.3.3
vue|jcb|0.1.5
php-namespace-resolver|Meh|1.1.9
git-graph|mhu|1.30.0
vscode-language-pack-zh-hans|MS-|1.77.2023040509
remote-wsl|ms-|0.77.0
vs-keybindings|ms-|0.2.1
php-docblocker|nei|2.7.0
vscode-mdx|uni|1.3.0
volar|Vue|1.2.0
JavaScriptSnippets|xab|1.8.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vscaac:30438847
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
nodejswelcome1:30587005
282f8724:30602487
pyind779:30671433
f6dab269:30613381
pythonsymbol12:30671437
a9j8j154:30646983
showlangstatbar:30672706
vsctsb:30705553
azdwalk:30687957
pythonms35:30701012
pythonclientmv:30705673

```

</details>

![20230407140423](https://user-images.githubusercontent.com/10061650/230551900-847e4a13-bb73-4fe3-b114-297ccda1c923.png)
![20230407140440](https://user-images.githubusercontent.com/10061650/230551924-8a51a6dd-80ab-439b-ba79-05a93a2b2109.png)

**Comment by gjsjohnmurray** [comment]
Please use the Start Extension Bisect command to investigate whether the problem is being caused by one of your extensions.

**Comment by ichynul** [comment]
The problem with dragging the divider bar at the top of the console will reappear, and I have disabled all extensions.

https://user-images.githubusercontent.com/10061650/230568964-37339dd9-b654-434e-984f-a5715da28e74.mp4
