### ISSUE TITLE
Syntax highlight for styles-jsx? 

### ISSUE THREAD

**Issue by DigitalMarc** [Microsoft/vscode#17947]
Hi guys,
It would be nice to have such feature:
https://atom.io/packages/language-styled-jsx

**Comment by rebornix** [comment]
It's a good extension candidate.

**Comment by mjbvz** [comment]
Yes, this is something that we would expect a third party extension to provide. Take a look at how the atom extension works to get started (I suspect it is using a grammar injection).

Thanks

**Comment by davibe** [comment]
I want this too.

I have also created this plugin for atom that works exactly in the same way:
https://github.com/davibe/language-markdown-in-js

I would like to create a vs code equivalent but i am not sure how to do it and where to start (note that it was easy for me to do it for atom even if i never created a plugin before)
