### ISSUE TITLE
java error

### ISSUE THREAD

**Issue by Qusea** [Microsoft/vscode#17940]
<img width="958" alt="screenshot 2016-12-30 16 50 02" src="https://cloud.githubusercontent.com/assets/6491176/21566056/3729c2b6-ceb0-11e6-82c5-4df4a8037397.png">
- VSCode Version: Code 1.8.1 (ee428b0eead68bf0fb99ab5fdc4439be227b6281, 2016-12-19T14:42:49.304Z)
- OS Version: Darwin x64 16.1.0
- Extensions:

|Extension|Author|Version|
|---|---|---|
|swift|Kasik96|0.0.2|
|javac-linter|faustinoaq|1.2.1|
|code-runner|formulahendry|0.6.5|
|ios-snippets|ornithologist|0.0.15|
|java|redhat|0.0.8|
|vscode-swift-language|rlovelett|0.1.0|
|java-imports-snippets|tushortz|0.0.1|
|java-snippets|tushortz|0.0.1|

---

I keep getting this message every time I launch, even though I already installed java

**Comment by rebornix** [comment]
I think this issue should be triaged in Java repository first.

**Comment by rebornix** [comment]
This issue was moved to redhat-developer/vscode-java#134
