### ISSUE TITLE
Subprocess call process lags with attached debugger

### ISSUE THREAD

**Issue by amine-aboufirass** [microsoft/vscode#179449]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 
```
1.77.1
b7886d7461186a5eac768481578c1d7ca80e2d21
x64
```

- OS Version: 
![image](https://user-images.githubusercontent.com/24267968/230572546-32be751d-af13-449e-bb82-e4c223168e79.png)

 # Steps to Reproduce:

Folder contents:

```
.vscode
    launch.json
cli.py
test_debugpy_issue_simplified.py
```

Contents of `cli.py`:

```
print("hello world")
```

Contents of `test_debugpy_issue_simplified`:

```
import subprocess
import os
import json

print(os.getpid())
input()

configArgs = ["python", "cli.py"]

ret_code=0
while ret_code==0:
    ret_code = subprocess.call(configArgs, shell=False, universal_newlines=True)
    print(ret_code)
```

Contents of `launch.json`:

```
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Python: Current File",
            "type": "python",
            "request": "launch",
            "program": "${file}",
            "console": "integratedTerminal",
            "justMyCode": true
        },
        {
            "name": "Python: Attach using Process Id",
            "type": "python",
            "request": "attach",
            "processId": "${command:pickProcess}",
            "justMyCode": true
        }
    ]
}
```

In order to replicate the issue, carry out the following steps:

- Open up a Powershell or CMD terminal
- Run `python .\test_debugpy_issue.py`
- Note the provided PID
- *Run > start debugging > * Attach to process with PID noted above
- Add breakpoint on line 10 in `test_debug_issue_simplified.py`
- Go back to terminal and press ENTER
- Step over to line 12 in Vs Code
- Step over line 12

The debugger freezes at `subprocess.call`. Running the script without debugging works just fine.

**Comment by roblourens** [comment]
Please file this on the vscode-python extension repo
