### ISSUE TITLE
Unknown icon is repo search results

### ISSUE THREAD

**Issue by Liturgist** [microsoft/vscode#179403]
I was asked to create this based on https://github.com/microsoft/vscode-remote-repositories-github/issues/320

Does this issue occur when all extensions are disabled?: Yes/No
Unknown.

- VS Code Version: 
```
PS C:\> code --version
1.77.1
b7886d7461186a5eac768481578c1d7ca80e2d21
x64

```
- OS Version: 
```
Caption        : Microsoft Windows 10 Pro
Version        : 10.0.19045
DisplayVersion : 22H2
BuildType      : Multiprocessor Free
OSArchitecture : 64-bit
```
Steps to Reproduce:

1. Search remote GitHub repository
2. Unknown icon occasionally appears in filename list. Looks like it might be related to communication with the remote repo, but unknown meaning.
![image](https://user-images.githubusercontent.com/2530958/230444055-59410d43-5f5d-4c79-9464-5cc227bf10a9.png)

**Comment by aeschli** [comment]
Can you give reproducible steps?
- Which remote repository do you open
- what do you search for
- when you open the file with the unknown icon, what language does it show in the status bar? Is the icon correct on the editor tab?

**Comment by Liturgist** [comment]
The repo is a GitHub Enterprise Cloud repo for a Fortune < 10 company. It seems unlikely that even if I could tell you what repo it is that you would be able to access it.

I provided a picture of the icon. When is that image used?

**Comment by aeschli** [comment]
I need reproducible steps to be able to investigate. If your repor is private, can you maybe reproduce/reconstruct  it with a public repository?
- what do you search for
- when you open the file with the unknown icon, what language does it show in the status bar? Is the icon correct on the editor tab?
