### ISSUE TITLE
Support experimental contextual non-modal dialogs to educate users on web experiences

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode#179401]
Parent issue:
https://github.com/microsoft/vscode/issues/171190

**Comment by bhavyaus** [comment]
We've now added an experimental https://github.com/microsoft/vscode/issues/179401 contextual welcome widget in the editor on the web for new users. 


<img width="414" alt="image" src="https://github.com/microsoft/vscode/assets/25044782/75738136-685f-4929-b1b5-1538f295895a">

**Comment by bhavyaus** [comment]
Next Steps:

- [ ] Create Experiment to roll this out to insiders.vscode.dev
- [ ] Staged rollout to stable.
