### ISSUE TITLE
Add command to rerun latest terminal command

### ISSUE THREAD

**Issue by dlschmidt** [microsoft/vscode#179468]
It would be very helpful if entering a build command again and again (with up-arrow and enter) to just use the new terminal features and add a command which runs the latest command of the terminal again. Then the user could specify a keyboard shortcut to activate this command.

It would be an extension to the "Terminal: Run Recent Command..." and just selecting the latest one.

**Comment by ArturoDent** [comment]
You can make your own keybinding to do that:

```jsonc
  {
    "key": "alt+x",         // whatever keybinding you want
  
    "command": "workbench.action.terminal.sendSequence",
        
    "args": { "text": "\u001b[A\u000d" }  // sends an uparrow to the terminal
  },

`\u000d` is a return so that the last command is run immediately.

**Comment by dlschmidt** [comment]
@ArturoDent Thanks!

The question would be if VSCode should implement this natively or if it would be rather redundant compared to the VSCode Tasks feature.

**Comment by Tyriar** [comment]
I think there are too many ways to already do this; focus and press up enter, tasks, keybindings, run recent command enter. I recommend @ArturoDent's keybinding as this is exactly what you're after.
