### ISSUE TITLE
When connecting to WSL2 via Remote, the extension cannot be installed normally.

### ISSUE THREAD

**Issue by RoryLiang** [microsoft/vscode#179473]
Type: <b>Bug</b>

1. Type 'code .' command in WSL2's terminal to open Visual Studio Code.
2. Click 'Extensions' in left side of the window.
3. In 'LOCAL-INSTALLED' view, find one extension tagged 'Install in WSL: Ubuntu-22.04', click the tag to install it to WSL.
4. After click 'Install in WSL: Ubuntu-22.04' tag, it change to installing for a while.
And then, unforeseen scenarios emerge:
1. That extension show '√ Installed' status on the left of the tag.
2. The tag 'Install in WSL: Ubuntu-22.04' still there.
3. The view 'WSL: UBUNTU-22.04-INSTALLED' still contains nothing, even after re-open Visual Studio Code.
4. When you close and open Visual Studio Code, the 'Extensions' view no change from before, the extension you try to install to WSL2 STILL TAGGED 'Install in WSL: Ubuntu-22.04', AND YOU WILL NOT SEE ANY EXTENSIONS IN the view 'WSL: UBUNTU-22.04-INSTALLED'

VS Code version: Code 1.77.1 (b7886d7461186a5eac768481578c1d7ca80e2d21, 2023-04-04T23:21:11.906Z)
OS version: Windows_NT x64 10.0.19044
Modes:
Sandboxed: Yes
Remote OS version: Linux x64 5.15.90.1-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10710U CPU @ 1.10GHz (12 x 1608)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.79GB (3.59GB free)|
|Process Argv|--folder-uri vscode-remote://wsl%2Bubuntu-22.04/home/lty/cpp-primer-5th --crash-reporter-id 8d49e66c-84ba-45e6-b6cd-396c77f76dc3|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-22.04|
|OS|Linux x64 5.15.90.1-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i7-10710U CPU @ 1.10GHz (12 x 1608)|
|Memory (System)|7.65GB (6.87GB free)|
|VM|0%|
</details><details><summary>Extensions (19)</summary>

Extension|Author (truncated)|Version
---|---|---
better-cpp-syntax|jef|1.17.2
vsc-python-indent|Kev|1.18.0
jupyter-keymap|ms-|1.1.0
remote-containers|ms-|0.288.0
remote-ssh|ms-|0.98.0
remote-ssh-edit|ms-|0.84.0
remote-wsl|ms-|0.77.0
vscode-remote-extensionpack|ms-|0.24.0
remote-explorer|ms-|0.4.0
remote-server|ms-|1.0.0
material-icon-theme|PKi|4.25.0
pdf|tom|1.2.2
vscode-icons|vsc|12.2.0
vim|vsc|1.25.2
jinja|who|0.0.8
cmake-tools|ms-|1.13.45
cpptools|ms-|1.14.5
cpptools-extension-pack|ms-|1.3.0
cmake|twx|0.0.17

(4 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
nodejswelcome1:30587005
2e4cg342:30602488
pyind779:30671433
f6dab269:30613381
pythonsymbol12:30671437
6233i204:30672705
vsctsb:30705553
vscodedisable:30660115
pythonb192:30669360
azdwalk:30687957
pythonms35:30701012

```

</details>

**Comment by sandy081** [comment]
Can you please follow these steps

- Enable log level to trace - F1 > Developer: Set Log Level > Trace
- Install the extension `Install in WSL: Ubuntu-22.04`
- Share following logs
  - F1 > Open View... > Remote
  - F1 > Open View... > Network (Remote)
  - F1 > Open View... > Window

**Comment by RoryLiang** [comment]
I tried the above reproduction process in the same environment today, and the problem no longer exists.
