### ISSUE TITLE
codespace terminal does not respond after reload request

### ISSUE THREAD

**Issue by rentazillla** [microsoft/vscode#179491]
issue reloading after closing vscode desktop remote access
currently trying to access cs50 codespace with Github login at https://code.cs50.io/
terminal shows $ and white cursor but does not respond - memory issue?

Version: 1.77.1
Commit: b7886d7461186a5eac768481578c1d7ca80e2d21
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/111.0
Embedder: codespaces

**Comment by rentazillla** [comment]
Issue persists please advise. It could be that the codespace needs to be rebuilt entirely

**Comment by meganrogge** [comment]
disable `terminal.integrated.gpuAccleration` as it's not supported on certain versions of safari

/duplicate #165416
