### ISSUE TITLE
[Feature] Adding a button to toggle terminal

### ISSUE THREAD

**Issue by orsag** [Microsoft/vscode#17943]
It would be nice to have dedicated button to toggle terminal open/close integrated into that blue bottom bar.

**Comment by Tyriar** [comment]
This can be easily accomplished now as an extension, I made this one recently which adds a button for each terminal tab https://marketplace.visualstudio.com/items?itemName=Tyriar.terminal-tabs

I suggest following this issue as well which explores making buttons for the panel(s) more visible https://github.com/Microsoft/vscode/issues/9659
