### ISSUE TITLE
Keybinding widget: "<"-key not working for Swedish keyboard (Windows)

### ISSUE THREAD

**Issue by AntonAderum** [Microsoft/vscode#1794]
When using the Keybinding widget to edit the keybindings.json file, it will just respond with "unknown" when you try to press the key ```<```. The ```<``` key is located between ```shift``` and ```z``` (see picture), and I belive that key isn't present on most US-keyboards. 

At first I thought it was a problem with the node-native-keymap but when I try it it gives me the correct binding:

```
...
{ key_code: 'VKEY_OEM_7',
    value: 'ä',
    withShift: 'Ä',
    withAltGr: '',
    withShiftAltGr: '' },
  { key_code: 'VKEY_OEM_102',
    value: '<',
    withShift: '>',
    withAltGr: '|',
    withShiftAltGr: '' } ]

```

Not being able to bind that key makes it more or less impossible to use any vim-extensions since the ```<``` is used to indent.
I tried searching for a similar issue and all I could find was #1372 which is only somewhat related. I hope this isnt a duplicate.

![keyboard](https://cloud.githubusercontent.com/assets/2329863/12114699/345297a4-b3ac-11e5-9b4b-c3a662676fae.png)

**Comment by alexandrudima** [comment]
@AntonAderum Indeed, we don't currently support VKEY_OEM_8 nor VKEY_OEM_102 (see https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/services/keybinding/electron-browser/nativeKeymap.ts#L183)

**Comment by AntonAderum** [comment]
Thank you for your reply!

Do you have any plans for when / if you think you will support those missing VKEY's? 
Maybe its something that the community can help out with..

Cheers!
