### ISSUE TITLE
export profile support exclude disabled extensions

### ISSUE THREAD

**Issue by tjx666** [microsoft/vscode#179439]
![image](https://user-images.githubusercontent.com/41773861/230535432-1db084cc-b8ea-45f2-b941-833c447c381a.png)

**Comment by sandy081** [comment]
You can always uncheck the extension to exclude it.

**Comment by tjx666** [comment]
@sandy081 but there is no way to batch exclude diaabled extenaion

**Comment by sandy081** [comment]
Yah, I assume its not so often used task and hence disabling one by one shall be ok.

**Comment by tjx666** [comment]
you can see I have tens of extensions disabled
