### ISSUE TITLE
VS Code refuses to install any extensions, Green Install button says, "Installing" then never changes, even after 20 minutes

### ISSUE THREAD

**Issue by codingisforyou** [Microsoft/vscode#17945]
- VSCode Version: 1.8.1
- OS Version: Windows 10 Pro
- .Net Framework version 4.6 Installed
- Visual Studio 2010 Installed
- At home, no proxy settings.  
- Firewall is off
- Uninstalled, re-installed at least 10x
- Installed version 1.7 same problem
- Installed VSCode in different folder
- Tried rebooting
- Tried changing "http.proxyStrictSSL": false and "http.proxyStrictSSL": true
- Tried installing VS 2015 Community, Uninstalled
- Tried installing .Net Core, Uninstalled
- Tried turning on all privacy settings to ON and to OFF, 
- Tried a different computer on the same network, a laptop, worked fine, can install extensions.

None of these have worked

Steps to Reproduce:
1.  Windows 10, install, click Extensions, Install, never installs, just says Installing 
 

![untitled](https://cloud.githubusercontent.com/assets/24845514/21570777/d3c39862-ce8e-11e6-96f7-3e3092bdbbe2.png)

![untitled](https://cloud.githubusercontent.com/assets/24845514/21570828/453123f2-ce8f-11e6-9169-9b767d21e919.png)

![untitled](https://cloud.githubusercontent.com/assets/24845514/21570865/9fdcfae2-ce8f-11e6-8829-d4ad39d34755.png)

**Comment by rogersachan** [comment]
I have this issue on Release and Insiders, so VSCode is broken and will continue to be for the next few days. In m case it will be unusable since the developers of an extension I use do not distribute VSIX.

**Comment by codingisforyou** [comment]
I guess this problem is too difficult to fix.

**Comment by codingisforyou** [comment]
![untitled](https://cloud.githubusercontent.com/assets/24845514/21596840/8c1d5212-d106-11e6-8839-d9e2c34ae5a6.png)

**Comment by rogersachan** [comment]
@joaomoreno THis kind of soltuion is diappointing! Why suggest a permanent uninstall?

**Comment by codingisforyou** [comment]
No one has any answers.

**Comment by joaomoreno** [comment]
@codingisforyou Are you behind a proxy? If you open the developer tools (<kbd>F1</kbd>, `Developer Tools`) do you see any errors in there?

**Comment by rogersachan** [comment]
```
shell.ts:541EPERM: operation not permitted, mkdir 'C:\Program Files (x86)\Microsoft VS Code\null'

Error: EPERM: operation not permitted, mkdir 'C:\Program Files (x86)\Microsoft VS Code\null'
    at Error (native): Error: EPERM: operation not permitted, mkdir 'C:\Program Files (x86)\Microsoft VS Code\null'

Error: EPERM: operation not permitted, mkdir 'C:\Program Files (x86)\Microsoft VS Code\null'
    at Error (native)
    at Timeout._onTimeout (C:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\code\electron-main\main.js:5:6143)
    at tryOnTimeout (timers.js:232:11)
    at Timer.listOnTimeout (timers.js:202:5)e.onUnexpectedError @ shell.ts:541
```

**Comment by codingisforyou** [comment]
I figured it was a possibly a permissions issue.

Earlier, I tried setting the C:\Users\TDuncan\.vscode folder to:
No security, Everyone, Full Control.  

However, it looks like that may not be the right place.  Perhaps VS Code needs permissions to install to a certain directory?  I will post the errors I see on (F1, Developer Errors) ASAP.

**Comment by codingisforyou** [comment]
shell.ts:541 ENOENT: no such file or directory, mkdir 'C:\Users\TDawg\AppData\Local\Temp;c:'

Error: ENOENT: no such file or directory, mkdir 'C:\Users\TDawg\AppData\Local\Temp;c:'
    at Error (native): Error: ENOENT: no such file or directory, mkdir 'C:\Users\TDawg\AppData\Local\Temp;c:'

Error: ENOENT: no such file or directory, mkdir 'C:\Users\TDawg\AppData\Local\Temp;c:'
    at Error (native)
    at Timeout._onTimeout (C:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\code\electron-main\main.js:5:6143)
    at tryOnTimeout (timers.js:232:11)
    at Timer.listOnTimeout (timers.js:202:5)

**Comment by codingisforyou** [comment]
Update: I added a New User account to my Windows 10.
Logged in as that new user. 
Installed VS Code again.  
And it installed Extensions and worked.

**Comment by joaomoreno** [comment]
@codingisforyou Did you ever launch VS Code as an Administrator?

**Comment by codingisforyou** [comment]
Yes, I did, it's in the comments above.
I created a New Account with Admin rights and it works with the new account.
Perhaps the other account was 'corrupted'

**Comment by joaomoreno** [comment]
I meant it as before you created that new account.

**Comment by codingisforyou** [comment]
Yes, I tried that before, many times.  I even made my entire C:\Users\TDawg\ directory read write and Everyone Full Control. That did not work.

**Comment by joaomoreno** [comment]
Can you also check the `.vscode` folder in your Home folder?

**Comment by hfierros** [comment]
I had the same problem. Checking my TEMP variable it said: 
TEMP=c:\Users\myname\AppData\Local\Temp;c:\cygwin64\bin
Changing it to 
TEMP=c:\Users\myname\AppData\Local\Temp 
fixed the issue.
