### ISSUE TITLE
Git: `Initialize Repository` button does not refresh state if `git.autoRepositoryDetection` is set to `false`

### ISSUE THREAD

**Issue by kanlukasz** [microsoft/vscode#179481]
### **Does this issue occur when all extensions are disabled?:**
- Yes

### **VS Code Version:**
```
Version: 1.77.1
Commit: b7886d7461186a5eac768481578c1d7ca80e2d21
Date: 2023-04-04T23:21:11.906Z
Electron: 19.1.11
Chromium: 102.0.5005.196
Node.js: 16.14.2
V8: 10.2.154.26-electron.0
OS: Windows_NT x64 10.0.22621
Sandboxed: No
```

### **OS Version:**
- Microsoft Windows 11 Pro
- 10.0.22621 N/A Build 22621

### **Description:**

Not sure if this is intended behavior or not but I think if I use the `Initialize Repository` button it should create and show the repository.
If `git.autoRepositoryDetection` is set to `false`, the repository is actually created but nothing is shown in VsCode
I understand that this option is for auto-detect and it's kind of logical, but should it affect the `Initialize Repository` action?

### **Steps to Reproduce:**

![aaaaa333333](https://user-images.githubusercontent.com/30685349/230648153-d2dd63d3-47d8-4ce0-b4f3-20aa26c58934.gif)

**Comment by lszomoru** [comment]
@kanlukasz, thank you very much for filing this issue. Setting `git.autoRepositoryDetection` to `false` disables repository detection independent whether it already exists or it has been created using VS Code. While this is the intended behaviour, I agree that we could probably make this experience better.
