### ISSUE TITLE
Debugger does not stop on function breakpoint

### ISSUE THREAD

**Issue by chris-schmitz** [Microsoft/vscode#17946]
- VSCode Version: 1.8.1
- OS Version: Mac OS 10.12.2 (16C67)

Steps to Reproduce:

1. Create a simple Javascript file with a function that you want to break on
2. In the debugger, add the functions name to the breakpoint list
3. Run debugger 

![function breakpoint doesn t break](https://cloud.githubusercontent.com/assets/2437424/21572717/0b3d59dc-cea2-11e6-8c48-9f68f7dee518.gif)

I was following [the documentation on using the debugger](http://code.visualstudio.com/docs/editor/debugging#_function-breakpoints). As far as I can tell there wasn't a detail I missed.

Here's my `launch.json` if it helps.

    {
        "version": "0.2.0",
        "configurations": [
            {
                "type": "node",
                "request": "launch",
                "name": "Launch Program",
                "program": "${workspaceRoot}/app.js",
                "cwd": "${workspaceRoot}",
                "stopOnEntry": true
            },
            {
                "type": "node",
                "request": "attach",
                "name": "Attach to Process",
                "port": 5858
            }
        ]
    }

I used the node configuration. The only thing I added was the `stopOnEntry` option. 

Please let me know if I can provide any other information.

**Comment by weinand** [comment]
You are running into the limitations of node.js function breakpoints: https://code.visualstudio.com/docs/nodejs/nodejs-debugging#_function-breakpoints

**Comment by chris-schmitz** [comment]
Ah ok. Thanks for letting me know.
