### ISSUE TITLE
in-product release notes hyperlink text is hard to read

### ISSUE THREAD

**Issue by gregvanl** [Microsoft/vscode#17949]
- VSCode Version: 1.8.1
- OS Version: Windows 10

1. Help > Release Notes

Blue hyperlink text is hard to read and appears to be smaller than rest of text. You can see this by looking at the 1.8.1 Recovery Build "key issues" link.

This is especially problematic for the in-product release notes since Zoom In crops the display and neither editor.fontSize nor markdown.preview.fontSize applies.

**Comment by joaomoreno** [comment]
This is a problem with the Markdown preview.

**Comment by gregvanl** [comment]
I was looking at Dark+ (default dark).
![lowcontrastlink](https://cloud.githubusercontent.com/assets/12818376/21784983/a12656ba-d672-11e6-9e15-e020818c716f.png)
I'd doesn't look quite so bad on a light theme but still low contrast.
@bgashler1 took a look at the dark theme contrast and it is too low for accessibility requirements (4.1 to 1, should be 4.5 to 1).
We should lightly the hyperlinks on dark theme and darken for light themes.

**Comment by aeschli** [comment]
We added text colors in https://github.com/Microsoft/vscode/issues/26298 and once the web view adopts these each theme can tune the link colors.

**Comment by mjbvz** [comment]
I believe this has been improved:


![screen shot 2017-08-02 at 5 19 18 pm](https://user-images.githubusercontent.com/12821956/28900550-d70245ca-77a6-11e7-8dfb-1d7c0a7283c1.png)
![screen shot 2017-08-02 at 5 19 59 pm](https://user-images.githubusercontent.com/12821956/28900551-d702eaa2-77a6-11e7-8bb2-e9184197e386.png)
