### ISSUE TITLE
Fullscreen zen mode setting removed?

### ISSUE THREAD

**Issue by smlombardi** [Microsoft/vscode#17941]
- VSCode Version: Code - Insiders 1.9.0-insider (ab491d3b40a99485eece2bff1ce8c4aa49aad913, 2016-12-30T07:05:18.775Z)
- OS Version: Darwin x64 16.3.0
- Extensions:

|Extension|Author|Version|
|---|---|---|
|material-icon-theme|PKief|1.1.5|
|code-settings-sync|Shan|2.4.0|
|sort-lines|Tyriar|1.1.0|
|html-css-class-completion|Zignd|1.0.3|
|Bookmarks|alefragnani|0.10.1|
|project-manager|alefragnani|0.12.2|
|one-monokai|azemoh|0.2.4|
|vscode-icontheme-nomo-dark|be5invis|1.2.1|
|vscode-eslint|dbaeumer|1.2.2|
|githistory|donjayamanne|0.1.4|
|tslint|eg2|0.7.1|
|vscode-great-icons|emmanuelbeziat|1.1.35|
|Angular2|johnpapa|1.0.2|
|theme-karyfoundation-themes|karyfoundation|10.2.0|
|ftp-sync|lukasz-wronski|0.3.2|
|HTMLHint|mkaufman|0.3.3|
|vscode-csscomb|mrmlnc|4.0.0|
|vscode-postcss-sorting|mrmlnc|2.1.0|
|vscode-stylefmt|mrmlnc|2.2.0|
|Theme-1337|ms-vscode|0.1.2|
|angular2-inline|natewallace|0.0.16|
|nonbreakingspace|smlombardi|0.0.1|
|vscode-icons|robertohuertasm|4.3.0|
|vscode-theme-darcula|rokoroku|1.0.10|
|stylelint|shinnn|0.21.1|
|darcula-extended|smlombardi|1.0.0|
|theme-tesla|smlombardi|5.3.10|
|ayu|teabyii|0.2.1|
|bootstrap-3-snippets|wcwhitehead|0.0.9|
|change-case|wmaurer|1.0.0|

---

Steps to Reproduce:

1. I had a setting `"window.fullScreenZenMode": false` which appears to be invalid now
2. entering Zen mode full-screens the window, which on Mac I find very annoying, which is why I had set it to false.

Will the ability to enter Zen Mode in the existing window size be restored?  Please?

**Comment by isidorn** [comment]
Yes, sorry about that.
We have renamed that setting to 
`zenMode.fullScreen`
This will be available in the insiders build tomorrow.

We did the rename for conistency reasons to align well with newly introduced
`zenMode.hideTabs`
`zenMode.hideStatusBar`
