### ISSUE TITLE
Source control repo overview not displaying everything

### ISSUE THREAD

**Issue by Lefky** [microsoft/vscode#179453]
Type: <b>Bug</b>

I've updated to the latest release. Since then the source control view is only showing a message box and commit button. Not the name of the repo or even other repo's that should be opened.
When opening another repo the view does show the open repo and the newly open repo, but still not the other repo's that should've been detected. When opening a repo that should've been automatically detected nothing changes. The broken source control stays the same.
Specific settings that apply to this behaviour:

```
    "git.ignoredRepositories": [
        "/Users/sennejanssens/Documents/GitHub/sennejan.github.io",
        "/Users/sennejanssens/Documents/GitHub/lefky.github.io",
        "davinsilabs_sa-hexagonviz",
        "davinsilabs_sa-timelineviz"
    ],
    "git.scanRepositories": [
        "TMS/tms-ucl",
        "TMS/splunk-tms",
        "splunk-id870433"
    ],
```

VS Code version: Code 1.77.1 (Universal) (b7886d7461186a5eac768481578c1d7ca80e2d21, 2023-04-04T23:23:33.779Z)
OS version: Darwin arm64 22.4.0
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (0.10GB free)|
|Process Argv|--crash-reporter-id 4c766144-8a53-4191-b173-dfc65ba3543c|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-splunk-search-linter|arc|0.5.0
vscode-splunk-search-syntax|arc|1.5.3
autofoldyeah|bob|1.0.6
transformer|dak|1.12.1
vscode-eslint|dba|2.4.0
gitlens|eam|13.4.0
gc-excelviewer|Gra|4.2.57
git-graph|mhu|1.30.0
remote-ssh|ms-|0.98.0
remote-ssh-edit|ms-|0.84.0
remote-explorer|ms-|0.4.0
vscode-commons|red|0.0.6
vscode-yaml|red|1.12.2
markdown-preview-enhanced|shd|0.6.8
splunk|Spl|0.2.10

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
nodejswelcome1cf:30587006
282f8724:30602487
pyind779:30671433
f6dab269:30613381
pythonsymbol12:30671437
2i9eh265:30646982
6233i204:30672705
functionswalk:30687959
pythonms35:30701012

```

</details>

![image](https://user-images.githubusercontent.com/10397178/230582392-65846a53-3f6b-4354-b56c-780fea86cf75.png)
![image](https://user-images.githubusercontent.com/10397178/230582647-4a25fe04-7490-4d6f-aaac-1ded797741c0.png)

**Comment by Lefky** [comment]
Update:
Disabling `git.scanRepositories` seems to restore the default behaviour although no updates were of this were mentioned in the release notes as I recall?
The functionality of that setting is obviously unusable for now.

**Comment by cveld** [comment]
Have seen the `Source Control` -> `View & Sort` -> `Repositories` flag list?

![image](https://user-images.githubusercontent.com/6196260/231988908-edd3c4dd-d0d4-4a52-af48-0f42a5cb7823.png)

It would be cool to be able to manage the visible repos through the workspace settings json file.
In its current state this flag list is quite unmanageable. It just displays the root folder name where the repo is residing. In my case I generally call this root folder `main` as a subfolder of an umbrella folder where I put feature branches as sibling folders.

```
c:\work\git\reponame
|--- main
|--- 202304-featurebranch1
|--- 202304-featurebranch2
```

**Comment by lszomoru** [comment]
@cveld, please feel free to file a separate issue to track your feature request. Thanks!

**Comment by lszomoru** [comment]
@Lefky, this does seem like a bug and I would like to get to the bottom of this. Would it be possible for you to create a simplified repro case where you use 2 or 3 repositories to illustrate the issue? Thank you!

**Comment by Lefky** [comment]
> @Lefky, this does seem like a bug and I would like to get to the bottom of this. Would it be possible for you to create a simplified repro case where you use 2 or 3 repositories to illustrate the issue? Thank you!

Hi
Well I don't actually know what more info I can provide.

The exact steps would be:
1. Create a workspace on a folder containing a few repo's and have a subdirectory containing also a few repo's
2. Like in my example ignore some repo's in the root folder and scan some repo's in the subdirectory
3. The expected result would be the scanned repo's from the subdirectory to show in the source control panel together with the not ignored repo's from de root folder
4. In my case the ignored repo's seem to actually be ignored but the scanned repo's don't match. I get a repo that isn't even selected and in a different subdirectory from anything that has been defined. From the selected repo's to scan only 1 is shown (always the same one and seems to be the first one when sorted alphabetically).

Would this be enough info?

**Comment by lszomoru** [comment]
@Lefky, apologies for not getting back to you on this until now. Apart from the settings that you have already shared, I would appreciate if you would be able to provide the values of the following settings: git.repositoryScanMaxDepth, git.autoRepositoryDetection. Could you also please provide a screenshot of the folder structure highlighting the folders that contain git repositories. 

The fact that disabling `git.scanRepositories` resolves the issue clearly indicates that this is a potential regression and I would like to make sure that I am getting to the bottom of it. Thank you!

**Comment by Lefky** [comment]
@lszomoru To be honest, I don't think I have encountered the issue after a few releases later.
At the moment everything seems to be working as expected.

This is the requested info:
```
└── bitbucket
    ├── SPLAAS
    │   ├── splunk-enterprise
    │   └── splunk-kvstore-sync
    ├── SRE
    │   ├── ansible-collection-base
    │   ├── ansible-collection-bitbucket
    │   ├── ansible-collection-cribl
    │   ├── ansible-collection-dnsmasq
    │   ├── ansible-collection-insightvm
    │   ├── ansible-collection-other
    │   ├── ansible-collection-packaging
    │   ├── ansible-collection-redis
    │   ├── ansible-collection-scp
    │   ├── ansible-collection-splunk
    │   ├── ansible-collection-syslogng
    │   ├── ansible-collection-telegraf
    │   ├── ansible-collection-unbound
    │   ├── ansible-playbooks
    │   ├── ansible-playbooks-aap
    │   ├── ansible-playbooks-aws
    │   ├── ansible-playbooks-bitbucket
    │   ├── ansible-playbooks-dpg
    │   ├── ansible-role-bckp
    │   ├── ansible-role-haproxy
    │   ├── ansible-role-naviseccli
    │   ├── ansible-testing
    │   ├── base-testing
    │   ├── confluence-docs
    │   ├── cribl-testing
    │   ├── dsi-splunk-sdk
    │   ├── splunk-box-cleanup
    │   ├── splunk-build
    │   ├── splunk-testing
    │   └── tms-ucl-testing
    ├── TMS
    │   ├── splunk-ais
    │   ├── splunk-asset-reporting
    │   ├── splunk-itsi
    │   ├── splunk-platforminsights
    │   ├── splunk-tms
    │   ├── splunk-tms-forwarding
    │   └── tms-ucl
    ├── davinsilabs_sa-ais_app
    ├── davinsilabs_sa-ais_root_cause_viz
    ├── davinsilabs_sa-ais_service_focus_viz
    ├── davinsilabs_sa-ais_service_impact_viz
    ├── davinsilabs_sa-hexagonviz
    ├── davinsilabs_sa-timelineviz
    ├── splunk-id870433
    └── splunk-id870433-8604dc
```

![image](https://github.com/microsoft/vscode/assets/10397178/bc2880cf-89f1-44e8-acee-b40cd20b5069)

**Comment by lszomoru** [comment]
@Lefky, thank you very much for the update. I will go ahead and close this issue for now, but please feel free to reopen it in case you are able to reproduce the issue again. Thanks!
