### ISSUE TITLE
Unable to switch between terminal and editor by pressing Ctrl+`

### ISSUE THREAD

**Issue by cary-rowen** [microsoft/vscode#179438]
Type: <b>Bug</b>

1. I know there is at least one active terminal waiting for my input, I can switch back to the editor with ctrl+`, but I can no longer switch back to the terminal with that shortcut.
2. I noticed that VS Code has added a terminal buffer function for screen reader users in the new version. The shortcut key assigned to this function is Shift+Tab, which confuses me very much. Isn't the function of this shortcut used in windows environment to switch in reverse between controls that have focus?
I tried assigning the function to other shortcuts, but it didn't work at all.

VS Code version: Code 1.77.1 (b7886d7461186a5eac768481578c1d7ca80e2d21, 2023-04-04T23:21:11.906Z)
OS version: Windows_NT x64 10.0.19045
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8350U CPU @ 1.70GHz (8 x 1896)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.88GB (8.11GB free)|
|Process Argv|--crash-reporter-id 08ab617a-b493-4182-980e-7383997e95a3|
|Screen Reader|yes|
|VM|0%|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-language-pack-zh-hans|MS-|1.77.2023040509
remote-containers|ms-|0.288.0
remote-ssh|ms-|0.98.0
remote-ssh-edit|ms-|0.84.0
remote-wsl|ms-|0.77.0
cmake-tools|ms-|1.13.45
cpptools|ms-|1.14.5
cpptools-extension-pack|ms-|1.3.0
remote-explorer|ms-|0.4.0
cmake|twx|0.0.17

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vscaat:30438848
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
nodejswelcome1:30587005
3biah626:30602489
pyind779:30671433
f6dab269:30613381
pythonsymbol12:30671437
2i9eh265:30646982
vsctsb:30705553
pythonb192:30669360
functionswalk:30687959
pythonms35:30701012
pythonclientmvcf:30705674

```

</details>

**Comment by cary-rowen** [comment]
1.76.2 does not have such a problem.

**Comment by cary-rowen** [comment]
I tested 1.77.3 and the issue is still reproducible.
aiday-mar Can this be fixed in the next stable release?

**Comment by Tyriar** [comment]
ctrl+` is working fine for me, do you have an extension or custom keybinding that could override it? You can run the `Toggle Keyboard Shortcut Troubleshooting` command in the command palette to get information on what's happening when you hit ctrl+`.

Is the shift+tab keybinding causing issues for you? It has a when clause and is only used under special circumstances.

**Comment by cary-rowen** [comment]
@Tyriar 
Here are the logs I captured:
```
2023-05-03 19:20:28.691 [info] [KeybindingService]: / Received  keydown event - modifiers: [ctrl], code: Backquote, keyCode: 192, key: `
2023-05-03 19:20:28.691 [info] [KeybindingService]: | Converted keydown event - modifiers: [ctrl], code: Backquote, keyCode: 86 ('`')
2023-05-03 19:20:28.692 [info] [KeybindingService]: | Resolving ctrl+`
2023-05-03 19:20:28.692 [info] [KeybindingService]: \ From 1 keybinding entries, matched workbench.action.terminal.toggleTerminal, when: terminal.active, source: user.
2023-05-03 19:20:28.692 [info] [KeybindingService]: + Invoking command workbench.action.terminal.toggleTerminal.
```
When I press ctrl+\` I don't perceive any change, the focus doesn't change.

**Comment by cary-rowen** [comment]
I found the steps to reproduce the problem exactly:
In a nutshell: As long as my keyboard focus stays on the "terminal buffer", pressing Ctrl+\` can only return to the editor. If I want to return to the terminal and try to read the output, pressing Ctrl+\` again will do nothing will happen.
I customized other shortcuts for "Terminal: Focus Accessible Buffer" and "Terminal: Navigate Accessible Buffer" respectively but nothing happened.
The following screen recording demonstrates what I'm talking about:

Uploading 20230503_194026.mp4…

**Comment by meganrogge** [comment]
I wonder if the cppdebug terminal is why this is happening. Can you reproduce with just a powershell terminal?

**Comment by Tyriar** [comment]
Looks like alt+o is the only keybinding the C/C++ extension contributions so it wouldn't be that.

IME related perhaps?

![image](https://user-images.githubusercontent.com/2193314/235939182-b5eb911d-a444-4611-a5f9-846af60292ae.png)

**Comment by cary-rowen** [comment]
Debugging a python script can also reproduce this.
Maybe it has nothing to do with the extension.
However, this problem cannot be reproduced in 1.76.2.
@Tyriar 
You wrote: "IME related perhaps?"
Do you mean related to the input method?

**Comment by Tyriar** [comment]
> Do you mean related to the input method?

@cary-rowen yes, does it happen if you switch to non-IME/English keyboard layout?

**Comment by cary-rowen** [comment]
No, I just tested and it has nothing to do with IME.

**Comment by cary-rowen** [comment]
The key to reproduce the problem is that as soon as I set the system focus to 'Terminal buffer' then I can only use Ctrl+\` to go back to the editor. But again, Ctrl+\` cannot return to the terminal.
But if I Tab once to set the focus to the terminal before going back to the editor, Ctrl+\` behaves as expected.

**Comment by meganrogge** [comment]
in the gif, it appears you are running a command to get the program to run in the terminal. I believe that is what should focus the terminal but isn't currently. that's why you have to tab in order to focus the terminal.

**Comment by meganrogge** [comment]
Maybe it's a hide from user terminal or something? I'd need to see the cppdebug terminal options that are provided

**Comment by cary-rowen** [comment]
@meganrogge 
> in the gif, it appears you are running a command to get the program to run in the terminal. I believe that is what should focus the terminal but isn't currently. that's why you have to tab in order to focus the terminal.

Sorry, I'm a visually impaired user using a screen reader and there is no way to see the gif.

@meganrogge 
> Maybe it's a hide from user terminal or something? I'd need to see the cppdebug terminal options that are provided
What can I do next to help you identify the problem?

**Comment by meganrogge** [comment]
@cary-rowen for me, what happens is:

- Run selected text in active terminal succeeds, reveals the terminal panel, and keeps the editor focused (by design)
- Ctrl+` focuses the terminal
- Ctrl+` focuses the editor and closes the terminal panel
- Ctrl+` focuses the terminal and reveals the terminal panel

Is that what you expect as well? That is what I am seeing in your gif.

**Comment by meganrogge** [comment]
@cary-rowen thank you for those steps. that is by design as we want the accessible buffer to remain focused until `tab` or `escape` are used.

**Comment by meganrogge** [comment]
Maybe I misspoke. The four steps you mention above are as designed and working for me. I still do not know why that is not happening for you.

**Comment by meganrogge** [comment]
Ah I just realized a potential source of confusion. When focus is in the terminal accessible buffer, the screen reader can read "editor" since beneath the surface, we are using a Monaco editor there. I wonder if that's why, from your perspective, it seems like the focus is still in the editor instead of in the terminal?

**Comment by cary-rowen** [comment]
@meganrogge 
> Ah I just realized a potential source of confusion. When focus is in the terminal accessible buffer, the screen reader can read "editor" since beneath the surface, we are using a Monaco editor there. I wonder if that's why, from your perspective, it seems like the focus is still in the editor instead of in the terminal?

I don't think so at all, although the code editor and the accessible buffer appear to have the same role in the screen reader, they are both 'EditableText', but their Name(or Label) is completely different.
More importantly, its value (that is, the text content it contains) is completely different. The former is the code I wrote, while the latter is the output information of the terminal buffer.

**Comment by cary-rowen** [comment]
For now, the label of the code editor is the name of the currently open source code file, and the label of the accessible buffer is "Terminal buffer".
Such nomenclature does not cause confusion, so once again proving that what you fear is unlikely to happen.

**Comment by hwf1324** [comment]
Hi, @meganrogge 

I have re-recorded the video visually to demonstrate the bug. hope this will help you.

Another problem is that in the final demo, the terminal appears with characters that don't fit as expected. I'm sorry I can't describe it very well in English.

**Comment by hwf1324** [comment]
Hi, @meganrogge 

I have re-recorded the video visually to demonstrate the bug. hope this will help you.

Another problem is that in the final demo, the terminal appears with characters that don't fit as expected. I'm sorry I can't describe it very well in English.


https://user-images.githubusercontent.com/43466291/236022342-96c57713-6fff-4b49-bfdf-680a5cfd43b2.mp4

**Comment by meganrogge** [comment]
Thank you - that recording helps me understand the bug and that behavior is not as designed. I'll look into it.

**Comment by meganrogge** [comment]
@cary-rowen and @hwf1324 thanks for your gifs and repro steps. I have tried on both windows and mac OS and cannot reproduce this in insider's. I can reproduce the issue in VS Code stable. So pls use Insider's or you can look fwd to this fix in the next release.

**Comment by cary-rowen** [comment]
Hello,

Thanks @meganrogge @Tyriar
It's good that the latest stable release 1.78.0 also enjoys this fix.

Best
Cary
