### ISSUE TITLE
"process" module cannot be imported

### ISSUE THREAD

**Issue by spywhere** [Microsoft/vscode#17956]
- VSCode Version: 1.8.1 (ee428b0eead68bf0fb99ab5fdc4439be227b6281)
- OS Version: macOS Sierra 10.12.2 (16C67)

The extension crashed upon importing (requiring) a "process" module

![screen shot 2559-12-31 at 12 13 42](https://cloud.githubusercontent.com/assets/1087399/21575960/a4397796-cf52-11e6-884e-4e3b41e41166.png)
![screen shot 2559-12-31 at 12 13 49](https://cloud.githubusercontent.com/assets/1087399/21575961/a49c9240-cf52-11e6-9602-a4279efa6623.png)

Testing Repo: https://github.com/spywhere/process-test
Trigger by using command "Hello World"

FYI: The testing repo is a fresh extension (generated from `yo code` with TypeScript option selected) that just add `process.arch` and `process.platform` to the message.

**Comment by spywhere** [comment]
**Workaround:**

I just found out that Node.js has provided "OS" module which got...

`os.arch()` that equivalent to `process.arch` and `os.platform()` that equivalent to `process.platform`

Switched from "process" to "os" module fix this issue.

**Comment by Spown** [comment]
I don't know about TS, but ``process`` in JS is global variable, that you don't need and aren't allowed (I think) to overwrite... 
[The process object is a global that provides information about, and control over, the current Node.js process. As a global, it is always available to Node.js applications without using require().](https://nodejs.org/api/process.html#process_process)

**Comment by spywhere** [comment]
@Spown Thanks! I tried remove the import statement and it works. Seems like VSCode provided "process" module for a long time since I use this statement in my extension for a very long time now.

I think I'll close the issue but still need clarification from the VSCode team though.

**Comment by Spown** [comment]
maybe you named it differently? Using it as ``import * as proc from 'process';`` shouldn't cause any problems (albeit would be redundant).

**Comment by spywhere** [comment]
That also worked. Strange on how long I got it worked in my extension.
