### ISSUE TITLE
Editor position in centered layout mode gets reset

### ISSUE THREAD

**Issue by ericmc2** [microsoft/vscode#179566]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.78.0
- OS Version: Windows 10 (x64)

Steps to Reproduce:

1. Enable "Centered Layout".
2. Reposition the editor by independently moving its sashes (holding down Alt).
3. Exit and restart VS Code.

The position used to be remembered in previous versions, but starting with version 1.76, the position gets reset on every start. Only the width is being remembered. It's still broken in the current insider build of VS Code 1.78.0.

**Comment by ShalokShalom** [comment]
Do we already know, which commit causes this regression?

**Comment by ericmc2** [comment]
I looked through the commits for 1.76.0 and I suspect it was f6e10119eb0fba13a1dcb6d2ae77b8852cde8e0e.

**Comment by ShalokShalom** [comment]
Yeah, it is solved for me.
