### ISSUE TITLE
Find and Replace Fails for large replacements

### ISSUE THREAD

**Issue by drcrook1** [Microsoft/vscode#17959]
- VSCode Version: latest
- OS Version: Windows 10 - latest

Steps to Reproduce:

1. I have a .tsv file with ~315,000 rows.
2. Find the base path and replace with empty

VS Code Crashes.

**Comment by alexandrudima** [comment]
I did some optimizations for this case a month or so ago. This now works quite well for me:

generator.js:
```
var fs = require('fs');

var str = '';
for (var i = 0; i < 315000; i++) {
    str += 'c:\\Alex\\src\\vscode\\src\\vs\\editor\\common\\Line' + i + '\n';
}
fs.writeFileSync('out.txt', str);
```

![17959](https://cloud.githubusercontent.com/assets/5047891/26329549/0e7fd1c6-3f48-11e7-9c86-1e6473dd438f.gif)
