### ISSUE TITLE
win11 enable 'text cursor indicator' feature, 'text cursor indicator' shows up at wrong position

### ISSUE THREAD

**Issue by charlie-wong** [microsoft/vscode#179545]
Does this issue occur when all extensions are disabled?  Yes

The vscode is fresh install, and has **no plugins** install at all!

- VS Code Version: 
  * Version: 1.77.1 (user setup)
  * Commit: b7886d7461186a5eac768481578c1d7ca80e2d21
  *  Date: 2023-04-04T23:21:11.906Z
  * Electron: 19.1.11
  * Chromium: 102.0.5005.196
  * Node.js: 16.14.2
  * V8: 10.2.154.26-electron.0
  * OS: Windows_NT x64 10.0.22000
  * Sandboxed: Yes

- OS Version:  Windows 11 家庭中文版，21H2

Steps to Reproduce:

- Windows 11 System Settings (Preparing)

  Win11 enable **text cursor indicator** feature operations
  ![Win11-System-Setting-Preparing](https://user-images.githubusercontent.com/8766173/230750793-a2a9830b-6463-4e01-95a2-cf7434e220b7.gif)

  After win11 enable **text cursor indicator** feature, what should be correct
  ![What-Should-Be-Right](https://user-images.githubusercontent.com/8766173/230750868-ef6fd8b6-5dc3-492e-8f84-aeb551da903c.gif)

  1. Click on the **Search Bar**, which is at the buttom left corner
  2. Search **settings** in the pop up windows, click and lunch windows 11 system setting windows
  4. On the left panel, navigate to the **Accessibility**
  5. Scroll down to the **Mouse pointer and touch** section and click on it.
  6. Scroll down and click on **Text cursor** to modify it.
  7. Enable the **text cursor indicator** switch

- Bug appenence in VSCode after win11 enable **text cursor indicator** feature

  **text cursor indicator** shows up at wrong position when move around the mouse indicator in the text opened by vscode,
  the **text cursor indicator** shows up, down, maybe near or maybe far from the insert location, or is does not shows up at all!
![VSCode-v1 77 1-BUGS](https://user-images.githubusercontent.com/8766173/230750888-0545c1aa-1969-463a-b5aa-1043173fc0c0.gif)

**Comment by charlie-wong** [comment]
The win11 system is fresh install, and the vscode has no plugins install at all!

**Comment by alexdima** [comment]
Let's track in https://github.com/microsoft/vscode/issues/109151

**Comment by charlie-wong** [comment]
> Let's track in #109151

OK, got it!
