### ISSUE TITLE
Search results in editor cannot ctrl click the file location and line of code

### ISSUE THREAD

**Issue by engkhsky** [microsoft/vscode#179590]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: Version: 1.78.0-insider (system setup)
- OS Version: Windows 10

This only happen to the latest version of insider (1.78), the current vscode is still working
Steps to Reproduce:

1. Search a keyword 
2. Click open in editor
3. Results shown in editor but now unable to ctrl click "Follow link" to go to the file or the line of code

**Comment by andreamah** [comment]
@alexdima is this a regression in link detection? I also notice that I can't ctrl+click on imports in the newest insiders.

**Comment by Leonidaz** [comment]
double clicking to go to the file also stopped working

**Comment by alexdima** [comment]
I ran `npx run vscode-bisect` and it points to this commit range: https://github.com/microsoft/vscode/compare/3e0b354932b8ddeb099c68ed3b7dfac25350dde2...ea0e3e0d1fabf0622fbcacdc4fe1c7b73b34dc0b

**Comment by joyceerhl** [comment]
> When I try to add the activation event back to the package.json, I get a squiggle that it isn't necessary and that I should remove it.

I do not see this in the latest insiders, do you still repro? I updated the extension linter to not emit a warning in https://github.com/microsoft/vscode/commit/413f98e4995d0c509c3b02bfd7498cbdd317b90c (the same commit which changes the implicit activation behavior):
<img width="403" alt="image" src="https://user-images.githubusercontent.com/30305945/231302959-1cc16225-c155-4756-b86b-6035f298eb59.png">

**Comment by nikitavoloboev** [comment]
Is there any fix for this available?
