### ISSUE TITLE
rich quick pick

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#1795]
There are needs for more complex quick pick and asking for input, like _do something on focus_, _validate user input_ etc. There are:

- [x] user input validation and feedback (#1381)
- [x] handle item focus/blur (#540, #1979)
- [ ] ~~update items based on input~~
- [x] have an option to show label and description in two rows
- [x] have an option to include octicons

**Comment by jrieken** [comment]
Idea is to have _in addition_ to `showQuickPick` and `showInputBox` something like `createQuickPick` which could look like this:

```
interface QuickPick {
  show(): void;
  hide(): void;
  items: Item[]|Thenable<Item[]>
  message: string;
  onDidSelectItem: Event<Item>
  onDidFocusItem: Event<Item>
  onDidBlurItem: Event<Item>
  onDidChangeInput: Event<string>
}
```

**Comment by daviwil** [comment]
Interesting!  cc @dfinke

**Comment by dfinke** [comment]
Looks good. It'd be nice to be able to customize the dropdown too. The `extension install` does with readme and install icons.

**Comment by alefragnani** [comment]
Hi @jrieken . Is it already available in the Insider build?

I tried to use the [Extension API Consumption #1881](https://github.com/Microsoft/vscode/issues/1881) and [Proposal for separating the vscode tools from the vscode API #970](https://github.com/Microsoft/vscode/issues/970) instructions, but it still result in the same API. Maybe I'm doing something wrong in my `package.json`?

Thanks in advance.

**Comment by daviwil** [comment]
I just updated to the latest vscode.d.ts (using the new install script) and I don't see it either.

**Comment by alefragnani** [comment]
Hi @daviwil ,

It was an error in my `package.json`. I fixed and now the new API is available:

#### Update the engine:
```
	"engines": {
		"vscode": "0.10.7-insiders"
	},
```

#### Add the `postinstall` script
```
  "scripts": {
    "vscode:prepublish": "node ./node_modules/vscode/bin/compile",
    "compile": "node ./node_modules/vscode/bin/compile -watch -p ./",
    "postinstall": "node ./node_modules/vscode/bin/install"
  },
```

#### Update `vscode` in `devDependencies`
```
  "devDependencies": {
    "vscode": "~0.11.0",
    "typescript": "^1.6.2"
  }
```

And it is working perfectly, thanks @jrieken  :smile:

**Comment by bpasero** [comment]
See also: https://github.com/Microsoft/vscode-docs/blob/master/release-notes/latest.md#api-consumption

**Comment by daviwil** [comment]
Cool!  I didn't know there was an 0.10.7-insiders engine specifically.  I think I didn't understand what I was looking for in the quick pick typings, the API suggestion that Johannes wrote in a comment before is what I was looking for :)  I can see now that the typings are different between 0.10.6 and 0.10.7.  All good now, thanks for the help!

**Comment by masaeedu** [comment]
@jrieken Regarding the "update items based on input" story that got removed, is there an alternative for this? It would be useful to allow the user to enter some custom text if none of the options suffice.

**Comment by jrieken** [comment]
We are tracking that in #426

**Comment by whitecolor** [comment]
allowing to have splitter in the list would be useful.

**Comment by aefernandes** [comment]
Just to confirm, are these rich quick pick features currently available? I want to create custom keybindings for the quick pick dropdown items and currently can't do something on focus.
