### ISSUE TITLE
UI is broken when changing Terminal font size

### ISSUE THREAD

**Issue by waterforce1205** [Microsoft/vscode#17958]
- VSCode Version: Code 1.8.1 (ee428b0eead68bf0fb99ab5fdc4439be227b6281, 2016-12-19T14:41:20.664Z)
- OS Version: Linux x64 4.4.0-57-generic
- Extensions:

|Extension|Author|Version|
|---|---|---|
|code-gnu-global|austin|0.2.1|
|Go|lukehoban|0.6.51|
|cpptools|ms-vscode|0.9.3|
|csharp|ms-vscode|1.6.2|

---

Steps to Reproduce:

1. Change "editor.fontFamily" to "'Ubuntu Mono'"
2. Change "terminal.integrated.fontSize" to 16

![screenshot](https://cloud.githubusercontent.com/assets/16859342/21576666/2275d2ea-cf6b-11e6-962a-96b9f36c607d.png)

In the screenshot, the first line of the Integrated Terminal is merely appeared due to font size.

**Comment by rebornix** [comment]
Dup of https://github.com/Microsoft/vscode/issues/14479 .
