### ISSUE TITLE
Quickly locate the definition location of a variable

### ISSUE THREAD

**Issue by tjy-gitnub** [microsoft/vscode#179515]
Press shortcut key, enter the name and quickly locate the definition location of a variable or function

**Comment by jrieken** [comment]
We have quick outline for that, trigger it with cmd+shift+o (windows/linux ctrl+shift+o), then type the name of the symbol. Is this new for you or are you missing something from that?

**Comment by tjy-gitnub** [comment]
oh,thanks,I didn't know it before
