### ISSUE TITLE
runTest is ignored when running extension tests

### ISSUE THREAD

**Issue by sophodoros** [microsoft/vscode#179576]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version:  1.77.1 and 1.78.0-insider (ea0e3e0d)
- OS Version: Windows 11 and Mac Ventura 13.2.1

The `runTest.ts` code that the [VS Code Testing Extensions documentation](https://code.visualstudio.com/api/working-with-extensions/testing-extension#the-test-script) says is needed for running extension tests is ignored and not needed to run the tests. 

I first discovered this when trying to make changes to my own extension's `runTest.ts` code and finding that they were ignored. I then verified this using the VS Code [helloworld-test-sample](https://github.com/microsoft/vscode-extension-samples/tree/main/helloworld-test-sample).   

Steps to Reproduce:

1. Download the [helloworld-test-sample](https://github.com/microsoft/vscode-extension-samples/tree/main/helloworld-test-sample) code. 
2. Open the helloworld-test-sample folder in VS Code.
3. Comment-out _all_ of the code in the `src/test/runTest.ts` file. 
4. Select the "Run and Debug" option in the VS Code activity bar.
5. Select "Run Extension Tests" in the "RUN AND DEBUG" dropdown.
6. Click the green run arrow to run the extension tests.
7. If the code in `runTest.ts` is needed, the tests should not run if the code is commented out. If the issue described here exists, the tests will run, and when they complete the "Debug Console" window will show that the "Extension Test Suite" ran and that 1 test passed. 

As a variation on step 3, instead of commenting out all of the code you can add code to throw an exception before the `await runTests` call in `runTest.ts`. It, too, will be ignored, and the tests will run successfully.

Issue #144115 may be related to this issue.

**Comment by connor4312** [comment]
The purpose of "runTest" is to download and launch a VS Code instance suitable for running tests. In the case of debugging, you're using your current VS Code version and profile--with some special mechanics to make a debug connection to the extension host, and `runTest` isn't used at all.

The `--extensionTestsPath` is the script that's run in the extension host in both cases. You might notice that this is referred to both in `.vscode/launch.json` and passed to `runTest`. This is where you want to put common code that needs to be run during tests.

Hope this helps.

**Comment by sophodoros** [comment]
Hi Connor. Thanks for the quick response. 

You said, "_The purpose of "runTest" is to download and launch a VS Code instance suitable for running tests._" 

However, the [VS Code extension documentation](https://code.visualstudio.com/api/working-with-extensions/testing-extension) never clearly states that `runTest.ts` is optional and, by default, not used at all. 

The "Custom setup with @vscode/test-electron" section of the doc describes how to change `runTest.ts` to use a different version of VS Code. The [helloworld-test-sample](https://github.com/microsoft/vscode-extension-samples/tree/main/helloworld-test-sample) code contains an example `runTest.ts`, but it is never called, so changing it as suggested in the "Custom setup" section has no effect. 

What else needs to change in the [helloworld-test-sample](https://github.com/microsoft/vscode-extension-samples/tree/main/helloworld-test-sample) code to tell the testing framework to use `runTest.ts`? Maybe the secret to this is buried in the documentation, but I'm not able to figure it out.

**Comment by connor4312** [comment]
The sample has code that uses runTest in the standard [`npm test`](https://github.com/microsoft/vscode-extension-samples/blob/98346fc4fa81067e253df9b32922cc02e8b24274/helloworld-test-sample/package.json#L30) script.

PR's into the docs to clarify things would be more than welcome!
