### ISSUE TITLE
Folder drag override bug!

### ISSUE THREAD

**Issue by iamideas** [Microsoft/vscode#17957]
- VSCode Version: Code 1.8.1 (ee428b0eead68bf0fb99ab5fdc4439be227b6281, 2016-12-19T14:41:20.664Z)
- OS Version: Linux x64 4.4.0-57-generic
- Extensions:

|Extension|Author|Version|
|---|---|---|
|html-css-class-completion|Zignd|1.0.3|
|Bookmarks|alefragnani|0.10.1|
|project-manager|alefragnani|0.12.2|
|vscode-color|anseki|0.2.2|
|code-gnu-global|austin|0.2.1|
|path-intellisense|christian-kohler|1.2.0|
|vscode-svgviewer|cssho|1.3.0|
|githistory|donjayamanne|0.1.4|
|python|donjayamanne|0.5.5|
|cpptools|ms-vscode|0.9.3|
|vscode-icons|robertohuertasm|4.2.0|
|vim|vscodevim|0.4.10|
|JavaScriptSnippets|xabikos|1.2.0|

---

Steps to Reproduce:

1. example:  ./test/test_target  and ./test/test_source/test_target
2. The action is delete the ./test/test_target/*   then copy ./test/test_source/test_target  when I drag ./test/test_source/test_target to ./test/.  Although it has prompt messge to me. But it is not clear enough that the action is deleted and copy or straight override.  
3. whatever is a bug or suggest for this action. I think that is a very bad experence.

**Comment by bpasero** [comment]
@iamideas to be clear, we are talking about this warning dialog right?

![image](https://cloud.githubusercontent.com/assets/900690/21587467/0e6f37b4-d0dd-11e6-9ff9-78c2cfcf42b1.png)

What would you expect to happen differently?

**Comment by iamideas** [comment]
![default](https://cloud.githubusercontent.com/assets/10566767/21588637/10c63426-d124-11e6-85b3-1bba308eaaf1.PNG)

First, maybe sorry that my english is not good. I will try my best to explain.

For dialog:
My platform language is Chinese. But meaning is same with yours.

For my mind:
I think that the action should be merage.  That mean is If files  is exist in target folder,  replaces it, else copy it to the target folder. For other files  should not move or delete in target folder.
But in my current version, The action likes delete target folder from current path then copy source to the current path.

I hope explain clear for my meaning.
Thanks your work for vs code.

**Comment by iamideas** [comment]
Then I catch that your test it via file. But my test it via folder.

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/1391
