### ISSUE TITLE
Screencast mode regression - always shows all keystrokes

### ISSUE THREAD

**Issue by Krxtopher** [microsoft/vscode#179541]
Does this issue occur when all extensions are disabled?: Yes/No
Yes

- VS Code Version: 1.77.1 
- OS Version: Mac OS 12.6.3

Until recently, it was possible to configure the "screencast mode" settings so that the overlay was only displayed when a keyboard shortcut was used. Now, the overlay shows _every single keystroke_ all the time, and there appears to be no way to change this.

Steps to reproduce:
1. Enable screencast mode by running "Developer: Toggle screencast mode" from the Command Palette.
2. Open settings.
3. Search for "screencast" to filter to just the screencast properties.
4. Try any combination of properties to limit to only showing the overlay when keyboard shortcuts are entered.
5. Try typing code into a file and see that every single key stroke displays in the overlay.

**Comment by gjsjohnmurray** [comment]
According to https://github.com/microsoft/vscode/issues/179096#issuecomment-1497946155 this is as designed. You reported it as a regression. In which version did you get different behaviour?

**Comment by Krxtopher** [comment]
I don't know what version of VS Code this was, but in this screencast recording I made on March 18th you'll see that the overlay only appears when I use keyboard shortcuts, Tab, or Backspace (which is my desired behavior.) I have other videos as well if they would be helpful.

https://user-images.githubusercontent.com/1727699/230823468-4a0200db-4981-4671-886d-d482a8eb1c77.mp4

**Comment by Krxtopher** [comment]
It's possible the _specific individual settings_ referenced by the author of the previous issue is working as designed, but it may be one (or more) of the other Screencast mode settings that is no longer working as designed.

**Comment by jaktestowac** [comment]
> According to [#179096 (comment)](https://github.com/microsoft/vscode/issues/179096#issuecomment-1497946155) this is as designed. You reported it as a regression. In which version did you get different behaviour?

My comment in https://github.com/microsoft/vscode/issues/179096#issuecomment-1503320262
should clarify because I having same problem as @Krxtopher

**Comment by joaomoreno** [comment]
I agree. I suggest having a tri-state setting here:

- Commands only
- Keyboard shortcuts only
- Commands and keyboard shortcuts

PR welcome.

**Comment by weartist** [comment]
I'll resolve this issue

**Comment by weartist** [comment]
hi @joaomoreno , I'd like to ask a small question, which behavior is the command in 'Commands only' you are referring to, is it a single key stroke? I'm afraid I'm misunderstanding, I would change this option to control when the screencast is displayed based on these three options

**Comment by joaomoreno** [comment]
When the user presses a certain key combo, let's say `Ctrl A`, that means `Select all text` when in the editor. If `Commands only` mode is enabled, I would expect only `Select all text` to appear.

**Comment by SpencerRauch** [comment]
This has been driving me wild, I teach at an online bootcamp and showing key presses for shortcuts is helpful, showing every single keystroke is not!

**Comment by zaccrites-intel** [comment]
Surely there is no reason to show *all* keystrokes. We can already see non-shortcut keystrokes-- they appear in the editor window...

**Comment by joaomoreno** [comment]
Going with a full options bag that allows users to mix and match what the keyboard overlay displays:

<img width="736" alt="image" src="https://github.com/microsoft/vscode/assets/22350/d85687c1-b0a0-497f-9007-571586e7d071">

**Comment by clarkio** [comment]
I tested things out with the settings available in the latest release (1.81.0), and I still see ALL keystrokes regardless of whether it's a shortcut/command or not. If I uncheck "Show raw keys" and execute a shortcut or command action, it only shows the name of the command action and doesn't show the keystroke combination to execute it. If I check "Show raw keys" back on, it shows the keystroke combination for commands but will also show general keystrokes when typing.

While it's certainly nice to see the simplified screencast mode keyboard options, I think the reasoning behind this issue is missed and should be re-opened.

**Comment by jaktestowac** [comment]
Simply: we need to present shortcuts but not all keystrokes (and it was working in 1.76.2)

**Comment by SpencerRauch** [comment]
![options](https://github.com/microsoft/vscode/assets/86501404/2eb8c1ac-c03d-49ba-a491-81e609114025)
With these options, no display of commands currently happens.

The only option seemingly working is show raw keys. 

Again, the desire is to be able to only show commands of shortcuts with their command name, as of 1.81.1 this is still not working.

**Comment by oscarlevin** [comment]
I was also disappointed to not be able to show the keys that are part of a command, without also showing all keys (even when typing in the editor).

**Comment by joaomoreno** [comment]
You guys are absolutely right.

**Comment by jaktestowac** [comment]
Tested insiders and problem persist:

Version: 1.83.0-insider (user setup)
Commit: 11bfd76a61a299156a9f3138ecfad70937af3527
Date: 2023-09-21T05:34:38.227Z
Electron: 25.8.1
ElectronBuildId: 23779380
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.22000

"screencastMode.keyboardOptions": {
  "showKeys": false,
  "showCommandGroups": true
}

When typing i.e. CTRL+SHIFT+R (code refactoring in editor) with above settings I cannot get this keys/shortcut displayed. Same as for CTRL + . and so on.

**Comment by gjsjohnmurray** [comment]
@jaktestowac maybe you are seeing #188938

**Comment by jaktestowac** [comment]
@gjsjohnmurray exactly, and as https://github.com/microsoft/vscode/issues/188938 is fixed finally after half year waiting I can get my shortcut displayed without single key logging 😊
