### ISSUE TITLE
FIrst call to vscode.startDebug does not show debug starting indicator (blue line)

### ISSUE THREAD

**Issue by indiejames** [Microsoft/vscode#17952]
- VSCode Version: 1.8.1
- OS Version: OS X 10.12.1 

Steps to Reproduce:

1. Create an extension
2. Add a command that calls 'vscode.startDebug'
3. Call the command while debugging extension
Expected: VS Code shows visual indicator (moving blue line) while debug session starts up
Actual: VS Code starts debug session but never shows indicator
4. Stop debug session and restart by calling command a second time
Visual indicator shows up while debug session is starting.

**Comment by isidorn** [comment]
Can not repro with latest insiders. What I did, I have an extension with the following snippet, I start debugging that extension from vscode and in the new window I trigger my command which triggers vscode.startDebug - I get a nice blue progress line.

Please keep in mind this issue which might be related to your scenario https://github.com/Microsoft/vscode/issues/16752
Please provide more details and I will reopen

```javascript
'use strict';
import * as vscode from 'vscode';

export function activate(context: vscode.ExtensionContext) {

    let disposable = vscode.commands.registerCommand('extension.test', () => {
        vscode.commands.executeCommand('vscode.startDebug');
    });

    context.subscriptions.push(disposable);
}

// this method is called when your extension is deactivated
export function deactivate() {
}
```

**Comment by indiejames** [comment]
I'm still encountering this, even with insiders (January). My exact test steps are as follows:

1. Close VS Code / VS Code Insiders
2.  generate a basic project (this will be the extension that launches the debugger).
```
yo code dtest
```

3. generate a second project to act as the debugged project
```
yo code ntest
```

4. Launch VS Code Insiders and open the first project (dtest)
5. Change the extension.ts file to this

```
'use strict';
import * as vscode from 'vscode';

export function activate(context: vscode.ExtensionContext) {

   let disposable = vscode.commands.registerCommand('extension.sayHello', () => {

        vscode.commands.executeCommand('vscode.startDebug');
    });

    context.subscriptions.push(disposable);
}

export function deactivate() {
}
```
6. Launch the extension (F5) open the second project (ntest).
7. Activate the "hello" command (cmd+alt+p ...)
(Debugger starts with no indicator).
8. Stop the debugger.
9. Reactivate the "hello" command
(Debugger stars with indicator)

**Comment by isidorn** [comment]
Thanks for details, reopening, will investigate this week

**Comment by isidorn** [comment]
We have changed how the initializing state behaves. Your sample should now work.
Please let me know if that is not the case and I will reopen
