### ISSUE TITLE
improving typescript error message formatting: message is printed twice

### ISSUE THREAD

**Issue by SimonSiefke** [microsoft/vscode#179549]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.77.1
- OS Version: Ubuntu 22.10

Steps to Reproduce:

### When an error in tsserver occurs, the error message is printed twice: 

![typescript-message](https://user-images.githubusercontent.com/23744935/230761494-3d882d46-4fc8-47b7-991b-16797c13f6d5.png)

console.ts:137 [Extension Host] Error processing request. Debug Failure. False expression: Non-string value passed to `ts.resolveTypeReferenceDirective`, likely by a wrapping package working with an outdated `resolveTypeReferenceDirectives` signature. This is probably not a problem in TS itself.
Error: Debug Failure. False expression: Non-string value passed to `ts.resolveTypeReferenceDirective`, likely by a wrapping package working with an outdated `resolveTypeReferenceDirectives` signature. This is probably not a problem in TS itself.

### Minor improvement: The error message is printed once like this:

console.ts:137 [Extension Host] Error processing request. Debug Failure. False expression: Non-string value passed to `ts.resolveTypeReferenceDirective`, likely by a wrapping package working with an outdated `resolveTypeReferenceDirectives` signature. This is probably not a problem in TS itself.

**Comment by mjbvz** [comment]
Closing as these are diagnostic messages, not user facing one
