### ISSUE TITLE
vscode + python virtual environment + mac terminal 

### ISSUE THREAD

**Issue by Tset-Noitamotua** [Microsoft/vscode#17950]
- VSCode Version: 1.8.1
- OS Version: OS X El Capitan 10.11.6

When launching vscode from terminal with command `code` while a virtual python environment is activated (e.g. `workon myenv`) it would be nice if vscode uses the same virtualenv in it's integrated terminal.

Steps to Reproduce:

1. open terminal
2. activate a virtual python environment (e.g. `workon DJANGO` -->  magic from virtualenvwrapper)
3. call `code`
4. in vscode open integrated terminal
5. with `pip list` check in which python environment you are

NOW: vscode is in default python env
BETTER: use virtualenv from which vscode was started

**Comment by spywhere** [comment]
I don't if this help or even related to the issue at all. But VSCode provide option for you to change to your custom terminal (`"terminal.external.osxExec"`) or even your own shell (`terminal.integrated.shell.osx`).

**Comment by Tyriar** [comment]
The terminal should inherit VS Code's env, I just tested it and it's working fine. Could you do the following to determine whether your issue is related to workon (perhaps it's not exporting?):

```
export TEST=1
code
```

Open the terminal and check the output of `echo $TEST`

**Comment by Tset-Noitamotua** [comment]
@Tyriar you are right. It works!

![image](https://cloud.githubusercontent.com/assets/5635462/21581686/049afbf6-d03d-11e6-8f7e-eb9aa56fa8ba.png)


Yet I found that it is documented [here](https://github.com/DonJayamanne/pythonVSCode/wiki/Python-Path-and-Version#option-2-activate-the-virtual-environment-from-your-terminalcommand-window-and-then-launch-vs-code)

> 1. Ensure none of the Python paths are configured in the settings.json file (leave them to their defaults).
> 2. Open your terminal (command) window and activate the relevant Python environment. Close all instances of VS Code.
> 3. Next, launch VS Code from that same terminal (command window) session
    ```
    (venv) ter@minal:~$ code .
    ```
    
or without period works, too
    ```
    (venv) ter@minal:~$ code
    ```

I guess issue in my case was that I had  manually set `"python.pythonPath": path_to_my_env` in settings.json at workspace level. I removed that setting and now it works.

I have a little enhancement suggestion though:
The prompt of integrated terminal does not show that  one have a virtual env activated.

And `workon` does not work (but that's another issue I guess):
![image](https://cloud.githubusercontent.com/assets/5635462/21581697/43a31d92-d03d-11e6-8993-c974dde8900d.png)

**Comment by Tyriar** [comment]
workon must not be on the path then. You can find out where it is with `whereis workon`, and then figure out why that directory is not in the path.

**Comment by Tset-Noitamotua** [comment]
hhhmm ... strange. `workon` seems to be on path but `whereis workon` gives nothing:

```
MyMac@MyMac[~/_GITHUB/_learnpython]$ workon
FAB
FLASK_BOOTSTRAP
MarkDown-RF
OPENSHIFT_DJANGO
PYTHON_VIMRC
PYVIM
SUPERSET
WATCHDOG
WHARFEE
MyMac@MyMac[~/_GITHUB/_learnpython]$ whereis workon
MyMac@MyMac[~/_GITHUB/_learnpython]$ 
```

**Comment by Tyriar** [comment]
Maybe it's an alias or something? This is very likely due to how workon works then, not with vscode. I'm going to close this off for now, let me know if you think there's an issue with vscode.
