### ISSUE TITLE
Shell integration failed to activate

### ISSUE THREAD

**Issue by ahmedelmahi** [microsoft/vscode#179529]
Type: <b>Bug</b>

Hi,

I just downloaded VS Code. When I try and follow the simple get started tutorial I get an error message when I try to run my file. The error message is copied below.

Hope you can help

Thanks,

Ahmed

JavaScript Debug Terminal

Process ID (PID): 3748

Command line: C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe '-noexit' '-command' 'try { . "c:\Users\ahmed\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\contrib\terminal\browser\media\shellIntegration.ps1" } catch {}'

Shell integration failed to activate

The following extensions have contributed to this terminal's environment:

Git

VS Code version: Code 1.77.1 (b7886d7461186a5eac768481578c1d7ca80e2d21, 2023-04-04T23:21:11.906Z)
OS version: Windows_NT x64 10.0.19045
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700T CPU @ 2.90GHz (8 x 2904)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|7.83GB (0.98GB free)|
|Process Argv|--crash-reporter-id deb1a435-e28e-4475-a9fc-6478b3a7007a|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2023.6.0
vscode-pylance|ms-|2023.4.10
jupyter|ms-|2023.3.1000892223
jupyter-keymap|ms-|1.1.0
jupyter-renderers|ms-|1.0.15
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-slideshow|ms-|0.1.5
remote-wsl|ms-|0.77.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscorecescf:30445987
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
nodejswelcome1:30587005
2e4cg342:30602488
pyind779:30671433
f6dab269:30613381
pythonsymbol12:30671437
vsccsb:30705552
pythonb192cf:30669361
defaultazurewalk:30687958
pythonms35:30701012
pythonclientmv:30708685

```

</details>

**Comment by PickleChum** [comment]
Hi Ahmed,

Here's a summarized list of steps to help you resolve the issue

    Ensure you have the latest version of PowerShell installed. Download it from [here](https://aka.ms/powershell-release?tag=stable) if needed.

    In VS Code, go to "Settings" (click on the gear icon or use Ctrl+,) and search for "terminal.integrated.shell".

    Update the "Terminal > Integrated > Shell: Windows" setting to the path of the newly installed PowerShell executable (e.g., C:\Program Files\PowerShell\7\pwsh.exe).

    Save the settings and restart VS Code.

    If the issue persists, try disabling all extensions temporarily to check if any extension is causing the problem. You can do this from the "Extensions" view (click on the square icon or use Ctrl+Shift+X). Restart VS Code and see if the issue is resolved. If it is, re-enable the extensions one by one to identify the problematic one.

I hope these steps help you resolve the issue.

**Comment by ahmedelmahi** [comment]
Hi,

It now says "Shell integration activated" but I do not get any output in the Debug Console.

I am trying to run a simple js file that contains the following:
console.log('-----');
console.log('Rise & Shine!');
console.log('-----');

**Comment by PickleChum** [comment]
Hi Ahmed,

I'm glad to hear that the shell integration issue is resolved. Now, let's try to troubleshoot the problem with the Debug Console. Please follow these steps:

    First, ensure that you have the necessary extensions installed for JavaScript development. The most important one is the "JavaScript Debugger" extension, which should be built-in. You can verify this by going to the "Extensions" view (Ctrl+Shift+X) and searching for "JavaScript Debugger".

    Next, create a launch configuration file for your project. To do this, click on the "Run" icon in the left sidebar (or use Ctrl+Shift+D). Then, click on "create a launch.json file" and select "Node.js" as the environment.

    In the newly created launch.json file, make sure you have a configuration similar to this:

json

{
  "version": "0.2.0",
  "configurations": [
    {
      "type": "node",
      "request": "launch",
      "name": "Launch Program",
      "skipFiles": ["<node_internals>/**"],
      "program": "${workspaceFolder}/path/to/your/js/file.js"
    }
  ]
}

Replace path/to/your/js/file.js with the correct path to your JavaScript file.

    Save the launch.json file.

    With the configuration in place, go back to the "Run" view, and you should see the "Launch Program" configuration in the dropdown menu. Select it, and click the green "Run" button (or press F5). This should start the debugger, and you should see the output in the "Debug Console".

If you still don't see any output in the Debug Console, please let me know, and we can look into other potential solutions.

**Comment by PickleChum** [comment]
Hi Ahmed,

I'm glad to hear that the shell integration issue is resolved. Now, let's try to troubleshoot the problem with the Debug Console. Please follow these steps:

1. **Ensure JavaScript Debugger is installed**: Go to the "Extensions" view (`Ctrl+Shift+X`) and search for "JavaScript Debugger".

2. **Create a launch configuration**: Click on the "Run" icon in the left sidebar (or use `Ctrl+Shift+D`). Click on "create a launch.json file" and select "Node.js" as the environment.

3. **Update the launch.json file**: Make sure you have a configuration similar to this:

   ```json
   {
     "version": "0.2.0",
     "configurations": [
       {
         "type": "node",
         "request": "launch",
         "name": "Launch Program",
         "skipFiles": ["<node_internals>/**"],
         "program": "${workspaceFolder}/path/to/your/js/file.js"
       }
     ]
   }
  ```
4. Replace `path/to/your/js/file.js` with the correct path to your JavaScript file.

5. **Save the launch.json file.**

6. **Run the debugge**r: Go back to the "Run" view, and you should see the "Launch Program" configuration in the dropdown menu. Select it, and click the green "Run" button (or press F5). This should start the debugger, and you should see the output in the "Debug Console".

If you still don't see any output in the Debug Console, please let me know, and we can look into other potential solutions.

**Comment by ahmedelmahi** [comment]
Thanks - now I am getting the following error

![image](https://user-images.githubusercontent.com/82056511/230733535-76bc6f58-ed74-41d1-9826-646d57f9c8ff.png)

In my launch.json file I have the following. I figure since I am already in my workspaceFolder - I only need to give it my filename - correct?

{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "node",
            "request": "launch",
            "name": "Launch Program",
            "skipFiles": ["<node_internals>/**"],
            "program": "${workspaceFolder}/jsSample.js"
        }
    ]
}

**Comment by PickleChum** [comment]
Hi Ahmed,

I apologize for the delay in my response. Let's address the new issue you're facing.

The error you're encountering suggests that Node.js might not be installed or its path is not set correctly in your system. Please follow these steps to resolve the issue:

1. **Install Node.js**: If you don't have Node.js installed, download and install it from [here](https://nodejs.org/en/download/).

2. **Verify Node.js installation**: Open a new terminal/command prompt and run `node -v` to check if Node.js is installed correctly. You should see the installed version number.

3. **Add Node.js to PATH (if needed)**: If the previous step did not show the version number, it's likely that Node.js is not added to your system's PATH. To add it, follow these steps:

   - For Windows:
     1. Press `Win + X` and select "System".
     2. Click on "Advanced system settings" on the right side.
     3. Click on the "Environment Variables" button.
     4. In the "System variables" section, find the "Path" variable and click "Edit".
     5. Click "New" and add the path to the Node.js installation folder (e.g., `C:\Program Files\nodejs`).
     6. Click "OK" to save the changes and close all the dialogs.

   - For macOS/Linux:
     1. Open a terminal.
     2. Run the following command (replace `/path/to/nodejs` with the actual path to the Node.js installation folder):

        ```bash
        echo 'export PATH=$PATH:/path/to/nodejs' >> ~/.bashrc
        ```

     3. Restart your terminal.

4. **Restart VS Code**: Close and reopen VS Code to ensure that the new environment variables are loaded.

5. **Check the launch.json file**: Your current `launch.json` configuration looks correct, as long as `jsSample.js` is located in the root of your workspace folder.

After completing these steps, try running the debugger again. If the issue persists, please let me know and we can explore other solutions.

Best regards,

**Comment by ahmedelmahi** [comment]
This works now. Thanks!

**Comment by PickleChum** [comment]
No problem, have a great day!

**Comment by uchenna2023** [comment]
please i need help am working on a react app for some while as a beginner. I have been using npm start to start my app it has being working fine. Just yesterday i tried practicing what i learnt on the creating a backend. After several attempt to set up a mern server that fail, when i tried running {npm start} to start my frontend the terminal when silent. 

When i tried hovering the pointer on powershell this is message am getting

shell integration activated  (the following extension has contributed to this terminal environment) : 'Git' 

after trying you suggestion above.

**Comment by uchenna2023** [comment]
Here is what i have tried maybe am still doing wrong please i need assistant. thanks

 "version": "0.2.0",
    "configurations": [
        {
            "type": "node",
            "request": "launch",
            "name": "Launch Program",
            "skipFiles": [
                "<node_internals>/**"
            ],
            "program": "${workspaceFolder}/C:/Users/pc/Desktop/projects/my-second-repo/lit_lemon/litle-lemon/src/Components/styles/ChicagoSection.js"
        }
    ]
}

**Comment by uchenna2023** [comment]
Finally i have resolved it. Using the node installation option. thanks alot
