### ISSUE TITLE
WSL2 - Unable to get any intellisense working for typescript-based project (all of a sudden)

### ISSUE THREAD

**Issue by teodosii** [microsoft/vscode#179589]
Does this issue occur when all extensions are disabled?: YES!

- VS Code Version: 1.77.1 (user setup)
- OS Version: Windows 11

Steps to Reproduce:

I'm using Windows 11 with WSL2 enabled. VSCode is installed on Windows, I mostly have ESLint, Prettier and Typescript Nightly Build extensions, but I tried disabling all my extensions and still run into the issue.

All of a sudden I no longer have intellisense, auto-imports not working, react props suggestions based on types no longer working. The only thing working is highlighting :)

I tried updating VSCode but I'm at the latest version, tried reinstalling it, downgraded TypeScript version, running out of solutions. Anyone know what it could be?

**Important**: No matter if I run vscode from WSL or from Windows, I still get the same end result

**Comment by mjbvz** [comment]
Did you perhaps disable the building JS/TS extension? Search `@builtin typescript` in the extensions vide to check this

**Comment by ferminarellanoSPF** [comment]
Hey, try downgrading vscode. 1.77 broke dev containers apparently. https://github.com/microsoft/vscode/issues/179366

**Comment by teodosii** [comment]
@mjbvz one disabled, one not installed
![image](https://user-images.githubusercontent.com/40542072/231085805-dc858a5e-e94f-4949-81a8-7b5caaafc30a.png)

@ferminarellanoSPF thanks for the tip but it doesn't work for me. I tried to 1.70.0 and 1.70.2 but no luck
![image](https://user-images.githubusercontent.com/40542072/231086766-8359d3cc-b1b4-4f1b-9321-39be8a0cf64e.png)

**Comment by teodosii** [comment]
@mjbvz this all happened all of a sudden, I didn't upgrade/install any additional extension in the past days. No specific Windows/WSL update either
