### ISSUE TITLE
What happened to the icon of the resource manager on the left side of vscode

### ISSUE THREAD

**Issue by wangshunshun** [microsoft/vscode#179586]
Does this issue occur when all extensions are disabled?: Yes

1. What happened to the icon of the left resource manager
<img width="722" alt="image" src="https://user-images.githubusercontent.com/26266527/230836559-c33cf31d-a337-4c42-8a5d-be59ae970869.png">

**Comment by lramos15** [comment]
You must've moved the explorer

Do `CTRL / CMD + SHIFT + P -> Reset View Locations`

**Comment by Aburupa1389** [comment]
أرسل gasem alotef إليك رسالة إلكترونية في وضع الحفاظ على السرّية في Gmail:

[image: شعار Gmail]Re: [microsoft/vscode] What happened to the icon of the resource manager on the left side of vscode (Issue #179586) <https://confidential-mail.google.com/msg/AA2T6PaMKPZcM-b6vWh149rP4o91v58b91O6qzGfvuJplsf2kRZLLgAuXu59FIJuP3NGjBdHFrRrLaCGM9ZLLIcKDikh4-1piueNzsAWOw0voH898wtjpGBj02RKnh7DZN0Z6PqR-H7VGTGtDPZmv-9n6MjarYcr7fIcou0dg3RPwU7YKZ3G6Ibm9y8V1ytAxjzEjRZgJ22cXfE9IhJJ>

تم إرسال هذه الرسالة يوم 11‏/04‏/2023 الساعة 8:19:34 م غرينتش-7
يمكنك فتحه بالنقر على الرابط أدناه. ولا يعمل هذا الرابط إلا مع ***@***.***

عرض الرسالة الإلكترونية <https://confidential-mail.google.com/msg/AA2T6PaMKPZcM-b6vWh149rP4o91v58b91O6qzGfvuJplsf2kRZLLgAuXu59FIJuP3NGjBdHFrRrLaCGM9ZLLIcKDikh4-1piueNzsAWOw0voH898wtjpGBj02RKnh7DZN0Z6PqR-H7VGTGtDPZmv-9n6MjarYcr7fIcou0dg3RPwU7YKZ3G6Ibm9y8V1ytAxjzEjRZgJ22cXfE9IhJJ>

يمنحك "الوضع السري في Gmail" مزيدًا من التحكُّم في الرسائل التي تُرسِلها. ربما اختار المُرسِل تحديد وقت انتهاء الصلاحية أو إيقاف الطباعة أو إعادة توجيه رسالة أو تتبّع الوصول إلى هذه الرسالة. مزيد من المعلومات <https://support.google.com/mail/answer/7674059>
Gmail: خدمة بريد إلكتروني مُقدَّمة من Google
يخضع الاستخدام لـ سياسة خصوصية Google <https://myaccount.google.com/privacypolicy?hl=ar>
Google LLC, 1600 Amphitheatre Parkway, Mountain View, CA 94043, USA
لقد استلمت هذه الرسالة لأن أحدهم أرسل إليك رسالة إلكترونية في وضع الحفاظ على السرّية في Gmail.
[image: شعار Google]

**Comment by Aburupa1389** [comment]
Your Google verification code is 077759
