### ISSUE TITLE
VS Code is broken encoding some strings files

### ISSUE THREAD

**Issue by readingsnail** [Microsoft/vscode#17954]
- VSCode Version: 1.8.1(1.8.1) - ee428b0eead68bf0fb99ab5fdc4439be227b6281
- OS Version: macOS 10.12.2

Steps to Reproduce:

1. i switching textwrangler to vscode, it's really awesome, but some problem is here...
2. in my case, please download zip files. in vscode is broken, but textwrangler is not broken. i don't what is happen.
3. but YOU ARE AWESOME!!!

<img width="938" alt="in textwrangler" src="https://cloud.githubusercontent.com/assets/1904967/21575136/491d2f8a-cf46-11e6-82d9-9ace4973d445.png">

![vscode](https://cloud.githubusercontent.com/assets/1904967/21575135/491c9e26-cf46-11e6-9b14-b68224acfe30.png)

[Localizable.strings.zip](https://github.com/Microsoft/vscode/files/679405/Localizable.strings.zip)

**Comment by Spown** [comment]
I see the same thing in notepad++. you have clearly problems with encoding in textwrangler and/or with macos. Vscode has nothing to do with this.

**Comment by rogersachan** [comment]
@Spown `.strings` files are UTF-16, so does that have anything to do with it?

**Comment by Spown** [comment]
@rogersachan in both screenshots the files seem to be utf-8. The file contents looks very differently from that XML staff - maybe its some sort of shortcut file?

**Comment by spywhere** [comment]
The file provided above is in fact a plist file with `.strings` extension. Hence the encoding is not corrected.

**Comment by bpasero** [comment]
The file from the screenshot and the attached file do not seem to be the same.

**Comment by spywhere** [comment]
@bpasero It is the same, just a different representation. Here I renamed the file to "Localizable.plist" and quick look at it...

![screen shot 2560-01-02 at 20 12 14](https://cloud.githubusercontent.com/assets/1087399/21589765/cad8862c-d127-11e6-98d1-45e548caee10.png)

**Comment by bpasero** [comment]
The file is likely not UTF-8, otherwise it would display properly. Try configuring it to the encoding it was saved.
