### ISSUE TITLE
Cannot sign a git commit with signing key which has a passphrase

### ISSUE THREAD

**Issue by Paper-Folding** [microsoft/vscode#179517]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.77.1 ( b7886d74 )
- Git for Windows 2.40.0
- OS Version: Windows 10 22H2 19045.2728

Steps to Reproduce:

1. Create a ssh key with passphrase and add it to git so that all commits are signed by it if "-S" switch is enabled while using git.  
2. Open vscode global settings.json, set `"git.enableCommitSigning": true`  
3. Stage and commit try to use vscode for any repositiory via clicking "Commit" button:  
![image](https://user-images.githubusercontent.com/49343539/230703937-9af90425-9edb-4b78-97f2-33e2abeeb7df.png)
4. An error occured:  
![image](https://user-images.githubusercontent.com/49343539/230703955-d37bab0a-ab0e-4acf-b9de-883a8c5708f4.png)
5. The error said:  
```log
TypeError: Cannot read properties of undefined (reading 'replace')?
    at g:\Microsoft VS Code\resources\app\extensions\git\dist\askpass-main.js:1:1665?
    at g:\Microsoft VS Code\resources\app\extensions\git\dist\askpass-main.js:1:1922?
    at g:\Microsoft VS Code\resources\app\extensions\git\dist\askpass-main.js:1:1938?
    at Object.<anonymous> (g:\Microsoft VS Code\resources\app\extensions\git\dist\askpass-main.js:1:2044)?
    at Module._compile (node:internal/modules/cjs/loader:1165:14)?
    at Module._extensions..js (node:internal/modules/cjs/loader:1220:10)?
    at Module.load (node:internal/modules/cjs/loader:1035:32)?
    at Module._load (node:internal/modules/cjs/loader:876:12)?
    at c._load (node:electron/js2c/asar_bundle:5:13343)?
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)?
Load key "C:\\Users\\[my user name]\\.ssh\\id_ed25519": incorrect passphrase supplied to decrypt private 
fatal: failed to write commit object
```

What is expected  
VSCode should prompt me to enter passphrase to continue.  

Trivia  
`git commit -S -m "fix sth"` can still be used normally

**Comment by stevehipwell** [comment]
Same here.

**Comment by lszomoru** [comment]
At the moment VS Code only support signing commits with a GPG key and we will be looking at adding support for SSH keys as well.

**Comment by Thibibi** [comment]
Different issue but probably the same cause, I cannot git push with the button (the terminal command git push does the job however).
My issue #182123 was merged here.

**Comment by DreamHollow** [comment]
Confirm that this bug still exists in both Linux and Windows versions.

Unknown what specifically creates this error.

Steps to reproduce:
Set up SSH key.
Configure SSH key for GitHub use following GitHub protocols for SSH key generation (with password.)
Configure git settings via terminal or CMD line, make sure SSH commits are set to always sign on commit.
Make sure that git credentials are accepted through normal terminal means: Git Bash or Powershell.
Provide SSH details in 'config' file for Linux / Windows, make sure to include direct path to SSH file.
Verify that normal commits through terminal settings work as expected, then attempt to use VSCode built in git handling.

Expected result:
VSCode allows git modifications after asking for credentials and confirming password.

Actual result:
VSCode locks up and throws error stating "askpass-main.js" did not function correctly.

**Comment by lszomoru** [comment]
This has been fixed in the latest VS Code Insiders release. 
Could anyone who reported this try it out and let me know if the issue still occurs. Thanks!

**Comment by kosratdev** [comment]
Same here, after I updated my MacBook Pro (M1 Pro) to Sequoia 15.3.2.

**Comment by DrinkingJuice** [comment]
I have same problem, my device is mac M3 air

**Comment by ArcadeArchie** [comment]
Seems to be broken again as of version 1.103
> Version: 1.103.0 (user setup)
Commit: e3550cfac4b63ca4eafca7b601f0d2885817fd1f
Date: 2025-08-06T21:40:10.271Z
Electron: 37.2.3
ElectronBuildId: 12035395
Chromium: 138.0.7204.100
Node.js: 22.17.0
V8: 13.8.500258-electron.0
OS: Windows_NT x64 10.0.19045
```
error: Missing or invalid credentials.
Error: Bad status code: 500
    at ClientRequest.<anonymous> (c:\Users\user\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\git\dist\askpass-main.js:1:2925)
    at Object.onceWrapper (node:events:633:26)
    at ClientRequest.emit (node:events:518:28)
    at HTTPParser.parserOnIncomingClient (node:_http_client:716:27)
    at HTTPParser.parserOnHeadersComplete (node:_http_common:117:17)
    at Socket.socketOnData (node:_http_client:558:22)
    at Socket.emit (node:events:518:28)
    at addChunk (node:internal/streams/readable:561:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:512:3)
    at Readable.push (node:internal/streams/readable:392:5)
Load key "C:/Users/user/.ssh/id_ed25519": incorrect passphrase supplied to decrypt private key?
```

**Comment by Thibibi** [comment]
I have never seen it work, to my knowledge. I test from time to time with the button (it fails), and then I use the git push command (it works after password entry)

**Comment by CybCom** [comment]
Same issue with 1.103.1

**Comment by zch9241** [comment]
same issue with 1.103.1

**Comment by stevehipwell** [comment]
@Thibibi this had been working correctly for a while and was broken by the `1.103.0` release.

**Comment by lszomoru** [comment]
A fix for this issue is available in today's VS Code Insiders and I am looking to see if there is any upcoming recovery release.
