### ISSUE TITLE
filewatchers on vscode.workspace convert windows drive letters to lowercase

### ISSUE THREAD

**Issue by c3-WesleyPickering** [microsoft/vscode#179623]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.77.1
- OS Version: Microsoft Windows 11 Pro, 10.0.22621

Steps to Reproduce:

1. use vscode.workspace.createFileSystemWatcher() to create a filewatcher
2. Trigger the filewatcher with a path inside of a drive that uses a uppercase letter (C:/<path>)

I would expect the path to maintain the drive uppercase, but the event comes in with (c:/<path>)

**Comment by bpasero** [comment]
This is a consequence of our `Uri` implementation that normalizes all file paths to lowercase drive letters. You should not depend on the casing of the drive letter but consider both the same. For display purposes however it should appear as uppercase to the user.
