### ISSUE TITLE
The JS/TS language service immediately crashed five times

### ISSUE THREAD

**Issue by awhittier-cribl** [microsoft/vscode#179641]
Type: <b>Bug</b>

I get the error message "The JS/TS language service immediately crashed 5 times. The service will not be restarted." the first time I open a typescript file in my project, if I open my workspace as a remote WSL workspace. If I open the workspace as a local workspace on my laptop, I do not see the error. I still see the problem if I disable all extensions.

I tried changing the typescript version to the one referenced from my workspace (4.8.4 instead of 5.0.2), which apparently helped other people, but it didn't help me.

VS Code version: Code 1.77.1 (b7886d7461186a5eac768481578c1d7ca80e2d21, 2023-04-04T23:21:11.906Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: No
Remote OS version: Linux x64 5.15.90.1-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|12th Gen Intel(R) Core(TM) i9-12900H (20 x 2918)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.67GB (8.13GB free)|
|Process Argv|--crash-reporter-id 3b9c01c6-cf5c-4880-9889-98e9639a0f7d|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 5.15.90.1-microsoft-standard-WSL2|
|CPUs|12th Gen Intel(R) Core(TM) i9-12900H (20 x 2918)|
|Memory (System)|15.46GB (7.73GB free)|
|VM|0%|
</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
remote-wsl|ms-|0.77.0
markdown-mermaid|bie|1.18.1
vscode-eslint|dba|2.4.0
gitlens|eam|13.5.0
prettier-vscode|esb|9.10.4
vscode-docker|ms-|1.24.0
memento-inputs|spa|1.0.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
vscccc:30610679
nodejswelcome1:30587005
3biah626:30602489
pyind779:30671433
89544117:30613380
pythonsymbol12:30671437
6233i204:30672705
vsccsb:30705552
defaultazurewalk:30687958
pythonms35:30701012

```

</details>

**Comment by mjbvz** [comment]
Please try collecting the TS Server log from the crashed instance:

1. Set `"typescript.tsserver.log": "verbose"`
1. Restart VS Code and reproduce the problem
1. Open the `TypeScript` section of the output panel
1. At the very top, find the first line that prints to path to the semantic error log file. It should look something like:

    ```
    [Info  - 19:54:59.247] <semantic> Log file: /Users/matb/Library/Application Support/Code - Insiders/logs/20200213T104930/exthost55/vscode.typescript-language-features/tsserver-log-ZT2zau/tsserver.log
    ```

    That file contains the typescript logs.

Look through that log file for the first error or stack trace you see. If you can share the log, I can also take a look to see if anything stands out

 > **⚠️Warning:** The TypeScript log may include information from your workspace, including file paths and source code. If you have any concerns about posting this publicly on Github, just let me know and we can arrange something else. On our side, we only use these logs to investigate issues like this

**Comment by awhittier-cribl** [comment]
I'm not sure why it didn't appear to be working yesterday, but after restarting my laptop this morning with this in my user config file, everything seems fine:

```
"typescript.tsdk": "./node_modules/typescript/lib"
```

For now things seem to be working so I'll just close this - thanks for the assistance!
