### ISSUE TITLE
Show 'Connect To Tunnel' on Welcome page in vscode.dev

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode#179687]
`Connect To Tunnel... should be prominently on the https://vscode.dev/ welcome page.

We want to explore if it's even possible to show the available tunnel names (if logged in)

**Comment by bhavyaus** [comment]
We now display "Connect via Remote Tunnels" in the start list entry on [insiders.vscode.dev](https://insiders.vscode.dev//)

<img width="989" alt="image" src="https://github.com/microsoft/vscode/assets/25044782/a8e3b862-3cbc-4058-bcd6-b9a17b417561">

**Comment by bhavyaus** [comment]
> We want to explore if it's even possible to show the available tunnel names (if logged in)

Once a workspace has been opened via tunnel, it would show up in the `Recents` list anyway and would be accessible from the Welcome Page. Should we still consider adding quick links to the existing remote tunnel connections? If yes, we could consider displaying existing tunnels under the `Recents` tab. We would need to ensure we pick the most recently used tunnels (or some other criteria) to only display a pre-determined number of tunnels in the list.

I also considered adding a new `Connections` list on the Welcome page to display remote connection links, but I worry that the welcome page might become too cluttered (with the addition of featured extension)

**Comment by aeschli** [comment]
Thanks for adding `Connect via Remote Tunnels`, that's great.
What about naming it `Open Tunnel...` (to match the other open command) or `Connect to Tunnel..` (to match the name of the command in the remote menu)

**Comment by aeschli** [comment]
I was think that behind `Connect to Tunnel...` we could show a list of tunnel names, e.g. `Office PC`, 'Surface` of the tunnels that are currently available. 
`Connect to Tunnel...  Office PC Surface`

My guess is that for a given user that should not be more than 2 or 3 entries. Listing them in Recent wold also work, but it's not exactly a recent entry.

It was just an idea, of course it's not fitting right in the current getting started framework.

**Comment by bhavyaus** [comment]
I'll rename the command to `Open Tunnel...` as you suggested.
We could track usage of the command for now and later decide if it would be worthwhile to consider showing other remotes? (not just open tunnels) on the welcome page. For now, the list of available tunnels and their status is only one click away from the welcome page. 
<img width="1036" alt="image" src="https://github.com/microsoft/vscode/assets/25044782/1c2f34a3-4ce3-4730-ade2-f7018cbc55f3">

**Comment by aeschli** [comment]
> We could track usage of the command for now and later decide if it would be worthwhile to consider showing other remotes? (not just open tunnels) on the welcome page.

Sounds good! IMO we want to keep the open list short and focus on the command that are most useful on the given platform. For the web that's open a tunnel or a remote repo.

**Comment by bhavyaus** [comment]
> BTW, the welcome page now has hardcoded knowledge about the remote hub and tunnels extensions. It would be better if the list of additional open entries comes from `product.json`. Other products that are based on `code oss` might not want such open commands.
> 
> I think with such a list (label, command id), you can also avoid special handling for the tunnel extension in `remoteStartEntry`

Labels coming from product.json would not be localized. I'll create a debt item to have it be setup for localization before refactoring since the remoteHub command and labels have existed in OSS for a while and I don't want to break that localization

**Comment by aeschli** [comment]
Closing as fixed
