### ISSUE TITLE
remote wsl plugin "Cannot read properties of undefined (reading 'name')"

### ISSUE THREAD

**Issue by John-zhan** [microsoft/vscode#179660]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.77.1 (user setup)
- OS Version: windows 11 22H2 22621.1485
- wsl2 distro： ubuntu20.04.6 LTS
- vscode wsl plugin version：ms-vscode-remote.remote-wsl v0.77.0

Steps to Reproduce:

1. open the vscode, and select the wsl target.
2. I get a prompt "Cannot read properties of undefined (reading 'name')"

**Comment by John-zhan** [comment]
But my ubuntu20.04.6 wsl can execute the "code .", to open the vscode.

**Comment by aeschli** [comment]
You run the command `Connect to Distro...` ? Otr is it in the remote explorer?
Can you find more on the error in the Dev tools console (e.g a full stacktrace)

**Comment by John-zhan** [comment]
no command, just use the remote explorer to get the wsl target.
yeah, in the terminal, use wsl command to start a distro, is fine.
how to get error in the DEV tools console, I don't understand.
what command I don't know, could U be more specifics about the command. I just wanna to known what command do we get in the vscode to open a wsl target.

**Comment by John-zhan** [comment]
the error showing before

**Comment by aeschli** [comment]
I think I found the issue. The next version will have the fix.
In the meantime, use the `WSL: Connect to WSL using Distro...` command

**Comment by John-zhan** [comment]
versioin: 1.77.3 (user setup)
commit: 704ed70d4fd1c6bd6342c436f1ede30d1cff4710
date: 2023-04-12T09:16:02.548Z
Electron: 19.1.11
Chromium: 102.0.5005.196
Node.js: 16.14.2
V8: 10.2.154.26-electron.0
OS: Windows_NT x64 10.0.22621
sandbox: No

released
2019/5/3 02:40:03
last release
2023/4/14 02:04:35
last update
2023/4/14 15:05:39
identifier
ms-vscode-remote.remote-wsl

just update but the problem still

**Comment by John-zhan** [comment]
excute this command "WSL: Connect to WSL using Distro...", left bottom says this:
**"No WSL distros found. New distros can be installed from the Microsoft Store."**

**Comment by aeschli** [comment]
So your distro name has braces `[`/`]` in it? Did you install this distro in a special way?

**Comment by John-zhan** [comment]
yeap, it's on my D: volume

**Comment by John-zhan** [comment]
I move it from default C: volume 2 D: volume

**Comment by John-zhan** [comment]
can U give me some advices, other than reinstall the distro from windows
store

**Comment by aeschli** [comment]
> yeap, it's on my D: volume

How is that related to the distro? Did you create the distro in a special way?

Another question: can you run `wsl -e bash -c "env | grep WSL"` from the Windows command prompt?

**Comment by John-zhan** [comment]
> wsl -e bash -c "env | grep WSL"
WSL2_GUI_APPS_ENABLED=1
WSL_DISTRO_NAME=[Ubuntu-20.04]
NAME=nathnialWSL
WSL_INTEROP=/run/WSL/114_interop
WSLENV=WT_SESSION::WT_PROFILE_ID

**Comment by John-zhan** [comment]
> > yeap, it's on my D: volume
> 
> How is that related to the distro? Did you create the distro in a special way?
> 
> Another question: can you run `wsl -e bash -c "env | grep WSL"` from the Windows command prompt?

hello, up here is my cmd prompt outputs

**Comment by John-zhan** [comment]
> yeah of cource, I get this output:
> 
> > wsl -e bash -c "env | grep WSL"
> > WSL2_GUI_APPS_ENABLED=1
> > WSL_DISTRO_NAME=[Ubuntu-20.04]
> > NAME=nathnialWSL
> > WSL_INTEROP=/run/WSL/114_interop
> > WSLENV=WT_SESSION::WT_PROFILE_ID

@aeschli aha I need UR help

**Comment by aeschli** [comment]
Currently, the WSL extension does not support distro names with `[` or `]` in the name.
Can you explain how you ended up with a distro of that name?
Did you use `--import`?

**Comment by aeschli** [comment]
@craigloewen-msft Do you have information on what the valid characters in distros names are?

**Comment by John-zhan** [comment]
> Currently, the WSL extension does not support distro with `[` or `]` in the name. Your distro is called `[Ubuntu-20.04]` Can you explain how you ended up with a distro of that name? Did you use `--import`?

nop just edit the regedit of windows. Now this problem done, I change the name HK_CU_SOFTWARE/Microsoft/Windows/CurrentVersion/Lxss in registration form. "[]" is the registration name of HK_CU_SOFTWARE/Microsoft/Windows/CurrentVersion/Lxss.

**Comment by John-zhan** [comment]
Thanks for UR help. My vscode now can find the distro. God bless U.

**Comment by aeschli** [comment]
@John-zhan Ok, so you initially also added the characters that way?

**Comment by John-zhan** [comment]
yes
