### ISSUE TITLE
Relative Paths Not Supported In "sourceFileMap" in launch.json

### ISSUE THREAD

**Issue by tparikka** [microsoft/vscode#179629]
Does this issue occur when all extensions are disabled?: Yes

- VS Code / OS Version: 
Version: 1.77.1 (user setup)
Commit: b7886d7461186a5eac768481578c1d7ca80e2d21
Date: 2023-04-04T23:21:11.906Z
Electron: 19.1.11
Chromium: 102.0.5005.196
Node.js: 16.14.2
V8: 10.2.154.26-electron.0
OS: Windows_NT x64 10.0.19045
Sandboxed: No

Steps to Reproduce:

1. Set a relative path in the sourceFileMap of launch.json like so:

```json
{
            "name": "Docker .NET Attach (WebUI)",
            "type": "docker",
            "request": "attach",
            "platform": "netCore",
            "containerName": "internal-webui-1",
            "sourceFileMap": {
                "/src": "..\\..\\OtherRepoName\\WebUI"
            }
        }
```
2. Launch the application in Docker via docker-compose
3. In VS Code, from the Run and Debug Menu select the "Docker .NET Attach (WebUI)" profile and click "Run" to connect
4. Try to hit a breakpoint, error occurs:

Could not load source '..\..\IntelliSource\IntelliScriptWebUI\IntelliScriptWebUI\Controllers\Irix\Case\CaseController.cs': Incorrect format of 'source' message..

This is somewhat generic to hide company information. If this isn't enough detail, please let me know and I'll try to put together a small sample reproduction repo for the team.

**Comment by roblourens** [comment]
This belongs on either the docker extension repo or the dotnet repo, I'm not sure which is responsible for this, thanks
