### ISSUE TITLE
Process created using `child_process.fork` behaves differently in 1.78.0-insiders

### ISSUE THREAD

**Issue by atscott** [microsoft/vscode#179637]
The Angular language service extension spawns a child process using `child_process.fork` and listens for the `error` and `close` events. The current version `1.77.0 (Universal)` works as expected. Without any changes to the project, simply updating to `1.78.0-insiders` results in the forked child process acting differently (never erroring and never closing). I'm using Mac 13.3.1 but we also had a report that the forked process isn't working in Windows_NT x64 10.0.22621 either.

There was a similar issue (though not entirely the same) a while back: https://github.com/microsoft/vscode/issues/136988

Apologies for the rather involved reproduction... Here's how I'm able to reproduce and compare the behavior between the versions:

1. Clone our [extension repo](https://github.com/angular/vscode-ng-language-service)
2. Open the repository with vscode insider version 1.78.0-insiders
3. Check out the `15.2.x` branch (we're actually removing this in the next version so it doesn't exist on `main`)
4. Install dependencies with `yarn && yarn --cwd integration/project/`
5. For debugging, put a debugger statement before [line that calls fork](https://github.com/angular/vscode-ng-language-service/blob/15.2.x/server/src/ngcc.ts#L44) and one in the [stderr data listener](https://github.com/angular/vscode-ng-language-service/blob/15.2.x/server/src/ngcc.ts#L52). The project is built with bazel so breakpoints would have to be put in the compiled JS files.
6. Run the build script with `./scripts/build.sh package.json`
7. Launch the extension development host (Dev Client + Server run configuration)
In the extension host, open the [integration project](https://github.com/angular/vscode-ng-language-service/tree/15.2.x/integration/project) and then open the app.component.html template file
-- debugger should stop on the fork and if you continue, you will see that the debugger stops in the stderr data listener but never in the `close` or `error`. The output of the stderr also indicates that it is listening for a debugger and that it gets attached. The fork used `execArgv: []` which should have prevented this. The process also never produces any results or completes.
You can have the fork retry by running the Angular: Restart Angular Language server command in the extension host.

I've also verified that the `childProcess` spawn args are the same between versions and both include "--ms-enable-electron-run-as-node".

**Comment by deepak1556** [comment]
Issue was caused by the allocator changes to `ELECTRON_RUN_AS_NODE` processes which now schedule delayed tasks to purge memory cache https://source.chromium.org/chromium/chromium/src/+/main:base/allocator/partition_alloc_support.cc;l=1183 and that revealed a bug in the [UvTaskRunner](https://github.com/electron/electron/blob/main/shell/app/uv_task_runner.cc) causing the process to hang.
