### ISSUE TITLE
Extension 'installing' stuck, Sync Turning on stuck

### ISSUE THREAD

**Issue by elwynynion** [microsoft/vscode#179662]
Type: <b>Performance Issue</b>

After I installed a new window, I installed Visual Studio Code. However, it runs very slowly on specific tasks, such as turning on Sync and installing extensions. The installation process often gets stuck on the 'Installing' phase.

VS Code version: Code 1.77.1 (b7886d7461186a5eac768481578c1d7ca80e2d21, 2023-04-04T23:21:11.906Z)
OS version: Windows_NT x64 10.0.19045
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 3 PRO 2100GE w/ Radeon Vega Graphics  (4 x 3194)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|13.92GB (9.40GB free)|
|Process Argv|--crash-reporter-id 039eb75b-59c2-4ba3-bfc8-f495d89daccf|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	   156	  4760	code main
    0	    71	  1196	fileWatcher [1]
    0	   266	  3696	extensionHost [1]
    0	    82	 10496	     electron-nodejs ("D:\Microsoft VS Code\Code.exe" --ms-enable-electron-run-as-node "d:\Microsoft VS Code\resources\app\extensions\json-language-features\server\dist\node\jsonServerMain" --node-ipc --clientProcessId=3696)
    0	   108	 10648	     electron-nodejs ("D:\Microsoft VS Code\Code.exe" --ms-enable-electron-run-as-node "d:\Microsoft VS Code\resources\app\extensions\html-language-features\server\dist\node\htmlServerMain" --node-ipc --clientProcessId=3696)
    8	   144	  4436	   gpu-process
    0	    96	  7568	shared-process
    0	    76	 10072	     ptyHost
    0	    24	  9232	   crashpad-handler
    5	   206	  9572	window [1] (index.html - JavaActivities - Visual Studio Code)
    1	    45	  9932	   utility-network-service
    0	    93	 10396	window [2] (Issue Reporter)
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (index.html - JavaActivities - Visual Studio Code)
|    Folder (JavaActivities): 1 files
|      File types: html(1)
|      Conf files:;
```

</details>
<details><summary>Extensions (25)</summary>

Extension|Author (truncated)|Version
---|---|---
aessoft-class-autocomplete|AES|0.1.0
html-class-suggestions|And|1.1.1
vscode-intelephense-client|bme|1.9.5
vscode-tailwindcss|bra|0.9.11
npm-intellisense|chr|1.4.4
flutter|Dar|3.62.0
bracket-pair-toggler|dzh|0.0.3
vscode-html-css|ecm|1.13.1
prettier-vscode|esb|9.10.4
codespaces|Git|1.14.4
copilot|Git|1.79.10634
copilot-labs|Git|0.12.791
live-sass|gle|6.0.5
helium-icon-theme|hel|1.0.0
jupyter-keymap|ms-|1.1.0
color-highlight|nau|2.5.0
material-icon-theme|PKi|4.26.0
LiveServer|rit|5.7.9
sass-indented|syl|1.8.26
intellicode-api-usage-examples|Vis|0.2.7
vscode-java-test|vsc|0.38.2
php-debug|xde|1.32.1
php-pack|xde|1.0.3
html-css-class-completion|Zig|1.20.0
php-intellisense|zob|1.1.2

(3 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
nodejswelcome1:30587005
3biah626:30602489
pyind779:30671433
89544117:30613380
pythonsymbol12:30671437
6233i204:30672705
vsccsb:30705552
vscodeenable:30660116
defaultazurewalk:30687958
pythonms35:30701012
pythonclientmvcf:30708686

```

</details>

**Comment by sandy081** [comment]
Please follow these steps and share logs

- Turn on log level to trace `F1 > Developer: Set Log Level... > Trace`
- Install extension manually
- Share following logs 
  - F1 > Open View.. > Shared
  - F1 > Open View.. > Network

**Comment by elwynynion** [comment]
I have already resolved the issue by flushing the DNS and renewing it using the command line.
