### ISSUE TITLE
Bug: Terminal has hidden click hitbox that sets it to plain text mode

### ISSUE THREAD

**Issue by domdomegg** [microsoft/vscode#179690]
Does this issue occur when all extensions are disabled?: Yes

VS Code Version: Version: 1.77.1
Commit: b7886d7461186a5eac768481578c1d7ca80e2d21
Date: 2023-04-04T23:22:38.708Z
Electron: 19.1.11
Chromium: 102.0.5005.196
Node.js: 16.14.2
V8: 10.2.154.26-electron.0
OS: Darwin arm64 22.4.0
Sandboxed: No

Steps to Reproduce:

1. Open the integrated VS Code terminal
2. Stretch it vertically to maximise the blank line space at the top (this makes clicking the invisible target easier). To do this, you can stretch it so it just adds a line at the top. Then decrease it a bit so the line disappears.
3. Click in the space where that line has disappeared

This seems to take the user to a 'plain text' version of the terminal with colours removed and less padding. It's unclear to users why this happens, or how to get out (the Esc key gets you out). This can be triggered accidentally by users when they're switching tabs, e.g. to view the Problems/Output/Debug Console views.

Expected behaviour: nothing to happen if you misclick on the terminal space.

Video demo:

https://user-images.githubusercontent.com/4953590/231206072-f45ac083-6944-45d0-bdbe-6fc24777b4ce.mov

**Comment by meganrogge** [comment]
this will be fixed in our recovery build and is already fixed in insider's
/duplicate #179020
