### ISSUE TITLE
VS Code: Extension panel crashes to desktop after using "Find"

### ISSUE THREAD

**Issue by dembeck** [microsoft/vscode#179653]
Type: <b>Bug</b>

## Summary

Visual Studio Code crashes if you use and leave open **Find** on an extensions marketplace page, as opened from the extensions panel, then click on another extension opening its marketplace page.

## Steps

1. In the extensions panel, click on any extension to show its marketplace page.
2. Press `Ctrl+F` to open **Find** on the extension marketplace page.
3. Type anything into **Find**.
4. Without closing **Find**, click on another extension.
5. Watch as VS Code instantly and silently crashes to the desktop.

## Notes

- The crash is immediate, and silent. There is no error shown, it just closes.

- If you close Find before clicking on another extension, then VS Code does not crash. 

- It does not make an difference if the find box is empty or not, just that it is open.

VS Code version: Code - Insiders 1.78.0-insider (7f03ec6f7a48791d8027761b22773b454fc52478, 2023-04-10T15:38:56.561Z)
OS version: Windows_NT x64 10.0.25206
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3517U CPU @ 1.90GHz (4 x 2395)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: unavailable_off<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: unavailable_off<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|7.88GB (5.08GB free)|
|Process Argv|--crash-reporter-id 08299dcb-eb20-4782-b418-5daabacfe9e3|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (89)</summary>

Extension|Author (truncated)|Version
---|---|---
separators|ale|2.5.0
vscode-sqlite|ale|0.14.1
nugetpackagemanagergui|ali|2.0.6
markdown-preview-github-styles|bie|1.0.1
vscode-tldr|bmu|1.0.0
vscode-path-tools|cg-|0.0.4
vscode-opennewinstance|chr|0.0.12
npm-intellisense|chr|1.4.4
activitybar-separator|ctf|0.0.1
vscode-eslint|dba|2.4.0
npm-browser|den|1.1.4
vscode-html-css|ecm|1.13.1
EditorConfig|Edi|0.16.4
prettier-vscode|esb|9.10.4
hadolint|exi|1.1.2
vscode-highlight|fab|1.7.3
shell-format|fox|7.2.5
vscode-yarn|gam|2.1.0
remotehub|Git|0.55.2023041001
vscode-github-actions|git|0.25.4
flat|git|0.24.0
unicode-substitutions|Gle|2.3.4
align-mode|Gru|0.0.21
vscode-drawio|hed|1.6.6
check-npm-updates|iak|1.7.10
npm|ide|1.3.0
path-autocomplete|ion|1.23.1
reg|ion|1.1.0
vscode-peacock|joh|4.2.2
vsc-python-indent|Kev|1.18.0
regexp-preview|Lou|0.1.5
reflow-markdown|mar|2.1.0
ts-error-translator|mat|0.8.0
vscode-language-babel|mgm|0.0.38
vscode-devskim|MS-|0.7.102
dotnet-interactive-vscode|ms-|1.0.4207041
black-formatter|ms-|2023.3.10961008
isort|ms-|2023.9.10931010
pylint|ms-|2023.5.10901018
python|ms-|2023.7.11001005
vscode-pylance|ms-|2023.4.11
jupyter|ms-|2023.4.1001021018
jupyter-keymap|ms-|1.1.0
jupyter-renderers|ms-|1.0.15
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-powertoys|ms-|0.0.7
vscode-jupyter-slideshow|ms-|0.1.5
remote-ssh|ms-|0.101.2023041015
remote-ssh-edit|ms-|0.84.0
vscode-remote-extensionpack|ms-|0.24.0
azure-account|ms-|0.11.3
azure-repos|ms-|0.31.2023041001
js-debug-nightly|ms-|2023.4.517
powershell|ms-|2023.3.3
remote-explorer|ms-|0.5.2023040509
remote-repositories|ms-|0.33.2023041001
remote-server|ms-|1.0.0
vscode-typescript-next|ms-|5.1.20230410
jsflowchart|MUL|0.1.6
typescript-explorer|mxs|0.4.0
gremlins|nho|0.26.0
autodocstring|njp|0.6.1
codemap|ole|1.20.2
vscode-gitignore-generator|pio|1.0.3
material-icon-theme|PKi|4.26.0
pester-test|psp|2023.1.0
fabric8-analytics|red|0.3.6
vscode-xml|red|0.25.2023032304
vscode-xml-complete|rog|0.3.0
comment-ts|sal|1.0.21
rewrap|stk|17.8.0
code-spell-checker|str|2.20.4
sort-json|Thi|17.0.1
evenbettercomments|Tio|5.0.7
vscode-status-bar-format-toggle|tom|3.1.1
vscode-inline-values-powershell|Tyl|0.0.7
sort-lines|Tyr|1.9.1
errorlens|use|3.9.0
intellicode-api-usage-examples|Vis|0.2.7
vscodeintellicode|Vis|1.2.30
vscodeintellicode-completions|Vis|1.0.21
vscode-icons|vsc|12.3.0
gistfs|vsl|0.4.1
gitdoc|vsl|0.1.0
codedox|wig|1.3.3
vscode-import-cost|wix|3.3.0
change-case|wma|1.0.0
zoombar-vscode|wra|1.4.4
json|Zai|2.0.2

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythontb:30258533
vsc_aacf:30263846
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscod805cf:30301675
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30404738
cppdebug:30492333
vsclangdf:30492506
c4g48928:30535728
dsvsc012:30540252
pynewext54:30618038
pylantcb52:30590116
nodejswelcome1:30587009
pyind779:30611226
pythonsymbol12:30651887
6233i204:30659907
pythonb192cf:30661257
azdwalk:30687957
pythonms35:30671666
19089226:30680468
ecj1e332:30687743
pythonfmttextcf:30710680
pythonclientmv:30700173

```

</details>

**Comment by sandy081** [comment]
@mjbvz By any chance is this crash related to Markdown editor?

**Comment by deepak1556** [comment]
Merging to https://github.com/microsoft/vscode/issues/177046
