### ISSUE TITLE
Emmet matching pair shortcut not working for lua code, VSCode highlights the corresponding pair but invoking the shortcut does nothing

### ISSUE THREAD

**Issue by rboy1** [microsoft/vscode#179694]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.77.1
- OS Version: Windows 10 22H2

Steps to Reproduce:

1. Sample lua code
```
local function someFunc(one, two, ...)
  return 1
end
```
2. Assign a shortcut to Emmet matching pair, e.g. `alt + shift + ]` 
3. Click on the `end` line in the code above in VSCode, it will highlight the corresponding matching pair `function`, invoke the shortcut on `end` to jump to `function` - nothing happens

**Comment by alekcunn** [comment]
I have found from a basic Google search emmet does not support Lua.
Someone may prove me wrong though
https://code.visualstudio.com/docs/editor/emmet#_how-to-expand-emmet-abbreviations-and-snippets

**Comment by rboy1** [comment]
VS seems to have no issues identifying and highlighting the pairs (function end, if then else, etc). Just doesn't jump between them.

**Comment by rboy1** [comment]
> like "Go To Bracket" or "Select To Bracket"

Yes I tried that and it ends up locating the "next bracket" in the code rather than jumping between the function/end and if/them/else/end

**Comment by rzhao271** [comment]
Emmet doesn't support Lua. Also, I just tried the steps you gave and "function" doesn't highlight for me when I click on "end". I'm wondering if you have a Lua extension installed. If so, please file a feature request in that extension's repository instead.

**Comment by rboy1** [comment]
Hmm I disabled all extensions and checked, it still seems to identifying the pairs function/end etc. See screenshot

![image](https://user-images.githubusercontent.com/3846367/232138829-50d36d87-5c79-4c1a-b401-8d000175a412.png)

**Comment by rboy1** [comment]
Separately, would be possible to add official support for lua? It's very similar to many existing languages so I'm hoping it's feasible

**Comment by rzhao271** [comment]
There is actually a built-in Lua extension that provides syntax and bracket pair highlighting, ref https://github.com/microsoft/vscode/blob/688bc028e3b5536d788729a57dc71066c7bd8b59/extensions/lua/language-configuration.json#L6
@aeschli Could one add more to the Lua extension config so that "Go to bracket" jumps between the `function`/`end` pairs in Lua files? Or, is there a separate command for jumping between that pair?

**Comment by rzhao271** [comment]
Reassigning to Martin for housekeeping. I believe this issue is a feature request for the Lua extension.

**Comment by aeschli** [comment]
I checked with other languages. We don't list keywords like `end` in brackets. Brackets are `(`, `{`, ... 

So 'Go to bracket` is the wrong command to jump from `end` to `function`.

I'm not aware of a command that does that.

**Comment by aeschli** [comment]
@rzhao271 Unless you want to extend the emmet support to also work with Lua, I suggest closing as out-of-scope
