### ISSUE TITLE
Rechargement

### ISSUE THREAD

**Issue by sambruno67** [microsoft/vscode#179614]
Type: <b>Bug</b>

Je ne trouve pas d'option ou de commande pour recharger visual studio code

VS Code version: Code 1.77.1 (b7886d7461186a5eac768481578c1d7ca80e2d21, 2023-04-04T23:21:11.906Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-10210U CPU @ 1.60GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.85GB (4.56GB free)|
|Process Argv|--crash-reporter-id dae6893a-0117-4c11-aabe-0ea83cfae817|
|Screen Reader|no|
|VM|50%|
</details><details><summary>Extensions (178)</summary>

Extension|Author (truncated)|Version
---|---|---
python-image-preview|076|0.1.2
better-comments|aar|3.0.2
html-snippets|abu|0.2.1
js-quick-console|Aha|0.0.3
python-quick-print|Aha|0.2.0
Bookmarks|ale|13.3.1
project-manager|ale|12.7.0
python-debug-address-prompt|ale|1.0.1
python-colorful-print|Ali|0.1.1
config-view|All|0.1.1
code-django|alm|0.5.2
arepl|alm|2.0.5
birdseye-vscode|alm|0.0.6
aws-toolkit-vscode|ama|1.67.0
alexa-skills-kit-toolkit|ask|2.14.1
vscode-database|baj|2.2.3
vscode-django|bat|1.10.0
pythoncpp-debug|ben|0.3.0
htmlplay|bia|0.0.10
django-html|bib|1.3.0
django-snippets|bib|1.1.1
django|big|1.0.2
vscode-intelephense-client|bme|1.9.5
phpserver|bra|3.0.2
python-logger-vscode|bri|0.2.6
simple-react-snippets|bur|1.2.7
cacher-vscode|Cac|1.1.1
ikp3db|cmo|0.0.8
console-wrap-php-js-python|Cod|0.0.7
python-live-coding|Cod|1.1.6
codesnippetsai|cod|1.3.3
auto-django|Cod|0.0.1
python-snippets|cst|0.1.2
vscode-mysql-client2|cwe|6.3.5
c-cpp-compile-run|dan|1.0.44
dart-code|Dar|3.62.0
flutter|Dar|3.62.0
vscode-markdownlint|Dav|0.49.0
vscode-eslint|dba|2.4.0
django-management|den|0.1.1
vscode-django-snippets|dev|1.0.0
profiler-php-vscode|DEV|1.33.12934
django-import-libraries|Dha|0.0.4
pyinit|Dio|0.0.3
githistory|don|0.6.20
python-environment-manager|don|1.0.4
python-extension-pack|don|1.7.0
xml|Dot|2.5.1
vscode-python-pack|dse|1.4.0
gitlens|eam|13.5.0
vscode-html-css|ecm|1.13.1
EditorConfig|Edi|0.16.4
RunOnSave|eme|0.2.0
django-factory|Eme|0.0.9
prettier-vscode|esb|9.10.4
vscode-pydev|fab|0.3.0
vscode-firefox-debug|fir|2.9.8
code-runner|for|0.12.0
vscode-mysql|for|0.4.1
vscode-cpython-extension-pack|fra|0.1.0
vscode-python-config|fra|1.13.0
vscode-python-dev-extension-pack|fra|0.8.0
pythonsnippets|frh|1.0.2
vscode-php-cs-fixer|fte|0.4.0
geecode-python|gee|2019.5.10
copilot|Git|1.79.10634
vscode-pull-request-github|Git|0.62.0
google-cloud-spanner-driver|goo|0.4.1
cloudcode|goo|1.21.3
gc-excelviewer|Gra|4.2.57
ai-docstring|gra|0.1.3
vs-code-runner|Har|2.0.1
vscode-test-explorer|hbe|2.21.1
vscode-test-explorer-liveshare|hbe|1.0.5
cyclops|j3m|0.0.5
better-cpp-syntax|jef|1.17.2
python-essentials|Jil|0.0.3
docstring-generator|jor|0.1.0
php-cs-fixer|jun|0.3.9
vscode-django-support|jun|1.0.23
python-resource-monitor|kai|0.2.0
vsc-python-indent|Kev|1.18.0
kodezi|kod|2.1.1
vscode-phpfmt|kok|1.0.31
kolo|kol|2.5.0
live-code-runner|lab|4.5.0
cyberbrain|lai|0.2.1
python-extension-pack|Leo|2.0.0
lightrunplugin-saas|lig|1.11.3
vscode-python-test-adapter|lit|0.7.1
MagicPython|mag|1.1.0
fox|Mal|0.1.1
javascript-docstrings|Mas|1.1.1
django-commands|Max|0.1.3
rainbow-csv|mec|3.6.0
php-constructor|Meh|0.1.2
php-namespace-resolver|Meh|1.1.9
python-path|mge|0.0.14
vscode-docker|ms-|1.24.0
vscode-language-pack-fr|MS-|1.77.2023040509
vscode-dotnet-runtime|ms-|1.6.0
vscode-edge-devtools|ms-|2.1.1
vscode-kubernetes-tools|ms-|1.3.11
data-workspace-vscode|ms-|0.4.0
mssql|ms-|1.18.0
sql-database-projects-vscode|ms-|0.21.0
pyright|ms-|1.1.302
isort|ms-|2022.8.0
python|ms-|2023.7.11001005
jupyter|ms-|2023.3.1000892223
jupyter-keymap|ms-|1.1.0
jupyter-renderers|ms-|1.0.15
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-slideshow|ms-|0.1.5
remote-containers|ms-|0.288.0
remote-ssh|ms-|0.98.0
remote-ssh-edit|ms-|0.84.0
remote-wsl|ms-|0.77.0
cpptools|ms-|1.14.5
js-debug-nightly|ms-|2023.4.517
powershell|ms-|2023.3.3
remote-explorer|ms-|0.4.0
sublime-keybindings|ms-|4.0.10
test-adapter-converter|ms-|0.1.7
vsliveshare|ms-|1.0.5834
vscode-react-native|msj|1.10.2
sqltools|mtx|0.27.1
sqltools-driver-mysql|mtx|0.5.1
composer-Intelephense|mua|1.0.1
python-docs|Muk|0.8.3
read-urls|mur|2.1.0
php-docblocker|nei|2.7.0
mysql-autocomplete|nes|0.5.0
vscode-ni-python-dataplugins|NI|1.0.2
python-coding-tools|nil|1.0.4
mobu-utils|Nil|1.2.5
ue-python|Nil|0.2.2
autodocstring|njp|0.6.1
vscode-python-typehint|njq|1.5.1
laravel-blade|one|1.34.0
mysql-shell-for-vs-code|Ora|1.9.1
oracledevtools|Ora|21.5.0
python-brackets|Ora|1.4.2
vscode-numpy-viewer|Per|0.1.7
material-icon-theme|PKi|4.26.0
open-php-html-js-in-browser|Pri|2.2.0
pyDocGenAI|pyD|1.0.2
vscode-yaml|red|1.12.2
python-template-snippets|Ric|1.2.0
LiveServer|rit|5.7.9
php-debug|rob|1.14.0
vscode-qt-for-python|sea|7.3.1
django-intellisense|sha|0.0.2
code-settings-sync|Sha|3.4.3
django-snippets|Sid|0.0.4
sidekick-debugger|Sid|0.0.19
php-ci|sma|0.4.2
php-formatter|Sop|0.2.4
sourcery|sou|1.1.0
bugfixer|spa|0.9.2
splunk|Spl|0.2.10
guides|spy|0.9.3
autoimport|ste|1.5.4
code-spell-checker|str|2.20.4
vscode-stripe|str|2.0.14
python-pack|Swe|0.1.15
tabnine-vscode|Tab|3.6.44
even-better-toml|tam|0.19.0
cython|tcw|0.1.0
tensorbox|Ten|1.0.2
vscode-djaneiro|the|1.4.2
html-preview-vscode|tht|0.2.5
thundra-debugger|thu|1.1.18
wolf|tra|0.4.3
python-extended-snippets|tus|0.0.1
vscode-java-debug|vsc|0.49.1
vscode-wakatime|Wak|24.0.7
markdown-all-in-one|yzh|3.5.1

(3 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vscaat:30438848
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
nodejswelcome1:30587005
282f8724:30602487
pyind779:30671433
f6dab269:30613381
pythonsymbol12:30671437
a9j8j154:30646983
vsccsb:30705552
functionswalk:30687959
pythonms35:30701012
pythonclientmv:30708685

```

</details>

**Comment by ulugbekna** [comment]
Invoke command "Developer: Reload Window" from the Command Palette (`ctrl+shift+p` or `F1`)
