### ISSUE TITLE
Fix typings on windows-process-tree

### ISSUE THREAD

**Issue by rzhao271** [microsoft/vscode#179697]
As part of refreshing some packages, we moved windows-process-tree under the vscode npm org. However, the types package corresponding to it was still being used in the VS Code repository to provide typings, even though it was deprecated. When windows-process-tree got moved under the vscode npm org, the types package became invalid because it pointed to the wrong module, so we had to remove it and substitute in a typings file elsewhere. That file, in turn, has an enum that clashes with the vscode/windows-process-tree package when compiling on Windows.

We currently use workarounds to get compilation to work on all OSes, ref https://github.com/microsoft/vscode/pull/179649/files#diff-be1e59cb9de48d302706802a06f7262dd66c44d89044968b12eb3b420b674324R11 and https://github.com/microsoft/vscode/pull/179649/files#diff-397828d0c533a7793690c33b8f6922fc8f5de8cc675c12d62a30a86f358ae7ceR175.

This issue tracks fixing the vscode/windows-process-tree package so that we don't need the workarounds above.

One approach is to allow that package to be installed on all OSes, so that types are available on all OSes, but then make it so that importing or calling into the package from a non-Windows OS results in a no-op or an error.

Another approach is to revive the types package on DefinitelyTyped, but an issue with that is that future changes to the module would require waiting for another PR to update the types upstream.

Ref https://github.com/microsoft/vscode/pull/179508
Ref https://github.com/microsoft/vscode/pull/179649

CC @Tyriar @joaomoreno @deepak1556

**Comment by Tyriar** [comment]
Shipping types in the package is far superior than going with definitely typed. I'm find to allow it to be installed on all OS's, I guess returning an empty object and warning if it's ever called not on Windows?
