### ISSUE TITLE
Change default light and dark themes to the v2 themes

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode#179688]
The new experimental themes will become the new default themes

- find a new name for the new themes
- show a notification the first time an existing user sees the new theme

**Comment by sean-mcmanus** [comment]
@aeschli With today's Insiders (on Windows), the notification shows `VS Code now ships with a new default theme ''.` for me, i.e. it's missing the theme name.

![image](https://user-images.githubusercontent.com/19859882/231837011-fe5de4bc-7e09-4847-afad-1886b7c71735.png)
