### ISSUE TITLE
Window sometimes stops responding when using the terminal

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#179636]
Over the past few days I’ve been noticing the window sometimes stop responding when I do things with the terminal, is there any known issue for this or should I try to grab a perf trace? It doesn't happen all that often.

Example steps

- Run the "focus next terminal group" command
- The vscode window does not respond to clicks or keypresses for about 3-5s and the renderer process shows 100% CPU usage
- Then it responds and continues as normal

**Comment by roblourens** [comment]
I haven't managed to capture a trace yet, but I still see it from time to time. If it helps at all or you can think of recent changes in this flow, I _think_ it is related to steps like this

- Start vscode
- Run the "VS Code Build" task when it is connecting to a daemon that has been running for a long time and has a long output history
- Open the panel and reveal that task terminal
- See the hang

But it's not every time

**Comment by Tyriar** [comment]
I haven't seen any lock ups, reopen if you manage to get a trace

**Comment by roblourens** [comment]
I don't think I've seen a full hang in a while but there is still suspicious slowness when showing the terminal where it has a lot of history. Here's a trace where it blocked for almost 2s. All I did was close the panel, let the build task produce a lot of output, then press cmd+J to show the panel with the terminal visible, and there was a noticeable delay before it appeared.

[Profile-20230517T173055.json.zip](https://github.com/microsoft/vscode/files/11503294/Profile-20230517T173055.json.zip)

**Comment by Tyriar** [comment]
Looks like the regression is caused by the accessible buffer:

![image](https://github.com/microsoft/vscode/assets/2193314/7016c94e-3ec9-4c07-a6e4-5254111c3c61)

**Comment by meganrogge** [comment]
@roblourens do you know what your scrollback was set to when this happened? was it 150000 like in the other issue?

**Comment by roblourens** [comment]
Yes
