### ISSUE TITLE
Debugging babel transpiled code not fully working with node2

### ISSUE THREAD

**Issue by mrukas** [Microsoft/vscode#17960]
- VSCode Version: 1.8.1
- OS Version: Fedora 25

Steps to Reproduce:

1. Use babel-register to transpile source files.
2. Set breakpoints in the original source files.
3. Try to hover variables if breakpoint gets hit.

The problem is, that the breakpoints gets hit but the values of variables doesn't get shown if you hover them. If you add the variable as a watch expression the value of it gets shown in the list. This only happens if you use the **node2** debugger. With the "old" **node** debugger everything works as expected.

This is my setup of babel-register:

```
require('babel-register')({
    plugins: ['transform-async-to-generator'],
    sourceMaps: true,
    retainLines: true
});

require('./src/app');
```

This is my launch.json: 
```
{
    "version": "0.2.0",
    "configurations": [{
        "name": "Launch Program",
        "type": "node2",
        "request": "launch",
        "program": "${workspaceRoot}/index.js",
        "cwd": "${workspaceRoot}",
        "sourceMaps": true
    }, {
        "name": "Attach to Process",
        "type": "node2",
        "request": "attach",
        "port": 9229
    }]
}
```

**Comment by roblourens** [comment]
This is a known issue in 1.8 - just in this specific dynamic compilation case, hover won't work. However, it should work in 1.9 (and currently in insiders).

**Comment by mrukas** [comment]
I tried it in a current insider build and got the same problem. I also doesn't see the values of hovered variables.

**Comment by roblourens** [comment]
It's working in my babel-register test project. Is this a public repo where I can try it out?

**Comment by mrukas** [comment]
I have pushed it into a public git repo so you can try it yourself.
Link: [https://github.com/mrukas/koa-babel-test](https://github.com/mrukas/koa-babel-test)

This is just a test project with **koa js** and **babel** as transpiler, there isn't anything useful in it. The **master** branch uses the new debugger and the **old-debug** branch uses the old debugger. For me the old debugger works perfectly fine, but the new one makes multiple problems which are: 

* Values of variables doesn't get shown when hovered.
* Errors are getting thrown if project gets started and breakpoints are already set.

Thanks in advance!

**Comment by roblourens** [comment]
I just realized that my fix for this didn't make it into node2 yet. It will be fixed in the next insiders build.

For reference, this was previously https://github.com/Microsoft/vscode-chrome-debug/issues/309

**Comment by mrukas** [comment]
Ok this sounds great! Thanks!
