### ISSUE TITLE
C/C++ for Visual Studio Code won't update.

### ISSUE THREAD

**Issue by scareware047** [Microsoft/vscode#17965]
- VSCode Version: Code 1.8.1 (ee428b0eead68bf0fb99ab5fdc4439be227b6281, 2016-12-19T14:49:23.350Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

|Extension|Author|Version|
|---|---|---|
|Theme-Blackboard|gerane|0.0.2|
|MagicPython|magicstack|1.0.3|
|cpptools|ms-vscode|0.9.3|
|you-complete-me|RichardHe|1.0.24|
|Spell|seanmcbreen|0.9.1|
|python|tht13|0.2.3|

---
Output:
Updating C/C++ dependencies...

Downloading package 'C/C++ language components (Windows)' Failed at stage: downloadPackages
Error: connect ETIMEDOUT 23.35.5.207:443

Finished

[9:52:57 PM] Connection to server is erroring. Shutting down server.
[9:52:57 PM] Connection to server is erroring. Shutting down server.
[9:52:57 PM] Connection to server is erroring. Shutting down server.
[9:52:57 PM] Connection to server is erroring. Shutting down server.

**Comment by rebornix** [comment]
@scareware047 it looks like a network issue but it has nothing to do with Code. Please file issues in the CPP extension repository you are using.

**Comment by rebornix** [comment]
This issue was moved to Microsoft/vscode-cpptools#428
