### ISSUE TITLE
File explorer disapear

### ISSUE THREAD

**Issue by wondertalik** [microsoft/vscode#179602]
Type: <b>Bug</b>

Hello,

During working with profiles sometimes explorer disapear and there are no way to return it back. I found only one way, is remove profile and import again.

Hotkeys doesnt work. [Screenshot](https://drive.google.com/file/d/1r19GPXA6c8MVmR6LWVW8FXpmMu6ASp-5/view?usp=share_link)

VS Code version: Code 1.77.1 (Universal) (b7886d7461186a5eac768481578c1d7ca80e2d21, 2023-04-04T23:23:33.779Z)
OS version: Darwin arm64 22.4.0
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|3, 3, 4|
|Memory (System)|16.00GB (0.35GB free)|
|Process Argv|--crash-reporter-id 992ce0fe-5e65-4e32-a10e-42d588fc1388|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (41)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|3.0.2
flutter-snippets|ale|3.0.0
al-code-outline|and|3.0.44
dart-code|Dar|3.62.0
flutter|Dar|3.62.0
vscode-markdownlint|Dav|0.49.0
vscode-dash|dee|2.4.0
javascript-vue|Dig|0.3.2
gitlens|eam|13.5.0
prettier-vscode|esb|9.10.4
bloc|Fel|6.6.3
shell-format|fox|7.2.5
vscode-flutter-files|gor|4.6.0
todo-tree|Gru|0.0.224
i18n-arb-editor|inn|1.3.0
l13-projects|L13|1.1.1
flutter-intl|loc|1.19.1
git-graph|mhu|1.30.0
dart-barrel-file-generator|miq|6.1.1
vscode-docker|ms-|1.24.0
vscode-kubernetes-tools|ms-|1.3.11
remote-containers|ms-|0.288.0
remote-ssh|ms-|0.98.0
remote-ssh-edit|ms-|0.84.0
remote-explorer|ms-|0.4.0
awesome-flutter-snippets|Nas|3.0.3
vetur|oct|0.37.3
colorful-comments|Par|1.0.0
advanced-new-file|pat|1.2.2
vscode-thunder-client|ran|2.6.1
vscode-yaml|red|1.12.2
vs-code-prettier-eslint|rve|5.1.0
vue-vscode-snippets|sdr|3.1.1
unique-window-colors|stu|1.0.51
vscode-gradle|vsc|3.12.7
vscode-icons|vsc|12.2.0
volar|Vue|1.2.0
crs-al-language-extension|wal|1.5.25
vscode-todo-highlight|way|1.0.5
faster-new|wen|1.5.2
vue|Wsc|1.0.26

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
nodejswelcome1cf:30587006
282f8724:30602487
pyind779:30671433
89544117:30613380
pythonsymbol12:30671437
vsctsb:30705553
azdwalk:30687957
pythonms35:30701012
pythonclientmvcf:30708686

```

</details>

**Comment by lramos15** [comment]
Try `CMD + SHIFT + P` then enter `Reset View Locations`

**Comment by peterdeme** [comment]
Same happened to me today, Reset View Locations fixed it
