### ISSUE TITLE
make accessibility help menu more accessible

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#179689]
In https://github.com/microsoft/vscode/pull/179424#issuecomment-1502872868, we introduced a more accessible terminal accessibility help menu for the terminal. we should do the same for the editor

**Comment by jjaeggli** [comment]
Hi Megan, I was working on a similar issue to use proper list markup for the Accessibility Help dialog, and coincidentally I was preparing it to send out today. Please take a look at the PR and let me know if this is what you had in mind. There are some outstanding questions in the PR which I could use someone with better familiarity with the codebase to provide feedback on.

**Comment by meganrogge** [comment]
Hey @jjaeggli thank you so much for looking into this. Your changes look good, but they are different from what I had in mind. 

Currently, the `monaco-editor`, IE the underlying element of files, is highly accessible. It can be navigated via arrow keys, which means header navigation etc. are not needed. 

Recently, I changed the terminal's accessibility help menu to use the `monaco-editor`. My plan was to do a similar thing here. You can look at the changes I made in that PR, though they could be a bit complicated/confusing as compared with what will be needed for this case.

**Comment by meganrogge** [comment]
Running the `Terminal: Show Terminal Accessibility Help` should enable you to try out what I am referring to as the example/desired outcome

**Comment by meganrogge** [comment]
Since you seem well versed in accessibility standards, I'm also curious to hear what you think of this approach and if there's anything you believe we should do instead

**Comment by jjaeggli** [comment]
One other comment is that the `dialog` role must be given an aria label while `document` does not require this. https://w3c.github.io/aria/#document

**Comment by meganrogge** [comment]
We will make this even more accessible via the `AccessibleView`
