### ISSUE TITLE
CCSID 273 encoding not recognised

### ISSUE THREAD

**Issue by mechefan** [microsoft/vscode#179693]
I am using VS Code to connect to an IBM i server. The encoding associated with my user profile in the server is CCSID 273, which is not included in the VS Code list, so I'm not able to open files using this encoding, and some characters are misunderstood by the VS Code editor.
I've tried to open the files in VS Code using different encodings but none of the included in the VS Code list are able to recognise correctly the complete set of characters.
Is there any way to add the CCSID 273 encoding or other EBCDIC CCSID encodings to VS Code?

**Comment by roblourens** [comment]
No, sorry we don't support text encodings besides the ones listed.
