### ISSUE TITLE
HTML preview size is broken

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#17966]
Affects 1.8.1 and 1.9 on Ubuntu 16.10.

This is probably a duplicate by now but I've been seeing this for some time for all HTML previews:

![image](https://cloud.githubusercontent.com/assets/2193314/21578988/1fc90a86-cf4c-11e6-846b-c4e68c2a0886.png)

**Comment by rebornix** [comment]
This problem happens if you zoom the window.

**Comment by rebornix** [comment]
Dup of https://github.com/Microsoft/vscode/issues/5745 .
