### ISSUE TITLE
Terminal crash suddenly 

### ISSUE THREAD

**Issue by wasiualhasib** [microsoft/vscode#179674]
Type: <b>Bug</b>

suddenly my teminal gray out. In that time unable run any command. I am not sure why this is happening. Please let me know

VS Code version: Code 1.77.1 (b7886d7461186a5eac768481578c1d7ca80e2d21, 2023-04-04T23:20:37.202Z)
OS version: Linux x64 5.19.0-38-generic snap
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-3240 CPU @ 3.40GHz (4 x 3392)|
|GPU Status|2d_canvas: unavailable_software<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>opengl: disabled_off<br>rasterization: disabled_software<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software<br>webgpu: disabled_off|
|Load (avg)|2, 2, 2|
|Memory (System)|11.59GB (3.27GB free)|
|Process Argv|--no-sandbox --force-user-env --unity-launch --crash-reporter-id 2dde48ee-603c-49d3-81ed-f728d59d4e35|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|wayland|
</details><details><summary>Extensions (26)</summary>

Extension|Author (truncated)|Version
---|---|---
terraform|4op|0.2.5
python-quick-print|Aha|0.2.0
golangwithdidi|ald|0.0.1
terraform-autocomplete|erd|0.0.8
pythonsnippets3|Eri|3.3.18
code-runner|for|0.12.0
go|gol|0.38.0
golang-snippets|hon|1.2.0
terraform-azure-autocomplete|las|0.0.1
MagicPython|mag|1.1.0
terraform-completer|mgt|0.2.0
python|ms-|2023.6.0
vscode-pylance|ms-|2023.4.10
jupyter|ms-|2023.3.1000892223
jupyter-keymap|ms-|1.1.0
jupyter-renderers|ms-|1.0.15
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-slideshow|ms-|0.1.5
gotools|neo|0.0.7
gremlins|nho|0.26.0
terraform-advanced-syntax-highlighting|pjm|1.4.0
gotestexplorer|pre|0.1.13
quicktype|qui|12.0.46
terraform-doc-snippets|run|0.6.0
vscode-postfix-go|yok|0.0.12
vscode-proto3|zxh|0.5.5

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
vsccc:30610678
nodejswelcome1:30587005
2e4cg342:30602488
pyind779:30671433
f6dab269:30613381
pythonsymbol12:30671437
vsccsb:30705552
vscodeenable:30660116
defaultazurewalk:30687958
pythonms35:30701012
pythonfmttext:30710681

```

</details>

**Comment by niyan-ly** [comment]
Actually it's pretty 'stable', i can easily re-produce this issue.
![Untitled](https://user-images.githubusercontent.com/28030655/231197916-54581b76-56c0-4fb3-9282-644542709be9.gif)
