### ISSUE TITLE
diff window use only one pane

### ISSUE THREAD

**Issue by Jimmy-Z** [Microsoft/vscode#17969]
- VSCode Version: 1.8.1
- OS Version: Windows 10

Steps to Reproduce:

1. use vscode in two or pane mode (or split mode).
2. diff a file, it will be contained in one pane, further splitting the pane to two sub panes.

**Comment by rebornix** [comment]
If we split them into two panes, it means these two panes can be irrelevant, you can close one or another, have different scrolling position, etc. However, they are not, they are closely connected to each other. So we have them in one pane. Not even to say inline diff view.

**Comment by Jimmy-Z** [comment]
Well, then, solve it, make two panes CAN be relevant.

**Comment by rebornix** [comment]
@Jimmy-Z I'm not saying we have difficulty implementing this, what I mean is users might get confused when it becomes two panes and it leads UX complexity.

**Comment by Jimmy-Z** [comment]
That sound like you had difficulty implement this to me.
