### ISSUE TITLE
"Cannot read property 'substring' of undefined" using elm + elm-format 

### ISSUE THREAD

**Issue by z5h** [Microsoft/vscode#17968]
- VSCode Version: 1.8.1
- OS Version: MacOS 10.12.1

Steps to Reproduce:

1. Install/configure plugins: elm, elm-format
2. attempt to format Elm code.

Result is `Error Cannot read property 'substring' of undefined`

This is not reproducible in VSCode Version: 1.9.0-insider.

**Comment by rebornix** [comment]
Since it's an extension issue, I'll suggest to file issues in extensions' repositories and start investigation there. Thanks!
