### ISSUE TITLE
VSCode opens the same file in multiple editors if the names use different cases

### ISSUE THREAD

**Issue by wm1** [Microsoft/vscode#17967]
- VSCode Version: 1.8.1
- OS Version: Windows 10 

Steps to Reproduce:
1. Create a file named LICENSE.txt
2. Run "Code --reuse-window LICENSE.txt"
3. Run "Code --reuse-window license.txt"
4. Observe that VSCode opens 2 editor windows.
5. Expect: VSCode detects the two file names are actually the same file, and only opens one file instead.

    ![case](https://cloud.githubusercontent.com/assets/12519738/21579035/51e6ca88-cf4e-11e6-8ac4-32a911f2420d.JPG)

This is especially annoying when dealing with MSVC project, when click the build error message and a new window is opened.
1. Create a C++ project. The file name contains mixed upper and lower case. Open the file d:\git\Test\Main.cpp in editor
2. Create a task.json and use msbuild to build the project
3. Build. Assume there is an syntax error like the following. Notice that cl.exe converts filename to lower case
  d:\git\test\main.cpp(10): error C2144: syntax error: 'int' should be preceded by ';' [d:\git\Test\Test.vcxproj]
4. Click the status "Problem" icon. Select the error message from the panel. The main.cpp is opened in editor, right next to Main.cpp

**Comment by bpasero** [comment]
Let's merge into https://github.com/Microsoft/vscode/issues/12448
