### ISSUE TITLE
Improvements to the UX/UI of Continuous Testing

### ISSUE THREAD

**Issue by dlschmidt** [microsoft/vscode#179624]
Currently I don't quite like the way Continuous Testing is presented right now.
For me it is a huge improvement in the development cycle and I would like to put it more in the foreground.

For example the button for starting and stopping is very confusing.
![image](https://user-images.githubusercontent.com/20640295/230969292-2faa37be-015b-4b2e-bda2-c38b6d45558b.png)

The button could represent to a new user two different meanings:
- watch symbol without crossline = Continuous Testing is active
- watch symbol without crossline = enable Continuous Testing = Continoous Testing is not active

Therefore I would like to communicate the state more clearly to the developer.

Also I could imagine to add a status bar item only when Continuous Testing is active. `vscode-jest` is doing the same thing for representing the state of Testing. VSCode does support to hide status bar items, therefore I dont think it would be _bloat_, but more a nice addition.

**Comment by connor4312** [comment]
You may be interested in improvements from last week as well: https://github.com/microsoft/vscode/issues/178973#issuecomment-1496713352

**Comment by connor4312** [comment]
Made some more improvements here in the last release which I think covers this decently well
