### ISSUE TITLE
TextMate grammar regexes able to only match a single line

### ISSUE THREAD

**Issue by tambry** [Microsoft/vscode#17964]
![Image of improper multiline syntax highlighting](http://i.imgur.com/PIV2uAM.png)

Everything between the parentheses should be coloured green, but the matching stops after the first line ends.

- VSCode Version: 1.8.1
- OS Version: Ubuntu 16.10 64-bit (4.8.0-30-generic)

Steps to Reproduce:

1. Clone [this minimal repro sample](https://github.com/tambry/vscode_multiline_match_bug).
2. Open the folder of the sample in VS Code.
3. Press F5 to run the extension in a new VS Code instance.
4. In the new instance open the *test.matchbug* file that's in the repro sample's root directory.
5. Code is improperly highlighted.

[How the regex should match](https://regex101.com/r/W29FWu/1)

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/vscode-textmate#32
