### ISSUE TITLE
feature request: put word under cursor in search box

### ISSUE THREAD

**Issue by Jimmy-Z** [Microsoft/vscode#17974]
I mean the "Find in Files" box.

**Comment by rebornix** [comment]
if you are referring to the search popup box in the editor, the feature already exists. So I'd like to ask are you referring to the search viewlet which is triggered by `ctrl/cmd+shift+f`?

**Comment by Jimmy-Z** [comment]
yes, sorry I've been using the vim extension exclusively, I never used the search in file feature.

**Comment by sandy081** [comment]
@roblourens I liked the feature of adding text to Search when not selected. But, I feel the current behaviour is confusing to me.. Word under cursor is only added if there is no text in Search viewlet. But, word under selection is always added. My expectation would be to behave same always.

Also I think, we are overloading cmd+shift+f a lot.

What do you think?

**Comment by sandy081** [comment]
Opening for discussion

**Comment by roblourens** [comment]
Hm, that may be. I can see how it will be confusing whether the current word will be added. Maybe it should just always be added? That interferes with using cmd+shift+f to just focus the viewlet but I don't know how many people rely on that.

**Comment by sandy081** [comment]
>>That interferes with using cmd+shift+f to just focus the viewlet but I don't know how many people rely on that.

This might be annoying while navigating from search results to editor and back. But we can be at least consistent with Find widget I suppose

**Comment by roblourens** [comment]
I like the current behavior, nobody else has complained.
