### ISSUE TITLE
Confusing Bash/Shell syntax highlighting

### ISSUE THREAD

**Issue by eddiezato** [microsoft/vscode#179749]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.77.2
- OS Version: Windows 11 Pro 22H2 22621.1485

The Bash/Shell syntax highlighting becomes very confusing.
For example, the arguments for a command are the same color as the strings. See picture (v1.75.1 for comparison):

<img width="338" alt="Screenshot 2023-04-12 132238" src="https://user-images.githubusercontent.com/11173476/231369691-ba14bbd0-2729-4bf0-9846-d4ca4c5cfedb.png">

**Comment by alexr00** [comment]
We recently switched to a new, better, grammar for shellscript syntax highlighting. The new grammar does a better job assigning scopes to each token, which in this case means that `-rf` has a more specific scope than before. I think we can improve this coloring slightly to this:

<img width="132" alt="image" src="https://user-images.githubusercontent.com/38270282/231463251-4caf72cf-93ea-47dc-adea-bbfc22151905.png">
