### ISSUE TITLE
Make progress on PR #161716

### ISSUE THREAD

**Issue by jackpunt** [microsoft/vscode#179738]
I'd like to see someone respond to #161716, tell what is still to be done to get it integrated.
@bpasero had some comments (months ago...) and I have addressed them, but then total silence.
I occasionally merge to keep up with vscode, but have no idea if/when this PR can be merged or closed.

Please find someone to respond and tell me where it is going.

**Comment by bpasero** [comment]
Will try to take a look this or next week.
