### ISSUE TITLE
modified key binding is not reflected on the UI

### ISSUE THREAD

**Issue by Jimmy-Z** [Microsoft/vscode#17971]
- VSCode Version: 1.8.1
- OS Version: Windows 10

for example in the menu
![image](https://cloud.githubusercontent.com/assets/85773/21581952/65a938ce-d081-11e6-9d3a-f6d819daae81.png)
or the command line
![image](https://cloud.githubusercontent.com/assets/85773/21581957/9079d4a0-d081-11e6-918b-707ea95eae0f.png)
I'm using vim extension which binds Ctrl-T otherwise, but still shown there, user binding is similar.

**Comment by rebornix** [comment]
sorry I don't think the title is `self explanatory `, when you say `UI` which part are you referring to? A screenshot will explain better.

**Comment by Jimmy-Z** [comment]
screenshot added

**Comment by bpasero** [comment]
This issue has already been reported. Please use the search function next time before reporting an issue and/or this time if you are curious about the progress of the issue.

**Comment by Jimmy-Z** [comment]
Believe me, I've searched, it would be helpful if you could cite the previous issue here.

**Comment by Jimmy-Z** [comment]
I'd like to point this out again, you failed to cite the "already been reported" issue.
