### ISSUE TITLE
Right-click on branch name

### ISSUE THREAD

**Issue by rhires** [microsoft/vscode#1797]
It would be helpful if I could right click on the branch name in the lower left hand corner to be able to copy the name of the branch (or get other details there, different from what is already provided by left-clicking).

**Comment by martellaj** [comment]
@rhires, what other things do you think would be useful on a right-click there?

**Comment by rhires** [comment]
Good question. Maybe other git info, such as files changed/staged/unstaged. I hadn't thought about it too much. There are a lot of other places I think that right-clicking should produce a useful context menu, but mainly my interest here is to be able to simply copy the name of the branch, since I need that for other tools in other places.

**Comment by martellaj** [comment]
I think it's a good idea. I was just trying to think of what else could be added there. I think including Git file status would be redundant since there's the nice Git tab that shows all of that already.

**Comment by mackness** [comment]
Hi @martellaj and @joaomoreno let me know if my approach makes sense. if it does I would be happy to add some tests around the code I added.

**Comment by joaomoreno** [comment]
I have removed the `help wanted` label as this isn't a trivial issue which can be done without any API discussion and proper planning.

**Comment by jaqra** [comment]
@joaomoreno what about something like that till to statusbaritem context menu api integrated?

![branch](https://user-images.githubusercontent.com/48099350/55747138-42698b80-5a44-11e9-9e19-dc81c76dd095.png)

if yes, can you let me do it :)

**Comment by Tyriar** [comment]
@joaomoreno right click now lets you configure the status bar, can this be closed since there is already a rename branch command?

**Comment by joaomoreno** [comment]
@Tyriar not sure if that matches the description of this issue. But I'll close this as `won't happen`.
