### ISSUE TITLE
API to get the "Editor" or "Webview" shown in a Tab

### ISSUE THREAD

**Issue by jogibear9988** [microsoft/vscode#179778]
At the moment it is not possible the get the "Editor" or "Webview" wich is shown in a Tab.

We need at Api to make this possible.

See also this issue for info:
https://github.com/microsoft/vscode-discussions/discussions/558
and this
https://github.com/microsoft/vscode/issues/178198

**Comment by mjbvz** [comment]
Webviews and custom editors are private to the extension that created them so there's no api that will return that for them. 

If you want to do this for custom editors you have created, you can keep track of your custom editors and either check it's properties or use `TabInputCustom` to check if a given tab is for your custom editor

**Comment by jogibear9988** [comment]
@mjbvz 
i did get the 
e.changed[0].activeTab?.input
for example, there I can see it is a instance of my extension, but from where should I know wich one? Cause I could open my designer multiple times for the same document, so I could not use the URI to differnciate
