### ISSUE TITLE
Leaking remote shellintegration process?

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#179798]
Noticed this still present long after the remote server shut down. I'm not sure how this fits into the process hierarchy

<img width="1335" alt="image" src="https://user-images.githubusercontent.com/323878/231525757-e975035a-9d77-4fe1-85bb-b6326dd29ba9.png">

**Comment by meganrogge** [comment]
Let us know if you can still reproduce in Insider's

**Comment by Tyriar** [comment]
Let's track in https://github.com/microsoft/vscode/issues/179911
