### ISSUE TITLE
Tasks no longer report error codes

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode#179791]
This has been reported a few times before, but previously it was for workspaces where I had multiple split terminals, so the working explanation was that wrapping terminal output isn't properly handled due to conpty issues. I just repro'd this on Windows for a single terminal instance (no splits):

![image](https://user-images.githubusercontent.com/30305945/231513158-3bf66a37-8cbf-4b7e-a46d-d7e4b3e6f290.png)

**Comment by meganrogge** [comment]
Which repo are you in and which task did you run? I will see if I can reproduce

**Comment by joyceerhl** [comment]
This was https://github.com/microsoft/vscode-pull-request-github. If it matters, I'm on a Surface Book 3 running Windows.

**Comment by meganrogge** [comment]
Yeah there have been several reports of issues with tasks that use the `amodio.tsl-problem-matcher` contributed problem matchers. I can reproduce on macOS

**Comment by meganrogge** [comment]
related

https://github.com/microsoft/vscode/issues/178698
https://github.com/microsoft/vscode/issues/149673#issuecomment-1246729245
