### ISSUE TITLE
doesn't load server and not showing page after rename to djecommerce

### ISSUE THREAD

**Issue by cyber-milanovicb** [microsoft/vscode#179766]
1. python rename.py demo djecommerce - done
2. python manage.py runserver

shows:
System check identified 1 issue (0 silenced).
April 12, 2023 - 08:12:31
Django version 4.2, using settings 'djecommerece.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CTRL-BREAK.

When I want to access the page it suddenly keeps loading the page forever, and nothing....

![image](https://user-images.githubusercontent.com/103489050/231453577-52323d63-0cda-454a-84fa-e9f106a8dcf2.png)
![image](https://user-images.githubusercontent.com/103489050/231453721-657ee063-759a-4ac7-a041-32bf1a12ca36.png)

Please help.

**Comment by roblourens** [comment]
Sorry, this sounds like an issue with your code or project configuration
