### ISSUE TITLE
Problem with  VS for python

### ISSUE THREAD

**Issue by 0zscar19** [microsoft/vscode#179703]
I'm trying to make a simply math in VS with python.

a = 2
b = 3
c = a + b

print (c) 

but it gave me this error:

>>> print (c) 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'c' is not defined
>>>

**Comment by lramos15** [comment]
Copying and pasting this code exactly works for me. Something is wrong with your setup.

**Comment by 0zscar19** [comment]
is there anyway to know how can I set up this correctly ?

**Comment by lramos15** [comment]
What version of python are you using? Maybe record a gif from https://gifcap.dev/

**Comment by 0zscar19** [comment]
For python i'm using 3.11 (64 bit)
The weird is that on the python works perfectly, just in  Visual studio doesn't work.


![Recording 2023-04-12 at 15 09 56 (1)](https://user-images.githubusercontent.com/115808579/231586083-0b3acf96-adea-4acb-bdba-2942b5553f1c.gif)

![Recording 2023-04-12 at 15 14 06](https://user-images.githubusercontent.com/115808579/231586651-9f2b96b7-8c6d-4f4d-a7d9-d8b8d394dee8.gif)

**Comment by lramos15** [comment]
The file you're showing is not saved. Does saving it before running fix it?

**Comment by 0zscar19** [comment]
How can I save it ? can you show me an example pls ? I think I did, just want to be sure.

**Comment by lramos15** [comment]
Just press CTRL + S

**Comment by 0zscar19** [comment]
Yes, it's save it and the error still there.
