### ISSUE TITLE
Notify users about installed deprecated extensions 

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#179756]
Currently if a user has a deprecated extension installed we just render that in the Extensions view. Looking at telemetry we noticed that users this is not a strong signal, and users still have a lot of deprecated extensions installed.

Due to that I suggest that we nudge the users more about deprecated extensions.
Especially if the deprecated extension has an alternative.

As @sandy081 suggests we could show a general depreciation prompt if users have deprecated extensions installed and allowing not to show this prompt again.

However I would love if the notification prompt offers the transition to the alternative extension if there is one.

So not sure if it would be notification per deprecated extension? What do you think?

**Comment by sandy081** [comment]
I think the notification is a general one guiding users to extensions view to see deprecated extensions. Users can take a necessary action from there.

**Comment by isidorn** [comment]
Ok. It would be nice if the flow is smooth, for example there is an action that opens the correct extension in the Extensions view. But I guess you already have that in mind :)

**Comment by sandy081** [comment]
> for example there is an action that opens the correct extension in the Extensions view.

Yes, there will be an action to list the deprecated extensions.

**Comment by sandy081** [comment]
To verify:

- Shutdown VS Code Insiders
- From CLI install extension `code-insiders --install-extension adashen.vscode-tomcat`
- Open Insiders and wait until you get the prompt

<img width="515" alt="image" src="https://user-images.githubusercontent.com/10746682/234339956-a3c22336-8ac6-4d13-a50b-23c88eae3df1.png">
