### ISSUE TITLE
NODE_OPTIONS environment variable value not present in VS Code

### ISSUE THREAD

**Issue by bszanto111** [microsoft/vscode#179712]
Type: <b>Bug</b>

I set NODE_OPTIONS as account environment variable to "--max-old-space-size=4096". When I open Process Explorer and there I check VS code's environment variables, NODE_OPTIONS is present there, but its value is empty. It should have inherited the value as it does for other environment variables. There is a similar issue, but the answer for that does not stand for the case of max-old-space-size as you can see there in the links: #164090

VS Code's environment variables captured with the Process Explorer (on the left side) and the global environment variables (on the right side):
![image](https://user-images.githubusercontent.com/62655896/231277131-49d29be4-70f6-436d-a81b-0b3ba5290907.png)

VS Code version: Code 1.73.0 (8fa188b2b301d36553cbc9ce1b0a146ccb93351f, 2022-11-01T15:34:06.111Z)
OS version: Windows_NT x64 10.0.19045
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 5600G with Radeon Graphics          (12 x 3900)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.30GB (8.32GB free)|
|Process Argv|--crash-reporter-id 1d2b4faf-cf60-4f28-8364-ad11ed51a46f|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-css-formatter|aes|1.0.2
gitlens|eam|13.5.0
gitlab-workflow|Git|3.61.0
git-graph|mhu|1.30.0
hg|mrc|1.8.1
vscode-proto3|zxh|0.5.5

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscoreces:30445986
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
nodejswelcome1:30587005
282f8724:30602487
pyind779:30671433
89544117:30613380
pythonsymbol12:30671437
a9j8j154:30646983
vscodeenable:30660116
pythonb192:30669360
functionswalk:30687959
pythonms35:30701012
pythonfmttextcf:30710682

```

</details>

**Comment by bszanto111** [comment]
I tried it now with 1.77.2 and the issue remains.

**Comment by bszanto111** [comment]
All of the Code.exe processes miss this variable setting.

**Comment by deepak1556** [comment]
Comment in https://github.com/microsoft/vscode/issues/164090#issuecomment-1338742244 still holds for this issue, when Electron application is packaged only the following two `NODE_OPTIONS` are allowed

```
--max-http-header-size
--http-parser
```
