### ISSUE TITLE
onDidChangeWindowState does not behave as expected on Web

### ISSUE THREAD

**Issue by 1123390260** [microsoft/vscode#179772]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.77.2
- OS Version: macOS 13.0

Steps to Reproduce:

1. Open up a Github CodeSpaces in browser.
2. Write a trivial extension that uses the `vscode.window.onDidChangeWindowState` api and logs the event out in its callback.
3. Run the extension and focus on the new tab (Extension Development Host tab).
4. Click outside the browser window, but the callback is not triggered.

I notice that it will only be triggered if I am switching tabs, but I think it should also react when the browser loses focus.

**Comment by joaomoreno** [comment]
Here's relevant info to fix this: https://stackoverflow.com/questions/28993157/visibilitychange-event-is-not-triggered-when-switching-program-window-with-altt

**Comment by antonioprudenzano** [comment]
Actually the vscode api already implements a focus/blur event handling for this reason.
