### ISSUE TITLE
Builtin official python support

### ISSUE THREAD

**Issue by tejinderss** [Microsoft/vscode#17975]
Hi

I just want to ask if there is any plan for the official support for python intellisense? If so is there any expected timeline for it ?

Thanks

**Comment by Daylien** [comment]
I think there are no plans for an official support. But you can download an [Python extension](https://marketplace.visualstudio.com/items?itemName=donjayamanne.python) where the Python Language is supported with Intellisense, Linting, Debugging .... and so on.

**Comment by Tyriar** [comment]
We recommend the Python extension that @Daylien mentioned and have invested in it. We don't have plans to bundle it though.
