### ISSUE TITLE
environmentVariableCollection.append behaves illogically on Linux

### ISSUE THREAD

**Issue by theIDinside** [microsoft/vscode#179759]
`ExtensionContext` has `environmentVariableCollection.append`  and `environmentVariableCollection.prepend` functionality that works, a little bizarre.

I've checked the source code out, it just operates like a naive `StringBuffer` on the environment variables where the appending and prepending is just _literal string_  pre-/app-ending, not actually an abstraction that understand environment variables.

Is this really desirable behavior? `environmentVariableCollection.append`, should, add a `:` before appending the value, as this is what Linux user would expect - otherwise VSCode should just expose the environment variables as a string buffer and let the user manipulate that, if such a naive approach is desired. At least it would make sense / be intuitive since it's then up to the user to make sure it's formatted correctly.

Currently, the end user now have to add `:foo` to appends and `foo:` to prepends. I would definitely recommend a change to this API, so that VSCode does the adding of `:` itself as this is what the interface implicitly suggests it does:

```ts
append(variable: string, value: string)
```
It appends a _value_ to the env variable. A value is separated by a `:`. The `:` is not _part_ of the value.

**Comment by Tyriar** [comment]
This is by design, we considered having it know about PATH specifically, but it's a general API for any environment variable and we opted to be more consistent than special-casing the PATH variable.
