### ISSUE TITLE
Open workspace from file uses wrong workspace folder path

### ISSUE THREAD

**Issue by sn321** [microsoft/vscode#179763]
Type: <b>Bug</b>

I use VSCode under Ubuntu LTS 20.04.
After one of the latest updates I discovered a new/wrong behavior when I want to open a workspace from file. The workspace file is located in my Home directory, but VSCode wants to open the projects from run/user/1000/...
The error message which is shown next to each project folder is "Unable to resolve workspace folder" which is not surprising because the workspace folder path is wrong.

VS Code version: Code 1.77.2 (e344f1f539a80912a0e9357cec841f36ce97a4e2, 2023-04-06T10:09:14.609Z)
OS version: Linux x64 5.15.0-69-generic snap
Modes: Restricted
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz (4 x 3408)|
|GPU Status|2d_canvas: unavailable_software<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>opengl: disabled_off<br>rasterization: disabled_software<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software<br>webgpu: disabled_off|
|Load (avg)|0, 0, 0|
|Memory (System)|7.73GB (5.66GB free)|
|Process Argv|--no-sandbox x4d-analyze-64.code-workspace --crash-reporter-id e448e20d-d960-499c-bac8-2adeeb19c230|
|Screen Reader|no|
|VM|100%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-pull-request-github|Git|0.62.0
better-cpp-syntax|jef|1.17.2
python|ms-|2023.6.0
vscode-pylance|ms-|2023.4.10
jupyter|ms-|2023.3.1000892223
jupyter-keymap|ms-|1.1.0
remote-containers|ms-|0.288.0
remote-ssh|ms-|0.100.0
remote-ssh-edit|ms-|0.84.0
remote-wsl|ms-|0.77.0
remote-explorer|ms-|0.4.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
nodejswelcome1cf:30587006
282f8724:30602487
pyind779:30671433
f6dab269:30613381
pythonsymbol12:30671437
vsccsb:30705552
azdwalk:30687957
pythonms35:30701012
pythonfmttext:30710681
pythonclientmvcf:30708686

```

</details>

**Comment by sn321** [comment]
Here is the sample content from the workspace file:
{
	"folders": [	
	{
            "path": "ProjectA"
        },
        {
            "path": "ProjectB"
        }
    ]
}

At the moment we found 2 work arounds;
1) use the full path starting from Home directory. This helps a bit, but is not working in my case because the absolut path must also work for the other team members in their VMs
2) When I open workspace folder with the file browser and open there a terminal to have to correct path I can open VSCode via the terminal command "code my.code-workspace" directly with the parameter which workspace file shall be used. Here it seems to work as expected

**Comment by bpasero** [comment]
@deepak1556 I feel this could be snap update related, see also https://github.com/microsoft/vscode/issues/180004 for a similar issue. Could it be that paths end up wrong in VS Code somehow?

**Comment by deepak1556** [comment]
Merging to https://github.com/microsoft/vscode/issues/180004
