### ISSUE TITLE
Performance Issue

### ISSUE THREAD

**Issue by yashp711** [microsoft/vscode#179741]
Type: <b>Performance Issue</b>

Starting up Vs code in my Computer take too long than as usual since last 3 days.

VS Code version: Code 1.77.2 (e344f1f539a80912a0e9357cec841f36ce97a4e2, 2023-04-06T10:08:05.978Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-10300H CPU @ 2.50GHz (8 x 2496)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|7.80GB (0.81GB free)|
|Process Argv|--crash-reporter-id 3a458cf5-4e4a-4308-b3e3-e3629f40a5bc|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	   185	  5268	code main
    0	    82	   164	fileWatcher [1]
    0	    28	  1432	   crashpad-handler
    0	    94	 10408	shared-process
    0	    82	  8968	     ptyHost
    0	   180	 11452	window [1] (Web Development - Visual Studio Code)
    0	   119	 13724	extensionHost [1]
    0	   101	  4416	     electron-nodejs ("C:\Users\DELL\AppData\Local\Programs\Microsoft VS Code\Code.exe" --ms-enable-electron-run-as-node "c:\Users\DELL\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\html-language-features\server\dist\node\htmlServerMain" --node-ipc --clientProcessId=13724)
    2	    92	 13932	window [2] (Issue Reporter)
    0	   147	 14772	   gpu-process
    0	    49	 16084	   utility-network-service
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (Web Development - Visual Studio Code)
|    Folder (Web Development): 2283 files
|      File types: svg(2012) css(45) png(40) js(27) map(22) scss(19) less(18)
|                  html(15) ttf(8) woff2(8)
|      Conf files:;
```

</details>
<details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-html-css|ecm|1.13.1
cmake-tools|ms-|1.13.45
cpptools|ms-|1.14.5
cpptools-extension-pack|ms-|1.3.0
LiveServer|rit|5.7.9
cmake|twx|0.0.17
JavaScriptSnippets|xab|1.8.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
vscccc:30610679
nodejswelcome1cf:30587006
2e4cg342:30602488
pyind779:30671433
f6dab269:30613381
vscrp:30673768
pythonsymbol12:30671437
2i9eh265:30646982
6233i204:30672705
vsctsb:30705553
azdwalk:30687957
pythonms35:30701012

```

</details>

**Comment by deepak1556** [comment]
Do you have McAfee antivirus installed, we had reports with the AV slowing down startup with recent update.

Refs https://github.com/microsoft/vscode/issues/178962

**Comment by yashp711** [comment]
Yes I have McAfee antivirus installed on my Computer.

**Comment by deepak1556** [comment]
Can you follow the steps in https://github.com/microsoft/vscode/issues/178733#issuecomment-1500812938 and exclude the `code.exe` binary.

Merging to https://github.com/microsoft/vscode/issues/178962
