### ISSUE TITLE
Use a more flexible indentation in different files

### ISSUE THREAD

**Issue by leaxoy** [Microsoft/vscode#17979]
Different language has different indent rule.
Java: always use 4 spaces.
Go: always use a tab with length 4.
Makefile: must use a tab.

But now, when I create a new `Makefile`, the indentation will use previous file rule(4 spaces)?
Always change settings is annoying.
For a high availability, we can add default indent rule for different file type.

**Comment by rebornix** [comment]
Dup of https://github.com/Microsoft/vscode/issues/11879
