### ISSUE TITLE
terminal font disapear after cat a file

### ISSUE THREAD

**Issue by TommyCat008** [microsoft/vscode#179779]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: latest
- OS Version: MacOS latest

there is a gif
https://github.com/TommyCat008/images/blob/main/9a1a3aab-6381-4076-9949-21af60da9639.gif

Steps to Reproduce:

1. cat a file 
2. type any character

**Comment by gjsjohnmurray** [comment]
Using `cat` on a binary file is liable to send escape sequences which mess up subsequent output. Why are you doing this?

**Comment by TommyCat008** [comment]
> Using `cat` on a binary file is liable to send escape sequences which mess up subsequent output. Why are you doing this?

I didn't mean to cat a binary, but I did it by accident and noticed an exception on subsequent input. Can the problem be fixed?
