### ISSUE TITLE
args entry not being acknowledging in launch.json 

### ISSUE THREAD

**Issue by lawalls46** [microsoft/vscode#179713]
Type: <b>Bug</b>

I am debugging python 3.10.6 in VSC and trying to read an external file that I would call as a command line argument.  I am using the launch.json file shown below which I have saved and verified on my drive. When I select "Debug Python File" using the right pointing triangle dropdown to the right of the editor group (with dropdowns "Run Python File", "Debug Python File" , "Run Current File in interactive window), the debugger throws IndexError exception when it reaches the code with my assignment of the "control_file". The sys.argv list has a length of 1 when I examine it in the Debug Console.  However, when I Debug the code using the green triangle in the left side panel ("Python: Current File"), the debugger does not throw an exception and runs normally. It could be that I have a misunderstanding of the function of these to paths or there may be an issue with VSC.  Is this normal? 

Thanks, L

control_file         = sys.argv[1]  # my call in the python code.
#-----------  my launch.json file  (below) -------------------------
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Python: Current File",
            "type": "python",
            "request": "launch",
            "program": "${file}",
            "console": "integratedTerminal",
            "justMyCode": true,
            "args": ["Control.txt"]
        }
    ]
}

VS Code version: Code 1.77.1 (b7886d7461186a5eac768481578c1d7ca80e2d21, 2023-04-04T23:21:11.906Z)
OS version: Windows_NT x64 10.0.19045
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz (16 x 2496)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|127.71GB (109.34GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (30)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-django|bat|1.10.0
githistory|don|0.6.20
python-environment-manager|don|1.0.4
python-extension-pack|don|1.7.0
gitlens|eam|13.5.0
vscode-firefox-debug|fir|2.9.8
gc-excelviewer|Gra|4.2.57
vsc-python-indent|Kev|1.18.0
markdown-shortcuts|mdi|0.12.0
git-graph|mhu|1.30.0
gather|ms-|2022.3.2
isort|ms-|2022.8.0
python|ms-|2023.6.0
vscode-pylance|ms-|2023.4.10
jupyter|ms-|2023.3.1000892223
jupyter-keymap|ms-|1.1.0
jupyter-renderers|ms-|1.0.15
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-slideshow|ms-|0.1.5
notepadplusplus-keybindings|ms-|1.0.7
vsliveshare|ms-|1.0.5834
autodocstring|njp|0.6.1
vscode-xml|red|0.24.0
vscode-perl|the|1.18.2
intellicode-api-usage-examples|Vis|0.2.7
vscodeintellicode|Vis|1.2.30
jinja|who|0.0.8
markdown-pdf|yza|1.4.4
markdown-all-in-one|yzh|3.5.1
simple-perl|zhi|0.0.4

(1 theme extensions excluded)

</details>

**Comment by Acrosicious** [comment]
The `launch.json` configuration is only used when running the code with the Debug view, e.g. "Python: Current File" or by pressing F5. The commands at the top right of the editor are just there to quickly run simple snippets, i.e. `python program.py` in the current environment. You could alternative probably run your code in the command line with `python program.py Control.txt`
