### ISSUE TITLE
Can't use VSCode Javascript debugger on insiders or recent release, crbug

### ISSUE THREAD

**Issue by rbavery** [microsoft/vscode#179734]
Type: <b>Bug</b>

I tried fresh installs of the recent releas eand insiders and both times get this error when running the following launch.json

errors
```
Fontconfig error: Cannot load default config file: No such file: (null)
crbug/1173575, non-JS module files deprecated.
(index)꞉6737:18:6736
INFO: Created TensorFlow Lite XNNPACK delegate for CPU.
```

launch.json
```

{
    "version": "0.2.0",
    "configurations": [
      {
        "type": "chrome",
        "request": "launch",
        "name": "Debug index.html",
        "url": "http://localhost:3000/index.html",
        "webRoot": "${workspaceFolder}",
        "sourceMaps": true,
        "trace": true
      }
    ]
  }
```

This error occurred after I came back to an untouched project after updating my system packages with a scheduled update.

to reproduce

```
git clone https://github.com/rbavery/animl-onnx
cd animl-onnx
code .
```
then copy the launch .json and run the debugger, after installing the javascript debugger extension.

in the browser I see connection refused, in the conosle I see the above errors. There's no helpful answer on stackoverflow: https://stackoverflow.com/questions/67191286/crbug-1173575-non-js-module-files-deprecated-chromewebdata-index%EA%9E%89530595551

VS Code version: Code - Insiders 1.78.0-insider (079272e4a37ceecd22dcebc3566bb46c8580a13c, 2023-04-11T11:00:43.766Z)
OS version: Linux x64 5.19.0-38-generic
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8600K CPU @ 3.60GHz (6 x 4175)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|1, 1, 1|
|Memory (System)|31.30GB (27.11GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2023.7.11011538
vscode-pylance|ms-|2023.4.11
js-debug-nightly|ms-|2023.4.517
autodocstring|njp|0.6.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythontb:30258533
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscod805cf:30301675
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30404738
cppdebug:30492333
vscaat:30438846
vsclangdf:30492506
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30618038
pylantcb52:30590116
nodejswelcome1:30587009
pyind779:30611226
pythonsymbol12:30651887
a9j8j154:30646983
showlangstatbar:30659908
pythonb192:30661256
defaultazurewalk:30687958
pythonms35:30671666
0bg3d529:30680467
7ij38806:30687742
pythonfmttext:30710679
pythonclientmv:30700173

```

</details>

**Comment by connor4312** [comment]
> in the browser I see connection refused

This indicates that nothing is listening on `localhost:3000`. You'll need to make sure you're running a program listening on that port.
