### ISSUE TITLE
Display glitching

### ISSUE THREAD

**Issue by BigM182** [microsoft/vscode#179745]
Type: <b>Performance Issue</b>

I have done eveything I know to solve this screen glitching in vscode  ,first thing I did update to windows 11 and the problem still there , second I unstall my graphics adapter , third thing I unstall the app directly from setting so many times nothing changed , fourth I install in revo uninstaller and delete everything belongs to the app and all cache and download it again the problem still there please help me tell me if you can solve me this issue please I am really really depressed because of this.

VS Code version: Code 1.77.2 (e344f1f539a80912a0e9357cec841f36ce97a4e2, 2023-04-06T10:08:05.978Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz (8 x 2803)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|7.79GB (1.94GB free)|
|Process Argv|--crash-reporter-id b9e28c3f-f06e-4353-9bac-e3d1476ede9f|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	    92	 11328	code main
    0	   153	  2020	window [1] (index.html - website for all AI tools project - Visual Studio Code)
    0	    28	  4340	   crashpad-handler
    0	    41	  5056	   utility-network-service
    0	   134	  8600	   gpu-process
    0	    86	  9632	window [2] (Issue Reporter)
    0	    75	 11032	fileWatcher [1]
    0	    92	 14364	shared-process
    0	    78	 13976	     ptyHost
    0	   104	 15840	extensionHost [1]
    0	   100	 11720	     electron-nodejs ("C:\Users\Marhaba\AppData\Local\Programs\Microsoft VS Code\Code.exe" --ms-enable-electron-run-as-node "c:\Users\Marhaba\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\html-language-features\server\dist\node\htmlServerMain" --node-ipc --clientProcessId=15840)
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (index.html - website for all AI tools project - Visual Studio Code)
|    Folder (website for all AI tools project): 1 files
|      File types: html(1)
|      Conf files:;
```

</details>
Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
nodejswelcome1cf:30587006
2e4cg342:30602488
pyind779:30671433
89544117:30613380
pythonsymbol12:30671437
2i9eh265:30646982
vsctsb:30705553
vscodeenable:30660116
functionswalk:30687959
pythonms35:30701012
pythonfmttext:30710681

```

</details>

![Screenshot 2023-04-11 054433](https://user-images.githubusercontent.com/129101634/231348463-5344a937-7bbb-4e6c-a4d3-1158696273bd.png)

**Comment by deepak1556** [comment]
Can you disable hw acceleration in the application using the following steps https://code.visualstudio.com/updates/v1_40#_disable-gpu-acceleration

Merging to https://github.com/microsoft/vscode/issues/124226

**Comment by BigM182** [comment]
thank you man it works fine thank from my heart you saved me
