### ISSUE TITLE
Open link in Linux requires alt-click, but alt is reserved!

### ISSUE THREAD

**Issue by VividLemon** [microsoft/vscode#179787]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: latest
- OS Version: Linux

On Linux the alt click is system reserved. The application already knows about this as there is an option to change the multi-cursor select option. However, when trying to open _links_, it still requires alt clicking. 

Steps to Reproduce:

1. Create a text file
2. Paste a link
3. Try to open using alt click
Doesn't work

My suggestion is to have an option to change this behavior to use different keybinds. 

You are able to open links by control+alt+click, perhaps this should just become the linux default (or an option change default)

**Comment by roblourens** [comment]
Which distro has this alt-click behavior, and what does it do?

**Comment by VividLemon** [comment]
> Which distro has this alt-click behavior, and what does it do?

Is it not globally reserved? Ubuntu branches should have it as window dragging. Something pretty dumb that windows doesn't have lmao.

**Comment by roblourens** [comment]
I don't see that behavior in Ubuntu. But it looks like this depends on the setting `editor.multiCursorModifier` if you want to swap the multicursor and open link keys, if that helps.

**Comment by VividLemon** [comment]
> I don't see that behavior in Ubuntu. But it looks like this depends on the setting `editor.multiCursorModifier` if you want to swap the multicursor and open link keys, if that helps.

Are you sure you dont see the behavior? The behavior is pretty well documented. The hotkey isn't a simple click -- its holding the alt key and dragging the cursor. 

But the multi cursor option, assuming its the same option, has always been on for me. It makes it so I can use multiple cursors, but its never had an affect on opening links

**Comment by VividLemon** [comment]
Okay, I have come with further news!

I have recently distro hopped. During my switch, saw that if I toggle on `switch to alt click for multi cursor`. Follow link goes from ctrl click to alt click

With multi cursor becoming ctrl click:

![image](https://user-images.githubusercontent.com/31498096/232245679-b3773724-7a70-42e2-baca-b388e4e84b42.png)

With multi cursor alt click: 

![image](https://user-images.githubusercontent.com/31498096/232245788-4ef0e4f9-9150-4032-9675-37155ce47617.png)

On my previous distro, alt-click (and hold) was the functionality for moving a window. Which, as you can see, breaks this functionality. 

On my current distro, that keybind has switched. So, as it stands, I'm not quite sure where to go with this issue. On my last distro, I wasn't ever able to open links, so I'm not sure the best fix for that. But everything is "working as intended", so I'm not sure what there is to fix.
