### ISSUE TITLE
keyboard shortcut

### ISSUE THREAD

**Issue by adzannyakbar** [microsoft/vscode#179747]
Type: <b>Bug</b>

i don't like new line shortcut keyboard ctrl+enter i want just only enter

VS Code version: Code 1.77.2 (e344f1f539a80912a0e9357cec841f36ce97a4e2, 2023-04-06T10:08:05.978Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 5600G with Radeon Graphics          (12 x 3893)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.37GB (6.95GB free)|
|Process Argv|. --crash-reporter-id cbad0644-58ca-4acb-890e-3a661b58155b|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (21)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-tailwindcss|bra|0.9.11
dart-code|Dar|3.62.0
flutter|Dar|3.62.0
vscode-eslint|dba|2.4.0
vscode-styled-components|die|0.1.33
es7-react-js-snippets|dsz|4.4.3
gitlens|eam|13.5.0
EditorConfig|Edi|0.16.4
prettier-vscode|esb|9.10.4
auto-close-tag|for|0.5.14
auto-complete-tag|for|0.1.0
auto-rename-tag|for|0.1.10
vscode-react-typescript|inf|1.3.1
pretty-formatter|mbl|0.2.2
remote-wsl|ms-|0.77.0
vsliveshare|ms-|1.0.5857
vscode-yaml|red|1.12.2
markdown-preview-enhanced|shd|0.6.8
vscode-java-debug|vsc|0.49.1
vscode-java-pack|vsc|0.25.10
JavaScriptSnippets|xab|1.8.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vscaat:30438848
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
vscccc:30610679
nodejswelcome1:30587005
3biah626:30602489
pyind779:30671433
89544117:30613380
pythonsymbol12:30671437
6233i204:30672705
pythonb192cf:30669361
functionswalk:30687959
pythonms35:30701012
f08j5886:30706078
pythonclientmv:30708685

```

</details>

**Comment by ulugbekna** [comment]
You are able to change the shortcuts to your taste - see https://code.visualstudio.com/docs/getstarted/keybindings and possibly more specifically https://code.visualstudio.com/docs/getstarted/keybindings#_keyboard-shortcuts-editor
