### ISSUE TITLE
Downloaded VS for Mac OS X (Sierra) 2017-01-01, but "cannot be opened because of a problem"

### ISSUE THREAD

**Issue by posfr** [Microsoft/vscode#17985]
- VSCode Version: As downloaded 2017-01-01
- OS Version: macOS Sierra Version 10.12.2

Steps to Reproduce:

1. Downloaded VSCode. 
2. Allowed macOS to run Apps from Anywhere
3. Launched VSCode
4. "Visual Studio Code cannot be opened because of a problem.
5. Problem details and System Configuration reported as follows:

Process:               Electron [3047]
Path:                  /Applications/Visual Studio Code.app/Contents/MacOS/Electron
Identifier:            com.microsoft.VSCode
Version:               1.8.1 (1.8.1)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           Electron [3047]
User ID:               501

Date/Time:             2017-01-01 23:45:36.974 +1030
OS Version:            Mac OS X 10.12.2 (16C67)
Report Version:        12
Anonymous UUID:        2A71EB9F-A759-0AD7-D75C-BCF21B613AE5

Sleep/Wake UUID:       4F8B9D22-7295-4FFE-AE2F-9686D2A08245

Time Awake Since Boot: 14000 seconds
Time Since Wake:       3500 seconds

System Integrity Protection: enabled

Crashed Thread:        0

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    DYLD, [0x1] Library missing

Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  Library not loaded: @rpath/Electron Framework.framework/Electron Framework
  Referenced from: /Applications/Visual Studio Code.app/Contents/MacOS/Electron
  Reason: no suitable image found.  Did find:
	/Applications/Visual Studio Code.app/Contents/MacOS/../Frameworks/Electron Framework.framework/Electron Framework: file too short

Binary Images:
       0x10abd6000 -        0x10abd6ff7 +com.microsoft.VSCode (1.8.1 - 1.8.1) <32397E1E-4249-3B36-99B2-C1B61154B991> /Applications/Visual Studio Code.app/Contents/MacOS/Electron
       0x10e800000 -        0x10e83d267  dyld (421.2) <947FC440-80F9-32F7-A773-6FC418FE1AB7> /usr/lib/dyld

Model: iMac11,1, BootROM IM111.0034.B04, 4 processors, Intel Core i5, 2.66 GHz, 8 GB, SMC 1.54f36
Graphics: ATI Radeon HD 4850, ATI Radeon HD 4850, PCIe, 512 MB
Memory Module: BANK 0/DIMM0, 2 GB, DDR3, 1067 MHz, 0x80CE, 0x4D34373142353637334648302D4346382020
Memory Module: BANK 1/DIMM0, 2 GB, DDR3, 1067 MHz, 0x80CE, 0x4D34373142353637334648302D4346382020
Memory Module: BANK 0/DIMM1, 2 GB, DDR3, 1067 MHz, 0x83DA, 0x4D474E303247363445314246324D542D4242
Memory Module: BANK 1/DIMM1, 2 GB, DDR3, 1067 MHz, 0x80AD, 0x484D54313235533642465238432D47372020
AirPort: spairport_wireless_card_type_airport_extreme (0x168C, 0x8F), Atheros 9280: 4.0.74.0-P2P
Bluetooth: Version 5.0.2f4, 3 services, 27 devices, 1 incoming serial ports
Network Service: AirPort, AirPort, en1
Network Service: Ethernet, Ethernet, en0
Serial ATA Device: ST31000528AS, 1 TB
Serial ATA Device: OPTIARC DVD RW AD-5680H
USB Device: USB 2.0 Bus
USB Device: Hub
USB Device: Keyboard Hub
USB Device: Apple Keyboard
USB Device: Usb Mouse
USB Device: IR Receiver
USB Device: Built-in iSight
USB Device: USB 2.0 Bus
USB Device: Hub
USB Device: ANT USB-m Stick
USB Device: Card Reader
USB Device: BRCM2046 Hub
USB Device: Bluetooth USB Host Controller
Thunderbolt Bus:

**Comment by bpasero** [comment]
This looks like maybe there are files missing from the download? Can you download on another machine and try if it reproduces?

**Comment by posfr** [comment]
Hi Benjamin,

Thank you for your email.

Per your suggestion, I tried again on two different machines and on several separate occasions – each time with the same problem.

However, today I found the cause of and solution to the problem and that many others have experiences this type of problem; for example https://discuss.atom.io/t/dont-work-with-mac-osx-10-9-2/6019/6

To quote “You need to use the standard [mac OS X] Archive Utility to unzip the app.  (I was using a third party zip app called…)”.

Likewise, on all of my failed attempts, I was using my own favourite third party utility to extract “Visual Studio Code.app” from  VSCode-darwin-stable.zip.

On using the standard mac OS X Archive Utility, it worked.

It might be worth making a note of this requirement on the download site.

Many thanks &
Regards,
Franz

**Comment by bpasero** [comment]
@gregvanl fyi on the website we should mention to unzip using macOS unzipper.

**Comment by ssamayoa** [comment]
@gregvanl & @bpasero:

> on the website we should mention to unzip using macOS unzipper.

Would be nice if that was the case, I suffer alike problem because I unpacked the zip file with other app than macOS unzipper - resolved until I found this thread.

Regads!
