### ISSUE TITLE
Unable to run Code in Ubuntu

### ISSUE THREAD

**Issue by shanalikhan** [Microsoft/vscode#17980]
After the last code update that is 1.8.1 i am unable to run code in ubuntu. 
When i open the code, it gets opens but except the top menus everything is black.
I tried to select any commands from the file menu and i think they are performed but i cant see it , because when i open the file menu ubuntu shows its opened but its cuts after few pixels from the editor starts.

I have tried to uninstall and reinstall code, but problem is still there
Tried with removing the extension folder and user folder after uninstalling also

When the code is minimized black screen appears on the code window size on other windows, it keeps showing black screen on other programs until code is closed.

**Comment by shanalikhan** [comment]
Still waiting ... 😞

**Comment by Tyriar** [comment]
Are you running in a VM? You could try running `code --disable-gpu`?

/cc @bpasero

**Comment by Tyriar** [comment]
Here is the [download for 1.8.0](https://az764295.vo.msecnd.net/stable/38746938a4ab94f2f57d9e1309c51fd6fb37553d/code-stable-code_1.8.0-1481651903_amd64.tar.gz) to unblock you. You could also try [insiders](https://code.visualstudio.com/insiders).

**Comment by shanalikhan** [comment]
I have tried insiders same problem, i am unable to capture the screen shoot when code is opened, i see black screen only. 
Yes im running in a VM
It works by running disable gpu but before this update, it was working fine

> Here is the download for 1.8.0 to unblock you

Do i have to install it ? what is the difference in this build

**Comment by Tyriar** [comment]
@shanalikhan here are the changes included in the 1.8.1 https://github.com/Microsoft/vscode/milestone/34?closed=1

If it's by a VM it's likely an upstream problem (Electron and/or Chromium).

**Comment by Asuza** [comment]
I'm having this same problem in Fedora 25 on the Enlightenment DE. When Enlightenment is using Software Rendering, then Code 1.8.1 (I've not tried other versions) completely locks up when I try to use any of the menus. Using `code --disable-gpu` seems to fix that particular issue.

Additionally, switching Enlightenment to use OpenGL allows Code to launch normally, without any special flags.

**Comment by shanalikhan** [comment]
> If it's by a VM it's likely an upstream problem (Electron and/or Chromium).
Actually i am using code since many versions earlier and its working fine. When i updated to latest one it shown such behavior.
Although it works  `code --disable-gpu` for code 1.8.1 but previously it was working.
If there is problem with electron then its fine, but i just wanted to let you know i faced after updating code

**Comment by cserret** [comment]
I couldn't get syntax highlighting for es5 to work with 1.8.1. I removed Code, installed 1.8.0, and my syntax highlighting is back. It did say an "Update is Avaliable" - for 1.8.1, which I declined. :)

**Comment by shanalikhan** [comment]
Latest Version works.
So i think i can close this issue.
