### ISSUE TITLE
VSCode crashes when building ionic app

### ISSUE THREAD

**Issue by elless** [Microsoft/vscode#17984]
I'm using VSCode to write an [Ionic app](http://ionicframework.com/). 
Since one of the recent VSCode updates, each time I run Ionic's build command - the VSCode crashes.  This also happens to a peer of mine that uses Windows (however to others in the group that use Mac, this doesn't happen). I tried to uninstall and install the VSCode again, however this didn't help.
Is a similar issue known to you?  Is there some workaround for this?  (It's pretty annoying that each time I build I have to restart the editor).

- VSCode Version: Code 1.8.1 (ee428b0eead68bf0fb99ab5fdc4439be227b6281, 2016-12-19T14:49:23.350Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

|Extension|Author|Version|
|---|---|---|
|vscode-stylefmt|mrmlnc|2.1.0|
|csharp|ms-vscode|1.5.3|
|annotator|ryu1kn|0.10.1|
|stylelint|shinnn|0.20.1|
|autoimport|steoates|1.2.2|

---

Steps to Reproduce:

(I'll try to reproduce this with a sample Ionic app and see if this also happens and update the issue if I am successful)

**Comment by joaomoreno** [comment]
From where do you run the Ionic build command?

**Comment by bpasero** [comment]
@elless ping
