### ISSUE TITLE
All Extensions Taking 20+ minutes to install in Devcontainer on M1 Mac

### ISSUE THREAD

**Issue by ariedl** [microsoft/vscode#179827]
Type: <b>Bug</b>

New Issue.  Since about 4-6 weeks ago when rebuilding and reopening in container (or creating a new devcontainer) container startup and vsc server installation is normal, however extensions are taking 20+ minutes each to install.  This used to take <30 seconds for all extensions.  Specifically python, pylance, and jupyter.

I am building amd64 using quemu emulation on a native arm64 system.  However, extension install had been 'normal' for 6+ months prior to onset.

VS Code version: Code 1.77.3 (Universal) (704ed70d4fd1c6bd6342c436f1ede30d1cff4710, 2023-04-12T09:19:37.325Z)
OS version: Darwin arm64 22.4.0
Modes:
Sandboxed: No
Remote OS version: Linux x64 5.15.49-linuxkit

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Max (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|3, 3, 3|
|Memory (System)|64.00GB (3.82GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|Dev Container: Python 3|
|OS|Linux x64 5.15.49-linuxkit|
|CPUs|unknown (6 x 0)|
|Memory (System)|31.31GB (22.95GB free)|
|VM|0%|
</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
remote-containers|ms-|0.288.0
remote-ssh|ms-|0.100.0
remote-ssh-edit|ms-|0.84.0
remote-explorer|ms-|0.4.0
vscode-eslint|dba|2.4.0
vscode-drawio|hed|1.6.6
python|ms-|2023.4.1
vscode-pylance|ms-|2023.3.30
jupyter|ms-|2023.3.1201040234
jupyter-keymap|ms-|1.1.0
jupyter-renderers|ms-|1.0.15
vscode-jupyter-cell-tags|ms-|0.1.8

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscoreces:30445986
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
nodejswelcome1cf:30587006
3biah626:30602489
pyind779:30671433
f6dab269:30613381
pythonsymbol12:30671437
2i9eh265:30646982
showlangstatbar:30672706
vsctsb:30705553
azdwalk:30687957
pythonms35:30701012
pythonfmttext:30710681
pythonclientmvcf:30708686

```

</details>

**Comment by ryboe** [comment]
I'm also experiencing this problem. I'm installing these extensions:

```
davidanson.vscode-markdownlint
eamodio.gitlens
golang.go
ms-azuretools.vscode-docker
redhat.vscode-yaml
```

I reproduce the issue by deleting the old devcontainer image (produced by `devcontainer build`) with `docker container rm`. Then I run `devcontainer open`. Some extensions install very quickly, but others take an eternity. The specific extensions that struggle to install are not reproducible. For example, sometimes `golang.go` installs quickly. Sometimes it takes forever.

Apple M1 Max 32 GB running macOS 13.3.1.
The devcontainer is built for the `linux/amd64` platform, but it's running on Apple Silicon.
[My `ryboe/q` repo](https://github.com/ryboe/q) is where I'm experiencing the problem. It uses an image based on `mcr.microsoft.com/vscode/devcontainers/base:alpine`.

**Comment by ariedl** [comment]
In the absence of more verbose logging, I attached to the above container while it was installing and ran htop to see what it was doing.  Here are few screenshots:

![Screenshot 2023-04-17 at 10 32 40](https://user-images.githubusercontent.com/10567932/232552027-1a266973-9547-4d1a-b30c-2060294a0e3f.png)

![Screenshot 2023-04-17 at 10 32 58](https://user-images.githubusercontent.com/10567932/232552068-b4add947-e321-4ed5-bc19-9d5aa4cf417a.png)

You can see in the first image that the cpu allocated to the container is pinned.  When I wrap one of the offending commands it looks like it's hung at a process named 'vice-sign'.

**Comment by sandy081** [comment]
Can you please add following setting in the remote settings.json file and retry?

```
"extensions.verifySignature": false
```

CC @isidorn

**Comment by ariedl** [comment]
After adding:
`"extensions.verifySignature": false`

to .devcontainer/devcontainer.json in customizations.vscode.settings such that the entire stanza is:

`"customizations": {"vscode":{
		"settings": { 
			"python.defaultInterpreterPath": "/usr/local/bin/python",
			"python.linting.enabled": true,
			"python.linting.pylintEnabled": true,
			"python.formatting.autopep8Path": "/usr/local/py-utils/bin/autopep8",
			"python.formatting.blackPath": "/usr/local/py-utils/bin/black",
			"python.formatting.yapfPath": "/usr/local/py-utils/bin/yapf",
			"python.linting.banditPath": "/usr/local/py-utils/bin/bandit",
			"python.linting.flake8Path": "/usr/local/py-utils/bin/flake8",
			"python.linting.mypyPath": "/usr/local/py-utils/bin/mypy",
			"python.linting.pycodestylePath": "/usr/local/py-utils/bin/pycodestyle",
			"python.linting.pydocstylePath": "/usr/local/py-utils/bin/pydocstyle",
			"python.linting.pylintPath": "/usr/local/py-utils/bin/pylint",
			"extensions.verifySignature": false
		},`

All extensions installed in a 'normal' amount of time.  It does seem as though the verify signature step is directly impacting installation time.

**Comment by isidorn** [comment]
fyi @dtivel

**Comment by ryboe** [comment]
Great discovery, @ariedl! Setting `"customizations.vscode.settings.extensions.verifySignature: false"` fixed it for me too. All the extensions install very quickly now. Thanks!

**Comment by isidorn** [comment]
Closing as dup of https://github.com/microsoft/vscode/issues/174632
