### ISSUE TITLE
Pasting not working

### ISSUE THREAD

**Issue by Sebo1411** [microsoft/vscode#179886]
Type: <b>Bug</b>

Start some python program that requires input from user. I am unable to paste anything into the terminal because the output is always "^V" even when trying to paste from clipboard. Otherwise the paste works fine and even in regular terminal.

VS Code version: Code 1.77.3 (704ed70d4fd1c6bd6342c436f1ede30d1cff4710, 2023-04-12T09:16:02.548Z)
OS version: Windows_NT x64 10.0.19044
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-10400F CPU @ 2.90GHz (12 x 2904)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.92GB (7.03GB free)|
|Process Argv|--crash-reporter-id 1e46f1e8-dfdb-4b1c-8d4b-909ee527861a|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2023.6.0
vscode-pylance|ms-|2023.4.10
jupyter|ms-|2023.3.1201040234
jupyter-keymap|ms-|1.1.0
jupyter-renderers|ms-|1.0.15
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-slideshow|ms-|0.1.5
remote-wsl|ms-|0.77.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263cf:30335440
vscorecescf:30445987
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
nodejswelcome1cf:30587006
3biah626:30602489
pyind779:30671433
f6dab269:30613381
pythonsymbol12:30671437
a9j8j154:30646983
vsctsb:30705553
azdwalk:30687957
pythonms35:30701012
pythonclientmv:30708685

```

</details>

**Comment by meganrogge** [comment]
What does the output say when you run the command `Developer: Toggle Keyboard Shortcuts Troubleshooting` and do `ctrl+v` in the terminal?

**Comment by Sebo1411** [comment]
I can't run that command, I can't even run `View: Show Commands` . I reinstalled vs code today and before that deleted all my settings and preferences. I reinstalledit because the pasting didn't work.

**Comment by meganrogge** [comment]
pls attach a gif

**Comment by Sebo1411** [comment]
Resolved it by changing in Keyboard shortcuts:
{
  "key": "ctrl+v",
  "command": "workbench.action.terminal.sendSequence",
  "when": "terminalFocus && !accessibilityModeEnabled && terminalShellType == 'pwsh'"
}

to:
{
  "key": "ctrl+shift+v",
  "command": "workbench.action.terminal.sendSequence",
  "when": "terminalFocus && !accessibilityModeEnabled && terminalShellType == 'pwsh'"
}
