### ISSUE TITLE
[GitHub] Recovery release template updates link points hard to 1.39 release

### ISSUE THREAD

**Issue by AnrDaemon** [microsoft/vscode#179858]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: not relevant
- OS Version: not relevant

Steps to Reproduce:

1. Open any recent recovery release.
2. Check "updates" link.

the link points hard to https://code.visualstudio.com/updates/v1_39 release notes. It should point either to a respective release, or to https://code.visualstudio.com/updates/ which is a redirect to a recent release.

**Comment by chrmarti** [comment]
Could you explain what "Open any recent recovery release." refers to? Are you opening VS Code or are you opening the website? Which URL?

**Comment by AnrDaemon** [comment]
This, for example: https://github.com/microsoft/vscode/releases/tag/1.77.3

![image](https://user-images.githubusercontent.com/6532485/232028528-0ba432b1-b574-4cfc-bf25-94e74dcc4c75.png)

**Comment by TylerLeonhardt** [comment]
Thanks! Fixed
