### ISSUE TITLE
"Undo Last Commit" should be grayed out if there are no commits.

### ISSUE THREAD

**Issue by bjtucker** [Microsoft/vscode#1798]
After initializing git repository, but before committing, I can select "Undo Last Commit" from the "..." menu. That fails, of course. The resulting git reset HEAD~ won't work if there are no commits.

Undo Last Commit should be grayed out if HEAD doesn't have a parent.

Here's the log:

```
git init
git fetch
fatal: No remote repository specified.  Please, specify either a URL or a
remote name from which new revisions should be fetched.
git reset HEAD~
fatal: ambiguous argument 'HEAD~': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
git fetch
fatal: No remote repository specified.  Please, specify either a URL or a
remote name from which new revisions should be fetched.
git fetch
fatal: No remote repository specified.  Please, specify either a URL or a
remote name from which new revisions should be fetched.
git fetch
fatal: No remote repository specified.  Please, specify either a URL or a
remote name from which new revisions should be fetched.
```

**Comment by joaomoreno** [comment]
It should... Dependent on #21131

**Comment by joaomoreno** [comment]
To keep the number of issues in our inbox on a manageable level, we're closing issues that have been on the backlog for a long time but haven't gained traction: We look at the number of votes the issue has received and the number of duplicates issues filed.

Thanks for your understanding. Happy coding!
