### ISSUE TITLE
Welcome Page customization

### ISSUE THREAD

**Issue by szabolcsdombi** [microsoft/vscode#179844]
Hi there, thank you for vscode it is amazing!

In the last update the welcome page got less useful for me.
The recently opened list, the only compoment I use got shrinked too much.

![image](https://user-images.githubusercontent.com/11232402/231688733-984d2740-771f-48c7-874e-d60a251890b0.png)

I would like to remove the entire Start section and keep a full page of "Recent".

Is there a way to customize the start screen?

**Comment by gjsjohnmurray** [comment]
I don't think this kind of customization is currently possible. However there **is** and issue about the recent layout change. See #179527, which I hope @bhavyaus is going to reopen and deal with.
