### ISSUE TITLE
VSCode on Windows 10 + Docker: Wrong build path

### ISSUE THREAD

**Issue by max06** [Microsoft/vscode#17986]
- VSCode Version: 1.8.1 (stable)
- OS Version: Windows 10 Build 14393

Steps to Reproduce:

1. Install Docker for Windows
2. Install VSCode
3. Add Docker extension
4. Create an empty Folder (eg MicroServiceTemplate) and open it in VSCode
5. Generate a Dockerfile from the command palette with default settings
6. Run Docker: Build from the command palette

Here the questions are already filled with the wrong values, like selecting the Dockerfile, it shows `e\Dockerfile` 

The Build fails then with ```C:\Users\max06\OneDrive\Dokumente\Develop\MicroServiceTemplate>docker build -f e\Dockerfile -t e:latest e
unable to prepare context:
unable to evaluate symlinks in context path: GetFileAttributesEx C:\Users\max06\On
eDrive\Dokumente\Develop\MicroServiceTemplate\e: Das System kann die angegebene Da
tei nicht finden.``` 

When I try to build it manually with correct parameters, it works.

**Comment by max06** [comment]
I could reproduce the problem on a second windows machine, but not on an ubuntu system.

**Comment by rebornix** [comment]
@max06 I think we can start investigation from the docker extension.

**Comment by rebornix** [comment]
This issue was moved to Microsoft/vscode-docker#51
