### ISSUE TITLE
Running `code .` on web vscode terminal cannot open a new window

### ISSUE THREAD

**Issue by zanminkian** [microsoft/vscode#179870]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.77.3
- OS Version: MacOS
- Browser: Newest chromium based browser. (Old version chromium based browser  (like chrome 100)  works well, I tested.)

Steps to Reproduce:

1. Run `docker run -it --init -p 3000:3000 gitpod/openvscode-server` in a terminal like iTerm2. (Not only openvscode-server has this bug, but also [coder/code-server](https://github.com/coder/code-server) has this bug too).
<img width="788" alt="image" src="https://user-images.githubusercontent.com/35495628/231766548-199a4c25-dde9-4549-b034-d3b1723841d1.png">

2. Open a newest chromium based browser, like `Edge`, and visit `http://localhost:3000`. And then install this website as PWA.
3. Stretch and  maximize the PWA.
4. Run `code .` in the PWA terminal. It doesn't works. (What I expect is opening a new window)
<img width="1792" alt="image" src="https://user-images.githubusercontent.com/35495628/231767977-134f699c-7215-4652-b99e-ad97df30456d.png">

5.  Shrink the PWA window to smaller a little bit. And then Run `code .` in the PWA terminal, it will open a new window as I expected.
<img width="1792" alt="image" src="https://user-images.githubusercontent.com/35495628/231769823-e043de17-cccb-4a39-9a14-6d4d49bd3b46.png">

**Comment by sandy081** [comment]
I do not think this is supported in VS Code. Please file the issue against the open vscode server.

**Comment by zanminkian** [comment]
Hello @sandy081, I believe this is the bug of vscode instead of open vscode server. Please reopen it.
I am going to show you another way to reproduce this bug.

1. Run `docker run -it --net host ubuntu`
2. Run `apt-get update && apt install wget`
3. Run `wget -O- https://aka.ms/install-vscode-server/setup.sh | sh`. **Docs**: https://code.visualstudio.com/blogs/2022/07/07/vscode-server
4. Run `code-server serve-local`
5. Visit `http://localhost:8000` on your newest Edge browser. And install the web app to PWA.
6. Stretch and maximize the PWA.
7. Run code . in the PWA terminal. It doesn't works. (What I expect is opening a new window)
<img width="1792" alt="image" src="https://user-images.githubusercontent.com/35495628/233838200-1ef56587-6c3d-4843-81a0-2443c82de516.png">

**Comment by connor4312** [comment]
Duplicates https://github.com/microsoft/vscode-remote-release/issues/4451

**Comment by zanminkian** [comment]
Hi @connor4312, the issue you post is not relative with this issue, I think.
- Old browser works well. Such as `Chrome 100` (released on March 29, 2022).
- This bug will appear only when the web vscode PWA stretched to the maximize on the screen.

**Comment by connor4312** [comment]
Thanks for the report, this looks like a bug in Chromium. I've reported the issue here: https://bugs.chromium.org/p/chromium/issues/detail?id=1441966
