### ISSUE TITLE
Key combination (Shift+)Opt+Z doesn't work on Mac

### ISSUE THREAD

**Issue by quendimax** [microsoft/vscode#179869]
Type: <b>Bug</b>

Steps to reproduce:
1. Open a new file in VSCode on Mac M1, macOS Ventura 13.3.1.
2. Switch to keylayout with additional symbols with Opt key (Polish for instance).
3. Type Opt+Z or Shift+Opt+Z.

Expected result: ż and Ż (z with dot above) correspondingly.
Actual result: nothing.

Now it looks like the issue is reproduced ONLY with Z key. The others work well.
Also I tried to write text with Polytonic Greek layout, and got the same issue only with Opt+Z, but Shift+Opt+Z worked correctly.

Interesting thing is that in the Issue Reporter window the key combination works correctly.

VS Code version: Code 1.77.3 (704ed70d4fd1c6bd6342c436f1ede30d1cff4710, 2023-04-12T09:41:48.638Z)
OS version: Darwin arm64 22.4.0
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|1, 2, 2|
|Memory (System)|16.00GB (1.03GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
vscccc:30610679
nodejswelcome1cf:30587006
3biah626:30602489
pyind779:30671433
f6dab269:30613381
pythonsymbol12:30671437
2i9eh265:30646982
showlangstatbar:30672706
vsctsb:30705553
pythonb192:30669360
azdwalk:30687957
pythonms35:30701012
03d35959:30706073
pythonclientmv:30708685

```

</details>

**Comment by alexdima** [comment]
That is because, by default, Option+Z is bound to toggle word wrap. You can unbind this by opening the keybindings editor (cmd+K cmd+S), searching for Option+Z and removing the binding:

<img width="857" alt="image" src="https://user-images.githubusercontent.com/5047891/232041590-b4d2449c-9aea-4ef7-944f-3c53de49855a.png">

**Comment by quendimax** [comment]
So easy. Thank you.
Actually I could guess to check the keybindings. Sorry to trouble you.
