### ISSUE TITLE
Run and Debug not available in devcontainer

### ISSUE THREAD

**Issue by GOVYANSONG** [microsoft/vscode#179862]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 
- 1.77.3
- OS Version: 
Windows_NT x64 10.0.19045

Steps to Reproduce:

1. create a typescript / nodejs app 
2. add devcontainer config 
3. add .vscode/launch.json
4. open folder in dev container
5. open a typescript file
6. under Run menu, it shows Install additional debuggers

as observed, the launch.json is ignored by vscode.

**Comment by GOVYANSONG** [comment]
When launch.json is open in editor, there is no intellisense either.

**Comment by roblourens** [comment]
Can you show a screenshot of what you're seeing? And do you see any errors in the devtools console (Help > Toggle Developer Tools)

**Comment by GOVYANSONG** [comment]
![vscode_err_02](https://user-images.githubusercontent.com/36177352/232017602-9920b1de-5558-46ec-991e-3a8e8f4df77c.png)
![vscode_err_01](https://user-images.githubusercontent.com/36177352/232017617-006fcca4-4a34-4f68-8105-a95659c7eb90.png)

Screenshots have been attached as requested. An error thrown by extension host could be suspicious. FYI my devcontainer is node alpine 16.14.2.

**Comment by roblourens** [comment]
Looks like the EH broke in this devcontainer, but I'm not sure how to interpret that message

**Comment by chrmarti** [comment]
Please see https://github.com/microsoft/vscode/issues/178748#issuecomment-1495225249. Continuing there.
