### ISSUE TITLE
Unable to open mp4 files on desktop in video preview

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode#179826]
This works on web e.g. https://insiders.vscode.dev/github.com/microsoft/vscode-docs/blob/vnext/release-notes/v1_77.md but does not work in desktop, either with a desktop git clone or with RemoteHub. The last time this happened it was due to a regression in the list of enabled codecs for our Electron builds.

**Comment by deepak1556** [comment]
Sorry for the breakage, the changes from https://github.com/microsoft/vscode/issues/175366 has not been added to Electron >= 22 versions yet. It will be addressed in new builds this week.

**Comment by deepak1556** [comment]
Addressed in https://domoreexp.visualstudio.com/Teamspace/_git/electron-build/pullrequest/739125

**Comment by deepak1556** [comment]
Reopening because of https://github.com/microsoft/vscode/pull/179991
