### ISSUE TITLE
save all working wrong

### ISSUE THREAD

**Issue by okansarica** [Microsoft/vscode#17988]
- VSCode Version: Code 1.8.0 (38746938a4ab94f2f57d9e1309c51fd6fb37553d, 2016-12-13T17:45:32.595Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

|Extension|Author|Version|
|---|---|---|
|angular2-snippets|danwahlin|1.0.5|
|Angular2|johnpapa|1.0.2|
|vscode-JS-CSS-HTML-formatter|lonefy|0.2.2|
|seti-icons|qinjia|0.1.3|
|autoimport|steoates|1.2.2|

---

Steps to Reproduce:

There are two json files open. i change the files and click save all. and code changes the second file content with first one

**Comment by rebornix** [comment]
This issue might share the same root cause as https://github.com/Microsoft/vscode/issues/17932

**Comment by rebornix** [comment]
@okansarica does it still happen if you disable all extensions?

**Comment by okansarica** [comment]
nope! it is plugin failure i think, thanks

**Comment by rebornix** [comment]
@okansarica my wild guess is `vscode-JS-CSS-HTML-formatter` or `autoimport`, it would be awesome if you can share some info about that :)

**Comment by rdewolff** [comment]
Just noticed the same issue with v1.8.1
