### ISSUE TITLE
Zen Coding Command Outputting Extra Closing Tag

### ISSUE THREAD

**Issue by ImranAhmed** [Microsoft/vscode#17981]
- VSCode Version: 1.8.1
- OS Version: Windows Home Premium 64GB

Steps to Reproduce:

1. create a new .html file
2. enter the following valid zen code command: `div>p`

actual output:
```
<div></div>
    <p></p>
</div>
```

expected output:
```
<div>
    <p></p>
</div>
```

**Comment by mrmlnc** [comment]
The problem is caused by one of the installed extensions. IMO, maybe, it's `Auto Close Tag` or other.

**Comment by ImranAhmed** [comment]
Thanks, this makes sense. Disabling Auto Close Tag resolves this.
