### ISSUE TITLE
Inserting snippets beginning with a placefolder does not select the placefolder text properly.

### ISSUE THREAD

**Issue by taketori** [Microsoft/vscode#17989]
- VSCode Version: Code 1.8.0 (38746938a4ab94f2f57d9e1309c51fd6fb37553d, 2016-12-13T17:45:32.595Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

|Extension|Author|Version|
|---|---|---|
|Go|lukehoban|0.6.51|

---

- Provide reproducible steps, what the result of the steps was, and what you would have expected.
Steps to Reproduce:

1. input below to \User\snippets\go.json 
```
	"snippet test": {
		"prefix": "prefix",
		"body": "${1:HoldMeTight} = ${2:LoveMeTender}"
	}
```
2. input `Irrésistiblement prefix` to new line on editor.
3. press ctrl+space, then, "prefix" is replaced to "HoldMeTight = LoveMeTender" and "Irrésistibl" (the first few characters of the same line) is selected. selection length is the same as the length of left-most placefolder text.
4. in case of `"${2:~} = ${1:~}"`
    1. at first, $1 text is selected properly.
    2. next  selection after pressing Tab key is "Irrésistibl" (not $2 text)

- A description of what you expect to happen
  - selecting the placefolder text (in case above, selecting "HoldMeTight")
  - if the body of the snippet does not begin with placeholders like `"_${1:HoldMeTight} = ${2:LoveMeTender}"`, the left-most placefolder text is selected properly.
- Errors in the Dev Tools Console (Help | Toggle Developer Tools)
  - nothing is displayed.
- can you reproduce the issue when starting vscode without extensions by using the --disable-extensions command line argument?
  - yes.

**Comment by jrieken** [comment]
regression from https://github.com/Microsoft/vscode/commit/6b515aea3244d547c15f5b2e2ea3fe31d3897a4e
