### ISSUE TITLE
Visual Studio UI lag in Macos VMware

### ISSUE THREAD

**Issue by mayed123502** [microsoft/vscode#179850]
I'm trying to run Visual Studio on Macos VMware, but after booting, the following picture appears

![Screenshot 2023-04-13 105922](https://user-images.githubusercontent.com/80541747/231711612-7bdc4690-ddde-47c0-9d72-f9d9826bbaf7.png)

For your information: the specifications of my device are somewhat high, and I downloaded Android and it worked normally

**Comment by deepak1556** [comment]
Can you check if the issue repros with our insiders version https://code.visualstudio.com/insiders, thanks!

**Comment by mayed123502** [comment]
@deepak1556 Thank you, the problem has been resolved with the attached version
