### ISSUE TITLE
How to publish test results in build step of visual studio online

### ISSUE THREAD

**Issue by nipobhsnro** [Microsoft/vscode#17987]
- VSCode Version:2015
- OS Version:

Steps to Reproduce:

1. Visual studio online 2015
2. Sign in to vs
3. Create new project
4.add build step with step publish test result

I am trying to publish test results but every time I am getting an error that not test.xml found I  project.

Can you please help me with how to publish test results

**Comment by rebornix** [comment]
Sorry it's a Visual Studio issue while we are Visual Studio Code, please report issues to them :)

**Comment by nipobhsnro** [comment]
Hi Peng Lyu,

Thanks for your reply.

Can you please tell me correct branch to ask this question.

Thanks in advance! !
