### ISSUE TITLE
Add a macro symbol kind for languages that have macros

### ISSUE THREAD

**Issue by nox** [Microsoft/vscode#17983]
RustyCode advertises macros as simple functions because there is no specific symbol kind for macros.

https://github.com/saviorisdead/RustyCode/blob/dae6ac740e2b52466f8883da6a716faa8455d6de/src/rustSymbols.ts#L13

**Comment by jrieken** [comment]
@nox Is that for completions or symbol search or both?

**Comment by nox** [comment]
I filed this for symbol search, but I guess it could be used for context in completions too?

**Comment by nox** [comment]
Any news on this?

**Comment by nox** [comment]
Ping?

**Comment by jrieken** [comment]
closing as dupe of https://github.com/Microsoft/vscode/issues/2628
