### ISSUE TITLE
Formatting in Test Output Window

### ISSUE THREAD

**Issue by matepek** [microsoft/vscode#179935]
Hello,

My extension generates a readable output for the test. Some users prefer that because for example it can have [stack trace](https://github.com/microsoft/vscode/issues/159339).
Now I'm using some ansi color javascript package to format it and also using full paths which are working nicely

<img width="1080" alt="Screenshot 2023-04-14 at 12 06 40" src="https://user-images.githubusercontent.com/16504598/231946648-b830c9b1-08dc-46a8-8fd0-dafff8eafe80.png">

except sometimes when links are just way too long, usually wrapped and continues in the next line which not nice for readability. (not shown in the example picture above)

I have tried
- relative links: not working
- link provider: not suitable because I have no control over the terminal.

I did run out of ideas.
 
What I'm looking for at the first place to solve the long link issue but if I had a tool to for mat the output nicely that would be even better. I could imagine markdown or html.

Thanks for your consideration.

**Comment by matepek** [comment]
Now I see that "test result" window is not even formatted:

<img width="1337" alt="Screenshot 2023-04-14 at 12 17 49" src="https://user-images.githubusercontent.com/16504598/231947860-c6cb12c5-331f-47bb-8cca-d8b78639a3e4.png">

**Comment by connor4312** [comment]
It looks like this duplicates https://github.com/microsoft/vscode/issues/157500 and https://github.com/microsoft/vscode/issues/151964. Let me know if not.
