### ISSUE TITLE
Next/Previous match doesn't scroll all the way in Windows

### ISSUE THREAD

**Issue by craxal** [microsoft/vscode#179980]
Type: <b>Bug</b>

1. Open a file with several hundred lines.
2. Press Ctrl+F and search for a term with multiple occurances (10-20).
3. Click Next and previous to navigate to each match.

VS Code version: Code 1.77.3 (704ed70d4fd1c6bd6342c436f1ede30d1cff4710, 2023-04-12T09:16:02.548Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-10900K CPU @ 3.70GHz (20 x 3696)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|127.78GB (88.33GB free)|
|Process Argv|--crash-reporter-id bc1846de-efb9-489e-8bf2-1cce9d515169|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (18)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-sidebar|Acr|1.2.2
markdown-mermaid|bie|1.18.1
LinkCheckMD|bla|0.3.1
vscode-markdownlint|Dav|0.49.0
docs-authoring-pack|doc|1.0.0
gitlens|eam|13.5.0
svg|joc|1.5.2
azure-pipelines|ms-|1.208.0
azure-account|ms-|0.11.3
powershell|ms-|2023.3.3
vscode-yaml|red|1.12.2
kuskus-extensions-pack|ros|1.0.10
kuskus-kusto-language-server|ros|1.0.31
kuskus-kusto-syntax-highlighting|ros|1.1.21
code-spell-checker|str|2.20.4
vscode-json-stable-stringify|Tra|1.2.1
gyp|Xad|1.0.0
json-color-token|yec|1.3.2

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vscaat:30438848
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
nodejswelcome1cf:30587006
282f8724:30602487
pyind779:30671433
f6dab269:30613381
vscrpc:30673769
pythonsymbol12:30671437
a9j8j154:30646983
vsccsb:30705552
vscodeenable:30660116
pythonb192cf:30669361
azdwalk:30687957
pythonms35:30701012
pythonclientmv:30708685

```

</details>

![Recording 2023-04-14 084519](https://user-images.githubusercontent.com/3473026/232092729-68363b3d-9d11-4678-a9c3-c129591018aa.gif)

**Comment by sylann** [comment]
This problem also happens on MacOS.

It's been happening a lot since maybe the last update, but I'm not sure when it started exactly.

Both horizontal and vertical scrolls are concerned.
