### ISSUE TITLE
macOS: HIstoryService: back / forward: edit selection changes

### ISSUE THREAD

**Issue by sbatten** [microsoft/vscode#179923]
https://dev.azure.com/monacotools/Monaco/_build/results?buildId=210721&view=logs&j=55ac390b-ffb1-50ea-3650-525dd9a3fd80&t=a0dd9636-50d2-5f8a-f17f-6bcaa254d802&l=10475

Error: Timeout of 5000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves

**Comment by bpasero** [comment]
Weird, first time I am made aware of this test failing...

**Comment by bpasero** [comment]
Seems like a CI fluke to me.

![image](https://user-images.githubusercontent.com/900690/234884014-be5d48d2-253e-49e1-aa47-230a27679cf0.png)
