### ISSUE TITLE
Fuk 

### ISSUE THREAD

**Issue by Gwill5200** [microsoft/vscode#179971]
ADD ISSUE DESCRIPTION HERE

Version: 1.77.3
Commit: 704ed70d4fd1c6bd6342c436f1ede30d1cff4710
User Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) SamsungBrowser/20.0 Chrome/106.0.5249.126 Safari/537.36
Embedder: codespaces

**Comment by thecutefinder** [comment]
This needs to be re-opened, alongside every other nonsensical issue.
