### ISSUE TITLE
Files getting automatically deleted at the source location if the cache files are removed

### ISSUE THREAD

**Issue by amdshameer** [microsoft/vscode#179949]
Does this issue occur when all extensions are disabled?: Yes/No (Do not know)

Version: 1.77.3
Commit: 704ed70d4fd1c6bd6342c436f1ede30d1cff4710
Date: 2023-04-12T09:16:52.732Z
Electron: 19.1.11
Chromium: 102.0.5005.196
Node.js: 16.14.2
V8: 10.2.154.26-electron.0
OS: Linux x64 5.4.0-146-generic snap
Sandboxed: Yes

For some reason, few files(in my case: .py and .xacro files) are stored as cache in /run/user/some_random_number/doc. If you open that python or xacro file from source location, it **still** opens from cache location. Hence, I tried to delete those files from cache location. However, I could not delete them. Suddenly, git says those files in the source location are deleted. Anyway, I was able to recover the files.

I do not know if this is an edge case, or a bug that exists in the new version.

Steps to Reproduce:

- Since I do not know how the files ended up in cache location, unfortunately, I cannot reproduce this behavior. If someone could point me how to get the files into cache location, I will try to reproduce the behavior.

**Comment by deepak1556** [comment]
Merging to https://github.com/microsoft/vscode/issues/180004
