### ISSUE TITLE
Use multiple font families in editor

### ISSUE THREAD

**Issue by Wattenberger** [microsoft/vscode#179903]
The GitHub Next team is exploring using different fonts at the same time. Most of these explorations fall along the same lines as syntax highlighting (for example, an italic font for comments), but we would also like to decide which font based on things like editor of last line.

I can't find a good way to bundle this behavior with either a theme or an extension, but would love either pointers or the ability to set the font-family in a theme or as part of an extension.

**Comment by alexdima** [comment]
Let's track in https://github.com/microsoft/vscode/issues/30925
