### ISSUE TITLE
Accessibility: Improve Problem View search input

### ISSUE THREAD

**Issue by jooyoungseo** [microsoft/vscode#179964]
CC @meganrogge

1. Ctrl+Shift+M to open problem view.

2. Type something.

3. Ctrl+DownArrow to go to the search result.

4. Press Ctrl+UpArrow: Does not go to the filter term input area. It would be great if this could be added.

5. Just type something in the problem view search result to provide a new search term: the new search term does not override what's already there. It is just appended. This is different behavior from Ctrl+K, Ctrl+S Keyboard Shortcut View search input where new search term clears up the previous one.

## System Info

Version: 1.78.0-insider (system setup)
Commit: 3ad5774eb8123d4224eb55629df9e5f82fe13b99
Date: 2023-04-14T05:25:56.476Z
Electron: 22.4.5
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Windows_NT x64 10.0.22621
Sandboxed: Yes

**Comment by meganrogge** [comment]
This works now
