### ISSUE TITLE
Add API to allow customization of the debug console's input box prompt from code

### ISSUE THREAD

**Issue by indiejames** [Microsoft/vscode#17992]
- VSCode Version: 1.8.1
- OS Version: OS X

Currently there is no way to customize the debug console's input box prompt - it is always '>'. It would be useful to allow the debug adapter to set the prompt to something different to indicate the context in which the code will execute (in what namespace, etc.)

**Comment by indiejames** [comment]
I would be satisfied if there were a way for an extension to set the debug console prompt - it wouldn't have to be set form the debug adapter.

**Comment by isidorn** [comment]
This goes into the direction of extensions being able to do UI contributions which is not on our immediate plan. Might conisder adding this if we open this door some time in the future

**Comment by indiejames** [comment]
I don't think this is a UI contribution so much as setting the state for the project that the UI uses to render itself - no different then outputting text to a console. There is no new element added, just a change in the content that is displayed from '>' to some other string.

**Comment by isidorn** [comment]
This feature request will not be considered in the next 6-12 months roadmap and as such will be closed to keep the number of issues we have to maintain actionable. Thanks for understanding and happy coding!
