### ISSUE TITLE
Feature Request : Option to Sync Manually instead of Auto

### ISSUE THREAD

**Issue by DanteMarshal** [microsoft/vscode#179945]
# Feature Request
It would be awesome if we could have an option to only manually sync, so the automatic sync on each startup doesn't slow down the launch of the app and people's workflow.
I do need the sync, so "Turn off Settings Sync" is not what I'm looking for. I only need to sync my data every few days, not every time I launch the app. It would be awesome if we could have a setting to make that optional.
I'd love to help implement this feature if needed, so let me know what I should do if that's an option.

The next part is just me venting about the frustrations and reason why I wrote this feature request. You can skip reading it if you don't want to hear me nagging 😁 

# Frustration
Automatic sync on VSCode when you open it makes it super slow, specially on slow internet connections like mine. It takes seconds for VSCode extensions to sync and load every single time I open VSCode.
I've had to switch to VSCodium for a while since both Telemetry and Sync slow down VSCode a lot (I've only realized that about telemetry by then). But there's no built-in Sync feature there at all, so I had to use an extension to sync with github.
VSCodium was amazingly fast but I missed both the official Marketplace (which is not legal to add to VSCodium manually) and also the built-in sync feature.
Then I realized that you can turn off Telemetry in VSCode, so I switched back to try to see if that makes it faster and it does. But then I realized that it's still slow with sync turned on, because it tries to sync automatically every single time you open it, and my internet connection isn't that good so it takes a lot of time (seconds) before everything is loaded. That doesn't happen if I turn off the sync feature completely.
I do need the sync feature because I work on two different setups, my laptop and the PC at my office. But I don't want it to slow me down and I don't want to use the weird extensions that sync things on a repository.
I also didn't find an this option nor any issues requesting it, so I thought it's not bad to write a feature request here.
Let me know if there's anything else I can do to help implement it.
Thanks

**Comment by sandy081** [comment]
Thanks for the feedback. I would like to understand why settings sync is slowing down you. Settings Sync runs on a separate process. Can you please let us know in more detail what is slowing down?

**Comment by DanteMarshal** [comment]
As I mentioned, VS Code launches faster when sync and telemetry are turned off. The launch process usually takes longer (in a matter of seconds) when any of those is turned on.

**Comment by sandy081** [comment]
Can you please share following data with and without settings sync enabled?

- F1 > Developer: Startup Performance?

**Comment by DanteMarshal** [comment]
After checking that I realized that I was mistaken. Here are the log files :  
[Startup Performance (Sync).txt](https://github.com/microsoft/vscode/files/11258491/Startup.Performance.Sync.txt)  
[Startup Performance (No Sync).txt](https://github.com/microsoft/vscode/files/11258492/Startup.Performance.No.Sync.txt)  
Or perhaps there was a bug that was fixed in a recent release.
