### ISSUE TITLE
Split Editor doesn't work

### ISSUE THREAD

**Issue by cmeexldai** [Microsoft/vscode#17991]
- VSCode Version: Code - Insiders 1.9.0-insider (ab491d3b40a99485eece2bff1ce8c4aa49aad913, 2016-12-30T07:11:50.471Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

|Extension|Author|Version|
|---|---|---|
|python|donjayamanne|0.5.5|
|csharp|ms-vscode|1.6.2|
|omnisharp|ms-vscode|0.3.3|

---

Steps to Reproduce:

1. press Ctrl+\ doesn't work
2. press Split Editor in menubar View->Split Editor doesn't work

**Comment by bpasero** [comment]
Likely https://github.com/Microsoft/vscode/issues/17871

**Comment by isidorn** [comment]
Closing as duplicate - should be fixed in tomorrow's insiders
