### ISSUE TITLE
Error: Timeout: get element '.extension-editor .monaco-action-bar .action-item:not(.disabled) .extension-action.uninstall' after 20 seconds

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode#179926]
Build: https://dev.azure.com/monacotools/a6d41577-0fa3-498e-af22-257312ff0545/_build/results?buildId=210762
Changes: https://github.com/Microsoft/vscode/compare/8e85312...5d454b0

**Comment by sandy081** [comment]
Checked the log and it seems the extension was kept installing, could be some of the services (Marketplace or unokg) are not responding. The run does not have window log to see at what state this got stuck. I will open an issue to also export the window log.
