### ISSUE TITLE
Autocomplete is autocompleting base64 gibberish

### ISSUE THREAD

**Issue by cjanikdev** [microsoft/vscode#179927]
Does this issue occur when all extensions are disabled?: Yes

![image](https://user-images.githubusercontent.com/35904738/231905354-55c1929e-ce56-4b0e-9eff-b252f2fd2752.png)

Autocomplete suggests random chunks of a base64 string present in the same file. Can't find any way to disable this. The issue was brought up previously (a long time ago) in https://github.com/Microsoft/vscode/issues/60857 but was determined to be an extension issue. I'm having this happen with all extensions disabled, so it can't be an extension issue. Is there a way to make this not happen?

- VS Code Version: 1.77.3
- OS Version: Windows_NT x64 10.0.19045

Steps to Reproduce:

1. Include a base64 string (quoted, commented, doesn't matter) in the file being edited
2. Attempt to use autocomplete

**Comment by jrieken** [comment]
This is mostly likely word based suggestions which you can configure via `editor.wordBasedSuggestionsMode`. If that's not it try F1 > Extension Bisect
