### ISSUE TITLE
Default value for 'markdown.previewFrontMatter' setting should be 'show'

### ISSUE THREAD

**Issue by goessner** [Microsoft/vscode#17990]
- VSCode Version: 1.8.1
- OS Version: win 10

... because 
 1. majority of markdown documents won't have front matter included (personal opinion ?), so this might be the general case.
 2. it should improve performance with markdown rendering as in 
 vscode/extensions/markdown/src/extension.ts @ getDocumentContentForPreview
the regular expression is not applied then.

thanks.

**Comment by mjbvz** [comment]
@goessner Is there any user bad here?

There's not much of a case IMO for rendering frontmatter as markdown (but we allow it as a fallback if users need it) so I think many more people would be opting into hiding the frontmatter than showing it.  

Performance of the regexp is also not really a problem in this context. Do you have numbers showing this is causing a problem?

**Comment by goessner** [comment]
>There's not much of a case IMO for rendering frontmatter as markdown (but we allow it as a fallback if >users need it) so I think many more people would be opting into hiding the frontmatter than showing it.

.. sounds reasonable .. switching defaults is always problematic ..

>Performance of the regexp is also not really a problem in this context. Do you have numbers showing this >is causing a problem?

.. no I did not do runtime performance measurements .. You say that performance is no problem here, so I will handle it the same way then.

Thanks
