### ISSUE TITLE
Issue about Setting-window.zoomLevel and webpage that browse extensions content

### ISSUE THREAD

**Issue by CCisanExplorer** [Microsoft/vscode#17995]
- VSCode Version:1.8.1
- OS Version:win7

    My screen resolution is 1920*1080.It makes the fontsize by default on the sidebar or tabslabels too small for me, so I set the window.zoomLevel at 2. But there is an issue when I search extensions and browse the content in the vscode that the browser just a part of my window like this:
![360 20170102034850438](https://cloud.githubusercontent.com/assets/24191122/21582719/7c9ced7e-d09e-11e6-9ff4-b3ce0967f1a6.jpg)
    The issue occurs in another situation where I run the python code in the Jupyter with extension "Python" ,
![360 20170102035615995](https://cloud.githubusercontent.com/assets/24191122/21582743/7d0c8674-d09f-11e6-9fe6-047abeca177c.jpg)

**Comment by rebornix** [comment]
Dup of https://github.com/Microsoft/vscode/issues/5745
