### ISSUE TITLE
When expression clause `activeEditorIsNotPreview` is not working when the editor show a markdown preview

### ISSUE THREAD

**Issue by HaujetZhao** [microsoft/vscode#179966]
Type: <b>Bug</b>

1. Open a markdown file in editor
2. Use `Ctrl + Shift + V` to show the preview
3. On the right top side, there is a `Show Source` button which trigger the command `markdown.showSource` 
4. Set a keyboard shortcut `Ctrl + Shift + V` and when expression `!activeEditorIsNotPreview` for the command `markdown.showSource`
5. In the markdown preview page, press  `Ctrl + Shift + V`. 

The expected behavior is the editor return to the source tab of the markdown preview page. But nothing happens, the shortcut is not triggered. 

It seems when the editor show the markdown preview, the `!activeEditorIsNotPreview` is not equal to `true`, is normal? 

![image](https://user-images.githubusercontent.com/19181833/232051189-e4854816-5591-4e82-9129-ce7fa22b6820.png)

VS Code version: Code 1.77.3 (704ed70d4fd1c6bd6342c436f1ede30d1cff4710, 2023-04-12T09:16:02.548Z)
OS version: Windows_NT x64 10.0.19045
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 4600H with Radeon Graphics          (12 x 2994)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.37GB (8.49GB free)|
|Process Argv|--crash-reporter-id 082b1596-7408-4001-b8bf-dc4e9bc6a70e --crash-reporter-id 082b1596-7408-4001-b8bf-dc4e9bc6a70e|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-language-pack-zh-hans|MS-|1.77.2023040509

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscoreces:30445986
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
vsccc:30610678
nodejswelcome1:30587005
282f8724:30602487
pyind779:30671433
89544117:30613380
pythonsymbol12:30671437
2i9eh265:30646982
vsccsb:30705552
functionswalk:30687959
pythonms35:30701012
pythonfmttext:30710681

```

</details>

**Comment by gjsjohnmurray** [comment]
My first guess is that the context key relates to the preview mode described at https://code.visualstudio.com/docs/getstarted/userinterface#_preview-mode

**Comment by HaujetZhao** [comment]
> My first guess is that the context key relates to the preview mode described at https://code.visualstudio.com/docs/getstarted/userinterface#_preview-mode

Thank you, that explained everything! I haven't complete reading the tutorial doc, sorry for the obtrusive issue. 

May I ask if there is a `when expression clause` for editor in markdown preview page condition? I searched the [reference page](https://code.visualstudio.com/api/references/when-clause-contexts) but didn't found it.

**Comment by HaujetZhao** [comment]
I found it: `markdownPreviewFocus` !
