### ISSUE TITLE
Dark mode for win32 popup windows

### ISSUE THREAD

**Issue by AndyHTML2012** [microsoft/vscode#180010]
This isn't that important, but it would be nice to have the ability to have the info popup windows have dark mode on Windows OS (or match the theme to whatever theme you have set in the editor).

Here is what I am talking about:
![VSCODE_CheckUpdates_Window](https://user-images.githubusercontent.com/54720001/232153357-6ac8de9d-1eb3-4d18-b796-aa68891b8667.png)
![VSCODE_AboutWindow](https://user-images.githubusercontent.com/54720001/232153359-eeaeeae6-17e8-427d-a237-bb09592183dc.png)

**Comment by deepak1556** [comment]
Merging to https://github.com/microsoft/vscode/issues/120420
