### ISSUE TITLE
Second window is not maximized

### ISSUE THREAD

**Issue by RenaldSB** [Microsoft/vscode#18008]
- VSCode Version: Code 1.8.1 (ee428b0eead68bf0fb99ab5fdc4439be227b6281, 2016-12-19T14:49:23.350Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

|Extension|Author|Version|
|---|---|---|
|angular2-snippets|danwahlin|1.0.12|
|tslint|eg2|0.7.1|
|csharp|ms-vscode|1.6.2|
|vsc-angular-cli|web-dave|0.1.1|
|Material-theme|zhuangtongfa|1.0.3|

---

Steps to Reproduce:

1. Open a folder in VSCode => the window is opened maximized
2. Open another folder in VSCode => The second window is in normal state and not maximized

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/10864
https://github.com/Microsoft/vscode/issues/10505
