### ISSUE TITLE
Search relevance in Quick Pick control 

### ISSUE THREAD

**Issue by ramya-rao-a** [Microsoft/vscode#18003]
_From @ahmetalpbalkan on July 12, 2016 22:18_

Obviously `os` should be the first output here:

![image](https://cloud.githubusercontent.com/assets/159209/16785612/d05abd4e-4843-11e6-8ab1-5a81fb78c69b.png)

In this case `io` is literally at the end

![image](https://cloud.githubusercontent.com/assets/159209/16785616/da19125e-4843-11e6-84e0-e163b30489c8.png)
![image](https://cloud.githubusercontent.com/assets/159209/16785621/e0357ea2-4843-11e6-8be2-3adbb37a5d50.png)

_Copied from original issue: Microsoft/vscode-go#390_

**Comment by ramya-rao-a** [comment]
_From @ahmetalpbalkan on December 18, 2016 2:16_

This is still very much an issue.

**Comment by ramya-rao-a** [comment]
The Go extension uses the `vscode.window.showQuickPick` to show list of packages that can be imported when the `Go: Add Import` command is run.

When user enters text to filter through such a list, the first item is always the default selected item.
This can be made smarter by choosing the item that matches the filter text the most instead.

**Comment by bpasero** [comment]
I think what we do today in the picker is just to preserve the order of elements as they where given to the picker API. Since the sorting order can be very much dependent on the context, I think we should have a way for API users to control the sorting behaviour for matching elements.

**Comment by jrieken** [comment]
> I think what we do today in the picker is just to preserve the order of elements as they where given to the picker API. Since the sorting order can be very much dependent on the context, I think we should have a way for API users to control the sorting behaviour for matching elements.

Disagree, because we allow multiple provider to contribute to that UI *at the same time*. Therefore a provider cannot define the sort order of n merged results.

**Comment by bpasero** [comment]
@jrieken can you give an example where multiple providers add stuff to the `showQuickPick` API at the same time? I was not aware this is possible today.

**Comment by jrieken** [comment]
Sorry, I miss read this is about quick pick. However, the more general case of navigate types (in file, in workspace) has this problem and provider-scope ranking/sorting is not an option there. 

I am not a fan of putting the burden on the extension writer for this as quick pick is about selecting an element from a list of static elements. To me there some pretty obvious failure of our ranking algorithm as not `os` (2 of 2 character matched) but `os/exec` (2 of 7 character matched) is pre-selected

**Comment by bpasero** [comment]
@ramya-rao-a I pushed a change to use our typical sorter that we use in other quick open handlers too. What would be the best way of verifying this issue using the go extension?

**Comment by ramya-rao-a** [comment]
You can run the `Go: Add Import` command in the command pallet. That will open a quick pick. Type away to filter

**Comment by ahmetalpbalkan** [comment]
I have been disabling all extensions for the 5th time now because it is the first option and not the "Install Extensions".

![image](https://cloud.githubusercontent.com/assets/159209/21947380/cc21e058-d999-11e6-9154-35307e33a887.png)

**Comment by bpasero** [comment]
There was no change in the relevance sorting for the command palette btw.

**Comment by ramya-rao-a** [comment]
@ahmetalpbalkan 

Can you open a separate issue for https://github.com/Microsoft/vscode/issues/18003#issuecomment-272561436 which is about the commands in the command pallet.

The original issue here was about the quick pick control (which in this particular case was when the `Go: Add Import` command was run).

The fix for the original issue is available in the insiders build, just tested it.

**Comment by bpasero** [comment]
@ramya-rao-a did you verify this fix, then could you maybe add the verified label?

As for the command palette this is https://github.com/Microsoft/vscode/issues/14727

**Comment by ramya-rao-a** [comment]
Verified.
