### ISSUE TITLE
color decorator bug

### ISSUE THREAD

**Issue by Bubekk** [microsoft/vscode#180019]
Type: <b>Bug</b>

I recently don't see color decorators neither in css and scss fies

VS Code version: Code 1.77.3 (704ed70d4fd1c6bd6342c436f1ede30d1cff4710, 2023-04-12T09:16:02.548Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-9600KF CPU @ 3.70GHz (6 x 3696)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.94GB (7.89GB free)|
|Process Argv|--crash-reporter-id 57ea658b-5b28-4f8c-b551-628c7b52944d|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
htmltagwrap|bra|0.0.9
simple-react-snippets|bur|1.2.7
vscode-html-css|ecm|1.13.1
prettier-vscode|esb|9.10.4
vscode-colorize|kam|0.11.1
indent-rainbow|ode|8.3.1
material-icon-theme|PKi|4.26.0
gruvbox-material|sai|6.5.2
vscode-scss-formatter|sib|2.5.0
JavaScriptSnippets|xab|1.8.0
html-css-class-completion|Zig|1.20.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
nodejswelcome1:30587005
2e4cg342:30602488
pyind779:30671433
89544117:30613380
pythonsymbol12:30671437
a9j8j154:30646983
vsccsb:30705552
functionswalk:30687959
pythonms35:30701012
pythonclientmvcf:30713944

```

</details>

**Comment by gjsjohnmurray** [comment]
Please use the Start Extension Bisect command to investigate whether the problem is being caused by one of your extensions.

**Comment by aeschli** [comment]
- Make sure that the editor language mode is `CSS` or `SCSS`
- Verify that the `CSS Language Features` extension is enabled
![image](https://user-images.githubusercontent.com/6461412/232404638-dfb6ef98-a5c6-4d0b-b3ba-73439910d99a.png)
- make sure you have not disabled the color decorators setting `editor.colorDecorators`
- enable `"css.trace.server": "verbose"` and check the `CSS Language Server` output for occurrences of `Sending request 'textDocument/documentColor`

**Comment by Bubekk** [comment]
> * Make sure that the editor language mode is `CSS` or `SCSS`
> * Verify that the `CSS Language Features` extension is enabled
>   ![image](https://user-images.githubusercontent.com/6461412/232404638-dfb6ef98-a5c6-4d0b-b3ba-73439910d99a.png)
> * make sure you have not disabled the color decorators setting `editor.colorDecorators`
> * enable `"css.trace.server": "verbose"` and check the `CSS Language Server` output for occurrences of `Sending request 'textDocument/documentColor`

Hi! Thanks for answers and tips.  Problem was CSS Language Features which doesn't work with some of my settings in VS Code. 
I just delete all files from VS Code and install it again. Now, everything is fine and good :)
