### ISSUE TITLE
Not able to see git log for a specific file

### ISSUE THREAD

**Issue by komal436** [Microsoft/vscode#18007]
- VSCode Version: 1.8.1
- OS Version: windows-10

Steps to Reproduce:

1. Open a git project.
2. Try to do git log -p <filename> 
It's not working. Is there a support of external installer to have this option?

**Comment by rebornix** [comment]
Are you running `git log -p` in integrated terminal? From what I can tell it works.

**Comment by mjbvz** [comment]
Closing as we need more info to investigate this issue. 

@komal436 If this is still a problem, please produce some addition information about the problem and how we can reproduce it.

Thanks
