### ISSUE TITLE
CMake Tools Cannot Debug - Access Denied

### ISSUE THREAD

**Issue by atom0s** [microsoft/vscode#180064]
Does this issue occur when all extensions are disabled?: N/A (Requires an extension in order to even function for this issue.)

- VS Code Version:  1.78.0-insider (system setup) 3ad5774eb8123d4224eb55629df9e5f82fe13b99
- OS Version: Windows_NT x64 10.0.22621 (Windows 11 Pro 22H2)

Steps to Reproduce:

1. Install CMake Tools extension and C++ developer tools/extension.
2. Create any basic project to produce an .exe file.
3. Build project.
4. Attempt to debug project via the CMake Tools extension 'bug' icon in the bottom toolbar.

This will cause an error to happen that says:
```
Unable to start program '<Path to your project>\<projname>.exe'. Access is denied.
```

However, if I run VSCode as an Administrator (right-click > Run as Administrator) then the above steps work fine and no error happens. Debugging will work as expected. This only appears to be affecting Windows 11 for me. I have two other machines that are sync'd with the same settings and extensions as this laptop and both are on Windows 10. Neither of those machines have this issue.

**Comment by roblourens** [comment]
Please file this on the repo for the extensions involved
