### ISSUE TITLE
Probelm wit my workspace

### ISSUE THREAD

**Issue by ghost** [microsoft/vscode#180020]
ADD ISSUE DESCRIPTION HERE

HI Im having problems wth my codespace. I can make anything run. It first had a container problem and now I don't how to make my code work. Sorry I'm new using VS and need help. Just  learnig how to program.

Version: 1.77.3
Commit: 704ed70d4fd1c6bd6342c436f1ede30d1cff4710
User Agent: Mozilla/5.0 (Windows NT 10.0; Win6
![Codespace problem](https://user-images.githubusercontent.com/126931753/232179251-dae0dbda-18e7-4c51-9f03-25de5fb68995.png)
4; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36 Edg/112.0.1722.39
Embedder: codespaces

**Comment by jaguayoe** [comment]
PLease ai realled need help with this I think I'm making it worst

**Comment by roblourens** [comment]
Sorry, this looks like it might be an issue with your configuration/project setup, not with vscode. You might need to save your file or make sure that your terminal is in the right folder, using `cd`
