### ISSUE TITLE
`code.cmd` does not give the correct exit code

### ISSUE THREAD

**Issue by alexrp** [microsoft/vscode#180021]
Type: <b>Bug</b>

`code.cmd --uninstall-extension this-does.not-exist` will exit with code `0`.

`code --uninstall-extension this-does.not-exist` will exit with code `1`.

VS Code version: Code 1.77.3 (704ed70d4fd1c6bd6342c436f1ede30d1cff4710, 2023-04-12T09:16:02.548Z)
OS version: Windows_NT x64 10.0.25336
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9900KF CPU @ 3.60GHz (16 x 3600)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|63.92GB (48.37GB free)|
|Process Argv|--crash-reporter-id 33c31161-bb25-44d9-be24-53a2c77525e5|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by lszomoru** [comment]
@sandy081 please feel free to reassign is this is not an issue with the `--uninstall-extension` implementation.

**Comment by connor4312** [comment]
Sure why not 🙂

**Comment by connor4312** [comment]
This appears to be [a quirk](https://stackoverflow.com/a/55290133/1125956) with how batch files get executed on Windows. I confirmed that I saw this issue, but following the advice to use `cmd /c` caused the exit code to propagate correctly.
