### ISSUE TITLE
Search editor to edit actual files

### ISSUE THREAD

**Issue by Jacobsamo** [microsoft/vscode#180092]
When using cross file search and you open in the editor you can show the lines or multiple lines, what would be cool is if that you can edit the content that has been searched e.g you search `console.log('hello world')`  and want to replace this with something like `log('hello world')`
 you can't actually replace it through the search editor window which is a little annoying as you then have to go to search window and do it where it would be really nice to just have this  in the search editor window.

**Comment by andreamah** [comment]
Unfortunately, the search editor is meant to just show the results at the time of search, so we probably wouldn't want to incorporate this functionality in core. However, the extension mention above seems to work for your use case.
