### ISSUE TITLE
Source control count badge empty

### ISSUE THREAD

**Issue by brandus1** [microsoft/vscode#180076]
Type: <b>Bug</b>

While version changes are shown when opening source control, the number of changes is not shouwn anymore on the source control icon in the side bar

VS Code version: Code 1.77.3 (Universal) (704ed70d4fd1c6bd6342c436f1ede30d1cff4710, 2023-04-12T09:19:37.325Z)
OS version: Darwin arm64 22.4.0
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|6, 4, 3|
|Memory (System)|16.00GB (0.06GB free)|
|Process Argv|--crash-reporter-id 459ad7fd-4cfb-4227-9986-56d6cedd85d9|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (34)</summary>

Extension|Author (truncated)|Version
---|---|---
atlascode|atl|3.0.3
vscode-tailwindcss|bra|0.9.11
systemd-unit-file|coo|1.0.6
doxdocgen|csc|1.4.0
gitlens|eam|13.5.0
prettier-vscode|esb|9.10.4
code-runner|for|0.12.0
copilot|Git|1.82.15
gitlab-workflow|Git|3.61.0
better-cpp-syntax|jef|1.17.2
cmake-language-support-vscode|jos|0.0.9
vscode-cudacpp|kri|0.1.1
rainbow-csv|mec|3.7.0
git-graph|mhu|1.30.0
vscode-docker|ms-|1.24.0
vscode-dotnet-runtime|ms-|1.6.0
python|ms-|2023.6.0
vscode-pylance|ms-|2023.4.20
jupyter|ms-|2023.3.1201040234
jupyter-keymap|ms-|1.1.0
jupyter-renderers|ms-|1.0.15
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-slideshow|ms-|0.1.5
remote-containers|ms-|0.288.1
remote-ssh|ms-|0.100.0
remote-wsl|ms-|0.77.0
cmake-tools|ms-|1.13.45
cpptools|ms-|1.15.2
cpptools-extension-pack|ms-|1.3.0
remote-explorer|ms-|0.4.0
vscode-yaml|red|1.12.2
svelte-vscode|sve|107.3.0
cmake|twx|0.0.17
vim|vsc|1.25.2

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vscaat:30438848
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
nodejswelcome1:30587005
3biah626:30602489
pyind779:30671433
f6dab269:30613381
pythonsymbol12:30671437
vsctsb:30705553
functionswalk:30687959
pythonms35:30701012

```

</details>

**Comment by gjsjohnmurray** [comment]
Have you perhaps hidden the badge? The context menu of the icon has an entry for doing that, after which the entry becomes one for showing the badge.

**Comment by brandus1** [comment]
The icon is not hidden, just the number of changes that was usually over the icon.

<img width="526" alt="Screenshot 2023-04-16 at 19 39 02" src="https://user-images.githubusercontent.com/62740047/232330541-61fcc587-8bf3-4263-8dba-4eb5dc5b0323.png">

**Comment by brandus1** [comment]
you are right. sorry! thanks a lot
