### ISSUE TITLE
onServerReadyAction -> startDebugging passing url ? 

### ISSUE THREAD

**Issue by VerdantForge** [microsoft/vscode#180068]
You're right the problem with my logic is that we could not launch independently a configuration if it depends on an url parameter...
    I guess we could use something like this in the configuration :
    ${command:extension.getServerReadyCapture}
    or something in the input variable: 
    https://code.visualstudio.com/docs/editor/variables-reference#_input-variables
    ${input:serverReadyCapture}
    If you think of a solution to get url parameter with a command or an input I will be interested.
    I 'll try it in the next update of vscode.
    Thanks @connor4312.

_Originally posted by @llgcode in https://github.com/microsoft/vscode/issues/109931#issuecomment-721591241_
     

I'm trying to have launch config that will automatically send an http request to my backend so I can quickly start debugging.
I came across the new feature startDebugging in onServerReadyAction.

Has there been any progress on passing the url to the receiving launch configuration ?

**Comment by roblourens** [comment]
Sorry, I don't quite follow, do you want to start a server launch config and also send a request so you hit a breakpoint? You can use this feature to navigate to your url in a browser, if that helps.

**Comment by VerdantForge** [comment]
Yes exactly hitting a breakpoint or triggering an exception is the intent. 
For instance to test a POST HTTP request, I would like to:
- Build as a pre launch task
- Launch in debug mode
- send http post with json content, once ready

I could accomplish this with `onServerReadyAction`, which would launch a task that runs curl or something. But in the case where the startup port is not constant, I would like to be able to grab it from the same pattern used in the `onServerReadyAction`

**Comment by roblourens** [comment]
I think the best solution for you is just to use  `serverReadyAction` to open that URL in a browser or start another debug config that does what you want to do.

https://code.visualstudio.com/docs/editor/debugging#_automatically-open-a-uri-when-debugging-a-server-program

Maybe it would be helpful to launch a task or run a script too but I would like to keep this feature focused on debugging.
