### ISSUE TITLE
Slow startup

### ISSUE THREAD

**Issue by satra-11** [microsoft/vscode#180031]
Type: <b>Performance Issue</b>

Slow startup performance. Happens every time.
 
VS Code version: Code 1.77.3 (704ed70d4fd1c6bd6342c436f1ede30d1cff4710, 2023-04-12T09:16:02.548Z)
OS version: Windows_NT x64 10.0.22621
Modes: Restricted
Sandboxed: No

<details>
<summary>Performance Marks</summary>

| What                                                            | Duration | Process                   | Info                                                        |
| --------------------------------------------------------------- | -------- | ------------------------- | ----------------------------------------------------------- |
| start => app.isReady                                            | 3364     | [main]                    | initial startup: true                                       |
| nls:start => nls:end                                            | 0        | [main]                    | initial startup: true                                       |
| require(main.bundle.js)                                         | 61       | [main]                    | initial startup: true                                       |
| start crash reporter                                            | 3328     | [main]                    | initial startup: true                                       |
| serve main IPC handle                                           | 1        | [main]                    | initial startup: true                                       |
| create window                                                   | 25       | [main]                    | initial startup: true, state: 0ms, widget: 11ms, show: 13ms |
| app.isReady => window.loadUrl()                                 | 107      | [main]                    | initial startup: true                                       |
| window.loadUrl() => begin to require(workbench.desktop.main.js) | 9860     | [main->renderer]          | NewWindow                                                   |
| require(workbench.desktop.main.js)                              | 197      | [renderer]                | cached data: YES, node_modules took 0ms                     |
| wait for window config                                          | 0        | [renderer]                | -                                                           |
| init storage (global & workspace)                               | 19       | [renderer]                | -                                                           |
| init workspace service                                          | 17       | [renderer]                | -                                                           |
| register extensions & spawn extension host                      | 123      | [renderer]                | -                                                           |
| restore viewlet                                                 | 13       | [renderer]                | workbench.view.explorer                                     |
| restore panel                                                   | 0        | [renderer]                | -                                                           |
| restore & resolve visible editors                               | 85       | [renderer]                | 1: PerfviewInput                                            |
| overall workbench load                                          | 236      | [renderer]                | -                                                           |
| workbench ready                                                 | 13791    | [main->renderer]          | -                                                           |
| renderer ready                                                  | 467      | [renderer]                | -                                                           |
| shared process connection ready                                 | 0        | [renderer->sharedprocess] | -                                                           |
| extensions registered                                           | 14018    | [renderer]                | -                                                           |

</details>

<details>
<summary>Profiles</summary>
[prof-DV9ePGAD.main.cpuprofile.txt](https://github.com/microsoft/vscode/files/11238851/prof-DV9ePGAD.main.cpuprofile.txt)
[prof-DV9ePGAD.renderer.cpuprofile.txt](https://github.com/microsoft/vscode/files/11238852/prof-DV9ePGAD.renderer.cpuprofile.txt)
</details>

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|

|CPUs|AMD Ryzen 9 5900HX with Radeon Graphics         (16 x 3294)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.41GB (7.36GB free)|
|Process Argv|--crash-reporter-id 2ffd1967-faf1-40ea-bbf7-7e90d2d64e78|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	    93	  3480	code main
    0	    26	 10196	   crashpad-handler
    0	    45	 11092	   utility-network-service
    0	   114	 14908	extensionHost [1]
    0	    76	  7064	     electron-nodejs ("C:\Users\syuzu\AppData\Local\Programs\Microsoft VS Code\Code.exe" --ms-enable-electron-run-as-node "c:\Users\syuzu\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\markdown-language-features\server\dist\node\workerMain" --node-ipc --clientProcessId=14908)
    0	   182	 17932	window [1] (Startup Performance - Visual Studio Code)
    0	    76	 19948	fileWatcher [1]
    0	   148	 21380	   gpu-process
    0	    92	 22848	shared-process
    0	    76	 25340	     ptyHost
    0	    87	 26204	window [2] (Issue Reporter)
```

</details>
<details>
<summary>Workspace Info</summary>

```
;
```

</details>
Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscoreces:30445986
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
nodejswelcome1cf:30587006
3biah626:30602489
pyind779:30671433
f6dab269:30613381
pythonsymbol12:30671437
vsccsb:30705552
vscodeenable:30660116
functionswalk:30687959
pythonms35:30701012
pythonfmttextcf:30710682
pythonclientmvcf:30713944

```

</details>

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by satra-11** [comment]
@bpasero 

Wow, it works fine now. Thank you so much !

**Comment by satra-11** [comment]
<details>
<summary>Performance Marks</summary>
## Performance Marks

| What                                                            | Duration | Process                   | Info                                                       |
| --------------------------------------------------------------- | -------- | ------------------------- | ---------------------------------------------------------- |
| start => app.isReady                                            | 3605     | [main]                    | initial startup: true                                      |
| nls:start => nls:end                                            | 0        | [main]                    | initial startup: true                                      |
| require(main.bundle.js)                                         | 57       | [main]                    | initial startup: true                                      |
| start crash reporter                                            | 3563     | [main]                    | initial startup: true                                      |
| serve main IPC handle                                           | 1        | [main]                    | initial startup: true                                      |
| create window                                                   | 26       | [main]                    | initial startup: true, state: 0ms, widget: 24ms, show: 0ms |
| app.isReady => window.loadUrl()                                 | 102      | [main]                    | initial startup: true                                      |
| window.loadUrl() => begin to require(workbench.desktop.main.js) | 10305    | [main->renderer]          | NewWindow                                                  |
| require(workbench.desktop.main.js)                              | 167      | [renderer]                | cached data: YES, node_modules took 0ms                    |
| wait for window config                                          | 1        | [renderer]                | -                                                          |
| init storage (global & workspace)                               | 18       | [renderer]                | -                                                          |
| init workspace service                                          | 14       | [renderer]                | -                                                          |
| register extensions & spawn extension host                      | 101      | [renderer]                | -                                                          |
| restore viewlet                                                 | 0        | [renderer]                | -                                                          |
| restore panel                                                   | 0        | [renderer]                | -                                                          |
| restore & resolve visible editors                               | 58       | [renderer]                | 1: PerfviewInput                                           |
| overall workbench load                                          | 185      | [renderer]                | -                                                          |
| workbench ready                                                 | 14390    | [main->renderer]          | -                                                          |
| renderer ready                                                  | 380      | [renderer]                | -                                                          |
| shared process connection ready                                 | 0        | [renderer->sharedprocess] | -                                                          |
| extensions registered                                           | 14555    | [renderer]                | -                                                          |

</details>

<details>
<summary>Performance Marks</summary>

</details>

<details>
<summary>System Info</summary>

* Code - Insiders: 1.78.0-insider (3ad5774eb8123d4224eb55629df9e5f82fe13b99)
* OS: win32(10.0.22621)
* CPUs: AMD Ryzen 9 5900HX with Radeon Graphics        (16 x 3294)
* Memory(System): 15.41 GB(8.11GB free)
* Memory(Process): 189.21 MB working set(154.94MB private, 1.03MB shared)
* VM(likelihood): 0%
* Initial Startup: true
* Has 0 other windows
* Screen Reader Active: false
* Empty Workspace: true
</details>

**Comment by bpasero** [comment]
> One thing I noticed is that it works fine when I started right from the installer

Can you clarify what that means?

**Comment by satra-11** [comment]
I meant like when I check the box and activate vscode from the installer the setup performance is far better.

<table>
  <tr>
    <td>installer</td>
  </tr>
  <tr>
    <td> 

![image](https://user-images.githubusercontent.com/115873069/232411054-a882a63b-f18f-429c-9104-9a00f79f369e.png)

 </td>
  </tr>
</table>

## Performance Marks

| What                                                            | Duration | Process                   | Info                                                        |
| --------------------------------------------------------------- | -------- | ------------------------- | ----------------------------------------------------------- |
| start => app.isReady                                            | 189      | [main]                    | initial startup: true                                       |
| nls:start => nls:end                                            | 0        | [main]                    | initial startup: true                                       |
| require(main.bundle.js)                                         | 149      | [main]                    | initial startup: true                                       |
| start crash reporter                                            | 87       | [main]                    | initial startup: true                                       |
| serve main IPC handle                                           | 4        | [main]                    | initial startup: true                                       |
| create window                                                   | 116      | [main]                    | initial startup: true, state: 1ms, widget: 33ms, show: 81ms |
| app.isReady => window.loadUrl()                                 | 329      | [main]                    | initial startup: true                                       |
| window.loadUrl() => begin to require(workbench.desktop.main.js) | 368      | [main->renderer]          | NewWindow                                                   |
| require(workbench.desktop.main.js)                              | 405      | [renderer]                | cached data: YES, node_modules took 0ms                     |
| wait for window config                                          | 3        | [renderer]                | -                                                           |
| init storage (global & workspace)                               | 40       | [renderer]                | -                                                           |
| init workspace service                                          | 40       | [renderer]                | -                                                           |
| register extensions & spawn extension host                      | 829      | [renderer]                | -                                                           |
| restore viewlet                                                 | 0        | [renderer]                | -                                                           |
| restore panel                                                   | 0        | [renderer]                | -                                                           |
| restore & resolve visible editors                               | 164      | [renderer]                | 1: PerfviewInput                                            |
| overall workbench load                                          | 488      | [renderer]                | -                                                           |
| workbench ready                                                 | 1839     | [main->renderer]          | -                                                           |
| renderer ready                                                  | 958      | [renderer]                | -                                                           |
| shared process connection ready                                 | 0        | [renderer->sharedprocess] | -                                                           |
| extensions registered                                           | 2872     | [renderer]                | -                                                           |

**Comment by bpasero** [comment]
I still do not really understand the difference, how are you starting VS Code that is ends up being slow vs. starting fast?

**Comment by satra-11** [comment]
Found out that  the antivirus software was causing the whole problem. It worked fine after I added insiders.exe to exclude files.

> One thing I noticed is that it works fine when I started right from the installer

For this, I think starting vscode from setup.exe somehow got around the scannnig process and ended up starting fast..
