### ISSUE TITLE
On MacOS, `"workbench.startupEditor": "readme"` does not fallback to `welcomePage`

### ISSUE THREAD

**Issue by yw662** [microsoft/vscode#180028]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.77.3 704ed70d4fd1c6bd6342c436f1ede30d1cff4710 arm64
- OS Version: macOS 13.3.1

Steps to Reproduce:

1. in user preference, set `"workbench.startupEditor": "readme"`
2. open an empty workbench (or a new window), or a folder without readme.

Expected: it should fallback to "welcomePage" and open the welcome page.
Actual: no startup editor opened.

**Comment by gjsjohnmurray** [comment]
https://github.com/microsoft/vscode/blob/682afdd61dd66e83cfdbefdf6b8214dbbc65e135/src/vs/workbench/contrib/welcomeGettingStarted/browser/startupPage.ts#L129-L152

Either the description of the `"readme"` option is wrong or the above code needs an `else` block to run `openGettingStarted()` when no readmes were found.
