### ISSUE TITLE
When opening the right-click context menu on Gnome, it closes immediately if there is an option under the mouse

### ISSUE THREAD

**Issue by MiguelGuthridge** [microsoft/vscode#180072]
## Does this issue occur when all extensions are disabled?
No, but only because the number of options in the right-click menu isn't enough to cause it to render below the mouse.

- VS Code Version: 1.77.3
- OS Version: Fedora 37 (Gnome 43)

## Steps to Reproduce

1. Have enough extensions enable to make the right-click context menu take up the majority of the screen
2. Right click somewhere in the middle of the file

## Expected results

The right-click context menu opens and I am able to click my desired option immediately.

## Actual results

Due to the mouse being at the centre of the right-click menu when it opens, the lifting of the right mouse button causes the menu item below the mouse to be immediately chosen. See the position of the mouse in the menu in the screenshot below, and observe that the "Rename symbol" option is highlighted.

![image](https://user-images.githubusercontent.com/31365175/232322677-9912bc0f-7f26-4af6-8cfc-ae3809ab59b6.png)

This means that as soon as I release my mouse, that selection will be chosen immediately, which is extremely frustrating, and potentially destructive if my mouse happens to be over a difficult-to-undo operation (eg a permanent file deletion when working on a remote machine through SSH).

**Comment by gjsjohnmurray** [comment]
Almost certainly a duplicate of #113175

**Comment by MiguelGuthridge** [comment]
Looks like it
