### ISSUE TITLE
ts errors / addMissingImports / checkJS , AllowJs / "javascript.validate.enable": false

### ISSUE THREAD

**Issue by MrOxMasTer** [microsoft/vscode#180001]
Type: <b>Bug</b>

I use js/jsx . I want to use the function "source.addMissingImports": true , but the problem is that it only works for me when I enable checkJS . For me, check JS causes the error ts (2339) and not only, but without check JS, adding imports does not work. Allow Js doesn't work either. "typescript.validate.enable": false,
""javascript.validate.enable": false, I also tried to set, but if I disable "javascript.validate", then adding imports stops working for me again.
What should I do so that this function works and there is no error?

VS Code version: Code - Insiders 1.78.0-insider (3ad5774eb8123d4224eb55629df9e5f82fe13b99, 2023-04-14T05:25:56.476Z)
OS version: Windows_NT x64 10.0.19045
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz (4 x 2712)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.89GB (4.89GB free)|
|Process Argv|--crash-reporter-id 8d5950e0-2632-4265-9569-e267bad308c4|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (41)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|3.0.2
vscode-color-picker|Ant|0.0.4
htmltagwrap|bra|0.0.9
npm-intellisense|chr|1.4.4
path-intellisense|chr|2.8.4
vscode-eslint|dba|2.4.0
vscode-faker|dee|2.0.0
gitlens|eam|13.5.0
vscode-html-css|ecm|1.13.1
prettier-vscode|esb|9.10.4
auto-close-tag|for|0.5.14
auto-complete-tag|for|0.1.0
auto-rename-tag|for|0.1.10
backticks|fra|1.7.0
todo-tree|Gru|0.0.226
google-translate|han|1.2.8
stylelint-plus|hex|0.56.6
vscode-htmlhint|HTM|1.0.4
discord-vscode|icr|5.8.0
hungry-delete|jas|1.7.0
styled-components-snippets|jon|0.10.0
google-fonts|lio|0.0.1
vscode-scss|mrm|0.10.0
css-responsive-jsx-tsx|MrO|1.1.3
vscode-language-pack-ru|MS-|1.77.2023041209
color-highlight|nau|2.5.0
px-to-rem|sai|1.3.1
svg-preview|Sim|2.8.3
guides|spy|0.9.3
autoimport|ste|1.5.4
code-spell-checker|str|2.20.4
code-spell-checker-russian|str|2.0.9
vscode-styled-components|sty|1.7.8
vscode-stylelint|sty|1.2.4
highlight-matching-tag|vin|0.11.0
intellicode-api-usage-examples|Vis|0.2.7
vscodeintellicode|Vis|1.2.30
vscode-icons|vsc|12.3.0
vscode-import-cost|wix|3.3.0
change-case|wma|1.0.0
material-theme|zhu|3.15.8

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythontb:30258533
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscod805:30301674
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30404738
cppdebug:30492333
vsclangdf:30492506
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30618038
pylantcb52:30590116
nodejswelcome1:30587009
pyind779:30611226
vscrp:30624060
pythonsymbol12:30651887
6233i204:30659907
functionswalk:30687959
pythonms35:30671666
pythonfmttext:30710679
pythonclientmv:30700173

```

</details>

**Comment by MrOxMasTer** [comment]
I've also read the vs code documentation. Why are you refactoring code only for TypeScript. I understand that for developers it is more gentle than regular javascript, but the organization of imports and the addition of non-existing ones is needed everywhere and it would be great to take it out as a separate function. (in code Action)

**Comment by MrOxMasTer** [comment]
I tried to prescribe "ignoreDeprecations": "5.0", "suppressExcessPropertyErrors": true, "suppressImplicitAnyIndexErrors": true, but he doesn't care and he doesn't remove the error
![Screenshot_16](https://user-images.githubusercontent.com/59291123/232227674-8d3b1225-439e-459c-a7ec-7d87f105ac4d.png)

**Comment by MrOxMasTer** [comment]
can you make addMissingImports work separately from checkJS? I have a lot of incomprehensible errors flying out because of checks.

**Comment by mjbvz** [comment]
> I use js/jsx . I want to use the function "source.addMissingImports": true , but the problem is that it only works for me when I enable checkJS .

Yes, checkJS signals that you want more advanced type checking. That signals that we can more confidently make fixes to your code too. Otherwise we'd be applying fixes to code that may silently contain coding patterns that we can't analyze, resulting in incorrect fixes

**Comment by MrOxMasTer** [comment]
I understand that check JS is made for type checking and much more, but the addMissingImports function does not relate to checkJS.

**Comment by MrOxMasTer** [comment]
I have addMissingImports does not work without checkJS and it seems to me that this is wrong. This is a very useful feature and it would be great if it is possible to use it without check JS. I think many people will thank you, because it's convenient.

**Comment by MrOxMasTer** [comment]
because addMissingImports refers to Code Actions, not to check JS and it's strange that it doesn't work without checkJs

**Comment by MrOxMasTer** [comment]
cool you solved the problem. You have a very useful function by itself does not work, but you are normal, close my posts

**Comment by MrOxMasTer** [comment]
is there any way to leave an assessment of your help?

**Comment by MrOxMasTer** [comment]
You understand that you just have completely disconnected functions. What is the relationship between type checking in javascript and adding imports of regular files or libraries?
