### ISSUE TITLE
Dynamic "inputs"

### ISSUE THREAD

**Issue by matepek** [microsoft/vscode#180025]
In the `launch.json` these input options are very useful. For some applications I would prefer to provide the input dynamically. Like I could run a script which returns the values and those would be the ones I can choose from.

I could imagine something like:
```
  "inputs": [
    {
      "id": "pickSomething",
      "description": "...",
      "type": "pickDynamicString",
      "cmd": "executable",
      "args": [],
      "envs": {},
      "default": ".*"
    }
```

Of course the executable should generate something which is understandable by the vscode like json or just lines..

Thanks for the consideration.

**Comment by roblourens** [comment]
The command-type inputs can be used in this way, with an extension providing the picker and returning the value

https://code.visualstudio.com/docs/editor/variables-reference#_input-variables

**Comment by matepek** [comment]
Hello,
I wouldn't mind a little more explanation or maybe an example.. And which extension are you referring to?

**Comment by matepek** [comment]
Found this: https://stackoverflow.com/questions/58747689/using-a-shell-command-as-vscode-task-variable-value
This works.
