### ISSUE TITLE
Toggle terminal keybind ignores terminals in editor view

### ISSUE THREAD

**Issue by makeway4pK** [microsoft/vscode#180029]
Type: <b>Bug</b>

1. Create a terminal in an editor by
setting terminal.integrated.defaultLocation = 'editor' and using the New Terminal keybind (workbench.action.terminal.new)
2. Open any file in another editor, the terminal open in editor will be hidden.
3. Use the Toggle Terminal keybind (workbench.action.terminal.toggleTerminal)
Observed: A new terminal is created in panel, ignoring the preciously open terminal in the editor, even if the terminal area of the panel was previously hidden (by rightClk panel header -> uncheck 'Terminal')

VS Code version: Code 1.77.3 (704ed70d4fd1c6bd6342c436f1ede30d1cff4710, 2023-04-12T09:16:02.548Z)
OS version: Windows_NT x64 10.0.19044
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5200U CPU @ 2.20GHz (4 x 2197)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|7.87GB (2.93GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (43)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-tomcat|ada|0.11.3
github-markdown-preview|bie|0.3.0
markdown-checkbox|bie|0.4.0
markdown-emoji|bie|0.3.0
markdown-footnotes|bie|0.1.1
markdown-mermaid|bie|1.18.1
markdown-yaml-preamble|bie|0.1.0
doxdocgen|csc|1.4.0
prettier-vscode|esb|8.0.1
vscode-pull-request-github|Git|0.27.1
vscode-auto-open-markdown-preview|hnw|0.0.4
discoverpanel|Ion|0.1.0
better-cpp-syntax|jef|1.17.2
chat|kar|0.35.0
vscode-fix-checksums|leh|1.1.0
git-graph|mhu|1.30.0
dotnet-interactive-vscode|ms-|1.0.4205010
jupyter|ms-|2022.5.1001601848
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.8
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-slideshow|ms-|0.1.5
remote-wsl|ms-|0.66.3
cmake-tools|ms-|1.12.26
cpptools|ms-|1.7.1
cpptools-extension-pack|ms-|1.3.0
powershell|ms-|2023.3.3
vsliveshare|ms-|1.0.4498
vscode-json-editor|nic|0.3.0
java|red|0.80.0
vscode-commons|red|0.0.6
vscode-xml|red|0.17.0
llvm-ir|rev|1.0.4
synthwave-vscode|Rob|0.1.15
nomo-dark-extended|Sen|1.4.2
ninja|sur|0.0.1
cmake|twx|0.0.17
vscodeintellicode|Vis|1.2.14
vscode-java-debug|vsc|0.34.0
vscode-java-dependency|vsc|0.18.5
vscode-java-pack|vsc|0.17.0
vscode-java-test|vsc|0.30.1
vscode-maven|vsc|0.31.0

(5 theme extensions excluded)

</details>

**Comment by makeway4pK** [comment]
correction in my text above:  ...ignoring the **previously** open...

I expect the the Toggle Terminal action/shortcut to at least switch to the terminal in the editor view when a terminal is not already in focus. It would be handy if the toggle terminal action can be used to switch to and from between other non-terminal editor tabs and the terminal editor tab, just like the terminals in the panel.

Further, this switching can result in reduced function of the quick tab switch actions (ctrl+tab) which could be avoided if the terminal tabs aren't included in the recently used cache

**Comment by makeway4pK** [comment]
default keybinds:
New Terminal: Ctrl+Shift+`
Toggle Terminal: Ctrl+`


unrelated, I noticed that Toggle Maximized panel (Ctrl+M) doesn't bring focus to the terminal input

**Comment by jylin** [comment]
Agree, if this setting is on `"terminal.integrated.defaultLocation": "editor"`, then the toggle terminal command should switch to the first opened "editor terminal" instead of always opening a terminal panel.

**Comment by meganrogge** [comment]
To avoid confusion, all the terminal focus commands apply to the panel. When you move it to the editor, it's treated as an editor tab.
