### ISSUE TITLE
Accessibility: Make Debug Console follow terminal tabFocusMode

### ISSUE THREAD

**Issue by jooyoungseo** [microsoft/vscode#180083]
CC @meganrogge

I have found that Debug Console (Ctrl+Shift+Y) follows editor.tabFocusMode. However, it will make more sense to tether this with terminal tabFocusMode status by default.

**Comment by meganrogge** [comment]
https://github.com/microsoft/vscode/issues/175432 was the idea behind separating them - as you might always want one on or off

**Comment by meganrogge** [comment]
We have gotten rid of terminal tab focus mode, so closing this
