### ISSUE TITLE
Javascript files treated like TypeScript files

### ISSUE THREAD

**Issue by odebroqueville** [microsoft/vscode#180034]
Type: <b>Bug</b>

I have an options.js file (which is part of a Firefox web extension project) that includes the following line of code:

import Sortable from 'sortablejs';

At the beginning of 'sortablejs', there are 3 dots underlining it (...) and when I hover over those 3 dots, I see the following text:

Could not find a declaration file for module 'sortablejs'. '/Users/odebroqueville/Developer/contextSearch/node_modules/sortablejs/Sortable.min.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/sortablejs` if it exists or add a new declaration (.d.ts) file containing `declare module 'sortablejs';`ts(7016)
module "/Users/odebroqueville/Developer/contextSearch/node_modules/sortablejs/Sortable.min"

I don't understand why I'm seeing this message as my code is in JavaScript and not TypeScript!

I also have no Default Formatter set for the Editor.

Would you please help explain why I'm seeing the above message.
Thank you.

VS Code version: Code 1.77.3 (Universal) (704ed70d4fd1c6bd6342c436f1ede30d1cff4710, 2023-04-12T09:19:37.325Z)
OS version: Darwin x64 22.4.0
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7600K CPU @ 3.80GHz (4 x 3800)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|3, 2, 3|
|Memory (System)|40.00GB (20.50GB free)|
|Process Argv|--crash-reporter-id 129d43d7-f508-4741-9b27-28e1a51af91b|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (29)</summary>

Extension|Author (truncated)|Version
---|---|---
jsoncrack-vscode|Ayk|1.0.8
vscode-eslint|dba|2.4.0
vscode-dash|dee|2.4.0
vscode-firefox-debug|fir|2.9.8
auto-close-tag|for|0.5.14
auto-rename-tag|for|0.1.10
copilot|Git|1.82.15
vscode-pull-request-github|Git|0.62.0
language-julia|jul|1.38.2
vsc-python-indent|Kev|1.18.0
git-graph|mhu|1.30.0
isort|ms-|2022.8.0
python|ms-|2023.6.0
vscode-pylance|ms-|2023.4.20
jupyter|ms-|2023.3.1201040234
jupyter-keymap|ms-|1.1.0
jupyter-renderers|ms-|1.0.15
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-slideshow|ms-|0.1.5
live-server|ms-|0.4.7
incrementor|nms|1.0.3
indent-rainbow|ode|8.3.1
vscode-versionlens|pfl|1.5.0
material-icon-theme|PKi|4.26.0
quarto|qua|1.81.0
vscode-yaml|red|1.12.2
even-better-toml|tam|0.19.0
fig|wit|0.0.7
markdown-all-in-one|yzh|3.5.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vscaac:30438847
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
nodejswelcome1cf:30587006
3biah626:30602489
pyind779:30671433
f6dab269:30613381
pythonsymbol12:30671437
6233i204:30672705
vscodeenable:30660116
defaultazurewalk:30687958
pythonms35:30701012
pythonfmttext:30710681

```

</details>

**Comment by IllusionMH** [comment]
That's because JS functionality(intellisense, quick actions etc) is provided by TypeScript under the hood.

In your case it cannot find module declarations which it would use to provide suggestions for module exports. Without declarations it won't provide suggestions and just notifies you why there won't be any suggestions, but you can ignore them.

Do you have Automatic Types Aquisition (ATA) disabled? because usually VS Code downloads definition in background to provide module related intellisense even in JS files.
See docs for details https://code.visualstudio.com/docs/nodejs/working-with-javascript#_typings-and-automatic-type-acquisition

As for formatter - please check your configuration to remove incorrect config (e.g. previous formatter extension removed) or set formatter you want.

**Comment by odebroqueville** [comment]
I couldn't find any setting to enable/disable ATA. I added the following line of code to my user settings.json, but that didn't help!

"typescript.npm": /Users/username/.nvm/versions/node/v19.8.1/bin/npm

I finally typed the following command and that did solve the problem:

npm install --save @types/sortablejs

I don't really understand why type declarations are required for js (not typescript) node modules. I also don't understand why ATA isn't working for me!

**Comment by odebroqueville** [comment]
@mjbvz If ATA isn't working, then it's not a question, but an issue. You're a bit quick to close issues and not very helpful.

**Comment by mjbvz** [comment]
@odebroqueville This is a question about how VS Code works, not an issue

Type declaration packages power VS Code's intellisense for pacakges in both JS and TS. As the error says, without them then the package will have an `any` type so it won't have proper intellisense
