### ISSUE TITLE
Can not input Chinese in termial with zsh shell.

### ISSUE THREAD

**Issue by yeluoqiuzhi** [Microsoft/vscode#18018]
I can not input Chinese in integrated terminal with zsh shell.

e.g. When I input “你", It would look like this: 

![image](https://cloud.githubusercontent.com/assets/9261562/21598578/f8dbfbea-d199-11e6-8fea-8572489e928e.png)

**Comment by donnol** [comment]
do u try that adding the setting "export LANG=en_US.UTF-8 export LC_ALL=en_US.UTF-8" to your .zshrc?

**Comment by yeluoqiuzhi** [comment]
@donnol  thank you. It is well.
