### ISSUE TITLE
Folding icon invisible in gutter

### ISSUE THREAD

**Issue by ulugbekna** [microsoft/vscode#180107]
# Description

On github.dev ([link](https://github.dev/tree-sitter/tree-sitter-typescript/blob/master/queries/highlights.scm)), folding icon is invisible in the gutter, but clicking it works: 

https://user-images.githubusercontent.com/16353531/232437746-3c7647b5-f867-4761-af37-8ce3d030009f.mov

# Info

Version: 1.78.0-insider
Commit: 1e774371f2ca5f6618b4f40fdc72ce7518443014
Date: 2023-04-17T05:16:14.521Z
Browser: Chrome/112.0.0.0 Safari/537.36

**Comment by alexdima** [comment]
Caused by https://github.com/microsoft/vscode/pull/179910
