### ISSUE TITLE
Reloading window in zen mode goes into fullscreen mode without zen

### ISSUE THREAD

**Issue by TheColorRed** [Microsoft/vscode#18016]
- VSCode Version: 1.8.1
- OS Version: Ubuntu 16.10

Steps to Reproduce:

1. Enter Zen Mode
2. Press <kbd>F1</kbd>
3. Search for and execute `Reload Window`
4. You are now in full screen mode instead of zen mode

This causes the menu bar to disappear, and I could not figure out how to get it back because I didn't know I was in full screen mode instead of zen mode.

Basically it seems as if zen mode is getting turned off but fullscreen mode is not when the window is reloaded in zen mode.

**Comment by isidorn** [comment]
Yes, we have decided that zen mode is not preserved across sessions. The reason for this is if somebody goes into zen mode and does not know how to get out of it - he can simply restart vscode.

Though I agree that this can be confusing that full screen and zen get out of sync - happens to me all the time.
So I propose that zen mode is preserved across vscode sessions.

@bpasero any suggestions maybe?

**Comment by bpasero** [comment]
Why not just preserve it when a window reload happens? We know if a reload happens vs. a restart (https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/electron-browser/workbench.ts#L798)

**Comment by isidorn** [comment]
@bpasero good idea - I'll go with that
