### ISSUE TITLE
It would be nice to have the close button on the left, or tabs with the same width.

### ISSUE THREAD

**Issue by paulo-fernando-silva** [Microsoft/vscode#18013]
- VSCode Version: Version 1.8.1 (1.8.1)
- OS Version: MacOS/OSX

The title says it all. A simple patch that "fixes" the issue is in attach. 
It's not so much because OSX has the close button on the left, but more because it's inefficient to have to move the mouse to close two tabs in a sequence. Think of chrome. It does it very well. When you close a tab, before resizing the tabs, the tab on the right will end up with its close button on the same location as the closed tab - that is, right under the mouse. This can be accomplished without resizing the tabs by placing it on the left. It even matches the OSX button placement. For me the patch works, but I would prefer to still get automatic updates without having to reapply it. I don't know if this can be applied as an extension - didn't research it. If yes, do let me know. I'll implement it.

<img width="1280" alt="code" src="https://cloud.githubusercontent.com/assets/6506378/21593127/41c6ea1a-d157-11e6-8532-92114482ae02.png">
[Code.patch.txt](https://github.com/Microsoft/vscode/files/681142/Code.patch.txt)

**Comment by bpasero** [comment]
This issue has already been reported. Please use the search function next time before reporting an issue and/or this time if you are curious about the progress of the issue.

**Comment by paulo-fernando-silva** [comment]
I did, but I didn't find it. Sorry about that. It would be nice if you could post the link to the issue instead of assuming that people didn't use the search function.
Thanks
