### ISSUE TITLE
Replace does not work with regex assertions

### ISSUE THREAD

**Issue by gomico** [microsoft/vscode#180101]
Version: 1.77.3
OS: Win10 22H2 and Win11 22H2
Extensions: all disabled

I have a markdown file with tens of fenced code blocks without language specified. I want to find the **```** at the beginning of each code block and append a language to it (like text, json, and shell). Here's an example of my file content:

````text
An example is as follows:

```
<a linux command>
```

By default, the exception detection rules use expressions to create the description of the collected data. The standard expressions look like follows:

```
<expression><operator><expression>
```
````

![屏幕截图 2023-04-17 151717](https://user-images.githubusercontent.com/40701601/232412478-a45bfa16-9329-47e9-a91e-e065b9a21bb7.png)

What I'm trying to do is that, search for ``(?<=^ *$\n *``` *)``, confirm it is a shell script, and replace it with `shell`, so **\```** becomes **\```shell**. (_The screenshot shows replace with text but you know what I mean._)
What actually happens is that, after matching the **\```** above `<a linux command>`, I hit the replace button but nothing is changed. I can click the replace all button to add **shell** after each **\```** but that's not what I want.

**Comment by roblourens** [comment]
Your pattern is only a lookbehind assertion, which by itself doesn't match anything and isn't part of the replacement. You need a regex pattern that matches something in order to do a replace
