### ISSUE TITLE
enable single disabled breakpoint after disabling all breakpoints 

### ISSUE THREAD

**Issue by johnbendi** [microsoft/vscode#180189]
I will like to be able to enable a single breakpoint after toggling to disable all breakpoints. Currently I don't believe this is possible as trying to enable a single breakpoint enables all breakpoint previously disabled via the toggle.

**Comment by roblourens** [comment]
This model is a bit tricky, but you can right click > "disable all breakpoints", which will simply uncheck them, then check the one you want to enable, instead of using the menu button that you are probably referring to
