### ISSUE TITLE
Open multiple folders in one instance

### ISSUE THREAD

**Issue by Doug290** [Microsoft/vscode#18010]
- VSCode Version: 1.8.1
- OS Version: Sierra 10.12.2

I would like to open several projects in only one instance of VScode. That would be of a great help.

**Comment by bpasero** [comment]
This issue has already been reported. Please use the search function next time before reporting an issue and/or this time if you are curious about the progress of the issue.

**Comment by bwowk** [comment]
Duplicate of #396, btw
