### ISSUE TITLE
[css] Disable prefixes from CSS/SCSS autocomplete suggestions

### ISSUE THREAD

**Issue by druellan** [Microsoft/vscode#18011]
- VSCode Version: 1.8.1
- OS Version: Win7 64

Steps to Reproduce:

1. Open/create a CSS file and type: `transition-`
2. The autocomplete window will show suggestions for `-webkit-transition`- or `-o-transition-` that pretty much fill up the popup.

![2017-01-02_12h01_40](https://cloud.githubusercontent.com/assets/6965667/21591774/d15656c4-d0e5-11e6-9a94-91f20d7e128a.png)

I found that annoying since most of the time I use snippets or some kind of Autoprefixer to handle that, and currently seems that there is no option to disable them.

Can I suggest something like `css.suggest.vendorPrefix` ?
Thanks!

**Comment by aeschli** [comment]
Vendor specific properties are now sorted after the regular properties.

**Comment by druellan** [comment]
Thanks @aeschli
