### ISSUE TITLE
EditorGroupsService: closeEditors timeout

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#180155]
Build: https://dev.azure.com/monacotools/a6d41577-0fa3-498e-af22-257312ff0545/_build/results?buildId=211100
Changes: https://github.com/Microsoft/vscode/compare/ec46824...d3d397c

https://dev.azure.com/monacotools/Monaco/_build/results?buildId=211100&view=logs&j=55ac390b-ffb1-50ea-3650-525dd9a3fd80&t=a0dd9636-50d2-5f8a-f17f-6bcaa254d802&l=10474

<img width="1112" alt="Screenshot 2023-04-17 at 12 54 34 PM" src="https://user-images.githubusercontent.com/29464607/232596054-b92bdd53-55cb-4759-a470-281e42c28fc6.png">

**Comment by bpasero** [comment]
As strange as https://github.com/microsoft/vscode/issues/179923, I wonder if our CI is acting up weird.

**Comment by bpasero** [comment]
Seems like a CI fluke to me:

![image](https://user-images.githubusercontent.com/900690/234884488-09f8fd29-1106-4468-b110-a539ebaf957f.png)
