### ISSUE TITLE
$ref 'globalconfiguration' in schema/settings can not be resolved

### ISSUE THREAD

**Issue by gaurangrshah** [microsoft/vscode#180141]
Type: <b>Bug</b>

I started a new project recently with create-t3-app, and started to see this error in the package.json file of the newly created project:

```
$ref 'gobalconfiguration' in 'vscode://schemas/settings/configurationDefaults' can not be resolved.(768)
```
This seems to now be happening across all of my projects so this leads me to believe the issue is directly with in my vscode settings schema. 

VS Code version: Code 1.77.3 (704ed70d4fd1c6bd6342c436f1ede30d1cff4710, 2023-04-12T09:41:48.638Z)
OS version: Darwin arm64 21.6.0
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|2, 2, 2|
|Memory (System)|8.00GB (0.09GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (82)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|3.0.2
vscode-file-peek|abi|1.0.1
yaml2json|ahe|0.0.4
Bookmarks|ale|13.3.1
vscode-color-picker|Ant|0.0.4
aspect-ratio|Bab|0.0.1
vscode-database|baj|2.2.3
vscode-custom-css|be5|7.1.0
vscode-toggle-quotes|Bri|0.3.6
turbo-console-log|Cha|2.9.3
npm-intellisense|chr|1.4.4
path-intellisense|chr|2.8.4
package-json-upgrade|cod|1.6.0
vscode-eslint|dba|2.4.0
vscode-new-file|dku|4.0.2
vscode-npm-source|dku|1.0.0
eslint-disable-snippets|drK|1.3.0
es7-react-js-snippets|dsz|4.4.3
gitlens|eam|13.5.0
replacequotes|eda|0.0.1
vscode-front-matter|eli|8.4.0
prettier-vscode|esb|9.10.4
file-icons|fil|1.0.29
auto-complete-tag|for|0.1.0
auto-rename-tag|for|0.1.10
vscode-vercel|fre|1.0.3
copilot|Git|1.82.15
copilot-labs|Git|0.12.791
remotehub|Git|0.54.0
vscode-pull-request-github|Git|0.62.0
search-with-cursor|has|0.1.5
json-and-jsonc|htw|1.0.1
npm|ide|1.3.0
css-to-jss|inf|1.0.7
vscode-react-typescript|inf|1.3.1
sandbox|jcc|1.0.1
npm-package-version-bumper|jef|1.6.0
vscode-peacock|joh|4.2.2
vscode-note-book|kam|0.0.5
chat|kar|0.35.0
vscode-gist|ken|3.0.3
hyper-vsc|Lev|1.0.3
template-string-converter|meg|0.6.1
dotenv|mik|1.0.1
vscode-duplicate|mrm|1.2.1
vscode-edge-devtools|ms-|2.1.1
remote-ssh|ms-|0.100.0
remote-ssh-edit|ms-|0.84.0
remote-explorer|ms-|0.4.0
remote-repositories|ms-|0.32.0
remote-server|ms-|1.0.0
sublime-keybindings|ms-|4.0.10
vsliveshare-pack|ms-|0.4.0
color-highlight|nau|2.5.0
back-n-forth|nic|3.1.1
vscode-extension-auto-import|Nuc|1.4.3
docthis|oou|0.8.2
vscode-twoslash-queries|Ort|1.1.0
convert-css-in-js|pau|1.1.3
git-file-history|pom|1.0.1
prisma|Pri|4.12.0
subtle-brackets|raf|3.0.0
vscode-thunder-client|ran|2.6.2
postcode|roh|1.3.9
shortenurl|Ros|1.1.0
indenticator|Sir|0.7.0
comment-divider|sta|0.4.0
marquee|sta|3.3.0
code-spell-checker|str|2.20.4
linear|str|0.0.3
chakra-ui-doc|tim|1.0.0
errorlens|use|3.9.0
highlight-matching-tag|vin|0.11.0
intellicode-api-usage-examples|Vis|0.2.7
vscodeintellicode|Vis|1.2.30
console-ninja|Wal|0.0.106
quokka-vscode|Wal|1.0.531
vscode-todo-highlight|way|1.0.5
vscode-nextjs-snippets|wil|0.3.0
glean|wix|5.2.2
vscode-import-cost|wix|3.3.0
open-in-external-app|YuT|0.9.7

(2 theme extensions excluded)

</details>

**Comment by sandy081** [comment]
@aeschli Any insights about this?

**Comment by gaurangrshah** [comment]
> @aeschli Any insights about this?

I'm still seeing this issue, and really haven't found much in regards to the error anywhere online as of yet.

**Comment by unional** [comment]
I saw the same thing and it seems like it is caused by front matter.

**Comment by unional** [comment]
https://github.com/estruyf/vscode-front-matter/blob/4fb32bbf9eb55375b030a453f7500a14b47af2a1/package.json#L97

**Comment by gaurangrshah** [comment]
> https://github.com/estruyf/vscode-front-matter/blob/4fb32bbf9eb55375b030a453f7500a14b47af2a1/package.json#L97

You're referring to the [front matter cms](https://frontmatter.codes) extension right? 

Yup, I can confirm that disabling the extension did remove the error for me.

**Comment by unional** [comment]
https://github.com/estruyf/vscode-front-matter/pull/574
