### ISSUE TITLE
Feedback - Improve loading time

### ISSUE THREAD

**Issue by 40tude** [Microsoft/vscode#18014]
Bonjour,
- VSCode Version: Code 1.8.1 (ee428b0eead68bf0fb99ab5fdc4439be227b6281, 2016-12-19T14:49:23.350Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

|Extension|Author|Version|
|---|---|---|

---

Steps to Reproduce:
0. Make sure VSCode do not have ANY extension installed
1. Go to http://www.passmark.com/products/apptimer.htm
2. Download Pass App Mark Timer. Note : I did'nt know this application until today. May be there is a more accurate way to make these type of measurments.
3. Configure it properly such a way VSCode is loaded with no file
4. Follow similar process with Notepad++

Here are the results I get (Surface Book, i7, 8 GB)
C:\Program Files (x86)\Notepad++\notepad++.exe - 3 executions
0.4030 sec
0.3738 sec
0.3741 sec

C:\Program Files (x86)\Microsoft VS Code\Code.exe - 3 executions
2.9274 sec
2.7750 sec
2.6008 sec

So on average this is .38 sec. vs 2.76 sec.
This means VSCode is 7 time slower than Notepad++

This might become more and more important for users since I realize I use more and more VSCode to edit any kind of file using the right click on the filename. Each time I'm a little bit furstrated by the load time (even if I understand why 

Best regards, Philippe

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/15455
