### ISSUE TITLE
terminal input bug

### ISSUE THREAD

**Issue by KongQBin** [microsoft/vscode#180180]
Type: <b>Bug</b>

When a command is entered quickly, a character is entered repeatedly.  For example, 'ls' becomes' lss';  'clear' becomes' cleeaar '.  The probability of recurrence is very high.

VS Code version: Code 1.77.3 (704ed70d4fd1c6bd6342c436f1ede30d1cff4710, 2023-04-12T09:16:52.732Z)
OS version: Linux x64 5.4.214-1.el7.elrepo.x86_64
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz (8 x 2803)|
|GPU Status|2d_canvas: unavailable_software<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>opengl: disabled_off<br>rasterization: disabled_software<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software<br>webgpu: disabled_off|
|Load (avg)|1, 1, 1|
|Memory (System)|6.76GB (2.41GB free)|
|Process Argv|--crash-reporter-id 1717025a-136d-4aae-8cef-150dfc756582|
|Screen Reader|no|
|VM|100%|
|DESKTOP_SESSION|gnome-classic|
|XDG_CURRENT_DESKTOP|GNOME-Classic:GNOME|
|XDG_SESSION_DESKTOP|gnome-classic|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
markdown-preview-github-styles|bie|2.0.0
git-graph|mhu|1.30.0
vscode-language-pack-zh-hans|MS-|1.77.2023040509
cmake-tools|ms-|1.13.45
cpptools|ms-|1.14.5
cpptools-extension-pack|ms-|1.3.0
cmake|twx|0.0.17
vscode-icons|vsc|12.3.0
vscode-todo-highlight|way|1.0.5
material-theme|zhu|3.15.8

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyonecf:30548226
vscccc:30610679
nodejswelcome1:30587005
282f8724:30602487
pyind779:30671433
89544117:30613380
pythonsymbol12:30671437
showlangstatbar:30672706
azdwalk:30687957
pythonms35:30701012
pythonfmttext:30716742

```

</details>

**Comment by meganrogge** [comment]
Please provide a screenshot or [a gif](https://gifcap.dev/) illustrating the problem (attaching images won't work via email, you need to go to github.com). See [this wiki page](https://github.com/microsoft/vscode/wiki/Terminal-Issues) for more general info on how to report actionable terminal issues.
/label info-needed terminal

**Comment by KongQBin** [comment]
![Peek 2023-04-20 10-21](https://user-images.githubusercontent.com/51445817/233241666-994bf6fe-a6bd-4d47-ae05-41e5a28996a2.gif)

**Comment by KongQBin** [comment]
The problem has been located. It is caused by the "Intelligent PinYin" input method of CentOS7 system. After switching the input method, it becomes normal.
