### ISSUE TITLE
performance is very slow

### ISSUE THREAD

**Issue by guruprasath-5502** [microsoft/vscode#180150]
Type: <b>Performance Issue</b>

almost 5 days today is 6th day i am facing this issue . It occurs on startup . I have uninstalled and installed again , but I  get the same issues .

VS Code version: Code 1.77.3 (704ed70d4fd1c6bd6342c436f1ede30d1cff4710, 2023-04-12T09:16:02.548Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|12th Gen Intel(R) Core(TM) i7-12650H (16 x 2688)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.63GB (8.26GB free)|
|Process Argv|--crash-reporter-id 8dd91830-ee74-4c15-b934-77f97160f75a|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	   103	 18368	code main
    0	   114	  2428	shared-process
    0	    82	 13804	     ptyHost
    0	    63	  2436	   utility-process
    0	   222	  3048	window [1] (Visual Studio Code)
    0	    85	 10312	fileWatcher [1]
    0	    28	 10712	   crashpad-handler
    0	   178	 10996	   gpu-process
    0	    46	 21424	   utility-network-service
    0	    84	 21476	window [3] (Issue Reporter)
```

</details>
<details>
<summary>Workspace Info</summary>

```
;
```

</details>
<details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-tailwindcss|bra|0.9.11
npm-intellisense|chr|1.4.4
es7-react-js-snippets|dsz|4.4.3
prettier-vscode|esb|9.10.4
code-runner|for|0.12.0
vscode-power-mode|hoo|3.0.2
vscode-react-native|msj|1.10.2
color-highlight|nau|2.5.0
material-icon-theme|PKi|4.26.0
LiveServer|rit|5.7.9
JavaScriptSnippets|xab|1.8.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
vsccc:30610678
nodejswelcome1:30587005
3biah626:30602489
pyind779:30671433
f6dab269:30613381
pythonsymbol12:30671437
showlangstatbar:30672706
azdwalk:30687957
pythonms35:30701012
pythonfmttextcf:30716743
pythonclientmvcf:30713944

```

</details>

**Comment by Billcountry** [comment]
Facing this on WSL.
Moved to full linux still facing the same issue

**Comment by deepak1556** [comment]
Merging to https://github.com/microsoft/vscode/issues/178962

Please follow the steps in https://github.com/microsoft/vscode/issues/178733#issuecomment-1500812938 as a temporary workaround.
