### ISSUE TITLE
Multiple background gradations

### ISSUE THREAD

**Issue by andi1984** [Microsoft/vscode#18012]
Hi,

I've the issue that my editor consists of multiple background gradations of different sizes (see screenshot at the end). This issue appears independent of the color theme and the viewed file type, but of course within the theme's color space.

The darker background is changing in widths based on the different code blocks' widths and the currently cursor position. The code block the cursor currently is in has always full width. But this issue not only appears in the editor, but also in the extensions sidebar (see second screenshot).

So it is totally unrelated to the color theme or the type of file viewing.

<img width="700" alt="vscode-multiple-backgrounds" src="https://cloud.githubusercontent.com/assets/1077917/21592338/d54afef2-d10c-11e6-8448-5242864efa7a.png">

![vscode-multiple-backgrounds-sidebar](https://cloud.githubusercontent.com/assets/1077917/21592395/70e54516-d10d-11e6-8d15-a3b68c7a2f55.png)

- VSCode Version: 1.8.1
- OS Version: macOS Sierra (10.12.1)

**Comment by bpasero** [comment]
#12473
