### ISSUE TITLE
Try to reload a notebook editor when its viewtype is installed or enabled

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#180191]
Related to https://github.com/microsoft/vscode/issues/179224

Enabling a notebook extension should ideally reload the editor with that view type without having to jump to another editor and back:

![Recording 2023-04-18 at 09 35 25](https://user-images.githubusercontent.com/900690/232705461-1d58f231-7595-488e-bb9e-326396bfb469.gif)

**Comment by rebornix** [comment]
In this scenario:

* Open NotebookEditorInput, it doesn't resolve and throw an error with actions
* Actions are rendered now in a Placeholder editor
* Serializer enabled, editor/view type provider registered

I'm not sure where is the best place to register the view type listener. IMHO we should register this in notebook land, but we would then need to tell the editor service to replace the Placeholder Editor with a new editor. @bpasero any suggestion?

**Comment by bpasero** [comment]
@rebornix this flow seems to actually work fine when I use the button in the placeholder editor:

![Recording 2023-04-19 at 08 23 28](https://user-images.githubusercontent.com/900690/232984570-c4d50b96-2797-44db-9c59-ee4ba12736bf.gif)

Given that, I am fine closing this as out of scope for now given it will not be the primary interaction from the user most likely.

I notice however, that when the extension is not installed, you briefly switch to the extension editor and then back to the notebook, I wonder if that flow can be made smoother.

**Comment by bpasero** [comment]
Hm, actually it may be nice to show the extension to the user so that the user gets to see what is being installed. Maybe we just leave it like this!

![Recording 2023-04-19 at 08 26 21](https://user-images.githubusercontent.com/900690/232985152-0d843ae9-ca51-4285-8b1e-e7fd835205e1.gif)

**Comment by rebornix** [comment]
@bpasero yeah that's the default experience of Install Recommended Extension. It gives users more awareness what's being installed.

Let's close this for now and see if we want to improve this later.
