### ISSUE TITLE
Wildcards in typescript.tsdk path

### ISSUE THREAD

**Issue by nickiaconis** [microsoft/vscode#180161]
**Context**

I have a project with multiple packages that I'm managing with Rush + PNPM. In this environment, dependencies get installed in `./common/temp/node_modules/.pnpm/package@version/node_modules/package`. This means the path to the local typescript version looks something like `./common/temp/node_modules/.pnpm/typescript@4.9.3/node_modules/typescript/lib`.

I have the typescript version specified with the caret modifier, allowing for minor and patch updates without requiring a change to package.json. Recently, while installing a new dependency, a new patch version of typescript was automatically installed. As a result, the `typescript.tsdk` path specified in `.vscode/settings.json` became no longer valid. I had actually forgotten that I had needed to set this path in the first place, and so for a while I was left wondering why VS Code couldn't find the local typescript version to use. Eventually, I determined that I needed to manually update the path to `./common/temp/node_modules/.pnpm/typescript@4.9.4/node_modules/typescript/lib`.

**Feature Request**

It would be a great QoL feature to allow wildcards in the `typescript.tsdk` path. It could eliminate the need to update this path manually for every version update, if used properly. For example, in the above outlined situation, the path could become something like `./common/temp/node_modules/.pnpm/typescript@*/node_modules/typescript/lib`, depending on the final syntax selected. This would match both paths from the context above and any future update to the version number:

- `./common/temp/node_modules/.pnpm/typescript@4.9.3/node_modules/typescript/lib`
- `./common/temp/node_modules/.pnpm/typescript@4.9.4/node_modules/typescript/lib`
- `./common/temp/node_modules/.pnpm/typescript@5.0.2/node_modules/typescript/lib`
- etc…

**Open Questions**

- What should the behavior be if a path with wildcard(s) resolves to more than one directory?
  - I don't know how likely it would be, but it seems reasonable to believe this could indeed happen.

**Comment by mjbvz** [comment]
I appreciate the detailed writeup but this adds complexity for a niche use case. The workaround is also simple: bump the setting when bumping your TS version. You could even do this with a script but that's probably overkill

Closing as I don't think it's worth it for core VS Code
