### ISSUE TITLE
Double-clicking custom title bar doesn't restore maximized window on Mac

### ISSUE THREAD

**Issue by gtritchie** [microsoft/vscode#180139]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version:  1.77.3
- OS Version: macOS Ventura 13.3.1

Steps to Reproduce:

1. Ensure using the "custom" window title bar style (the default)
2. Resize the VSCode window to something easily distinguishable from maximized
3. Double-click the title bar; window maximizes
4. Double-click the title bar again; window does not restore to the previous size as it should

I also opened an issue about quirky restore behaviour when using the native title bar style: #180138

**Comment by bpasero** [comment]
Actually this now seems entirely handled natively when appkit region drag is set. You can configure the behaviour you want from macOs settings:

![Image](https://github.com/user-attachments/assets/b22090eb-434c-421f-a8e1-2ecd10e8b9d2)
