### ISSUE TITLE
Build failed:    EditorMemento - use with editor input Assertion failed: (timeout != -1)

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#180225]
Build: https://dev.azure.com/monacotools/a6d41577-0fa3-498e-af22-257312ff0545/_build/results?buildId=211221
Changes: https://github.com/Microsoft/vscode/compare/7559567...498b681

![Screenshot 2023-04-18 at 7 18 00 AM](https://user-images.githubusercontent.com/29464607/232806208-d58b1915-ace0-4d29-af3c-51836029f502.png)

**Comment by meganrogge** [comment]
it's odd because there's a checkmark by the test as if it passed though 🤔

**Comment by bpasero** [comment]
I have updated `playwright` to latest, lets see.

**Comment by bpasero** [comment]
There are some related issues with the same error indicating that the error comes from an old node.js version, but I doubt we use that of an old version. Lets see.
