### ISSUE TITLE
Allow recommended extensions on the welcome page to be turned off

### ISSUE THREAD

**Issue by miguelsolorio** [microsoft/vscode#180232]
On the welcome page, there is a new "recommended extensions" section that, when dismissed, keeps coming back with different extensions:

![CleanShot 2023-04-18 at 08 54 52](https://user-images.githubusercontent.com/35271042/232834041-71adb819-ec96-447c-aefe-7af3ab5cfb3b.png)

![CleanShot 2023-04-18 at 08 58 31@2x](https://user-images.githubusercontent.com/35271042/232835361-f1080ffe-ac60-4dc9-b8dc-9806475000c1.png)

On behalf of those that like a clean/empty welcome page, I'd like to request to have a setting to turn off these recommendations so you don't have to keep dismissing these.

Ref https://github.com/microsoft/vscode/issues/178831

**Comment by DanielRouxSA** [comment]
I would also like to be able to turn this off, especially since it is now being used to advertise GitHub Copilot.

**Comment by bhavyaus** [comment]
Recommended extensions are no longer supported.
