### ISSUE TITLE
Unable to select prev/next item in Command Palatte using ctrl+p/ctrl+n

### ISSUE THREAD

**Issue by R--J** [Microsoft/vscode#18024]
- VSCode Version: 1.8.1
- OS Version: macOS Sierra 10.12.2

Steps to Reproduce:

1. Open Command Palatte

It is possible to set emacs key-binding "ctrl+p/ctrl+n" to select prev/next item in editor suggesion. But it seems that I can't use the same key-binding selecting prev/next item in command palatte. I've searched the "keyboard shortcuts" configuration file, but didn't find a corresponding command.

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/7876
