### ISSUE TITLE
Auto-close back-tick

### ISSUE THREAD

**Issue by tstringer** [Microsoft/vscode#1802]
In VS Code, currently when you type an opening single or double quote, the IDE will auto-close the string.  I.e.

```javascript
// type single quote, closing quote auto-filled
'<cursor_here>'

// type double quote, closing quote auto-filled
"<cursor_here>"

// type back-tick (es6 template string), no auto-filled closing back-tick
`<cursor_here>
```

As you can see in the above sample (using `<cursor_here>` to indicate where the cursor is located after the char), the back-tick doesn't exhibit the same behavior as the single/double quotes.

This is a nice-to-have, as the template string should follow the same editor behavior as the single/double-quoted strings.

**Comment by felixfbecker** [comment]
:+1: backticks are so annoying to type
