### ISSUE TITLE
Cannot update on Ubuntu

### ISSUE THREAD

**Issue by pmattes** [microsoft/vscode#180250]
$ sudo apt update
...
W: Failed to fetch https://packages.microsoft.com/repos/code/dists/stable/InRelease  Certificate verification failed: The certificate is NOT trusted. The certificate chain uses expired certificate.  Could not handshake: Error in the certificate verification. [IP: 13.90.56.68 443]

W: Some index files failed to download. They have been ignored, or old ones used instead.

**Comment by neverabsolute** [comment]
+1, looks like the SSL cert for the domain expired lol

**Comment by pmattes** [comment]
And it was apparently fixed while I was typing in the description.

**Comment by neverabsolute** [comment]
that was fast

**Comment by pmattes** [comment]
I'll guess they were in the process of fixing it already.
