### ISSUE TITLE
Slow Start

### ISSUE THREAD

**Issue by 1fox4** [microsoft/vscode#180255]
Type: <b>Performance Issue</b>

I dont know when it started, and i dont know what i have done to become like this

VS Code version: Code 1.77.3 (704ed70d4fd1c6bd6342c436f1ede30d1cff4710, 2023-04-12T09:16:02.548Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.87GB (8.01GB free)|
|Process Argv|--crash-reporter-id da1c2326-2f36-4a4e-9aba-1fc0f1770db0|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	   106	  3392	code main
    0	    42	  5492	   utility-network-service
    0	   134	  6476	   gpu-process
    0	    88	  8808	shared-process
    0	    67	 11052	     ptyHost
    0	   189	  9892	window [1] (Visual Studio Code)
    0	    69	 15768	fileWatcher [1]
    0	    23	 16372	   crashpad-handler
    0	   142	 20768	extensionHost [1]
    0	    36	 17420	     c:\Users\filip\.vscode\extensions\ms-vscode.cpptools-1.14.5-win32-x64\bin\cpptools.exe
    0	     4	  1852	       "c:\Users\filip\.vscode\extensions\ms-vscode.cpptools-1.14.5-win32-x64\bin\cpptools.exe"
    0	     6	 16260	       console-window-host (Windows internal process)
    0	    91	 20924	window [2] (Issue Reporter)
```

</details>
<details>
<summary>Workspace Info</summary>

```
;
```

</details>
<details><summary>Extensions (17)</summary>

Extension|Author (truncated)|Version
---|---|---
doxdocgen|csc|1.4.0
c-cpp-runner|fra|5.2.1
cmake-language-support-vscode|jos|0.0.9
vscode-dotnet-runtime|ms-|1.6.0
python|ms-|2023.6.1
remote-containers|ms-|0.288.1
remote-ssh|ms-|0.100.0
remote-ssh-edit|ms-|0.84.0
remote-wsl|ms-|0.77.0
cmake-tools|ms-|1.13.45
cpptools|ms-|1.14.5
cpptools-extension-pack|ms-|1.3.0
remote-explorer|ms-|0.4.0
vsliveshare|ms-|1.0.5862
gcc-md|pha|0.0.1
cmake|twx|0.0.17
vscode-lldb|vad|1.9.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
nodejswelcome1cf:30587006
3biah626:30602489
pyind779:30671433
f6dab269:30613381
pythonsymbol12:30671437
showlangstatbar:30672706
vsctsb:30705553
azdwalk:30687957
pythonms35:30701012
j16hj152:30706079
pythonfmttext:30716742

```

</details>

**Comment by deepak1556** [comment]
@1fox4 do you have Mcafee AV installed ? We had a couple of issues reported about the AV slowing down the application (including hanging renderers) with latest updates, refs https://github.com/microsoft/vscode/issues/178962.

**Comment by 1fox4** [comment]
yes i have, i can do something to resolve that?

A qua, 19 de abr de 2023, 06:17, Robo ***@***.***> escreveu:

**Comment by deepak1556** [comment]
Can you follow the steps in https://github.com/microsoft/vscode/issues/178733#issuecomment-1500812938 and exclude the `code.exe` binary ?

Merging to https://github.com/microsoft/vscode/issues/178962

**Comment by 1fox4** [comment]
it works, thank you

Robo ***@***.***> escreveu no dia quarta, 19/04/2023 à(s)
12:42:
