### ISSUE TITLE
vscode不能设置断点

### ISSUE THREAD

**Issue by YSHIDM** [Microsoft/vscode#18021]
vscode cannot set breakpoint.

**Comment by yeyuguo** [comment]
我的也是刚刚出现了不能设置断点

**Comment by yeyuguo** [comment]
我的刚刚找到问题了，是文件格式不对，把右下角的  语言选择模式设置成 JS 的，断点功能就又出现了

**Comment by YSHIDM** [comment]
右下角：禁用Babel相关扩展并重启,Javascript(Babel)变成Javascript，依旧不起作用。





------------------ 原始邮件 ------------------
发件人: "Struggling Youth";<notifications@github.com>;
发送时间: 2017年1月3日(星期二) 下午2:20
收件人: "Microsoft/vscode"<vscode@noreply.github.com>; 
抄送: "YSHI"<1179082420@QQ.COM>; "Author"<author@noreply.github.com>; 
主题: Re: [Microsoft/vscode] vscode不能设置断点 (#18021)




我的刚刚找到问题了，是文件格式不对，把右下角的  语言选择模式设置成 JS 的，断点功能就又出现了

**Comment by yeyuguo** [comment]
我的 Babel 那些都没禁用 其他什么设置也没改动，就自己手动点击切换成 javascript 就ok 了，如果这个都没解决的话   就不知道啥情况了 - - 我的切换过来后现在一直在用断点功能

**Comment by YSHIDM** [comment]
俩电脑一个行，一个不行






------------------ 原始邮件 ------------------
发件人: "Struggling Youth";<notifications@github.com>;
发送时间: 2017年1月3日(星期二) 下午2:13
收件人: "Microsoft/vscode"<vscode@noreply.github.com>; 
抄送: "YSHI"<1179082420@QQ.COM>; "Author"<author@noreply.github.com>; 
主题: Re: [Microsoft/vscode] vscode不能设置断点 (#18021)




我的也是刚刚出现了不能设置断点

**Comment by sandy081** [comment]
@YSHIDM Can you please provide proper
- summary 
- description with steps to reproduce

Also please give the details in English.

Thanks

**Comment by YSHIDM** [comment]
Thank you for your help.
Machine translation:



Red box locations there is no spatial setting breakpoints.
(No space to set breakpoint!)
Normal should be like this:





------------------ 原始邮件 ------------------
发件人: "Sandeep Somavarapu";<notifications@github.com>;
发送时间: 2017年1月3日(星期二) 下午5:41
收件人: "Microsoft/vscode"<vscode@noreply.github.com>; 
抄送: "YSHI"<1179082420@QQ.COM>; "Mention"<mention@noreply.github.com>; 
主题: Re: [Microsoft/vscode] vscode不能设置断点 (#18021)




@YSHIDM Can you please provide proper
  
summary
 
description with steps to reproduce
  
Also please give the details in English.
 
Thanks

**Comment by sandy081** [comment]
@YSHIDM Can you please provide a screenshot or a video of what you are facing?

**Comment by YSHIDM** [comment]
NOTHING!UNABLE!


------------------ 原始邮件 ------------------
发件人: "Sandeep Somavarapu";<notifications@github.com>;
发送时间: 2017年1月3日(星期二) 晚上6:24
收件人: "Microsoft/vscode"<vscode@noreply.github.com>; 
抄送: "YSHI"<1179082420@QQ.COM>; "Mention"<mention@noreply.github.com>; 
主题: Re: [Microsoft/vscode] vscode不能设置断点 (#18021)




@YSHIDM Can you please provide a screenshot or a video of what you are facing?
