### ISSUE TITLE
502 bad gateway

### ISSUE THREAD

**Issue by karneaud** [microsoft/vscode#180247]
I'm using the NPM/ YArn image to run a server using `http.createServer`. I have the respective ports `9229`( web sockets) and `2567` forwarded but for some reason I get 

> 502 Bad Gateway

when trying to preview the forwarded port url.

The websocket port seems to work fine though

Version: 1.77.3
Commit: 704ed70d4fd1c6bd6342c436f1ede30d1cff4710
User Agent: Mozilla/5.0 (Linux; Android 10; 8094M) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Mobile Safari/537.36
Embedder: codespaces

**Comment by alexr00** [comment]
@karneaud is your forwarded port public or private? Is this in a public repo where I can try it out?

**Comment by karneaud** [comment]
It appears that the error was fixed by changing `https.createServer` to `http.createServer`
