### ISSUE TITLE
Shortcut [command + .(dot)] not working in vscode web

### ISSUE THREAD

**Issue by kianfang** [microsoft/vscode#180201]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version:  [1.77.3 for web](https://vscode.dev/)
- OS Version: `MacOS 12.6` & `Chrome 112.0.5615.49`

Steps to Reproduce:

1. Open `Developer: Toggle Keyboard Shortcuts Troubleshooting` to debug
2. Enter this shortcut `command .` to execute `Quick Fix...`
3. Trouble: `Quick Fix...` not executed. It's only listening to `command` input, not listening to `.` input
<img width="1443" alt="image" src="https://user-images.githubusercontent.com/16569491/232735483-fc65f23f-6e7a-4dc5-ae4b-a0545bf70fdc.png">

**Comment by roblourens** [comment]
Do you have any browser extensions that could be intercepting this keybinding?

**Comment by kianfang** [comment]
> 

There are some plugins, but I have opend incognito window testing.

**Comment by kianfang** [comment]
I found the shortcut key entry for Chrome extensions, and upon inspection, it was found that.

Removing this shortcut key will solve the problem.
<img width="1396" alt="image" src="https://user-images.githubusercontent.com/16569491/232973180-e3b5e7d7-a65c-48ee-8480-25b8b2d6fe7c.png">
The extensions shortcut key entry is:
[chrome://extensions/shortcuts]()

**Comment by kianfang** [comment]
> Do you have any browser extensions that could be intercepting this keybinding?

Thank you for reminding me.
