### ISSUE TITLE
Add "play" button to Outline for jupyter notebooks

### ISSUE THREAD

**Issue by Riezebos** [microsoft/vscode#180272]
I'm a big fan of using the Outline to see and navigate the structure of a long Jupyter Notebook. Similarly, I'm a big fan of being able to run a single test, or a test file, or a folder of tests using the "play" button in the "Testing" panel. It would be useful to have similar functionality in the Outline panel, to be able to run a whole section/subsection of a notebook at once. I can imagine that this is not what the Outline is meant for. In that case another option would be to add a "play" button next to the "fold" button that can be used to fold/unfold a section of a jupyter notebook.

**Comment by Yoyokrazy** [comment]
There will now be a toolbar in relevant md and code cell entries in the outline view. Given the context of the cell, you will have the following options:
- Run Cells in Section (if cell is md, with children)
- Run Cell (if cell is code)
- Expand / Fold Section (if cell is md, with children, depending on folding state)

Currently there isn't a good icon choice to display outright, but when one is created, this will be displayed on hover as a primary action of the toolbar in the outline entry.

In the folded cell hint within your notebook editor, there is also now a play button that will execute cells in the folded range.
