### ISSUE TITLE
Visual Bug (Overlap text)

### ISSUE THREAD

**Issue by budiharyonoo** [microsoft/vscode#180275]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:
Version: 1.77.3
Commit: 704ed70d4fd1c6bd6342c436f1ede30d1cff4710
Date: 2023-04-12T09:16:52.732Z
Electron: 19.1.11
Chromium: 102.0.5005.196
Node.js: 16.14.2
V8: 10.2.154.26-electron.0
OS: Linux x64 6.1.8-200.fc37.x86_64
Sandboxed: No
- OS Version: Fedora 37 KDE

Steps to Reproduce:

1. When I open my vscode this visual bug happen, even if I close and re-open it again, the visual bug still exists.

![Screenshot_20230419_082921](https://user-images.githubusercontent.com/91255312/232943427-cb0dd841-7290-4b42-98d5-c24dafe1171c.png)

**Comment by deepak1556** [comment]
Merging to https://github.com/microsoft/vscode/issues/174721
