### ISSUE TITLE
[Accessibility]: Typing characters does not move focus in File Explorer View

### ISSUE THREAD

**Issue by jooyoungseo** [microsoft/vscode#180216]
CC @meganrogge

Let's say you two folders in the current workspace: `foo/` and `bar/`.

In File Explorer (Ctrl+Shift+E) View, typing "f" does not move focus to "foo/"

I cannot recall the exact version, but this was working previously and very convenient when locating a specific folder in a workspace.

**Comment by gjsjohnmurray** [comment]
Maybe also check your `workbench.list.typeNavigationMode` setting is `automatic`. A

**Comment by jooyoungseo** [comment]
@gjsjohnmurray -- Yes, my `workbench.list.typeNavigationMode` is set to "automatic" by default.
