### ISSUE TITLE
tasks.options.cwd has no effect

### ISSUE THREAD

**Issue by vadi2** [microsoft/vscode#180298]
Type: <b>Bug</b>

I customised my task and set the `cwd` value to a directory within my workspace:

"cwd": "${workspaceFolder}/questionnaires/gofsh",

However the task is still being run at the ${workspaceFolder}, and thus failing.

VS Code version: Code 1.77.3 (704ed70d4fd1c6bd6342c436f1ede30d1cff4710, 2023-04-12T09:16:52.732Z)
OS version: Linux x64 5.15.95-16520-g682786dc5340
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-10210U CPU @ 1.60GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|1, 1, 0|
|Memory (System)|6.44GB (1.75GB free)|
|Process Argv|--unity-launch --crash-reporter-id ce434e89-7e9e-48a9-a68c-97758ceade62|
|Screen Reader|no|
|VM|100%|
|DESKTOP_SESSION|undefined|
|XDG_CURRENT_DESKTOP|X-Generic|
|XDG_SESSION_DESKTOP|undefined|
|XDG_SESSION_TYPE|undefined|
</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
unique-lines|bib|1.0.0
path-intellisense|chr|2.8.4
markdown-table-prettify|dar|3.6.0
githistory|don|0.6.20
url-encode|fle|1.1.0
shell-format|fox|7.2.5
comment-translate|int|2.2.4
vscode-language-fsh|MIT|1.10.2
vscode-thunder-client|ran|2.6.2
cody-ai|sou|0.0.7
shellcheck|tim|0.32.4

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vstes627:30244334
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscoreces:30445986
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
nodejswelcome1cf:30587006
282f8724:30602487
pyind779:30671433
89544117:30613380
pythonsymbol12:30671437
showlangstatbar:30672706
vsccsb:30705552
vscodedisable:30660115
defaultazurewalk:30687958
pythonms35:30701012
pythonfmttext:30716742

```

</details>

**Comment by meganrogge** [comment]
I can reproduce - it looks like `includeCommandOptions` is `false` here. @alexr00 is that expected/as designed for tasks of type `shell`?

![Screenshot 2023-04-19 at 11 37 30 AM](https://user-images.githubusercontent.com/29464607/233169040-55dd9bc9-6964-45b7-bff1-a9d2d5dc85ef.png)

**Comment by alexr00** [comment]
I would expect cwd to work for shell.

**Comment by meganrogge** [comment]
This works for me

![Screenshot 2023-11-22 at 10 40 49 AM](https://github.com/microsoft/vscode/assets/29464607/c6a53aed-3eb0-4e21-b033-5b4be7ab322a)
