### ISSUE TITLE
Enter key behavior is unknowingly changed

### ISSUE THREAD

**Issue by herzaislad** [microsoft/vscode#180235]
Type: <b>Bug</b>

I just updated it on my macbook m1 pro 16" ventura 13.2.
The enter key behaviour is unknowingly changed!
Now I can't push characters down to new line with "enter" key!
And to move to new line I can't simply use "enter" key

VS Code version: Code 1.77.3 (704ed70d4fd1c6bd6342c436f1ede30d1cff4710, 2023-04-12T09:41:48.638Z)
OS version: Darwin arm64 22.3.0
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Max (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|2, 2, 2|
|Memory (System)|32.00GB (0.75GB free)|
|Process Argv|--crash-reporter-id d8488d98-a7a8-4364-9347-8f8fb42903d9|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (40)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|3.0.2
project-manager|ale|12.7.0
laravel-extra-intellisense|ami|0.6.3
laravel-blade-spacer|aus|2.1.3
vscode-intelephense-client|bme|1.9.5
gitignore|cod|0.9.0
laravel-goto-view|cod|1.3.8
laravel-goto-controller|ctf|0.5.2
vscode-eslint|dba|2.4.0
vscode-styled-components|die|0.1.33
git-extension-pack|don|0.1.3
githistory|don|0.6.20
gitlens|eam|13.5.0
prettier-vscode|esb|9.10.4
vscode-env|Iro|0.1.0
auto-comment-blocks|kev|1.0.1
vscode-JS-CSS-HTML-formatter|lon|0.2.3
json-to-ts|Mar|1.7.5
lintel|mfl|1.3.4
dotenv|mik|1.0.1
prettify-json|moh|0.0.3
laravel-blade|one|1.34.0
laravel5-snippets|one|1.17.0
material-icon-theme|PKi|4.26.0
laravel-intelephense|por|1.21.0
phpdoc-comment-vscode-plugin|rex|1.3.0
laravel-artisan|rya|0.0.28
vscode-blade-formatter|shu|0.20.14
vscode-fileutils|sle|3.10.1
php-ci|sma|0.4.2
addDocComments|ste|0.0.8
selectline-statusbar|tom|0.0.2
lorem-ipsum|Tyr|1.3.1
change-case|wma|1.0.0
php-debug|xde|1.32.1
php-pack|xde|1.0.3
markdown-all-in-one|yzh|3.5.1
json|Zai|2.0.2
commentbars|zfz|0.0.10
vscode-open-in-github|ziy|1.3.6

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
nodejswelcome1:30587005
282f8724:30602487
pyind779:30671433
f6dab269:30613381
vscrp:30673768
pythonsymbol12:30671437
functionswalk:30687959
pythonms35:30701012
pythonfmttext:30716742
pythonclientmv:30713943

```

</details>

**Comment by gjsjohnmurray** [comment]
Please use the Start Extension Bisect command to investigate whether the problem is being caused by one of your extensions.

**Comment by ArturoDent** [comment]
See https://github.com/microsoft/vscode/issues/178782#issuecomment-1492651359 probably the same issue since you are using the extension `vscode-styled-components`.  Possible solutions in that link.

**Comment by herzaislad** [comment]
> See [#178782 (comment)](https://github.com/microsoft/vscode/issues/178782#issuecomment-1492651359) probably the same issue since you are using the extension `vscode-styled-components`. Possible solutions in that link.

Tnkiu now it's solved!
