### ISSUE TITLE
Crashing randomly

### ISSUE THREAD

**Issue by siddharthd0** [microsoft/vscode#180258]
No clue what is happening, it keeps crashing randomly

Version: 1.77.3
Commit: 704ed70d4fd1c6bd6342c436f1ede30d1cff4710
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36 Edg/112.0.1722.48
Embedder: codespaces

**Comment by rzhao271** [comment]
Hi, can you send over a crash dump, following the instructions at https://github.com/microsoft/vscode/wiki/Native-Crash-Issues?
