### ISSUE TITLE
I can't run the app

### ISSUE THREAD

**Issue by Mhandyas86** [microsoft/vscode#180229]
Type: <b>Performance Issue</b>

APP\node_modules\babel-loader\lib\index.js:55:103 {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ], 
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v18.16.0
Please I need help

**Comment by roblourens** [comment]
It's not clear what's going on here, I don't think this error came from vscode. Please give more details

**Comment by Mhandyas86** [comment]
When I tried to run my APP, on terminal Visual studio I received this message "APP\node_modules\babel-loader\lib\index.js:55:103 {
opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
library: 'digital envelope routines',
reason: 'unsupported',
code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v18.16.0'' and on my browser I got a message "localhost refused to connect"
Thank you

**Comment by alexis-opolka** [comment]
@Mhandyas86 It seems to be related to webpack and not vscode.

Here are links talking about it and giving workarounds to solve this issue.

- [Webpack GitHub's issue](https://github.com/webpack/webpack/issues/15900)
- [stackoverflow question](https://stackoverflow.com/questions/74726224/opensslerrorstack-error03000086digital-envelope-routinesinitialization-e)

I hope it'll help you solve your issue.

**Comment by Mhandyas86** [comment]
Thank you
