### ISSUE TITLE
Terminal window loses characters when resized horizontally

### ISSUE THREAD

**Issue by varadero** [Microsoft/vscode#18027]
- VSCode Version: 1.7.2
- OS Version: Windows 7

Steps to Reproduce:

1. Open VSCode and maximize its window
2. Press CTRL+` to open a terminal - a standard text "Microsoft Windows [Version 6.1.7601] ... Copyright (c) 2009 Microsoft Corporation.  All rights reserved." is shown
3. Horizontally resize (shrink) VSCode window - make it small enough to hide part of the text in terminal
4. Expand/maximize VSCode window - some of the text in the terminal is now gone

Some screenshots are  attached.

Before shrinking:
![before-shrink](https://cloud.githubusercontent.com/assets/7610713/21602469/d633f806-d19c-11e6-8856-7017bdfc6ffc.jpg)

After shrinking:
![after-shrink](https://cloud.githubusercontent.com/assets/7610713/21602471/db17b362-d19c-11e6-9891-6bc3158cd56e.jpg)

After expanding (note how the text now says "All ri" only):
![after-expand](https://cloud.githubusercontent.com/assets/7610713/21602475/df957014-d19c-11e6-981e-537600ca123b.jpg)

Sometimes while shrinking VSCode window horizontally, the lines in terminal window are duplicated:
![after-shrink-multiple-lines](https://cloud.githubusercontent.com/assets/7610713/21602504/3b88d988-d19d-11e6-8601-4b7c63eaf456.jpg)

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/8336

This is being investigated upstream currently
