### ISSUE TITLE
Mismatch between preview pane and main pane when editing two Markdown files

### ISSUE THREAD

**Issue by zivcaspi** [Microsoft/vscode#18020]
- VSCode Version: Code 1.8.1 (ee428b0eead68bf0fb99ab5fdc4439be227b6281, 2016-12-19T14:49:23.350Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

|Extension|Author|Version|
|---|---|---|
|vscode-antlr4|mike-lischke|0.4.2|
|csharp|ms-vscode|1.5.3|
|PowerShell|ms-vscode|0.7.2|
|RustyCode|saviorisdead|0.19.1|

---

Steps to Reproduce:

1. Open two Markdown (.md) files
2. While editing each file, use CTRL-SHIFT P, Markdown: Open Preview to the Side
3. Note that when switching between the two files on the left ("main") pane, the right ("preview") pane is not switched to reflect a preview of the file being edited

**Comment by mjbvz** [comment]
This is by design. The markdown preview is currently tied to a specific document.

We could explore adding a setting to change this behavior if there is enough interest

**Comment by zivcaspi** [comment]
I’m not sure I understand – I have two open documents and when I switch between them the preview doesn’t switch accordingly. How is that a useful experience? It essentially forces me to open three panes (one for the document being edited + the document that I’m comparing myself to, one for the preview of the document I’m editing, and one for the preview of the document that I’m comparing myself to).

**Comment by mjbvz** [comment]
@zivcaspi Yes, this is how it is designed currently. Each text document has it's own markdown preview. 

If you would like to see different behavior, with multiple markdown editors mapping to a single preview, please file a feature request so that we can gauge interest in this.

Thanks

**Comment by zivcaspi** [comment]
Sure, thanks.
