### ISSUE TITLE
ChromeOS typing cursor is offset from text

### ISSUE THREAD

**Issue by NottPeak** [microsoft/vscode#180223]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: VSCode for the web 1.77.3
- OS Version: ChromeOS 111.0.5563.118 (Official Build) (64-bit)

Steps to Reproduce:

1. Randomly happens only on specific lines of code, and nowhere else
2. Same thing as issue [78058](https://github.com/microsoft/vscode/issues/78058) (Making a new issue due to it being old and closed but not yet fixed)
3. This randomly occurs, but the cursor will be in the wrong position making it difficult to work 
4. I have almost all defualt settings, and the only plugin I am using is a plugin pack (Still occurs when it is disabled)

**Comment by alexdima** [comment]
Let's track in https://github.com/microsoft/vscode/issues/160702 . Please let me know if you know of any way to reproduce this in a VM.

**Comment by NottPeak** [comment]
> Let's track in #160702 . Please let me know if you know of any way to reproduce this in a VM.

Ok, sorry I missed that other one, I am unsure on any methods to reproduce in a vm, but I can try testing it out. ATM it seems to only happen in normal ChromeOS on a Chromebook, but it may be able to be replicated elsewhere
