### ISSUE TITLE
How to perform telemetry for extensions

### ISSUE THREAD

**Issue by shanalikhan** [Microsoft/vscode#18035]
I want to get a report of currently users online or used my extension recently, filtering them by locations and other many things.
is there any way to do that ?

**Comment by formulahendry** [comment]
You may try Application Insight to track your custom event: https://github.com/formulahendry/vscode-extension-leaderboard/blob/master/src/appInsightsClient.ts. 😄 
![image](https://cloud.githubusercontent.com/assets/1050213/21607665/a693c15c-d1f2-11e6-9186-d827a1580e62.png)

I am also curious how VS Code team get the telemetry data. 🤔

**Comment by shanalikhan** [comment]
> You may try Application Insight

I\m looking for free service rather then paying on azure.
Are there any free ones

**Comment by eamodio** [comment]
I would like something like this as well, but am less concerned with active users though (it could be nice) and more concerned with seeing how people are using my extension. Like the which settings they have set for my extensions (don't want all settings, just mine), which commands they run (again only the ones contributed by my extension), etc. All of this could be completely anonymized as I don't have any interest in the individual, just trying to figure out which features are used, which may be deprecated and removed, etc.

**Comment by seanmcbreen** [comment]
Hi,

The best bet today is to use App Isights (this is what we use internally) this will allow you to measure active use, scenario/feature use etc.  There is a free tier of App Insights and Node support that could suffice depending on volume.  

If you exceed the volume they just start dropping events (and you can sample events if you want to reduce volume.

> **App Insights Pricing:** With Basic, you pay based on the volume of telemetry your application sends, with a 1 GB free allowance per month.

Some links:
* https://azure.microsoft.com/en-us/pricing/details/application-insights/
* https://docs.microsoft.com/en-us/azure/application-insights/app-insights-nodejs

Finally two last thoughts:

1. Our marketplace team is looking at providing some support in the manage portal that will provide a little more detail on installs etc - but thats a while off.
2. It's important to do the right thing with telemetry for instance ideally observe the VS Code setting for not sending any telemetry `telemetry.enableTelemetry` and focus only on what you need to make your extension better.

Sean

p.s. People love setting-sync, auto-close-* and Git Lens - thank you for your contributions!

**Comment by eamodio** [comment]
@seanmcbreen is there any guidance on how to protect the application-insights key in an extension?

**Comment by shanalikhan** [comment]
> Our marketplace team is looking at providing some support in the manage portal that will provide a little more detail on installs etc

I would love to use this feature from manage page.

@seanmcbreen for Azure, they ask credit card information which i dont want to provide, i know they wont charge anything.
Do you know any other tool that does provide functionality like application-insights and is some what free ?
