### ISSUE TITLE
When I presss "reload", an unnecessary confirm dialog appears

### ISSUE THREAD

**Issue by PunchyRascal** [Microsoft/vscode#18039]
After installing an extension and pressing "reload", a confirm dialog appears.

Say I am trying to find a theme, where I can actually read the tab labels (most are dark grey on slightly darker background and there is no theme customization) and need to try tens of themes, each time going through this reload-confirm-uninstall routine.

I move to remove the dialog, as is doesn't seem to serve any purpose. (regardless of my specific use case)

- VSCode Version: Code 1.8.1 (ee428b0eead68bf0fb99ab5fdc4439be227b6281, 2016-12-19T14:49:23.350Z)
- OS Version: Windows_NT ia32 10.0.14393

**Comment by sandy081** [comment]
Marking this as a dup as it is listed in UX improvement item #18354
