### ISSUE TITLE
Allow to programatically remove selection in TreeView

### ISSUE THREAD

**Issue by DaveWasTakn** [microsoft/vscode#180394]
Items in the TreeView can be selected using the `reveal` method, but there is no way, that I am aware of, to programmatically clear the selection.

Something similar was already requested in issue #48754 (which was stalled for almost 3 years and then disregarded)

This would currently be needed when wanting to handle the event of a user *clicking* an item in the TreeView, which is currently only possible using the `TreeView.onDidChangeSelection()` event. **BUT** this is does **NOT** handle every click on a TreeView item, since it remains selected after the first click and therefore it wont fire on consecutive clicks.

**Comment by alexr00** [comment]
> This would currently be needed when wanting to handle the event of a user clicking an item in the TreeView,

@DaveWasTakn can you walk me through why the `TreeItem` `command` doesn't work for this?

**Comment by DaveWasTakn** [comment]
Hello, 
you are correct! I should have described what I am trying to achieve:
I want to handle consecutive clicks on a TreeItem and update the selection depending on a few factors, like where the user is at currently. For example, I want to handle and deselect an item when clicking it while it is selected (i.e. **deselect** when clicking an item the second time).
