### ISSUE TITLE
Enable the use of custom functions in the the debugger's watch window

### ISSUE THREAD

**Issue by dmentock** [microsoft/vscode#180311]
When working on c++ applications, it's often the case that you have objects which cannot be fully examined by just looking at the debugger. One example are `Eigen::Tensor` objects:
![image](https://user-images.githubusercontent.com/92803460/233044752-d730e433-1394-4478-9c5e-23c20eceb703.png)
Where currently the only option to view the actual values is to add a temporary print statement to your program. One idea could be to write a debug function in a custom header, e.g.:

```
#include <unsupported/Eigen/CXX11/Tensor>

template <typename T, int num_indices>
std::string eigen_tensor_to_string(const Eigen::Tensor<T, num_indices>& tensor) {
    std::stringstream ss;
    Eigen::array<Eigen::DenseIndex, num_indices> indices;
    indices.fill(0);

    for (int i = 0; i < tensor.size(); ++i) {
        ss << "Index: (";
        for (int j = 0; j < num_indices; ++j) {
            ss << indices[j] << (j == num_indices - 1 ? "" : ", ");
        }
        ss << ")\tValue: " << tensor(indices) << std::endl;

        // Increment indices
        for (int j = num_indices - 1; j >= 0; --j) {
            if (++indices[j] < tensor.dimension(j)) {
                break;
            }
            indices[j] = 0;
        }
    }
    return ss.str();
}
```

And then entering the expression

`eigen_tensor_to_string(u_tilde_p_padded)`

in the watch window to view the values. I realized then that this is  not possible because custom functions are not accessible from this window, but I believe that it would be a useful feature in many cases where the datastructure of an object doesn't allow for direct examination of the variables in the debgger.

**Comment by roblourens** [comment]
I think this is a request for the c++ debug extension, please file it on that repo, thanks

**Comment by dmentock** [comment]
@roblourens could you maybe link the repo? I wasn't able to find it
