### ISSUE TITLE
TypeScript IntelliSense is not working in VS Code

### ISSUE THREAD

**Issue by Veer0x1** [microsoft/vscode#180384]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.77.3
- OS Version: macOS 13.3.1

Description:
 I created a Next.js 13 project with a typescript, but its not showing any error when I made any type error, neither it show the red wiggly line; below are my vs code typescript setting and tsconfig file

<img width="1552" alt="Screenshot 2023-04-20 at 11 22 56 AM" src="https://user-images.githubusercontent.com/96714915/233271480-eac2f15d-2cff-42a1-9654-5a85480d8b0e.png">
<img width="1552" alt="Screenshot 2023-04-20 at 11 32 13 AM" src="https://user-images.githubusercontent.com/96714915/233272042-fc72f28d-8c56-493f-8ab2-50fd30afd0f6.png">

**Comment by gjsjohnmurray** [comment]
Did you try running the Start Extension Bisect command to investigate whether the problem is being caused by one of your extensions?

**Comment by mjbvz** [comment]
Did you disable the built-in typescript extension? Search `@builtin typescript` in the extensions view to check

**Comment by Veer0x1** [comment]
Thank you, the builtin typescript extension was disabled; now that I enabled it, everything is working fine
<img width="1381" alt="Screenshot 2023-04-21 at 3 44 15 AM" src="https://user-images.githubusercontent.com/96714915/233498752-ae680715-5d4a-4af2-adf7-ea219c3a982b.png">
