### ISSUE TITLE
Profile tries to install a pre-release version of an extension in VS Code Stable

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#180318]
1.  Click on https://vscode.dev/profile/github/15acae9d6a5d9d6431752f36a3afd596
2. Open VS Code
3. Get the following error

I would expect that we are not trying to install a pre-release version of an extension since we are applying the Profile for VS Code Stable.

![Screenshot 2023-04-19 at 14 46 03](https://user-images.githubusercontent.com/1926584/233079117-905704c6-249d-47b8-8aa3-1abef07b6a3c.png)

**Comment by sandy081** [comment]
It is because the profile says to install pre-release version of jupyter extension. I would recommend to reexport the profile including release version of the extension and not the pre-release.
