### ISSUE TITLE
Add pretty Typescript error messages

### ISSUE THREAD

**Issue by sebastianvitterso** [microsoft/vscode#180389]
The https://github.com/yoavbls/pretty-ts-errors repo contains a vscode extension that improve error messages for typescript errors. Now it seems obvious that this kind of functionality should be part of the built-in vscode TS language server, as it is so much easier to read than the current error messages (which often come in the form of a huge wall of text). 

Example images from extension page:
<p><img src="https://github.com/yoavbls/pretty-ts-errors/raw/HEAD/assets/this.png" style="max-height:350px;" height="350px">&nbsp; &nbsp; <img src="https://github.com/yoavbls/pretty-ts-errors/raw/HEAD/assets/instead-of-that.png" height="350px" width="350px" style="max-height:350px;"></p>

**Comment by sandy081** [comment]
@mjbvz Is not this a dup of https://github.com/microsoft/vscode/issues/54272

**Comment by mjbvz** [comment]
Yes let's close it in favor of https://github.com/microsoft/vscode/issues/54272
