### ISSUE TITLE
Cannot stay signed in multiple VSCode windows at the same time - Copilot message: "Sign in to use GitHub Copilot"

### ISSUE THREAD

**Issue by Rigel772** [microsoft/vscode#180381]
Does this issue occur when all extensions are disabled?: Yes

Version: 1.77.3
Commit: 704ed70d4fd1c6bd6342c436f1ede30d1cff4710
Date: 2023-04-12T09:16:52.732Z
Electron: 19.1.11
Chromium: 102.0.5005.196
Node.js: 16.14.2
V8: 10.2.154.26-electron.0
OS: Linux x64 6.2.10-1-MANJARO
Sandboxed: No

Steps to Reproduce:

1. Open two windows of VSCode
2. When you sign in in one window the other shows Copilot message: Sign in to use GitHub Copilot.
3. When you sign in the other window shows same message.

**Comment by TylerLeonhardt** [comment]
Can you follow these steps so that we can get more information on what's going on?

* Trigger the sign in
* _Wait for the issue to happen..._
* Open the Output pane (ctrl+shift+u)
* drop in this issue he contents of the following:
  * `GitHub Authentication` Output channel

**Comment by Rigel772** [comment]
Tested on a laptop and all was good, so came back to my desctop and all in all it was issue with my manjaro system.
`sudo pacman -S gnome-keyring libsecret libgnome-keyring` sorted the problem.
Thank you.
