### ISSUE TITLE
Cannot remove breakpoint in 2-lane gutter by clicking on it

### ISSUE THREAD

**Issue by gjsjohnmurray** [microsoft/vscode#180395]
Type: <b>Bug</b>

Testing #180013, I added a [Bookmarks](https://marketplace.visualstudio.com/items?itemName=alefragnani.Bookmarks) extension, set a bookmark on a line, then used the gutter context menu to set a breakpoint there too. As expected, a second lane got created in the gutter and the breakboint displayed there. But I was surprised not to be able to remove the breakpoint by simply clicking on it. Instead I had to use the context menu again.

VS Code version: Code - Insiders 1.78.0-insider (208bbb0d788cce3eb80799e3565ee2204391b86d, 2023-04-20T05:20:21.925Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: Yes

**Comment by joyceerhl** [comment]
This is https://github.com/microsoft/vscode/issues/114776--we don't yet support scoping clicks to decorations, and we will do so by introducing some notion of a glyph widget.

**Comment by roblourens** [comment]
Oh bummer... it's a bit worse now that the breakpoint appears separately, maybe we can prioritize #179725

**Comment by joyceerhl** [comment]
Working on it :)

**Comment by roblourens** [comment]
Oh, yes you are... I didn't really look at that issue and thought it was one of the older ones like #114776
