### ISSUE TITLE
Feature Request: Make API to open a new window of VSCode

### ISSUE THREAD

**Issue by KalitaAlexey** [Microsoft/vscode#18034]
Hi everybody.

I haven't found a feature like mine so I am opening it.

# Description

I need a possibility to open a new window from my code.

I would like to have a method like this:

```typescript
export namespace vscode {
    /**
     * Opens a new window using the specified path as a target.
     * @param path An entry located at the path is opened in the new window. If it is undefined the new window is opened without target
     */
    export function createWindow(path: string | undefined): void;
}
```

And use it like this:
```typescript
const newWindowWithFile = vscode.createWindow('/etc/passwd');
const newWindowWithDirectory = vscode.createWindow('/mnt');
const newWindow = vscode.createWindow();
```

# Unresolved Questions

Should the method return `Promise` to schedule actions after a new window is opened?

Should the method return `Promise` to return an error if a new window isn't opened?

Regards,
Alexey

**Comment by bpasero** [comment]
You can use the `vscode.openFolder` command without providing a path to open and setting the second parameter `forceNewWindow` to true.

**Comment by KalitaAlexey** [comment]
@bpasero,
I don't see the method.

**Comment by bpasero** [comment]
@KalitaAlexey https://code.visualstudio.com/docs/extensionAPI/vscode-api-commands

**Comment by KalitaAlexey** [comment]
@bpasero,
Thanks.
