### ISSUE TITLE
VS Code 1.77.3 Slow Startup on Win11

### ISSUE THREAD

**Issue by manuel-barreiro** [microsoft/vscode#180325]
##When I run it through the terminal with the comand "start 'Visual Studio Code' --disable-gpu" it starts really fast (start => app.isReady = 52).

##Cached data attached

## System Info

* Code: 1.77.3 (704ed70d4fd1c6bd6342c436f1ede30d1cff4710)
* OS: win32(10.0.22621)
* CPUs: 11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz(8 x 2419)
* Memory(System): 7.71 GB(2.46GB free)
* Memory(Process): 2
[prof-8HvvBxpO.renderer.cpuprofile.txt](https://github.com/microsoft/vscode/files/11273723/prof-8HvvBxpO.renderer.cpuprofile.txt)
[prof-8HvvBxpO.main.cpuprofile.txt](https://github.com/microsoft/vscode/files/11273724/prof-8HvvBxpO.main.cpuprofile.txt)
08.35 MB working set(148.80MB private, 18.62MB shared)
* VM(likelihood): 0%
* Initial Startup: true
* Has 0 other windows
* Screen Reader Active: false
* Empty Workspace: true

## Performance Marks

| What                                                            | Duration | Process                   | Info                                                       |
| --------------------------------------------------------------- | -------- | ------------------------- | ---------------------------------------------------------- |
| start => app.isReady                                            | 3823     | [main]                    | initial startup: true                                      |
| nls:start => nls:end                                            | 0        | [main]                    | initial startup: true                                      |
| require(main.bundle.js)                                         | 60       | [main]                    | initial startup: true                                      |
| start crash reporter                                            | 3792     | [main]                    | initial startup: true                                      |
| serve main IPC handle                                           | 2        | [main]                    | initial startup: true                                      |
| create window                                                   | 23       | [main]                    | initial startup: true, state: 0ms, widget: 9ms, show: 13ms |
| app.isReady => window.loadUrl()                                 | 109      | [main]                    | initial startup: true                                      |
| window.loadUrl() => begin to require(workbench.desktop.main.js) | 11328    | [main->renderer]          | NewWindow                                                  |
| require(workbench.desktop.main.js)                              | 189      | [renderer]                | cached data: YES, node_modules took 0ms                    |
| wait for window config                                          | 0        | [renderer]                | -                                                          |
| init storage (global & workspace)                               | 17       | [renderer]                | -                                                          |
| init workspace service                                          | 17       | [renderer]                | -                                                          |
| register extensions & spawn extension host                      | 130      | [renderer]                | -                                                          |
| restore viewlet                                                 | 38       | [renderer]                | workbench.view.explorer                                    |
| restore panel                                                   | 30       | [renderer]                | workbench.panel.markers                                    |
| restore & resolve visible editors                               | 74       | [renderer]                | 1: PerfviewInput                                           |
| overall workbench load                                          | 239      | [renderer]                | -                                                          |
| workbench ready                                                 | 15713    | [main->renderer]          | -                                                          |
| renderer ready                                                  | 460      | [renderer]                | -                                                          |
| shared process connection ready                                 | 0        | [renderer->sharedprocess] | -                                                          |
| extensions registered                                           | 15880    | [renderer]                | -                                                          |

## Raw Perf Marks: main

```
Name	Timestamp	Delta	Total
code/timeOrigin	1681911749328.622	0	0
code/didStartMain	1681911749387	58.3779296875	58.3779296875
code/willStartCrashReporter	1681911749397	10	68.3779296875
code/didStartCrashReporter	1681911753189	3792	3860.3779296875
code/willGenerateNls	1681911753190	1	3861.3779296875
code/mainAppReady	1681911753210	20	3881.3779296875
code/willLoadMainBundle	1681911753214	4	3885.3779296875
code/fork/willLoadCode	1681911753224	10	3895.3779296875
code/registerFilesystem/file	1681911753268	44	3939.3779296875
code/didLoadMainBundle	1681911753274	6	3945.3779296875
code/willStartMainServer	1681911753279	5	3950.3779296875
code/didStartMainServer	1681911753281	2	3952.3779296875
code/willCreateCodeWindow	1681911753294	13	3965.3779296875
code/willRestoreCodeWindowState	1681911753294	0	3965.3779296875
code/didRestoreCodeWindowState	1681911753294	0	3965.3779296875
code/willCreateCodeBrowserWindow	1681911753295	1	3966.3779296875
code/didCreateCodeBrowserWindow	1681911753304	9	3975.3779296875
code/willMaximizeCodeWindow	1681911753304	0	3975.3779296875
code/didMaximizeCodeWindow	1681911753317	13	3988.3779296875
code/didCreateCodeWindow	1681911753317	0	3988.3779296875
code/willOpenNewWindow	1681911753319	2	3990.3779296875
```
## Raw Perf Marks: renderer

```
Name	Timestamp	Delta	Total
code/timeOrigin	1681911753322	0	0
code/didStartRenderer	1681911764640	11318	11318
code/willWaitForWindowConfig	1681911764640	0	11318
code/didWaitForWindowConfig	1681911764640	0	11318
code/willShowPartsSplash	1681911764640	0	11318
code/didShowPartsSplash	1681911764641	1	11319
code/willLoadWorkbenchMain	1681911764647	6	11325
code/didLoadWorkbenchMain	1681911764836	189	11514
code/registerFilesystem/file	1681911764840	4	11518
code/registerFilesystem/vscode-userdata	1681911764840	0	11518
code/willInitWorkspaceService	1681911764841	1	11519
code/willInitStorage	1681911764842	1	11520
code/willInitUserConfiguration	1681911764854	12	11532
code/didInitUserConfiguration	1681911764857	3	11535
code/willInitWorkspaceConfiguration	1681911764857	0	11535
code/didInitWorkspaceConfiguration	1681911764858	1	11536
code/didInitWorkspaceService	1681911764858	0	11536
code/didInitStorage	1681911764859	1	11537
code/willStartWorkbench	1681911764861	2	11539
code/LifecyclePhase/Ready	1681911764863	2	11541
code/willCreateWorkbenchContributions/1	1681911764904	41	11582
code/didCreateWorkbenchContributions/1	1681911764925	21	11603
code/willCreateWorkbenchContributions/2	1681911764925	0	11603
code/registerFilesystem/trustedDomains	1681911764927	2	11605
code/registerFilesystem/vscode-interactive	1681911764928	1	11606
code/registerFilesystem/vscode-local-history	1681911764930	2	11608
code/didCreateWorkbenchContributions/2	1681911764932	2	11610
code/willCreatePart/workbench.parts.titlebar	1681911764934	2	11612
code/didRemovePartsSplash	1681911764939	5	11617
code/didCreatePart/workbench.parts.titlebar	1681911764952	13	11630
code/willCreatePart/workbench.parts.banner	1681911764952	0	11630
code/didCreatePart/workbench.parts.banner	1681911764952	0	11630
code/willCreatePart/workbench.parts.activitybar	1681911764952	0	11630
code/didCreatePart/workbench.parts.activitybar	1681911764955	3	11633
code/willCreatePart/workbench.parts.sidebar	1681911764955	0	11633
code/didCreatePart/workbench.parts.sidebar	1681911764956	1	11634
code/willCreatePart/workbench.parts.editor	1681911764956	0	11634
code/didCreatePart/workbench.parts.editor	1681911764981	25	11659
code/willCreatePart/workbench.parts.panel	1681911764981	0	11659
code/didCreatePart/workbench.parts.panel	1681911764981	0	11659
code/willCreatePart/workbench.parts.auxiliarybar	1681911764981	0	11659
code/didCreatePart/workbench.parts.auxiliarybar	1681911764982	1	11660
code/willCreatePart/workbench.parts.statusbar	1681911764982	0	11660
code/didCreatePart/workbench.parts.statusbar	1681911764983	1	11661
code/willRestoreEditors	1681911765026	43	11704
code/restoreEditors/editorGroupsReady	1681911765030	4	11708
code/willRestoreViewlet	1681911765030	0	11708
code/willRestorePanel	1681911765038	8	11716
code/restoreEditors/editorsToOpenResolved	1681911765068	30	11746
code/didRestoreViewlet	1681911765068	0	11746
code/didRestorePanel	1681911765068	0	11746
code/willRegisterExplorerViews	1681911765069	1	11747
code/didRegisterExplorerViews	1681911765075	6	11753
code/restoreEditors/editorGroupsRestored	1681911765100	25	11778
code/didRestoreEditors	1681911765100	0	11778
code/didStartWorkbench	1681911765100	0	11778
code/LifecyclePhase/Restored	1681911765101	1	11779
code/willCreateWorkbenchContributions/3	1681911765101	0	11779
code/willConnectSharedProcess	1681911765101	0	11779
code/willLoadExtensions	1681911765137	36	11815
code/willHandleExtensionPoints	1681911765218	81	11896
code/willHandleExtensionPoint/configurationDefaults	1681911765218	0	11896
code/didHandleExtensionPoint/configurationDefaults	1681911765219	1	11897
code/willHandleExtensionPoint/configuration	1681911765219	0	11897
code/didHandleExtensionPoint/configuration	1681911765230	11	11908
code/willHandleExtensionPoint/jsonValidation	1681911765230	0	11908
code/didHandleExtensionPoint/jsonValidation	1681911765230	0	11908
code/willHandleExtensionPoint/debuggers	1681911765230	0	11908
code/didHandleExtensionPoint/debuggers	1681911765233	3	11911
code/willHandleExtensionPoint/breakpoints	1681911765233	0	11911
code/didHandleExtensionPoint/breakpoints	1681911765233	0	11911
code/willHandleExtensionPoint/notebooks	1681911765233	0	11911
code/didHandleExtensionPoint/notebooks	1681911765233	0	11911
code/willHandleExtensionPoint/notebookRenderer	1681911765233	0	11911
code/didHandleExtensionPoint/notebookRenderer	1681911765234	1	11912
code/willHandleExtensionPoint/problemPatterns	1681911765234	0	11912
code/didHandleExtensionPoint/problemPatterns	1681911765234	0	11912
code/willHandleExtensionPoint/problemMatchers	1681911765234	0	11912
code/didHandleExtensionPoint/problemMatchers	1681911765235	1	11913
code/willHandleExtensionPoint/taskDefinitions	1681911765235	0	11913
code/didHandleExtensionPoint/taskDefinitions	1681911765236	1	11914
code/willHandleExtensionPoint/terminal	1681911765236	0	11914
code/didHandleExtensionPoint/terminal	1681911765236	0	11914
code/willHandleExtensionPoint/terminalQuickFixes	1681911765236	0	11914
code/didHandleExtensionPoint/terminalQuickFixes	1681911765236	0	11914
code/willHandleExtensionPoint/walkthroughs	1681911765236	0	11914
code/didHandleExtensionPoint/walkthroughs	1681911765236	0	11914
code/willHandleExtensionPoint/commands	1681911765236	0	11914
code/didHandleExtensionPoint/commands	1681911765237	1	11915
code/willHandleExtensionPoint/menus	1681911765237	0	11915
code/didHandleExtensionPoint/menus	1681911765240	3	11918
code/willHandleExtensionPoint/languages	1681911765240	0	11918
code/didHandleExtensionPoint/languages	1681911765247	7	11925
code/willHandleExtensionPoint/customEditors	1681911765247	0	11925
code/didHandleExtensionPoint/customEditors	1681911765247	0	11925
code/willHandleExtensionPoint/codeActions	1681911765247	0	11925
code/didHandleExtensionPoint/codeActions	1681911765247	0	11925
code/willHandleExtensionPoint/viewsWelcome	1681911765247	0	11925
code/didHandleExtensionPoint/viewsWelcome	1681911765247	0	11925
code/willHandleExtensionPoint/grammars	1681911765247	0	11925
code/didHandleExtensionPoint/grammars	1681911765251	4	11929
code/willHandleExtensionPoint/semanticTokenScopes	1681911765251	0	11929
code/didHandleExtensionPoint/semanticTokenScopes	1681911765251	0	11929
code/willHandleExtensionPoint/snippets	1681911765251	0	11929
code/didHandleExtensionPoint/snippets	1681911765251	0	11929
code/willHandleExtensionPoint/keybindings	1681911765251	0	11929
code/didHandleExtensionPoint/keybindings	1681911765256	5	11934
code/willHandleExtensionPoint/themes	1681911765256	0	11934
code/didHandleExtensionPoint/themes	1681911765257	1	11935
code/willHandleExtensionPoint/iconThemes	1681911765257	0	11935
code/didHandleExtensionPoint/iconThemes	1681911765257	0	11935
code/willHandleExtensionPoint/continueEditSession	1681911765257	0	11935
code/didHandleExtensionPoint/continueEditSession	1681911765257	0	11935
code/willHandleExtensionPoint/viewsContainers	1681911765257	0	11935
code/didHandleExtensionPoint/viewsContainers	1681911765261	4	11939
code/willHandleExtensionPoint/views	1681911765261	0	11939
code/didHandleExtensionPoint/views	1681911765263	2	11941
code/didHandleExtensionPoints	1681911765263	0	11941
code/didLoadExtensions	1681911765267	4	11945
```

### cached data created (lazy, might need refreshes)
-`prof-8HvvBxpO.main.cpuprofile.txt`
-`prof-8HvvBxpO.renderer.cpuprofile.txt`

**Comment by bpasero** [comment]
Can you see if it still reproduces when disabling the GPU support in VSCode? You can do that by running VSCode from the command line like this: `code --disable-gpu`

If that helps, you can permanently configure this option via:
* Command Palette search for "Configure Runtime Arguments"
* Set `disable-hardware-acceleration: true`
* Restart

**Comment by enesbala5** [comment]
I am also facing a lot of lag on 1.77.3 for some reason. Trying your solution now, but it feels hacky. I'm not sure if I can say it's fixed yet.

**Comment by manuel-barreiro** [comment]
@bpasero I tried with `code --disable-gpu` but it also starts lagged...

 I run it through the Windows Powershell with the comand "start 'Visual Studio Code' --disable-gpu" it starts really fast (start => app.isReady = 52). Do you know how can I configure to start VS Code always that way?
 
 Thanks a lot!

**Comment by manuel-barreiro** [comment]
@bpasero could you please help me solve this issue please?

Thanks a lot

**Comment by bpasero** [comment]
If VS Code runs fast using Powershell but not using command prompt, this sounds like a configuration problem on your machine and nothing VS Code can solve. 

Do you have any AntVirus software installed that maybe checks VS Code and make it start slower?

**Comment by manuel-barreiro** [comment]
I had McAfee Antivirus installed. I uninstalled it, rebooted my machine and now VS Code starts up perfectly fast.

Thak you very much, you were really helpful! @bpasero 

Greetings from Argentina
