### ISSUE TITLE
Explorer twistie spacing and issues

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#18031]
- VSCode Version: Code - Insiders 1.9.0-insider (d384271ffb5655cee1ddf8f93f51cd892ee2cc40, 2017-01-03T07:05:16.958Z)
- OS Version: Darwin x64 16.1.0

---

The changes to the explorer to make it work when our Seti icon theme is enabled have some serious drawbacks. When not using icons, the spacing from twistie to label is now looking broken:

![image](https://cloud.githubusercontent.com/assets/900690/21603994/1464e064-d1a1-11e6-8566-00809db17b9d.png)

Also, the rename box is no longer filling the full width:

![image](https://cloud.githubusercontent.com/assets/900690/21604004/21b4f8f8-d1a1-11e6-9ffb-5ee522ca53e2.png)

The changes to make it work with Seti icon theme should only be applied when an icon theme is active.

Finally, I am no longer seeing a "..." when the label overflows:

![image](https://cloud.githubusercontent.com/assets/900690/21748902/4b3f7916-d591-11e6-9d26-3c41b0807022.png)

**Comment by aeschli** [comment]
The difference is that the twistie now takes 22px instead of 16px. Is that so bad?

**Comment by bpasero** [comment]
Yes, compared to the spacing any other application is using:

![image](https://cloud.githubusercontent.com/assets/900690/21633463/bdeaa5e8-d24f-11e6-9ba2-5933d675f7ed.png)

**Comment by bpasero** [comment]
Another regression: when the explorer is narrow, no longer is a "..." drawn for the overflowing label:

![image](https://cloud.githubusercontent.com/assets/900690/21748906/5b1d8634-d591-11e6-8b61-38ce08f745b0.png)

@aeschli all these CSS changes in the explorer have quite a negative impact, can we not just add an invisible icon in our theme for the case where we have no icon for the folder? It seems all this was done to fix the issue with indenting files and folders properly, so let's just add an invisible folder icon?
