### ISSUE TITLE
supprt api set codelens placeholder

### ISSUE THREAD

**Issue by tjx666** [microsoft/vscode#180353]
For now, when resolveCodeLens costs long time, here will show empty:

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/41773861/233172808-e0b44b12-eca5-44e3-b134-7770c834ee0d.png">

Usage:

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/41773861/233173168-78993b57-cf70-487e-9178-109b5194949f.png">

**Comment by jrieken** [comment]
@tjx666 not sure what you are asking for. Are you the author or a consumer of the extension?

**Comment by tjx666** [comment]
I'm extension author, because the resolveCodeLens cost long time, it would be great to display the placeholder before codeLens reaolved

**Comment by jrieken** [comment]
You can already do that via `onDidChangeCodeLenses` event. Just use a placeholder for the command and emit the event once the data has arrived.
