### ISSUE TITLE
Crash in linux smoke tests

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#180478]
Found a crash dump attached to the smoke test: https://dev.azure.com/vscode/VSCode/_build/results?buildId=91614&view=results

Dump: 
[crash-dump-linux-x64-smoke-1.zip](https://github.com/microsoft/vscode/files/11293034/crash-dump-linux-x64-smoke-1.zip)

**Comment by rzhao271** [comment]
Symbolicated file: 
[symbolicated-87.log](https://github.com/microsoft/vscode/files/11299200/symbolicated-87.log)

**Comment by deepak1556** [comment]
Merging to https://github.com/microsoft/vscode-internalbacklog/issues/3454
