### ISSUE TITLE
Accessibility buffer keystroke incorrectly gets sent to terminal

### ISSUE THREAD

**Issue by dennischenfeng** [microsoft/vscode#180454]
Type: <b>Bug</b>
Does this issue occur when all extensions are disabled?: Yes
Notes: using NVDA screen reader on Windows 11.

1. Go to terminal (ctrl+`). I've tried and have seen the issue on both Command Prompt and Git Bash terminal.

2. Go to accessibility buffer using shift+tab. Then, return to terminal prompt by pressing tab or esc. 

3. The shift-tab keystroke was sent to the terminal which usually invokes some command (depending on terminal). 
For example, on Command Prompt, a shift+tab autocompletes an item name in the current directory, so my terminal prompt at this point shows one of my folder names. I can visually verify this and can also verify this by going into the buffer again and reading it.
As another example, if the terminal buffer was instead Git Bash, it seems like a tab keystroke was sent to ther terminal, which (after you wait 1-2 seconds) it shows "Display all ___ possibilities? (y or n)". Idk why in this case it send tab instead of shift+tab, but in any case it's still unexpected behavior and can be disruptive.

VS Code version: Code - Insiders 1.78.0-insider (208bbb0d788cce3eb80799e3565ee2204391b86d, 2023-04-20T05:20:21.925Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|12th Gen Intel(R) Core(TM) i7-1250U (12 x 1882)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.63GB (6.10GB free)|
|Process Argv|--crash-reporter-id 1afd7eee-9792-4ab8-bea6-a54e65310e3c|
|Screen Reader|yes|
|VM|0%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
remote-wsl|ms-|0.78.3
indent-nav|Ton|1.0.3
markdown-all-in-one|yzh|3.5.1

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256197
vstes627:30244334
vslsvsres303:30308271
pythontb:30258533
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscod805:30301674
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30404738
cppdebug:30492333
vsclangdf:30492506
c4g48928:30535728
dsvsc012:30540252
pynewext54:30618038
pylantcb52:30590116
nodejswelcome1:30587009
pyind779:30611226
vscrp:30624060
pythonsymbol12:30651887
2i9eh265:30646982
6233i204:30659907
defaultazurewalk:30687958
pythonms35:30671666
f08j5886:30680471
7ij38806:30687742
pythonfmttext:30716741
pythonclientmv:30700173
showcppwkth:30715168

```

</details>

**Comment by meganrogge** [comment]
This is by design but you can change that by altering the keybinding for focus accessible buffer
