### ISSUE TITLE
Test: standalone color picker:   in a json file: no color decorator, or it disappears

### ISSUE THREAD

**Issue by ArturoDent** [microsoft/vscode#180433]
Testing https://github.com/microsoft/vscode/issues/180678

@aiday-mar 

Steps to Reproduce:

1. Enable the setting `Editor: Default Color Decorators`
2. Open a json file with a css-formatted value.
3. Observe that there is no color decorator shown.
4. Reload vscode with the json file in focus: color decorator briefly appears but then disappears with no file interaction.

![colorDecorationJSONbug](https://user-images.githubusercontent.com/31813701/233455850-1a616ff7-8ae4-4146-8e71-38b8c8ef1a65.gif)

Version: 1.78.0-insider
Commit: 208bbb0d788cce3eb80799e3565ee2204391b86d
Date: 2023-04-20T05:20:21.925Z
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Code-Insiders/1.78.0-insider Chrome/108.0.5359.215 Electron/22.4.7 Safari/537.36

**Comment by itzTheMeow** [comment]
I have this issue as well with a .ts file

**Comment by aiday-mar** [comment]
Thanks for filing the issue, I am indeed able to reproduce it in a JSON file
