### ISSUE TITLE
Symbolic links not marked as such in the explorer

### ISSUE THREAD

**Issue by evur** [microsoft/vscode#180412]
Type: <b>Bug</b>

Symbolic links are not marked as such in the explorer when they were normal files or folders before.

When creating a file, deleting it and then creating a symbolic link with the same name, the link is shown as if it were a normal file until VSCode is restarted.

## Reproduction (Linux)

Reproduction setup:
```
touch testfile
```

For a symbolic link which looks like a regular file in the VSCode explorer, run this:
```
touch foo
rm foo
ln --symbolic testfile foo
```

For the opposite (a regular file that looks like a symbolic link), run this:
```
ln --symbolic testfile bar
rm bar
touch bar
```

This also happens with directories (replace `touch` with `mkdir`).

VSCode version: VSCode 1.77.3
OS version: Linux x64 5.15.0-70-generic
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|Process Argv|--ms-enable-electron-run-as-node --no-sandbox --disable-extensions|
|Screen Reader|no|
</details>Extensions disabled

**Comment by lramos15** [comment]
\duplicate https://github.com/microsoft/vscode/issues/167146
