### ISSUE TITLE
[Feature request] Add Amend option for to Commit button

### ISSUE THREAD

**Issue by hansu** [microsoft/vscode#180419]
- Add a shorter path for Commit Amend (the same as **. . .** --> Commit --> Commit Staged (Amend).
- Add option for amend --no-edit, so without COMMIT_EDITMSG popping up.

![bild](https://user-images.githubusercontent.com/67957916/233402215-a2729eeb-d41e-4d85-8af5-39a861cd8b36.png)

**Comment by heartacker** [comment]
please

**Comment by lszomoru** [comment]
Latest Insiders release has "Commit (Amend)" command in the dropdown:

<img width="577" alt="image" src="https://github.com/microsoft/vscode/assets/3372902/af022170-70c0-4a92-a4fe-785880d548ae">

**Comment by hansu** [comment]
Great, thanks!
But it currently works only with staged changes.
But not if one only wants to use amend for changing the commit message. In this case the commit button is disabled
( when using this setting:
```
    "git.showActionButton": {
        "commit": true,
        "sync": false
      }
```
otherwise it would just show the Sync button )
It would be great if it would work in this case as well.

**Comment by lszomoru** [comment]
@hansu, thanks for the feedback. you are correct, the "Commit" action button is only enabled (and inherently the secondary actions (ex: Commit (Amend)) if you have changes to commit. If you would like to change the commit message of the last commit you would have to use the command from the `...` menu or the command palette.

**Comment by hansu** [comment]
Running the command "Git Commit (Amend)" does also only work with staged changes.
But no worries, there is still the command line for this case ;-)

**Comment by lszomoru** [comment]
@hansu, I see. Please feel free to file a feature request to add the capability to edit the last commit message.

**Comment by heartacker** [comment]
@lszomoru hi, do you remember that FR

add dropdown button like commit button with option for sync button
when:
- setting `git.rebaseWhenSync = false`
1. sync（ by default）
2. sync rebase （dropdown）

![image](https://github.com/microsoft/vscode/assets/1876302/764f83c5-4441-4f9e-be52-f5701c53bc62)


- setting `git.rebaseWhenSync = true`
1. sync rebase （ by default）
2. sync （dropdown）

I still believe that is useful and some like this (amend option)

**Comment by SIMJO774478989THXXX** [comment]
https://youtu.be/ZdSrOnuIxkU

**Comment by SIMJO774478989THXXX** [comment]
https://youtu.be/ZdSrOnuIxkU[https://youtu.be/ZdSrOnuIxkU](https://github.com/nodejs/help.wiki.git)

**Comment by lszomoru** [comment]
@heartacker, thanks for the nudge. 
We are planning on making some improvements to the "sync experience" so this is something that we will consider.

**Comment by lszomoru** [comment]
Verifications steps:
* Open a folder/workspace that contains a git repository
* Open a file, and make changes to it
* Expand the "Commit" action button and choose the "Commit (Amend)" option
    * Confirm that a text editor is opened with the commit message of the previous commit
* Change the previous commit message and either close the editor or click on the ✔️ icon in the editor toolbar
    * Confirm that the previous commit was amended and the commit message was updated
