### ISSUE TITLE
Menubar fails to enter compact mode on title change 

### ISSUE THREAD

**Issue by PenguinCaptain** [microsoft/vscode#180456]
Type: <b>Bug</b>

## Description
When title text changes, the compact state of menubar is not following the update. The broken menubar seems to have a werid `overflow: hidden` effect. All title text changes trigger this bug including entering on first line of new text file or switching from one file to another. There seem to have no such problem when Command Center on titlebar is enabled.

## To Reproduce
1. Create a new file by `File > New Text File`. The title text should be the content of the first line of the file.
2. Adjust the window size to the exact point where the menubar is not in compact mode.
3. Enter some random text in the first line and then a part of menubar button will be hidden.
4. Regain focus on the window or resize the window a bit should turn the menubar back to normal.

See:
![vscode-bug](https://user-images.githubusercontent.com/35358684/233506836-40df68db-d172-45b1-b464-24262fb89354.gif)

VS Code version: Code 1.77.3 (704ed70d4fd1c6bd6342c436f1ede30d1cff4710, 2023-04-12T09:16:02.548Z)
OS version: Windows_NT x64 10.0.19045
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|13th Gen Intel(R) Core(TM) i9-13900KF (32 x 2995)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|63.79GB (36.27GB free)|
|Process Argv|--crash-reporter-id 2404ace9-006b-4462-9580-a882e205457d|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by benibenj** [comment]
fixed
