### ISSUE TITLE
Feature Request: Allow `CodeLens` To Be Placed At Specified Position

### ISSUE THREAD

**Issue by KalitaAlexey** [microsoft/vscode#18046]
Hi everybody.

Currently `CodeLens` accepts a position, but it doesn't use it.

Let's look at the code:
```c
int main() {
    int a = 5 + 10;
               ^ Here is code lens
}
```

Regards,
Alexey

**Comment by jrieken** [comment]
Unlikely because it will make the looks cluttered and asks for conflicts when two lenses want the same line/character. @KalitaAlexey what is your use case and why can't you use editor decorations which allow you to do that?

**Comment by KalitaAlexey** [comment]
@jrieken,
I don't know about editor decorations.
Can you share a link with me?

**Comment by jrieken** [comment]
Sure - here we have a [sample extension](https://github.com/Microsoft/vscode-extension-samples/blob/master/decorator-sample/README.md) and full API can be found here: https://github.com/Microsoft/vscode/blob/master/src/vs/vscode.d.ts#L3575, here https://github.com/Microsoft/vscode/blob/master/src/vs/vscode.d.ts#L857, and here https://github.com/Microsoft/vscode/blob/master/src/vs/vscode.d.ts#L979

**Comment by KalitaAlexey** [comment]
I will check it out.
Please keep the issue opened.
If text decorations suit me I will close the issue.

**Comment by KalitaAlexey** [comment]
@jrieken,
Is there any way to show a text after a decorated text?
I tried to use the `after` property, but it places the text exactly after the decorated text.

**Comment by KalitaAlexey** [comment]
@jrieken,
I want to do exactly what I wrote in the issue's description.
I want a text to be placed after a line and at a certain column.
I haven't got reasons why it doesn't work this way.

**Comment by jrieken** [comment]
With "after" you mean "below", right?

**Comment by KalitaAlexey** [comment]
@jrieken,
Yes. I want it to be placed below.

**Comment by KalitaAlexey** [comment]
@jrieken,
Hi again.
What do you think is there any way to do that now?

**Comment by jrieken** [comment]
No, you cannot but something below. Only code lenses supports in-between line content, but not at a specific position, just a line

**Comment by KalitaAlexey** [comment]
@jrieken,
It is a shame.
Thanks for your assistance.

**Comment by KalitaAlexey** [comment]
@jrieken,
What does it need to implement the feature?

**Comment by jrieken** [comment]
If firstly means that the team and UX is convinced that this is a good feature that doesn't cause clutter in the editor UI, is easy to read, and has good story for handling conflicts, e.g when two lenses want to show at the same position.

**Comment by KalitaAlexey** [comment]
@jrieken,
You meant "It" instead of "If", is that correct?

**Comment by jrieken** [comment]
yes - edited my comment

**Comment by KalitaAlexey** [comment]
@jrieken,
So I can't help, isn't it?

**Comment by jrieken** [comment]
Yeah, it's a little unhappy right now. Adding @stevencl you know more about the design of code lens. 

In the meantime we can think of other approached to tackle you problem. From https://github.com/KalitaAlexey/vscode-rust/issues/46 it seems like want show more information for a compile error/warning. Is that right? Do you use the F8 feature?

**Comment by KalitaAlexey** [comment]
@jrieken,
What is **F8**?

**Comment by jrieken** [comment]
@KalitaAlexey A button on your keyboard ;-) So, have an error/warning squiggle in VS code, hit F8 (or pick 'go to next error or warning' from the command palette) and see more info about compile error inline. Like so (it does support multiline verbatim messages)  

![screen shot 2017-01-19 at 16 34 01](https://cloud.githubusercontent.com/assets/1794099/22113027/4be3aaa4-de65-11e6-8a63-343ab0ba3100.png)

**Comment by coder543** [comment]
Allowing CodeLens to decorate code arbitrarily seems like an excellent feature, and it's up to the extensions to provide configurability to suit the user. Two examples:

- IntelliJ/Android Studio now supports [parameter name hints](https://i.stack.imgur.com/BaqcG.png).
- For languages heavy on type inference, like Rust, it would be amazing to have annotations similar to the parameter name hints that shows the inferred type inline with the code.

I would love that so much.

**Comment by kjeremy** [comment]
@coder543 This is getting closer for rust. Check out https://github.com/rust-analyzer/rust-analyzer/pull/1586
