### ISSUE TITLE
Keyboard shortcut for 'keep editor' doesn't work

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#18048]
- Open a preview editor
- Press the keyboard shortcut for 'keep editor' (cmd+k enter)
- Nothing happens
- Select 'Keep Editor' from the command palette
- Command takes effect (title goes from italics to non-italics)

I added a new shortcut for the command, and nothing happens when I press that shortcut either.

**Comment by bpasero** [comment]
@roblourens does it reproduce when running "out of sources"? I think Isidor pushed a fix in this area.

**Comment by roblourens** [comment]
Does not repro in master, thanks.
