### ISSUE TITLE
Inconsistent debugger status when debuggee is paused/continued really fast

### ISSUE THREAD

**Issue by FlorentRevest** [microsoft/vscode#180409]
I am in a situation where my debugger (codelldb) attaches to a gdbserver instance in a paused state and immediately continues it (as part of the connection steps). This causes two DAB events to be sent really fast to VSCode: paused & continued. It appears that the processing of the continued event is much faster than the paused event and both are treated asynchronously so the VSCode UI ends up in a "paused" state even though the debuggee really is in a "running" state. I found that adding a Queue in the style of outputQueue in vs/workbench/contrib/debug/browser/debugSession.ts would serialize the processing of these status events and keep the end result coherent and I'm sending a PR with that proposed solution.

**Comment by roblourens** [comment]
Temporarily reverting this due to https://github.com/microsoft/vscode/issues/181485- I will restore it with a better fix for the underlying issue
