### ISSUE TITLE
Unresolved icon uses  a border color in comments panel

### ISSUE THREAD

**Issue by a-stewart** [microsoft/vscode#180420]
In the Comments panel - the unresolved comment icon uses the colour `editorCommentsWidget.unresolvedBorder` which if not defined inherits `peekViewBorder`

This means for a theme which has a very low constrast set of borders, the icon is very low in in contrast, for example:

![image](https://user-images.githubusercontent.com/150152/233403390-a88fd505-2ca6-488b-8801-e45e7a743909.png)

I'll submit a PR to the Ayu theme to see if this can be updated there, but I was wondering if perhaps it would be better to change the colour used here to something we was not originally meant to be a border?

Perhaps we could define a colour `editorCommentsWidget.unresolvedIcon` which inherits from something else, then perhaps we could change `unresolvedBorder` to perhaps inherit from that if defined, otherwise from peek view?

**Comment by alexr00** [comment]
This is the change I ended up going with (thank you for the input!):
- There are new colors `commentsView.resolvedIcon` and `commentsView.unresolvedIcon`.
- `commentsView.resolvedIcon` inherits from `list.focusOutline` (similar color to before) and `commentsView.unresolvedIcon` inherits from `disabledForeground` (same as before).
- `editorCommentsWidget.resolvedBorder` inherits from `commentsView.resolvedIcon` and `editorCommentsWidget.unresolvedBorder` inherits from `commentsView.unresolvedIcon`.
