### ISSUE TITLE
Build failed: `TextModelSearch issue #53415. W should match line break. `

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#180423]
Build: https://dev.azure.com/monacotools/a6d41577-0fa3-498e-af22-257312ff0545/_build/results?buildId=211543
Changes: https://github.com/Microsoft/vscode/compare/0610414...b02700c

**Comment by alexdima** [comment]
This test is not using async, so it has no I/O tasks, it is CPU bound. On my machine the test takes 38ms:
<img width="423" alt="image" src="https://user-images.githubusercontent.com/5047891/235127571-76d1fd31-06d7-4f1f-95fe-fdbfe3b26864.png">

The failure is that the test timed out after 5000ms. I believe that these build machines sometimes have complete freezes while running tests and everything halts and then recovers. Short of switching unit testing frameworks that don't complain about wall clock time, I don't see anything actionable that I can do.
