### ISSUE TITLE
Support a real toolbar below the window title with actions

### ISSUE THREAD

**Issue by pabloalbella** [Microsoft/vscode#18042]
- VSCode Version: Code 1.8.1 (ee428b0eead68bf0fb99ab5fdc4439be227b6281, 2016-12-19T14:49:23.350Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

|Extension|Author|Version|
|---|---|---|
|vscode-react-native|vsmobile|0.2.3|

---

Steps to Reproduce:

I couldn't find the way to load an enhancement so my apologies to use this way. Why VSCode doesn't have a Bar on top where we can configure the favorites keyboard shortcuts in buttons? Would be great to can add short access on a top bar to options like go back, indent, copy, paste, etc. any option. Thanks.

**Comment by sandy081** [comment]
@pabloalbella Do you mean to provide UI to configuring key board short cuts? I am not sure what does a Bar means here?

**Comment by pabloalbella** [comment]
@sandy081  A very simple toolsbars to set some buttons like navigate backward or any one (yes in the UI). This is just a suggestion I am very comfortable with VSCode!  

![image](https://cloud.githubusercontent.com/assets/16269622/21613456/1247754a-d1b4-11e6-8bf6-bda38cee1cbf.png)

**Comment by pabloalbella** [comment]
@sandy081 sometime you don't remember all the keyboard shortcuts, so you remember the ones you use everyday and you can create access to others you use not frequently in small buttons on top below menu. Users could add/remove buttons using the actual keyboard shortcuts list.

**Comment by sandy081** [comment]
If I am not wrong your request is to provide a customizable tool bar?

**Comment by pabloalbella** [comment]
@sandy081 Correct! And to add a new button on the tool bar we can select it from the current Command Palette. I think it is the only thing missing on VSCode. Thanks for reading the suggestion.

**Comment by ronnyek** [comment]
Honestly, this is one of the biggest reasons I find myself reverting back to using webstorm. I'd rather use vscode, but I cant remember every last keyboard shortcut and odtn want to search in command pallete

**Comment by ronnyek** [comment]
To further expand on what I'd personally like to see is debug tools in a toolbar that persist across the different views (code explorer vs extensions vs source control) so I can start debugging no matter what view I have open on the left. (having debug controls in a toolbar means it wouldn't be overlapping tabs)

Also, another few buttons I use frequently, are buttons for forward/back nav through files I've been editing. I know there are commands for that, but I cant remember them.

Seems like this would also help unclutter the status bar as developers could put buttons in a more appropriate place.

**Comment by dmgrtx** [comment]
The lack of a toolbar is the only think keeping me from making VSCode my preferred editor.
