### ISSUE TITLE
InlineCompletionContext.triggerKind is always Automatic

### ISSUE THREAD

**Issue by hstaudacher** [microsoft/vscode#180489]
Does this issue occur when all extensions are disabled?: Yes

Version: 1.78.0-insider
Commit: b19017cea80b6157aa8214c984a70022e77526f2
Date: 2023-04-21T05:39:53.263Z
Electron: 22.4.7
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Darwin arm64 22.4.0
Sandboxed: Yes

### Steps to Reproduce:

1. Execute the command `editor.action.inlineSuggest.trigger`
2. In the `InlineCompletionItemProvider` implementation `provideInlineCompletionItems` method you have access to the `InlineCompletionContext` which has a `triggerkind`. The 2 possibilities here are `Automatic` and `Invoke`. The value here is always `Automatic` regardless of auto invoke or executing the command.

### In Copliot
This issue prevents the Copilot extension from distinguishing the triggers. Our users ask for a way to disable auto completions while still allowing manual triggers. It seems the `triggerkind` is the correct way to determine this trigger but it doe snot work.

**Comment by hstaudacher** [comment]
Sure, here are 2 examples:
* https://github.com/orgs/community/discussions/46437
* https://github.com/orgs/community/discussions/9817

Having a VSCode solution sounds fine at first. Thinking about it I wonder how to name it. I mean, our customers do not know anything about an InlineCompletionProvider or so. They know Copilot, so they are looking for Copilot settings. 

I think it would really help us if the existing API would just work. We also have a setting to completely disable inline completions already.

**Comment by isidorn** [comment]
Thanks for sharing - this is great.
https://github.com/orgs/community/discussions/46437 feels unrelated to this, these folk have a problem of having multiple inline suggestion providers. Something we plan to tackle better on the VS Code side.

https://github.com/orgs/community/discussions/9817 sounds like a valid use case, and imho should be VS Code driven. Good point for having "Copilot" mentioned in the setting name for ease of finding. Can we first, better understand why users find Inline Suggestions annoying in this case. For example, is it because they are getting in the way of the Suggest Widget or it is completely unrelated. @SmallLemur could you find this out?

Let's see what @hediet thinks.

**Comment by SmallLemur** [comment]
From what  I gathered, it is not not entirely related to the  suggest widget but also preferences of the team using it. In the case of our customer, they simply prefer to have control on when they get a suggestion. So this enhancement is just to provide a way to our user to have only manual suggestion if they wish to.

**Comment by mroch** [comment]
this is a regression. `editor.action.inlineSuggest.trigger` results in "Invoked" in 1.77.3, and "Automatic" in 1.78.0-insider (b19017cea80b6157aa8214c984a70022e77526f2)

**Comment by hstaudacher** [comment]
Thx for the fast fix! You guys rock 🚀

**Comment by hstaudacher** [comment]
I can confirm that the trigger does also have the value `Invoke` now. Unfortunately manually triggered completions are not showing up at all now 😞 . This still works in 1.77 but not in the latest insiders. 

I'm using:
```
Version: 1.78.0-insider
Commit: 2902f278ad8e2d830fa6883d3d8fd7b5c2ca59e9
Date: 2023-04-25T05:59:25.219Z
Electron: 22.4.8
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Darwin arm64 22.4.0
Sandboxed: Yes
```

**Comment by isidorn** [comment]
@hstaudacher thanks for letting us know.
@hediet I can reproduce, and I opened a new issue https://github.com/microsoft/vscode/issues/180792
