### ISSUE TITLE
Terminal: command history will not be saved to $HISTFILE when close vscode

### ISSUE THREAD

**Issue by YOYOYOYOGA-seu** [microsoft/vscode#180474]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.77.3
- OS Version: macOS Ventura 13.3.1

Problem:

1.  After update to vscode 1.77, the command history will not be saved when closing vscode or kill terminal.
2. If you type 'exit' to close the terminal, the command history will be saved.
3. this problem are not existed in the previous vscode version such as 1.75.

https://user-images.githubusercontent.com/53963800/233556401-7db58b50-bc76-4f0a-8f18-0d5c5b57615e.mov

For example, in this case, the cmd `history`, `ls`, `clear` were saved successfully when close terminal by typing `exit`, but the cmd `cat ./.zsh_history` was not saved when I just close the VScode (the same problem will occur when kill the terminal).

By the ways, this problem also existed when I working in Ubuntu 20.04 by using a remote SSH.

This problem has been bothering me for a while, which causing me to use an older version VScode.

**Comment by CRISTIAN-MULLER** [comment]
The same thing is happening to me, I'm using MacBook PRO M2.

VSCODE:
Version: 1.77.3
Commit: 704ed70d4fd1c6bd6342c436f1ede30d1cff4710
Date: 2023-04-12T09:41:48.638Z (1 wk ago)
Electron: 19.1.11
Chromium: 102.0.5005.196
Node.js: 16.14.2
V8: 10.2.154.26-electron.0
OS: Darwin arm64 22.4.0
Sandboxed: Yes

**Comment by AfzalSohaib** [comment]
Same issue on Ubuntu 22.04
VSCode installed as "code" from Snap store

I verified that typing exit in the integrated terminal saves history.

**Comment by akukuq** [comment]
Same for me on Win10 with Remote SSH into Debian 11.
Closing with `exit` saves history.

**Comment by gabrielmittag** [comment]
Same issue here using WSL on Windows 11
