### ISSUE TITLE
Issue with Syntax highlighting for typescript

### ISSUE THREAD

**Issue by nurdism** [microsoft/vscode#180494]
Type: <b>Bug</b>

![](https://i.imgur.com/QkX34YD.png)

Put this code, set the file type to typescript and the Syntax highlighting messes up
```ts
() => {
    const input = ref('')
    let inputTimeout: NodeJS.Timeout | undefined
    watch(input, (value: string) => {
      if (!chatDocumentStore.value) {
        return
      }
  
      clearTimeout(inputTimeout)
      inputTimeout = setTimeout(() => {
        if (!chatDocumentStore.value) {
          return
        }
  
        const doc = chatDocumentStore.value.getLatest()
        if (input.value !== doc.input) {
          doc.incrementalPatch({
            input: value,
          })
        }
      }, 150)
    })
}
```

the issue does not persist with `code --disable-extensions`. Ran "Help: Start Extension Bisect" and it did not help, the issue persisted.

VS Code version: Code 1.77.3 (704ed70d4fd1c6bd6342c436f1ede30d1cff4710, 2023-04-12T09:16:02.548Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 9 5950X 16-Core Processor             (32 x 3400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|63.91GB (36.66GB free)|
|Process Argv|--crash-reporter-id 75225892-1767-44d8-9974-4bc743736ad1|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
gitlens|eam|13.5.0
vscode-docker|ms-|1.25.0
remote-containers|ms-|0.288.1
remote-ssh|ms-|0.100.0
remote-ssh-edit|ms-|0.84.0
remote-wsl|ms-|0.77.0
vscode-remote-extensionpack|ms-|0.24.0
remote-explorer|ms-|0.4.0
remote-server|ms-|1.0.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
nodejswelcome1cf:30587006
3biah626:30602489
pyind779:30671433
89544117:30613380
vscrpc:30673769
pythonsymbol12:30671437
2i9eh265:30646982
vsccsb:30705552
azdwalk:30687957
pythonms35:30701012
pythonfmttextcf:30716743

```

</details>

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

**Comment by nurdism** [comment]
it seems to be fine on VS Code insiders, with fresh install

**Comment by mjbvz** [comment]
Thanks for testing. Sounds like this was already fixed so closing
