### ISSUE TITLE
VSCode refuses to type check JavaScript files

### ISSUE THREAD

**Issue by wojtekmaj** [microsoft/vscode#180401]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.77.3 (Universal)
- OS Version: macOS Ventura 13.3.1

Steps to Reproduce:

Despite trying everything that was [documented](https://code.visualstudio.com/docs/nodejs/working-with-javascript#_type-checking-javascript), VSCode straight out refuses to type check JavaScript files.

I have tried:
* Adding `@ts/check` explicitly to files I want to have checked
* Adding `jsconfig.json` with `"checkJs": true`
* Adding `tsconfig.json` with `"allowJs": true, "checkJs": true`
* Adding `js/ts.implicitProjectConfig.checkJs": true` setting

The following illustration shows how TS file is checked, while identical JS file is not.

<img width="1463" alt="image" src="https://user-images.githubusercontent.com/5426427/233329252-6fd441ce-ff98-4b72-8cb1-730ad49d832a.png">

Another example shows how `tsc --noEmit` is able to find the error, but VSCode is not:

<img width="1463" alt="image" src="https://user-images.githubusercontent.com/5426427/233331405-1e22d0d3-f731-4671-ac6b-0c0b45ed1e07.png">

**Comment by mjbvz** [comment]
What's the structure of your project? Can you share a small example project with the issue

**Comment by wojtekmaj** [comment]
Sure! Here's the minimal reproduction:

[vscode-typescript-repro.zip](https://github.com/microsoft/vscode/files/11289608/vscode-typescript-repro.zip)

**Comment by mjbvz** [comment]
Thanks. Works fine for me though:

![Screenshot 2023-04-20 at 2 00 42 PM](https://user-images.githubusercontent.com/12821956/233486762-760a84a6-99f4-43a8-b7fe-2dbc588559c1.png)

Did you set `"javascript.validate.enable": false`?  Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

**Comment by wojtekmaj** [comment]
OH. MY. GOD. 

It's that setting indeed! I've set it back in like 2017 and completely forgot about it 🤦‍♂️ Would be good to add it to the docs to ensure this setting is not turned off!
