### ISSUE TITLE
gutter shift when hovering the currently debugged line

### ISSUE THREAD

**Issue by amunger** [microsoft/vscode#180435]
1. debug with a breakpoint and hit the breakpoint
2. hover over the breakpoint
:bug: the breakpoint moves and I click a different icon
![breakpointShift](https://user-images.githubusercontent.com/2019016/233457896-74cc2ae6-70b2-490b-9337-795d2088745b.gif)

**Comment by joyceerhl** [comment]
Duplicate https://github.com/microsoft/vscode/issues/180439
