### ISSUE TITLE
Close settings: maximum call stack size exceeded

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#18055]
1. Open user or workspace settings
2. Close settings editor -> maximum call stack size exceeded -> vscode crash

I am seeing this with latest from master, not with insiders - will probably show up in tomorrow's build.

**Comment by sandy081** [comment]
@jrieken This is coming from [here](https://github.com/microsoft/vscode/blob/master/src/vs/editor/contrib/quickFix/common/quickFixModel.ts#L150)

I am not sure why this is not happening for normal file editors. I am explicitly disposing editors.

**Comment by isidorn** [comment]
@jrieken consider rebuilding insiders - this issue can be rather frustrating :)

**Comment by jrieken** [comment]
Builds are already running
