### ISSUE TITLE
Notebook cell selection is altered by inner list view selection

### ISSUE THREAD

**Issue by amunger** [microsoft/vscode#180575]
1. create a notebook with a few cells
2. call function that has a few references
3. peek at the references and navigate between them
:bug: cell selection changes

![listViewSelection](https://user-images.githubusercontent.com/2019016/233737591-0cb5acdc-531d-48fe-8a21-f0f3b3b6addc.gif)

**Comment by roblourens** [comment]
I don't understand why that code is focusing a different cell?

**Comment by roblourens** [comment]
It seems like it's focusing the list row with the same index, there is another issue related to the nested list problem, and a PR open with an attempt to fix it, maybe this is related to that.

**Comment by rebornix** [comment]
This is a dup of https://github.com/microsoft/vscode/issues/97820, let's merge into that issue.
