### ISSUE TITLE
terminal path link support recogonize query string

### ISSUE THREAD

**Issue by tjx666** [microsoft/vscode#180574]
@Tyriar @meganrogge 

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/41773861/233735883-f0d1f477-5b77-4490-bd59-a08a9be59c0f.png">

path:

```bash
 File: /Users/yutengjing/code/vite-vue2/apps/design/src/explorerVue/App.vue?vue&type=style&index=0&lang.css
```

Versions:

```
Version: 1.77.3 (Universal)
Commit: 704ed70d4fd1c6bd6342c436f1ede30d1cff4710
Date: 2023-04-12T09:19:37.325Z
Electron: 19.1.11
Chromium: 102.0.5005.196
Node.js: 16.14.2
V8: 10.2.154.26-electron.0
OS: Darwin x64 22.4.0
Sandboxed: No
```

**Comment by tjx666** [comment]
I have one question wish can get help:

how vscode terminal detect the path cwd? why can the path correct go to the file with a releative path?

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/41773861/233736630-48597538-38df-4955-b21e-5d56d7dca963.png">

I guess it may use the [terminal integratation](https://code.visualstudio.com/docs/terminal/shell-integration)

But seems I can get the cwd in TerminalLinkProvider now:

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/41773861/233737100-8de7dc1b-709e-43fe-8b70-871b1d89b146.png">

**Comment by roblourens** [comment]
When I click, it opens the right file, but it underlines the first query argument when I hover

<img width="539" alt="image" src="https://github.com/microsoft/vscode/assets/323878/516eabfa-4a12-4ccf-93a1-6fd12b944efa">

**Comment by Tyriar** [comment]
@roblourens not much of an issue but it would look more polished by just underlining the whole thing https://github.com/microsoft/vscode/issues/183958
