### ISSUE TITLE
Minor glitch in context menu causes frustrating behaviour with trackpad

### ISSUE THREAD

**Issue by KayJay7** [microsoft/vscode#180544]
Does this issue occur when all extensions are disabled?: No

- VS Code Version: 1.77.3
- OS Version: Fedora 38 with gnome 44 wayland, occurred on fedora 37 with gnome 43 wayland as well

Steps to Reproduce:

1.  Open vscode with a bunch of extensions (adding items to the context menu)
2.  Do a 2-fingers tap on a word around the middle of the screen (with a mouse the glitch is harmless)

The context menu appears just a tiny bit too much to the left, just enough that if the menu is tall enough, the mouse pointer is already hovering over an item in the menu (which appears highlighted), not just the border of the menu. Screenshot below.

When using a mouse this is not an issue, nothing particular happens other than being imperceptibly too left. But when using a trackpad, tapping behaves like holding and releasing the right mouse button, so instead of just opening the context menu it immediately executes whatever action was already under the mouse cursor when tapping.

I believe this only happens when the context menu is taller than a certain amount (probably half the screen), because disabling all extension fixes the problem. And when bisecting it still happens when enough extension are enabled but it doesn't identify any specific extension.

This happens both on wayland and xwayland, but I'm not sure about x11, I think x11 might expose the 2-fingers tap differently from wayland.

![Screenshot from 2023-04-19 10-08-48](https://user-images.githubusercontent.com/31775749/233687365-aab02103-aa79-4fb8-a5a0-d5408dee7c6a.png)

**Comment by lszomoru** [comment]
@jrieken, is this something that falls into your area of ownership? Thanks!
