### ISSUE TITLE
vscode crashing on starting the application

### ISSUE THREAD

**Issue by Shourabh1478** [microsoft/vscode#180591]
Type: <b>Bug</b>

On starting vscode it displays black screen then shows the prompt 'keep waiting' and 'close the application' 
I reinstalled the application but the issue didn't resolve
It started happening after I updated my windows 11 version to 22H2.

VS Code version: Code 1.77.3 (704ed70d4fd1c6bd6342c436f1ede30d1cff4710, 2023-04-12T09:16:02.548Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-10300H CPU @ 2.50GHz (8 x 2496)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|7.84GB (1.86GB free)|
|Process Argv|--crash-reporter-id 64c260a9-32c3-4573-aeae-e090097d4dc3|
|Screen Reader|no|
|VM|50%|
</details><details><summary>Extensions (21)</summary>

Extension|Author (truncated)|Version
---|---|---
bootstrap5-vscode|Anb|0.4.2
dart-code|Dar|3.62.0
vscode-styled-components|die|0.1.33
es7-react-js-snippets|dsz|4.4.3
prettier-vscode|esb|9.12.0
code-runner|for|0.12.0
cxx-compiler-explorer|har|0.7.0
terraform|has|2.25.4
isort|ms-|2022.8.0
python|ms-|2023.6.1
vscode-pylance|ms-|2023.4.30
jupyter|ms-|2023.3.1201040234
jupyter-keymap|ms-|1.1.0
jupyter-renderers|ms-|1.0.15
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-slideshow|ms-|0.1.5
cpptools|ms-|1.14.5
debugger-for-chrome|msj|4.13.0
LiveServer|rit|5.7.9
bootstrap4-vscode|the|6.1.0
msbuild-project-tools|tin|0.4.9

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
nodejswelcome1:30587005
2e4cg342:30602488
pyind779:30671433
f6dab269:30613381
pythonsymbol12:30671437
azdwalk:30721579
pythonms35:30701012
pythonfmttext:30716742
pythonclientmvcf:30713944
f8hc8238:30694864

```

</details>

**Comment by deepak1556** [comment]
Do you have Mcafee AV installed ? If so, can you follow the steps in https://github.com/microsoft/vscode/issues/178733#issuecomment-1500812938 and see if that resolves the issue ?

**Comment by Shourabh1478** [comment]
Thanks  a lot!! 
The issue got resolved.
