### ISSUE TITLE
Error when debugging javascript

### ISSUE THREAD

**Issue by viethung9at1** [microsoft/vscode#180587]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.77.3
- OS Version: 10.0.22624.1616

Steps to Reproduce:

1. Debug Javascript code by Launch Edge
2. Error running browserasd: connect ECONNREFUSED 127.0.0.1:53709

**Comment by connor4312** [comment]
Duplicates https://github.com/microsoft/vscode-js-debug/issues/1603
