### ISSUE TITLE
<enter><enter><up> does not place caret on correct line.

### ISSUE THREAD

**Issue by arkalyanms** [microsoft/vscode#180555]
Start with code like:

![image](https://user-images.githubusercontent.com/60013978/233699793-afb02553-8dfd-47dc-acd8-ca9f668f7929.png)

With caret after the first `{` for 'OnWorkspaceChanged's method body.

Press enter twice, then up. 

Expected:

to have:

![image](https://user-images.githubusercontent.com/60013978/233699826-2b540f35-d3b8-4545-aff3-f420d5af1d0b.png)

Where the caret is at the right position to start typing (this is how VS works, since 2003/2005).

Actual:  Caret is left flush:

![image](https://user-images.githubusercontent.com/60013978/233699851-a98c58d1-dc5c-4f54-972f-a7c1c6681d53.png)

This means that typing will be in the wrong location, leading to formatting errors.  It's also just extremely annoying.  `Up/Down` into a blank line should go to the appropriate indentation level so someone can just start typing what they need and have it immediately be in the right indentation level.

**Comment by CyrusNajmabadi** [comment]
hey @DonJayamanne lmk if you need anymore info on this.

**Comment by alexdima** [comment]
By default, the editor will trim automatic whitespace that it inserted as soon as a different line is edited. This behavior can be obtained using `"editor.trimAutoWhitespace": false`.
