### ISSUE TITLE
i cant name the untitlled 

### ISSUE THREAD

**Issue by Aravindh0359** [microsoft/vscode#180504]
Type: <b>Bug</b>

when  i open "OEPN EDITORS" in that one icon i have seen "+"  simboal i want to name that coading which it is "UNTITLED" in defalt i want to change it but something trobule shooting was facing i cant rename it so kindly help me with this issue.

VS Code version: Code 1.77.3 (704ed70d4fd1c6bd6342c436f1ede30d1cff4710, 2023-04-12T09:16:02.548Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: No

<details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
codeium|Cod|1.2.5
LiveServer|rit|5.7.9

</details>

**Comment by gjsjohnmurray** [comment]
I suggest you save the file, giving it the name you want.

**Comment by aeschli** [comment]
Yes, as @gjsjohnmurray says, when you save the file you can give it a name
