### ISSUE TITLE
windows not responding

### ISSUE THREAD

**Issue by SAKSHaTHOR** [microsoft/vscode#180592]
Type: <b>Bug</b>

the app is opening very slow like it taking alm,ost a minute to open and after that it showing window is not responding with three notes close ,keepwriting , reopen please resolve this in next update

VS Code version: Code 1.77.3 (704ed70d4fd1c6bd6342c436f1ede30d1cff4710, 2023-04-12T09:16:02.548Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|12th Gen Intel(R) Core(TM) i5-1235U (12 x 2496)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|7.73GB (2.12GB free)|
|Process Argv|--crash-reporter-id bde4f319-985e-444a-9a79-5ddf3d39b7de|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (17)</summary>

Extension|Author (truncated)|Version
---|---|---
dart-code|Dar|3.62.0
flutter|Dar|3.62.0
vscode-html-css|ecm|1.13.1
prettier-vscode|esb|9.12.0
code-runner|for|0.12.0
solidity|Jua|0.0.152
cpptools|ms-|1.15.2
cpptools-extension-pack|ms-|1.3.0
java|red|1.18.2023042004
LiveServer|rit|5.7.9
intellicode-api-usage-examples|Vis|0.2.7
vscodeintellicode|Vis|1.2.30
vscode-java-debug|vsc|0.49.2023032407
vscode-java-dependency|vsc|0.21.2
vscode-java-pack|vsc|0.25.2023042006
vscode-java-test|vsc|0.38.2023032402
vscode-maven|vsc|0.41.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
nodejswelcome1:30587005
2e4cg342:30602488
pyind779:30671433
89544117:30613380
pythonsymbol12:30671437
2i9eh265:30646982
showlangstatbar:30672706
vsccsb:30705552
azdwalk:30721579
pythonms35:30701012
pythonfmttextcf:30716743
pythonclientmv:30713943

```

</details>

**Comment by deepak1556** [comment]
Can you follow the steps in https://github.com/microsoft/vscode/issues/178733#issuecomment-1500812938 and exclude the `code.exe` binary.

Merging to https://github.com/microsoft/vscode/issues/178962
