### ISSUE TITLE
Test: making Continue Working On easier to discover

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode#180570]
Refs: https://github.com/microsoft/vscode/issues/179012, https://github.com/microsoft/vscode/issues/179013

- [x] anyOS @aiday-mar
- [x] anyOS @digitarald

Complexity: 1

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23180570%0A%0A&assignees=joyceerhl)

---

Setup:
- If you have previously turned on Cloud Changes, ensure it is turned off

Testing:
1. Open a repository like https://insiders.vscode.dev/github/microsoft/vscode
2. Open the terminal and verify that there are actions to continue working in another environment. Ensure that the text you see in the terminal is clear
3. Click one of the actions to continue working elsewhere
4. Ensure that you are first prompted about whether you want working changes to come with you, then prompted to sign in to store your working changes in our services

**Comment by digitarald** [comment]
So cool, just ran into this last week and this new flow would have solved it.
