### ISSUE TITLE
Test: remote repository picker in remote windows

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode#180536]
Refs: https://github.com/microsoft/vscode/issues/177944

- [x] anyOS @deepak1556
- [x] anyOS @mjbvz

Complexity: 2

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23180536%0A%0A&assignees=joyceerhl)

---

Setup:
- Install pre-release GitHub Repositories and pre-release Remote Repositories extensions in VS Code desktop

Testing:
1. Open a few of the following remote window types
    - WSL
    - SSH
    - Tunnels
    - Containers
    - Codespaces
2. Run the `Open Remote Repository` command from the command palette and ensure that the picker works
3. Ensure that when you select a GitHub repository to open, the resultant window opens in the web worker extension host rather than reusing the remote window's remote connection
4. Enable `"workbench.remote.experimental.showStartListEntry": true`
5. Ensure that the `Open Remote Repository` option appears in the welcome page's `Connect to...` picker and in the remote indicator in remote windows

**Comment by deepak1556** [comment]
> Ensure that when you select a GitHub repository to open, the resultant window opens in the web worker extension host rather than reusing the remote window's remote connection

Can you clarify what does opening in the web worker extension host mean ? What is the best way to verify this ?

**Comment by joyceerhl** [comment]
Sorry, I mean to say that you'd just verify that the window with your remote repository workspace is not running over a remote connection (i.e. the resultant window is not a remote window). I think the easiest way is to open the extensions view and check that you only see one set of extensions, rather than both local and remote extensions.
