### ISSUE TITLE
Node port not being killed on quit (CMD + Q)

### ISSUE THREAD

**Issue by arsen-a** [microsoft/vscode#180528]
Type: <b>Bug</b>

Environment: Vue 3 bundled with Vite, Yarn package manager

1. Open up the integrated terminal
2. Start up the server (defaulted to port 5173 in my case)
3. Without killing the server force quit the VS Code
4. Observe the port not being killed ( lsof -i:5173 )

I'm not sure whether this started happening since we've moved to Vite from Webpack, or when the previous VS Code update occurred.

VS Code version: Code 1.77.3 (704ed70d4fd1c6bd6342c436f1ede30d1cff4710, 2023-04-12T09:41:48.638Z)
OS version: Darwin arm64 22.3.0
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M2 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|4, 3, 2|
|Memory (System)|16.00GB (3.92GB free)|
|Process Argv|--crash-reporter-id adf82c68-4f24-4335-94ed-af63a9f10a5a|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by deepak1556** [comment]
Merging to https://github.com/microsoft/vscode/issues/174956
