### ISSUE TITLE
Test: Git LFS commit support in github.dev and vscode.dev

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode#180542]
Refs: https://github.com/microsoft/vscode-remote-repositories-github#7

- [x] anyOS @daviddossett
- [x] anyOS @mjbvz
- [x] anyOS @rzhao271

Complexity: 3

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23180542%0A%0A&assignees=joyceerhl)

---

This milestone, we've added support for committing LFS-tracked files when using GitHub Repositories in vscode.dev and github.dev.

Setup:
- Ensure you have installed and enabled the pre-release of GitHub Repositories in vscode.dev and/or github.dev
- Verify you have `"githubRepositories.lfs.write.enabled": true`

Testing:
1. Open https://github.dev/microsoft/vscode-docs/tree/vnext/ or https://insiders.vscode.dev/github/microsoft/vscode-docs/tree/vnext
2. Add your release notes screenshots, gifs, or mp4 (to simultaneously create image files and generate a markdown link to that file, you can paste screenshots from your clipboard directly into a markdown file. For mp4s and gifs, you can first use the Upload File explorer context menu entry to upload the file, then copy the explorer entry or drag and hold shift to create a markdown link to the file)
    <img width="558" alt="image" src="https://user-images.githubusercontent.com/30305945/233689760-2dadfcf9-93cb-4aee-bbcb-aab0f35647fb.png">

3. Commit them using the SCM view
4. Open the repo on github.com (you can use `Copy GitHub HEAD Link` in the editor context menu to get a link to a specific LFS-tracked file on github.com) and verify that GitHub.com says that the file was committed with LFS

**Comment by hbons** [comment]
I'll be out of office and won't be able to test this round.

**Comment by daviddossett** [comment]
👏

**Comment by mjbvz** [comment]
Works great!
