### ISSUE TITLE
f1 autocomplete o select first match

### ISSUE THREAD

**Issue by MrShortcut** [microsoft/vscode#180516]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.77.3
- OS Version: Windows NT x64

Steps to Reproduce:

1. by pressing the f1 key or what is executing the command shoy all commands, and writing a command for example >editor font zoom in, before pressing the enter key the first match was selected, now I have to press the down arrow key to select. why the change?
2. I know it sounds ridiculous to press one more key, but when you have vim installed in vscode and you do everything with few hand movements to improve ergonomics, separating your hand to go find the down arrow key takes away my development flow

**Comment by gjsjohnmurray** [comment]
Does https://github.com/microsoft/vscode/issues/180302#issuecomment-1514589387 help?

**Comment by MrShortcut** [comment]
hey  @gjsjohnmurray thanks!!!
