### ISSUE TITLE
Expose ILinkSupport in API

### ISSUE THREAD

**Issue by IgnacioHR** [Microsoft/vscode#1805]
Hi, I've started to write an extension to provide support for W3C XLink Specification to the xml language the xlink specification provides attributes to document links from an XML fragment o another XML fragment.

At the time I find an xlink:href attribute on an XML node I'm able to create a customized decoration on the attribute value but I'm unable to find the way to properly implement a mechanism to detect when the user has clicked on the decoration. I've actually implemented a DefinitionProvider that is able to open the document but the user must press F12 or right click on the text and select "Go to Definition" but a link is not a Definition but just the link end point.

Cheers,
Ignacio

**Comment by joaomoreno** [comment]
@alexandrudima ping

**Comment by alexandrudima** [comment]
@jrieken How do you think we should better handle this?

Should we expose `ILinkSupport` in the api and accumulate & dedup the links from all parties? Or should DefinitionProvider be expanded in scope to capture any link?

**Comment by jrieken** [comment]
@IgnacioHR Are the documents those links point to usually inside the workspace or something like a http-url that you want to be opened in a browser?

**Comment by IgnacioHR** [comment]
Links points anywhere. They are just links. The URI is resolved using xml:base standard resolution and the target file might be local or external. When local, I open it on a side editor and I find the target element so it is highlighted.
<img width="1907" alt="_extension_development_host__-_202-01-hrefresolution_xsd_y_extension_ts_-_miextension_y_add_api_support_to_mouse_events_in_editor_ _issue__1805_ _microsoft_vscode_y_entrada_ _ignacio_reportingstandard_com__2959_mensajes_" src="https://cloud.githubusercontent.com/assets/16385090/12377425/3d8951ca-bd1e-11e5-9a2f-a4b88fefd738.png">

**Comment by jrieken** [comment]
Thanks. I think the best will be expose the `ILinkSupport` in some form. VS Code (as today) will come with a decent default implementation but for special cases (like above) you can mark for regions of a document as hyperlink.

**Comment by IgnacioHR** [comment]
Sounds good to me. Thanks

**Comment by jrieken** [comment]
- [ ] add `registerDocumentLinkProvider` API
- [ ] add corresponding command
- [ ] update sample
