### ISSUE TITLE
intellisense

### ISSUE THREAD

**Issue by AntonioliBenjamin** [microsoft/vscode#180519]
Type: <b>Bug</b>

ifinitly loading IntelliSense status

VS Code version: Code 1.77.0 (Universal) (7f329fe6c66b0f86ae1574c2911b681ad5a45d63, 2023-03-29T09:57:11.797Z)
OS version: Darwin x64 21.3.0
Modes:
Sandboxed: No
Remote OS version: Linux x64 5.15.49-linuxkit

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|3, 4, 4|
|Memory (System)|16.00GB (0.24GB free)|
|Process Argv|--crash-reporter-id 5700f1e7-62ae-483f-9465-0a35c6254649|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|Dev Container: Cresh API @ desktop-linux|
|OS|Linux x64 5.15.49-linuxkit|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (6 x 2600)|
|Memory (System)|7.67GB (1.66GB free)|
|VM|0%|
</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-sql-template-literal|for|0.1.0
remote-containers|ms-|0.288.1
remote-explorer|ms-|0.4.0
material-icon-theme|PKi|4.26.0
material-theme|zhu|3.15.8
vscode-openapi|42C|4.16.6
npm-intellisense|chr|1.4.4
vscode-eslint|dba|2.4.0
EditorConfig|Edi|0.16.4
vscode-sql-template-literal|for|0.1.0
vscode-pull-request-github|Git|0.62.0
vscode-yaml|red|1.12.2

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
nodejswelcome1:30587005
282f8724:30602487
pyind779:30671433
f6dab269:30613381
pythonsymbol12:30671437
showlangstatbar:30672706
azdwalk:30687957
pythonms35:30701012
pythonfmttext:30716742

```

</details>

**Comment by AntonioliBenjamin** [comment]
Thank you for the answer, in my case what caused this problem was more related to the dev container, when I'm outside I have no problem with imports and types that load indefinitely.

So I just stop using the dev container

**Comment by jrieken** [comment]
Thanks for the update
