### ISSUE TITLE
Enter inside a comment should start a comment on the next line.

### ISSUE THREAD

**Issue by arunchndr** [microsoft/vscode#180551]
![image](https://user-images.githubusercontent.com/60013978/233698236-57efba01-9508-4434-af3a-89190ef239c0.png)

Caret is after `solution` in that comment.  Hitting enter should produce:

![image](https://user-images.githubusercontent.com/60013978/233698246-6879bddf-fa75-4838-866c-9d8286157ac5.png)

(note the caret location as well).  But it does not.  Instead, you get:

![image](https://user-images.githubusercontent.com/60013978/233698263-d95ea72d-0588-4732-8b17-7c781488bdc6.png)

**Comment by alexdima** [comment]
This is a nice idea and can be achieved by adding the following rule to `onEnterRules` in the language configuration:
```jsonc
"onEnterRules": [
    {
        "beforeText": {
            "pattern": "//.*"
        },
        "afterText": {
            "pattern": "\\S+"
        },
        "action": {
            "indent": "none",
            "appendText": "// "
        }
    },
    // ...
]
```

https://user-images.githubusercontent.com/5047891/235083102-d3fe1598-2cc3-4413-8819-12993a979ea0.mp4

**Comment by starball5** [comment]
What exactly does it mean that this is in a milestone? I'm confused, because @alexdima's comment above seems to imply "go ask the maintainer of the language support extension you're using to implement this".

**Comment by katerlouis** [comment]
> What exactly does it mean that this is in a milestone? I'm confused, because @alexdima's comment above seems to imply "go ask the maintainer of the language support extension you're using to implement this".

@alexdima 👆 could you elaborate on that?

**Comment by RobertOstermann** [comment]
@aiday-mar  Is there a way to disable this? Most of the time I am working with comments I do not want the next line to also be commented.

**Comment by aiday-mar** [comment]
Hi @RobertOstermann thanks for the comment. This behavior has changed and now it behaves as what you mentioned, that is a comment is added when there are letters after the cursor position on the current line. You should see this in the latest insiders

**Comment by starball5** [comment]
The case with no text after caret is covered by #26694.

**Comment by iwangbowen** [comment]
Why it took so long add this feature

**Comment by aoyama-val** [comment]
Is there a plan to enable this also when the cursor is at the end of line?

**Comment by aiday-mar** [comment]
Hi @aoyama-val thank you for the comment. For the moment there is no such plan.

**Comment by CyrusNajmabadi** [comment]
@iwangbowen 

> Why it took so long add this feature

Resourcing and other priorities.  Note: this is all open source.  So if this is something you are passionate about, we welcome community contributions.
