### ISSUE TITLE
terminal is not showing any out put in java code

### ISSUE THREAD

**Issue by Gablukumar** [microsoft/vscode#180558]
We have written the needed data into your clipboard because it was too large to send. Please paste.
I start vs code for java coding now i m facing problems in terminal .
terminal is not showing any output of java or error,
I try so much effort to fix this problem but i can not fix this problem
i try may sattings options and reinstall vs code and jdk but problem not fix 
please help to fix it 
i think when i run my first code then its run good and i want to type anouther code i erase some different code which is importent .

**Comment by meganrogge** [comment]
Pls create an issue w the Java extension
