### ISSUE TITLE
Exit code: '137' Error: 'Failed to initialize CoreCLR in Visual Studio Code 1.77.3

### ISSUE THREAD

**Issue by Hobbit7** [microsoft/vscode#180598]
I get this error when I click on F5(Start Debugging) in my project:
https://i.stack.imgur.com/IBTS7.png

In the Terminal window I have this:

> MSBuild version 17.5.1+f6fdcf537 for .NET Determining projects to restore... All projects are up-to-date for restore. Myazurefunctions -> /Users/name/Myazurefunctions/bin/Debug/netcoreapp3.1/bin/Myazurefunctions.dll /Users/name/.nuget/packages/microsoft.azure.webjobs.script.extensionsmetadatagenerator/1.1.8/build/Microsoft.Azure.WebJobs.Script.ExtensionsMetadataGenerator.targets(37,5): warning : Failed to initialize CoreCLR, HRESULT: 0x80004005 [/Users/name/Myazurefunctions/Myazurefunctions.csproj] Debug output from extension.json generator:
/Users/name/.nuget/packages/microsoft.azure.webjobs.script.extensionsmetadatagenerator/1.1.8/build/Microsoft.Azure.WebJobs.Script.ExtensionsMetadataGenerator.targets(37,5): error : Metadata generation failed. Exit code: '137' Error: 'Failed to initialize CoreCLR, HRESULT: 0x80004005' [/Users/name/Myazurefunctions/Myazurefunctions.csproj]
> The terminal process "dotnet 'build', '/property:GenerateFullPaths=true', '/consoleloggerparameters:NoSummary'" terminated with exit code: 1.
> Terminal will be reused by tasks, press any key to close it.

I have already tried to delete my project's bin and obj folders on my Mac but the problem still exists when I open Visual Studio Code. My project looks like this:
https://i.stack.imgur.com/hKP8c.png

I use Visual Studio Code Version: 1.77.3.
How can I solve this problem?

**EDIT:**
Myazurefunctions.csproj:
`<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <AzureFunctionsVersion>v3</AzureFunctionsVersion>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Sdk.Functions" Version="3.0.7" />
    <PackageReference Include="PlayFabAllSDK" Version="1.80.200901" />
    <PackageReference Include="PlayFabCloudScriptPlugin" Version="1.53.190627-alpha" />
  </ItemGroup>
  <ItemGroup>
    <None Update="host.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="local.settings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>Never</CopyToPublishDirectory>
    </None>
  </ItemGroup>
</Project>`

**Comment by roblourens** [comment]
vscode doesn't know anything about dotnet or coreCLR out of the box. If you think that there's an issue with the dotnet extension, please file this on that extension's repo
