### ISSUE TITLE
Multiroot Workspaces per folder profile

### ISSUE THREAD

**Issue by Real-Gecko** [microsoft/vscode#180599]
It would be nice to be able to apply different profiles on per folder basis for multi-root workspaces.

For example I work on a project that has backend in Python and frontend in Typescript. Thus I use different profiles for each part of the project, however this means I have to open two VSCode instances at the same time, with different profiles applied. And also VSCode treats this as two different workspaces even though "logically" it's same project.

**Comment by sandy081** [comment]
If I understand, you want to open a MR workspace and have two profiles applied for that?

**Comment by Real-Gecko** [comment]
Yes, exactly.

**Comment by sandy081** [comment]
I do not think it is trivial to support and not according to the current design of how workspaces and profiles work. It is designed such a way that a workspace can be associated to a single profile.

**Comment by Real-Gecko** [comment]
It's a pity.
