### ISSUE TITLE
Test: remote explorer polish

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode#180561]
Refs: https://github.com/microsoft/vscode/issues/178854

- [x] anyOS @ulugbekna
- [ ] anyOS @gregvanl

Complexity: 2

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23180561%0A%0A&assignees=joyceerhl)

---

This milestone, we've made several polish improvements to the remote explorer.

Setup:
- Install the pre-releases of the remote extensions (click the remote indicator and select `Install Additional Remote Extensions` to show all remote extensions in the extensions view, then install any extensions you don't already have from the extensions view)

Test:
1. The Get Started item in the remote explorer help section now supports opening remote extensions' walkthroughs (if one is contributed)
    - Verify that the entries for WSL and Remote Repos will open their Get Started walkthroughs
    - Verify that the other entries will open the documentation
2. There is no longer a Provide Feedback node in the remote help section
3. The Report Issue node for GitHub codespaces now goes to GitHub Discussions rather than opening the issue reporter
4. The Remote Help view title for Tunnels and SSH now says `Remotes (Tunnels/SSH)` rather than `Remote`
5. The WSL icon to add a new distro in the view title matches the icon for all other remotes

**Comment by ulugbekna** [comment]
Cool, I learned a bunch about remote extensions testing this. Maybe Greg finds these helpful as well: 

0. Remote WSL extension is Windows only

1. There's Remote Explorer item in the activity bar 

<img width="199" alt="image" src="https://user-images.githubusercontent.com/16353531/234233491-d5477b93-3f1b-4683-b6e0-c99281aa8447.png">

2. There's "Help & feedback" tree view section
<img width="468" alt="image" src="https://user-images.githubusercontent.com/16353531/234233604-f378a730-abfd-4dab-98d6-466f43ae8cae.png">

3. One can switch between different remotes to see different views

<img width="481" alt="image" src="https://user-images.githubusercontent.com/16353531/234234366-d5bb51ea-74d0-4a33-bbe3-e26082201218.png">

**Comment by gregvanl** [comment]
Looks good. Tested on Windows 11
