### ISSUE TITLE
Connect ENOENT Error when trying to restart powershell debugging session.

### ISSUE THREAD

**Issue by GarThor** [microsoft/vscode#180565]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.77.3
- OS Version: windows 10
![image](https://user-images.githubusercontent.com/43391503/233712460-e21081e3-e7de-4cc8-b16a-9e33f3a8ffa5.png)

Steps to Reproduce:

1. Start debugging a powershell project
2. terminate debugging early, or have it crash the powershell terminal
3. attempt to restart debugging without restarting vscode
4. connect ENOENT error telling me to Open 'launch.json', but not what to do with that file.
![image](https://user-images.githubusercontent.com/43391503/233712556-781615e6-8fcc-442f-944d-d96074ea9149.png)

My Launch.json for debugging powershell:
        {
            "name": "PowerShell Interactive Session",
            "type": "PowerShell",
            "request": "launch",
            "cwd": "${WorkspaceRoot}"
        },
        {
            "type": "PowerShell",
            "request": "launch",
            "name": "PowerShell Launch Script",
            "script": "${file}",
            "args": [],
            "cwd": "${file}"
        },

**Comment by roblourens** [comment]
Please file this on the powershell debug extension
