### ISSUE TITLE
Files are not restored on next startup

### ISSUE THREAD

**Issue by dbradomaha** [microsoft/vscode#180512]
Hi everyone,

I just wanted to let the dev team know that I am also experiencing the issue described in this thread.
Sometimes, after a clean closing of the application (done by clicking the upper-right cross), followed by a shutdown of the computer (typically during the night or week-end), it won't reopen the opened files at its next launch (but it will often [or always?] re-open the project folder, but with no files/tab opened).

I don't do anything differently, and I always close vscode myself (not letting the OS, Windows here, forcing its termination), then I always wait a few seconds before shutting down the system. 
After startup, I always re-open vscode by typing "vscode" in the windows search bar, and clicking the App from there, if that matters.

That would be amazing if you could make a patch for this issue, because when one is working on a big project and in the middle of implementing something, having the tabs organized in a specific way is super productive, and re-opening all the files manually is time consuming.

Many thanks for your work on vscode by the way!

_Originally posted by @FranckQC in https://github.com/microsoft/vscode/issues/160077#issuecomment-1485207205_

**Comment by dbradomaha** [comment]
I am having the same issue referenced above. This is on a Dell XPS laptop running Windows 11. I do not now how to troubleshoot it or where to find any log files that would tell me why it is happening.

**Comment by bpasero** [comment]
Can you clarify what steps you take and what you see?

**Comment by dbradomaha** [comment]
Thank you for your reply. In settings I have Restore Windows set to "all". I have also set it to "preserve". The behavior is the same. I start VSCode and it opens with my workspace showing in the explorer pane. I open several files from the workspace and work on them. At the end of the day, I close VSCode and all other applications and shut the laptop down. The next day when I start the laptop back up and start VSCode, it opens with my workspace showing in the explorer pane but none of the files that I had open the previous day are open. I do not know what other settings I should have or where to look for diagnostic information. VSCode is installed in Program Files.

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by bpasero** [comment]
I suggest you file a new issue for that. The insiders version you are on will be promoted to stable next week.

**Comment by dbradomaha** [comment]
Thank you

**Comment by dbradomaha** [comment]
I spoke too soon. I opened vscode this morning and it did not restore my session from yesterday.

**Comment by CraigJamesHamilton** [comment]
Hi,
I'm experiencing exactly the same problem on v1.77.3. As with dbradomaha I just have an explorer panel and no previously opened files available. All settings are as they should be as detailed in earlier posts.

In addition it VS code also looses all breakpoints when it is restarted which is a nightmare.

I'll try an insider build to see what happens.

Good luck!

**Comment by CraigJamesHamilton** [comment]
Hi,
Just installed 1.78 insider and this issue is resolved, but now I can't set any breakpoints. Time to dig out an old version for me.

**Comment by CraigJamesHamilton** [comment]
Hi,
I've narrowed down the behaviour. Now using the 1.77.3, it only affects one of my projects as the rest are behaving as expected. If I open the failing project, open files, open another project, open the failing project, the failing project has its windows and breakpoints as expected. If I then close the application and reopen the failing project then we lose the open windows etc.

My solution was to remove the .code-workspace file, rename the folder, open the folder within vs code, and then "Save Workspace As..." in the renamed folder. Now it works.

I need help on how to fully remove a workspace from all settings etc to find where this going wrong. Obviously references to the old folder are stuffing things.

**Comment by dbradomaha** [comment]
By any chance are you using Windows Subsystem for Linux?

**Comment by CraigJamesHamilton** [comment]
Hi dbradomaha,
No, I'm using Windows 11.
