### ISSUE TITLE
Visual Studio Code starts up slowly

### ISSUE THREAD

**Issue by Samumancio** [microsoft/vscode#180607]
[prof-UCGG2ap8.extHost.cpuprofile.txt](https://github.com/microsoft/vscode/files/11301774/prof-UCGG2ap8.extHost.cpuprofile.txt)
[prof-UCGG2ap8.main.cpuprofile.txt](https://github.com/microsoft/vscode/files/11301775/prof-UCGG2ap8.main.cpuprofile.txt)
[prof-UCGG2ap8.renderer.cpuprofile.txt](https://github.com/microsoft/vscode/files/11301776/prof-UCGG2ap8.renderer.cpuprofile.txt)
1. :warning: We have copied additional data to your clipboard. Make sure to **paste** here. :warning:
1. :warning: Make sure to **attach** these files from your *home*-directory: :warning:
-`prof-UCGG2ap8.extHost.cpuprofile.txt`
-`prof-UCGG2ap8.main.cpuprofile.txt`
-`prof-UCGG2ap8.renderer.cpuprofile.txt`

**Comment by roblourens** [comment]
Could you also run the "Startup Performance" command and share the numbers here?

**Comment by Samumancio** [comment]
> Could you also run the "Startup Performance" command and share the numbers here?
## Performance Marks

| What                                                            | Duration | Process                   | Info                                                        |
| --------------------------------------------------------------- | -------- | ------------------------- | ----------------------------------------------------------- |
| start => app.isReady                                            | 6941     | [main]                    | initial startup: true                                       |
| nls:start => nls:end                                            | 0        | [main]                    | initial startup: true                                       |
| require(main.bundle.js)                                         | 94       | [main]                    | initial startup: true                                       |
| start crash reporter                                            | 6828     | [main]                    | initial startup: true                                       |
| serve main IPC handle                                           | 3        | [main]                    | initial startup: true                                       |
| create window                                                   | 44       | [main]                    | initial startup: true, state: 0ms, widget: 17ms, show: 27ms |
| app.isReady => window.loadUrl()                                 | 209      | [main]                    | initial startup: true                                       |
| window.loadUrl() => begin to require(workbench.desktop.main.js) | 20069    | [main->renderer]          | NewWindow                                                   |
| require(workbench.desktop.main.js)                              | 278      | [renderer]                | cached data: YES, node_modules took 0ms                     |
| wait for window config                                          | 2        | [renderer]                | -                                                           |
| init storage (global & workspace)                               | 13       | [renderer]                | -                                                           |
| init workspace service                                          | 32       | [renderer]                | -                                                           |
| register extensions & spawn extension host                      | 441      | [renderer]                | -                                                           |
| restore viewlet                                                 | 40       | [renderer]                | workbench.view.explorer                                     |
| restore panel                                                   | 28       | [renderer]                | terminal                                                    |
| restore & resolve visible editors                               | 34493    | [renderer]                | 1: workbench.input.notebook                                 |
| overall workbench load                                          | 34736    | [renderer]                | -                                                           |
| workbench ready                                                 | 62286    | [main->renderer]          | -                                                           |
| renderer ready                                                  | 35070    | [renderer]                | -                                                           |
| shared process connection ready                                 | 23807    | [renderer->sharedprocess] | -                                                           |
| extensions registered                                           | 28381    | [renderer]                | -                                                           |

## Extension Activation Stats

| Extension                                           | Eager | Load Code | Call Activate | Finish Activate | Event                                 | By                                                  |
| --------------------------------------------------- | ----- | --------- | ------------- | --------------- | ------------------------------------- | --------------------------------------------------- |
| vscode.git                                          | true  | 20        | 13            | 4928            | *                                     | vscode.git                                          |
| vscode.git-base                                     | true  | 3         | 0             | 0               | *                                     | vscode.git                                          |
| vscode.github                                       | true  | 3         | 0             | 0               | *                                     | vscode.github                                       |
| albert.TabOut                                       | true  | 5         | 0             | 0               | *                                     | albert.TabOut                                       |
| vscode.debug-auto-launch                            | false | 2         | 1             | 0               | onStartupFinished                     | vscode.debug-auto-launch                            |
| vscode.emmet                                        | false | 5         | 25            | 0               | onLanguage                            | vscode.emmet                                        |
| vscode.extension-editing                            | false | 6         | 1             | 0               | onLanguage:markdown                   | vscode.extension-editing                            |
| vscode.github-authentication                        | false | 19        | 1             | 2               | onAuthenticationRequest:github        | vscode.github-authentication                        |
| vscode.ipynb                                        | false | 6         | 4             | 0               | onNotebookSerializer:jupyter-notebook | vscode.ipynb                                        |
| vscode.markdown-language-features                   | false | 50        | 8             | 10608           | onLanguage:markdown                   | vscode.markdown-language-features                   |
| vscode.markdown-math                                | false | 8         | 0             | 0               | api                                   | vscode.markdown-language-features                   |
| vscode.merge-conflict                               | false | 9         | 1             | 2               | onStartupFinished                     | vscode.merge-conflict                               |
| vscode.microsoft-authentication                     | false | 11        | 1             | 344             | onAuthenticationRequest:microsoft     | vscode.microsoft-authentication                     |
| ms-vscode-remote.remote-wsl-recommender             | false | 10        | 4             | 2               | onStartupFinished                     | ms-vscode-remote.remote-wsl-recommender             |
| formulahendry.code-runner                           | false | 37        | 5             | 1               | onStartupFinished                     | formulahendry.code-runner                           |
| ms-python.isort                                     | false | 20        | 2             | 5               | onLanguage:python                     | ms-python.isort                                     |
| ms-python.python                                    | false | 249       | 13            | 297             | api                                   | ms-toolsai.jupyter                                  |
| ms-python.vscode-pylance                            | false | 109       | 0             | 95              | api                                   | ms-python.python                                    |
| ms-toolsai.jupyter                                  | false | 66        | 52            | 260             | onNotebook:jupyter-notebook           | ms-toolsai.jupyter                                  |
| ms-toolsai.jupyter-renderers                        | false | 3         | 0             | 0               | onNotebook:*                          | ms-toolsai.jupyter-renderers                        |
| ms-toolsai.vscode-jupyter-cell-tags                 | false | 3         | 0             | 0               | onNotebook:jupyter-notebook           | ms-toolsai.vscode-jupyter-cell-tags                 |
| ms-toolsai.vscode-jupyter-slideshow                 | false | 3         | 0             | 0               | onNotebook:jupyter-notebook           | ms-toolsai.vscode-jupyter-slideshow                 |
| ms-vscode-remote.remote-containers                  | false | 44        | 0             | 378             | onStartupFinished                     | ms-vscode-remote.remote-containers                  |
| ms-vscode-remote.remote-wsl                         | false | 15        | 7             | 1               | onStartupFinished                     | ms-vscode-remote.remote-wsl                         |
| ms-vsliveshare.vsliveshare                          | false | 114       | 1             | 720             | onStartupFinished                     | ms-vsliveshare.vsliveshare                          |
| VisualStudioExptTeam.intellicode-api-usage-examples | false | 159       | 4             | 10646           | onLanguage:python                     | VisualStudioExptTeam.intellicode-api-usage-examples |
| VisualStudioExptTeam.vscodeintellicode              | false | 143       | 7             | 12200           | onLanguage:python                     | VisualStudioExptTeam.vscodeintellicode              |

## Raw Perf Marks: main

```
Name	Timestamp	Delta	Total
code/timeOrigin	1682420899525.541	0	0
code/didStartMain	1682420899630	104.458984375	104.458984375
code/willStartCrashReporter	1682420899662	32	136.458984375
code/didStartCrashReporter	1682420906490	6828	6964.458984375
code/mainAppReady	1682420906571	81	7045.458984375
code/willGenerateNls	1682420906573	2	7047.458984375
code/willLoadMainBundle	1682420906585	12	7059.458984375
code/fork/willLoadCode	1682420906603	18	7077.458984375
code/registerFilesystem/file	1682420906671	68	7145.458984375
code/didLoadMainBundle	1682420906679	8	7153.458984375
code/willStartMainServer	1682420906707	28	7181.458984375
code/didStartMainServer	1682420906710	3	7184.458984375
code/willCreateCodeWindow	1682420906735	25	7209.458984375
code/willRestoreCodeWindowState	1682420906735	0	7209.458984375
code/didRestoreCodeWindowState	1682420906735	0	7209.458984375
code/willCreateCodeBrowserWindow	1682420906735	0	7209.458984375
code/didCreateCodeBrowserWindow	1682420906752	17	7226.458984375
code/willMaximizeCodeWindow	1682420906752	0	7226.458984375
code/didMaximizeCodeWindow	1682420906779	27	7253.458984375
code/didCreateCodeWindow	1682420906779	0	7253.458984375
code/willOpenNewWindow	1682420906780	1	7254.458984375
```
## Raw Perf Marks: localExtHost

```
Name	Timestamp	Delta	Total
code/timeOrigin	1682420934890.613	0	0
code/fork/start	1682420934959	68.386962890625	68.386962890625
code/fork/willLoadCode	1682420934980	21	89.386962890625
code/extHost/willConnectToRenderer	1682420935097	117	206.386962890625
code/extHost/didConnectToRenderer	1682420935098	1	207.386962890625
code/extHost/didWaitForInitData	1682420935148	50	257.386962890625
code/extHost/didCreateServices	1682420935149	1	258.386962890625
code/extHost/willWaitForConfig	1682420935163	14	272.386962890625
code/extHost/didWaitForConfig	1682420935172	9	281.386962890625
code/extHost/didInitAPI	1682420935215	43	324.386962890625
code/extHost/didInitProxyResolver	1682420935221	6	330.386962890625
code/extHost/ready	1682420935221	0	330.386962890625
code/extHost/willLoadExtensionCode/vscode.ipynb	1682420935222	1	331.386962890625
code/extHost/didLoadExtensionCode/vscode.ipynb	1682420935228	6	337.386962890625
code/extHost/willLoadExtensionCode/vscode.github-authentication	1682420935229	1	338.386962890625
code/extHost/didLoadExtensionCode/vscode.github-authentication	1682420935248	19	357.386962890625
code/extHost/willActivateExtension/vscode.ipynb	1682420935248	0	357.386962890625
code/extHost/didActivateExtension/vscode.ipynb	1682420935252	4	361.386962890625
code/extHost/willActivateExtension/vscode.github-authentication	1682420935253	1	362.386962890625
code/extHost/didActivateExtension/vscode.github-authentication	1682420935259	6	368.386962890625
code/extHost/willLoadExtensionCode/vscode.git-base	1682420935265	6	374.386962890625
code/extHost/didLoadExtensionCode/vscode.git-base	1682420935268	3	377.386962890625
code/extHost/willLoadExtensionCode/albert.TabOut	1682420935273	5	382.386962890625
code/extHost/didLoadExtensionCode/albert.TabOut	1682420935278	5	387.386962890625
code/extHost/willActivateExtension/vscode.git-base	1682420935593	315	702.386962890625
code/extHost/didActivateExtension/vscode.git-base	1682420935593	0	702.386962890625
code/extHost/willActivateExtension/albert.TabOut	1682420937546	1953	2655.386962890625
code/extHost/didActivateExtension/albert.TabOut	1682420937546	0	2655.386962890625
code/extHost/willLoadExtensionCode/vscode.git	1682420937554	8	2663.386962890625
code/extHost/didLoadExtensionCode/vscode.git	1682420937574	20	2683.386962890625
code/extHost/willLoadExtensionCode/vscode.github	1682420937575	1	2684.386962890625
code/extHost/didLoadExtensionCode/vscode.github	1682420937578	3	2687.386962890625
code/extHost/willLoadExtensionCode/vscode.microsoft-authentication	1682420937582	4	2691.386962890625
code/extHost/didLoadExtensionCode/vscode.microsoft-authentication	1682420937593	11	2702.386962890625
code/extHost/willLoadExtensionCode/ms-toolsai.jupyter	1682420937593	0	2702.386962890625
code/extHost/didLoadExtensionCode/ms-toolsai.jupyter	1682420937659	66	2768.386962890625
code/extHost/willLoadExtensionCode/ms-toolsai.vscode-jupyter-cell-tags	1682420937659	0	2768.386962890625
code/extHost/didLoadExtensionCode/ms-toolsai.vscode-jupyter-cell-tags	1682420937662	3	2771.386962890625
code/extHost/willLoadExtensionCode/ms-toolsai.vscode-jupyter-slideshow	1682420937662	0	2771.386962890625
code/extHost/didLoadExtensionCode/ms-toolsai.vscode-jupyter-slideshow	1682420937665	3	2774.386962890625
code/extHost/willLoadExtensionCode/ms-toolsai.jupyter-renderers	1682420937665	0	2774.386962890625
code/extHost/didLoadExtensionCode/ms-toolsai.jupyter-renderers	1682420937668	3	2777.386962890625
code/extHost/willActivateExtension/vscode.git	1682420937668	0	2777.386962890625
code/extHost/willActivateExtension/vscode.github	1682420937686	18	2795.386962890625
code/extHost/didActivateExtension/vscode.github	1682420937686	0	2795.386962890625
code/extHost/willActivateExtension/vscode.microsoft-authentication	1682420937688	2	2797.386962890625
code/extHost/willActivateExtension/ms-toolsai.jupyter	1682420937693	5	2802.386962890625
code/extHost/didActivateExtension/ms-toolsai.jupyter	1682420938008	315	3117.386962890625
code/extHost/willActivateExtension/ms-toolsai.vscode-jupyter-cell-tags	1682420938010	2	3119.386962890625
code/extHost/didActivateExtension/ms-toolsai.vscode-jupyter-cell-tags	1682420938010	0	3119.386962890625
code/extHost/willActivateExtension/ms-toolsai.vscode-jupyter-slideshow	1682420938011	1	3120.386962890625
code/extHost/didActivateExtension/ms-toolsai.vscode-jupyter-slideshow	1682420938011	0	3120.386962890625
code/extHost/willActivateExtension/ms-toolsai.jupyter-renderers	1682420938011	0	3120.386962890625
code/extHost/didActivateExtension/ms-toolsai.jupyter-renderers	1682420938011	0	3120.386962890625
code/extHost/didActivateExtension/vscode.microsoft-authentication	1682420938033	22	3142.386962890625
code/extHost/willLoadExtensionCode/ms-python.python	1682420938034	1	3143.386962890625
code/extHost/didLoadExtensionCode/ms-python.python	1682420938283	249	3392.386962890625
code/extHost/didActivateExtension/vscode.git	1682420942609	4326	7718.386962890625
```
## Raw Perf Marks: renderer

```
Name	Timestamp	Delta	Total
code/timeOrigin	1682420906775	0	0
code/didStartRenderer	1682420926846	20071	20071
code/willWaitForWindowConfig	1682420926846	0	20071
code/didWaitForWindowConfig	1682420926848	2	20073
code/willShowPartsSplash	1682420926848	0	20073
code/didShowPartsSplash	1682420926848	0	20073
code/willLoadWorkbenchMain	1682420926849	1	20074
code/didLoadWorkbenchMain	1682420927127	278	20352
code/registerFilesystem/file	1682420927142	15	20367
code/registerFilesystem/vscode-userdata	1682420927142	0	20367
code/willInitWorkspaceService	1682420927144	2	20369
code/willInitStorage	1682420927145	1	20370
code/didInitStorage	1682420927158	13	20383
code/willInitUserConfiguration	1682420927164	6	20389
code/didInitUserConfiguration	1682420927168	4	20393
code/willInitWorkspaceConfiguration	1682420927168	0	20393
code/didInitWorkspaceConfiguration	1682420927176	8	20401
code/didInitWorkspaceService	1682420927176	0	20401
code/willStartWorkbench	1682420927180	4	20405
code/LifecyclePhase/Ready	1682420927182	2	20407
code/willCreateWorkbenchContributions/1	1682420927225	43	20450
code/didCreateWorkbenchContributions/1	1682420927252	27	20477
code/willCreateWorkbenchContributions/2	1682420927252	0	20477
code/registerFilesystem/trustedDomains	1682420927254	2	20479
code/registerFilesystem/vscode-interactive	1682420927256	2	20481
code/registerFilesystem/vscode-local-history	1682420927259	3	20484
code/didCreateWorkbenchContributions/2	1682420927262	3	20487
code/willCreatePart/workbench.parts.titlebar	1682420927265	3	20490
code/didRemovePartsSplash	1682420927275	10	20500
code/didCreatePart/workbench.parts.titlebar	1682420927292	17	20517
code/willCreatePart/workbench.parts.banner	1682420927292	0	20517
code/didCreatePart/workbench.parts.banner	1682420927293	1	20518
code/willCreatePart/workbench.parts.activitybar	1682420927293	0	20518
code/didCreatePart/workbench.parts.activitybar	1682420927299	6	20524
code/willCreatePart/workbench.parts.sidebar	1682420927299	0	20524
code/didCreatePart/workbench.parts.sidebar	1682420927300	1	20525
code/willCreatePart/workbench.parts.editor	1682420927300	0	20525
code/didCreatePart/workbench.parts.editor	1682420927346	46	20571
code/willCreatePart/workbench.parts.panel	1682420927346	0	20571
code/didCreatePart/workbench.parts.panel	1682420927347	1	20572
code/willCreatePart/workbench.parts.auxiliarybar	1682420927347	0	20572
code/didCreatePart/workbench.parts.auxiliarybar	1682420927348	1	20573
code/willCreatePart/workbench.parts.statusbar	1682420927348	0	20573
code/didCreatePart/workbench.parts.statusbar	1682420927349	1	20574
code/willRestoreEditors	1682420927423	74	20648
code/restoreEditors/editorGroupsReady	1682420927429	6	20654
code/willRestoreViewlet	1682420927429	0	20654
code/willRestorePanel	1682420927441	12	20666
code/restoreEditors/editorsToOpenResolved	1682420927468	27	20693
code/didRestoreViewlet	1682420927469	1	20694
code/didRestorePanel	1682420927469	0	20694
code/willRegisterExplorerViews	1682420927469	0	20694
code/willResolveExplorer	1682420927490	21	20715
code/didRegisterExplorerViews	1682420927492	2	20717
code/willLoadExtensions	1682420927570	78	20795
code/didResolveExplorer	1682420927677	107	20902
code/willHandleExtensionPoints	1682420927877	200	21102
code/willHandleExtensionPoint/configurationDefaults	1682420927877	0	21102
code/didHandleExtensionPoint/configurationDefaults	1682420927878	1	21103
code/willHandleExtensionPoint/configuration	1682420927878	0	21103
code/didHandleExtensionPoint/configuration	1682420927900	22	21125
code/willHandleExtensionPoint/jsonValidation	1682420927900	0	21125
code/didHandleExtensionPoint/jsonValidation	1682420927900	0	21125
code/willHandleExtensionPoint/debuggers	1682420927900	0	21125
code/didHandleExtensionPoint/debuggers	1682420927911	11	21136
code/willHandleExtensionPoint/breakpoints	1682420927911	0	21136
code/didHandleExtensionPoint/breakpoints	1682420927912	1	21137
code/willHandleExtensionPoint/notebooks	1682420927912	0	21137
code/didHandleExtensionPoint/notebooks	1682420927912	0	21137
code/willHandleExtensionPoint/notebookRenderer	1682420927912	0	21137
code/didHandleExtensionPoint/notebookRenderer	1682420927913	1	21138
code/willHandleExtensionPoint/notebookPreload	1682420927913	0	21138
code/didHandleExtensionPoint/notebookPreload	1682420927914	1	21139
code/willHandleExtensionPoint/problemPatterns	1682420927914	0	21139
code/didHandleExtensionPoint/problemPatterns	1682420927914	0	21139
code/willHandleExtensionPoint/problemMatchers	1682420927914	0	21139
code/didHandleExtensionPoint/problemMatchers	1682420927916	2	21141
code/willHandleExtensionPoint/taskDefinitions	1682420927916	0	21141
code/didHandleExtensionPoint/taskDefinitions	1682420927919	3	21144
code/willHandleExtensionPoint/terminal	1682420927919	0	21144
code/didHandleExtensionPoint/terminal	1682420927919	0	21144
code/willHandleExtensionPoint/terminalQuickFixes	1682420927919	0	21144
code/didHandleExtensionPoint/terminalQuickFixes	1682420927920	1	21145
code/willHandleExtensionPoint/walkthroughs	1682420927920	0	21145
code/didHandleExtensionPoint/walkthroughs	1682420927920	0	21145
code/willHandleExtensionPoint/commands	1682420927920	0	21145
code/didHandleExtensionPoint/commands	1682420927925	5	21150
code/willHandleExtensionPoint/submenus	1682420927925	0	21150
code/didHandleExtensionPoint/submenus	1682420927925	0	21150
code/willHandleExtensionPoint/menus	1682420927925	0	21150
code/didHandleExtensionPoint/menus	1682420927943	18	21168
code/willHandleExtensionPoint/authentication	1682420927943	0	21168
code/didHandleExtensionPoint/authentication	1682420927944	1	21169
code/willHandleExtensionPoint/languages	1682420927944	0	21169
code/didHandleExtensionPoint/languages	1682420927952	8	21177
code/willHandleExtensionPoint/customEditors	1682420927952	0	21177
code/didHandleExtensionPoint/customEditors	1682420927952	0	21177
code/willHandleExtensionPoint/codeActions	1682420927952	0	21177
code/didHandleExtensionPoint/codeActions	1682420927952	0	21177
code/willHandleExtensionPoint/viewsWelcome	1682420927952	0	21177
code/didHandleExtensionPoint/viewsWelcome	1682420927952	0	21177
code/willHandleExtensionPoint/resourceLabelFormatters	1682420927952	0	21177
code/didHandleExtensionPoint/resourceLabelFormatters	1682420927952	0	21177
code/willHandleExtensionPoint/grammars	1682420927952	0	21177
code/didHandleExtensionPoint/grammars	1682420927956	4	21181
code/willHandleExtensionPoint/colors	1682420927956	0	21181
code/didHandleExtensionPoint/colors	1682420927956	0	21181
code/willHandleExtensionPoint/semanticTokenTypes	1682420927956	0	21181
code/didHandleExtensionPoint/semanticTokenTypes	1682420927957	1	21182
code/willHandleExtensionPoint/semanticTokenModifiers	1682420927957	0	21182
code/didHandleExtensionPoint/semanticTokenModifiers	1682420927957	0	21182
code/willHandleExtensionPoint/semanticTokenScopes	1682420927957	0	21182
code/didHandleExtensionPoint/semanticTokenScopes	1682420927957	0	21182
code/willHandleExtensionPoint/snippets	1682420927957	0	21182
code/didHandleExtensionPoint/snippets	1682420927957	0	21182
code/willHandleExtensionPoint/keybindings	1682420927957	0	21182
code/didHandleExtensionPoint/keybindings	1682420927965	8	21190
code/willHandleExtensionPoint/themes	1682420927965	0	21190
code/didHandleExtensionPoint/themes	1682420927966	1	21191
code/willHandleExtensionPoint/iconThemes	1682420927966	0	21191
code/didHandleExtensionPoint/iconThemes	1682420927966	0	21191
code/willHandleExtensionPoint/continueEditSession	1682420927966	0	21191
code/didHandleExtensionPoint/continueEditSession	1682420927966	0	21191
code/willHandleExtensionPoint/viewsContainers	1682420927966	0	21191
code/didHandleExtensionPoint/viewsContainers	1682420927992	26	21217
code/willHandleExtensionPoint/views	1682420927992	0	21217
code/didHandleExtensionPoint/views	1682420928004	12	21229
code/willHandleExtensionPoint/remoteHelp	1682420928004	0	21229
code/didHandleExtensionPoint/remoteHelp	1682420928004	0	21229
code/didHandleExtensionPoints	1682420928004	0	21229
code/didLoadExtensions	1682420928011	7	21236
code/willConnectSharedProcess	1682420929153	1142	22378
code/LifecyclePhase/Restored	1682420929516	363	22741
code/willCreateWorkbenchContributions/3	1682420929517	1	22742
code/registerFilesystem/vscode-edit-sessions	1682420929570	53	22795
code/didCreateWorkbenchContributions/3	1682420929663	93	22888
code/LifecyclePhase/Eventually	1682420932018	2355	25243
code/willCreateWorkbenchContributions/4	1682420932020	2	25245
code/didCreateWorkbenchContributions/4	1682420932044	24	25269
code/registerFilesystem/git	1682420938327	6283	31552
code/registerFilesystem/vsls	1682420943538	5211	36763
code/didConnectSharedProcess	1682420952960	9422	46185
code/restoreEditors/editorGroupsRestored	1682420961916	8956	55141
code/didRestoreEditors	1682420961916	0	55141
code/didStartWorkbench	1682420961916	0	55141
```

## Node Cached Data Stats


### cached data used


### cached data missed


### cached data rejected


### cached data created (lazy, might need refreshes)

**Comment by roblourens** [comment]
Thanks. In my interpretation this doesn't point at anything in particular, but it does look extremely slow. 

Are you using any antivirus? Does disabling it make a difference? 

Does anything in https://github.com/microsoft/vscode/issues/22087#issuecomment-879457090 sound relevant?

What OS?

**Comment by Samumancio** [comment]
Thanks, it  worked for me disabling the antivirus
