### ISSUE TITLE
Hard to stop GitHub auth dance

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#180697]
1. Attempt to sign in to GitHub via GHPRI, click `Allow`
2. Click `Cancel`

🐛 I now have to click twice `No` and once `Cancel` to stop the notification stream. I expected no extra clicks after step (2).

https://user-images.githubusercontent.com/22350/234018103-1757f6a7-7c07-4bab-b9c7-6dc41f8fd451.mov

**Comment by TylerLeonhardt** [comment]
3rd notification is my bug, 4th would be GHPR (@alexr00). Here's the PR for my side ^^^

**Comment by andreamah** [comment]
Just verified this issue and seems okay, but I also noticed this:

1. Click to sign into github for an extension that needs it.
<img width="375" alt="image" src="https://github.com/microsoft/vscode/assets/31675041/315517af-5719-418e-a7ff-9ea4fc837e21">

2. press cancel on the notification in vscode.
<img width="355" alt="image" src="https://github.com/microsoft/vscode/assets/31675041/ada17170-85b0-4bc4-a5c4-49abcfef6e99">

3. still go through the steps to authorize github in the browser and open the link that they give to open in vscode.
4. nothing happens :bug:. I get that nothing should change, but should there be a warning?

**Comment by TylerLeonhardt** [comment]
@andreamah what would you like to see in the warning in this case?

**Comment by andreamah** [comment]
I'm not too sure. The state just leaves me sorta questioning whether the auth did anything I think. But looking at it again, I see that it doesn't do anything if it succeeds, so I guess silently failing also works?

**Comment by TylerLeonhardt** [comment]
I think I'd like air on the side of not annoying the user with yet another notification, so I think the silence is ok.
