### ISSUE TITLE
editor.hover.delay doesn't affect debugger hovering, only language server hovering

### ISSUE THREAD

**Issue by MetalSlime0** [microsoft/vscode#180621]
Type: <b>Bug</b>

Set editor.hover.delay to 3000 (3 seconds). While debugging, hold Alt and hover over a keyword. It will correctly take 3 seconds to display the hover information from the language server. Then, release Alt and hover over a variable. It always takes about 3/4 of a second to evaluate the value regardless of the setting.

(This is frustratingly slow for me.)

VS Code version: Code 1.77.3 (704ed70d4fd1c6bd6342c436f1ede30d1cff4710, 2023-04-12T09:16:02.548Z)
OS version: Windows_NT x64 10.0.19042
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 9 5950X 16-Core Processor             (32 x 3394)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|63.94GB (27.65GB free)|
|Process Argv|--crash-reporter-id bbc83cb3-8859-43b9-93a1-5337a381d19f|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscorecescf:30445987
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
nodejswelcome1:30587005
282f8724:30602487
pyind779:30671433
89544117:30613380
pythonsymbol12:30671437
vsccsb:30705552
azdwalk:30721579
pythonms35:30701012
pythonfmttext:30716742

```

</details>

**Comment by roblourens** [comment]
We do look at that setting, but we multiply by 2, I didn't realize that. @isidorn do you remember why you made this change, is it just that the debug hover can be very large and you don't want it to be too touchy?

https://github.com/microsoft/vscode/commit/5e5ae15b22c6617f22923edce6e359897cac0f83

**Comment by MetalSlime0** [comment]
Multiplying by 2 doesn't explain why it's still less than a second when I set it to 3000 though.

**Comment by isidorn** [comment]
@roblourens yes, the idea was that debug hover can be very large and requires user interaction. So we make it as twice as slow as the editor hover.
Just a naive heuristic, feel free to change :)

**Comment by MetalSlime0** [comment]
No, I didn't do that, so maybe that's it. If that can't easily be changed, the description of the setting should probably explain that a restart is necessary.

**Comment by roblourens** [comment]
Can you let me know whether the general delay behavior is ok with you after a reload? I think I would like to leave the heuristic, it seems fine to me and adding a new setting for the debug hover delay would be overkill to me.

The restart only applies to where this setting is used for debug, so I wouldn't describe it in the setting description, but maybe that can be resolved.

**Comment by MetalSlime0** [comment]
Looks like it's correctly 6 seconds after a reload.

Would you consider making the 2x heuristic itself into a setting? I'd really just like to make it responsive for myself. I'd also think a better heuristic might be a fixed additional length of time, like an additional 100ms or something, but it doesn't matter to me if I can discover it and turn it off. Is it common for users to hover their mouse over an identifier for a length of time *between*, say, 100 and 1000 milliseconds? I figure once the mouse stops it's probably not gonna start moving again for a while, and at that point it's just a question of how responsive the program feels. But this is just my opinion and I don't have any real data to back it up of course.

My only problem with the restart being required is that it prevented me from realizing this setting even has any effect in debug, so it makes the setting just seem like it doesn't work. I was lucky to even think of the idea that it might be different between the debugger and language server; my initial impression was that the setting had no effect at all. Now that I know how it works it doesn't matter for me personally, of course.

**Comment by Ivelate** [comment]
I was having the same issue - the value evaluation in debug felt very slow to me. I tried everything, including modifying the hover delay. However it felt like it had no effect so I returned it back to its original value - I would have never thought about needing to restart. Good thing I found this thread.
Maybe the need to restart should be clearly specified in some way?

**Comment by mindThomas** [comment]
Is it possible to avoid/configure this factor of 3 in the delay for those who would want to see the variable content quickly while hovering?

**Comment by connor4312** [comment]
Made some changes here to:

1. Let the delay be changed without a reload
2. Improve the heuristic by basing the factor on the setting. Now the `*2` factor is applied for a hover delay between 0 and 300ms (the default hover value, so default behavior is unchanged), after which it reduces to `*1` by 900ms.
