### ISSUE TITLE
slow working of VS code in my pc.

### ISSUE THREAD

**Issue by SHASHIKAUSHALSINGH** [microsoft/vscode#180657]
Type: <b>Performance Issue</b>

whenever I open the VS CODE in my laptop it takes a lot of time as compare to other apps.
It takes a time to run a program .I reinstall the VS code again but problem remain the  same.
please help me out to execute my programes.

my pc is samsung galaxy book 2 .

VS Code version: Code 1.77.3 (704ed70d4fd1c6bd6342c436f1ede30d1cff4710, 2023-04-12T09:16:02.548Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|12th Gen Intel(R) Core(TM) i5-1235U (12 x 2496)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.71GB (7.99GB free)|
|Process Argv|--crash-reporter-id 61330abe-000c-4dcc-9e7b-70884396e20c|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	    95	 25384	code main
    0	   182	   932	   gpu-process
    0	    46	  2476	   utility-network-service
    0	    26	  8896	   crashpad-handler
    0	   103	 12468	shared-process
    0	    88	 13456	     ptyHost
    0	     6	 10100	       console-window-host (Windows internal process)
    0	     6	 21968	       console-window-host (Windows internal process)
    0	    68	 28540	       C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe -noexit -command "try { . \"c:\Users\Shashi Kaushal Singh\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\contrib\terminal\browser\media\shellIntegration.ps1\" } catch {}"
    0	    62	 32808	       C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe -noexit -command "try { . \"c:\Users\Shashi Kaushal Singh\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\contrib\terminal\browser\media\shellIntegration.ps1\" } catch {}"
    0	    79	 18736	fileWatcher [1]
    0	   142	 21520	extensionHost [1]
    0	    37	 10540	     "c:\Users\Shashi Kaushal Singh\.vscode\extensions\ms-vscode.cpptools-1.14.5-win32-x64\bin\cpptools.exe"
    0	    10	 20040	       console-window-host (Windows internal process)
    0	     4	 29972	       "c:\Users\Shashi Kaushal Singh\.vscode\extensions\ms-vscode.cpptools-1.14.5-win32-x64\bin\cpptools.exe"
    0	    38	 33128	         "c:\Users\Shashi Kaushal Singh\.vscode\extensions\ms-vscode.cpptools-1.14.5-win32-x64/bin/cpptools-srv.exe" 10540 {5F0C5C98-FE9F-4572-80D5-4A7EF8040FC1}
    0	    10	  4824	           console-window-host (Windows internal process)
    0	    78	 17564	     electron-nodejs ("C:\Users\Shashi Kaushal Singh\AppData\Local\Programs\Microsoft VS Code\Code.exe" --ms-enable-electron-run-as-node "c:\Users\Shashi Kaushal Singh\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\json-language-features\server\dist\node\jsonServerMain" --node-ipc --clientProcessId=21520)
    0	    87	 29624	window [2] (Issue Reporter)
    0	   194	 32728	window [1] (sqroot.cpp - dsa course - Visual Studio Code)
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (sqroot.cpp - dsa course - Visual Studio Code)
|    Folder (dsa course): 54 files
|      File types: cpp(25) exe(22) json(2)
|      Conf files: settings.json(1) tasks.json(1);
```

</details>
<details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
code-runner|for|0.12.0
isort|ms-|2022.8.0
python|ms-|2023.6.1
vscode-pylance|ms-|2023.4.30
jupyter|ms-|2023.3.1201040234
jupyter-keymap|ms-|1.1.0
jupyter-renderers|ms-|1.0.15
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-slideshow|ms-|0.1.5
cmake-tools|ms-|1.14.30
cpptools|ms-|1.14.5
cpptools-extension-pack|ms-|1.3.0
LiveServer|rit|5.7.9
cmake|twx|0.0.17

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
nodejswelcome1cf:30587006
282f8724:30602487
pyind779:30671433
f6dab269:30613381
pythonsymbol12:30671437
2i9eh265:30646982
vsccsb:30705552
azdwalk:30721579
pythonms35:30701012
pythonfmttext:30716742
pythonclientmvcf:30713944

```

</details>

**Comment by deepak1556** [comment]
Can you follow the steps in https://github.com/microsoft/vscode/issues/178733#issuecomment-1500812938 and exclude the `code.exe` binary.

Merging to https://github.com/microsoft/vscode/issues/178962

**Comment by SHASHIKAUSHALSINGH** [comment]
Thank you my problem is solve.
