### ISSUE TITLE
[scss] support interpolation in layer name

### ISSUE THREAD

**Issue by ngdangtu-vn** [microsoft/vscode#180631]
This feature request is about new CSS [at-rule call `@layer`](https://developer.mozilla.org/en-US/docs/Web/CSS/@layer). This at-rule can be considerate available for public since it is very close to [90% supported browsers](https://caniuse.com/css-cascade-layers). But the current vscode `1.77.3` doesn't support `@layer` keyword and constantly fire error every time I use it.

Language that needs to support this feature: CSS, SASS/SCSS, LESS

**Comment by gjsjohnmurray** [comment]
#161842 implies this should already be handled. Please check its related issues, and also that extensions you may be using are up to date.

**Comment by ngdangtu-vn** [comment]
![Screenshot_20230423_133826](https://user-images.githubusercontent.com/68631458/233824079-6021e20b-6575-4925-8a3e-e9f6eda5cf9a.png)

I don't think I use any extensions that affect syntax highlight. Could it be because I'm using Linux?

Just double check on plain CSS, it works now. But for SCSS it doesn't. Can I ask for SCSS support in here since it also got native support from vscode?

![image](https://user-images.githubusercontent.com/68631458/233824445-01de0e17-cdee-4ca3-aba7-4b7c0daedae0.png)

**Comment by aeschli** [comment]
@ngdangtu-vn Please paste the small code sample that doesn't work.

**Comment by ngdangtu-vn** [comment]
Sure

```SCSS
/**
 * Cascade Threshold
 */
@mixin module-on($min-width, $layer, $selector)
{
	@layer #{$layer}
	{
		@media screen and (min-width: #{$min-width})
		{
			#{$selector}
			{
				@content;
			}
		}
	}
}
```

```SCSS
@import 'https://fonts.googleapis.com/css2?family=Cinzel+Decorative:wght@400;700&display=swap' layer(font);
```

All the error underlines in those code above will display once you modify the code file. If you save it and close then reopen, the error will disappear. (Of course it appears in the Problems panel too)

**Comment by Alexand3r** [comment]
Here's a more simple reproducible example where it throws this error with the `@layer` in .scss files (.css files have no issues)

```css
@layer bootstrap;
@import url('bootstrap/scss/bootstrap.scss') layer(bootstrap);
```

`{ expectedscss(css-lcurlyexpected)`

![image](https://github.com/microsoft/vscode/assets/988056/9fbfc5ba-60c2-4bd5-8f86-e1e358d27ec0)

**Comment by aeschli** [comment]
Fixed by https://github.com/microsoft/vscode-css-languageservice/pull/370

**Comment by TylerLeonhardt** [comment]
No longer errors, verified ✅ 

`@layer` in 
```scss
@layer bootstrap;
@import url('bootstrap/scss/bootstrap.scss') layer(bootstrap);
```
not being highlighted seems like a syntax highlighting issue...

I'll open a new issue for that.

**Comment by justschen** [comment]
@aeschli was this accidentally reopened? deferring to https://github.com/microsoft/vscode-css/issues/24 and closing this one on this milestone
