### ISSUE TITLE
Could Let's select to update

### ISSUE THREAD

**Issue by osjn** [Microsoft/vscode#1806]
Because of some issues happened after updating perhaps, could let's select to update? So we can install the last stable version.

**Comment by joaomoreno** [comment]
Thanks for filing this. I find it hard to understand what you mean by *could let's select to update*. Can you provide more details, or an example?

**Comment by osjn** [comment]
After Code checking updates, let's select whether or not to download the new version installer.

**Comment by joaomoreno** [comment]
We won't support this, as we want to keep our users on a steady update channel.
