### ISSUE TITLE
esbuild watch cannot be used as preLaunchTask

### ISSUE THREAD

**Issue by tekumara** [microsoft/vscode#180641]
Type: <b>Bug</b>

esbuild watch cannot be used as preLaunchTask

![CleanShot 2023-04-23 at 21 38 37@2x](https://user-images.githubusercontent.com/125105/233837582-d30d87b6-0bed-4428-a8f7-22fdb5dc5a30.png)

I've configured the following scripts:
```json
    "esbuild-base": "esbuild ./src/extension.ts --bundle --outfile=out/main.js --external:vscode --format=cjs --platform=node",
    "esbuild": "npm run esbuild-base -- --sourcemap",
    "esbuild-watch": "npm run esbuild-base -- --sourcemap --watch",
    "compile": "tsc -p ./",
    "watch": "tsc -watch -p ./",
```    

When using `watch` as a preLaunchTask is completes (see ✔️ in the screenshot above).

When using `esbuild-watch` as a preLaunchTask it never completes (see the rotating circle in the screenshot above). Therefore the launch configuration never starts.

VS Code version: Code 1.77.3 (Universal) (704ed70d4fd1c6bd6342c436f1ede30d1cff4710, 2023-04-12T09:19:37.325Z)
OS version: Darwin arm64 22.4.0
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|20, 16, 15|
|Memory (System)|32.00GB (0.44GB free)|
|Process Argv|--disable-extensions --crash-reporter-id 1420092c-d4ca-4cab-85bb-af47402199b1|
|Screen Reader|no|
|VM|0%|

</details>Extensions disabled<details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
nodejswelcome1cf:30587006
3biah626:30602489
pyind779:30671433
f6dab269:30613381
pythonsymbol12:30671437
azdwalk:30721579
pythonms35:30701012
pythonfmttextcf:30716743
pythonclientmvcf:30713944

```

</details>

**Comment by roblourens** [comment]
I think you will have to configure the task in tasks.json in order for vscode to detect when it has completed a build

**Comment by tekumara** [comment]
Oh yes, so here's what I have in tasks.json:
```json
// See https://go.microsoft.com/fwlink/?LinkId=733558
// for the documentation about the tasks.json format
{
	"version": "2.0.0",
	"tasks": [
		{
			"type": "npm",
			"script": "watch",
			"problemMatcher": "$tsc-watch",
			"isBackground": true,
			"presentation": {
				"reveal": "never"
			},
			"group": "build",
		},
		{
			"type": "npm",
			"script": "esbuild-watch",
			"problemMatcher": "$tsc",
			"group": "build",
			"presentation": {
				"reveal": "never"
			},
			"isBackground": true,
		}
	]
}
```

**Comment by meganrogge** [comment]
I think you'd need a `dependsOn` for that to work

**Comment by tekumara** [comment]
Maybe I'm missing something obvious but I'm still not sure what to do here...

The `watch` task completes (see ✔️ in the screenshot above), but I can't see why the `esbuild-watch` doesn't (see the rotating circle in the screenshot above) ... even though their task definitions are basically the same.

**Comment by meganrogge** [comment]
looks like a different problem matcher, so maybe there's an issue with that

**Comment by tekumara** [comment]
Oh thanks you're right.. that was actually a editing error when I copied over my tasks.json ... 

I've now tried it with the same problemMatcher for both, ie: `$tsc-watch`. The only difference I can see is the output of the commands.

esbuild-watch (doesn't complete):

```
 *  Executing task: npm run watch 

pyenv shell 3.9

> typos-vscode@0.0.1 watch
> npm run esbuild-base -- --sourcemap --watch


> typos-vscode@0.0.1 esbuild-base
> esbuild ./src/extension.ts --bundle --outfile=out/main.js --external:vscode --format=cjs --platform=node "--sourcemap" "--watch"

[watch] build finished, watching for changes...
```

watch (completes):
```
[1:32:00 PM] Starting compilation in watch mode...

[1:32:01 PM] Found 0 errors. Watching for file changes.
```

**Comment by meganrogge** [comment]
the only difference is the script that runs, so i'd check what `esbuild-watch` is doing and try to run that manually instead of as a task
