### ISSUE TITLE
Explorer pane shows npm scripts as npm scripts: npm scripts

### ISSUE THREAD

**Issue by yamachu** [microsoft/vscode#180673]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.78.0-insider 3a69e153f6c68b2b855fb2f1e5bdb798a16a1ee4
- OS Version: macOS 13.3.1

Steps to Reproduce:

1. Open Explorer pane
2. Show `npm scripts` tab

Insiders (Version: 1.78.0)

<img width="256" alt="スクリーンショット 2023-04-24 17 02 04" src="https://user-images.githubusercontent.com/1955233/233935563-fb0da85c-0811-4023-8911-47f865a60a8e.png">

Stable (Version: 1.77.3)

<img width="305" alt="スクリーンショット 2023-04-24 17 02 14" src="https://user-images.githubusercontent.com/1955233/233935575-1df7d307-1861-4d6e-9c6d-b04fc10aa046.png">

**Comment by aiday-mar** [comment]
Hi @lramos15, I think you are working on the explorer, if I am not mistaken?

**Comment by lramos15** [comment]
@yamachu Does `CMD + SHIFT + P` -> `Reset View Locations` fix it?

**Comment by yamachu** [comment]
@lramos15 Thanks for suggesting a solution!
This seems to have been resolved.
