### ISSUE TITLE
[Git] "Dscard All Changes" and "Discard Changes" should provide clearer warnings

### ISSUE THREAD

**Issue by Demonese** [microsoft/vscode#180669]
It should clearly remind users that this operation will delete "files in the folder". A friend of mine mistakenly believed that it would "remove files from the git repository" and unfortunately caused the files to be lost.

**Comment by lszomoru** [comment]
Thank you very much for the feedback. 
I think that the message in the current dialog is pretty clear that data will be lost:

<img width="265" alt="image" src="https://github.com/microsoft/vscode/assets/3372902/28fcce36-802b-496a-a9ac-8c6bec5498ab">
