### ISSUE TITLE
[Accessibility]: Present content first in References Treeview

### ISSUE THREAD

**Issue by jooyoungseo** [microsoft/vscode#180653]
CC @meganrogge @isidorn

1. Create `test.py` with the following content:

  ``` python
  x = 1
  x = 2
  x = 3
  ```

1. Locate your cursor at `x` and press Shift+F12.

## Current Output

> symbol in test.py on line 1 at column 1, x = 1

## Suggested Output

> x = 1 in test.py on line 1 at column 1

* Note: the word 'symbol' is not needed here.

**Comment by isidorn** [comment]
Good feedback for references tree. I think this is a low hanging change in the AccessibilityTreeProvider.
Assigning to @jrieken

**Comment by jrieken** [comment]
Code pointer: https://github.com/microsoft/vscode/blob/3059063b805ed0ac10a6d9539e213386bfcfb852/extensions/references-view/src/references/model.ts#L299

**Comment by jooyoungseo** [comment]
@jrieken  and @meganrogge While this seems a good chance for community contribution, accessibility issues and its impact needs more attention than people think and must not be put on the back burner. This issue has been long-standing issue and not trivial, negatively impacting the productivity to those having to consume information via speech.

**Comment by meganrogge** [comment]
I agree @jooyoungseo - what github does not show you is that I had moved this to my `planning` category of my Github project so I will work on it soon

**Comment by jooyoungseo** [comment]
Thanks, @meganrogge ! I apologize if I was out of line. I had to act as an accessibility evangelist.

**Comment by meganrogge** [comment]
All good 😄
