### ISSUE TITLE
Test: new proposed API to save an editor

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#180666]
Refs: https://github.com/microsoft/vscode/issues/178713

- [x] anyOS @sbatten
- [x] anyOS @alexr00

Complexity: 3

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23180666%0A%0A&assignees=bpasero)

---

There is a new API proposal to save an editor by its `Uri`: [vscode.proposed.saveEditor.d.ts](https://github.com/microsoft/vscode/blob/3a69e153f6c68b2b855fb2f1e5bdb798a16a1ee4/src/vscode-dts/vscode.proposed.saveEditor.d.ts#L10-L33).

Create a new extension (for example via `npx yo code`) with the proposed API enabled:
* Add a proposed API:
  * First add the proposed API to the `package.json` (see below)
  * Then run `npx vscode-dts dev` to get the typings
```json
	"enabledApiProposals": [
		"saveEditor"
	],
```

Play with and use the new methods `workspace.save` and `workspace.saveAs` and verify they work as for normal editors as well as untitled editors. Specifically the returned result `Thenable<Uri | undefined>` matches expectations.

**Comment by alexr00** [comment]
Works great! It might be nice if the API threw a specific error when the file isn't open.
