### ISSUE TITLE
[REQ] File nesting - make indentation less chaotic

### ISSUE THREAD

**Issue by jrj2211** [microsoft/vscode#180654]
I love the file nesting feature, but visually I think an improvement could be made for clarity. 

When a file has nesting, it is indented further to allow space for an arrow. This means that its not visually indented the same as all the other non nested files.

Usually, I'm using this to nest a components CSS file with its JS file. If a component doesn't need a CSS file, I still end up creating an empty css file just to keep the indentation the same. Otherwise sometimes in long lists it can be visually difficult to tell if I'm still in the parent directory because the indentation is all over the place.

**Proposal:**

I think there's three options that could help improve this:

1. Change all indentation if file nesting is enabled to leave room for an arrow on all files no matter what.
2. Dynamically determine if a folder has nested files and if so, fix the indentation of the other files in that folder to match.
3. Sort nested files to the top (same behavior's as actual folders)

![image](https://user-images.githubusercontent.com/6005836/233858540-e2b3e35c-90fb-4f08-a982-35a7a93609ba.png)

I'd personally pick option 2.

I know there's some limitations to modifications to the file explorer with extensions, but alternatively, could this be achieved with an extension?

**Comment by gjsjohnmurray** [comment]
Have you seen #148974? One of the observations there is that some File Icon Themes play better that others when nesting is being used.

**Comment by jrj2211** [comment]
I did not see that one, I didn't even think about the icon set affecting the position of it and I'm using seti. The minimal icon set does indeed fix the weird indentation.

Closing this issue as it is a duplicate of the #148974
