### ISSUE TITLE
make search for PRs and issues configurable for the repository you are working in

### ISSUE THREAD

**Issue by willi84** [microsoft/vscode#180675]
Its cool, that I have a search through issues and pull request on github

![image](https://user-images.githubusercontent.com/6207308/233954201-952a0f2e-5346-456d-b012-d1b803625b17.png)

but if my company has an internal system this doesnt help me. 
I wish I could configure this to use e.g an internal git-System (Github, Gitlab, git*. Maybe also to search through my JIRA-tasks

**Comment by alexr00** [comment]
These views come from the GitHub Pull Requests and Issues extension and they work with GitHub and GitHub Enterprise. Any other git remotes would be great candidates for a separate extension.
