### ISSUE TITLE
App won‘t launch on macOS from user-specific ~/Applications directory

### ISSUE THREAD

**Issue by tcsRTI** [Microsoft/vscode#18062]
- VSCode Version: 1.9.0-insider
- OS Version: macOS Sierra 10.12.2

Steps to Reproduce:

1. Download and extract insider build
2. Move application bundle to ~/Applications
3. Launch Visual Studio Code.app
4. Launch does not complete. Full menu bar and main window do not appear.

Workaround:

- After moving the bundle from user-specific ~/Applications to system-wide /Applications, application launches.

**Comment by joaomoreno** [comment]
If you run it from the Terminal as 

```
~/Applications/Visual\ Studio\ Code\ -\ Insiders.app/Contents/MacOS/Electron
```

Do you see any output?

**Comment by tcsRTI** [comment]
To answer your question: there is no output in Terminal from ~/Applications/Visual\ Studio\ Code\ -\ Insiders.app/Contents/MacOS/Electron when this occurs.

However, I have more info. It is reproducible only under “first launch” conditions; that is, if ~/Library/Application\ Support/Code\ -\ Insiders does not exist. By deleting this directory, I could reproduce the issue readily again. A dock icon is created, and the app has exactly one menu item—“Quit”. This is reproducible from /Applications also, so I characterized the issue incorrectly at first.

If I run it a second time, it starts up. To make it fail again, I just delete ~/Library/Application\ Support/Code\ -\ Insiders.

**Comment by joaomoreno** [comment]
@tcsRTI Is this still an issue for you?

**Comment by tcsRTI** [comment]
I have confirmed that with the latest version, the issue has been resolved. I was able to reproduce it again, then installed the latest update, and now it’s not reproducible any longer. Thanks!
