### ISSUE TITLE
Add tooling for grammar and theme authors

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode#18068]
- show tokenizer scopes and inidcate how color theme rules were matched
- improve yeoman to make grammar and theme authoring simpler

See https://marketplace.visualstudio.com/items?itemName=siegebell.scope-info as a nice example

**Comment by Gama11** [comment]
Will this include a command to reload a grammar / recolorize at runtime (or maybe even detect changes to the grammar file automatically if instructed)? Afaik, this currently requires reloading the window, which makes testing a bit cumbersome.

**Comment by aeschli** [comment]
There's now a new command 'Dev Tools: Show Tm Scopes'.
No further improvements for January planed.

**Comment by aeschli** [comment]
Closed.
