### ISSUE TITLE
LaTeX syntax highlighting broken with minted and escapeinside

### ISSUE THREAD

**Issue by The-Compiler** [microsoft/vscode#180692]
Type: <b>Bug</b>

When using [minted](https://github.com/gpoore/minted) with LaTeX with its `escapeinside` feature (see pages 22/23 in [the docs](https://tug.ctan.org/macros/latex/contrib/minted/minted.pdf)), this breaks VS Code's syntax highlighting, and the rest of the file is (mostly) rendered in red.

Minimal example:

```latex
\documentclass{article}
\usepackage{minted}

\begin{document}
\begin{minted}[escapeinside=||]{python}
    print(|\emph{test}|)
\end{minted}

\textbf{\textrightarrow{} Syntax highlighting broken for the rest of the file!}
\end{document}
```

Outcome on stock config without extensions:

![image](https://user-images.githubusercontent.com/625793/234011662-5c2148c3-d96d-410f-bf83-1a8a3fb5cd71.png)

VS Code version: Code 1.77.1 (b7886d7461186a5eac768481578c1d7ca80e2d21, 2023-04-04T23:20:37.202Z); 1.77.3 (704ed70d4fd1c6bd6342c436f1ede30d1cff4710)
OS version: Linux x64 6.2.11-arch1-1
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 PRO 4750U with Radeon Graphics (16 x 4000)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|3, 1, 1|
|Memory (System)|46.29GB (19.20GB free)|
|Process Argv|--user-data-dir /tmp/fresh --disable-extensions|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|herbstluftwm-locked|
|XDG_CURRENT_DESKTOP|undefined|
|XDG_SESSION_DESKTOP|undefined|
|XDG_SESSION_TYPE|x11|
</details>Extensions disabled<details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
vsccc:30610678
nodejswelcome1cf:30587006
2e4cg342:30602488
pyind779:30671433
f6dab269:30613381
pythonsymbol12:30671437
6233i204:30672705
vsctsb:30705553
azdwalk:30721579
pythonms35:30701012
pythonfmttext:30716742
pythonclientmv:30713943

```

</details>

**Comment by The-Compiler** [comment]
Also present on 1.77.3. The "Inspect editor tokens and scopes" feature reveals that VS Code still assumes Python inside the escape:

![image](https://user-images.githubusercontent.com/625793/234018990-fcc9bdbd-277d-43c0-b7e0-758f364b4f94.png)

and then gets stuck in that even past the `\end{minted}`:

![image](https://user-images.githubusercontent.com/625793/234019133-adbfb138-e3d5-4d1e-9a1d-d26141636b86.png)

**Comment by alexr00** [comment]
@The-Compiler thank you for the clear example. I've moved the issue over to https://github.com/jlelong/vscode-latex-basics/issues/58, which is where we get our syntax highlighting grammar from. I suspect though that this is going to be a tough one to fix.
