### ISSUE TITLE
Emmet: Support for CSS modules in jsx/tsx (bump @emmetio/abbreviations to >2.4.0)

### ISSUE THREAD

**Issue by stefan-enveritas** [microsoft/vscode#180689]
A new emmet release supports abbreviations, such that `dev.foo` resolves to `<div className={styles.foo}` instead of `<div className="foo">`. 

The change was released with Emmet v2.4.0 — See also: https://github.com/emmetio/emmet/issues/589

It would be great if vscode could support this new feature as well.

**Comment by rzhao271** [comment]
We are on Emmet 2.4.x now.

**Comment by roblourens** [comment]
How do you configure this?

**Comment by rzhao271** [comment]
We can test the new default behaviour for now.

1. Open a JSX file.
2. Type `div..test`
3. Confirm that `<div styleName={styles.test}></div>` shows up. This behaviour aligns with https://github.com/emmetio/emmet/issues/589#issuecomment-1217717361

**Comment by danmiles** [comment]
I would appreciate help on how to change
  styleName to className?

When I write ..test it gives
<div styleName={styles.test}></div>

**Comment by rzhao271** [comment]
Hi @danmiles, thanks for asking!
I tried adding some steps, but then noticed that `@vscode/emmet-helper` didn't actually support the new properties. I'll re-open this issue due to lack of proper support of the upstream feature.

**Comment by rzhao271** [comment]
Moving this issue to the next month. There seems to be an issue with the way emmet merges some configs that I'll either have to work around or fix upstream.

**Comment by rzhao271** [comment]
The fix has not been released yet. It should be available on [Insiders](https://code.visualstudio.com/insiders/) starting on Monday.

1. Configure the `emmet.syntaxProfiles` setting as follows
```json
"emmet.syntaxProfiles": {
	"jsx": {
		"markup.attributes": {
			"class*": "className",
		},
		"markup.valuePrefix": {
			"class*": "styles"
		}
	}
}
```
2. In a JSX file, expand the abbreviations `.test` and `..test`.
3. `.test` should expand to `<div className="test"></div>` and `..test` should expand to `<div className={styles.test}></div>`.

CC @danmiles
