### ISSUE TITLE
VS Code downloads and attempts to install the wrong pre-release version of Jupyter extension

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode#180671]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:  Latest Stable
- OS Version: N/A
- 
Steps to Reproduce:

1. Go into VSC Stable.
2. Install the latest stable version of Jupyter extension
3. Click on `Switch to Pre-Release Version`,
4. Installation fails with an error message

VS Code now seems to download the version `2023.4.*`, however that requires a minimum of VS Code 1.78 (which happens to be the latest Insiders )
![Screenshot 2023-04-24 at 16 31 43](https://user-images.githubusercontent.com/1948812/233917937-0f819da6-6e2b-42d3-878f-b9d1f4dc2f19.png)
![Screenshot 2023-04-24 at 16 31 56](https://user-images.githubusercontent.com/1948812/233917961-14ec4ba1-df42-41d0-b082-c509662a1c3e.png)

**Comment by DonJayamanne** [comment]
I was under the impression that VS Code will inspect the engine version in package.json and filter out the versions that are not relevant to the current version of VS Code.

@sandy081 @rebornix /cc

**Comment by rjra2611** [comment]
Hey, Guys! 

I have this extension as a dependency for my vscode extension. 

```
"extensionDependencies": [
    "ms-toolsai.jupyter"
  ],
```

Whenever I try to install the pre-release version of my extension I get the following error 

```
Can't install pre-release version of 'ms-toolsai.jupyter' extension because it is not compatible with the current version of Visual Studio Code (version 1.78.2). Would you like to install the release version?
```

I also have other extensions as dependencies but they get installed as `release` versions even if I'm installing my extension as pre-release but looks like the Jupyter extension tries to get installed in the pre-release version for some reason

**Comment by sandy081** [comment]
@DonJayamanne This is because, there is no pre-release version newer than the release version that is compatible with VS Code. Hence VS Code is unable to install.
