### ISSUE TITLE
Test: ffmpeg codec support has not changed

### ISSUE THREAD

**Issue by deepak1556** [microsoft/vscode#180780]
Refs: https://github.com/microsoft/vscode-electron-prebuilt/pull/22

- [x] anyOS @gregvanl
- [x] anyOS @bpasero

Complexity: 3

Authors: @deepak1556 

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23180780%0A%0A&assignees=deepak1556)

---

## Summary:

We have now changed how ffmpeg component is packaged in the MS Electron repo. This should not cause any change in our supported list of codecs and containers and the test plan item is to verify it. The following are the list of codecs and containers we should be supporting,

* Vorbis
* Flac
* VP8
* MP3
* WAV
* OGG
* H.264
* MP4 (without AAC support)

## Steps to Test:

* F1 > Help: List Audio Cues > you can hear all the audio cues being played
* You can play audio files from notebooks. Code sample:

```
import IPython.display as ipd
ipd.audio('PATH_TO_SOME_AUDIO_FILE')
```

**Audio file samples for testing:**
[Unsupported_audio.zip](https://github.com/microsoft/vscode/files/11318049/Unsupported_audio.zip) - Contains opus and aac
[Supported_audio.zip](https://github.com/microsoft/vscode/files/11318090/Supported_audio.zip) - Contains mp3 and ogg

* Convert them to other formats not in the supported codec list and ensure that they don't play (Optional, good to test)
* Verify video files in release notes play as expected

**Comment by bpasero** [comment]
I tested macOS (Intel).

**Comment by gregvanl** [comment]
I tested Windows 11
