### ISSUE TITLE
Test Electron 24

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#180783]
Refs

- [x] Mac @paulacamargo25
- [x] Linux @karthiknadig
- [x] Windows @aeschli

Complexity: 4

Authors: @deepak1556  @bpasero  

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23180783%0A%0A&assignees=bpasero,deepak1556,)

--- 
We plan to promote Electron 24 in the May 2023 milestone to insiders. The following tests cover some of the common UI bits that don't have smoke tests, but feel free to self-host on the nightly builds for rest of the iteration. You can download the nightly explorations builds from [here](https://builds.code.visualstudio.com/builds/exploration) for testing.

---

**Testing:**

* **macOS:**
  * Enable Native Tabs (via settings: `window.nativeTabs: true`)
    - Ensure native tabs are enabled in the system preferences (System Preferences > General > Prefer tabs: "always":)
    - Launch application
    - Try opening new window from either command line (code-exploration <path-to-project>) or from the menu entry (Cmd + Shift + N)
    - Verify new window is launched as a new tab in the active instance of the application
  * window is focused when starting from command line
    - open the code exploration application from finder or dock
    - open external terminal
    - run code-exploration
    - make sure the new window is put to foreground

* **windows:**
  * touch device, verify onscreen keyboard doesn't pop up when clicking inside vscode while external keyboard is attached
  * verify maximize and restore operations work as expected when task bar is auto-hidden for custom titlebar
  * Verify titlebar is not clipped off when exiting fullscreen
    - Maximize VS Code window
    - Press F11 or Ctrl+K Z twice to enter/exit full screen.
    - Verify titlebar is not cropped
  * Verify there is no rendering lag with custom titlebar

* **linux:**
  * Verify application launches successfully with the following install flavors on any of the minimum supported distro version described in https://code.visualstudio.com/docs/supporting/requirements#_platforms
     - Snap
     - Deb
     - RPM
     
 * **All OS:**
   * Check out the `electron-24.x.y` branch locally and verify you can run out of sources, set a breakpoint and debug using the VS Code launch configurations and VS Code debugger

**Comment by lorand-horvath** [comment]
So only 1 month of actual Electron 22 (April) ?

**Comment by karthiknadig** [comment]
Works well on LinuxMint.

**Comment by lewallen** [comment]
@bpasero Is there any place I could still obtain that exploration build (I don't have login authorisation using your original link)? I'm hoping this version might ameliorate the [native crash bug](https://github.com/microsoft/vscode/issues/167936#issue-1473018998) which I've been struggling with.

Note-I was able to build the Electron 24 branch but it doesn't have extension marketplace access--I think the exploration build would? If not than ignore the request.

On the version I built I did still see the crash problem once I think, but I thought it might be happening less. Not sure about that completely.

Thanks for your time/any advice!

**Comment by bpasero** [comment]
Sure:

VS Code Build: 2a026dbfa74a48e629f23f1d54fd7cd788a44ffb

cli-alpine-arm64: https://az764295.vo.msecnd.net/exploration/2a026dbfa74a48e629f23f1d54fd7cd788a44ffb/vscode_cli_alpine_arm64_cli.tar.gz
cli-alpine-x64: https://az764295.vo.msecnd.net/exploration/2a026dbfa74a48e629f23f1d54fd7cd788a44ffb/vscode_cli_alpine_x64_cli.tar.gz
cli-darwin-arm64: https://az764295.vo.msecnd.net/exploration/2a026dbfa74a48e629f23f1d54fd7cd788a44ffb/vscode_cli_darwin_arm64_cli.zip
cli-darwin-x64: https://az764295.vo.msecnd.net/exploration/2a026dbfa74a48e629f23f1d54fd7cd788a44ffb/vscode_cli_darwin_x64_cli.zip
cli-linux-arm64: https://az764295.vo.msecnd.net/exploration/2a026dbfa74a48e629f23f1d54fd7cd788a44ffb/vscode_cli_linux_arm64_cli.tar.gz
cli-linux-x64: https://az764295.vo.msecnd.net/exploration/2a026dbfa74a48e629f23f1d54fd7cd788a44ffb/vscode_cli_linux_x64_cli.tar.gz
cli-win32-arm64: https://az764295.vo.msecnd.net/exploration/2a026dbfa74a48e629f23f1d54fd7cd788a44ffb/vscode_cli_win32_arm64_cli.zip
cli-win32-ia32: https://az764295.vo.msecnd.net/exploration/2a026dbfa74a48e629f23f1d54fd7cd788a44ffb/vscode_cli_win32_ia32_cli.zip
cli-win32-x64: https://az764295.vo.msecnd.net/exploration/2a026dbfa74a48e629f23f1d54fd7cd788a44ffb/vscode_cli_win32_x64_cli.zip
darwin: https://az764295.vo.msecnd.net/exploration/2a026dbfa74a48e629f23f1d54fd7cd788a44ffb/VSCode-darwin.zip
darwin-arm64: https://az764295.vo.msecnd.net/exploration/2a026dbfa74a48e629f23f1d54fd7cd788a44ffb/VSCode-darwin-arm64.zip
darwin-universal: https://az764295.vo.msecnd.net/exploration/2a026dbfa74a48e629f23f1d54fd7cd788a44ffb/VSCode-darwin-universal.zip
linux-arm64: https://az764295.vo.msecnd.net/exploration/2a026dbfa74a48e629f23f1d54fd7cd788a44ffb/code-exploration-arm64-1682397176.tar.gz
linux-deb-arm64: https://az764295.vo.msecnd.net/exploration/2a026dbfa74a48e629f23f1d54fd7cd788a44ffb/code-exploration_1.78.0-1682396873_arm64.deb
linux-deb-x64: https://az764295.vo.msecnd.net/exploration/2a026dbfa74a48e629f23f1d54fd7cd788a44ffb/code-exploration_1.78.0-1682398222_amd64.deb
linux-rpm-arm64: https://az764295.vo.msecnd.net/exploration/2a026dbfa74a48e629f23f1d54fd7cd788a44ffb/code-exploration-1.78.0-1682396943.el7.aarch64.rpm
linux-rpm-x64: https://az764295.vo.msecnd.net/exploration/2a026dbfa74a48e629f23f1d54fd7cd788a44ffb/code-exploration-1.78.0-1682398296.el7.x86_64.rpm
linux-snap-x64: https://az764295.vo.msecnd.net/exploration/2a026dbfa74a48e629f23f1d54fd7cd788a44ffb/code-exploration-x64-1682398978.snap
linux-x64: https://az764295.vo.msecnd.net/exploration/2a026dbfa74a48e629f23f1d54fd7cd788a44ffb/code-exploration-x64-1682398650.tar.gz
win32: https://az764295.vo.msecnd.net/exploration/2a026dbfa74a48e629f23f1d54fd7cd788a44ffb/VSCodeSetup-ia32-1.78.0-exploration.exe
win32-archive: https://az764295.vo.msecnd.net/exploration/2a026dbfa74a48e629f23f1d54fd7cd788a44ffb/VSCode-win32-ia32-1.78.0-exploration.zip
win32-arm64: https://az764295.vo.msecnd.net/exploration/2a026dbfa74a48e629f23f1d54fd7cd788a44ffb/VSCodeSetup-arm64-1.78.0-exploration.exe
win32-arm64-archive: https://az764295.vo.msecnd.net/exploration/2a026dbfa74a48e629f23f1d54fd7cd788a44ffb/VSCode-win32-arm64-1.78.0-exploration.zip
win32-arm64-user: https://az764295.vo.msecnd.net/exploration/2a026dbfa74a48e629f23f1d54fd7cd788a44ffb/VSCodeUserSetup-arm64-1.78.0-exploration.exe
win32-user: https://az764295.vo.msecnd.net/exploration/2a026dbfa74a48e629f23f1d54fd7cd788a44ffb/VSCodeUserSetup-ia32-1.78.0-exploration.exe
win32-x64: https://az764295.vo.msecnd.net/exploration/2a026dbfa74a48e629f23f1d54fd7cd788a44ffb/VSCodeSetup-x64-1.78.0-exploration.exe
win32-x64-archive: https://az764295.vo.msecnd.net/exploration/2a026dbfa74a48e629f23f1d54fd7cd788a44ffb/VSCode-win32-x64-1.78.0-exploration.zip
win32-x64-user: https://az764295.vo.msecnd.net/exploration/2a026dbfa74a48e629f23f1d54fd7cd788a44ffb/VSCodeUserSetup-x64-1.78.0-exploration.exe

**Comment by eamodio** [comment]
@bpasero I was trying to get the latest exploration build, but https://builds.code.visualstudio.com/builds/exploration prompts for authentication.

**Comment by deepak1556** [comment]
@eamodio you can use the dowload links from the previous comment which are public facing endpoints.

**Comment by eamodio** [comment]
@deepak1556 thanks. I completely glossed over that those were links.
