### ISSUE TITLE
Improve terminal action hover UI

### ISSUE THREAD

**Issue by karrtikr** [microsoft/vscode#180739]
1. Improve description when only one terminal is opened:

    ![image](https://user-images.githubusercontent.com/13199757/234088171-ec56fe18-d36d-46f6-b5b1-25f37b4f087e.png)

    Ideally it should be the same as:

![image](https://user-images.githubusercontent.com/13199757/234088292-2bb89294-e0fd-4453-84d5-4c17bce90e80.png)

**Comment by karrtikr** [comment]
Also, use markdown for process description:

![image](https://user-images.githubusercontent.com/13199757/234093449-b9763cdc-d4d1-40b3-81cf-0f960cbd2682.png)

**Comment by karrtikr** [comment]
Third UI issue:

_Originally posted by @amunger in https://github.com/microsoft/vscode-python/issues/21129#issuecomment-1522479376_

also you can tell that I struggled a bit to actually click the actions in the dialog

![terminalWarnings](https://user-images.githubusercontent.com/2019016/234414452-6a6456f1-9415-48ac-a40a-5aa1dd98b4cd.gif)

**Comment by Tyriar** [comment]
> 1 Improve description when only one terminal is opened:

https://github.com/microsoft/vscode/issues/177774

> 2 We should probably use markdown backticks for process description:

It was originally styled like that but it was much too large and less readable considering the default shell integration injection command line.

> also you can tell that I struggled a bit to actually click the actions in the dialog

https://github.com/microsoft/vscode/issues/162336

**Comment by karrtikr** [comment]
> It was originally styled like that but it was much too large and less readable considering the default shell integration injection command line.

Maybe not for the whole command line but atleast for the file paths I think using backticks makes it more readable.

**Comment by Tyriar** [comment]
Args could be paths too though and the default Windows profile can be really huge:

![image](https://github.com/microsoft/vscode/assets/2193314/97eefebb-695c-4a80-b37a-9a659249d0df)
