### ISSUE TITLE
the software take some time for open.

### ISSUE THREAD

**Issue by Ueiej** [microsoft/vscode#180724]
Type: <b>Performance Issue</b>

when i click on the softare icon, a black screen is displayed after that a warning come on the screen : windows is not responding.(close,keep waiting). and
it take some time to open

VS Code version: Code 1.77.3 (704ed70d4fd1c6bd6342c436f1ede30d1cff4710, 2023-04-12T09:16:02.548Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 5700U with

**Comment by deepak1556** [comment]
Can you follow the steps in https://github.com/microsoft/vscode/issues/178733#issuecomment-1500812938 and exclude the `code.exe` binary.

Merging to https://github.com/microsoft/vscode/issues/178962

**Comment by arunspacek** [comment]
> Can you follow the steps in [#178733 (comment)](https://github.com/microsoft/vscode/issues/178733#issuecomment-1500812938) and exclude the `code.exe` binary.
> 
> Merging to #178962

Hi Deepak. This solution does fix the slow boot time, but it's not the right way. There's something wrong with the latest versions of vscode. It needs to be fixed.

**Comment by deepak1556** [comment]
@arunspacek I will check back on this after `v1.78` gets released this week which comes with a newer version of the runtime.
