### ISSUE TITLE
GLIBC_2.8 required for terminal

### ISSUE THREAD

**Issue by schnapper79** [microsoft/vscode#180798]
Type: <b>Bug</b>

when using ssh-remote extension to work on an embedded system (armv7, Debian Stretch) i can't open a terminal du to missing GLIBC_2.8.  This is new for about a week, before that it worked fine.
![image](https://user-images.githubusercontent.com/27971627/234233527-895f8ef0-34b3-4a6a-9f44-14cc1741dba1.png)

VS Code version: Code - Insiders 1.78.0-insider (2902f278ad8e2d830fa6883d3d8fd7b5c2ca59e9, 2023-04-25T05:39:22.920Z)
OS version: Linux x64 6.2.11-arch1-1
Modes:
Sandboxed: Yes
Remote OS version: Linux arm 4.9.11-ame

**Comment by meganrogge** [comment]
@deepak1556 or @roblourens know anything about this?
