### ISSUE TITLE
Test: Toggle notebook output scrolling

### ISSUE THREAD

**Issue by amunger** [microsoft/vscode#180761]
Refs: https://github.com/microsoft/vscode/issues/174951

- [x] windows @bamurtaugh
- [x] macOS @ulugbekna
- [x] linux @connor4312

Complexity: 3

Authors: @amunger, @rebornix 

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23180761%0A%0A&assignees=amunger,rebornix)

---

1. Create a new notebook file
2. Run a few cells with large outputs, examples below
3. while focused in a cell with large output, toggle the scrollability with the command `Notebook: toggle scroll cell output`, hotkey ctrl+k ctrl+y, and the link in the truncation message.
4. Use the settings link to find notebook output related settings and try to update them (changing the global scroll setting will determine how cells are initially rendered)

### Streaming output

Output will continuously update but is still able to toggle scrollability

```
import time
for i in range(200):
    time.sleep(.1)
    print(i)
```

### Longer than the hard limit of 5000 lines

```
for i in range(5005):
    print(i)
```

**Comment by ulugbekna** [comment]
> hotkey ctrl+k ctrl+y

just a typo probably, but it seems to be `ctrl+k y`

**Comment by bamurtaugh** [comment]
I can't seem to get `ctrl+k y` or `ctrl+k + ctrl y` to work:

![image](https://user-images.githubusercontent.com/25310137/234332622-3c082758-470f-4b6f-981b-a14d2d96045a.png)

![image](https://user-images.githubusercontent.com/25310137/234332713-256bd63f-b472-44d5-961b-1ae4efadf23d.png)

I'm using Jupyter pre-release `v2023.4.1011171100`. Am I missing something? The other methods (i.e. `Notebook: toggle scroll cell output`) work for me.
