### ISSUE TITLE
vscode.dev link with spaces does not open the file

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#180799]
Testing #180563

The links is: https://insiders.vscode.dev/github/bpasero/vscode-bisect/blob/ben/initial-jaguar/src/super%2520duper%2520test%2520.%2520txt#L1

Steps:
* clone https://github.com/bpasero/vscode-bisect to local
* create a branch and push
* create files `src/super duper test . txt` and `src/more coming now /test.txt`
* "Copy vscode.dev link"
* open in browser

=> 🐛 file does not open

**Comment by bpasero** [comment]
Above was done using desktop client, seems to work when I do it from vscode.dev.

**Comment by TylerLeonhardt** [comment]
+1 on this with:
https://insiders.vscode.dev/github/microsoft/vscode/blob/tyler/marine-termite/extensions/github-authentication/src/hi%2520joyce.txt#L7

**Comment by TylerLeonhardt** [comment]
+1 on this with this file generated from VS Code Desktop AND insiders.vscode.dev:
https://insiders.vscode.dev/github.com/microsoft/vscode/blob/tyler/marine-termite/extensions/github-authentication/src/%3B/?:@&=+$,#L5

**Comment by joyceerhl** [comment]
There is double encoding going on in this file link https://insiders.vscode.dev/github/microsoft/vscode/blob/tyler/marine-termite/extensions/github-authentication/src/hi%2520joyce.txt#L7
