### ISSUE TITLE
"Show Next Change" doesn't show the right change

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#180744]
- Open a file with multiple changed regions in git
- Move cursor inside/next to some change
- Run "Show Next Change" (alt+f3)
- It reveals and shows a different change- I think it always shows the last one in the editor. It should show the next one after the cursor position

I can press it multiple times to cycle through changes, and that's correct, but it always starts with the last change

**Comment by alexr00** [comment]
I'd like to fix this for April, but it looks like the change could be risky. I will fix it for May.

**Comment by alexr00** [comment]
Found a low risk fix.

**Comment by roblourens** [comment]
This works, thanks! But one thing that my muscle memory is unsure about, did this command previously move the cursor? I'm noticing that if I press it multiple times, then press escape, the view moves back to the place where I started, when I'm expecting this to be like a "navigate" action.

I can open a new issue, or if it's always worked like this, it's fine

**Comment by alexr00** [comment]
I went back to 1.74 to check, and it didn't move the cursor there. "Go to Next Change" will move the cursor though.
