### ISSUE TITLE
Test new drop UX and drop metadata proposal 

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#180741]
Test for #179430

- [x] Mac @Yoyokrazy 
- [x] Linux @lramos15
- [x] Windows @joyceerhl

Complexity: 5

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23180741%0A%0A&assignees=mjbvz)

---

## Summary
This iteration we introduced a new UI element that allows you to change changing how content is dropped. This shows up as a widget after you drag and drop content into an editor:

![Screenshot 2023-04-24 at 11 48 00 AM](https://user-images.githubusercontent.com/12821956/234088220-33ad1b68-014e-4e10-b64f-886a79d7ae65.png)

To support this new widget, we also introduce a new API proposal: `vscode.proposed.dropMetadata.d.ts`. This proposal lets extensions contribute metadata that is shown in the new UI

## Testing
You can test the new UI in any type of file. To test the new API proposal or create more complex scenarios, use the [drop provider extension sample](https://github.com/microsoft/vscode-extension-samples/tree/main/drop-on-document).

**UI elements to test**

- Dropping one or more files into any editor should show two options: `insert relative path` and  `insert path`. By default, a workspace relative path should be inserted

- After dropping, you can change how the content was dropped using the widget

- The widget should go away you edit the file or move the cursor outside of the drop edit's initial range (ie the path that was inserted)

- The widget should not show up if there is only a single drop provider. To test this, drag text content into the editor. You can drag and drop from outlook for example

- You should be able to open the widget using ctrl+. or cmd+.

- The `editor.dropIntoEditor.showDropSelector` setting should control if the widget shows up

- For extensions not using the new API (specifically those that don't set `DocumentDropEdit.label`), the drop labels should include the extension name

**API elements to test**
- `DocumentDropEdit.label` should show up in the new widget UI

- The `dropMimeTypes` list should let you restrict when a provider is invoked. To test this, try setting `dropMimeTypes: ["image/png"]` and then dropping text into the editor. Your provider should not be invoked

- `dropMimeTypes` should support using `*/*` to always be invoked for any mime type data

**Comment by lramos15** [comment]
I didn't realize at first that I needed to modify the extension sample to consume the new proposed API. Just leaving this comment in case anyone else doesn't notice

**Comment by roblourens** [comment]
Have you started on this one @aeschli?

**Comment by aeschli** [comment]
Thanks @Yoyokrazy for jumping in!
