### ISSUE TITLE
 Uncaught TypeError: Cannot read property 'startLineNumber' of null

### ISSUE THREAD

**Issue by vscodeerrors** [Microsoft/vscode#1807]
Issue Id: <b>90d6b67b-6e38-cd60-db01-bda8743edd02</b><br /><br />*Versions* <br />- 0.10.5<br />-  a80232bbcfe8a5cdad1ebc98638673d9dcb02458<br />*Stack* <br />TypeError: Cannot read property 'startLineNumber' of null<br />[/vs/editor/contrib/hover/browser/modesContentHover.ts#L260:27 (ModesContentHoverWidget._renderMessages)](https://github.com/microsoft/vscode/blob/dfc08dc9edf6607483b193bf934d3badc3fa2e11/src/vs/editor/contrib/hover/browser/modesContentHover.ts#L260:27 (ModesContentHoverWidget._renderMessages))<br />[/vs/editor/contrib/hover/browser/modesContentHover.ts#L204:8 (ModesContentHoverWidget._withResult)](https://github.com/microsoft/vscode/blob/dfc08dc9edf6607483b193bf934d3badc3fa2e11/src/vs/editor/contrib/hover/browser/modesContentHover.ts#L204:8 (ModesContentHoverWidget._withResult))<br />[/vs/editor/contrib/hover/browser/modesContentHover.ts#L134:52 (ModesContentHoverWidget.constructor)](https://github.com/microsoft/vscode/blob/dfc08dc9edf6607483b193bf934d3badc3fa2e11/src/vs/editor/contrib/hover/browser/modesContentHover.ts#L134:52 (ModesContentHoverWidget.constructor))<br />[/vs/editor/contrib/hover/browser/hoverOperation.ts#L143:8 (HoverOperation._onComplete)](https://github.com/microsoft/vscode/blob/dfc08dc9edf6607483b193bf934d3badc3fa2e11/src/vs/editor/contrib/hover/browser/hoverOperation.ts#L143:8 (HoverOperation._onComplete))<br />[/vs/editor/contrib/hover/browser/hoverOperation.ts#L117:8 (HoverOperation._triggerSyncComputation)](https://github.com/microsoft/vscode/blob/dfc08dc9edf6607483b193bf934d3badc3fa2e11/src/vs/editor/contrib/hover/browser/hoverOperation.ts#L117:8 (HoverOperation._triggerSyncComputation))<br />[/vs/editor/contrib/hover/browser/hoverOperation.ts#L71:73 (HoverOperation.constructor)](https://github.com/microsoft/vscode/blob/dfc08dc9edf6607483b193bf934d3badc3fa2e11/src/vs/editor/contrib/hover/browser/hoverOperation.ts#L71:73 (HoverOperation.constructor))<br />[/vs/base/common/async.ts#L514:8 (RunOnceScheduler.onTimeout)](https://github.com/microsoft/vscode/blob/dfc08dc9edf6607483b193bf934d3badc3fa2e11/src/vs/base/common/async.ts#L514:8 (RunOnceScheduler.onTimeout))<br />

**Comment by alexandrudima** [comment]
Dup of #2235
