### ISSUE TITLE
directory globs in launch.json "outFiles" cause breakpoints not to trigger on Windows 10. 

### ISSUE THREAD

**Issue by stephensong** [Microsoft/vscode#18074]
- VSCode Version:  1.8.1
- OS Version: Windows 10

Steps to Reproduce:

1.  With the following config in launch.json 

    {
      "type": "node",
      "request": "launch",
      "name": "Generate Model Types",
      "program": "${workspaceRoot}/src/lib/gentypes.ts",
      "cwd": "${workspaceRoot}",
      "outFiles": [ "${workspaceRoot}/src/dist/lib/*.js" ],
      "sourceMaps": true
    },

then breakpoints trigger ok for all .ts files in the ".../src/lib" folder.

2.  If I change the outFiles entry instead to read:

      "outFiles": [ "${workspaceRoot}/src/dist/**/*.js" ],

then only breakpoints in the program entry file (".../src/lib/gentypes.ts") will trigger.  Other files can be stepped into ok from the entry file, and breakpoints can be set therein that appear active and ok (no sourcemap warning messages etc.), but they simply fail to trigger.  

I tried changed the above to the traditional Windows style instead:

      "outFiles": [ "${workspaceRoot}\\src\\dist\\**\\*.js" ],

but still no cigar.

Thanks.

**Comment by weinand** [comment]
attribute outfiles is no longer supported.
