### ISSUE TITLE
Test: dirty notebook working copy data loss prevention

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#180767]
Refs: #179224

- [x] anyOS @joyceerhl 
- [x] anyOS @alexr00

Complexity: 4

Authors: @rebornix @bpasero  

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23180767%0A%0A&assignees=rebornix,bpasero)

---

## Summary:

We now stopped disposing dirty notebook working copies to avoid data loss. Previously it happened when extension host goes down or restarts, and we will immediately try to save or dispose working copies, and they would throw exceptions since the serializer for the working copies are gone.

Now the experience has been improved:

## Steps to Test:

**ipynb**
- Create a new ipynb notebook
- Turn off auto save, make the document dirty
- Trigger EH restart, there are two ways
  - Switch to a new Profile
  - Kill the EH process through Process Explorer (or command line, task manager, etc)
- Now test
  - After the profile switching or EH restart, you can switch between editor tabs
    - If the notebook editor doesn't open, you should see actions on the editor view, which guide you through how to install/enable missing extension or save the backups
  - Saving should work

**github-issues**
- Install GitHub Issues Notebook extension and create a new github-issues notebook
- Turn off auto save, make the document dirty
- Switch to a new Profile without the GitHub Issue Notebook extension
- Now test
  - After the profile switching , you can switch between editor tabs
    - If the notebook editor doesn't open, you should see actions on the editor view, which guide you through how to install/enable missing extension or save the backups
  - After the profile switching, reload the window immediately, test if the warning/error actions on the editor view gives you clear guidance

**Comment by joyceerhl** [comment]
Nice! 👏
