### ISSUE TITLE
Tagged Version SHA Hash Changing

### ISSUE THREAD

**Issue by jdsatava127** [microsoft/vscode#180701]
Does this issue occur when all extensions are disabled?: N/A

- VS Code Version: 
- OS Version: 

Steps to Reproduce:

I noticed that for some recently tagged versions the SHA hash for the tag no longer matches the SHA hash for the actual version commit. Here is an example for 1.77.3. The SHA hash for type tag can be seen as c7f0ae15feb915c17f7bfb6c4ad1420470f9a46d at https://api.github.com/repos/microsoft/vscode/git/ref/tags/1.77.3. But if you look at https://api.github.com/repos/microsoft/vscode/git/tags/c7f0ae15feb915c17f7bfb6c4ad1420470f9a46d for the full details of the tag, the SHA has for the actual commit is 704ed70d4fd1c6bd6342c436f1ede30d1cff4710. The 704ed70d4fd1c6bd6342c436f1ede30d1cff4710 value is the version hash that is reflected in VS Code itself and on update.code.visualstudio.com.

This is not an issue for other versions with a type of tag instead of commit like 1.77.1 at https://api.github.com/repos/microsoft/vscode/git/ref/tags/1.77.1. The SHA hash for the tag is b7886d7461186a5eac768481578c1d7ca80e2d21 and consistent across all services.

**Comment by TylerLeonhardt** [comment]
Here's the reason why: https://stackoverflow.com/a/25996877

> Internals differences
> 
> both lightweight and annotated tags are a file under .git/refs/tags that contains a SHA-1
>
> for lightweight tags, the SHA-1 points directly to a commit:
> 
> git tag light
> cat .git/refs/tags/light
> prints the same as the HEAD's SHA-1.
> 
> So no wonder they cannot contain any other metadata.
> 
> annotated tags point to a tag object in the object database.
> 
> git tag -as -m msg annot
> cat .git/refs/tags/annot
> contains the SHA of the annotated tag object:
> 
> c1d7720e99f9dd1d1c8aee625fd6ce09b3a81fef

That `c7f0ae15feb915c17f7bfb6c4ad1420470f9a46d` isn't the commit, but the annotated tag.

**Comment by TylerLeonhardt** [comment]
closing as answered but let us know if you have more questions
