### ISSUE TITLE
Test: Explore `notebook.codeActionsOnSave`

### ISSUE THREAD

**Issue by Yoyokrazy** [microsoft/vscode#180765]
Refs: #179213

- [x] macOS @jrieken
- [x] linux @roblourens
- [x] windows @sbatten

Complexity: 2

Authors: @Yoyokrazy 

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23180765%0A%0A&assignees=Yoyokrazy)

---

## Summary:

Notebooks now have preliminary support for CodeActions on save. Currently, that allows the user to execute a set of pre-defined commands (not specifically CodeActions) upon the saving of their notebook. 

## Steps to Test:

- Create a new or open a pre-existing notebook
- Go to Settings (UI) and search for `notebook.codeActionsOnSave`
- Add several commands to this setting
- Save the notebook, which should run all commands defined in settings
- Adjust boolean values of commands, ensuring that it changes whether or not the command runs
- Have fun! Play around with this, tweak your notebook workflow, find some bugs.
<img width="721" alt="image" src="https://user-images.githubusercontent.com/12552271/234132636-e87b41c8-bcaf-40de-a4ad-10b2afe34e1d.png">

## Things to check
- The commands all executed (or didn't) as expected given boolean values.
- The notebook saved.
- Saving of the notebook occurred after all actions.

**Comment by roblourens** [comment]
Works as advertised but I agree with https://github.com/microsoft/vscode/issues/180839 that it should be based on code actions, not commands
