### ISSUE TITLE
Test JSX linked editing

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#180769]
Test for microsoft/typescript#51832

- [x] Mac @eleanorjboyd
- [x] Linux @deepak1556
- [x] Windows @luabud

Complexity: 3

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23180769%0A%0A&assignees=mjbvz)

---

## Summary
TS 5.1 enables linked editing for JSX tags. This means you can place your cursor on one tag and start editing to update the matching tag

## Testing
1. Enable linked editing: `"editor.linkedEditing": true`
2. `npm install typescript@next` and switch your workspace to use TypeScript 5.1
3. In a `.tsx` or `.jsx` file, try making linked edits to jsx tags

Some things to test:

- Linked editing should stop once you type space or a non tag character
- Linked editing should only effect the  matching tags
- Linked editing should not be activated when you are on an attribute
- Linked editing should work when the cursor is on either the opening or closing tag
- Pressing escape should exit linked editing mode
- Linked editing should work for qualified names, like `myNamespace.Component`

**Comment by luabud** [comment]
Worked as expected :)

**Comment by yamatsum** [comment]
@mjbvz @luabud 
Works mostly well, but stops working when the tag name is empty

**Comment by justgage** [comment]
For some reason, it required me to restart VSCode (HTML-only files didn't), but after that, it works well. Thanks 🙂.

**Comment by yamatsum** [comment]
I tried restarting but it doesn't work
