### ISSUE TITLE
Recent projects not appearing in Windows taskbar anymore (can't be pinned)

### ISSUE THREAD

**Issue by magnattic** [microsoft/vscode#180743]
Type: <b>Bug</b>

This used to work: When I open project (doesn't matter if local or remote on WSL), I was able to pin it to the taskbar in Windows 11.

For some reason, this is not working for me in the current version.
I can still open projects and they show up in "Recent" of the welcome window.

![image](https://user-images.githubusercontent.com/7560166/234094323-750a8ab5-2051-4d7e-a6bf-1599999a41c1.png)

But they don't show up and can't be pinned in the taskbar, not even if a project is currently open:

![image](https://user-images.githubusercontent.com/7560166/234094426-770a1768-db95-4e0b-8991-047f2ec5e2a8.png)

VS Code version: Code 1.77.3 (704ed70d4fd1c6bd6342c436f1ede30d1cff4710, 2023-04-12T09:16:02.548Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: No
Remote OS version: Linux x64 5.15.90.1-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 PRO 5850U with Radeon Graphics      (16 x 1896)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|30.83GB (9.81GB free)|
|Process Argv|--file-uri=vscode-remote://wsl+Urbyo/home/magnattic/code/urbyo/platform/urbyo.code-workspace --remote=wsl+Urbyo --crash-reporter-id becc655e-3081-4047-91d8-e84f05b6d232|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Urbyo|
|OS|Linux x64 5.15.90.1-microsoft-standard-WSL2|
|CPUs|AMD Ryzen 7 PRO 5850U with Radeon Graphics (16 x 1896)|
|Memory (System)|23.47GB (15.64GB free)|
|VM|0%|
</details><details><summary>Extensions (59)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-apollo|apo|1.19.11
vscode-zipfs|arc|3.0.0
svelte-intellisense|ard|0.7.1
markdown-preview-github-styles|bie|2.0.2
npm-intellisense|chr|1.4.4
path-intellisense|chr|2.8.4
vscode-css-modules|cli|0.5.1
vscode-eslint|dba|2.4.0
vscode-deno|den|3.17.0
gitlens|eam|13.5.0
EditorConfig|Edi|0.16.4
prettier-vscode|esb|9.12.0
vscode-open-in-npm|fab|1.0.4
psalm-vscode-plugin|get|2.7.0
codespaces|Git|1.14.6
copilot|Git|1.84.51
copilot-labs|Git|0.12.791
remotehub|Git|0.54.0
vscode-github-actions|git|0.25.6
vscode-pull-request-github|Git|0.62.0
gitpod-desktop|git|0.0.99
vscode-graphql|Gra|0.8.7
vscode-graphql-execution|Gra|0.1.8
vscode-graphql-syntax|Gra|1.1.0
vscode-test-explorer|hbe|2.21.1
npm-dependency-links|her|1.2.0
easy-snippet|inu|0.6.3
latex-workshop|Jam|9.8.2
pubspec-assist|jer|2.3.2
commitlint|jos|2.4.2
vscode-jest-test-adapter|kav|0.8.1
git-graph|mhu|1.30.0
vscode-scss|mrm|0.10.0
vscode-docker|ms-|1.25.0
playwright|ms-|1.0.10
remote-ssh|ms-|0.100.0
remote-ssh-edit|ms-|0.84.0
remote-wsl|ms-|0.77.0
azure-repos|ms-|0.30.0
remote-explorer|ms-|0.4.0
remote-repositories|ms-|0.32.0
test-adapter-converter|ms-|0.1.7
vsliveshare|ms-|1.0.5862
vsliveshare-pack|ms-|0.4.0
vscode-jest|Ort|5.2.3
vscode-versionlens|pfl|1.5.0
vscode-commons|red|0.0.6
vscode-yaml|red|1.12.2
vscode-sort-json|ric|1.20.0
svg-preview|Sim|2.8.3
vscode-zipexplorer|sle|0.3.1
vscode-stylelint|sty|1.2.4
svelte-vscode|sve|107.3.0
sass-indented|syl|1.8.26
jestRunIt|ves|0.6.0
intellicode-api-usage-examples|Vis|0.2.7
vscodeintellicode|Vis|1.2.30
vscode-conventional-commits|viv|1.25.0
pretty-ts-errors|yoa|0.3.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
nodejswelcome1cf:30587006
2e4cg342:30602488
pyind779:30671433
f6dab269:30613381
pythonsymbol12:30671437
a9j8j154:30646983
azdwalk:30721579
pythonms35:30701012
pythonfmttextcf:30716743

```

</details>

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by magnattic** [comment]
You are right, I seem to have accidentally switched this off in Windows somewhere in the past.

For anyone else stumbling across this problem, it's this setting in `Personalization > Start`:

> Show recently opened items in Start, Jump Lists, and File Explorer

![image](https://user-images.githubusercontent.com/7560166/234241773-bc104057-2e1b-466b-ae31-a9057505ecf3.png)

Thanks for getting me on the right track!
