### ISSUE TITLE
Revisit always showing "Add to Watch" and "Run to Cursor" to editor context menu

### ISSUE THREAD

**Issue by alexdima** [microsoft/vscode#180752]
The change for https://github.com/microsoft/vscode/issues/162727 went in without a UX discussion. IMHO we should reconsider adding these two actions to all editor context menus. IMHO we need to be more critical with adding things there and have good reasons to do so.

<img width="284" alt="image" src="https://user-images.githubusercontent.com/5047891/234118418-11c8c80d-fc80-4f7c-bff1-dd36b7e43608.png">

**Comment by roblourens** [comment]
I figured it wasn't a major change since they are already in the context menu during a debug session. Would a Debug submenu help?

**Comment by roblourens** [comment]
We discussed this in standup and I will likely just remove them when not in a debug session.

**Comment by roblourens** [comment]
From https://github.com/microsoft/vscode/pull/153224 and https://github.com/microsoft/vscode/pull/169819

Keeping the changes so that they will work and appear in the command palette when not in a debug session, but only appear in the editor context menu while debugging
