### ISSUE TITLE
TypeError: Failed to parse URL from `./extensions/github.copilot-nightly-1.83.50/dist/tree-sitter.wasm`

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#180787]
It looks like GH Copilot fails to work in E24, maybe related to the global `fetch` now being present in node.js 18:

```
Extension Host] [ERROR] [promptlib proxy] [2023-04-25T06:54:59.539Z] TypeError: Failed to parse URL from /Users/bpasero/.vscode-exploration/extensions/github.copilot-nightly-1.83.50/dist/tree-sitter.wasm
    at Object.fetch (node:internal/deps/undici/undici:14152:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) (at console.<anonymous> (/Applications/Visual Studio Code - Exploration.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:98:155677))
I @ console.ts:137

ERR [Extension Host] [ERROR] [promptlib proxy] [2023-04-25T06:54:59.542Z] Error: Worker thread exited with code 1.
    at Worker.<anonymous> (/Users/bpasero/.vscode-exploration/extensions/github.copilot-nightly-1.83.50/dist/extension.js:8:1235149)
    at Worker.emit (node:events:513:28)
    at Worker.[kOnExit] (node:internal/worker:280:10)
    at Worker.<computed>.onexit (node:internal/worker:200:20)
```

**Comment by deepak1556** [comment]
The underlying issue is from Emscripten https://github.com/emscripten-core/emscripten/commit/eab875588e7517e6ba86883be010d38b93f914bd, it will be addressed if copilot bumps `web-tree-sitter` to `v0.20.8` https://github.com/tree-sitter/tree-sitter/issues/1765

**Comment by bpasero** [comment]
Looks like https://github.com/tree-sitter/tree-sitter/releases/tag/v0.20.8 is out. @bmuskalla could Copilot update?

**Comment by bmuskalla** [comment]
Yes, we'll update soon https://github.com/github/copilot-client/issues/1982

**Comment by bpasero** [comment]
@bmuskalla any updates?

**Comment by bmuskalla** [comment]
The team is still working on it but got sidetracked by more important issues

**Comment by joaomoreno** [comment]
@SmallLemur Any updates here? Thanks!

**Comment by devm33** [comment]
@joaomoreno web-tree-sitter was updated. This should be working as of copilot-nightly-1.89.162

**Comment by devm33** [comment]
Thanks @bpasero! Two related questions, is there a timeline for #184021 and is there any way to test with E24?

**Comment by bpasero** [comment]
@devm33 please connect with @deepak1556 on this topic

**Comment by devm33** [comment]
Thanks!

**Comment by deepak1556** [comment]
@devm33 in this milestone we are investigating the impact of Node v18 update for our server scenario due to an increase in minimum GLIBC version, the timeline for adoption will be decided based on the results. I will post updates in https://github.com/microsoft/vscode/issues/184021

**Comment by devm33** [comment]
Thanks @deepak1556! I'll watch there
