### ISSUE TITLE
[html] Auto insert Quote when i type equal sign (=)

### ISSUE THREAD

**Issue by ebattulga** [microsoft/vscode#18071]
- VSCode Version: 1.8.1
- OS Version: Win10

I need option like Visual studio. (_Insert attribute value quote automatically_)

When i type **=** (Equal sign) automatically add double quote like this. 
1: <div class
2: <div class="|"

Please add this option in Next version! 🙏

**Comment by fvsch** [comment]
Currently, when writing `attr="` or `attr='` you get the matching quote (single or double) automatically. It requires typing one more character, but lets you choose if you want single quotes, double quotes, or none; all three options are valid in HTML, so it might not be a great idea to force double quotes in HTML files.

**Comment by skorunka** [comment]
@fvsch that doe snot work for me. When I type `<i class="` the closing `"` is not inserted.

**Comment by fvsch** [comment]
Apparently it works in XML documents but not in HTML documents. :/

**Comment by aeschli** [comment]
@skorunka That works for me in HTML as well: Note that this has to be at the end of the line.
If this still doesn't work, disable all extensions. Extensions can overwrite the auto-pair characters.

**Comment by Ionaru** [comment]
Currently when typing `attr<tab>`, VSCode auto-inserts the double quotes, it would be nice is the same is applied to `attr=`.

**Comment by skorunka** [comment]
@aeschli Why it has to be at the end of line? Not all the time you are writing a new HTML code, but also editing the extincting - adding new attributes.

**Comment by Ionaru** [comment]
@skorunka It is not very commone to be typing a HTML attribute at the end of the line.

Imagine typing this: `<div>`, VSCode will automatically append `</div>` to it. Now when I want to add an attribute to that div, it is not the end of the line anymore and the auto-pair does not work.

**Comment by aeschli** [comment]
The idea behind it is to only automatically add pairs when writing new code, not when modifying code.
I think right now we only do autopairs when the character after the cursor is a new line or a whitespace. We should extend this and allow to specify other characters as well. In the case of HTML, for `'` and `"`, that would be '>'

**Comment by Ionaru** [comment]
@aeschli What I mean is that even when typing new code, VSCode automatically creates the closing HTML tag, making the auto-pair impossible.

**Comment by aeschli** [comment]
@Ionaru Yes, I get what you mean. Features like auto pair or auto close tags work against the 'writing new code' heuristic that we chose.

**Comment by Bjeaurn** [comment]
Did the discussion evolve from getting the auto-pairing quotes to work, from the original `add auto-paired quotes when typing '=' in like HTML`?

**Comment by bmdatl** [comment]
Is there any update on this? This is one of the biggest features I miss after switching from WebStorm.

**Comment by AchmadFathoni** [comment]
I wondering if there any plug-in that can cover this function.

**Comment by tommcclean** [comment]
Would like this feature too, end up just using Visual Studio over vscode if I know I am doing work on markup

**Comment by tommulkins** [comment]
Might as well add my $.02 here.  I'm surprised how much I miss this feature moving over from PhpStorm.

**Comment by Maweypeyyu** [comment]
I really miss the behaviour of typing `sty` + `ENTER/TAB`and it auto expands to `style='|'` ( `|` = cursor :) ). At least in jsx files it doesn't work for me. Does anyone know of a plugin/custom hack that would enable this?

**Comment by shaunmoss** [comment]
+1 , All these small things you never knew you would miss when move over from Netbeans, phpstorm etc.

**Comment by scottieslg** [comment]
This is seriously not a feature yet???  How does something as simple as this get missed??

**Comment by klocus** [comment]
+1.

**Comment by Linux249** [comment]
+1 Just switch from WebStorm to VsCode and miss this every attribute I wrote

Or is there a plugin for this?

**Comment by rushenn** [comment]
Those who looking for this feature, try this extension https://marketplace.visualstudio.com/items?itemName=AESSoft.aessoft-class-autocomplete

**Comment by mkoma808** [comment]
It's quite astonishing to me that this functionality hasn't yet been added to VS Code given that so many other popular IDEs and editors do this already, including Visual Studio.

**Comment by octoxan** [comment]
This is a much needed feature, switching back to PHP Storm till `<div attr=` auto opens. There's nothing else you would be typing after the equal sign. If you're not using quotes around your value, you're a monster.

**Comment by kejojedi** [comment]
> This is a much needed feature, switching back to PHP Storm till `<div attr=` auto opens. There's nothing else you would be typing after the equal sign. If you're not using quotes around your value, you're a monster.

Actually a previous comment already stated that a possibility is a single quote after the equal sign, instead of a double quote. This is valid when dealing with more complex attributes.

Uh...I mean....rawr I'm a monster.

**Comment by octoxan** [comment]
Then have an option to choose single or double as the default?

**Comment by andrei-scripcaru** [comment]
Hey there. Any updates on this one?

**Comment by ryancco** [comment]
Would really like to see this as well!

**Comment by octoxan** [comment]
Really only still using PHP Storm because of this. Just even over the course of one project this could save tens of thousands of keypresses, especially since " required 2 keys to be pressed lol

**Comment by vegerot** [comment]
This is one of the features I miss the most from WebStorm.  I know it's only a single character (and two keypresses), but it makes thing so much nicer

**Comment by ultrax007** [comment]
i have been searching the whole web to resolve this

**Comment by ida-frontend** [comment]
Any updates? So frustrated by this...

**Comment by AchmadFathoni** [comment]
How to increase the chance of vscode developer will notice this lack of feature?

**Comment by trin4ik** [comment]
realy stupid situation, i need this shit

**Comment by tommulkins** [comment]
This may help.  Turn on `Auto Closing Quotes` and it reaches close to what you want.

![image](https://user-images.githubusercontent.com/11251283/97441471-26b42780-18ff-11eb-9aa9-6612bcb89913.png)

**Comment by trin4ik** [comment]
> This may help. Turn on `Auto Closing Quotes` and it reaches close to what you want.
> 
> ![image](https://user-images.githubusercontent.com/11251283/97441471-26b42780-18ff-11eb-9aa9-6612bcb89913.png)
no.
in phpStorm i write `value=` and get `value="|"`, in vsCode i write `value=` and get `value=`

**Comment by octoxan** [comment]
So silly that something so universally useful isn't in there yet.

**Comment by hmaesta** [comment]
![adp4rm2tg4u11](https://user-images.githubusercontent.com/741969/107859510-ae736280-6e18-11eb-8e0e-74a05b21871c.jpg)

**Comment by hamedhomaee** [comment]
Hello everyone, 
There is still no fix for it?

**Comment by kmoth** [comment]
Depending on the attribute, it'll help you complete the entire attribute name including the `=""` bit.
I only came looking for the option to specify single or double for that autocompletion but I'd enjoy a feature that auto-added the quotes after typing `=`

**Comment by mzinniarranz** [comment]
4 years and counting, how is this even possible?

**Comment by sawarkarrajat** [comment]
kudos guys i think they have included it in the latest update of the vs code, if you search quotes in setting and search for html quotes you can see it there 
![image](https://user-images.githubusercontent.com/52417511/140689650-98d4e481-35a2-4b22-a769-863fe8f51d5a.png)

**Comment by jzyrobert** [comment]
Hello, I've given this PR a go as you can see from the link above.

Please have a look and comment any suggestions.

**Comment by trin4ik** [comment]
> Hello, I've given this PR a go as you can see from the link above.
> 
> 
> 
> Please have a look and comment any suggestions.

great work! as @aeschli says, its need on all language, not only html. very important in jsx. but in jsx need insert not qoutes:

<View style|
<View style={|}

**Comment by TylerLeonhardt** [comment]
<img width="235" alt="image" src="https://user-images.githubusercontent.com/2644648/151622634-852934b0-2ff5-494e-9ba0-fe0cf1fd5587.png">

works well!
