### ISSUE TITLE
[theme] JS `class` does not highlight

### ISSUE THREAD

**Issue by tomByrer** [Microsoft/vscode#18076]
- VSCode Version: 1.8.1
- OS Version: Win10_64

Javascript `class` does not highlight, though other ES6 does.  Seems [another](https://github.com/Microsoft/vscode-themes/issues/12) had the issue in November.
[related ?](https://github.com/Microsoft/vscode/issues/133)

**Comment by mjbvz** [comment]
Can you please provide example code. I see the `class` keyword being highlighted just fine.

**Comment by mjbvz** [comment]
Closing as we need example code to investigate this.

@tomByrer Please try running vscode with `--disable-extensions` and provide some sample code that shows this problem.

Thanks
