### ISSUE TITLE
i want handle multiple projects in one workspace like eclipse 

### ISSUE THREAD

**Issue by omsai5467** [microsoft/vscode#180784]
Type: <b>Feature Request</b>

i want handle multiple projects in same vscode 
can you build like that 

like eclipse manageing the projects like that i need

VS Code version: Code 1.77.3 (704ed70d4fd1c6bd6342c436f1ede30d1cff4710, 2023-04-12T09:16:02.548Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: No

**Comment by gjsjohnmurray** [comment]
Please see https://code.visualstudio.com/docs/editor/multi-root-workspaces
