### ISSUE TITLE
Cannot find module 'xterm' / Loading "xterm" failed

### ISSUE THREAD

**Issue by pocesar** [Microsoft/vscode#18075]
- VSCode Version: 1.9.0-insider
- OS Version: windows 10 x64

Steps to Reproduce:

1. Opened the editor after restarting, it randomly gave me this error
2. Restarting the editor doesn't help

![vscode](https://cloud.githubusercontent.com/assets/461084/21632278/7f01c2ac-d223-11e6-88bb-ebfaba5766d5.png)

**Comment by sandy081** [comment]
@pocesar I (and our team) also on insiders and we do not see this issue. It would be helpful if thee are any steps to reproduce this? Do you have any extensions that might causing this? Try to disable extensions and check?

**Comment by pocesar** [comment]
@sandy081 it seems to have been caused by a restore point. I reinstalled from the latest installer and it's fine.
