### ISSUE TITLE
Feature: Tooltip drill down

### ISSUE THREAD

**Issue by unional** [Microsoft/vscode#18070]
- VSCode Version: 1.8.0
Steps to Reproduce:
```ts
interface FooOption {
  /**
   * Doing boo stuff
   */
  boo(x: number): boolean
}

function foo(option: FooOption) {

}

foo({
  boo()
})
```
![image](https://cloud.githubusercontent.com/assets/3254987/21629779/2145d0a6-d1e0-11e6-965c-e674fe53d86d.png)

![image](https://cloud.githubusercontent.com/assets/3254987/21629764/08958916-d1e0-11e6-975a-87a74eb3f80c.png)

Currently, autocomplete is doing a better job than the tooltip. When you type `boo`, autocomplete gets the definition of `boo` and display it. But once you type `(`, it falls back to the tooltips and only show the tooltip of `foo(...)` instead. 

It would be nice to have the tooltips shows the info for `boo()`. 🌷

**Comment by sandy081** [comment]
@unional This is happening because you are not accessing function `boo` using object of type `FooOption`. If you does that tool tip provides you proper information.

**Comment by unional** [comment]
Yes, I understand it is not:

```ts
let b: FooOption;
b.boo(
      ^ cursor here
```

However it is very common practice in JS to do this kind of option bag, and it would be better to drill down and display the same information in this scenario.

**Comment by sandy081** [comment]
I see. Reopening and assigning to correct owner to provide correct feedback on this.

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript#13304
