### ISSUE TITLE
Test new behavior of ClearSessionPreference in `getSession`

### ISSUE THREAD

**Issue by TylerLeonhardt** [microsoft/vscode#180771]
Refs: https://github.com/microsoft/vscode/issues/152399

- [x] anyOS @rebornix
- [x] anyOS @roblourens

Complexity: 2

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23180771%0A%0A&assignees=TylerLeonhardt)

---

The issue referenced is encompassing the overall story for multi-account extensions, and we'll certainly have a TPI for that when it's ready, but one part that has gone in does affect users today and that's the changes to `ClearSessionPreference` which is a part of the `getSession` API.

You see, for authentication providers that support being signed into multiple accounts at once (like Microsoft), the user will be prompted to select an account to use when `vscode.authentication.getSession` with `createIfNone: true` is called.

**Previous behavior:**

This preference is remembered until `vscode.authentication.getSession` is called with the `ClearSessionPreference` flag.

**New behavior:**

This preference is remembered per-workspace until `vscode.authentication.getSession` is called in that workspace with the `ClearSessionPreference` flag.

This sets us up to allow an extension like GitHub Repos say "this workspace is this account and that workspace is that account".

Anyway, it's a lot of backstory, but the testing itself is pretty easy... All I want to you do is:

* Grab my test extension that leverages this API: [vscode-clearsessionpref-0.0.1.vsix.zip](https://github.com/microsoft/vscode/files/11315382/vscode-clearsessionpref-0.0.1.vsix.zip) (unzip it and run `Extensions: Install from VSIX...`)
* Open two windows each pointing to a different workspace
* Run the command `Run Clear Session Preference Test` in one, chose your work account
* In the other window, run the same command. Note: it should go directly to the notification that says what account you're logged in to
* Now, in that new window, click the "Clear session preference" button in the notification... follow the flow to add a new account (your personal Microsoft account)
* Reload both windows and run `Run Clear Session Preference Test`

Expected:
* The workspace that you didn't clear the session preference in should have the account as before (work)
* The workspace that you _did_ clear the session preference in should have the new account (personal)

<details><summary>What the code of the test extension looks like</summary>
<p>

```ts
import * as vscode from 'vscode';

export function activate(context: vscode.ExtensionContext) {
	let disposable = vscode.commands.registerCommand('vscode-clearsessionpref.helloWorld', async () => {
		const sessionMaybe = await vscode.authentication.getSession('microsoft', ['email'], { silent: true });
		const session1 = sessionMaybe ?? await vscode.authentication.getSession('microsoft', ['email'], { createIfNone: true });
		const yes = await vscode.window.showInformationMessage(`Account: ${session1.account.label}`, 'Clear session preference');
		if (yes) {
			const session2 = await vscode.authentication.getSession('microsoft', ['email'], { clearSessionPreference: true, createIfNone: true });
			await vscode.window.showInformationMessage(`Account: ${session2.account.label}`);
		}
	});

	context.subscriptions.push(disposable);
}

export function deactivate() {}
```

</p>
</details>

**Comment by hbons** [comment]
I'll be out of office and won't be able to test this round.

**Comment by roblourens** [comment]
Thanks for the test extension and clear steps!

**Comment by roblourens** [comment]
Should the description for `clearSessionPreference` be updated to describe the change?

**Comment by TylerLeonhardt** [comment]
@roblourens yeah you're right... it probably should. Wanna Create Issue?
