### ISSUE TITLE
Feature Request: make sidebar folder toggle behaviour configurable

### ISSUE THREAD

**Issue by hpcsc** [Microsoft/vscode#18072]
When going through the file tree in sidebar, I have a tendency to click on a folder to mark where I'm looking at. Same thing when I want to create a file under a folder

The current behaviour is to toggle open/closed it in a single click and sometimes it can be quite annoying for me, since I still want to keep it in the same way as before. With current behaviour, I need to click one more time to return it to previous state.

Is it possible to make a folder selected in a single click and toggle state in double click? Can make it configurable and leave the default as current behaviour

**Comment by bpasero** [comment]
I would move this into https://github.com/Microsoft/vscode/issues/9388
