### ISSUE TITLE
Test builtin profile templates

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#180731]
Refs: https://github.com/microsoft/vscode/issues/166359

- [x] win @karrtikr
- [x] mac @eleanorjboyd
- [x] linux @connor4312

Complexity: 3

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23180731%0A%0A&assignees=sandy081)

---

We now ship some builtin profile templates out of the box. You can create the profile using the builtin profile template from the profile creation flow - Settings Gear > Profile > Create Profile. Test creating profiles from builtin profile templates and make sure they are working as expected. Creating the profile again from the same template will ask you to either overwrite or create a new one. Do some exploratory testing.

**Comment by eleanorjboyd** [comment]
to confirm if I create a profile from a template, rename the created profile, then create another profile from that same template these are now distinct profiles and vscode should not ask if I want to have the first profile overridden right?
