### ISSUE TITLE
Any theme colours break after a while

### ISSUE THREAD

**Issue by ale-dg** [microsoft/vscode#180778]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 
-Version: 1.77.3
Commit: 704ed70d4fd1c6bd6342c436f1ede30d1cff4710
Date: 2023-04-12T09:41:48.638Z
Electron: 19.1.11
Chromium: 102.0.5005.196
Node.js: 16.14.2
V8: 10.2.154.26-electron.0
OS: Darwin arm64 22.4.0
Sandboxed: No

- OS Version: 
-macOS Ventura 13.3.1

Steps to Reproduce:

1. Choose any theme, either built-in in VsCode or any downloaded 
2. Code for a while (in Python, at least) and suddenly the colours break

I honestly have tried any theme, even removed all the downloaded themes and still the colours suddenly break down. See screenshot of an example that happened within a Jupyter Notebook file 

![Screenshot 2023-04-24 at 21 40 18](https://user-images.githubusercontent.com/106413328/234172002-291e5c3a-89cf-468d-9ec1-32c73619334d.jpeg)

**Comment by ale-dg** [comment]
Hi,

Maybe in the screenshot above the change between colours is not quite clear. See below for a more specific explanation on how the change happens, since it's been happening a lot lately.

Thanks

Best,

![Picture 1](https://user-images.githubusercontent.com/106413328/234465156-fe621eb4-fe54-4de7-b11a-8f299600dc8c.png)

**Comment by ale-dg** [comment]
Hi, 

Just for curiosity, I checked today with VSCode insiders and the same issue happens in it (even faster). What I noticed different today is that when starting the app, it takes a while to load the colours of any theme (something like 20 seconds or so). Also when scrolling or when changing windows to any other program, both VSCode versions kind of "lose" track of the theme and reloads the entire code for it, therefore it might be in those moments where the issue happens.

Thanks

Best

**Comment by hediet** [comment]
Does this reproduce with default settings? (go to user settings json and make the sure the file is empty, also make sure the workspace settings are clean as well)
Thanks for reporting!

**Comment by ale-dg** [comment]
Hi, 

Thank you for your answer. It happens either with a blank installation and when modifying the settings.json. When I installed the Insiders edition, I left it alone for a while and the issue is still there. As I mentioned above, it "normally" happens when either scrolling back to check something or when changing programmes i.e. from VSCode to Safari (or any other software). When working with a new installation and using the Dark+ theme, what I have been noticing is that VSCode reloads the entire formatting every time I scroll (even for a small amount of scrolling), so all the colours disappear and the entire text becomes white. Once I left it there idling and suddenly the colours appear for just the old code, but if I type something new, the formatting is not working. The same happens when I change to any other programme (the colours are gone and suddenly reappear, but not for new code). 

What is strange to me is, for instance, in the screenshot I've attached is that also happens like those... just typing in new code in the same line and the colours break. I have tried to replicate it again and again, but it is a very random thing. Actually those screenshots happened out of the blue and took the capture of them as those where entirely new lines of code. 

Thanks

Best

**Comment by ale-dg** [comment]
Hi @hediet 

Just following up on this issue. With the most recent update of VSCode, the issue of the colours breaking suddenly has not happened in these days. What has happened is the colours reloading when switching between programmes or even between tabs within VSCode. Sometimes happen when choosing different themes (which I guess is normal) but then VSCode seems to "remember" that there are colours needed. 

Best

**Comment by aeschli** [comment]
Can it be that this semantic highlighting?
Set the cursor on the word and invoke `Developer: Inspect Editor Scopes and Tokens`.
Add a screenshot of the hover.

**Comment by ale-dg** [comment]
Hi @aeschli 

Thank you for your answer. As I mentioned, this particular issue hasn't happened in these days. Even though, I attach you a picture on something I am working now. I haven't closed the issue since it still could happen with an update or something, so you can keep it in your radar (my current build is below).

Thanks

Best

Version: 1.78.2
Commit: b3e4e68a0bc097f0ae7907b217c1119af9e03435
Date: 2023-05-10T15:00:40.428Z (2 wks ago)
Electron: 22.5.2
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Darwin arm64 22.5.0
Sandboxed: No


![Screenshot 2023-05-26 at 11 46 50](https://github.com/microsoft/vscode/assets/106413328/c8ff4f04-b339-43f0-8428-ac212e8a78da)

**Comment by aeschli** [comment]
I'll close the issue then. Please reopen if you see it again.
