### ISSUE TITLE
Notebook markdown preview: typing in replace should not automatically switch to edit mode

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#180797]
Testing #180768

I find the current transition very harsh.
Can we instead transition to edit mode once the user clicks on the Replace button?
That way the transition will not be so rough. It will be triggered later, and by user pressing a button. Not by typing.

**Comment by rebornix** [comment]
Yeah, the thinking behind this having the switch less often if possible, but I agree with you that current behavior can be very unexpected.
