### ISSUE TITLE
node.js assertion `Assertion failed: (timeout != -1), function uv__io_poll, file ../deps/uv/src/unix/kqueue.c, line 256`

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#180707]
Build: https://dev.azure.com/monacotools/a6d41577-0fa3-498e-af22-257312ff0545/_build/results?buildId=212098
Changes: https://github.com/Microsoft/vscode/compare/16307b3...f0a3f5f

**Comment by bpasero** [comment]
This seems to be a native assertion exception in node.js itself, maybe related to the Electron update, not sure, but could also be specific to the Azure pipeline we run in:

```
  ResourceEditorInput
    ✔ basics
Assertion failed: (timeout != -1), function uv__io_poll, file ../deps/uv/src/unix/kqueue.c, line 256.

  EditorPane
##[error]Exit code 134 returned from process: file name '/Users/runner/runners/3.218.0/externals/node16/bin/node', arguments '"/Users/runner/work/_tasks/CmdLine_d9bafed4-0b18-4f58-968d-86655b4d2ce9/2.212.0/cmdline.js"'.
Finishing: Run unit tests (Electron)
```

I have no ideas how to address this from the unit test, I think this needs investigation what the assertion is about in libuv and then reason about it.

**Comment by bpasero** [comment]
Relevant `kqueue.c` contents:

https://github.com/nodejs/node/blob/6b06e89c7dfccec6792008302af1cee57649445c/deps/uv/src/unix/kqueue.c#L256

**Comment by Tyriar** [comment]
Happened again: https://dev.azure.com/monacotools/Monaco/_build/results?buildId=222610&view=results

This time in the setup-npm-registery.js step:

```
/bin/bash --noprofile --norc /Users/runner/work/_temp/15d83cf3-9153-4e4c-a9dc-ca52e13f61d4.sh
Assertion failed: (timeout != -1), function uv__io_poll, file ../deps/uv/src/unix/kqueue.c, line 256.
/Users/runner/work/_temp/15d83cf3-9153-4e4c-a9dc-ca52e13f61d4.sh: line 1:  2124 Abort trap: 6           node build/setup-npm-registry.js $NPM_REGISTRY
##[error]Bash exited with code '134'.
Finishing: Setup NPM Registry
```

**Comment by deepak1556** [comment]
Refs https://github.com/nodejs/node/issues/47241#issuecomment-1482563632

Fixed in Node.js >= 18
