### ISSUE TITLE
Description is not changing for terminals which are not interacted with

### ISSUE THREAD

**Issue by karrtikr** [microsoft/vscode#180851]
Testing microsoft/vscode-python#21102 https://github.com/microsoft/vscode/issues/171108

_Originally posted by @aiday-mar in https://github.com/microsoft/vscode-python/issues/21102#issuecomment-1521488421_

⚠️ signs only appears next to terminals which are dirty, as they require a relaunch to update the envs. The second has not been interacted with yet, so envs are updated without the need for relaunching it, but it seems that the description is not updated.

https://user-images.githubusercontent.com/61460952/234238206-9842cf35-9a58-40f8-9227-b3a580d289c2.mov

**Comment by karrtikr** [comment]
@meganrogge any idea what might be going on?

**Comment by meganrogge** [comment]
We automatically accept the env changes in terminals which haven't been interacted with by design. That is why the description for the non-interacted with terminal appears the way it does vs the one that has been interacted with which requires relaunching

**Comment by karrtikr** [comment]
> We automatically accept the env changes in terminals which haven't been interacted with by design.

I understand that, although the bug here is that we should automatically accept the description changes in such terminals as well.
