### ISSUE TITLE
Sticky scroll stills displays function after it is hidden

### ISSUE THREAD

**Issue by nicofrand** [microsoft/vscode#180832]
Sticky scroll still displays some functions even after they are hidden.

Example with this code:

```js
/**
 * File: file.js
 */

/**
 * @class mynamespace.Component class
 */
mynamespace.Component = function () {
	
};

/**
 * Fires a <i>onComponentTitleChanged</i> event on all registered listeners.
 * @private
 */
mynamespace.Component.prototype._fireTitleChanged = function () {
	this._listeners.forEach(l => {
		if (l.onComponentTitleChanged) {
			l.onComponentTitleChanged(this, this._title);
		}
	});
};

/**
 * Fires a <i>onComponentIconChanged</i> event on all registered listeners.
 * @private
 */
mynamespace.Component.prototype._fireIconChanged = function () {
	this._listeners.forEach(l => {
		if (l.onComponentIconChanged) {
			l.onComponentIconChanged(this, this._icon);
		}
	});
};

/**
 * Fires a <i>onComponentResized</i> event on all registered listeners.
 * @private
 */
mynamespace.Component.prototype._fireResized = function () {
	this._listeners.forEach(l => {
		if (l.onComponentResized) {
			l.onComponentResized(this);
		}
	});
};

/**
 * Fires a <i>onComponentMinimized</i> event on all registered listeners.
 * @private
 */
mynamespace.Component.prototype._fireMinimized = function () {
	this._listeners.forEach(l => {
		if (l.onComponentMinimized) {
			l.onComponentMinimized(this, this._isMinimized);
		}
	});
};

/**
 * Fires a <i>onComponentMaximized</i> event on all registered listeners.
 * @private
 */
mynamespace.Component.prototype._fireMaximized = function () {
	this._listeners.forEach(l => {
		if (l.onComponentMaximized) {
			l.onComponentMaximized(this, this._isMaximized);
		}
	});
};

/**
 * Fires a <i>onComponentClosed</i> event on all registered listeners.
 * @private
 */
mynamespace.Component.prototype._fireClosed = function () {
	for (var i = this._listeners.length - 1; i >= 0; --i) {
		var l = this._listeners[i];
		if (l.onComponentClosed) {
			l.onComponentClosed(this);
		}
	}
};

```
See, `mynamespace.Component.prototype._fireTitleChanged` should not be displayed as sticky:

![image](https://user-images.githubusercontent.com/3419050/234319252-82b50bed-886a-4844-9a49-32c233c3ab43.png)

Version: 1.77.3
Commit: 704ed70d4fd1c6bd6342c436f1ede30d1cff4710
User Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/113.0
Embedder: vscode.dev

**Comment by aiday-mar** [comment]
Hi thanks for filing the bug, the lines stuck by sticky scroll use by default the document symbols provided by extensions. I suspect the issue you see could be caused by this. Could you please tell me, what is the value of your setting `Editor > Sticky Scroll: Default Model` and the extensions, if any, that you have installed from the marketplace?

**Comment by nicofrand** [comment]
Hi!

Thanks for answering.
After reproducing on vscode.dev I cleaned the code to make it smaller and removed

```js
/**
 * File: file.js
 */
```

which removed the syntax highlighting and so on.

I edited the code in the post above to fix that.
With that you should be able to reproduce from a brand new vscode.dev (no account linked, no repo, no extensions, just enable sticky scroll).

In case I am missing a bit of context with vscode.dev (localstorage etc) here are STR that should be enough:

1. Open vscode.dev in a private window
2.  Press `CTRL`+`ALT`+`N` to open a new file and paste the code from the ticket above
3.  Press `CTRL` + `,` and search for "sticky"
4.  Check "Editor > Sticky Scroll: Enabled"
5. Go back to your file (Untitled-1)
6. Scroll to the bottom, at least past `mynamespace.Component.prototype._fireTitleChanged`

I hope that's enough, let me know if it isn't.

**Comment by aiday-mar** [comment]
I see thanks for letting us know. The issue has been noted, and worked on in due time.

**Comment by aiday-mar** [comment]
Hi @nicofrand, I discussed the issue with the team. The sticky lines are rendered that way because they rely on the outline model (which you can find in the outline explorer). For the particular example you gave, the outline model does not coincide with the hierarchical architecture of the scopes. You may change the model used for the sticky model for the settings under: `Editor > Sticky Scroll: Default Model`, and choose between the outline model, the folding provider model, the indentation model. The latter two could render a better experience. 

An issue has been opened to allow extensions to define their own sticky models: https://github.com/microsoft/vscode/issues/168428, and thereby address cases such as this one. In the meantime this issue will be closed.

**Comment by nicofrand** [comment]
Hi @aiday-mar!

Thank you for your answer. The foldingProviderModel indeed behaves likes I expected.
Is there a documentation somewhere explaining the differences? I am not sure I understand correctly when the outline model would differ as those `mynamespace.Component.prototype._fireXXX| methods are on the same level…

**Comment by aiday-mar** [comment]
H @nicofrand. The outline model essentially describes the code architecture. In your example, Component is part of namespace and inside of namespace there are 6 functions (the ones starting with an underscore). The strategy adopted at VS Code has been to consider the namespace scope as starting on line 16 in your example. The Component scope starts also at line 16 and the underscore functions start on various other lines after that.

The folding provider model is a model of the lines where the folding ranges are to be rendered. The folding provider model is used to decide where to render the folding arrows in the side gutter. The folding provider model can be chosen for sticky scroll, in which case the lines stuck by sticky scroll will closely align to the folding ranges. 

The indentation model (which always exists) is a fallback model used by the folding ranges when no folding provider model exists. It is used in the last resort by sticky scroll by default, when no outline model and no folding provider model exists. It essentially is a model of the indentation scopes.
