### ISSUE TITLE
Quitting VSCode w/o closing window leaves all shells and tasks running forever. (MacOS).

### ISSUE THREAD

**Issue by joshstrike** [microsoft/vscode#180894]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.77.3
- OS Version: MacOS 12.6

Integrated terminal shells and their processes continue running forever after VSCode is quit. New ones are spawned when VSCode is re-opened. This includes zsh and node (tsc-watch).

Manually closing the workspace window prior to quitting _does_ correctly terminate the shells.

Steps to Reproduce:

1. Open a shell or a task running tsc-watch in the integrated terminal.
2. Quit VSCode without closing the workspace window first.

**Comment by meganrogge** [comment]
what's the value of `terminal.integrated.persistentSessionReviveProcess` for you?

there's a known issue with node processes hanging around that will soon be fixed

**Comment by deepak1556** [comment]
Merging to https://github.com/microsoft/vscode/issues/174956, refs https://github.com/microsoft/vscode/issues/174956#issuecomment-1526988366
