### ISSUE TITLE
run without debugging icon to be present

### ISSUE THREAD

**Issue by ranjan-ranjan** [Microsoft/vscode#18086]
- VSCode Version: 1.8.1
- OS Version: Windows 10 Pro 1607

I am debugging a python program. I feel the need of "Run without debugging" icon. Snapshot is attached as reference.
![2](https://cloud.githubusercontent.com/assets/16834561/21635876/35fbc7b6-d286-11e6-9393-f0b872b8a7ae.png)

**Comment by isidorn** [comment]
Run without debugging is not such a key feature that it deserives an icon - just like many of the other commands we have availble in the command pallete. You can add a custom keybinding to it so it is easy for you to trigger it.

Closing this as designed. If we put all the actions into icons vscode ux will no longer be minimalstic and would become bloated.
