### ISSUE TITLE
opening the find widget messes up the notebook view

### ISSUE THREAD

**Issue by amunger** [microsoft/vscode#180857]
Testing #180768

1. open a notebook and add a markdown cell with content at the top
2. open the replace widget and find an existing string in the markdown cell
3. Put focus somewhere else in the notebook, then press ctrl+f to focus the find widget
🐛 markdown cell is bumped up out of the view

![searchUIbump](https://user-images.githubusercontent.com/2019016/234359619-31f24058-1551-43a4-9713-cb0edd4d0b13.gif)

**Comment by rebornix** [comment]
@amunger you found good bugs!
