### ISSUE TITLE
visual studio code reports error in temporary file when compiling xaml

### ISSUE THREAD

**Issue by HowardPWeiss** [microsoft/vscode#180877]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 
- OS Version: 

Steps to Reproduce:

I am building an MVVM WPF project in C# on Linux.
Visual Studio Code reports an error in a temporary file used by the XAML compiler

An example 

/home/howard/Desktop/SudokuUnoTest/SudokuUnoTest/SudokuUnoTest/SudokuUnoTest/Uno.UI.SourceGenerators/Uno.UI.SourceGenerators.XamlGenerator.XamlCodeGenerator/MainPage_c6813ceb9e79be38b2f92b31a9dd5cd2.cs(1744,107): error CS0030: Cannot convert type 'string' to 'double' [/home/howard/Desktop/SudokuUnoTest/SudokuUnoTest/SudokuUnoTest/SudokuUnoTest/SudokuUnoTest.csproj::TargetFramework=net7.0]

Note that file being compiled is being created during the Xaml compilation,  The file is deleted at the end of the build.  Therefore, there is not way to determine what is causing the error

The offending XAML code is as follows

<ItemsControl  ItemsSource="{Binding Path=RectangleCollection,Mode=TwoWay}">
            <ItemsControl.ItemsPanel>
                <ItemsPanelTemplate>
                    <Canvas x:Name="Gameboard" Margin="13,105"  Width="800" Height="922" Background="Red"  VerticalAlignment="Top" HorizontalAlignment="Left">
                    </Canvas>
                </ItemsPanelTemplate>
            </ItemsControl.ItemsPanel>
             <ItemsControl.ItemContainerStyle>
                <Style TargetType="ContentPresenter">
                    <Setter Property="Canvas.Left" Value="{Binding X}"/>
                    <Setter Property="Canvas.Top" Value="{Binding Y}"/>
                </Style>
            </ItemsControl.ItemContainerStyle>
            <ItemsControl.ItemTemplate>
                <DataTemplate >
                    <Rectangle 
                        Stroke="Black" 
                        Height="{Binding Height}"
                        Width="{Binding Width}"
                        StrokeThickness="{Binding StrokeThickness}" />
                </DataTemplate>
            </ItemsControl.ItemTemplate>
        </ItemsControl>

where Rectangle Collection is defined in the View Model as

public ObservableCollection<RectItem> RectangleCollection { get; set; }

and RectItem is a class

public class RectItem
    {
        public double X { get; set; }
        public double Y { get; set; }
        public double Width { get; set; }
        public double Height { get; set; }
        public double StrokeThickness {get; set;}
    }
There seems to be no way to prevent dotnet from deleting the Uno.UI.SourceGenerators/ folder

Howard Weiss

**Comment by meganrogge** [comment]
> There seems to be no way to prevent dotnet from deleting the Uno.UI.SourceGenerators/ folder

pls create an issue in the dotnet repo
