### ISSUE TITLE
Extension-contributed providers don't show up in drop widget

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode#180878]
Testing #180741

I modified the extension API sample to consume the drop proposal (also added it to `enabledApiProposals`):
```ts
	context.subscriptions.push(vscode.languages.registerDocumentDropEditProvider(selector, new ReverseTextOnDropProvider(), { id: 'reversetext', dropMimeTypes: [ 'text/*' ] }));
	context.subscriptions.push(vscode.languages.registerDocumentDropEditProvider(selector, new FileNameListOnDropProvider(), { id: 'filenamelist', dropMimeTypes: [ 'files' ] }));
```
and have a label
```ts
		return { insertText: snippet, label: 'Insert as filename list' };
```

But neither of the provided labels show up as options in the drop widget when I'm dropping either file names or text.

**Comment by joyceerhl** [comment]
If I change `dropMimeTypes` to `*/*`, then my providers get called. But I would expect it to work with `[ 'files' ]` which is what the docstring says to do for dropping files, or `text/*` for dropping text.

**Comment by mjbvz** [comment]
Thanks for testing

There's a bug with the `text/*` wildcard

For the `files` case, were are you dragging from? This special type will only work when dragging from an external app into VS Code (these are the only drops that create `DataTransferFile` types). For dragging content in VS Code, such as from the explorer, you can instead use the `text/uri-list` mime type

**Comment by joyceerhl** [comment]
Ah, that's why, I was dragging from the VS Code explorer view. I was just using `files` wrong then, maybe worth a comment in the docstring for the proposal?
