### ISSUE TITLE
Linked editing does not stop once you type space or a non tag character

### ISSUE THREAD

**Issue by luabud** [microsoft/vscode#180897]
Testing #180769

I could have misunderstood the "Linked editing should stop once you type space or a non tag character" bullet point, but I expected the edit to stop once I entered space and/or the invalid tag:

![linkededitingbug](https://user-images.githubusercontent.com/45497113/234430017-b1cf9872-0fea-4aca-8491-1b9d07b18d5a.gif)

**Comment by mjbvz** [comment]
Linked editing should happen automatically as you type in the tag so no need to press `F2`

What you're using is the standard rename UI (`F2`), which will not stop if you enter space into its input box
