### ISSUE TITLE
Markdown "code cell source" still being searched even when toggled off

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#180808]
Testing #179922

1. Open clone of this repo in VS Code
2. Open the my-endgame.github-issues notebook
3. Run some queries from the notebook
4. Change the toggles in the search filter so that "Code Cell Source" is toggled off and "Code Cell Output" is toggled on.
5. Search for "microsoft/vscode"
6. ✅ See correct results for my-endgame.github-issues
7. However, the results for inbox.github-issues include markdown code cell source

![image](https://user-images.githubusercontent.com/38270282/234254417-28052b75-9078-4db2-aa23-ceddcec75b21.png)

**Comment by andreamah** [comment]
To get the filters to apply, we currently require the notebook to be opened. So it makes sense that `inbox.github-issues` would just search the raw ipynb json text. Does it make sense via that context?
