### ISSUE TITLE
Expand selection and shrink selection in HTML

### ISSUE THREAD

**Issue by oliverjanik** [Microsoft/vscode#1808]
Continuing from here: #495

Expand Select and shrink select work OK in typescript, json and JS. It seems it's not implemented for HTML.

**Comment by joaomoreno** [comment]
@jrieken ping

**Comment by esko** [comment]
Seconding this. It would be useful for both selecting content inside HTML element and selecting attribute values/names.

**Comment by oliverjanik** [comment]
And extending selection hierarchically up the element tree.

**Comment by sortegam** [comment]
+1

**Comment by JimNewkirk** [comment]
Let me upvote this as strongly as possible. HTML is so highly structured, and in such a variety of ways, that selection of specific tags and strings is really crucial to working quickly and well. Without this feature, editing becomes not just unhandy, but too error-prone for my purposes. It would transform the utility of the editor if the same selection abilities were present in HTML as in other languages.

**Comment by oliverjanik** [comment]
If anyone is looking for a reference Resharper for Visual Studio does this really well.

**Comment by bodiam** [comment]
IntelliJ is also quite at this, but Visual Studio code is quite lacking in this. I'm commenting on this because expand selection is my most used shortcut in IntelliJ, and I tried the same in Visual Studio Code, just to find out it's basically not working. I'm hoping someone might find the time to improve this feature.

**Comment by kaiwood** [comment]
Just in case it helps someone, I link to my answer to this topic from Stackoverflow a while ago: http://stackoverflow.com/questions/40949929/how-do-i-select-the-insides-of-div-in-visual-studio-code/40971959#40971959

It's not perfect, but with this keybinding setup, you basically use Emmet's selection / balancing commands in HTML files and standard shrink / grow for everything else. Works for me, the only caveat is that you can't "shrink back" to the selected attributes.

**Comment by JimNewkirk** [comment]
Very helpful, kaiwood - thanks.

**Comment by entriol** [comment]
In case if anyone out there is still looking for this feature, see `expand-region` extension. It might help at the moment.

**Comment by Maxhodges** [comment]
+1 two years on and this feature still sucks. it skips many levels of hierarchy in HTML, going from current link to entire file instead of climbing nested levels of tags. IntelliJ (Webstorm) does this right.

**Comment by scottbickell** [comment]
Any updates on this? Expand selection is terrible. In an HTML doc, the selection goes from one word, one line, to entire document. As @Maxhodges said, IntelliJ IDEs do this right and it is one of the main reasons I continue to use their products instead of VS Code. Come on people, figure it out.

**Comment by TranMacTien** [comment]
nice!

**Comment by anantoghosh** [comment]
@Maxhodges @scottbickell  use emmet's balance in/out instead for html/jsx.
as mentioned in https://github.com/Microsoft/vscode/issues/1808#issuecomment-267956024
(balance in is still broken.)  

![2018-05-13_16-02-43](https://user-images.githubusercontent.com/12339068/39966304-41d8390e-56c7-11e8-9ac2-5a4bd7ed497f.gif)

Try it from the command menu.

You can add shortcut for it as required.
```json
  {
    "key": "shift+alt+right",
    "command": "editor.emmet.action.balanceOut",
    "when": "editorTextFocus && editorLangId == html && editorHasSelection"
  },
  {
    "key": "shift+alt+left",
    "command": "editor.emmet.action.balanceIn",
    "when": "editorTextFocus && editorLangId == html && editorHasSelection"
  },
  {
    "key": "shift+alt+right",
    "command": "editor.emmet.action.balanceOut",
    "when": "editorTextFocus && editorLangId == javascriptreact && editorHasSelection"
  },
  {
    "key": "shift+alt+left",
    "command": "editor.emmet.action.balanceIn",
    "when": "editorTextFocus && editorLangId == javascriptreact && editorHasSelection"
  },
  {
    "key": "shift+alt+right",
    "command": "editor.emmet.action.balanceOut",
    "when": "editorTextFocus && editorLangId == typescriptreact && editorHasSelection"
  },
  {
    "key": "shift+alt+left",
    "command": "editor.emmet.action.balanceIn",
    "when": "editorTextFocus && editorLangId == typescriptreact && editorHasSelection"
  },
```

**Comment by Maxhodges** [comment]
@anantoghosh that's kind of rubbish for me. Try on something with quotes. It should do word, the string inside quotes, then string with quotes
and when retracting it resolves to another string entirely

![image](https://user-images.githubusercontent.com/957271/39980346-6fa42a5e-5786-11e8-9cc2-694616482eeb.png)

**Comment by anantoghosh** [comment]
I have created an issue for this https://github.com/Microsoft/vscode/issues/49777
let's see if we make any progress.

**Comment by octref** [comment]
Currently, you can run "Emmet: Balance (ourward)" or "Emmet: Balance (inward)" command for this functionality.

There's plan to support Expand Selection for all languages, and we'll do it for HTML/CSS using emmet.

You can track the new feature in: https://github.com/Microsoft/vscode/issues/65925

**Comment by Maxhodges** [comment]
sorry but Emmet outward falls very short of a good solution. It only considers tags, not text elements. In Webstorm it will expand to the current word, then words within quotes, then include the quotes, then the tag. Emmet just grabs everything in the tag. Often we use this to grab a word, or a string with or without quotes.

![image](https://user-images.githubusercontent.com/957271/50621745-3c4aa700-0f4b-11e9-96b4-196fb7038e3a.png)

**Comment by Maxhodges** [comment]
@octref try this with Emmet Balance in/out! It fails miserably. Please reopen the issue when you are done.
![wb33175780-28f81182-d0a0-11e7-96b7-21324684dd7e](https://user-images.githubusercontent.com/957271/50621889-710b2e00-0f4c-11e9-91e9-eefc85f657de.gif)

**Comment by oliverjanik** [comment]
Thank you @Maxhodges for investing time into this. I too feel strongly about good syntax aware expand/shrink selection, but it seems mostly ignored brushed off by people who have not experienced the joy of using it.

**Comment by octref** [comment]
@Maxhodges JavaScript/TypeScript balance outward will be provided by TypeScript language service. See https://github.com/Microsoft/vscode/issues/4795.

I'll start with Emmet and improve it later to have more granularity.

**Comment by octref** [comment]
This will be available in tomorrow's insiders:

![html-selection](https://user-images.githubusercontent.com/4033249/51643241-a211c980-1f20-11e9-819d-9e28946f30b9.gif)

Feel free to open new issues if something doesn't work as expected.

**Comment by oliverjanik** [comment]
Fantastic news!
