### ISSUE TITLE
Nothing happen when run code-exploration

### ISSUE THREAD

**Issue by paulacamargo25** [microsoft/vscode#180882]
Testing #180783

I have open Vscode Exploration from finder with two tabs. I open an external terminal and run vscode-exploration, nothing happened, I still only see the 2 tabs.

**Comment by bpasero** [comment]
The command is `code-exploration` and you need to this command to enable it:

<img width="742" alt="image" src="https://user-images.githubusercontent.com/900690/234477970-d3ac70ac-d696-481d-b737-70f4fe48ed9f.png">
