### ISSUE TITLE
Linked editing not working for qualified names

### ISSUE THREAD

**Issue by eleanorjboyd** [microsoft/vscode#180865]
Let me know if I misunderstood this bullet point but I do not think linked editing is working for qualified names. 

https://user-images.githubusercontent.com/26030610/234368542-5030060f-f5cb-41af-9aa9-293fd87d20fd.mov

Testing #180769

**Comment by mjbvz** [comment]
It looks like that tag has already been closed What if you remove the `/`?

**Comment by eleanorjboyd** [comment]
yep that was the reason, looks good now thanks!
