### ISSUE TITLE
"Install in devcontainer" on a pre-release extension installs the stable version

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#180893]
- Install the pre-release version of the Python extension locally
- Open a devcontainer
- Click "install in devcontainer"
- It installs the stable version on the remote

With that button I assume that I am installing the same configuration that is already installed, so it's confusing to get a different version

**Comment by alhuede-thncs** [comment]
This also means if there is no current release version, it will not install it in the container

**Comment by alhuede-thncs** [comment]
This also means if there is no release version available it will not install it in the devcontainer
