### ISSUE TITLE
upon "running" program, it should automatically exit

### ISSUE THREAD

**Issue by ranjan-ranjan** [Microsoft/vscode#18088]
- VSCode Version: 1.8.1
- OS Version: Windows 10 Pro 1607

I am running python program. Upon doing "Ctrl + F5", it should automatically exit. This the current result of the action.
![3](https://cloud.githubusercontent.com/assets/16834561/21636174/a00610d4-d287-11e6-9c5d-b59a0da23743.png)

**Comment by isidorn** [comment]
This issue is coming form the pyhton extension
Can you please file it there https://github.com/DonJayamanne/pythonVSCode

Namely the problem is that the python debug adapter should emit an 'exit' event when a program stops - when that happens vscode will automatically close the action bar.
