### ISSUE TITLE
Empty search result from currently open notebook

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#180807]
Testing #179922

1. Open clone of this repo in VS Code
2. Open the my-endgame.github-issues notebook
3. Run some queries from the notebook
4. Search for some text that's some rendered output
5. There's now an empty file node in the search view:

![image](https://user-images.githubusercontent.com/38270282/234252883-3a5463e9-96c4-44e7-8ea3-5b1cf5e3a5ff.png)

**Comment by andreamah** [comment]
Are you still able to get the empty node? I just see the error in the second screenshot, which should be a duplicate of https://github.com/microsoft/vscode/issues/178286

**Comment by alexr00** [comment]
I'm no longer able to repro the empty node.
