### ISSUE TITLE
VS "The window is not responding"

### ISSUE THREAD

**Issue by PedroCasavilcaSilva** [microsoft/vscode#180855]
Type: <b>Performance Issue</b>

I'm coding in Julia using VS. My code is long.
These last weeks, I've had two main problems:
1. When I open VS, the window freezes, and I get the following message: "The window is not responding". And after around 20 seconds, VS shows the codes I've used in the previous session. 
2. When I execute lines of codes plotting some graphs, it now takes a lot of time to show them. And when I go from the plots window back to the code window and then return to the plot window, they are empty. The plots take some seconds to be shown again.

Could you please help me to solve this annoying issue?

VS Code version: Code 1.77.3 (704ed70d4fd1c6bd6342c436f1ede30d1cff4710, 2023-04-12T09:16:02.548Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-10885H CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|63.75GB (49.70GB free)|
|Process Argv|--crash-reporter-id 4deaf8fb-376c-44f7-9e60-caa330612d65|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	   122	 26340	code main
    0	    97	  5792	shared-process
    0	    89	 27744	     ptyHost
    0	     6	  7368	       console-window-host (Windows internal process)
    0	   758	 24152	       "C:\Users\pedri\AppData\Local\Programs\Julia 1.5.3\bin\julia.exe" -i --banner=no --project=C:\Users\pedri\.julia\environments\v1.5 c:\Users\pedri\.vscode\extensions\julialang.language-julia-1.38.2\scripts\terminalserver\terminalserver.jl \\.\pipe\vsc-jl-repl-76c65d59-417c-45e9-b56f-4ac84fede21c \\.\pipe\vsc-jl-cr-baa6b312-acdd-4ea4-8f82-1c86c30a8938 USE_REVISE=true USE_PLOTPANE=true USE_PROGRESS=true ENABLE_SHELL_INTEGRATION=true DEBUG_MODE=false
    0	     4	 11052	         C:\WINDOWS\system32\cmd.exe /c C:\Users\pedri\.julia\artifacts\aa3e0157eff69c2604027b85f1ff85a59bfae52f\kaleido.cmd plotly --disable-gpu --no-sandbox
    0	    32	 11020	           .\bin\kaleido.exe  plotly --disable-gpu --no-sandbox
    0	    28	  1196	             utility-process
    0	    33	 18192	             gpu-process
    0	    55	 34128	             window
    0	     6	 26824	       console-window-host (Windows internal process)
    0	    63	 30376	       C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe -noexit -command "try { . \"c:\Users\pedri\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\contrib\terminal\browser\media\shellIntegration.ps1\" } catch {}"
    0	    88	 24440	window [2] (Issue Reporter)
    0	    84	 28336	fileWatcher [1]
    0	    67	 30540	   crashpad-handler
    0	    70	 32676	   utility-network-service
    0	   330	 34012	   gpu-process
    0	   167	 34368	extensionHost [1]
    0	   812	 16392	     "C:\Users\pedri\AppData\Local\Programs\Julia 1.5.3\bin\julia.exe" --startup-file=no --history-file=no --depwarn=no main.jl C:\Users\pedri\.julia\environments\v1.5 --debug=no \\.\pipe\vsc-jl-cr-baa6b312-acdd-4ea4-8f82-1c86c30a8938 "" c:\Users\pedri\AppData\Roaming\Code\User\globalStorage\julialang.language-julia download https://www.julia-vscode.org/symbolcache --detached=no
    0	    10	  9844	       console-window-host (Windows internal process)
    0	   191	 34556	window [1] (PCasavilca_solution.jl - Untitled (Workspace) - Visual Studio Code)
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (PCasavilca_solution.jl - Untitled (Workspace) - Visual Studio Code)
|    Folder (Lecture Programs): 44 files
|      File types: pdf(25) jl(16) xlsx(1)
|      Conf files:
|    Folder (PS): 233 files
|      File types: png(80) jl(66) pdf(19) tex(7) log(7) aux(7) blg(7) bbl(7)
|                  zip(5) out(4)
|      Conf files:
|    Folder (Pros Numerical Solution): 40 files
|      File types: jl(23) jld2(12) txt(2) pdf(2)
|      Conf files:;
```

</details>
<details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
language-julia|jul|1.38.2

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyonecf:30548226
vscccc:30610679
nodejswelcome1:30587005
282f8724:30602487
pyind779:30671433
89544117:30613380
pythonsymbol12:30671437
a9j8j154:30646983
showlangstatbar:30672706
azdwalk:30721579
pythonms35:30701012
pythonfmttextcf:30716743

```

</details>

**Comment by meganrogge** [comment]
Please see https://github.com/Microsoft/vscode/wiki/Performance-Issues for creating actionable performance problem issues.
/label info-needed

**Comment by deepak1556** [comment]
@PedroCasavilcaSilva do you have Mcafee AV installed ? We have had multiple reports of the AV slowing down the application, refs https://github.com/microsoft/vscode/issues/178962

**Comment by PedroCasavilcaSilva** [comment]
Thank you for your comments.
1. @meganrogge Thanks. Here I attach: 
- CPU profile:
[CPU profile CPU-20230426T234114.356Z.cpuprofile.txt](https://github.com/microsoft/vscode/files/11338314/CPU.profile.CPU-20230426T234114.356Z.cpuprofile.txt)

- Renderer profile:
[Renderer profile CPU-20230426T203531.txt](https://github.com/microsoft/vscode/files/11338405/Renderer.profile.CPU-20230426T203531.txt)

- I followed the instructions to create the shared-process profile but "toggle shared-process" doesn't appear to be executed.
- 
- Two screenshots: (i) error when opening VS; and (ii) the Process Explorer. 
- ![1 Error message](https://user-images.githubusercontent.com/127336938/234731309-33967997-548f-42fb-a022-2c5cacf2c039.png)
![2 Process explorer](https://user-images.githubusercontent.com/127336938/234731316-a935d506-ad66-43a7-8a8d-58205a7a8da4.png)

2. @deepak1556 Thanks. Yes, I do have Mcafee AV installed. By the previous webpage that Megan sent me, it seems that the issue is not only that VS takes time to start but also that it becomes laggy when execute other commands. I'll check the reference and let you know. 

Please, let me know if there is anything else I can do.

Best,

Pedro.

**Comment by deepak1556** [comment]
@PedroCasavilcaSilva It would be good to check if the issue is mitigated following the steps at https://github.com/microsoft/vscode/issues/178733#issuecomment-1500812938

**Comment by PedroCasavilcaSilva** [comment]
@deepak1556 Thank you for the recommendation. I followed the instructions, tried VS these couple of days and everything is working much better. Thanks!
