### ISSUE TITLE
Testing notebook output scrolling: Unexpected setting value

### ISSUE THREAD

**Issue by bamurtaugh** [microsoft/vscode#180840]
Testing #180761

- Disable scrolling output via command `Notebook: toggle scroll cell output`
- Select `Adjust cell output settings`
- ![image](https://user-images.githubusercontent.com/25310137/234333640-fe0c163a-9f66-44a9-a97f-0bedfe318d9b.png)
- The scrolling setting is enabled, which I didn't expect
- ![image](https://user-images.githubusercontent.com/25310137/234333732-312d0195-06d8-48de-91c1-38ad6846106a.png)

**Comment by amunger** [comment]
The setting is for the initial rendering of all outputs, whereas the command will change a single cell's output. I'll see if I can clarify that in the description
