### ISSUE TITLE
[insiders] Gutter icons are stretched and cropped when adding breakpoints

### ISSUE THREAD

**Issue by DanTup** [microsoft/vscode#180834]
Presumably related to #5923. Adding breakpoints to lines with gutter icons causes the icon to be stretched and cropped:

![Apr-25-2023 16-18-54](https://user-images.githubusercontent.com/1078012/234324181-bd0f9215-6cbf-4b2c-9963-5662c43093b6.gif)

I don't know if related, but I'm using `gutterIconSize`:

```ts
vs.window.createTextEditorDecorationType({
	gutterIconPath: vs.Uri.parse(docsIconPathFormat.replace("$1", iconName)),
	gutterIconSize: "75%",
})
```

**Comment by joyceerhl** [comment]
The problem is that we set each decoration `div`'s width to be the width of the entire gutter (which is sized to fit potentially multiple decorations, so `gutterIconSize` sets `background-size` which ends up stretching the decoration to fit the entire gutter instead of just its lane.

**Comment by DanTup** [comment]
Fix looks good, thanks!

/verified
