### ISSUE TITLE
Renaming a component doesn't change references  

### ISSUE THREAD

**Issue by luabud** [microsoft/vscode#180898]
Testing #180769

I have two files open, one called "MyComponent2.tsx" with the following content:
```tsx
import React from 'react';

function MyComponent2() {
        
  return (
    <div>
      <header>
        <nav>
          <ul>
            <li><a href="/">Home</a></li>
            <li><a href="/about">About</a></li>
            <li><a href="/contact">Contact</a></li>
          </ul>
        </nav>
      </header>
      <main>
        <h1>Welcome to My Website!</h1>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam hendrerit ipsum eu tortor bibendum fringilla.</p>
        <p>Maecenas ut semper dolor. Praesent finibus arcu at augue convallis, ac vestibulum dui luctus.</p>
      </main>
      <footer>
        <p>&copy; 2023 My Company. All rights reserved.</p>
      </footer>
    </div>
  );
}

export default MyComponent2;
```

And then I have another one called "App.tsx"
```tsx
import React from 'react';
import MyComponent2 from './MyComponent2';

function App() {
  return (
    <div>
      <p>My App</p>
      <MyComponent2></MyComponent2> 
    </div>
  );
}

export default App;
```

Renaming `MyComponent2` on line 8 in the App.tsx file edits both tags correctly, but it doesn't rename the component itself. If I rename the symbol on line 2, it updates the tags correctly:

![linkededitingbug3](https://user-images.githubusercontent.com/45497113/234431408-76f3d150-7f26-4f4c-a2cb-6fc6966264bc.gif)

I also noticed that if I only have `<MyComponent2 />` on line 8 instead of the opening and closing tags, and I try to rename it, it seems to fail silently. Happy to file a separate bug if it'd be helpful:

![linkededitingbug4](https://user-images.githubusercontent.com/45497113/234431754-6ec7fd9f-74bb-4494-969b-6e90276cf3c9.gif)

**Comment by mjbvz** [comment]
When you're on a tag, both linked editing and F2 (post #159534) only rename the matching tag. They don't rename all references to the tag. For that you can run `F2` on the component itself

This behavior matches how linked editing and F2 work in html files
