### ISSUE TITLE
Vscode is not updating on windows shutdown/reboot

### ISSUE THREAD

**Issue by soredake** [microsoft/vscode#180814]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.77.3
- OS Version: Windows 11 (happens on 10 too)

Steps to Reproduce:

1. Have windows 11/10
2. Install older vscode version.
3. Wait for vscode to download update.
4. Initiate reboot/shutdown.
5. You will see "Vscode is updating" (don't remember exact text).
6. After rebooting you will still that vscode is not updated (probably windows kills it faster than vscode can update).

**Comment by joaomoreno** [comment]
#52855

**Comment by soredake** [comment]
@joaomoreno it's not duplicate, my vscode is not LOST, it's just not updated.

**Comment by joaomoreno** [comment]
@soredake Yes, I agree. But the fix is the same: we must have VS Code participate in the Windows shutdown lifecycle phase and prevent it from shutting down while an update is pending.

**Comment by soredake** [comment]
@joaomoreno can at least https://github.com/microsoft/vscode/issues/52855 title be rename to something more general like "Vscode updating problems on windows shutdown (lost/not updated)"?

**Comment by soredake** [comment]
https://github.com/microsoft/vscode/issues/181762
