### ISSUE TITLE
How do I compile vscode?

### ISSUE THREAD

**Issue by Barbacamanitu** [Microsoft/vscode#18083]
I've cloned the source. I've run scripts/npm install. I've run npm run watch. I've tried gulp vscode-win32.
These all build the typescript stuff, but nothing builds the executable. I can't find any information on this, because everytime I google "how to compile vscode" or anything similar, I find hundreds of articles about "how to compile stuff in vscode".

The documentation here: https://github.com/Microsoft/vscode/wiki/How-to-Contribute is extremely lacking. I've done everything it says and have not gotten anything built.

**Comment by sandy081** [comment]
Link here https://github.com/Microsoft/vscode/wiki/How-to-Contribute explains how one can contribute to VS Code by setting up development workspace for VS Code, but not how to build VS Code. Building VS Code application is proprietary and hence this is not shared, but you can always build your own open source version of VS Code by cloning it. It is based on Electron platform, so you can check how to build an electron based apps and follow that. 

Thanks
