### ISSUE TITLE
Not clear how to use notebook.codeActionsOnSave and editor.codeActionsOnSave

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#180846]
Testing #180765

If I'm just looking at these settings for the first time, it's not clear what the shape of the object is supposed to be, or what the boolean value means. 

Also, the notebook setting's description says "a series of codeactions" which implies that there is some order, does it always run the commands in the order of keys in the object or is the order not guaranteed?

**Comment by Yoyokrazy** [comment]
Had a couple chats offline, I'll just be removing the setting for now. It'll likely be reintroduced alongside proper codeaction support later on in the next iteration. There was a misunderstanding surrounding the behavior of `editor.codeActionsOnSave`, which led to nb.codeActionsOnSave picking up the different functionality.

**Comment by Yoyokrazy** [comment]
Closing due to revised functionality, this is outdated in regard to the current implementation.
