### ISSUE TITLE
IDE Theme PNG files broken when opening Welcome Screen in HTTPS with Docker when using VS Code Server

### ISSUE THREAD

**Issue by DJlee139** [microsoft/vscode#180853]
Seeing failures to get the ide theme png files when on the welcome screen. When I test on my machine's localhost on http, everything seems to work fine but when testing on a docker container over https they fail to load. Everything else seems to be working fine aside from these, so I don't suspect it has something to do with my container or setup.

Steps to replicate:

Launch vs code over https
Go to welcome page
Select the theme tile (might need to select a different file first)
The other strange thing is that the other png files for other tiles seem to work so perhaps it's something with the extension that it pulls the themes from.

![](https://user-images.githubusercontent.com/4110496/230160829-07b67757-2b6e-424a-b173-bb66241f85da.png)

I've seen similar issues in coder's code-server which wraps vs code server
https://github.com/coder/code-server/issues/4483 with the fix https://github.com/coder/vscode/pull/16

So I suspect this is an issue in the vscode that can be resolved.

**Comment by alexdima** [comment]
@mjbvz Steps to get up and running on `https`:
* launch the server e.g. from sources using `./scripts/code-server.sh`
* download caddy from https://caddyserver.com/v2
* on macOS, the downloaded blob must be made executable and opened first via right click open
* `./caddy_darwin_amd64 reverse-proxy --to localhost:8000`
* open `https://localhost/`

**Comment by DJlee139** [comment]
@mjbvz @alexdima I'm able to see the png files when I run on my machine's localhost. However, I'm having issues viewing them when I run on a docker container's localhost. I also need to host the docker container on an aws ec2 instance for my use case so I'm unsure if that's also a layer that would affect this.

In my trial and error I found that by enabled "Bypass for network" for service workers in my chrome's dev tool application settings that the files do show correctly so it makes me suspect that there's something with how those service workers are being used that isn't playing nice with how I'm attempting to use VS Code Server right now. I've tried various methods through either Caddy or Apache to no success at this point.

**Comment by mjbvz** [comment]
I also don't see this locally: 

![Screenshot 2023-05-01 at 2 09 18 PM](https://user-images.githubusercontent.com/12821956/235531915-f983fc75-1ef6-4071-928c-d96d703c07f0.png)


@DJlee139 Do other webview based features work, such the built-in markdown preview?

**Comment by DJlee139** [comment]
I'm unable to replicate it locally. I've only been able to see this when I run vs code server on localhost inside of a Docker container that is on an aws ec2 instance. Also other png files appear from the rest of the IDE. It's only those that are for theme that show.

Slightly unrelated, but for my case, is this something that I could replace the welcome page with? Ultimately, having this walkthrough appear isn't important for what I'm building, but having broken png's on my opening page when the IDE starts up is not ideal. I believe I've seen that I can build a vs code extension to have my own custom welcome page. Is that correct in assuming I could show my own walkthroughs instead. I wouldn't need this issue resolved if so.
