### ISSUE TITLE
Settings sync doesn't specify which extension needs workspace trust to be installed

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode#180867]
1. Have an extension that requires workspace trust to be installed/enabled synced to settings sync
2. Turn on settings sync from a new VS Code instance that doesn't have that extension installed/enabled already
3. :bug: get this modal dialog that doesn't specify which extension requires workspace trust to be installed/enabled (I do not know which extension causes this to repro because the dialog doesn't say)

![image](https://user-images.githubusercontent.com/30305945/234370902-b6df4822-4419-4191-87a6-09b3362fa98a.png)

**Comment by sbatten** [comment]
@sandy081 since the install is not triggered explicitly by the user, the dialog does not make sense. Do you need anything from the workspace trust side to avoid this dialog, or vice versa, do you provide something to let us know that this is from settings sync?

**Comment by sandy081** [comment]
@joyceerhl I assume this is happening on the web client, because in Desktop Settings Sync install extensions on the shared process.
