### ISSUE TITLE
The display problem of jupyter notebook running results

### ISSUE THREAD

**Issue by Zolliner** [microsoft/vscode#180956]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.77.3 (user setup)
- OS Version: Windows_NT x64 10.0.22621

Steps to Reproduce:

1. Run a jupyter notebook cell and wait for it to print a line or lines
2. Slide the jupyter notebook page to other units while no output is complete
3. After running the output completely, slide the page to view the result and find that the printing is incomplete

I demonstrated this process using a video:
https://user-images.githubusercontent.com/24618122/234637810-de16627e-555e-49a1-ba67-9d7284f24ea0.mp4

**Comment by rebornix** [comment]
@Zolliner thanks for the report, this issue should now be fixed in latest Insiders and be available in next Stable build (shipped next week)
