### ISSUE TITLE
Scroll to top/bottom in explorer

### ISSUE THREAD

**Issue by OliverJAsh** [Microsoft/vscode#18097]
- VSCode Version: 1.8.1
- OS Version: macOS Sierra 10.12.2

Steps to Reproduce:

1. Focus explorer
2. Press home/end to scroll to top/bottom, respectively

Expected: home/end should scroll to top/bottom, respectively
Actual: nothing happens

**Comment by bpasero** [comment]
hm, this should probably go to the tree level for any tree if it is standard behaviour.

/cc @joaomoreno
