### ISSUE TITLE
Support checksum matching when binding breakpoints

### ISSUE THREAD

**Issue by isadorasophia** [microsoft/vscode#180964]
VS Code currently doesn't seem to support checksum matching for an unsaved source file, see [isDirty()](https://github.com/microsoft/vscode/blob/d4237bd8d548a45e2759f3b3fe4fb75dfeb677a9/src/vs/workbench/services/textfile/common/textfiles.ts#L51).

Consider the following scenario:
1. User modifies the source;
2. User manually undoes the change;
3. User adds breakpoint.

On step 2, VS Code will show that the file is dirty through the UI (the dot appears in front of the file name), even though the contents are the same.

On step 3, the debugger successfully binds the breakpoint, but the UI still displays the breakpoint "grayed out".

This behavior lacks consistency and a checksum support in the file changes would address this.

**Remarks**
I noticed that Ctrl-Z seems to track correctly whether the file was modified or not. This still doesn't consider when the user manually modifies the source back into its original state.

**Comment by roblourens** [comment]
Besides this, the behavior of the sourceModified flag is inconsistent, see https://github.com/microsoft/vscode/issues/175872. I also have https://github.com/microsoft/vscode/issues/85290 related to the checksums in DAP. Closing this in favor of those issues
