### ISSUE TITLE
Extension 'Docker' is configured as formatter but it cannot format 'Dockerfile'-files

### ISSUE THREAD

**Issue by onionyst** [microsoft/vscode#180904]
Does this issue occur when all extensions are disabled?: Yes.

- VS Code Version: 1.78.0-insider (2902f278)
- OS Version: macOS Ventura 13.3.1

Steps to Reproduce:

1. Create a `Dockerfile`, select language model as `Dockerfile (dockerfile)`. 
2. Format the file, and it alerts the message box with `Extension 'Docker' is configured as formatter but it cannot format 'Dockerfile'-files`. 

This may be related to this [issue](https://github.com/microsoft/vscode-docker/issues/3899). It is not reproduced on VSCode 1.77, but on 1.78 insiders.

**Comment by jrieken** [comment]
Please check if this setting is configured anywhere: `editor.defaultFormatter`

**Comment by onionyst** [comment]
> Please check if this setting is configured anywhere: `editor.defaultFormatter`

I have the following configuration in global `settings.json`. 

```jsonc
{
  "[dockerfile]": {
    "editor.defaultFormatter": "ms-azuretools.vscode-docker"
  },
}
```

There should be no side effects of this?

**Comment by jrieken** [comment]
It's the cause of that. The `ms-azuretools.vscode-docker` extension needs to advertise that it supports formatting these files, it's not enough to just configure this. Two parts come together: the extension saying which files it can formatter, the user setting a preferences (which is only really needed when having multiple applicable formatters)

What happens is that you have the configuration but that the extension isn't supporting to format these files. 

Is there anything special about this file? Is it untitled and not yet saved? Does it come from a remote like WSL, containers etc?

**Comment by onionyst** [comment]
That's amazing! I removed the `"[dockerfile]"` configuration and it worked again. 

The file is a `Dockerfile` already saved on MBP local disk, with minimal reproducing example as follows, when the configuration is set:

```Dockerfile
FROM ubuntu:latest
```

<img width="652" alt="image" src="https://user-images.githubusercontent.com/14269397/234508057-2f1c8973-f583-4a34-8abe-d09fac02dfb1.png">

That's a bit strange, though. Other languages (e.g., `"[c]"`, `"[json]"`, or `"[shellscript]"`) are working normally with the default formatter configuration, regardless of how many valid formatters are installed. If I understand correctly, `ms-azuretools.vscode-docker` surely supports the `Dockerfile` format, as it works properly when the configuration is not set. 

Thanks again for the advice.

**Comment by jrieken** [comment]
This is indeed caused by the docker extension but it only reproduce like so

* open docker file
* open explorer, not show the docker sidebar
* reload window
* 🐛 there is no docker formatter

The reason is that the docker extension isn't activated which is because the docker extension doesn't activate on the docker-language, only on dockercompose

<img width="621" alt="Screenshot 2023-05-03 at 18 00 14" src="https://user-images.githubusercontent.com/1794099/235972442-102453e0-5bd7-47d9-956d-186fbf269d8f.png">
