### ISSUE TITLE
Markdown Render VSCode Command URI with arguments

### ISSUE THREAD

**Issue by sdankel** [microsoft/vscode#180913]
I've been trying to implement a `hover` feature with go-to definition links, like this. 

<img width="502" alt="image" src="https://user-images.githubusercontent.com/47993817/234487808-ab29765d-4eac-404d-a9cc-5408e0d16621.png">

I found https://github.com/microsoft/vscode/issues/140733 which states that vscode commands can be embedded in markdown (and in hover requests), and this is working. However, I can't figure out how to pass arguments to the command. Is this possible? If not, I'd very much appreciate support for this.

Unfortunately the LSP doesn't support commands in hover requests, as that would be my preferred method. However, I can certainly make it work by passing arguments along with the command in the markdown. Thank you!

cc @mjbvz

**Comment by mjbvz** [comment]
See https://code.visualstudio.com/api/extension-guides/command#command-uris

Command arguments can be passed as a JSON array encoded on the uri
