### ISSUE TITLE
Keep getting the error: "The workbench failed to connect to the server (Error: )"

### ISSUE THREAD

**Issue by tamirpoindexter** [microsoft/vscode#180905]
Hello. I am operating the Visual Studio Code for CS50 IDE on a chromebook in the web browser and I keep getting an error that reads, "The workbench failed to connect to the server (Error: )". I am inexperienced with visual studio code, github and Chrome OS and was using CS50 to learn more. I cannot access any of the files that I was working with, nor can I make or edit new ones. Please help.

Version: 1.77.3
Commit: 704ed70d4fd1c6bd6342c436f1ede30d1cff4710
User Agent: Mozilla/5.0 (X11; CrOS x86_64 14541.0.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36
Embedder: codespaces

**Comment by lszomoru** [comment]
@tamirpoindexter, it seems to be that this is specific to the environment that has been set up for the CS50 class. I would suggest that you reach out to the people that are managing that environment. In case they confirm that this is indeed a problem with VS Code please feel free to reopen the issue. Thanks!
