### ISSUE TITLE
Visual Studio Code wants write access to `/home/-mateusz` - but my home directory is `/home/mateusz`

### ISSUE THREAD

**Issue by matkoniecz** [microsoft/vscode#180940]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:  `code --version` gives  ```
- 1.77.3
704ed70d4fd1c6bd6342c436f1ede30d1cff4710
x64
```

- OS Version:  `lsb_release -a` gives ```
- No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.6 LTS
Release:        20.04
Codename:       focal
```

I am running Lubuntu.

Steps to Reproduce:

1. ???
2. `code --disable-extensions`

![screen](https://user-images.githubusercontent.com/899988/234592381-6fe11d8a-0d01-46a1-a00d-cbd913f54985.png)

Note that nothing is shown in stdout and and stderr (maybe `-` is from misbehaving word splitting because error message gets mangled at some stage? But I checked stderr and stdout to confirm that and nothing is there)

-----------------------

I originally wanted to report that pasting space-prefixed string into multiline Ruby string removes spaces. For example copying

`                  foobar`

into `bb` in

```
string = 'aa
bb
cc
'
```

causes `foobar` to be pasted.

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by matkoniecz** [comment]
> Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

It does not happen with it, "pasting space-prefixed string into multiline Ruby string removes spaces" still  happens and I will open a new issue for it.

**Comment by bpasero** [comment]
I think we fixed this issue, I recall an issue around Snap.
