### ISSUE TITLE
git bash freezes upon opening on windows 

### ISSUE THREAD

**Issue by saranatour1** [microsoft/vscode#180929]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.77.3
- OS Version: Windows 11

I'm Having an issue with gitbash, it freezes upon opening, I have searched for solutions but I did not find anything matching my issue.
here is a screen for reference: 
![gitbash issue](https://user-images.githubusercontent.com/77834808/234554930-aa6cabae-24f6-4f5a-a348-e79f3953ac67.png)

Please let me know if there is a possible solution 😸

**Comment by lszomoru** [comment]
@saranatour1, does the same happens when you update gitbash outside of VS Code?

**Comment by saranatour1** [comment]
I did update it, and I get the same issue, it freezes, I tried killing the port but it didn't work.. and it looks like it is not a vsc issue?  
![image](https://user-images.githubusercontent.com/77834808/234886459-5559b537-3263-4984-a368-02c75aad9882.png)

**Comment by saranatour1** [comment]
It's working again.

**Comment by saranatour1** [comment]
The issue seemed to get resolved  after I updated the packages.
