### ISSUE TITLE
Investigate int Welcome experience

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#18091]
Ideas for exploration:
- [ ] Overlay pointing out the main parts of the workbench
- [ ] Welcome editor with "Getting Started" actions
- [ ] Welcome editor with short introduction and interactive samples

**Comment by daviwil** [comment]
I would also like to suggest that there should be a way to disable the welcome experience for a fresh install before first launch.

I'm helping a team who wants to use VS Code to debug code on machines that get re-built from machine images daily and made a PowerShell script for them that automates the process of installing VS Code.  One of their complaints is that the first launch always launches the browser with the VS Code homepage.

@joaomoreno  gave me a workaround for that, but it'd be nice to have a command line flag like `-skip-welcome` which would allow the caller to skip the first welcome and make it not appear in subsequent launches, especially if the welcome experience becomes more elaborate.

All that said, I think having a more interactive welcome experience is a great idea!

**Comment by chrmarti** [comment]
@daviwil What is the workaround you use to avoid the webpage opening?

**Comment by egamma** [comment]
Closing the plan item, no more work is planned on this for January.
