### ISSUE TITLE
"Trigger inline suggest" doesn't work when 'editor.inlineSuggest.enabled' is false

### ISSUE THREAD

**Issue by ulugbekna** [microsoft/vscode#180933]
Basically, what the heading says. 

https://user-images.githubusercontent.com/16353531/234569140-e0cb5c51-3939-4b77-84f4-9043666610de.mov

# version info

```
Version: 1.78.0-insider (Universal)
Commit: 2c51b3de329d48f45eabe80316f099f46fd3a5cc
Date: 2023-04-26T05:23:57.381Z
Electron: 22.4.8
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Darwin arm64 22.4.0
Sandboxed: Yes
```

**Comment by matkoniecz** [comment]
Why "Trigger inline suggest" should work with inlineSuggest.enabled set to false?

**Comment by hediet** [comment]
Should work now.

**Comment by ulugbekna** [comment]
It's triggered, but now disabling "inlineSuggest.enabled" is again not respected, sorry 

https://user-images.githubusercontent.com/16353531/234812385-d0a9b58d-c4cb-4988-928c-3296944c5a02.mov
