### ISSUE TITLE
"Maximum call stack size exceeded" when closing settings

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#18090]
Steps to Reproduce:

1. Open user settings
2. Close them

![image](https://cloud.githubusercontent.com/assets/22350/21636370/cf26106e-d262-11e6-9e1d-d84e0ef6d5c9.png)

**Comment by joaomoreno** [comment]
cc @jrieken @bpasero

**Comment by bpasero** [comment]
My guess would be https://github.com/Microsoft/vscode/commit/94e477d0b3ba3ec151e3198b70c762980f5381f3

**Comment by isidorn** [comment]
Dup of https://github.com/Microsoft/vscode/issues/18055
