### ISSUE TITLE
Selected wordHighlight looks the same as unselected

### ISSUE THREAD

**Issue by sapegin** [Microsoft/vscode#18092]
- VSCode Version:  1.8.1
- OS Version: macOS 10.11.6

Steps to Reproduce:

In my theme I have: 

```xml
<key>selection</key>
<string>#ff0</string>
<key>selectionHighlight</key>
<string>#0f0</string>
<key>wordHighlight</key>
<string>#f00</string>
<key>wordHighlightStrong</key>
<string>#00f</string>
```

Test code:

```js
function test(source) {
	let parsedProps;
	try {
		parsedProps = propsParser(source);
	}
	catch (exception) {
		parsedProps = [];
	}
	return parsedProps;
}
```

1. Put cursor inside one of the `parsedProps` (looks fine so far):

![image 2017-01-04 at 11 13 53 am](https://cloud.githubusercontent.com/assets/70067/21639161/e4818ad6-d26e-11e6-9596-bfcf7c4e285c.png)

2. Select part of `parsedProps` (selected part has the same style as non-selected):

![image 2017-01-04 at 11 14 50 am](https://cloud.githubusercontent.com/assets/70067/21639188/088657cc-d26f-11e6-9b0d-c6717167594c.png)

**Comment by alexandrudima** [comment]
@sapegin The trick is to use 8 hex chars. The last two represent the alpha.

e.g.:

```
<key>wordHighlight</key>
<string>#ff000044</string>
<key>wordHighlightStrong</key>
<string>#0000ff44</string>
```
