### ISSUE TITLE
column count starts at 2 for search results for screen reader

### ISSUE THREAD

**Issue by amunger** [microsoft/vscode#180982]
1. put some text in an editor
2. ctrl+shift+f and search for that text
🐛  screen reader will report that the result is on a column that is actual+2 

![image](https://user-images.githubusercontent.com/2019016/234709157-736c7b78-ead6-47c3-b37f-c5f66313c897.png)

**Comment by meganrogge** [comment]
pretty sure this is by design, but @andreamah can answer that

**Comment by andreamah** [comment]
Thinking about it, it seems to not make much sense to start at 2 (although I see this behavior in areas outside of notebooks). @meganrogge do you see why this should be design? If not, I can go ahead and try to make the columns start at 1 like it does in the editor.

**Comment by meganrogge** [comment]
Yeah @andreamah that sounds good to me 👍🏼 thanks
