### ISSUE TITLE
Build failed: ipynb tests

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#180987]
Build: https://dev.azure.com/monacotools/a6d41577-0fa3-498e-af22-257312ff0545/_build/results?buildId=212629
Changes: https://github.com/Microsoft/vscode/compare/b816a3f...50cc7df

**Comment by roblourens** [comment]
I think this is likely the tests being slow for some reason before the ipynb then happening to time out in the ipynb section, not something from the ipynb tests. Can revisit if it would come up again. Could also be related to the known crashing issues with integration tests in CI.
