### ISSUE TITLE
Use the correct names in the keyboard shortcut menu!

### ISSUE THREAD

**Issue by csss1234** [microsoft/vscode#180943]
I am a brand new user, this is day one. I wanted to change the keyboard shortcuts for the commands I would use most: for the **Command Palette** and for **Search Files by Name**

Those are the names that the program uses for these commands. But when I go into keyboard shortcuts and type in
-  "Command Palette" I see nothing
- Type in "Search files", see nothing

In keyboard shortcuts they are called "Show All Commands" and "Go to file"

**Comment by ulugbekna** [comment]
Hey @csss1234 ,

Thanks for filing the issue. 

Where have you learned about the naming "Search Files By Name"?

--

If you have trouble with finding commands by name, you can search by an already existing keyboard shortcut.

Press "record keys" and it will record your keypresses.

![Image](https://user-images.githubusercontent.com/16353531/234810918-9fdf6af0-6488-4a2f-a683-eca101713f34.png)

That's what I personally do if I don't know the exact command name

**Comment by csss1234** [comment]
When you chose "Go To File..." then it is the text prefilled in the search bar 
![image](https://user-images.githubusercontent.com/45954264/234910889-9d84aaa2-8220-49ce-95b7-592065e51b4e.png)

**Comment by ulugbekna** [comment]
Thank you for your input.

I understand the concern, but these names have existed for a while and it's too late to change them, I'm afraid.
