### ISSUE TITLE
External issue reporter doesn't show up after switching away from and back to an extension

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode#180997]
Testing #180757

1. Select an extension that implements the api 
2. Select an extension which doesn't
3. Select the same extension from step 1
4. :bug: still shows the section for the extension from step 2

**Comment by TylerLeonhardt** [comment]
Is this what you mean? If so, I can't seem to repro it:
![Recording 2023-04-27 at 09 18 51](https://user-images.githubusercontent.com/2644648/234926706-007ddc5a-ad89-4f03-8261-21d16da4613e.gif)

(not pictured is the macOS native drop down where I am switching between extensions. "sandbox" implements the API)

Do you see anything in dev tools?

**Comment by joyceerhl** [comment]
Hmmm, can't repro this anymore, I swear I saw it yesterday though... closing for now, will reopen if I find it again.
