### ISSUE TITLE
Should the `handleIssueUrlRequest` be more powerful?

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#180923]
Testing #180757

I wonder if allowing an extension to return a URI is powerful enough? Why not let the extension decide how to file the issue? 

For example, if an extension has a way to report issues via API and not via browser, it would be hard to adopt it here. I think an extension should deal with issue reporting in the best way it can and then open a browser tab if needed.

**Comment by TylerLeonhardt** [comment]
Yeah it's a good idea but a tough balance between allowing the extension to do whatever it wants and providing a nice way that extensions don't have to re-invent the wheel.

**Comment by justschen** [comment]
closing, and tracking new API updates here: https://github.com/microsoft/vscode/issues/196863
