### ISSUE TITLE
Whole UI offsets after some time

### ISSUE THREAD

**Issue by schockocraft** [microsoft/vscode#180912]
After having VSC run for a few days the UI breaks down for a moment while the app is not focused and then completely offsets itself to the top-left.

![image](https://user-images.githubusercontent.com/44204747/234484687-78af4c53-1348-44ac-a4e2-89499372c804.png)
this is a screencap of the whole window

All Interactive elements still react to mouse-over on their original position, not on their offset visual position

This happened at least 5 times to me now over multiple versions, but as it takes considerable time until it starts to happen i can not test if the most recent version/insiders build has this issue still, or if any of my extensions is responsible, but i have no extension that changes the UI as far as i know.

Of course it might just be an issue with Windows reallocating RAM to whatever program is focused atm, but other programs (including other apps running on electron, like Discord) don't have any issue like this when running in background.

Does this issue occur when all extensions are disabled?: Maybe (see above)

- VS Code Version: 1.76.2 (user setup)
- OS Version: Windows 10 Pro 21H2 (Build 19044.2364)"

Steps to Reproduce:

1. Open VS Code
2. Use it normally over the next 3-5 days, hibernating the pc every night
3. unfocus VSC (but keep it visible on second window) for around half an hour

**Comment by schockocraft** [comment]
Just tried to reload the window with the "Developer: Reload Window" command, and the issue persists

**Comment by deepak1556** [comment]
Can you test if the issue happens with our latest insiders https://code.visualstudio.com/insiders ?
