### ISSUE TITLE
API `handleIssueUrlRequest` should pass in the content that was provided

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#180922]
Testing #180757

I would have expected the API to pass in the summary and description and probably also the environment such as OS, version so that I can build a meaningful URL to report the issue.

**Comment by TylerLeonhardt** [comment]
Couple questions:

> summary & description

* What summary & description? We hide the Title and Steps to Repro boxes when an extension uses the API. All you see is a big blue button

> also the environment such as OS, version

* the handler has access to `vscode.env`... is that not sufficient?

**Comment by bpasero** [comment]
Since I never saw this flow working when testing, I was not sure. 

We have a lot of info we attach, not sure extensions can get this or would need it:

<img width="327" alt="image" src="https://user-images.githubusercontent.com/900690/234769825-7ca9b59a-39ef-476b-9f00-a6419fef16d8.png">

**Comment by TylerLeonhardt** [comment]
Yeah extensions today can't get that data so perhaps we should pass it down to extensions... maybe as strings so we don't need a concrete contract with extensions.

**Comment by justschen** [comment]
closing, since the API was updated to support sending additional data as well (still proposed API)
