### ISSUE TITLE
Feature request: keep the selection in test explorer after running multiple tests

### ISSUE THREAD

**Issue by rzhao271** [microsoft/vscode#180950]
Testing microsoft/vscode-python#21091

1. Select some tests in the test explorer.
2. Press the play button on one of the tests to run the selected tests.

Expected result: The tests stay selected.
Actual result: Only one of the tests is selected after.

**Comment by connor4312** [comment]
You ca choose alternate sorting methods here. Ordering by location sounds like what you want:

<img width="259" alt="image" src="https://user-images.githubusercontent.com/2230985/234635449-106c55cc-b8e7-4c3c-8c11-3ba69a430f47.png">

**Comment by eleanorjboyd** [comment]
I think what @Raymo111 is talking about is this behavior but please correct me if I'm wrong, thanks!

https://user-images.githubusercontent.com/26030610/234636737-0b96900b-ff06-444e-a1d1-1ebc08cc8303.mov

**Comment by connor4312** [comment]
Oh, sorry, misread. I think it's sensible that if multiple elements are selected, we don't touch it

**Comment by Raymo111** [comment]
> I think what @Raymo111 is talking about is this behavior but please correct me if I'm wrong, thanks!
> 
> https://user-images.githubusercontent.com/26030610/234636737-0b96900b-ff06-444e-a1d1-1ebc08cc8303.mov
> 
> 

Wrong @.
