### ISSUE TITLE
Investigate and Improve Key bindings customisations experience

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode#18095]
Investigate and improve key bindings customisations experience. 

Following are the proposals, use cases, challenges in this area

### Keybindings view
A table based view, each row for each key binding

Key | Command | When | Action
------------ | ------------- | ------------- | -------
alt+cmd+[ | editor.fold | editorTextFocus | Unbind
alt+cmd+] | editor.unfoldRecursively | editorTextFocus | Unbind
Bind | workbench.action.reloadWindow |  | Bind

#### Show the correct Keybindings based on the keyboard layout (both defaults and user)

Currently, keybindings show the keys those were shown in the US Keyboard. Since the keys location changes with Keyboard layout, some of the Keybindings shown as is in the file do not work. For eg: 
<kbd>ctrl</kbd>+<kbd>`</kbd> does not work on German layout key board. Instead the associated Keybinding for this is <kbd>ctrl</kbd>+<kbd><</kbd>

#### Show the invalid Keybindings
Some key bindings might not makes sense in some keyboard layouts since . Show such keybindings as unbound entries, probably with message?

#### Grouping

Group key bindings by VS code core and each extension key bindings

#### Command id vs title

Show just title or just id or both for the command column? Not all commands have labels and not all command ids are straight to interpret what action they perform. Not all command ids maps well with labels.

#### When context

`when`  is a combination of the location in VS Code where key binding is applied to and the pre-condition to be met to trigger the action. Not all commands have proper separation of location and precondition. Also some commands have multiple locations. How to render this when clause? How to let user edit this?

#### Command args

`args` How to display args

#### Bound and unbound commands 

Display bound and unbound commands as two different groups

### As a user, I would like to associate a Keybinding to a command/action

User should be able to find an action say in `Keybindings editor` or `Command Pallette` and associate a key binding to it. Use the widget `Define Keybinding` to record the Key bindings instead of writing it by hand. 

An action next to command pallette list entry to bind/unbind the key binding?

### As a user, I would like to find the command/action for a Keybinding.

User should be able to find the Keybinding in `Keybindings editor` and see the associated commands/actions to it.

**Comment by sgtoj** [comment]
@sandy081 Insider build has been my daily driver since its inception; as well as Windows Insiders. 

Anyways, I checked it out the keybinding editor view in today's build. It looks great!

**Comment by sgtoj** [comment]
@sandy081 If I can make two suggestions...

1. Show user overrides at the top.
  - Maybe even separate them with a small gap and heading.
2. Provide a way to easily identify if a default keybinding has been replaced.

**Comment by sandy081** [comment]
@sgtoj Thanks for the feedback. 

The design of this editor is to be simple and show the available Keybindings in the system. Source column was added to help user to show where a particular keybinding is coming from. 

To separate User and Default keybindings was one of the initial designs. But as a first cut and with some initial feedback, above simple design was chosen. 

I will gather all the feedback and update/improve the design.

Yes, terminal view covering the keybindings is a bug and I will fix it today and you can get it in tomorrows insiders. 

Thanks

**Comment by schmuli** [comment]
@sandy081 further to @sgtoj's comment, I've noticed that even when there is no lower panel open, the bottom of the editor is below the bottom of the screen.

**Comment by Tekbr** [comment]
-- Sorry for the English, I used Google Translator --

@sandy081 The new Keybindings screen would be possible or feasible, allow search not only for the column 'command', but also for the column 'Keybinding' and 'When'?

Why this? VSCode is not yet in my language, and searching for the shortcut key may be faster in this case.

I know we still have the old screen.

**Comment by sandy081** [comment]
@Tekbr Searching for keybindings is possible. Typing `control+w` would look for such keybindings. Let me know if it is not working for you. Thanks.

**Comment by Tekbr** [comment]
@sandy081 Oh, I was typing `ctrl` instead of `control`. That was my mistake. Why not type `Ctrl + anything `or instead of `Control + anything`?

**Comment by sandy081** [comment]
I will be improving Search to accept both full or short forms

**Comment by Tekbr** [comment]
OK. Thanks for the quick response.

**Comment by pixieaka** [comment]
The interface frozen here https://github.com/Microsoft/vscode/issues/23039

**Comment by Tekbr** [comment]
@sandy081 

-- Sorry for the English, I used Google Translator --

I do not know if it's in a commit that was not made available in Insiders.

But in 1.11.0 - Insiders d98a518 2017-03-29T06: 11: 14.271Z, I can not use <kbd>Ctrl</kbd> instead of using <kbd>Control</kbd>. Can you check it please?


And not forgetting, thanks for allowing you to search the 'When' column. 😄 👍

**Comment by sandy081** [comment]
@Tekbr This is not yet supported. Please follow the issue #23368.
