### ISSUE TITLE
Wrong multiline parenthesis indent (JS)

### ISSUE THREAD

**Issue by alexanderby** [Microsoft/vscode#181]
When formatting JavaScript the indent of right parenthesis (that is placed on different line) is too large.
This is expected to be
```javascript
function (
    arg1,
    arg2
) {
    if (
        arg1
        && arg2
    ) {
        //...
    }
}
```
but actually is
```javascript
function (
    arg1,
    arg2
    ) {
    if (
        arg1
        && arg2
        ) {
        //...
    }
}
```

**Comment by jrieken** [comment]
This issue was moved to Microsoft/TypeScript#5771

**Comment by alexanderby** [comment]
So, in version 0.10.6 (which uses TS1.7 language service) I can still reproduce this issue when editing JavaScript (not TypeScript). Please, re-open.
