### ISSUE TITLE
Walkthrough current stage becomes collapsed and clicking it doesn't expand it after switching to another document and back

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode#181069]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: Version: 1.78.0-insider (user setup)
Commit: d6290ef6582acecbf3bca1558111f2ee64375801
Date: 2023-04-27T05:20:48.295Z
Electron: 22.4.8
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Windows_NT x64 10.0.22621
Sandboxed: Yes
or
Version: 1.77.3 (user setup)
Commit: 704ed70d4fd1c6bd6342c436f1ede30d1cff4710
Date: 2023-04-12T09:16:02.548Z
Electron: 19.1.11
Chromium: 102.0.5005.196
Node.js: 16.14.2
V8: 10.2.154.26-electron.0
OS: Windows_NT x64 10.0.22621
Sandboxed: Yes
- OS Version: Windows, probably Linux/Mac too

Steps to Reproduce:

1. Open some walkthrough, such as Getting Started With VS Code
2. Select some stage.
3. Switch documents and back to the walkthrough.

Actual: The currently active stage becomes collapsed and clicking on it doesn't expand it. The workaround is to first click some other stage and then click the stage that wasn't clickable previously.

Expected: Ideally, the current stage would remain expanded, but maybe you have a "by design" reason to collapse it, in which case it should at least be expandable when clicked.

![image](https://user-images.githubusercontent.com/19859882/234990323-08ee9c80-b163-4f74-aae7-b943a7c865a6.png)

**Comment by bhavyaus** [comment]
Fixed by https://github.com/microsoft/vscode/pull/182947
