### ISSUE TITLE
Build failed:  `Files - NativeTextFileService i/o readStream - large UTF16 BE`

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#181070]
Build: https://dev.azure.com/monacotools/a6d41577-0fa3-498e-af22-257312ff0545/_build/results?buildId=212759
Changes: https://github.com/Microsoft/vscode/compare/2d28a86...016a3fd

**Comment by bpasero** [comment]
Seems like a CI flake, very stable since 2 weeks:

![image](https://github.com/microsoft/vscode/assets/900690/a23c90fa-2d38-44a3-bd6e-3eb610a2580f)
