### ISSUE TITLE
[Feature request] Test explorer show failing tests number in the Activity Bar Badge

### ISSUE THREAD

**Issue by mustafaabobakr** [microsoft/vscode#181094]
<h1 align="center">Option to show failing tests number in  vscode Activity Bar Badge </h1>

An extension example here is [TODO Tree](https://marketplace.visualstudio.com/items?itemName=Gruntfuggly.todo-tree)

<br >
<br >
<p align="center">Naming suggestion</p>

1- Enabling option
```json
 "testExplorer.showActivityBarBadge": true,
```
2- Badge number of `failed tests`
```json
"testExplorer.activityBarBadge": "failed"
```
3- Badge number of `total tests`
```json
"testExplorer.activityBarBadge": "total" 
```

<img width="900" alt="Test explorer show failing tests number in the Activity Bar Badge" src="https://user-images.githubusercontent.com/27288406/235074375-95a277d1-dcef-4b74-8dce-682c1718e53e.png">

**Comment by jhunt-scottlogic** [comment]
Hi, I interested in picking up this issue if it isn't already in progress.  Having poked around the Todo Tree extension it seems to be similar to the implementation required for this. I just wanted to confirm a couple of things before getting started.

1. What would the intended behaviour/text of the badge be if the tests are currently being run?

2. Is the naming convention for the settings suggested above suitable?

> 1- Enabling option
> ```"testExplorer.showActivityBarBadge": true,```
> 2- Badge number of failed tests
> ```"testExplorer.activityBarBadge": "failed"```
> 3- Badge number of total tests
> ```"testExplorer.activityBarBadge": "total" ```

3. Should it be able to show the number of passed tests as well as total/failed?


Thanks,
Josh

**Comment by meganrogge** [comment]
@connor4312 should this be on the May milestone?
