### ISSUE TITLE
Cursor out of position with RTL UTF8 text

### ISSUE THREAD

**Issue by leegee** [Microsoft/vscode#18104]
- VSCode Version: Code - Insiders 1.9.0-insider (c6a320c4f9c53b809a9615324a5b563eeb217984, 2017-01-04T09:10:08.396Z)
- OS Version: Darwin x64 15.3.0
- Extensions:

|Extension|Author|Version|
|---|---|---|
|Bookmarks|alefragnani|0.10.1|
|vscode-eslint|dbaeumer|1.2.2|
|vscode-instant-markdown|dbankier|0.2.1|
|docthis|joelday|0.3.6|
|vscode-exec-node|miramac|0.2.1|
|joinlines|webdokkeren|1.1.1|

---

Steps to Reproduce:

1. Enter some RTL UTF text in the middle of a markdown document:
```
    Heading
    --------- 
    A paragraph.
    
        {
            "facebook": {
                "username" : "יִצְחָק עוזיאל",
                "password" : "בוקר טוב"
            }
        }
    And so on.
```
2. Try navigating and editing.

**Comment by mjbvz** [comment]
Thanks for the report.

This is not markdown specific. It repos for plain text files as well. I'm going to update the issue title to reflect this

**Comment by alexandrudima** [comment]
@leegee Could you please explain what exactly is wrong:

Here I press repeatedly arrow right:
![rtl](https://cloud.githubusercontent.com/assets/5047891/22175261/dfe2ad1c-dff1-11e6-9be6-b3f0f6d11da8.gif)

**Comment by alexandrudima** [comment]
Closing until further information is provided.

**Comment by leegee** [comment]
Seems okay now, thanks.
