### ISSUE TITLE
Bump js-debug to 1.78

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#181047]
A [pipeline issue](https://github.com/microsoft/vscode-engineering/pull/280) prevented publishing js-debug at the normal time, but we should take the update in order to have fixes and tests for the release.

**Comment by connor4312** [comment]
Issues not on nightly as a result of the same issue https://github.com/microsoft/vscode-js-debug/compare/1fc48e57096379620125f6231e4c32c39dc51723...v1.78.0

**Comment by roblourens** [comment]
Thanks, LGTM
