### ISSUE TITLE
Regex find/replace: Cannot prefix newline

### ISSUE THREAD

**Issue by Jakst** [Microsoft/vscode#18107]
- VSCode Version: 1.8.1
- OS Version: Windows 7

Steps to Reproduce:

1. Open any file that is not empty and has multiple lines
2. Open the find-module
3. Enable regex-matching
4. Enter the last character from any line in your file, followed by \n. For example `a\n`.
5. Observe that no lines were found.

However, `.?\n` and `.*\n` works, but only highlights the newline character.

I have identified this error on my Windows 7 machine, but it does not reproduce on my Mac.

**Comment by mjbvz** [comment]
Since this works on your mac but not on windows, I suspect you may be using different line endings on the different machine. If the document has CRLF line endings, as is common on windows, you would have to use the regular expression: `a\r\n` instead of `a\n`. Depending on your needs, you could also just use `a$` to match the end of the line. That should work for both LF and CRLF

Give that a try and let me know if that fixes the issue. If not, please provide a more complete example so that we can investigate.

Thanks

**Comment by Jakst** [comment]
Yeah `\r\n` or switching to LF line endings worked. `a$` wouldn't solve the problem as I was really searching for strings across line endings.

The followup question is then, should VS Code differentiate between the different line endings? It might be semantically correct, but I would argue it is bad UX, as the user usually doesn't pay attention to the type of line ending in the file. Maybe it could be and opt-in setting to separate the two line-endings.

For example, in Sublime Text 3 all types of line endings are matched by \n.

**Comment by mjbvz** [comment]
We've generally played it conservative for this type of behavior. I think that what we do currently is correct and we would want to keep this more explicit behavior as an option at least. If you want to handle any type of newline, just use `\r?\n`

@alexandrudima @rebornix Any further thoughts on this?

**Comment by alexandrudima** [comment]
IMHO we cannot transform `\n` to `\r?\n` safely w.r.t. semantics in the search string (a regular expression) without writing a regular expression parser or moving off the built-in JS regex.

Some tricky rewrite examples I could come up with:
* `\n+` => `(\r\n)+` => notice how we need to introduce a new group
* `\r[\n]` => `\r[\n]` => notice how in this case `\n` should not be transformed to `\r\n`.
* `asd\u000A` => `asd\r\u000A` => notice how there are multiple representations for `\n`.

I recommend doing no transformation to the input string, it has the risk of introducing some very unexpected bugs.
