### ISSUE TITLE
Setup walkthrough does not open by default on first launch

### ISSUE THREAD

**Issue by bhavyaus** [microsoft/vscode#181063]
This scenario is flaky due to a timing issue between walkthroughs being registered and check for first open. I can repro this occasionally.

**Comment by meganrogge** [comment]
@bhavyaus I think this should be on the May milestone?

**Comment by bhavyaus** [comment]
Verification Steps:

1. Launch VS Code with a clean profile
`code-insiders  --user-data-dir=$TMPDIR/cleanvsi/dir1 --extensions-dir=$TMPDIR/cleanvsi/ext-dir1`
2. Verify that the Setup walkthrough launches on startup.
<img width="766" alt="image" src="https://github.com/microsoft/vscode/assets/25044782/0731185f-5e11-430e-8ae3-6081f5cff861">

**Comment by DonJayamanne** [comment]
Didn't work for me
* Mac OS

![Screenshot 2023-06-01 at 11 54 28](https://github.com/microsoft/vscode/assets/1948812/0c79d6ed-af08-4673-b24a-746ab69f2045)
