### ISSUE TITLE
Closing a native tab crashes app

### ISSUE THREAD

**Issue by sberlan-odeko** [microsoft/vscode#181034]
Type: <b>Bug</b>

This seems to be a relatively new behavior since last update, and I don't recall changing anything-- but since I switch repos a lot and dislike multiple rows of tabs, I use Open Editors mostly to control files being open/closed, and use the native tabs feature for macOS because it's fantastic being able to navigate between repos this way. I am however cursed to never having anything software work correctly, so it's entirely possible it's just a me-problem.

Anyway, looks like something is causing the whole app to crash when closing workspace tabs.

1. Restore a session that has multiple code windows
2. Window -> Merge All Windows
3. Click the tab close button on an inactive repo
4. Code disappears, have to restart it.

VS Code version: Code 1.77.3 (704ed70d4fd1c6bd6342c436f1ede30d1cff4710, 2023-04-12T09:41:48.638Z)
OS version: Darwin arm64 22.4.0
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|28, 10, 6|
|Memory (System)|16.00GB (0.22GB free)|
|Process Argv|--crash-reporter-id 6d46dbb8-1b62-49b7-bb62-3010c7244e06|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (22)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|2.4.0
prettier-vscode|esb|9.12.0
remotehub|Git|0.54.0
vscode-graphql|Gra|0.8.7
vscode-graphql-execution|Gra|0.1.8
vscode-graphql-syntax|Gra|1.1.0
playwright|ms-|1.0.10
remote-ssh|ms-|0.100.0
remote-ssh-edit|ms-|0.84.0
azure-repos|ms-|0.30.0
remote-explorer|ms-|0.4.0
remote-repositories|ms-|0.32.0
remote-server|ms-|1.1.0
vsliveshare|ms-|1.0.5864
sqltools|mtx|0.27.1
sqltools-driver-pg|mtx|0.5.1
ruby|reb|0.28.1
svg-preview|Sim|2.8.3
sass-indented|syl|1.8.26
errorlens|use|3.10.1
volar|Vue|1.6.0
vscode-ruby|win|0.28.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscoreces:30445986
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
nodejswelcome1cf:30587006
3biah626:30602489
pyind779:30671433
89544117:30613380
pythonsymbol12:30671437
vsctsb:30705553
azdwalk:30721579
pythonms35:30701012
pythonfmttextcf:30716743
pythonclientmv:30725892

```

</details>

**Comment by bpasero** [comment]
Probable https://github.com/microsoft/vscode/issues/167936
