### ISSUE TITLE
NPM script runs with yarn instead of npm.

### ISSUE THREAD

**Issue by wonsang-choishin** [microsoft/vscode#181006]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:  Version: 1.77.3 (Universal)
- OS Version: macOS Monterey version 12.6.5

Steps to Reproduce:

Running NPM script from sidebar or running a task build uses yarn instead of npm, when project is opened from sub folders.

VSCode error:
*  Executing task: yarn run build:watch 

zsh:1: command not found: yarn

 *  The terminal process "/bin/zsh '-c', 'yarn run build:watch'" failed to launch (exit code: 127). 
 *  Terminal will be reused by tasks, press any key to close it.

This is my folder structure.

Root ==> If this is opened, uses npm.
  - node_modules
  - packages ==> If this is opened, uses yarn.
    - package1 ==> If this is opened, uses yarn.
    - package2 ==> If this is opened, uses yarn.
    - package3 ==> If this is opened, uses yarn.

1.  If I open the root folder then NPM script runs with npm command. ==> OK
2. If I open packages folder or one of individual package folder then NPM script runs with yarn command. ==> FAIL

**Comment by meganrogge** [comment]
You can set this with `npm.packageManager`
