### ISSUE TITLE
Explorer is not showing in activity bar

### ISSUE THREAD

**Issue by Venugopal0161** [microsoft/vscode#181093]
Type: <b>Bug</b>

Explorer menu is not showing in activity bar in vs code side menu

VS Code version: Code 1.77.3 (704ed70d4fd1c6bd6342c436f1ede30d1cff4710, 2023-04-12T09:16:02.548Z)
OS version: Windows_NT x64 10.0.22624
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz (8 x 2419)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.74GB (5.92GB free)|
|Process Argv|--crash-reporter-id 6aa1c646-62c5-439d-bdf8-5e92b6d0e897|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (19)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|3.0.2
ng-template|Ang|15.2.1
blackbox|Bla|0.10.70
npm-intellisense|chr|1.4.4
vscode-eslint|dba|2.4.0
gitlens|eam|13.5.0
vscode-html-css|ecm|1.13.1
prettier-vscode|esb|9.12.0
auto-close-tag|for|0.5.14
vscode-pull-request-github|Git|0.62.0
ionic|Ion|1.38.0
dotenv|mik|1.0.1
vscode-typescript-next|ms-|5.1.20230427
color-highlight|nau|2.5.0
tsimporter|pmn|2.0.1
vscode-css-peek|pra|4.2.0
LiveServer|rit|5.7.9
tabnine-vscode|Tab|3.6.45
vscode-gradle|vsc|3.12.7

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscorecescf:30445987
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
nodejswelcome1:30587005
2e4cg342:30602488
pyind779:30671433
f6dab269:30613381
vscrp:30673768
pythonsymbol12:30671437
2i9eh265:30646982
6233i204:30672705
vsccsb:30705552
azdwalk:30721579
pythonms35:30701012
pythonfmttextcf:30716743
pythonclientmv:30725892

```

</details>

**Comment by gjsjohnmurray** [comment]
Maybe https://github.com/microsoft/vscode/issues/180568#issuecomment-1518293221 will help.

**Comment by lramos15** [comment]
Please try @gjsjohnmurray's fix and will re-open it if this doesn't solve your problem
