### ISSUE TITLE
Markdown - inconsistence rendering of code blocks in editor and preview

### ISSUE THREAD

**Issue by dhcgn** [Microsoft/vscode#18105]
- VSCode Version: 1.8.1
- OS Version: Win7Pro

# Language name

Editor understands `c#` and `csharp`, preview tab only `csharp`.

Editor
![image](https://cloud.githubusercontent.com/assets/6566207/21645023/b2da3790-d290-11e6-93ff-5785fda01f60.png)
Preview tab
![image](https://cloud.githubusercontent.com/assets/6566207/21645028/bb25bad2-d290-11e6-92a3-16c81ffddbd8.png)

Editor
![image](https://cloud.githubusercontent.com/assets/6566207/21645036/c20e3612-d290-11e6-82a6-cb99e279ba14.png)
Preview tab
![image](https://cloud.githubusercontent.com/assets/6566207/21645043/c7ceec7c-d290-11e6-99c3-9da154cdd1e5.png)

# Syntax highlighting

Colors differs between editor and preview tab.

Editor
![image](https://cloud.githubusercontent.com/assets/6566207/21645114/13831486-d291-11e6-820d-993dbf855ff6.png)
Preview tab
![image](https://cloud.githubusercontent.com/assets/6566207/21645129/20a0fb7e-d291-11e6-8ae5-e0ef866f5f5d.png)

**Comment by nambrot** [comment]
I have the same problem with Scala
