### ISSUE TITLE
High CPU usage by Visual Studio Code

### ISSUE THREAD

**Issue by Ebeldev** [microsoft/vscode#181068]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.77.3
- OS Version:  Mac 13.3.1

I have been experiencing high cpu usage everytime I start and use VSCode, since about 2 or 3 months. 

Steps to Reproduce:

1. Open VSCode
2. The cpu usage goes up. If I open 3  windows of vscode (some with reacnative, wordpress and nodejs projects), the CPU goes way up high if you look at the activity monitor.
![Screenshot 2023-04-27 at 4 50 44 PM](https://user-images.githubusercontent.com/8010184/234989780-924ed857-9d5a-4274-8c7a-a00e9f408653.png)
You can see the 3 processes for vscode is running at 245% each of my cpu!. 

As soon as I start vscode, my fans goes up and stays on pretty. As soon as I close VsCode the fans goes down. 

I update OS version, VSCode version, shutdown the computer, follow the recommendations (disable all extensions, delete user settings), open vscode insiders (the insiders does not make my fan or my cpu goes up). Still always the same results, the fan blows a lot.

**Comment by Ebeldev** [comment]
It works good now. 

Here what I did. 

1. Free up space on my hard drive. (Vs code still takes a lot of cpu)
2. Deleted Vs Code, reinstall it. (Vs code still takes a lot of cpu)
3. Uninstall all extension and only reinstall as few extensions possible. (Vs code is running good)

And it works correctly now.

**Comment by carloshpb** [comment]
Not okay at all. Out of the blue, VSCode has started to use 100% of my Quad-Core CPU, without doing anything at it (like installing new extensions or removing any)
