### ISSUE TITLE
JSON intellisence is not working

### ISSUE THREAD

**Issue by KlsBecker** [microsoft/vscode#181073]
Type: <b>Bug</b>

It seems as if VSCode doesn't support the JSON language, it's not possible to use its intelli sense or anything else related to that language.

When looking for the language settings in the settings, the message "No Settings Found" appears.

I've tried reinstalling VSCode and it's still the same.

I am available to provide any additional information that may be necessary to resolve this issue.

VS Code version: Code 1.77.3 (704ed70d4fd1c6bd6342c436f1ede30d1cff4710, 2023-04-12T09:16:02.548Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: No
Remote OS version: Linux x64 5.15.90.1-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz (8 x 1382)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.74GB (1.69GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-18.04|
|OS|Linux x64 5.15.90.1-microsoft-standard-WSL2|
|CPUs|11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz (6 x 1382)|
|Memory (System)|9.72GB (7.61GB free)|
|VM|0%|
</details><details><summary>Extensions (29)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|13.3.1
openvpn|idl|0.3.1
better-shellscript-syntax|jef|1.6.1
kconfig|luv|1.0.3
jupyter-keymap|ms-|1.1.0
remote-ssh|ms-|0.100.0
remote-ssh-edit|ms-|0.84.0
remote-wsl|ms-|0.77.0
remote-explorer|ms-|0.4.0
material-product-icons|PKi|1.5.0
autocomplate-shell|tru|0.1.1
doxdocgen|csc|1.4.0
gitlens|eam|13.5.0
terminal-in-status-bar|fly|0.0.1
git-graph|mhu|1.30.0
python|ms-|2023.6.1
vscode-pylance|ms-|2023.4.40
jupyter|ms-|2023.3.1201040234
jupyter-keymap|ms-|1.1.0
jupyter-renderers|ms-|1.0.15
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-slideshow|ms-|0.1.5
cpptools|ms-|1.14.5
makefile-tools|ms-|0.7.0
command-variable|rio|1.52.0
code-spell-checker|str|2.20.4
code-spell-checker-portuguese-brazilian|str|2.0.12
cpp-comment-generator|wuj|0.0.9
json|Zai|2.0.2

(1 theme extensions excluded)

</details>

**Comment by aeschli** [comment]
We provide code completions in JSON files if the JSON file has a JSON schema associated with is.
See https://code.visualstudio.com/docs/languages/json for more information what VS Code provides and how to configure a schema.

If this still doesn't work for you, can you provide a small code sample (along the the file name for that sample), describe what you see and what you expect?

**Comment by KlsBecker** [comment]
When opening any parameterization JSON file from VSCode itself (e.g. settings.json, launch.json, task.json), no intelli sense , or code competition is displayed.

In addition, the settings referring to JSON, do not appear for me, when creating some config related to JSON as "json.schema" this parameter becomes opaque in the settings.json file, it is as if my IDE does not provide support for this language. ..

**Comment by aeschli** [comment]
Can you verify that when you open one of these files, the language mode is `JSON` or `JSON with Comments`. That's shown in the status bar. There should also be a symbol `{}`that when you hover over it will show you that a schema has been used.

If that's not the case, check that 
- the JSON extensions are enabled:
![image](https://user-images.githubusercontent.com/6461412/235425796-dd1ee72f-0ddb-40f7-9ad1-0d0bcef6c626.png)
- Configuration editor is enabled:
![image](https://user-images.githubusercontent.com/6461412/235425943-2e8cabef-f036-4aa3-845d-818d94140021.png)

**Comment by KlsBecker** [comment]
I don't know how, but the JSON Bultin extension was disabled. This is strange because I didn't know that there were this type of extensions, so I never disabled it. 

Anyway, I turned it on again and everything works fine. 

Thank's for your help!

**Comment by aeschli** [comment]
Thanks for the reply. Closing.
