### ISSUE TITLE
VSCODE not responding fast

### ISSUE THREAD

**Issue by dinesh38555** [microsoft/vscode#181092]
Type: <b>Performance Issue</b>

After the last update of vscode I am facing these issues. My vscode is not opening immediately when I start it.It's taking very long to start it.

VS Code version: Code 1.77.3 (704ed70d4fd1c6bd6342c436f1ede30d1cff4710, 2023-04-12T09:16:02.548Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: No

<details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
isort|ms-|2022.8.0
python|ms-|2023.6.1
vscode-pylance|ms-|2023.4.30
java|red|1.17.0
vscode-java-debug|vsc|0.50.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vscaac:30438847
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
nodejswelcome1:30587005
2e4cg342:30602488
pyind779:30671433
f6dab269:30613381
pythonsymbol12:30671437
showlangstatbar:30672706
vsccsb:30705552
azdwalk:30721579
pythonms35:30701012
pythonfmttext:30716742

```

</details>

**Comment by bpasero** [comment]
If you have McAfee: Antivirus installed, can you uninstall that and try if it helps?

**Comment by dinesh38555** [comment]
Thank you for your assistance. Uninstalling McAfee has improved the performance of Visual Studio Code on my system. However, I am curious to know why McAfee was affecting the performance of Visual Studio Code on my current system, while it did not have the same effect when I ran it using the Program Compatibility troubleshooter on Windows 8. This type of issue did not occur for me earlier, and it only took place after the last update of Visual Studio Code.

**Comment by bpasero** [comment]
I suggest you report it to them.
