### ISSUE TITLE
 TypeError: Cannot read property 'apply' of undefined

### ISSUE THREAD

**Issue by vscodeerrors** [Microsoft/vscode#1810]
Issue Id: <b>bf34bcd5-6b6a-9e67-470e-92af0248f808</b><br /><br />*Versions* <br />- 0.9.2<br />-  783ecf841a2b21edca6d86853670cae89b4c244f<br />-  df352367df2efcfa9d602d471e4e2f42140a0f05<br />-  dfc08dc9edf6607483b193bf934d3badc3fa2e11<br />-  7917414ff6ec7255dc60b2f7881e5178966e864e<br />-  a80232bbcfe8a5cdad1ebc98638673d9dcb02458<br />-  7cc0c602a2b802b09a3f56b68a1a61ee9e8f0066<br />-  76a59279c3f40e630e5af72b996f2783f4d5aa79<br />*Stack* <br />TypeError: Cannot read property 'apply' of undefined<br />[/vs/platform/thread/common/abstractThreadService.ts#L138:23 (AbstractThreadService.handle)](https://github.com/microsoft/vscode/blob/3fd93bd0833cc6ad311134e254f8ec2b048994a3/src/vs/platform/thread/common/abstractThreadService.ts#L138:23 (AbstractThreadService.handle))<br />[/vs/base/common/worker/workerProtocol.ts#L110:39 (RemoteCom._invokeHandler)](https://github.com/microsoft/vscode/blob/3fd93bd0833cc6ad311134e254f8ec2b048994a3/src/vs/base/common/worker/workerProtocol.ts#L110:39 (RemoteCom._invokeHandler))<br />[/vs/base/common/worker/workerProtocol.ts#L105:14 (RemoteCom.handleMessage)](https://github.com/microsoft/vscode/blob/3fd93bd0833cc6ad311134e254f8ec2b048994a3/src/vs/base/common/worker/workerProtocol.ts#L105:14 (RemoteCom.handleMessage))<br />[/vs/base/common/worker/workerServer.ts#L200:19 (WorkerServer._handleMessage)](https://github.com/microsoft/vscode/blob/3fd93bd0833cc6ad311134e254f8ec2b048994a3/src/vs/base/common/worker/workerServer.ts#L200:19 (WorkerServer._handleMessage))<br />[/vs/base/common/worker/workerServer.ts#L192:9 (WorkerServer._onmessage)](https://github.com/microsoft/vscode/blob/3fd93bd0833cc6ad311134e254f8ec2b048994a3/src/vs/base/common/worker/workerServer.ts#L192:9 (WorkerServer._onmessage))<br />[/vs/base/common/worker/workerServer.ts#L125:7 (WorkerServer.onmessage)](https://github.com/microsoft/vscode/blob/3fd93bd0833cc6ad311134e254f8ec2b048994a3/src/vs/base/common/worker/workerServer.ts#L125:7 (WorkerServer.onmessage))<br />    at DedicatedWorkerGlobalScope.self.onmessage (out/vs/base/worker/workerMain.js?service2:5:373)<br />

**Comment by alexandrudima** [comment]
Dup of #2236
