### ISSUE TITLE
Nerd Fonts not displaying properly in Codespaces in Safari

### ISSUE THREAD

**Issue by oliverlabs** [microsoft/vscode#181038]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: Insiders (latest)
- OS Version: Mac OS (latest)

Steps to Reproduce:

1. Open GitHub Codespaces in Safari browser
2. Open Terminal within the opened Codespace
3. Ensure that the Nerd font is not being displayed correctly

There is a similar issue #83294 which is open. I am not sure if it is caused by the same font limitation in Mac OS.

**Comment by meganrogge** [comment]
Yeah looks like the same issue
