### ISSUE TITLE
Compatibility with Baidu IME on ubuntu 18/20/22

### ISSUE THREAD

**Issue by tu6ge** [microsoft/vscode#181083]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.77.3
- OS Version: ubuntu 22.04
- [Baidu IME](http://srf.baidu.com/site/guanwang_linux/) 

Steps to Reproduce:

1. install Baidu IME.
2. open vscode integrated terminal with any dir.
3. when I input `git` in bash, it should change to `giit` or `gitt`, and If I input slowly, there will be no problem

I consulted Baidu about this issue, but there was no response.

**Comment by Tyriar** [comment]
Upstream: https://github.com/xtermjs/xterm.js/issues/4537

**Comment by Tyriar** [comment]
Let's track this upstream
