### ISSUE TITLE
Separate `.vscode-cli` per quality

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode#181017]
Run separate tunnels with insiders and oss.

Note that we still use the same data folder `.vscode-cli`. The `code_tunnel.json` file is overwritten by each quality,

A `code_tunnel.json` per quality would be a possibility, but I still think we should either
- follow the example of VS Code and keep qualities as separate products, each with its own data folder (names specified in `product.json`)
- have a folder `cli` in the existing data folder `.vscode`, `.vscode-insiders`...

**Comment by meehien** [comment]
Also, would it be possible to `.vscode-cli` directory stored with the rest of the settings in VS code's data folder? I am using a custom location for my settings and this gets created in my userprofile.
