### ISSUE TITLE
Add expand all / collapse all support for file explorer folders.

### ISSUE THREAD

**Issue by Andrew1431** [Microsoft/vscode#18109]
In sublime, if you alt-click a folder that is closed, it will open all subfolders as well, (expanding the entire tree). If you alt-click a folder that is opened, it will collapse the entire tree underneath, and upon reopening you will have a nice fresh view of closed folders, etc. Would love to have this functionality in vs code!

**Comment by Andrew1431** [comment]
Hmm I, literally upon posting this, JUST found the collapse all button in the file explorer. This will suit my needs for now :) But to have it for individual folders would be awesome.

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/9456
