### ISSUE TITLE
Error when trying to detect gulp tasks

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#181028]
Found while verifying https://github.com/microsoft/vscode/issues/175821

1. Open your clone of this repo in VS Code
2. Command "Run Task"
3. Choose "gulp"
4. Choose "Gulp task detection is turned off. Enable gulp task detection..."
5. See error "Unable to write gulp.autoDetect to Workspace Settings. This setting can be written only into User settings."

**Comment by meganrogge** [comment]
I can repro. Happens when the configuration scope is `application`. Weird because I don't think this has changed recently 🤔 

https://github.com/microsoft/vscode/blob/b44d1fb989750ebd168ca7b05f373cd0e264906c/src/vs/workbench/services/configuration/common/configurationEditing.ts#L522-L524

**Comment by meganrogge** [comment]
Doesn't reproduce in stable, so seems like a regression from https://github.com/microsoft/vscode/issues/175821

**Comment by meganrogge** [comment]
Does not reproduce with `grunt`

**Comment by meganrogge** [comment]
`grunt` and `gulp` have the same scope here, so not sure what is going on 

![Screenshot 2023-04-27 at 7 50 19 AM](https://user-images.githubusercontent.com/29464607/234900882-7ecc4f32-9386-450d-a41a-905cb056c70f.png)

**Comment by meganrogge** [comment]
Oh, I think that's because there aren't any `grunt` tasks

**Comment by meganrogge** [comment]
Reverting that PR does not fix it

**Comment by meganrogge** [comment]
`gulp` task detection is working for me now. @alexr00 pls lmk if you can still repro
