### ISSUE TITLE
Launch Vscode server from current ssh session like wsl

### ISSUE THREAD

**Issue by tomoum** [microsoft/vscode#181074]
It would be super helpful to launch vscode remote ssh from the command line while I am inside an ssh session like `code .` you can do this with wsl (windows subsystem for linux) why not from a remote ssh session? this is very annoying as I am constantly moving around my target and needing to edit files all over the place and having to go to vscode and open the file from there is super annoying. 

example:

Currently: 
1. open vscode.
2. use the ms-vscode-remote.remote-ssh extension to connect to the remote host
3. open the folder on the remote target.

Feature Request:
1. ssh to my remote target `ssh user@mylinuxpc`
2. navigate to the folder I want `cd ~/work/project`
3. open remote vscode session `code .` or `code myfile.sh`

Thank you!

**Comment by roblourens** [comment]
Unfortunately it's not really possible for us to do this because there is no way for us to call out from your remote machine to the local one to open a vscode window
