### ISSUE TITLE
Search preview text incorrect formatting notebooks

### ISSUE THREAD

**Issue by eleanorjboyd** [microsoft/vscode#181057]
was verifying this bug was fixed when I came across this other bug (sorry if it has already been reported). 

When I first search for something, this is what I see
![image](https://user-images.githubusercontent.com/26030610/234950416-2c739545-d665-4bad-9b91-28bef814ab85.png)

After I click to open that page, the preview text then changes to this
![image](https://user-images.githubusercontent.com/26030610/234950464-417fec1c-cff9-46ad-8d80-af2830002161.png)

After I close that given page the preview text stays in the correct formatting until I redo a search
![image](https://user-images.githubusercontent.com/26030610/234950549-c3df9cf6-4b7b-4938-8226-0c41e57cacf7.png)

**Comment by andreamah** [comment]
This is intentional, since the formatted version of the search result is considered the most accurate preview. Closing this for now, but we can also discuss if this seems like the wrong approach.
