### ISSUE TITLE
Built-in fonts

### ISSUE THREAD

**Issue by babakfp** [microsoft/vscode#181157]
Are there any plans to add built-in fonts to vscode? To keep the UI consistent and avoid UI complications and other related issues? For example adding a few popular, free, and open-source fonts, for the editor and the markdown. So the developers can also easily switch between the built-in fonts...

### `JetBrainsMono` font used on the entire editor:

![Screenshot 2023-04-28 125812-min](https://user-images.githubusercontent.com/44144724/235244885-4f6f4b0d-9a5e-4a05-85b1-37afc6ccb541.png)

### Select your desired built-in font:

![Mask Group 2-min (1)](https://user-images.githubusercontent.com/44144724/235246737-a188a6b9-85c4-4c56-bbb1-a1ba9e8d2ff0.png)

![Mask Group 3-min](https://user-images.githubusercontent.com/44144724/235246769-a0f23fd2-ef1a-40b1-8632-20e0c7bda8a1.png)

**Comment by rzhao271** [comment]
I'm not sure about shipping fonts with the product, but parts of the designs you posted are being tracked by other feature requests.

For the font picker, see https://github.com/microsoft/vscode/issues/128355.
For customizable workbench fonts, see https://github.com/microsoft/vscode/issues/519.
