### ISSUE TITLE
vscode.dev: Infinite project loading on Safari 16.4, 16.5

### ISSUE THREAD

**Issue by bandantonio** [microsoft/vscode#181156]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: vscode.dev
  - Version: 1.77.3
  - Commit: 704ed70d4fd1c6bd6342c436f1ede30d1cff4710
  - Date: 2023-04-12T09:19:00.989Z
  - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.5 Safari/605.1.15
- OS Version: macOS Monterrey 12.6.5

Steps to Reproduce:

1. Make sure you're using Safari 16.4
2. Open any link in vscode.dev. For example, theme preview: the one from the [docs](https://vscode.dev/theme/wesbos.theme-cobalt2) or my own [theme](https://vscode.dev/theme/mister-gold.aurora-borealis-theme)
3. Check that the project is not loading: ![](https://user-images.githubusercontent.com/16765690/235243440-67d7c575-de11-469d-90fe-f719c260bc1d.mov)

Furthermore, there are tons of errors in the console:
<img width="1512" alt="console" src="https://user-images.githubusercontent.com/16765690/235243770-6945c92d-1ba6-4ee5-85d9-1c3834471921.png">

I tried the links in other browsers:
- Safari Technological Preview (Release 168 (Safari 16.4, WebKit 17616.1.10.2)) - OK
- Google Chrome (Version 112.0.5615.137 (Official Build) (arm64) - OK
- Safari 16.4 - issue exists
- Safari Beta 16.5 - issue exists

I believe that it's 95% something wrong with my Safari setup, but I can't figure out the origin of the errors in console.
I worked with vscode.dev about a week ago without any issues and no changes in browser were made since then.

Any help or clues are highly appreciated 🙏 Thank you

**Comment by bpasero** [comment]
Can you clear all caches? When this happens and you reload from devtools without caches, does it help?

**Comment by bandantonio** [comment]
@bpasero Yes, basically I cleared caches in the first place, just forgot to mention it (I did it from the Settings and Develop menu). However, this didn't help, all the errors are still there.

<img width="500" alt="caches" src="https://user-images.githubusercontent.com/16765690/235301878-27b6baa9-4db1-43c0-84fe-75eee1dcd7f6.png">

**Comment by bpasero** [comment]
Does it work if you use `insiders.vscode.dev` instead?

**Comment by bandantonio** [comment]
> Does it work if you use `insiders.vscode.dev` instead?

Nope, still the same

**Comment by bpasero** [comment]
I am quite puzzled that the Technology Preview with the same version does not show this issue, I wonder if your normal Safari has some kind of setting or experiment enabled that triggers this...

**Comment by bandantonio** [comment]
The issue was related to my spell checker extension 😔 in Safari. After disabling it, the project loaded successfully in vscode.dev and insiders.vscode.dev both directly via a link and from GitHub after pressing the `.` (dot) (despite the errors in the console are still there).

Thanks for your help, I knew that something wrong with that specific version and with your guidance I made sure that the problem is not in the settings. So extensions were the only suspects.
