### ISSUE TITLE
auto closing tags  doest not work

### ISSUE THREAD

**Issue by irfan9244** [microsoft/vscode#181194]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 
- OS Version: 

Steps to Reproduce:

1. 
2.

**Comment by aeschli** [comment]
I just verified they work in HTML.
- create a file `foo.html`. Validate that the language selector in the status bar says `HTML`
- make sure setting `html.autoClosingTags` is true
- type `<div`
- type `> ` and you see that `</foo>` is automatically added

If this doesn't work for you, please provide a code sample and precise steps to reproduce

**Comment by aeschli** [comment]
I just verified they work in HTML.
- create a file `foo.html`. Validate that the language selector in the status bar says `HTML`
- make sure setting `html.autoClosingTags` is true
- type `<div`
- type `> ` and you see that `</foo>` is automatically added

If this doesn't work for you please provide a code sample and precise steps to reproduce
