### ISSUE TITLE
File: Reveal Active File in Explorer View when Media Preview (image opened)

### ISSUE THREAD

**Issue by setupson** [microsoft/vscode#181101]
`File: Reveal Active File in Explorer View` works on text/code files but not works when image file is focused/opened.

**Comment by lramos15** [comment]
![Recording 2023-04-28 at 09 20 39](https://user-images.githubusercontent.com/4544166/235201543-f295f707-181f-4af7-8dc5-9c209e702a64.gif)

Am I missing a step to repro this issue?

**Comment by setupson** [comment]
Doing it from command palete works as expected.

https://user-images.githubusercontent.com/32313101/235308900-14da4ac1-5ca2-408a-8cc3-c4f29ee86a22.mp4

But using keyboard shortcut (Ctrl+R in my case) not works for **image files**.


https://user-images.githubusercontent.com/32313101/235308908-84d374cd-077b-4ec0-a834-27fb041dbb0b.mp4

Maybe my custom config is wrong.

![image](https://user-images.githubusercontent.com/32313101/235308730-597c9783-a417-48cd-8786-c318380ee530.png)

**Comment by lramos15** [comment]
It must be your configuration as when I set a shortcut (I tried Shift + alt +r) image files work the same as well. I would follow the wiki for keybinding issues and try and figure out what when clause may be incorrect.
