### ISSUE TITLE
run sign 

### ISSUE THREAD

**Issue by zubuxmd** [microsoft/vscode#181184]
Type: <b>Feature Request</b>

my run sign is not showing on scren

VS Code version: Code 1.77.3 (704ed70d4fd1c6bd6342c436f1ede30d1cff4710, 2023-04-12T09:16:02.548Z)
OS version: Windows_NT x64 10.0.22000
Modes:
Sandboxed: No

**Comment by roblourens** [comment]
Likely related to the Code Runner, you can open an issue on that extension
