### ISSUE TITLE
json.schemas does not support relative url

### ISSUE THREAD

**Issue by bgausden** [microsoft/vscode#181187]
Type: <b>Bug</b>

In settings.json define json.schemas "fileMatch" and "url". 

In url enter a relative path for the schema file.

Expect: a relative url value will be interpreted as relative to ${workspaceFolder}.

Actual: VS Code will interpret the url value as relative to the drive root on Windows.

e.g.

```
"json.schemas": [
        {
            "fileMatch": [
                "*/src/staffHurdle.json"
            ],
            "url": "./staffHurdleSchema.json"
        }
    ],
```

Will show the following error in the Problems pane:
`Unable to load schema from '\.\staffHurdleSchema.json': ENOENT: no such file or directory, open 'd:\staffHurdleSchema.json'.
`

Impact: JSON validation is broken if the location of the workspace folder is changed

VS Code version: Code - Insiders 1.78.0-insider (b19017cea80b6157aa8214c984a70022e77526f2, 2023-04-21T05:21:50.420Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz (8 x 3600)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.94GB (19.32GB free)|
|Process Argv|--crash-reporter-id e1070bf9-1a99-46ef-818f-2bd2eb9d9f7e|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
npm-intellisense|chr|1.4.4
vscode-eslint|dba|2.4.0
copilot-chat|Git|0.1.2023042804
copilot-labs|Git|0.12.791
copilot-nightly|Git|1.84.61
azure-dev|ms-|0.5.0
vscode-edge-devtools|ms-|2.1.1

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vslsvsres303:30308271
pythontb:30258533
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscod805cf:30301675
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30404738
cppdebug:30492333
vsclangdf:30492506
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30618038
pylantcb52:30590116
nodejswelcome1:30587009
pyind779:30611226
vscrp:30624060
pythonsymbol12:30651887
6233i204:30725950
azdwalk:30721579
pythonms35:30671666
j16hj152:30680472
24365598:30687740
pythonfmttext:30716741
pythoncmvfstr:30726892
fixhidewlkth:30724384
hidesbindicator:30724476
pythongtdpath:30726887

```

</details>

**Comment by bgausden** [comment]
The [VS Code documentation](https://code.visualstudio.com/docs/languages/json) states:

> To map a schema that is located in the workspace, use a relative path.

The observed behaviour of VS Code does not appear to align with the instructions or the example provided in the section "Mapping to a schema in the workspace" on the linked page.

**Comment by aeschli** [comment]
Yes, when defined in the workspace or folder settings, you can also use relative URLs. They are resolved against the workspace file resp. folder.
I just verified this works.
You can try this here: https://github.com/aeschli/test-schema-in-workspace
- open folder1
- open `foo.java` and verify it gets associated with `foo.schema.json`

**Comment by bgausden** [comment]
I'm unable to reproduce your result in my workspace. 

`[Trace - 2:34:17 PM] Sending request 'textDocument/diagnostic - (192)'.
Params: {
    "textDocument": {
        "uri": "file:///d%3A/git/Commission/src/staffHurdle.json"
    }
}


[Trace - 2:34:17 PM] Received response 'textDocument/diagnostic - (190)' in 2ms.
Result: {
    "kind": "full",
    "items": []
}


[Trace - 2:34:17 PM] Received request 'vscode/content - (67)'.
Params: [
    "vscode://schemas/settings/user"
]


[Trace - 2:34:17 PM] Received response 'textDocument/diagnostic - (192)' in 3ms.
Result: {
    "kind": "full",
    "items": [
        {
            "range": {
                "start": {
                    "line": 0,
                    "character": 0
                },
                "end": {
                    "line": 0,
                    "character": 1
                }
            },
            "message": "Unable to load schema from '\\staffHurdleSchema.json': ENOENT: no such file or directory, open 'd:\\staffHurdleSchema.json'.",
            "severity": 2,
            "code": 768
        }
    ]
}


[Trace - 2:34:17 PM] Sending notification 'textDocument/didOpen'.
Params: {
    "textDocument": {
        "uri": "vscode://schemas/settings/user",
        "languageId": "jsonc",
        "version": 1,
        "text": "{\"properties\":{\"editor.tabSize\":{\"type\":\"number\",\"default\":4,\"minimum\":1,\"markdownDescription\":\"The number of spaces a tab `

**Comment by bgausden** [comment]
OK. Now have it working.

settings.json in the **User** context only supports absolute paths to schema files.

settings.json in the **Workspace** or **Folder** context supports both absolute and relative URIs

![image](https://user-images.githubusercontent.com/130431/236663043-3041d08d-32ba-44a2-9ba5-fdecdda2d53e.png)

The below sample works, although I note the url is relative to ${workspacefolder} rather than the fileMatch).
```
        "json.schemas": [
            
            {
                "fileMatch": [
                    "staffHurdle.json"
                ],
                "url": "./src/staffHurdleSchema.json"
            }
        ]
```

**Comment by aeschli** [comment]
Yes, it's relative to the workspace folder, or the workspace file (if defined there).
