### ISSUE TITLE
[MacOS] Tooltip disappears when try to hover on it

### ISSUE THREAD

**Issue by PawelNiedzwiecki** [microsoft/vscode#181130]
When I try to mouse over any tooltip (mainly to click on github intellisense links etc.) the tooltip disappears. Tried launching VS Code without any extentions using `code --disable-extensions` but no luck.
Here's a quick video of the issue:

https://user-images.githubusercontent.com/66324097/235164755-b409212a-64cd-45d4-80fe-eca8dc29e39c.mp4

- VS Code Version: 
```
Version: 1.77.3
Commit: 704ed70d4fd1c6bd6342c436f1ede30d1cff4710
Date: 2023-04-12T09:41:48.638Z
Electron: 19.1.11
Chromium: 102.0.5005.196
Node.js: 16.14.2
V8: 10.2.154.26-electron.0
OS: Darwin arm64 22.4.0
Sandboxed: No
```
- OS Version: `MacOS Ventura 13.3.1 (22E261)`

Steps to Reproduce:

1. Mouse over any element within the code to show the tooltip
2. Try to mouse over the tooltip area
3. Tooltip disappears

**Comment by AlencarGabriel** [comment]
I have the same problem. I thought it was associated with my extension, but apparently not.

This behavior does not happen with the GitLens extension.

**Comment by PawelNiedzwiecki** [comment]
Hello again! Any updates on this one?

**Comment by PawelNiedzwiecki** [comment]
Hi @aiday-mar ! Thanks for reply. I installed Insiders version and tooltip works there. However it's still an issue for a stable version of VSCode.

**Comment by aiday-mar** [comment]
Hi thanks for your reply. The current Insiders code will be soon shipped to the stable version (by next week), and the problem should be solved at that time.
