### ISSUE TITLE
Automatic Type Acquisition not loading types

### ISSUE THREAD

**Issue by mbugbee** [Microsoft/vscode#18118]
- VSCode Version: 1.8.1
- OS Version: 10.12.2

Dependencies:
"devDependencies": {
    "enzyme": "^2.4.1",
    "eslint": "^3.11.1",
    "eslint-config-airbnb": "^13.0.0",
    "eslint-import-resolver-babel-module": "^2.2.1",
    "eslint-plugin-flowtype": "2.21.0",
    "eslint-plugin-import": "^2.2.0",
    "eslint-plugin-jsx-a11y": "^2.2.3",
    "eslint-plugin-react": "^6.8.0",
    "jest-cli": "^17.0.0",
    "jsdom": "^9.5.0",
    "moxios": "^0.3.0",
    "nock": "^8.0.0",
    "react-addons-test-utils": "^15.3.2",
    "react-hot-loader": "^1.3.1",
    "redux-devtools": "^3.3.1",
    "stylelint": "^7.6.0",
    "supertest": "^2.0.0",
    "supertest-as-promised": "^4.0.0",
    "webpack-dev-server": "^1.15.1"
  },
  "dependencies": {
    "axios": "^0.14.0",
    "babel-core": "^6.14.0",
    "babel-eslint": "7.0.0",
    "babel-loader": "^6.2.5",
    "babel-plugin-module-resolver": "^2.4.0",
    "babel-plugin-transform-regenerator": "^6.16.1",
    "babel-plugin-transform-runtime": "^6.15.0",
    "babel-polyfill": "^6.16.0",
    "babel-preset-es2015": "^6.14.0",
    "babel-preset-react": "^6.11.1",
    "babel-preset-stage-0": "^6.5.0",
    "bunyan": "^1.8.3",
    "cookie-parser": "^1.4.3",
    "cookies-js": "^1.2.3",
    "css-loader": "^0.25.0",
    "express": "^4.14.0",
    "extract-text-webpack-plugin": "^1.0.1",
    "file-loader": "^0.9.0",
    "mixpanel": "^0.5.0",
    "nconf": "^0.8.4",
    "node-sass": "^3.13.0",
    "pm2": "^2.0.18",
    "postal": "^2.0.4",
    "postcss-loader": "^1.1.1",
    "react": "^15.3.1",
    "react-dom": "^15.3.1",
    "react-redux": "^4.4.5",
    "react-router": "^2.8.1",
    "react-router-redux": "^4.0.5",
    "redux": "^3.6.0",
    "redux-saga": "^0.12.0",
    "sass-loader": "^4.0.2",
    "style-loader": "^0.13.1",
    "systemjs": "^0.19.39",
    "webpack": "^1.13.2",
    "webpack-stats-plugin": "^0.1.3",
    "yargs": "^6.0.0"
  },

I open a js/jsx file in my project that has import statements, for example "import React from 'react';", but do not receive intellisense support for React.  When checking ~/Library/Application Support/Microsoft I only have a Silverlight folder.  I have verified that "typescript.disableAutomaticTypeAcquisition": false is set.

Any other help on how I can track down the issue would be appreciated!  If I'm missing any helpful information please let me know and I'll provide asap.

**Comment by mjbvz** [comment]
Thank you for the report. Unfortunately I'm not able to repo this on my machine using those dependencies. Using automatic typings accession should create a `TypeScript` folder in `~/Library/Application Support/Microsoft` so it does look like the typings are never being installed.

A few other points to help investigate:

* Are you using a custom `typescript.tsdk` setting or do you have typescript installed locally in your project?
* Can you try adding the setting `"typescript.tsserver.trace": "verbose"` to VSCode and then reloading your project. Then go to the output view and select the `TypeScript` output pane. This output may help us investigate the problem.

You can also try using VSCode 1.9 insiders. It includes a new version of TS (2.1.5-insiders) that fixes a number of corner cases that people have been running into.

**Comment by mbugbee** [comment]
Not using typescript in the project at all so no custom typscript.tsdk.

tsserver trace output:

> [Info  - 4:11:07 PM] Using tsserver from location: /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/typescript/node_modules/typescript/lib/tsserver.js
[Trace - 4:11:07 PM] Sending request: configure (0). Response expected: yes. Current queue length: 0
Arguments: {}
[Trace - 4:11:07 PM] Response received: configure (0). Request took 185 ms. Success: true 
[Trace - 4:11:07 PM] Sending request: compilerOptionsForInferredProjects (1). Response expected: yes. Current queue length: 1
Arguments: {}
[Trace - 4:11:07 PM] Response received: compilerOptionsForInferredProjects (1). Request took 186 ms. Success: true 
Result: true
[Trace - 4:11:07 PM] Sending request: open (2). Response expected: no. Current queue length: 0
Arguments: {}
[Trace - 4:11:08 PM] Event received: configFileDiag (0).
Data: {}
[Trace - 4:11:09 PM] Sending request: open (3). Response expected: no. Current queue length: 0
Arguments: {}
[Trace - 4:11:09 PM] Event received: configFileDiag (0).
Data: {}
[Trace - 4:11:25 PM] Sending request: open (4). Response expected: no. Current queue length: 0
Arguments: {}
[Trace - 4:11:25 PM] Event received: configFileDiag (0).
Data: {}


Dowloaded 1.9 Insider, Intellisense appears to work as intended, however, the '~/Library/Application Support/Microsoft' remains empty.  Is that expected of the Insider build?

**Comment by mjbvz** [comment]
Actually, with 2.1.5, I think TypeScript may be installing the typings files to `~/Library/Caches/typescript/` instead. @mbugbee Can you check if this folder exists?

**Comment by mbugbee** [comment]
Folder exists.

**Comment by mjbvz** [comment]
Good to hear. I believe you were running into one of the known TypeScript 2.1.4 issues and it looks like 2.1.5 fixes things. Closing as upstream. Please let me know if you run into any other issues

In case anyone else runs into this sort of problem using VSCode 1.8, there are two options:

* Install VSCode 1.9 insiders to pick up a insiders release of TypeScript 2.1.5
* Install Typescript 2.1.5 insiders into your workspace (for example `npm install typescript@2.1.5-insiders.20161229`) and point the `typescript.tsdk` setting to the local TypeScript install.

Thanks
