### ISSUE TITLE
Don't show switch to release version button for extensions when no release exists.

### ISSUE THREAD

**Issue by lramos15** [microsoft/vscode#181144]
It would be great if we knew ahead of time as clicking the button will just throw an error notification
<img width="446" alt="image" src="https://user-images.githubusercontent.com/4544166/235193871-b07faacb-10fa-49b9-97b8-7d9d56c0b0f8.png">

**Comment by sandy081** [comment]
/duplicate 

This is known and is a limitation because the MP does not support this.
