### ISSUE TITLE
code convert in to non readable form 

### ISSUE THREAD

**Issue by mueedahmed1** [Microsoft/vscode#18112]
- VSCode Version: Code 1.8.1 (ee428b0eead68bf0fb99ab5fdc4439be227b6281, 2016-12-19T14:49:23.350Z)
- OS Version: Windows_NT ia32 6.3.9600
- Extensions:

|Extension|Author|Version|
|---|---|---|
system is shutdown unexpectedly at the time of shutdown file is not saved when reopen file so all code is lost  
![bug](https://cloud.githubusercontent.com/assets/12622228/21652197/95f6ad42-d2cd-11e6-87b3-0b2c2f88894f.png)

---

Steps to Reproduce:

1.
2.

**Comment by mueedahmed1** [comment]
Please give me quick response

**Comment by mueedahmed1** [comment]
how to convert in to code

**Comment by bpasero** [comment]
@mueedahmed1 can you see if the file on disk still has your contents? the file is dirty and has restored your changes from the last session but it seems like the changes did not make it to disk on the event of the unexpected system shutdown.
