### ISSUE TITLE
Format on unsaved JS/TS not working

### ISSUE THREAD

**Issue by unional** [Microsoft/vscode#18114]
- VSCode Version: 1.8.0

Steps to Reproduce:

1. Create a new file by [Ctrl+n] or [Cmd+n] (so the file is named "Untitled-1"
2. Change the Langauge Mode to JavaScript (in lower right task bar)
3. Paste some unformatted JS/TS code
4. Try to format code [Alt+Shift+f]

Expect the code to be formatted, but it does not.

The same steps work for XML/HTML.

**Comment by mjbvz** [comment]
@unional Thanks. I confirmed the issue.

@dbaeumer In the untitled document case, we do not have a path to a file on disk (`this.client.asAbsolutePath`). This means that the TypeScript extension never attempts to format the document and I don't think the TypeScript server even knows about the document.

Do you have any thoughts on how we should handle untitled documents better? Should we only register the TS formatter for `scheme: 'file'` like we do with the other TS features?

**Comment by dbaeumer** [comment]
Typescript relaxed the need of a file on disk for 2.1. We should try to adopt and test this for the January milestone. The TS team states that they now accept any path (there is no reason that the path exists on disk or is even a valid file path) so we should simply try to pass them the URI as a string we have. The TS team said that if we encounter problems with this they will fix them.
