### ISSUE TITLE
Terminal cuts off long strings when debugging

### ISSUE THREAD

**Issue by boppreh** [microsoft/vscode#181182]
Type: <b>Bug</b>

## Steps to reproduce:

1. Create a Python file with the following code that prints a 1MB string made of '0123456789' repeated 100.000 times:

```python 
print('\n'.join(['0123456789' for i in range(100_000)]))
print('finished')
```

2. Run with "Python: Debug Python file".

Note it only happens with "Debug Python file", not "Run Python file in Terminal".

## Expected

The last lines in Terminal are

    [...]
    0123456789
    0123456789
    0123456789
    finished

## Observed

The last lines in Terminal are

    [...]
    0123456789
    0123456789
    01
    finished

showing that the string got cut at some point. Note that the program continued running.

## Environment

VS Code version: Code 1.77.3 (704ed70d4fd1c6bd6342c436f1ede30d1cff4710, 2023-04-12T09:16:02.548Z)
OS version: Windows_NT x64 10.0.19045
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 3600 6-Core Processor               (12 x 3600)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.95GB (22.49GB free)|
|Process Argv|--crash-reporter-id 36b87417-7c27-4264-9aea-a5731eebb150|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-html-css|ecm|1.13.1
copilot|Git|1.84.51
go|gol|0.38.0
python|ms-|2023.6.1
vscode-pylance|ms-|2023.4.40
jupyter|ms-|2023.3.1201040234
jupyter-keymap|ms-|1.1.0
jupyter-renderers|ms-|1.0.15
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-slideshow|ms-|0.1.5
powershell|ms-|2023.3.3
rust-analyzer|rus|0.3.1489

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
nodejswelcome1:30587005
2e4cg342:30602488
pyind779:30671433
f6dab269:30613381
pythonsymbol12:30671437
2i9eh265:30646982
vsctsb:30705553
azdwalk:30721579
pythonms35:30701012
pythonfmttextcf:30716743
pythonclientmvcf:30725893

```

</details>

**Comment by roblourens** [comment]
Please file this on the vscode-python extension repo. Since I think that configuration just involves running the python code "normally" in the terminal but with the debugger attached, I don't know how you would end up with this...

```
01
finished
```

**Comment by boppreh** [comment]
Thanks, created https://github.com/microsoft/vscode-python/issues/21170 .
