### ISSUE TITLE
[html] URL autocompletion doesn't work for cite attributes in HTML

### ISSUE THREAD

**Issue by anthonyvdotbe** [microsoft/vscode#181176]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.77.3 (704ed70d4fd1c6bd6342c436f1ede30d1cff4710)
- OS Version: 10.0.22621

Steps to Reproduce:

1. create the file `root/ref/source.html`
2. create the file `root/main.html` containing a `blockquote` with a `cite` attribute and attempt to use URL autocompletion (as with the `src` attribute of `img` elements) to set its value to `ref/source.html`. The same issue occurs with a `q` element (and there may be others I'm unaware of).

**Comment by roblourens** [comment]
I don't see any smart suggestions, only word-based, when I type in here `<blockquote cite="">`, is that how it's supposed to work?
