### ISSUE TITLE
Consider to have a separate log channel for extensions location

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#181175]
There is quite a lot of output when you run with `--verbose` from:

https://github.com/microsoft/vscode/blob/34cba75c513878d683004561c799dd5cd13f5222/src/vs/workbench/services/extensions/electron-sandbox/nativeExtensionService.ts#L747

<img width="1508" alt="image" src="https://user-images.githubusercontent.com/900690/235287695-9cd30fea-7908-40fd-92fd-dfbeafc64bd1.png">

Maybe this could go to a dedicated log channel.

//cc @sandy081

**Comment by sandy081** [comment]
I would keep this in the window log, probably having better filter capabilities will help here.
