### ISSUE TITLE
Kotlin Hello World

### ISSUE THREAD

**Issue by AGoh2019** [microsoft/vscode#181186]
Type: <b>Bug</b>

Ran HelloWorld.kt
Errors -
- Variable ${workspaceRoot} can not be resolved.
- Kotlinc is not recognised as an internal or external command, operable program or batch file.

VS Code version: Code 1.77.3 (704ed70d4fd1c6bd6342c436f1ede30d1cff4710, 2023-04-12T09:16:02.548Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz (8 x 2419)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.77GB (7.48GB free)|
|Process Argv|--crash-reporter-id 878a6b85-9049-465e-849e-1cc9b3b95d57|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by lszomoru** [comment]
Could you please file an issue in [the extension's repository](https://github.com/fwcd/vscode-kotlin/issues)? Thank you!
