### ISSUE TITLE
Node process is not killed when quit vs code

### ISSUE THREAD

**Issue by sentend** [microsoft/vscode#181111]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.77.3
- OS Version: Darwin arm64 22.4.0

when i'm working with my project im running next command: 
"start": "node --preserve-symlinks ./node_modules/webpack/bin/webpack serve",
so when i quit vs code this process is not killed and remains until it is forcibly closed or killed with the `kill -9`  

Does this issue occur when all extensions are disabled?: yes

**Comment by gjsjohnmurray** [comment]
Maybe #174956

**Comment by roblourens** [comment]
Likely that issue, please try it out in our Insiders build or wait for the stable release next week @sentend
