### ISSUE TITLE
Consider to have a separate log channel for `SemanticTokensProviderStyling`

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#181174]
I found out that the logging is quite spammy when running with `--verbose`, each time you change an editor.

<img width="679" alt="image" src="https://user-images.githubusercontent.com/900690/235287635-db01e0e1-118f-4c17-9322-ff9514e796e5.png">

//cc @sandy081

**Comment by aeschli** [comment]
I created a separate logger with #181239 

What's not so nice is that this adds to the list of available loggers:
![image](https://user-images.githubusercontent.com/6461412/235445544-a042241f-30fd-4b46-8583-384b8f6afb5a.png)

When we add too many of there, this becomes difficult to handle.
@sandy081 What do you think? Is this the way to go?

Alternative would be to improve filtering on the output view.

**Comment by aeschli** [comment]
We discussed this in the team and we concluded that we should avoid too many separate loggers. It would be better if we had a better filtering story.

**Comment by bpasero** [comment]
This still kills me:

<img width="1450" alt="image" src="https://github.com/microsoft/vscode/assets/900690/1fe11e64-58be-45bf-a274-a832b0376761">

And makes every reading of a users log file a pain.
