### ISSUE TITLE
Cloud Changes hangs on exit/window close when not enabled

### ISSUE THREAD

**Issue by skamansam** [microsoft/vscode#181159]
Type: <b>Bug</b>

1. Sign in to preferences sync on two different computers using the same profile, via github.
2. enable cloud preference sync via github and sync the two.
3. work on a project on computer no.1 and enable cloud changes.
4. keep cloud changes off on computer no.2 and work on a different project.
5. close vscode on computer no.2

### Actual results:
The window hangs with a popup that says:
```
Closing the window is taking a bit longer...
The following operations are still running:
- Storing current working changes...
```
If you have previously sign in to store changes and turned them off for that project, nothing else happens, it just hangs. If you have not signed in to cloud changes, the command bar will popup and ask you to sign in to microsoft or github, but you can't access it due to the popup dialog above.

### Expected Results:
the window closes without any notifications, popups, or any other interaction.

VS Code version: Code - Insiders 1.78.0-insider (e410e7c66e7ce5c6bc31f73150d66857804a0ee9, 2023-04-28T12:24:36.251Z)
OS version: Linux x64 6.2.12-703.inttf.fc37.x86_64
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 3096)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|2, 4, 5|
|Memory (System)|15.46GB (4.87GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|gnome-xorg|
|XDG_CURRENT_DESKTOP|GNOME|
|XDG_SESSION_DESKTOP|gnome-xorg|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (60)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|3.0.2
Bookmarks|ale|13.3.1
vulgocode-color-theme|ale|0.6.12
vscode-color|ans|0.4.5
material-icons|Arc|0.2.0
atlascode|atl|3.0.3
vue-jsdoc|bej|0.0.2
emojisense|bie|0.9.1
vscode-toggle-quotes|Bri|0.3.6
gitignore|cod|0.9.0
vue-peek|dar|1.0.2
vscode-quick-select|dba|0.2.9
css-flexbox-cheatsheet|dzh|3.3.2
gitlens|eam|13.5.0
EditorConfig|Edi|0.16.4
prettier-vscode|esb|9.12.0
vscode-diff|fab|1.4.2
auto-close-tag|for|0.5.14
auto-rename-tag|for|0.1.10
copilot|Git|1.84.51
copilot-labs|Git|0.12.791
todo-tree|Gru|0.0.226
rest-client|hum|0.25.1
vscode-typescript-jsdoctag-completions|jef|1.1.2
story-explorer|jos|0.11.2
vscode-insertdatestring|jsy|2.3.1
auto-comment-blocks|kev|1.0.1
vscode-codemetrics|kis|1.26.1
better-package-json|ldd|0.2.1
blockman|leo|1.7.2
materialdesignicons-intellisense|luk|4.1.0
vue-storybook-snippets|Meg|0.0.7
dotenv|mik|1.0.1
file-downloader|min|1.0.12
remote-server|ms-|1.1.0
test-adapter-converter|ms-|0.1.7
vsliveshare|ms-|1.0.5864
vscode-vue2-snippets|Nic|1.3.2
indent-rainbow|ode|8.3.1
material-icon-theme|PKi|4.26.0
sqlite-viewer|qwt|0.2.4
vscode-xml|red|0.25.2023041804
vscode-yaml|red|1.12.2
redshred-pack|red|0.0.1
vscode-sort-json|ric|1.20.0
partial-diff|ryu|1.4.3
gitmoji-vscode|sea|1.2.2
vscode-stable-sort|sgr|1.2.2
slim|sia|0.1.2
code-spell-checker|str|2.20.4
vscode-json-stable-stringify|Tra|1.2.1
errorlens|use|3.10.1
intellicode-api-usage-examples|Vis|0.2.7
vscodeintellicode|Vis|1.2.30
vscode-conventional-commits|viv|1.25.0
rainbow-tags|vol|0.4.1
volar|Vue|1.6.1
vscode-wakatime|Wak|24.0.10
vscode-import-cost|wix|3.3.0
html-css-class-completion|Zig|1.20.0

</details>

**Comment by joyceerhl** [comment]
Workaround: set `'workbench.experimental.cloudChanges.autoStore': 'off'`
