### ISSUE TITLE
Share the .vscode directory on a USB or Drive.

### ISSUE THREAD

**Issue by longtomjr** [Microsoft/vscode#18115]
Good day all

Is there a way to make VSCode work from a different .vscode directory than the default one. I know that there are extensions that can do this, but I was just wondering if there is a way to change the path to .vscode directory.

**Comment by CoenraadS** [comment]
https://github.com/Microsoft/vscode/issues/329#issuecomment-260745649

**Comment by longtomjr** [comment]
I am talking about the .vscode directory in your home or user folder. This is the directory that contains your extensions and global settings. I will go through the issue you linked and there might be a way for me to do this.

I have two intended uses for this: I want to share my global settings aswell as my extentions on a USB to be able to work with VSCode on my laptop and desktop with the same setting ect. 

The other use I have in mind is to save my config and setting on my desktop PC where I run a dual linux/windows boot. I sometimes work in windows (when coding in Unity and for other tests), and sometimes in linux, and I use VSCode on both.

**Comment by longtomjr** [comment]
I have a couple of ideas for solving this, but nothing clear cut and easy.

Currently I have a solution, split into two configurable options:

- I am thinking of having an option in the global settings that will enable you to specify a custom settings file (path) to append to the current one. 
- The second option could enable the user to set a custom path for the extensions folder.

**Comment by sandy081** [comment]
I am making this dup of #329 since this looks similar to it. I would suggest to provide your ideas/opinions over there.
