### ISSUE TITLE
Create a settings.json variable for globalStoragePath

### ISSUE THREAD

**Issue by sam-f0** [microsoft/vscode#181134]
I am a user of an extension for CircuitPython https://marketplace.visualstudio.com/items?itemName=joedevivo.vscode-circuitpython for a multi contributor project.

It has a handy feature where it downloads the CircuitPython release bundles, and stores them in its globalStoragePath, and then adds the path to your python.analysis.extraPaths automatically. Unfortunately it adds the absolute path, so when you are collaborating on a repository which uses this extension you end up trading hardcoded paths in the workspace settings.json

```
    "python.analysis.extraPaths": [
        "c:\\Users\\MyUser\\.vscode\\extensions\\joedevivo.vscode-circuitpython-0.1.20-win32-x64\\boards\\0x239A\\0x811E",
        "c:\\Users\\MyUser\\.vscode\\extensions\\joedevivo.vscode-circuitpython-0.1.20-win32-x64\\stubs",
        "c:\\Users\\MyUser\\AppData\\Roaming\\Code\\User\\globalStorage\\joedevivo.vscode-circuitpython\\bundle\\20230428\\adafruit-circuitpython-bundle-py-20230428\\lib"
    ]
```

Separately to this feature request for VS Code, I would like to submit a PR to the extension changing it to use "${extensionInstallFolder:joedevivo.vscode-circuitpython}" for definitions stored in the extension install folder, however since it uses globalStoragePath for some Python library assets, these paths would still need to be added by the extension by absolute path. So I propose the addition of a ${globalStoragePath} or ${extensionGlobalStoragePath:<extension>} variable for use in settings.json, so I could change the extension to instead insert

```
    "python.analysis.extraPaths": [
        "${extensionInstallFolder:joedevivo.vscode-circuitpython}/boards/0x239A/0x811E",
        "${extensionInstallFolder:joedevivo.vscode-circuitpython}/stubs",
        "${globalStoragePath}/joedevivo.vscode-circuitpython/bundle/20230428/adafruit-circuitpython-bundle-py-20230428/lib"
    ]
```

which is much more appropriate to check into my repository settings.json

**Comment by DonJayamanne** [comment]
Duplicate of https://github.com/microsoft/vscode/issues/2809
