### ISSUE TITLE
No Git support when using a Dev Container with Alpine Linux

### ISSUE THREAD

**Issue by gcobr** [microsoft/vscode#181299]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 
Version: 1.77.3 (Universal)
Commit: 704ed70d4fd1c6bd6342c436f1ede30d1cff4710
Date: 2023-04-12T09:19:37.325Z
Electron: 19.1.11
Chromium: 102.0.5005.196
Node.js: 16.14.2
V8: 10.2.154.26-electron.0
OS: Darwin arm64 22.3.0
Sandboxed: No

- OS Version: 
➜  ~ sw_vers
ProductName:		macOS
ProductVersion:		13.2.1
BuildVersion:		22D68

Steps to Reproduce:

1. Create a Dev Container with any Alpine Linux image that does not have Git pre-installed.

The Source Control tab does not work when we use a Dev Container with Alpine Linux without Git pre-installed.
In my view, it should always be using Git from the host, not from the container.

See the screenshot:

![no-git-alpine-dev-container](https://user-images.githubusercontent.com/1643413/235581806-96881608-30d2-4f3b-943f-6ba800f850c5.jpg)

**Comment by lszomoru** [comment]
@gcobr , thanks for filing this issue. The built-in extensions that provide git functionality (vscode.git-base, vscode.git) are both workspace extensions which means that they will always be installed and run on the remote extension host. While you can control where an extension is installed using the `remote.extensionKind` setting, running these extensions on the host is not a supported scenario. As of right now, we have no plans for supporting running the git extensions on the host machine.
