### ISSUE TITLE
Featured extensions tiles need styling tune up 

### ISSUE THREAD

**Issue by daviddossett** [microsoft/vscode#181253]
These look pretty rough and could use some love:

<img width="568" alt="CleanShot 2023-05-01 at 08 42 15@2x" src="https://user-images.githubusercontent.com/25163139/235480299-56e613ab-80f8-4030-8c14-a6143e2cf6dd.png">

**Comment by bhavyaus** [comment]
Featured extensions no longer show up on the welcome page/.
