### ISSUE TITLE
The "return to top" icon blocks the extension's readme text

### ISSUE THREAD

**Issue by Justin-Marks** [microsoft/vscode#181207]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version:  1.77.3
- OS Version: Ubuntu 22.04.2 LTS

Steps to Reproduce:

1. View an extension's readme and scroll to the bottom of it.
2. If the final line of text is long and the body is narrow, the text is obscured by the "return to top" icon.
3. You can't scroll further down to see the text.

Adding some padding to the bottom would be one way to fix it.

![Screenshot (14)](https://user-images.githubusercontent.com/10189008/235337338-b5fc2a09-6d78-471e-89c9-dd9279cacccf.png)

**Comment by Saarthak09** [comment]
Hi @mjbvz I am willing to work on this, can I take a shot at this as my first good first issue? Thanks.

**Comment by mjbvz** [comment]
Sure

**Comment by tarun7singh** [comment]
@mjbvz If its still up for grabs i can pick it up.
I was able to find which code needs tweaking.

**Comment by antonioprudenzano** [comment]
Actually you can't put just some bottom padding, if the final text is longer the issue will persist.

**Comment by Justin-Marks** [comment]
I've also noticed the icon changed recently in 1.78. So whatever the best solution is, it should not depend on the size of the current icon.

**Comment by Justin-Marks** [comment]
@antonioprudenzano Maybe we can just put the icon as the last element of the container and use `position: sticky`, and give the container an id and link the icon back to the container.

**Comment by antonioprudenzano** [comment]
With this fix the icon position changes based on the text height, i don't know if this is ok for the mantainers.

**Comment by AKBuggy** [comment]
May I also try, I am willing to work on this.
