### ISSUE TITLE
Command palette: Remember the last command

### ISSUE THREAD

**Issue by cesaraaron** [Microsoft/vscode#18124]
I find myself very often writing the same command time after time persistently, so I think it would be cool if the command palette remember the last thing you wrote and so you only need to hit enter _instead of writing all again._

That would be very helpful.

**Comment by bpasero** [comment]
@cesaraaron I remember this request has already been reported, can you please search for it and link it here?

**Comment by cesaraaron** [comment]
@bpasero I found #6923 and #8939 although both are regarding the quick open so nope.

If you have sublime: ctrl+shift+p type settings, hit enter, close settings, ctrl+shift+p again <- the editor remember you the last thing you wrote, the text is selected so you can either hit enter to open the same command or start writing another without deleting anything.

**Comment by bpasero** [comment]
No I think there was another one, but even I could not find it, weird.

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/17163
