### ISSUE TITLE
Add tooltip on the revert arrow in the diff editor

### ISSUE THREAD

**Issue by wjandrea** [microsoft/vscode#181225]
Could you add a tooltip for the revert arrow in the diff editor? I wasn't sure what it did when I first looked at it and had to open the developer tools to be sure.

I don't know TypeScript, but it seems to be defined here:
https://github.com/microsoft/vscode/blob/34cba75c513878d683004561c799dd5cd13f5222/src/vs/editor/browser/widget/diffEditorWidget.ts#L2750-L2754

I think the new code would look something like this:
```ts
...
    arrow.title = 'Revert change';
    return dom.$('div', {}, arrow);
}
```

**Comment by joyceerhl** [comment]
Done in https://github.com/microsoft/vscode/pull/180378

**Comment by TylerLeonhardt** [comment]
<img width="929" alt="image" src="https://user-images.githubusercontent.com/2644648/235486343-9a43bec9-62f3-4dc9-83e2-453592ae1aa1.png">
looks good!

**Comment by wjandrea** [comment]
@joyceerhl Just curious, why is it "**Click to** revert change" instead of just "Revert change"? Is it to avoid ambiguity with the breakpoint button?

**Comment by joyceerhl** [comment]
It's for consistency with our other decorations (testing, breakpoints) which also have hover messages, e.g. "click for test options"
