### ISSUE TITLE
new code window help/get started no longer shows up

### ISSUE THREAD

**Issue by anandijain** [microsoft/vscode#181264]
Type: <b>Bug</b>

when a new code window opened before a week ago or so, it would show this pane with recently opened projects/folders/workspaces. 

sometime recently it stopped showing it and i dont know how to get it back

VS Code version: Code 1.77.3 (Universal) (704ed70d4fd1c6bd6342c436f1ede30d1cff4710, 2023-04-12T09:19:37.325Z)
OS version: Darwin arm64 22.3.0
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|1, 2, 2|
|Memory (System)|16.00GB (0.30GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
copilot|Git|1.84.51
language-julia|jul|1.45.1
remote-ssh|ms-|0.100.0
remote-ssh-edit|ms-|0.84.0
atom-keybindings|ms-|3.3.0
remote-explorer|ms-|0.4.0
remote-repositories|ms-|0.32.0
vscode-serial-monitor|ms-|0.9.0
vscode-xml|red|0.25.0
vscode-yaml|red|1.12.2
rust-analyzer|rus|0.3.1498

</details>

**Comment by gjsjohnmurray** [comment]
The setting `workbench.startupEditor` is relevant.

**Comment by anandijain** [comment]
thanks!!
