### ISSUE TITLE
alt+click for mutiple cursor not working

### ISSUE THREAD

**Issue by burhankhanzada** [microsoft/vscode#181229]
Type: <b>Bug</b>

I have checked all my mac os shortcuts, vscode code default shortcuts and user shortcuts there is nothing overridden also when i toggle the option in the setting to use cmd+clcik instead of alt+click that's working but i want the default alt+click coz then ctrl+click not working to go definitions

VS Code version: Code 1.77.3 (704ed70d4fd1c6bd6342c436f1ede30d1cff4710, 2023-04-12T09:41:48.638Z)
OS version: Darwin arm64 22.4.0
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|1, 1, 2|
|Memory (System)|8.00GB (0.09GB free)|
|Process Argv|--crash-reporter-id 90337fad-b50c-4440-a139-99b5bc321ba9|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (103)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|3.0.2
vscode-flutter-helper|aks|0.2.5
TabOut|alb|0.2.2
flutter-snippets|ale|3.0.0
toggle-excluded-files|amo|2.0.0
vscode-symlink|anb|0.0.3
astro-vscode|ast|0.28.2
jsoncrack-vscode|Ayk|1.0.8
vscode-custom-css|be5|7.1.0
shell-syntax|bma|1.0.5
better-toml|bun|0.3.2
npm-intellisense|chr|1.4.4
path-intellisense|chr|2.8.4
regex|chr|0.4.0
doxdocgen|csc|1.4.0
dscodegpt|Dan|2.1.5
dart-code|Dar|3.62.0
flutter|Dar|3.62.0
vscode-markdownlint|Dav|0.49.0
vscode-quick-select|dba|0.2.9
chmod|dle|1.1.1
binary-plist|dni|0.11.0
dotfiles-syntax-highlighting|dot|0.1.0
xml|Dot|2.5.1
gitlens|eam|13.5.0
vscode-flutter-riverpod-helper|evi|0.1.10
bloc|Fel|6.6.3
shell-format|fox|7.2.5
copywidget|Fus|0.0.3
get-snippets|get|4.3.0
vscode-pull-request-github|Git|0.62.0
gitlab-workflow|Git|3.62.0
vscode-select-by-indent|hab|0.3.3
codesnap-plus|hui|1.4.1
dart-data-class-generator|hzg|0.5.4
reg|ion|1.1.0
vscode-plist|ivh|0.1.3
flutter-preview|jam|0.0.9
better-cpp-syntax|jef|1.17.2
better-prolog-syntax|jef|0.3.2
better-shellscript-syntax|jef|1.6.1
bats|jet|0.1.9
vscode-todo-highlight|jgc|2.0.8
vscode-gnupg-tool|JHe|1.3.9
vscode-peacock|joh|4.2.2
vsc-python-indent|Kev|1.18.0
vscode-codemetrics|kis|1.26.1
vscode-gutter-preview|kis|0.30.0
git-tree-compare|let|1.14.0
vs-color-picker|lih|1.0.0
inifmt|lkr|0.1.5
bash-ide-vscode|mad|1.36.0
flutter-tree|mar|1.0.0
clear-view-indent|Mar|0.0.7
flutter-snippets|Mar|1.0.5
rainbow-csv|mec|3.7.0
git-graph|mhu|1.30.0
dotenv|mik|1.0.1
dart-barrel-file-generator|miq|6.1.1
revealfileinfolder|Mol|0.0.3
vscode-dotnet-runtime|ms-|1.6.0
black-formatter|ms-|2023.2.0
isort|ms-|2022.8.0
python|ms-|2023.6.1
vscode-pylance|ms-|2023.4.40
jupyter|ms-|2023.3.1201040234
jupyter-keymap|ms-|1.1.0
jupyter-renderers|ms-|1.0.15
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-slideshow|ms-|0.1.5
remote-ssh|ms-|0.100.0
remote-wsl|ms-|0.77.0
cpptools|ms-|1.14.5
cpptools-extension-pack|ms-|1.3.0
powershell|ms-|2023.3.3
remote-explorer|ms-|0.4.0
vscode-serial-monitor|ms-|0.9.0
awesome-flutter-snippets|Nas|4.0.1
vscode-json-editor|nic|0.3.0
indent-rainbow|ode|8.3.1
dartgettersetter|Pet|1.0.2
vscode-versionlens|pfl|1.5.0
material-icon-theme|PKi|4.27.0
quicktype|qui|12.0.46
vscode-thunder-client|ran|2.6.2
prolog|reb|0.0.4
vscode-xml|red|0.25.0
vscode-yaml|red|1.12.2
schemastore|rem|1.0.69
LiveServer|rit|5.7.9
flutter-riverpod-snippets|rob|1.2.2
shebang-snippets|rpi|0.1.4
prettier-vscode|Sim|2.0.7
vscode-stripe|str|2.0.14
pdf|tom|1.2.2
autocomplate-shell|tru|0.1.1
errorlens|use|3.10.1
vscode-conventional-commits|viv|1.25.0
vscode-arduino|vsc|0.6.0
markdown-pdf|yza|1.4.4
markdown-all-in-one|yzh|3.5.1
flutter-provider-snippets|Zar|1.5.0
propertylist|zho|0.0.2

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscorecescf:30445987
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vscaac:30438847
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
nodejswelcome1:30587005
3biah626:30602489
pyind779:30671433
f6dab269:30613381
pythonsymbol12:30671437
a9j8j154:30646983
vsccsb:30705552
azdwalk:30721579
pythonms35:30701012
pythonfmttext:30716742

```

</details>

**Comment by gjsjohnmurray** [comment]
Please use the Start Extension Bisect command to investigate whether the problem is being caused by one of your extensions.

**Comment by burhankhanzada** [comment]
after so much try and fail i found out the problem is with the yabairc config file I was using 

> ~/.config/yabairc

```
yabai -m config mouse_modifier alt
```

removed that line and issue fixed
