### ISSUE TITLE
Unable to set Editor: Font Family to ComicMono 

### ISSUE THREAD

**Issue by br15** [microsoft/vscode#181238]
Type: <b>Bug</b>

I've installed the ComicMono font on my Windows 11 system. Rebooted the system. The font is now visible in the "Font" drop-down in other apps. However, when I added it in the VS code settings, I just get some defalt font. I can set it to the Microsoft Comic Sans MS font, but not ComicMono?

VS Code version: Code 1.77.3 (704ed70d4fd1c6bd6342c436f1ede30d1cff4710, 2023-04-12T09:16:02.548Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz (16 x 2496)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.73GB (5.13GB free)|
|Process Argv|--crash-reporter-id 4304dab2-4e3d-4072-85e4-f2014e10f446|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (17)</summary>

Extension|Author (truncated)|Version
---|---|---
masm|bli|0.0.5
npm-intellisense|chr|1.4.4
vscode-markdownlint|Dav|0.49.0
vscode-eslint|dba|2.4.0
githistory|don|0.6.20
es7-react-js-snippets|dsz|4.4.3
cloudcode|goo|1.21.5
firebase-explorer|jsa|0.3.3
csharp|ms-|1.25.4
hexeditor|ms-|1.9.11
vsliveshare|ms-|1.0.5864
env-cmd-file-syntax|Nix|0.3.0
LiveServer|rit|5.7.9
code-spell-checker|str|2.20.4
vsfire|tob|1.4.1
lorem-ipsum|Tyr|1.3.1
vscode-icons|vsc|12.4.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
vscccc:30610679
nodejswelcome1:30587005
3biah626:30602489
pyind779:30671433
f6dab269:30613381
pythonsymbol12:30671437
a9j8j154:30646983
showlangstatbar:30672706
vsctsb:30705553
azdwalk:30721579
pythonms35:30701012
pythonfmttext:30716742
pythonclientmv:30725892

```

</details>

**Comment by IllusionMH** [comment]
/needsMoreInfo

What is your `editor.fontFamily` in `settings.json`?
Are you using it as `ComicMono` or as `'Comic Mono'`? Have you tried both options?

**Comment by br15** [comment]
Hi Andrii,

I've just tried it with "Comiic Mono" instead of "ComicMono" and it now
works!

Thanks
