### ISSUE TITLE
Squigglies disappear when caret on var name

### ISSUE THREAD

**Issue by aozgaa** [Microsoft/vscode#18125]
- VSCode Version: master, commit c62d20228b84b3aa00269d63f44cab41b357700b
- OS Version: Ubuntu 16.04

(Note: does not occur with Version 1.8.1, Commit ee428b0eead68bf0fb99ab5fdc4439be227b6281)

Steps to Reproduce:

1. Make a new *.ts file
2. Copy the following contents into the file:

```ts
interface I {
    x: number;
}

class RedSquiggly implements I {

}
```
3.  Place the caret with the mouse so it touches the classname (ie: "RedSquiggly"), endpoints inclusive.
4. Observe that squiggly disappears when the classname gets "highlighted".

Images:
![squiggly_present](https://cloud.githubusercontent.com/assets/3226984/21661453/047d1386-d289-11e6-8304-08148419b3d7.png)
![squiggly_missing](https://cloud.githubusercontent.com/assets/3226984/21661454/047d1ae8-d289-11e6-81b4-881eef038a4c.png)

**Comment by jrieken** [comment]
This doesn't reproduce for me. @aozgaa Please refine you steps
