### ISSUE TITLE
TypeScript Shows "tsdk Updated" Message Even if the Settings Update Fails

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#18127]
- VSCode Version: 1.9

Steps to Reproduce:

1. Install a local version of TypeScript in a folder
2. Add an invalid `.vscode/settings.json` file (for example `{,}`)
3. Open the folder in VSCode.
4. Open a js file
5. There should  be an alert about selecting which version of TypeScript to use.
6. Select use bundled or one of the options.

**Expected**
This normally should persist the new `tsdk` setting into `.vscode/settings.json`, but since that is invalid, the setting update fails. We should show a message indicating this happened.

**Actual**
We display a message stating that the settings update succeeded. If you open `.vscode/settings.json`, you see that it in fact has not been updated

**Comment by roblourens** [comment]
Now N/A?

**Comment by mjbvz** [comment]
Yes, we should not hit this anymore since the TS extension does not write `typescript.tsdk` to the workspace settings in the new flow.
