### ISSUE TITLE
[html][css] [custom data] Reload custom data- Publish web-component.html-data.json as a extension

### ISSUE THREAD

**Issue by pswaroop611** [microsoft/vscode#181247]
I followed https://github.com/microsoft/vscode-custom-data/tree/main/samples/webcomponents for a **vscode-custom-data**, and it works like a champ. 👍 
**I needed some suggestions:**
1.  I have added the code to suggest custom HTML tags in the **web-component.html-data.json** file
2. Add the path of the above file in **.vscode/settings.json**
3. Now I want to create a VS extension using these two logics/files. So anyone who had this extension in their VS code needs to have similar functions of suggesting custom HTML tags and their attributes.

**Comment by aeschli** [comment]
There are the custom data contribution points: https://code.visualstudio.com/api/extension-guides/custom-data-extension
Is that what you are looking for?
