### ISSUE TITLE
breakpoint decoration leak

### ISSUE THREAD

**Issue by rebornix** [Microsoft/vscode#18126]
- VSCode Version: 1.9.0-Insiders
- OS Version: macOS

Steps to Reproduce:

1. Make changes to a file in a git repository
2. Set breakpoints
3. Undo the change
4. The breakpoints are no longer valid but they are not deleted somehow.

![decoration-leak](https://cloud.githubusercontent.com/assets/876920/21661579/92fe7870-d289-11e6-9b6a-1fcc9a6faed8.gif)

**Comment by isidorn** [comment]
Can you still delete them in the breakpoints pane?
If yes I acknowledge the bug but will not fix

**Comment by rebornix** [comment]
@isidorn sounds good to me.
