### ISSUE TITLE
Close parenthesis not inserted when open parenthesis entered directly to the left of a semicolon

### ISSUE THREAD

**Issue by mkeathley** [Microsoft/vscode#18120]
- VSCode Version: 1.8.1
- OS Version: Windows 10 Enterprise

Steps to Reproduce:

0. This is using JavaScript.
1. Type a semicolon.
2. Place the cursor directly to the left of the semicolon.
3. Enter an open parenthesis.

Context does not appear to matter with this.  You can reproduce this on a blank line.  Entering an open parenthesis inserts a close parenthesis as we might expect.  However if there is a semicolon to the right of the cursor, entering an open parenthesis does not result in a matching close parenthesis.  Invocation of a function does not appear to matter.

**Comment by mjbvz** [comment]
This does not seem to be JavaScript specific. I see the same behavior in other languages and with other punctuators besides `;`. For example: typing `(` before `*` or  `+` shows the same behavior.

**Comment by alexandrudima** [comment]
Currently, this is implemented with the following rule:
* if `(` is typed
* if the cursor is at the end of a line or the text after `(` is whitespace, a closing `)` is also inserted
* this is consistent with other editors e.g. Sublime

**Comment by alexandrudima** [comment]
fyi @joaomoreno

**Comment by cosmarc** [comment]
Brackets are not closed when writing ReactNative JSX neither.
Example: <Text style={>
Make sure that you type first the Text tag and after that start typing before the last ">" character.
![image](https://user-images.githubusercontent.com/15168615/34464205-4563a6ae-ee7f-11e7-9d35-262568df71e8.png)

**Comment by peterromfeldhk** [comment]
can we have a setting to always create closing par? without any smartness?
when i do any of `'"[{( i always want a closing par, and when i select something i always want it to be surrounded by it
