### ISSUE TITLE
Include interactiveEditor.editMode in settingsLayout.ts

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#181278]
> `[warning] SettingsEditor2: Settings not included in settingsLayout.ts: interactiveEditor.editMode, accessibility.verbosity.diff-editor, accessibility.verbosity.terminal`

**Comment by jrieken** [comment]
@rzhao271 can you help me understand what this means and what needs to be done

**Comment by rzhao271** [comment]
Duplicate of https://github.com/microsoft/vscode/issues/181084

**Comment by jrieken** [comment]
@rzhao271 not a dupe
