### ISSUE TITLE
"Sort Imports" support for .vue files

### ISSUE THREAD

**Issue by dshinton-qstart** [microsoft/vscode#181232]
I used to use `source.organizeImports` in `editor.codeActionsOnSave` but it deletes unused imports which can break an application. I read that [VS Code v1.57](https://code.visualstudio.com/updates/v1_57#_sort-imports-source-action) added the `source.sortImports` action for javascript and typescript files. However, this action has no effect on `.vue` files that can contain Javascript.

Please add `source.sortImports` support for `.vue` files or allow me to exclude certain files (e.g. `main.js`) from `source.organizeImports`.

Thank you!

**Comment by IllusionMH** [comment]
VS Code doesn't support `.vue` files out of the box, so you should post this request in repo of extension you are using for Vue.

**Comment by mjbvz** [comment]
Sounds like `source.sortImports` already addresses your use case though: it only sorts imports without removing unused one. You can always add that to `editor.codeActionsOnSave` and then run `organizeImports` manually when you really want to clean up and remove unused imports

**Comment by mjbvz** [comment]
> I want to sort imports in vue files, I have to use organizeImports

Please file an issue against your Vue extension to support `sortImports` too

**Comment by dshinton-qstart** [comment]
> Please file an issue against your Vue extension to support sortImports too

I already did. Since you closed this, would like me to make a new feature request that doesn't mention the Vue extension so my VS Code feature request isn't muddled together with it? I think it would be helpful to have a white/black list for the automated `organizeImports` since that would solve my problem.

**Comment by mjbvz** [comment]
Yes you can file a feature request against TypeScript for that since they provide the feature for JS and TS file: https://github.com/microsoft/TypeScript/issues/new/choose

**Comment by dshinton-qstart** [comment]
Done. Thank you!
