### ISSUE TITLE
Can't right click to see context menu on menu bar 

### ISSUE THREAD

**Issue by daviddossett** [microsoft/vscode#181340]
On vscode.dev it seems to be appearing and disappearing almost immediately.

https://user-images.githubusercontent.com/25163139/235715531-486f84b1-430e-4d2c-9ac2-2e1bea4333ea.mp4

**Comment by bpasero** [comment]
I think I fixed it, can you try again in insiders?

**Comment by daviddossett** [comment]
Works great now, thanks!
