### ISSUE TITLE
It's really really slow

### ISSUE THREAD

**Issue by jeffpatel71** [microsoft/vscode#181303]
Type: <b>Bug</b>

It's really really slow. I have a pretty decked out machine but for whatever reason it's taking ages to load. I reinstalled, cleared extension etc etc. but i've got no idea what's going on

VS Code version: Code 1.77.3 (704ed70d4fd1c6bd6342c436f1ede30d1cff4710, 2023-04-12T09:16:02.548Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|12th Gen Intel(R) Core(TM) i9-12900H (20 x 2918)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.70GB (19.48GB free)|
|Process Argv|--crash-reporter-id e358e616-8102-4686-8279-4c32375d2f16|
|Screen Reader|no|
|VM|50%|
</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2023.6.1
vscode-pylance|ms-|2023.4.40
jupyter|ms-|2023.3.1201040234
jupyter-keymap|ms-|1.1.0
jupyter-renderers|ms-|1.0.15
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-slideshow|ms-|0.1.5

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
nodejswelcome1:30587005
282f8724:30602487
pyind779:30671433
89544117:30613380
vscrpc:30673769
pythonsymbol12:30671437
a9j8j154:30646983
showlangstatbar:30730054
vsctsb:30705553
azdwalk:30721579
pythonms35:30701012
pythonfmttextcf:30716743
pythonclientmvcf:30725893
fixshowwlkth:30730052
showsbindicator:30730056

```

</details>

**Comment by jeffpatel71** [comment]
<img width="890" alt="image" src="https://user-images.githubusercontent.com/77821959/235599667-7fadb240-f6cc-4dc7-b6f4-10be063161e6.png">

<img width="1202" alt="image" src="https://user-images.githubusercontent.com/77821959/235599769-aaaa0657-d7c4-4325-a375-acdb53fe45a2.png">

**Comment by bpasero** [comment]
Do you have McAffee AntiVirus installed and running?

**Comment by jeffpatel71** [comment]
Yea.. om i found out that's the problem.... sorry

**Comment by bpasero** [comment]
Thanks, we will investigate and maybe follow up with them.
