### ISSUE TITLE
While typing in the Settings search field, font overlapping shadows in the menu bar

### ISSUE THREAD

**Issue by Syukkic** [microsoft/vscode#181336]
Does this issue occur when all extensions are disabled?: No

I haven't installed any extensions yet. Just fresh installed VS Code.

- VS Code Version: 1.77.3
- OS Version: Arch Linux

Version: 1.77.3
Commit: 704ed70d4fd1c6bd6342c436f1ede30d1cff4710
Date: 2023-04-12T09:16:52.732Z
Electron: 19.1.11
Chromium: 102.0.5005.196
Node.js: 16.14.2
V8: 10.2.154.26-electron.0
OS: Linux x64 6.2.13-arch1-1
Sandboxed: No

Steps to Reproduce:

1. Type something in settings search field
2. The font on menu bar occurs overlapping shadows
![2023-05-02_22-59](https://user-images.githubusercontent.com/39305719/235708693-5f7cb9a0-2ade-4e65-9c15-934a8bdeb834.png)
![2023-05-02_23-00](https://user-images.githubusercontent.com/39305719/235708731-eff8362d-7f33-4130-b8ba-a04ddc9bfb7d.png)

**Comment by Syukkic** [comment]
Version: 1.77.3
Commit: 704ed70d4fd1c6bd6342c436f1ede30d1cff4710
Date: 2023-04-12T09:16:52.732Z
Electron: 19.1.11
Chromium: 102.0.5005.196
Node.js: 16.14.2
V8: 10.2.154.26-electron.0
OS: Linux x64 6.2.13-arch1-1
Sandboxed: No

**Comment by rzhao271** [comment]
Hi, is the issue easily reproducible? Also, does the issue occur when you launch Code with the `--disable-gpu` flag, i.e. `code --disable-gpu`?

**Comment by Syukkic** [comment]
Thanks for your tip, I added flag `--disable-gpu` to start VS Code, and the overlapping shadows problem no longer occurs. Thank you :)
