### ISSUE TITLE
Issue with snippets

### ISSUE THREAD

**Issue by ManojPhadnis** [Microsoft/vscode#18134]
When we loan a snippet - 
1. Unnecessary backslash appears for all the "{"
2. "$" sign is lost.

- VSCode Version: Code 1.8.1 (ee428b0eead68bf0fb99ab5fdc4439be227b6281, 2016-12-19T14:49:23.350Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions:

|Extension|Author|Version|
|---|---|---|
|PDNLabAngularMaterial|PDNLabs|1.0.0|

---

Steps to Reproduce:

1.
2.

**Comment by sandy081** [comment]
@ManojPhadnis Can you please provide the snippets you are using and proper steps to reproduce.

**Comment by mjbvz** [comment]
Closing as we need more info here. 

@ManojPhadnis Please provide the information @sandy081 requested so that we can investigate.

Thanks
