### ISSUE TITLE
Add keyboard shortcuts for next and previous quick fix

### ISSUE THREAD

**Issue by balajip881** [microsoft/vscode#181324]
As a screen reader user, I  am not able to  locate the next quickfix in the file. Currently pressing ctrl +.  only works when i am on quick fix line in the file.

please provide a way to screen reader users to go to next and previous quick fix.

Solution :
we can add a view for quick fix panel and add some commands to keyboard   shortcuts. We can  use the bookmarks extention for the reference.
https://marketplace.visualstudio.com/items?itemName=alefragnani.Bookmarks

1.  Add keyboard short cuts for going to previous and next quick fix.
2. please add a view for quickfix  like bookmarksexplorer view.

please add shortcuts for previous and next quick fix ASAP if  there is  limited time.
The changes that you do in your code will significantly improve the lifes of the people in need of them.

**Comment by mjbvz** [comment]
You can use F8 to jump to the next error (which may or may not have a quick fix)

It's not possible to jump to the next quick fix because quick fixes are computed dynamically based on the cursor position
