### ISSUE TITLE
Reloading tunnel on vscode.dev fails with error handshaking session: EOF

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode#181319]
- starting the tunnel from the Code OSS, Account menu
- opening the tunnel in vscode.dev with the link given by the notification
- folder opens
 -reload browser: it no longer can show the folder. Server log shows `error handshaking session` for all client connections
```
2023-05-02 12:22:13.387 [info] [2023-05-02 12:22:13] info [tunnels::connections::relay_tunnel_host] Opened new client on channel 51

2023-05-02 12:22:13.408 [info] [2023-05-02 12:22:13] error [tunnels::connections::relay_tunnel_host] error handshaking session: EOF
```

**Comment by aeschli** [comment]
Relooad works now with fix https://github.com/microsoft/vscode/pull/181286 in the new 1.78-insiders build
There is still the log
```
error [tunnels::connections::relay_tunnel_host] error handshaking session: EOF
```
but it doesn't seem to cause that the folder can not be loaded

**Comment by j0no** [comment]
I thought it was just my machine.

**Comment by HackerDaGreat57** [comment]
Also happening to me on 1.78.2 Ubuntu 23.04 arm64

Strange thing is, this problem is not happening on my 1.79.0 Ubuntu 22.10 x64 🤔

I will try updating and see if that fixes it.

**Comment by HackerDaGreat57** [comment]
Update, restarting the code server fixed it for me. It updated the server automatically on the spot to 1.79.0 and it works now.

We'll see if this happens again. Until then I advise you all to set up a script that restarts your code server every 24 hours or so, in case you won't have physical access to the server computer for a long time. You can use tmux or something like that to preserve terminal session.

**Comment by flames** [comment]
For me the error happens all 10-15 minutes. Restarting server helps, and then again after 10-15 min.
Debian Bullseye, version 1.79.0 from stable apt-repository

**Comment by JK88-1337** [comment]
OS: Ubuntu 22.04 x64
Restarting the service temporarily solves the issue, but the error will be triggered again in half an hour.

**Comment by HackerDaGreat57** [comment]
The error does happen in my logs but I can connect to the server and work just fine, extensions enabled or not... 🤔
![image](https://github.com/microsoft/vscode/assets/70416002/0af08d0f-ab15-4e43-98b6-873d6de9817b)

**Comment by Some-random** [comment]
I'm also having this issue, it happens every now and then

**Comment by Abdulmalik-rebdi** [comment]
i am also having this same issue

**Comment by connor4312** [comment]
If you experience this issue, please open the developers tools on the page (cmd+option+i or ctrl+shift+i) and share any console errors. Thanks!

**Comment by crochereau** [comment]
Having the same issue, hope the console error can help

<img width="555" alt="Screenshot 2023-07-13 at 2 04 54 AM" src="https://github.com/microsoft/vscode/assets/44776544/67df5778-ff59-4a98-b0ee-8d27121dacd7">

**Comment by connor4312** [comment]
The "EOF" error happens due to some Dev Tunnels control flow that happens when a session is getting torn it. It doesn't directly cause any issues.
