### ISSUE TITLE
Telemetry output channel missing from Codespaces

### ISSUE THREAD

**Issue by luabud** [microsoft/vscode#181358]
Does this issue occur when all extensions are disabled?: Yes

Codespaces
Visual Studio Code - Insiders
Version: 1.78.0-insider
Commit: 657bb89984f37b810b250955570593cde0cd62eb
Date: 2023-05-02T11:17:01.989Z (10 hrs ago)
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36 Edg/112.0.1722.68

Steps to Reproduce:

1. Open a GitHub Codespace from an existing repo 
2. Run the "Developer:  Set Log Level..." command and set it to "Trace"
3. Notice there's no "Telemetry" channel there, only Extension Telemetry:

![image](https://user-images.githubusercontent.com/45497113/235790051-6fe7cb3c-1955-4ef8-b32e-952105ec8d77.png)

**Comment by sandy081** [comment]
Where do you register Telemetry logger in codespaces?

**Comment by lramos15** [comment]
> Where do you register Telemetry logger in codespaces, is it in server or on client side?

It's registered client side.

**Comment by lramos15** [comment]
https://github.com/microsoft/vscode/blob/d0ca6131bfe1936153df2f8a11f85e3790ec1f4b/src/vs/platform/telemetry/common/telemetryLogAppender.ts#L13-L47

**Comment by sandy081** [comment]
Can you please check if this code is being executed in the codespace?

**Comment by lramos15** [comment]
@sandy081 It seems to be missing from web too. I can confirm when debugging the web bits locally it is called and registered, but nothing shows up in the output channel list.

**Comment by sandy081** [comment]
> I can confirm when debugging the web bits locally it is called and registered, but nothing shows up in the output channel list.

Can you please provide me steps to enable this locally from sources?

**Comment by lramos15** [comment]
Sent instructions offline 👍

**Comment by joyceerhl** [comment]
Still not seeing the telemetry output channel in Codespaces (on desktop if it matters)

**Comment by sandy081** [comment]
Actually this is a bug in web, but I can confirm that this is working for me in both web and desktop. Wondering if you have any additional steps to repro.
