### ISSUE TITLE
The C/Cpp Language Server server crashed 5 times in the last 3 minutes. The server will not be restarted.

### ISSUE THREAD

**Issue by prasoonnaik** [Microsoft/vscode#18139]
- VSCode Version: Code 1.8.1 (ee428b0eead68bf0fb99ab5fdc4439be227b6281, 2016-12-19T14:49:23.350Z)
- OS Version: Windows_NT ia32 10.0.10586
- Extensions:

|Extension|Author|Version|
|---|---|---|
|code-gnu-global|austin|0.2.1|
|cpptools|ms-vscode|0.9.3|

---

Steps to Reproduce:

1. Install the c/c++ intellisense, complete C/C++ language support including code-editing and debugging. 
2. restart and start coding, it gives the error mentioned in the title bar.

**Comment by Litewhite** [comment]
same problem on the environment below:
- VSCode Version: Code 1.9.1 (f9d0c687ff2ea7aabd85fb9a43129117c0ecf519, 2017-02-08T23:44:55.542Z)
- OS Version: Linux x64 4.9.0-1-amd64
- Extensions:

|Extension|Author|Version|
|---|---|---|
|vscode-theme-onedark|akamud|1.1.0|
|python|donjayamanne|0.5.8|
|code-runner|formulahendry|0.6.9|
|cpptools|ms-vscode|0.10.0|
|Ruby|rebornix|0.10.4|
|java|redhat|0.0.10|
|todotasks|sandy081|0.4.0|
|shader|slevesque|0.2.2|

---

when this error comes out, the memory usage of process "~/.vscode/extensions/ms-vscode.cpptools-0.10.0/bin/Microsoft.VSCode.CPP.Extension.linux" will be increasing until all the ram run out.
