### ISSUE TITLE
Formatting HTML breaks

### ISSUE THREAD

**Issue by charlieargue** [Microsoft/vscode#18133]
- VSCode Version: Version 1.8.1 (1.8.1)
- OS Version: Mac OS Sierra 10.12.1 (16B2659)

Steps to Reproduce:

1. Right-click auto-format HTML not working 
2. Also, jsbeautify extension with wrap_attributes set to force stopped working also as of this update

Please help, thanks so much!

**Comment by charlieargue** [comment]
Hi, yes sorry.

Issue #1: So, the attached file is not auto-formatting at the table element.

[formatting-broken-at-table.html.txt](https://github.com/Microsoft/vscode/files/688861/formatting-broken-at-table.html.txt)

Issue #2: the upgrade to 1.8.1 broke the jsbeautify extension feature that was AWESOME, and I believe you guts are thinking about incorporating: wrap each HTML attribute on a new line:

<bla attrib1="ok" attrib2="ok"...

with jsbeautify's wrap_attribute set, makes vscode auto-format the above to:

<bla attrib1="ok"
         attrib2="ok"
         ...

Which is great! 

It just seems that with each upgrade to vscode, this often stops working. Should I assume it's just jsbeautify's fault?

Thanks! 

Love vscode, great product!

**Comment by charlieargue** [comment]
And here's another example that often occurs, on this version and previous:
(is it the button or #popContent that breaks it, not sure) -- but auto-format never works (native vscode autoformat), it always stays to the left, instead of indenting right:

```
<template #popContent>Hello, <b>{{name}}</b>!</template>
<button type="button" class="btn btn-secondary" [ngbPopover]="popContent" popoverTitle="Fancy content">
  I've got markup and bindings in my popover!
</button>
```

**Comment by aeschli** [comment]
issue 1 is #17849, issue 2 is #2204.
