### ISSUE TITLE
Can't disable horizontal brace auto placement.

### ISSUE THREAD

**Issue by Scatterblak** [microsoft/vscode#181386]
Type: <b>Bug</b>

In a new file, create something like this:

`for(x=1;x<=rs_IF_Staging.recordCount;x++){`

...then, hit 'Enter' a couple of times, and then tab out 3 or 4 times, and enter the closing brace:

                    `}`

...VS Code immediately snaps it to the same column as the initial for() statement. I need to be able to disable this behavior, and place the brace anywhere on the line.  Looked everywhere, Googled for hours, changed tons of settings, can't find a way to get it done.

VS Code version: Code 1.77.3 (704ed70d4fd1c6bd6342c436f1ede30d1cff4710, 2023-04-12T09:16:02.548Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i9-11900K @ 3.50GHz (16 x 3504)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.77GB (20.09GB free)|
|Process Argv|Private|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|2.4.0
vscode-cfml|Kam|0.5.4
data-workspace-vscode|ms-|0.4.0
mssql|ms-|1.18.0
sql-bindings-vscode|ms-|0.3.0
sql-database-projects-vscode|ms-|0.21.0
sftp|Nat|1.16.1
rust-analyzer|rus|0.3.1498
vscode-counter|uct|3.2.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
nodejswelcome1cf:30587006
3biah626:30602489
pyind779:30671433
f6dab269:30613381
pythonsymbol12:30671437
a9j8j154:30646983
6233i204:30730053
vsccsb:30705552
azdwalk:30721579
pythonms35:30701012
pythonfmttextcf:30716743
fixshowwlkth:30730052
hidesbindicator:30730055

```

</details>

**Comment by Scatterblak** [comment]
Please note: can I humbly ask not to hear all the reasons why this is desired behavior? We've got our reasons in-house to need this disabled, and it's nothing to do with proper indentation, etc.

**Comment by gjsjohnmurray** [comment]
Maybe this?

```
	"editor.language.brackets": [],
```

**Comment by MrAndersen1** [comment]
While a bit more cumbersome you could override the keybinding to something like this
```
{
    "key": "alt+shift+9",
    "command": "editor.action.insertSnippet",
    "when": "editorTextFocus",
    "args": {
        "snippet": "}"
    }
}
```
It won't remove the indentation then.

**Comment by hediet** [comment]
@gjsjohnmurray's suggestion should work.

**Comment by MrAndersen1** [comment]
> @gjsjohnmurray's suggestion should work.

Yet it doesn't unfortunately, but I do agree it sounds like it should work.

**Comment by r3m0t** [comment]
What about `editor.formatOnType`?

If setting it to `false` works, but the command `Format Document` causes the whitespace to be removed, then the formatting extension you're using is at fault. What language is your code? (shown in the bottom right in "Editor Language")

**Comment by MrAndersen1** [comment]
> What about `editor.formatOnType`?
> 
> If setting it to `false` works, but the command `Format Document` causes the whitespace to be removed, then the formatting extension you're using is at fault. What language is your code? (shown in the bottom right in "Editor Language")

Not sure what language the author is using but I just tried typescript. I also tried opening a plain text file with the same issue. No settings I've found affects the behaviour (in typescript, haven't gone through them all for plaintext).

I'm starting to think that either my editor is malfunctioning or no one is testing their proposed solutions :)

**Comment by r3m0t** [comment]
It worked for me, but I only pressed enter once, maybe that's my error.

**Comment by MrAndersen1** [comment]
Actually editor.language.brackets have begun working for me now, not sure why it didn't before but I did test it several times without success. I have updated the editor since then though so it could have been fixed or there were some shenanigans going on locally which a reboot resolved perhaps.

**Comment by MrAndersen1** [comment]
> It worked for me, but I only pressed enter once, maybe that's my error.

That's good to know, getting feedback that it works for you makes it easier to try and find the issue.

**Comment by aiday-mar** [comment]
Indeed as was mentioned above, setting the following:

`"editor.language.brackets": []`

should work.

Ideally, setting `editor.autoIndent: 'none'` should also prevent indentation. It seems however to cause indentation still if the brackets array above is non empty. This issue will be tracked here: https://github.com/microsoft/vscode/issues/111265. In the meantime, this issue will be closed.
