### ISSUE TITLE
Unify markdown paste + drag n drop experiences

### ISSUE THREAD

**Issue by Yoyokrazy** [microsoft/vscode#181354]
Currently when pasting images into a markdown editor, the default behavior is to paste as a markdown image link with a path to the image. If the asset is a screenshot, then a workspace file is created with the paste.

I was thinking that giving paste functionality the same UX as the new drag n drop provider could be useful for people creating different paste handlers. This could be especially useful within notebooks, as currently the default paste behavior is to paste as an attachment, even if the file is already present and being pasted from the workspace itself.

Notebook users would likely appreciate a UX similar to drag n drop, allowing them to paste screenshots or files into notebooks as either the more portable attachment format, or as an image link pointing to the workspace. This would also simplify the reuse of images as currently you would have to hunt down the `![](attachment:filename)` and then paste that elsewhere to duplicate images. 
cc: @rebornix

**Comment by mjbvz** [comment]
I believe this was already added by 11ca8d75a13a3940b197696786cf44ae6c2cbd37

It adds a widget that lets you change how content is pasted if there are multiple potential options. You can try it out in OSS
