### ISSUE TITLE
 TypeError: Cannot read property 'getWordAtPosition' of null

### ISSUE THREAD

**Issue by vscodeerrors** [Microsoft/vscode#1813]
Issue Id: <b>354cba91-9b6e-d4a7-3588-6549890f3667</b><br /><br />*Versions* <br />- 0.10.3<br />-  a80232bbcfe8a5cdad1ebc98638673d9dcb02458<br />-  df352367df2efcfa9d602d471e4e2f42140a0f05<br />*Stack* <br />TypeError: Cannot read property 'getWordAtPosition' of null<br />[/vs/editor/common/modes/abstractModeWorker.ts#L246:26 (AbstractModeWorker.findOccurrences)](https://github.com/microsoft/vscode/blob/783ecf841a2b21edca6d86853670cae89b4c244f/src/vs/editor/common/modes/abstractModeWorker.ts#L246:26 (AbstractModeWorker.findOccurrences))<br />[/vs/editor/common/modes/abstractMode.ts#L199:31 (AbstractMode.findOccurrences)](https://github.com/microsoft/vscode/blob/783ecf841a2b21edca6d86853670cae89b4c244f/src/vs/editor/common/modes/abstractMode.ts#L199:31 (AbstractMode.findOccurrences))<br />[vs/base/common/worker/vs/base/common/winjs.base.raw.js#L1826:0 (onComplete)](https://github.com/microsoft/vscode/blob/783ecf841a2b21edca6d86853670cae89b4c244f/srcvs/base/common/worker/vs/base/common/winjs.base.raw.js#L1826:0 (onComplete))<br />[/vs/editor/common/modes/abstractMode.ts#L131:35 (AbstractMode._worker)](https://github.com/microsoft/vscode/blob/783ecf841a2b21edca6d86853670cae89b4c244f/src/vs/editor/common/modes/abstractMode.ts#L131:35 (AbstractMode._worker))<br />[/vs/editor/common/modes/abstractMode.ts#L199:14 (AbstractMode.findOccurrences)](https://github.com/microsoft/vscode/blob/783ecf841a2b21edca6d86853670cae89b4c244f/src/vs/editor/common/modes/abstractMode.ts#L199:14 (AbstractMode.findOccurrences))<br />[/vs/platform/thread/common/workerThreadService.ts#L89:16 (WorkerThreadService.OneWorker)](https://github.com/microsoft/vscode/blob/783ecf841a2b21edca6d86853670cae89b4c244f/src/vs/platform/thread/common/workerThreadService.ts#L89:16 (WorkerThreadService.OneWorker))<br />[/vs/platform/thread/common/threadService.ts#L58:34 (OneWorker)](https://github.com/microsoft/vscode/blob/783ecf841a2b21edca6d86853670cae89b4c244f/src/vs/platform/thread/common/threadService.ts#L58:34 (OneWorker))<br />[/vs/platform/thread/common/workerThreadService.ts#L51:37 (WorkerThreadService._handleRequest)](https://github.com/microsoft/vscode/blob/783ecf841a2b21edca6d86853670cae89b4c244f/src/vs/platform/thread/common/workerThreadService.ts#L51:37 (WorkerThreadService._handleRequest))<br />[/vs/platform/thread/common/workerThreadService.ts#L57:21 (WorkerThreadService.dispatch)](https://github.com/microsoft/vscode/blob/783ecf841a2b21edca6d86853670cae89b4c244f/src/vs/platform/thread/common/workerThreadService.ts#L57:21 (WorkerThreadService.dispatch))<br />[/vs/editor/common/worker/editorWorkerServer.ts#L154:21 (EditorWorkerServer.request)](https://github.com/microsoft/vscode/blob/783ecf841a2b21edca6d86853670cae89b4c244f/src/vs/editor/common/worker/editorWorkerServer.ts#L154:21 (EditorWorkerServer.request))<br />

**Comment by alexandrudima** [comment]
The code is now deleted
