### ISSUE TITLE
"Real" Find in files (in any folder on disk)

### ISSUE THREAD

**Issue by RalfJahns** [microsoft/vscode#181380]
Please add "Find in files" like Visual Studio has https://learn.microsoft.com/en-us/visualstudio/ide/find-in-files?view=vs-2022 or every other Editor / IDE I have ever used (Notepad++, geany, CodeLite IDE, embarcadero C++ builder, Visual Studio, Qt Creator,  ...).

This missing feature is holding me back from using Visual Studio Code. **I work on a project, that is part of a (hundreds of times) bigger codebase.** Usually I only have my project / folder open in the IDE but sometimes I must search the whole codebase. Because of this, this feature is a must have for me.

**Comment by andreamah** [comment]
Unfortunately, we only have searching files within the workspace, as accessing user data outside of the workspace is out of scope of the feature.
