### ISSUE TITLE
Select text in integrated terminal with keyboard and not using the mouse

### ISSUE THREAD

**Issue by erikgrahn13** [microsoft/vscode#181390]
Being able to to use similar features as "mark mode" (Windows terminal) or "copy mode" (tmux) to be able to select text in the integrated terminal without the need of using the mouse. For example, "mark mode" uses ctrl+shift+m to enter the mode where you will be able to navigate the terminal with keyboard and select text to yank/copy. tmux for example uses ctrl+b [ to enter selection mode.

**Comment by meganrogge** [comment]
You can now do this by running `Terminal: focus accessible buffer` and then use editor shortcuts to copy parts of the text via keyboard
