### ISSUE TITLE
Select a Profile Proposal Before Opening the Software.

### ISSUE THREAD

**Issue by xxxxj-up** [microsoft/vscode#181314]
You can select a profile before opening VScode.
For example,
`code . profile=c++`
or Right-click the taskbar icon to select.

**Comment by sandy081** [comment]
> code . profile=c++

Yes you can do that `code . --profile <name>`

**Comment by xxxxj-up** [comment]
ok...Perhaps I didn't speak clearly enough. There is another situation. I need to be able to open a new tab here
![image](https://github.com/microsoft/vscode/assets/61113746/dc25b9c4-18d8-4031-bb36-f4e93cb1ce83)
