### ISSUE TITLE
Keyboard shortcut for View > Editor Layout > Single 

### ISSUE THREAD

**Issue by userrand** [microsoft/vscode#181337]
Thank you for this very nice editor.

I would like a keyboard shortcut or command palette option to undo the split editor via View > Editor Layout > Single

**Comment by DonJayamanne** [comment]
Thanks @ArturoDent that should work
Closing as the solution provided above should address this issue.

**Comment by userrand** [comment]
> View: Single Column Editor Layout

Thank you indeed that seems to work.
