### ISSUE TITLE
PROBLEMS tab still shows problems.

### ISSUE THREAD

**Issue by nellenium** [microsoft/vscode#181321]
Type: <b>Bug</b>

The "PROBLEMS" tab still shows problems after closing out the file I was working on. I would think that when the file was closed the tab would refresh and there would be no problems showing because there is no file open. 

VS Code version: Code 1.77.3 (704ed70d4fd1c6bd6342c436f1ede30d1cff4710, 2023-04-12T09:16:02.548Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8600 CPU @ 3.10GHz (6 x 3096)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.83GB (7.38GB free)|
|Process Argv|--crash-reporter-id c464a395-b17a-4805-a83e-77e80f2d2338|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
regionfolder|map|1.0.22
data-workspace-vscode|ms-|0.4.0
mssql|ms-|1.18.0
sql-bindings-vscode|ms-|0.3.0
sql-database-projects-vscode|ms-|0.21.0
notepadplusplus-keybindings|ms-|1.0.7
powershell|ms-|2023.3.3

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
nodejswelcome1cf:30587006
3biah626:30602489
pyind779:30671433
89544117:30613380
pythonsymbol12:30671437
6233i204:30672705
azdwalk:30721579
pythonms35:30701012
19089226:30706075
pythonfmttextcf:30716743

```

</details>

**Comment by sandy081** [comment]
Extension which created these problems is supported to handle that. Please file the issue against the extension creating the problems.
