### ISSUE TITLE
Focus Terminal Instances when switching between them

### ISSUE THREAD

**Issue by leander-hass** [microsoft/vscode#181316]
When you have multiple instances of terminals running and you switch between them, the focus should switch automatically to the selected terminal instance so you could start typing.

**Comment by meganrogge** [comment]
That's what happens AFAIK, pls include a gif with screen cast mode on if you're seeing otherwise

**Comment by leander-hass** [comment]
![Bildschirmaufnahme-2023-05-02-um-19 09 39](https://user-images.githubusercontent.com/81513805/235736887-fdb9602a-1d14-4915-b53b-92650e81e258.gif)

hope this works

**Comment by leander-hass** [comment]
I just noticed you need to double click the Instance, then it focuses. Makes sense to me.

I'm closing this issue. Thanks.

**Comment by meganrogge** [comment]
You can change that with `terminal.integrated.tabs.focusMode` if you want to

**Comment by leander-hass** [comment]
OK, that's even more awesome, thanks!
