### ISSUE TITLE
cs50

### ISSUE THREAD

**Issue by TALYD13** [microsoft/vscode#181368]
ADD ISSUE DESCRIPTION HERE

Version: 1.77.3
Commit: 704ed70d4fd1c6bd6342c436f1ede30d1cff4710
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/112.0
Embedder: codespaces

**Comment by aeschli** [comment]
Closing as incomplete.

If you want to report an issue against VS Code, please add more details and steps for us to reproduce 
For CS50 issues, please report to the CS50 support
