### ISSUE TITLE
Built in Concurrency

### ISSUE THREAD

**Issue by bickhamr** [microsoft/vscode#181327]
The Concurrency settings for the "For Each" loop no longer shows up when you open in Designer  in VS Code

**Comment by roblourens** [comment]
Sorry, no idea what you are referring to, can you include more details or a screenshot

**Comment by bickhamr** [comment]
The sscreenshot below is from the settings of the "for each" action from the portal, you can see the concurrency settings option;

***@***.***

The screenshot below is from a workflow in VS Code, the "For each" action, and you do not see the concurrency option, this is a problem;

***@***.***

**Comment by roblourens** [comment]
There is no screenshot, you have to upload attachments through github.com

**Comment by bickhamr** [comment]
Rather than getting any help fro  Premier Support, I keep getting demands. Is it too involved for you to google concurrency settings or create a "For Each" loop in a workflow, go to the settings for the action and see the concurrency setting option. In addition, the List Folders action for the Sharepoint Connector does not work correctly, it does not allow you to browse through folders you have access to in Sharepoint Online. There are many other things wrong with the last release of VS Code, this should not be news.

**Comment by roblourens** [comment]
It sounds like you are having an issue with an extension. VS Code doesn't have any builtin support for Sharepoint and I don't know what you are referring to by "workflow" or "concurrency settings"

**Comment by bickhamr** [comment]
VS Code is a platform in which you can create Logic App "Workflows" locally, the term "Workflow" refers to Logic App. The Built-in connectors, the actions, the Sharepoint connections, all of that is a part of Logic App, not VS Code but VS Code is recommended as a tool to create Logic App Workflows rather than creating the Workflows on the portal. Yes, Logic App's works in VS Code like so much else, via extensions. So, technically I am having a problem with the VS Code Logic App extensions.

Sense you amazingly keep claiming to not know what I am talking about regarding "concurrency", here is a link dealing with "Concurrency Control" in Logic App, https://yourazurecoach.com/2017/08/29/logic-apps-concurrency-control/ . Here is a link dealing with "Workflows" in Logic App, https://docs.dapr.io/developing-applications/integrations/azure/workflows/.

Perhaps in the ticket I did not mention that I am using VS Code locally to produce Azure Logic App Workflows that then connect to Sharepoint and other platforms using actions built into Connectors, actions that in some cases contain "Concurrency settings" as an option. After four days of dropped appointments and the seeming inability for you all to understand without it being explicitly spelled out that Logic App "Workflows" with Concurrency Controls and connections to Sharepoint can be built locally using Extensions in VS Code, I have received zero support concerning getting VS Code and specifically, its Logic App extensions working correctly.

The VS Code "Triage Bot" was able to tell me what I already know, which is that Logic App Extensions are not working correctly in VS Code. Before another email comes asking me whether I have checked for Updates of the extensions or updates of VS Code, I check every morning, several times during the day.  My point here is that no news about clear serious problems has been explicitly put out by Microsoft, no explicit information about when and if repairs are forthcoming, about whether we end users should uninstall and reinstall the software, no acknowledgement by Microsoft that there is a problem except through Microsoft consultants we are working with. My point, is there seems to be no actual support on this problem.

**Comment by bickhamr** [comment]
Adding Incident Manager, @Karen ***@***.***> for awareness.

Teresa

Support: (800) 936-3100       Online: https://serviceshub.microsoft.com<https://serviceshub.microsoft.com/>

From: Bickham, Rodney ***@***.***>
Sent: Thursday, May 4, 2023 8:41 AM
To: microsoft/vscode ***@***.***>
Cc: Microsoft Support ***@***.***>; Teresa Davis ***@***.***>; West, Nancy ***@***.***>
Subject: [EXTERNAL] RE: [microsoft/vscode] Built in Concurrency (Issue #181327)

VS Code is a platform in which you can create Logic App "Workflows" locally, the term "Workflow" refers to Logic App. The Built-in connectors, the actions, the Sharepoint connections, all of that is a part of Logic App, not VS Code but VS Code is recommended as a tool to create Logic App Workflows rather than creating the Workflows on the portal. Yes, Logic App's works in VS Code like so much else, via extensions. So, technically I am having a problem with the VS Code Logic App extensions.

Sense you amazingly keep claiming to not know what I am talking about regarding "concurrency", here is a link dealing with "Concurrency Control" in Logic App, https://yourazurecoach.com/2017/08/29/logic-apps-concurrency-control/ . Here is a link dealing with "Workflows" in Logic App, https://docs.dapr.io/developing-applications/integrations/azure/workflows/.

Perhaps in the ticket I did not mention that I am using VS Code locally to produce Azure Logic App Workflows that then connect to Sharepoint and other platforms using actions built into Connectors, actions that in some cases contain "Concurrency settings" as an option. After four days of dropped appointments and the seeming inability for you all to understand without it being explicitly spelled out that Logic App "Workflows" with Concurrency Controls and connections to Sharepoint can be built locally using Extensions in VS Code, I have received zero support concerning getting VS Code and specifically, its Logic App extensions working correctly.

The VS Code "Triage Bot" was able to tell me what I already know, which is that Logic App Extensions are not working correctly in VS Code. Before another email comes asking me whether I have checked for Updates of the extensions or updates of VS Code, I check every morning, several times during the day.  My point here is that no news about clear serious problems has been explicitly put out by Microsoft, no explicit information about when and if repairs are forthcoming, about whether we end users should uninstall and reinstall the software, no acknowledgement by Microsoft that there is a problem except through Microsoft consultants we are working with. My point, is there seems to be no actual support on this problem.

**Comment by bickhamr** [comment]
The response below, essentially another demand, implicitly requiring me to submit another ticket or whatever "issue on the repos" means, then implying that I would need to list all the Logic App extensions I am using, and then telling me I am wrong about something that I never indicated about "support built into VS Code". I have previously had very positive experiences with Premier support, this is the worst. In addition this person has basically lowered the criticality level and then canceled the ticket without first informing me about it.

All that would have been necessary is a phone call, email or meeting, a civil conversation about what's going on, letting me know that Microsoft is working on the issue, something I have deduced anyway on my own from other sources. The most I expected from Premier support is maybe a few clues on ways I might be able to reinstall or jump start the extensions, some information about why VS Code seems to have malfunctioned. This kind of bureaucratic double talk and gaslighting is unnecessary and insulting. Its already clear without Premier that VS Code and/or its Extensions are having issues, and its not clear that it's the extensions rather than VS Code that has the problem. There seems to be a premium on short quick vague dismissive responses to anything rather than an honest attempt at support.

The "Engineer" initially assigned to this issue sent me an email at least acknowledging a miscommunication and that he was going on vacation which at least showed a minimum of civility rather than some  vague demand for more information that is then dismissed. Here is the email from Wilfrido Cascante,

*** External Email - Exercise Caution ***
Hello Rodney,
I think we had a timezone mismatch in our todays meeting
My calendar displayed the call for 10 am CST
***@***.***

I will going on vacation , I will request one of my colleagues to reach out to you in priority to get this issue resolved.
Regards.

Wilfrido Cascante
Support Engineer
Azure Logic Apps
Phone: +506 41143681
8:00 AM - 5:00 PM (Central America Time Zone)
Backup engineer 1: Heiner ***@***.******@***.***>)
Backup engineer 2: ***@***.******@***.***>)
Manager: Yolanda Briggs
***@***.******@***.***>

As far as I can see based on the responses of Mr. Lourens, Premier Support can be of no help whatsoever on these issues.
***@***.***
CAUTION: This email was received at the City of Austin, from an EXTERNAL source. Please use caution when clicking links or opening attachments. If you believe this to be a malicious and/or phishing email, please forward this email to ***@***.******@***.***>.

**Comment by roblourens** [comment]
I think there is some sort of misunderstanding here. I'm not "premier support" or any sort of support engineer. I'm not related to the other people you were talking to. You've opened a github issue on VS Code and I am very sure that what you are describing is not a VS Code issue.

**Comment by bickhamr** [comment]
Rodney,

Could you call me about this case?

512-795-5325
Or cat with me on Teams

***@***.*** .com



Teresa Davis
Customer Service Account Manager
State and Local Government
Phone: (512) 795-5325          Email: ***@***.******@***.***>
Support: (800) 936-3100       Online: https://serviceshub.microsoft.com<https://serviceshub.microsoft.com/>
[MS-logo]

From: Bickham, Rodney ***@***.***>
Sent: Thursday, May 4, 2023 8:41 AM
To: microsoft/vscode ***@***.***>
Cc: Microsoft Support ***@***.***>; Teresa Davis ***@***.***>; West, Nancy ***@***.***>
Subject: [EXTERNAL] RE: [microsoft/vscode] Built in Concurrency (Issue #181327)

VS Code is a platform in which you can create Logic App "Workflows" locally, the term "Workflow" refers to Logic App. The Built-in connectors, the actions, the Sharepoint connections, all of that is a part of Logic App, not VS Code but VS Code is recommended as a tool to create Logic App Workflows rather than creating the Workflows on the portal. Yes, Logic App's works in VS Code like so much else, via extensions. So, technically I am having a problem with the VS Code Logic App extensions.

Sense you amazingly keep claiming to not know what I am talking about regarding "concurrency", here is a link dealing with "Concurrency Control" in Logic App, https://yourazurecoach.com/2017/08/29/logic-apps-concurrency-control/ . Here is a link dealing with "Workflows" in Logic App, https://docs.dapr.io/developing-applications/integrations/azure/workflows/.

Perhaps in the ticket I did not mention that I am using VS Code locally to produce Azure Logic App Workflows that then connect to Sharepoint and other platforms using actions built into Connectors, actions that in some cases contain "Concurrency settings" as an option. After four days of dropped appointments and the seeming inability for you all to understand without it being explicitly spelled out that Logic App "Workflows" with Concurrency Controls and connections to Sharepoint can be built locally using Extensions in VS Code, I have received zero support concerning getting VS Code and specifically, its Logic App extensions working correctly.

The VS Code "Triage Bot" was able to tell me what I already know, which is that Logic App Extensions are not working correctly in VS Code. Before another email comes asking me whether I have checked for Updates of the extensions or updates of VS Code, I check every morning, several times during the day.  My point here is that no news about clear serious problems has been explicitly put out by Microsoft, no explicit information about when and if repairs are forthcoming, about whether we end users should uninstall and reinstall the software, no acknowledgement by Microsoft that there is a problem except through Microsoft consultants we are working with. My point, is there seems to be no actual support on this problem.
