### ISSUE TITLE
windows PATH is not refreshed upon restarting vscode

### ISSUE THREAD

**Issue by akbergsn** [microsoft/vscode#181323]
Type: <b>Bug</b>

I added yarn to my PATH and I can see it with Windows environment variables. When I restart Code, it does not pick up the changes to PATH. I can confirm the changes are valid on another new CMD prompt and other terminals. 

VS Code version: Code 1.77.3 (704ed70d4fd1c6bd6342c436f1ede30d1cff4710, 2023-04-12T09:16:02.548Z)
OS version: Windows_NT x64 10.0.19044
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) E-2174G CPU @ 3.80GHz (8 x 3792)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.83GB (17.72GB free)|
|Process Argv|-n --enable-proposed-api genuitecllc.codetogether --crash-reporter-id a530ab84-034c-46ca-a16b-ca5d73862f81|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
better-toml|bun|0.3.2
codetogether|gen|2023.1.1
cpptools|ms-|1.15.4
rust-analyzer|rus|0.3.1498
vscode-lldb|vad|1.9.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyonecf:30548226
nodejswelcome1:30587005
282f8724:30602487
pyind779:30671433
89544117:30613380
pythonsymbol12:30671437
a9j8j154:30646983
showlangstatbar:30730054
vsctsb:30705553
azdwalk:30721579
pythonms35:30701012
pythonfmttext:30716742
fixshowwlkth:30730052
hidesbindicator:30730055

```

</details>

**Comment by Tyriar** [comment]
All VS Code windows share the same environment, you need to close all windows (ie. close the main process) in order to refresh the environment.

/duplicate https://github.com/microsoft/vscode/issues/47816

**Comment by akbergsn** [comment]
I did that but the bug report I shared did not have a vscode history. I found that only New Window will load the path. Other ways of opening vscode only restore what was previously used.

**Comment by Tyriar** [comment]
If you closed them all, the only way an old environment could come is if you're using a "revived terminal" where the history shows up and it re-launches, as that uses the original environment. Still #47816 is what you're after.
