### ISSUE TITLE
Multiline commit description is sized incorrectly after scrolling away and back

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#181370]
- Type a multiline commit message
- Scroll away
- Scroll back
- When the row gets rerendered (I assume) it is sized to one line. If I type a newline in this box, the size gets fixed

![Recording 2023-05-02 at 20 18 28](https://user-images.githubusercontent.com/323878/235821644-6b880fd2-bfe8-4def-a033-8bee7286e8eb.gif)

**Comment by lszomoru** [comment]
Possibly a regression introduced with https://github.com/microsoft/vscode/commit/f5fdf679b8d22a0dd0dcb6fd8e3bc96bbeb99f75
