### ISSUE TITLE
Relative file links in comments do not work anymore

### ISSUE THREAD

**Issue by Sidebail** [microsoft/vscode#181435]
Possible regression of https://github.com/microsoft/vscode/issues/90848 

Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.77.3
- OS Version: Windows 11

Steps to Reproduce:

1. Open any folder with files in it
2. Open any code file that supports comments, preferably
3. Write a link to a relative file like this "file:///./relativeFile.txt"
4. Observe that upon clicking this link VSCode attempts to open the file with wrong/empty path

**Comment by Sidebail** [comment]
I've decided to fix it myself via pull request!
https://github.com/microsoft/vscode/pull/181475

Making a note of it since auto-triage assigned Microsoft employee to the issue. Sup, @alexr00 !

**Comment by KasparOrange** [comment]
Still an issue for me. 

- VS Code Version: 1.79.2
- OS Version: Windows 10

Same behavior. Would be really nice to have this feature working in a stable release. Get the most out of it if I can show other people how to find their way around my code easily. For that, It has to work for everybody (or most people).

**Comment by Challanger524** [comment]
### Place bets
I bet the _fix merging_ will have its first birthday celebration which is on 4th of May: https://github.com/microsoft/vscode/pull/181475

> May the 4th be with @alexdima to pull hi ~sh**~ feature-area together!

**Comment by schlawg** [comment]
For clarity, here are some things I've noticed on the state of this:

**Comment by schlawg** [comment]
This kinda works already for some - just not for windows and web users. On mac and linux, you can ctrl-click the `file://./relative-path` link directly and it works great. However if you wait for the mouseover popup and click "Follow link", it does not. :shrug:

It would be great if the mouseover popup behavior could be fixed along with the Windows behavior.

And oh my gosh, if we could have it working on vscode web, that would be amazeballs.
