### ISSUE TITLE
Bug with Escape char(0x1B) in text files

### ISSUE THREAD

**Issue by dimiden** [microsoft/vscode#181471]
Type: <b>Bug</b>

I have noticed that when a text file contains the "<Escape char(0x1B)>[0m" more than about 5000 times, VSCode is unable to show the line numbers properly.

I tested the issue with all extensions disabled, but the problem still occurred.

VS Code version: Code 1.78.0 (252e5463d60e63238250799aef7375787f68b4ee, 2023-05-03T20:09:00.748Z)
OS version: Windows_NT x64 10.0.22000
Modes:
Sandboxed: Yes
Remote OS version: Linux x64 5.13.0-44-generic
Remote OS version: Linux x64 5.13.0-44-generic
Remote OS version: Linux x64 5.13.0-44-generic
Remote OS version: Linux x64 5.13.0-44-generic

Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscoreces:30445986
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
2e4cg342:30602488
pyind779:30671433
89544117:30613380
pythonsymbol12:30671437
2i9eh265:30646982
showlangstatbar:30730054
vsctsb:30705553
azdwalk:30721579
pythonms35:30701012
pythonfmttext:30731395
pythonclientmv:30725892
fixshowwlkth:30730052

```

</details>

**Comment by dimiden** [comment]
This is the file I tested: [test.txt](https://github.com/microsoft/vscode/files/11392465/test.txt)
And this is a screenshot:
![image](https://user-images.githubusercontent.com/4264558/236096683-073d26fc-2dd1-4a74-94f0-b7ad023da4bc.png)

If I delete 2000+ lines, it works properly
![image](https://user-images.githubusercontent.com/4264558/236096771-06702f9b-5ec8-4110-9c7a-d78da24cbfe4.png)

**Comment by hediet** [comment]
I think this is fixed now.
