### ISSUE TITLE
Cursor is visible on top of color picker

### ISSUE THREAD

**Issue by usernamehw** [microsoft/vscode#181480]
1. Run `editor.action.showOrFocusStandaloneColorPicker`
2. Editor cursor is rendered on top of it

<img width="400" src="https://user-images.githubusercontent.com/9638156/236129089-f3604e40-d36d-488d-b328-4d302e2f6774.gif">

---
Version: 1.78.0
Commit: 252e5463d60e63238250799aef7375787f68b4ee
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Code/1.78.0 Chrome/108.0.5359.215 Electron/22.4.8 Safari/537.36

**Comment by aiday-mar** [comment]
Hi @usernamehw, thank you for filing the issue. I tried to reproduce this issue, but it seems to work fine on my computer. 

- Could you please try spawning a color picker in the latest VS Code Insiders (https://code.visualstudio.com/insiders/). 
- If you continue seeing this issue, could you please try to run VS Code Insiders without any extensions and reproduce this error? It so happens sometimes that extensions cause errors. 
- If you still see this issue, do you think you could copy paste below a minimally reproducible example of the contents of the editor where this happens?

**Comment by aiday-mar** [comment]
Hi, thanks for the reply, could you post here a copy of your settings file. I am thinking this error could be happening in relation to one of your settings.

**Comment by usernamehw** [comment]
Hmmm, it's a 2000 line-long file, not sure how useful it would be. It looks like I can reproduce it on the web with browser zoom and `"editor.wordWrap": "on",`. On desktop that would be:


```js
"editor.wordWrap": "on",
"window.zoomLevel": 2,
```
