### ISSUE TITLE
extension install 

### ISSUE THREAD

**Issue by lingxd** [microsoft/vscode#181492]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:  1.78.0
- OS Version: ubuntu18.04 linux x64 5.4.0-148-generic

Steps to Reproduce:

1.  install vscode extension from vsix file.
2.  output log,extension install faild.
```output
2023-05-04 17:01:51.352 [error] Unexpected token 'r', "r}
   */
 "... is not valid JSON: SyntaxError: Unexpected token 'r', "r}
   */
 "... is not valid JSON
    at JSON.parse (<anonymous>)
    at Object.factory (/usr/share/code/resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:85:90319)
```

**Comment by sandy081** [comment]
Seems the vsix is not valid. Can you please share the vsix?

**Comment by lingxd** [comment]
[ms-vscode.cpptools-extension-pack-1.3.0.zip](https://github.com/microsoft/vscode/files/11402775/ms-vscode.cpptools-extension-pack-1.3.0.zip)


> Seems the vsix is not valid. Can you please share the vsix?

**Comment by lingxd** [comment]
> Seems the vsix is not valid. Can you please share the vsix?

After I did a full reinstall of vscode I was able to install the extension normally.
