### ISSUE TITLE
Sometimes typing/writing code is not working

### ISSUE THREAD

**Issue by rmuddana-ns** [microsoft/vscode#181450]
Type: <b>Bug</b>

I am using Vim extension. Not sure it is a vscode/vim problem. It shows I am in insert mode but when I type it doesn't accept the input.

VS Code version: Code - Insiders 1.78.0-insider (657bb89984f37b810b250955570593cde0cd62eb, 2023-05-02T11:21:33.752Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: Yes
Remote OS version: Linux x64 4.4.0-210-generic
Remote OS version: Linux x64 4.4.0-210-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10850H CPU @ 2.70GHz (12 x 2712)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.76GB (12.76GB free)|
|Process Argv|--crash-reporter-id 06735b0a-7081-43af-8359-8d44db3e5a57|
|Screen Reader|no|
|VM|40%|

|Item|Value|
|---|---|
|Remote|SSH: rm-devbox|
|OS|Linux x64 4.4.0-210-generic|
|CPUs|Intel(R) Core(TM) i7-10850H CPU @ 2.70GHz (4 x 2712)|
|Memory (System)|5.83GB (2.88GB free)|
|VM|100%|

|Item|Value|
|---|---|
|Remote|SSH: rm-devbox|
|OS|Linux x64 4.4.0-210-generic|
|CPUs|Intel(R) Core(TM) i7-10850H CPU @ 2.70GHz (4 x 2712)|
|Memory (System)|5.83GB (2.88GB free)|
|VM|100%|
</details><details><summary>Extensions (20)</summary>

Extension|Author (truncated)|Version
---|---|---
jupyter-keymap|ms-|1.1.0
remote-ssh|ms-|0.101.2023050215
remote-ssh-edit|ms-|0.84.0
remote-explorer|ms-|0.5.2023040509
vim|vsc|1.25.2
gitlens|eam|2023.5.305
vscode-pull-request-github|Git|0.62.0
black-formatter|ms-|2023.3.10961008
isort|ms-|2022.8.0
python|ms-|2023.6.1
vscode-pylance|ms-|2023.4.40
jupyter|ms-|2023.4.1011241018
jupyter-keymap|ms-|1.1.0
jupyter-renderers|ms-|1.0.15
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-slideshow|ms-|0.1.5
cmake-tools|ms-|1.14.31
cpptools|ms-|1.15.4
cpptools-extension-pack|ms-|1.3.0
cmake|twx|0.0.17

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256197
vslsvsres303:30308271
pythontb:30258533
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscod805:30301674
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30404738
cppdebug:30492333
vscaac:30438845
vsclangdf:30492506
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30618038
pylantcb52:30590116
pyind779:30611226
pythonsymbol12:30651887
6233i204:30725950
azdwalk:30721579
pythonms35:30671666
0bg3d529:30680467
57b77579:30687741
pythonfmttext:30716741
pythoncmvfstr:30726892
fixhidewlkth:30724384
hidesbindicator:30724476
pythongtdpath:30726887

```

</details>

**Comment by rebornix** [comment]
Please file this issue against the Vim extension first, thanks
