### ISSUE TITLE
Improve dynamic extension recommendations

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#18147]
- [x] Include the language ID in the query
  - [x] We might need to curate a mapping
- [x] Add extensions tips to the results of "find extensions for this file type"

**Comment by joaomoreno** [comment]
@waderyan 

I've pushed a couple of changes:

- Querying for file extensions will now include a further set of keywords to search for. These keywords come from:
  - The language mode's name, in case we actually know about that file extension
  - A [curated map](https://github.com/Microsoft/vscode-distro/blob/master/quality/stable/product.json#L113) of keywords, which needs population. I'll leave that to you 👍 
- Additionally, the results will be merged with any recommendations we might have for that file extension

**Comment by waderyan** [comment]
FYI - done on my end.

**Comment by waderyan** [comment]
Ah nevermind and please ignore https://github.com/Microsoft/vscode/issues/19102. I see that I need to fill in the map (I thought you meant for the tips section... which is done :) )

**Comment by waderyan** [comment]
PR here - https://github.com/Microsoft/vscode-distro/pull/74
