### ISSUE TITLE
JavaScript and TypeScript crashes

### ISSUE THREAD

**Issue by nkjaiswal** [microsoft/vscode#181493]
Type: <b>Bug</b>

JavaScript and TypeScript crashes

VS Code version: Code 1.78.0 (Universal) (252e5463d60e63238250799aef7375787f68b4ee, 2023-05-03T20:11:00.813Z)
OS version: Darwin x64 22.4.0
Modes:
Sandboxed: Yes
Remote OS version: Windows_NT x64 10.0.22621

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz (16 x 2300)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|3, 2, 2|
|Memory (System)|16.00GB (0.36GB free)|
|Process Argv|--crash-reporter-id c3bf7b67-232c-4fb3-b747-a9906d0f1307|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: nishantkumarpc|
|OS|Windows_NT x64 10.0.22621|
|CPUs|Intel(R) Core(TM) i7-9700 CPU @ 3.00GHz (8 x 3000)|
|Memory (System)|31.83GB (17.07GB free)|
|VM|0%|
</details><details><summary>Extensions (58)</summary>

Extension|Author (truncated)|Version
---|---|---
tsl-problem-matcher|amo|0.6.2
es7-react-js-snippets|dsz|4.4.3
auto-close-tag|for|0.5.14
auto-rename-tag|for|0.1.10
Kotlin|mat|1.7.1
jupyter-keymap|ms-|1.1.0
remote-containers|ms-|0.292.0
remote-ssh|ms-|0.100.0
remote-ssh-edit|ms-|0.84.0
remote-wsl|ms-|0.78.4
vscode-remote-extensionpack|ms-|0.24.0
remote-explorer|ms-|0.4.0
remote-server|ms-|1.1.0
vscode-todo-highlight|way|1.0.5
tsl-problem-matcher|amo|0.6.2
regex-copy-or-cut|ara|1.0.0
npm-intellisense|chr|1.4.4
path-intellisense|chr|2.8.4
vscode-svgviewer|css|2.0.0
vscode-markdownlint|Dav|0.49.0
vscode-eslint|dba|2.4.0
githistory|don|0.6.20
es7-react-js-snippets|dsz|4.4.3
prettier-vscode|esb|9.12.0
flow-for-vscode|flo|2.2.1
auto-close-tag|for|0.5.14
auto-complete-tag|for|0.1.0
auto-rename-tag|for|0.1.10
search-node-modules|jas|1.3.0
rn-full-pack|kel|1.1.0
graphql-for-vscode|kum|1.15.3
Kotlin|mat|1.7.1
vscode-language-babel|mgm|0.0.39
isort|ms-|2022.8.0
python|ms-|2023.8.0
vscode-pylance|ms-|2023.5.10
jupyter|ms-|2023.4.1011241018
jupyter-keymap|ms-|1.1.0
jupyter-renderers|ms-|1.0.15
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-slideshow|ms-|0.1.5
azure-account|ms-|0.11.4
vscode-react-native|msj|1.11.0
color-highlight|nau|2.5.0
polacode|pnp|0.3.4
java|red|1.18.0
code-spell-checker|str|2.20.4
ms-teams-vscode-extension|Tea|4.2.5
teams-dyson|tea|0.0.2023041901
vscode-java-debug|vsc|0.50.0
vscode-java-dependency|vsc|0.22.0
vscode-java-pack|vsc|0.25.11
vscode-java-test|vsc|0.38.2
vscode-maven|vsc|0.41.0
gitblame|wad|10.2.0
vscode-todo-highlight|way|1.0.5
change-case|wma|1.0.0
markdown-all-in-one|yzh|3.5.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
vscccc:30610679
3biah626:30602489
pyind779:30671433
f6dab269:30613381
vscrp:30673768
pythonsymbol12:30671437
2i9eh265:30646982
6233i204:30730053
vsctsb:30705553
azdwalk:30721579
pythonms35:30701012
pythonfmttext:30731395
pythonclientmvcf:30725893
fixhidewlkth:30730051

```

</details>

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

**Comment by sms1989** [comment]
After update my VSCode to 1.78.0 in some projects with typescript JSX the IntelliSense stoped working .... I'm use insiders build with all extensions disabled but nothing changed ... I have "loading ..." popup and every intellisense system stoped.

system info:
machine: Macbook pro M1 pro
OS: macOS 13.3.1 (a) (22E772610a)

**Comment by mjbvz** [comment]
Closing as need more info from the original posters

@sms1989 If you still see this in VS Code 1.79, please open a separate issue with info about you workspace
