### ISSUE TITLE
Bug Ctrl C Kill Server

### ISSUE THREAD

**Issue by bimosptr1** [microsoft/vscode#181488]
Does this issue occur when all extensions are disabled?: Yes

Version: 1.78.0 (Universal)
Commit: 252e5463d60e63238250799aef7375787f68b4ee
Date: 2023-05-03T20:11:00.813Z
Electron: 22.4.8
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Darwin x64 18.7.0
Sandboxed: Yes

ProductName: macOS
ProductVersion: 10.14.6 Mojave
BuildVersion: 18G9323

Steps to Reproduce:

Open the integrated terminal.
Execute cat
Type Ctrl-C
The cat command doesn't exit. Only ^C is printed.
Notice that Ctrl-C does work on the latest v1.78.0.

**Comment by meganrogge** [comment]
works for me on Insider's 

https://user-images.githubusercontent.com/29464607/236213122-8a4453be-ec40-4267-8a63-c5bb98231586.mov

**Comment by bimosptr1** [comment]
> works for me on Insider's
> 
>  cat.mov

on mac os monjave version not work 

<img width="1039" alt="image" src="https://user-images.githubusercontent.com/75081018/236243937-bfb1b715-5606-4879-8058-e862bd6f92ed.png">

**Comment by vinipaschoal** [comment]
Still broken on mine, MacOS Mojave.
