### ISSUE TITLE
Areas of the app are unclickable on ChromeOS

### ISSUE THREAD

**Issue by wesort** [microsoft/vscode#181403]
- VS Code Version: 1.77
- OS Version: ChromeOS v113, Debian GNU/Linux 11
- Does this issue occur when all extensions are disabled?: Yes

Adding info to #179666 (closed) and is a wider issue (not only overlay messages)

### Steps to Reproduce:
- Open the VS Code on a ChromeOS device and lay out the app / window in any of the following ways: 
  - Window "maximised" on external displays
  - Window "docked" to right or left on a landscape display, or "docked" to top or bottom on a portrait (rotated 270°) display 
- The "unclickable areas" are:
  - approximately the bottom 20% of the "[editor groups](https://code.visualstudio.com/docs/getstarted/userinterface)"
  - buttons in the "panel" (terminal can be typed in, but can't use the buttons)
  - right side of blue bottom-bar ("tweet feeback", "notifications")
- Try to use anything in the interface that sits within the "unclickable areas"

**NB:** _this does not affect the explorer tree list, or the profile or gear icons in the far left_

### Workaround
- Change the window size such that the new height is less than the portion that was unusable before
- This makes those areas now clickable.

<details>
<summary>Environment: OS & VS Code</summary>

## VS code
Version: 1.77.3
Commit: 704ed70d4fd1c6bd6342c436f1ede30d1cff4710
Date: 2023-04-12T09:16:52.732Z
Electron: 19.1.11
Chromium: 102.0.5005.196
Node.js: 16.14.2
V8: 10.2.154.26-electron.0
OS: Linux x64 5.15.103-17407-ged5b2e0e131c
Sandboxed: No

## ChromeOS
Google Chrome: Version 113.0.5672.67 (Official Build) beta (64-bit)
Platform: 15393.38.0 (Official Build) beta-channel puff
Channel: beta-channel
Firmware Version: Google_Duffy.13324.71.0
ARC enabled: false
ARC: 9899622
Enterprise enrolled: false
Developer mode: false

## Linux on ChromeOS
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
</details>

**Comment by deepak1556** [comment]
I don't have the setup to verify this issue

**Comment by bpasero** [comment]
Is this still happening?

**Comment by wesort** [comment]
Seems to be resolved for me.

Tested on Pixelbook Go running:
- ChromeOS: beta v120 
- Linux: Debian GNU/Linux 11 (bullseye)
- VS Code:
  > Version: 1.84.2
Commit: 1a5daa3a0231a0fbba4f14db7ec463cf99d7768e
Date: 2023-11-09T10:50:47.800Z
Electron: 25.9.2
ElectronBuildId: 24603566
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Linux x64 6.1.60-08589-g295af3f6449b
