### ISSUE TITLE
Language selectors should get higher priority if it includes a notebookType

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#181453]
For two language selectors:

```ts
{ language: 'markdown' }
{ language: 'markdown', notebookType: 'foo' }
```

Currently our language provider scoring gives the two selectors the same score when you are in a notebook document. I suggest that the second selector gets priority when in notebook documents as it is more specific 

/cc @jrieken @Yoyokrazy

**Comment by jrieken** [comment]
>  I suggest that the second selector gets priority when in notebook documents as it is more specific

Why would that be? We also don't score higher for other matches like `{ language: 'foo' }` is the same as `{ language: 'foo', scheme: 'file' }`

**Comment by mjbvz** [comment]
Closing this in favor of adding a priority to the paste/drop edits. This lets providers give an order to their edits
