### ISSUE TITLE
unneccessary coercing of values in filter method

### ISSUE THREAD

**Issue by nikikalwar** [microsoft/vscode#181470]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: latest
- OS Version: Windows

My question is regarding the code at https://github.com/microsoft/vscode/blob/main/build/filters.js 
at line 194 with the implementation of the filter method. --> .filter(line => !!line)
if we use .filter(line=>line) it removes all the falsy values without the requirement of coercing the value of line to change truthsy or falsy values as seen above. I believe it will be unnecessary overhead if we use the double exclamation.

Thanks for your help.

**Comment by nikikalwar** [comment]
Hi Team, Can I raise a PR for this issue?

**Comment by joaomoreno** [comment]
While you're not wrong, this is functionally OK and has virtually zero performance impact. It's also a build file.

If you're looking to help, our guide is pretty good: https://github.com/microsoft/vscode/wiki/How-to-Contribute
