### ISSUE TITLE
file document content loss when the computer storage is full

### ISSUE THREAD

**Issue by sshuair** [Microsoft/vscode#18142]
- VSCode Version: Code 1.8.1 (ee428b0eead68bf0fb99ab5fdc4439be227b6281, 2016-12-19T14:42:49.304Z)
- OS Version: Darwin x64 16.3.0
- Extensions:

|Extension|Author|Version|
|---|---|---|
|beautify|HookyQR|0.7.2|
|code-settings-sync|Shan|2.3.8|
|project-manager|alefragnani|0.12.2|
|githistory|donjayamanne|0.1.4|
|python|donjayamanne|0.5.5|
|Lua|keyring|0.0.9|
|MagicPython|magicstack|1.0.3|
|vscode-icons|robertohuertasm|4.3.0|
|vscode-proto3|zxh404|0.0.5|

---

Steps to Reproduce:

1. find a computer which the storage is almost full
2. open a not empty file with vscode 
3. edit the file then save the file
4. then, all file content will loss

**Comment by bpasero** [comment]
@sshuair can you finish that sentence under point 3
