### ISSUE TITLE
regression: source origin no longer shown in editor header

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#18148]
- VSCode Version: 1.9.0

Steps to Reproduce:
- disable editor tabs
- start node debugging and select internal node module 'module.js' in CALLSTACK

Observe:
With VS Code 1.9.0 the editor header now shows the (bogus) 'path' instead of the 'origin':
![2017-01-05_11-25-49](https://cloud.githubusercontent.com/assets/1898161/21677374/184c7d82-d33a-11e6-93d7-17438163f4b9.png)

In stable the 'origin' attribute of the source is shown:
![2017-01-05_11-23-29](https://cloud.githubusercontent.com/assets/1898161/21677387/2ca44986-d33a-11e6-9791-8480fe39a84f.png)

I've tagged this as 'important' because this makes my current work on #16918 more confusing than necessary.

**Comment by isidorn** [comment]
Due to this [ITextModelContenProvider](https://github.com/Microsoft/vscode/blob/master/src/vs/editor/common/services/resolverService.ts#L36), should also have a `provideDescription(resource:URI): string` - so each content provider could customize this area.

thoughts @joaomoreno @bpasero

**Comment by isidorn** [comment]
@bpasero thanks! This worked! Though what might still be needed is to customize the hover - currently you always show the path of the uri and we might want to change that for this use case. Will let you know if we end up needing this

**Comment by bpasero** [comment]
@isidorn that is weird, we use the description as hover title and if you specify it, it should show up as such.

**Comment by isidorn** [comment]
@bpasero no, the description you seem to use only in no tab mode for the grayed out text next to the title. The hover you always compute based on uri path

![screen shot 2017-01-05 at 15 22 46](https://cloud.githubusercontent.com/assets/1926584/21683722/e6daad3e-d35a-11e6-9548-14b6bde40982.png)

**Comment by bpasero** [comment]
@isidorn got it, pushed a fix.

Btw when I tested this, I noticed that the read-only core module editor is not closing when I stop the debug session. I think these used to close when ending the debug session but do not close anymore? Is that known?

**Comment by isidorn** [comment]
@bpasero Yes, before the content provider debug world was handling the lifecycle of these editors inputs and would dispose all of them on debug session end.
However now that is not the case. What I could do is go through all the open editors, check if they represent internal modules and potentially close them. Not sure if there is a nicer way to do this?

**Comment by bpasero** [comment]
@isidorn you are creating the models for provideTextContent, you could dispose them once done and the resource input is tracking that. I think there is no better way currently from the API (@joaomoreno am I right?)

**Comment by isidorn** [comment]
@bpasero thanks! Now I am doing exactly that and seems to work just fine

**Comment by joaomoreno** [comment]
Yeah, it's ugly, but the only available way for now.
