### ISSUE TITLE
[Feature Request] Add feature to disable or grey-out obsolete/deprecated C# methods, attributes, etc on autocomplete

### ISSUE THREAD

**Issue by CanisLupus** [Microsoft/vscode#18149]
Or is this something that should be suggested for Omnisharp instead?

I couldn't find a setting for this, nor find results about it on Google. It would be really helpful to avoid auto-completing obsolete stuff when using an API that has legacy methods and attributes. Greying out things marked Obsolete (and showing them last) - or maybe even disabling them - would be great.

Thanks,
Daniel

**Comment by sandy081** [comment]
@CanisLupus Please open this request for Omnisharp
