### ISSUE TITLE
Moving unsaved files loses content irreversably

### ISSUE THREAD

**Issue by DmitryEfimenko** [Microsoft/vscode#18145]
- VSCode Version: 1.8.1
- OS Version: Windows 10

Steps to Reproduce:

1. create a file "myFile.ts"
2. create a folder "myFolder"
3. edit "myFile.ts"
4. without saving the file, move it to "myFolder"
5. observe notification about lost unsaved changes
6. click OK.
7. observe the file is empty

The Issue:

To me, this workflow is a big issue. Windows conditioned people to click OK on annoying popup notifications.
I was working on a file for 2 hours, saving it every minute (just like I used to). Then I modified it again and decided to move it to find out that 2 hours worth of work is gone. There is no Ctrl-Z to this. GONE.
Surely it's my fault for quickly dismissing the popup, but people will do that. I'd think it should not be hard to avoid this popup especially after all the great work you guys did with the hot reload.

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/11997
