### ISSUE TITLE
Accept next word doesn't reveal it

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#181407]
* type at the end of line
* have ghost text
* accept it word by word
* 🐛 when reaching the end of the viewport accepted words aren't revealed

https://user-images.githubusercontent.com/1794099/235932410-ad0dcf0e-da43-47ff-b735-17545b3ebc3d.mov

**Comment by jrieken** [comment]
@hediet fyi that I have pushed https://github.com/microsoft/vscode/pull/213530 as a fix for this

**Comment by hediet** [comment]
Thank you! ❤️ Sorry for not fixing this, I thought the fix was more complicated.

**Comment by karthiknadig** [comment]
Accepting single word seems to move the horizontal scroll, but tabbing to accept the whole line does not scroll. Is that expected?

**Comment by karthiknadig** [comment]
Marking as verified as word by word works.
