### ISSUE TITLE
One 1px black line appears every 6 lines of code while set Zoom Level = -1 

### ISSUE THREAD

**Issue by fullmooooon** [microsoft/vscode#181468]
Type: <b>Bug</b>

I enjoy working with Zoom Level=-1 setting
But one 1px black line appears every 6 lines of code while set Zoom Level = -1 
This issue will not occur in larger or smaller Zoom setting

Look carefully at the demarcation point between lines 5 and 6, or lines 17 and 18

Zoom Level = -1 
![image](https://user-images.githubusercontent.com/43309591/236091786-52b4a88d-7cec-452e-89fc-21a3d5ef2463.png)

Zoom Level = 0
![image](https://user-images.githubusercontent.com/43309591/236092126-6a270799-73b7-4832-9845-a94541643eea.png)

Zoom Level = 1
![image](https://user-images.githubusercontent.com/43309591/236092236-de1cb9a3-61d8-4e9e-b2c5-ffb5a04839cf.png)

Zoom Level = -2
![image](https://user-images.githubusercontent.com/43309591/236092374-eb6e68a0-a7eb-4793-bfdb-f98ae82bf0ed.png)

VS Code version: Code 1.78.0 (252e5463d60e63238250799aef7375787f68b4ee, 2023-05-03T20:09:00.748Z)
OS version: Windows_NT x64 10.0.19044
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i5-11400 @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.77GB (3.10GB free)|
|Process Argv|--crash-reporter-id c5dd1000-1cea-459e-81ce-b6a43a9961b6|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (48)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-javascript-snippet-pack|aka|0.1.6
Bookmarks|ale|13.3.1
electron-snippets|ant|1.0.3
path-intellisense|chr|2.8.4
EnglishChineseDictionary|Cod|1.1.0
vbscript|Dar|1.0.4
dart-code|Dar|3.62.0
flutter|Dar|3.62.0
javascript-ejs-support|Dig|1.3.3
jquerysnippets|don|0.0.1
xml|Dot|2.5.1
vscode-html-css|ecm|1.13.1
EditorConfig|Edi|0.16.4
prettier-vscode|esb|9.12.0
auto-close-tag|for|0.5.14
auto-rename-tag|for|0.1.10
code-runner|for|0.12.0
kotlin|fwc|0.2.31
vscode-atom-javascript-snippet|glu|0.2.1
pause-console|Guy|0.2.4
svg|joc|1.5.2
jsdoc|lll|1.0.9
Kotlin|mat|1.7.1
vscode-scss|mrm|0.10.0
vscode-docker|ms-|1.25.0
vscode-language-pack-zh-hans|MS-|1.78.2023050309
remote-containers|ms-|0.288.1
remote-wsl|ms-|0.78.4
powershell|ms-|2023.5.0
gradle-language|nac|0.2.3
javascriptsnippets|nat|0.4.0
indent-rainbow|ode|8.3.1
rust-analyzer|rus|0.3.1498
vue-vscode-extensionpack|sdr|0.2.0
kotlin-on-vscode|set|0.0.1
vscode-3dviewer|sle|0.2.2
element-ui-snippets|SS|0.7.2
autoimport|ste|1.5.4
svelte-vscode|sve|107.3.0
vscode-status-bar-format-toggle|tom|3.1.1
volar|Vue|1.6.4
vscode-todo-highlight|way|1.0.5
vscode-jumpy|wma|0.3.1
vue|Wsc|1.0.26
php-debug|xde|1.32.1
php-pack|xde|1.0.3
type-challenges|YRM|1.13.0
markdown-all-in-one|yzh|3.5.1

(5 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vstes627:30244334
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
3biah626:30602489
pyind779:30671433
89544117:30613380
pythonsymbol12:30671437
showlangstatbar:30730054
vsctsb:30705553
azdwalk:30721579
pythonms35:30701012
pythonfmttext:30731395
fixhidewlkth:30730051

```

</details>

**Comment by daviddossett** [comment]
Not sure off the top of my head what would be causing this. @hediet any ideas?
