### ISSUE TITLE
`Reopen Closed Editor` keyboard shortcut (Ctrl+Shift+T) not working on vscode.dev

### ISSUE THREAD

**Issue by bhavyaus** [microsoft/vscode#181565]
Steps to Reproduce:

1.  Open a file on vscode.dev
2.  Close the editor
3. Use Ctrl+Shift+T to reopen the editor. 

Expected: Previously opened editor is restored.
Actual: 
no-op on vscode.dev. Edge reopens the previously opened tab.

**Comment by bpasero** [comment]
There are keybindings that are reserved for the browser. If you want the full support of keybindings, you will have to run VSCode as a PWA application and/or use fullscreen mode.

Duplicate / related to https://github.com/microsoft/vscode/issues/149478
