### ISSUE TITLE
Proposal: window activity API

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#181569]
## Motivation

Many implementors who manage remote resources, like Codespaces and Azure Functions, want to know if the user has been inactive for a while in order to suspend resources. Currently, they just listen to a ton of events and try to guess when the user is active. In effect:

```ts
vscode.workspace.onDidChangeTextDocument((e) => {
    this.onActivity();
}),
vscode.workspace.onDidOpenTextDocument((e) => {
    this.onActivity();
}),
vscode.workspace.onDidCloseTextDocument((e) => {
    this.onActivity();
}),
vscode.workspace.onDidSaveTextDocument((e) => {
    this.onActivity();
}),
// ...
```

This is still partial, since there is some activity (such as work in custom editors) which is not surfaced through these events at all. VS Code itself could provide a much simpler and more reliable approach.

## Proposal

A new property to the `WindowState`:

```ts
export interface WindowState {
	/**
	 * Indicates whether the window has been interacted with recently. This will
	 * change immediately on activity, or after a short time of user inactivity.
	 */
	readonly active: boolean;
```

In core, we would set up a global handler for mouse movements and keystrokes that can be used to drive the handler logic.

Addition from standup discussion: if a notebook cell is running, we would never consider the window to be inactive. Probably have some `register*`able API in core for different components to hook into.

## Alternatives

One alternative is what extensions do today, which is flawed.

Another proposed approach, which is mainly just useful in the remote case, is monitoring flowing bytes to the remote and developing a heuristic based off that. But this is very finicky and similarly doesn't capture activity which may only interact with the local editor or extension host.

**Comment by paulyuk** [comment]
:+1:

**Comment by akosyakov** [comment]
fyi for an alternative: https://github.com/microsoft/vscode/issues/134795

**Comment by connor4312** [comment]
From discussion, it would make sense to have an `active: boolean` on the existing `WindowState`. Extensions can do what they want as a result of change to that, such as setting a timeout that will dispose resources

**Comment by connor4312** [comment]
Yes. Generally it's helpful to see some consumers of it, so if you've used it and like it, dislike it, or ran into problems, please let us know!

**Comment by jeanp413** [comment]
Is this still on track to be finalized for July release 🙏 ?

**Comment by connor4312** [comment]
Not currently, I haven't gotten any feedback on it yet, and it's likely to stay in proposed until I do

**Comment by li-yq** [comment]
Thumbs up for stabilizing the API! I created a [simple extension](https://github.com/li-yq/vscode-heartbeat) using this API to monitor user activity and update a heartbeat file. This allows for automatic shutdown of idle remote VMs, and it appears to function effectively. Only the problem is that I can not use the proposed API without Insider version :rofl:

**Comment by CareyJWilliams** [comment]
Another thumbs up here! This works well for our use-case and we'd be happy to help get this stabilized.

**Comment by connor4312** [comment]
This'll be finalized in our next release
