### ISSUE TITLE
Abnormal after reloading the terminal

### ISSUE THREAD

**Issue by tisilent** [microsoft/vscode#181536]
Version: 1.78.0 (user setup) 77 76
Commit: 252e5463d60e63238250799aef7375787f68b4ee
Date: 2023-05-03T20:09:00.748Z
Electron: 22.4.8
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Windows_NT x64 10.0.19044
Sandboxed: No

![20230505_000231](https://user-images.githubusercontent.com/48614781/236262213-cb2ccc54-5801-4f91-b7bb-0cdb5b287fab.gif)

1.Create two new terminals
2.Move the second to Editor area
3.reload
4.Move to panel

Sometimes it just disappears

Check related to storage.

**Comment by Tyriar** [comment]
Related: https://github.com/microsoft/vscode/issues/135968

**Comment by jeanp413** [comment]
PR fixing it https://github.com/microsoft/vscode/pull/182121
