### ISSUE TITLE
CSS format dont work

### ISSUE THREAD

**Issue by marpereira** [Microsoft/vscode#18152]
- VSCode Version: Code 1.8.1 (ee428b0eead68bf0fb99ab5fdc4439be227b6281, 2016-12-19T14:49:23.350Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

|Extension|Author|Version|
|---|---|---|
|vscode-angular2-files|alexiv|1.3.6|
|swagger-viewer|Arjun|1.2.0|
|vscode-svgviewer|cssho|1.3.0|
|Angular2|johnpapa|1.0.2|
|debugger-for-chrome|msjsdiag|2.4.2|
|change-case|wmaurer|1.0.0|

---

Steps to Reproduce:

1. produce css code
2. using {"key": "shift+alt+f",           "command": "editor.action.formatDocument"} don't do anything to document

**Comment by mrmlnc** [comment]
Works fine for me. I think, that you can provide your file or code sample for reproduce your problem?

**Comment by marpereira** [comment]
`/* === MARGIN === */
.ml22   {
      margin-left: 22px;
}

      .mb10{
  margin-bottom: 10px;
}

        .w100{
  width: 100%;
    }`

**Comment by sandy081** [comment]
@marpereira In which kind of file (html or css) this css code is in?

**Comment by marpereira** [comment]
Css

**Comment by sandy081** [comment]
@marpereira I do not see format feature is available in CSS files by default. Do you have any extension that add this functionality?

**Comment by marpereira** [comment]
I don't think so. Probably this is not a bug and need to be a feature :)
I report it like a bug because I think that i've done this before. Maybe i didn't.

**Comment by aeschli** [comment]
The built-in css support does not provide formatting. There are various extensions that add support for this.
