### ISSUE TITLE
Ctrl + click doesn't show all places where component used

### ISSUE THREAD

**Issue by GIT-MDW** [microsoft/vscode#181511]
![Screenshot 2023-05-04 165453](https://user-images.githubusercontent.com/94377644/236211082-515d16ff-e8c1-42d1-99f9-a393bbc7138d.png)
![Screenshot 2023-05-04 165536](https://user-images.githubusercontent.com/94377644/236211094-e6ad4903-932d-4178-8dfe-6c344cf2c201.png)

**Comment by GIT-MDW** [comment]
Here is the differences

**Comment by GIT-MDW** [comment]
I believe it will function in a tiny bit of code, but not in large projects.

**Comment by mjbvz** [comment]
Please share a project that demonstrates it then. Otherwise we can't investigate it
