### ISSUE TITLE
Unused variables in Python no longer semantically highlighted

### ISSUE THREAD

**Issue by mhillebrand** [microsoft/vscode#181540]
- VS Code Version: 1.78.0
- Python Extension Version: 2023.8.0
- Pylance Extension Version: 2023.5.10
- OS Version: macOS 13.3.1 (a); Linux Mint 21.1

Steps to Reproduce:

1. Upgrade to latest version of VS Code.
2. Create a variable that isn't used.
3. Notice that it is no longer a darker/different color from variables that ARE used.

**Comment by yomajo** [comment]
Related: my python code is mostly white.

**Comment by g5becks** [comment]
This issue is still happening  for me, and not just in python code, but Go as well.

**Comment by VladyslavY** [comment]
The issue persists for me too despite trying all linters I could find

**Comment by alexdima** [comment]
@mhillebrand From your screenshot, I can see that the editor-level feature of unnecessary code works correctly. I believe this is a language specific problem. Please report to https://github.com/microsoft/vscode-python

Also, I can see the feature working for TS, so this cannot be a problem with the editor itself.
```
"workbench.colorCustomizations": {
	"editorUnnecessaryCode.border": "#ff0000"
},
```

![image](https://github.com/microsoft/vscode/assets/5047891/15728d32-1f42-480f-8fba-fe2cd28efc55)
