### ISSUE TITLE
Running Commands in VS Code Terminal does not save the history

### ISSUE THREAD

**Issue by shalearkane** [microsoft/vscode#181508]
Running commands in a normal bash terminal retains the history (of the commands ran) but the same is not true for VS Code. So after closing VSCode all of the command history is deleted and the user has to remember any complex command that they ran. Ideally we would want our history to be stored in .bash_history or if VS Code doesn't want to touch user files, in .vscode_bash_history perhaps?

**Comment by hameer-spire** [comment]
Doesn't work for me either, tried deleting `$HOME/.vscode-server` and re-installing, no dice.

**Comment by meganrogge** [comment]
Maybe this is a remote issue

**Comment by Tyriar** [comment]
More reports here: https://github.com/microsoft/vscode/issues/180474

**Comment by vaindil** [comment]
This affects me on my MacBook Pro as well. It's a problem 100% of the time, it's not intermittent. I'm guessing it's not a remote issue, as it happens when I'm using a completely local folder without any sort of remote functionally.

If I type `exit` to close the terminal before I quit VS Code, the history is saved like it should be. If I quit VS Code without doing that, the history is lost. This is a recent issue (within the last couple of months or so), it used to work correctly. Happy to provide any other info that can help diagnose this, as I can always reproduce it.

**Comment by shalearkane** [comment]
Yes, the history save feature works if I type `exit` or `ctrl+D` to close the terminal. Doing it by any other way (like clicking the trash button to close the terminal) does not save the history.

**Comment by shalearkane** [comment]
I think that I have found the issue. 
https://github.com/microsoft/vscode/blob/704ed70d4fd1c6bd6342c436f1ede30d1cff4710/src/vs/platform/terminal/node/terminalProcess.ts#L378

In this line, we are sending `SIGKILL` instead of `SIGTERM`, hence the process gets killed without the chance to write the history to the file ([source](https://unix.stackexchange.com/a/25052/511319))

However it seems that this change was made because the terminal subprocess (running `shellIntegration-bash.sh`) couldn't be killed because the `traps` are also gobbling up any signal. 

I think the solution to this can be done by creating a function something like :
```bash
cleanup() {
    err=$?
    trap '' EXIT INT TERM
    exit $err 
}
sig_cleanup() {
    trap '' EXIT
    false # sets $?
    cleanup
}

trap sig_cleanup TERM
```
(relevant discussion in [SO](https://unix.stackexchange.com/questions/57940/trap-int-term-exit-really-necessary))
That way, the `SIGTERM` signal can be intercepted and exited as needed.

**Comment by shalearkane** [comment]
If you it is possible, could you help me to write a patch to fix this issue? :smile: I have tried patching with the about function to trap SIGTERM in `src/vs/workbench/contrib/terminal/browser/media/shellIntegration-bash.sh` however, I am having trouble getting it to work.
