### ISSUE TITLE
Firefox crash when trying to open link from VSCODE

### ISSUE THREAD

**Issue by MalcolmMielle** [microsoft/vscode#181500]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.78.0
- OS Version: Fedora 37

Steps to Reproduce:

1. Install vscode as snap
2. Try to open a link anywhere (terminal, github extension, Azure extension).
3. Watch firefox crash :(

**Comment by deepak1556** [comment]
Merging to https://github.com/microsoft/vscode/issues/179917
