### ISSUE TITLE
`TypeError: Cannot set properties of undefined (setting 'ELECTRON_USE_V8_CONFIGURED_PARTITION_POOL')` for 1.78.0

### ISSUE THREAD

**Issue by c3wenjiaowang** [microsoft/vscode#181580]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.78.0
- OS Version: macOS Monterey v12.4

Steps to Reproduce:

1. In any vscode extension, add this line: `spawnSync(process.execPath, [], {})`
2. The error in title is thrown

The `process.execPath` points to '/Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Plugin).app/Contents/MacOS/Code Helper (Plugin)', which looks normal.

**Comment by c3-kaspesi** [comment]
I am also seeing this issue

**Comment by danielxu7** [comment]
Hello, I am also experiencing this issue. In my extension, I have been able to reproduce with the following code:
```js
  public async activate(ctx: ExtensionContext): Promise<void> {
    spawnSync(process.execPath, [], {}); // throws
  }
```
When I run the same line in a standalone Node.js file, the same line passes:
```js
const spawnSync = require('child_process').spawnSync;
spawnSync(process.execPath, [], {}); // does not throw
```

**Comment by deepak1556** [comment]
Sorry for the breakage, you can provide an empty env as a workaround

```
spawnSync(process.execPath, [], {env: {}});
```

**Comment by c3wenjiaowang** [comment]
@deepak1556 Thanks for fast response and the workaround! May I ask do you have an estimation of the version release with the fix? As it is used in dependencies, and we can't update all use cases there. Thank you!

**Comment by deepak1556** [comment]
*Verification steps:*

1) Add the following `require('child_process').spawnSync(process.execPath, [], {});` to the [hello world extension](https://github.com/microsoft/vscode-extension-samples/tree/main/helloworld-minimal-sample)
2) Launch the extension and confirm that the spawn call does not throw an error
