### ISSUE TITLE
 Uncaught TypeError: Cannot read property 'startColumn' of null

### ISSUE THREAD

**Issue by vscodeerrors** [Microsoft/vscode#1815]
Issue Id: <b>f25ac3e8-6b36-281b-a59c-626477d4a8a2</b><br /><br />*Versions* <br />- 0.10.6-release<br />-  dfc08dc9edf6607483b193bf934d3badc3fa2e11<br />*Stack* <br />TypeError: Cannot read property 'startColumn' of null<br />[/vs/editor/contrib/rename/browser/rename.ts#L130:22 (LocalProgressService._addDecoration)](https://github.com/microsoft/vscode/blob/a80232bbcfe8a5cdad1ebc98638673d9dcb02458/src/vs/editor/contrib/rename/browser/rename.ts#L130:22 (LocalProgressService._addDecoration))<br />[/vs/editor/contrib/rename/browser/rename.ts#L107:21 (LocalProgressService.showWhile)](https://github.com/microsoft/vscode/blob/a80232bbcfe8a5cdad1ebc98638673d9dcb02458/src/vs/editor/contrib/rename/browser/rename.ts#L107:21 (LocalProgressService.showWhile))<br />

**Comment by alexandrudima** [comment]
I removed the entire file in the meantime.
