### ISSUE TITLE
Save new file dialog box in Ubuntu 16.04 has poor UI layout

### ISSUE THREAD

**Issue by DolphinDream** [microsoft/vscode#181532]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.78
- OS Version: Ubuntu 16.04

Steps to Reproduce:

1. Create new file
2. Save the file
3. observe the dialog box UI 

The dialog box when saving the new files are showing the path (subpaths) where the file is going to be saved concatenated together without any slashes or spaces or tabs and it’s hard to see where the file is saved and to navigate to any of the subpaths in the initial path. See attached screen capture.. and a comparison with Sublime Text save dialog box feature (which has a better UI layout with path better separated visually). VSCode seems to invoke a different dialog box system than other apps (like SublimeText) which perhaps explains the difference. Either way, it’s not fun to have to visually parse the path from a concatenated subpaths without subpath separations. Whatever version of the save dialog box ST uses it seems to be more polished and user friendly than the one VScode uses. 

<img width="1680" alt="VScode-save-dialogbox" src="https://user-images.githubusercontent.com/2083719/236251740-3eb37142-e28f-47d6-9aac-31bd8cb73776.png">

<img width="1680" alt="SublimeText-save-dialogbox" src="https://user-images.githubusercontent.com/2083719/236251554-f4dd060c-2655-481f-b848-ae587bdd95aa.png">

**Comment by rzhao271** [comment]
The UI looks fine to me on a one-week-old Insiders on Ubuntu 22.04.
I'll reconfirm with the latest Stable and Insiders, but also let me know if the issue still occurs on Ubuntu >=18.04 for you, @DolphinDream.

**Comment by DolphinDream** [comment]
The issue occurred and still occurs in **Ubuntu 16.04** (even with VSCode 1.85). However, the issue does not occur in **Ubuntu 22.04**.

**Comment by rzhao271** [comment]
16.04 isn't officially supported now, ref https://code.visualstudio.com/Docs/supporting/requirements
