### ISSUE TITLE
First terminal does not follow default. 

### ISSUE THREAD

**Issue by tbenthompson** [microsoft/vscode#181515]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.78.0 
- OS Version: Mac OS 13.3.1

Steps to Reproduce:

1. Open a new VSCode window using Codespaces. 
2. The initial terminal window opens a `bash` terminal. If I kill that terminal and open a new terminal, I get `zsh` as expected. 

I have in my settings.json:
```
  "terminal.integrated.defaultProfile.linux": "zsh",
```

I believe this is a duplicate of these closed issues: 
- https://github.com/microsoft/vscode/issues/142425
- https://github.com/microsoft/vscode/issues/142649

**Comment by Tyriar** [comment]
I was expecting this would get fixed as part of https://github.com/microsoft/vscode/pull/175844, cc @jeanp413

**Comment by jeanp413** [comment]
PR https://github.com/microsoft/vscode/pull/181832
