### ISSUE TITLE
All custom Keyboard shortcuts are gone (even in sync history!)

### ISSUE THREAD

**Issue by jmevel** [microsoft/vscode#181582]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.78.0
- OS Version: Fedora 38 - KDE Plasma 5.27.4

Steps to Reproduce:

1. `Ctrl+K Ctrl+S`
2. `Open Keyboard shortcuts (JSON)` -> File is empty in all profiles including the default !
3. Open the Palette then `Settings sync: Show synced data`
4. Scroll to an old `Keyboard shortcuts` entry to see the diff -> Diff is empty

To add some details to my case, I recently migrated from Windows to Linux, I don't know if that's relevant here...
Kind of sad now because I spent some time setting some custom key bindings for each profile and now they're all gone. I don't have any physical backup of my `keybindings.json` files.

![image](https://user-images.githubusercontent.com/2572775/236306857-34fc5385-8bee-4d31-8a59-e136008dac9a.png)

**Comment by JUNGHUNKIM-7** [comment]
i had same issue too, because of switching to linux. i had to copy and paste all from window.

**Comment by MasterInQuestion** [comment]
"[github.dev](https://github.dev/)", I have all settings lost.

**Comment by jmevel** [comment]
Well, turns out: *It's not a bug, it's a feature !*

By default key bindings are specified **per platform** meaning an OS won't receive key bindings from another OS.
That's why I couldn't see anything in the `Show Synced Data` view because in the past when I was modifying my key bindings in Windows, the Linux key bindings were still untouched... (weird user experience in my opinion)

It's possible to turn this feature off by setting `"settingsSync.keybindingsPerPlatform":false` in your default `settings.json` file (not applicable in your profiles' settings.json files).

In the meantime I was able to retrieve my Windows keybindings from Linux by going into `~/.config/Code/user/sync` and copying the content of the different `lastSynckeybindings.json` files located in the sub directories (one for the default and one for each profile).

**Comment by exodus4d** [comment]
It seems like  manual changes in `C:\Users\[USER]\AppData\Roaming\Code\User\keybindings.json` do not have any effect because the file gets auto-updated just a few seconds after my changes and re-add the prev. deleted keybinding.

![GIF 05 05 2023 03-11-47](https://user-images.githubusercontent.com/9299033/236359963-acdcdd99-2541-4e2c-baa2-e41eab09d1d9.gif)

**Comment by jmevel** [comment]
> It seems like manual changes in `C:\Users\[USER]\AppData\Roaming\Code\User\keybindings.json` do not have any effect because the file gets auto-updated just a few seconds after my changes and re-add the prev. deleted keybinding.
> 
> Change `settingsSync.keybindingsPerPlatform: false` seems to fix my issue.
> 
> ![GIF 05 05 2023 03-11-47](https://user-images.githubusercontent.com/9299033/236359963-acdcdd99-2541-4e2c-baa2-e41eab09d1d9.gif) [ ![GIF 05 05 2023 03-11-47](https://user-images.githubusercontent.com/9299033/236359963-acdcdd99-2541-4e2c-baa2-e41eab09d1d9.gif) ](https://user-images.githubusercontent.com/9299033/236359963-acdcdd99-2541-4e2c-baa2-e41eab09d1d9.gif) [ ](https://user-images.githubusercontent.com/9299033/236359963-acdcdd99-2541-4e2c-baa2-e41eab09d1d9.gif)

Hum that's weird, I can't explain that. But at least you have a fix...

I'm closing this ticket because my issue is resolved, yours seems to be something different
