### ISSUE TITLE
VSCode crashes when expanding window with custom titlebar

### ISSUE THREAD

**Issue by bemyak** [microsoft/vscode#181503]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.78.0
- OS Version: Archlinux

Steps to Reproduce:

1. In Arch/Manjaro Linux install KDE and log into a Wayland session
2. Run `echo "--ozone-platform-hint=auto" > ~/.config/code-flags.conf`
3. Set VSCode setting `"window.titleBarStyle"` to `"custom"`
4. Run VSCode. If it launches minimized, maximize the window. Observe the crash.

Crashdump: [d10f0932-7345-4452-bd3a-21350040eae2.zip](https://github.com/microsoft/vscode/files/11397160/d10f0932-7345-4452-bd3a-21350040eae2.zip)

These lines appear in the terminal:
```
[0504/145950.931838:ERROR:elf_dynamic_array_reader.h(64)] tag not found
[0504/145950.933656:ERROR:elf_dynamic_array_reader.h(64)] tag not found
```

[Screencast_20230504_144028-2.webm](https://user-images.githubusercontent.com/6333105/236197800-3961ffcc-5b5d-4501-891e-1684c476625b.webm)

**Comment by dynobo** [comment]
Same issue, however, for me it only crashs when maximizing. The issue started to occur after install the update with Gnome 44.

**Comment by dvartic** [comment]
Can confirm the same problem occurs in Fedora 38, Gnome 44 and Wayland.

**Comment by deepak1556** [comment]
Merging to https://github.com/microsoft/vscode/issues/181533
