### ISSUE TITLE
Multi Cursor Paste Spread Mode doesn't work in insiders

### ISSUE THREAD

**Issue by mattico** [microsoft/vscode#181650]
Does this issue occur when all extensions are disabled?: **Yes**

- VS Code Version: 1.79-insider (user setup) 2c73d2651
- OS Version: Windows 11 x64 10.0.22621

Steps to Reproduce:

1. Type text.
2. Create multiple cursors across lines.
3. Copy (Control + C)
4. Paste (Control + V)

https://user-images.githubusercontent.com/853158/236515932-91b78f85-626b-4255-9b42-6315821b1c97.mp4

**Comment by eamodio** [comment]
Seeing the same -- this just broke VERY recently. Typing still works, but paste only pastes into the first cursor.

**Comment by fenvalle** [comment]
They make a break change and the new default is true. You should set **pasteAs** Parameter to false
(I will bring the correct parameter name)

**Comment by fenvalle** [comment]
editor.pasteAs.enabled

**Comment by gjsjohnmurray** [comment]
Maybe related to #181468

**Comment by mattico** [comment]
@fenvalle Thanks, that fixed it!

It looks like the paste as paste selector widget isn't implemented yet, or at least it's not showing for me despite being enabled. So that makes this especially confusing.

I'll consider this closed, though. Unfinished features are just part of the deal with insiders.

**Comment by eamodio** [comment]
FYI, even with `"editor.pasteAs.enabled": true` in today's insiders things are fixed.
