### ISSUE TITLE
Keyboard shortcut to Toggle Terminal to open Integrated Terminal NOT working in Insider 

### ISSUE THREAD

**Issue by rohan-paul** [microsoft/vscode#181622]
- VS Code Version: 
Version: 1.79.0-insider (user setup)
Commit: 2c73d2651cc525b27fc697b820743098a204ec01
Date: 2023-05-04T22:11:08.187Z
Electron: 22.4.8
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Windows_NT x64 10.0.22621
Sandboxed: Yes

- OS Version:  Windows 11

Steps to Reproduce:

1. Issue Keyboard shortcut of Ctrl+`
2. Its opening the Native Terminal

Getting error - "The terminal process "C:\Program Files\Git\git-bash.exe" terminated with exit code: 3221225786."

I have the same Keyboard shortcut and the same configurations in Preference (JSON file) in the stable vscode and there its working fine.

**Comment by meganrogge** [comment]
I cannot reproduce, so would recommend using the command `Toggle keyboard shortcuts troubleshooting` to figure out what's happening for you
