### ISSUE TITLE
[VSC-Web] [Suggestion] Settings Sync off should still load remote settings if no local configuration exists

### ISSUE THREAD

**Issue by MasterInQuestion** [microsoft/vscode#181688]
A recent change seems to cause the remote settings being no more retrieved if Settings Sync is off.
    And the default configuration is applied if no previous configuration (locally cached) available.
    Which would hardly make sense, and caused compatibility break. [ See: [https://github<i>.</i>com/microsoft/vscode/issues/181582#issuecomment-1535359487](https://github.com/microsoft/vscode/issues/181582#issuecomment-1535359487) ]

&#x2D;---

Version: 1.78.0
Commit: 252e5463d60e63238250799aef7375787f68b4ee
User Agent: Mozilla/5.0 (X11; Linux x86_64; rv:111.0) Gecko/20100101 Firefox/111.0
Embedder: github.dev

**Comment by sandy081** [comment]
Please file the issue against github / codespaces that enable this feature externally.

**Comment by MasterInQuestion** [comment]
I believe this applies to Settings Sync in general.
