### ISSUE TITLE
git not working properly since two or three days or so

### ISSUE THREAD

**Issue by vincolus** [microsoft/vscode#181696]
Type: <b>Bug</b>

git stage file button is greyed out after one git operation. it seems random which button is greyed out and which is not.
restarting vscode is helping to get it back working.

VS Code version: Code 1.78.0 (252e5463d60e63238250799aef7375787f68b4ee, 2023-05-03T20:09:00.748Z)
OS version: Windows_NT x64 10.0.19044
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 3600X 6-Core Processor              (12 x 3800)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.93GB (5.07GB free)|
|Process Argv|--crash-reporter-id 19bed334-2910-444f-bf4a-f8a4e585dab1|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-tailwindcss|bra|0.9.11
npm-intellisense|chr|1.4.4
file-tree-to-text-generator|d-k|1.4.0
vscode-html-css|ecm|1.13.1
prettier-vscode|esb|9.12.0
vscode-terminals|fab|1.15.0
copilot|Git|1.85.75
copilot-labs|Git|0.12.791
l13-diff|L13|1.3.1
git-graph|mhu|1.30.0
vscode-docker|ms-|1.25.0
vscode-language-pack-de|MS-|1.78.2023050309
docker-compose|p1c|0.3.5
synthwave-vscode|Rob|0.1.15
svelte-vscode|sve|107.4.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscorecescf:30445987
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
vscccc:30610679
2e4cg342:30602488
pyind779:30671433
89544117:30613380
pythonsymbol12:30671437
6233i204:30730053
azdwalk:30721579
pythonms35:30701012
pythonfmttext:30731395
pythoncmvfstrcf:30731970
fixshowwlkth:30730052
showsbindicator:30730056
pythongtdpathcf:30731979

```

</details>

**Comment by mmomtchev** [comment]
Confirm, same version, both Linux and Windows. Staging through `Stage All Changes`  works fine, but individual files are randomly greyed out.

**Comment by Dreamer269** [comment]
I can confirm this issue too. Since v1.78.0 the button is greyed out randomly. However I can still stage a file by using the right click menue.
