### ISSUE TITLE
A filesystem provider for the scheme 'userdataprofileexport' is already registered.

### ISSUE THREAD

**Issue by tekumara** [microsoft/vscode#181687]
Type: <b>Bug</b>

`Create from Current Profile` errors with 

> A filesystem provider for the scheme 'userdataprofileexport' is already registered.

VS Code version: Code 1.78.0 (Universal) (252e5463d60e63238250799aef7375787f68b4ee, 2023-05-03T20:11:00.813Z)
OS version: Darwin arm64 22.4.0
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|13, 10, 12|
|Memory (System)|32.00GB (0.06GB free)|
|Process Argv|--crash-reporter-id 1420092c-d4ca-4cab-85bb-af47402199b1|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (51)</summary>

Extension|Author (truncated)|Version
---|---|---
acorn|Aco|0.5.0
vscode-sql-formatter|adp|1.4.4
TabOut|alb|0.2.2
tsl-problem-matcher|amo|0.6.2
indent-jump|aPi|1.0.1
ruff|cha|2023.12.0
codeium|Cod|1.2.15
vscode-markdownlint|Dav|0.49.0
vscode-eslint|dba|2.4.0
gitlens|eam|13.5.0
prettier-vscode|esb|9.12.0
hadolint|exi|1.1.2
shell-format|fox|7.2.5
vscode-pull-request-github|Git|0.62.0
go|gol|0.38.0
terraform|has|2.26.0
vscode-test-explorer|hbe|2.21.1
git-graph|mhu|1.30.0
dotenv|mik|1.0.1
autoflake-extension|mik|1.0.4
python|ms-|2023.8.0
vscode-pylance|ms-|2023.5.10
jupyter|ms-|2023.4.1011241018
jupyter-keymap|ms-|1.1.0
jupyter-renderers|ms-|1.0.15
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-slideshow|ms-|0.1.5
remote-containers|ms-|0.292.0
remote-ssh|ms-|0.100.0
remote-ssh-edit|ms-|0.84.0
makefile-tools|ms-|0.7.0
remote-explorer|ms-|0.4.0
test-adapter-converter|ms-|0.1.7
vscode-marketplace-extension-browser|ms-|0.0.7
vsliveshare|ms-|1.0.5864
cuelang|nic|0.0.1
autodocstring|njp|0.6.1
excalidraw-editor|pom|3.5.1
vscode-yaml|red|1.12.2
rust-analyzer|rus|0.3.1498
cody-ai|sou|0.0.10
code-spell-checker|str|2.20.4
vscode-rust-test-adapter|Swe|0.11.0
even-better-toml|tam|0.19.0
typos-vscode|tek|0.1.1
tiltfile|til|0.0.3
shellcheck|tim|0.32.5
vscode-mermaid-editor|tom|0.18.1
vscode-lldb|vad|1.9.1
volar|Vue|1.6.4
vscode-open-in-github|ziy|1.3.6

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
3biah626:30602489
pyind779:30671433
f6dab269:30613381
pythonsymbol12:30671437
6233i204:30730053
azdwalk:30721579
pythonms35:30701012
pythonfmttext:30731395
fixhidewlkth:30730051
showsbindicator:30730056

```

</details>

**Comment by gjsjohnmurray** [comment]
Please use the Start Extension Bisect command to investigate whether the problem is being caused by one of your extensions.

**Comment by tekumara** [comment]
Seems to have vanished after restarting.

**Comment by TomasHubelbauer** [comment]
This also happened for me and was also fixed by a restart.
