### ISSUE TITLE
Command Palette Disappears In New Window After Welcome Page Gets Rendered

### ISSUE THREAD

**Issue by stagefright5** [microsoft/vscode#181660]
Does this issue occur when all extensions are disabled?: **Yes**

- VS Code Version: 1.79.0-insider
- Commit: 2c73d2651cc525b27fc697b820743098a204ec01
- Date: 2023-05-04T22:11:08.187Z
- Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Code-Insiders/1.79.0-insider Chrome/108.0.5359.215 Electron/22.4.8 Safari/537.36

Steps to Reproduce: (Video attached)

1. Open a new VS Code window
2. As and when the window is open, press `Ctrl + R` to open recent folders top panel
3. The panel disappears when the `Welcome` page is rendered

https://user-images.githubusercontent.com/15051871/236548204-d630474b-bf6f-4b3e-9395-35035a0e39ad.mp4

**Comment by stagefright5** [comment]
This issue does not occur when the setting `"workbench.startupEditor": "none"` is set

**Comment by jespertheend** [comment]
I reported this as well three months ago: #173792
I don't understand why there's so few users with this issue. Opening a recent folder is basically the first thing you do after launching vscode.

**Comment by jespertheend** [comment]
I have but only because of this issue

**Comment by bpasero** [comment]
I think the welcome view grabs focus when it opens after quick open has been opened and thus quick open closes. You can configure in settings to keep quick open open in that case: `workbench.quickOpen.closeOnFocusLost`

**Comment by TylerLeonhardt** [comment]
I feel like a better approach for this one is:
1. to understand why the Welcome page opens so late.
2. to understand why the Welcome page steals focus

I think the first would be a better one to focus on. My expectation would be that the Welcome page opens with VS Code, rather than being delayed.

**Comment by bhavyaus** [comment]
The welcome page relies on the gallery service, experiment service which could be slow to startup. Im working on fix to only load the welcome page once all the services are readied. 
The issue of it stealing focus after load still needs to be fixed though.
