### ISSUE TITLE
Unable debug dapr application written by c#

### ISSUE THREAD

**Issue by BurningTeng** [microsoft/vscode#181605]
- VS Code Version:  1.78.0
- OS Version: Win10 

Steps to Reproduce:

1. c# code as below:
`// See https://aka.ms/new-console-template for more information
Console.WriteLine("Hello, World!");
Console.WriteLine("Hello world".Reverse());
`
2. lauch.json
`{
    "version": "0.2.0",
    "configurations": [
        {
            // Use IntelliSense to find out which attributes exist for C# debugging
            // Use hover for the description of the existing attributes
            // For further information visit https://github.com/OmniSharp/omnisharp-vscode/blob/master/debugger-launchjson.md
            "name": ".NET Core Launch (dapr)",
            "type": "coreclr",
            "request": "launch",
            "preLaunchTask": "dapr-debug-clr",
            // If you have changed target frameworks, make sure to update the program path.
            "program": "${workspaceFolder}/bin/Debug/net7.0/test.dll",
            "args": [],
            "cwd": "${workspaceFolder}",
            // For more information about the 'console' field, see https://aka.ms/VSCode-CS-LaunchJson-Console
            "console": "internalConsole",
            "stopAtEntry": false
        }
    ]
}`

3. tasks.json
`{
    "version": "2.0.0",
    "tasks": [
        {
            "label": "build",
            "command": "dotnet",
            "type": "process",
            "args": [
                "build",
                "${workspaceFolder}/test.csproj",
                "/property:GenerateFullPaths=true",
                "/consoleloggerparameters:NoSummary"
            ],
            "problemMatcher": "$msCompile"
        },
        // {
        //     "label": "publish",
        //     "command": "dotnet",
        //     "type": "process",
        //     "args": [
        //         "publish",
        //         "${workspaceFolder}/test.csproj",
        //         "/property:GenerateFullPaths=true",
        //         "/consoleloggerparameters:NoSummary"
        //     ],
        //     "problemMatcher": "$msCompile"
        // },
        // {
        //     "label": "watch",
        //     "command": "dotnet",
        //     "type": "process",
        //     "args": [
        //         "watch",
        //         "run",
        //         "--project",
        //         "${workspaceFolder}/test.csproj"
        //     ],
        //     "problemMatcher": "$msCompile"
        // },
        {
            "label": "dapr-debug-clr",
            "command": "daprd",
            "args": [
                "--app-id", "console-http",
                "--app-port", "7001",
                "--log-level", "info"
            ],
            "isBackground": true,
            "group": {
                "kind": "build",
                "isDefault": true
            },
            "options": {
                "cwd": "${workspaceFolder}"
            },
            "dependsOn": [
                "build"
            ]
        }
    ]
}`

4. Run and debug, dapr can start success, but c# application can not start and I can not debug the c# application.

**Comment by roblourens** [comment]
Please file an issue with more details on the C# debug extension
