### ISSUE TITLE
V1.78.0 can't hover to statusBarItem tooltip

### ISSUE THREAD

**Issue by tjx666** [microsoft/vscode#181606]
https://user-images.githubusercontent.com/41773861/236374251-2c337fd7-1936-4e54-9f3f-b52e741ab27f.mov

problem extension: https://github.com/tjx666/reload-can-solve-any-problems

```
Version: 1.78.0 (Universal)
Commit: 252e5463d60e63238250799aef7375787f68b4ee
Date: 2023-05-03T20:11:00.813Z
Electron: 22.4.8
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Darwin x64 22.4.0
Sandboxed: No
```

**Comment by AlencarGabriel** [comment]
I have the same problem. I thought it was associated with my extension, but apparently not.

This behavior does not happen with the GitLens extension

**Comment by tjx666** [comment]
@AlencarGabriel This issue only happen to stausBarItem at left side

**Comment by AlencarGabriel** [comment]
> I have the same problem in tooltips of TreeItem. I thought it was associated with my extension, but apparently not.
> 
> This behavior does not happen with the GitLens extension.

![tooltip](https://user-images.githubusercontent.com/10109480/236569614-d83b31a7-9633-4df1-a667-78adc8284296.gif)

**Comment by tjx666** [comment]
@sbatten this issue should be mark new release label

**Comment by tjx666** [comment]
@sandy081 can you help look into this issue?

**Comment by Tyriar** [comment]
Wasn't this always like this? It's not hoverable in 1.78.0 either.

You can hold alt to hover it though which is a common feature of hovers (outside the editor) https://code.visualstudio.com/docs/editor/accessibility#_hover-accessibility

**Comment by usernamehw** [comment]
@Tyriar **1.78** is the current VSCode version - the one where it broke. **1.77** and below works properly.

**Comment by Tyriar** [comment]
Doh, checking an older one 🤦

**Comment by aeschli** [comment]
Looks like the hover only sticks if there are textual links in it. Example is the hover on the `{}` next to the language selector.
I didn't change anything in the hover area recently.

**Comment by Tyriar** [comment]
@aeschli that's how it used to work, it doesn't anymore. @TylerLeonhardt and I made some changes around this recently, it was probably us.

**Comment by Tyriar** [comment]
> I have the same problem in tooltips of TreeItem. I thought it was associated with my extension, but apparently not.

@AlencarGabriel this is by design if the content does not contain any links. Hold alt to "lock" any hover

**Comment by Tyriar** [comment]
This is happening because you're using an anchor tag, a change was made recently to only force hovering when the hover contained "](". I'll add an anchor tag check.

**Comment by AlencarGabriel** [comment]
> > I have the same problem in tooltips of TreeItem. I thought it was associated with my extension, but apparently not.
> 
> @AlencarGabriel this is by design if the content does not contain any links. Hold alt to "lock" any hover

@Tyriar  Curious, because in these tooltips I never used links (html or md) and it worked. Recently this behavior started

**Comment by Tyriar** [comment]
@AlencarGabriel previously the logic would disable hide on hover if it was any markdown string which is why it was like that. If the user wants to copy information they can do so by [holding alt](https://code.visualstudio.com/docs/editor/accessibility#_hover-accessibility). I know it's not the most discoverable but it's intuitive once you know about it.

It's a harder problem than you might expect because if it didn't behave like this we would get the opposite type of issue where hovers are really annoying because they don't dismiss. So we don't hide hovers on mouse over only when there's a high chance of interaction.
