### ISSUE TITLE
Vscode markdown inserts a video file to play without sound and the video cannot be full-screen and zoomed out,...

### ISSUE THREAD

**Issue by zhouxinghong** [microsoft/vscode#181616]
Vscode markdown inserts a video file to play without sound and the video cannot be full-screen and zoomed out, nor can it be fast-forwarded or rewinded during playback
Windows10
VsCode 1.78
Now that the video playback function has been introduced, it is still hoped that the video playback function can be improved.

**Comment by mjbvz** [comment]
You can change the html that's inserted for that. We insert reasonably conservative defaults but obviously can't handle every use case out of the box

**Comment by zhouxinghong** [comment]
Many third-party markdown editors already support audio and video playback. I remember that I asked you this question a few years ago, but you said that it would not support video playback, but now it supports video playback, so it is best to support it General audio and video playback functions.

**Comment by zhouxinghong** [comment]
Or you provide an extension so that users can fully enable audio and video playback when writing markdown files. This is also a very good solution!

**Comment by zhouxinghong** [comment]
This feature is so well done! Still hope you can perfect it!

**Comment by zhouxinghong** [comment]
Or you can also provide APIs related to video playback for users to expand and implement it, which is also great!
