### ISSUE TITLE
The Intellisense is incorrect when adding configuration in launch.json file

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode#181615]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.78.0
- OS Version: Win 10

**Steps to Reproduce:**
1. Create a .NET core project with the command "dotnet new mvc".
2. Open the project in Visual Studio Code.
3. Click "Yes" in the below notification.
![image](https://user-images.githubusercontent.com/45614674/236405310-2cb2bc06-769e-4f28-8af9-f3cb32b913c7.png)
4. Open the launch.json file.
5. Click "Add Configuration..." button in the bottom of launch.json file or "VS Code Run -> Add Configuration...".
6. Check the Intellisense.

**Expect:**
The Intellisense shows like below.
![image](https://user-images.githubusercontent.com/45614674/236406247-9122a934-ab33-4833-ad9f-9cf044ca55d5.png)

**Actual:**
The Intellisense is incorrect.
![image](https://user-images.githubusercontent.com/45614674/236406356-fabc0dae-699a-4bbe-bf46-2a01db4683a9.png)

**More Info:**
1. This issue still reproduces in the VS Code Insiders build 1.79.0.
2. This issue does not reproduce in VS Code 1.77.3.

**Comment by Teassassin** [comment]
I haven encountered the same issue, and I'm sure this happened when I upgrade VSCode to new version 1.78.0.

**Comment by xidianzhangjun** [comment]
Me too. When will this bug be fixed?

**Comment by rickstaa** [comment]
I am also effected. Will manually add the right configuration for now (See https://code.visualstudio.com/docs/nodejs/nodejs-debugging#_attach-to-node-process-action):

```json
{
  "name": "Attach to Process",
  "type": "node",
  "request": "attach",
  "processId": "${command:PickProcess}"
}
```

**Comment by roblourens** [comment]
Closing for https://github.com/microsoft/vscode/issues/181641
