### ISSUE TITLE
VS Code starting up slowly

### ISSUE THREAD

**Issue by VinayRayana** [microsoft/vscode#181609]
[prof-tZWD4QER.main.cpuprofile.txt](https://github.com/microsoft/vscode/files/11403241/prof-tZWD4QER.main.cpuprofile.txt)

[Startup Performance Details.txt](https://github.com/microsoft/vscode/files/11403270/Startup.Performance.Details.txt)

[prof-tZWD4QER.renderer.cpuprofile.txt](https://github.com/microsoft/vscode/files/11403244/prof-tZWD4QER.renderer.cpuprofile.txt)

**Comment by tamuratak** [comment]
McAfee Antivirus might be the cause. See https://github.com/microsoft/vscode/issues/178733#issuecomment-1500812938

**Comment by VinayRayana** [comment]
> McAfee Antivirus might be the cause. See [#178733 (comment)](https://github.com/microsoft/vscode/issues/178733#issuecomment-1500812938)

Thanks For Your Reply, I tried that but no use.
