### ISSUE TITLE
Color Theme 'Dark (Visual Studio)' Breaks Syntax Highlighting

### ISSUE THREAD

**Issue by RexGreenway** [microsoft/vscode#181663]
Type: <b>Bug</b>

## Test Steps
Completed using VS Code - Insiders
- On Fresh Install of VS Code (Post Clean Uninstall and Computer Restart)
- Open fresh project.
- Code shows hightlighting only when using Dark Modern
- Switching theme "turns on & off" highlighting present.
- Tested with Python and JavaScript Syntax

## Suggested Cause
I believe that with the update and the new Dark Modern theme as Default, highlighting for the old theme has broken.

## Images
<img width="986" alt="Screenshot 2023-05-05 at 21 03 29" src="https://user-images.githubusercontent.com/74911207/236559410-5c2c7f60-b8b7-4896-aefc-ca5d1432d3ca.png">
<img width="986" alt="Screenshot 2023-05-05 at 21 03 24" src="https://user-images.githubusercontent.com/74911207/236559479-920c574f-e62b-4d22-b9d0-dccaed0a5c33.png">
<img width="986" alt="Screenshot 2023-05-05 at 21 03 11" src="https://user-images.githubusercontent.com/74911207/236559497-15c5b6aa-a1de-4de6-9e14-be426a21243e.png">
<img width="986" alt="Screenshot 2023-05-05 at 21 03 04" src="https://user-images.githubusercontent.com/74911207/236559514-e00e967f-a037-4b6b-9aed-51fb71b0f5b4.png">

VS Code version: Code - Insiders 1.79.0-insider (Universal) (2c73d2651cc525b27fc697b820743098a204ec01, 2023-05-04T22:14:17.675Z)
OS version: Darwin arm64 22.4.0
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M2 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|1, 2, 2|
|Memory (System)|8.00GB (0.36GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythontb:30258533
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscod805cf:30301675
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30404738
cppdebug:30492333
vsclangdf:30492506
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30618038
pylantcb52:30590116
pyind779:30611226
pythonsymbol12:30651887
showlangstatbar:30725951
azdwalk:30721579
pythonms35:30671666
03d35959:30680466
ecj1e332:30687743
pythonfmttext:30716741
pythoncmvfstr:30726892
9b8hh234:30694863
fixshowwlkth:30724385
hidesbindicator:30724476
pythongtdpath:30726887

```

</details>

**Comment by RexGreenway** [comment]
Further testing shows that it also occurs with Golang:
<img width="367" alt="Screenshot 2023-05-05 at 21 26 31" src="https://user-images.githubusercontent.com/74911207/236562393-636b7f99-0230-48bf-9bf5-38830bbf1f66.png">
<img width="367" alt="Screenshot 2023-05-05 at 21 26 15" src="https://user-images.githubusercontent.com/74911207/236562444-f2c38c42-b53e-47a0-a813-bd0115250cc7.png">

**Comment by leegodden** [comment]
Here too.Python syntax highlighting only work with Dark modern theme WTF vscode???

**Comment by Merded** [comment]
+1

**Comment by Merded** [comment]
+1, TypeScript

**Comment by onursahindur** [comment]
+1, Php

**Comment by bill876** [comment]
Have you tried `Dark+`?

Syntax highlighting works and I don't see differences in color compared to non-plus.

**Comment by NickKoz** [comment]
+ Terraform

**Comment by daviddossett** [comment]
Also, just to be 100% clear, are you sure you weren't using Dark+ before, not Dark (Visual Studio). Dark+ was the old default theme not the latter.

**Comment by matiasmarcodelpont** [comment]
For me, Dark + actually works correctly. Dark (Visual Studio) is breaking syntax highligh. This started happening after going back to this theme after trying out the new dark mode

**Comment by daviddossett** [comment]
`Dark (Visual Studio)` has different highlighting behavior than Dark+. The screenshots above look normal to me. My guess here is that you were looking at Dark+ before since that was the default.

**Comment by RexGreenway** [comment]
> `Dark (Visual Studio)` has different highlighting behavior than `Dark+`. The screenshots above look normal to me. My guess here is that you were looking at Dark+ before since that was the default. 
> 
> My understanding is that `Dark (Visual Studio)` is intended for Visual Studio users coming to VS Code who are used to the highlighting looking like that, especially for C#. @aeschli can confirm.

So, I do not know about anyone else or which theme was in fact being pointed to in the background but I know that 'Dark (Visual Studio)' has always been my colour theme. Up untill the recent update, with no changes on my end, this theme had syntax highlighting - for example: yellow text for Python functions.

**Comment by daviddossett** [comment]
Ok, I'll see if we can repro on our end and will report back. No changes to that theme were intended.

**Comment by aeschli** [comment]
Dark (Visual Studio) is much simpler and has no colors for variables and function references. Nothing changed there.

We don't automatically change your theme if you have `Dark (Visual Studio)` set in the settings. That only happens if you didn't had any theme configured, which defaulted to Dark+.

**Comment by RexGreenway** [comment]
Okay - I must've been mistaken. Thank you for the help.
