### ISSUE TITLE
File Explorer: First-letter navigation broken in last insider builds

### ISSUE THREAD

**Issue by Menelion** [microsoft/vscode#181635]
Type: <b>Bug</b>

In latest insider builds, when you press Ctrl+Shift+E and get to the Explorer tab, first-letter navigation is broken. I.e., if there is a large project with folders and files, it's convenient to use keyboard to input first letters of the file name to navigate. This used to work, and in the latest build it stopped working which is really annoying, especially for larger projects.

VS Code version: Code - Insiders 1.78.0-insider (e410e7c66e7ce5c6bc31f73150d66857804a0ee9, 2023-04-28T12:24:04.788Z)
OS version: Windows_NT x64 10.0.19045
Modes:
Sandboxed: Yes
Remote OS version: Darwin x64 19.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz (4 x 2904)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.89GB (21.01GB free)|
|Process Argv|--crash-reporter-id 45b8c0ea-90b0-46d5-b814-b57a23d72992|
|Screen Reader|yes|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: mac|
|OS|Darwin x64 19.2.0|
|CPUs|Intel(R) Core(TM) i7-8700B CPU @ 3.20GHz (12 x 3200)|
|Memory (System)|32.00GB (20.39GB free)|
|VM|38%|
</details><details><summary>Extensions (19)</summary>

Extension|Author (truncated)|Version
---|---|---
remote-ssh|ms-|0.100.0
remote-ssh-edit|ms-|0.84.0
remote-wsl|ms-|0.78.4
vscode-remote-extensionpack|ms-|0.24.0
remote-explorer|ms-|0.4.0
remote-server|ms-|1.1.0
vscode-twig-pack|baj|1.1.0
json-tree-view|Cha|2.6.0
gitlens|eam|13.5.0
php-intellisense|fel|2.3.14
php-symbols|lin|2.1.0
bash-ide-vscode|mad|1.36.0
php-constructor|Meh|0.1.2
vsliveshare|ms-|1.0.5864
vsliveshare-audio|ms-|0.1.93
vsliveshare-pack|ms-|0.4.0
vscode-php-getters-setters|php|1.2.3
xml-toolkit|SAP|1.1.0
php-debug|xde|1.32.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256197
vslsvsres303:30308271
pythontb:30258533
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscod805cf:30301675
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30404738
cppdebug:30492333
vsclangdf:30492506
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30618038
pylantcb52:30590116
pyind779:30611226
pythonsymbol12:30651887
6233i204:30725950
azdwalk:30721579
pythonms35:30671666
03d35959:30680466
24365598:30687740
pythonfmttext:30716741
pythoncmvfstr:30726892
fixshowwlkth:30724385
showsbindicator:30724477
pythongtdpath:30726887

```

</details>

**Comment by gjsjohnmurray** [comment]
Your Insiders looks out of date. Please update and retest.

**Comment by Menelion** [comment]
Fixed in the latest Insider build indeed.
