### ISSUE TITLE
Add Configuration shows word suggestions not debug configurations

### ISSUE THREAD

**Issue by buonan** [microsoft/vscode#181659]
Type: <b>Bug</b>

1. mkdir temp
2. cd temp
3. npm init -y
4. touch index.js
5. code --disable-extensions .
6. click the 'Run and Debug'
7. add create launch.json
8. pick NodeJS
9. click 'Add Configurations'

Bug: shows word suggestions
Expected: 'Attach to process, etc'

VS Code version: Code 1.78.0 (252e5463d60e63238250799aef7375787f68b4ee, 2023-05-03T20:11:00.813Z)
OS version: Darwin x64 22.4.0
Modes:
Sandboxed: No
<img width="1222" alt="Screenshot 2023-05-05 at 11 42 28 AM" src="https://user-images.githubusercontent.com/4878081/236542284-c7302913-7b5e-4f6f-bb90-3690c64645eb.png">

**Comment by xidianzhangjun** [comment]
Me too.

**Comment by jacobbogers** [comment]
same issue, whats going on here
![screenshot-broken-vscode](https://github.com/microsoft/vscode/assets/896018/6db79145-5091-4679-a680-0aac506b97f8)

**Comment by roblourens** [comment]
I believe this is fixed in 1.78.2 and insiders, can anyone confirm?

**Comment by roblourens** [comment]
Closing for https://github.com/microsoft/vscode/issues/181641

**Comment by buonan** [comment]
> I believe this is fixed in 1.78.2 and insiders, can anyone confirm?

Looks good for me!

<img width="789" alt="Screenshot 2023-05-11 at 4 51 06 PM" src="https://github.com/microsoft/vscode/assets/4878081/8932aa52-1492-453e-a970-57e95d0d25b0">
