### ISSUE TITLE
Slow startup

### ISSUE THREAD

**Issue by ghadwalsunil** [microsoft/vscode#181670]
Whenever I start the vscode, it takes a lot of time. I am not even opening a folder. I tried uninstalling and reinstalling, removing all extensions and nothing helps. When I try opening folder, it takes a lot of time, and sometimes a popup appears saying that the window is not responding, even though it is still loading in the background.
Here are my startup performance stats-
## Performance Marks

| What                                                            | Duration | Process                   | Info                                                       |
| --------------------------------------------------------------- | -------- | ------------------------- | ---------------------------------------------------------- |
| start => app.isReady                                            | 7643     | [main]                    | initial startup: true                                      |
| nls:start => nls:end                                            | 0        | [main]                    | initial startup: true                                      |
| require(main.bundle.js)                                         | 80       | [main]                    | initial startup: true                                      |
| start crash reporter                                            | 7599     | [main]                    | initial startup: true                                      |
| serve main IPC handle                                           | 2        | [main]                    | initial startup: true                                      |
| create window                                                   | 24       | [main]                    | initial startup: true, state: 0ms, widget: 14ms, show: 9ms |
| app.isReady => window.loadUrl()                                 | 132      | [main]                    | initial startup: true                                      |
| window.loadUrl() => begin to require(workbench.desktop.main.js) | 22387    | [main->renderer]          | NewWindow                                                  |
| require(workbench.desktop.main.js)                              | 247      | [renderer]                | cached data: YES, node_modules took 0ms                    |
| wait for window config                                          | 2        | [renderer]                | -                                                          |
| init storage (global & workspace)                               | 24       | [renderer]                | -                                                          |
| init workspace service                                          | 22       | [renderer]                | -                                                          |
| register extensions & spawn extension host                      | 298      | [renderer]                | -                                                          |
| restore viewlet                                                 | 0        | [renderer]                | -                                                          |
| restore panel                                                   | 0        | [renderer]                | -                                                          |
| restore & resolve visible editors                               | 12       | [renderer]                | 1: workbench.editors.gettingStartedInput                   |
| overall workbench load                                          | 224      | [renderer]                | -                                                          |
| workbench ready                                                 | 30667    | [main->renderer]          | -                                                          |
| renderer ready                                                  | 510      | [renderer]                | -                                                          |
| shared process connection ready                                 | 0        | [renderer->sharedprocess] | -                                                          |
| extensions registered                                           | 31083    | [renderer]                | -                                                          |

Thank you

**Comment by subrat09-subrat** [comment]
Same problem here

**Comment by tamuratak** [comment]
McAfee Antivirus might be the cause. See https://github.com/microsoft/vscode/issues/178733#issuecomment-1500812938

**Comment by ghadwalsunil** [comment]
I added the code.exe file to the exception list and it worked. Thanks!
