### ISSUE TITLE
Visual studio slow to start

### ISSUE THREAD

**Issue by GervitKT** [microsoft/vscode#181626]
1. :warning: We have copied additional data to your clipboard. Make sure to **paste** here. :warning:
1. :warning: Make sure to **attach** these files from your *home*-directory: :warning:
-`prof-NE9XaEld.main.cpuprofile.txt`
[prof-NE9XaEld.main.cpuprofile.txt](https://github.com/microsoft/vscode/files/11406239/prof-NE9XaEld.main.cpuprofile.txt)

-`prof-NE9XaEld.renderer.cpuprofile.txt`
[prof-NE9XaEld.renderer.cpuprofile.txt](https://github.com/microsoft/vscode/files/11406240/prof-NE9XaEld.renderer.cpuprofile.txt)

**Comment by jrieken** [comment]
Takes ~5sec to start the crash reporter...

<img width="690" alt="Screenshot 2023-05-09 at 08 22 31" src="https://user-images.githubusercontent.com/1794099/237011243-3a7272fe-db53-42e3-9e0f-4df69228577b.png">

**Comment by GervitKT** [comment]
So how do I fix this??

**Comment by jrieken** [comment]
@GervitKT This could be caused by AV software, esp by McAffee. Any an chance you are using this or any chance of excluding VS Code from you AV software?

**Comment by GervitKT** [comment]
You were right. I have excluded code.exe from McAffee and it works like a charm now. Thanks for the help!
