### ISSUE TITLE
[VSC-Web] ["github.dev"] Settings Sync inconsistency for GitHub options

### ISSUE THREAD

**Issue by MasterInQuestion** [microsoft/vscode#181685]
"Settings Sync: Turn on Settings Sync..." -> "Select an account to sign in":
    At this interface hitting 【Enter】 with highlight on a GitHub option, seems to produce different result vs. clicking on the very option:
    |&#x2A;| 【Enter】 would attempt to open a pop-up window with current URL ("https://github.dev/..."), which seems to regardless fail with an "Error while turning on Settings Sync. Failed to authenticate to Settings Sync." in "Notifications".
    |&#x2A;| Clicking would open a new window at [ [https://github.com/codespaces/allow_settings_sync?](https://github.com/codespaces/allow_settings_sync?) ], which seems to work; but would cause a reload of the editor page upon closing.

    This feels like a regression of recent update. (cannot reckon exact details)

&#x2D;---

Version: 1.78.0
Commit: 252e5463d60e63238250799aef7375787f68b4ee
User Agent: Mozilla/5.0 (X11; Linux x86_64; rv:111.0) Gecko/20100101 Firefox/111.0
Embedder: github.dev

**Comment by sandy081** [comment]
This is github/codespaces related. Please file issue against codespaces. Thanks.

**Comment by MasterInQuestion** [comment]
Could you please ensure whether this would not affect other Sync related options (like Microsoft ones).
    I don't have related accounts thus cannot test.
    Thanks.
