### ISSUE TITLE
Add function to learn current code format style before format

### ISSUE THREAD

**Issue by ruifeng96150** [microsoft/vscode#181675]
Type: <b>Feature Request</b>

When opening other JavaScript projects, only a small piece of code was changed, but after formatting, there were many changes. Such as multiple spaces, line breaks, etc. After submitting the code, there are too many modification records, making it difficult to compare what you have truly changed.

So I want to add such a feature. Before formatting, I can ask the software to learn the current code style first (because it is also troublesome to manually set code format style, and many times I don't know how to set it), and now formatting, we can keep the original style and make us easier to find what we commit.

VS Code version: Code 1.78.0 (252e5463d60e63238250799aef7375787f68b4ee, 2023-05-03T20:09:00.748Z)
OS version: Windows_NT x64 10.0.19044
Modes:
Sandboxed: Yes

**Comment by gjsjohnmurray** [comment]
Have you evaluated https://code.visualstudio.com/updates/v1_49#_only-format-modified-text yet?

**Comment by ruifeng96150** [comment]
Thanks, It's also works for me.
