### ISSUE TITLE
Ability to use a custom profile as a default profile

### ISSUE THREAD

**Issue by nickfan** [microsoft/vscode#181677]
![image](https://user-images.githubusercontent.com/100613/236593453-8d10c51e-9be1-4b20-99b0-bda56e19265d.png)

In VSCode, the Default Profile cannot be **deleted**, **renamed**, or **replaced**. It is hoped that a feature can be provided to use a newly created Profile to replace the Default Profile, or to allow deletion and renaming of the Default Profile, and set the newly created Profile as the default Profile.

**Comment by sandy081** [comment]
Can you please provide the usecase why you want a custom default profile?

**Comment by nickfan** [comment]
When I first used vscode, the Default Profile tried installed and configured too many messy extensions and settings. Now it has been split into grouped profiles according to needs, but the Default Profile cannot be deleted or not set as the default option.

**Comment by nickfan** [comment]
and when you run command  code xxx.txt from new path, it'll use the 'Default profile' not my recent used profile.

**Comment by sandy081** [comment]
So you want to use a custom profile to be opened by default always? Is it for files only or also when you open folders?

**Comment by nickfan** [comment]
also when i open folders
Or in another way, use the custom PROFILE settings and extensions etc. to replace the 'Default Profile' setup.

**Comment by nickfan** [comment]
May I inquire if there has been any progress regarding the current issue?

**Comment by OldStarchy** [comment]
@sandy081 Use case here, I have a computer setup on which I am unable to use certain extensions, so I created a profile for use on this computer in which those extensions are disabled, I was hoping to set it as the default profile for this computer.

Eg. I don't need the unity debugger extension on my work computer, and I don't need Vue on my home computer.

It might be possible to manage this with the "install (do not sync)" option, but for that I think I'd need to uninstall all the extensions, then go home and install them all again. It would also then not sync those extensions to my laptop.

**Comment by ArnieGA** [comment]
@sandy081 Respectfully, it is just a basic user experience update that doesn't necessarily require a specific use case. The user should be able to arbitrarily set any profile as the default profile, at any given moment. Today I want "Profile A" to be the default profile. Tomorrow, or 15 minutes later, or a year from now, or seconds afterwards, I want "Profile <X>" to be the default one. It shouldn't require a special use case.

Thanks.

**Comment by asherber** [comment]
Following up on @OldStarchy 's comment -- what would be great is the ability to set a default custom profile per machine.

My Default profile has just a few extensions and basic settings -- things that I would want to include in any child profile and use no matter what. Then I have a Home profile and and a Work profile. What I'd like to be able to do (and I think this is what @OldStarchy is asking for as well) is set my Home profile as default on my home machine and my Work profile as default on my work machine. Otherwise, every time I open a new Code window that's not tied to a workspace, I need to manually switch to the appropriate profile.

**Comment by gjsjohnmurray** [comment]
At the moment, if you launch VS Code from the command line and specify the `--profile "MyProfile"` you will get an empty (i.e. no-folder) workspace.

@sandy081 if we were able to set a `profile` property in argv.json and have VS Code respect this, maybe that would help some folk. I guess the argv.json value should only be used when an empty workspace is opening, otherwise we'd lose the existing ability to set the profile for a folder / workspace and have it use that profile whenever it opens.

**Comment by nickfan** [comment]
May I ask if there is any progress at the moment?

Is it possible to modify/overwrite/delete the Default Profile in the current version?

**Comment by acoomans** [comment]
+1 would love to reset or import or delete the Default profile

**Comment by 1j01** [comment]
I have a "Journal" profile with only minimal extensions for markdown, spellcheck, etc.
My "Default" profile has many extensions, including Copilot, which I wouldn't feel comfortable using for journaling.
I always have a Journal window open, so any time I open a new folder, it defaults to the Journal profile.
I would love it if I could set the "Default" profile as default. The heuristic of "last used" is always wrong for me.
In my use case, I would prefer the default profile selection to be synced, though I wouldn't mind configuring this one thing when setting up a new computer — that is, I would rather have the feature even if it's per-computer.

**Comment by KubasuIvanSakwa** [comment]
Can I get assigned to this issue if still open

**Comment by AWenmanFK** [comment]
> Can you please provide the usecase why you want a custom default profile?

Are you being serious????

**Comment by Adiiieee** [comment]
is this issue fixed? @sandy081

**Comment by Adiiieee** [comment]
I have one extension in my default profile, which works only for linux, so I can't use default profile for mac. There should be a option to set custom profile as default, I mean this is pretty basic feature.

**Comment by jez9999** [comment]
> Can you please provide the usecase why you want a custom default profile?

When you use VS Code on a new machine, you used to be able to export the Default profile and import it to the new one, overwriting the Default profile.  For some reason you now can't do that, it won't let you do the overwrite.  So you need to import to a new profile and be able to set the new one as the startup profile.

**Comment by johannww** [comment]
@sandy081, I have another use case here. I sometimes work on projects on my phone and GitHub codespaces. I don't want my 5 billion extensions to be loaded in this environment. I want a simple instance of VSCode to load fast. But every time I create a codespace, I have to wait for the installation of many extensions. Only after everything is installed can I switch profiles, and this takes time.

**Comment by sandy081** [comment]
Ref - https://github.com/microsoft/vscode/issues/194105

Introduced a new setting to choose which profile to use for new windows / folders for those a profile is not associated.

![Image](https://github.com/microsoft/vscode/assets/10746682/5c911386-7e71-4583-9609-e94e78230d1a)

This supports most of the asks in this issue (There are asks which are not related/off-topic are not considered like replacing default profile).

In favour of the above setting, I am closing this issue. 

I would request users to check existing [issues](https://github.com/microsoft/vscode/issues?q=is%3Aopen+label%3Auser-profiles+label%3Afeature-request) for the new use cases, if you do not find one, please file a new feature request with proper reasoning

**Comment by sandy081** [comment]
Thanks for the feedback. Will take a note of it.

**Comment by AWenmanFK** [comment]
hey @sandy081, is this something that will be appearing after a future update? I can't see the segment in the settings anywhere:
![image](https://github.com/microsoft/vscode/assets/88448044/a5ba6676-6df3-436e-bbe8-34949ab5b648)

**Comment by sandy081** [comment]
@AWenmanFK Yes, this will be available in next release.

**Comment by murugappanrm** [comment]
@sandy081 
I may have very good usecase for overriding the default profile. I am a freelance developer and i do development work at my client's place who commonly give me a new Workstation to work. I need to set up the VS code in these PCs each time. When i set up VS code it creates a "dumb" profile with nothing much. Therefore i use my "template" profile and import. Previously i could override the default and i always do. Why? After i leave, the people at my clients would take over the workstation and also need all the setting i have imported for them and avoids them dumping vs code as useless and takes them back to their existing editor. By overriding the default profile, these people need not worry about which profile to use and makes them see the benefits of using VS Code.

I hope this help in further consideration on the request.

**Comment by murugappanrm** [comment]
@sandy081 , Thank you so much. The solutions stated there works great.
