### ISSUE TITLE
copy/past full line is broken

### ISSUE THREAD

**Issue by Jule-** [microsoft/vscode#181640]
Type: <b>Bug</b>

1. Open a file
2. Put the cursor in the middle of any line you want to duplicate (without selecting any character)
3. Hit Ctrl+C
4. Hit Ctrl+V

The line is pasted in place instead of being pasted above the active line.

- [x] I have tested with all extensions disabled

VS Code version: Code - Insiders 1.79.0-insider (2c73d2651cc525b27fc697b820743098a204ec01, 2023-05-04T22:12:16.054Z)
OS version: Linux x64 5.19.0-41-generic snap
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz (12 x 4299)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|3, 3, 3|
|Memory (System)|15.57GB (4.44GB free)|
|Process Argv|--no-sandbox --force-user-env --unity-launch|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details>

**Comment by KrisCarr** [comment]
Similar issue on macOS (M1) on Insiders build when Copy-pasting in-place.

- Highlight anything
- CMD + C
- CMD + V (while copied content is still highlighted)
- Nothing happens

Currently working around it by pressing right arrow first to de-highlight.

**Comment by seritools** [comment]
Similarly multi-cursor copy/pasting is broken (adds all lines to each cursor, even if the number of cursors match the number of lines). This seemed to have started at the same time, so adding it to this issue.

**Comment by nnmrts** [comment]
Yup, pasting in general is just broken unless you literally only paste a few characters while not having anything selected.

**Comment by nnmrts** [comment]
@Jule- @KrisCarr @seritools check out this: https://github.com/microsoft/vscode/issues/181650

you need to set "pasteAs" to false

why anyone would copy paste full lines differently and then thought it was a good idea to make this the default in vscode is beyond me but whatever, i hope this is not intentional

**Comment by Jule-** [comment]
@nnmrts Oh good catch, thank you so much!

I am closing this one then, but I hope the default has been reverted to what users are expecting for the stable channel future release.

**Comment by rsstiglitz** [comment]
@Jule- please reopen until it's clear this is intentional or an unfixed bug...whatever the "pasteAs" feature is supposed to be in the future, I don't think I'm the only one who doesn't expect it to be enabled by default
