### ISSUE TITLE
Revert change to always update status

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#181755]
Just saw https://github.com/microsoft/vscode/pull/180903, this goes against the design. It's meant to only add the status if it doesn't already exist, if the status changed then it should use a different id and/or remove the old status first.

**Comment by karrtikr** [comment]
@Tyriar I'm not clear on the solution. There's a limited number of Terminal Status IDs: https://github.com/microsoft/vscode/blob/9b322006a9f28e550c51223485c2f1d93e5bfcdb/src/vs/workbench/contrib/terminal/browser/terminalStatusList.ts#L21-L27

In this case status ID hasn't changed, it's still `EnvironmentVariableInfoChangesActive`, only the description which comes with it has updated.

**Comment by Tyriar** [comment]
@karrtikr working on it, I'll send a PR to you in a bit

**Comment by karrtikr** [comment]
### Verification steps:

Validate https://github.com/microsoft/vscode/issues/180851 still doesn't happen.
