### ISSUE TITLE
Reconsider using F10 for debugger step over, even with `isWeb`

### ISSUE THREAD

**Issue by rehmsen** [microsoft/vscode#181792]
We ran into this at Google:

Currently, VSCode will use `F10` (like many debuggers) for stepping over on Electron, but `Alt+F10` on Web. The rationale, according to the code comment, is that browsers will not allow you to bind F10:
https://github.com/microsoft/vscode/blob/60fe2d5970245742a89a0bdead58f0626d957f1c/src/vs/workbench/contrib/debug/browser/debugCommands.ts#L476

I believe that is not fully correct: 
* VSCode itself uses F10 (curiously exactly when in the browser), to focus the file menu: https://github.com/microsoft/vscode/blob/60fe2d5970245742a89a0bdead58f0626d957f1c/src/vs/workbench/browser/parts/titlebar/menubarControl.ts#L443 
* I changed the shortcut to F10 in the settings, and in my browser (Chrome on OS X) it worked fine - maybe it does not work on specific browsers?

@isidorn, you removed `F10` for step over on web in https://github.com/microsoft/vscode/commit/f0cf34e073bd506334185273cd78e9a5cd368be5 - do you recall the exact reason?
@sbatten, you added the `F10` for application menu on web - why is this only on web?

I would like to better understand if we can somehow make this work, as users generally expect `F10` to step over in debuggers, and having to type `Alt+F10` for step over, when e.g. step in is just `F11` is causing friction.

**Comment by rehmsen** [comment]
Besides the inconsistency between step in and step over shortcuts, and web and electron, another issue with `Alt+F10` is that this is "Toggle Maximization State" in Gnome: https://defkey.com/gnome-shortcuts#23614

**Comment by isidorn** [comment]
@rehmsen I do not remember the exact reason. It seems like some browsers do not support this.
Can you please try it out in Safari, Firefox, Edge and Chrome? And if it works across all browsers then maybe we can change this.

Though I leave the decision up to @roblourens who owns debug.

**Comment by rehmsen** [comment]
@roblourens If I could confirm that it works on the four mentioned browsers, would you be open to changing this?

**Comment by roblourens** [comment]
It works fine for me too in Edge on macOS. But yeah, if you could do a little testing in different browsers, and on Windows, I would set F10 by default. I suppose I have to keep alt+F10 as an alternate keybinding on web to not confuse people, hm

**Comment by sbatten** [comment]
It's not explicitly stated where added it in this issue https://github.com/microsoft/vscode/issues/82759, but I believe the only reason the menu focus F10 keybinding is web specific is because all other platforms had pre-existing methods that didn't work in web.

**Comment by roblourens** [comment]
Thanks for trying that. I would take a PR for it

**Comment by roblourens** [comment]
Thanks!
