### ISSUE TITLE
Can't open VSCode from WSL2 Debian 12

### ISSUE THREAD

**Issue by ViniciusBastosTR** [microsoft/vscode#181718]
- VSCode Version: 1.79.0
- Local OS Version: 22H2
- Remote OS Version: Debian GNU/Linux 12 (bookworm)
- Remote Extension/Connection Type: WSL

- Logs:

```text
vinicius@pc:~/repos/hub/next/devops$ code --version
/mnt/c/Users/userID/AppData/Local/Programs/Microsoft VS Code Insiders/bin/code-insiders: 61: /mnt/c/Users/userID/AppData/Local/Programs/Microsoft VS Code Insiders/Code - Insiders.exe: Exec format error
```
.bash_aliases

```bash
alias code='/mnt/c/Users/userID/AppData/Local/Programs/"Microsoft VS Code Insiders"/bin/code-insiders'
```

Steps to Reproduce:

1. Trying to open VSCode from WSL Linux Terminal
2. Get exec format error:
```bash
/mnt/c/Users/userID/AppData/Local/Programs/Microsoft VS Code Insiders/bin/code-insiders: 61: /mnt/c/Users/userID/AppData/Local/Programs/Microsoft VS Code Insiders/Code - Insiders.exe: Exec format error
```

**Comment by ViniciusBastosTR** [comment]
Able to solve it using this solution: https://github.com/microsoft/WSL/issues/9887#issuecomment-1516434388

**Comment by spd-asia** [comment]
> Able to solve it using this solution: [microsoft/WSL#9887 (comment)](https://github.com/microsoft/WSL/issues/9887#issuecomment-1516434388)

Upgraded to Debian 12. 
```bash
userID@pc:~/$ code --version
/mnt/c/Users/userID/AppData/Local/Programs/Microsoft VS Code Insiders/bin/code-insiders: 61: /mnt/c/Users/userID/AppData/Local/Programs/Microsoft VS Code Insiders/Code - Insiders.exe: Exec format error
```
Used the  [microsoft/WSL#9887 (comment)](https://github.com/microsoft/WSL/issues/9887#issuecomment-1516434388) solution to resolve.
