### ISSUE TITLE
Not Responding

### ISSUE THREAD

**Issue by iamradhikajha** [microsoft/vscode#181763]
Type: <b>Performance Issue</b>

When i open vs code in my laptop it shows not responding and give options of reopen close and keep waiting, Please fix this bug as soon as possible.

VS Code version: Code 1.78.0 (252e5463d60e63238250799aef7375787f68b4ee, 2023-05-03T20:09:00.748Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|12th Gen Intel(R) Core(TM) i5-1235U (12 x 2496)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|7.69GB (0.84GB free)|
|Process Argv|--crash-reporter-id 4dcca62b-e7e2-46fc-a32a-918c353d3265|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	    95	 12616	code main
    0	    27	  2808	   crashpad-handler
    0	    86	  3612	window [2] (Issue Reporter)
    0	   169	  8948	   gpu-process
    2	   168	 13456	window [1] (Visual Studio Code)
    0	    48	 17376	   utility-network-service
    0	    87	 17836	shared-process
    0	    77	 18248	     ptyHost
    0	    77	 18068	fileWatcher [1]
    0	   202	 18372	extensionHost [1]
    0	    78	 17048	     electron-nodejs ("C:\Users\radhi\AppData\Local\Programs\Microsoft VS Code\Code.exe" --ms-enable-electron-run-as-node c:\Users\radhi\.vscode\extensions\kisstkondoros.vscode-gutter-preview-0.30.0\dist\server.js --node-ipc --clientProcessId=18372)
    0	    77	 17592	     electron-nodejs ("C:\Users\radhi\AppData\Local\Programs\Microsoft VS Code\Code.exe" --ms-enable-electron-run-as-node c:\Users\radhi\.vscode\extensions\formulahendry.auto-rename-tag-0.1.10\packages\server\dist\serverMain.js --node-ipc --clientProcessId=18372)
    0	    93	 17620	     electron-nodejs ("C:\Users\radhi\AppData\Local\Programs\Microsoft VS Code\Code.exe" --ms-enable-electron-run-as-node c:\Users\radhi\.vscode\extensions\streetsidesoftware.code-spell-checker-2.20.4\packages\_server\dist\main.js --node-ipc --clientProcessId=18372)
```

</details>
<details>
<summary>Workspace Info</summary>

```
;
```

</details>
<details><summary>Extensions (46)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|3.0.2
color-info|bie|0.7.2
vscode-tailwindcss|bra|0.9.11
vscode-wev-dev-extension-pack|c0d|2.5.0
c-cpp-compile-run|dan|1.0.44
vscode-eslint|dba|2.4.0
es7-react-js-snippets|dsz|4.4.3
gitlens|eam|13.5.0
vscode-html-css|ecm|1.13.1
EditorConfig|Edi|0.16.4
prettier-vscode|esb|9.12.0
auto-rename-tag|for|0.1.10
code-runner|for|0.12.0
c-cpp-runner|fra|5.3.1
output-colorizer|IBM|0.1.2
error-gutters|Igo|1.0.1
better-cpp-syntax|jef|1.17.2
vscode-gutter-preview|kis|0.30.0
template-string-converter|meg|0.6.1
git-graph|mhu|1.30.0
dotenv|mik|1.0.1
inline-fold|moa|0.2.4
vscode-html-format|moh|0.0.5
cpptools|ms-|1.15.4
cpptools-extension-pack|ms-|1.3.0
color-highlight|nau|2.5.0
material-icon-theme|PKi|4.27.0
subtle-brackets|raf|3.0.0
LiveServer|rit|5.7.9
trailing-spaces|sha|0.4.1
html-to-css-autocompletion|sol|1.1.2
css-auto-prefix|spo|0.1.7
code-spell-checker|str|2.20.4
vscode-styled-components|sty|1.7.8
es6-string-html|Tob|2.12.1
errorlens|use|3.11.0
vscode-lldb|vad|1.9.1
highlight-matching-tag|vin|0.11.0
intellicode-api-usage-examples|Vis|0.2.7
vscodeintellicode|Vis|1.2.30
vscodeintellicode-completions|Vis|1.0.22
rainbow-tags|vol|0.4.1
vscode-todo-highlight|way|1.0.5
JavaScriptSnippets|xab|1.8.0
html-css-class-completion|Zig|1.20.0
classnametocss|zit|0.0.7

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
vsccc:30610678
2e4cg342:30602488
pyind779:30671433
f6dab269:30613381
pythonsymbol12:30671437
a9j8j154:30646983
showlangstatbar:30730054
azdwalk:30721579
pythonms35:30701012
pythonfmttext:30731395
pythoncmvfstr:30731969
fixshowwlkth:30730052
pythongtdpath:30731978

```

</details>

**Comment by tamuratak** [comment]
McAfee Antivirus might be the cause. See https://github.com/microsoft/vscode/issues/178733#issuecomment-1500812938

**Comment by deepak1556** [comment]
Merging to https://github.com/microsoft/vscode/issues/178962

Please follow the workaround mentioned in https://github.com/microsoft/vscode/issues/178733#issuecomment-1500812938 until the issue is resolved.
