### ISSUE TITLE
VSIX Format Change for Snippets

### ISSUE THREAD

**Issue by billjwolff** [Microsoft/vscode#18177]
- VSCode Version: 1.8.1 and earlier
- OS Version: Win 10, Win 7

Steps to Reproduce:

1. create a VSIX for snippets
2. install as extension
3. call snippet
4. some characters are not escaped correctly
5. exact same VSIX works in versions prior to 1.8.1

Looks like {{ is not escaped correctly and $ now needs to be escaped. Is this new?

**Comment by jrieken** [comment]
@billjwolff Please attach a sample snippet or the extension in question. Snippets contributed via extensions, were always using a subset of the TextMate snippet syntax and still do: https://code.visualstudio.com/docs/customization/userdefinedsnippets#_snippet-syntax. 

For 1.8 we have rewritten our snippet parser to be more correct and to allow for new feature. That also removed *internal* snippet syntax we were supporting there by accident (not by spec). What you refer to `{{` seems like old/internal/undocumented syntax
