### ISSUE TITLE
Bug Ctrl C Kill Server

### ISSUE THREAD

**Issue by bimosptr1** [microsoft/vscode#181783]
Does this issue occur when all extensions are disabled?: Yes

Version: 1.78.0 (Universal)
Commit: https://github.com/microsoft/vscode/commit/252e5463d60e63238250799aef7375787f68b4ee
Date: 2023-05-03T20:11:00.813Z
Electron: 22.4.8
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Darwin x64 18.7.0
Sandboxed: Yes

ProductName: macOS
ProductVersion: 10.14.6 Mojave
BuildVersion: 18G9323

Steps to Reproduce:

Open the integrated terminal.
Execute cat
Type Ctrl-C
The cat command doesn't exit. Only ^C is printed.
Notice that Ctrl-C does work on the latest v1.78.0. 

(Ctrl C work on version 1.77)

![image](https://user-images.githubusercontent.com/75081018/236734814-c8a299d4-3b66-481d-8f0c-c2339694058f.png)

**Comment by kolmakova** [comment]
Can confirm bug happens on the same OS for me #181488.

**Comment by Hertony** [comment]
Same bug here. MacOS. Broken since v1.78.0.

**Comment by vinipaschoal** [comment]
Same, broken on MacOS.

**Comment by meganrogge** [comment]
this works for me on insider's - if you can repro there, I'd recommend checking your settings

**Comment by bimosptr1** [comment]
> ini berfungsi untuk saya di orang dalam - jika Anda dapat melakukan repro di sana, saya sarankan untuk memeriksa pengaturan Anda

where setting ?

**Comment by kolmakova** [comment]
@meganrogge Do you test on OSX 10.14.6 Mojave? What setting to check and why does it work in VSCode 1.77 and in the latest version doesn't? I've spent a whole day checking all the settings that can be related to the terminal and nothing helped, only roll back to 1.77. I'm sure it's a bug on the VSCode side.

**Comment by Tucsky** [comment]
CTRL+C won't stop any process in terminals since vscode 1.78.0.

**Comment by pitbrest** [comment]
Та же проблема на High Sierra, помогает только откат на старую версию
