### ISSUE TITLE
Moving views between side bars and moving items around in the activity bar don't work on wayland

### ISSUE THREAD

**Issue by nichady** [microsoft/vscode#181736]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.78.0
- OS Version: Arch Linux (Hyprland)

Steps to Reproduce:

1. Run vscode with wayland:
`code --enable-features=WaylandWindowDecorations --ozone-platform-hint=auto`

2. Try moving views between the primary and secondary side bars, or try moving items around on the activity bar. Neither work.

**Comment by deepak1556** [comment]
Merging to https://github.com/microsoft/vscode/issues/156723
