### ISSUE TITLE
VSCode startup is slow

### ISSUE THREAD

**Issue by bhavneet-bodh** [microsoft/vscode#181728]
[Clipboard.txt](https://github.com/microsoft/vscode/files/11413260/Clipboard.txt)
[1.]([Clipboard.txt](https://github.com/microsoft/vscode/files/11413255/Clipboard.txt)) :warning: We have copied additional data to your clipboard. Make sure to **paste** here. :warning:
1. :warning: Make sure to **attach** these files from your *home*-directory: :warning:
-`prof-nyskzuz8.main.cpuprofile.txt`
-`prof-nyskzuz8.renderer.cpuprofile.txt`
[Clipboard.txt](https://github.com/microsoft/vscode/files/11413262/Clipboard.txt)

**Comment by bhavneet-bodh** [comment]
[prof-nyskzuz8.main.cpuprofile.txt](https://github.com/microsoft/vscode/files/11413265/prof-nyskzuz8.main.cpuprofile.txt)
[prof-nyskzuz8.renderer.cpuprofile.txt](https://github.com/microsoft/vscode/files/11413266/prof-nyskzuz8.renderer.cpuprofile.txt)

**Comment by tamuratak** [comment]
McAfee Antivirus might be the cause. See https://github.com/microsoft/vscode/issues/178733#issuecomment-1500812938

**Comment by bhavneet-bodh** [comment]
Thanks this solved my issue.

**Comment by bhavneet-bodh** [comment]
Thanks this solved my issue.
