### ISSUE TITLE
Enable symbol searching in the pop-up peeked window

### ISSUE THREAD

**Issue by rainingdays** [microsoft/vscode#181706]
When we peek the implementations of an interface/a trait, by using the key combination Ctrl+F12 or Ctrl+Shift+F12, the peeked window is poped up and display the related implementations as a list. However , we can't search in this list. When the number of implementations is large, to locate a specific one is extremely tough.

![20230506211238](https://user-images.githubusercontent.com/33363420/236626454-97a19d9d-5a2d-4c9d-8fbf-1b3857668924.jpg)

Expectation:
Please enable symbol searching in the pop-up peeked window

**Comment by jrieken** [comment]
This works with `cmd+f`

<img width="632" alt="Screenshot 2023-05-09 at 07 44 25" src="https://user-images.githubusercontent.com/1794099/237004754-05739f2a-bdad-4146-808b-c19dcddbbf2e.png">
