### ISSUE TITLE
Non-git repository causes Code to grab all files on Mac

### ISSUE THREAD

**Issue by coryjohnson26** [Microsoft/vscode#1817]
When opening a non-git repository in Code, the Git tab seems to pull in every file on my Mac. In Windows, if the folder isn't a git repository, a button to Initialize a git repository is displayed.

**Comment by joaomoreno** [comment]
What do you mean by *grab* and *pull in*? Can you be more descriptive? Can you provide a screenshot?

**Comment by coryjohnson26** [comment]
<img width="1440" alt="screen shot 2016-01-06 at 7 36 43 am" src="https://cloud.githubusercontent.com/assets/11200966/12144959/626c20fa-b448-11e5-92f0-7087b6fa05c9.png">

As shown in the picture, I opened my Documents folder, which contains 2 sub-folders, each with 3 or 4 files. However, the git tab shows there are 20444 files that have yet to be committed. From what I can tell, it is showing every file on my computer.

**Comment by joaomoreno** [comment]
You must've accidentally created a git repository in your user home folder.

Open a Terminal, and type `ls ~/.git`. This will confirm that. You can remove it with `rm -r ~/.git`.

**Comment by coryjohnson26** [comment]
Perfect.   Thank you!

Cory Johnson
801-360-7864




On Wed, Jan 6, 2016 at 7:03 AM -0800, "João Moreno" <notifications@github.com> wrote:





You must've accidentally created a git repository in your user home folder.

Open a Terminal, and type `ls ~/.git`. This will confirm that. You can remove it with `rm -r ~/.git`.

---
