### ISSUE TITLE
Slow startup of vs code.

### ISSUE THREAD

**Issue by saransh79** [microsoft/vscode#181786]
Type: <b>Performance Issue</b>

From last 10 days , VS code takes lot of time for open and sometimes it show warning to close, restart and wait. This issue was never happened before.
I want you to suggest me something to deal with this issue.

VS Code version: Code 1.78.0 (252e5463d60e63238250799aef7375787f68b4ee, 2023-05-03T20:09:00.748Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz (8 x 2419)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.70GB (7.84GB free)|
|Process Argv|--crash-reporter-id 25145be5-1b6c-4728-b160-2ff78d0f2578|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	    97	  7836	code main
    0	    28	  4388	   crashpad-handler
    0	    90	  9800	shared-process
    0	    81	 15564	     ptyHost
    0	   175	 10312	window [1] (index.html - First Chrome Extension - Visual Studio Code)
    0	   171	 15344	extensionHost [1]
    0	   103	 21864	     electron-nodejs ("C:\Users\dream\AppData\Local\Programs\Microsoft VS Code\Code.exe" --ms-enable-electron-run-as-node "c:\Users\dream\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\html-language-features\server\dist\node\htmlServerMain" --node-ipc --clientProcessId=15344)
    0	    79	 23420	     electron-nodejs ("C:\Users\dream\AppData\Local\Programs\Microsoft VS Code\Code.exe" --ms-enable-electron-run-as-node c:\Users\dream\.vscode\extensions\formulahendry.auto-rename-tag-0.1.10\packages\server\dist\serverMain.js --node-ipc --clientProcessId=15344)
    0	    83	 15700	fileWatcher [1]
    0	    50	 18960	   utility-network-service
    0	    87	 23888	window [2] (Issue Reporter)
    0	   230	 24564	   gpu-process
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (index.html - First Chrome Extension - Visual Studio Code)
|    Folder (First Chrome Extension): 5 files
|      File types: html(1) js(1) png(1) json(1) css(1)
|      Conf files:;
```

</details>
<details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
npm-intellisense|chr|1.4.4
c-cpp-compile-run|dan|1.0.44
es7-react-js-snippets|dsz|4.4.3
prettier-vscode|esb|9.12.0
file-icons|fil|1.0.29
auto-rename-tag|for|0.1.10
code-runner|for|0.12.0
vscode-language-babel|mgm|0.0.39
python|ms-|2023.8.0
vscode-pylance|ms-|2023.5.10
jupyter|ms-|2023.4.1011241018
jupyter-keymap|ms-|1.1.0
jupyter-renderers|ms-|1.0.15
cpptools|ms-|1.15.4
vscode-react-native|msj|1.11.0
LiveServer|rit|5.7.9

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
vsccc:30610678
282f8724:30602487
pyind779:30671433
89544117:30613380
pythonsymbol12:30671437
a9j8j154:30646983
6233i204:30730053
azdwalk:30721579
pythonms35:30701012
pythonfmttext:30731395
pythoncmvfstr:30731969
fixshowwlkth:30730052
hidesbindicator:30730055

```

</details>

**Comment by tamuratak** [comment]
McAfee Antivirus might be the cause. See https://github.com/microsoft/vscode/issues/178733#issuecomment-1500812938

**Comment by deepak1556** [comment]
Merging to https://github.com/microsoft/vscode/issues/178962

Please follow the workaround mentioned in https://github.com/microsoft/vscode/issues/178733#issuecomment-1500812938 until the issue is resolved.
