### ISSUE TITLE
Column select with keyboard doesn't work

### ISSUE THREAD

**Issue by BillDenton** [Microsoft/vscode#18175]
- VSCode Version: Code 1.8.1 (ee428b0eead68bf0fb99ab5fdc4439be227b6281, 2016-12-19T14:49:23.350Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions:

|Extension|Author|Version|
|---|---|---|
|read-only-indicator|alefragnani|0.4.0|
|alignment|annsk|0.3.0|
|bettertab|arenl|1.0.1|
|Doxygen|bbenoist|1.0.0|
|python|donjayamanne|0.5.5|
|EditorConfig|EditorConfig|0.3.4|
|vscode-great-icons|emmanuelbeziat|1.1.36|
|matlab|Gimly81|0.4.0|
|status-bar-tasks|GuardRex|0.1.2|
|vscode-dimmer|hoovercj|2.1.0|
|cpptools|ms-vscode|0.9.3|
|vscode-clearcase|OpenNingia|1.4.1|
|vscode-icons|robertohuertasm|4.3.0|
|theme-cyanicpastels|SamuelLampa|0.0.9|
|indenticator|SirTori|0.2.1|
|vscode-hexdump|slevesque|1.1.4|
|code-spell-checker|streetsidesoftware|0.13.3|
|comment-snippets|Tobiah|0.2.0|
|dark-plus-material|vangware|0.1.4|
|change-case|wmaurer|1.0.0|
|highlight-trailing-white-spaces|ybaumes|0.0.2|

---

Steps to Reproduce:

1. Click inside an editor to give it focus.
2. Press Ctrl+Shift+Alt+any arrow key. Nothing happens. Cursor doesn't move at all.

Works with the mouse with Alt-Shift-Click drag. But needs to work with keyboard only. For example, in SlickEdit it is simple, just press Ctrl-B and move the cursor using cursor keys.

**Comment by alexandrudima** [comment]
@BillDenton Is it possible that you have some software on your machine that prevents VS Code from getting these keybindings?

If you go to `File > Preferences > Keyboard shortcuts` and define the following keybindings:
```json
// Place your key bindings in this file to overwrite the defaults
[
{
  "key": "ctrl+down",
  "command": "cursorColumnSelectDown",
  "when": "editorTextFocus"
},
{
  "key": "ctrl+left",
  "command": "cursorColumnSelectLeft",
  "when": "editorTextFocus"
},
{
  "key": "ctrl+right",
  "command": "cursorColumnSelectRight",
  "when": "editorTextFocus"
},
{
  "key": "ctrl+up",
  "command": "cursorColumnSelectUp",
  "when": "editorTextFocus"
}
]
```

Can you then do column select with `ctrl+arrow` keys?

**Comment by BillDenton** [comment]
Just tested it again with the original keys without changing keybinds and it is working. Not sure what has changed. Changes in my extension list:
added docthis|joelday|0.3.6 
updated vscode-icons|robertohuertasm|6.0.0 from version 4.3.0
updated code-spell-checker|streetsidesoftware|0.14.2 from 0.13.3

As it is working now, I'll close. Can be reopened if any further issues.

**Comment by BillDenton** [comment]
Today when I'm accessing VS Code via remote desktop it isn't working. Could it be remote desktop?

**Comment by BillDenton** [comment]
Working fine today, when I'm not using remote desktop.
