### ISSUE TITLE
Can you guys maintain your presence in the `apt` repository.

### ISSUE THREAD

**Issue by R-Rothrock** [microsoft/vscode#181710]
If you run `sudo apt install code-oss` in Debian/Ubuntu (Kali in my case), you will get an old version of VSCode (1.55.1 I think, don't quote me on that.) This version of VSCode was prone to constant segfaults.

Are you guys able to get a maintainer for the apt repository, so that VSCode will:
1. Install as the latest version
2. Update when I run `sudo apt update; sudo apt upgrade`

**Comment by joaomoreno** [comment]
`code-oss` isn't a product we maintain, only `Code` and `Code Insiders`. More details: https://code.visualstudio.com/docs/setup/linux#_debian-and-ubuntu-based-distributions
