### ISSUE TITLE
DAP important output message results in [object Object] popup

### ISSUE THREAD

**Issue by lukaszsamson** [microsoft/vscode#181719]
Type: <b>Bug</b>

I'm a developer of Debugger adapter for elixir language https://github.com/elixir-lsp/elixir-ls. Inoticed that `important` debugger events result in popup with [object Object]. All other output categories work as expected.

To reproduce:

Publish DAP Output event https://microsoft.github.io/debug-adapter-protocol/specification#Events_Output with `"category": "important"`

Result:
<img width="898" alt="Rondonized with seed 317328" src="https://user-images.githubusercontent.com/1078186/236639060-2c1a984e-07ca-484b-b4bd-ea18689b9a2c.png">

VS Code version: Code 1.78.0 (Universal) (252e5463d60e63238250799aef7375787f68b4ee, 2023-05-03T20:11:00.813Z)
OS version: Darwin arm64 22.4.0
Modes:
Sandboxed: Yes
Remote OS version: Linux arm64 5.15.49-linuxkit

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M2 Pro (12 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|2, 3, 3|
|Memory (System)|32.00GB (0.04GB free)|
|Process Argv|--crash-reporter-id 737eb191-7a40-4099-bfe0-4be53f44d180|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|Dev Container: SimpleFX Core Candles|
|OS|Linux arm64 5.15.49-linuxkit|
|CPUs|unknown (4 x 0)|
|Memory (System)|7.77GB (6.14GB free)|
|VM|0%|
</details><details><summary>Extensions (53)</summary>

Extension|Author (truncated)|Version
---|---|---
elm-format|aba|0.1.0
vscode-mjml|att|1.6.0
vscode-hex-pm-intellisense|ben|0.5.0
better-toml|bun|0.3.2
compare-view|che|0.13.0
npm-intellisense|chr|1.4.4
circleci|Cir|1.12.0
systemd-unit-file|coo|1.0.6
doxdocgen|csc|1.4.0
vscode-markdownlint|Dav|0.49.0
vscode-eslint|dba|2.4.0
vscode-remove-final-newlines|DoC|1.2.0
githistory|don|0.6.20
xml|Dot|2.5.1
es7-react-js-snippets|dsz|4.4.3
prettier-vscode|esb|9.12.0
hadolint|exi|1.1.2
vscode-diff|fab|1.4.2
vscode-github-actions|git|0.25.7
vscode-pull-request-github|Git|0.62.0
terraform|has|2.26.0
elixirlinter|iam|0.4.1
compareit|in4|0.0.2
elixir-ls|Jak|0.14.6
c-cpp-flylint|jbe|1.13.0
better-cpp-syntax|jef|1.17.2
cmake-language-support-vscode|jos|0.0.9
bash-ide-vscode|mad|1.36.0
vscode-docker|ms-|1.25.0
csharp|ms-|1.25.7
vscode-dotnet-runtime|ms-|1.6.0
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-slideshow|ms-|0.1.5
remote-containers|ms-|0.292.0
remote-ssh|ms-|0.100.0
remote-wsl|ms-|0.78.4
cmake-tools|ms-|1.14.31
cpptools|ms-|1.15.4
cpptools-extension-pack|ms-|1.3.0
remote-explorer|ms-|0.4.0
test-adapter-converter|ms-|0.1.7
mql-over-cpp|nic|0.0.3
hardhat-solidity|Nom|0.7.1
vetur|oct|0.37.3
phoenix|pho|0.1.2
qub-xml|qub|1.2.1
vscode-commons|red|0.0.6
vscode-yaml|red|1.12.2
elm|sbr|0.26.0
code-spell-checker|str|2.20.4
shellcheck|tim|0.32.5
beamdasm|Val|1.1.5
vscode-proto3|zxh|0.5.5

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscoreces:30445986
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
2e4cg342:30602488
pyind779:30671433
89544117:30613380
vscrpc:30673769
pythonsymbol12:30671437
2i9eh265:30646982
showlangstatbar:30730054
vsctsb:30705553
azdwalk:30721579
pythonms35:30701012
19089226:30706075
pythonfmttext:30731395
pythoncmv:30731968
fixhidewlkth:30730051

```

</details>

**Comment by roblourens** [comment]
This was just fixed. Should be fixed in the Insiders build- https://github.com/microsoft/vscode/pull/181964

I just noticed that there was no issue filed so I will use this issue for verification.
