### ISSUE TITLE
Problem with Do While loop in VS Code, but not in Visual Studio, for example

### ISSUE THREAD

**Issue by dogodogopequeno** [microsoft/vscode#181774]
- VS Code Version: 1.78.0
- OS Version: Windows 10 22H2

Steps to Reproduce:

1.  Just a program that takes user input to add numbers to a vector or display the numbers, amongst others. The function to display the options is called in a do while loop, as well as the switch for the input, which in of itself calls other functions depending on the input. 
2. In VS Code, the display function just keeps going, even if I call the function that ends the program, meanwhile in Visual Studio it just works perfectly.

I'd love to get to the bottom of this, because I really prefer VS Code.
Here's a print of the main function.
Thanks!
![MainFunction](https://user-images.githubusercontent.com/68162119/236702539-8bde3458-50b5-43e5-a9e4-603c2b7ea75a.jpeg)

**Comment by roblourens** [comment]
VS Code doesn't run your code- this sounds like an issue with your code or your project/system configuration
