### ISSUE TITLE
[MacOS and C++ projects] debugging binaries compiled with gcc hangs

### ISSUE THREAD

**Issue by lukka** [Microsoft/vscode#18174]
- VSCode Version: Code 1.8.1 (ee428b0eead68bf0fb99ab5fdc4439be227b6281, 2016-12-19T14:42:49.304Z)
- OS Version: Darwin x64 16.3.0
- Extensions:

|Extension|Author|Version|
|---|---|---|
|vscode-markdownlint|DavidAnson|0.6.0|
|vscode-docker|PeterJausovec|0.0.11|
|code-gnu-global|austin|0.2.1|
|githistory|donjayamanne|0.1.4|
|python|donjayamanne|0.5.5|
|vscode-clang|mitaki28|0.2.1|
|PowerShell|ms-vscode|0.8.0|
|Theme-MarkdownKit|ms-vscode|0.1.1|
|cpptools|ms-vscode|0.9.3|
|csharp|ms-vscode|1.6.2|
|standard|shinnn|0.2.3|
|vscode-hexdump|slevesque|1.1.4|

---

Steps to Reproduce:

1. create a x.cpp file, with an hello world C++ application
2. compile with a task.json that looks like this:
{
    // See https://go.microsoft.com/fwlink/?LinkId=733558
    // for the documentation about the tasks.json format
    "version": "0.1.0",
    "command": "g++",
    "isShellCommand": true,
    "args": ["-std=c++14","-g","x.cpp"],
    "showOutput": "always"
}

3. start debugging by pressing the greenish play button with the following configuration:
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "C++ Launch",
            "type": "cppdbg",
            "request": "launch",
            "program": "${workspaceRoot}/a.out",
            "args": [],
            "stopAtEntry": false,
            "cwd": "${workspaceRoot}",
            "environment": [],
            "externalConsole": true,
            "linux": {
                "MIMode": "gdb",
                "setupCommands": [
                    {
                        "description": "Enable pretty-printing for gdb",
                        "text": "-enable-pretty-printing",
                        "ignoreFailures": true
                    }
                ]
            },
            "osx": {
                "MIMode": "lldb"
            },
            "windows": {
                "MIMode": "gdb",
                "setupCommands": [
                    {
                        "description": "Enable pretty-printing for gdb",
                        "text": "-enable-pretty-printing",
                        "ignoreFailures": true
                    }
                ]
            }
        },
        {
            "name": "C++ Attach",
            "type": "cppdbg",
            "request": "attach",
            "program": "enter program name, for example ${workspaceRoot}/a.out",
            "processId": "${command.pickProcess}",
            "linux": {
                "MIMode": "gdb",
                "setupCommands": [
                    {
                        "description": "Enable pretty-printing for gdb",
                        "text": "-enable-pretty-printing",
                        "ignoreFailures": true
                    }
                ]
            },
            "osx": {
                "MIMode": "lldb"
            },
            "windows": {
                "MIMode": "gdb",
                "setupCommands": [
                    {
                        "description": "Enable pretty-printing for gdb",
                        "text": "-enable-pretty-printing",
                        "ignoreFailures": true
                    }
                ]
            }
        }
    ]
}

4- the status bar change color to orange, no output on the debug view, not output on the console tab of the developer tools, cpu hangs at 100%.

**Comment by pieandcakes** [comment]
@lukka This issue should be filed in https://github.com/Microsoft/vscode-cpptools .  

Question: do you get the pop up asking you to enable superuser? This is necessary for the debug to work.

**Comment by sandy081** [comment]
@lukka Moved to VSCode cpp tools repository

**Comment by lukka** [comment]
@pieandcakes i do not get any dialog asking for admin password. Sometime a console is opened, and it is an interactive one just idling for my input, my ./a.out file is not executed inside it.
