### ISSUE TITLE
Failed to clear settings-sync data in Codespaces

### ISSUE THREAD

**Issue by zWingz** [microsoft/vscode#181780]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 
- OS Version: 

Steps to Reproduce:

1.  Clear settings-sync data in Codespaces
2.  return 403
<img width="621" alt="image" src="https://user-images.githubusercontent.com/13031838/236720962-350b2fe8-88dc-4989-99a3-4c41ade5b5f8.png">

**Comment by sandy081** [comment]
> return 403

This is expected because you do not have enough permissions to do this operation.

Do you see a badge on the Account menu to Sign in to Settings Sync?
