### ISSUE TITLE
Slow Start

### ISSUE THREAD

**Issue by dhruvk0011** [microsoft/vscode#181754]
[prof-lpH52Cf3.renderer.cpuprofile.txt](https://github.com/microsoft/vscode/files/11414934/prof-lpH52Cf3.renderer.cpuprofile.txt)

[prof-lpH52Cf3.main.cpuprofile.txt](https://github.com/microsoft/vscode/files/11414931/prof-lpH52Cf3.main.cpuprofile.txt)
Type: <b>Performance Issue</b>

VS Code is slow to start. Happens everytime I try to start VS Code. Tried and disabled all extensions, same issue persists!

VS Code version: Code 1.78.0 (252e5463d60e63238250799aef7375787f68b4ee, 2023-05-03T20:09:00.748Z)
OS version: Windows_NT x64 10.0.19045
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz (8 x 1690)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.73GB (7.48GB free)|
|Process Argv|--crash-reporter-id 530515e6-3383-456e-b35f-4bb4238d5670|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    1	   119	  4868	code main
    0	    80	  3880	fileWatcher [1]
    0	    72	  7644	   utility-network-service
    0	   157	 13428	extensionHost [1]
    0	    97	 19280	     electron-nodejs ("C:\Users\DELL\AppData\Local\Programs\Microsoft VS Code\Code.exe" --ms-enable-electron-run-as-node "c:\Users\DELL\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\markdown-language-features\server\dist\node\workerMain" --node-ipc --clientProcessId=13428)
    0	    67	 14440	   crashpad-handler
    0	   220	 16008	   gpu-process
    0	   183	 17000	window [1] (Startup Performance - Visual Studio Code)
    0	   103	 19308	shared-process
    0	    82	  8484	     ptyHost
    2	    90	 20296	window [2] (Issue Reporter)
```

</details>
<details>
<summary>Workspace Info</summary>

```
;
```

</details>
<details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
flutter-snippets|ale|3.0.0
path-intellisense|chr|2.8.4
ccs-flutter-color|cir|1.0.2
dart-code|Dar|3.62.0
flutter|Dar|3.62.0
prettier-vscode|esb|9.12.0
code-runner|for|0.12.0
better-cpp-syntax|jef|1.17.2
cpptools|ms-|1.15.4
material-icon-theme|PKi|4.27.0
intellicode-api-usage-examples|Vis|0.2.7
vscodeintellicode|Vis|1.2.30

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
282f8724:30602487
pyind779:30671433
89544117:30613380
pythonsymbol12:30671437
6233i204:30730053
vsccsb:30705552
azdwalk:30721579
pythonms35:30701012
pythonfmttext:30731395
fixshowwlkth:30730052
hidesbindicator:30730055

```

</details>

**Comment by tamuratak** [comment]
McAfee Antivirus might be the cause. See https://github.com/microsoft/vscode/issues/178733#issuecomment-1500812938

**Comment by dhruvk0011** [comment]
Thanks for the advice !! Will have a look.

**Comment by dhruvk0011** [comment]
> McAfee Antivirus might be the cause. See [#178733 (comment)](https://github.com/microsoft/vscode/issues/178733#issuecomment-1500812938)

It worked !! Thanks.
