### ISSUE TITLE
VSCode doesn't fetch remotes from gitconfig after update

### ISSUE THREAD

**Issue by dnquinn** [microsoft/vscode#181717]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.78.0
- OS Version: Windows 11 Version 22H2 22621.1555

Steps to Reproduce:

1. Update to Visual Studio Code 1.78.0
2. Create global git config with some remote sections 
3. Initialize repository then push it to a remote origin
4. It fails with warning (Your repository has no remotes configured to push to) that suggesting to add new remote origin

Note: before vscode was updated a data about remotes was fetched by gui push panel automatically. Now it creates local section into git/config of current repository. `git.requireGitUserConfig` setted to false and `git config --global --list` shows the same data as in global config. If add remote manually, as suggested, data will pushed as before using all global credentials and ssh key. 

```
# .gitconfig example

[user]
    email = username@mail.com
    name = username
	
[remote "project1"]
    fetch = +refs/heads/*:refs/remotes/project1/*
    url = git@bitbucket.org:username/project1.git

[remote "project2"]
    fetch = +refs/heads/*:refs/remotes/project2/*
    url = git@bitbucket.org:username/project2.git
```

```
# local config before

[core]
   repositoryformatversion = 0
   filemode = false
   bare = false
   logallrefupdates = true
   symlinks = false
   ignorecase = true
[branch "master"]
   remote = projectname
   merge = refs/heads/master
```

```
# local config after

[core]
   repositoryformatversion = 0
   filemode = false
   bare = false
   logallrefupdates = true
   symlinks = false
   ignorecase = true
[remote "project"]
   url = git@bitbucket.org:username/project.git
   fetch = +refs/heads/*:refs/remotes/project/*
[branch "master"]
   remote = projectname
   merge = refs/heads/master
```

**Comment by lszomoru** [comment]
@dnquinn, thank you very much for filing this issue. I have looked at the code, and while the VS Code extension does read from the "git config" file, I do not believe that it ever writes to the local configuration file. 

Are you certain that VS Code is the one that updated the local configuration file? If you open the [git output window](https://code.visualstudio.com/docs/sourcecontrol/overview#_git-output-window), as that will list all the git commands that are being executed. If you go through the steps listed above, do you see any `git config` calls there? Can you also reproduce the issue if you start VS Code with the `--disable-extensions` flag?
