### ISSUE TITLE
Terminal shared between instances!?

### ISSUE THREAD

**Issue by houbi56** [microsoft/vscode#181799]
Type: <b>Bug</b>

I have a vscode instance running an angular app with 'ng serve'.
Opening a separate instance of vscode  (very common use-case) for another project/path, I see the output of the angular app in the terminal. 

VS Code version: Code 1.78.0 (252e5463d60e63238250799aef7375787f68b4ee, 2023-05-03T20:09:00.748Z)
OS version: Windows_NT x64 10.0.19044
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.82GB (2.35GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|16.0.0
bracket-pair-colorizer-2|Coe|0.2.4
angular-schematics|cyr|5.3.1
vscode-eslint|dba|2.4.0
githistory|don|0.6.20
Angular2|joh|13.0.0
csharp|ms-|1.25.7

</details>

**Comment by meganrogge** [comment]
Please provide a screenshot or [a gif](https://gifcap.dev/) illustrating the problem (attaching images won't work via email, you need to go to github.com). See [this wiki page](https://github.com/microsoft/vscode/wiki/Terminal-Issues) for more general info on how to report actionable terminal issues.
/label info-needed terminal
