### ISSUE TITLE
Inline Suggest toolbar missing when set to 'Always'

### ISSUE THREAD

**Issue by omermizr** [microsoft/vscode#181764]
Type: <b>Bug</b>

Change the setting for 'editor.inlineSuggest.showToolbar' to 'always'.

Expected:
Suggestion toolbar is shown for suggestions without hovering. 

Actual:
Suggestion toolbar is never shown, not even when hovering. 
Changing this back to 'onHover' works as expected (hovering shows the toolbar)

VS Code version: Code - Insiders 1.79.0-insider (Universal) (2c73d2651cc525b27fc697b820743098a204ec01, 2023-05-04T22:14:17.675Z)
OS version: Darwin arm64 22.2.0
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Max (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|301, 152, 81|
|Memory (System)|32.00GB (0.06GB free)|
|Process Argv|--crash-reporter-id 70a87a82-3a18-4efd-a579-683643eba8e8|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (64)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|3.0.2
codesnap|adp|1.3.4
TabOut|alb|0.2.2
Bookmarks|ale|13.3.1
scratchpads|bue|1.0.0
better-toml|bun|0.3.2
vscode-expo|byC|0.9.2
path-intellisense|chr|2.8.4
regex|chr|0.4.0
vscode-svgviewer|css|2.0.0
vscode-eslint|dba|2.4.0
es7-react-js-snippets|dsz|4.4.3
gitlens|eam|2023.5.505
prettier-vscode|esb|9.12.0
vscode-jest-runner|fir|0.4.60
auto-complete-tag|for|0.1.0
auto-rename-tag|for|0.1.10
code-runner|for|0.12.0
shell-format|fox|7.2.5
copilot-chat|Git|0.1.2023050301
copilot-labs|Git|0.12.791
copilot-nightly|Git|1.85.80
gitlab-workflow|Git|3.62.0
git-worktrees|Git|2.0.5
debug-visualizer|hed|2.4.0
realtime-debugging|hed|0.1.0
search-editor-apply-changes|jak|0.1.1
jwt-decoder|jfl|1.2.0
Kotlin|mat|1.7.1
git-graph|mhu|1.30.0
mongodb-vscode|mon|0.11.1
vscode-docker|ms-|1.25.0
vscode-edge-devtools|ms-|2.1.1
isort|ms-|2023.9.11141005
python|ms-|2023.9.11251005
vscode-pylance|ms-|2023.5.11
jupyter|ms-|2023.5.1001271002
jupyter-keymap|ms-|1.1.0
jupyter-renderers|ms-|1.0.15
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-slideshow|ms-|0.1.5
vscode-js-profile-flame|ms-|1.0.5
vscode-typescript-next|ms-|5.1.20230506
vsliveshare|ms-|1.0.5864
vscode-react-native|msj|1.11.0
color-highlight|nau|2.5.0
vscode-twoslash-queries|Ort|1.1.0
vscode-versionlens|pfl|1.5.0
quicktype|qui|12.0.46
vscode-xml|red|0.25.0
vscode-yaml|red|1.12.2
partial-diff|ryu|1.4.3
vscode-fileutils|sle|3.10.1
code-spell-checker|str|2.20.4
vscode-pets|ton|1.22.0
luna-paint|Tyr|0.16.0
errorlens|use|3.11.0
console-ninja|Wal|0.0.118
quokka-vscode|Wal|1.0.534
wallaby-vscode|Wal|1.0.352
vscode-import-cost|wix|3.3.0
vscode-jumpy|wma|0.3.1
pretty-ts-errors|yoa|0.4.0
markdown-all-in-one|yzh|3.5.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythontb:30258533
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscod805:30301674
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30404738
cppdebug:30492333
vsclangdf:30492506
c4g48928:30535728
dsvsc012:30540252
pynewext54:30618038
pylantcb52:30590116
pyind779:30611226
pythonsymbol12:30651887
a9j8j154:30646983
6233i204:30725950
azdwalk:30721579
pythonms35:30671666
f08j5886:30680471
57b77579:30687741
pythonfmttext:30716741
pythoncmvfstr:30726892
fixshowwlkth:30724385
showsbindicator:30724477
pythongtdpath:30726887

```

</details>

**Comment by bksubramanyarao** [comment]
im facing the same problem in windows 10 pro, when i set onHover it is showing

**Comment by ctf0** [comment]
samehere
```
Version: 1.79.0-insider
Commit: 2575777b9d3cdb865d61f9f1dfaac1fea9e1bde6
Date: 2023-05-12T05:24:44.544Z
Electron: 22.5.2
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Darwin arm64 21.6.0
Sandboxed: Yes
```

**Comment by hstaudacher** [comment]
Copilot users are also facing this issue, see https://github.com/orgs/community/discussions/56187
