### ISSUE TITLE
slow response

### ISSUE THREAD

**Issue by gopireddy311** [microsoft/vscode#181782]
Type: <b>Performance Issue</b>

when iam trying to open vscode not respondingfast .its running on very slow .please look into it and slove my issue as soon as possible

VS Code version: Code 1.78.0 (252e5463d60e63238250799aef7375787f68b4ee, 2023-05-03T20:09:00.748Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|12th Gen Intel(R) Core(TM) i5-1235U (10 x 2496)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.69GB (7.30GB free)|
|Process Argv|--crash-reporter-id 3a4d84de-3d3d-4f76-af8e-d718bbcf4a15|
|Screen Reader|yes|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	   104	 22928	code main
    0	    27	  1516	   crashpad-handler
    0	    87	  5796	window [2] (Issue Reporter)
    0	    83	  8640	fileWatcher [1]
    0	   184	 13620	   gpu-process
    0	   186	 14592	extensionHost [1]
    0	    79	  5480	     electron-nodejs ("C:\Users\gopir\AppData\Local\Programs\Microsoft VS Code\Code.exe" --ms-enable-electron-run-as-node c:\Users\gopir\.vscode\extensions\formulahendry.auto-rename-tag-0.1.10\packages\server\dist\serverMain.js --node-ipc --clientProcessId=14592)
    0	   148	 10828	     electron-nodejs ("C:\Users\gopir\AppData\Local\Programs\Microsoft VS Code\Code.exe" --ms-enable-electron-run-as-node c:\Users\gopir\.vscode\extensions\ms-edgedevtools.vscode-edge-devtools-2.1.1\node_modules\vscode-webhint\dist\src\server.js c:\Users\gopir\AppData\Roaming\Code\User\globalStorage\ms-edgedevtools.vscode-edge-devtools "Microsoft Edge Tools" --node-ipc --clientProcessId=14592)
    0	    86	 11188	     electron-nodejs ("C:\Users\gopir\AppData\Local\Programs\Microsoft VS Code\Code.exe" --ms-enable-electron-run-as-node c:\Users\gopir\.vscode\extensions\mtxr.sqltools-0.27.1\dist\languageserver.js --node-ipc --clientProcessId=14592)
    0	   102	 17432	     electron-nodejs ("C:\Users\gopir\AppData\Local\Programs\Microsoft VS Code\Code.exe" --ms-enable-electron-run-as-node "c:\Users\gopir\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\html-language-features\server\dist\node\htmlServerMain" --node-ipc --clientProcessId=14592)
    0	    80	 20708	     electron-nodejs ("C:\Users\gopir\AppData\Local\Programs\Microsoft VS Code\Code.exe" --ms-enable-electron-run-as-node c:\Users\gopir\.vscode\extensions\dbaeumer.vscode-eslint-2.4.0\server\out\eslintServer.js --node-ipc --clientProcessId=14592)
    0	   180	 16032	window [1] (index.html - sample - Visual Studio Code)
    0	    65	 17236	   gpu-process
    0	    49	 22236	   utility-network-service
    0	   105	 23296	shared-process
    0	    83	 14248	     ptyHost
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (index.html - sample - Visual Studio Code)
|    Folder (sample): 7 files
|      File types: jpg(2) html(1) md(1) css(1)
|      Conf files:;
```

</details>
<details><summary>Extensions (40)</summary>

Extension|Author (truncated)|Version
---|---|---
arepl|alm|2.0.5
vscode-color|ans|0.4.5
vscode-intelephense-client|bme|1.9.5
turbo-console-log|Cha|2.9.3
vscode-eslint|dba|2.4.0
githistory|don|0.6.20
gitlens|eam|13.5.0
vscode-html-css|ecm|1.13.1
prettier-vscode|esb|9.12.0
auto-close-tag|for|0.5.14
auto-rename-tag|for|0.1.10
code-runner|for|0.12.0
vscode-pull-request-github|Git|0.62.0
todo-tree|Gru|0.0.226
rest-client|hum|0.25.1
chatgpt-vscode-plugin|Jay|1.1.10
init-node-script|Jer|0.0.2
vsc-python-indent|Kev|1.18.0
git-indicators|lam|2.1.2
vscode-autoprefixer|mrm|3.0.1
vscode-edge-devtools|ms-|2.1.1
python|ms-|2023.8.0
vscode-pylance|ms-|2023.5.10
jupyter|ms-|2023.4.1011241018
jupyter-keymap|ms-|1.1.0
jupyter-renderers|ms-|1.0.15
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-slideshow|ms-|0.1.5
sublime-keybindings|ms-|4.0.10
sqltools|mtx|0.27.1
autodocstring|njp|0.6.1
phscript-sdk-formatter-vs|pho|1.0.1
material-icon-theme|PKi|4.27.0
vscode-thunder-client|ran|2.6.2
python-extended-snippets|tus|0.0.1
vscode-icons|vsc|12.4.0
vscode-surround|yat|1.5.0
php-intellisense|zob|1.1.2
cron-tasks|zok|0.1.2
sync-settings|zok|0.16.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vstes627:30244334
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
282f8724:30602487
pyind779:30671433
89544117:30613380
vscrp:30673768
pythonsymbol12:30671437
a9j8j154:30646983
6233i204:30730053
vsctsb:30705553
azdwalk:30721579
pythonms35:30701012
pythonfmttext:30731395
fixshowwlkth:30730052

```

</details>

**Comment by tamuratak** [comment]
McAfee Antivirus might be the cause. See https://github.com/microsoft/vscode/issues/178733#issuecomment-1500812938

**Comment by marcaureln** [comment]
I'm on Linux Mint 21.1 x86_64 and had no antivirus. I experienced the same. My VS Code starts slowing down after the April 2023 update. I removed some extensions thinking about the IDE being blotted but nothing. It's a bit slow on startup and take seconds (not milliseconds) to save files. I'm downgrading to March 2023 and keep you updated.

**Comment by deepak1556** [comment]
Merging to https://github.com/microsoft/vscode/issues/178962

Please follow the workaround mentioned in https://github.com/microsoft/vscode/issues/178733#issuecomment-1500812938 until the issue is resolved.

**Comment by deepak1556** [comment]
@marcaureln please open a separate issue for your scenario, thanks!
