### ISSUE TITLE
i cant install package on vs code

### ISSUE THREAD

**Issue by nathanieweb** [microsoft/vscode#181701]
Type: <b>Bug</b>

i cant install a package in python

VS Code version: Code 1.78.0 (252e5463d60e63238250799aef7375787f68b4ee, 2023-05-03T20:09:00.748Z)
OS version: Windows_NT x64 10.0.19042
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4210U CPU @ 1.70GHz (4 x 2394)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|7.90GB (3.59GB free)|
|Process Argv|--crash-reporter-id ab188f9a-08e2-4f9b-92a9-8cddbd529867|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (60)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-javascript-snippet-pack|aka|0.1.6
project-manager|ale|12.7.0
python-debug-address-prompt|ale|1.0.1
vscode-django|bat|1.10.0
vscode-node-readme|ben|3.0.2
node-json-autocomplete|bhs|0.1.3
java-run|cao|1.1.4
node-snippets|chr|1.3.3
npm-intellisense|chr|1.4.4
path-intellisense|chr|2.8.4
js-codeformer|cms|2.6.1
jsrefactor|cms|3.0.1
gitignore|cod|0.9.0
vscode-eslint|dba|2.4.0
git-extension-pack|don|0.1.3
githistory|don|0.6.20
python-environment-manager|don|1.0.4
python-extension-pack|don|1.7.0
gitlens|eam|13.5.0
EditorConfig|Edi|0.16.4
vscode-npm-script|eg2|0.3.29
vscode-firefox-debug|fir|2.9.8
code-runner|for|0.12.0
javascript-essentials|Gyd|0.1.1
search-node-modules|jas|1.3.0
chatgpt-vscode-plugin|Jay|1.1.10
black-vscode|jos|2.0.6
vsc-python-indent|Kev|1.18.0
vscode-exec-node|mir|0.5.5
vscode-edge-devtools|ms-|2.1.1
black-formatter|ms-|2023.2.0
isort|ms-|2022.8.0
python|ms-|2023.8.0
vscode-pylance|ms-|2023.5.10
jupyter|ms-|2023.4.1011241018
jupyter-keymap|ms-|1.1.0
jupyter-renderers|ms-|1.0.15
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-slideshow|ms-|0.1.5
js-debug-nightly|ms-|2023.5.317
node-debug2|ms-|1.43.0
vscode-typescript-next|ms-|5.1.20230502
autodocstring|njp|0.6.1
vscode-python-typehint|njq|1.5.1
LiveServer|rit|5.7.9
vscode-javascript-booster|sbu|14.0.1
pythonpack|shi|0.3.0
vscode-standard|sta|2.1.3
code-spell-checker|str|2.20.4
python|tht|0.2.3
vscode-status-bar-format-toggle|tom|3.1.1
python-extended-snippets|tus|0.0.1
intellicode-api-usage-examples|Vis|0.2.7
vscodeintellicode|Vis|1.2.30
nodejs-extension-pack|wad|0.1.9
NodeJS-extension-pack|wal|1.0.0
jinja|who|0.0.8
JavaScriptSnippets|xab|1.8.0
chat-gpt|zha|1.1.6
vscode-open-in-github|ziy|1.3.6

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscorecescf:30445987
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
3biah626:30602489
pyind779:30671433
f6dab269:30613381
pythonsymbol12:30671437
2i9eh265:30646982
6233i204:30730053
vsccsb:30705552
azdwalk:30721579
pythonms35:30701012
pythonfmttext:30731395
pythoncmv:30731968
fixhidewlkth:30730051
pythongtdpath:30731978

```

</details>

**Comment by brettcannon** [comment]
@nathanieweb that's unfortunately not enough information to go by to help you, and the Python extension doesn't do installations for you, so I don't think VS Code or its Python extension are causing your installation failure.

If you still think that somehow the Python extension is involved, please follow the instructions at https://aka.ms/pvsc-bug to file a bug report.
