### ISSUE TITLE
With Latest version not able to terminate terminal while running local dev server.

### ISSUE THREAD

**Issue by sakshikhurana** [microsoft/vscode#181767]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.78.0 
- OS Version: macOS Mojave 10.14.6 

Steps to Reproduce:

1.  Run npm start 
2. Try terminating local server with Control C, Command . but not nothing works

**Comment by sakshikhurana** [comment]
Also getting error in terminal as "bash: no job control in this shell"

**Comment by Eden-tran** [comment]
same problem with PHP laravel and "bash:no job control in this shell"

**Comment by mgarci201** [comment]
same issue w/ new vscode` version 1.78`, I've rolled back from previous working `version 1.77.3`

**Comment by zibiv** [comment]
Same, when running a process such as a server or npm run dev in Node JS, the Ctrl+C shortcut no longer interrupts the process in the terminal. It took me an hour to figure out that this issue only started occurring after the update.
