### ISSUE TITLE
startup is too slow

### ISSUE THREAD

**Issue by sebines** [microsoft/vscode#181722]
Type: <b>Performance Issue</b>

When is open vscode it is too slow to startup. Its been happening quiet some times. Please help me to find nec

VS Code version: Code 1.78.0 (252e5463d60e63238250799aef7375787f68b4ee, 2023-05-03T20:09:00.748Z)
OS version: Windows_NT x64 10.0.22624
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-10300H CPU @ 2.50GHz (8 x 2496)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|7.84GB (1.24GB free)|
|Process Argv|--crash-reporter-id 5ff47ab2-a49c-4230-870d-143a52cd1563|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	    96	 10840	code main
    1	    92	  6040	window [2] (Issue Reporter)
    0	   145	  6592	window [1] (● python_basics.ipynb - DataScience - Visual Studio Code)
    0	   147	 11456	extensionHost [1]
    0	   131	  2832	     electron-nodejs (C:\Users\Asus\AppData\Local\Programs\VSCode\Code.exe --ms-enable-electron-run-as-node c:\Users\Asus\.vscode\extensions\ms-python.vscode-pylance-2023.5.10\dist\server.bundle.js --cancellationReceive=file:94d0e7b4efe9fbbb90f98871921c75c70cd0dc8bcd --node-ipc --clientProcessId=11456)
    0	    67	 21568	     electron-nodejs (SV.js )
    0	    10	  6712	       console-window-host (Windows internal process)
    0	    34	 24468	     c:\Users\Asus\AppData\Local\Programs\Python\Python311\python.exe c:\Users\Asus\.vscode\extensions\ms-python.isort-2022.8.0\bundled\tool\server.py
    0	    10	 15300	       console-window-host (Windows internal process)
    0	    16	 26488	     c:\Users\Asus\anaconda3\python.exe c:\Users\Asus\.vscode\extensions\ms-toolsai.jupyter-2023.4.1011241018-win32-x64\pythonFiles\vscode_datascience_helpers\kernel_interrupt_daemon.py --ppid 11456
    0	    10	 25240	       console-window-host (Windows internal process)
    0	    27	 12240	   crashpad-handler
    0	    48	 15324	   utility-network-service
    0	    88	 18464	shared-process
    0	    77	 22584	     ptyHost
    0	   148	 19700	   gpu-process
    0	    93	 22928	   window
    0	    67	 26744	fileWatcher [1]
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (● python_basics.ipynb - DataScience - Visual Studio Code)
|    Folder (DataScience): 1 files
|      File types: ipynb(1)
|      Conf files:;
```

</details>
<details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
isort|ms-|2022.8.0
python|ms-|2023.8.0
vscode-pylance|ms-|2023.5.10
jupyter|ms-|2023.4.1011241018
jupyter-keymap|ms-|1.1.0
jupyter-renderers|ms-|1.0.15
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-slideshow|ms-|0.1.5
remote-wsl|ms-|0.78.4

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vstes627:30244334
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vscaac:30438847
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
2e4cg342:30602488
pyind779:30671433
89544117:30613380
pythonsymbol12:30671437
showlangstatbar:30730054
vsccsb:30705552
azdwalk:30721579
pythonms35:30701012
03d35959:30706073
pythonfmttext:30731395
pythoncmv:30731968
fixshowwlkth:30730052
pythongtdpathcf:30731979

```

</details>

**Comment by tamuratak** [comment]
McAfee Antivirus might be the cause. See https://github.com/microsoft/vscode/issues/178733#issuecomment-1500812938

**Comment by deepak1556** [comment]
Merging to https://github.com/microsoft/vscode/issues/178962

Please follow the workaround mentioned in https://github.com/microsoft/vscode/issues/178733#issuecomment-1500812938 until the issue is resolved.
