### ISSUE TITLE
I can't go down to the line below with the enter key.

### ISSUE THREAD

**Issue by MateuscardosoRocha** [microsoft/vscode#181705]
Type: <b>Bug</b>

I can't go down to the line below with the enter key.
Before taking a breath, for some reason now I can't take it anymore, I'm using shift + enter, but I'm not used to it...

I will be grateful if you help me to change this shortcut to enter only.

VS Code version: Code 1.78.0 (252e5463d60e63238250799aef7375787f68b4ee, 2023-05-03T20:09:00.748Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|7.88GB (1.74GB free)|
|Process Argv|--crash-reporter-id e2cf676b-8008-446f-9977-01e01092418f|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (32)</summary>

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|16.0.0
vscode-database|baj|2.2.3
vscode-intelephense-client|bme|1.9.5
simple-react-snippets|bur|1.2.7
vscode-styled-components|die|0.1.33
es7-react-js-snippets|dsz|4.4.3
prettier-vscode|esb|9.12.0
code-runner|for|0.12.0
vscode-exec-node|mir|0.5.5
vscode-language-pack-pt-BR|MS-|1.78.2023050309
isort|ms-|2022.8.0
python|ms-|2023.8.0
vscode-pylance|ms-|2023.5.10
jupyter|ms-|2023.4.1011241018
jupyter-keymap|ms-|1.1.0
jupyter-renderers|ms-|1.0.15
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-slideshow|ms-|0.1.5
php-docblocker|nei|2.7.0
material-icon-theme|PKi|4.27.0
open-php-html-js-in-browser|Pri|2.2.0
sqlite-viewer|qwt|0.2.5
java|red|1.18.0
LiveServer|rit|5.7.9
sass-indented|syl|1.8.26
tabnine-vscode|Tab|3.6.46
html-preview-vscode|tht|0.2.5
intellicode-api-usage-examples|Vis|0.2.7
vscodeintellicode|Vis|1.2.30
vscode-java-debug|vsc|0.50.0
vscode-java-pack|vsc|0.25.11
vscode-maven|vsc|0.41.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
2e4cg342:30602488
pyind779:30671433
89544117:30613380
pythonsymbol12:30671437
6233i204:30730053
azdwalk:30721579
pythonms35:30701012
pythonfmttext:30731395
pythoncmvfstr:30731969
fixhidewlkth:30730051
hidesbindicator:30730055

```

</details>

**Comment by ulugbekna** [comment]
Please, see the fix in this comment - https://github.com/microsoft/vscode/issues/181469#issuecomment-1535258363

Please, report back if this doesn't fix the problem.
