### ISSUE TITLE
Export more git commands

### ISSUE THREAD

**Issue by hffmnn** [Microsoft/vscode#18185]
- VSCode Version: Version 1.8.1 (1.8.1)
- OS Version: macOS 10.12.2

Steps to Reproduce:

1. Add `workbench.action.git.stageRanges` as a keybinding
2. Try to run with selected text in a diff view

Expected:
The selected lines get staged.

Experienced:
Editor gives a warning with `command 'workbench.action.git.stageRanges' not found`

I know that this command is not officially documented (in the provided `keybindings.json`), still I would like to know if:
1. there is reason for that
2. it should work.

**Comment by sandy081** [comment]
@hffmnn Its because, this actions is not registered as command and hence you see command not found. 

@joaomoreno Any reason why this is not exposed as a command?

**Comment by joaomoreno** [comment]
No reason, we can add it.

**Comment by hffmnn** [comment]
Cool! Thank you very much!

**Comment by joaomoreno** [comment]
Closed in the new SCM world.
