### ISSUE TITLE
The Window is not responding

### ISSUE THREAD

**Issue by DeepaChegi** [microsoft/vscode#181828]
Type: <b>Bug</b>

Have updated my pc to Win 11 from Win 10. Since then, facing the issue.
![Screenshot (1)](https://user-images.githubusercontent.com/76608316/236881451-cf084089-c071-4eea-9ce3-a39465a82dee.png)

VS Code version: Code 1.78.0 (252e5463d60e63238250799aef7375787f68b4ee, 2023-05-03T20:09:00.748Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-10210U CPU @ 1.60GHz (8 x 2112)|
|GPU Status|2d_canvas: unavailable_software<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>opengl: disabled_off<br>rasterization: disabled_software<br>raw_draw: disabled_off_ok<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software<br>webgpu: unavailable_software|
|Load (avg)|undefined|
|Memory (System)|7.83GB (2.94GB free)|
|Process Argv|--disable-gpu --crash-reporter-id c93a2fef-1562-4160-9dbf-25bb9628f7a0|
|Screen Reader|no|
|VM|80%|
</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
es7-react-js-snippets|dsz|4.4.3
vscode-html-css|ecm|1.13.1
code-runner|for|0.12.0
python|ms-|2023.8.0
vscode-pylance|ms-|2023.5.10
java|red|1.18.0
LiveServer|rit|5.7.9
pdf|tom|1.2.2
intellicode-api-usage-examples|Vis|0.2.7
vscodeintellicode|Vis|1.2.30
vscode-java-debug|vsc|0.50.0
vscode-java-dependency|vsc|0.22.0
vscode-java-pack|vsc|0.25.11
vscode-java-test|vsc|0.38.2
vscode-maven|vsc|0.41.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vscaat:30438848
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
vsccc:30610678
3biah626:30602489
pyind779:30671433
f6dab269:30613381
pythonsymbol12:30671437
a9j8j154:30646983
showlangstatbar:30730054
vsccsb:30705552
azdwalk:30721579
pythonms35:30701012
pythonfmttext:30731395
pythoncmvfstr:30731969
fixshowwlkth:30730052
showsbindicator:30730056

```

</details>

**Comment by tamuratak** [comment]
McAfee Antivirus might be the cause. See https://github.com/microsoft/vscode/issues/178733#issuecomment-1500812938

**Comment by deepak1556** [comment]
Merging to https://github.com/microsoft/vscode/issues/178962

Please follow the workaround mentioned in https://github.com/microsoft/vscode/issues/178733#issuecomment-1500812938 until the issue is resolved.

**Comment by DeepaChegi** [comment]
Thank you. Adding an exclusion in McAfee resolved the issue.
