### ISSUE TITLE
MultiCursorPaste fails to spread lines of text

### ISSUE THREAD

**Issue by rdhar** [microsoft/vscode#181847]
#### Does this issue occur when all extensions are disabled?
Yes, as confirmed with Extension Bisect having all extensions disabled with v1.79.0-insider.

<details><summary>VS Code Insiders - System Info</summary><p>

- Version: 1.79.0-insider (user setup)
- Commit: 2c73d2651cc525b27fc697b820743098a204ec01
- Date: 2023-05-04T22:11:08.187Z
- Electron: 22.4.8
- Chromium: 108.0.5359.215
- Node.js: 16.17.1
- V8: 10.8.168.25-electron.0
- OS: Windows_NT x64 10.0.22621
- Sandboxed: Yes
</p>
</details> 

#### Steps to Reproduce:

1. Confirm that `"editor.multiCursorPaste": "spread",` is set by default. 
1. Get multiple cursors by <kbd>Alt</kbd>/<kbd>Option</kbd> + clicking on different lines of text. 
1. Select some text on each line with <kbd>Shift</kbd> + <kbd>→</kbd> then copy with <kbd>Ctrl</kbd>/<kbd>Cmd</kbd> + <kbd>C</kbd>.
1. Paste that text as-is across each line with <kbd>Ctrl</kbd>/<kbd>Cmd</kbd> + <kbd>V</kbd>.
1. Instead of the expected behaviour of `spread`, observe as the `full` selection of text is pasted at each cursor. 

Please feel free to let me know if I can help provide any further information to aid troubleshooting. 

Thank you for your time.

**Comment by andregreeff** [comment]
I'm experiencing the same issue.. quite surprised at this one actually, VSCode's multi cursor editing has always been so beautifully consistent and predictable. hope it gets fixed soon..

just for clarity, here's an animated GIF of the issue, using the same settings as @rdhar:

![VSCode 1 79 0 - multi cursor paste issue](https://user-images.githubusercontent.com/126144414/237009036-b50f9962-cf0a-4ffb-91c1-c97f0f11f73f.gif)

**Comment by gjsjohnmurray** [comment]
Probably #181486

Are you using the latest Insiders?

**Comment by andregreeff** [comment]
assuming this was aimed at me.. (:

> Are you using the latest Insiders?

that I am, yes.

with regards to the issue ID you referenced, I'd say possibly..? if I copy a single selection, then add multiple carets and paste, I *correctly* get a copy of my single selection at each caret. perhaps this is related to the fix for that one?

my next best idea is that it's possibly related to how VSCode is trying to retain the current text selection when pasting anything, but since I'm not sure how or why it's now doing that, this is just wild speculation. 🤷

**Comment by andregreeff** [comment]
@gjsjohnmurray could this perhaps be related to #181860?

**Comment by rdhar** [comment]
> Probably #181486
> Are you using the latest Insiders?
> —@gjsjohnmurray

Afraid so, yes, I am using the latest v1.79.0-insider (2023-05-04T22:11:08.187Z) without any extensions installed and I'm able to replicate this erroneous behaviour as @andregreeff kindly demonstrated.

However, #181486 describes a different bug that also happens to be about multiple cursor which has since been resolved by PR #181558 ~5 days ago.

---

> Could this perhaps be related to #181860?
> —@andregreeff

I reckon you're spot-on. And just as @trueliarx reported on #181860, the bug in this issue also appears to have been resolved on the very latest v1.79.0-insider (2023-05-09T05:23:39.976Z). 

More than happy to mark as resolved, if a but curious as to how it came about in the first. Thanks once again for your time to look into this on our behalf.
