### ISSUE TITLE
Support debug of cpp without C/C++ extension

### ISSUE THREAD

**Issue by zclllyybb** [microsoft/vscode#181872]
Before some force update a few days ago, I can't debug using the configuration of type of `cppdbg` without the `C/C++` extension.
That can be confirmed as caused by that update since all my friends meet the same situation. Can I ask why you made this change? Where can I find relative documents?

**Comment by roblourens** [comment]
I don't quite understand- vscode doesn't support debugging C/C++ without an extension, and never has
