### ISSUE TITLE
VS Code Crashed with "The Window Has Crashed"

### ISSUE THREAD

**Issue by twentyonegrams** [Microsoft/vscode#18188]
- VSCode Version: 1.8.1
- OS Version: Windows Server 2008 R2

Just installed Visual Studio Code on a VM running Windows Server 2008 R2. The installation ends with launching Visual Studio Code, then the CPU usage hits the roof and some minutes later Code is launched but with the  "The window has crashed" dialog. I try the Reopen button but it will just repeat itself. I have no choice but to close the window but that also mean I can't launch Visual Studio Code at all
Steps to Reproduce:

1. Launch Visual Studio Code by either
      a. click the desktop icon
      b. right click the desktop icon and select "Run As Administrator"
      c. run Code in command line prompt
      d. run "Code -n" in command line prompt
      e. run Code in a command windows running as Administrator

All of the above result in the same error

**Comment by bpasero** [comment]
@twentyonegrams is that VM having a single CPU core?

**Comment by twentyonegrams** [comment]
Yes it is a single processor VM. Would that be an issue?

Thanks,
Ben

**Comment by bpasero** [comment]
Yes: https://github.com/Microsoft/vscode/issues/17097
