### ISSUE TITLE
Hold on the popup when clicking the status bar

### ISSUE THREAD

**Issue by zanminkian** [microsoft/vscode#181811]
![image](https://user-images.githubusercontent.com/35495628/236807212-4edd13af-2e69-4597-9f76-381f89d3d489.png)
When hovering on the `{ }` icon of `{ } TypeScript` in status bar, a popup will appear.

After I click the `{ }` icon, I hope the popup will hold on. But actually, it will easily disappear.

It really annoy me when I want to change another TypeScript version.

**Comment by kunalvirk** [comment]
You should be able to move the cursor to click "Select Version" after hovering `{}`. It is working fine for me.

**Comment by DonJayamanne** [comment]
Thanks for filing this issue.

You can press the `Alt` key to keep the popup open (i.e. prevent it from getting closed).
Let me know if that does not work for you.

**Comment by zanminkian** [comment]
@DonJayamanne Hi, it doesn't works for me. Btw, I use macOs and github codespace (web) in the latest Edge.
