### ISSUE TITLE
VSCode uses way too much memory

### ISSUE THREAD

**Issue by pmullot** [microsoft/vscode#181806]
Type: <b>Performance Issue</b>

When launching vscode, even with the "disable-extensions" option on Linux (mint), **17** processes are started, using around 600Mb of Ram and more than **32 TB** of Virtual Memory

VS Code version: Code 1.78.0 (252e5463d60e63238250799aef7375787f68b4ee, 2023-05-03T20:09:46.685Z)
OS version: Linux x64 5.15.0-71-generic
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 9 5900X 12-Core Processor (24 x 2200)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|7, 8, 9|
|Memory (System)|31.27GB (25.33GB free)|
|Process Argv|--disable-extensions --crash-reporter-id 6878e7d1-5676-4556-8a79-e5a0600135e1|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|cinnamon|
|XDG_CURRENT_DESKTOP|X-Cinnamon|
|XDG_SESSION_DESKTOP|cinnamon|
|XDG_SESSION_TYPE|x11|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	   128	 24879	code main
    0	    32	 24882	   zygote
    0	   160	 24915	     gpu-process
    0	     0	 24923	       broker
    0	    32	 24883	   zygote
    0	     0	 24885	     zygote
    0	    64	 26140	window [2] (Issue Reporter)
    0	    32	 24921	   utility-network-service
    0	   288	 24940	window [1] (releaseDocumentation.ts - bbva-ibf-staffmanager - Visual Studio Code)
    0	    96	 24988	extensionHost [1]
    0	    96	 25109	     electron-nodejs (/usr/share/code/code --ms-enable-electron-run-as-node --max-old-space-size=3072 /usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js --serverMode partialSemantic --useInferredProjectPerProjectRoot --disableAutomaticTypingAcquisition --cancellationPipeName /tmp/vscode-typescript1000/1add7a3925dc09a25a13/tscancellation-b29396684448a0b57cd3.tmp* --locale en --noGetErrOnBackgroundUpdate --validateDefaultNpmLocation --useNodeIpc)
    0	   448	 25110	     electron-nodejs (/usr/share/code/code --ms-enable-electron-run-as-node --max-old-space-size=3072 /usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js --useInferredProjectPerProjectRoot --enableTelemetry --cancellationPipeName /tmp/vscode-typescript1000/1add7a3925dc09a25a13/tscancellation-927373756a8b34f731f2.tmp* --locale en --noGetErrOnBackgroundUpdate --validateDefaultNpmLocation --useNodeIpc)
    0	    64	 25125	       electron-nodejs (/usr/share/code/code --ms-enable-electron-run-as-node /usr/share/code/resources/app/extensions/node_modules/typescript/lib/typingsInstaller.js --globalTypingsCacheLocation /home/patrick/.cache/typescript/5.0 --enableTelemetry --typesMapLocation /usr/share/code/resources/app/extensions/node_modules/typescript/lib/typesMap.json --validateDefaultNpmLocation)
    0	    64	 25186	     electron-nodejs (/usr/share/code/code --ms-enable-electron-run-as-node /usr/share/code/resources/app/extensions/json-language-features/server/dist/node/jsonServerMain --node-ipc --clientProcessId=24988)
    0	    96	 25000	shared-process
    0	    64	 25041	     ptyHost
    0	     0	 26158	     /bin/sh -c /usr/bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0	     0	 26159	       /usr/bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0	    64	 25001	fileWatcher [1]
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (releaseDocumentation.ts - bbva-ibf-staffmanager - Visual Studio Code)
|    Folder (bbva-ibf-staffmanager): 2479 files
|      File types: py(589) pyc(347) ts(319) html(148) scss(134) js(111)
|                  map(106) json(62) svg(25) png(22)
|      Conf files: package.json(4) tsconfig.json(3) launch.json(2)
|                  tslint.json(2) settings.json(1) makefile(1)
|      Launch Configs: node(5) python;
```

</details>
Extensions disabled<details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vstes627:30244334
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
2e4cg342:30602488
pyind779:30671433
f6dab269:30613381
pythonsymbol12:30671437
2i9eh265:30646982
showlangstatbar:30730054
vsccsb:30705552
azdwalk:30721579
pythonms35:30701012
pythonfmttext:30731395
pythoncmv:30731968
fixshowwlkth:30730052

```

</details>

**Comment by bpasero** [comment]
Everything you say sounds reasonable to me and not like a performance issue or bug except for the virtual memory, that seems incredibly high, but I am also not entirely sure that amount of space is gone vs. reserved. Did you typo and meant to say GB instead of TB?

**Comment by pmullot** [comment]
Hi,

Thank you very much for such a quick response!

I wish I had made a typo...
[image: image.png]


My Pc OS runs on a 500GB NVMe, with another 2Tb traditional hard drive... I
don't really understand where all those TB are allocated from...

**Comment by pmullot** [comment]
You can see all the details in the attached screenshot

**Comment by bpasero** [comment]
I think you need to attach it again here, not via e-mail. It is not visible.

**Comment by pmullot** [comment]
On precision though, this last screenshot has been taken from a normal session of vsCode, not with the --disable-extensions flag.
The only difference is that there are more "code" processes. When run with said flag, the VMem consumption is still the same, except there are less processes

**Comment by bpasero** [comment]
Just curious, what does Chrome report as browser when you check it out? We use a framework quite similar to Chrome.

**Comment by pmullot** [comment]
It reports the same...
So I guess it's more of an Electron issue.
In any case, after checking more stuff, it seems that those TBs aren't really an issue. They don't look real to me. I only have 32Gb of Ram and the swap file is at 0% used.

And after rebooting my machine twice, it seems that the slowness of vscode was gone... dunno why.
Sorry to have wasted your time.

![image](https://user-images.githubusercontent.com/75703/236845002-f546805e-64c2-40a1-9b40-ef07eb3632ea.png)
