### ISSUE TITLE
Javascript Error

### ISSUE THREAD

**Issue by Speedy9d2** [microsoft/vscode#181843]
Type: <b>Bug</b>

I've checked on multiple different software and VS Code is the only one that doesn't update the count variable. 

var output = [];
var count = 1;

function fizzBuzz() {
    output.push(count);
    count++;
    console.log(output);
}

fizzBuzz();

VS Code version: Code 1.78.0 (Universal) (252e5463d60e63238250799aef7375787f68b4ee, 2023-05-03T20:11:00.813Z)
OS version: Darwin x64 22.4.0
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7267U CPU @ 3.10GHz (4 x 3100)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|4, 4, 5|
|Memory (System)|8.00GB (0.01GB free)|
|Process Argv|--crash-reporter-id eac995f4-6e64-4ab8-b94f-4572b79bac6a|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
simple-react-snippets|bur|1.2.7
vscode-eslint|dba|2.4.0
vscode-jest-runner|fir|0.4.60
code-runner|for|0.12.0
vscode-language-babel|mgm|0.0.39
LiveServer|rit|5.7.9
synthwave-vscode|Rob|0.1.15
ayu|tea|1.0.5
open-in-browser|tec|2.0.0
JavaScriptSnippets|xab|1.8.0

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vscaac:30438847
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
3biah626:30602489
pyind779:30671433
f6dab269:30613381
pythonsymbol12:30671437
a9j8j154:30646983
6233i204:30730053
vsccsb:30705552
azdwalk:30721579
pythonms35:30701012
pythonfmttext:30731395
pythoncmvfstr:30731969
fixhidewlkth:30730051
pythongtdpathcf:30731979

```

</details>

**Comment by roblourens** [comment]
Likely https://github.com/microsoft/vscode/issues/181485
