### ISSUE TITLE
Menu shows "No Configurations" when .vscode folder is on the root of the drive and the root drive is opened in VS Code

### ISSUE THREAD

**Issue by ejohn54** [Microsoft/vscode#18183]
- VSCode Version: 1.8.1
- OS Version: Windows 10

Steps to Reproduce:

1. Ensure you have installed the PowerShell extensions for VS Code.
2. Create a file "test.ps1" on the root of a USB drive (e.g. D:\)
3. Open the folder D:\ from Visual Studio Code.
4. Put the following line in the ps1 file:  Write-Host "Testing"
5. Save the ps1 file.
6. Press F5 to debug.
7.  VS Code will create a .vscode folder in the root of the USB drive and create a "launch.json" file with a template to launch the current file.  Save the launch.json file.
8. Switch back to the .ps1 file and press F5 again.
9. VS Code still says "Please set up the launch configuration file for your application." and switches to the launch.json file.  The debug drop down menu is disabled and shows "No Configurations"

Expected results:
The debug drop down should show the launch configurations and allow debugging.

The Debug console has the following error:

messageService.ts:126
Unable to open 'launch.json': File not found (d:\.vscode\launch.json).: Error: Unable to open 'launch.json': File not found (d:\.vscode\launch.json).
    at Object.g [as create] (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:30:20765)
    at t.doHandleSetInputError (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:126:3451)
    at file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:126:3145
    at Object.v [as _notify] (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:32:13263)
    at Object.enter (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:32:16768)
    at _run (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:32:18089)
    at _chainedError (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:32:17448)
    at n (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:32:15271)
    at then (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:32:18898)
    at Object.enter (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:32:15340)e.doShow @ messageService.ts:126

**Comment by isidorn** [comment]
@ejohn54 so the launch.json get properly created?
What happens if you change a file outside of vscode repository while vscode is open, does vscode pick up that change?

@bpasero looks like file events are missing or some permission problems.

**Comment by bpasero** [comment]
I cannot reproduce, I just tried with a USB stick plugged in on Windows 10 and the launch config was showing up just fine.

**Comment by ejohn54** [comment]
Yes the launch.json file does get created in the subfolder ".vscode".

I have reproduced this issue on two Windows 10 computers with three different USB drives.
It only happens when you open the root drive as a folder.

I have attached some screen shots also.   I am not sure what else I can provide.


![drive](https://cloud.githubusercontent.com/assets/16762859/21721682/0343f9b4-d3ef-11e6-98fd-a510cb21f1df.PNG)
![drive2](https://cloud.githubusercontent.com/assets/16762859/21721685/0948731c-d3ef-11e6-9121-7734c306119a.PNG)
![vscode1](https://cloud.githubusercontent.com/assets/16762859/21721687/0c2b7f84-d3ef-11e6-9487-d5bcb0cc2470.PNG)
![vscode2](https://cloud.githubusercontent.com/assets/16762859/21721689/0e5dbde4-d3ef-11e6-9c96-99b70a8523cc.PNG)
![vscode3](https://cloud.githubusercontent.com/assets/16762859/21721694/10eec832-d3ef-11e6-9128-87fd743f1386.PNG)

**Comment by bpasero** [comment]
@isidorn can you repro that?

**Comment by isidorn** [comment]
@bpasero let me try

**Comment by isidorn** [comment]
I can repro
1. Open vscode on a root folder
2. Create a new launch.json -> notice how the drop down is not updated

After more experimenting file events are working fine but the configuration service seems not be emitting configuraiton change events.

**Comment by bpasero** [comment]
I can reproduce.

**Comment by bpasero** [comment]
This is a bug in paths library:

`paths.relative("C:\\", "C:\\foo.txt")` returns "`..\foo.txt`" instead of `foo.txt`

As such our assumptions for checking for `settings.json` inside the `.vscode` folder all fail.

**Comment by jrieken** [comment]
I'd reckon not to use that function anymore but the use the nodes-variant which is more correct. The investment to fix our custom method, which we actually only really required in a nodejs context, isn't justified

**Comment by bpasero** [comment]
+1 for moving off to node, but unfortunately this comes in from many places in common/browser layer.

Anyway, I think I found a fix by ignoring trailing slashes in paths when doing the math. The problematic part was that "`C:\`" got normalized to "`C:/`" and then when you split it by the path separator ends up being `["C:", ""]` (note the extra empty segment).

**Comment by jrieken** [comment]
The problem is that we don't honour the path prefix, like `c:`, `file://`, or `//localhost/`. That is a source for trouble but also very tricky to get right. 

I see that we have references to `browser` or `common` that IMO that is artificial because the standalone editor doesn't use any of that API and iff it doesn't require a working implementation of `IWorkspace`. The rest is in the git land which is VS Code, so nodejs only

**Comment by bpasero** [comment]
👍  https://github.com/Microsoft/vscode/issues/18350
