### ISSUE TITLE
Unable to move or rename the file/directory when the affected file has been opened in the editor

### ISSUE THREAD

**Issue by liuweiGL** [microsoft/vscode#181836]
Type: <b>Bug</b>

I am unable to reproduce it in a simple (with a small number of files/directories) project, but I can provide screenshots.

I have disabled all the plugins and restart the editor before testing, the brighter plugin list is due to the screen flickering caused by enabling HDR.

I apologize, but the GIF image exceeds the limitations of GitHub [screengif.zip](https://github.com/microsoft/vscode/files/11424276/screengif.zip)

This issue should have been introduced in the last two versions, and it has been causing me a lot of frustration, please help me.

---

VS Code version: Code 1.78.0 (252e5463d60e63238250799aef7375787f68b4ee, 2023-05-03T20:09:00.748Z)
OS version: Windows_NT x64 10.0.19045
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i5-11400 @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.88GB (15.28GB free)|
|Process Argv|C:\\Users\\liuwei\\Desktop\\gitlab\\eastcoal-pc --crash-reporter-id e8f9661f-456c-4980-959e-530a1e168dd0 --crash-reporter-id e8f9661f-456c-4980-959e-530a1e168dd0|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|2.4.0
prettier-vscode|esb|9.12.0
copilot|Git|1.86.82
vscode-pont|jas|1.5.7
vscode-uuid-generator|mot|0.4.1
vscode-language-pack-zh-hans|MS-|1.78.2023050309
material-icon-theme|PKi|4.27.0
comment-divider|sta|0.4.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vscaat:30438848
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
vscccc:30610679
282f8724:30602487
pyind779:30671433
f6dab269:30613381
pythonsymbol12:30671437
showlangstatbar:30730054
azdwalk:30721579
pythonms35:30701012
pythonfmttext:30731395
pythoncmv:30731968
fixshowwlkth:30730052
pythongtdpath:30731978

```

</details>

**Comment by lramos15** [comment]
Does anything appear in the dev tools? `CTRL + SHIFT + P` -> `Toggle Developer Tools`

**Comment by bpasero** [comment]
This is likely https://github.com/microsoft/TypeScript/issues/54087

**Comment by liuweiGL** [comment]
Yes, I also found that the code process is occupying the file.

**Comment by lramos15** [comment]
@bpasero Can we show some sort of error here rather than spinning for awhile

**Comment by liuweiGL** [comment]
`Developer Tools Console` display the following error:
```log
 ERR NoPermissions (FileSystemError): Error: EPERM: operation not permitted, rename 'c:\Users\liuwei\Desktop\gitlab\eastcoal-pc\packages\common\src\components\ProTable' -> 'c:\Users\liuwei\Desktop\gitlab\eastcoal-pc\packages\common\src\components\ProTables'
    at t.create (C:\Program Files\Microsoft VS Code\resources\app\out\vs\code\electron-main\main.js:37:3882)
    at a (C:\Program Files\Microsoft VS Code\resources\app\out\vs\code\electron-main\main.js:37:4012)
    at t.Y (C:\Program Files\Microsoft VS Code\resources\app\out\vs\code\electron-main\main.js:42:38452)
    at t.rename (C:\Program Files\Microsoft VS Code\resources\app\out\vs\code\electron-main\main.js:42:36611)
notificationsAlerts.ts:40 NoPermissions (FileSystemError): Error: EPERM: operation not permitted, rename 'c:\Users\liuwei\Desktop\gitlab\eastcoal-pc\packages\common\src\components\ProTable' -> 'c:\Users\liuwei\Desktop\gitlab\eastcoal-pc\packages\common\src\components\ProTables'
    at t.create (C:\Program Files\Microsoft VS Code\resources\app\out\vs\code\electron-main\main.js:37:3882)
    at a (C:\Program Files\Microsoft VS Code\resources\app\out\vs\code\electron-main\main.js:37:4012)
    at t.Y (C:\Program Files\Microsoft VS Code\resources\app\out\vs\code\electron-main\main.js:42:38452)
    at t.rename (C:\Program Files\Microsoft VS Code\resources\app\out\vs\code\electron-main\main.js:42:36611)
c @ notificationsAlerts.ts:40
(anonymous) @ notificationsAlerts.ts:28
invoke @ event.ts:862
deliver @ event.ts:1075
fire @ event.ts:1031
addNotification @ notifications.ts:204
error @ notificationService.ts:130
onFinish @ fileActions.ts:988
await in onFinish (async)
(anonymous) @ explorerViewer.ts:566
(anonymous) @ functional.ts:17
(anonymous) @ explorerViewer.ts:609
(anonymous) @ dom.ts:88
log.ts:441   ERR Error: EPERM: operation not permitted, rename 'c:\Users\liuwei\Desktop\gitlab\eastcoal-pc\packages\common\src\components\ProTable' -> 'c:\Users\liuwei\Desktop\gitlab\eastcoal-pc\packages\common\src\components\ProTables': NoPermissions (FileSystemError): Error: EPERM: operation not permitted, rename 'c:\Users\liuwei\Desktop\gitlab\eastcoal-pc\packages\common\src\components\ProTable' -> 'c:\Users\liuwei\Desktop\gitlab\eastcoal-pc\packages\common\src\components\ProTables'
    at t.create (C:\Program Files\Microsoft VS Code\resources\app\out\vs\code\electron-main\main.js:37:3882)
    at a (C:\Program Files\Microsoft VS Code\resources\app\out\vs\code\electron-main\main.js:37:4012)
    at t.Y (C:\Program Files\Microsoft VS Code\resources\app\out\vs\code\electron-main\main.js:42:38452)
    at t.rename (C:\Program Files\Microsoft VS Code\resources\app\out\vs\code\electron-main\main.js:42:36611)
```

**Comment by liuweiGL** [comment]
![image](https://github.com/microsoft/vscode/assets/21048878/7e891039-f5a6-4ffe-afb4-5855f98dfe9b)

**Comment by liuweiGL** [comment]
![image](https://github.com/microsoft/vscode/assets/21048878/5b61463e-390b-4a4c-b1c1-0ec03530ff71)

**Comment by liuweiGL** [comment]
![image](https://github.com/microsoft/vscode/assets/21048878/8233eceb-c198-4050-8b59-35cda8e94e16)

**Comment by bpasero** [comment]
There should be an error bubbling up from the call to delete.

**Comment by lramos15** [comment]
Thanks @liuweiGL, my guess is this is a typescript bug but there is also a bug on our side about the error not being shown.

**Comment by liuweiGL** [comment]
Let me know if you need anything 😁
