### ISSUE TITLE
Default paste into Markdown from OneNote is image

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#181882]
Copy pasting regular text from a OneNote page now pastes an image:

https://github.com/microsoft/vscode/assets/22350/d62dbcf2-c479-4e9e-9df8-f3b7f42f1312

I only found a way out of this by completely disabling the feature with `editor.pasteAs.enabled` set to `false`.

Should we provide user-level defaults (ie "always prefer text")?

**Comment by mjbvz** [comment]
Duplicate of #181886
