### ISSUE TITLE
Odd javascript formatting

### ISSUE THREAD

**Issue by QwertyZW** [Microsoft/vscode#18181]
- VSCode Version: 1.8.1
- OS Version: Windows 10

Steps to Reproduce:

Auto formatting (alt-shift-f)

```
returnspromise()
.then(()=>{
    
})
```

Produces:

```
returnspromise()
    .then(() => {

    })
```

Expected:

```
returnspromise()
.then(()=>{
    
})
```

The point is that I'd like to format other parts of the code while my . calls indentation remains the same. How would I go about configuring this? If it's possible

**Comment by mjbvz** [comment]
This is the expected formatting. Since indenting method chains like this is the common style for js, we do not have a formatting option for disabling the indent.

I suggest looking to see any extensions offer the type of formatting control you are after.
