### ISSUE TITLE
SAP Fiori Tools - Connection to system

### ISSUE THREAD

**Issue by z3ll3-mndst** [microsoft/vscode#181827]
Type: <b>Bug</b>

Updating VS Code from ver. 1.77.3 to ver. 1.78 we found an issue. Connection to ABAP On-Premise systems doesn't work anymore. We always get "self-signed certificate" error ("The system URL is using a self-signed security certificate").

![image](https://user-images.githubusercontent.com/122386542/236873054-19f98ea6-e95a-4a45-bc1e-982ec85cfca7.png)

In VS Code 1.77.3 we solved using instructions found in following link: https://help.sap.com/docs/SAP_FIORI_tools/17d50220bcd848aa854c9c182d65b699/4b318bede7eb4021a8be385c46c74045.html?locale=en-US, but in ver. 1.78 it doesn't work.

To reproduce issue follow these steps:
- install SAP Fiori Tools extension;
- add SAP connection to ABAP On-Premise system using "SAP Systems" menu in SAP Fiori Tools
- Fill SAP System Details form with data
- Save and click on "Test Connection" button

VS Code version: Code 1.77.3 (704ed70d4fd1c6bd6342c436f1ede30d1cff4710, 2023-04-12T09:16:02.548Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|12th Gen Intel(R) Core(TM) i7-12700H (20 x 2688)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.70GB (2.15GB free)|
|Process Argv|--crash-reporter-id cc739aa8-76d7-4c8e-8040-e98a248c015a --crash-reporter-id cc739aa8-76d7-4c8e-8040-e98a248c015a --crash-reporter-id cc739aa8-76d7-4c8e-8040-e98a248c015a|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (64)</summary>

Extension|Author (truncated)|Version
---|---|---
angular-material|1to|0.13.0
vscode-sqlite|ale|0.14.1
vscode-angular2-files|ale|1.6.4
ng-template|Ang|16.0.0
vscode-icontheme-nomo-dark|be5|1.3.6
simple-react-snippets|bur|1.2.7
npm-intellisense|chr|1.4.4
path-intellisense|chr|2.8.4
angular-schematics|cyr|5.3.1
vscode-eslint|dba|2.4.0
es7-react-js-snippets|dsz|4.4.3
EditorConfig|Edi|0.16.4
prettier-vscode|esb|9.12.0
auto-close-tag|for|0.5.14
auto-rename-tag|for|0.1.10
copilot|Git|1.85.75
vscode-mocha-test-adapter|hbe|2.14.1
vscode-test-explorer|hbe|2.21.1
rest-client|hum|0.25.1
ui5plugin|ilj|1.3.0
angular2-switcher|inf|0.4.0
angular-file-changer|joh|0.0.4
angular-essentials|joh|13.0.0
Angular2|joh|13.0.0
vscode-peacock|joh|4.2.2
angular-extension-pack|loi|1.1.0
ui5-xml-support|m85|0.6.4
rainbow-csv|mec|3.7.0
Angular-BeastCode|Mik|10.0.3
vscode-language-pack-it|MS-|1.77.2023041209
remote-containers|ms-|0.292.0
remote-ssh|ms-|0.100.0
remote-ssh-edit|ms-|0.84.0
js-debug-nightly|ms-|2023.5.317
remote-explorer|ms-|0.4.0
test-adapter-converter|ms-|0.1.7
vscode-react-native|msj|1.11.0
sqltools|mtx|0.27.1
arrr|obe|0.1.3
material-icon-theme|PKi|4.27.0
quicktype|qui|12.0.46
typescript-hero|rbb|3.0.0
karma-problem-matcher|rct|1.0.1
vscode-xml|red|0.25.0
yeoman-ui|SAP|1.11.0
app-studio-toolkit|SAP|1.13.2
sap-guided-answers-extension|SAP|1.20.6
sap-hana-driver-for-sqltools|SAP|0.2.1
vscode-ui5-language-assistant|SAP|4.0.14
xml-toolkit|SAP|1.1.0
sap-ux-annotation-modeler-extension|SAP|1.9.5
sap-ux-application-modeler-extension|SAP|1.9.5
sap-ux-fiori-tools-extension-pack|SAP|1.9.5
sap-ux-help-extension|SAP|1.9.5
sap-ux-service-modeler-extension|SAP|1.9.5
vsc-extension-odata-csdl-modeler|SAP|1.0.9
vscode-cds|SAP|6.8.0
vscode-wing-cds-editor-vsc|SAP|23.4.0
angular-cli|seg|0.0.19
simontest|Sim|1.9.10
autoimport|ste|1.5.4
move-ts|str|1.12.0
vscode-icons|vsc|12.4.0
JavaScriptSnippets|xab|1.8.0

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
3biah626:30602489
pyind779:30671433
89544117:30613380
pythonsymbol12:30671437
a9j8j154:30646983
6233i204:30730053
azdwalk:30721579
pythonms35:30701012
pythonfmttext:30731395
fixshowwlkth:30730052

```

</details>

**Comment by chrmarti** [comment]
Tracked in https://github.com/microsoft/vscode/issues/181404 as a candidate for a 1.78.x recovery release.
