### ISSUE TITLE
Have a way to disable max-height on comments 

### ISSUE THREAD

**Issue by kazemicode** [microsoft/vscode#181846]
PR #180044 introduced a max-height on comments, which goes against my team's use case when using the [CodeTour extension](https://github.com/microsoft/codetour). Since our tours have animated GIFs that support our hands-on coding labs, the reduced max-height makes it impossible for a user to see entire images in the comment frame at once, which imposes a negative learner experience. (See: https://www.youtube.com/watch?v=h0F8_-Te8p4 for comparison across versions).

Proposed feature is to allow a user to set a max-height rather than imposing a max-height.

**Comment by gjsjohnmurray** [comment]
I also think it should be settable through the API. My original [commit](https://github.com/microsoft/vscode/pull/180044/commits/27c900d33a8fd1c1fb451580fc8321a806854206) on the PR has a comment exchange with @alexr00 about this at the place where I originally hardwired it.

**Comment by alexr00** [comment]
Generally we try not to add API unless we see a clear case for having it. At the time @gjsjohnmurray suggested the max height I wasn't aware of a use case that would require a comment peek view. 

@kazemicode your case makes sense, and makes the case for having API for this. I would make this API rather than user configurable.

**Comment by kazemicode** [comment]
Yes, making the max-height configurable via the API makes perfect sense, since any extension can be configured with that functionality to set a max-height attribute that makes sense for the use case.

**Comment by alexr00** [comment]
@kazemicode I'm not sure yet which would be default. I will discuss with our UX folks and see what they prefer.

**Comment by kazemicode** [comment]
@alexr00 My humble preference would be to adopt the old behavior as the default. Though the CodeTour extension is open source, it’s only seen one update in the past year. My team has a stale PR from 2021 on the CodeTour repo that was never commented on, so I’m afraid that even if we opened a PR with a fix for the max-height problem, it might not ever get accepted and merged. On the other hand, my team has been discussing forking CodeTour so that we can control the addition of new functionality and bug fixes.

**Comment by alexr00** [comment]
There wasn't enough interest in adding API for this, so I added the user setting `"comments.maxHeight"`.

**Comment by kazemicode** [comment]
@alexr00 thanks! Is `comments.maxHeight` a boolean? If so, is the default `true` (maintaining the `maxHeight` as `20em` by default) or `false` (no `maxHeight` defined?

**Comment by alexr00** [comment]
It is a boolean and the default is true, meaning the max height of a comment will be 20em.

**Comment by alexr00** [comment]
Thanks for verifying!
