### ISSUE TITLE
`treeView.reveal` with `expand: 3` only expands the first level 3 folder

### ISSUE THREAD

**Issue by david-tejada** [microsoft/vscode#181889]
- VS Code Version: 1.79.0-insider
- OS Version: macOS 12.6.3

I am working on a file explorer tree view extension and `treeView.reveal` doesn't work properly if `expand` is 2 or 3. When expand is 3 only the first level 3 folder expands. I have checked and `getChildren` doesn't get called for the rest of the level 3 folders. If I call `reveal` again with `expand: 3` the rest of the level 3 folders expand. 

When I use `treeView.reveal` with `expand` 2 or 3 on a large folder (hundreds of items) the promise never fulfills even though the folder expands (at least up to level 2).

I don't get any error in any of the two cases.

**Comment by alexr00** [comment]
@david-tejada can you share a minimal example that reproduces this issue?

**Comment by david-tejada** [comment]
Sure thing, here you have it: [david-tejada/vscode-expand-treeitem: Minimal reproducible example for vscode issue #181889](https://github.com/david-tejada/vscode-expand-treeitem)

**Comment by alexr00** [comment]
Thank you for the repro repo!

**Comment by david-tejada** [comment]
No problem, thanks for the fix!
