### ISSUE TITLE
Timed out activating extensions for task providers

### ISSUE THREAD

**Issue by microhobby** [microsoft/vscode#181844]
Type: <b>Bug</b>

1- Open the command palet
2- Run task
3- Activating Extensions (will show and will take some time...)
4- Nothing happens

VS Code version: Code 1.78.0 (252e5463d60e63238250799aef7375787f68b4ee, 2023-05-03T20:09:00.748Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: Yes
Remote OS version: Linux x64 6.3.0-MicroHobby-win11+

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 4800H with Radeon Graphics          (16 x 2894)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|63.37GB (38.11GB free)|
|Process Argv|--crash-reporter-id a5996d7f-754d-4ba0-84ae-a94457aa5aed|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-22.04|
|OS|Linux x64 6.3.0-MicroHobby-win11+|
|CPUs|AMD Ryzen 7 4800H with Radeon Graphics (16 x 2894)|
|Memory (System)|31.04GB (27.94GB free)|
|VM|0%|
</details><details><summary>Extensions (103)</summary>

Extension|Author (truncated)|Version
---|---|---
language-x86-64-assembly|13x|3.0.0
better-comments|aar|3.0.2
icons-carbon|ant|0.2.6
chalice-icon-theme|art|1.2.23
vscode-icontheme-nomo-dark|be5|1.3.6
beardedicons|Bea|1.12.0
simple-icons|com|0.1.6
arm|dan|1.7.4
udev-rules|dpk|1.0.1
apacheconf-snippets|eim|1.3.0
el-vsc-product-icon-theme|ElA|0.1.8
LogFileHighlighter|emi|2.16.0
vscode-great-icons|emm|2.1.92
file-icons|fil|1.0.29
remotehub|Git|0.56.0
vscode-systemd-support|han|1.0.1
output-colorizer|IBM|0.1.2
monkey-patch|ioc|0.1.23
better-cpp-syntax|jef|1.17.2
better-dockerfile-syntax|jef|1.0.2
better-shellscript-syntax|jef|1.6.1
bats|jet|0.1.9
icons-octicons|joa|0.1.0
vscode-peacock|joh|4.2.2
vscode-icon-theme|jtl|1.6.6
kconfig|luv|1.0.3
feather-vscode|mel|1.0.1
3bc|mic|0.0.1
gambas3|mic|0.0.2
fluent-icons|mig|0.0.18
theme-monokai-pro-vscode|mon|1.2.1
vscode-apache|mrm|1.2.0
jupyter-keymap|ms-|1.1.0
remote-containers|ms-|0.292.0
remote-ssh|ms-|0.100.0
remote-ssh-edit|ms-|0.84.0
remote-wsl|ms-|0.78.4
vscode-remote-extensionpack|ms-|0.24.0
azure-repos|ms-|0.32.0
remote-explorer|ms-|0.4.0
remote-repositories|ms-|0.34.0
remote-server|ms-|1.1.0
file-and-folder-icons|nex|1.0.4
gdb-syntax|pie|0.3.2
material-product-icons|PKi|1.5.0
devicetree|plo|0.1.1
shebang-snippets|rpi|0.1.4
bootstrap-product-icons|rub|1.0.2
bunker|sld|1.1.6
errorlens|use|3.11.0
icons-tabler|zgu|0.0.5
material-theme|zhu|3.15.8
riscv|zhw|0.0.8
linkerscript|Zix|1.0.3
dark-synthwave-vscode|Aar|1.0.3
typewriterscrollmode|and|0.1.1
vscode-color-picker|Ant|0.0.4
asciidoctor-vscode|asc|2.9.8
better-toml|bun|0.3.2
vscode-markdownlint|Dav|0.50.0
vscode-eslint|dba|2.4.0
vscode-wasm|dts|1.4.1
gitlens|eam|13.5.0
shell-format|fox|7.2.5
copilot|Git|1.86.82
vscode-pull-request-github|Git|0.62.0
todo-tree|Gru|0.0.226
vscode-ansi|ili|1.1.6
taskrunnercodeplus|mic|0.0.10
vscode-arm64|MKo|1.0.6
vscode-docker|ms-|1.25.0
csharp|ms-|1.25.7
isort|ms-|2022.8.0
pylint|ms-|2023.4.0
python|ms-|2023.8.0
vscode-pylance|ms-|2023.5.10
jupyter|ms-|2023.4.1011241018
jupyter-keymap|ms-|1.1.0
jupyter-renderers|ms-|1.0.15
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-slideshow|ms-|0.1.5
cpptools|ms-|1.15.4
cpptools-extension-pack|ms-|1.3.0
live-server|ms-|0.4.7
makefile-tools|ms-|0.7.0
powershell|ms-|2023.5.0
wati|Nat|1.1.5
indent-rainbow|ode|8.3.1
vscode-rapidapi-client|Rap|1.10.2
vscode-services|rap|1.0.2
vscode-xml|red|0.25.0
vscode-yaml|red|1.12.2
synthwave-vscode|Rob|0.1.15
avr-support|roc|0.0.1
bash-beautify|sha|0.1.1
markdown-preview-enhanced|shd|0.6.8
slint|Sli|1.0.2
code-spell-checker|str|2.20.4
code-spell-checker-portuguese-brazilian|str|2.0.12
tcb-vscode|Tor|0.0.10
vscode|uno|0.9.4
vscode-lldb|vad|1.9.1
vscode-wakatime|Wak|24.0.10

(38 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
vsccc:30610678
2e4cg342:30602488
pyind779:30671433
89544117:30613380
pythonsymbol12:30671437
showlangstatbar:30730054
vsctsb:30705553
azdwalk:30721579
pythonms35:30701012
pythonfmttext:30731395
pythoncmv:30731968
fixshowwlkth:30730052
hidesbindicator:30730055
pythongtdpath:30731978

```

</details>

**Comment by microhobby** [comment]
Probably some extension that is using task provider is crashing 🤷‍♂️? I checked the developer tools and the host logs, but did not find the root cause. There is some other stuff that I can do to investigate this?

**Comment by microhobby** [comment]
Anyway, it seems to be a problem in the Uno Platform extension https://github.com/unoplatform/uno/issues/12210. But I only came to this conclusion by bisecting the extensions. There was no log other than `Timed out activating extensions for task providers` in the Developer Console.

To maintainers, I don't think an extension should break built-in functionality like listing and executing tasks, this sounds very wrong to me.

**Comment by meganrogge** [comment]
already fixed! 

https://github.com/microsoft/vscode/issues/173384
