### ISSUE TITLE
Crash when starting on native wayland, but only when restoring last session

### ISSUE THREAD

**Issue by KayJay7** [microsoft/vscode#181805]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.78.0
- OS Version: Fedora 38 with Gnome 44.1

Steps to Reproduce:

1.  Open a project and quit with `window.restoreWindows` set to `all`
2.  Retart code with `--ozone-platform-hint=auto` on wayland
3.  Code crashes

Disabling extension does nothing. Restarting with `-n` or setting `restoreWindows` to `none` fixes the problem. Starting without `--ozone-platform-hint` (and thus running on xwayland) fixes the issue.

Verbose output  with `WAYLAND_DEBUG=1 code --ozone-platform-hint=auto --enable-features=UseOzonePlatform --verbose --log=debug --crash-reporter-directory /home/alvise/vscode-crash`:
[output.txt](https://github.com/microsoft/vscode/files/11420077/output.txt)

Journalctl log:
[log.txt](https://github.com/microsoft/vscode/files/11420088/log.txt)

Crash report:
[vscode-crash.zip](https://github.com/microsoft/vscode/files/11420089/vscode-crash.zip)

Correction: sometimes adding `-n` doesn't solve the issue. But disabling `restoreWindows` always does.

**Comment by strifel** [comment]
I do have the same issue

**Comment by dr-br** [comment]
Same issue here:
- VS Code Version: 1.78.0
- OS Version: Manjaro Linux with Gnome 44.1
- flags: `--enable-features=UseOzonePlatform`, `--ozone-platform=wayland`
- Starting w/o extensions: same behavior

**Comment by flyingfishflash** [comment]
Same issue here, Archlinux, ditto also on flags/extensions. Started w/ 1.78.0

**Comment by joshjavier** [comment]
Same issue on EndeavourOS Sway. Running with flag `--ozone-platform-hint=auto` works on 1.77.3 (version before upgrade) but causes a crash when starting on 1.78.1.

For now, I'm running VS Code on xwayland which doesn't cause the window to crash.

**Comment by inalone** [comment]
Same here issue here - with or without extensions this issue occurs.

**Comment by 0bCdian** [comment]
Same exact issue, removing the flags and running under xwayland works normally.

**Comment by ugudango** [comment]
I'm having this issue as well. I'm running an AMD/Nvidia setup. Same flags, same issues.

**Comment by deepak1556** [comment]
Thanks for the crash logs, merging to https://github.com/microsoft/vscode/issues/181805 since they share the same trace.

**Comment by kaechele** [comment]
@deepak1556 Sorry, did you mean #181533? Because you self-referenced this issue in your comment.

**Comment by deepak1556** [comment]
Sorry yeah it should be https://github.com/microsoft/vscode/issues/181533

**Comment by KorigamiK** [comment]
[This fixes it](https://github.com/microsoft/vscode/issues/181533#issuecomment-1597187136)  for me
