### ISSUE TITLE
How to setup the c_cpp_properties.json to create a local database and look it up for symbol references.

### ISSUE THREAD

**Issue by rahulagr** [Microsoft/vscode#18189]
- VSCode Version: 1.8.1
- OS Version: Mac OS X 10.12.2

My code lives on a NFS mounted partition (linux server). I am launching Microsoft Code on my Mac, and using NFS mount to access the files.

The file search and symbol reference is very slow currently. I want to create a local database, and use that database to do symbol reference and file search. Please let me know if it is possible, and if so, what exactly needs to be configured and where. I tried to search for c_cpp_properties.json documentation, but didn't find anything relevant.

Steps to Reproduce:
1. 
2.

**Comment by chrmarti** [comment]
There is currently no cache for the file lookup/search, we will investigate adding one as part of #15382. Moving to the cpptools in case there is a cpp specific solution/answer to the symbol cache.

**Comment by chrmarti** [comment]
This issue was moved to Microsoft/vscode-cpptools#433

**Comment by rahulagr** [comment]
What about the symbol search if not the file search? Is there a cache for it? If so, what is required to create a local cache.

**Comment by rahulagr** [comment]
Is there a cscope plugin for Visual Studio code?
