### ISSUE TITLE
keyboard navigation can cause terminal to lose styles

### ISSUE THREAD

**Issue by SimonSiefke** [microsoft/vscode#181838]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.78.0
- OS Version: Ubuntu 23.04

Steps to Reproduce:

1. Open a terminal
2. Focus on the terminal actions (at the top right of the panel)
3. Press tab two times
4. The terminal text loses all styles and becomes white

https://user-images.githubusercontent.com/23744935/236915730-9d30c735-c020-448c-9947-9156882bc139.mp4

**Comment by meganrogge** [comment]
I believe this is already fixed, can you see if you can reproduce in the [Insiders build](https://code.visualstudio.com/insiders)?
/label info-needed

**Comment by SimonSiefke** [comment]
The issue is present in vscode insiders as well.

**Comment by SimonSiefke** [comment]
@meganrogge Are you able to reproduce the issue or maybe can I help with providing any more info?
