### ISSUE TITLE
'Problems' pane remembers issues for deleted/renamed files

### ISSUE THREAD

**Issue by stefanb2** [microsoft/vscode#181802]
_Followup from https://github.com/microsoft/vscode/issues/66982#issuecomment-1534356293_

It was recommended that I report this specific problem as a separate issue. When I rename/delete a TS module, that has been flagged with problems, then the 'Problems' pane remembers the issues for the old file, although it is gone.

Restarting TS or ESLint server doesn't clear those flagged problems. I need to create the file again, then the empty content is parsed and the flagged problems get cleared.

Does this issue occur when all extensions are disabled?: **DON'T KNOW** (well, probably *NO* as the problems are owned by TS/eslint plugins...)

- VS Code Version: 
~~~
Version: 1.78.0
Commit: 252e5463d60e63238250799aef7375787f68b4ee
Date: 2023-05-03T20:09:46.685Z
Electron: 22.4.8
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Linux x64 6.2.14-300.fc38.x86_64
Sandboxed: No
~~~
- OS Version: Fedora 38, KDE Plasma, Wayland

Steps to Reproduce:

1. Add `src/dummy.ts` to project with the following contents
~~~ts
type BrokenSyntax {
  dummy: number
}

// NOTE: this is important: the module needs to be imported into the project
export const dummy = () => { /* ... */ }
~~~
2. The file `src/dummy.ts` (and the whole project tree where the file is located) is flagged **red** in the explorer and I see 2 problems in the Problems pane for `src/dummy.ts`
~~~json
[{
	"resource": "..../src/dummy.ts",
	"owner": "eslint",
	"severity": 8,
	"message": "Parsing error: '=' expected.",
	"source": "eslint",
	"startLineNumber": 1,
	"startColumn": 18,
	"endLineNumber": 1,
	"endColumn": 18
},{
	"resource": ".../src/dummy.ts",
	"owner": "typescript",
	"code": "1005",
	"severity": 8,
	"message": "'=' expected.",
	"source": "ts",
	"startLineNumber": 1,
	"startColumn": 19,
	"endLineNumber": 1,
	"endColumn": 20
}]
~~~
3. import the module into your project (in my case that seems to be a requirement)
~~~ts
// add to some other module...
import { dummy } from './dummy'
~~~
4. rename or delete `src/dummy.ts` -> 'Problems' pane still shows the same problems for `src/dummy.ts`
5. create file `src/dummy.ts` and then delete it again -> the problems flagged for `src/dummy.ts` are gone

**Comment by jecc1982** [comment]
I have the same issue with C#, the errors still remain in the Problems pane even the underlying source file is deleted. I have to restart VS Code or use Reload Window command to clear the errors.

**Comment by mjbvz** [comment]
I'm unable to reproduce this issue:

![Screenshot 2023-07-18 at 4 38 46 PM](https://github.com/microsoft/vscode/assets/12821956/f1111372-56a0-4f58-9dec-44a6149ff31c)

Does it only happen when eslint is installed? What if you disable all other extensions?

**Comment by mjbvz** [comment]
I can confirm that eslint seems to remember the old file name

![Screenshot 2023-07-18 at 4 41 40 PM](https://github.com/microsoft/vscode/assets/12821956/8eea9b22-c5b6-4a40-b708-e2e65e631560)

Can you please file this against the eslint extension to start as it seems like the bug is on their side
