### ISSUE TITLE
ftp feature is too poor

### ISSUE THREAD

**Issue by singharyan015** [Microsoft/vscode#18186]
- VSCode Version:1.8.1
- OS Version: ubuntu 16

Steps to Reproduce:

1. it must open all ftp file on project folder without downloading it.
2. it must save remote file after open in editor

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/13643

**Comment by ManPython** [comment]
I agree with author: "ftp feature is too poor" in extensions. In fact no exist any main support for ftp?
MS VSC Product manager can't expect all as free job/work as extensions (I'm not sure about MS VSC status as OS/Commercial, but we dealing about good stuff in VCS as github community). And maybe external coders not understand perfectly the API for extensionts or part of this code to create something what can made web developers happy of use their solutions. I tested all extensions and it's risk to use, with think that something can be bad done. The current 3extensions are not user friendly.
Curently VSC is good as local editor, but huge part (maybe 50%) is remote as web - by this, live editor for FTP is important. Coz thiss issue I'm backing to the Notepad++ coz exist usefull FTP plugin pracitaly used as base.
http://www.inmotionhosting.com/support/website/ftp-client-setup/connect-ftp-notepad-plus
