### ISSUE TITLE
Version 1.78 breaks the debug adapter protocol (DAP)

### ISSUE THREAD

**Issue by msweeney1999** [microsoft/vscode#181825]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:  1.78
- OS Version:  Windows 10

Steps to Reproduce:

1. Install v1.78 of VS Code
2. Try the sample mock debug program
3. You cannot perform step, step over, etc. 
4. v 1.77 works perfectly

I suspect that 
sendEvent(new StoppedEvent("breakpoint", 1)
is not working properly.

**Comment by MrSarius** [comment]
I am experiencing the same issues. Downgrading to 1.77 fixed it.

**Comment by roblourens** [comment]
https://github.com/microsoft/vscode/issues/181485
