### ISSUE TITLE
Version 1.78.0 - Getting "No access to job control" opening new bash terminal session

### ISSUE THREAD

**Issue by marvfinsy** [microsoft/vscode#181885]
mac osx intel.

Upgraded to April 2023 1.78.0 version.
opening terminal window shows: message; "No access to job control."

Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: April 2023 1.78.0 version.
- OS Version: Mac OS Mojave

Steps to Reproduce:

1. Start VS code
2. Start a new bash terminal. see message. At this point i start a ruby server. Cannot debug or enter ctrl+C to terminate server.
3. Downgraded to latest 1.77 version fixed it.

Marvin Foster: marvinfoster@finsync.com

**Comment by meganrogge** [comment]
I believe this is already fixed, can you see if you can reproduce in the [Insiders build](https://code.visualstudio.com/insiders)?
/label info-needed

**Comment by E-Bo** [comment]
mac osx intel.

version: 1.79.0-insider
commit: 02298ef4180f2a5db39e0cb6288382860b96a596
date: 2023-05-11T05:26:00.234Z
Electron: 22.5.2
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Darwin x64 18.0.0

Does this issue occur when all extensions are disabled?: No，"Language pack extension for Chinese (Simplified)" and "Integrates ESLint JavaScript into VS Code"

bash: **no job control** in this shell
Cannot enter ctrl+C to terminate server
