### ISSUE TITLE
[keybindings] Keybindings without "when" should be given lower priority

### ISSUE THREAD

**Issue by MasterInQuestion** [microsoft/vscode#181871]
Than those with.
    This should somewhat reduce the need of excessive "when" clauses.

&#x2D;---

Version: 1.78.0
Commit: 252e5463d60e63238250799aef7375787f68b4ee
User Agent: Mozilla/5.0 (X11; Linux x86_64; rv:111.0) Gecko/20100101 Firefox/111.0
Embedder: github.dev

**Comment by ulugbekna** [comment]
Sorry, this would break how the keybinding system is designed and what people are used to.

**Comment by MasterInQuestion** [comment]
Changed indeed.
    But seems to have rather low impact on already defined settings. (shall break very few or probably no case)
    .
    Much lower than this [ [https://github<i>.</i>com/microsoft/vscode/issues/165388#issuecomment-1313897825](https://github.com/microsoft/vscode/issues/165388#issuecomment-1313897825) ] one would do.
