### ISSUE TITLE
Need to target localhost for localhost:6490/evaluatepolicy with proxy to authenticate to login.microsoft.com

### ISSUE THREAD

**Issue by ronarieke** [microsoft/vscode#181839]
We run into an issue running an API call to localhost:6490/evaluatepolicy when the proxy is enabled.  We tried adding localhost to NO_PROXY but that did not work.  We need to keep the proxy in place to make an authenticate to azure call in VS Code, because that is the only way my customer may authenticate in VS Code.  Here is their feedback on the issue:

- When connected to my company’s VPN, we need to use a proxy to call Connect to Azure from VS Code, so that we may authenticate

- NO_PROXY settings have both included and excluded “login.microsoft.com” to ensure authentication can take place. I have seen authentication fail at times both because that value was included and excluded from the NO_PROXY setting, which might be a separate but related issue. We receive 504 status codes regardless of that configuration and the configurations listed below.

- When the proxy is in place, we are prevented from making a call to localhost:6490/evaluatePolicy on the Azure Policy Extension.

- When we add the localhost to the NO_PROXY in VS Code, we do not see the expected outcome. We receive a 504 status code.

- When we configure the LAN Settings within Internet Properties to Bypass proxy server for local addresses, we still do not see the expected outcome. We receive a 504 status code.

- When proxy settings are completely disabled and I am disconnected from my company’s VPN, which is not acceptable workaround, the call to localhost:6490/evaluatePolicy on the Azure Policy Extension works as expected.

- VS Code Dev Tools team recommends reaching out to the VS Code GitHub support team to evaluate further.

 My alias: Ron.Rieke@microsoft.com

**Comment by chrmarti** [comment]
localhost should automatically be excluded from being proxied.

Could you install the Network Proxy Test extension (https://marketplace.visualstudio.com/items?itemName=chrmarti.network-proxy-test) and check the output of `F1` > `Network Proxy Test: Test Connection` in VS Code with "http://localhost:6490/evaluatepolicy"?

It sounds like the 504 is indicating a problem with your local service, but I might be missing some details here.

**Comment by ronarieke** [comment]
Here is the feedback we have on that test:
Note: Make sure to replace all sensitive information with dummy values before sharing this output.

VS Code 1.78.1 (6a995c4f4cc2ced6e3237749973982e751cb0bf9)
Network Proxy Test 0.0.6
win32 10.0.22000 x64

Settings:
- http.proxy: 
- http.proxyAuthorization: null
- http.proxyStrictSSL: true
- http.proxySupport: override
- http.systemCertificates: true

Environment variables:
HTTPS_PROXY=http://[username redacted]:[password redacted]@naproxy.gm.com:80/
HTTP_PROXY=http://[username redacted]:[password redacted]@naproxy.gm.com:80/
NO_PROXY=gm.com

Sending GET request to http://localhost:6490/evaluatePolicy...
vscode-proxy-agent: DIRECT
Received response:
- Status: 404 Not Found

**Comment by chrmarti** [comment]
That looks good, I assume. I suggest you investigate the 504 on that URL for your request.
