### ISSUE TITLE
my visual studio code starts slowly

### ISSUE THREAD

**Issue by Swapn2** [microsoft/vscode#181835]
1. :warning: We have copied additional data to your clipboard. Make sure to **paste** here. :warning:
1. :warning: Make sure to **attach** these files from your *home*-directory: :warning:
-`prof-XNlsoNZg.main.cpuprofile.txt`
-`prof-XNlsoNZg.renderer.cpuprofile.txt`
[prof-XNlsoNZg.main.cpuprofile.txt](https://github.com/microsoft/vscode/files/11424258/prof-XNlsoNZg.main.cpuprofile.txt)
[Uploading prof-XNlsoNZg.renderer.cpuprofile.txt…]()

**Comment by mjbvz** [comment]
Duplicate of #178962
