### ISSUE TITLE
Native Terminal: Improve tmux support

### ISSUE THREAD

**Issue by elithrar** [Microsoft/vscode#18182]
- VSCode Version: Version 1.8.1 (1.8.1)
- OS Version: OS X 10.11.6

**Summary**: Highlighting text between tmux splits, and scrolling within tmux, does not work reliably when using the native terminal vs. (e.g.) iTerm2. Mouse support (clicking between splits) is also not supported.

Steps to Reproduce:

1. Have tmux running inside your shell
2. Open a split (prefix + %)
3. Try to highlight text within a split with the mouse (ends up crossing splits, and putting them both into 'normal' mode)
4. Try to scroll within a split, or use PgUp, and it breaks the tmux history.

![tmux-vscode](https://cloud.githubusercontent.com/assets/18544/21691713/920eccf8-d32e-11e6-8b10-c70a01ba80ee.gif)

**Comment by Tyriar** [comment]
Moved upstream https://github.com/sourcelair/xterm.js/issues/456

**Comment by 17011977** [comment]
Wysłane z programu Outlook<http://aka.ms/weboutlook>


________________________________
Od: Daniel Imms <notifications@github.com>
Wysłane: 6 stycznia 2017 16:21
Do: Microsoft/vscode
DW: Subscribed
Temat: Re: [Microsoft/vscode] Native Terminal: Improve tmux support (#18182)


Closed #18182<https://github.com/Microsoft/vscode/issues/18182>.

-

**Comment by whitecolor** [comment]
Also In windows (with Ubuntu bash shell) I experience different visual bugs after adding panels and resizing the window:
![image](https://cloud.githubusercontent.com/assets/736697/21748370/b527f4a2-d5a5-11e6-9f25-57a6c34f52e2.png)

![image](https://cloud.githubusercontent.com/assets/736697/21748371/bc443318-d5a5-11e6-95e6-a0525298656b.png)

**Comment by whitecolor** [comment]
For example tmux reacts badly on window resize events, and doen't react on on minimize/maximize window and going to full-screen, resizing terminal panel.
