### ISSUE TITLE
Mat controls are flagged by Intellisense

### ISSUE THREAD

**Issue by chaibloom** [microsoft/vscode#181841]
Type: <b>Bug</b>

If I use most Mat controls in my html (e.g. mat-card, mat-form-field, etc), they get flagged by Intellisense with a comment like:

'mat-form-field' is not a known element:
1. If 'mat-form-field' is an Angular component, then verify that it is part of this module.
2. If 'mat-form-field' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.

The code compiles and runs fine, but the sea of red warning flags make it difficult to work...

VS Code version: Code 1.78.0 (252e5463d60e63238250799aef7375787f68b4ee, 2023-05-03T20:09:00.748Z)
OS version: Windows_NT x64 10.0.19044
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.74GB (11.81GB free)|
|Process Argv|--crash-reporter-id 77f91bf0-511b-4226-a371-fa8ca0674d97|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|16.0.0
angular-schematics|cyr|5.3.1
xml|Dot|2.5.1
csharp|ms-|1.25.7
remote-wsl|ms-|0.78.4
live-server|ms-|0.4.7
vsliveshare|ms-|1.0.5864
vscode-coverage-gutters|rya|2.10.4
vscode-scss-formatter|sib|2.5.0
simontest|Sim|1.9.10
rename-angular-component|tom|2.1.3

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
3biah626:30602489
pyind779:30671433
f6dab269:30613381
pythonsymbol12:30671437
a9j8j154:30646983
6233i204:30730053
vsccsb:30705552
azdwalk:30721579
pythonms35:30701012
pythonfmttext:30731395
fixshowwlkth:30730052
hidesbindicator:30730055
pythongtdpathcf:30731979

```

</details>

**Comment by aeschli** [comment]
The built-in HTML extension does not do any validation. You write 'Intellisense', that's code assist. Not sure how this would flag an error.
The error must come from one of the extensions. Please find out which extension causes this and file an issue against that extension.

**Comment by chaibloom** [comment]
Thanks for the suggestion, aeschli.  Turns out that it was the latest version of the Angular Language Service extension.  Rolling it back to to prior version fixed the issue.
