### ISSUE TITLE
Automatic type acquisition autocomplete is not working with JSDoc comments 

### ISSUE THREAD

**Issue by mohsen1** [Microsoft/vscode#18184]
- VSCode Version: 1.8.1
- OS Version: macOS

Steps to Reproduce:

1. Make a file with following contents 

```js
var webpack = require('webpack')

/** @type {webpack.Configuration} */
var config = {
    module: {
        loa // expected autocomplete 
    }
}

module.exports = config;
```
2. In line 6, based on webpak type definition I should autocomplete for `loaders`.

![screen shot 2017-01-05 at 10 26 04 am](https://cloud.githubusercontent.com/assets/543633/21692426/b3ebb338-d331-11e6-82f1-812701538bdf.png)

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript#13333
