### ISSUE TITLE
`--user-data-dir`, `--help` and other command line arguments not working with portable installation executable

### ISSUE THREAD

**Issue by CS-Account** [microsoft/vscode#181876]
Type: <b>Bug</b>

---

<H3><a href="#potential-solution">Potential Solution</a></H3>

---

I'm using the Linux x64 portable tarball version of VSCode 1.78.0 (stable) on CentOS 7 and I'm having trouble using the `--user-data-dir` command line argument to launch VSCode with a custom data directory. I've tried using both absolute and relative paths to the custom data directory, but VSCode doesn't seem to be using the specified directory.

I'm launching the `code` executable directly from the root of the extracted tarball for the portable installation. Here's an example of the command I'm using to launch VSCode:

```
/path/to/vscode/code --user-data-dir=/my/custom/data/dir
```
<detail>
I've also tried using a relative path to the custom data directory and a `' '` instead of a `'='`,  but neither worked.

I've tried using other command line arguments, such as `--help`, with the `code` executable located in the `bin` directory and they seem to work. I vaguely remember reading something about a similar issue with VSCode involving the `code` executable in the root of the extracted tarball preprocessing command line arguments before actually calling `code` to do some type of startup process. This could be a clue as to what is happening, as commands seem to work with the /bin/code executable [but not the one recommended in the documentation for portable installation.](https://code.visualstudio.com/docs/editor/portable)

This issue/documentation issue maybe??? has been present in every version of VSCode that I've used, for more than a year most likely. Not being able to use this command prevents me from using VSCode with REZ, a cross-platform package manager, because users would need to have their own user data, but a shared extensions directory would be preferable. Of course it can be used outside of the package manager however.

I created this ticket after troubleshooting the issue with Bing chat 😆 and trying to get my ducks in a row. Letting that sit for a while I decided to do more searching and came upon this somewhat similar [issue](https://github.com/microsoft/vscode/issues/63657) and [new documentation changes](https://code.visualstudio.com/docs/editor/command-line) (since the last time I looked into this issue) stating that --user-data-dir has no effect, however that does not seem to be the case, nor the intention from developers.

</detail>

From the searching I have done I think I see the most likely answer/solution to this issue. As the comment mentioning what I assume to be the original changes to documentation [said here](https://github.com/microsoft/vscode/issues/63657#issuecomment-456413633), I assume this wasn't so much a decision to can the feature but simply not bother fixing this particular bug.

<H3 id='potential-solution'>Potential Solution</H3>

From all that I have now read looking into this issue, I believe its very possible this could simply be a documentation issue in the 2 locations covered, but I am unsure as Im not sure what the intent was when the code was written. That being said, if it were simply documentation, this is what I would assume the fix would entail:

1. Unless I am missing something about the differences between `/vscode_dir/code` and `/vscode_dir/bin/code` I assume that based on wording on [this documentation page](https://code.visualstudio.com/docs/editor/command-line) that `/vscode_dir/bin/code` is *actually* the intended method to launch vscode for command line usage. This would be a documentation change if correct.

2. The documentation could be updated to reworded to be more accurate. Specifically, it could simply be rephrased to list the oddity in portable mode as simple functionality, simply listing that in portable mode it needs to be either or when it comes to that command like option or adding a data folder to the portable Code directory. To make sure that this was unlikely to be simply a decision to remove the feature entirely rather than an inaccurate documentation change, as I already have a fork of the vscode docs repo, I looked at [the documentation commit which changed the phrasing to indicate this feature does not exist at all](https://github.com/microsoft/vscode-docs/commit/fe4fbc1398a12b5698f836e84d7a1fec2abb56a9) and verified it was the author of that ticket at the time of that ticket, indicating this was likely a documentation error rather than a feature discontinuation.

I, at the start of making this ticket was quite confident that it was an issue for the Code repo rather than the Docs repo, but reaching the end of my investigation into it, I'm not quite sure anymore. Regardless, I will still post this with the hopes that at the very least someone more knowledgeable might be able to steer me in a direction with regards to whether or not this is an issue or if the documentation changes above sound like the correct course of action, in which case **I would be happy to make the necessary documentation pull request**.

VSCode version: `Code 1.78.0 (252e5463d60e63238250799aef7375787f68b4ee, 2023-05-03T20:09:46.685Z)` portable tarball
OS: CentOS 7
OS version: Linux x64 3.10.0-1160.25.1.el7.x86_64
Modes:
Sandboxed: No

VS Code version: Code 
<details>
<summary>Potentially Irrelevant System Info</summary>
I note this so that a potential reader does not waste their time reading this when the issue may very well not be a code one.
<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-2630 v3 @ 2.40GHz (32 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|1, 1, 1|
|Memory (System)|62.68GB (53.73GB free)|
|Process Argv|--help --crash-reporter-id 81c7061f-41cd-43cc-847e-92e1d120ccc0|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|1-kde-plasma-standard|
|XDG_CURRENT_DESKTOP|KDE|
|XDG_SESSION_DESKTOP|undefined|
|XDG_SESSION_TYPE|undefined|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
isort|ms-|2022.8.0
python|ms-|2023.2.0
vscode-pylance|ms-|2023.2.30
jupyter|ms-|2023.4.1011241018
jupyter-keymap|ms-|1.1.0
jupyter-renderers|ms-|1.0.15
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-slideshow|ms-|0.1.5

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
vsccc:30610678
282f8724:30602487
pyind779:30671433
89544117:30613380
pythonsymbol12:30671437
showlangstatbar:30730054
azdwalk:30721579
pythonms35:30701012
pythonfmttext:30731395
pythoncmvfstr:30731969
fixhidewlkth:30730051

```

</details>
</details>

Steps to Reproduce:

1. Try to launch VSCode with any command line options.

**Comment by joaomoreno** [comment]
> I would be happy to make the necessary documentation pull request.

Please go ahead!

**Comment by CS-Account** [comment]
@joaomoreno Thank you for the fast response. I just wanted to ensure I was seeing 2020 before doing it. Would you be able to verify that my assumptions were correct/that vscode/bin/code should be used for the command line instead of vscode/code and that it is only the documentation that needs changing for vscode portable?

I will go ahead and make it in the meantime though, I suppose if those assumptions were wrong, the pr wouldn't get through or you would have suggested otherwise in your response. Thanks once again.

**Comment by joaomoreno** [comment]
> vscode/bin/code should be used for the command line instead of vscode/code and that it is only the documentation that needs changing for vscode portable?

Correct.
