### ISSUE TITLE
[bash] commands after HEREDOC delimiter are highlighted like the HEREDOC

### ISSUE THREAD

**Issue by dexwerx** [Microsoft/vscode#18192]
- VSCode Version: 1.8.1
- OS Version: Windows 7 x64

Steps to Reproduce:

1. Create a Shell Script
2. Paste 
```
# grab field types from ORACLE
sqlplus -s user/pass << EOD | sed '/^$/d' | awk 'NR>2{print}' > temp.txt
SET PAGESIZE 0;
SET FEEDBACK OFF;
DESCRIBE $1;
EOD
```

everything after the end of heredoc token **EOD** is highlighted the same as the rest of the heredoc.

**Comment by aeschli** [comment]
This issue was moved to textmate/shellscript.tmbundle#35
