### ISSUE TITLE
Fix incorrect "stopped" event handling

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#181966]
From https://github.com/microsoft/vscode/issues/181485

Need a better fix for the underlying issue at https://github.com/microsoft/vscode/blob/5967addf56035cd63c313ab2f3feaff4fcd11d66/src/vs/workbench/contrib/debug/common/debugModel.ts#L1313-L1336

then to bring back the change from https://github.com/microsoft/vscode/pull/181855

**Comment by roblourens** [comment]
When verifying, test with one of the multi-threaded examples here (https://github.com/microsoft/vscode/issues/29168) the sample dev containers are helpful for getting a debug environment for C# or C++ too.

**Comment by joyceerhl** [comment]
Still repros for me, I can't step past this line 
<img width="1620" alt="image" src="https://github.com/microsoft/vscode/assets/30305945/1f91cdcd-c77f-4075-924e-0d3f0db23607">

**Comment by joyceerhl** [comment]
Hm, stopped and restarted the debug session, am now able to step over that second breakpoint 🤔 I'll consider this verified for now

**Comment by roblourens** [comment]
Not sure about that, but also all the issue reports have gone away so I think it's ok.

**Comment by sim642** [comment]
The supposed fix doesn't really work though, it's still broken in 1.79: https://github.com/goblint/GobPie/pull/60#issuecomment-1590842140.

**Comment by roblourens** [comment]
I'm not following the comments in the issue, can you help me understand what is still an issue in vscode? A sample that I can repro would be great
