### ISSUE TITLE
`ctrl+c` doesn't work in the terminal sometimes

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#181939]
Run a command - `ls` for example - then `ctrl+c` and it doesn't exit that command

![image (14)](https://github.com/microsoft/vscode/assets/29464607/1ff06c57-bc4b-4db1-9509-6af155b71bcb)

**Comment by Se7en-IT** [comment]
Same issue:
Versione: 1.78.1
Commit: 6a995c4f4cc2ced6e3237749973982e751cb0bf9
Data: 2023-05-04T09:57:42.343Z
Electron: 22.5.1
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
Sistema operativo: Darwin x64 18.7.0
In modalità sandbox: No

**Comment by hypo1986** [comment]
请问到底哪个版本解决了这个问题啊insiders-release也是不行，contrl+C还是不能用啊，还是显示bash: no job control in this shell

**Comment by bunsenstraat** [comment]
I went back to 1.77 to make it work

**Comment by mouday** [comment]
me too!

```
Version: 1.78.2
Commit: b3e4e68a0bc097f0ae7907b217c1119af9e03435
Date: 2023-05-10T14:44:45.204Z (3 wks ago)
Electron: 22.5.2
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Darwin x64 18.5.0
Sandboxed: Yes
```

**Comment by honomoa** [comment]
me either

```
Version: 1.78.2
Commit: b3e4e68a0bc097f0ae7907b217c1119af9e03435
Date: 2023-05-10T14:44:45.204Z
Electron: 22.5.2
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Darwin x64 18.7.0
Sandboxed: Yes
```

**Comment by Tucsky** [comment]
this clearly isn't fixed 😄
