### ISSUE TITLE
Pattern matching in "Find all files" work only for open files?

### ISSUE THREAD

**Issue by ahmetalpbalkan** [Microsoft/vscode#18198]
- VSCode Version: 1.8.1
- OS Version: macOS 10.12.2

Steps to Reproduce:

I have a Go project (https://github.com/ahmetalpbalkan/go-linq)  and I am looking for this pattern in the codebase: a '{' followed by two new lines.

I have no open files currently.

I hit Cmd+Shift+F and type regex: `\{\n\n`, hit the [.*] regex button and then hit return, I get no results:

![image](https://cloud.githubusercontent.com/assets/159209/21701211/359549a4-d359-11e6-9631-e8a671fcc30a.png)

Suspicious, because I am sure I have some matches.. Then I open a file `aggregate.go` and I hit Cmd+Shift+F again and return again to perform the exact same search:

![image](https://cloud.githubusercontent.com/assets/159209/21701225/4d607d56-d359-11e6-9c6f-35f6e79e628e.png)

Bam! I have matches now, but only from the open file, `aggregate.go`. Is this a bug?

**Comment by sandy081** [comment]
Duplicates #13068
