### ISSUE TITLE
Unable to debug (hit breakpoints) for ASYNC functions

### ISSUE THREAD

**Issue by JordanYankovich** [Microsoft/vscode#18191]
- VSCode Version: Code 1.8.1 (ee428b0eead68bf0fb99ab5fdc4439be227b6281, 2016-12-19T14:49:23.350Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions:

|Extension|Author|Version|
|---|---|---|
|vscode-mocha|Compulim|0.1.1|
|code-runner|formulahendry|0.6.2|
|docomment|k--kato|0.0.9|
|net-core-project-manager|ksubedi|0.3.6|
|cpptools|ms-vscode|0.9.2|
|csharp|ms-vscode|1.5.3|
|omnisharp|ms-vscode|0.3.3|
|typescript-javascript-grammar|ms-vscode|0.0.6|

---

Steps to Reproduce:

1. Create typescript project
2. Create async method in class ( methodName = async() => {} ) 
3. Put breakpoint inside method, debug and see breakpoint does not get it

**Comment by octref** [comment]
It's working for me though.

![image](https://cloud.githubusercontent.com/assets/4033249/21713241/e3d3fb02-d433-11e6-9319-1a9e77883cb5.png)

Please post exact steps for reproducing the bug. Otherwise people can't help you much.

**Comment by roblourens** [comment]
It looks like the difference in your case is that this is a single line function - we don't have a way to set a bp in the middle of a line right now.

This will be handled by https://github.com/Microsoft/vscode/issues/14784 (but won't work until maybe node 8)
