### ISSUE TITLE
Vscode cannot debug console content and cannot use filter search?

### ISSUE THREAD

**Issue by CHANGUO** [microsoft/vscode#181917]
![image](https://user-images.githubusercontent.com/35283633/236396916-87517541-39f1-4a70-b846-1d880811f03f.png)

**Comment by roblourens** [comment]
Sorry, I don't understand what problem you're trying to show, please give more details

**Comment by CHANGUO** [comment]
> Sorry, I don't understand what problem you're trying to show, please give more details
Using VScode to output Python program results to DEBUG CONSOLE, using the DEBUG CONSOLE filter seems to have no effect and cannot filter text

**Comment by roblourens** [comment]
We filter for lines that contain that string, and you are pointing out that the line contains that string
