### ISSUE TITLE
`.git-blame-ignore-revs` should be highlighted as ignore syntax

### ISSUE THREAD

**Issue by ntnyq** [microsoft/vscode#181998]
Currently, it is treated as `plain text`. (I have disabled all my extensions and confirm this behavior)

It does support `#` as comment like `gitignore` does.

A simple workaround now is to set 

```jsonc
// settings.json
{
  "files.associations": { 
    ".git-blame-ignore-revs": "ignore"
  }
}
```

But it's nice to have it built in supported.

**Comment by lszomoru** [comment]
### Verification steps:
* Clone the `microsoft/vscode` repository
* Open the `microsoft/vscode` repository in VS Code Insiders
* Rename `.git-blame-ignore` to `.git-blame-ignore-revs`
* Open the file:
  * Confirm that the file type is detected as "Ignore"
  * Confirm that the comments in the file are coloured correctly
