### ISSUE TITLE
Profile's extension state (enabled or disabled) not sync

### ISSUE THREAD

**Issue by cethink** [microsoft/vscode#181984]
Type: <b>Feature Request</b>

Profile's extension state (enabled or disabled) not sync

VS Code version: Code 1.78.1 (6a995c4f4cc2ced6e3237749973982e751cb0bf9, 2023-05-04T09:48:08.683Z)
OS version: Windows_NT x64 10.0.22624
Modes:
Sandboxed: No

**Comment by cethink** [comment]
![image](https://github.com/microsoft/vscode/assets/756512/0d24ce23-5ebb-4d15-be92-c0450e921fae)

**Comment by sandy081** [comment]
> Profile's extension state (enabled or disabled) not sync

Not sure if I understand the request. Can you please elaborate?

**Comment by cethink** [comment]
就是在A电脑上新建了一个配置文件之后，配置文件里对一些拓展做了禁用，在B电脑上同步之后，A电脑上被禁用的拓展在B电脑上还是启用状态

**Comment by sandy081** [comment]
Closing this issue as the requested information is not provided.
