### ISSUE TITLE
iPad arrow keys, Enter keys, scroll wheel may not work

### ISSUE THREAD

**Issue by gabrc52** [microsoft/vscode#181990]
Really sorry for not having a straightforward reproducibility, but I am using VS Code on my iPad, and I am experiencing the following issues:

* The scroll wheel stops working at random intervals (liveable, can use the touchscreen instead)
* The arrow keys stop working at random intervals (slightly liveable)
* The Enter key stops working at random intervals (I can only code one-liners if that happens)
* When one of these components is not working, it appears that it does not just resolve by itself, and may require a restart, which may not help

I am running the following versions:

```
code-server: v4.12.0
Code: 1.77.3
Commit: 704ed70d4fd1c6bd6342c436f1ede30d1cff4710
Date: 2023-04-13T18:36:32.554Z
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.3 Safari/605.1.15
```

My iOS version is iPadOS 16.3.1 (20D67).

Let me know what additional information I can provide.

**Comment by roblourens** [comment]
code-server is not an officially supported VS Code release. However I know that there are bugs with Safari affecting the editor that we have to live with. Let me know if it's reproable with an official vscode release
