### ISSUE TITLE
Can't toggle breakpoints if there is a decorator in the gutter

### ISSUE THREAD

**Issue by alefragnani** [microsoft/vscode#181982]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.78 and 1.79 insiders
- OS Version: MacOS Ventura

The recent release improved how glyphs are rendered in margin (https://code.visualstudio.com/updates/v1_78#_glyph-margin-decoration-rendering-improvements), so you may use that sample to test the scenario
 
Steps to Reproduce:

1. Add a breakpoint with mouse click in the gutter
2. The breakpoint icon is added
3. Add a bookmark using command palette / shortcut
4. The bookmark decorated is added
5. The gutter is _expanded_
6. Everything is just fine
7. Remove both, the bookmark and the breakpoint
8. Now, using the reverse order, first add the Bookmark using command palette / shortcut
9. And try to add the breakpoint using mouse click
10. You will notice it is not possible
11. If you try to add the breakpoint with command palette instead, it will work

I have noticed that even when the gutter is _expanded_ after step 4, the mouse click (to add a breakpoint) is not woking on any line that already contains a bookmark decorator. The mouse simply doesn't change to _hand_ icon when you hover the location.

Related to #179725

Thank you

**Comment by alefragnani** [comment]
It seems #180395 resolved the _removal_ of breakpoints, and maybe the same comment added by @joyceerhl (https://github.com/microsoft/vscode/issues/180395#issuecomment-1517083923) would be applied here

**Comment by joyceerhl** [comment]
Duplicate https://github.com/microsoft/vscode/issues/185814
