### ISSUE TITLE
"Learn More" button unexpectedly orphans unsaved editors when reopening workspaces on untrusted UNC hosts

### ISSUE THREAD

**Issue by ThubLives** [microsoft/vscode#181956]
Does this issue occur when all extensions are disabled?: Yes

Version: 1.78.1 (system setup)
Commit: 6a995c4f4cc2ced6e3237749973982e751cb0bf9
Date: 2023-05-04T09:48:08.683Z
Electron: 22.5.1
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Windows_NT x64 10.0.19044
Sandboxed: No

Steps to Reproduce:

1. Open a workspace at a UNC path that isn't set in security.allowedUNCHosts.
2. Click "Yes" when prompted to temporarily allow working from that host.
3. Make changes to one or more files _without_ saving them.
4. Restart VSCode without closing the workspace (may require specific settings to automatically re-open the previous workspace).
5. This time, click the "Learn More" button when prompted to allow working from that host.

Note that any unsaved editors remain, but the rest of the workspace is not loaded as though the user clicked the "No" button.  I'd argue that "Learn More" doesn't constitute a decision from the user and shouldn't proceed as though it was.  Depending on the nature of the changes, this may cause a problem for safely saving those changes because if the user tries to re-open the workspace, they are asked to either save or close these orphaned editors.

Perhaps a link among the text in the dialogue box would be more appropriate than a button which closes the box.

**Comment by bpasero** [comment]
I agree that the dialog should not close and/or make a decision when you click "Learn More". Unfortunately the dialog closes when you press that button, so best I can do is to open it again asking the same question.
