### ISSUE TITLE
Disable filepath highlighting

### ISSUE THREAD

**Issue by jaymegordo** [microsoft/vscode#181922]
I can't find a setting, but is there a way to disable the "filepath highlighting" from the interactive window renderer?

This is a simple example, but almost any kind of output I use has some sort of `/` in it, and this is just really annoying and not helpful. Would love to disable it completely. Thanks!

<img width="606" alt="image" src="https://user-images.githubusercontent.com/29611875/229325535-97ed5b23-2f5c-4c0b-97fd-87489dbe83ff.png">

**Comment by jaymegordo** [comment]
@amunger would be forever grateful if you can fix it, I get so annoyed by it every day haha 🙏🏻

**Comment by amunger** [comment]
I thought I was seeing this too, but now can't seem to repro. Can you check which render you're using with `change presentation` in the output menu to see if you're using the built-in?
![image](https://github.com/microsoft/vscode/assets/2019016/81bee151-3644-4094-979c-c747b1288cd0)

**Comment by amunger** [comment]
you're right, I found some that show the bad behavior on windows. 
Created https://github.com/microsoft/vscode/pull/182117 to fix that issue and I'll leave this feature request open - which would be more complex to implement since the backend setting needs to be piped to the renderer.

**Comment by jaymegordo** [comment]
@amunger Are you able to figure this one out? Still super annoying haha!
<img width="397" alt="image" src="https://github.com/microsoft/vscode/assets/29611875/2a502bcb-52ca-4e4f-9ffd-ee53bf6b172a">
