### ISSUE TITLE
Support global namespace reference in JavaScript

### ISSUE THREAD

**Issue by unional** [Microsoft/vscode#18196]
- VSCode Version: 1.8.0

I asked [this question on SO](http://stackoverflow.com/questions/41476411/how-to-make-vscode-work-with-global-namespace) but it is more like a feature request for Salsa so I copy it here:

Say I have two files:

```js
// a.js
Abc.foo = function(x) { return x; };

// b.js
Abc.foo(1);
```

The feature request is to enable "Goto Definition [F12]" to jump from `b.js` `Abc.foo()` to `a.js`

**Comment by mjbvz** [comment]
Thanks. I think this is already being tracked by: https://github.com/Microsoft/TypeScript/issues/13271

If you instead write:

```js
// a.js
var Abc = {
    foo: function(x) { return x; }
}
```

```js
//b.js
Abc.foo(1);
```

I am able to use *go to definition* just fine. The root problem here seems to be that Salsa does not understand properties added to the namespace after it is created.

Please let me know if that does not sound correct.

**Comment by unional** [comment]
I see. Also, I notice that:

```js
// a.js
Abc = { ... }  // without var
```
does not work either.

Together with Microsoft/TypeScript#13271, that means The JavaScript namespace style doesn't work that well:

```js
// Abc/def/xyz.js
Ext.ns('Abc.def');
Abc.def.xyz = { ... }

// Abc.def/pqr.js
Ext.ns('Abc.def');
Abc.def.pqr = { ... }
```
