### ISSUE TITLE
code --wait should return control when closing window

### ISSUE THREAD

**Issue by bmalicoat** [Microsoft/vscode#18199]
- VSCode Version: 1.8.1
- OS Version: Mac OS 10.11.6

Steps to Reproduce:

1. Set your EDITOR path to use VS Code and open with the Wait flag:
        export EDITOR='open -W -a Visual\ Studio\ Code'
2. Use an interactive command line tool like 'arc diff'
3. This will launch VS Code and allow you to edit a summary

Expected:
VS Code should return control to command line after I hit command-W to close the window.

Actual:
Control is only returned to the command line after completely closing VS Code via command-Q

Let me know if you need more details. Beyond Compare does a good job of this behavior where git difftool commands using BC will proceed back to the command line when a BC window is closed.

**Comment by joaomoreno** [comment]
This actually works, but you should not use the `open` command.

Try `export EDITOR='code --wait`.

**Comment by bmalicoat** [comment]
I'll try that, thanks João!

**Comment by ringods** [comment]
@joaomoreno I do have this in my setup:

`export EDITOR='code --wait'`

But still, I have to `Cmd-Q` VSCode to return back to the bash prompt. Closing the window is not enough.

VSCode 1.13.1 on Mac.

**Comment by joaomoreno** [comment]
@bpasero `--wait` doesn't seem to work like before

**Comment by bpasero** [comment]
I am not 100% sure we ever supported that, but I will check.

**Comment by bpasero** [comment]
We support this in case you run `code --wait` and another instance is already running, however we do not support this for the initial case, so this is a fair feature request.

**Comment by bpasero** [comment]
Some related issues with `--wait`:
* When using --wait and a file is passed, close the window when last tabs closes #28661
* `--wait` doesn't return when opening a new window and closing the first one #4142
* code --wait should return control when closing window #18199
