### ISSUE TITLE
The execution process is not correct of Python

### ISSUE THREAD

**Issue by xWuliou** [Microsoft/vscode#1819]
when I excute the code like this:
import threading
import asyncio

@asyncio.coroutine
def hello():
    print("hello world (%s)" % threading.currentThread())
    yield from asyncio.sleep(5)
    print("hello again (%s)" % threading.currentThread())
    
loop = asyncio.get_event_loop()
tasks = [hello(),hello()]
loop.run_until_complete(asyncio.wait(tasks))
loop.close()

the correct process is display the hello world,and pause 5 second ,and display the hello again.
but when I do the excution is vscode .. it pauses for 5 second ,and display the all result.

ISSUE：the output that in vscode is not the same as in python console of a Same piece of code.

**Comment by joaomoreno** [comment]
I assume:
- this has nothing to do with the execution process
- this is related to the buffering of stdout streams of the spawned process.

**Comment by xWuliou** [comment]
I doubt if there is some optimization for iterator . It has no effect for the output about the time delay in Iterator object.

**Comment by xWuliou** [comment]
the detail of the output that python code runs on vscode.
    vscode version:0.10.6
    python version:3.5.0
the tasks.json configuration:
{
    "version": "0.1.0",
    "command": "python",
    "isShellCommand": true,
    "showOutput": "always",
    "windows": {
        "command": "python.exe"
    },
    "args": ["${file}"]
}

**Comment by dbaeumer** [comment]
The reason for not seeing exactly the same timing is that we do some buffering on the VSCode side to not update the output panel to frequently if a lot of output appears. This is currently expected and there are no plans right now to change this. 

If we want to do something we need to extend the task framework to control the buffer interval for the output window.
