### ISSUE TITLE
Error using 'sidebar find / replace'

### ISSUE THREAD

**Issue by garfieldbanks** [Microsoft/vscode#18194]
- VSCode Version: 1.8.1
- OS Version: Windows 10

In my actual project, I tried to use the 'sidebar find / replace' to replace '\n ' with just '\n'. The error:
![image](https://cloud.githubusercontent.com/assets/12904270/21698284/75301464-d353-11e6-8962-e3e7fadce770.png)

I then tried reproducing it on a fresh instance of VSCode with a single file. Again, using the 'sidebar find / replace', to replace '\n ' with just '\n'. There was no visible error message this time, but VSCode failed to actually make the replacement:
![image](https://cloud.githubusercontent.com/assets/12904270/21698487/6d1fd16e-d354-11e6-8ccb-aeb64f36baa1.png)

I then tried using the 'single file find / replace' and it successfully made the replacement:
![image](https://cloud.githubusercontent.com/assets/12904270/21698541/a78a802e-d354-11e6-8f7d-bede756f819c.png)

So the issue is with the 'sidebar find / replace' only.

**Comment by sandy081** [comment]
Could be related to #13068

**Comment by sandy081** [comment]
There is no multi-line search supported. Hence this is making it as a dup of #13155
