### ISSUE TITLE
intent no correct for scss files

### ISSUE THREAD

**Issue by calidion** [Microsoft/vscode#18190]
- VSCode Version: Code 1.8.1 (ee428b0eead68bf0fb99ab5fdc4439be227b6281, 2016-12-19T14:42:49.304Z)
- OS Version: Darwin x64 16.3.0
- Extensions:

|Extension|Author|Version|
|---|---|---|
|tslint|eg2|0.7.1|
|code-beautifier|michelemelluso|1.6.2|
|vscode-icons|robertohuertasm|4.1.0|
|vim|vscodevim|0.4.10|

---

Steps to Reproduce:

1.  open an scss file from an angular2 project.
2. right click => choose 'format document'
3. then the indent will be changed from 2 spaces to 4 spaces.

And it is useless to change the indent settings.

**Comment by sandy081** [comment]
@calidion css formatting feature is from one of the extensions installed (may be code-beautifier). Please file the bug against it. Thanks.
