### ISSUE TITLE
Debugging BC AL Extension

### ISSUE THREAD

**Issue by MJelvani** [microsoft/vscode#181958]
Type: <b>Bug</b>

Hi,
The recent update to the VS-Code,  Verision: 1.78.0 ~ 1.78.1, causes the debugger not functioning correctly for debugging BC extensions.
When you create Breakpoint on several lines the debugger stops on the first Breakpoint line and if you push F11 key it goes to next line and then freezes.
Then if you push the F5 the browser loads BC page as looks like bypassing the breakpoints, however the VS-Code still stays on the freezing line.
Can somebody please review this issue?

Best Regards,
Massood

VS Code version: Code 1.78.1 (6a995c4f4cc2ced6e3237749973982e751cb0bf9, 2023-05-04T09:48:08.683Z)
OS version: Windows_NT x64 10.0.17763
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i9-11900K @ 3.50GHz (16 x 3504)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|63.90GB (48.01GB free)|
|Process Argv|--crash-reporter-id ad222188-bdd6-4920-8e64-0b462b5c42a4|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
al-code-outline|and|3.0.46
vscode-guid|hea|1.7.0
al-object-designer|mar|0.2.4
al|ms-|11.0.787898
al-formatter|ras|3.0.0
crs-al-language-extension|wal|1.5.25
vscode-c-al|zod|0.0.11

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vstes627:30244334
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
vscccc:30610679
282f8724:30602487
pyind779:30671433
89544117:30613380
pythonsymbol12:30671437
showlangstatbar:30730054
vsccsb:30705552
azdwalk:30721579
pythonms35:30701012
19089226:30706075
pythonfmttext:30731395
fixshowwlkth:30730052
hidesbindicator:30730055
pythongtdpath:30731978

```

</details>

**Comment by roblourens** [comment]
https://github.com/microsoft/vscode/issues/181485
