### ISSUE TITLE
Syntax highlighting broken in JSX when using arrow function's implicit return

### ISSUE THREAD

**Issue by matthamil** [Microsoft/vscode#18208]
- VSCode Version: 1.8.1
- OS Version: OSX 10.11.6

Steps to Reproduce:

1. Create a `.js` file, and write some JSX in it like so:

![image](https://cloud.githubusercontent.com/assets/11802078/21708284/94d486f8-d39c-11e6-91ec-2ef1149e5b1a.png)

2. Use an arrow function to implicitly return JSX.

3. Watch as the syntax highlighting below breaks.

This only breaks when the JSX is implicitly returned with the ES6 arrow function. If you wrap the JSX in parens, the syntax highlighting is not broken:

![image](https://cloud.githubusercontent.com/assets/11802078/21708312/d0693b00-d39c-11e6-899b-fe611387f394.png)

Using the arrow function and using an explicit return fixes the syntax highlighting as well:

![image](https://cloud.githubusercontent.com/assets/11802078/21708329/fa3fa860-d39c-11e6-83b5-eadaf5b76bd1.png)

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript-TmLanguage#401
