### ISSUE TITLE
Allow to disable `security.allowedUNCHosts`

### ISSUE THREAD

**Issue by weed-** [microsoft/vscode#182055]
The new "security.allowedUNCHosts" in 1.78.1 setting breaks our workflow. We edit _a lot_ of files on _a lot_ of UNC hosts (around ~3k hosts per user, many users). How can the feature be disabled or all/regex hosts be allowed?

Alternatively, we could try to add all our UNC hosts. The list ist around 5mb (now) and changes on a hourly basis - editing this manually is nonsense, but neither `security.allowedUNCHosts` nor `NODE_UNC_HOST_ALLOWLIST` allows for centralized (and realtime) management.

Using a match pattern like \\10.2.*.* or \\(*.)*.*.example.com would be our preferred method.

**Comment by asherjvitek** [comment]
The current state of this is completely unmaintainable. Having to enter every single server to browse to is not realistic. I use VS Code multiple times a day to open to files on servers.

There should be a way to either provide a wildcard or disable this allowing people to accept the risk.

**Comment by no3rdw** [comment]
We absolutely need a way to enter a wildcard or disable the feature entirely.  Every workspace I use is now unable to be opened until I can add the paths of every folder to this list.  I don't have 3000+ constantly updating paths like OP, but this is still a huge pain when every single one of those paths that need to be added individually are located under a single root directory that should be able to be added ONCE.

**Comment by FVolral** [comment]
For those who can't read the content of their folder in  `\\wsl$\`. In JSON settings, I added : 

` "security.allowedUNCHosts": ["\\wsl$"], ` According to : https://code.visualstudio.com/docs/setup/windows#_working-with-unc-paths.  
Then, after rebooting VSCode it works again

**Comment by Andy78DE** [comment]
I second @weed- 's comment. I have the same problem here.
Also, I tried to list the most used servers and IP addresses, but I still get the warning when opening a file. Is there a special format for the entries? Couldn't find any examples.
My settings file looks like this:
`    "security.allowedUNCHosts": [
        "abcde",
        "10.1.2.3",
        "hjfd"
    ]
`

**Comment by weed-** [comment]
@bpasero is right and we do understand the risk of this Information Disclosure Vulnerability. UNC retrieval and meta data access (... NTLM delegation ...) is a hot mess in Windows anyway.

We need a way to be able to "willingly accept this risk". In a closed environment like ours (telko stuff) the risk is more a theoretical one anyway. So a "disable" setting or "enable glob patterns", if global matching is "not enough", would be extremely helpful.

**Comment by Emilyaoc** [comment]
@FVolral I have this problem, but am really new to using VSCode and can't quite figure out exactly how to edit JSON settings as you suggest? I followed the link you provided, but still not sure how I access and change the security.allowedUNCHosts setting? Many thanks for any help you can offer! Emily

**Comment by jdonaldson-Lamar** [comment]
I am going to stop using VS Code if this issue is not resolved.

**Comment by marguz-wag** [comment]
Hello,

We use User Profile redirection at work and I have tried setting the needed environment variable "NODE_UNC_HOST_ALLOWLIST" to our NAS FQDN and still all our developers are unable to launch VSCode. I have been testing on version. 1.78.2.

Any way to allow the "risk" while MS works on fixing this "oops" without making the fix a breaking change?

**Comment by jgilfoil** [comment]
I didn't really want to start a new issue just for this comment, but this really just breaks the WSL integration experience. I develop from my Windows OS on files inside my WSL2 VM. Previously, the experience was seamless in being able to open files from the WSL2 environment. Now instead of working by default, I have to allow wsl.localhost? That seems like an unnecessary security impediment for very little security gain. Please add wsl.localhost to the allowed list by default.

**Comment by FlushingBaseball** [comment]
This is absurd and completely broke our workflow, Microsoft you need to be better.

**Comment by SuperBartimus** [comment]
At the minimum, It would be good to see this as a button prompt like you get for specific workspaces.  A button to Trust the location.  Which, isn't that really the same thing?

**Comment by ThiconZ** [comment]
This has completely broken our workflow and required us to make an emergency change to another editor to continue working. While we would love to continue using VS Code, we cannot return to using it until something is changed with this implementation.

Ideally the option to disable this would work best, perhaps even an opt-in/out on first launch, but other means to mitigate it would be welcome in the short term at least. Seeing as this breaking change was implemented quickly, an update to the behavior can come just as swiftly.

**Comment by rwalle** [comment]
Not exactly related to the topic, but I think in any case this change regarding UNC path issue should be very carefully designed and visibly announced and notified to end users. I just spent an hour figuring out why many extensions that are critical to my workflow stopped working, including the built-in TypeScript language service (it keeps crashing). Turns out these extensions cannot access any UNC path in any way (whether introduced by user configuration, or because the text file itself is actually using UNC path). I only accidentally discovered the cause when I tried to explicitly open a text file on a UNC path and saw an "allowed host" warning and was able to track it down.

I consider myself an expert VSCode user and developer (I have explored a lot of the codebase, written several VSCode extensions and language clients/servers and have done a ton of customization), and if it takes ma an hour to understand what is happening, it will only take other people a much longer time to figure this out.

**Comment by bramdier** [comment]
for those of you. still get message error. try to open your setting.json file from visual studio code. after that add code like this
```javascript
"security.allowedUNCHosts": ["Kbgatewaytest$", "Kbdev$"]
``` 
for example i have two diffrent path:
1. Kbgatewaytest
2. Kbdev
add symbol $ in the end of that path. after that save it.

**Comment by bramdier** [comment]
> I second @weed- 's comment. I have the same problem here. Also, I tried to list the most used servers and IP addresses, but I still get the warning when opening a file. Is there a special format for the entries? Couldn't find any examples. My settings file looks like this: ` "security.allowedUNCHosts": [ "ABC", "10.1.2.3", "DEF" ]`
> 
> **_EDIT:_** Got it: I put server names like "ABC" (upper-case) into settings, but it seems it has to be like "abc" (lower-case) 🤦🏼‍♂️ Still just a temporary workaround...

```
"security.allowedUNCHosts": ["ABC$", "DEF$"]
```

**Comment by rwalle** [comment]
> 

Does GIOVANNI without the dollar sign work?

**Comment by AmansRevenger** [comment]
No it does not. Do i need to add something else like my local domain (fritz.box) or something? I also dont know how to access VSCode logs ...

**Comment by fozi** [comment]
This "fix" just complicated me life way too much. (and my coworkers)

Not the best solution. But it worked for us.

Roll back to 1.77.3, disable auto update and wait for MS to give us a working solution.

**Comment by Nick-HK** [comment]
Guess you will need a local mapping to the drive first to access to remote file server..

**Comment by jdonaldson-Lamar** [comment]
> This "fix" just complicated me life way too much. (and my coworkers)
> 
> Not the best solution. But it worked for us.
> 
> Roll back to 1.77.3, disable auto update and wait for MS to give us a working solution.

I am doing the same. Was about to go back to Sublime.

**Comment by asherjvitek** [comment]
> > This "fix" just complicated me life way too much. (and my coworkers)
> > Not the best solution. But it worked for us.
> > Roll back to 1.77.3, disable auto update and wait for MS to give us a working solution.
> 
> I am doing the same. Was about to go back to Sublime.

Unfortunately this is also what I have done.

**Comment by alejandro99so** [comment]
> allowedUNCHosts
It was solved with this:

1. Ctrl + Shift + p
2. Open settings (UI)
3. allowedUNCHosts
4. Add item
5. wsl.localhost
6. OK
7. restart

I hope you can solve your problem!

**Comment by Tanterrria** [comment]
I just wanna leave comment in disagree with this uncontrollable update. Some new troubles right before passing done work to my boss in the morning - nice big thank you!

**Comment by kolonuk** [comment]
I've just updated, got annoyed, and now reverted to 1.78. I have a few servers (not hundreds) and no way am I going to list all in VSCode just for some file editing maybe once a day.

Windows uses UNC paths all the time, and (when configured properly) that doesn't come up with warnings. Need an option to add regex, or wildcard, or just accept the Windows domain trusts - no expert, but assume that can be found and used.

Or, something that would go towards helping uses is a "add to exception" button on the warning popup, rather than just yes and no.

**Comment by bencfreeman** [comment]
I'd love to see how many hits the 1.78.0 download link has gotten in the last 24 hours compared to a few weeks ago. This breaks our workflow as well since a lot of our code is on SMB file servers. Will be using 1.78 until this update gets pushed and documented.

**Comment by jdonaldson-Lamar** [comment]
Does anyone know if 1.78.2 fixed this issue or is it randomly happening to users? I have a Co-Worker using 1.78.2 and he can open files from the server with no issues. I am still on 1.77 and do not want to deal with the hassle of uninstalling 1.78.2 if the issues still persist for some users.

**Comment by marguz-wag** [comment]
> 

1.78.2 does not "fix" the issue.

I do agree that the user should be given a button or something to opt-out of UNC security fix and accept "risk".

**Comment by bpasero** [comment]
We still need an upstream change before this will work. We plan for having it for our next stable release early June.

**Comment by ThiconZ** [comment]
I find it concerning that it is going to take so long for a proper fix for this issue to be implemented and make its way into the live environment. Though even the current changes appears to be only a half measure and not a true proper fix. After the relatively short turnaround time for a massive breaking change to have been implemented and pushed live, I would have hoped for a faster resolution here.

Being able to open a UNC path file is a basic feature that any file editor from Visual Studio down to even basic Notepad supports out of the box, but now VS Code seemingly can't support that by default? To me at least, it seems baffling that VS Code will not be able to do this anymore as the previously mentioned change will also still _default_ to UNC being blocked.
![image](https://github.com/microsoft/vscode/assets/6924950/5e224977-baf2-4d1b-a8f6-46b4a38858a1)

This type of sudden breaking change with no warning has unfortunately eroded a significant amount of confidence we once had in VS Code for being a primary tool in our workflows.

**Comment by bpasero** [comment]
@ThiconZ the change for blocking UNC paths in VS Code is a response to a security vulnerability. Please see https://github.com/microsoft/vscode/security/advisories/GHSA-mmfh-4pv3-39hr for more information.

**Comment by jdonaldson-Lamar** [comment]
@bencfreeman I was thinking the exact same thing. We have an entire team devoted to security and servers. If there is something malicious on our servers we have much bigger problems than VS code.  I can still open up files on my server with The Enterprise Version of Visual Studio. How come Visual Studio allows it but not VS Code? I can do way more Damage with Visual Studio than VS Code.  This seems like a knee jerk reaction with VS Code.

**Comment by bpasero** [comment]
The fix for this change will go out at the end of this week in our insiders build [1] and early June in stable build. 

A new setting `security.restrictUNCAccess` can be used to disable the UNC access checks. 

[1] Insiders builds normally release every day but are currently on-hold given the MSBuild conference that takes place.

**Comment by vrajbillings** [comment]
How bad is this. Is someone looking to provide a better fix?

**Comment by bencfreeman** [comment]
The monitor on my workstation died this morning and I had to rig up something temporary with laptop to get by. It is very frustrating to have to jump through hoops just to set up VS Code in a temporary dev environment so I can work. Remove this feature, or perhaps look into fixing whatever the vulnerability is on the server side. At this point it's more of a bug than a feature. Perhaps next time in your lengthy team discussions you might also consider the quality of the user experience.

**Comment by fmillion-mnsu** [comment]
Many settings in VS Code take effect immediately. Why do you have to _restart_ (closing everything you already have open - remote connections, debug sessions...) in order to add a server to the allow list?

**Comment by isaacolsen94** [comment]
This setting is driving me crazy! Let us disable it please.

**Comment by isaacolsen94** [comment]
> This "fix" just complicated me life way too much. (and my coworkers)
> 
> Not the best solution. But it worked for us.
> 
> Roll back to 1.77.3, disable auto update and wait for MS to give us a working solution.

Thank you this saved me tonight trying to find which version I had to go back to.

**Comment by Tzwcard** [comment]
It's already June, when will the update roll out?
I don't want to click "Yes" tens of times whenever I start VSCode anymore
Or anyone has suggestions of better tools that won't just break your workflow without any warning like this?

**Comment by bencfreeman** [comment]
Looks like the UNC security stuff is still enabled by default in 1.79.0. You'll have to manually go to settings on every VS Code install that you use and turn it off. I prefer VS Code's log file syntax highlighting over other text editors, and I have it installed on a bunch of machines just to view log files. 99% of the files we work with are on SMB shares. It's frustrating but at least we can disable the setting now. Find the "Security: Restrict UNCAccess" setting and uncheck it. And of course restart VS Code. Reminds me of the days of Win95 when you had to restart the whole machine every time you changed a setting. I hope future VS Code updates don't reset it back to default.

**Comment by dfloer** [comment]
Still broken in 1.79.1, neither setting `"security.restrictUNCAccess": false` or adding hostnames/IP addresses to `"security.allowedUNCHosts"` works.

It seems like having a working way to add allowed hosts should have been a pre-requisite to disabling UNC, even if it's a critical security issue, not being able to use VSCode with any UNC paths is also a big issue.
