### ISSUE TITLE
VS Code do not allow me to add network path

### ISSUE THREAD

**Issue by Leonidas300** [microsoft/vscode#182037]
Type: <b>Bug</b>

Hi,
I have an issue with one of my workspace folders that is on a remote host. Problem is that after editor update it asks for UNC name, I tried do all the suggestions that BING AI Copilot gave me. But still not working. Things I did:
- I added  path to UNC Allowed host, by IP - not working
- I added name to Host and LMHost file - not working
- I added then security.workspace.trust.untrustedFiles = open - and still not working.

Even AI Bot gived up and told me to contact support. Please tell me what to do because I used this location at my work.

VS Code version: Code 1.78.1 (6a995c4f4cc2ced6e3237749973982e751cb0bf9, 2023-05-04T09:48:08.683Z)
OS version: Windows_NT x64 10.0.19045
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4720HQ CPU @ 2.60GHz (8 x 2594)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|11.89GB (0.96GB free)|
|Process Argv|--crash-reporter-id 9a1b7a9e-ff8d-4acd-b85f-f6061646098e|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (46)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-autohotkey-plus|cwe|2.7.1
dart-code|Dar|3.62.0
flutter|Dar|3.62.0
ini-for-vscode|Dav|0.0.4
vscode-ionic-snippets|fiv|2.2.2
dotnet|for|0.0.4
abap-snippets|fre|0.1.0
godot-tools|gee|1.3.1
vscode-pull-request-github|Git|0.64.0
blender-development|Jac|0.0.18
mysql-syntax|jak|1.3.1
cisco|jam|1.9.1
boo|kar|0.0.2
unity-code-snippets|kle|1.3.0
vscode-abap|lar|0.5.7
vscode-autohotkey-plus-plus|mar|3.3.0
kvlang|Mon|0.0.6
vscode-language-pack-pl|MS-|1.78.2023051009
csharp|ms-|1.25.7
isort|ms-|2022.8.0
python|ms-|2023.8.0
vscode-pylance|ms-|2023.5.10
jupyter|ms-|2023.4.1011241018
jupyter-keymap|ms-|1.1.0
jupyter-renderers|ms-|1.0.15
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-slideshow|ms-|0.1.5
remote-containers|ms-|0.292.0
remote-ssh|ms-|0.102.0
remote-ssh-edit|ms-|0.86.0
remote-wsl|ms-|0.78.4
cpptools|ms-|1.15.4
powershell|ms-|2023.5.0
remote-explorer|ms-|0.4.0
cordova-tools|msj|2.6.3
platformio-ide|pla|3.1.1
Csharp-ASPNETCore|rah|1.11.0
vscode-commons|red|0.0.6
vscode-xml|red|0.25.0
vscode-yaml|red|1.12.2
aspnet-helper|sch|0.6.4
bash-beautify|sha|0.1.1
html-language-features|Sim|1.24.2
tensorflow-snippets|vah|0.3.3
intellicode-api-usage-examples|Vis|0.2.7
vscodeintellicode|Vis|1.2.30

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyonecf:30548226
vscccc:30610679
2e4cg342:30602488
pyind779:30671433
f6dab269:30613381
pythonsymbol12:30671437
2i9eh265:30646982
showlangstatbar:30730054
vsctsb:30705553
azdwalk:30721579
pythonms35:30701012
pythonfmttext:30731395
pythoncmvfstr:30731969
fixhidewlkth:30730051
pythongtdpathcf:30731979

```

</details>

**Comment by bpasero** [comment]
@Leonidas300 can you see if https://code.visualstudio.com/docs/setup/windows#_working-with-unc-paths helps?

**Comment by Leonidas300** [comment]
@bpasero Thank you for reply.
 - security.allowedUNCHosts - address is set there by ip and name from hosts file.
 - NODE_UNC_HOST_ALLOWLIST - tried that and still not working
 - The mapping of drive I didn't try because I don't want to map that drive - I use this only from VSCode and don't want this to be mapped.
 -

Is there a way to turn this UNC filter OFF?

**Comment by bpasero** [comment]
Oh, one thing we should probably document better: if you are using Remote, the setting needs to be configured on the machine and not in user settings on the client. Can you try that?

**Comment by bpasero** [comment]
Oh ok, then I misunderstood. I thought you were connecting to a remote with one of our remote extensions (such as SSH).

In your case, yes, changing the setting by adding the hostname and then restarting VS Code should work. What is the full path of the folder and what have you configured?

**Comment by Leonidas300** [comment]
I cannot give you full path because it contains some information that I don't know if my company policy allow me to share but I can tell you that in settings under Allowed UNCHosts I added \\IP\Folder I tried with name that i setup in host file, and also I tried just paste the full path but everytime I got "!" next to this folder and error message: Unable to resolve workspace folder (UNC Host 'IP' access is not allowed. Please update the 'security.allowedUNCHosts' setting if you want to allow this host.)

In this error message even when I enter just name it still says UNC Host 'IP' access is not allowed.

**Comment by bpasero** [comment]
A UNC path typically looks like this: `\\<host>\<path>`. You would have to configure the setting to match exactly `host` and we print the `host` also as part of the error message, so please double check that.

If it still does not work, then we need to investigate further. Just to clarify: this is a multi-root workspace (a `*.code-workspace` file you open as workspace) with one entry that is the path to a folder on a UNC drive?

If you can give me the file for me to try, it is fine if you redact the UNC path. Ideally you can add `foo` where you want to redact, but keep the structure the same.

**Comment by Leonidas300** [comment]
This is a multi-root workspace. I just open workspace file, I have all my projects there and one folder from many is this remote folder. This folder is placed in \\remote_host\im\foo\bar\ and there are scripts without a folder. In visual studio code I don't see any files inside - is just name of this folder with ! . If I type in Start->run program->name I wrote in host file or in explorer the location opens so my system recognize the name I created. Only vs code don't. And yes I restarted the PC.

**Comment by Leonidas300** [comment]
I just remove folder, and add it again with name. I got prompt do I trust this source. I say yes. And it still the same.

**Comment by bpasero** [comment]
@Leonidas300 I am trying to reproduce and see no issue so far.

Here is my workspace file:

```json
{
	"folders": [
		{
			"path": "\\\\localhost\\c$\\Users\\benjpas\\Desktop\\test-ts"
		}
	]
}
```

When I open the workspace at first, I see an exclamation mark:

![image](https://github.com/microsoft/vscode/assets/900690/cffb85bf-2df2-47df-b77b-5f039a112a6e)

Then I am configuring `localhost` to be allowed:

![image](https://github.com/microsoft/vscode/assets/900690/3c4ae0d9-797d-460f-99b4-98a7bcc82f43)

Specifically the value of the setting copied as JSON is:

```json
"security.allowedUNCHosts": [
  "localhost"
]
```

Are you doing anything different?

**Comment by Leonidas300** [comment]
God, Thanks it works. In security.allowedUNCHosts I had \\name and not just the name. That worked. I thought I need to place a path \\name or \\name\folder there. It's just name. Thanks. Maybe in this Allowed UNC Host setting in UI give not only link but example what to enter e.g. localhost or something like that. Thank you for you assistance.
