### ISSUE TITLE
Wrong color in C#

### ISSUE THREAD

**Issue by PotterDai** [Microsoft/vscode#18204]
- VSCode Version: 1.8.1
- OS Version: macOS sierra

Steps to Reproduce:
1.  Define an enum.
2.  Assign enum items int value.
Color theme starts to mess up.
Please check the following screenshot:

![screenshot 2017-01-05 21 18 14](https://cloud.githubusercontent.com/assets/3758951/21705250/c80a8db6-d38c-11e6-8c61-df6085d98a15.png)

**Comment by sandy081** [comment]
Moved to C# extension repo
