### ISSUE TITLE
Terminal opens powershell even when disabled

### ISSUE THREAD

**Issue by dan-petty** [microsoft/vscode#182091]
Type: <b>Bug</b>

Terminal intermittently opens powershell even when disabled in user config:
    "terminal.integrated.profiles.windows": {
        "PowerShell": null,
        "Command Prompt": null,
        "Git Bash": {
            "source": "Git Bash"
        }
    }

VS Code version: Code 1.78.1 (6a995c4f4cc2ced6e3237749973982e751cb0bf9, 2023-05-04T09:48:08.683Z)
OS version: Windows_NT x64 10.0.19044
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|12th Gen Intel(R) Core(TM) i7-1280P (20 x 1997)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.20GB (3.36GB free)|
|Process Argv|--crash-reporter-id cfb0ef8f-78e2-46b9-81b8-6150fe8b08e3|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
aws-toolkit-vscode|ama|1.72.0
hcl|has|0.3.2
terraform|has|2.26.0
python|ms-|2023.8.0
vscode-pylance|ms-|2023.5.10
makefile-tools|ms-|0.7.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
282f8724:30602487
pyind779:30671433
f6dab269:30613381
pythonsymbol12:30671437
a9j8j154:30646983
showlangstatbar:30730054
vsctsb:30705553
azdwalk:30721579
pythonms35:30701012
pythonfmttext:30731395
pythoncmvfstr:30731969
fixhidewlkth:30730051
hidesbindicator:30730055

```

</details>

**Comment by meganrogge** [comment]
what's your default profile set to? if nothing, we will fallback to powershell by design

**Comment by dan-petty** [comment]
It should fallback to the option that is not null if there is one.

**Comment by Tyriar** [comment]
This is by design, you need to set a different default profile if you deleted the current default.
