### ISSUE TITLE
Annoying behavior rather than a bug: When folder is opened, all tabs are cleared/closed !

### ISSUE THREAD

**Issue by myuseringithub** [Microsoft/vscode#18209]
When I open a folder and other file tabs are open, the editor closes these tabs and all edit history is deleted (so I cannot ctrl+z) and I need to open them again. 
Expected behavior: Open folder and keep existing tabs open. OR Open folder in a new window and keep other tabs in another window.

- VSCode Version: Code 1.8.1 (ee428b0eead68bf0fb99ab5fdc4439be227b6281, 2016-12-19T14:49:23.350Z)
- OS Version: Windows_NT ia32 10.0.14393

**Comment by bpasero** [comment]
In 1.9 we introduce a new setting `window.openFoldersInNewWindow` which you can set to "on" to get folders open in a new window. You can try this out from our insiders build: http://code.visualstudio.com/Download#insiders

**Comment by myuseringithub** [comment]
Thanks
