### ISSUE TITLE
tag select

### ISSUE THREAD

**Issue by paulbolen** [microsoft/vscode#182092]
Type: <b>Bug</b>

tags are selected and I can't delete the ending tag without deleting the starting tab

VS Code version: Code 1.78.1 (Universal) (6a995c4f4cc2ced6e3237749973982e751cb0bf9, 2023-05-04T09:57:42.343Z)
OS version: Darwin x64 22.4.0
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz (16 x 2300)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.09GB free)|
|Process Argv|. --crash-reporter-id c0641998-8c75-4863-ae61-d8679545b29a|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (70)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|3.0.2
codesnap|adp|1.3.4
Bookmarks|ale|13.3.1
project-manager|ale|12.7.0
blackbox|Bla|0.10.79
turbo-console-log|Cha|2.9.3
path-intellisense|chr|2.8.4
regex|chr|0.4.0
vscode-eslint|dba|2.4.0
denigma|den|0.0.15
githistory|don|0.6.20
gitlens|eam|13.5.0
prettier-vscode|esb|9.12.0
explaindev|exp|0.11.2
auto-rename-tag|for|0.1.10
code-runner|for|0.12.0
shell-format|fox|7.2.5
classroom|git|0.0.3
codespaces|Git|1.14.7
copilot|Git|1.86.82
copilot-labs|Git|0.12.791
copilot-nightly|Git|1.86.86
heygithub|Git|0.16.1329
remotehub|Git|0.56.0
vscode-codeql|Git|1.8.4
vscode-github-actions|git|0.25.7
vscode-pull-request-github|Git|0.64.0
wireit|goo|0.6.0
gc-excelviewer|Gra|4.2.57
todo-tree|Gru|0.0.226
vscode-test-explorer|hbe|2.21.1
vscode-auto-open-markdown-preview|hnw|0.0.4
output-colorizer|IBM|0.1.2
icon-fonts|idl|2.5.4
RelativePath|jak|1.5.0
markdown-extended|jeb|1.1.3
vscode-peacock|joh|4.2.2
vscode-colorize|kam|0.11.1
document|min|2.2.1
vscode-docker|ms-|1.25.0
remote-ssh|ms-|0.102.0
remote-ssh-edit|ms-|0.86.0
azure-repos|ms-|0.32.0
makefile-tools|ms-|0.7.0
powershell|ms-|2023.5.0
remote-explorer|ms-|0.4.0
remote-repositories|ms-|0.34.0
test-adapter-converter|ms-|0.1.7
vsliveshare|ms-|1.0.5864
indent-rainbow|ode|8.3.1
explorer-exclude|Pet|1.3.2
polacode|pnp|0.3.4
vscode-css-peek|pra|4.2.0
vscode-thunder-client|ran|2.6.2
vscode-yaml|red|1.12.2
LiveServer|rit|5.7.9
vs-code-prettier-eslint|rve|5.1.0
markdown-preview-enhanced|shd|0.6.8
code-spell-checker|str|2.20.4
open-in-browser|tec|2.0.0
intellicode-api-usage-examples|Vis|0.2.7
vscodeintellicode|Vis|1.2.30
vscode-java-dependency|vsc|0.22.0
vscode-icons|vsc|12.4.0
gitblame|wad|10.2.0
vscode-todo-highlight|way|1.0.5
vscode-import-cost|wix|3.3.0
JavaScriptSnippets|xab|1.8.0
markdown-pdf|yza|1.4.4
markdown-all-in-one|yzh|3.5.1

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
2e4cg342:30602488
pyind779:30671433
89544117:30613380
pythonsymbol12:30671437
6233i204:30730053
vsccsb:30705552
azdwalk:30721579
pythonms35:30701012
a2ce3375:30706076
pythonfmttext:30731395
pythoncmv:30731968
fixshowwlkth:30730052
hidesbindicator:30730055
pythongtdpath:30731978

```

</details>

**Comment by aeschli** [comment]
I assume you have enabled `editor.linkedEditing`
To only delete the closing tag, select the closing tab, press escape to exit the linked editing mode and press delete then.
