### ISSUE TITLE
highlight issue on TypeScript with higher order function

### ISSUE THREAD

**Issue by unional** [Microsoft/vscode#18206]
- VSCode Version: 1.8.1
- tsc: 2.2.0-dev.20170103

```ts

interface Foo {
  do(): (() => any)
  someProps: string
}
```

![image](https://cloud.githubusercontent.com/assets/3254987/21705437/c89e3f42-d374-11e6-94b1-a210a616fd0b.png)

Notice `string` is not colored properly.

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript-TmLanguage#399
