### ISSUE TITLE
2023-05-10 updated VScode, now powershell changed to orange color with error

### ISSUE THREAD

**Issue by tommy66374** [microsoft/vscode#182058]
```
Version: 1.78.1 (user setup)
Commit: 6a995c4f4cc2ced6e3237749973982e751cb0bf9
Date: 2023-05-04T09:48:08.683Z
Electron: 22.5.1
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Windows_NT x64 10.0.19044
Sandboxed: No
```

Steps to Reproduce:

![vscode-powershell-error](https://github.com/microsoft/vscode/assets/80481558/0aa554d3-a511-4ad4-afad-af588d47b6ae)

**Comment by Tyriar** [comment]
It's telling you the issue here:

![image](https://github.com/microsoft/vscode/assets/2193314/44a34042-f779-43ba-9e26-d08d5a30d8bb)
