### ISSUE TITLE
Show ISO format dates always

### ISSUE THREAD

**Issue by unikitty37** [microsoft/vscode#182014]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: Version: 1.78.1
- OS Version: macOS 12.6.3 (21G419)

Steps to Reproduce:

1. Set your OS date format to `dd/mm/yyyy`.
2. Open the Extensions pane.
3. Click on an extension.

## Expected behaviour

The dates in "More Info" are shown in dd/mm/yyyy format. VSCode should have a setting where the locale can be set, but should use the system locale if it has not been set. (I assume there is no setting; a search for "locale" doesn't find anything, and "date" or "language" produces far too many results to be useful!)

Alternatively, if implementing locale support here is tricky, yyyy-mm-dd could be used — or just text like "July 11, 2016" rather than short dates.

## Actual behaviour

The dates are shown in mm/dd/yyyy format, despite the fact that most locales do not use this format.

Here's an example, grabbed today (May 10, 2023). The "last release" and "last updated" dates give a clue in this case, as it's not yet September or October, but the "published" date looks valid. However, it's July 11, 2016 and not November 7, 2016.

![image](https://github.com/microsoft/vscode/assets/139183/2fcabfbf-4427-452f-9c09-32b86f1f9716)

**Comment by sandy081** [comment]
These dates are shown based on VS Code Display Language / Locale. Changing this will change the format.

**Comment by gjsjohnmurray** [comment]
![image](https://github.com/microsoft/vscode/assets/6726799/37adddb7-edda-4eab-a97e-bcf5a67e98ec)

@sandy081 please explain what I need to do to have my VS Code display in English but with "rest of the world" date ordering rather than US ordering.

**Comment by sandy081** [comment]
Not sure what is recommended here. 

@TylerLeonhardt I am using `platform.Language` to display this date string. If one changes the locale to `en-GB`, language is not picking up this. Please suggest what is recommended.

**Comment by TylerLeonhardt** [comment]
There's no such thing as `en-GB` in VS Code. We only support `en`... which basically defaults to `en-US`. Couple of options:
* use `2020/10/20` so everyone is happy (simplest)
* look at `platform.locale` which will be exactly what the user has in argv.json, but then you are going against what the language was resolved to which is `platform.language`... (aka simple, but risky...)
* we ship an en-GB language pack... (not simple... also https://github.com/microsoft/vscode-loc/issues/443)

**Comment by unikitty37** [comment]
If there's no such thing as `en-GB` (very annoying that the US seems to think their version of English is the One True Version, rather than the one spoken in England 😁 — but I understand the reason behind removing the language pack) then ISO-format dates would be least confusing for all.

**Comment by Nandha-Venkatesh** [comment]
I'd like to help with this but I keep getting thrown errors when attempting to download the dependencies for the repo with yarn so I can't test my code. I already made changes in my repo that might fix this issue but I can't test it ☹️

**Comment by devrajgadhvi** [comment]
I would love to help with the issue, Can you guide me what exactly needs to be done, are we going with "2020/10/20" this format? and where should we do change this?

**Comment by Nandha-Venkatesh** [comment]
To add to this, I believe there is already a toISOString method that can be used to convert the published, last released, and last updated dates to the ISO format. I still ran into errors when I tried to setup the environment to test my code, which is why I haven't submitted a pull request. If someone can properly test the code and confirm that it works, then they can submit a PR if they want. Otherwise, I'll submit a PR whenever I get my setup working and can test my proposed solution.

**Comment by rielAsh24** [comment]
Hey @sandy081 @unikitty37 

I was looking into this issue and implemented the `2020/10/20` format. I received the following output and wanted to confirm if it's correct:

![ISO_format](https://github.com/microsoft/vscode/assets/89381263/359f2539-369d-4480-aa87-1402ef9eb583)
