### ISSUE TITLE
Writing `vscode.CommentThread.comments` steals focus from Reply input / resets empty Reply input

### ISSUE THREAD

**Issue by hermannloose** [microsoft/vscode#182060]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.78.0 (Universal)
- OS Version: macOS Ventura 13.3.1 (a)

Steps to Reproduce:

1. Have a comment thread with multiple replies.
2. Click on "Reply".
3. Start typing a response.
4. Concurrently write `vscode.CommentThread.comments`, e.g. to add new replies fetched in the background by the extension.

Focus is removed from the Reply input when the comment list renders.

When the Reply input is open but empty, this will also close the input again, which is jarring.

![comments-update-focus-lost](https://github.com/microsoft/vscode/assets/163766/902cc40c-1aec-4cd0-992f-f1b1c507b2a2)

Expected behavior would be that updates to earlier replies (at least as long as they preserve `vscode.Comment.mode`) do not affect focus. When the Reply input is empty, it should remain open if new comments come in.

cc @JonasMa

**Comment by hermannloose** [comment]
To clarify our use case a bit more: we don't expect background updates to `comments` happening frequently (i.e. not live collaboration similar to Google Docs) but we might occasionally still receive a single new round of comments from a reviewer while the change author is currently typing a reply.

As far as I know there is no way for our extension to learn if the Reply input is open with pending content, meaning we cannot delay automatic background updates to wait until we won't interrupt the user.

**Comment by hermannloose** [comment]
Focus goes back to `body.mac` so it appears to be lost, not stolen.

**Comment by ogiekako** [comment]
It's a surprising and inconvenient behavior that updating fields in vscode.CommentThread steals focus. It'd be great if the APIs are updated not to steal the focus.

Our extension (for Gerrit code review integration) has a method to decorate a vscode.CommentThread, which currently always updates all the CommenThread's fields even if there's a field having no change. This construct makes the implementation simple, removing the need of checking the equality for every field. All was good - until we realized the bug of the focus being stolen at an unexpected timing while the user is editing the code. We will workaround the issue by introducing equality check everywhere, but I hope we could remove the workaround in future.
