### ISSUE TITLE
There was a paste issue after the version update

### ISSUE THREAD

**Issue by topazur** [microsoft/vscode#182015]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.79.0-insider
- OS Version: macOS 13.2.1

Steps to Reproduce:

1. Cursor selected row
2. First：ctrl+c
3. Second: ctrl+v
4. expect or Before the version was updated
![Kapture 2023-05-10 at 16 00  47](https://github.com/microsoft/vscode/assets/88650465/64915958-3cee-4c76-836c-a7da8ef3939f)
6. After version update
![Kapture 2023-05-10 at 15 39 00](https://github.com/microsoft/vscode/assets/88650465/fddd07c1-7fa7-4699-9959-7fee2b574ac6)

Finally，How can I set it to return to the operating logic before the update ？

**Comment by mjbvz** [comment]
Are you on the latest insiders build? I believe this issue was already fixed so please try updating

**Comment by topazur** [comment]
> Are you on the latest insiders build? I believe this issue was already fixed so please try updating

After I clicked on restart to update, it returned to normal, but the version number did not change. Is that strange?
```
版本: 1.79.0-insider
提交: 2c73d2651cc525b27fc697b820743098a204ec01
日期: 2023-05-04T22:14:17.675Z (6 天前)
```
