### ISSUE TITLE
Forward and backward of trackpad in Webview should be disabled?

### ISSUE THREAD

**Issue by yiliang114** [microsoft/vscode#182013]
Does this issue occur when all extensions are disabled?: Yes

Anywhere in the whole workspace except Webview(there may be other places), the trackpad behavior is prohibited, including forward and backward, zoom, etc,  Of course the zoom behavior via (ctrl++/--) is available.   But in Webview area,  forward, backward and zoom of trackpad, can be used.  

It's strange to be able to step back here,  It is easy to misoperate. I think it should probably be disabled here.

![image](https://github.com/microsoft/vscode/assets/11473889/b143296e-fa34-4115-9ee2-e35341837d27)

- VS Code Version:  latest vscode.dev
- OS Version:  Mac os Intel 

Steps to Reproduce:

1.  Open `https://vscode.dev`
2. Open a remote repo or any other folder.
3. Click a markdown file and Preview it, or any other operation that opens the webview
4. Use backward gesture

**Comment by TylerLeonhardt** [comment]
I still repro this in insiders.vscode.dev.

**Comment by mjbvz** [comment]
https://github.com/microsoft/vscode/issues/182013 had syntax errors. Should be fixed by 6aca75d9d09f7d9d32c18e58c836067f2d420495

However I'm going to also port this change to all webviews

**Comment by yiliang114** [comment]
hi @mjbvz Unfortunately, there does not seem to be a solution to this problem in `insiders.vscode.dev`?

![image](https://github.com/microsoft/vscode/assets/11473889/dfda90fa-7510-4c2b-878f-81d365badf29)

**Comment by yiliang114** [comment]
> hi @mjbvz Unfortunately, there does not seem to be a solution to this problem in `insiders.vscode.dev`?
> 
> ![image](https://user-images.githubusercontent.com/11473889/253284135-dfda90fa-7510-4c2b-878f-81d365badf29.png)

When I mentioned this a few months ago, I solved this problem in our company's internal version of vscode, but not through css attributes. If this issue will reopen, I can create another pr to try to solve this problem.   @mjbvz

**Comment by roblourens** [comment]
I still see this on the markdown preview
