### ISSUE TITLE
Whitespace only diffs should be highlighted somehow regardless of settings

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#182087]
This diff confused me for a bit.

![image](https://github.com/microsoft/vscode/assets/2193314/c3328416-2d77-4681-a4db-5d2c6b25ef79)

There's a trailing space at the end of the line but it's not highlighted. This would be even more confusing if you have non-visible whitespace (I think that's the default).

**Comment by hediet** [comment]
I bet you disabled whitespace diffing. Why should this setting be ignored now?

**Comment by Tyriar** [comment]
I have `"diffEditor.ignoreTrimWhitespace": false` set, which means whitespace should show right? Setting to true doesn't show it either. Am I looking at the wrong setting?

The why even if it's ignored is I click for more info and it shows nothing which confused me, I can understand why you wouldn't want to handle it specially though.
