### ISSUE TITLE
CODE NOT RUNNING

### ISSUE THREAD

**Issue by MNarayan04** [microsoft/vscode#182096]
THE CODE IS NOTE RUNNING .. 
 PREVIOUS CODE WERE RUNNING BUT NEWLY MADE C++ FILE ARE NOT RUNNING

**Comment by SooryaSRajan** [comment]
> THE CODE IS NOTE RUNNING ..
> PREVIOUS CODE WERE RUNNING BUT NEWLY MADE C++ FILE ARE NOT RUNNING

Code running has nothing to do with the IDE. Check if your compiler paths have been exported properly and try using the CLI manually for compilation.
