### ISSUE TITLE
support call extension command via vscode schema url

### ISSUE THREAD

**Issue by tjx666** [microsoft/vscode#182047]
My use case:

I want to open gitlens branchs compare view from web page with link like:

`vscode://gitlens.compare?branch1=xxx&branch2=yyy`

<img width="1440" alt="image" src="https://github.com/microsoft/vscode/assets/41773861/867adba6-6a53-49a1-aff5-9fc5f105ba2a">

After search, I can't find a universal method to call command via vscode schema.

My proposal:

provide a universal url handle to call extension command with format:

```
vscode://command/commandId?arg1=xxx&arg2=yyy
```

before you can call this command, user must add the command to white list in settings:

```
// settings.json
"command.callBySchema.whiteList": [
	"command.commandId"
]
```

@eamodio

**Comment by mjbvz** [comment]
See the [UriHandler api](https://github.com/microsoft/vscode/blob/cc443365dcf57248436812e218805983f426cabe/src/vscode-dts/vscode.d.ts#L10244) It lets your extension be invoked from an external uri

**Comment by eamodio** [comment]
@tjx666 This sounds like a great feature request for GitLens, and we are already adding more deep link support directly into GitLens on the desktop (though we are still blocked from using deep links on vscode.dev /cc @bamurtaugh). We also have a not-yet public chrome extension that adds some deep link ability to GitHub (though hadn't considered this one -- so please file it).

**Comment by bamurtaugh** [comment]
Thanks for the tag @eamodio! cc @joyceerhl for the deep link aspect.
