### ISSUE TITLE
EnvironmentVariableCollection API enhancements

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#182069]
This issue tracks the overall improvements for the upcoming API improvements so they're all in one place:

- https://github.com/microsoft/vscode/issues/179476
- https://github.com/microsoft/vscode/issues/171173
- https://github.com/microsoft/vscode/issues/171108

We don't currently have a proposal for the first issue but the combined proposal for the other two is currently:

```ts
export interface EnvironmentVariableMutator {
	readonly type: EnvironmentVariableMutatorType;
	readonly value: string;
	readonly scope: EnvironmentVariableScope | undefined;
}

export interface EnvironmentVariableCollection extends Iterable<[variable: string, mutator: EnvironmentVariableMutator]> {
	/**
	 * Sets a description for the environment variable collection, this will be used to describe the changes in the UI.
	 * @param description A description for the environment variable collection.
	 * @param scope The scope to which this description applies to. If unspecified, operation applies to all
	 * workspace folders.
	 */
	setDescription(description: string | MarkdownString | undefined, scope?: EnvironmentVariableScope): void;

	replace(variable: string, value: string, scope?: EnvironmentVariableScope): void;
	append(variable: string, value: string, scope?: EnvironmentVariableScope): void;
	prepend(variable: string, value: string, scope?: EnvironmentVariableScope): void;
	get(variable: string, scope?: EnvironmentVariableScope): EnvironmentVariableMutator | undefined;
	delete(variable: string, scope?: EnvironmentVariableScope): void;
	clear(scope?: EnvironmentVariableScope): void;
}

export type EnvironmentVariableScope = {
	/**
	* The workspace folder to which this collection applies to. If unspecified, collection applies to all workspace folders.
	*/
	workspaceFolder?: WorkspaceFolder;
};
```

I have given feedback about `scope` being everywhere and maybe we should have a `getScopedEnvironmentVariableCollection` API on `ExtensionContext` instead of peppering it everywhere.

**Comment by karrtikr** [comment]
Alternative proposal:

```typescript
export interface ExtensionContext {
    /**
     * Gets the extension's environment variable collection for this workspace, enabling changes
     * to be applied to terminal environment variables.
     * 
     * @param scope The scope to which the environment variable collection applies to.
     */
    getEnvironmentVariableCollection(scope?: EnvironmentVariableScope): EnvironmentVariableCollection;
}

export type EnvironmentVariableScope = {
	/**
	* The workspace folder to which this collection applies to. If unspecified, collection applies to all workspace folders.
	*/
	workspaceFolder?: WorkspaceFolder;
};

export interface EnvironmentVariableCollection extends Iterable<[variable: string, mutator: EnvironmentVariableMutator]> {
	/**
	 * A description for the environment variable collection, this will be used to describe the
	 * changes in the UI.
	 */
	description: string | MarkdownString | undefined;
}
```
Note the following already exists, so we'll be duplicating APIs, in cases where `scope` is not required:
```typescript
export interface ExtensionContext {
    /**
     * Gets the extension's environment variable collection for this workspace, enabling changes
     * to be applied to terminal environment variables.
     */
    readonly environmentVariableCollection: EnvironmentVariableCollection;
}
```

**Comment by karrtikr** [comment]
Another thing to keep in mind is In the future we may also be adding `options` parameter to `.replace()` API.

**Comment by Tyriar** [comment]
Comments/open questions:

> `readonly scope: EnvironmentVariableScope | undefined;`

This instead?

```ts
readonly scope?: EnvironmentVariableScope
```

> `getEnvironmentVariableCollection(scope?: EnvironmentVariableScope): EnvironmentVariableCollection;`

Do we need some way to enumerate and delete collections?

> `getEnvironmentVariableCollection(scope?: EnvironmentVariableScope): EnvironmentVariableCollection;`

My preference if we go this route:

```ts
getScopedEnvironmentVariableCollection(scope: EnvironmentVariableScope): EnvironmentVariableCollection;
```

> ```ts
> export interface EnvironmentVariableCollection extends Iterable<[variable: string, mutator: EnvironmentVariableMutator]> {
> 	/**
> 	 * A description for the environment variable collection, this will be used to describe the
> 	 * changes in the UI.
> 	 */
> 	description: string | MarkdownString | undefined;
> }
> ```

Do we need a note here about only taking the first line of the description?

**Comment by Tyriar** [comment]
Feedback from API sync:

- Workspace scope
  - How does the default and scoped collections interact? @karrtikr and I chatted about this; they are completely separate objects and are both applied, similar to how 2 extension collections both apply. We need to make sure this is explained well in the jsdoc
  - `getScopedEnvironmentVariableCollection` should live under `EnvironmentVariableCollection`, maybe as `getScoped`?
  - We can use `EnvironmentVariableCollection & { getScoped(workspace) }` as the type, or `Exclude<EnvironmentVariableCollection, 'getScoped'>`. Whatever way is preferred in the future API sync
  - Still not sure if we need a way to get all scoped collections and/or delete them, let's assume no for now as an extension can always do `getScoped(workspace).clear()`
- Description
  - Let's finalize the `description` property 🚀

**Comment by karrtikr** [comment]
Closing in favor of https://github.com/microsoft/vscode/issues/171173 as the other proposal is finalized.
