### ISSUE TITLE
Highlight issue with Array

### ISSUE THREAD

**Issue by unional** [Microsoft/vscode#18202]
- VSCode Version: 1.8.1

```ts
let x: Array<{ name: string, fn(): any, field: string }>
```

![image](https://cloud.githubusercontent.com/assets/3254987/21703741/2b7677c6-d369-11e6-9d05-a7841a457cf2.png)

notice after `fn()` the highlight does not work.

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript-TmLanguage#398

**Comment by unional** [comment]
Thanks. btw, "This issue IS moved to ...". Please delete this comment after you see it. 🌷
