### ISSUE TITLE
Add a keyboard shortcut for staging the current file

### ISSUE THREAD

**Issue by tht13** [Microsoft/vscode#1821]
It would be great if there was a keyboard shortcut, or at least an unassigned command, to stage the current file (ie git add) so that the entire process could be done with the keyboard. 
Also navigation of the git add and git revert icons in the git sidebar by keyboard would also be nice (I don't think this can even be done in accessibility mode).

**Comment by joaomoreno** [comment]
This is a really cool idea. Do you want to try to tackle it?

We have code to handle [staging ranges](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/git/common/stageRanges.ts) and an [example action](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/git/browser/gitActions.contribution.ts#L251) that uses it, as a starting point.

**Comment by tht13** [comment]
I can have a go :smile:  I see this was also a feature request in this issue #150

**Comment by massimocode** [comment]
@tht13 hey did you have any luck with this? This would be an awesome addition!

**Comment by joaomoreno** [comment]
@massimocode Feel free to pick it up!

**Comment by tht13** [comment]
@joaomoreno I have been re-looking into this, do you have any advice or example to look at for binding such a keyboard shortcut. I know where to bind it and have found examples of how other actions are bound (toggleLineComment and showGitView) but the interfaces that the registration methods for those use are incompatible. Do you have a method which can take a GitAction? 

An alternative I have thought of is creating an API for git actions, and utilising that to provide shortcuts however that is a much bigger engineering task which would require significant development and its own milestone task.

**Comment by joaomoreno** [comment]
What you wanna do is to [register your action as a workbench action](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/git/browser/gitActions.contribution.ts#L473). The `SyncActionDescriptor` even [supports specifying default keybindings for it](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/git/browser/gitWorkbenchContributions.ts#L474), if that is what you mean. But I think we can simply make the action available as a global command with that initial registration leaving the keybinding up to user to configure in the `keybindings.json` file... similar to all other git actions. What do you think?

**Comment by tht13** [comment]
I had done down a similar path trying to apply [GitActions.StageAction](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/git/browser/gitActions.ts#L282) to `SyncActionDescriptor` however it was incompatible. I will try wrapping it in `GitActions.Contributions.ts` and see how that goes.

I think an unbound command would suffice, VSCode is running out of suitable shortcuts anyway :stuck_out_tongue: 

If I register it as a workbench action (I assume that means it appears in the `F1` quick actions) will it automatically appear in keybindings.json in the commented section which shows unbound actions?

Thanks for the help :smile:

**Comment by joaomoreno** [comment]
Yes it will!

**Comment by joaomoreno** [comment]
Closed by #6897, thanks @tht13 !
