### ISSUE TITLE
Add an option to launch.json to include another launch.json 

### ISSUE THREAD

**Issue by dabrain34** [microsoft/vscode#182188]
It would be great for a project's `launch.json` to include custom_launch.json files 
In that manner the comon `launch.json` could be commited to the VCS and the custom not.
```
configurations": [
    {
      "type": "node",
      // Relative path to launch.json 
      "ref": "./path/to/other.launch.json"
    }
```

**Comment by roblourens** [comment]
For private launch configs I recommend using a multiroot workspace and putting your own launch configs in the workspace config file
