### ISSUE TITLE
Syntax coloring for "yield" keyword

### ISSUE THREAD

**Issue by ThisIsManta** [Microsoft/vscode#18213]
- VSCode Version: 1.8.1
- OS Version: Windows 10 Home

The `yield` keyword needs to be highlighted just like `await`. There are 2 cases here:
```js
yield doSomethingThatDoesNotReturn(); // The yield here is highlighted correctly.

const result = yield doSomething(); // The yield here is **NOT** highlighted.
```

Note that I was using **Light (Visual Studio)** theme.

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript-TmLanguage#400

**Comment by ThisIsManta** [comment]
Thanks for the good work!
