### ISSUE TITLE
vscode.dev android webapp stuck in portrait

### ISSUE THREAD

**Issue by kthornbloom** [microsoft/vscode#182128]
I was trying vscode.dev in Chrome on an android device. It works fine in the browser, but if I "Add to Homescreen" so I can pull it up as a full screen webapp, it is stuck in portrait mode. 

I would expect it to follow the device's rotation

Version: 1.78.1
Commit: 6a995c4f4cc2ced6e3237749973982e751cb0bf9
User Agent: Mozilla/5.0 (Linux; Android 13; SM-G988U1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Mobile Safari/537.36
Embedder: vscode.dev

**Comment by TylerLeonhardt** [comment]
Hmm so I can't repro this in iOS or iPad OS... and we're not doing anything fancy in our manifest to mess with device rotation:
https://vscode.dev/static/stable/code.webmanifest

We are not specifying `orientation` there which is supposed to mean "let the OS decide what to do". 

I did see this SO post saying that Chrome for Android was aggressively caching the manifest... so maybe clear the cache just in case you have some old version of the manifest that maybe had orientation set.
https://stackoverflow.com/a/38166340

Let us know how it goes!

**Comment by kthornbloom** [comment]
@TylerLeonhardt - welp, just tried it again and seems to be working just fine now. Apologies for the false bug report!
