### ISSUE TITLE
Untitled files are not considered dirty?

### ISSUE THREAD

**Issue by karrtikr** [microsoft/vscode#182124]
@bpasero When using proposed API "saveEditor" to save Untitled files, nothing happens.
Behavior should match with 
![image](https://github.com/microsoft/vscode/assets/13199757/2d9eb12f-7d34-4094-8344-7fb8174de04f)

**Comment by bpasero** [comment]
I cannot reproduce given this code:

```ts
export function activate(context: vscode.ExtensionContext) {

	// Use the console to output diagnostic information (console.log) and errors (console.error)
	// This line of code will only be executed once when your extension is activated
	console.log('Congratulations, your extension "test-ts" is now active!');

	// The command has been defined in the package.json file
	// Now provide the implementation of the command with registerCommand
	// The commandId parameter must match the command field in package.json
	let disposable = vscode.commands.registerCommand('test-ts.helloWorld', async () => {
		// The code you place here will be executed every time your command is executed
		// Display a message box to the user
		const rs = await vscode.workspace.save(vscode.window.activeTextEditor!.document.uri);
	});

	context.subscriptions.push(disposable);
}
```
![Recording 2023-05-11 at 07 01 38](https://github.com/microsoft/vscode/assets/900690/794e1066-782b-448d-90f8-d6eeecfc9398)

**Comment by karrtikr** [comment]
Sorry, we were doing an extra `doc.isDirty()` check before calling the API, and it seems that unpersisted changes in untitled files are not considered dirty.

![image](https://github.com/microsoft/vscode/assets/13199757/fd70c4ab-8c9d-4e4e-8e8f-8bf95b348c82)

If this is expected feel free to close the issue, thanks for checking!

**Comment by bpasero** [comment]
An untitled file is not dirty when you open it, it requires changes. As soon as it has changes, it will be dirty.
