### ISSUE TITLE
Theme selection palette broken

### ISSUE THREAD

**Issue by kumarharsh** [Microsoft/vscode#18212]
- VSCode Version: 1.9.0-insider, 80481e
- OS Version: Windows 10

Steps to Reproduce:

1. Open the color theme selection palette
2. Type a theme name
3. When I select a theme, it shows the correct colors applied in the preview mode, but when I press <ENTER>, a different theme is applied.

In this example, I select "Afterglow", and vscode applies "Abyss"

![bug](https://cloud.githubusercontent.com/assets/760112/21712348/56945cc8-d41a-11e6-8ad3-da62a0dcd8c1.gif)

**Comment by sandy081** [comment]
@kumarharsh This is working for me correctly. I also tried with "Afterglow" theme. Is there any other steps you did that can help us in reproducing this issue?

**Comment by kumarharsh** [comment]
@sandy081 it seems like it's fixed now. I ran into this bug while running yesterday's build. I updated vscode just after making the gif, and it seems to be working fine now.
