### ISSUE TITLE
UNC allow list should not fail for resolved mapped network drives or symbolic links

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#182196]
Seeing an increase in issues (such as https://github.com/microsoft/vscode/issues/182185) where a mapped network drive or symbolic link points to a UNC path. If you use node.js methods such as `fs.readlink` or `fs.realpath.native` to resolve these paths to their UNC equivalent and use them for further file operations, our UNC allow list might prevent use of these paths until you add them to the allow list.

We should discuss if there are options here to make this easier on the impacted users. The issue often goes unnoticed because we do not prompt the user on startup for these paths to add them to the allow list.

**❗Workaround**
Given an exception like this one:

```
Error: Debug Failure. False expression: z:/home/siddharth/workspace/newWebUi/facilgo-web-ui/node_modules/react-table-6/index.d.ts linked to nonexistent file //wsl$/Ubuntu-20.04/home/siddharth/workspace/newWebUi/facilgo-web-ui/node_modules/react-table-6/index.d.ts
    at realPath (c:\Users\smish\.vscode\extensions\ms-vscode.vscode-typescript-next-5.1.20230510\node_modules\typescript\lib\tsserver.js:42142:9)
    at getOriginalAndResolvedFileName (c:\Users\smish\.vscode\extensions\ms-vscode.vscode-typescript-next-5.1.20230510\node_modules\typescript\lib\tsserver.js:41079:28)
```

Find the resolved file path (here `//wsl$/Ubuntu-20.04/home...`) and add the hostname of the path (the value between `//` and the first `/` after that) to the `security.allowedUNCHosts` setting (here: `wsl$`). Then restart VS Code.

See also: https://aka.ms/vscode-windows-unc

**Comment by rwalle** [comment]
There are some cases that are a bit difficult to handle: In my company, people always either use the raw path `\\company\dev\files\folder` to access files, or map a drive to `\\company\dev\files\` and then access files using the mapped drive name. However the real path is `\\file-server\files\` , which is on a server that most developers have never directly interacted with or even heard of (and there are a number of these file servers depending on the exact path). The TS server and likely many other extensions use this real path in their code, and when it does not have access the server crashes. The only way developers would be able to know the host names causing problems and add them to the allowed host list is by examining the error message of extension host which is extremely user-unfriendly.

**Comment by JimmyBjorklund** [comment]
Is there a way to get an older version of vscode ? The current version is unusable as long as this bug persists.

**Comment by JimmyBjorklund** [comment]
> Is there a way to get an older version of vscode ? The current version is unusable as long as this bug persists.

https://github.com/microsoft/vscode/issues?q=is%3Aissue+milestone%3A%22March+2023+Recovery+3%22+is%3Aclosed

**Comment by anodynos** [comment]
This worked for me 
```
    "security.allowedUNCHosts":[
        "wsl.localhost"
    ]
```
**Note**: omit the leading `\\`  and the `\` at the end.

**Comment by deepak1556** [comment]
/fixedWith https://github.com/microsoft/vscode/commit/35da3a2c8ae79754ae555af69066bbfe597e5665

**Comment by deepak1556** [comment]
Steps for verification:

* create a [mapped network drive](https://support.microsoft.com/en-us/windows/map-a-network-drive-in-windows-29ce55d1-34e3-a7e2-4801-131475f9557d) that points to a localhost UNC folder which has a Typescript project
* open the mapped network drive  `code-insiders z:\<path-to-typescript-project>`
* verify TypeScript smartness works and shows no errors in the TS server output logs

**Comment by iomedico-beyer** [comment]
For some reason I wish to go back to 1.78 until there is a release which included the fix. However I cannot find the zip (needed to make VSC portable) on the [1.78 download page](https://code.visualstudio.com/updates/v1_78). Any idea where to find it?

**Comment by bpasero** [comment]
The fix for this is in `1.79.x` releases.

**Comment by amitasil** [comment]
I am still getting this error while using the cucumber.io extension

![image](https://github.com/microsoft/vscode/assets/26156829/156638ea-2dee-49d4-9f26-ba92ac29506f)

**Comment by bpasero** [comment]
@amitasil can you give more details, did you configure the setting accordingly?

**Comment by bpasero** [comment]
Are we certain this is related to UNC paths? Whats the extension repository, maybe reach out to them as well?

**Comment by bpasero** [comment]
I see no UNC mentioned in any of these issues, so I consider it unrelated.

**Comment by francisco-nunez-bcp-matrix** [comment]
> @amitasil can you give more details, did you configure the setting accordingly?

@bpasero , you have a example from this configuration ??
