### ISSUE TITLE
improve package.json parsing performance

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#18218]
I have made the below modification to the [`ExtensionManifestParser`](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/node/extensionPoints.ts#L83) and it seems that the general performance of our JSON in comparing to the native JSONparse is OK'ish there are cases in which it is very bad. For instance parsing [`css/package.json`](https://github.com/Microsoft/vscode/blob/master/extensions/css/package.json#L1) takes 0.3ms using `JSON.parse` it takes 8ms using our parser. Other larger json files show similar behaviour.

![screen shot 2017-01-06 at 11 26 02](https://cloud.githubusercontent.com/assets/1794099/21715101/f142a4ae-d402-11e6-9808-d53c67dc9d9b.png)

```ts
let t1 = process.hrtime();
const extensionDescription = json.parse(manifestContents.toString(), errors);
let d = process.hrtime(t1);
let D1 = (d[0] * 1e9 + d[1]) / 1e6;

let t2 = process.hrtime();
JSON.parse(manifestContents.toString());
let d2 = process.hrtime(t2);
let D2 = (d2[0] * 1e9 + d2[1]) / 1e6;

console.log(`PARSE + ${this._absoluteManifestPath} took ${D1}ms, NATIVE ${D2}ms`);
```

**Comment by jrieken** [comment]
Assigning @aeschli to see if there is something low hanging that can be improved and @sandy081 to check if we can get away with stripping comments and using JSON.parse

**Comment by aeschli** [comment]
Comments are not valid in package.json. We can use the native json.parser. The only difference is that our implementation is fault tolerant, but IMO that's not important here.
I had a quick look at our parser implementation and also improved it slightly, but it's unlikely that we can match the native implementation.
