### ISSUE TITLE
Crash when closing a native tab

### ISSUE THREAD

**Issue by PSalant726** [microsoft/vscode#182142]
Type: <b>Bug</b>

1. On macOS, open multiple workspaces, each in a separate native tab
2. Close one of the native tabs using either its close button (appears on hover) or Cmd + W
3. Observe that the application crashes

VS Code version: Code 1.78.1 (Universal) (6a995c4f4cc2ced6e3237749973982e751cb0bf9, 2023-05-04T09:57:42.343Z)
OS version: Darwin x64 22.4.0
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-8100 CPU @ 3.60GHz (4 x 3600)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|4, 4, 3|
|Memory (System)|16.00GB (0.34GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (36)</summary>

Extension|Author (truncated)|Version
---|---|---
markdown-preview-github-styles|bie|2.0.2
npm-intellisense|chr|1.4.4
path-intellisense|chr|2.8.4
vscode-eslint|dba|2.4.0
jquerysnippets|don|0.0.1
xml|Dot|2.5.1
gitlens|eam|13.5.0
vscode-pull-request-github|Git|0.64.0
go|gol|0.38.0
haml|kar|1.4.1
bash-ide-vscode|mad|1.36.0
rainbow-csv|mec|3.7.0
vscode-docker|ms-|1.25.0
isort|ms-|2022.8.0
python|ms-|2023.8.0
vscode-pylance|ms-|2023.5.20
jupyter|ms-|2023.4.1011241018
jupyter-keymap|ms-|1.1.0
jupyter-renderers|ms-|1.0.15
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-slideshow|ms-|0.1.5
atom-keybindings|ms-|3.3.0
sqltools|mtx|0.27.1
sqltools-driver-pg|mtx|0.5.1
material-icon-theme|PKi|4.27.0
ruby|reb|0.28.1
sass-indented|rob|1.5.1
gitconfig|sid|2.0.1
even-better-toml|tam|0.19.0
shellcheck|tim|0.32.5
pdf|tom|1.2.2
errorlens|use|3.11.0
vscode-todo-highlight|way|1.0.5
vscode-ruby|win|0.28.0
JavaScriptSnippets|xab|1.8.0
vscode-proto3|zxh|0.5.5

(1 theme extensions excluded)

</details>

**Comment by coolzjy** [comment]
Seems duplicate with #167936

**Comment by PSalant726** [comment]
Closing in favor of https://github.com/microsoft/vscode/issues/167936.
