### ISSUE TITLE
The `source` property of problem matchers is not documented

### ISSUE THREAD

**Issue by akbyrd** [microsoft/vscode#182168]
This page mentions it exists https://code.visualstudio.com/docs/editor/tasks
This page is missing it entirely https://code.visualstudio.com/docs/editor/tasks-appendix

It's an important one too. If it's missing then the "code" property is silently thrown away and it's a pain to figure out why it's not showing up in the problems view.

**Comment by babakks** [comment]
@meganrogge I've just submitted a PR in the docs repo. Could you please review it?
