### ISSUE TITLE
Navigate to next/previous symbolic match in file

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#18214]
Similarly to the navigation in textual matches: The editor could offer navigation between symbolic matches.

E.g., I often find myself with the text cursor on a symbol, looking at the overview ruler to see the other occurrences of that symbol and wanting to navigate through these. Currently I have to use the mouse to click through the other occurrences in the overview ruler, it would be great to have a way to do the same with the keyboard.

**Comment by alexandrudima** [comment]
How this could be implemented:
* `wordHighlighter` (under editor/contrib) could maintain a context key through `IContextKeyService` e.g. `hasWordHighlights`. This context key can be updated as necessary based on the current word highlights.
* two new commands could be contributed by `wordHighlighter` that set the editor selection to the next/prev word highlight.

**Comment by samjjc** [comment]
I would like to work on this. It might take a little time, though. I am new here.
