### ISSUE TITLE
Python multi-line comment strings should be treated as comments in all themes

### ISSUE THREAD

**Issue by ElectricRCAircraftGuy** [microsoft/vscode#182163]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.78.1
- OS Version: Linux Ubuntu 20.04

Steps to Reproduce:

1. Set the color theme to Monokai. Comment block strings should be highlighted the same as single-line comments, just like Monokai in Sublime Text, but in VSCode they are not. 

Fixed by PR #182162 <-- **see screenshots here** too!

**Comment by ElectricRCAircraftGuy** [comment]
@VSCodeTriageBot , I just updated to version 1.78.1, the latest, and the issue is still present.

**Comment by aeschli** [comment]
To verify:
create a python file with a doc string, e.g.
```
def my_function():
	'''Demonstrates triple double quotes
	docstrings and does nothing really.'''

	return None

print("Using __doc__:")
print(my_function.__doc__)

print("Using help:")
help(my_function)

```
Verify that `Demonstrates triple double quotes docstrings and does nothing really.` get the same color as a comment
That's for all built-in themes, not only Monokai.
