### ISSUE TITLE
Abnormal information was generated when testing vscode!

### ISSUE THREAD

**Issue by DigOrDog** [microsoft/vscode#182161]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: Code 1.78.1([6a995c4](https://github.com/microsoft/vscode/commit/6a995c4f4cc2ced6e3237749973982e751cb0bf9))
- OS Version: Windows 10 Pro

Steps to Reproduce:
I used a testing tool to run vscode, with a testing time of 5 hours. The testing process has been uploaded to YouTube, and the link is [here](https://drive.google.com/file/d/1zKO1kqj5Mxk-rToxCpuO5f0r-Axs8pbv/view?usp=sharing).

After completing the test, the tool scanned the generated log files and found some abnormal information.  
>error:C:\Users\d\AppData\Roaming\Code\logs\20230510T203100\sharedprocess.log
exception:C:\Users\d\AppData\Roaming\Code\logs\20230510T203100\sharedprocess.log
error:C:\Users\d\AppData\Roaming\Code\logs\20230510T204857\sharedprocess.log
exception:C:\Users\d\AppData\Roaming\Code\logs\20230510T204857\sharedprocess.log
error:C:\Users\d\AppData\Roaming\Code\logs\20230510T211602\network.log
failed:C:\Users\d\AppData\Roaming\Code\logs\20230510T211602\network.log
error:C:\Users\d\AppData\Roaming\Code\logs\20230510T211602\sharedprocess.log
exception:C:\Users\d\AppData\Roaming\Code\logs\20230510T211602\sharedprocess.log
error:C:\Users\d\AppData\Roaming\Code\logs\20230510T220442\sharedprocess.log
exception:C:\Users\d\AppData\Roaming\Code\logs\20230510T220442\sharedprocess.log
error:C:\Users\d\AppData\Roaming\Code\logs\20230510T235617\sharedprocess.log
exception:C:\Users\d\AppData\Roaming\Code\logs\20230510T235617\sharedprocess.log
error:C:\Users\d\AppData\Roaming\Code\logs\20230511T001311\sharedprocess.log
exception:C:\Users\d\AppData\Roaming\Code\logs\20230511T001311\sharedprocess.log
error:C:\Users\d\AppData\Roaming\Code\logs\20230510T211602\window1\renderer.log
failed:C:\Users\d\AppData\Roaming\Code\logs\20230510T211602\window1\renderer.log
error:C:\Users\d\AppData\Roaming\Code\logs\20230510T203100\window1\exthost\exthost.log
error:C:\Users\d\AppData\Roaming\Code\logs\20230510T203100\window1\output_20230510T203101\tasks.log
error:C:\Users\d\AppData\Roaming\Code\logs\20230510T204857\window1\exthost\exthost.log
error:C:\Users\d\AppData\Roaming\Code\logs\20230510T204857\window1\output_20230510T204858\tasks.log
error:C:\Users\d\AppData\Roaming\Code\logs\20230510T211602\window1\exthost\exthost.log
error:C:\Users\d\AppData\Roaming\Code\logs\20230510T211602\window1\output_20230510T211602\tasks.log
error:C:\Users\d\AppData\Roaming\Code\logs\20230510T220442\window1\exthost\exthost.log
error:C:\Users\d\AppData\Roaming\Code\logs\20230510T220442\window1\output_20230510T220442\tasks.log
error:C:\Users\d\AppData\Roaming\Code\logs\20230510T232012\window1\exthost\exthost.log
error:C:\Users\d\AppData\Roaming\Code\logs\20230510T232012\window1\output_20230510T232013\tasks.log
error:C:\Users\d\AppData\Roaming\Code\logs\20230510T234111\window1\exthost\exthost.log
error:C:\Users\d\AppData\Roaming\Code\logs\20230510T234111\window1\output_20230510T234112\tasks.log
error:C:\Users\d\AppData\Roaming\Code\logs\20230510T235617\window1\exthost\exthost.log
error:C:\Users\d\AppData\Roaming\Code\logs\20230510T235617\window1\output_20230510T235619\tasks.log
error:C:\Users\d\AppData\Roaming\Code\logs\20230511T001311\window1\exthost\exthost.log
error:C:\Users\d\AppData\Roaming\Code\logs\20230511T001311\window1\output_20230511T001311\tasks.log
error:C:\Users\d\AppData\Roaming\Code\logs\20230511T004645\window1\exthost\exthost.log
error:C:\Users\d\AppData\Roaming\Code\logs\20230511T004645\window1\output_20230511T004647\tasks.log
error:C:\Users\d\AppData\Roaming\Code\logs\20230511T005124\window1\exthost\exthost.log
error:C:\Users\d\AppData\Roaming\Code\logs\20230511T005124\window1\output_20230511T005125\tasks.log

>
The log information is saved to log.7z, with the following [link](https://drive.google.com/file/d/1Z03pwduq0WtWmW5Udn-kaR-vHayo9Lo-/view?usp=sharing)

**Comment by connor4312** [comment]
It looks like the sharedprocess/network errors are mostly transient issues

**Comment by DigOrDog** [comment]
From this log, it seems that this issue is related to network communication. I tried to disconnect the network and open the extensions of vscode. An error message will appear, as shown in the following figure.
![image](https://github.com/microsoft/vscode/assets/87884938/436df520-f6bb-40a0-9fcf-ad62277300dc)
However, from the above video, there is no prompt regarding Error, so does this issue need to be resolved?
