### ISSUE TITLE
VSCode does not open when used on remote (RDP)

### ISSUE THREAD

**Issue by worc4021** [microsoft/vscode#182180]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.78.1
- OS Version: Win 10 19045.2728

Steps to Reproduce:

1.  Update to 1.78.1 on remote (RDP).
2.  Try opening vscode. Process(es) start(s) but no windows open. No error, nothing, just no window opening.

Works fine when reverting to 1.76 (I didn't test other versions but had the installer lying around for 1.76)

Best,
Manuel

**Comment by rzhao271** [comment]
Hi, could you create and attach a crash report following the steps at https://github.com/microsoft/vscode/wiki/Native-Crash-Issues#creating-a-crash-report?

**Comment by worc4021** [comment]
Hello!

I updated to the current version again and ran followed the instructions to produce a dump folder. However, apart from the folder structure being initialised in the folder, there is only one `settings.dat`. In particular the `*.dmp` file was not created.

Apologies for being no help.
Cheers,
Manuel

**Comment by worc4021** [comment]
Hello again! 

I have determined the issue. It is unrelated to the RDP. It is some UNC path that our profiles seem to refer to on domain, https://code.visualstudio.com/docs/setup/windows#_working-with-unc-paths. Allowing the server makes things work fine again. 

Interestingly, the crash dump doesn't get there, but the `code --verbose` does show what is going on.

Apologies for any confusion caused.

Cheers,
Manuel
