### ISSUE TITLE
Cannot run a debugger

### ISSUE THREAD

**Issue by Elysys** [microsoft/vscode#182199]
Type: <b>Bug</b>

We open a project in VSC, set the break point and
start the debugger with F5.
The app opens the Browser in debug mode.
When the code hits the break point,
the VSC code takes the focus and shows the line. So far all good
I press F11 to move to next line in the debugger, and at the next line the debugger and VSC freezes.
The only way to  resolve this situation is to disable the debugger or to press a few times F5.
We use the language AL, based on Dynamics 365 Business central.  

Currently we are not able to use the debugger at all, which is a big problem.
Thanks for your help.

Ivan Vukadinovic

VS Code version: Code 1.78.1 (6a995c4f4cc2ced6e3237749973982e751cb0bf9, 2023-05-04T09:48:08.683Z)
OS version: Windows_NT x64 10.0.14393
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD EPYC 7452 32-Core Processor                 (8 x 2346)|
|GPU Status|2d_canvas: unavailable_software<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>opengl: disabled_off<br>rasterization: disabled_software<br>raw_draw: disabled_off_ok<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software<br>webgpu: unavailable_software|
|Load (avg)|undefined|
|Memory (System)|64.00GB (7.17GB free)|
|Process Argv|--crash-reporter-id 35d4835d-0cf9-4ba4-8cce-9915e1fc64da|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (30)</summary>

Extension|Author (truncated)|Version
---|---|---
al-code-outline|and|3.0.46
al-toolbox|Bar|2.0.28
bracket-select|chu|2.0.2
al-codeactions|dav|1.0.29
githistory|don|0.6.20
gitlens|eam|13.5.0
todo-tree|Gru|0.0.226
rest-client|hum|0.25.1
al-test-runner|jam|0.9.0
mdal|jon|0.4.1
al-object-designer|mar|0.2.4
vscode-docker|ms-|1.25.0
al|ms-|11.0.787898
powershell|ms-|2023.5.0
team|ms-|1.161.1
al-snippets|myn|0.0.2
nab-al-tools|nab|1.30.0
createGUID|nwa|0.0.2
al-formatter|ras|3.0.0
al-var-helper|ras|2.4.0
xliff-sync|rva|1.4.0
partial-diff|ryu|1.4.3
markdown-preview-enhanced|shd|0.6.8
businesscentral-lintercop|ste|0.1.4
code-spell-checker|str|2.20.4
vscode-icons|vsc|12.4.0
al-extension-pack|wal|1.0.21
crs-al-language-extension|wal|1.5.25
vscode-todo-highlight|way|1.0.5
al-navigator|wbr|0.5.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes516:30244333
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
2e4cg342:30602488
pyind779:30671433
89544117:30613380
pythonsymbol12:30671437
a9j8j154:30646983
showlangstatbar:30737416
vsctsb:30705553
azdwalk:30721579
pythonms35:30701012
pythonfmttext:30731395
pythoncmvfstr:30731969
fixshowwlkth:30730052
pythongtdpathcf:30731979

```

</details>

**Comment by gjsjohnmurray** [comment]
/duplicate and will be fixed in 1.78.2 which is expected later today.
