### ISSUE TITLE
Word wrapping enabled through the menu is reset whenever settings.json is modified

### ISSUE THREAD

**Issue by rotemdan** [Microsoft/vscode#18210]
- VSCode Version:
1.8.1, latest insider build
- OS Version:
Windows 10 x64

Steps to Reproduce:
1. Make sure that wrapping isn't permanently enabled, and if it is, remove any permanent setting related to wrapping.
2. Open a file that contains lines longer than the width of the screen.
3. Enable word wrapping through `View` -> `Toggle Word Wrap`.
4. Modify one character in `settings.json` and save it.
5. Word wrapping should be unexpectedly disabled.

This behavior makes extensions that modify configuration based on user actions, constantly reset the wrapping setting. For example [this issue with vscode-spellchecker](https://github.com/swyphcosmo/vscode-spellchecker/issues/24) where the wrapping is reset every time the user selects to "always ignore" a word because that action causes `settings.json` to be modified with the newly ignored word.

**Comment by rotemdan** [comment]
Seems like the same behavior happens with the `Toggle Render Whitespace` and  `Toggle Control Characters` menu options as well.

**Comment by alexandrudima** [comment]
Test plan item is #18316

**Comment by rotemdan** [comment]
The quick response was amazing! I'm already seeing this on the Insider build. Thanks!
