### ISSUE TITLE
Extension API: Provide the option for Code Lenses to be stacked vertically in the margin

### ISSUE THREAD

**Issue by StanFromTraction** [microsoft/vscode#182225]
Hey,

I use Copilot Lab's Brushes extension. It's amazing, but since the lenses are quite tall and keep popping up whenever you select text or a function, they cause the editor to vertically shift. 

Not only is it visually jarring, but it also "breaks" code selection; you must either predict the shift or wait for it to happen to reposition your cursor and avoid selecting the wrong lines.

Since the left margin is mostly empty (with a few edge cases like the Code Actions icon), it makes sense for the lenses to appear vertically stacked in the margin. That way they don't interfere.

**Comment by gjsjohnmurray** [comment]
Related to #90235

**Comment by roblourens** [comment]
Thanks @gjsjohnmurray, I will close it as a dupe of that for some alternate rendering
