### ISSUE TITLE
Publish build failed

### ISSUE THREAD

**Issue by ulugbekna** [microsoft/vscode#182280]
Build: https://dev.azure.com/monacotools/Monaco/_build/results?buildId=214395&view=logs&j=43b54640-f671-5524-8f7b-714d77229de9&s=380ab8c6-4139-55ff-15c4-fb48260f4dca&t=93e2f8ab-3488-5e8e-d7d9-978a5cf7f65f&l=1068

Changes: https://github.com/Microsoft/vscode/compare/2575777...2575777

**Comment by TylerLeonhardt** [comment]
I've seen this happen from time to time... but I'm not entirely sure why. It's almost as if our build agent drops the mooncake credentials for some reason.
