### ISSUE TITLE
Search Results: add context menu

### ISSUE THREAD

**Issue by warpdesign** [Microsoft/vscode#18225]
- VSCode Version: 1.9.0 insiders
- OS Version: Windows 10

In the VSCode explorer, right-clicking on a file shows a context menu with options like "reveal in explorer", etc...

I wish the Search panel would do the same for files that are part of the search results: right now right-clicking on files does nothing in the Search panel.

**Comment by roblourens** [comment]
Good idea. Here are the context menu options I have. I think everything in the top group would be useful, and copy path. I wouldn't want to rename, delete, or copy/paste from the search results though.

![image](https://cloud.githubusercontent.com/assets/323878/21728003/d99ea28a-d3f8-11e6-9f56-54456068c2b9.png)

**Comment by warpdesign** [comment]
I agree: top elements are all useful, file operations not so much.

**Comment by roblourens** [comment]
https://github.com/Microsoft/vscode/issues/8594
