### ISSUE TITLE
More configurable builds for C/C++

### ISSUE THREAD

**Issue by Rn86** [Microsoft/vscode#18227]
Feature Request

Using cpptool you can define configurations. Those configurations can only be used just for include paths and symbols databases. It would be nice to use those configurations in build to specify compilation flags (e.g. debug/release build). I would like to be able to change those configurations and build accordingly to specified configuration. In other words i want to be able to add compilation arguments for specific configuration only.  Now its only possible to change your build by modifying tasks.json file, which is not a big deal but still.

**Comment by sandy081** [comment]
Moved to cpp tools repository
