### ISSUE TITLE
bug report

### ISSUE THREAD

**Issue by pernlwu** [microsoft/vscode#182273]
Type: <b>Bug</b>

The first three times I responded to vscode after restarting my computer, I received no response, and a window showing "windows not responding" popped up. And Macfee antivirus(per #178962) is not installed on the computer. 
Sometimes there is a problem that the memory usage keeps growing until vscode is shut down(I used the start extension bisect command to eliminate the extension problem).

VS Code version: Code 1.78.2 (b3e4e68a0bc097f0ae7907b217c1119af9e03435, 2023-05-10T14:39:26.248Z)
OS version: Windows_NT x64 10.0.19043
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz (16 x 2496)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.73GB (7.13GB free)|
|Process Argv|--crash-reporter-id b722c478-6165-43f1-b7f2-92795bacef48|
|Screen Reader|no|
|VM|50%|
</details><details><summary>Extensions (33)</summary>

Extension|Author (truncated)|Version
---|---|---
keil-assistant|cl|1.7.0
doxdocgen|csc|1.4.0
vscode-markdownlint|Dav|0.50.0
gitlens|eam|13.6.0
gc-excelviewer|Gra|4.2.57
better-cpp-syntax|jef|1.17.2
cmake-language-support-vscode|jos|0.0.9
cortex-debug|mar|1.10.0
debug-tracker-vscode|mcu|0.0.15
memory-view|mcu|0.0.20
rtos-views|mcu|0.0.6
vscode-language-pack-zh-hans|MS-|1.78.2023051009
vscode-dotnet-runtime|ms-|1.6.0
isort|ms-|2022.8.0
python|ms-|2023.8.0
vscode-pylance|ms-|2023.5.20
jupyter|ms-|2023.4.1011241018
jupyter-keymap|ms-|1.1.0
jupyter-renderers|ms-|1.0.15
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-slideshow|ms-|0.1.5
remote-ssh|ms-|0.102.0
remote-ssh-edit|ms-|0.86.0
cmake-tools|ms-|1.14.31
cpptools|ms-|1.15.4
cpptools-extension-pack|ms-|1.3.0
makefile-tools|ms-|0.7.0
remote-explorer|ms-|0.4.0
llvm|RRe|0.1.1
markdown-preview-enhanced|shd|0.6.8
python-extended-snippets|tus|0.0.1
cmake|twx|0.0.17
markdown-all-in-one|yzh|3.5.1

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
2e4cg342:30602488
pyind779:30671433
f6dab269:30613381
pythonsymbol12:30671437
showlangstatbar:30737416
azdwalk:30721579
pythonms35:30701012
pythonfmttext:30731395
pythoncmvfstrcf:30731970
fixshowwlkth:30730052
hidesbindicator:30730055

```

</details>

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by pernlwu** [comment]
It looks like the issues are fixed, and I hope to get a release build out soon。
