### ISSUE TITLE
unit tests failure - WorkingCopyBackupTracker (native)

### ISSUE THREAD

**Issue by ulugbekna** [microsoft/vscode#182278]
Build: https://dev.azure.com/monacotools/Monaco/_build/results?buildId=214407&view=logs&j=55ac390b-ffb1-50ea-3650-525dd9a3fd80&s=a56e7651-4213-56af-9488-c25fe636c10c&t=a0dd9636-50d2-5f8a-f17f-6bcaa254d802&l=10511

Changes: https://github.com/Microsoft/vscode/compare/5860847...d1c1c8c

**Comment by bpasero** [comment]
Flaky CI, I think we had discussed to increase the timeout when running in CI, I can see to do that.
