### ISSUE TITLE
Suddenly Vs Code is opening with white and black screen

### ISSUE THREAD

**Issue by govindpasi** [microsoft/vscode#182230]
Type: <b>Performance Issue</b>

### But prior it usually starts within 3s that to without that white and black screen in initial startup.
```
Please help me to solve this issue.
```

VS Code version: Code 1.78.2 (b3e4e68a0bc097f0ae7907b217c1119af9e03435, 2023-05-10T14:39:26.248Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|12th Gen Intel(R) Core(TM) i5-1240P (16 x 2112)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.69GB (7.82GB free)|
|Process Argv|-n --crash-reporter-id 97d4fa1f-4697-48eb-8f58-cc3fbcf0ade4|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	   102	  9812	code main
    0	    51	  4340	   utility-network-service
    0	   109	  5496	extensionHost [1]
    0	    29	  5864	   crashpad-handler
    0	   153	  7052	window [1] (Visual Studio Code)
    0	    81	 10464	fileWatcher [1]
    0	    89	 11648	window [4] (Issue Reporter)
    0	   155	 20452	   gpu-process
    0	    99	 20592	shared-process
    0	    80	 19980	     ptyHost
```

</details>
<details>
<summary>Workspace Info</summary>

```
;
```

</details>
Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263cf:30335440
vscorecescf:30445987
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
282f8724:30602487
pyind779:30671433
89544117:30613380
pythonsymbol12:30671437
a9j8j154:30646983
showlangstatbar:30737416
vsctsb:30705553
azdwalk:30721579
pythonms35:30701012
pythonfmttext:30731395
pythoncmv:30731968
fixshowwlkth:30730052

```

</details>

**Comment by gjsjohnmurray** [comment]
Are you using Mcafee antivirus?

**Comment by govindpasi** [comment]
> Are you using Mcafee antivirus?

Thanks for replying it is now resolved after adding code.exe in Mcafee real-time scanning excluded files.
