### ISSUE TITLE
Bash job control error in intgrated Vscode terminal

### ISSUE THREAD

**Issue by Metwesh** [microsoft/vscode#182223]
Type: <b>Bug</b>

When starting a new instance of bash on the latest Vscode version on macosx, for some reason job control is disallowed & produces the following error:

bash: cannot set terminal process group (1502): Inappropriate ioctl for device
bash: no job control in this shell

VS Code version: Code 1.78.1 (Universal) (6a995c4f4cc2ced6e3237749973982e751cb0bf9, 2023-05-04T09:57:42.343Z)
OS version: Darwin x64 18.7.0
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5350U CPU @ 1.80GHz (4 x 1800)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|6, 3, 3|
|Memory (System)|8.00GB (2.59GB free)|
|Process Argv|-psn_0_335954 --crash-reporter-id c9b30abe-7f57-4f3b-945b-40ba5617dd60|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (70)</summary>

Extension|Author (truncated)|Version
---|---|---
codesnap|adp|1.3.4
ng-template|Ang|16.0.0
html-end-tag-labels|ant|0.11.0
vscode-intelephense-client|bme|1.9.5
simple-react-snippets|bur|1.2.7
turbo-console-log|Cha|2.9.3
npm-intellisense|chr|1.4.4
path-intellisense|chr|2.8.4
cssrem|cip|3.1.0
doxdocgen|csc|1.4.0
vscode-markdownlint|Dav|0.50.0
vscode-eslint|dba|2.4.0
docs-markdown|doc|1.0.1
docs-preview|doc|1.0.1
githistory|don|0.6.20
xml|Dot|2.5.1
es7-react-js-snippets|dsz|4.4.3
gitlens|eam|13.5.0
prettier-vscode|esb|9.12.0
vscode-firefox-debug|fir|2.9.8
code-runner|for|0.12.0
vscode-pull-request-github|Git|0.64.0
live-sass|gle|6.0.5
todo-tree|Gru|0.0.226
better-cpp-syntax|jef|1.17.2
Angular2|joh|13.0.0
cmake-language-support-vscode|jos|0.0.9
dotenv|mik|1.0.1
vscode-docker|ms-|1.25.0
vscode-dotnet-runtime|ms-|1.6.0
isort|ms-|2022.8.0
pylint|ms-|2023.4.0
python|ms-|2023.8.0
vscode-pylance|ms-|2023.5.10
jupyter|ms-|2023.4.1011241018
jupyter-keymap|ms-|1.1.0
jupyter-renderers|ms-|1.0.15
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-slideshow|ms-|0.1.5
remote-containers|ms-|0.292.0
cmake-tools|ms-|1.14.31
cpptools|ms-|1.15.4
cpptools-extension-pack|ms-|1.3.0
vscode-typescript-next|ms-|5.1.20230509
color-highlight|nau|2.5.0
autodocstring|njp|0.6.1
indent-rainbow|ode|8.3.1
material-icon-theme|PKi|4.27.0
heroku-command|pko|0.0.8
reactree|Rea|1.0.8
vscode-xml|red|0.25.0
vscode-yaml|red|1.12.2
LiveServer|rit|5.7.9
vs-code-prettier-eslint|rve|5.1.0
vscode-javascript-booster|sbu|14.0.1
vsc-quokka-statusbar|ske|1.3.6
code-spell-checker|str|2.20.4
unique-window-colors|stu|1.0.51
tabnine-vscode|Tab|3.6.46
cmake|twx|0.0.17
intellicode-api-usage-examples|Vis|0.2.7
vscodeintellicode|Vis|1.2.30
quokka-vscode|Wal|1.0.536
vscode-todo-highlight|way|1.0.5
glean|wix|5.2.2
vscode-import-cost|wix|3.3.0
php-debug|xde|1.32.1
pretty-ts-errors|yoa|0.4.1
html-css-class-completion|Zig|1.20.0
php-intellisense|zob|1.1.2

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
2e4cg342:30602488
pyind779:30671433
f6dab269:30613381
pythonsymbol12:30671437
2i9eh265:30646982
showlangstatbar:30730054
vsctsb:30705553
azdwalk:30721579
pythonms35:30701012
pythonfmttext:30731395
pythoncmvfstrcf:30731970
fixhidewlkth:30730051
showsbindicator:30730056

```

</details>

**Comment by tomaseti** [comment]
Yep I'm seeing this issue too, really annoying.

**Comment by dennischow** [comment]
Same issues here. Any idea how to get it works again like days ago?

bash: no job control in this shell

**Comment by dennischow** [comment]
Hi guys, is there any solution to fix it? bash: no job control in this shell

Version: 1.78.2
Commit: b3e4e68a0bc097f0ae7907b217c1119af9e03435
Date: 2023-05-10T14:44:45.204Z (5 days ago)
Electron: 22.5.2
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Darwin x64 17.7.0
Sandboxed: No

**Comment by safga** [comment]
Got this issue too.

bash: no job control in this shell

**Comment by ankarastrix** [comment]
> I have the same issue. It does not allow me stopping a job running in terminal with Ctrl+C.
> 
> MacOS 10.13.6.
> 
> VSCode info: Version: 1.78.2 Commit: [b3e4e68](https://github.com/microsoft/vscode/commit/b3e4e68a0bc097f0ae7907b217c1119af9e03435) Date: 2023-05-10T14:44:45.204Z (1 day ago) Electron: 22.5.2 Chromium: 108.0.5359.215 Node.js: 16.17.1 V8: 10.8.168.25-electron.0 OS: Darwin x64 17.7.0 Sandboxed: Yes

I have changed the shell to zsh and everything is working properly again.

**Comment by valentyn-dasburo** [comment]
Thank you for the workaround. `zsh` should be selected in settings - `terminal.integrated.defaultProfile.osx` on MacOS.
