### ISSUE TITLE
Bracket pair highlighting issue for double brackets in markdown

### ISSUE THREAD

**Issue by stone-zeng** [microsoft/vscode#182271]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.78.2 (Universal)
- OS Version: Darwin x64 22.5.0

Steps to Reproduce:

1. Create a markdown file with the following content:

    ```md
    [[test]]
    ```

2. The highlight is:

    <img width="179" alt="Screenshot 2023-05-12 at 15 44 46" src="https://github.com/microsoft/vscode/assets/18233088/c3c7c276-9a43-4753-9a5d-be43e6507902">

3. When setting `editor.bracketPairColorization.enabled` to `false`, then it will be correct.

**Comment by mjbvz** [comment]
I believe this is actually an issue with the markdown grammar's highlighting. Opened https://github.com/microsoft/vscode-markdown-tm-grammar/issues/146 to track this
