### ISSUE TITLE
Unable to read file 'vscode-userdata://dv.local/ROOT/USERS/spek/AppData/Code/User/settings.json

### ISSUE THREAD

**Issue by OlafvdSpek** [microsoft/vscode#182293]
Type: <b>Bug</b>

`Unable to read file 'vscode-userdata://dv.local/ROOT/USERS/spek/AppData/Code/User/settings.json`

Isn't the user data dir automatically put on the allow list?
I do have `NODE_UNC_HOST_ALLOWLIST = DV.LOCAL` in env,

```
[7704:0512/130520.436:INFO:CONSOLE(754)] "Unable to read file 'vscode-userdata://dv.local/ROOT/USERS/spek/AppData/Code/User/settings.json' (Unknown (FileSystemError): UNC host 'dv.local' access is not allowed. Please update the 'security.allowedUNCHosts' setting if you want to allow this host.)", source: vscode-file://vscode-app/c:/Users/spek/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js (754)
[7704:0512/130520.447:INFO:CONSOLE(624)] "%cTRACE color: #888 Error while resolving configuration file 'vscode-userdata://dv.local/ROOT/USERS/spek/AppData/Code/User/tasks.json': Unable to read file 'vscode-userdata://dv.local/ROOT/USERS/spek/AppData/Code/User/tasks.json' (Error: Unable to resolve nonexistent file 'vscode-userdata://dv.local/ROOT/USERS/spek/AppData/Code/User/tasks.json')", source: vscode-file://vscode-app/c:/Users/spek/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js (624)
```

VS Code version: Code 1.78.2 (b3e4e68a0bc097f0ae7907b217c1119af9e03435, 2023-05-10T14:39:26.248Z)
OS version: Windows_NT x64 10.0.19045
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 3700X 8-Core Processor              (16 x 3593)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.95GB (22.28GB free)|
|Process Argv|--verbose --crash-reporter-id 38a08b52-dec2-4734-9f3a-f6654d51d1cd|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
doxdocgen|csc|1.4.0
better-cpp-syntax|jef|1.17.2
vscode-dotnet-runtime|ms-|1.6.0
isort|ms-|2022.8.0
python|ms-|2023.8.0
vscode-pylance|ms-|2023.5.20
jupyter|ms-|2023.4.1011241018
jupyter-keymap|ms-|1.1.0
jupyter-renderers|ms-|1.0.15
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-slideshow|ms-|0.1.5
remote-containers|ms-|0.292.0
remote-ssh|ms-|0.102.0
remote-ssh-edit|ms-|0.86.0
remote-explorer|ms-|0.4.0
errorlens|use|3.11.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
vsccc:30610678
282f8724:30602487
pyind779:30671433
89544117:30613380
vscrpc:30673769
pythonsymbol12:30671437
a9j8j154:30646983
showlangstatbar:30737416
vsccsb:30705552
azdwalk:30721579
pythonms35:30701012
pythonfmttext:30731395
pythoncmvfstrcf:30731970
fixhidewlkth:30730051
showsbindicator:30730056

```

</details>

**Comment by bpasero** [comment]
We only fixed this in insiders.

Beginning with VS Code `1.78.1` accessing any UNC path (those that begin with `\\`) on Windows is blocked to mitigate a security risk that is further explained in this [Security Advisory](https://github.com/microsoft/vscode/security/advisories/GHSA-mmfh-4pv3-39hr).

Please refer to https://aka.ms/vscode-windows-unc for more information how to make your specific UNC path work again.

**Comment by OlafvdSpek** [comment]
> We only fixed this in insiders.

Will this be released later?
This is causing lots of trouble..

**Comment by bpasero** [comment]
You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by OlafvdSpek** [comment]
> You can give our preview releases a try from: https://code.visualstudio.com/insiders/

I can, but for a lot of others that are less tech savvy this is quite a road block..
