### ISSUE TITLE
Feature-Request: Ability to Login to Microsoft to Sync settings across all computers (Like in Visual Studio Pro)

### ISSUE THREAD

**Issue by CryptoJones** [Microsoft/vscode#18226]
- VSCode Version: Any
- OS Version: Any

Would like to be able to login to my Microsoft account and sync my VS Code Settings across all my installations. This is done in Visual Studio Pro.

**Comment by pavankumarkatakam** [comment]
I'm also thinking this feature like if we download new vscode and login it should sync extensions, preferences etc.

**Comment by shanalikhan** [comment]
Have you guys tried this extension
https://marketplace.visualstudio.com/items?itemName=Shan.code-settings-sync

**Comment by yfdyh000** [comment]
Duplicate of #7311.

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/2743
