### ISSUE TITLE
Select and copy text from integrated terminal output(buffer scrollback) via keyboard

### ISSUE THREAD

**Issue by valerii15298** [microsoft/vscode#182210]
It would be very useful to be able to select(and edit/copy) text in integrated terminal buffer scrollback using keyboard. For example Alacritty has [vi mode](https://github.com/alacritty/alacritty/blob/master/docs/features.md#vi-mode): , Kitty has similar [feature](https://sw.kovidgoyal.net/kitty/overview/#the-scrollback-buffer)

Would be nice at least to be able to select and copy text from integrated terminal output with keyboard, which is not possible for now :(

**Comment by meganrogge** [comment]
This is possible when you run `terminal: focus accessible buffer` now

**Comment by valerii15298** [comment]
@meganrogge thanks. It is really very useful feature. 

Is it possible to edit this output directly in Vs code editor(maybe shortcut or command for it)?
Current functionality doesn't allow to use multiple cursors or other Vs code editor features.

**Comment by valerii15298** [comment]
If anyone will look into this here is a simple shortcut to achive it:
First add this shortcut to your `keybindings.json`:
```json
{
    "key": "ctrl+alt+a",
    "command": "runCommands",
    "args": {
      "commands": [
        {
          "command": "workbench.action.terminal.selectAll",
        },
        {
          "command": "editor.action.clipboardCopyAction"
        },
        {
          "command": "workbench.action.files.newUntitledFile"
        },
        {
          "command": "editor.action.clipboardPasteAction"
        }
      ]
    }
  }
```

After that any time when in terminal press `ctrl+alt+a` to edit all terminal output in vs code newly created unsaved file.
