### ISSUE TITLE
Add autocomplete for keybindings.json

### ISSUE THREAD

**Issue by tht13** [Microsoft/vscode#1822]
It would be useful to have auto complete for the `command`and `when` fields in the keybindings.json.
I don't think this would be too hard for when as as far as I understand extensions cannot add new events. However commands may be slightly trickier as you would have to incorporate commands from extensions, but these are registered anyway so hopefully would not be a show stopper.
Thanks

**Comment by joaomoreno** [comment]
@alexandrudima fyi

**Comment by alexandrudima** [comment]
:+1: Cool request!

**Comment by tht13** [comment]
auto complete of commands is fixed in June release https://code.visualstudio.com/Updates#_editor,
is there intention to add similar functionality for the when option? if not this can be closed.

**Comment by sandy081** [comment]
I do not think there are plans to support auto complete for when contexts. Hence closing it.
