### ISSUE TITLE
jupyter notebooks end up with weird grey colour between code blocks and occasionally the blocks are hidden

### ISSUE THREAD

**Issue by Vaishnav-Varma** [microsoft/vscode#182231]
Type: <b>Bug</b>

1. Make a Jupyter notebook file and make code blocks for, say, a ML model.
2. Run the sections one by one.
3. The  code blocks irregularly appear, and the colouring changes.

VS Code version: Code 1.78.2 (b3e4e68a0bc097f0ae7907b217c1119af9e03435, 2023-05-10T14:39:26.248Z)
OS version: Windows_NT x64 10.0.19045
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 5800H with Radeon Graphics          (16 x 3194)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.35GB (5.99GB free)|
|Process Argv|--crash-reporter-id 1b86ef51-de20-45f3-9693-ef32244f4a10|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (60)</summary>

Extension|Author (truncated)|Version
---|---|---
vsc-prolog|art|0.8.23
vscode-database|baj|2.2.3
exe-runner|bra|0.2.1
path-intellisense|chr|2.8.4
c-cpp-compile-run|dan|1.0.44
vscode-markdownlint|Dav|0.50.0
vscode-eslint|dba|2.4.0
vscode-terminal-for-ubuntu|Doc|0.0.2
githistory|don|0.6.20
chatgpt-gpt4-gpt3-vscode|Eas|0.7.8
vscode-html-css|ecm|1.13.1
EditorConfig|Edi|0.16.4
copilot|Git|1.86.82
vscode-pull-request-github|Git|0.64.0
gc-excelviewer|Gra|4.2.57
haskell|has|2.2.4
discord-vscode|icr|5.8.0
language-haskell|jus|3.6.0
google-search|kam|0.0.1
vscode-line-history|lih|0.2.0
vscode-docker|ms-|1.25.0
vscode-dotnet-runtime|ms-|1.6.0
data-workspace-vscode|ms-|0.4.0
mssql|ms-|1.18.0
sql-bindings-vscode|ms-|0.3.0
sql-database-projects-vscode|ms-|0.21.0
isort|ms-|2022.8.0
python|ms-|2023.8.0
vscode-pylance|ms-|2023.5.20
jupyter|ms-|2023.4.1011241018
jupyter-keymap|ms-|1.1.0
jupyter-renderers|ms-|1.0.15
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-slideshow|ms-|0.1.5
azure-account|ms-|0.11.4
cpptools|ms-|1.15.4
cpptools-extension-pack|ms-|1.3.0
powershell|ms-|2023.5.0
remote-explorer|ms-|0.4.0
vsliveshare|ms-|1.0.5864
sqltools|mtx|0.27.1
phoityne-vscode|pho|0.0.29
material-icon-theme|PKi|4.27.0
prolog|reb|0.0.4
java|red|1.18.0
LiveServer|rit|5.7.9
openxml-explorer|ser|0.1.1
tabnine-vscode|Tab|3.6.46
pdf|tom|1.2.2
vaishnav-chatgpt|und|0.0.1
indent-one-space|use|1.0.0
vscodeintellicode|Vis|1.2.30
vscode-java-debug|vsc|0.50.0
vscode-java-dependency|vsc|0.22.0
vscode-java-pack|vsc|0.25.11
vscode-java-test|vsc|0.38.2
vscode-maven|vsc|0.41.0
JavaScriptSnippets|xab|1.8.0
commandlist|yam|1.1.0
html-css-class-completion|Zig|1.20.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
282f8724:30602487
pyind779:30671433
f6dab269:30613381
pythonsymbol12:30671437
showlangstatbar:30737416
vsctsb:30705553
azdwalk:30721579
pythonms35:30701012
pythonfmttext:30731395
fixhidewlkth:30730051
pythongtdpath:30731978

```

</details>

**Comment by Ja-Crispy** [comment]
![image](https://github.com/microsoft/vscode/assets/77791242/6df5d7ea-34ba-48e7-a097-9e0128eb4380)

This is another account of mine, I just happened to be logged into it on my browser.
Attaaching a screenshot of the issue here.

**Comment by Vaishnav-Varma** [comment]
Only temporary fix found is to copy the contents of the affected notebook to another and then run it.
This suggestion was found in a similar discussion, linked [here](https://github.com/microsoft/vscode/issues/146153).

Version: 1.79.0-insider (user setup)
Commit: 2575777b9d3cdb865d61f9f1dfaac1fea9e1bde6
Date: 2023-05-12T05:21:06.392Z
Electron: 22.5.2
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Windows_NT x64 10.0.19045
Sandboxed: Yes

**Comment by Vaishnav-Varma** [comment]
UPDATE : 

After doing what I mentioned in my last comment, all the notebooks seem to be working fine.
I'll close the issue after a day or so if it doesn't happen again.
