### ISSUE TITLE
Flutter/dart: the error message when hovering over the errored line goes away when moving the mouse to it.

### ISSUE THREAD

**Issue by AlejandroMagdaleno** [microsoft/vscode#182213]
Type: <b>Bug</b>

After running Flutter app. 

1. Break the program through an exception. 

Mine was a format exception,  with int.parse(uidController.text). 

2. Insert code from non-imported files while the program is paused with the above step. 
 I inserted
 inputFormatters: [
    FilteringTextInputFormatter.allow(RegExp(r'[b\d]+')),
  ],  
but the FilteringTextInputFormatter needed a service file import.

3. Hover the mouse over the affected error line. The error box with the quick fix option shows up. 

4. Move the mouse toward the box to click on quick fix. 

Expected Result: The error box doesn't go away and lets the mouse move to it. Would give the user a chance to mouse over the options in the error box.

Actual Result: At this point the error box goes away quickly, not giving me a chance to click on the quick fix options. 

VS Code version: Code 1.78.1 (6a995c4f4cc2ced6e3237749973982e751cb0bf9, 2023-05-04T09:48:08.683Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 5600H with Radeon Graphics          (12 x 3294)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|7.86GB (0.86GB free)|
|Process Argv|--crash-reporter-id cc99cce4-d50a-43ec-93af-1bfde77493d8|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (18)</summary>

Extension|Author (truncated)|Version
---|---|---
dart-code|Dar|3.64.0
flutter|Dar|3.64.0
vscode-html-css|ecm|1.13.1
vsc-material-theme|Equ|33.8.0
vsc-material-theme-icons|equ|2.7.5
prettier-vscode|esb|9.12.0
isort|ms-|2022.8.0
python|ms-|2023.8.0
vscode-pylance|ms-|2023.5.20
jupyter|ms-|2023.4.1011241018
jupyter-keymap|ms-|1.1.0
jupyter-renderers|ms-|1.0.15
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-slideshow|ms-|0.1.5
nodejs-snippets|piy|0.0.2
ayu|tea|1.0.5
vscode-gradle|vsc|3.12.7
JavaScriptSnippets|xab|1.8.0

(9 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
3biah626:30602489
pyind779:30671433
f6dab269:30613381
pythonsymbol12:30671437
showlangstatbar:30737416
vsccsb:30705552
azdwalk:30721579
pythonms35:30701012
j16hj152:30706079
24365598:30736109
pythonfmttext:30731395
pythoncmvfstrcf:30731970
fixshowwlkth:30730052
hidesbindicator:30730055

```

</details>

**Comment by roblourens** [comment]
Could you share a screenshot or recording? I wonder whether the error is just being layed out in the wrong place?

**Comment by AlejandroMagdaleno** [comment]
https://github.com/microsoft/vscode/assets/16804549/17684ffb-e805-40f9-a8b4-c999ce60dacd

Here is a recording. The error keeps going away when I go to hover over it.

**Comment by roblourens** [comment]
Thanks, that seems wrong. Does this happen with all hovers, or all error hovers? Or only with your steps to debug, pause, etc.

**Comment by roblourens** [comment]
Oh I can repro it, never mind

**Comment by roblourens** [comment]
@Viijay-Kr guessing this is related somehow to https://github.com/microsoft/vscode/issues/169151. If you want to investigate you could help me figure out why the error hover is being hidden on every mouse move?

**Comment by Viijay-Kr** [comment]
@AlejandroMagdaleno Thanks for reporting 👍🏽 . 

@roblourens I did some digging and learnt that the the hover configuration is not applied correctly when the debug expression is not available. 

I opened a WIP PR 

https://github.com/microsoft/vscode/pull/182555

I would like to check this clearly, this is just a naive change
