### ISSUE TITLE
Failed to Find Dependency "windows-process-tree"

### ISSUE THREAD

**Issue by filthyslider** [microsoft/vscode#182229]
Type: <b>Bug</b>

When I try to Run an Azure Functions project, I get this warning, which won't allow me to debug my project.  

VS Code version: Code 1.78.2 (b3e4e68a0bc097f0ae7907b217c1119af9e03435, 2023-05-10T14:39:26.248Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-10900X CPU @ 3.70GHz (20 x 3696)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|63.80GB (35.73GB free)|
|Process Argv|--crash-reporter-id 5b1da790-dd1d-4e53-aa9a-43345f408755|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (61)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-angular2-files|ale|1.6.4
ng-template|Ang|16.0.0
armview|ben|0.4.6
vscode-eslint|dba|2.4.0
githistory|don|0.6.20
gitlens|eam|13.5.0
EditorConfig|Edi|0.16.4
prettier-vscode|esb|9.12.0
vscode-indent-on-paste|gaz|2.4.0
copilot|Git|1.86.82
copilot-labs|Git|0.14.884
remotehub|Git|0.56.0
vscode-pull-request-github|Git|0.64.0
angular-essentials|joh|13.0.0
Angular2|joh|13.0.0
vscode-peacock|joh|4.2.2
json|Mee|0.1.2
Angular-BeastCode|Mik|10.0.3
azure-pipelines|ms-|1.208.0
azure-dev|ms-|0.5.0
vscode-azureappservice|ms-|0.24.8
vscode-azurecontainerapps|ms-|0.5.0
vscode-azurefunctions|ms-|1.10.5
vscode-azureresourcegroups|ms-|0.7.1
vscode-azurestaticwebapps|ms-|0.12.0
vscode-azurestorage|ms-|0.15.1
vscode-azurevirtualmachines|ms-|0.6.4
vscode-bicep|ms-|0.17.1
vscode-cosmosdb|ms-|0.19.3
vscode-docker|ms-|1.25.0
csharp|ms-|1.25.7
vscode-dotnet-runtime|ms-|1.6.0
vscode-edge-devtools|ms-|2.1.1
isort|ms-|2022.8.0
python|ms-|2023.8.0
vscode-pylance|ms-|2023.5.20
jupyter|ms-|2023.4.1011241018
jupyter-keymap|ms-|1.1.0
jupyter-renderers|ms-|1.0.15
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-slideshow|ms-|0.1.5
remote-containers|ms-|0.292.0
azure-account|ms-|0.11.4
azure-repos|ms-|0.32.0
azurecli|ms-|0.5.0
powershell|ms-|2023.5.0
remote-repositories|ms-|0.34.0
vscode-node-azure-pack|ms-|1.2.0
azurerm-vscode-tools|msa|0.15.10
debugger-for-edge|msj|1.0.15
angular2-inline|nat|0.0.17
angular-console|nrw|18.1.1
vscode-starlark|phg|0.3.1
material-icon-theme|PKi|4.27.0
snyk-vulnerability-scanner|sny|1.19.0
ms-teams-vscode-extension|Tea|4.2.5
vscode-pets|ton|1.22.0
intellicode-api-usage-examples|Vis|0.2.7
vscodeintellicode|Vis|1.2.30
vscode-icons|vsc|12.4.0
material-theme|zhu|3.15.8

(4 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vscaac:30438847
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
vscccc:30610679
2e4cg342:30602488
pyind779:30671433
89544117:30613380
pythonsymbol12:30671437
showlangstatbar:30737416
vsctsb:30705553
azdwalk:30721579
pythonms35:30701012
pythonfmttext:30731395
pythoncmvfstr:30731969
fixshowwlkth:30730052

```

</details>

**Comment by roblourens** [comment]
This sounds like either an issue with your code or the Azure Function extension
