### ISSUE TITLE
GIT Source Control Activation

### ISSUE THREAD

**Issue by ccarmont** [microsoft/vscode#182287]
Type: <b>Bug</b>

Hello since 1.78.2 update,
When windows PATH system variable is scanned by Git extension to detect Git installation, if UNC path are defined before Git folder, Git extension do not start and get stucked on "scanning folders for git repositories". Only solution for me was to move up git folder before my UNC path in PATH system variable. Maybe UNC could be ignored and scan could go on to detect next PATH entries.

VS Code version: Code 1.78.2 (b3e4e68a0bc097f0ae7907b217c1119af9e03435, 2023-05-10T14:39:26.248Z)
OS version: Windows_NT x64 10.0.19045
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz (8 x 3408)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.88GB (5.16GB free)|
|Process Argv|--crash-reporter-id 7e85ce54-2a84-49e2-af04-9d437ea52521|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
gitlens|eam|13.6.0
vscode-firefox-debug|fir|2.9.8
start-git-bash|McC|1.2.1
git-graph|mhu|1.30.0
vscode-language-pack-fr|MS-|1.78.2023051009
js-debug-nightly|ms-|2023.5.1117
vscode-scss-formatter|sib|2.5.0
sonarlint-vscode|Son|3.17.0
sass-indented|syl|1.8.26

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
vscccc:30610679
3biah626:30602489
pyind779:30671433
89544117:30613380
vscrpc:30673769
pythonsymbol12:30671437
showlangstatbar:30737416
vsccsb:30705552
azdwalk:30721579
pythonms35:30701012
j16hj152:30706079
pythonfmttext:30731395
pythoncmvfstrcf:30731970
fixhidewlkth:30730051
pythongtdpath:30731978

```

</details>

**Comment by lszomoru** [comment]
@ccarmont, could you please share the PATH system variable when the git extension is not working as expected along with the value of the PATH system variable when it does. Please feel free to obfuscate any folder names as you see fit. Thanks!

**Comment by ccarmont** [comment]
When  UNC path  (%JEEPE_HOME% in screenshots) is placed before GIT folder in PATH system variable , VSC Git extension init fails.  Only way to succeed is to move up GIT folder above %JEEPE_HOME% entry.
![2023-06-06 11_34_16-Modifier la variable d'environnement](https://github.com/microsoft/vscode/assets/34480048/681dbade-aae8-4ad1-9531-4cc912d345e2)
![2023-06-06 11_35_47-Variables d’environnement](https://github.com/microsoft/vscode/assets/34480048/0378f6d9-3940-420b-89f7-2439a8b650cf)

**Comment by lszomoru** [comment]
@ccarmont, thanks for the additional information. I will look into this and get back to you.

**Comment by lszomoru** [comment]
@ccarmont, the latest Insides release (1.83) is using an updated dependency that should have this issue resolved. Could you please switch back the order of the PATH environment variable, download the latest Insiders release and verify that indeed the issue has been resolved? Thanks!
