### ISSUE TITLE
Setting allowed UNC hosts fails. 

### ISSUE THREAD

**Issue by jmagosta** [microsoft/vscode#182221]
Type: <b>Bug</b>

VS code unable to write file to UNC host

I get this warning:
 
![image](https://github.com/microsoft/vscode/assets/87355/05b5cc03-935b-4a17-813a-e92d3d18bbf2)

So I change the security setting:

![image](https://github.com/microsoft/vscode/assets/87355/5d22d018-969e-4c95-ad72-2c6ef9c2c9e2)

 
This did not clear the error.  The file is still not writable. 

VS Code version: Code 1.78.1 (6a995c4f4cc2ced6e3237749973982e751cb0bf9, 2023-05-04T09:48:08.683Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz (8 x 2995)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|47.71GB (28.66GB free)|
|Process Argv|--crash-reporter-id b075abe4-909f-4851-8db8-f53aa02e8181 --crash-reporter-id b075abe4-909f-4851-8db8-f53aa02e8181 --crash-reporter-id b075abe4-909f-4851-8db8-f53aa02e8181|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (33)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-sql-formatter|adp|1.4.4
project-manager|ale|12.7.0
gitignore|cod|0.9.0
databricks|dat|0.3.13
git-extension-pack|don|0.1.3
githistory|don|0.6.20
gitlens|eam|13.5.0
vsc-python-indent|Kev|1.18.0
json|Mee|0.1.2
diff-merge|mos|0.7.0
csharp|ms-|1.25.7
isort|ms-|2022.8.0
python|ms-|2023.8.0
vscode-pylance|ms-|2023.5.20
jupyter|ms-|2023.4.1011241018
jupyter-keymap|ms-|1.1.0
jupyter-renderers|ms-|1.0.15
vscode-ai|ms-|0.32.2
vscode-ai-remote|ms-|0.30.0
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-slideshow|ms-|0.1.5
remote-wsl|ms-|0.78.4
azure-account|ms-|0.11.4
powershell|ms-|2023.5.0
wordcount|ms-|0.1.0
quarto|qua|1.85.0
r|REd|2.8.0
pdf|tom|1.2.2
vim|vsc|1.25.2
jinja|who|0.0.8
markdown-all-in-one|yzh|3.5.1
json|Zai|2.0.2
vscode-open-in-github|ziy|1.3.6

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
vscccc:30610679
2e4cg342:30602488
pyind779:30671433
f6dab269:30613381
pythonsymbol12:30671437
showlangstatbar:30737416
vsccsb:30705552
azdwalk:30721579
pythonms35:30701012
57b77579:30736110
pythonfmttext:30731395
fixhidewlkth:30730051
showsbindicator:30730056
pythongtdpathcf:30731979

```

</details>

**Comment by bpasero** [comment]
Leave out the `\` and keep just the host name.
