### ISSUE TITLE
restart after update，exception in macos

### ISSUE THREAD

**Issue by zileyuan** [microsoft/vscode#182258]
Type: <b>Bug</b>

vscode macos version，restart after update，window lost caption title bar，can't max、min and fullscreen functions， also can't close window，and also can't quit vscode，must kill process

VS Code version: Code 1.78.2 (b3e4e68a0bc097f0ae7907b217c1119af9e03435, 2023-05-10T15:00:40.428Z)
OS version: Darwin arm64 22.4.0
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M2 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|6, 3, 3|
|Memory (System)|16.00GB (0.08GB free)|
|Process Argv|--crash-reporter-id aeade9be-d3e2-4070-ab12-dfee8eaedabb|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (93)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|13.3.1
project-manager|ale|12.7.0
stm32-for-vscode|bmd|3.2.5
better-toml|bun|0.3.2
npm-intellisense|chr|1.4.4
path-intellisense|chr|2.8.4
doxdocgen|csc|1.4.0
vscode-office|cwe|3.1.4
arm|dan|1.7.4
dart-code|Dar|3.64.0
flutter|Dar|3.64.0
vscode-eslint|dba|2.4.0
python-environment-manager|don|1.0.4
rust-syntax|dus|0.6.1
vscode-html-css|ecm|1.13.1
EditorConfig|Edi|0.16.4
prettier-vscode|esb|9.12.0
esp-idf-extension|esp|1.6.2
auto-close-tag|for|0.5.14
godot-tools|gee|1.3.1
vscode-github-actions|git|0.25.7
go|gol|0.38.0
vscode-drawio|hed|1.6.6
vscode-htmlhint|HTM|1.0.4
rest-client|hum|0.25.1
yuml|Jai|3.5.1
plantuml|jeb|2.17.5
better-cpp-syntax|jef|1.17.2
svg|joc|1.5.2
svn-scm|joh|2.15.7
cmake-language-support-vscode|jos|0.0.9
cortex-debug|mar|1.10.0
debug-tracker-vscode|mcu|0.0.15
memory-view|mcu|0.0.20
rtos-views|mcu|0.0.6
git-graph|mhu|1.30.0
diff-merge|mos|0.7.0
csharp|ms-|1.25.7
vscode-dotnet-runtime|ms-|1.6.0
vscode-kubernetes-tools|ms-|1.3.11
isort|ms-|2022.8.0
python|ms-|2023.8.0
vscode-pylance|ms-|2023.5.20
jupyter|ms-|2023.4.1011241018
jupyter-keymap|ms-|1.1.0
jupyter-renderers|ms-|1.0.15
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-slideshow|ms-|0.1.5
remote-containers|ms-|0.292.0
remote-ssh|ms-|0.102.0
remote-ssh-edit|ms-|0.86.0
remote-wsl|ms-|0.78.4
cmake-tools|ms-|1.14.31
cpptools|ms-|1.15.4
hexeditor|ms-|1.9.11
mono-debug|ms-|0.16.3
remote-explorer|ms-|0.4.0
godot-csharp-vscode|nei|0.2.1
vscode-extension-auto-import|Nuc|1.4.3
rust-and-friends|nyx|1.0.0
vetur|oct|0.37.3
platformio-ide|pla|3.1.1
minapp-vscode|qiu|2.4.10
java|red|1.18.0
vscode-commons|red|0.0.6
vscode-xml|red|0.25.0
vscode-yaml|red|1.12.2
git-commit-plugin|red|1.1.2
LiveServer|rit|5.7.9
rust-analyzer|rus|0.3.1506
crates|ser|0.5.11
markdown-preview-enhanced|shd|0.6.8
rust-pack|Swe|0.3.3
even-better-toml|tam|0.19.0
tauri-vscode|tau|0.2.6
cmake|twx|0.0.17
vscode-lldb|vad|1.9.1
intellicode-api-usage-examples|Vis|0.2.7
vscodeintellicode|Vis|1.2.30
vscode-boot-dev-pack|vmw|0.2.1
vscode-spring-boot|vmw|1.46.0
vscode-gradle|vsc|3.12.7
vscode-java-debug|vsc|0.50.0
vscode-java-dependency|vsc|0.22.0
vscode-java-pack|vsc|0.25.11
vscode-java-test|vsc|0.38.2
vscode-lombok|vsc|1.1.0
vscode-maven|vsc|0.41.0
vscode-spring-boot-dashboard|vsc|0.13.0
vscode-spring-initializr|vsc|0.11.2
vscode-icons|vsc|12.4.0
volar|Vue|1.6.4
vscode-proto3|zxh|0.5.5

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyonecf:30548226
vscccc:30610679
3biah626:30602489
pyind779:30671433
f6dab269:30613381
pythonsymbol12:30671437
showlangstatbar:30737416
vsccsb:30705552
azdwalk:30721579
pythonms35:30701012
pythonfmttext:30731395
pythoncmvfstrcf:30731970
fixhidewlkth:30730051
hidesbindicator:30730055
pythongtdpathcf:30731979

```

</details>

**Comment by deepak1556** [comment]
Merging to https://github.com/microsoft/vscode/issues/161586
