### ISSUE TITLE
Debug is hiting twice on install mongocsharpdriver

### ISSUE THREAD

**Issue by eduardoguilarducci** [Microsoft/vscode#18220]
- VSCode Version: 1.8.1 (1.8.1)
- OS Version: macOS Sierra 10.12.2 (16C67)
- mongocsharpdriver: 2.4.1
Steps to Reproduce:

1. Create new WebAPI project (using yeoman) 
2. yo aspnet 
3. Select WebAPI project
4. Open project in Visual Studio Code (go to folder on terminal "code ."
5. Configure debug
6. Try debug some method (will hit only once)
7. Add mongocsharpdriver dependency on project.json
8. Try debug some method (will hit twice) - only on firt "call"

**Comment by sandy081** [comment]
Moved to Omnisharp vscode repo.
