### ISSUE TITLE
Cucumber plugin (https://cucumber.io/) broken since VSCode 1.78

### ISSUE THREAD

**Issue by stmcarryg** [microsoft/vscode#182274]
Does this issue occur when all extensions are disabled?: Yes/No

Bug

- VS Code Version: 1.78, 1.78.2
- OS Version: Win1021H2

Steps to Reproduce:

1. Edit a *.feature file
Then some error popups appear:

- Cucumber Language Server client: couldn't create connection to server.
- Server initialization failed
- Request initialize failed with message: abort(Assertion fai...

And output is:
[Error - 10:02:05 AM] Server initialization failed.
  Message: Request initialize failed with message: abort(Assertion failed: bad export type for `tree_sitter_c_sharp_external_scanner_create`: undefined). Build with -s ASSERTIONS=1 for more info.
  Code: -32603 
[Error - 10:02:05 AM] Cucumber Language Server client: couldn't create connection to server.
  Message: Request initialize failed with message: abort(Assertion failed: bad export type for `tree_sitter_c_sharp_external_scanner_create`: undefined). Build with -s ASSERTIONS=1 for more info.
  Code: -32603

**Comment by gjsjohnmurray** [comment]
Have you raised the issue with the author of the extension yet?

**Comment by stmcarryg** [comment]
Hi,
Apparently someone else did: https://github.com/cucumber/vscode/issues/155
It seems to confirm the issue started with VSCode 1.78.
Thank-you,
Best regards.

**Comment by stmcarryg** [comment]
Hi,
Looking at #182196 I can't see the connection between those issues. Nothing seems to match.
Are you sure it's a duplicate?

**Comment by gjsjohnmurray** [comment]
@stmcarryg the extension author will need to investigate. If they think the issue is caused by VS Code they should raise an issue here and provide technical details.

**Comment by stmcarryg** [comment]
Ok but what is the connection with #182196 ???

**Comment by stmcarryg** [comment]
Ah Ok!
I understand better now.
Thank-you for the update.
