### ISSUE TITLE
Addition of Multiple debug windows in single vscode instance in Multi Core Debugging

### ISSUE THREAD

**Issue by asitsahoo351** [microsoft/vscode#182203]
In Multicore debugging, opening a new vscode debug window inside the same vscode instance with the same context as the previous one would help in debugging the application in two separate independent Sessions. 

Currently, it is not supported to do multiple debug sessions in the same vscode instance. Using multiple debug windows would help in debugging multi-core applications with two separate Sessions independently in the same vscode instance.

**Comment by roblourens** [comment]
Can you explain what you are referring to by "debug window"?

**Comment by roblourens** [comment]
We can't practically support this with the way Electron works. We have https://github.com/microsoft/vscode/issues/10121 for multiple windows for the same vscode session.

I probably wouldn't want to do this feature anyway, I try to make it easy to manage multiple debug sessions within one window.
