### ISSUE TITLE
Support Bash for Windows as a first class citizen

### ISSUE THREAD

**Issue by jonomacd** [Microsoft/vscode#18222]
If VS code properly supported bash on windows it will make windows a viable machine to actually buy as a developer.   

By proper support I mean that extensions (like the golang extension for example) shell out to bash not to windows terminal.  Environment variables are respected from bash. Debugging works via bash, git works via bash, etc. Basically nothing goes through the windows terminal at all and every command is done via bash.  

This would likely make me buy a windows machine.

**Comment by whitecolor** [comment]
Don't worry sooner or later lunux will become a basis for windows os. Currently that all is still half-measures.

**Comment by Tyriar** [comment]
We have some support for Bash for Windows in the integrated terminal and working on better support (https://github.com/Microsoft/vscode/issues/10163 https://github.com/Microsoft/vscode/issues/13625). With the terminal API, extensions are free to launch whatever shell they desire, with the default being whatever the user has configured (initially cmd.exe soon to be powershell https://github.com/Microsoft/vscode/issues/16838).

I'm not sure why you would care about what debugging and git uses as it's all behind the scenes.

Bash for Windows still has so many problems so it would be irresponsible to do something like this by default, and unexpected for the many Windows developers that don't know anything about bash.

If this is not your cup of tea, feel free to stick to your current OS as we have first class support for macOS and Linux too :sparkles:
