### ISSUE TITLE
Cycle through VS Code windows with Mac's native quick switch

### ISSUE THREAD

**Issue by nfiacco** [microsoft/vscode#182204]
Macs allow you to switch between windows with CMD+Tab, and I would like to be able to use this to cycle between VS Code windows as well. Right now I have VS Code installed twice under different names but it's kind of a hack and has some issues.

![image](https://github.com/microsoft/vscode/assets/9993537/dc63f044-3711-4406-a4e4-0366c33d9f35)

**Comment by deepak1556** [comment]
This is a limitation in the runtime we cannot workaround. You can use arrow keys with `Cmd + Tab` to cycle between windows of an application.
