### ISSUE TITLE
Disable specific code languages from appearing in the Language Mode menu

### ISSUE THREAD

**Issue by mehas** [Microsoft/vscode#18224]
The Language Mode menu is very long and contains many languages I never use:

![lm snip_20170106101554](https://cloud.githubusercontent.com/assets/389970/21722116/493708a8-d3f9-11e6-920d-d5c5950c76cd.png)

I would like to be able to disable unused languages. In ST3, this is achieved [by disabling the packages associated with each language](http://superuser.com/questions/680477/how-to-shorten-list-of-syntax-options-in-sublime-text#comment868788_684686).

**Comment by sandy081** [comment]
@mehas You can also disabled the extension associated with the language which will filter the languages.

**Comment by mehas** [comment]
thank you @sandy081,  but for most of those languages there are no corresponding extensions installed.

For example, the list I'm shown when I select "show installed extensions" does no contain `Batch`, `C`, or `C++`.

![installed extensions snip_20170109101104](https://cloud.githubusercontent.com/assets/389970/21771126/25d3ee5a-d654-11e6-8ff3-f9d86f99ebf8.png)

**Comment by sandy081** [comment]
@mehas Right, that's because these languages come from VS Code in-built extensions. We have a feature request to also show / manage in-built extensions: https://github.com/Microsoft/vscode/issues/17068

Otherwise let us know if you are able to disable extensions other languages?

**Comment by mehas** [comment]
@sandy081 Thank you, that's what I am looking for, the ability to disable built-in extensions (such as `C++`, etc). I will wait for an update to that feature.

To answer your question: disabling extensions that are not built-in does successfully remove them from the Language Mode menu. For example, disabling the [Twig extension](https://marketplace.visualstudio.com/items?itemName=whatwedo.twig) remove the `HTML (Twig)` entry from the menu's list.

**Comment by sandy081** [comment]
Cool. Thanks for updating. Closing this as a dup of #17068
