### ISSUE TITLE
Can code.cmd have higher precedence on the PATH than code (the shell script)?

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#18230]
See discussion for more context: https://twitter.com/Nick_Craver/status/817190115491647489

Steps to Reproduce:

1. Open windows explorer to some directory
2. Focus address bar and type "code ."
3. This will run "code ." with the current working directory set to explorer's current folder

However this results in an application picker since `code.sh` has its extension removed during packaging so it's simply `code`, so it takes precedence over `code.cmd` and Windows doesn't know how to open code(.sh) the shell script. `code.cmd .` works fine, so right now it's possible to do this, just much less discoverable `code.cmd .`

If the shell script is removed from the PATH then `code .` works fine as the command resolves to `code.cmd`.

**Comment by eteeselink** [comment]
This is a great idea, but afaik Windows has no way to remove a single file from PATH; the PATH contains directories, not files.

I guess that even on windows, you'd want to have the `code` sh script available, for example for starting Code from a WSL prompt (which I assume just works in recent Insider builds).

The only approach I can come up with is having multiple `bin` folders and ensuring that they get added to the PATH in the appropriate order. That seems like a pretty heavy approach for what's admittedly a niche use case.

Still, I like this niche use case. Any more ideas? :-)

**Comment by Tyriar** [comment]
Yes the sh script is for bash on windows (mingw, WSL, etc.). I considered multiple bin folders as an option. There is also renaming code to code.sh which will probably also fix the issue, but then it would be `code.sh` in bash (without an alias).

**Comment by joaomoreno** [comment]
Double PATH directories sounds odd. Renaming too.

I wonder if it's possible to have a single file for both...

**Comment by eteeselink** [comment]
Full-on bikeshedding here, but hey, it's fun :-)

The thing that's awkward to me is that right now, usage seems to be *optimized* for WSL. I really like WSL but I think we can assume that more people use Cmd or PowerShell than WSL. 

In a way, this feels more like a WSL limitation than a VS Code problem. Maybe WSL needs a way for WSL-aware apps to tell it to add things to the PATH that aren't there in "normal" windows. Like some WSLPATH env variable that gets prepended to PATH when WSL starts. I assume that Code isn't the only cross-platform program with this issue. 

Until then, I think it makes most sense to rename `code` back to `code.sh` and be done with it.

It looks like more people are struggling with this: https://github.com/Microsoft/BashOnWindows/issues/1493

**Comment by joaomoreno** [comment]
To keep the number of issues in our inbox on a manageable level, we're closing issues that have been on the backlog for a long time but haven't gained traction: We look at the number of votes the issue has received and the number of duplicates issues filed.

Thanks for your understanding. Happy coding!
