### ISSUE TITLE
Pressing PageUp in search panel causes layout to shift

### ISSUE THREAD

**Issue by brawaru** [microsoft/vscode#182308]
Type: <b>Bug</b>

1. Go to search panel
2. Type anything into search field
3. Press Page Up (sometimes it's Page Down)

After that the layout shifts and hides the line indicating the current tab, which is annoying. You need to resize the window for layout to shift back, which fixes the problem.

https://github.com/microsoft/vscode/assets/10401817/f37276f4-5d42-4694-a463-6f84a950209c

VS Code version: Code 1.78.2 (b3e4e68a0bc097f0ae7907b217c1119af9e03435, 2023-05-10T14:39:26.248Z)
OS version: Windows_NT x64 10.0.19043
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4440 CPU @ 3.10GHz (4 x 3093)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|11.95GB (3.80GB free)|
|Process Argv|. --crash-reporter-id 00f2bb44-44e6-48df-99e8-c8d250a1afbb|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-language-pack-de|MS-|1.78.2023051009

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes516:30244333
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
vscccc:30610679
3biah626:30602489
pyind779:30671433
f6dab269:30613381
pythonsymbol12:30671437
a9j8j154:30646983
showlangstatbar:30737416
azdwalk:30721579
pythonms35:30701012
pythonfmttext:30731395
pythoncmvfstrcf:30731970
fixhidewlkth:30730051
hidesbindicator:30730055

```

</details>

**Comment by franciscacarneiro** [comment]
Hello, I am a Computer Science student working on an open source project and I would like to contribute to this issue. Would it be possible for it to be attributed to me?
Thank you.

**Comment by andreamah** [comment]
> Hello, I am a Computer Science student working on an open source project and I would like to contribute to this issue. Would it be possible for it to be attributed to me? Thank you.

You can just start working on it :) I'm not too sure why this happens, so you can always try and investigate that first- from there, we can talk about a good fix!

**Comment by franciscacarneiro** [comment]
Hello, I have created a solution that I believe fixes this bug! Is it okay to create a pull request?
Thank you.
