### ISSUE TITLE
Integrated terminal should use up more of available space

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#18237]
![image](https://cloud.githubusercontent.com/assets/2193314/21729278/46168904-d3ff-11e6-94bc-bf0902d0df0f.png)

Related: https://github.com/Microsoft/vscode/issues/14479

**Comment by Tyriar** [comment]
To verifier: Please test in Windows and Mac

**Comment by ramya-rao-a** [comment]
@Tyriar I don't see any difference between the stable and insiders ...

**Comment by Tyriar** [comment]
@ramya-rao-a it should be more obvious when you make the window really wide and select text in the terminal. Basically it should fit as many rows/columns as possible in the panel excluding the padding on the left and right.

**Comment by dbaeumer** [comment]
I see a difference under Windows:

![capture](https://cloud.githubusercontent.com/assets/1931590/22347722/4f9edb74-e409-11e6-863b-4d70fbef5b26.png)
