### ISSUE TITLE
Broken fonts of hotkeys text on main page

### ISSUE THREAD

**Issue by koteyur** [microsoft/vscode#182350]
Type: <b>Bug</b>

1. Fedora 38, VSCode 1.78.2
2. Open VSCode, close welcome page if exists.

Expected result:
Hotkeys text (Show all Commands, Open File, Open Folder, Open Recent) looks ok.

Actual result:
Some text is broken, looks like corrupted. Characters are visible but with some weird artifacts:
![image](https://github.com/microsoft/vscode/assets/4014972/f20025fa-f361-472e-b016-bc44f85dff1a)

Notes:
Tried on two laptops with and without NVIDIA graphic card. Both Wayland and x11. Other text in VSCode is ok, at least I haven't noticed any other issues.

VS Code version: Code 1.78.2 (b3e4e68a0bc097f0ae7907b217c1119af9e03435, 2023-05-10T14:47:05.613Z)
OS version: Linux x64 6.2.14-300.fc38.x86_64
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz (8 x 1140)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|1, 0, 0|
|Memory (System)|15.32GB (11.43GB free)|
|Process Argv|--unity-launch --crash-reporter-id d8c6362a-492b-4462-bb36-f358d5b8fbb3|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|gnome|
|XDG_CURRENT_DESKTOP|GNOME|
|XDG_SESSION_DESKTOP|gnome|
|XDG_SESSION_TYPE|wayland|
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
vscccc:30610679
282f8724:30602487
pyind779:30671433
89544117:30613380
pythonsymbol12:30671437
showlangstatbar:30737416
vsccsb:30705552
azdwalk:30721579
pythonms35:30701012
a2ce3375:30706076
ecj1e332:30736112
pythonfmttext:30731395
fixshowwlkth:30730052
pythongtdpathcf:30739705

```

</details>

**Comment by roblourens** [comment]
Does it work if you start vscode with `--disable-gpu`?

**Comment by koteyur** [comment]
With the flag the problem disappear, thanks!
