### ISSUE TITLE
Contributed icon in JS debug terminal stopped working

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#182303]
See https://github.com/microsoft/vscode-js-debug/issues/975#issuecomment-1544573154

I can reproduce:

![image](https://github.com/microsoft/vscode/assets/2193314/71830fcc-f8bc-45c3-ae63-cee1f562a85c)

**Comment by tisilent** [comment]
I want to try.

**Comment by Tyriar** [comment]
@tisilent sure! This is where the profile info is pulled in:

https://github.com/microsoft/vscode/blob/b725a17a109465037c077d35e89ffaee4b99cf2f/src/vs/workbench/contrib/terminal/common/terminalExtensionPoints.ts#L23-L50
