### ISSUE TITLE
Media Preview does not support files mith multiple extensions e.g. image.png.au

### ISSUE THREAD

**Issue by c0rp3n** [microsoft/vscode#182395]
Type: <b>Bug</b>

1. Open a image e.g. image.png
2. Rename image to image.png.au or some other extension
3. Open image.png.au, VScode tries to open this as a binary file rather than a image.

It would be useful if the extension could be infered from the first extension in the path or the user could override the derived mime type from the filename.

VS Code version: Code 1.78.2 (b3e4e68a0bc097f0ae7907b217c1119af9e03435, 2023-05-10T14:39:26.248Z)
OS version: Windows_NT x64 10.0.19044
Modes:
Sandboxed: No

<details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vscaac:30438847
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
3biah626:30602489
pyind779:30671433
89544117:30613380
vscrp:30673768
pythonsymbol12:30671437
2i9eh265:30646982
showlangstatbar:30737416
vsctsb:30705553
azdwalk:30721579
pythonms35:30701012
pythonfmttext:30731395
fixhidewlkth:30730051
hidesbindicator:30730055
pythongtdpathcf:30739705

```

</details>

**Comment by YokasCarbon** [comment]
dasdcasdcasdc

**Comment by YokasCarbon** [comment]
erterherthe

**Comment by YokasCarbon** [comment]
sdfvsdfv

**Comment by IllusionMH** [comment]
Which system would treat this as `.png`?
You can try custom `files.associations` for this custom setup, but it's usually other way around - `.au.png` if it should be universally opened as image

**Comment by c0rp3n** [comment]
The decision to use `*.something.au` etc was made over a decade ago and is not something practical to change in our test suites.
It would be the built-in media-preview extension as far as I am aware, I am not familiar with the VScode codebase.

The following file associations does not seem to work:
```json
"files.associations": {
    "*.png.au": "image/png"
}
```

Trying to just match on `*.au` also does not work and would not be correct for our test suites.

**Comment by mjbvz** [comment]
@c0rp3n The setting you want is `workbench.editorAssociations`:

```json
"workbench.editorAssociations": {
  "*.png.au": "imagePreview.previewEditor"
}
```
