### ISSUE TITLE
Terminal bash shell has job control disabled

### ISSUE THREAD

**Issue by gizmola** [microsoft/vscode#182335]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version:  1.78.2
- OS Version: OSX 10.14.6

```
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin18)
Copyright (C) 2007 Free Software Foundation, Inc.
```

```
Version: 1.78.2
Commit: b3e4e68a0bc097f0ae7907b217c1119af9e03435
Date: 2023-05-10T14:44:45.204Z (2 days ago)
Electron: 22.5.2
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Darwin x64 18.7.0
Sandboxed: Yes
```

Steps to Reproduce:

1.  start vscode with "code --disable-extensions" 
2.  Open bash terminal

Message displayed:

**bash: no job control in this shell**

- Does not happen using OSX Terminal
- No changes made to OS environment/packages etc.  Seems to be new in VSCode
- Discovered [at least one other user reporting this issue on SO](https://stackoverflow.com/questions/76215332/vscode-integrated-terminal-will-not-allow-job-control-for-some-reason)
- In that thread, user stated, that rollback to 1.77.3 does not have issue.

**Comment by Hamzashikh** [comment]
استطيع حل المشكلة

**Comment by dennischow** [comment]
I also have issues "bash: no job control in this shell" after the VS Code auto updated in 5 days ago (1.78.2). I have no idea how get it works again.

**Comment by gizmola** [comment]
> I also have issues "bash: no job control in this shell" after the VS Code auto updated in 5 days ago (1.78.2). I have no idea how get it works again.

The issue was closed because it has already been fixed in the next release.  You can issue a `set -m` in your bash shell to turn on job control manually while you wait for the next release, or you can download and install the vscode insiders release, where the fix should have already been made.

**Comment by hypo1986** [comment]
vscode insiders release 也是不行

**Comment by kgdo** [comment]
> > I also have issues "bash: no job control in this shell" after the VS Code auto updated in 5 days ago (1.78.2). I have no idea how get it works again.
> 
> The issue was closed because it has already been fixed in the next release. You can issue a `set -m` in your bash shell to turn on job control manually while you wait for the next release, or you can download and install the vscode insiders release, where the fix should have already been made.

Hello I am having this issue and I have downloaded the vscode insiders release. Still at the top of each new  terminal "bash: no job control in this shell" and ctrl c will not work. I have also tried set -m to no avail either. Any help greatly appreciated
