### ISSUE TITLE
unable to debug vs code unit tests

### ISSUE THREAD

**Issue by amunger** [microsoft/vscode#182341]
latest version of insiders

1. open a unit test file, e.g. `untitledFileWorkingCopyManager.ts`
2. set a breakpoint in a unit test
3. `debug unit tests current file` or right click on the test indicator, debug test
🐛 breakpoint is not hit, test completes

Might only be happening for me, let me know how to gather any necessary logs

**Comment by esnyder1** [comment]
I am also seeing this issue after updating to 1.78. Was able to debug unit tests this morning, as soon as the update occurred the same tests will run but no breakpoints are hit.

**Comment by amunger** [comment]
after rebooting I can hit breakpoints, so something was likely just blocking the debug port in my case

**Comment by esnyder1** [comment]
For me, it looks like the issue was that `Auto Attach: Always` was not attaching. I tried rebooting, downgrading, and upgrading back to 1.78 and one of those steps fixed it.

**Comment by Michael-Zhang-Xian-Sen** [comment]
I restarted my computer and it worked fine.

**Comment by jrieken** [comment]
These are my steps

* debug a test
* quickly debug the test again
* :bug: the test runs but isn't debugged, a while after a connect error shows. If I want for long between debugs it might work

https://github.com/microsoft/vscode/assets/1794099/f6b22cec-1632-4b39-89b5-1770d88d6db3

**Comment by jrieken** [comment]
It's now a random port but I can still not debug unit tests

<img width="1490" alt="Screenshot 2023-12-19 at 11 30 12" src="https://github.com/microsoft/vscode/assets/1794099/590c423a-389f-4eba-9470-19b36505a3ee">

**Comment by connor4312** [comment]
ah, looks like that got broken in our move away from optimist
