### ISSUE TITLE
Show source name in callstack even when path is provided

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#18234]
For https://github.com/Microsoft/vscode-chrome-debug-core/issues/150

**Comment by isidorn** [comment]
This is fine by me, but not sure if it is contradicting with @weinand comment [here](https://github.com/Microsoft/vscode/issues/16913#issuecomment-270666642)

We should just come to a consensus, what has priority `name` or the `path`?

**Comment by weinand** [comment]
@isidorn yes, 'name' has priority over 'path' for the callstack 'name' (shown on the right).  And 'path' has priority over 'name' for the callstack 'path' (shown on hover).
