### ISSUE TITLE
Visual Studio Startup is slow

### ISSUE THREAD

**Issue by Sameer-Ahmed-S** [microsoft/vscode#182384]
Performance of  visual studio startup is slow . Here the details  of my startup process
## System Info

* Code: 1.78.2 (b3e4e68a0bc097f0ae7907b217c1119af9e03435)
* OS: win32(10.0.22621)
* CPUs: Intel(R) Core(TM) i7-10875H CPU @ 2.30GHz(16 x 2304)
* Memory(System): 15.88 GB(8.04GB free)
* Memory(Process): 187.90 MB working set(152.63MB private, 1.09MB shared)
* VM(likelihood): 0%
* Initial Startup: true
* Has 0 other windows
* Screen Reader Active: false
* Empty Workspace: true

Here are the output of Startup performance of Visual studio code for your reference.
[https://gist.github.com/Sameer-Ahmed-S/e80d9ef9dc631a8f555c65368d29fe16](url)

**Comment by gjsjohnmurray** [comment]
If you are using Mcafee antivirus please see #178962

**Comment by Sameer-Ahmed-S** [comment]
Thank you @gjsjohnmurray for quick response. I went thru this   #178962   issues. It did resolved the issue. Appreciated !!!
