### ISSUE TITLE
multi-line lua comments never ends, unless type in extra - 

### ISSUE THREAD

**Issue by Please-Pick-a-Name** [microsoft/vscode#182375]
Type: <b>Bug</b>

when using multi-line comments in lua, everything behind the comment will be treated as comment despite the comment was closed off properly:
```lua
--[[ if foo then
	bar=nil
end ]]
bar = foo
```
the bar = foo line should not be consider as a part of the comment
but somehow by changing it to:
```lua
--[[ if foo then
	bar=nil
end -]]
bar = foo
```
the bar = foo line was nolonger considered as a part of the comment
![image](https://github.com/microsoft/vscode/assets/81009804/8da0dc8e-20ba-464a-b906-818a9364d8c9)

VS Code version: Code - Insiders 1.79.0-insider (2575777b9d3cdb865d61f9f1dfaac1fea9e1bde6, 2023-05-12T05:21:06.392Z)
OS version: Windows_NT x64 10.0.19044
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-9300H CPU @ 2.40GHz (8 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|7.85GB (1.39GB free)|
|Process Argv|C:\\Users\\Name\\AppData\\Local\\Temp\\Rar$DIa8756.1081\\pickup_brakes_ceramic.jbeam --crash-reporter-id f2d3adf6-7801-406a-9822-4a02de2d55a3|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-language-pack-zh-hans|MS-|1.78.2023051009

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythontb:30258533
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscod805cf:30301675
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30404738
cppdebug:30492333
vsclangdf:30492506
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30618038
pylantcb52:30590116
pyind779:30611226
pythonsymbol12:30651887
a9j8j154:30646983
showlangstatbar:30737417
azdwalk:30721579
pythonms35:30671666
pythonfmttext:30716741
pythoncmvfstr:30726892
fixhidewlkth:30724384
showsbindicator:30724477
pythongtdpath:30726887

```

</details>

**Comment by Please-Pick-a-Name** [comment]
after accidental testing, if i were to do the multi-line comment like this, where theres nothing in front of it, it will color the code properly aswell (having - in front of it is also fine)
![image](https://github.com/microsoft/vscode/assets/81009804/be37688e-3fa9-4895-904e-5f9f25c0f9b6)
![image](https://github.com/microsoft/vscode/assets/81009804/f0a11704-c17f-4b95-ae35-c67959906ed4)
![image](https://github.com/microsoft/vscode/assets/81009804/b3dd5a23-a138-4487-be3f-02916ea931f7)
`lua
--[[ if foo then
	bar=nil
end 
]]
bar = foo
`

**Comment by Please-Pick-a-Name** [comment]
issue persist on the newest insider update

**Comment by alexr00** [comment]
Thanks for all the examples! I've moved the issue to the repo that we pull our lua syntax highlighting grammar from: https://github.com/LuaLS/lua.tmbundle/issues/16
