### ISSUE TITLE
TS / JS: When autocomple method / function add parentheses `()` to end of auto completed method / function

### ISSUE THREAD

**Issue by psnet** [microsoft/vscode#182431]
TS / JS: When autocomplete method / function add parentheses `()` to the end of auto completed method / function:

```ts
classInstance.me [do autocomplete]
->
classInstance.method();
```

**Comment by mjbvz** [comment]
Try these two settings:

```
"javascript.suggest.completeFunctionCalls": true,
"typescript.suggest.completeFunctionCalls": true
```

Once enabled, it should add `()` in most cases

**Comment by psnet** [comment]
Thanks, but can we just add `()` with cursor inside **w/o placeholders?**

![зображення](https://github.com/microsoft/vscode/assets/1023918/3b671eb9-9054-4ed9-bff0-aa14bb41649e)
