### ISSUE TITLE
[Feature-Request] Add another mode for "renderWhiteSpace" when selecting

### ISSUE THREAD

**Issue by c633** [Microsoft/vscode#18246]
- VSCode Version: Version 1.8.1 (1.8.1)
- OS Version: macOS 10.12

It would be great if `editor.renderWhiteSpace` has another mode for rendering the whitespace characters only when they are being selected, much like Sublime Text's behavior:
(these 2 images are captured from the same document)

![image](https://cloud.githubusercontent.com/assets/5112602/21739408/c0cf0e00-d4cc-11e6-842e-3c4dac2cb7fd.png)

![image](https://cloud.githubusercontent.com/assets/5112602/21739403/a705746e-d4cc-11e6-8557-99a18a78bc21.png)

**Comment by tanweershahzaad** [comment]
Hi It would be nice if renderWhitespace has one more option which would be intermediate option of the two 'boundary' and 'all'. what this will do that it will show only render whitespaces which are not at the boundary cases(i.e don't show whitespaces at the beginning of line too)

**Comment by ramya-rao-a** [comment]
Option to show whitespace when selecting is being tracked in #1477
