### ISSUE TITLE
';' expected.ts(1005) error is shown in a .js file #import statement. Using "TypeScript and JavaScript Language Features"

### ISSUE THREAD

**Issue by fmotion1** [microsoft/vscode#182478]
- VS Code Version: 1.78.2
- OS Version: Windows 10 Pro x64 22H2

Steps to Reproduce:

1. Enable the "**TypeScript and JavaScript Language Features"** extension included in VSCode.
2. Create a new `.js` file.
3. Add `#include "SomeScript.js";` to the top of the file.
4. Observe that the extension is marking the line as a problem with the cause of `';' expected.ts(1005)`

The #include statement above is perfectly valid JavaScript from what I understand. Why is it throwing a TypeScript error in a JavaScript file?

![Code_KNgLSUemOp](https://github.com/microsoft/vscode/assets/33441569/b7fb476a-e13a-4746-9292-d43de689d8be)

**Comment by mjbvz** [comment]
> The #include statement above is perfectly valid JavaScript from what I understand

Not any javascript I'm familiar with. You want `import` instead: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import
