### ISSUE TITLE
File rename input box is too narrow

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#18240]
- Rename a folder with a long name
- The input box doesn't show the whole name, even though there's room

In 1.8, it took the width of the sidebar. In 1.9 it doesn't.

![jan-06-2017 12-20-32](https://cloud.githubusercontent.com/assets/323878/21731753/d4ac8ee2-d40a-11e6-94cc-19ac64f4165e.gif)

**Comment by aeschli** [comment]
Fixed by 	4e64aa3

**Comment by aeschli** [comment]
Verified on Linux
