### ISSUE TITLE
the code of a.c was replaced by b.h

### ISSUE THREAD

**Issue by XuBovey** [Microsoft/vscode#18245]
- VSCode Version: Code 1.8.1 (ee428b0eead68bf0fb99ab5fdc4439be227b6281, 2016-12-19T14:49:23.350Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

|Extension|Author|Version|
|---|---|---|
|GBKtoUTF8|bukas|0.0.2|
|cpptools|ms-vscode|0.9.3|
|csharp|ms-vscode|1.6.2|
|Material-theme|zhuangtongfa|1.0.3|

---

Steps to Reproduce:

1. u have a.c and b.h files, a.c include b.h
2. open a.c
3. in a.c ctrl + leftClick open the b.h
4. close b.h
5. ctrl + move cursor on the code < #include ”b.h“ > in a.c , the code of a.c will be replaced by the code of b.h

**Comment by bpasero** [comment]
@XuBovey does it help you if you configure `"workbench.editor.enablePreview": false` ?

**Comment by XuBovey** [comment]
@bpasero thanks, it worked. but i cannot repeat the error, when i remove the configure "workbench.editor.enablePreview": false or set true, maybe the issue was a mistake. anyway i will keep the configure.
thanks a lot.
