### ISSUE TITLE
Crash when trying to move a file on wayland with sway

### ISSUE THREAD

**Issue by Ranguna** [microsoft/vscode#182435]
Does this issue occur when all extensions are disabled?: Yes/No

Version: 1.78.2 and 1.79.0-insider

### Steps to Reproduce:

1. On a machine with linux and sway, with the 1.5 scaling on a display with 2560x1440;
2. Open vscode with the following flags to enable wayland:
   ```
    --enable-features=UseOzonePlatform --ozone-platform=wayland
    ```
3. Try moving a file by dragging.

#### What is expected:

4. The "ghost" of the file should appear, and the user should be allowed to move the file.

#### What actually happens:

4. vscode crashes with the following error:
```
[505523:0514/151651.871725:ERROR:wayland_event_watcher.cc(36)] libwayland: wl_surface@45: error 2: Buffer size (288x41) is not divisible by scale (2)
```

Workaround:

Changing the global scaling from 1.5 to 1 solves the issue (but the text becomes way too small for high dpi displays).

**Comment by Ranguna** [comment]
I'm not sure if this is a wayland/sway issue or a vscode issue. Wayland world is a bit weird.

I found this old closed issue on sway: https://github.com/swaywm/sway/issues/6014

**Comment by konradwojda** [comment]
I have similar issue on GNOME 44.1. Same display resolution and scaling (2560x1440, 1.5). 
Error:
```
[64637:0517/130100.673982:ERROR:wayland_event_watcher.cc(36)] libwayland: wl_surface@58: error 2: Buffer size (241x70) must be an integer multiple of the buffer_scale (2).
```
For me it happens when I try to move editor tabs, usually crash depends on length of opened file.
