### ISSUE TITLE
Static web app development hook to API debugger from emulator

### ISSUE THREAD

**Issue by pwang2** [microsoft/vscode#182446]
Yes, I have read another discussion thread #2405 which is locked for comment. 

In current SWA development, it is suggesting to use a 2 step flow to start an API debug session.  https://learn.microsoft.com/en-us/azure/static-web-apps/local-development#debugging,   first, start the normal API debugger using the default debugger, then use a command line to connect the emulator to the API backend. 

with postLaunchTask, we can start the function api backend, then using 
```
swa start --api-location http://localhost:7071
```
to start the swa emulator connect the backend which is already started API function debugger.   it sounds much handier than the 2 step approach. 

Any other way to achieve this is also greatly appreciated.

**Comment by roblourens** [comment]
I don't quite understand, what does that command do? Can you start it _before_ the launch config?

**Comment by roblourens** [comment]
I still only have a rough understanding of the scenario but I think vscode shouldn't try to solve the problem for the same reasons we discussed in https://github.com/microsoft/vscode/issues/2405. I agree that there could be a better experience, but I think it would be better for the Azure debug extension to try to solve this.

**Comment by pwang2** [comment]
As I have mentioned in the original issue content.   I feel it might be a  chance for us to revisit the needs of a postLaunchTask.

If we want to debug the API protected by AAD or something similar,  instead of creating some swagger interface for user to input, it makes a lot of sense and much easier to call from the UI to API directly which is also the best starting point for a debug session as well.

With current Azure static web apps cli setup,  the emulator is accountable as a proxy to the API resource.  or the UI can create a devServer proxy to the API endpoint as well.   Since it is an lazy proxy,  the emulator or the devServer proxy does not need to ensure a qualified ready state at all. 

Thanks for your time again.   I am a little stubborn here as I feel this is a real generic user case when mono repos are gaining more popularity nowardays.

**Comment by roblourens** [comment]
Sorry, but I still don't think that we should try to solve this from vscode. I don't think we can do a good job because we can't really know at what point your debuggee has actually finished "launching" and is ready for whatever task you want to run. That's why I think it would be better for an extension that understands the domain to solve this.
