### ISSUE TITLE
Support Sticky Scroll (showing markdown headers) in notebooks

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#182444]
Does this issue occur when all extensions are disabled?: Yes/No

We could explore sticky scroll by showing markdown headers (aligned with TOC and Folding) in notebook editor.

**Comment by rebornix** [comment]
Here is another scenario that sticky scroll can help with

<img width="1990" alt="image" src="https://github.com/microsoft/vscode/assets/876920/fdac4e14-c72a-45f7-8cd7-8c1a7f1f79c0">

I was searching for issues created or assigned to me through Find Widget, since the output is large, I can't easily tell what category the output belongs to, whether it's "Open Issues" or "Verifiable Issues". If we have Sticky Scroll headers, it would be much easier to tell.

**Comment by Yoyokrazy** [comment]
listview top padding support via #178626

**Comment by Yoyokrazy** [comment]
out of date -- nb sticky scroll is in polish stage. tracking via #188703
