### ISSUE TITLE
Build failures with timeout exceeded - "vscode API - copy paste" tests

### ISSUE THREAD

**Issue by ulugbekna** [microsoft/vscode#182489]
We had two build failures with timeout exceeded and the code was recently changed, so a bit suspicious: 

Run 1: 

https://dev.azure.com/monacotools/Monaco/_build/results?buildId=214554&view=logs&j=a8b516b9-5c25-5ad9-505a-b03d38bc1dad&t=dfa17021-5047-5128-653a-6715a72ca3f9&l=846

Run 2: 

https://dev.azure.com/monacotools/Monaco/_build/results?buildId=214546&view=logs&j=963754b8-394e-5caf-de5d-2790b068caec&s=c041ccde-92b7-5163-1d93-b1c06077f4b4&t=d61c32fd-93f0-5126-b44d-dcf4920dede7&l=854

**Comment by bpasero** [comment]
More:
* https://dev.azure.com/monacotools/Monaco/_build/results?buildId=214714&view=logs&j=a8b516b9-5c25-5ad9-505a-b03d38bc1dad&t=8f2e4787-addf-5530-4164-a727ac47f0b3&l=497
* https://dev.azure.com/monacotools/Monaco/_build/results?buildId=214610&view=logs&j=a8b516b9-5c25-5ad9-505a-b03d38bc1dad&t=dfa17021-5047-5128-653a-6715a72ca3f9&l=839
* https://dev.azure.com/monacotools/Monaco/_build/results?buildId=214509&view=logs&j=a8b516b9-5c25-5ad9-505a-b03d38bc1dad&t=dfa17021-5047-5128-653a-6715a72ca3f9&l=889
