### ISSUE TITLE
Syntax highlighting fails for Lua block comments in some cases

### ISSUE THREAD

**Issue by tobiesque** [microsoft/vscode#182484]
Type: <b>Bug</b>

* Create a new text-file in VS Code and set it to .Lua
* Add the following text:
```
--[[ ]]
Should not be commented out

--[[ 
 ]]
Should not be commented out
```
* The lines saying "Should not be commented out" should not be highlighted as comment (green).

VS Code version: Code - Insiders 1.79.0-insider (9084e081d4e89ed8ab67fce340d573c4e1378939, 2023-05-15T05:20:50.327Z)
OS version: Windows_NT x64 10.0.19045
Modes:

**Comment by alexr00** [comment]
Looks like this upstream issue https://github.com/LuaLS/lua.tmbundle/issues/16.
