### ISSUE TITLE
[json] support `jsonl` format out of the box

### ISSUE THREAD

**Issue by DoctorKrolic** [microsoft/vscode#182402]
`jsonl` is a basic format, where a file is a collection of `json`s, where each `json` takes a line. This is common format for representing data in ML, where each line in `.jsonl` file represents a data frame. Considering, that the format is pretty primitive, I think, it is reasonable to support basic features for such file format out of the box. Basic features are:
- syntax colorization (basically same token types as in normal `json`)
- `json` icon in explorer/code tab (already there for some reason)
- add `JSON Lines` format for such files, so other extensions can potentially add features to this file format. The same way as there is a `JSON with Comments` format, for instance

**Comment by aeschli** [comment]
Syntax colorization is now available in 1.79 (thanks for the PR!)
Currently no plans for formatter support. Icon would need to have to come form seti.

**Comment by F-loat** [comment]
An [extension](https://github.com/F-loat/jsonl-converter) for one-click convert JSON/JSONL.

![screenshot](https://github.com/F-loat/jsonl-converter/raw/main/media/screenshot.gif)
