### ISSUE TITLE
Request to expose the built-in ptyService API

### ISSUE THREAD

**Issue by bitekas** [microsoft/vscode#182424]
Hello, I'm trying to build an extension over Terminal and found that this part of API is somewhat in shadow. As a result, not many developers are building their awesome Terminal extensions.
For example, it is virtually impossible to build an extension that would replace all "foo" texts with "bar" in Terminal . Or how would one build an extension that would hide all the passwords in command line outputs after a certain period of time, or highlight particular words or phrases, etc.
The reason why it is unpractical is because in order to implement anything meaningful a developer would have to replicate the terminal functionality from scratch by implementing a pty interface with custom readers and writers. Which means in order to support Windows, Linux, OS X, WSL, remote development, and who knows what else, correctly, and with all related hacks, the developer would have to copy-paste [ptyService.ts](https://github.com/microsoft/vscode/blob/main/src/vs/platform/terminal/node/ptyService.ts) with all its dependencies into their plugin.
This is why implementing any extension using terminal is so unpractical so even documentation is stale. What the API gives currently is only the raw PTY interface and that's it.

The proposed API change is quite simple: to expose the built-in ptyService with modifiers such as onBeforeWrite and onBeforeRead alike:
```
const pty: vscode.SystemPseudoterminal = {
  onBeforeRead: (buffer) => { return buffer.replace("foo", "bar"); },
  onBeforeWrite: (buffer) => { return "\x1b[31m"+buffer; }
};
```
through proper interfaces.

Alternatively, may I please request exposing the xterm.js buffer of a terminal through an API.

Thank you for considering this feature request.

**Comment by Tyriar** [comment]
The pty service mostly just passes data back and forth between a real pty, VS Code doesn't have much smarts on top of that really. Yes it can read what's in the buffer, but we decided for the `Pseudoterminal` API to mirror what a pty is capable of only. So if you want to write an interactive app you can do so by maintaining your own view of the buffer and tracking/reacting to resize of the pty.

You might find https://github.com/microsoft/shell-engine-js useful if you're trying to implement a REPL, it's a little rough around the edges but works fairly well.
