### ISSUE TITLE
When name of thread is changed, the UI is not updated. 

### ISSUE THREAD

**Issue by pieandcakes** [Microsoft/vscode#18244]
- VSCode Version: 1.8.1
- OS Version: Windows 10 x64

Steps to Reproduce:

1. Report name of a thread as `Thread 1`
2. Change name of the thread as `main()`

Expected: Threads name to change in UI
Actual: Name in Call Stack window still is `Thread 1`

When we report a ThreadCreated event, we receive a ThreadsRequest which we respond to with the id and Name of threads. When code then hits a breakpoint we are able to actually resolve the thread name to something besides `Thread 1` so with the same thread id we change the name but the UI doesn't reflect this. 

Also: Is there a reason why after every ThreadCreated event, that we are queried for Threads?

**Comment by isidorn** [comment]
> Also: Is there a reason why after every ThreadCreated event, that we are queried for Threads?

Yes, this is how our thread model is designed. The `ThreadCreated` event has no details about the new thread, there is no name for instance only the id. 
More details https://code.visualstudio.com/Docs/extensionAPI/api-debugging
