### ISSUE TITLE
ctrl+c does not stop node server in command line from vscode macos high sierra

### ISSUE THREAD

**Issue by codegdo** [microsoft/vscode#182459]
Does this issue occur when all extensions are disabled?: Yes/No

Install
VS Code Version:1.78.2
OS Version: Mac OS High Sierra

Ctrl+c or other keybinding is not working.

---

VS Code Version: 1.77.3 
Work fine.

**Comment by codegdo** [comment]
VS Code Version:1.78.2
OS Version: Mac OS High Sierra

Ctrl+c or other keybinding is not working.

---

VS Code Version: 1.77.3 
Work fine.

**Comment by tamuratak** [comment]
Similar to #181700 #181783

@deepak1556, it seems that `node-pty` doesn't work well on old macOS.
