### ISSUE TITLE
window.restoreFullscreen has unintended side effect of forcing openFilesInNewWindow=false behavior

### ISSUE THREAD

**Issue by karolz-ms** [Microsoft/vscode#18243]
- VSCode Version: Code 1.8.1 (ee428b0eead68bf0fb99ab5fdc4439be227b6281, 2016-12-19T14:49:23.350Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

|Extension|Author|Version|
|---|---|---|
|githistory|donjayamanne|0.1.4|
|Go|lukehoban|0.6.52|
|csharp|ms-vscode|1.6.2|
|PowerShell|ms-vscode|0.8.0|
|incremental-search|siegebell|0.2.1|

---

Steps to Reproduce:

1. Open some file in VS Code and maximize the VS Code window
2. set window.restoreFullscreen to true in user settings (window.openFilesInNewWindow is not set and the default value/behavior should be "true")
3. Open another file by running "code file-name" from command line

Expected: file should open in a new, maximized window
Actual: file opens in existing VS Code window

**Comment by bpasero** [comment]
I cannot reproduce using 1.9 insiders where I set `"window.openFilesInNewWindow": "on"`. 
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: http://code.visualstudio.com/Download#insiders

**Comment by karolz-ms** [comment]
Build 1.9 works as expected. 

Seems that the default behavior changed between 1.8 (where openFilesInNewWindow is true by default) and 1.9, where the default is to open files in the last active window.

So I assume this issue should be treated as fixed in 1.9 series?

**Comment by bpasero** [comment]
@karolz-ms yes, see https://github.com/Microsoft/vscode/issues/371#issuecomment-270076869
