### ISSUE TITLE
Misspelled command names: Carret → Caret

### ISSUE THREAD

**Issue by svenax** [Microsoft/vscode#18252]
- VSCode Version: Code 1.8.1

The user accessible commands `editor.action.moveCarretLeftAction` and `editor.action.moveCarretRightAction` are misspelled. They should use `Caret` instead. These files are affected:

- editor.all.ts
- carretOperations.ts
- moveCarretCommands.ts
- moveCarretCommands.test.ts

Maybe the old names need to be kept as deprecated in order to not break existing code.

**Comment by alexandrudima** [comment]
I had to keep the command ids in the misspelled form
