### ISSUE TITLE
VS Code Does not open as it used to

### ISSUE THREAD

**Issue by Sanjay-2004** [microsoft/vscode#182517]
![vscode](https://github.com/microsoft/vscode/assets/118104350/6234a8da-e598-4c48-8772-716a5984069a)

Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:  1.78.2
- OS Version:  Win 11

Steps to Reproduce:

1.  Just open Vs Code
2. This pop up comes but eventually after like 4 to 5 minutes VS code opens

**Comment by gjsjohnmurray** [comment]
Are you using Mcafee antivirus? If so please see https://github.com/microsoft/vscode/issues/178962

**Comment by Sanjay-2004** [comment]
Thank you so much @gjsjohnmurray 
I uninstalled McAfee AntiVirus and it is now working perfectly fine
