### ISSUE TITLE
Disabling "workbench.tips.enabled" has no effect, seems a fairly recent regression

### ISSUE THREAD

**Issue by nikita-r** [microsoft/vscode#182513]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.78.2
- OS Version: Windows 10

Steps to Reproduce:

1. Disable "watermark tips"
![image](https://github.com/microsoft/vscode/assets/53914057/97468e48-9b6d-4127-8d08-fbe6fc594463)

2. Observe that the tips do appear when no editor
![image](https://github.com/microsoft/vscode/assets/53914057/9efae0dd-d6d7-420a-8106-a4de712119da)

**Comment by jNaimXIII** [comment]
can confirm. reloading the window a few times will randomly fix it but yeah, this seems to be a recent addition.
