### ISSUE TITLE
Provide a way for extension that have extension specific telemetry opt-in settings to use the new API

### ISSUE THREAD

**Issue by davidanthoff** [microsoft/vscode#182527]
The [Julia](https://marketplace.visualstudio.com/items?itemName=julialang.language-julia) extension has used telemetry for a long time, and we have a strict user opt-in policy for collecting it. So, there are two existing settings in the extension for usage and crash telemetry, and we only ever send anything if the users explicitly opted in.

I would like to use the new `TelemetryLogger` infrastructure (together with https://github.com/microsoft/vscode-extension-telemetry), but I can't figure out how we could integrate our custom opt-in settings with that.

I think conceptually the right thing would be that `TelemetryLogger` provides some way for extensions to indicate their own opt-in settings, and then `TelemetryLogger` takes that _and_ the VS Code-wide setting into account to decide whether anything should be sent, right? But right now it seems that `TelemetryLogger` only ever looks at the system wide settings, with no way to integrate extension specific settings?

Is there some way around that? I initially thought I could write a custom `TelemetrySender` to add another level of filtering, but 1) conceptually that seems not right, and 2) when using https://github.com/microsoft/vscode-extension-telemetry, then it seems to provide the `TelemetrySender`, so that option is also not open to me.

**Comment by lramos15** [comment]
Number one would be the suggested way to do it since we avoid placing any extension specific concepts in the API and allow extensions to abstract things however they so wish.

Number two seems to be https://github.com/microsoft/vscode-extension-telemetry/issues/54

**Comment by davidanthoff** [comment]
> Number one would be the suggested way to do it since we avoid placing any extension specific concepts in the API and allow extensions to abstract things however they so wish.

I don't fully understand this :) Are you saying that the proper way to do this is to write a custom `TelemetrySender` who takes extension specific settings into account? But isn't the idea of the current design that all the _filtering_ etc. happens inside the `TelemetryLogger`? To me that seems to make more sense than to put this into the `TelemetrySender`, which AFAIK is really just there to connect with various telemetry backends, right?

In my mind, a good design would be if a `TelemetryLogger` had methods that would allow an extension to enable and disable usage and crash telemetry. Say something like `logger.enableErrorLogging(true)`, `logger.disableUsageLogging(false)`. `TelemetryLoggerOptions` would probably also need two more fields for this (say `enableErrorLogging` and `enableUsageLogging`) for the initial state of these two. The implementation of `TelemetryLogger` would then check whether the extension had enabled things, _and_ the global telemetry settings were enabled, and only if both are the case would it send telemetry. This design would be very non-specific with respect to any given extension. I could completely control how I want to set extension specific telemetry settings etc.

> Number two seems to be https://github.com/microsoft/vscode-extension-telemetry/issues/54

To me that seems really not an ideal solution, for two reasons: first, isn't the primary purpose of vscode-extension-telemetry to bridge to appinsights? It seems inefficient if every telemetry sender has to implement this separately. And second, that proposal seems _very_ specific and constraint on how an extension could actually store its extension-specific telemetry settings.

**Comment by lramos15** [comment]
I get what you're saying for number one, but my idea was that you would wrap the logger entirely and do your additional filtering before calling log. I understand it's not ideal, but extensions may have many metrics which determine when telemetry is on and off. Additionally, I wonder if it may be confusing if someone says `.enableUsage(true)` but then the setting is off so it doesn't get sent even though you enabled it. To me the VS Code API should be simple and easy to use for the common case while enabling more advanced use cases like this one. VS Code does this in core in a way as does the extension-telemetry module by basically exposing a telemetry service which wraps the logger. I understand the logger should handle most of the logic which it does especially for the common case, but I'm not sure we will ever be able to cover all of the use cases.

As for updating the module, the module wouldn't modify the sender just when the logger is called. We expose a wrapped interface so this logic can live one level up.

**Comment by davidanthoff** [comment]
> my idea was that you would wrap the logger entirely and do your additional filtering before calling log

That won't work with the catch-all-unhandled-exceptions feature, though, right? That is the primary thing from the new telemetry stuff I am interested in :)

> To me the VS Code API should be simple and easy to use for the common case while enabling more advanced use cases like this one.

Yes, I think that is exactly the right spirit. But at the same time, I don't think having an extension-specific way to enable/disable its own telemetry is an advanced scenario, in my mind pretty much any third-party extension should provide that option.

Telemetry for every third-party extension will have a different legal entity in charge of the telemetry data, different data retention policies etc. The idea that users have to opt-out of either all telemetry from all vendors that they have extensions from, or none seems weird. What if a user has one extension from vendor A and one from B, and they are comfortable with the privacy policy from A but not B. So with this design of one global switch, they now have to turn off all telemetry. That is _really_ not in the interest of vendor A: they designed a good policy, and now because B has a bad one, they aren't getting telemetry data anymore.

Case in point: what if a user is not comfortable with the MS data collection policy (and there seem to be [some](https://github.com/microsoft/vscode/issues/176269) ;), but OK with the Julia extension privacy policy? Why should we not be able to receive our own telemetry data in that case? Just anecdotally, we have a fair number of users in that camp (I personally don't hold that view, just to be clear).

> I wonder if it may be confusing if someone says `.enableUsage(true)` but then the setting is off so it doesn't get sent even though you enabled it.

Maybe a better API would be that `TelemetryLogger` has two new properties called `usageStatus` and `crashStatus` (not the best names, so probably would be good to iterate on that) of enum type `TelemetryStatus` that can have values `Off` (no telemetry is sent), `On` (telemetry is sent no matter what, i.e. ignores the main VS Code setting) and `FollowSystemSetting` (the current behavior and maybe this could be the default). To me that would strike a good balance between simple and easy, but at the same time giving extensions all the flexibility to enable their custom handling of opt-in, opt-out etc.

**Comment by lramos15** [comment]
> That won't work with the catch-all-unhandled-exceptions feature, though, right? That is the primary thing from the new telemetry stuff I am interested in :)
That is correct

> Case in point: what if a user is not comfortable with the MS data collection policy (and there seem to be [some](https://github.com/microsoft/vscode/issues/176269) ;), but OK with the Julia extension privacy policy? Why should we not be able to receive our own telemetry data in that case? Just anecdotally, we have a fair number of users in that camp (I personally don't hold that view, just to be clear).

It's because the extensions live inside VS Code that we feel if the user disables global telemetry it should extend to extensions. This is the current policy we operate under and have done so since the beginning. Maybe it needs to be revisited at some point to cover cases like this, but I do not feel we should combine those discussions.

> I don't understand this :) What "module" are you referring to in the first part of the sentence?
The @vscode/extension-telemetry npm module

**Comment by lramos15** [comment]
I believe everything requested is currently possible by wrapping the `TelemetryLogger` or is covered by a feature request in `vscode-extension-telemetry`.

You can see even the unhandled error handler will call the logger

https://github.com/microsoft/vscode/blob/99a0a99fc371fa4b6a5c6f3968fcfc69ce047387/src/vs/workbench/api/common/extHostTelemetry.ts#L167


The other discussions surrounding extension settings being above global settings is something we won't do and is out of scope
