### ISSUE TITLE
Blue screen error after installing a extension and reloading VS code

### ISSUE THREAD

**Issue by Pixelico** [Microsoft/vscode#18257]
- VSCode Version: Code - Insiders 1.9.0-insider (83db3cad0c9a05dac75a7472b3b81b39ace243f7, 2017-01-06T07:10:22.163Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

|Extension|Author|Version|
|---|---|---|
|Angular2|johnpapa|1.0.2|
|debugger-for-chrome|msjsdiag|2.4.2|
|typescript-hero|rbbit|0.12.0|

---

Hi, before all: thanks for the awesome tool you're making.

Steps to Reproduce:

1. I installed two extensions ( the two listed up)
2. Then I clicked on the blue icon "Reload" after installation ends. 
3. I've got the message with the new feature "Hot save". 
4. Blue screen of death
5. Rebooted and yes, hot save works! 👍

**Comment by bpasero** [comment]
Wow, is that reproducible for you?

**Comment by Pixelico** [comment]
I've been installing some other extensions and reloading the application after. No blue screens. I close this issue since I can't reproduce the error.
