### ISSUE TITLE
Quick Open show the "..." to the left or center to not hide important segments

### ISSUE THREAD

**Issue by drKnoxy** [microsoft/vscode#18259]
- VSCode Version: Insider latest
- OS Version: osx sierra

## Feature Idea
In the quick open window for searching by file names, it would be nice if the file path were below the file name, and  also if long paths had the ellipsis on the left of the line instead of the right. This is really a annoyance in my current project where most tests and files are under the same folder and the __tests__ dir is hidden by ellipsis
* /DetailsPage/index.js
* /DetailsPage/__tests__/index.js

## Steps to Reproduce:
1. Open a workspace that has deeply nested paths
2. type `cmd+p` and start typing a file name
3. *err* When the path is longer than the quick-open window ellipsis are added to the right of the path.

## PR Feedback
I saw where in the code to correct the quick-open css. It also looks like the line-height for the items in the quick-open widget are set by JS to either 44px or 22px. But 44px is only triggered if the type implements getDescription(). I was going to add a getHeight method that the FileType could use to return 44px. And then use css to bump the path down to the next line.

Let me know if this would actually be merged if I submitted the PR 📟

**Comment by bpasero** [comment]
I like the idea of improving where the "..." is drawn when text overflows. As a reference, here is how ST is doing it:

![image](https://cloud.githubusercontent.com/assets/900690/21748760/6e5110da-d58d-11e6-9cd4-89eec97f6c24.png)

Unfortunately I do not think HTML by default supports an ellipsis in the center of the label.

**Comment by drKnoxy** [comment]
Here is the css snippet that would move the ellipsis and overflow to the left for a block level item, while keeping the text left-aligned.

```css
.quick-open-widget .quick-open-tree .quick-open-entry-description {
overflow: hidden;
text-overflow: ellipsis;
direction: rtl;
text-align: left;
}
```

**Comment by bpasero** [comment]
@drKnoxy careful though with changing the direction property, would that not confuse screen readers?

**Comment by drKnoxy** [comment]
Will external contributions be considered for this feature?

**Comment by bpasero** [comment]
@drKnoxy yes, we always welcome good quality PRs 👍

**Comment by phifa** [comment]
Why can't the whole quick-open-pane just be bigger? Or at least make it configurable. I have a large monitor and all my paths are being cut down, I have no idea which file is the right one, other than guessing.
