### ISSUE TITLE
Please add an ability to highlight any extra characters belonging to a word/variable

### ISSUE THREAD

**Issue by ArthurZ** [Microsoft/vscode#18258]
Please add an ability to highlight (with an intent to copy) any extra characters belonging to a word on double click.

Example is say symbols in Ruby - `:user_name` the colon in front indicates it is a symbol, presently clicking on the `:user_name` word highlights only the `user_name` part which makes a user re-select it using the keyboard+arrow keys which is awkward and time consuming.

Apart from Ruby there are many other languages where special characters form a variable.

PS: I am aware of another editor I used [EMEditor ](https://www.emeditor.com/)which has this capability.

**Comment by kaiwood** [comment]
There is already a setting for controlling the word boundaries:

        "editor.wordSeparators": "`~!@#$%^&*()-=+[{]}\\|;:'\",.<>/?"

For Ruby, simply remove `@` and `:`.

**Comment by sandy081** [comment]
@ArthurZ Please try the above suggestion and let us know if it works for you.
