### ISSUE TITLE
cannot open terminal tool under SSH - linux

### ISSUE THREAD

**Issue by navehgrofi** [microsoft/vscode#182591]
when trying to open a terminal window when connected to RPI via SSH i get the following error:

The terminal process failed to launch: A native exception occurred during launch (/lib/arm-linux-gnueabihf/libc.so.6: version `GLIBC_2.28' not found (required by /home/pi/.vscode-server/bin/b3e4e68a0bc097f0ae7907b217c1119af9e03435/node_modules/node-pty/build/Release/pty.node)).

vscode version - 1.78.2
host machine - windows
remote machine - rpi
RPi OS - RPI stretch

when using VSCode version 1.77 all is working well

**Comment by 1066mutex** [comment]
having the same issue, was working till the update

**Comment by jnoelvictorino** [comment]
Confirmed that it was happening in 1.78, but not in 1.77

**Comment by deepak1556** [comment]
Merging to https://github.com/microsoft/vscode/issues/181720
