### ISSUE TITLE
VSCode.dev is down, preventing login to VS Code

### ISSUE THREAD

**Issue by okaybenji** [microsoft/vscode#182544]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: N/A
- OS Version: macOS

Steps to Reproduce:

1. Visit https://vscode.dev

**Comment by TylerLeonhardt** [comment]
It works for me... Can you follow these steps so that we can get more information on what's going on?

* Trigger the sign in
* _Wait for the issue to happen..._
* Open the Output pane (ctrl+shift+u I think on Windows)
* drop in this issue he contents of the following:
  * `GitHub Authentication` or `Microsoft Authentication` Output channel (whichever you're using)

**Comment by okaybenji** [comment]
Hey, thanks so much for your assistance with this issue. Once I received your response a few moments ago, I tested and saw that it was only happening on my laptop and not other devices. It turned out to be caused by a piece of software called Pow, which I guess intercepts browser visits to domains ending in .dev for some reason.

On the off chance someone else has the same issue, here's some more information:

Chrome says ERR_CONNECTION_REFUSED. Safari says "Safari can't establish a secure connection to the server." However, Firefox shows:

```
Symlink your app to ~/.pow/vscode first.

When you access http://vscode.dev/, Pow looks for a Rack application at ~/.pow/vscode. To run your app at this domain:

$ cd ~/.pow
$ ln -s /path/to/myapp vscode
$ open http://vscode.dev/
```

If this is happening to you, you can get the uninstaller for Pow here: https://github.com/basecamp/pow/blob/master/uninstall.sh

In terminal, make the script executable:
`chmod +x /path/to/uninstall.sh`

Then run it:
`/path/to/uninstall.sh`

**Comment by TylerLeonhardt** [comment]
I wonder by pow doesn't like .dev 🤔 in any case, glad you're unblocked! I'll go ahead and close this since you're set.

cc @joaomoreno
