### ISSUE TITLE
VS Code opens system terminal instead of VS Code integrated terminal from "Source Control" on MacOS

### ISSUE THREAD

**Issue by EsDmitrii** [microsoft/vscode#182524]
Does this issue occur when all extensions are disabled?: Yes

Hi!
VS Code version:
    Version: 1.78.1 (Universal)
    Commit: 6a995c4f4cc2ced6e3237749973982e751cb0bf9
    Date: 2023-05-04T09:57:42.343Z
    Electron: 22.5.1
    Chromium: 108.0.5359.215
    Node.js: 16.17.1
    V8: 10.8.168.25-electron.0
    OS: Darwin arm64 22.4.0
    Sandboxed: No

Earlier I opened terminal in specific repository using this button:
<img width="288" alt="Screenshot 2023-05-15 at 19 28 00" src="https://github.com/microsoft/vscode/assets/124890665/ee41df36-4a12-4563-b260-95da6b973637">
It should open integrated to VS Code terminal like this:
<img width="1464" alt="Screenshot 2023-05-15 at 19 29 30" src="https://github.com/microsoft/vscode/assets/124890665/d3c573e4-fe67-4a9e-b8f7-bed948a1f0f1">
But after update, it opens system terminal app:
![example](https://github.com/microsoft/vscode/assets/124890665/485050a8-b2d8-4386-9711-0da96cf803d5)

Thank you in advance!

**Comment by meganrogge** [comment]
change the value of `terminal.explorerKind`

**Comment by EsDmitrii** [comment]
It is set by default. Nothing changed when I switched to another and back
<img width="917" alt="Screenshot 2023-05-15 at 20 56 26" src="https://github.com/microsoft/vscode/assets/124890665/5b7b5ca1-bb9d-415c-84f7-ef420e403b64">
