### ISSUE TITLE
LSP `textDocument/documentColor` requests not being sent since v1.78

### ISSUE THREAD

**Issue by bradlc** [microsoft/vscode#182534]
Does this issue occur when all extensions are disabled?: Yes (all extensions other than the reproduction extension)

- VS Code Version: 1.78.2
- OS Version: macOS 12.5.1

Over at the Tailwind CSS IntelliSense repo we are seeing multiple reports of issues with colour decorators since the release of v1.78. Some are related to the new `defaultColorDecorators` setting which I think is a separate issue, but we are also seeing an issue where document colour requests are not being sent to the language server at all (`defaultColorDecorators` is `false` in this case).

I was able to create a small reproduction based on the LSP extension sample. Please see below.

Steps to Reproduce:

1. Clone https://github.com/bradlc/vscode-document-colors
2. Follow instructions from reproduction readme: https://github.com/bradlc/vscode-document-colors/blob/main/README.md

When the same project is opened in v1.76.2, the `onDocumentColor` count is logged repeatedly when editing the document.

**Comment by aeschli** [comment]
Thanks a lot for the great steps to reproduce. I pushed a fix for the issue.
