### ISSUE TITLE
why not 64bit version build?

### ISSUE THREAD

**Issue by shangxinbo** [Microsoft/vscode#18254]
Does it have a 64bit version on windows?

**Comment by sandy081** [comment]
Of course version available for windows is 64 bit.

**Comment by levrik** [comment]
@sandy081 I was asking me the same. The task manager shows 32 bit.
![image](https://cloud.githubusercontent.com/assets/9491603/22178172/d65384ea-e02f-11e6-80e4-574aaca2f2a0.png)
