### ISSUE TITLE
The 'Save All' function causes the current document to be out of orde

### ISSUE THREAD

**Issue by Csirme** [Microsoft/vscode#18255]
- VSCode Version: Code 1.8.1 (ee428b0eead68bf0fb99ab5fdc4439be227b6281, 2016-12-19T14:42:49.304Z)
- OS Version: Darwin x64 15.6.0
- Extensions:

|Extension|Author|Version|
|---|---|---|
|html-css-class-completion|Zignd|1.0.3|
|vscode-JS-CSS-HTML-formatter|lonefy|0.2.2|
|debugger-for-chrome|msjsdiag|2.4.2|

---

Steps to Reproduce:

hi,thans for vs code.but i meet some problems.

When I modify a lot of files, use the Save All function, all the changes to save the file, but will change all the files to the current document window, resulting in the current document confusion.
I can only 'back' document to correct, this is not cool oh ~ ~ look forward to solving.

当我修改了许多文件后，使用全部保存功能，的确全部改变的文件保存了，但是又会把所有改变的的文件保存到当前的文档窗口，导致当前的文档错乱。
我只能‘后退’文档，才能更正，这个不酷哦～～期待解决。
thanks .

**Comment by bpasero** [comment]
I wonder if this issue is being caused by an installed extension. Can you try to run VS Code without extensions? From the command line (NOT the integrated terminal in Code), execute: `code --disable-extensions` and try your steps again to see if it reproduces. If you see it is an issue with the extension, please file it against the extension repository itself.

**Comment by Csirme** [comment]
@bpasero

**Comment by Csirme** [comment]
Sorry,it's the 'vscode-JS-CSS-HTML-formatter	lonefy	0.2.2'  wrong.
it let me lose some code files.......AAAAAAA!!!

**Comment by Csirme** [comment]
@bpasero
hi,I tried several times ,disable too extensions.Problem will reappear. please you try once,it let me lose code files!

**Comment by Csirme** [comment]
@bpasero now,i'm a little scared to use VS Code....wowwww....my code file....

**Comment by bpasero** [comment]
@Csirme can you maybe show me what happens with screenshots or video, I am not sure I fully understand.

**Comment by Csirme** [comment]
@bpasero i try to use my friend's mac computer,it's no problem . i just can't to use 'save all',no time to fix it.thanks ,how about use vs code's  'shift +command+F' to format html code,it's very sad.

**Comment by Csirme** [comment]
@bpasero thanks，may be it's good now.
