### ISSUE TITLE
Version: 1.78.2 cannot start in windows 10

### ISSUE THREAD

**Issue by DaiZack** [microsoft/vscode#182520]
I updated VScode to the version UserSetup-x64-1,78.2 and the VScode cannot start as usual.
There are four vscode processes running in the backend but the window never shows up.
Version 1.77.3 and 1.76.2 working fine with me.

- VS Code Version: 1.78.2
- OS Version: Windows 10 Enterprise 22H2 OS

**Comment by bpasero** [comment]
Beginning with VS Code `1.78.1` accessing any UNC path (those that begin with `\\`) on Windows is blocked to mitigate a security risk that is further explained in this [Security Advisory](https://github.com/microsoft/vscode/security/advisories/GHSA-mmfh-4pv3-39hr).

Please refer to https://aka.ms/vscode-windows-unc for more information how to make your specific UNC path work again.

**Comment by DaiZack** [comment]
@bpasero Thank you for replying. But I'm not sure what do you mean?
I don't think I have UNC path with my installation. And my path is C:\Users\myuser\AppData\Local\Programs\Microsoft VS Code

**Comment by bpasero** [comment]
What happens when you run `code --verbose`

**Comment by DaiZack** [comment]
OK. I have solve the issue by adding the host into the configure file
    "security.allowedUNCHosts": [
        "group",
       "group.dns"
    ],

Also adding user environment variable NODE_UNC_HOST_ALLOWLIST with "group/group.dns" also works for me.

Thank you! @bpasero

**Comment by bpasero** [comment]
See also https://aka.ms/vscode-windows-unc
