### ISSUE TITLE
`onCancel` handler was attached after the promise settled

### ISSUE THREAD

**Issue by ulugbekna** [microsoft/vscode#182624]
Build failure: 

https://dev.azure.com/monacotools/Monaco/_build/results?buildId=214712&view=logs&j=55ac390b-ffb1-50ea-3650-525dd9a3fd80&t=0beb721c-bc23-58b2-a0a2-2fceaa3e6b2b&l=22

@joaomoreno says one of these may be related: 
https://github.com/microsoft/vscode/pull/179105 or https://github.com/microsoft/vscode/pull/179149

**Comment by aeschli** [comment]
See https://github.com/sindresorhus/got/issues/1489

I suggest we move to `node-fetch` so that when we are on node 18 we can replace if with the built-in fetch.

**Comment by bpasero** [comment]
Thanks Martin.
