### ISSUE TITLE
Save file prompt is not keyboard accessible

### ISSUE THREAD

**Issue by kiewic** [microsoft/vscode#182668]
Type: <b>Bug</b>

1. Create a new file
2. Press `Ctrl  + W` and the *Do you want to save the changes you made to file?* dialog appears
3. Bug is here, it is not possible to select `Save`, `Don't Save` or `Cancel` usign the keyboard, the trackpad is always needed to select an option

![image](https://github.com/microsoft/vscode/assets/874134/eec71cdd-9dc1-44a8-b0a9-2ff2b9211bf9)

VS Code version: Code - Insiders 1.79.0-insider (Universal) (9233de805c8fb05fad4d9d1c15f22fbca85430ad, 2023-05-16T10:48:21.936Z)
OS version: Darwin arm64 22.4.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M2 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|3, 3, 2|
|Memory (System)|16.00GB (0.08GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythontb:30258533
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscod805cf:30301675
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30404738
cppdebug:30492333
vsclangdf:30492506
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30618038
pylantcb52:30590116
pyind779:30611226
pythonsymbol12:30651887
a9j8j154:30646983
showlangstatbar:30737417
azdwalk:30721579
pythonms35:30671666
j16hj152:30680472
ecj1e332:30687743
pythonfmttext:30716741
pythoncmvfstr:30726892
fixhidewlkth:30724384
showsbindicator:30724477
pythongtdpath:30726887

```

</details>

**Comment by bpasero** [comment]
<img width="827" alt="Screenshot 2023-05-17 at 06 08 23" src="https://github.com/microsoft/vscode/assets/900690/7f9b887c-38ca-48bb-b3e8-c3c34ecdd47d">

I am still waiting for Apple to reward me for everytime I have to answer this.

**Comment by kiewic** [comment]
It worked, thank you! You should really get a reward!
