### ISSUE TITLE
Add API for win.isFocused(), win.isMinimized(), win.isVisible()

### ISSUE THREAD

**Issue by ShyykoSerhiy** [Microsoft/vscode#18263]
It would be great to have an API exposed to extensions to see if the vscode is visible/focused/minimized (http://electron.atom.io/docs/api/browser-window/#winisvisible)

Extensions that continuously show some kind of information in UI can benefit from this because they will not need to do the work if the editor for whatever reason is not visible (example extensions: https://marketplace.visualstudio.com/items?itemName=roblourens.vscode-stocks, 
https://marketplace.visualstudio.com/items?itemName=shyykoserhiy.vscode-spotify
)

**Comment by joaomoreno** [comment]
Focus state will be released this August milestone.

**Comment by ShyykoSerhiy** [comment]
Closed as win.isFocused() is sufficient for initial purposes. Thx!
