### ISSUE TITLE
Can't attach to main target.

### ISSUE THREAD

**Issue by hovek** [microsoft/vscode#182689]
In our corporate network we connect over VPN to our VM where we develop. Our terminals need to be run as an administrator in order to run npm commands and to run VS code as an administrator we have to run it with a command "code --disable-gpu-sandbox", otherwise it won't start at all. That possibly creates a problem where VS code is not able to attach to main target (debugger), be that Chrome or Edge.

Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.78.2
- OS Version: Windows 10 Enterprise 21H2

Steps to Reproduce:

1. Start VS code with "code --disable-gpu-sandbox" in VM environment as an administrator.
2. Start Debugging.

**Comment by connor4312** [comment]
Duplicates https://github.com/microsoft/vscode-js-debug/issues/1477#issuecomment-1353622384

**Comment by connor4312** [comment]
Edge and Chrome share the codebase.

VS specifically deelevates Edge to work around this issue and they have specific logic to do so.
