### ISSUE TITLE
boolean shown as a string in debug

### ISSUE THREAD

**Issue by Eli-Goldberg** [Microsoft/vscode#18268]
- VSCode Version: 1.8.1
- OS Version: Ubuntu 16.04

Steps to Reproduce:

1.  have this in your code: _const reportQuery = JSON.parse('{"advanced":true}');_
2. stop one line after, _advanced_ will be shown as a string but will be of type "boolean"
![string-bool-2](https://cloud.githubusercontent.com/assets/19211868/21748657/959c1e96-d592-11e6-8284-372a45fec819.png)

![string-bool](https://cloud.githubusercontent.com/assets/19211868/21748661/b3329cf0-d592-11e6-974c-f6bdbcfa24d4.png)

**Comment by isidorn** [comment]
Does not repro with latest vscode insiders
Can you please try with latest vscode insiders with this exacty snippet if it reproes for you


```javascript
const reportQuery = JSON.parse('{"advanced":true}');
if (reportQuery.advanced === true) {
	console.log("hello");
}
debugger;
```

![screen shot 2017-01-10 at 12 50 35](https://cloud.githubusercontent.com/assets/1926584/21805229/6b0c9f1e-d733-11e6-926b-bd337d475b43.png)

**Comment by Eli-Goldberg** [comment]
True, fixed in insiders.
