### ISSUE TITLE
Support json schema merging

### ISSUE THREAD

**Issue by unional** [Microsoft/vscode#18265]
- VSCode Version: 1.8.1

Today we can specify json schemas:

```js
{
  "json.schemas": [
    {
      "fileMatch": [
        "tsconfig.*.json"
      ],
      "url": "http://json.schemastore.org/tsconfig"
    }
  ]
}
```

It would be great we can extend a schema to provide additional fields:

```js
{
  "json.schemas": [
    {
      "fileMatch": [
        "package.json"
      ],
      "url": [ "http://json.schemastore.org/package", "./avajs.schema.json", "./nyc.schema.json"]
    }
  ]
}
```

Or is there a way to extend (multiple inherits) a schema with the json schema syntax?

```js
{
  "json.schemas": [
    {
      "fileMatch": [
        "package.json"
      ],
      "url": "./my.package.schema.json"]
    }
  ]
}
```

```js
// my.pacakge.schema.json
{
   // merging "http://json.schemastore.org/package", "./avajs.schema.json", "./nyc.schema.json"
}
```

**Comment by aeschli** [comment]
You can create a JSON schema that references other schemes.
{
   "anyOf": [
        { "$ref" : "http://json.schemastore.org/package" },
        { "$ref" : "./avajs.schema.json" }
   ]
}

If you are an extension author and configure a schema through the [jsonValidation extension point](https://code.visualstudio.com/docs/extensionAPI/extension-points#_contributesjsonvalidation), that schema will be added to any other schemas contributed to that file. We use that to add schema information to vscode custom fields in package.json: https://github.com/Microsoft/vscode/blob/master/extensions/extension-editing/package.json#L22
(that URL is a virtual URL served by vscode, but it can be also a schema located in the extension).
