### ISSUE TITLE
Dark empty blocks in editor on large screens

### ISSUE THREAD

**Issue by cmelone** [Microsoft/vscode#18264]
- VSCode Version:  1.8.1
- OS Version: MacOS 10.12.2

Steps to Reproduce:

1. Open a file on a display around 1920x1080
2. See large empty blocks on screen

Whenever I open a file on my display (Samsung UE590), I see these large blocks. Here's an [example](https://i.sli.mg/kQQAHx.png). The app looks normal when it is at regular resolution (no external display).

Is there any fix to this?

Thanks

**Comment by bpasero** [comment]
#12473
