### ISSUE TITLE
UI Freezes when 'Open Folder' button pressed

### ISSUE THREAD

**Issue by craftit** [microsoft/vscode#182632]
Type: <b>Bug</b>

The UI freezes whenever I try and use 'Open Folder'. I disabled extensions and it still happens, so I think the problem is in the editor code.
I've tried leaving it for a few hours to see if it is just slow, but it doesn't change anything. 
Closing and opening lets you use the UI again and do anything but try and open something. 

On 'Ubuntu 22.04.2 LTS'  with KDE installed.

VS Code version: Code - Insiders 1.79.0-insider (9233de805c8fb05fad4d9d1c15f22fbca85430ad, 2023-05-16T10:45:57.437Z)
OS version: Linux x64 5.15.0-72-generic
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) Gold 6142 CPU @ 2.60GHz (64 x 2600)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|1, 1, 1|
|Memory (System)|125.49GB (111.88GB free)|
|Process Argv|--unity-launch --crash-reporter-id 9fe8de81-62c1-4f4e-8ee3-bc9c4f63965d|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|plasma|
|XDG_CURRENT_DESKTOP|KDE|
|XDG_SESSION_DESKTOP|KDE|
|XDG_SESSION_TYPE|x11|
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythontb:30258533
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscod805:30301674
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30404738
cppdebug:30492333
vscaac:30438845
vsclangdf:30492506
c4g48928:30535728
dsvsc012:30540252
pynewext54:30618038
pylantcb52:30590116
pyind779:30611226
pythonsymbol12:30651887
a9j8j154:30646983
showlangstatbar:30737417
azdwalk:30721579
pythonms35:30671666
19089226:30680468
57b77579:30687741
pythonfmttext:30716741
pythoncmvfstr:30726892
fixshowwlkth:30724385
showsbindicator:30724477
pythongtdpath:30726887

```

</details>

**Comment by gjsjohnmurray** [comment]
Maybe related to #146422

**Comment by craftit** [comment]
I just checked, and yes, it is the same issue. There is a dialogue hidden behind the window.
