### ISSUE TITLE
Build failure: following tasks did not complete: vscode-reh-darwin-x64-min-ci

### ISSUE THREAD

**Issue by ulugbekna** [microsoft/vscode#182626]
Build: https://dev.azure.com/monacotools/a6d41577-0fa3-498e-af22-257312ff0545/_build/results?buildId=214785

Failure: https://dev.azure.com/monacotools/Monaco/_build/results?buildId=214785&view=logs&j=260a512b-e5ca-5cf1-3f8e-20c0fa41efc9&t=ffb884bb-7609-5d1e-3434-a70e531948ad&l=19

Changes: https://github.com/Microsoft/vscode/compare/1236c13...3e4ed47

**Comment by bpasero** [comment]
Looks like @aeschli will also fix this one via https://github.com/microsoft/vscode/pull/182629

**Comment by AadreshMaghnani** [comment]
Hello! I'd like to work on this issue! :)

**Comment by aeschli** [comment]
This is about node not being downloaded. 

It's not directly related to the change I made to https://github.com/microsoft/vscode/pull/182629

Let's mark it as dup of https://github.com/microsoft/vscode/issues/182951
