### ISSUE TITLE
OSS debugger hung

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#182616]
Debugging and OSS freezing seems happen a bit more frequent. This is the sample I snapped [freeze.txt](https://github.com/microsoft/vscode/files/11486831/freeze.txt)

**Comment by deepak1556** [comment]
Main process seems to have an uncaught exception since most of the cycles in the stack are spent reporting the exception `node::errors::TriggerUncaughtException`, @jrieken do you see any exception printed to the console ? Attaching the symbolicated trace below for reference.

**Comment by jrieken** [comment]
> @jrieken do you see any exception printed to the console ?

Sorry too late - I cannot keep a froozen oss instance around because I need a working one for development
