### ISSUE TITLE
Interactive Window keyboard shortcut

### ISSUE THREAD

**Issue by sant3e** [microsoft/vscode#182644]
Type: <b>Bug</b>

After the last update, i can no longer send lines of python codes to Interactive Window. Pressing SHIFT+ENTER on select code, used to open Interactive Window. Now I can only right click and send to interactive window.
I've search all internet for a fix, nothing works
I do have check the box: "When pressing shift+enter, send select code in a Python file to the Jupyter interactive window as opposed to the Python terminal" .. but still nothing. 
I even tried addin in the Preferences settings JSON this:
"python.dataScience.sendSelectionToInteractiveWindow": true
... still nothing. How do i get back this function!

VS Code version: Code 1.78.2 (b3e4e68a0bc097f0ae7907b217c1119af9e03435, 2023-05-10T14:39:26.248Z)
OS version: Windows_NT x64 10.0.19044
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz (8 x 1805)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.73GB (1.85GB free)|
|Process Argv|--crash-reporter-id c060e1d8-490f-4510-9e57-1ea4b134760c|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (18)</summary>

Extension|Author (truncated)|Version
---|---|---
jsoncrack-vscode|Ayk|1.0.8
copilot|Git|1.86.82
copilot-labs|Git|0.14.884
gc-excelviewer|Gra|4.2.57
debug-visualizer|hed|2.4.0
vsc-python-indent|Kev|1.18.0
black-formatter|ms-|2023.2.0
isort|ms-|2022.8.0
python|ms-|2023.8.0
vscode-pylance|ms-|2023.5.20
jupyter|ms-|2023.4.1011241018
jupyter-keymap|ms-|1.1.0
jupyter-renderers|ms-|1.0.15
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-slideshow|ms-|0.1.5
remote-wsl|ms-|0.78.5
autodocstring|njp|0.6.1
vscode-icons|vsc|12.4.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
282f8724:30602487
pyind779:30671433
f6dab269:30613381
pythonsymbol12:30671437
a9j8j154:30646983
showlangstatbar:30737416
vsctsb:30705553
azdwalk:30721579
pythonms35:30701012
pythonfmttext:30731395
pythoncmv:30739700
fixhidewlkth:30730051
hidesbindicator:30730055
pythongtdpathcf:30739705

```

</details>

**Comment by ulugbekna** [comment]
Hi,

Thanks for filing the issue.

Could you please [try the following](https://github.com/microsoft/vscode/wiki/Keybinding-Issues#basic-troubleshooting):

- Run the command "Developer: Toggle Keyboard Shortcuts Troubleshooting" (you can, for example, run it from the Command Palette)
This will activate logging of dispatched keyboard shortcuts and will open an output panel with the corresponding log file.
- Press exactly the keybinding you desire.
- check what VS Code detects.

If you are having trouble understanding the output, please feel free to paste here and we'll be happy to help :-)

**Comment by sant3e** [comment]
I hope i did what you asked. I got this:
2023-05-16 19:03:22.811 [info] [KeybindingService]: / Received  keydown event - modifiers: [shift], code: ShiftLeft, keyCode: 16, key: Shift
2023-05-16 19:03:22.811 [info] [KeybindingService]: | Converted keydown event - modifiers: [shift], code: ShiftLeft, keyCode: 4 ('Shift')
2023-05-16 19:03:22.811 [info] [KeybindingService]: \ Keyboard event cannot be dispatched in keydown phase.
2023-05-16 19:03:22.816 [info] [KeybindingService]: / Soft dispatching keyboard event
2023-05-16 19:03:22.816 [info] [KeybindingService]: | Resolving shift+Enter
2023-05-16 19:03:22.816 [info] [KeybindingService]: \ From 16 keybinding entries, matched interactive.input.focus, when: no when condition, source: user.
2023-05-16 19:03:22.816 [info] [KeybindingService]: / Received  keydown event - modifiers: [shift], code: Enter, keyCode: 13, key: Enter
2023-05-16 19:03:22.816 [info] [KeybindingService]: | Converted keydown event - modifiers: [shift], code: Enter, keyCode: 3 ('Enter')
2023-05-16 19:03:22.816 [info] [KeybindingService]: | Resolving shift+Enter
2023-05-16 19:03:22.816 [info] [KeybindingService]: \ From 16 keybinding entries, matched interactive.input.focus, when: no when condition, source: user.
2023-05-16 19:03:22.817 [info] [KeybindingService]: + Invoking command interactive.input.focus.
2023-05-16 19:03:23.413 [info] [KeybindingService]: + Ignoring single modifier shift due to it being pressed together with other keys.

**Comment by ulugbekna** [comment]
Thanks! It seems either you or some extension has overridden that keybinding.

Please, check your `keybindings.json` (to open it, invoke command `Open Keyboard Shortcuts (JSON)` from the Command Palette (`ctrl+shift+p` on Windows and `cmd+shift+p` on MacOS)) for a keybinding that includes `"key": "shift+enter"` and remove it

If that's not the case, please copy-paste your keybindings.json here

**Comment by sant3e** [comment]
I have these:

[
    {
        "key": "shift+z",
        "command": "workbench.action.terminal.runSelectedText"
    },
    {
        "key": "ctrl+shift+a",
        "command": "copilot-labs.use-brush-picker",
        "when": "editorTextFocus"
    },
    {
        "key": "ctrl+shift+alt+e",
        "command": "-copilot-labs.use-brush-picker",
        "when": "editorTextFocus"
    },
    {
        "key": "shift+enter",
        "command": "interactive.input.focus"
    },
    {
        "key": "alt+enter",
        "command": "python.execSelectionInTerminal",
        "when": "editorTextFocus && !findInputFocussed && !jupyter.ownsSelection && !notebookEditorFocused && !replaceInputFocussed && editorLangId == 'python'"
    },
    {
        "key": "shift+enter",
        "command": "-python.execSelectionInTerminal",
        "when": "editorTextFocus && !findInputFocussed && !jupyter.ownsSelection && !notebookEditorFocused && !replaceInputFocussed && editorLangId == 'python'"
    },
    {
        "key": "ctrl+shift+o",
        "command": "workbench.action.openGlobalKeybindingsFile"
        
As i see i have 2 of them, not exactly sure which one to delete. My next question would be .. what do i do after i delete that binding and save?
Thank you for your prompt support!

**Comment by sant3e** [comment]
I may have found a solution.
I did this 2 times, but it worked only once
So, opening Keyboard Shortcuts (CTRL+K CTRL+S), type: Run Selection 
You should have 2 options: a) Jupyter: Run Selection/Line in Interactive Window with SHIFT+ENTER as key binding, and b) Python: Run Selection/Line in Python Terminal with (probably) also SHIFT+ENTER
You need to change the key binding for the Python (i did for ALT+ENTER). 

The thing is i did this before and it didn't work .. but once I uninstalled the Jupyter extension (there are 4 in fact) and reinstalled, and then proceed with changing the key binding ... only then it worked

**Comment by ulugbekna** [comment]
Based on your keybindings.json, you created a keybinding (the first entry)
and removed the old keybinding (the second entry - note how the command ID
has a - at the beginning). You should remove both entries to restore old
behavior. But it seems you have solved the problem

We have great docs around key bindings online if you want to have a look
