### ISSUE TITLE
`git status` with `--find-renames=50%` breaks version control for old versions of Git

### ISSUE THREAD

**Issue by albireox** [microsoft/vscode#182645]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.79.0-insider
- OS Version: macOS 13.3.1

Steps to Reproduce:

1. Launch VSCode in a computer with a relatively old version of Git (2.16.2 does it).
2. Open a project under version control.
3. Version control fails silently and only shows the Publish button. Trying to publish causes an error.

This seems to be related to a change that makes use of the `--find-renames=50%` option in `git status`, which doesn't seem to be supported by old-ish Git.

**Comment by lszomoru** [comment]
@albireox, sorry about this. I will try to get this fixed this week.

**Comment by biiigwang** [comment]
I am also experiencing the same issue.
- VS Code Version: 1.79.0-insider
- OS: Windows_NT x64 10.0.22621 
- git version 2.17.1

**Comment by biiigwang** [comment]
> It looks like the `--find-renames` option was added in git 2.18.0. Ideally you would want to keep your git installation up to date to keep up with the security fixes. Having said that I do understand that there are scenarios in which one cannot install the latest git release, so I have pushed a fix for this issue. The fix will be included in the next Insiders release.

Cheers！

**Comment by WuShichao** [comment]
@lszomoru Hi, I encountered the same issue with my VSCode + WSL1 (I haven't upgraded to WSL2 for some reason)

- git version: 2.11.0
- VSCode Version: 1.79.0

**Comment by lszomoru** [comment]
@WuShichao, could you please share the complete contents of the [git output window](https://code.visualstudio.com/docs/sourcecontrol/overview#_git-output-window)? What version of git are you running inside WSL? This flag should only be added in case you have a version of git that support it.

**Comment by pablobots** [comment]
Same issue here

**Comment by pierce-martin-overwatch** [comment]
Affecting me too. This seems like a major breaking change. Is there a bugfix release planned? Thanks.

**Comment by lszomoru** [comment]
@pablobots, @pierce-martin-overwatch, could you please share more about your environment? What version of git are you running (git --version). Are you also using WSL, or any other remote environments? Anything that helps me reproduce the issue would be extremely valuable (ex: the contents of [the git output window](https://code.visualstudio.com/docs/sourcecontrol/overview#_git-output-window)). Thanks!

**Comment by pierce-martin-overwatch** [comment]
Thanks Ladislau

Using git 2.17. I don't want to upgrade to insiders build

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by lszomoru** [comment]
@pierce-martin-overwatch, could you please run `git --version` and share the exact output. My current hypothesis is that for some reason we are unable to correctly detect the version number and that is why we incorrectly add the flag.

**Comment by lszomoru** [comment]
Let's continue the investigation in this issue https://github.com/microsoft/vscode/issues/184718. Thanks!
