### ISSUE TITLE
Clicking the middle mouse button on a terminal tab no longer kills it

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode#182775]
Type: <b>Bug</b>

Prior to 1.78 (I believe), middle-clicking on a terminal tab would kill/close that terminal. Now this no longer works, it just ends up with a 4-way scrolling mouse icon, but also doesn't scroll.

VS Code version: Code - Insiders 1.79.0-insider (f1258a5fbed44b8f84a097c73c1799c13c5c3646, 2023-05-17T05:27:38.052Z)
OS version: Windows_NT x64 10.0.22624
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 9 3900X 12-Core Processor             (24 x 3800)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.92GB (12.66GB free)|
|Process Argv|--enable-proposed-api GitHub.remotehub --enable-proposed-api GitHub.remotehub-insiders --crash-reporter-id 561c0491-629f-4c23-a394-b5e7a8dc8bb7|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by meganrogge** [comment]
This is working for me on macOS. I don't have a mouse attached to my windows computer - @tyriar can you repro?

https://github.com/microsoft/vscode/assets/29464607/ec8f482d-5e18-44c1-9a28-83e56cef5b8a

**Comment by Tyriar** [comment]
Works for me on Windows. Whether there's a scroll bar or not. Any other details @eamodio?

**Comment by eamodio** [comment]
This is the oddest thing, and it seems to be limited to interaction with the FancyZone Powertoy. If I resize the VS Code window manually, it all works fine -- middle-click on a Terminal tab closes it as it used to AND there is no sticky cursor for middle scrolling. 

BUT if I hold shift and drag the VS Code window to a FancyZone (I have the "Hold Shift key to activate zones while dragging" setting on in FancyZones) then the middle mouse button doesn't work to close a terminal tab (it still works in editor tabs FWIW) and the mouse cursor sticks for middle scrolling. And nothing seems to fix it (switching windows, minimizing, etc) except resizing the window, and then it fixes everything.

I've only experienced this with VS Code.

**Comment by eamodio** [comment]
FWIW, it only started with Electron 22 release in 1.78 and while the Powertoys release didn't change.

**Comment by deepak1556** [comment]
I don't have the setup to verify this issue, @rzhao271 in case you want to take a look.
