### ISSUE TITLE
It doesn't recognize Spanish characters such as á, ñ, etc.

### ISSUE THREAD

**Issue by FANMixco** [Microsoft/vscode#18274]
[103.txt](https://github.com/Microsoft/vscode/files/692049/103.txt)
- VSCode Version: 1.8.1
![capture](https://cloud.githubusercontent.com/assets/1666156/21749202/573afd18-d59a-11e6-8e60-ca5fc0956b57.PNG)

- OS Version: Windows 10 1607 (10.0.14393.576)

Steps to Reproduce:

1. Open the attached file.

**Comment by Mlocik97** [comment]
You can change a text-coding.

**Comment by FANMixco** [comment]
Thanks! It's a good point. However I don't program in Spanish very often, this is an exception because I was updating a project and I discovered that in Notepad, Wordpad, etc. The file is opened successfully without any additional configuration and not here.

**Comment by bpasero** [comment]
Yes, you have to set the encoding of the file, either just for the file or in settings. We default to UTF-8 and I guess that file is using a different encoding.

**Comment by FANMixco** [comment]
Hi @bpasero , I understand your point. However in Visual Studio, Notepad, Notepad++, Wordpad, etc. I don't need to change any special configuration to open one specific file, as I explain before, I tend to program more in English than in another language, but I noticed this challenge when I tried to open this XML with Latin Characters.

**Comment by bpasero** [comment]
Related: https://github.com/Microsoft/vscode/issues/5388
