### ISSUE TITLE
Adding NODE_OPTIONS environment variable externally results in an empty value

### ISSUE THREAD

**Issue by TheJim01** [microsoft/vscode#182777]
## Environment Info
Does this issue occur when all extensions are disabled?: **Yes**

- VS Code Version: 
> Version: 1.78.2 (user setup)
> Commit: b3e4e68a0bc097f0ae7907b217c1119af9e03435
> Date: 2023-05-10T14:39:26.248Z
> Electron: 22.5.2
> Chromium: 108.0.5359.215
> Node.js: 16.17.1
> V8: 10.8.168.25-electron.0
> OS: Windows_NT x64 10.0.19045
> Sandboxed: No
- OS Version: 
> Edition: Window 10 Pro
> Version: 22H2
> OS Build: 19045.2846
> Experience: Windows Feature Experience Pack 120.2212.4190.0

## Steps to Reproduce:

1. Add `NODE_OPTIONS` as a user or system environment variable (it doesn't matter which), with any value.
2. Open VSCode
3. Open a terminal in VSCode
4. `echo` the environment variable as appropriate for the shell.

## Expected Results

The results of the `echo` should show the value of `NODE_OPTIONS`.

## Actual Results

A blank line is printed instead.

## Other Debugging Information

- Tested with Powershell and CMD

- I created a `TEST_ME` environment variable, and the reproduction steps produced the expected result--the value was printed in the terminal.

- I tried to `echo` the `NODE_OPTIONS` _outside_ VSCode (using Windows Terminal), and the value was printed as expected.

- I tried using a different value in `NODE_OPTIONS` (just "test") and the results were the same--a blank line was printed, rather than the value.

- If I set the environment variable in the terminal in VSCode, the value works and persisted for that shell.

**Comment by Tyriar** [comment]
I wouldn't be surprised if NODE_OPTIONS gets dropped along the way as vscode is itself a node app and that could change how it operates. https://github.com/microsoft/vscode/issues/47816 would give you what you want

/duplicate https://github.com/microsoft/vscode/issues/47816

**Comment by TheJim01** [comment]
>  #47816 would give you what you want

Would it though? I read through the comments and--how I read it--#47816 is all about ensuring new env vars get pulled into fresh terminals. The scenario I'm describing here is that one specific environment variable value is _never available_, even after doing all the close/refresh/restart hoop-jumping.

Can there be confirmation that VSCode is actually dropping `NODE_OPTIONS` to ensure its own stability? If it's not, then I'd still consider this a problem.

**Comment by Tyriar** [comment]
> Can there be confirmation that VSCode is actually dropping NODE_OPTIONS to ensure its own stability?

Yes I think this is what's happening. #47816 would fix it as it would be pulling in NODE_OPTIONS from the fresh environment block when the terminal process is created, we don't need to worry about it messing with node/vscode at that point as it's only being used in the shell process.
