### ISSUE TITLE
Commands in Demo are not executing

### ISSUE THREAD

**Issue by idkjs** [Microsoft/vscode#18273]
- VSCode Version: code-insiders 1.9.0
- OS Version: 10.11.6 (15G1212) El Capitan
- Source Materials: <http://code.visualstudio.com/blogs/2017/01/15/connect-nina-e2e#_deploying-your-app>  

Steps to Reproduce:

1. Install azure cli preview with pip
2. run `az login`
3. run `az group create -n nina-demo -l westus`

This produces some sort of syntax error. I got it to work by running `az resource group create -n todo-demo -l westus`. I am guessing the demo is assuming that we have no resource groups created....

Update: Per [SO](https://stackoverflow.com/questions/41531866/using-azure-cli-in-terminal-az-error-argument-for-appservice-plan), am I supposed to add the appservice component before running the az appservice command?
Any ideas? Thank you.

related to https://github.com/Azure/azure-cli/issues/1682

**Comment by lostintangent** [comment]
@idkjs Could you install the [nightly build](https://github.com/Azure/azure-cli#nightly-builds) of the Azure CLI? The "az resource group" command was changed to "az group", which may not have made it to the latest release yet. I just updated the pre-reqs in the tutorial to mention this.

**Comment by lostintangent** [comment]
@idkjs As an aside, we can track this discussion via [this issue](https://github.com/lostintangent/node-e2e-nina2016/issues/3), and [this issue](https://github.com/Azure/azure-cli/issues/1682), since the problem doesn't appear to be related to VS Code. Feel free to close this one if you think that makes sense. Thanks!

**Comment by sandy081** [comment]
This does not looks related to VS Code. Closing this.
