### ISSUE TITLE
Text scribbles in Ubuntu

### ISSUE THREAD

**Issue by kirilllzaitsev** [microsoft/vscode#182723]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version:  1.78.2
- OS Version:  Ubuntu 22.04

Issue description:

On a start page, I have been observing the following for a while (in multiple VScode releases):

![image](https://github.com/microsoft/vscode/assets/44346535/c187cf7d-78dd-40b0-9352-17f57eb094e1)

Previously, very similar scribbles were on the left panel of Settings, but recently it got fixed:

![image](https://github.com/microsoft/vscode/assets/44346535/f23b2ac3-2a58-4009-9a0a-475fe0e32cb9)

Steps to Reproduce:

1. Start the editor

**Comment by rzhao271** [comment]
Does the issue still occur when running with the `--disable-gpu` flag, i.e. `code --disable-gpu`?

**Comment by kirilllzaitsev** [comment]
Yes, 
![image](https://github.com/microsoft/vscode/assets/44346535/17a33f71-350d-4faf-a501-99948a084ec6)

**Comment by deepak1556** [comment]
Merging to https://github.com/microsoft/vscode/issues/174721
