### ISSUE TITLE
highlighting of matching react tags

### ISSUE THREAD

**Issue by franckstifler** [Microsoft/vscode#18278]
- VSCode Version: 1.7.2
- OS Version: Ubuntu 16.04

Steps to Reproduce:

1. Click on the closing tag, all the other tags get highlighted.
![image](https://cloud.githubusercontent.com/assets/11504867/21751816/aa1f8bb0-d5cd-11e6-9228-fba60dfd9bd3.png)

**Comment by aeschli** [comment]
Has to be implemented in the typescript server...

**Comment by aeschli** [comment]
duplicate of https://github.com/Microsoft/TypeScript/issues/10138
