### ISSUE TITLE
Vs code start up very slow. Getting program not responding warning everytime at startup

### ISSUE THREAD

**Issue by k0kumar** [microsoft/vscode#182719]
1. :warning: We have copied additional data to your clipboard. Make sure to **paste** here. :warning:
 Startup Performance:[Startup Performance.txt](https://github.com/microsoft/vscode/files/11494567/Startup.Performance.txt)
 
1. :warning: Make sure to **attach** these files from your *home*-directory: :warning:

-`prof-FIQ0T2kw.main.cpuprofile.txt`
[prof-FIQ0T2kw.main.cpuprofile.txt](https://github.com/microsoft/vscode/files/11494515/prof-FIQ0T2kw.main.cpuprofile.txt)

-`prof-FIQ0T2kw.renderer.cpuprofile.txt`
[prof-FIQ0T2kw.renderer.cpuprofile.txt](https://github.com/microsoft/vscode/files/11494518/prof-FIQ0T2kw.renderer.cpuprofile.txt)

**Comment by gjsjohnmurray** [comment]
Are you using McAfee antivirus? If so please see https://github.com/microsoft/vscode/issues/178962

**Comment by k0kumar** [comment]
Thanks @gjsjohnmurray , was able to fix the problem.
