### ISSUE TITLE
VSCode doesn't response to keyboard input

### ISSUE THREAD

**Issue by jackyzy823** [microsoft/vscode#182740]
Does this issue occur when all extensions are disabled?: Yes/No

Version: 1.78.2 (system setup)
Commit: b3e4e68a0bc097f0ae7907b217c1119af9e03435
Date: 2023-05-10T14:39:26.248Z (6 days ago)
Electron: 22.5.2
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Windows_NT x64 10.0.19045
Sandboxed: Yes

Steps to Reproduce:

1. Use mouse to click `New File` (this time cursor is `hyperlink Icon` which is normal) , then random type something, You can observe that VSCode did not response to the keyboard input and the cursor become `Type Icon` wherever it points at. 
2. (The second half of gif) , Do a windows minimize and maximize, the mouse become normal, however when typing , it go back to step 1.

Some observation:
This situation mostly happens when VSCode running a long time.

![Recording 2023-05-17 at 16 44 22](https://github.com/microsoft/vscode/assets/2900871/9ed74919-c023-42b9-b460-a65003bf95c5)

**Comment by jackyzy823** [comment]
It is weird that VSCode become normal when i try to enabling screencast mode for the recording (Developer: Toggle Screencast Mode in the command palette) to make this issue more clear.

**Comment by jackyzy823** [comment]
> It is weird that VSCode become normal when i try to enabling screencast mode for the recording (Developer: Toggle Screencast Mode in the command palette) to make this issue more clear.

Update: even when i enable  screencast mode  , when encountering this problem , then screencast for keyboard  does not work either. And the red point won't follow mouse after keyboard input.

![Recording 2023-05-18 at 10 10 20](https://github.com/microsoft/vscode/assets/2900871/b9cc5149-d98b-4c3c-b172-066e4b043715)

Some observation:
This situation also sometimes happens after system resuming from sleep.

**Comment by jackyzy823** [comment]
It might be related to #167556

**Comment by deepak1556** [comment]
Do you still experience the issue with latest stable 1.96 ? If so, please capture a perf profile following the steps at https://github.com/microsoft/vscode/wiki/Performance-Issues#profiling-the-renderer-process

**Comment by jackyzy823** [comment]
Hi , I'm sure this is a duplication of #167556 . I'll close this one. Thanks.
