### ISSUE TITLE
Build failure: Generate cache image

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#182720]
https://github.com/microsoft/vscode/actions/runs/4999292341/jobs/8955542308

I have seen this fail often over the days, we should do something about it.

**Comment by chrmarti** [comment]
@Chuxel It looks like `secrets.AZ_ACR_CREDS` might have expired. How is that created?

**Comment by Chuxel** [comment]
@jkeech @samruddhikhandale - I assume creds were rev'd for the devcon ACR, correct? If so, can you help Christof/Ben get updated creds (offline obviously 😂).  vscode-dev-containers may need to be updated as well if this still uses the image published from there.

**Comment by joshspicer** [comment]
👋 Whoever is able to update this secret, feel free to message me on Teams :)
