### ISSUE TITLE
Visual Studio Code Keeps Crashing

### ISSUE THREAD

**Issue by amit-71** [microsoft/vscode#182751]
Type: <b>Bug</b>

It keeps creshing whenever I open the IDE/APP. I am facing the issue from a couple of days. Also it takes unexpectedly more than longer time to open and get crashed with a popup message saying "This window is not responding".

VS Code version: Code 1.78.2 (b3e4e68a0bc097f0ae7907b217c1119af9e03435, 2023-05-10T14:39:26.248Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|12th Gen Intel(R) Core(TM) i7-12700H (20 x 2688)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.63GB (8.91GB free)|
|Process Argv|--crash-reporter-id c709a9f0-c1de-4b3c-b817-ba0f476e4ea5|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
gitlens|eam|13.6.0
code-runner|for|0.12.0
copilot|Git|1.86.82
python|ms-|2023.8.0
vscode-pylance|ms-|2023.5.20
cmake-tools|ms-|1.14.31
cpptools|ms-|1.15.4
cpptools-extension-pack|ms-|1.3.0
cmake|twx|0.0.17

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
3biah626:30602489
pyind779:30671433
f6dab269:30613381
pythonsymbol12:30671437
showlangstatbar:30737416
vsctsb:30705553
azdwalk:30721579
pythonms35:30701012
pythonfmttext:30731395
pythoncmv:30739700
fixshowwlkth:30730052
pythongtdpathcf:30739705

```

</details>

**Comment by gjsjohnmurray** [comment]
Are you using McAfee antivirus? If so please see https://github.com/microsoft/vscode/issues/178962

**Comment by Vollbrecht** [comment]
after updating from 1.78.0 to 1.78.2 its also started to crash for me constantly. Running debian 11. I created a crashdump . I attache the .dmp file in a zip as suggested from https://github.com/Microsoft/vscode/wiki/Native-Crash-Issues 
[dump.zip](https://github.com/microsoft/vscode/files/11500741/dump.zip)

**Comment by gjsjohnmurray** [comment]
> Ok will do, should i remove my other comment than?

I think it's OK to leave it but maybe post a link to the issue you created.
