### ISSUE TITLE
We should show the `DiffReview` by default for screen reader users when `/fix` is used

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#182789]
ATM, users must tab into the editor and invoke `f7` for a nice experience. Even if they were to do this manually, we want to prevent them from going into the underlying diff editors where the audio cues don't work and because navigation in those will be tedious. 

Hack that worked to prevent tab from stopping at those editors, removed the close button which would bring the user back to them, and to focus the `DiffReview`, these hacks worked but aren't ideal/mergeable. 

https://github.com/microsoft/vscode/compare/merogge/enter-diff-review

@jrieken had the idea that this could be accomplished by passing in original/modified `ITextModel` info instead of a `diffEditor` to the `DiffReview`.

It's even more hacky and not working for me, so will wait for @hediet to see if he has any other ideas

https://github.com/microsoft/vscode/compare/merogge/try-other-hack

3rd attempt, slightly less hacky but doesn't fully work because `options.diffReviewOnly` is always `false` somehow

https://github.com/microsoft/vscode/compare/merogge/3

**Comment by Perfecto1noly** [comment]
👌👌👍👋

**Comment by aiday-mar** [comment]
Hi I was wondering what are the verification steps?

**Comment by hediet** [comment]
Just open the inline chat when screenreader mode is enabled and enter an instruction. At the moment this crashes though (https://github.com/microsoft/vscode/issues/188750).

**Comment by Perfecto1noly** [comment]
Verification for this project is by authentic by Microsoft  and Microsoft account through github
