### ISSUE TITLE
Experiment with threading AI into extraction refactorings

### ISSUE THREAD

**Issue by DanielRosenwasser** [microsoft/vscode#182779]
Today, TSServer provides several actions for "extract to function" and "extract to local" for both TypeScript and JavaScript. Currently, TSServer just creates a pre-generated name like `newLocal` or `newFunction` that's sufficiently unique. While this is fine, it would be interesting if we could use a language model to come up with a useful name and calculate a better name while TypeScript itself calculates the refactoring.

In cases where a language model can "confidently" calculate a new name, that name can replace the contents of the automatically-invoked rename for the refactor.

**Comment by spartanatreyu** [comment]
This should be controlled by a setting for sure.

Here are the outcomes I can see with this feature:

- A user refactors some code, likes the AI generated name and decides to use it.
- A user refactors some code and sees the AI generated name, but they want to make a slight tweak to the name.
- A user reactors some code and doesn't want to use the AI generated names at all.
  - Perhaps the user is consistently getting bad suggestions for the particular thing they are trying to do.
  - Perhaps seeing pre-generated names like `newLocal` or `newFunction` is a part of their proofing workflow (with eyeballs, linters, git hooks, or other code analysis tools).
  - The user is against using AI for some other reason

**Comment by zardoy** [comment]
I think TypeScript should try to infer name using common naming conventions at least (such as `use...` or `get...`), just like [vscode-postfix-ts extension](https://github.com/ipatalas/vscode-postfix-ts) does:
<img width="510" src="https://github.com/ipatalas/vscode-postfix-ts/raw/develop/images/infer-names.png">

From my experience it covers ~20% of code and can be useful if AI suggestions are slow, unavailable or a user doesn't want to use the AI generated names at all.

**Comment by robbiespeed** [comment]
Why not instead expose this through an API? So it's not tied to a single technology. It would allow valuable customization to make sure the name conforms to project guidelines, or takes into account various patterns from a given framework. In some cases even allow the name to be inferred statically by the content without AI.

**Comment by so1ve** [comment]
`rust-analyzer` has a `suggest_name` utility: https://github.com/rust-lang/rust-analyzer/blob/426d2842c1f0e5cc5e34bb37c7ac3ee0945f9746/crates/ide-assists/src/utils/suggest_name.rs

**Comment by amunger** [comment]
@DanielRosenwasser - is this the newly added behavior?

![image](https://github.com/microsoft/vscode/assets/2019016/89d8efc6-86ad-49f8-a020-79d0d334e8dc)

**Comment by mjbvz** [comment]
Marking this as an exploration. We'll create test items for the individual features that came out of it
