### ISSUE TITLE
TODO comment that will be saved to a 3rd party reminder service and will notify you later. 

### ISSUE THREAD

**Issue by jofftiquez** [Microsoft/vscode#18275]
- VSCode Version: 1.8.0
- OS Version: Linux Mint Sarah

Steps to Reproduce:

1. Type "TODO" a pop up widget will appear. 
2. Login to a 3rd party service/app to save the "TODO" task. 
3. If logged in, set a reminder time
4. Get notified for the TODO task, with the name of the script where you put it.

**Comment by sandy081** [comment]
@jofftiquez Firstly, I am not sure if I understand what you are trying to report.

And, There is no such feature in Vanilla VS Code. Looks like you have some extension that does it. Please open the issue on the corresponding extension.
