### ISSUE TITLE
Typing in git bash integrated terminal, then backspacing causes glitching and fails to show characters as deleted

### ISSUE THREAD

**Issue by kvoth3** [Microsoft/vscode#18277]
- VSCode Version: 1.8.1
- OS Version: Win10

Steps to Reproduce:

1. Set up git bash and your integrated terminal
2. Ctrl + ` to open it up. Then type anything like "npm install". Next try backspacking to delete some characters and you will notice it might end up with "np" after backspacing all the way. If you press enter you'll see that you indeed deleted the entire command but it just failed to render properly. This happens in extreme frequency, I'd say >95% of the time which makes using the integrated terminal an extremely frustrating experience. 

![image](https://cloud.githubusercontent.com/assets/5633757/21751484/26dae65a-d596-11e6-978c-f46efcdf7a6f.png)

![image](https://i.gyazo.com/cf294567e65ae0d09afdff92610e8051.gif)

![image](https://i.gyazo.com/c516e7a1f634a6549f49609da761e507.gif)

Lastly, this might be related to another issue in which the terminal window loses its position after being resized. I've attached a gif of that as well.

![image](https://i.gyazo.com/4f22c299d7ca8b7123173788ec3ffed7.gif)

**Comment by Tyriar** [comment]
Merging into https://github.com/Microsoft/vscode/issues/14613

The line wrap issue is likely part of the same problem, there is also this issue that looks at preserving the line on resize which could also potentially fix the problem https://github.com/Microsoft/vscode/issues/8336

**Comment by Tyriar** [comment]
This should hopefully be fixed in tomorrow's Insiders build (via https://github.com/Microsoft/vscode/commit/63f1fa66800bf641de5e36027610503ba75085b5). Please let me know if it still reproduces.

See https://github.com/Microsoft/vscode/issues/13625 for more information.

**Comment by kvoth3** [comment]
Typing seems to be working fine with the latest insider's build. However the resizing issue still persists (last gif posted above),
