### ISSUE TITLE
The Intellisense doesn't work properly for predefined variables in launch.json file

### ISSUE THREAD

**Issue by Teassassin** [microsoft/vscode#182700]
Type: <b>Bug</b>

**Expected**:

> version 1.77.3

![image](https://github.com/microsoft/vscode/assets/47493353/592f288d-3375-4141-94e8-d1479f7307f2)

**Actual**:

> version 1.78.2

![image](https://github.com/microsoft/vscode/assets/47493353/c99f12e2-39a7-44c0-bfef-c58139bea29f)

**Steps to Reproduce**:
1. create a launch.json file.
2. add one configuration for any language.
3. edit in ${} block and intellisense doesn't provide proper hints.

**More Info**:
1. this bug is likely related to #181641 and #181615.
2. this bug can be reproduced in 1.79.0-insider.

VS Code version: Code 1.78.2 (b3e4e68a0bc097f0ae7907b217c1119af9e03435, 2023-05-10T14:39:26.248Z)
OS version: Windows_NT x64 10.0.19045
Modes:
Sandboxed: No

**Comment by roblourens** [comment]
Going way back to affa0691f94fa9fff0ff5db2559e3fca960c60af, @joyceerhl this change seems right since the extension has contributions for these languages but the extension doesn't actually activate unless I add explicit activation events. I can't figure out why the auto activation event isn't kicking in?

**Comment by joyceerhl** [comment]
Oh, sorry--we revised the `onLanguage` event to only do auto activation if the extension also contributed a language definition for that language, since otherwise this led to extensions like Python being activated too eagerly. For debug we should restore the explicit activation events too.

**Comment by roblourens** [comment]
I see, thanks
