### ISSUE TITLE
bash: no job control in this shell

### ISSUE THREAD

**Issue by danielHighspot** [microsoft/vscode#182819]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 
- OS Version: 

Steps to Reproduce:

1. click "Attach with rdbg" to debug ruby
2. get the error msg "bash: no job control in this shell"

**Comment by roblourens** [comment]
Please file an issue on the ruby debug extension repo, thanks

**Comment by jdsalaro** [comment]
I'm also experiencing this, I've opened https://github.com/rubyide/vscode-ruby/issues/861 at as suggested by @roblourens
