### ISSUE TITLE
Add a command to close all non-file editors of a group

### ISSUE THREAD

**Issue by vilic** [Microsoft/vscode#18287]
Sometimes I just want to close one pane for a better view diffing files, but it will close all the files opened in that pane. I feel more comfortable with the ancient behavior.

**Comment by vilic** [comment]
@bpasero Hi, I may not have made myself clear. The point is to leave the file opened after its group gets closed, thus I can still find it quickly in the opened files via `Ctrl+P`, and have the editing history kept.

**Comment by bpasero** [comment]
@vilic can you maybe share a screenshot or video of the behaviour you dont like?

**Comment by vilic** [comment]
@bpasero in this demo, after closing a group, the file was closed and editing history was gone. Also, if I have a lot of files to search I have to find it out from a longer list instead of just several opened files.
![2017-01-11_0-32-07](https://cloud.githubusercontent.com/assets/970430/21815015/37ef3494-d796-11e6-9e16-531d5588adae.gif)

**Comment by bpasero** [comment]
@vilic a list of most recently opened editors is always available when you hit Ctrl+P (quick open for files), did you try that?

It is true that undo history is gone when closing an editor, we have a bug for this already.

**Comment by bpasero** [comment]
@vilic no, the recent files have always been in that list, even before introducing tabs. 

I am going to close this as duplicate of https://github.com/Microsoft/vscode/issues/7169
