### ISSUE TITLE
feature: support double Activity Bars.

### ISSUE THREAD

**Issue by Simon-He95** [microsoft/vscode#182836]
There is only one sidebar, which may not be so convenient to use. With the increase of sidebar icons, you may want to put some commonly used ones on one side and put uncommonly used ones on the other side. I hope it can be supported.

**Comment by gjsjohnmurray** [comment]
Your mention of icons makes me wonder if you are asking for two Activity Bars. See https://code.visualstudio.com/docs/getstarted/userinterface for the distinction between Activity Bar and Side Bar.

VS Code already has two Side Bars, one on each side. Out of the box only one is displayed.

**Comment by Simon-He95** [comment]
> Your mention of icons makes me wonder if you are asking for two Activity Bars. See [code.visualstudio.com/docs/getstarted/userinterface](https://code.visualstudio.com/docs/getstarted/userinterface) for the distinction between Activity Bar and Side Bar.
> 
> VS Code already has two Side Bars, one on each side. Out of the box only one is displayed.

<img width="1512" alt="image" src="https://github.com/microsoft/vscode/assets/57086651/88d821af-6683-4fec-9c6a-71ba295cc74d">
I think I should be talking about Activity Bar.
By default, the bar can be placed on the right or left, but I think there is only one side, and the number of icons is too large to be fully displayed. Can both be used at the same time? Independent on both sides, more icons can be placed

**Comment by gjsjohnmurray** [comment]
Have you tried using the Secondary Side Bar yet? It doesn't have an adjacent activity bar, but instead there are icon tabs along its top edge.

In any case I suggest you edit the title of this issue to clarify what it is about.

**Comment by gjsjohnmurray** [comment]
> I think my side bar can't fit more content.

That screenshot shows your Status Bar.

To open the Secondary Side Bar I suggest you open Command Palette and enter "secondary", then pick `View: Toggle Secondary Side Bar Visibility`.

Once the extra side bar has appeared opposite your first, drag one of your Activity Bar icons onto it. Then drag another into its top tab area to create a second tab.

**Comment by Simon-He95** [comment]
oh my god, that's what I want！
This solved my problem, I will close this issue, thank you again。
<img width="1334" alt="image" src="https://github.com/microsoft/vscode/assets/57086651/af98b4c6-b87d-4896-8ee4-61d6a209af85">
