### ISSUE TITLE
Report Issues doesn't work

### ISSUE THREAD

**Issue by Leon99** [Microsoft/vscode#18288]
- VSCode Version: 1.8.1
- OS Version: Windows 10.0.14393

Steps to Reproduce:

1. Press Help - Report Issues (or trigger it via F1)

Result: nothing happens. Nothing shows up in the Dev Tools console.

**Comment by sandy081** [comment]
@Leon99 It works for me in both VS Code stable and insiders version. Can you please try again or try by disabling all extension and provide any helpful information?

Thanks

**Comment by bpasero** [comment]
@Leon99 does it work eventually when you wait long enough? we do some integrity checking before opening a browser and that can take up to 10 seconds or more.

**Comment by Leon99** [comment]
Doesn't work with all extensions disabled either. **Search Feature Requests** works and opens in a browser almost instantly. No workspace opened, I even tried to remove all the user settings with no success.

**Comment by bpasero** [comment]
@Leon99 how about waiting longer?

**Comment by Leon99** [comment]
@bpasero 4 hours now and counting :)

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: http://code.visualstudio.com/Download#insiders

**Comment by Leon99** [comment]
Works fine with 1.9.0-insider.

**Comment by bpasero** [comment]
@Leon99 when you install all the extensions you have in stable to the insiders version, does it then fail again? I still wonder if an extension could cause this. Would also help to know which extension you have installed.

**Comment by Leon99** [comment]
I synced using Shan.code-settings-sync, the Insiders ver was still fine after that. Here is the GIST ID I used: ece838568ac438cee805a66359b6437d
