### ISSUE TITLE
Atomic Design workflow

### ISSUE THREAD

**Issue by emmekkappa** [microsoft/vscode#182864]
Create a workflow between a design software (Illustrator, etc), a prototyping software and VSC to easily implement Atomic Design systems. In the design software, the user should be able to create atoms, molecules, organisms, templates, and pages of a design system that can be opened in the prototyping software and VSC too, to speed up prototyping and development.

This workflow should create CSS, classes etc from the design software file on. The changes should propagate from one software to the other.

For example, if I design a main button in the design software, when I open the file in the prototyping software, it is already a button there too, with the three states ready to be edited. Then, when I open the correspondent file in   @@VSC, I have the HTML/CSS already done for that button and its states.

**Comment by roblourens** [comment]
Sorry, I don't know what Atomic Design is, but this sounds like something that would probably be a job for a vscode extension
