### ISSUE TITLE
Absolute windows links in tsconfig.json not resolved correctly

### ISSUE THREAD

**Issue by mavigozler** [microsoft/vscode#182898]
Type: <b>Bug</b>

I have been having issues with name resolution of symbols (without use of `import`/`export` statements) and while I don't think this reported issue is involved with my name resolution issues, it still seems to be a bug.

When user defines 'references' property with its 'path' property to another path, and the pointing device (mouse) is hovered over active link made and clicked with Ctrl button pressed, it does not open the file and instead, it reports the error in dialog that the file could not be opened because it was not found.

Several efforts were made to get the URL/path correct, even using the "Copy path" with the selected tsconfig.json file, using forward or double-backward slashes for path separator characters. Always an error.

Did search of  opened and closed issues with search 'tsconfig.json references path click' and omitting keywords too, sometimes with "bug" label.
https://github.com/microsoft/vscode/issues?q=tsconfig.json+references+path+click+is%3Aclosed+

VS Code version: Code 1.78.2 (b3e4e68a0bc097f0ae7907b217c1119af9e03435, 2023-05-10T14:39:26.248Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-1035G1 CPU @ 1.00GHz (8 x 1190)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|11.82GB (0.91GB free)|
|Process Argv|--crash-reporter-id 72770bc9-9704-4ad5-8690-6709345d0a89|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (32)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|3.0.2
project-manager|ale|12.7.0
npm-intellisense|chr|1.4.4
gitignore|cod|0.9.0
vscode-markdownlint|Dav|0.50.0
vscode-eslint|dba|2.4.0
githistory|don|0.6.20
gitlens|eam|13.6.0
vscode-html-css|ecm|1.13.1
code-runner|for|0.12.0
vscode-pull-request-github|Git|0.64.0
ftp-simple|hum|0.7.6
compareit|in4|0.0.2
start-git-bash|McC|1.2.1
vscode-language-babel|mgm|0.0.39
git-graph|mhu|1.30.0
csharp|ms-|1.25.7
vscode-edge-devtools|ms-|2.1.1
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-slideshow|ms-|0.1.5
notepadplusplus-keybindings|ms-|1.0.7
powershell|ms-|2023.5.0
debugger-for-edge|msj|1.0.15
deepdark-material|Nim|3.3.0
vscode-jest|Ort|5.2.3
binary-viewer|Qia|1.1.1
LiveServer|rit|5.7.9
errorlens|use|3.11.0
vscode-icons|vsc|12.4.0
vscode-todo-highlight|way|1.0.5
markdown-all-in-one|yzh|3.5.1
vscode-open-in-github|ziy|1.3.6

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
vscccc:30610679
3biah626:30602489
pyind779:30671433
f6dab269:30613381
pythonsymbol12:30671437
showlangstatbar:30737416
vsccsb:30705552
azdwalk:30721579
pythonms35:30701012
pythonfmttext:30731395
pythoncmv:30739700
fixhidewlkth:30730051
hidesbindicator:30730055
pythongtdpath:30739704

```

</details>

**Comment by mavigozler** [comment]
To give the minimal example, I did the following:

1. Created the path "C:/MyProjects/MyApp" anew, representing a web app project
2. I opened VSC, and used Open Folder to open that path. In the terminal, on the command line, I initialized a `tsconfig.json` setup: 'tsc --init'. I also initialized a NodeJS setup: 'npm init'. With VSC, I created an empty 'app1.ts' file under `MyApps` folder.
3. Outside of VSC, created the path "D:/dev/GenLib", representing a repository for library files with utility functions, modules. With VSC, repeated the process to initialize the folder with typescript and nodeJS, and to add an empty file 'lib1.ts' in `GenLib` folder.
The workspace is imaged.

![image](https://github.com/microsoft/vscode/assets/49463960/80cef372-6e9f-436a-b480-3cfa3bc34aef)

4. I then set the properties of the 'tsconfig.json' files under the app and lib folders to approximate the real two `tsconfig.json` files I was working with.
5. In the `tsconfig.json` in `MyApp` folder, I set `references.path` to any of the following: `D:\\dev\\GenLib`, `D:/dev/GenLib`, `D:\\dev\\GenLib\\tsconfig.json`, `D:/dev/GenLib/tsconfig.json`. A link is sensed in all cases, and using the 'Ctrl + click' action always results in a file not found error dialog, with offer to create the file.

The uncommented settings of both associated `tsconfig.json` files are given below:

C:/MyProjects/MyApp/tsconfig.json
```JSON
{
  "compilerOptions": {
    "composite": true,
    "target": "ES2020",
    "lib": ["ES2017", "DOM", "DOM.Iterable"],
    "module": "ESNext",
    "moduleResolution": "node",
    "sourceMap": true,
    "outDir": "./transpiled",
    "importHelpers": true,
    "esModuleInterop": true,
    "forceConsistentCasingInFileNames": true,
    "strict": true,
  },
  "include": [
    "./src/**/*"
  ],
  "references": [
    { "path": "D:\\dev\\GenLib\\tsconfig.json" }
  ]
}
```

D:/dev/GenLib/tsconfig.json
```JSON
{
  "compilerOptions": {
    "composite": true,
    "target": "ESNext",
    "module": "commonjs",
    "rootDir": "D:/dev/GenLib",
    "allowJs": true,
    "esModuleInterop": true,
    "forceConsistentCasingInFileNames": true,
    "strict": true,
    "skipLibCheck": true
  },
  "files": [
    "./src/lib1.ts"
  ],
  "extends": "C:\\MyProjects\\MyApp\\tsconfig.json"
}
```

Note 1: these settings were attempted to overcome TSC build errors related to source files needing to have a common root path, and using `references` and `rootDirs` to avoid this error, and the objective of this was to ensure that source files of modules/libraries/support code remain in one place, rather than copies of them scattered into separate project folder hierarchies, since changes to script files that are dependencies for many projects are/were thought to benefit all projects for which they are dependencies. If the settings don't make sense, it was because of a lot of trial and error to see what would work. While the TSC build action might produce errors (and no actual build process is required to demonstrate the error), it should not affect VSC detecting a link that actually exists but reports the link is not found (on the click), when it should be.

Note 2: I have checked the TypeScript handbook on the use of the `references.path` property to see for any warnings, FYIs, caveats on the path I used (construction of a URL or filesystem path), and could find nothing that explained that using the path as I did was not how to use it. Maybe I missed something.

**Comment by joyceerhl** [comment]
This still repros for me

> In the tsconfig.json in MyApp folder, I set references.path to any of the following: D:\\dev\\GenLib, D:/dev/GenLib, D:\\dev\\GenLib\\tsconfig.json, D:/dev/GenLib/tsconfig.json. A link is sensed in all cases, and using the 'Ctrl + click' action always results in a file not found error dialog, with offer to create the file.

If I open the tsconfig.json in MyApp and try to ctrl+click into the `references.path` link, I still get an error 
![image](https://github.com/microsoft/vscode/assets/30305945/0e5d03b3-869e-4055-a7a0-6d4510ca02b3)
