### ISSUE TITLE
Support "infinite" scrollback in the terminal

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#182876]
I have seen several times now where users want to use a very large number for scrollback to ensure they see everything like in https://github.com/microsoft/vscode/issues/181081. It's not clear to users the exact impact of this which currently pre-allocates memory for `cols * viewport_height * scrollback *` cells, each of which takes approximately 4 bytes (with some more overhead for tracking lines).

We could simplify this by either supporting a -1 value and/or after some threshold like 5000, lazily pushing content that exceeds the threshold to a file/storage service on an idle frame, where it's available if the user needs to scroll up. This would need some commits to xterm.js to handle this type of buffer virtualization.

**Comment by amelvil2-ford** [comment]
It sounds like the vscode integrated terminal isn't a good fit for what I need to do right now.
- It is true that I could work around this by manually copying important old output to my notes, but sometimes I don't catch important output before it scrolls out of the terminal
- Unfortunately, nearly every time I try to use vscode for a more major deep dive, I find that something I wanted to read got "scrolled out of memory" with the default settings
- Unfortunately, I don't know in advance whether what I'm doing is going to be "one of those major deep dives" 
- Then I have to reproduce a weird condition again that scrolled out of memory, which might be hard to do
- I can set the scrollback size to something large like 150k but it sounds like that caused performance issues from what's mentioned in the linked issue
- My OS terminals support unlimited scrollback, I could find/make an extension that makes them easier to start with less clicks
- I'd rather use the integrated terminal with vscode sometimes, so I don't have to manage so many IDE and terminal windows

I know the vscode team doesn't want to prioritize this, but would the team be open to a PR for this, if I find a clean way to do this?
