### ISSUE TITLE
Inline suggest "Always Show Toolbar" doesn't work

### ISSUE THREAD

**Issue by digitarald** [microsoft/vscode#182830]
Type: <b>Bug</b>

Clicking _Always Show Toolbar_ causes the toolbar to never show again. The worst part, once its gone there no obvious way to get it back.

STR: Select the option.
ER: Toolbar always shows up.
AR: Toolbar never shows.

I experienced this and it just happened to another Build demo-er who was really excited to always get the toolbar for demos.

<img width="593" alt="image" src="https://github.com/microsoft/vscode/assets/8599/1d6dc5d1-6d8d-4b16-b86b-2ad2515f7b8f">

VS Code version: Code - Insiders 1.79.0-insider (f1258a5fbed44b8f84a097c73c1799c13c5c3646, 2023-05-17T05:27:27.525Z)
OS version: Darwin x64 22.4.0
Modes:
Remote OS version: Linux x64 5.4.0-1106-azure

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|64.00GB (0.20GB free)|
|Process Argv|--enable-proposed-api digitarald.chat-ai-plugins --log trace --crash-reporter-id 4cf0a6f0-aaf8-4da3-9b2b-81f6c639c12b|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|Codespaces|
|OS|Linux x64 5.4.0-1106-azure|
|CPUs|Intel(R) Xeon(R) Platinum 8370C CPU @ 2.80GHz (8 x 2793)|
|Memory (System)|15.63GB (12.02GB free)|
|VM|0%|
</details><details><summary>Extensions (46)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
Bookmarks|ale|13.3.1
tsl-problem-matcher|amo|0.6.2
emojisense|bie|0.9.1
esbuild-problem-matchers|con|0.0.2
kusto|don|0.4.3
auto-close-tag|for|0.5.14
codespaces|Git|1.14.7
remotehub|Git|0.57.2023051001
debug-tracker-vscode|mcu|0.0.15
theme-monokai-pro-vscode|mon|1.2.1
jupyter-keymap|ms-|1.1.0
remote-containers|ms-|0.293.0
remote-ssh|ms-|0.103.2023051015
remote-ssh-edit|ms-|0.86.0
remote-wsl|ms-|0.78.5
azure-repos|ms-|0.33.2023051001
remote-repositories|ms-|0.34.0
remote-server|ms-|1.2.2023051509
particle-vscode-snippets|par|1.16.0
fugio|Tyl|0.0.1
vscode-eslint|dba|2.4.0
prettier-vscode|esb|9.12.0
codespaces|Git|1.14.7
copilot-chat|Git|0.1.2023051701
copilot-nightly|Git|1.86.102
vscode-github-actions|git|0.25.7
vscode-pull-request-github|Git|0.64.0
azure-dev|ms-|0.5.0
vscode-azureappservice|ms-|0.24.9
vscode-azurecontainerapps|ms-|0.5.1
vscode-azurefunctions|ms-|1.10.7
vscode-azureresourcegroups|ms-|0.7.3
vscode-azurestaticwebapps|ms-|0.12.1
vscode-azurestorage|ms-|0.15.2
vscode-azurevirtualmachines|ms-|0.6.5
vscode-bicep|ms-|0.17.1
vscode-cosmosdb|ms-|0.19.4
vscode-docker|ms-|1.25.1
vscode-dotnet-runtime|ms-|1.6.0
black-formatter|ms-|2023.2.0
python|ms-|2023.8.0
vscode-pylance|ms-|2023.5.30
azure-account|ms-|0.11.5
azurecli|ms-|0.5.0
vscode-node-azure-pack|ms-|1.2.0

(2 theme extensions excluded)

</details>

**Comment by muneebshahid** [comment]
I had the same issue.  I had to open up settings.json for my user and delete the line `"editor.inlineSuggest.showToolbar": "always",`  to get the toolbar back.
