### ISSUE TITLE
Task not found if same definition already exists

### ISSUE THREAD

**Issue by rubensa** [microsoft/vscode#182871]
Comes from [here](https://github.com/microsoft/vscode-docker/issues/3937#issuecomment-1553100759) and that from [here](https://github.com/microsoft/vscode-java-test/issues/1557).

I'm checking a new pre-release version (`0.38.2023051002`) of [Test Runner for Java](https://github.com/microsoft/vscode-java-test) extension that includes support for [postDebugTask](https://github.com/microsoft/vscode-java-test/issues/1557) property.

Trying to run a [docker-compose](https://code.visualstudio.com/docs/containers/reference#_compose-task-reference) type task after a test run I found that the specified task can't be found if the task definition (except for the **label**) is the same for other existing task (more detail [here](https://github.com/microsoft/vscode-java-test/issues/1557#issuecomment-1541920533)).

Should it be possible that an "optimization" (or something) is been done for **docker-compose** task definitions that prevents duplicates?

Does this issue occur when all extensions are disabled?: Couldn't check this without extensions

- VS Code Version: 
```
Version: 1.78.2
Commit: b3e4e68a0bc097f0ae7907b217c1119af9e03435
Date: 2023-05-10T14:47:05.613Z
Electron: 22.5.2
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Linux x64 5.19.0-41-generic
Sandboxed: No
```
- OS Version: 
```
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.2 LTS
Release:	22.04
Codename:	jammy
```

Steps to Reproduce:

1. The relevant info is provided [here](https://github.com/microsoft/vscode-java-test/issues/1557#issuecomment-1541429757).
2. An [here](https://github.com/microsoft/vscode-java-test/issues/1557#issuecomment-1541920533) there is extra info about how, based on the `type` of task, the problem appears or not.

Looks like this [might have been identified previously](https://github.com/microsoft/vscode-docker/issues/3937#issuecomment-1542511382) but I can't find any information about that.

Other issues that might be related to this one:
- [Visual Studio Code launch can't find custom prelaunch task](https://github.com/microsoft/vscode/issues/157957)

**Comment by rubensa** [comment]
Just downloaded latest insiders build (right now):
```
Version: 1.79.0-insider
Commit: 2946b1ee55db1d406526d3fd1df49250b2f8322d
Date: 2023-05-18T05:26:08.467Z
Electron: 22.5.2
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Linux x64 5.19.0-41-generic
```
Checked again but the result is the same: `Could not find the task 'Teardown test-local'.`

**Comment by meganrogge** [comment]
Thanks for the info. Given the finding here, https://github.com/microsoft/vscode-java-test/issues/1557#issuecomment-1541920533, this seems like an issue with the docker extension, not VS Code, thus closing.
