### ISSUE TITLE
Typescript breakpoints don't work on file imported with "import let = require("./file")"

### ISSUE THREAD

**Issue by drew-y** [Microsoft/vscode#18285]
- VSCode Version: 1.8.1
- OS Version: macOS 10.12.2

Steps to Reproduce:

1. Create a file index.ts
2. Create another file server.ts and export a fucntion with `export =` and set various breakpoints in the function
3. Back in index.ts import the function from server.ts using `import let = require("./server.ts")`
4. With source maps enabled (and generated by tsc) launch the debugger using index.ts as the program

Breakpoints work in all files except server.ts

**Comment by weinand** [comment]
- what is you project structure?  (which folders and where does the generated JavaScript and source maps live?) 
- how does the source map for server.js look like?
- what is in your launch config?

**Comment by drew-y** [comment]
It's been awhile since I've ran into this issue. I can't seem to reproduce it anymore. I'm not sure if it was fixed in the meantime or I was doing something wrong. Sorry for the lack of info in the original post.

**Comment by weinand** [comment]
Thanks for the update!
