### ISSUE TITLE
GitHub pushing stops pushing automatically

### ISSUE THREAD

**Issue by DanJ210** [Microsoft/vscode#18283]
- VSCode Version: Code 1.8.1 (ee428b0eead68bf0fb99ab5fdc4439be227b6281, 2016-12-19T14:49:23.350Z)
- OS Version: Windows_NT ia32 10.0.14986
- Extensions:

|Extension|Author|Version|
|---|---|---|
|vscode-css-formatter|aeschli|0.0.2|
|vs-code-css-comments|ashhitch|1.0.2|
|vscode-icontheme-nomo-dark|be5invis|1.2.4|
|javadebugger|donjayamanne|0.0.2|
|python|donjayamanne|0.5.1|
|vscode-html-css|ecmel|0.0.32|
|javac-linter|faustinoaq|1.2.1|
|php-intellisense|felixfbecker|0.0.12|
|auto-close-tag|formulahendry|0.3.8|
|auto-rename-tag|formulahendry|0.0.11|
|code-runner|formulahendry|0.6.5|
|csharpextensions|jchannon|1.1.0|
|format-indent|Kasik96|1.3.0|
|format-php|Kasik96|1.1.2|
|ftp-sync|lukasz-wronski|0.3.2|
|cpptools|ms-vscode|0.9.3|
|csharp|ms-vscode|1.6.2|
|theme-railscasts|PaulOlteanu|1.0.0|
|material-icon-theme|PKief|1.2.0|
|vscode-icons|robertohuertasm|5.0.0|
|elise|schematrix|0.0.1|
|theme-tinaciousdesign|tinaciousdesign|0.1.1|

---

Steps to Reproduce:

1. Pushing to a GitHub repository was automatic
2. No longer automatic, I must manually "git push" in terminal

I'm still new so I'm sorry if I'm not helping at all. But at first when I would connect a GitHub repository, my changes would get uploaded automatically. Now when I hit the check mark to update changes, it doesn't happen automatically. I changed nothing so is this something that is supposed to happen or did I change this? Am I too of a newbie to be posting this or is this a legit thing to post?

**Comment by joaomoreno** [comment]
VS Code never uploads changes automatically. That could've been an extension which did that to you.

**Comment by DanJ210** [comment]
Soooo do you want to tell me how to find out what would have to be changed by an extension @joaomoreno ? FYI, I barely have any extensions, icons, theme and language support... This started happening a week or two ago after I installed my last extensions months ago during school fall semester. So does that make sense?

**Comment by joaomoreno** [comment]
What I mean is: Code does not have any feature which will push your code automatically. Something else in your machine was doing that. And either the same thing or another one stopped that behaviour from working.
