### ISSUE TITLE
format  when  if  switch exists

### ISSUE THREAD

**Issue by yuxing1994** [Microsoft/vscode#18289]
- VSCode Version: Code 1.8.1 (ee428b0eead68bf0fb99ab5fdc4439be227b6281, 2016-12-19T14:42:49.304Z)
- OS Version: Darwin x64 15.5.0
- Extensions:

|Extension|Author|Version|
|---|---|---|
|beautify|HookyQR|0.7.3|
|crane|HvyIndustries|0.2.2|
|format-php|Kasik96|1.1.2|
|theme-setimonokai|SmukkeKim|0.0.1|
|alignment|annsk|0.3.0|
|path-intellisense|christian-kohler|1.2.0|
|vscode-html-css|ecmel|0.0.32|
|Theme-Trepid|enkrypt|0.0.1|
|text-transform|florianloch|0.1.0|
|auto-rename-tag|formulahendry|0.0.11|
|vscode-phpfmt|guodf|0.0.4|
|theme-material-theme|jprestidge|1.0.1|
|theme-chromodynamics|lei|1.0.8|
|Theme-MaterialKit|ms-vscode|0.1.1|
|vscode-icons|robertohuertasm|4.3.0|
|clang-format|xaver|1.0.0|

---

Steps to Reproduce:

1.
2.

**Comment by sandy081** [comment]
@yuxing1994 Issue summary and description is not complete. Can you please provide 
- What is the issue
- How to reproduce it
- If possible some samples

Thanks
