### ISSUE TITLE
Intellisense for doesn't work for extended method

### ISSUE THREAD

**Issue by UnderNotic** [Microsoft/vscode#18281]
- VSCode Version:  1.8.1
- OS Version: Windows 10

Steps to Reproduce:
![image](https://cloud.githubusercontent.com/assets/6854701/21753566/f6615284-d5ef-11e6-8270-c79106b6882d.png)

**Comment by waderyan** [comment]
@UnderNotic thanks for opening this issue. Can you do the following? 

1. Share code that we can copy and paste or clone to reproduce on our own machine. 
2. Share what extensions you have installed
3. Run the code with all [extensions disabled](https://code.visualstudio.com/docs/editor/extension-gallery#_disable-an-extension). 

Please see the guidelines in our [Contribution doc](https://github.com/Microsoft/vscode/wiki/How-to-Contribute).

**Comment by UnderNotic** [comment]
1. `import React, { Component } from 'react';

export default class App extends Component {
  render() {
    return (
      <h1>hello, world.</h1>
    );
  }
  componentWillMount() {
    console.log('component will mount');
  }
  componentWillReceiveProps() {
    console.log('Will receive props');
  }
  shouldCom
}
`
2. Extensions:
![image](https://cloud.githubusercontent.com/assets/6854701/21775297/ce956df2-d695-11e6-8829-0866b6cd8e76.png)

3. Disabling all extension didn't fix this.

**Comment by waderyan** [comment]
@UnderNotic thanks for sharing. 

@mjbvz this is strange... can you take a look? 

I don't seem to be getting anything relevant. We're displaying from TypeScript correctly. Should we move this to tsserver? 

![image](https://cloud.githubusercontent.com/assets/2449568/21776942/b564715a-d651-11e6-8afe-eaec2b5ec461.png)

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript#13372
