### ISSUE TITLE
creat a file manually need to wait for a long time

### ISSUE THREAD

**Issue by gogogofuture** [Microsoft/vscode#18286]
- VSCode Version: Code 1.8.1 (ee428b0eead68bf0fb99ab5fdc4439be227b6281, 2016-12-19T14:49:23.350Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions:

|Extension|Author|Version|
|---|---|---|

---

Steps to Reproduce:

1.via vscode terminal or  new a  file manually in explorer ...eg: npm, there is not fount in vscode's directort immediately, i need to wait for a long time
2.

**Comment by sandy081** [comment]
@gogogofuture I am not sure if I understand the steps. Can you please help us in understanding how to reproduce this?

Thanks

**Comment by dbaeumer** [comment]
@gogogofuture without better steps on how to reproduce this we are not able to work on this issue. Closing. We will reopen when better steps are provided.
