### ISSUE TITLE
Problem when you open file directly ..

### ISSUE THREAD

**Issue by a0m0rajab** [Microsoft/vscode#18280]
- VSCode Version: Code 1.8.1 (ee428b0eead68bf0fb99ab5fdc4439be227b6281, 2016-12-19T14:49:23.350Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

|Extension|Author|Version|
|---|---|---|
|vscode-npm-script|eg2|0.1.6|
|cpptools|ms-vscode|0.9.3|

---

when you open a direct c file , it dont save the changes on main file sand sometimes odnt accpet to open it ... it doesnot come to explorer  , so we cant open it , its #$%#%

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: http://code.visualstudio.com/Download#insiders

**Comment by mjbvz** [comment]
Closing as we need more information and repo  steps to investigate this.
