### ISSUE TITLE
Cannot debug pytest tests in docker

### ISSUE THREAD

**Issue by ilaner** [microsoft/vscode#182879]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.78.2
- OS Version: Darwin x64 22.4.0

I'm trying to debug pytest tests inside Docker. I understand it's not supported by the Python VSCode extension yet, but I followed this [guide](https://code.visualstudio.com/docs/containers/debug-common) to setup this.

My tasks.json file:
```
{
    "version": "2.0.0",
    "tasks": [
      {
        "type": "docker-run",
        "label": "docker-run: test",
        "python":{ 
          "module": "pytest",
          "args": ["."],
        },
        "platform": "python",
        "dockerRun": {
            "image": "<my-image-tag>",
            "volumes": [
                {
                    "localPath": "${workspaceFolder}",
                    "containerPath": "/app"
                    
                },
            ],

          }

      }
    ]
  }
```
My launch.json file:
```
{
  "version": "2.0.0",
  "configurations": [
    {
      "name": "Docker: Debug tests in docker",
      "type": "docker",
      "request": "launch",
      "preLaunchTask": "docker-run: test",
      "python": {
        "pathMappings": [
          {
            "localRoot": "${workspaceFolder}",
            "remoteRoot": "/app"
          }
        ],
        "projectType": "general",
        "justMyCode": false,

      }
    }
  ]
}
```

If I hit **Debug and Run**, all the tests are running, but it doesn't stop on VSCode breakpoints. I tried using the `-k` argument for specific test, but it still doesn't work. However, I'm able to debug the `pytest` internal module, but not my code. In addition, I can debug properly regular python files as expected.
Steps to Reproduce:

1. Set the tasks.json and launch.json to .vscode directory.
2. Set breakpoints on the test
3. The test fail/pass, but without entering the breakpoint

**Comment by roblourens** [comment]
Please file this on the repo for the docker extension that you're using for debugging, thanks
