### ISSUE TITLE
fetchTasks() is hanging on multifolder workspace with virtual FS provider

### ISSUE THREAD

**Issue by elaskavaia** [microsoft/vscode#182875]
Reproducible without extensions: Yes (only extension is one demonstrating the issue)

--- PLATFORM ---
LSB Version:    core-11.1.0ubuntu2-noarch:security-11.1.0ubuntu2-noarch
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.6 LTS
Release:        20.04
Codename:       focal
--- VSCODE ---
1.78.2
b3e4e68a0bc097f0ae7907b217c1119af9e03435
x64
--- VSCODE EXTENSIONS ---
vscode-samples-mod.vscode-memfs@0.0.3

Description:

Fetch tasks is forever hanging when virtual fs folder exists in multi-folder workspace
NOTE: this is not bug about sample project - I can reproduce it with ANY virtual file system contributions, this is just a minimal example

Steps to Reproduce:

1.  Use same code from memFS sample - modify code so it possible to mount the virtual fs as secondary folder in multi-folder workspace (remove "when" condition from memfs.workspaceInit command) https://github.com/microsoft/vscode-extension-samples/blob/main/fsprovider-sample/README.md
2. Build and create vsix file and install this sample into code (or same effect if launch this project in debugger). Or use attached pre-built version
3. Open vscode without any workspace
4. Add any "empty" folder to workspace - will result in multi-folder workspace with one folder
5. Execute "Setup Workspace" command which will add another virtual folder
6. Run "Run Build Task" command (Ctrl-Shift-B)

It hangs
Note it also hangs if I run fetchTasks() programmatically

![Screenshot from 2023-05-18 10-34-44](https://github.com/microsoft/vscode/assets/12936066/40c57e33-4158-4c78-8ec0-c0d821337e5c)

Also attaching vsix file of memfs modified extension for reference (vsix in the zip file)
[vscode-memfs-0.0.3.zip](https://github.com/microsoft/vscode/files/11508808/vscode-memfs-0.0.3.zip)

Nothing useful in the log only relevant record
2023-05-18 11:05:09.709 [warning] No search provider registered for scheme: memfs. Another scheme has a provider, not waiting for memfs

**Comment by elaskavaia** [comment]
Update: I cannot reproduce this issue if running in debugger using latest vscode code from git. Either its fixed or some other environmental issues that makes it behavior different. Note this is big issue for us currently because building simply does not work if any virtual workspace folder is used  (i.e sshfs, etc)

**Comment by elaskavaia** [comment]
Apparently don't even need to install the provider, can reproduce with non-existing provider
This is workspace file:
```
{
        "folders": [
                {
                        "name": "MemFS - Sample",
                        "uri": "memfs:/"
                },
                {
                        "path": "emptyFake"
                }
        ]
}
```

**Comment by elaskavaia** [comment]
Update: it does not hang on 1.79 however there is still timeout of 5 seconds and vscode.tasks.fetchTasks() takes 5 seconds (on empty workspace above)

**Comment by meganrogge** [comment]
Thanks for the info, I believe that we always wait to resolve tasks for a maximum of 5 seconds, so that is expected, and I believe this can be closed.
