### ISSUE TITLE
For compare function add ability to DnD for file`s content into editor

### ISSUE THREAD

**Issue by psnet** [microsoft/vscode#182807]
![зображення](https://github.com/microsoft/vscode/assets/1023918/031a9252-e145-4cff-b9b3-ef90efe525a9)

Add ability to put contents of file using DnD to editor:

![зображення](https://github.com/microsoft/vscode/assets/1023918/cf2ed67d-62e7-4a1e-88c2-ca3d36c11c32)

Now if you press `shift` it puts path of file into editor

![зображення](https://github.com/microsoft/vscode/assets/1023918/84c36a92-9fe9-40a5-af94-95374021c960)

**Comment by mjbvz** [comment]
I personally would never use this feature. We also have drop to open and drop into, so I am not in favor of adding another way of dropping content without a very good use case

**Comment by psnet** [comment]
This is not about usage or not, this is basic fundamental feature that exists in many other IDEs: side-by-side diff for texts

**Comment by mjbvz** [comment]
>  side-by-side diff for texts

yes and there are ways to do that already without dnd

**Comment by psnet** [comment]
ok, how to do this: one file from this project / git, one from another, I need compare them

**Comment by mjbvz** [comment]
If both files are in the same project, select both in the explorer and use `compare selected`. Otherwise, you can use one of the `Compare active file...` commands, like `compare active file with clipboard`

Maybe we could add another way to compare files if there's a need, but DND doesn't seem like the correct UX

**Comment by psnet** [comment]
Its first thing you think about to compare, DnD needed and is used in other also well-known IDE. 

year ago when I [requested this feature](https://github.com/microsoft/vscode/issues/151854) answer was also "it doesnt actual", but as we see it is added

**Comment by hediet** [comment]
> This is not about usage or not, this is basic fundamental feature that exists in many other IDEs: side-by-side diff for texts

@psnet just for future reference, can you do research which editors/IDEs support this?

**Comment by psnet** [comment]
Full research dont have time, but exactly IntelliJ products have this functionality. Open command "open new diff window" and you will see side-by-side windows both accept DnD files into each side for comparison
