### ISSUE TITLE
VSCode keyboard shortcut for 'Assign expression result to new local variable'?

### ISSUE THREAD

**Issue by WangJincheng4869** [microsoft/vscode#182825]
In IDEA, there's this really handy shortcut, mapped to + + by default, which works when an expression is selected. What it does is to create a new local variable to hold the result of the expression. For example... `CTRL + ALT + V`
```
this.doSomeCalculation();
```
If the mouse cursor is positioned over the line above, + + will turn the line into... `CTRL + ALT + V`
```
double someCalculation = this.doSomeCalculation()
```
I find myself using this shortcut a lot when coding Java. Is there something similar available for editing Typescript in Visual Studio Code?

**Comment by mjbvz** [comment]
This should already be possible to confine, see: https://code.visualstudio.com/docs/editor/refactoring#_keybindings-for-code-actions

I use:

```
	{
		"key": "ctrl+shift+e",
		"command": "editor.action.refactor",
		"args": {
			"kind": "refactor.extract",
			"preferred": true,
			"apply": "ifSingle"
		}
	},
```

**Comment by WangJincheng4869** [comment]
> editor.action.refactor

这个在哪设置？找不到啊！
