### ISSUE TITLE
Word Wrap Not Working

### ISSUE THREAD

**Issue by cliffhays** [microsoft/vscode#182868]
Type: <b>Bug</b>

On MacBook pro in VSCode, even with "editor.wordWrap": "on", in my settings.json, every time I open a file if I want word wrap I have to press Option+Z. I've tried toggling the setting, restarting VSCode, even turning accessibilitySupport off. Nothing seems to work. This is my only complaint with VSCode. Otherwise it's an amazing program. Thanks in advance.

VS Code version: Code 1.78.2 (Universal) (b3e4e68a0bc097f0ae7907b217c1119af9e03435, 2023-05-10T14:44:45.204Z)
OS version: Darwin x64 22.4.0
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz (16 x 2300)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|2, 2, 4|
|Memory (System)|16.00GB (0.08GB free)|
|Process Argv|. --crash-reporter-id 4c24ed21-e25f-4d42-975f-1a14b583f482|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
VS-code-drupal|mar|0.0.12
twig-language|mbl|0.9.2
php-debug|xde|1.32.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vscaat:30438848
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
vsccc:30610678
2e4cg342:30602488
pyind779:30671433
f6dab269:30613381
pythonsymbol12:30671437
a9j8j154:30646983
showlangstatbar:30737416
vsccsb:30705552
azdwalk:30721579
pythonms35:30701012
pythonfmttext:30731395
pythoncmv:30739700
fixshowwlkth:30730052
showsbindicator:30730056
pythongtdpath:30739704

```

</details>

**Comment by SRNissen** [comment]
It's been A While, but if you haven't seen this fixed yet, I have a number of suggestions for what might be causing it (if you *have* seen it fixed, hey, good)

- Do you have some kind of one-way settings sync such that a different machine overrides the settings on this one?
- Do you have workspace-specific settings that override your desired word wrap on opening the workspace(s) where you see this?
- Is your wrap set to "wordWrapColumn" rather than "on" and your viewport is narrower than your column bound?

**Comment by Yoyokrazy** [comment]
Could you please reply if the bug has been resolved, or if it is still present in the latest version of vscode (1.96.2), thanks.
