### ISSUE TITLE
JavaScript (Extension) Debugger inconsistent display of strings with escaped characters

### ISSUE THREAD

**Issue by rioj7** [microsoft/vscode#182835]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version:  1.75 insiders
- OS Version: Windows 8.1

Steps to Reproduce:

Create an extension that has a command with the following lines:

```javascript
let line = document.lineAt(0);
let text = line.text;
let numChar = text.length;
```

1. Set a breakpoint on the line with `numChar`
1. start debugging the extension
1. create a JavaScript file with the content:
    ```javascript
    let b = "Hello \"//programmer\"";
    ```
1. execute the command with the breakpoint

If the string variable is displayed with `'` the correct display is: `'let b = "Hello \\"//programmer\\"";'`

If the string variable is displayed with `"` the correct display is: `"let b = \"Hello \\\"//programmer\\\"\";"`
### Debug console

Summary of `line` and `text` are **incorrect**

```none
-> line
 v C {a: 0, b: 'let b = "Hello \"//programmer\"";', c: true}
      a: 0
      b: 'let b = "Hello \\"//programmer\\"";'
      c: true
-> text
   'let b = "Hello \"//programmer\"";'
-> console.log(text);
   let b = "Hello \"//programmer\"";
   undefined
```

### Hover over variable in editor
`line` (**correct**)
```none
C {a: 0, b: 'let b = "Hello \\"//programmer\\"";', c: true}
   a: 0
   b: 'let b = "Hello \\"//programmer\\"";'
   c: true
```

`text` (**correct**)
```none
'let b = "Hello \\"//programmer\\"";'
```

### Debugger Variables View

Summary of `line` and `text` are **incorrect**

```none
line: C {a: 0, b: 'let b = "Hello \"//programmer\"";', c: true}
   a: 0
   b: 'let b = "Hello \\"//programmer\\"";'
   c: true

text: 'let b = "Hello \"//programmer\"";'
```

### Copy Value

`line` (**correct**)
```none
{
  a: 0,
  b: "let b = \"Hello \\\"//programmer\\\"\";",
  c: true,
}
```

`text` (**correct**)
```none
"let b = \"Hello \\\"//programmer\\\"\";"
```

----

## VSC 1.62.2

Using VSC 1.62.2 only the Debug Console was incorrect

### Debug console

Summary of `line` and `text` are **incorrect**

```none
-> line
 v p {_line: 0, _text: 'let b = "Hello \"//programmer\"";', _isLastLine: true}
      _isLastLine: true
      _line: 0
      _text: 'let b = "Hello \\"//programmer\\"";'
-> text
   'let b = "Hello \"//programmer\"";'
-> console.log(text);
   let b = "Hello \"//programmer\"";
   undefined
```

### Hover over variable in editor
`line`  (**correct**)
```none
p {_line: 0, _text: 'let b = "Hello \\"//programmer\\"";', _isLastLine: true}
  _isLastLine: true
  _line: 0
  _text: 'let b = "Hello \\"//programmer\\"";'
```

`text` (**correct**)
```none
'let b = "Hello \\"//programmer\\"";'
```

### Debugger Variables View

**correct**

```none
line: p {_line: 0, _text: 'let b = "Hello \\"//programmer\\"";', _isLastLine: true}
  _isLastLine: true
  _line: 0
  _text: 'let b = "Hello \\"//programmer\\"";'

text: 'let b = "Hello \\"//programmer\\"";'
```

### Copy Value of

`text` (**correct**)
```none
"let b = \"Hello \\\"//programmer\\\"\";"
```

`line` (**correct**)
```none
{
  _line: 0,
  _text: "let b = \"Hello \\\"//programmer\\\"\";",
  _isLastLine: true,
}
```

----

It looks like a problem in the JavaScript Debugger and not in the VSC debug adapter/view side because the Python debugger used with VSC 1.75 always showed the string correct in Debug Console, Variables View, Hover over variable.

Using the Python script and having a breakpoint: on the `print()` statement.

```python
with open('test-escape.js') as file:
  for line in file:
    line = line.rstrip();
    struc = {'line': line}
    print(line)
```

**Comment by rioj7** [comment]
An alternative is to debug the NodeJS JavaScript file:

```javascript
let text = 'let b = "Hello \\"//programmer\\"";'
let line = { _lineNr: 0, _text: text };
console.log(text);
```

**Comment by connor4312** [comment]
Thanks for the issue, I now try to match the behavior of the Node REPL in all cases, which is to prefer a quote style to avoid escaping, but fall back to `'` otherwise
