### ISSUE TITLE
extensão não funciona para python 

### ISSUE THREAD

**Issue by dreanlima** [microsoft/vscode#182991]
ADD ISSUE DESCRIPTION HERE

Version: 1.78.2
Commit: b3e4e68a0bc097f0ae7907b217c1119af9e03435
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36 Edg/113.0.1774.50
Embedder: vscode.dev

**Comment by dreanlima** [comment]
boa noite meu programa esta com problema na extensão, aparece esta mensagem:
Python was not found but can be installed from the Microsoft Store: https://go.microsoft.com/fwlink?linkID=2082640
[Done] exited with code=9009 in 0.257 seconds

**Comment by dreanlima** [comment]
e o site da Microsoft não abre

**Comment by roblourens** [comment]
It sounds like you don't have python installed. Make sure it's installed and on your PATH variable. If you think that vscode is doing the wrong thing, please open an issue on the python extension repo with more details.

**Comment by dreanlima** [comment]
Bom dia
Obrigado pelo retorno.

Em sex., 19 de mai. de 2023 20:14, Rob Lourens ***@***.***>
escreveu:
