### ISSUE TITLE
The `commandCenter` color customisations don't affect the theme

### ISSUE THREAD

**Issue by ppseprus** [microsoft/vscode#182913]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: Version: 1.78.2 (Universal) Commit: b3e4e68a0bc097f0ae7907b217c1119af9e03435
- OS Version: macOS 13.3.1 (a) (22E772610a)

**Steps to Reproduce:**

1. Set `workbench.colorCustomizations.commandCenter.background` to `"#ff0000"`
2. Optionally, You can delete the `workbench.colorTheme` setting

**Expected Behaviour**

The background of the Command Center is red.

**Actual Behaviour**

The background of the Command Center is dependent on the selected theme OR if that is deleted from the Settings, the background is some default color.

**Comment by jrieken** [comment]
This works for me. @ppseprus Do you use `workbench.colorCustomizations.commandCenter.background` (as stated above) which would be wrong or do you use 

```
 "workbench.colorCustomizations": {
    "commandCenter.background": "#ff0000"
},
```

<img width="802" alt="Screenshot 2023-12-04 at 11 31 46" src="https://github.com/microsoft/vscode/assets/1794099/0dedf9ce-2758-405c-834f-123c691dcb67">

**Comment by ppseprus** [comment]
Hey @jrieken ,

> or do you use

Yes, I used properly. I only simplified the notation here to show _which_ setting doesn't work.

Also, on version `1.84.2` 1a5daa3a0231a0fbba4f14db7ec463cf99d7768e I can no longer reproduce this issue.

**I consider this issue resolved**
