### ISSUE TITLE
.gitignore files don't take effect in Search if there is no .git folder 

### ISSUE THREAD

**Issue by studyingegret** [microsoft/vscode#182958]
Type: <b>Bug</b>

Steps to reproduce:
1. Create the following files in a folder and open it with Code:
   ```
   something/
     something irrelevant.txt
     something/
       also something irrelevant.txt
   .gitignore
   irrelevant.md
   abc.txt
   ```

   Fill each file with the text `Something`, except for .gitignore which should be:
   ```ignore
   /something
   *.md
   ```
2. Open the search panel from the activity bar, and search for "Some".

Expected behavior: All files (including .gitignore) except for those with "irrelevant" in its name are displayed in the results.

Actual behavior: Every file is shown.

Does this happen when all extensions are disabled?: Yes

VS Code version: Code - Insiders 1.79.0-insider (2d416df5f00253f5ebd60d2f08508a440747fd8d, 2023-05-19T05:25:00.632Z)
OS version: Windows_NT x64 10.0.19042
Modes:

**Comment by andreamah** [comment]
When you do this, do you have the ignored files open in the editor?

**Comment by studyingegret** [comment]
The same seems to happen no matter what files are opened in the editor.

Tested with 1.79.0-insider (6d3fedb7c2cf965915c785dc07701eb978947506, 2023-05-19T20:39:14.598Z)

**Comment by studyingegret** [comment]
Also, I verified that `search.useIgnoreFiles` is `true`.

**Comment by andreamah** [comment]
That's so strange. I can't seem to repro this. Do you have any other search related settings that aren't default? Can you show a screen recording?

**Comment by cmtm** [comment]
I ran into this too. @studyingegret , can you confirm that there's no `.git` directory in your workspace? If not, then it's the same problem I ran into. The issue is that vscode doesn't respect your `.gitignore` file if it isn't in a git directory. I made a pull request to fix this: https://github.com/microsoft/vscode/pull/183368.

**Comment by studyingegret** [comment]
@cntm Indeed, that's the case! The same doesn't happen if I use .ignore instead.

**Comment by cmtm** [comment]
@andreamah , let me know if there's any further information you need. The PR I linked fixes the issue.

**Comment by andreamah** [comment]
verification steps: 
1. create a directory with some files and don't initialize it as a git repo
2. create a `.gitignore` and add some paths
3. verify that search ignores the paths in `.gitignore`, even if it's not initialized as a git repo.
