### ISSUE TITLE
Build failure: following tasks did not complete: vscode-reh-linux-x64-min-ci

### ISSUE THREAD

**Issue by ulugbekna** [microsoft/vscode#182951]
Failure: https://dev.azure.com/monacotools/Monaco/_build/results?buildId=215171&view=logs&j=e5bbec05-0f06-558d-ebe9-5973d52063d2&t=eb0f2deb-013d-5d99-3d95-17b511254f31&l=19

Build: https://dev.azure.com/monacotools/Monaco/_build/results?buildId=215171&view=results

Changes: https://github.com/Microsoft/vscode/compare/b11a3f7...ce903f3

Similar to https://github.com/microsoft/vscode/issues/182626

**Comment by aeschli** [comment]
Looks like there's a problem downloading the node executable.

**Comment by aiday-mar** [comment]
Happened in this build too: https://dev.azure.com/monacotools/Monaco/_build/results?buildId=215985&view=results

**Comment by Yoyokrazy** [comment]
Hitting this in a recent build as well: https://dev.azure.com/monacotools/Monaco/_build/results?buildId=216704&view=results

cc @joaomoreno / @lszomoru

**Comment by aeschli** [comment]
I addded more log output.

**Comment by aeschli** [comment]
@joaomoreno Improved the downloading of node. Closing the issue.
