### ISSUE TITLE
Return SerialPort as intended instead of SerialPortInfo

### ISSUE THREAD

**Issue by brianignacio5** [microsoft/vscode#182957]
Could `requestSerialPort ` return the SerialPort class (port) instead of `port.getInfo()` ?

Reference in https://github.com/microsoft/vscode/blob/42fcfb8bfc975a450fcc7f32ce11ad0c4171a9b8/src/vs/base/browser/deviceAccess.ts#L67

@thegecko @mjbvz

**Comment by thegecko** [comment]
Install from VSIX will install the extension in the server extension host (running in the codespace), not the web extension host.

The only way of reliably testing an unpublished web extension is to [sideload it into vscode.dev](https://code.visualstudio.com/api/extension-guides/web-extensions#test-your-web-extension-in-vscode.dev):

- Build the web extension
- Serve the folder up on localhost (e.g. `npx serve --cors -p 3000`)
- Open https://vscode.dev/
- Run the `Developer: Install Extension from Location` command and paste in the url being served

Also, be aware of this issue on codespaces:

https://github.com/orgs/community/discussions/41636
