### ISSUE TITLE
Recently, whenever I open VS Code, i am getting an error message

### ISSUE THREAD

**Issue by GauravUpreti893** [microsoft/vscode#182968]
Type: <b>Bug</b>

I am getting an error message saying "Window is not responding". Earlier, it was working perfectly. I don't know what cause this

VS Code version: Code 1.78.2 (b3e4e68a0bc097f0ae7907b217c1119af9e03435, 2023-05-10T14:39:26.248Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-10210U CPU @ 1.60GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|7.79GB (1.44GB free)|
|Process Argv|-n --crash-reporter-id 16d3298f-8e59-49ff-a04c-f3962eef117f|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (50)</summary>

Extension|Author (truncated)|Version
---|---|---
code-gnu-global|aus|0.2.2
azps-tools|azp|0.2.0
vscode-database|baj|2.2.3
exe-runner|bra|0.2.1
competitive-programming-helper|Div|5.10.0
python-environment-manager|don|1.0.4
python-extension-pack|don|1.7.0
es7-react-js-snippets|dsz|4.4.3
vscode-npm-script|eg2|0.3.29
prettier-vscode|esb|9.12.0
snippet-generator|fio|1.0.1
auto-rename-tag|for|0.1.10
code-runner|for|0.12.0
terminal|for|0.0.10
gc-excelviewer|Gra|4.2.57
vscode-psl|ing|1.12.2
cpp-recolored|kep|0.2.1
vsc-python-indent|Kev|1.18.0
vscode-leetcode|Lee|0.18.1
MagicPython|mag|1.1.0
vscode-dotnet-runtime|ms-|1.6.0
vscode-edge-devtools|ms-|2.1.1
isort|ms-|2022.8.0
python|ms-|2023.8.0
vscode-pylance|ms-|2023.5.30
jupyter|ms-|2023.4.1011241018
jupyter-keymap|ms-|1.1.0
jupyter-renderers|ms-|1.0.15
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-slideshow|ms-|0.1.5
remote-wsl|ms-|0.78.5
cpptools|ms-|1.15.4
cpptools-extension-pack|ms-|1.3.0
js-debug-nightly|ms-|2023.5.1117
powershell|ms-|2023.5.1
vscode-serial-monitor|ms-|0.9.0
vscode-typescript-next|ms-|5.2.20230517
debugger-for-chrome|msj|4.13.0
sqltools|mtx|0.27.1
autodocstring|njp|0.6.1
cp-tools|pla|2.1.0
remove-comments|pli|1.2.2
cpp-boilerplate-code|Raj|1.0.0
vscode-thunder-client|ran|2.6.2
LiveServer|rit|5.7.9
python|tht|0.2.3
directory-switcher|ton|0.2.5
intellicode-api-usage-examples|Vis|0.2.7
vscodeintellicode|Vis|1.2.30
vscode-icons|vsc|12.4.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263:30335439
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
vscccc:30610679
2e4cg342:30602488
pyind779:30671433
89544117:30613380
pythonsymbol12:30671437
2i9eh265:30646982
showlangstatbar:30737416
pythonms35:30701012
pythonfmttext:30731395
pythoncmv:30739700
f8hc8238:30694864
fixhidewlkth:30730051
pythongtdpath:30739704

```

</details>

**Comment by roblourens** [comment]
I'm guessing you're using this antivirus: https://github.com/microsoft/vscode/issues/178962
