### ISSUE TITLE
Cannot copy ANYTHING from VS Code Stable Jupyter Notebook and paste into VS Code Insider

### ISSUE THREAD

**Issue by rohan-paul** [microsoft/vscode#182975]
This Problem of NOT being able to paste, is happening ONLY when I am copying something from a Jupyter Notebook from Stable Version of Code to Insider version.

But copy-paste is working fine when I am copying from a python file of the stable version to Insiders.

( And ofcouse, there is no problem with clipboard, as I am very well able to copy-paste the same text from a Jupyter Notebook of Stable Code to any other text-editor or or to any other document).

So, as a workaround, what I am having to do is first copy from VSCode Stable Jupyter Notebook, to any other Text Editor, then copy from there, and paste it into VSCode Insider Jupyter Notebook.

I have tried opening inside with `code-insiders --disable-extensions` - BUT that did not help

 I completely uninstalled Insiders and re-installed it. But the problem remains.

Stable Version

```
Version: 1.78.2 (user setup)
Commit: b3e4e68a0bc097f0ae7907b217c1119af9e03435
Date: 2023-05-10T14:39:26.248Z
Electron: 22.5.2
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Windows_NT x64 10.0.22621
Sandboxed: No
```

Insider Version 

```
Version: 1.79.0-insider (user setup)
Commit: f1258a5fbed44b8f84a097c73c1799c13c5c3646
Date: 2023-05-17T05:27:38.052Z
Electron: 22.5.2
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Windows_NT x64 10.0.22621
```

**Comment by amunger** [comment]
oh, you already opened one on vs code
