### ISSUE TITLE
Extension Development Host + remote-ssh + extensionKind=ui not working

### ISSUE THREAD

**Issue by alexandruavadanii** [microsoft/vscode#182903]
Type: <b>Bug</b>

Trying to debug an UI-only extension in the Extension Development Host while connected to a remote machine does not work. In fact it does nothing, the Extension Development Host doesn't seem to acknowledge the debugged extension at all.

Steps to reproduce:
1. Connect to a remote host (in my case I was using a local Windows machine and a remote Linux machine)
2. Follow the instructions for creating a basic Hello World extension [1], nothing special required;
3. Edit `package.json` and add `"extensionKind": [ "ui" ]`
4. Launch a debug session with `F5`, look for the "Hello world" command in the command palette;

Expected results: "Hello world" command is present.

Actual result: "Hello world" command is not available. In fact, the whole extension doesn't seem to do anything. I would share traces from the `ms-vcode.js-debug` extension (json.gz) if they didn't keep getting corrupted.

Other observations:
- having extensionKind as `[ "ui", "workspace" ]` bypasses the limitation, although I haven't checked whether it actually runs the extension locally or remotelly;
- trying to debug the same extension with extensionKind "ui" locally (without remote-ssh) works fine;

I'm opening this against the vscode repo, although it involves the remote-ssh extension, since I'm not sure it's remote-ssh's fault. In fact, this might be expected behavior, but I couldn't find it documented it anywhere.
Feel free to close this if it's expected behavior / move it to remote-ssh if that's appropriate.

[1] https://code.visualstudio.com/api/get-started/your-first-extension

VS Code version: Code - Insiders 1.79.0-insider (2946b1ee55db1d406526d3fd1df49250b2f8322d, 2023-05-18T05:25:02.319Z)
OS version: Windows_NT x64 10.0.18362
Modes:
Remote OS version: Linux x64 4.18.0-372.19.1.el8_6.x86_64
Remote OS version: Linux x64 4.18.0-372.19.1.el8_6.x86_64
Remote OS version: Linux x64 4.18.0-372.19.1.el8_6.x86_64
Remote OS version: Linux x64 4.18.0-372.19.1.el8_6.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.81GB (7.17GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: sestolabccv8|
|OS|Linux x64 4.18.0-372.19.1.el8_6.x86_64|
|CPUs|Intel(R) Xeon(R) Silver 4216 CPU @ 2.10GHz (8 x 2095)|
|Memory (System)|31.21GB (18.08GB free)|
|VM|100%|

|Item|Value|
|---|---|
|Remote|SSH: sestolabccv8|
|OS|Linux x64 4.18.0-372.19.1.el8_6.x86_64|
|CPUs|Intel(R) Xeon(R) Silver 4216 CPU @ 2.10GHz (8 x 2095)|
|Memory (System)|31.21GB (18.08GB free)|
|VM|100%|

|Item|Value|
|---|---|
|Remote|SSH: sestolabccv8|
|OS|Linux x64 4.18.0-372.19.1.el8_6.x86_64|
|CPUs|Intel(R) Xeon(R) Silver 4216 CPU @ 2.10GHz (8 x 2095)|
|Memory (System)|31.21GB (18.08GB free)|
|VM|100%|

|Item|Value|
|---|---|
|Remote|SSH: sestolabccv8|
|OS|Linux x64 4.18.0-372.19.1.el8_6.x86_64|
|CPUs|Intel(R) Xeon(R) Silver 4216 CPU @ 2.10GHz (8 x 2095)|
|Memory (System)|31.21GB (18.08GB free)|
|VM|100%|
</details>

**Comment by roblourens** [comment]
But the extension code is on the remote, right? It can't be loaded on the local side in this case so I think this exact scenario can't be supported.

**Comment by alexandruavadanii** [comment]
Yes, the code is on the remote. It's not unexpected that it can't be loaded in that direction, but I wasted a bit of time until I figured it out ...
