### ISSUE TITLE
Terminal Tab UI Improvements

### ISSUE THREAD

**Issue by nbennett25** [microsoft/vscode#182986]
Can we get the Terminal Tab UI to actually _be_ tabs, similar to how 'tab' is generally
understood to be layers of content? and not 2 panels: 1 terminal window
and one right hand group of 'tabs'? (this makes zero sense)

While cursor-focused in the terminal window, tabbing between tabs (or opt+1, opt+2, etc) should 
rotate through the tabs making the selected tab content active and the cursor should focus on the terminal line, 
allowing the user to type normally.

Currently to switch terminal windows, the user has to:
 - tab or physically click with a mouse to select the right hand column tab list 
 - select a 'tab' to be active
 - physically click or back-tab *back* to the terminal window
 
 This is just awful UI / UX.

PhpStorm does this just fine, and if there's a setting in VSCode to allow this, please point me 
in that direction.

**Comment by Tyriar** [comment]
> and one right hand group of 'tabs'? (this makes zero sense)

It's on the side, not the tab/bottom as there's little vertical space to work with as it would reduce the number of rows the terminal can use (in the default position). We considered horizontal tabs in the past and it has come up a few times, but when it does there isn't that much attention https://github.com/microsoft/vscode/issues/164806.

> While cursor-focused in the terminal window, tabbing between tabs (or opt+1, opt+2, etc) should
rotate through the tabs

You can add keybindings for the focus next and previous commands to rotate through the tabs, here's what I use:

```json
{ "key": "ctrl+shift+j",     "command": "workbench.action.terminal.focusNext" },
{ "key": "ctrl+shift+k",     "command": "workbench.action.terminal.focusPrevious" },
```

> tab or physically click with a mouse to select the right hand column tab list

If the distance to click is an issue you can move the tabs to the left:

```json
"terminal.integrated.tabs.location": "left"
```

<img width="476" alt="Screenshot 2023-05-19 at 5 13 15 pm" src="https://github.com/microsoft/vscode/assets/2193314/e0994d2c-22c2-4563-9500-a7137a29ce86">

> physically click or back-tab back to the terminal window

You can double click to focus back into the terminal, or you can focus on single click by setting this:

```json
"terminal.integrated.tabs.focusMode": "singleClick"
```

The reason this is not the default is for accessibility reasons and to align with the rest of the UI.

---

If you really want it to act exactly like editor tabs, you should use editor terminals: 

https://code.visualstudio.com/docs/terminal/basics#_terminals-in-editor-area

You can also revert to the old dropdown which we still support via:

```json
"terminal.integrated.tabs.enabled": false
```

<img width="367" alt="Screenshot 2023-05-19 at 5 19 27 pm" src="https://github.com/microsoft/vscode/assets/2193314/5bbb3e5d-06b5-48f6-985f-f9b2465c99d6">
