### ISSUE TITLE
Support for Environment Variables in Workspace Files

### ISSUE THREAD

**Issue by cilerler** [microsoft/vscode#182964]
I would like to propose a feature that allows the use of environment variables within workspace files (.code-workspace). This feature would be particularly useful for creating portable, platform-independent workspaces.

Currently, it's not possible to specify a directory in the workspace file that is relative to, for example, the user's home directory. This can be a problem when sharing workspaces across different operating systems or between different users, as the home directory is different on each system and for each user.

Here is an example of how it could look:

```json
{
    "folders": [
        {
            "path": "${env:HOME}/project"
        },
        {
            "path": "${env:USERPROFILE}/another_project"
        }
    ],
    "settings": {}
}
```

In this example, `${env:HOME}` and `${env:USERPROFILE}` would be replaced by the value of the **HOME** and **USERPROFILE** environment variables, respectively.

By allowing for environment variables in workspace files, it would enable the creation of more flexible and portable workspace configurations.

**Comment by bpasero** [comment]
Can you see if this request is already covered in https://github.com/microsoft/vscode/issues?q=is%3Aopen+label%3Aworkbench-multiroot+environment

**Comment by cilerler** [comment]
Yes, [this one](https://github.com/microsoft/vscode/issues/44755) does.  Thanks for pointing it out.

![bitmoji](https://sdk.bitmoji.com/render/panel/98342d7e-a9bb-4c00-8923-4fc0c63fc1ef-ccdabca3-9682-4342-aa5e-1222b8adc35f-v1.png?transparent=1&palette=1&width=246)
