### ISSUE TITLE
"editor.fontSize" settings changes "Output" panel font size but not the font size of other panesl

### ISSUE THREAD

**Issue by H-G-Hristov** [microsoft/vscode#182960]
Type: <b>Bug</b>

The following setting changes the font size not only for the editor but also for the "Output" panel. It will be much better if there is a separate setting to change the font size of all panels consistently. There is no sense to change just "Output" panel's font. The code editor and the panel fonts should be independent. This looks like bug.

> "editor.fontSize": 25,

VS Code version: Code 1.78.2 (Universal) (b3e4e68a0bc097f0ae7907b217c1119af9e03435, 2023-05-10T14:44:45.204Z)
OS version: Darwin arm64 22.4.0
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (0.14GB free)|
|Process Argv|--crash-reporter-id a7eaff19-94ae-4653-b917-d9aaab19da5d|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (35)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|13.3.1
markdown-mermaid|bie|1.18.1
mermaid-markdown-syntax-highlighting|bpr|1.5.1
doxdocgen|csc|1.4.0
vscode-markdownlint|Dav|0.50.0
githistory|don|0.6.20
gitlens|eam|13.6.0
EditorConfig|Edi|0.16.4
codespaces|Git|1.14.7
vscode-pull-request-github|Git|0.65.2023051809
restructuredtext|lex|189.3.0
vscode-catch2-test-adapter|mat|4.4.2
git-graph|mhu|1.30.0
vscode-docker|ms-|1.25.1
isort|ms-|2022.8.0
pylint|ms-|2023.4.0
python|ms-|2023.8.0
vscode-pylance|ms-|2023.5.30
remote-containers|ms-|0.292.0
remote-ssh-edit|ms-|0.86.0
cmake-tools|ms-|1.14.31
cpptools|ms-|1.15.4
cpptools-extension-pack|ms-|1.3.0
hexeditor|ms-|1.9.11
remote-explorer|ms-|0.4.0
vsliveshare|ms-|1.0.5864
vscode-xml|red|0.25.0
swift-lang|ssw|1.3.0
shellcheck|tim|0.32.5
vscode-mermaid-editor|tom|0.18.1
simple-rst|tro|1.5.3
cmake|twx|0.0.17
vscode-lldb|vad|1.9.1
vscode-apple-swift-format|vkn|1.4.2
vscode-swiftlint|vkn|1.8.3

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
vsccc:30610678
3biah626:30602489
pyind779:30671433
89544117:30613380
pythonsymbol12:30671437
a9j8j154:30646983
showlangstatbar:30737416
vsccsb:30705552
pythonms35:30701012
pythonfmttext:30731395
pythoncmv:30739700
fixshowwlkth:30730052
pythongtdpathcf:30739705

```

</details>

**Comment by connor4312** [comment]
Test results does not use anything from the terminal

**Comment by H-G-Hristov** [comment]
> The described behavior is how it is expected to work. If you disagree, please explain what is expected and what is not in more detail. See also our [issue reporting guidelines](https://aka.ms/vscodeissuereporting).
> 
> Happy Coding!

I don't want that the Output panel is not affected by the code editor font size. I need this to be independent. The reason is that tthe Output panel gets very long messages and rows, it is where the extensions output their logs and it usually is set to a smaller size and if the font is smaller then more information can be viewed. If I increase the font size to be able to view the code editor the Output text also gets increased and very little information is displayed and I need to constantly resize the windows which is very inconvenient and distracting.

If this is by design. Why this panel was design like that at all it doesn't make sense.
