### ISSUE TITLE
Build and Run From Source for Ubuntu: directory vscode not created

### ISSUE THREAD

**Issue by wbartussek** [Microsoft/vscode#1829]
This issue relates to 
[https://github.com/Microsoft/vscode/wiki/How-to-Contribute#build-and-run-from-source]
(https://github.com/Microsoft/vscode/wiki/How-to-Contribute#build-and-run-from-source). 
I just wanted to build VS Code from scratch on an Ubuntu box (14.04). After having executed the recommended command 
git clone https://github.com/microsoft/vscode
trying to execute
cd vscode && npm install -g mocha gulp
returned the error message
vscode: No such file or directory
However: The hidden directory .vscode has been created. It seems to be a tiny typo. So I would like to ask the team to look into this.
Thanks.

**Comment by joaomoreno** [comment]
The `.vscode` directory is where an instance of VSCode saves its configuration settings. It's unrelated to what you are doing.

When you ran `git clone https://github.com/microsoft/vscode`, this should've created a `vscode` folder under your current working directory. This is the folder that `cd vscode` should go into.

**Comment by wbartussek** [comment]
After having removed the whole project directory and having rerun git clone https://github.com/microsoft/vscode I could not reproduce the observed behaviour. So I think it is not worth while further examinig this case. Thanks for your quick response.
