### ISSUE TITLE
Cannot drag notebook cells

### ISSUE THREAD

**Issue by Yoyokrazy** [microsoft/vscode#182915]
Type: <b>Bug</b>

Create notebook with multiple cells, try to drag cell up or down to move it.

Cursor changes to "drag" icon, however unable to drag cell.

VS Code version: Code - Insiders 1.79.0-insider (2946b1ee55db1d406526d3fd1df49250b2f8322d, 2023-05-18T05:25:02.319Z)
OS version: Windows_NT x64 10.0.22621
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|12th Gen Intel(R) Core(TM) i7-1265U (12 x 2688)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.83GB (16.13GB free)|
|Process Argv|--crash-reporter-id 1cb7488a-bb2c-46a8-ac2f-3151dbb5b996|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (29)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|3.0.2
vscode-django|bat|1.10.0
github-markdown-preview|bie|0.3.0
ruff|cha|2023.17.11351528
doxdocgen|csc|1.4.0
githistory|don|0.6.20
python-environment-manager|don|1.0.4
python-extension-pack|don|1.7.0
gitlens|eam|2023.5.1805
prettier-vscode|esb|9.12.0
copilot-chat|Git|0.1.2023051803
copilot-nightly|Git|1.86.103
vscode-pull-request-github|Git|0.65.2023051809
vsc-python-indent|Kev|1.18.0
theme-monokai-pro-vscode|mon|1.2.1
black-formatter|ms-|2023.3.11241004
python|ms-|2023.9.11371007
vscode-pylance|ms-|2023.5.31
jupyter|ms-|2023.5.1001401100
jupyter-keymap|ms-|1.1.1
jupyter-renderers|ms-|1.0.15
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-slideshow|ms-|0.1.5
vscode-typescript-next|ms-|5.2.20230517
autodocstring|njp|0.6.1
vscode-status-bar-format-toggle|tom|3.1.1
intellicode-api-usage-examples|Vis|0.2.7
vscodeintellicode|Vis|1.2.30
jinja|who|0.0.8

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythontb:30258533
pythonptprofiler:30281269
vshan820:30294714
vscod805:30301674
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30404738
cppdebug:30492333
vsclangdf:30492506
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30618038
pylantcb52:30590116
pyind779:30611226
pythonsymbol12:30651887
a9j8j154:30646983
showlangstatbar:30737417
pythonms35:30671666
cai9j608:30680470
7ij38806:30687742
pythonfmttext:30716741
pythoncmvfstr:30726892
fixshowwlkth:30724385
hidesbindicator:30724476
pythongtdpath:30726887

```

</details>

**Comment by roblourens** [comment]
Working for me, where are you dragging? Any relevant settings?

**Comment by Yoyokrazy** [comment]
Nothing relevant in settings that I'm aware of. Double checked, and I *can't* drag markdown cells specifically. I *can* drag code cells. 

Clicking in the region with the red box : 
<img width="416" alt="image" src="https://github.com/microsoft/vscode/assets/12552271/5bd010f2-2d42-4486-8c16-59e9b466fbeb">


Looping in @amunger as he seems to be unable to drag both markdown and code cells

**Comment by amunger** [comment]
I had it disabled, don't remember doing that

**Comment by Yoyokrazy** [comment]
Ok, might be by design, didn't realize you could only drag around rendered markdown cells. A lot of mine had been kept in source mode, so didn't think to render them and check again. If that's intended behavior, then false alarm

**Comment by roblourens** [comment]
Oh yeah, there is an issue for that. Gotta get back to that one at some point
