### ISSUE TITLE
msedge/chrome launch config no longer works

### ISSUE THREAD

**Issue by brentmjohnson** [microsoft/vscode#182978]
Type: <b>Bug</b>

Unable to launch browser: "Timed out waiting for browser connection"

Worked perfectly until a recent update.  Non-insiders build works fine with exact same config.

VS Code version: Code - Insiders 1.79.0-insider (2d416df5f00253f5ebd60d2f08508a440747fd8d, 2023-05-19T05:25:00.632Z)
OS version: Windows_NT x64 10.0.25357
Modes:
Remote OS version: Linux x64 5.15.90.1-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 9 5950X 16-Core Processor             (32 x 3400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|63.91GB (7.20GB free)|
|Process Argv|--folder-uri vscode-remote://ssh-remote%2B7b22686f73744e616d65223a22454550437634227d/home/brent/dataStore/chunkify/chunkify --crash-reporter-id c17fa07e-ef79-4a39-a56b-926636dff579|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: PC
|OS|Linux x64 5.15.90.1-microsoft-standard-WSL2|
|CPUs|AMD Ryzen 9 5950X 16-Core Processor (32 x 3400)|
|Memory (System)|47.04GB (44.94GB free)|
|VM|0%|
</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
codespaces|Git|1.14.7
better-cpp-syntax|jef|1.17.2
vscode-edge-devtools|ms-|2.1.1
jupyter-keymap|ms-|1.1.1
remote-containers|ms-|0.293.0
remote-ssh|ms-|0.102.0
remote-ssh-edit|ms-|0.86.0
remote-wsl|ms-|0.78.6
vscode-remote-extensionpack|ms-|0.24.0
remote-explorer|ms-|0.4.0
remote-server|ms-|1.1.0
vscode-docker|ms-|1.25.1

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythontb:30258533
pythonptprofiler:30281269
vshan820:30294714
vscod805cf:30301675
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30404738
cppdebug:30492333
vsclangdf:30492506
c4g48928:30535728
dsvsc012:30540252
pynewext54:30618038
pylantcb52:30590116
pyind779:30611226
vscrp:30624060
pythonsymbol12:30651887
2i9eh265:30646982
showlangstatbar:30737417
pythonms35:30671666
19089226:30680468
24365598:30687740
pythonfmttext:30716741
pythoncmvfstr:30726892
fixshowwlkth:30724385
showsbindicator:30724477
pythongtdpath:30726887

```

</details>

**Comment by connor4312** [comment]
duplicates https://github.com/microsoft/vscode/issues/182749
