### ISSUE TITLE
Unable to drag tabs around

### ISSUE THREAD

**Issue by W3Warp** [microsoft/vscode#182902]
Type: <b>Bug</b>

For some inexplicable reason the future to move tabs around, left and right, down to terminal, split to compare in the text editor...

What I've tried
1. Disabled all extensions, no change. 
2. Reset setting ´to defailt, no change.
3. Reinsatlled VScode

The only thing that works until the bug gets triggerd again is to restart "Windows Explorer"

VS Code version: Code 1.78.2 (b3e4e68a0bc097f0ae7907b217c1119af9e03435, 2023-05-10T14:39:26.248Z)
OS version: Windows_NT x64 10.0.19045
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz (8 x 4008)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|63.94GB (45.18GB free)|
|Process Argv|--crash-reporter-id 4329be14-42bd-4c1e-ada3-49597ab3359a|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (99)</summary>

Extension|Author (truncated)|Version
---|---|---
codegeex|AMi|1.1.7
vscode-openai|And|1.1.7
vscode-django|bat|1.10.0
Bito|Bit|1.0.135
solargraph|cas|0.24.0
npm-intellisense|chr|1.4.4
path-intellisense|chr|2.8.4
codeque|Cod|0.21.1
vscode-test-explorer-status-bar|con|1.2.0
vscode-micromamba|cor|0.1.16
rapid-json-search|dat|0.1.8
vscode-eslint|dba|2.4.0
conda-wingman|DJS|0.2.1
python-environment-manager|don|1.0.4
python-extension-pack|don|1.7.0
xml|Dot|2.5.1
vscode-go-syntax|dun|0.0.18
pythonsnippets3|Eri|3.3.18
prettier-vscode|esb|9.12.0
font-switcher|eva|4.1.0
docker-explorer|for|0.1.7
shell-format|fox|7.2.5
remotehub|Git|0.56.1
go|gol|0.38.0
vscode-test-explorer|hbe|2.21.1
swift|Kas|0.2.0
vsc-python-indent|Kev|1.18.0
vscode-fix-checksums|leh|1.1.0
node-module-intellisense|lei|1.5.0
markdown-auto-index|Leo|1.0.1
vscode-python-test-adapter|lit|0.7.1
regexp-preview|Lou|0.1.5
MagicPython|mag|1.1.0
python-path|mge|0.0.14
document|min|2.2.1
vscode-docker|ms-|1.25.1
dotnet-interactive-vscode|ms-|1.0.4258030
vscode-dotnet-runtime|ms-|1.6.0
vscode-kubernetes-tools|ms-|1.3.11
autopep8|ms-|2023.4.0
black-formatter|ms-|2023.2.0
gather|ms-|2022.3.2
isort|ms-|2022.8.0
python|ms-|2023.8.0
vscode-pylance|ms-|2023.5.30
jupyter|ms-|2023.4.1011241018
jupyter-keymap|ms-|1.1.0
jupyter-renderers|ms-|1.0.15
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-slideshow|ms-|0.1.5
remote-containers|ms-|0.292.0
remote-wsl|ms-|0.78.5
azure-repos|ms-|0.32.0
cmake-tools|ms-|1.14.31
cpptools|ms-|1.15.4
cpptools-extension-pack|ms-|1.3.0
powershell|ms-|2023.5.0
remote-repositories|ms-|0.34.0
test-adapter-converter|ms-|0.1.7
php-docblocker|nei|2.7.0
hash|net|0.0.4
gremlins|nho|0.26.0
vscode-python-typehint|njq|1.5.1
pip-installer|Pet|0.0.4
vscode-versionlens|pfl|1.5.0
material-icon-theme|PKi|4.27.0
tsimporter|pmn|2.0.1
quicktype|qui|12.0.46
ruby|reb|0.28.1
java|red|1.18.0
vscode-xml|red|0.25.0
vscode-yaml|red|1.12.2
vs-code-prettier-eslint|rve|5.1.0
sourcery|sou|1.3.0
autoimport|ste|1.5.4
code-spell-checker|str|2.20.4
python-task-provider|ton|0.3.0
cmake|twx|0.0.17
sort-lines|Tyr|1.9.1
errorlens|use|3.11.0
intellicode-api-usage-examples|Vis|0.2.7
vscodeintellicode|Vis|1.2.30
vscodeintellicode-completions|Vis|1.0.22
vscodeintellicode-insiders|Vis|1.1.10
vscode-swiftlint|vkn|1.8.3
vscode-concourse|vmw|1.46.0
vscode-java-debug|vsc|0.50.0
vscode-java-pack|vsc|0.25.11
vscode-java-test|vsc|0.38.2
vscode-maven|vsc|0.41.0
vscode-icons|vsc|12.4.0
gistfs|vsl|0.4.1
jinja|who|0.0.8
vscode-ruby|win|0.28.0
JavaScriptSnippets|xab|1.8.0
php-debug|xde|1.32.1
markdown-all-in-one|yzh|3.5.1
php-intellisense|zob|1.1.3
vscode-proto3|zxh|0.5.5

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vstes627:30244334
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscoreces:30445986
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
3biah626:30602489
pyind779:30671433
89544117:30613380
pythonsymbol12:30671437
showlangstatbar:30737416
vsctsb:30705553
azdwalk:30721579
pythonms35:30701012
pythonfmttext:30731395
pythoncmv:30739700
fixhidewlkth:30730051
pythongtdpathcf:30739705

```

</details>

**Comment by gjsjohnmurray** [comment]
See also #182766

**Comment by bpasero** [comment]
@W3Warp why did you close https://github.com/microsoft/vscode/issues/182766 and keep filing duplicate issues? If you are not willing to provide the information asked, how do you expect we could help you here?

**Comment by bpasero** [comment]
Please send me a screen recording of the issue so I can provide help.

**Comment by bpasero** [comment]
Yeah, for example how visually it appears when you cannot move tabs around. I have a theory it maybe related to permissions, are you maybe running as admin?

**Comment by bpasero** [comment]
Likely window and main logs if there is any error logged during drag and drop.

Do you know if you run VS Code as administrator not a normal user account?

**Comment by bpasero** [comment]
Another question: you say that dragging a tab to the terminal does not work to paste the path in. I assume this is the integrated terminal inside VS Code and not outside?

And related: when this fails, can you also not move the tab around to move it somewhere else in the editor area, e.g. to split it to the side via drag and drop?

**Comment by bpasero** [comment]
Any update?

**Comment by W3Warp** [comment]
> 

Hi, thank you for asking. things look good for now.
stuff that has happens since the last time ...

- Windows has been updated
- VScode has been completely installed.
- An VScode ext that directly modifies VS code to change its GUI no longer exists. This could have been the culprit because even if all extensions would have been disabled this one would not have been,, sry I don't remember the name.
