### ISSUE TITLE
Replace All is very difficult to use in Find in Selection mode, when you want to make repeated replace selections

### ISSUE THREAD

**Issue by MinuteReversal** [microsoft/vscode#182954]
Does this issue occur when all extensions are disabled?: Yes/No

# Replace All is very difficult to use in Find in Selection mode, when you want to make repeated replace selections
- VS Code Version: 
```
Version: 1.78.2 (user setup)
Commit: b3e4e68a0bc097f0ae7907b217c1119af9e03435
Date: 2023-05-10T14:39:26.248Z
Electron: 22.5.2
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Windows_NT x64 10.0.22621
Sandboxed: No
```
- OS Version: 
```
Windows 11
Microsoft Windows
Version 22H2(OS Build 22621.1702)
```
Steps to Reproduce:

1. Select multiple lines of text
2. Copy multiple lines of text
3. Paste multiple lines of text
4. ctrl + h
5. Select multiple lines of text
6. Open Find in Selection
7. Select multiple lines of text
8. Copy multiple lines of text
9. Paste multiple lines of text
10. Select multiple lines of text
11. Modify the replacement content in the replacement box
12. The replacement position is not the text area just selected (it is possible to replace only the text before copying, or it may replace the text before and after copying)

* For large-scale repetitions =>selection=>copy=>paste=>selection=>replace. The Replace dialog box always doesn't know to update the selected area.The Find in Selection button must be switched on and off repeatedly to reselect the text, which is very inconvenient.

![output](https://github.com/microsoft/vscode/assets/13540837/be17c46c-69f6-4fa2-b560-bad9e6b99ebf)

**Comment by amunger** [comment]
Updating the selection range is covered in https://github.com/microsoft/vscode/issues/116827
