### ISSUE TITLE
Jump to matching bracket issue

### ISSUE THREAD

**Issue by bobcho** [Microsoft/vscode#183]
"Jump to matching bracket" (⇧⌘]) goes to the outer side of left bracket and the inner side of right bracket. This breaks further matching. 

To reproduce just issue ⇧⌘] on nested brackets starting from the most outer ones, see where the cursor ends up (goes to inner couple each time).

**Comment by jrieken** [comment]
this code has changed at lot since the last 3 years ;-)

**Comment by alexandrudima** [comment]
@bobcho Thank you for reporting this :+1:

**Comment by alexandrudima** [comment]
For verification:
```javascript
var x = (3 + (5-7))
```
position cursor in every possible position around brackets. Use jump to bracket, it should not get stuck or start jumping to other bracket pair.
