### ISSUE TITLE
Eager `getResolvedShellEnv` call

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#183069]
The `IPtyHostService` can spawn a process eagerly on startup competing with the first window open:

https://github.com/microsoft/vscode/blob/adbcbfa5d06a268f338c00ecb15e7860261e5b63/src/vs/platform/terminal/node/ptyHostService.ts#L138

This should only be done:
* only when actually needed
* after a window has opened if possible (i.e. after restored phase)

**Comment by bpasero** [comment]
I believe this could possibly explain why macOS starts slower:

![image](https://github.com/microsoft/vscode/assets/900690/61965b9b-c26b-4652-b9f0-d422be323e77)

**Comment by Fecotgt** [comment]
@doudou  adbcbfa](vscode/src/vs/platform/terminal/node/ptyHostService.ts)

**Comment by Fecotgt** [comment]
@bpasero

**Comment by Fecotgt** [comment]
> @bpasero

https://github.com/microsoft/vscode/issues/183069#issuecomment-1556594220
