### ISSUE TITLE
HTML: certain tags (e.g. data, meter, time) should have an Emmet abbreviation, while others (e.g. datagrid) shouldn't

### ISSUE THREAD

**Issue by anthonyvdotbe** [microsoft/vscode#183020]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: Version: 1.78.2 (user setup) b3e4e68a0bc097f0ae7907b217c1119af9e03435
- OS Version: Windows_NT x64 10.0.22621

Steps to Reproduce:

In an HTML document:
1. Type `data`, `meter`, `time` and notice none of them have an Emmet abbreviation
2. Type `datag` and notice it's an Emmet abbreviation for `datagrid`, even though that's a [nonexistent](https://developer.mozilla.org/en-US/search?q=datagrid) HTML tag ([apparently](https://www.quackit.com/html_5/tags/html_datagrid_tag.cfm) it was part of a draft version of HTML5)

**Comment by Baldauren** [comment]
Emmet does't works

**Comment by Baldauren** [comment]
i also have this problem

**Comment by Baldauren** [comment]
Emmet is breaking while using

**Comment by rzhao271** [comment]
Hi @anthonyvdotbe, I'm wondering what `meter` should expand to? Should it include all the [attributes](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meter#attributes)?

Also, the snippets live in the [emmetio/emmet](https://github.com/emmetio/emmet) repository. Marking this as an upstream issue.

**Comment by anthonyvdotbe** [comment]
> Hi @anthonyvdotbe, I'm wondering what `meter` should expand to? Should it include all the [attributes](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meter#attributes)?

Hi @rzhao271, I'd prefer if it would just include the `value` attribute

> Also, the snippets live in the [emmetio/emmet](https://github.com/emmetio/emmet) repository. Marking this as an upstream issue.

Thanks for pointing this out, I've created an issue there

**Comment by rzhao271** [comment]
This issue seems to have been resolved as part of https://github.com/microsoft/vscode/pull/180583.
