### ISSUE TITLE
Visual studio code opening very slowly and displaying window is not responding message

### ISSUE THREAD

**Issue by Infyn8** [microsoft/vscode#183031]
Type: <b>Bug</b>

I double click on my vs code ,nothing happens for like 10 seconds then vs code slowly starts opening. After that it sometimes displays the "This window is not responding error and I have the option to Wait or reopen or close it. I have tried uninstalling and reinstalling it but nothing works. It used to work fine before this just started today.

VS Code version: Code 1.78.2 (b3e4e68a0bc097f0ae7907b217c1119af9e03435, 2023-05-10T14:39:26.248Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|12th Gen Intel(R) Core(TM) i5-12450H (12 x 2496)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.63GB (8.64GB free)|
|Process Argv|--crash-reporter-id 71915bd7-2319-4a00-b86b-2517acbdd11d|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscorecescf:30445987
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
vscccc:30610679
2e4cg342:30602488
pyind779:30671433
89544117:30613380
vscrpc:30673769
pythonsymbol12:30671437
2i9eh265:30646982
showlangstatbar:30737416
vsccsb:30705552
pythonms35:30701012
pythonfmttext:30731395
pythoncmv:30739700
fixhidewlkth:30730051
hidesbindicator:30730055
pythongtdpathcf:30739705

```

</details>

**Comment by Infyn8** [comment]
![Screenshot (1)](https://github.com/microsoft/vscode/assets/122700343/e080a287-e812-4b32-b1da-961c65bfea20)

**Comment by Lakshmikanth2001** [comment]
facing the same issue on windows 11

**Comment by Infyn8** [comment]
I have tried everything, from reinstalling to deleting all extensions to clearing temps and even the previous version nothing works. It works fine on my PC and even my friend's laptop but not with my laptop. For now after the startup and the not responding dialogue box, my application runs fine if I wait for it to respond. I am on the latest version of windows 11 and have a good laptop that is not even 1 month old. All my other applications run fine without any problems. Even Vs code did but now I have this problem.

**Comment by gjsjohnmurray** [comment]
Are you using McAfee antivirus? If so please see https://github.com/microsoft/vscode/issues/178962
