### ISSUE TITLE
Dark+ still listed as "Default Dark+" in settings dropdown

### ISSUE THREAD

**Issue by daviddossett** [microsoft/vscode#183000]
<img width="533" alt="CleanShot 2023-05-19 at 15 06 51@2x" src="https://github.com/microsoft/vscode/assets/25163139/932ae001-e5a7-49a1-95a5-e8cf0e7c3a93">

**Comment by aeschli** [comment]
`Default Dark` is the value goes into the the settings. We need to continue to support that value for compatibility reasons. 
The `Default` rather reflect that this is part of our built-in default themes. The theme that is actual set as default get's the `default` info at the end. Note that this depends on the product. E.g. on github.dev it's the Github theme.

![image](https://github.com/microsoft/vscode/assets/6461412/d7d5d094-cfec-409c-8747-ed42e7fcedc9)

**Comment by aeschli** [comment]
No changes planed.
