### ISSUE TITLE
App Start with Delay

### ISSUE THREAD

**Issue by Asinghhackerzz** [microsoft/vscode#183071]
Type: <b>Performance Issue</b>

When I open the app, it opens after almost 30 seconds, kindly fix that. 

VS Code version: Code 1.78.2 (b3e4e68a0bc097f0ae7907b217c1119af9e03435, 2023-05-10T14:39:26.248Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 4800H with Radeon Graphics          (16 x 2895)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.42GB (8.10GB free)|
|Process Argv|--crash-reporter-id 19e3040f-a43d-49f3-8c25-6a058097c597|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	    98	 11176	code main
    0	    29	  8764	   crashpad-handler
    0	   101	 10656	   window
    0	   205	 11132	window [1] (Settings - Project Code - Visual Studio Code)
    0	    96	 12072	window [2] (Issue Reporter)
    0	    52	 13288	   utility-network-service
    0	   155	 13296	extensionHost [1]
    0	    72	  3804	     electron-nodejs (GQR.js )
    0	    11	 15896	       console-window-host (Windows internal process)
    0	    17	  9016	     c:\Users\asing\AppData\Local\Programs\Python\Python311\python.exe c:\Users\asing\.vscode\extensions\ms-toolsai.jupyter-2023.3.1201040234\pythonFiles\vscode_datascience_helpers\kernel_interrupt_daemon.py --ppid 13296
    0	    11	 12596	       console-window-host (Windows internal process)
    0	   388	 16216	     electron-nodejs ("C:\Users\asing\AppData\Local\Programs\Microsoft VS Code\Code.exe" --ms-enable-electron-run-as-node c:\Users\asing\.vscode\extensions\ms-python.vscode-pylance-2023.5.30\dist\server.bundle.js --cancellationReceive=file:88ba00a6f007d1fc14eb25e703c79ec16ff8cfe029 --node-ipc --clientProcessId=13296)
    0	   100	 16264	     electron-nodejs ("C:\Users\asing\AppData\Local\Programs\Microsoft VS Code\Code.exe" --ms-enable-electron-run-as-node c:\Users\asing\.vscode\extensions\visualstudioexptteam.intellicode-api-usage-examples-0.2.7\dist\server\server.js --node-ipc --clientProcessId=13296)
    0	    89	 13864	fileWatcher [1]
    0	   144	 13996	   gpu-process
    0	    98	 18256	shared-process
    0	    84	  9940	     ptyHost
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (Settings - Project Code - Visual Studio Code)
|    Folder (Project Code): 143 files
|      File types: png(130) ipynb(1) py(1)
|      Conf files:;
```

</details>
<details><summary>Extensions (21)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-django|bat|1.10.0
python-environment-manager|don|1.0.4
python-extension-pack|don|1.7.0
vsc-python-indent|Kev|1.18.0
python|ms-|2023.8.0
vscode-pylance|ms-|2023.5.30
jupyter|ms-|2023.4.1011241018
jupyter-keymap|ms-|1.1.0
jupyter-renderers|ms-|1.0.15
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-slideshow|ms-|0.1.5
autodocstring|njp|0.6.1
java|red|1.18.0
intellicode-api-usage-examples|Vis|0.2.7
vscodeintellicode|Vis|1.2.30
vscode-java-debug|vsc|0.50.0
vscode-java-dependency|vsc|0.22.0
vscode-java-pack|vsc|0.25.11
vscode-java-test|vsc|0.38.2
vscode-maven|vsc|0.41.0
jinja|who|0.0.8

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
2e4cg342:30602488
pyind779:30671433
89544117:30613380
pythonsymbol12:30671437
showlangstatbar:30737416
vsctsb:30705553
pythonms35:30701012
pythonfmttext:30731395
fixhidewlkth:30730051
showsbindicator:30730056
pythongtdpathcf:30739705

```

</details>

**Comment by gjsjohnmurray** [comment]
Are you using McAfee antivirus? If so please see https://github.com/microsoft/vscode/issues/178962
