### ISSUE TITLE
Cannot push to gitlab

### ISSUE THREAD

**Issue by ignxcy** [microsoft/vscode#183052]
If you're using the integrated terminal in vscode, it automaticly always authenticates for you, but when you don't want to push into github, but gitlab it will still auto authenticate and will fill the password field with the github token, a nice feature would be auto checking if the remote is a github link and only auto authenticate when it is one

**Comment by lszomoru** [comment]
@ignxcy, that does not seem right as the `github` extension should only be providing the user name and password for a repository that is being hosted on GitHub. Would you be able to provide a recording (https://gifcap.dev) so that I better understand the issue? Thank you!

**Comment by ignxcy** [comment]
nevermind, you're right
