### ISSUE TITLE
[duplicate] - "Ctrl + ." as the default quick fix shortcut only writes an "e" without any action 

### ISSUE THREAD

**Issue by bolandi** [microsoft/vscode#183068]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.78.2
- OS Version: Ubuntu 22.04.2 LTS (jammy)

This is a duplicate of https://github.com/microsoft/vscode/issues/135084 but reproducible i.e. after disabling "All installed extensions".

**Comment by gjsjohnmurray** [comment]
Per https://github.com/microsoft/vscode/issues/135084#issuecomment-943686448 what keyboard layout are you using?

Also, does your keybindings.json file contain any entries?

**Comment by bolandi** [comment]
> Per https://github.com/microsoft/vscode/issues/135084#issuecomment-943686448 what keyboard layout are you using?
English. I also have a Swedish layout and the behavior is the same on both layouts

> Also, does your keybindings.json file contain any entries?
I just added "alt+enter" as the default binding for quick fix after creating this issue which works now however pressing `ctrl+.` still produces the exact same behavior. The weird thing is the emoji pop-up menu after pressing Enter. In other words, the following context menu pops up with this sequence: `ctrl+.+space`

![image](https://github.com/microsoft/vscode/assets/5443036/862e564e-8f46-4440-86fd-86888de2433e)

**Comment by gjsjohnmurray** [comment]
Also happens in Text Editor in Ubuntu, so not a VS Code fault. See https://askubuntu.com/questions/1370022/ubuntu-21-10-keyboard-shortcut-ctrl-changed-how-to-disable-or-change

**Comment by bolandi** [comment]
True, I confirm that it's also happening in a the text editor so seems to be an OS wide issue. 

Thanks for the quick resolution!

**Comment by ulugbekna** [comment]
thanks for investigation @gjsjohnmurray ! :-)
