### ISSUE TITLE
Crashed, Code: -1073741819, always！

### ISSUE THREAD

**Issue by RAiNY7Study** [microsoft/vscode#183056]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.78.2 (user setup)
- OS Version: Windows_NT x64 10.0.19045

Steps to Reproduce:

1. It always crashes when I'm writing code and I need to restart vsCode! I can't reproduce it because it's always there and crashes frequently!

**Comment by deepak1556** [comment]
Can you attach the crash reports following the steps at https://github.com/microsoft/vscode/wiki/Native-Crash-Issues#creating-a-crash-report
