### ISSUE TITLE
Update Default Keybinding for Quit Command to Ctrl+B 

### ISSUE THREAD

**Issue by rivo2302** [microsoft/vscode#183113]
As an Azerty keyboard user, I often find myself accidentally triggering the "**Quit**" command in Visual Studio Code when intending to save my work using the `Ctrl+S` shortcut. This confusion arises due to the proximity of the "**Quit**" shortcut (`Ctrl+Q`) to the "**Save**" shortcut (`Ctrl+S`) on Azerty keyboards.

To improve the user experience for **Azerty** keyboard users and reduce the risk of unintended application quitting, I suggest updating the default keybinding for the "**Quit**" command to `Ctrl+B`. 

Thank you for considering this improvement 🙏.

Note: This issue is specifically targeted at Azerty keyboard users

**Comment by roblourens** [comment]
We don't have any keybinding customizations based on keyboard layout as far as I'm aware. However you can easily customize the keybinding yourself in our keyboard shortcuts editor
