### ISSUE TITLE
TypeScript installs file watchers, ignoring `files.watcherExclude` setting

### ISSUE THREAD

**Issue by jelmd** [microsoft/vscode#183177]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.78.2
- OS Version: Linux (Ubuntu 20.04)

Steps to Reproduce:

1. mkdir myapp
2. ```sh
cat >package.json<<EOF
{
	"name": "foobar",
	"description": "Test",
	"repository": "https://github.com/x/y",
	"bugs": {
		"url": "https://github.com/x/y/issues"
	},
	"author": "Foo Bar <foobar@do.main>",
	"contributors": [],
	"version": "0.1.0",
	"private": true,
	"scripts": {
		"db": "NODE_OPTIONS='--no-warnings --loader ts-node/esm' nodemon --watch scripts scripts/db.ts",
		"dev": "next dev",
		"build": "next build",
		"start": "next start",
		"lint": "next lint",
		"clean": "rm -rf .next",
		"realclean": "rm -rf .next node_modules package-lock.json"
	},
	"dependencies": {
		"@next-auth/prisma-adapter": "^1.0.6",
		"@prisma/client": "^4.14.1",
		"next": "13.4.3",
		"nodemailer": "^6.9.2",
		"react": "18.2.0",
		"react-dom": "18.2.0"
	},
	"devDependencies": {
		"@styled-icons/material": "^10.47.0",
		"@styled-icons/fa-solid": "^10.47.0",
		"@types/busboy": "^1.5.0",
		"@types/node": "20.2.3",
		"@types/nodemailer": "^6.4.8",
		"@types/react": "18.2.6",
		"@types/react-dom": "18.2.4",
		"eslint": "8.41.0",
		"eslint-config-next": "13.4.3",
		"prisma": "^4.14.1",
		"typescript": "5.0.4"
	}
}
EOF
4. `npm i`
5. with super user privileges:  `sysctl fs.inotify.max_user_watches=4096`
6. adjust excludes in `~/.config/Code/User/settings.json`. E.g.:
```
{
   "files.watcherExclude": {
        "**/.git/objects": true,
        "**/.git/subtree-cache": true,
        "**/.nfs*": true,
        "**/*.swp": true,
        "**/node_modules": true,
        "**/.next": true
    },
 }
```
7. code .

No matter, what you specify, code still watches __all__ directories, even so it is not desired at all to watch anything below `./node_models/`. In the example  above these are ~ 4K directories. This is a huge waste of resources and should be fixed (beside it causes other problems with other misbehaving apps, which do similar insane things ...).

To inspect inotify watches in a very easy way, it is highly recommended to use a tool like [inotify-info](https://github.com/mikesart/inotify-info)!

**Comment by jelmd** [comment]
FWIW: If I set the limit to 16K, code uses 8030 watches for no reason.

**Comment by bpasero** [comment]
It is possible that not VS Code's file watcher is watching these large folders but an extension. As such:

### Is the issue caused by an Extension?
Stop VS Code and from the command line (NOT the integrated terminal in Code), execute: `code --disable-extensions` and try your steps again to see if it reproduces. If it still reproduces, jump to the next chapter.

If you see it is an issue with the extension, please run the command `Start Extension Bisect` and follow the instructions to find the extension that is causing this issue.

<img width="631" alt="image" src="https://user-images.githubusercontent.com/900690/228760008-d5790ad1-74da-46a2-917f-e1bd26281ca8.png">

Please report the issue to the extension causing this.

**Comment by jelmd** [comment]
`--disable-extensions` doesn't change anything:
```
> inotify-info
------------------------------------------------------------------------------
INotify Limits:
  max_queued_events    16384
  max_user_instances   128
  max_user_watches     16384
------------------------------------------------------------------------------
        Pid  App                        Watches   Instances
      625735 code                           7973   1
        4263 csd-xsettings                   45   1
      625686 code                            40   2
        4557 gvfsd-trash                     36   1
        4473 cinnamon                        24   1
        4734 nemo-desktop                     9   1
      625585 code                             7   2
        5623 firefox                          7   1
        4807 gnome-terminal-server            7   1
        4261 csd-color                        5   2
        4146 systemd                          4   3
        4255 csd-automount                    4   1
        4269 csd-sound                        4   1
        4317 csd-power                        4   1
      625626 code                             3   1
        4158 pulseaudio                       2   2
        4551 evolution-source-registry        2   1
        4205 dbus-daemon                      2   1
        4448 goa-identity-service             1   1
        4571 evolution-calendar-factory       1   1
        4586 evolution-addressbook-factory    1   1
        4421 goa-daemon                       1   1
        4742 python3.8                        1   1
        4382 gvfs-afc-volume-monitor          1   1
        4351 gvfs-udisks2-volume-monitor      1   1
        4286 csd-housekeeping                 1   1
        4282 dbus-daemon                      1   1
      625685 code                             1   1
        4260 csd-background                   1   1
------------------------------------------------------------------------------
Total inotify Watches:   8189
Total inotify Instances: 35
------------------------------------------------------------------------------
```
>> If it still reproduces, jump to the next chapter.

???

**Comment by bpasero** [comment]
The glob pattern needs to have trailing `**` to match. Can you use `**/node_modules/*/**` for the node modules one?

**Comment by jelmd** [comment]
Well, not kind of glob pattern this is, but tried as suggested with and w/o `--disable-extensions`: no change, still ~8K watches in use. Attaching a file, which shows all watches - perhaps it helps to ring some bells?

zless -R [inotify-watches.out.gz](https://github.com/microsoft/vscode/files/11559388/inotify-watches.out.gz)

or `gunzip -c inotify-watches.out.gz|less -R`

**Comment by bpasero** [comment]
This only happens with TypeScript project and `node_modules` folder right?

**Comment by jelmd** [comment]
Not really. I just `mkdir foobar; cp -a nextjs_app/node_modules foobar/modules;` added the following lines to `~/.config/Code/User/settings.json::files.watcherExclude`
```
        "**/modules": true,
        "**/modules/**": true,
        "**/modules/*/**": true,
```
and `cd foobar; code .`

Output of inotify-info after opening a file e.g. prisma in modules/.bin/:
```
     1510277 code                           5942   1
     1510125 code                             7   2
     1510233 code                             5   2
     1510167 code                             3   1
     1510232 code                             1   1
```
So I would say no.

**Comment by bpasero** [comment]
Ok just to confirm this is coming from our watcher, can you configure `files.watcherExclude` to be `**`? This is  a hint to entirely disable any recursive file watching in VS Code. Curious if that brings the number down.

**Comment by jelmd** [comment]
Does not work: [settings.json](https://github.com/microsoft/vscode/files/11568787/settings.json.txt)

BTW: if I close all tabs (editors) stop code and start it again, I get
```
     1685869 code                             7   1
     1685778 code                             7   2
     1685819 code                             3   1
     1685868 code                             1   1
```
As soon as I open a file it goes up:
```
     1686650 code                           10109   1
     1685869 code                             7   1
     1685778 code                             7   2
     1685819 code                             3   1
     1685868 code                             1   1
```

**Comment by bpasero** [comment]
Ok that is a good finding, so which file do you open specifically that results in the watch count to increase? Are you opening `package.json` or any file and it goes up?

**Comment by jelmd** [comment]
Tried with https://github.com/KaterinaLupacheva/nextjs-dashboard-layout.git to check, whether it happens on other projects as well: yepp. It seems, that watches explode as soon as a *.js or *.tsx? file gets opened. Stays at ~50 watches, if something else like *.json or .gitignore, LICENSE, etc. gets opened (using the same settings.json posted above).

**Comment by bpasero** [comment]
Thanks, this sounds like the typescript extension is installing watchers, ignoring our setting.

**Comment by jelmd** [comment]
Anybody working on this nasty thing?

**Comment by mjbvz** [comment]
Falls under #193848
