### ISSUE TITLE
VSCode portable mode does not work when move udisk to another computer installed vscode.

### ISSUE THREAD

**Issue by LeoYelton** [microsoft/vscode#183179]
Does this issue occur when all extensions are disabled?: Yes/No

VS Code Version: 1.78.2
 OS Version: win 10.0.19045.2846

Steps to Reproduce:
computer 1 (install both in win10 and put vscode 1.78.2 in udisk）:
1.Store vscode in my udisk, and create a data directly in same dir of Code.exe , instore extensions ,change profile.
2.the data directory has been successfully changed.
![image](https://github.com/microsoft/vscode/assets/29271141/aee4c6df-2eab-423c-abb5-5f00415ca7f1)

Next day , i open my udisk in computer2:
computer 2(have install one in win10, and one in my udisk）
i open the vscode(1.78.2) in my udisk, and doesn't read the data,extension directory in udisk. 
It’s not effective when i change to another computer. 

I also tried the latest insider version: VSCode-win32-x64-1.79.0-insider , it doesn't have an effect either.

**Comment by LeoYelton** [comment]
Oh , i just find the fix way . It is not a bug , but maybe an improvement point. I change the profile
![image](https://github.com/microsoft/vscode/assets/29271141/29c3c90c-749b-48f3-be86-f209ad4f4fb3)
and both extension and theme and profile in udisk were read
![image](https://github.com/microsoft/vscode/assets/29271141/5e204d6c-88e4-4809-82b2-ddc1e7e1e5a9)
![image](https://github.com/microsoft/vscode/assets/29271141/2d8b05aa-a341-4d97-b8ad-c033b71e374f)
I think maybe "default" is not so clear. "Default" of portable vscode should be the profile under data in udisk.

**Comment by sandy081** [comment]
> Oh , i just find the fix way . It is not a bug , but maybe an improvement point. I change the profile

You mean, you changed the profile to **profile** and it worked?

> "Default" of portable vscode should be the profile under data in udisk.

Not sure what you mean, can you please elaborate?

**Comment by LeoYelton** [comment]
> > Oh , i just find the fix way . It is not a bug , but maybe an improvement point. I change the profile
> 
> You mean, you changed the profile to **profile** and it worked?
> 
> > "Default" of portable vscode should be the profile under data in udisk.
> 
> Not sure what you mean, can you please elaborate?

I mean when I change the udisk. What i profile set before should not change. In this case, i config vscode as profile in computer 1, when i change udisk to computer 2 . Vscode auto change the profile to 'Default' instead of 'profile'.
1. So the first improve way is to store the state before（not relation to disk letter)  to avoid auto change to 'Default' which will cause mislead of 'vscode didn't read data directory under udisk'.
2. Second way is to change what word 'Default' means. In portable mode , default should mean what directly config under vscode installation directory.
3. Third way is not to use word 'Default' but more clear and intuitive.
Well , I think first method is better.

**Comment by sandy081** [comment]
> Vscode auto change the profile to 'Default' instead of 'profile'.

Profiles are associated to folders and I assume the location of the folders is changing when you move from one system to another system? Can you please confirm this?

**Comment by LeoYelton** [comment]
> > Vscode auto change the profile to 'Default' instead of 'profile'.
> 
> Profiles are associated to folders and I assume the location of the folders is changing when you move from one system to another system? Can you please confirm this?

I’m so sorry to reply to you so late. I check my mail not so frequently.
You're right, the profile is related to specific project folder. If I choose the project folder, it'll auto change to its' profile. I'm not so familliar with this usage before. 
From my point of view, I just thought when i change to another computer, and not open my project, the portable vscode  will auto read the data directory under my udisk and auto change to the previous profile.

**Comment by sandy081** [comment]
Unfortunately we do not support profile - workspace associations across machines.

**Comment by LeoYelton** [comment]
> Unfortunately we do not support profile - workspace associations across machines.

Thanks for your kindly reply!
