### ISSUE TITLE
C/Cpp No generation of browse.VC.db under 32 bit linux

### ISSUE THREAD

**Issue by je-so** [Microsoft/vscode#18313]
- VSCode Version: Code 1.8.1 (ee428b0eead68bf0fb99ab5fdc4439be227b6281, 2016-12-19T14:55:32.357Z)
- OS Version: Linux ia32 4.4.0-57-generic
- Extensions:

|Extension|Author|Version|
|---|---|---|
|cpptools|ms-vscode|0.9.3|

---

Steps to Reproduce:

1. Generate c_cpp_properties.json and add include path of current workspace.
2. Symbol information is not generated.
3. I think the problem is: ~/.vscode/extensions/ms-vscode.cpptools-0.9.3/bin/Microsoft.VSCode.CPP.Extension.linux is 64-bit binary - no 32-bit binary provided.

**Comment by mjbvz** [comment]
@je-so This looks like a problem with the cpptools extension. @je-so Please try [opening an issue with them](https://github.com/Microsoft/vscode-cpptools/issues)

Thanks
