### ISSUE TITLE
Reload Specific Extension without Reload Window

### ISSUE THREAD

**Issue by domeniczz** [microsoft/vscode#183191]
**_Feature_**:

Reload a specific extension without reloading the whole window.

**_Reason_**:

Because If I reload the window, it's reeeeally resource-intensive.

If I load VS Code without network connection, extensions like github copilot or codeium won't work, but sometimes after connecting my computer to internet, they still didn't work.

Thus, if I want to use these extensions in this scenario, I have to reload the window, and it takes time when I have a large project opened with vscode.

**Comment by wanyukang** [comment]
Is anyone following this issue? I think this is a very valuable feature, and it is also good if it is a lightweight command.

**Comment by alexdima** [comment]
There exists a command called `Developer: Restart Extension Host` which would be suitable for this purpose.
