### ISSUE TITLE
Vscode window is not responding

### ISSUE THREAD

**Issue by HETARTH7** [microsoft/vscode#183108]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.78.2
- OS Version:  11

![Screenshot (215)](https://github.com/microsoft/vscode/assets/89123479/bb6d4d2c-e380-4bb9-9146-61aea9735aa0)

This happens every time I run vs code.
I looked up a previous similar issue. They fixed it by updating the Pylance version. It didn't work for me.
I tried re-installing vs code, disabling all extensions, and logging out.
Even Vscode Insider shows the same issue and also "code" terminal command takes about 15 seconds to run. So, I think something's wrong in my system but I don't know how to fix it.

**Comment by gjsjohnmurray** [comment]
Are you using McAfee antivirus? If so please see https://github.com/microsoft/vscode/issues/178962

**Comment by HETARTH7** [comment]
It works. Thank you for helping me.

**Comment by HETARTH7** [comment]
It works. Thank you for your help.

**Comment by gjsjohnmurray** [comment]
I am glad to have helped. In return please see https://github.com/microsoft/vscode/issues/178962#issuecomment-1547360886, then temporarily remove the exclusion and email @deepak1556 the requested information.
