### ISSUE TITLE
from django.http shows squiggly line error

### ISSUE THREAD

**Issue by eddhyne** [microsoft/vscode#183125]
Type: <b>Bug</b>

Started https://code.visualstudio.com/docs/python/tutorial-django
Got down to Create a Django app #2
entered from django.http import HttpResponse into hello/views
got squiggly error lines under django.http

VS Code version: Code 1.78.2 (b3e4e68a0bc097f0ae7907b217c1119af9e03435, 2023-05-10T14:39:26.248Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8086K CPU @ 4.00GHz (12 x 4008)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.91GB (17.97GB free)|
|Process Argv|. --crash-reporter-id 84602e94-2f46-4c6f-9501-16dea106dc30|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-sqlite|ale|0.14.1
django-vscode|May|1.0.0
yeah|Moe|0.0.1
csharp|ms-|1.25.7
black-formatter|ms-|2023.2.0
python|ms-|2023.8.0
vscode-pylance|ms-|2023.5.30
jupyter|ms-|2023.4.1011241018
jupyter-keymap|ms-|1.1.0
jupyter-renderers|ms-|1.0.15
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-slideshow|ms-|0.1.5
live-server|ms-|0.4.8
powershell|ms-|2023.5.0
django-intellisense|sha|0.0.2
vscode-extension-for-zowe|Zow|2.8.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vstes627:30244334
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
vscccc:30610679
2e4cg342:30602488
pyind779:30671433
f6dab269:30613381
pythonsymbol12:30671437
showlangstatbar:30737416
pythonms35:30701012
cai9j608:30706077
pythonfmttext:30731395
pythoncmv:30739700
fixshowwlkth:30730052
hidesbindicator:30730055
pythongtdpath:30739704

```

</details>

![Snag_5c58de](https://github.com/microsoft/vscode/assets/92999884/776ab8ec-70e3-4034-bf3e-6a7c235c72fc)

**Comment by roblourens** [comment]
Would be helpful to know what the actual warning is. This seems likely an issue with your configuration, but if you think that vscode is doing the wrong thing, please open an issue with some more details on the vscode-python repo

**Comment by eddhyne** [comment]
There are no error messages only squiggly line under all my "from django.    import   "  statements. I thought I opened an issue on vscode.  How do I do that?

**Comment by eddhyne** [comment]
There are no error messages only sqiggly error lines under all my “from django.    Import “ statements. I thought I started a n issue with vscode. How do you do that?

Ed Dhyne
Direct: 954-608-6603
***@***.******@***.***>
www.linkedin.com

**Comment by eddhyne** [comment]
You didn’t recommend any changes. How can you close this issue?

Ed Dhyne
Direct: 954-608-6603
***@***.******@***.***>
www.linkedin.com

**Comment by roblourens** [comment]
If you hover the squiggled text, you will see the message. You opened an issue on vscode, I'm recommending that you open an issue on the vscode-python extension repo, which is presumably where the warning comes from.

**Comment by eddhyne** [comment]
OK Here is the message from the squiggly line. I though I started and issue with vscode and you answered. How do I start an issue with vscode?  Thanks for getting back to me. I really appreciate the response.,

***@***.***

This is were it took me. What do I look for?

***@***.***

Ed Dhyne
Direct: 954-608-6603
***@***.******@***.***>
www.linkedin.com
