### ISSUE TITLE
Enhance built-in sort lines ascending/descending for case insensitivity, remove duplicate lines, numeric sort

### ISSUE THREAD

**Issue by BillDenton** [microsoft/vscode#18315]
- VSCode Version: Code 1.8.1 (ee428b0eead68bf0fb99ab5fdc4439be227b6281, 2016-12-19T14:49:23.350Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions:

|Extension|Author|Version|
|---|---|---|
|read-only-indicator|alefragnani|0.4.0|
|alignment|annsk|0.3.0|
|bettertab|arenl|1.0.1|
|Doxygen|bbenoist|1.0.0|
|python|donjayamanne|0.5.5|
|EditorConfig|EditorConfig|0.3.4|
|vscode-great-icons|emmanuelbeziat|1.1.36|
|matlab|Gimly81|0.4.0|
|status-bar-tasks|GuardRex|0.1.2|
|vscode-dimmer|hoovercj|2.1.0|
|docthis|joelday|0.3.6|
|cpptools|ms-vscode|0.9.3|
|vscode-clearcase|OpenNingia|1.4.1|
|vscode-icons|robertohuertasm|6.0.0|
|theme-cyanicpastels|SamuelLampa|0.0.9|
|indenticator|SirTori|0.2.1|
|vscode-hexdump|slevesque|1.1.4|
|code-spell-checker|streetsidesoftware|0.14.1|
|comment-snippets|Tobiah|0.2.0|
|dark-plus-material|vangware|0.1.4|
|change-case|wmaurer|1.0.0|
|highlight-trailing-white-spaces|ybaumes|0.0.2|

---

Steps to Reproduce:

1. Ctrl+Shift+P sort ascending/descending
2. No options for case insensitivity, remove duplicate lines, numeric sort.

**Comment by sergeevabc** [comment]
Indeed, numeric sort is a crucial thing.
```
Values    Now     Expected                
1         0.5     0.5
100       1       1
0.5       100     3
3         3       100
```

**Comment by alexandrudima** [comment]
To keep the number of issues in our inbox at a manageable level, we're closing issues that have been on the backlog for a long time but haven't gained traction: we look at the number of votes the issue has received and the number of duplicate issues filed. Thank you for your time and understanding.

If you disagree and feel that this issue is crucial: we're happy to listen and to reconsider.

**Comment by BillDenton** [comment]
I work around lack of this feature by opening another editor (SlickEdit) to sort items. I regularly have to sort lists, so argue that this feature is critical.
I'm not happy issues just being closed and so lost. It there any way they could be put on a long-term backlog?

**Comment by sergeevabc** [comment]
> We look at the number of votes the issue has received and the number of duplicate issues filed

How often do ordinary users come to the developer's lair like Github being aware they need to create an account, navigate to Issues, then search for the specific issue and finally vote to get more traction? 

No, sir, ordinary users suffer while you live under delusion that low-voted issues are not significant.

Perhaps reminding you of [sort][1] utility, which was a part of Unix v1 (1971), might bring you back to earth.

[1]: https://en.wikipedia.org/wiki/Sort_%28Unix%29

**Comment by neilsustc** [comment]
Current sorting is not *stable* regarding to letter case

![sort](https://user-images.githubusercontent.com/7588612/34079805-f0e78312-e36f-11e7-8c91-f05ff5fe065d.gif)

**Comment by sergeevabc** [comment]
Traitors.

**Comment by Colecf** [comment]
I don't know how to "vote" on an issue, but I'd also like to see this because https://github.com/google/keep-sorted defaults to case-sensitive sort and removing duplicates.
