### ISSUE TITLE
Ability to disable find & undo shortcuts in File Explorer panel

### ISSUE THREAD

**Issue by anentropic** [microsoft/vscode#183157]
I love VS Code but there is one thing that drives me absolutely nuts...

So many times I will do a `cmd+f` to Find or a `cmd+z` to Undo (and I feel like some others too, maybe Copy and Paste?) but I'll unknowingly have the file explorer pane focused instead of the editor like I was expecting 😖

There are basically no circumstances when I want to do those ops in the file explorer - if I want to search by file name I can `cmd+p` (a distinct shortcut key, yes!)

So I get tripped over by this unnecessary feature. And usually I end up bringing back some previously deleted file too, and don't notice until later when I've committed some junk to a Pull Request

I'm not against having a way to undo file deletes... but please don't make it via `cmd+z` in the file explorer. The number of times I've done that unwantedly vs deliberately must be 10:1 or more

I have seen there is an "Explorer: Enable Undo" setting that i can toggle off, but I don't want to be completely unable to undo, and it still leaves the annoying redundant Find shortcut. So, more concretely, this feature request is:

- disable all overloaded keyboard shortcuts in the file explorer (`cmd+f`, `cmd+z` are the worst, maybe `cmd+c` `cmd+v` too) ...I'd be happy to have to do any file ops very deliberately via right-click menus only
  - being able to undo file ops is potentially useful, can we please have it via a right-click menu or distinct shortcut key though
- the current find feature only highlights visible files anyway (i.e. containing folder tree has to be open), so it's strictly worse than the `cmd+p` file finder that already exists, I think this mis-feature could just go away

**Comment by lramos15** [comment]
You can edit the when expression in your keybinding to have `!filesExplorerFocus` and then undo won't work in the explorer for example

**Comment by ArturoDent** [comment]
See https://stackoverflow.com/a/73739830/836330 for a couple of ways to handle the accidental find in the Explorer problem.

**Comment by lramos15** [comment]
Closing because this should all be achievable with the keybindings editor. If one is not possible please reply back.

**Comment by anentropic** [comment]
How do I undo a file delete in the file explorer without the keybinding?

My issue is partly a complaint that overloading these text-editing shortcuts is a bad default
