### ISSUE TITLE
VS code crash when using find (CTRL+F) across edit and preview tabs

### ISSUE THREAD

**Issue by yavn** [microsoft/vscode#183149]
Type: <b>Bug</b>

1. Launch VS code
2. New text document (CTRL+N)
3. Switch language to Markdown
4. Switch to preview mode (CTRL+SHIFT+V)
5. Open the find box (CTRL+F) and type something in, can be "aaa"
6. Switch back to edit tab
7. Switch back to preview tab
8. VS code will crash

It has been happening for a longer while in release VS code builds.

VS Code version: Code - Insiders 1.79.0-insider (f6be5461f8bc69013a605f5baea834651c6589fb, 2023-05-20T01:18:53.811Z)
OS version: Windows_NT x64 10.0.22621
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 9 5950X 16-Core Processor             (32 x 3400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|63.93GB (57.36GB free)|
|Process Argv|--crash-reporter-id 0c7b0d89-62ee-4805-8940-54d5a266a7a6|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythontb:30258533
pythonptprofiler:30281269
vshan820:30294714
vscod805:30301674
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30404738
cppdebug:30492333
vsclangdf:30492506
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30618038
pylantcb52:30590116
pyind779:30611226
pythonsymbol12:30651887
2i9eh265:30646982
showlangstatbar:30737417
pythonms35:30671666
a2ce3375:30680469
24365598:30687740
pythonfmttext:30716741
pythoncmvfstr:30726892
fixhidewlkth:30724384
hidesbindicator:30724476
pythongtdpath:30726887

```

</details>

**Comment by mjbvz** [comment]
Crash reporter logs:  [crahses.zip](https://github.com/microsoft/vscode/files/11559477/crahses.zip)

**Comment by deepak1556** [comment]
Thanks for the detailed steps, merging to https://github.com/microsoft/vscode/issues/177046
