### ISSUE TITLE
Publish to GitHub creates a repository with a 'master' branch

### ISSUE THREAD

**Issue by egamma** [microsoft/vscode#183158]
I would have expected that the command creates a repository with a branch 'main'. I was using the latest insider:
```
Version: 1.79.0-insider (Universal)
Commit: f6be5461f8bc69013a605f5baea834651c6589fb
Date: 2023-05-20T01:20:35.044Z (3 days ago)
```

This is the repository created using 'Publish to Github' https://github.com/egamma/langchain-demobook.

**Comment by gjsjohnmurray** [comment]
Related to #118182
