### ISSUE TITLE
showSnippets renamed to insertSnippet

### ISSUE THREAD

**Issue by kumarharsh** [Microsoft/vscode#18314]
- VSCode Version: 1.9.0.-insider 83db3c
- OS Version: Windows 10

Steps to Reproduce:
I'd bound "Alt+K S" to `editor.action.showSnippets`. In this build, it's not working.

![image](https://cloud.githubusercontent.com/assets/760112/21766553/34746020-d695-11e6-80fc-3a09bc3f176f.png)

**Comment by bpasero** [comment]
Looks like @jrieken renamed it to `editor.action.insertSnippet` in https://github.com/Microsoft/vscode/commit/9aaa2de60ffe177923eb28d7a83e81cd253b81e2

**Comment by jrieken** [comment]
Yes - we renamed that to the more correct `insertSnippet`. Unsure we should provide a backwards-comp action or just document this...

**Comment by kumarharsh** [comment]
I see. Though when I try to run `insertSnippet` from command palette, it says `cannot read property 'snippet' of null`.

**Comment by jrieken** [comment]
That should be fixed with todays insiders
