### ISSUE TITLE
Be able to enable and hide instead of only enable/disable with git.showActionButton

### ISSUE THREAD

**Issue by gian1200** [microsoft/vscode#183277]
"git.showActionButton" enables/disables the functionality for commit, publish and sync buttons. However, there is no option to show only when there is some action to do. Instead of showing a disabled button, I'd like the option to hide it (I can't click it anyway).

In summary, the new feature/option should be something like "enabled, but show only when clickable"

![image](https://github.com/microsoft/vscode/assets/405347/81581d70-3c7c-48a3-9cf9-e281773c376e)

![image](https://github.com/microsoft/vscode/assets/405347/3cd44a30-636a-46da-8fb1-52406e3f7f41)

**Comment by lszomoru** [comment]
@gian1200, thank you very much for your feedback. Hiding the action button was something that we have tried in the early prototypes. We have found that showing/hiding the button would result in significant jumps in the contents of the "Source Control" view so we have settled on enabling and disabling it.
