### ISSUE TITLE
IntelliSense completions don't account for character symbols (e.g. `@`)

### ISSUE THREAD

**Issue by matteematt** [microsoft/vscode#183200]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.78.2 Commit: b3e4e68a0bc097f0ae7907b217c1119af9e03435
- OS Version: MacOS 12.6.5

I am developing an LSP plugin for typescript and one of the functions is to be able to suggest snippets for [Microsoft Fast Event template bindings](https://www.fast.design/docs/fast-element/declaring-templates#events). This requires sending back `insertText` with a `@` symbol, but this appears not to be accounted for when typing in VSCode. Notice the difference in functionlity between NeoVim where I can type `@cl` and it will filter on the events and let me complete it. In VSCode I have to open the intellisense with no characters to match to get it to work, and then scroll with my mouse and seleect it

https://github.com/microsoft/vscode/assets/43502076/299fdbfd-2acb-4a9c-9ece-e33cfc38bcf7

https://github.com/microsoft/vscode/assets/43502076/fed58558-d5cc-4c79-a794-5d7f740265cc

**Comment by jrieken** [comment]
A completion item provider is invoked, returns completions but they don't show up! 😕  What's the issue? Filtering! Filtering compares completions with a prefix and hides those that don't match.

#### Example

* trigger completions here: `say.he|` (`|` is the cursor)
* provider returns `abc`, `help`, `hood`
* the editor takes the `he`-prefix and scores it against `abc`, `help`, and `hood`. 
* scoring yields these result: 
  * `abc` - no match, don't show
  *  `help` - good match, show
  * `hood`  - no match, only `h` occurs, don't show
* editor shows `help` suggestion, does *not* show `abc` and `hood` suggestion

#### Extensions Rule!

The above sample was using "defaults" to determine the prefix and the filter criteria. 

 * `prefix:`  each completion can define its very own prefix via [`vscode.CompletionItem#range`](https://github.com/microsoft/vscode/blob/47b1183dfda519c32d78b591cfa721d3b0b874ae/src/vs/vscode.d.ts#L3803). Taking the example above, valid prefixes can be `say.he` or `.he` or ` ` (the empty string). Any range is valid as long as it includes the cursor position and is single line only.
* `filter:` each completion can define what string to use when filtering. The default is the label but via [`vscode.CompletionItem#filterText`](https://github.com/microsoft/vscode/blob/47b1183dfda519c32d78b591cfa721d3b0b874ae/src/vs/vscode.d.ts#L3776) any string can be defined

When to use what? It depends on the language, its word definition, and if you control/understand the word definition or not. The defaults usually work well enough but some languages might use a non-intuitive word definition, or completions span multiple words, or completions include non-word character etc. In all those cases the `range`-property should be used.

**Comment by matteematt** [comment]
So for my use case do I need to provide a `range {}` object which ensures that I am capturing the `@` at the start of the text that includes the completion too?

**Comment by matteematt** [comment]
@jrieken is what you have suggested specically for a vscode plugin rather than a generic LSP reponse? Apologies if I have misunderstood but when I look at the interface I am working with [here](https://github.com/microsoft/TypeScript/blob/2beeb8b93143f75cdf788d05bb3678ce3ff0e2b3/tests/baselines/reference/api/tsserverlibrary.d.ts#L1809) I don't see the `range` item you're talking about

**Comment by jrieken** [comment]
LSP is same, same but slighty different. I believe in there it' not range but embedded in the text edit

**Comment by matteematt** [comment]
So if we strip the problem back to a high level, I need to find in the API a setting where I can specify a range that includes the `@` symbol so VSCode will use that in the filter text, and will not filter the `@click` `@mousedown` events?

**Comment by jrieken** [comment]
yes
