### ISSUE TITLE
using ctrl+c is invalid in terminal

### ISSUE THREAD

**Issue by putoputoputo** [microsoft/vscode#183298]
Type: <b>Bug</b>

1.Open a vue project
2.Use the command "npm run dev"，normal project startup
3.I'm gonna use "control+c", Project will not be terminated

VS Code version: Code 1.78.2 (Universal) (b3e4e68a0bc097f0ae7907b217c1119af9e03435, 2023-05-10T14:44:45.204Z)
OS version: Darwin x64 18.7.0
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5350U CPU @ 1.80GHz (4 x 1800)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|56, 44, 22|
|Memory (System)|8.00GB (0.29GB free)|
|Process Argv|-psn_0_2777766 --crash-reporter-id ed56607b-9639-4b9b-bb68-6e4ab2de45de|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (17)</summary>

Extension|Author (truncated)|Version
---|---|---
path-intellisense|chr|2.8.4
cssrem|cip|3.1.0
vscode-eslint|dba|2.4.0
jquerysnippets|don|0.0.1
gitlens|eam|13.6.0
prettier-vscode|esb|9.12.0
auto-rename-tag|for|0.1.10
vscode-view-in-browser|kop|1.0.5
easy-less|mrc|2.0.0
vscode-language-pack-zh-hans|MS-|1.78.2023051009
LiveServer|rit|5.7.9
open-in-web|VCa|1.0.1
vscode-icons|vsc|12.4.0
volar|Vue|1.2.0
vscode-typescript-vue-plugin|Vue|1.6.5
JavaScriptSnippets|xab|1.8.0
material-theme|zhu|3.15.14

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vscaac:30438847
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
282f8724:30602487
pyind779:30671433
89544117:30613380
pythonsymbol12:30671437
a9j8j154:30646983
showlangstatbar:30737416
vsctsb:30748421
pythonms35:30701012
pythonfmttext:30731395
pythoncmv:30739700
fixhidewlkth:30730051
pythongtdpathcf:30739705

```

</details>

**Comment by AceYangWQ** [comment]
> /duplicate #181939
VS Code version: 1.79.0/1.79.1  still has a problem，I'll update the latest version 1.79.2 later
