### ISSUE TITLE
Search panel results are hard to visually skim

### ISSUE THREAD

**Issue by wavebeem** [Microsoft/vscode#18326]
- **VSCode Version:** 1.8.1
- **OS Version:** macOS Sierra 10.12.2

## Steps to Reproduce:

1. `Command-Shift-F` and search for something
2. Observe that the filename headers and search results are not easily visually separated

## Code

![image](https://cloud.githubusercontent.com/assets/176815/21776302/b56b90d2-d64e-11e6-80df-ab515b0f0f0c.png)

## Sublime

![image](https://cloud.githubusercontent.com/assets/176815/21776313/c0b8c95a-d64e-11e6-93c4-f50791977056.png)

## Description

In Sublime there is some spacing between the the search result groups, and the filenames have a different color. This makes it a lot easier for me to skim results. It'd be nice to have something similar in Code.

**Comment by roblourens** [comment]
This feature request will not be considered in the next [6-12 months roadmap](https://github.com/Microsoft/vscode/wiki/Roadmap) and as such will be closed to keep the number of issues we have to maintain actionable. Thanks for understanding and happy coding!
