### ISSUE TITLE
VS code crashing upon launch, reason: 'crashed' code: '-1' 

### ISSUE THREAD

**Issue by lopez2000** [microsoft/vscode#183247]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 
- OS Version: 

Steps to Reproduce:

1. 
2.

**Comment by lopez2000** [comment]
Does this issue occur when all extensions are disabled?: Dont know

VS Code Version: 1.78.2
OS Version: Win10 22H2
Steps to Reproduce: Start vs code

**Comment by lopez2000** [comment]
![image](https://github.com/microsoft/vscode/assets/62019546/94961b16-c52d-4adc-9763-b84b69dcc5b6)

I followed the steps and keeps on crashing. even with vs code insiders. When I run the last command you suggested, this happens. Thanks for the help.

**Comment by lopez2000** [comment]
I realized that this happened after I ran Chromedriver. Also, slack and discord are crashing now, I need help :(

**Comment by meganrogge** [comment]
It sounds like your system has an issue. You can check if this is as a result of VS Code by uninstalling it, but I really doubt this is caused by our app
