### ISSUE TITLE
OSError: No Default Input Device Found

### ISSUE THREAD

**Issue by Celvenia** [microsoft/vscode#183210]
Type: <b>Bug</b>

This is separate code from what produced the OSError but they seem related. Using the following code i get no input or output devices found. My default mic on my Surface Pro 7 is what i'm using and although everything it checked on Microphone Privacy Settings I don't see VS Code listed as ever asking for mic access so perhaps that could be the reason.

import sounddevice as sd
import pyttsx3
import speech_recognition as sr
import pyaudio

def print_default_device_info():
    default_input_device = sd.default.device[0]
    default_output_device = sd.default.device[1]
    devices = sd.query_devices()
    print(sd.get_portaudio_version())

    print("Available Input Devices:")
    for device in devices:
        print(f"   device: {device}")
        print(f"   Name: {device['name']}")
        print(f"   Index: {device['index']}")
        print(f"   Sample Rate: {device['default_samplerate']}")
        print(f"   Channels: {device['max_input_channels']}")

    print("\nDefault Input Device:")
    for device in devices:
        if device['name'] == default_input_device:
            print(f"   Name: {device['name']}")
            print(f"   Index: {device['index']}")
            print(f"   Sample Rate: {device['default_samplerate']}")
            print(f"   Channels: {device['max_input_channels']}")

    print("\nAvailable Output Devices:")
    for device in devices:
        print(f"   Name: {device['name']}")
        print(f"   Index: {device['index']}")
        print(f"   Sample Rate: {device['default_samplerate']}")
        print(f"   Channels: {device['max_output_channels']}")

    print("\nDefault Output Device:")
    for device in devices:
        if device['name'] == default_output_device:
            print(f"   Name: {device['name']}")
            print(f"   Index: {device['index']}")
            print(f"   Sample Rate: {device['default_samplerate']}")
            print(f"   Channels: {device['max_output_channels']}")

print_default_device_info()
print(sd.query_devices(), 'testing')

p = pyaudio.PyAudio()
for index in range(p.get_device_count()):
    info = p.get_device_info_by_index(index)
    print(f"Device {index}: {info['name']}")

VS Code version: Code 1.78.2 (b3e4e68a0bc097f0ae7907b217c1119af9e03435, 2023-05-10T14:39:26.248Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: Yes
Remote OS version: Linux x64 5.10.16.3-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz (8 x 1498)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.60GB (7.83GB free)|
|Process Argv|--crash-reporter-id 19da0f26-6257-4644-be6e-431ad626a0f2|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 5.10.16.3-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz (8 x 1497)|
|Memory (System)|7.57GB (6.73GB free)|
|VM|0%|
</details><details><summary>Extensions (20)</summary>

Extension|Author (truncated)|Version
---|---|---
codesandbox-projects|Cod|0.2.88
es7-react-js-snippets|dsz|4.4.3
jupyter-keymap|ms-|1.1.0
remote-ssh|ms-|0.102.0
remote-ssh-edit|ms-|0.86.0
remote-wsl|ms-|0.78.7
remote-explorer|ms-|0.4.0
sqlite-viewer|qwt|0.2.5
simple-react-snippets|bur|1.2.7
prettier-vscode|esb|9.12.0
pip-packages|etm|0.4.3
code-runner|for|0.12.0
python|ms-|2023.8.0
vscode-pylance|ms-|2023.5.30
jupyter|ms-|2023.4.1011241018
jupyter-keymap|ms-|1.1.0
jupyter-renderers|ms-|1.0.15
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-slideshow|ms-|0.1.5
LiveServer|rit|5.7.9

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscorecescf:30445987
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
3biah626:30602489
pyind779:30671433
f6dab269:30613381
pythonsymbol12:30671437
2i9eh265:30646982
showlangstatbar:30737416
vsctsb:30748421
pythonms35:30701012
pythonfmttext:30731395
fixhidewlkth:30730051
hidesbindicator:30730055
pythongtdpath:30739704

```

</details>

**Comment by roblourens** [comment]
Sounds like this is an issue with your code or your system configuration. If you think that vscode is doing the wrong thing, please give more details about why it's a vscode issue.
