### ISSUE TITLE
Can't attach VSCode Docker when using VSCode Tunnels connect.

### ISSUE THREAD

**Issue by sanbuphy** [microsoft/vscode#183283]
Does this issue occur when all extensions are disabled?: Yes/No
No

- VS Code Version:  lastest version
- OS Version:  ubuntu 20.04 (remote)    windows11(local)

Steps to Reproduce:

I recently discovered the functionality of tunnels and found it to be great in helping me reduce a lot of development pressure. However, I have encountered an issue where I am unable to attach Docker to VSCode when i using Tunnels. Although I can see which containers are running and attach them to the terminal, I receive an error message when attempting to attach them to VSCode. The error message indicates that there are no currently running containers available.

Thank you very much.

**Comment by gjsjohnmurray** [comment]
This issue might belong at https://github.com/microsoft/vscode-docker/issues if that is the extension you are using to integrate Docker with VS Code.

**Comment by sanbuphy** [comment]
> This issue might belong at https://github.com/microsoft/vscode-docker/issues if that is the extension you are using to integrate Docker with VS Code.
Thank you, I will try to ask for help there
