### ISSUE TITLE
Add Stop Push Button for Error and Infinite Loading Handling

### ISSUE THREAD

**Issue by On1zuma** [microsoft/vscode#183223]
Hi, You should add a prominent button to stop the push process in case of an error or, as is currently happening in my case, an infinite loading issue from my previous push. This would enable users to proceed more efficiently and retrieve any changes that were not pushed correctly. Specifically, the feature should retain the changes that have been successfully pushed while preserving the new changes that have not yet been pushed. In my situation, I was unaware that the push did not work, and as a result, I am unable to see my new code.

<img width="462" alt="image" src="https://github.com/microsoft/vscode/assets/96482486/6d847161-5f09-4af7-8555-5671256fdf48">

**Comment by hamedonassar95** [comment]
Pkg

**Comment by On1zuma** [comment]
@lszomoru, That happens when I make a commit followed by a push to my GitHub repository. Sometimes, I encounter an infinite loading issue that can only be resolved by closing VSCode and losing all the commits.

My VSCode workspace is a clone of a GitHub repository, and I am connected to GitHub with my GitHub account.

I don't have access to any specific Git error logs at the moment, but it is possible that the issue I am experiencing is related to the problem discussed in this GitHub issue: https://github.com/microsoft/vscode/issues/121231

**Comment by lszomoru** [comment]
@On1zuma, thanks for getting back to me on this. If you are able to reproduce the issue again please share the contents of the [git output window](https://code.visualstudio.com/docs/sourcecontrol/overview#_git-output-window), as well as any errors that you receive. Hopefully that will help us track down the root cause. Thanks!
