### ISSUE TITLE
Rethink Diff Review

### ISSUE THREAD

**Issue by hediet** [microsoft/vscode#183228]
The Diff Review feature is exclusively for screen reader users.
Thus I would suggest to rename it to "Accessible Diff Viewer".

Currently, it is implemented as a modal experience. I think it would make more sense to implement it as a third mode, next to side-by-side diff view and inline diff view.

Also, consumers of the diff editor should be able to open the review mode by default.

cc @meganrogge @alexdima

**Comment by hediet** [comment]
Verification steps:
* Verify the "Diff Review" feature is now branded as "Accessible Diff Viewer" everywhere (in F1, command names and menu entry names). Check the available commands when a diff editor is opened.
* Verify there is "Open Accessible Diff Viewer" in this menu, and it works:
![XHzwfZx2uS](https://github.com/microsoft/vscode/assets/2931520/f9e7366b-4b0e-4786-b588-cac6ca04eb63)

**Comment by roblourens** [comment]
Works but shouldn't "Open Accessible Diff Viewer" be in the command palette as well?

<img width="631" alt="image" src="https://github.com/microsoft/vscode/assets/323878/cf36d151-8557-433d-914d-5bf8965babd2">

**Comment by hediet** [comment]
> Works but shouldn't "Open Accessible Diff Viewer" be in the command palette as well?

This would just be an alias of "Go to Next Difference".

**Comment by roblourens** [comment]
Oh, got it
