### ISSUE TITLE
Loading editor: initial text is black on black

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#18320]
- VSCode Version: 1.9 insiders
- OS Version: macOS

Steps to Reproduce:

1. reload window with dark theme
2. pay attention to the editor text

=> it shows as black on dark background

![view-picker](https://cloud.githubusercontent.com/assets/900690/21771399/7da580b6-d687-11e6-91f1-426a0b916209.gif)

**Comment by alexandrudima** [comment]
@aeschli @bpasero The theme service needs to help me out here. I call `themeService.getColorThemeDocument()`. That one is null until the theme is fully loaded. Perhaps the theme service could know if a dark or white theme is being loaded very quickly and provide a corresponding "fake" theme document until the real theme document is loaded.

**Comment by alexandrudima** [comment]
fyi @egamma This is the bug you mentioned.
