### ISSUE TITLE
workbench.action.focusNextGroup spawns unwanted split view editor when in the right-most editor group

### ISSUE THREAD

**Issue by JarvisPrestidge** [Microsoft/vscode#18324]
- VSCode Version: 1.8.1
- OS Version: Windows 7 Professional

Steps to Reproduce:

1. Have one or many editors open in one or many groups.
2. Navigate to the right most editor and group.
3. Trigger the workbench.action.focusNextGroup command (i.e. via keybinding - in my example .gif I've bound to Alt+L)

Result: An unwanted(?) split view editor is created as a copy of the right most editor

![issue](https://cloud.githubusercontent.com/assets/6669336/21774863/dd0c89ba-d68b-11e6-9a4d-5659ac88e803.gif)

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/12833
