### ISSUE TITLE
POSH Module Intellisense Not Working

### ISSUE THREAD

**Issue by cajunitalian** [Microsoft/vscode#18325]
- VSCode Version: 1.8.1
- OS Version: Windows 10

Steps to Reproduce:

1. Install PowerCLI (New Version) - 6.5 - Module Based

Unable to use intellisense w/ PowerCLI Module Cmdlets.  See my screenshot, you'll see the PowerCLI Module path is clearly in $env:PSModulePath (C:\VMware\Infra\PowerCLI\Modules)*

*Yes, I am writing in a .ps1 file.  Powershell is working, just not intellisense for that module.

![image](https://cloud.githubusercontent.com/assets/1809840/21776068/48b951ee-d65e-11e6-80f5-f34a228a62b5.png)

**Comment by cajunitalian** [comment]
Here's an example of Connect-VIServer, you can see it's not working.

![image](https://cloud.githubusercontent.com/assets/1809840/21776220/18321668-d65f-11e6-9513-601b4162a108.png)

**Comment by mjbvz** [comment]
This looks like an issue with the powershell extension since it is what provides IntelliSense here.

@cajunitalian Please [open the issue against the powershell extension](https://github.com/PowerShell/vscode-powershell/issues)

Thanks
