### ISSUE TITLE
How to configure the active text color of the parameter hints pop-up box🙏

### ISSUE THREAD

**Issue by performence** [microsoft/vscode#183284]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 
- OS Version: 

Steps to Reproduce:
![image](https://github.com/microsoft/vscode/assets/56541757/499f2713-5dad-4da0-845c-23604db71b49)
![image](https://github.com/microsoft/vscode/assets/56541757/10414fe9-48df-48c1-aa05-0bcf209a0e76)

1.  How to configure the active text color of the parameter hints pop-up box 🙏
2.

**Comment by gjsjohnmurray** [comment]
Please try `editorHoverWidget.background`

**Comment by performence** [comment]
> Please try `editorHoverWidget.background`

![image](https://github.com/microsoft/vscode/assets/56541757/8022f5ff-c6c7-4fe5-9de7-2edb49e12ca4)
i want to change active text color,not background color

**Comment by mjbvz** [comment]
Try `editorHoverWidget.highlightForeground`
