### ISSUE TITLE
Feature request: Make "Go to Bracket" work with selections

### ISSUE THREAD

**Issue by danvk** [Microsoft/vscode#18322]
- VSCode Version: Version 1.8.1 (1.8.1)
- OS Version: OS X 10.11.4 (15E65)

With some code like this:

```
{
   blah
}
```

1. Move the cursor after the closing brace.
1. Hit <kbd>cmd</kbd>+<kbd>shift</kbd>+<kbd>\\</kbd> to bounce to the matching open brace.
1. Now _select_ the closing brace.
1. Hitting <kbd>cmd</kbd>+<kbd>shift</kbd>+<kbd>\\</kbd> does nothing.

It should select the braces and everything in between them. I use this in vim (with `v%`) all the time to copy/paste code blocks.

**Comment by mikelward** [comment]
Also, the binding for jumpToBracket should not use Shift, so that holding Shift will implement jumpToBracketSelect or similar.

**Comment by rebornix** [comment]
Dup of https://github.com/Microsoft/vscode/issues/9768, let's track it there. It's on our deck now.
