### ISSUE TITLE
VScode crashes when I open it. The window terminated unexpectedly (reason: 'crashed', code: '-1073741502')

### ISSUE THREAD

**Issue by hkax** [microsoft/vscode#183302]
I try to reinstall it,but it report this .
![image](https://github.com/microsoft/vscode/assets/29496925/41ae9f9c-51c7-48d1-9623-498c451bb32c)
![image](https://github.com/microsoft/vscode/assets/29496925/0e8756a7-6b19-4781-8bf7-3cd1438e5f25)

Does this issue occur when all extensions are disabled?: Yes

- VS Code Version:  1.78.2
- OS Version:  window10

Steps to Reproduce:

1. reinstall 
2. close and open,it crash.

**Comment by forReak** [comment]
I also have the same problem, have you fixed vscode? How was it repaired?

**Comment by hkax** [comment]
I had solve this problem , I add the -no-sandbox in the end .it works.
![image](https://github.com/microsoft/vscode/assets/29496925/b209571b-2ab7-4fd2-84a0-e1862002ba8d)

**Comment by deepak1556** [comment]
Refs https://code.visualstudio.com/updates/v1_80#_disable-chromium-sandbox
