### ISSUE TITLE
Accidentally cleared entire wsl data from vscode

### ISSUE THREAD

**Issue by osayes** [microsoft/vscode#183319]
After using vscode and wsl for a long time, there are too many folders on the wsl targets of vscode, so I want to clear all these folders and clicked a delete button around the wsl targets, then I can't connect to wsl any more
I checked the wsl root folder on the windows, and found that the root folder is decreased to < 2GB from > 100GB, I realized all system/program/code/... data is gone

（Speechless...)

**Comment by aeschli** [comment]
The `x` button next to the folder doesn't delete any data.
I hope you didn't invoke the `Delete Distro` command in the context menu. That one really release the distro and the data, just as the dialog says.

Run `wsl --list` to see if your distro is still around.

**Comment by osayes** [comment]
I indeed invoked the `Delete Distro` command, I didn't realized it will delete all, I supposed that the wsl system can only be deleted from powershell(after all, once it is installed, it is rarely deleted)

**Comment by aeschli** [comment]
Sorry for that, that's horrible. I hope you were able to recover your work.
When adding the `add distro` functionality I thought having delete would be good to have too.

I was hoping the the dialog message was clear enough. I see how I can improve it.
