### ISSUE TITLE
scratchpad editors should not confirm on window close when `hotexit` = `onexit`

### ISSUE THREAD

**Issue by amunger** [microsoft/vscode#183378]
follow up on https://github.com/microsoft/vscode/issues/174485

we should change the logic to just backup/recover scratchpad working copies when a window is closed, rather than prompting and forcing the user to save/discard.

https://insiders.vscode.dev/github/microsoft/vscode/blob/main/src/vs/workbench/services/workingCopy/electron-sandbox/workingCopyBackupTracker.ts#L151

**Comment by bpasero** [comment]
👍 , I think the interesting method to look at is:

https://github.com/microsoft/vscode/blob/51325c051938da4e90665f55b2a252d25cd91dfa/src/vs/workbench/services/workingCopy/electron-sandbox/workingCopyBackupTracker.ts#L165

This decides globally based on the `hot.exit` setting if backups should perform, but then would have to decide on a per-workingcopy basis.
