### ISSUE TITLE
The window terminated unexpectedly crash code "-1"

### ISSUE THREAD

**Issue by sidharthhhh** [microsoft/vscode#183362]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.78.2
- OS Version: 22621.265

Steps to Reproduce:

1. Install latest version of VSCode

![Screenshot 2023-05-25 010422](https://github.com/microsoft/vscode/assets/90138886/326655c2-d3c9-4614-818e-69f750b6340f)

**Comment by deepak1556** [comment]
Can you provide the crash logs following the steps at https://github.com/microsoft/vscode/wiki/Native-Crash-Issues#creating-a-crash-report, thanks!

**Comment by sidharthhhh** [comment]
now the bug is fixed automatically after 12-13hr, thanks!
