### ISSUE TITLE
Collapsible state of child tree items persists after refreshing entry

### ISSUE THREAD

**Issue by david-tejada** [microsoft/vscode#183360]
- VS Code Version:  1.78.2
- OS Version: macOS 12.6.3

I'm not sure if this is a bug or if I'm not understanding completely how this work but I would expect that after calling `this._onDidChangeTreeData.fire(entry)` the child entries are collapse since when calling `getChildren` all the folder entries are created as collapsed. In the debugger I can actually see that the entries are created as collapsed so I don't understand why they remain expanded.

Here is a [demo repository](https://github.com/david-tejada/vscode-refresh-treeitem) to showcase what I mean.

![demo](https://github.com/microsoft/vscode-discussions/assets/3219671/a5aa1578-a7f2-446e-9536-847a0d9f5cd3)

**Comment by alexr00** [comment]
User state wins over extension state. The user has already expanded the items so they stay expanded. This is so that you don't get bad expanding/collapsing behavior when refreshing your tree. If you want them to collapse you can give the tree items a different ID when you refresh the tree.

**Comment by david-tejada** [comment]
Of course, I'll do the id thing. Thanks a lot, Alex, you're the best!
