### ISSUE TITLE
Background terminal scroll bars are not synced when the foreground terminal is resized

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#18332]
- VSCode Version: Code - Insiders 1.9.0-insider (12af9ea6effefeaeecde2107c960ae5222703864, 2017-01-09T07:18:17.300Z)
- OS Version: Linux x64 4.8.0-30-generic
- Extensions:

|Extension|Author|Version|
|---|---|---|
|EditorConfig|EditorConfig|0.3.4|
|lorem-ipsum|Tyriar|1.0.0|
|sort-lines|Tyriar|1.1.0|
|theme-glacier|Tyriar|0.0.10|
|vscode-svgviewer|cssho|1.3.0|
|vscode-eslint|dbaeumer|1.2.2|
|python|donjayamanne|0.5.5|
|tslint|eg2|0.8.1|
|git-project-manager|felipecaputo|1.0.0|
|Theme-Wombat|gerane|0.0.2|
|md-navigate|jrieken|0.0.1|
|vscode-scss|mrmlnc|0.6.0|
|typescript-javascript-grammar|ms-vscode|0.0.14|
|seti-icons|qinjia|0.1.3|
|sass-indented|robinbentley|1.3.0|
|dark-plus-material|vangware|0.1.4|

---

Steps to Reproduce:

1. Open 2 terminals
2. Increase vertical size of terminal
3. Switch to other terminal, the viewport's scroll bar will be the size it was before the resize

Notice the viewport is at the bottom but the scroll bar is in the middle:

![image](https://cloud.githubusercontent.com/assets/2193314/21777826/7ad9515a-d655-11e6-9a8e-10c9d99dc5b7.png)

**Comment by dbaeumer** [comment]
Verified under Windows.
