### ISSUE TITLE
sync git without requiring internet access on remote server

### ISSUE THREAD

**Issue by Jason3900** [microsoft/vscode#183391]
Currently, the git related options are executed on the remote host. There're some cases where the remote hosts have network isolation/restriction for security reasons. Without internet access, we can't sync git project with vscode. We may need a option to manipulate git pull/push/... locally and only synchronize results on the remote server.

**Comment by lszomoru** [comment]
@Jason3900, thanks for filing this issue. The built-in extensions that provide git functionality (vscode.git-base, vscode.git) are both workspace extensions which means that they will always be installed and run on the remote extension host. While you can control where an extension is installed using the `remote.extensionKind` setting, running these extensions on the host is not a supported scenario. As of right now, we have no plans for supporting running the git extensions on the host machine.
