### ISSUE TITLE
TypeScript quick fix for implementing interface missing

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#183323]
![image](https://github.com/microsoft/vscode/assets/900690/f1d6fe58-b28a-4bc1-91ec-d3595371accf)

Add the following line to:

https://github.com/microsoft/vscode/blob/e7e97f8ea8519885e13dac9df6eae7c747d531b1/src/vs/workbench/services/untitled/common/untitledTextEditorInput.ts#L24

```ts
override closeHandler = this;
```

See how there is no quick fix to implement the `IEditorCloseHandler`:

![image](https://github.com/microsoft/vscode/assets/900690/9d184028-8d1d-4941-a263-7dceff7b697b)

**Comment by mjbvz** [comment]
The implement interface quick fix is shown when the class already lists `implements interface`. The quick fix than add the required methods/properties from the interface

It seems like this example is more: `make this type conform to the required interface`. That may be helpful in this specific example but I'd be concerned that we'd show such a quick fix in many more non-useful cases too (basically anytime there is a type erro)
