### ISSUE TITLE
C++ colorization is incorrect after a multi-line ? : expression.

### ISSUE THREAD

**Issue by sean-mcmanus** [Microsoft/vscode#18337]
- VSCode Version: 1.8.1
- OS Version: Windows (I assume Linux/OSX too).

Steps to Reproduce:

1. Use this code in a .cpp file.
long A() {
    return true ?
        Sum() : 0;
}

class Bar {

};

Bug: "class Bar" is white instead of colored correctly. It's a bug with textmate, atom, or whatever other thing VS code users for colorization.

This report is from https://github.com/Microsoft/vscode-cpptools/issues/438 .

**Comment by aeschli** [comment]
This issue was moved to atom/language-c#196

**Comment by sean-mcmanus** [comment]
@aeschli They fixed the bug in atom/language-c (along with other bug fixes). When can we expect this fix to be integrated into VS Code?

**Comment by aeschli** [comment]
It will be part of the January build. You can already try it out in the [insiders](https://code.visualstudio.com/insiders) release.
