### ISSUE TITLE
Markdown anchor links not working using <a name=""></a> in VSCode Preview

### ISSUE THREAD

**Issue by agabhinav** [microsoft/vscode#183343]
Anchor links with &lt;a name=""&gt;&lt;/a&gt; don't work properly in the Markdown Preview of VSCode, but they work fine with &lt;a id=""&gt;&lt;/a&gt;. I tested the same file in another markdown editor, Ghostwriter, and all the links worked correctly there. Links also function properly when viewed on GitHub's website. So, the problem seems to be limited to the Markdown Preview feature in VSCode.

OS Name: Microsoft Windows 10 Enterprise  
VSCode 1.78.2  
Extensions: WSL, Git Graph, Markdown Preview Mermaid Support  

To replicate the problem, open this markdown file in VSCode and then launch the Markdown Preview.
[TestInternalLinks.md](https://github.com/microsoft/vscode/files/11556661/TestInternalLinks.md)

**Comment by weartist** [comment]
I'm on it

**Comment by weartist** [comment]
@mjbvz I have a question. Is it true that HTML5 specification no longer supports jumping to <a name="xx"></a>, and only supports <a id="xx"></a>? If we want to support jumping to name, do we need to customize click events or generate id tags along with name tags? thanks!

**Comment by mjbvz** [comment]
Here's the relevant spec: https://html.spec.whatwg.org/multipage/browsing-the-web.html#find-a-potential-indicated-element

Looks like `name` is still supported for `a` elements

**Comment by weartist** [comment]
> Here's the relevant spec: https://html.spec.whatwg.org/multipage/browsing-the-web.html#find-a-potential-indicated-element
> 
> Looks like `name` is still supported for `a` elements

Strangely I tried it,  `name` does not work when anchor jumps, I looked at the solution of other websites, they jump by assigning href, I don't know if we can accept this treatment in this case, if we allowed, I can submit my modifications

**Comment by mjbvz** [comment]
Given the lack of further interest in this issue, I'm going to close this. Would still accept a PR if someone is passionate about it

**Comment by weartist** [comment]
> Given the lack of further interest in this issue, I'm going to close this. Would still accept a PR if someone is passionate about it

Can we solve this with `href`？

**Comment by agabhinav** [comment]
It'll be great if it could work with <a name=""></a>
