### ISSUE TITLE
PHP syntax coloring lost after encountering '?>' in comments

### ISSUE THREAD

**Issue by tarunzoot** [Microsoft/vscode#18333]
- VSCode Version: 1.8.1
- OS Version: OS X El Capitan 10.11.6

Steps to Reproduce:

1. Paste following code into the editor
`
file_get_contents('localfile.txt'); // shown in color
// $doc = new DOMDocument();
// libxml_use_internal_errors(true);

// $doc->loadHTML('<?xml encoding="utf-8"?>'.file_get_contents('dietlast.com.html'), LIBXML_NOBLANKS | LIBXML_NOCDATA | LIBXML_NOWARNING | LIBXML_ERR_WARNING);

// just black text is rendered from here onwards
file_get_contents('localfile.txt');
`
<img width="1180" alt="screenshot" src="https://cloud.githubusercontent.com/assets/18568258/21778331/00af3132-d6c9-11e6-82f3-780fbd094a79.png">

Comments are also behaving weirdly. For eg.
comment this line with shortcut [cmd | ctrl]+/
`// $doc->loadHTML('<?xml encoding="utf-8"?>'.file_get_contents('localfile.html'), LIBXML_NOBLANKS | LIBXML_NOCDATA | LIBXML_NOWARNING | LIBXML_ERR_WARNING);`

now try commenting the next line with [cmd | ctrl]+/, instead of php's comments, html comments are applied.
<img width="1180" alt="shot" src="https://cloud.githubusercontent.com/assets/18568258/21779369/618cd47e-d6cd-11e6-84a0-1db4e7a26dda.png">

**Comment by mattacosta** [comment]
PHP terminates line comments upon encountering a line break or a close tag so that's actually the correct behavior.

**Comment by roblourens** [comment]
Agreed, I have 

``
echo "a\n";
// ?>
echo "b\n";
```

Result:

```
$ php ./scratch.php

echo "b\n";
```
