### ISSUE TITLE
The window terminated unexpectedly (reason: 'launch-failed', code: '40') 

### ISSUE THREAD

**Issue by duyhieu97bn** [microsoft/vscode#183341]
The window terminated unexpectedly (reason: 'launch-failed', code: '40') 
We are sorry for the inconvenience. You can reopen the window to continue where you left off.

Does this issue occur when all extensions are disabled?: No

VS Code Version: 1.78.2
OS Version: Client: Windows 10

Steps to Reproduce:

1.  Turn on features SMB 1.0/CIFS File Sharing Support
2. Restart Windows when VScode still open

Uninstalled VScode and reinstall but still error
created new account in window and install vscode but still error

**Comment by rzhao271** [comment]
Hi, could you follow the instructions to [create a crash report](https://github.com/microsoft/vscode/wiki/Native-Crash-Issues#creating-a-crash-report), and then attach the zip file here?

**Comment by duyhieu97bn** [comment]
Oh , I think the problem was because my company's software affected vscode.

"Warning: PowerShell detected that you might be using a screen reader and has disabled PSReadLine for compatibility purposes. If you want to re-enable it, run 'Import-Module PSReadLine'."

Thanks for your support
