### ISSUE TITLE
Cannot open same workspace via "Open Recent" with two different profiles

### ISSUE THREAD

**Issue by darkvertex** [microsoft/vscode#183333]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.78.2 (user setup)
- OS Version: Windows_NT x64 10.0.22621

Steps to Reproduce:

1. Make a secondary settings profile, say we call it "ProfileB".
2. Make a new window and switch to ProfileB.
3. In this ProfileB window, open a repo and keep that window open.
4. From the original window using the default profile, go to Open Recent -> and try to open your recently opened repo.
5. Observe that VSCode instead brings focus to the ProfileB window, instead of opening the repo in the default profile like expected.

VSCode should not bring focus to an open window when it is not in the same profile as you are opening from. I should be able to open the same repo in the default profile and any secondary profiles I feel like.

I'm trying to investigate another bug for an extension developer and wanted to make a secondary profile to compare extensions and this annoyance is making it quite cumbersome.

**Comment by sandy081** [comment]
Its current design that a folder can be opened only in one window.

@bpasero If there is an issue already for this, please mention.

Thanks.

**Comment by bpasero** [comment]
https://github.com/microsoft/vscode/issues/2686
