### ISSUE TITLE
editor.linkedEditing for html in php files

### ISSUE THREAD

**Issue by Morgy93** [microsoft/vscode#183316]
Hello,

the `editor.linkedEditing` (https://code.visualstudio.com/Docs/languages/html#_auto-update-tags) feature only works for file type HTML.
But if you use file type PHP which may contain HTML code, it should work as well.

Would love to have this feature expanded to other file types ❤️

**Comment by aeschli** [comment]
You need to file this as feature request against the PHP extension that you use.
