### ISSUE TITLE
Built-in VB language LT / GT operators may appear not as operator color

### ISSUE THREAD

**Issue by msftrncs** [microsoft/vscode#183359]
Does this issue occur when all extensions are disabled?: Yes

Version: 1.78.2 (user setup)
Commit: b3e4e68a0bc097f0ae7907b217c1119af9e03435
Date: 2023-05-10T14:39:26.248Z
Electron: 22.5.2
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Windows_NT x64 10.0.22621
Sandboxed: Yes
Steps to Reproduce:

1. Create a VB file with the following line:
``` vb
If JobNameLen < 0 Then
```
Observe that the `<` seems to be marked with the mismatched bracket color.
![image](https://github.com/microsoft/vscode/assets/26179051/d7e0373d-a4e7-4858-9a07-86c74c0d1220)

instead of line 
![image](https://github.com/microsoft/vscode/assets/26179051/4250f739-c78e-4318-abca-70f2ec720d01)

Probably the ideal solution is to add an `unbalancedBracketScopes` value of `keyword.operator` to the package.json file.

However, it might also be worth noting that I do not understand why the `<` or `>` are getting this treatment, because I am not observing them being color matched.

**Comment by alexr00** [comment]
> However, it might also be worth noting that I do not understand why the < or > are getting this treatment, because I am not observing them being color matched.

@hediet would you expect angle brackets in VB to get color matching when bracket pair colorization is turned on?

**Comment by hediet** [comment]
As a quick workaround, I'd suggest to remove <...> as bracket pair from VB (and wait of a PR to configure it properly).
