### ISSUE TITLE
Continuous segfaults when opening new window on wayland

### ISSUE THREAD

**Issue by danog** [microsoft/vscode#183311]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.78.2, b3e4e68a0bc097f0ae7907b217c1119af9e03435, x64
- OS Version: Arch linux, sway
- Electron Version: v22.3.3

Steps to Reproduce:

1. Open one repository using `code --goto --disable-extensions repo1`
2. Open a different repository using `code --goto --disable-extensions repo2`

Sometimes, vscode can segfault right away even when opening just one repository.

Using these electron flags to enable wayland support:
```
--enable-features=UseOzonePlatform
--ozone-platform=wayland
```

Coredumps:
https://paste.daniil.it/core.code-oss.1000.fda55a72533c4a30ab28a4f64152a76d.142642.1684927266000000.zst
https://paste.daniil.it/core.code-oss.1000.fda55a72533c4a30ab28a4f64152a76d.143430.1684927298000000.zst
https://paste.daniil.it/core.code-oss.1000.fda55a72533c4a30ab28a4f64152a76d.144473.1684927537000000.zst

**Comment by danog** [comment]
Here's what `--crash-reporter-directory` generates: https://paste.daniil.it/report.tar.xz

**Comment by deepak1556** [comment]
Merging to https://github.com/microsoft/vscode/issues/179836
