### ISSUE TITLE
When connecting to remote tunnel, the "Connecting to <hostname>...." message never disappears

### ISSUE THREAD

**Issue by skroth** [microsoft/vscode#183345]
Type: <b>Bug</b>

I see in the logs that a tunnel connection is established, and I'm able to open files on the remote system, but the message saying it's connecting never goes away. This happens on Insiders build as well as Stable.

<img width="470" alt="image" src="https://github.com/microsoft/vscode/assets/3495926/9b240489-6221-4c52-bc02-7142c1d7682f">

VS Code version: Code - Insiders 1.79.0-insider (Universal) (f6be5461f8bc69013a605f5baea834651c6589fb, 2023-05-20T01:20:35.044Z)
OS version: Darwin x64 22.3.0
Modes:
Remote OS version: Darwin x64 22.4.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|3, 3, 4|
|Memory (System)|64.00GB (22.87GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|peach-mbp-insiders|
|OS|Darwin x64 22.4.0|
|CPUs|Intel(R) Core(TM) i5-1038NG7 CPU @ 2.00GHz (8 x 2000)|
|Memory (System)|16.00GB (0.43GB free)|
|VM|0%|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
remote-explorer|ms-|0.4.0
remote-server|ms-|1.1.0
vim|vsc|1.25.2
python|ms-|2023.8.0
vscode-pylance|ms-|2023.5.30

(1 theme extensions excluded)

</details>

**Comment by connor4312** [comment]
Thanks for the issue, just published a new version of the extension which will fix this issue. We had a short pause on Insiders builds due to Microsoft Build which caused some desync here.

**Comment by skroth** [comment]
> Thanks for the issue, just published a new version of the tunnels extension which will fix this issue. We had a short pause on Insiders builds due to Microsoft Build which caused some desync here.

The problem is still occurring for me, and I updated Insiders to latest update. I also don't see any extensions that that need updating. Am I missing something?

**Comment by skroth** [comment]
@connor4312 
I'm on tunnel 1.2.1. I'm still getting it on stable and insiders. When it initially connects, it works. But if I reconnect and it reuses the existing proxy connection, everything functions fine but the Connecting notification never goes away.

Here's what it looks like when it works
```
2023-06-27 20:17:55.632 [info] Resolving tunnel+peach-mbp-insiders...
2023-06-27 20:17:55.635 [info] Creating new tunnel proxy server
2023-06-27 20:17:57.065 [info] [proxy] Found tunnel (ID=23x322pv, Cluster=usw3)
2023-06-27 20:17:57.070 [info] Remote resolution completed
2023-06-27 20:18:00.800 [info] [proxy] [connection.0] tunnel connection established
2023-06-27 20:18:00.852 [info] [proxy] Tunnel connection successful
2023-06-27 20:18:01.224 [info] [proxy] [connection.1] tunnel connection established
```
And this is what it looks like when I connect again shortly after having been connected
```
2023-06-27 20:32:41.986 [info] Resolving tunnel+peach-mbp-insiders...
2023-06-27 20:32:41.992 [info] Found running server in /var/folders/6x/v1m4_y9d1hx92gr6mh6hxwlw0000gn/T/vscode-tunneling-7f2dae95d88662db.sock
2023-06-27 20:32:41.997 [info] Remote resolution completed
2023-06-27 20:32:42.213 [info] [proxy] [connection.2] tunnel connection established
2023-06-27 20:32:42.518 [info] [proxy] [connection.3] tunnel connection established
2023-06-27 20:32:43.536 [info] [proxy] [connection.4] tunnel connection established
```
It's in this second case that the notification never goes away. Are these logs equivalent of running it with `--verbose`? I tried doing that but there was so much output in the terminal I couldn't find what was related to the tunnel. Let me know if there's anything else I can try to fix it, or more debug info I can get you.
