### ISSUE TITLE
Support filtering search by folder with './' syntax

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#18334]
'files to include' maps the input 'foo' to globs like `foo/**`, `**/foo`, so it includes anything under the folder foo, or files named foo anywhere in the workspace. It would be helpful to have syntax like `./foo` to limit this to folders from the root, especially for 'Find in folder' from the explorer. Related to #18123.

**Comment by roblourens** [comment]
- Multiple folders like - `./foo, ./bar` - just search in the last one, since I don't want to deal with spawning multiple ripgrep processes and merging results right now.
- A pattern like `./foo/bar/**/*.js` - convert to `./foo/bar, **/*.js`, somehow. Or, ignore it, and anything else that doesn't look exactly like a relative path to a folder in the workspace.

**Comment by roblourens** [comment]
Actually multiple folders is not a problem at all, ripgrep can handle that

**Comment by roblourens** [comment]
Actually, ripgrep has no problem searching multiple folders, or searching patterns like `./foo/**/*.js`.

**Comment by roblourens** [comment]
Except on Windows 😛  https://github.com/BurntSushi/ripgrep/issues/234

**Comment by aeschli** [comment]
Marking as verified as find in folders works. But I filed some issues and I'm still confused on how './' is supposed to work. To search in the root, isn't the typical syntax to start with '/' (`/foo` searches in files and folders foo that are in the root)
