### ISSUE TITLE
Cmd+P opens editor in first panel rather than active panel

### ISSUE THREAD

**Issue by creynia-dmatrix** [microsoft/vscode#183450]
Type: <b>Bug</b>

Use Cmd+P to open a file. It used to open a new tab in the current editor panel, it now opens a new tab in the first (leftmost) editor panel.

VS Code version: Code 1.78.2 (b3e4e68a0bc097f0ae7907b217c1119af9e03435, 2023-05-10T15:00:40.428Z)
OS version: Darwin arm64 22.1.0
Modes:
Sandboxed: Yes
Remote OS version: Linux arm64 5.15.49-linuxkit

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|3, 3, 4|
|Memory (System)|16.00GB (0.08GB free)|
|Process Argv|--crash-reporter-id 6602b188-5879-4a12-85ac-52ece85f1bc4|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|Dev Container: perf_model dev env|
|OS|Linux arm64 5.15.49-linuxkit|
|CPUs|unknown (8 x 0)|
|Memory (System)|13.65GB (11.70GB free)|
|VM|0%|
</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
better-cpp-syntax|jef|1.17.2
jupyter-keymap|ms-|1.1.0
remote-containers|ms-|0.293.0
gitlens|eam|13.6.0
vscode-clangd|llv|0.1.24
vscode-docker|ms-|1.25.1
cmake-tools|ms-|1.14.31
cpptools|ms-|1.15.4
cpptools-extension-pack|ms-|1.3.0
hexeditor|ms-|1.9.11
cmake|twx|0.0.17
markdown-all-in-one|yzh|3.5.1

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
2e4cg342:30602488
pyind779:30671433
89544117:30613380
pythonsymbol12:30671437
showlangstatbar:30737416
vsctsb:30748421
pythonms35:30701012
57b77579:30736110
pythonfmttext:30731395
f8hc8238:30694864
fixshowwlkth:30730052
hidesbindicator:30730055
pythongtdpathcf:30739705

```

</details>

**Comment by bpasero** [comment]
Do you have `workbench.editor.revealIfOpen` configured maybe?

**Comment by creynia-dmatrix** [comment]
revealIfOpen is disabled and this behavior is happening with fresh tabs not just files I already have open in the first editor pane.

From: Benjamin Pasero ***@***.***>
Date: Thursday, May 25, 2023 at 12:09 PM
To: microsoft/vscode ***@***.***>
Cc: Chris Reynia ***@***.***>, Author ***@***.***>
Subject: Re: [microsoft/vscode] Cmd+P opens editor in first panel rather than active panel (Issue #183450)
[This email originated from outside d-Matrix Corporation.]


Do you have workbench.editor.revealIfOpen configured maybe?

**Comment by creynia-dmatrix** [comment]
This is happening on a remote container (local docker), and doesn't repro on a different project which is running locally.

settings.json in the failing workspace:
```
{
    "editor.tabSize": 2,
    "git.rebaseWhenSync": true,
    "cmake.sourceDirectory": "${workspaceFolder}/src",
    "cmake.buildDirectory": "${workspaceFolder}/build_${buildType}",
    "cmake.buildBeforeRun": false,
    "clangd.arguments": [
        "-background-index",
        "-compile-commands-dir=build"
    ],
    "C_Cpp.clang_format_fallbackStyle": "{ ColumnLimit: 80 }",
    "testExplorer.useNativeTesting":true,
    "cmakeExplorer.debugConfig":"test_dbg_cfg",
    "files.associations": {
        "array": "cpp",
        "atomic": "cpp",
        "strstream": "cpp",
        "bit": "cpp",
        "*.tcc": "cpp",
        "cctype": "cpp",
        "cinttypes": "cpp",
        "clocale": "cpp",
        "cmath": "cpp",
        "cstdarg": "cpp",
        "cstddef": "cpp",
        "cstdint": "cpp",
        "cstdio": "cpp",
        "cstdlib": "cpp",
        "cstring": "cpp",
        "cwchar": "cpp",
        "cwctype": "cpp",
        "deque": "cpp",
        "map": "cpp",
        "unordered_map": "cpp",
        "vector": "cpp",
        "exception": "cpp",
        "algorithm": "cpp",
        "functional": "cpp",
        "iterator": "cpp",
        "memory": "cpp",
        "memory_resource": "cpp",
        "numeric": "cpp",
        "optional": "cpp",
        "random": "cpp",
        "string": "cpp",
        "string_view": "cpp",
        "system_error": "cpp",
        "tuple": "cpp",
        "type_traits": "cpp",
        "utility": "cpp",
        "fstream": "cpp",
        "initializer_list": "cpp",
        "iosfwd": "cpp",
        "iostream": "cpp",
        "istream": "cpp",
        "limits": "cpp",
        "new": "cpp",
        "ostream": "cpp",
        "sstream": "cpp",
        "stdexcept": "cpp",
        "streambuf": "cpp",
        "typeindex": "cpp",
        "typeinfo": "cpp",
        "list": "cpp",
        "unordered_set": "cpp",
        "regex": "cpp",
        "chrono": "cpp",
        "condition_variable": "cpp",
        "mutex": "cpp",
        "thread": "cpp",
        "systemc": "cpp",
        "tlm": "cpp",
        "any": "cpp",
        "bitset": "cpp",
        "cassert": "cpp",
        "cerrno": "cpp",
        "cfloat": "cpp",
        "charconv": "cpp",
        "ciso646": "cpp",
        "climits": "cpp",
        "csignal": "cpp",
        "ctime": "cpp",
        "set": "cpp",
        "ratio": "cpp",
        "future": "cpp",
        "iomanip": "cpp",
        "ios": "cpp",
        "locale": "cpp",
        "queue": "cpp",
        "shared_mutex": "cpp",
        "stack": "cpp",
        "variant": "cpp",
        "complex": "cpp",
        "spike": "cpp",
        "socket": "cpp",
        "internet": "cpp",
        "io_context": "cpp"
    },
    "window.zoomLevel": 1,
    "editor.mouseWheelZoom": false
}
```

**Comment by creynia-dmatrix** [comment]
Thanks for trying to help me out. Sometime in the past couple days it started behaving as expected again. I didn't update vscode, but I have rebuilt the docker container (and so I think must have picked up a newer version of an in-container extension). Thanks again, closing.
