### ISSUE TITLE
Workspace folder picker entry descriptions are suboptimal for some filesystems

### ISSUE THREAD

**Issue by gjsjohnmurray** [microsoft/vscode#183418]
Type: <b>Bug</b>

1. Configure setting `"terminal.integrated.splitCwd": "workspaceRoot"` in order to provide a convenient way of invoking the workspace folder picker by splitting a terminal when in a multiroot workspace.
2. Install the MemFS extension (jrieken.vscode-memfs) from Marketplace.
3. Close any open folder or workspace, then run the `MemFS: Setup Workspace` command.
4. Run `Preferences: Open Workspace Settings (JSON)`
5. Edit this to simulate a multi-root workspace in which the paths of the uris point to the filesystem root of two different authorities:
```json
{
	"folders": [
		{
			"name": "MemFS - Sample 1",
			"uri": "memfs://1/"
		},
		{
			"name": "MemFS - Sample 2",
			"uri": "memfs://2/"
		}
	],
	"settings": {}
}
```
6. On the Terminal tab on the Panel, use the Split Terminal button.

The Workspace folder picker looks like this:

![image](https://github.com/microsoft/vscode/assets/6726799/7a5f6086-c85d-4fa0-b66c-de5dea9b4082)

Displaying the folder name twice on each line is unhelpful.

 When the path of the uri is `/` I propose showing the non-relative label instead. I will submit a PR.

VS Code version: Code - Insiders 1.79.0-insider (f6be5461f8bc69013a605f5baea834651c6589fb, 2023-05-20T01:18:53.811Z)
OS version: Windows_NT x64 10.0.22621
Modes:

**Comment by DonJayamanne** [comment]
I'm still seeing the duplicate information
Version: 1.79.0-insider (Universal)
Commit: b9a77b3c7b43f229a430b28070250d55e5d14858
Date: 2023-05-31T20:19:54.210Z
Electron: 22.5.4
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Darwin arm64 22.5.0
![Screenshot 2023-06-01 at 11 58 38](https://github.com/microsoft/vscode/assets/1948812/4aa504ed-4762-48fe-be14-f2f9c2d22df7)

**Comment by bpasero** [comment]
Yeah looks like I missed a case.

**Comment by joyceerhl** [comment]
I now see only a label and no further description: <img width="641" alt="image" src="https://github.com/microsoft/vscode/assets/30305945/1731297e-c358-4615-81bc-63afc886379e">
