### ISSUE TITLE
Use StringMatch for finding files

### ISSUE THREAD

**Issue by tucker-m** [Microsoft/vscode#1834]
VSCode's "Go To File" function isn't very lenient. You can type the path to a file, but you have to include the full folder names and slashes. E.g.: `app/webroot/main.css`, or `webroot/main.css`.

[Brackets](http://brackets.io), another code editor, has much more lenient matching. You could find that file by typing `appwebmain`, or even just `apwemain` or `awm`. Any sequence of characters that appear in the file's path will work. Something short like `awm` could match multiple files, but it's good at determining which one you meant (based on special characters and capitalization in the path and filename).

You can read about the algorithm [here](http://blog.brackets.io/2013/04/03/brackets-quick-open-thats-no-regex/). The file that does the work is [StringMatch.js](https://github.com/adobe/brackets/blob/2c1616a6346dfee29a8321b5ecc9e0f636ec42d8/src/utils/StringMatch.js). According to the copyright notice, it'd be OK to use that in VSCode.

I know that some work is being done on the Go To File function in issue #55. Using StringMatch would be a related improvement.

**Comment by bpasero** [comment]
@tucker-m please enable `filePicker.alternateFileNameMatching` in settings to get fuzzy matching. Happy to hear feedback how it works.
