### ISSUE TITLE
Can not search local extensions offline.

### ISSUE THREAD

**Issue by shutaozhenzhen** [microsoft/vscode#183413]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.78.2
- OS Version: Windows 10

Steps to Reproduce:

1. install vscode in a offline computer, install extensions by .vsix file
2. want to search local extensions to enable/disable one extension
3. get `XHR failed`, can not show local extension
4. can be reproduce on online computer with http.proxy set as unreachable.

**Comment by sandy081** [comment]
Please try `@installed <search term>`
