### ISSUE TITLE
How about support 'project' unit in VSCode?

### ISSUE THREAD

**Issue by gseok** [Microsoft/vscode#18345]
There is no plan of 'Project' unit support ?
I Know.. VSCode is NOT IDE. It's Editor....
But...
I Think... IF VSCode support project then it's very helpful for many developers...

for example some project is not compose single directory..,
some project compose many directory... 

this time, VSCode open many directory and VSCode's workspace tree also open many directory.
if VSCode support project unit then.. these many opened directory's root is project and it's very simple control for developer.. even if each directory's real path's root is not same...
it's just very simple e.g...
I Think.. if VSCode support project unit then there are many benefit for developer...
how about your think?

**Comment by mjbvz** [comment]
This looks like it falls under #396

Please let us know if you do not think this is a duplicate or have any specific ideas on how things could be improved

Thanks

**Comment by gseok** [comment]
oh.. I think.. same issue~!!
thanks!

2017-01-10 13:06 GMT+09:00 Matt Bierner <notifications@github.com>:
