### ISSUE TITLE
support multiple backend marketplace.

### ISSUE THREAD

**Issue by kajberg84** [microsoft/vscode#183498]
I have a private open vsx where I have stored some private extensions.
When I use the marketplace search I want to configure it so it searches the private first and then the open vsx marketplace.

So I want to use [open.vsx.registry](https://open-vsx.org/) and my private extension repo that is also on open-vsx. 

Is this possible already and I have missed that documentation or is it something that can be done?

**Comment by isidorn** [comment]
Currently not possible
Closing as duplicate of https://github.com/microsoft/vscode/issues/21839
Thanks
