### ISSUE TITLE
Modernizing VS Code UI to fit other Microsoft Products

### ISSUE THREAD

**Issue by EmrecanKaracayir** [microsoft/vscode#183486]
With very minor adjustments, VS Code can be really beautiful and modern-looking. I was experimenting with the developer console and prepared some custom CSS. I thought VS Code can benefit a design that is similar to the new Microsoft Edge UI refresh.

In the video, I am not demonstrating a theme, the idea is the panel design. The design proposes that all fundamental UI elements such as; Title bar, Activity Bar and Status Bar resides on the base level (i.e., z-index 1) while the panels like; Terminal, Side Bar and Editor resides on an upper layer (i.e., z-index 2). The Windows 11 Design guidelines suggests that upper level surfaces' background colors should be lighter than lower level ones (in this example: base level HEX:202020, upper level HEX:282828). Following these two rules and rounded panel design would give us a result that is similar to new Microsoft Edge UI refresh.

Example UI footage: (Not a concept)

https://github.com/microsoft/vscode/assets/84916904/2af718be-f7a9-4800-9b28-30a167b41cbd

This is a veery rough little experiment, has quirks and issues. But the idea is this:

![edge-new-ui-splitscreen-tab-center-hero](https://github.com/microsoft/vscode/assets/84916904/4b0d4e6b-efed-4d7d-86af-bd4643010a21)
![gR2tVyByeDdv97NiWg6cBG-970-80](https://github.com/microsoft/vscode/assets/84916904/8abe6ce9-f66e-47d6-9d25-010e42e58cf8)

**Comment by EmrecanKaracayir** [comment]
Edit: in the video don't focus to the colors. The idea is rounded corners and modularity.

**Comment by RGarrido03** [comment]
This looks amazing! Would you mind sharing the custom CSS?

**Comment by daviddossett** [comment]
Thanks for exploring 🙏 As with Edge's recent update, I suspect this would be a very polarizing change. However I am planning to explore some UI updates at some point this year. I'll take this as some input.

The most obvious challenge in pulling off this kind of layout, cool as it is visually, is that you lose precious real estate, especially on smaller screens.

**Comment by EmrecanKaracayir** [comment]
> Thanks for exploring 🙏 As with Edge's recent update, I suspect this would be a very polarizing change. However I am planning to explore some UI updates at some point this year. I'll take this as some input.
> 
> 
> 
> The most obvious challenge in pulling off this kind of layout, cool as it is visually, is that you lose precious real estate, especially on smaller screens. 

That is right, losing real-estate is always a bad thing but, i used 16px of margin around panels, this can be reduced to 8px. Also, to me, the biggest real-estate hog is the activity bar. And also as always, there can be a compact mode.

By the way, I loved your work for the new modern themes. It was a great step to making VS Code ui great. Thank you.

**Comment by Kroc** [comment]
Try out your design in 1366x768, where I'm already struggling to have the Explorer, Code view and side panel without reducing code to less than 80 chars! Certainly, different metrics could be used for larger screens (responsive CSS in VSCode?)
