### ISSUE TITLE
Provide a (more) neutral default mechanism for feedback 

### ISSUE THREAD

**Issue by drittich** [microsoft/vscode#183412]
(Similar to issue at https://github.com/microsoft/azuredatastudio/issues/23209)

I'm disappointed to see Twitter continue to be promoted as the primary platform for feedback within VS Code, when it is an extremely partisan platform that promotes specific political and moral values which I believe is harmful to society. I cannot provide feedback in this way, and I doubt that I am alone.

**Comment by lszomoru** [comment]
Closing this issue as it is specific to Azure Data Studio.

**Comment by gjsjohnmurray** [comment]
See #188960
