### ISSUE TITLE
Sometime VS Code Debugger will Crash (PowerShell Extension) then odd things happen

### ISSUE THREAD

**Issue by swinster** [Microsoft/vscode#18344]
- VSCode Version: Code 1.8.1 (ee428b0eead68bf0fb99ab5fdc4439be227b6281, 2016-12-19T14:49:23.350Z)
- OS Version: Windows_NT ia32 10.0.14986
- Extensions:

|Extension|Author|Version|
|---|---|---|
|python|donjayamanne|0.5.5|
|beautify|HookyQR|0.7.3|
|rest-client|humao|0.11.4|
|PowerShell|ms-vscode|0.8.0|

---

Steps to Reproduce:
Not sure if this is with VS Code or the PowerShell Extension. 

Apologies for the woolly title and no step to replicate, but this is odd to say the least. Sometime, the VS Code debugger will hang when debugging a  PS script. I can't restart the debugger, but eventually, after pressing the stop button several times it will stop. However, pressing play results in a blue scrolling time line above the debug pane, and when I click stop this time I retrieve an error saying the debugger has crashed. 

Debug will not start until I have exited and restart Vs-code, but things to not stop there.  I threw together a simple test of some functions in an attempt to replicate an odd behaviour I was seeing through a pipeline (running the through the VS PS Debugger), and even more odd behaviours were seen, such as the Process block of the second function in the pipeline running before the process block on the first function. In another script I was also seeing other pipeline functions fire (and of course fail) when simply stepping over  a command in the current function (for example, a New-Item command to create a directory, or a '&' call out to another process. Even shutting down and restarting VS Code seem to do nothing.

Eventually I rebooted, but pretty sure this too too didn't do much either, until I change so code in `For Each-Object` loop, then eventually VS Code started behaving. 

It was almost as it VS Code hadn't cleared some kind of internal stack and kept reverted to old path, or some such when the debugger was run.

Not sure if you can understand what I'm explaining, or if I can replicate, but this has been going on an off for a while. If there are file I can provide, let me know.

**Comment by mjbvz** [comment]
This issue was moved to PowerShell/vscode-powershell#424
