### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by lanlianjiu** [Microsoft/vscode#18349]
#- VSCode Version: Code 1.8.1 (ee428b0eead68bf0fb99ab5fdc4439be227b6281, 2016-12-19T14:49:23.350Z)
- OS Version: Windows_NT ia32 10.0.10586
- Extensions:

|Extension|Author|Version|
|---|---|---|

---

Steps to Reproduce:

- 

- [ ] 
- [ ] 
- [ ] 1.
- [ ] 2.

**Comment by mjbvz** [comment]
Please provide some info.

Thanks
