### ISSUE TITLE
Pixel artifacts in dark theme

### ISSUE THREAD

**Issue by Vanbjorn** [microsoft/vscode#183459]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: latest
- OS Version: Win10

Steps to Reproduce:

1. Just open VSCode in dark theme
2. Point mouse elswhere on the screen but the application
![pixel_artifacts](https://github.com/microsoft/vscode/assets/133606305/d2dedcc8-b2ff-44c5-af41-9590fb52b31d)
![pixel_arts_2](https://github.com/microsoft/vscode/assets/133606305/41dffd34-589f-47cd-9c88-4529e090edd0)

**Comment by deepak1556** [comment]
/duplicate https://github.com/microsoft/vscode/issues/124226

Please disable hardware acceleration https://code.visualstudio.com/updates/v1_40#_disable-gpu-acceleration as a temporary workaround.
