### ISSUE TITLE
Reverting a change in diff view, inserts a debug breakpoint

### ISSUE THREAD

**Issue by AbdullahAmrSobh** [microsoft/vscode#183400]
Does this issue occur when all extensions are disabled?: No
I can't insert debug breakpoints when extensions are disabled

- VS Code Version: 1.78.2
- OS Version: Win 10 x64

Steps to Reproduce:

1. Open a diff view for any file changed in source control
2. Click on the revert this change arrow, to revert this change

A debug break point is inserted on the same line.

**Comment by gjsjohnmurray** [comment]
Inverse of #180789

**Comment by ulugbekna** [comment]
It seems like I can still repro: 

https://github.com/microsoft/vscode/assets/16353531/9b01dfe0-19f3-4aac-8454-b2b4e7ee6a6f

**Comment by bmarvinb** [comment]
Any updates?

**Comment by daviddq** [comment]
Hi! Any updates on this issue? Any temporary workaround? Thanks :)

**Comment by joyceerhl** [comment]
\closedWith https://github.com/microsoft/vscode/commit/9ed6654cc5e2103e2b5f27cf10bd869654175324
