### ISSUE TITLE
Open New External Terminal command opens an extra one too

### ISSUE THREAD

**Issue by aderchox** [microsoft/vscode#183401]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.78.2 (user setup)
- OS Version: Windows 10 x64 10.0.19045.2965

Steps to Reproduce:

1. Open VSCode
2. Either trigger the command `workbench.action.terminal.openNativeConsole`, or use its hotkey `Ctrl + Shift + C` (in my case).
3. Opens both the terminal I had last time restoring its layout (e.g., if it was vertically split, it's kept that layout) which is what I expect and is fine and very helpful indeed, however, opens up another (extra) bare instance of the terminal as well, which I don't want, and I always have to close it manually.
Here's a GIF screenshot of the issue:
![extra-external-terminal](https://github.com/microsoft/vscode/assets/52244768/db900e0c-3bda-498f-a1ae-7bfccd9f0315)

**Comment by meganrogge** [comment]
Am I correct in understanding from your gif that the new terminal is opening in your external terminal window? If so, I don't believe we can impact how that program works.

**Comment by aderchox** [comment]
> Am I correct in understanding from your gif that the new terminal is opening in your external terminal window? If so, I don't believe we can impact how that program works.

Sorry your question is not quite clear to me. I'm running the command to open a new external terminal, so yes, the new terminal "is in an external terminal window", but the main issue isn't that. The main thing here is, I expect a single external terminal window to open, but it opens two windows instead (I'm personally more comfortable with an external terminal window than the integrated one).

**Comment by meganrogge** [comment]
Your external terminal is responsible this, not VS Code
