### ISSUE TITLE
Changelog replaces open file

### ISSUE THREAD

**Issue by mahiDan** [Microsoft/vscode#18342]
- VSCode Version: Code 1.8.1 (ee428b0eead68bf0fb99ab5fdc4439be227b6281, 2016-12-19T14:42:49.304Z)
- OS Version: Darwin x64 16.3.0
- Extensions:
None

Steps to Reproduce:

1. Upgrade version, 
2. Open vscode with no tabs open
3. Save an empty document
4. Saved document is replaced with the changelog

This also happened yesterday when I first noticed it although I didnt keep track of the steps to reproduce. In this situation I had multiple tabs open and the document that was replaced with the changelog was the one I had just opened. I hadn't used vscode for a while previously.

**Comment by bpasero** [comment]
@mahiDan can you share a screenshot how VS Code looks like after step 3 and before step 4?

**Comment by mahiDan** [comment]
I've attempted to produce a better recreation steps for this,
1. Install 1.72
2. Open, check for upgrades
3. When prompted to restart click Later
4. Close the program
5. Open from terminal using 'code <filename>'
6. Code will open and have the file opened replaced
6i. If this doesn't happen check the Code menu, if it says restart to update, repeat from step 4.

I'm not sure if opening from terminal is necessary.
Here's what it looks like when it replaces the document with a changelog:
<img width="1088" alt="screen shot 2017-01-10 at 11 06 15 pm" src="https://cloud.githubusercontent.com/assets/22137454/21803250/2d03fa22-d78e-11e6-81ce-a2bec2bca4a7.png">

**Comment by bpasero** [comment]
Good point, this is fixed I believe. When starting from command line the file should opened not as preview but pinned.
