### ISSUE TITLE
Test tree checkbox API

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#183549]
Refs: https://github.com/microsoft/vscode/issues/116141

- [x] anyOS @TylerLeonhardt 
- [x] anyOS @aeschli

Complexity: 5
Roles: Developer, Engineering Manager

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23183549%0A%0A&assignees=alexr00)

---

Tree items support an optional checkbox with this API proposal:

https://github.com/microsoft/vscode/blob/0524ecce238fb19b5847a6ddac026775f1e234c1/src/vscode-dts/vscode.proposed.treeItemCheckbox.d.ts#L8-L15

To verify, you'll need to use this checkbox property in a tree view. If you don't have an extension that could benefit from having checkboxes, you can use the tree view sample and add the checkbox property here:

https://github.com/microsoft/vscode-extension-samples/blob/f7b27a91779e770b8f8f0e6791bcefc5d9c64035/tree-view-sample/src/testView.ts#L77-L81

And listen for the checkbox change event on this tree view:

https://github.com/microsoft/vscode-extension-samples/blob/f7b27a91779e770b8f8f0e6791bcefc5d9c64035/tree-view-sample/src/testView.ts#L6-L7

Things to verify:
- Verify that by default, if you check the checkbox of a node with children, the children get checked.  Verify that when you check all children, the parent gets checked. Also verify that you see this reflected in the `onDidChangeCheckboxState`.
- Verify that if you set the `manuallyManageCheckboxSelection` option (https://github.com/microsoft/vscode/blob/0524ecce238fb19b5847a6ddac026775f1e234c1/src/vscode-dts/vscode.proposed.treeItemCheckbox.d.ts#L51-L56) that you do not see the children and parents get automatically checked as described in the previous point.
- Verify that the JS Doc comments make sense.
- Verify that the checkbox tool tip and accessibility information are applied in the way you'd expect.

**Comment by TylerLeonhardt** [comment]
Feels really nice! Excited for finalization so I can adopt it completely 😄

**Comment by TylerLeonhardt** [comment]
@aeschli I was using a tree data provider by setting the checked state on the TreeItem, then firing the did change event. This allowed me to programmatically set an item as checked/unchecked.

**Comment by meganrogge** [comment]
I think this should be closed, reopen if I'm wrong

**Comment by alexr00** [comment]
Using a tree data provider and setting the checked state on the TreeItem, then fireing the on did change event is the way to set the checked state programatically.
