### ISSUE TITLE
Unexpected output from standalone `code` CLI 

### ISSUE THREAD

**Issue by bamurtaugh** [microsoft/vscode#183570]
Found a couple issues when using the standalone CLI:

- There seems to be a typo in the `status` description: 
- ![image](https://github.com/microsoft/vscode-remote-release/assets/25310137/c99b6ee3-4a1e-490d-b52a-e3baa0a84ce4)
- I wouldn't expect a lack of a running tunnel to be classified as an error:
- ![image](https://github.com/microsoft/vscode-remote-release/assets/25310137/58e4ea44-b3bd-4ef7-8077-881368d9206a)

**Comment by rzhao271** [comment]
Using the Insiders CLI from 5 hours ago

`code-insiders.exe tunnel --help` still prints an extra "iou" for the status description:
`status        Gets whether there is a tunnel running on the current machineiou`

`code tunnel status` still uses the word `error`, though it prints that word in the same colour as the rest of the text.
`[2023-05-31 14:06:11] error no tunnel process is currently running`

**Comment by alexr00** [comment]
Moving out as this was not discovered during testing. If this isn't correct, then please feel free to label with `candidate` and re-assign to the June!
