### ISSUE TITLE
Git view doesn't properly show difference

### ISSUE THREAD

**Issue by MaJerle** [microsoft/vscode#183556]
Does this issue occur when all extensions are disabled?: **Yes**/No

- VS Code Version: 
- OS Version: Win11

Version: 1.78.2 (user setup)
Commit: b3e4e68a0bc097f0ae7907b217c1119af9e03435
Date: 2023-05-10T14:39:26.248Z
Electron: 22.5.2
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Windows_NT x64 10.0.22621
Sandboxed: Yes

Built-in git does not show difference when previous vs new file diff is just a 4 spaces (NOT TAB).
![image](https://github.com/microsoft/vscode/assets/405717/85568234-5d1f-425b-8117-aca0c8e40760)

While in git extensions this is clearly visible and correct:
![image](https://github.com/microsoft/vscode/assets/405717/9823a28d-9a94-4271-9b9b-366b1dd8db33)

Steps to Reproduce:

1. Commit a file
2. Change that file in one line by adding some spaces
3. Go to built-in source control and see the "changes".

FYI, I committed above changes, and tried adding new space - see difference again.
![image](https://github.com/microsoft/vscode/assets/405717/1852e30d-4f69-45a1-809f-00a861e424e8)

**Comment by MaJerle** [comment]
Has this been reproduced?

**Comment by lszomoru** [comment]
@MaJerle, apologies for not getting back to you on this. Are you able to reproduce this in the new diff editor that you can enable by toggling the `diffEditor.experimental.useVersion2` setting? Please give it a try and let us know. Thanks!

**Comment by hediet** [comment]
I think the bug here is that the notification that you have to enable whitespace diffs does not seem to show?

**Comment by MaJerle** [comment]
I can reproduce with setting enabled.

Version info
```
Version: 1.80.1 (user setup)
Commit: 74f6148eb9ea00507ec113ec51c489d6ffb4b771
Date: 2023-07-12T17:22:07.651Z
Electron: 22.3.14
ElectronBuildId: 21893604
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Windows_NT x64 10.0.19044
```

**Comment by hediet** [comment]
Closing in favor of https://github.com/microsoft/vscode/issues/188202.

If that doesn't fix your bug, please share your input files, thanks!
