### ISSUE TITLE
Test Ports Attributes API

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#183547]
Refs: https://github.com/microsoft/vscode/issues/115616

- [x] anyOS @andreamah 
- [x] anyOS @paulacamargo25   

Complexity: 5

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23183547%0A%0A&assignees=alexr00)

---

### Background

We are getting ready to finalize the ports attributes API. This API was added to allow extension that run processes to provide an "action" to take when VS Code notices their port for auto forwarding. 

Here's are a few examples of how a ports attributes provider could work:

1. Opening the preview browser
When connected to a remote, the extension starts a process at localhost:3000 (on the remote). When this process starts, the extension wants to open the preview browser to https://localhost:3000. This extension could use a ports attributes provider to cause the preview browser to open ever time port 3000 is auto forwarded.

2. Extension internals
The extension always starts a server that listens on a random port between 5050 and 5100, which is used only for internal extension communication. When running locally, the user never knows about the server (unless they're watching their task manager or other list of running processes). When running in a remote, this port always gets auto forwarded, which not only forwards the port so it shows in the Ports view, but also disrupts the user with a notification. This extension could use a ports attributes provider to cause it's ports to be ignored entirely from auto forwarding.

### Pointers

I tried to assign testers who work on extensions that could benefit from having a ports attributes provider. If you have any questions, please let me know!

You'll need to register a provider:

https://github.com/microsoft/vscode/blob/0524ecce238fb19b5847a6ddac026775f1e234c1/src/vscode-dts/vscode.proposed.portsAttributes.d.ts#L89-L101

And specify a selector in the provider:

https://github.com/microsoft/vscode/blob/0524ecce238fb19b5847a6ddac026775f1e234c1/src/vscode-dts/vscode.proposed.portsAttributes.d.ts#L73-L86

### Things to verify

After you have implemented your provider, run your extension when connected to a remote. On the remote, run a process that listens on a port and verify the following:
- Verify that your provider only gets called for ports that match your selector.
- Verify that the action you provide is respected. Try some other actions and verify that they all work as expected.
- Set the `remote.portsAttributes` setting with a value that conflicts with what your provider returns. Verify that the setting wins.
- Verify that the JS doc comments make sense.
- If you can't use a selector, please comment with why.

**Comment by TylerLeonhardt** [comment]
Had some issues trying to test this in Codespaces so I really didn't get started. Feel free to steal from me or I'll do it first thing tomorrow morning.

**Comment by paulacamargo25** [comment]
I will test the issue today, thanks @TylerLeonhardt  for trying. :)
