### ISSUE TITLE
Using window.zoomLevel affects rendering

### ISSUE THREAD

**Issue by jsnjack** [Microsoft/vscode#18355]
- VSCode Version: 1.8.1
- OS Version: Fedora 25

Steps to Reproduce:

1. Set window.zoomLevel different from 0
2. Move mouse like shown on the video:  https://drive.google.com/open?id=0Bzf1ot7c1tUsdkU0RzRWaGQ1bTQ

**Comment by jsnjack** [comment]
Actually, I noticed, that this problem is also exist when zoomLevel = 0. It is just much more harder to notice

**Comment by Tyriar** [comment]
Are you in a VM by chance?

**Comment by jsnjack** [comment]
No, I'm not in a VM. However, I use 4k external monitor

**Comment by bpasero** [comment]
Is this https://github.com/Microsoft/vscode/issues/8606 ?

**Comment by jsnjack** [comment]
It does not require scrolling to reproduce the issue

**Comment by alexandrudima** [comment]
This looks like a Chromium rendering issue to me. We don't change anything in the DOM when the mouse moves (except when the hover pops up)

**Comment by dbaeumer** [comment]
@alexandrudima assigning to you since it happens in the editor.

**Comment by alexandrudima** [comment]
@jsnjack For pixel perfect rendering I recommend not using zoomLevel at all. You can also check if this reproduces on https://microsoft.github.io/monaco-editor/ when using Chromium and zooming in. 

In any case, you can report the issue to Chromium

**Comment by matejkramny** [comment]
The tag `linux` should be removed as it applies to all platforms. See the issue just referenced here. Had `zoomLevel` to -1

**Comment by alexandrudima** [comment]
This is an upstream issue (possibly within Chromium), and there are no known workarounds that we could implement on our side. This means there is no possible code change for us to do in VS Code sources to improve things. 

To keep the number of issues in our inbox at a manageable level, we’re closing issues that have been on the backlog for a long time but haven’t gained traction or that are not actionable. Thank you for your time and understanding.
