### ISSUE TITLE
Unable to authenticate with Github

### ISSUE THREAD

**Issue by fogoplayer** [microsoft/vscode#183552]
When using VSCode.dev, attempting to sign in using Github for settings sync or remote tunnels invariably results in an error. 

![image](https://github.com/microsoft/vscode/assets/13542612/43288f41-b256-4bae-a311-a7f5fd00e16a)

To reproduce:

1. Open vscode.dev
2. Trigger Github login (for example, by turning on settings sync)
3. Watch the pop-up appear and error out

The DevTools console reports the following error: 
![image](https://github.com/microsoft/vscode/assets/13542612/6c4a262e-4a09-4887-8233-78256c55ce83)

Version: 1.78.2
Commit: b3e4e68a0bc097f0ae7907b217c1119af9e03435
User Agent: Mozilla/5.0 (X11; CrOS x86_64 14541.0.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36
Embedder: vscode.dev

**Comment by TylerLeonhardt** [comment]
@joaomoreno any ideas here?

**Comment by joaomoreno** [comment]
@fogoplayer What browser exactly are you using?

**Comment by fogoplayer** [comment]
Chrome on Chrome OS. The issue has stopped; I can only assume it was a temporary outage on either vscode.dev or Github's part.
