### ISSUE TITLE
window.zoomLevel is ignored in User settings

### ISSUE THREAD

**Issue by jsnjack** [Microsoft/vscode#18352]
- VSCode Version: 1.8.1
- OS Version: Fedora 25

Steps to Reproduce:

1.  Set `window.zoomLevel` in user settings different than 0
2.  Nothing changes

**Comment by mjbvz** [comment]
I'm unable to repo this on Mac with the insiders build or Ubuntu with 1.8. @Tyriar Can you please take a look?

**Comment by Tyriar** [comment]
I use it all the time on my Ubuntu machine without issues. Also works fine on my VirtualBox Fedora VM.

**Comment by jsnjack** [comment]
It also works for me now. :/ Sorry, must have messed the configuration at some point...
