### ISSUE TITLE
Breakpoint option "Uncaught Exceptions" is activated automatically

### ISSUE THREAD

**Issue by jpele-tis** [microsoft/vscode#183513]
Hello,
I recreating the ticket https://github.com/microsoft/vscode/issues/172354#issue-1556131127 Since it is not fixed following the PR : https://github.com/microsoft/vscode/pull/173160

For me Breakpoint option "Uncaught Exceptions" keeps being randomly activated automatically.

**Comment by roblourens** [comment]
The original steps don't repro for me. I haven't seen this happen- can you help me find some steps that reproduce the issue?

**Comment by jpele-tis** [comment]
Restarting VSCode does not reproduce it, I agree. I didn't strictly identify the steps to reproduce it (after reboot ? updating ?). It seems to reactivate over time. 
Easy step to reproduce I think it to start editing a new project.

**Comment by jpele-tis** [comment]
Sorry, I mean `code .` in a new directory, Uncaught Exceptions will be on by default instead of take the last state.

**Comment by roblourens** [comment]
These flags are per-workspace, not remembered globally, so I would expect that.

**Comment by jpele-tis** [comment]
> These flags are per-workspace, not remembered globally, so I would expect that.

Is it possible to add a global or per-workspace option? We are working with novice users, and this option is not particularly user-friendly, and it occur because we added `"justMyCode": false,`

And if an error occur the user ends in a subfile, maybe we're doing something wrong
![image](https://github.com/microsoft/vscode/assets/57767497/e1d1d431-43ed-4b48-aab5-8a0bd1e5c5ea)
