### ISSUE TITLE
Test UNC allow list improvements

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#183537]
Refs: 

- [ ] windows @Tyriar
- [x] windows @dbaeumer 
- [x] windows @Yoyokrazy

Complexity: 4

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23183537%0A%0A&assignees=bpasero)

---

VS Code is blocking UNC hosts that are not acknowledged by the user either from a dialog on startup or via the `security.allowedUNCHosts` setting. The easiest to test this item is to work with localhost UNC paths that have the form:

```
\\localhost\c$\<directory>
```

**Note:** start testing without having configured `security.allowedUNCHosts` or `security.restrictUNCAccess`

**Testing**
* open `code-insiders \\localhost\c$\<some existing directory>` and verify you get a dialog asking to acknowledge opening of that UNC host
   * click the "Learn More" button and ensure the dialog is still there when you go back
   * click "Permanently allow host 'localhost' and verify this adds to the `security.allowedUNCHosts` setting
* reset the `security.allowedUNCHosts` setting, configure `security.restrictUNCAccess: false` and **quit**
   * open `code-insiders \\localhost\c$\<some existing directory>` and verify you are not getting asked to open the UNC path and it will just open
* reset the `security.restrictUNCAccess` setting, add `LOCALHOST` to the `security.allowedUNCHosts` setting and **quit**
   * open `code-insiders \\localhost\c$\<some existing directory>` and verify you are not getting asked to open the UNC path and it will just open
* create a [mapped network drive](https://support.microsoft.com/en-us/windows/map-a-network-drive-in-windows-29ce55d1-34e3-a7e2-4801-131475f9557d) that points to a localhost UNC folder
   * reset the `security.allowedUNCHosts` setting, **quit**
   * open the mapped network drive and a folder with a TypeScript project
   * verify TypeScript works and shows no errors in the output logs
* open `code-insiders --user-data-dir \\localhost\c$\<some path to empty folder>` and make sure you can use that instance to open a local TypeScript project (such as VS Code, without using UNC paths) and get TS smartness from the extension

**Comment by Yoyokrazy** [comment]
All working without issues 👍 great instructions

**Comment by Tyriar** [comment]
I'm overloaded and we decided to close it off instead of reassigning considering it's already had 2 tests on Windows.
