### ISSUE TITLE
running and debugging

### ISSUE THREAD

**Issue by Killerboy1534** [microsoft/vscode#183502]
Type: <b>Feature Request</b>

when i try to run my code it opens up a gui with some options in it like: "C/C++ runner"... and stuff like that with (windows),(launch) it has never happened in the past 3 years of my use of vsc

VS Code version: Code 1.78.2 (b3e4e68a0bc097f0ae7907b217c1119af9e03435, 2023-05-10T14:39:26.248Z)
OS version: Windows_NT x64 10.0.19045
Modes:
Sandboxed: Yes

**Comment by roblourens** [comment]
Sounds like you've installed an extension for this?

If you think it's just a vscode issue, please include a screenshot
