### ISSUE TITLE
Github PR on web: Open file from diff opens copy of document with unexpected authority

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#183586]
Version: 1.79.0-insider
Commit: 2dfb838f494f035099e999f0cd0eff5f1f488a30
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36
Embedder: vscode.dev

## Repo
1. View a PR on vscode.dev (for example https://insiders.vscode.dev/github/microsoft/vscode/pull/183488)
2. Open one of the changed files using quick open or the explorer (for example `markdownExtension.ts`)
3. Now In the PR view, click one the changed file to view its diff
4. In the diff editor, click `open file` in the editor toolbar

## Bug
There are now two copies of the file open 

![Screenshot 2023-05-26 at 12 39 03 PM](https://github.com/microsoft/vscode/assets/12821956/c61bab64-3cdd-4395-97d7-8ac1a25bd4b6)

The first open (the one on the left opened through the explorer/quick open) has an authority that matches the current workspace folder's uri. In my case, this looks like:

```
"vscode-vfs://github%2B7b2276223a312c22726566223a7b2274797065223a332c226964223a22313833343838227d7d/microsoft/vscode/extensions/markdown-language-features/src/markdownExtensions.ts"
```

However the file opened through `open file` (the one on the right) doesn't have the full authority. Its uri is:

```
"vscode-vfs://github/microsoft/vscode/extensions/markdown-language-features/src/markdownExtensions.ts"
```

**Comment by mjbvz** [comment]
`Open file` from the PR view seems to work correctly. It's only the `open file` button in the editor toolbar that causes this issue for me:

![Screenshot 2023-05-26 at 12 41 50 PM](https://github.com/microsoft/vscode/assets/12821956/d9a2c7b8-2406-43f1-9855-8bb19c1753ff)

**Comment by joyceerhl** [comment]
@mjbvz do you have GitLens installed? I see gitlens appearing in the callstack when I repro this, and if I uninstall gitlens I do not repro anymore 
<img width="525" alt="image" src="https://github.com/microsoft/vscode/assets/30305945/b1c237a7-89ee-41bd-bd43-2165400a8486">
