### ISSUE TITLE
Some Unit Test Problems

### ISSUE THREAD

**Issue by yiliang114** [microsoft/vscode#183506]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version:  latest vscode.dev or Version: 1.78.0 (Universal)

Version: 1.78.0 (Universal)
Commit: 252e5463d60e63238250799aef7375787f68b4ee
Date: 2023-05-03T20:11:00.813Z
Electron: 22.4.8
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Darwin x64 21.3.0
Sandboxed: Yes

- OS Version: 12.2.1 (21D62)

Steps to Reproduce:

1.  Clone `https://github.com/microsoft/vscode`
2. Use `Cmd + shift + p` to build vscode.

Case 1: 
1. Use `yarn test-browser --browser chromium --glob vs/**/**.test.ts` to run unit test. 
2. Then You will find that the unit test executes all the test files instead of the glob match specified.

Case 2:
1. Use `yarn test-browser --browser chromium --glob vs/**/**.test.ts --debug` to run unit test. 
2. There will be a browser flash, but I found that the ` loader.js ` is loaded repeatedly in `renderer.html`,  Ideally, what version of the file to load should be determined according to the parameters, not all of them, otherwise the browser will report an error.

Case 3:
1. Use `yarn test-browser --browser chromium --glob src/vs/**/**.test.ts --debug` to run unit test. 
2. An error has occurred:  `zsh: no matches found:  vs/**/**.test.ts`. Because the path prefix and suffix are not processed in glob mode.

![image](https://github.com/microsoft/vscode/assets/11473889/6437b0b8-3f0c-4db9-99fb-adf25cdf4c4e)

**Comment by connor4312** [comment]
Fixed 1/2 in https://github.com/microsoft/vscode/pull/199979

3 is your shell trying to expand the glob pattern -- quote the pattern to avoid this
