### ISSUE TITLE
Switching between tabs on extensions page crashes when search window is open

### ISSUE THREAD

**Issue by aely-aronoff** [microsoft/vscode#183591]
Type: <b>Bug</b>

Hi VS Code devs! 
I noticed a small bug on the extensions tab of VS Code. When you first open an extension's page, it lands you on the "Details" tab that gives the overview of the extension. Some extensions also have a "Changelog" tab. 
When I was on the details page, I pressed ctrl+F to search for text on that page. Then, I typed something into the search bar. With the search bar still active, I clicked on the changelog tab. VS Code froze up for about a second or two, then the program crashed. I was able to replicate the bug every time. It didn't seem to matter which extension's page was open: it crashed every time. In this case I was working on a remote machine when I submitted the bug report, but I was able to replicate the bug even when I was working on my local machine with no other files open.

VS Code version: Code 1.78.2 (b3e4e68a0bc097f0ae7907b217c1119af9e03435, 2023-05-10T14:39:26.248Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: Yes
Remote OS version: Linux arm64 5.15.0-1034-oracle

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-10300H CPU @ 2.50GHz (8 x 2496)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|7.87GB (2.11GB free)|
|Process Argv|--folder-uri vscode-remote://ssh-remote/<remote-dir> --crash-reporter-id 67b51dbd-217d-4c1b-bc12-51dcb2e2ad19|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: instance1|
|OS|Linux arm64 5.15.0-1034-oracle|
|CPUs|Neoverse-N1 (4 x 0)|
|Memory (System)|23.43GB (17.21GB free)|
|VM|0%|
</details><details><summary>Extensions (18)</summary>

Extension|Author (truncated)|Version
---|---|---
better-cpp-syntax|jef|1.17.2
jupyter-keymap|ms-|1.1.0
remote-containers|ms-|0.292.0
remote-ssh|ms-|0.102.0
remote-ssh-edit|ms-|0.86.0
remote-wsl|ms-|0.78.8
remote-explorer|ms-|0.4.0
isort|ms-|2022.8.0
python|ms-|2023.8.0
vscode-pylance|ms-|2023.5.40
jupyter|ms-|2023.4.1011241018
jupyter-keymap|ms-|1.1.0
jupyter-renderers|ms-|1.0.15
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-slideshow|ms-|0.1.5
live-server|ms-|0.4.8
vscode-coverage-gutters|rya|2.10.4
code-spell-checker|str|2.20.4

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
3biah626:30602489
pyind779:30671433
89544117:30613380
pythonsymbol12:30671437
showlangstatbar:30737416
vsctsb:30748421
pythonms35:30701012
pythonfmttext:30731395
pythoncmv:30739700
fixshowwlkth:30730052
showsbindicator:30730056
pythongtdpathcf:30739705

```

</details>

**Comment by deepak1556** [comment]
Merging to https://github.com/microsoft/vscode/issues/177046
