### ISSUE TITLE
Unexpected focusing behavior of content hover inside of a Jupyter notebook

### ISSUE THREAD

**Issue by aiday-mar** [microsoft/vscode#183529]
This issue has first been noticed https://github.com/microsoft/vscode-jupyter/issues/13263. While the core issue of 13263 has been solved, there remains an unexpected behavior of the focusing of the content hover inside of the Jupyter notebook.

1. Open a Jupyter notebook
2. Hover on code inside of a cell. Click on the hover, notice how the cell remains focused. :bug:
3. Press Enter, the focus disappears from the hover and the cell? :bug:
4. Press on the hover, the cell becomes focused, but the hover does not become visibly focused? :bug:

https://github.com/microsoft/vscode/assets/61460952/07c43505-975c-43fc-9d04-c6e4350341ef

cc @rebornix

**Comment by aiday-mar** [comment]
Hi @rebornix, I will place this on the next milestone

**Comment by aiday-mar** [comment]
Hi @rebornix, I am verifying the issue, I am wondering if it is expected that the following happens:


https://github.com/microsoft/vscode/assets/61460952/fb928060-39e8-4151-b478-9037c304af5c

When I click on the hover, the hover focuses and the cell focuses too.

**Comment by rebornix** [comment]
This is actually another case that I didn't cover.

**Comment by aiday-mar** [comment]
I am not able to make a hover appear in a Jupyter notebook cell anymore. Did we disable hovers in cells?
