### ISSUE TITLE
Test: Terminal image support

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#183563]
Refs: #182443

- [x] macOS @lszomoru
- [x] linux @roblourens

Complexity: 3

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23183563%0A%0A&assignees=Tyriar)

---

The terminal can now render images when using either sixel or iterm's image protocol.

- Set `"terminal.integrated.experimentalImageSupport": true`
- Sixel
  - Download .six file(s) from https://github.com/saitoha/libsixel/tree/master/images
  - Run `cat <file>.six`, verify an image shows up
- iterm's image protocol
  - Install imgcat off pypi https://pypi.org/project/imgcat/ (https://iterm2.com/utilities/imgcat is also available, I haven't tried it though)
  - Get a png, gif and jpg file
  - Run `imgcat <file>`, verify an image shows up
- Try resizing, selecting, etc. in the terminal

Current limitations:

- The image does not restore after VS Code reloads

**Comment by lszomoru** [comment]
@Tyriar, I have updated the steps as there was a typo: `imagecat <file>` instead of `imgcat <file>`.

**Comment by roblourens** [comment]
Cool!

**Comment by jerch** [comment]
@Tyriar Some early feedback from my side:
- animated gif - This is currently not supported, as the image rendering gets triggered from normal terminal update/rendering. To get animations working a much more involved render logic will be needed, with its own cycling decoupled from normal terminal render cycles. I did not bother yet to look into that, it also looks tricky to me to not penalize mainthread perf too much.
- copy output/HTML - Idk how the HTML is created - if through serialization then its not possible atm (serialization is still WIP). A more lightweight variant to get a hold of the image resource would be possible via `getImageAtBufferCell(x: number, y: number): HTMLCanvasElement | undefined` API call.

**Comment by Tyriar** [comment]
> To get animations working a much more involved render logic will be needed, with its own cycling decoupled from normal terminal render cycles. I did not bother yet to look into that, it also looks tricky to me to not penalize mainthread perf too much.

If you generate bitmaps for the frames and cache them it shouldn't be too costly to render.

> copy output/HTML - Idk how the HTML is created - if through serialization then its not possible atm (serialization is still WIP).

Yeah this would need some special handling and API, some way of xterm.js reaching out to an extension for cells that it owns or something

**Comment by Tyriar** [comment]
@jerch created some issues, we can move them over to the main repo after https://github.com/jerch/xterm-addon-image/issues/49
