### ISSUE TITLE
Provide access to current editor column

### ISSUE THREAD

**Issue by IgnacioHR** [Microsoft/vscode#1835]
I want to open a document right side of current editor according to the following logic:

If current editor is on column 1, side editor must be on column 2,
If current editor is on column 2, side editor must be on column 3,
if current editor is on column 3, side editor must be on column 1.

Also, if the target document to open is already opened in any of the existing editors, then no new editor shall be opened but the editor with the target document opened shall get the focus.

window has the showTextDocument with an argument to indicate the column. This can be used when the new document is still not opened, but if the target document is already opened, you have no way to know in which column.

I've tried a loop over all editors and that doesn't work because the order of the editors array does not follow the same order as the column numbers.

I've found no satisfactory solution for this problem and having access to every editor column might help a lot.

**Comment by bpasero** [comment]
Also @jrieken fyi

**Comment by jrieken** [comment]
I like

**Comment by jrieken** [comment]
tho, there are cases where an editor is embedded inside a 'large' editor - the find reference et al experience. unsure how to handle those...

**Comment by jrieken** [comment]
@bpasero Are there events when editor get rearranged et al?

**Comment by bpasero** [comment]
@jrieken currently not, but I can add such an event to the collection of editor events.

**Comment by jrieken** [comment]
there is now `TextEditor.viewColumn` and `window.onDidChangeTextEditorViewColumn`
