### ISSUE TITLE
Test: readonly mode

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#183543]
Refs: https://github.com/microsoft/vscode/issues/4873

- [x] anyOS @meganrogge
- [x] anyOS @hediet

Complexity: 4

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23183543%0A%0A&assignees=bpasero)

---

New settings have been added to mark file paths as readonly in the explorer and in text and notebook editors:
* `files.readonlyInclude`: paths or glob patterns that will make a file be readonly if matching
* `files.readonlyExclude`: paths or glob patterns that will skip files from being readonly when they match `files.readonlyInclude`
* `files.readonlyFromPermissions`: whether a file that has no write-permissions on disk should be readonly

According to the rules of the settings, if a path is considered to be readonly, you cannot modify it from the explorer (e.g. delete it) and you should see a readonly text or notebook editor.

In addition, new commands have been added to change readonly state for the current session only.

**Testing**
* play with the settings and ensure you can understand their meaning
* configure paths as readonly and verify that works as expected in explorer and for text files and notebooks
* play with the commands that allow to toggle readonly state for the current session - these will always allow to override the configured settings:
   * `Set Active Editor Readonly in Session`: mark active editor readonly
   * `Set Active Editor Writeable in Session`: mark active editor writeable
   * `Toggle Active Editor Readonly in Session`: toggle between readonly and writeable
   * `Clear Active Editor Readonly in Session`: reset the session state
*  with `files.readonlyFromPermissions` enabled, verify that files without user permissions to write on disk open as readonly
   * using node.js you can run this: `Promises.chmod(the-path, existing-stats-mode & ~0o200);`

**Comment by hediet** [comment]
Works as described! (It is `reset` though instead of `clear`)

I think 4 commands are a little much for this though.
Maybe a single command would be enough that has a quickpick (which can be set by an argument in keybindings) for the options "toggle", "readonly", "writeable", "reset"?

**Comment by jackpunt** [comment]
Note/MinorQuibble:
The term 'readonly' is legacy/expected by all who search for the feature.
But 'writeable' is would be better expressed as 'editable': 
This setting does not change the write-ability of the underlying file, 
but rather controls the ability to edit/modify the text in the model.

:)

**Comment by bpasero** [comment]
@jackpunt you refer to the commands? feel free to rename them in a PR if you want
