### ISSUE TITLE
Test static status bar contributions

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#183545]
Refs: https://github.com/microsoft/vscode/issues/167874

- [x] anyOS @bpasero 
- [x] anyOS @ulugbekna 
- [x] anyOS @devinvalenciano

Complexity: 3

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23183545%0A%0A&assignees=jrieken)

---

Status bar items can now be contributed statically, from `package.json`. Write an extension that uses `contributes/statusBarItems` . Make sure the doc is clear, that things work, and esp that you can elevate this static item into a dynamic item from source.

**Comment by gjsjohnmurray** [comment]
> ```json
> 	"enabledApiProposals": [
> 		"quickPickSeparators"
> 	],
>     
> ```

In this case, `contribStatusBarItems` I assume?

**Comment by bpasero** [comment]
Pretty 👍 , I noticed if you call `vscode.window.createStatusBarItem` with an existing item but set a different alignment and priority, the item would not move. But not a big deal I think, so I did not file an issue for that.

**Comment by jrieken** [comment]
> different alignment and priority, the item would not move

I did that on purpose. The API marks them as readonly and I extended that restriction* into the static status item works. (*) IMO this is a good restriction because otherwise extension can make the status bar "flicker" a lot (move from far left to far right for instance)
