### ISSUE TITLE
[Proposal] Move git related extensions from properties to git

### ISSUE THREAD

**Issue by JimiC** [Microsoft/vscode#18358]
In [vscode-icons](https://github.com/robertohuertasm/vscode-icons) we are leveraging the power of `languageIds` to associate filenames and file extensions for those that are supported. What I have noticed is that all `git` related filenames are under the `properties` `languageId` (`extensions/ini/`), which is kinda odd, since there is already a `git` `languageId`. Consider moving them from `properties` to `git`.

While we are at it, could you please add any remaining `git` related filenames to it (i.e `.gitignore`, `.gitkeep`)?

**Comment by bpasero** [comment]
@JimiC The git extension only defines the "languages" for `git-commit` and `git-rebase` when using the interactive git editor. Are you asking to introduce a new language git for git related files to this extension and use the same tokenizer we use for ini?

**Comment by JimiC** [comment]
@bpasero 
Well, thinking about it further, I realize that there is a conflict here. What I'm proposing is to group all `git` related filenames under one `language` extension, when clearly the purpose of the `languageId` is to support the `git` syntax.

I do understand that `.gitignore` is syntactically a text file, thus it's defined in `plaintext`, and `.gitconfig` with `.gitattributes` are defined in `properties` in the `ini` extension as they are configuration syntactical files. The problem thought to that, is that by using the `languageId` for `git` the icons aren't associated correctly. Maybe the problem lies with the usage of `git` `languageId` on our side and not with the `git` `languageId` itself.

I'll come back to you once I investigate it a little further.

**Comment by JimiC** [comment]
Upon further investigation it looks like @robertohuertasm PR #17865 fixed the issue.
I see correct icon association in `vscode-insiders` unlike in `vscode`.

So I'm closing this as invalid.

Thank you all for your time.
