### ISSUE TITLE
Test shortcut of file system operations from extensions

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#183528]
Refs: 

- [x] anyOS @jrieken 
- [x] anyOS @mjbvz

Complexity: 3

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23183528%0A%0A&assignees=bpasero)

---

**Note:** This is a test for `workspace.fs` methods on resources of `file` scheme. This is NOT a test of using node.js `fs` methods!

This milestone methods of `workspace.fs` are implemented to perform within the extension host if possible and no longer on the main process. This saves us quite some roundtrip time, but we have to test for regressions.

As preparation, create or open a fresh VS Code extension. You can use the Yeoman generator to build one:
* `npm install -g yo`
* `npm install -g generator-code`
* `yo code`
* follow the instructions for a TypeScript extension

**Testing:**
* in your extension make use of the `workspace.fs` API
* test all of the methods of that API
* use local file `Uri` that have the scheme `file`
* make sure the methods work and return the results you expect or behave as you expect
* also test error cases, for example using a path that does not exist

**Comment by jrieken** [comment]
Tested with anycode which, when run locally, makes lots of file request. Standard deviation looks better, times are ~10% better

<img width="410" alt="Screenshot 2023-05-30 at 12 14 57" src="https://github.com/microsoft/vscode/assets/1794099/343aabd5-5138-4f1e-97f0-986bcaa7df7f">
