### ISSUE TITLE
Missing Text in titles and sections, and extensions.  Can see icons with --disable-gpu, but not text

### ISSUE THREAD

**Issue by ibigpapa** [Microsoft/vscode#18365]
- VSCode Version:1.8.1 
ee428b0eead68bf0fb99ab5fdc4439be227b6281
- OS Version:
Centos 7.3.1611 (Core)
3.10.0-514.2.2.el7.x86_64
GDM 3.14.2
XFCE 4.12
Steps to Reproduce:

1. Install Centos 7.3 minimal from ISO - create a user as well
2. log in as root
3. ```yum install epel-release wget -y```
3. ```yum groupinstall "X Window system"```
4. ```yum groupinstall xfce```
5. ```systemctl set-default graphical.target```
6. ```reboot```
7. log in as user
8. download the vs code rpm
9. ```sudo yum localinstall <vscode.rpm>```
10. run ```code```
11. Extensions shows a blank panel
12. exit code
13. run ```code with --disable-gpu```
14. Extensions shows icons with no words

![vscode-icons-only](https://cloud.githubusercontent.com/assets/694054/21816596/3de3b9ee-d726-11e6-911c-8a8a6176b9cf.png)

output of ```code --disable-gpu --verbose``` then selecting extensions waiting for icons to load
```
code --disable-gpu --verbose
[7814:0110/111718:WARNING:audio_manager.cc(314)] Multiple instances of AudioManager detected
[7814:0110/111718:WARNING:audio_manager.cc(275)] Multiple instances of AudioManager detected
[main 11:17:19 AM] Starting VS code in verbose mode
[main 11:17:19 AM] from: /usr/share/code/resources/app
[main 11:17:19 AM] args: { _: [],
  help: false,
  h: false,
  version: false,
  v: false,
  wait: false,
  w: false,
  diff: false,
  d: false,
  goto: false,
  g: false,
  'new-window': false,
  n: false,
  'reuse-window': false,
  r: false,
  performance: false,
  p: false,
  verbose: true,
  logExtensionHostCommunication: false,
  'disable-extensions': false,
  disableExtensions: false,
  'list-extensions': false,
  'show-versions': false,
  nolazy: false,
  'disable-gpu': true }
[main 11:17:25 AM] IPC#vscode-workbenchLoaded
```

output of ```code --list-extensions```
```
```

**Comment by Tyriar** [comment]
@ibigpapa does Chrome or Electron act the same way?

**Comment by ibigpapa** [comment]
@Tyriar No chrome doesn't have any issues.  Not sure how to test Electron alone.

**Comment by Tyriar** [comment]
You should be able to test Electron by running this (from http://electron.atom.io/): 

```bash
# Clone the Quick Start repository
git clone https://github.com/electron/electron-quick-start

# Go into the repository
cd electron-quick-start

# Install the dependencies and run
npm install && npm start
```

**Comment by ibigpapa** [comment]
It Appears the quickstart electron app also has the issue.  So i'm guessing The issue is with the electron app.

**Comment by Tyriar** [comment]
Thanks for filing the upstream issue :smile:
