### ISSUE TITLE
Test: running tunnels must not block VS Code update on Windows

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode#183698]
Refs: https://github.com/microsoft/vscode/issues/177226

- [x] win @amunger
- [x] win @hediet

Complexity: 4

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23183698%0A%0A&assignees=aeschli)

---
There was work on the VS Code (Windows) setup wizard so that running tunnels do not block the update
There are two ways the updater can run and there are two ways a tunnel can run. So there are 4 setups to test

The VS Code updater has two modes: with the setup wizard, or in the background.
The Tunnels server can run as service or manually.

The update wizard should not be blocked by the running tunnel. The update should restart the tunnel service. The manually started tunnel will just be stopped.

Preparations:
- install the latest VS Code insiders using the regular setup wizard as user install.
- from the VS Code web page (or the builds page) download the latest VS Code insiders installer into a local folder: `Downloads`. `VSCodeUserSetup-x64-1.79.0-insider.exe

1.  VS Code setup wizard & tunnel as service

- close VS Code, make sure no tunnel is running: From the command prompt run `code-insiders tunnel status`. It should say `no tunnel process is currently running`
- start a tunnel server as service from the command prompt: `code-insiders tunnel service install`. `code-insiders tunnel status` should show you a running tunnel
- start the setup from the command prompt: Run `Downloads\VSCodeUserSetup-x64-1.79.0-insider.exe /log`. `/log will get us additional information in case of problems. The resulting log file is in `%temp%` (`Setup Log...`)
- go through the wizard, accept all defaults (install VS Code over the existing installation)
- the wizard must complete without any warnings or problem. The update will detect the tunnel running as service, stop it and restart it on the new bits. This can also be seen in the log file.
- when the wizard has completed, close VS Code. Run `code-insiders tunnel status`. The tunnel should still be running
- uninstall the service with `code-insiders tunnel service uninstall`. `code-insiders tunnel status` should say `no tunnel process is currently running`

2.  VS Code background update & tunnel as service

- make sure no tunnel is running `code-insiders tunnel status` should say `no tunnel process is currently running`
- start a tunnel server as service from the command prompt: `code-insiders tunnel service install`. `code-insiders tunnel status` should show you a running tunnel
- in VS Code set the settings `"update.mode": "manual"`. Then run the command `Developer: Apply update...` and pick the downloaded build (`Downloads\VSCodeUserSetup-x64-1.79.0-insider.exe`). This simulates an update that would happen if VS Code found a newly released version.
- The build will be installed in the background. The gear icon will show a dot when the installation is ready.
- When ready, run the update with `Restart to update..` from the context menu of the gear.
- This will close VS Code, complete the update, and restart VS Code again. There should be no problems or hangs. The update will detect the tunnel running as service, stop it and restart it on the new bits. This can also be seen in the log file (in `%temp%` (`Setup Log...`))
- after the successful update run `code-insiders tunnel status` from the terminal. The tunnel should still be running
- uninstall the service with `code-insiders tunnel service uninstall`. `code-insiders tunnel status` should say `no tunnel process is currently running`

3.  VS Code setup wizard & tunnel manually run

- close VS Code, make sure no tunnel is running: From the command prompt run `code-insiders tunnel status`. It should say `no tunnel process is currently running`
- start a tunnel server from the command prompt: `code-insiders tunnel`. 
- start the setup from the command prompt: Run `Downloads\VSCodeUserSetup-x64-1.79.0-insider.exe /log`. `/log will get us additional information in case of problems. The resulting log file is in `%temp%` (`Setup Log...`)
- go through the wizard, accept all defaults (install VS Code over the existing installation)
- the wizard must not result in any error. The tunnel will be stopped automatically (but not restarted)

4.  VS Code background update & tunnel as service

- make sure no tunnel is running `code-insiders tunnel status` should say `no tunnel process is currently running`
- start a tunnel server from the command prompt: `code-insiders tunnel`. 
- In VS Code set the settings `"update.mode": "manual"`. Then run the command `Developer: Apply update...` and pick the downloaded build (`Downloads\VSCodeUserSetup-x64-1.79.0-insider.exe`). This simulates an update that would happen if VS Code found a newly released version.
- the build will be installed in the background. The gear icon will show a dot when the installation is ready.
- when ready, run the update with `Restart to update..` from the context menu of the gear.
- this will close VS Code, complete the update, and restart VS Code again. There should be no problems or hangs. The tunnel will be stopped automatically (but not restarted)

**Comment by hediet** [comment]
You mean VS Code update on windows, right? (windows updates probably should also not be blocked though)

**Comment by amunger** [comment]
for the 3rd test, I was prompted to stop the tunnel, rather than it restarting:
![image](https://github.com/microsoft/vscode/assets/2019016/e97360be-2b06-4e2a-91a7-b16279f824e8)

**Comment by amunger** [comment]
I was prompted to stop the tunnel, rather than it stopping automatically:
![image](https://github.com/microsoft/vscode/assets/2019016/9c450501-0639-4104-8929-6584704c965b)
