### ISSUE TITLE
Feature Request: Add language support for `.toml`

### ISSUE THREAD

**Issue by nurmohammed840** [microsoft/vscode#183625]
Currently `.toml` has no built-in language support.
  
`.toml` file is very similar to `.ini` file format.

Currently the language mode for `.toml` is `Plain Text`,
I recommend setting the default language mode to `ini`, so that it can provide basic syntax highlighting.

**Comment by aeschli** [comment]
There are several extensions for TOML out there.
We don't want to bundle too much with VS Code to keep VS Coce lean but also to share the burden of maintaining with the community.
