### ISSUE TITLE
Underlined links in banner collide with text 

### ISSUE THREAD

**Issue by daviddossett** [microsoft/vscode#183605]
See below. These are also inconsistent with other links in VS Code (most don't use underlines), so not sure why they are there in the first place.

<img width="642" alt="image" src="https://github.com/microsoft/vscode/assets/25163139/306adf11-8cd6-42f4-b1cb-75a05fd79771">

**Comment by lszomoru** [comment]
@daviddossett, the thinking here was to use underline to differentiate between the banner text and the banner actions. Happy to change the styling if you have any suggestions that better aligns with our design system. Also, what browser/version are you using as I am not seeing this in Safari.

**Comment by daviddossett** [comment]
Ah so we don't use the usual `textLink.foreground` token then? I guess that explains why it isn't blue here. It probably didn't meet contrast ratio minimums w/ Dark+ since its banner color was blue.

**Comment by sbatten** [comment]
@daviddossett do you still feel we should change something here?

**Comment by daviddossett** [comment]
For now I think adjusting the colors used in Dark/Light Modern will be a good first step. Since the banner isn't blue in those themes, we can use the typical link color. 

@lszomoru do you remember what the theme color names used here were?

**Comment by lszomoru** [comment]
We are using `banner.foreground` for the link colour. 
https://github.com/microsoft/vscode/blob/ebd67244fb2da33ab078bb2baa96106fda29f336/src/vs/workbench/browser/parts/banner/media/bannerpart.css#L61-L62
