### ISSUE TITLE
Welcome Widget in the editor

### ISSUE THREAD

**Issue by bhavyaus** [microsoft/vscode#183658]
Refs: #179401

- [x] web @sandy081
- [x] web @lszomoru 

Authors: @bhavyaus
Complexity: 1

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23183658%0A%0A&assignees=bhavyaus)

---

We now display a welcome overlay widget in the editor in [insiders.vscode.dev](https://insiders.vscode.dev/). This widget is intended to inform new users and will only appear once during your first session.

Test:
1. Ensure that you have a clean setup. We only show this for a new user who has never used insider.vscode.dev before.
2. Open a GitHub URL such as https://insiders.vscode.dev/github/microsoft/vscode
2. Edit any file in the repo.
3. An overlay widget, such as the one shown below, should appear in the top right-hand corner of the editor when you have paused typing.

![image](https://github.com/microsoft/vscode/assets/25044782/daef974b-c7a6-451c-aa57-f77acadb662d)

Please verify that this dialog only appears once during your first session and that it does not interrupt your typing.
Please note any performance issues you might encounter with rendering the widget content.

**Comment by lszomoru** [comment]
On macOS I have tried multiple browsers (Safari, Edge, Brave) but I was not able to observe the overlay.

**Comment by meganrogge** [comment]
this should be ready for testing in less than an hour with the new build

**Comment by meganrogge** [comment]
@lramos15 thanks for trying. looks like it's still not the latest version

![Screenshot 2023-05-31 at 2 50 24 PM](https://github.com/microsoft/vscode/assets/29464607/aafb998a-40b7-4961-91fd-1b67f6c6b2e7)

**Comment by TylerLeonhardt** [comment]
Just tried and still can't get this to show up.

**Comment by meganrogge** [comment]
it's not yet released
