### ISSUE TITLE
Generated sourcemaps in vscode build are broken. Blocks debugging vscode sourcecode with source maps

### ISSUE THREAD

**Issue by nojvek** [Microsoft/vscode#18363]
After building .js.map files aren't emitting the right information

```
{"version":3,"file":"commonCodeEditor.js","sourceRoot":"file:///Users/noj/git/vscode/src","sources":["/src/vs/editor/common/commonCodeEditor.js"],"names":[],"mappings":";;;;;;IAAA;;;oGAGgG;IAChG,YAAY,CAAC;IA6Bb,IAAO,iBAAiB,GAAG,
```

This should be 

```
{"version":3,"file":"commonCodeEditor.js","sourceRoot":"file:///Users/noj/git/vscode/","sources":["/src/vs/editor/common/commonCodeEditor.ts"],"names":[],"mappings":";;;;;;IAAA;;;oGAGgG;IAChG,YAAY,CAAC;IA6Bb,IAAO,iBAAiB,GAAG,
```

sources should be ts files and sourceRoot should not include src folder. This was working in december but I can no longer debug vscode source with source maps enabled. 

I looked into build/lib/compilation.ts to see if I could figure it out. The build system looks quite complicated than what I am used to.

As a work around I am just going oldschool and debugging js files. Its a painful experience but gets the job done.

**Comment by joaomoreno** [comment]
@isidorn Did you look into this?

**Comment by joaomoreno** [comment]
The problem is not the `sourceRoot` attribute, but the `sourcesContent` which seems to have no content at all...

**Comment by joaomoreno** [comment]
The issue seems to appear during minification. Bundling, which happens right before minification, still keeps sane sourcemaps.

**Comment by joaomoreno** [comment]
And when I build it locally, it actually works. What.

**Comment by bpasero** [comment]
@joaomoreno make sure you do a clean npm install of all modules, I noticed this yesterday only on linux, `scripts/test.sh` --coverage was failing likely due to this issue.

**Comment by joaomoreno** [comment]
Yup, cleaned, reinstalled, rebuilt. I still get good results on my machine. Will look into the build machine what's up.

**Comment by isidorn** [comment]
@joaomoreno I did not look into this, I decided to go with js debugging as everyone in the team seems to be doing that.

**Comment by joaomoreno** [comment]
This is super weird. I just rebuilt on our build machine and it works...

**Comment by joaomoreno** [comment]
And I just realised @nojvek might just be talking about the dev build not the production build.

**Comment by joaomoreno** [comment]
I won't have time to look into why this broke any time soon. @Microsoft/vscode if someone wants TS debugging, please look into this.

**Comment by joaomoreno** [comment]
Found the issue. Well, found a fix. The issue is that no one understands sourcemaps. Neither do we nor anyone who develops libraries for sourcemaps.

**Comment by nojvek** [comment]
Thanks. I'll update my sources.
