### ISSUE TITLE
SEARCH:  Select file on the left when file is open on the right. (feature request)

### ISSUE THREAD

**Issue by knowltonGit** [Microsoft/vscode#18367]
- VSCode Version: any
- OS Version: any

Steps to Reproduce:

1. Open multiple files resulting from a search
2. Select a different file tab than the file you have open.
**3.  Expectation:  file will highlight on the left hand side.**

**Comment by roblourens** [comment]
I actually don't understand the request. You can cmd+click to open a search result file in split view. Is that what you mean?
