### ISSUE TITLE
Allow task bindings (like Task Runner Explorer's ProjectOpened/SolutionOpened)

### ISSUE THREAD

**Issue by langdonx** [Microsoft/vscode#18360]
- VSCode Version: 1.8.1
- OS Version: Windows 10

I'm migrating my solution from VS2015 to VSCode.  Something I'm sorely missing is the ability to launch `grunt watch` automatically when I open the folder.  My gruntfile.js has this at the top (one is from VS2013, the other from VS2015):

    /// <binding BeforeBuild='build-dev' ProjectOpened='watch' />
    /// <vs BeforeBuild='build-dev' SolutionOpened='watch' />

I'd love to see `.vscode/tasks.json` be able to support this kind of thing.

**Comment by alexr00** [comment]
This exits now 😊 #17147
