### ISSUE TITLE
vscode light theme is not easy to distinguish

### ISSUE THREAD

**Issue by StraySheepPO8** [microsoft/vscode#183662]
When I write java code **(using a light theme)**, I use blue for the public keyword #0033b3. The keyword rendering of IntelliJ IDEA is also the same #0033b3 color number, but there are obvious differences between the two software renderings, idea looks more comfortable. **What I'm trying to say is that vscode's light theme code doesn't render well enough, has no contrast, and isn't easy to read. Hope to improve.** Not only blue, all color in light theme is too weak. Thanks for your time!
vscode:
![image](https://github.com/microsoft/vscode/assets/97979993/9362b616-350a-4f6f-9da7-fcaaf9c7c649)

idea:
![image](https://github.com/microsoft/vscode/assets/97979993/385be4cc-ee86-4e8a-83b0-24feaa603d8f)

**Comment by aeschli** [comment]
Please check out the many other themes there are on the marketplace.
In general, we rarely making changes to the default theme to not upset users that like the current colors.
