### ISSUE TITLE
Private tasks for "dependsOn"

### ISSUE THREAD

**Issue by JosephHubbard** [microsoft/vscode#183687]
I, like many people, use vscode's task and launch functionality to entirely abstract away the compilation process of my programs. For complex programs like servers this can get quite messy and I make liberal use of the "dependsOn" feature to chain different compilation programs together.

However, this can get quite messy when I or my team go to run a task and tens of, what should be, intermediate tasks pop up before the actual public important ones.
It would be cool if there was a "private" attribute that can be set such that it removes it from the task menu but still allows it to take part in a "dependsOn".

..This might be a duplicate

**Comment by gjsjohnmurray** [comment]
https://github.com/microsoft/vscode/issues/149095#issuecomment-1195711551
