### ISSUE TITLE
Multiline object properties

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#18364]
In node and node2, I see this when looking at an object with multiline properties like `{ 'a\nb': 'c\nd' }`

In the variables pane, everything lost after the first newline:
![image](https://cloud.githubusercontent.com/assets/323878/21815934/3284f6fc-d713-11e6-8078-d9f6cb38c0de.png)

In the console, preview and prop name are split:
![image](https://cloud.githubusercontent.com/assets/323878/21815896/0d73237a-d713-11e6-902f-3509374f699a.png)

If I remember correctly, we decided that the debug adapter should return the actual value, and the client should display it however it supports it, right? I can't find that discussion. Or should the debug adapter be escaping the newlines in this case?

**Comment by isidorn** [comment]
@roblourens yes debug adapter should return the actual value and the client will display the result as it think is best. Variables pane should replace \n with the actual \n character to prevent this. For some reason this does not seem to be working in this case

**Comment by roblourens** [comment]
Or the 'return' symbol, which I'm a fan of 	⏎

**Comment by roblourens** [comment]
Also, actual newline looks the same as literal \n here:

![image](https://cloud.githubusercontent.com/assets/323878/21816332/ae80e2c4-d714-11e6-8019-d13aec7db18d.png)

**Comment by isidorn** [comment]
Fixed the issue that now the properties also get their value replaced, previosuly it was only the case for values.

As for the ⏎ character I think it looks nice but it does not align well with 2 other characters we replace \t and \r. If there are nice unicode characters for those also then we could replace all 3.

**Comment by roblourens** [comment]
You could use ⇥ for tab. And you could use the newline one for either \r\n or \n.
