### ISSUE TITLE
Why does editor.action.marker.next/prev remove focus from the editor?

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#18366]
- VSCode Version: Code - Insiders 1.9.0-insider (12af9ea6effefeaeecde2107c960ae5222703864, 2017-01-09T07:18:17.300Z)
- OS Version: Linux x64 4.8.0-30-generic
- Extensions:

|Extension|Author|Version|
|---|---|---|
|EditorConfig|EditorConfig|0.3.4|
|lorem-ipsum|Tyriar|1.0.0|
|sort-lines|Tyriar|1.1.0|
|theme-glacier|Tyriar|0.0.10|
|vscode-svgviewer|cssho|1.3.0|
|vscode-eslint|dbaeumer|1.2.2|
|python|donjayamanne|0.5.5|
|tslint|eg2|0.8.1|
|git-project-manager|felipecaputo|1.0.0|
|Theme-Wombat|gerane|0.0.2|
|md-navigate|jrieken|0.0.1|
|vscode-scss|mrmlnc|0.6.0|
|typescript-javascript-grammar|ms-vscode|0.0.15|
|seti-icons|qinjia|0.1.3|
|sass-indented|robinbentley|1.3.0|
|dark-plus-material|vangware|0.1.4|

---

I _really_ want to get used to using F8/shift+F8 to navigate to errors on the page but it makes it difficult the way it messes with the editor's focus.

Steps to Reproduce:

1. Open a file with errors
2. Press F8, notice that focus is on the inline problem view itself, not the editor. This means in order to fix the error I need to either focus the editor (ctrl+<num>) or close the problem view (esc), the latter of which hides the error.

![image](https://cloud.githubusercontent.com/assets/2193314/21817716/f1bbba14-d719-11e6-9059-03e06d39142b.png)

This is the state that I want it in when I press F8, where esc will dismiss the problem view and F8 will go to the next problem, not focus the opened problem view:

![image](https://cloud.githubusercontent.com/assets/2193314/21817761/24c493cc-d71a-11e6-9a82-32d70f37706b.png)

**Comment by jrieken** [comment]
I know, but we have to do this because of accessibility...

**Comment by Tyriar** [comment]
@jrieken surely there's a way to make it usable and accessible. How about keeping focus on the editor, using [`aria-alert`](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ARIA_Techniques/Using_the_alert_role) to surface the message to screen readers and making the problem view itself `aria-hidden`?

**Comment by jrieken** [comment]
@alexandrudima did the reasoning about that change

**Comment by alexandrudima** [comment]
My understanding is that aria alerts should be avoided if possible and aria roles should be used (I believe aria alerts interrupt the screen reader and immediately announce the text in the alert).

**Comment by jrieken** [comment]
A workaround would be to allow an argument to the next/prev command which goes like `{focus: false}`

**Comment by Tyriar** [comment]
@alexandrudima that's the point though isn't it? Do we not want it immediately announced because the editor scrolls down to the section?

@jrieken that would fix my use case but I imagine other people have this gripe as well, command args aren't very discoverable.

**Comment by jrieken** [comment]
Thanks to @alexandrudima we now know if a screen reader has been attached. This allows us to change the behaviour of F8 accordingly.

**Comment by Tyriar** [comment]
@jrieken great news :smile: I plan on using F8 a lot more now.
