### ISSUE TITLE
Orca talking excessively when using QuickPick

### ISSUE THREAD

**Issue by jvesouza** [microsoft/vscode#183642]
Type: <b>Bug</b>
CC: @meganrogge @isidorn 

Steps to reproduce:

1. Press ctrl+shift+p .
2. Pay attention to the message that is read by the orca. Basically it informs what action can be performed by the user and if there is any command selected, it also informs what the command is.
3. start typing slowly.

In my environment, for each typed character, practically all information spoken in step 2 is repeated, along with information from the new command.

In my opinion information from the new command would suffice. The same behavior can be observed in other scenarios such as searching for files activated with ctrl+p.

VS Code version: Code - Insiders 1.79.0-insider (2dfb838f494f035099e999f0cd0eff5f1f488a30, 2023-05-26T05:24:15.146Z)
OS version: Linux x64 6.2.15-300.fc38.x86_64
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 3002)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|1, 1, 1|
|Memory (System)|15.26GB (6.28GB free)|
|Process Argv|-n /backup/sotreq/predic/Sotreq.PredicAPI/ --crash-reporter-id bc02adbd-6c3a-44b8-af92-55103a608af7|
|Screen Reader|yes|
|VM|0%|
|DESKTOP_SESSION|gnome-xorg|
|XDG_CURRENT_DESKTOP|GNOME|
|XDG_SESSION_DESKTOP|gnome-xorg|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (45)</summary>

Extension|Author (truncated)|Version
---|---|---
doxdocgen|csc|1.4.0
vscode-markdownlint|Dav|0.50.0
vscode-eslint|dba|2.4.0
EditorConfig|Edi|0.16.4
copilot-chat|Git|0.1.2023052602
copilot-nightly|Git|1.86.118
rest-client|hum|0.25.1
better-cpp-syntax|jef|1.17.2
docomment|k--|1.0.0
azure-pipelines|ms-|1.208.0
vscode-docker|ms-|1.25.1
csharp|ms-|1.25.7
vscode-dotnet-runtime|ms-|1.6.0
vscode-kubernetes-tools|ms-|1.3.11
remote-containers|ms-|0.294.0
remote-ssh|ms-|0.103.2023051015
remote-ssh-edit|ms-|0.86.0
azure-account|ms-|0.11.5
azurecli|ms-|0.5.0
cmake-tools|ms-|1.14.31
cpptools|ms-|1.16.0
cpptools-extension-pack|ms-|1.3.0
makefile-tools|ms-|0.7.0
powershell|ms-|2023.5.3
remote-explorer|ms-|0.5.2023040509
vsliveshare|ms-|1.0.5864
oracledevtools|Ora|21.5.0
fabric8-analytics|red|0.3.10
java|red|1.19.2023052604
vscode-xml|red|0.25.2023051904
vscode-yaml|red|1.13.0
sonarlint-vscode|Son|3.18.0
cmake|twx|0.0.17
intellicode-api-usage-examples|Vis|0.2.7
vscodeintellicode|Vis|1.2.30
vscode-boot-dev-pack|vmw|0.2.1
vscode-spring-boot|vmw|1.46.0
vscode-java-debug|vsc|0.50.2023052405
vscode-java-dependency|vsc|0.22.2023051900
vscode-java-pack|vsc|0.25.2023052400
vscode-java-test|vsc|0.38.2023051002
vscode-maven|vsc|0.41.2023042103
vscode-spring-boot-dashboard|vsc|0.13.0
vscode-spring-initializr|vsc|0.11.2
gitblame|wad|10.2.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256198
vstes627cf:30244335
vslsvsres303:30308271
pythontb:30258533
pythonptprofiler:30281269
vshan820:30294714
vscod805cf:30301675
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30404738
cppdebug:30492333
vsclangdf:30492506
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30618038
pylantcb52:30590116
pyind779:30611226
pythonsymbol12:30651887
showlangstatbar:30737417
pythonms35:30671666
cai9j608:30680470
24365598:30687740
pythonfmttext:30716741
pythoncmvfstr:30726892
fixshowwlkth:30724385
hidesbindicator:30724476
pythongtdpath:30726887

```

</details>

**Comment by TylerLeonhardt** [comment]
@isidorn / @meganrogge so I tested this in NVDA and it says something more reasonable:
* the character you typed (ex: "a")
* the number of results (ex: "200 results")
* the command name (ex: "Add breakpoint")
* the number that that item is (ex: "3 of 200")

What's the guidance here for when one screen reader is more correct than the other?

**Comment by meganrogge** [comment]
When it works for one screen reader and not another (orca), that means it's a problem with orca. 

@jvesouza thank you for the report. can you pls report this issue to orca?

**Comment by meganrogge** [comment]
It's possible this has the same root cause as https://github.com/microsoft/vscode/issues/121811 and thus will be fixed in June. Let's track there

**Comment by joanmarie** [comment]
It's now fixed in Orca master.
