### ISSUE TITLE
Integrated Terminal not auto-scrolling

### ISSUE THREAD

**Issue by jmc265** [Microsoft/vscode#18362]
- VSCode Version: Insider (1.9.0-insider)
- OS Version: Mac OSX

Steps to Reproduce:

1. Open integrated terminal
2. Do a command which will output text which should scroll the window
3. The window is not scrolled all the way to the bottom

This is something which is only happening very recently in the Insider build (last day or 2)

**Comment by jmc265** [comment]
I don't really know much about your code base here, but this might be the culprit:

https://github.com/Microsoft/vscode/commit/5f73daec57aabf74458bd2f67635020870513104

**Comment by Tyriar** [comment]
Just fixed it :smile: https://github.com/Microsoft/vscode/issues/18370

Resizing the terminal should fix the problem until the fix is out tomorrow.

**Comment by Tyriar** [comment]
I checked on my other PC and this is in fact a distinct issue from #18370

**Comment by Tyriar** [comment]
Increasing the vertical size of the panel breaks the prompt line until something is input.

**Comment by Tyriar** [comment]
@jmc265 you were right, it was exactly that commit :+1:
