### ISSUE TITLE
Test project wide JS/TS IntelliSense on web

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#183684]
Test for #170920

- [x] web @bpasero
- [x] web @Tyriar

Complexity: 4

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23183684%0A%0A&assignees=mjbvz)

--- 

### Summary
We've enabled project wide IntelliSense on web for JS/TS projects with a key limitations. More importantly, all semantic errors are currently disabled until we ship support for type acquisition on web. Additionally, intellisense will not work for third party packages for the same reason

### Testing
For this test plan item, try exploring that works and what doesn't with this feature. You can use https://insiders.vscode.dev/github/microsoft/vscode-markdown-languageservice to test

Try our Intellisense features like `find all references` and `go to definition`, along with auto imports. Also try changing the `tsconfig.json` (such as turning on/off certain strictness errors) and make sure these changes are picked up

You can disable project wide Intellisense on web by setting `typescript.tsserver.web.projectWideIntellisense.enabled`

**Comment by bpasero** [comment]
So 💯 useful! I tested in Chrome. I was not sure how to test changes to `tsconfig.json` though, given we do not seem to show any warnings.
