### ISSUE TITLE
VSC latex structure not work

### ISSUE THREAD

**Issue by SunYoungCurrent** [microsoft/vscode#183721]
Type: <b>Bug</b>

I wrote LATEX in VSC, installed TEXLIVE correctly, and downloaded the LATEX workshop, but there was no response to the Structure function of LATEX. Clicking on a chapter will always redirect the code in the tex file of LATEX to the beginning, rather than to the corresponding chapter. I can't figure it out.

As shown in the figure, I clicked on Chapter 4 on the left, but the code on the right did not jump to Chapter 4

![image](https://github.com/microsoft/vscode/assets/92208838/ac38e1ec-3519-4102-a207-2c21d4d5ed41)

VS Code version: Code 1.78.2 (b3e4e68a0bc097f0ae7907b217c1119af9e03435, 2023-05-10T14:39:26.248Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|13th Gen Intel(R) Core(TM) i7-13700H (20 x 2918)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.74GB (19.83GB free)|
|Process Argv|--crash-reporter-id 72e8c8f6-16ec-4064-9cd4-5fdd716e49b6|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
latex-workshop|Jam|9.11.4
vscode-latex|mat|1.2.0
vscode-language-pack-zh-hans|MS-|1.78.2023051009
latex-utilities|tec|0.4.10

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
282f8724:30602487
pyind779:30671433
89544117:30613380
pythonsymbol12:30671437
a9j8j154:30646983
showlangstatbar:30737416
vsctsb:30748421
pythonms35:30701012
pythonfmttext:30731395
pythoncmv:30739700
fixhidewlkth:30730051
showsbindicator:30730056
pythongtdpathcf:30739705

```

</details>

```[tasklist]
### Tasks
```

```[tasklist]
### Tasks
```

**Comment by SunYoungCurrent** [comment]
The problem has been resolved. It is indeed caused by extension. There are two different types of LATEX workshops written by two different authors. I should download the other  author's, which has a smaller download volume, but it can solve my problem.

**Comment by afjun** [comment]
Indeed, the issue is attributable to versioning, and the resolution is simply a matter of replacing the current version with a historical version.
