### ISSUE TITLE
Test default additional builtin extension in insiders.vscode.dev

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#183734]
Refs: https://github.com/microsoft/vscode/issues/174682

- [x] anyOS @joyceerhl 
- [x] anyOS @lszomoru 
- [x] anyOS @jrieken 

Complexity: 5

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23183734%0A%0A&assignees=sandy081)

---

This TPI is to test that [insiders.vscode.dev](https://insiders.vscode.dev) will always load latest version for following additional builtin extensions

- ms-vscode.azure-repos
- ms-vscode.remote-server
- GitHub.remotehub
- GitHub.codespaces 
- ms-vscode.anycode

Make sure when you open insiders.vscode.dev always latest versions of above extensions are loaded. Not only above extensions, their transitive closure dependencies and extension pack extensions are also loaded with latest versions.

- `ms-vscode.remote-repositories` extension, dependency of `ms-vscode.azure-repos` and `GitHub.remotehub`
- **9** anycode extensions included in the `ms-vscode.anycode` extension
- `ms-vscode.remote-explorer` extension included in `ms-vscode.remote-server` and `GitHub.codespaces` extensions

Try to publish a new version for one of these extensions and make sure this version is loaded in insiders.vscode.dev. 

- ms-vscode.azure-repos (@lszomoru): Test loading dev version of this extension by passing the location using the query param `vscode-azurerepos-dev`. For example, host this extension locally and pass the location in the URL like below
`https://insiders.vscode.dev/?vscode-azurerepos-dev={location}`. This will override the extension that comes from the MP.
- GitHub.remotehub (@joyceerhl): Test loading dev version of this extension by passing the location using the query param `vscode-remotehub-dev`. For example, host this extension locally and pass the location in the URL like below
`https://insiders.vscode.dev/?vscode-remotehub-dev={location}`. This will override the extension that comes from the MP.

**Please NOTE** that server has a cache time of 2.5 minutes and MP also has a cache (5~10mins), which means in a worst case, if a new version of extension is published to MP, it might not be available on insiders.vscode.dev for a max of **15 minutes**. For all these extensions **Update** action is never shown even if there is a latest version in Marketplace. 

**Troubleshoot:** In case, the latest version is not loaded, please open Elements tab in dev tools and share the content of the `meta` element with name `vscode:defaultExtensions` under `head` element.

**Comment by joyceerhl** [comment]
> Test loading dev version of this extension by passing the location using the query param vscode-remotehub-dev. For example, host this extension locally and pass the location in the URL like below

Does this mean it is no longer possible to do Install Extension From Location for an embedder builtin extension like GitHub Repositories?

**Comment by joyceerhl** [comment]
Latest version loading in insiders.vscode.dev works like a charm :clap:

**Comment by lszomoru** [comment]
+ 💯 on automatically loading the latest version 👏🏻

**Comment by sandy081** [comment]
> Does this mean it is no longer possible to do Install Extension From Location for an embedder builtin extension like GitHub Repositories?

I would say `Install Extension From Location` is the recommended approach. To clarify, I did not add the support for 

> Test loading dev version of this extension by passing the location using the query param vscode-azurerepos-dev. For example, host this extension locally and pass the location in the URL like below
https://insiders.vscode.dev/?vscode-azurerepos-dev={location}. This will override the extension that comes from the MP.

This was there before (I do not know who added this) adding this feature and in this TPI I just want to make sure this is not broken with my changes. If no one owns this, I would like to remove this.

CC @lszomoru @joyceerhl
