### ISSUE TITLE
Empty reason while switching profile

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#183775]
Testing #183534

- Open a folder that has a image in an empty profile
- Install Luna Paint Extension
- Edit the image using Luna Paint and do not save
- Switch the profile to another profile
🐛 Reason is empty

<img width="573" alt="image" src="https://github.com/microsoft/vscode/assets/10746682/448be215-af02-41f9-b8fd-5a87ea313d25">

**Comment by bpasero** [comment]
Good catch, there is an error thrown but I fail to remember the reason in that case. It should be:

![image](https://github.com/microsoft/vscode/assets/900690/3cedd021-23d1-4134-a7f2-d2509672d2f9)
