### ISSUE TITLE
How should extensions programmatically set the languageId or files.associations?

### ISSUE THREAD

**Issue by sean-mcmanus** [Microsoft/vscode#18374]
I'm not sure if this is the correct place to ask this...

Our C++ extension knows that certain files located via #include <string> should have a languageId = "cpp" or "c", so we want to be able to set that for the files (opened via Go To Definition) or automatically add it to the files.associations setting. What method do you guys recommend? Making edits to settings.json is problematic because it is non-standard JSON with comments and I don't know a parser that allows roundtrip insertions into it that preserve the comments. Having access to some internal parser like ConfigurationEditingService.writeConfiguration might work but that doesn't seem to be available via the public extension APIs.

**Comment by jrieken** [comment]
If you know your files by extension, name, pattern, or first line content *statically* you should use `package.json` and the [`languages`](https://code.visualstudio.com/docs/extensionAPI/extension-points#_contributeslanguages) contribution point. 

For *dynamic* language associations you can update the configuration using the [API](https://github.com/Microsoft/vscode/blob/master/src/vs/vscode.d.ts#L2819) for that.

**Comment by sean-mcmanus** [comment]
@jrieken Thanks a lot. That's what I wanted. I didn't see WorkspaceConfiguration.update because we were using engine "1.4.0", but I got if after updating to the "1.6.0" engine.

**Comment by jrieken** [comment]
I still wonder why the package.json solution doesn't work?

**Comment by sean-mcmanus** [comment]
We don't know the files statically in the situation where people use Go to Definition on a #include for a file that is extensionless or has non-standard extensions (C++ doesn't have an extension requirement for header files). Users can manually configure the files.associations, but we wanted to investigate the possibility of making that automatic.

**Comment by jrieken** [comment]
ok
