### ISSUE TITLE
source maps interpretation inconsistent

### ISSUE THREAD

**Issue by cdaringe** [Microsoft/vscode#18373]
- VSCode Version: `Version 1.8.1 (1.8.1)`
- OS Version: `osx 10.11.6`

# problem statement

- source maps are only periodically honored, based on compiled content.

# discussion

- i confess, this _may_ be an issue with `babel`s sourceMap output, but i'm still debugging that.  i figured i'd post this in advanced in case there is existing visibility or ideas people might have.

# example

1. observe a compile->test->debug session, watch sourceMaps **not** be honored
1. add a `debugger` statement. observe another compile->test->debug session, watch sourceMaps **be** honored

![babel-sourcemaps-not-honored mov](https://cloud.githubusercontent.com/assets/1003261/21821896/12939166-d72a-11e6-94c9-bee39f451510.gif)

Steps to Reproduce:

1. see https://github.com/cdaringe/babel-vscode-source-map-woes

**Comment by cdaringe** [comment]
this was working in the same code base as shown over in the screen cast at https://github.com/facebookincubator/create-react-app/pull/1360

gotta🚶 for a bit.  maybe it will come to me :)

**Comment by roblourens** [comment]
Not exactly sure what's happening in your gif, but the test repo works fine for me. I'm using vscode insiders, so maybe something is fixed there now.
