### ISSUE TITLE
Project wide intellisense not working on github.dev

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#183765]
Testing #183684

Wonderful feature 👏 . But it seems to not work on github.dev, which I use for reviewing PRs, such as https://github.dev/microsoft/vscode/pull/183310

To reproduce:
* open `editorCommands.ts`
* click on line 10 on the `IEditorIdentifier` import
* Find All References

**Comment by mjbvz** [comment]
@jrieken Looks like `window.crossOriginIsolated` is false for GitHub.dev (even on insiders). Do you know when they plan to enable this?

**Comment by jrieken** [comment]
We haven't engaged with them yet

**Comment by jrieken** [comment]
This will be supported via the `?vscode-coi=on` query, see https://github.com/github/codespaces-web/pull/455
