### ISSUE TITLE
No dialog is shown when entering a workspace

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#183780]
Testing #183534

- Open a folder with an image file
- Install Luna Paint extension and edit the image file and do not save it
- Enter into workspace - `Workspaces: Save Workspace As...`

🐛 No dialog is shown and workspace is opened

**Comment by bpasero** [comment]
To clarify: there should not be any dialog, we explicitly trigger a save. If you have steps with a specific image, let me know.
