### ISSUE TITLE
Terminal API should throw an event when a terminal has completed (and is waiting to close)

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#18376]
From @dbaeumer:

> an event when a task executed in a terminal has finished (e.g. the terminal process existed)

**Comment by dbaeumer** [comment]
What I actually want to do is the following:

```ts
this.terminalService.createInstance(`Task: ${task.name}`, undefined, ['/C', 'dir'], false);
```

`dir` is an example here and '/C' is currently specific to cmd.exe. 

What I would like to see happening here is that the cmd.exe is started, dir is executed and then cmd.exe terminates. When cmd.exe terminates I would like to get an event.

Regarding the '/C' option: any change to have this abstracted in the terminal itself. Having that knowledge on the client side is not very nice.

**Comment by dbaeumer** [comment]
What currently happens is the following:

- the terminal is started
- dir is not executed
- the terminal stays alive

**Comment by dbaeumer** [comment]
I changed it to 
`this.terminalService.createInstance(`Task: ${task.name}`, 'C:\\WINDOWS\\system32\\cmd.exe', ['/C', this.configuration.command], false);` after some debugging but now no terminal shows up

**Comment by Tyriar** [comment]
Did you call `Terminal.show()` immediately after? API terminals are launched in the background. You could try point to `C:\\Windows\\sysnative\\cmd.exe` and/or use an environment var to find `C:\\Windows`. `Sysnative` is a weird symlink thing that points to `system32` or `syswow64`. Try that first and maybe `rm -rf node_modules/node-pty node_modules/pty.js` and try reinstall deps?

It would be good to encapsulate the bash and cmd command execution commands inside the TerminalService, however I'm not sure something like that should be exposed in the Terminal API. In general I don't want to encourage using a custom shell/args unless the specific use case calls for it (like tasks).

**Comment by dbaeumer** [comment]
I got it working passing in true to `waitOnExit`. My code looks like this now:

```typescript
let terminal = this.terminalService.createInstance(`Task: ${task.name}`, 'C:\\WINDOWS\\system32\\cmd.exe', ['/C', this.configuration.command], true);
this.terminalService.setActiveInstance(terminal);
this.terminalService.showPanel(false);
```

What I actually would like to have is a listener instead of the waitOnExit. But we already discussed this.

**Comment by dbaeumer** [comment]
Regarding:

> It would be good to encapsulate the bash and cmd command execution commands inside the TerminalService, however I'm not sure something like that should be exposed in the Terminal API. In general I don't want to encourage using a custom shell/args unless the specific use case calls for it (like tasks).

As said we keep the task framework in the core for now. So it would allow us to experiment with some API here before thinking about making it official.

**Comment by Tyriar** [comment]
@dbaeumer I guess I'll expose some event on `ITerminalInstance` exit for now which when used with `waitOnExit` to allow reuse of the terminal (via another `ITerminalInstance` call to start up a new process while retaining the old output).

**Comment by Tyriar** [comment]
I closed this as it's possible internally now via `ITerminalInstance.onExit`
