### ISSUE TITLE
Test: Running tunnels must not block Linux or Mac uninstall or update

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode#183700]
Refs: https://github.com/microsoft/vscode/issues/177226

- [x] Linux @connor4312 apt
- [x] Linux @roblourens snap
- [x] Mac @deepak1556

Complexity: 3

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23183700%0A%0A&assignees=aeschli)

---

Test that running tunnels should not block an update or uninstall of VS Code

- install the latest VS Code insiders 
- close VS Code, make sure no tunnel is running: From the command prompt run `code-insiders tunnel status`. It should say `no tunnel process is currently running`
- start a tunnel server as service from the command prompt: `code-insiders tunnel service install`. `code-insiders tunnel status` should show you a running tunnel. The task manager should show the running tunnel (look for `code-insiders-tunnel`)

1. uninstall should work without issues. Check in the task manager that the process is gone
2. update should also work. The tunnel should not be stopped

**Comment by roblourens** [comment]
I haven't been able to test the upgrade scenario with a snap, but I'll test it with the real insiders update tomorrow.
