### ISSUE TITLE
editor.quickSuggestions setting for completion providers

### ISSUE THREAD

**Issue by W4RH4WK** [Microsoft/vscode#18372]
I have set `editor.quickSuggestions` to `false` and like to bring the suggestions up manually when I need them. Recently I encountered an issue with an extension (ChristianKohler/PathIntellisense#52) where the autocompletion popup is shown upon hitting `/`.

Investigating the API in more detail it seems that the registered *trigger characters* are used to trigger the extension in a generic fashion, independent of the extension's specific function. So while the corresponding *trigger characters* should still be registered, in the case of a `CompletionItemProvider` such a character should only trigger the extension if `editor.quickSuggestions` is set to `true`.

What do you think about this?

**Comment by jrieken** [comment]
There are 2 settings:

* `editor.quickSuggestions` invoke IntelliSense while you type *words*, aka as 24x7 IntelliSense
* `editor.suggestOnTriggerCharacters` invoke IntelliSense when a registered trigger character is encountered

For the full manual mode set both settings to `false`

**Comment by W4RH4WK** [comment]
Oh sorry, I have missed that there is a dedicated option for the trigger characters, thanks for pointing that out.
