### ISSUE TITLE
Terminal image - six image shown only briefly

### ISSUE THREAD

**Issue by lszomoru** [microsoft/vscode#183797]
Testing #183563

* Clone https://github.com/saitoha/libsixel.git
* Open terminal and run:
  * `cat images/snake.six` will show the image
  * `cat images/map8.six` will only show the image briefly after this it is gone

<img width="902" alt="image" src="https://github.com/microsoft/vscode/assets/3372902/758c27d8-c922-4da1-a08e-6a391e413fc0">

**Comment by Tyriar** [comment]
The map8.six issue is covered by https://github.com/microsoft/vscode/issues/183840
