### ISSUE TITLE
Can the action be called open on vscode.dev

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#183790]
Testing #183576

Can the action be called open on vscode.dev just like other action to open in GitHub?

<img width="265" alt="image" src="https://github.com/microsoft/vscode/assets/10746682/9aea26f5-e031-49b2-b932-868a90213fd5">

<img width="198" alt="image" src="https://github.com/microsoft/vscode/assets/10746682/c9f42898-6060-4483-988b-3b7d53fa93ac">

**Comment by joyceerhl** [comment]
I would not change this for now since we use checkout vs open elsewhere, e.g. GHPRI view context menu: <img width="341" alt="image" src="https://github.com/microsoft/vscode/assets/30305945/c721bb2b-519c-44df-86ac-7322fa041265">
