### ISSUE TITLE
Question - Can QuickOpen go to the open file in a different editor group?

### ISSUE THREAD

**Issue by psrivongse** [Microsoft/vscode#18375]
- VSCode Version: 1.8.1
- OS Version: Windows 7

Is this currently a setting? 
If I have 2 editor groups, Group A has index.html, Group B does not have index.html. I'm focused in Group B and I use QuickOpen (ctrl+p) to open index.html, can I make it focus the opened index.html in Group A?

**Comment by bpasero** [comment]
****
