### ISSUE TITLE
Breakpoints on the extreme left edge of the glyph margin

### ISSUE THREAD

**Issue by jpallatin** [microsoft/vscode#183723]
Type: <b>Bug</b>

Are the breakpoints on the glyph margin in the intended position? It seems to me they are a little on the extreme left side edge.

VS Code version: Code 1.78.2 (b3e4e68a0bc097f0ae7907b217c1119af9e03435, 2023-05-10T15:00:40.428Z)
OS version: Darwin arm64 22.5.0
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|3, 4, 3|
|Memory (System)|16.00GB (0.30GB free)|
|Process Argv|--crash-reporter-id d7807ade-c720-444a-a86a-1f19a144576f|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
catppuccin-vsc|Cat|2.7.0
prettier-vscode|esb|9.13.0
code-runner|for|0.12.0
material-icon-theme|PKi|4.27.0
LiveServer|rit|5.7.9

(1 theme extensions excluded)

</details>

**Comment by roblourens** [comment]
If they look wrong, can you include a screenshot?

**Comment by jpallatin** [comment]
I don’t really know if it’s wrong or if this is on purpose. Breakpoints to the extreme left (should be centered in the glyph margin, in my humble opinion):

[Screenshot 2023-06-01 at 8.06.09 PM.png]


On 1/06/2023, at 7:57 PM, Rob Lourens ***@***.***> wrote:



If they look wrong, can you include a screenshot?

**Comment by roblourens** [comment]
And if you have any other margin glyphs in that file, then it may change the size of the glyph margin, however I think breakpoints should always be on the right, near the line numbers

**Comment by jpallatin** [comment]
<img width="1512" alt="Screenshot 2023-06-01 at 8 06 09 PM" src="https://github.com/microsoft/vscode/assets/98668838/8c5853a6-558b-4e92-887a-5e5d0b83941b">

**Comment by roblourens** [comment]
I think that is correct, there is just some space for the line numbers to grow. You can check whether you have any settings or extensions impacting this too
