### ISSUE TITLE
Microsoft authentication broken on Codespaces (Web Insiders)

### ISSUE THREAD

**Issue by ronakj** [microsoft/vscode#183754]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.79.0-insiders
- OS Version: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36 Edg/113.0.1774.57

Steps to Reproduce:

1. Create Codespace in this repo.
2. Switch to insiders using settings icon in bottom left.
3. Install any extension which needs Microsoft login. I used this one https://marketplace.visualstudio.com/items?itemName=ms-azuretools.vscode-azureresourcegroups.
4. After going through the login process, come back to VSCode page. The extension doesn't seem to get the auth and VSCode also doesn't have any signed in Microsoft account in the account section.

This doesn't happen in stable version. I really want to make sure this issue doesn't get propagated to stable, because our Codespaces workflow is very heavily dependent on Microsoft auth working properly.

**Comment by TylerLeonhardt** [comment]
can you provide the contents of the Microsoft Authentication output pane:
![image](https://user-images.githubusercontent.com/2644648/128087382-c706864f-7005-4a2e-878b-662c69c4457e.png)

And also anything that shows up in Dev Tools:

* ctrl + shift + P
* "Dev Tools"

**Comment by ronakj** [comment]
<details><summary>Microsoft Authentication (Remote) Output</summary>

```

2023-05-30 19:12:03.564 [info] Reading sessions from secret storage...
2023-05-30 19:12:03.564 [info] Got 0 stored sessions
2023-05-30 19:12:03.564 [info] Getting sessions for all scopes...
2023-05-30 19:12:03.564 [info] Got 0 sessions for all scopes...
2023-05-30 19:12:03.564 [info] Getting sessions for the following scopes: email offline_access openid profile
2023-05-30 19:12:03.564 [info] Got 0 sessions for scopes: email offline_access openid profile
2023-05-30 19:12:32.578 [info] Getting sessions for the following scopes: email https://management.azure.com/.default offline_access openid profile
2023-05-30 19:12:32.578 [info] Got 0 sessions for scopes: email https://management.azure.com/.default offline_access openid profile
2023-05-30 19:12:34.252 [info] Logging in for the following scopes: email https://management.azure.com/.default offline_access openid profile
```
</details>

<details><summary>Microsoft Authentication Output</summary>

```

2023-05-31 00:41:58.856 [info] Reading sessions from secret storage...
2023-05-31 00:41:58.856 [info] Got 0 stored sessions
2023-05-31 00:41:58.856 [info] Getting sessions for all scopes...
2023-05-31 00:41:58.856 [info] Got 0 sessions for all scopes...
```
</details>

Nothing relevant in Dev Tools (no errors, warnings after login)

**Comment by TylerLeonhardt** [comment]
@joaomoreno looks like the UrlHandler in the Microsoft auth extension isn't firing. Any ideas why?

**Comment by TylerLeonhardt** [comment]
One thing that’s interesting is that my [open-external extension](https://marketplace.visualstudio.com/items?itemName=TylerLeonhardt.open-external) ([code here](https://github.com/TylerLeonhardt/open-external/blob/main/src/extension.ts#L61-L70)) works fine:
![image](https://github.com/microsoft/vscode/assets/2644648/5d2e926e-dd87-45ce-81d4-7a0c79449b6f)

 but when I start either the Microsoft or GitHub auth flows… their URL Handlers in the extension never fire… so the issue appears to be before the auth extensions, but we have Core & Codespaces layers still to choose from.

Another simple repro with GitHub auth:
* Install my [Fugio](https://marketplace.visualstudio.com/items?itemName=TylerLeonhardt.fugio) extension
* Run: `Fugio: Mint Token`
* Choose either `github` or `microsoft`
* if you choose GitHub, use `workflow` as the value for scopes. If you choose Microsoft, use `offline_access` as the value for scopes

Go through the flow. Works in Stable just fine... but not Insiders.

**Comment by TylerLeonhardt** [comment]
Adding @osortega + @jkeech from the Codespaces side.

**Comment by osortega** [comment]
@TylerLeonhardt this seems to be a CORS issue happening in the extension host worker

<img width="1357" alt="Screenshot 2023-05-31 at 2 28 21 PM" src="https://github.com/microsoft/vscode/assets/48293249/d1f19860-6b3e-478a-a1ff-399a9214cb97">

It also seems to only happen on latest insiders, if you go back in time and use an older version everything works fine.
I'm unfamiliar with that particular request but perhaps there was a change in the request headers?

**Comment by TylerLeonhardt** [comment]
@osortega I think you must be experiencing something different from myself and @ronakj. I don't even get that far where that request happens.

**Comment by joaomoreno** [comment]
@TylerLeonhardt has bisected the behavior change to have happened somewhere in this commit range: https://github.com/microsoft/vscode/compare/9084e081d4e89ed8ab67fce340d573c4e1378939...9233de805c8fb05fad4d9d1c15f22fbca85430ad

**Comment by TylerLeonhardt** [comment]
Ok so to but a brief summary here... 

This was happening because the GitHub Authentication extension was running in both the web worker extension host and the remote extension host.

@alexdima pushed a change that influenced when the web worker extension host started and this issue should be fixed in the latest insiders.

However, this fix only applies to Codespaces and not Remote Tunnels. I will close this issue since it's fixed for Codespaces, but I will open another issue for Remote Tunnels.
