### ISSUE TITLE
Electron 24 updates d3dcompiler_47.dll to 10.0.22621.755

### ISSUE THREAD

**Issue by ChaseKnowlden** [microsoft/vscode#183730]
Type: <b>Bug</b>

PR #180466
Download Electron from https://github.com/electron/electron/releases/tag/v24.0.0.
Unzip the files.
See the d3dcompiler_47 change. 
![image](https://github.com/microsoft/vscode/assets/46290258/a34aedfd-e785-4906-8157-782631307b78)

VS Code version: Code - Insiders 1.79.0-insider (667d4629dee90744edd5054f13bc2452c8c14490, 2023-05-29T05:20:12.992Z)
OS version: Windows_NT x64 10.0.22621
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 5700G with Radeon Graphics          (16 x 3793)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|13.90GB (5.19GB free)|
|Process Argv|--crash-reporter-id ab7ad0b7-0c37-41e0-a133-6bf01b9e6c7e|
|Screen Reader|no|
|VM|44%|
</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-tailwindcss|bra|0.9.11
vscode-eslint|dba|2.4.0
EditorConfig|Edi|0.16.4
vscode-pull-request-github|Git|0.64.0
remote-containers|ms-|0.294.0
vscode-github-issue-notebooks|ms-|0.0.128
vscode-selfhost-test-provider|ms-|0.3.15
rust-analyzer|rus|0.4.1532
code-spell-checker|str|2.20.4
vscode-lldb|vad|1.9.2
volar|Vue|1.7.8
vscode-typescript-vue-plugin|Vue|1.7.8
markdown-all-in-one|yzh|3.5.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256198
vslsvsres303:30308271
pythontb:30258533
pythonptprofiler:30281269
vshan820:30294714
vscod805cf:30301675
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30404738
cppdebug:30492333
vsclangdf:30492506
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30618038
pylantcb52:30590116
pyind779:30611226
pythonsymbol12:30651887
a9j8j154:30646983
showlangstatbar:30737417
pythonms35:30671666
03d35959:30680466
7ij38806:30687742
pythonfmttext:30716741
pythoncmvfstr:30726892
fixshowwlkth:30724385
hidesbindicator:30724476
pythongtdpath:30726887

```

</details>

**Comment by deepak1556** [comment]
@ChaseKnowlden can you elaborate what issue comes with d3dcompiler version update ?

**Comment by ChaseKnowlden** [comment]
I extracted electron v24.0.0 from https://github.com/electron/electron/releases/tag/v24.0.0, then see this screenshot 
![Screenshot 2023-05-30 202438](https://github.com/microsoft/vscode/assets/46290258/5b1f6263-fa27-4d29-9cf9-d32690d0eba9)

**Comment by deepak1556** [comment]
Yes I can see the version update but is there any regression you are facing from the update ? I am trying to understand what the scope of this issue is ?

**Comment by ChaseKnowlden** [comment]
Fixes issues.

**Comment by deepak1556** [comment]
Closing as there is nothing actionable from our end.
