### ISSUE TITLE
Move to new file action shall open the file picker

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#183795]
Testing #183683

Move to new file action shall open the file picker
- Default location is the location where the existing file exists
- Default name of the file being set to the name of the symbol.

**Comment by mjbvz** [comment]
> Move to new file action shall open the file picker 

Do you mean you expect the file picker to be opened directly instead of first showing a list of candidate files in a quick pick?

**Comment by sandy081** [comment]
At present, `Move to New File...` action is creating the file with name as the symbol name automatically. It is not showing any save file dialog.

**Comment by mjbvz** [comment]
Thanks for the details. This is the expected behavior for the `move to new file` refactoring. This one has been around for a while so I don't want to change it. If there's user feedback through, we could consider not showing it unless explicitly requested
