### ISSUE TITLE
The parent was already checked but yet it was included in the firing of the `onDidChangeCheckboxState`

### ISSUE THREAD

**Issue by TylerLeonhardt** [microsoft/vscode#183877]
Testing #183549

![Recording 2023-05-30 at 15 15 22](https://github.com/microsoft/vscode/assets/2644648/15eab6f8-bc92-43c2-b6bc-fe0e2e587cc6)

You can see the parent is checked, but when I check the last child, the `onDidChangeCheckboxState` contains 2 items, the item I checked and the parent.

The parent's state didn't change so I didn't expect it to be in the array.

**Comment by alexr00** [comment]
Will be fixed by https://github.com/microsoft/vscode/pull/184154
