### ISSUE TITLE
When `shell integration` is disabled, the env changes are still applied

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#183838]
Testing #182970

I'm guessing that's because `applyAtProcessCreation` is `true` by default, but it's a bit surprising when I have explicitly only provided `applyAtShellIntegration`

```
collection.replace('FOO', 'REPLACED', { applyAtShellIntegration: true });
collection.append('APPENDING', 'appending', { applyAtShellIntegration: true })
collection.prepend('PREPENDING', 'prepending', { applyAtShellIntegration: true });
```

![Screenshot 2023-05-30 at 11 57 00 AM](https://github.com/microsoft/vscode/assets/29464607/a064c585-8168-4c34-864c-11782130a2d3)

**Comment by meganrogge** [comment]
it works (does not get applied) if I explicitly also provide `applyAtProcessCreation: false`, but I wish we could skip that step - related #183831

**Comment by Tyriar** [comment]
This was brought up by @karrtikr at https://github.com/microsoft/vscode/issues/179476#issuecomment-1559742246, we'll finalize the exact behavior in the api sync
