### ISSUE TITLE
Prevent Welcome page from opening in the workspace when transitioning from Continue On

### ISSUE THREAD

**Issue by bhavyaus** [microsoft/vscode#183842]
Testing #183577

On opening in VS Code Desktop (after choosing to `Continue Working in Remote Repository on VS Code Desktop` from vscode.dev), prevent the Welcome page from opening and instead restore the editors. 

You can do prevent the welcome page from opening by setting the `configurationDefaults = {'workbench.startupEditor': 'none'}`

**Comment by joyceerhl** [comment]
> instead restore the editors

Tracked in https://github.com/microsoft/vscode/issues/183449, fyi @bpasero
