### ISSUE TITLE
`readonly include` is not applied 

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#183830]
Testing #183543

I added an entry `*terminal*ts` to my `Files: Readonly Include` setting. 

I can still edit `terminal.ts`. I also edited my `User` settings to include that entry. 

https://github.com/microsoft/vscode/assets/29464607/ea51ec2f-e0f9-490d-8f78-d69840dfcc41

**Comment by bpasero** [comment]
@meganrogge to clarify, the glob pattern needs to be written that it matches the workspace relative path if contained in the workspace or full absolute path otherwise.

**Comment by meganrogge** [comment]
Works 👍🏼

**Comment by spartanatreyu** [comment]
If anyone has come to this issue trying to figure out why their folders are still not readonly (for example: `node_modules`, `vendor`, etc)...

You'll need to surround it on both sides with a `/` then again with `**`.

So if you're trying to block every `node_modules` folder in your project, you would put in `**/node_modules/**`.
