### ISSUE TITLE
Startup performance regression restoring editors

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#183820]
We seem to be running in an increased startup time for editors:

![image](https://github.com/microsoft/vscode/assets/900690/6a49992d-bddc-45c6-aed4-6d26c657df34)

The first bump seems to be in these commits: https://github.com/microsoft/vscode/compare/2dfb838f49...1942c0eccc

**Comment by bpasero** [comment]
@jrieken my local bisect hints towards https://github.com/microsoft/vscode/commit/ddbac4875ca7bf06d114701169a2e9cd7e26dc30 which changed the interactive editor to be created `Eager`:

https://github.com/microsoft/vscode/blob/fa8eefda18bf099d82b58453f8fe5d3010196fa0/src/vs/workbench/contrib/interactiveEditor/browser/interactiveEditor.contribution.ts#L22

I see how this contribution is created first even before resolving a text file.

Within that contribution I believe the eager creation of the zone widget slows things down, but I have not drilled in further:

https://github.com/microsoft/vscode/blob/fa8eefda18bf099d82b58453f8fe5d3010196fa0/src/vs/workbench/contrib/interactiveEditor/browser/interactiveEditorController.ts#L121

There are also many services being instantiated, for example notebook editor service.

**Comment by jrieken** [comment]
Good find... I made the editor chat controller eager because notebooks dispose and create new editors upon scroll and controllers need to be eager to know if a session needs to be recreated....

Turns out that the creation of the controller takes longer than expected, mostly due to it creating its zone widget eagerly. I will make that idle and see how it goes

<img width="786" alt="Screenshot 2023-05-31 at 11 18 09" src="https://github.com/microsoft/vscode/assets/1794099/a6544afd-5acd-4007-aefd-e5eb53712eb3">

**Comment by jrieken** [comment]
Hm... my changes from yesterday don't seem to make a difference. Bot is still complaining


<img width="551" alt="Screenshot 2023-06-01 at 11 17 17" src="https://github.com/microsoft/vscode/assets/1794099/8b08150e-5a97-462c-8456-cfd7d5754ffd">

**Comment by jrieken** [comment]
Looking at windows numbers and the time it take to create the code editor, you nice see the regression and the effect of my fix... However, there seems to be another thing 🕵️ 

<img width="1451" alt="Screenshot 2023-06-01 at 12 38 15" src="https://github.com/microsoft/vscode/assets/1794099/2cf2c631-6a3d-4588-8107-fb38a41c0d5f">

**Comment by jrieken** [comment]
Pushed another PR that defers the creation of the IE widget until used (lazy, instead of idlevalue) so that we can make sure no unwanted idle-time creation causes this
