### ISSUE TITLE
Share provider doesn't receive selection

### ISSUE THREAD

**Issue by ulugbekna** [microsoft/vscode#183810]
Testing #183574

My extension's provider is not receiving the `selection` within the `ShareableItem` passed to its `provideShare` 

I think this's caused by this - https://github.com/microsoft/vscode/blob/ef372f4335d82525403b03d6b3ab9b61b2bb5db2/src/vs/workbench/contrib/share/browser/share.contribution.ts#L87

**Comment by aiday-mar** [comment]
The same is observed when I test.
