### ISSUE TITLE
The Learn More button of build-in NPM support for VS code extensions goes to a page that does not exist.

### ISSUE THREAD

**Issue by fuhan666** [microsoft/vscode#183889]
Does this issue occur when all extensions are disabled?: Yes/No
No, specify a build-in extension

- VS Code Version: 1.78.2
- OS Version: Windows_NT x64 10.0.19045

### This is a bug about the build-in extension of **NPM support for VS code**
Steps to Reproduce:

1. Make sure your TypeScript/JavaScript project folder has multiple lockfiles like `package-lock.json` and `pnpm-lock.yaml`.
2. Make sure your `@ext:vscode.npm` extension is the default setting.
3. Open `package.json`, mouse hover on one of any scripts, and click the "**Run Script**" button on the popup widget.
4. Then you will have a notifications window like this :
![Snipaste_2023-05-31_09-33-10](https://github.com/microsoft/vscode/assets/60378434/89194f61-ec3a-47e4-9509-9a24b90fcb82)
5. Click the "**Learn More**" button.
6. Will automatically open an URL of `https://nodejs.dev/learn/the-package-lock-json-file` which is "PAGE NOT FOUND".

Found the code at line 143 in `VSCODE/extensions/npm/src/task.ts`:
 ```TypeScript
window.showInformationMessage(multiplePMWarning, learnMore, neverShowAgain).then(result => {
switch (result) {
	case neverShowAgain: extensionContext.globalState.update(neverShowWarning, true); break;
	case learnMore: env.openExternal(Uri.parse('https://nodejs.dev/learn/the-package-lock-json-file'));
}
});
```

**Comment by gjsjohnmurray** [comment]
@meganrogge I think the associated PR has shipped, so this issue can be closed.
