### ISSUE TITLE
[Bug] Text jitters when using IME if the zoom level is 1

### ISSUE THREAD

**Issue by wenfangdu** [microsoft/vscode#183814]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.77.0-insider (Universal)
- OS Version: macOS 13

Steps to Reproduce:

1. Set `"window.zoomLevel": 1` (important, as `0` zoom level seems pretty stable).
2. Use "Pinyin - Simplified" IME.
3. Notice the text jitters a little bit when typing with IME.

https://github.com/microsoft/vscode/assets/28700378/84c7bcd8-c49a-402a-a6f8-c8ab7b694ac7

**Comment by wenfangdu** [comment]
@alexdima Alex, it's been a year, any progress on this?

**Comment by red-co** [comment]
Win11这只有一点抖动，win10直接字符重叠了，
只能退回到1.80.0以下的版本。

**Comment by red-co** [comment]
![image](https://github.com/user-attachments/assets/58d9c89e-25e0-4f88-b264-7ee980d78d72)

**Comment by red-co** [comment]
Character overlap occurs repeatedly in versions 80_93, but the current version 93 of win11 does not have this problem.

**Comment by aiday-mar** [comment]
The new "editor.experimentalEditContextEnabled" fixes this issue, because a div containing the text is no longer being made visible during composition. This issue will be closed.

**Comment by xiyaowong** [comment]
This new option disrupts extensions like vscodevim and vscode-neovim. These extensions register commands such as `type` and `replacePreviousChar`.

**Comment by wenfangdu** [comment]
> This new option disrupts extensions like vscodevim and vscode-neovim. These extensions register commands such as `type` and `replacePreviousChar`.

@aiday-mar Please take a look.

**Comment by aiday-mar** [comment]
Hi yes thank you for letting me know. We will have a look at this. The feature is experimental for now and has bugs/missing features. The idea is to adopt the EditContext and keep the existing functionality as is.
