### ISSUE TITLE
getaddrinfo EAI_AGAIN lukehoban.gallery.vsassets.io:443

### ISSUE THREAD

**Issue by brettlee672** [Microsoft/vscode#18389]
- VSCode Version: Code 1.8.0 (38746938a4ab94f2f57d9e1309c51fd6fb37553d, 2016-12-13T17:45:32.595Z)
- OS Version: Windows_NT ia32 6.3.9600
- Extensions:

|Extension|Author|Version|
|---|---|---|

---

Steps to Reproduce:

1.I click on extension icon  
2.Then i tried to install go plugin . It is giving me getaddrinfo EAI_AGAIN lukehoban.gallery.vsassets.io:443 error

**Comment by mjbvz** [comment]
It looks to me like the extension is trying to load a some sort of asset from a resource that cannot be resolved.

To do you this for other extensions or just the Go extension? If you are still seeing this, try opening the issue against the [Go extension](https://github.com/microsoft/vscode-go)

**Comment by a5066987** [comment]
Have you already solved this problem? I have the same problem, I cant install any extension.

**Comment by mdarif** [comment]
I got the same issue but realized later on, it was due to internet connection went on toss.

You may need to check your connectivity.
