### ISSUE TITLE
`markdown.copyFiles.destination` variables not working?

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#183851]
Testing #183682

Not sure what's happening, but none of the "document" variables work for me. Example

<img width="814" alt="image" src="https://github.com/microsoft/vscode/assets/323878/17f2003c-15b0-4ad0-abb6-12f2114d5ef8">

That is pasted as this

<img width="590" alt="image" src="https://github.com/microsoft/vscode/assets/323878/48de89e4-9196-4cfa-9c63-061d114389c3">

So it saw "images" but not the second component. All of the other "document" variables are ignored similarly

**Comment by mjbvz** [comment]
Thanks for testing. There's a bug when the variables are in the last part of the path (the file name). Will fix this but you can also test variables in other parts of the path, such as `images/${documentFileName}/`
