### ISSUE TITLE
`markdown.copyFiles.destination` doesn't escape markdown characters in path

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#183849]
Testing #183682

Set the value to `abc)/${fileName}`. This is a valid path, but the `)` does not get escaped in the markdown link.

**Comment by mjbvz** [comment]
Also happens without this setting if the file being pasted contains `(` or other special characters. In these cases, we should likely use the `[text](<link with special chars>)` link syntax instead

**Comment by roblourens** [comment]
Cool, didn't know you could do that
