### ISSUE TITLE
Debugger stops at eval:122 

### ISSUE THREAD

**Issue by guogaigai** [Microsoft/vscode#18384]
- VSCode Version: 1.8.1
- OS Version: ubuntu12.04

Steps to Reproduce:

1. Open a web app to the workspace 
2. Press F5 to debug ,it stops at eval:122  If I continue with , the debugging works

This phenomenon is accidental . I just attach the screenshot below , Does someone knows the reason ? 
Thanks

![eval](https://cloud.githubusercontent.com/assets/18524505/21834656/ccb577d6-d7f1-11e6-9678-be7b2e540305.png)

**Comment by roblourens** [comment]
That evaled script is throwing an exception, and you must have the button checked to break on exceptions, so this is expected.
