### ISSUE TITLE
Could `TreeItemCheckboxState` be a boolean?

### ISSUE THREAD

**Issue by TylerLeonhardt** [microsoft/vscode#183879]
Testing #183549

```
export enum TreeItemCheckboxState {
		/**
		 * Determines an item is unchecked
		 */
		Unchecked = 0,
		/**
		 * Determines an item is checked
		 */
		Checked = 1
	}
```

for quickpick we used:
https://github.com/microsoft/vscode/blob/c3c6a33390ba492934a72a69c552927af1820e11/src/vscode-dts/vscode.d.ts#L1752-L1763

You can't really use `picked` but would a boolean be ok here? Is there ever a 3rd option?

**Comment by alexr00** [comment]
@TylerLeonhardt we may decide to support the "mixed" state at some point:

- [ ] Parent
  - [x] Child 1
  - [ ] Child 2

In the above example, if we supported the "mixed" state then Parent would be "mixed" as it has both checked and unchecked children.
