### ISSUE TITLE
Doubleclick should take me to the test

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#183835]
Testing microsoft/vscode-python#21092

Here:

![image](https://github.com/microsoft/vscode-python/assets/900690/8c054d33-d803-4e02-8025-15cf691d4981)

**Comment by bpasero** [comment]
This works fine via double click but for example `Cmd+DownArrow` does not open on macOS. This works in other trees as standard gesture to open.

To make this easy to adopt for trees, I think we have a convention in custom trees, not sure if they are used here. @alexr00 do you remember?

**Comment by alexr00** [comment]
Yes, if you set the command of the tree item in extension provided trees to `vscode.open` or `vscode.diff` then we do some magic and respect the arguments to those commands as outlined at https://code.visualstudio.com/api/references/commands.
