### ISSUE TITLE
Notebook editor does not report dirty after EH restart when making edits

### ISSUE THREAD

**Issue by amunger** [microsoft/vscode#183854]
Testing #183534

1. create a new notebook and make an edit
2. switch profiles to restart the EH
3. save the file when prompted and provide a file name: `saved.ipynb`
The untitled-n.ipynb tab remains open, rather than opening saved.ipynb, 
:bug: The file is no longer marked dirty, even with futher edits and **can be closed without prompting to save**

**Comment by bpasero** [comment]
@rebornix can you maybe check from the notebook side?

**Comment by bpasero** [comment]
Somehow today I cannot reproduce an issue with insiders:

![Recording 2023-05-31 at 10 45 57](https://github.com/microsoft/vscode/assets/900690/5e3a8f3c-5b51-45e9-b88c-5da561c22ee7)

Please give me more detailed steps and see if you still find this.

**Comment by amunger** [comment]
@bpasero - the notebook extension is built-in so it's still available in an empty profile. The repro steps can even start with an empty profile -> 
1. run `Create: New Jupyter notebook` and make an edit to the first cell
2. switch profile to default and save as 1.ipynb when prompted
3. make an edit in the notebook
:bug: file is not dirty

**Comment by bpasero** [comment]
@amunger oh nice, sounds like an issue related to EH restart then, will update the title

**Comment by amunger** [comment]
It looks like the issue in the notebook scenario is that it's calling save directly on the workingCopy in the [OnWillStop handler](https://insiders.vscode.dev/github/microsoft/vscode/blob/main/src/vs/workbench/contrib/notebook/common/notebookEditorModel.ts#L67): In the untitled case, that will delegate to saveAs, which will dispose the untitled workingcopy, and since it's not handled at the editor level, it doesn't open a new editor with the resulting `StoredFileWorkingCopy`. The editor is left open with its underlying WorkingCopy disposed.

For non-built-in custom editors though, it seems like we should just close them if we don't know if they will be supported in the new profile. I don't see how we can expect a custom editor to support a scenario where its source extension isn't installed - is that even possible?

I went over the issue with @kieferrm and concluded that we can defer to next release since the previous stable version also didn't handle this scenario well.

**Comment by bpasero** [comment]
@amunger fyi I just created https://github.com/microsoft/vscode/issues/184142 which is a similar issue for custom editors.

Here for notebooks I suggest the following:
* if the EH restarts and still has the notebook extension for the opened notebooks, reconnect to the EH and allow to further make edits on the editor (I actually thought this was already implemented based on the work @rebornix did)
* if the EH restarts and there is no more extension for the notebook editor, turn the notebook readonly and inform the user somehow

Does that make sense?

**Comment by amunger** [comment]
The previous change just doesn't account for untitled notebooks, but I think I can fix that.

That makes sense, although I'm surprised that we would require all custom editors to handle this (asked about it in the other issue)
