### ISSUE TITLE
Go to file - allow to type folder name after file name for better narrowing of many results

### ISSUE THREAD

**Issue by normalser** [Microsoft/vscode#18381]
User typed 'types':

Current view:
![image](https://cloud.githubusercontent.com/assets/1723815/21982246/69a50c9e-dbb9-11e6-88a1-24b3f82ba261.png)

Notice how there are multiple files with the same name and then there is useful folder name after the file name to distinguish the files - but as soon as user starts typing folder name - hoping that it will filter the values - it returns empty result:

![image](https://cloud.githubusercontent.com/assets/1723815/21830794/43a29d86-d76d-11e6-84ba-285216fd7724.png)

It would be very helpful if `types comm` would return:
![image](https://cloud.githubusercontent.com/assets/1723815/21830855/bcd24616-d76d-11e6-8275-4d659b1d6899.png)

**Comment by dakaraphi** [comment]
I would like to be able to do something like
`folder name | file name`

And have it fuzzy match separately the full path and folder name

**Comment by bpasero** [comment]
![image](https://cloud.githubusercontent.com/assets/900690/21882599/75160f6c-d8ab-11e6-8b02-7534c51122da.png)

Yes, only that makes sense for me and that is how it works today.

**Comment by dakaraphi** [comment]
@bpasero It does not work that way for me.  Possibly the algorithm breaks on long paths?
![image](https://cloud.githubusercontent.com/assets/10656375/21892974/2b06c028-d8a7-11e6-9649-807e364b1022.png)

Exactly what would I type to filter only files that have the word 'copy' inside a directory path with the word 'copy'?

**Comment by bpasero** [comment]
I think this is a problem because "copy" matches on both the file name and the folder name.

**Comment by dakaraphi** [comment]
@bpasero 
If I type only 'utility' I get results like this.
![image](https://cloud.githubusercontent.com/assets/10656375/21895094/772c5366-d8af-11e6-8b64-a29d37caa300.png)

If I type 'planning utility' I get this
![image](https://cloud.githubusercontent.com/assets/10656375/21895124/913e7eb4-d8af-11e6-9044-4efb4138e1e8.png)

No matter the combination, I get back non intuitive results.  I want it to weight stronger on whole word matches and be able to separately match paths vs files, but don't seem to be able to do that.

**Comment by dakaraphi** [comment]
@bpasero I think what needs to be addressed here is more than just folder name.  Even for files only the results don't match intuitively.
I would expect 'async' here as contiguous letters to be matched higher in priority, but it is actually pages down.
<img width="595" alt="image" src="https://cloud.githubusercontent.com/assets/10656375/21999496/71eb8a3c-dc08-11e6-85fa-ad8b775e848e.png">

**Comment by dakaraphi** [comment]
This is still a pain point for large projects.  This is the type of functionality that would really be helpful to be able to enter in the file search field.

Using character like`|` to provide search context
`name` this would match on both path and file as it does today
`folder name | file name` this would match separately on path and file
`folder name |` this would match only folder names
`| file name` this would match only file names

This would give immense flexibility in being able to resolve files in large projects.

**Comment by bpasero** [comment]
I think the only logical separator to distinguish folder from file portion is the "`/`" on Linux and macOS and "`\`" on Windows. This already works today.

**Comment by dakaraphi** [comment]
Seems it would be good if there were some usage hints somewhere about `\` or `/`.
