### ISSUE TITLE
Text is not saved when file is renamed

### ISSUE THREAD

**Issue by DrGo** [Microsoft/vscode#18388]
- VSCode Version: Code 1.8.1 (ee428b0eead68bf0fb99ab5fdc4439be227b6281, 2016-12-19T14:42:49.304Z)
- OS Version: Darwin x64 16.3.0
- Extensions:

|Extension|Author|Version|
|---|---|---|
|aurelia|AureliaEffect|0.2.0|
|vscode-pandoc|DougFinke|0.0.8|
|Aurelia|behzad88|1.2.1|
|path-intellisense|christian-kohler|1.2.0|
|tslint|eg2|0.7.1|
|Go|lukehoban|0.6.52|
|debugger-for-chrome|msjsdiag|2.4.2|
|todotasks|sandy081|0.4.0|
|code-spell-checker|streetsidesoftware|0.13.3|

---

Steps to Reproduce:

1. open a new window and type in some text.
2. save file eg as "test" (no extension).
3. add some more text.
4. click on file in the Explorer window and change file name to eg "test.md"

Expected:
- text entered in step 3 is saved OR a prompted to save changes.

what happened:
- text entered in step 3 is not saved without prompt or warning.

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/11997
