### ISSUE TITLE
Share provider's document selector can't select by language

### ISSUE THREAD

**Issue by ulugbekna** [microsoft/vscode#183809]
Testing #183574

`registerShareProvider` takes a `DocumentSelector` but doesn't respect the selector's `language`. 

I created an extension which uses Share Provider API, but its share contribution wasn't being invoked. It seems the language isn't being passed - see 3rd arg being an empty string [here](https://github.com/microsoft/vscode/blob/ef372f4335d82525403b03d6b3ab9b61b2bb5db2/src/vs/workbench/contrib/share/browser/shareService.ts#L51).

```
const docSelector : vscode.DocumentSelector =  { scheme: 'file', language: 'typescript' };
```

**Comment by aiday-mar** [comment]
I observe the same, using: `{scheme: 'file'}` registers the share provider, however as soon as I add a language, this is no longer the case
