### ISSUE TITLE
Hovering the checkbox and then the label has overlapping tooltips

### ISSUE THREAD

**Issue by TylerLeonhardt** [microsoft/vscode#183878]
Testing #183549

![image](https://github.com/microsoft/vscode/assets/2644648/a7e30382-c613-4914-ac9a-9377cc473ab9)

I hovered over the checkbox, which rendered `Checked` then I hovered over the tree item label, and it rendered underneath.

**Comment by alexr00** [comment]
This will be fixed by adopting the custom hover: https://github.com/microsoft/vscode/issues/183918
