### ISSUE TITLE
Running process in terminal not terminated when closing window

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode#18385]
- VSCode Version: Code 1.8.1 (ee428b0eead68bf0fb99ab5fdc4439be227b6281, 2016-12-19T14:42:49.304Z)
- OS Version: Darwin x64 15.6.0
- Extensions:

|Extension|Author|Version|
|---|---|---|
|vscode-eslint|dbaeumer|1.2.2|
|tslint|eg2|0.8.1|
|debugger-for-chrome|msjsdiag|2.4.2|
|vetur|octref|0.2.0|
|language-stylus|sysoev|1.6.0|
|vim|vscodevim|0.4.10|

---

Steps to Reproduce:

1. I was running a webpack dev server using this template: https://github.com/vuejs-templates/webpack#usage
2. `npm run dev` to start a dev server
3. `Cmd+Shift+W` to close window
4. Reopen workspace, the previous process is still there

![image](https://cloud.githubusercontent.com/assets/4033249/21835006/985272f2-d7f4-11e6-8d6b-a2aedeaa242b.png)

@Tyriar

**Comment by Tyriar** [comment]
Cannot reproduce on Ubuntu, is it 100% reproducible?

**Comment by octref** [comment]
Oops sorry. In my project I was using `webpack-dashboard` and it seems to be the cause.

When using this template ( https://github.com/vuejs-templates/webpack#usage), if you run an additional `npm i -D webpack-dashboard`, and run dev server like this:

```
  "scripts": {
    "dev": "webpack-dashboard -m -- node build/dev-server.js"
  }
```

Then quitting VSCode does not end the process. I don't know if it's VSCode's fault though.

**Comment by Tyriar** [comment]
I suspect it's related to this:

> After the initial release, it was decided that running a separate process and communicating via sockets would be more efficient and solves a lot of problems with stdout.

https://github.com/FormidableLabs/webpack-dashboard/blob/3158e2f113fabab1de81933a6b64650b0ce622ac/docs/getting-started.md#packagejson-recommended
