### ISSUE TITLE
tunnel service runs after removing the application on macOS

### ISSUE THREAD

**Issue by deepak1556** [microsoft/vscode#183824]
Testing #183700

* After starting the tunnel service, move the application to trash (there is no uninstall process on macOS)
* Verify `code-insiders tunnel status` results in `command not found: code-insiders`
* Check activity monitor and see `code-insiders-tunnel` is running out of `~/.Trash/Visual Studio Code - Insiders.app/Contents/Resources/app/bin/code-tunnel-insiders`

**Comment by connor4312** [comment]
I can't repro this -- for me the tunnel successfully notices the application is deleted and shuts down after a few seconds

<img width="662" alt="image" src="https://github.com/microsoft/vscode/assets/2230985/af61bbce-2c87-4eee-b292-a35876a0bc37">

@deepak1556 if you can still reproduce this, can you please share the contents of `~/.vscode-insiders/cli/tunnel-service.log` after doing it?
