### ISSUE TITLE
Filename reported by API is incorrect after file rename with case-sensitive change

### ISSUE THREAD

**Issue by smcenlly** [microsoft/vscode#183886]
Does this issue occur when all extensions are disabled?: No - specific to extension API

- VS Code Version: 1.78.2 (Universal), 1.79.0-insider (Universal)
- OS Version: Darwin arm64 22.4.0, Darwin arm64 22.5.0

Steps to Reproduce:

1. `git clone https://github.com/smcenlly/vscode-rename-bug.git`
2. after cloning repo, open project and run `npm install`
3. Start extension sample with `Debug: Start Debugging`
4. In `Extension Development Host`, open `sample` folder.
5. Open `filename.js`
6. Run command, `Rename Bug`
7. Should get output with correct (current) filename:

<img width="574" alt="image" src="https://github.com/microsoft/vscode/assets/2074089/068fd395-5a13-4c73-9a98-d0d14d257ea8">

8. Rename the file to `Filename.js` (note case sensitive change only).
9. Run command, `Rename Bug`
10. Will not get incorrect filename:

<img width="659" alt="image" src="https://github.com/microsoft/vscode/assets/2074089/5542c2b0-1a4e-45c3-a239-59cc51a89e39">

11. Reload the editor with `Developer: Reload Window`
12. Run the command again, will still get incorrect filename.
13. Close and re-open the file, will still get incorrect filename.

---

At this point, the only way to get the API to start reporting the correct name again is to close the file and restart the editor.

---

Here is the code for the extension (also in repo provided):

```typescript
import * as vscode from 'vscode';

export function activate(context: vscode.ExtensionContext) {
	let disposable = vscode.commands.registerCommand('rename-bug.command', () => {
		vscode.window.visibleTextEditors.forEach(async editor => {
			vscode.window.showInformationMessage(editor.document.uri.fsPath);
		});		
	});

	context.subscriptions.push(disposable);
}

export function deactivate() {}
```

**Comment by bpasero** [comment]
The path of a document cannot change on case insensitive file systems. This is a design limitation we have to live with.

**Comment by smcenlly** [comment]
I strongly disagree that this is by design when the behavior is inconsistent. If the file paths were always lowercase for instance, I can understand how this could be by design. 

I understand that the path of the document cannot change on case insensitive file systems but the reality is that as development tool makers (ourselves included, I work on Wallaby.js products), we need to support case sensitive file systems.

In this case, our tools broke because VS Code API is providing misleading (I assume cached) information through the API.

Could you please reconsider fixing this bug? If you're open to a pull request, I'm happy to investigate and fix myself.

**Comment by bpasero** [comment]
If in your tool you need the actual casing as it is on disk you will have to use calls such as `fs.realpath.native` or do a `readdir` call on the parent and find the name. You cannot rely on the `document.uri`, we give no guarantee that the casing is as it is on disk. In fact, the casing will be as it was when the editor opened initially.

The document `URI` is immutable in our world, renaming a file on disk we preserve the documents so that everything associated with it (such as undo / redo) still continues to work. We do not want to close and reopen the editor in that case.

Sorry that I do not have a better answer.

**Comment by smcenlly** [comment]
OK, thanks. We'll probably have to go with something like the `reader` option.

I do really appreciate your fast response. Thanks!
