### ISSUE TITLE
chore(performance test): Add performance test criteria

### ISSUE THREAD

**Issue by unional** [Microsoft/vscode#18382]
- VSCode Version: 1.8.1

I love vscode and using it every day.
It works better for me compare to all other editors and it is the speediest of the bunch.

As vscode continues to grow, it may be a good time to start investing in adding some performance criteria so that we can ensure the IDE performance does not degrade as more features are added.

Criteria such as:

- without extensions
  - Starts within 3 seconds
  - Command Palette shows within 100 ms
 
I'm not performance experts and will leave it at your good hands in defining more criteria.

If such criteria already exist, that's great. 🌷

**Comment by jrieken** [comment]
We have `--performance` which shows good stats about startup, loading the main JS files, and interpreting that. Also, we send some telemetry data about startup performance to get an idea about average performance in relation to other factors like OS, number of core etc. 

All that data is available from 'F1 > Developer: Startup Performance' but I agree that we should make that data more accessible and comparable. Also, in addition to startup perf we should also measure things like open file, render editor etc

**Comment by bgse** [comment]
@jrieken I'd say rendering performance should be pretty high on the priority list.

Now this is a gut feeling backed only by some rudimentary testing with top, but for example I have the impression that scrolling in files seems to put somewhat heavy load on the cpu, and thus draining laptop batteries quite fast.

**Comment by jrieken** [comment]
We have telemetry on performance and reports on that. Also we have enabled profiling for our users. We know what the ideal startup time is from an empty electron app and have a continuous effort to get faster.
