### ISSUE TITLE
`Open Workspace in New Window` icon in the remote explorer is not keyboard accessible via tabbing.

### ISSUE THREAD

**Issue by bhavyaus** [microsoft/vscode#183843]
Testing #183578

Tested on mac. 
1. Open Remote Explorer with some remote extensions installed. 
2. Select an entry in the tree and try to tab to the `Open Workspace in New Window` button. However, `Open Workspace in Current Window` is keyboard accessible.

**Comment by joyceerhl** [comment]
You can use the right arrow key to move focus to additional inline actions.
