### ISSUE TITLE
Test: Notebooks -- Format on Cell Execution

### ISSUE THREAD

**Issue by Yoyokrazy** [microsoft/vscode#183821]
Refs: [#7058](https://github.com/microsoft/vscode-jupyter/issues/7058)

- [x] macOS @eleanorjboyd 
- [x] linux @andreamah 
- [x] windows @devinvalenciano 

Complexity: 2

Authors: @Yoyokrazy 

---

## Summary:

Notebooks now can format cells upon cell execution. This will trigger using run cell, run all, run above/below, and combined kernel+run commands.

## Steps to Test:

- Create a new or open a pre-existing notebook
  - Create a code cell(s) with some formatting issues (extra spaces in variable declaration, tons of empty lines, etc)
- Go to Settings (UI) and search for `notebook.formatOnCellExecution`, enable this setting
- Make sure you have a formatter available for Python (I use Black)
- Try using run cell, run all, run above, or run below -- ensure formatting is correct

## Things to check
- When running cells, they format as expected
- The cell(s) executed as expected

**Comment by eleanorjboyd** [comment]
looks great- tested both on an unsaved notebook and a saved / named notebook. Also control-Z worked to undo all the changes made by the formatter.
