### ISSUE TITLE
collection applied twice for second terminal

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#183836]
Testing #182970

In my extension's `activate` function, I have:

```ts
vscode.window.createTerminal({
	name: `Ext Terminal tranisent #${NEXT_TERM_ID++}`,
	isTransient: true
} as any);
vscode.window.createTerminal({
	name: `Ext Terminal tranisent #${NEXT_TERM_ID++}`,
	isTransient: true,
	shellPath: 'fish'
} as any);
const collection = context.environmentVariableCollection;
collection.replace('FOO', 'REPLACED', { applyAtShellIntegration: true });
collection.append('APPENDING', 'appending', { applyAtShellIntegration: true })
collection.prepend('PREPENDING', 'prepending', { applyAtShellIntegration: true });
```

When the extension activates, I log the `env` in each terminal. In the first, `zsh`, the mutations are applied right next to each-other in order

![Screenshot 2023-05-30 at 11 53 15 AM](https://github.com/microsoft/vscode/assets/29464607/712f29b7-949d-429b-8c3e-fbad8c6ea685)

In the second, `fish`, I see that they're applied in a different order and the appending / prepending happens twice. I'm not sure if this is expected. 
![Screenshot 2023-05-30 at 11 52 55 AM](https://github.com/microsoft/vscode/assets/29464607/cbe7fb35-f1fe-4261-a078-97031375b091)
![Screenshot 2023-05-30 at 11 51 56 AM](https://github.com/microsoft/vscode/assets/29464607/035ff744-c55a-4444-bcb7-1f7f499b0ce7)

**Comment by meganrogge** [comment]
does not occur when I set process creation to false

**Comment by Tyriar** [comment]
Will bring up in API sync https://github.com/microsoft/vscode/issues/179476#issuecomment-1559742246
