### ISSUE TITLE
I thought spacebar would toggle the checkbox but it doesn't with VoiceOver

### ISSUE THREAD

**Issue by TylerLeonhardt** [microsoft/vscode#183881]
Testing #183549

![Recording 2023-05-30 at 15 25 56](https://github.com/microsoft/vscode/assets/2644648/a9a0045b-6f68-41fe-ac07-50281bd3bf06)

Is this typical for VoiceOver? cc @meganrogge @isidorn

**Comment by meganrogge** [comment]
According to VO docs, you have to hold down the VO key(s)+ spacebar

**Comment by TylerLeonhardt** [comment]
Gotcha. This is good then
