### ISSUE TITLE
tunnel service repeatedly prompts for keychain access

### ISSUE THREAD

**Issue by deepak1556** [microsoft/vscode#183822]
Testing #183700

* Download Insiders zip from https://code.visualstudio.com/insiders and move it to /Applications
* Ensure the following,
```
code-insiders tunnel status           
no tunnel process is currently running
```
* Run `code-insiders tunnel service install` and see the following prompt popup repeatedly when just clicking `Allow`

<img width="428" alt="Screenshot 2023-05-31 at 0 37 27" src="https://github.com/microsoft/vscode/assets/964386/27abd92e-4872-4e36-b849-74dae4312648">

**Comment by connor4312** [comment]
"Always Allow" is the way to go here. The CLI will need repeated keychain access to check for, read, and store access/refresh tokens over time.

**Comment by deepak1556** [comment]
What about creating a custom keychain configured for the tunnel service to avoid repeated prompts ? If the service process owns the keychain it should be able to perform operations in it once it has proven the initial identity to the user
