### ISSUE TITLE
Object literal may only specify known properties, and 'indentSize' does not exist in type 'FormatCodeOptions'.

### ISSUE THREAD

**Issue by basarat** [Microsoft/vscode#18393]
- VSCode Version: latest

Trying to do a monaco build I get this error: 

```
/Users/syedb/REPOS/monaco/vscode/build/monaco/api.ts:220 Type '{ indentSize: number; tabSize: number; newLineCharacter: string; convertTabsToSpaces: boolean; in...' is not assignable to type 'FormatCodeOptions'.
  Object literal may only specify known properties, and 'indentSize' does not exist in type 'FormatCodeOptions'.
```

Think the case is changed in typescript :rose:

**Comment by basarat** [comment]
This is the code : https://github.com/Microsoft/vscode/blob/b2d2a79da81853bff6e1c60876c9cee8582f9e61/build/monaco/api.ts#L218-L237 

Tagging in @alexandrudima cause he's witnessed it before ? https://github.com/Microsoft/TypeScript/issues/11852#issuecomment-256500564

**Comment by alexandrudima** [comment]
This might be caused by the new TS version

**Comment by mjbvz** [comment]
Looks like monaco is still using TS 2.0.3. I'll look into upgrading it to 2.1.4 as well which should fix this error.
