### ISSUE TITLE
can't install extensions

### ISSUE THREAD

**Issue by lock22** [Microsoft/vscode#18395]
- VSCode Version: 1.8.1
- OS Version: Windows 10, 10.0.14393 Build 14393

I was modifying the color of a theme then decided to reinstall that theme now I can't reinstall. it says "Installing" but nothing happened. I've tried reinstall vscode twice.. Once, with Programs and Features then with Revo uninstaller and removed registry etc.

what should i do?

**Comment by mjbvz** [comment]
A few questions to help investigate:

* Does this happen for all extensions or just the one? 
* Can you install another extension that you have not installed before?
* In your home directory, there's a hidden `.vscode` file. Try opening this and going to `extensions`. Do you see the extension listed in there?

**Comment by lock22** [comment]
- Not all, happened to a few. Mainly setting sync that I was trying to get.
- yes. I didn't try many though. Just a few
- nope and I've tried emptied it and delete it after reinstall.

Before going to bed I went on my Mac and backed up my extensions to Google drive. Back to Windows and pasted them in extensions folder and that was working for me. I guess I can live with that.

**Comment by fiveisprime** [comment]
I'm seeing the same thing. I saw this on 1.8.x and now on 1.9.0. No extensions
will install and out of date extensions won't update. They just get stuck with
a disabled "Installing".

- Yes, all extensions
- No
- No

**Comment by sandy081** [comment]
@fiveisprime Strange, its totally a bummer to see it happening for all extensions. Very sorry for that.  Are you hitting this consistently all the time. Say restarting is also not fixing it?

**Comment by fiveisprime** [comment]
It's consistent and persists between restarts (of both machine and VS Code). This
has been going on for a couple of weeks, but I haven't been using VS Code full
time so it wasn't a huge deal. Now I'm hoping to make the switch - the latest
updates are *incredibly* compelling.

I should also note that VS Code wouldn't update itself; I had to manually go get
the new installer and install over it. It's almost as if Code doesn't have
permission to make connections or something.

I'm up for trying anything, just let me know :+1:

**Comment by sandy081** [comment]
@fiveisprime Happy to hear that you want to switch to VS Code full time. We would be happy to hear your feedback.

Which platform are you on? On linux, auto update feature is not yet there.. we are working on it. 

Regarding installing extensions are you behind some proxy settings?

**Comment by fiveisprime** [comment]
@sandy081 This only happens on my Windows machine (Windows 10 - surface book); I
also use a Mac and VSCode extensions and VSCode updates install perfectly fine.

The problem occurs both on the Microsoft Corp network and my home network so I'm
not sure it's a proxy issue - I was able to install extensions a month or two ago
with all of the same configuration. It really just seems like VSCode can't make
any kind of outbound connections if that makes any sense.

I've also uninstalled, restarted, reinstalled to see if that helps with no luck.

Is there a way to see an error log for VSCode? Maybe there is some kind of tip in
the logs.

**Comment by sandy081** [comment]
@joaomoreno Does it ring any bells for you?

**Comment by joaomoreno** [comment]
@fiveisprime Seems like a proxy issue. #18103

**Comment by fiveisprime** [comment]
I'm still not convince that it's a proxy issue. I ran the proxy test and saw no
errors - besides, all of this worked last month. I also tried uninstalling code
and removing all of the configuration files, which didn't help (but I did get
some icons back)..

I tried toggling the tools and noticed this error when attempting to install an
extension

```
shell.ts:437 EPERM: operation not permitted, mkdir 'C:\Program Files (x86)\Microsoft VS Code\null'

Error: EPERM: operation not permitted, mkdir 'C:\Program Files (x86)\Microsoft VS Code\null'
    at Error (native): Error: EPERM: operation not permitted, mkdir 'C:\Program Files (x86)\Microsoft VS Code\null'

Error: EPERM: operation not permitted, mkdir 'C:\Program Files (x86)\Microsoft VS Code\null'
    at Error (native)
    at Timeout._onTimeout (C:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\code\electron-main\main.js:5:8066)
    at tryOnTimeout (timers.js:232:11)
    at Timer.listOnTimeout (timers.js:202:5)e.onUnexpectedError @ shell.ts:437(anonymous function) @ shell.ts:389e.onUnexpectedError @ errors.ts:68o @ errors.ts:88(anonymous function) @ window.ts:232emitTwo @ events.js:106emit @ events.js:191
```

**Comment by joaomoreno** [comment]
cc @sandy081

**Comment by sandy081** [comment]
I am not sure why and where the above error is coming from. We do not install extensions under the folder `C:\Program Files (x86)\Microsoft VS Code\null` unless user opts to install there.  @joaomoreno Are you aware of any code where we create things in the above folder?

**Comment by joaomoreno** [comment]
@fiveisprime Can you check whether that `null` issue occurs on both your machines?

**Comment by fiveisprime** [comment]
@joaomoreno Confirmed that it only happens on my Windows machine.

**Comment by fiveisprime** [comment]
Solved.

Something that I've installed along the way created a `TEMP` environment
variable with the value of `null`. After removing that, my problems went away.

**Comment by joaomoreno** [comment]
Closing as per @fiveisprime discovery

**Comment by SuperRooo** [comment]
Hi everyone, I get this errors when searching for Search Extensions to Install.Help me to solve this  issue.

Error XHR failed:

Please find error  message below,
https://drive.google.com/open?id=0B0YfV0dly2iBQU1EQXFnanRHLXc

**Comment by pgriscti** [comment]
@SuperRooo 

- Find the extension in VSCode, and click on its name. 
- This should open the link in the market place, for example 
https://marketplace.visualstudio.com/items?itemName=msjsdiag.debugger-for-chrome
- Download the .VSIX file, and save it to your hard drive
- Back in VSCode, in the extensions page, click on ... (more), and select "Install from VSIX" 
- Select your saved file.
