### ISSUE TITLE
Test explorer: test-level causes a layout shift

### ISSUE THREAD

**Issue by pavelfeldman** [microsoft/vscode#183993]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.78, 1.79-insiders
- OS Version: macOS (all)

Steps to Reproduce:

1. Pick a project that has nested test items (multiple tests in a file or in a test group)
2. Start watching the last test item in the list of tests

Expected: that item is watched
Actual: first item in the list is watched

//cc @connor4312

**Comment by connor4312** [comment]
I'm having some trouble reproducing this, are there additional steps needed?

https://github.com/microsoft/vscode/assets/2230985/4922ad92-3d9b-48c3-9cf6-48b828db61ea

**Comment by pavelfeldman** [comment]
@connor4312 did you have a chance to verify this issue?

**Comment by connor4312** [comment]
I recorded my attempt to do so in https://github.com/microsoft/vscode/issues/183993#issuecomment-1622543855. Am I doing something differently than you are / do you still repro it? If so, a quick screen recording of what you see may be helpful 🙂 

https://gifcap.dev is useful

**Comment by pavelfeldman** [comment]
> I recorded my attempt to do so in https://github.com/microsoft/vscode/issues/183993#issuecomment-1622543855. Am I doing something differently than you are / do you still repro it? If so, a quick screen recording of what you see may be helpful 🙂

Did you try reproducing using the original steps (i.e. needs to be the last test item in the group of several, as in the steps to repro).

**Comment by pavelfeldman** [comment]
![Recording 2023-07-17 at 15 02 37](https://github.com/microsoft/vscode/assets/883973/3f0729af-d424-4555-80ad-608dd64ea6a2)

**Comment by connor4312** [comment]
That looks like the same as what I was getting. We automatically sort the "watched" test to the top when it enters that mode to make it visible to the user if the list of tests is long. But maybe we should only do that at a top level, what do you think?

**Comment by pavelfeldman** [comment]
Oh, the UX threw me off, I now see what you mean. There is a golden rule of the UX which is "Location of the toggle button should not change upon toggling". I.e for toggles you shoild be able to enfage / disengage w/o moving the mouse. You can have a separare (optional) wonodw of Watches (much like breakpoints) if you want to ease the watch management.

It is still my #1 complaint that when I start the tests entire tree of tests shift. I'd reserve the space for progress beforehand and lose these 24px just to make sure controls don't move under my mouse when I start a test from the tree item toolbar.
