### ISSUE TITLE
Build task not available when pressing cmd+shift+B immediately after window opens

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#183989]
Maybe related to https://github.com/microsoft/vscode/issues/173184

- Quit vscode
- Open vscode
- When the window for the vscode repo opens, immediately press cmd+shift+B. This is a multi-root workspace with vscode and one other repo, if it mattters
- On the first try, I get this

<img width="636" alt="image" src="https://github.com/microsoft/vscode/assets/323878/03b9110c-7f60-4c57-9ad3-09d900e1659b">

- On the second try, I get this, where the primary "VS Code - Build". If I run a task, then press cmd+shift+B again, that build task will then show up
<img width="628" alt="image" src="https://github.com/microsoft/vscode/assets/323878/e9c6bced-d821-4799-a672-8e36d48aacda">

This is what I see when I wait a bit after starting vscode before pressing cmd+shift+B for the first time, all tasks are available

<img width="634" alt="image" src="https://github.com/microsoft/vscode/assets/323878/130a341c-7338-4846-ac37-c0f47592cfdc">

What I wish would happen is that it would just run the "VS Code - Build" task automatically, but that's a different issue

**Comment by meganrogge** [comment]
@roblourens if you set `"runOptions": {"runOn": "folderOpen"},`, it will happen automatically

**Comment by meganrogge** [comment]
I can repro if I set the above, reload the window, `cmd+shift+b` and in the logs I see `Workspace folder was undefined
`

**Comment by meganrogge** [comment]
@roblourens does your other repo have a default build task as well?

**Comment by roblourens** [comment]
Yes it also has a default build task

**Comment by meganrogge** [comment]
That's the issue. Since there are several, we don't know which one you want to run. Thus the quick pick

**Comment by roblourens** [comment]
There are two, but you're showing me like 15 tasks. But that's not the real problem in this issue, the problem is the first two screenshots where it doesn't show up at all.

**Comment by meganrogge** [comment]
That case occurs when it takes more than 200 ms to get the task quick pick entries. https://github.com/microsoft/vscode/blob/2959f41a1a529fc31e12cc6a508493a45b014d77/src/vs/workbench/contrib/tasks/browser/abstractTaskService.ts#L2647

**Comment by roblourens** [comment]
I messed with the code to force that call to time out, and when that happens, I see the quick pick not show up at all

**Comment by weartist** [comment]
Is it possible to increase the waiting time to get entries somewhat?

**Comment by joaomoreno** [comment]
Very consistent repro for me, not timing dependent:

1. Start VS Code in `vscode`
2. <kbd>Cmd Shift B</kbd> to start default build tasks. Wait for all compile jobs to finish.
3. Reload workbench
4. Press <kbd>Cmd Shift B</kbd> once again.

🐛 VS Code no longer knows what's the default build task.

**Comment by joaomoreno** [comment]
Something else I notice after reloading, the ✔️ check mark of a successful build state is gone and the 🛠️ icon is shown instead:

![image](https://github.com/microsoft/vscode/assets/22350/7f643cf9-4a23-4128-b900-04abed57743e)

**Comment by meganrogge** [comment]
here's what I'm seeing - I'll keep trying to repro 
https://github.com/microsoft/vscode/assets/29464607/108e95b5-92ab-43e4-9053-6bdb156f0866

**Comment by joaomoreno** [comment]
Yes, the result of step 4 is:

![image](https://github.com/microsoft/vscode/assets/22350/92c013f6-c3cb-4636-9eea-03f28b93c198)

**Comment by meganrogge** [comment]
can repro when I do this 

![Screenshot 2023-06-21 at 1 48 33 PM](https://github.com/microsoft/vscode/assets/29464607/88c23e27-6213-461c-b611-e6b06e7e0e15)

![Screenshot 2023-06-21 at 1 48 10 PM](https://github.com/microsoft/vscode/assets/29464607/b916a621-6961-4eb7-99fa-1d9fce8b620c)

**Comment by meganrogge** [comment]
one of the ways this happens (by design) is when there are more than 1 default task

![Screenshot 2023-06-21 at 1 50 13 PM](https://github.com/microsoft/vscode/assets/29464607/2d30f59f-8dfb-4f98-b6bf-3f5cb1a5a4c0)

**Comment by meganrogge** [comment]
But for your case, if there is, in fact, only one, what could be happening is because of task reconnection, `taskGroupTasks.length > 0` already here, so it's not going in to this condition like it used to

https://github.com/microsoft/vscode/blob/b8d5deab6e48a7a92f08b66c19739e7c5a958c76/src/vs/workbench/contrib/tasks/browser/abstractTaskService.ts#L3001-L3005

**Comment by meganrogge** [comment]
`taskGroupTasks` has length 0 despite entering line 3003

![Screenshot 2023-06-21 at 2 01 43 PM](https://github.com/microsoft/vscode/assets/29464607/69c2e8c0-9c31-49cf-8710-ff0a57ceed28)

**Comment by meganrogge** [comment]
Nice, finally can repro

![Screenshot 2023-06-21 at 2 10 22 PM](https://github.com/microsoft/vscode/assets/29464607/7e51e3e6-5e01-45b2-80d4-0f5b22ae5044)

**Comment by meganrogge** [comment]
Ok - here's the issue - when the build command is triggered before the default build task has been reconnected to, that request is processed eventually after the tasks have been reconnected to. Since it knows the default build tasks are already taken (running), it presents a quick pick with multiple options for what you might want to run instead.

![Screenshot 2023-06-21 at 2 14 47 PM](https://github.com/microsoft/vscode/assets/29464607/7a2e1432-11b3-4dff-ace8-731652c690c3)
![Screenshot 2023-06-21 at 2 15 50 PM](https://github.com/microsoft/vscode/assets/29464607/4829057e-f135-44a8-841f-5da0bc036bd2)
![Screenshot 2023-06-21 at 2 17 29 PM](https://github.com/microsoft/vscode/assets/29464607/7b14677c-aa06-4d9f-9599-ec127a803488)

**Comment by roblourens** [comment]
I have this set, dunno if that's part of it `"task.experimental.reconnection": false,`

**Comment by meganrogge** [comment]
maybe related https://github.com/microsoft/vscode/issues/179684

**Comment by meganrogge** [comment]
yep, pretty sure this is related - when I reproduced, the workspace task length was 0 

/duplicate #179684

reopen if you hit it again

**Comment by meganrogge** [comment]
> Very consistent repro for me, not timing dependent:
> 
> 1. Start VS Code in `vscode`
> 2. Cmd Shift B to start default build tasks. Wait for all compile jobs to finish.
> 3. Reload workbench
> 4. Press Cmd Shift B once again.
> 
> 🐛 VS Code no longer knows what's the default build task.

This does not reproduce for me.
