### ISSUE TITLE
Regression: extension gets activated in both web worker extension host and remote extension host

### ISSUE THREAD

**Issue by jeanp413** [microsoft/vscode#183901]
- VS Code Version: from sources

Steps to Reproduce:

1. Inline a web extension in `builtinExtensionsScannerService.ts` that can run in web and remote, e.g. git-base
2. Run vscode from sources
3. :bug: extension gets activated in both extension host, check extension host logs

Code pointer https://github.com/microsoft/vscode/blob/fa8eefda18bf099d82b58453f8fe5d3010196fa0/src/vs/workbench/services/extensions/browser/extensionService.ts#L246-L254

cc @alexdima

**Comment by connor4312** [comment]
Potentially related: https://github.com/microsoft/vscode/issues/183921

**Comment by jeanp413** [comment]
The linked issue is not related as it's reported using stable version. 

This regression is from the work on the remote resolvers api https://github.com/microsoft/vscode/pull/180263, so it would be good to fix it before releasing version 1.79

**Comment by sandy081** [comment]
Reopening this because it is not merged into release branch yet.

**Comment by TylerLeonhardt** [comment]
This is the related bug that I think @connor4312 meant
https://github.com/microsoft/vscode/issues/183754

**Comment by jeanp413** [comment]
@alexdima  yep it's fixed :+1:
