### ISSUE TITLE
Put options in reverse order in context menu when context menu is above mouse

### ISSUE THREAD

**Issue by OscarNOW** [microsoft/vscode#183990]
Right now, when you right click and the menu appears below the mouse and when you right click and the menu appears above the mouse, the options are from top to bottom in the same order.
<img width="229" alt="image" src="https://github.com/microsoft/vscode/assets/56079903/6db9cb13-7f9a-4688-8d80-acd9cc3bacf0">
(mouse is above menu)

<img width="232" alt="image" src="https://github.com/microsoft/vscode/assets/56079903/38e9c26c-32d6-4e6b-8677-ad161727fd9d">
(mouse is below menu)

I think it makes more sense to flip the options when the context menu appears above the mouse. So in this case in the second screenshot, format appears on top and Decompress here appears on the bottom. I think this makes more sense, because the most useful options are (when the moues is above the menu) on top and closest to the mouse. So when the menu appears above the mouse, the most useful options are closest to the mouse.

(maybe related): #109482

**Comment by sbatten** [comment]
Native OS context menus do not do such behavior so I don't think we will tackle this one. Thanks for the suggestion though
