### ISSUE TITLE
Add command "Close without saving"

### ISSUE THREAD

**Issue by josharian** [microsoft/vscode#183999]
I'd like a command like `workbench.action.closeActiveEditorWithoutSaving` that will abandon any changes to the open editor and close it.

It is possible to do this now by invoking `workbench.action.closeActiveEditor` and then interacting with the OS-level save dialogue. However, as evidenced by several issues in this repository, many people do not know how to interact with that dialogue using only keys. I suspect they would like to be able to create custom keybindings for it.

More importantly for me, I use a voice control system ([Talon](http://talonvoice.com)) to deal with RSI issues, and I would like to create a command to do this. With the current setup, I need to add in a sleep to give time for the OS dialogue to come up and then simulate a keypress, which is inherently fragile. I would rather be able to describe precisely my intent. This is, for me, an accessibility feature request.

Thank you.

**Comment by bpasero** [comment]
The command exists: `workbench.action.revertAndCloseActiveEditor`
