### ISSUE TITLE
Debug toolbar draggable in the 4 edges of the VS Code screen.

### ISSUE THREAD

**Issue by FeliceGeracitano** [Microsoft/vscode#18399]
Feature Request

The debug toolbar that appear when the a process is running, often (in my opinion) is in the wrong place and cover tabs/refresh buttons/console buttons. 
I'd like to drag this toolbar in a custom edge of the editor like in the bottom.

**Comment by mjbvz** [comment]
This looks like a duplicate of #9093

Let me know if that is not the case

**Comment by FeliceGeracitano** [comment]
@mjbvz it is. Thanks very much
