### ISSUE TITLE
Syncing of parent and child checked state is not enforced

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode#183916]
Testing https://github.com/microsoft/vscode/issues/183549

Create a tree with `manuallyManageCheckboxSelection` not set and where tree items are created as unchecked.

Unchecking child does not uncheck parent
![checktree1](https://github.com/microsoft/vscode/assets/6461412/ef673d40-d56e-4f36-9b60-5fb1bbae0612)

When expanding for the first time, the parent check state is not applied to children (or the new child state is not applied to parent)
![checktree2](https://github.com/microsoft/vscode/assets/6461412/25af6b1f-ac0c-4db5-ac87-fbb79ed731e4)

_Originally posted by @aeschli in https://github.com/microsoft/vscode/issues/183829#issuecomment-1569828611_

**Comment by alexr00** [comment]
Good find!

**Comment by sandy081** [comment]
Can you please provide steps to verify

**Comment by alexr00** [comment]
You will need to modify an extension to test this.
1. You can start with the file explorer tree view sample: https://github.com/microsoft/vscode-extension-samples/blob/main/tree-view-sample/src/fileExplorer.ts
2. Add checkboxes to the items using the newly finalized `checkboxState` on `TreeItem`.
3. Run the extension and open workspace that contains folders with files in them.
5. In the sample view, do not expand anything
6. Check the checkbox on a folder
7. Expand that folder
8. Verify that all the children of the newly expanded folder are checked.
