### ISSUE TITLE
VS does not pick up .txt files without the run and debug-action

### ISSUE THREAD

**Issue by irmavheerden** [microsoft/vscode#183919]
Type: <b>Bug</b>

contents = ''
with open('input.txt' , 'r') as f:
    for line in f:
    contents = contents + line
print(contents)
f.close()

# The .txt-file is available in the same folder
# The program runs in Pycharm and Python IDLE without errors

VS Code version: Code 1.78.2 (b3e4e68a0bc097f0ae7907b217c1119af9e03435, 2023-05-10T14:39:26.248Z)
OS version: Windows_NT x64 10.0.19045
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4310U CPU @ 2.00GHz (4 x 2594)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|7.91GB (3.41GB free)|
|Process Argv|--crash-reporter-id c3a548e7-301e-46cf-a8d9-1b9bb5c90086|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2023.8.0
vscode-pylance|ms-|2023.5.40

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
3biah626:30602489
pyind779:30671433
89544117:30613380
pythonsymbol12:30671437
showlangstatbar:30737416
vsctsb:30748421
pythonms35:30701012
ecj1e332:30736112
pythonfmttext:30731395
pythoncmv:30739700
fixshowwlkth:30730052
pythongtdpathcf:30739705

```

</details>

**Comment by roblourens** [comment]
Not clear what the issue is, however, if you think that vscode is doing the wrong thing, please open an issue with more details on the vscode-python repo
