### ISSUE TITLE
Carriage return \r display is incorrect in both output and debug console

### ISSUE THREAD

**Issue by xuancong84** [microsoft/vscode#183971]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: all versions up to today 
- OS Version: all OS

Steps to Reproduce:

1. Any code that displays a progress bar using carriage return character "\r", vscode will display it as "\n" which goes to the next line instead of going to the beginning of the current line.
2. It occurs on both STDOUT and STDERR

**Comment by roblourens** [comment]
The debug console and output panes don't support a carriage return character or other terminal control sequences. If you want these handled like you expect, you should run your code in the terminal. For debugging, depending on which debug extension you're using, there should be an option to start the program in the terminal.

**Comment by xuancong84** [comment]
Well, the presence of a workaround does not imply the bug is non-existent. The fact that the bug has been there since day one and has still not been fixed means the working team don't bother to work on this anymore. That is not a sign of competence.

**Comment by roblourens** [comment]
The goal of the debug console is to support basic streaming text along with interactive object output. Since we have a really good terminal built-in to vscode, it's not a design goal of the debug console to also be a terminal.

**Comment by xuancong84** [comment]
As a perfect debug/output console, they should have a switch to toggle whether to show control characters as a printable or execute control characters to go to line begin or previous character or set bold/italic/color, etc. This is because without any plugin, when debugging an application, all those STDOUT/STDERR goes to the debug/output console. If users always need to resolve to use terminal console for debugging in order to work around the control character issue, then what is the purpose of the debug console in the first place?

**Comment by xuancong84** [comment]
**Issue close without being solved.**

FYI, `"console": "integratedTerminal"` only works for `"request": "launch"`, but does not work for Python remote attach, i.e., `"request": "attach"`.
