### ISSUE TITLE
Notebook cell editor 'is not accessible at this time'

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode#183967]
While testing https://github.com/microsoft/vscode/issues/180470

1. Enable screenreader
2. Click into notebook cell
3. :bug: hear 'the editor is not accessible at this time'

**Comment by meganrogge** [comment]
That's coming from here. @joyceerhl were you in `Screen reader optimized` mode? 

https://github.com/microsoft/vscode/blob/5ff3aa8b3466fe825d12ecd91804826974919cbf/src/vs/editor/browser/controller/textAreaHandler.ts#L550

**Comment by meganrogge** [comment]
Then the root of this bug is we're not detecting your screen reader correctly cc @deepak1556 

Which were you using? NVDA, JAWS, Narrator?

**Comment by joyceerhl** [comment]
After digging around in settings I think the problem is that I'd set "editor.accessibilitySupport" to "off" some time ago, so even though I had a screen reader attached, editor accessibility support wasn't enabled--but all the accessibility verbosity settings were still functional, so I didn't initially realize that I'd disabled editor accessibility support. Is there a real end-user scenario for turning accessibility support off.
