### ISSUE TITLE
markdown.copyFiles.destination isn't applied when the markdown file is in a folder that starts with '.'

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#183998]
While verifying https://github.com/microsoft/vscode/issues/183851, I noticed this, it's odd, hopefully I'm interpreting it correctly

- Open the vscode workspace
- Add a `test.md` file under `.vscode/`
- Add any entry to the setting for `**/test*`
- Drag an image into that file
- The setting doesn't take effect, the image goes to its default location
- Rename `.vscode` to `vscode` and drag an image in again
- Now the setting takes effect

**Comment by mjbvz** [comment]
Turns out picomatch won't match dot files by default. However you  can enable this using `dot: true` https://www.npmjs.com/package/picomatch
