### ISSUE TITLE
Test explorer item title can be cut off by inline actions

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode#183997]
In the test explorer, items with a long title and inline actions don't render an ellipses, so the actions cut off the text:
<img width="341" alt="image" src="https://github.com/microsoft/vscode/assets/30305945/4b1d0a3c-79e2-4197-8909-711ae561dc78">

Elsewhere e.g. in the remote explorer, items with a long title and inline actions get text-overflow: ellipses treatment:
![image](https://github.com/microsoft/vscode/assets/30305945/f78ddf8f-b6e2-4656-ba4a-32c8b8c7f211)

**Comment by connor4312** [comment]
Duplicated by https://github.com/microsoft/vscode/issues/186320
