### ISSUE TITLE
'dnu restore' EACCES on Mac OS X.

### ISSUE THREAD

**Issue by ben-humangeo** [Microsoft/vscode#1839]
Version 0.10.6 (0.10.6)

  *    1.0.0-rc1-update1    coreclr x64          darwin          default

I ran `>dnx: Restore Packages` and received a `EACCES` from **npm**.

```
npm ERR! Darwin 14.5.0
npm ERR! argv "node" "/usr/local/bin/npm" "install"
npm ERR! node v0.10.35
npm ERR! npm  v2.3.0
npm ERR! path /Users/bparrish/.npm/lru-cache/2.7.3
npm ERR! code EACCES
npm ERR! errno 3

npm ERR! Error: EACCES, mkdir '/Users/bparrish/.npm/lru-cache/2.7.3'
npm ERR!  { [Error: EACCES, mkdir '/Users/bparrish/.npm/lru-cache/2.7.3']
npm ERR!   errno: 3,
npm ERR!   code: 'EACCES',
npm ERR!   path: '/Users/bparrish/.npm/lru-cache/2.7.3',
npm ERR!   parent: 'minimatch' }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/bparrish/Visual Studio Code/WebApplication/npm-debug.log
The 'postrestore' script failed with status code 3.

Errors in postrestore
    The 'postrestore' script failed with status code 3.
```

I was able to resolve the issue by running the terminal command as `sudo ...` and then rerunning the dnu restore as not sudo to get by the next error with bower.

**Comment by joaomoreno** [comment]
You seem to have made a mistake by running `npm` with `sudo` at least once. I'd preferably avoid it since that will create root owned directories in `~/.npm` which will be hard for your user to work with. Just my two cents.

**Comment by jrieken** [comment]
Correct, it is an issue with the installation on the user machine. That custom restore script just happens to call `npm` somewhere.
