### ISSUE TITLE
stat '# /etc/shells: valid login shells'

### ISSUE THREAD

**Issue by SimonSiefke** [microsoft/vscode#183933]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.78.2
- OS Version: Ubuntu 23.04

Steps to Reproduce:

1. Start VSCode
2. Look at stat calls (for example by using `strace`)

```
[pid 239554] 00:02:45 statx(AT_FDCWD, "# /etc/shells: valid login shells", AT_STATX_SYNC_AS_STAT|AT_SYMLINK_NOFOLLOW, STATX_ALL, 0x7f78df9d8648) = -1 ENOENT (No such file or directory)
```

### Expected behaviour: 
`# /etc/shells: valid login shells` is not accessed since it is not a valid filepath.

### Actual behaviour: 
VSCode tries to access `# /etc/shells: valid login shells` which is not a valid file path.

### Additional information

This is the contents of `/etc/shells`:

```
# /etc/shells: valid login shells
/bin/sh
/bin/bash
/usr/bin/bash
/bin/rbash
/usr/bin/rbash
/bin/dash
/usr/bin/dash
/usr/bin/sh
```

### Terminal profile code 
The only thing I could find related to `/etc/shells` in VSCode was the terminal profile code. Maybe this condition should be negated, e.g `!e.trim().includes('#')` instead of `e.trim().includes('#')` to filter out the comments correctly? 
https://github.com/microsoft/vscode/blob/b3f2337542a15907c998d4e14e73d2bdc2e96530/src/vs/platform/terminal/node/terminalProfiles.ts#L394

**Comment by roblourens** [comment]
@SimonSiefke can you confirm that you aren't seeing this issue in the latest insiders?

I've also verified this by code review

**Comment by SimonSiefke** [comment]
I can confirm it is fixed in insiders. Thanks @Tyriar! :)
