### ISSUE TITLE
Auto hidden panel when losing focus

### ISSUE THREAD

**Issue by shaonianruntu** [microsoft/vscode#183900]
Can we add a feature to enable automatically hide panel when losing focus?

**Comment by lszomoru** [comment]
@sbatten, could you please help with the routing of this issue? Thanks!

**Comment by shaonianruntu** [comment]
At the same time, when you start vscode, the panel will be opened by default. 
I hope to support setting the default status of panel to hidden when opening.

**Comment by sbatten** [comment]
essentially https://github.com/microsoft/vscode/issues/3742
