### ISSUE TITLE
The highlighter of the opening and closing classes doesn't work sometimes.

### ISSUE THREAD

**Issue by ils-mahendrak** [Microsoft/vscode#18392]
- VSCode Version: Code 1.8.1 (ee428b0eead68bf0fb99ab5fdc4439be227b6281, 2016-12-19T14:49:23.350Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

|Extension|Author|Version|
|---|---|---|

---

Steps to Reproduce:

1.
2.

**Comment by mjbvz** [comment]
Can you please provide an example with repo steps, and also describe the expected behavior vs the actual behavior.

Thanks

**Comment by dbaeumer** [comment]
@ils-mahendrak  without the requested information we can't track this problem down. I will close the issue. Will reopen when the requested information is available.
