### ISSUE TITLE
Add additional tokens for bracketColorizer to ignore

### ISSUE THREAD

**Issue by jamesvillarrubia** [microsoft/vscode#183987]
https://github.com/microsoft/vscode/blob/c38a9e9ba506a4530026421f58d58a4e6312bc43/src/vs/editor/common/languages/supports.ts#LL84C2-L84C88

Is there a way to add a custom token or array of tokens that would allow the bracket colorizer to ignore?  

My use-case is that I want to dim and modify all of the Typescript annotations to one or two darker colors.  But... to the bracket colorizer, the tokens are still in the "code" space and thus get colorized, ignoring any TextMate rules.

**Comment by jamesvillarrubia** [comment]
Sorry.  Maybe I'm misunderstanding.  A textmate grammar would allow me to apply grammar to certain token types.  But the VSCode Bracket Colorizer (afaik) applies its colors AFTER textmate.  Meaning that no matter what grammar I set in textmate, the colorizer will override it.

I love the Bracket colorizer and it's inclusion in core VSCode, but is there anyway to override it for certain tokens that are comments?  The problem is not with Textmate, the problem is with Bracket Colorizer overriding Textmate.

Thanks!

**Comment by hediet** [comment]
A contributed language can set a list of textmate scopes in which brackets should be ignored by the bracket colorizer feature.
