### ISSUE TITLE
Console.in vsCode not stopping node app

### ISSUE THREAD

**Issue by psthree** [microsoft/vscode#183974]
Type: <b>Bug</b>

When using console to run a node js app
Control C DOES NOT stop the process
Using the system console (termnial) does

VS Code version: Code 1.78.2 (b3e4e68a0bc097f0ae7907b217c1119af9e03435, 2023-05-10T14:44:45.204Z)
OS version: Darwin x64 18.7.0
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz (4 x 2500)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|8.00GB (0.02GB free)|
|Process Argv|-psn_0_155686 --crash-reporter-id c0b03944-773f-4c29-a0f1-436b9b400752|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (37)</summary>

Extension|Author (truncated)|Version
---|---|---
copy-relative-path|ale|0.0.2
aws-toolkit-vscode|ama|1.74.0
npm-intellisense|chr|1.4.4
vscode-eslint|dba|2.4.0
python-environment-manager|don|1.0.4
python-extension-pack|don|1.7.0
css-flexbox-cheatsheet|dzh|3.3.2
vscode-html-css|ecm|1.13.1
prettier-vscode|esb|9.13.0
auto-close-tag|for|0.5.14
auto-complete-tag|for|0.1.0
auto-rename-tag|for|0.1.10
RelativePath|jak|1.5.0
vsc-python-indent|Kev|1.18.0
vscode-gutter-preview|kis|0.30.0
MagicPython|mag|1.1.0
vscode-duplicate|mrm|1.2.1
vscode-docker|ms-|1.25.1
isort|ms-|2022.8.0
python|ms-|2023.8.0
autodocstring|njp|0.6.1
vetur|oct|0.37.3
vscode-versionlens|pfl|1.5.0
vscode-thunder-client|ran|2.7.3
LiveServer|rit|5.7.9
code-spell-checker|str|2.20.4
pdf|tom|1.2.2
intellicode-api-usage-examples|Vis|0.2.7
vscodeintellicode|Vis|1.2.30
vscode-icons|vsc|12.4.0
jinja|who|0.0.8
glean|wix|5.2.2
vscode-wrap-console-log-simple|woo|1.6.30
vue|Wsc|1.0.26
JavaScriptSnippets|xab|1.8.0
json|Zai|2.0.2
previewjs|zen|1.23.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vscaac:30438847
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
vsccc:30610678
282f8724:30602487
pyind779:30671433
f6dab269:30613381
pythonsymbol12:30671437
2i9eh265:30646982
showlangstatbar:30737416
vsctsb:30748421
pythonms35:30701012
pythonfmttext:30731395
fixshowwlkth:30730052
pythongtdpathcf:30739705

```

</details>

**Comment by roblourens** [comment]
ctrl+C isn't handled in the debug console. You can click the stop button or use the terminal.

**Comment by roblourens** [comment]
Can you give some more details- how do you start the process, how can you tell it is not stopping, what shell?
