### ISSUE TITLE
F12 is not assigned to go to definition in web

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#183953]
Testing #183684

Web Windows

![image](https://github.com/microsoft/vscode/assets/2193314/de113b35-dc5b-403b-8a22-8fa5cea084d4)

Desktop Windows

![image](https://github.com/microsoft/vscode/assets/2193314/b5973258-9b8a-4774-89f0-27b98cc3d2b5)

This may be the case because F12 often opens devtools, but this is not always the case. I have my browser configured such that F12 does not open devtools and it should pass through to the window. Maybe bind both F12 and ctrl+f12?

**Comment by jrieken** [comment]
I share the pain, we seem to [do this on purpose](https://github.com/microsoft/vscode/blob/efb49cc271d6eea5634ac395e36e1e4cd108a447/src/vs/editor/contrib/gotoSymbol/browser/goToCommands.ts#L275-L277) but I also think that we should overrule devtools, e.g have both keybindings registered or check if F12 for devtools is still a thing - afaik that was an IE thing
