### ISSUE TITLE
Wrong comment indent in multiline expressions (TS, JS)

### ISSUE THREAD

**Issue by alexanderby** [Microsoft/vscode#184]
When formatting JavaScript or TypeScript, comments placed between parts of multi-line expressions are placed wrong.
Expected to look like
```javascript
doStuff()
    .then()
    // Comment
    .then();
```
but actually is
```javascript
doStuff()
    .then()
// Comment
    .then();
```

**Comment by jrieken** [comment]
This issue was moved to Microsoft/TypeScript#5772
