### ISSUE TITLE
Can't scroll hover content with arrow keys in notebook editor

### ISSUE THREAD

**Issue by amunger** [microsoft/vscode#184095]
likely caused by the fix for https://github.com/microsoft/vscode-jupyter/issues/13263

1. open notebook and add a few cells
2. put `print(1)` in the first cell and hover over `print`
3. click in the pop up content and press down to scroll
:bug: next cell is focused

![Recording 2023-06-01 at 13 58 05](https://github.com/microsoft/vscode/assets/2019016/5b704237-0cf0-4b22-916c-d26f7f691f8c)

**Comment by aiday-mar** [comment]
I am no longer able to make a hover appear from a cell. It seems to me like hovers have been disabled in cells?

**Comment by aiday-mar** [comment]
Hovers no longer exist in notebooks so this issue can be closed
