### ISSUE TITLE
Snippets don't work in insider on MacOS

### ISSUE THREAD

**Issue by marvinhagemeister** [Microsoft/vscode#18407]
- VSCode Version: 1.9.0-insider b2d2a79da81853bff6e1c60876c9cee8582f9e61 
- OS Version: MacOS Sierra
- Keyboard Language: German (not sure if this has anything to do with the issue)

Somehow I can't get (existing) snippets to work in the current insider build. They are not listed in the autocomplete suggestions anymore.

Steps to Reproduce:

1. Open a file in the language of your choice (like .js)
2. trigger one of your snippets
3. Snippets are missing in autocomplete widget

**Comment by marvinhagemeister** [comment]
Just noticed that they work fine in typescript files. Seems like only JavaScript files are affected as far as I can tell.

**Comment by jrieken** [comment]
I see snippets in JavaScript and it seems that `somehow I can't` needs further details so that I am to reproduce

**Comment by kumarharsh** [comment]
+1 This is not working in Windows also. The `insert snippet` list doesn't populate with user-defined snippets anymore.

**Comment by jrieken** [comment]
I can repo

**Comment by marvinhagemeister** [comment]
@jrieken Awesome, everything is working again with todays build. Thanks a lot for your fix. Really appreciate it! 💯
