### ISSUE TITLE
Dialog is disappearing automatically

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#184025]
Testing #183658

The dialog is disappearing automatically after sometime. If I am slow reader, I would miss it and I do not know how to get it back. Probably we shall show this until user closes it?

**Comment by lszomoru** [comment]
+1 on this, especially that this UX element is only shown once.

**Comment by bhavyaus** [comment]
This has been fixed with: https://github.com/microsoft/vscode/pull/184876
