### ISSUE TITLE
There are missing event listeners for JavaScript

### ISSUE THREAD

**Issue by ScrimoPlayz** [microsoft/vscode#184032]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.78.2 (user setup)
- OS Version: Windows 10 Pro

Steps to Reproduce:

1. Try to save a button in javascript
2. Type (varname).onmouseenter
3. As you will observe, the intellisense doesn't provide any suggestions

**Comment by mjbvz** [comment]
Please share example code that demonstrates the issue

**Comment by ScrimoPlayz** [comment]
const a = document.querySelector('.change')
a.onmouseenter
Try this and you will observe that while typing 'onmouseenter' you get no suggestions.
