### ISSUE TITLE
Global launch.json option

### ISSUE THREAD

**Issue by Kutsan** [Microsoft/vscode#18401]
I have this file and can use my every project. I just don't want to copy them all the time. VSCode generates .vscode/launch.json file every time at project root, this is no good for me. Is it possible to have just one static and default launch config file? Or a option to avoid this copying problem?

```
{
    "version": "0.2.0",
    "configurations": [
		{
			"type": "node",
			"request": "launch",
			"name": "Launch Program",
			"program": "${file}",
			"cwd": "${workspaceRoot}",
			"runtimeExecutable": "/usr/local/bin/node"
		}
    ]
}
```
> launch.json

- VSCode Version: 1.8.1
- OS Version: macOS 10.12.2

**Comment by bpasero** [comment]
fyi @weinand @isidorn

**Comment by isidorn** [comment]
@Kutsan currently it is not possible to have one global launch.json file which would be used everywhere, but what works is to add a "launch" object inside your user settings (preferences > user settings). This way it will be shared across all your workspaces
Example:

```json
"launch": {
		"version": "0.2.0",
		"configurations": [
			{
			"type": "node",
			"request": "launch",
			"name": "Launch Program",
			"program": "${file}",
			"cwd": "${workspaceRoot}",
			"runtimeExecutable": "/usr/local/bin/node"
			}
		]
	}
```

**Comment by weinand** [comment]
@isidorn this is a feature that we mention in the release notes (and the doc).

**Comment by isidorn** [comment]
@weinand makes sense, we should market it proper

**Comment by matyasforian** [comment]
@weinand Where is it in the docs? Ive looked here: https://code.visualstudio.com/docs/getstarted/settings and here: https://code.visualstudio.com/docs/editor/debugging but could not fund anything.

**Comment by weinand** [comment]
@isidorn please add this to the generic debugger doc.

**Comment by matyasforian** [comment]
Also the "launch" tag is not recognized by IntelliSense in the settings.. this is a bug I guess.

**Comment by isidorn** [comment]
I have added this section to the debugging doc
https://github.com/microsoft/vscode-docs/blob/vnext/docs/editor/debugging.md#L96

**Comment by matyasforian** [comment]
@isidorn thanks for the very quick fix! It looks nice, but something is still not clear to me: 
What is the order of precedence of this? Does a launch configuration in the user/workspace setting override a launch config in the launch.json? Perhaps it'd be good to clarify this.

**Comment by weinand** [comment]
And I suggest to include an inline example in the documentation (instead of a link to an issue).

**Comment by isidorn** [comment]
I have added an example inline in the documentation and I have clarified that if a launch.json is present in the workspace the global launch confiugration is ignored.
Thanks for feedback!
