### ISSUE TITLE
Investigate in adopting new Replace pattern in Search

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode#18404]
From #18111 

@alexandrudima has created a new Replace pattern for Find where it records groups while doing search. Adopt the same in Search.

**Comment by sandy081** [comment]
cc @roblourens

**Comment by sandy081** [comment]
@roblourens Currently we compute replace strings for capturing groups on the lines containing matches by applying the search string again. This is not good because as computing search matches (ripgrep) is not the same while computing the replace patterns. 

So, we have to move computation of replace strings to the place where matches are computed (ripgrep). It is the best one to know how to replace capturing groups.

**Comment by roblourens** [comment]
Yes but ripgrep does not have the ability to return info about capturing groups, as far as I know

**Comment by sandy081** [comment]
Can we request this feature?

**Comment by roblourens** [comment]
What problem is prompting this? I don't quite understand the original issue, that case seems to work fine with search now.

**Comment by sandy081** [comment]
As said replace string is built by executing the regex again on the line and getting the matches/groups. So, not sure if these results are always the same with ripgrep results. 

Actually we do not want ripgrep to compute replace string for us, but what we need is that ripgrep can provide us the groups information which would be enough to build replace string without executing again. So, is it possible to get groups information along with matches?

**Comment by roblourens** [comment]
I have not* come across a situation where ripgrep actually matches a regex differently from JS. There is the question of supporting different regex features but as far as I know, if the regex parses in both engines then we get the same result.

*There have been some edge cases involving CR characters but I do some work to get around that and ripgrep has also changed behavior there a bit.

And if there was a difference, we would still have the issue that open file results come from js and not ripgrep, so replacements would be executed differently based on whether they are open. So I don't really want to ask for this unless there is a more specific issue that it will fix.

**Comment by sandy081** [comment]
Ok. Closing this based on above comment.
