### ISSUE TITLE
HTML and CSS servers should have meaningful default settings 

### ISSUE THREAD

**Issue by mniewrzal** [Microsoft/vscode#18402]
At the moment vscode after CSS/HTML language server initialization is sending `didChangeConfiguration` notification to set correct settings. Its ok in general but if such notification wont be sent then some obvious functionalities wont work e.g. validation. I believe that after start the language server should have set of default settings that will enable most important features (without sending additional request). It will help to consume CSS/HTML language server by other clients.

- Version 1.8.1
- Commit ee428b0eead68bf0fb99ab5fdc4439be227b6281
- Date 2016-12-19T14:41:20.664Z
- Shell 1.4.6
- Renderer 53.0.2785.143
- Node 6.5.0

**Comment by aeschli** [comment]
Added changes to the css and html language service to enable validation unless explicitly disabled.
