### ISSUE TITLE
code-insiders tunnel can't sign into Github

### ISSUE THREAD

**Issue by zyh3826** [microsoft/vscode#184024]
Does this issue occur when all extensions are disabled?: Yes/No yes

- VS Code Version: 
- code-cli 1.79.0 
- OS Version: 
- Ubuntu 18.04.5 LTS

Steps to Reproduce:
I download code-insiders CLI, and after `tar` it, I use this command `./code-insiders tunnel --accept-server-license-term`
and open the URL on my browser, a new page displays below, and after a few seconds, it tells me `Sign in failed: Error: No auth flow succeeded.`
![image](https://github.com/microsoft/vscode/assets/31238754/a172e74a-7073-4334-86ac-09f8410d641d)
what's wrong with this?
Hope you can help me, thanks

**Comment by TylerLeonhardt** [comment]
Can you follow these steps so that we can get more information on what's going on?

* Trigger the sign in
* _Wait for the issue to happen..._
* Open the Output pane (ctrl+shift+u)
* drop in this issue he contents of the following:
  * `GitHub Authentication` Output channel

**Comment by zyh3826** [comment]
> Can you follow these steps so that we can get more information on what's going on?
> 
> * Trigger the sign in
> * _Wait for the issue to happen..._
> * Open the Output pane (ctrl+shift+u)
> * drop in this issue he contents of the following:
>   
>   * `GitHub Authentication` Output channel

sorry for reply lately, I already solved this problem, this is because network error
