### ISSUE TITLE
Dialog feedback

### ISSUE THREAD

**Issue by lszomoru** [microsoft/vscode#184036]
Testing #183658

  <img width="1643" alt="image" src="https://github.com/microsoft/vscode/assets/3372902/833dfe6d-d22f-4a5c-8618-e9455249f9fd">

Some feedback to consider for the "dialog":
* We should have some border on the dialog since especially on dark theme it is very difficult to notice  
* It seems that it takes some time for the image to load? Any optimizations that we could do there?
* I would suggest to significantly reduce the width of the dialog:
    * This will help with the text being laid out more nicely
    * This will help with the long button to dismiss the dialog
* Instead of the "Learn more" link button I would use a sentence (ex: Read out documentation to learn more) and place it in the first paragraph.

**Comment by bhavyaus** [comment]
This has been fixed with https://github.com/microsoft/vscode/pull/184876
