### ISSUE TITLE
code-server can not run python file

### ISSUE THREAD

**Issue by 18392152392** [microsoft/vscode#184020]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 
- OS Version: 

Steps to Reproduce:

1.  I download the latest code-server, version is code-server-4.13.0
2.  I use ./code-server --port 5000 to start
3. I download the python extension then it toast some warnings
4.  the error is as followings

![1685601645168](https://github.com/microsoft/vscode/assets/52459655/5364d383-e068-47cf-ba67-523aec0787ed)

5. also, the python file can not run
6. I think it is a serious bug, can you help to fix

**Comment by roblourens** [comment]
code-server is not an officially supported vscode distribution
