### ISSUE TITLE
Feedback on the text

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#184033]
Testing #183658

![image](https://github.com/microsoft/vscode/assets/25044782/daef974b-c7a6-451c-aa57-f77acadb662d)

I see there are two actions doing the same thing.

1. Source Control View Link
2. View Changes

- Do we really need the first link, given that there is a big blue button to view changes?
- `Learn More` link should be right next to the end of the first sentence and not in a separate line.
- Probably `Learn More` link should point to documentation page in code.visualstudio.com and not to github readme.

**Comment by bhavyaus** [comment]
@bamurtaugh Currently I am using the https://aka.ms/vscode-remote/remote-repositories link. Is there a better link to direct users to?

**Comment by bamurtaugh** [comment]
I'd probably recommend https://code.visualstudio.com/docs/sourcecontrol/github#_github-repositories-extension if this appears in any GitHub Repos session (web and desktop). 

But if this only appears in web, I'd recommend our vscode.dev doc: https://code.visualstudio.com/docs/editor/vscode-web#_opening-a-project.

I can create an aka.ms link for either of the above if you'd like, just let me know which scenario feels more fitting here!
