### ISSUE TITLE
Welcome page doesn't load if internet isn't available

### ISSUE THREAD

**Issue by TylerLeonhardt** [microsoft/vscode#184082]
<img width="1680" alt="image" src="https://github.com/microsoft/vscode/assets/2644648/9a079f6c-39a9-4cb6-b0a7-04becb227410">

Steps to repro:
* Connect to a wifi network that doesn't provide a reliable internet connection (like the Connector 😉 )
* Open VS Code

Welcome view fails to load due to a web request. I expect the Welcome page to load even without internet.

**Comment by joyceerhl** [comment]
I just encountered this:

<img width="1203" alt="image" src="https://github.com/microsoft/vscode/assets/30305945/fc76d5d5-6037-464e-9fd4-5c244caab6ea">

I believe this is a regression

**Comment by joyceerhl** [comment]
Yeah, 1.78.2 stable allows to open the welcome page without internet

**Comment by bhavyaus** [comment]
Doesn't repro in OSS.
Same issue occurs with the Extension marketplace when searching without internet.
<img width="700" alt="image" src="https://github.com/microsoft/vscode/assets/25044782/94d36720-eb2f-4564-9235-b0b0568c5bdf">

Calls to the galleryService is failing when there is no internet. 
https://github.com/microsoft/vscode/blob/4137aa15f55c5ec3777daf6684908f64b439f6aa/src/vs/workbench/contrib/welcomeGettingStarted/browser/featuredExtensionService.ts#L111-L112
