### ISSUE TITLE
do not add '--nolazy' flag when 'running' a target

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#18400]
- VSCode Version: 1.9.0
- OS Version: any

Steps to Reproduce:

1. 'run' a node program (Cmd-F5)

Observe: node is called with a '--nolazy' argument

**Comment by dbaeumer** [comment]
@weinand not sure if this is intended but --noLazy is missing as well when debugging a node app (e.g. start with F5)

**Comment by weinand** [comment]
@dbaeumer I always see a '--nolazy' flag being passed when debugging a node app:

![2017-01-27_16-36-14](https://cloud.githubusercontent.com/assets/1898161/22376607/fd1588f2-e4ae-11e6-8c7b-f83596a03e97.png)

But I see the problem that "Run without Debugging" (Cmd + F5) is not working.
I've filed #19517 for this.

**Comment by dbaeumer** [comment]
Strange now I see the --noLazy as well.
