### ISSUE TITLE
mouse select doesn't work in rename text box on OS X

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#1840]
- select a (TypeScript) symbol for rename
- from context menu pick "Rename symbol"
- Observe: a text box appears
- trying to select the text in the text box with the mouse doesn't work

**Comment by alexandrudima** [comment]
interestingly, it works on windows

**Comment by weinand** [comment]
@alexandrudima it now works on OS X too, I've just verified with the latest. May be this is the issue that Isi had found with the hover?

**Comment by alexandrudima** [comment]
You're correct. the `RenameInputField` is exactly an `IContentWidget` with `allowEditorOverflow` = `true`

**Comment by alexandrudima** [comment]
fyi thanks @isidorn !

**Comment by isidorn** [comment]
😇
