### ISSUE TITLE
Second editor with specified window.zoomLevel is blurred 

### ISSUE THREAD

**Issue by jsnjack** [Microsoft/vscode#18403]
- VSCode Version: 1.8.1
- OS Version: Fedora 25

Steps to Reproduce:

1. Set window.zoomLevel = 0.2
2. Create a layout with 2 vertical editors
3. If explorer is closed, second editor is blurred (See screenshots)
![screenshot from 2017-01-11 14-37-12](https://cloud.githubusercontent.com/assets/5493713/21850871/f6fb27aa-d80c-11e6-90a7-36db3229914e.png)
![screenshot from 2017-01-11 14-37-20](https://cloud.githubusercontent.com/assets/5493713/21850872/fba0c3dc-d80c-11e6-89b9-5a65b258ab30.png)

**Comment by Tyriar** [comment]
I cannot repro, all text looks blurry for me though because I'm on a standard monitor.

**Comment by jsnjack** [comment]
It is actually depends if zoomLevel is odd or even. I posted an example with even zoomLevel. If I make it odd, the result is still blurred but in the opposite order

**Comment by bpasero** [comment]
Todays VS Code insider build comes with Electron 1.6.x, would be interesting to hear if this update solves this issue for anyone: http://code.visualstudio.com/Download#insiders
