### ISSUE TITLE
Right click in file tree to create new file when vscode was not in focus, does not allow you to type a name

### ISSUE THREAD

**Issue by basvdijk** [microsoft/vscode#184144]
Type: <b>Bug</b>

- Open a folder in vscode
- Focus on another window than vscode
- Right click on the file tree to create a new folder / file
- The box to enter a name appears in the tree, but you cannot enter any data
![image](https://github.com/microsoft/vscode/assets/644550/8baf2694-dd79-4ec6-a46b-3d7a00c90c94)

- To make it work you have to do the above again, then it works:
![image](https://github.com/microsoft/vscode/assets/644550/267fb42b-ef11-4e9e-8a99-4881512d6b67)

It looks like it has something to do with vscode not being in focus while the right click happens.

VS Code version: Code - Insiders 1.79.0-insider (784e72bc4486b7ea5ad3447c506e31d949848592, 2023-05-30T05:23:26.066Z)
OS version: Darwin arm64 22.4.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Max (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|10, 10, 9|
|Memory (System)|32.00GB (0.10GB free)|
|Process Argv|--crash-reporter-id a320977d-9954-4d56-aa5e-e808c1ad3dcf|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythontb:30258533
pythonptprofiler:30281269
vshan820:30294714
vscod805cf:30301675
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30404738
cppdebug:30492333
vscaat:30438846
vsclangdf:30492506
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30618038
pylantcb52:30590116
pyind779:30611226
pythonsymbol12:30651887
showlangstatbar:30737417
pythonms35:30671666
03d35959:30757351
ecj1e332:30687743
pythonfmttext:30716741
pythoncmvfstr:30726892
fixhidewlkth:30724384
hidesbindicator:30724476
pythongtdpath:30726887
welcomedialog:30756234
pythonnosmt12:30757129

```

</details>

**Comment by lramos15** [comment]
\duplicate https://github.com/microsoft/vscode/issues/143968
