### ISSUE TITLE
Syncing with github in the app doesn't work behind a corporate proxy

### ISSUE THREAD

**Issue by critesjm** [Microsoft/vscode#18417]
I have the proxy settings saved in my global .gitconfig and they seem to work fine with the github for windows app. I'm not really sure what needs to happen to make it work in code but I'd like it to be able to do the couple of basic things I do regularly without having to switch apps all the time.

- VSCode Version: Code 1.8.1 (ee428b0eead68bf0fb99ab5fdc4439be227b6281, 2016-12-19T14:49:23.350Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions:

|Extension|Author|Version|
|---|---|---|
|vscode-eslint|dbaeumer|1.2.2|
|python|donjayamanne|0.5.5|
|xml|DotJoshJohnson|1.7.0|
|vscode-babel-coloring|dzannotti|0.0.4|
|EditorConfig|EditorConfig|0.3.4|
|beautify|HookyQR|0.7.3|
|docomment|k--kato|0.0.11|
|theme-karyfoundation-themes|karyfoundation|10.2.0|
|mssql|ms-mssql|0.2.0|
|csharp|ms-vscode|1.6.2|
|PowerShell|ms-vscode|0.8.0|
|vscode-docker|PeterJausovec|0.0.11|
|language-stylus|sysoev|1.6.0|
|ayu|teabyii|0.2.1|

---

Steps to Reproduce:

1. Open local copy of a repository on a machine behind a corporate proxy
2. Attempt to pull or use the sync feature

In the Git output pane, you'll see "fatal: unable to access 'https://github.com/UserName/project.git/': Failed to connect to github.com port 443: Timed out"

**Comment by mjbvz** [comment]
It sounds like the creds are working with github for windows, but what happens if you try to run git from your command line directly? Do you also see this error?

**Comment by critesjm** [comment]
Ah, yeah. So maybe it's not something specific to you guys and I'll need to figure that out.
