### ISSUE TITLE
SCM consolidated status bar item no longer reflects incoming/outgoing changes

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode#184102]
1. Have incoming changes 
2. Run **Git: Fetch** command
3. :bug: status bar no longer shows incoming changes

<img width="662" alt="image" src="https://github.com/microsoft/vscode/assets/30305945/a4998732-77ef-48f6-984a-bcb240ecdd8b">

**Comment by lszomoru** [comment]
@joyceerhl, I am unable to reproduce this so I am wondering if we could get on a call so that I take a look. Thanks!

**Comment by joyceerhl** [comment]
I believe the behavior I saw last week has to do with the fact that I had abandoned a bisect session previously and then continued working on the main branch. If I reset my bisect session and checkout main again, git reports ahead/behind status correctly.

**Comment by joyceerhl** [comment]
Hm, I cannot figure out a minimal repro. Possibly has to do with the number of intervening commits between HEAD and where I was with the bisect session, since I likely abandoned that bisect session months ago. I'll close this for now since it's not currently actionable and revisit if I hit on the repro. Thank you for taking a look!
