### ISSUE TITLE
Notebook toolbar execution section improvements

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#184194]
On the notebook toolbar we have multiple sections of actions, and the first two are core sections: insert and execution. The Insert section is very stable and it always contains two actions: insert code and insert markdown. However the execution section has actions from both VS Code core and Jupyter extension, and with a mix use of visibility and enablement, it is not user friendly and often leads to mis-clicks.

## Jupyter kernels

**Initial state**

<img width="811" alt="image" src="https://github.com/microsoft/vscode/assets/876920/a5bafa5a-7b7c-422c-ae85-d95727c7689b">

**Start execution**

<img width="884" alt="image" src="https://github.com/microsoft/vscode/assets/876920/f2f81e01-d434-4768-bfbb-2638b28a99d5">

**Execution fails**

<img width="903" alt="image" src="https://github.com/microsoft/vscode/assets/876920/6a884578-6beb-4c9d-9f2d-2723aada4884">

**Execution succeeds**

<img width="810" alt="image" src="https://github.com/microsoft/vscode/assets/876920/126a2b18-4812-4596-ad2f-5dc665eb7b9b">

## Non Jupyter Kernels (e.g. Pyodide)

**Initial state**

<img width="657" alt="image" src="https://github.com/microsoft/vscode/assets/876920/f07d4b5f-a7fe-4c61-984a-08444e5bfcee">

**Start execution**

<img width="867" alt="image" src="https://github.com/microsoft/vscode/assets/876920/897256e3-9dab-49a9-9fa9-70f8e0278254">

**Execution fails**

<img width="728" alt="image" src="https://github.com/microsoft/vscode/assets/876920/2958aa33-ae5e-43ab-99d9-61e28052d30f">

**Execution succeeds**

<img width="625" alt="image" src="https://github.com/microsoft/vscode/assets/876920/b33434d7-53a3-49df-b59c-059cbacb4a92">

---

As shown above, currently only `Clear all outputs` is using enablement while all others are using visibility, which can lead to change of positions for the actions and often when users want to interrupt or restart the kernel, their position changes and users click on wrong actions. cc @roblourens

**Comment by roblourens** [comment]
What are users misclicking on? From my memory, I remember Go To vs Restart. I think that "Restart" has a confirm dialog, are there other destructive actions that should also have a confirm dialog?

Or, should we use enablement and have all actions always visible?

**Comment by rebornix** [comment]
> What are users misclicking on

@roblourens  For Jupyter kernel, I ran into Go To vs Restart and sometimes Restart vs next action on the toolbar (since Go To disappears), and for non Jupyter, it's Interrupt vs Clear all outputs. 

> Or, should we use enablement and have all actions always visible?

It might be hard to enforce that but we could probably at least ensure the ones that are always visible won't change their position when the execution state changes. For example, if Go To only shows at the end in this group, and Run All is always replaced by "Interrupt" or "Stop", then it's less likely to mis-click.
