### ISSUE TITLE
[Intellisense][HTML] Picking css property from intellisense suggestions list replaces the next property key

### ISSUE THREAD

**Issue by hun1ahpu** [Microsoft/vscode#18414]
- VSCode Version: 1.8.1
- OS Version: Windows 10

Please see video for repro steps:

![cssintellisense](https://cloud.githubusercontent.com/assets/4397796/21864006/fd5187ce-d83f-11e6-81d4-e8380f4c89a9.gif)

**Comment by aeschli** [comment]
I can't remove the replacing behavior, in most cases where users use code assist in the kiddle of an existing value replacing is what users want. I agree that you don't want it it in this case, but I don't know how to decide when to insert and when to replace. Any suggestion?

**Comment by hun1ahpu** [comment]
@aeschli: Don't know how easy/performant it can be but when inserting the value to check if the text on the right is css key or css value (has ':' after it).
Looked at how visual studio does it. It correctly replaces the key, though it doesn't seem to work for values. it keeps the text after even if it's css value.

**Comment by aeschli** [comment]
closing. Workaround is to add a space first.
