### ISSUE TITLE
[html wrong comment syntax while still in script element attributes

### ISSUE THREAD

**Issue by unional** [Microsoft/vscode#18416]
- VSCode Version: 1.8.1

```html
<!DOCTYPE html>
<html>

<body>
  <script src="node_modules/lodash/lodash.min.js"></script>
</body>
</html>
```

When the cursor is at `<scrip^t...`, it is working correctly.
But if the cursor is at `<script^` or in `src="..."`, it is incorrect.

![image](https://cloud.githubusercontent.com/assets/3254987/21865166/cbd028e0-d7f9-11e6-8000-c71a4649dfbe.png)

...by pressing `[ctrl + /]` or `[cmd + /]`

**Comment by aeschli** [comment]
Caused by https://github.com/textmate/html.tmbundle/issues/48
