### ISSUE TITLE
Allow Setting Syntax With Command Palette

### ISSUE THREAD

**Issue by sheldonhull** [Microsoft/vscode#18411]
- VSCode Version: 1.8.1
- OS Version: Windows 10

Setting syntax of a newly created file requires clicking in the bottom right hand corner and selecting from the list of available syntax types. 

In sublime text, the user is able to do this very quickly by `Command Palette` > `Set Syntax: X` and the syntax tools and formatting then are available. This requires no mouse interaction. 

Request: Enable command palette to set syntax quickly based on partial match (ie, set sql should fuzzy match to set syntax: Sql > set power  should fuzzy match to set syntax: Powershell)

**Comment by bpasero** [comment]
![image](https://cloud.githubusercontent.com/assets/900690/21859821/7101b28c-d82e-11e6-9157-4db80aac7da0.png)

**Comment by sheldonhull** [comment]
My apologies. I searched and didn't find the right wording for this command. Thanks for the quick response. 

Is there any configuration option I can use to "alias" a command so I can use "set Syntax" if I want to, to keep it consistent in both editors? If so respond, otherwise I'll assume that's not possible. cheers

**Comment by bpasero** [comment]
No, maybe for that we should have a separate feature request.
