### ISSUE TITLE
Cannot hide files on some conditions

### ISSUE THREAD

**Issue by TitaneBoy** [Microsoft/vscode#18419]
- VSCode Version: 1.8.1
- OS Version: Windows 7 Pro 64bits

Hi. I'm facing an issue. I'm not able to hide files on specific conditions. I'm trying do to the same thing as described here: [Hiding Derived JavaScript Files](https://code.visualstudio.com/Docs/languages/typescript#_hiding-derived-javascript-files).

In my example, I've done a simple hello world example. I'm trying to hide the derived javascript file "HelloWorld.js", generated from "HelloWorld.ts" but for a reason I don't understand, it's not working. The "When" condition doesn't seem to work. But when I put "true" instead of "$(basename).ts", my only javascript file (and other I guess if there were more than one) is hidded.

Can you tell me please what I am missing in the procedure or if it's an issue ?

Thank you for your answer.

![vscode issue](https://cloud.githubusercontent.com/assets/15614466/21867452/3339bf38-d81c-11e6-9c55-c7eb6abf8a1f.png)

**Comment by mjbvz** [comment]
It looks to me like the problem here is that the output js files are in a different directory than the source ts files. I tried `./$(basename).ts` and `.$(basename.ts)` and `${workspaceRoot}/$(basename).ts` but none seemed to work.

@bpasero or @roblourens Any thoughts on this?

**Comment by roblourens** [comment]
In a case like this, you probably just want to exclude the 'scripts' folder entirely, right?

**Comment by TitaneBoy** [comment]
@roblourens In my case, not necessarily. I may put some others js file in this folder that I would like to see in the file Explorer tree. I just want to hide js files generated from ts files, no matter where they are...

**Comment by TitaneBoy** [comment]
In the task used to generate js file from ts, I specified to output files in the scripts folder

**Comment by bpasero** [comment]
There is no support to use the when clause on files that are not siblings of the file in question. You will have to exclude files in that folder using the normal glob patterns.
