### ISSUE TITLE
vscode becomes too slow and shows error

### ISSUE THREAD

**Issue by i-am-coding-right-now** [microsoft/vscode#184149]
Type: <b>Performance Issue</b>

it takes too much time to open vscode saved files

VS Code version: Code 1.78.2 (b3e4e68a0bc097f0ae7907b217c1119af9e03435, 2023-05-10T14:39:26.248Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz (8 x 2419)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|7.73GB (1.26GB free)|
|Process Argv|--crash-reporter-id 3c970658-9a42-437f-a6a2-7b2f6bf22538|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	   110	  6388	code main
    0	   132	  8568	window [2] (Welcome - Visual Studio Code)
    0	   168	 11452	window [3] (validate.php - MyHostel-main - Visual Studio Code)
    0	    79	 18168	fileWatcher [2]
    0	   191	 22844	   gpu-process
    0	    87	 25604	fileWatcher [3]
    0	   102	 28016	shared-process
    0	    79	 35336	     ptyHost
    0	   287	 30312	extensionHost [3]
    0	   123	 21836	     electron-nodejs ("D:\New folder\Microsoft VS Code\Code.exe" --ms-enable-electron-run-as-node c:\Users\Parth\.vscode\extensions\bmewburn.vscode-intelephense-client-1.9.5\node_modules\intelephense\lib\intelephense.js --node-ipc --clientProcessId=30312)
    0	    83	 37004	     electron-nodejs ("D:\New folder\Microsoft VS Code\Code.exe" --ms-enable-electron-run-as-node c:\Users\Parth\.vscode\extensions\amazonwebservices.aws-toolkit-vscode-1.75.0\dist\src\ssmDocument\ssm\ssmServer.js --node-ipc --clientProcessId=30312)
    0	    93	 37344	     electron-nodejs ("D:\New folder\Microsoft VS Code\Code.exe" --ms-enable-electron-run-as-node c:\Users\Parth\.vscode\extensions\amazonwebservices.aws-toolkit-vscode-1.75.0\dist\src\stepFunctions\asl\aslServer.js --node-ipc --clientProcessId=30312)
    0	   170	 32324	extensionHost [2]
    0	    79	 20932	     electron-nodejs ("D:\New folder\Microsoft VS Code\Code.exe" --ms-enable-electron-run-as-node c:\Users\Parth\.vscode\extensions\amazonwebservices.aws-toolkit-vscode-1.75.0\dist\src\ssmDocument\ssm\ssmServer.js --node-ipc --clientProcessId=32324)
    0	    81	 21920	     electron-nodejs ("D:\New folder\Microsoft VS Code\Code.exe" --ms-enable-electron-run-as-node "d:\New folder\Microsoft VS Code\resources\app\extensions\json-language-features\server\dist\node\jsonServerMain" --node-ipc --clientProcessId=32324)
    0	    90	 30432	     electron-nodejs ("D:\New folder\Microsoft VS Code\Code.exe" --ms-enable-electron-run-as-node c:\Users\Parth\.vscode\extensions\amazonwebservices.aws-toolkit-vscode-1.75.0\dist\src\stepFunctions\asl\aslServer.js --node-ipc --clientProcessId=32324)
    0	    28	 33992	   crashpad-handler
    0	    88	 35228	window [4] (Issue Reporter)
    0	    50	 38008	   utility-network-service
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (validate.php - MyHostel-main - Visual Studio Code)
|    Folder (MyHostel-main): 40 files
|      File types: jpeg(18) php(16) html(2)
|      Conf files:;
```

</details>
<details><summary>Extensions (21)</summary>

Extension|Author (truncated)|Version
---|---|---
aws-toolkit-vscode|ama|1.75.0
ng-template|Ang|16.0.0
vscode-intelephense-client|bme|1.9.5
vscode-eslint|dba|2.4.0
isort|ms-|2022.8.0
python|ms-|2023.8.0
vscode-pylance|ms-|2023.5.50
jupyter|ms-|2023.4.1011241018
jupyter-keymap|ms-|1.1.0
jupyter-renderers|ms-|1.0.15
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-slideshow|ms-|0.1.5
cpptools|ms-|1.15.4
notepadplusplus-keybindings|ms-|1.0.7
vscode-serial-monitor|ms-|0.9.0
nodejs-snippets|piy|0.0.2
LiveServer|rit|5.7.9
vscode-zipexplorer|sle|0.3.1
vscode-arduino|vsc|0.6.0
php-debug|xde|1.32.1
json|Zai|2.0.2

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
vscccc:30610679
282f8724:30602487
pyind779:30671433
f6dab269:30613381
vscrp:30673768
pythonsymbol12:30671437
a9j8j154:30646983
showlangstatbar:30737416
vsctsb:30748421
pythonms35:30701012
03d35959:30757346
pythonfmttext:30731395
pythoncmv:30756943
fixhidewlkth:30730051
showsbindicator:30730056
pythongtdpath:30739704
pythonnosm12tcf:30757130

```

</details>

**Comment by gjsjohnmurray** [comment]
Are you using McAfee anntivirus?

If so please see https://github.com/microsoft/vscode/issues/178962. Let us know if McAfee is not installed on your PC, else use the instructions to resolve.

**Comment by fisforfaheem** [comment]
vscode has become so slow these days, please update the chromium engine

**Comment by Lanibugatti** [comment]
Lol
