### ISSUE TITLE
Jumpy cursor with trim trailing whitespace and autosave

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#18410]
I think this is a regression.

workspace settings:
```
    "files.autoSave": "afterDelay",
    "files.trimTrailingWhitespace": true,
    "editor.renderWhitespace": "all"
```

* open file `A.ts` side-by-side with itself
* reload workbench
* focus on the right hand side and type two spaces => cursor doesn't jump
* focus on the left hand side and type two spaces on a different line => cursor doesn't jump
* focus on the right hand side and type two spaces => **cursor jumps**
* Note: sometimes reproduces right away
![jumpy](https://cloud.githubusercontent.com/assets/5047891/21858343/05e51c6e-d829-11e6-99ca-54aab70176d1.gif)

Please let me know if you think this is something on my side, but I think this was implemented initially to work in these cases.

**Comment by bpasero** [comment]
@alexandrudima I don't know why but for some reason this [check](https://github.com/Microsoft/vscode/blob/master/src/vs/editor/common/commands/trimTrailingWhitespaceCommand.ts#L69) assumes that there is a cursor on line 3:

![image](https://cloud.githubusercontent.com/assets/900690/21859443/ed1fc806-d82c-11e6-9003-a3ba4cb81de9.png)

I can also only reproduce with 2 editors open.

**Comment by bpasero** [comment]
Pushed a fix, the focussed editor was not preferred when finding the editor for the model.
