### ISSUE TITLE
Inline completion not displaying when surrounded by whitespace

### ISSUE THREAD

**Issue by njiang747** [microsoft/vscode#184108]
Does this issue occur when all extensions are disabled?: N/A (requires extension to provide inline completions)

- VS Code Version: 1.78.2
- OS Version: macOS 13.0

Steps to Reproduce:

1. Trigger inline completion on a line with whitespace to the immediate left and right of the cursor.
2. Even when the InlineCompletionProvider returns items, they do not display in VSCode.

Example:

Starting with this code:
<img width="134" alt="image" src="https://github.com/microsoft/vscode/assets/12000736/de00353f-b7ce-4cbc-be56-3977527a8849">

Delete `baz`, suggests it correctly:
<img width="133" alt="image" src="https://github.com/microsoft/vscode/assets/12000736/dd6dab6c-19d3-4f96-8152-f15c8049bbb1">

Delete `az:`, suggests it correctly:
<img width="132" alt="image" src="https://github.com/microsoft/vscode/assets/12000736/e304ac8a-b76d-4a0b-b9f7-82d3914bd43c">

Delete `baz:`, does not suggest anything:
<img width="134" alt="image" src="https://github.com/microsoft/vscode/assets/12000736/6f218be7-97ae-458a-883e-1b6e03434e19">

I confirmed that the InlineCompletionProvider does return `baz:` as expected but in this case VSCode does not display it.

**Comment by hediet** [comment]
Please try to reproduce in the [inline completion playground](https://microsoft.github.io/monaco-editor/playground.html?source=http%3A%2F%2Flocalhost%3A5001%2Fout%2Fvs#XQAAAAIqHAAAAAAAAABBqQkHQ5NjdMjwa-jY7SIQ9S7DNlzs5W-mwj0fe1ZCDRFc9ws9XQE0SJE1jc2VKxhaLFIw9vEWSxW3yscxyx-6HVciAKctgAboa7AaZZDHLgrLqPRv_fRv2RyIokydlTdTYccsu6v6jDrc8jQ8utukPwKUQ2RhhDEWkiejwvhCv6mI9f-mMWJ901Y9mnfbO1g9WbURsQKLj7If1bEqyfxshEfYmMsEBsZWDcvtviGwczYH-bGaY1q1RTksWprUaeb-7D9qk8sSZzNt4rv4OI9tPsXri4WDjMgCqcbDuFokXJzKy2gqmGmSPqpHgQIM0u8P3kyl2iDyOLRX7pffC0wtHHJbtk5Wp_jyMrpJQhlh4zrZoEKisNLyVy6r7velG7BULVOfeVyuQwec9LaEKXOW7WsrPRvPUXd6Mc-6NCjumphLE7e7qlpuD4U8a3tyNqUafePM05t3TUd5jHLGWAyJNlKsFrchjXEoUumGQ_461dRDaztbiGlpCzR3VJTXFCmH8oScjafsl5jj5eIzfi2-915tKakSFDv27UiLkjCItKT-Behj3gK9SSTNPzqj3unV95iGA4PZXZOJNQGsRDRZ1b5Nln9zL4YZ6TUSLpBxoj-eFljivVriY81Vm9c9VCNrpzx0_t9np7-g4X1rdNmxxz3sEGZhRg6DE31OlRMuU4nNu-arXPjKs0K56snZteJ29YKdWq3FI3ETCVzZ_TwZoTOhOEhkr7mI1LNtezFmBIDTjgucW_w_uPk3czeE-k65Ul-k-3GcSMG9Y03EPMKdoaPPAet1ikRlMobg0nPnFn5XqlzZcnKiqimCQs86lrbOOeQNMBnfVD41RVH6p_mZs-8THqT7j6gPzIfTAJ7jZ3SC7bTRxBAuHNkXJK6lb8AO0gcJcjyilwM7_tYTWwVg-D0YbPG4HvzaC9-egJJ3CbHm50VUKSTJCoQptXhBbrnVEa6Q7F8MOnVrWyKusAP-eX8NNss24XQQhdz2GB5j6ELJ66eekSIHt7cCN2-FUEmx1tf-VR8t3cmW5FgBznDeQAAojFzZ4jgSPW_bvVwIbg0Mk1SyEh7MEeOuegjfBj6FEUI9yKfuNMR7jF5PA87fx7-xB6ydHB-OWm14uH_9sXFn6P0n5dGDZEVoGBMZWb-sF9Jn9hdhrASGcmTcHSz9fzv9vgAaAF9u5Ubn4XJSp_bgfDGUTOSATxIDgRj9DHkvF8tIRugFPJPGxhd7vZj0lcm0ZemuP751sgqmj8FLicEcFHn43q-MMFP1urjATCDS_VMwLR_L4YvAx-GEVWxLqxRmb6bR00fdVr9D88t0Xb20bejJe7SBvM_vMEzqqInPlIC5JWJshR3OtmnNrE9boka4xJpnUy0YyD1yEi63j1TeYzSjL2WInktcJj7_M5L6jCyYg0fIH6_hmVZRaPH9PkMowCOEoFW-ftqpMXNpW7MFVRiZ4PLXAEDAFvgSfpJKu16sO-p2iVaDPCHM5R3Sq-Lu_kdXooT8qcAagpMyNL5ZdLF-q-8fRgWadzoklGONplwoU3J0ngeG5JQNTX3G4IWblQHnR3xAmw_ZZp9qg640zarmwbdbBfP9erXzv31t3Mo6TS6CpjCC2NNGpBEoYYuU-SXPPrpoaQ27etcZOl4lONdpp8y2j7OXF24RCjsk8B5LRjERL2t4dZ5wK0RDZvuTG9FL4G6loWAXX6yc3bCUaMYnh-Kb6DMKFgbOwo52NWadVksCNtG4pjIZBEBIhU41JPXcwf9Z55FdT6IUOgcUK_K1EXEzDKL5Zn9hu_lOeE7HtD5geYKcYn3e0eNZMC6r0bwHsP4T57DruS0kwbr2jy2EqVsg_GGfB1AHmIdrsSFTJz4wanEynUBmaVD4U4pihuQfvVpfCMkT2OKlH41ejHCzPyItLZGoYBVOA2pYBfUjdDd2bTbhGsJmYvCw8M4OPJ60ifu3emYNWQZTlDcEUTXB2q-1_kD86m-424P77lzmtdswcorbKu4SEKaunXRXdwSXieCiguZTacHbgZ8CqeWRI9b0vJYx9CQX7Al8lXAoLd3Hwr_2kb2HHIRW6qFDHnyGnX7CojYBtnQRM1-pxMz5vzPlz96AQcxdFS_2FKIVfzftLjmR3eraFQQtynlWFhgOEyL7mc-ptHvBLe748Rw__zX1Ca3Po5o2kYUli-dwpZBRocw-It0hp-joU62EKgQri1Q6ZyL5E_NHDuanyhr-_hZNB4XlLHRZdegtyFWwmcmBgbgh1kL5ZPx9IleapAVnE0fIMoaK2thH7mz51VcsSKbvmVbMu9QBcWDkbfGmWeAB_dqqC02YJLzzBCmTxcSu4T9MH7qlwsYKhumektALWnlInzMc_R427vBnYSvXhBpX0w2KkdzqCdAc7-WvOkQ2Ci8V1eEPkgdLnvci0qGqxE6dXJ1N-zuq5FlBmQTjpdy0nVKDkE1141me54IRy-t1_I4KR7rW1AUStUKvnIzKwWJ1wMppJ3lqh_vjwvVN5Fhsb3WHLRHhvLSafTLkgwpW2DQH_XSu2nBKkvHREbiyKiJAaeG86XPZMn-ek1k3MPsuaJkdYimQcctD6kRaPI6LBKkxK_4bHpU4mzPvXfva8rntn_MEhOheUi4WgtA8Db_QZAagvWozQIpJ9Y8NBlGPWJjFeEdJlBsvTu-_Thek_oXprxFSFP1Z6XYJcdPR1W90Fm-GKT2zDANNRGVRMMDJGwaXQg-GWuDuxdBzFbEXBHokVC_JUvYwSmEDLB7mSjFSJIvATVgZAwuWCY0LjPtqh3tqXqBKFEfQNzqfhf0fUrlOVdC1O8xqVAB-w_J_7LGwQGKWt2wFMvVtCbi0_3iphAA).

**Comment by njiang747** [comment]
I tried to come up with a minimal example [here](https://microsoft.github.io/monaco-editor/playground.html?source=v0.39.0-dev.20230601#XQAAAAJyBAAAAAAAAABBqQkHQ5NjdMjwa-jY7SIQ9S7DNlzs5W-mwj0fe1ZCDRFc9ws9XQE0SJE1jc2VKxhaLFIw9vEWSxW3yscw6qUcO_1uhs0-3YGTBOsVJ4S4FwfCDQb5-2uUHXTVAefbVSd9IzaZ_vv9VR9KugsKikrz1yE9gFH9OhlbPy-J7d5sSKeOrMzKBWDFblNCJU0tW3WwheMBQ7S6bLidj1LnY0O2JVXSf6mxl2r6ajKEdWXm-uipv3QLRd6q3Az03vb9ksBnE7kCo2qYu2zKSMHIeaouaSi5-1JaLIWjfrrbNq3cVTLLpvElKhLVQwDktapqS-6ei1PZZUhBwEu0uIugrBzXbyEAWaveX4E837pFhfzzt2s-WNejPKZsvz_5W6k3GaeP7htmNqqtWjl3eX_7JVRPYilz8UY7fAOQV8blGH61fUatQk5aJ9TyjMy9pYn2TVwlQAZoRJzi0pzd0qW5SgOm7Zggn8LPKhTytCnD3EiMn0g5Y_kYmaARwGX_EWXqrekP-E060IUq4MWGfRiMxhsnv8opppiD0FIrLYXC_nJJI0xHUTDYVrEn4mk44R42u5GrqDaEVkOPR7s2ieXqXf-B3vONJ1gyRb2dQd1FY7_FISKKwpW_dxgV2K79YJGjovSppfWBH383TN97uu_4ALl48yvxcwdIM7vluLx84AQxeOUuiQkiqplt-sggTZtGE9qua4jqr4ZvubF-7ffqIUOKGzaolMjIIBLcdbHiFn7VJ9QS5P-pkV4lGWJZicGvGn3SWBYRaDTtlOycR788AMWfbZkIoYuJoQ3Xyt33Gj0JSGg5Tuaik9bBWDoQydon9of-fBqj)

Here's a video of that replicates the behavior described above.

https://github.com/microsoft/vscode/assets/12000736/474daefb-3587-44f4-b2aa-d9c760fd7201

As you can see the provide inline completions function is called each time (and always returns a single `test` inline completion item), but in the last case it does not get displayed.

**Comment by hediet** [comment]
Thanks for the repro, that helps a lot! I can verify the bug and will look at it soon.
