### ISSUE TITLE
Launching a fish shell in the terminal is raising an error about `fish_prompt` not existing

### ISSUE THREAD

**Issue by brettcannon** [microsoft/vscode#184191]
Type: <b>Bug</b>

I am seeing the following error when launching a new terminal with the fish shell:
```
functions: Function 'fish_prompt' does not exist

~/.vscode-server-insiders/bin/05ae089c791aa5c8ec05abd5687c9a31517579bc/out/vs/workbench/contrib/terminal/browser/media/fish_xdg_data/fish/vendor_conf.d/shellIntegration.fish (line 132): 
functions --copy fish_prompt __vsc_fish_prompt
^
from sourcing file ~/.vscode-server-insiders/bin/05ae089c791aa5c8ec05abd5687c9a31517579bc/out/vs/workbench/contrib/terminal/browser/media/fish_xdg_data/fish/vendor_conf.d/shellIntegration.fish
        called on line 248 of file /usr/share/fish/config.fish
from sourcing file /usr/share/fish/config.fish
        called during startup
```

The funny thing is I do have a `fish_prompt` defined at `~/.config/fish/functions/fish_prompt.fish`, so I suspect the fish shell integration is trying too soon and assuming that funcion is always defined at that point.

This is on fish 3.6.1.
```
❯ fish --version
fish, version 3.6.1
```

VS Code version: Code - Insiders 1.79.0-insider (05ae089c791aa5c8ec05abd5687c9a31517579bc, 2023-06-02T09:39:34.473Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Remote OS version: Linux x64 5.15.90.1-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.75GB (3.50GB free)|
|Process Argv|--crash-reporter-id 2f8216b4-0af9-4bf4-a156-6cdcff01b0ab|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 5.15.90.1-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz (8 x 2112)|
|Memory (System)|7.63GB (6.71GB free)|
|VM|0%|
</details><details><summary>Extensions (40)</summary>

Extension|Author (truncated)|Version
---|---|---
zephyr-asdl|bre|2021.5.0
codespaces|Git|1.14.7
remotehub|Git|0.57.2023060101
vscode-todo-highlight|jgc|2.0.8
remote-containers|ms-|0.294.0
remote-wsl|ms-|0.79.2
azure-repos|ms-|0.32.0
remote-repositories|ms-|0.35.2023060101
github-markdown-preview|bie|0.3.0
markdown-checkbox|bie|0.4.0
markdown-emoji|bie|0.3.0
markdown-footnotes|bie|0.1.1
markdown-preview-github-styles|bie|2.0.2
markdown-yaml-preamble|bie|0.1.0
wwbd|bre|2022.1.0
zephyr-asdl|bre|2021.5.0
vscode-eslint|dba|2.4.1
prettier-vscode|esb|9.13.0
vscode-diff|fab|1.4.2
copilot-chat|Git|0.1.2023060101
copilot-nightly|Git|1.88.135
remotehub|Git|0.57.2023060101
vscode-pull-request-github|Git|0.65.2023060209
symbols|mig|0.0.11
vscode-docker|ms-|1.25.1
python|ms-|2023.9.11521013
vscode-pylance|ms-|2023.5.51
jupyter|ms-|2023.5.1001541100
jupyter-renderers|ms-|1.0.15
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-slideshow|ms-|0.1.5
azure-repos|ms-|0.33.2023051101
cpptools|ms-|1.16.0
live-server|ms-|0.4.8
remote-repositories|ms-|0.35.2023060101
vscode-github-issue-notebooks|ms-|0.0.128
vscode-python-web-wasm|ms-|0.13.0
vscode-yaml|red|1.13.0
rust-analyzer|rus|0.3.1533
partial-diff|ryu|1.4.3

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256198
vslsvsres303:30308271
pythontb:30258533
pythonptprofiler:30281269
vsdfh931:30280409
vshan820:30294714
vscod805cf:30301675
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30404738
cppdebug:30492333
vscaat:30438846
vsclangdf:30492506
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30618038
pylantcb52:30590116
pyind779:30611226
pythonsymbol12:30651887
2i9eh265:30646982
showlangstatbar:30737417
pythonms35:30671666
03d35959:30757351
ecj1e332:30687743
pythonfmttext:30716741
pythoncmvfstr:30726892
fixshowwlkth:30724385
hidesbindicator:30724476
pythongtdpath:30726887
welcomedialog:30756234
pythonnosmt12:30757129

```

</details>

**Comment by meganrogge** [comment]
to reproduce:

- run `set fish_prompt` which will set it to undefined
- create a fish terminal
- you'll see the error above

**Comment by meganrogge** [comment]
Create a `fish` terminal and verify it does not have shell integration enabled. If you have a `fish_prompt` set, it should show. If not, you shouldn't see an error.
