### ISSUE TITLE
VSCode webview - Is it possible to make the VSCode Extension wait on the webview to be disposed of

### ISSUE THREAD

**Issue by davidkjackson54** [microsoft/vscode#184166]
Is there a documented method that explains how to make a VSCode Extension wait on an associated webview to be disposed of before allow the user to continue with the extension?
In my case, I have a treeview and I require certain information to be provided by the user. As this involves a number of fields to be provided, the cleanest approach is to use a webview. However, whilst the webview panel is presented, I don't want the user to continue to try to access the treeview as it is necessary to get the completed info back from the webview before proceeding

I am using the provided VSCode UI Toolkit.  I need to wait and block the  Extension from proceeding till the panel is disposed.

Regular VSCode showInputBox is easy as it allows to be `awaited` on.

**Comment by mjbvz** [comment]
Not currently possible. See https://github.com/microsoft/vscode/issues/66842

**Comment by davidkjackson54** [comment]
Without this functionality, it makes it rather useless for an extension that relies on a Webview to provide user input before proceeding.
Please reconsider this as a significant shortcoming that renders Webview for user input as somewhat unusable.
