### ISSUE TITLE
vscode.dev link with notebook cell fragment sometimes doesn't focus the right cell

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#184110]
Discussed in Slack

If I open this link 

https://insiders.vscode.dev/github/microsoft/vscode/blob/main/.vscode/notebooks/endgame.github-issues#C11:L1

then open this link

https://insiders.vscode.dev/github/microsoft/vscode/blob/main/.vscode/notebooks/endgame.github-issues#C23:L1

sometimes cell 11 is still selected instead of it selecting cell 23. Could be that notebook view state persistence is getting involved?

**Comment by joyceerhl** [comment]
I've alternately opened both those links 10 times and still can't repro this, @rebornix do you have any thoughts?

**Comment by joyceerhl** [comment]
I still can't repro this, optimistically closing. @roblourens feel free to reopen if this persists for you
