### ISSUE TITLE
Extension Marketplace Page: Support Emojis

### ISSUE THREAD

**Issue by jpoon** [Microsoft/vscode#1841]
It'd be nice to support emojis in the extension marketplace pages. For instance, on the VSCodeVim page: https://marketplace.visualstudio.com/items/vscodevim.vim:

This line:
> This project is maintained by a group of awesome contributors. Thank you! :heart:

Instead, the marketplace shows the literal string `:heart:`

(Definitely low priority but a nicety :smile: )

**Comment by egamma** [comment]
FYI @wadeanderson7

**Comment by wadeanderson7** [comment]
I have moved this to the marketplace backlog.

**Comment by jpoon** [comment]
Thanks! Seriously impressed at how on top of it you guys are with triaging these issues :+1:
