### ISSUE TITLE
Integrated Terminal Going Blank

### ISSUE THREAD

**Issue by mattnwa** [Microsoft/vscode#18415]
- VSCode Version: Code - Insiders 1.9.0-insider (b2d2a79da81853bff6e1c60876c9cee8582f9e61, 2017-01-11T07:09:02.740Z)
- OS Version: Darwin x64 15.6.0
- Extensions:

|Extension|Author|Version|
|---|---|---|
|vscode-ipaddress|Compulim|0.0.1|
|haml|atefth|0.0.1|
|vscode-ruby-ctags|otoniel-isidoro|1.4.1|
|gitblame|waderyan|1.3.0|

---

Steps to Reproduce:

1.Open Integrated Terminal
2. Use the drag to expand feature to change terminal height to more than half the screen and my terminal goes completely blank when I make the section smaller again.
![screen shot 2017-01-11 at 1 54 02 pm](https://cloud.githubusercontent.com/assets/13283053/21864029/72f8d09e-d805-11e6-9479-43686c813ef3.png)
. I can't cmd+K to reset the shell or enter anything. Opening a new terminal session and closing resets.

**Comment by Tyriar** [comment]
@mattnwa does this repro reliably for you? Also can you check the dev tools console (Help > Toggle Developer Tools) for any errors?

**Comment by mattnwa** [comment]
@Tyriar It throws the error I've attached here when I drag the terminal back down to the initial height. I can reproduce every time. Even after Vscode Restart. Thanks!

<img width="801" alt="screen shot 2017-01-11 at 3 34 19 pm" src="https://cloud.githubusercontent.com/assets/13283053/21867394/9bbaedc4-d813-11e6-9121-c24402fe760c.png">

**Comment by Tyriar** [comment]
Thanks that's perfect :smile:

**Comment by Tyriar** [comment]
I think it's related to zooming the window, @mattnwa do you think that could have been how you caused it?

**Comment by Tyriar** [comment]
Zooming seems to screw up the terminal row count as well. My current guess is that since a lot of stuff is now async, refreshes and resizes are being interleaved causing a race condition.

**Comment by mattnwa** [comment]
When I grab and drag the terminal height up past a couple inches and go back down is when it loses the window. I'd assume the logic for the refreshLoop might be causing this issue?

**Comment by Tyriar** [comment]
Yes the exception itself is within `refresh` (called by `refreshLoop`) but it appears to only happen when a `resize` happens, which leads me to believe it's a race condition.

I'm looking into this today as it's a pretty bad issue.

**Comment by Tyriar** [comment]
After many zoom ins/outs the prompt is really screwed up, particularly the line-height 
![image](https://cloud.githubusercontent.com/assets/2193314/21902623/79a4d1de-d8b1-11e6-8dcd-48bcf8217397.png)

**Comment by Tyriar** [comment]
Fixing https://github.com/sourcelair/xterm.js/issues/470 fixes the line-height issue, however there's still the `innerHTML` null reference exception:

![image](https://cloud.githubusercontent.com/assets/2193314/21903356/69f8cb2a-d8b4-11e6-8ec4-5e23f25098b9.png)

**Comment by Tyriar** [comment]
This fixes the other issue https://github.com/sourcelair/xterm.js/issues/473 (PR https://github.com/sourcelair/xterm.js/pull/474)

**Comment by mattnwa** [comment]
@Tyriar You rock! Thanks for such quick turnaround on this bug! Just updated my build and it is working perfectly!

**Comment by Tyriar** [comment]
Great to hear :smile:
