### ISSUE TITLE
File path problem

### ISSUE THREAD

**Issue by tokyoabc** [microsoft/vscode#184168]
https://github.com/microsoft/vscode/assets/96530884/e00239c3-f20f-4e8e-82a9-2abdfcb6df80

Type: <b>Feature Request</b>

I use HTML language for web design. When I use the a form to create a file path, I use a relative path that starts with ./ + type a few letters and press Enter to select that file, but suddenly one day when I type ./, instead of manually When automatically selecting the file, the cursor will automatically return to the line, I do not install any extension related to the file path. I have inserted a video about the problem I am having. I hope to help. Thank you.

VS Code version: Code 1.78.2 (b3e4e68a0bc097f0ae7907b217c1119af9e03435, 2023-05-10T14:39:26.248Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: Yes

**Comment by aeschli** [comment]
This is fixed in the latest build.

You were in template mode and enter of the code completion didn't work there.
