### ISSUE TITLE
Variable showing in editor as not accessed

### ISSUE THREAD

**Issue by enrique343** [microsoft/vscode#184263]
Type: <b>Bug</b>

I don't have any repro steps but I have seen this issue only in one file in my flask app.py file. It's a large amount of lists and variables in one function that appear as not accesed but I do i access the variables shortly after creation. The VSCode UI shows it never accessed and I don't know if this is a issue with VSCode or something in the python extension.

VS Code version: Code 1.78.2 (b3e4e68a0bc097f0ae7907b217c1119af9e03435, 2023-05-10T14:39:26.248Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2208)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.90GB (7.54GB free)|
|Process Argv|--crash-reporter-id a45f1be1-1eac-4217-9935-db5ae822f393|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (40)</summary>

Extension|Author (truncated)|Version
---|---|---
armview|ben|0.4.6
vscode-postgres|cko|1.4.2
doxdocgen|csc|1.4.0
better-cpp-syntax|jef|1.17.2
azure-pipelines|ms-|1.208.0
azure-dev|ms-|0.6.0
vscode-azureappservice|ms-|0.24.9
vscode-azurecognitivesearch|ms-|0.3.1
vscode-azurecontainerapps|ms-|0.5.1
vscode-azurefunctions|ms-|1.11.0
vscode-azureresourcegroups|ms-|0.7.5
vscode-azurestaticwebapps|ms-|0.12.1
vscode-azurestorage|ms-|0.15.2
vscode-azurevirtualmachines|ms-|0.6.5
vscode-bicep|ms-|0.17.1
vscode-cosmosdb|ms-|0.19.4
vscode-docker|ms-|1.25.1
vscode-dotnet-runtime|ms-|1.6.0
isort|ms-|2022.8.0
python|ms-|2023.8.0
vscode-pylance|ms-|2023.5.40
jupyter|ms-|2023.4.1011241018
jupyter-keymap|ms-|1.1.0
jupyter-renderers|ms-|1.0.15
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-slideshow|ms-|0.1.5
remote-containers|ms-|0.292.0
remote-ssh|ms-|0.102.0
remote-ssh-edit|ms-|0.86.0
remote-wsl|ms-|0.78.8
azure-account|ms-|0.11.5
azurecli|ms-|0.5.0
cmake-tools|ms-|1.14.31
cpptools|ms-|1.15.4
cpptools-extension-pack|ms-|1.3.0
remote-explorer|ms-|0.4.0
vscode-node-azure-pack|ms-|1.2.0
azurerm-vscode-tools|msa|0.15.10
vscode-data-preview|Ran|2.3.0
cmake|twx|0.0.17

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscoreces:30445986
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyonecf:30548226
3biah626:30602489
pyind779:30671433
89544117:30613380
pythonsymbol12:30671437
showlangstatbar:30737416
vsctsb:30748421
pythonms35:30701012
57b77579:30736110
pythonfmttext:30731395
fixshowwlkth:30730052
pythongtdpathcf:30739705

```

</details>

**Comment by enrique343** [comment]
Here's what I see the UI displaying
![image](https://github.com/microsoft/vscode/assets/54344743/1207bcba-99e1-4c64-b81e-972dfac5faec)

**Comment by roblourens** [comment]
Please file this on the python or pylance extension repos, thanks
