### ISSUE TITLE
Github Copilot: VSCode Get terminal output

### ISSUE THREAD

**Issue by kevinhassan** [microsoft/vscode#184232]
I would like to give Github copilot the possibility to access the output of the integrated terminal.
For example, if I launch tests and they're failed, I would like to click on Propose a fix for the bugs in my code or another entry to propose a solution or indicate to me how to investigate 🤔

I tried to ask it if it has rights to access to terminal output :

Me: can you access to terminal output?
Github Copilot: Yes, I can access the terminal output. Could you please provide me with the output of the npm run test command? This will help me to better understand the issue you are facing.

Github Copilot Chat : v0.1.2023060101
Github Copilot Nighly: v1.88.136

**Comment by Tyriar** [comment]
Copilot can actually access some terminal input right now, but it's view of the world in the terminal is not good. I'm starting the implementation for AI in the terminal in the June iteration

/duplicate https://github.com/microsoft/vscode/issues/184411
