### ISSUE TITLE
Shortcuts are intercepted by VS Code and not recognised by system

### ISSUE THREAD

**Issue by BohdanCh-w** [microsoft/vscode#184282]
Type: <b>Bug</b>

I use Logi Options+ v1.42.411539 (latest version) to customize mouse buttons 4 and 5 (initially "back" and "forward"). They are set to switch between virtual desktops in Windows: `Ctrl + Win + Left Arrow` and `Ctrl + Win + Right Arrow`.

Whenever I try to use these buttons to switch to another desktop VS Code intercepts it and switches between tabs - back and forward.

This issue appeared about 1-2 weeks ago. Though I use same setup for more than half a year.

I already tried disabling all extensions, but it still reproduces.

Probably unrelated, but I have other Logitech product, specifically keyboard. It also has custom shortcuts via Logi Options+, which work without problems. But probably its because they are not standart on all keyboards (`App menu` by default)

VS Code version: Code 1.78.2 (b3e4e68a0bc097f0ae7907b217c1119af9e03435, 2023-05-10T14:39:26.248Z)
OS version: Windows_NT x64 10.0.19045
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E3-1505M v5 @ 2.80GHz (8 x 2808)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.92GB (5.37GB free)|
|Process Argv|--crash-reporter-id 904b3485-4189-4a67-af23-de4f0b7d3784|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-diff|fab|1.4.2
go|gol|0.38.0
mypy|mat|0.2.3
jupyter-keymap|ms-|1.1.0
remote-ssh|ms-|0.102.0
live-server|ms-|0.4.8
vscode-thunder-client|ran|2.7.4
vscode-coverage-gutters|rya|2.10.4
tabnine-vscode|Tab|3.6.51
doki-theme|unt|88.1.15
vscode-icons|vsc|12.4.0
vscode-postfix-go|yok|0.0.12
markdown-all-in-one|yzh|3.5.1

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vscaat:30438848
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
vscccc:30610679
282f8724:30602487
pyind779:30671433
89544117:30613380
pythonsymbol12:30671437
showlangstatbar:30737416
vsctsb:30748421
pythonms35:30701012
a2ce3375:30757347
pythonfmttext:30731395
pythoncmv:30756943
fixshowwlkth:30730052
showsbindicator:30730056
pythongtdpath:30739704

```

</details>

**Comment by ulugbekna** [comment]
> Whenever I try to use these buttons to switch to another desktop VS Code intercepts it and switches between tabs - back and forward.

I also use logi options+ and had this issue. This is caused by logi options+ having shortcuts for these mouse buttons specifically for vscode, as far as I know. You can disable this from logi options+.
