### ISSUE TITLE
PowerShell opens instead of cmd.exe as of 1.78.2 (wasn't a problem in 1.77.3)

### ISSUE THREAD

**Issue by SamuelMarks** [microsoft/vscode#184223]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.78.2
- OS Version: Windows 11 22621.1778

Steps to Reproduce:

1. Same setting as before
![image](https://github.com/microsoft/vscode/assets/807580/d2e78e01-06bd-4c15-bf54-9c3d77ea6af0)

2. <kbd>Ctrl</kdb>+<kbd>`</kdb>

3. 
![image](https://github.com/microsoft/vscode/assets/807580/49871460-4ffd-4ea7-89fa-5015702b9b80)

**Comment by meganrogge** [comment]
similar #179958

**Comment by meganrogge** [comment]
that setting applies to the external terminal whereas ctrl backtick opens an integrated terminal

**Comment by SamuelMarks** [comment]
@meganrogge Well regardless on old VS Code it would open Command Prompt. How do I get back to that standard?

**Comment by Tyriar** [comment]
@SamuelMarks select your default profile here:

![image](https://github.com/microsoft/vscode/assets/2193314/e488e08c-c820-4675-9e95-af006ebeba9e)
