### ISSUE TITLE
Python theme broken

### ISSUE THREAD

**Issue by connorwilloughby** [microsoft/vscode#184245]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: Multiple versions (1.76.2, 1.77.3, 1.78.2)
- OS Version:  Windows 10.0.19045 N/A Build 19045

Steps to Reproduce: 

1. Open any .py file

Additional Info:

Seems that regardless of the three versions above or with extensions disabled the theming for python files is dramatically limited. Please see SC:

![image](https://github.com/microsoft/vscode/assets/41489250/5734eed8-0493-472a-af42-862aff4f04e2)

This is a regression as typically variables / functions and imports will each receive a specific format style. 

Please note that the python (Microsoft) extension has also been enabled at multiple versions in order to test issues and many of them still appear to be failing. 

This also has happened across multiple themes including dark, dark+ and dark modern

**Comment by mo1878** [comment]
I'm having the same issue on my IDE

**Comment by connorwilloughby** [comment]
Resolved by adding pylance language server to the settings.json for each project. 

```json
    "python.languageServer": "Pylance",
```
