### ISSUE TITLE
"Tweet us your feedback"

### ISSUE THREAD

**Issue by SRNissen** [microsoft/vscode#184238]
Type: <b>Bug</b>

Click feedback 

Enter any feedback

Look at the button

Expected result:

Button says "Submit feedback"

Actual result:

Button says "Tweet"

VS Code version: Code 1.78.2 (b3e4e68a0bc097f0ae7907b217c1119af9e03435, 2023-05-10T14:47:05.613Z)
OS version: Linux x64 6.2.6-76060206-generic
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 2999)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|2, 2, 2|
|Memory (System)|15.38GB (2.91GB free)|
|Process Argv|--unity-launch /home/srnissen/repos/LinkLogisticsIT/InvoiceControl/InvoiceControl.UnitTests/Resources/Specifikation faktura 150189241.postnorddk.csv --crash-reporter-id 2cdaf423-f4f3-44dc-b7af-3f0ac1b06e51|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|pop|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|pop|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
aws-toolkit-vscode|ama|1.76.0
go|gol|0.38.0
vscode-graphviz|joa|0.0.6
csharp|ms-|1.25.8
cmake-tools|ms-|1.14.31
cpptools|ms-|1.15.4
cpptools-extension-pack|ms-|1.3.0
kb-macro|tsh|0.13.4
cmake|twx|0.0.17

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vscaat:30438848
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
3biah626:30602489
pyind779:30671433
f6dab269:30613381
pythonsymbol12:30671437
showlangstatbar:30737416
vsctsb:30748421
pythonms35:30701012
03d35959:30757346
pythonfmttext:30731395
pythoncmv:30756943
fixshowwlkth:30730052
showsbindicator:30730056
pythongtdpath:30739704

```

</details>

**Comment by TylerLeonhardt** [comment]
Tweet is very common terminology on Twitter. That's what the button on Twitter says.
<img width="621" alt="image" src="https://github.com/microsoft/vscode/assets/2644648/9ffc0311-dbca-42d2-85c5-bdacf475c8ec">

I think the way it is is more consistent.

**Comment by SRNissen** [comment]
> Tweet is very common terminology on Twitter

Yes, this is the problem. It might accidentally give the user the impression that they are writing a tweet when they are actually trying to submit feedback for their code editor.
