### ISSUE TITLE
cin is ambigous

### ISSUE THREAD

**Issue by singh3abhi** [microsoft/vscode#184280]
Type: <b>Bug</b>

Hello i was coding in cpp and I just noticed that whenever I wrote cin, it started showing "cin is ambiguous" on all the cin's and similarly for cout
When I rescan the IntelliSense the error goes away, although the red errors do not cause any trouble in running the code but they are just annoying, can anyone help me get rid of this problem

VS Code version: Code 1.78.2 (b3e4e68a0bc097f0ae7907b217c1119af9e03435, 2023-05-10T14:39:26.248Z)
OS version: Windows_NT x64 10.0.19045
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 3600 6-Core Processor               (12 x 3600)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.93GB (9.15GB free)|
|Process Argv|D:\\Coding\\Codeforces --crash-reporter-id 2bfd9e03-bf87-4275-beb2-f26455026637|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (51)</summary>

Extension|Author (truncated)|Version
---|---|---
es7-javascript-class-snippets|abr|0.4.0
TabOut|alb|0.2.2
run|Alb|2.0.1
npm-intellisense|chr|1.4.4
path-intellisense|chr|2.8.4
doxdocgen|csc|1.4.0
dart-code|Dar|3.66.0
flutter|Dar|3.66.0
vscode-eslint|dba|2.4.0
snippet|dev|1.1.0
competitive-programming-helper|Div|5.11.0
xml|Dot|2.5.1
vscode-npm-script|eg2|0.3.29
prettier-vscode|esb|9.13.0
auto-close-tag|for|0.5.14
auto-rename-tag|for|0.1.10
code-runner|for|0.12.0
mayukaithemevsc|Gul|3.2.4
json-to-dart|hir|3.5.8
dart-data-class-generator|hzg|0.5.4
search-node-modules|jas|1.3.0
better-cpp-syntax|jef|1.17.2
vscode-gutter-preview|kis|0.30.0
mongodb-vscode|mon|1.0.1
isort|ms-|2022.8.0
python|ms-|2023.8.0
vscode-pylance|ms-|2023.5.50
jupyter|ms-|2023.4.1011241018
jupyter-keymap|ms-|1.1.0
jupyter-renderers|ms-|1.0.15
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-slideshow|ms-|0.1.5
remote-containers|ms-|0.292.0
remote-ssh|ms-|0.102.0
remote-wsl|ms-|0.78.9
cmake-tools|ms-|1.14.31
cpptools|ms-|1.16.0
cpptools-extension-pack|ms-|1.3.0
remote-explorer|ms-|0.4.0
jsontodart|Muh|0.2.2
awesome-flutter-snippets|Nas|4.0.1
color-highlight|nau|2.5.0
dart-syntax-highlighting-only|osc|1.0.1
material-icon-theme|PKi|4.28.0
quicktype|qui|12.0.46
LiveServer|rit|5.7.9
pdf|tom|1.2.2
cmake|twx|0.0.17
nodejs-extension-pack|wad|0.1.9
JavaScriptSnippets|xab|1.8.0
material-theme|zhu|3.15.15

(6 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263:30335439
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
282f8724:30602487
pyind779:30671433
f6dab269:30613381
vscrp:30673768
pythonsymbol12:30671437
showlangstatbar:30737416
vsctsb:30748421
pythonms35:30701012
03d35959:30757346
pythonfmttext:30731395
pythoncmv:30756943
fixshowwlkth:30730052
showsbindicator:30730056
pythongtdpathcf:30739705
pythonnosmt12:30757131

```

</details>

**Comment by roblourens** [comment]
Please file this on the C++ extension that this error is coming from
