### ISSUE TITLE
ayuda

### ISSUE THREAD

**Issue by AstriDanielaCastellanos** [microsoft/vscode#184211]
Type: <b>Feature Request</b>

no aparece al opción crear un nuevo proyecto

VS Code version: Code 1.78.2 (b3e4e68a0bc097f0ae7907b217c1119af9e03435, 2023-05-10T14:39:26.248Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: Yes

**Comment by aiday-mar** [comment]
Hi, in order to create a new project, you may go to Edit > New Window, then Edit > New File, in order to create your first project file
