### ISSUE TITLE
Go full screen with focused tab in editor window.

### ISSUE THREAD

**Issue by BobbyBabes** [Microsoft/vscode#18421]
```
Version 1.8.1
Commit ee428b0eead68bf0fb99ab5fdc4439be227b6281
Date 2016-12-19T14:41:20.664Z
Shell 1.4.6
Renderer 53.0.2785.143
Node 6.5.0
```

I checked the keyboard shortcuts but couldn't find this functionality. And also couldn't find it when going through the menus.
https://code.visualstudio.com/shortcuts/keyboard-shortcuts-linux.pdf

When I have 2+ editor windows opened side-by-side, I would want to go full screen with the editor tab that is focused, and back. For example by pressing Ctrl+F11.

Example of starting point as in screenshot. I want to go full screen with the focused editor tab (name in title bar) in the middle editor window. Full screen as in : just take up the place of the other 2 editor windows. Not Zen mode.

Could you please add this?

![vscode-is-it-possible-to-go-fullscreen-with-one-tab_cropped](https://cloud.githubusercontent.com/assets/22870070/21868160/ce86043a-d851-11e6-9293-db3e6126dc3d.png)

**Comment by bpasero** [comment]
Dupe: centered editor layout

**Comment by BobbyBabes** [comment]
I looked up that issue : https://github.com/Microsoft/vscode/issues/1568 That's a request for Zen mode.
I did write :
> Not Zen mode.
