### ISSUE TITLE
Markdown extensions won't work after installation until window reload

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#184295]
* Install bierner.markdown-preview-github-styles on github.dev
* Preview markdown
* `[ ]` is not rendered until window reload

I didn't see a "reload" button for the markdown extension after installing it so I would expect it to work immediately.

**Comment by mjbvz** [comment]
We support this for markdown css and script extensions. However it's currently not supported for syntax extensions (which is needed to render `- [ ]`
