### ISSUE TITLE
ubuntu, v0.10.6, tab works "too" hard in find/replace mode

### ISSUE THREAD

**Issue by innerlee** [Microsoft/vscode#1842]
reproduce:

1. ctrl+f
2. tab

The focus go from search box to replace box, as we wish. However, the main text also being wrongly tabbed.

Works normal in windows version. Thanks.

**Comment by alexandrudima** [comment]
I cannot reproduce this anymore in 0.10.7, I did quite some work in the tab/shift-tab handling in the find widget that I think fixed this one.
