### ISSUE TITLE
Wrong reference count in code lens

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#18425]
- VSCode Version: Code - Insiders 1.9.0-insider (b2d2a79da81853bff6e1c60876c9cee8582f9e61, 2017-01-11T07:09:02.740Z)
- OS Version: Darwin x64 15.6.0
- Extensions:

|Extension|Author|Version|
|---|---|---|
|EditorConfig|EditorConfig|0.3.4|
|autofilename|JerryHong|0.1.3|
|vscode-docker|PeterJausovec|0.0.7|
|azure-cli|chrmarti|0.2.0|
|regex|chrmarti|0.0.7|
|vscode-eslint|dbaeumer|1.1.0|
|ghlink|dt|0.0.4|
|tslint|eg2|0.6.0|
|vscode-scss|mrmlnc|0.6.0|
|PowerShell|ms-vscode|0.7.2|
|cpptools|ms-vscode|0.9.3|
|debugger-for-chrome|msjsdiag|2.2.2|
|diff|rafaelmaiolla|0.0.1|
|vscode-open-in-github|sysoev|1.2.1|

---

Not sure what triggers it, a simple example did not reproduce it:
![screen shot 2017-01-11 at 4 04 09 pm](https://cloud.githubusercontent.com/assets/9205389/21871630/4204f3b0-d818-11e6-98ad-bc108b0555af.png)

**Comment by mjbvz** [comment]
@chrmarti Thanks for reporting this. Quick question: if you reload vscode, does the bad reference count still show up?

**Comment by chrmarti** [comment]
Yes, it is the same.

**Comment by chrmarti** [comment]
This reproduces it:
```
export class A {
	public a() {
		const input = b();
	}
}

export function b() {
}
```

Funny: Using `let` instead of `const` or changing the variable name `input` to something else makes the refcount go to 1.

**Comment by chrmarti** [comment]
More fun, this shows 0 references on `c()`:
```
export class A {

	b() {
		if (true) {
			if (true) {
				this.c();
			}
		}
	}

	private c() {
	}
}
```

Decreasing the indentation of the `this.c();` line by one step makes the refcount go to 1.
