### ISSUE TITLE
vscode showing a nonexistent  parse error 

### ISSUE THREAD

**Issue by moe123** [Microsoft/vscode#18423]
- VSCode Version: Code 1.8.1 (ee428b0eead68bf0fb99ab5fdc4439be227b6281, 2016-12-19T14:42:49.304Z)
- OS Version: Darwin x64 15.6.0

Steps to Reproduce:

1. copy https://github.com/moe123/abraxas/blob/master/scl/bits/scl_base_iterator_traits.php
2. launch vscode

<img width="691" alt="screen shot 2017-01-11 at 2 42 06 pm" src="https://cloud.githubusercontent.com/assets/19998532/21869367/284cd7aa-d80c-11e6-8f79-c8978eff5a6b.png">

<img width="587" alt="screen shot 2017-01-11 at 3 32 34 pm" src="https://cloud.githubusercontent.com/assets/19998532/21870845/53d9d3d0-d813-11e6-9a38-3eb70b4b76f8.png">

<img width="524" alt="screen shot 2017-01-11 at 3 32 53 pm" src="https://cloud.githubusercontent.com/assets/19998532/21870846/57ad5892-d813-11e6-847f-372d7711cacc.png">

<img width="687" alt="screen shot 2017-01-11 at 3 33 16 pm" src="https://cloud.githubusercontent.com/assets/19998532/21870848/5a41b8a0-d813-11e6-8d8b-5d806ca465c3.png">

<img width="640" alt="screen shot 2017-01-11 at 3 37 58 pm" src="https://cloud.githubusercontent.com/assets/19998532/21870953/034a0a42-d814-11e6-995e-9d788089b00b.png">

**Comment by mattacosta** [comment]
If I had to guess I'd say that you need to make sure that your "php.validate.executablePath" setting is pointing to a PHP 7 executable. Otherwise vscode is probably using some default 5.x version it found after poking around your system paths...

**Comment by moe123** [comment]
@mattacosta, hello, thank you for your interest  in this issue and yes you are completely right, setting up properly the default interpreter path fixed it!, however, vscode folks should handle the matter by enforcing the use of `which` (i.e `which` -- locate a program file in the user's path) command.
