### ISSUE TITLE
when use ^- the focus is not currect

### ISSUE THREAD

**Issue by lang2858** [Microsoft/vscode#18435]
- VSCode Version: Code 1.8.1 (ee428b0eead68bf0fb99ab5fdc4439be227b6281, 2016-12-19T14:42:49.304Z)
- OS Version: Darwin x64 16.3.0
- Extensions:

|Extension|Author|Version|
|---|---|---|
|cocos-creator|Chukong Technologies|0.0.1|
|cocos-debug|Chukong Technology|0.0.1|
|python|donjayamanne|0.5.5|
|cpptools|ms-vscode|0.9.3|

---

Steps to Reproduce:

1. use command+\ split editor , open same file both left and right window
2. operate at left, then use ^- return, the focus run to right

**Comment by bpasero** [comment]
@lang2858 can you find out what command runs when you press that key?
