### ISSUE TITLE
Region fold not working in GO

### ISSUE THREAD

**Issue by yardengp** [microsoft/vscode#184394]
Type: <b>Bug</b>

The region is not folding in GO files.... only folding when there is no code in the region
```golang
package main

func main() {
	// #region New Region
	// when any code is used... the folding is not working
	variable := 1001
	// #endregion
}
```

VS Code version: Code 1.78.2 (b3e4e68a0bc097f0ae7907b217c1119af9e03435, 2023-05-10T14:39:26.248Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: Yes

**Comment by aeschli** [comment]
Are you using the go extension? I believe it lacks support for regions. The issue is https://github.com/golang/vscode-go/issues/134
