### ISSUE TITLE
Adopt EnvironmentVariableCollection.description in git extension

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#184331]
There's a new API (https://github.com/microsoft/vscode/issues/171108) being finalized this month that allows extensions to explain why it's changing environment variables. Adopting this will show additional information when hovering a terminal tab

API:

https://github.com/microsoft/vscode/blob/e6936ce0ab10bc9fb3ec220db3c4304bdd909292/src/vscode-dts/vscode.proposed.envCollectionWorkspace.d.ts#L27-L33

Current:

![image](https://github.com/microsoft/vscode/assets/2193314/bafd9d70-797b-4230-af39-dafdb6b97d7a)

After description:

![image](https://github.com/microsoft/vscode/assets/2193314/3ff3bd57-b4e8-4b54-be0e-8b5996cab8b0)

cc @karrtikr

**Comment by lszomoru** [comment]
@Tyriar, will you create a test plan item or add verification steps for this? Thanks!
