### ISSUE TITLE
Tab as Space

### ISSUE THREAD

**Issue by PauloPintor** [microsoft/vscode#184344]
Type: <b>Bug</b>

Hei,

I have the "editor.renderWhitespace" (selection) on, to see spaces, tabs, etc. Although, if I put a space or multplie spaces I see dots, and if I use the tabs I also see dots. And I have the option: Insert Spaces off. 

I am using the VS Code to code in JAVA.

Best regards

VS Code version: Code - Insiders 1.79.0-insider (Universal) (666396ddec7708df2b986dcc178863faaa67c14d, 2023-06-05T14:15:13.024Z)
OS version: Darwin arm64 22.5.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M2 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|10, 7, 5|
|Memory (System)|16.00GB (0.07GB free)|
|Process Argv|--crash-reporter-id 7cfd6414-b0c2-462e-839b-e04a620b9427|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (20)</summary>

Extension|Author (truncated)|Version
---|---|---
regex|chr|0.4.0
prettier-vscode|esb|9.13.0
copilot|Git|1.88.132
todo-tree|Gru|0.0.226
latex-workshop|Jam|9.11.4
javadoc-tools|mad|1.6.0
python|ms-|2023.9.11561008
vscode-pylance|ms-|2023.5.51
fabric8-analytics|red|0.3.10
java|red|1.19.0
latex-utilities|tec|0.4.11
intellicode-api-usage-examples|Vis|0.2.7
vscodeintellicode|Vis|1.2.30
vscode-java-debug|vsc|0.51.0
vscode-java-dependency|vsc|0.23.0
vscode-java-pack|vsc|0.25.11
vscode-java-test|vsc|0.39.0
vscode-maven|vsc|0.41.0
vscode-icons|vsc|12.4.0
grammarly|znc|0.23.15

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythontb:30258533
pythonptprofiler:30281269
vshan820:30294714
vscod805cf:30301675
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30404738
py29gd2263:30754469
cppdebug:30492333
vsclangdf:30492506
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30618038
pylantcb52:30590116
pyind779:30611226
pythonsymbol12:30651887
a9j8j154:30646983
showlangstatbar:30737417
pythonms35:30671666
03d35959:30757351
ecj1e332:30687743
pythonfmttext:30716741
pythoncmvfstr:30726892
fixshowwlkth:30724385
showsbindicator:30724477
pythongtdpath:30726887
pythonnosmt12:30757129

```

</details>

**Comment by aiday-mar** [comment]
Hi thank you for filing the issue. Could you please inform us more clearly what is the issue or your expected output?

**Comment by PauloPintor** [comment]
Hi,

Yes ofc.

<img width="667" alt="Captura de ecrã 2023-06-05, às 21 21 25" src="https://github.com/microsoft/vscode/assets/12814875/4475b5d1-60a7-42f3-af2f-ecd77a3fafd7">

In the image, you have dots and arrows. Dots for spaces, arrows for tabs. But since some updates, everything is "dots". If I press a tab it appears dots. If I press, space appears dots.

And I would like to have it like on the image to distinguish the things on I select the text.

**Comment by PauloPintor** [comment]
Hi,

I already find the "problem". I don't know if this is an issue or if it is the right behaviour. If we set the option - "editor.detectIndentation" - true, the tabs symbol changes to spaces symbols consequently all new tabs are considered spaces, as I showed in the image.
