### ISSUE TITLE
bad experience when switching to an empty profile with a github-issues notebook open 

### ISSUE THREAD

**Issue by amunger** [microsoft/vscode#184355]
@amunger fyi I just created https://github.com/microsoft/vscode/issues/184142 which is a similar issue for custom editors.
...
* if the EH restarts and there is no more extension for the notebook editor, turn the notebook readonly and inform the user somehow

_Originally posted by @bpasero in https://github.com/microsoft/vscode/issues/183854#issuecomment-1573388742_

**Comment by bpasero** [comment]
I reflected my points in the more complete https://github.com/microsoft/vscode/issues/184496
