### ISSUE TITLE
ctrl + s didn't save anything

### ISSUE THREAD

**Issue by tcdona** [Microsoft/vscode#18437]
- VSCode Version: Code - Insiders 1.9.0-insider (b2d2a79da81853bff6e1c60876c9cee8582f9e61, 2017-01-11T07:15:12.230Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions:

|Extension|Author|Version|
|---|---|---|
|htmltagwrap|bradgashler|0.0.3|
|expand-region|letrieu|0.0.2|
|sample-ext|RolandGreim|0.0.2|
|textcraft|yolio2003|0.0.8|

---

Steps to Reproduce:

If you do not modify the code, the editor will not save anything. 
But I need an editor to change the last modify time.
I think it's over optimized

**Comment by bpasero** [comment]
@tcdona the last modified time is updated when you save, even if the file is not dirty.
