### ISSUE TITLE
Recent files (not folders) support in Visual Code?

### ISSUE THREAD

**Issue by hanhpho** [Microsoft/vscode#1843]
Hi team,

I'm wondering is there a feature (or future feature) to show the list of the latest opened files, so you can go back a recent file when you're working with many files at a time and don't wanna keep so many tabs.

Like the **[Recently opened file](https://www.jetbrains.com/pycharm/help/navigating-to-recent-file.html#d867862e114)** feature in Inteliij

**Comment by joaomoreno** [comment]
<kbd>Ctrl E</kbd> (<kbd>⌘E</kbd> on Mac) will open **quick open**. This widget will not only let you open any file in your workspace, but also show you the list of your previously opened files.

**Bonus tip:** holding <kbd>Ctrl</kbd> (or <kbd>⌘</kbd>), pressing <kbd>E</kbd> multiple times and releasing <kbd>Ctrl</kbd> (or <kbd>⌘</kbd>) gives you the feature of **quick navigate** in that very same history. It's my bread and butter.

**Comment by hanhpho** [comment]
@joaomoreno That's awesome, didn't know that, thank you man :+1: :)

**Comment by joaomoreno** [comment]
@chrisdias It seems that we should write a Navigation blog post, highlighting the exceptional Code features in this area.

**Comment by chrisdias** [comment]
great idea, created https://github.com/Microsoft/vscode-docs/issues/109 and assigned that bug to @gregvanl

**Comment by haifzhan** [comment]
use Ctrl + Tab will list the recent opened files  https://code.visualstudio.com/docs/editor/editingevolved

**Comment by lawreenas** [comment]
@haifzhan `ctrl+tab` gives a list of *all files open* in an editor group, not recelty opened.
