### ISSUE TITLE
localStorage access is slow

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#18439]
* `scripts\code.sh`
* hide viewlet
* close all editors
* restart profiler, reload, stop profiler
* 🐌 you see 135ms spend in `index.html` reading the theme from local storage (I assume the times vary with the size/history of the workspace)

![screen shot 2017-01-12 at 10 56 47](https://cloud.githubusercontent.com/assets/1794099/21884965/e69c5f42-d8b5-11e6-97bf-c779a15fdbb5.png)

[CPU-20170112T105633.cpuprofile.zip](https://github.com/Microsoft/vscode/files/701266/CPU-20170112T105633.cpuprofile.zip)

**Comment by bpasero** [comment]
For more reasons that just performance, local storage should be file based.

**Comment by jrieken** [comment]
How is this upstream? Surly local storage is file based (how else should it work) the problem is that we need to load *all* of local storage to ready a single value. That the local storage API and I don't see that changing. I think we should just stop using locale storage and implement our own storage mechanism.

**Comment by jrieken** [comment]
<img width="591" alt="screen shot 2017-11-02 at 17 32 23" src="https://user-images.githubusercontent.com/1794099/32337997-cf61a38e-bff3-11e7-855d-ead468e2c555.png">

`StorageService#setWorkspaceId` "nicely" exposes this and blocks startup

**Comment by jrieken** [comment]
Simple expertement I ran is to start with `code-insiders --prof-startup`, one time with the `LocalStorage` folder as it is today (for me ~9MB) and once with a fresh, empty folder. Different is around ~150ms.

**with data**
<img width="892" alt="screen shot 2017-12-01 at 16 33 32" src="https://user-images.githubusercontent.com/1794099/33489976-da823480-d6b5-11e7-89b9-4878abaff57f.png">

**without data**
<img width="623" alt="screen shot 2017-12-01 at 16 36 16" src="https://user-images.githubusercontent.com/1794099/33489977-da9ae5d4-d6b5-11e7-82d2-080b58f33c44.png">

**Comment by jrieken** [comment]
@bpasero Unrelated question: what does `cleanupWorkspace` do and why does it run every time I open a workspace and why does everything need to wait for this?

**Comment by bpasero** [comment]
@jrieken I think it is just the first guy who uses local storage that pays the price of it. If I remove that call, the next one hits it right after:

![image](https://user-images.githubusercontent.com/900690/33494020-339172fa-d6c2-11e7-9a22-16863bd21dea.png)

The cleanup is useful in cases where a folder was deleted and then recreated with the same name. We store the `ctime` of a folder in local storage and compare it to the `ctime` of the folder that is opened. If the path is the same but the `ctime` different, we clear all storage for that workspace early on assuming that the folder was deleted and recreated.

**Comment by bpasero** [comment]
Via https://github.com/Microsoft/vscode/pull/64719, we are not using `window.localStorage` anymore.
