### ISSUE TITLE
Slow scrolling in terminal

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#184374]
A couple times recently I've noticed scrolling in the terminal start to feel laggy. Here it just happened after running this command `GIT_TRACE2_PERF=1  git commit -m "test"` which writes some sort of wide lines. But the terminal doesn't even have very much history in it.

[slow-term-scroll.json.zip](https://github.com/microsoft/vscode/files/11658563/slow-term-scroll.json.zip)

It seems like it started rendering a bit slowly

**Comment by meganrogge** [comment]
Are you on a remote when this happens? 

what's your value for `terminal.integrated.scrollback`?

does changing `terminal.integrated.gpuAcceleration` help?

**Comment by roblourens** [comment]
Not a remote, scrollback is the default. Oh, I had gpuAcceleration off from investigating some other bug. I just turned it on and scrolling was much faster. I don't know if it's expected to be that bad with that setting off.

**Comment by meganrogge** [comment]
Yep, `dom` and `canvas` are slower
