### ISSUE TITLE
LaTex Math render is totally not working on Jupyter

### ISSUE THREAD

**Issue by littlecube8152** [microsoft/vscode#184329]
Type: <b>Bug</b>

1. Enter any simple math enclosed with dollars (`$`) or double dollars (`$$`).
2. See it rendered as plain text.

Already tried disabling all extensions, enabling only notebook ones and enable notebook and markdown ones. None of them works after reload VSCode.

VS Code version: Code 1.78.2 (b3e4e68a0bc097f0ae7907b217c1119af9e03435, 2023-05-10T14:39:26.248Z)
OS version: Windows_NT x64 10.0.19044
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-10300H CPU @ 2.50GHz (8 x 2496)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.87GB (8.44GB free)|
|Process Argv|--crash-reporter-id 118cc4cd-f5f1-4b7b-b0dc-2d967370118f|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
language-julia|jul|1.47.2
python|ms-|2023.8.0
jupyter|ms-|2023.4.1011241018
jupyter-keymap|ms-|1.1.0
jupyter-renderers|ms-|1.0.15
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-slideshow|ms-|0.1.5
markdown-all-in-one|yzh|3.5.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes516:30244333
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263:30335439
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
3biah626:30602489
pyind779:30671433
89544117:30613380
pythonsymbol12:30671437
2i9eh265:30646982
showlangstatbar:30737416
vsctsb:30748421
pythonms35:30701012
03d35959:30757346
pythonfmttext:30731395
pythoncmv:30756943
fixshowwlkth:30730052
pythongtdpath:30739704

```

</details>

**Comment by littlecube8152** [comment]
Screenshots:

Code:
![image](https://github.com/microsoft/vscode/assets/73371510/45d81110-0b63-481b-ba9b-c11417fab743)

Display:
![image](https://github.com/microsoft/vscode/assets/73371510/34ed3af1-6066-49f6-8388-6543f100998a)

**Comment by mjbvz** [comment]
Please share an example notebook file which demonstrate the issue

**Comment by littlecube8152** [comment]
The following code in my workspace won't render LaTeX math:
```ipynb
{
 "cells": [
  {
   "attachments": {},
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "$a$"
   ]
  },
  {
   "attachments": {},
   "cell_type": "markdown",
   "metadata": {},
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "file_extension": ".jl",
   "mimetype": "application/julia",
   "name": "python",
   "version": "3.9.2"
  },
  "orig_nbformat": 4
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
```

[The math display example notebook](https://github.com/jupyter/notebook/blob/57fcc413b4cd8e2c15d3fd4d14f79f3f339cfd12/docs/source/examples/Notebook/Typesetting%20Equations.ipynb) also doesn't work. It is not like some equation is not rendering, it is all of the math blocks are not rendering.

**Comment by mjbvz** [comment]
Did you disable the builtin markdown math extension? Search `@builtin math` in the extensions view to check

**Comment by littlecube8152** [comment]
Now it is rendered perfectly. Thanks for the help!
