### ISSUE TITLE
Insufficient gap between viewlet content and scrollbar

### ISSUE THREAD

**Issue by keyiis** [Microsoft/vscode#18431]
- VSCode Version:1.8.1
- OS Version:win10 x64
The left scrollbar and file item selected area are too closed,when i drag scrollBar then offen tigger item selected event
![qq 20170112103408](https://cloud.githubusercontent.com/assets/7766085/21874877/ce50c372-d8b2-11e6-96ed-5abd1818c20d.jpg)

i hope as below
![qq 20170112104454](https://cloud.githubusercontent.com/assets/7766085/21875091/41c8fb66-d8b4-11e6-96ff-d81c43c695c2.jpg)

**Comment by bpasero** [comment]
This feature request will not be considered in the next [6-12 months roadmap](https://github.com/Microsoft/vscode/wiki/Roadmap) and as such will be closed to keep the number of issues we have to maintain actionable. Thanks for understanding and happy coding!
