### ISSUE TITLE
Insiders 1.79.0 broke statusbar functionality - Tasks extension can only show single task now

### ISSUE THREAD

**Issue by ThaDaVos** [microsoft/vscode#184395]
Does this issue occur when all extensions are disabled?: Yes/No
No, as it's related to a specific extension - one cannot disable all extensions and still see the issue

- VS Code Version: 1.79.0 (commit: a8e719eeed4dac1f59fc2e48ed00545c0acafc42)
- OS Version: Windows_NT x64 10.0.25381

Steps to Reproduce:

1. Install `actboy168.tasks`
2. Configure multiple tasks in the task.json
3. Only the last task is shown in the taskbar in the latest insiders version (since about 31th of May) - all tasks are shown in the normal vscode versions

**Comment by ThaDaVos** [comment]
Related to: https://github.com/actboy168/vscode-tasks/issues/44
As I was asked to create an issue here instead of on the extensions github

**Comment by meganrogge** [comment]
thanks for the issue, can you clarify with a screenshot what you mean by taskbar?

**Comment by meganrogge** [comment]
if you mean the status bar, this is working for me - I run 2 separate tasks (1 that has 2 dependent ones) and see 3 in the status bar

![Screenshot 2023-06-07 at 7 56 36 AM](https://github.com/microsoft/vscode/assets/29464607/2390fa13-2228-446d-a42f-90460939bf16)

**Comment by ThaDaVos** [comment]
Yeah the statusbar - but that specific plugin adds multiple tasks to the statusbar so they can be clicked and run - but since the specified insiders build of vscode - it seems to be broken as it only shows a single one

**Comment by ThaDaVos** [comment]
I am talking about the yellow marked parts - top is stable and bottom is insiders:
![afbeelding](https://github.com/microsoft/vscode/assets/5251028/6a9e66a7-343b-4bf9-b3b6-7032189e391e)

As you can see, insiders only shows the last one

**Comment by meganrogge** [comment]
@bpasero has anything changed with the status bar API?

**Comment by bpasero** [comment]
I know that @jrieken did changes in the status bar API to allow for static items: https://github.com/microsoft/vscode-docs/blob/vnext/release-notes/v1_79.md#static-status-bar-items

**Comment by jrieken** [comment]
Closing as this is the wanted API behaviour. Not using an identifier does have the "wanted" effect of them all being treated the same (wrt hiding, naming etc).
