### ISSUE TITLE
Colorization of Javascript misses Unicode-flagged RegExp literals and some types of \u{...} constructions in RegExp literals

### ISSUE THREAD

**Issue by dilijev** [Microsoft/vscode#18430]
- VSCode Version: Code 1.8.1 (ee428b0eead68bf0fb99ab5fdc4439be227b6281, 2016-12-19T14:49:23.350Z)
- OS Version: Windows_NT ia32 10.0.15002
- Extensions:

|Extension|Author|Version|
|---|---|---|
|python|donjayamanne|0.5.5|
|indentation-level-movement|kaiwood|1.1.1|
|cpptools|ms-vscode|0.9.3|
|csharp|ms-vscode|1.6.2|
|PowerShell|ms-vscode|0.8.0|
|rewrap|stkb|1.0.0|

---

Steps to Reproduce:

1. Load a javascript file with the following regexes:

```js
// 037F and 03F3 - GREEK LETTER YOT
assertMatches(/\u{037f}/iu, 0x037f, '\u{037f}');
assertMatches(/\u{037f}/iu, 0x03f3, '\u{03f3}');
assertMatches(/\u{03f3}/iu, 0x037f, '\u{037f}');
assertMatches(/\u{03f3}/iu, 0x03f3, '\u{03f3}');

// New Cyrillic case-mapped pairs
assertMatches(/\u{0528}/i, 0x0528, '\u{0528}');
assertMatches(/\u{0528}/i, 0x0529, '\u{0529}');
assertMatches(/\u{0529}/i, 0x0528, '\u{0528}');
assertMatches(/\u{0529}/i, 0x0529, '\u{0529}');
assertMatches(/\u{052a}/i, 0x052a, '\u{052a}');
assertMatches(/\u{052a}/i, 0x052b, '\u{052b}');
assertMatches(/\u{052b}/i, 0x052a, '\u{052a}');
assertMatches(/\u{052b}/i, 0x052b, '\u{052b}');
```

2. Observe colorization

![image](https://cloud.githubusercontent.com/assets/494055/21874350/5e6a7f6e-d829-11e6-9f6a-c87543e56f7d.png)

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript-TmLanguage#404

**Comment by dbaeumer** [comment]
Verified the issue move.
