### ISSUE TITLE
Sass list syntax not yet supported 

### ISSUE THREAD

**Issue by BeniaminoBaggins** [Microsoft/vscode#18432]
- VSCode Version: 1.8.1
- OS Version: macOS Sierra 10.12.1

Steps to Reproduce:

1. enter list into sass file
2. see errors in vs code

**Comment by mjbvz** [comment]
@BeniaminoBaggins Can you please provide some example code along with the error you are seeing

**Comment by adi8i** [comment]
Try this code:

```
$base_colors: ('white': #ffffff, 'black': #222222, 'color-base': $ai-text-color, 'off-white': $ai-off-white);
@each $key, $value in $base_colors {
    .ai-#{$key} {
        color: $value;
    }
    .ai-background-#{$key} {
        background: $value;
    }
}
```

**Comment by adi8i** [comment]
Hello,

The `list` works fine, the problem was with `maps` and `@each $key, $value` when you pass multiple variables. I see it was fixed https://github.com/Microsoft/vscode/issues/19068.

**Comment by mjbvz** [comment]
Thanks @adi8i It does look like #19068 may have fixed things.

Please try out the latest insiders build and let us know if you see any further problems with syntax highlighting.
