### ISSUE TITLE
Can't Open a folder on macOS

### ISSUE THREAD

**Issue by avivfaraj** [microsoft/vscode#184376]
Type: <b>Bug</b>

On macOS Monterey, opening an existing project with File -> Open Folder.. makes the screen zoomed in so much, that this application becomes useless. 

VS Code version: Code 1.78.2 (Universal) (b3e4e68a0bc097f0ae7907b217c1119af9e03435, 2023-05-10T14:44:45.204Z)
OS version: Darwin x64 21.6.0
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5250U CPU @ 1.60GHz (4 x 1600)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|4, 6, 7|
|Memory (System)|8.00GB (0.12GB free)|
|Process Argv|--crash-reporter-id 7fdf5281-cd81-4b82-a466-25d266586de2|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
prettier-vscode|esb|9.13.0
python|ms-|2023.8.0
vscode-pylance|ms-|2023.5.50

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
vscccc:30610679
3biah626:30602489
pyind779:30671433
89544117:30613380
pythonsymbol12:30671437
2i9eh265:30646982
showlangstatbar:30737416
vsctsb:30748421
pythonms35:30701012
03d35959:30757346
pythonfmttext:30731395
pythoncmvfstrcf:30756944
fixshowwlkth:30730052
pythongtdpath:30739704

```

</details>

**Comment by gjsjohnmurray** [comment]
From Finder I suggest you go into the `. vscode ` subfolder of the problem folder, then open the `settings.json` file and look for a line setting the property that controls the zoom level. Delete that line, save the file, close it, then retry.

**Comment by DonJayamanne** [comment]
@avivfaraj Please let us know if the above works for you.

**Comment by avivfaraj** [comment]
@gjsjohnmurray @DonJayamanne Thanks for you help. It worked!
