### ISSUE TITLE
Sort entries in "Feature Contributions" tables of extension

### ISSUE THREAD

**Issue by gjsjohnmurray** [microsoft/vscode#184399]
Type: <b>Feature Request</b>

The lists under sections "Settings", "Commands" etc are not sorted, making it hard to check for a specific entry (and there is no "find" support).

For example:
![image](https://github.com/microsoft/vscode/assets/6726799/e689817c-8376-4d0c-98d9-b6951f26f848)

VS Code version: Code - Insiders 1.79.0-insider (666396ddec7708df2b986dcc178863faaa67c14d, 2023-06-05T11:30:50.018Z)
OS version: Windows_NT x64 10.0.22621
Modes:

**Comment by devrajgadhvi** [comment]
Hi @sandy081, I would like to address this issue, can you let me know what should be done?

**Comment by weartist** [comment]
I'll try to fix this

**Comment by gjsjohnmurray** [comment]
@ashutosh887 a PR from @weartist is waiting for review by @sandy081, so I think you'd be wasting your time if you submitted another.

**Comment by AMalfez** [comment]
Hi
Is this issue still open ?
I would like to work on it...
