### ISSUE TITLE
IgnoreFocusOut

### ISSUE THREAD

**Issue by celador** [Microsoft/vscode#18433]
ignoreFocusOut for inputboxOption and quickpickOptions is missing from the vscode.d.ts file.
It causes an error in my extension unless I manually change this typing whenever I do an npm install.
- VSCode Version: 1.8.1
- OS Version: Mac OS X

Steps to Reproduce:

1. npm install vscode
2. observe the IgnoreFocusOut property is missing

**Comment by mjbvz** [comment]
@dbaeumer I'm not too familiar with the `vscode` npm package and don't even see a `vscode.d.ts` file. Can you please take a look

**Comment by celador** [comment]
Refer to this issue
https://github.com/Microsoft/vscode-extension-vscode/issues/45

**Comment by dbaeumer** [comment]
Moving to @bpasero. Hope that is correct.

**Comment by bpasero** [comment]
@celador make sure you declare a more recent vscode dependency. IgnoreFocusOut was introduced in August 2016 it seems (https://github.com/Microsoft/vscode/commit/cfbf71725cf9e626d21c9847fc517df7c877fc45)

http://code.visualstudio.com/docs/extensions/debugging-extensions#_common-questions

**Comment by celador** [comment]
Thanks Ben, I updated my engine number and did npm install and everything is great again.  Thanks.
