### ISSUE TITLE
Emmet XHTML broken

### ISSUE THREAD

**Issue by Avol-V** [Microsoft/vscode#18434]
- VSCode Version: 1.8.1
- OS Version: Ubuntu 14.04

Steps to Reproduce:

1. Set xhtml syntax:
   ```json
   	"emmet.syntaxProfiles": {
   		"html": "xhtml"
   	},
   ```
2. Write `br` and press `Tab`.

Result is:
```html
<br></br>
```

Should be:
```html
<br />
```

Same for other tags.

Also didn't work shorthands like `input:radio`, result is:
```html
<input:radio></input:radio>
```

**Comment by ramya-rao-a** [comment]
@Avol-V For the time being, please use the below

```
"emmet.syntaxProfiles": {
        "html": {
              "self_closing_tag": "xhtml"
         }
}
```

@mrmlnc @egamma As of now the "emmet.syntaxProfiles" configuration in VS Code is being used for 2 purposes
- To define how generated HTML content should look like as described in the [docs for sytax-profiles in emmet](http://docs.emmet.io/customization/syntax-profiles/)
- To map any file extension to one of the supported modes in emmet (#9500)

"xhtml" is one of the [predefined profiles](http://docs.emmet.io/customization/syntax-profiles/#predefined-profiles), as in you can use it to say "I want everything just like html, but also want self closing tags".

When "xhtml" is passed as a syntax to emmet, you see the behavior that is described by @Avol-V. 
None of the [html abbreviations](https://github.com/emmetio/emmet/blob/master/lib/snippets.json#L689) get expanded correctly.

Emmet users know "xhtml" as just a profile that gives everything that html gives + self closing tags.

Therefore, I propose  the changes in #18625

**Comment by ramya-rao-a** [comment]
This is now fixed and the fix is in the insiders build
