### ISSUE TITLE
^[[200~copiedText~

### ISSUE THREAD

**Issue by krasi-georgiev** [microsoft/vscode#184397]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 
- Version: 1.79.0-insider
Commit: f6be5461f8bc69013a605f5baea834651c6589fb
Date: 2023-05-20T01:20:25.075Z
Electron: 22.5.2
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Linux x64 5.15.0-72-generic

Steps to Reproduce:

Copy text by selecting it - copy on selection is enabled
Paste the text by right clicking

Randomly there will be this strange prefix and suffix added to the text.

This started happening since an update I did 1 month ago

**Comment by quyenlv-unicloud** [comment]
What terminal you using? I see it long time ago (> 1 year), still happen few days ago. But I think is Git bash problem?

**Comment by krasi-georgiev** [comment]
as I said I am using the built-in vscode terminal

What do you mean by Git bash problem?

**Comment by krasi-georgiev** [comment]
Thanks will try the suggestion

Not sure what you mean by "your shell has told the terminal that it supports"?
was this some update on vscode? It wasn't doing this until some of the recent updates

**Comment by krasi-georgiev** [comment]
the suggested fix in the link is not practical as I login to many remote servers with the remote extension and having to add an entry in ~/.inputrc on every server is not practical.

There should be an option to disable this from the vscode settings.

**Comment by krasi-georgiev** [comment]
@Tyriar  I wouldn't consider this as fixed or by design since there is no way to disable this behavior globally and to return to the previous working behavior.
