### ISSUE TITLE
Menu not showing when I open new VScode window using File -> New Window

### ISSUE THREAD

**Issue by tfilo** [microsoft/vscode#184478]
Type: <b>Bug</b>

1. Open some project in Visual Studio Code (maybe empty vscode window is enough)
2. Click File -> New Window
3. In new Window try to click File, Edit, Selection or any other menu, menu will not show up.

This issue happens quite often but it is not producible this way every time. It is more like random behavior. Sometimes I close new opened window, than again click File -> New Window and than new widow works just fine. I have this issue for long period of time (I think at least more than one year). I have this problem on all of my computers, all are running some version of Ubuntu. I'm convinced that in situations when menu doesn't show, it does render menu "under" rest of vscode UI. Because when menu doesn't work in new window, I tried to open project from side menu using explorer, in that way I am able to open new project but open dialog opens under vscode window and I must move vscode window to side to see open dialog.

VS Code version: Code 1.78.2 (b3e4e68a0bc097f0ae7907b217c1119af9e03435, 2023-05-10T14:47:05.613Z)
OS version: Linux x64 5.19.0-43-generic snap
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz (12 x 3593)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|1, 1, 1|
|Memory (System)|31.09GB (24.41GB free)|
|Process Argv|--no-sandbox --force-user-env --unity-launch --crash-reporter-id 019d834c-efaa-419c-96a8-33827016f4b4|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vscaat:30438848
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
vscccc:30610679
282f8724:30602487
pyind779:30671433
f6dab269:30613381
pythonsymbol12:30671437
a9j8j154:30646983
showlangstatbar:30737416
vsctsb:30748421
pythonms35:30701012
03d35959:30757346
pythonfmttext:30731395
pythoncmv:30756943
fixhidewlkth:30730051
hidesbindicator:30760978
pythongtdpath:30739704
pythonnosmt12:30757131

```

</details>

**Comment by tfilo** [comment]
As I play with this a lot, I found that issue occurs more often in this scenario:

1) Open VScode
2) Open project in VScode using File -> Open Folder
3) Click File -> New Window
4) Grab new window and move it against top of screen to maximize (Or press maximize button)
5) Try click File menu, it will not show up and any other menu like Edit, Selection doesn't work too.

**Comment by deepak1556** [comment]
This is fixed in latest insiders, merging to https://github.com/microsoft/vscode/issues/187126
