### ISSUE TITLE
Why is `workspaceContains:<file that doesn't exist>` activating the Python, Pylance, and NPM extensions in the web?

### ISSUE THREAD

**Issue by TylerLeonhardt** [microsoft/vscode#184446]
Steps to repro:
* (prereq) make sure Python is installed in [insiders.vscode.dev](http://insiders.vscode.dev/) or [github.dev](http://github.dev/) (also repros with stable [vscode.dev](http://vscode.dev/), does not repo in Desktop)
* open https://insiders.vscode.dev/github/microsoft/vscode-extensions-loc or https://github.dev/microsoft/vscode-extensions-loc
* wait a bit
* see that Python gets activated even though this repo has nothing python-y in it (just XML files)

![image](https://github.com/microsoft/vscode/assets/2644648/77187e06-bad9-487a-a8f3-717bc1502da4)

@joyceerhl informed me of `Developer: Startup Performance` which gave me a very curious output:

#### Extension Activation Stats

| Extension                           | Eager | Load Code | Call Activate | Finish Activate | Event                                 | By                                  |
| ----------------------------------- | ----- | --------- | ------------- | --------------- | ------------------------------------- | ----------------------------------- |
| vscode.npm                          | true  | 1         | 0             | 0               | workspaceContains:package.json        | vscode.npm                          |
| ms-python.python                    | true  | 14        | 1             | 1               | workspaceContains:mspythonconfig.json | ms-python.python                    |
| ms-python.vscode-pylance            | true  | 91        | 0             | 244             | workspaceContains:pyrightconfig.json  | ms-python.vscode-pylance            |

What’s interesting about this is that this repo has no `package.json`, no `mspythonconfig.json`, no `pyrightconfig.json` … so this takes me to the original question.

Why is this causing activation?

After chatting a bit, @roblourens pointed out:
https://github.com/microsoft/vscode/blob/707854a76fa034e802c36073f32aeaa065c39461/src/vs/workbench/api/common/extHostExtensionService.ts#L682

as suspicious.

**Comment by alexdima** [comment]
@jrieken I think these host methods are not implemented correctly and they might be the root cause: https://github.com/microsoft/vscode/blob/707854a76fa034e802c36073f32aeaa065c39461/src/vs/workbench/api/worker/extensionHostWorker.ts#L163

**Comment by jrieken** [comment]
Yeah, the `exists` function isn't really implemented. Tho, I could change the default to `true` to `false` but the bigger challenge is that the `IHostUtils` interface assumes local file access - it talks about paths, not uris and therefore this will be hard to implement. And by extension I also think this is buggy for the node EH with workspace not hosted on local disk

**Comment by jrieken** [comment]
> And by extension I also think this is buggy for the node EH with workspace not hosted on local disk

NVM - I found the `forceUsingSearch` magic and will use that for web EH
