### ISSUE TITLE
Modern Fortran Intellisense

### ISSUE THREAD

**Issue by washout13** [Microsoft/vscode#18446]
It would be very useful to have modern Fortran Intellisense for VSCode, is this a possibility?

There is currently a great syntax highlighting extension for Fortran with snippets, but Intellisense would be great.

Cheers!

**Comment by SamVerschueren** [comment]
Should be done by an external extension like all the others.

**Comment by mjbvz** [comment]
Yes, this is something we would expect and extension to provide
