### ISSUE TITLE
Ctrl-Shift-F displays Replace textbox after Replace has been used once

### ISSUE THREAD

**Issue by johnnyreilly** [Microsoft/vscode#18442]
- VSCode Version: Code 1.8.1 (ee428b0eead68bf0fb99ab5fdc4439be227b6281, 2016-12-19T14:49:23.350Z)
- OS Version: Windows_NT ia32 6.3.9600
- Extensions:

|Extension|Author|Version|
|---|---|---|
|EditorConfig|EditorConfig|0.3.4|
|tslint|eg2|0.8.1|

---

Steps to Reproduce:

1. Ctrl-Shift-F 
2. Observe Search box alone
3. Ctrl-Shift-H
4. Observe Search and Replace boxes
5. Ctrl-Shift-F 
6. Observe Search and Replace boxes rather than just Search box

Not a biggy but it's a little weird and has bugged me for some time.  One of my colleagues also bumped into this yesterday hence prompting to me to actually raise and issue.

BTW VS Code **rocks**!!!!! Well done on all your work 👍

**Comment by mjbvz** [comment]
I confirmed this.

@roblourens can you please take a look. Is this the expected behavior?

**Comment by roblourens** [comment]
I think this is expected. The expandy arrow thing to the left will hide the replace box again.

**Comment by johnnyreilly** [comment]
I still think it's rather strange UX.

**Comment by roblourens** [comment]
ctrl+shift+f is just focusing the search box right now. I guess I could see it also collapsing that widget though.

**Comment by johnnyreilly** [comment]
I think that's more expected behaviour - certainly in my view

**Comment by sandy081** [comment]
Duplicates #9513
