### ISSUE TITLE
One Dark - theme pack

### ISSUE THREAD

**Issue by mlntr** [microsoft/vscode#184453]
After the GitHub acquisition by Microsoft, Atom got discontinued in favour of VS Code

Atom's famous theme "One Dark" has become the most popular theme in VS Code (spread across multiple extensions) showing its significant appeal/demand

Taking these into account, it would be appropriate to include One Dark in the default themes pack

![image](https://github.com/microsoft/vscode/assets/17552475/3e67fb5b-2e34-4f37-af76-8c02dd32d539)

**Comment by aeschli** [comment]
The marketplace contains many variants of the `One Dark` theme, created and maintained by users from the community. I don't see any real advantage in adding another variant.
