### ISSUE TITLE
Terminal Quick Fix never shows up

### ISSUE THREAD

**Issue by vfonic** [microsoft/vscode#184442]
Type: <b>Bug</b>

I don't know what could be wrong with my setup. I cannot get Terminal Quick Fix to show up. I had 1.71.0 version and updated to 1.78.2 today. I created a separate profile*, reloaded with disabled extensions, tried insiders build, ...

*this (Profiles functionality) is built in such an unintuitive way... It's great and I'd love to use it, but I feel like I have never used a computer before, when I try to figure out how to use different profiles...Please fix this...

Here's the screen recording (it's the same in Insiders):

https://github.com/microsoft/vscode/assets/67437/c38699cf-523c-4efd-9a62-8446334f4f8f

VS Code version: Code - Insiders 1.79.0-insider (Universal) (aee52551e25d98391f9064996196cd83a9fc8669, 2023-06-06T15:04:36.424Z)
OS version: Darwin arm64 22.4.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|4, 3, 3|
|Memory (System)|16.00GB (0.04GB free)|
|Process Argv|--crash-reporter-id 3736748d-5d75-43cf-9808-b4a10e9cefe8|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-todo-plus|fab|4.19.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythontb:30258533
pythonptprofiler:30281269
vshan820:30294714
vscod805cf:30301675
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30404738
py29gd2263:30754469
cppdebug:30492333
vsclangdf:30492506
c4g48928:30535728
dsvsc012:30540252
pynewext54:30618038
pylantcb52:30590116
pyind779:30611226
pythonsymbol12:30651887
a9j8j154:30646983
showlangstatbar:30737417
pythonms35:30671666
03d35959:30757351
57b77579:30687741
pythonfmttext:30716741
pythoncmvfstr:30726892
fixshowwlkth:30724385
hidesbindicator:30724476
pythongtdpath:30726887
pythonnosmt12:30757129

```

</details>

**Comment by meganrogge** [comment]
what program are you using for the styling of your prompt? this won't work when using things like powerlevel10k

**Comment by vfonic** [comment]
Oh shoot! That's exactly what I'm using. What are my options? Is there any solution aside from disabling powerlevel10k?

**Comment by meganrogge** [comment]
unfortunately not, the latest issue related to this is here if you're curious

https://github.com/microsoft/vscode/issues/146587

**Comment by meganrogge** [comment]
Yes, /duplicate https://github.com/microsoft/vscode/issues/145234
