### ISSUE TITLE
When viewing diff/changes to Python Notebook the mouse right-click context menu is hidden behind terminal

### ISSUE THREAD

**Issue by mattmazzola** [microsoft/vscode#184455]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.78.2 (user setup)
- OS Version: Microsoft Windows 11 Enterprise Insider Preview Version 10.0.23466 Build 23466

Version: 1.78.2 (user setup)
Commit: b3e4e68a0bc097f0ae7907b217c1119af9e03435
Date: 2023-05-10T14:39:26.248Z (3 wks ago)
Electron: 22.5.2
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Windows_NT x64 10.0.23466
Sandboxed: Yes

Steps to Reproduce:

1. Edit python notebook
2. Observe file in Source Control
![image](https://github.com/microsoft/vscode/assets/2856501/c1e49b29-3b92-4f56-964a-b571c492898d)
3. Click file to view changes made to that file
4. Right click to open context menu

Expected:
Menu should be above all other content so I can see and select any option

Actual:
Menu is rendered behind terminal of bottom panel so it is only partially visible.
This could mislead users since it may not be known that it is clipped

![vscode_ipynb_diff](https://github.com/microsoft/vscode/assets/2856501/e76039aa-ea6f-4477-bf5c-db7b6b3418d8)

**Comment by Tyriar** [comment]
I don't think there's anything on my side here

**Comment by DonJayamanne** [comment]
This issue no longer exists, possbiby fixed as part of some other issue in the past few months.
Closing for now, if this still exists, please feel free to ping here and I'll reopen this or feel free to create a new issue
![Image](https://github.com/user-attachments/assets/ede7890a-7e3a-420b-be2a-b080f6e33b8b)
