### ISSUE TITLE
Squeezed Application Memory

### ISSUE THREAD

**Issue by ouzmno** [microsoft/vscode#184421]
Type: <b>Performance Issue</b>

Hi there,

My m1 air experienced an issue of asking me quit some applications when I was updating vsc insider to release some memories. 

VS Code version: Code - Insiders 1.79.0-insider (Universal) (a8e719eeed4dac1f59fc2e48ed00545c0acafc42, 2023-06-05T21:53:50.950Z)
OS version: Darwin arm64 22.5.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|44, 35, 15|
|Memory (System)|16.00GB (0.06GB free)|
|Process Argv|--crash-reporter-id e4a04d57-caf5-46cb-b73c-0930774033c0|
|Screen Reader|yes|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
   13	   180	  1550	code-insiders main
    0	    82	  1555	   gpu-process
    0	    33	  1557	   utility-network-service
    0	   344	  1558	window [1] (non_finc_spread_to_swap.ipynb — comp6200)
    0	    66	  1601	ptyHost
    0	   344	  1602	extensionHost [1]
    0	    16	  1618	     /Users/john/Library/Application Support/Code - Insiders/User/globalStorage/tabnine.tabnine-vscode/binaries/4.4.329/aarch64-apple-darwin/TabNine --no-lsp=true --client=vscode --client-metadata clientVersion=1.79.0-insider pluginVersion=v3.6.52-alpha.20230606130349 t9-vscode-AutoImportEnabled=true t9-vscode-TSAutoImportEnabled=true t9-vscode-JSAutoImportEnabled=true vscode-telemetry-enabled=true vscode-remote=false vscode-extension-kind=1 vscode-theme-name=GitHub Dark Colorblind (Beta) vscode-theme-kind=Dark vscode-machine-id=389e376c066c6564df5a42cb5f1d0d004c731d340ff8d93cbf9c0aedd8307985 vscode-is-new-app-install=false vscode-session-id=6de52ef8-631d-4cee-abc6-069688a0b7a51686059885768 vscode-language=en vscode-app-name=Visual Studio Code - Insiders vscode-beta-channel-enabled=true vscode-status-customization=unknown vscode-inline-api-enabled=true ide-restart-counter=0
    0	   115	  1625	       /Users/john/Library/Application Support/Code - Insiders/User/globalStorage/tabnine.tabnine-vscode/binaries/4.4.329/aarch64-apple-darwin/TabNine --no-lsp=true --client=vscode --client-metadata clientVersion=1.79.0-insider pluginVersion=v3.6.52-alpha.20230606130349 t9-vscode-AutoImportEnabled=true t9-vscode-TSAutoImportEnabled=true t9-vscode-JSAutoImportEnabled=true vscode-telemetry-enabled=true vscode-remote=false vscode-extension-kind=1 vscode-theme-name=GitHub Dark Colorblind (Beta) vscode-theme-kind=Dark vscode-machine-id=389e376c066c6564df5a42cb5f1d0d004c731d340ff8d93cbf9c0aedd8307985 vscode-is-new-app-install=false vscode-session-id=6de52ef8-631d-4cee-abc6-069688a0b7a51686059885768 vscode-language=en vscode-app-name=Visual Studio Code - Insiders vscode-beta-channel-enabled=true vscode-status-customization=unknown vscode-inline-api-enabled=true ide-restart-counter=0 --no_bootstrap
    0	    49	  1636	     electron-nodejs (/Applications/Visual Studio Code - Insiders.app/Contents/Frameworks/Code - Insiders Helper (Plugin).app/Contents/MacOS/Code - Insiders Helper (Plugin) --ms-enable-electron-run-as-node /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/json-language-features/server/dist/node/jsonServerMain --node-ipc --clientProcessId=1602)
    0	    82	  1637	     electron-nodejs (/Applications/Visual Studio Code - Insiders.app/Contents/Frameworks/Code - Insiders Helper (Plugin).app/Contents/MacOS/Code - Insiders Helper (Plugin) --ms-enable-electron-run-as-node /Users/john/.vscode-insiders/extensions/visualstudioexptteam.intellicode-api-usage-examples-0.2.7/dist/server/server.js --node-ipc --clientProcessId=1602)
    0	   672	  1752	     electron-nodejs (/Applications/Visual Studio Code - Insiders.app/Contents/Frameworks/Code - Insiders Helper (Plugin).app/Contents/MacOS/Code - Insiders Helper (Plugin) --ms-enable-electron-run-as-node /Users/john/.vscode-insiders/extensions/ms-python.vscode-pylance-2023.5.51/dist/server.bundle.js --cancellationReceive=file:11eeda25ef380d9a14536f36da06295704dab34be2 --node-ipc --clientProcessId=1602)
    0	    66	  1753	     /Users/john/miniforge3/bin/python /Users/john/.vscode-insiders/extensions/ms-python.pylint-2023.5.11321005/bundled/tool/lsp_server.py
    0	    66	  1808	     electron-nodejs (cHVywO.js )
    0	    66	  1817	     electron-nodejs (Uq.js )
    0	   131	  1614	   window
    0	   115	  1623	shared-process
    0	     0	  1847	     /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0	    66	  1624	fileWatcher [1]
    0	    98	  1843	window [2] (Issue Reporter)
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (non_finc_spread_to_swap.ipynb — comp6200)
|    Folder (comp6200): 172 files
|      File types: ipynb(51) csv(21) DS_Store(14) xml(7) txt(6) gpx(5) py(4)
|                  md(3) gitignore(2) json(2)
|      Conf files: settings.json(2);
```

</details>
<details><summary>Extensions (36)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-django|bat|1.10.0
github-markdown-preview|bie|0.3.0
markdown-checkbox|bie|0.4.0
markdown-emoji|bie|0.3.0
markdown-footnotes|bie|0.1.1
markdown-mermaid|bie|1.18.1
markdown-preview-github-styles|bie|2.0.2
markdown-yaml-preamble|bie|0.1.0
docs-markdown|doc|1.0.1
python-environment-manager|don|1.0.4
python-extension-pack|don|1.7.0
copilot-chat|Git|0.1.2023060601
copilot-nightly|Git|1.88.142
vscode-pull-request-github|Git|0.65.2023060609
vsc-python-indent|Kev|1.18.0
pylint|ms-|2023.5.11321005
python|ms-|2023.9.11571010
vscode-pylance|ms-|2023.5.51
jupyter|ms-|2023.5.1001541100
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.15
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-slideshow|ms-|0.1.5
cmake-tools|ms-|1.15.12
onedrive-browser|ms-|0.0.1
vscode-markdown-notebook|ms-|0.0.26
wordcount|ms-|0.1.0
autodocstring|njp|0.6.1
indent-rainbow|ode|8.3.1
tabnine-vscode|Tab|3.6.52
cmake|twx|0.0.17
intellicode-api-usage-examples|Vis|0.2.7
vscodeintellicode|Vis|1.2.30
vscode-java-dependency|vsc|0.23.2023060200
vscode-icons|vsc|12.4.0
jinja|who|0.0.8

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256198
vslsvsres303:30308271
pythontb:30258533
pythonptprofiler:30281269
vshan820:30294714
vscod805:30301674
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30404738
py29gd2263cf:30754470
cppdebug:30492333
vsclangdf:30492506
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30618038
pylantcb52:30590116
pyind779:30611226
pythonsymbol12:30651887
showlangstatbar:30737417
pythonms35:30671666
03d35959:30757351
24365598:30687740
pythonfmttext:30716741
pythoncmvfstr:30726892
fixshowwlkth:30724385
hidesbindicator:30724476
pythongtdpath:30726887
pythonnosmt12:30757129

```

</details>

**Comment by mjbvz** [comment]
From the process info, Pylance is using the most memory. If you believe it is using too much, please file an issue against them

**Comment by ouzmno** [comment]
> From the process info, Pylance is using the most memory. If you believe it is using too much, please file an issue against them

Actually when I run on ubuntu, it has been crashed three times.
