### ISSUE TITLE
Add option to install remote extensions on local and vice versa

### ISSUE THREAD

**Issue by kauz56** [microsoft/vscode#184407]
What the title says. Example:
I'm working in WSL on an AHK project. Notice the missing language support, and install an extension for it. Now I might have some AHK files somewhere on Windows aswell. If I want to install the extension there also, I need to reconnect to WSL, lookup what extension it was, disconnect and install it again on Windows.

Something that makes this process less tiresome would be nice. Maybe an option that syncs the extensions on connect/disconnect from remote.

Edit: I've found the `Install Local Extensions in 'WSL: Ubuntu'...` button in the meantime. This only solves the issue from one side though.

**Comment by sandy081** [comment]
There is also command `Remote: Install Remote Extensions Locally...` to install remote extensions locally.

**Comment by kauz56** [comment]
@sandy081 That's awesome, thanks for the info!
Can you consider implementing this as a button here also though? Since the counterpart is already there..
![image](https://github.com/microsoft/vscode/assets/121489265/2ff5ad9c-e306-4d35-a215-1f110ed85db0)

**Comment by sandy081** [comment]
> Can you consider implementing this as a button here also though? Since the counterpart is already there..

Install remotely button is more needed than this one. I think the command is sufficient enough.
