### ISSUE TITLE
ssh alias not Working

### ISSUE THREAD

**Issue by vigikaran** [Microsoft/vscode#18448]
- VSCode Version: Code 1.8.1 (ee428b0eead68bf0fb99ab5fdc4439be227b6281, 2016-12-19T14:42:49.304Z)
- OS Version: Darwin x64 16.3.0
- Extensions:

|Extension|Author|Version|
|---|---|---|
|rainbow-brackets|2gua|0.0.6|
|crane|HvyIndustries|0.2.2|
|html-css-class-completion|Zignd|1.0.3|
|githistory|donjayamanne|0.1.4|
|rest-client|humao|0.11.4|
|debugger-for-chrome|msjsdiag|2.4.2|
|indent-rainbow|oderwat|0.4.1|
|laravel-blade|onecentlin|1.5.0|
|view-in-browser|qinjia|0.0.3|
|vscode-icons|robertohuertasm|6.0.0|
|laravel-artisan|ryannaddy|0.0.3|

---

Steps to Reproduce:

1. open built in terminal
2. type my ssh alias 
3.  command not found error

**Comment by mjbvz** [comment]
A few quick questions to help investigate:

* Which terminal are you using? Bash?
* How did you define the aliases? In an `~/.aliases` file?

I confirmed that I also do not see aliases from `~/.aliases` being recognized on Mac. @Tyriar Any thoughts?

**Comment by Tyriar** [comment]
You probably need to run as a login shell by adding this to settings.json:

```js
"terminal.integrated.shellArgs.osx": ["-l"]
```

See https://code.visualstudio.com/docs/editor/integrated-terminal#_linux-os-x
