### ISSUE TITLE
Open file with space form terminal

### ISSUE THREAD

**Issue by ashishverma87** [Microsoft/vscode#18444]
- VSCode Version:  1.8.1
- OS Version:  Unubtu 16.10

Steps to Reproduce:
Type below command in terminal
 code  '/path/somefile 2.php'

two files with name somefile and 2.php will open instead of somefile 2.php

**Comment by SamVerschueren** [comment]
Can reproduce this on macOS as well.

**Comment by mjbvz** [comment]
I'm unable to repo this using VSCode 1.8.1 on Mac with bash:

```
$ code 'somefile 2.php'
```

However I can repo this on ubuntu using the same command

@Tyriar I see you fixed an issue similar to this (https://github.com/Microsoft/vscode/commit/b6095e9d859f5df22c02d7aa660cb478476cc37c). Can you please take a look

*(sorry for the label spam btw)*

**Comment by SamVerschueren** [comment]
Odd, I have the same VS Code version but it's not working here. It opens `2.php` in my case.

**Comment by Tyriar** [comment]
Reported for Linux here https://github.com/Microsoft/vscode/issues/17713

@SamVerschueren you're on a Mac and seeing it?

**Comment by SamVerschueren** [comment]
Yes, but maybe it's me. I noticed I had a function in my `bash_profile`, which was the old school way of doing it. I removed it and did `source ~/.bash_profile` but it kept working. I then did [this trick](https://code.visualstudio.com/docs/setup/mac#_installation) but still it didn't work. So will reboot tomorrow then. Don't have time currently. Will keep you posted.

**Comment by Tyriar** [comment]
This should be fixed in latest insiders.
