### ISSUE TITLE
Issue 504

### ISSUE THREAD

**Issue by Ilkarion** [microsoft/vscode#184402]
ADD ISSUE DESCRIPTION HERE

Version: 1.78.2
Commit: b3e4e68a0bc097f0ae7907b217c1119af9e03435
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36
Embedder: codespaces

Hello. Yesterday all was fine but today at all my codespaces(when i write "npx serve") as result it returne 
**504
Gateway Timeout
The port forwarding timed out while trying to create a connection.**

**Comment by alexr00** [comment]
This looks like a Codespaces specific issue, which is best reported over in https://github.com/orgs/community/discussions.

Looks like https://github.com/orgs/community/discussions/57336? Not sure if you're all in the same region.

I've also forwarded directly to the Codespaces folks.
