### ISSUE TITLE
GitHub Codespaces Template 504  Gateway Timeout

### ISSUE THREAD

**Issue by cozydnb** [microsoft/vscode#184403]
Hello! 

I have a problem with GitHub Codespaces preact template. When I run code from example I get the "504 Gateway Timeout" error with message: "The port forwarding timed out while trying to create a connection".

I attached screenshots with the port information and error message.

Could you help me please?
![Снимок экрана 2023-06-06 в 13 56 23](https://github.com/microsoft/vscode/assets/47223819/ee977275-067a-4e90-8bdf-9b366f5f9e75)
![Снимок экрана 2023-06-06 в 13 56 44](https://github.com/microsoft/vscode/assets/47223819/aca3cba9-2ae7-4889-a6aa-f88d766ed745)

Version: 1.78.2
Commit: b3e4e68a0bc097f0ae7907b217c1119af9e03435
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.4.1 Safari/605.1.15
Embedder: codespaces

**Comment by ismaelcv** [comment]
We are running on the same issue.

We had a codespaces instance running on localhost 0.0.0.0:8080. Suddenly it stopped working and gave us 504 code.
Im sure yesterday it was working correctly.

Definitively following this issue!

**Comment by alexr00** [comment]
This looks like a Codespaces specific issue, which is best reported over in https://github.com/orgs/community/discussions.

Looks like https://github.com/orgs/community/discussions/57336? Not sure if you're all in the same region.
