### ISSUE TITLE
Setting sync conflicted on different OS

### ISSUE THREAD

**Issue by adison** [microsoft/vscode#184474]
Type: <b>Bug</b>

I am using VSC on Windows 10 and OSX 13.3.1
And I found a setting conflict about setting file path, but that is a issue from OS feature, kind of "file:///C:/Users/..." on window and "file://Users/...." on OS X.

Below is the screenshot of it
![image](https://github.com/microsoft/vscode/assets/2823871/fc6ff2bb-394d-4dc6-ad50-3b1de7928e9e)

VS Code version: Code 1.78.2 (b3e4e68a0bc097f0ae7907b217c1119af9e03435, 2023-05-10T14:44:45.204Z)
OS version: Darwin x64 22.4.0
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz (16 x 2300)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|2, 3, 3|
|Memory (System)|16.00GB (0.27GB free)|
|Process Argv|--crash-reporter-id a1e6c320-233b-43f0-bbc4-6340c8256c85|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (101)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-log-viewer-gb2312|And|0.9.1
LinkCheckMD|bla|0.3.1
ccls|ccl|0.1.29
doxdocgen|csc|1.4.0
rapid-json-search|dat|0.1.8
vscode-markdownlint|Dav|0.50.0
binary-plist|dni|0.11.2
docs-article-templates|doc|1.0.0
docs-authoring-pack|doc|1.0.0
docs-build|doc|0.4.1
docs-images|doc|1.0.0
docs-linting|doc|0.0.13
docs-markdown|doc|1.0.1
docs-metadata|doc|1.0.9
docs-preview|doc|1.0.1
docs-scaffolding|doc|0.0.17
docs-visual-areas|doc|0.2.1
docs-yaml|doc|1.0.0
githistory|don|0.6.20
xml|Dot|2.5.1
gitlens|eam|13.6.0
EditorConfig|Edi|0.16.4
json-tools|eri|1.0.2
prettier-vscode|esb|9.13.0
unicode-normalizer|esp|0.0.2
vscode-diff|fab|1.4.2
pipenv-scripts|Fed|1.0.3
auto-close-tag|for|0.5.14
auto-rename-tag|for|0.1.10
code-runner|for|0.12.0
docker-explorer|for|0.1.7
copilot|Git|1.88.132
log-view-l4n|glu|0.0.2
go|gol|0.38.0
cloudcode|goo|1.21.5
todo-tree|Gru|0.0.226
vscode-auto-open-markdown-preview|hnw|0.0.4
chatgpt-vscode-plugin|Jay|1.1.10
better-cpp-syntax|jef|1.17.2
vscode-peacock|joh|4.2.2
chat|kar|0.35.0
swift|Kas|0.2.0
Lua|key|0.0.9
chatgpt-helper|kir|4.1.0
MagicPython|mag|1.1.0
hexinspector|mat|1.5.1
pretty-formatter|mbl|0.2.2
rainbow-csv|mec|3.7.0
json|Mee|0.1.2
dotenv|mik|1.0.1
nc-gcode|ML|0.13.0
prettify-json|moh|0.0.3
vscode-azureappservice|ms-|0.24.9
vscode-azureresourcegroups|ms-|0.7.5
vscode-docker|ms-|1.25.1
vscode-language-pack-zh-hant|MS-|1.78.2023051009
csharp|ms-|1.25.8
vscode-kubernetes-tools|ms-|1.3.11
isort|ms-|2022.8.0
python|ms-|2023.8.0
vscode-pylance|ms-|2023.5.50
jupyter|ms-|2023.4.1011241018
jupyter-keymap|ms-|1.1.0
jupyter-renderers|ms-|1.0.15
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-slideshow|ms-|0.1.5
remote-containers|ms-|0.292.0
remote-wsl|ms-|0.78.9
azure-account|ms-|0.11.5
cmake-tools|ms-|1.14.33
cpptools-extension-pack|ms-|1.3.0
hexeditor|ms-|1.9.11
makefile-tools|ms-|0.7.0
powershell|ms-|2023.5.0
sublime-keybindings|ms-|4.0.10
vs-keybindings|ms-|0.2.1
vsliveshare|ms-|1.0.5864
vsliveshare-pack|ms-|0.4.0
autodocstring|njp|0.6.1
indent-rainbow|ode|8.3.1
pymakr|Pyc|2.22.5
vscode-yaml|red|1.13.0
partial-diff|ryu|1.4.3
vscode-base64-encoding-decoding|san|1.1.2
code-settings-sync|Sha|3.4.3
searchdocsets-vscode|sil|1.0.1
vscode-fileutils|sle|3.10.1
guides|spy|0.9.3
code-spell-checker|str|2.20.4
cmake|twx|0.0.17
lorem-ipsum|Tyr|1.3.1
intellicode-api-usage-examples|Vis|0.2.7
vscodeintellicode|Vis|1.2.30
expand-selection-to-scope|vit|0.2.0
WebTemplateStudio-dev-nightly|WAS|0.7.2117301
vscode-todo-highlight|way|1.0.5
vscode-ptt|Yuk|0.3.2
markdown-pdf|yza|1.4.4
json|Zai|2.0.2
propertylist|zho|0.0.2
material-theme|zhu|3.15.15

(4 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
3biah626:30602489
pyind779:30671433
f6dab269:30613381
pythonsymbol12:30671437
2i9eh265:30646982
showlangstatbar:30737416
vsctsb:30748421
pythonms35:30701012
pythonfmttext:30731395
pythoncmv:30756943
fixshowwlkth:30730052
pythongtdpathcf:30739705

```

</details>

**Comment by sandy081** [comment]
I would expect this setting is not registered to be synced because it has machine semantics. Please file an issue against the corresponding extension to ignore this setting to sync.
