### ISSUE TITLE
Default build task runs user task in random repositories

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#184454]
I got confused after seeing this a few times when running the default build task:

![image](https://github.com/microsoft/vscode/assets/2193314/733fae04-53e1-4766-b9dd-435565b034e3)

Looking into this I found that I only have a single build task, which is defined in user tasks:

![image](https://github.com/microsoft/vscode/assets/2193314/2f889c60-2229-4ef4-9ad7-a205c080c06a)

![image](https://github.com/microsoft/vscode/assets/2193314/e7fbe362-37e4-4d8f-9445-9040ba2517a1)

I don't remember adding this, so an extension may have done this without my knowledge, or I just forgot I tested something. Additionally I have seen this build task trigger in folders with actual default build tasks, which is likely that recurring issue coming back where the default build task can't be found until I reload the window.

Regardless, I think we should consider some changes:

- How do you unset the default build task?
- A user task probably should never be the default, this makes sense to me at least.

**Comment by meganrogge** [comment]
This is odd because you haven't specified `isDefault` here, so i'm not sure why it would run any task at all. It should instead prompt you to configure the default build task.

**Comment by meganrogge** [comment]
> How do you unset the default build task?

by removing `isDefault`

**Comment by meganrogge** [comment]
> A user task probably should never be the default, this makes sense to me at least.

We should allow this, but in your case, this was a bug because you hadn't set it as the default via `isDefault` and it was falling back to that.

**Comment by meganrogge** [comment]
Repro:

1. have a workspace with no tasks besides a user defined one that has `group:build` 
2. Use the `ctrlCmd+shift+b` shortcut to run the default build task
3. 🐛 before, it was running that task
4. now, there should be a configure default build task quickpick

**Comment by meganrogge** [comment]
Make sure to also verify that if you have a defined `isDefault` task, it gets run automatically.

Also try having several with `isDefault` and verify that it prompts you to choose which one you mean.
