### ISSUE TITLE
`ext install <extension name>` not working

### ISSUE THREAD

**Issue by kumarharsh** [Microsoft/vscode#18440]
- VSCode Version: 1.9.0-insider
- OS Version: Windows 10

Steps to Reproduce:

1. Go to marketplace, copy the install instruction `ext install theme-charcoal-oceanicnext` 
2. `Ctrl+P`, Paste instruction, nothing happens

**Comment by bpasero** [comment]
@kumarharsh you need to press enter after doing so. Maybe this entry should be selected though.

**Comment by kumarharsh** [comment]
It's showing `no commands matching` for `ext install <anything>`

**Comment by sandy081** [comment]
@kumarharsh It works for me. See the following screen shot. Can you provide us more information like have you done more than what mentioned in description and a screen shot would be much 
helpful.

![image](https://cloud.githubusercontent.com/assets/10746682/21887742/7a3536b0-d8c1-11e6-94c6-a26ffa8785f9.png)

**Comment by kumarharsh** [comment]
![image](https://cloud.githubusercontent.com/assets/760112/21891679/dfe5c4e2-d8f9-11e6-8304-1b0facfe3067.png)

VSCode Insider: 1.9.0-insider
Git Version: ed5a9f

![image](https://cloud.githubusercontent.com/assets/760112/21891698/f5cfeb98-d8f9-11e6-8fcd-d916efff38bc.png)

**Comment by sandy081** [comment]
@kumarharsh You are looking in command pallette, please see the character `>` at the beginning. As per the instructions, type `ctrl+p` which will open `quick open` without any characters and paste the text `ext install theme-charcoal-oceanicnext` and press enter.

**Comment by kumarharsh** [comment]
Sorry. I didn't notice this. My bad
