### ISSUE TITLE
Let's make it easier to open a New Window with a profile

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#184594]
When there is more than 1 profile, let's make the New Window action a submenu with the following actions: New Window, New PROFILE_NAME_1 Window, New PROFILE_NAME_2 Window... 

Should we do this also for the Open Folder action in the menu? Or just for that one? I am not sure.

fyi @bpasero

Here's what Safari does.

![image](https://github.com/microsoft/vscode/assets/1926584/d1d0c4ac-fdad-430b-a27e-59968dba307e)

**Comment by sandy081** [comment]
Fixed

![Image](https://github.com/user-attachments/assets/0592de46-df9c-49ee-a9d8-44dc9eabe381)

**Comment by isidorn** [comment]
Works well - I really like this flow. Adding verified
