### ISSUE TITLE
add open file menu icon when open replace editor

### ISSUE THREAD

**Issue by tjx666** [microsoft/vscode#184565]
when I open the search and replace preview editor, I can't find a way to quickly open the file and editor

![image](https://github.com/microsoft/vscode/assets/41773861/029183db-b39a-414e-babc-18c231fdd46d)

**Comment by andreamah** [comment]
Hm, I actually never noticed that. Probably a good addition! 
For now, if you want to never see the replace preview, you can also set `search.useReplacePreview` to false.

**Comment by andreamah** [comment]
I just noticed that this is a duplicate of https://github.com/microsoft/vscode/issues/35337

/duplicate https://github.com/microsoft/vscode/issues/35337
