### ISSUE TITLE
[php] Newline characters not escaped correctly

### ISSUE THREAD

**Issue by mastazi** [Microsoft/vscode#1845]
In many languages you can write a multi-line string by escaping the newline character, e.g.:

```
myString = "this \
is a multiline \
string";
```

However, in vscode, the text highlighting is broken when you have multi-line strings (the colour assigned to the string is only applied to the part of the string before the first back-slash, and as a result the text highlighting of the remaining part of the file is broken too).
I was able to reproduce the issue in PHP files, other languages might be affected too.

**Comment by Enquiren** [comment]
JavaScript multiline strings also look as described in this bug.

**Comment by felixfbecker** [comment]
Afaik you dont need to escape new lines in PHP

**Comment by ianwesterfield** [comment]
Yup - this is an issue with JS as well. Pretty annoying really.

Can't say this is a theme issue since, as you can see in the screenshot, the subsequent lines are not marked with "string" after the escaped first line:

<img width="1440" alt="screen shot 2016-03-12 at 2 10 57 pm" src="https://cloud.githubusercontent.com/assets/15803541/13724727/7b88bb50-e85c-11e5-9c1b-d7d128b9c064.png">

**Comment by ianwesterfield** [comment]
@felixfbecker You don't need to, you can, and most would say use `.`, but the problem here isn't coder preference. The escape in string contexts being missed in subsequent lines in the editor.

**Comment by mastazi** [comment]
@felixbecker are you suggesting that I propose to the team to change the codebase so that I can use VSCode?

**Comment by mastazi** [comment]
@Enquiren @ianwesterfield Yeah it's not limited to PHP and I don't understand why it was made to appear as a PHP-only issue.
Just modified the title to reflect the initial one.

**Comment by aeschli** [comment]
Please don't mix issues for different languages, the grammars that are used to power the syntax highlighting are different, managed even by different teams. As the original description talked mainly about PHP I made this a PHP bug.
Please file a new issue for JavaScipt, best with a JavaScript sample.

**Comment by ianwesterfield** [comment]
@mastazi I guess that's why it was made to appear PHP only. If only the contribution guidelines had clarified this, @aeschli wouldn't have had to ;)

**Comment by mastazi** [comment]
@aeschli @ianwesterfield sorry I wasn't aware of the way issues are managed, I should have checked.

**Comment by aeschli** [comment]
This seems to work in the meantime (1.10-insiders).

![image](https://cloud.githubusercontent.com/assets/6461412/23277717/3120da3c-fa0f-11e6-9136-9e071cf10270.png)
