### ISSUE TITLE
Settings scope switcher is too verbose when using a screenreader

### ISSUE THREAD

**Issue by rzhao271** [microsoft/vscode#184530]
I'm able to repro the issue on at least macOS with VoiceOver. I still need to test with NVDA on Windows.

1. Navigate to the Settings editor.
2. Tab to the scope switcher (the navbar that contains tabs that usually say User and Workspace)
3. :bug: A lot of info is read out for those tabs.

**Comment by rzhao271** [comment]
## Code pointers

I'll update this list as I get more info.

`SettingsTargetWidget` is defined in `preferencesWidgets.ts`. It holds the logic for the scope switcher.

https://github.com/microsoft/vscode/blob/725f83a711bc34049dbe8eb518110051e515ac74/src/vs/workbench/contrib/preferences/browser/preferencesWidgets.ts#L213

**Comment by cadinsl** [comment]
Hello! @rzhao271 would a fix to this issue be to instead of passing the fsPath we would only pass User or Workspace accordingly?

**Comment by rzhao271** [comment]
Hi, and yep, that'd work. I just confirmed with NVDA on Windows that the noise is due to using fsPath. I still have to confirm with VoiceOver on macOS whether there is more noise besides that.

**Comment by cadinsl** [comment]
I could try to fix this issues if that's ok! 
I can also confirm that the whole path is read with NVDA on windows

**Comment by sandy081** [comment]
Verified that navigating in tabs read now User, Workspace instead of full file paths
