### ISSUE TITLE
Can't re-arrange panels (on wayland?)

### ISSUE THREAD

**Issue by phisch** [microsoft/vscode#184515]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.79.0-insider (aee52551e25d98391f9064996196cd83a9fc8669)
- OS Version: Linux x64 6.3.6-arch1-1

Steps to Reproduce:

1. open vscode
2. try to move a panel

I can't move panels to the bottom panel or the secondary panel. The drag/drop indication is shown, but when I drop, nothing happens. I'm on the latest insider build since the stable build currently crashes on wayland with fractional scaling (so I can't test that build).

Here is a video that demonstrates the issue:

https://github.com/microsoft/vscode/assets/1282767/c34cb597-ea41-4c49-8598-b01e8205b7ef

**Comment by sbatten** [comment]
@phisch Is this still reproducing for you?

**Comment by deepak1556** [comment]
I will merge this to https://github.com/microsoft/vscode/issues/156723, the crash on startup is tracked separately at https://github.com/microsoft/vscode/issues/184124. Please follow these issues for updates, thanks!
