### ISSUE TITLE
Show "Downloading Update" instead of "Checking for Updates..."

### ISSUE THREAD

**Issue by normalser** [Microsoft/vscode#18450]
It seems like VSCode is actually downloading the update while showing to user "Checking for updates". On slow connection it can take some time and it feels like VSCode just got stuck while checking if there is any update (while in fact it is downloading the update) and user might restart VSCode to see if it fixes the Update Check. Consider changing the text to `Downloading Update` if there is an update in fact and it started downloading

![image](https://cloud.githubusercontent.com/assets/1723815/21891521/0b8de2a4-d8a1-11e6-93d2-70e0ebce0d84.png)

FYI - here is Atom:

![image](https://cloud.githubusercontent.com/assets/1723815/21891506/f7856e3a-d8a0-11e6-8ad7-e76cf70489f4.png)

**Comment by joaomoreno** [comment]
To keep the number of issues in our inbox on a manageable level, we're closing issues that have been on the backlog for a long time but haven't gained traction: We look at the number of votes the issue has received and the number of duplicates issues filed.

Thanks for your understanding. Happy coding!
