### ISSUE TITLE
Native TypeScript extension "validation" now seems to run on-type instead of on-save

### ISSUE THREAD

**Issue by claytoneast** [microsoft/vscode#184551]
Does this issue occur when all extensions are disabled?: Yes

Version: 1.78.2 (Universal)
OS: Darwin x64 20.6.0

When I type `const someName =` in a JS/TS file, before I save the file, there is a red squiggly line informing me of an error. I know. I haven't finished typing. Why is this editor screaming in red at me, while I'm "mid-sentence" so to speak, in 3 places:
1. Where I'm typing
2. In the tab for the open file
3. In the file tree explorer, where the filename is now red 

Example: (note the unsaved file indicator)
<img width="844" alt="Screen Shot 2023-06-07 at 3 43 45 PM" src="https://github.com/microsoft/vscode/assets/13628644/349358f2-9f81-4ee7-a40a-aef40e7250d0">

This did NOT used to work this way. I very purposefully shut off eslint running in my editor to disable this kind of on-type annoyance, and it worked great for almost 2 years. But today, I noticed VSC is once again showing me errors _when I haven't saved the goddamn file_. 

Steps to Reproduce:

1. Type `const whyIsThisYellingAtMe =` in a js/ts file, don't save the file yet
2. See errors everywhere, even though you haven't saved the file and thus there is no reason for it to be showing these errors.

If there is some setting I'm missing here that forces this validation to occur on-save instead of on-type, I'd be glad to hear of it, but I am fairly sure this did NOT used to scream at you until you hit save, which is the way I would expect it to work. This operates the same way even when all extensions are disabled (I guess TypeScript is a "native" extension or package or something).

**Comment by mjbvz** [comment]
I'm not sure what you think you were seeing before but validation has always ran on type with a slight delay (unless the reported errors are coming from a task)
