### ISSUE TITLE
intelliSense does not work with tsconfig.json ("includes")

### ISSUE THREAD

**Issue by MrOxMasTer** [microsoft/vscode#184556]
Type: <b>Bug</b>

intelliSense does not work together with tsconfig.json . Specifically with the "include" option.
What is the problem: when configuring config.json, specifically the paths in "include", then intelliSense stops working with some libraries, for example react-query, and displaying dependencies from them, for example useQuery. How did I understand that the problem is in tsconfig.json? Because I deleted it and intelliSense started working again, but instead a bunch of errors came up on the example of "React" and UMD and so on.
Without a config, I have dependencies perfectly and I can import them without pain, and as soon as I add it, that's it, intelliSense stops working for me. I tried to configure different paths, I even took settings from the official react-query website using typescript, and there intelliSense works perfectly: https://tanstack.com/query/v4/docs/react/examples/react/optimistic-updates-typescript
The problem is that as soon as I add the correct paths, all the errors go away from vscode, but intelliSense stops working. I repeat, I tried to set up completely different paths. I tried all the options, but it didn't help

VS Code version: Code - Insiders 1.79.0-insider (b380da4ef1ee00e224a15c1d4d9793e27c2b6302, 2023-06-07T14:26:54.152Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz (4 x 2712)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.89GB (4.01GB free)|
|Process Argv|--crash-reporter-id 8d5950e0-2632-4265-9569-e267bad308c4 --crash-reporter-id 8d5950e0-2632-4265-9569-e267bad308c4 --crash-reporter-id 8d5950e0-2632-4265-9569-e267bad308c4|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythontb:30258533
pythonptprofiler:30281269
vshan820:30294714
vscod805:30301674
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30404738
cppdebug:30492333
vsclangdf:30492506
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30618038
pylantcb52:30590116
pyind779:30611226
vscrp:30624060
pythonsymbol12:30651887
showlangstatbar:30737417
pythonms35:30671666
03d35959:30757351
24365598:30687740
pythonfmttext:30716741
pythoncmvfstr:30726892
fixshowwlkth:30724385
hidesbindicator:30724476
pythongtdpath:30726887
pythonnosmt12:30757129

```

</details>

**Comment by MrOxMasTer** [comment]
"typescript": "^5.1.3",
"@types/node": "^20.2.5",
"@types/react": "^18.2.8",
"@types/react-dom": "^18.2.4",
"react-query": "^3.39.3",
![image](https://github.com/microsoft/vscode/assets/59291123/30d0208c-d7bd-4851-8048-9b965a3b4dff)
![image](https://github.com/microsoft/vscode/assets/59291123/382eac70-79d4-46e7-b6eb-faef334e2d0a)
This is when there are paths and how I think they are correct, because if they were wrong, I would get an error that typescript did not find anything

**Comment by MrOxMasTer** [comment]
![image](https://github.com/microsoft/vscode/assets/59291123/859626a0-4be3-4143-9a11-487fec84d6ae)
If he can't find the way, then everything works fine for me (This is from the official react-query website, only the path is wrong)

**Comment by MrOxMasTer** [comment]
![image](https://github.com/microsoft/vscode/assets/59291123/00f72ee0-a6c8-4de7-bd24-11c5c33a0c29)
It used to work, but now it has stopped. Even when there is no config, it still does not highlight anything

**Comment by MrOxMasTer** [comment]
By the way, I have "typescript" installed: "^5.1.3", and rename tag on typescript built-in does not work for you either

**Comment by mjbvz** [comment]
Please share a self contained example project which demonstrates the issue

**Comment by MrOxMasTer** [comment]
https://github.com/MrOxMasTer/TestLibraryNextTurbo

**Comment by MrOxMasTer** [comment]
By the way, I updated vs code and "editor.linkedEditing": true earned for jsx. I do not know what I installed in this build that I threw off, although I was just testing various libraries.

**Comment by mjbvz** [comment]
Thanks but this example is too large to effectively debug. It's unclear to me what you're trying to achieve and if it should work or not

Please create the minimal possible sample and explain the expected behavior vs the actual behavior
