### ISSUE TITLE
Copilot Chat user study 2

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#184505]
User study about the inline chat, copilot chat and quick thoughts on the quick pick + Copilot experience.

**Comment by digitarald** [comment]
[Study guide for reference](https://microsoft.sharepoint.com/:o:/r/teams/VSCode68/_layouts/15/Doc.aspx?sourcedoc=%7B32de3923-4ec7-44c5-876e-5dbb7246eba2%7D&action=edit&wd=target(UX.one%7CBDE74AFC-3BE1-4298-B603-E3D03C2F5431%2FDiscussion%20guide%20template%7CA68A9FA9-4B4B-4530-A333-BD31F7AC0C35%2F)&ovuser=72f988bf-86f1-41af-91ab-2d7cd011db47%2Chkirschner%40microsoft.com&clickparams=eyJBcHBOYW1lIjoiVGVhbXMtRGVza3RvcCIsIkFwcFZlcnNpb24iOiIyOC8yMzA1MDEwMDQyMiIsIkhhc0ZlZGVyYXRlZFVzZXIiOmZhbHNlfQ%3D%3D&SafelinksUrl=https%3A%2F%2Fmicrosoft.sharepoint.com%2Fteams%2FVSCode68%2F_layouts%2FOneNote.aspx&share=IgEjOd4yx07FRIduXbtyRuuiASXk1PKwVlqlaMrNgaztfKM)

**Comment by digitarald** [comment]
Insights from observing 6 devs trying out Copilot Chat in different form factors to test the latest improvements to inline chat, the new quick question prompt. Moderated by Steven Clarke, Isidor Nikolic and me.

📖 [3-pager](https://microsoft.sharepoint.com/:w:/t/VSCode68/EU-e-9RJrbZDv_C1H5WTbDoBh1jVywlJGKwZFQb63ol9jA?e=QMiMrM&isSPOFile=1) for background on the key takeaways. The insightful research thoughts from [@stevencl](https://vscodeteam.slack.com/team/U0K5PA3QE) are a must-read.
 

🍿 [25min best moments/quotes](https://microsoft.sharepoint.com/:v:/t/VSCode68/Ec5_1pFGmT5CmzIZZ7tHHokB-0IDEMORcZYZGaN1YgBbLw?e=9H4wRS&isSPOFile=1) from 6hrs of user interviews. A must-watch (during or lunch or while making coffee)!

_(Trying the video montage this time. Please let me know if you watched it, and if its helpful 🙏🏻)_

🧵 Key takeaways (just a sneak peek, the doc is much better!):

1. Improvements for inline chat greatly improved the review and editing flow.
2. While the Discard button was understood, the dropdown did not make sense to most participants.
3. Some expected inline chat to be conversational/multi-turn, but after unexpected results adapted by iterating on the one-shot prompt.
4. Quick chat was used by some, but many struggled with taking action on the responses, as they didn’t know if the response persists.
5. Participants lost time manually moving code suggestions into the editor (code blocks rarely worked out-of-the-box). This made the experience feel disconnected from the editor (like ChatGPT) and didn’t meet users’ expectation. Inline chat in comparison gave an integrated (better than ChatGPT) feeling.
6. Participants overestimated the context grounding Copilot’s answers, which leads to churning on prompt crafting and overestimating quality of suggested code.
7. Quality of answers dictated the jobs developers expect to use Copilot with, a) where it actually saved time compared to doing it by hand and b) where devs are confident enough to review suggestions.
