### ISSUE TITLE
Welcome editor shows up with a delay and progress bars

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#184562]
See below video for a first time user startup:

![Recording 2023-06-02 at 12 13 39](https://github.com/microsoft/vscode/assets/900690/5dfc42f9-45db-4eac-a732-335778286435)

I immediately get the impression that VS Code is slow because even the welcome page cannot show instantly. 

A similar case reported from @rebornix :
![Kapture 2023-06-08 at 06 12 18](https://github.com/microsoft/vscode/assets/900690/995d3cb5-60f7-46a5-a5bd-030acbff9f8c)

I think we should really try to find a solution where the welcome editor can start instantly to tell our users we are providing a fast editor and not a slow one.

**Comment by rebornix** [comment]
When using Remote SSH

* 1.78 Stable. Welcome page shows immediately, even if it requires password to start the connection.
* Insiders. Welcome page only displays after the connection is established.

**Comment by meganrogge** [comment]
@bhavyaus can you pls assign this to May Recovery after the release and add `candidate`?

**Comment by precha1989** [comment]
good
