### ISSUE TITLE
VSCode - Cmd+Shift+E & Cmd+Shift+F stopped working on Mac

### ISSUE THREAD

**Issue by klueless-io** [microsoft/vscode#184557]
Type: <b>Bug</b>

I have used VSCode for years and frequently use Cmd+Shift+E to see the explorer panel and Cmd+Shift+F to find files, but the functionality stopped working a few days ago.

I'm do not think I have accidentally changed any keybindings, and wondering if an upgrade to VSCode is the reason.

I usually can press:

**OLD**: 

Cmd+Shift+E (press once only) would always go to Explorer, and other collapsable elements like Search would disappear.

**NOW**: 

**A:** if File Explorer is collapsed, then Cmd+Shift+E goes to Search and does not show the File Explorer

[![enter image description here][1]][1]

**B:** If File Explorer is not collapsed, Cmd+Shift+E goes to Explorer, but the Search area is still showing.

[![enter image description here][2]][2]

**OLD**: 

Cmd+Shift+F (press once only) would always go to the file Search, and collapsable elements like file explorer would disappear.

**NOW**:

**A:** If File Explorer is collapsed, Cmd+Shift+F goes to Search (This is expected)

[![enter image description here][3]][3]

**B:** if File Explorer is not collapsed and Cmd+Shift+F is pressed, it goes to Search and leaves the file explorer visible. (File Explorer used to disappear)

[![enter image description here][4]][4]

  [1]: https://i.stack.imgur.com/9URtg.png
  [2]: https://i.stack.imgur.com/UvvKX.png
  [3]: https://i.stack.imgur.com/7PQHs.png
  [4]: https://i.stack.imgur.com/BaLVY.png

VS Code version: Code 1.78.2 (b3e4e68a0bc097f0ae7907b217c1119af9e03435, 2023-05-10T14:44:45.204Z)
OS version: Darwin x64 22.4.0
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M2 Pro (12 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|32.00GB (0.01GB free)|
|Process Argv|--crash-reporter-id dcee092e-90d4-43d3-b522-fb2b3c339e18|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
282f8724:30602487
pyind779:30671433
89544117:30613380
vscrpc:30673769
pythonsymbol12:30671437
showlangstatbar:30737416
vsctsb:30748421
pythonms35:30701012
03d35959:30757346
pythonfmttext:30731395
pythoncmvfstrcf:30756944
f8hc8238:30694864
fixhidewlkth:30730051
showsbindicator:30760979
pythongtdpathcf:30739705

```

</details>

**Comment by ulugbekna** [comment]
Hi,

Thanks for filing the issue.

Could you please [try the following](https://github.com/microsoft/vscode/wiki/Keybinding-Issues#basic-troubleshooting):

1. Run the command "Developer: Toggle Keyboard Shortcuts Troubleshooting" (you can, for example, run it from the Command Palette). 

   This will activate logging of dispatched keyboard shortcuts and will open an output panel with the corresponding log file.

2. Press exactly the keybinding you desire
 
3. Check what VS Code detects

If you are having trouble understanding the output, please feel free to paste here and we'll be happy to help ☺️

You can also check your keybindings for what's bound to `cmd+shift+e` and `cmd+shift+f` -- open keybindings editor by pressing `cmd+k cmd+s` and then `cmd+option+k` to record keys and then press your desired keybinding to search for it

**Comment by klueless-io** [comment]
I have given the info-needed, do you need any more information?

**Comment by ulugbekna** [comment]
Thanks for the reminder @klueless-io ! 

I have to defer to @lramos15 who's a lot more knowledgable about the Explorer view -- I don't think the problem is in keybindings but rather how the commands they invoke behave. 

@lramos15 would you mind having a look?

**Comment by lramos15** [comment]
I assume you purposefully moved the search into the same container as the explorer? Did this work before when you did that? The explorer was recently made a moveable view which may relate to this issue. Does it work as expected with things in their default locations?

**Comment by klueless-io** [comment]
> `CMD + SHIFT + P` => `Reset View Locations`

This resolved my issue

> I assume you purposefully moved the search into the same container as the explorer? 

I did not purposefully do this, but I may accidentally created the issue.

Thanks for the answer
