### ISSUE TITLE
SCM status bar items take a long time to appear in web

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode#184541]
1. Open any GitHub repo in vscode.dev
2. :bug: initially there are no SCM status bar items, additionally any existing changes to the repo contents are not reflected in the SCM view
3. After an unknown amount of time they appear

@TylerLeonhardt and I ran into this yesterday, and @rzhao271 just ran into this as well

@lszomoru do you have any ideas for what might be going on here?

**Comment by lszomoru** [comment]
Not from the top of my head. Could we get trace logs when this occurs?

**Comment by joyceerhl** [comment]
@TylerLeonhardt and I debugged this yesterday and I believe this is due to the rich nav endpoint taking upwards of 1 min to return 404s, thus closing and following up with the rich nav team.

**Comment by lszomoru** [comment]
Great work 👏 . Glad that you two were able to track this down.
