### ISSUE TITLE
Allow virtual space in text editor

### ISSUE THREAD

**Issue by jamiefutch** [microsoft/vscode#184561]
VS Code needs virtual space in the same manner as Visual Studio before I can recommend it to my team.  Until it has this I'll  continue to purchase Jetbrains Rider for my team.  VS Code is just not usable to long time MS  developers without virtual space.

**Comment by bpasero** [comment]
What do you refer to when you mean "virtual space", do you mean the desktop window management feature?

**Comment by jamiefutch** [comment]
Virtual space allows two things:
1) the cursor to be placed anywhere in the edit window
2) the user to move the cursor up and down in the edit window and the cursor to remain in a specified column

More info can be found here:
https://learn.microsoft.com/en-us/visualstudio/ide/how-to-manage-editor-modes?view=vs-2022

https://www.youtube.com/watch?v=t8ulNHoW5HE

sorry for the video link but it is probably better than anything I can cook up.
