### ISSUE TITLE
#ifndef Cppsnippets write #ifndef

### ISSUE THREAD

**Issue by Athius** [Microsoft/vscode#18452]
- VSCode Version: Code 1.8.1 (ee428b0eead68bf0fb99ab5fdc4439be227b6281, 2016-12-19T14:49:23.350Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions:

|Extension|Author|Version|
|---|---|---|
|Bookmarks|alefragnani|0.10.1|
|code-gnu-global|austin|0.2.1|
|togglehs|bbenoist|0.1.2|
|vscode-instant-markdown|dbankier|0.2.1|
|githistory|donjayamanne|0.1.4|
|python|donjayamanne|0.5.5|
|CppSnippets|hars|0.0.5|
|vscode-auto-open-markdown-preview|hnw|0.0.3|
|beautify|HookyQR|0.7.2|
|Go|lukehoban|0.6.51|
|cpptools|ms-vscode|0.9.3|
|vscode-docker|PeterJausovec|0.0.11|
|tmlanguage|Togusa09|0.7.1|
|json2yaml|tuxtina|0.2.0|
|cmake|twxs|0.0.15|
|cmake-tools|vector-of-bool|0.8.6|
|code-d|webfreak|0.15.1|

---

Steps to Reproduce:

1. When I write #ifn and make completion to use the snippet #ifndef of Cppsnippets, the generated code is this one: 
 
```cpp   
#ifdef 1 // instead of #ifndef 1
   
#endif // !1
```

**Comment by mjbvz** [comment]
This looks like it is coming from the `Cppsnippets` extension. Please open the bug against them

Thanks.
