### ISSUE TITLE
Explorer tab isn't working

### ISSUE THREAD

**Issue by AhmedOsman101** [microsoft/vscode#184577]
Type: <b>Bug</b>

After opening a new folder or an existing project, I open the explorer tab and I can't find any folders or files visible in it only showing Outline and Timeline dropdown menu only. please fix this issue I tried reinstalling vs code and reset all settings.

VS Code version: Code 1.78.2 (b3e4e68a0bc097f0ae7907b217c1119af9e03435, 2023-05-10T14:39:26.248Z)
OS version: Windows_NT x64 10.0.19045
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-10105F CPU @ 3.70GHz (8 x 3696)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.92GB (11.51GB free)|
|Process Argv|C:\\Users\\Othman Enterprises\\Desktop\\apps --crash-reporter-id f21d4078-99ef-4ca0-84ec-12183752cab1|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vscaac:30438847
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
3biah626:30602489
pyind779:30671433
89544117:30613380
pythonsymbol12:30671437
showlangstatbar:30737416
vsctsb:30748421
pythonms35:30701012
a2ce3375:30757347
24365598:30736109
pythonfmttext:30731395
pythoncmv:30756943
fixhidewlkth:30730051
showsbindicator:30760979
pythongtdpath:30739704
pythonnosmt12:30757131

```

</details>

**Comment by lramos15** [comment]
`CTRL + SHIFT + P` -> `Reset View Locations`
