### ISSUE TITLE
Handlebars block expressions are not highlighted anymore

### ISSUE THREAD

**Issue by t-sauer** [Microsoft/vscode#18451]
- VSCode Version: Code - Insiders 1.9.0-insider (ed5a9f269d2d1c9e866bc1f29dbd6a25abc02701, 2017-01-12T07:05:52.808Z)
- OS Version: Darwin x64 15.6.0

---

Steps to Reproduce:

1. Create a new Handlebars file
2. Add the following content:

```hbs
{{#foo}}
  <h1>Test</h1>
{{/foo}}
```

In the current stable version (1.8.1) the Handlebars expression is highlighted correctly:
<img width="142" alt="screen shot 2017-01-12 at 14 37 18" src="https://cloud.githubusercontent.com/assets/5306662/21891860/f11b6926-d8d4-11e6-8250-7321f3e2a31a.png">

In the current insider version the Handlebars expression is not highlighted at all:
<img width="151" alt="screen shot 2017-01-12 at 14 40 09" src="https://cloud.githubusercontent.com/assets/5306662/21891875/0c5d427c-d8d5-11e6-8f18-585aa76ee4ba.png">

**Comment by mjbvz** [comment]
@aeschli I confirmed this difference. Not sure if it is expected or if the grammar has been updated recently. Can you please take a look?

**Comment by aeschli** [comment]
The grammar stayed the same, but we fixed the way that themes rules are applied to scopes (see #3008).
I verified that the new way of matching is correct. Before it was rather random that {{ .. }} were mapped to functions.

**Comment by aeschli** [comment]
Closing as it's the expected behaviour. The default color themes render brackets and operators always with the standard foreground color.

**Comment by t-sauer** [comment]
> The default color themes render brackets and operators always with the standard foreground color.

Why are non-block operators highlighted then? 

<img width="140" alt="screen shot 2017-01-20 at 18 52 34" src="https://cloud.githubusercontent.com/assets/5306662/22159530/aa7acf16-df41-11e6-9c8b-bf14dd669ae5.png">

**Comment by aeschli** [comment]
The handlebar grammar gives block expressions the same color as the brackets.
It gives it the support.constant scope which we don't color in the default themes.

I files https://github.com/daaain/Handlebars/issues/94 to give the block expressions a separate color.

I pushed a fix for our themes.
