### ISSUE TITLE
PSScriptAnalzyer corrupts multi-line code during replace-aliases

### ISSUE THREAD

**Issue by lansalot** [Microsoft/vscode#18459]
Platform
Win7 x64
![pic4](https://cloud.githubusercontent.com/assets/9885921/21896501/887754d4-d8de-11e6-89ba-f74239da5b48.jpg)

To replicate (note use of backtick to split line)

    $Pools = gwmi -query "select * from IIsApplicationPoolSetting" -computer $server `
       -namespace "root\microsoftiisv2" -Authentication PacketPrivacy -erroraction SilentlyContinue

PSScriptAnalyzer pulled that up at gwmi being an alias, so I hit the lightbulb to convert it to Get-WMIObject. This happened.

    $Pools = Get-WmiObjectroot\microsoftiisv2" -Authentication PacketPrivacy -erroraction SilentlyContinue

As you can see, it cut out a heap of code and merged the two lines.

![pic1](https://cloud.githubusercontent.com/assets/9885921/21896498/886096f4-d8de-11e6-9032-89c6b47dec08.jpg)
![pic2](https://cloud.githubusercontent.com/assets/9885921/21896500/886f8b1e-d8de-11e6-8d33-3ca7b9ba239c.jpg)
![pic3](https://cloud.githubusercontent.com/assets/9885921/21896499/8863ee9e-d8de-11e6-9bec-88ad36bffc96.jpg)

**Comment by mjbvz** [comment]
This looks like it is caused by a powershell extension. Please try opening the issue against them
