### ISSUE TITLE
ITerminalInstance.onData should be higher level

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#18453]
- VSCode Version: 1.9.x

The callback trigger on ITerminalInstance.onData() receives a string containing the raw pty output including the ANSI Control characters. Although this might be useful for some clients I think the majority is not interested in ANSI Control characters since the interpretation is not easy. I therefore suggest that the terminal provide two different listeners. One raw listener that includes the data like it is today and one line based listener that fires if

1. a line got added to the output
1. when a line got changed. 

The event should contain the line number as well.

**Comment by Tyriar** [comment]
Oh I thought you mentioned you wanted to include escape sequences? You just want line by line data with escape sequences stripped then? 

Line number is not an easy thing to convey as the buffer continually gets trimmed to adhere to the terminal's scrollback.

**Comment by dbaeumer** [comment]
Yes, line by line with escape sequence stripped would be perfect. I don't necessarily need a line number a sort of line ID would help as well to determine if a line has changed in regards to a previous line. That would allow to determine if an computed problem needs to be invalidated.

**Comment by Tyriar** [comment]
@dbaeumer RE line ID: Does this line rewriting happen with any compilers/linters you know? In my experience they typically just print new lines.

**Comment by dbaeumer** [comment]
@Tyriar agree that they typically print new lines. But if not there is no way for the matcher to detect this if we don't have some sort of id.

**Comment by Tyriar** [comment]
The current solution is working fine for now so closing this off.

**Comment by BartNetJS** [comment]
@Tyriar  I try to use the terminal.onData(data => ...) in an extension
But the vscode.d.ts Terminal Interface does not have the onData declaration
I'm using VSCode 1.19.0-insider
And in the package.json for the extension:

> "engines": {
> 		"vscode": "^1.19.0"
> 	}

> "dependencies": {
> 		"vscode": "^1.1.7",
> 		"vscode-languageclient": "^3.5.0"
> 	}

**Comment by Tyriar** [comment]
@BartNetJS this is an internal API so it's not available to extensions. We're not sure currently whether we want to expose this to extensions as there are security and performance considerations to take into account.

**Comment by Tyriar** [comment]
Not sure why this was locked but https://github.com/Microsoft/vscode/issues/13337 might be what you're after.
