### ISSUE TITLE
Remote Tunnels won't connect

### ISSUE THREAD

**Issue by JamesB-Blur** [microsoft/vscode#184528]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.78.2 (remote and local)
- OS Version: Local: Windows 10 21H2 (19044.2965) Remote:  Windows 10 21H2 (19044.2251)
- Extension version: Remote Tunnels 1.2.0 (remote and local)

I tried connecting to my work machine this morning via a tunnel.  This was working fine on 6.6.2023.  But this morning (6.7.2023) I noticed that the Remote - Tunnel extension updated and now I am not able to connect to my work machine via a VS Code Tunnel.  I also tried the browser version and that fails to connect as well.

Steps to Reproduce:

1. Open shell in remote machine, run `code tunnel`
2. Open VS Code in host machine, select 'Connect to Tunnel', select remote machine tunnel

Error:
On remote machine I get this error:
`error [tunnels::connections::relay_tunnel_host] error handshaking session: EOF`

Then is cycles this error:
`info [tunnels::connections::relay_tunnel_host] Opened new client on channel 5`
`info [tunnels::connections::relay_tunnel_host] Opened new client on channel 6`
....

UPDATE
from log.txt
```
* Visual Studio Code Server
*
* By using the software, you agree to
* the Visual Studio Code Server License Terms (https://aka.ms/vscode-server-license) and
* the Microsoft Privacy Statement (https://privacy.microsoft.com/en-US/privacystatement).
*
Server bound to \\.\pipe\code-c3c17599-600f-4a3c-a272-1c2b9a8698f0
Extension host agent listening on \\.\pipe\code-c3c17599-600f-4a3c-a272-1c2b9a8698f0

[10:18:37] 




[10:18:37] Extension host agent started.
[10:18:37] [<unknown>][ab2c068a] Client refused: version mismatch.
[10:18:37] [<unknown>][39c1653b] Client refused: version mismatch.
[10:18:40] [<unknown>][a0825270] Client refused: version mismatch.
[10:18:42] [<unknown>][6aba811f] Client refused: version mismatch.
[10:18:44] [<unknown>][cc58d9e0] Client refused: version mismatch.
[10:18:46] [<unknown>][5c333a6a] Client refused: version mismatch.
Last EH closed, shutting down
[10:23:37] Last EH closed, shutting down
```

On the host machine I get these errors:
`Could not fetch remote environment`
`Failed to connect to the remote extension host server (Error: Connection error: Client refused: version mismatch)`

**Comment by digismack** [comment]
Having the same issue here. Completely blocked on remote tunnel based development at the moment.

**Comment by digismack** [comment]
Installed the Insiders build of VSCode on my local machine and was able to connect to the remote tunnel that was failing on the normal build. Unblocked for now, at least.

**Comment by connor4312** [comment]
Duplicates https://github.com/microsoft/vscode-remote-release/issues/8582
