### ISSUE TITLE
Can commit code with unused imports and which is not formatted

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#18460]
- On linux, I can commit TS files with unused imports and which are not formatted
- Also, the build machine does not seem to mind this anymore

**Comment by jrieken** [comment]
@egamma Is this because of the new tslint version?

**Comment by egamma** [comment]
@alexandrudima did you do an `npm update` to get a new version of tslint on your Linux machine? We have custom tslint rules and I've updated them to the latest tslint API. Therefore you need to update the tslint version in your setup.

**Comment by joaomoreno** [comment]
The problem here was an NPE not caught anywhere.

@egamma I've pushed a change to our build scripts which would make them fail in this case. Now we just need to fix the NPE. 👍

**Comment by egamma** [comment]
The NPE is fixed now, closing the issue.
