### ISSUE TITLE
Visual Studio Code takes forever to start and then runs incredibly slowly

### ISSUE THREAD

**Issue by ShaunCurtis** [Microsoft/vscode#18461]
- VSCode Version: Code 1.8.1 (ee428b0eead68bf0fb99ab5fdc4439be227b6281, 2016-12-19T14:49:23.350Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

|Extension|Author|Version|
|---|---|---|
|xml|DotJoshJohnson|1.6.0|
|csharp|ms-vscode|1.5.3|
|PowerShell|ms-vscode|0.7.2|

---
See screenshots for hung application load.  Blank Visual Code window and three Visual Studio Code processes running - one using all processor time.  It takes about 3-5 minutes to load.  Once it loads, clicking on a directory produces the same sequence - 2-5 mins to load - see last screen shot.

Steps to Reproduce:

Same installation runs on other computers - my Windows 10 desktop and Windows 10 Surface Pro 3.
The system is my new dev system. Its a Windows 10 Pro Virtual Machine - running on a Windows Server 2016 host in HyperV.

I've uninstalled Code  and re-installed from the Web.  Same result.
 
![image](https://cloud.githubusercontent.com/assets/24959469/21898649/68e164dc-d8e5-11e6-83c4-0dd707965aac.png)
![capture](https://cloud.githubusercontent.com/assets/24959469/21898761/cfe96968-d8e5-11e6-9a83-dbaeee96db68.PNG)
![image](https://cloud.githubusercontent.com/assets/24959469/21899049/c80db978-d8e6-11e6-9a9d-25968cf40009.png)

**Comment by bpasero** [comment]
@ShaunCurtis single CPU VM?

**Comment by ShaunCurtis** [comment]
Yes, 1 Virtual Processor and 8GB RAM,  It's the only machine currently running on the host - a HP ML110.

See Setup.
![image](https://cloud.githubusercontent.com/assets/24959469/21940129/bae6f23a-d9ba-11e6-929c-7e6024ad7b2b.png)
My Code install is OOB.  no changes to modules.

**Comment by bpasero** [comment]
That is #17097

**Comment by ShaunCurtis** [comment]
I gave the machine 2 Virtual Processors and all works now.
Thanks.
