### ISSUE TITLE
Issue with markdown table

### ISSUE THREAD

**Issue by yanglw** [Microsoft/vscode#1846]
- VS Code version : 0.10.6
- OS system : windows 10 x64

Like this markdwon file :

```
key | value
--- | ---
\| | `|`
a \| b | `a | b`
```

VS Code preview :

![qq 20160107130222](https://cloud.githubusercontent.com/assets/4635831/12162564/e9ba53b4-b53e-11e5-820b-b4a9f4ae1cdd.png)

github preview :

key | value
--- | ---
\| | `|`
a \| b | `a | b`

**Comment by jpoon** [comment]
+1

That's funny, I came across this exact issue just a moment ago. My workaround was to use it's ASCII code: `&#124;`

**Comment by bpasero** [comment]
Fixed!
