### ISSUE TITLE
Doesn't report any errors, warnings. Threats js files as ts

### ISSUE THREAD

**Issue by TheRealSmeddy** [microsoft/vscode#184683]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.79.0
Commit: b380da4ef1ee00e224a15c1d4d9793e27c2b6302
Date: 2023-06-07T14:28:44.251Z
Electron: 22.5.5
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Linux x64 5.19.0-43-generic snap

- OS Version: Ubuntu 22.04.2

Recently after VSCode update to 1.79, I've got this.
Insiders gives the same.
It doesn't show any errors or warnings, instead, I got typescript errors and types on hover and only on hover/
Problems tab is blank.

Started without extensions (also disabled all of them, restarted manually).
Cleared up all user/profile/workspace configs nothing helped.

![image](https://github.com/microsoft/vscode/assets/81646214/5bc2917f-be03-48b8-b611-ddad925a4225)
![image](https://github.com/microsoft/vscode/assets/81646214/5446bef1-5b7f-478c-a7b7-c504dba8bc84)

**Comment by TheRealSmeddy** [comment]
If I am not mistaken, it shouldn't behave like this, or at least it should notify my that I use undeclared value in problems tab.
But instead we get a little ... under the first letter.
![image](https://github.com/microsoft/vscode/assets/81646214/5c9b090d-3139-4553-b58b-4d38f937f00f)

**Comment by mjbvz** [comment]
Try enabling semantic checking: https://code.visualstudio.com/docs/nodejs/working-with-javascript#_type-checking-javascript (it's off by default)

**Comment by TheRealSmeddy** [comment]
You're right brother, thank you!
![image](https://github.com/microsoft/vscode/assets/81646214/3ae86fef-00ff-439f-ae1e-98d155d4043c)
