### ISSUE TITLE
Using the keybind ( ctrl + k, ctrl + o ) to open a folder will cause the new window to not be focused [Linux]

### ISSUE THREAD

**Issue by Robonics** [microsoft/vscode#184639]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: ~~1.78.2~~ 1.79.0
- OS Version: Linux Mint 21.1 Cinnamon 5.6.8 (5.15.0-72-generic kernel)

Steps to Reproduce:

1. Use the chord `ctrl + k` `ctrl + o` to open a folder
2. Prompt an Open Folder dialogue, or open a second Window of VSCode
3. The Open Folder dialogue will open, but will be behind the VSCode window and unfocused

This does not happen when selecting open folder from the `File` menu.

**Comment by Robonics** [comment]
Updated to 1.79.0. Did not fix the issue. I have noticed that it will work in a freshly opened window, but if you have already opened a "Open Folder" dialogue, or if you have multiple windows of VSCode open it will not work as expected.

**Comment by deepak1556** [comment]
Merging to https://github.com/microsoft/vscode/issues/146422
