### ISSUE TITLE
variables in php double quote is not highlighted 

### ISSUE THREAD

**Issue by soohoon90** [Microsoft/vscode#18464]
- VSCode Version: Code 1.8.1 (ee428b0eead68bf0fb99ab5fdc4439be227b6281, 2016-12-19T14:42:49.304Z)
- OS Version: Darwin x64 16.3.0
- Extensions:

|Extension|Author|Version|
|---|---|---|
|vscode-theme-onedark|akamud|0.2.14|
|vscode-great-icons|emmanuelbeziat|1.1.37|
|ftp-simple|humy2833|0.4.14|
|vscode-icons|robertohuertasm|6.0.0|

---

Steps to Reproduce:

1. type "hello, $user" in php file
2. see the problem

**Comment by mjbvz** [comment]
I think the php content has to be inside of a `<?PHP` block:

<img width="269" alt="screen shot 2017-01-12 at 10 30 14 am" src="https://cloud.githubusercontent.com/assets/12821956/21902799/1d75b83c-d8b2-11e6-961f-9a0bd138337a.png">

After adding that, I see the correct colorization
