### ISSUE TITLE
Git Graph interactive rebase and terminal activation conflict

### ISSUE THREAD

**Issue by janhurst** [microsoft/vscode#184671]
Does this issue occur when all extensions are disabled?: N/A

- VS Code Version: 1.79.0
- OS Version: Windows 11

Steps to Reproduce:

1. Build dev container w/ `mhutchie.git-graph` extension installed
2. From Git Graph interface checkout a branch, right click on target and "Rebase current branch on this Commit"

This will trigger a terminal window to activate where the following appears:
![image](https://github.com/microsoft/vscode/assets/16224889/d3c08781-32e5-460e-8020-e89be66341b3)

Terminal activation and the git branch interactive command appear to conflict

**Comment by lszomoru** [comment]
This issue seems to be related to the git-graph extension so I would like to ask you to create an issue in the extension's repository: https://github.com/mhutchie/vscode-git-graph/issues. Thanks!
