### ISSUE TITLE
displaying the signal that caused process termination on terminal not working.

### ISSUE THREAD

**Issue by mohammad-baazza** [microsoft/vscode#184613]
Type: <b>Bug</b>

1 - write a program in c that just sends a SIGSEGV or SIGABRT to itself
2 - compile it
3 - run it
the process will end but the terminal wont print that a segmentation fault or abort occured as expected

VS Code version: Code 1.78.2 (Universal) (b3e4e68a0bc097f0ae7907b217c1119af9e03435, 2023-05-10T14:44:45.204Z)
OS version: Darwin x64 18.7.0
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7500 CPU @ 3.40GHz (4 x 3400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|8.00GB (0.30GB free)|
|Process Argv|-psn_0_122910 --crash-reporter-id be6c40ff-c4e8-4829-8668-aafae2a0717b|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
beyond-debug|coo|0.9.15
doxdocgen|csc|1.4.0
gdb-debug|Dam|1.0.7
ayat|Hus|2.3.3
better-cpp-syntax|jef|1.17.2
42header|kub|0.42.9
codam-norminette-3|Mar|4.5.3
vscode-docker|ms-|1.25.1
remote-containers|ms-|0.292.0
cmake-tools|ms-|1.14.33
cpptools|ms-|1.15.4
cpptools-extension-pack|ms-|1.3.0
makefile-tools|ms-|0.7.0
cmake|twx|0.0.17
vscode-lldb|vad|1.9.2

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263:30335439
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
2e4cg342:30602488
pyind779:30671433
89544117:30613380
pythonsymbol12:30671437
a9j8j154:30646983
showlangstatbar:30737416
vsctsb:30748421
pythonms35:30701012
03d35959:30757346
pythonfmttext:30731395
pythoncmv:30756943
fixhidewlkth:30730051
showsbindicator:30760979
pythongtdpath:30739704
pythonnosm12tcf:30757130

```

</details>

**Comment by meganrogge** [comment]
does this happen in an external terminal?

**Comment by mohammed-ba** [comment]
No

**Comment by meganrogge** [comment]
when you do this , does the terminal just close? a gif would be helpful

**Comment by mohammed-ba** [comment]
i think these screenshots will be useful

<img width="227" alt="Screen Shot 2023-06-08 at 4 29 54 PM" src="https://github.com/microsoft/vscode/assets/115046361/72e3ea47-1378-4092-a3e3-9f3bc1569738">
<img width="296" alt="Screen Shot 2023-06-08 at 4 35 33 PM" src="https://github.com/microsoft/vscode/assets/115046361/bf068a9a-5976-4c2c-b38c-f06be828d709">

**Comment by meganrogge** [comment]
@deepak1556 any thoughts?

**Comment by deepak1556** [comment]
Seems related to https://github.com/microsoft/vscode/issues/184713

@mohammed-ba does `ctrl+c` work in the VSCode terminal ?

**Comment by mohammed-ba** [comment]
@deepak1556 no, it doesnt

**Comment by deepak1556** [comment]
Thanks for confirming, looks like the underlying issue is absence of controlling terminal, merging to https://github.com/microsoft/vscode/issues/184713
