### ISSUE TITLE
explorer does not display any files

### ISSUE THREAD

**Issue by demonsfish** [microsoft/vscode#184695]
Type: <b>Bug</b>

open project，The current Explorer does not display any files，In the current search，Can search for files normally，The editor opened can display the modified，Or open files，And in source code management, modified files can be submitted，Any project opening is the same bug

VS Code version: Code 1.79.0 (b380da4ef1ee00e224a15c1d4d9793e27c2b6302, 2023-06-07T14:26:35.552Z)
OS version: Windows_NT x64 10.0.22621
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10870H CPU @ 2.20GHz (16 x 2208)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.83GB (8.03GB free)|
|Process Argv|F:\\桌面\\集成国网国际项目\\iso --crash-reporter-id f31142c5-5e12-43cd-8ada-7ee4fcc5f607|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (77)</summary>

Extension|Author (truncated)|Version
---|---|---
tailwindcss-extension-pack|and|1.1.4
vscode-ant-design-vue-helper|ant|1.0.6
iconify|ant|0.5.3
tailwind-docs|aus|2.0.0
ajax-query|Bal|0.6.0
antd-snippets|ban|1.2.0
vscode-tailwindcss|bra|0.9.11
node-snippets|chr|1.3.3
npm-intellisense|chr|1.4.4
path-intellisense|chr|2.8.4
cssrem|cip|3.1.0
language-postcss|cpy|1.1.0
postcss|css|1.0.9
vscode-eslint|dba|2.4.0
jquerysnippets|don|0.0.1
gitlens|eam|2023.6.810
vscode-html-css|ecm|1.13.1
prettier-vscode|esb|9.13.0
vscode-firefox-debug|fir|2.9.8
auto-close-tag|for|0.5.14
auto-rename-tag|for|0.1.10
anes|gam|0.0.2
copilot|Git|1.88.132
live-sass|gle|6.0.5
headwind|hey|1.7.0
vscode-htmlhint|HTM|1.0.5
vue|jcb|0.1.5
vscode-gutter-preview|kis|0.30.0
i18n-ally|lok|2.9.1
tailwind-sass-syntax|mac|1.3.0
dotenv|mik|1.0.1
vscode-less|mrm|0.6.3
vscode-docker|ms-|1.25.1
vscode-language-pack-zh-hans|MS-|1.79.2023060709
data-workspace-vscode|ms-|0.5.0
mssql|ms-|1.19.1
sql-bindings-vscode|ms-|0.4.0
sql-database-projects-vscode|ms-|1.1.1
color-highlight|nau|2.5.0
vetur|oct|0.37.3
open-html-in-browser|pea|2.1.10
vscode-tailwindcss-explorer|Pet|0.7.0
vscode-css-peek|pra|4.2.0
java|red|1.19.0
git-commit-plugin|red|1.1.2
LiveServer|rit|5.7.9
html5-boilerplate|sid|1.1.1
swdc-vscode|sof|2.7.0
html-to-css-autocompletion|sol|1.1.2
guides|spy|0.9.3
element-ui-snippets|SS|0.7.2
vscode-stylelint|sty|1.2.4
tailwindcss-transpiler|sud|0.0.8
tabnine-vscode|Tab|3.6.53
css-class-intellisense|tar|4.5.1
open-in-browser|tec|2.0.0
vscode-npm-scripts|tra|0.2.1
uni-app-schemas-vscode|uni|0.8.11
uni-app-snippets-vscode|uni|0.9.5
uni-cloud-snippets-vscode|uni|0.2.8
uni-helper-vscode|uni|0.5.9
uni-highlight-vscode|uni|0.1.6
uni-ui-snippets-vscode|uni|0.6.6
intellicode-api-usage-examples|Vis|0.2.7
vscodeintellicode|Vis|1.2.30
vscode-java-debug|vsc|0.51.0
vscode-java-dependency|vsc|0.23.0
vscode-java-pack|vsc|0.25.11
vscode-java-test|vsc|0.39.0
vscode-maven|vsc|0.41.0
vscode-icons|vsc|12.4.0
volar|Vue|1.6.4
vscode-typescript-vue-plugin|Vue|1.6.5
eno|Wsc|2.3.53
JavaScriptSnippets|xab|1.8.0
axios-snippets|Ygg|1.0.0
html-css-class-completion|Zig|1.20.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscoreces:30445986
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
vscccc:30610679
3biah626:30602489
pyind779:30671433
89544117:30613380
vscrpc:30673769
pythonsymbol12:30671437
showlangstatbar:30737416
vsctsb:30748421
pythonms35:30701012
pythonfmttext:30731395
pythoncmvfstrcf:30756944
fixshowwlkth:30730052
hidesbindicator:30760978
pythongtdpathcf:30739705
dh2dc718:30763024
pythonnosm12tcf:30757130

```

</details>

**Comment by gjsjohnmurray** [comment]
Please use the Start Extension Bisect command to investigate whether the problem is being caused by one of your extensions.

**Comment by lramos15** [comment]
Please try `CTRL+ SHIFT + P` -> `Reset View Locations`

**Comment by demonsfish** [comment]
I disabled all plugins and it's no use. My family's and company's are synchronized.The same goes for the situation at home. I will return to the previous version.Still hasn't solved the problem.I also tried to log out of my account or download again（VScode）

**Comment by demonsfish** [comment]
The problem has been resolved. The folder has been detached from the resource manager separately。I don't know why it separated
