### ISSUE TITLE
Problem with debugging python

### ISSUE THREAD

**Issue by NevisaurusRex** [microsoft/vscode#184601]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.78.2
- OS Version: Windows 11

Steps to Reproduce:

1. Create a python file that uses file handling
2. "Run and Debug" the file

I have been having an issue when debugging files in python. Any files that contain file handling cause errors. However, when running the code normally (without debugging), no errors occur, and the code runs as intended. This includes when using the file open() function, as well as other functions that involve using files, such as in tkinter.
![image](https://github.com/microsoft/vscode/assets/129645676/2b0b6bf8-c2e9-4ca9-afa7-42ff6883197b)
![image](https://github.com/microsoft/vscode/assets/129645676/32b297f5-17d2-4284-9e3e-afe55b8450cb)
The files being used are in the same directory as the program, as can be seen in the second image.
If there is any other information I need to add, let me know. I am very new to VScode.

**Comment by NevisaurusRex** [comment]
This issue strangely has now changed: it affects both when I run the code normally and when I debug. Previously it wasn't a problem when I ran the code normally. I believe that the problem is that the current root directory, according to VScode, is 1 level up, above what it was when I was running the code in other IDEs like IDLE. Instead of the current directory being the directory of the python file I am running (like normal), it is the directory above that, which is weird. Relative file paths do not work because of this.

**Comment by NevisaurusRex** [comment]
What seems to be the problem is that the working directory for running without debugging is the directory the file is in (as is normal). However, when debugging, the working directory appears to be the directory 1 above that. Why is this? How can I fix this?

**Comment by roblourens** [comment]
Please file this on the python extension repo

**Comment by NevisaurusRex** [comment]
managed to fix the issue by modifying my code, but it is still annoying that the cwd for run is different to that for run and debug
