### ISSUE TITLE
Sticky scroll disappears and reappears when deleting lines in a Markdown file

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode#184617]
1. Paste the following markdown text into a markdown file in VS Code, including newlines
```md
start of file







1. bullet point
    - sub bullet point 1
    - sub bullet point 2
    - sub bullet point 3
        - sub sub bullet point
            - sub sub bullet point
        - sub sub bullet point
            - sub sub bullet point
1. bullet point
    - sub bullet point 
        - sub sub bullet point
1. bullet point
    - sub bullet point 
        - sub sub bullet point
1. bullet point
    - sub bullet point 
        - sub sub bullet point
1. bullet point
    - sub bullet point 
        - sub sub bullet point
1. bullet point
    - sub bullet point 
        - sub sub bullet point
1. bullet point
    - sub bullet point 
        - sub sub bullet point
```
2. Scroll down so that sticky scroll shows line 9 and 12
3. Type at the bottom of the file, then delete with ctrl+backspace
4. :bug: sticky scroll disappears for a second, then reappears. This gets pretty distracting over time, also only seems to happen in Markdown files containing deeply nested lists like above

https://github.com/microsoft/vscode/assets/30305945/f5a7a1c3-3caa-49ee-8bfa-ec2c6c41619c

**Comment by aiday-mar** [comment]
Hi @joyceerhl, are you still able to reproduce the issue to this day? I am currently trying to reproduce the issue and am not seeing the flickering. I will be on the lookout for sticky scroll flickering.

**Comment by joyceerhl** [comment]
I cannot repro this anymore 🎉

**Comment by aiday-mar** [comment]
I suspect the flickering may happen whenever the model content changes, but it is visible when the machine is slow. I'll try to reproduce this on an older machine.
