### ISSUE TITLE
Add onDidChangeModelMarkers to IEditor interface

### ISSUE THREAD

**Issue by gatesn** [Microsoft/vscode#18465]
Similar methods such as setModelLanguage have emitters:

[setModelLanguage](https://microsoft.github.io/monaco-editor/api/modules/monaco.editor.html#setmodellanguage)
[onDidChangeModelLanguage](https://microsoft.github.io/monaco-editor/api/modules/monaco.editor.html#ondidchangemodellanguage)

It would be useful to have the same for modelMarkers:

[setModelMarkers](https://microsoft.github.io/monaco-editor/api/modules/monaco.editor.html#setmodelmarkers)
onDidChangeModelMarkers

**Comment by alexandrudima** [comment]
Let's keep the issue in the monaco-editor repository, as it is about the standalone editor and does not have any impact on vscode. Microsoft/monaco-editor#313
