### ISSUE TITLE
First line of terminal isn't really visible when editor is zoomed in

### ISSUE THREAD

**Issue by papaiatis** [Microsoft/vscode#18466]
- VSCode Version: 1.8.1
- OS Version: Ubuntu 16.10

Steps to Reproduce:

1. Zoom in by pressing CTRL & +
2. Open integrated terminal -> the first line isn't really shown, see attached screenshot

![image](https://cloud.githubusercontent.com/assets/3688096/21904703/dcc17148-d904-11e6-850f-24383f727fe4.png)

**Comment by Tyriar** [comment]
Fixed this today, should be in tomorrow's Insiders build
