### ISSUE TITLE
DebugProtocol.Source.presentationHint = "deemphasize" not handled correctly?

### ISSUE THREAD

**Issue by isc-bsaviano** [microsoft/vscode#184640]
In my debugger, I sometimes have StackFrames that have a known named source file, but that file's text isn't available. To represent this, I created a Source object with a name and presentationHint set to "deemphasize", which according to the docs "can be used to indicate that the source is not available or that it is skipped on stepping":
```
{
            id: stackFrameId,
            name: place,
            source: {
              name: routine,
              presentationHint: "deemphasize"
            },
            line,
            column: 1,
}
```
However, VS Code still automatically tries to open the source for the StackFrame. I think that behavior is a conflict with the documentation. If that behavior is expected, how should I represent these frames? I don't want to exclude a Source entirely since the name alone is useful information, but I don't want an editor to open automatically for a document whose text can't be resolved.

**Comment by roblourens** [comment]
This is happening when the deemphasized frame is first in the callstack? 

I think this can happen if the deemphasized frame is the only one available, but we try to skip deemphasized frames and pick the first one off the top that is not deemphasized

**Comment by isc-bsaviano** [comment]
@roblourens Yes, this happens when the deemphasized frame is first in the callstack. In the exact case I'm testing, all 8 frames are deemphasized. I would expect that in this case, none of the frames would be opened.

**Comment by roblourens** [comment]
Hm, I think I agree, and in this case it opens an editor with an error message for you?

**Comment by isc-bsaviano** [comment]
Yes, exactly. I'd like for it to not do that, but still allow me to supply a Source with a name because I have that information. I think using deemphasize to signal this is fine, or allowing a Source without a sourceReference or path.

**Comment by isc-bsaviano** [comment]
@roblourens Thanks for the quick fix! I verified that in the latest insiders the "deempasize" stack frame isn't automatically opened when the debugger breaks.

**Comment by TylerLeonhardt** [comment]
verified based on @isc-bsaviano's comment
