### ISSUE TITLE
Mouse button 4/5 for back forward don't work in insiders build

### ISSUE THREAD

**Issue by jimAtLoyal** [microsoft/vscode#184645]
Type: <b>Bug</b>

workbench.editor.mouseBackForwardToNavigate is set to true for both released and insiders builds, but the buttons only work in the released build. I'm on a Mac M1 Ventura with a Logitech M705 mouse

To reproduce
1. Open a file, click to move the cursor to a few locations
2. Use the back/forward buttons on the mouse and they do nothing.

I ran code --disable-extensions

VS Code version: Code - Insiders 1.79.0-insider (Universal) (c3867859cf3e1a73f3ddce5ad36b3791b7883d88, 2023-06-01T05:26:38.346Z)
OS version: Darwin arm64 22.4.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|5, 7, 6|
|Memory (System)|16.00GB (1.32GB free)|
|Process Argv|--disable-extensions . --crash-reporter-id ab336b3b-928a-4cbb-928e-f29f273c3b25|
|Screen Reader|no|
|VM|0%|
</details>Extensions disabled<details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythontb:30258533
pythonptprofiler:30281269
vshan820:30294714
vscod805:30301674
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30404738
py29gd2263:30754469
cppdebug:30492333
vsclangdf:30492506
c4g48928:30535728
dsvsc012:30540252
pynewext54:30618038
pylantcb52:30590116
pyind779:30611226
pythonsymbol12:30651887
a9j8j154:30646983
showlangstatbar:30737417
pythonms35:30671666
03d35959:30757351
ecj1e332:30687743
pythonfmttext:30716741
pythoncmvfstr:30726892
fixshowwlkth:30724385
hidesbindicator:30724476
pythongtdpath:30726887
dh2dc718:30763024
pythonnosmt12:30757129
pythonidxpt:30763123
pythondjangots:30763122

```

</details>

**Comment by nicoandmee** [comment]
+1. I have this issue and it's incredibly frustrating.

**Comment by jgodwin-kobold** [comment]
FYI, this bug exists in 1.81.1, but you can work around with these instructions:
https://superuser.com/questions/1216047/universal-back-forward-mouse-buttons-in-osx-instead-of-m4-m5

**Comment by bpasero** [comment]
Can people clarify in what version it works and in what version it does not?  Stable is currently on `1.81.x` and insiders is on `1.82.x`.

**Comment by jimAtLoyal** [comment]
I rebooted today and the buttons are working

```
Version: 1.82.0-insider (Universal)
Commit: f1302be1e67e3af5fbeb8bbb2ea784de7bc96150
Date: 2023-09-01T11:10:56.707Z
Electron: 25.8.0
ElectronBuildId: 23503258
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Darwin arm64 22.5.0
```
