### ISSUE TITLE
ShellIntegration for fish is gone

### ISSUE THREAD

**Issue by max06** [microsoft/vscode#184659]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.79.0-insider (system setup)
- Commit: b380da4ef1ee00e224a15c1d4d9793e27c2b6302
- OS Version: Remote on Ubuntu 22.04, Client on Win11

The reverted automated shell integration for fish done in #184363 is incomplete.

While the integration is no longer injected, a manual integration now fails as well because the script can't be found at the generated path.

```fish
 $ set integration (code-insiders --locate-shell-integration-path fish)                                                                                                                             
 $ stat $integration                                                                                                                                                                                
stat: cannot statx '/home/max06/.vscode-server-insiders/bin/b380da4ef1ee00e224a15c1d4d9793e27c2b6302/out/vs/workbench/contrib/terminal/browser/media/shellIntegration.fish': No such file or directory
```

After digging in, I found a directory `fish_xdg_data` in the location where the script should have been. 

```fish
 $ tree fish_xdg_data/                                                                                                                                                                              
fish_xdg_data/
└── fish
    └── vendor_conf.d
        └── shellIntegration.fish
```

Something got messed up :beer:

Just verified: Issue is present in 1.79.0 non-insiders - same git hash.

**Comment by Tyriar** [comment]
Need to bring the change at:

https://github.com/microsoft/vscode/blob/8ffaf6b7cc3306b36627b1d6681ae2a281c98dd1/src/vs/code/node/cli.ts#L103

to:

https://github.com/microsoft/vscode/blob/8ffaf6b7cc3306b36627b1d6681ae2a281c98dd1/src/vs/server/node/server.cli.ts#L148

**Comment by max06** [comment]
Hey @Tyriar,
I took your instructions and created a PR from them. I just can't tell you if it works, I'm unable to build it... Please, feel free to close it if you want to fix it another way.

**Comment by meganrogge** [comment]
verified 

![Image](https://github.com/microsoft/vscode/assets/29464607/bb7a6dfa-2c49-4888-90a1-3f3c81d0711b)

**Comment by max06** [comment]
@rben01 
A workaround would be adding 

```fish
. (path dirname (code --locate-shell-integration-path fish)/fish_xdg_data/fish/vendor_conf.d/shellIntegration.fish)
```

to your fish profile.

**Comment by Tyriar** [comment]
@rben01 the release should have just gone out

**Comment by rben01** [comment]
@Tyriar I updated VSCode and am still seeing the issue. I did not make any changes to my fish config or to anything else.

**Comment by rben01** [comment]
> @Tyriar I updated VSCode and am still seeing the issue. I did not make any changes to my fish config or to anything else. The error I'm seeing is
> 
> ```
> .: Error encountered while sourcing file ''/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/contrib/terminal/browser/media/shellIntegration.fish'':
> .: No such file or directory
> ```

I am still seeing this issue on VSCode 1.80. Fish is version 3.6.1.

**Comment by max06** [comment]
Did you follow the instructions how to manually activate the integration in the past maybe? Is there a chance anything in your environment (vscode settings, dotfiles, ...) would try to load the script for you?
