### ISSUE TITLE
Ctrl-Shift-B does not correctly detect when a process exits when sub-processes are started.

### ISSUE THREAD

**Issue by aardappel** [microsoft/vscode#18470]
- VSCode Version: 1.8.1
- OS Version: Windows 10

Steps to Reproduce:

1. Launch build task A.exe (Ctrl-Shift-B)
2. A.exe launches B.exe, then quits.
3. Try to build again (Ctrl-Shift-B)
4. Get "there is an active task running right now"
5. Press "terminate".
6. Get error "the launched task doesn't exist anymore"
7. Be stuck in loop 3..6 until you quit and restart VSCode, or manually quit the unrelated B.exe.

Here, B.exe is a deamon process needing to be active for all runs of A.exe, which gets started on first run of A.exe. Quitting B.exe on each run is unpractical.

**Comment by dbaeumer** [comment]
@aardappel how do you launch B.exe. VS Code waits until the streams passed to A.exe (stdio) are closed because under node the signaled exit doesn't necessarily mean that all data written to stdio has arrived in VS Code. If B.exe inherits the stdio stream then code still thinks that data is to be read. Could you try to launch B.exe in full detached mode without inheriting streams?

**Comment by aardappel** [comment]
This is not something I have control over. B is SteamVR actually, was trying to state it in general terms. It is launched by a library that I don't have the source to (https://github.com/ValveSoftware/openvr). I was assuming it is a more general problem. I can open a bug there if this is not fixable in VSCode.

**Comment by dbaeumer** [comment]
The only way how I think that could be addressed in VS Code is an optional flag describing when VS Code think the process has terminated. As said, listening to exit only has the potential of loosing output since that event can occur before all data is read. 

Need to think about it a little more.

**Comment by aardappel** [comment]
Ah, so it is a bug in Windows that output of a process can happen after it exits? Just kidding :)

Maybe just allow the user to specify N seconds to wait for more output after the process exits? That way they can set it at 0 if they don't care, and if they set it at 3 or so unlikely more output is coming. With the default being the current "indefinite".

**Comment by dbaeumer** [comment]
It is how NodeJS API is speced (which atucally does make sense considering process chains like yours :-)).

**Comment by aardappel** [comment]
You're saying the API has a timeout? Maybe expose it then? :)

**Comment by dbaeumer** [comment]
No. The Node API sends to events on processes 'exit' and 'close'. 'Close' signals that the stdio streams associated with the process are closed. 'exit' that the process exited. In your example we receive an 'exit' but no 'close' ('exit' can always come before 'close'). To not loose data we assume that the process is still active if the stdio streams are still open.

**Comment by Balderick** [comment]
So A.exe = openvr app and B.exe = openvr runtime?

Subnautica appears to be a real life example of what is described in op.

**Comment by alexr00** [comment]
This sounds like it was an issue with tasks v1, which is no longer supported.
