### ISSUE TITLE
TypeScript Codelens keeps scrolling the window while typing

### ISSUE THREAD

**Issue by rebornix** [Microsoft/vscode#18474]
- VSCode Version: 1.9.0-Insiders
- OS Version: macOS

The easy way to reproduce is making changes to a command in code 

![typescript-codelens](https://cloud.githubusercontent.com/assets/876920/21909243/e8ed5538-d8cb-11e6-8a4d-771fcee96e2c.gif)

**Comment by mjbvz** [comment]
I think 8bfcb15 fixed things but please let me know if you see this again

References code lens should actually now be usable in the vscode workspace :)

**Comment by jrieken** [comment]
I still see it jumping, maybe not as much but it seems like TypeScript discards all existing lenses in the presence of a syntax error (which happens often while you type). The extension should be smarter and not discard existing lenses so aggressively

![jan-27-2017 10-53-28](https://cloud.githubusercontent.com/assets/1794099/22366883/240c403e-e47f-11e6-9119-de3f61918a90.gif)

**Comment by mjbvz** [comment]
Pushing to February. The original issue was much worse and should be fixed now.

Your example shows that if a class definition (the `class Foo` part) becomes invalid while editing a line , we clear all code lenses for that class. Lenses for the rest of the file outside the class should be unaffected. You can have syntax errors inside methods or classes, but syntax errors in the definition line itself could be handled better

**Comment by kevinbarabash** [comment]
I'm seeing this in the Gitlens plugin as well.
