### ISSUE TITLE
Voiceover selection and deselection commands don't work with the Explorer view

### ISSUE THREAD

**Issue by mohammad-suliman** [microsoft/vscode#184788]
Type: <b>Bug</b>

1. Run Voiceover along with VS Code
2. Open any folder in the Explorer view and navigate to it
3. Try to deselect the currently selected folder by hitting VO + Return
4. Try to multi-select by hitting Vo + Command + Return to start multi-selection for the current item, and then navigate with the VO cursor for the next item to select, and when you reach it, hit VO + Return to add it to selection

Expected behavior:
All mentioned commands work like they do in the Finder files table view for example
Actual behavior:
None of the mentioned commands work in the Explorer file view table

Notes:
1. I faced the issue when I tried to deselect a folder - when I tried to move an item inside it to be besides it on the same level. The task isn't doable without using VO mouse rooting and clicking commands.
2. [Here is Apple Support documentation for the mentioned commands](https://support.apple.com/en-il/guide/voiceover/vo2735/mac)

VS Code version: Code - Insiders 1.79.0-insider (b380da4ef1ee00e224a15c1d4d9793e27c2b6302, 2023-06-07T14:33:06.501Z)
OS version: Darwin arm64 22.6.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Max (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|32.00GB (8.05GB free)|
|Process Argv|--crash-reporter-id 0c4f24aa-01c3-4fbf-885f-bf6ebffe0b33|
|Screen Reader|yes|
|VM|0%|
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythontb:30258533
pythonptprofiler:30281269
vshan820:30294714
vscod805:30301674
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30404738
py29gd2263:30763246
cppdebug:30492333
vsclangdf:30492506
c4g48928:30535728
dsvsc012:30540252
pynewext54:30618038
pylantcb52:30590116
pyind779:30611226
pythonsymbol12:30651887
showlangstatbar:30737417
pythonms35:30671666
03d35959:30757351
57b77579:30687741
pythonfmttext:30716741
pythoncmvfstr:30726892
fixshowwlkth:30724385
hidesbindicator:30724476
pythongtdpath:30726887
dh2dc718:30763024
pythonnosmt12:30757129
pythonidxpt:30763123
pythondjangots:30763122

```

</details>

**Comment by mohammad-suliman** [comment]
@isidorn

**Comment by meganrogge** [comment]
We use a list rather than a table in the explorer view so it is not expected for it to behave like a table.

We should provide a way to do this though via only the keyboard 

> I faced the issue when I tried to deselect a folder - when I tried to move an item inside it to be besides it on the same level. The task isn't doable without using VO mouse rooting and clicking commands.

**Comment by meganrogge** [comment]
@mohammad-suliman has this ever worked in VS Code?

wondering if it's related to this upstream issue https://bugs.chromium.org/p/chromium/issues/detail?id=1301373

**Comment by mohammad-suliman** [comment]
I am closing this issue because I am able to achieve the afor mentioned task. Besides, Escape now deselects selected files now, atleast now VO reports this currently.
