### ISSUE TITLE
Sourcemaps are broken in building from source

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#18475]
`"sourceRoot":"file:///Users/roblou/code/vscode","sources":["vs/workbench/services/search/node/textSearch.ts"]`

Missing the `src` path segment.

**Comment by roblourens** [comment]
@joaomoreno It works when I undo the change in 1c38df7823b50c6ca09e7a721fbf94a373db9cf8, and use options.sourceRoot instead, which makes sense, because the `path.dirname` will drop the `/src` from rootDir. Has something else changed?

**Comment by joaomoreno** [comment]
Run `./scripts/npm.sh install`, @bpasero has fixed this.
