### ISSUE TITLE
Cannot disable Open Editors by setting explorer.openEditors.visible to 0

### ISSUE THREAD

**Issue by iutlu** [microsoft/vscode#184705]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.79.0
- OS Version: macOS Ventura 13.0.1

Steps to Reproduce:

1.  Set `explorer.openEditors.visible` to `0` in `~/Library/Application Support/Code/User/settings.json`
2. The settings editor nags that`Value is below the minimum of 1.`

Setting this to 0 used to be allowed, and was the way to disable the "Open Editors" functionality completely. This no longer works.

**Comment by caweidmann** [comment]
Running into same issue, cannot hide open editors. Is there a new setting for it perhaps?

**Comment by lramos15** [comment]
It was removed in favor of the normal view controls in VS Code. Click the three dots in the top right of the open editors view and check off open editors.

**Comment by Basicbydesign** [comment]
Is it possible to achieve the same thing in a config file or by cli?
