### ISSUE TITLE
Add the ability to do imports using drag and drop

### ISSUE THREAD

**Issue by VyacheslavKolodrubskiy** [microsoft/vscode#184714]
I found this [Drag And Drop Import Relative Path](https://marketplace.visualstudio.com/items?itemName=ElecTreeFrying.drag-import-relative-path) extension that allow do import using drag and drop, and it's very cool, but it doesn't work in React or Vue files, please add this feature by default to the vscode, it will save a lot of time and effort

**Comment by mjbvz** [comment]
We leave this up to individual language extensions to support. Please file feature requests against those extensions / languages to enable this feature
