### ISSUE TITLE
Run Python selection opens an extra terminal window

### ISSUE THREAD

**Issue by selgamal-telnyx** [microsoft/vscode#184790]
Type: <b>Bug</b>

1- Create new .py file
2- Write line, example "import sys"
3-Right click the line and select Run Python > Run Selection/Line in python terminal

VS Code version: Code 1.79.0 (b380da4ef1ee00e224a15c1d4d9793e27c2b6302, 2023-06-07T14:26:35.552Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Remote OS version: Linux x64 5.15.90.1-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz (8 x 1805)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.73GB (19.23GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Debian|
|OS|Linux x64 5.15.90.1-microsoft-standard-WSL2|
|CPUs|11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz (8 x 1804)|
|Memory (System)|15.49GB (13.87GB free)|
|VM|0%|
</details><details><summary>Extensions (18)</summary>

Extension|Author (truncated)|Version
---|---|---
dotenv|mik|1.0.1
jupyter-keymap|ms-|1.1.2
remote-ssh|ms-|0.102.0
remote-ssh-edit|ms-|0.86.0
remote-wsl|ms-|0.79.4
remote-explorer|ms-|0.4.0
better-toml|bun|0.3.2
isort|ms-|2022.8.0
python|ms-|2023.10.0
vscode-pylance|ms-|2023.6.10
jupyter|ms-|2023.5.1001582324
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.15
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-slideshow|ms-|0.1.5
vscode-xml|red|0.25.0
LiveServer|rit|5.7.9
code-spell-checker|str|2.20.4

</details>

**Comment by selgamal-telnyx** [comment]
Add screen capture

https://github.com/microsoft/vscode/assets/117951564/ffa0c153-3bb2-47d5-a55e-ca7c406ea04d

**Comment by aleewen** [comment]
I'm having the exact same issue as well in Ubuntu

**Comment by KatlehoJordan** [comment]
> I'm having the exact same issue as well in Ubuntu. I believe it's a problem with the Python Extension in VSCode. Go ahead an rollback to the previous version and see if that fixes it.

Great tip!

Rolling back to v2023.8.0 fixed this issue for me. Thank you!

**Comment by ctedja** [comment]
Was struggling with this issue all night last night but rolling it back to v.2023.8.0 also worked for me. **Thank you**! 

Also will be following this issue here to see if any changes.
https://github.com/microsoft/vscode-python/issues/21393

**Comment by meganrogge** [comment]
/duplicate https://github.com/microsoft/vscode-python/issues/21393

**Comment by KatlehoJordan** [comment]
> /duplicate https://github.com/microsoft/vscode-python/issues/21393

I suggest closing this issue.

This was a bug with the vscode python extension, and the bug was crushed. 🪲💀

Please update your extensions as per this other ticket. If the issue persists, consider opening a new ticket referencing the one where the vscode python team crushed this bug, as it would suggest a regression.

**Comment by hse1223** [comment]
> > > > I'm having the exact same issue as well in Ubuntu. I believe it's a problem with the Python Extension in VSCode. Go ahead an rollback to the previous version and see if that fixes it.
> > > 
> > > 
> > > Great tip!
> > > Rolling back to v2023.8.0 fixed this issue for me. Thank you!
> > 
> > 
> > What does it mean by "Roll back"? Does it mean uninstalling the current vs code and then reinstalling a new one of v2023.8.0?
> 
> Go to the Python extension within VSCode and click the down arrow next to 'Uninstall' and select 'Install Another Version' and choose v2023.8

Understood. Thank you.
