### ISSUE TITLE
Autocomplete adds word ending when it already exists

### ISSUE THREAD

**Issue by notiv-nt** [microsoft/vscode#184736]
Does this issue occur when all extensions are disabled?: **Yes**

- VS Code Version: 1.79.0
- OS Version: Win 10

Steps to Reproduce:

1. Just use autocomplete in the middle of any words

https://github.com/microsoft/vscode/assets/10743009/f1d33216-4bf3-49cf-bb29-ce2b39af39e6

#### Expected behavior:

Autocomplete should complete the word under the cursor, not append from the cursor

**Comment by jrieken** [comment]
This can be configured via `editor.suggest.insertMode`
