### ISSUE TITLE
extensions doesn't work

### ISSUE THREAD

**Issue by CrisDan1905** [Microsoft/vscode#18478]
- VSCode Version: Code 1.8.1 (ee428b0eead68bf0fb99ab5fdc4439be227b6281, 2016-12-19T14:41:20.664Z)
- OS Version: Linux x64 4.4.0-59-generic
- Extensions:

|Extension|Author|Version|
|---|---|---|
|theme-monokai-dark-soda|AdamCaviness|0.0.5|
|theme-dark-monokai|bogdan-sinitsa|0.3.0|
|vscode-icons|robertohuertasm|6.0.0|

---

Steps to Reproduce:

1.
2.

I have installed some extensions and none of them works at all, it's like been installed nothing

**Comment by mjbvz** [comment]
A few questions:

* Have you restarted VSCode? VSCode must be restarted for extensions to load properly after they are installed
* Do you see the extensions listed as installed in the VSCode extension panel?
* What is the output of running `code --list-extensions` on a command line?

**Comment by CrisDan1905** [comment]
I terribly sorry mate, it's just I forgot to activate those extensions on preferences. Long time since I configured those parameters at my old O.S. and just forgot it, thanks very much anyway for answer me!

**Comment by mjbvz** [comment]
@CrisDan1905 Glad to hear.

Closing since it sounds like the issue has been resolved
