### ISSUE TITLE
Python intellisense and autocomplete not working as expected.

### ISSUE THREAD

**Issue by Ogami-Ku** [Microsoft/vscode#18471]
- VSCode Version: Code 1.8.1 (ee428b0eead68bf0fb99ab5fdc4439be227b6281, 2016-12-19T14:41:20.664Z)
- OS Version: Linux x64 4.4.41-1-lts
- Extensions:

|Extension|Author|Version|
|---|---|---|
|python|donjayamanne|0.5.5|

---
After installing the extension mentioned above intellisense and autocomplete for python not working as expected. Even pressing "Ctrl+Space" doesn't help. If I want to type "class" and I typed "cl" then pressed "Ctrl+Space"  it keeps "loading..." and nothing happens and I have to delete it then press "Ctrl+Space" or it shows on its own.

![vscode](https://cloud.githubusercontent.com/assets/11742610/21907170/1e380ed6-d917-11e6-8ad1-ac8c0b336fd8.gif)

**Comment by mjbvz** [comment]
This issue was moved to DonJayamanne/pythonVSCode#640
