### ISSUE TITLE
Cannot watch for file changes for files on disk root

### ISSUE THREAD

**Issue by potasiyam** [Microsoft/vscode#1847]
Code version: 0.10.6
OS: Windows 10 x64

I have noticed that if a file is open in code and the file is changed externally, there is no way to know about it until I try to save it. I feel that if the file on the disk and file opened on code is in same state it should automatically reflect the changes made on the disk. This is what every modern text  editor do.
Here is how to reproduce it.
* Create a text file.
* Open the file in Sublime text, Bracket and Code. In this situation the file is blank in all 3 editors.
* In Sublime text, write "Hello". Then save.
* Switch to Bracket, You will see "Hello".
* Switch to Code, you will see blank.
* Now again switch to Bracket, write "Hello world". Then save.
* Switch to Sublime text, You will see "Hello world".
* Switch to Code, you will see blank.

In both cases Code should reflect the changes made on disk.

**Comment by bpasero** [comment]
@potasiyam can you run "code --verbose" and open the dev tools console to see file events logged and retry and send the output here?

**Comment by potasiyam** [comment]
Here is the log in verbose mode.
```
### VSCode main.js ###
c:\Program Files (x86)\Microsoft VS Code\resources\app { pathArguments: [],
  programStart: 0,
  workers: -1,
  enablePerformance: false,
  verboseLogging: true,
  debugPluginHostPort: undefined,
  debugBrkPluginHost: undefined,
  logPluginHostCommunication: false,
  firstrun: false,
  openNewWindow: false,
  openInSameWindow: false,
  gotoLineMode: false,
  pluginHomePath: undefined,
  pluginDevelopmentPath: undefined,
  pluginTestsPath: undefined,
  disablePlugins: false }
Lifecycle#unload() 1
IPC#vscode-workbenchLoaded
```
The opened file was changed several time with other editors. No reflection of that in code window.

**Comment by potasiyam** [comment]
Actually nothing appears in the console when the file is externally changed.
![capture](https://cloud.githubusercontent.com/assets/767359/12215127/246cf71e-b6d9-11e5-96b5-2a60e7d10752.PNG)

**Comment by bpasero** [comment]
I think in your case you opened just a file, can you try the same thing with opening its parent folder and see if then the updates happen? Also, is this G: drive something you created with SUBST or a real physical drive?

**Comment by potasiyam** [comment]
Opening the parent folder solves it. I created a folder then put the file in there and opened the folder in code. Now it updates immediately with external changes.
My G: drive is a physical drive.
So it doesn't work with single files, right?

**Comment by bpasero** [comment]
I can reproduce, this only seems to happen for files that are on the root of the disk: https://github.com/nodejs/node/issues/4643

**Comment by bpasero** [comment]
This issue was fixed meanwhile in node.js and we updated to a newer Electron version.
