### ISSUE TITLE
code-settings-sync  Shan  2.4.2  hava a problem

### ISSUE THREAD

**Issue by yy7054wyq5** [Microsoft/vscode#18479]
- VSCode Version: Code 1.8.1 (ee428b0eead68bf0fb99ab5fdc4439be227b6281, 2016-12-19T14:49:23.350Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions:

|Extension|Author|Version|
|---|---|---|
|html-snippets|abusaidm|0.0.18|
|project-manager|alefragnani|0.12.2|
|jquerysnippets|donjayamanne|0.0.1|
|vscode-great-icons|emmanuelbeziat|1.1.37|
|vscode-angular2-emmet|jakethashi|1.0.9|
|code-settings-sync|Shan|2.4.2|

---

Steps to Reproduce:

1.code-settings-sync Shan 2.4.2 
if i Disable this extension. 
vscode will not show this problem.

**Comment by mjbvz** [comment]
Please try opening an issue against the extension: https://github.com/shanalikhan/code-settings-sync
