### ISSUE TITLE
The connection to the terminal

### ISSUE THREAD

**Issue by Mayer-04** [microsoft/vscode#184791]
Type: <b>Bug</b>

 The connection to the terminal's pty host process is unresponsive, the terminals may stop working.

VS Code version: Code 1.79.0 (b380da4ef1ee00e224a15c1d4d9793e27c2b6302, 2023-06-07T14:26:35.552Z)
OS version: Windows_NT x64 10.0.22621
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz (8 x 2419)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|7.80GB (3.27GB free)|
|Process Argv|--crash-reporter-id a8cdbbfe-2a5a-4fa2-9a09-521dd69fa7b6|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|16.0.0
vscode-tailwindcss|bra|0.9.11
vscode-deno|den|3.19.1
auto-close-tag|for|0.5.14
vscode-gutter-preview|kis|0.30.0
git-graph|mhu|1.30.0
fluent-icons|mig|0.0.18
symbols|mig|0.0.11
mongodb-vscode|mon|1.0.1
live-server|ms-|0.4.8
material-icon-theme|PKi|4.28.0
vscode-thunder-client|ran|2.7.6
LiveServer|rit|5.7.9
errorlens|use|3.11.1
pretty-ts-errors|yoa|0.4.1

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
3biah626:30602489
pyind779:30671433
89544117:30613380
vscrpc:30673769
pythonsymbol12:30671437
2i9eh265:30646982
showlangstatbar:30737416
vsctsb:30748421
pythonms35:30701012
03d35959:30757346
pythonfmttext:30731395
pythoncmv:30756943
fixshowwlkth:30730052
hidesbindicator:30760978
pythongtdpath:30739704
dh2dc718:30763024
pythonnosmt12:30757131

```

</details>

**Comment by OverTheSunshine** [comment]
My colleagues and I also encountered the same problem. At present, we can temporarily solve the problem by going back to 1.78.0.

**Comment by OverTheSunshine** [comment]
My colleagues and I have also encountered the same problem. We have returned to version 1.78.0, which can avoid the problem temporarily.

**Comment by Mayer-04** [comment]
Thanks for sharing your experience with the problem.
