### ISSUE TITLE
React components cannot include JSX namespace names ts(2639)

### ISSUE THREAD

**Issue by Ellested** [microsoft/vscode#184760]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.79
- OS Version: Windows Version 10.0.19044 Build 19044
- TypeScript version 5.0.2

Steps to Reproduce:

1. Add (XML) namespace to a JSX tag `<myns:Component/>`
2. Tag is now getting reported as an error

We are using this feature with custom transformers, can it be disabled by configuration?

**Comment by mjbvz** [comment]
What typescript version are you using?

**Comment by Ellested** [comment]
Sorry, I have updated the versions now

**Comment by mjbvz** [comment]
Did that fix the issue? What version are you using now?

**Comment by Ellested** [comment]
Sorry, didn't get a notification on this one. 
I updated the versions in the issue header - not the software.
So the issue should be correctly filled out now with the version information, sorry for the confusion.

**Comment by mjbvz** [comment]
Thanks. JSX namespaces are only supported TS 5.1+ https://devblogs.microsoft.com/typescript/announcing-typescript-5-1/#namespaced-jsx-attributes

Please try upgrading to that TS version
