### ISSUE TITLE
Change of docstring color in Python

### ISSUE THREAD

**Issue by zucchet-julien** [microsoft/vscode#184889]
Type: <b>Bug</b>

Hi,
I recently updated VSCode to the May 2023 version 1.79. I use VS Code for Python and the color of my dostrings changed from orange/brown (the usual color for strings) to green (the usual color for comments). I did not find how to change this setting.

VS Code version: Code 1.79.0 (Universal) (b380da4ef1ee00e224a15c1d4d9793e27c2b6302, 2023-06-07T14:29:00.206Z)
OS version: Darwin arm64 22.5.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M2 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|3, 4, 3|
|Memory (System)|16.00GB (0.06GB free)|
|Process Argv|--crash-reporter-id 66fa3fa8-f0b9-497f-9da7-c93146a573fe|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (22)</summary>

Extension|Author (truncated)|Version
---|---|---
githistory|don|0.6.20
gitlens|eam|13.6.0
copilot|Git|1.88.132
vscode-pull-request-github|Git|0.66.0
git-graph|mhu|1.30.0
eps-preview|mkv|0.4.0
vscode-language-pack-fr|MS-|1.79.2023060709
autopep8|ms-|2023.4.0
isort|ms-|2022.8.0
python|ms-|2023.10.0
vscode-pylance|ms-|2023.6.10
jupyter|ms-|2023.5.1001582324
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.15
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-slideshow|ms-|0.1.5
remote-wsl|ms-|0.79.4
autodocstring|njp|0.6.1
vscode-python-typehint|njq|1.5.1
intellicode-api-usage-examples|Vis|0.2.7
vscodeintellicode|Vis|1.2.30
vscodeintellicode-completions|Vis|1.0.22

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263:30335439
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
vscccc:30610679
3biah626:30602489
pyind779:30671433
f6dab269:30613381
pythonsymbol12:30671437
2i9eh265:30646982
showlangstatbar:30737416
vsctsb:30748421
pythonms35:30701012
pythonfmttext:30731395
pythoncmvfstrcf:30756944
fixhidewlkth:30730051
hidesbindicator:30760978
pythongtdpathcf:30739705
dh2dc718:30763024

```

</details>

**Comment by zucchet-julien** [comment]
Update : a workaround can be found in https://github.com/microsoft/vscode/pull/182162

**Comment by lkct** [comment]
Actually I already opened an issue summarizing where we are about this problem: #184836
And now I'm proposing to revert this change: #184938
