### ISSUE TITLE
Issue: Autocomplete not working for embedded JS exports

### ISSUE THREAD

**Issue by vincent-ly** [Microsoft/vscode#18482]
I noticed I don't get code completion for exports that are defined inside script tags for .vue files. 

Vue single file component:

![71579e79f1c1d2c45a0adc75e82874dd](https://cloud.githubusercontent.com/assets/2602146/21915984/276d08b4-d8f2-11e6-8024-bdab486d44b5.png)

Imported into another file:

![9cfa7ce63be30e53622e1ea2f6b3f6b1](https://cloud.githubusercontent.com/assets/2602146/21916003/458ef44c-d8f2-11e6-902a-7bf225efaa5c.png)

**Comment by mjbvz** [comment]
Try using the [vetur extension](https://marketplace.visualstudio.com/items?itemName=octref.vetur) for working with `.vue` file. I believe this should provide intellisense for your example

**Comment by vincent-ly** [comment]
Thanks @mjbvz. It looks like the developer for that plugin is already working towards a solution.

https://github.com/octref/vetur/issues/26#issuecomment-295420611
