### ISSUE TITLE
References Window Immediately Dismissed When Selecting Peek Definition From Command Pallet 

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#18483]
- VSCode Version: 1.8.1
- OS Version: Mac 10.11.6 

Steps to Reproduce:

1. Create ts file:

```ts
function abc() { };
abc()
```

2. Put selection on last line in `abc`
3. From command pallet, run `peek definition`.
4. Select the `peek definition` command with <kbd>enter</kbd>, but hold the enter key a moment.

**Expected Behavior**
Peek is shown. Enter key must be pressed again to navigate to a reference

**Actual behavior**
If the enter key is pressed when the references window shows, we navigate to that reference. This ends up causing the references window to flash quickly and then be dismissed:

![jan-12-2017 18-15-15](https://cloud.githubusercontent.com/assets/12821956/21916111/17dbecca-d8f3-11e6-9bb1-797c247abfb7.gif)

You have to be very quick when pressing  <kbd>enter</kbd> to accept the `peek definition` command from the command pallet to avoid this.

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/6146
