### ISSUE TITLE
路径 d:\Downloads\VSCode-win32-1.9.0-insider\resources\app\extensions\typescript\node_modules\typescript\lib 未指向有效的 tsserver 安装。将禁用 TypeScript 语言功能。

### ISSUE THREAD

**Issue by ydcoming** [Microsoft/vscode#18489]
- VSCode Version:
- OS Version:

Steps to Reproduce:

1.VSCode-win32-1.9.0
2.

**Comment by ydcoming** [comment]
my steps 
1. 下载官网的 VSCode-win32-1.9.0-insider,并且解压。
2 打开一个目录文件夹 
3 目录的文件内容是这个 :https://github.com/Microsoft/vscode-samples/tree/master/node-express-javascript。
4.打开目录下的app.js. 就会出现这个问题。

**Comment by ydcoming** [comment]
I found the reason. I downloaded VSCode-win32-1.9.0 version of vscode. it is a zip file.It is a non installed version of vscode. 360 antivirus software prompts him to be malicious files, and then delete him.
![bi 3 d t30 3e39vq_aeus2](https://cloud.githubusercontent.com/assets/3353702/21922075/626cc23c-d9a7-11e6-8721-b46a32995316.png)
![bi 3 d t30 3e39vq_aeus2](https://cloud.githubusercontent.com/assets/3353702/21922081/740c1830-d9a7-11e6-9634-0054a1745095.png)

**Comment by f111fei** [comment]
看你是天朝人就用中文说好了。 出现这个问题的原因是你自己在配置里面设置了`typescript.tsdk` 的路径。 然后你下载了流氓软件360，360认为tsserver.js这个文件是病毒把这个目录这个文件干掉了。

解决办法是把你的配置还原一下,不要设置`typescript.tsdk`  或者 卸载流氓软件360

**Comment by ydcoming** [comment]
你好 你说的不对。首先我没有设置typescript.tsdk 所以配置是没有问题。其次，你可以看我上面说找到原因的描述。我是从官网下载的Insiders版本的zip,不是安装版本.也就是说安装版的没有问题，另外我也测试了下，把安装版本的复制到另外一个目录 国内的软杀也会删除tsserver.js这个文件。ps：大天朝万岁 哈哈

**Comment by scriptkitz** [comment]
😄...
见到国人

**Comment by ydcoming** [comment]
@scriptkitz 360被我告到这里了

**Comment by mjbvz** [comment]
Ok, sounds like the cause is external. Closing since we cannot fix this

As a workaround, try setting `"typescript.tsdk"` to a local or global install of typescript
