### ISSUE TITLE
Release notes video is not working

### ISSUE THREAD

**Issue by VijayakumarMariappan** [microsoft/vscode#184875]
- VS Code Version: 1.79.0
- OS Version: macOS ventura

Steps to Reproduce:

1. Open this link https://code.visualstudio.com/updates/v1_79#_new-tab-sizing-option-fixed.
2. You can note that the video clip not working.
<img width="697" alt="image" src="https://github.com/microsoft/vscode/assets/92971875/4f6a4fbe-d0c7-4398-9758-3a45a66ffdda">

**Comment by mjbvz** [comment]
Works for me:

<img width="781" alt="Screenshot 2023-06-12 at 8 02 25 AM" src="https://github.com/microsoft/vscode/assets/12821956/b993e842-dc5f-4083-ac8c-12736e75d42a">

Closing since this seems like an issue with your browser instead of with VS Code itself
