### ISSUE TITLE
Improve UI/UX of 3-way merge editor

### ISSUE THREAD

**Issue by garysassano** [microsoft/vscode#184834]
I'd like the 3-way merge editor in VS Code to look like the one in PyCharm:
- local changes on the left
- remote changes on the right
- result in the middle

This layout makes way easier to see all at once and it saves time by not having to scroll down to look at the result.

![3way-merge-editor-pycharm](https://github.com/microsoft/vscode/assets/10464497/b90f45d0-b7b4-4734-b8b8-70b793bf8b34)

**Comment by hediet** [comment]
You can toggle the layout in the ... menu.

**Comment by garysassano** [comment]
@hediet Which menu are you referring to? I see no option to change the 3-way merge editor layout so that the result gets shown as a third central column instead of being placed at the bottom.
