### ISSUE TITLE
vscode.dev - Tunnel missing icons from extension

### ISSUE THREAD

**Issue by ayk** [microsoft/vscode#184858]
Tried with differenct icon extensions and different servers (external root server, home desktop, etc.).
Whenever I install an icon extension (in my example Material Icon Theme) and activate them, the icons are not shown in browser (source url showing: url('https://vscode.dev/loopback?{"$mid":1,"path":"/c:/Users/AT.DESKTOP-799Q1C4/.vscode-server/extensions/pkief.material-icon-theme-4.28.0/icons/folder.svg","scheme":"vscode-remote","authority":"tunnel+desktop-799q1c4"}')

Anyone else facing this issue?

Version: 1.79.0
Commit: b380da4ef1ee00e224a15c1d4d9793e27c2b6302
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36
Embedder: vscode.dev

**Comment by connor4312** [comment]
Please ensure you have not disabled service workers in your browser, and you may also want to hard refresh to ensure you're using the latest version.

**Comment by josejefferson** [comment]
I'm facing same issue
