### ISSUE TITLE
ctrl+c doesn't exit commands in terminal

### ISSUE THREAD

**Issue by Tucsky** [microsoft/vscode#184837]
Does this issue occur when all extensions are disabled?: yes

- VS Code Version: 1.79.0 (07/06/2023) (**3 days ago**)
- OS Version: OSX 10.14.16

Steps to Reproduce:

0. In the vscode terminal (any terminal, bash zsh, it doesn't matter)
1. Run a command - sleep 10 for example - then immediately press ctrl+c
2. and it doesn't exit that command

It's been like that **for more than a month** now, what are you guys doing 😅 

![2023-06-11 14 52 02](https://github.com/microsoft/vscode/assets/5738336/c69cc8e1-db16-4b9c-9e8d-c2a8de8a3ddf)

There is no error in console like https://github.com/microsoft/vscode/issues/181939 thus why I created this issue

Version: 1.79.0
Commit: b380da4ef1ee00e224a15c1d4d9793e27c2b6302
Date: 2023-06-07T14:29:00.206Z (3 days ago)
Electron: 22.5.5
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Darwin x64 18.7.0

**Comment by uovol** [comment]
I have the same problem.

**Comment by uovol** [comment]
I have the same problem.

**Comment by Tyriar** [comment]
@meganrogge this might be a mac only issue, can you reproduce?

**Comment by meganrogge** [comment]
does disabling shell integration via `terminal.integrated.shellIntegration.enabled` fix it?

**Comment by Tyriar** [comment]
Also have you manually installed shell integration? Check your .zshrc/etc. scripts

**Comment by Tucsky** [comment]
> Also have you manually installed shell integration? Check your .zshrc/etc. scripts

ctrl+c works as expected on the osx terminal app, which uses zshrc as well

I did tried removing my .zshrc file to see it that was the cause but beside changing the theme of the terminal and name format, the ctrl+c remains unsuccessful 

> does disabling shell integration via `terminal.integrated.shellIntegration.enabled` fix it?

I tried set to false, restarted terminal, or even vscode, no change...

**Comment by Naji-k** [comment]
👍

**Comment by ycalm** [comment]
> > Also have you manually installed shell integration? Check your .zshrc/etc. scripts
> 
> ctrl+c works as expected on the osx terminal app, which uses zshrc as well
> 
> I did tried removing my .zshrc file to see it that was the cause but beside changing the theme of the terminal and name format, the ctrl+c remains unsuccessful
> 
> > does disabling shell integration via `terminal.integrated.shellIntegration.enabled` fix it?
> 
> I tried set to false, restarted terminal, or even vscode, no change...

I tried the same operation, but ctrl + c doesn't work

Version: 1.79.0 (Universal)
Commit: b380da4ef1ee00e224a15c1d4d9793e27c2b6302
Date: 2023-06-07T14:29:00.206Z
Electron: 22.5.5
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Darwin x64 18.7.0

**Comment by AceYangWQ** [comment]
So do I

**Comment by huaigu** [comment]
I have same issue on my mac os.
crtl +c is not working on vscode.
> Version: 1.79.2
Commit: 695af097c7bd098fbf017ce3ac85e09bbc5dda06
Electron: 22.5.7
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Darwin x64 17.7.0

**Comment by gagermaniac** [comment]
got the same issue on macOS Mojave 10.14.6

**Comment by whereismygithub** [comment]
same the issue with me on macOS Mojave 10.14.6，
This question has been bothering me for a month。
 @Tyriar 
Version:  1.79.1
Commit: 4cb974a7aed77a74c7813bdccd99ee0d04901215
Date: 2023-06-12T16:16:49.215Z
Electron: 22.5.7
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Darwin x64 18.7.0
Sandboxed: Yes

**Comment by meganrogge** [comment]
maybe related to https://github.com/microsoft/vscode/issues/184713 ? @deepak1556

**Comment by deepak1556** [comment]
Yup they are related, merging to https://github.com/microsoft/vscode/issues/184713

**Comment by AceYangWQ** [comment]
This issue is not solved why do you always close related issues

**Comment by olliequ** [comment]
Same issue for a couple weeks now. Really annoying. @Tucsky @ycalm @AceYangWQ did any of you guys find a fix/workaround? Driving me nuts.

MacOS Mojave.

**Comment by AceYangWQ** [comment]
> Same issue for a couple weeks now. Really annoying. @Tucsky @ycalm @AceYangWQ did any of you guys find a fix/workaround? Driving me nuts.
> 
> MacOS Mojave.

I'm using an old version (1.78.0) for now

**Comment by olliequ** [comment]
> > Same issue for a couple weeks now. Really annoying. @Tucsky @ycalm @AceYangWQ did any of you guys find a fix/workaround? Driving me nuts.
> > MacOS Mojave.
> 
> I'm using an old version (1.78.0) for now

Is there an easy way to rollback VSCode versions, or do you have to uninstall and install an old version manually...

**Comment by huaigu** [comment]
It seems like this issue occurred on an older version of MacOS, specifically version 14 and earlier.
Anyone who uses a higher version of MacOS is also experiencing the same issue?

**Comment by flyMDW** [comment]
I rollback to 1.77.3 to resolve this problem

**Comment by huaigu** [comment]
> I rollback to 1.77.3 to resolve this problem

thanks buddy, it works.

**Comment by Tyriar** [comment]
> This issue is not solved why do you always close related issues

Because they're the same thing so they get merged?

---

Looks like https://github.com/microsoft/vscode/issues/184713 will hopefully get fixed in the August release (v1.82). Note that downgrading several version may leave you exposed to security vulnerabilities as we typically release a security release every month or 2.
