### ISSUE TITLE
Terminal tabs description disappear when using a integrated terminal profile with args and a pre-script

### ISSUE THREAD

**Issue by LeonardoRick** [microsoft/vscode#184833]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.79.0
- OS Version: MacOS Ventura 13.2.1

Steps to Reproduce:

1. create a terminal profile and set it as your default profile
```settings.json
  "terminal.integrated.profiles.osx": {
    "zsh": {
      "path": "zsh",
      "args": [
        "-l"
      ]
    },
    "tmux": {
      "path": "tmux",
      "icon": "terminal-tmux"
    },
    "pwsh": {
      "path": "pwsh",
      "icon": "terminal-powershell"
    },
    "ZshWithNvm": {
      "id": "ZshWithNvm",
      "path": "zsh",
      "source": "zsh",
      "args": [
        "-c",
        "[ -f .nvmrc ] && { [ -f ./scripts/loadNvmAndNode.sh ] && ./scripts/loadNvmAndNode.sh || { [ -f /usr/local/bin/loadNvmAndNode.sh ] && loadNvmAndNode.sh || true; }; } || true; exec $SHELL"
      ],
      "extensionIdentifier": "osx",
      "icon": "terminal",
      "title": "Zsh with NVM"
    }
  },
"terminal.integrated.defaultProfile.osx": "ZshWithNvm",
```
2. create a .nvmrc with `18` or any node version inside of it
3. create a /scripts/loadNvmAndNode.sh file in the root of your opened vscode folder and change it's permissions with `chmox +x`
4. This is my script

```loadNvmAndNode.sh
#!/bin/sh
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"

if [ -f .nvmrc ]; then
  NODE_VERSION=$(cat .nvmrc)
  nvm use "$NODE_VERSION" || nvm install "$NODE_VERSION"
else
  nvm use default
fi

exec $SHELL
```

5. check if the command do runs and changes your node version
6. now, in this terminal, try to navigate to other folders and you'll see that the terminal tabs description don't change, showing in what folder you are. In mac, for example, it only shows zsh as title and thats it

PS: I'm referring specifically to: 
`"terminal.integrated.tabs.description": "${task}${separator}${local}${separator}${cwdFolder}"`

**Comment by meganrogge** [comment]
Is this still an issue? It is working for me with my default profile. Not sure why your script would change anything about how ths works.

**Comment by LeonardoRick** [comment]
With the default profile it works normally. The hole profile configuration is attached on the description and I canta see something that could affect that. I haven't tested in a while but I'll do an comment if it still happens
