### ISSUE TITLE
VS Code 1.79: launch-failed with error Code: '18'

### ISSUE THREAD

**Issue by rvveldhuyzen** [microsoft/vscode#184888]
Does this issue occur when all extensions are disabled?: **Yes**

- VS Code Version:  1.79.0
- OS Version: Virtual Machine Win2019 server standard, 1809 OS Build 17763.4377

Steps to Reproduce:
1. I open VS code version 1.79 with shortcut: "C:\Program Files\Microsoft VS Code\Code.exe" --no-sandbox --disable-gpu-sandbox 
2. Following error pops-up and the application stops:
![2023-06-12_10-16-05](https://github.com/microsoft/vscode/assets/25078664/c2f108fe-f540-48be-b3df-4b8c8907324f)
3. This error does not occur when I have VS Code 1.78.2 installed

**Comment by crimsonstrife** [comment]
> Does this issue occur when all extensions are disabled?: **Yes**
> 
> * VS Code Version:  1.79.0
> * OS Version: Virtual Machine Win2019 server standard, 1809 OS Build 17763.4377
> 
> Steps to Reproduce:
> 
> 1. I open VS code version 1.79 with shortcut: "C:\Program Files\Microsoft VS Code\Code.exe" --no-sandbox --disable-gpu-sandbox
> 2. Following error pops-up and the application stops:
>    ![2023-06-12_10-16-05](https://user-images.githubusercontent.com/25078664/245083770-c2f108fe-f540-48be-b3df-4b8c8907324f.jpg)
> 3. This error does not occur when I have VS Code 1.78.2 installed

Having the same issue here - have to run VS Code as admin because of certain needed CLI commands.  If I don't run as admin it will open normally and doesn't need the sandbox flags, but then I can't use it for what I need.

OS Version: Windows 10 Enterprise 22H2 19045.2965

I can also tell you that our IT is utilizing Intune and App Locker.  At the moment keeping the older version installed gets around the problem as mentioned above, but the updates are automatic through Intune so it keeps undoing that.

**Comment by VladimirKhvostov** [comment]
I am seeing the same issue issue, when I try to open VS Code from the admin PowerShell. Things work If I try to open VS Code from the non-elevated command prompt/PowerShell.

**Comment by deepak1556** [comment]
Merging to https://github.com/microsoft/vscode/issues/184687

**Comment by rvveldhuyzen** [comment]
1.79.2 solved the issue @deepak1556, thanks!

**Comment by binarycrusader** [comment]
1.79.2 has *not* solved the issue for me on Win11:

code --version
1.79.2
695af097c7bd098fbf017ce3ac85e09bbc5dda06
x64

Neither has the latest insiders version:

code-insiders --version
1.80.0-insider
61ba389b0a7108af0411c73ab30c7e4350051645
x64

I still cannot launch vscode as an admin/elevated process. Only version 1.78.2 still works as expected.
