### ISSUE TITLE
Request vs code to add the ability to search for save historical XML files

### ISSUE THREAD

**Issue by ednykissyou** [microsoft/vscode#184800]
Type: <b>Feature Request</b>

Request vs code to add the ability to search for save historical XML files

I hope to store the search and replace as an XML file in the future, which can be called at any time.

Yes, you can now use the arrows to search for historical search records. But this is not practical enough. It doesn't have to be said that it's difficult to choose to use, perhaps you won't be able to find it tomorrow.

There is a software that can be used as a reference, and it has done a great job in this area.

That's Adobe InDesign, which can save countless search and replace files for you to select and execute when needed. As long as you back up these files, they will never disappear, it's great.

Can't send pictures, you can take a look here

Thank you.
http://www.fileconvoy.com/dfl.php?id=gfc68bda4c3f79bba1000497920277aa4fa67a51933

VS Code version: Code 1.79.0 (b380da4ef1ee00e224a15c1d4d9793e27c2b6302, 2023-06-07T14:26:35.552Z)
OS version: Windows_NT x64 10.0.22000
Modes:

**Comment by andreamah** [comment]
You can use the Search Editor and save the search to re-run it at a later time. 
<img width="375" alt="image" src="https://github.com/microsoft/vscode/assets/31675041/b0931fb9-67de-4383-9862-f42dc71574e9">
