### ISSUE TITLE
API for extensions to know the scope as per grammar of the cursor position

### ISSUE THREAD

**Issue by ramya-rao-a** [Microsoft/vscode#18485]
It would be helpful for extension authors to know if the cursor is inside a string or a comment or any of the other scopes as defined by the grammar.

When an extension is not using LSP, this can help the extension in being smarter say in case of completion item provider.
Currently to do so, the extension needs to parse the file itself.
But, the scope (as per grammar) is already available to core VS Code.

If that can be exposed, I can fix a bunch of issues in the Go extension :)

**Comment by rebornix** [comment]
Extensions provide a language grammar for Code to generate the tokens and then ask Code for the token info, very reasonable.

**Comment by ramya-rao-a** [comment]
@rebornix VS Code already has the grammar for most of the languages.

**Comment by siegebell** [comment]
See #580.

Until the feature is supported by vscode, my extension ([scope-info](https://marketplace.visualstudio.com/items?itemName=siegebell.scope-info)) exports an API that other extensions can use to get the scope information that vscode uses.

**Comment by ramya-rao-a** [comment]
Closing as duplicate of #580

**Comment by ramya-rao-a** [comment]
Thanks for the pointer @siegebell !
