### ISSUE TITLE
Error opening Welcome after reloading

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#184895]
1. Make sure the File Explorer is visible
2. Create temporary profile
3. Reload window

🐛 Welcome editor fails to open.

https://github.com/microsoft/vscode/assets/22350/0d863c27-6db2-4e11-b05b-71cb17ab8474

cc @sandy081

**Comment by bhavyaus** [comment]
Is probably due to: https://github.com/microsoft/vscode/pull/184770.

**Comment by luabud** [comment]
@cwebster-99 and I also reproduced this when testing out her walkthrough changes: https://github.com/microsoft/vscode-python/pull/21411
