### ISSUE TITLE
Undo functionality not working properly.

### ISSUE THREAD

**Issue by agrawalrajat310** [microsoft/vscode#184804]
Type: <b>Bug</b>

- VS Code Version: 1.79.0 (user setup)
- OS Version: Windows_NT x64 10.0.22621

I am currently facing the not working of undo functionality only in my VS Code from past few weeks. Can you please check and guide me how to get rid of this issue ?

VS Code version: Code 1.79.0 (b380da4ef1ee00e224a15c1d4d9793e27c2b6302, 2023-06-07T14:26:35.552Z)
OS version: Windows_NT x64 10.0.22621
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz (8 x 2419)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.79GB (2.95GB free)|
|Process Argv|--crash-reporter-id a5944ee6-b8a9-42c1-9c86-93832a5136f1|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (27)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|3.0.2
codesnap|adp|1.3.4
project-manager|ale|12.7.0
aws-toolkit-vscode|ama|1.76.0
blackbox|Bla|1.0.8
simple-react-snippets|bur|1.2.7
multi-cursor-case-preserve|Car|1.0.5
dscodegpt|Dan|2.1.10
vscode-eslint|dba|2.4.0
docs-images|doc|1.0.0
es7-react-js-snippets|dsz|4.4.3
gitlens|eam|13.6.0
vsc-material-theme|Equ|33.8.0
vsc-material-theme-icons|equ|2.8.0
prettier-vscode|esb|9.13.0
auto-rename-tag|for|0.1.10
vscode-colorize|kam|0.11.1
document|min|2.2.1
vscode-edge-devtools|ms-|2.1.2
live-server|ms-|0.4.8
css-grid-snippets|oha|0.0.5
material-icon-theme|PKi|4.28.0
LiveServer|rit|5.7.9
vscode-styled-components|sty|1.7.8
tabnine-vscode|Tab|3.6.53
in-your-face-incredible|TTO|1.1.0
errorlens|use|3.11.1

(3 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscoreces:30445986
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
3biah626:30602489
pyind779:30671433
89544117:30613380
pythonsymbol12:30671437
2i9eh265:30646982
showlangstatbar:30737416
vsctsb:30748421
pythonms35:30701012
03d35959:30757346
57b77579:30736110
pythonfmttext:30731395
pythoncmvfstrcf:30756944
fixshowwlkth:30730052
hidesbindicator:30760978
pythongtdpathcf:30739705
bgfeh915:30763804
dh2dc718:30763024

```

</details>

**Comment by gjsjohnmurray** [comment]
Please use the Start Extension Bisect command to investigate whether the problem is being caused by one of your extensions.

**Comment by agrawalrajat310** [comment]
I did all the things but nothing is helping me until I go to the "Edit" section at the top every time when I want to use the "Undo" functionality 🥲🥲.

**Comment by agrawalrajat310** [comment]
Any update on my query ? @gjsjohnmurray

**Comment by gjsjohnmurray** [comment]
Please clarify. Is it that Undo chosen from the Edit menu works but Ctrl+Z doesn't? If yes, please check for any custom keyboard shortcuts.

**Comment by agrawalrajat310** [comment]
@gjsjohnmurray  Yes, **Undo** chosen from the **Edit** menu works but Ctrl+Z doesn't. I checked for all the shortcuts but can't find anything unusual.

Looking for more help from your side 1:1 until I uninstall the vs code on my laptop. 

Thank you

**Comment by gjsjohnmurray** [comment]
Advice at https://github.com/microsoft/vscode/wiki/Keybinding-Issues can help you discover where the Ctrl+Z is going.
