### ISSUE TITLE
Tab conflict custom code snippet placement with code suggestions

### ISSUE THREAD

**Issue by Arifursdev** [microsoft/vscode#184849]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: May 2023 (version 1.79)
- OS Version: 

Steps to Reproduce:

the snippet for example for css:
```css
"@media": {
		"prefix": "media",
		"body": [
			"@media (${1:max}-width:${2}) {",
			" ${3} ",
			"}"
		],
		"description": "@media",
		"scope": "css,html,scss"
}
```

so in the same css/scss file with lot of other codes, when typing "media" and press tab, it will include with cursor selecting 'min' and tab to go after the colon.
```css
@media (min-width:) {
              
}
```

but suddenly in new version maybe, requesting "media"  snippet and tab > code is included
```css
@media (min-width:) {
              
}
```
 with the cursor over 'min'. But it shows little popup with suggestions like "min-height, min-width..." when i just want to have "min".
and while popup is there and you want to go after colon by pressing tab, it includes "min-height" instead of going to colon.
```css
@media (min-height-width:) {
              
}
```

**Comment by mohamedhashemx** [comment]
I have the same issue but in JavaScript like this
`console.log(' ` 
don't complete the whole line

**Comment by jrieken** [comment]
This can be controlled via `editor.suggest.snippetsPreventQuickSuggestions`, we changed its default for the [1.79](editor.suggest.snippetsPreventQuickSuggestions)-release
