### ISSUE TITLE
New PasteAs does not allow to choose default way to paste

### ISSUE THREAD

**Issue by ollikoponenbel** [microsoft/vscode#184871]
Type: <b>Bug</b>

Hi

The idea of of the 1.79 new "PasteAs" is great, but it totally broke my workflow. I have used copy-paste rows without any selection. This has previously pasted the current row below the cursor row.

With "PasteAs" enabled, this behaviour has changed (to worse)
- if I am at the end of the line, paste will add the current row on the same row, with preceding white spaces.
- if I am in the middle of the line, the line is paster (again, with preceding white spaces) to current position

Currently my fix is to disable the feature
    "editor.pasteAs.showPasteSelector": "never",
    "editor.pasteAs.enabled": false,

VS Code version: Code 1.79.0 (b380da4ef1ee00e224a15c1d4d9793e27c2b6302, 2023-06-07T14:28:44.251Z)
OS version: Linux x64 6.2.0-20-generic
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz (8 x 2341)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|2, 2, 2|
|Memory (System)|15.32GB (4.76GB free)|
|Process Argv|--unity-launch --crash-reporter-id 058641ec-6c83-4f22-873d-961543d63c45|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|wayland|
</details><details><summary>Extensions (29)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|3.0.2
vscode-sql-formatter|adp|1.4.4
Bookmarks|ale|13.3.1
aurelia|Aur|2.1.4
vscode-django|bat|1.10.0
django-html|bib|1.3.0
path-intellisense|chr|2.8.4
vscode-eslint|dba|2.4.0
githistory|don|0.6.20
EditorConfig|Edi|0.16.4
vscode-ember-unstable|lif|3.0.51
isort|ms-|2022.8.0
python|ms-|2023.10.0
vscode-pylance|ms-|2023.6.10
tsimporter|pmn|2.0.1
java|red|1.19.0
vscode-xml|red|0.25.0
scala|sca|0.5.6
django-intellisense|sha|0.0.2
sonarlint-vscode|Son|3.18.0
autoimport|ste|1.5.4
svelte-vscode|sve|107.5.1
vscodeintellicode|Vis|1.2.30
vscode-java-debug|vsc|0.51.0
vscode-java-dependency|vsc|0.23.0
vscode-java-pack|vsc|0.25.11
vscode-maven|vsc|0.41.0
volar|Vue|1.6.4
vscode-typescript-vue-plugin|Vue|1.6.5

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes516:30244333
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vscaac:30438847
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyonecf:30548226
2e4cg342:30602488
pyind779:30671433
89544117:30613380
pythonsymbol12:30671437
a9j8j154:30646983
showlangstatbar:30737416
vsctsb:30748421
pythonms35:30701012
03d35959:30757346
57b77579:30736110
pythonfmttext:30731395
pythoncmvfstrcf:30756944
fixshowwlkth:30730052
hidesbindicator:30760978
pythongtdpath:30739704
dh2dc718:30763024
pythonnosm12tcf:30757130

```

</details>

**Comment by mjbvz** [comment]
Will be tested in #235016
