### ISSUE TITLE
Cannot click and drag scroll bar in terminal

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#184894]
On the latest insiders I can't click and drag the terminal scroll bar:

![Recording 2023-06-12 at 12 02 10](https://github.com/microsoft/vscode/assets/38270282/7f12d4c9-c21d-4a0b-818d-ee8409c44a22)

**Comment by talkingnews** [comment]
Same here - but at least the terminal can actually be resized now!

```Version: 1.80.0-insider (user setup)
Commit: ef6abe4cd1573689d070b8715e97019cfadaeb51
Date: 2023-06-12T05:21:26.842Z
Electron: 22.5.5
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Windows_NT x64 10.0.19045```

**Comment by hidekuro** [comment]
I faced the same problem.
In my case, all scrollbars (editor, explorer, ...) were.
I tried `code --disable-extensions` and it was the same.

```
❯ sw_vers
ProductName:		macOS
ProductVersion:		13.4
BuildVersion:		22F66

❯ code --version
1.79.2
695af097c7bd098fbf017ce3ac85e09bbc5dda06
arm64
```

**Comment by Ashesh3** [comment]
Same issue here, cannot scroll the terminal window.
The cursor changes to text selector and is unable to scroll for the entire life of the terminal window.

![image](https://github.com/microsoft/vscode/assets/3626859/8dea2b71-162f-4d47-80fe-c01f4846de5e)

**Comment by hidekuro** [comment]
> https://github.com/microsoft/vscode/issues/184894#issuecomment-1600237723

I completely shut down macOS and restarted it and it fixed it. It's strange.

**Comment by Ashesh3** [comment]
> > [#184894 (comment)](https://github.com/microsoft/vscode/issues/184894#issuecomment-1600237723)
> 
> I completely shut down macOS and restarted it and it fixed it. It's strange.

Restarting vscode fixes it for me. It only happens when my cursor either hovers over a link in the terminal or I select some text from the terminal, it gets forever stuck in text selection/link click mode.

**Comment by Tyriar** [comment]
This is because of the image addon:

![image](https://github.com/microsoft/vscode/assets/2193314/9c9864f8-5fb6-47aa-b902-a80c33eac368)

cc @jerch

**Comment by diminutivesloop** [comment]
I'm seeing this in Insiders. Restarting VSCode doesn't fix it and it only happens when I have multiple terminals open and the terminal tab sidebar is showing.

Version: 1.81.0-insider (Universal)
Commit: ad791ef3d26b99963da31636af697afd86575435
Date: 2023-07-07T19:50:58.701Z
Electron: 22.3.14
ElectronBuildId: 21893604
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Darwin x64 22.5.0

**Comment by Tyriar** [comment]
@jerch it came in a bit late for the release and didn't think it met the bar. I'll be updating soon
