### ISSUE TITLE
loading issue

### ISSUE THREAD

**Issue by fleckjr** [microsoft/vscode#184808]
Codespace is taking long to load when I deleted a file

Version: 1.79.0
Commit: b380da4ef1ee00e224a15c1d4d9793e27c2b6302
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36
Embedder: codespaces

**Comment by chrmarti** [comment]
Thanks for your feedback. Since it concerns GitHub Codespaces, could you please start a discussion about it here: https://github.com/community/community/discussions/categories/codespaces
