### ISSUE TITLE
UNC allow list checks cannot be disabled in extension host

### ISSUE THREAD

**Issue by mmramseier** [microsoft/vscode#184989]
Type: <b>Bug</b>

When searching (Ctrl+Shift+F) the following message is shown right below the search field:

"UNC host [host-address] access is not allowed. Please update the 'security.allowedUNCHosts' setting if you want to allow this host."

However, the host ist added to "security.allowedUNCHosts" and "security.restrictUNCAccess" is set to false.

The individual files of the host can be viewed, editted and searched but the 'search all files' gives the above message.

This problem does not occur in V1.78.2

Version: 1.79.0 (user setup)
Commit: b380da4ef1ee00e224a15c1d4d9793e27c2b6302
Date: 2023-06-07T14:26:35.552Z
Electron: 22.5.5
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Windows_NT x64 10.0.17763

VS Code version: Code 1.79.0 (b380da4ef1ee00e224a15c1d4d9793e27c2b6302, 2023-06-07T14:26:35.552Z)
OS version: Windows_NT x64 10.0.17763
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) W-2145 CPU @ 3.70GHz (16 x 3696)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.59GB (22.58GB free)|
|Process Argv|-n --crash-reporter-id d76eadfc-6b4c-4690-b191-6d7c880f540e|
|Screen Reader|no|
|VM|80%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes516:30244333
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
3biah626:30602489
pyind779:30671433
89544117:30613380
pythonsymbol12:30671437
showlangstatbar:30737416
vsctsb:30748421
pythonms35:30701012
03d35959:30757346
pythonfmttext:30731395
pythoncmv:30756943
fixshowwlkth:30730052
hidesbindicator:30760978
pythongtdpath:30739704
i26e3531:30763805
dh2dc718:30763024
pythonnosm12tcf:30765602

```

</details>

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by mmramseier** [comment]
Thank you for the prompt response!

After testing the VSCodeUserSetup-x64-1.80.0-insider release, I discovered that despite setting "security.restrictUNCAccess" to false, the functionality still doesn't work. However, when I set "security.restrictUNCAccess" to true and include the host's address in the "security.allowedUNCHosts" setting, the search feature begins working.

This resolves the issue for me since I prefer to restrict UNC access anyway. Nevertheless, it would be nice if setting "security.restrictUNCAccess" to false behaved as expected.

**Comment by bpasero** [comment]
This is actually a bug on our end 😱

**Comment by bpasero** [comment]
**Verification:**
* uncheck `security.restrictUNCAccess`
* restart
* from a simple hello world extension (e.g. via `yo code`) trigger the following from a command:
  * `vscode.window.showInformationMessage('Hello World from test-ts!: ' + fs.statSync("\\\\localhost\\c$"));`
* verify you do not get an error and that the notification message appears

**Comment by sandy081** [comment]
Verified in insiders and stable and I see following output

<img width="491" alt="image" src="https://github.com/microsoft/vscode/assets/10746682/25602fd0-a40f-4376-a4eb-c8e062ecfa0e">
