### ISSUE TITLE
[themes] More colorful default theme - Feedback

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode#1849]
The light and dark themes have recently been in the center of attention due to colors being added and removed again.

More colors became visible due to the update of tokenizers in November. In December we decided to remove these again, to stay in sync with the classic Visual Studio Dark and Light themes.

From reactions in #1270 and #1470 and other issues, we learned that we have fans of both the classic Visual Studio dark and light themes as well as the more colorful version, e.g., from [comment]
(https://github.com/Microsoft/vscode/issues/1470#issuecomment-166152680)
>The `Dark` and `Light` default themes were very nice in 0.10.3, I'm already missing them.

So we decided to bring the colors back in new themes, 'Dark+' and 'Light+'.
![image](https://cloud.githubusercontent.com/assets/6461412/12168352/e64004c0-b531-11e5-8e6b-2b90c16e4939.png)

You can currently try these out by installing the extension 'Colorful Default Themes'. The plan is to add them to the built-in themes in the January build.

In addition to 4 major colors in the Visual Studio themes (comments, strings, numbers and keywords) we now have again colors for
- control flow keywords
- type names
- function names
- parameter names

![image](https://cloud.githubusercontent.com/assets/6461412/12168372/fe1ae9c0-b531-11e5-8578-0de2ba719fab.png)

When trying the new themes out, you will still find some keywords like 'import', 'module' nor correctly highlighted. These are issues in the tokenizer that we are working on. Please post your findings here, if possible add a code snippet and don't forget to mention for what language it is :-)

**Comment by bpasero** [comment]
I love the new light theme plus! <3

**Comment by bpasero** [comment]
The dark theme seems to color functions different compared to light plus. I am not sure though colouring functions adds much value.

![image](https://cloud.githubusercontent.com/assets/900690/12173820/54e198ea-b559-11e5-8170-6aa15bb33757.png)

![image](https://cloud.githubusercontent.com/assets/900690/12173824/58e1d3ec-b559-11e5-8941-89a7f0ad52cd.png)

**Comment by ricmed205** [comment]
for me the old and the new themes look exactly the same (javascript)

**Comment by borgdylan** [comment]
Thanks for making these themes available again. Colour can be used as visual metadata while navigating through code, so the more colourful the better.

**Comment by Tyriar** [comment]
C++ includes aren't colored correctly in Dark+ or Light+, both color the whole line as purple:

Dark:

![dark](https://cloud.githubusercontent.com/assets/2193314/12188762/13f691e6-b56d-11e5-88ef-1610be5fb1db.png)

Dark+:

![dark_plus](https://cloud.githubusercontent.com/assets/2193314/12188765/18c5450a-b56d-11e5-9c57-c4175697649f.png)

**Comment by Tyriar** [comment]
@bpasero coloring functions in C++ feels pretty essential:

Dark:

![dark_func](https://cloud.githubusercontent.com/assets/2193314/12188845/d48d7cda-b56d-11e5-952b-aa3ed70d148b.png)

Dark+:

![dark_plus_func](https://cloud.githubusercontent.com/assets/2193314/12188847/d7bbdc12-b56d-11e5-83df-c4a48cb42e34.png)

On this, it would be nice if the coloring was somewhat consistent across languages (functions are colored the same in all languages).

**Comment by aeschli** [comment]
I'm still working on better c# coloring. Unfortunately the tokenizer we use for c# behaves differently.

**Comment by aeschli** [comment]
I delivered a fix for csharp. Please update the extension.

**Comment by Tyriar** [comment]
[Dark+] Not sure if this is intentional but Java strings are colored inconsistently based on whether they're assigned to variables or not:

![java_strings_1](https://cloud.githubusercontent.com/assets/2193314/12201665/7cad0144-b5da-11e5-8875-41aa77d2d6e5.png)

Styled with:

```css
.monaco-editor.vs-dark .token.string.quoted.variable {
    color: #74B0DF;
}
```

![java_strings_2](https://cloud.githubusercontent.com/assets/2193314/12201668/7ede464e-b5da-11e5-817d-ba052070c872.png)

Styled with:

```css
.monaco-editor.vs-dark .token.string, .monaco-editor.vs-dark .token.string.tag, .monaco-editor.vs-dark .token.string.value {
    color: #CE9178;
}
```

**Comment by ddotlic** [comment]
The Dark+ is better but there are issues, likely with the new tokenizer (all in TypeScript):

-  Types of return values are not colorized for non-builtin types (so all my types are not colorized)

![coloring1](https://cloud.githubusercontent.com/assets/1737586/12230296/b6caece8-b84f-11e5-9482-5ccf8dda9fb9.png)

- Sometimes, if the return type is generic, part of it is colorized the same as function name

![coloring2](https://cloud.githubusercontent.com/assets/1737586/12230315/e36e2ce2-b84f-11e5-9d7b-2c323e8e6477.png)

- Keyword public is colorized like type when used in constructor

![coloring4](https://cloud.githubusercontent.com/assets/1737586/12230359/57a73e82-b850-11e5-8ca0-5aedcfbd321e.png)

- All words in a lambda are colorized like types

![coloring3](https://cloud.githubusercontent.com/assets/1737586/12230349/31459c7a-b850-11e5-8d10-8a3383ade7e1.png)

- I don't recall if methods - when called - were also colorized before? (declarations are now colorized fine)

All in all, a step in a right direction :smile: I sincerely hope you had a good reason to change the tokenizer because coloring was really great before...

**Comment by nomenon** [comment]
![c vscode](https://cloud.githubusercontent.com/assets/16668962/12267661/df07f3a6-b951-11e5-9a03-1620028d3b10.png)
please fix this (C#)

**Comment by aeschli** [comment]
@nomenon First issue is https://github.com/atom/language-csharp/issues/47
Second is likely https://github.com/atom/language-csharp/issues/46

**Comment by nomenon** [comment]
@aeschli not exactly the same
![codec bug](https://cloud.githubusercontent.com/assets/16668962/12322714/809fc56e-babe-11e5-8f1f-63e9c4d66740.png)

**Comment by bpasero** [comment]
@aeschli not sure I like the color of functions in light theme:

![image](https://cloud.githubusercontent.com/assets/900690/12333503/d0aecad8-baf4-11e5-9a1f-6ffa853ecac9.png)

A function name should stand out from other things like the visibility. Using a grey here puts the name to the background and it is harder to catch with the other colours we now use.

**Comment by aeschli** [comment]
@bpasero There's a better color on the way. Please comment in #1943 for the tuning of colors.

**Comment by adnan333bd** [comment]
Could 'module' have same color as 'class' or 'interface' ? I would love that ....

![image](https://cloud.githubusercontent.com/assets/15263521/12352087/2095ede8-bbad-11e5-94ea-78fa8681e062.png)

**Comment by felixfbecker** [comment]
Keywords like function, let, const, var are colored wrong (like interfaces/classes) in latest update in JS files. TS files are not affected. This is so ugly I wish it was possible to revert extension versions xD

![image](https://cloud.githubusercontent.com/assets/10532611/12435392/9015b000-bf0d-11e5-8836-d7b2d786b5e1.png)

**Comment by dwbruhn** [comment]
This is definitely an improvement! In JS, however, when declaring multiple var's, only the first one is colorized (`testSource` in the example below):

![image](https://cloud.githubusercontent.com/assets/8230981/12436299/dbe33a88-bec8-11e5-833a-6f34dfbe45be.png)

**Comment by aeschli** [comment]
@felixfbecker, @dwbruhn I made a fix for this, please update to the latest version of the extension.

**Comment by felixfbecker** [comment]
@aeschli fixed, thanks!

**Comment by dwbruhn** [comment]
Hi @aeschli, I'm running version 0.1.10 of the extension, but I'm seeing the same issue: `testSource` and `reportsDirectory` are both variables but different colors. It's just a little weird to see only the first one colored:

![image](https://cloud.githubusercontent.com/assets/8230981/12454661/5320886a-bf4d-11e5-8070-00c9524259fa.png)

Webstorm, for example, leaves them uncolored, but they're *both* uncolored at least:

![image](https://cloud.githubusercontent.com/assets/8230981/12454777/cc7873d0-bf4d-11e5-87fa-f44d8085efda.png)

**Comment by aeschli** [comment]
@dwbruhn That's https://github.com/Microsoft/TypeScript-TmLanguage/issues/41

**Comment by aeschli** [comment]
Closing as fixed. The new themes will be part of VSCode in the January build. It is no longer needed to install the themes extensions from the marketplace. In fact, everybody who has installed them can uninstall the extensions to avoid duplicated entries in the theme selection dialog.
