### ISSUE TITLE
Cannot load global eslint.config.js

### ISSUE THREAD

**Issue by thdoan** [microsoft/vscode#184979]
Type: <b>Bug</b>

VS Code is not able to load a global `eslint.config.js`, or maybe I'm doing it the wrong way. My settings:

```
    "eslint.experimental.useFlatConfig": true,
    "eslint.options": {
        "overrideConfigFile": "/path/to/eslint.config.js"
    },
```

eslint.config.js

```
export default [
  "eslint:recommended",
  {
    "rules": {
      "quotes": ["error", "single"]
    }
  }
];
```

Error in ESLint log:

```
[Info  - 8:45:48 PM] ESLint library loaded from: C:\dev\nvm\v16.20.0\node_modules\eslint\lib\unsupported-api.js
(node:9076) Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.
(Use `Code --trace-warnings ...` to show where the warning was created)
Uncaught exception received.
C:\path\to\eslint.config.js:1
export default [
^^^^^^

SyntaxError: Unexpected token 'export'
    at Object.compileFunction (node:vm:360:18)
    at wrapSafe (node:internal/modules/cjs/loader:1109:15)
    at Module._compile (node:internal/modules/cjs/loader:1144:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1243:10)
    at Module.load (node:internal/modules/cjs/loader:1058:32)
    at Module._load (node:internal/modules/cjs/loader:893:12)
    at f._load (node:electron/js2c/asar_bundle:2:13330)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:170:29)
    at ModuleJob.run (node:internal/modules/esm/module_job:193:25)
    at async Promise.all (index 0)
```

VS Code version: Code 1.79.0 (b380da4ef1ee00e224a15c1d4d9793e27c2b6302, 2023-06-07T14:26:35.552Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2808)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.95GB (15.45GB free)|
|Process Argv|--crash-reporter-id e86a0267-29ec-4153-bda4-a329db5a1c66 --crash-reporter-id e86a0267-29ec-4153-bda4-a329db5a1c66 --crash-reporter-id e86a0267-29ec-4153-bda4-a329db5a1c66|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
file-properties-viewer|bru|1.0.0
path-intellisense|chr|2.8.4
hex-to-rgba|dak|1.0.0
vscode-eslint|dba|2.4.0
gitlens|eam|13.6.0
vscode-ts-whitespace-converter|joh|1.2.1
l13-diff|L13|1.3.2
vscode-json-validate|rio|1.4.3
sort-lines|Tyr|1.10.1
remove-empty-lines|use|1.0.1

</details>

**Comment by mjbvz** [comment]
Please file this against the eslint extension
