### ISSUE TITLE
DSC Resource for configuring Visual Studio Code

### ISSUE THREAD

**Issue by denelon** [microsoft/vscode#184925]
I'd like a DSC Resource so I can run a [WinGet configuration](https://learn.microsoft.com/windows/package-manager/configuration/) and have Visual Studio Code configured for my project.

For reference, there is a [Visual Studio module](https://www.powershellgallery.com/packages/Microsoft.VisualStudio.DSC) on the PowerShell gallery with DSC resources.

**Comment by lszomoru** [comment]
This work has been completed https://github.com/microsoft/vscode/blob/main/.configurations/configuration.dsc.yaml
