### ISSUE TITLE
Debug failed to load: Process picker failed (your 131072x1 screen size is bogus, expect trouble) , with chinese locale

### ISSUE THREAD

**Issue by hylas-deng** [microsoft/vscode#184972]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.79.0
- OS Version: windows 11 x64 22621.1778

1. Same issue with #75932
2. The difference is that my terminal language is zh_CN.UTF-8.

**Comment by roblourens** [comment]
So you are also trying to start the debugger? Or just using the terminal to do something else?

**Comment by hylas-deng** [comment]
> So you are also trying to start the debugger? Or just using the terminal to do something else?

Yep, I was trying to start debugger with "attach by process ID". After reconfiguring the default locale of WSL2 with en_US.UTF-8, it's fine.

**Comment by roblourens** [comment]
The node debugger? Or some other language?

**Comment by hylas-deng** [comment]
> 

C++ debuger.

**Comment by roblourens** [comment]
Please file an issue on that extension's repo, thanks
