### ISSUE TITLE
problem on the hover bg color of Source Control item in status bar

### ISSUE THREAD

**Issue by huacat1017** [microsoft/vscode#184996]
Type: <b>Bug</b>

1. Open VSCode.
2. Switch Color Theme to another one
3. the hover bg color of Source Control item still uses the previous theme's setting
After I press <kbd>Ctrl</kbd>+<kbd>K</kbd> <kbd>Ctrl</kbd>+<kbd>T</kbd> or Reload Window, VSCode use the correct color.

https://github.com/microsoft/vscode/assets/57604590/011ea6e5-1f3f-485a-8405-a74938f505be

VS Code version: Code 1.79.0 (b380da4ef1ee00e224a15c1d4d9793e27c2b6302, 2023-06-07T14:26:35.552Z)
OS version: Windows_NT x64 10.0.22621
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|7.88GB (2.81GB free)|
|Process Argv|--crash-reporter-id 1984ce79-8f1f-47b0-88ab-e865d36f3187|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (31)</summary>

Extension|Author (truncated)|Version
---|---|---
language-x86-64-assembly|13x|3.0.0
easy-cpp-projects|ACh|2.0.0
fenix|ACh|1.1.5
project-manager|ale|12.7.0
markdown-shiki|bie|0.1.1
doxdocgen|csc|1.4.0
jquerysnippets|don|0.0.1
vsc-material-theme|Equ|33.8.0
vsc-material-theme-icons|equ|2.8.0
better-cpp-syntax|jef|1.17.2
git-graph|mhu|1.30.0
vscode-language-pack-zh-hant|MS-|1.79.2023060709
python|ms-|2023.10.0
vscode-pylance|ms-|2023.6.10
remote-containers|ms-|0.296.0
remote-wsl|ms-|0.79.4
cmake-tools|ms-|1.14.33
cpptools|ms-|1.15.4
cpptools-extension-pack|ms-|1.3.0
remote-explorer|ms-|0.4.0
material-icon-theme|PKi|4.28.0
java|red|1.19.0
swdc-vscode|sof|2.7.0
ayu|tea|1.0.5
open-in-browser|tec|2.0.0
pdf|tom|1.2.2
cmake|twx|0.0.17
windows-terminal|Tyr|0.7.0
vscode-java-debug|vsc|0.51.0
vscode-java-dependency|vsc|0.23.0
material-theme|zhu|3.15.17

(7 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscorecescf:30445987
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyonecf:30548226
vsccc:30610678
2e4cg342:30602488
pyind779:30671433
89544117:30613380
pythonsymbol12:30671437
showlangstatbar:30737416
vsctsb:30748421
pythonms35:30701012
a2ce3375:30757347
24365598:30736109
pythonfmttext:30731395
pythoncmvfstrcf:30756944
fixhidewlkth:30730051
showsbindicator:30760979
pythongtdpath:30739704
dh2dc718:30763024
pythonnosm12tcf:30765602

```

</details>

**Comment by Aburupa1389** [comment]
أرسل gasem alotef إليك رسالة إلكترونية في وضع الحفاظ على السرّية في Gmail:

[image: شعار Gmail]Re: [microsoft/vscode] problem on the hover bg color of Source Control item in status bar (Issue #184996) <https://confidential-mail.google.com/msg/ANo0PrUAnq0I_qFMzRQctpBke9btkQe2HifU-t8RUOOr7NWESb92RWr1xthOaSdvLbwA-B2mnETIQjKSabL-p5B1qGbmXtYzIXVNlG5pcIpWH943uSShivwHRulygpUIJRFk985O7BRCBBrIl5kzGLvMGyL1J5MK0JoImj70AqX71gKH9ZBhMf8tkMfmqPIIVbJLXT4Ad-8os3jym5Pv>

تم إرسال هذه الرسالة يوم 13‏/06‏/2023 الساعة 1:31:28 ص غرينتش-7
يمكنك فتحه بالنقر على الرابط أدناه. ولا يعمل هذا الرابط إلا مع ***@***.***

عرض الرسالة الإلكترونية <https://confidential-mail.google.com/msg/ANo0PrUAnq0I_qFMzRQctpBke9btkQe2HifU-t8RUOOr7NWESb92RWr1xthOaSdvLbwA-B2mnETIQjKSabL-p5B1qGbmXtYzIXVNlG5pcIpWH943uSShivwHRulygpUIJRFk985O7BRCBBrIl5kzGLvMGyL1J5MK0JoImj70AqX71gKH9ZBhMf8tkMfmqPIIVbJLXT4Ad-8os3jym5Pv>

يمنحك "الوضع السري في Gmail" مزيدًا من التحكُّم في الرسائل التي تُرسِلها. ربما اختار المُرسِل تحديد وقت انتهاء الصلاحية أو إيقاف الطباعة أو إعادة توجيه رسالة أو تتبّع الوصول إلى هذه الرسالة. مزيد من المعلومات <https://support.google.com/mail/answer/7674059>
Gmail: خدمة بريد إلكتروني مُقدَّمة من Google
يخضع الاستخدام لـ سياسة خصوصية Google <https://myaccount.google.com/privacypolicy?hl=ar>
Google LLC, 1600 Amphitheatre Parkway, Mountain View, CA 94043, USA
لقد استلمت هذه الرسالة لأن أحدهم أرسل إليك رسالة إلكترونية في وضع الحفاظ على السرّية في Gmail.
[image: شعار Google]

**Comment by connor4312** [comment]
I no longer reproduce this
