### ISSUE TITLE
No file icon in titlebar if titleBarStyle != "native"

### ISSUE THREAD

**Issue by terriblegoodday** [Microsoft/vscode#18499]
- VSCode Version: 1.8.1
- OS Version: macOS 10.12.2

No file icon in title if **window.titleBarStyle != "native"**, therefore you can't drag-and-drop file you're working on.
![screen shot 2017-01-13 at 18 58 42](https://cloud.githubusercontent.com/assets/8566524/21922387/6ab22200-d9c2-11e6-8d8d-8d92ab9994d0.png)
![screen shot 2017-01-13 at 18 58 20](https://cloud.githubusercontent.com/assets/8566524/21922388/6b2f2606-d9c2-11e6-8a6f-151eaa42e87b.png)

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/17664
