### ISSUE TITLE
Cannot read property 'length' of null when replace all

### ISSUE THREAD

**Issue by leaxoy** [Microsoft/vscode#18497]
- VSCode Version: Code - Insiders 1.9.0-insider (ed5a9f269d2d1c9e866bc1f29dbd6a25abc02701, 2017-01-12T07:05:52.808Z)
- OS Version: Darwin x64 16.4.0
- Extensions:

|Extension|Author|Version|
|---|---|---|
|vscode-docker|PeterJausovec|0.0.11|
|vscode-custom-theme|bentx|1.1.1|
|Gradle|cazzar09|1.0.1|
|npm-intellisense|christian-kohler|1.2.1|
|path-intellisense|christian-kohler|1.2.0|
|vscode-eslint|dbaeumer|1.2.2|
|githistory|donjayamanne|0.1.4|
|python|donjayamanne|0.5.5|
|tslint|eg2|0.8.1|
|file-icons|file-icons|0.0.4|
|theme-material-theme|jprestidge|1.0.1|
|Go|lukehoban|0.6.52|
|vscode-clang|mitaki28|0.2.1|
|cpptools|ms-vscode|0.9.3|
|debugger-for-chrome|msjsdiag|2.4.2|
|theme-pixeler|pixeler|0.6.0|
|java|redhat|0.0.8|
|vscode-nginx|shanoor|0.3.0|
|pdf|tomoki1207|0.1.0|
|vscode-apielements|vncz|0.6.0|
|gitblame|waderyan|1.3.0|
|vscode-proto3|zxh404|0.0.7|

---

Steps to Reproduce:

1. give a ansi file, each is a double quote sentence.
2. use `cmd + f` find all and then leave replacement empty, use `cmd + option + enter` will produce this

**Comment by mjbvz** [comment]
Crash is on this line when accessing `this._pieces`: https://github.com/Microsoft/vscode/blob/master/src/vs/editor/contrib/find/common/replacePattern.ts#L47

@alexandrudima Can you please take a look

**Comment by alexandrudima** [comment]
Fixed via 8289f6fa059d580ec063386ccebb4bde2354bb89
