### ISSUE TITLE
Link opening attempted repeatedly 

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#184951]
1. open an editor
2. `alt+f1`
3. press `h`
4. 🐛 see several popups abt opening a link

**Comment by Tyriar** [comment]
This isn't working for me. Note I had 4 windows open and 5 links opened.

![Recording 2023-06-28 at 09 09 20](https://github.com/microsoft/vscode/assets/2193314/e789f459-c993-4d71-8927-67cdc602f86c)

**Comment by Tyriar** [comment]
I'm also curious why it's no longer ctrl+h? Hotkeys without modifiers feel weird to me

**Comment by Tyriar** [comment]
@meganrogge do you mean when you have a terminal focused? I think that should work in general, gave a pointer to the issue this was discussed?

**Comment by meganrogge** [comment]
https://github.com/microsoft/vscode/issues/186434

**Comment by Tyriar** [comment]
@meganrogge that's saying that the quick open default keybinding is taking priority, not related to the OS/desktop manager:

```
{ "key": "ctrl+e",                "command": "workbench.action.quickOpen" },
```

**Comment by Tyriar** [comment]
You could probably bump the keybinding priority to fix that
