### ISSUE TITLE
All walkthroughs don't show immediately from "Welcome: Open Walkthrough"

### ISSUE THREAD

**Issue by bamurtaugh** [microsoft/vscode#184960]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 
Version: 1.80.0-insider (user setup)
Commit: ef6abe4cd1573689d070b8715e97019cfadaeb51
Date: 2023-06-12T05:21:26.842Z
Electron: 22.5.5
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Windows_NT x64 10.0.25387
- OS Version: Windows 11 Insiders

Steps to Reproduce:

I can reproduce this locally and in a dev container.

1. Run command `Welcome: Open Walkthrough...`
2. Only see the 3 core walkthroughs 
3. Run command `Help: Welcome`
4. See there are more walkthroughs on the welcome page
5. Try `Welcome: Open Walkthrough...` again, now see the full set of walkthroughs that I saw on the home page

**Comment by bhavyaus** [comment]
This issue has been around. The `gettingStartedService` is not primed yet and hence is missing the extension walkthroughs. Running the same command again displays all walkthroughs
