### ISSUE TITLE
In markdown preview, if the font size is not the original 12 px, the editor's preview window will have a row of blank space

### ISSUE THREAD

**Issue by iamwrm** [Microsoft/vscode#18495]
- VSCode Version: Code 1.8.1 (ee428b0eead68bf0fb99ab5fdc4439be227b6281, 2016-12-19T14:42:49.304Z)
- OS Version: Darwin x64 16.3.0
- Extensions:

|Extension|Author|Version|
|---|---|---|
|code-gnu-global|austin|0.2.1|
|theme-dark-monokai|bogdan-sinitsa|0.3.0|
|CppSnippets|hars|0.0.5|
|vscode-clang|mitaki28|0.2.1|
|cpptools|ms-vscode|0.9.3|
|vscode-icons|robertohuertasm|6.0.0|
|vim|vscodevim|0.4.10|

---
![im1-normal](https://doc-0o-2g-docs.googleusercontent.com/docs/securesc/ha0ro937gcuc7l7deffksulhg5h7mbp1/3jfeom16obo9airg4dtnjvbthqls2a0k/1484287200000/06480732660433267696/*/0B3Mi3s5y0UmASVRjX0s1Nms3UjQ)

![im2-bug](https://doc-0o-2g-docs.googleusercontent.com/docs/securesc/ha0ro937gcuc7l7deffksulhg5h7mbp1/ma7em2fabrvihj8ngc6buebfkkda560j/1484287200000/06480732660433267696/*/0B3Mi3s5y0UmARTlwRGpzMU5Jbjg)

Steps to Reproduce:

1. open any .md file
2. toggle markdown preview
3. use `command`  + `+` to enlarge the font

**Comment by mjbvz** [comment]
@iamwrm Can you please try uploading the images again? 

I suspect this is a duplicate of #5745 (see issues such as #14329 for example that are root caused to #5745)

**Comment by iamwrm** [comment]
@mjbvz 
Yes exactly. It's a duplicate.
I'll go over that issue and find some solutions.
Thank you.
