### ISSUE TITLE
Can't make the function tooltip disappear after the braces have been removed

### ISSUE THREAD

**Issue by DominikDitoIvosevic** [Microsoft/vscode#18498]
- VSCode Version: 1.8.1
- OS Version: Win10

Steps to Reproduce:

![2017-01-12_17-02-16](https://cloud.githubusercontent.com/assets/6378638/21897123/eb2c7f6e-d8e8-11e6-81b9-b4d763048fcd.gif)

So I want to make the tooltip disappear after the bracket is removed but it only disappears after ESC is pressed (endline, random character, new bracket don't remove it).

I suppose the problem is with the language server but I was wondering if you could tell me what triggers the disappearance. I've tried with a js file and it works normally.

**Comment by dbaeumer** [comment]
@joaomoreno @jrieken any tip?

@DominikDitoIvosevic which extensions do you have installed ?

**Comment by DominikDitoIvosevic** [comment]
AL Lanugage extension (I'm working on that one). I'm from the Modern Dev team (msft).

**Comment by jrieken** [comment]
Your signature help provider must return something falsy (null/undefined) for it to close

**Comment by DominikDitoIvosevic** [comment]
Thanks @jrieken ! I finally found the time to check and fix this :D
I was returning from the handler without adding a falsy SignatureHelp to the ResponseQueue.
I can confirm this fixes the problem.
