### ISSUE TITLE
Tasks endlessly fetches build tasks in remote

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#184941]
Repro:

1. `code tunnel` (Windows)
2. Connect to it via local desktop, open vscode repo
3. Run default build task

I then see:

1. Activating extensions
2. Fetching build tasks...
4. A task errors notification which shows an error with gulp hygiene
5. Fetching build tasks never ends
6. There are multiple Fetching build tasks notifications if you run default build task again

![image](https://github.com/microsoft/vscode/assets/2193314/855e1e62-c377-4a2f-bd41-813314241cc9)

![image](https://github.com/microsoft/vscode/assets/2193314/c07f49ee-e8ff-4821-b880-b2d6f80d310a)

![image](https://github.com/microsoft/vscode/assets/2193314/ead582e5-3016-43cf-86da-4c493b0bff81)

![image](https://github.com/microsoft/vscode/assets/2193314/c1228525-3982-4c75-b7f4-01077dcd52cb)

Version: 1.80.0-insider (user setup)
Commit: ef6abe4cd1573689d070b8715e97019cfadaeb51
Date: 2023-06-12T05:21:26.842Z
Electron: 22.5.5
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Windows_NT x64 10.0.22621

**Comment by Tyriar** [comment]
Not reproducible every time; worked after I reloaded

**Comment by meganrogge** [comment]
This is working for me. It's possible I fixed this in one of the many task changes.
