### ISSUE TITLE
toggleSuggestionDetails when there is no jsdoc

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#18490]
From this question: http://stackoverflow.com/questions/41614733/see-the-entire-information-of-intellisense

I can use ctrl+space in the intellisense window for toggleSuggestionDetails when something has JSDoc, but otherwise, I can't see the full untruncated details.

- Add this code to any TS file:
```
declare var FooBar: {
	new(): typeof FooBar;
	prototype: ErrorEvent;
	bar(): any;
}
```

- Type `FooBar` and trigger intellisense
- See that there is cut off text, describing the type of FooBar, and ending in ... like in the SO question, but no way to see the full text.

![image](https://cloud.githubusercontent.com/assets/323878/21918538/19e997e2-d907-11e6-9061-3d5cbbd01ffd.png)

- Add a jsdoc-style to the thing, like

```
/**
 * foo
 */
```

- Now when you repeat the steps to see intellisense, you can press ctrl+space again to see a large popup with the full text

![image](https://cloud.githubusercontent.com/assets/323878/21918542/25ff259c-d907-11e6-95d2-d328cff78284.png)

Should this be available in every case? Maybe it's not because we don't know whether the text is cut off.

**Comment by mjbvz** [comment]
This does not seem JS specific. I think the bug is that we only allow expanding the completion item if it has the `documentation` property set. We should also allow expansions if the `detail` property has any new lines in it
