### ISSUE TITLE
Git Bash launches into external terminal when set as integrated terminal for windows VSCode version 1.79.0

### ISSUE THREAD

**Issue by saschoff** [microsoft/vscode#184914]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.79.0
- OS Version: Windows_NT x64 10.0.19045

Steps to Reproduce:

1. Set Git bash as the default integrated terminal for Windows
2. From the menu select Terminal -> New Terminal
3. Git Bash opens outside of VS Code in an external Git Bash command prompt and an empty, non-interactive console remains open in VS Code

I just took this latest update for VS Code (1.79.0) and this started happening.  Here is how my settings are for integrated terminal in settings.json:

"terminal.integrated.defaultProfile.windows": "Git Bash",
  "terminal.external.windowsExec": "",
  "terminal.integrated.automationProfile.windows": null,
  "terminal.integrated.profiles.windows": {
    "Git Bash": {
      "source": "Git Bash",
      "path": "C:\\Program Files\\Git\\git-bash.exe"
    }
  }

I updated Git to version 2.39.1-1.0.0 to see if that would fix and it did not.

Selecting Windows normal command prompt and PowerShell still work as integrated terminals.

**Comment by meganrogge** [comment]
What happens if you remove this:

```
"terminal.external.windowsExec": "",
```

**Comment by saschoff** [comment]
> "path": "C:\Program Files\Git\git-bash.exe"

That worked!  Thank you!
