### ISSUE TITLE
Very slow when view the large-stack-array in debugging program

### ISSUE THREAD

**Issue by AbelaroJiang** [Microsoft/vscode#18503]
- VSCode Version: Code 1.8.1 (ee428b0eead68bf0fb99ab5fdc4439be227b6281, 2016-12-19T14:41:20.664Z)
- OS Version: Linux x64 4.4.0-45-generic
- Extensions:

|Extension|Author|Version|
|---|---|---|
|compulim-vscode-dictionary|Compulim|0.0.5|
|java-debug|DSnake|0.0.2|
|start-git-bash|McCarter|1.1.0|
|code-settings-sync|Shan|2.4.2|
|logcat|abhiagr|0.0.6|
|code-gnu-global|austin|0.2.1|
|GBKtoUTF8|bukas|0.0.2|
|vscode-javac|georgewfraser|0.0.23|
|CppSnippets|hars|0.0.5|
|vscode-csscomb|mrmlnc|4.0.0|
|PowerShell|ms-vscode|0.8.0|
|cpptools|ms-vscode|0.9.3|
|vscode-icons|robertohuertasm|6.0.0|
|vscode-header-source|ryzngard|1.0.4|
|guides|spywhere|0.6.1|
|java-imports-snippets|tushortz|0.0.1|
|java-snippets|tushortz|0.0.1|
|cmake|twxs|0.0.15|
|vscode-react-native|vsmobile|0.2.5|
|intelligence-change-case|zhengxiaoyao0716|1.1.0|
|vscode-proto3|zxh404|0.0.7|

---

Steps to Reproduce:
example:
int main()
{
    char buf[2048] = "";
    return 0;
}

1.debug a c/c++ program.
2.define a large stack array(such as 1024, 2048...102400).
3.set break point below the large-stack-array.launch gdb debug mode with vscode. 
4.view the large-stack-array content at the Locals area.

Problem: it 's very slow when view the large-stack-array in debugging program.
Pls help me to solve this problem.

**Comment by mjbvz** [comment]
Please try opening this against the cpptools extension first: https://github.com/Microsoft/vscode-cpptools/issues
