### ISSUE TITLE
Turn on editor.quickSuggestions for Markdown by default?

### ISSUE THREAD

**Issue by yinan1048576** [microsoft/vscode#185075]
Hi, I noticed that the `editor.quickSuggestions` setting is [turned off](https://github.com/microsoft/vscode/blob/352d2d3934fd0d2e62cd3992038cc6476f7e8b45/extensions/markdown-language-features/package.json#LL664C37-L664C37) for Markdown by default.

I find my experience of editing Markdown files in VS Code less efficient than other files because of that, for two reasons:

- I cannot quickly type words I typed before.
- I cannot use snippets to quickly expand out to templates.

I know I can alter the `editor.quickSuggestions` setting, but do you think if it can be turned on by default? I don't see a clear reason why not, but perhaps I'm missing something - please let me know if it's the case.

Thank you!

**Comment by mjbvz** [comment]
This is by design and easy to turn back on. We've found showing suggestions while typing normal text to be a pretty annoying default
