### ISSUE TITLE
Need support to specify cwd per terminal instance

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#18506]
- VSCode Version: 1.9.0

The task framework supports to specify a cwd per task (e.g command). To support this when running tasks in a terminal I need API to set the cwd per created terminal instance.

**Comment by Tyriar** [comment]
@dbaeumer FYI I changed `ITerminalService.createInstance` to accept an `IShellLaunchConfig` as part of this which should make it a lot nicer to call.
