### ISSUE TITLE
Tooling stops working after VSCode update

### ISSUE THREAD

**Issue by olliephillips** [Microsoft/vscode#18508]
- VSCode Version: Code 1.8.1 (ee428b0eead68bf0fb99ab5fdc4439be227b6281, 2016-12-19T14:42:49.304Z)
- OS Version: Darwin x64 15.0.0
- Extensions:

|Extension|Author|Version|
|---|---|---|
|elm-format|abadi199|0.1.0|
|Go|lukehoban|0.6.51|
|prettify-json|mohsen1|0.0.3|
|elm|sbrink|0.8.3|
|Material-theme|zhuangtongfa|1.0.3|

---

Steps to Reproduce:

1. Update VSCode
2. Go tooling such as Goimports and Gofmt seem to stop working

I would suggest this can't be reliably reproduced, but I've seen this behaviour on a couple of updates.  Preferences are not changed.  On the last occasion even restarting did not help. 

I should say that the issue seems temporary. In that the tooling does eventually work again without action on my part. I'm wondering if the plugins that provide the tooling mentioned take time to update.

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/vscode-go#722
