### ISSUE TITLE
Compound debugging fails with "Configuration '<name>'does not exist."

### ISSUE THREAD

**Issue by Loghorn** [Microsoft/vscode#18502]
- VSCode Version: 1.9.0-insider (2cdc2b3da8f0fd5322b48747241584cf9dd98f8f)
- OS Version: Windows 10 Insider 15007

Steps to Reproduce:

1. Open a node.js project and edit `launch.json` to add a compound configuration
2. Start debugger with the compound debugging configuration selected
3. The error message appears and debug does not start

**Comment by mjbvz** [comment]
@Loghorn Can you share your `launch.json`?

**Comment by Loghorn** [comment]
Here it is:
[launch.zip](https://github.com/Microsoft/vscode/files/707646/launch.zip)
