### ISSUE TITLE
Git Sync fails with error: unable to write file .git/objects/c5/eb4274e2f1f9d7f567c0d01412d3905a498604: Invalid argument

### ISSUE THREAD

**Issue by jmalloci** [microsoft/vscode#185099]
Type: <b>Bug</b>

When trying to commit changes to repo using VS Code Source Control Git, it gives error: unable to write file .git/objects/c5/eb4274e2f1f9d7f567c0d01412d3905a498604: Invalid argument. I have had no isssues pushing before only in the last few days have I experienced this issue. Currently on newest updated version of VS Code. I have staged a commit and whenever I try to sync/pull/fetch it fails with this error.

VS Code version: Code 1.79.1 (4cb974a7aed77a74c7813bdccd99ee0d04901215, 2023-06-12T16:14:05.102Z)
OS version: Windows_NT x64 10.0.19044
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|12th Gen Intel(R) Core(TM) i5-1250P (16 x 2112)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.24GB (2.54GB free)|
|Process Argv|--crash-reporter-id 3456828a-f755-4e94-a467-40ad368f5750|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
aadb2c|Azu|1.3.5
xml|Dot|2.5.1
vscode-azureresourcegroups|ms-|0.7.5
vscode-azurestorage|ms-|0.15.3
azure-account|ms-|0.11.5

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
vscccc:30610679
2e4cg342:30602488
pyind779:30671433
89544117:30613380
vscrp:30673768
pythonsymbol12:30671437
showlangstatbar:30737416
vsctsb:30748421
pythonms35:30701012
a2ce3375:30757347
pythonfmttext:30731395
pythoncmv:30756943
fixshowwlkth:30730052
pythongtdpath:30739704
dh2dc718:30763024
pythonnosmt12:30765603

```

</details>

**Comment by lszomoru** [comment]
@jmalloci, does the same error occurs if you try to run these operation from the terminal?

**Comment by lszomoru** [comment]
@jmalloci, that seems to indicate that this is probably an issue with the git repository store and not VS Code. I would like to suggest that you post your question on stackoverflow as that would be a more appropriate forum. Thank you!
