### ISSUE TITLE
Terminal welcome message animates the buttons the first time it's shown

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#185026]
Repro is open the terminal in a github.dev/web window

![Recording 2023-06-13 at 07 28 29](https://github.com/microsoft/vscode/assets/2193314/20dc8ca8-0bd7-4d1a-a7a1-85e9aa8aa3f2)

**Comment by daviddossett** [comment]
Hmm, it almost seems like there's a resize happening to trigger that animation. Normally you'd only see it when manually resizing a welcome view afaik.

**Comment by Tyriar** [comment]
Applying some class shortly after opening and using that for the transition rule should fix it

**Comment by Tyriar** [comment]
Don't think this happens anymore
