### ISSUE TITLE
Add line per line in Git panel

### ISSUE THREAD

**Issue by maxime1992** [Microsoft/vscode#18509]
It would be nice to have an equivalent of `git add -p`.

For example when looking at a file diff, on the left, close to line number have a `+` symbol to add only that line in staging.

**Comment by kaiwood** [comment]
This feature is already supported, although not in the same way as in your example. Just open your diff view, select the line(s) you want to add and use `Stage Selected Lines` from the menu in the upper right corner:

![screen shot 2017-01-13 at 14 05 47](https://cloud.githubusercontent.com/assets/7542/21931106/e8c41be0-d999-11e6-9c35-3ae132e0ef16.png)

**Comment by maxime1992** [comment]
This is awesome I totally missed it.
Thanks @kaiwood !

**Comment by maxime1992** [comment]
@kaiwood on the opposite, can we reset line per line ? For example if I want to keep a bloc somewhere, I'll do it you way but I also have another block (or even a line) that I want to remove.

Can I reset it somewhere ?

**Comment by kaiwood** [comment]
It works both ways, yes. 

You have to open a diff view for the stage changes here by clicking the file here:

![screen shot 2017-01-24 at 08 59 15](https://cloud.githubusercontent.com/assets/7542/22238802/b5936596-e213-11e6-91f1-33b2af808f1a.png)

Then simply select the lines you want (you can select multiple lines by tripple-clicking the first line and then alt+tripple-click the additional lines you want). There should now be `Unstage Selected Lines` in the same menu:

![screen shot 2017-01-24 at 08 59 32](https://cloud.githubusercontent.com/assets/7542/22238898/195790a2-e214-11e6-8ad5-02533f8544b4.png)

**Comment by maxime1992** [comment]
Yes this is for unstaging and it's already great ! But how about a possibility to reset a line ?

Just like a git reset --soft HEAD for only one line (or a group).

It would be available in "Staged Changes" **and** "Changes" sections. :)

**Comment by kaiwood** [comment]
Ah, reset like in "undoing the changes". Misread that, sorry.

So basically a menu item for `git reset -p`. Looks like this is not supported currently, but might be worth to have. You should absolutely open an issue with a feature request for this 👍

**Comment by maxime1992** [comment]
For the record : https://github.com/Microsoft/vscode/issues/19118

Thanks @kaiwood
