### ISSUE TITLE
Call hierarchy tooltip has dash "-" when there are no details to display

### ISSUE THREAD

**Issue by michelleangela** [microsoft/vscode#185051]
Does this issue occur when all extensions are disabled?: Yes

Version: 1.79.0 (user setup)
Commit: b380da4ef1ee00e224a15c1d4d9793e27c2b6302
Date: 2023-06-07T14:26:35.552Z
Electron: 22.5.5
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Windows_NT x64 10.0.22621

**Typescript sample code:**
```ts
namespace MyNamespace {
  export function sub(a: number, b: number): number {
    return a + b;
  }
}

function addNumbers(a: number, b: number): number {
  return a + b;
}

function caller(a: number, b: number): number {
  return addNumbers(1, 2) + MyNamespace.sub(1, 2);
}
```

**Steps to Reproduce:**

1. Use sample code and do a call hierarchy on function `caller` to show calls from the function.
2. On the call hierarchy tree view result, hover over item "addNumbers" to display tooltip.

**Actual result:**
A dash "-" is added after the function name when there are no function details to display in the tooltip.
![image](https://github.com/microsoft/vscode/assets/38734287/d8e50c6c-051d-4ee0-8117-2020e5128644)

**Other notes:**
It looks like the dash "-" should only be added when the function has details, such as
![image](https://github.com/microsoft/vscode/assets/38734287/7d23417f-b905-46da-99c5-25a2eb5700f1)

**Comment by weartist** [comment]
I'll fix it
