### ISSUE TITLE
Using Notebook Edit API no longer works when replace cells

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode#185070]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:  Insiders (1.80)
- OS Version: N/A

Steps to Reproduce:

1. Use the following code sample and run the command
Next hit undo and you will see the UI is broken.
```typescript
vscode.commands.registerCommand('nb-will-save.helloWorld', () => {
		const activeNotebook = vscode.window.activeNotebookEditor?.notebook;

		if (activeNotebook) {
			const notebookEdit = vscode.NotebookEdit.replaceCells(new vscode.NotebookRange(0, activeNotebook.cellCount), [new vscode.NotebookCellData(vscode.NotebookCellKind.Code, 'print(1)', 'python')]);
			const edit = new vscode.WorkspaceEdit();
			edit.set(activeNotebook.uri, [notebookEdit]);
			vscode.workspace.applyEdit(edit);
		}
	})
```
3. 

Identified the PR that broke this https://github.com/microsoft/vscode/commit/b0bcc33d34f504d0bef88cdb1514bb9eecc93bd6

**Comment by jrieken** [comment]
@joaomoreno Passing this on to you. The title and repro steps are misleading, it the infamous final touches to the perf pr that causes a rendering glitch. See #185071 for a partial revert

**Comment by joaomoreno** [comment]
Yes, this is only about a list perf code change which is OK to leave reverted.

Thanks for the ping.
