### ISSUE TITLE
VS Code Server Login with GitHub Enterprise

### ISSUE THREAD

**Issue by TylerMoll15HP** [microsoft/vscode#185021]
My organization is relatively large, and has pretty strict security concerns. All of our authentication and GitHub use is routed through GitHub Enterprise, so the ability to log in to VS Code Server with a GitHub enterprise token would save a great deal of headache, and allow for more control over the authentication of VS Code Server use.

I believe many others are in my situation and would also really appreciate the feature addition! Thank you!

**Comment by connor4312** [comment]
This is probably covered by https://github.com/microsoft/vscode-remote-release/issues/8150
