### ISSUE TITLE
C code run problem

### ISSUE THREAD

**Issue by Daya3611** [microsoft/vscode#185096]
Type: <b>Performance Issue</b>

test.c: In function 'test':
test.c:7:5: warning: implicit declaration of function 'print' [-Wimplicit-function-declaration]
     print("Squre of Your Number is:%d \n", a*a);
     ^~~~~
C:\Users\DELL\AppData\Local\Temp\ccGXwdxv.o:test.c:(.text+0x3a): undefined reference to `print'
c:/mingw/bin/../lib/gcc/mingw32/6.3.0/../../../libmingw32.a(main.o):(.text.startup+0xa0): undefined reference to `WinMain@16'
collect2.exe: error: ld returned 1 exit status

VS Code version: Code 1.79.1 (4cb974a7aed77a74c7813bdccd99ee0d04901215, 2023-06-12T16:14:05.102Z)
OS version: Windows_NT x64 10.0.22621
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i3-1115G4 @ 3.00GHz (4 x 2995)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|7.74GB (1.68GB free)|
|Process Argv|--crash-reporter-id c65733e5-7b33-4fdb-976e-958ace9e6772|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	    92	  8824	code main
    0	   232	  2292	   gpu-process
    2	    91	  4296	window [2] (Issue Reporter)
    0	    84	  4492	ptyHost
    0	    64	 11364	     C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -noexit -command "try { . \"c:\Users\DELL\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\contrib\terminal\browser\media\shellIntegration.ps1\" } catch {}"
    0	     7	 25592	     console-window-host (Windows internal process)
    0	   129	  4856	extensionHost [1]
    0	    75	   436	     electron-nodejs ("C:\Users\DELL\AppData\Local\Programs\Microsoft VS Code\Code.exe" --ms-enable-electron-run-as-node "c:\Users\DELL\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\json-language-features\server\dist\node\jsonServerMain" --node-ipc --clientProcessId=4856)
    0	    28	 19992	     c:\Users\DELL\.vscode\extensions\ms-vscode.cpptools-1.15.4-win32-x64\bin\cpptools.exe
    0	     5	  6356	       "c:\Users\DELL\.vscode\extensions\ms-vscode.cpptools-1.15.4-win32-x64\bin\cpptools.exe"
    0	    18	 11800	         c:\Users\DELL\.vscode\extensions\ms-vscode.cpptools-1.15.4-win32-x64/bin/cpptools-srv.exe 19992 {026D9000-D48A-4B31-AECA-469170A9A5C9}
    0	    11	 13532	           console-window-host (Windows internal process)
    0	    17	 16264	         c:\Users\DELL\.vscode\extensions\ms-vscode.cpptools-1.15.4-win32-x64/bin/cpptools-srv.exe 19992 {6620898E-91D9-49D8-8E5D-E066FAA0BE4F}
    0	     7	 15744	           console-window-host (Windows internal process)
    0	     7	 16644	       console-window-host (Windows internal process)
    0	   200	  7484	window [1] (test.c - C Shikha - Visual Studio Code [Administrator])
    0	    29	 11608	   crashpad-handler
    0	    94	 12864	shared-process
    0	    71	 18608	fileWatcher [1]
    0	    44	 18728	   utility-network-service
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (test.c - C Shikha - Visual Studio Code [Administrator])
|    Folder (C Shikha): 40 files
|      File types: pdf(23) json(1) exe(1) c(1)
|      Conf files:;
```

</details>
<details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
cmake-tools|ms-|1.14.33
cpptools|ms-|1.15.4
cpptools-extension-pack|ms-|1.3.0
live-server|ms-|0.4.8
cmake|twx|0.0.17

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263cf:30335440
vscorecescf:30445987
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
282f8724:30602487
pyind779:30671433
89544117:30613380
pythonsymbol12:30671437
a9j8j154:30646983
showlangstatbar:30737416
vsctsb:30748421
pythonms35:30701012
03d35959:30757346
pythonfmttext:30731395
pythoncmvfstrcf:30756944
fixshowwlkth:30730052
hideindicator:30766889
pythongtdpathcf:30739705
dh2dc718:30763024
pythonnosm12tcf:30765602

```

</details>

**Comment by roblourens** [comment]
If this is an issue with the C extension, please open an issue there with more details, otherwise it's probably an issue with your code or configuration
