### ISSUE TITLE
Inline Chat takes a long time to show up with big files

### ISSUE THREAD

**Issue by TylerLeonhardt** [microsoft/vscode#185034]
Steps to Reproduce:

1. Have Copilot Chat
1. open the [big.js](https://github.com/microsoft/vscode/files/11736680/big.js.zip) file in VS Code
1. cmd+i

It takes like 2s for the UI to show up. One time when I was doing a lot with VS Code it took so long (like 10s) that I thought I didn't have the extension installed.

Not sure if this is on the UI side or the extension side, but even still, I think the UI should be instant (even if it's perceived fastness) since all I'm seeing is an input box that I will type in.

**Comment by jrieken** [comment]
I have done a bunch of tricks, most importantly to showing the UI while asking the extension to create a session. Also the UI is more lazily created which helps. However, once there are changes the bottleneck is setting up the embedded diff editor. There isn't much I can do about it

<img width="726" alt="Screenshot 2023-06-15 at 16 10 35" src="https://github.com/microsoft/vscode/assets/1794099/493b5a01-afc4-4d2e-b16c-01b19ee83590">
