### ISSUE TITLE
vscode deletes project by running it

### ISSUE THREAD

**Issue by PothpothBR** [microsoft/vscode#185035]
Does this issue occur when all extensions are disabled?: The problem occurred with active extensions.

Versão: 1.79.0
Commit: b380da4ef1ee00e224a15c1d4d9793e27c2b6302
Data: 2023-06-07T14:28:44.251Z
Electron: 22.5.5
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Linux x64 5.19.0-43-generic snap

Steps to Reproduce:

1. press F5
2. sweep your tears

I was with my project after hours of development, decided to run it, and pressed F5. The entire project was deleted, no recovery. The files in the .vscode folder will be attached, as well as the command executed by vscode when I pressed F5.

I had 3 windows of vscode open at the time, and had already run it a few times on the 2 windows not related to the problem.

```bash
rm -fr caches daemon cd /home/bruno/github/supreme-checklist ; /usr/bin/env /bin/python3.11 /home/bruno/.vscode/extensions/ms-python.python-2023.10.0/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher 56347 -- /home/bruno/github/supreme-checklist/main.py 
```

after this command:

![image](https://github.com/microsoft/vscode/assets/41635420/e7e673b0-e227-417f-bead-910357bd6f5c)

the ./vscode/launch.json
```json
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Python: Main",
            "type": "python",
            "request": "launch",
            "program": "${workspaceFolder}/main.py",
            "console": "integratedTerminal"
        }
    ]
}
```

the ./vscode/settings.json
```json
{
    "materialkv.pythonFile": "main.py"
}
```

These files were retrieved by the version in my git repository.

The .vscode files have not been changed at any time, no vscode settings have been changed as well as no extensions have been installed, in the last 2 months.

I use vscode daily for at least 8 hours.

**Comment by roblourens** [comment]
Sorry for the trouble, had you started typing the `rm -rf` command in the python debugger's terminal before pressing F5? If so there is an open issue to address that. Otherwise, where did the `rm` come from?

**Comment by PothpothBR** [comment]
I use buildozer to compile a kivy application in python. I didn't run any remove commands, just run `buildozer android debug deploy run logcat`. VSCode opens a new shell to run a python application (Python Debug Console), which had not been opened before. So I can guarantee that there was nothing dumped before the command was executed.

**Comment by roblourens** [comment]
Will fold this into https://github.com/microsoft/vscode/issues/106743
