### ISSUE TITLE
`Copy` context menu item copies whole response in panel chat instead of selected text

### ISSUE THREAD

**Issue by ulugbekna** [microsoft/vscode#185088]
https://github.com/microsoft/vscode-copilot-release/assets/16353531/ab0227d7-b600-4b04-9ff2-5babffeda4f3

# Repro

1. Have some text as response in panel chat
2. Select part of it, right click, click on `Copy` - the whole response instead of the selection is copied

# Version info

```
Version: 1.80.0-insider
Commit: 990d40aad4e5fe57500132cae7ad8c69950399b0
Date: 2023-06-14T00:21:29.167Z
Electron: 22.5.7
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Darwin arm64 22.5.0
```

**Comment by roblourens** [comment]
Not even sure if I can fix this

**Comment by roblourens** [comment]
https://github.com/microsoft/vscode-copilot-release/issues/416
