### ISSUE TITLE
Text highlighted with double click intermittently can't be edited

### ISSUE THREAD

**Issue by massimocode** [Microsoft/vscode#1850]
Hi

Before I continue I just want to say thanks for all the hard work on making visual studio code a fantastic editor. I prefer it to WebStorm, Atom, Sublime and anything else!

Ok to the main point, I have noticed what I think is a bug.

When editing simple JS files (although not tried with other languages), if I double click a word (to highlight it) and then start tying (i.e. to replace it), it sometimes ignores my typing.

I'm using the standard dark theme and I have noticed that when this is the case, the highlight is a slightly different colour to the normal editable selected text highlight.

I have also noticed that is happens more often if I double click quickly on a word, as opposed to if I double click more slowly.

I have a feeling that because this is running on Electron and essentially some kind of web application, maybe there is a race condition of sorts where if I double click too fast, the electron framework detects a select "span element" as opposed to the editor detecting that I'm highlighting a word for editing.

It might be a bug in the underlying Electron framework and not VS Code itself, but I have no idea, just suggesting. I have asked a friend who uses Atom on the same setup as me (also uses Electron) and he says he can't replicate, but he did say he uses a plugin which highlights the same words as the selected word (https://atom.io/packages/highlight-selected).

For additional information that might be of relevance in reproducing the issue, I am using VS Code 0.10.6 (latest release), Mac OS X (version 10.10.5), using the application in full screen mode (i.e. Command+Ctrl+F) and using an external USB mouse.

**Comment by alexandrudima** [comment]
I think what can happen is that in some configurations the native browser selection occurs on double click. @massimocode To help us try to reproduce, can you please share any settings you have customized (e.g. font family, font size, etc.)

**Comment by massimocode** [comment]
Hi @alexandrudima 

My settings are as below:
`{
  "editor.formatOnType": true,
  "editor.insertSpaces": true,
  "filePicker.alternateFileNameMatching": true,
  "window.zoomLevel": 1,
  "editor.tabSize": 2
}`

I think the only setting I have that might be influencing this is the window.zoomLevel

**Comment by massimocode** [comment]
Please note that it is very difficult to replicate. It happens maybe 1 in every 20 times or something. So it will need some persistence!

**Comment by alexandrudima** [comment]
@massimocode Indeed, the zooming (due to Chromium bugs?) might leave tiny 1px gaps in between lines. Then, double clicking in there could get the native browser selection occur. I'm wondering why do you prefer changing the `zoomLevel` over customizing the `editor.fontSize` and `editor.lineHeight`?

**Comment by massimocode** [comment]
I have just spent some time trying out the font size and line height settings and managed to find the correct ones to replicate the window.zoomLevel setting I had set. However, everything else (apart from the editor) is still small (i.e. the folder navigation pane on the left, the popup command window, the status bar, etc).

I guess if this is a Chromium bug then nothing much can be done and I'll continue using window.zoomLevel for now because squinting at small text is difficult!

I can confirm that it is only in certain pixels that this behaviour occurs so you are most likely correct.

**Comment by alexandrudima** [comment]
@bpasero and I have actually seen this together on his mac, when he was using `zoomLevel`. I forgot the exact commit, but the issue was the following:
- the mouse event we got from Chromium had as target the token text
- we would then use hit testing to find out at which offset the mouse hits the token text
- the hit test would (incorrectly?) hit a view cursor
- the logic was not ready for such inconsistency between a mouse event's target and its posx/posy.

**Comment by bpasero** [comment]
Yes, we fixed this one for March! Also had this but only when zooming in.

**Comment by vilic** [comment]
:+1: BTW, though it's labeled with `mac`, it's happening on Windows as well.

**Comment by bpasero** [comment]
To verify, install our insiders build: http://code.visualstudio.com/insiders

**Comment by vilic** [comment]
@bpasero Thanks, seems to be fixed.

**Comment by malibuzios** [comment]
I was just going to report this. I felt this was the single most significant and disturbing bug on VS code. Anyway, at least for future reference, here's an animated screen capture I've made for it (note I'm using Windows 10 x64 so this is definitely not a Mac-only issue):

![vs code bug](https://cloud.githubusercontent.com/assets/17719551/14317023/dd22f2e8-fc0e-11e5-8672-dbe07378678a.gif)

**Comment by bpasero** [comment]
You can give it a try from our insiders release today: http://code.visualstudio.com/Download#insiders
