### ISSUE TITLE
Status Bar Item not appear while in remote container

### ISSUE THREAD

**Issue by r0548** [microsoft/vscode#185089]
Type: <b>Bug</b>

I add a ststus bar item on extension activation and install the extension from .VSIX.
When openning a remote container the status bar item disappears and the extension is not included when right click on status bar, this issue does not occur on version 1.78

VS Code version: Code 1.79.1 (4cb974a7aed77a74c7813bdccd99ee0d04901215, 2023-06-12T16:14:05.102Z)
OS version: Windows_NT x64 10.0.19045
Modes:
Remote OS version: Linux x64 5.15.90.1-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3770 CPU @ 3.40GHz (8 x 3392)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: unavailable_off<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.82GB (1.65GB free)|
|Process Argv|--enable-proposed-api undefined_publisher.elmo --crash-reporter-id 556e21dd-915c-4f34-93dc-6343dc40b80e|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|Dev Container: Elmo Toolchains|
|OS|Linux x64 5.15.90.1-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i7-3770 CPU @ 3.40GHz (8 x 3392)|
|Memory (System)|7.67GB (5.64GB free)|
|VM|0%|
</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
maestro-toolchains|elm|0.0.3
remote-containers|ms-|0.295.0
remote-ssh|ms-|0.102.0
remote-ssh-edit|ms-|0.86.0
remote-explorer|ms-|0.4.0
cmake-tools|ms-|1.14.33
cpptools|ms-|1.15.4
cpptools-extension-pack|ms-|1.3.0
cmake|twx|0.0.17

</details>

**Comment by bpasero** [comment]
@jrieken for if this is maybe a duplicate of https://github.com/microsoft/vscode/issues/184395

@r0548 is this a extension you develop or something else?

**Comment by r0548** [comment]
Yes,  this is an extension I develop (extensionKind = "ui") and it looks fine while working locally, but when opening a dev container I can see the status bar item for a second and then it disappears and other status bar items from other extensions are shown.
It might be related to the fact that the extension is activated immediately on container load, I tried using an extension activated by manual command and it worked, but I noticed a strange behavior: if the extension is set as extensionKind = "workspace" the item is displayed in the right side of status bar, as defined, but if I change it to extensionKind = "ui" the item is displayed on the left side instead.

**Comment by bpasero** [comment]
Do you use a unique identifier for the status entry? Are you using multiple entries with the same ID?

**Comment by r0548** [comment]
Using an id resolved the problem, Thanks!
