### ISSUE TITLE
Remote attach of vscode debugger to dlv debugger does not show struct values

### ISSUE THREAD

**Issue by gopiextrahop** [microsoft/vscode#185050]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 
- Version: 1.79.0
Commit: b380da4ef1ee00e224a15c1d4d9793e27c2b6302
Date: 2023-06-07T14:31:03.317Z
Electron: 22.5.5
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Darwin arm64 22.5.0

dlv debugger version: 1.20.2

Steps to Reproduce:

1. Write a simple test go program like below.
```go
package sfsinker

import (
	"os"
	"testing"
)

func TestMain(m *testing.M) {
	os.Exit(m.Run())
}

func TestDelve(t *testing.T) {
	
	val2 := "tst"
	//get file info
	fileInfo, err := os.Stat("/home/gopi/.zshrc")
	//handle error
	if err != nil {
		t.Log("Fail")
	}

	t.Logf("File info: %+v\n", fileInfo)
	t.Logf("%s", val2)
}
```
2. Use dlv remote connect to debug the test in headless mode
```bash
dlv test --log --api-version 2 --headless --listen "127.0.0.1:50000" --only-same-user=false --build-flags '--tags=integrationtest' --wd "/home/jdoe/code/project/pkg/sfsinker" -- -test.v
# connect to the debugger using dlv
dlv connect 127.0.0.1:50000
``` 
3. You can set breakpoints and print struct values like below:

![image](https://github.com/microsoft/vscode/assets/55415440/433fa634-10a6-4e0d-be71-6bd5cc239a15)

4. Now do the same with vscode to debug remotely, here's the launch.json setting

```json
        {
            "name": "Integration Tests Attach To Debuggee",
            "type": "go",
            "request": "attach",
            "mode": "remote",
            "remotePath": "${workspaceFolder}",
            "port": 50000,
            "host": "127.0.0.1",
            "apiVersion": 2
        },
```

5.Try to view struct values, but it is not visible in vscode debugger. Can see other non-struct variable value.

![image](https://github.com/microsoft/vscode/assets/55415440/095fdc6c-b9d1-4e58-836a-af914e26441c)

**Comment by gopiextrahop** [comment]
Might be dup of https://github.com/microsoft/vscode-go/issues/3035 ?

**Comment by roblourens** [comment]
Please open an issue on the go debug extension repo
