### ISSUE TITLE
Cannot open Visual Studio Code when Offline (no internet connection)

### ISSUE THREAD

**Issue by thanhcuong90** [Microsoft/vscode#18507]
- VSCode Version: Code 1.8.1 (ee428b0eead68bf0fb99ab5fdc4439be227b6281, 2016-12-19T14:49:23.350Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions:

|Extension|Author|Version|
|---|---|---|

---

Steps to Reproduce:

1. Off your internet
2. Start Program Visual Studio Code

**Comment by mjbvz** [comment]
Please provide some additional information here to help us investigate. VSCode normally works fine offline

**Comment by dbaeumer** [comment]
@thanhcuong90 without additional information we can't investigate the issue. Will reopen the issue when additional information is provided.

**Comment by BSykesUSCG** [comment]
I am able to reproduce this.  Fresh copy of Visual Studio Code and attempt to run on a machine that is disconnected from internet access results in screen appearing but the application hangs completely.  Tested on Windows Server 2012R2.  CPU is spiked to 100% by the Visual Studio Code process.

**Comment by dbaeumer** [comment]
@BSykesUSCG can you provide the command line of the Visual Studio Code process that has 100% CPU load?

**Comment by BSykesUSCG** [comment]
Reproduced on two separate machines at my location.  

"XXXXXX\DotNet\VSCode-win32-1.8.1\Code.exe" --type=renderer --no-sandbox --primordial-pipe-token=F436D4581BC6D17D9CAF6C3BC8C960F2 --lang=en-US --app-user-model-id=Microsoft.VisualStudioCode --node-integration=true --background-color=#1E1E1E --enable-pinch --device-scale-factor=1 --num-raster-threads=1 --content-image-texture-target=3553,3553,3553,3553,3553,3553,3553,3553,3553,3553,3553,3553,3553,3553,3553 --video-image-texture-target=3553,3553,3553,3553,3553,3553,3553,3553,3553,3553,3553,3553,3553,3553,3553 --disable-accelerated-video-decode --disable-webrtc-hw-encoding --disable-gpu-compositing --mojo-channel-token=33C3A637ADC8A62D808730F7AD405879 --mojo-application-channel-token=F436D4581BC6D17D9CAF6C3BC8C960F2 --channel="3892.0.407487230\289126489" --mojo-platform-channel-handle=1584 /prefetch:1	No	Visual Studio Code

**Comment by dbaeumer** [comment]
@bpasero @joaomoreno any idea what could cause this?

**Comment by bpasero** [comment]
Looks to me like https://github.com/Microsoft/vscode/issues/7570 which however I was never able to reproduce. 

@thanhcuong90 can you try to start Electron on that setup? I wonder if it starts (https://github.com/electron/electron/releases/download/v1.4.15/electron-v1.4.15-win32-ia32.zip)

**Comment by dbaeumer** [comment]
@BSykesUSCG can you try @bpasero test https://github.com/Microsoft/vscode/issues/18507#issuecomment-274713733 as well?

**Comment by BSykesUSCG** [comment]
Running electron appears to work without issues.  Just starting the exe (double-click) brings up the window and it is responsive.  
I tried clearing out the appdata cache I found in AppData\Roaming\Code as a coworker believed the app worked upon first launch but hung after that.  Unfortunately clearing that cache did not seem to help and as yet the first run theory has not yet been confirmed.  Are there any other cache locations that I should try?

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: http://code.visualstudio.com/Download#insiders

**Comment by BSykesUSCG** [comment]
It appears to exhibit the same behavior.  

Additional detail:  If I use task manager to lower the cpu priority on the thread that is eating all the CPU to low I am able to access the menu and window normally.  Other than that things are very limited.  The window itself is black inside the border and menus generally don't do anything.  The exception seems to be the Help->About and Help->Toggle Developer Tools which both do come up.

![capture](https://cloud.githubusercontent.com/assets/25253059/22254573/f6eb955e-e222-11e6-974d-e4592c88d1f0.JPG)

**Comment by bpasero** [comment]
@BSykesUSCG is there any output in the "Console" when you open "Developer Tools"? Could you start a profiling session to capture where most time is spend?

To create a CPU profile using developer tools in VS Code:
* select Help > Toggle Developer Tools
* click on Profiles
* click the start button
* do whatever you need to do to get the CPU spin high
* wait for some time (10-20 seconds should be enough)
* stop the profiling 
* click the save button and attach the output file to this issue

**Comment by BSykesUSCG** [comment]
Ok, get this....

Open up, start the profile and wait 20 sec.  Hit the stop button and it hangs for what I'm betting was an additional 60 sec.  It finally completes, the trace comes up _and the CPU load drops off and the app LOADS finally......_

The trace is 16MB unzipped
[CPU-20170124T121452.zip](https://github.com/Microsoft/vscode/files/727389/CPU-20170124T121452.zip)

**Comment by bpasero** [comment]
I wonder if this is Windows Server 2012 related. Any chance you could test on a different OS?

**Comment by BSykesUSCG** [comment]
Yep, it works fine on a 2008R2 box.  So its either the OS difference or some security tool that we have installed that is different between the machines.  Its odd though because I left the app running on the 2012R2 box for more than an hour and it does not come up until you follow the process I described above.  Its flipping some bit somewhere that lets it "pass" whatever is causing the CPU spike.

**Comment by bpasero** [comment]
I suggest we continue in https://github.com/Microsoft/vscode/issues/7570
