### ISSUE TITLE
auto-complete/intellisense extremely slow

### ISSUE THREAD

**Issue by andy-crain-kr** [microsoft/vscode#185047]
Does this issue occur when all extensions are disabled?: Yes (tested both with extensions enabled, and with all extensions disabled; same behavior both cases)

- VS Code Version: 
  Version: 1.79.0 (Universal)
  Commit: b380da4ef1ee00e224a15c1d4d9793e27c2b6302
  Date: 2023-06-07T14:29:00.206Z (6 days ago)
  Electron: 22.5.5
  Chromium: 108.0.5359.215
  Node.js: 16.17.1
  V8: 10.8.168.25-electron.0
  OS: Darwin x64 22.5.0

- OS Version: macOS Ventura 13.4

Starting very recently, approximately 2023-06-13T00:00Z, all auto-complete/intellisense functionality has slowed down dramatically, even though no updates to VS Code or installed extensions occurred recently.

Steps to Reproduce:

1. Open VS Code
2. In a .ts file, start typing a symbol or function, wait 5+ seconds for the editor to suggest auto-completion options

This occurs for a project with a decent-sized number of packages installed in node_modules (551 packages installed, with 8372 total files in node_modules). It does not occur, and performance is fine, when opening a single file. But the slowness experienced in the first case, with many installed packages, is new as of yesterday, didn't occur for the same project prior to yesterday.

**Comment by andy-crain-kr** [comment]
Performance profile:
[Profile-20230613T131326.json.zip](https://github.com/microsoft/vscode/files/11737689/Profile-20230613T131326.json.zip)

**Comment by andy-crain-kr** [comment]
Additionally, the problem is resolved if I delete node_modules, but of course I can't leave these deleted. I also tried adding node_modules to the excluded files (`"files.exclude": { "node_modules": true }`) but this did not resolve the issue.

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

If it does, can you share a project which demonstrates the issue?

**Comment by andy-crain-kr** [comment]
@mjbvz this seems to have resolved after I updated to
