### ISSUE TITLE
Go to Definition no longer works after update to 1.8.1

### ISSUE THREAD

**Issue by chadi-kazan** [Microsoft/vscode#18504]
- VSCode Version: Code 1.8.1 (ee428b0eead68bf0fb99ab5fdc4439be227b6281, 2016-12-19T14:49:23.350Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions:

|Extension|Author|Version|
|---|---|---|
|vscode-css-formatter|aeschli|0.0.2|
|vscode-color|anseki|0.2.2|
|vscode-eslint|dbaeumer|1.2.2|
|githistory|donjayamanne|0.1.4|
|xml|DotJoshJohnson|1.7.0|
|vscode-babel-coloring|dzannotti|0.0.4|
|flow-for-vscode|flowtype|0.4.0|
|Theme-Facebook|gerane|0.0.2|
|beautify|HookyQR|0.7.3|
|debugger-for-chrome|msjsdiag|2.4.2|
|jsx|TwentyChung|0.0.1|
|console|vilicvane|0.0.6|
|vscode-react-native|vsmobile|0.2.5|
|JavaScriptSnippets|xabikos|1.2.0|
|Material-theme|zhuangtongfa|1.0.3|

---

Steps to Reproduce:

1. install 1.8.1 rather than letting VSC apply the update 
2. reopen jsx file, fina a call to any method in the class in any other method. hit F12 on it and nothing happens

**Comment by mjbvz** [comment]
Can you please provide some example code that show this problem

**Comment by mjbvz** [comment]
Closing as more information is needed to investigate
