### ISSUE TITLE
Unable commit local git without remote configuration

### ISSUE THREAD

**Issue by vanowm** [microsoft/vscode#185073]
Type: <b>Bug</b>

Using source control UI attempting to commit changes to a local git repository, which doesn't have remote configured, partially disabled features in source control UI and commit doesn't go through.
The progress line moves indefinitely, "Commit" button disabled.

Committing via terminal works fine, however the commit is not reflected in source control UI, until vscode is restarted.

How to reproduce:
1) open new VSCode window and add an empty folder to workspace.
2) in source control tab click "initialize repository"
3) create a file or a folder inside this workspace.
4) in source control click commit, the commit never finishes.

![image](https://github.com/microsoft/vscode/assets/511517/6f863898-9fcb-4b7c-ae4f-570c5dee941f)

VS Code version: Code 1.79.1 (4cb974a7aed77a74c7813bdccd99ee0d04901215, 2023-06-12T16:14:05.102Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz (16 x 3600)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|63.67GB (38.14GB free)|
|Process Argv|--verbose|
|Screen Reader|no|
|VM|50%|
</details><details><summary>Extensions (84)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|3.0.2
vscode-userscript|adp|1.3.2
Bookmarks|ale|13.3.1
tsl-problem-matcher|amo|0.6.2
autolispext|Aut|1.6.2
spellright|ban|3.0.116
vscode-log-viewer|ber|0.12.2
vscode-intelephense-client|bme|1.9.5
git-exclude|bou|0.3.1
phpserver|bra|3.0.2
insert-unicode|bru|0.14.0
turbo-console-log|Cha|2.9.3
doxdocgen|csc|1.4.0
autoit|Dam|1.0.11
copy-directory-path|dan|1.0.3
vscode-eslint|dba|2.4.0
xml|Dot|2.5.1
gitlens|eam|13.6.0
EditorConfig|Edi|0.16.4
vscode-great-icons|emm|2.1.93
prettier-vscode|esb|9.13.0
vscode-macros|EXC|1.4.1
vscode-highlight|fab|1.7.3
vscode-firefox-debug|fir|2.9.8
auto-rename-tag|for|0.1.10
remotehub|Git|0.58.0
vscode-pull-request-github|Git|0.66.1
customize-ui|ioc|0.1.65
monkey-patch|ioc|0.1.23
reg|ion|1.1.0
better-cpp-syntax|jef|1.17.2
vscode-peacock|joh|4.2.2
minifyall|jos|2.10.0
node-module-intellisense|lei|1.5.0
Lisp|mat|0.1.12
render-crlf|med|1.6.1
vscode-language-babel|mgm|0.0.39
git-graph|mhu|1.30.0
vscode-filesize|mkx|3.1.0
vscode-apache|mrm|1.2.0
vscode-edge-devtools|ms-|2.1.2
isort|ms-|2022.8.0
python|ms-|2023.10.1
vscode-pylance|ms-|2023.6.10
remote-containers|ms-|0.295.0
remote-ssh|ms-|0.102.0
remote-ssh-edit|ms-|0.86.0
vscode-remote-extensionpack|ms-|0.24.0
azure-repos|ms-|0.34.0
cmake-tools|ms-|1.14.33
cpptools|ms-|1.15.4
cpptools-extension-pack|ms-|1.3.0
hexeditor|ms-|1.9.11
live-server|ms-|0.4.8
remote-explorer|ms-|0.4.0
remote-repositories|ms-|0.36.0
remote-server|ms-|1.2.1
test-adapter-converter|ms-|0.1.8
debugger-for-edge|msj|1.0.15
color-highlight|nau|2.5.0
vscode-auto-scroll|pej|1.1.0
vscode-versionlens|pfl|1.5.0
parse-tree|pok|0.26.4
vscode-phpunit|rec|3.1.2
tmlanguage-syntax-highlighter|Red|2.2.1
vscode-xml|red|0.25.0
format-html-in-php|rif|1.7.0
rust-analyzer|rus|0.3.1549
multi-command|ryu|1.6.0
vbsvscode|Ser|1.2.1
swapdiff|sha|0.2.0
comment-divider|sta|0.4.0
code-spell-checker|str|2.20.5
tabnine-vscode|Tab|3.6.56
tauri-vscode|tau|0.2.6
vscode-ltex|val|13.1.0
intellicode-api-usage-examples|Vis|0.2.7
vscodeintellicode|Vis|1.2.30
vscode-wakatime|Wak|24.0.14
vscode-backup|Wes|0.0.6
php-debug|xde|1.32.1
local-history|xyz|1.8.1
json-color-token|yec|1.3.2
html-css-class-completion|Zig|1.20.0

(2 theme extensions excluded)

</details>

**Comment by gjsjohnmurray** [comment]
Please use the Start Extension Bisect command to investigate whether the problem is being caused by one of your extensions.

**Comment by vanowm** [comment]
I did, the problem reproducible with all extensions disabled. I've noticed the git that vscode is using was outdated, but updated version didn't fix the issue. Also, after closing vscode window, some vscode processes and git processes are stay behind and require manually closing via task manager.
Git output panel shows no related errors.

**Comment by lszomoru** [comment]
@vanowm, given that you can only reproduce this when the folder is on a network drive, I was wondering if you could try setting the `security.restrictUNCAccess` setting to `false`, restating VS Code and checking if you are still able to reproduce. Thanks!

**Comment by vanowm** [comment]
It seems this was due to either/combination of outdated `git.exe` / `gpg.exe` binaries, after update of both, my git signature was lost, so generated new key/signature fixed the issue.
