### ISSUE TITLE
Settings that support glob patterns should validate the glob to only use slashes

### ISSUE THREAD

**Issue by adalisk-emikhaylov** [microsoft/vscode#185100]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.79.1
- OS Version: Windows 10

Steps to Reproduce:

1. Add something like following to `settings.json`:

   ```json
   "files.readonlyInclude": {
        "C:\\Program Files (x86)\\Microsoft Visual Studio\\**": true
    },
    ```

2. Try opening a matching file.
3. Observe that it's not in read-only mode.
4. Close the file.
5. Now try changing the setting to `"C:\\Program Files (x86)\\Microsoft Visual Studio/**": true` (note `/` instead of ``\`` as the last slash).
6. Open a matching file again.
7. Observe that it's correctly opened as read-only.

The globs should work regardless of the slash style used.

**Comment by bpasero** [comment]
All glob patterns in VS Code require you to use `/` for path separators. That is documented here: https://code.visualstudio.com/docs/editor/codebasics#_advanced-search-options

> Paths must use forward slashes.

**Comment by adalisk-emikhaylov** [comment]
@bpasero It being hidden in the manual for "search" (which is an unrelated feature?) looks unintuitive.

I'd suggest to show a warning for malformed globs when editing the config.

**Comment by bpasero** [comment]
Yes, this issue actually made me ask Greg to start having a dedicated topic for glob patterns in our documentation: https://github.com/microsoft/vscode-docs/commit/4c70e37adde19ea1c0fbcace1cb510ba0707d609

We will update it this milestone and then link to it from all places.

Nevertheless, I really like the suggestion of validating those settings that have glob patterns.

**Comment by adalisk-emikhaylov** [comment]
I assume it would be enough to check for ``\*``, ``*\``, and maybe some other patterns.
