### ISSUE TITLE
execute command vscode.commands.executeCommand('outline.removeView') it not work

### ISSUE THREAD

**Issue by Azurehuihui** [microsoft/vscode#185144]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 
- OS Version: 

Steps to Reproduce:

1. execute command vscode.commands.executeCommand('outline.removeView')  will show outline view again. but I want to hide that forver
2.

**Comment by Azurehuihui** [comment]
This will reproduce after executing the command vscode.commands.executeCommand('outline.removeView') twice

**Comment by sbatten** [comment]
@jrieken are commands that have preconditions expected to validate them in their run implementations?

**Comment by jrieken** [comment]
Yes, preconditions are treated as UI-only concept but command execution is always happening

**Comment by benibenj** [comment]
Fixed this a month ago
