### ISSUE TITLE
Extensions do not show up on Activity Bar

### ISSUE THREAD

**Issue by cfunke2** [microsoft/vscode#185120]
Type: <b>Bug</b>

This is not related to one specific extension, it happens at the most or all.
At least at the SFTP Plugin v.1.18.1 from Satiro Marra.
The extension can be installed and enabled normally. But it does not show up in the activity bar and there is no filter item for it.
In the tab "runtime" status there is a hint that something is wrong.
Newest version of VSCode, downgrad to 1.78.2 didn't help, complete reinstall didn't help. Copy Profile from my colleauge did not help.
Asking stackoverflow didnt help: https://stackoverflow.com/questions/76472005/vscode-extension-sftp-does-not-appearing-in-activity-bar

VS Code version: Code 1.79.1 (4cb974a7aed77a74c7813bdccd99ee0d04901215, 2023-06-12T16:14:05.102Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9850H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.79GB (4.43GB free)|
|Process Argv|--crash-reporter-id a44cf253-11c0-4b67-ab47-92cc5df90c32|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-intelephense-client|bme|1.9.5
code-sftp|sat|1.18.1
drtphp|und|0.0.3

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
2e4cg342:30602488
pyind779:30671433
f6dab269:30613381
pythonsymbol12:30671437
showlangstatbar:30737416
vsctsb:30748421
pythonms35:30701012
03d35959:30757346
pythonfmttext:30731395
pythoncmv:30756943
fixshowwlkth:30730052
pythongtdpath:30739704
i26e3531:30763805
dh2dc718:30763024
pythonnosm12tcf:30765602

```

</details>

![problem](https://github.com/microsoft/vscode/assets/7287691/d191387f-4d7d-4cc3-841e-0a657ce6568d)

**Comment by ArturoDent** [comment]
With respect to the `SFTP` extension you mentioned, I have answered your SO question.  It appears you have not activated that extension, which you can do with its `SFTP: Config` command found in the Command Palette.

**Comment by cfunke2** [comment]
Thank you. I think in our company was a special problem with folder protection. Indeed the file must be placed manually and then the extension acitvates.
