### ISSUE TITLE
Options to disable snippet suggestions in the comment region

### ISSUE THREAD

**Issue by gbuntu127** [microsoft/vscode#185142]
Options to disable snippet suggestions in the comment region. 

There is one setting found in user settings: 

_"Editor: Quick Suggestions", it says: "Controls whether suggestions should automatically show up while typing. This can be controlled for typing in comments, strings, and other code. Quick suggestion can be configured to show as ghost text or with the suggest widget. Also be aware of the [Editor: Suggest On Trigger Characters](vscode-file://vscode-app/usr/share/code/resources/app/out/vs/code/electron-sandbox/workbench/workbench.html)-setting which controls if suggestions are triggered by special characters."_ 

However, turning this setting off for "comment" does not prevent snippet suggestions from popping up while typing in the comment region. 

Vscode version:
```
Version: 1.79.1
Commit: 4cb974a7aed77a74c7813bdccd99ee0d04901215
Date: 2023-06-12T16:17:13.990Z
Electron: 22.5.7
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Linux x64 4.15.0-212-generic
```

**Comment by gjsjohnmurray** [comment]
Maybe https://github.com/microsoft/vscode/issues/105373#issuecomment-682503034 is relevant.

**Comment by jrieken** [comment]
> However, turning this setting off for "comment" does not prevent snippet suggestions from popping up while typing in the comment region.

This shouldn't happen and isn't what I see. How do you trigger snippet suggestions? Via ctrl+space or as you type? Can double check your settings file for language specific overwrites?

**Comment by gbuntu127** [comment]
Thanks for your reply. The snippet suggestion was triggered as typing. The only other option I find relevant is to disable snippet suggestions: 

![image](https://github.com/microsoft/vscode/assets/1526055/8868d313-b5d8-4b4f-bbcf-7cb747637082)
However, unchecking this option disables snippet suggestions in all cases.

What I need is to still have snippet suggestions in normal code blocks while typing, but to disable them while typing in the comment area. I am working in Python language specifically. 

Like I mentioned above, when I turn off quick suggestions in the comment block like below:
![image](https://github.com/microsoft/vscode/assets/1526055/e55dab25-0ada-45ed-86f9-260018cf7f4b)
the snippet suggestions still pop up when I type in the comment block:
![image](https://github.com/microsoft/vscode/assets/1526055/4c30aebc-6f34-4b13-a540-326908981a69)

**Comment by jrieken** [comment]
This check the "elsewhere"

![246104675-e55dab25-0ada-45ed-86f9-260018cf7f4b](https://github.com/microsoft/vscode/assets/1794099/78ddcf81-cb67-4644-94ed-8b9bc602b67e)

**Comment by gjsjohnmurray** [comment]
Didi you check for a setting on the Workspace tabs too? Workspace settings trump User ones.

**Comment by gbuntu127** [comment]
There is no setting related in the workspace settings. But I think I see what is going on. The disabling of quick suggestions works for Python comments started with \#comment\#, but not for comments in the triple quote cases ("""comment"""). For this language-specific comment style, would it be possible to add support to account for it?

**Comment by jrieken** [comment]
Looks like the standard token type for these comments is identified as string. I don't know what that is, looks like an issue with the grammar. 

<img width="651" alt="Screenshot 2023-06-15 at 16 22 44" src="https://github.com/microsoft/vscode/assets/1794099/1a978eac-1718-4518-a385-cdc9affda78a">

Forwarding to @alexr00 for this the grammar issue

@gbuntu127 You could workaround this by doing a python specific override to also disable quick suggestions inside strings

**Comment by gbuntu127** [comment]
Thanks @jrieken for the confirmation and workaround suggestion, I will use it for now. It would be nice if the triple quote for Python can be supported as the comment syntax. Thanks!

**Comment by alexr00** [comment]
@DonJayamanne would you expect a python docstring to have syntax highlighting applied as though it were a string or a comment?

**Comment by DonJayamanne** [comment]
I think this is best answered by @debonte @brettcannon

**Comment by debonte** [comment]
> comments in the triple quote cases ("""comment""").

@gbuntu127, that's not a comment, it's a docstring. Although both can be used to describe what a unit of code does, they are syntactically different things. Docstrings are string literals.

The current behavior seems correct to me.

**Comment by gbuntu127** [comment]
Got it, I will turn off suggestions for "string" then, thanks!
