### ISSUE TITLE
Add 'debugger' as a parameter for 'workbench.action.debug.selectandstart'

### ISSUE THREAD

**Issue by WardenGnaw** [microsoft/vscode#185167]
Running `vscode.command.executeCommand('workbench.action.debug.selectandstart')` will prompt the `Debug: Select and Start Debugging` dialog and prompt for all dynamic configuration debuggers. 
![image](https://github.com/microsoft/vscode/assets/3953714/6cbd42ab-a111-45b5-8258-4eba37a6da50)

It will be helpful for extensions if we can run the command with an arg so it will call into a specific debugger's dynamic configuration provider. 

E.g. `vscode.command.executeCommand('workbench.action.debug.selectandstart', 'node')`
This just jump directly to 
![image](https://github.com/microsoft/vscode/assets/3953714/4cd1143f-b76d-436c-84fd-57a1a8011a26)

**Comment by rzhao271** [comment]
This works well if there's one launch config, but if there's multiple with the same type, it seems to go back to the view with all the options instead of filtering to that type.

**Comment by roblourens** [comment]
What do you mean by "multiple with the same type"? The first level is debuggers, not launch configs
