### ISSUE TITLE
The last line of a newly created file isn't highlighted by git difference 

### ISSUE THREAD

**Issue by kornatskyi** [microsoft/vscode#185140]
Type: <b>Bug</b>

Steps to Reproduce:
Setup: Git repository opened in VScode
1. Create a new file (.txt, .feature, etc)
2. Add several lines of text to the file
3. Go to Source Control tab to see files changes
4. Slect the newly created file to see the difference
Observe: All lines are highlighted(with green diff color) except the last one
If you add only 1 line to the file, you won't see any highlighting in the diff mode
![image](https://github.com/microsoft/vscode/assets/62629228/bf358710-c172-4889-a98e-b9872d996ab3)

Expected behavior: All lines in the newly created file should be hightlighted

This happens after the updated  to v1.79 or maybe v1.79.1

I was able to reproduce the same behavior in GitHub Codespaces and VScode Insider

VScode version: v1.79.1 (user setup)
OS: Windows 11 Home 64-bit operating system, x64-based processor

VS Code version: Code 1.79.1 (4cb974a7aed77a74c7813bdccd99ee0d04901215, 2023-06-12T16:14:05.102Z)
OS version: Windows_NT x64 10.0.22621
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.91GB (7.82GB free)|
|Process Argv|--crash-reporter-id 3b902c6f-515d-40e4-b624-2d1d2c5a0a50|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (74)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-javascript-snippet-pack|aka|0.1.6
increment-selection|alb|0.2.0
vscode-sqlite|ale|0.14.1
jsx-html-tags|ang|1.0.1
github-markdown-preview|bie|0.3.0
markdown-checkbox|bie|0.4.0
markdown-emoji|bie|0.3.0
markdown-footnotes|bie|0.1.1
markdown-mermaid|bie|1.18.1
markdown-preview-github-styles|bie|2.0.2
markdown-yaml-preamble|bie|0.1.0
turbo-console-log|Cha|2.9.3
npm-intellisense|chr|1.4.4
doxdocgen|csc|1.4.0
vscode-mysql-client2|cwe|6.5.2
javascript-ejs-support|Dig|1.3.3
python-preview|don|0.0.4
githistory|don|0.6.20
python-environment-manager|don|1.0.4
python-extension-pack|don|1.7.0
gitlens|eam|13.6.0
vscode-html-css|ecm|1.13.1
auto-close-tag|for|0.5.14
auto-complete-tag|for|0.1.0
auto-rename-tag|for|0.1.10
shell-format|fox|7.2.5
vscode-pull-request-github|Git|0.66.1
gc-excelviewer|Gra|4.2.57
vscode-drawio|hed|1.6.6
vscode-htmlhint|HTM|1.0.5
output-colorizer|IBM|0.1.2
vscode-env|Iro|0.1.0
svg|joc|1.5.2
markdown-table-formatter|jos|0.3.0
env-autocomplete|jpr|1.4.1
vscode-colorize|kam|0.11.1
vsc-python-indent|Kev|1.18.0
bash-ide-vscode|mad|1.37.0
MagicPython|mag|1.1.0
rainbow-csv|mec|3.7.0
python-path|mge|0.0.14
git-graph|mhu|1.30.0
file-downloader|min|1.0.12
autopep8|ms-|2023.4.0
black-formatter|ms-|2023.2.0
isort|ms-|2022.8.0
python|ms-|2023.10.1
vscode-pylance|ms-|2023.6.10
jupyter|ms-|2023.5.1001582324
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.15
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-slideshow|ms-|0.1.5
vscode-typescript-next|ms-|5.2.20230613
autodocstring|njp|0.6.1
vscode-python-typehint|njq|1.5.1
inline-html|pus|0.3.8
vscode-thunder-client|ran|2.7.6
vscode-xml|red|0.25.0
vscode-yaml|red|1.13.0
vs-code-prettier-eslint|rve|5.1.0
vscode-javascript-booster|sbu|14.0.1
markdown-preview-enhanced|shd|0.6.8
autoimport|ste|1.5.4
markdowntable|Tak|0.10.4
pdf|tom|1.2.2
python-extended-snippets|tus|0.0.1
vscode-icons|vsc|12.4.0
vscode-import-cost|wix|3.3.0
autocomplete-english-word|wus|0.1.7
JavaScriptSnippets|xab|1.8.0
txt-syntax|xsh|0.2.2
vscode-yseopml|Yse|1.16.0
json|Zai|2.0.2

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vstes516:30244333
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
2e4cg342:30602488
pyind779:30671433
89544117:30613380
pythonsymbol12:30671437
showlangstatbar:30737416
vsctsb:30748421
pythonms35:30701012
03d35959:30757346
57b77579:30736110
pythonfmttext:30731395
pythoncmvfstrcf:30756944
fixhidewlkth:30730051
hideindicator:30766889
pythongtdpath:30739704
bgfeh915:30763804
dh2dc718:30763024
pythonnosm12tcf:30765602

```

</details>

**Comment by hediet** [comment]
Thanks for reporting! This broke [here](https://github.com/microsoft/vscode/compare/8242d2080384095ab40ee36b1f0a6821cb278e0c...eef30e7165e19b33daa1e15e92fa34ff4a5df0d3).
