### ISSUE TITLE
Syntax coloring behavior folllowing <<EOF in bash

### ISSUE THREAD

**Issue by Arcahub** [microsoft/vscode#185119]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version:  1.79.1
- OS Version: Linux x64 5.19.0-38-generic

Following #177977 I still got some syntax error with `cat<<EOF` syntax in bash files

Steps to Reproduce:

The behavior change depending if you write:

```bash
#!/usr/bin/env bash

cat <<EOF | sudo tee myfile
{
    "jsonObject": {
        "key1": "value1",
        "key2": "value2"
    }
}
EOF
```
![image](https://github.com/microsoft/vscode/assets/57360508/d841f5c7-ab93-4c9c-a541-3c7457345f26)

Or (simply remove the space between cat and <<EOF and this is a valid syntax):
```bash
#!/usr/bin/env bash

cat<<EOF | sudo tee myfile
{
    "jsonObject": {
        "key1": "value1",
        "key2": "value2"
    }
}
EOF
```
![image](https://github.com/microsoft/vscode/assets/57360508/8b9efc74-e391-42b7-bf4e-6a588196bf5b)

The expected behavior for me is:
- The context should be display as a pure string between the EOF mark and it is done well in the first exemple but not in the second.
- Depending on what is comming after `cat<<EOF` either a pipe or a redirect it should adapt the syntax color for command or string, it is well done in the second example but not in the first
- On previous version of vscode the EOF mark had special syntax differencing them from the rest of the text and I think it was a good things

There is some good things on both behavior but neither is perfect from my point of vue and it still make syntax coloring inconsistent.

**Comment by alexr00** [comment]
Thank you for the example and for the screenshots. I have copied the issue over to https://github.com/jeff-hykin/better-shell-syntax/issues/61, which is the repo that we pull our shellscript syntax highlighting grammar from.
