### ISSUE TITLE
VSCode can't find the referenced script variable

### ISSUE THREAD

**Issue by gackt2** [microsoft/vscode#185166]
**Update** ---- somehow vs code fixed itself after I reloaded C# Dev Kit -- pls close. Will report back if error pops up again

Type: <b>Bug</b>

For Unity 2021.3.24

Current: C# scripts cannot find their referenced scripts via variables. I get 73 errors all related to C# Dev Kit.
**2023-06-14 17:15:13.196 [error] Failed to load project 'd:\ProjectY\Assembly-CSharp.csproj'. One or more errors occurred. (This project is not supported in C# Dev Kit.)**

On VS Community I can regenerate my project files and then the referenced scripts can be found. 

There's no such option in Unity for VSCode unfortunately

VS Code version: Code 1.79.1 (4cb974a7aed77a74c7813bdccd99ee0d04901215, 2023-06-12T16:14:05.102Z)
OS version: Windows_NT x64 10.0.19045
Modes:
 
Extension|Author (truncated)|Version
---|---|---
unity-code-snippets|kle|1.3.0
csharp|ms-|2.0.212
vscode-dotnet-runtime|ms-|1.6.0
unity-tools|Tob|1.2.12
unity-debug|Uni|3.0.2
unity-snippets|Ycl|0.1.2

(2 theme extensions excluded)

</details>

**Comment by roblourens** [comment]
Please file on the C# dev kit extension repo
