### ISSUE TITLE
Right click menu not working

### ISSUE THREAD

**Issue by SujithManjavana** [microsoft/vscode#185141]
Type: <b>Bug</b>

I am currently utilizing VS Code on Mint Linux and I have encountered an issue that I would greatly appreciate your assistance with.

The problem occurs when I have two VS Code windows open simultaneously. In the second window, I am unable to access the top menus and right-click menu. Whenever I attempt to right-click, the menu briefly appears but then disappears immediately, making it impossible to utilize the available options.

VS Code version: Code 1.79.1 (4cb974a7aed77a74c7813bdccd99ee0d04901215, 2023-06-12T16:17:13.990Z)
OS version: Linux x64 5.15.0-73-generic
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i5-11320H @ 3.20GHz (8 x 3200)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|2, 1, 1|
|Memory (System)|15.41GB (4.28GB free)|
|Process Argv|--unity-launch --crash-reporter-id fa7cb9b3-b282-4da0-b7c1-a284d5152369|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|cinnamon|
|XDG_CURRENT_DESKTOP|X-Cinnamon|
|XDG_SESSION_DESKTOP|cinnamon|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (21)</summary>

Extension|Author (truncated)|Version
---|---|---
rtf|ale|2.7.0
simple-react-snippets|bur|1.2.7
prettier-vscode|esb|9.13.0
live-sass|gle|6.0.5
rest-client|hum|0.25.1
vscode-language-babel|mgm|0.0.39
vscode-docker|ms-|1.25.1
python|ms-|2023.10.1
vscode-pylance|ms-|2023.6.10
jupyter|ms-|2023.5.1001582324
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.15
cpptools|ms-|1.15.4
vscode-react-native|msj|1.11.0
deepdark-material|Nim|3.3.0
indent-rainbow|ode|8.3.1
LiveServer|rit|5.7.9
nativeemmet|Sau|0.0.8
html5-boilerplate|sid|1.1.1
lorem-ipsum|Tyr|1.3.1
vscode-icons|vsc|12.4.0

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
3biah626:30602489
pyind779:30671433
f6dab269:30613381
pythonsymbol12:30671437
showlangstatbar:30737416
vsctsb:30748421
pythonms35:30701012
03d35959:30757346
pythonfmttext:30731395
pythoncmv:30756943
fixhidewlkth:30730051
pythongtdpathcf:30739705
e440d664:30763025
pythonnosm12tcf:30765602

```

</details>

**Comment by bellomimarc** [comment]
Thanks @SujithManjavana, I never notifce that this happen when multiple vs code are open.
It happens to me too! 
https://github.com/microsoft/vscode/issues/185161

**Comment by SujithManjavana** [comment]
Any fix available?

**Comment by bellomimarc** [comment]
I add an additional info:
- open one instance of vs code, it works
- open second instance of vs code, it does not work
- close one of the two instances, it does not work
- close all instances
- one one instance again, it works

**Comment by sbatten** [comment]
@deepak1556  native menus on linux

**Comment by deepak1556** [comment]
We recently had some improvements to native and custom context menu, can you please check if the issue is present with latest insiders https://code.visualstudio.com/insiders
