### ISSUE TITLE
html pages not loading

### ISSUE THREAD

**Issue by zashy11** [microsoft/vscode#185149]
Type: <b>Bug</b>

I've been using VS code for several months now and enjoy the user experience. Howver, today, none of my html files are loading on my chrome browser. I use live server. I've tried restarting and even updating my VS code. I even tried to open in an incognito browser. Nothing is working. please how do i resolve this?

VS Code version: Code 1.79.1 (4cb974a7aed77a74c7813bdccd99ee0d04901215, 2023-06-12T16:17:13.990Z)
OS version: Linux x64 5.15.103-17409-g07029265d738
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) m3-8100Y CPU @ 1.10GHz (4 x 1608)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|1, 1, 1|
|Memory (System)|2.72GB (0.63GB free)|
|Process Argv|--unity-launch --crash-reporter-id a86725bc-8a7b-478c-87c8-2573bd8cc3f2|
|Screen Reader|no|
|VM|100%|
|DESKTOP_SESSION|undefined|
|XDG_CURRENT_DESKTOP|X-Generic|
|XDG_SESSION_DESKTOP|undefined|
|XDG_SESSION_TYPE|undefined|
</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
vsc-material-theme|Equ|33.8.0
vsc-material-theme-icons|equ|2.8.0
LiveServer|rit|5.7.9
code-spell-checker|str|2.20.5

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
vscaat:30438848
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
3biah626:30602489
pyind779:30671433
89544117:30613380
pythonsymbol12:30671437
showlangstatbar:30737416
vsctsb:30748421
pythonms35:30701012
03d35959:30757346
pythonfmttext:30731395
pythoncmvfstrcf:30756944
fixshowwlkth:30730052
pythongtdpathcf:30739705
dh2dc718:30763024
pythonnosmt12:30765603

```

</details>

**Comment by aeschli** [comment]
Sounds like an issue of the live server. Can you file against the live server extension that you use?
https://github.com/ritwickdey/vscode-live-server/issues
