### ISSUE TITLE
Allow to map a filename to a language based on a prefix

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#1851]
In addition to the extname (`*.es6`), the full name (`Dockerfile`), and the first line content (`#! /user/bin/node`) we should also allow to map a file to a language based on a prefix, like `Dockerfile-dev` maps because of `Dockerfile*`.

**Comment by jrieken** [comment]
@PeterJausovec, @SteveLasker fyi

**Comment by matthewp** [comment]
What do you mean by prefix? I'd like to be able to map file extensions to a language, ie map `.foo` to `HTML`.

**Comment by egamma** [comment]
@matthewp this is another issue #334, let's keep these issues separate.
