### ISSUE TITLE
Code crashes three times at startup

### ISSUE THREAD

**Issue by fatman45** [microsoft/vscode#185174]
Type: <b>Bug</b>

Start Code, with or without extensions. Wait approximately 20 seconds; screen will flicker, each pane separately. Wait approximately 20 seconds more; repeat of last crash. Wait approximately 20 seconds more; repeat of last crash. At this point, I can continue using Code for hours with no issues. Curiously, Microsoft Edge browser for Linux exhibits the exact same behavior - three crashes approximately 20 seconds apart, then everything is fine for hours. 

Here are pastebins of the crash reports.

https://termbin.com/774w
https://termbin.com/ryg7d
https://termbin.com/3qfc

VS Code version: Code 1.79.1 (4cb974a7aed77a74c7813bdccd99ee0d04901215, 2023-06-12T16:17:13.990Z)
OS version: Linux x64 5.15.0-73-generic
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 1700X Eight-Core Processor (16 x 2200)|
|GPU Status|2d_canvas: unavailable_software<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>opengl: disabled_off<br>rasterization: disabled_software<br>raw_draw: disabled_off_ok<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software<br>webgpu: disabled_off|
|Load (avg)|0, 0, 0|
|Memory (System)|31.26GB (27.99GB free)|
|Process Argv|--disable-extensions --crash-reporter-id 47cd3433-4bce-411d-b540-9b27ade1c499|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|mate|
|XDG_CURRENT_DESKTOP|MATE|
|XDG_SESSION_DESKTOP|mate|
|XDG_SESSION_TYPE|x11|
</details>Extensions disabled<details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
vsccc:30610678
2e4cg342:30602488
pyind779:30671433
f6dab269:30613381
pythonsymbol12:30671437
2i9eh265:30646982
showlangstatbar:30737416
vsctsb:30748421
pythonms35:30701012
03d35959:30757346
pythonfmttext:30731395
pythoncmvfstrcf:30756944
fixhidewlkth:30730051
pythongtdpath:30739704
i26e3531:30763805
dh2dc718:30763024
pythonnosmt12:30765603

```

</details>

**Comment by rzhao271** [comment]
Hi, thanks for the crash reports!

Unfortunately, we aren't able to symbolicate them. Could you send us a zip of some dmp files following the [creating a crash report](https://github.com/microsoft/vscode/wiki/Native-Crash-Issues#creating-a-crash-report) instructions?

Also, could you run the "Help: About" command and paste the output into this issue? That way, we can quickly identify which Electron symbols to use to symbolicate the files.

**Comment by fatman45** [comment]
@rzhao271 Attaching the dumps here. And this is the output from Help | About.

`Version: 1.79.2
Commit: 695af097c7bd098fbf017ce3ac85e09bbc5dda06
Date: 2023-06-14T08:59:55.818Z
Electron: 22.5.7
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Linux x64 5.15.0-73-generic`

[code_dumps.zip](https://github.com/microsoft/vscode/files/11764853/code_dumps.zip)

@deepak1556 Yes, the GPU and/or drivers was my thought also. This entire system is a new install of Linux, so yes, the drivers are also new. I noticed in the Crash report this command line:

`Command Line: $'/usr/share/code/code --type=gpu-process --crashpad-handler-pid=28951 --enable-crash-reporter=92be6071-f5a7-4852-87a0-b70ac18ac357,no_channel --user-data-dir=/home/ron/.config/Code --gpu-preferences=WAAAAAAAAAAgAAAIAAAAAAAAAAAAAAAAAABgAAAAAAA4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAIAAAAAAAAAABAAAAAAAAAAgAAAAAAAAACAAAAAAAAAAIAAAAAAAAAA== --shared-files --field-trial-handle=0,i,8301173418809640930,2175803506988919068,131072 --disable-features=CalculateNativeWinOcclusion,SpareRendererForSitePerProcess'
`
The --gpu-preferences option, what is that Base64 encoded value? Is it for some generic GPU? I tried to find help on that option, but had no luck.

**Comment by rzhao271** [comment]
Thanks for the info! I've symbolicated the files. The call stack is different in each case.

[symbolicated-47.log](https://github.com/microsoft/vscode/files/11790211/symbolicated-47.log)
[symbolicated-a3.log](https://github.com/microsoft/vscode/files/11790212/symbolicated-a3.log)
[symbolicated-f3.log](https://github.com/microsoft/vscode/files/11790213/symbolicated-f3.log)

**Comment by deepak1556** [comment]
@fatman45 do you ESET anti-virus installed ? Based on the stack the gpu sandbox is killing the process due to seccomp violations and seem like it is a known issue in upstream https://bugs.chromium.org/p/chromium/issues/detail?id=1040117#c8. I suggest to either ignore VSCode executable from the AV or run with sandbox disabled using `--no-sandbox --disable-gpu-sandbox`

**Comment by fatman45** [comment]
@deepak1556 yes, I do have ESET antivirus installed. I will try disabling it and see if the issue persists. BTW, if I use `--disable-gpu` then I do not experience the issue.

**Comment by fatman45** [comment]
Thank you all, uninstalling ESET cured the issue, with Edge, also. As ESET is no longer maintaining their Linux code base, I will find a different antivirus. I'm going to close this issue now.
