### ISSUE TITLE
May I strongly suggest that the setup for the basic program direct the installer to look at the Color Themes before anything else.  The default screen is almost unreadably dark and low contrast.  Some of the optional Color Themes are just great and very easy to read

### ISSUE THREAD

**Issue by Sub568** [Microsoft/vscode#18515]
**-** VSCode Version: Code 1.8.1 (ee428b0eead68bf0fb99ab5fdc4439be227b6281, 2016-12-19T14:49:23.350Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

|Extension|Author|Version|
|---|---|---|
|python|donjayamanne|0.5.5|
|MagicPython|magicstack|1.0.3|
|theme-mild|radub|0.1.3|
|view-in-default-application|seesharprun|2.0.0|
|JavaScriptSnippets|xabikos|1.2.0|

---

Steps to Reproduce:

1.
2.

**Comment by mjbvz** [comment]
@chrmarti Selecting an initial theme sounds like it would fall into the welcome experience.

**Comment by chrmarti** [comment]
@Sub568 Could you attach a screenshot? I would like to understand which parts of the UI are unreadable.

**Comment by Sub568** [comment]
Hi
Here is a screenshot of a video lesson and one of a recent assignment worked on VS Code in the Light+ color theme.  The difference is striking.  I think that the process of transferring the lessons to U tube sacrifices a lot of clarity for speed of download.

On 1/13/2017 2:45 PM, chrmarti wrote:

@Sub568<https://github.com/Sub568> Could you attach a screenshot? I would like to understand which parts of the UI are unreadable.

**Comment by chrmarti** [comment]
I think you need to attach it in GitHub directly. The attachment hasn't made it through from the email.

**Comment by Sub568** [comment]
I've not done this before
![light color theme](https://cloud.githubusercontent.com/assets/7491922/21954793/fcfd5104-da29-11e6-88e6-ee8955aa33f7.JPG)
![html lesson](https://cloud.githubusercontent.com/assets/7491922/21954794/fd0b5254-da29-11e6-8fc6-9fa2ab9481ca.JPG)

**Comment by chrmarti** [comment]
Thanks. The screenshots look as designed. We are working on making it easier for new users to pick a different color theme as part of #18091. Marking as duplicate of that.
