### ISSUE TITLE
Cannot save "$server"

### ISSUE THREAD

**Issue by MichaelGosselin** [microsoft/vscode#185160]
Type: <b>Bug</b>

I tried to enter a new server in VS Code. I entered the information requested, and received a message: 

Failed to store server '$(name)' definition.

I've tried several times and this has not worked.

VS Code version: Code 1.79.1 (4cb974a7aed77a74c7813bdccd99ee0d04901215, 2023-06-12T16:14:05.102Z)
OS version: Windows_NT x64 10.0.19044
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 PRO 4650U with Radeon Graphics (12 x 2096)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|23.23GB (13.09GB free)|
|Process Argv|--crash-reporter-id 2daa83e1-0fc8-41d1-9b66-471370eca25b|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
objectscript-pack|int|1.0.3
servermanager|int|3.2.2
vscode-objectscript|int|2.8.1
language-server|int|2.3.5
vscode-docker|ms-|1.25.1
remote-wsl|ms-|0.79.5

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
3biah626:30602489
pyind779:30671433
89544117:30613380
pythonsymbol12:30671437
2i9eh265:30646982
showlangstatbar:30737416
vsctsb:30748421
pythonms35:30701012
03d35959:30757346
pythonfmttext:30731395
pythoncmv:30756943
fixhidewlkth:30730051
hideindicator:30766889
pythongtdpathcf:30739705
e440d664:30763025
pythonnosm12tcf:30765602

```

</details>

**Comment by roblourens** [comment]
> I tried to enter a new server in VS Code

Please give more details, I don't know what you're referring to

**Comment by MichaelGosselin** [comment]
OKay, let's try this again.

I open VS Code. Then, I click on "Intersystems Tools", which is what I will be using. At the top, there is a "+" symbol, so I click that. I enter all the server information, and when I finish, it gives the message "Cannot save '$server(name').

It turns out that my settings file had an extra "}" in it, so whatever I tried, it wasn't formed correctly.

You might want to document this, 

I think you can also close this. Thanks.

**Comment by roblourens** [comment]
I don't know what "Intersystems Tools" is, this sounds like an issue with an extension

**Comment by MichaelGosselin** [comment]
Yes; it was an issue with the extension.

Michael Gosselin
Contract Cache Developer

Quest Diagnostics | Action from Insight | 200 Forest Street | Marlborough, MA 01752 USA | ***@***.******@***.***> | AthenaDiagnostics.com<http://athenadiagnostics.com/>
***@***.***
This communication and any files transmitted with it may contain information that is confidential, privileged and exempt from disclosure under applicable law. This message is intended only for the use of the addressee and may contain information that is protected by the HIPAA Privacy Rule, 45 CFR § 164.500. It is intended solely for the use of the individual or entity to which it is addressed. If you are not the intended recipient, you are hereby notified that any use, dissemination or copying of this communication is strictly prohibited. If you have received this communication in error, please notify the sender. Athena Diagnostics does not accept credit card payments via email or fax.

Thank you for your cooperation.
