### ISSUE TITLE
Debug Console should accept Enter key to insert suggestion, not just Tab

### ISSUE THREAD

**Issue by jedwards1211** [microsoft/vscode#185152]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.79.1
- OS Version: macOS

Steps to Reproduce:

1. Debug a program
2. Type something in the debug console that triggers the autocomplete popup
3. Press enter

Right now enter always submits the statement to be evaluated, and the popup says to press `Tab` to insert.  But I constantly press `Enter` out of habit because it works in editors.  This gets really annoying...it inevitably errors out and I have to press up and retype.

The autocomplete should behave just like in the editor, it should take over the `Enter` keybinding while it's open.

**Comment by yannickowow** [comment]
Hello,
A setting already exists for Debug Suggestion, see:

Debug › Console: Accept Suggestion On Enter
Controls whether suggestions should be accepted on Enter in the Debug Console. Enter is also used to evaluate whatever is typed in the Debug Console.

By default, it is off

**Comment by jedwards1211** [comment]
@yannickowow ah okay.

So Editor: Accept Suggestion On Enter is on by default...
Shouldn't those defaults match?

**Comment by yannickowow** [comment]
Not sure if they should match since they are targetting two different kind of features. 
One is dedicated to Debug, and the other one to IntelliSense.
