### ISSUE TITLE
Mixed keyboard menu shortcuts

### ISSUE THREAD

**Issue by kumarharsh** [Microsoft/vscode#18513]
- VSCode Version: 1.9.0-insider (2cdc2b)
- OS Version: Win 10

Steps to Reproduce:

1. Change keyboard to some other language (mine became Hindi)
2. Some, *and only some*, shortcuts now come with the new keyboard's characters. See below

![image](https://cloud.githubusercontent.com/assets/760112/21931255/819f0fe8-d9c0-11e6-92ad-6c4119984451.png)

![image](https://cloud.githubusercontent.com/assets/760112/21931303/c9c070c8-d9c0-11e6-896b-3e668dfd9850.png)

**Comment by alexandrudima** [comment]
Yes, non alpha-numeric keybindings show the produced character in the menu on Windows.

This is expected.
