### ISSUE TITLE
Suggest widget accepts hidden suggestions when opening parenthesis

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#18510]
I type `.branch`, which doesn't exist as a suggestion. As I press `(`, the `branch` is replaced with `checkout`.

![bug](https://cloud.githubusercontent.com/assets/22350/21926867/f2cc510e-d983-11e6-9d55-293c137e8c35.gif)

**Comment by jrieken** [comment]
Nice catch. It seems that the commit character is still being honoured...
