### ISSUE TITLE
Unable to deploy function app (python) to Azure

### ISSUE THREAD

**Issue by AICowboy** [microsoft/vscode#185136]
Type: <b>Bug</b>

Replication steps:
1. Select the Azure tab to see Azure resources (remote) and workspace (local) objects
2. Select the "Deploy..." icon next in the workspace section
3. Select the subscription and Azure function app as prompted
OR
2. Expand the function app context under resources
3. Right-click on appropriate function app and select "Deploy to Function App..."

I get the following the output context for Azure Functions:
"9:02:09 AM azcvsecspdfuncweathersnd: Starting deployment...
9:02:09 AM azcvsecspdfuncweathersnd: Creating zip package..."

A popup states 'Deploying to "azcvsecspdfuncweathersnd"... Check [output window](command:azureFunctions.showOutputChannel) for status.' and the function app working icon appears but nothing ever happens.  No other log messages that I am aware of.

VS Code version: Code 1.79.1 (4cb974a7aed77a74c7813bdccd99ee0d04901215, 2023-06-12T16:14:05.102Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz (8 x 2419)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.69GB (4.99GB free)|
|Process Argv|--crash-reporter-id a2843ee6-87bd-4012-b312-64b6b49a75d3|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (22)</summary>

Extension|Author (truncated)|Version
---|---|---
azure-dev|ms-|0.6.0
vscode-azureappservice|ms-|0.24.9
vscode-azurecontainerapps|ms-|0.5.1
vscode-azurefunctions|ms-|1.11.0
vscode-azureresourcegroups|ms-|0.7.5
vscode-azurestaticwebapps|ms-|0.12.1
vscode-azurestorage|ms-|0.15.3
vscode-azurevirtualmachines|ms-|0.6.5
vscode-cosmosdb|ms-|0.19.4
csharp|ms-|1.25.9
vscode-dotnet-runtime|ms-|1.6.0
python|ms-|2023.10.1
vscode-pylance|ms-|2023.6.10
jupyter|ms-|2023.5.1001582324
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.15
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-slideshow|ms-|0.1.5
azure-account|ms-|0.11.5
powershell|ms-|2023.6.0
vscode-node-azure-pack|ms-|1.2.0
azurerm-vscode-tools|msa|0.15.10

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263:30335439
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
3biah626:30602489
pyind779:30671433
f6dab269:30613381
pythonsymbol12:30671437
showlangstatbar:30737416
vsctsb:30748421
pythonms35:30701012
03d35959:30757346
pythonfmttext:30731395
pythoncmv:30756943
fixshowwlkth:30730052
pythongtdpathcf:30739705
bgfeh915:30763804
dh2dc718:30763024
pythonnosmt12:30765603

```

</details>

**Comment by AICowboy** [comment]
Additional information.  I found in the Azure Account output the following error:
Get Token request returned http error: 400 and server response: {"error":"interaction_required","error_description":"AADSTS50076: Due to a configuration change made by your administrator, or because you moved to a new location, you must use multi-factor authentication to access 'xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx'.\r\nTrace ID: 0b06c0f1-c1aa-4d21-8c31-d01aaa833100\r\nCorrelation ID: 05d711a9-4a31-419a-a252-d9516c0e4634\r\nTimestamp: 2023-06-14 20:13:59Z","error_codes":[50076],"timestamp":"2023-06-14 20:13:59Z","trace_id":"0b06c0f1-c1aa-4d21-8c31-d01aaa833100","correlation_id":"05d711a9-4a31-419a-a252-d9516c0e4634","error_uri":"https://login.microsoftonline.com/error?code=50076","suberror":"basic_action"}
2023-06-14 14:13:59.375 [error] Acquiring token with refresh token failed

**Comment by AICowboy** [comment]
Update 2:
I was able to login with another account which didn't require MFA but now only get a "spinning" icon and never deploys.

**Comment by roblourens** [comment]
Please file on the relevant extension's repo, thanks
