### ISSUE TITLE
Chat input widget is positioned wrong

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#185283]
I think this is supposed to be aligned with the code text

<img width="671" alt="image" src="https://github.com/microsoft/vscode/assets/323878/6e916284-fb79-4542-9779-3eecc1885aa7">

**Comment by aiday-mar** [comment]
Hi thanks @roblourens, this should be fixed by https://github.com/microsoft/vscode/pull/185209. Let me know if you continue seeing this error
