### ISSUE TITLE
codespace issue

### ISSUE THREAD

**Issue by papilloos** [microsoft/vscode#185214]
codespace seems to be having issue with remote connection if i am not wrong. Internet connection is very fast so i cant imagine whats wrong
Version: 1.80.0-insider
Commit: 6545c4c2671127c323182225963fcd732e1fbcc5
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36
Embedder: codespaces

**Comment by sandy081** [comment]
Please file the issue against Codespaces.
