### ISSUE TITLE
Have a search history

### ISSUE THREAD

**Issue by soljohnston777** [Microsoft/vscode#18528]
It is nice when you have a search history that pops up(down below the search field)  - with pressing the down arrow on your keyboard or just clicking the search area.  I haven't see this implemented in yet .

**Comment by mjbvz** [comment]
We do have a search history. You can brows through this using <kbd>alt</kbd><kbd>up</kbd> and <kbd>alt</kbd><kbd>down</kbd> while in the search text box. These are the `search.history.showNext` and search.history.showPrevious" commands

**Comment by soljohnston777** [comment]
Thanks for the hints. Why couldn't it be shown like a list ( for example like when using a form drop down list showing the last 5 entries).  That would be more intuitive.

**Comment by roblourens** [comment]
Related to https://github.com/Microsoft/vscode/issues/17492, problem is just that we're using the arrow keys to navigate between fields at the moment.
