### ISSUE TITLE
Feature request: Put open folder name first in window title (better for thumbnails)

### ISSUE THREAD

**Issue by indywill** [Microsoft/vscode#18526]
- VSCode Version: 1.8.1
- OS Version: Win 10 64-bit

# Overview: 
Having filename first (rather than folder) in window title bar title makes switching between multiple instances more difficult.

# Abstract: 
Like many developers, I usually have at least 2-3 (often many more) project folders (i.e. code instances) open at the same time, and switch between them. Currently, the window title for each instance is set as follows (at least in Windows version):
[file name] - [folder name] - Visual Studio Code

The problem is that one may be editing a file called 'settings.json' in multiple projects at the same time, making it difficult to quickly discern which tile or thumbnail represents which project when using alt-tab or windows taskbar hover tiles. And if the file name is very long, the folder name may not be visibile at all.

If the folder name were first, it would be much more immediately apparent which tile/thumbnail was which project instance.

# Concerns: 
While I believe that this would be a simple change programmatically, I must admit I have no idea how this would impact my friends on other platforms since I only use Windows. Perhaps someone familiar with the OSx or Linux versions could share their thoughts on this.

**Comment by mjbvz** [comment]
@bpasero Since you worked on #3119, can you please take a look at this?

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/1723
