### ISSUE TITLE
Crashing immediately on startup

### ISSUE THREAD

**Issue by ritch** [Microsoft/vscode#18521]
- VSCode Version:

```
Ω code -v
1.8.1
ee428b0eead68bf0fb99ab5fdc4439be227b6281
```

- OS Version:

```
Ω system_profiler SPSoftwareDataType
Software:

    System Software Overview:

      System Version: macOS 10.12.2 (16C68)
      Kernel Version: Darwin 16.3.0
```

Also might be worth noting that I have `git@1.8.4` on this machine.

aka Mac OS 10 Sierra

Steps to Reproduce:

1. download the latest `.app` from chrome
2. click on the downloaded zip icon (which uses ??? to unzip it)
3. move the unzipped `.app` to `Applications`
4. double click it
5. crashes immediately

Here is output of `--verbose`.

```sh
(master) Ω code -v
1.8.1
ee428b0eead68bf0fb99ab5fdc4439be227b6281
(master) Ω code --verbose
[main 7:12:16 AM] Sending env to running instance...
[main 7:12:16 AM] Sent env to running instance. Terminating...
```

Downgraded to 1.7 and ...

```sh
(master) Ω code -v
1.7.2
7ba55c5860b152d999dda59393ca3ebeb1b5c85f
(master) Ω code --verbose
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[main 7:14:40 AM] Sending env to running instance...
[main 7:14:40 AM] Sent env to running instance. Terminating...
```

Upgrading to 1.9.0-insider - and no more immediate crashing!

```sh
(master) Ω code-insiders -v
1.9.0-insider
2cdc2b3da8f0fd5322b48747241584cf9dd98f8f
(master) Ω code-insiders --verbose
[main 7:25:18 AM] Starting VS Code in verbose mode
[main 7:25:18 AM] from: /private/var/folders/b1/h9wy_qtd2ml588hrfcg2vtlh0000gn/T/AppTranslocation/B0B632EC-003B-4560-A274-8366DEE642D2/d/Visual Studio Code - Insiders.app/Contents/Resources/app
[main 7:25:18 AM] args: { _: [],
  help: false,
  h: false,
  version: false,
  v: false,
  wait: false,
  w: false,
  diff: false,
  d: false,
  goto: false,
  g: false,
  'new-window': false,
  n: false,
  'new-window-if-not-first': false,
  'reuse-window': false,
  r: false,
  performance: false,
  p: false,
  verbose: true,
  logExtensionHostCommunication: false,
  'disable-extensions': false,
  disableExtensions: false,
  'list-extensions': false,
  'show-versions': false,
  nolazy: false }
[main 7:25:20 AM] IPC#vscode-workbenchLoaded
# cut off for brevity
```

**Comment by mjbvz** [comment]
@ritch After trying to open vscode and it crashes, do you see any additional information? Is there a "Report Problem For Electron Window"?

#17034 had a similar error. Do any of the suggestions in that issue help?

**Comment by moe123** [comment]
```
 -	    kqueueop->events[0].flags != EV_ERROR) {
 +	    !(kqueueop->events[0].flags & EV_ERROR)) {
```
buzz here http://libevent.org

**Comment by bpasero** [comment]
@ritch so you say 1.9 insider works fine for you? are you using the macOS native zip tool for unzip?

**Comment by ritch** [comment]
> are you using the macOS native zip tool for unzip?

yes

**Comment by ritch** [comment]
> @ritch After trying to open vscode and it crashes, do you see any additional information? Is there a "Report Problem For Electron Window"?

no... just a very quick open of the app icon in the dock then it goes away... pretty odd.

**Comment by ritch** [comment]
After a restart I downloaded 1.8.1 recovery and it just opened without issue...

Would downloading a new build clear out my installed extensions?

I think the zombie process think is worth looking into, because it would explain this workaround.

**Comment by bpasero** [comment]
Yeah, very likely to be zombie process related. Happy to hear it works again.
