### ISSUE TITLE
OSX - Chrome - All links broken on home page: https://code.visualstudio.com

### ISSUE THREAD

**Issue by jmlivingston** [Microsoft/vscode#1852]
I am unable to navigate to any of the links (Docs, Extensions, FAQ, etc.) on Google Chrome on OS X. Any link that is clicked is redirected to the home page. 

The links work perfectly fine on Safari and Chrome on Windows.

Here is the URL it redirects me to. Perhaps a Google Analytics integration issue?

https://code.visualstudio.com/Home/IndexB?utm_expid=101350005-9._kM5PDapS5KdYQ0OiWM-yQ.1

**Comment by joaomoreno** [comment]
I can't reproduce. Can you clear your browser history, cache, etc?

**Comment by jmlivingston** [comment]
My bad, should have thought of that first. Verified in In Cognito mode, so I'm sure it works fine.
