### ISSUE TITLE
Can't initialize github repository

### ISSUE THREAD

**Issue by olivDiogo** [microsoft/vscode#185275]
Type: <b>Bug</b>

Go to 'Source control' and click 'Initialize Repository'.
An error message shows "Git:unknown switch 'b'".

VS Code version: Code 1.79.2 (695af097c7bd098fbf017ce3ac85e09bbc5dda06, 2023-06-14T08:57:04.379Z)
OS version: Windows_NT x64 10.0.22621
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2208)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.85GB (6.84GB free)|
|Process Argv|--crash-reporter-id 3fdd78d1-d12f-4ce8-957e-608a5064ed16|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
LiveServer|rit|5.7.9

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
2e4cg342:30602488
pyind779:30671433
89544117:30613380
pythonsymbol12:30671437
2i9eh265:30646982
showlangstatbar:30737416
vsctsb:30748421
pythonms35:30701012
03d35959:30757346
pythonfmttext:30731395
pythoncmvfstrcf:30756944
fixshowwlkth:30730052
pythongtdpathcf:30739705
dh2dc718:30763024
pythonidxptcf:30768922

```

</details>

**Comment by Webtwine** [comment]
Having the same issues after a recent update this morning. 

Version: 1.79.2
Date: 2023-06-14T08:58:52.392Z (1 day ago)
Electron: 22.5.7
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Darwin x64 22.5.0

**Comment by Prefsmaster** [comment]
I encountered the same issue....
Output from GIT:

2023-06-16 10:31:06.946 [info] > git init -b main [4ms]
2023-06-16 10:31:06.946 [info] error: unknown switch `b'
usage: git init [-q | --quiet] [--bare] [--template=<template-directory>] [--shared[=<permissions>]] [<directory>]

    --template <template-directory>
                          directory from which templates will be used
    --bare                create a bare repository
    --shared[=<permissions>]
                          specify that the git repository is to be shared amongst several users
    -q, --quiet           be quiet
    --separate-git-dir <gitdir>
                          separate git dir from working tree
2023-06-16 10:33:13.422 [info] > git rev-parse --show-toplevel [1ms]
2023-06-16 10:33:13.422 [info] fatal: not a git repository (or any of the parent directories): .git

**Comment by Webtwine** [comment]
> I encountered the same issue.... Output from GIT:
> 
> 2023-06-16 10:31:06.946 [info] > git init -b main [4ms] 2023-06-16 10:31:06.946 [info] error: unknown switch `b' usage: git init [-q | --quiet] [--bare] [--template=] [--shared[=]] []
> 
> ```
> --template <template-directory>
>                       directory from which templates will be used
> --bare                create a bare repository
> --shared[=<permissions>]
>                       specify that the git repository is to be shared amongst several users
> -q, --quiet           be quiet
> --separate-git-dir <gitdir>
>                       separate git dir from working tree
> ```
> 
> 2023-06-16 10:33:13.422 [info] > git rev-parse --show-toplevel [1ms] 2023-06-16 10:33:13.422 [info] fatal: not a git repository (or any of the parent directories): .git

Yes, that the exact same Output received.

**Comment by lszomoru** [comment]
Could you please share the version of git that you are using? Thank you!

**Comment by olivDiogo** [comment]
[image: image.png]

Ladislau Szomoru ***@***.***> escreveu no dia sexta,
16/06/2023 à(s) 16:14:

**Comment by olivDiogo** [comment]
![Git version](https://github.com/microsoft/vscode/assets/130308508/66ad7973-5582-49c1-af39-d914dd1a51b9)
