### ISSUE TITLE
generate type fix does not work

### ISSUE THREAD

**Issue by five70apps** [Microsoft/vscode#18525]
- VSCode Version: Code 1.8.1 (ee428b0eead68bf0fb99ab5fdc4439be227b6281, 2016-12-19T14:49:23.350Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

|Extension|Author|Version|
|---|---|---|
|csharp|ms-vscode|1.6.2|

---

Steps to Reproduce:

1. In VSCode, new csharp project, edit a .cs file
2. write some code referencing a non-existent type; the name of the non-existent type (SimpleLinkedList, for example) will be underlined with a red squiggly line
3. with the cursor on the line of code containing the non-existent type, click on the light bulb for fixes shows that shows up in the gutter
4. click on "generate type 'SimpleLinkedList'"
5. nothing happens (it should generate the type but it doesn't)
![untitled](https://cloud.githubusercontent.com/assets/4247685/21941669/e1e1f61e-d997-11e6-870a-b18a6366a056.png)

Note: "generate method", "remove unnecessary usings" work as expected

**Comment by mjbvz** [comment]
This issue was moved to OmniSharp/omnisharp-vscode#1119
