### ISSUE TITLE
Code does a NotifyChangeDirectory operation on the file's parent directory, causing WinSCP's "keep remote diretory up-to-date" to upload the entire directory on every save.

### ISSUE THREAD

**Issue by Aven-dev** [microsoft/vscode#185240]
Type: <b>Bug</b>

1) Open a file that is inside of a directory in a workspace. The directory should also have (many) other files.
2) Open WinSCP and use the "Keep remote directory up to date" functionality with the option "Update subdirectories" enabled.
3) Save the file in Code.
4) Observe how the entire directory gets uploaded.

The NotifyChangeDirectory operation Code does can be observed with Process Monitor.

VS Code version: Code 1.79.1 (4cb974a7aed77a74c7813bdccd99ee0d04901215, 2023-06-12T16:14:05.102Z)
OS version: Windows_NT x64 10.0.19045
Modes:

**Comment by bpasero** [comment]
We use node.js for all file operations so I suggest you report this issue to: https://github.com/nodejs/node
