### ISSUE TITLE
I can't do a Find in Files search

### ISSUE THREAD

**Issue by igiliev** [microsoft/vscode#185238]
Type: <b>Bug</b>

When I try finding something in the files of my project with ctrl + shift + f I am getting the following error:  A system error occured (spawn UNKNOWN) it was working normally, but after the last vscode update I think this error started showing

VS Code version: Code 1.79.1 (4cb974a7aed77a74c7813bdccd99ee0d04901215, 2023-06-12T16:14:05.102Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz (8 x 1382)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.41GB (2.76GB free)|
|Process Argv|--crash-reporter-id 392a0fc1-120d-4404-83e3-fefa13c95ec2|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|16.0.0
vscode-tailwindcss|bra|0.9.11
simple-react-snippets|bur|1.2.7
githistory|don|0.6.20
prettier-vscode|esb|9.13.0
Angular2|joh|13.0.0
mongodb-vscode|mon|1.0.1
vscode-typescript-next|ms-|5.2.20230614
html5-boilerplate|sid|1.1.1
vscode-styled-components|sty|1.7.8

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
vscaac:30438847
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
vsccc:30610678
2e4cg342:30602488
pyind779:30671433
f6dab269:30613381
pythonsymbol12:30671437
showlangstatbar:30737416
vsctsb:30748421
pythonms35:30701012
03d35959:30757346
pythonfmttext:30731395
pythoncmv:30756943
fixhidewlkth:30730051
pythongtdpathcf:30739705
dh2dc718:30763024
pythonnosmt12:30765603

```

</details>

**Comment by andreamah** [comment]
If you disable all extensions, does this still happen?
