### ISSUE TITLE
TypeScript go to implementation goes to correct file but wrong cursor position

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#18524]
Go to ITerminalConfigHelper:

![image](https://cloud.githubusercontent.com/assets/2193314/21940233/3db51630-d978-11e6-9b49-c7b81152636b.png)

Go to ITerminalService:

![image](https://cloud.githubusercontent.com/assets/2193314/21940239/449ad502-d978-11e6-8971-f70ab3e71ffb.png)

**Comment by mjbvz** [comment]
Confirmed. This appears to be a TypeScript bug. Here's the TSServer communications:

```
]
[Trace - 1:31:38 PM] Sending request: implementation (521). Response expected: yes. Current queue length: 0
Arguments: {
    "file": "/Users/matb/projects/vscode/src/vs/workbench/parts/terminal/common/terminal.ts",
    "line": 63,
    "offset": 28
}
[Trace - 1:31:38 PM] Response received: implementation (521). Request took 2 ms. Success: true 
Result: [
    {
        "file": "/Users/matb/projects/vscode/src/vs/workbench/parts/terminal/electron-browser/terminalConfigHelper.ts",
        "start": {
            "line": 40,
            "offset": 15
        },
        "end": {
            "line": 212,
            "offset": 16
        }
    }
]
```

The returned range makes no sense. The end location is beyond the file end while the start location is 30 lines before the actual implementation

I'll see if I can get a smaller repo so I can report this to TS.

**Comment by Tyriar** [comment]
@mjbvz it might be worth disabling the feature for TS until this is fixed, it feels very broken currently.

**Comment by mjbvz** [comment]
Good idea, it’s clearly not stable across files with TS2.1.5. I’m going to gate the feature to TS 2.2 for now. That way when ts fixes it in the nightly builds (which we hopefully can prioritize) people will automatically pick up better support. The only buggy scenario then would be for people on a 2.2 TS nightly before they fix things

**Comment by mjbvz** [comment]
Fixed on the TS side: https://github.com/Microsoft/TypeScript/issues/13477 . You can try it by installing `typescript@next`
