### ISSUE TITLE
Hide Sticky Scroll In Diff Editor When Collapse Unchanged Regions Is Enabled

### ISSUE THREAD

**Issue by hediet** [microsoft/vscode#185228]
![Code_-_Insiders_ppouFWjcAa](https://github.com/microsoft/vscode/assets/2931520/fda4d62c-10b5-496d-a50f-4c5eb7848a86)

Maybe we can quickly meet to discuss how to do this.

**Comment by aiday-mar** [comment]
Recently fixed by @hediet
