### ISSUE TITLE
Can't kill servers

### ISSUE THREAD

**Issue by Fantasim** [microsoft/vscode#185296]
Type: <b>Bug</b>

after installing the last version I can't anymore kill anything with Ctrl+C in the VSCode terminal

^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^....

**Comment by milankrushna** [comment]
I am also facing the same issue on my Mac os

**Version: 1.79.1**
Commit: 4cb974a7aed77a74c7813bdccd99ee0d04901215
Date: 2023-06-12T16:16:49.215Z (3 days ago)
Electron: 22.5.7
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Darwin x64 18.6.0

**Comment by Yugenstudio** [comment]
same here

Version: 1.79.2 (Universal)
Commit: 695af097c7bd098fbf017ce3ac85e09bbc5dda06
Date: 2023-06-14T08:58:52.392Z (4 days ago)
Electron: 22.5.7
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Darwin x64 18.7.0

**Comment by Fantasim** [comment]
When the problem will be fixed @Tyriar

**Comment by AceYangWQ** [comment]
So do I

VS Code Version: 1.79.2
OS Version: macOS Mojave 10.14.6

**Comment by milankrushna** [comment]
For a temporary fix, we can install a previous version like 1.75 of VS Code, and just disable the auto-update till a new update resolve of this issue. this is working for me.

**Comment by AceYangWQ** [comment]
So do I

VS Code Version: 1.79.2 (latest)
OS Version: macOS Mojave 10.14.6

I can't use the new version because of this problem. When can you solve it completely

**Comment by Tucsky** [comment]
I bought a new mac, problem solved

**Comment by AceYangWQ** [comment]
> I bought a new mac, problem solved

Really? No problems with the new system?
