### ISSUE TITLE
Compounds launch configuration not working on latest Insider's

### ISSUE THREAD

**Issue by Krzysztof-Cieslak** [Microsoft/vscode#18529]
Running compounds launch configuration ends up with `Configuration 'Compound' does not exist.`

I *think* it got broken on yesterday's Insider.

Reproduction: https://github.com/Krzysztof-Cieslak/vscode-compounds-bug

**Comment by Krzysztof-Cieslak** [comment]
I can't reproduce problem any more, looks like it's fixed.

**Comment by isidorn** [comment]
Yes, this got fixed sorry for not closing it!
