### ISSUE TITLE
[Feature request] In search, show total result count

### ISSUE THREAD

**Issue by AshleyScirra** [Microsoft/vscode#18523]
- VSCode Version: Code 1.8.1 (ee428b0eead68bf0fb99ab5fdc4439be227b6281, 2016-12-19T14:49:23.350Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

Steps to Reproduce:

1. In a large project, search for a term with lots of results (e.g. "TODO")
2. Wonder how many results there are in total

I can't see that VS Code gives the total result count anywhere. It lists the results per file, but the total result count either isn't there, or isn't obvious enough for me to have found it!

**Comment by roblourens** [comment]
Something like this would be cool:

![image](https://cloud.githubusercontent.com/assets/323878/21946541/bb292f62-d995-11e6-8bd2-c6121db02542.png)

**Comment by roblourens** [comment]
I just found this old issue with some discussion on this feature: #6669

Closing as dupe
