### ISSUE TITLE
Activitybar active border color gone v1.79.2

### ISSUE THREAD

**Issue by EmrecanKaracayir** [microsoft/vscode#185264]
After the update, `activityBar.activeBorder` color attribute is not visible

![image](https://github.com/microsoft/vscode/assets/84916904/984e3e81-b71e-4c20-9800-df16d355d9f1)

Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.79.2
- OS Version: Windows 11 22H2

Steps to Reproduce:

1. Update VS Code
2. Open any sidebar item
3. Observe activity bar active indicator (border)

**Comment by christippett** [comment]
The colour settings in `globalStorage/settings.json` seem to be overriding theme colours or customisations made in `workbench.colorCustomizations`.

```json
{
  "windowSplash": {
      "zoomLevel": -1,
      "baseTheme": "vs",
      "colorInfo": {
          "foreground": "#444d56",
          "background": "#ffffff",
          "editorBackground": "#ffffff",
          "titleBarBackground": "#14474b",
          "activityBarBackground": "#0e3335", // green/teal colour
          "sideBarBackground": "#f6f8fa",
          "statusBarBackground": "#ffffff",
          "statusBarNoFolderBackground": "#ffffff"
      },
      "layoutInfo": {
          "sideBarSide": "left",
          "editorPartMinWidth": 220,
          "titleBarHeight": 42,
          "activityBarWidth": 48,
          "sideBarWidth": 352,
          "statusBarHeight": 22,
          "windowBorder": false
      }
  }
}
```

![Screenshot 000205 - Code@2x](https://github.com/microsoft/vscode/assets/7218120/8f63e302-1a11-4ecb-901a-b1269a145e85)

**Comment by daviddossett** [comment]
Hmm, I can't repro this. Is it happening in all themes? 

I'm able to see the border on both mac and web versions, fwiw.

**Comment by EmrecanKaracayir** [comment]
It was a weird bug. Not happened to me on Linux, not happened to me on another Windows 11 22H2 installation. I reinstalled the installation of VS Code that this bug was happening and it is magically went away. I am not able to reproduce again.

**Comment by daviddossett** [comment]
Strange! Well I'll go ahead and close this but reopen if you see it again.

I doubt this was the case but I've sometimes thought it's gone missing too, only to find out my non-maximized window was slightly offset such that the border was clipped off the side of the screen.

**Comment by EmrecanKaracayir** [comment]
Oh wait. I think I know why. It is because the theme that was active defined 'window.border' and 'window.activeBorder' a value rather than null. Later when I changed the theme to any other theme (default ones too) that activity bar border was not there, even after restarting VS Code. Maybe that was why.
