### ISSUE TITLE
Restarting the pty host can break future terminals

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#185254]
Something doesn't seem right, this may have regressed with the utility process refactor. May be the direct proxy never gets set up when it's restarted?

**Comment by meganrogge** [comment]
What does it look like when this happens?

**Comment by Tyriar** [comment]
An empty terminal panel, no xterm or tabs. You can create a new instance fine though

**Comment by Tyriar** [comment]
It just breaks all terminals, and creating new ones show and then get destroyed
