### ISSUE TITLE
Opening integrated terminal using ctrl+` doesn't unset ctrl when viewing image

### ISSUE THREAD

**Issue by connorskees** [microsoft/vscode#185247]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 
Version: 1.80.0-insider (user setup)
Commit: 6545c4c2671127c323182225963fcd732e1fbcc5
Date: 2023-06-15T05:33:30.720Z
Electron: 22.5.7
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Windows_NT x64 10.0.19045
- OS Version: Microsoft Windows [Version 10.0.19045.2965]

Steps to Reproduce:

When viewing an image, you can hold down ctrl to switch the action of scrolling from moving around the image to zooming in and out of the image.

When one opens the integrated terminal using the ctrl+` shortcut while viewing an image, the image does not register the ctrl key-up event, and so remains in the zooming state, despite ctrl not being held. Presumably this is because the terminal captures the key-up event, rather than the main window. If you click back into the main window and press ctrl, it registers the keypress and goes back to normal.

1. Open image file in VSCode
2. Open integrated terminal using ctrl+\` (backtick) keyboard shortcut
3. Hover over image and scroll mouse wheel/pad

**Comment by connorskees** [comment]
This reproes on at least a version of VSCode from February, and would likely be unrelated to any recent changes.

**Comment by meganrogge** [comment]
This works for me on macOS

https://github.com/microsoft/vscode/assets/29464607/9ea6a260-715f-4622-ae00-189c6f733037

**Comment by connorskees** [comment]
Here is a screen recording of the issue:

https://github.com/microsoft/vscode/assets/39542938/16ba0df9-3512-4f9c-b466-c8c6fc9ee98c

After the integrated terminal opens, I am not holding any keys. This is in a fresh install of VSCode insiders without any changes applied.
