### ISSUE TITLE
VSCodeInline template html element selection brokenish

### ISSUE THREAD

**Issue by invaderb** [microsoft/vscode#185267]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.79.2
- OS Version:  Ventura 13.4

Steps to Reproduce:
1.  use an inline HTML template (doing this with angular currently)
2. click on an element and see that it highlights the whole template string rather than just the matching html elements

I've disabled all extension and using the default theme and it still does it, it's not really a blocking visual bug but kinda annoying when editing inline html.  any help fixing this would be greatly appreciated!
See attached file
<img width="773" alt="Screenshot 2023-06-15 at 12 31 50 PM" src="https://github.com/microsoft/vscode/assets/16693116/c4b36d68-9a08-4f1a-b789-e9db6821b438">

Edit:
I've also tried installing the highlight matching tag extension and didn't see to help the issue. but in regualr html files VScode does this out of the box so I'm curious how to get it working for inline templates...

**Comment by invaderb** [comment]
Ok I figured out this is an issues with the occurrencesHighlight setting and doesn't seem to play nicely with inline templates, if I turn the setting off the border goes away but then I loose out on highlighting occurrences...

**Comment by mjbvz** [comment]
Occurrences highlighting now seems to be disabled on multi-line template strings like this
