### ISSUE TITLE
colorization of tab character "\t" in string does not work properly

### ISSUE THREAD

**Issue by bernd4** [microsoft/vscode#185246]
Type: <b>Bug</b>

In C#
When using een tab character "\t" in a string, the colorization of the "\t" only works when it is used behind a curly-brace {} with string-interpolation.
The tab character "\t" now displays a ligther orange color.

If the tab character is not directly behind a curly-brace, the tab character "\t" displays the same color as the rest of the string.

Good:
Console.WriteLine($"{name}\t\t{studentGrade}\t?");

Not Good:
Console.WriteLine("Student\t\tGrade\n");

VS Code version: Code 1.79.1 (4cb974a7aed77a74c7813bdccd99ee0d04901215, 2023-06-12T16:14:05.102Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|16.0.0
vscode-html-css|ecm|1.13.1
remotehub|Git|0.58.0
csharpextensions|kre|1.7.3
csharp|ms-|1.25.9
python|ms-|2023.10.1
vscode-pylance|ms-|2023.6.20
azure-repos|ms-|0.34.0
remote-repositories|ms-|0.36.0
vsliveshare|ms-|1.0.5873
material-icon-theme|PKi|4.28.0
LiveServer|rit|5.7.9

</details>

**Comment by ulugbekna** [comment]
Hi, thanks for filing the issue! 
I believe this issue needs to be filed with the C# extension.

**Comment by RedCMD** [comment]
@bernd4 I don't see the issue
![image](https://github.com/microsoft/vscode/assets/33529441/e4f6f9ec-58f9-4da3-816d-8f6f29dba8f2)
can you send a screenshot?
are you using vscodes `dark` theme?
you should switch to `dark+`

**Comment by bernd4** [comment]
I use the dark+ theme.
When I switch themes or copy paste the code, it momentarily renders correct, but switches back to the wrong color.

If I turn off the C# extentions (the standard extention from microsoft), there are no problems.

![image](https://github.com/microsoft/vscode/assets/122995488/8e225ee1-3d18-4004-b5d6-e837056bf024)

![image](https://github.com/microsoft/vscode/assets/122995488/714e07f3-0e7c-4e6e-aadd-06540c1f7dae)

**Comment by RedCMD** [comment]
if issue still exists
should make report to https://github.com/jeff-hykin/better-cpp-syntax

**Comment by bernd4** [comment]
Ok just did... issue still exists.
Below the link to new report.
https://github.com/jeff-hykin/better-cpp-syntax/issues/639
