### ISSUE TITLE
VSCode Sticky scroll

### ISSUE THREAD

**Issue by Yarmuhammadtalpur** [microsoft/vscode#185333]
Vscode sticky scroll only works on simple function but does not work on arrow function can you add that too?
![Screenshot (165)](https://github.com/microsoft/vscode/assets/76510029/8e21a9bd-3e9b-4e11-982c-d526442d3acc)
![Screenshot (164)](https://github.com/microsoft/vscode/assets/76510029/3f3207b1-fa0c-49b2-9c5c-035f16e17f62)

**Comment by aiday-mar** [comment]
Hi @Yarmuhammadtalpu, the lines which are stuck with sticky scroll are determined by the the model which you use to define the sticky lines. This can be configured in the setting: `editor.stickyScroll.defaultModel`. By default this setting takes in the value outline model which means it will use the outline model to determine which lines should be stuck by the sticky scroll. You may also choose the folding provider model (will use the folding ranges) or the indentation model (uses the indentation guides to stick the lines). These may not help you stick the arrow functions as you so wish. This is the reason why the following issue is open: https://github.com/microsoft/vscode/issues/168428. When the sticky scroll API is implemented, extensions will be able to provide their own sticky scroll outlines and, for example, also stick arrow functions.
