### ISSUE TITLE
Settings Sync is On should show what account it is using

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#185352]
Was just discussing with @timheuer how to figure out what account is being used for setting sync. And currently it is not trivial. We render it only after user clicks on the Settings Sync is On button inside the quick pick.

Tim had a good suggestion to render the account in brackets in the menu. So something like
`Settings Sync is On (isidorn GitHub)`
@sandy081 what do you think?

Alternatively, if we redesign the account menu we should keep this in mind to make it more obvious to the users what is under what account.

![Screenshot 2023-06-16 at 17 54 32](https://github.com/microsoft/vscode/assets/1926584/5204727a-3ed3-431b-911e-97bb073e7713)

**Comment by sandy081** [comment]
Label looks good with GitHub account

<img width="405" alt="image" src="https://github.com/microsoft/vscode/assets/10746682/a65f890f-7bbe-4eb0-b689-5b512a40cbe9">

But not with Microsoft account

<img width="657" alt="image" src="https://github.com/microsoft/vscode/assets/10746682/81321f09-f5eb-4067-9f32-2e8f6cd0ecd0">

CC @TylerLeonhardt

**Comment by jammel-yeboah** [comment]
> Label looks good with GitHub account
> 
> <img alt="image" width="405" src="https://user-images.githubusercontent.com/10746682/255400166-a65f890f-7bbe-4eb0-b689-5b512a40cbe9.png">
> But not with Microsoft account
> 
> <img alt="image" width="657" src="https://user-images.githubusercontent.com/10746682/255400132-81321f09-f5eb-4067-9f32-2e8f6cd0ecd0.png">
> CC @TylerLeonhardt

Hey @sandy081 I'm interested in working on this issue but I'm not familiar with the account and settings menu and working on them. Do you mind pointing toward the right place to look in the codebase for this issue? Thanks!

**Comment by isidorn** [comment]
@jammel-yeboah thanks for reaching out, but @sandy081 and me synced offline and decided to tackle this as part of a bigger work item that will look into improving the accounts menu overall.

If you would like to contribute I suggest looking for issues with the `help-wanted` label. Thank you

**Comment by alexchandel** [comment]
Will this ever be fixed?  It's impossible to determine at the moment, and causing problems for me.

@sandy081 How can you determine it?
