### ISSUE TITLE
Bring read-only message to explorer decoration

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#185322]
Follow up from https://github.com/microsoft/vscode/issues/166971: 
https://github.com/microsoft/vscode/pull/185216#discussion_r1231796181

**Comment by bpasero** [comment]
//cc @lramos15

**Comment by bpasero** [comment]
Having played with this, I am no longer so convinced to actually do it because decorations already have lots of text and this makes it only longer. The user will get the feedback in the editor with a nice action to resolve it, so I think we can close this as out of scope.
