### ISSUE TITLE
Feedback of default log level for a channel is confusing

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#185342]
Repro:

1. Set default log level for all channels to debug
2. Set default log level for pty host to trace
3. Run the set log level command

This is the quick pick that shows, this is good:

![image](https://github.com/microsoft/vscode/assets/2193314/1ec891db-11dc-4cba-863b-48a1dc145c17)

When I click into the pty host it shows that debug is the default, which is the default for all channels, not the pty host specifically:

![image](https://github.com/microsoft/vscode/assets/2193314/2af37d1c-b0f4-48ed-9e61-f2fe6c500b36)

**Comment by sandy081** [comment]
This is because we do not support setting default log level per logger in core. It can be configured for core + extensions only.  This action shown in UI for core loggers is a bug.
