### ISSUE TITLE
drag dropping folders goes to the wrong window.

### ISSUE THREAD

**Issue by bobmagicii** [Microsoft/vscode#18535]
- VSCode Version: 1.9.0-insider
- OS Version: Windows 10

Steps to Reproduce:

1. start vs code
2. open folder as project workspace
3. file > new window
4. drag folder from desktop to new window
5. lol as first window opens the folder

**Comment by bpasero** [comment]
@bobmagicii is the first window maybe having that folder open already? we currently do not support opening the same folder in multiple windows.

**Comment by bobmagicii** [comment]
ah. no i don't think so. here is the situation:

start vs code, open folder w:\ (a remote ssh mount not that it matters)

file > new window, open folder c:\users\bob\desktop\autofoldyeah (my extension on the market place)

however, autofoldyeah ends up in the first window, not the new window i drag it to.

if you'd like, i could record a video of it.

**Comment by bpasero** [comment]
@bobmagicii yeah video would help

**Comment by bobmagicii** [comment]
i am inclined to say we can close this issue. i've only been able to replicate it twice since, and both times was not while i was recording. im thinking that maybe this computer is crap (old imac with w10) and maybe the drop target just isn't getting updated fast enough. for the most part, intentionally replicating has been difficult.

**Comment by bobmagicii** [comment]
i don't want to jynx it, but i actually just had it happen without even drag and dropping. had a new window clicked the blue open folder button, and it took over my existing window rather than the new one. the same instance is still running, is there by chance any specific log files that may be useful?
