### ISSUE TITLE
Startup fails for EditorServices for PowerShell

### ISSUE THREAD

**Issue by gabfv** [microsoft/vscode#185353]
Type: <b>Bug</b>

When starting EditorServices for PowerShell. Here's the error message:

```
PowerShell Extension v2023.6.0
Copyright (c) Microsoft Corporation.

https://aka.ms/vscode-powershell
Type 'help' to get help.

Exception encountered starting EditorServices. Exception logged in D:\a\_work\1\s\src\PowerShellEditorServices.Hosting\Commands\StartEditorServicesCommand.cs on line 236 in EndProcessing:      
System.MissingMethodException: Méthode introuvable : '!0 OmniSharp.Extensions.JsonRpc.JsonRpcOptionsRegistryBase`1.WithServices(System.Action`1<Microsoft.Extensions.DependencyInjection.IServiceCollection>)'.
   à Microsoft.PowerShell.EditorServices.Server.PsesLanguageServer.<StartAsync>b__14_0(LanguageServerOptions options)
   à OmniSharp.Extensions.LanguageServer.Server.LanguageServer.From(Action`1 optionsAction, IServiceProvider outerServiceProvider, CancellationToken cancellationToken)
   à Microsoft.PowerShell.EditorServices.Server.PsesLanguageServer.<StartAsync>d__14.MoveNext()
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à Microsoft.PowerShell.EditorServices.Hosting.EditorServicesRunner.<CreateEditorServicesAndRunUntilShutdown>d__9.MoveNext()
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à Microsoft.PowerShell.EditorServices.Commands.StartEditorServicesCommand.EndProcessing()
```

VS Code version: Code 1.79.2 (695af097c7bd098fbf017ce3ac85e09bbc5dda06, 2023-06-14T08:57:04.379Z)
OS version: Windows_NT x64 10.0.19044
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-10210U CPU @ 1.60GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.68GB (6.97GB free)|
|Process Argv|--crash-reporter-id 69b9c32f-c375-4f66-9b8f-cfe3122fa474|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (18)</summary>

Extension|Author (truncated)|Version
---|---|---
xml|Dot|2.5.1
prettier-vscode|esb|9.13.0
vscode-diff|fab|1.4.2
copilot-chat|Git|0.2.1
copilot-nightly|Git|1.89.163
todo-tree|Gru|0.0.226
dupchecker|jia|0.1.7
intellij-idea-keybindings|k--|1.5.9
vscode-autohotkey-plus-plus|mar|3.3.0
git-graph|mhu|1.30.0
hexeditor|ms-|1.9.11
powershell|ms-|2023.6.0
vscode-sanddance|msr|4.1.0
indent-rainbow|ode|8.3.1
partial-diff|ryu|1.4.3
vbsvscode|Ser|1.2.1
sort-lines|Tyr|1.10.1
win-ca|uko|3.5.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes516:30244333
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscorecescf:30445987
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
3biah626:30602489
pyind779:30671433
f6dab269:30613381
pythonsymbol12:30671437
showlangstatbar:30737416
vsctsb:30748421
pythonms35:30701012
a2ce3375:30757347
24365598:30736109
pythonfmttext:30731395
pythoncmvfstrcf:30756944
fixhidewlkth:30730051
showindicator:30766890
pythongtdpath:30769146
i26e3531:30769768
dh2dc718:30763024

```

</details>

**Comment by ulugbekna** [comment]
I think this needs to be filed with the OmniSharp extension - https://github.com/dotnet/vscode-csharp
