### ISSUE TITLE
Cannot connect to remote tunnels from the web since 1.79

### ISSUE THREAD

**Issue by francoismichel** [microsoft/vscode#185311]
Hi,

Since this week, I cannot connect to my remote tunnels anymore.
I use vscode.dev to connect on my development server that runs the code CLI
in a Ubuntu docker. Everything seems to work correctly on the server-side: the tunnel is spawned
and correctly connected with the relay, regularly sending pings and receiving pongs.

When I try to connect to my remote environment, I can see that the remote tunnel is marked "online"
from the client, so everything looks fine.

However, when I try to connect, it hangs forever, unable to establish websocket connections with  the relay.

When opening the browser console, I can see this error occurring repeatedly at intervals of several dozens of seconds:

```
extension.js:4 WebSocket connection to 'wss://euw-data.rel.tunnels.api.visualstudio.com/api/v1/Client/Connect/20hbrvgh' failed: 
openConnection @ extension.js:4
createRelayStream @ extension.js:4
createSessionStream @ extension.js:4
connectSession @ extension.js:4
5log.ts:441   ERR Timeout connecting to relay: Error: Timeout connecting to relay
	at eval (https://ms-vscode.vscode-unpkg.net/ms-vscode/remote-server/1.2.1/extension/dist/web/extension.js#vscode-extension:4:729805)
```

I was using the 1.79.1 version, then had the same problem with the 1.79.2 version, and I just tried the insider 1.80.0 version with no success, but it looks that the problem is coming from the client and not the server. The server looks fine, here are the
last lines of the code CLI log on the server:

```
[2023-06-16 08:00:23] trace Found token in keyring
[2023-06-16 08:01:23] debug [tunnels::connections::ws] sent liveness ping
[2023-06-16 08:01:23] debug [tunnels::connections::ws] received liveness pong
[2023-06-16 08:02:23] debug [tunnels::connections::ws] received liveness pong
[2023-06-16 08:03:23] debug [tunnels::connections::ws] sent liveness ping
[2023-06-16 08:03:23] debug [tunnels::connections::ws] received liveness pong
[2023-06-16 08:04:23] debug [tunnels::connections::ws] received liveness pong
[2023-06-16 08:05:23] debug [tunnels::connections::ws] sent liveness ping
[2023-06-16 08:05:23] debug [tunnels::connections::ws] received liveness pong
[2023-06-16 08:06:23] debug [tunnels::connections::ws] received liveness pong
[2023-06-16 08:07:23] debug [tunnels::connections::ws] sent liveness ping
[2023-06-16 08:07:23] debug [tunnels::connections::ws] received liveness pong
[2023-06-16 08:08:23] debug [tunnels::connections::ws] received liveness pong
[2023-06-16 08:09:23] debug [tunnels::connections::ws] sent liveness ping
[2023-06-16 08:09:23] debug [tunnels::connections::ws] received liveness pong
[2023-06-16 08:10:23] debug [tunnels::connections::ws] received liveness pong
```

What is puzzling me is that it was working fine for weeks before.

It seems similar to #185106 but the person there succeeded to make it work simply by
downloading the .tar.gz archive, I can not. I tried with both the tar.gz and the .deb package.

Version: 1.80.0-insider
Commit: 0e9c2fa760932b13f81516aff15f2b0112aa6eeb
User Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36
Embedder: vscode.dev

**Comment by connor4312** [comment]
@derekbekoe it looks like the host connection is up (required for us to mark the state as "online") but relay connections aren't getting through. Is your team able to investigate logs here?

Looks like the tunnel ID is `20hbrvgh. euw`

**Comment by IlyaBiryukov** [comment]
We're seeing some of client connections in this scenario hanging while they try to open SSH channel to the host SSH session. The hosts are connected with `vscode-server-launcher` user agent. One more peculiarity is that sometimes there are multiple host connections for the same tunnel at the same time.

@connor4312 can you share traces from the host SSH session when this issue happens?

**Comment by connor4312** [comment]
I have observed that, if the CLI process is not terminated gracefully, the host connection can stay around on the tunnel even though there's actually no longer any connection running. In this case, a client connecting will observe that the websocket connection to the Tunnels service times out after several minutes. This is pretty easy to reproduce by SIGKILL'ing a `code tunnel` process.

More rarely, similar behavior is seen on the client side, but the host side never gets any SSH messages from the service, although the websocket is still alive. Usually after retrying a few times or recreating the tunnel the issue goes away. That seems to be what's happening here. I never got a good repro for that.

**Comment by IlyaBiryukov** [comment]
I see we have two issues here on the dev tunnels side: 
1. Better detect when the host process is killed and host connection gets stale. We could decrease ws timeout or introduce SSH ping messages.
2. Whenever there are multiple host connections, pick the good one (right now we assume all are the good ones and pick one randomly).  

Any idea why this started happening now?

**Comment by connor4312** [comment]
The issues I referenced aren't new, they've been around for quite some time.

**Comment by megamorf** [comment]
This has also been affecting me for roughly a month. Let me know what information I can provide to narrow down the number of possible causes.

**Comment by megamorf** [comment]
Also, to add to this - so far I've been using vscode-server which was installed and ran like this:

```
wget https://aka.ms/install-vscode-server/setup.sh
bash setup.sh
/usr/local/bin/code-server --accept-server-license-terms
```

Thanks to the issue that francois has linked at the top of this issue I learned that apparently code CLI has replaced  code-server. This is not clear at all from the docs so I definitely urge you to update the page to add that users of code-server are expected to switch: https://code.visualstudio.com/docs/remote/tunnels

**Comment by connor4312** [comment]
Since the beginning of May, you should have been getting a warning notification whenever you connected to a deprecated "code-server" tunnel.

**Comment by megamorf** [comment]
Yes, however the warning just mentioned that the tunnel was outdated. The page itself contained no instructions on how to update the tunnel. And that's the main issue - you were linking to a page that did not clearly explain that users of code-server need to migrate.

I deal with technical writing a lot and what might be clear to you might not be clear at all to others. It would've been easy to have a section on that page with migration instructions. It also does not help, that you refer to code-server and code CLI as "VS Code Server". That together with the lack of migration instructions makes the distinction even harder.

**Comment by connor4312** [comment]
In the next release, the warning will be more verbose and also modal.

**Comment by francoismichel** [comment]
Hi,

I think several issues are mixed here and I don't think the original issue is solved. I am not using an outdated version of the code cli. I am using the most recent versions of the `code` cli on my tunnel, and it still does not work, even on the insiders version.

Here is the command I use to spawn my server:

```
code-insiders tunnel --verbose --accept-server-license-terms
```

I still cannot connect to the server, either from the web or the app, still having timeouts to connect to the relay, as the following error, coming directly from Brave's developer console:

```
 INFO Creating a socket (renderer-Management-0e15b721-79f8-41d0-843d-11654d17a3ec) returned an error after 29936 ms.
workbench.web.main.js:624   ERR Error: Timeout connecting to relay
	at eval (extension.js:4:729805)
workbench.web.main.js:624   ERR [remote-connection][Management   ][0e15b…][initial][Managed(1)] socketFactory.connect() failed or timed out. Error:
workbench.web.main.js:624   ERR Error: Timeout connecting to relay
	at eval (extension.js:4:729805)
workbench.web.main.js:624   ERR [remote-connection][attempt 1] An error occurred in initial connection! Will retry... Error:
workbench.web.main.js:624   ERR Error: Timeout connecting to relay
	at eval (extension.js:4:729805)
```

I don't think it is an outdated CLI problem as my `code` CLI is the as up-to-date as possible.
