### ISSUE TITLE
terminal.integrated.localEchoStyle has 2 default values?

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#185343]
![image](https://github.com/microsoft/vscode/assets/2193314/ddf72880-99ac-4251-8486-2392b564a94e)

		[TerminalSettingId.LocalEchoStyle]: {
			description: localize('terminal.integrated.localEchoStyle', "Terminal style of locally echoed text; either a font style or an RGB color."),
			default: 'dim',
			oneOf: [
				{
					type: 'string',
					default: 'dim',
					enum: ['bold', 'dim', 'italic', 'underlined', 'inverted'],
				},
				{
					type: 'string',
					format: 'color-hex',
					default: '#ff0000',
				}
			]
		},

**Comment by weartist** [comment]
I'll fix it
