### ISSUE TITLE
30 seconds of 100% CPU usage every time my web app makes an ajax request

### ISSUE THREAD

**Issue by seanthebean** [Microsoft/vscode#18538]
- VSCode Version: 1.8.1
- OS Version: Arch Linux (kernel v4.8.8)

Steps to Reproduce:

1. Trigger any HTTP request when running the web application I'm working on (sorry, it isn't open source, so I realize that doesn't help a great deal)

The problem is that when I do this, vscode immediately jumps to 100% CPU on one core, and stays there for about 30 seconds before returning to normal. Naturally, this cuts the battery life of my laptop pretty dramatically, to the extent that I am not willing to make vscode my primary editor.
![vscode using 100 cpu](https://cloud.githubusercontent.com/assets/3988775/21951406/c1379aae-d9d3-11e6-8ac5-8767c9fe7a74.png)

Oddly, it is a `code` process that spikes, but performance while using the application does not seem to be affected. At first I thought it might be reindexing files (due to adding a rendered view file or some such), but I tried adding and editing test files, and neither produced the same result (doesn't rule it out, just makes it less a likely suspect in my mind). I have also tried opening it via `code --disable-extensions`, and I still have the same issue, so it's not an extension that's causing the problem.

Here are a few details about my project that might help narrow it down:
- this is a large application (hundreds of thousands of files)
- we use PHP (Laravel) for the back-end, and we're in the process of transitioning to Angular 2 in TypeScript (from an awkward mish-mash of Angular 1, Knockout, and some other stuff that we wrote ourselves in CoffeeScript)
- we use gulp, webpack, npm, and websockets (to name a few more technologies that might be relevant)

To make this even more of a challenge, none of my three coworkers who are using vscode for this project are experiencing this issue, despite having very similar setups. At this point I don't have much hope of there being a clear solution, but I wanted to log this so that if anyone else experiences it, they may be able to add more info that would help diagnose it.

**Comment by dbaeumer** [comment]
@seanthebean can you please provide the full command line of the process that causes the CPU spike. That would help to better understand which part of VS Code is consuming the CPU.

**Comment by seanthebean** [comment]
```
/opt/visual-studio-code/code /opt/visual-studio-code/resources/app/out/bootstrap --type=watcherService
```

**Comment by dbaeumer** [comment]
@bpasero --type=watcherService

**Comment by bpasero** [comment]
@seanthebean is the CPU high only initially on startup when opening the folder and then eventually calms down?

**Comment by adamk33n3r** [comment]
This might be related, I have found that sometimes when changing to a different branch in `git` that has a lot of differences I get super high cpu usage to the point where my computer becomes unresponsive. the process that has the high usage is a `--type=searchService`

**Comment by bpasero** [comment]
@adamk33n3r can we have a separate issue for that? please double check that the process is reproducibly search service.

**Comment by seanthebean** [comment]
@bpasero No. It spikes whenever an AJAX request is made while vscode is running, not just on startup. So far it seems to be related to the number of files the web app compiles and stores in a designated folder in the project directory, and vscode's watcher service just can't keep up.

**Comment by bpasero** [comment]
Let's merge into https://github.com/Microsoft/vscode/issues/3998
