### ISSUE TITLE
Docker Extension Icon Not Showing On Activity Bar

### ISSUE THREAD

**Issue by MinamiHasaki** [microsoft/vscode#185366]
OS: Windows 10 Enterprise 19045.3086
Browser: Google Chrome 114.0.5735.134
Remote OS: Ubuntu 22.04.2 LTS
VS Code: 1.79.2
Remote - Tunnels Extension: v1.2.1
Docker Extension: 1.25.1

I'm using VS Code remotely. I'm using the Visual Studio Code Remote - Tunnels to connect to an Linux machine running the tunnel service via VS Code CLI.

I've installed the Docker extension and the icon isn't showing up in the activity bar even though I can click it and use the extension. Uninstalling and reinstalling the extension doesn't help; neither does restarting the system or tunnel service.

![image](https://github.com/microsoft/vscode/assets/20251864/7f9f98ce-6f7a-4ec0-943c-f8f28feab3f5)

**Comment by sandy081** [comment]
Can you please inspect the element and let us know the URL of the icon
- F1 > Toggle Developer Tools
- Go to Elements Tab, Click on Inspect element button
<img width="482" alt="image" src="https://github.com/microsoft/vscode/assets/10746682/8adfb57a-ad9e-4c7d-a421-2b5ab2dde632">
- Select the invisible docker icon element - This will reveal the element in the tab
- In the Styles tab, check the location of the image and let us know. Please take a screenshot and share it.

**Comment by MinamiHasaki** [comment]
Here is the screenshot:

![image](https://github.com/microsoft/vscode/assets/20251864/eaf3d769-599f-4ee0-8bb7-176de3cce9fb)

This is the full CSS declaration  that seems to point to the docker icon svg file:

```css
    -webkit-mask: url("https://vscode.dev/loopback?{\"$mid\":1,\"path\":\"/home/minami/.vscode-server/extensions/ms-azuretools.vscode-docker-1.25.1/resources/docker.svg\",\"scheme\":\"vscode-remote\",\"authority\":\"tunnel+minami_pusheen\"}") 50% 50% / 24px no-repeat;
```

**Comment by sandy081** [comment]
Looks like tunnels related.

**Comment by connor4312** [comment]
Duplicates https://github.com/microsoft/vscode/issues/185886
