### ISSUE TITLE
JS-MSEdge Debugger stops working when extension changes from html to php

### ISSUE THREAD

**Issue by Spsp1981** [microsoft/vscode#185383]
Type: <b>Bug</b>

I'm making a locally hosted personal website using WAMP, to practise, learn, etc... First I set up and try the JS debugger (using edge) and threw an small html sample file with some embedded JS and it worked fine. Then I set up and try the same page but changed its extension to php and added the classic "phpinfo()" to test php/xdebug settings and it worked just fine but the JS debugger did nothing... 
After a lot of trial and error in launch.json... I removed all extensions, removed all setting except the "Launch Edge"... I commented out the php script and left just the html/js part and made two copies of the file.  When I start the debug session with "index.php" nothings happens, not even the variables are listed. When I start the debug session with "index.html" it all works perfectly!

I've attached the debugger's trace log file for the failing php session in case it's useful
[vscode-debugadapter-628aa5e8.json.gz](https://github.com/microsoft/vscode/files/11775953/vscode-debugadapter-628aa5e8.json.gz)

VS Code version: Code 1.79.2 (695af097c7bd098fbf017ce3ac85e09bbc5dda06, 2023-06-14T08:57:04.379Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 9 3950X 16-Core Processor             (8 x 3500)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: unavailable_off<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|8.00GB (5.02GB free)|
|Process Argv|--crash-reporter-id e2118edf-6fc0-43c8-bc18-04eab49581bf|
|Screen Reader|no|
|VM|100%|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
prettier-vscode|esb|9.13.0
vscode-edge-devtools|ms-|2.1.2

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
3biah626:30602489
pyind779:30671433
f6dab269:30613381
vscrpc:30673769
pythonsymbol12:30671437
showlangstatbar:30737416
vsctsb:30748421
pythonms35:30701012
03d35959:30757346
pythonfmttext:30731395
pythoncmv:30756943
fixhidewlkth:30730051
hideindicator:30766889
pythongtdpath:30769146
bgfeh915:30763804
dh2dc718:30763024

```

</details>

**Comment by connor4312** [comment]
It looks like the line numbers are probably different in your rendered index.php than in the source file. The easiest way to fix this is just use external scripts and include them via `<script src="...">` tags
