### ISSUE TITLE
String delimiters should be different colour to the string contents

### ISSUE THREAD

**Issue by benliddicott** [microsoft/vscode#185350]
It is useful to be able to quickly see which characters are the delimiters of a string, versus the contents of a string. 

This is especially useful in languages which support multiple string delimiters and/or use "string pasting" such as Python and shell scripts, where it is not always obvious whether the quote marks are part of the string, or are delimiters.

As a workaround, this can be done right now by specifying custom textmate rules, but I find this so useful I think that other people will find it useful too.

```json

    "editor.tokenColorCustomizations": {
        "textMateRules": [
            {
                "scope": [
                    "punctuation.definition.string", 
                    "punctuation.definition.string string"
                ],
                "settings": {
                    "foreground": "#ff8050"
                }
            }
        ]
    },
```

This works for me in all the languages I have tried, including Python, Ruby, Shell, Java, SQL, YAML, JSON, Groovy, Javascript, Typescript and so on.

I am not sure why the second scope is necessary, but without it, it wasn't working for Python f-strings.

**What is the feature**

The feature is to (somehow) make this a first-class "thing" supported by default themes, and hopefully in time all themes.

**Examples**

I'm using default dark theme.

With that theme, by default it looks like this (I have disabled the customization by adding a spurious prefix):

![image](https://github.com/microsoft/vscode/assets/1070719/710df701-8c7a-4408-8265-207f64cf0656)

However, if I enable those textmate rules, it looks like this:
![image](https://github.com/microsoft/vscode/assets/1070719/695d298f-c79c-40d7-a060-80037e600f78)

As you can see the double-quotes in the first image are exactly the same colour as the string contents.
In the second image, they are slightly different.

To make it more obvious, I can increase the contrast:
![image](https://github.com/microsoft/vscode/assets/1070719/a68ace5e-458b-473c-9d3b-6411b8090d4c)

The point is not that I can't do this - I can do this - the point is I would like other people to also get the benefit of this.

Example in Bash code:

![image](https://github.com/microsoft/vscode/assets/1070719/76a38f81-5d49-4140-884a-8b26669cb608)

It's helpful to be able to see which quotes delimit the string and which are part of it.

For example we can see immediately that the single quotes around 'test' are part of the string (and will be echoed) and we are not mislead by the double-quotes around "$2" and can see that they are part of the string - because the single quotes that delimit the string are highlighted.

**Comment by benliddicott** [comment]
I'm using default dark theme.

With that, theme, by default it looks like this:

![image](https://github.com/microsoft/vscode/assets/1070719/710df701-8c7a-4408-8265-207f64cf0656)

However, if I enable those textmate rules, it looks like this:
![image](https://github.com/microsoft/vscode/assets/1070719/695d298f-c79c-40d7-a060-80037e600f78)

As you can see the double-quotes in the first image are exactly the same colour as the string contents.
In the second image, they are slightly different.

To make it more obvious, I can increase the contrast:
![image](https://github.com/microsoft/vscode/assets/1070719/a68ace5e-458b-473c-9d3b-6411b8090d4c)


The point is not that I can't do this - I can do this - the point is I would like other people to also get the benefit of this.

Example in Bash code:

![image](https://github.com/microsoft/vscode/assets/1070719/76a38f81-5d49-4140-884a-8b26669cb608)

It's helpful to be able to see which quotes delimit the string and which are part of it.

**Comment by aeschli** [comment]
Thanks for the suggestion. Please understand that we are careful about changing our default themes. Adding an additional color is always problematic, can cause ripples and result in a lot of user reactions.

I'm happy that you can implement your feature through a setting. The next step would be to publish your own theme.

Closing as won't fix
