### ISSUE TITLE
VS Code crashes when trying to open "as administrator"

### ISSUE THREAD

**Issue by m-e-conroy** [microsoft/vscode#185339]
Type: <b>Bug</b>

Just upgraded to 1.79.2 and now VS Code won't open under administrative privileges.  I keep getting a failed to open window message with 2 buttons to "open a new window" and to "close." Both do the same thing, which is just close VS Code - no new window opens when using the first button.  I need to be able to do this in order to use the NodeJS in the terminal on my work machine.  VS Code opens fine when not using "open as administrator."

VS Code version: Code 1.79.2 (695af097c7bd098fbf017ce3ac85e09bbc5dda06, 2023-06-14T08:57:04.379Z)
OS version: Windows_NT x64 10.0.19042
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.78GB (7.71GB free)|
|Process Argv|--crash-reporter-id 3c96abb6-b40e-4f2f-a6c3-3c6e416a47b0|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (34)</summary>

Extension|Author (truncated)|Version
---|---|---
html-class-suggestions|And|1.2.1
vscode-mjml|att|1.6.0
vscode-intelephense-client|bme|1.9.5
npm-intellisense|chr|1.4.4
vscode-eslint|dba|2.4.0
EditorConfig|Edi|0.16.4
vsc-material-theme|Equ|33.8.0
vsc-material-theme-icons|equ|2.8.0
prettier-vscode|esb|9.13.0
php-intellisense|fel|2.3.14
auto-close-tag|for|0.5.14
godot-tools|gee|1.3.1
todo-tree|Gru|0.0.226
rest-client|hum|0.25.1
vscode-phpfmt|kok|1.1.9
compare-folders|mos|0.22.5
vscode-docker|ms-|1.25.1
vetur|oct|0.37.3
vscode-print|pdc|0.11.6
vscode-versionlens|pfl|1.5.0
vscode-gitignore-generator|pio|1.0.3
polacode|pnp|0.3.4
developer-theme-dark|Raj|5.0.0
vscode-xml|red|0.25.0
vue-vscode-snippets|sdr|3.1.1
unique-window-colors|stu|1.0.51
sass-indented|syl|1.8.26
language-stylus|sys|1.16.0
vscode-status-bar-format-toggle|tom|3.1.1
haml|vay|1.0.1
intellicode-api-usage-examples|Vis|0.2.7
vscodeintellicode|Vis|1.2.30
vscode-icons|vsc|12.4.0
volar|Vue|1.6.4

(4 theme extensions excluded)

</details>

**Comment by m-e-conroy** [comment]
![image](https://github.com/microsoft/vscode/assets/5355587/fa7b2409-a431-48f7-9e48-a5ba22787c6e)

**Comment by deepak1556** [comment]
Please refer to https://code.visualstudio.com/docs/setup/windows#_unable-to-run-as-admin-when-applocker-is-enabled for launching as administrator.
