### ISSUE TITLE
Trying to install an extension, but am getting an error command not found

### ISSUE THREAD

**Issue by filtration** [Microsoft/vscode#18537]
Trying to install a vscode extension, but OP doesn't have a readme I've tried putting the folder in the:

    user/.vscode/extension 

but when I run the command I get the error:

> command 'extension.resolveNamespace' not found

The repo is here: 

    https://github.com/ivonunes/vscode-php-namespace

Any help would be appreciated.

**Comment by kaiwood** [comment]
If you are not using the marketplace, you need to compile the extension yourself before you are able to use it.

After the checkout from within the project directory, run `npm install` first for getting the build tools and required libraries. After that, you can either run it at least one time in the graphical debugger (this triggers the build); or build it on the command line with: `npm run-script vscode:prepublish`.

That should be enough to make it work.

BTW: The correct directory to put extensions in is `~/.vscode/extensions` (notice the additional 's' at the end). 

Extra tip: You don't even have to put the git repo in there, a simple symlink to the project will do too.

**Comment by filtration** [comment]
You, my friend are a live saver. Everything is working.
