### ISSUE TITLE
Problems pane continues to show errors for a moved file

### ISSUE THREAD

**Issue by mandar-lad** [microsoft/vscode#185336]
Type: <b>Bug</b>

The problem pane continues to show errors for a file in which the errors were fixed and was moved to a different folder .. it is a little annoying :)

VS Code version: Code 1.79.1 (4cb974a7aed77a74c7813bdccd99ee0d04901215, 2023-06-12T16:16:49.215Z)
OS version: Darwin x64 22.5.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2800)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|4, 3, 2|
|Memory (System)|16.00GB (0.01GB free)|
|Process Argv|--crash-reporter-id 4dbad343-5c53-45dd-8e2b-3fef39039fdc|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (33)</summary>

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|16.0.0
armview|ben|0.4.6
prettier-vscode|esb|9.13.0
vscode-jest-runner|fir|0.4.60
copilot|Git|1.89.156
mac-ca-vscode|lin|0.1.1
azure-pipelines|ms-|1.208.0
azure-dev|ms-|0.6.0
vscode-azureappservice|ms-|0.24.9
vscode-azurecontainerapps|ms-|0.5.1
vscode-azurefunctions|ms-|1.11.0
vscode-azureresourcegroups|ms-|0.7.5
vscode-azurestaticwebapps|ms-|0.12.1
vscode-azurestorage|ms-|0.15.3
vscode-azurevirtualmachines|ms-|0.6.5
vscode-bicep|ms-|0.18.4
vscode-cosmosdb|ms-|0.19.4
vscode-docker|ms-|1.25.1
vscode-dotnet-runtime|ms-|1.6.0
remote-containers|ms-|0.295.0
azure-account|ms-|0.11.5
azurecli|ms-|0.5.0
vscode-node-azure-pack|ms-|1.2.0
azurerm-vscode-tools|msa|0.15.10
angular-console|nrw|18.2.1
java|red|1.19.0
intellicode-api-usage-examples|Vis|0.2.7
vscodeintellicode|Vis|1.2.30
vscode-java-debug|vsc|0.51.0
vscode-java-dependency|vsc|0.23.0
vscode-java-pack|vsc|0.25.11
vscode-java-test|vsc|0.39.0
vscode-maven|vsc|0.41.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
3biah626:30602489
pyind779:30671433
f6dab269:30613381
pythonsymbol12:30671437
showlangstatbar:30737416
vsctsb:30748421
pythonms35:30701012
03d35959:30757346
pythonfmttext:30731395
pythoncmvfstrcf:30756944
fixshowwlkth:30730052
showindicator:30766890
pythongtdpath:30739704
dh2dc718:30763024
pythonnosmt12:30765603

```

</details>

**Comment by gjsjohnmurray** [comment]
What language? If it's one provided by an extension rather than one VS Code has built-in support for then the issue is likely to be the responsibility of the extension author.

**Comment by mandar-lad** [comment]
Ok looks like those errors were cached for some reason, and are not showing up anymore after restart. But probably this needs to be looked at. The errors should not show up for a file in which the errors were fixed and moved to a different file. Could be a glitch though?

**Comment by sandy081** [comment]
Errors are generated by the extension and it is responsible to clean them up for any file change. If you know which extension is generating these errors, I would recommend to file issue against the extension.
