### ISSUE TITLE
VS Code install new version corrupts installation if app is open

### ISSUE THREAD

**Issue by tehho** [microsoft/vscode#185318]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.79.2
- OS Version: Windows 11 21H2 22000.1936

Steps to Reproduce:

1. Have vs code installed and open
2. Let company portal push an update from windows store
3. VS Code goes blank and on restart of app shows that .js files are missing
4. Trigger reinstall from company portal, this might work if teams does not have write lock on shared dlls (guessing.
4. b restart computer, close teams on startup and trigger reinstall again

**Comment by joaomoreno** [comment]
> Let company portal push an update from windows store

Company Portal should not push an update while the app is running. Please file an issue for them to look into that.
