### ISSUE TITLE
type filtering on intersection types

### ISSUE THREAD

**Issue by unional** [Microsoft/vscode#18546]
- VSCode Version: 1.8.1

```ts
interface X {  a: string,  b: number }
interface Y {  a: number,  b: string }
function foo(_option: X | Y) { }
foo({
  a: 'x',
  b: 'y'  // incorrect, needs number
})
```

It would be godsends if after typings `{ a: 'x'`, the completion shows `b: number`.
Currently, it shows `b: string | number`

`ts language service` can correctly detect the above is incorrect.
![image](https://cloud.githubusercontent.com/assets/3254987/21954739/5d8e973c-da0f-11e6-8600-b31da45624e7.png)

So the capability of determining which type the `_option` currently fits to is in place.

From the message in the dialog, it seems like it tries to match `b` before match `a`.

**Comment by unional** [comment]
A slightly more complicated case:

```ts
```ts
interface X {
  a: string,
  b: { 
    c: string,
    d: number
  }
}
interface Y {
  a: number,
  b: {
    c: number,
    e: number
  }
}
function foo(_option: X | Y) { }
foo({
  a: 'x',
  b: {
    c: 'y',
    // caret here
  }
})
```
The competetion should show `d: number` and not `e: number` as the shape of the object already ruled out `Y`.

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript#13541
