### ISSUE TITLE
Wrong position of context menu modal when Primary Side Bar in the left

### ISSUE THREAD

**Issue by evgeniyworkbel** [microsoft/vscode#185483]
Type: <b>Bug</b>

It causes to unexpected behavior: if click some bar button or "right" click on filenames, dirnames then automatically it chooses some menu option because of the wrong position of context menu or another reason.

1. Open some project into VSCode
2. Move Side Bar Left
3. Click right mouse button on file name or dirname

1. Open some project into VSCode
2. Move Side Bar Left
3. Click left mouse button on Settings below button on panel 

Expected behavior:
Mouse button clicking does not cause any actions automatically - I wanna choose option by myself

Actual behavior:
Mouse button clicking causes actions automatically

VS Code version: Code 1.79.2 (695af097c7bd098fbf017ce3ac85e09bbc5dda06, 2023-06-14T08:59:55.818Z)
OS version: Linux x64 5.19.0-43-generic snap
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz (8 x 3204)|
|GPU Status|2d_canvas: unavailable_software<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>opengl: disabled_off<br>rasterization: disabled_software<br>raw_draw: disabled_off_ok<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software<br>webgpu: disabled_off|
|Load (avg)|1, 1, 1|
|Memory (System)|15.32GB (9.68GB free)|
|Process Argv|--no-sandbox --force-user-env --unity-launch --crash-reporter-id cd74b515-2fd0-43e5-994b-0c2eab3ba858|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|wayland|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|2.4.0
vscode-html-css|ecm|1.13.1
prettier-vscode|esb|9.13.0
markdown-preview-enhanced|shd|0.6.8
volar|Vue|1.8.0
vscode-import-cost|wix|3.3.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
282f8724:30602487
pyind779:30671433
f6dab269:30613381
pythonsymbol12:30671437
showlangstatbar:30737416
vsctsb:30748421
pythonms35:30701012
03d35959:30757346
pythonfmttext:30731395
pythoncmvfstrcf:30756944
fixhidewlkth:30730051
hideindicator:30766889
pythongtdpath:30769146
i26e3531:30769768
e440d664:30770001
pythondjangotscf:30768920

```

</details>

**Comment by gjsjohnmurray** [comment]
Did you mean "right" rather than "left"? If so, see #167941 for a probable duplicate.

**Comment by evgeniyworkbel** [comment]
> Did you mean "right" rather than "left"? If so, see #167941 for a probable duplicate.

Referenced issue makes sense for me. Author recommended change `Title Bar Style` setting in `Window` category to `native` value. But for me issue was resolved setting from `native` to `custom` value.

i appreciate you for help and my issue might be closed
