### ISSUE TITLE
Integrated terminal Issue.

### ISSUE THREAD

**Issue by Mr-Unforgettable** [microsoft/vscode#185469]
Type: <b>Bug</b>

Version: 1.79.2
Commit: 695af097c7bd098fbf017ce3ac85e09bbc5dda06
Date: 2023-06-14T08:59:55.818Z
Electron: 22.5.7
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Linux x64 5.19.0-45-generic

### Description

When attempting to start or restart Visual Studio Code (VSCode) on a Linux system running on a virtual machine, an error message is encountered stating "PTY Host Unresponsive." This issue prevents the successful launch of VSCode and hinders the user's ability to use the editor effectively.

### Prerequisites

- Linux operating system installed on a virtual machine.
- Visual Studio Code version 1.79.2.

### Steps to Reproduce

1. Open a terminal window on your Linux system.

2. Ensure that Visual Studio Code is not currently running. If it is, close the application completely.

3. Execute the following command in the terminal to launch VSCode:

   ```bash
   code
   ```

4. Observe the terminal output and check for any error messages.

### Expected Behavior

After executing the `code` command, Visual Studio Code should start without any errors and open the editor interface.

### Actual Behavior

Instead of launching successfully, the following error message appears in the bottom right hand corner of the vscode

```
PTY Host Unresponsive ...
```

VS Code version: Code 1.79.2 (695af097c7bd098fbf017ce3ac85e09bbc5dda06, 2023-06-14T08:59:55.818Z)
OS version: Linux x64 5.19.0-45-generic
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (4 x 1799)|
|GPU Status|2d_canvas: unavailable_software<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>opengl: disabled_off<br>rasterization: disabled_software<br>raw_draw: disabled_off_ok<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software<br>webgpu: disabled_off|
|Load (avg)|1, 1, 1|
|Memory (System)|3.82GB (0.93GB free)|
|Process Argv|. --crash-reporter-id 5c1a1847-c246-4f93-bb39-4b08c2bc009a|
|Screen Reader|no|
|VM|100%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|wayland|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|2.4.0
prettier-vscode|esb|9.13.0
theme-monokai-pro-vscode|mon|1.2.1
cmake-tools|ms-|1.14.33
cpptools|ms-|1.15.4
cpptools-extension-pack|ms-|1.3.0
material-icon-theme|PKi|4.28.0
cmake|twx|0.0.17

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscorecescf:30445987
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
vscccc:30610679
282f8724:30602487
pyind779:30671433
f6dab269:30613381
pythonsymbol12:30671437
2i9eh265:30646982
showlangstatbar:30737416
vsctsb:30748421
pythonms35:30701012
a2ce3375:30757347
pythonfmttext:30731395
pythoncmvfstrcf:30756944
fixhidewlkth:30730051
hideindicator:30766889
pythongtdpath:30769146
dh2dc718:30770000

```

</details>

**Comment by DeleteMetaInf** [comment]
I’m having the same issue. ‘The connection to the terminal’s pty host process is unresponsive’

This only started happening after the latest update, 1.79.2. Something in the update must’ve broken the terminal for a lot of users.

**Comment by Jamie1606** [comment]
I am also having the same issue. This issue only occurs after updating to the latest update (May 2023). There is no extension installed and I have also tried to reinstall VS Code. It is fine on February 2023 version.
Version: 1.79.2 (user setup)
Commit: 695af097c7bd098fbf017ce3ac85e09bbc5dda06
Date: 2023-06-14T08:57:04.379Z
Electron: 22.5.7
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Windows_NT x64 10.0.22621

**Comment by Mr-Unforgettable** [comment]
It is happening in my windows environment as well after the update. It looks like there is indeed some issues with the integrated terminal of this particular version of vscode. So far temporary work around is to just revert back to previous version. If you don't vs code to update itself to this version then just change the update settings of vscode to manual.
