### ISSUE TITLE
Feature Request: an API to programmatically set language mode

### ISSUE THREAD

**Issue by iliazeus** [microsoft/vscode#185440]
The feature to set language mode programmatically would be beneficial for extensions like https://github.com/ahebrank/vscode-yaml2json that convert the current document to a different language.

Right now, the only semi-reliable way to do this seems to be renaming the opened file, changing its extension. But this does not really work if the file has not been saved yet, or if detection of the language in question does not depend of the extension.

**Comment by ArturoDent** [comment]
Does this work for you - to change the active editor language mode:

```javascript
await vscode.languages.setTextDocumentLanguage(vscode.window.activeTextEditor.document, 'css');
```

**Comment by iliazeus** [comment]
@ArturoDent my bad, I totally missed that in the docs
