### ISSUE TITLE
tsconfig.json extends jump to definition doesn't work

### ISSUE THREAD

**Issue by tjx666** [microsoft/vscode#185453]
@mjbvz 

When a tsconfig.json extends another package and the package is installed as system soft link for example install by pnpm, the extends `jump to definition` doesn't work.

If I install the node_moduels by npm, the `jump to definition` will work, but not for pnpm which use symblic links

<img width="1440" alt="image" src="https://github.com/microsoft/vscode/assets/41773861/9a6e76bc-5eb5-45e3-807a-fc9498e4d5e8">

reproduce:

1. git clone git@github.com:tjx666/tsconfig-extends-issue.git
2. pnpm install
3. open `node_modules/@yutengjing/tsconfig-node/tsconfig.json`
4. `cmd + click` on extends path: `"@yutengjing/tsconfig-base/tsconfig.json`
5. will notify `Failed to resolve @yutengjing/tsconfig-base/tsconfig.json as module`

```
Version: 1.79.2
Commit: 695af097c7bd098fbf017ce3ac85e09bbc5dda06
Date: 2023-06-14T08:58:33.551Z
Electron: 22.5.7
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Darwin arm64 22.5.0
```

**Comment by mjbvz** [comment]
This is because pnpm installs packages to different paths. The proper fix would be to try to resolve the package to get the correct path but I don't think it's worth it for a minor feature like this

**Comment by tjx666** [comment]
But the tsc can resolve the path correctly, maybe this is not implemented by the ts lsp? @mjbvz
