### ISSUE TITLE
Integrated terminal does not render Truecolor.

### ISSUE THREAD

**Issue by jordwalke** [microsoft/vscode#18544]
- VSCode Version:
Insiders build as of now.
- OS Version:
mac Sierra

Steps to Reproduce:

1.
`curl https://raw.githubusercontent.com/JohnMorales/dotfiles/master/colors/24-bit-color.sh > testColors.sh`
2. `sh testColors.sh`

You will see that it does not render all of the colors, and instead appears to only render 256.

**Comment by Tyriar** [comment]
Created upstream issue https://github.com/sourcelair/xterm.js/issues/484

**Comment by Tyriar** [comment]
Related https://github.com/Microsoft/vscode/issues/24620

**Comment by joerideg** [comment]
Hi,
https://github.com/xtermjs/xterm.js/pull/1895 
this was merged 27days ago. Any clue when this would hit vscode?
cheers

**Comment by Tyriar** [comment]
@joelday because of the remote release this was too risky of a change to pull in for April (there are also still bugs around it that need to be fixed). It will likely get pulled in for the May release.
