### ISSUE TITLE
Add easy copy/paste in vscode terminal like in BlackBox terminal

### ISSUE THREAD

**Issue by sandenbergmelo** [microsoft/vscode#185451]
[BlackBox terminal](https://gitlab.gnome.org/raggesilver/blackbox) has the option to active an easy copy & paste mode, this allows to use ctrl+c/ctrl+v instead of using ctrl+shit+c/ctrl+shift+v to copy and paste in the terminal.
![image](https://github.com/microsoft/vscode/assets/77549672/9075a464-ddbb-46e6-9c70-66bfeffeceab)

It would be useful if vscode had this option too.

**Comment by meganrogge** [comment]
I use ctrl+c and ctrl+v to copy/paste in the terminal. 

Do you know why you cannot?

there's also `terminal.integrated.rightClickBehavior`
