### ISSUE TITLE
Account sync problem

### ISSUE THREAD

**Issue by ViniciusRed** [microsoft/vscode#185448]
Type: <b>Bug</b>

When connecting the account to sync and closing Visual Studio Code - Insiders and opening the account again, I am logged out

VS Code version: Code - Insiders 1.80.0-insider (61ba389b0a7108af0411c73ab30c7e4350051645, 2023-06-16T09:47:52.031Z)
OS version: Linux x64 6.3.8-273-tkg-bmq
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Celeron(R) CPU  N3010  @ 1.04GHz (2 x 2240)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: disabled_off<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|3, 3, 3|
|Memory (System)|7.19GB (2.83GB free)|
|Process Argv|--crash-reporter-id 11e64e2f-d22b-4e89-ace1-49fc2b734c9c|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|undefined|
|XDG_CURRENT_DESKTOP|undefined|
|XDG_SESSION_DESKTOP|undefined|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (42)</summary>

Extension|Author (truncated)|Version
---|---|---
flutter-snippets|ale|3.0.0
jsoncrack-vscode|Ayk|1.0.8
vscode-mysql-client2|cwe|6.5.3
dart-code|Dar|3.67.20230613
flutter|Dar|3.67.20230601
fastcompare|Dav|1.1.1
vscode-eslint|dba|2.4.0
EditorConfig|Edi|0.16.4
vscode-rojo|eva|2.1.2
vscode-yarn|gam|2.1.0
vscode-github-actions|git|0.25.7
vscode-pull-request-github|Git|0.67.2023061509
google-translate|han|1.2.8
vscode-lottie|lot|1.0.5
vscode-docker|ms-|1.25.1
vscode-language-pack-pt-BR|MS-|1.79.2023061409
csdevkit|ms-|0.1.103
csharp|ms-|2.0.212
vscode-dotnet-runtime|ms-|1.6.0
vscodeintellicode-csharp|ms-|0.1.9
isort|ms-|2023.9.11661018
python|ms-|2023.11.11671008
vscode-pylance|ms-|2023.6.21
jupyter|ms-|2023.6.1001691100
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.15
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-slideshow|ms-|0.1.5
remote-containers|ms-|0.296.0
live-server|ms-|0.5.2023061501
vscode-selfhost-test-provider|ms-|0.3.15
rust-analyzer|rus|0.4.1554
sourcepawn-vscode|Sar|5.3.10
vue-preview|Sim|1.7.3
source-engine-support|ste|0.12.3
autoimport|ste|1.5.4
tauri-vscode|tau|0.2.6
adb-interface-vscode|vin|0.22.2
intellicode-api-usage-examples|Vis|0.2.7
vscodeintellicode|Vis|1.2.30
vscode-icons|vsc|12.4.0
volar|Vue|1.8.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythontb:30258533
pythonptprofiler:30281269
vshan820:30294714
vscod805:30301674
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30404738
py29gd2263cf:30763247
vscaac:30438845
vsclangdf:30492506
c4g48928:30535728
dsvsc012:30540252
pynewext54:30618038
pylantcb52:30590116
pyind779:30611226
pythonsymbol12:30651887
showlangstatbar:30737417
pythonms35:30671666
pythonfmttext:30716741
pythoncmvfstr:30726892
fixshowwlkth:30724385
showindicator:30766888
pythongtdpath:30726887
i26e3531:30769768
gsof2:30767485
dh2dc718:30770000
pythonidxpt:30768918
pythondjangots:30768917
pythonnoceb:30766855
h7j2d465:30769890

```

</details>

**Comment by TylerLeonhardt** [comment]
What Desktop environment do you use? 

We recently changed what we use to store secrets and are compiling new docs to reflect. 

Can you take a look at these docs here:

https://github.com/microsoft/vscode-docs/blob/vnext/docs/editor/settings-sync.md#troubleshooting-keychain-issues

My guess is that you're seeing

https://github.com/microsoft/vscode/issues/185212

**Comment by ViniciusRed** [comment]
I use openbox and I've never had a problem, only now that I have this problem

**Comment by TylerLeonhardt** [comment]
@ViniciusRed As I said above, We recently changed what we use to store secrets. It's possible that this change caused your problem. I linked docs and a possible related issue. Let me know if that solution works for you.

**Comment by ViniciusRed** [comment]
I already looked at the documentation but it didn't solve it but I already found the problem

**Comment by TylerLeonhardt** [comment]
What was the problem? We would love to expand the docs.

**Comment by ViniciusRed** [comment]
the problem is related to the installation of the system
