### ISSUE TITLE
Jump to matching bracket no longer moves the editor's viewport to the cursor

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#18540]
- VSCode Version: Code - Insiders 1.9.0-insider (2cdc2b3da8f0fd5322b48747241584cf9dd98f8f, 2017-01-13T07:03:18.620Z)
- OS Version: Linux x64 4.8.0-32-generic
- Extensions:

|Extension|Author|Version|
|---|---|---|
|EditorConfig|EditorConfig|0.3.4|
|lorem-ipsum|Tyriar|1.0.0|
|theme-glacier|Tyriar|0.0.10|
|vscode-svgviewer|cssho|1.3.0|
|python|donjayamanne|0.5.5|
|gitlens|eamodio|1.4.1|
|tslint|eg2|0.8.1|
|git-project-manager|felipecaputo|1.0.1|
|Theme-Wombat|gerane|0.0.2|
|md-navigate|jrieken|0.0.1|
|Go|lukehoban|0.6.50|
|vscode-scss|mrmlnc|0.6.0|
|csharp|ms-vscode|1.6.2|
|seti-icons|qinjia|0.1.3|
|java|redhat|0.0.8|
|annotator|ryu1kn|0.10.1|

---

Steps to Reproduce:

1. Open a TS/JS file with a large function
2. Put the cursor on the opening `{` of the function
3. Trigger `editor.action.jumpToBracket`, notice the editor's viewport isn't moved to the new cursor position

**Comment by alexandrudima** [comment]
Fixed via bda6cb768e0a8fe61840632a992ef87559d44989

**Comment by jhasse** [comment]
This is happening again for me in 1.16.0. I've tried with smooth scrolling on and off.

**Comment by alexandrudima** [comment]
@jhasse Yes, it regressed again ... it is already fixed in insiders. See #32597

**Comment by jhasse** [comment]
Ah, I've missed that. Thanks :)
