### ISSUE TITLE
Hacker got in thru apps and controls my phone and tv and e erything else. Please help me show you I diont code at all I'm screwed

### ISSUE THREAD

**Issue by Fungus46** [microsoft/vscode#185481]
![Screenshot_2023-06-18-03-28-02-137](https://github.com/microsoft/vscode/assets/136956918/f3d1d0e4-1273-4105-883e-396362da29ea)
![Screenshot_2023-06-18-03-27-53-837](https://github.com/microsoft/vscode/assets/136956918/93008c38-97ea-488b-8688-e3dc6da7bbdd)

Version: 1.80.0-insider
Commit: 61ba389b0a7108af0411c73ab30c7e4350051645
User Agent: Mozilla/5.0 (Linux; Android 12; T602DL) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Mobile Safari/537.36 EdgA/114.0.1823.43
Embedder: codespaces

**Comment by Fungus46** [comment]
He's mocking my ip address my wifi and Google and my phone company all thru apk I guess but I can't reboot because it won't even advance. I'm stuck with no updates as well

**Comment by EdricCantu** [comment]
Not sure what this has to do with VSCode, but if you want to be more careful, you can try turning off your router and removing your sim card to prevent any further remote access. if this is a security issue with VSCode, I'd recommend going through the [Microsoft Security Response Center](https://msrc.microsoft.com/create-report). Also, unless your phone is rooted, it would be of better assistance to show the "User Apps" tab.
