### ISSUE TITLE
[folding] Support single shortcut for toggling fold/unfold

### ISSUE THREAD

**Issue by atlib77** [microsoft/vscode#18549]
Currently we have the possibility to fold and unfold using different shortcuts. 

I would like to have "editor.toggleFold" option as well so I can have a single shortcut for that (e.g. Ctrl+M, Ctrl+M as in VS.NET)

E.g.:
{
        "key": "ctrl+1",
        "command": "editor.toggleFold",
        "when": "editorTextFocus"
    }

That way, I only have to remember a single shortcut for this and matches various other functionality in vscode. (e.g. toggle line comments/block comments, etc).

A toggle case (upper and lower) would also be nice as mentioned here. https://github.com/Microsoft/vscode/issues/16895

**Comment by rafaelrinaldi** [comment]
I would love to support this in order to improve the Vim mode. If you are okay with supporting this feature I could try to submit a PR (instructions to where I should start are welcome to).

**Comment by waynebloss** [comment]
@rafaelrinaldi Here is a VSCode extension that adds extra commands for code-folding - https://github.com/dakaraphi/vscode-extension-fold

It doesn't yet include a command to toggle foldable code. However, it should be trivial to add a new command to that extension or use it as a reference to build your own extension.

**Comment by freMea** [comment]
Having to remember all those key to fold/unfold makes harder to use keyboard shortcut and be efficient.

I suggest to implement all of this [vscode-extension-fold](https://github.com/dakaraphi/vscode-extension-fold) extension features too:

- Fold All Same Level as Cursor
- Fold All with Selected Text
- Fold All keep Selected Text
- Fold All keep Cursor Line

But with the toggle feature added to unfold too.

**Comment by coderjz** [comment]
I would also like to be able to just toggle with a single key press; for myself in vim mode I'd use <space>f to either fold all or unfold all.

**Comment by dwaxe** [comment]
Found the folding code here (https://github.com/Microsoft/vscode/blob/master/src/vs/editor/contrib/folding/folding.ts)

**Comment by raptor235** [comment]
1+

**Comment by lopugit** [comment]
has this been added? I swear I used to use 1 keyboard shortcut for this

**Comment by snielsson** [comment]
+1

**Comment by xfudox** [comment]
Has this been implemented yet?

**Comment by lucianoratamero** [comment]
+1

**Comment by lvadla** [comment]
+1

**Comment by lschuft** [comment]
+1, very interested in this feature, coming from VS .NET.

**Comment by stdvg** [comment]
+1

**Comment by ShadeBlack** [comment]
I would also like this, coming from cloud9 ide, which supported inline toggle folding.

**Comment by vhnatyk** [comment]
+1

**Comment by babinc** [comment]
Not having a single command for toggle fold irritates me. VSCode not as good as VIM yet.

**Comment by calebmeyer** [comment]
@babinc VS Code is already better than vim in many ways (vim doesn't and can't have many of the awesome graphical tools we have). On the folding front, VS Code may never be better than vim, per https://github.com/microsoft/vscode/issues/22276#issuecomment-302061827

I wish we had a single editor that could do everything at a perfect level, but there's tradeoffs everywhere. One of the largest tradeoffs is choosing where to spend your time as a dev team. This is one of the places the dev team has chosen not to spend time yet. If I knew the API better, I'd contribute this myself, even though I'm a (very) occasional user of VS Code.

**Comment by hinell** [comment]
Would be really nice feature. Currently we are forced to use couple button to do the same work.

**Comment by kopacabana** [comment]
+1

**Comment by nsstrickland** [comment]
I found and came to love this functionality in Powershell ISE, I was dismayed to find that it is not also in Code

**Comment by LiamEderzeel** [comment]
+1

**Comment by Garviell** [comment]
I don't know why but needing to use a different button for folding and unfolding makes me irrationally annoyed.

I really hope you figure out a way to get this in here despite the design hurdles.

**Comment by chipbite** [comment]
I hate to be that +1 / me too guy, but this is really a pain in my fingers. 

Would just love to see this implemented!

**Comment by aeschli** [comment]
I added a new shortcut `Ctrl + K Ctrl + K`
