### ISSUE TITLE
Built-in environment variables overriding those set by user

### ISSUE THREAD

**Issue by User087** [microsoft/vscode#185428]
I'm running a python script that loads environment variables from a `.env` file using `load_dotenv()` from the `python-dotenv` library. One of the variables specified in the `.env` file is named `USERNAME`, which appears to also be the name of [a built-in environment variable in VSCode](https://code.visualstudio.com/docs/editor/variables-reference#_environment-variables). Even after loading the environment variables from the `.env` file, I find the `USERNAME` variable is still set to the built-in value, not that which I specifed in the `.env` file.

Is there no option to give priority to the variables loaded from a `.env` file or otherwise specified when running a script over the built-in ones, so that the latter don't override the former? Lack of such an option can be a hindrance to running code developed in other environments, as it means having to read up on built-in environment variables in VSCode and rename any clashes in your `.env` file any time you want to run code there, which clearly goes against code portability.

Steps to Reproduce:

1. Make a `.env` file with a variable `USERNAME` specified within (and given a value different to that of the built-in `${env:USERNAME}`
2. Run the following Python code:
```
from dotenv import load_dotenv
load_dotenv()
username = os.environ.get("USERNAME")
print(username)
```
3. Observe the output is different to the value you specified in the `.env` file

**Comment by roblourens** [comment]
That doc is not saying that we set the `USERNAME` variable, it's just showing how to reference that variable in vscode features that resolve variable references.

This would be an issue with your code or configuration

**Comment by User087** [comment]
Whatever the case, it remains that when running the code above, the result is the USERNAME variable as set in VSCode, not as set in the `.env` file. How to fix that?
