### ISSUE TITLE
Auto save settings

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#1854]
- [x] win @alexandrudima 
- [x] mac @joaomoreno 
- [x] linux @isidorn 

The auto save behaviour is now configurable via settings and moved out of the File menu.
* verify the setting is migrated to your settings file when having it enabled the old way
* verify you can configure auto save delay in seconds
* verify you can configure auto save on focus lost and verify it works as expected
* verify you can configure auto save per workspace settings too
* verify files are saved on exit immediately independent from the auto save configuration

**Comment by isidorn** [comment]
I did not verify that the setting gets migrated on linux since I am not sure how to have it before for my alpha installation

**Comment by bpasero** [comment]
@isidorn sorry I should have mentioned that, just SHUTDOWN code and add the following to storage.json in /home/ticino/.config/Code-Development: autoSaveDelay: 1000

**Comment by isidorn** [comment]
:heavy_check_mark:

**Comment by alexandrudima** [comment]
Nice!
