### ISSUE TITLE
Syntax selection missing for new unsaved code

### ISSUE THREAD

**Issue by diaconu13** [Microsoft/vscode#18543]
- VSCode Version:1.81
- OS Version: win 10

Steps to Reproduce:

1. open new file
2. paste some js code
3. Format Document option missing from right click menu(since IDE does not know what kind of syntax you have and there is no option to select it)

**Comment by dbaeumer** [comment]
You can switch the language by clicking on the language indicator in the status bar (e.g in our example on Plain Text)

**Comment by diaconu13** [comment]
Thanks!
