### ISSUE TITLE
Window: single logic core full usage & memory usage grow uniformly

### ISSUE THREAD

**Issue by Lost-MSth** [microsoft/vscode#185420]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.79.2 & 1.80.0-insider
- OS Version: Windows 11   22631.1835

Steps to Reproduce:

1. Juse open vscode.

Hello. When opening the vscode, I see that my single logic core shows full usage in task manager. It's so strange so I use "Process Hacker" to see what happened. Well, "threads" shows `Code - Insiders.exe!cppgc::internal::WriteBarrier::DijkstraMarkingBarrierRangeSlow+0x6a69f0` occupys CPU so much and memory usage grows uniformly. In vscode's task manager, it shows the thread is `window [1] ...` and `window [2] ...` ( task manager window).

I think it is a bug in vscode 1.79.2. Additionally I install an insider version and find the same bug, so I am sure it is not due to my extensions.

**Comment by Lost-MSth** [comment]
![image](https://github.com/microsoft/vscode/assets/66946123/e1dfb50b-9c52-4774-980c-8cbfc129d12b)


The thread Stack shows:

![image](https://github.com/microsoft/vscode/assets/66946123/3c1193c1-fa6e-4ca6-a8f8-edf0178d3107)

It changes in real time and the last stationary one is `Code.exe!v8::Platform::SystemClockTimeMillis+0x102455
`.

**Comment by Lost-MSth** [comment]
OS is updated to `Windows 11 22631.1900 (beta channel)` and the problem still exists. Well, it occurs randomly. Yesterday it didn't happened but today it appeared again. I guess it is a bug of OS.

Same with issue https://github.com/microsoft/vscode/issues/185462.

**Comment by deepak1556** [comment]
Does this issue repro with latest stable `1.84` ? If it does, can you provide the command line of the process with high cpu usage.

**Comment by Lost-MSth** [comment]
Seem that I forget to report it. On Windows 11 `22635.2700`, it have not happened with VSCode `1.84.2`. Although I do not know the specific reason, I believe this problem has been solved. Thank you for your patience!
