### ISSUE TITLE
The facility for exposing default settings launch.json

### ISSUE THREAD

**Issue by mda-jobs** [microsoft/vscode#185485]
The official documentation for VS Code's built-in debugger doesn't provide comprehensive detail on the attributes exposed by Intellisense for launch.json. For example, showAsyncStacks is a boolean, for which no default is indicated. Neither symbols nor settings expose its value. 

For example, Intellisense does not expose an `address` attribute, contrary to the 'official' documentation, which asserts that remote debugging is baked into VS Code, and is specified with the `address` attribute. Without a facility to expose internals, it's difficult to know if this was simply an oversight in the preparation of the Intellisence database, or if VS Code doesn't recognize an `address` attribute, if included in launch.json. Intellisense exposes the following 48 attributes: 

args, attachSimplePort, autoAttachChildProcesses, cascadeTerminateToConfigurations, console, customDescriptionGenerator, customPropertiesGenerator, debugServer, enableContentValidation, enableTurboSourcemaps, env, envFile, internalConsoleOptions, killBehavior, linus, localRoot, name, nodeVersionHint, osx, outFiles, outputCapture, pauseForSourceMap, postDegugTask, preLaunchTask, presentation, profileStartup, program, remotesRoot, request, resolveSourceMapLocations, restart, runtimeArgs, runtimeExecutable, runtimeSourcemapPausePatterns, runtimeVersion, serverReadyAction, showAsyncStacks, skipFiles, smartStep, sourceMapPathOverrides, sourceMapRenames, sourceMaps, supressMultipleSessionWarning, timeout, timeouts, trace, type, windows

BTW, the attribute, runtimeArgs, appears to be misnamed for its intended purpose: to include command-line arguments. runtimeArgs has the same symantics as Args (args are passed at runtime). `commandOptions` would be more appropriate.

-MDA
michael@speedroi.com

**Comment by connor4312** [comment]
> For example, Intellisense does not expose an address attribute, contrary to the 'official' documentation, which asserts that remote debugging is baked into VS Code, and is specified with the address attribute.

I do not reproduce this:

<img width="531" alt="image" src="https://github.com/microsoft/vscode/assets/2230985/2e0c2e1b-7068-4d46-9795-f1d14a037243">


The complete set of options documentation can be found here: https://github.com/microsoft/vscode-js-debug/blob/main/OPTIONS.md. This is also linked to in the 2nd paragraph of [options documentation](https://code.visualstudio.com/docs/nodejs/nodejs-debugging#_launch-configuration-attributes) on the docs site.
