### ISSUE TITLE
[Bug] No syntax highlighting for `.cjs` `.vue` files in the search editor

### ISSUE THREAD

**Issue by wenfangdu** [microsoft/vscode#185430]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.79.2
- OS Version: macOS 13

Steps to Reproduce:
![image](https://github.com/microsoft/vscode/assets/28700378/7b9705c7-6223-4dbd-9592-05facd3b8da4)
![image](https://github.com/microsoft/vscode/assets/28700378/5246bfd0-bcbc-4466-a47a-7c53058bf4e9)
`.js` file has syntax highlighting:
![image](https://github.com/microsoft/vscode/assets/28700378/5826622d-c073-47ff-835c-232ff7193366)

**Comment by andreamah** [comment]
I _believe_ that the syntax highlighting comes from whether you have that language extension installed. Is there syntax highlighting when you open a `.vue` or `.cjs` file?

**Comment by wenfangdu** [comment]
@andreamah `.vue` highlighting requires an extension and I've installed it, `.cjs` highlighting is built-in and doesn't require extensions, both are highlighted when you open them but are not highlighted in the search editor.

**Comment by andreamah** [comment]
Just checked, and it looks like syntax highlighting is dictated using a fixed set of mappings. I could probably add `cjs` since it's built-in but we only support built-in languages for syntax highlighting for this; sorry about that!

**Comment by wenfangdu** [comment]
@andreamah You mean even if I installed the syntax highlighting extension for `.vue` files, they still won't work in the search editor? That seems like a bug.

**Comment by andreamah** [comment]
You can create a feature request to support non-default syntax highlighting for the search editor and we can put it as a backlog candidate to see whether enough people would want to see it. 

Unfortunately, using a fixed list is intentional, as the grammar for the search editor cannot be dynamically changed based on which extensions are installed. We would need to do a fairly large restructuring (integrate search editor highlighting into core) to get this working.

**Comment by wenfangdu** [comment]
@andreamah Feature request opened here: https://github.com/microsoft/vscode/issues/185717

**Comment by eleanorjboyd** [comment]
Thank you for submitting your feature request and everyone who considered it! Unfortunately, this issue did not receive enough votes over the allotted time, and so we are closing the issue.

**Comment by RedCMD** [comment]
@wenfangdu could ask the `vue` extension to add a `searchResults` injection

like so
![Image](https://github.com/user-attachments/assets/1115e3cb-4071-4293-a6e1-55e75a416be7)

https://github.com/microsoft/vscode/blob/main/extensions/search-result/syntaxes/searchResult.tmLanguage.json
