### ISSUE TITLE
Unable to use TextEditorEdit.delete() as first class function

### ISSUE THREAD

**Issue by Jasonlhy** [Microsoft/vscode#18559]
- VSCode Version: 1.8.1
- OS Version: Windows 10

I was writing an extension yesterday and faced an interesting error. I tried to use TextEditorEdit.delete() as first class function inside `.forEach` but it just failed with message `Running the contributed command:'extension.hungryDelete' failed.` I solved the problem with explicitly specifying the callback function. Is it a bug or just a feature of typescript?

Steps to Reproduce:
1. Download the source code at `https://github.com/Jasonlhy/VSCode-Hungry-Delete` and open it in VSCode
2. Replace

```ts
let result = editor.edit((editorBuilder) => {
            deleteRanges.forEach((deleteRange) => {
                 editorBuilder.delete(deleteRange);
            });
        });
```

with

```ts
let result = editor.edit((editorBuilder) => {
           deleteRanges.forEach(editorBuilder.delete);
        });
```

3. `npm install` and run the project
4. Add some text in the testing environment
```
    222

    333
```
5. Press `ctrl + backspace` to execute the command

**Comment by jrieken** [comment]
I cannot repo using this snippets. Please update this issue with more precise steps and/or the full error message (use debugger and pause exception)

```
if (vscode.window.activeTextEditor) {
            vscode.window.activeTextEditor.edit(builder => {
                builder.delete(vscode.window.activeTextEditor.selection);
            })
       }
```

**Comment by Jasonlhy** [comment]
@jrieken  Your snippet works because you explicitly specify the parameter of `delete()`. If you pass `delete()` into a higher order function, it will fail just like me

```ts
 var higherOrderFunction = function(deleteFunction){
            deleteFunction(window.activeTextEditor.selection);
        }

        if (window.activeTextEditor) {
            window.activeTextEditor.edit(builder => {
                higherOrderFunction(builder.delete);
            })
        }
```

I tried to step into with the debugger.
1. Set the breakpoint here
![1](https://cloud.githubusercontent.com/assets/1687930/22004717/15a99930-dc99-11e6-8a53-6901180f3411.png)

2. Step into until this line
![2](https://cloud.githubusercontent.com/assets/1687930/22004720/1734e462-dc99-11e6-99a8-24efb170e826.png)

3. If I click step into or step over, the debugger directly jump to this line
![3](https://cloud.githubusercontent.com/assets/1687930/22004721/18b7b5e4-dc99-11e6-8487-b0405ef5ffe9.png)

4. And the warning prompted up
![4](https://cloud.githubusercontent.com/assets/1687930/22004723/1b03ba8c-dc99-11e6-84b7-31bcc9881734.PNG)

**Comment by jrieken** [comment]
The `delete`-function is a member of the builder and passing it around the way you do makes it being invoked without it original `this`. See https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/this and  https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/bind and 

<img width="698" alt="screen shot 2017-01-17 at 08 42 41" src="https://cloud.githubusercontent.com/assets/1794099/22011764/fcd5b0ae-dc90-11e6-9d17-3926fc74360a.png">

**Comment by Jasonlhy** [comment]
@jrieken Thanks so much for your help, much appreciated!
