### ISSUE TITLE
gopls install fail

### ISSUE THREAD

**Issue by KimLyu** [microsoft/vscode#185541]
Type: <b>Bug</b>

Go Extension 
The "gopls" command is not availabe. Run "go install -v golang.org/x/tools/gopls@latest" to install，
after press install, it shows sysprep dialog.

VS Code version: Code 1.79.2 (695af097c7bd098fbf017ce3ac85e09bbc5dda06, 2023-06-14T08:57:04.379Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-10400 CPU @ 2.90GHz (12 x 2904)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.82GB (21.30GB free)|
|Process Argv|--crash-reporter-id e8c5de84-4829-43c3-887c-3e10976a9ea1|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (35)</summary>

Extension|Author (truncated)|Version
---|---|---
project-manager|ale|12.7.0
toml|be5|0.6.0
npm-intellisense|chr|1.4.4
path-intellisense|chr|2.8.4
gitignore|cod|0.9.0
doxdocgen|csc|1.4.0
api-blueprint-viewer|dev|0.9.4
githistory|don|0.6.20
gitlens|eam|14.0.0
prettier-vscode|esb|9.13.0
docker-explorer|for|0.1.7
docker-extension-pack|for|0.0.1
go|gol|0.39.0
search-node-modules|jas|1.3.0
vscode-nuget-package-manager|jmr|1.1.6
vscode-language-babel|mgm|0.0.39
vscode-html-format|moh|0.1.2
vscode-docker|ms-|1.25.1
vscode-language-pack-zh-hant|MS-|1.79.2023061409
remote-wsl|ms-|0.79.5
sftp|Nat|1.16.3
indent-rainbow|ode|8.3.1
docker-compose|p1c|0.5.0
java|red|1.19.0
vscode-community-server-connector|red|0.26.12
vscode-rsp-ui|red|0.24.8
blueprint|tea|3.0.0
vscode-apielements|vnc|0.6.7
vscode-java-debug|vsc|0.51.0
vscode-java-pack|vsc|0.25.11
vscode-java-test|vsc|0.39.0
volar|Vue|1.8.0
vscode-typescript-vue-plugin|Vue|1.8.0
JavaScriptSnippets|xab|1.8.0
markdown-all-in-one|yzh|3.5.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627cf:30244335
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
3biah626:30602489
pyind779:30671433
89544117:30613380
pythonsymbol12:30671437
showlangstatbar:30737416
vsctsb:30748421
pythonms35:30701012
03d35959:30757346
pythonfmttext:30731395
pythoncmv:30756943
fixhidewlkth:30730051
hideindicator:30766889
pythongtdpath:30769146
e440d664:30770001

```

</details>

**Comment by lszomoru** [comment]
Please file an issue in the go extension's [repository](https://github.com/golang/vscode-go/issues). Thank you.
