### ISSUE TITLE
Extremely slow loading and operation

### ISSUE THREAD

**Issue by SkaterDad** [Microsoft/vscode#1855]
Initial loading of VS Code can take between 10 and 20 seconds.
The `Reload Window` command takes about 10 seconds to complete.

I've tried it from the installer and also building from source with similar problems.

CPU profiling shows `ChildProcess.spawn` is the biggest problem, which calls all the way down to `node.js _tickCallback`.  I'd be happy to email someone the profile if it would help.

I suppose this issue could be with node itself?  I'm at a loss, since VS Code works perfectly on my home computers which have no proxy.

**System Properties**
 * Windows 7 Enterprise SP1
 * Intel i5-4590, 8GB RAM, Samsung 950Pro SSD

**Corporate Environment**
 * Behind a NTLM proxy.  Have CNTLM installed with environment variables `http_proxy` and `https_proxy` pointing to it.  npm works fine with this setup.
 * Symantec Endpoint is installed also.

**Comment by bpasero** [comment]
@SkaterDad can you attach the profile dump?

**Comment by SkaterDad** [comment]
@bpasero Here you go!  I didn't realize you could attach files to Github issues.

[profiles.zip](https://github.com/Microsoft/vscode/files/82750/profiles.zip)

**Comment by bpasero** [comment]
@SkaterDad do you have extensions installed? Could you try the same thing with "code --disable-extensions"

**Comment by SkaterDad** [comment]
@bpasero There were no extensions installed on the 'built from source' profile.  I had the eslint extension installed in the other one, but the slowness predates that.

When typing `ext install`, there is about 5 seconds lag after i hit the space before `install` even shows up.

Just did a fresh install of Code v0.10.6 (including removing all the Code related folders from my `users` directory).
 * The app window opens up about 20 seconds after clicking the shortcut.
 * The editor shows up about 15-20 seconds later.
 * Adding `--disable-extensions` didn't affect these times.

Here is the new profile: 
[CPU-20160108T102601.zip](https://github.com/Microsoft/vscode/files/82943/CPU-20160108T102601.zip)

I'm not sure if this is related, since the version I built from source didn't give these errors (and was just as slow), but my Console log showed 2 of these:
```
ApplicationInsights:Sender [Error: connect ECONNREFUSED 23.102.160.172:80
    at Object.exports._errnoException (util.js:837:11)…]0: Error: connect ECONNREFUSED 23.102.160.172:80
    at Object.exports._errnoException (util.js:837:11)
    at exports._exceptionWithHostPort (util.js:860:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1060:14)length: 1__proto__: Array[0]
C:\Program Files (x86)\Microsoft VS Code\resources\app\node_modules\applicationinsights\Library\Log…:19 ApplicationInsights:Sender [Error: connect ECONNREFUSED 64.4.54.254:443
    at Object.exports._errnoException (util.js:837:11)
 …]0: Error: connect ECONNREFUSED 64.4.54.254:443
    at Object.exports._errnoException (util.js:837:11)
    at exports._exceptionWithHostPort (util.js:860:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1060:14)length: 1__proto__: Array[0]
```

**Comment by bpasero** [comment]
@SkaterDad can you do one of:
* https://code.visualstudio.com/Docs/supporting/FAQ#_how-to-disable-crash-reporting
* https://code.visualstudio.com/Docs/supporting/FAQ#_how-to-disable-telemetry-reporting

And see if it improves?

**Comment by SkaterDad** [comment]
@bpasero  Disabling telemetry got rid of my Console errors, but the startup & reload speeds weren't really affected.

Disabling crash reporting didn't have any discernible impact either.

**Comment by SkaterDad** [comment]
This may be useful: I opened up the `.build/electron` and opened `CodeOSS.exe`.  That took about 20 seconds to fully load.

**Comment by bpasero** [comment]
Any chance Symantec scans the exe heavily and slows loading down? Can you set it to ignore Code?

**Comment by SkaterDad** [comment]
Unfortunately our Symantec Endpoint is locked down heavily by corporate IT.  Certainly wouldn't surprise me if that was causing the problems.  I might have to try disconnecting from the network and attempt to kill the Symantec processes.

As a side note, I tried running the source-built VS Code with the latest Electron build and it didn't impact performance.

**Comment by SkaterDad** [comment]
I was unable to disable Endpoint, but I don't think it's the problem.

I installed VS Code on one of our Win Server 2012 R2 boxes (also runs Symantec) and it opens completely within 3 seconds.

Something on my Win 7 SP1 machine is the culprit.   Really, though, it seems like an Electron issue, so if you prefer I can submit an Issue there instead.

**Comment by bpasero** [comment]
@SkaterDad does a bare Electron application also take so long to open then?

**Comment by SkaterDad** [comment]
Yes it does.

**Comment by bpasero** [comment]
@SkaterDad I think under these circumstances you should report it against Electron and maybe include the CPU profile for them.

**Comment by SkaterDad** [comment]
I'll do that.  Thanks for your time and input :+1:
