### ISSUE TITLE
Scroll on treckpad

### ISSUE THREAD

**Issue by Nrjwolf** [Microsoft/vscode#18553]
I have wrong scroll with trackpad, it scrolling curcsor not scrollbar, so on mouse wheel it works fine, what I should to do to fix it? 

And with trackpad works fine if I use cntrl + trackpad

- VSCode Version: Code 1.8.1 (ee428b0eead68bf0fb99ab5fdc4439be227b6281, 2016-12-19T14:49:23.350Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

|Extension|Author|Version|
|---|---|---|
|csharp|ms-vscode|1.6.2|

---

Steps to Reproduce:

1.
2.

**Comment by alexandrudima** [comment]
@Nrjwolf Does this work for you in Chrome v53? VSCode is currently built on top of Chromium v53 and Chromium provides `wheel` events, which we listen to.

**Comment by alexandrudima** [comment]
Closing without further information. We cannot reproduce.
