### ISSUE TITLE
LINUX - VS CODE - UPDATE GITHUB CREDINTIALS

### ISSUE THREAD

**Issue by mgood7123** [microsoft/vscode#185529]
how do i update my github credentials?

i have accidentally put in the wrong PAT in the password field and i cannot update it to the correct PAT

**Comment by TylerLeonhardt** [comment]
Account icon -> the account -> Sign out

![image](https://github.com/microsoft/vscode/assets/2644648/12cac8f9-7f80-4314-a4d4-dc5bc93e1224)
