### ISSUE TITLE
Code Suggestions are stacked together and those are very difficult to see.

### ISSUE THREAD

**Issue by dhrubajyotifounderofDSoft** [microsoft/vscode#185572]
Does this issue occur when all extensions are disabled?: Yes/No
No

- VS Code Version: v1.79
- OS Version: Windows 11 22621.525

I was facing this bug for many days. The Code Suggestions are stacked together and those are very difficult to see.
![image](https://github.com/microsoft/vscode/assets/108980710/f08167e0-01bb-43be-bc58-da442730ddb9)

System specifications

```
Device name	DesktopDhrubajyotiDSoft
Processor	Intel(R) Pentium(R) CPU G3240 @ 3.10GHz   3.10 GHz
Installed RAM	4.00 GB
Device ID	0007FE93-19CB-4744-959B-5F7BE300C9CD
Product ID	00330-80000-00000-AA594
System type	64-bit operating system, x64-based processor
Pen and touch	No pen or touch input is available for this display
```

**Comment by dhrubajyotifounderofDSoft** [comment]
> Thanks for creating this issue! It looks like you may be using an old version of VS Code, the latest stable release is 1.79.2. Please try upgrading to the latest version and checking whether this issue remains.
> 
> Happy Coding!

These are the recent updates I did 👇
```
Version: 1.80.0-insider (user setup)
Commit: 73eb619afb87cab4aa83a569259c891b6983c11e
Date: 2023-06-19T05:35:37.388Z
Electron: 22.3.11
ElectronBuildId: 21658788
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Windows_NT x64 10.0.22621
```

**Comment by jrieken** [comment]
Please following the instructions [above](https://github.com/microsoft/vscode/issues/185572#issuecomment-1597424110) start with 1 and 2

**Comment by dhrubajyotifounderofDSoft** [comment]
Thank you @jrieken for your help. I used the 2) step and it worked. But for default and syncing and my account I also changed this setting in the `settings.json` file of User Settings.

![image](https://github.com/microsoft/vscode/assets/108980710/448c81fa-fca4-433b-8eb3-fd402435a9e1)
 and This is final result I got👇
![image](https://github.com/microsoft/vscode/assets/108980710/9d68fb51-24af-47eb-88ce-4c4fa3500f99)

**Comment by jrieken** [comment]
Thanks for reporting back. Closing this as question

**Comment by dhrubajyotifounderofDSoft** [comment]
Thank you! Nice to meet you!
