### ISSUE TITLE
Request for CDN Feature for winget installing VS Code

### ISSUE THREAD

**Issue by hayschan** [microsoft/vscode#185512]
### Issue Description
When using the `winget` package manager to install Microsoft Visual Studio Code, the package is downloaded from a US server `az764295.vo.msecnd.net` by default, resulting in issues for Chinese users. The download link is in the following format: `Downloading https://az764295.vo.msecnd.net/stable/695af097c7bd098fbf017ce3ac85e09bbc5dda06/VSCodeUserSetup-x64-1.79.2.exe`.

The problem lies in the fact that Chinese users often face timeout errors due to the Great Firewall (GFW), and are unable to download VS Code through `winget` without the use of a proxy.

```
Downloading https://az764295.vo.msecnd.net/stable/695af097c7bd098fbf017ce3ac85e09bbc5dda06/VSCodeSetup-x64-1.79.2.exe
  ▋                               2.00 MB / 88.6 MB
An unexpected error occurred while executing the command:
InternetReadFile() failed.
0x80072ee2 : unknown error
```

According to another issue “Make some China mirrors boost download speed“ #145128, when downloading VS Code through the web, the download occurs from the nearest Azure Content Delivery Network (CDN) server, including servers in China. By changing download server from `az764295.vo.msecnd.net` to `vscode.cdn.azure.cn`, the download speed is boosted from 6KB/s to 7MB/s.

However, the current `winget` installation method for VS Code does not utilize the CDN and always downloads from the default US server `az764295.vo.msecnd.net`. This limitation prevents Chinese users from accessing the software easily and efficiently.

### Expected Behavior
It would be greatly beneficial if the `winget` package manager could incorporate a CDN feature for Microsoft Visual Studio Code installations. By utilizing the CDN, the `winget` command should automatically download the package from the nearest Azure CDN server to the user's location, ensuring faster and more reliable downloads for Chinese users.

### Steps to Reproduce
1. Run the `winget install Microsoft.VisualStudioCode` command.
2. Observe that the package is downloaded from the default US server.

```
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://az764295.vo.msecnd.net/stable/695af097c7bd098fbf017ce3ac85e09bbc5dda06/VSCodeSetup-x64-1.79.2.exe
  █████████████▌                  40.0 MB / 88.6 MB
An unexpected error occurred while executing the command:
InternetReadFile() failed.
0x80072ee2 : unknown error
```

### Actual Behavior
The package is always downloaded from the US server, leading to difficulties and timeout errors for Chinese users.

### Additional Information
By introducing a CDN feature to the `winget` package manager, Chinese users would be able to download and install Microsoft Visual Studio Code more easily, without encountering network issues. This enhancement would greatly improve the user experience for Chinese developers who rely on `winget` for software installations.

Thank you for considering this feature request.

**Comment by joaomoreno** [comment]
Starting with 1.85, we will have a new CDN which works world wide: `vscode.download.prss.microsoft.com`. @lszomoru Leaving it up to you to adopt this in the winget registry, once we release 1.85.

**Comment by lszomoru** [comment]
The GitHub action that publishes the widget manifest uses the update service to get the location of the package, so we are all set. The VS Code Insiders manifest is already using [the new location](https://github.com/microsoft/winget-pkgs/blob/master/manifests/m/Microsoft/VisualStudioCode/Insiders/1.85.0/Microsoft.VisualStudioCode.Insiders.installer.yaml).

**Comment by dbaeumer** [comment]
Verified that `winget` uses vscode.download.prss.microsoft.com
