### ISSUE TITLE
Extensions cannot activate with allowJs compiler option

### ISSUE THREAD

**Issue by adelphes** [Microsoft/vscode#18550]
- VSCode Version: 1.8.1
- OS Version: Ubuntu 16, Linux x64

Steps to Reproduce:

1. Create a new extension using `yo generator-code`
2. Build, debug and activate the new extension to check it works.
3. Add a pure JavaScript (.js) file to the project.
4. As per the documentation, add the following to `compilerOptions` in *tsconfig.json*:

`"allowJs": true`

5. Relaunch the debugging session. The extension now fails to activate.
6. Remove the `allowJs` option from compilerOptions and restart debugging. The extension is able to activate again.

The errors reported in the debugger console when the extension fails to load always look like this:

> Activating extension myextension.foo failed: {1}.
> Activating extension myextension.foo failed:  undefined
> Here is the error stack:  undefined
> 

I've tried manually adding the `--allowJs` option into *.vscode/tasks.json* - with the same result.

**Comment by dbaeumer** [comment]
Did you generate a TS or JS extension when using yo

**Comment by adelphes** [comment]
It was a TS extension (otherwise the allowJs option would not be necessary).

I'm closing this because it turned out that the problem was due to the newly added file itself - an exception was being thrown during the loading of the JavaScript module.  
It's confusing that there's no error or stack trace to show this (as there normally is a node application). Maybe that should be created as a separate issue?
