### ISSUE TITLE
Can't start node debugger when "node" is a function in the shell

### ISSUE THREAD

**Issue by sjml** [Microsoft/vscode#18556]
- VSCode Version: 1.8.1
- OS Version: macOS 10.12.2

I recognize that I'm in "special snowflake" territory with my setup here, and definitely don't expect first-class support for what I'm doing, but it feels like the kind of thing VS Code could handle more gracefully than it currently does. Basically this is a stranger occurrence of #10571. 

The [zsh port of nvm](https://github.com/lukechilds/zsh-nvm) has a side effect of slowing down shell startups; to mitigate this, it has a lazy loading functionality that has node, npm, and any other installed binaries defined as functions at shell startup. On first invocation, they load up Node properly and everything proceeds hunky dory. (Thus you only incur the delay when you're actually using Node.) 

This seems to be interfering with VS Code's ability to figure out the environment -- I'm guessing that when it loads a fresh shell at startup and pulls its environment, the function definitions don't play a role (nor should they). 

If I start code from a command line where the lazy loading has already been done, the debugger works fine. 

Steps to Reproduce:

1. Install zsh and the [zsh port of nvm](https://github.com/lukechilds/zsh-nvm). Make them your default shell.
2. In your .zshrc, `export NVM_LAZY_LOAD=true` before `source`-ing `zsh-nvm/zsh-nvm.plugin.zsh`.
3. Try to debug a Node.js project in VS Code. 
4. Note "Cannot find runtime 'node' on PATH" error.
5. Close down VS Code, open a terminal, and run `node -v`. Then invoke `code` on a directory containing a Node.js project. 
6. Note that you can successfully debug this project.
6. Close down VS Code, remove the NVM_LAZY_LOAD export from .zshrc, and restart VS Code.
7. Note that the debugger now can find Node.

**Comment by sjml** [comment]
Sorry, submitted early; updating information still

**Comment by sjml** [comment]
Reopening just so the team can be aware of it as a potential snag. If nothing else, maybe somebody googling will find this page and solve their immediate issue.

**Comment by weinand** [comment]
@sjml thanks for raising this problem.
Since we do not want to start copying function definitions when we copy the environment variables, there is nothing we can do here.

**Comment by sjml** [comment]
Is there any plan to have something like user event hooks into VS Code, so I could, say, assign a script to "pre-debug" and have it initialize the environment properly? (Or in this case, simply something that runs when VS Code is building its environment?)

**Comment by danez** [comment]
I have the same issue. 

Would it be possible to write a plugin for vscode to initialize node? I haven't looked what possibilities plugins have, but if there is a way maybe we can write a plugin.

**Comment by danez** [comment]
As a workaround I did this in my .zshrc and it seems to work for me:

```zsh
export NVM_DIR=~/.nvm

# Only do lazy loading when NOT inside vscode
if [ -z "$VSCODE_PID" ]; then
    export NVM_LAZY_LOAD=true ;
fi

antigen bundle lukechilds/zsh-nvm
```

This can also probably also be adapted to other ways of lazy-loading.

**Comment by sjml** [comment]
That works perfectly! The check for $VSCODE_PID is exactly what was needed. Is that documented anywhere?

**Comment by sjml** [comment]
Closing because this is answered. Would be nice/smart to actually document $VSCODE_PID since it seems like it's a potentially very useful thing for playing with environments.
