### ISSUE TITLE
loss text in terminal

### ISSUE THREAD

**Issue by mingming-ctr** [microsoft/vscode#185591]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 
- OS Version: 

Steps to Reproduce:

1. setup node js
2. type node in terminal
3. create file 1.js,type in file like 
let searchSelector = "div.MmsUiMaterialModal___tab___1dQI92-24-0 > div.MmsUiMaterialModal___search___1pW_I2-24-0 > div > div > div > div > div.IPT_inputBlockCell_5-66-0 > input"
4. select text above,then terminal -> run selected text
5. if  not error .type the code:
searchSelector = "div.MmsUiMaterialModal___tab___1dQI92-24-0 > div.MmsUiMaterialModal___search___1pW_I2-24-0 > div > div > div > div > div.IPT_inputBlockCell_5-66-0 > input"
6. selected the code and then run multi times(terminal -> run selected text)
7. you can get error :Uncaught SyntaxError: Invalid or unexpected token
8. if you press“Upward Arrow”，you will find the executed code loss text.my execute text is :> searchSelector = "div.MmsUiMaterialModal___tab___1dQI92-24-0 > div.MmsUiMaterialModal___search___1pW_I2-24-0 > div > div > div > div > div.IPT_inputB

```[tasklist]
### Tasks
```

**Comment by mingming-ctr** [comment]
Thanks for your reply
I copy a puppeteer demo from url: https://developer.chrome.com/docs/puppeteer/get-started/
This is my code:
[test.zip](https://github.com/microsoft/vscode/files/11844822/test.zip)
I run it two ways:
1. node .\test.js
This way is ok.
2. open test.js in notebook ,copy the whole code;type "node" in vscode terminal and paste code. you will find the error.


[demo.zip](https://github.com/microsoft/vscode/files/11845703/demo.zip)

**Comment by meganrogge** [comment]
the demo:
https://github.com/microsoft/vscode/assets/29464607/665f7b88-16d1-4fa5-9c01-916e555fa38f

**Comment by mingming-ctr** [comment]
if not node.exe,eg:powershell,python etc.
This method is ok.

The picture below is the same function.
The function of the menu should be the function you planned.

![6](https://github.com/microsoft/vscode/assets/12455138/ef739442-18a7-48d1-87ba-b2a719208d73)

The purpose of this function is to be able to view the results of a certain piece of code at any time. There is no need to go through it from start to finish.
At the same time, I can also modify the code at any time, select and press F1 to run after the modification.

**Comment by meganrogge** [comment]
This suggests that node doesn't support bracketed paste mode, which we cannot do anything about.

**Comment by mingming-ctr** [comment]
@meganrogge 
Can you support "Run Selected Text" ?

The same as "bracketed paste "
