### ISSUE TITLE
all of my code lost and cannot undo anything

### ISSUE THREAD

**Issue by Vernando05** [Microsoft/vscode#18551]
- VSCode Version: 1.8.1
- OS Version:  Windows 10 latest update

Steps to Reproduce:

1. I dont know it happened so quick, I was copy and pasting a line of code in my js file, but my finger slipped and press wrong keyboard button (I dont know what it is), and  suddenly all of my code is disappear, I cannot undo or redo anything, and the worst part is it's a long streak coding, I havent commited my changes yet :( 
2. is there any solutions for this? vscode hot exit file cache maybe??
3. and there's a red triangle at line number after my code dissapear 
ps: I'm on a deadline any help would be appreciated.

**Comment by dbaeumer** [comment]
@Tyriar any change the file can be recovered from hot exit. If not I suggest to close the issue.

**Comment by Tyriar** [comment]
I doubt it will be in the hot exit cache as it tries to keep exactly what's on screen. You can check it though inside `%APPDATA%\Code\User\Backups`. That's the only copy of file data we replicate AFAIK, if you figure out what you pressed please let us know.
