### ISSUE TITLE
Terminal: Job table full or recursion limit exceeded, in long running instances

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#185567]
<details><summary>Version Details</summary>
<p>

```
Version: 1.80.0-insider
Commit: 73eb619afb87cab4aa83a569259c891b6983c11e
Date: 2023-06-19T05:56:57.953Z
Electron: 22.3.11
ElectronBuildId: 21658788
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Darwin arm64 22.5.0
```

I use zsh:

```
zsh 5.9 (x86_64-apple-darwin22.0)
```

</p>
</details> 

My terminals have been running for a while, since at least last week. They went through a few VS Code updates but were always resumed. This afternoon I logged in and saw this on some of them:

![image](https://github.com/microsoft/vscode/assets/22350/ae80b6d8-2a31-4047-a900-afe217980016)

Related: #166303 #165648 #165648

**Comment by joaomoreno** [comment]
No, I haven't disabled it.

**Comment by Tyriar** [comment]
This is almost certainly related to shell integration but it doesn't look like there's any recursion so I'm not sure how to action this one.

**Comment by meganrogge** [comment]
@joaomoreno I have not seen this, thus closing. Pls reopen if you've been able to reproduce it recently.
