### ISSUE TITLE
VSCode doesn't start and stays quiet when Prefs folder doesn't exist

### ISSUE THREAD

**Issue by NiklasRosenstein** [Microsoft/vscode#18554]
- VSCode Version: 1.8.1
- OS Version: Windows 10 x64

Steps to Reproduce:

1. Delete or temporarily rename the folder `%APPDATA%\Code\User`
2. Try to start VSCode

Notice how VSCode doesn't start at all. Luckily you still get a warning when running Code with `--verbose`

    Startup error: Error: ENOENT: no such file or directory, stat 'C:\Users\niklas\AppData\Roaming\Code\User'

This warning should be displayed in a dialog box or something.

**Comment by bpasero** [comment]
@NiklasRosenstein I cannot reproduce, for me the folder "User" gets created when I start Code again after having it renamed to "Foo".

**Comment by NiklasRosenstein** [comment]
You're right, my description is wrong. It's not when the folder does not exist, but when the folder actually is a symbolic link to a folder that does not exist.
