### ISSUE TITLE
Duplicate error notification from terminal process non-zero termination

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#185570]
<details><summary>Details</summary>
<p>

```
Version: 1.80.0-insider
Commit: 73eb619afb87cab4aa83a569259c891b6983c11e
Date: 2023-06-19T05:56:57.953Z
Electron: 22.3.11
ElectronBuildId: 21658788
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Darwin arm64 22.5.0
```

</p>
</details> 

Every now and then, exiting zsh by typing `exit` and hitting <kbd>Enter</kbd> results in an error notification. What just happened to me was that the same error notification came up in the window I did that, as well as another workspace window. I even had more workspace windows open and the error didn't show up on those. 🤷 

![image](https://github.com/microsoft/vscode/assets/22350/baad7032-018b-46f9-b526-28f8ebb7099d)

cc @bpasero

**Comment by Tyriar** [comment]
This has actually always happened on macOS and I never understood why `exit` doesn't always exit with zero. The `terminal.integrated.showExitAlert` setting was added to workaround this many years ago.

**Comment by joaomoreno** [comment]
That setting is enough for me :)
