### ISSUE TITLE
Add links to MarkedString

### ISSUE THREAD

**Issue by IgnacioHR** [Microsoft/vscode#1856]
In case of an exception while debugging code you have the chance to jump to the line of the source code by clicking on the underlined text in red.

That feature is not available in a hove message but it might be a good idea to allow the user to click on a link in a hover message and "do something" like opening the link on a side editor instead of in the current editor.

In order to easily implement the following proposal might work:
1) extend the MarkedString to allow links (using the markdown syntax would be fine)
2) add an event to MarkedString to be notified when the user clicks on a link inside the rendered text. the link uri shall be received as the event parameter

**Comment by jrieken** [comment]
I agree - tho it won't be a special event but invoking a command

**Comment by IgnacioHR** [comment]
OK, As far as the command knows where the user has clicked

**Comment by jrieken** [comment]
We will pass the link itself to the command

**Comment by IgnacioHR** [comment]
Looking forward to test it ;)

**Comment by jrieken** [comment]
stretch for Jan

**Comment by jrieken** [comment]
wrt to links it's this: `[label](commandId)` to run a command
