### ISSUE TITLE
The class file of the third-party library cannot be debugged

### ISSUE THREAD

**Issue by StraySheepPO8** [microsoft/vscode#185635]
The class file of the third-party library cannot be debugged, is that correct?
When I set a breakpoint in RedisAutoConfiguration.class, unable to take effect. I'm sure the program should execute that method.
If I am right, can you add this function? After all, IDEA does have this function.

env:
- vscode: 1.78.2 latest version
- Plugin: Debugger for Java, 0.51.0

**Comment by roblourens** [comment]
This is a request for the Java debug extension
