### ISSUE TITLE
browser-plugin doesn't scale with zoomLevel

### ISSUE THREAD

**Issue by spacegoing** [Microsoft/vscode#18566]
- VSCode Version: V1.8
- OS Version: macOS 10.12

Steps to Reproduce: Unknown, may be by set `zoomLevel`

![screenshot 2017-01-15 23 33 43](https://cloud.githubusercontent.com/assets/5180020/21962502/72e4bd6a-db7b-11e6-8548-2460cfdc5f5a.png)

As you can see in the screenshot, "browser-plugin" (I found the name by devTools) doesn't scale with the editor

**Comment by joaomoreno** [comment]
#5745
