### ISSUE TITLE
open terminal from SCM uses integrated terminal

### ISSUE THREAD

**Issue by FernandoMiguel** [microsoft/vscode#185650]
Type: <b>Bug</b>

When right clicking on the SCM to open a terminal, vscode is opening the integrated teminal instead of the external one.
Doing the same from the file explorer tree, works as expected.
In the settings, this is set as `  "terminal.external.osxExec": "iTerm.app",`

This was working fine up to two weeks ago or so, in the nightly build.

VS Code version: Code - Insiders 1.80.0-insider (8c85702bca51b08005ada7fc4eaf52a61623b2b6, 2023-06-20T05:57:02.452Z)
OS version: Darwin arm64 22.6.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|2, 2, 3|
|Memory (System)|32.00GB (0.13GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (18)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-base64|ada|0.1.0
inline-hasher|ale|1.1.0
spellright|ban|3.0.116
iam-policy|bin|0.0.1
better-toml|bun|0.3.2
auto-markdown-toc|hun|3.0.12
vscode-kubernetes-tools|ms-|1.3.13
indent-rainbow|ode|8.3.1
vscode-yaml-sort|Pas|6.5.3
vscode-yaml|red|1.13.0
vscode-gitweblinks|red|2.9.2
iam-legend|Seb|1.1.37
kubernator-vscode|smp|1.0.0
code-spell-checker|str|2.20.5
shellcheck|tim|0.32.6
sort-lines|Tyr|1.10.1
errorlens|use|3.11.1
vscode-icons|vsc|12.4.0

(1 theme extensions excluded)

</details>

**Comment by lszomoru** [comment]
The change in behaviour happened in [this commit](https://github.com/microsoft/vscode/commit/acd434717a53c49283467fedebe1ed6413087138). There is a similar action in the Explorer and I see that there is a setting (`terminal.explorerKind`) that controls which action is being shown in the Explorer. I will adopt the same setting for the actions that are being shown in the "Source Control" viewlet.

**Comment by FernandoMiguel** [comment]
@lszomoru let me know once this is in the nightly, and I can test if it is fixed .
thanks

**Comment by lszomoru** [comment]
VS Code Inciders version 1.81 (planned to be released later this week) will contain a new setting, `terminal.sourceControlRepositoriesKind` that users can control the menu items for opening the repository in integrated/external terminal.
