### ISSUE TITLE
Improve presentation of startup perf raw marks

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#185669]
We should put these in a table:

![image](https://github.com/microsoft/vscode/assets/2193314/3dbeb9d5-ea68-4479-832f-f7c67bb5fa1d)

Something like this:

## Raw Perf Marks: main

| Name | Timestamp | Delta | Total
|---|---|---|---
| code/timeOrigin | 1687187191725.414 | 0 | 0
| code/didStartMain | 1687187191797 | 71.5859375 | 71.5859375
| code/willStartCrashReporter | 1687187191812 | 15 | 86.5859375
| code/didStartCrashReporter | 1687187191838 | 26 | 112.5859375
| code/willGenerateNls | 1687187191841 | 3 | 115.5859375
| code/mainAppReady | 1687187191872 | 31 | 146.5859375
| code/willLoadMainBundle | 1687187191872 | 0 | 146.5859375
| code/fork/willLoadCode | 1687187191885 | 13 | 159.5859375
| code/registerFilesystem/file | 1687187191998 | 113 | 272.5859375
| code/didLoadMainBundle | 1687187192018 | 20 | 292.5859375

cc @bpasero, @jrieken

**Comment by jrieken** [comment]
The current format is on purpose so that the data can simply be copy-pasted into Excel for further inspection. This is a rare case but very useful when drilling into perf issues and something I don't wanna loose. So, if this is done it should be behind a setting

**Comment by Tyriar** [comment]
@jrieken an online converter seems to work pretty well, is that fine since it's the edge case? https://tableconvert.com/markdown-to-csv

**Comment by Tyriar** [comment]
![image](https://github.com/microsoft/vscode/assets/2193314/5f4f13fb-7b04-4b6c-b4e2-111aa13f6b3e)

**Comment by jrieken** [comment]
No, I don't wanna have to use an online converter for this. Performance investigations are already stressful enough. I use the copy-paste-to-excel flow repeatedly for multiple runs of two versions (slow/fast) and I want that to be as smooth as possible. That also the reason why it's called "Raw" perf marks. The top section is already a table of roll-up data and I wonder why your additions aren't going in there.

**Comment by Tyriar** [comment]
Sounds good, I'll move it into its own section somewhere similar to the extension status section. I didn't initially because the main table at the top is exclusively pulled from the timer service which workbench contribs can't integrate nicely with, and wanted to reuse as much code as possible.
