### ISSUE TITLE
Only first "debug-test" configuration in launch.json is used and other configs are ignored.

### ISSUE THREAD

**Issue by Amourspirit** [microsoft/vscode#185657]
Type: <b>Bug</b>

# Behaviour
## Expected vs. Actual

Expected that when I choose a configuration debug it environment vars are loaded

What actaully happens is whatever "debug-test" conifguration is found first in the launch.json is the environment vars that get loaded

## Steps to reproduce:

Add More then one "debug-test" configuration to launh.json.
Select any "debug-test" configuration that is not the first one in the launch.json file.
Run a test in debug mode and the incorrect environment vars are now loaded.

```json
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Python: Current File",
            "type": "python",
            "request": "launch",
            "program": "${file}",
            "console": "integratedTerminal",
            "justMyCode": true
        },
        {
            "name": "Python: Test Local GUI",
            "type": "python",
            "console": "integratedTerminal",
            "request": "launch",
            "purpose": [
                "debug-test"
            ],
            "program": "${file}",
            "env": {
                "NO_HEADLESS": "1",
                "ODEV_TEST_CONN_SOCKET": "",
                "ODEV_TEST_CONN_SOCKET_KIND": "default",
                "ODEV_TEST_CONN_SOCKET_PORT": "2002",
            }
        },
        {
            "name": "Python: Test Remote",
            "type": "python",
            "console": "integratedTerminal",
            "request": "launch",
            "purpose": [
                "debug-test"
            ],
            "program": "${file}",
            "env": {
                "ODEV_TEST_CONN_SOCKET": "true",
                "ODEV_TEST_CONN_SOCKET_KIND": "no_start",
                "ODEV_TEST_CONN_SOCKET_PORT": "2002",
            }
        },
        {
            "name": "Python: Current All Code",
            "type": "python",
            "request": "launch",
            "program": "${file}",
            "console": "integratedTerminal",
            "justMyCode": false
        }
}
```

# Diagnostic data

-   Python version (& distribution if applicable, e.g. Anaconda): 3.10.5
-   Type of virtual environment used (e.g. conda, venv, virtualenv, etc.): Poetry
-   Value of the `python.languageServer` setting: Default

<details>

<summary>Output for <code>Python</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Python</code>)
</summary>

<p>

```
XXX
```

</p>
</details>

<details>

<summary>User Settings</summary>

<p>

```

languageServer: "Pylance"

formatting
• provider: "black"
• blackArgs: "<placeholder>"

testing
• pytestArgs: "<placeholder>"
• pytestEnabled: true

```

</p>
</details>

VS Code version: Code 1.79.2 (695af097c7bd098fbf017ce3ac85e09bbc5dda06, 2023-06-14T08:59:55.818Z)
OS version: Linux x64 5.19.0-45-generic
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-7130U CPU @ 2.70GHz (4 x 2700)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|1, 1, 1|
|Memory (System)|15.48GB (4.77GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|wayland|
</details><details><summary>Extensions (73)</summary>

Extension|Author (truncated)|Version
---|---|---
project-manager|ale|12.7.0
arepl|alm|2.0.5
vscode-color|ans|0.4.5
mermaid-markdown-syntax-highlighting|bpr|1.5.2
better-toml|bun|0.3.2
ruff|cha|2023.26.0
gitignore|cod|0.9.0
python-snippets|cst|0.1.2
lines|Dan|0.0.6
vscode-markdownlint|Dav|0.51.0
xslt-xpath|del|1.5.13
python-extensions-pack|dem|1.0.2
snippet|dev|1.1.0
git-extension-pack|don|0.1.3
githistory|don|0.6.20
python-environment-manager|don|1.0.4
python-extension-pack|don|1.7.0
xml|Dot|2.5.1
gitlens|eam|14.0.1
vscode-diff|fab|1.4.2
vscode-todo-plus|fab|4.19.1
git-project-manager|fel|1.8.2
code-runner|for|0.12.0
shell-format|fox|7.2.5
codespaces|Git|1.14.8
copilot-chat|Git|0.3.2023060801
copilot-nightly|Git|1.89.172
vscode-gitbuild|grz|1.0.1
vscode-test-explorer|hbe|2.21.1
output-colorizer|IBM|0.1.2
vsc-python-indent|Kev|1.18.0
vscode-python-test-adapter|lit|0.7.1
linecounter|lyz|0.2.7
bash-ide-vscode|mad|1.37.0
MagicPython|mag|1.1.0
python-path|mge|0.0.14
git-graph|mhu|1.30.0
colored-regions|mih|0.0.3
vscode-docker|ms-|1.25.1
vscode-dotnet-runtime|ms-|1.6.0
black-formatter|ms-|2023.2.0
isort|ms-|2022.8.0
python|ms-|2023.10.1
vscode-pylance|ms-|2023.6.20
remote-containers|ms-|0.295.0
remote-ssh|ms-|0.102.0
remote-ssh-edit|ms-|0.86.0
remote-wsl|ms-|0.79.5
vscode-remote-extensionpack|ms-|0.24.0
remote-explorer|ms-|0.4.0
remote-server|ms-|1.2.1
sublime-keybindings|ms-|4.0.10
test-adapter-converter|ms-|0.1.8
autodocstring|njp|0.6.1
vscode-python-typehint|njq|1.5.1
indent-rainbow|ode|8.3.1
vscode-gitignore-generator|pio|1.0.3
qub-xml-vscode|qub|1.2.8
shortenurl|Ros|1.1.0
markdown-preview-enhanced|shd|0.6.8
sourcery|sou|1.4.0
code-spell-checker|str|2.20.5
spellchecker|swy|1.4.0
wolf|tra|0.4.3
simple-rst|tro|1.5.3
intellicode-api-usage-examples|Vis|0.2.7
vscodeintellicode|Vis|1.2.30
vscode-icons|vsc|12.4.0
snippet|vsc|1.0.2
jinja|who|0.0.8
livecode|xir|1.3.10
open-in-external-app|YuT|0.9.10
vscode-open-in-github|ziy|1.3.6

(1 theme extensions excluded)

</details>

**Comment by roblourens** [comment]
Please file this on the vscode-python extension repo, thanks
