### ISSUE TITLE
No-tab info guide font display glitch on Linux

### ISSUE THREAD

**Issue by dxdt0** [microsoft/vscode#185695]
Does this issue occur when all extensions are disabled?: Yes/No
**Yes**

- VS Code Version: **1.79.2**
- OS Version: **Kubuntu 22.04**

Steps to Reproduce:

1. Start VSCode
2. Close all editor tabs

![image](https://github.com/microsoft/vscode/assets/48856944/bf493286-184f-4564-a6d8-5f32a6ac5421)
![image](https://github.com/microsoft/vscode/assets/48856944/67dc38ed-f664-474c-9eac-855dcbccac0b)

In multiple Linux distributions, with multiple desktop environments, I face this glitch where the guide text isn't displayed correctly. Setting `window.titleBarStyle` to `custom` or disabling extensions also doesn't work.

**Comment by deepak1556** [comment]
Merging to https://github.com/microsoft/vscode/issues/171367
