### ISSUE TITLE
Extend icon theme with custom icons

### ISSUE THREAD

**Issue by mxschmitt** [microsoft/vscode#185639]
So the idea was to add a Playwright icon for `.*playwright\.config\.{ts,js,mjs}` files. Either in the core or via our [extension](https://marketplace.visualstudio.com/items?itemName=ms-playwright.playwright).

I saw multiple ways of setting a custom file icon as of today:

a) via a custom language: https://github.com/microsoft/vscode/issues/140047 (I tried this, but then the config is no TS/JS file anymore - I loose the language features)
b) via adding it to the seti icon pack: https://github.com/jesseweed/seti-ui (I could try to go this approach - not sure if they accept it)
c) via adding a completely custom icon pack: https://code.visualstudio.com/api/extension-guides/file-icon-theme (This means I loose all the other icons)

What I felt was missing is a way of adding only one icon to it, aka. extending the default icon pack. Is this already possible and just not documented or not planned?

Thanks in advance!

**Comment by aeschli** [comment]
There's no other way than what you described.

The idea is that each icon theme author has the full power to choose which file icons they want and how they look like.
Some are minimal, some keep all icons in a certain style.
The default language icons are a special case, but themes can disable that. 

Maybe what's missing is to create a new language that inherits all feature of an other language, so you could define your 'Playwright config file' language.

I recommend making a pull request against Seti and lobby with the authors of the popular file icon themes.
