### ISSUE TITLE
Folder Settings in Workspace File (Exclude files or folders per workspace folder)

### ISSUE THREAD

**Issue by ThaJay** [microsoft/vscode#185673]
This issue was immediately closed, although I do not think that was completely warranted.
https://github.com/Microsoft/vscode/issues/44476

https://github.com/Microsoft/vscode/issues/44476#issuecomment-368794983

> @lostfields you can easily do that by configuring folder based settings. files.exclude is supported on that level.

This was the official answer. Although it is possible to ignore certain folders through the folder settings, a `workspace folder` is not the same as a `file system folder`. I could have the same `file system folder` multiple times in one workspace. It would be amazing If I could have (some) folder settings in my workspace file for the following reasons:

- All project related settings would be in one (1) place, making them easier to manage and maintain.
- I do not like having a `.vscode` folder in my project because it's another source of confusion. For our organisation 2 levels is enough. We all use VsCode, so we use the `user` settings for personalization and `workspace` settings for project standardization. This works well and does not need more complexity
- The folder settings are bound to a specific location on the file system, while workspace folders are just a pointer to a location that does not have to be unique in the workspace.

My proposition:
```
{
  "folders": [
    {
      "name": "Source code",
      "path": "src",
      "settings": {
        "files.exclude": {
          "*.json": true,
          (...)
        },
      }
    },
    (...)
  ],
  "settings": {
    "cSpell.enableFiletypes": ["!json"],
    (...)
  }
}
```

Thank you

**Comment by sandy081** [comment]
> I do not like having a .vscode folder in my project because it's another source of confusion. For our organisation 2 levels is enough. We all use VsCode, so we use the user settings for personalization and workspace settings for project standardization. This works well and does not need more complexity

Folder settings is supported under `.vscode` folder and we would not want to introduce another mechanism.
