### ISSUE TITLE
Long commit message warning covers commit button for Source Control UI

### ISSUE THREAD

**Issue by ctsstc** [microsoft/vscode#185606]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.79.2 (Universal)
- OS Version: Mac OS 13.2.1 (22D68)

Steps to Reproduce:

1. Write a long commit message in the Source Control UI
2. Don't Profit

<img width="329" alt="image" src="https://github.com/microsoft/vscode/assets/416814/0edc7824-1710-4021-99ad-a1539dc09251">

I saw on another ticket that there's a setting turn off the warning message via `enableLongCommitWarning`, but the current UX for the warning message is not so great. It would be nicer if it could sit below the commit button rather than overlapping above it.

Edit: I couldn't find that setting any more that was mentioned in: #12089  it seems the closest setting is: `git.inputValidationLength` but it doesn't seem you can disable it anymore unfortunately. I thought maybe putting 0 or -1 would work, but it does not, so I guess for now I just need to set it to a large number.

**Comment by gjsjohnmurray** [comment]
This scenario was the main motivation for me contributing the PR that added the X button with which you can dismiss the message.

**Comment by ctsstc** [comment]
My team utilizes many small commits with long explanations in commit messages to document changes, so this gets to be an annoying part of the workflow on every commit.

**Comment by lszomoru** [comment]
@ctsstc, the setting to control the commit message input validation is `git.inputValidation`. Starting with VS Code 1.85, we have also updated the default value of this setting to `off` which means that the warning will not be shown by default. At the moment we are not planning on changing the rendering of the input validation so I will go ahead and close the issue.
