### ISSUE TITLE
ES2015 import from './css' incorrectly links to .../css/index.d.ts instead of my own css.js

### ISSUE THREAD

**Issue by davnicwil** [Microsoft/vscode#18562]
I have a file `css.js` and I `import css from './css.js'` in another module in the same directory.

`'./css.js'` seems to be interpreted by the editor as a link to `/Users/me/Library/Application Support/Microsoft/TypeScript/node_modules/@types/css/index.d.ts`, rather than my `css.js` module.

Problems:

1. cmd+click on `'./css.js'` incorrectly links to `/Users/me/Library/Application Support/Microsoft/TypeScript/node_modules/@types/css/index.d.ts`.
2. Intellisense does not work on the `css` variable - nothing from my `css.js` module is suggested

Observations: 
* `import css from 'css'` also links to `index.d.ts`
* `import css from './css.js'` (with js extension) correctly links to my `css.js` file
* `import css from '../mydir/css'` correctly links to my `css.js` file
* changing the import variable name from `css` to `somethingElse` has no effect - same problems occur.

This was not an issue until very recently - only noticed it in the last week or so, and the behaviour changed for existing code where previously the linking was working fine. I suspect it was introduced with v1.8.1.

---
- VSCode Version: 1.8.1
- OS Version: MacOS Sierra

Steps to Reproduce:

1. create a file `css.js` and a file `other.js` in the same directory
2. `export default { a: 1, b: 2 }` from `css.js`
3. `import css as './css'` in `other.js`
4. cmd+click `'./css'` in the editor, see the incorrect navigation to `../css/index.d.js`
5. notice that intellisense on `css.` in `other.js`does not suggest `css.a` or `css.b`
---

**Comment by davnicwil** [comment]
@mjbvz This issue has gone away in 1.9.0

**Comment by mjbvz** [comment]
@davnicwil Glad to here that. Sorry that we are not able to prioritize investigating this bug, but it sounds like TypeScript 2.1.5 fixed things.

Please let us know if you notice any similar problems
