### ISSUE TITLE
Ctrl+backspace will delete a whole paragraph of text in the editor instead of deleting a single word. How to solve it?

### ISSUE THREAD

**Issue by Traumaa** [microsoft/vscode#185652]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 
- OS Version: 

Steps to Reproduce:

1. 
2. 

```[tasklist]
### Tasks
```

**Comment by Traumaa** [comment]
Does this issue occur when all extensions are disabled?: No
VS Code Version: latest
OS Version: windows 11

**Comment by 0ME9A** [comment]
Hi, @Traumaa 👋

To delete a line in VS Code, you can use the following shortcuts:

1. To delete a single line: Press `Ctrl` + `Shift` + `Backspace`.
2. To delete multiple lines: Select all the lines you want to delete, and then press `Ctrl` + `Shift` + `Backspace`.

If you want to customize shortcuts in VS Code, you can follow these steps:

1. Press `Ctrl` + `K`, then release the keys and press `S`. This will open the Keyboard Shortcuts menu.
2. In the search bar of the Keyboard Shortcuts menu, type in your query or the name of the command you want to customize.
3. Double-click on the desired command from the list to edit its shortcut.
4. Either create a new shortcut that is not already assigned to a command or delete the existing shortcut for that command and assign your desired shortcut.

Note: If a shortcut is already assigned to a command, it won't work until you either create a new shortcut or remove the existing one for that command.

I hope this clarifies the information for you! Let me know if there's anything else I can help you with.

**Comment by ulugbekna** [comment]
Please, see **reference** on how to learn how to change a specific keybinding
