### ISSUE TITLE
Strange hint on reference

### ISSUE THREAD

**Issue by youngytj** [Microsoft/vscode#18565]
- VSCode Version: Code 1.8.1 (ee428b0eead68bf0fb99ab5fdc4439be227b6281, 2016-12-19T14:42:49.304Z)
- OS Version: Darwin x64 16.3.0
- Extensions:

|Extension|Author|Version|
|---|---|---|
|beautify|HookyQR|0.7.3|
|vscode-docker|PeterJausovec|0.0.11|
|code-settings-sync|Shan|2.4.2|
|html-snippets|abusaidm|0.0.18|
|githistory|donjayamanne|0.1.4|
|python|donjayamanne|0.5.5|
|rest-client|humao|0.12.0|
|cpptools|ms-vscode|0.9.3|
|csharp|ms-vscode|1.6.2|
|java|redhat|0.0.8|
|guides|spywhere|0.6.1|
|JavaScriptSnippets|xabikos|1.2.0|

---
![image](https://cloud.githubusercontent.com/assets/4630470/21962290/4be61024-db5d-11e6-958a-e7d6f5cef0c7.png)

![image](https://cloud.githubusercontent.com/assets/4630470/21962310/af86a544-db5d-11e6-99c0-ff5bc312b3c5.png)

**Comment by dbaeumer** [comment]
@youngytj can you please provide steps or better describe what the problem is?

**Comment by youngytj** [comment]
@dbaeumer Hi, `AddMvc()` method should be found but still told me it was no reference.

**Comment by dbaeumer** [comment]
This issue was moved to OmniSharp/omnisharp-vscode#1129
