### ISSUE TITLE
Menu bar not responsive after creating a new window and maximising it

### ISSUE THREAD

**Issue by bennaa** [microsoft/vscode#185643]
Type: <b>Bug</b>

Steps to Reproduce:
1. Go to File -> New window
2. Double click on top bar of VSCode window
3. Menu bar is not responsive. Also right cllick in explorer not working

VS Code version: Code 1.79.2 (695af097c7bd098fbf017ce3ac85e09bbc5dda06, 2023-06-14T08:59:55.818Z)
OS version: Linux x64 5.19.0-45-generic
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz (8 x 3687)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|2, 1, 1|
|Memory (System)|15.42GB (9.42GB free)|
|Process Argv|--unity-launch --crash-reporter-id 5a2e4b62-0e27-4e1d-ac38-d8c0baffc98d|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu-xorg|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu-xorg|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (43)</summary>

Extension|Author (truncated)|Version
---|---|---
jsoncrack-vscode|Ayk|1.0.8
beardedicons|Bea|1.12.0
path-intellisense|chr|2.8.4
compulim-vscode-closetag|Com|1.2.0
vscode-dash|dee|2.4.0
gitlens|eam|14.0.1
code-runner|for|0.12.0
vscode-edit-csv|jan|0.7.6
better-cpp-syntax|jef|1.17.2
intellij-idea-keybindings|k--|1.5.9
vsc-python-indent|Kev|1.18.0
rainbow-csv|mec|3.7.0
git-graph|mhu|1.30.0
autopep8|ms-|2023.4.0
pylint|ms-|2023.4.0
python|ms-|2023.10.1
vscode-pylance|ms-|2023.6.20
jupyter|ms-|2023.5.1001582324
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.15
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-slideshow|ms-|0.1.5
cmake-tools|ms-|1.14.33
cpptools|ms-|1.16.1
cpptools-extension-pack|ms-|1.3.0
test-adapter-converter|ms-|0.1.8
vscode-sanddance|msr|4.1.0
sqltools|mtx|0.27.1
sqltools-driver-sqlite|mtx|0.5.0
autodocstring|njp|0.6.1
vscode-pbkit|pbk|0.0.5
material-icon-theme|PKi|4.28.0
material-product-icons|PKi|1.5.0
sqlite-viewer|qwt|0.2.5
indenticator|Sir|0.7.0
tabnine-vscode|Tab|3.6.60
vscode-pets|ton|1.22.0
pypi-assistant|twi|1.1.3
cmake|twx|0.0.17
sort-lines|Tyr|1.10.1
intellicode-api-usage-examples|Vis|0.2.7
vscodeintellicode|Vis|1.2.30
local-history|xyz|1.8.1

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
vscaac:30438847
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
3biah626:30602489
pyind779:30671433
89544117:30613380
pythonsymbol12:30671437
showlangstatbar:30737416
vsctsb:30748421
pythonms35:30701012
03d35959:30757346
pythonfmttext:30731395
pythoncmvfstrcf:30756944
fixshowwlkth:30771522
showindicator:30766890
pythongtdpath:30769146
dh2dc718:30770000
pythondjangotscf:30768920

```

</details>

**Comment by sbatten** [comment]
@deepak1556 native title bar

**Comment by deepak1556** [comment]
This is fixed in latest insiders, merging to https://github.com/microsoft/vscode/issues/187126
