### ISSUE TITLE
Watch .git/info/exclude the same way .gitignore is

### ISSUE THREAD

**Issue by brianjmurrell** [microsoft/vscode#185667]
In the same way that VS Code watches `.gitignore` and acts immediately upon changes to it, without a need to reload the source-code view, it should watch `.git/info/exclude` and act the same way.

As it is currently, when one edits and saves that file, one then has to reload the source-code view for the repo in order to have it reflect those changes.

Maybe a separate issue, but it would also be nice to be able to add multiply selected items to `.git/info/exclude`.  Currently even with multiple items selected, only the first is added to the file.

**Comment by lszomoru** [comment]
Thank you very much for filing this issue. Given that there is currently a workaround and low interest I will close this feature request.
> As it is currently, when one edits and saves that file, one then has to reload the source-code view for the repo in order to have it reflect those changes.
