### ISSUE TITLE
Intellisense not working with Python 3.6

### ISSUE THREAD

**Issue by senhtry** [Microsoft/vscode#18563]
Intellisense not working with Python 3.6. Python extension hasn't the 3.6 grammer file.

Solution:
copy grammar3.5.txt to grammar3.6.txt in ~\.vscode-insiders\extensions\donjayamanne.python-0.5.5\pythonFiles\preview\jedi\parser and my autocompletion started to work again.

**Comment by dbaeumer** [comment]
@senhtry please file the issue against https://github.com/DonJayamanne/pythonVSCode which owns the extension.
