### ISSUE TITLE
OmniSharp.exe virus on Bitdefender Antivirus for Mac 

### ISSUE THREAD

**Issue by kivvv** [Microsoft/vscode#18560]
- VSCode Version: Code 1.8.0 (38746938a4ab94f2f57d9e1309c51fd6fb37553d, 2016-12-13T17:38:28.425Z)
- OS Version: Darwin x64 16.3.0
- Extensions:

|Extension|Author|Version|
|---|---|---|
|csharp|ms-vscode|1.6.2|

---
Bitdefender Antivirus for Mac alerted me that..
"1/15/2560 BE, 5:24 PM
Gen:Variant.Barys.50536 deleted
/Users/1v5/.vscode/extensions/ms-vscode.csharp-1.6.2/bin/omnisharp/refs/OmniSharp.exe"
 
![screen shot 2560-01-15 at 5 31 17 pm](https://cloud.githubusercontent.com/assets/10217657/21961896/84a8acd8-db48-11e6-89b6-a517b16d79be.png)

Is it really safe? Or it is just a false alarm?

**Comment by dbaeumer** [comment]
This issue was moved to OmniSharp/omnisharp-vscode#1127
