### ISSUE TITLE
Support for regex test along the lines of IntelliJ

### ISSUE THREAD

**Issue by thekalinga** [Microsoft/vscode#18569]
Intellij allows us to check regex against arbitrary string to validate any regex within code.

This feature also escapes the regex characters appropriately according to the language of the file the user is editing.

This would a "nice to have" feature in vscode.

Reference:
https://blog.jetbrains.com/idea/2011/11/regexp/

**Comment by mjbvz** [comment]
Try this extension: https://marketplace.visualstudio.com/items?itemName=chrmarti.regex
