### ISSUE TITLE
Behavior of the `${command:...}` preLaunchTask in the `launch.json` is not obvious

### ISSUE THREAD

**Issue by astrochili** [microsoft/vscode#185755]
- VS Code Version: 1.79.2
- OS Version: macOS 13.4

I have a goal to run my extension's command before launching other extension's debugger. This is `launch.json` configuration example:
```json
{
  "name": "Lua",
  "type": "lua-local",
  "request": "launch",
  "program": {
    "lua": "lua",
    "file": "${workspaceFolder}/main.lua"
  },
  "preLaunchTask": "${command:anyCommand}"
}
```

- Without `preLaunchTask` the debugger starts as expected.
- With `preLaunchTask` the command runs as expected but doesn't trigger debugger launching after finishing.

The behavior is the  same with any command, not only my extension's command, for example, try the built-in `search.action.openEditor` command.

On other hand, everything works as expected if I create the task in `tasks.json` with the same command and set `"preLaunchTask"` to `"My Pre Launch Task"`:

```json
{
  "label": "My Pre Launch Task",
  "command": "${command:anyCommand}"
}
```

But it's not so pretty to create or edit `tasks.json`, because all I want to do is run the known command before running the debugger. So I went a little deeper and added the following code to my extension activation method:

```typescript
let mySecretTaskDefinition = {
  type: 'mySecretTaskType',
  command: "${command:anyCommand}"
};

let mySecretTask = new vscode.Task(
  mySecretTaskDefinition,
  vscode.TaskScope.Workspace,
  'Pre Launch Task',
  'My',
  new vscode.CustomExecution(() => {
    return vscode.commands.executeCommand('anyCommand');
  })
);

vscode.tasks.registerTaskProvider('mySecretTaskType', {
  provideTasks: () => {
    return [mySecretTask];
  },
  resolveTask(_task: vscode.Task): vscode.Task | undefined {
    return mySecretTask;
  }
});
```

and set `"preLaunchTask"` to `"My Pre Launch Task"`. And it works, the debugger starts when the `anyCommand` is finished, without openning terminal panel and without touching `tasks.json` and `package.json`. 🎉

But it looks quite tricky:

- I can't omit the `execution` parameter, as it immediately stops working and the task is not found.
- `CustomExecution`, which I pass to the `Task`'s constructor, is never called unless I add `taskDefinitions` to `package.json`.
- If I add `taskDefinitions` in `package.json` with `"type": "mySecretTaskType"`, the `CustomExecution` is called and `anyCommand` is called from there, not from definition's `command` property. But the debugger doesn't start, just a terminal panel with the message `Executing task: My Pre Launch Task`, which I didn't really want to open.
- If I provide `ShellExecution` to compare, it works perfectly without getting stuck (shell -> debugger), but I need to invoke my extension command, not the shell.

It looks like very undefined behaviour in different circumstances and the expected behaviour also is unknown.

The final workaround is to register any `CustomExecution` task with `command: "${command:...}"` in it's definition and not add it to `package.json`. But how stable and expected is it? What is the correct solution? Why do `${command:anyCommand}` in `tasks.json` and `launch.json` works differently?

**Comment by roblourens** [comment]
Right, the idea behind `preLaunchTask` is to run some task. Using it to run an arbitrary command that isn't related to a task is kind of a hack, and I wouldn't say I officially support that scenario, but it sounds like you've found a workaround to get what you need.
