### ISSUE TITLE
Diff Editor: Collapse Unchanged Code - Show Context Header

### ISSUE THREAD

**Issue by hediet** [microsoft/vscode#185781]
It would be very helpful to include the current symbol name in the collapsed unmodified code indicator (see `DiffEditorWidget2` and `constructor`):

![chrome_BE4rflvO6W](https://github.com/microsoft/vscode/assets/2931520/97dcd4ee-7b98-44fa-9ed0-71770cbb9963)

Verification steps:
* Open a diff in vscode (not monaco editor playground)
* Enable collapsing unchanged regions (map icon in editor titlebar)
* Observe that the collapsed code shows a header indicating which symbol started inside of the unchanged code but ended outside of it.
* Verify that clicking on it reveals the symbol

**Comment by bpasero** [comment]
I cannot click on the left hand side to expand:

![image](https://github.com/microsoft/vscode/assets/900690/8bf6a252-1473-4870-9e47-620b73b4a521)

Also, is the hover color themable?

**Comment by hediet** [comment]
> Also, is the hover color themable?

Yes.

> I cannot click on the left hand side to expand:

This is a bug, thanks for discovering!
