### ISSUE TITLE
Register * doesn't contain contents of PRIMARY selection

### ISSUE THREAD

**Issue by sbro-google** [microsoft/vscode#185723]
Steps
Select some text
Type "*p

Expected result
Pastes the selected text (i.e. it should act similar to middle click pasting the selected text)

Actual result
Pastes the contents of the clipboard (i.e. acts similar to ctrl+v)

Version: 1.79.2
Commit: 695af097c7bd098fbf017ce3ac85e09bbc5dda06
User Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36
Embedder: vscode.dev

**Comment by gjsjohnmurray** [comment]
It sounds like you are using a vim extension in VS Code. If so, please raise this with the extension author.

**Comment by sbro-google** [comment]
Thanks, I'll port the issue over to the extension's github issues tracker. I opened [this issue](https://github.com/microsoft/vscode/issues/185820) to track issues being reported in the wrong github project.
