### ISSUE TITLE
Can't commit

### ISSUE THREAD

**Issue by vunh79** [Microsoft/vscode#18574]
- VSCode Version: Code 1.8.1 (ee428b0eead68bf0fb99ab5fdc4439be227b6281, 2016-12-19T14:49:23.350Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

|Extension|Author|Version|
|---|---|---|
|vscode-github-file-folder-url|cycloware|1.0.0|
|copy-github-url|mattlott|0.1.0|

---

Steps to Reproduce:

1.
2.

**Comment by dbaeumer** [comment]
@vunh79 can you please provide steps or an example demonstrating the problem
