### ISSUE TITLE
problem: while using debug feature,if you want to extend the full list of a complex variable, it takes so much time and if you extend another variable, the whole debug process would stuck

### ISSUE THREAD

**Issue by Lordworms** [microsoft/vscode#185740]
when I want to extend the whole member of a complex data structure, and it keeps pending, however, if I want to extend the whole members of a simple data structure in DEBUG mode, the whole debug process would crash

**Comment by roblourens** [comment]
Please file this on the debug extension you're using, with more detail, thanks
