### ISSUE TITLE
VS Code takes ages to open

### ISSUE THREAD

**Issue by Pakerusa** [microsoft/vscode#185794]
Type: <b>Performance Issue</b>

I use VS Code a lot, a few days ago I started the application but it took like a half to one minute to open. I disabled all extensions and completely uninstalled it. After the reinstall it wasn’t any better.

VS Code version: Code 1.79.2 (695af097c7bd098fbf017ce3ac85e09bbc5dda06, 2023-06-14T08:57:04.379Z)
OS version: Windows_NT x64 10.0.22621
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 5600H with Radeon Graphics          (12 x 3294)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|13.87GB (7.16GB free)|
|Process Argv|--crash-reporter-id 3ce8cc40-f14c-470c-a0cf-094484c8ca17|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	    94	 16768	code main
    0	   142	  5328	extensionHost [1]
    0	   137	 23748	     electron-nodejs ("C:\Users\paulc\AppData\Local\Programs\Microsoft VS Code\Code.exe" --ms-enable-electron-run-as-node c:\Users\paulc\.vscode\extensions\ms-python.vscode-pylance-2023.6.20\dist\server.bundle.js --cancellationReceive=file:ec910ced90b1a19751771bab66301fb1a2481b9031 --node-ipc --clientProcessId=5328)
    0	    40	 26832	     c:\Users\paulc\AppData\Local\Microsoft\WindowsApps\python3.9.exe c:\Users\paulc\.vscode\extensions\ms-python.isort-2022.8.0\bundled\tool\server.py
    0	    10	 21192	       console-window-host (Windows internal process)
    0	    25	 26080	       c:\Users\paulc\AppData\Local\Microsoft\WindowsApps\python3.9.exe c:\Users\paulc\.vscode\extensions\ms-python.isort-2022.8.0\bundled\tool\runner.py
    0	   134	  8388	   gpu-process
    0	   175	 10376	window [1] (lotto.py - openCV - Visual Studio Code)
    0	    91	 12032	ptyHost
    0	    63	  5836	     C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe -noexit -command "try { . \"c:\Users\paulc\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\contrib\terminal\browser\media\shellIntegration.ps1\" } catch {}"
    0	     6	 20324	     console-window-host (Windows internal process)
    0	    27	 15560	   crashpad-handler
    0	   100	 15592	shared-process
    0	    48	 18744	   utility-network-service
    0	    91	 22348	fileWatcher [1]
    0	    88	 23432	window [2] (Issue Reporter)
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (lotto.py - openCV - Visual Studio Code)
|    Folder (openCV): 6 files
|      File types: py(3) pyc(1)
|      Conf files:;
```

</details>
<details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
dscodegpt|Dan|2.1.12
better-cpp-syntax|jef|1.17.2
debug-tracker-vscode|mcu|0.0.15
vscode-language-pack-de|MS-|1.79.2023061409
isort|ms-|2022.8.0
python|ms-|2023.10.1
vscode-pylance|ms-|2023.6.20
cpptools|ms-|1.16.1
cpptools-extension-pack|ms-|1.3.0
powershell|ms-|2023.6.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
2e4cg342:30602488
pyind779:30671433
89544117:30613380
pythonsymbol12:30671437
showlangstatbar:30737416
vsctsb:30748421
pythonms35:30701012
03d35959:30757346
pythonfmttext:30731395
pythoncmv:30756943
fixshowwlkth:30771522
pythongtdpath:30769146
bgfeh915:30769767
dh2dc718:30770000
pythonidxpt:30772539
pythondjangots:30772535

```

</details>

**Comment by gjsjohnmurray** [comment]
Do you use McAfee antivirus? If so please see https://github.com/microsoft/vscode/issues/178962 which is currently a pinned issue [here](https://github.com/microsoft/vscode/issues).

**Comment by Pakerusa** [comment]
Thanks fixed the issue....
