### ISSUE TITLE
Upload configuration (for Bing settings search)

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#185724]
This task failed:

https://monacotools.visualstudio.com/DefaultCollection/Monaco/_build/results?buildId=219534&view=logs&j=3792f238-f35e-5f82-0dbc-272432d9a0fb&t=07088cf7-fede-5f74-0d50-155edd53af7d&l=16

But I also thought we would not support Bing settings search anymore? So can we remove this task?

**Comment by roblourens** [comment]
I removed it last week
