### ISSUE TITLE
Syntax highlighting broken after member function with requires clause with less comparison 

### ISSUE THREAD

**Issue by lukas-lang** [microsoft/vscode#185728]
(Note: This was originally submitted to the cpp-tools repo as https://github.com/microsoft/vscode-cpptools/issues/11100)
Consider the following snippet:

```cpp
template <int n>
struct S{        
    int foo() requires(n == 2)
    {
        return 2;
    }

        
    int foo() requires(n < 2)
    {
        return 2;
    }

private:
    int b;
};
```

The syntax highlighting is completely broken after the second `requires` clause:

![image](https://github.com/microsoft/vscode-cpptools/assets/33105866/732a2199-a239-4412-975e-cefd1a057f06)

Expected behavior:
The syntax highlighting should continue to work as normal, as it does if you replace the `<` with `>`:
![image](https://github.com/microsoft/vscode-cpptools/assets/33105866/5191f538-018a-4c14-9b80-7ec7cf4289e6)

Version: 1.79.2
Commit: 695af097c7bd098fbf017ce3ac85e09bbc5dda06
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36 Edg/114.0.1823.51
Embedder: vscode.dev

**Comment by alexr00** [comment]
I've moved this issue to https://github.com/jeff-hykin/better-cpp-syntax/issues/638, which is the repo that well pull our C++ syntax highlighting grammar from. Sorry for the repo ping pong!
