### ISSUE TITLE
F# highlighting - open namespace not colored correctly when namespace starts with lowercase letter

### ISSUE THREAD

**Issue by rojepp** [Microsoft/vscode#18572]
- VSCode Version: 1.8.1
- OS Version: OSX

<img width="193" alt="screenshot 2017-01-15 18 34 36" src="https://cloud.githubusercontent.com/assets/445888/21964754/a58a9bdc-db52-11e6-8a9a-8f300238da70.png">

**Comment by rojepp** [comment]
This is upstream - https://github.com/ionide/ionide-atom-fsharp/issues/256

The fix still needs to be manually copied here though.

**Comment by Krzysztof-Cieslak** [comment]
According to https://github.com/Microsoft/vscode/issues/17820 F# grammar will be now taken from https://github.com/ionide/ionide-fsgrammar. Please create issue there.

**Comment by rojepp** [comment]
Posted a bug there https://github.com/ionide/ionide-fsgrammar/issues/22

**Comment by Krzysztof-Cieslak** [comment]
I've fixed the grammar. 

Is the process of updating it here somehow automated or we should PR changes here every time we change grammar in Ionide's repo? CC: @aeschli

**Comment by aeschli** [comment]
We have a update script.
in `/extensions/fsharp` invoke `npm run update-grammar`
after that the test must be run `/scripts/test-integration`

Just ping me then I run it. No need for a PR.

**Comment by aeschli** [comment]
fixed by 90a8cdb324932adeaa7cd00f8f60c356d1d9b02a
