### ISSUE TITLE
Select Multiline

### ISSUE THREAD

**Issue by AlexOConnorHub** [microsoft/vscode#185787]
Does this issue occur when all extensions are disabled?: Yes

- VS Code:
```
Version: 1.80.0-insider (user setup)
Commit: 636dbcff557af8aa088ae118b1a094dce6632ce7
Date: 2023-06-21T08:26:26.328Z
Electron: 22.3.13
ElectronBuildId: 21803499
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Windows_NT x64 10.0.19045
```

Steps to Reproduce:

##### Disable Extensions

1. Navigate to Extensions
1. Select "Disable All Installed Extensions"
1. Reload

##### Replicate Issue

1. Create new file
1. Put multiple lines of text (ex: `# This is sample data` copy/pasted)
1. Move mouse to end of a line (or anywhere over text)
1. Click primary mouse button (Left click)
1. Drag cursor to different line
1. Release primary mouse button

Expected outcome: all text is selected between cursor beginning and ending location (beginning and ending being the point where the primary button was clicked and released respectivly).
![image](https://github.com/microsoft/vscode/assets/43659595/c17edad4-2b88-4b8d-8bb7-4063ac3d7899)

Actual outcome:
Multiple cursors were created on each line, selecting the columns from each line individually.
![image](https://github.com/microsoft/vscode/assets/43659595/921c0522-919d-4dcd-817f-8b374643f267)

The expected outcome example was done in

```
Version: 1.79.2 (user setup)
Commit: 695af097c7bd098fbf017ce3ac85e09bbc5dda06
Date: 2023-06-14T08:57:04.379Z
Electron: 22.5.7
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Windows_NT x64 10.0.19045
```

**Comment by gjsjohnmurray** [comment]
Does a `Column Selection` message show in your status bar?

**Comment by AlexOConnorHub** [comment]
Yes. When I clicked on it, the expected behavior happened :facepalm:. Thanks for taking the time to point that out to me. Have a good day, and thanks for supporting such an amazing tool!
