### ISSUE TITLE
html not colored

### ISSUE THREAD

**Issue by NeitCuhp** [microsoft/vscode#185716]
Type: <b>Feature Request</b>

My html is getting normal but affter I set up some extensions, the color of html has gone, but code of php, javascript, css is still remaining, how can I do that, please help me!

VS Code version: Code 1.79.2 (695af097c7bd098fbf017ce3ac85e09bbc5dda06, 2023-06-14T08:57:04.379Z)
OS version: Windows_NT x64 10.0.22621
Modes:

**Comment by gjsjohnmurray** [comment]
Please use the Start Extension Bisect command to investigate which extension is causing the problem.

**Comment by aeschli** [comment]
Please find out which extension causes this. The `Start Extension Bisect` command is useful for that.
