### ISSUE TITLE
fish shell integration stopped working

### ISSUE THREAD

**Issue by alexanderniebuhr** [microsoft/vscode#185758]
Type: <b>Bug</b>

the fish shell integration stopped working with the newest insider update

```
fish: Unknown command: __init_vscode_shell_integration
fish: 
                __init_vscode_shell_integration
                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
in function '__preserve_fish_prompt'
        called on line 125 of file /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/contrib/terminal/browser/media/fish_xdg_data/fish/vendor_conf.d/shellIntegration.fish
from sourcing file /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/contrib/terminal/browser/media/fish_xdg_data/fish/vendor_conf.d/shellIntegration.fish
        called on line 248 of file /opt/homebrew/Cellar/fish/3.6.1/share/fish/config.fish
from sourcing file /opt/homebrew/Cellar/fish/3.6.1/share/fish/config.fish
        called during startup
```

VS Code version: Code - Insiders 1.80.0-insider (636dbcff557af8aa088ae118b1a094dce6632ce7, 2023-06-21T08:21:53.800Z)
OS version: Darwin arm64 23.0.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Max (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|4, 4, 3|
|Memory (System)|64.00GB (8.25GB free)|
|Process Argv|--crash-reporter-id 945a6c23-6933-4234-81df-47ad843c173f|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (24)</summary>

Extension|Author (truncated)|Version
---|---|---
op-vscode|1Pa|1.0.4
astro-vscode|ast|2.0.18
vscode-eslint|dba|2.4.1
dprint|dpr|0.14.0
prettier-vscode|esb|9.15.0
copilot-chat|Git|0.3.2023062101
copilot-labs|Git|0.14.884
copilot-nightly|Git|1.90.175
vscode-github-actions|git|0.25.8
vscode-pull-request-github|Git|0.67.2023062109
symbols|mig|0.0.12
markdoc|moh|0.6.2
moon-console|moo|0.6.1
vscode-dotnet-runtime|ms-|1.6.0
datawrangler|ms-|0.10.0
js-debug-nightly|ms-|2023.6.1917
vscode-js-profile-flame|ms-|1.0.5
vscode-typescript-next|ms-|5.2.20230620
rose-pine|mvl|2.8.0
deoptexplorer-vscode|rbu|1.1.2
vscode-yaml|red|1.13.0
vscode-stylelint|sty|1.2.4
wvsc-serendipity|wic|0.105.0
pretty-ts-errors|yoa|0.4.1

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythontb:30258533
vsc_aa:30263845
pythonptprofiler:30281269
vshan820:30294714
vscod805:30301674
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30404738
vsclangdf:30492506
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30618038
pylantcb52:30590116
pyind779:30611226
pythonsymbol12:30651887
2i9eh265:30646982
showlangstatbar:30737417
pythonms35:30671666
03d35959:30757351
57b77579:30687741
pythonfmttext:30716741
pythoncmvfstr:30726892
fixshowwlkth:30771523
showindicator:30766888
pythongtdpath:30726887
i26e3531:30769768
gsof1:30771514
dh2dc718:30770000
pythonidxpt:30768918
pythondjangots:30768917
pythonnocebcf:30766856
copilotsettingt:30767686
e537b577:30772214

```

</details>

**Comment by lionello** [comment]
same as #185750
