### ISSUE TITLE
Cannot download folders (or large files)

### ISSUE THREAD

**Issue by drmrbrewer** [microsoft/vscode#185783]
![image](https://github.com/microsoft/vscode/assets/9009792/aaca121b-4e88-4d94-b37d-62799f65e462)

Referring to [this issue](https://github.com/microsoft/vscode/issues/120908) (which is closed and locked), if it's a limitation of Chrome which means that we can't download directly into the Downloads folder (but can download into other folders, even a sub-folder within Downloads), might it be a nice idea at least to make the dialog a little more informative, like telling the user that they cannot download directly into Downloads, but can into a sub-folder, or something like that?  The dialog at present is slightly cryptic, and doesn't really explain why a normal folder (Downloads) apparently contains these mysterious "system files", or whether there is any way around it.  If the dialog itself is from Chrome, maybe a dialog from vscode could appear beforehand?  There is also a related [issue here](https://github.com/coder/code-server/issues/4646), where the same dialog appears.

**Comment by bpasero** [comment]
Please report this to the respective browser (Chrome), they bring up this dialog.
