### ISSUE TITLE
JavaScript formatter: Place else on separate line

### ISSUE THREAD

**Issue by poke** [Microsoft/vscode#18570]
I would like to request an option to make the JavaScript formatter place an `else` on its own line. There does not appear to be an option for this in the vscode settings so far. Consider the following as an example:

```js
if (x) {
    console.log('foo');
}
else {
    console.log('bar');
}
```

Currently, the JavaScript formatter converts this into the following:

```js
if (x) {
    console.log('foo');
} else {
    console.log('bar');
}
```

Note that this behavior is also inconsistent with the TypeScript formatter which formats the latter code into the former format.

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript#15061
