### ISSUE TITLE
reverted custom editor for untitled files will stay open after shutdown

### ISSUE THREAD

**Issue by amunger** [microsoft/vscode#185796]
1. create a new notebook (or new image with Luna editor) and also a new text file
2. make all the editors dirty
3. ensure hotexit is off
4. close the window, selecting "don't save" when prompted to revert all working copies
5. re-open the window - the text editor is gone (closed during shut down), but the other editors are open and blank.

**Comment by amunger** [comment]
This is why I thought the revert behavior was broken in https://github.com/microsoft/vscode/pull/184757#issuecomment-1600058339. 
I think it would be much better if an interactive window closed when it was reverted.

**Comment by bpasero** [comment]
@amunger this is really up to the editor itself to decide whether to close the editor when the underlying working copy is disposed or not. Generally working copies try to stay as agnostic as possible to editors. There is only very few exceptions when it comes to restoring backups.

Untitled editors listen to working copies getting disposed to self-dispose:

https://github.com/microsoft/vscode/blob/4db4ae5f98394fac8ab6c7256e119386935511a3/src/vs/workbench/services/untitled/common/untitledTextEditorInput.ts#L59-L60

I suggest you go down a similar path. 

fyi @mjbvz for custom editors

**Comment by amunger** [comment]
fixed for notebook/Interactive window editor. @mjbvz - did you want another issue to track this for custom editors?

**Comment by mjbvz** [comment]
@amunger Yes that would be great
