### ISSUE TITLE
Allow `contributes.views` into Comments panel / `workbench.panel.comments`

### ISSUE THREAD

**Issue by hermannloose** [microsoft/vscode#185767]
`contributes.views` at the moment allows contributing to the built-in `explorer`, `scm`, `debug`, and `test` view containers, as well as custom view containers. We would additionally like the capability to contribute a view to the `workbench.panel.comments` view container for the Comments panel.

Our extension has a need to display contextual information and actions alongside the Comments panel, e.g. a button to publish comments drafted by the user, if applicable. We are aware that commands can be contributed to the Comments panel already, but discoverability of commands that we put there has been extremely low for our users in the past year.

Since the Comments panel lives in the bottom panel, the alternative of contributing a web view with actions to e.g. the Explorer or SCM view container unfortunately leads to an inconsistent experience where this view is not guaranteed to show up together with the Comments panel automatically, as it depends on which sidebar the user happens to have open.

While users can manually drag any view into the Comments panel view container, they are unlikely to do so on their own initiative. `ViewDescriptorService` allows programmatically moving views in this manner, but is not available to extensions.

cc @JonasMa @laurentlb @a-stewart

**Comment by alexr00** [comment]
This seems reasonable. Tentatively adding for July.

**Comment by alexr00** [comment]
Moving to the backlog. I would also accept a PR for this!

**Comment by alexr00** [comment]
Took a quick look into this and there are two parts:
1. Add the contribution point
2. Register the Comments view container (we don't do this until there are comments in the workspace right now).

The first part can be seen in https://github.com/microsoft/vscode/commit/cc9d4ffed8790bf7fe984c0e5e92e6c6166348e3

**Comment by alexr00** [comment]
If this is still something folks want then I will reopen!
