### ISSUE TITLE
[themes] support preferredDarkIconTheme and preferredLightIconTheme

### ISSUE THREAD

**Issue by wzhudev** [microsoft/vscode#185727]
`preferredDarkColorTheme` and `preferredLightColorTheme` are very convenient. However file icon themes don't change with the systems' light/dark theme. Some file icons extensions (such as Catppuccin) provide multi sets of icons and icons and dark icons on a light theme are barely visible. 

Icons for the dark mode and a light theme:
<img width="300" alt="截屏2023-06-21 13 58 50" src="https://github.com/microsoft/vscode/assets/12122021/75fdc260-d477-4078-a47c-71037873108a">

Icons for the light mode and the light theme:
<img width="302" alt="截屏2023-06-21 14 01 15" src="https://github.com/microsoft/vscode/assets/12122021/43f3aac8-45a0-4546-b5dc-de315ac1affe">

**Comment by wzhudev** [comment]
I am glad to submit a PR if this feature request sounds good to you.

**Comment by manuthebyte** [comment]
Any update on this? Would love that!

**Comment by manuthebyte** [comment]
Til' someone implements this I decided to make an extension (Wanted to try that anyways)
Get it [here](https://marketplace.visualstudio.com/items?itemName=manuthebyte.dynamic-icon-theme&ssr=false#version-history) or check out [the repo](https://github.com/manuthebyte/vscode-change-icon-theme) :)

**Comment by wzhudev** [comment]
Anyone who wants this feature can open another feature request for this.
