### ISSUE TITLE
Tab sizing option fixed

### ISSUE THREAD

**Issue by frankforte** [microsoft/vscode#185766]
Type: <b>Feature Request</b>

I am very happy that you introduced this feature, for quickly closing many tabs:
`workbench.editor.tabSizingFixedMaxWidth`

However, with fixed width, the tabs become so small that it is hard to distinguish files with the same first 3 or 4 characters. Can you also add a minimum width setting? `workbench.editor.tabSizingFixedMinWidth`

This would allow each developer to set a minimum width based on their file naming convention (e.g. if they have many files starting with the first 6 characters, they can set the minimum to see at least 8 or 9 characters).

Thank you.

VS Code version: Code 1.79.2 (695af097c7bd098fbf017ce3ac85e09bbc5dda06, 2023-06-14T08:57:04.379Z)
OS version: Windows_NT x64 10.0.19045
Modes:

**Comment by bpasero** [comment]
fyi @jacekkopecky if you want to provide a PR for this kind of functionality.
