### ISSUE TITLE
Crashing

### ISSUE THREAD

**Issue by ac12644** [microsoft/vscode#185730]
Type: <b>Bug</b>

I have been experiencing frequent occurrences of the issue where the Visual Studio Code window terminates unexpectedly with the reason "crashed" and the error code "5".

<img width="759" alt="Screenshot 2023-06-21 at 09 09 40" src="https://github.com/microsoft/vscode/assets/43683452/e0565bb1-c201-4908-a959-df61f0e64ece">

VS Code version: Code 1.79.2 (Universal) (695af097c7bd098fbf017ce3ac85e09bbc5dda06, 2023-06-14T08:58:52.392Z)
OS version: Darwin arm64 22.5.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|5, 6, 6|
|Memory (System)|8.00GB (0.11GB free)|
|Process Argv|--crash-reporter-id d3b98ed7-e2c9-416c-8722-dc57d98ed5da|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (21)</summary>

Extension|Author (truncated)|Version
---|---|---
docify|AIC|1.3.4
markdown-preview-github-styles|bie|2.0.2
simple-react-snippets|bur|1.2.7
gltf-vscode|ces|2.4.0
ccs-flutter-color|cir|1.0.2
gitlens|eam|14.0.1
prettier-vscode|esb|9.15.0
go|gol|0.39.0
composer-support-client|Hyp|0.19.12
ibmcloud-account|IBM|1.0.6
solidity|Jua|0.0.165
git-graph|mhu|1.30.0
isort|ms-|2022.8.0
python|ms-|2023.10.1
jupyter|ms-|2023.5.1001582324
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.15
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-slideshow|ms-|0.1.5
tabnine-vscode|Tab|3.6.60
vscode-import-cost|wix|3.3.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vstes627:30244334
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
282f8724:30602487
pyind779:30671433
f6dab269:30613381
vscrp:30673768
pythonsymbol12:30671437
showlangstatbar:30737416
vsctsb:30748421
pythonms35:30701012
03d35959:30757346
24365598:30736109
pythonfmttext:30731395
pythoncmv:30756943
fixshowwlkth:30771522
pythongtdpath:30769146
bgfeh915:30769767
dh2dc718:30770000
pythonidxpt:30772539
pythondjangots:30772535

```

</details>

**Comment by deepak1556** [comment]
Can you share the crash logs following the steps at https://github.com/microsoft/vscode/wiki/Native-Crash-Issues#creating-a-crash-report

**Comment by ac12644** [comment]
Issue solved thanks:)

**Comment by rizkianakbar** [comment]
> Issue solved thanks:)

@ac12644 May I know how did you solve this issue? because I also experienced the same thing

**Comment by ac12644** [comment]
just updated my pc.

**Comment by ac12644** [comment]
@rizkianakbar  Again had this issue fixed by uninstalling the extension in vs studio. check by uninstalling extensions one by one.
