### ISSUE TITLE
only select input when it has changed

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#185706]
1. Use a screen reader
2. Run some request in the inline chat
3. 🐛 your input is selected and thus you hear it immediately after entering

This is because sometimes, for example, when `Fix with Copilot` is used, response info is inserted there. 

We should only select when it has changed

**Comment by meganrogge** [comment]
https://github.com/microsoft/vscode/assets/29464607/fa0a2d66-f5cd-406b-9623-ebcb3d545294

**Comment by meganrogge** [comment]
So if we use `aria alert` to announce the placeholder text when it is important to do so, we can keep the selection

**Comment by Tyriar** [comment]
This still happens:

![image](https://github.com/microsoft/vscode/assets/2193314/ea8c2d1b-f979-43c6-b2d3-6584975564fa)

NVDA

Version: 1.80.0-insider (user setup)
Commit: 4649b5333370139d161e7b5d4f78ca13741efa35
Date: 2023-06-28T08:01:04.380Z
Electron: 22.3.14
ElectronBuildId: 21893604
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Windows_NT x64 10.0.22621

**Comment by meganrogge** [comment]
We have a workaround now so it's fine that it gets selected
