### ISSUE TITLE
python snippet doesn't show up in jupyter notebook  on Mac

### ISSUE THREAD

**Issue by eromoe** [microsoft/vscode#185729]
/

Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:  latest
- OS Version: macOS 13.4

Steps to Reproduce:

1.  Sync vscode settings and extention between  Windows and mac
2. create a `xx.ipynb` file , edit it.
3. type a snippet name on vscode (win) ,  intelligently prompt suggestions ,  press enter insert this snippet. 
4. but on vscode(mac) , it doesn't .  Even type `shift + command + p` select  `insert snippet ` , it shows nothing . 

Same settings and snippets work on Windows.

**Comment by eromoe** [comment]
OK, I found that I need select a python kernel and run once, then vscode can prompt snippets. Is it right ?

**Comment by DonJayamanne** [comment]
Once the language of the cell has been set to `Python` you will get the snippets for Python languages.
If this doesn't work as expected please feel free to create a new issue or ping here.
