### ISSUE TITLE
VSCode "loses" virtual environment (in-project .venv folder)

### ISSUE THREAD

**Issue by slobentanzer** [microsoft/vscode#185876]
Does this issue occur when all extensions are disabled?: Difficult to test due to the random (?) nature of the issue

Version: 1.80.0-insider (Universal)
Commit: e8b22318bfab2e52d5dbceee767e8b4bfe9b5300
Date: 2023-06-22T05:38:43.259Z
Electron: 22.3.13
ElectronBuildId: 21803499
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Darwin arm64 21.6.0

I am using Poetry to install an environment into the project folder, in the `.venv` directory. VSCode prompts me to select it upon installation, it works fine. After some time, sometimes after running the app, while still in the same VSCode session, I cannot use the launch configuration to start the app any more, and VSCode prompts me to "Select Interpreter." In the list that appears (which contains conda environments, system environments), the in-project venv is not visible any more. Adding it to the venv path or entering the path manually in the Select Interpreter dialog does not work.

The only thing that works is reinstalling the environment, upon which VSCode recognises it again, and again prompts me to select it. Unfortunately, I don't even know where to begin troubleshooting this issue.

Thanks for your time. :)

**Comment by roblourens** [comment]
Please file this on the vscode-python extension repo, thanks
