### ISSUE TITLE
Randomly getting "Could not find the task '...'"

### ISSUE THREAD

**Issue by hediet** [microsoft/vscode#185892]
When trying to debug code oss or launch a task, sometimes I get this error:

![image](https://github.com/microsoft/vscode/assets/2931520/6f06dcd8-ac19-499d-afd4-4c737e69ff05)

After reloading the window often it works again.

**Comment by meganrogge** [comment]
I'm sure in this case that we haven't yet resolved the workspace tasks

**Comment by meganrogge** [comment]
saw it when I saw #173384 so pretty sure same root cause

/duplicate #173384

**Comment by meganrogge** [comment]
yeah the fix is in insider's @YHAMSTM not 1.80.1

**Comment by YHAMSTM** [comment]
Ok thanks! Sorry for the inconvenience
