### ISSUE TITLE
Performance Improvement Suggestion: Only Rerender Sticky Scroll When State Is Different

### ISSUE THREAD

**Issue by hediet** [microsoft/vscode#185884]
In `stickyScrollWidget.ts` there is `setState`, which seems to be called every time the scroll event of the editor fires.
That method seems to clear the dom node and reconstruct it unconditionally.

When smooth scrolling is turned on, the scroll event fires many times per second and the `setState` call seems to take some time:

![chrome_vNZj2xVvRt](https://github.com/microsoft/vscode/assets/2931520/9537996f-4897-48d3-90b1-b5af282159b1)

I think if you would only rerender the sticky scroll widget when necessary (and generally try to minimize dom API accesses), we could improve the performance here easily.
I think `StickyScrollWidgetState` could have an equals method and `setState` would just do an early return if the new state equals the old state.

**Comment by aiday-mar** [comment]
Thanks for this remark. It is a very good optimization point.
