### ISSUE TITLE
Removed keybinding not trigger global hotkey

### ISSUE THREAD

**Issue by yunsii** [microsoft/vscode#185855]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.79.2
- OS Version: win 11

Steps to Reproduce:

1. Remove keybinding `f1`

![image](https://github.com/microsoft/vscode/assets/18096089/9f781ae2-74aa-41e9-8811-7d938d984514)

2. Press `f1` to trigger my global screenshot hotkey (snipaste app default hotkey), but it is not work

![keyboard troubleshooting](https://github.com/microsoft/vscode/assets/18096089/036dc094-2550-46e0-ae00-e42fc620b594)

**Comment by jrieken** [comment]
VS Code isn't consuming the keybinding as the logs show. I'd say the issue with the external tools, if the keybinding would be global it shouldn't be reaching VS Code - that how other global keybindings work (like cmd+space on mac)
