### ISSUE TITLE
Suggestion: open latest edited file when closing a file instead of closing/emptying the view

### ISSUE THREAD

**Issue by warpdesign** [Microsoft/vscode#1858]
Right now, let's say I open file1, then file2, then file3 (on the same view).

If I close the current file (either by clicking on the cross on the working files panel, or by choosing "close file" in the palette command), the file will be closed, but the view will be empty.

Worse, if the opened file was on the right panel, the panel would be closed when closing the file: I think "close file" shouldn't modify the editor's layout.

What about opening the latest opened file in the history (alt+tab) when closing a file instead of emptying/closing current view ?

There could be an option for that if it's not the default one.

**Comment by bpasero** [comment]
#1044
