### ISSUE TITLE
[Launch Configuration] Could not find the task "<task_name>"

### ISSUE THREAD

**Issue by YHAMSTM** [microsoft/vscode#185835]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.79.2
- OS Version: Windows 10

This issue is quite difficult to reproduce and only happens sometimes after a computer restart. Here is how I've experience it for the last time:

Steps to Reproduce:

1. Shutdown computer
2. Restart Visual Studio Code which will open multiple instances at the same time (here: 8 windows)
3. Start "launch configuration" which has a "preLaunchTask" available in "tasks.json"
4. Error is thrown: "Could not find the task '<name>'"
5. Rename the task with a new name and save
6. Undo and save
7. Start "launch configuration", it magically starts

Best regards,
Yanis

**Comment by roblourens** [comment]
@meganrogge  This is just calling into the task service, I don't think there is much custom logic on the debug side for this feature
