### ISSUE TITLE
Azure-insider not working with Azure Tools v1.2.0

### ISSUE THREAD

**Issue by scottschwab2** [microsoft/vscode#185809]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 
- OS Version: 

Steps to Reproduce:

This is the insider build, so I am not surprised the Azure Tools does not yet work, but for the record.

Azure extension not working in Azure Insider build, on Windows 10, Mac OS, or debian Linux

Version: 1.80.0-insider (user setup)
Commit: 636dbcff557af8aa088ae118b1a094dce6632ce7
Date: 2023-06-21T08:26:26.328Z
Electron: 22.3.13
ElectronBuildId: 21803499
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Windows_NT x64 10.0.19044

Thanks,
Bradley Scott Schwab

**Comment by sandy081** [comment]
Please report the issue against the Azure Extension repository/author.
