### ISSUE TITLE
Feature request: keybindings, single/multi line selecting condition for the when clause

### ISSUE THREAD

**Issue by marcelopm** [Microsoft/vscode#18585]
- VSCode Version: 1.8.1
- OS Version: Ubuntu 16.10

It would be great to have a single/multi line selection condition for the when clause on keybindings.json

This would allow to create smart keybindings, such as:

If a single line is selected, and I press CTRL+C, // is added to the beginning of the line. Otherwise, if multiple lines are selected instead, the selection is wrapped with /* */

example:
```
$a = 1; <-- selected line
$b = 2;
```
becomes:
```php
//$a = 1;
$b = 2;
```
Otherwise:
```php
$a = 1; <-- selected line
$b = 2; <-- selected line
```
becomes:
```php
/*$a = 1;
$b = 2;*/
```

**Comment by mjbvz** [comment]
Extensions can set context keys with the `setContext`. However, in most cases, it would be easier to use a single command that adapts dynamically to the current selection
