### ISSUE TITLE
Tasks sometimes ask me for which task to run

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#185862]
In some cases when I execute the default build task (`workbench.action.tasks.build`), I see a picker asking me for the task to pick. Then after a window reload or restart, this does not happen anymore.

Do we have an understanding of what this is?

![Recording 2023-06-22 at 14 11 31](https://github.com/microsoft/vscode/assets/900690/ffbb763b-4c0a-49db-ae73-527be41f44b7)

**Comment by meganrogge** [comment]
was this in the latest insider's today @bpasero ?

same as https://github.com/microsoft/vscode/issues/183989

having a hard time reproducing

**Comment by bpasero** [comment]
@meganrogge yes, todays insider. but tbh have seen this for months sporadically. could it be timing related based on extension startup timing?

**Comment by meganrogge** [comment]
Do both of you have task reconnection enabled? 

And when this happens, do you already have the build task running? 

And does the default build task get run?

**Comment by meganrogge** [comment]
I think this is related to task reconnection. @roblourens can you repro with that disabled?

**Comment by bpasero** [comment]
I did not even know I could disable task reconnection, but yes I heavily rely on the build tasks showing up again in the status bar when I do a window reload. But when this issue appears, I am quite certain that the build tasks are not showing in the status bar.
