### ISSUE TITLE
Undue C++ namespace std error

### ISSUE THREAD

**Issue by vitorfff** [microsoft/vscode#185878]
Type: <b>Bug</b>

Error from Closed Issue  #184167 still persists.

In C++ code, even with "using namespace std", code still sometimes shows "cout is ambiguous" error message. When clicking to run code it runs fine. Also if window is reopened error message disappears.

Code:
`#include <iostream>
using namespace std;

int main()
{
    cout << "test string" << endl;
    cout << "another string";
    

    return 0;
}`

EDIT: For some reason Github is not properly displaying pasted code. And thus it is missing the iostream header. Make sure to include that when copying/pasting the code.

<img width="591" alt="Screen Shot 2023-06-22 at 6 58 58 AM" src="https://github.com/microsoft/vscode/assets/65467998/08181e14-ffac-4080-bbc4-14ff0d47382f">
<img width="493" alt="Screen Shot 2023-06-22 at 6 59 05 AM" src="https://github.com/microsoft/vscode/assets/65467998/e79e91f1-b5a4-46d4-8d2f-ecee70537b94">

VS Code version: Code - Insiders 1.80.0-insider (636dbcff557af8aa088ae118b1a094dce6632ce7, 2023-06-21T08:21:53.800Z)
OS version: Darwin arm64 21.6.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|8.00GB (0.08GB free)|
|Process Argv|--crash-reporter-id f324f5e2-5bae-4725-be16-5efc5b642d47|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
code-runner|for|0.12.0
copilot-chat|Git|0.3.2023062201
copilot-nightly|Git|1.92.179
cpptools|ms-|1.16.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythontb:30258533
pythonptprofiler:30281269
vshan820:30294714
vscod805:30301674
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30404738
py29gd2263cf:30773604
vsclangdf:30492506
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30618038
pylantcb52:30590116
pyind779:30611226
pythonsymbol12:30651887
a9j8j154:30646983
showlangstatbar:30737417
pythonms35:30671666
03d35959:30757351
7ij38806:30687742
pythonfmttext:30716741
pythoncmvfstr:30726892
fixshowwlkth:30771523
showindicator:30766888
pythongtdpath:30726887
bgfeh915:30769767
gsof1:30771514
dh2dc718:30770000
pythonnosmt12:30773574
pythonidxpt:30768918
pythondjangots:30768917
pythonnoceb:30766855
copilotsettingt:30767686
e537b577:30772214

```

</details>

**Comment by isidorn** [comment]
@sean-mcmanus  Sorry about that. Same as https://github.com/microsoft/vscode/issues/185304#issuecomment-1609214616
