### ISSUE TITLE
Mermaid support in Markdown preview

### ISSUE THREAD

**Issue by btoo** [microsoft/vscode#185819]
[GitHub supports rendering Mermaid diagrams in Markdown files](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-diagrams#creating-mermaid-diagrams). It would be nice to be able to develop these Markdown files in VSCode using [its Markdown preview](https://code.visualstudio.com/docs/languages/markdown#_markdown-preview)

**Comment by mjbvz** [comment]
Try this extension https://marketplace.visualstudio.com/items?itemName=bierner.markdown-mermaid
