### ISSUE TITLE
High CPU Usage

### ISSUE THREAD

**Issue by wrridgeway** [microsoft/vscode#185887]
Type: <b>Performance Issue</b>

vscode is using 40% of my cpu with a single .txt file open. none of my extensions should be causing this issue, most are published by MS.

VS Code version: Code 1.79.2 (695af097c7bd098fbf017ce3ac85e09bbc5dda06, 2023-06-14T08:57:04.379Z)
OS version: Windows_NT x64 10.0.22000
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.76GB (21.49GB free)|
|Process Argv|--crash-reporter-id afd9316d-36d9-4fc2-ab37-0b33a5a7dd7d|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	   104	  7388	code main
    0	   108	   748	extensionHost [1]
    0	    76	  2536	ptyHost
    0	    75	  7624	fileWatcher [1]
    0	    42	  8100	   utility-network-service
    0	    27	 13100	   crashpad-handler
   15	   248	 17108	window [1] (NOTES.txt - Documents - Visual Studio Code)
    8	    95	 23032	window [3] (Issue Reporter)
    0	    95	 27372	shared-process
    0	   124	 27624	   gpu-process
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (NOTES.txt - Documents - Visual Studio Code)
|    Folder (Documents): more than 22457 files
|      File types: py(6350) pyc(6126) dat(841) h(493) txt(414) pyi(314)
|                  pyd(282) csv(241) mat(123) pxd(102)
|      Conf files: makefile(2) settings.json(1);
```

</details>
<details><summary>Extensions (17)</summary>

Extension|Author (truncated)|Version
---|---|---
empty-indent|Dmi|0.2.0
vscode-sqlfluff|dor|2.3.4
remotehub|Git|0.58.0
mssql|ms-|1.19.1
isort|ms-|2022.8.0
python|ms-|2023.10.1
vscode-pylance|ms-|2023.6.30
jupyter|ms-|2023.5.1101742258
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.15
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-slideshow|ms-|0.1.5
remote-ssh|ms-|0.102.0
remote-ssh-edit|ms-|0.86.0
remote-explorer|ms-|0.4.0
remote-repositories|ms-|0.36.0
vscode-autohide|sir|1.0.7

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
py29gd2263:30773603
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
vscccc:30610679
2e4cg342:30602488
pyind779:30671433
89544117:30613380
vscrp:30673768
pythonsymbol12:30671437
2i9eh265:30646982
showlangstatbar:30737416
vsctsb:30748421
pythonms35:30701012
a2ce3375:30757347
pythonfmttext:30731395
pythoncmv:30756943
fixshowwlkth:30771522
pythongtdpath:30769146
i26e3531:30769768
dh2dc718:30770000
pythonidxptcf:30772540
pythondjangotscf:30772537
pythonnocebcf:30773527

```

</details>

**Comment by wrridgeway** [comment]
I can't say for sure when this started for sure. Teams is also maxing out my CPU whenever it's open, currently. Last few days is my best guess.

**Comment by chadacious** [comment]
I was struggling as well. I found that up to version 1.77.3 cpu usage is normal (negligible when idle). But versions after that, I get 30% cpu usage at idle. It seems ok if I just open VSCode with no folder or file. But I can create an empty folder on my local drive, open that folder in VSCode (no files) and it will spin up the CPU to between 15%-30% and stay there indefinitely. No extensions, fresh install of vscode. Processes just shows the window taking up all the CPU. Couldn't figure it out so just reverted to 1.77.3 for now.

**Comment by chadacious** [comment]
I concur. Upgraded back to 1.79.2 and I'm not seeing high CPU Usage now either. Strange but seems resolved for now.

**Comment by roblourens** [comment]
Sure, let me know if you see it again
