### ISSUE TITLE
Vscode opens many Connect to GitHub windows

### ISSUE THREAD

**Issue by cveld** [microsoft/vscode#185843]
Does this issue occur when all extensions are disabled?: Yes

Version: 1.79.2 (user setup)
Commit: 695af097c7bd098fbf017ce3ac85e09bbc5dda06
Date: 2023-06-14T08:57:04.379Z
Electron: 22.5.7
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Windows_NT x64 10.0.22621

Steps to Reproduce:

1. Set up a workspace with many repos
2. Invalidate credentials
3. Reopen vscode

You will see an experience comparable to the following screenshot:

![image](https://github.com/microsoft/vscode/assets/6196260/6fa8238b-caf7-4e82-a716-a46316eb5321)

The vscode github integration just naively triggers a separate process for all authentication failures, which spawns a huge set of windows.

**The ask**
Maybe the vscode github integration can be a bit smarter and hold off that many windows. Maybe be a list should appear with all repos that require reauthentication and the user can then start top to bottom revalidating them.
Actually the out of band behavior is a bit user-unfriendly, regularly I don't notice the additional windows that have popped up at the background.

The github authentication experience is a bit less user-friendly than the azure active directory authentication. As I am using many chrome user profiles it is not always the right profile that is opened when I click "Sign in with your browser". The device code flow obviously is even harder. 

Summarized I would say this is a minor issue. This is not blocking my workflow. It is just an area where the vscode git integration can be improved.

**Comment by TylerLeonhardt** [comment]
VS Code doesn't own this dialog. I believe this is shown by git/[gcm](https://github.com/git-ecosystem/git-credential-manager)... it's possible that vscode may be running a git command that causes git/gcm to show this dialog though.
