### ISSUE TITLE
Visual Studio Code query

### ISSUE THREAD

**Issue by dbeaver12** [microsoft/vscode#185849]
Hi,
With ref. to a ticket raised on MMU system(<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/46058578/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/46058578/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">

71405931
--

</body>

</html>
) we would like to know a few questions prior to its use in one of our departments in Manchester Metropolitan University –
1. When was software last updated
2. Is software still on active development
3. Are the software provider committed to patching the software in event of security incident or known security vulnerabilities?
We would also like to know a list of queries for our Info sec team regarding<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/46058578/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/46058578/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">

Visual   Studio Code
--

</body>

</html>

Thanks ,

Jesu

Jesu Mathew 
Software Licensing Administrator

**Comment by chrisdias** [comment]
You can find information on our update cadence (daily/monthly) here: https://code.visualstudio.com/docs/setup/setup-overview. 

Yes, the product actively developed, check the Code tab of the repo, you can see the commits.

Yes, we provide updates for security issues in both Stable and Insider releases. For example, see the release notes for 1.80.2 at the top of the 1.80 release notes: https://code.visualstudio.com/updates/v1_80
