### ISSUE TITLE
Wrong autocompletion

### ISSUE THREAD

**Issue by smddzcy** [Microsoft/vscode#18580]
- VSCode Version: Code 1.8.1 (ee428b0eead68bf0fb99ab5fdc4439be227b6281, 2016-12-19T14:42:49.304Z)
- OS Version: Darwin x64 15.6.0
- Extensions:

|Extension|Author|Version|
|---|---|---|
|beautify|HookyQR|0.7.3|
|vscode-eslint|dbaeumer|1.2.2|
|code-runner|formulahendry|0.6.5|
|ide-purescript|nwolverson|0.6.3|
|language-purescript|nwolverson|0.1.1|
|vscode-coffeelint|slb235|0.0.2|
|react-beautify|taichi|0.3.0|
|vscode-react-native|vsmobile|0.2.5|
|JavaScriptSnippets|xabikos|1.2.0|

---

Steps to Reproduce:

1. Write something that has an autocompletion and has a dot (.) in it.
2. After inserting the dot, autocomplete the rest (by pressing _Enter_ or _Tab_ or your custom key, doesn't matter).
3. You should see that the autocompletion adds the part before the dot as well, which is undesirable. 

Here are 2 explanatory images.

Before autocompletion:
![screen shot 2017-01-16 at 00 04 48](https://cloud.githubusercontent.com/assets/13895224/21966166/63bab58e-db7f-11e6-8e7b-fe052e8c5c8f.png)

After autocompletion: (I press _Enter_, and VSCode autocompletes to this)
![screen shot 2017-01-16 at 00 04 54](https://cloud.githubusercontent.com/assets/13895224/21966165/63b78332-db7f-11e6-973d-db4f179a6d7e.png)

**Comment by dbaeumer** [comment]
@jrieken this is under the control of the purescript language provider. Right? They simply need to craft the right text edit. I know that we once discussed if VS Code should do the by default. Do you have any final thoughts here?

**Comment by jrieken** [comment]
Yes - the language provider must set the replace range for each completion item. @smddzcy Please file this issue against the extension you are using
