### ISSUE TITLE
GPG Passphrase will not prompt if the terminal height is small

### ISSUE THREAD

**Issue by khusika** [microsoft/vscode#185838]
Does this issue occur when all extensions are disabled?: **Yes**

- VS Code Version:       1.79.2
- OS Name:                   Microsoft Windows 11 Home Single Language
- OS Version:                10.0.22621 N/A Build 22621

Related Issues: #160007 #154503 #130415

Steps to Reproduce Bugs:

1. Open folder with `.git` in it
2. Set terminal height as short as possible
3. Do commit with GPG signing `-S` e.x
    `git commit -S -m "test gpg"`
    or
    `git commit --amend -S -m "test gpg"`
4. Output will be like this:
    `error: gpg failed to sign the data`
    `fatal: failed to write commit object`

Steps to Reproduce Fixes:

1. Set terminal height as height as possible
2. Do commit with `-S`

See video below:
https://github.com/microsoft/vscode/assets/5193379/21e3fc26-ac8b-4f69-abdb-b4aee2985368

**Comment by Tyriar** [comment]
I think the right place to report this would be to git or whatever is driving the gpg dialog.

**Comment by khusika** [comment]
Just in case if someone looking for fixes, try to replace `pinentry-curses` with `pinentry-tty`
See https://superuser.com/a/1381147
