### ISSUE TITLE
can't put all windows in one instance

### ISSUE THREAD

**Issue by chenjie4255** [Microsoft/vscode#18590]
- VSCode Version: Code 1.8.1 (ee428b0eead68bf0fb99ab5fdc4439be227b6281, 2016-12-19T14:42:49.304Z)
- OS Version: Darwin x64 16.1.0
- Extensions:

|Extension|Author|Version|
|---|---|---|
|vscode-docker|PeterJausovec|0.0.7|
|code-gnu-global|austin|0.2.1|
|vscode-yaml-validation|djabraham|0.0.1|
|githistory|donjayamanne|0.1.4|
|python|donjayamanne|0.5.0|
|Go|lukehoban|0.6.51|
|cpptools|ms-vscode|0.9.2|
|csharp|ms-vscode|1.5.3|
|Ruby|rebornix|0.10.4|
|rst-vscode|tht13|1.3.0|
|vscode-apielements|vncz|0.2.0|

---

Steps to Reproduce:

1. files -> new window
2. the new window is opened in a new window(or instace?) which I remember should be placed in tab bar? I can't find the relevant setting...

**Comment by kaiwood** [comment]
The command labeled "New Window" new (obviously) open a new window.

If you want to open a new file in the tab bar inside the same window, you can use "Files -> New File".

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/15478
