### ISSUE TITLE
Cannot "remove" keyboard shortcuts for some built in commands.

### ISSUE THREAD

**Issue by jordwalke** [Microsoft/vscode#18597]
The following works well to remove a build in keyboard mapping.

```
  { "key": "cmd+k m",               "command": "-workbench.action.editor.changeLanguageMode" },

```

The following does not:

```
  { "key": "shift+cmd+s",           "command": "-workbench.action.files.saveAs"},
```

The reason I wanted to completely remove `shift+cmd+s` was to allow the terminal to intercept the `cmd+s/cmd+shift+s` keys when the terminal is focused. When the terminal is focused, there's no need to intercept the `cmd+s` shortcut especially.

**Comment by alexandrudima** [comment]
It is possible to remove any keybinding. 

However, if a keybinding is shown in a top level menu, it might be necessary to restart VS Code until the change takes effect.

**Comment by bpasero** [comment]
@jordwalke can you clarify where you did not see this keybinding to be removed?

**Comment by jordwalke** [comment]
> However, if a keybinding is shown in a top level menu, it might be necessary to restart VS Code until the change takes effect.


That could have been the issue, thanks.

**Comment by bpasero** [comment]
With upcoming 1.9 you no longer have to restart to see the changed keybindings.
