### ISSUE TITLE
Intellisense/suggestions don't work

### ISSUE THREAD

**Issue by coolCucumber-cat** [microsoft/vscode#185946]
Type: <b>Bug</b>

1. CSS container queries: VSCode hasn't ever recognised them but now Intellisense is completely broken for them. Media queries do work though, even though they're exactly the same.

2. Angle brackets don't self close and all the self-closing characters ()[]''{}"" can't be escaped with tab, you have to press the right arrow key. Maybe not a bug but it feels like you should be able to. If you create a snippet for it, it works, but then you can't surround text with them.

3. Suggestions in general are so terrible it has to be a bug, especially in JS and it doesn't go away with TS. It gives you suggestions for the most random weird things I have never typed in before just because they share the first letter like "getJSDocOverrideTagNoCache", "toUSVString", "stripVTControlCharacters", "collapseTextChangeRangesAcrossMultipleVersions" and "ChannelSplitterNode". Sometimes being more specific with a name suggests it lower on the list. "weit" suggests "WebkitCSSMatrix", "wakeLockSentinal" and "WritableStream" and not my own function "writeJson". It even got "writable" but not the function I just defined. And helpful suggestions like "if" don't make and if statement, it's just "if". Same with fn, for, etc. In CSS a lot of the time it doesn't even show you your variables at all. I guess that makes sense if the variable is in another file and it can't know about it but it works equally badly across all files.

4. That little lightbulb thing gives the dumbest suggestions too, like in JS it asks if you want to turn a => a * 2 into function(a){return a * 2}. No, I do not. And usually it's not even in the right place.

VS Code version: Code 1.79.2 (695af097c7bd098fbf017ce3ac85e09bbc5dda06, 2023-06-14T08:57:04.379Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz (8 x 3592)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.95GB (8.38GB free)|
|Process Argv|--crash-reporter-id b67b341d-41c8-4d1e-9396-3ff475cbda2c|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (20)</summary>

Extension|Author (truncated)|Version
---|---|---
laravel-extra-intellisense|ami|0.6.3
tsl-problem-matcher|amo|0.6.2
vscode-intelephense-client|bme|1.9.5
vscode-eslint|dba|2.4.0
vscode-command-runner|edo|0.0.124
prettier-vscode|esb|9.15.0
code-runner|for|0.12.0
vscode-autohotkey-plus-plus|mar|3.3.1
python|ms-|2023.10.1
vscode-pylance|ms-|2023.6.20
powershell|ms-|2023.6.0
laravel5-snippets|one|1.17.0
synthwave-vscode|Rob|0.1.15
laravel-artisan|rya|0.0.31
language-stylus|sys|1.16.0
intellicode-api-usage-examples|Vis|0.2.7
vscodeintellicode|Vis|1.2.30
volar|Vue|1.8.1
quokka-vscode|Wal|1.0.546
php-debug|xde|1.32.1

</details>

**Comment by jrieken** [comment]
Please try again and have one issue per bullet point

**Comment by coolCucumber-cat** [comment]
> Please try again and have one issue per bullet point

But it's all just different aspects of the same issue?

**Comment by jrieken** [comment]
No they are not. The light bulb is a different feature than bracket insertion or completions. CSS is a different language than JS
