### ISSUE TITLE
Enable data-breakpoints

### ISSUE THREAD

**Issue by Ernestopheles** [microsoft/vscode#185985]
I am missing a feature to set a halt globally when a variable changes its value or reaches a defined value.
It is only possible by setting a line breakpoint right now. I wish it could be set global.

VSCode PHP XDebug all latest versions.

**Comment by roblourens** [comment]
Data breakpoints are supported by vscode and the debug adapter protocol and need to be implemented by debug extensions, so you can file this against the debug extension
