### ISSUE TITLE
Windows10自带拼音输入法输入错误

### ISSUE THREAD

**Issue by senduo** [Microsoft/vscode#18592]
- VSCode Version: Code 1.8.1 (ee428b0eead68bf0fb99ab5fdc4439be227b6281, 2016-12-19T14:49:23.350Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

|Extension|Author|Version|
|---|---|---|
|vscode-emacs|hiro-sun|0.1.1|

---

Steps to Reproduce:

1. 使用拼音输入法，输入"nihaoma"
2.按空格键，屏幕上显示的是"n你好吗"

**Comment by dbaeumer** [comment]
Can anyone help translating this?

**Comment by initialshl** [comment]
Windows 10 built-in Pinyin input method error:
1. Using (Chinese) Pinyin input method, type "nihaoma"
2. Press space bar, the screen shows "n你好吗"
(Expected result: "你好吗")

I can't reproduce it on my Windows 10 using Microsoft Pinyin (Simplified Chinese) though.

**Comment by Jasonlhy** [comment]
I also can't reproduce the issue on my Windows 7 using Microsoft Pinyin (Simplified Chinese).

**Comment by dbaeumer** [comment]
@initialshl @Jasonlhy thanks for the translation and the verification.

@senduo does the problem reproduce for you with vscode-emacs disabled. To disable all extensions use the command F1 > Disable all extensions.

**Comment by dbaeumer** [comment]
Without the requested information we can't work on this issue. We will reopen when the information is available.

**Comment by tcztzy** [comment]
I also met this problem. It seems to be related to the extension [vscode-emacs](https://github.com/hiro-sun/vscode-emacs/).

After I installed and enabled the extension, once I type in Chinese by Microsoft Pinyin, it will delete the former character before cursor if able, and put the first English character in, and then finally works expected.

for example:
if I have some code like `print("")`, and I move the cursor between the double quote, then type in 你好, it will finally get the result `print(n你好")`

**Comment by dbaeumer** [comment]
@tcztzy can you please report this to the vscode-emacs extension then.
