### ISSUE TITLE
Quick open symbols search regression

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#185998]
* open a file
* open an empty group to the side and focus it
* open quick open for files
* type a typescript file name
* add @ to enable symbol search
* :bug: the editor in group 1 changes, not the active group

**Comment by Tyriar** [comment]
Caused by https://github.com/microsoft/vscode/pull/185784, TIL about adding @ after a filename

**Comment by bpasero** [comment]
I had seen your PR and actually thought you would fix an issue associated with that feature 🤔

**Comment by Tyriar** [comment]
I was fixing specifically `@` in a folder/file name before a line/col match

**Comment by bpasero** [comment]
To clarify the feature: typing `@` in a file search allows to ad-hoc flip into a "go to symbol" without having to first open the file.

**Comment by Tyriar** [comment]
@bpasero before it was only checking for the existence of @ and disabling line/col filter extraction if so

**Comment by bpasero** [comment]
I am more arguing that when you search for a file and then type `:` for a line/col pattern, we should automatically open the file in the background and initiate "Go to line", same as we do now for when you type `@` for symbols.

**Comment by Tyriar** [comment]
@bpasero that would be awesome 👍. This was just a drive by fix from me, not sure if @TylerLeonhardt is tracking this
