### ISSUE TITLE
Select next occurrence config popup does not appear in .ipynb files.

### ISSUE THREAD

**Issue by voney** [microsoft/vscode#185932]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version:  1.79.2
- OS Version: Fedora 38

I'm seeing an issue where the little popup that usually appears on the top right side of the editor windows when pressing `CTRL+D` that lets you select whether you want case sensitivity and partial/whole words does not appear in `.ipynb` files.

Steps to Reproduce:

1. Open an `.ipynb` file.
2. Select some text
3. Press `CTRL+D`
4. Notice the popup is missing and there's no way to change how the text is selected.

**Comment by Yoyokrazy** [comment]
/duplicate #233055 + stale functionality. multiselect across cells is now implemented, so this is more useful.
