### ISSUE TITLE
Automatic jump to the cursor

### ISSUE THREAD

**Issue by linedotwww** [Microsoft/vscode#18593]
- VSCode Version: Code 1.8.1 (ee428b0eead68bf0fb99ab5fdc4439be227b6281, 2016-12-19T14:49:23.350Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions:

|Extension|Author|Version|
|---|---|---|
|vscode-caniuse|akamud|0.5.3|
|theme-onedark|azemoh|0.4.3|
|vscode-great-icons|emmanuelbeziat|1.1.38|
|auto-rename-tag|formulahendry|0.0.11|
|easy-less|mrcrowl|1.3.4|
|vscode-less|mrmlnc|0.6.0|

---

Steps to Reproduce:

1.Hello. I have a question. When I enter a snippet or tag then clicking on TAB goes to the cursor, how is it to disable?

![gif](https://cloud.githubusercontent.com/assets/15665678/21975033/68654e6c-dbdb-11e6-8862-7b978e9ab234.gif)

**Comment by linedotwww** [comment]
Вообщем проблема такая, что когда ввожу будь то сниппет, либо элементарно тег картинки, автоматом ставиться конечная позиция курсора. Приходится лишние движения делать, чтоб элементарно добавить новую строку

**Comment by alexandrudima** [comment]
`File` > `Preferences` > `Keyboard Shortcuts` and add this rule:
```
{ "key": "tab", "command": "-editor.emmet.action.expandAbbreviation" }
```

**Comment by linedotwww** [comment]
это не решило проблему

**Comment by alexandrudima** [comment]
I'm sorry I don't understand this language. If you have any problem please open a new issue and use English.
