### ISSUE TITLE
Move `import 'vs/editor/browser/widget/diffEditorWidget2/diffEditorWidget2.contribution';`

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#185944]
I came across this import:

https://github.com/microsoft/vscode/blob/a201c730802a9e27f038b1c95fa70a284d91c93b/src/vs/workbench/browser/parts/editor/editor.contribution.ts#L71

I think it should move to another place that these contributions also work in the standalone case. I would move it somewhere within the `vs/editor` component.

**Comment by hediet** [comment]
Let's clean this up once we remove the old diff editor.

**Comment by bpasero** [comment]
@hediet you just did :D
