### ISSUE TITLE
Less stressful way to navigate Quick Open / Command pallets. 

### ISSUE THREAD

**Issue by jordwalke** [Microsoft/vscode#18596]
Right now, you can easily open the Quick Open / Command Pallets, and you can customize keyboard shortcuts for navigating the contents of these dialogs. However, the keyboard shortcuts have counterintuitive keyboard behavior, or at the very least a more *stressful* interaction model. Currently, when hitting "Command+P" to navigate the entries after the QuickOpen dialog is open, releasing the Command key will open the highlighted entry. This is "stressful" (on the hands) because you cannot relax your hands while navigating the items, or while casually pausing to read the list. This is different than the down/up arrow keys which seem more intuitive, or at the very least less stressful on the hands. Can we have the ability to customize alternative keyboard shortcuts that behave like down/up in this case? I would customize "ctrl-p/ctrl-n" to be up/down respectively (like the Chrome browser autocomplete does, and like the Atom command pallet does).

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/7876
