### ISSUE TITLE
Cannot stage ranges in diff editor v2

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#185977]
When I try to stage ranges via keyboard shortcut, I get this:

![image](https://github.com/microsoft/vscode/assets/900690/01c6a348-5d83-4900-bcff-5c121f57d3cd)

Command is `git.stageSelectedRanges`

**Comment by hediet** [comment]
I think this is fixed by https://github.com/microsoft/vscode/pull/185972

**Comment by hediet** [comment]
Fixed.
