### ISSUE TITLE
link detection do not work in debug console (flutter dart)

### ISSUE THREAD

**Issue by altynbek132** [microsoft/vscode#185911]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.79.2
- OS Version: windows 11 22621.1848

Steps to Reproduce:

1. download https://github.com/altynbek132/link_detect
2. install flutter
3. run flutter test
4. run test in test explorer or debug

https://github.com/microsoft/vscode/assets/48729942/37c59223-3d0a-4334-aea3-8973f2b62e6f

**Comment by roblourens** [comment]
https://github.com/microsoft/vscode/issues/34026
