### ISSUE TITLE
terminal relative path can't recognize line:column

### ISSUE THREAD

**Issue by tjx666** [microsoft/vscode#186096]
https://github.com/microsoft/vscode/assets/41773861/6f08ded7-4a38-447b-8b9c-3be4da72813a

@Tyriar 

```
Version: 1.79.2
Commit: 695af097c7bd098fbf017ce3ac85e09bbc5dda06
Date: 2023-06-14T08:58:33.551Z
Electron: 22.5.7
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Darwin arm64 22.5.0
```

**Comment by Tyriar** [comment]
@tjx666 does this reproduce in insiders? There was a similar issue I looked into recently. To help diagnose, you can set the log level to trace via the command palette, hover the line with the link, then check the "Terminal" channel in the Output panel (this is new to insiders).

**Comment by tjx666** [comment]
@Tyriar Yes, latest insiders version also doesn't work:

```
Version: 1.80.0-insider
Commit: 49b8e2d5410795e5a23a9c6b7f99b97f4afb4b47
Date: 2023-06-23T14:12:20.836Z
Electron: 22.3.13
ElectronBuildId: 21803499
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Darwin arm64 22.5.0
```

**Comment by Tyriar** [comment]
@tjx666 I can't reproduce this so the logging requested above might be able to identify the problem.

**Comment by tjx666** [comment]
I found that is caused because I set:

```json
"terminal.integrated.wordSeparators": " ()[]{}',，\"`─‘’“”<>（）【】{}《》「」:："
```

**Comment by tjx666** [comment]
@Tyriar As the setting description say, `terminal.integrated.wordSeparators` should only affect the word selection, but affect the link detection now.
