### ISSUE TITLE
Test: new setting if files and folders should open in last active or new instance

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#18609]
Refs: #371

- [x] win @dbaeumer 
- [x] mac @egamma 
- [x] linux @roblourens 

New settings `window.openFilesInNewWindow` and `window.openFoldersInNewWindow` are provided to control if files and folders should open in the last active instance or new instance. 
Verify:
* the description of the settings make sense in preferences
* changing the values of either makes it behave as expected when opening files and folders

**Comment by dbaeumer** [comment]
Retested after Ben's clarifications.

**Comment by bpasero** [comment]
@egamma @roblourens note that this setting is ignored if you configure it in workspace. it is user global only.
