### ISSUE TITLE
the vs of cs50 doesn't work with me it is  continuing loading 

### ISSUE THREAD

**Issue by AyA-EhaB** [microsoft/vscode#186082]
ADD ISSUE DESCRIPTION HERE

Version: 1.79.2
Commit: 695af097c7bd098fbf017ce3ac85e09bbc5dda06
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36
Embedder: codespaces

**Comment by aeschli** [comment]
Please contact the cs50 support crew
