### ISSUE TITLE
Lower editor latency over ssh

### ISSUE THREAD

**Issue by jariji** [microsoft/vscode#186056]
Editing over ssh remote has high keystroke latency in the editor which can be disruptive to the editing experience. For example moving the caret around with the arrow keys takes many milliseconds.

One solution would be showing a local transformation of the state immediately before changes are propagated to the remote host. The terminal already has some of this feature but most of my typing is in the editor.

The latency can be especially bad when using complex combination commands, like [Emacs friendly keymap](https://marketplace.visualstudio.com/items?itemName=lfs.vscode-emacs-friendly)'s `kill to line end` which should be instantaneous but can take ~700ms (eyeball estimate) over ssh because it performs a sequence of editing operations (move to next line, move to start of previous line, select to start of line, delete).

Related issue: Zero-latency Typing https://github.com/microsoft/vscode/issues/27378

**Comment by roblourens** [comment]
Typing happens locally, you aren't seeing SSH latency. If you are seeing typing latency there is a different issue, maybe an interaction with the emacs extension. If they are running the extension on the remote extension host, that could explain it, but they should not do that. You might try with all extensions disabled to check if that makes a difference.
