### ISSUE TITLE
ENOPRO: No file system provider found for resource

### ISSUE THREAD

**Issue by calvinchan98133** [microsoft/vscode#186047]
ADD ISSUE DESCRIPTION HERE

Version: 1.79.2
Commit: 695af097c7bd098fbf017ce3ac85e09bbc5dda06
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36
Embedder: codespaces

**Comment by calvinchan98133** [comment]
Unable to open 'file'

**Comment by calvinchan98133** [comment]
An unexpected error occurred that requires a reload of this page.
The workbench failed to connect to the server (Error: )

**Comment by dsetzer** [comment]
Having same issue
![image](https://github.com/microsoft/vscode/assets/18156908/c8f365df-92d4-4298-8362-c2fbcb409ec8)

This has happened to me on two different codespaces so far, one of them I created today, the other was an existing one I created a few days ago and has been working fine, both are repos related to Auto GPT (not sure if that is relevant or just a coincidence yet).

I have tried stopping and restarting the instance, didn't fix it.
I have tried cleariong browser data/cookies and loading it again, didn't fix it.
Finally tried closing my browser (opera) completely and reopening it , this got it to load up without giving the error but it's behaving strangely, seems slow, unresponsive, extensions don't load, the terminal doesn't recognize commands, etc.

**Comment by alexr00** [comment]
@calvinchan98133 this sounds like a Codespaces issue. Can you open an issue over in https://github.com/orgs/community/discussions/categories/codespaces?

**Comment by calvinchan98133** [comment]
Issue resolved with no action from me.

**Comment by alexr00** [comment]
I forwarded this to the Codespaces folks and they resolved the issue.
