### ISSUE TITLE
Autocomplete of HTML/JSX end tags should be more tolerant of accidentally typing the end tag name

### ISSUE THREAD

**Issue by justingrant** [microsoft/vscode#186011]
I like the new autocomplete for HTML/JSX end tags in 1.79 (May 2023). But I frequently find myself typing the name of the end tag anyway, which causes problems because I have to back up and delete the duplicate `foo>` that I just typed. 

Another, less common problem is that sometimes the tag name isn't the end tag that I wanted, for example when typing an end tag before the beginning tag. 

Both of these reminded me of the elegant solution that the HTML/JSX editor does when you type a double quote: the caret is placed between the begin-quote (that I typed) and the end-quote (that the editor added). Could something similar be done with end tag completion?

Specifically, when I type "</", the following should happen:
1. The end tag should be auto-completed like in 1.79.
2. The the tag name should be selected, so if I keep typing then I'll replace the auto-completed tag name.
3. The caret should be at the first character of the tag name.
4. If I press Tab or Enter then the caret should advance to the end of the end tag. In other words, to get the 1.79 behavior, just hit Enter or Tab.
5. For developers who like the 1.79 behavior, there could be a user setting to control whether my suggested behavior or the 1.79 behavior is used.

**Comment by mjbvz** [comment]
Closing since there's been no additional feedback in support of this feature request
