### ISSUE TITLE
variable command is called twice

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#18600]
- VSCode Version: 1.9.0
- OS Version: macOS

Steps to Reproduce:

1. use this launch config:
```json
{
	"type": "node",
	"request": "attach",
	"name": "Attach to Port",
	"port": 5858,
	"processId": "${command.PickProcess}"
}
```
2. run the launch config
3. enter number '123' in the QuickPick and press return

Observe:
Quickpick opens again

**Comment by isidorn** [comment]
Should be fixed via 7376e98
I can not repro it anymore. 
@weinand please reopen if you still see it in tomorrow's insiders
