### ISSUE TITLE
Unable to update Visual Studio Code Insiders

### ISSUE THREAD

**Issue by c0m3tx** [microsoft/vscode#186005]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: Version: 1.80.0-insider
Commit: e8b22318bfab2e52d5dbceee767e8b4bfe9b5300
Date: 2023-06-22T05:34:30.725Z (1 day ago)
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Code-Insiders/1.80.0-insider Chrome/108.0.5359.215 Electron/22.3.13 Safari/537.36
- OS Version: Windows 10 64-bit 21H2 19044.3086

Steps to Reproduce:

1. Start Visual Studio Code Insider
2. Click on the cog and select "Restart to update"
3. The updater appears but does nothing, after a minute or so it fails saying
![immagine](https://github.com/microsoft/vscode/assets/3389462/e4ec7381-74f9-4de5-b16b-47ceef693c0a)
4. Pressing retry does nothing (just waits one more minute and fails again), after pressing cancel this message appears
![immagine](https://github.com/microsoft/vscode/assets/3389462/fa069c10-7450-4c60-8b32-ed0337b86f58)
5. Pressing ok here does restart Visual Studio Code Insiders (which sees an update ready to be installed)

[Related log file](https://github.com/microsoft/vscode/files/11850178/vscode-inno-updater-1687536205.log)

Already tried removing everything and reinstalling from scratch, but did not work.

**Comment by joaomoreno** [comment]
What is inside this folder?

```
C:\\Users\\USERNAME\\AppData\\Local\\Programs\\Microsoft VS Code Insiders\\nul
```

This isn't a folder we ship.

**Comment by c0m3tx** [comment]
It's a file I'm unable to delete from windows, but I'm able to delete from git bash. However, it is created again as soon as the updater starts up.

**Comment by c0m3tx** [comment]
It seem I was able to update it by opening a new empty window by deleting that file first. Normally I use it via SSH, and updating via a SSH-connected code instance, or with that file present, fails every time. I will confirm tomorrow if it's repeatable.

**Comment by joaomoreno** [comment]
Sounds good, let me know.

**Comment by c0m3tx** [comment]
Additional information:
the `nul` file gets created as soon as I connect to my remote linux machine via SSH, but does not get removed afterwards. I also just found out that the same happens on the stable VSCode version, so it's not a matter of just insiders version. Could it be something on my SSH host?

**Comment by joaomoreno** [comment]
> the `nul` file gets created as soon as I connect to my remote linux machine via SSH

Very interesting!

@roblourens Have you seen this before?

**Comment by joaomoreno** [comment]
@c0m3tx Can you try using something like [FileActivityWatch](https://www.nirsoft.net/utils/file_activity_watch.html) to catch which process creates that `nul` file?

**Comment by c0m3tx** [comment]
![immagine](https://github.com/microsoft/vscode/assets/3389462/5afafbc6-6264-4bc0-b145-d4b2475af710)

**Comment by c0m3tx** [comment]
Seem to be related to

```
"remote.SSH.useLocalServer": true,
```

in my configuration. If I disable it, `nul` does not get created!

**Comment by joaomoreno** [comment]
Very cool, thanks for that info!

Sadly, I still can't repro, which points to something in your system.

**Comment by roblourens** [comment]
I've never heard of that before. Thanks for narrowing it down to the `useLocalServer` setting. There is a known issue with that mode, and I suspect that this is related. I'll close it as a dupe unless I can prove otherwise later https://github.com/microsoft/vscode-remote-release/issues/6227
