### ISSUE TITLE
better display decimal number of version in Extensions section

### ISSUE THREAD

**Issue by uxitten** [Microsoft/vscode#18605]
- VSCode Version: 1.8.1
- OS Version: Windows 8

UX Improvement
for example: 1.5M or 1.560M

![capture](https://cloud.githubusercontent.com/assets/1549069/21986272/fb69be86-dc13-11e6-96f5-476804ba44dc.PNG)

**Comment by uxitten** [comment]
if this feature added, developer easy compare between extensions

**Comment by joaomoreno** [comment]
Care to submit a PR? 👍 [hint](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/extensions/browser/extensionsWidgets.ts#L78)

**Comment by uxitten** [comment]
just for UX improvement 
now display 1M for 1.1 and 1.9
