### ISSUE TITLE
Wrong language used to indicate errors

### ISSUE THREAD

**Issue by Liturgist** [microsoft/vscode#186032]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 
```
PS C:\Users\pwatson2> code --version
1.79.2
695af097c7bd098fbf017ce3ac85e09bbc5dda06
x64
```
- OS Version: 
```
Caption             : Microsoft Windows 10 Enterprise
Version             : 10.0.19044
DisplayVersion      : 21H2
BuildType           : Multiprocessor Free
OSArchitecture      : 64-bit
```
Steps to Reproduce:

1. Ctrl-N create a new file
2. Paste in a list of column names
3. Edit into an SQL SELECT statement
4. Ctrl-K, M set language to SQL
5. Keyword 'FROM' is red underlined with message:
"The 'from' keyword is not supported in this version of the language.PowerShell"
6. Also, WHERE' keyword is indicated as an alias of 'Where-Object'

![image](https://github.com/microsoft/vscode/assets/2530958/c3d184a1-c77d-4290-b34b-73897ee074f8)

**Comment by aeschli** [comment]
It looks like this error is created by the Powershell extension. Can you file the issue there?

**Comment by aeschli** [comment]
\extPowershell
