### ISSUE TITLE
Regression: "Debug: Run To Cursor" does not start a debug session

### ISSUE THREAD

**Issue by jceipek** [microsoft/vscode#186080]
Type: <b>Bug</b>

Since https://code.visualstudio.com/updates/v1_76, "Debug: Run To Cursor" should start a debug session if it is not active (https://github.com/microsoft/vscode/pull/169819).
It behaves correctly in https://code.visualstudio.com/updates/v1_78 and stopped working in https://code.visualstudio.com/updates/v1_79.

## Steps to reproduce:

1. Create a workspace with a source file to debug and a `launch.json` file for debugging. For example:
```
// hello.c
#include <stdio.h>

int main(void) {
    printf("Hello world\n");
    return 0;
}
```

```
// .vscode/launch.json
{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "lldb",
            "request": "launch",
            "name": "Launch",
            "program": "${workspaceFolder}/${fileBasenameNoExtension}",
            "args": [],
            "cwd": "${workspaceFolder}",
            "preLaunchTask": "C/C++: clang build active file",
        },
     ]
}
```

3. Click on a line in the source file to debug. For example, `printf("Hello world\n");`
4. Trigger the command "> Debug: Run To Cursor" from the command palette or via keyboard shortcut.

**Expected Behavior**: the debug session starts and the code stops executing on the line with the cursor.
**Actual Behavior**: nothing happens.

VS Code version: Code 1.79.2 (695af097c7bd098fbf017ce3ac85e09bbc5dda06, 2023-06-14T08:58:52.392Z)
OS version: Darwin x64 21.6.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|2, 3, 8|
|Memory (System)|32.00GB (0.31GB free)|
|Process Argv|--crash-reporter-id 7931cb88-468f-4cd8-93d4-26036e2669c7|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
cpptools|ms-|1.16.3
vscode-lldb|vad|1.9.2

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263:30335439
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
py29gd2263:30773603
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
3biah626:30602489
pyind779:30671433
89544117:30613380
vscrpc:30673769
pythonsymbol12:30671437
a9j8j154:30646983
showlangstatbar:30737416
vsctsb:30748421
pythonms35:30701012
03d35959:30757346
pythonfmttext:30731395
pythoncmvfstrcf:30756944
fixshowwlkth:30771522
pythongtdpath:30769146
bgfeh915:30769767
dh2dc718:30770000
pythonidxpt:30772539
pythondjangotscf:30772537
pythonnoceb:30773526

```

</details>

**Comment by roblourens** [comment]
Thanks for the report, will have it fixed for the next stable release
