### ISSUE TITLE
WebView contributed context menus should have element context

### ISSUE THREAD

**Issue by timheuer** [microsoft/vscode#186092]
Following on some conversations that seem unresolved here https://github.com/microsoft/vscode/issues/54285

When using the `webview/context` contributions it's great that it's easy to contribute, but it doesn't provide much context or easy pattern to get at an element that was used (unless I'm missing some documentation).

Basically I want the `HTMLElement` that it was invoked on.

**Comment by mjbvz** [comment]
> Basically I want the HTMLElement that it was invoked on.

That's not possible because the extension host and webview live in different processes. The current api lets you pass JSON serializable data back to your extension code, see: https://code.visualstudio.com/api/extension-guides/webview#context-menus
