### ISSUE TITLE
Reload necessary to adhere to system theme after theme change.

### ISSUE THREAD

**Issue by RokeJulianLockhart** [microsoft/vscode#186002]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version:

	```log
	PS /home/rokejulianlockhart> code-insiders -v   
	1.80.0-insider
	e8b22318bfab2e52d5dbceee767e8b4bfe9b5300
	x64
	```

- OS Version:

	```log
	PS /home/rokejulianlockhart> uname -a
	Linux RQN6C6 6.3.7-1-default #1 SMP PREEMPT_DYNAMIC Mon Jun 12 05:01:32 UTC 2023 (b5f9ff5) x86_64 x86_64 x86_64 GNU/Linux
	```

Steps to Reproduce:

1. `startplasma-wayland`
2. `lookandfeeltool --apply org.kde.breeze.desktop` or `lookandfeeltool --apply org.kde.breezedark.desktop`

The window manager's theme now differs to `code-insiders`'s.

4. `kquitapp5 code-insiders`
5. `code-insiders`

Remediates this.

https://github.com/electron/electron/issues/38684#issue-1747865762:

<blockquote>

When switching themes in a `startplasma-wayland` session (`lookandfeeltool --apply org.kde.breeze.desktop` or `lookandfeeltool --apply org.kde.breezedark.desktop` per https://askubuntu.com/a/1183309/1002900), I must restart https://github.com/microsoft/vscode (`code` and `*insiders`) and https://software.opensuse.org/package/discord for them to adhere to the changed system theme if they were running when the theme was changed.

This isn't the case in a `startx` session.

</blockquote>

Although this affects `discord` too, I've reported downstream due to https://github.com/electron/electron/issues/38684#issuecomment-1588149865:

<blockquote>

Without a test case that reproduces this issue, we cannot resolve the issue. Perhaps someone from one of the projects you mentioned can provide a test case that reproduces the issue.

</blockquote>

because https://canary.discord.com doesn't have a decent issue tracker, whereas https://github.com/microsoft/vscode/ [does](https://github.com/microsoft/vscode/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc).

<details>

0. [ ] https://support.discord.com/hc/en-us/requests/new?ticket_form_id=360006586013

</details>

**Comment by aeschli** [comment]
We rely on the events created by Electron, so this needs to be fixed there. Thanks for filing the issue https://github.com/electron/electron/issues/38684

I wrote a small utility to debug what Electron reports. Maybe you can try that out in your setup and use it for the reproducible steps they request.
See the description on how to use the tool: https://github.com/electron/electron/issues/33635
