### ISSUE TITLE
Codespace in-browser VSCode won't open

### ISSUE THREAD

**Issue by tara-gibbs** [microsoft/vscode#186042]
I was working in my codespace when it suddenly stopped working. The first sign that something was wrong was that the embedded terminal couldn't write the `.git/index.lock` file when I tried to switch to a different branch.

I tried reloading and got this:

<img width="507" alt="image" src="https://github.com/microsoft/vscode/assets/903414/0768e69b-a51f-4c84-a28e-853c4f16d045">

Subsequent reloads result in the same error.

I'm also seeing many connection errors in the javascript console. An example:
`vscs:web-client:4de1:codespaces-component:connection-hub:vscode:connection:E12E79A93C373F62565DF318645D0170C788_2eca8c2e-1722-4191-b715-b508c54c718a_stable_695af097c7bd098fbf017ce3ac85e09bbc5dda06:vscode Failed to complete start-remote-server with Live Share RPC Failed to start VS Code Remote server. code:-32098`

Version: 1.79.2
Commit: 695af097c7bd098fbf017ce3ac85e09bbc5dda06
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:109.0) Gecko/20100101 Firefox/114.0
Embedder: codespaces

**Comment by ulugbekna** [comment]
Could you please have a look at Codespaces troubleshooting [guide](https://docs.github.com/en/codespaces/troubleshooting/troubleshooting-github-codespaces-clients) and report this issue with them?
