### ISSUE TITLE
VSCode default behavior corrupts React-Native apps and my linters

### ISSUE THREAD

**Issue by davidfekke** [Microsoft/vscode#18603]
VSCode default behavior corrupts React-Native apps and my linters. By deleting beginning and trailing whitespace, it is also causing my linter to fail on my CI builds. Adding "editor.trimAutoWhitespace" to false has corrected this, but this requires me going back and changing all of my VSCode repos.

- VSCode Version: 1.8.1
- OS Version: macOS 10.12.2

Steps to Reproduce:

1. Save a file

**Comment by egamma** [comment]
@davidfekke 

In the steps to reproduce can you add a snippet that illustrates the corruption:
- what is the contents of the file before the save
- what is the contents of the file after the save
- how does the 'after save' behaviour break React-Native apps?
- what is the linter rule that breaks in your setup.

>Adding "editor.trimAutoWhitespace" to false has corrected this, but this requires me going back and changing all of my VSCode repos.

If you change this in the user settings 'Preferences>User Settings' then this applies to all your workspaces unless you have set `editor.trimAutoWhitespace` as a workspace setting 'Preferences>Workspace Settings` in all your repositories.

**Comment by davidfekke** [comment]
I should probably separate these into two separate issues. In my React-Native apps when I cut and paste my JSX, VSCode is adding spaces in between the tag and the attribute, which is reeking havoc in one of my apps. The other behavior of deleting beginning and trailing whitespace is causing my linter to fail my builds. I use a Mac at home, and at work. The deleting of the lines is happening on my Mac at home, but not on my Mac at work, which is the machine I am using right now. I will try to duplicate this on my Mac at home tonight. Weird because I am using the same operating system and version of VSCode.

**Comment by davidfekke** [comment]
I changed the settings.json for my workspace to have the following setting;

```
"editor.trimAutoWhitespace": false
```

After I made that change, VSCode stopped removing the beginning and trailing lines.
