### ISSUE TITLE
Diff scrollbar decorations are misaligned when word wrap is on

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#186017]
1. Diff a file with several changes, such as dev_tunnels.rs in https://github.com/microsoft/vscode/pull/186016
2. Notice the decorations in the scrollbar bear little to no relation to editor content

https://github.com/microsoft/vscode/assets/2230985/20309caf-266a-420c-a26b-3b48836b9c93

**Comment by hediet** [comment]
I notice the alignment is off, do you use the latest insiders?

**Comment by connor4312** [comment]
Yes, this is on today's Insiders (49b8e2d5)

**Comment by connor4312** [comment]
Oh, seems like toggling word wrap off fixes it

**Comment by hediet** [comment]
I did some word wrap bugfixes and think this should be covered by them.
