### ISSUE TITLE
Debug errors

### ISSUE THREAD

**Issue by FANXING-0710** [microsoft/vscode#186089]
Does this issue occur when all extensions are disabled?: Yes/No
**Yes**

- VS Code Version: 1.79.2
- OS Version: Windows 10 22H2 19045.2846

Steps to Reproduce:

https://github.com/microsoft/vscode/assets/126996221/4f2f4898-8c58-4825-87f9-fb3eb3eca213

Previously, debugging was not like this.

**Comment by roblourens** [comment]
Please file an issue on the Java debug extension
