### ISSUE TITLE
Cmd+C and Cmd+V do not copy the entire line of code

### ISSUE THREAD

**Issue by anazar2001** [microsoft/vscode#186162]
Type: <b>Bug</b>

Used to work fine if I just want to copy the entire line and paste it below. Now it copies it but with some weird shift, not straight one below another. I think the position of cursor on the original line matters when you try to copy.

VS Code version: Code 1.79.1 (4cb974a7aed77a74c7813bdccd99ee0d04901215, 2023-06-12T16:17:16.971Z)
OS version: Darwin arm64 22.2.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|7, 7, 6|
|Memory (System)|32.00GB (0.06GB free)|
|Process Argv|--crash-reporter-id ca77d4d7-a862-4b3b-a666-ca0626efb457|
|Screen Reader|yes|
|VM|0%|
</details><details><summary>Extensions (43)</summary>

Extension|Author (truncated)|Version
---|---|---
cucumberautocomplete|ale|2.15.2
vscode-eclipse-keybindings|alp|0.16.1
format-json|Cle|1.0.3
generator-java-unit-test-file|den|0.0.12
java-decompiler|dgi|0.0.3
javadebugger|don|0.1.5
gitlens|eam|14.0.1
copilot|Git|1.92.177
compareit|in4|0.0.2
vscode-edit-csv|jan|0.7.6
java-test|jav|0.0.2
auto-comment-blocks|kev|1.0.1
vscode-docker|ms-|1.25.1
vscode-dotnet-runtime|ms-|1.6.0
remote-containers|ms-|0.295.0
remote-ssh|ms-|0.102.0
remote-ssh-edit|ms-|0.86.0
live-server|ms-|0.4.8
remote-explorer|ms-|0.4.0
vscode-thunder-client|ran|2.7.7
fabric8-analytics|red|0.3.10
java|red|1.19.0
vscode-community-server-connector|red|0.26.13
vscode-rsp-ui|red|0.24.8
vscode-xml|red|0.25.0
vscode-coverage-gutters|rya|2.11.0
multi-command|ryu|1.6.0
sonarlint-vscode|Son|3.19.0
tabnine-vscode|Tab|3.6.60
vscode-boot-dev-pack|vmw|0.2.1
vscode-spring-boot|vmw|1.47.0
vscode-java-debug|vsc|0.51.0
vscode-java-dependency|vsc|0.23.0
vscode-java-pack|vsc|0.25.11
vscode-java-test|vsc|0.39.0
vscode-lombok|vsc|1.1.0
vscode-maven|vsc|0.41.0
vscode-spring-boot-dashboard|vsc|0.13.1
vscode-spring-initializr|vsc|0.11.2
vscode-icons|vsc|12.4.0
vscode-icons-mac|way|7.25.3
fig|wit|0.0.7
familiar-java-themes|zer|0.1.7

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
py29gd2263:30773603
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
vscccc:30610679
3biah626:30602489
pyind779:30671433
f6dab269:30613381
pythonsymbol12:30671437
showlangstatbar:30737416
vsctsb:30748421
pythonms35:30701012
03d35959:30757346
pythonfmttext:30731395
pythoncmvfstrcf:30756944
fixshowwlkth:30771522
pythongtdpath:30769146
bgfeh915:30769767
gsof2:30774497
e440d664:30770001
pythonidxptcf:30772540
pythondjangotscf:30772537
pythonnoceb:30773526

```

</details>

**Comment by gjsjohnmurray** [comment]
Does it also happen with all extensions disabled? The `Start Extension Bisect` command can help you check this.

**Comment by anazar2001** [comment]
wow it is a useful thing!!! Though it said in the end that no extension identified so might be VSCode

**Comment by anazar2001** [comment]
The issue remains in the latest VSCode version

**Comment by gjsjohnmurray** [comment]
Please provide details of a simple repro. Paste a screenshot if you think that will help explain.

**Comment by anazar2001** [comment]
<img width="1728" alt="BeforeCopyPaste" src="https://github.com/microsoft/vscode/assets/13858727/224308d7-4469-4aba-b18d-43a7018f7ef5">
<img width="1728" alt="AfterCopyPaste" src="https://github.com/microsoft/vscode/assets/13858727/21cdc28e-7e29-4486-8faa-53dd8152360c">
You can see before and after Copy/Paste

**Comment by anazar2001** [comment]
It looks like it only copies a string starting from the cursor to the end of the line not the entire line as it was before

**Comment by gjsjohnmurray** [comment]
Please show this happening in a plaintext file with all extension disabled.

Please also check your `editor.emptySelectionClipboard` setting, and use the Keyboard Shortcuts editor to verify that Cmd+C hasn't been bound to anything non-standard.

**Comment by anazar2001** [comment]
Have the same issue even with all extensions disabled. Not using the editor.emptySelectionClipboard in my settings

**Comment by mstgms** [comment]
Hi, i have the same issue, it is only seems when copying from compare's source tab. The others copy sources are proper.
I tried this when all extensions disabled. 

It seems to copy the "newline" characters after the line content when copying from the compare source tab, normally in other places it copies the "newline" characters before the line content.

<img width="764" alt="image" src="https://github.com/microsoft/vscode/assets/20553549/2b246383-abc1-4580-9a6a-4bd2323bd197">

**Comment by musashi-miyamoto** [comment]
I think it's new "Paste As" option behavior [from vscode 1.79](https://code.visualstudio.com/updates/v1_79#_paste-as).
You can disable it by "Editor > Paste As: Enabled".

<img width="303" alt="image" src="https://github.com/microsoft/vscode/assets/44890163/067a27e6-510c-4a32-a40e-26fa414a7ef7">

**Comment by mstgms** [comment]
Yes @musashi-miyamoto it was fixed when i disabled this setting. Thank you.
