### ISSUE TITLE
Walkthroughs are not always registered when the editor loads

### ISSUE THREAD

**Issue by umpox** [microsoft/vscode#186165]
Type: <b>Bug</b>

<img width="544" alt="image" src="https://github.com/microsoft/vscode/assets/9516420/c3031a29-c12b-4aa2-a22f-6dda74f1e368">

1. Install [GitLens](https://marketplace.visualstudio.com/items?itemName=eamodio.gitlens)
2. Close VS Code or run the "Reload window" command.
3. Open VS Code and navigate to the GitLens extension in the sidebar
<img width="168" alt="image" src="https://github.com/microsoft/vscode/assets/9516420/d9b3115a-afc2-425e-a93f-d34bde53582e">

4. Click "Feature Walkthrough" under Getting Started.
<img width="484" alt="image" src="https://github.com/microsoft/vscode/assets/9516420/1240487d-ddf5-4161-8595-502f04df0f18">

**Expected**: The walkthrough opens

**Actual**: The "new file" placeholder page opens. Clicking the "Feature Walkthrough" link again will load the walkthrough correctly.

------------------------------------------------------------------ 

VS Code version: Code - Insiders 1.80.0-insider (Universal) (e8b22318bfab2e52d5dbceee767e8b4bfe9b5300, 2023-06-22T05:38:43.259Z)
OS version: Darwin arm64 22.4.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Max (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|3, 3, 4|
|Memory (System)|64.00GB (38.70GB free)|
|Process Argv|--crash-reporter-id 41155d03-e126-48b7-b999-4c4fdc98b918|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
gitlens|eam|2023.6.2005

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256198
vslsvsres303:30308271
pythontb:30258533
vsc_aa:30263845
pythonptprofiler:30281269
vshan820:30294714
vscod805:30301674
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30404738
py29gd2263:30773603
vsclangdf:30492506
c4g48928:30535728
dsvsc012:30540252
pynewext54:30618038
pylantcb52:30590116
pyind779:30611226
pythonsymbol12:30651887
a9j8j154:30646983
showlangstatbar:30737417
pythonms35:30671666
03d35959:30757351
24365598:30687740
pythonfmttext:30716741
pythoncmvfstr:30726892
fixshowwlkth:30771523
hideindicator:30766887
pythongtdpath:30726887
bgfeh915:30769767
gsof1:30771514
dh2dc718:30770000
pythonnosmt12:30773574
pythonidxpt:30768918
pythondjangots:30768917
pythonnocebcf:30766856
copilotsettingt:30767686
e537b577:30772214

```

</details>

**Comment by bhavyaus** [comment]
Closed with https://github.com/microsoft/vscode/pull/186263
