### ISSUE TITLE
Javascript syntax highlighting broken with RequireJS style files

### ISSUE THREAD

**Issue by Weetbix** [Microsoft/vscode#18612]
- VSCode Version: Insiders `217f96222ed0c8fc8693d85c6a2ed8e0c9ca35a1`
- OS Version: Mac OSX 10.11

Steps to Reproduce:

1. Paste the following code in a .js file: 
```
define( function()
{
    function bar()
    {

    };

    _.extend( Blah.prototype, 
    {
        foo : function(){
            var foobar = 'foobar';
            return foobar;
        }
    } );
} );
```
2. Notice how the syntax highlighting is broken.
3. The highlighting seems to work correctly if the brace on line 2 is moved up to the end of line 1.

### Screenshots
![screen shot 2017-01-16 at 16 41 09](https://cloud.githubusercontent.com/assets/492636/21989457/3eedb6ca-dc0b-11e6-94ec-27b7c1881da9.png)

![screen shot 2017-01-16 at 16 41 20](https://cloud.githubusercontent.com/assets/492636/21989456/3eeb00f6-dc0b-11e6-9440-a1b9aa0138a2.png)

**Comment by mjbvz** [comment]
This looks fixed in the latest TS grammar. 

@aeschli Do you want me to try picking up the new grammar or will you be taking care of it?
