### ISSUE TITLE
Can't connect to my code space

### ISSUE THREAD

**Issue by joakimaz** [microsoft/vscode#186152]
ADD ISSUE DESCRIPTION HERE

Version: 1.79.2
Commit: 695af097c7bd098fbf017ce3ac85e09bbc5dda06
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36
Embedder: codespaces

Hello, I'm trying to connect to my codespace but it is not working. It worked this morning but was complaning that it could not save a file (don't know why, it was a simple file without any code besides css and html). Can you help? I will send some printscreens.

Best regards.
![Codespace_1](https://github.com/microsoft/vscode/assets/36771490/b5d16a21-6739-44cb-8294-6edc3ad83b81)

**Comment by alexr00** [comment]
This sounds like a Codespaces issue. Can you open an issue over in https://github.com/orgs/community/discussions/categories/codespaces?
