### ISSUE TITLE
Polish git as an SCM extension

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#18615]
**Git extension**

- [x] Model
- [x] Output channel
- [x] Decorations
- [x] Menus
- [x] Status bar
- [x] Commit box as text editor?
- [x] Merge decorator
- [x] Auto fetch
- [x] Configurations
- [x] Progress
- [x] Localization
- [x] Status bar
- [x] `View > Git` menu
- [x] Make sure it runs under `en` locale
- [x] Commands
- [x] Editor menu actions
- [x] Empty slate (git init)
- [x] Scoped git workspaces
- [x] Range staging
- [x] Range reverting
- [x] Commit template
- [x] Git 2.0 recommender
- [x] Askpass
- [x] Clone command
- [x] Telemetry

**Misc**

- [x] Shrinkwrap git extension dependencies

**Comment by chrmarti** [comment]
I miss the action to switch an editor back and forth between current content and diff view. Is that tracked here, should I open an issue?

**Comment by joaomoreno** [comment]
It's tracked as _Editor menu actions_.

**Comment by johncrim** [comment]
Are issues for the git SCM Extension moving to another GitHub repo? Or will they stay within vscode?

The reason I ask: If issues are moving, I want to make sure #5770 doesn't get lost.

**Comment by joaomoreno** [comment]
Not moving 👍

**Comment by Mellbourn** [comment]
I can't see "Quick copy lines in diff view #22003". Shouldn't it be out?

**Comment by joaomoreno** [comment]
@Mellbourn 

![image](https://cloud.githubusercontent.com/assets/22350/25430059/80d20aaa-2a7b-11e7-8bc7-6724f66547c4.png)

**Comment by Mellbourn** [comment]
@joaomoreno ah. ok. I was hoping for the GUI "arrows" mentioned in the original issue.
