### ISSUE TITLE
Test extension provided read-only message

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#186170]
Refs: https://github.com/microsoft/vscode/issues/166971

- [x] anyOS @daviddossett
- [x] anyOS @hediet

Complexity: 2

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23186170%0A%0A&assignees=alexr00)

---

We have a new API proposal for extension that have a read-only file system provider to provide markdown for the message that is shown when the user ties to edit a read-only file:

https://github.com/microsoft/vscode/blob/2e9aae6c26904fe91bd2149d446db40d27734889/src/vscode-dts/vscode.proposed.readonlyMessage.d.ts#L12-L13

The GitHub Pull Requests and Issues extension uses the this proposal to show a useful message if you try to edit a file in a PR that isn't currently checked out.

To verify:
1. Install the pre-release version of GitHub Pull Requests and issues
2. Open a folder that contains a clone of a GitHub repo.
3. From the "Pull Requests" view, expand a PR and open a file diff
4. Try to edit the diff
5. Verify that you see a message that instructs you to check out the PR to edit.
6. Verify that you can click on the "Check out" in the message to check out the PR.

**Comment by daviddossett** [comment]
Works great! Just a few nits.
