### ISSUE TITLE
An unexpected error occurred that requires a reload of this page.

### ISSUE THREAD

**Issue by katarzynastec** [microsoft/vscode#186169]
ISSUE DESCRIPTION HERE
![error](https://github.com/microsoft/vscode/assets/137056944/c7f89eec-0a5e-4f67-addb-094d5a5ef6ae)

Reloading does not help

Version: 1.79.2
Commit: 695af097c7bd098fbf017ce3ac85e09bbc5dda06
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36
Embedder: codespaces

**Comment by meganrogge** [comment]
this is a codespaces issue, pls file as such on their repo
