### ISSUE TITLE
Test: dirty files are preserved when renaming or moving around

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#18610]
Refs: #11997

- [x] @mousetraps 
- [x] @kieferrm 

You can now move or rename dirty files without having to save them first. Verify for all of the following actions that the dirty contents and dirty state are preserved and restored:
* rename file
* rename parent of file
* move file
* move parent of file

**Comment by kieferrm** [comment]
Tested on macOS.

**Comment by mousetraps** [comment]
tested on windows
