### ISSUE TITLE
Requests for donations from within the vi editor (accessed through codespaces)

### ISSUE THREAD

**Issue by Werner0** [microsoft/vscode#186108]
The "Become a registered Vim user!" line on the intro screen when using vi from the codespaces terminal (launching the editor by just typing `vi`) displayed a non-specific request for donations for the "poor children in Uganda" when I launched the editor earlier today.

Version: 1.79.2
Commit: 695af097c7bd098fbf017ce3ac85e09bbc5dda06
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.4.1 Safari/605.1.15
Embedder: codespaces

**Comment by gjsjohnmurray** [comment]
Please use the Start Extension Bisect command to investigate whether the problem is being caused by one of your extensions.

**Comment by Werner0** [comment]
Here's a screenshot of the line on a fresh codespaces instantiation using the codespaces-jupyter template on github.com:

![Screenshot 2023-06-25 at 8 37 05 PM](https://github.com/microsoft/vscode/assets/11156694/99c72ded-b372-4368-b8c1-2d5dd52b5727)

**Comment by bpasero** [comment]
@Werner0 did you consider to report this to the VIM project? I think what you see there is not associated to VS Code or Codespaces.

**Comment by Werner0** [comment]
@bpasero I have not considered reporting the issue to the VIM project yet. However, I have so far only seen the edited VIM screen on the Jupyter Notebook (codespaces-jupyter) template, not the blank codespaces template. These templates are provided by Github.
![Capture](https://github.com/microsoft/vscode/assets/11156694/d7332fc7-fac8-40b2-a1d6-92344fcb2f3e)
