### ISSUE TITLE
Test: improvements to sharing links

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode#186199]
Refs: https://github.com/microsoft/vscode/issues/176316, https://github.com/microsoft/vscode/issues/183810, https://github.com/microsoft/vscode/pull/185908

- [x] anyOS @lszomoru
- [ ] anyOS @Yoyokrazy

Complexity: 5

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23186199%0A%0A&assignees=joyceerhl)

---

We've made further improvements to copying and sharing links from inside VS Code.

Test:
1. Open an Azure Repos repository in insiders.vscode.dev. Right click in the editor gutter and Copy vscode.dev Link for a line. Paste the link into your browser tab and verify that it takes you back to that specific line for Azure Repos
2. Open a GitHub repository that has been cloned with git to your local machine. Be on an unpublished branch. Right click in the editor gutter and Copy vscode.dev Link for a line. Verify that you are informed the branch is not yet published to the remote, and that the followup actions work and make sense.
3. Repeat step 2 for the following scenarios:
    - Have some local uncommitted changes (either staged or in working tree)
    - Be a couple of commits behind the remote
4. Enable `window.commandCenter` and `workbench.experimental.share.enabled`, reload window, and install GitHub Pull Requests and Issues pre-release
    - Ensure a Copy Markdown Link option is available from the share button next to the command center and that it works as expected
    - If you have an active editor selection, ensure that all the options from the share button include a deeplink to the editor selection

**Comment by lszomoru** [comment]
> Ensure a Copy Markdown Link option is available from the share button next to the command center and that it works as expected

Do you mean "Copy GitHub Permalink as Markdown"?

![Image](https://github.com/microsoft/vscode/assets/3372902/f6eb2536-8944-486f-b6df-1ca165fae3c4)

**Comment by Yoyokrazy** [comment]
Also running into #186298, and same expectation for uncommitted changes, expected a dialog.
