### ISSUE TITLE
[BUG] 'Stage Selected Range' button disappered in diff editor commond list.

### ISSUE THREAD

**Issue by shenmishajing** [microsoft/vscode#186106]
Does this issue occur when all extensions are disabled?: Yes

- Version: 1.80.0-insider
- Commit: 49b8e2d5410795e5a23a9c6b7f99b97f4afb4b47
- Date: 2023-06-23T13:51:01.857Z
- Electron: 22.3.13
- ElectronBuildId: 21803499
- Chromium: 108.0.5359.215
- Node.js: 16.17.1
- V8: 10.8.168.25-electron.0
- OS: Darwin x64 22.5.0
- OS Version: Macos 13.4

<img width="216" alt="Screenshot 2023-06-25 at 15 40 05" src="https://github.com/microsoft/vscode/assets/32559715/57a87abb-b192-45a5-a933-2bf279f62bcf">

Steps to Reproduce:

1.  Open diff editor
2. Click the 'More Actions' button to show the commond list
3. No 'Stage Selected Range' and 'Unstage Selected Range' in here

**Comment by mvasilkov** [comment]
Yup, it also disappeared from the context menu! Please revert, it's a very useful feature to have on the right click menu.

**Comment by lszomoru** [comment]
@hediet, could this be related to the diff editor rewrite?

**Comment by hediet** [comment]
This should be fixed now.
