### ISSUE TITLE
Test new `files.dialog.defaultPath` setting (local & remote)

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#186172]
Refs: https://github.com/microsoft/vscode/issues/115730

- [x] anyOS @DonJayamanne
- [x] anyOS @jrieken

Complexity: 3

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23186172%0A%0A&assignees=bpasero)

---

A new setting `files.dialog.defaultPath` allows to set the path that file dialogs should present in case we do not have any other default (i.e. when no folder is opened or no active file). We use this in file dialogs when opening or picking a file to save.

**Note:** the path is not validated to exist on disk currently

**Test: Local**
* configure `files.dialog.defaultPath` to some path on your local disk
* open an empty window and have no file opened or only an untitled file
* verify your configured folder is picked when you select commands from the "File" menu to open or save
* verify the same works when you have configured `files.simpleDialog.enable` for the simple dialog

**Test: Remote**
* configure `files.dialog.defaultPath` to some path on the remote as a remote machine setting (see [1])
* verify the steps from "Test: Local" works with the remote machine configured path when the dialog is about remote paths and your local configured path when the dialog is about local paths (you should be able to switch to a local picker from the simple file dialog)

[1] Settings editor in remote have a tab for remote machine settings:

![image](https://github.com/microsoft/vscode/assets/900690/2e7863cf-22ec-438f-bcdb-980626867a6c)

**Comment by DonJayamanne** [comment]
Unfortunately I couldn't get this to work in local nor remote https://github.com/microsoft/vscode/issues/186249

**Comment by bpasero** [comment]
Yup, needs an insiders from today. Reassigning.

**Comment by DonJayamanne** [comment]
Works well in local setup, but not in remote
