### ISSUE TITLE
feature request: multiple named keybinding contributions to work with global keymap

### ISSUE THREAD

**Issue by siegebell** [Microsoft/vscode#18617]
Allow an extension to supply multiple, *named*, keybinding contributions to correspond with the active keymap. E.g. if an extension contributes keybindings for "vim" (or "emacs"), then they should be enabled when the user selects a vim (resp. emacs) keymap. And also allow the user to manually specify the name of a keybinding contribution to activate, or `none`, per extension in settings.json. Keymap name `"vscode"` should be reserved for vscode's default keybindings, and an extension may optionally provide a default keybinding contribution to activate for all other keymaps.

This feature request is a finer-grained extension of #18441. 

Concrete example: my vscoq extension provides language support for Coq, and incoming users are used to very different keybindings depending on whether they're coming from CoqIDE, vim, or emacs. Ideally, I would be able to provide the default keybindings for all of them (in addition to the default bindings that I have chosen to work well with vscode's defaults) -- and the right one would automatically be selected when the user changes their keymap.

At the moment, I can provide additional keymap extensions that a user can manually select from. But it's not nice that a user has to first choose to use an emacs keymap extension, and then manually configure all of their extensions to also provide emacs-like keybindings (by downloading additional keymap extensions or tediously creating their own keybindings).

**Comment by dbaeumer** [comment]
Not sure if this is @alexandrudima  or @chrmarti
