### ISSUE TITLE
Intellisense doesn't work sometimes. 

### ISSUE THREAD

**Issue by sfshameem5** [Microsoft/vscode#18619]
- VSCode Version: Code 1.8.1 (ee428b0eead68bf0fb99ab5fdc4439be227b6281, 2016-12-19T14:49:23.350Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

|Extension|Author|Version|
|---|---|---|
|code-gnu-global|austin|0.2.1|
|python|donjayamanne|0.5.5|
|Theme-Acai|gerane|0.0.2|
|Theme-Kimbiedark|gerane|0.0.2|
|beautify|HookyQR|0.7.3|
|theme-material-theme|jprestidge|1.0.1|
|MagicPython|magicstack|1.0.3|
|cpptools|ms-vscode|0.9.3|
|Theme-3024Kit|ms-vscode|0.1.1|
|vscode-icons|robertohuertasm|4.3.0|

---

Steps to Reproduce:

1.
2.

**Comment by dbaeumer** [comment]
@sfshameem5 can you please provide steps on how to reproduce this. Which programming language are you using. If it is about Python, please file the issue against the corresponding Python extension.

**Comment by sfshameem5** [comment]
I'm using C. All of a sudden intellisense stops working for some variables.

**Comment by dbaeumer** [comment]
This issue was moved to Microsoft/vscode-cpptools#454
