### ISSUE TITLE
ugly working files section

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#1861]
I guess this is due to the size changes. The unsaved-banner looks bad in many ways

![screen shot 2016-01-08 at 09 10 50](https://cloud.githubusercontent.com/assets/1794099/12193359/cc57e8be-b5e7-11e5-8178-aba9f71e6609.png)

**Comment by jrieken** [comment]
@bpasero fyi in case it's you

**Comment by bpasero** [comment]
Yeah a regression from the font change, @isidorn please apply magic

**Comment by isidorn** [comment]
Fixed with 42c3b94
