### ISSUE TITLE
Replace Command doesn't replece " " -> ""

### ISSUE THREAD

**Issue by viniciusjarina** [Microsoft/vscode#18614]
Using the replace to get rid of the whitespace seems not to work.

The replaces only replaces when is different from 
- VSCode Version: Code - Insiders 1.9.0-insider (217f96222ed0c8fc8693d85c6a2ed8e0c9ca35a1, 2017-01-16T07:41:07.221Z)
- OS Version: Darwin x64 16.3.0
- Extensions:

|Extension|Author|Version|
|---|---|---|
|code-gnu-global|austin|0.2.1|
|python|donjayamanne|0.5.5|
|cpptools|ms-vscode|0.9.3|
|csharp|ms-vscode|1.6.2|
|cmake|twxs|0.0.15|

---

Steps to Reproduce:

1.
2.

**Comment by alexandrudima** [comment]
Fixed via 8289f6fa059d580ec063386ccebb4bde2354bb89
