### ISSUE TITLE
A solution to bash not recognizing Windows-style file system path separators

### ISSUE THREAD

**Issue by listenerri** [microsoft/vscode#186119]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.79.2
- OS Version: Windows11

The issues related to this issue are closed and locked, so I have to create a new issue to discuss it.

Related issues are: #35593 #48149 #40954

My solution is:

```
"terminal.integrated.profiles.windows": {
    "bash (MINGW64-MSYS2)": {
        "path": "C:\\msys64\\usr\\bin\\bash.exe",
        "args": [
            "--login",
            "-i",
            "-c",
            "if [ -z \"$@\" ]; then bash; else eval \"$(cygpath \"$@\")\"; fi"
        ],
        "env": {
            "CHERE_INVOKING": "1",
            "MSYSTEM": "MINGW64",
            "MSYS2_PATH_TYPE": "inherit"
        }
    },
    // other terminal profiles
    // ....
},
"terminal.integrated.defaultProfile.windows": "bash (MINGW64-MSYS2)",
```

The main part is using the `cygpath` command.

Inspired by this answer: https://stackoverflow.com/a/49779607/7059407

WSL also has `wslpath` cmd, just like `cygpath`.

**Comment by listenerri** [comment]
> Those issues are all about tasks but I think you're asking about the terminal? Can you clarify what the problem is exactly?

On windows, assuming the default terminal is set to use bash (from msys2, git for windows, cygwin or wsl), when a task is to be executed, and the task specifies a command with a path, and/or a file parameter with a path. The task provider typically uses Windows-style paths (delimited by backslashes), and bash will report an error that the specified command or file cannot be found because bash uses backslashes as escape characters by default.

For specific errors, please refer to the following information extracted from the above issues.

**from #48149 :**
```
Executing task: tsc --watch -p c:\Users\rnaddy\Documents\vscode\projects\red5\tsconfig.json <

error TS5058: The specified path does not exist: 'c:UsersrnaddyDocumentsvscodeprojectsred5tsconfig.json'.
The terminal process terminated with exit code: 1
```

**from #40954 :**
```
    "terminal.integrated.shell.windows": "C:\\devel\\msys64\\usr\\bin\\bash.exe",
    "terminal.integrated.shellArgs.windows": ["--login", "-i"],
```
```
> Executing task: node_modules\.bin\gulp.cmd serve <

bash: node_modules.bingulp.cmd: command not found
The terminal process terminated with exit code: 127

Terminal will be reused by tasks, press any key to close it.
```

**from #35593 :**
```
// launch.json
{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "typescript",
            "tsconfig": "tsconfig.json",
            "group": {
                "kind": "build",
                "isDefault": true
            }
        }
    ]
}
```
```
/usr/bin/bash: c:UsersrobertCodeNodegraphicsnode_modules.bintsc.cmd: command not found
```

**Comment by jcrben** [comment]
Here's a solution which worked for me:

```
"terminal.integrated.automationProfile.windows": {
        "path": "Powershell"
    },
```

This way I can keep my default as `git-bash` for when I open the terminal, but when I run a Python launch.json it will use Powershell which seems to be working.
