### ISSUE TITLE
HTML Collapse issue!

### ISSUE THREAD

**Issue by khaledmndev** [microsoft/vscode#186122]
Type: <b>Bug</b>

Greetings Devs,
I have an issue when i want to collapse a specific code in HTML something the collapse is on the comment instead of the the starting code under it!

VS Code version: Code 1.79.2 (695af097c7bd098fbf017ce3ac85e09bbc5dda06, 2023-06-14T08:57:04.379Z)
OS version: Windows_NT x64 10.0.22621
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8300H CPU @ 2.30GHz (8 x 2304)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.85GB (8.14GB free)|
|Process Argv|--crash-reporter-id a1f8fb56-96aa-4e2e-aaed-8cbe20b7df88|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (17)</summary>

Extension|Author (truncated)|Version
---|---|---
css-compressor|bes|0.0.2
vscode-tailwindcss|bra|0.9.11
vscode-eslint|dba|2.4.2
javascript-ejs-support|Dig|1.3.3
es7-react-js-snippets|dsz|4.4.3
gitlens|eam|14.0.1
vsc-material-theme|Equ|33.8.0
vsc-material-theme-icons|equ|2.8.0
prettier-vscode|esb|9.16.0
auto-close-tag|for|0.5.14
auto-rename-tag|for|0.1.10
vsliveshare|ms-|1.0.5873
iconfont-preview|stx|0.0.5
lorem-ipsum|Tyr|1.3.1
windows-terminal|Tyr|0.7.0
vscode-wakatime|Wak|24.0.14
vscode-import-cost|wix|3.3.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscorecescf:30445987
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
py29gd2263:30773603
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
vscccc:30610679
2e4cg342:30602488
pyind779:30671433
89544117:30613380
pythonsymbol12:30671437
showlangstatbar:30737416
vsctsb:30748421
pythonms35:30701012
03d35959:30757346
7ij38806:30736111
pythonfmttext:30731395
pythoncmvfstrcf:30756944
fixshowwlkth:30771522
pythongtdpath:30769146
bgfeh915:30769767
dh2dc718:30770000
pythonidxpt:30772539
pythondjangots:30772535
pythonnoceb:30773526

```

</details>

**Comment by aeschli** [comment]
Can you add a code sample that demonstrates the problem?

**Comment by khaledmndev** [comment]
> Can you add a code sample that demonstrates the problem?

I think it worked after i changed my Computer 😅 "False Alarm".

Thanks Anyways
