### ISSUE TITLE
Test Troubleshoot Issue feature

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#186171]
- [x] mac @kieferrm
- [ ] linux @jrieken
- [x] win @dbaeumer 

Complexity: 3

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23186171%0A%0A&assignees=sandy081)

---

You can now troubleshoot an issue in VS Code and find out what is causing this. A new command `>Help: Troubleshoot Issue` is introduced to determine if an issue is with

- VS Code
- VS Code Settings
- an Extension

Test this feature in insiders and stable. Please download the latest unreleased stable build to test stable version

Test running above command and check if the troubleshooting flow will help you in determining where the issue is. It uses vscode profiles feature to check if the issue is with VS Code or VS Code settings. This will help to un-touch your current setup. To find the problematic extension, this flow uses extension bisect. At the end, you would be asked to report an issue by adding necessary troubleshooting context in the description. 

If you are in stable release, the flow will also ask if the issue exists in insiders or not. Please test this flow too. 

Once troubleshooting is done, you will be back to your original setup/profile.

Explore the feature and test any other scenarios you can think of.

**Comment by sandy081** [comment]
Stable build is not available yet. I am building it. I will announce here once it is available.

**Comment by sandy081** [comment]
Stable build is available

**Comment by jahuarcristian** [comment]
Realizar trasferencia paypal $ 5,79993

**Comment by sandy081** [comment]
@jrieken Extensions are indeed getting disabled. Please check the extensions view / running extensions editor. What you are seeing is a bug in status bar.

**Comment by sandy081** [comment]
@kieferrm I assume you are done with testing here because you unassigned yourself. @jrieken might have assigned you back  by mistake. Hence unassigning you and closing this.

If I am wrong, please reopen and continue testing.
