### ISSUE TITLE
Overwriting / munging/ corrupting files

### ISSUE THREAD

**Issue by rr326** [Microsoft/vscode#18611]
- VSCode Version: 1.8.1
- OS Version: OSX 10.2.2

Steps to Reproduce:
Sorry I don't really know how to reproduce it - it happens randomly.  But here is what happens:

I'm working on a.js and b.js.  I'll go to debug  (an electron app) and it will fail. Then I'll check out the failure place and somehow a whole chunk of a.js will have inserted into b.js.  I wind up either having to find the chunk and remove it or revert to my last saved state.

It's basically unworkable and I've had to switch back to Sublime. But clearly VSCode is used by tons of people, so this can't be a common occurrence.  

Any ideas of how to even debug what's going on or reproduce it?

**Comment by bpasero** [comment]
@rr326 does `"workbench.editor.enablePreview": false` in settings help?

**Comment by rr326** [comment]
I'll try it for a while and see if any errors arise.  Could be a couple days to be sure if its working. 

Thanks.

**Comment by bpasero** [comment]
Ok, closing until we hear back.

**Comment by rr326** [comment]
Happened right away (even with enablePreview: false)

**Comment by bpasero** [comment]
@rr326 can you maybe show this with a video?

**Comment by rr326** [comment]
I could show you a screen capture, but it won't show more than this:

- I'm working on a few files
- I push "debug main process" (which I've set up in my launch.json)
- It fails. I go to the offending line in the code and a whole section of one file has been inserted into the other file. 

I don't see it happen and I haven't figured out any logic to it.  Also, it doesn't happen every time, but it happens often. 

Happy to do more debugging. If you still want a video or screen capture, let me know.  

Could it be some sort of extension automatically trying to beautify of lint or something? In fact, maybe I should disable all extensions. I'll try that.

**Comment by bpasero** [comment]
Yes, a video is helpful here, I have no idea what is going on...

**Comment by rr326** [comment]
Ok - working on it.  (Also disabled all my extensions. Just in case.)

**Comment by rr326** [comment]
My bad - you can close this.

This was user error. I disabled all my extensions. It then worked perfectly. Then I looked at my extensions - I had two extensions that were probably clobbering each other - beautify & js-css-html formatter. I must have been over-eager when installing VScode. 

Thanks for the help and sorry for wasting your time.
