### ISSUE TITLE
Test: saving an Interactive Window

### ISSUE THREAD

**Issue by amunger** [microsoft/vscode#186196]
Refs: https://github.com/microsoft/vscode/issues/172974

- [x] macOS @ulugbekna
- [x] linux @connor4312
- [x] windows @minsa110

Complexity: 3

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23186196%0A%0A&assignees=amunger)

---

## Explanation

This focuses on the behavior for saving an Interactive Window. Current behavior testing should be covered by https://github.com/microsoft/vscode/issues/186191.

## Prerequisites

- install the pre-release versions of jupyter and python extensions
- ensure you have a python interpreter installed
- use `Python: create environment` to create a local virtual environment in the workspace to keep any changes out of your global python environment
- You'll need the python kernel packages to run the interpreter as a kernel, but vscode should guide you in installing these when attempting to run anything.

## Test steps

1. Create a python file and add a few code cells (`# %%` marks a cell), e.g.

```
# %%
# this will likely show a syntax error in the python file
%pip install matplotlib

# %%
import matplotlib.pyplot as plt
x = [1, 6, 10]
y = [5, 13, 27]
plt.plot(x, y)
plt.plot(y, y)
plt.plot(y, x)

# %%
import time
for i in range(50):
    print(i)
    time.sleep(.1)

# %%
def throwAnError(x):
    raise Exception('This is an error message.')

throwAnError(x)
```

2. Execute the code in an interactive window, either `Run file in interactive window` related commands or the code lenses.
 a. This will open the interactive window editor to be saved
3. Save the Interactive Window editor. It can only be saved as .ipynb, and the editor will re-open as a notebook. 
  a. loading is [not supported](https://github.com/microsoft/vscode/issues/183985)
4. Create another interactive window and Switch `files.hotExit` to off. Then close vscode to ensure you are prompted to save.
  a. test both save and revert options.

**Comment by ulugbekna** [comment]
> Create a python file and add a few code cells (# %% marks a cell), e.g.
> Save the Interactive Window editor.

Do you mean that I need to create a new untitled file, put the code with some cell markers, and try saving?

> It can only be saved as .ipynb

Does this mean the filename for save should by `.ipynb` and not `.py`? Because I get `.py`

<img width="864" alt="image" src="https://github.com/microsoft/vscode/assets/16353531/daf328eb-a449-45ff-91f4-055396de972a">

> the editor will re-open as a notebook.

I save a new untitled file with the code you provided as `.ipynb`. It does try reopening it in a notebook editor but fails: 

https://github.com/microsoft/vscode/assets/16353531/d39a36fb-cefd-401c-bdf4-87381a1429b1

**Comment by amunger** [comment]
@ulugbekna - sorry, I missed a step. you need to execute the code in the .py file with the code lenses or `run file in interactive window`. It's the interactive window that is intended to be saved.

**Comment by ulugbekna** [comment]
@amunger thanks for clarification! feature works well for me 👍
