### ISSUE TITLE
Test: notebook saving perf improvement for Remote SSH

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#186238]
Refs: #172345

- [x] anyOS @eleanorjboyd
- [x] anyOS @rzhao271

Complexity: 3

Authors: @rebornix, @bpasero  

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23186238%0A%0A&assignees=rebornix,bpasero)

---

When using a notebook editor in Remote SSH, both the notebook serializer (the extension handles file parsing and decoding) and file system provider are running in the remote extension host. However the renderer window is the coordinator for saving. If users have auto save turned on, on each save, the notebook document model or its buffer are being sent back and forth between the renderer and remote extension host 3 times. When users' network has limited upload speed (say 10 Mbps) and saving a 10MB notebook can starve the whole IPC channel between Remote EH and Renderer.

This happens more easily when users are doing model training in notebooks in a MB size notebook:

* kernel sent output to renderer
* in a second auto save triggers
* MB buffer sent to remote extension host
* kernel sent another output to renderer
* ...

This can easily block the whole VS Code and make it unresponsive.

This month we added an experiment to run notebook saves all in the remote extension host. A simple way to test this is

* Remote SSH into a workspace
* Install Jupyter and Python extensions
* Add setting `"notebook.experimental.remoteSave": true` to your remote/user settings
* Turn on auto save
* Reload the window
* Open a notebook which is MB https://github.com/rebornix/notebook-testdata/blob/main/large.ipynb
* Run a simple for loop to print 
```
import time

for i in range(0, 50):
    print(i)
    time.sleep(1)
```

Please test
* if operations in the workbench is smooth, e.g., creating a file
* check if VS Code is sending unnecessary data to the remote (by checking the network)

**Comment by alexr00** [comment]
> Open a notebook which is MB https://github.com/rebornix/notebooks/blob/main/bugs/large.ipynb

How big does the notebook need to be? That repo is private.

**Comment by eleanorjboyd** [comment]
It all worked well for me, was able to create a file, write, and save it while the long-running operation was performed! Also saw no network requests when just running the notebook. Thanks!

**Comment by rebornix** [comment]
@alexr00 do you have Jupyter and Python extension installed on the remote extension host? https://github.com/microsoft/vscode/issues/186364 is a regression but if you have these two extensions installed, you should be able to see kernels.

To ensure we finish test today, I'll ask Redmond to help with this item but I would really appreciate if you continue testing with this. Thanks in advance!

**Comment by alexr00** [comment]
@rebornix I didn't have those two extensions installed because I didn't think my setup all the way through. When I test SSH I just SSH to localhost, so I think that if I have the extension installed locally then it is also installed remote because it is localhost. However, this is not the case, which I know if I stop to think about it. I have tested again and it works as expected.
