### ISSUE TITLE
"Connect to" picker is empty when quickly clicked after window opening

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#186276]
Testing #186222

![image](https://github.com/microsoft/vscode/assets/900690/3525d50f-4681-47a9-84f4-55b2739f051e)

A second click reveals:

![image](https://github.com/microsoft/vscode/assets/900690/d2879f8a-c9e7-48b3-a862-992c8777bd78)

**Comment by bhavyaus** [comment]
We wait till extension gallery service availability before populating this list. Ill add a context key to hide the start entry till all items are populated.

**Comment by rzhao271** [comment]
I confirmed that when the window first opens, the "Connect to..." start entry isn't there, but after it appears, clicking on it reveals all the options.
