### ISSUE TITLE
Test: NB toolbar Run All + Stop execution actions

### ISSUE THREAD

**Issue by Yoyokrazy** [microsoft/vscode#186262]
Refs: #184194

- [x] anyOS @deepak1556
- [x] anyOS @bamurtaugh 

Complexity: 1

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23186262%0A%0A&assignees=Yoyokrazy)

--- 
## Summary:

There was previously a bug when executing notebook code using a kernel without an interrupt handler. After executing the Run All action, it would not hide, and the Stop Execution action would appear alongside.

Intended behavior is for the Stop Execution action to replace the Run All action.

## Steps to Test:
- Open a notebook, and select a kernel without an interrupt handler.
  - [This extension](https://marketplace.visualstudio.com/items?itemName=joyceerhl.vscode-pyodide) works well to test with.
- Execute multiple code cells, and ensure that Run All and Stop Execution do not appear side by side. Running a cell with a sleep in it makes this more visible.

--- 
Thanks so much for testing!

**Comment by deepak1556** [comment]
Using the kernel from https://marketplace.visualstudio.com/items?itemName=joyceerhl.vscode-pyodide and the following code with sleep didn't help to verify the issue

```
import time

print("Hello World!")
time.sleep(30)
print('Done!')
```

I ended up using examples from https://jupyterlite.readthedocs.io/en/latest/_static/lab/index.html to get long enough execution. Would be great if some notebook samples are provided with the test plan :)

**Comment by Yoyokrazy** [comment]
I'll toss a notebook up now! Thanks for the feedback and testing 👍
