### ISSUE TITLE
Test: screen reader experience in copilot panel and inline chat 

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#186218]
Refs https://github.com/microsoft/vscode/issues/185705
Refs https://github.com/microsoft/vscode/issues/185690
Refs https://github.com/microsoft/vscode-copilot/issues/313
Refs https://github.com/microsoft/vscode-copilot/issues/197

- [x] Windows @rebornix 
- [x] macOS @ulugbekna 
- [x] anyOS @TylerLeonhardt 

Complexity: 5

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23186218%0A%0A&assignees=meganrogge)

---

Using a screen reader, test out the copilot panel and inline chat experiences. 

We now have audio cues that can be found via `audioCue.chat...`. Try these out in any combination. 

There have been improvements made to each feature's accessibility help menus. Try these as well via `alt+f1` or `Open Accessibility Help`.

**Comment by ulugbekna** [comment]
excited to see improvements in accessibility for chats, thanks! ❤️ 

made two issues with some comments
