### ISSUE TITLE
Tunnel to WSL2 refuses connection

### ISSUE THREAD

**Issue by xisui-MSFT** [microsoft/vscode#186205]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.79.2
- OS Version: Windows 11 (22621.1926) + WSL2 (Ubuntu 22.04)

Steps to Reproduce:

1. Create a workspace extension, in which create a server listening to a port (workspacePort)
2. Create a UI extension, in which create a tunnel, like this (proposed API `tunnels` is required):
    ```ts
    tunnel = await vscode.workspace.openTunnel({ remoteAddress: { port: workspacePort, host: 'localhost' } });
    ```
3. In the UI extension, connect to the tunnel:
    ```ts
    const tunnelConnection = new Promise<void>((resolve, reject) => {

        const doConnect = () => tunnelSocket.connect(tunnelPort, 'localhost', () => resolve());

        tunnelSocket.on('data', data => {
            ... // Do something
        });

        tunnelSocket.on('end', () => {
            ... // Do something
            resolve();
        });

        tunnelSocket.on('error', err => {
            if (err) {
                console.log(`Error: ${err.message}`);
            }

            ... // Do something
            reject();
        });

        doConnect();
    });
    ```
4. Run the extensions, so that the UI extension runs locally, and the workspace extension runs in WSL. Notice that error messages like `Error: connect ECONNREFUSED 127.0.0.1:46871` are shown in the console.

A side question: This does NOT repro for docker containers or codespaces. But I wonder if there's a better way to do raw TCP communication between host and WSL?

**Comment by xisui-MSFT** [comment]
@alexr00 Could you please take a look?

**Comment by alexr00** [comment]
This is by design. We do not support port forwarding with a WSL connection. Someone else just made a feature request to support port forwarding with WSL: https://github.com/microsoft/vscode-remote-release/issues/8621

**Comment by Sandros94** [comment]
@xisui-MSFT, if you are interested, be sure to go about and upvote [that feature request](https://github.com/microsoft/vscode-remote-release/issues/8621).
