### ISSUE TITLE
No remote indicator in empty window

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#186278]
Testing #186222

![image](https://github.com/microsoft/vscode/assets/900690/7f508651-af0b-4ae6-8232-3deb97ace0de)

I would have expected a remote indicator with menu in the status bar in empty windows. This was with an empty profile.

**Comment by joyceerhl** [comment]
@bpasero in this scenario, do you have any remote extensions installed (since I see you are using a temp profile)? The remote indicator is currently suppressed when there aren't any remote extensions already installed. IMHO now that the remote indicator has items which allow installing remote extensions, it makes sense to consider showing it always.

**Comment by bhavyaus** [comment]
I'll enable to show it always.

**Comment by bpasero** [comment]
I am not a fan of showing it delayed, imho it should be there on startup and if we need to wait for anything, the picker should show a progress bar.

![Recording 2023-06-28 at 15 09 20](https://github.com/microsoft/vscode/assets/900690/942e1bab-4311-4f4e-8257-3960976173d1)

**Comment by bhavyaus** [comment]
> I am not a fan of showing it delayed, imho it should be there on startup and if we need to wait for anything, the picker should show a progress bar.
> 
> ![Recording 2023-06-28 at 15 09 20](https://user-images.githubusercontent.com/900690/249479801-942e1bab-4311-4f4e-8257-3960976173d1.gif)

We need to wait for the extension gallery service to be initialized before we can display the remote indicator as being available since we show options to install remote extensions. 
Did you mean the remote indicator quick pick should show a progress bar when clicked while it's still initializing?

**Comment by bpasero** [comment]
My recommendation is to keep the UI stable when a user starts into an empty workspace because that is the default scenario for every new user. So I suggest to show the remote indicator instantly and the picker with a progress bar as needed.
