### ISSUE TITLE
Test: Terminal launch and pty host improvements

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#186228]
Refs: #186070, #186069, #185396, #185393, #185392, #185391, #185379, #185256, #185254, #130320

- [x] macOS @aiday-mar
- [x] linux @alexr00 
- [x] windows @bamurtaugh

Complexity: 3

Authors: @Tyriar, @meganrogge 

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23186228%0A%0A&assignees=Tyriar,meganrogge)

---

A lot of improvements have happened to how terminals reconnect/revive and how the pty host starts up. This is just a general test, please test at least the following:

- Create several terminals, type in them, reload the window
  - They should reconnect
- Create several terminals, type in them, exit the application and restart
  - They should "revive" with a restored buffer
- Reload twice in quick succession
- Full a terminal's scrollback (eg. `ls -lR ~` or `tree`) and reload
- Anything other edge case you can think of.

If you spot something weird, enable trace logging and capture the Pty Host channel log and the Terminal channel log.

**Comment by aiday-mar** [comment]
Hi @Tyriar, I am unsure if I am testing wrong, let me know. I opened a VS Code window, the VS Code repo and created three zsh terminals where I typed in each a print statement. I closed the window, opened a VS Code instance with the VS Code repo. From what I understood I should be seeing the print statements from before?

https://github.com/microsoft/vscode/assets/61460952/860f63a3-9e4c-4977-a47f-266a7b651b7b

I enabled trace logging, and I get the following output under the PTY host output view and in the Terminal output view. 

PTY host output before exiting and restarting: [pty_host_before.txt](https://github.com/microsoft/vscode/files/11878022/pty
Terminal output before exiting and restarting: [terminal_output.txt](https://github.com/microsoft/vscode/files/11878024/terminal_output.txt)
_host_before.txt)

PTY host output after exiting and restarting: [pty_host_after.txt](https://github.com/microsoft/vscode/files/11878041/pty_host_after.txt)

Terminal output after exiting and restarting: [terminal_output_after.txt](https://github.com/microsoft/vscode/files/11878043/terminal_output_after.txt)

**Comment by Tyriar** [comment]
@aiday-mar why didn't the window load vscode again? You might have some setting which messes with this?

**Comment by Tyriar** [comment]
@aiday-mar on macOS by exit the application I mean cmd+q to kill the main process, try doing that instead of hitting the red x

**Comment by bamurtaugh** [comment]
Looks great!

@aiday-mar I'll leave this issue open since I see you're still assigned to it, but please feel free to close if your testing is actually complete (as I see your box is checked in the main issue).

**Comment by Tyriar** [comment]
Let's close as she's checked off

**Comment by aiday-mar** [comment]
Hey @Tyriar, I see thanks for the note. Yes it works for me now
