### ISSUE TITLE
Issue report includes the same remote info n times

### ISSUE THREAD

**Issue by dbaeumer** [microsoft/vscode#186271]
See screen shot

<img width="707" alt="capture" src="https://github.com/microsoft/vscode/assets/1931590/faff52f7-a47a-483e-9b23-17163e8b5d03">

**Comment by justschen** [comment]
Been monitoring this in the past few iterations - @dbaeumer does this still happen?

**Comment by dbaeumer** [comment]
Couldn't reproduce.
