### ISSUE TITLE
Readonly hover seems to disappear slightly too fast

### ISSUE THREAD

**Issue by daviddossett** [microsoft/vscode#186257]
Testing #186170

Tiniest of nits, and perhaps this is inherited from all hovers, but I felt like the hover disappeared too quickly. If I was reading particularly slowly or looked away and then back at the message, I might've missed it.

**Comment by bpasero** [comment]
👍 felt the same, I think using the workbench hover infra would help.

**Comment by hediet** [comment]
Also, it disappears when you still hover on it:

![Code_-_Insiders_CYA8RjUh6T](https://github.com/microsoft/vscode/assets/2931520/a0e2dfbc-961e-4d27-a5a9-d98b4c8b8ab7)

**Comment by bpasero** [comment]
I think given the new complexity of this hover and the actions we should do a tactical fix here. I suggest to remove the timer that removes the message automatically after 3 seconds:

https://github.com/microsoft/vscode/blob/ac34ea3a6e3334c2bfb01f5c234863747e07f18c/src/vs/editor/contrib/message/browser/messageController.ts#L92-L93

There are still other listeners in place to hide the message, so I think we are good.

**Comment by ulugbekna** [comment]
trying to verify: "readonly hover" means "hover in readonly files" ?

**Comment by bpasero** [comment]
@ulugbekna best to verify would be in `vscode` repo open a file from `node_modules` folder and try to edit in such a file. You should see a hover with a link.
