### ISSUE TITLE
Simple file dialog doesn't validate nonsense default path

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#186295]
Testing #186172

* configure `files.dialog.defaultPath` to be nonsense 
* use `"files.simpleDialog.enable": true`
* in an empty workspace open file picker via `cmd+o`
* 😕 the file picker shows the nonsense path, the native file picker doesn't do that

<img width="905" alt="Screenshot 2023-06-27 at 11 40 25" src="https://github.com/microsoft/vscode/assets/1794099/44af200e-e4b7-4a9e-8515-0030e0e7aa8e">

**Comment by jrieken** [comment]
Unsure if the setting itself or the dialog should validate the path. Ideally the settings editor already gives me a warning about a misspelled path

**Comment by bpasero** [comment]
Fix will be to refuse to take invalid paths in the dialogs.
