### ISSUE TITLE
Please allow multiple commands per keybinding

### ISSUE THREAD

**Issue by kobi2187** [Microsoft/vscode#18621]
- VSCode Version: Version 1.9.0-insider
- OS Version: Linux Mint 18.1 Cinnamon 64 bit

Steps to Reproduce:
Feature request...
1. open Keyboard Shortcuts from File Prefs menu. keybindings.json
2. look at the triple of: key, command, when.
3. please allow command to also have type Array of String, not just String. 
4. The point is to allow user to run several commands one after the other with one shortcut.
Example: build code, focus on errors pane, 
``` 
        {
	"key": "F8",
	"command":  [ "workbench.action.tasks.build" , 
                      "workbench.action.showErrorsWarnings" ]
	},
```

**Comment by dbaeumer** [comment]
@alexandrudima not sure if this deservers a general feature or whether this is better handled  in the task framework. So feel free to move to me :-)

**Comment by bohenderson** [comment]
In the meantime, there's an extension that will do this for you.
https://marketplace.visualstudio.com/items?itemName=geddski.macros

**Comment by alexandrudima** [comment]
Dup of #871
