### ISSUE TITLE
Show progress notification while setting up troubleshooting profile

### ISSUE THREAD

**Issue by dbaeumer** [microsoft/vscode#186269]
Testing #186171

I started the Troubleshoot issue flow and it took a long time to create my initial profile. All I had was a status bar item which took me a while to discover (I actually thought something else went wrong). I would love to see and editor / web view better guiding me through that process by:

- listing the steps and adding check marks when done
- showing me the number of bisects still necessary
- giving me a final report.

**Comment by dbaeumer** [comment]
<img width="258" alt="capture" src="https://github.com/microsoft/vscode/assets/1931590/2c0ba3d8-890d-44e8-b5d6-946beb7c3ff2">

**Comment by dbaeumer** [comment]
We should also have a UI to always stop the process (see https://github.com/microsoft/vscode/issues/186270) for a situation where this is useful

**Comment by sandy081** [comment]
Actually, setting up the trouble shooting profile should be fast and instant.

**Comment by dbaeumer** [comment]
Was not for me :-(

**Comment by sandy081** [comment]
Following notification is shown now

![Image](https://github.com/microsoft/vscode/assets/10746682/15b9cf2d-ab3d-4d68-87d3-2d8d78fb3148)
