### ISSUE TITLE
Focusing hover still breaks keyboard navigation

### ISSUE THREAD

**Issue by nmay231** [microsoft/vscode#186223]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Insiders Version: `1.80.0-insider b4952d14a465572e33f0635ef58de089227b8876`
- VS Code Version: `1.79.2 695af097c7bd098fbf017ce3ac85e09bbc5dda06`
- OS Version: Ubuntu 22.04.2 LTS

Steps to Reproduce:

> 1. Press Cmd K, Cmd I twice on a symbol which has a hover.
> 2. Press Escape
> 3. Press UpArrow or DownArrow
> bug Nothing happens, since focus didn't return to the editor after pressing Escape.

This issue is identical to #177806 which was supposedly fixed by #177859. I do not have a windows machine atm, so I cannot test if this is exclusively an issue with the snap-installed version of vscode, but I highly doubt it is.

`shift-tab` does give focus back to editor, but that's just a workaround.

**Comment by aiday-mar** [comment]
Hi thanks for filing the issue. It appears this is a regression from the previous work done on making the hover resizable. A fix will be made.
