### ISSUE TITLE
Default path not used when opening a file

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode#186249]
Testing #186172

* On a Mac
* Settings updated as follows
```jsonc
"files.dialog.defaultPath": "/Users/donjayamanne/crap",
	"files.simpleDialog.enable": false
```
* Exit vscode
* Open vscode
* Go into `File -> Open`
* Event tried `cmd+o` and that doesn't make any difference
* Does not work with `Save` either
File dialog points to my home directory instead of the folder I setup

Tried the same in a docker container as well, hence does not work in local and remove. (unless I'm missing something)

**Comment by bpasero** [comment]
Thanks, unfortunately the change only lands in todays insider.
