### ISSUE TITLE
We have both Accessibility View and Accessibility Help commands

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#186294]
Testing #186214

Write now we have both "Accessibility View" and "Accessibility Help" commands. Could we unify them in once command, why do we need both?

If we really need to keep the commands separate, could we at least use the same keyboard shortcut? So that when users learn to use `Ctrl + F1` they can use the same all across the workbench

![Screenshot 2023-06-27 at 11 40 35](https://github.com/microsoft/vscode/assets/1926584/d7618f8c-d976-4d1f-8890-8c1144dfc700)

**Comment by meganrogge** [comment]
They do different things and there may be a case where we want each to apply separately - for example, with focus in the notebook output, we will have an accessibility help menu and also an accessible view.

**Comment by isidorn** [comment]
Thanks for clarifying. But is that really a use case? In what scenario would a user want to have two separate experiences? Why not combine them into one for the notebook example you provided?

**Comment by meganrogge** [comment]
In my opinion, mixing help menu content with the content of a particular chat response, hover, or notebook output would not be expected or helpful.

**Comment by meganrogge** [comment]
I say that because then the user has to navigate through all of the content or help menu to reach what they want. Instead, with this approach, they just go to it directly using the particular keybinding.

**Comment by isidorn** [comment]
Ok. Feel free to close this if we do not hear user feedback that aligns with my suggestion.
