### ISSUE TITLE
Test: Notebook Toolbar rewrite

### ISSUE THREAD

**Issue by Yoyokrazy** [microsoft/vscode#186261]
Refs: #161119

- [x] anyOS @bhavyaus
- [x] anyOS @aiday-mar 

Complexity: 2

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23186261%0A%0A&assignees=Yoyokrazy)

--- 
## Summary:

The notebook toolbar was refactored to adopt the Workbench toolbar, allowing users to hide certain actions as they want. 

## Steps to Test:
- Open a notebook, and select a kernel, populating all of the actions in the toolbar
- Test the following for the three settings: (`notebook.globalToolbarShowLabel` with `always/never/dynamic`)
  - Resize your window and ensure that actions overflow into the secondary menu properly.
  - Resize your window and ensure there is never a separator between an action and the secondary menu.
  - Hide actions and ensure they end up in the overflow menu inside their own divided section
    - The secondary menu should have three sections: (top) Hidden | Overflow | Secondary (bottom), see screenshot for example
  - Hide all actions between two separators, ensure that only one separator is now rendering. 
  - Hide all actions before the first separator, ensuring the separator is hidden as well once there are none left preceding it.
  - Hide all actions after the last separator, ensuring the separator is hidden as well once none follow it

    
![image](https://github.com/microsoft/vscode/assets/12552271/ddc3db11-ea14-481e-9459-274bc2a9c2dd)
*restart is the hidden action here
   
--- 
Thanks so much for testing!

**Comment by aiday-mar** [comment]
Hi @Yoyokrazy! Great work. I was testing point 3 in the list and I see only two sections, the menu appears to be containing the same commands, but the restart command is not separated from the rest of the commands as in the screenshot. I am wondering if this is expected?

<img width="614" alt="Screenshot 2023-06-27 at 14 28 00" src="https://github.com/microsoft/vscode/assets/61460952/78491e66-5628-4c5b-beab-1c7c0e9ecfa4">
