### ISSUE TITLE
Readonly hover link doesn't look like a link

### ISSUE THREAD

**Issue by daviddossett** [microsoft/vscode#186256]
Testing #186170

This would benefit from an underline instead of the bold treatment to match the rendering we use in the workspace banner links (e.g. restricted mode)

<img width="490" alt="CleanShot 2023-06-26 at 21 53 54@2x" src="https://github.com/microsoft/vscode/assets/25163139/fc893179-0ab0-4c02-a2ce-43ad22ad27eb">

**Comment by bpasero** [comment]
I also think its hard to discover, but I think we are not using underline for links in hovers so far?

**Comment by alexr00** [comment]
We also do not show underlines in other places we show markdown in hovers:

<img width="485" alt="image" src="https://github.com/microsoft/vscode/assets/38270282/c92389a2-0224-4a45-9e18-a0172a3f98db">

**Comment by bpasero** [comment]
I think the intent of the blue color in the message widget is to draw more attention, i.e. giving the signal of an information message vs. just being a normal tooltip. But maybe we can make the background color of the widget the same as hovers and then user blue color for links. I think that way we can still keep the blue border but it will not collide with the links.

**Comment by bpasero** [comment]
Sample with a mix of hover colors and info colors for border:

<img width="764" alt="image" src="https://github.com/microsoft/vscode/assets/900690/05f86892-36d3-4059-bb05-5c7095aead2c">

**Comment by bpasero** [comment]
And in dark theme:

![image](https://github.com/microsoft/vscode/assets/900690/25c9907b-9ad1-4dfc-9a5a-fcc5d657db6c)

**Changes I did:**
* use hover colors
* use the same border radius of `3px` as in editor hovers
* allow to tab into the message with keyboard to invoke the link within
