### ISSUE TITLE
Emoji ascii warning showing up twice

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#186206]
Repro:

Open https://insiders.vscode.dev/github/microsoft/vscode-internalbacklog/blob/main/templates/endgame-plan.md
Hover the warning

![image](https://github.com/microsoft/vscode/assets/2193314/562da891-2a2d-440a-a1ab-0b804b136594)

**Comment by hediet** [comment]
Monaco editor repro
https://microsoft.github.io/monaco-editor/playground.html?source=v0.40.0-dev.20230621#XQAAAAJjAQAAAAAAAABBqQkHQ5NjdMjwa-jY7SIQ9S7DNlzs5W-mwj0fe1ZCDRFc9ws9XQE0SJE1jc2VKxhaLFIw9vEWSxW3yscwzZypW_1uhs0-3YGTBOsVJ4S4FwfCDQb5-2uUHXTVAefbVSd9IzaZ_vv9VR9KugsKixL9jLeD7HHL26qxFDltSgM4yCD-Oxo0Le1R7t_ezMZs4Fqbwf2LLftlGDbVC0pzlSC0FKh_zxEB2PYU8mnloEYCRxBUCirzPZl-pNGYPkUzLUS30fWAevSH-YVy8w-ajItWMcFieVh3ABCemhcYdAR5_CQZMEToq6B5ANZWC7FKaenDFFIJTbFnggipMs1JRuN612Pva9BBI9vxuZ-HELRkWd7_Uk0jdXWCIIsNrZFJ_-BvI2A
