### ISSUE TITLE
[Bug] Resizable hover can be made slightly taller after initial render

### ISSUE THREAD

**Issue by daviddossett** [microsoft/vscode#186260]
Testing #185751

While this is related to a resizing situation:

> Verify that during resizing, the maximum possible height achievable by the content hover is capped by the contents inside (that is, the content hover can not be made bigger if there is nothing more to show) or by the available space.

..I noticed that I could make the hover slightly taller than it's initial render. Not sure if this is a real issue or intentional but felt worth capturing here.

https://github.com/microsoft/vscode/assets/25163139/04a3db70-ab70-43be-ae6d-fc53c50da3c5

**Comment by aiday-mar** [comment]
Hi @daviddossett, thanks for filing the issue. The maximum height currently is indeed the content height plus 6 pixels. These 6 pixels were added to fix another issue, but it should not be as so. I'll be looking into how to remove these pixels
