### ISSUE TITLE
Copy path of the directory which contains space

### ISSUE THREAD

**Issue by QueenYoung** [Microsoft/vscode#18629]
- VSCode Version: Code 1.8.1 (ee428b0eead68bf0fb99ab5fdc4439be227b6281, 2016-12-19T14:42:49.304Z)
- OS Version: Darwin x64 16.4.0
- Extensions:

|Extension|Author|Version|
|---|---|---|
|beautify|HookyQR|0.7.3|
|html-snippets|abusaidm|0.0.18|
|Handlebars|andrejunges|0.2.0|
|materialcolorsnippets|brunnerlivio|0.1.1|
|npm-intellisense|christian-kohler|1.2.1|
|path-intellisense|christian-kohler|1.2.0|
|vscode-eslint|dbaeumer|1.2.2|
|auto-close-tag|formulahendry|0.3.8|
|code-runner|formulahendry|0.6.5|
|haskell-linter|hoovercj|0.0.6|
|vscode-ghc-mod|hoovercj|1.0.1|
|language-haskell|justusadam|1.4.4|
|vscode-clang|mitaki28|0.2.1|
|HTMLHint|mkaufman|0.3.3|
|Theme-MaterialKit|ms-vscode|0.1.1|
|atom-keybindings|ms-vscode|1.8.3|
|cpptools|ms-vscode|0.9.3|
|debugger-for-chrome|msjsdiag|2.4.2|
|ios-snippets|ornithologist|0.0.15|
|vscode-swift-language|rlovelett|0.1.0|
|vscode-icons|robertohuertasm|7.0.1|
|Spell|seanmcbreen|0.9.1|
|addDocComments|stevencl|0.0.8|
|vim|vscodevim|0.4.10|
|JavaScriptSnippets|xabikos|1.2.0|
|Material-theme|zhuangtongfa|1.0.3|

---

Steps to Reproduce:

1. The name of a dir or file contains spaces
2. right click it and copy the path in the explorer 

But the path doesn't append the `\` automatically in the correct place.

e.g:
I have a dir is `/code/It's good/`
when I copy its path, rather `/code/it's\ good/` than just `/code/it's good/`.

**Comment by bpasero** [comment]
@QueenYoung I cannot reproduce when I invoke the "Copy Path" action on the explorer, are you maybe using an extension? Can you share screenshot or video of the bug?

**Comment by QueenYoung** [comment]
![image](https://cloud.githubusercontent.com/assets/11444431/22016894/de7cd0fe-dce2-11e6-8b69-41381f326595.png)
This is Chinese version, and the highlight is what I mean(`Copy Path`).
I hope the `Code` to identify my copy path is DIR or just a normal file.
And if gets the dir path, it can append the `\` in a correct place. 
You know, most time, we use the dir path in **terminal**.
Otherwise, just copy it and do nothing, because we maybe need this in a `browser`.

I don't sure whether this feature can be implemented, even could be called a `bug`.

**Comment by bpasero** [comment]
@QueenYoung ah I think now I get it, you want the copy operation to give you `/code/it's\ good/` but instead you are getting `/code/it's good/` ?

**Comment by QueenYoung** [comment]
@bpasero yeah, right 👍 ! To apologize for my English 😞 .
But I don't know whether other people think this feature is right.
And maybe in `Windows`, append `\` will be an error?

**Comment by bpasero** [comment]
I am not sure, we are returning the path as it is, without special escaping rules. I think your escaping is only needed when used in the terminal? But people might want to use it elsewhere so I am not sure escaping makes sense in all cases.

This could be done via an extension maybe ("Copy Terminal Path").

**Comment by QueenYoung** [comment]
Yeah, you are right. Please close the issues 😃 .
