### ISSUE TITLE
Test: Unified Remote Menu for remote menu and remote start entry.

### ISSUE THREAD

**Issue by bhavyaus** [microsoft/vscode#186258]
Refs: https://github.com/microsoft/vscode/issues/184845

- [x] windows @Yoyokrazy 
- [x] mac @TylerLeonhardt
- [x] linux @alexr00

Complexity: 2

Authors: @bhavyaus 

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23186258%0A%0A&assignees=bhavyaus)

---

**Feature**
The remote indicator and the remote start entry now share the same remote command. As a result,
- the remote indicator now supports the ability to 1-click download, install and get started with a remote extension.
- the remote start list entry now supports Continue on scenarios where supported. 

### Steps for Remote Indicator
1. Ensure you have atleast one remote extension not installed.
2. Click on the remote indicator and verify that the not-installed extensions shows up as installable in the quick pick.

<img width="369" alt="image" src="https://github.com/microsoft/vscode/assets/25044782/939a7831-9990-49af-ae55-9584d50c0993"> 

 3. Click to install the remote extension and ensure that you get started with that remote development scenario.

### Steps for Remote Start Entry
1. Open the welcome page in vscode
<img width="354" alt="image" src="https://user-images.githubusercontent.com/25044782/226445406-6c0d0056-2d04-4c7d-9cee-5aed660ce0d5.png">

2. Use the "Connect to..."  start list entry in the welcome page to get started with a new remote connection such as Tunnel or Remote Repository. 

3. Re-open the welcome page and click on the "Connect to..." start list entry again and verify that you see the "Continue on" commands for your remote scenario,

**Comment by Yoyokrazy** [comment]
Blocked via #186440, will pick up late if there's a fix. Otherwise can hand off to someone without this blocker, might be specific to something in my setup.
