### ISSUE TITLE
Inconsistencies with relative default path

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#186297]
Testing #186172

* configure files.dialog.defaultPath to be `../`
* open native file picker -> it shows `/`
* open simple file picker -> it shows `/../`

<img width="720" alt="Screenshot 2023-06-27 at 11 48 22" src="https://github.com/microsoft/vscode/assets/1794099/4dd75faf-f773-442e-a15c-ff4ebca6e678">

**Comment by bpasero** [comment]
I think we should not allow relative paths, i.e. show an error in the settings editor and also refuse to take it on the dialog side of things.
