### ISSUE TITLE
HTML comment tags break Markdown list indentation

### ISSUE THREAD

**Issue by rokejulianlockhart** [microsoft/vscode#186232]
Does this issue occur when all extensions are disabled?: Yes

0. VS Code Version: 

	```log
	rokejulianlockhart@RQN6C6:~> code-insiders -v
	1.80.0-insider
	49b8e2d5410795e5a23a9c6b7f99b97f4afb4b47
	x64
	rokejulianlockhart@RQN6C6:~>
	```

0. OS Version: 

	```log
	rokejulianlockhart@RQN6C6:~> uname -a
	Linux RQN6C6 6.3.9-1-default #1 SMP PREEMPT_DYNAMIC Thu Jun 22 03:53:43 UTC 2023 (0df701d) x86_64 x86_64 x86_64 GNU/Linux
	rokejulianlockhart@RQN6C6:~>
	```

0. **Steps to Reproduce:**

	```markdown
	0. placeholder
	
	    text
	
	0. placeholder
	
	    text
	
	0. placeholder
	
	    text
	
	    0. placeholder
	
	        text
	
	    0. placeholder
	
	        text
	
	    0. placeholder
	
	        text
	
	        0. placeholder
	
	            text
	
	        0. placeholder
	
	            text
	
	        0. placeholder
	
	            text
	
	0. placeholder
	
	    text
	
	<!--
	
	0. placeholder
	
	    text
	
	-->
	
	0. placeholder
	
	    text
	
	    0. placeholder
	
	        text
	
	    <!--
	
	    0. placeholder
	
	        text
	
	    -->
	
	    0. placeholder
	
	        text
	
	        0. placeholder
	
	            text
	
	        <!--
	
	        0. placeholder
	
	            text
	
	        -->
	
	        0. placeholder
	
	            text
	```
	
	(scroll) produces
	
	![image](https://github.com/markdown-it/markdown-it/assets/42837531/702b502b-4cfd-4438-b9e8-73c4b8298aef)
	
	which is obviously wrong.

	---
	
	Due to https://github.com/microsoft/vscode/issues/184429#issuecomment-1585180018, reported at https://github.com/microsoft/vscode/issues/184429#issuecomment-1585180018. Close if unnecessary to track here.

**Comment by mjbvz** [comment]
This matches [how the common spec implementation renders it](https://spec.commonmark.org/dingus/?text=0.%20placeholder%0A%0A%20%20%20%20text%0A%0A0.%20placeholder%0A%0A%20%20%20%20text%0A%0A0.%20placeholder%0A%0A%20%20%20%20text%0A%0A%20%20%20%200.%20placeholder%0A%0A%20%20%20%20%20%20%20%20text%0A%0A%20%20%20%200.%20placeholder%0A%0A%20%20%20%20%20%20%20%20text%0A%0A%20%20%20%200.%20placeholder%0A%0A%20%20%20%20%20%20%20%20text%0A%0A%20%20%20%20%20%20%20%200.%20placeholder%0A%0A%20%20%20%20%20%20%20%20%20%20%20%20text%0A%0A%20%20%20%20%20%20%20%200.%20placeholder%0A%0A%20%20%20%20%20%20%20%20%20%20%20%20text%0A%0A%20%20%20%20%20%20%20%200.%20placeholder%0A%0A%20%20%20%20%20%20%20%20%20%20%20%20text%0A%0A0.%20placeholder%0A%0A%20%20%20%20text%0A%0A%3C!--%0A%0A0.%20placeholder%0A%0A%20%20%20%20text%0A%0A--%3E%0A%0A0.%20placeholder%0A%0A%20%20%20%20text%0A%0A%20%20%20%200.%20placeholder%0A%0A%20%20%20%20%20%20%20%20text%0A%0A%20%20%20%20%3C!--%0A%0A%20%20%20%200.%20placeholder%0A%0A%20%20%20%20%20%20%20%20text%0A%0A%20%20%20%20--%3E%0A%0A%20%20%20%200.%20placeholder%0A%0A%20%20%20%20%20%20%20%20text%0A%0A%20%20%20%20%20%20%20%200.%20placeholder%0A%0A%20%20%20%20%20%20%20%20%20%20%20%20text%0A%0A%20%20%20%20%20%20%20%20%3C!--%0A%0A%20%20%20%20%20%20%20%200.%20placeholder%0A%0A%20%20%20%20%20%20%20%20%20%20%20%20text%0A%0A%20%20%20%20%20%20%20%20--%3E%0A%0A%20%20%20%20%20%20%20%200.%20placeholder%0A%0A%20%20%20%20%20%20%20%20%20%20%20%20text)

If you feel this in correct, please follow up with Common mark

**Comment by rokejulianlockhart** [comment]
Probably best to close as not planned then, right?

**Comment by vassudanagunta** [comment]
This isn't a CommonMark or Markdown-it bug. See https://talk.commonmark.org/t/html-comment-tags-break-markdown-list-indentation/4459/2?u=vas

**Comment by rokejulianlockhart** [comment]
@vassudanagunta, that comment merely states that current CommonMark HTML comment tag support is basic. Considering the obvious formatting issues with no evident benefit to their continued existence, I have, per the instruction stated within that response, filed this as an issue at https://github.com/commonmark/commonmark-spec/issues/741#issue-1814957180.
