### ISSUE TITLE
Test: `Open Accessibility Help` command

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#186217]
Refs #183363

- [x] Windows @cwebster-99 
- [x] macOS @aiday-mar 
- [x] Linux @karthiknadig 

Complexity: 3

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23186217%0A%0A&assignees=meganrogge)

---

We have a new command, `Open Accessibility Help`, which allows SR users to open a help menu for any feature which registers a provider.

Currently, this can be triggered from the:

- inline chat input box
- panel chat input box
- terminal
- editor

Verify that this works well, you can reassign the keybinding, the command title makes sense, and more.

**Comment by aiday-mar** [comment]
Hi @meganrogge, looking great. I wonder if it makes sense to also show the command in the command palette?

**Comment by meganrogge** [comment]
@aiday-mar is it not showing up there for you?

![Screenshot 2023-06-27 at 8 14 11 AM](https://github.com/microsoft/vscode/assets/29464607/bb8e0318-0a7f-4a8d-b75f-e749998204ad)

**Comment by meganrogge** [comment]
@karthiknadig a gif would be helpful - sounds like a general screen reader/quick pick issue as opposed to this particular item?

**Comment by karthiknadig** [comment]
Screen capture is not able to capture the narrator box. I can show this to you over slack.

**Comment by cwebster-99** [comment]
I just retested this and am not able to get this feature to work in the terminal. I tested this earlier today and was able to see it successfully so might be a me thing 😩

**Comment by aiday-mar** [comment]
Hey @meganrogge, I was not seeing it yesterday, but I see the command in the palette today
