### ISSUE TITLE
Test our usage of Electron safeStorage APIs and review docs

### ISSUE THREAD

**Issue by TylerLeonhardt** [microsoft/vscode#186239]
Refs: https://github.com/microsoft/vscode/issues/185677

- [x] Linux @rzhao271
- [x] Linux @lramos15

Complexity: 3
Roles: Developer, Engineering Manager
Authors: @TylerLeonhardt, @deepak1556 

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23186239%0A%0A&assignees=TylerLeonhardt,deepak1556)

---

This iteration we've moved from keytar to using Electron's [safeStorage API](https://www.electronjs.org/docs/latest/api/safe-storage) for encrypting secrets. This test plan item is testing a couple of scenarios that user may run into and trying to make sure they have the tools in mind to troubleshoot.

This TPI will work best with Ubuntu.

#### Scenario 1: "We couldn't recognize your environment"

Picture this, you're using some obscure desktop environment and we don't detect it because it's not super common. VS Code should do two things:
* allow you to use a weaker encryption that `safeStorage` provides (and this persists)
* allows you to read the troubleshooting docs

To fake this, download the latest Insiders targz, extract it, and run:
```
env -u XDG_CURRENT_DESKTOP -u DESKTOP_SESSION -u GNOME_DESKTOP_SESSION_ID ~/Downloads/VSCode-linux-x64/bin/code-insiders --verbose --vmodule="*/components/os_crypt/*=1"
```

Then turn on settings sync and go through the flow. You should get a modal that tells you about your "unknown" environment. Try both options (note, the docs should go to vnext branch for now).

If you do the docs option, you should be taken to the docs but are still logged in. That's because your secrets are still stored in-memory. If you quit and relaunch VS Code the same way, that log in state should be gone.

When you do the weaker encryption option, make sure it saves `password-store` to the file opened when you run `Configure Runtime Arguments`. This means that if you kill the process and restart it using the same command, it should _not_ show you the modal and instead should "just work" as you expect.

#### Scenario 2: "Ubuntu has a weird issue, open the troubleshooting guide"

Picture this: your system isn't setup properly and your keyring isn't working as expected... but we know you're running in a GNOME-like environment. We can tell you to just go check out the docs for assistance.

> NOTE: make sure you delete the `password-store` property generated in the argv.json... and kill for VS Code for now...

This is an easier scenario because what we're gonna do is put the Keyring in a locked state... So, open the Passwords & Keys app (aka seahorse) and click the 🔓 next to the `Login` keyring. That will lock  this keyring.

Now start VS Code as normal... hitting cancel on the million modals that pop up asking you to unlock the keyring... don't do it!

Sign in to Settings Sync (keep hitting cancel on the OS modal asking you to unlock the keyring) and what you should eventually get is a notification that will bring you to the troubleshooting guide.

#### Conclusion

Our goal is to have a nice place to start enumerating docs. Linux will undoubtably have more unique ways to be misconfigured, so at least we are starting somewhere...

We're looking to make sure we help when we can and the docs make sense.

**Comment by alexr00** [comment]
I didn't get a modal for scenario 1, I just got this:

![image](https://github.com/microsoft/vscode/assets/38270282/eba4cdc9-23bf-4f53-b3f8-3837cd5bb20b)

I used device login to authenticate.

**Comment by deepak1556** [comment]
@alexr00 can you attach the logs from `env -u XDG_CURRENT_DESKTOP -u DESKTOP_SESSION -u GNOME_DESKTOP_SESSION_ID ~/Downloads/VSCode-linux-x64/bin/code-insiders --verbose --vmodule="*/components/os_crypt/*=1"`

**Comment by deepak1556** [comment]
@TylerLeonhardt the logs from @alexr00 looks good,

```
6049: 0627/120427.662568:VERBOSE1:key_storage_util_linux.cc(54)] Password storage detected desktop environment: (unknown)
6049: 0627/120427.662830:VERBOSE1:key_storage_linux.cc(122)] Selected backend for OSCrypt: BASIC_TEXT
6049: 0627/120427.662933:VERBOSE1:key_storage_linux.cc(142)] OSCrypt did not initialize a backend.
```

**Comment by deepak1556** [comment]
The check here looks incorrect https://github.com/microsoft/vscode/blob/ac34ea3a6e3334c2bfb01f5c234863747e07f18c/src/vs/workbench/services/secrets/electron-sandbox/secretStorageService.ts#L69, shouldn't it be `provider === KnownStorageProvider.unknown` ?

**Comment by alexr00** [comment]
Marking my testing as complete as Scenario 2 worked as expected. Please @ mention me in the bug for https://github.com/microsoft/vscode/issues/186239#issuecomment-1609225154 and I will verify it!

**Comment by TylerLeonhardt** [comment]
@deepak1556 os right. It should be basic text... I forgot to change that back while I was testing on macOS

**Comment by TylerLeonhardt** [comment]
PR out here: https://github.com/microsoft/vscode/pull/186346

Once this goes in I'll fire off another Insiders to this TPI can be tested

**Comment by TylerLeonhardt** [comment]
New insiders released.

**Comment by rzhao271** [comment]
Suggestion: because the verbose flag causes there to be a lot of output, would it make sense to suggest storing that info into a file?

I was able to get the "locked collection" string, though :+1:

```
$ ~/Downloads/VSCode-linux-x64/bin/code-insiders --verbose --vmodule="*/components/os_crypt/*=1" > run.log 2>&1
$ grep locked run.log
[47408:0627/114250.985588:VERBOSE1:libsecret_util_linux.cc(169)] Dummy store to unlock the default keyring failed: Cannot create an item in a locked collection
[47408:0627/114251.984576:VERBOSE1:key_storage_libsecret.cc(73)] Libsecret lookup failed: Cannot create an item in a locked collection
```

**Comment by deepak1556** [comment]
@rzhao271 thanks for the feedback, you can use `--verbose --vmodule="*/components/os_crypt/*=1" --log-file=<absolute-path>/chrome.log` to capture runtime logs in a file.

**Comment by alexr00** [comment]
Since I'd already done part of this I went back and verified Scenario 1 with the fix.
