### ISSUE TITLE
Issue logging in to Copilot

### ISSUE THREAD

**Issue by TylerLeonhardt** [microsoft/vscode#186226]
Hi @TylerLeonhardt, thank you for your reply. 
After start VSCode Insider with the parameters `--verbose --vmodule="*/components/os_crypt/*=1"`, when I try to authorize the Github Copilot the message returned at terminal is:
**ExtensionUrlTrustService#isExtensionUrlTrusted There are no configured trusted keys**
and the authentication process never ends.

_Originally posted by @marcelo-amorim-mobrj in https://github.com/microsoft/vscode/issues/185212#issuecomment-1608160243_

**Comment by TylerLeonhardt** [comment]
Can you follow these steps so that we can get more information on what's going on?

* Open the Command Palette
* Run the `Developer: Set Log Level...` command
* To the right of `Trace`, click the double check mark button. ✔️ ✔️ (enables trace logging as the default)
* _Start the login, wait for the issue to happen..._
* Open the Output pane (cmd+shift+u)
* drop in this issue he contents of the following:
  * `GitHub Authentication` Output channel
  * `Log (Settings Sync)` Output channel
  * `Log (Main)` Output channel
* Open the Command Palette
* Run the `Developer: Set Log Level...` command
* To the right of `Info`, click the double check mark button. ✔️ ✔️ (to set the default back to info)

**Comment by Leask** [comment]
same here

**Comment by TylerLeonhardt** [comment]
@Leask can you follow the steps?

**Comment by TylerLeonhardt** [comment]
You know what, this is likely fixed in this ^^ PR. Let's see what tomorrow's Insider build has

**Comment by Leask** [comment]
> You know what, this is likely fixed in this ^^ PR. Let's see what tomorrow's Insider build has

Cool! Thanks! Waiting for the next version. 🍻

**Comment by marcelo-amorim-mobrj** [comment]
@TylerLeonhardt I will try with the updated version and return here.

**Comment by Leask** [comment]
Confirm the latest version released today fixed everything! 🍻

**Comment by marcelo-amorim-mobrj** [comment]
Problem solved!!!
Thank you guys.
