### ISSUE TITLE
Not able to sign in with microsoft account after sign in with github

### ISSUE THREAD

**Issue by johste93** [microsoft/vscode#186224]
Type: <b>Bug</b>

After accidently signin in with a github account I'm no longer able to sign in with my microsoft account where are all my settings are synced.

Reproduction steps:
1. Fresh install
2. Click Profile icon in bottom left corner
3. Sign in to sync settings
4. Select Github
5. Complete sign in
6. Click profile icon
7. Select Github account
8. Select Sign Out
9. Click profile button
10. Tap Sign in to sync settings (1)
11. See that Browser opens and automatically signs you in with github. No option to select a different microsoft account

Expected result:
After signing out of GitHub account I should be able to select sign in with Microsoft again.

VS Code version: Code 1.79.2 (Universal) (695af097c7bd098fbf017ce3ac85e09bbc5dda06, 2023-06-14T08:58:52.392Z)
OS version: Darwin arm64 22.5.0
Modes:

Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263cf:30335440
vscoreces:30445986
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
py29gd2263:30776702
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
282f8724:30602487
pyind779:30671433
89544117:30613380
pythonsymbol12:30671437
showlangstatbar:30737416
vsctsb:30748421
pythonms35:30701012
03d35959:30757346
ecj1e332:30736112
pythonfmttext:30731395
pythoncmvfstrcf:30756944
fixshowwlkth:30771522
showindicator:30766890
pythongtdpath:30769146
e440d664:30776459
pythonidxptcf:30772540
pythondjangotscf:30772537
pythonnoceb:30776495

```

</details>

**Comment by TylerLeonhardt** [comment]
@sandy081 this seems more related to which account Settings Sync uses so I think this is you.

**Comment by lakyadam** [comment]
> @sandy081 this seems more related to which account Settings Sync uses so I think this is you.

This is a VS Code bug. It should offer the 2 types of login, microsoft account or github after you log out but it remembers what the user choose and doesn't let it change after a logging out. I managed to replicate it as well.

**Comment by sandy081** [comment]
This is expected and designed. If you want to use different account for settings sync, the recommended way is to turn off and turn on settings sync again - https://code.visualstudio.com/docs/editor/settings-sync#_switching-accounts

**Comment by johste93** [comment]
> This is expected and designed. If you want to use different account for settings sync, the recommended way is to turn off and turn on settings sync again - https://code.visualstudio.com/docs/editor/settings-sync#_switching-accounts

I see. Thats super unintuitive imo. As a user I expect to be able to login with a different account after manually logging out.

If it cannot be changed. May I suggest adding a dialog prompt on logout asking if you wish to disable sync as well?

**Comment by sandy081** [comment]
Thanks for the feedback, we are currently exploring this user experience.

**Comment by sandy081** [comment]
/duplicate 

https://github.com/microsoft/vscode/issues/104934
