### ISSUE TITLE
Test: pasting markdown links

### ISSUE THREAD

**Issue by MeghanKulkarni** [microsoft/vscode#186236]
Refs: #179628 

- [x] macOS @isidorn
- [x] windows @Yoyokrazy
- [x] linux @ulugbekna 

Complexity: 3

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23186236%0A%0A&assignees=MeghanKulkarni)

----

Description: Links that are pasted into the Markdown editor can be automatically converted to Markdown links. This feature can be enabled and disabled by the user.

Testing: You can test the following with the setting markdown.editor.pasteUrlAsFormattedLink enabled and not enabled. Also, each step can be tested with regular links and media links.

- Highlight some text and paste a link over the text
- Paste the link without any highlighted text
- Paste a link with multiple cursors
- Paste the link over text with brackets and of multiple lines
- Other cases

Verify that all of the following steps paste markdown links in an intuitive manner.

**Comment by isidorn** [comment]
Cool feature 👏
