### ISSUE TITLE
Add a "complex command" to allow extensions to open a URL in the default web browser

### ISSUE THREAD

**Issue by DavidAnson** [Microsoft/vscode#18624]
- VSCode Version: 1.8.1
- OS Version: All

Steps to Reproduce:

1. Browse https://code.visualstudio.com/docs/extensionAPI/vscode-api-commands
2. Don't find a command to open a URL in the default web browser
3. Implement one yourself via the popular, cross-platform [opn](https://www.npmjs.com/package/opn) package
4. Get [bug report for Linux](https://github.com/DavidAnson/vscode-markdownlint/issues/4) because `vsce` doesn't preserve the `execute` bit of `xdg-open`

VS Code already implements this functionality; this issue just asks to expose it.

Note: A fix for this issue would allow you to close https://github.com/Microsoft/vscode-vsce/issues/152

**Comment by jrieken** [comment]
It is in there and call `vscode.open`

<img width="669" alt="screen shot 2017-01-17 at 10 38 47" src="https://cloud.githubusercontent.com/assets/1794099/22015155/23914842-dca1-11e6-9263-954c1f1ca053.png">

**Comment by DavidAnson** [comment]
The good news is that the `vscode.open` command appears to do exactly what I want! Thank you.

The bad news is that the documentation cited above is wrong and led me to deliberately choose *not* to use this command in the first place. The snippet above says the specified resource is opened in the *editor* instead of in the *browser* - which is where URLs appear to be opened in VS Code 1.8.1 (and what I wanted all along).
