### ISSUE TITLE
Left border in Zen mode of non-centered layout

### ISSUE THREAD

**Issue by MasterInQuestion** [microsoft/vscode#186288]
Border left too much space in Zen mode of non-centered layout with line numbers off.
![](https://github.com/microsoft/vscode/assets/81106051/a5eb1eac-d18b-426d-bd08-be58c773e3b8)

&#x2D;---

Version: 1.79.2
Commit: 695af097c7bd098fbf017ce3ac85e09bbc5dda06
User Agent: Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/115.0
Embedder: vscode.dev

**Comment by MasterInQuestion** [comment]
Another problem is the Full Screen mode made the Menu Bar unnecessarily disappear (and cannot be re-enabled [1]).

[ [1]
    Precisely, cannot be easily re-enabled:
    As "View: Toggle Menu Bar" only unconditionally toggles "window.menuBarVisibility" between "compact" and "classic". ]

**Comment by joaomoreno** [comment]
> Border left too much space in Zen mode of non-centered layout with line numbers off.

When in Zen/Centered mode, you can resize one sash by click&drag while holding <kbd>Alt</kbd>. Also, you can reset the size by double-clicking the sash.

**Comment by MasterInQuestion** [comment]
Irrelevant of described problem.

    Regardless of in centered layout or not (and actually not Zen mode specific), the left margin with line numbers off appears to be excessive.
