### ISSUE TITLE
Extensions: typing while search is running always resets progress back to 0

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#1863]
This looks very hectic imho.

**Comment by joaomoreno** [comment]
Isn't this an issue with quick open?

**Comment by bpasero** [comment]
I do not see this behavior when I type in the file search while a search is running.

**Comment by joaomoreno** [comment]
And how do you do that?

**Comment by bpasero** [comment]
@joaomoreno I think you made a change where your quick open provider has full control over the progress bar and no other provider is leveraging that. Instead they just rely on the controller to start showing progress if no results are returned for 800ms.

**Comment by joaomoreno** [comment]
Negative. I do exactly the same everyone does.

**Comment by joaomoreno** [comment]
The quick open widget simply [stops the progress bar every time the user types](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/browser/parts/quickopen/quickOpenController.ts#L566) and then restarts it.

The gallery simply has instant progress bar displayed, as opposed to the 800ms of every other handler.

But this seems like it's something I cannot control from my handler.

**Comment by bpasero** [comment]
It is a consequence of setting `instantProgress` to true when registering the handler, no other handler does that. I suggest to remove this flag and behave like all other handlers.
