### ISSUE TITLE
`git log` in bash shows error 

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#186350]
Testing #186228

1. On Ubuntu, open a bash integrated terminal
2. cd to a folder with a git repo
3. `git log`
4. `q`
5. The shell integration gutter shows an error
![image](https://github.com/microsoft/vscode/assets/38270282/a38c95ef-002d-42a7-b99a-0b2495e4f881)

**Comment by Tyriar** [comment]
Looks like git log returns an exit code of 1, so this is expected
