### ISSUE TITLE
Can't stop notebook cell execution

### ISSUE THREAD

**Issue by bamurtaugh** [microsoft/vscode#186371]
Testing #186262

- Select Pyolite kernel from Pyodide extension
- Select `Run All`
- Try `Stop Execution`, :bug: nothing happens, cell is still running
- Scroll down to the cell, select its specific stop button, :bug: cell continues running
- If I reload VS Code, the cell stops executing 

![Recording 2023-06-27 at 09 52 08](https://github.com/microsoft/vscode/assets/25310137/67a1a2cf-5193-4bba-99c1-8805b190cff9)

**Comment by roblourens** [comment]
It doesn't look like this is implemented by the Pyodide extension
