### ISSUE TITLE
Tree view actions inconsistently named

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode#186370]
Testing #186245

For the same go to file codicon action, the one on the test says 'go to file' and the one on the output says 'go to source'
<img width="421" alt="image" src="https://github.com/microsoft/vscode/assets/30305945/bb72df35-07b3-4358-90f9-fe34a188cf2f">

Similarly for the same run codicon action, the one on the test suite says 'rerun test run' and the one on the test says 'run test'
<img width="416" alt="image" src="https://github.com/microsoft/vscode/assets/30305945/08568cc1-3f9a-4d4c-8c4c-f861dd4bc769">

**Comment by connor4312** [comment]
> Similarly for the same run codicon action, the one on the test suite says 'rerun test run' and the one on the test says 'run test'

In this case it's accurate -- the former action is doing that exact same test run again, the latter is individually running that specific test case

**Comment by DonJayamanne** [comment]
@connor4312 Do i need a new insiders version of some extension.
I still see `Go to file` in the test panel and `Go to source` in the output panel

**Comment by connor4312** [comment]
I intentionally did not change that wording due to my reasoning in the earlier comment https://github.com/microsoft/vscode/issues/186370#issuecomment-1622524633
