### ISSUE TITLE
Copying vscode.dev link from notebook cell gutter, no cursor placement.

### ISSUE THREAD

**Issue by Yoyokrazy** [microsoft/vscode#186390]
Testing #186199

As title states, copying a vscode.dev link from the gutter within a cell of a notebook does not place the cursor within the cell, just selects the cell. The column and line are specified, just no cursor placement in the cell. Example link is below:

`https://insiders.vscode.dev/github/Yoyokrazy/ipynb-playground/blob/unpublished-branch/woooooo.ipynb#C5:L6`

**Comment by joyceerhl** [comment]
This is fixed now 
<img width="1200" alt="image" src="https://github.com/microsoft/vscode/assets/30305945/f382fc47-cb30-4a8b-8602-6a11614bd6d7">
