### ISSUE TITLE
Clear All should not clear interactive window markdown message

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode#186387]
Testing #186191

In an interactive window, clear all deletes the markdown cell containing the kernel connection info. I don't recall if this was always the case but given how `/clear` behaves in Copilot Chat (i.e. always inserting the welcome message) I think the interactive window should maybe also keep around the last kernel connection message (or rather the Jupyter extension should insert it after a clear has happened)

**Comment by amunger** [comment]
closing in favor of https://github.com/microsoft/vscode-jupyter/issues/14862
