### ISSUE TITLE
Test output - switching between test output and log message

### ISSUE THREAD

**Issue by lszomoru** [microsoft/vscode#186322]
Testing #186245

Added a `console.log` statement to one of the tests. The log message appears in the output and the treeview:
<img width="1224" alt="image" src="https://github.com/microsoft/vscode/assets/3372902/a1c53806-999c-4e25-94ad-261ec13ad88c">

Clicking on the `10` node in the treeview will switch to the view showing the log messages only.
Clicking on a "test node" does not switch back though. I think it would make sense for it to switch back.

**Comment by connor4312** [comment]
I initially did this, but it was kind of janky because the test run item also expands/collapses its childen, so instead I have it only being shown when clicking on the inline action -- whereas the test message never has children.

**Comment by connor4312** [comment]
I improved the display in the tree view in recent months
