### ISSUE TITLE
debug attach is not working with 64bit MinGW on Windows 10

### ISSUE THREAD

**Issue by CarstenPfeffer** [microsoft/vscode#186358]
Type: <b>Bug</b>

1. create or open a C/C++ project using MinGW
2. create debug 'attach' configuration for GDB
3. start the project executable to be debugged
4. try to start debugging
    * pickProcess is shown and allows selecting the running project executable
    * debug session fails, command line in terminal seems to be corrupted

VS Code version: Code 1.79.2 (695af097c7bd098fbf017ce3ac85e09bbc5dda06, 2023-06-14T08:57:04.379Z)
OS version: Windows_NT x64 10.0.19045
Modes:

btw: 'launch' config is working well

**Comment by roblourens** [comment]
Please file this on the C++ extension repo
