### ISSUE TITLE
Interactive window restore interaction with creation mode setting

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode#186398]
Testing #186191

1. In multiple mode, create 3 interactive windows
2. Switch to single interactive window mode in settings
3. Reload window
4. There are still 3 interactive windows 🤔

**Comment by amunger** [comment]
Those windows were created when the setting was not `single`. We can't just force close windows without throwing away data, and I don't think this scenario is worth trying to figure out how to merge them in a logical way.
