### ISSUE TITLE
Include extension description

### ISSUE THREAD

**Issue by TylerLeonhardt** [microsoft/vscode#186395]
Testing #186258

<img width="665" alt="image" src="https://github.com/microsoft/vscode/assets/2644648/b9c59817-3d3b-4b1d-901e-0af9282bac7c">

If I'm new to the VS Code ecosystem, I probably don't know what any of these are (except maybe SSH). Maybe the quick pick could have the description of the extension as either a detail or a description of the quick pick item so it's more obvious what these do.

**Comment by bhavyaus** [comment]
We added the `Learn More` info button to aide with this.  Will try to pull the descriptions from the extensions to better the experience

**Comment by bhavyaus** [comment]
I'll wait for more user feedback before making this change. We also have the `Learn More` info button which helps.
