### ISSUE TITLE
Can't focus the diff in inline chat with accessibility mode on

### ISSUE THREAD

**Issue by ulugbekna** [microsoft/vscode#186309]
- Can't focus the diff with mouse 

https://github.com/microsoft/vscode/assets/16353531/ac2b35a1-8d53-4020-b197-852d71e64b3d

- Can't tab into the diff, focus is stuck on the send button (paper plane)

https://github.com/microsoft/vscode/assets/16353531/8292bf27-f7c1-4d16-9505-59a1de38dd95

**Comment by jrieken** [comment]
this is a regression from https://github.com/microsoft/vscode/pull/185219

**Comment by ulugbekna** [comment]
Focusing with a mouse works, but still can't tab into diff 

  

https://github.com/microsoft/vscode/assets/16353531/3f41a0ec-c6ce-4316-a6ed-8df27f7471ab

**Comment by jrieken** [comment]
Works for me. @ulugbekna please add steps or try w/o extensions

https://github.com/microsoft/vscode/assets/1794099/54992b54-a459-49fc-97d1-84d7216f21ce

**Comment by ulugbekna** [comment]
@jrieken you're right, that was caused by an extension, but it also seems incorrect that `editorFocus` ctx key is true when the focus is on the send button, wdyt?

https://github.com/microsoft/vscode/assets/16353531/72a2b135-0111-438a-8c5e-4439b4034482

**Comment by jrieken** [comment]
The `editorFocus` comes from the outer editor, its `editorTextFocus` context key says `false` (since it has no blinking cursor)
