### ISSUE TITLE
[Bug] Diff is out of view 

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#186365]
Testing #186146

I am not sure if this is expected/ as designed

https://github.com/microsoft/vscode/assets/29464607/4194135e-1261-47d2-ae10-32b7d18f4d7c

**Comment by meganrogge** [comment]
Actually, seems to be as designed - I have screen reader mode on so we use `preview` mode and:

Select the setting preview, verify that the inline chat appears at the end of the selection. Verify that the inline chat does not change position, independent of whether messages or text edits are generated.

**Comment by meganrogge** [comment]
I wonder if it should be within view though 🤔

**Comment by aiday-mar** [comment]
I'll look into the possibility of scrolling the inline chat into the view so that we can maximally see it

**Comment by aiday-mar** [comment]
Recently inline chat has been modified in order to make the widget always appear at the top of the selection so that it does not move as code is generated. This should no longer be an issue.
