### ISSUE TITLE
CharService#onWillSaveState says persisting when chat hasn't been used

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#186340]
Repro:

1. Run OSS
2. Enable trace logs
3. Unfocus window

![image](https://github.com/microsoft/vscode/assets/2193314/cd944d50-f72f-4456-bd9e-d66a7255ce48)

I don't have copilot installs in OSS so I wouldn't expect anything to happen here. Not sure what the 2 chars are.

**Comment by roblourens** [comment]
Probably `[]` 😁
