### ISSUE TITLE
[Bug] Hovers Should Have A Minimum Width / Height

### ISSUE THREAD

**Issue by hediet** [microsoft/vscode#186314]
Testing #185751

![Code_-_Insiders_fNyudoOGS4](https://github.com/microsoft/vscode/assets/2931520/81a410d0-0c3e-4360-9240-f54388cf18ef)

**Comment by hediet** [comment]
I think the minimum size should me much bigger:
![Code_-_Insiders_v7ArVzokzF](https://github.com/microsoft/vscode/assets/2931520/70925111-ce7a-4a48-b5aa-d14975000851)

**Comment by aiday-mar** [comment]
Currently the minimum height is the line height plus 8 pixels, and the minimum width is 4/3 times the minimum height. Do you think the minimum width should be larger?

**Comment by hediet** [comment]
> Do you think the minimum width should be larger?

I think a min width of 150px could work

**Comment by aiday-mar** [comment]
To verify:

1. Open a hover and make sure that the hover can be sized down to a minimum width of 150px provided that the hover width is naturally above 150px
2. Open a small hover with a natural width smaller than 150px, verify it can not be sized down to a smaller width than its initial width
