### ISSUE TITLE
"Ignore Whitespace Differences" button has no effect when viewing .py files

### ISSUE THREAD

**Issue by r3m0t** [microsoft/vscode#186384]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 
- OS Version: Version: 1.80.0-insider (user setup)
Commit: da7f05a70eb760e4ce1fe230ae158ae214433341
Date: 2023-06-27T15:13:35.848Z
Electron: 22.3.14
ElectronBuildId: 21893604
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Windows_NT x64 10.0.19045

Steps to Reproduce:

Write a Python file and commit it using git.

Put a few lines in a try-catch block and open Source Control.

Left click the file in the "Changes" panel. It shows a diff viewer with a change.

This opens a diff view with a "Ignore Whitespace Differences" button labelled ⁋ that has no effect (other than changing color when I click on it)

**Comment by hediet** [comment]
Thanks for reporting this! Can you please share the original and modified files? Thanks!

**Comment by r3m0t** [comment]
![image](https://github.com/microsoft/vscode/assets/1485998/732e78a6-ecdb-4da9-b239-87f5c417013d)

After clicking "Ignore Whitespace Differences" at the top right:

![image](https://github.com/microsoft/vscode/assets/1485998/e1a15c3c-b1cc-4f06-bbdc-99b0c99f415b)

Please rename these to .py
[eg1.txt](https://github.com/microsoft/vscode/files/11916478/eg1.txt)
[eg2.txt](https://github.com/microsoft/vscode/files/11916481/eg2.txt)

**Comment by r3m0t** [comment]
And what it should look like with whitespace ignored:

![image](https://github.com/microsoft/vscode/assets/1485998/6aa05b87-0fb9-4e7a-a58b-85cf216dd60a)

**Comment by hediet** [comment]
[This will work with the advanced diff algorithm](https://microsoft.github.io/monaco-editor/playground.html?source=v0.40.0-dev.20230629#XQAAAAJLBgAAAAAAAABBqQkHQ5NjdMjwa-jY7SIQ9S7DNlzs5W-mwj0fe1ZCDRFc9ws9XQE0SJE1jc2VKxhaLFIw9vEWSxW3yscw_OaBRgmSatbNyrNa50VLHWwDOn0YI7IfU0xJ0CGYU1vRtgnKPmZzQcQ1KconWO2GUmd66cKnicDABstGVU7bAJ7iXJ5axD-MovUvUeGCJ-vKgRcuNBYplL9MQaxzNUc4zTccWW5zF_73ov3x96ZpOsMxcIlGWa0qcJ13GijFLX7oehH1458VKcGShwG0hjp3j0WK1OyLI4QrC0fOHQ0ghNFmnyzokSG2CTo0i0UsmlBnY76ZG2BlOqWyUQ8ajdKK1i75ba8TOs5cOFKVWduFpqIdNYJ4RxoauwsrbcLWWWyfnj-4pFyoYEb2pJDYLwF07IYtGqvcX-RGkaUrFPhuqt3o-7nPEzvaj9wkuyIp6r8C4CJ478sprpPWQ7YzABfEL_c2rbEZ3zuMOx0Yq_X5hnj9LbS5mJ9ydpOC2tCF0AF848zOiBEcXWB-er9PaB-DVOU7W4xbZ6wCxeLwtFVvo8XUnYjHe5NBH7ZMITJdpizBXjktWGJ4f5B34ate6SGcL8Nr_ODNPg).

[With ignore whitespace differences](https://microsoft.github.io/monaco-editor/playground.html?source=v0.40.0-dev.20230629#XQAAAAJKBgAAAAAAAABBqQkHQ5NjdMjwa-jY7SIQ9S7DNlzs5W-mwj0fe1ZCDRFc9ws9XQE0SJE1jc2VKxhaLFIw9vEWSxW3yscw_ODCRgmSatbNyrNa50VLHWwDOn0YI7IfU0xJ0CGYU1vRtgnKPmZzQcQ1L9J7fCG48SpY2EIkpDE0S8hEos9zUvPWHJukWEzd75AcYmdBg8pRC7arXQqF3-aK5zCyC_O_K5tqxDyw_F4EjsGJ-ZDn9ZGdcU568RzQLEplb67JOpSNiOITw8GJxh0kXlyRBDmlybv2k_o2DLxTLHVjuwtZCxXZlZOZBduyvXvmRFOKAvJltLd5OIQ13Ei0HscanfnXUGveV9xwt8T1W0kNGyLehOpZ3RwWD33SeQ_nysuBrGd3Ay5C-gzLZEIEv6iZ9RrVIdflxSxjpmQqv15bkoORxe2C3uieQdF4HOpeWvG7_msNluYMTfEHWhJXlwICovlLZ8LG0LvUcG-JWpXwnCg8vzITjen0LT5fkBGlumR2Sa3rb75XGrFEQ6X_5HNW3ZnkD_c_Lk5VeVsIxAwahw7Inu-A-5A9PFYhwC19QOAD3AEkGp9Pxlo6lxL79Lsg2_-V3OPb)
