### ISSUE TITLE
Quick open wizards should use custom hover for tooltips

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#186347]
Testing https://github.com/microsoft/vscode-jupyter/issues/13765

Format of keybindings is particularly ugly

![image](https://github.com/microsoft/vscode-jupyter/assets/2193314/b3c29509-20af-4c06-a3f5-340a70025fd0)
![image](https://github.com/microsoft/vscode-jupyter/assets/2193314/9514da52-6f2e-4697-8898-e3e023f366be)

**Comment by weartist** [comment]
Does this question accept PR from outsiders?

**Comment by TylerLeonhardt** [comment]
@weartist yes. VS Code does accept PRs!

**Comment by weartist** [comment]
> @weartist yes. VS Code does accept PRs!

Thanks!,  and I'm going to refer to styles for other widgets, or if we already have styles we like?

**Comment by TylerLeonhardt** [comment]
It's more complicated than just styles, sadly. We need to use our rich hovers instead of the native hovers... thankfully we did some work recently to plumb a [hoverDelegate](https://github.com/microsoft/vscode/blob/5f547ba513be0ffe70537e37dda48a52d60eb93a/src/vs/workbench/services/quickinput/browser/quickInputService.ts#L44-L85) all the way down to the QuickPick. To fix the title bar buttons, you can probably add the hover delegate in `this.options` into the options of these `ActionBar`s:
https://github.com/microsoft/vscode/blob/5f547ba513be0ffe70537e37dda48a52d60eb93a/src/vs/platform/quickinput/browser/quickInput.ts#L1322-L1328

The list will be harder has the buttons get created here:
https://github.com/microsoft/vscode/blob/5f547ba513be0ffe70537e37dda48a52d60eb93a/src/vs/platform/quickinput/browser/quickInputList.ts#L285

but we can be iterative here and focus on the title bar buttons first.

the _other_ issue that has to be addressed is that Monaco: https://microsoft.github.io/monaco-editor/ currently doesn't have a HoverDelegate implementation here:
https://github.com/microsoft/vscode/blob/5f547ba513be0ffe70537e37dda48a52d60eb93a/src/vs/editor/standalone/browser/quickInput/standaloneQuickInputService.ts#L54

so either we need to implement a HoverDelegate in the "standalone" code (aka Monaco) or we need to pass in the right value to tell quick pick to not use a hover delegate and use native hovers instead. So yeah... it's a bit more complicated than styles unfortunately 😅

**Comment by weartist** [comment]
> It's more complicated than just styles, sadly. We need to use our rich hovers instead of the native hovers... thankfully we did some work recently to plumb a [hoverDelegate](https://github.com/microsoft/vscode/blob/5f547ba513be0ffe70537e37dda48a52d60eb93a/src/vs/workbench/services/quickinput/browser/quickInputService.ts#L44-L85) all the way down to the QuickPick. To fix the title bar buttons, you can probably add the hover delegate in `this.options` into the options of these `ActionBar`s:可悲的是，它比样式更复杂。我们需要使用我们丰富的悬停而不是原生悬停......值得庆幸的是，我们最近做了一些工作，将悬停委托一直探测到快速选择。要修复标题栏按钮，您可以将悬停委托添加到以下 `ActionBar` 选项 `this.options` 中：
> 
> https://github.com/microsoft/vscode/blob/5f547ba513be0ffe70537e37dda48a52d60eb93a/src/vs/platform/quickinput/browser/quickInput.ts#L1322-L1328
> 
> The list will be harder has the buttons get created here:如果在此处创建按钮，列表将更难：
> 
> https://github.com/microsoft/vscode/blob/5f547ba513be0ffe70537e37dda48a52d60eb93a/src/vs/platform/quickinput/browser/quickInputList.ts#L285
> 
> but we can be iterative here and focus on the title bar buttons first.但是我们可以在这里迭代，并首先关注标题栏按钮。
> 
> the _other_ issue that has to be addressed is that Monaco: https://microsoft.github.io/monaco-editor/ currently doesn't have a HoverDelegate implementation here:另一个必须解决的问题是Monaco： https://microsoft.github.io/monaco-editor/ 目前这里没有HoverDelegate实现：
> 
> https://github.com/microsoft/vscode/blob/5f547ba513be0ffe70537e37dda48a52d60eb93a/src/vs/editor/standalone/browser/quickInput/standaloneQuickInputService.ts#L54
> 
> so either we need to implement a HoverDelegate in the "standalone" code (aka Monaco) or we need to pass in the right value to tell quick pick to not use a hover delegate and use native hovers instead. So yeah... it's a bit more complicated than styles unfortunately 😅因此，要么我们需要在“独立”代码（又名 Monaco）中实现 HoverDelegate，要么我们需要传入正确的值来告诉 Quick Pick 不使用悬停委托而改用本机悬停。所以是的...不幸的是 😅 ，它比样式复杂一些



> It's more complicated than just styles, sadly. We need to use our rich hovers instead of the native hovers... thankfully we did some work recently to plumb a [hoverDelegate](https://github.com/microsoft/vscode/blob/5f547ba513be0ffe70537e37dda48a52d60eb93a/src/vs/workbench/services/quickinput/browser/quickInputService.ts#L44-L85) all the way down to the QuickPick. To fix the title bar buttons, you can probably add the hover delegate in `this.options` into the options of these `ActionBar`s:
> 
> https://github.com/microsoft/vscode/blob/5f547ba513be0ffe70537e37dda48a52d60eb93a/src/vs/platform/quickinput/browser/quickInput.ts#L1322-L1328
> 
> The list will be harder has the buttons get created here:
> 
> https://github.com/microsoft/vscode/blob/5f547ba513be0ffe70537e37dda48a52d60eb93a/src/vs/platform/quickinput/browser/quickInputList.ts#L285
> 
> but we can be iterative here and focus on the title bar buttons first.
> 
> the _other_ issue that has to be addressed is that Monaco: https://microsoft.github.io/monaco-editor/ currently doesn't have a HoverDelegate implementation here:
> 
> https://github.com/microsoft/vscode/blob/5f547ba513be0ffe70537e37dda48a52d60eb93a/src/vs/editor/standalone/browser/quickInput/standaloneQuickInputService.ts#L54
> 
> so either we need to implement a HoverDelegate in the "standalone" code (aka Monaco) or we need to pass in the right value to tell quick pick to not use a hover delegate and use native hovers instead. So yeah... it's a bit more complicated than styles unfortunately 😅

Sorry to reply late, thank you for your help! I will start learning the relevant code here over the weekend, hope it goes well!

**Comment by weartist** [comment]
@TylerLeonhardt It is very convenient to create rich hover based on the clues you provide!(Please ignore his style and content) I'm using method `setupCustomHover` for the time being to set the style:
https://github.com/microsoft/vscode/blob/1606401f5b761397488f53b75130809fba073194/src/vs/base/browser/ui/iconLabel/iconLabelHover.ts#L161
I would like to ask for help, is it the right choice to use this method? If yes, I will continue to improve
ps:For Monaco, I haven't started looking at the relevant code, but I will as soon as possible




![image](https://github.com/microsoft/vscode/assets/17105034/671c2889-317c-4b40-a3b0-67daadadbe16)

**Comment by TylerLeonhardt** [comment]
On the VS Code (non-Monaco side) we already pass a hover delegate in here:
https://github.com/microsoft/vscode/blob/98d1724530cf307f8dcc49370d2e2d216cab9e55/src/vs/workbench/services/quickinput/browser/quickInputService.ts#L22

So you should be able to just reuse that instead of `setupCustomHover`

**Comment by weartist** [comment]
@TylerLeonhardt I adapted the title bar, but the buttons in the menu options cannot be easily adapted because they are not available e.g. 'Learn More' in screenshot, next I'm going to learn monaco-related code, For Monaco's tabbar, do you know which pages can be easily called show?

**Comment by TylerLeonhardt** [comment]
@weartist we can start with just fixing the title bar buttons if you'd like and then fix the Learn More ones later. We can be iterative :)

We still for sure need this before that PR of yours comes in:

> the _other_ issue that has to be addressed is that Monaco: https://microsoft.github.io/monaco-editor/ currently doesn't have a HoverDelegate implementation here:
> https://github.com/microsoft/vscode/blob/5f547ba513be0ffe70537e37dda48a52d60eb93a/src/vs/editor/standalone/browser/quickInput/standaloneQuickInputService.ts#L54
> 
> so either we need to implement a HoverDelegate in the "standalone" code (aka Monaco) or we need to pass in the right value to tell quick pick to not use a hover delegate and use native hovers instead. So yeah... it's a bit more complicated than styles unfortunately 😅 

from https://github.com/microsoft/vscode/issues/186347#issuecomment-1660833587

**Comment by weartist** [comment]
> @weartist we can start with just fixing the title bar buttons if you'd like and then fix the Learn More ones later. We can be iterative :)
> 
> We still for sure need this before that PR of yours comes in:
> 
> > the _other_ issue that has to be addressed is that Monaco: https://microsoft.github.io/monaco-editor/ currently doesn't have a HoverDelegate implementation here:
> > https://github.com/microsoft/vscode/blob/5f547ba513be0ffe70537e37dda48a52d60eb93a/src/vs/editor/standalone/browser/quickInput/standaloneQuickInputService.ts#L54
> > 
> > so either we need to implement a HoverDelegate in the "standalone" code (aka Monaco) or we need to pass in the right value to tell quick pick to not use a hover delegate and use native hovers instead. So yeah... it's a bit more complicated than styles unfortunately 😅
> 
> from [#186347 (comment)](https://github.com/microsoft/vscode/issues/186347#issuecomment-1660833587)

Thanks for your help, I'll go investigate the monaco related code, but it may be later, I'm also stuck with this issue 🤣:https://github.com/tree-sitter/tree-sitter/issues/2338

**Comment by weartist** [comment]
> > I'm also stuck with this issue 🤣:[tree-sitter/tree-sitter#2338](https://github.com/tree-sitter/tree-sitter/issues/2338)
> 
> If you use Node 18, you shouldn't see that issue.

It works for me, I would also like to ask for a simple question: In addition to calling api, is there any scenario in vscode that directly runs monaco? I'm trying to find a link to a monaco input call, but failing

**Comment by TylerLeonhardt** [comment]
Good question. Here are the steps for running Monaco:
https://github.com/microsoft/monaco-editor/blob/main/CONTRIBUTING.md#debugging--developing-the-core-editor

What I would recommend is maybe temporarily adding a button to an existing quick pick like the command palette:
https://github.com/microsoft/vscode/blob/67ea2e95eb3f17ac07e4f759e51bce76da9697dc/src/vs/platform/quickinput/browser/pickerQuickAccess.ts#L117

add a line like:
```
                 picker.buttons = [backButton];
```
and don't forget to import it:
```
import { backButton } from 'vs/platform/quickinput/browser/quickInput';
```

**Comment by weartist** [comment]
> Good question. Here are the steps for running Monaco: https://github.com/microsoft/monaco-editor/blob/main/CONTRIBUTING.md#debugging--developing-the-core-editor
> 
> What I would recommend is maybe temporarily adding a button to an existing quick pick like the command palette:
> 
> https://github.com/microsoft/vscode/blob/67ea2e95eb3f17ac07e4f759e51bce76da9697dc/src/vs/platform/quickinput/browser/pickerQuickAccess.ts#L117
> 
> add a line like:
> 
> ```
>                  picker.buttons = [backButton];
> ```
> 
> and don't forget to import it:
> 
> ```
> import { backButton } from 'vs/platform/quickinput/browser/quickInput';
> ```

Thank you for your patience! I will start learning the code

**Comment by weartist** [comment]
@TylerLeonhardt I investigated the existing code and found some problem if I wanted to implement a HoverDelegate in the "standalone" code: 
We need to use `hover` related code, but they are in the `vs/workbench`, and `editor/standalone` should not be import this layer, do we need to re-implement a standalone with hover?  or lower the `hover` code hierarchy to the `platfom` level, I'm not sure if the conclusion I got is correct, so I still need to ask you for help, thanks!

**Comment by TylerLeonhardt** [comment]
@weartist so considering there's no implementation of the `HoverService` on the Standalone side, you can, for now, use a native hover by using this function:
https://github.com/microsoft/vscode/blob/ecb0c80fc1da718cabb863409897d941bf18aa49/src/vs/base/browser/ui/iconLabel/iconLabelHover.ts#L22-L31

(`vs/base` is allowed in standalone)

so you will need to create a `HoverDelegate` (like how we [do so for the workbench side](https://github.com/microsoft/vscode/blob/ecb0c80fc1da718cabb863409897d941bf18aa49/src/vs/workbench/services/quickinput/browser/quickInputService.ts#L53-L82)) that uses the native hover.

**Comment by TylerLeonhardt** [comment]
@weartist so before, I provided a default implementation of the `HoverDelegate` here:
https://github.com/microsoft/vscode/blob/ecb0c80fc1da718cabb863409897d941bf18aa49/src/vs/platform/quickinput/browser/quickInputService.ts#L89-L94

I think what we _should_ do is remove that and allow `hoverDelegate` to be `undefined`/optional. If it's `undefined` don't pass it in to the `ActionBar`s so that the native hover is used.

**Comment by weartist** [comment]
> @weartist so before, I provided a default implementation of the `HoverDelegate` here that does nothing:
> 
> https://github.com/microsoft/vscode/blob/ecb0c80fc1da718cabb863409897d941bf18aa49/src/vs/platform/quickinput/browser/quickInputService.ts#L89-L94
> 
> I think what we _should_ do is remove that and allow `hoverDelegate` to be `undefined`/optional. If it's `undefined` don't pass it in to the `ActionBar`s so that the native hover is used as fallback.

It's better to handle it this way, otherwise it's really difficult to achieve the current situation (especially for me🤣)

**Comment by weartist** [comment]
@TylerLeonhardt  I submitted an initial PR, but I'm not sure if I missed some details, and found that one of the tests timed out

**Comment by TylerLeonhardt** [comment]
Verification on macOS:
* Open up a few pickers
* Hover over different components:
  * description
  * detail
  * quick pick buttons
  * quick pick item buttons
  
None of them should be using native hovers. They should all be using custom hovers.

**Comment by weartist** [comment]
> Verification on macOS would be easiest I think:
> 
> * Open up a few pickers
> * Hover over different components:
>   
>   * description
>   * detail
>   * quick pick buttons
>   * quick pick item buttons
> 
> None of them should be using native hovers. They should all be using custom hovers.

Is there anything I can do to help? Do we need to replace everything that needs to be replaced with a custom hover,I'm willing to submit a PR to modify these if I can

**Comment by TylerLeonhardt** [comment]
It's already done! Now we verify everything is working as expected before [we release](https://github.com/microsoft/vscode/wiki/Development-Process#end-game) :)

**Comment by andreamah** [comment]
Are these the old tooltips or the new ones? 
<img width="275" alt="image" src="https://github.com/microsoft/vscode/assets/31675041/8be4d37b-7ce5-402c-81a3-238e17c308e4">

<img width="306" alt="image" src="https://github.com/microsoft/vscode/assets/31675041/0aa28729-1dd0-4476-bdcb-c36de451e43a">

This is what I'm seeing.

**Comment by TylerLeonhardt** [comment]
Yes those look like custom

**Comment by TylerLeonhardt** [comment]
Actually, the keybinding one isn't... let me capture this in another issue as the `KeybindingLabel` class doesn't actually support a hover delegate.
