### ISSUE TITLE
Revert arrows reverting the wrong chunk

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#186396]
Testing #186213

![Recording 2023-06-27 at 10 53 12](https://github.com/microsoft/vscode/assets/323878/16ffe725-84d1-474c-903c-5e5a30527198)

**Comment by hediet** [comment]
Thanks for reporting! Please share the input files the next time ;)

Original:
```
a
b
c
d
e
f
g
```

Modified:
```
a
c
d
e
f
```
