### ISSUE TITLE
Conflict  with Visual studio code and Android studio

### ISSUE THREAD

**Issue by upruslanko** [microsoft/vscode#186304]
Type: <b>Bug</b>

After Java analysis, I have an issue with Gradle. I tried updating the version of Gradle to 7.6.1 but am still getting errors. 
Flutter doctor show no issue. 
Could not run phased build action using connection to Gradle distribution 'https://services.gradle.org/distributions/gradle-7.6.1-all.zip'.
Execution failed for task ':app:compileDebugKotlin'.
A failure occurred while executing org.jetbrains.kotlin.compilerRunner.GradleCompilerRunnerWithWorkers$GradleKotlinCompilerWorkAction
Compilation error. See log for more details

VS Code version: Code - Insiders 1.80.0-insider (45b31e9a872da8cc3cc8fff41c1eeb2063be04b7, 2023-06-27T05:35:02.267Z)
OS version: Darwin x64 22.5.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|4, 4, 5|
|Memory (System)|16.00GB (1.35GB free)|
|Process Argv|--crash-reporter-id 555706e0-c23a-444d-8963-24ef17641f5b|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (82)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|3.0.2
vscode-flutter-helper|aks|0.2.5
flutter-snippets|ale|3.0.0
vscode-comment-autocomplete|axe|0.4.2
ccs-flutter-color|cir|1.0.2
dart-code|Dar|3.66.0
flutter|Dar|3.66.0
vscode-markdownlint|Dav|0.51.0
vscode-faker|dee|2.0.0
emulate|Die|1.6.0
vscode-new-file|dku|4.0.2
python-environment-manager|don|1.0.4
xml|Dot|2.5.1
gitlens|eam|14.0.1
vscode-html-css|ecm|1.13.1
RunOnSave|eme|0.2.0
json-tools|eri|1.0.2
explaindev|exp|1.0.17
auto-rename-tag|for|0.1.10
rp-consumer|Gag|0.2.1
vscode-yarn|gam|2.1.0
copilot|Git|1.93.189
vscode-github-actions|git|0.25.8
gitlab-workflow|Git|3.68.0
live-sass|gle|6.0.5
go|gol|0.39.0
vscode-flutter-files|gor|4.7.1
gc-excelviewer|Gra|4.2.57
rest-client|hum|0.25.1
dart-data-class-generator|hzg|0.5.4
pubspec-assist|jer|2.3.2
firebase-explorer|jsa|0.3.3
unity-code-snippets|kle|1.3.0
flutter-tree|mar|1.0.0
flutter-snippets|Mar|1.0.5
fluent-icons|mig|0.0.18
vscode-language-pack-ru|MS-|1.80.2023062109
csharp|ms-|1.26.0
vscode-dotnet-runtime|ms-|1.6.0
autopep8|ms-|2023.5.11721010
isort|ms-|2023.9.11721010
pylint|ms-|2023.5.11721009
python|ms-|2023.11.11771009
vscode-pylance|ms-|2023.6.31
cpptools|ms-|1.16.3
vsliveshare|ms-|1.0.5873
gradle-language|nac|0.2.3
awesome-flutter-snippets|Nas|4.0.1
vetur|oct|0.37.3
indent-rainbow|ode|8.3.1
dart-syntax-highlighting-only|osc|1.0.1
dartgettersetter|Pet|1.0.2
vscode-versionlens|pfl|1.5.0
nested-comments|phi|4.0.0
remove-comments|pli|1.2.2
riverpodsnippets|Pyt|0.0.3
vscode-thunder-client|ran|2.7.7
java|red|1.19.0
vscode-xml|red|0.25.2023062304
vscode-yaml|red|1.13.0
vscode-gradle-extension-pack|ric|0.0.4
LiveServer|rit|5.7.9
flutter-riverpod-snippets|rob|1.2.2
flutter-dart-utils|Rod|1.2.0
trailing-spaces|sha|0.4.1
svg-preview|Sim|2.8.3
pip-manager|sli|1.1.3
iconfont-preview|stx|0.0.5
unity-tools|Tob|1.2.12
vscode-counter|uct|3.2.1
errorlens|use|3.11.1
vscode-autohotkey-vj|vin|3.0.1
intellicode-api-usage-examples|Vis|0.2.7
vscodeintellicode|Vis|1.2.30
vscode-gradle|vsc|3.12.7
vscode-java-debug|vsc|0.51.0
vscode-java-dependency|vsc|0.23.0
vscode-java-pack|vsc|0.25.11
vscode-java-test|vsc|0.39.0
vscode-maven|vsc|0.41.0
volar|Vue|1.8.2
vscode-wakatime|Wak|24.0.14

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vslsvsres303:30308271
pythontb:30258533
pythonptprofiler:30281269
vshan820:30294714
vscod805cf:30301675
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30404738
py29gd2263:30776702
vsclangdf:30492506
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30618038
pylantcb52:30590116
pyind779:30611226
pythonsymbol12:30651887
showlangstatbar:30737417
pythonms35:30671666
03d35959:30757351
57b77579:30687741
pythonfmttext:30716741
pythoncmvfstr:30726892
fixshowwlkth:30771523
showindicator:30766888
pythongtdpath:30726887
gsof1:30771514
dh2dc718:30776458
pythonnosmt12:30773574
pythonidxpt:30768918
pythondjangots:30768917
pythonnoceb:30776497
copilotsettingc:30767685
e537b577:30772214
asynctok:30776451

```

</details>

**Comment by meganrogge** [comment]
It looks like your report is missing some important information
/label info-needed

**Comment by meganrogge** [comment]
pls create an issue for that extension
