### ISSUE TITLE
Incorrect C# comment syntax-highlighting

### ISSUE THREAD

**Issue by BBosman** [Microsoft/vscode#18633]
- VSCode Version: 1.8.1
- OS Version: macOS Sierra 10.12.2

Steps to Reproduce:

1. Create the following C# code:
``` cs
namespace MyTest
{
    public interface ITest
    {
        // Random comment 1
        int Test1 { get; set; }

        int Test2 { get; set; } // Random comment 2


        int Test3 { get; set; }
        // Random comment 3
    }
}
```
2. See the screenshot below. I would expect `// Random comment 2` to be coloured green, similar to comments 1 and 3.
<img width="487" alt="comments" src="https://cloud.githubusercontent.com/assets/5115488/22010477/b8e59a64-dc89-11e6-8b52-10fa7923b883.png">

**Comment by dbaeumer** [comment]
@aeschli not sure if this is us or OmniSharp.

**Comment by aeschli** [comment]
This issue was moved to OmniSharp/omnisharp-vscode#1134
