### ISSUE TITLE
Continue in vscode.dev should work even with no file open

### ISSUE THREAD

**Issue by TylerLeonhardt** [microsoft/vscode#186392]
Testing #186258

Steps:
* disable Remote Repos, GitHub Repos, Azure Repos.
* Then I `Connect to...`
* Continue Working in vscode.dev shows up so I picked it
* nothing happens

This might be https://github.com/microsoft/vscode/issues/186388 but I see the same behavior when I disable Codespaces so it might be a different issue.

**Comment by joyceerhl** [comment]
Ooh I just reproed this in OSS, log says

```
TypeError: Cannot read properties of undefined (reading 'selectedStep')
```
