### ISSUE TITLE
keychain issue with awesomewm

### ISSUE THREAD

**Issue by EmilienM** [microsoft/vscode#186341]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: code-insiders-1.80.0-1687758724.el7.x86_64
- OS Version: Fedora 38

Steps to Reproduce:

1. Don't use Gnome, but use [AwesomeWM](https://awesomewm.org/).
2. Run VS Code with Github extensions (e.g. Copilot)
3. It can't find the secrets in password storage (it used to work in a previous version)
4. Impossible to login even after entering the credentials

Logs are provided: https://gitlab.com/-/snippets/2562861/raw/main/code.log

**Comment by TylerLeonhardt** [comment]
@EmilienM a few days ago we improved the flow by including a dialog that either:
* takes you to this doc: https://github.com/microsoft/vscode-docs/blob/vnext/docs/editor/settings-sync.md#other-linux-desktop-environments
* allows you to opt in to a weaker encryption

Can you grab the latest insiders and see if that dialog pops?

**Comment by EmilienM** [comment]
> @EmilienM a few days ago we improved the flow by including a dialog that either:
> 
>     * takes you to this doc: https://github.com/microsoft/vscode-docs/blob/vnext/docs/editor/settings-sync.md#other-linux-desktop-environments
> 
>     * allows you to opt in to a weaker encryption
> 
> 
> Can you grab the latest insiders and see if that dialog pops?

Hey @TylerLeonhardt - thanks for your prompt answer.
I know this is not helpful but I re-installed my environment with Gnome as I had too many other issues without Wayland, so I won't be able to keep testing this scenario.
Note that I also tried the weaker encryption and it didn't work for me.

At least this issue can be used for someone looking for the same kind of error.

Thanks for your support!

**Comment by TylerLeonhardt** [comment]
Ok. I'll go ahead and close this since we don't have the environment anymore but if anyone lurking _does_ run into this feel free to get a new issue going and we can debug together!
