### ISSUE TITLE
Reconnected default build task not used

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode#186373]
1. Have default build task already running
2. Reload window, reconnected to existing default build task
3. Ctrl+Shift+B
4. :bug: new set of default build tasks starts running (this is in the VS Code repo)

![image](https://github.com/microsoft/vscode/assets/30305945/1cc3e5be-cbe0-4a28-9e38-adf783aee0c2)

**Comment by meganrogge** [comment]
@joyceerhl are you reproducing one set of inactive terminals associated with a task that's no longer running and one set that is running?

or are both sets running now, per #188806?

I believe these are separate issues

**Comment by joyceerhl** [comment]
Oh yea, will consider this one verified and reopen the other one then

**Comment by meganrogge** [comment]
Thanks, this issue occurred because task reconnection was broken before but should now be fixed. The other one is a race condition that I'll look into in August.
