### ISSUE TITLE
interactive window on reload doesn't retain variable state

### ISSUE THREAD

**Issue by andreamah** [microsoft/vscode#186391]
Testing #186191

Not sure if this is a bug, but reloading the window with an interactive window open causes the interactive window to lose any state that was created before the reload.  My setting for `files.hotExit` is `onExit`. 

<img alt="image" src="https://github.com/microsoft/vscode/assets/31675041/efefc37a-b9ce-4ff0-a7de-37083e5f27f2">

steps:
1. make a python file that just contains `x=1` and run in an interactive window.
2. reload
3. try to run `print(x)` in the input box. Notice that `x` isn't defined.

**Comment by amunger** [comment]
this is expected, I'll try to clarify as part of https://github.com/microsoft/vscode/issues/186389
