### ISSUE TITLE
Inline output action not disposed when test changes

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode#186372]
Testing #186245

1. Add a console.log
2. Run the test
3. Take out the console.log
4. Run the test
5. :bug: inline action is still there

<img width="222" alt="image" src="https://github.com/microsoft/vscode/assets/30305945/c6c7cc21-3a17-4193-9cd7-46de0e557205">

**Comment by connor4312** [comment]
This was an opt-in setting, but it should not have been on by default
