### ISSUE TITLE
feature missing: enable/disable all extensions

### ISSUE THREAD

**Issue by guhuajun** [Microsoft/vscode#18630]
- VSCode Version: 1.8.1
- OS Version: Windows 7 SP1

Steps to Reproduce:

1. Press Ctrl + Shift + X to open Extensions.
2. Click More button, Disable/Enable All menu items are missing.

![default](https://cloud.githubusercontent.com/assets/14121694/22009857/bda8122a-dcc0-11e6-852b-21a7102238bb.png)

Here is the example image in [October Release Summary](http://code.visualstudio.com/updates/v1_7#_disable-extensions)
![default](https://cloud.githubusercontent.com/assets/14121694/22009925/14411438-dcc1-11e6-94fb-652fa66ed43a.png)

Found some discussions in https://github.com/Microsoft/vscode/issues/14288, sorry if this issue was reported before.

**Comment by sandy081** [comment]
@guhuajun These actions were moved into Command Pallette as they are not very frequent ones to use.

![image](https://cloud.githubusercontent.com/assets/10746682/22020368/2fa7b9d8-dcb8-11e6-8e12-f4e0c3c9ffda.png)

**Comment by guhuajun** [comment]
@sandy081 Thanks for updating. I wish these menu items will be added back in the future.

**Comment by sandy081** [comment]
@guhuajun Sorry, these might not be added back since they are not very common actions and hence were moved to command pallette. But, I definitely see the issue of discovering them and will try to solve it.
