### ISSUE TITLE
Accessibility Help - H opens help many times

### ISSUE THREAD

**Issue by hediet** [microsoft/vscode#186352]
Every time I try it, it opens one more time:

![Code_-_Insiders_FwfeMdljlz](https://github.com/microsoft/vscode/assets/2931520/5605a00b-4eee-4ec4-acc7-ff877260d2e4)

**Comment by rzhao271** [comment]
I can still repro the issue.
1. Open accessibility help on a code editor and press H. One dialog shows up.
2. Open accessibility help again on the same code editor and press H. :bug: Two dialogs show up.
3. Open accessibility help again on the same code editor and press H. :bug: Three dialogs show up.
