### ISSUE TITLE
Run current file in interactive window doesn't show interactive window

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode#186382]
Testing #186191

1. Run Python file in interactive window
2. Move interactive window to background (i.e. tab is visible but not active)
3. Interactive window isn't made active/visible. Not really sure what the expected behavior is here, I could see users maybe wanting to be able to send execution requests in the background, but initially I thought nothing had happened because there was no visible progress indicator

**Comment by amunger** [comment]
duplicate of https://github.com/microsoft/vscode-jupyter/issues/11138
