### ISSUE TITLE
Peek Call/Type Hierarchy not in command palette

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#186399]
Testing #186213

<img width="497" alt="image" src="https://github.com/microsoft/vscode/assets/323878/ba07c303-4a1a-460f-9da5-d582c3b43d85">

<img width="667" alt="image" src="https://github.com/microsoft/vscode/assets/323878/436aab1c-305a-4b2d-aab2-a32c9d9f6d6b">

**Comment by jrieken** [comment]
same is true for "Peek Type Hierarchy"

**Comment by 21xiaofanli** [comment]
Hi Rob and Johannes,
Would you mind if I took a crack at this issue? I am just starting open source, and I think this would be a great learning experience to do!

**Comment by weartist** [comment]
I stand in line

**Comment by jammel-yeboah** [comment]
> Hi Rob and Johannes, Would you mind if I took a crack at this issue? I am just starting open source, and I think this would be a great learning experience to do!

Hey have you started working on this issue?

**Comment by weartist** [comment]
I'll fix this

**Comment by 21xiaofanli** [comment]
Yes I have! I have already wrote code for this issue, just haven't made a pr yet :)

**Comment by 20080** [comment]
> Yes I have! I have already wrote code for this issue, just haven't made a pr yet :)

Hey @21xiaofanli can you take a little time and help me if you have resolved this issue how you did it? just a brief, also where is your pr I want to take a look at it!

**Comment by SevenOutman** [comment]
It's been quite a while that no updates about the fix is coming out, so I've committed mine in #189607.
