### ISSUE TITLE
Forever spinning `Connecting to tunnel` notification

### ISSUE THREAD

**Issue by deepak1556** [microsoft/vscode#186345]
Testing #186246

Following steps 1-4 on macOS desktop client, trying to switch folders after connecting to the tunnel shows the following loader

https://github.com/microsoft/vscode/assets/964386/9bcd4da3-2971-4bbb-ac6a-6d21805ca220

**Comment by deepak1556** [comment]
It also happens in other scenarios, when closing the remote connection and reconnecting to the tunnel

**Comment by deepak1556** [comment]
After realizing https://github.com/microsoft/vscode/issues/186246#issuecomment-1609759303, this was actually seen when tunnel was running inside WSL.

**Comment by skroth** [comment]
I have the same issue and reported it here: https://github.com/microsoft/vscode/issues/183345 not sure why it was closed :/

**Comment by benemead** [comment]
I am also encountering this - much in the same manner as @skroth reported in #183345 - posting here because that issue is locked.

**Comment by mdonato-fn** [comment]
I also see that. It kind of hid itself down in the status bar for a while, but now it is back in all its glory
