### ISSUE TITLE
Two different inserted line background colors

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#186393]
Testing #186213

<img width="333" alt="image" src="https://github.com/microsoft/vscode/assets/323878/0ca53627-729f-4521-9314-57e608e97cdf">

I peeked at the DOM and I think `var(--vscode-diffEditor-insertedTextBackground)` is doubled up with `var(--vscode-diffEditor-insertedLineBackground)` on some of these

**Comment by roblourens** [comment]
Shorter, if it helps

<img width="532" alt="image" src="https://github.com/microsoft/vscode/assets/323878/fcf013b1-9008-4751-9157-ae2e165f13ee">

**Comment by roblourens** [comment]
And on the left side
<img width="434" alt="image" src="https://github.com/microsoft/vscode/assets/323878/f9a56b9d-36b3-46c3-9fd1-88f07cb0090f">

**Comment by hediet** [comment]
I was hoping nobody would run into this and did this as a workaround to fix an ugly bug :D Guess I was wrong, I'll see what I can do.
