### ISSUE TITLE
Switching profile and remote sessions

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode#186351]
Testing #186171

1) Open a Remote-SSH workspace
2) Open a couple of editors
3) Switch to a profile that does not contain the Remote-SSH extension 
4) Now that the remote connection is broken, switch back to the original profile
-> The remote connection remains broken and I need to reload the window manually to get it reestablished. I would have expected that after step 4) I'm in a good spot.

**Comment by sandy081** [comment]
This should get fixed with https://github.com/microsoft/vscode/issues/186270. We should never disable remote extension.
