### ISSUE TITLE
Custom tree view looses focussed checkbox on toggle

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#186306]
Testing #186164

It almost looks like we do a tree refresh and then loose the focus on the checkbox:

![Recording 2023-06-27 at 11 59 28 (1)](https://github.com/microsoft/vscode/assets/900690/a2382485-cc17-4c54-b736-0a4e6294ac22)

This was tested with the extension sample of the npm explorer, so might also be related to that?

**Comment by alexr00** [comment]
Good find, that is exactly what we do.

**Comment by alexr00** [comment]
This is going to be a more involved change than we should take during endgame. I will fix after endgame.
