### ISSUE TITLE
Reload window prompts to save unsaved Interactive Window session

### ISSUE THREAD

**Issue by minsa110** [microsoft/vscode#186448]
Testing #186196

`Reload window` should not ask to save unsaved Interactive Window session.
![image](https://github.com/microsoft/vscode/assets/10833267/590b538c-254c-4d03-a931-73f05b343d9f)

Side note, this would be confusing to folks:
- Prompt here to save shows `.interactive`
- Save as shows as type `.json`
- Actually saves as `.ipynb`

**Comment by amunger** [comment]
I recall @bpasero telling me we should always backup/recover for normal reload, but maybe I'm misrembering since the backupTracker code is pretty explicit for not backing up if hotexit==off

```
if (!this.filesConfigurationService.isHotExitEnabled) {
	return []; // never backup when hot exit is disabled via settings
}
```

So this is actually consistent for all editor types, but should it be this way?

**Comment by amunger** [comment]
either way, not something that needs to be taken care of this iteration

**Comment by bpasero** [comment]
Is this with hot exit disabled? If the user disables hot exit, there are no backups (as far as I recall) and then we can only prompt. The idea of hot exit is to allow quit/close/reload without prompt. If you disable hot exit, you get prompts.
