### ISSUE TITLE
QuickAccess test failures

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode#186476]
https://dev.azure.com/monacotools/Monaco/_build/results?buildId=220787&view=logs&j=da48166e-7b5a-5795-baad-2da069a28643&t=1dcf3dc6-fe09-5df6-ee0d-57088363368d

The diffs seems to be missing from the output:
<img width="739" alt="image" src="https://github.com/microsoft/vscode/assets/9205389/5a9fb802-6ff3-4686-9acd-4f2b3c84f5c3">

**Comment by TylerLeonhardt** [comment]
Haven't seen this in a while and we don't have the outputs... so it's not very actionable. Closing.
