### ISSUE TITLE
Tabbing to "Make Request" says nothing

### ISSUE THREAD

**Issue by TylerLeonhardt** [microsoft/vscode#186446]
Testing #186218

<img width="360" alt="image" src="https://github.com/microsoft/vscode/assets/2644648/31ef954b-12df-44d2-880b-9be5deacb87a">

Tab to this button. Screen reader NVDA doesn't say anything. Possibly related to https://github.com/microsoft/vscode/issues/186444 ?

**Comment by meganrogge** [comment]
Yeah that reads it for me, so I think something is off with NVDA for you atm.

**Comment by meganrogge** [comment]
Pls reopen if you can repro when not in a VM
