### ISSUE TITLE
"Collapse unchanged regions" looks disabled

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#186403]
Testing #186213

<img width="273" alt="image" src="https://github.com/microsoft/vscode/assets/323878/0334000a-1820-4edb-9a88-435d39a95562">

Should use a toggle state instead, or a new icon. You can see it looks the same as the other disabled action

**Comment by hediet** [comment]
I agree, but then this also applies to the "toggle whitespace" button.

**Comment by jrieken** [comment]
I'd prefer to have an icon per state. That's how we have done it in other toolbars (like output scroll lock).

**Comment by hbons** [comment]
<img width="584" alt="image" src="https://github.com/microsoft/vscode/assets/103326/dfc7e85e-2e96-4f4d-88f3-9c06d720bfe7">

Mockup with a toggled state.

Having an icon per state makes sense for the lock icon, because the reverse icon metaphors make intuitive sense. This is not the case for the whitespace and fold icon here though.

cc @daviddossett

**Comment by daviddossett** [comment]
We do use toggle elsewhere. One easy example:

<img width="472" alt="CleanShot 2023-07-07 at 09 13 11@2x" src="https://github.com/microsoft/vscode/assets/25163139/f8b1c80f-d30b-4b94-801e-dbfe0dd56ec8">

**Comment by hediet** [comment]
I'm still in favor of a toggle border, but @jrieken has to agree.
Alternatively, we can explore other icons.
Or we leave it as is.

**Comment by jrieken** [comment]
No, I don't need to agree (but also not to like it). If you wanna explore https://github.com/microsoft/vscode/issues/186403#issuecomment-1621283112 or something similar go ahead but we should be aware that this is also open to extensions, so we need to deal with every (contributed) button looking like this in the future

**Comment by abhijit-chikane** [comment]
> <img alt="image" width="584" src="https://user-images.githubusercontent.com/103326/251086799-dfc7e85e-2e96-4f4d-88f3-9c06d720bfe7.png">
> Mockup with a toggled state.
> 
> Having an icon per state makes sense for the lock icon, because the reverse icon metaphors make intuitive sense. This is not the case for the whitespace and fold icon here though.
> 
> cc @daviddossett

I think this approach looks good to me
It is more aligned with the vs code current design and should be replaced the current find widget toggle ui

**Comment by hediet** [comment]
Verification steps:
* Notice that in the diff editor buttons have a background now to indicate their toggled state:
![Code_-_Insiders_Lt8Z0g6xRr](https://github.com/microsoft/vscode/assets/2931520/a14b0a62-2a61-4f3b-9af3-f46efc36b37b)
