### ISSUE TITLE
Up in chat input should only navigate history when the custom is on the top line

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#186433]
Testing https://github.com/microsoft/vscode-internalbacklog/issues/4396

Repro:

1. Write out a multi line prompt
2. Press up

Here the chat navigates prompt history, it should only do that when the cursor is on the first line imo.

**Comment by rebornix** [comment]
Ran into this every day and it's very inconvenient IMHO.

**Comment by roblourens** [comment]
If you follow those steps, the cursor will move like you expect. Up only goes through history when you're at the top or when you have navigated history to another multiline prompt. I assume you have hit the second case. I agree it's a bit annoying but I don't think people hit it that often

**Comment by roblourens** [comment]
It can probably still be improved

**Comment by Tyriar** [comment]
Makes sense, I think I was doing the second one. While testing I was amending many multi-line prompts

**Comment by roblourens** [comment]
Implemented in November
