### ISSUE TITLE
Git - offer a stash option when pulling with outgoing dirty changes

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#186431]
Here:

<img width="346" alt="image" src="https://github.com/microsoft/vscode/assets/900690/b92bacc6-e40d-488b-9afc-8ed8510b1933">

It would be super nice if the dialog could offer to automatically stash, pull and then pop.

**Comment by lszomoru** [comment]
Please enable the `git.autoStash` setting and reopen the issue if that does not meet the requirements. Thanks!
