### ISSUE TITLE
`Reset Menu` and `Hide` are no-ops in the Notebook toolbar

### ISSUE THREAD

**Issue by bhavyaus** [microsoft/vscode#186415]
Testing #186261

`Reset Menu` and `Hide` are no-ops.

![Recording 2023-06-27 at 11 29 28](https://github.com/microsoft/vscode/assets/25044782/36bbb929-dc8e-4f3f-9236-79b0e15c528d)

**Comment by Yoyokrazy** [comment]
Can't get a consistent repro, though I did manage to turn the `Restart` action into a noop... Do you have steps to consistently repro this issue? 

Also was this the default `always` strategy, or `dynamic`?
