### ISSUE TITLE
Let me click on "hidden lines" text to unfold

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#186406]
Testing #186213

I was trying to double-click on the the "123 Hidden Lines" text to unfold that region. I would love to be able to do that if possible

<img width="262" alt="image" src="https://github.com/microsoft/vscode/assets/323878/9bd04b99-b999-4d84-b390-7b74b5ed5d35">

**Comment by roblourens** [comment]
Btw the drag up/down action to reveal a portion of this is so cool, I love it

**Comment by weartist** [comment]
Can I submit a PR for this issue

**Comment by hediet** [comment]
@weartist feel free to do so!

**Comment by weartist** [comment]
@hediet I would like to ask for a small question, if I have a file that I modify it and look at it using the diff editor and turn on Collaps Unchanged Regions, and assuming it has three collapsed regions, and then I expand two of them, whether the collapse button should also remain Collaps Unchanged Regions, but if I expand the last collapsed code by double-clicking, the corresponding button should also change back to Show collapsed regions, and the status changes from gray to normal?

**Comment by hediet** [comment]
@weartist can you create a new issue and share a screenrecording? Thanks!

**Comment by bpasero** [comment]
I find this a bit strange: does it require a double click on the "N hidden lines" text? There is no feedback that I can do that, no cursor change. And why wouldn't I be able to do this over the empty area as well?
