### ISSUE TITLE
Cannot `Ctrl+S` to save Interactive Window

### ISSUE THREAD

**Issue by minsa110** [microsoft/vscode#186427]
Testing #186196

Cannot `Ctrl+S` to save Interactive Window. When I have my cursor in the IW and `Ctrl+S`, I would expect it to `Export to Jupyter Notebook` (i.e., same as `Save` button in IW as below).

![image](https://github.com/microsoft/vscode/assets/10833267/2e10b050-3b5c-4ac6-9124-c5928ce0add2)

**Comment by amunger** [comment]
does ctrl+s do nothing for you, or just perform a different operation than the toolbar's save action?

**Comment by minsa110** [comment]
Doesn't do anything for me

**Comment by minsa110** [comment]
Works now
