### ISSUE TITLE
Git: bring back action to toggle between file and changes

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#18649]
Would be nice to have this useful toggle back that allows to jump between file and diff.

**Comment by joaomoreno** [comment]
Fixed!

**Comment by bpasero** [comment]
@joaomoreno awesome. the only thing is that the action does not show disabled when there are no changes (it used to). Is there already an issue for that?

**Comment by joaomoreno** [comment]
Not yet, create!

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/21131
