### ISSUE TITLE
Show Next Difference is not working

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#186402]
Testing #186213

Running this from the command palette, I see the cursor move but the editor doesn't change. Then if I switch to a different editor and switch back, I get the view of the diff, but I'm not 

<img width="1548" alt="image" src="https://github.com/microsoft/vscode/assets/323878/17058c3e-c285-474d-aac4-e3636538e757">

If I drag the scroll bar it scrolls the sticky scroll header but doesn't change the other text, so something is wrong

**Comment by roblourens** [comment]
I repro this with the old diff too

**Comment by roblourens** [comment]
Btw the F7 keybinding conflicts with `editor.action.wordHighlight.next` so I've got to use the command palette or change it

**Comment by bhavyaus** [comment]
Tried verifying this issue but the diff editor appears stuck after using the `Go to Next Difference` command from the command palette. I have to manually hit `X` to get rid of the diffeditor. 
![Recording 2023-06-29 at 11 18 44](https://github.com/microsoft/vscode/assets/25044782/2202aa87-1478-4d2c-bcc2-243b46a0c52b)

**Comment by hediet** [comment]
@bhavyaus good find, thanks!
