### ISSUE TITLE
Accessibility View: read whole model line instead of wrap line

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#186405]
Testing #186218

When the accessibility view is opened, it only reads the current wrap line (also when we move the cursor), so the initial reading of the accessibility help is never complete. It feels weird that if the accessibility help is partial and requires moving cursor to read the whole sentence.

**Comment by meganrogge** [comment]
That is by design - reading all content at once instead of line by line is what this feature was implemented to accomplish.
