### ISSUE TITLE
Scrolling at the edges of the reference view editor will scroll the outer editor

### ISSUE THREAD

**Issue by Legend-Master** [microsoft/vscode#186477]
Does this issue occur when all extensions are disabled?: Yes/No

Yes

- VS Code Version: 1.79.2
- OS Version: Windows_NT x64 10.0.19045

Steps to Reproduce:

1. Use go to references/definitions to open a reference view window
2. Scroll to the bottom of the embedded editor
3. Keep scrolling will scroll the outer editor

It's quite annoying sometimes, make it behaves like the file tree in the right side would be nice

https://github.com/microsoft/vscode/assets/68118705/1ae23b05-4ddb-46ef-965b-2f06d5cf0107

But I saw this, so is this behavior intended? If so may I ask why?

https://github.com/microsoft/vscode/blob/efb49cc271d6eea5634ac395e36e1e4cd108a447/src/vs/editor/contrib/gotoSymbol/browser/peek/referencesWidget.ts#L308

**Comment by jrieken** [comment]
To verify

* open peek references
* in embedded editor scroll to the end and make sure scrolling stops
