### ISSUE TITLE
Unable to open any WSL files in vscode using the code . command

### ISSUE THREAD

**Issue by vader-v** [microsoft/vscode#186432]
Type: <b>Bug</b>

running into errors for each of my repositories after using the code . command telling me vscode is unable to fetch my remote environment and i am unable to connect to remote extension host server (Error: WebSocket close with status code 10006)

VS Code version: Code 1.79.2 (695af097c7bd098fbf017ce3ac85e09bbc5dda06, 2023-06-14T08:57:04.379Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Connection to 'WSL: Ubuntu' could not be established  WebSocket close with status code 1006

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 9 5900HS with Radeon Graphics         (16 x 3294)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.41GB (5.18GB free)|
|Process Argv|--folder-uri=vscode-remote://wsl+Ubuntu/home/vadersreign/code/sei/labs/finch-collector --remote=wsl+Ubuntu --crash-reporter-id acec7e72-b8cd-465e-9d05-46a0f8c1e556|
|Screen Reader|no|
|VM|0%|

Connection to 'WSL: Ubuntu' could not be established  WebSocket close with status code 1006
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
py29gd2263:30776702
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
3biah626:30602489
pyind779:30671433
89544117:30613380
pythonsymbol12:30671437
a9j8j154:30646983
showlangstatbar:30737416
vsctsb:30748421
pythonms35:30701012
03d35959:30757346
pythonfmttext:30731395
pythoncmv:30756943
fixshowwlkth:30771522
showindicator:30766890
pythongtdpath:30769146
gsof2:30774497
dh2dc718:30776458
pythonidxptcf:30772540
pythondjangotscf:30772537
pythonnoceb:30776495

```

</details>

**Comment by aeschli** [comment]
Does shutting down the wsl distro (`wsl --shutdown`) help?

**Comment by vader-v** [comment]
i’m not entirely sure how i fixed the issue but i had to restart my computer and my router as well.

**Comment by aeschli** [comment]
Likely a runtime issue of the WSL distro. Closing the issue.
