### ISSUE TITLE
terminal not opening

### ISSUE THREAD

**Issue by Pugazh28** [microsoft/vscode#186466]
Type: <b>Performance Issue</b>

sorry to say that in my visual studio code the terminal not opening while i try to open the terminal it shows like  = process failed to launch "A native exception occured during launch (Error launching WinPty agent:agent died)". ple find it fix it

VS Code version: Code 1.79.2 (695af097c7bd098fbf017ce3ac85e09bbc5dda06, 2023-06-14T08:57:04.379Z)
OS version: Windows_NT x64 10.0.17763
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD PRO A4-4350B R4, 5 COMPUTE CORES 2C+3G      (2 x 2495)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: disabled_off<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|3.84GB (1.13GB free)|
|Process Argv|--crash-reporter-id 6068365d-70d6-4713-994a-19a86942af7a|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    4	    88	  9140	code main
    0	    52	   236	shared-process
    2	   142	  3904	   gpu-process
    7	    57	  7084	window [2] (Issue Reporter)
    0	    11	  7560	   crashpad-handler
    0	    23	  8388	   utility-network-service
    0	   173	  8456	window [1] (index.js - Desktop - Visual Studio Code)
    0	    36	  8492	fileWatcher [1]
    0	    75	  8588	extensionHost [1]
    0	    44	  3692	     electron-nodejs ("C:\Users\Lenovo\AppData\Local\Programs\Microsoft VS Code\Code.exe" --ms-enable-electron-run-as-node --max-old-space-size=3072 "c:\Users\Lenovo\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js" --useInferredProjectPerProjectRoot --enableTelemetry --cancellationPipeName C:\Users\Lenovo\AppData\Local\Temp\vscode-typescript\a50b17c6a023b11614b7\tscancellation-60a2fe9bdf1b776b2d01.tmp* --locale en --noGetErrOnBackgroundUpdate --validateDefaultNpmLocation --useNodeIpc)
    0	    30	  7164	       electron-nodejs ("C:\Users\Lenovo\AppData\Local\Programs\Microsoft VS Code\Code.exe" --ms-enable-electron-run-as-node "c:/Users/Lenovo/AppData/Local/Programs/Microsoft VS Code/resources/app/extensions/node_modules/typescript/lib/typingsInstaller.js" --globalTypingsCacheLocation C:/Users/Lenovo/AppData/Local/Microsoft/TypeScript/5.1 --enableTelemetry --typesMapLocation "c:/Users/Lenovo/AppData/Local/Programs/Microsoft VS Code/resources/app/extensions/node_modules/typescript/lib/typesMap.json" --validateDefaultNpmLocation)
    0	    41	  5912	     electron-nodejs ("C:\Users\Lenovo\AppData\Local\Programs\Microsoft VS Code\Code.exe" --ms-enable-electron-run-as-node --max-old-space-size=3072 "c:\Users\Lenovo\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js" --serverMode partialSemantic --useInferredProjectPerProjectRoot --disableAutomaticTypingAcquisition --cancellationPipeName C:\Users\Lenovo\AppData\Local\Temp\vscode-typescript\a50b17c6a023b11614b7\tscancellation-a36110f831fe09269c1e.tmp* --locale en --noGetErrOnBackgroundUpdate --validateDefaultNpmLocation --useNodeIpc)
    0	    39	  7488	     electron-nodejs ("C:\Users\Lenovo\AppData\Local\Programs\Microsoft VS Code\Code.exe" --ms-enable-electron-run-as-node "c:\Users\Lenovo\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\json-language-features\server\dist\node\jsonServerMain" --node-ipc --clientProcessId=8588)
    0	    35	  8744	ptyHost
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (index.js - Desktop - Visual Studio Code)
|    Folder (Desktop): 37 files
|      File types: html(7) css(6) js(4) jpg(3) png(3) svg(2) lnk(2) json(1)
|      Conf files: tasks.json(1);
```

</details>
<details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
es7-react-js-snippets|dsz|4.4.3
vscode-html-css|ecm|1.13.1
prettier-vscode|esb|9.16.0
code-runner|for|0.12.0
remote-containers|ms-|0.296.0
vscode-css-peek|pra|4.2.0
LiveServer|rit|5.7.9
html5-boilerplate|sid|1.1.1
JavaScriptSnippets|xab|1.8.0
five-server|yan|0.2.3
material-theme|zhu|3.15.17

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
py29gd2263:30776702
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
3biah626:30602489
pyind779:30671433
f6dab269:30613381
pythonsymbol12:30671437
showlangstatbar:30737416
vsctsb:30748421
pythonms35:30701012
a2ce3375:30757347
pythonfmttext:30731395
pythoncmvfstrcf:30756944
fixshowwlkth:30771522
pythongtdpath:30769146
i26e3531:30769768
e440d664:30776459
pythonidxptcf:30772540
pythondjangots:30772535
pythonnocebcf:30776496

```

</details>

**Comment by Tyriar** [comment]
This sort of thing is typically due to antivirus software messing with the launching of terminals. Regardless, the "winpty" component is now legacy and you will need to update Windows to move on to the new "conpty" which is maintained by another team at Microsoft.
