### ISSUE TITLE
Remote menu option inconsistencies

### ISSUE THREAD

**Issue by minsa110** [microsoft/vscode#186416]
Testing #186222

A few inconsistencies between the two ways to get to the remote menu:
- Category `GitHub Codespaces` vs. `Codespaces`
- Differences in order of remote sources
- `Install` options appear differently

Go to `Help: Welcome` -> click `Connect to...` shows this list:
![image](https://github.com/microsoft/vscode/assets/10833267/e587849e-5c0e-428a-bce3-eb582a7858c9)

Clicking on the remote indicator shows this list:
![image](https://github.com/microsoft/vscode/assets/10833267/7fd60849-5b49-481c-9d5d-dc244963373a)

**Comment by bhavyaus** [comment]
@minsa110 the screenshot of the remote indicator is **before** https://github.com/microsoft/vscode/issues/186222. Could you please try again after updating to the latest insiders build?

**Comment by minsa110** [comment]
Verified no longer an issue
