### ISSUE TITLE
Tunnel [web -> WSL]: WSL extension claims it cannot connect but it connects

### ISSUE THREAD

**Issue by karthiknadig** [microsoft/vscode#186430]
Testing #186246

![image](https://github.com/microsoft/vscode/assets/3840081/7e0f6a5b-e364-47fc-896c-1c200c346e98)
![image](https://github.com/microsoft/vscode/assets/3840081/5132d071-b817-47dd-8b8f-da599317abb7)

**Comment by connor4312** [comment]
Fixed in https://github.com/microsoft/vscode-remote-wsl/pull/150
