### ISSUE TITLE
`+ Markdown` item is missing from the toolbar when resized to fit smaller screen size.

### ISSUE THREAD

**Issue by bhavyaus** [microsoft/vscode#186412]
Testing #186261

`+ Markdown` item is missing from the toolbar when resized with `notebook.globalToolbarShowLabel:dynamic`

<img width="297" alt="image" src="https://github.com/microsoft/vscode/assets/25044782/40470d2b-78c6-4cad-aa66-ce87c4ae710b">

**Comment by Yoyokrazy** [comment]
This is intended behavior to align with pre-rewrite functionality. Will be looking into maybe expanding the functionality of this action in the future.
