### ISSUE TITLE
[themes] Comments are not colored

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#1864]
![screen shot 2016-01-08 at 10 00 29](https://cloud.githubusercontent.com/assets/1926584/12194233/b2b0ed32-b5ee-11e5-9393-35e2d2bf24e5.png)

I see this for all languages and all themes in VSCode 27db7e99c6bf9832b77448636c75cd8fbbf62599

**Comment by aeschli** [comment]
fix delivered
