### ISSUE TITLE
jump to another file doesn't work

### ISSUE THREAD

**Issue by kevin1211** [Microsoft/vscode#18640]
- VSCode Version:1.8.1
- OS Version:macOS 10.12.2

Steps to Reproduce:

```
// file a.js
const M = module.exports = {};
M.A = '';

//file b.js
const M = require('./a');
const A = M.A;

```
and now press `command` and click `A` of `M.A` in b.js, it can noe jump to `M.A` where in `a.js`

**Comment by mjbvz** [comment]
This is really another manifestation of https://github.com/Microsoft/TypeScript/issues/7632 since `M.A` has an `any` type. Closing as upstream
