### ISSUE TITLE
showInputBox() close instantly

### ISSUE THREAD

**Issue by Ludonope** [Microsoft/vscode#18643]
- VSCode Version:
Version 1.8.1
Commit ee428b0eead68bf0fb99ab5fdc4439be227b6281
Date 2016-12-19T14:41:20.664Z
Shell 1.4.6
Renderer 53.0.2785.143
Node 6.5.0

- OS Version: Linux ludonope 4.8.13-1-ARCH #1 SMP PREEMPT Fri Dec 9 07:24:34 CET 2016 x86_64 GNU/Linux
I'm using Gnome 3.22

Problem:

I'm developping a small extension in typescript, and I would like to ask input from the user.

When I use vscode.window.showInputBox().then(val => {...}); and execute my command, the command itself execute, and I see the input box pop and disapearing in maybe 0.5s, and then the message "Info: Your input was undefined" if promped by vscode.

**Comment by jrieken** [comment]
@Ludonope Please attach a code snippet that allows me to reproduce this

**Comment by Ludonope** [comment]
Ok my bad, I was creating multiple commands, and (being more a C dev) I used the same object to push in the context.subscription.push(...), but in my last commands I didn't tried to use showInputBox(). So it was just completely ignored and there was no real error.

Thanks anyway
