### ISSUE TITLE
Default path does not work for remote

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode#186439]
Testing #186172

* Open a dev container , the workspace folder is `/workspaces/crap/containers/ubuntux64`
* Update the remote setting to point to the folder `"file.dialog.defaultPath":"/workspaces/crap/containers/ubuntux64/folder"`
* Close the workspace folder and Reload VS Code
* Try the `File->Open` and it defaults to `/root/` instead of `/workspaces/crap/containers/ubuntux64/folder`

**Comment by tanushkathakre** [comment]
i would like to contribute

**Comment by gjsjohnmurray** [comment]
@DonJayamanne I wasn't able to repro this with the devcontainer for a public repo I contribute to, nor with the following Codespaces test:

1. Go to https://github.com/microsoft/vscode-extension-samples in a web browser.
2. Launch a codespace
3. Confirm that File\Open File... shows simple Open File dialog at /workspaces/vscode-extension-samples/
4. Don't open anything, but instead just press Esc.
5. In Settings Editor's Remote [Codespaces] tab set `files.dialog.defaultPath` to `/workspaces/vscode-extension-samples/helloworld-sample`
6. From File menu choose Close Folder.
7. From File menu choose Open File... and observe simple File Open starts at `/workspaces/vscode-extension-samples/helloworld-sample/`
8.

**Comment by DonJayamanne** [comment]
Note, I’m in a docket container, not codespace
Will try codespaces as Sri

**Comment by gjsjohnmurray** [comment]
> Note, I’m in a docket container, not codespace

Yes,. noted. I offered Codespaces steps as ones you'd be able to repeat. If vscode-extension-samples was devcontainer-ready I'd have tried to verify that way.

**Comment by gjsjohnmurray** [comment]
Just remembered that https://github.com/microsoft/vscode-jupyter is devcontainer-ready, so am testing with that...

**Comment by gjsjohnmurray** [comment]
Worked as expected with that repo in a devcontainer. I followed your steps, using `/workspaces/vscode-jupyter/docs/` as the remote-specific value for the new setting.

**Comment by bpasero** [comment]
I think this is a timing issue. I can only reproduce this if I very quickly go to "Open Folder..." before the remote has initialized and this is probably because settings in that case are not yet defined from the remote.

I think this is OK to leave like that.
