### ISSUE TITLE
Debug: prevent breakpoints on left hand side diff editor or readonly editor

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#18647]
Does not make sense to add a breakpoint to the left hand side of an editor. And also not to the right hand side if the editor is readonly (staged).

**Comment by isidorn** [comment]
No, readonly editor makes sense since we allow people to put breakpoints in readonly internal module.
Left hand side of diff editor - agree.

**Comment by bpasero** [comment]
@isidorn I see the point with the internal module, but couldn't we then say that the only readonly editor where we allow breakpoints is those with a `debug://` resource?

**Comment by isidorn** [comment]
Might you know what is the best way to check if I am in the left hand side of the diff editor. As far as I see diff editor is one editor which has one model

**Comment by isidorn** [comment]
@bpasero makes sense. In that case how do I figure out if an editor is readonly, where does that property live?

**Comment by bpasero** [comment]
@isidorn how today do we enable to set breakpoints in an editor? is that an editor option?

**Comment by isidorn** [comment]
@bpasero adapters are contributing the languge type they want breakpoints to be enabled.
More details: https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/debug/electron-browser/debugConfigurationManager.ts#L409

So I could add an aditional check on an editor or on the model.

**Comment by bpasero** [comment]
@isidorn that looks perfect, can you not change that check to be `file://` or `debug://` resource?

**Comment by isidorn** [comment]
@bpasero thanks! Also notice that I have moved the debug schema to network schemas via 00e2657   not sure if the debug schema should be merged with inmemory, but for now they are seperate

**Comment by bpasero** [comment]
Cool, Not sure it makes sense to add those schemas to base though, we have many more that are not in there.

**Comment by isidorn** [comment]
@bpasero was not aware we have more that are not in there, I will revert my commit.
