### ISSUE TITLE
error when attempting to run `WSL: Reopen Folder in Windows`

### ISSUE THREAD

**Issue by amunger** [microsoft/vscode#186418]
Testing #186246

[Window Title]
Visual Studio Code - Insiders

[Main Instruction]
Command 'WSL: Reopen Folder in Windows' resulted in an error

[Content]
Attempted to send error data when the @vscode/extension-telemetry module does not support it.

[OK]

**Comment by connor4312** [comment]
Was this when in a tunnel, or in normal WSL?

**Comment by amunger** [comment]
normal WSL
