### ISSUE TITLE
Accessible view should show content of currently focused chat message

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#186526]
Accessible view should show content of currently focused chat message, of the most recent if the textbox has focus. Currently if I focus some message in the past and hit alt+f2, it brings up the most recent message instead.

**Comment by meganrogge** [comment]
This didn't come up in testing via the TPI which is surprising if it's not working.

**Comment by Tyriar** [comment]
Focusing responses it definitely happens for me:

![Recording 2023-06-28 at 10 40 22](https://github.com/microsoft/vscode/assets/2193314/23ebbdbd-da84-4fb8-b870-bb645bbb0b81)

**Comment by meganrogge** [comment]
Yeah something changed 😢 I can repro
