### ISSUE TITLE
Workspace file encoding setting is not affect

### ISSUE THREAD

**Issue by halityurttas** [Microsoft/vscode#18653]
- VSCode Version: Code 1.8.1 (ee428b0eead68bf0fb99ab5fdc4439be227b6281, 2016-12-19T14:49:23.350Z)
- OS Version: Windows_NT ia32 10.0.14393
Steps to Reproduce:
Workspace setting File encoding variable set to "iso88599" that is not affect on file open. But is truly working previous version. My workspace working file is contains below lines

`// Place your settings in this file to overwrite default and user settings.`
`{`
`    "files.encoding": "iso88599"`
`}`

**Comment by bpasero** [comment]
@halityurttas I cannot reproduce, are you opening a file from the folder you have open? can you share a screenshot or video that prooves what is going wrong?

**Comment by halityurttas** [comment]
Setting up workspace settings that Its shown below
<a data-flickr-embed="true"  href="https://www.flickr.com/photos/122559855@N05/31765908094/in/album-72157679657682776/" title="2017-01-30 16_42_42-settings.json - S__ - Visual Studio Code"><img src="https://c1.staticflickr.com/1/333/31765908094_1cc678dd4a_z.jpg" width="640" height="234" alt="2017-01-30 16_42_42-settings.json - S__ - Visual Studio Code"></a><script async src="//embedr.flickr.com/assets/client-code.js" charset="utf-8"></script>
But not working file open. You can see encoding is UTF-8 on image bottom. I change to every file open encoding to iso88599.
<a data-flickr-embed="true"  href="https://www.flickr.com/photos/122559855@N05/32456135602/in/album-72157679657682776/" title="2017-01-30 16_43_38-pert_list.asp - S__ - Visual Studio Code"><img src="https://c1.staticflickr.com/1/627/32456135602_06aa896831_o.jpg" width="511" height="407" alt="2017-01-30 16_43_38-pert_list.asp - S__ - Visual Studio Code"></a><script async src="//embedr.flickr.com/assets/client-code.js" charset="utf-8"></script>

**Comment by halityurttas** [comment]
I specify also I am working a folder that i dont open file directly. I remember truly working on its directory previous version.

**Comment by halityurttas** [comment]
Problem resolved at new version. Thanx
