### ISSUE TITLE
Set default indentation for new files in workspace

### ISSUE THREAD

**Issue by marcospgp** [microsoft/vscode#186519]
Looking for how to set the default indentation for new files, Google led me to the closed issue https://github.com/Microsoft/vscode/issues/22012, though the issue does not appear to have been solved.

I'd like files created in my current workspace to default to an indentation of 2 spaces. Currently, they default to an indentation of 4 spaces.

I was not able to configure this through the editor settings.

**Comment by M-Arham-Kashif** [comment]
Ok, 
I think it would work to change the **JSON** file for new files.
Please respond to work together on this issue.
Thank You.

**Comment by marcospgp** [comment]
@M-Arham-Kashif Couldn't this be supported by an editor setting? We already have similar settings, we'd just need an option to set the default indentation for new files (tabs or some number of spaces). 

This could then be saved to workspace settings and stored on repositories.

**Comment by nickmccurdy** [comment]
This should already be supported. I'm able to create new files after setting `editor.tabSize` using the correct indentation level.

In your case you'd want:
```json
"editor.tabSize": 2
```
