### ISSUE TITLE
[Feature Request] show JSDoc info for component / directive properties and events in Angular template (HTML file or inline)

### ISSUE THREAD

**Issue by KingMario** [microsoft/vscode#186589]
Please implement the function to show JSDoc info (if exists) for component / directive properties and events in Angular html file or inlined template while hover.

Thanks

Searched terms: _is:issue_ `JSDoc` `Angular`
Search result: not related

PS: I don't know whether it's a built-in function for VSCode to show JSDoc in .ts/.js files. If so, since Angular Language Service has provided the component / directive and member information for the bound attributes in html tags, is it VSCode's convenience to show the JSDoc info in a hover component?

Please point me out if the function is up to Angular Language Service, then I'll raise a feature request in Angular language service extension.

**Comment by mjbvz** [comment]
Please file this feature request against the angular extension

**Comment by KingMario** [comment]
@mjbvz got it. will file this FR against the Angular extension. Thanks
