### ISSUE TITLE
Git: renamed file is showing up weirdly

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#18654]
Steps to Reproduce:

1. rename a file
2. stage it

=> the file shows up with many changes, even though it is just a rename
=> right clicking on the change "Open File" does not work either

![image](https://cloud.githubusercontent.com/assets/900690/22019304/4b43508a-dcb3-11e6-89a7-f44c2e1a07f0.png)

**Comment by bpasero** [comment]
Still:

![image](https://cloud.githubusercontent.com/assets/900690/23210701/17523dbe-f8ff-11e6-8849-074e0d21cf1b.png)

**Comment by joaomoreno** [comment]
I can't repro.

**Comment by joaomoreno** [comment]
Happens when the file isn't in root.

**Comment by joaomoreno** [comment]
Nope. Steps are:

1. Start with a workspace in which a file has been renamed, but not staged
2. Open that file
3. Switch to the SCM viewlet
4. Stage the add and delete
5. Open the rename
