### ISSUE TITLE
Multiroot workspace build tasks are shown in the wrong order

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#186539]
My workspace config looks like this

<img width="436" alt="image" src="https://github.com/microsoft/vscode/assets/323878/db733974-7107-48bc-937b-6c301fdc5dbd">

But build tasks are shown in the opposite order

<img width="634" alt="image" src="https://github.com/microsoft/vscode/assets/323878/c4540241-3aea-418b-877f-4b427bea5d75">

There are lots of commands that do something similar and show workspaces in a random order, I really want them to show up in a predictable customizable order, especially since I operate on the vscode repo 99% of the time, so I am filing issues on all these features as it comes up.

**Comment by roblourens** [comment]
I realized that since this the "recently used" list, it's probably just in recency order.

**Comment by meganrogge** [comment]
Ok so should this be closed?

**Comment by roblourens** [comment]
Up to you
