### ISSUE TITLE
Custom label on a timeline entry

### ISSUE THREAD

**Issue by kenmckaba** [microsoft/vscode#186555]
A way to add a label or tag to a timeline entry.

Now most of my timeline entries are "File Saved". I'd like a way to identify a particular point in my changes. E.g. if I'm about to embark on a refactoring but want a quick way to identify and restore my previous code.

**Comment by bpasero** [comment]
You can rename entries:

![image](https://github.com/microsoft/vscode/assets/900690/5b2e23aa-1702-4631-9a80-62b4d10711c0)

You can create custom entries:

![image](https://github.com/microsoft/vscode/assets/900690/c18b7e40-101e-4241-ba7c-39996e148b17)
