### ISSUE TITLE
BUG: diff collapse unchange regions button moves

### ISSUE THREAD

**Issue by dimateos** [microsoft/vscode#186599]
Does this issue occur when all extensions are disabled?: Yes

Version: 1.79.2 (system setup)
Commit: 695af097c7bd098fbf017ce3ac85e09bbc5dda06
Date: 2023-06-14T08:57:04.379Z
Electron: 22.5.7
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Windows_NT x64 10.0.19044

Steps to Reproduce:

1. new diff editor
```json
    "diffEditor.experimental.useVersion2": true,
    "diffEditor.experimental.collapseUnchangedRegions": true,
```
2. hide most of the tab icons. I cannot exactly remember which option was, but I guess right click hide works too?
3. clicking the button (or using `diffEditor.toggleCollapseUnchangedRegions`) changes the buttons order:

![2023-06-29_(091133)_Code](https://github.com/microsoft/vscode/assets/26868611/5ad9209a-717d-44d6-96f8-9a27da54ced7)

**Comment by hediet** [comment]
This is already fixed in insiders.
