### ISSUE TITLE
git commit and scrolling issues in integrated terminal

### ISSUE THREAD

**Issue by johandalabacka** [Microsoft/vscode#18659]
- VSCode Version: Code 1.8.1 (ee428b0eead68bf0fb99ab5fdc4439be227b6281, 2016-12-19T14:42:49.304Z)
- OS Version: Darwin x64 16.0.0
- Extensions:

---

If I have vi as default git commit editor and does a commit will the integrated terminal scroll to the top instead of staying at the bottom.

Steps to Reproduce:

1. git commit
2. Write a commit and ZZ (save and exit)
3. terminal is scrolled to top. Scroll down while sighing 😞

**Comment by Tyriar** [comment]
This whole area was redone in the latest Insiders so it should be fixed in the next version.

In the meantime I recommend replacing step 3 with <kbd>cmd</kbd>+<kbd>end</kbd> :smiley:
