### ISSUE TITLE
Add macOS Profile support for System Administrators (Similar to Group Policy on Windows)

### ISSUE THREAD

**Issue by Ifrit-Fire** [microsoft/vscode#186556]
Currently Group Policy is an available option for System Administrators on Windows.  It would be beneficial to also supply a similar solution using macOS Profiles on macOS.  For us sys admins deploying VSCode to both platforms, we get a nice way to enforce company wide software settings on Windows but a less nice way to do the same on macOS.

**Comment by joaomoreno** [comment]
https://github.com/microsoft/vscode/issues/148942
