### ISSUE TITLE
Missing source maps not unmapped by unmapMissingSources

### ISSUE THREAD

**Issue by capegreg** [microsoft/vscode#186563]
Version: 1.79.2 (user setup)
Commit: 695af097c7bd098fbf017ce3ac85e09bbc5dda06
Date: 2023-06-14T08:57:04.379Z
Electron: 22.5.7
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Windows_NT x64 10.0.19045

Steps to Reproduce:

1. Open VSCode 
2. Enable unmapMissingSources in settings
3. Create a new html page. Add the html here.
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.7.0/dist/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@floating-ui/core@1.3.1/dist/floating-ui.core.umd.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/i-floating-ui-dom@0.4.2/dist/floating-ui.dom.umd.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.cs"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js"></script>
</head>
<body>
    here i am.
</body>
</html>

4. Save page and run to launch in Chrome browser.
5. Observe Debug console.
"Could not read source map..."

// Configures whether sourcemapped file where the original file can't be read will automatically be unmapped. 
// If this is false (default), a prompt is shown.
set to true still shows missing source map 
"debug.javascript.unmapMissingSources": true

**Comment by capegreg** [comment]
html was sanitized in submission. Here is screenshot.

![image](https://github.com/microsoft/vscode/assets/1051118/a0a3ae39-30f7-4bfb-8f81-e32682b04fbc)

**Comment by capegreg** [comment]
Added trace file

[vscode-debugadapter-56682a36.json.gz](https://github.com/microsoft/vscode/files/11906780/vscode-debugadapter-56682a36.json.gz)

**Comment by connor4312** [comment]
You can tweak the `resolveSourceMapLocations` setting in your launch.json for this.
