### ISSUE TITLE
Random test order in gutter context menu

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#186515]
1. Follow the setup of microsoft/vscode-python#21494
2. Open `test_wait_parameterized.py`
3. Right click the Test gutter decoration

🐛 Numbers appear in random order:

<img width="485" alt="image" src="https://github.com/microsoft/vscode-python/assets/22350/b4f96db1-1cd4-44f5-9c25-8a25a73664c0">

Also, if you change `range(1, 100)` to `range(1, 10000)`, you'll get a very slow opening menu.

cc @connor4312

**Comment by connor4312** [comment]
Maybe we should have a "X more tests..." item that opens a quickpick after like 10. What do you think @eleanorjboyd?

**Comment by eleanorjboyd** [comment]
yeah agreed that its not worth displaying more than 10 tests in a quick pick and I think the "X more tests..." will be a good way to tell users
