### ISSUE TITLE
pre-release icon missing from extensions view

### ISSUE THREAD

**Issue by amunger** [microsoft/vscode#186530]
![image](https://github.com/microsoft/vscode/assets/2019016/553297b3-d462-4023-83af-75855a4c567f)

There used to be a small icon 
![image](https://github.com/microsoft/vscode/assets/2019016/1e61ebcb-bed5-4006-8c21-4cc40ba0e7a6)

**Comment by sandy081** [comment]
@amunger I am seeing it. Can you reproduce it consistently?

**Comment by amunger** [comment]
sorry, forgot to follow up on this - they came back (possibly even the same day) and I haven't seen them missing since then.
