### ISSUE TITLE
Need a quick way to run or debug the last test I ran

### ISSUE THREAD

**Issue by kenmckaba** [microsoft/vscode#186553]
I often repeatedly run or debug a test as I work on it. I'd like a quick way to run or debug the last test I ran.
Ideally something I can assign to a single keystroke. 
Currently, I have to find the test's first line in my code, in the testing panel or in test results.

**Comment by connor4312** [comment]
Please use the "Test: Rerun failed tests" or "Test: Rerun last run" commands for this.

**Comment by kenmckaba** [comment]
Thanks! However, I find that those commands do nothing unless I have previously debugged a test. But, I can live with that...
