### ISSUE TITLE
Mouse not working at all in terminal + all terminal editor keybinding is occupied by vs code

### ISSUE THREAD

**Issue by photogyulai** [microsoft/vscode#186573]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.79.2
- OS Version: Windows 10.

Steps to Reproduce:

1. Open Vs code
2. Open new terminal
3. SSH into a server,  for example: ssh username@192.168.2.87  (i was logged into an ubuntu server)
4. open some larger config file @ the server. for example:
                sudo nano .bashrc
                sudo micro .bashrc

### The first bug:
 **the mouse does not work at all in does editors**. Nor in nano, nor in micro.
In different terminal softwares: "Micro editor" >> uses the mouse with no problem.
"Nano editor" could use the mouse with the  -m switch.  

After two hours of ai chat and google and youtube i could not use the mouse in the terminal.

### The second bug:
If in nano or micro editor i try to do anything usual (save, exit, delete a line, copy/paste), there is a huge possibility that a vs code keyboard shortcut is conflicting with the nano and or micro editor. 

- Ctrl+K in nano editor to delete a line >> no chance to use it in vs code terminal
- Ctrl+Shift+K in micro editor to delete a line >> does not work in vs code terminal
- ctrl+q to exit from micro editor in the terminal >> steps out from the terminal in vs code so you can not close the micro editor

vs code look promissing, but without the mouse usage in the terminal it has a "DOS" system productivity, 
and with the keybindings conflict, using vs code to ssh is basically impossible

thanks i hope you find solution, get back to me if you need help or testing.

Bence Gyulai

**Comment by Tyriar** [comment]
For mouse support we do support this, but it's bound to the conpty version which is shipped in Windows. You'll need to update windows to improve this.

For the keybindings, you can read all about how to tweak the to your liking in https://code.visualstudio.com/docs/terminal/advanced#_keybinding-and-the-shell

**Comment by photogyulai** [comment]
Hey Daniel!
Thanks for the reply.
I just installed a fresh, windows10 and updated it a week ago. Alongside
with a fresh vs code (1.79.2.
The mouse is not working* in vscode terminal if i ssh to a server and open
an editor window to configure soem file.
Example: sudo macro .bashrc >> no mouse functionality in vs code.   In
other terminal emulators i dont have such a problem. Mouse and
keybindings... they just work.

Keybindings:
i will look into the link that you sent. But i think in general, form a
software ergonomic view, is not a good idea to occupy offen used
keybindings. If i press come keyboard in vs code >> terminal >> macro -
nano - vim editor. There is a good chance that will not work because it is
reserved by vs code by default.
It is not a good practice to start "hacking" a freshly installed software,
for features that must have to work instantly.
Thank again!
Bence Gyulai




Üdvözlettel
Gyulai Bence


Daniel Imms ***@***.***> ezt írta (időpont: 2023. jún. 29.,
Cs, 21:43):
