### ISSUE TITLE
Expose diffEditor to plugins

### ISSUE THREAD

**Issue by SamVerschueren** [Microsoft/vscode#1865]
It would be nice to be able to open the diffEditor in a plugin. At the moment, I determine the diff myself in `vscode-yo` if a conflict arrises. But the diffEditor of Code is much more powerfull and shows the diffs very nicely. Is this a possibility?

// @bpasero

**Comment by bpasero** [comment]
Yes, just talked about this with @jrieken

**Comment by jrieken** [comment]
@bpasero Given virtual document etc and the API command, can't we just expose the underlying command?

**Comment by bpasero** [comment]
@jrieken the command I am using in the explorer currently only works with files that exists on disk (https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/files/browser/fileActions.ts#L1270). we would have to introduce a new command that can deal with any resource and then use it from that action too.

**Comment by jrieken** [comment]
k. seems easy, let's do that in May

**Comment by bpasero** [comment]
Something like this seems to work already:

**extHostApiComands**
```typescript
this._register('vscode.diff', (left: URI, right: URI, label: string) => {
	return this._commands.executeCommand('_workbench.diff', left, right, label);
}, {
	description: 'Opens the provided resources in the diff editor to compare their contents.',
	args: [
		{ name: 'left', description: 'Uri of the resource for the left hand side of the diff editor', constraint: value => value instanceof URI },
		{ name: 'right', description: 'Uri of the resource for the right hand side of the diff editor', constraint: value => value instanceof URI },
		{ name: 'label', description: 'Label to use for the diff editor', constraint: value => typeof value === 'string' }
	]
});
```

**electron-browser/actions**
```typescript
KeybindingsRegistry.registerCommandDesc({
	id: '_workbench.diff',
	weight: KeybindingsRegistry.WEIGHT.workbenchContrib(0),
	handler(accessor: ServicesAccessor, args: [URI, URI, string]) {
		const instantiationService = accessor.get(IInstantiationService);
		const editorService = accessor.get(IWorkbenchEditorService);

		const left = instantiationService.createInstance(ResourceEditorInput, nls.localize('left', "Left"), null, args[0]);
		const right = instantiationService.createInstance(ResourceEditorInput, nls.localize('right', "Right"), null, args[1]);
		const diff = new DiffEditorInput(args[2], null, left, right);

		return editorService.openEditor(diff);
	},
	context: undefined,
	primary: undefined
});
```

**Comment by daviwil** [comment]
If we provide a normal file URI to this API (not a virtual document URI) will it work as expected?

**Comment by rebornix** [comment]
Good to see this newly added api then we may diff PR in VS Code.

**Comment by jrieken** [comment]
@daviwil Yes `file` or _virtual_ resources are all supported
