### ISSUE TITLE
Git: hygiene check fails does not report properly when committing

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#18655]
Steps to Reproduce:

1. have a hygiene error (e.g. layer breaker)
2. try to commit

=> you see a generic git error, not even an action to show output

![image](https://cloud.githubusercontent.com/assets/900690/22019361/894315fa-dcb3-11e6-8098-aefa0efbbde9.png)

**Comment by bpasero** [comment]
A bit unhappy, since we have multi line error messages, we only show the first line:

![image](https://cloud.githubusercontent.com/assets/900690/22294694/83fe5962-e314-11e6-9092-026d6e647e21.png)

**Comment by joaomoreno** [comment]
At least there's the `Open Git Log` action.
