### ISSUE TITLE
Focus issues with Home/End in Autocomplete dialog

### ISSUE THREAD

**Issue by thekalinga** [Microsoft/vscode#18656]
- VSCode Version:

Version 1.9.0-insider
Commit 2cdc2b3da8f0fd5322b48747241584cf9dd98f8f
Date 2017-01-13T07:03:18.620Z
Shell 1.4.6
Renderer 53.0.2785.143
Node 6.5.0

- OS Version:

Ubuntu 14.04

Steps to Reproduce:

1. Type something that triggers auto complete
2. Press up & down arrow. Press pagup & pagedown. In both cases, focus moves within the auto suggestions dialog
3. Now press home/end, the auto complete dialog closes & the cursor moves to the start of the line. Instead the first/last item in the auto suggest needs to be selected in the dialog without closing the auto suggest window.

#### Why should the implementation for Home/End buttons needs to be changed?

1. Because the user was interested in narrowing down the auto suggest results by pressing `up`/`down`/`pgup`/`pgdn`/the key combination that triggers auto suggestions `ctrl+space`. So we should assume that he would be interested in moving within the autosuggest dialog when he presses either `home`/`end` after he presses any of the key combinations mentioned above

2. IntelliJ implementation is along similar lines

#### Suggestion on the implementation of handling Home/End.

1. If the user starts typing & auto suggest window automatically opens up, `home`/`end` will take the user to start/end of the line in the editor after closing the dialog (the current behaviour)
2. If the `home`/`end` buttons are pressed after user presses `up`/`down`/`pgup`/`pgdn`/`ctrl+space` keys, the subsequent `home`/`end` buttons should move the focus within the dialog, not in the editor

**Comment by mlewand** [comment]
@joaomoreno this issue got fixed by #20156.

**Comment by joaomoreno** [comment]
Thanks man!

**Comment by joaomoreno** [comment]
Due to #24673, I've removed the keybindings for <kbd>Home</kbd> and <kbd>End</kbd>, but left the commands in. If you'd like those keys to be handled by the suggest widget, add the following to your `keybindings.json`:

```json
{
    "key": "home",
    "when": "editorTextFocus && suggestWidgetMultipleSuggestions && suggestWidgetVisible",
    "command": "selectFirstSuggestion"
},
{
    "key": "end",
    "when": "editorTextFocus && suggestWidgetMultipleSuggestions && suggestWidgetVisible",
    "command": "selectLastSuggestion"
}
```
