### ISSUE TITLE
Why does accessibility help go to the monaco editor accessibility wiki page?

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#186523]
Previously this went to _VS Code's_ a11y help https://go.microsoft.com/fwlink/?linkid=851010 -> https://code.visualstudio.com/docs/editor/accessibility

![image](https://github.com/microsoft/vscode/assets/2193314/8445943b-c73c-4318-85b3-e7ed85ce96fa)

Now it goes to monaco's? https://go.microsoft.com/fwlink/?linkid=852450 -> https://github.com/Microsoft/monaco-editor/wiki/Monaco-Editor-Accessibility-Guide

**Comment by meganrogge** [comment]
Also forgot to remove the `AccessibilityHelpWidget` and `AccessibilityHelpController`, which are no longer used

https://github.com/microsoft/vscode/blob/0ab28d67242cead18e69df6697df93f4bdf2a7b4/src/vs/workbench/contrib/codeEditor/browser/accessibility/accessibility.ts#L12-L25
