### ISSUE TITLE
Cant see terminal text

### ISSUE THREAD

**Issue by X-DCB** [microsoft/vscode#186598]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 
- OS Version:
![image](https://github.com/microsoft/vscode/assets/28706220/96b9666e-be53-4d80-a31d-04be0a50b457) 

What is happening?
It's been a week haha. I've tried all kinds of terminal but same issue.
![image](https://github.com/microsoft/vscode/assets/28706220/a800c5dc-98e4-44c9-8f33-9b40fea6ba42)

**Comment by Tyriar** [comment]
Looks like you're probably hitting issues with the GPU acceleration. You can try updating your graphics drivers but if that doesn't work I'd recommend turning it off: https://code.visualstudio.com/docs/terminal/appearance#_gpu-acceleration
