### ISSUE TITLE
DAP, Evaluate Request: EvaluateArguments Should Include Range

### ISSUE THREAD

**Issue by hediet** [microsoft/vscode#186639]
When hovering the mouse on source code while debugging, the [Evaluate](https://microsoft.github.io/debug-adapter-protocol/specification#Requests_Evaluate) DAP request is sent out.
It sets the context to `hover` and includes the expression. However, it does not include the source range of the expression.

This has severals problems:
* The user can hover on unrelated variables and gets confusing results: 
     ![Code_-_Insiders_6E7ggLQdej](https://github.com/microsoft/vscode/assets/2931520/dfef19e1-3c61-42ee-8dfc-d72e7d4b3e7f)
* Languages that allow shadowing are not really supported:
     ![Code_-_Insiders_dgmLn9ZUwV](https://github.com/microsoft/vscode/assets/2931520/bd038586-e6d9-476b-889c-c7511217a644)
     Output:
     ```
     inner x: 2
     outer x: 1
     ```

* It is very difficult to make use of static type information to interpret the evaluation result.

Related: #84044

**Comment by roblourens** [comment]
The debug adapter can't really do anything about this. This is what the EvaluatableExpressionProvider is for. I don't think that TS has ever adopted this. So maybe that's what you are asking for?

**Comment by hediet** [comment]
> The debug adapter can't really do anything about this.

It can - it can trace back the variable to the variable declaration if it knew the location of the variable/expression the user hovered on.

> This is what the EvaluatableExpressionProvider is for. 

This can only set the hover range and the expression, but not really include information where the x is from (outer scope or inner scope).
Or do you mean the `EvaluatableExpressionProvider` should resolve the expression `x` to something like `x:4` (:4 referring to declaration of x in line 4) and `x:2` (referring to line 2) so that the evaluation request handler can use the modified expression to disambiguate the scopes?

**Comment by roblourens** [comment]
Ok I see what you have in mind

> It can - it can trace back the variable to the variable declaration if it knew the location of the variable/expression the user hovered on.

@connor4312 can js-debug do this?

**Comment by connor4312** [comment]
Not very well.

Today, js-debug intentionally never parses the AST of compiled code. We avoid doing this for performance reasons, since compiled bundles can be massive and slow. Implementing this would require parsing the bundle, having logic to determine variable scopes, and figuring out some mapping of what scopes each variable is in.

This would actually be useful to have for sourcemap renames (and I have a [WIP PR](https://github.com/microsoft/vscode-js-debug/pull/1548) that does this) but I'm not very eager to adopt it mainly for performance considerations. A few months ago I started work on a fork of the [es module lexer](https://github.com/guybedford/es-module-lexer) that could do a minimal subset of parsing to figure out scopes, but I didn't finish it, and it was never going to be a 100% correct implementation.

Then, with that, we can only actually evaluate a variable if we have a synchronous stackframe that is still in that scope. We can't access variables in scopes beyond an async boundary, nor can we access variables that are not used in the current stackframe (e.g. covered by shadowing) since V8 optimizes them away.

**Comment by hediet** [comment]
>  Implementing this would require parsing the bundle

Why would you need to parse the bundle? Cannot you use source-maps and a typescript language server plugin to reuse their information?

**Comment by hediet** [comment]
> nor can we access variables that are not used in the current stackframe (e.g. covered by shadowing) since V8 optimizes them away.

Not (always?) true:
![chrome_FoZ4fgLHOm](https://github.com/microsoft/vscode/assets/2931520/8633909e-77f9-4eb8-8538-a2a2059c8810)

Chrome confuses the variables on hover, but shows the correct value in the inline hint.

**Comment by connor4312** [comment]
> nor can we access variables that are not used in the current stackframe (e.g. covered by shadowing) since V8 optimizes them away... Not (always?) true

This is always the case, the inline hint was only shown when you made the stack frame on line 10 the current stackframe.

> Why would you need to parse the bundle? Cannot you use source-maps and a typescript language server plugin to reuse their information?

I prefer to parse the compiled code. Given a variable in another scope, the process we need to do is:

1. Map that location back to the compiled location, which we can easily do via sourcemaps
2. Figure out which stackframes, if any, would contain variables from that scope
3. Do some magic and pull the variable from those stackframes instead

An alternative would be

1. Parse the source code and figure out scopes in that code
2. Map those scopes back to the compiled code and the hover location back to the compiled code
3. 2 and 3 from above

I think that this is not as good for a few reasons:

- Mainly: we don't know if the source code is something we're able to parse. For example, users might be using newer or experimental language features, custom macros in a build system, or just languages or frameworks we can't parse by tossing into a JS/TS parser--such as Svelte files, Vue components, or the various more niche frameworks that compile another language to JS.
- If the compilation process changes or introduces new blocks that aren't in source code (such as downleveling iterators or async functions) I'm not sure what kind of results we'd get from looking at the source code that doesn't represent all the scopes.
- js-debug does not include TypeScript and is distributed as a standalone DAP server as well as in VS Code, so direct extension dependencies involve more complexity.

**Comment by DanTup** [comment]
@connor4312 was this done as part of https://github.com/microsoft/debug-adapter-protocol/issues/465, or was it only added to the DAP spec and not implemented in Code?

**Comment by connor4312** [comment]
Thanks for the ping, that was adopted in https://github.com/microsoft/vscode/pull/216551
