### ISSUE TITLE
[extension/debug/snippets] Cannot insert ${command:...} into a snippet.

### ISSUE THREAD

**Issue by kotborealis** [microsoft/vscode#186618]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.79.2
- OS Version: Ubuntu 20.04

Steps to Reproduce:

1. Create an extension with a debugger and `configurationSnippets` json section.
2. Populate snippet like this:
```json
"label": "(gdb) Attach to process",
"body": {
  "name": "(gdb) Attach to process",
  "process": "${command:pickRemoteProcess}"
}
```
3. Field `process` is treated as a placeholder, which is right. However, I want to insert this text literally. I've tried a number of combinations for escaping `$`, `{`, `}`, but none seem to work properly.
![image](https://github.com/microsoft/vscode/assets/6463851/a41a212d-4d7d-472a-b7b7-88e89ceb0bbb)

**Comment by roblourens** [comment]
https://stackoverflow.com/questions/42669459/vs-code-snippet-escape-file

https://code.visualstudio.com/docs/editor/userdefinedsnippets#_how-do-i-have-a-snippet-place-a-variable-in-the-pasted-script

**Comment by kotborealis** [comment]
![image](https://github.com/microsoft/vscode/assets/6463851/7b91a201-ee7b-4983-8e56-e29db7446f97)

@roblourens suggested answers do not work for this specific case.

![image](https://github.com/microsoft/vscode/assets/6463851/b898f2ee-9142-466b-af5a-e49446fd300e)

Increasing `\\` escapes does nothing.

However, it works properly with ordinary snippets:
![image](https://github.com/microsoft/vscode/assets/6463851/9b3588c2-8e43-4197-bcde-c9eb64626152)

I assume this might be a bug specific to debugger's `configurationSnippets`

**Comment by roblourens** [comment]
Sorry, there's an open issue for this https://github.com/microsoft/vscode/issues/176795
