### ISSUE TITLE
How to unignore extension recommends

### ISSUE THREAD

**Issue by babaric-dev** [microsoft/vscode#186690]
I accidentally clicked "dont show again" button in the "do you want to install recommends" prompt. It ignored extension recommendation for .c files and now I can't find the recommended extension again. There is no way to unignore the extension? I can't find it.

**Comment by gjsjohnmurray** [comment]
See #24815 for tips on how to do this, though it involves accessing VS Code's SQLite database directly.

@sandy081 rather than closing this immediately as a duplicate I'm pinging you to request that 6 year old issue gets some love soon.

**Comment by sandy081** [comment]
@gjsjohnmurray Thanks for pinging me. 

@bpasero I think this request is for you.

**Comment by bpasero** [comment]
We did not end up doing anything so far, so what else should happen here other than closing this as a duplicate? A component is free to provide a command to reset the choice, maybe that should be done here as a workaround.

**Comment by sandy081** [comment]
I would prefer to mark this as a dup instead of implementing it at component level unless this is highly asked request.

**Comment by gjsjohnmurray** [comment]
There were some good ideas in #144324 about providing a unified "Don't show this notification again" mechanism, which I think would be necessary before being able to offer a unified "unignore" mechanism. But that issue got closed after "do not disturb" was implemented by @daviddossett

**Comment by sandy081** [comment]
@gjsjohnmurray I do not think it is helpful to have this issue open and discuss about #144324 / #24815. 

@daviddossett @bpasero Up to you to reopen those issues and continue discussion there.
