### ISSUE TITLE
Extension page's text color doesn't change properly when system high contrast theme is turned on

### ISSUE THREAD

**Issue by alanrenmsft** [microsoft/vscode#186682]
Type: <b>Bug</b>

Steps to reproduce:
1. Open VSCode and select an extension
![image](https://github.com/microsoft/vscode/assets/13777222/da17c4e2-d3b8-43c0-b323-8f85f1093318)

2. Turn on system high contrast theme and observe the vscode theme is also changed
![image](https://github.com/microsoft/vscode/assets/13777222/55eaa50d-1809-441c-90df-1ee424401cfc)
![image](https://github.com/microsoft/vscode/assets/13777222/f9f7dc3c-37f6-4417-84bb-0eae211e66ab)

4. Change the VSCode theme to high contrast light
![image](https://github.com/microsoft/vscode/assets/13777222/9df7c092-6822-4d29-a7cd-2725eb497e76)

now the colors are inconsistent with the vscode theme.

VS Code version: Code 1.79.2 (695af097c7bd098fbf017ce3ac85e09bbc5dda06, 2023-06-14T08:57:04.379Z)
OS version: Windows_NT x64 10.0.22621
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.75GB (3.09GB free)|
|Process Argv|--crash-reporter-id 68eca69d-851b-4176-b2ee-ab655695d191|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (22)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-css-formatter|aes|1.0.2
vsc-organize-imports|alf|0.1.10
vscode-eslint|dba|2.4.2
gitlens|eam|14.0.1
EditorConfig|Edi|0.16.4
vs-code-xml-format|fab|0.1.5
copilot|Git|1.93.189
vscode-azurefunctions|ms-|1.11.0
vscode-azureresourcegroups|ms-|0.7.5
csharp|ms-|1.26.0
sqlops-debug|ms-|1.4.0
isort|ms-|2022.8.0
python|ms-|2023.10.1
vscode-pylance|ms-|2023.6.40
jupyter|ms-|2023.5.1101742258
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.15
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-slideshow|ms-|0.1.5
azure-account|ms-|0.11.5
js-debug-nightly|ms-|2023.6.2117
code-spell-checker|str|2.20.5

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
py29gd2263:30776702
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
282f8724:30602487
pyind779:30671433
89544117:30613380
pythonsymbol12:30671437
showlangstatbar:30737416
vsctsb:30748421
pythonms35:30701012
03d35959:30757346
pythonfmttext:30731395
pythoncmv:30756943
fixshowwlkth:30771522
pythongtdpath:30769146
i26e3531:30769768
pythonidxpt:30772539
pythondjangots:30772535
pythonnocebcf:30776496

```

</details>

**Comment by heysujal** [comment]
@mjbvz Can you assign me this issue ? I would like to work on it.

**Comment by Cyddharth-Gupta** [comment]
@mjbvz can I be assigned for this issue, even though this is in backlog?

**Comment by adway7103** [comment]
Please assign me thiis issue i feel that i can do this.  i want to start my opensource journey with this projject

**Comment by balaji-sivasakthi** [comment]
Hey @Cyddharth-Gupta @adway7103, I also want to work this issue.

**Comment by Cyddharth-Gupta** [comment]
@balaji-sivasakthi I have not been assigned, check the assignees

**Comment by balaji-sivasakthi** [comment]
Ok

**Comment by mjbvz** [comment]
We generally do not assigned community members to issues. If you want to work on this, just say you are doing so in a comment and then submit a PR

**Comment by Cyddharth-Gupta** [comment]
@mjbvz thanks for clarifying

**Comment by JaGPR** [comment]
@Cyddharth-Gupta @mjbvz i am aslo new to open source and would love to contribute .

**Comment by balaji-sivasakthi** [comment]
@mjbvz I'm working on it.

**Comment by balaji-sivasakthi** [comment]
Yeah I did

**Comment by heysujal** [comment]
> Yeah I did

can you share the process? I followed the docs but I kept getting errors and deleted the fork, but now I want to give it another try.

**Comment by balaji-sivasakthi** [comment]
Fork the repo and then install dependencies with `yarn` then press `ctrl+shift+B`

**Comment by heysujal** [comment]
> Fork the repo and then install dependencies with `yarn` then press `ctrl+shift+B`

No luck, when I run `yarn` I get an error 
 C:\Users\sujal\Desktop\vscode\node_modules\@vscode\spdlog: Command failed.

**Comment by balaji-sivasakthi** [comment]
Could you please, Share your node and npm version ?

**Comment by heysujal** [comment]
![image](https://github.com/microsoft/vscode/assets/55016909/4ae292eb-2d89-4ca1-a803-1e09c7bc48db)


I downgraded my npm version as I saw a GitHub discussion for some error fixes.

**Comment by balaji-sivasakthi** [comment]
> I downgraded my npm version as I saw a GitHub discussion for some error fixes.

I'm using,
- node version (v18.12.1)
- npm version (8.19.2)

**Comment by heysujal** [comment]
@balaji-sivasakthi  I wonder how were you able to set it up as [contribution guidelines mentions to use a older node version.](https://github.com/microsoft/vscode/wiki/How-to-Contribute#prerequisites)
Also, if you don't do that you get an error or warning. That's why I downgraded my node version.

**Comment by balaji-sivasakthi** [comment]
> Also, if you don't do that you get an error or warning. That's why I downgraded my node version.
> Should I give it a try by upgrading node and npm again?

No, Use `version >=16.17.x and <17`

**But I haven't seen any errors! It may be compatible with my machine.**

**Comment by balaji-sivasakthi** [comment]
@mjbvz  Why? I'm so getting empty extensions here!, How can I seed the hard-coded data or get the data.

![Screenshot (336)](https://github.com/microsoft/vscode/assets/65065614/a7f782ba-795f-47d9-9f55-5218846e7c32)

**Comment by balaji-sivasakthi** [comment]
@mjbvz Could you help me resolve this issue? Where do I start?

**Comment by code-4-bread** [comment]
@alanrenmsft Unable to reproduce on `Version: 1.80.1 (Universal)`. Can you confirm if it has been resolved? Thanks.

**Comment by balaji-sivasakthi** [comment]
![image](https://github.com/microsoft/vscode/assets/65065614/f54bbcca-0652-406f-b689-fdb64ccdce90)

@code-4-bread I've not been resolved yet, `version: 1.80.2`

**Comment by balaji-sivasakthi** [comment]
![google](https://github.com/microsoft/vscode/assets/65065614/f64a69dc-2556-4ef6-a014-d00ab4c1f49a)

How can we change the background color when the system has a dark high contrast and VSCode has a light contrast? 
Is this possible?

**Comment by balaji-sivasakthi** [comment]
![image](https://github.com/microsoft/vscode/assets/65065614/a50b3f17-93fe-4571-b348-20398e832af5)
@alanrenmsft Is this ok now?

**Comment by code-4-bread** [comment]
> ![image](https://user-images.githubusercontent.com/65065614/256714914-f54bbcca-0652-406f-b689-fdb64ccdce90.png)
> 
> @code-4-bread It hasn't been resolved yet. The current version is `1.80.2.`

My bad, seems Window specific issue. I am on Mac.

**Comment by balaji-sivasakthi** [comment]
@code-4-bread Oh! Alright, did you figure it out, how to resolve it?

**Comment by code-4-bread** [comment]
> @code-4-bread Oh! Alright, did you figure it out, how to resolve it?

I am not sure.

**Comment by balaji-sivasakthi** [comment]
> I am not sure.

I've reproduced this issue by using dev tools. It has been applied by running it emulated with `forces color: active`. I think we can resolve this by emulating events API. What do others think about it? Is this a good way of using it?

**Comment by VatsalBhuva11** [comment]
no issues in ubuntu. 
![image](https://github.com/microsoft/vscode/assets/66008435/44c5c812-38e9-4403-9065-fe1c6151ff77)

**Comment by balaji-sivasakthi** [comment]
@VatsalBhuva11 
Help -> Toggle Developer Tools -> Ctrl + Shift + P
Search -> Emulate CSS forced-colors: active
Kindly try this in ubuntu and confirm it.

**Comment by VatsalBhuva11** [comment]
@balaji-sivasakthi 
Yes, it does seem like an issue in ubuntu as well.
![image](https://github.com/microsoft/vscode/assets/66008435/9d8fb54d-0e1a-48c8-8434-80ee99af1d50)

**Comment by balaji-sivasakthi** [comment]
@VatsalBhuva11 You've any idea to resolve this issue?
