### ISSUE TITLE
editor.insertSpaces: auto always inserts spaces in new files

### ISSUE THREAD

**Issue by SamVerschueren** [Microsoft/vscode#1866]
The `editor.insertSpaces` setting can autodetect if it should insert spaces or tabs. Some people like tabs more then spaces, but it's just personal preference.

I think in Code < 0.10 it inserted tabs when the setting was set to `auto`. In Code >= 0.10 it changed to spaces. I'm more a tab guy, except for `json` files. So that's why I don't want to set it to `false` because I would have to change it forth and back when in a JSON file.

The setting should not be reverted, but maybe an extra setting like `editor.insertSpacesDefault` which can only be set to `true` and `false` and has a default of `true` (to not break the current behaviour). If `editor.insertSpaces` is set to `auto` and a new file is created, it will check the `editor.insertSpacesDefault` setting.

@alexandrudima I guess you are the person for this as you wrote the tests regarding the `insertSpaces` autodetect :)

**Comment by Tyriar** [comment]
This is a duplicate of https://github.com/Microsoft/vscode/issues/1747

The change in question was made in https://github.com/Microsoft/vscode/issues/498

**Comment by SamVerschueren** [comment]
Aha, thanks @Tyriar . Missed that one.
