### ISSUE TITLE
Diffs For Deleted Files Is Not Great

### ISSUE THREAD

**Issue by hediet** [microsoft/vscode#186648]
[Repro](https://microsoft.github.io/monaco-editor/playground.html?source=v0.40.0-dev.20230629#XQAAAALvBQAAAAAAAABBqQkHQ5NjdMjwa-jY7SIQ9S7DNlzs5W-mwj0fe1ZCDRFc9ws9XQE0SJE1jc2VKxhaLFIw9vEWSxW3yscw9zsK1_7RaxvTpxkYn3V-u8LX9aoCz6W93JdE-E7gNRYqv4Nj7ofd3sXvMZS3Q7wGKETF2-D42O7I090YntPzuUtCYa-4cDJgFEOuR5W1ivQxZGNLFM0Lhb3UbKd8Yxu3eP17Xy8lzTiuVLaAWjuU-Lzvbp0aRJeJoSvfODtCuN-hO1Q8cjQO20MKeJuVxmfQgfo-0H9LumAGHHOsdflVS2psk9ynS9VVp5y0ZqFOFkhZQXL2I6o65XapRzve6tenixCk1InAFL7zVmkS6HM0HOexjmOOAK3SIhvDc3zxRBmecpr4ltxrCVoApC3mLA2KmYYWHipFCH-N-kgR_mwHM7p6aysPRe-0zJ6Ok8OKsAUmD87DmgdsEU3fHtFG6SKbxaqC0XNtlJRKGL3r-2Dog00NH4JMMz5rbyBhGv1JnqCeuUFW3ANVBwA-VEps3TeOPSmh8cWk9XbHcHz7zrKLu5HT4qiQ52MjJAjZpkXbRtygIoIRbqJetzvsIdOIkAUYQlulL1hnzqD84_3MI6QfW3gpqkSl0_UNIuIRPRLMUBsxPe13U2dCXJfhJf6v4dzm0iuziPOv593fuU-RFBXWvZzZLCfbI7Pvk69ve3aLF8PhjutVuS0sUqX9foIwADaRitWon7fLJxjrTvuuRQn4SoHAK66cWSLpAj9ds2gQnYSHcNbZeUV2WnXoNt8a2TAGhaUF-4_mFWW1iEC6MWZF1A0E73MaEjvamtNPLZYr-9mHivhBEOIQAKzBGxTY0KWgsr_7tMR0htgChuVSla2SXytKovmeJZh4dI_zUcNtKsX3k85z9r5np1zlRYqLRnEEdSMbIyR4_RLeP1Kx6emSkKd99N41Zb49NrXW9SfuSGS4Z9DQ_OJIbIYLeYads0d2LaPWlDb0vWdfhgZPPogN3__amaly) (verify in latest dev release)

![chrome_MNbMaDZTMM](https://github.com/microsoft/vscode/assets/2931520/e6bce998-593e-461d-8955-f26cc5b839d9)

**Comment by joyceerhl** [comment]
This is what I see now ([playground link](https://microsoft.github.io/monaco-editor/playground.html?source=v0.41.0-dev.20230719#XQAAAALvBQAAAAAAAABBqQkHQ5NjdMjwa-jY7SIQ9S7DNlzs5W-mwj0fe1ZCDRFc9ws9XQE0SJE1jc2VKxhaLFIw9vEWSxW3yscw9zsK1_7RaxvTpxkYn3V-u8LX9aoCz6W93JdE-E7gNRYqv4Nj7ofd3sXvMZS3Q7wGKETF2-D42O7I090YntPzuUtCYa-4cDJgFEOuR5W1ivQxZGNLFM0Lhb3UbKd8Yxu3eP17Xy8lzTiuVLaAWjuU-Lzvbp0aRJeJoSvfODtCuN-hO1Q8cjQO20MKeJuVxmfQgfo-0H9LumAGHHOsdflVS2psk9ynS9VVp5y0ZqFOFkhZQXL2I6o65XapRzve6tenixCk1InAFL7zVmkS6HM0HOexjmOOAK3SIhvDc3zxRBmecpr4ltxrCVoApC3mLA2KmYYWHipFCH-N-kgR_mwHM7p6aysPRe-0zJ6Ok8OKsAUmD87DmgdsEU3fHtFG6SKbxaqC0XNtlJRKGL3r-2Dog00NH4JMMz5rbyBhGv1JnqCeuUFW3ANVBwA-VEps3TeOPSmh8cWk9XbHcHz7zrKLu5HT4qiQ52MjJAjZpkXbRtygIoIRbqJetzvsIdOIkAUYQlulL1hnzqD84_3MI6QfW3gpqkSl0_UNIuIRPRLMUBsxPe13U2dCXJfhJf6v4dzm0iuziPOv593fuU-RFBXWvZzZLCfbI7Pvk69ve3aLF8PhjutVuS0sUqX9foIwADaRitWon7fLJxjrTvuuRQn4SoHAK66cWSLpAj9ds2gQnYSHcNbZeUV2WnXoNt8a2TAGhaUF-4_mFWW1iEC6MWZF1A0E73MaEjvamtNPLZYr-9mHivhBEOIQAKzBGxTY0KWgsr_7tMR0htgChuVSla2SXytKovmeJZh4dI_zUcNtKsX3k85z9r5np1zlRYqLRnEEdSMbIyR4_RLeP1Kx6emSkKd99N41Zb49NrXW9SfuSGS4Z9DQ_OJIbIYLeYads0d2LaPWlDb0vWdfhgZPPogN3__amaly))

![image](https://github.com/microsoft/vscode/assets/30305945/d6c690f3-f0f9-4111-9655-e4941e3c6126)
