### ISSUE TITLE
Toggle Inline Diff not discoverable in inline chat

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode#186644]
Followup to https://github.com/microsoft/vscode/issues/185040#issuecomment-1612399427

I spent quite some time messing with the inline chat preview mode setting to get the diff to appear, without success. It didn't occur to me to look in the Discard dropdown for the Toggle Inline Diff action, since I don't associate diffing with discarding. Have we considered surfacing this another way, maybe as a separate icon or through a keybinding with some helper text below the result?

**Comment by jrieken** [comment]
Totally valid. I moved it into the menu to reduce visual noise. Maybe a cog wheel after the feedback buttons would be helpful. Or have this just as a setting and don't expose it directly in the UI

**Comment by martinwoodward** [comment]
I definitely went into settings.json first to try and figure out why it wasn't showing up on one machine but was in another...  Only discovered the option existed by searching here first :) 

<img width="1062" alt="toggle diff in drop down" src="https://github.com/microsoft/vscode/assets/856858/9b0e4047-9fe9-4f8b-b407-39aa85ce684f">

**Comment by jrieken** [comment]
Let's make it a setting and let's start with a context menu that allows to tweak settings in place (this is IMO better than a cog wheel and similar to other places like breadcrumbs, stickyscroll, or minimap)

**Comment by aiday-mar** [comment]
To verify:

- Verify that in the discard menu you no longer see `Show Diff`
- Enable the setting `inlineChat.showDiff`
- Verify that when the setting is enabled, you see a diff when generating text edits (for live and livePreview mode, but not preview)
- Disable the setting, verify you no longer see the diff
- Right-click on the inline chat, verify that you can enable and disable the diff from the context menu that appears

**Comment by hediet** [comment]
I can verify the implementation, but I find the context menu very hard to discover.
I'd prefer a cog wheel, but maybe it only makes sense when there are more settings to tweak than just hiding/showing the diff.
