### ISSUE TITLE
Git (SCM) issues in latest insiders

### ISSUE THREAD

**Issue by eamodio** [Microsoft/vscode#18665]
- VSCode Version: `1.9.0-insider` f67f87c5498d9361c0b29781c341fd032815314b
- OS Version: macOS Sierra `10.12.2`

The new SCM changes seem to have lost a bunch of functionality as well as caused some bugs.

Bugs:
- The SCM icon (hopefully it is temporary) doesn't show any badge (count) until you open it.
- Can't open a file diff (from the SCM pane) with [GitLens](https://marketplace.visualstudio.com/items?itemName=eamodio.gitlens) installed -- throws errors. I will take a look into this, but I mention it mainly because it could break a bunch of users until I get an update out. -- EDIT: I've pushed a new version of GitLens that fixes the issue (I was using a DocumentScheme of `git` it is now `gitlens-git`)

Missing features:
- Commit button is missing
- Many missing Git commands from the content menu (pull, push, etc)
- File diff is missing toggle back (and forth) to the file
- Staging lines -- was an AWESOME feature (would have been nice to even be more prominent)
- Commit message length notification

**Comment by DuncanBeard** [comment]
Thanks for updating GitLens - fixed the errors for me.

**Comment by joaomoreno** [comment]
Much thanks for the summary, but it's always better to file each issue independently. 👍 

Some of these are already fixed, some are dupes, others tracked here: #18615.

**Comment by eamodio** [comment]
@joaomoreno will do next time -- just didn't want to create a ton of noise. Thanks!
