### ISSUE TITLE
Enable a repository for Debian/Suse/RedHat family

### ISSUE THREAD

**Issue by RafaelAybar** [Microsoft/vscode#18668]
I think that enable an official repository will be a great idea, because you dont need to implement auto update. I can add your repository and upgrade my vs-code and all my software with ```apt update && apt upgrade``` instead download .deb or .rpm

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/229 https://github.com/Microsoft/vscode/issues/2973
