### ISSUE TITLE
Markdown paste pastes inside of a link

### ISSUE THREAD

**Issue by TylerLeonhardt** [microsoft/vscode#186668]
I was trying to paste a link into `[product.json](HERE)` but when I did it pasted as a full link:

<img width="742" alt="image" src="https://github.com/microsoft/vscode/assets/2644648/d22998ff-082e-4e00-b7d6-520421d4cac6">

This feature should be smart enough to not do this if I'm already in a link.

**Comment by MeghanKulkarni** [comment]
I believe this issue also covers not pasting inside a link: https://github.com/microsoft/vscode/issues/186289
Matt suggested working making the feature smarter in a future iteration!
