### ISSUE TITLE
Opened editors: file names no longer align to explorer

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#18667]
With the recent CSS changes, the file labels in opened editors no longer perfectly align with the explorer:

![image](https://cloud.githubusercontent.com/assets/900690/22026524/5479bd10-dcd1-11e6-9680-232f78a259a8.png)

**Comment by bpasero** [comment]
Actually a lot worse once icons are enabled:

![image](https://cloud.githubusercontent.com/assets/900690/22026581/83e93742-dcd1-11e6-96d0-eacb9190c3b3.png)

**Comment by bpasero** [comment]
Here is how it used to look in stable:

![image](https://cloud.githubusercontent.com/assets/900690/22026595/8f845104-dcd1-11e6-9a6c-81cb75ae3db0.png)

![image](https://cloud.githubusercontent.com/assets/900690/22026610/9aab763e-dcd1-11e6-8034-44a457c36d13.png)

**Comment by isidorn** [comment]
@aeschli do you plan to look into this? Let me know if not.
Code pointer https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/files/browser/views/openEditorsView.ts#L107

**Comment by bpasero** [comment]
I can also if any of you are running out of time.

**Comment by isidorn** [comment]
Take it easy cowboy 
Maybe Martin is already fixing since he is in this area. If not I will fix it.

**Comment by bpasero** [comment]
Spoken like a calm Zen master 👍

**Comment by isidorn** [comment]
@bpasero ok I have aligned the open editor with the explorer in the case where there are no icons.

If we want to align it in the case where there are icons then it will look like this. Notice that open editors do not look like children of LEFT. We can go this way which I think is confusing or we can
1. not show icons in the open editors view
2. not be aligned when there are icons
Other suggestions also welcome

![screen shot 2017-01-18 at 17 10 42](https://cloud.githubusercontent.com/assets/1926584/22071943/0b81afca-dda1-11e6-8b50-dfabd305b565.png)

**Comment by bpasero** [comment]
@isidorn I see the problem with the icons. I am fine with closing since you fixed it for the non icon case and it still looks good for themes that have folder icons 👍

**Comment by isidorn** [comment]
Yeah, let's go with that for now.
