### ISSUE TITLE
Ensure 'configurationEditingService.doWriteConfiguration' flushes to disk before a window reload.

### ISSUE THREAD

**Issue by JimiC** [Microsoft/vscode#18660]
- VSCode Version: 1.81 ~ 1.9.0 (insiders)
- OS Version: Win10

Steps to Reproduce:

1. Call `vscode.workspace.getConfiguration().update('someSetting', value);` to update a configuration value on disk.
2. Call `vscode.workspace.getConfiguration().update('someOtherSetting', value);` to update another configuration value on disk.
3. Immediately call `vscode.commands.executeCommand('workbench.action.reloadWindow');` to trigger window reload.
4. Notice only first setting gets updated.

The reason seems to be that the app doesn't wait for the `queue` to get flushed before reloading.

My current workaround is to introduce a delay before reloading in order for the updates to get persisted on disk.

**Comment by dbaeumer** [comment]
@sandy081 starting with you since I know you are doing work there right now. If not you please move on.

**Comment by sandy081** [comment]
@JimiC `vscode.workspace.getConfiguration().update()` returns a `Thenable`. It means it is an async request. You can chain your code in the return `Thenable` instead of introducing delays/timeouts.

**Comment by JimiC** [comment]
@sandy081 That's the issue. Even when inside the `Thenable` I have to introduce a delay/timeout. Please don't close issues without investigation.

**Comment by sandy081** [comment]
@JimiC Sorry for closing the issue. I was guessing that you are not using `Thenable` as I do not see it in the description. Hence closed that this would help you in fixing your problem. If `Thenable` is not working, then it is a bug which I will investigate. Thanks for confirming.

**Comment by JimiC** [comment]
@sandy081 Here is a [code sample](https://github.com/vscode-icons/vscode-icons/blob/master/src/init/autoDetectProject.ts#L85) where I'm forced to introduce a delay.

**Comment by sandy081** [comment]
@JimiC I used a sample extension which does same as you mentioned in the description

```typescript
vscode.workspace.getConfiguration().update('editor.fontSize', 12, true)
            .then(() => vscode.workspace.getConfiguration().update('workbench.statusBar.visible', false, true))
            .then(() => vscode.commands.executeCommand('workbench.action.reloadWindow'));
```

And after reload both the changes are applied and there is no delay added. I tried with insiders. Let me know if I am missing something here

**Comment by JimiC** [comment]
@sandy081 I'll have it checked again.

**Comment by JimiC** [comment]
@sandy081 I can confirm that it's indeed working correctly. I swear it wasn't working when I opened the issue. Maybe it got fixed along the way.

What I spotted though is that if I change the setting and then try to load it again by `vscode.workspace.getConfiguration()` the updated value isn't returned. Do we get the updated value in another way?

**Comment by sandy081** [comment]
@JimiC Yeah there were some changes in config edit service.. may be some of them got fixed it (not sure).

Regarding not getting the updated value after update is due to the delay in our side. I will fix that using this issue.

**Comment by sandy081** [comment]
@JimiC I think you can listen to `vscode.workspace.onDidChangeConfiguration` event that will trigger configuration update. This will make your flow correct instead of having delays in your code. I understand `vscode.workspace.getConfiguration()` is not retrieving latest value after update but we trigger an event when there is an update. 

Let me know if this works out for you?

**Comment by JimiC** [comment]
@sandy081 Thanks for the advice. Yeah, `vscode.workspace.onDidChangeConfiguration` will ensure that the flow continues only when the configuration got updated. Unfortunately, we are depending on re-reading configuration values in order to trigger some specific process. I'll keep looking into this on our side.

**Comment by sandy081** [comment]
Thanks @JimiC. I would be closing this for now. Please reopen it if needed.
