### ISSUE TITLE
Cannot read property 'windows' of null

### ISSUE THREAD

**Issue by neilyoung** [Microsoft/vscode#18669]
- VSCode Version: Version 1.9.0-insider (1.9.0-insider) f67f87c5498d9361c0b29781c341fd032815314b
2017-01-17T07:02:22.533Z
- OS Version:
Mac OSX Sierra

Steps to Reproduce:

1. Create an Node JS server and run it
2. Hit 'Restart'

**Comment by isidorn** [comment]
Can not reproduce. I tried running our vscode smoke test sample https://github.com/Microsoft/vscode-smoketest-express and hitting restart, everything works fine.

@neilyoung do you reproduce this for any node js server. Can you please provide a workspace for which you see this so we can try reproducing it on our end.

**Comment by neilyoung** [comment]
Maybe this helps: Usually once I hit debug VSCode asks me to create a launch configuration. Not in this case. Basically I can start debugging w/o any launch.json. The debugger starts, but if I restart the a.m. error appears.

I was creating a launch.json now from the menu. The file created contains a wrong entry:

`			"program": "${workspaceRoot}/${workspaceRoot}/index.js",
`

Note the double workspaceRoot

Once I remove that, I can restart w/o any problem.

For me there are two new issues now, whereas the initial problem is gone:

1) Why can I start debugging w/o having a launch.json?
2) Why is my launch.json corrupted?

**Comment by isidorn** [comment]
@neilyoung great finding! I am able to reproduce it, will fix it today so you can check tomorrow's insiders for improvments.

As for the corrupeted launch.json - I can reproduce this behavior and have created an issue https://github.com/Microsoft/vscode/issues/18723
You can start debugging w/o having a launch.json becaue we are trying to simplify starting of a debug session for users. More about it can be found here https://github.com/Microsoft/vscode/issues/285

**Comment by isidorn** [comment]
To verify:
1. Start debugging without a 'launch.json'
2. Hit restart -> should work

**Comment by neilyoung** [comment]
Cool :)
