### ISSUE TITLE
In LIVE SHARE the active participants are not seen

### ISSUE THREAD

**Issue by xperticia** [microsoft/vscode#186632]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.79.2
- OS Version: Linux x64 5.19.0-45-generic

I use the LIVE SHARE extension, and while programming in parallel with a colleague, I shared the collaboration link with him. It accesses normally, but after a few moments, I want to keep track of where it is working, but it is not visible as a participant in the "SESSION DETAILS" section, but I do notice that it opens files, modifies them and saves normally.
Just in case, I haven't shared the link with anyone else.
Obviously this is a very serious security or control problem.

**Comment by joyceerhl** [comment]
This is caused by the Live Share extension so I have cross-filed it as https://github.com/MicrosoftDocs/live-share/issues/4944
