### ISSUE TITLE
Markdown pasting is forcing url  to be encoded 

### ISSUE THREAD

**Issue by luabud** [microsoft/vscode#186685]
Does this issue occur when all extensions are disabled?: Yes

![image](https://github.com/microsoft/vscode/assets/45497113/d0b55ad6-5c83-4b93-ae0a-f46b037c39b6)

Steps to Reproduce:

1.  Copy this url: https://marketplace.visualstudio.com/items?itemName=ms-python.debugpy
2.  Open a markdown file
3. Paste the url

It becomes `https://marketplace.visualstudio.com/items?itemName%25253Dms-python.debugpy`

![markdown-url-encoding](https://github.com/microsoft/vscode/assets/45497113/4489e09b-bc90-44a7-8a47-1f2176cb4b6f)

**Comment by bhavyaus** [comment]
Verified on build: 
Version: 1.80.0-insider
Commit: 5b7440441bbd2548a862f7321cafdfa1597132e5
![Recording 2023-06-30 at 15 43 59](https://github.com/microsoft/vscode/assets/25044782/bf9f78de-3d3f-4fd5-98df-43290650f5cb)
