### ISSUE TITLE
Sticky scroll for screen reader users

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#186659]
Sticky scroll is a feature that allows sighted users to understand the nested context that they are in. 

@kieferrm suggested it would be cool if we had this for screen reader users. 

Imagine you jump to a line where there's a problem reported. You invoke a command which provides context - what class you are in, the function signature, the conditional, etc. 

cc @rperez030 and @jooyoungseo

**Comment by rperez030** [comment]
I would love to understand the visual experience better. I often use commands such as "focus on outline view" for context, but maybe there is a better way. Understanding context certainly can be a challenge.

**Comment by meganrogge** [comment]
Yes, sticky scroll allows users to see their current context in the current view - even when the class or function is defined far above the current line. 

Example:

line 1: class Telephone
line 2...36
line 37 function _createCall()
line 38....64
line 65 if _cellNumber === 10
line 65...80
line 81 (current line) x += 8.

Before sticky scroll, only lines 65 through 81 would be in the view, so the context of those things was lost.

With sticky scroll for sighted users, here's the view
class Telephone
function _createCall()
if _cellNumber === 10
      (current line) x += 8.

so, for SR users, we could have a command which allows you to hear the current context like "in class telephone, function createCall, condition _cellNumber === 10"

**Comment by jooyoungseo** [comment]
@meganrogge what is the current issue? I have been using Sticky Scroll with JAWS and NVDA without challenges.

**Comment by jooyoungseo** [comment]
FYI, I have assigned the following keybindings:

``` json
[
  {
    "key": "ctrl+k ctrl+;",
    "command": "editor.action.focusStickyScroll"
  }
]
```

**Comment by meganrogge** [comment]
Oh that is very cool 😄 I had not realized one could focus the components of sticky scroll. It works well. Thanks for pointing this out @jooyoungseo

**Comment by jooyoungseo** [comment]
For those using screen reader and visiting this thread later, I have additionally configured the following settings:

`settings.json`:

``` json
{
  "editor.stickyScroll.enabled": true,
  "editor.stickyScroll.defaultModel": "foldingProviderModel"
}
```

**Comment by aiday-mar** [comment]
Hey @meganrogge, my apologies, the focusing behavior was there for a couple of iterations already. I forgot to inform this thread of its existence.

**Comment by rperez030** [comment]
@jooyoungseo , thanks a million! I had no idea sticky scroll even existed. These are the things I wish were better documented. Thanks @meganrogge  for explaining it. I will definitely play with this when I'm back from vacation. Thank you all.

**Comment by jvesouza** [comment]
@jooyoungseo  Thank you very much, I was just looking for this.

**Comment by meganrogge** [comment]
@aiday-mar this is a very useful feature - are there plans to enable it by default? If so, we can then add info about how to use it to the editor's help menu

**Comment by aiday-mar** [comment]
Hi @meganrogge, focusing can be done directly through the command palette, without the need for a setting configuration. 

Do you mean perhaps, adding a setting to focus directly on sticky scroll when it appears?

**Comment by meganrogge** [comment]
@aiday-mar for me, sticky scroll is off by default.

<img width="611" alt="Screenshot 2023-07-12 at 8 05 01 AM" src="https://github.com/microsoft/vscode/assets/29464607/5e4384e4-3e87-4936-8f33-eec36fec9325">

**Comment by aiday-mar** [comment]
Ah I see, I misunderstood. I can make a PR to enable sticky scroll when screen reader optimization is on, by default.
