### ISSUE TITLE
Please update native-is-elevated package

### ISSUE THREAD

**Issue by montoner0** [microsoft/vscode#186606]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.79.2 (user setup)
- OS Version: Windows 10 22H2

To fix the issue #173698 please update the native-is-elevated package. It was fixed two months ago.

**Comment by bpasero** [comment]
Could you maybe verify using our insiders? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by montoner0** [comment]
It seems working properly now. Thanks!
