### ISSUE TITLE
terminal path can't be detected when endsWith `.`

### ISSUE THREAD

**Issue by tjx666** [microsoft/vscode#186661]
@Tyriar 

<img width="1440" alt="image" src="https://github.com/microsoft/vscode/assets/41773861/974e504d-2b6c-49c5-8707-e7d5ed57611d">

path:

```bash
/Users/yutengjing/code/leetcode-javascript-2023/tests/0083-remove-duplicates-from-sorted-list.test.js.
```

```
Version: 1.79.2
Commit: 695af097c7bd098fbf017ce3ac85e09bbc5dda06
Date: 2023-06-14T08:58:33.551Z
Electron: 22.5.7
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Darwin arm64 22.5.0
```

**Comment by Tyriar** [comment]
@tjx666 thanks again for all these reports, these are great!

**Comment by DonJayamanne** [comment]
@rebornix @amunger we had a similar issue with outputs in Jupyter extension, still looking for that.
Looks like we've fixed the same issue in terminals, as well.
