### ISSUE TITLE
Stepping via commands in the Debug Console moves focus out of Debug Console

### ISSUE THREAD

**Issue by rehmsen** [microsoft/vscode#186634]
Does this issue occur when all extensions are disabled?: I am not sure one can step from the Debug Console without any extensions - but the focus grabbing seems to happen when you step via other means, too - it's just less disruptive.

- VS Code Version: 1.79.2
- OS Version: macOS Ventura 13.4.1

Steps to Reproduce:

1. Start a debug session, for example for C++ with LLDB, add a breakpoint, wait until the execution is paused.
2. Type "`n" into the Debug Console. The backtick is to escape from VSCode's default to interpret the input as expression and instead send a command to LLDB. The "n" stands for "next". 

Expected:

It will make the step, and keep the focus in the Debug Console, so that I can type the next command (maybe another "n").

Actual:

It will make the step, but move the focus into the editor in the new line you stepped to. If you type n again, it will type into the editor. This behavior makes it super cumbersome to use the debugger with traditional LLDB//GDB commands.

**Comment by ashgti** [comment]
`"debug.focusEditorOnBreak": false,` should resolve this I think

**Comment by roblourens** [comment]
Yes, there are pros and cons for this so the user setting lets you configure it to your preference
