### ISSUE TITLE
Find in files no go to next/previous match by keyboard

### ISSUE THREAD

**Issue by BillDenton** [Microsoft/vscode#18674]
- VSCode Version: Code 1.8.1 (ee428b0eead68bf0fb99ab5fdc4439be227b6281, 2016-12-19T14:49:23.350Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions:

|Extension|Author|Version|
|---|---|---|
|read-only-indicator|alefragnani|0.4.0|
|alignment|annsk|0.3.0|
|Doxygen|bbenoist|1.0.0|
|python|donjayamanne|0.5.6|
|EditorConfig|EditorConfig|0.3.4|
|vscode-great-icons|emmanuelbeziat|1.1.38|
|matlab|Gimly81|0.4.0|
|status-bar-tasks|GuardRex|0.1.2|
|vscode-dimmer|hoovercj|2.1.0|
|docthis|joelday|0.3.9|
|cpptools|ms-vscode|0.9.3|
|vscode-clearcase|OpenNingia|1.4.1|
|vscode-icons|robertohuertasm|7.0.1|
|theme-cyanicpastels|SamuelLampa|0.0.9|
|indenticator|SirTori|0.2.1|
|vscode-hexdump|slevesque|1.1.4|
|code-spell-checker|streetsidesoftware|0.14.6|
|comment-snippets|Tobiah|0.2.0|
|dark-plus-material|vangware|0.1.4|
|change-case|wmaurer|1.0.0|
|highlight-trailing-white-spaces|ybaumes|0.0.2|

---

Steps to Reproduce:

1. Ctrl+shift+f enter search string, etc.
2. Get a list of matches.
3. Select one of them.
4. How to get to the next/previous only using the keyboard?

**Comment by mjbvz** [comment]
I believe that @roblourens just added this feature. You can try it out in insiders builds using <kbd>f4</kbd> and <kbd>f4</kbd><kbd>shift</kbd>

The commands for keybindings are:
`search.action.focusNextSearchResult`
`search.action.focusPreviousSearchResult`

**Comment by BillDenton** [comment]
Thanks. I've confirmed it works the preview build. Will check in release when it arrives. I note that there is a clash with the C++extension  (see #18679).
