### ISSUE TITLE
ctrl+e in editor accessibility help doesn't update help text

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#186722]
1. Focus in an editor
2. Command: Open Accessibility Help
3. Notice that the help says ctrl+e will set the editor to be screen reader optimized. Do ctrl+e.
4. I can see in the status bar that "Screen Reader Optimized" is now on ✅
5. But the accessibility help still says that it is not optimized and that I can uses ctrl+e to enable it.

**Comment by meganrogge** [comment]
fixed this in a PR yesterday
