### ISSUE TITLE
Exceeded machine limit for port forwarding when trying to create tunnel

### ISSUE THREAD

**Issue by aehampton99** [microsoft/vscode#186769]
<img width="1031" alt="Screenshot 2023-06-30 at 1 53 46 PM" src="https://github.com/microsoft/vscode/assets/75088436/31e77b3e-27a7-460f-93f2-433b690d0ea9">
<img width="939" alt="Screenshot 2023-06-30 at 11 11 48 AM" src="https://github.com/microsoft/vscode/assets/75088436/cc1003ef-388f-408e-a8d2-c61e43ad1966">

PROCESS: 

> ssh anna.hampton@hpg.rc.ufl.edu
> ssh login2
> module load tmux
> tmux attach
> srundev --mem=50gb --ntasks=1 --cpus-per-task=1 --time=12:00:00
> module load conda jupyter; export XDG_RUNTIME_DIR=${SLURM_TMPDIR}; code tunnel

**Comment by connor4312** [comment]
Duplicates https://github.com/microsoft/vscode-remote-release/issues/8618
