### ISSUE TITLE
Extension 'github.vscode-pull-request-github' wants API proposal 'treeItemCheckbox' but that proposal DOES NOT EXIST

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#186723]
1. Install latest pre-release version of GH PR
2. Have VS Code Insiders
3. Open Developer Tools. Notice error in console:

`Extension 'github.vscode-pull-request-github' wants API proposal 'treeItemCheckbox' but that proposal DOES NOT EXIST. Likely, the proposal has been finalized (check 'vscode.d.ts') or was abandoned.`

**Comment by alexr00** [comment]
\closedWith 8ddc0b4016a66fa9d62fa3a4a866aaa58089a272
