### ISSUE TITLE
SCM icon needs love

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#18675]
![image](https://cloud.githubusercontent.com/assets/900690/22029139/e2fa6500-dcd9-11e6-8891-3ed551d773a2.png)

**Comment by joaomoreno** [comment]
I actually like it a LOT.

Btw renamed the issue. It's one icon for all SCM providers. Not a git specific one.

**Comment by dfroze** [comment]
I have 2 problems about this:
1. if the button will be ONLY for git (even in the future), shouldn't  it have the git icon or something 'Git' written ?  The icon looks too similar to the Explorer button and its not intuitive to say 'hey, i am related to git'. 
2. If it's for git, svn, etc, similar to the first question, it's not intuitive when looking at it, it's kinda similar to Explorer

**Comment by bpasero** [comment]
It should at least align with the explorer icon.

**Comment by bgashler1** [comment]
I just put in a request to our icon team cc @chryw

**Comment by rmunn** [comment]
The http://www.larch.in/images/icon-qms.png icon looks like "upload to the cloud", which does not at all communicate "This is the icon for your source control system," at least to me. I'm :-1: on using a cloud icon.

:+1: for just using the Git icon. If Mercurial or SVN support is added in the future, then perhaps the icon could change to be the Mercurial icon when the current project folder has an `.hg` directory, or the SVN icon when the current project folder has an `.svn` directory. But defaulting to the Git icon makes the most sense.

**Comment by Krzysztof-Cieslak** [comment]
IMO, SCM extensions should be defining icon that is used there.

**Comment by Krzysztof-Cieslak** [comment]
And yes, I'd default to Git icon if there is no SCM initialized in current workspace.

**Comment by chryw** [comment]
I'm also in favor of defaulting to Git icon. But if you do need a generic version control icon, how about this
![image](https://cloud.githubusercontent.com/assets/7075677/22087937/be6d9b0a-dd95-11e6-8647-13bcdd381e22.png)

![image](https://cloud.githubusercontent.com/assets/7075677/22087920/a7af81c6-dd95-11e6-8443-7360e4e901c1.png)

I really like @bpasero 's idea of using +- . I just changed the container so that it's less like the Explorer icon.

**Comment by dfroze** [comment]
Wonder if @chryw version could be used as default until setting up the version control tool. After setting it up, the icon can change to specific one or can remain the same based on the user preference. Some user might not like the idea, when working with multiple project each with different version control tool, to see different icon.

**Comment by chryw** [comment]
[GenericVersionControlIcon.zip](https://github.com/Microsoft/vscode/files/832459/GenericVersionControlIcon.zip)

Not sure where this landed. I'm attaching the icon file just in case.

**Comment by rhires** [comment]
Not thrilled w/ the new icon. How do we choose what icon goes there? Can I have one of the old ones back?

**Comment by joaomoreno** [comment]
We're just going to nail on one eventually, which some people will like and others won't. There are bigger things to worry about.

**Comment by rmunn** [comment]
But but but... I wanted the bikeshed to be ***blue***! :grinning:

Seriously, though, "just pick one and move on" is the right decision. If enough people don't like it, submitting a new SVG icon in a pull request is always possible; if it gets several hundred upvotes, then I can't see the dev team saying "no" to merging it in. But they shouldn't spend their time re-painting the bikeshed every day.

And for what it's worth, I like the icon you picked as the default. Would I have picked something else? Sure. But eh, each VCS extension is going to change the icon anyway, right? So it's not worth spending time on the inevitable bikeshed.

**Comment by chryw** [comment]
btw I'm totally cool with this - 
![image](https://cloud.githubusercontent.com/assets/7075677/23879942/a00b27ca-080d-11e7-9535-3d73e5295204.png)

**Comment by joaomoreno** [comment]
@egamma isn't a big fan of the current one:

![image](https://cloud.githubusercontent.com/assets/22350/24360180/dc68004a-1306-11e7-9be9-dd0028822c47.png)

He suggested to experiment with the octicon one looks and prefers it:

![image](https://cloud.githubusercontent.com/assets/22350/24360212/f3a8f0ac-1306-11e7-9277-5e880da19b0e.png)

![image](https://cloud.githubusercontent.com/assets/22350/24360218/f97c58ca-1306-11e7-9ca2-83c8979e7ffb.png)

@bpasero and @chrisdias Please let me know if you *hate* it.

PS: We are on the last week for this.

**Comment by bpasero** [comment]
I like our current one, the new one seems unbalanced.

**Comment by chrisdias** [comment]
I don't hate the new one, I like it better than the existing one (looks like a stethoscope to me).  

Really though, I want to see the Git icon when i'm in a workspace that is backed by a git repository. Can an SCM extension contribute an icon?

**Comment by chryw** [comment]
Well we do have an equivalent version of that octicon. Just throwing it here.
![image](https://cloud.githubusercontent.com/assets/7075677/24380431/23b446cc-1300-11e7-9f29-6cde1fcdebd5.png)

![image](https://cloud.githubusercontent.com/assets/7075677/24380695/8c517f32-1301-11e7-881d-ced9dfb9eccc.png)

[GenericVersionControlIcon.zip](https://github.com/Microsoft/vscode/files/873987/GenericVersionControlIcon.zip)

I think we all want a specified repo to show corresponding icon (git icon for git repo, etc.). This is only for "I don't know what type it is" scenario, isn't it?

**Comment by joaomoreno** [comment]
@chrisdias 

> Really though, I want to see the Git icon when i'm in a workspace that is backed by a git repository. Can an SCM extension contribute an icon?

We don't see a Go icon in the explorer when opening a Go workspace. Neither is the Java icon showing up in the debug viewlet when debugging a Java app. So why should SCM be any different?

**Comment by joaomoreno** [comment]
Went with the much improved `forked` octicon: https://octicons.github.com/icon/repo-forked/

**Comment by chrisdias** [comment]
@joaomoreno perhaps after so many years i simply miss seeing the git icon there :(
