### ISSUE TITLE
 VSCode not picking up Environmental variables which start with CS_*

### ISSUE THREAD

**Issue by priyamvada-singh-27** [microsoft/vscode#186730]
When setting these environment variables using deployment.yaml for VSCODE-SERVER 
{
- name: ROOT__CS_SECTION
   value: CS_AZURE
- name: CS_AZURE__ENDPOINT
  value: ***
- name: CS_AZURE__ACCESS_KEY
  value: ***
- name: CS_AZURE__SECRET_KEY
  value: ***
}

All environment variables starting with CS_* are being dropped. 

`printenv | grep CS ` only gives `ROOT__CS_SECTION=CS_AZURE`

We have to set this manually on the server to get it working, which is an issue when deploying on K8 service with multiple pods.

Want to understand if there is a list of environment variables which are dropped because they are a security hazard? and where can we get them?

**Comment by connor4312** [comment]
What do you mean "VSCODE-SERVER"? What product is this / how are you deploying it?

**Comment by priyamvada-singh-27** [comment]
on micromamba base docker file installing vscode using code-server; here are the commands

RUN curl -fsSL https://code-server.dev/install.sh | sh
RUN code-server --install-extension rogalmic.bash-debug
RUN code-server --install-extension ms-python.python
RUN code-server --install-extension foxundermoon.shell-format
RUN code-server --install-extension redhat.vscode-yaml

**Comment by connor4312** [comment]
code-server.dev is not something maintained by the VS Code team. Please open an issue on them.
