### ISSUE TITLE
repeated input occuring When switching between Chinese and English input methods on OSX

### ISSUE THREAD

**Issue by xiuxiuxius** [microsoft/vscode#186718]
Type: <b>Bug</b>

macos: ventura 13.4.1

open vscode terminal
1.Chinese input mode
input "conda"， keeping, don't “enter”
2. switching Chinese to English
command line appears
>con daconda
3. other places have no such phenomenon （chrome, notebook, bing）

VS Code version: Code 1.79.2 (695af097c7bd098fbf017ce3ac85e09bbc5dda06, 2023-06-14T08:58:33.551Z)
OS version: Darwin arm64 22.5.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|2, 2, 3|
|Memory (System)|16.00GB (0.88GB free)|
|Process Argv|--crash-reporter-id cf7e3351-f1b4-4d6b-ac5d-dac616d6e140|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (51)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-django|bat|1.10.0
doxdocgen|csc|1.4.0
c-cpp-project-generator|dan|1.2.12
vscode-markdownlint|Dav|0.51.0
githistory|don|0.6.20
python-environment-manager|don|1.0.4
python-extension-pack|don|1.7.0
xml|Dot|2.5.1
gitlens|eam|14.0.1
code-runner|for|0.12.0
codespaces|Git|1.14.8
vscode-pull-request-github|Git|0.66.2
vscode-edit-csv|jan|0.7.6
better-cpp-syntax|jef|1.17.2
nbpreviewer|jit|1.2.2
vsc-python-indent|Kev|1.18.0
vscode-leetcode|Lee|0.18.1
rainbow-csv|mec|3.7.0
git-graph|mhu|1.30.0
vscode-clang|mit|0.2.4
vscode-docker|ms-|1.25.2
vscode-language-pack-zh-hans|MS-|1.79.2023061409
isort|ms-|2022.8.0
python|ms-|2023.10.1
vscode-pylance|ms-|2023.6.40
jupyter|ms-|2023.5.1101742258
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.15
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-slideshow|ms-|0.1.5
remote-containers|ms-|0.295.0
remote-ssh|ms-|0.102.0
remote-ssh-edit|ms-|0.86.0
remote-wsl|ms-|0.79.5
vscode-remote-extensionpack|ms-|0.24.0
cmake-tools|ms-|1.14.34
cpptools|ms-|1.16.3
cpptools-extension-pack|ms-|1.3.0
remote-explorer|ms-|0.4.0
remote-server|ms-|1.2.1
autodocstring|njp|0.6.1
ufmt|omn|2023.4.3
csv-to-table|php|1.4.0
partial-diff|ryu|1.4.3
code-spell-checker|str|2.20.5
python-extended-snippets|tus|0.0.1
cmake|twx|0.0.17
vscode-icons|vsc|12.4.0
jinja|who|0.0.8
json|Zai|2.0.2
material-theme|zhu|3.15.17

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263cf:30335440
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
py29gd2263:30776702
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
vscccc:30610679
3biah626:30602489
pyind779:30671433
f6dab269:30613381
pythonsymbol12:30671437
showlangstatbar:30737416
vsctsb:30748421
pythonms35:30701012
pythonfmttext:30731395
pythoncmvfstrcf:30756944
fixshowwlkth:30771522
hideindicator:30766889
pythongtdpath:30769146
pythonnosmt12:30779714
pythonidxpt:30772539
pythonnoceb:30776495
e537b577:30772215

```

</details>

**Comment by xiuxiuxius** [comment]
<img width="787" alt="截屏2023-06-30 18 02 37" src="https://github.com/microsoft/vscode/assets/89114157/fdfb23d9-8b6a-4e40-8b3f-235d1388c811">
<img width="725" alt="截屏2023-06-30 18 02 45" src="https://github.com/microsoft/vscode/assets/89114157/e706f119-3982-4614-a421-0eaa947c914f">
<img width="593" alt="截屏2023-06-30 18 02 58" src="https://github.com/microsoft/vscode/assets/89114157/cb1a1dae-cb07-4dbe-92ec-8f4a405ebec2">
<img width="461" alt="截屏2023-06-30 18 03 03" src="https://github.com/microsoft/vscode/assets/89114157/ab47d418-18c5-43f1-b94c-b0a5dbec806d">

**Comment by Tyriar** [comment]
We're tracking problems with Chinese IMEs in the upstream repo.

/duplicate https://github.com/xtermjs/xterm.js/issues/4486
