### ISSUE TITLE
Search results nav F4 conflicts with the C++ extension

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#18679]
@egamma What problem did you say you had with shift+f4? It works as expected for me.

**Comment by egamma** [comment]
@roblourens my problem was the 'F4' gives focus to the editor and I could not press it repeatedly. I've tried to reproduce it with all extensions disabled and it worked well. Sorry about the false issue.

**Comment by egamma** [comment]
The culprit is the C++ extension, this means the users of the C++ extensions have the same issue.

**Comment by egamma** [comment]
Given that the C++ extension is popular we should "fix this" by announcing this as a "breaking" key binding change in the release notes.

**Comment by BillDenton** [comment]
Shouldn't this be moved to C++ extension and the extension change its key mapping?

**Comment by roblourens** [comment]
Filed an issue on vscode-cpptools, and added to the release notes
