### ISSUE TITLE
Crash when opening new windows

### ISSUE THREAD

**Issue by Eshnek** [microsoft/vscode#186789]
Hello!

I am experiencing a crash with VSCode that seems to be unrelated to any extensions.
A crash occurs seemingly randomly when I open new windows.
In the attached video, I open and close instances until the crash occurs.

I have had this issue for a couple of months now.

I saw a message about TabNine in the logs despite having all extensions disabled. I tried uninstalling it and the issue still occurs.

I notice a core dump in my `journalctl`, which I have attached.

- VS Code Version: 1.79.2
- OS Version: Arch Linux

Steps to Reproduce:
1. Open a new window
2. Failure occurs some proportion of the time, irrespective of other windows.
3. Failure closes all windows

Here I open and close instances with my associated hotkeys:
https://github.com/microsoft/vscode/assets/89618355/5f07dacb-0589-4984-9614-16aacbc31035

[logs.zip](https://github.com/microsoft/vscode/files/11919608/logs.zip)
[journal.txt](https://github.com/microsoft/vscode/files/11919607/journal.txt)

**Comment by utherpally** [comment]
I have the same problem with the following versions:
Version: 1.79.2
Commit: 695af097c7bd098fbf017ce3ac85e09bbc5dda06
Date: 2023-06-14T08:59:55.818Z
Electron: 22.5.7
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Linux x64 6.4.1

But with no logs file generated when crashing.
[journal.txt](https://github.com/microsoft/vscode/files/12026088/journal.txt)
