### ISSUE TITLE
Can't use cmd+up/down in terminal after closing find widget

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#186781]
- cmd+F to open find widget
- Close it with escape
- cmd+up to navigate to previous command
- Nothing happens, I have to click or run a command to reset focus in the terminal

**Comment by Tyriar** [comment]
@roblourens I can't reproduce this, if you still can are there any more details on the repro case? The keyboard troubleshooting command output would be helpful if only you can repro.

**Comment by roblourens** [comment]
Sorry it's working now, agreed that it was probably a context key thing so I'll check that next time

**Comment by jeanp413** [comment]
I can repro this when the serch input have has text selected, PR https://github.com/microsoft/vscode/pull/187781
