### ISSUE TITLE
The layout of the interface under multi-window is abnormal

### ISSUE THREAD

**Issue by Dynesshely** [microsoft/vscode#186711]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.79.2
- OS Version: Windows NT x64 10.0.22621

Steps to Reproduce:

1. Open serveral instances of vscode with different workspaces.
2. Adjust layout of these instances to same.
3. Close all these instances (at now to reopen them, the layout is same).
4. Open a new vscode, adjust to another layout and close.
5. Open all before instances.
6. Previous instances layout all changed to latest closed one.

Can you storage layout in workspace file ?
Or just remember different layout for different workspaces or folders ?
Is this difficult to achieve ?

This really bothers me a lot
I have to be careful lest a change in any one of the vscode window layouts cause a change in my previous vscode window layout

**Comment by Dynesshely** [comment]
I think, we can storage layout config in `.code-workspace` file for workspaces, and storage layout config in one sheet for folders.

**Comment by sbatten** [comment]
Layout state is mixed between workspace and global state based on what we determined makes sense at certain points in time. Now, the best workaround is to create profiles for different layouts. In this way, you can set your layout in a profile and reuse it in as many workspaces as you like, or not.

**Comment by Dynesshely** [comment]
Currently, I'm a student at 12 grades in China, with no time to test the way you mentioned, though I think your method would work.
You can close this issue. I will test your method after my Colleges Entrance Examination at next year June, and I will reopen this issue if there is still problems.
Thanks.
