### ISSUE TITLE
Language features restarting continuously

### ISSUE THREAD

**Issue by nicoabie** [microsoft/vscode#186753]
Type: <b>Bug</b>

in logs

VS Code version: Code 1.79.2 (695af097c7bd098fbf017ce3ac85e09bbc5dda06, 2023-06-14T08:58:33.551Z)
OS version: Darwin arm64 23.0.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|4, 13, 15|
|Memory (System)|16.00GB (0.74GB free)|
|Process Argv|--crash-reporter-id ac6a28e7-9b57-4a9e-84ee-2a172c5f5cae|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-apollo|apo|1.19.11
github-markdown-preview|bie|0.3.0
markdown-mermaid|bie|1.19.0
vscode-eslint|dba|2.4.2
gitlens|eam|14.0.1
EditorConfig|Edi|0.16.4
copilot-chat|Git|0.2.1
copilot-nightly|Git|1.93.213
vscode-github-actions|git|0.25.8
go|gol|0.39.0
vscode-goto-node-modules|mrl|1.3.0
es6-string-html|Tob|2.12.1
quokka-vscode|Wal|1.0.547

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vstes627:30244334
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
py29gd2263:30776702
vscaac:30438847
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
282f8724:30602487
pyind779:30671433
89544117:30613380
pythonsymbol12:30671437
a9j8j154:30646983
showlangstatbar:30737416
vsctsb:30748421
pythonms35:30701012
03d35959:30757346
pythonfmttext:30731395
pythoncmvfstrcf:30756944
fixshowwlkth:30771522
showindicator:30766890
pythongtdpath:30769146
bgfeh915:30769767
pythonnosmt12:30779714
pythonidxpt:30772539
pythonnoceb:30776495

```

</details>

**Comment by aiday-mar** [comment]
Hi @nicoabie, could you please add more information regarding the bug and steps to reproduce it? Thank you.

**Comment by nicoabie** [comment]
Hi @aiday-mar,

I just open vscode and the extension keeps restarting. I don't have any specifics, I attached all the logs.

**Comment by aiday-mar** [comment]
Hi @dbaeumer, @aeschli, feel free to reassign the issue if this is under someone else's responsibility

**Comment by dbaeumer** [comment]
@nicoabie can you please run the command Help: Troubleshoot issue which will help find the extension that is causing the bahviour.
