### ISSUE TITLE
Default light theme does not colorize comments in typescript

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#1867]
`findWidget.ts` , comment some code inside a closure.

The light theme contains a rule for meta that overwrites the rule for comment.

![image](https://cloud.githubusercontent.com/assets/5047891/12195470/b3d4c3c4-b5f7-11e5-8b3d-6b14ab6b5d08.png)

**Comment by aeschli** [comment]
duplicate of #1864
