### ISSUE TITLE
EnvironmentVariableCollection.description is not shown in the hover when the environment is stale

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#186798]
Repro:

1. Create a terminal
2. Hover the terminal tab, see the git extension shows a description
3. Change auto attach via command palette
4. Hover the terminal tab, 🐛  see the git extension _does not_ show a description

![image](https://github.com/microsoft/vscode/assets/2193314/7d0987c6-edd8-4067-99ed-ad6a7448cc9d)

**Comment by karrtikr** [comment]
I'm not able to reproduce this issue in the latest insiders with any combination of toggle auto attach:

![image](https://github.com/microsoft/vscode/assets/13199757/e9a4ec9e-50ab-433b-b873-d1e89191be70)

Can you double check?

**Comment by Tyriar** [comment]
Yes looks like this is fixed with that candidate. Thanks for checking
