### ISSUE TITLE
The JS/TS language service immediately crashed 5 times

### ISSUE THREAD

**Issue by robeastwood** [microsoft/vscode#186788]
Type: <b>Bug</b>

Open VS Code, a quasar project.
get a message:

The JS/TS language service immediately crashed 5 times. The service will not be restarted.

Intellisense seems to be unable to load, no formatting happening

VS Code version: Code 1.79.2 (695af097c7bd098fbf017ce3ac85e09bbc5dda06, 2023-06-14T08:57:04.379Z)
OS version: Windows_NT x64 10.0.19045
Modes:
Remote OS version: Linux x64 5.15.90.1-microsoft-standard-WSL2
Remote OS version: Linux x64 5.15.90.1-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz (12 x 3696)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.94GB (12.27GB free)|
|Process Argv|--folder-uri=vscode-remote://wsl+Ubuntu-20.04/home/rob/wslcode/testapi --remote=wsl+Ubuntu-20.04 --crash-reporter-id d386230a-8b8a-479c-8e71-b46a96143059|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-20.04|
|OS|Linux x64 5.15.90.1-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz (12 x 3696)|
|Memory (System)|7.76GB (3.99GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-20.04|
|OS|Linux x64 5.15.90.1-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz (12 x 3696)|
|Memory (System)|7.76GB (3.99GB free)|
|VM|0%|
</details><details><summary>Extensions (24)</summary>

Extension|Author (truncated)|Version
---|---|---
dotenv|mik|1.0.1
remote-wsl|ms-|0.79.5
laravel5-snippets|one|1.17.0
vscode-icons|vsc|12.4.0
vscode-todo-highlight|way|1.0.5
laravel-extra-intellisense|ami|0.6.3
vscode-intelephense-client|bme|1.9.5
laravel-goto-view|cod|1.3.8
vscode-eslint|dba|2.4.2
EditorConfig|Edi|0.16.4
prettier-vscode|esb|9.19.0
laravel-create-view|gli|0.0.6
laravel-blade-wrapper|IHu|1.0.1
dotenv|mik|1.0.1
laravel-goto-components|nao|1.2.0
laravel-blade|one|1.34.0
laravel-extension-pack|one|1.2.0
laravel5-snippets|one|1.17.0
laravel-pint|ope|1.1.4
laravel-jump-controller|pgl|0.0.33
vs-code-prettier-eslint|rve|5.1.0
laravel-artisan|rya|0.0.31
vscode-blade-formatter|shu|0.20.15
volar|Vue|1.8.3

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
py29gd2263:30776702
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
vsccc:30610678
3biah626:30602489
pyind779:30671433
89544117:30613380
pythonsymbol12:30671437
showlangstatbar:30737416
vsctsb:30748421
pythonms35:30701012
03d35959:30757346
pythonfmttext:30731395
pythoncmv:30756943
fixshowwlkth:30771522
hideindicator:30766889
pythongtdpath:30769146
i26e3531:30780429
pythonnosmt12:30779714
pythonidxptcf:30772540
pythonnoceb:30776495

```

</details>

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)? 

If it does, please share a minimal project which demonstrates the issue

**Comment by robeastwood** [comment]
I updated to latest version, issue seems to have gone.

I'll repoen or raise again if it warrants more attention.

Cheers
