### ISSUE TITLE
did not support  <div style="display:none;"> format

### ISSUE THREAD

**Issue by hzmnet** [Microsoft/vscode#18677]
- VSCode Version: Code 1.8.1 (ee428b0eead68bf0fb99ab5fdc4439be227b6281, 2016-12-19T14:49:23.350Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

|Extension|Author|Version|
|---|---|---|
|Go|lukehoban|0.6.39|

---

Steps to Reproduce:

1.when the code including attr style. then it can not be format correctly!
2.

**Comment by aeschli** [comment]
duplicate of #17849
