### ISSUE TITLE
PHP

### ISSUE THREAD

**Issue by RonnyG2121** [microsoft/vscode#186791]
<p>
Hello
I have a problem with an extension from php
When I use a php extensions, code comments does html
instead of using the double /, it makes the comments as if it were programming in html
thanks for read me
</p>
VS Code version: Code 1.79.2 (695af097c7bd098fbf017ce3ac85e09bbc5dda06, 2023-06-14T08:57:04.379Z)
OS version: Windows_NT x64 10.0.22621
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Celeron(R) N4000 CPU @ 1.10GHz (2 x 1094)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: disabled_off<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|3.83GB (0.65GB free)|
|Process Argv|C:\\wamp64\\www\\ajax\\ajax.code-workspace --crash-reporter-id ebe70f17-e335-44d9-afea-bcc35f431670|
|Screen Reader|yes|
|VM|0%|
</details><details><summary>Extensions (32)</summary>

Extension|Author (truncated)|Version
---|---|---
bs5|aja|0.7.0
vscode-mysql-client2|cwe|6.5.10
vscode-html-css|ecm|1.13.1
vscode-firefox-debug|fir|2.9.8
code-runner|for|0.12.0
vscode-pull-request-github|Git|0.66.2
vscode-language-pack-es|MS-|1.79.2023061409
csharp|ms-|1.26.0
vscode-dotnet-pack|ms-|1.0.12
vscode-dotnet-runtime|ms-|1.6.0
vscode-dotnet-sdk|ms-|0.8.0
vscode-postgresql|ms-|0.3.0
isort|ms-|2022.8.0
python|ms-|2023.10.1
vscode-pylance|ms-|2023.6.40
jupyter|ms-|2023.5.1101742258
jupyter-renderers|ms-|1.0.15
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-slideshow|ms-|0.1.5
remote-wsl|ms-|0.79.5
cmake-tools|ms-|1.14.34
cpptools|ms-|1.16.3
cpptools-extension-pack|ms-|1.3.0
java|red|1.20.0
LiveServer|rit|5.7.9
intellicode-api-usage-examples|Vis|0.2.7
vscodeintellicode|Vis|1.2.30
vscode-java-debug|vsc|0.52.0
vscode-java-dependency|vsc|0.23.0
vscode-java-pack|vsc|0.25.12
vscode-java-test|vsc|0.39.0
vscode-maven|vsc|0.41.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263cf:30335440
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
py29gd2263:30776702
vscaat:30438848
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyonecf:30548226
282f8724:30602487
pyind779:30671433
f6dab269:30613381
pythonsymbol12:30671437
showlangstatbar:30737416
vsctsb:30748421
pythonms35:30701012
pythonfmttext:30731395
pythoncmvfstrcf:30756944
fixshowwlkth:30771522
pythongtdpath:30769146
bgfeh915:30780428
pythonnosm12tcf:30779713
pythonidxptcf:30772540
pythonnocebcf:30776496
cmakesidepanelv2:30779593

```

</details>

**Comment by roblourens** [comment]
Does it happen if you start vscode with `--disable-extensions`?

**Comment by RonnyG2121** [comment]
No, does not

RG

**Comment by roblourens** [comment]
Sounds like this is related to some php or html related extension changing the language configuration.

**Comment by RonnyG2121** [comment]
surethis is so awkward Enviado desde Correo para Windows De: Rob LourensEnviado: miércoles, 5 de julio de 2023 22:30Para: microsoft/vscodeCC: Ronny Gonzalez; AuthorAsunto: Re: [microsoft/vscode] PHP (Issue #186791) Sounds like this is related to some php or html related extension changing the language configuration.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>
