### ISSUE TITLE
Revisit usage of native private fields

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#186737]
related https://github.com/microsoft/vscode/issues/185991#issuecomment-1607337382

Using native private properties has always been very, very slow. That's because they transpiled to a WeakMap-based polyfill, with ES2022 they compile into the equivalent JS but they are still much slower. Depending on the browser you are loosing between 50 to 95% performance over a compile-time private. So, seriously re-consider the use of native privates in the following files:

- [x] `src/vs/editor/contrib/codeAction/browser/codeActionController.ts` @mjbvz 
- [x] `src/vs/editor/contrib/codeAction/browser/codeActionModel.ts` @mjbvz 
- [x] `src/vs/workbench/contrib/editSessions/browser/editSessionsStorageService.ts` @joyceerhl 
- [x] `src/vs/workbench/contrib/interactive/browser/interactiveEditor.ts` @rebornix
- [x] `src/vs/workbench/contrib/interactive/browser/interactiveHistoryService.ts` @rebornix 
- [x] `src/vs/workbench/contrib/webviewPanel/browser/webviewWorkbenchService.ts` @mjbvz 
- [x] `src/vs/workbench/services/remote/common/remoteAgentService.ts` @bpasero 
- [x] `src/vs/workbench/services/terminal/common/embedderTerminalService.ts` @Tyriar  

The API implementation is also affected by this but kinda exempted because native privates are a cheap way to hide API implementation details from extension. However, better patterns is the [apiObject-pattern](https://github.com/microsoft/vscode/blob/e2fcf63174e7fe6e768694353b322b768767b5dd/src/vs/workbench/api/common/extHostNotebookDocument.ts#L78)

<details>
<summary>API</summary>
- [ ] `src/vs/workbench/api/common/extHostCommands.ts`
- [ ] `src/vs/workbench/api/common/extHostDiagnostics.ts`
- [ ] `src/vs/workbench/api/common/extHostExtensionService.ts`
- [ ] `src/vs/workbench/api/common/extHostSCM.ts`
- [ ] `src/vs/workbench/api/common/extHostSecrets.ts`
- [ ] `src/vs/workbench/api/common/extHostStatusBar.ts`
- [ ] `src/vs/workbench/api/common/extHostTask.ts`
- [ ] `src/vs/workbench/api/common/extHostTesting.ts`
- [ ] `src/vs/workbench/api/common/extHostTypes.ts`
- [ ] `src/vs/workbench/api/common/extHostWebview.ts`
- [ ] `src/vs/workbench/api/common/extHostWebviewPanels.ts`
- [ ] `src/vs/workbench/api/common/extHostWebviewView.ts`

</details>

**Comment by jrieken** [comment]
Note that all these file have a `/* eslint-disable local/code-no-native-private */` rule after their copy right header. Please remove in case you decide for performance and against native private fields

**Comment by bpasero** [comment]
via https://github.com/microsoft/vscode/pull/186741

**Comment by rebornix** [comment]
Cleaned up interactive window. It's all done now I think.
