### ISSUE TITLE
Add an unsaved file marker

### ISSUE THREAD

**Issue by pam66** [microsoft/vscode#186706]
It would be desirable to have in the "markers" side column (see figure below) a graphical marker of some sort to indicate that the (modified) file is unsaved.

![image](https://github.com/microsoft/vscode/assets/36194853/05629e49-949c-43c1-b6a9-b5125c273ecb)

**Comment by gjsjohnmurray** [comment]
Which view is this? Explorer? Source Control? Something else?

**Comment by pam66** [comment]
it's Explorer. Sorry.

**Comment by pam66** [comment]
if you don't want to add/show a marker in that side column, maybe one could turn the coloured "source kind" icon (the one indicating C, C++, python, Makefile, etc.) into a grey (or some other color) icon, for instance. Or, one could add a white bullet to the file name, as it already happens in the top bar.

**Comment by ulugbekna** [comment]
hm, to my understanding, you can't have an unsaved file without a tab open, and a tab shows that file is unsaved -- dot on the right

<img width="269" alt="image" src="https://github.com/microsoft/vscode/assets/16353531/e78d6627-bee2-48ad-aed7-17efcded5399">


If you don't use tabs, you have "Open editors" tree within explorer that also shows unsaved files:

<img width="396" alt="image" src="https://github.com/microsoft/vscode/assets/16353531/13563c2d-e81e-4df1-98cc-744829651c2f">

**Comment by pam66** [comment]
ah, ok, now I see. So the tree view I used to watch is the "explorer" one that simply shows all folder(s) content, while the "Open editors" view is the right one I should refer to, because that shows only files open in the editor.

Ok, sorry, so this feature request can be cancelled.
Thanks and apologize for the waste of time... 😞
