### ISSUE TITLE
Git/SCM: Open File/Open Change context menu items should avoid using preview tabs

### ISSUE THREAD

**Issue by eamodio** [Microsoft/vscode#18673]
- VSCode Version: `1.9.0-insider` f67f87c5498d9361c0b29781c341fd032815314b
- OS Version: macOS Sierra `10.12.2`

I like that clicking on a file in the Git/SCM pane uses a preview tab (if enabled), but I really wish that when right-clicking to select `Open File` or `Open Change` it would avoid the preview tab. Since it feels like a less exploratory operation at least IMO. :)

Steps to Reproduce:

1. Right-click on a file in the Git/SCM pane
2. Select `Open File` or `Open Change`
3. Opens the desired in a preview tab (if enabled)

**Comment by joaomoreno** [comment]
@bpasero @jrieken Is this controllable via the API?

**Comment by jrieken** [comment]
Do you use `showTextDocument`? We should/could add a message if it should be opened as `pinned` or however we call that

**Comment by bpasero** [comment]
I am not sure we should change this, in stable we open these things as preview editor and people might like that. What is the rationale of changing this suddenly?

**Comment by eamodio** [comment]
@bpasero The rationale for me is because it is such an explicit action, rather than an exploratory click. Similar to how macOS considers a right-click -> Open a more explicit action than just clicking on an application. And personally it drives me nuts to try to open a few files from here - as I first need to right-click on the entry, choose `Open File`, then go over and double-click on the tab to "pin" it, then back to the viewlet to repeat the process.

If we can't change the default behavior could there at least be a setting to control it? Although honestly, I like this less, since I like just clicking on the files to open in a preview tab, but not when I take the explicit action `Open File` / `Open Change` action.

Other things that could also help here, is multi-select (and in that case you'd have to open them "pinned") and also would be great to have an `alt` click on the files to open the file rather than the change.

**Comment by joaomoreno** [comment]
Better late than never :grimacing:

**Comment by bpasero** [comment]
This works for "Open File", but not for "Open Changes", nor "Open File (HEAD)"

**Comment by ramya-rao-a** [comment]
Verified by running from source
