### ISSUE TITLE
Add global default setting for pasting links into markdown files for `plain text`

### ISSUE THREAD

**Issue by nikitavoloboev** [microsoft/vscode#186878]
<img width="621" alt="image" src="https://github.com/microsoft/vscode/assets/6391776/0c8ed301-c604-4254-ab6e-a93fc9b1a246">

Above was added to recent code-insiders and I really dislike it. Now every time I paste a link it asks me to add a title. I want it so by default it pastes as `plain text`, not markdown. Can I do this?

**Comment by ken0x0a** [comment]
@nikitavoloboev 
Did you try the following?

```json
"markdown.editor.pasteUrlAsFormattedLink.enabled": false,
```

**Comment by nikitavoloboev** [comment]
Perfect. Thank you.

I can close this issue but I would vote for the default to be `false` instead of true. I think being able to just paste URLs freely in markdown is very important.

**Comment by mjbvz** [comment]
Duplicate of #184871
