### ISSUE TITLE
"Close Repository" in a repository with submodules gets reset for no reason

### ISSUE THREAD

**Issue by TomasHubelbauer** [microsoft/vscode#186846]
Type: <b>Bug</b>

When using "Close Repository" on a submodule repository in a repository with submodules, the repository gets reopened in the SCM pane all the time:

https://github.com/microsoft/vscode/assets/6831144/5ff906e6-a9ac-4673-b430-ee6c09b79fa5

VS Code version: Code 1.79.2 (695af097c7bd098fbf017ce3ac85e09bbc5dda06, 2023-06-14T08:58:33.551Z)
OS version: Darwin arm64 22.5.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|3, 2, 2|
|Memory (System)|16.00GB (2.00GB free)|
|Process Argv|. --crash-reporter-id 59cf1bed-5b44-43f7-a7e9-0f2d11ca0d35|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
openscad|Ant|1.1.1
copilot|Git|1.94.220
vscode-github-actions|git|0.25.8
rust-analyzer|rus|0.3.1566

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
py29gd2263:30776702
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
282f8724:30602487
pyind779:30671433
89544117:30613380
vscrp:30673768
pythonsymbol12:30671437
showlangstatbar:30737416
vsctsb:30748421
pythonms35:30701012
03d35959:30757346
pythonfmttext:30731395
pythoncmvfstrcf:30756944
fixshowwlkth:30771522
showindicator:30766890
pythongtdpath:30769146
bgfeh915:30780428
pythonnosmt12:30779714
pythonidxptcf:30772540
pythonnocebcf:30776496
h7j2d465:30772216
cmakesidepanelv2:30779593

```

</details>

**Comment by lszomoru** [comment]
@TomasHubelbauer, we have done some improvements in this area so I was wondering if you are also able to reproduce this issue with the latest VS Code Insiders release? Thank you!

**Comment by lszomoru** [comment]
@TomasHubelbauer, thanks for the update! Glad to hear that things are resolved.
