### ISSUE TITLE
Parantesis pliminar check as pre run of the gcc compiler

### ISSUE THREAD

**Issue by rdx789** [microsoft/vscode#186890]
Type: <b>Feature Request</b>

Check first for even and matching number of parentesis.
If there is an additional open curley brace some where in the function the compiler will complain on somthing un related.

VS Code version: Code 1.79.2 (695af097c7bd098fbf017ce3ac85e09bbc5dda06, 2023-06-14T08:57:04.379Z)
OS version: Windows_NT x64 10.0.19045
Modes:
Remote OS version: Linux arm 6.1.21-v8+

**Comment by roblourens** [comment]
Sounds like this might be a feature request for the C++ extension, or whatever other extension you are using to integrate with gcc. This isn't something that vscode would have built-in

**Comment by rdx789** [comment]
actually, the vocode does mark the parenthesis in deferent colors which helps to find the un matching parentheses.
But as I said if you did not pay attention enough you are getting very strange error from gcc compiler.
Thanks.
