### ISSUE TITLE
EnvironmentVariableCollection.description only works for one extension

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#186859]
This is the reason js-debug isn't working but git is:

https://github.com/microsoft/vscode/blob/01d4949f36c7a5598f115adaea463dc30e4f9c12/src/vs/platform/terminal/common/environmentVariableCollection.ts#L139-L161

This is probably a good candidate for recovery, not a good reason to push 1.80.0 out though.

**Comment by Tyriar** [comment]
Fixed in main https://github.com/microsoft/vscode/pull/186861

**Comment by karrtikr** [comment]
Thanks for taking care of it while I was out! Can this be closed?

**Comment by Tyriar** [comment]
@karrtikr this one's going into the recovery build, didn't quite make the cut for 1.80.0.

**Comment by meganrogge** [comment]
@karrtikr verified that JavaScript debug terminals are getting the expected env - can you pls lmk what the repro steps were here?

**Comment by karrtikr** [comment]
You can add the following setting to activate description for Python ext: `"python.experiments.optInto": ["pythonTerminalEnvVarActivation"]` in User settings and reload.

After which, if you select a virtual environment (Python: Select Interpreter), it should use env collection to activate terminal with appropriate description, something like:

![image](https://github.com/microsoft/vscode/assets/13199757/15617f63-597c-4254-a661-7a7d60649379)

Description is the "Enable Nodejs..." string next to "Javascript debugger:", it appears when hovering over the terminal label.

**Comment by meganrogge** [comment]
![Screenshot 2023-07-12 at 10 18 02 AM](https://github.com/microsoft/vscode/assets/29464607/e754abb9-3dd3-4dcf-b8dc-7ce4b400092f)

**Comment by karrtikr** [comment]
Seems to work 👍

**Comment by Tyriar** [comment]
The actual verify steps for this is to ensure 2 list items appear in the same section. Verified below.

Insiders:

![image](https://github.com/microsoft/vscode/assets/2193314/9ff17673-33b8-49cb-af4f-3bbddaee6402)

Stable:

![image](https://github.com/microsoft/vscode/assets/2193314/62feada1-bfaf-406e-addb-f4ad3c44d567)
