### ISSUE TITLE
Custom problemMatcher provided by extension

### ISSUE THREAD

**Issue by mar3kk** [Microsoft/vscode#18689]
Please add possibility to create custom problem matcher in an extension that could be then used in a project's tasks.json like built in problem matchers
`{
    "problemMatcher" : $myCustomProblemMatcher
  }`

**Comment by dbaeumer** [comment]
Implemented for 1.11.

**Comment by jrieken** [comment]
@dbaeumer that means, via API, right?

**Comment by dbaeumer** [comment]
No, via package.json which was on the test plan. Removed verification needed.
