### ISSUE TITLE
Readonly in literal type not colorized correctly in Quite Light theme

### ISSUE THREAD

**Issue by sheetalkamat** [Microsoft/vscode#18688]
From @andy-hanson at Microsoft/TypeScript-TmLanguage#406

**[TS and JS Grammar Extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.typescript-javascript-grammar) version:**  latest

**Code**

```ts
type T = { readonly x: number; }
interface I { readonly x: number; }
```

![screenshot](https://cloud.githubusercontent.com/assets/5387404/21957983/e851f024-da57-11e6-94b6-88d8c784188d.jpg)

As a side note, I've been seeing a lot of purple in the "Quiet Light" color theme in vscode. Would prefer black for normal identifiers.

**Comment by sheetalkamat** [comment]
From @sheetalkamat
I don't see this. This looks like theme issue. Moving this to vscode
![capture](https://cloud.githubusercontent.com/assets/8052792/22036771/7956a454-dca9-11e6-9673-a2f1cb3a1d49.JPG)

**Comment by mjbvz** [comment]
Only repos with the latest grammar, not the one in insiders currently. Here's the two token classes:

`token meta type declaration ts storage object field modifier`
`token meta declaration ts storage field modifier class`

**Comment by mjbvz** [comment]
This seems to be fixed in the latest insiders with the TS grammar extension version 0.0.18

<img width="323" alt="screen shot 2017-01-24 at 11 26 14 pm" src="https://cloud.githubusercontent.com/assets/12821956/22281586/83ee9906-e28c-11e6-8f5b-979dbbdba48c.png">
