### ISSUE TITLE
Not able to forward a port in vscode.dev

### ISSUE THREAD

**Issue by chaoming** [microsoft/vscode#186847]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: vscode.dev
- OS Version: macOS, Linux

Steps to Reproduce:

1. Enable VSCode tunnel in VSCode UI in a host (Ubuntu)
2. Connect to the tunnel in a web browser (Chrome, Firefox) on macOS or Linux
3. Run your application in the remote terminal, such as running a React application
4. Go to Ports and click the"Forward a Port" button, input "3000" or any port that the React app is running on
5. vscode.dev shows the error "Unable to forward localhost:3000. The host may not be available or that remote port may already be forwarded"

Without the ability to forward a port, is there any way to preview the application remotely?

**Comment by connor4312** [comment]
Duplicates https://github.com/microsoft/vscode-remote-release/issues/8618
