### ISSUE TITLE
icon ans file are vanish

### ISSUE THREAD

**Issue by ANURAG-BADWAHE** [microsoft/vscode#186898]
Type: <b>Bug</b>

In my explorer section there is no file or icons are showing

VS Code version: Code 1.79.2 (695af097c7bd098fbf017ce3ac85e09bbc5dda06, 2023-06-14T08:57:04.379Z)
OS version: Windows_NT x64 10.0.22000
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 3 5300U with Radeon Graphics          (8 x 2595)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|7.33GB (1.78GB free)|
|Process Argv|D:\\Being-Developer-Backend --crash-reporter-id eafb6ee7-667e-4494-824b-497f314b517b|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (21)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-color-dlw|Bra|0.0.6
vscode-tailwindcss|bra|0.9.11
doxdocgen|csc|1.4.0
vscode-eslint|dba|2.4.2
vscode-html-css|ecm|1.13.1
prettier-vscode|esb|9.19.0
auto-rename-tag|for|0.1.10
code-runner|for|0.12.0
better-cpp-syntax|jef|1.17.2
cmake-tools|ms-|1.14.34
cpptools|ms-|1.16.3
cpptools-extension-pack|ms-|1.3.0
vsliveshare|ms-|1.0.5873
material-icon-theme|PKi|4.28.0
vscode-css-peek|pra|4.2.0
vscode-thunder-client|ran|2.8.3
LiveServer|rit|5.7.9
es7-react-js-snippets|rod|1.9.3
js-jsx-snippets|sky|11.0.1
cmake|twx|0.0.17
classnametocss|zit|0.0.7

(5 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
py29gd2263:30776702
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
2e4cg342:30602488
pyind779:30671433
89544117:30613380
pythonsymbol12:30671437
a9j8j154:30646983
showlangstatbar:30737416
vsctsb:30748421
pythonms35:30701012
03d35959:30757346
pythonfmttext:30731395
pythoncmvfstrcf:30756944
fixshowwlkth:30771522
hideindicator:30766889
pythongtdpath:30769146
i26e3531:30780429
pythonnosmt12:30779714
pythonidxpt:30772539
pythonnoceb:30776495

```

</details>

**Comment by lramos15** [comment]
`CTRL + SHIFT + P` -> `Reset View Locations`
