### ISSUE TITLE
Mac: Let Cmd+Click make the window take focus

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#18687]
- VSCode Version: Code - Insiders 1.9.0-insider (f67f87c5498d9361c0b29781c341fd032815314b, 2017-01-17T07:04:34.904Z)
- OS Version: Darwin x64 15.6.0
- Extensions:

|Extension|Author|Version|
|---|---|---|
|EditorConfig|EditorConfig|0.3.4|
|autofilename|JerryHong|0.1.3|
|vscode-docker|PeterJausovec|0.0.7|
|azure-cli|chrmarti|0.2.0|
|regex|chrmarti|0.0.7|
|vscode-eslint|dbaeumer|1.1.0|
|ghlink|dt|0.0.4|
|tslint|eg2|0.6.0|
|vscode-scss|mrmlnc|0.6.0|
|PowerShell|ms-vscode|0.7.2|
|cpptools|ms-vscode|0.9.3|
|debugger-for-chrome|msjsdiag|2.2.2|
|diff|rafaelmaiolla|0.0.1|
|vscode-open-in-github|sysoev|1.2.1|

---

Steps to Reproduce:

1. Open a TypeScript file with a reference that can be Cmd+Clicked
2. Give focus to a different application on a second screen (e.g., mail reader)
3. Cmd+Click the reference from step 1
4. Observe: The reference is followed, but the application from step 2 keeps focus
5. Expected: VSCode should take focus, because it is clicked into. (Subsequent keyboard interaction goes to other application, which is confusing.)

**Comment by dbaeumer** [comment]
@alexandrudima not sure if this is editor or workbench. @bpasero FYI.

**Comment by bpasero** [comment]
@weinand as macOS expert, would you expect you can "click through" to the non focussed application? Imho when a window does not have focus, you should probably not be allowed to interact with it before making it focussed.

**Comment by alexandrudima** [comment]
The code that listens to `cmd+click` is electron agnostic, it simply listens to `cmd+click`. This is most likely an electron issue, electron should activate the window you click on.

**Comment by alexandrudima** [comment]
This is an upstream issue (possibly within Chromium), and there are no known workarounds that we could implement on our side. This means there is no possible code change for us to do in VS Code sources to improve things. 

To keep the number of issues in our inbox at a manageable level, we’re closing issues that have been on the backlog for a long time but haven’t gained traction or that are not actionable. Thank you for your time and understanding.
