### ISSUE TITLE
Unbound breakpoint popup

### ISSUE THREAD

**Issue by MarchandMD** [microsoft/vscode#186831]
Type: <b>Bug</b>

1. Launch a node process that has a "attach" debugger
2. try to set a breakpoint

If the breakpoint is an "unbound breakpoint" there is a popup screen that appears; the popup has a link to "troubleshoot your launch configuration", but as soon as I move my mouse, the pop up disappears!

VS Code version: Code 1.79.2 (Universal) (695af097c7bd098fbf017ce3ac85e09bbc5dda06, 2023-06-14T08:58:52.392Z)
OS version: Darwin arm64 20.6.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|8.00GB (0.11GB free)|
|Process Argv|--crash-reporter-id bb98004e-8ecb-417d-b574-ae93e552ea43|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (32)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-erb-beautify|ali|0.4.0
rails|bun|0.17.8
vscode-gemfile|bun|0.4.2
solargraph|cas|0.24.0
path-intellisense|chr|2.8.4
erb|Cra|0.0.1
githistory|don|0.6.20
prettier-vscode|esb|9.19.0
font-switcher|eva|4.1.0
auto-rename-tag|for|0.1.10
latex-workshop|Jam|9.12.2
rspec-snippets|kar|0.0.4
theme-1|Mar|1.2.6
ruby-rubocop|mis|0.8.6
vscode-docker|ms-|1.25.2
remote-containers|ms-|0.295.0
live-server|ms-|0.4.8
emoji|Per|1.0.1
material-icon-theme|PKi|4.28.0
ruby|reb|0.28.1
vscode-yaml|red|1.13.0
LiveServer|rit|5.7.9
ruby-lsp|Sho|0.3.5
slim|sia|0.1.2
shopify-liquid|sis|3.2.2
code-spell-checker|str|2.20.5
learn-vim|vin|0.0.28
simple-ruby-erb|vor|0.2.1
vscode-icons|vsc|12.4.0
vscode-ruby|win|0.28.0
markdown-all-in-one|yzh|3.5.1
html-css-class-completion|Zig|1.20.0

(7 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
py29gd2263:30776702
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
vsccc:30610678
3biah626:30602489
pyind779:30671433
f6dab269:30613381
pythonsymbol12:30671437
a9j8j154:30646983
showlangstatbar:30737416
vsctsb:30748421
pythonms35:30701012
a2ce3375:30757347
7ij38806:30736111
pythonfmttext:30731395
pythoncmv:30756943
fixshowwlkth:30771522
pythongtdpath:30769146
bgfeh915:30780428
pythonnosmt12:30779714
pythonidxpt:30772539
pythonnocebcf:30776496

```

</details>

**Comment by MarchandMD** [comment]
This is probably more due to my inability to work with the debugger, but the fact that the popup disappears when I move my mouse, I'm not able to link to the recommended troubleshooting docs

**Comment by roblourens** [comment]
It is a hover but should stick around when you move your cursor over the hover widget. Is it in the wrong place? Can you share a screen recording?

**Comment by MarchandMD** [comment]
ya know what, i'm going to close this issue. 

This was occurring because of how I was configuring the `launch.json`... and through trial and error, I was able to properly attach the debugger to the correct file/process.
