### ISSUE TITLE
Keep diff editors after window reload

### ISSUE THREAD

**Issue by josh-tepper** [microsoft/vscode#18681]
- VSCode Version: Code 1.8.1 (ee428b0eead68bf0fb99ab5fdc4439be227b6281, 2016-12-19T14:42:49.304Z)
- OS Version: Darwin x64 15.6.0
- Extensions:

|Extension|Author|Version|
|---|---|---|
|vscode-docker|PeterJausovec|0.0.11|
|ActiveFileInStatusBar|RoscoP|1.0.2|
|githistory|donjayamanne|0.1.5|
|python|donjayamanne|0.5.6|
|Go|lukehoban|0.6.52|
|cpptools|ms-vscode|0.9.3|
|Ruby|rebornix|0.10.4|
|java|redhat|0.0.9|
|annotator|ryu1kn|0.10.1|
|vscode-open-in-github|sysoev|1.3.1|
|Material-theme|zhuangtongfa|1.0.3|
|vscode-proto3|zxh404|0.0.7|

---

Steps to Reproduce:

1. Open a diff tab in the editor by clicking on one of the changes in the git view
2. Install an update to an extension
3. Click on the "reload" button next to the newly updated extension
4. When the window is reloaded, all the tabs are preserved except for the diff tab.

**Comment by dbaeumer** [comment]
Not sure if @joaomoreno or @bpasero

**Comment by joaomoreno** [comment]
@bpasero This goes in the direction of having a diff input just be another resource.

**Comment by bpasero** [comment]
Yes, and the decision has to be made if every resource should just be restored blindly on restart. It could well be that a resource is not valid anymore between restarts.

**Comment by joaomoreno** [comment]
That would be handled by the resource provider not returning any content for it.

**Comment by bpasero** [comment]
@joaomoreno there is no resource content provider involved for a tab that is not active...
