### ISSUE TITLE
Weird text overlap glitch

### ISSUE THREAD

**Issue by FallibleCanine** [microsoft/vscode#186830]
![Screenshot 2023-07-01 11 56 06 AM](https://github.com/microsoft/vscode/assets/138325916/523fb600-96ea-42c8-afe6-9174e3072386)
Type: <b>Bug</b>

Pretty consistently, get this weird overlapping text error on certain text, where it's like it's printing something else under it. Temporarily goes away when I click into it? I'm not sure, but I think the underlaid text might be the text from a couple lines above.

VS Code version: Code 1.79.2 (695af097c7bd098fbf017ce3ac85e09bbc5dda06, 2023-06-14T08:59:55.818Z)
OS version: Linux x64 5.15.108-18910-gab0e1cb584e1
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i3-1115G4 @ 3.00GHz (4 x 2995)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|0, 0, 0|
|Memory (System)|6.49GB (1.54GB free)|
|Process Argv|--unity-launch --crash-reporter-id 0ff1793c-fb28-4226-85d9-715ed4f0bae0|
|Screen Reader|no|
|VM|100%|
|DESKTOP_SESSION|undefined|
|XDG_CURRENT_DESKTOP|X-Generic|
|XDG_SESSION_DESKTOP|undefined|
|XDG_SESSION_TYPE|undefined|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
isort|ms-|2022.8.0
python|ms-|2023.10.1
vscode-pylance|ms-|2023.6.40
jupyter|ms-|2023.5.1101742258
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.15
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-slideshow|ms-|0.1.5

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscorecescf:30445987
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
py29gd2263:30776702
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
3biah626:30602489
pyind779:30671433
89544117:30613380
pythonsymbol12:30671437
2i9eh265:30646982
showlangstatbar:30737416
vsctsb:30748421
pythonms35:30701012
03d35959:30757346
ecj1e332:30736112
pythonfmttext:30731395
pythoncmv:30756943
fixshowwlkth:30771522
pythongtdpath:30769146
bgfeh915:30780428
pythonnosm12tcf:30779713
pythonidxptcf:30772540
pythonnocebcf:30776496
cmakestatusbarv2:30779594

```

</details>

**Comment by hediet** [comment]
Can you provide repro steps? Does it repro after a system start?
I'm very curious what the dev tools say.
Thanks!

**Comment by ferreteleco** [comment]
Bringing back #173296, might be related.

**Comment by FallibleCanine** [comment]
> Can you provide repro steps? Does it repro after a system start?

Hmm. It just happens every time, pretty much. I think it started about 6 months ago?
I'll try to keep an eye out for what happens just prior to it occurring.

**Comment by hediet** [comment]
Closing due to missing repro steps and lack of other users who have the same problem.
