### ISSUE TITLE
List snippet

### ISSUE THREAD

**Issue by amenefus** [Microsoft/vscode#18683]
- VSCode Version: Code 1.8.1 (ee428b0eead68bf0fb99ab5fdc4439be227b6281, 2016-12-19T14:49:23.350Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

|Extension|Author|Version|
|---|---|---|
|path-intellisense|christian-kohler|1.2.0|
|code-runner|formulahendry|0.6.5|
|cs-syntax-visualizer|itn3000|0.0.2|
|csharpextensions|jchannon|1.1.0|
|vscode-todo|MattiasPernhult|0.8.0|
|quicksnippet|mousetraps|0.0.1|
|csharp|ms-vscode|1.6.2|
|omnisharp|ms-vscode|0.3.3|
|Theme-MaterialKit|ms-vscode|0.1.1|

---

Steps to Reproduce:

1.  Tried to create a list but the c# snippet  is not recognize it. not snippet and when i run in console it contains exception.

**Comment by dbaeumer** [comment]
@amenefus without the additional information we can't work on this issue. Please ping when the information is available and we will reopen the issue.
