### ISSUE TITLE
revealRange won't scroll horizontal with default reveal type.

### ISSUE THREAD

**Issue by aioutecism** [Microsoft/vscode#1868]
https://code.visualstudio.com/docs/extensionAPI/vscode-api#TextEditor.revealRange

`revealRange` wouldn't scroll horizontally with default reveal type `TextEditorRevealType.Default`.
`TextEditorRevealType.InCenterIfOutsideViewport` and `TextEditorRevealType.InCenter` works fine btw.

**Comment by aioutecism** [comment]
:+1:

**Comment by alexandrudima** [comment]
Thanks for reporting and sorry about it slipping through! :+1:
