### ISSUE TITLE
Recommended workspace extensions are not prompted after dev container is recreated

### ISSUE THREAD

**Issue by mehmetgiritli** [microsoft/vscode#186867]
Type: <b>Bug</b>

We use docker containers (of our own) and using "Attach to a running container"  feature of dev containers, we get connected to these in VS Code.

In a remote folder in container, we have a .vscode folder with recommended extensions. This works quite well, but only the first time.

When the remote workspace is opened which contains the recommended extensions settings, it will ask and install them when accepted.

However, if the containers are recreated after this, it will no longer ask to install recommended extensions. And since the containers are recreated, the extensions which were previously installed into the container are all gone.

The only way I could find to make VSCode to ask avbout the recommended extensions again is by going to the host computer and removing .config/Code folder. Once I do that and connect to the recreated container again, I will get the recommendations question.

It would be great to be able to avoid this. I'm not sure if it is a bug or just a missing feature. I think this should be considered a bug.

VS Code version: Code 1.79.2 (695af097c7bd098fbf017ce3ac85e09bbc5dda06, 2023-06-14T08:59:55.818Z)
OS version: Linux x64 6.4.0-gentoo
Modes:
Remote OS version: Linux x64 6.4.0-gentoo

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 5700G with Radeon Graphics (16 x 4336)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|0, 1, 1|
|Memory (System)|30.76GB (8.49GB free)|
|Process Argv|--unity-launch --crash-reporter-id ef329fbd-6ee2-4e4e-ae97-8c564886dba7|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|gnome|
|XDG_CURRENT_DESKTOP|GNOME|
|XDG_SESSION_DESKTOP|gnome|
|XDG_SESSION_TYPE|x11|

|Item|Value|
|---|---|
|Remote|Container universityofabdn/workspace-built:latest (workspace)|
|OS|Linux x64 6.4.0-gentoo|
|CPUs|AMD Ryzen 7 5700G with Radeon Graphics (16 x 4566)|
|Memory (System)|30.76GB (8.50GB free)|
|VM|0%|
</details><details><summary>Extensions (20)</summary>

Extension|Author (truncated)|Version
---|---|---
remote-containers|ms-|0.295.0
npm-intellisense|chr|1.4.4
redis-xplorer|Dav|1.2.7
vscode-eslint|dba|2.4.2
composer-php-vscode|DEV|1.36.13417
phptools-vscode|DEV|1.36.13417
profiler-php-vscode|DEV|1.36.13417
githistory|don|0.6.20
vscode-duplicate|mrm|1.2.1
vscode-docker|ms-|1.25.2
sqltools|mtx|0.28.0
sqltools-driver-mysql|mtx|0.6.0
phpstan-vscode|San|2.2.25
vscode-blade-formatter|shu|0.20.15
code-spell-checker|str|2.20.5
vscode-stylelint|sty|1.2.4
shellcheck|tim|0.32.6
vscode-phpsab|val|0.0.16
volar|Vue|1.8.3
vscode-typescript-vue-plugin|Vue|1.8.3

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
py29gd2263:30776702
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
282f8724:30602487
pyind779:30671433
f6dab269:30613381
pythonsymbol12:30671437
a9j8j154:30646983
showlangstatbar:30737416
vsctsb:30748421
pythonms35:30701012
03d35959:30757346
pythonfmttext:30731395
pythoncmvfstrcf:30756944
fixshowwlkth:30771522
pythongtdpath:30769146
i26e3531:30780429
pythonnosmt12:30779714
pythonidxptcf:30772540
pythonnocebcf:30776496

```

</details>

**Comment by sandy081** [comment]
Can you please check if these extensions are installed locally too?

**Comment by mehmetgiritli** [comment]
> Can you please check if these extensions are installed locally too?

Hi there. No, these extensions are not installed locally.
