### ISSUE TITLE
Cannot open Disassembly view when focus on other WebView

### ISSUE THREAD

**Issue by QuocDoBV** [microsoft/vscode#186838]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.79.2
- OS Version: all version

Steps to Reproduce:

1. Open other WebView
2. Open Disassembly view
-> The Disassembly view cannot open.
Note: If we focus to another editor, we can open Disassembly view
I guess that below condition make the Disassembly view cannot open:
`precondition: CONTEXT_FOCUSED_STACK_FRAME_HAS_INSTRUCTION_POINTER_REFERENCE, `

**Comment by QuocDoBV** [comment]
When I open a WebView in my own extension, I cannot open Disassembly view after that.
![image](https://github.com/microsoft/vscode/assets/111261098/8feeba80-fa21-495b-8407-8280f707e09e)
But when I focus on an editor then opening Disassembly view, the view can open
![image](https://github.com/microsoft/vscode/assets/111261098/09d999a8-6ab9-4dcb-9023-41186ae67463)
![image](https://github.com/microsoft/vscode/assets/111261098/3b80b1e5-9ac2-42e9-a4a0-8ba1b487ccf7)

**Comment by mjbvz** [comment]
Please start by filing this against the extension that provides the disassembly view

**Comment by QuocDoBV** [comment]
hi @mjbvz, 
Could you explain more detail about this. Why did you close it?

**Comment by QuocDoBV** [comment]
other issue is being discussed at https://stackoverflow.com/questions/75060035/vscode-open-disassembly-view-is-not-opened-when-no-opened-editor
