### ISSUE TITLE
C# Debugging very slow in codespaces

### ISSUE THREAD

**Issue by arnoldpistorius** [microsoft/vscode#186844]
When I debug my C# code in Github Codespaces, it takes minutes before the debugger is initialized and the first breakpoint is hit. Also stepping through code takes 5-10s per code line. When I do this on my local VS Code installation, it is fast (within a second). Also running in devcontainers in docker seems to work correctly.

It seems this behaviour only applies to when debugging a unit test or attaching a debugger later to a running dotnet process. When I start debugging by pressing F5, everything is fine.

I tried both stable and insider versions of codespaces, but neither gives the correct performance. The specs of the codespace is the 4 cpu cores variant (the highest I can select).

Version: 1.80.0-insider
Commit: 39efe30bfc8e196f5be2119479092bd9eb83e174
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36
Embedder: codespaces

**Comment by roblourens** [comment]
Please file on the C# extension, thanks
