### ISSUE TITLE
Large amount of CompletionItems returned by CompletionItemProvider causes significant lag

### ISSUE THREAD

**Issue by Janne252** [Microsoft/vscode#18682]
If a CompletionItemProvider implementation returns a large amount of CompletionItems, it causes the text editor to lag while typing. What can be done to reduce the lag?

- VSCode Version: 1.8.1
- OS Version: Windows 10 Pro, 1607

Steps to Reproduce:

The "issue" can be reproduced with this test extension: [Janne252/vscode-test-completionItemProvider](https://github.com/Janne252/vscode-test-completionItemProvider) (see the readme for additional steps)

Some background:

I'm working on an extension for a video game's internal scripting language. This language has a rather large API which results in a total of 6313 completionItems from various kinds of sources, which I have dumped to a single .json file for demonstration.

**Comment by jrieken** [comment]
@Janne252 Can you be a little more precise please? What lack to you mean? I see a short time of 'Loading...' which is basically what it takes to call all providers and to build the completion model but from then on I don't see any lack when typing

![jan-18-2017 10-52-48](https://cloud.githubusercontent.com/assets/1794099/22059290/74f011a2-dd6c-11e6-90ef-43dd9b7213a0.gif)


Please open dev tools, and run a CPU profile for the scenario that is slow for you. That should allow us to understand this bestter

**Comment by Janne252** [comment]
@jrieken Absolutely. Here's 2 recordings that should demonstrate the issue:

**Without the massive CompletionItemProvider:**
![](http://i.imgur.com/sxdjhkb.gif)

**With the massive CompletionItemProvider:**
![](http://i.imgur.com/Hq3Wzmy.gif)

The lag is most noticeable while typing multiple short words, like passing local variables to a function call. Perhaps I'm over-exaggerating the issue a bit.

**Comment by jrieken** [comment]
Ok, I can reproduce but not as easy as you can. Do you have the `editor.quickSuggestionsDelay`-setting? 

I'll see how this can be made faster on our side, basically we are still filtering the list of 6000+ items when the next character wants to be inserted. We should be faster (or cancel earlier) but on your side you could also return less suggestion if that is possible

**Comment by Janne252** [comment]
No, I don't have editor.quickSuggestionsDelay set. It would be great if the process can be made faster. It's a bit problematic when the public API is so ridiculously long and with standard lua, they are all exposed in the global namespace, so reducing the number of returned suggestions is not really an option.

**Comment by jrieken** [comment]
Yeah, I will make it faster and already found one or two things. To validate my theories, I would be helpful if you can create profile and share it with me. Do the following

* hit 'F1 > Developer Tools'
* in there select 'Profiles' and start a 'CPU profile'
* type with suggestions and lack for a few seconds
* stop the profiler, save, and share it the profile with me

Thanks

**Comment by Janne252** [comment]
[CPU-20170118T182734.zip](https://dl.dropboxusercontent.com/u/49227828/CPU-20170118T182734.zip)

For reference, I typed the following text and then waited for about 5 seconds before ending the recording:
`This is a test and the test goes on and on and on. Now pausing.`

**Comment by jrieken** [comment]
Things we should look into

* [ ] debounce filtering while typing
* [ ] first filter, then sort (when retrieving results)
* [ ] run object track logic inside deserialise logic (when retrieving results)

**Comment by jrieken** [comment]
@Janne252 So far I have the communication between the main side and the extension host a lot faster. You should feel this when suggestions are requested freshly for a new word. Also I have made small improvements in how often and how we filter. That should make a small difference when we filter down the 6000+ suggestions against the word you are just typing... The changes will be in tomorrows insiders build and I'd be happy to get some early feedback.

**Comment by Janne252** [comment]
@jrieken How do I know when a new insiders build is out? 
The date suggests that I have the  today's version.
![](http://i.imgur.com/Mu52mAE.png)

**Comment by jrieken** [comment]
That's good. There is an update every day and you should already have some performance improvements. It would be helpful if you can do another profiler run

**Comment by Janne252** [comment]
@jrieken Here you go: [CPU-20170125T172131.zip](https://dl.dropboxusercontent.com/u/49227828/CPU-20170125T172131.zip)

**Comment by jrieken** [comment]
The match/score performance will be tackled in https://github.com/Microsoft/vscode/issues/22153

**Comment by jrieken** [comment]
Closing this as scoring, sending/receiving items, and finally garbage collection spying has been improved. This has served as a great issue to tackle various issues and I hope things are better now. I will keep the sample extensions for the future and I will continue with performance work here and there.
