### ISSUE TITLE
Vastly simplify the API proposal type installation

### ISSUE THREAD

**Issue by zm-cttae** [microsoft/vscode#186842]
## Problem statement

* **As a:** extension developer who consumes proposed APIs in extensions & libraries
* **I want to:** install and wire proposed APIs automatically in a static manner (without a CLI)
* **So that:** I can reduce entropy and build script sizes in my codebases :)

## State of the art

I use a special script to download the proposals and generate a triple-slash reference wiring.
The output looks something like:

```typescript
/// <reference path="../../vscode.proposed.tokenInformation.d.ts" />
/// <reference path="../../vscode.proposed.terminalDataWriteEvent.d.ts" />
```

## Proposed solution

We need static type packages to augument the existing @types/vscode package.
This would follow the NPM package pattern `@vscode/types/*`.

The extension authors could then install them using something like:

```console
$ npm install @vscode/types/token-information --save-dev
```

**Comment by jrieken** [comment]
This more or less exists as you have asked for and is the recommended way of consuming proposed API. See https://www.npmjs.com/package/@vscode/dts

**Comment by zm-cttae** [comment]
I think this is too far away from the normal method of installing type definitions but OK.

**Comment by zm-cttae** [comment]
I think this is workable in current form, with a small wiring build script, & a postinstall trigger

**Comment by zm-cttae** [comment]
```javascript
'use strict';

const shelljs = require('shelljs');
const path = require('path');
const fs = require('fs');
const prettier = require('prettier');

const enabledApiProposals = require('../package.json').enabledApiProposals;

const root = path.relative(__dirname, '..');

shelljs.exec('npx @vscode/dts dev');

for (const proposal of enabledApiProposals) {	
	let definitionSrc = fs.readFileSync(path.resolve(root, `./src/vscode.proposed.${proposal}.d.ts`))
	const prettierrcJson = require('../.prettierrc.json');
	definitionSrc = prettier.format(definitionSrc, prettierrcJson);
	fs.writeFileSync(path.resolve(root, `./typings/proposals/vscode.proposed.${proposal}.d.ts`), definitionSrc);
	shelljs.rm('-f', path.resolve(root, `vscode.proposed.${proposal}.d.ts`));
}

const declarationSrc = enabledApiProposals.map(fromProposalToPath).join('\n');
fs.writeFileSync(path.resolve(root, `./typings/proposals/index.d.ts`), declarationSrc);

function fromProposalToPath(proposal) {
	return `/// <reference path="./vscode.proposed.${proposal}.d.ts" />`;
}
```
