### ISSUE TITLE
Support line number fragment in vscode.open command

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#18696]
Example:

```ts
vscode.commands.executeCommand(
    'vscode.open',
    vscode.Uri.parse('file:///Users/matb/projects/sand/readme.md#L281'));
```

**Expected**
Opens file and jumps to requested line. This is what happens if you click on a link that uses that path. 

**Actual**
Opens file but ignores the line argument.

**Comment by bpasero** [comment]
@mjbvz can you explain the use case for this? why can you not use the `showTextDocument` API and reveal the line/column on the editor?

**Comment by mjbvz** [comment]
This is not a priority, I was just confused by the inconsistency of how links are handled in these cases.

`vscode.open` does provide some useful extra functionality (such as prompting users if the target file does not exist). Implementing the logic to open a file and go to a line number using `showTextDocument` also requires a few lines of code. Mainly though, as an extension author, I kind of just expected this to work and had to look into the implementation of `vscode.open` to see why it did not.

**Comment by jrieken** [comment]
Closing because we want folks to use the `showTextDocument`-api method
