### ISSUE TITLE
Search not excluding configured folders

### ISSUE THREAD

**Issue by burtonrodman** [microsoft/vscode#186942]
Type: <b>Bug</b>

I have many of the typical folders excluded in my User Settings:
**/.git, **/.vs, **/bin, etc...

However when I search I am receiving results from within theses folders.

VS Code version: Code 1.79.2 (695af097c7bd098fbf017ce3ac85e09bbc5dda06, 2023-06-14T08:57:04.379Z)
OS version: Windows_NT x64 10.0.22621
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz (16 x 2304)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.73GB (9.24GB free)|
|Process Argv|--folder-uri file:///c%3A/source/whirlwindbuildings/CustomApps/ShippingCommandCenter --crash-reporter-id 24452be9-7e87-49ef-aeb5-c1b3aefe6bde|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (41)</summary>

Extension|Author (truncated)|Version
---|---|---
add-reference|adr|1.0.2
libman|adr|1.0.1
doxdocgen|csc|1.4.0
vscode-eslint|dba|2.4.2
githistory|don|0.6.20
gitlens|eam|14.0.1
EditorConfig|Edi|0.16.4
prettier-vscode|esb|9.19.0
vscode-firefox-debug|fir|2.9.8
auto-rename-tag|for|0.1.10
rest-client|hum|0.25.1
better-cpp-syntax|jef|1.17.2
compare-folders|mos|0.22.5
vscode-bicep|ms-|0.18.4
vscode-docker|ms-|1.25.2
blazorwasm-companion|ms-|1.1.4
csdevkit|ms-|0.1.103
csharp|ms-|2.0.248
vscode-dotnet-runtime|ms-|1.6.0
vscodeintellicode-csharp|ms-|0.1.23
vscode-edge-devtools|ms-|2.1.2
remote-containers|ms-|0.295.0
remote-ssh|ms-|0.102.0
remote-wsl|ms-|0.79.5
azure-account|ms-|0.11.5
cmake-tools|ms-|1.14.34
cpptools|ms-|1.16.3
cpptools-extension-pack|ms-|1.3.0
live-server|ms-|0.4.8
powershell|ms-|2023.6.0
remote-explorer|ms-|0.4.0
test-adapter-converter|ms-|0.1.8
vsliveshare|ms-|1.0.5873
vscode-jest|Ort|5.2.3
vscode-nuget-gallery|pat|0.0.24
LiveServer|rit|5.7.9
vscode-coverage-gutters|rya|2.11.0
code-spell-checker|str|2.20.5
es6-string-html|Tob|2.12.1
cmake|twx|0.0.17
vscode-icons|vsc|12.4.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263:30335439
vscoreces:30445986
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
py29gd2263:30776702
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
282f8724:30602487
pyind779:30671433
89544117:30613380
pythonsymbol12:30671437
showlangstatbar:30737416
vsctsb:30748421
pythonms35:30701012
03d35959:30757346
24365598:30736109
pythonfmttext:30731395
pythoncmvfstrcf:30756944
fixshowwlkth:30771522
hideindicator:30766889
pythongtdpath:30769146
bgfeh915:30780428
pythonnosmt12:30779714
pythonidxpt:30772539
pythonnoceb:30776495

```

</details>

**Comment by burtonrodman** [comment]
![image](https://github.com/microsoft/vscode/assets/7658657/8c83b270-2b7c-41f5-8d53-9041211f4cb2)

**Comment by burtonrodman** [comment]
![image](https://github.com/microsoft/vscode/assets/7658657/61cc55ed-87ba-418e-93f6-b7705688a68b)

**Comment by burtonrodman** [comment]
![image](https://github.com/microsoft/vscode/assets/7658657/ee9f3728-0460-49a3-8c1f-edfe25046ca5)

**Comment by burtonrodman** [comment]
![image](https://github.com/microsoft/vscode/assets/7658657/04f248e2-4d5f-4ea4-9115-73a4334c586f)

**Comment by gjsjohnmurray** [comment]
Did you notice the message "Exclude settings and ignore files are disabled"?

**Comment by burtonrodman** [comment]
no.  thank you for pointing that out.  closing
