### ISSUE TITLE
Inline chat diff incorrect when whole file is selected

### ISSUE THREAD

**Issue by ulugbekna** [microsoft/vscode#186901]
# Description

Notice how the diff shows the whole file outside the diff but also the whole file in the diff: 

<img width="1485" alt="image" src="https://github.com/microsoft/vscode/assets/16353531/f9df4696-044c-4a77-90fd-a6b990da2c67">

(I've filed an issue for this before but can't find it anymore -- I think it was closed as fixed by changing the diff mode to `live` when the whole file is selected, but I still somehow get this bug)

# Screencast: 

https://github.com/microsoft/vscode/assets/16353531/113ec882-2b05-488c-b07d-8d6cef6f3b2f

# Repro 

1. Select whole file
2. Trigger inline chat & ask something that will show a diff - 🐞

# Version 

```
Version: 1.80.0-insider
Commit: 5b7440441bbd2548a862f7321cafdfa1597132e5
Date: 2023-06-30T21:17:11.593Z
Electron: 22.3.14
ElectronBuildId: 21893604
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Darwin arm64 22.5.0
```

**Comment by jrieken** [comment]
> Select whole file

That's the reason for this. The diff ranges are extended by the selection/whole range in order to preserve context. And yeah, not being able to hide everything is tracked in another issues (which is still open)
