### ISSUE TITLE
Merge conflicts not displayed in editor

### ISSUE THREAD

**Issue by blntptr** [microsoft/vscode#186900]
Type: <b>Bug</b>

Have 2 branches and edit the same file on the 2 branches to create a merge conflict, merge 1 branch into another and check if conflicts are shown

VS Code version: Code 1.79.2 (695af097c7bd098fbf017ce3ac85e09bbc5dda06, 2023-06-14T08:57:04.379Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-10300H CPU @ 2.50GHz (8 x 2496)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|7.84GB (1.02GB free)|
|Process Argv|C:\\Users\\blntp\\finso3-client --crash-reporter-id c0bb605e-8d5e-462b-9063-7f2b58174c99|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-intelephense-client|bme|1.9.5
vetur|oct|0.37.3
laravel-blade|one|1.34.0
laravel5-snippets|one|1.17.0
LiveServer|rit|5.7.9
vue-vscode-snippets|sdr|3.1.1
vscode-icons|vsc|12.4.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
py29gd2263:30776702
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
3biah626:30602489
pyind779:30671433
89544117:30613380
pythonsymbol12:30671437
a9j8j154:30646983
showlangstatbar:30737416
vsctsb:30748421
pythonms35:30701012
03d35959:30757346
pythonfmttext:30731395
pythoncmvfstrcf:30756944
fixshowwlkth:30771522
pythongtdpath:30769146
i26e3531:30780429
pythonnosm12tcf:30779713
pythonidxpt:30772539
pythonnocebcf:30776496

```

</details>

**Comment by hediet** [comment]
Can you share some screenshots? Thanks!

**Comment by blntptr** [comment]
Thanks. Sure, here's a screeshot of a file that apparently has some conflicts, the highlight are missing on the file map side bar on the right as well as the file itself [click here](https://prnt.sc/-a81WN7Yy2yw)

**Comment by hediet** [comment]
Can you run `git status` and share the result?

**Comment by blntptr** [comment]
Thanks, please see below:
[First part](https://prnt.sc/e-i2qdqodGlI)
[Second part](https://prnt.sc/dtTEEtlsty5m)

**Comment by hediet** [comment]
The merge editor cannot handle delete/modified conflicts (only modified/modified).

**Comment by blntptr** [comment]
I am trying to see modified / modified conflicts, that's the case for the 3 files mentioned above.

**Comment by hediet** [comment]
You cannot re-resolve conflicted files that were auto-merged by git

**Comment by blntptr** [comment]
Ok thanks, then I am wondering why doesn't it allow me to finish the merge, commit and push
