### ISSUE TITLE
Refresh should not change focus in explorer

### ISSUE THREAD

**Issue by andi1984** [Microsoft/vscode#18690]
If we refresh the explorer files the currently opened file is focussed file in the explorer afterwards. In my opinion the explorer focus should stay as it is instead of moving it if I only want to refresh the file list.

- VSCode Version: 1.8.1
- OS Version: Mac OS Sierra 10.12.2

Steps to Reproduce:

1. In a project open a file in a tab
2. Select/focus now another element in the explorer
3. Refresh explorer

**Comment by bpasero** [comment]
Works with `"explorer.autoReveal": false` in settings.
