### ISSUE TITLE
Moved Code Detection: Lines Are Not Visible

### ISSUE THREAD

**Issue by hediet** [microsoft/vscode#186918]
How it is:
![chrome_ANekuDKdIc](https://github.com/microsoft/vscode/assets/2931520/de2afbc7-7840-49c8-bd75-ed909b8e2c12)

How it should be:
![vTZF1qwxuf](https://github.com/microsoft/vscode/assets/2931520/b76298eb-1548-4661-a86d-2f1b298b17ed)

**Comment by alexr00** [comment]
Closing for verification.
