### ISSUE TITLE
Better touch screen experience

### ISSUE THREAD

**Issue by wmertens** [microsoft/vscode#186990]
Touch should get more love. On Linux+Wayland, you can't even scroll the editor panes, and apparently on ChromeBooks too #98218. I'm creating a new issue because I'd like to get a more holistic approach to the feature.

Here's things touch is really great for, and should be prioritized:

- resizing panes
- moving tabs between groups
- scrolling panes
- tapping buttons

Here's what touch is bad at, and shouldn't be attempted:

- selecting text
- tapping small buttons

To handle the button issue, I propose that touch events must be very close to the center of buttons, and mistouches must be ignored. Perhaps buttons should have internal padding where they don't accept touch events.

The resizing really is a big thing - it's very annoying to resize panes by mouse, especially with a trackpad.

**Comment by d-bucur** [comment]
See my comment [here](https://github.com/microsoft/vscode/issues/98218#issuecomment-1631251531) on how to enable touch, which solves most of the use cases your describe. This seems more like a Weyland/X issue where touch is converted to mouse click events for all applications and proper touch is not supported. I think that Chromium bypasses the issue

**Comment by wmertens** [comment]
@d-bucur indeed most things are solved with that, thanks!

The only thing I can't seem to do with touch is moving editor tabs.

**Comment by d-bucur** [comment]
Yes, I actually prefer it this way. It means that you can use touch to scroll tabs horizontally when they don't fit on the screen. I would rather use touch to scroll through things than modify their state.

**Comment by wmertens** [comment]
@d-bucur sure, but I'd like to be able to for example, long tap + drag to move them.

**Comment by sbatten** [comment]
Thanks for taking the time to file the issue and looking through existing issues. Given the discussion here and existing number of touch related issues, I am going to close this issue as a dupe. If there is a specific case that you would like implemented and it is not covered by an existing issue, please file an issue per request so we can prioritize.
