### ISSUE TITLE
Cursor for `next issue` (F8) is not reset on build.

### ISSUE THREAD

**Issue by martincohen** [Microsoft/vscode#18695]
The `cpptools` produces a lot of `Include file not found in directory`, therefore it is essential to reset the cursor within the problems view to first item on next build. Otherwise the cursor just keeps keeping on pointing to me meaningless `Include file not found in directory` issues and never resets to begin of the list (I have to do that manually now).

- VSCode Version:
1.8.1
- OS Version:
Windows 10

Steps to Reproduce:

1. Open a file that is not part of the project that includes "unreachable" file so that `cpptools` produces `Include file not found` issue in problem view.
2. Build the project.

**Comment by dbaeumer** [comment]
@sandy081 starting with you. I think even if the cpptools would like to do that they wouldn't be able to do so. Could we add a button to the UI?. This might need support in the task framework as well if the cpptools build using a task.

**Comment by martincohen** [comment]
I've already reported the issue to `cpptools`, they sent me here. Their issue is with parsing a file that clearly doesn't belong to the project (not in project root, nor on include path), plus another issue with keeping the errors in the log even after such file is closed.

**Comment by sandy081** [comment]
@martincohen By default Problems view is linked to the current opened editor. There is a setting `problems.autoReveal` that controls this. May be disabling this setting will help you. Can you please try and let us know the experience?

**Comment by sandy081** [comment]
Please reopen it with the requested information from above comment. Thanks.
