### ISSUE TITLE
Go to Bracket should reveal new cursor position

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#18693]
- VSCode Version: Code - Insiders 1.9.0-insider (f67f87c5498d9361c0b29781c341fd032815314b, 2017-01-17T07:04:34.904Z)
- OS Version: Darwin x64 15.6.0
- Extensions:

|Extension|Author|Version|
|---|---|---|
|EditorConfig|EditorConfig|0.3.4|
|autofilename|JerryHong|0.1.3|
|vscode-docker|PeterJausovec|0.0.11|
|azure-cli|chrmarti|0.2.0|
|regex|chrmarti|0.0.7|
|vscode-eslint|dbaeumer|1.2.2|
|ghlink|dt|0.0.4|
|tslint|eg2|0.8.1|
|vscode-scss|mrmlnc|0.6.0|
|PowerShell|ms-vscode|0.8.0|
|cpptools|ms-vscode|0.9.3|
|debugger-for-chrome|msjsdiag|2.4.2|
|diff|rafaelmaiolla|0.0.1|
|vscode-open-in-github|sysoev|1.3.1|

---

Steps to Reproduce:

1. Position cursor at curly brace with its opposite being offscreen
2. Go to Bracket
3. Observe the cursor has move and its new position is offscreen
4. Expected: The new cursor position should be scrolled into view

**Comment by alexandrudima** [comment]
Dup of #18645
