### ISSUE TITLE
Debug does not stop executing when trying to stop debugging after hitting a breakpoint.

### ISSUE THREAD

**Issue by thealphamoose** [microsoft/vscode#186996]
Type: <b>Bug</b>

Debug does not stop executing when I tried to stop debugging after hitting a breakpoint. I found this problem reported Aug 18,2020 and the solution from Microsoft was to install the most recent release. But I have the most recent 1.79.2. Visual Studio Code
My app is written in python/Django. It used to work three months ago but since I have returned to the app for some changes my VSC must have updated to 1.79.2 and now this issue has appeared. 

Details: When I set a breakpoint and it is tripped, the code execution stops normally. I can step, I can continue, all is good. But when I STOP (the red button on the ribbon) the program continues executing. If I hit stop a second time the program does stop but a great deal of code has been executed between the first and second clicks.

VS Code version: Code 1.79.2 (695af097c7bd098fbf017ce3ac85e09bbc5dda06, 2023-06-14T08:59:55.818Z)
OS version: Linux x64 5.15.0-76-generic snap
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 3600 6-Core Processor (12 x 2800)|
|GPU Status|2d_canvas: unavailable_software<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>opengl: disabled_off<br>rasterization: disabled_software<br>raw_draw: disabled_off_ok<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software<br>webgpu: disabled_off|
|Load (avg)|2, 1, 1|
|Memory (System)|62.73GB (56.54GB free)|
|Process Argv|--no-sandbox --force-user-env --unity-launch --crash-reporter-id e7718076-72e9-4f77-8582-28e46196ba60|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|undefined|
|XDG_CURRENT_DESKTOP|GNOME|
|XDG_SESSION_DESKTOP|undefined|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
isort|ms-|2022.8.0
python|ms-|2023.10.1
vscode-pylance|ms-|2023.6.40
jupyter|ms-|2023.5.1101742258
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.15
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-slideshow|ms-|0.1.5
django-intellisense|sha|0.0.2
ayu|tea|1.0.5

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscoreces:30445986
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
py29gd2263:30776702
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
vscccc:30610679
3biah626:30602489
pyind779:30671433
89544117:30613380
pythonsymbol12:30671437
showlangstatbar:30737416
vsctsb:30748421
pythonms35:30701012
03d35959:30757346
pythonfmttext:30731395
pythoncmv:30756943
fixshowwlkth:30771522
showindicator:30766890
pythongtdpath:30769146
bgfeh915:30780428
pythonnosm12tcf:30779713
pythonidxptcf:30772540
pythonnoceb:30776495
cmakestatusbarv2:30779594

```

</details>

**Comment by roblourens** [comment]
Please file this on the vscode-python repo
