### ISSUE TITLE
function list(ctrl+shift+o) is too simple and ugly 

### ISSUE THREAD

**Issue by jasonshaw** [Microsoft/vscode#18698]
- VSCode Version: 1.8.1
- OS Version:windows 7 sp1

Steps to Reproduce:

1.
2.

we need a list of shortcuts named by function name instead of symbol such as function <function>
1.context function Intelligent perception
2.Shortcut key for function(by names) list

**Comment by dbaeumer** [comment]
@jasonshaw could you please make an example of what you expect using a code example. Your description is very hard to understand.

**Comment by jasonshaw** [comment]
1.first scene
![2016-04-28_130941](https://cloud.githubusercontent.com/assets/7032304/22093623/373047f2-de42-11e6-874f-5af30eb246e4.jpg)
above showed by shortjcut key "ctrl+shift+o"
can't see any function names
2.second scene
when coding in scipit tag of HTML， can't get any intelligent prompt of functions in js files imported

**Comment by jrieken** [comment]
@jasonshaw For the first sample, what language is that?

**Comment by mjbvz** [comment]
@jasonshaw Can you please provide some example code that shows this problem. 

TS returns anon functions and classes in their nav tree response, but we may want to filter them out of here or at least show some additional information about them, such as line number

**Comment by mjbvz** [comment]
Removed anon functions from the symbol. Please let us know how else the experience could be improved
