### ISSUE TITLE
Intellisense font is incredibly small.

### ISSUE THREAD

**Issue by mikeymop** [microsoft/vscode#186921]
Does this issue occur when all extensions are disabled?: **Yes**

- VS Code Version: `1.79.2`
- OS Version: Fedora 38 (`6.3.8-200.fc38.x86_64`)
- Device: Framework Laptop (2256x1504)

Steps to Reproduce:

1. Open Vscode 
2. Write some code such that vscode can provide a suggestion
3. Press ctrl + space to open intellisense
4. Observe the Intellisense font is incredibly small

![Screenshot from 2023-07-03 09-52-40](https://github.com/microsoft/vscode/assets/4002969/1df4c5ba-1b21-4fee-900e-2077fcded0d6)

**Comment by jrieken** [comment]
Looks like your `editor.suggestFontSize` setting has been tweaked
