### ISSUE TITLE
Window title is special char instead of normal text

### ISSUE THREAD

**Issue by MultiQSteen** [microsoft/vscode#186911]
Type: <b>Bug</b>

I just open visual studio code.
Problem also applies to popups.
If I push the GIT-syncronize in the lover left, all content is special chars.

VS Code version: Code 1.79.2 (695af097c7bd098fbf017ce3ac85e09bbc5dda06, 2023-06-14T08:59:55.818Z)
OS version: Linux x64 5.19.0-46-generic snap
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|12th Gen Intel(R) Core(TM) i7-1255U (4 x 2611)|
|GPU Status|2d_canvas: unavailable_software<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>opengl: disabled_off<br>rasterization: disabled_software<br>raw_draw: disabled_off_ok<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software<br>webgpu: disabled_off|
|Load (avg)|1, 1, 1|
|Memory (System)|3.82GB (1.58GB free)|
|Process Argv|--no-sandbox --force-user-env --unity-launch --crash-reporter-id c5632280-156e-4f5b-95ce-2af6560ad9d2|
|Screen Reader|no|
|VM|100%|
|DESKTOP_SESSION|ubuntu|
![Screenshot from 2023-07-03 14-55-12](https://github.com/microsoft/vscode/assets/108074892/2d5b635f-6a12-4965-b08e-3f95468e74c0)

|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|wayland|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-systemd-support|han|1.0.1
cmake-tools|ms-|1.14.34
cpptools|ms-|1.16.3
cpptools-extension-pack|ms-|1.3.0
cmake|twx|0.0.17
![Screenshot from 2023-07-03 14-32-44](https://github.com/microsoft/vscode/assets/108074892/f8227a30-2f6c-493a-88c0-31d7efd45631)

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
py29gd2263:30776702
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
2e4cg342:30602488
pyind779:30671433
f6dab269:30613381
pythonsymbol12:30671437
2i9eh265:30646982
showlangstatbar:30737416
vsctsb:30748421
pythonms35:30701012
03d35959:30757346
pythonfmttext:30731395
pythoncmvfstrcf:30756944
fixshowwlkth:30771522
pythongtdpath:30769146
i26e3531:30780429
pythonnosm12tcf:30779713
pythonidxpt:30772539
pythonnoceb:30776495

```

</details>

**Comment by MultiQSteen** [comment]
![Screenshot from 2023-07-03 15-03-55](https://github.com/microsoft/vscode/assets/108074892/9789b918-bcb3-45bb-868b-2b5b30c84cba)
Popup as described.

**Comment by rzhao271** [comment]
Does running VS Code with `--disable-gpu`, i.e. `code --disable-gpu`, help fix the issue?

**Comment by MultiQSteen** [comment]
Thanks for the suggestion. 
It didn't change anything, but when I disabled the 3D acceleration feature on my virtual machine it fixed the problem.
So, it must be related to gpu somehow.
