### ISSUE TITLE
After using Microsoft account to sync setting, unable to use Github account to sync setting

### ISSUE THREAD

**Issue by aeroxy** [microsoft/vscode#186988]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.79.2
- OS Version: macOS 13.4

Steps to Reproduce:

1. Account -> Sign In to Sync Setting -> Microsoft -> Done
2. Account -> Sign Out
3. Account -> Sign In to Sync Setting -> No option

Instead, we must turn off the sync first to get Github option back.

**Comment by sandy081** [comment]
Yes, this is expected flow - https://code.visualstudio.com/docs/editor/settings-sync#_switching-accounts
