### ISSUE TITLE
Unable to login on macOS Ventura and VS Code 1.79.2

### ISSUE THREAD

**Issue by ndebarnot** [microsoft/vscode#187053]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.79.2
- OS Version: 13.4.1

Steps to Reproduce:

1. Click "Sign in to sync settings in user menu"
2. Authenticate on GitHub

Everytime when I come back to VS Code I'm having a popup saying: "Having trouble logging in? Would you like to try a different way? (local server)"

I have 2FA set on Github but tried to disable it and still had the same issue.

**Comment by TheBlckbird** [comment]
same on windows

**Comment by TylerLeonhardt** [comment]
> Everytime when I come back to VS Code I'm having a popup saying: "Having trouble logging in? Would you like to try a different way? (local server)"


And what happens when you do this different way? GitHub auth can take you through 3 different flows to get you unblocked... can you please try those ways and let me know how it goes?

**Comment by ndebarnot** [comment]
Hi!

I don't know if something changed in 1.80.0 or maybe I didn't fully follow all the steps but I just did and ended up entering a 1-time code on Github to authorize the device and it's now working, I'm logged in in VSCode.

Thanks!

**Comment by TylerLeonhardt** [comment]
Glad you're unblocked! I'll go ahead and close this.
