### ISSUE TITLE
Permission denied and cannot connect to server on port 1337 using update50 and debug50.

### ISSUE THREAD

**Issue by SimonsBrother** [microsoft/vscode#187000]
See images; when I run "update50" as shown in the first image (I had blurred out the number to post the image in discord, in case it was confidential), I get an error to do with permission being denied and not being able to connect to extension server on port 1337. When I tried to run "debug50 tideman" as shown in second image, I seem to get a related problem, something with port 1337. If this isn't an issue, how do I fix this?

Version: 1.79.2
Commit: 695af097c7bd098fbf017ce3ac85e09bbc5dda06
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.5.1 Safari/605.1.15
Embedder: codespaces

<img width="606" alt="update50" src="https://github.com/microsoft/vscode/assets/86736629/8ebf086e-88a1-4159-8dd7-869b820b7996">
<img width="918" alt="debug50" src="https://github.com/microsoft/vscode/assets/86736629/89264e56-f7c6-4367-b9eb-c70706639aeb">

**Comment by roblourens** [comment]
This might be an issue with your configuration or the update50 tool, I don't know, but I don't think it's an issue with vscode itself.
