### ISSUE TITLE
Glob pattern in included files produces different results each time

### ISSUE THREAD

**Issue by qi55wyqu** [microsoft/vscode#187056]
Type: <b>Bug</b>

When using a glob pattern in "files to include" in the search bar such as `./workspace/path/to/**/*.py`, I get different results everytime I click on the refresh icon.
This is not the case when I only use a wildcard like `*.py`.

Tested with Version 1.79.2 and 1.80.0-insider.

Version: 1.79.2
Commit: 695af097c7bd098fbf017ce3ac85e09bbc5dda06
Date: 2023-06-14T08:59:55.818Z
Electron: 22.5.7
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Linux x64 5.15.0-76-generic snap

VS Code version: Code 1.79.2 (695af097c7bd098fbf017ce3ac85e09bbc5dda06, 2023-06-14T08:59:55.818Z)
OS version: Linux x64 5.15.0-76-generic snap
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz (16 x 2300)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|1, 2, 2|
|Memory (System)|30.97GB (12.49GB free)|
|Process Argv|--no-sandbox --force-user-env --unity-launch --crash-reporter-id 28e31990-950d-453b-bda3-028fa6c72c02|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
py29gd2263:30776702
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
3biah626:30602489
pyind779:30671433
89544117:30613380
vscrpc:30673769
pythonsymbol12:30671437
showlangstatbar:30737416
vsctsb:30748421
pythonms35:30701012
03d35959:30757346
pythonfmttext:30731395
pythoncmvfstrcf:30756944
fixshowwlkth:30771522
pythongtdpath:30769146
i26e3531:30780429
pythonnosmt12:30779714
pythonidxptcf:30772540
pythonnoceb:30776495
e537b577:30772215

```

</details>

**Comment by andreamah** [comment]
Are the results always missing some, or is it just sometimes whole and sometimes not? Are you hitting the limit to the number of files searched?

**Comment by qi55wyqu** [comment]
Thank you for looking into this. 

The number of results and the number of files with hits are different each time I refresh the search. 
The file limit is never reached.

**Comment by andreamah** [comment]
Hmm. Are you waiting until the search finishes? Can you provide a screen recording?

**Comment by qi55wyqu** [comment]
https://github.com/microsoft/vscode/assets/27998820/392de948-b576-42d2-82c0-8544939d368c

**Comment by andreamah** [comment]
I think this should be fixed by https://github.com/microsoft/vscode/pull/189289. It seems that there is supposed to be a message about hitting the file limit. The reason that it's much lower than the actual limit stated in the settings is because of a race condition documented in this issue: https://github.com/microsoft/vscode/issues/189359

**Comment by roblourens** [comment]
@qi55wyqu This should be fixed and we would appreciate you trying it out and letting us know if you still see the problem, thanks

**Comment by qi55wyqu** [comment]
> @qi55wyqu This should be fixed and we would appreciate you trying it out and letting us know if you still see the problem, thanks

I can confirm that it has been fixed. Thank you very much!
