### ISSUE TITLE
Can't copy code to Microsoft Word with style

### ISSUE THREAD

**Issue by King66** [Microsoft/vscode#18706]
- VSCode Version: Code 1.8.1 (ee428b0eead68bf0fb99ab5fdc4439be227b6281, 2016-12-19T14:49:23.350Z)
- OS Version: Windows_NT ia32 10.0.14393
Steps to Reproduce:

1. copy code from VS to Word, the color exists.
2. copy code from VSCode to Word, only plain text.

**Comment by rebornix** [comment]
Dup of https://github.com/Microsoft/vscode/issues/3518 . Let's track it there, thanks.
