### ISSUE TITLE
TerminalWordLinkDetector leaks memory

### ISSUE THREAD

**Issue by SvanT** [microsoft/vscode#187082]
Repro:
1. Open OSS
2. Open 10 terminals
3. Close the terminals
4. Take memory heap snapshot using developer tools
5. The 10 terminals is still allocated as they are locked by TerminalWordLinkDetector
 
![image](https://github.com/microsoft/vscode/assets/3172483/c0b97946-40ae-4fdd-97b7-cdd6cf5ed127)

**Comment by mjbvz** [comment]
I still see the leaked terminals although not from `TerminalWordLinkDetector` any more:


![Image](https://github.com/microsoft/vscode/assets/12821956/dd6ff979-ccd0-4345-86fc-fcdf3ac0927c)

I don't know the code well but one possible cause might be the difference between `_removeInstance` and `removeInstance` in `TerminalGroup`. `removeInstance` cleans up instance listeners, while `_removeInstance` does not

**Comment by jrieken** [comment]
`verified` but @Tyriar there is another leak with `BaseTerminalBackend` accumulating memory when opening/close terminal. I see their retains size grow as I repeat these steps
