### ISSUE TITLE
Outline members of a file in a panel

### ISSUE THREAD

**Issue by seigan** [Microsoft/vscode#18700]
I miss very much a outlining tool to give an good overview of members in a file to see a list of namespaces, classes, their methods and var and see if they are private protected public static abstract etc and se if the are constructors etc. It would also be very useful to be able to click on a member to directly jump to it in the code. 

I know there have been similar requests before. One that suggested to be able to see members in the explorer has been added to the backlog. What I suggest though is a separate panel showing the outline/overview/member-tree for the current file, similar to the "outline panel" in eclipse. Ideally it would also be able to be open at the same time as the explorer panel.

It would be useful if one could have the list sorted both "naturally" as it comes in the code but also be able to sort it alphabetically and apply filters on it (see only public/protected/private or vars or methods etc) to customize the result. 

Be able to choose if it should include members of parent classes in the scope or not would also be very nice. 

Further it would also be helpful to be able to rearrange the "natural order" by drag and drop to reorganize the file. #

**Comment by dbaeumer** [comment]
@seigan you can get a quick outline (flat) using Ctrl+Shift+O. The request for a separate view is a dup of #5605
