### ISSUE TITLE
Step through "locations" you visited in the code

### ISSUE THREAD

**Issue by seigan** [Microsoft/vscode#18701]
It would be very useful if one was able to retrace ones steps/locations in the code based on what members/code chunks you have clicked on. This is very useful if you go through the code and ctrl+click on a function, object reference or extension that make you jump to the new file/place directly and you then want to find you way back. Also being able to go step by step forward again can be very handy. A little bit like "back" and "forward" in a web browser.

**Comment by dbaeumer** [comment]
@seigan this should work using Alt cursor left and right. Are you looking for something different?

**Comment by yashcr07** [comment]
or search for the setting named "workbench.action.navigateBack" in File > Preferences > Keyboard Shortcuts and check the key binded to this setting. That should do it.
