### ISSUE TITLE
Wishlist

### ISSUE THREAD

**Issue by szechem** [Microsoft/vscode#18708]
- VSCode Version: Version 1.8.1
- OS Version: Linux Ubuntu 16.04
Wishlist - 
Add tooltip, show html open tag, when mouse pointer over html close tag and open tag top of off screen.
Similar feature in Netbean 8.1 for html5 files

**Comment by aeschli** [comment]
@szechem Can you add a screenshot?

**Comment by aeschli** [comment]
Closing due to lack of information. Please add a screenshot...
