### ISSUE TITLE
Cannot drag and drop to move Jupyter cells up/down under wayland

### ISSUE THREAD

**Issue by EncryptedCicada** [microsoft/vscode#187029]
Using jupyter notebooks in vscode, grab and move for cells does not work under wayland. Using the shortcut `Alt+Arrow Key Up/Down` works.

Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.79.2 (Stable) / 1.80.0 (Insider)
- OS Version: Linux x64 6.4.1-zen1-1-zen (Arch Linux)
- Display protocol used: Wayland

Steps to Reproduce:

1. Launch VSCode in wayland with `-enable-features=UseOzonePlatform --ozone-platform=wayland`
2. Create a jupyter file and add several cells (can be markdown or code)
3. Cannot move cells around using drag and drop
4. No observable error messages in the devconsole.

Intended behaviour (xwayland):

[VSCode_Issue_Demo_XWayland.webm](https://github.com/microsoft/vscode/assets/52757733/5e3b0262-4d47-4291-a4b7-6b6710fd22b6)

Buggy behaviour demo (wayland):

[VSCode_Issue_Demo_Wayland.webm](https://github.com/microsoft/vscode/assets/52757733/f487109a-afc0-4ad1-97e4-76e7d6776c50)

NOTE: Cursor is not visible in the recordings but every action has been done using the cursor only.

**Comment by roblourens** [comment]
Your recordings seem to have not been uploaded properly

**Comment by EncryptedCicada** [comment]
> Your recordings seem to have been lost or not uploaded properly

Updated! Thanks for the reminder!

**Comment by pedroaugustosmribeiro** [comment]
I confirm, it does happen

**Comment by roblourens** [comment]
Thanks. https://github.com/microsoft/vscode/issues/156723
