### ISSUE TITLE
explorer.openEditors.visible setting

### ISSUE THREAD

**Issue by paul-jarrow** [microsoft/vscode#187087]
Type: <b>Bug</b>

It appears that the setting for explorer.openEditors.visible has a tooltip suggesting that the value must be greater than or equal to 1.

Setting this value to 0 disables the open editors part of the panel. However, it appears that the Open Editors panel has re-appeared, and this new tooltip is showing up!

Please let me know how to resolve this: to turn off the unused Open Editors part of VSCode, and/or how to set this value to 0 without it being an error.

VS Code version: Code 1.79.2 (695af097c7bd098fbf017ce3ac85e09bbc5dda06, 2023-06-14T08:58:52.392Z)
OS version: Darwin x64 22.5.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|2, 4, 4|
|Memory (System)|32.00GB (0.68GB free)|
|Process Argv|--crash-reporter-id 5462db83-ca1a-4b91-8344-f1170fbd4be1 --crash-reporter-id 5462db83-ca1a-4b91-8344-f1170fbd4be1|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (41)</summary>

Extension|Author (truncated)|Version
---|---|---
tsl-problem-matcher|amo|0.6.2
vscode-zipfs|arc|3.0.0
markdown-preview-github-styles|bie|2.0.2
vscode-eslint|dba|2.4.2
xml|Dot|2.5.1
gitlens|eam|14.0.1
json-tools|eri|1.0.2
prettier-vscode|esb|9.19.0
vscode-jest-runner|fir|0.4.60
copilot|Git|1.95.233
vscode-github-actions|git|0.25.8
vscode-graphql|Gra|0.8.16
vscode-graphql-syntax|Gra|1.2.2
terraform|has|2.27.0
unity-code-snippets|kle|1.3.0
dotenv|mik|1.0.1
vscode-docker|ms-|1.25.2
csharp|ms-|1.26.0
isort|ms-|2022.8.0
python|ms-|2023.10.1
vscode-pylance|ms-|2023.6.40
jupyter|ms-|2023.5.1101742258
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.15
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-slideshow|ms-|0.1.5
cmake-tools|ms-|1.14.34
cpptools|ms-|1.16.3
cpptools-extension-pack|ms-|1.3.0
vsliveshare|ms-|1.0.5873
vsliveshare-pack|ms-|0.4.0
prisma|Pri|4.16.2
vscode-yaml|red|1.13.0
markdown-preview-enhanced|shd|0.6.8
vscode-styled-components|sty|1.7.8
vscode-stylelint|sty|1.2.4
unity-tools|Tob|1.2.12
cmake|twx|0.0.17
vscode-mdx|uni|1.3.0
unity-snippets|Ycl|0.1.2
markdown-pdf|yza|1.4.4

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
py29gd2263:30776702
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
3biah626:30602489
pyind779:30671433
89544117:30613380
pythonsymbol12:30671437
2i9eh265:30646982
showlangstatbar:30737416
vsctsb:30748421
pythonms35:30701012
03d35959:30757346
57b77579:30736110
pythonfmttext:30731395
pythoncmvfstrcf:30756944
fixshowwlkth:30771522
showindicator:30766890
pythongtdpath:30769146
bgfeh915:30780428
pythonnosmt12:30779714
pythonidxpt:30772539
pythonnoceb:30776495

```

</details>

**Comment by gjsjohnmurray** [comment]
I think the zero setting was removed recently in favour of using the standard mechanism for hiding a view via it's context menu.

**Comment by lramos15** [comment]
> I think the zero setting was removed recently in favour of using the standard mechanism for hiding a view via its context menu.

That is correct
