### ISSUE TITLE
Missing Source Explorer

### ISSUE THREAD

**Issue by ecoffman** [microsoft/vscode#187049]
Type: <b>Bug</b>

I can no longer see the source explorer. And, I do not see it under View. I've tried to follow the steps found while googling but none of them worked.

I also loaded from the terminal window without extensions and the same happened.

Other tabs such as Git and extensions, etc. are still there and visible. I can click on them to experience the functionality I expect from them. 

VS Code version: Code 1.79.2 (Universal) (695af097c7bd098fbf017ce3ac85e09bbc5dda06, 2023-06-14T08:58:52.392Z)
OS version: Darwin arm64 22.5.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Max (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|4, 5, 6|
|Memory (System)|32.00GB (0.87GB free)|
|Process Argv|--crash-reporter-id 9db60bcb-d60b-4313-bc58-eef041bd5ad3|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (54)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|3.0.2
project-manager|ale|12.7.0
vscode-apollo|apo|1.19.11
atlascode|atl|3.0.3
vscode-database|baj|2.2.3
simple-react-snippets|bur|1.2.7
turbo-console-log|Cha|2.9.6
codium|Cod|0.6.16
vscode-eslint|dba|2.4.2
githistory|don|0.6.20
xml|Dot|2.5.1
EditorConfig|Edi|0.16.4
auto-rename-tag|for|0.1.10
todo-tree|Gru|0.0.226
terraform|has|2.27.0
implicit-parentheses|Jor|1.1.0
regionfolder|map|1.0.22
rainbow-csv|mec|3.7.0
vscode-azureresourcegroups|ms-|0.7.5
vscode-docker|ms-|1.25.2
csharp|ms-|1.26.0
data-workspace-vscode|ms-|0.5.0
mssql|ms-|1.19.1
sql-database-projects-vscode|ms-|1.1.1
isort|ms-|2022.8.0
python|ms-|2023.10.1
vscode-pylance|ms-|2023.6.40
jupyter|ms-|2023.5.1101742258
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.15
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-slideshow|ms-|0.1.5
remote-containers|ms-|0.295.0
remote-ssh|ms-|0.102.0
remote-ssh-edit|ms-|0.86.0
remote-wsl|ms-|0.79.5
azure-account|ms-|0.11.5
powershell|ms-|2023.6.0
remote-explorer|ms-|0.4.0
sqltools|mtx|0.28.0
vscode-thunder-client|ran|2.8.3
vscode-commons|red|0.0.6
vscode-yaml|red|1.13.0
LiveServer|rit|5.7.9
vs-code-prettier-eslint|rve|5.1.0
jenkinsfile-support|sec|0.1.0
vscode-scss-formatter|sib|2.5.0
html5-boilerplate|sid|1.1.1
sonarlint-vscode|Son|3.19.0
code-spell-checker|str|2.20.5
remove-empty-lines|use|1.0.1
veracode-vscode-plugin|Ver|1.0.0
veracode-greenlight-for-vs-code|vs-|1.6.5272135
vscode-import-cost|wix|3.3.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
py29gd2263:30776702
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
282f8724:30602487
pyind779:30671433
89544117:30613380
pythonsymbol12:30671437
showlangstatbar:30737416
vsctsb:30748421
pythonms35:30701012
a2ce3375:30757347
pythonfmttext:30731395
pythoncmvfstrcf:30756944
fixshowwlkth:30771522
hideindicator:30766889
pythongtdpath:30769146
bgfeh915:30780428
pythonnosm12tcf:30779713
pythonidxpt:30772539
pythonnoceb:30776495

```

</details>

**Comment by lszomoru** [comment]
@ecoffman, @CesarJs could you try to invoke the "View: Reset View Locations" commands from the command palette and see if that resolves the issue? If that does not resolve the issue could you please provide a screenshot of what you are seeing. Thanks!

**Comment by ecoffman** [comment]
Yes, that fixed it for me. Thank you.

From: Ladislau Szomoru ***@***.***>
Date: Wednesday, July 5, 2023 at 11:20 AM
To: microsoft/vscode ***@***.***>
Cc: Eric Coffman ***@***.***>, Mention ***@***.***>
Subject: Re: [microsoft/vscode] Missing Source Explorer (Issue #187049)

@ecoffman<https://github.com/ecoffman>, @CesarJs<https://github.com/CesarJs> could you try to invoke the "View: Reset View Locations" commands from the command palette and see if that resolves the issue? If that does not resolve the issue could you please provide a screenshot of what you are seeing. Thanks!
