### ISSUE TITLE
Latest version of NodeJs in Visual Studio Code

### ISSUE THREAD

**Issue by cvsschaitu** [microsoft/vscode#187148]
Hi Team,
I see latest versions of VSCode have old/ vulnerable version of Nodejs and is same being used in plugins like Remote SSH.
Can we get an option to use installed node instead to have control on the version?
https://code.visualstudio.com/updates/v1_78#_engineering

Thank You.

**Comment by deepak1556** [comment]
Updating to Node 18 will be done as part of https://github.com/microsoft/vscode/issues/184021
