### ISSUE TITLE
Dates in the VSCode UI and extensions are fixed to ambiguous en-US format regardless of system locale

### ISSUE THREAD

**Issue by roblframpton** [microsoft/vscode#187132]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.79.2
- OS Version: Windows 10.0.19045

Steps to Reproduce:

As an example:

1. Go to Extensions
2. Click any extension
3. Look at the "Published" date under "More Info".  It uses the US month/day/year format regardless of the system locale.

This is just one example, but there are many more severe.  As noted on [this ticket](https://github.com/microsoft/vscode/issues/56995), which was closed as out-of-scope, the incorrect format filters down to ALL extensions.  This means that, for example, the [Git history extension uses the wrong format](https://github.com/DonJayamanne/gitHistoryVSCode/issues/740), which is far more problematic.  Any event which occurred before the 13th day in a month are totally ambiguous.  This is a relatively severe problem for people outside North America which devalues the funtionality and could cause genuine misunderstandings.

![Screenshot 2023-07-06 095802](https://github.com/microsoft/vscode/assets/43182639/15d39b8f-7558-4420-8adb-27fd02800f1e)

**Comment by gjsjohnmurray** [comment]
Extensions view is #182014 and fixed in 1.81
