### ISSUE TITLE
copy notebook output command for built in renderers

### ISSUE THREAD

**Issue by amunger** [microsoft/vscode#187152]
The Jupyter renderer extension provides `copy image` through an icon for images, but the builtin renderers do not support any copying.
We can provide a context menu and toolbar locations for this command

**Comment by rebornix** [comment]
Relevant issues

* https://github.com/microsoft/vscode-jupyter/issues/13453
* https://github.com/dotnet/interactive/issues/1982

**Comment by amunger** [comment]
the command is just available through the output toolbar for now
