### ISSUE TITLE
调试工具问题

### ISSUE THREAD

**Issue by shuzongran** [Microsoft/vscode#18716]
- VSCode Version: Code 1.8.1 (ee428b0eead68bf0fb99ab5fdc4439be227b6281, 2016-12-19T14:49:23.350Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions:

|Extension|Author|Version|
|---|---|---|
|python|donjayamanne|0.5.6|
|hopscotch|idleberg|0.1.3|

---

Steps to Reproduce:

1.
![20170118181359](https://cloud.githubusercontent.com/assets/25197414/22060044/4717d43e-ddaa-11e6-82c3-c21acdbb9606.png)

2.开启调试无法进入print_x方法内的断点

**Comment by mjbvz** [comment]
Auto translated:

> 2. Debugging can not open the print_x method into the breakpoint

Please try opening this sort of issue against the Python extension: https://github.com/DonJayamanne/pythonVSCode

Thanks
