### ISSUE TITLE
Information on updates prior to using "Restart to Update"

### ISSUE THREAD

**Issue by prsmendonca** [microsoft/vscode#187150]
It would be great if users could know what changes an update will apply to VSCode before we choose "Restart to Update". A link to a "What's New" or some log would probably suffice.

<img width="313" alt="image" src="https://github.com/microsoft/vscode/assets/10928388/d14a435c-bf92-42cd-8ec4-5f7670f3ace0">

**Comment by joaomoreno** [comment]
**Verification:**

When getting a **Stable** major update, you should now have a menu item next to `Restart to Update` which lets you read the release notes of the upcoming version. No great way to verify other than code review.
