### ISSUE TITLE
Focused panel border bottom too prominent

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#18719]
The current border bottom 2px is too prominent and too close to the titile.
I propose    ` border-bottom: 1px solid #007acc;`

![screen shot 2017-01-18 at 11 27 39](https://cloud.githubusercontent.com/assets/1926584/22060484/3eb8db14-dd71-11e6-85de-3606ca6132d3.png)

**Comment by bpasero** [comment]
I like how it looks now because it matches the style for the active one:

![screen shot 2017-01-18 at 12 25 54](https://cloud.githubusercontent.com/assets/900690/22062286/4853e756-dd79-11e6-856d-686b3f58e776.png)

Anyhow, moving to @bgashler1 for comment.

**Comment by isidorn** [comment]
@bpasero I like the improvments in the panel title area
