### ISSUE TITLE
Handle quotes and brackets in conjuction with AI copilots

### ISSUE THREAD

**Issue by JHarrisGTI** [microsoft/vscode#187151]
Type: <b>Feature Request</b>

I'm writing some unit tests using Amazon CodeWhisperer (similar to GitHub Copilot, and I had the same problem while I was using Copilot). When I type:

`describe('fi`

VScode automatically provides a close-quote and close-paren, adding ') to the right side of the line, so it looks like this:

`describe('fi')`

This is helpful. Then CodeWhisperer suggests:

`describe('findAll', () => {')`

This suggestion is filling out the rest of the function definition, which is also helpful, but it conflicts with the close-quote VSCode has provided. After I accept the suggestion I have to clean up the close-quote myself, and I have to manually close the new curly brace.

It would be better if VSCode would detect when close-quotes, close-brackets, and close-parens have been provided by the copilot's suggestion and delete the ones it provided earlier. It should also automatically close the curly-brace provided by the copilot suggestion.

VS Code version: Code 1.79.2 (Universal) (695af097c7bd098fbf017ce3ac85e09bbc5dda06, 2023-06-14T08:58:52.392Z)
OS version: Darwin x64 22.5.0
Modes:

**Comment by hediet** [comment]
This is out of scope of VS Code and should be handled by the extension.

> This is helpful. Then CodeWhisperer suggests:
> ```
> describe('findAll', () => {')
> ```

I'd say this is a bug in CodeWhisperer/Copilot.
