### ISSUE TITLE
Error! i can't open my codeplace

### ISSUE THREAD

**Issue by elenachai96** [microsoft/vscode#187143]
ADD ISSUE DESCRIPTION HERE

An unexpected error occurred that requires a reload of this page.
The workbench failed to connect to the server (Error: connection record disposed by ConnectionHub: {
"errorMessage": "Failed to start VS Code Remote server.",
"originalErrorType": "<no original type>",
"errorCode": -1,
"errorType": "GenericError",
"stack": "Error: Failed to start VS Code Remote server.\n at [CODESPACE_URL]\n at [CODESPACE_URL]\n at [CODESPACE_URL]\n at [CODESPACE_URL]\n at d ([CODESPACE_URL]\n at a ([CODESPACE_URL]"
} $1 $1)Version: [1.79.2](url)
Commit: 695af097c7bd098fbf017ce3ac85e09bbc5dda06
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36
Embedder: codespaces

**Comment by elenachai96** [comment]
Unable to open '123867463'
Unable to resolve resource vscode-remote://codespaces%2Belenachai96-supreme-space-happiness-6676g59vxrvcrr79/workspaces/123867463

**Comment by Tyriar** [comment]
This looks like an issue with the Codespaces service which we don't track in this repository. You can report this to the Codespaces team at https://github.com/orgs/community/discussions/categories/codespaces
