### ISSUE TITLE
Ability to clone Git repository gone.

### ISSUE THREAD

**Issue by IonMironov-main** [microsoft/vscode#187172]
Type: <b>Bug</b>

VS Code suddenly no longer allows ability to clone Git repository (again). Source Control says no providers registered. Git extension doesn't exist. Updated Git from 2.40 to 2.41, it didn't make a difference. No viable solutions online as they're all outdated and completely useless. I've spent the last hour trying to find answers.

Everything was literally working fine two hours ago when I last used VSC. Ctrl+Shift+P and searching for "Git" will not pull up anything.

VS Code version: Code 1.79.2 (695af097c7bd098fbf017ce3ac85e09bbc5dda06, 2023-06-14T08:57:04.379Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 9 5900X 12-Core Processor             (24 x 4200)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|63.91GB (50.77GB free)|
|Process Argv|--crash-reporter-id 3ddf3d6f-1ad5-4e61-802f-737bfb78dcb2|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (34)</summary>

Extension|Author (truncated)|Version
---|---|---
TabOut|alb|0.2.2
markdown-mermaid|bie|1.19.0
bracket-pair-color-dlw|Bra|0.0.6
npm-intellisense|chr|1.4.4
vscode-markdownlint|Dav|0.51.0
vscode-eslint|dba|2.4.2
json-tools|eri|1.0.2
prettier-vscode|esb|9.19.0
html-preview-vscode|geo|0.2.5
vscode-language-babel|mgm|0.0.39
isort|ms-|2022.8.0
python|ms-|2023.10.1
vscode-pylance|ms-|2023.7.10
live-server|ms-|0.4.8
wordcount|ms-|0.1.0
vsliveshare|ms-|1.0.5873
java|red|1.20.0
LiveServer|rit|5.7.9
vscode-checkstyle|she|1.4.2
js-jsx-snippets|sky|11.0.1
code-spell-checker|str|2.20.5
errorlens|use|3.11.1
intellicode-api-usage-examples|Vis|0.2.7
vscodeintellicode|Vis|1.2.30
vscode-spring-boot|vmw|1.47.0
vscode-java-debug|vsc|0.52.0
vscode-java-dependency|vsc|0.23.0
vscode-java-pack|vsc|0.25.12
vscode-java-test|vsc|0.39.0
vscode-maven|vsc|0.41.0
vscode-icons|vsc|12.4.0
JavaScriptSnippets|xab|1.8.0
markdown-pdf|yza|1.4.4
json|Zai|2.0.2

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
py29gd2263:30776702
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
vsccc:30610678
282f8724:30602487
pyind779:30671433
f6dab269:30613381
pythonsymbol12:30671437
2i9eh265:30646982
showlangstatbar:30737416
vsctsb:30748421
pythonms35:30701012
03d35959:30757346
pythonfmttext:30731395
pythoncmv:30756943
fixshowwlkth:30771522
showindicator:30766890
pythongtdpath:30769146
bgfeh915:30780428
pythonnosmt12:30779714
pythonidxptcf:30772540
pythonnocebcf:30776496
e537b577:30772215

```

</details>

**Comment by gjsjohnmurray** [comment]
Please use the Start Extension Bisect command to investigate whether the problem is being caused by one of your extensions.

**Comment by IonMironov-main** [comment]
I have no clue what you're talking about when you say to do that. I'm a novice to VS Code.

But, it does not matter as I found what the problem was: For some unknown reason, VS Code changed my profile to Default. Switching back to my actual profile brought everything back to normal.
