### ISSUE TITLE
Merge in languages.registerInlineCompletionItemProvider proposed extension

### ISSUE THREAD

**Issue by talbright** [microsoft/vscode#187110]
Can we move https://github.com/microsoft/vscode/blob/e3a8e502ad7263836d0bc34cbcefbfc7bd65104f/src/vscode-dts/vscode.proposed.inlineCompletionsNew.d.ts from out of proposed state into mainline? I see its been in this state for almost a year. Is there an issue with it that needs to be addressed? What steps need to happen to bring it in?

https://github.com/microsoft/vscode-discussions/discussions/26

**Comment by hediet** [comment]
That file does not exist anymore on main - the API got finalized.
