### ISSUE TITLE
Strange Behavior when right-click

### ISSUE THREAD

**Issue by Seraphli** [microsoft/vscode#187111]
Does this issue occur when all extensions are disabled?: Yes

Version: 1.79.2
Commit: 695af097c7bd098fbf017ce3ac85e09bbc5dda06
Date: 2023-06-14T08:59:55.818Z
Electron: 22.5.7
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Linux x64 6.1.31-2-MANJARO

Steps to Reproduce:

After right-clicking at certain locations, the context menu automatically selects the option closest to the mouse cursor. This is not a mouse issue as I encountered the same problem on two different Manjaro machines using different mice. I initially thought it was an issue with extensions until I disabled all extensions, but the problem still persists. This behavior is not observed in other software.
Here is a video showing this bug.

https://github.com/microsoft/vscode/assets/1586755/83193acb-73cc-42bf-86d7-60050c5db994

**Comment by hsfzxjy** [comment]
Same here.

**Comment by Seraphli** [comment]
> Same here.
> 
> I observe that sometimes the coordinate of right click position will fall in the bounding box of context menu, causing the menu item to be clicked.

Yes, exactly. I recently experience this issue a lot.

**Comment by hsfzxjy** [comment]
Seems like an upstream issue https://github.com/electron/electron/issues/31641

**Comment by Seraphli** [comment]
This issue is opened 3 years ago
https://github.com/microsoft/vscode/issues/113175

**Comment by deepak1556** [comment]
Merging to https://github.com/microsoft/vscode/issues/113175
