### ISSUE TITLE
Documentation for JSON Schema support needs updating

### ISSUE THREAD

**Issue by gregsdennis** [microsoft/vscode#187188]
_This isn't a feature request but an issue with your documentation.  This template seemed to work best for that._

The documentation for JSON Schema support has a couple problems.

## Meta-schema URI

In an [example](https://code.visualstudio.com/docs/languages/json#_use-rich-formatting-in-hovers), it lists `http://json-schema.org/schema` a value to use for `$schema`, but this is not a valid meta-schema URI.  We used to host the latest there, but that practice was stopped quite a while ago.

Furthermore, `$schema` holds a basic URI, not a URL.  It's not intended for implementations to fetch a meta-schema from the value provided in `$schema`.  `http://json-schema.org/schema` should not resolve to a meta-schema.

Instead, one of the versioned URIs below (the exact string) needs to be used:

- `http://json-schema.org/draft-06/schema#`
- `http://json-schema.org/draft-07/schema#`
- `https://json-schema.org/draft/2019-09/schema`
- `https://json-schema.org/draft/2020-12/schema`

## Draft Support

The documentation [says](https://code.visualstudio.com/docs/languages/json#_json-schemas-and-settings) that it supports draft 4 through draft 2020-12.  As there are features in 2019-09 and 2020-12 that are not supported, notably `unevaluated*` and `$dynamic*`, this statement is misleading.

It would be more correct to state that draft 4 through draft 7 are supported with _limited_ support for drafts 2019-09 and 2020-12.

Also, it would be good to indicate which features in the later drafts are not supported.

We get numerous questions about VSCode support for JSON Schema, and it would be great to have accurate documentation that we can point them to.

**Comment by aeschli** [comment]
Thanks, I made the suggested changes: https://github.com/microsoft/vscode-docs/commit/0627e8fcdc656a6fb369117ecf0d0365224ef595
