### ISSUE TITLE
Disable "Restart" button in Debug toolbar when Debug Adapter doesn't support restartRequest 

### ISSUE THREAD

**Issue by apupier** [microsoft/vscode#187129]
https://microsoft.github.io/debug-adapter-protocol/specification#Types_Capabilities
`supportRestartRequest` can be set to false.

https://microsoft.github.io/debug-adapter-protocol/specification#Requests_Restart

`Restarts a debug session. Clients should only call this request if the corresponding capability supportsRestartRequest is true.`

The button in UI is enabled. If clicking on it, there is effectively no Restart which is called but it would be nicer to not provide the restart button

**Comment by roblourens** [comment]
When that value is false, then the DA does not handle the request but VS Code handles it instead. From the doc, 

> If the capability is missing or has the value false, a typical client emulates restart by terminating the debug adapter first and then launching it anew.
