### ISSUE TITLE
"<" in "</script>" scoped as JS source

### ISSUE THREAD

**Issue by sdalmonte** [microsoft/vscode#187113]
Type: <b>Bug</b>

In HTML documents, the opening bracket `<` of a closing script tag `</script>` is assigned the TextMate scope `source.js-ignored-vscode`. This scope takes precedence over all other scopes assigned to the `<`, which may cause it to appear incorrectly coloured in certain colour themes (such as my current colour theme, [Cold Horizon](https://marketplace.visualstudio.com/items?itemName=vincentfiestada.cold-horizon-vscode)).

<img width="658" alt="Screenshot 2023-07-05 at 10 46 27 PM" src="https://github.com/microsoft/vscode/assets/1361737/0afbdd32-db70-4a52-9943-bbd3fa7016ba">

VS Code version: Code 1.79.2 (695af097c7bd098fbf017ce3ac85e09bbc5dda06, 2023-06-14T08:58:33.551Z)
OS version: Darwin arm64 22.5.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M2 Pro (12 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|32.00GB (4.99GB free)|
|Process Argv|--crash-reporter-id cd026240-3a85-4016-bffb-9bb4e16ec8a8|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
chalice-icon-theme|art|1.2.24
prettier-vscode|esb|9.19.0
vscode-stylelint|sty|1.2.4
errorlens|use|3.11.1

(4 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
py29gd2263:30776702
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
2e4cg342:30602488
pyind779:30671433
f6dab269:30613381
pythonsymbol12:30671437
2i9eh265:30646982
showlangstatbar:30737416
vsctsb:30748421
pythonms35:30701012
03d35959:30757346
pythonfmttext:30731395
pythoncmvfstrcf:30756944
fixshowwlkth:30771522
pythongtdpath:30769146
bgfeh915:30780428
pythonnosm12tcf:30779713
pythonidxptcf:30772540
pythonnoceb:30776495

```

</details>

**Comment by aeschli** [comment]
See https://github.com/textmate/html.tmbundle/issues/65.

It's done intentionally so that the position on the left side of `<` is still treated as JavaScript.

**Comment by sdalmonte** [comment]
Makes sense! Other themes colour the `<` correctly, so this particular case seems to be more of an issue with the theme. Thanks for your help @aeschli
