### ISSUE TITLE
Incorrect "There is an available update"

### ISSUE THREAD

**Issue by Alonski** [Microsoft/vscode#18714]
- VSCode Version: Latest
- OS Version: Windows 10

Steps to Reproduce:

1. Go to Help -> Check for updates...
This pops up:
![screenshot_7](https://cloud.githubusercontent.com/assets/452199/22059464/8b33d26a-dd75-11e6-802a-144783b735b1.png)

**Comment by joaomoreno** [comment]
Does this happen **everytime** you click Help > Check for updates?

**Comment by Alonski** [comment]
After updating this morning it seems to be fixed. I will update if this happens again thanks.

**Comment by raditp** [comment]
This still happens to me on version 1.9.1 on Windows 10

**Comment by joaomoreno** [comment]
2.1.6 is not a version we have.

**Comment by raditp** [comment]
Sorry, I misread the Typescript version as vscode version.

it's 1.9.1
![parallels picture](https://cloud.githubusercontent.com/assets/6302584/23060339/e32206d2-f52f-11e6-909b-acc684c92227.png)

**Comment by joaomoreno** [comment]
How does it happen to you? It just opens by itself?

**Comment by raditp** [comment]
The "There is an available update." popup opens by itself very often. When click Download Now, nothing happens.
I can also reproduce the above reproduce steps.

**Comment by joaomoreno** [comment]
Do you get the popup when you click `Help > Check for Updates...`?

**Comment by raditp** [comment]
Yes, same as in @Alonski 's image

**Comment by joaomoreno** [comment]
Can you show me your settings file? Are you behind a proxy?

**Comment by raditp** [comment]
I just have these two settings modified.
```
{
    "files.associations": {
        "*.txt": "robot"
    },
    "editor.wordWrap": true
}
```
I don't have any proxies, but run my Windows inside Macbook's Parallels Desktop. And this only happens to the vscode inside Windows, but not on the one in MacOS.

**Comment by Diggsey** [comment]
This happens for me too, exactly the same symptoms and version as @raditp

**Comment by joaomoreno** [comment]
@Diggsey No proxy?

**Comment by Diggsey** [comment]
No

**Comment by andy-ms** [comment]
This has started happening for me too. I'm on Linux Mint 18 and just updated from the Update Manager (Linux Mint's `.deb` package manager). If I go to Help -> Download Available Update, and try to install from there, I get an error: `A later version is already installed`.

**Comment by joaomoreno** [comment]
@Tyriar Check @andy-ms comment

**Comment by Tyriar** [comment]
@andy-ms this will happen for a little while until I get around to fixing our release site. Currently only the daily builds are submitted automatically to the repository, one off manual builds such currently require me to submit it manually. This will probably only happen pretty infrequently for a week or so.

**Comment by joaomoreno** [comment]
To keep the number of issues in our inbox on a manageable level, we're closing issues that have been on the backlog for a long time but haven't gained traction: We look at the number of votes the issue has received and the number of duplicates issues filed.

Thanks for your understanding. Happy coding!
