### ISSUE TITLE
Stray underlines in terminal

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#187137]
* copy a file path, open terminal
* run `echo <filepath_from_clipboard>`
* hover over the file path, make sure it is decorated as link
* w/o moving the mouse, press `cmd+k` to clear the terminal
* underline is kept

**Comment by jrieken** [comment]
https://github.com/microsoft/vscode/assets/1794099/534f6529-f108-4967-874e-8e7ef61541d0

**Comment by Tyriar** [comment]
I fixed an issue that sounds a lot like this about 6 months ago where link underlines would stick around after being hovered.
