### ISSUE TITLE
Create function body on PHP writting "fun" doesn't work ok

### ISSUE THREAD

**Issue by skydonesolutions** [microsoft/vscode#187136]
Type: <b>Feature Request</b>

I am working with PHP, in the last two versions released, when I write "fun" the suggested generated function structure isn't correct.

Before (OK):
```
public function FunctionName(): Returntype 
{
    ...
}
```
Now: 
```
function FunctionName() : Returntype {

}
```
VS Code version: Code 1.79.2 (695af097c7bd098fbf017ce3ac85e09bbc5dda06, 2023-06-14T08:59:55.818Z)
OS version: Linux x64 4.15.0-213-generic snap
Modes:

**Comment by roblourens** [comment]
See https://github.com/microsoft/vscode/issues/185005
