### ISSUE TITLE
Windows keybinding with REST extension

### ISSUE THREAD

**Issue by a8775** [Microsoft/vscode#18712]
- VSCode Version: 1.9.0-insider (Date 2017-01-18)
- OS Version: Windows 10

Steps to Reproduce:
1. Install REST extension
2. Keybinding is: { "key": "ctrl+alt+e",            "command": "rest-client.switch-environment" },

The problem:
When I press: AltGr+e the command is executed.

Normally I should get special letter that is bonded with national keyboard mapping in Windows.

The issue has possibly two aspects:
1. The command for REST extension should not be executed as it's ctrl+alt+e not alt-e
2. The key binding AltGr+<char> is not differentiated from Alt+<char> - i believe this is related to issue: https://github.com/Microsoft/vscode/issues/17521

**Comment by alexandrudima** [comment]
### To find out what a keybinding does:

1. Open `Preferences` > `Keyboard Shortcuts`
2. Click on `Define Keybinding`
3. Press your desired key combination
(e.g. doing it for <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>1</kbd>):
![image](https://cloud.githubusercontent.com/assets/5047891/22168002/1df3bb24-df6a-11e6-93f8-0842e8f37b3d.png)
4. Take note of the string shown inside the textbox (highlighted in purple above)
5. Search for that string in the default keybindings and you shall find what it is bound to.

### To remove a keybinding:

1. Identify the keybinding you would like to remove (e.g:)
```json
{ "key": "ctrl+shift+1",          "command": "editor.action.replaceOne",
                                     "when": "editorFocus && findWidgetVisible" },
```
2.a. Completely free up the keybinding. This will remove all the commands bound to `"ctrl+shift+1"`. Write the following rule:
```json
{ "key": "ctrl+shift+1" }
```
2.b. Completely remove a command. This will remove all keybindings associated with `"editor.action.replaceOne"`. Write the following rule:
```json
{ "command": "-editor.action.replaceOne" }
```
2.c. Remove that specific keybinding. Write the following rule:
```json
{ "key": "ctrl+shift+1", "command": "-editor.action.replaceOne" },
```

> Tip: Remember, in VS Code you can modify each and every keybinding to your liking, you are the sole master of your keyboard.
