### ISSUE TITLE
Accessibility buffer is only read by line for latest terminal

### ISSUE THREAD

**Issue by steverep** [microsoft/vscode#187288]
Type: <b>Bug</b>

When navigating the terminal accessibility buffer using up/down arrow keys, the expectation is that the current line will be read by a screen reader.  However, this only works on the latest terminal opened.  For older terminals, the up/down arrows navigate and read by character, which makes the buffer all but useless on those terminals.

Steps to reproduce using NVDA:
1. Open a new terminal and `echo "Hello"`.
2. Open a 2nd terminal and do the same.
3. Shift+Tab then up arrow - "Hello" read as expected.
4. Go back to terminal 1 and do the same - up arrow reads "o"

VS Code version: Code 1.80.0 (660393deaaa6d1996740ff4880f1bad43768c814, 2023-07-04T15:06:02.407Z)
OS version: Windows_NT x64 10.0.19045
Modes:
Remote OS version: Linux x64 5.15.90.1-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3570K CPU @ 3.40GHz (4 x 3400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|7.70GB (0.27GB free)|
|Process Argv|--crash-reporter-id 3a22bbf5-2056-4e13-b76d-f877a84ba4c7|
|Screen Reader|yes|
|VM|0%|

|Item|Value|
|---|---|
|Remote|Dev Container: Home Assistant Frontend|
|OS|Linux x64 5.15.90.1-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i5-3570K CPU @ 3.40GHz (2 x 3400)|
|Memory (System)|3.83GB (2.09GB free)|
|VM|0%|
</details><details><summary>Extensions (24)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-firefox-debug|fir|2.9.8
remotehub|Git|0.60.0
jupyter-keymap|ms-|1.1.2
remote-containers|ms-|0.300.0
remote-ssh|ms-|0.102.0
remote-wsl|ms-|0.80.2
vscode-remote-extensionpack|ms-|0.24.0
azure-repos|ms-|0.36.0
remote-explorer|ms-|0.4.1
remote-repositories|ms-|0.38.0
remote-server|ms-|1.2.1
browserslist|web|1.1.0
vscode-ruby|win|0.28.0
vscode-markdownlint|Dav|0.51.0
vscode-eslint|dba|2.4.0
gitlens|eam|14.0.1
prettier-vscode|esb|9.14.0
vscode-pull-request-github|Git|0.68.0
python|ms-|2023.12.0
vscode-pylance|ms-|2023.7.10
vscode-yaml|red|1.13.0
lit-plugin|run|1.3.0
shellcheck|tim|0.32.6
markdown-all-in-one|yzh|3.5.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
py29gd2263:30776702
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
282f8724:30602487
pyind779:30671433
f6dab269:30613381
pythonsymbol12:30671437
showlangstatbar:30737416
vsctsb:30748421
pythonms35:30701012
03d35959:30757346
24365598:30736109
pythonfmttext:30731395
pythoncmvfstrcf:30756944
fixshowwlkth:30771522
showindicator:30766890
pythongtdpath:30769146
i26e3531:30780429
pythonnosmt12:30779714
pythonidxpt:30784022
pythonnoceb:30776495

```

</details>

**Comment by meganrogge** [comment]
I cannot reproduce in insider's, can you?

**Comment by steverep** [comment]
Yes, seems to now be fixed in insiders.  I did test that at the time of opening this issue, so not sure which commit fixed it.  Thanks.
