### ISSUE TITLE
'XHR failed' error profile creation/import operations in offline portable mode

### ISSUE THREAD

**Issue by ComradePan** [microsoft/vscode#187226]
Type: <b>Bug</b>

Steps to Reproduce:

1. Configure VS Code for **portable **offline** mode** usage (there's no internet for  corp's rules);
2. Create profile - get 'XHR failed' error;
3. Export local profile to file .code-profile (only installed extensions);
4. Try to import received profile on same PC or share it to another - get 'XHR failed' error;
6. Switch to created/imported profile and check extensions (list is almost blank, despite of a lot of items during the creation);
7. Creating/Importing thus profile at PC with internet cause no errors

VS Code version: Code 1.80.0 (660393deaaa6d1996740ff4880f1bad43768c814, 2023-07-04T15:06:02.407Z)
OS version: Windows_NT x64 10.0.19044
Modes:

<details><summary>Extensions (31)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|3.0.2
project-manager|ale|12.7.0
project-templates|can|1.2.0
doxdocgen|csc|1.4.0
arm|dan|1.7.4
overtype|DrM|0.5.0
gitlab-workflow|Git|3.68.0
activitusbar|Gru|0.0.47
vscode-test-explorer|hbe|2.21.1
vscode-drawio|hed|1.6.6
shortcut-menu-bar|jer|3.0.4
cortex-debug|mar|1.12.0
debug-tracker-vscode|mcu|0.0.15
memory-view|mcu|0.0.22
peripheral-viewer|mcu|1.4.6
rtos-views|mcu|0.0.7
git-graph|mhu|1.30.0
compare-folders|mos|0.22.5
vscode-language-pack-ru|MS-|1.80.2023070509
cpptools|ms-|1.16.3
cpptools-extension-pack|ms-|1.3.0
live-server|ms-|0.4.9
test-adapter-converter|ms-|0.1.8
material-icon-theme|PKi|4.28.0
vscode-coverage-gutters|rya|2.11.0
code-spell-checker|str|2.20.5
code-spell-checker-russian|str|2.0.9
vscode-icons|vsc|12.4.0
debug|web|0.26.1
markdown-all-in-one|yzh|3.5.1
markdown-editor|zaa|0.1.10

</details>

![1](https://github.com/microsoft/vscode/assets/138841843/99341d9b-a26f-47d6-bd29-13b4de4f86de)
![2](https://github.com/microsoft/vscode/assets/138841843/3957f429-cdd6-4667-b9ab-77cf86084182)

**Comment by ComradePan** [comment]
this problem was since profile's release and not so important number or list of extensions

**Comment by sandy081** [comment]
Importing a profile will not work if you do not have network, as the extensions are installed from Marketplace. But it should not happen when you create the profile. Can you please let us know what do you see when you create the profile?

**Comment by ComradePan** [comment]
> Importing a profile will not work if you do not have network, as the extensions are installed from Marketplace.   

sad to hear it, such a useful tool for sharing work environment with colleagues as a devops; extensions could be installed from vsix or simple coping between PC's nor than installed from Marketplace.

> Can you please let us know what do you see when you create the profile?

There is at least two different behaviors. First case creating profile: user gets the same 'XHR failed' error, still profile creates and you can switch to it and see it's content almost blank
![2](https://github.com/microsoft/vscode/assets/138841843/df46a1f3-c0ae-4cd8-97f9-3e08ea0884de)
![3](https://github.com/microsoft/vscode/assets/138841843/44734017-5d0c-421c-be35-2f5629b79011)

Second one: user exports default profile to local .code-profile file. In this case import accomplish correct, but when user try to import created profile he gets 'XHR failed' error

Such a weird behavior leads to frustration, cose it's seems pretty logical that local profile could be just copied to another PC and imported without any requirements such a internet connection and so on. As for me it's not the obvious behavior

**Comment by terje-rosenlund** [comment]
> Importing a profile will not work if you do not have network, as the extensions are installed from Marketplace. But it should not happen when you create the profile. Can you please let us know what do you see when you create the profile?

Importing a profile will not work even if you have network

**Comment by sandy081** [comment]
> First case creating profile: user gets the same 'XHR failed' error, still profile creates and you can switch to it and see it's content almost blank

Are you creating the profile from current profile?

**Comment by ComradePan** [comment]
> Are you creating the profile from current profile?

Yep, from default profile

**Comment by sandy081** [comment]
Agreed that creating a profile from a profile that is existing in VS Code should not need network connectivity.

But creating a profile from the template needs network connectivity. Because, the template has just extension id and therefore it is required to resolve the id to an extension.
