### ISSUE TITLE
typingsInstaller/telemetry process causing high CPU usage

### ISSUE THREAD

**Issue by laggingreflex** [Microsoft/vscode#18729]
- VSCode Version: 1.8.1
- OS Version: Win 10 

Steps to Reproduce:

1. Open VSCode
2. Open process explorer, one of the child processes will be related to telemetry and eating CPU

I was experiencing high CPU usage and found the following process which was causing it:

`"C:\Program Files (x86)\Microsoft VS Code\Code.exe" "c:\Program Files (x86)\Microsoft VS Code\resources\app\extensions\typescript\node_modules\typescript\lib/typingsInstaller.js" --globalTypingsCacheLocation C:/Users/x/AppData/Local/Microsoft/TypeScript --enableTelemetry`

![vscode-telemetry](https://cloud.githubusercontent.com/assets/2523987/22063402/971bd6d4-dda4-11e6-8696-01d558fd3ef7.png)

(that's 20% with just one project, with a couple of projects it gets really worse)

Not sure if this is related to telemetry but I've already set `"telemetry.enableTelemetry": false` in user setting (as seen in gif) but still seeing the above process.

**Comment by binbinfrog** [comment]
version 1.8.1
os win 10

Having exactly the same problem, I'm using vscode for a react.js project (es6)

BTW, this also happens on fedora

**Comment by mjbvz** [comment]
Please try out VSCode 1.10 with the current insiders builds. This includes a new version of TypeScript which fixed a number of regressions over VSCode 1.8. 

If you still see this performance issue in VSCode 1.10 with all extensions disabled, to help us investigate, please try collecting some logs from the TypeScript server when this occurs. Here's information on to do this using the TSS_LOG environment variable: https://github.com/Microsoft/TypeScript/wiki/Standalone-Server-%28tsserver%29#logging

From a command prompt, run:

```
set TSS_LOG=-level verbose -file c:\tmp\tsserver.log
code 
```

Reproduce the problem in VSCode and then share the c:\tmp\tsserver.log file


Let me know if you have any questions about this.

Thanks

**Comment by syusukexrj** [comment]
Have the same issue. As a workaround I renamed typingsInstaller.js.

VSCode Version: 1.10.2
OS Version: Win 7

**Comment by UzEE** [comment]
I can confirm the issue still exists. Also, while I'm working on a large JavaScript project, I am not using any typescript at the moment.

I was going to attach a tsserver.log file but it came out to be over 800 MB, so I'm skipping that.

VSCode Version: 1.12.2 (I have been noticing it since 1.12.0)
OS Version: Win 10.15063.296
Typescript Version: 2.3.2
