### ISSUE TITLE
Keyring / keychain CLI option being ignored after 1.80 change

### ISSUE THREAD

**Issue by lucaspar** [microsoft/vscode#187271]
Does this issue occur when all extensions are disabled?: **Yes**

- VS Code Version: 1.80.0
- OS Version: Kubuntu 23.04

```
$ gnome-keyring version
gnome-keyring: 42.1
```

### Steps to Reproduce:

1. Have `Kwallet` disabled and `gnome-keyring` installed.
2. Launch VS Code with `--password-store="gnome"` option [as in the docs](https://github.com/microsoft/vscode-docs/blob/vnext/docs/editor/settings-sync.md#troubleshooting-keychain-issues).
Using `code --verbose --disable-extensions --password-store="gnome"` here.
3.  Getting kwallet warning despite specifying gnome's keyring: "You're running in a KDE environment but the OS keyring is not available for encryption. Ensure you have kwallet running." error.

![image](https://github.com/microsoft/vscode/assets/7535699/cd3120f9-d206-4487-9fbe-3c101908afa2)

#### Main

Many instances of

```
[error] Error: Error while encrypting the text provided to safeStorage.encryptString. Encryption is not available.
```

No other relevant logging source found.

**Comment by jelmd** [comment]
Since the 'Unlock keyring' dialog on startup really sucks (**even if no file/project is opened and no extension installed**!!!), I use `code --password-store=basic` on Ubuntu 20.04 to disable this non-sense. Before I found this solution I used `mv /usr/libexec/gcr-prompter /usr/libexec/gcr-prompter.disabled` (part of the gcr package) to get rid off it. Not sure, whether this helps, but yes, code should use lazy initialization (i.e. ask when secrets are actually needed) as well as make it customizable, what kind of store (if any) to use.

**Comment by TylerLeonhardt** [comment]
Let's follow up in https://github.com/microsoft/vscode/issues/187284 @jelmd since you are seeing a different issue.

**Comment by lucaspar** [comment]
So since I posted this issue, I enabled the KDE Wallet system to be able to use VS Code as usual.

Now I tried to replicate the original problem by disabling the KDE Wallet system (as it was before); terminating all kwallet processes; terminating all VS Code instances; then I re-opened VS Code. And now it works (yay?).

So I am unable to replicate it now, but should I have keyring issues again I'll try that increased logging approach to get more messages.

**Comment by TylerLeonhardt** [comment]
Thanks for following up @lucaspar! I'll close this since we don't have the repro but if you see it again don't hesitate to reach out. Also I updated the redirection link to point to the new docs location rather than the GitHub link so now the docs are a bit more readable :)

**Comment by chiboreache** [comment]
how to suppress this error? 

don't care about 

at all ...

**Comment by TylerLeonhardt** [comment]
@chiboreache the docs can help you get passed the error:

https://code.visualstudio.com/docs/editor/settings-sync#_other-linux-desktop-environments

**Comment by jelmd** [comment]
It is getting worse! :((((((((
With 1.80.1 even the suggested measure do not work anymore, neither via CLI nor argv.json! It really sucks.

**Comment by TylerLeonhardt** [comment]
@jelmd please open a new issue with what you are seeing so we can further debug together.
