### ISSUE TITLE
Installing an extension with multiple Code instances open

### ISSUE THREAD

**Issue by massimocode** [Microsoft/vscode#1872]
A colleague showed me something interesting today.

He said he had multiple VS Code windows open (in Mac OS X) and installed an extension. He was notified that the installation was successful and that he should restart, so he clicked the restart button. As expected, the VS Code window closed and reopened and the extension was available.

However, he then switched to another VS Code window and saw that his newly installed extension was unavailable.

We noticed it was because clicking the restart button only restarts the active VS Code window, not all of them. So you might still have other CS Code windows that do not get the extension until they are manually restarted.

What might potentially make this more complicated is that VS Code has the session restore setting and the default is to restore only 1 window. So if you kill all code processes and relaunch code, and the user had multiple open when they installed the extension, then by default only 1 of them will "restart" and the rest will remain closed.

It might be an idea to temporarily change the editor setting to restore all, then kill all code processes and relaunch, then change the setting back... or maybe that's a terrible idea, but hey it's a suggestion!

**Comment by joaomoreno** [comment]
@bpasero is this true?

> What might potentially make this more complicated is that VS Code has the session restore setting and the default is to restore only 1 window. So if you kill all code processes and relaunch code, and the user had multiple open when they installed the extension, then by default only 1 of them will "restart" and the rest will remain closed.

**Comment by bpasero** [comment]
There is a setting to control this, just set "window.reopenFolders": "all"

**Comment by joaomoreno** [comment]
I will then close this issue, since there is a way to preserve the state upon restart.

**Comment by massimocode** [comment]
I'd like to reopen this issue. I think we got a little distracted with the whole window.reopenFolders setting, which is just a heads-up to help you guys fix the real issue.

The real issue was described as follows:
"... clicking the restart button only restarts the active VS Code window, not all of them. So you might still have other CS Code windows that do not get the extension until they are manually restarted."

**Comment by joaomoreno** [comment]
@massimocode I actually think that is an acceptable behaviour. You could either
1. Provide a **Restart all** button
2. Provide a **Restart** button (current solution)
3. Provide both

Given them all, I still think 2 is a fair option, as I often want to leave my other windows intact.

**Comment by massimocode** [comment]
Ok that's fine, I just wanted to bring the issue to your attention in case it wasn't desirable behaviour
