### ISSUE TITLE
Disable select ligatures with a blacklist

### ISSUE THREAD

**Issue by OldStarchy** [microsoft/vscode#187216]
Reopening #98758

> I would love an option to disable certain ligatures while keeping the rest.
>
> I love most ligatures, but the "=" vs "==" vs "===" is sometimes hard to tell apart (and led to an hour long bug hunt.) I would love a blacklist of ligatures to ignore.
>
> For now, I will just go back to a classic font... like the ones muggles use... bleh.

Personally, I'd like to disable the `.-` ligature in s/css files.

**Comment by nickmccurdy** [comment]
I don't think it's possible to toggle ligatures for specific pairs, but if you read the docs for your font/typeface it should tell you what features are supported.

**Comment by OldStarchy** [comment]
Is this an issue with the font renderer in chromium/electron?
