### ISSUE TITLE
Activity design for panel switcher

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#18724]
Now that we have the panel switcher added, we should think about how to show activity. For example, the "Problems" view today changes its title based on the number of problems:

![image](https://cloud.githubusercontent.com/assets/900690/22062920/680411e0-dd7c-11e6-9eeb-c53cb066b374.png)

I think this model no longer works nicely with the switcher and I would suggest we have something like the badges in the activity bar for panels too.

Thoughts?

/cc @sandy081

**Comment by sandy081** [comment]
I remember @isidorn had done something similar for problems panel when we want to show the panels on the activity bar. @isidorn Can we reuse that ?

**Comment by isidorn** [comment]
@sandy081 I forgot how exactly it worked, but something in the manner of activity bar asking for each panel on it's progres and displaying it properly.
activityBarPart.ts would be a good starting point to dig into history
Not sure if I reverted all those changes since we decided not to keep it in the end.

**Comment by bpasero** [comment]
Well yeah, we do have a story for the activity bar and it works nicely, but what I wonder is, do we want something similar for the panel bar now too and if so, how would it look like.

**Comment by bpasero** [comment]
@isidorn  implemented this, but we are not using it yet.

**Comment by isidorn** [comment]
friendly ping @sandy081 to adopt this in problems land (should be low effort)

**Comment by sandy081** [comment]
Sure.
