### ISSUE TITLE
Replace does not work if replace string is empty

### ISSUE THREAD

**Issue by thekalinga** [Microsoft/vscode#18728]
- VSCode Version:

Version 1.9.0-insider
Commit 2cdc2b3da8f0fd5322b48747241584cf9dd98f8f
Date 2017-01-13T07:03:18.620Z
Shell 1.4.6
Renderer 53.0.2785.143
Node 6.5.0

- OS Version:

Ubuntu

Steps to Reproduce:

1. Open any project
2. Create a new file using the menu `File -> New file`
3. Write some text & try replacing any text
4. It does not work

NOTE: This file is not yet saved to the disk. This is a file thats yet to be saved to disk & no file on the disk as of now

**Comment by thekalinga** [comment]
I just saved the file; It does not work now aswell for some reason.

It worked a while back. Now its not working. Both using UI & `Ctrl+Alt+Enter`

Not sure how to debug this.

**Comment by thekalinga** [comment]
It show this error `Cannot read property 'length' of null` if I press `Ctrl+Shift+1`, i.e shortcut for replace :)

**Comment by thekalinga** [comment]
Am facing issue with this version aswell


Version 1.9.0-insider
Commit 39d761bf1f4ce7ea605539bdba41a8727b3c7ce0
Date 2017-01-18T07:21:35.814Z
Shell 1.4.6
Renderer 53.0.2785.143
Node 6.5.0

**Comment by thekalinga** [comment]
Here is the actual issue.

If replace string is empty, then replace action not performing anything.

But it should allow me to replace something with nothing.

**Comment by thekalinga** [comment]
Looks like `Ctrl+Shift+1` (the shortcut) does not have this null check, which is its throwing `Cannot read property 'length' of null` :)

**Comment by alexandrudima** [comment]
Thank you. Fixed via 8289f6fa059d580ec063386ccebb4bde2354bb89
