### ISSUE TITLE
Markdown preview broken after 1.80 update

### ISSUE THREAD

**Issue by gmccullo** [microsoft/vscode#187234]
Type: <b>Bug</b>

Got the June update this morning. Noticed this stopped working: markdown.preview.markEditorSelection

Looking at the HTML in dev tools the body tag looks malformed:

```html
<body class="vscode-body style= vscode-light" overscroll-behavior-x:="" none;"="" scrollbeyondlastline="" wordwrap="" showeditorselection"="" role="document" data-vscode-theme-kind="vscode-light" data-vscode-theme-name="Light Modern" data-vscode-theme-id="Default Light Modern">
```

I copied this with extensions disabled.

VS Code version: Code 1.80.0 (660393deaaa6d1996740ff4880f1bad43768c814, 2023-07-04T15:06:02.407Z)
OS version: Windows_NT x64 10.0.22621
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 3750H with Radeon Vega Mobile Gfx   (8 x 2296)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|13.95GB (3.65GB free)|
|Process Argv|--crash-reporter-id f4d11365-b8df-4076-a7d2-5647e124f85c|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (66)</summary>

Extension|Author (truncated)|Version
---|---|---
increment-selection|alb|0.2.0
Bookmarks|ale|13.3.1
rtf|ale|2.7.0
vscode-unfancy-file-icons|ale|3.15.0
html-end-tag-labels|ant|1.0.0
icons-carbon|ant|0.2.6
vscode-open-file-folder|auc|0.0.4
markdown-footnotes|bie|0.1.1
insert-unicode|bru|0.14.0
markdown-toc|Cha|1.5.6
reverse-search|Dan|2.0.2
vscode-markdownlint|Dav|0.51.0
vscode-simpler-icons|dav|1.6.5
vscode-eslint|dba|2.4.2
vscode-quick-select|dba|0.2.9
githistory|don|0.6.20
xml|Dot|2.5.1
overtype|DrM|0.5.0
vsc-material-theme-icons|equ|2.8.0
prettier-vscode|esb|9.19.0
font-switcher|eva|4.1.0
auto-close-tag|for|0.5.14
dotnet-test-explorer|for|0.7.8
macros|ged|1.2.1
html-preview-vscode|geo|0.2.5
live-sass|gle|6.0.5
todo-tree|Gru|0.0.226
vscode-htmlhint|HTM|1.0.5
docomment|k--|1.0.0
vscode-autohotkey-plus-plus|mar|3.3.2
markdown-shortcuts|mdi|0.12.0
render-crlf|med|1.6.1
fluent-icons|mig|0.0.18
ecdc|mit|1.8.0
csharp|ms-|1.26.0
vscode-dotnet-runtime|ms-|1.6.0
powershell|ms-|2023.6.0
vscode-paste-image|mus|1.0.4
fix-json|oli|0.1.2
subtitles-editor|pep|1.1.7
material-icon-theme|PKi|4.28.0
material-product-icons|PKi|1.5.0
word-counter|plu|0.0.1
toggle|reb|0.0.2
vscode-sort-json|ric|1.20.0
partial-diff|ryu|1.4.3
block-travel|sas|0.0.2
MDTools|sea|1.0.1
vscode-table-formatter|shu|1.2.1
vscode-fileutils|sle|3.10.2
uridecode|sry|0.3.6
character-count|ste|0.1.1
code-spell-checker|str|2.20.5
code-spell-checker-british-english|str|1.1.4
code-spell-checker-french|str|0.3.1
code-spell-checker-german|str|2.2.1
code-spell-checker-greek|str|1.0.4
code-spell-checker-italian|str|1.0.2
code-spell-checker-medical-terms|str|2.0.3
code-spell-checker-scientific-terms|str|0.1.9
code-spell-checker-spanish|str|2.1.9
duplicate-finder|tle|0.0.6
vscode-w3cvalidation|Umo|2.9.1
vscode-icons|vsc|12.4.0
copyrawvalue|wer|1.0.0
markdown-all-in-one|yzh|3.5.1

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263cf:30335440
vscoreces:30445986
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
py29gd2263:30776702
vscaac:30438847
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
2e4cg342:30602488
pyind779:30671433
f6dab269:30613381
pythonsymbol12:30671437
showlangstatbar:30737416
vsctsb:30748421
pythonms35:30701012
03d35959:30757346
pythonfmttext:30731395
pythoncmv:30756943
fixshowwlkth:30771522
pythongtdpath:30769146
bgfeh915:30780428
pythonnosmt12:30779714
pythonidxpt:30784022
pythonnocebcf:30776496
h7j2d465:30772216

```

</details>

**Comment by alexr00** [comment]
Closing as this looks to be merged.
