### ISSUE TITLE
Copy paste code does not automatically paste the imports in typescript

### ISSUE THREAD

**Issue by thekalinga** [Microsoft/vscode#18726]
- VSCode Version:

Version 1.9.0-insider
Commit 2cdc2b3da8f0fd5322b48747241584cf9dd98f8f
Date 2017-01-13T07:03:18.620Z
Shell 1.4.6
Renderer 53.0.2785.143
Node 6.5.0

- OS Version:

Ubuntu

Steps to Reproduce:

1. Import a typescript class(A in a.ts) in another class(B in b.ts)
2. Create one more new typescript class (C in c.ts)
3. Copy code that contains class A from b.ts to c.ts; Lets say `let a = new A();`
4. Only the text copied gets pasted in c.ts, but not the `import {A} from './a'`;

#### Implementation details
When ever the user tries to copy paste the code within the editor between multiple files

1. During copy, vscode should be able to find imports corresponding to the copied text
2. During paste, it should automatically add the corresponding imports(may be more than one) aswell into the target file, along with the copied text

**Comment by mjbvz** [comment]
Closing as extension candidate / lack of further interest in this feature
