### ISSUE TITLE
Provide API to open a file/folder picker from an extension

### ISSUE THREAD

**Issue by dennisfrostlander** [Microsoft/vscode#18727]
- VSCode Version: 1.8.0
- OS Version: Any

I am developing an extension which is activated when a folder is open in VSCode. Additionally I want to provide a boostrapping command, e.g. the user chooses an empty folder and my extension prepares all necessary files in this folder. Think of how you create a new C# project in regular VS - Class1.cs, Project.csproj and other files are automatically created.

I was thinking to use the vscode.openFolder command to let the user choose a folder to initialize. The problem is that if the user chooses an empty folder, my extension is no longer activated, unless I use activationEvent:* which I am quite reluctant to do.
If only after vscode.openFolder command I could run one last line of code in my extension, that would be great.

```javascript
vscode.commands.executeCommand('vscode.openFolder').then(folder => {
    if (folder) initializeFolder(folder);
    //bye-bye
}) ;
```

The problem is that the command promise is currently resolved immediately, but not when the user chose a folder (or cancelled the dialog).

**Comment by jrieken** [comment]
That's not possible because opening a folder is more or less a restart of the window including the extension host. That mean you will be deactivated and there is very little time (1sec) for extensions to do something then. 

I see two options

1. run your init sequence *before* opening that new folder,
2. store a tagging file like (`.hello`) in that folder and use the [`workspaceContains:*.hello`](https://code.visualstudio.com/docs/extensionAPI/activation-events) activation command

Will any of the two work for you?

**Comment by dennisfrostlander** [comment]
@jrieken I understand that the extension is deactivated after the users opens the new folder. Maybe I was not clear enough with my question. After I call vscode.commands.executeCommand('vscode.openFolder') I cannot know which folder the user chose. In other words, the promise in previous example will _not_ be resolved with a folder name. It is resolved immediately when the file open dialog is shown and then I have no control when the user chooses a folder.

Both of your suggestions assume that I already know which folder to use, but that's not the case. 

Another option I was thinking about was to use workspace/global state to set some flag for the next restart of my extension.

Would it be possible for you to resolve the promise from executeCommand with a folder that the user chose? Or provider some other mechanism to get this data?

**Comment by jrieken** [comment]
I don't think so but @bpasero will know. The open folder command is handles by yet another process (the main process) and that then restarts the renderer process which causes the extension host process to restart

**Comment by bpasero** [comment]
Fair request, but not so straight forward to do in our current world. As Joh was saying, the command is entirely handled on the main side and the renderer is actually not involved at all. Even if we would return the folder back to you, at that time the renderer is likely being deactivated to open the picked folder so you could end up with timing issues.

I think the only way of solving this is by allowing an extension to open the native file picker to pick something and return this path back to the extension. The extension can then do the things needed and call the open method again, this time with the path already picked.

**Comment by WebFreak001** [comment]
I don't think you really need an API for this, my solution was backing up the package.json file in the extension path, overwriting activationEvents to `*`, set a global variable, reload and then on startup check for the global variable and restore the old package.json.

Code: https://github.com/Pure-D/code-d/blob/f1b18dda0a87042059ac33ad8a54e63411455dd6/src/project-creator.ts#L71-L89

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/13807
