### ISSUE TITLE
Adding tsconfig.json to existing Meteor project breaks Intellisense

### ISSUE THREAD

**Issue by jschlieber** [Microsoft/vscode#18725]
I recently tried VS Code as I no longer want to pay for Webstorm. I want to gradually migrate my existing Meteor (i.e. JavaScript) project to TypeScript. Thus, I need a mixed setup that allows for `js` as well as `ts` files. As long as I don't add a `tsconfig.json` file, everything works as expected (at least as far as I can tell). I'm gonna use a Meteor package to do the TypeScript compiling, so all I want from VS Code is Syntax Checks, Auto Complete and Intellisense. I don't need VS Code to do any compilations. But I still need a `tsconfig.json` file to configure the Meteor TypeScript compiler. And also I can't get VS Code to recognize typings for Meteor. I was hoping I could use `tsconfig.json` to point VS Code to those type definitions. But one after the other...

Syntax Checking, Autocomplete and Intellisense working (without `tsconfig.json`):
![index ts - admin - visual studio code_005](https://cloud.githubusercontent.com/assets/11458212/22061639/28ee5796-dd76-11e6-8dae-a8dbc2e3be5b.png)

Then I add an empty `tsconfig.json`, which is [permitted](http://www.typescriptlang.org/docs/handbook/tsconfig-json.html). What happens is that instantly there is no more Syntax Checking, Autocomplete and Intellisense in `js` as well as `ts` files. Forcing suggestions with `Ctrl + Space` just gives this:
![index ts - admin - visual studio code_006](https://cloud.githubusercontent.com/assets/11458212/22061747/abefeee8-dd76-11e6-9bbc-969af71a79ca.png)

Relaunching VS Code makes no difference. Interestingly, suggestions do still work inside of `tsconfig.json`:
![tsconfig json - admin - visual studio code_007](https://cloud.githubusercontent.com/assets/11458212/22061853/22d92bb4-dd77-11e6-8ea3-6bfe4a28c79f.png)

I also tried adding content to `tsconfig.json` (derived from [here](http://www.typescriptlang.org/docs/handbook/tsconfig-json.html)) and reloading VS Code
```javascript
{
    "compilerOptions": {
        "module": "system",
        "allowJs": true
    },
    "exclude": [
        "node_modules"
    ]
}
```
but nothing changes. No more Syntax Checks, no more Auto Complete, no more Intellisense. Removing `tsconfig.json` and reloading VS Code brings it all back.

So I'm stuck. Please Help! Thank you!

**Note 1**: I can't reproduce this issue when I open a new and empty project, then add a `ts` and a `js` file and then add a `tsconfig.json` file. In this new project everything works as expected.

**Note 2**: This project has a pretty large codebase and unfortunately I cannot share it for others to investigate.

- VSCode Version: 1.8.1
- OS Version: Linux Mint 17.1 Rebecca

Steps to Reproduce: Unfortunately unknown

**Comment by jschlieber** [comment]
## Update

Still no success. I removed all extensions (only had 2 installed so far anyway) and... nothing. I tried to reproduce this issue by creating a new Meteor project. But it's all working as expected with a new project.

**Comment by jschlieber** [comment]
## It works!

Turns out I had to exclude a Meteor package wich i forked and cloned into my `packages` folder. So by adding `packages/meteor-roles` to `exclude` in `tsconfig.json` everything works as expected again.

```javascript
{
  "compilerOptions": {
    "target": "es6",
    "allowJs": true
  },
  "exclude": [
    "node_modules",
    "packages/meteor-roles"
  ]
}
```

This was the only real difference I could spot compared to a new Meteor project. `meteor-roles` itself contains some Meteor projects in `examples` so maybe that causes some conflicts.

![tsconfig json - admin - visual studio code_011](https://cloud.githubusercontent.com/assets/11458212/22099529/00d48670-de2c-11e6-968b-1ca857d3d471.png)

Hope this helps in resolving this issue. In the mean time this can be used as a workaround.

**Comment by mjbvz** [comment]
Glad you found a solution. I suspect you were running into this TypeScript bug: https://github.com/Microsoft/TypeScript/issues/14636

In the presence of a `tsconfig.json`, TypeScript will sometimes try to watch a very large number of files. This can hang the TSServer and cause all intellisense to stop working. We're looking into a fix
