### ISSUE TITLE
My VSC is updating in loop between version 1.79.2 to 1.80.0 and vice versa

### ISSUE THREAD

**Issue by adrianojosue** [microsoft/vscode#187277]
Type: <b>Bug</b>

When I updated to version 1.80.0 it started to update in a loop between version 1.79.2 to 1.80.0 and vice versa.

VS Code version: Code 1.80.0 (Universal) (660393deaaa6d1996740ff4880f1bad43768c814, 2023-07-04T13:39:33.766Z)
OS version: Darwin x64 22.5.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-1030NG7 CPU @ 1.10GHz (8 x 1100)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|8.00GB (0.14GB free)|
|Process Argv|--crash-reporter-id 84753aed-b580-420b-95b2-3911187434a5|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (22)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-tailwindcss|bra|0.9.11
simple-react-snippets|bur|1.2.7
path-intellisense|chr|2.8.4
dart-code|Dar|3.68.1
flutter|Dar|3.68.0
vscode-eslint|dba|2.4.2
es7-react-js-snippets|dsz|4.4.3
auto-close-tag|for|0.5.14
auto-rename-tag|for|0.1.10
code-runner|for|0.12.0
vscode-gutter-preview|kis|0.30.0
vscode-language-babel|mgm|0.0.39
dotenv|mik|1.0.1
live-server|ms-|0.4.9
vscode-typescript-next|ms-|5.2.20230706
awesome-flutter-snippets|Nas|3.0.3
indent-rainbow|ode|8.3.1
quicktype|qui|12.0.46
LiveServer|rit|5.7.9
errorlens|use|3.11.1
console-ninja|Wal|0.0.180
pretty-ts-errors|yoa|0.4.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
py29gd2263:30776702
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
vsccc:30610678
282f8724:30602487
pyind779:30671433
f6dab269:30613381
pythonsymbol12:30671437
a9j8j154:30646983
showlangstatbar:30737416
vsctsb:30748421
pythonms35:30701012
03d35959:30757346
pythonfmttext:30731395
pythoncmvfstrcf:30756944
fixshowwlkth:30771522
showindicator:30766890
pythongtdpath:30769146
bgfeh915:30780428
pythonnosmt12:30779714
pythonidxpt:30784022
pythonnoceb:30776495
dsvsc013cf:30784101

```

</details>

**Comment by xgdgsc** [comment]
I'm also seeing this on macOS (m2 max).

版本: 1.80.0
提交: 660393deaaa6d1996740ff4880f1bad43768c814
日期: 2023-07-04T13:39:33.766Z
浏览器: Mozilla/5.0 (Macintosh; Intel Mac OS X 13_4_1) AppleWebKit/537.36 (KHTML, like Gecko) Code/1.80.0 Chrome/108.0.5359.215 Electron/22.3.14 Safari/537.36

**Comment by CryZe** [comment]
Yeah this just started happening for me too.

**Comment by rgripper** [comment]
There is also more than a doze of these "failing update" tickets already posted in the last 20 hours 😁

**Comment by joaomoreno** [comment]
https://github.com/microsoft/vscode/issues/187229#issuecomment-1625579951
