### ISSUE TITLE
Export function/class to implement dialog 

### ISSUE THREAD

**Issue by ccastrotrejo** [microsoft/vscode#187205]
I don't know if this is already implemented but it would be great to have the functions/classes exposed to implement this type of dialogs when developing vscode extensions
![image](https://github.com/microsoft/vscode/assets/102700317/382351f4-e7cf-46bb-a8bb-21150058cf63)

**Comment by sbatten** [comment]
I think you  are looking for this https://code.visualstudio.com/api/references/vscode-api#MessageOptions
