### ISSUE TITLE
June 2023 Update Issue

### ISSUE THREAD

**Issue by ahmedivy** [microsoft/vscode#187269]
Type: <b>Bug</b>

VS Code installs June 2023 Update and then after that it again downloads some update and request to restart app to apply some new update and if i restart i saw that June 2023 update gone and then again it downloads some update and if restart i saw it again updated to June 2023 and cycle is continued till now.

VS Code version: Code 1.80.0 (660393deaaa6d1996740ff4880f1bad43768c814, 2023-07-04T15:06:02.407Z)
OS version: Windows_NT x64 10.0.22621
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz (4 x 2808)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.88GB (7.12GB free)|
|Process Argv|--crash-reporter-id 4c156cb6-a04a-498d-a072-773b5026972c|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (104)</summary>

Extension|Author (truncated)|Version
---|---|---
language-x86-64-assembly|13x|3.0.0
vscode-django|bat|1.10.0
scenebuilderextension|bil|1.0.1
vscode-tailwindcss|bra|0.9.11
better-toml|bun|0.3.2
simple-react-snippets|bur|1.2.7
gitignore|cod|0.9.0
ddb50|CS5|1.1.1
doxdocgen|csc|1.4.0
vscode-markdownlint|Dav|0.51.0
vscode-eslint|dba|2.4.2
python-environment-manager|don|1.0.4
python-extension-pack|don|1.7.0
es7-react-js-snippets|dsz|4.4.3
gitlens|eam|14.0.1
vscode-html-css|ecm|1.13.1
vsc-material-theme-icons|equ|2.8.0
prettier-vscode|esb|9.19.0
flippidippi-theme|fli|0.0.8
auto-rename-tag|for|0.1.10
code-runner|for|0.12.0
codespaces|Git|1.14.9
copilot|Git|1.95.243
copilot-chat|Git|0.2.2
copilot-labs|Git|0.14.884
vscode-github-actions|git|0.25.8
vscode-pull-request-github|Git|0.68.0
go|gol|0.39.0
gc-excelviewer|Gra|4.2.57
vscode-test-explorer|hbe|2.21.1
vscode-drawio|hed|1.6.6
plantuml|jeb|2.17.5
better-cpp-syntax|jef|1.17.2
svg|joc|1.5.3
vsc-python-indent|Kev|1.18.0
graphql-for-vscode|kum|1.15.3
auto-commit-msg|Mic|0.26.1
dotenv|mik|1.0.1
graphql|mqu|0.1.2
vscode-docker|ms-|1.25.2
data-workspace-vscode|ms-|0.5.0
mssql|ms-|1.19.1
sql-bindings-vscode|ms-|0.4.0
sql-database-projects-vscode|ms-|1.1.1
autopep8|ms-|2023.6.0
isort|ms-|2023.10.0
python|ms-|2023.12.0
vscode-pylance|ms-|2023.7.10
jupyter|ms-|2023.6.1001861915
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.17
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-slideshow|ms-|0.1.5
remote-containers|ms-|0.299.0
remote-ssh|ms-|0.102.0
remote-wsl|ms-|0.80.2
azure-account|ms-|0.11.5
cmake-tools|ms-|1.14.34
cpptools|ms-|1.16.3
cpptools-extension-pack|ms-|1.3.0
makefile-tools|ms-|0.7.0
powershell|ms-|2023.6.0
remote-explorer|ms-|0.4.1
test-adapter-converter|ms-|0.1.8
autodocstring|njp|0.6.1
launchqtcreator|Ora|0.1.12
cargo|pan|0.2.3
material-icon-theme|PKi|4.28.0
material-product-icons|PKi|1.5.0
fabric8-analytics|red|0.3.10
java|red|1.20.0
LiveServer|rit|5.7.9
synthwave-vscode|Rob|0.1.15
es7-react-js-snippets|rod|1.9.3
bootstrap-product-icons|rub|1.0.2
rust-analyzer|rus|0.3.1481
vscode-qt-for-python|sea|7.4.0
gitmoji-vscode|sea|1.2.3
html5-boilerplate|sid|1.1.1
swdc-vscode|sof|2.7.0
icons|tal|3.6.3
cython|tcw|0.1.0
pdf|tom|1.2.2
in-your-face-incredible|TTO|1.1.0
cmake|twx|0.0.17
vscode-choosealicense|ult|0.9.2
intellicode-api-usage-examples|Vis|0.2.7
vscodeintellicode|Vis|1.2.30
vscode-gradle|vsc|3.12.7
vscode-java-debug|vsc|0.52.2023063003
vscode-java-dependency|vsc|0.23.0
vscode-java-pack|vsc|0.25.12
vscode-java-test|vsc|0.39.0
vscode-maven|vsc|0.41.0
vscode-spring-initializr|vsc|0.11.2
vscode-icons|vsc|12.4.0
vscode-wakatime|Wak|24.2.0
quokka-vscode|Wal|1.0.547
jinja|who|0.0.8
masm-tasm|xsr|1.1.1
vscode-dosbox|xsr|0.1.8
vscode-java-saber|You|0.1.2
markdown-all-in-one|yzh|3.5.1
material-theme|zhu|3.15.18

(20 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscoreces:30445986
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
py29gd2263:30776702
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
vscccc:30610679
2e4cg342:30602488
pyind779:30671433
f6dab269:30613381
pythonsymbol12:30671437
2i9eh265:30646982
showlangstatbar:30737416
vsctsb:30748421
pythonms35:30701012
03d35959:30757346
24365598:30736109
pythonfmttext:30731395
pythoncmv:30756943
fixshowwlkth:30771522
pythongtdpath:30769146
bgfeh915:30780428
pythonnosmt12:30779714
pythonidxpt:30784022
pythonnoceb:30776495
e537b577:30772215
cmakestatusbarv2:30779594

```

</details>

**Comment by Kurt-Shiwz** [comment]
The same problem. vscode  between 1.79.2  and 1.80.
MacOS 13.4.1 (Apple M1 pro)
