### ISSUE TITLE
Code helper (renderer) eats a lot of CPU

### ISSUE THREAD

**Issue by olegstepanov** [microsoft/vscode#187272]
Type: <b>Performance Issue</b>

I experience slowdoen and Activity Monitor shows that code helper (renderer) eats a lot of CPU.

VS Code version: Code 1.80.0 (Universal) (660393deaaa6d1996740ff4880f1bad43768c814, 2023-07-04T13:39:33.766Z)
OS version: Darwin x64 22.5.0
Modes:
Remote OS version: Linux x64 5.4.161-26.3
Connection to 'ssh-remote+bigb-dev-ogstepanov.sas.yp-c.yandex.net' could not be established

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-1038NG7 CPU @ 2.00GHz (8 x 2000)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|5, 4, 4|
|Memory (System)|16.00GB (0.52GB free)|
|Process Argv|--crash-reporter-id f34d6c97-210d-4af0-9169-4cb9b07cceaa|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: bigb-dev-ogstepanov.sas.yp-c.yandex.net|
|OS|Linux x64 5.4.161-26.3|
|CPUs|Intel(R) Xeon(R) Gold 6230 CPU @ 2.10GHz (80 x 2095)|
|Memory (System)|97.35GB (82.69GB free)|
|VM|0%|

Connection to 'ssh-remote+bigb-dev-ogstepanov.sas.yp-c.yandex.net' could not be established
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    4	   180	  4879	code main
    5	    66	  4882	   gpu-process
    0	    16	  4884	   utility-network-service
    2	   246	  4885	window [1] (mutable_row.h — bsyeti-cpp (Workspace) [SSH: bigb-dev-ogstepanov.sas.yp-c.yandex.net])
  106	   623	  4886	window [2] (queries.py — ads-solo (Workspace) [SSH: bigb-dev-ogstepanov.sas.yp-c.yandex.net])
    0	    66	  4894	extensionHost [2]
    0	    33	  4906	     electron-nodejs (/Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Plugin).app/Contents/MacOS/Code Helper (Plugin) --ms-enable-electron-run-as-node /Users/ogstepanov/.vscode/extensions/ms-vscode-remote.remote-ssh-0.102.0/out/localServer.js {"serverId":1,"ipcHandlePath":"/var/folders/zn/gyh8x6zs3jb9t084xqqfqhldynzt13/T/vscode-ssh-askpass-1a7794b6d8716b835710b6622d2d6829f9e9b66a.sock","sshCommand":"ssh","sshArgs":["-v","-T","-D","54441","-o","ConnectTimeout=15","bigb-dev-ogstepanov.sas.yp-c.yandex.net","bash"],"serverDataFolderName":".vscode-server","dataFilePath":"/Users/ogstepanov/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-8d638b94-660393deaaa6d1996740ff4880f1bad43768c814-0.102.0/data.json"})
    0	    49	  4910	       ssh -v -T -D 54441 -o ConnectTimeout=15 bigb-dev-ogstepanov.sas.yp-c.yandex.net bash
    0	    66	  4895	extensionHost [1]
    0	    66	  4903	shared-process
    0	     0	  5459	     /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0	    33	  4904	fileWatcher [2]
    0	    33	  4905	fileWatcher [1]
    0	    33	  4911	ptyHost
    0	    66	  4945	   window
    0	    82	  5451	window [3] (Issue Reporter)

Remote: SSH: bigb-dev-ogstepanov.sas.yp-c.yandex.net
CPU %	Mem MB	   PID	Process
    0	     0	2162030	remote agent
    0	     0	2162066	   ptyHost
    0	     0	2162517	     /usr/bin/fish
    0	     0	2163041	     /usr/bin/fish
    0	   197	2162108	   extension-host
    1	   901	2162729	     /home/ogstepanov/.vscode-server/bin/660393deaaa6d1996740ff4880f1bad43768c814/node /home/ogstepanov/.vscode-server/extensions/ms-python.vscode-pylance-2023.7.10/dist/server.bundle.js --cancellationReceive=file:36b8942db1db133ad689695135c57520d77ee573d8 --node-ipc --clientProcessId=2162108
    0	    16	2162109	   extension-host
    0	     0	2162130	   fileWatcher
    0	     0	2162141	   fileWatcher
    0	     0	2308436	   /bin/sh -c /usr/bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0	     0	2308437	     /usr/bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
Connection to 'ssh-remote+bigb-dev-ogstepanov.sas.yp-c.yandex.net' could not be established
```

</details>
<details>
<summary>Workspace Info</summary>

```

|  Remote: SSH: bigb-dev-ogstepanov.sas.yp-c.yandex.net
Connection to 'ssh-remote+bigb-dev-ogstepanov.sas.yp-c.yandex.net' could not be established;
```

</details>
<details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
jupyter-keymap|ms-|1.1.2
remote-ssh|ms-|0.102.0
remote-ssh-edit|ms-|0.86.0
remote-explorer|ms-|0.4.1
ayu|tea|1.0.5
forbeslindesay-taskrunner|for|1.0.0
vscode-clangd|llv|0.1.24
python|ms-|2023.12.0
vscode-pylance|ms-|2023.7.10
cpptools|ms-|1.16.3
vscode-yandex-arc|per|0.189.0
jinjahtml|sam|0.20.0
trailing-spaces|sha|0.4.1

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
py29gd2263:30776702
vscaat:30438848
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
vsccc:30610678
282f8724:30602487
pyind779:30671433
f6dab269:30613381
pythonsymbol12:30671437
showlangstatbar:30737416
vsctsb:30748421
pythonms35:30701012
03d35959:30757346
pythonfmttext:30731395
pythoncmv:30756943
fixshowwlkth:30771522
pythongtdpath:30769146
bgfeh915:30780428
pythonnosm12tcf:30779713
pythonidxpt:30784022
pythonnocebcf:30776496

```

</details>

**Comment by olegstepanov** [comment]
Here's a profile I collected, as VS code itself was sluggish to the point of stalling.
[Profile-20230707T171331.json.zip](https://github.com/microsoft/vscode/files/11982872/Profile-20230707T171331.json.zip)

**Comment by jrieken** [comment]
Thanks for the profile! That's really good information, looks like a lot of time is spend in [`checkTrim`](https://github.com/microsoft/vscode/blob/efb49cc271d6eea5634ac395e36e1e4cd108a447/src/vs/platform/uriIdentity/common/uriIdentityService.ts#L90-L114) called via [changeMany](https://github.com/microsoft/vscode/blob/b529a3be0bc07437248c6578606e94ab3cc02731/src/vs/workbench/api/browser/mainThreadDiagnostics.ts#L55). This suggests that extensions are reporting errors across very many files. Does that match you project setup? Does the problems panel show many errors and if so for what language/files does it show them?

**Comment by jrieken** [comment]
@olegstepanov confirmation ping for https://github.com/microsoft/vscode/issues/187272#issuecomment-1630484101

**Comment by jrieken** [comment]
Moving to August for confirmation. I have pushed a change that limits the amount of files that can have diagnostics. Based on the profile information that will fix this issue

**Comment by da730** [comment]
> Moving to August for confirmation. I have pushed a change that limits the amount of files that can have diagnostics. Based on the profile information that will fix this issue

Can't wait to use the new version. This issue bothers me almost every day when I am working on TS project with a large scale.

**Comment by jrieken** [comment]
Closing this but I would like to get confirmation from @olegstepanov

**Comment by andreamah** [comment]
@jrieken are there alternative verification steps if we don't get a response from @olegstepanov?

**Comment by Tyriar** [comment]
Verified via another code review. Change makes sense and there's also a test to verify the new behavior.
