### ISSUE TITLE
Automatic markdown link paste happens with any text with a colon

### ISSUE THREAD

**Issue by MeghanKulkarni** [microsoft/vscode#187201]
Does this issue occur when all extensions are disabled?: Yes/No
No

- VS Code Version: 
- OS Version: 

pasting text with a colon in it leads to automatic markdown link pasting (with the new format url and markdown link feature)

**Comment by mjbvz** [comment]
This seems to be fixed. We now restrict this feature to specific uri schemes: https://github.com/microsoft/vscode/blob/6079e24015ed3594788b1e68f1d5af764cdd9003/extensions/markdown-language-features/src/languageFeatures/copyFiles/pasteUrlProvider.ts#L145
