### ISSUE TITLE
Secrets store `onDidChange` does not fire in the window where the update was made in VS Code 1.8.0

### ISSUE THREAD

**Issue by tomduncalf-figma** [microsoft/vscode#187247]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.80.0 (660393deaaa6d1996740ff4880f1bad43768c814)
- OS Version: macOS 12.5.1 (21G83)

**Steps to Reproduce:**

1. Create an extension listens for changes in the secrets store and calls `console.log` when there is a change (for example), using `context.secrets.onDidChange`.
2. Update the secrets store, using `context.secrets.store`

**Expected behaviour:**

The change listener should fire and the log message will be seen in both the current VS Code window, and any other VS Code windows which are open where the extension is running

**Actual behaviour:**

In VS Code 1.8.0 (and also Insiders and VS Code built from source from the latest `main`), the `onDidChange` listener never fires in the window where the update was made. It does fire in other windows. 

In 1.79.2, the listener would fire in the instance where the update was made. It seems the behaviour changed in https://github.com/microsoft/vscode/pull/185077/, specifically [the change listener is paused when storing the secret](https://github.com/microsoft/vscode/pull/185077/files#diff-726112fcb3dbe72a5f8464bc5fd7e3d1a408d32723a380f4354121d7336a1618R88-R91).

It may be that this is a deliberate change, in which case it should be documented, but it seems somewhat surprising/a bit of a regression to me, as now you need to make sure you manually invoke any secret store change handlers in addition to using a listener.

This broke some functionality in our extension which was working in 1.79.2, the workaround is just to call the change handler manually at the point of updating the secret store, but this means you have to remember to do this in multiple places potentially and breaks my expectations around how the listener would work.

**Repro:**

This example extension provides a minimal repro of the bug: https://github.com/tomduncalf-figma/vscode-insiders-secrets-ondidchange-bug. Running the extension and triggering the "Hello World" command will log `Secrets changed` in the regular VS Code build, but will not log anything in Insiders.

**Comment by TylerLeonhardt** [comment]
Thanks for calling this out. I originally did this _because_ you already have the secret you're storing in the window you're storing it in... but this is changed behavior so I'll change it back. We'll also include it in the 1.80 recovery which will be next week.

**Comment by BeFunes** [comment]
Hi! We're having the same problem in our extension .
@tomduncalf-figma, could you share what you did to manually call the listener?

**Comment by TylerLeonhardt** [comment]
Closing this since the PR is merged and it'll be in 1.80.1

**Comment by tomduncalf-figma** [comment]
Hey @BeFunes - I just mean something like:

```
context.secrets.onDidChange(e => {
  handleSecretsDidChange();
});

function handleSecretsDidChange() {
  // do stuff
}

function somethingWhichUpdatesSecrets() {
  context.secrets.store("whatever", "secret");
  handleSecretsDidChange(); // This won't be necessary after 1.80.1 but for now we need to manually invoke the change listener, otherwise it will never fire for the VS Code window in which the change happened
}
```

**Comment by TylerLeonhardt** [comment]
Verification in Stable candidate:

* download the zip, unzip it, and install the VSIX:
[secret-storage-issue-verification-0.0.1.vsix.zip](https://github.com/microsoft/vscode/files/12030496/secret-storage-issue-verification-0.0.1.vsix.zip)
* open two VS Code windows
* Run the command `Secret Storage Issue Verification: Do the thing`
* You should see a notification in each window saying that a secret changed

in 1.80.0, you would only see it in the window that you didn't run the command in.
