### ISSUE TITLE
Issue when saving - crazy identation

### ISSUE THREAD

**Issue by pedrodgcouto** [Microsoft/vscode#18721]
Hi there. When I save an HTML + JS file in VSCode, makes some crazy identation on the file and then saves. 

- VSCode Version: Code 1.8.1 (ee428b0eead68bf0fb99ab5fdc4439be227b6281, 2016-12-19T14:42:49.304Z)
- OS Version: Darwin x64 16.3.0
- Extensions:

|Extension|Author|Version|
|---|---|---|
|theme-monokai-dark-soda|AdamCaviness|0.0.5|
|EditorConfig|EditorConfig|0.3.4|
|beautify|HookyQR|0.7.3|
|theme-hackershaze|Nuuf|1.3.1|
|material-icon-theme|PKief|1.2.0|
|vscode-docker|PeterJausovec|0.0.11|
|Seti-theme|TsumiNa|0.0.1|
|html-css-class-completion|Zignd|1.0.3|
|html-snippets|abusaidm|0.0.18|
|Bookmarks|alefragnani|0.10.2|
|one-monokai|azemoh|0.2.4|
|materialcolorsnippets|brunnerlivio|0.1.1|
|polymer-snippets|chimon2000|1.0.1|
|jshint|dbaeumer|0.10.15|
|vscode-eslint|dbaeumer|1.2.2|
|githistory|donjayamanne|0.1.5|
|jquerysnippets|donjayamanne|0.0.1|
|theme-dracula|dracula-theme|1.2.5|
|tslint|eg2|0.8.1|
|knockoutjs|furstenberg|0.1.0|
|Theme-FlatlandMonokai|gerane|0.0.4|
|docthis|joelday|0.3.9|
|language-polymer|jonwolfe|0.7.10|
|vscode-JS-CSS-HTML-formatter|lonefy|0.2.2|
|mssql|ms-mssql|0.2.0|
|Theme-MaterialKit|ms-vscode|0.1.1|
|latex|ms-vscode|0.1.3|
|debugger-for-chrome|msjsdiag|2.4.2|
|polymer-ide|polymer|0.3.0|
|vscode-icons|robertohuertasm|7.0.1|
|Spell|seanmcbreen|0.9.1|
|Align|steve8708|0.2.0|
|addDocComments|stevencl|0.0.8|
|perl-html-template|viatsko|1.1.1|
|bootstrap-3-snippets|wcwhitehead|0.0.9|
|JavaScriptSnippets|xabikos|1.2.0|
|Material-theme|zhuangtongfa|1.0.3|

---

Steps to Reproduce:

1.
2.

**Comment by aeschli** [comment]
Please add a code example that shows the crazy indentation after formatting.

**Comment by pedrodgcouto** [comment]
Sure, here it goes the gist for you to see well.

https://gist.github.com/pedrodgcouto/c18b7c380cce8a4d6ff4f252922bbf1d

I'm using the version 1.8.1 for macOS.

**Comment by aeschli** [comment]
The problem is with the [jsbeautifier](http://jsbeautifier.org/) that we use. Please file the bug [there](https://github.com/beautify-web/js-beautify/issues)
