### ISSUE TITLE
Syntax highlighting/colorization bug for C/C++ 

### ISSUE THREAD

**Issue by pavolmarko** [Microsoft/vscode#18720]
VSCode Version: 1.8.1
OS Version: Linux (Ubuntu)

Steps to reproduce:
Enter this code into a .cc file:
```
int main() {
  os << (a? b->c(): d) << "#\n";
  const char* this_is_now_also_wrong = "??";
}
```

The problem:
Highlighting is weird:
![vscode_wrong_colorization](https://cloud.githubusercontent.com/assets/7988188/22060627/d6106cde-dd71-11e6-8a58-e80ba85bd5d1.png)

**Comment by aeschli** [comment]
![image](https://cloud.githubusercontent.com/assets/6461412/22210603/b1ece6b2-e18a-11e6-87f5-60588004bbca.png)

Seem to work with the latest grammar (in the insider build)
