### ISSUE TITLE
delete previous word with ctrl+backspace adds the control character in integrated powershell

### ISSUE THREAD

**Issue by amunger** [microsoft/vscode#187209]
ctrl+backspace adds `^W` in the integrated powershell terminal rather than deleting the previous word as it does outside of vscode.

confirmed that both terminals are pointing to the same executable:
<img width="372" alt="image" src="https://github.com/microsoft/vscode/assets/2019016/867f14ee-b08c-4f94-b284-db9b2f12df80">

This seems specific to my dev machine, I don't think I've ever been able to use this (though I sure to miss it)
Repros on both powershell exes I have, but not for cmd, git bash, wsl

**Comment by Tyriar** [comment]
@amunger can you run the troubleshoot keybindings command and paste in the output when you hit ctrl+w?

**Comment by amunger** [comment]
I can't seem to repro this anymore
