### ISSUE TITLE
Shortcuts mentioned in the menu are not in sync with the actual shortcuts

### ISSUE THREAD

**Issue by thekalinga** [Microsoft/vscode#18731]
- VSCode Version:

Version 1.9.0-insider
Commit 2cdc2b3da8f0fd5322b48747241584cf9dd98f8f
Date 2017-01-13T07:03:18.620Z
Shell 1.4.6
Renderer 53.0.2785.143
Node 6.5.0

- OS Version:

Ubuntu

Steps to Reproduce:
1. I have installed IntellIj keybinding plugin & it resets `Goto symbol in workspace` to a shortcut of `Ctrl+N`
2. But if I go to vscode menu `File`, `New file` option shows that `Ctrl+N` is mapped it.
3. But in reality when I press `Ctrl+N`, I am shown `Goto symbol` dialog.

**Comment by bpasero** [comment]
@thekalinga does this problem fix itself when you quit and restart VS Code?

**Comment by thekalinga** [comment]
No it does not. This is persistent even after many restarts

**Comment by bpasero** [comment]
@thekalinga awesome catch 👍
