### ISSUE TITLE
After I press the shortcut that opens in Explorer, it becomes "Run" in the menu

### ISSUE THREAD

**Issue by LongYinStudio** [microsoft/vscode#187349]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.80.0 
- OS Version: Windows_NT x64 10.0.19045

Steps to Reproduce:

1. Press <kbd>Alt</kbd>+<kbd>Shift</kbd>+<kbd>R</kbd> in sequence
2. You will jump to "Run" instead of Explorer

**Comment by roblourens** [comment]
I don't follow, is this supposed to be a shortcut for the explorer? Where do you see that?

**Comment by LongYinStudio** [comment]
yes. Default shortcut key for opening current file in Explorer is <kbd>alt</kbd>+<kbd>shift</kbd>+<kbd>r</kbd>.  But when I press this shortcut, it goes to the "run" screen in the menu.
