### ISSUE TITLE
request to refactor bordered version of color schemes directly in VSC, please see description

### ISSUE THREAD

**Issue by OTonGitHub** [microsoft/vscode#187361]
Type: <b>Feature Request</b>

A lot of themes have bordered and non bordered version, I'd like to request for VSC to refactor this as a standard feature related to color theme, so its more streamlined for extension authors and users/developers to choose between bordered and unborderd version of a theme, sometimes we switch between monitors, old/new, with more/less contrast but still wanna work with favourite theme, then having a bordered and nonbordered version of same theme is a nice to have, a way to even generate in VSC bordered version will be particularly nice

VS Code version: Code 1.80.0 (660393deaaa6d1996740ff4880f1bad43768c814, 2023-07-04T15:06:02.407Z)
OS version: Windows_NT x64 10.0.22621
Modes:

**Comment by aeschli** [comment]
Automatically generating a theme is difficult as all colors must work together. Just using a border color as background color might result in indistinguishable colors and bad contrasts.

No plans to implement such a feature. Themes are best hand crafted and tested.
