### ISSUE TITLE
Debug Console lineheight looks like an extra blank line per line printed

### ISSUE THREAD

**Issue by LambiekNL** [Microsoft/vscode#18734]
- VSCode Version:
Version 1.8.1
Commit ee428b0eead68bf0fb99ab5fdc4439be227b6281
Date 2016-12-19T14:41:20.664Z
Shell 1.4.6
Renderer 53.0.2785.143
Node 6.5.0

- OS Version:
Linux 3.13.0-24-generic #47-Ubuntu SMP Fri May 2 23:30:00 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

Steps to Reproduce:

1.

test.py:
print "Hello"
print "World"

![image](https://cloud.githubusercontent.com/assets/19410118/22062242/0b585a26-dd79-11e6-8072-2c105fceabdc.png)

2.

Expected output:

![image](https://cloud.githubusercontent.com/assets/19410118/22062321/6a37f48e-dd79-11e6-943d-472f4d27d5fb.png)

**Comment by LambiekNL** [comment]
Update:

Multiline output shows good:

test.py:
print "Hello"
print "World"
print "Hello\nWorld"

Output:

![image](https://cloud.githubusercontent.com/assets/19410118/22110230/3c3c4480-de5b-11e6-8fc1-f5562722371f.png)

**Comment by isidorn** [comment]
Dup of https://github.com/Microsoft/vscode/issues/17526
