### ISSUE TITLE
Rename Symbol option missing when editing javascript.

### ISSUE THREAD

**Issue by andrewtoups** [microsoft/vscode#187372]
Type: <b>Bug</b>

1. Open a javascript file.
2. Highlight a variable and press "F2".
3. Nothing happens.
4. Highlight a variable and right click.
5. The option for "Rename Symbol" is missing.
6. Open the command palette and type "Rename Symbol."
7. The option does not appear in the command palette.

VS Code version: Code 1.80.0 (660393deaaa6d1996740ff4880f1bad43768c814, 2023-07-04T15:06:02.407Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 1600 Six-Core Processor             (12 x 3194)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.95GB (5.89GB free)|
|Process Argv|--crash-reporter-id cc0cf839-d479-4883-9622-0bed511ed1b1|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-scss|mrm|0.10.0
vscode-docker|ms-|1.25.2
remote-containers|ms-|0.299.0
remote-ssh|ms-|0.102.0
remote-ssh-edit|ms-|0.86.0
remote-wsl|ms-|0.80.2
vscode-remote-extensionpack|ms-|0.24.0
remote-explorer|ms-|0.4.1
remote-server|ms-|1.2.1
LiveServer|rit|5.7.9
rust-analyzer|rus|0.3.1575
sass-indented|syl|1.8.26
even-better-toml|tam|0.19.0
JavaScriptSnippets|xab|1.8.0
markdown-all-in-one|yzh|3.5.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
py29gd2263:30784847
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
vsccc:30610678
282f8724:30602487
pyind779:30671433
89544117:30613380
pythonsymbol12:30671437
showlangstatbar:30737416
vsctsb:30748421
pythonms35:30701012
a2ce3375:30757347
pythonfmttext:30731395
pythoncmv:30756943
fixshowwlkth:30771522
showindicator:30785052
pythongtdpath:30769146
bgfeh915:30780428
pythonnosm12tcf:30779713
pythonidxpt:30784022
pythonnocebcf:30776496
dsvsc013cf:30784101

```

</details>

**Comment by gjsjohnmurray** [comment]
Please use the Start Extension Bisect command to investigate whether the problem is being caused by one of your extensions.

**Comment by andrewtoups** [comment]
I just used the Extension Bisect feature and the problem was not resolved.
![image](https://github.com/microsoft/vscode/assets/15691275/21a89ef7-6def-4a78-a566-d02f0f576822)

**Comment by mjbvz** [comment]
Did you disable the built-in JS/TS language extension? Search `@builtin Javascript` in the extensions view and make sure `TypeScript and JavaScript Language Features` is still enabled

**Comment by andrewtoups** [comment]
Hey that was it! I don't know how it got disabled but that did the trick. Thanks!
