### ISSUE TITLE
Operating System Specific Properties in launch.json

### ISSUE THREAD

**Issue by edvinv** [Microsoft/vscode#1873]
... it would be nice to have them. For example: OS specific env variables...

**Comment by felixfbecker** [comment]
+1

**Comment by isidorn** [comment]
fyi @weinand

**Comment by weinand** [comment]
Proposal: wrapping any attribute or group of attributes in a sub structure "osx", "linux", and "windows" makes it OS specific.

**Comment by felixfbecker** [comment]
Yes, and env variables declared without an OS should merge with the OS specific ones.

**Comment by joekim** [comment]
@weinand 
+1 for proposal. Need to specify a different "runtimeExecutable" when on osx vs. win32

**Comment by JimiC** [comment]
:+1: This will come very handy especially when developing Electron apps. Currently I'm stuck at changing the path each time when changing OS env.

**Comment by weinand** [comment]
@isidorn am I right that this feature does not change the structure of the launch config that arrives in the debug adapter?

Example:
```json
{
   "type": "node",
   "request": "launch",
   "runtimeExecutable": "mynode",
   "Windows": {
     "runtimeExecutable": "mynode.exe" 
   }
}
```
arrives in the debug adapter on OS X and linux as:
```json
{
   "type": "node",
   "request": "launch",
   "runtimeExecutable": "mynode" 
}
```
and on Windows as:
```json
{
   "type": "node",
   "request": "launch",
   "runtimeExecutable": "mynode.exe" 
}
```

**Comment by isidorn** [comment]
@weinand no, I also send the "windows" part to each adapter. I could remove it - but we are not doing that for any other property so far - removing it from the launch.json

**Comment by felixfbecker** [comment]
@isidorn please do that on the VS Code side

**Comment by weinand** [comment]
@isidorn and what are you sending to the adapter in this case:
```json
{
   "type": "node",
   "request": "launch",
   "Windows": {
     "runtimeExecutable": "mynode.exe" 
   },
   "OSX": {
     "runtimeExecutable": "mynode" 
   },
   "linux": {
     "runtimeExecutable": "mynode" 
   }
}
```

**Comment by isidorn** [comment]
on windows
```
{
   "type": "node",
   "request": "launch",
   "runtimeExecutable": "mynode.exe",
   "Windows": {
     "runtimeExecutable": "mynode.exe" 
   },
   "OSX": {
     "runtimeExecutable": "mynode" 
   },
   "linux": {
     "runtimeExecutable": "mynode" 
   }
}
```

**Comment by felixfbecker** [comment]
thats fine 👍

**Comment by weinand** [comment]
@isidorn intellisense inside the OS sections works?

**Comment by JimiC** [comment]
Excuse my ignorance but doesn't OSX use "mynode.app"?

**Comment by weinand** [comment]
@JimiC "mynode.app" is the name of the application folder (aka "application bundle'") which the Finders shows as the application "mynode" in the UI. But mynode.app is not an executable in the OS sense, so you can not use it with the "runtimeExecutable" attribute from above. For "runtimeExecutable" you have to specify a file that has the executable bit set, e.g. "/usr/local/bin/node".

**Comment by JimiC** [comment]
@weinand Thanks for clarifying. I see it now. The executable is in "*.app/Contents/MacOS/".

**Comment by isidorn** [comment]
@weinand not inside, but you get OS sections offered top level

**Comment by weinand** [comment]
@isidorn we should offer intellisense for the OS types on the top level and repeat the intellisense inside the OS sections.

**Comment by isidorn** [comment]
Added intellisense inside os sections
