### ISSUE TITLE
Syntax highlighting broken for Python after updating to 1.80.0

### ISSUE THREAD

**Issue by AliKHaliliT** [microsoft/vscode#187378]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: Version: 1.80.0 (user setup)
- OS Version: Windows_NT x64 10.0.19045

Steps to Reproduce:

After the latest update, the syntax highlighting is broken for Python. I tried reverting to older extension releases or disabling them but the issue persisted. 

![image](https://github.com/microsoft/vscode/assets/30647838/3744ea57-5bd6-4004-843a-030f871e1358)

**Comment by alexr00** [comment]
Can you share a copy+pastable example I can use to reproduce the issue?

**Comment by AliKHaliliT** [comment]
I am sorry, but I don't think that it is possible to replicate the problem through a "copy+pastable" code. Suppose the problem does exist and is not machine specific. In that case, the syntax highlighting should technically not work for any Python code in a VSCode with only the extension with the id "ms-python.python" installed.

**Comment by alexr00** [comment]
This snippet looks fine to me:
<img width="433" alt="image" src="https://github.com/microsoft/vscode/assets/38270282/7a619260-710f-41db-8257-bef3833c4b62">

**Comment by AliKHaliliT** [comment]
That problem is apparent in your code snippet.

This is what the code snippet you shared looks like on my end.

![image](https://github.com/microsoft/vscode/assets/30647838/2b500da2-85a6-4262-997d-c520d197576f)

This the code snippets you've requested,

`# VSCode Syntax Highlighting: Python Test

# Variable assignment
x = 10

# Function definition
def greet(name):
    print("Hello, " + name + "!")

# Conditional statement
if x > 5:
    print("x is greater than 5")
else:
    print("x is less than or equal to 5")

# Looping
for i in range(5):
    print(i)

# String concatenation
message = "Hello"
message += " World!"

# List comprehension
numbers = [1, 2, 3, 4, 5]
squared = [x**2 for x in numbers]

# Class definition
class Animal:
    def __init__(self, name):
        self.name = name

    def sound(self):
        pass

# Object instantiation
cat = Animal("Cat")

# Method call
cat.sound()

# Built-in functions
print(len(numbers))
print(max(numbers))

# Exception handling
try:
    result = 10 / 0
except ZeroDivisionError:
    print("Cannot divide by zero")

# Import statement
import math

# Function call from imported module
print(math.sqrt(25))`

and how it looks on my end,

![image](https://github.com/microsoft/vscode/assets/30647838/19f4e975-f709-40da-92d4-fa53bb3c288e)


And below is how it is supposed to look like and used to look before the update. 

https://raw.githubusercontent.com/microsoft/vscode-python/main/images/ConfigureDebugger.gif

Above is the best example I could find. 

P.S: I did a clean Uninstall (i.e. Used a third-party app to remove the VSCode, removed the leftovers, performed a cache clean, performed a registry clean, ...) and Install of the VSCode but the issue still persists.

**Comment by RedCMD** [comment]
looks like semantic highlighting isn't working?

**Comment by alexr00** [comment]
If it's semantic highlighting then that would be an issue with one of the users installed extensions.

**Comment by jim3** [comment]
FWIW, I was having the same problem and could not figure out why. Uninstalling, then re-installing Pylance fixed it, the syntax highlighting came back. 🎉
