### ISSUE TITLE
[Bug] non-copilot quickfix launches a copilot in-line editor

### ISSUE THREAD

**Issue by amunger** [microsoft/vscode#187328]
Steps to Reproduce:

1. add a method to an interface
2. go to an implementing class and open the quickfix on the class
3. select `Implement interface...`
:bug: method is added correctly, but an in-line editor is also opened to ask copilot to do the same thing

![Recording 2023-07-07 at 15 09 55](https://github.com/microsoft/vscode/assets/2019016/8eb787e2-f7e2-45f5-a666-ad31f70c3f95)

**Comment by jrieken** [comment]
That's `typescript.experimental.aiQuickFix`

**Comment by aiday-mar** [comment]
With @mjbvz's recent PR https://github.com/microsoft/vscode/pull/200162 and previous work before it, it is now possible to enable separately the different TypeScript code actions using the setting `typescript.experimental.aiCodeActions` as follows:

```
"typescript.experimental.aiCodeActions": {
    "classIncorrectlyImplementsInterface": true
  },
```

If the action uses copilot, it will add the suffix 'with Copilot' to indicate this. 

![Screenshot 2023-12-20 at 16 28 15](https://github.com/microsoft/vscode/assets/61460952/1a54bf75-fb1d-4598-afc4-b5dc6491103c)

This issue will be closed.
