### ISSUE TITLE
Filter commands by extension

### ISSUE THREAD

**Issue by ppo** [microsoft/vscode#187383]
Please allow to see all the commands coming from a given extension. And/or in "show all commands", allow to clearly identify from which extension a command is coming.

**Accessibility:**

* From the extension's page, in the "manage" menu (cog icon), besides "Extension Settings".
* In the "show commands" modal, allow to filter like in settings `@ext:extension-id`.

**Use cases:**

* I found a bug or have a suggestion related to a command => where should I go?
* What can I do with this extension?
* Do I really need that extension?

**Comment by roblourens** [comment]
You can do this by clicking the extension in the extension viewlet to see the extension README and details, and looking under the "Feature Contributions" tab.

<img width="1042" alt="image" src="https://github.com/microsoft/vscode/assets/323878/d716ed09-f251-415a-a503-88f8ecadbb17">

**Comment by ppo** [comment]
@roblourens Thanks.… but my message was probably not clear enough.

That allows from an extension, to see its commands.  
I would like to have also the opposite relationship: from a command, see to what extension it belongs.

For example, in the "show all commands" modal, I see "Delete Duplicate Lines"… but where does that come from?  
Is there a way to find that information?
