### ISSUE TITLE
Can't open my vscode properly 

### ISSUE THREAD

**Issue by boli8845** [microsoft/vscode#187368]
ADD ISSUE DESCRIPTION HERE
I tried restart and also create new codespaces but all not working. 
The error message I got is "The workbench failed to connect to the server (Error: Time limit reached)" and my existing folders won't load. 
my number is https://github.com/code50/27709499. 
Can you please help me check and let me know where the issue is ?
Version: 1.80.0
Commit: 660393deaaa6d1996740ff4880f1bad43768c814
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36
Embedder: codespaces

**Comment by rebornix** [comment]
Please file the issue against the codespace extension, thanks!
