### ISSUE TITLE
Kernel picker spins indefinitely when there are no kernel sources

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode#187325]
1. Have Python extension installed but not Jupyter extension (setting up a new machine)
2. Open an untitled Jupyter notebook
3. Run a cell
4. Get prompted to browse marketplace for kernel extensions
5. Hit cancel
6. :bug: kernel picker spins saying it's detecting kernels:
 
<img width="579" alt="image" src="https://github.com/microsoft/vscode/assets/30305945/3ca1c0fb-9e90-45fe-8f4c-b569219cf6e7">

**Comment by rebornix** [comment]
Let's merge it into https://github.com/microsoft/vscode/issues/186364
