### ISSUE TITLE
Bug : VSCode 1.80  |  Autocomplete not working

### ISSUE THREAD

**Issue by SaeidJavadi** [microsoft/vscode#187312]
Bug

I have problem after updating to 1.80
And none of the AUTOCOMPLETE work (tabnine , pylance, IntelliCode, ... )

- VS Code Version: 1.80.0
- OS Version: windows 10 x64

**Comment by justinianoleo** [comment]
I'm having the same issue, Everything were working perfect before the update to 1.8 version.

**Comment by Blainetang** [comment]
Me too

**Comment by DifficultNick** [comment]
I have noticed that client side of my extension stopped sending autocomplete request to the server side. So `connection.onCompletion` stops being invoked. This happens after 5 minutes of working in text editor, and there is no errors in debug console. So I cant understand what cause this problem. But previous versions of VSCode (before 1.80) don't have this problem.
Hope this will help, thank you!

**Comment by jrieken** [comment]
> I have noticed that client side of my extension stopped sending autocomplete request to the server side.

Do you get any other requests to your server? Also what extension/language is this?

**Comment by DifficultNick** [comment]
@jrieken, yes other requests work well (for example `connection.onHover` and others). This is my extension for custom language. ([here is the repo](https://github.com/tiburon-research/vsc-xml-plugin) if needed)

**Comment by jrieken** [comment]
Interesting. And this happens for all completion requests or just for those that are explicitly triggered (ctrl+space) or those that are made while you type?

Also, is there anything in the error logs or dev tools console?

**Comment by DifficultNick** [comment]
This happens for all completion requests and I haven't found any errors neither in dev tools console nor in any output channel nor in debug console. Explicitly triggered completion requests return snippets (from json files), but not completions that computed on server

**Comment by justinianoleo** [comment]
¿How can we solve the problem? I uninstalled and installed VS, but the big is still here.

**Comment by DifficultNick** [comment]
> Is this for all files or just some languages? When this happens does this only affect your tib language or also completions in other files like TS/JS or CSS?

When it's broken in my extension other languages complitions still works

**Comment by jrieken** [comment]
This is very likely the same as https://github.com/microsoft/vscode/issues/187642

@DifficultNick can you confirm/check if you are using snippet choice when this bug happens?

**Comment by DifficultNick** [comment]
looks like it's not related to snippets. I could not find a sequence of steps to reproduce the problem with my extension =(
Every time I write the same text, I get the same list of autocompletions, and at one moment it stops working.
Though adding new snippet for my language (via user snippets json) always leads to this problem.

**Comment by ThFriedrich** [comment]
I am also experiencing issues with Autocomplete. My [language extension](https://github.com/ThFriedrich/lammps_vscode) uses SnippetStrings in the CompletionItemProvider. Debugging the extension I noticed everything works fine, but once a "choice" item was used in a SnippetString it breaks the CompletionItemProvider (One can still make the choice and tab through as usual this one time). There is no errors thrown, the rest of the extension keeps working fine (Hover, Webviews, etc.). I tested different vscode version and everything still seems fine in 1.79. 

Further info:
<details><summary>Details</summary>
<p>

Version: 1.80.0
Commit: 660393deaaa6d1996740ff4880f1bad43768c814
Date: 2023-07-04T13:39:48.236Z
Electron: 22.3.14
ElectronBuildId: 21893604
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Linux x64 5.15.0-75-generic

</p>
</details>

**Comment by starball5** [comment]
Possibly related: https://github.com/redhat-developer/vscode-java/issues/3194

**Comment by SaeidJavadi** [comment]
@VSCodeTriageBot 

Type: <b>Bug vscode 1.81</b>

> Issue troubleshooting has identified that the issue is with Visual Studio Code. 

VS Code version: Code 1.80.1 (74f6148eb9ea00507ec113ec51c489d6ffb4b771, 2023-07-12T17:22:07.651Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Celeron(R) CPU  N2840  @ 2.16GHz (2 x 2167)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: disabled_off<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: unavailable_off<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|7.89GB (3.34GB free)|
|Process Argv|--crash-reporter-id c634184b-d5ea-44cf-9764-7a76ac4d5cdb|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263cf:30335440
vscorecescf:30445987
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
py29gd2263:30789496
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
2e4cg342:30602488
pyind779:30671433
f6dab269:30613381
vscrp:30673768
pythonsymbol12:30671437
showlangstatbar:30737416
vsctsb:30748421
pythonms35:30701012
03d35959:30757346
pythonfmttext:30731395
pythoncmv:30756943
fixshowwlkth:30771522
showindicator:30785052
pythongtdpath:30769146
bgfeh915:30780428
pythonnosm12tcf:30779713
pythonidxpt:30784022
pythonnocebcf:30776496
e537b577:30786199
dsvsc013cf:30789518

```

</details>
