### ISSUE TITLE
Dragging a tab can show visual glitch when tab not fully visible

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#18733]
* use tabs, open many such that it shows a scrollbar
* scroll all the way to the right
* move the last tab around

<img width="1280" alt="screen shot 2017-01-18 at 14 07 44" src="https://cloud.githubusercontent.com/assets/1794099/22065269/c25e5316-dd87-11e6-9a45-99539f58eb70.png">

**Comment by bpasero** [comment]
Interesting, looks like an issue with how Chrome decides to come up with a drag image.
