### ISSUE TITLE
Add Tab Icons for open file tabs across the top

### ISSUE THREAD

**Issue by tonym99** [Microsoft/vscode#18738]
Add Tab Icons for open file tabs across the top of the IDE instead of just plain text.  This makes it easer to identify which files and file types you want to work on.  There are several other IDEs that allow for text only, text w small icons, and text with large icons as options for the tabs.

Below is a screen shot snippet from Coda and its use of text w small icons as reference.

Thanks!!

![screenshot_218](https://cloud.githubusercontent.com/assets/24207880/22068983/c5da4e8c-dd64-11e6-8bb7-3216a7e0e21d.png)

**Comment by bpasero** [comment]
Landed a long time ago.
