### ISSUE TITLE
Format specifiers in strings are syntax-highlighted even when not involved in a format

### ISSUE THREAD

**Issue by mcrumiller** [microsoft/vscode#187319]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: latest
- OS Version: Windows

Steps to Reproduce:

1. Create a variable with a string containing a format specifier:
    ```python
    s = "hi there %0.4f see how it's highlighted?"
    ```
3. Observe syntax highlighting on the `%0.4f`:  
    
    ![image](https://github.com/microsoft/vscode/assets/1896992/90db4e32-9ddd-4848-a05b-56b0bb213ad1)

**Comment by aeschli** [comment]
Which language?

**Comment by mcrumiller** [comment]
Ahh sorry--this is in Python.

**Comment by aeschli** [comment]
We use the grammar from https://github.com/MagicStack/MagicPython. Can you file the issue there?

Maybe this is a duplicate of https://github.com/MagicStack/MagicPython/issues/243

**Comment by mcrumiller** [comment]
Hi @aeschli, this does indeed look like a duplicate of that issue. You can close here. That issue was posted in 2021 and hasn't been resolved though, so I'm not holding my breath.

Thanks for the guidance.
