### ISSUE TITLE
Get parsed launch.json or parse it in the extension

### ISSUE THREAD

**Issue by dennisfrostlander** [Microsoft/vscode#18736]
- VSCode Version: 1.8.0
- OS Version: Any

In my extension I need to access information from the launch.json file in code. I did not find any related services exposed in typescript definitions.

Is it possible to get parsed launch.json content in the extension code? 
If not, it it possible to invoke the built-in VSCode json parser to parse the contents myself?

**Comment by isidorn** [comment]
Try `vscode.workspace.getConfiguration('launch)'`
https://github.com/Microsoft/vscode/blob/master/src/vs/vscode.d.ts#L4008
