### ISSUE TITLE
Error while commiting not surfaced to user and commit simply ignored

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#18741]
- VSCode Version: insiders
- OS Version: os x

Steps to Reproduce:

1. Open vscode repo, make some change which is not with aligned with our rules (use spaces instead of tabs)
2. try to commit that change via git viewlet
3. no error is surfaced and the commit is simply ignored
4. I would expect that a notification is shown that I have been formating as in vscode stable

**Comment by joaomoreno** [comment]
#18655
