### ISSUE TITLE
Commit button is lost

### ISSUE THREAD

**Issue by valdirviana** [Microsoft/vscode#18749]
- VSCode Version: Code - Insiders 1.9.0-insider (39d761bf1f4ce7ea605539bdba41a8727b3c7ce0, 2017-01-18T07:10:04.990Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

|Extension|Author|Version|
|---|---|---|
|html-snippets|abusaidm|0.0.18|
|vscode-theme-onedark|akamud|0.3.0|
|vscode-icontheme-nomo-dark|be5invis|1.2.5|
|path-intellisense|christian-kohler|1.2.0|
|tslint|eg2|0.8.1|
|Angular2|johnpapa|1.0.2|
|vscode-attrs-sorter|mrmlnc|2.0.0|
|vscode-jade-snippets|mrmlnc|1.0.1|
|vscode-puglint|mrmlnc|2.3.0|
|csharp|ms-vscode|1.6.2|
|debugger-for-chrome|msjsdiag|2.4.2|
|material-icon-theme|PKief|1.2.0|
|seti-icons|qinjia|0.1.3|
|vscode-icons|robertohuertasm|7.0.1|
|stylelint|shinnn|0.21.2|
|guides|spywhere|0.6.1|
|cordova-tools|vsmobile|1.2.6|
|bootstrap-3-snippets|wcwhitehead|0.0.9|
|Material-theme|zhuangtongfa|1.0.3|

---

Steps to Reproduce:

1.
2.
![image](https://cloud.githubusercontent.com/assets/5238402/22077793/ce4fbc40-dd9c-11e6-98d9-68730a2128ae.png)

**Comment by nicholasgonzalezsc** [comment]
I'm seeing this as well. It is also showing everything as an addition, and doesn't show a diff

**Comment by JimiC** [comment]
Confirmed.

**Comment by joaomoreno** [comment]
672315c0731f6845a5ba58c61a557966f67ecadf
