### ISSUE TITLE
Add option to disable bracket matching

### ISSUE THREAD

**Issue by thuyettiensinh** [Microsoft/vscode#18745]
- VSCode Version: 1.8.1
![untitled](https://cloud.githubusercontent.com/assets/21211244/22076046/0e3c685a-dde1-11e6-9b8b-7bbfb3f93491.png)

HTML tag highlight when i active !
How to disable them ???
plz help me !

**Comment by Gama11** [comment]
Duplicate? #16424

**Comment by mjbvz** [comment]
Thanks @Gama11! Closing as a duplicate of #16424

**Comment by thuyettiensinh** [comment]
tks all !
