### ISSUE TITLE
Get listed on the JSON Schema website as a compatible editor

### ISSUE THREAD

**Issue by fulldecent** [Microsoft/vscode#18744]
I learned that VSCode supports auto completion of JSON files by using JSON schema.

> Source: http://schemastore.org/json/

However, you probably want to get listed on this page (that the above links to) for wider exposure.

> http://json-schema.org/implementations.html

You can edit the file here:

> https://github.com/json-schema-org/json-schema-org.github.io/blob/master/implementations.html

**Comment by fulldecent** [comment]
Related https://github.com/json-schema-org/json-schema-org.github.io/issues/13

**Comment by aeschli** [comment]
I created https://github.com/json-schema-org/json-schema-org.github.io/pull/72
