### ISSUE TITLE
Wrong position of Codelens references in CSS 

### ISSUE THREAD

**Issue by mraveux** [microsoft/vscode#187439]
Type: <b>Bug</b>

The "x references" line is misplaced in CSS when a list of selector are targeted. It will display it right above the last selector thus kinda breaking the layout and not allowing to properly track references to the other selectors.
<img width="231" alt="Screenshot 2023-07-10 at 12 34 07" src="https://github.com/microsoft/vscode/assets/7260891/467f0e8f-f982-440b-93dd-b4418b09a649">

The issue is not visually disturbing if you put the selectors on one line, but I think this case should be handled properly for multi-line.

If there is multiple selectors stacked on top of each other like in the screenshot it should either show the reference of each above each, or (and i would prefer this way) show all the references above the stack of selectors thus not breaking the CSS block.

VS Code version: Code - Insiders 1.80.0-insider (Universal) (61ba389b0a7108af0411c73ab30c7e4350051645, 2023-06-16T09:51:41.757Z)
OS version: Darwin arm64 22.3.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Max (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|2, 3, 3|
|Memory (System)|32.00GB (3.49GB free)|
|Process Argv|--crash-reporter-id 2d1b9b68-3bf5-4d8a-b2e9-119ac32ba0a9|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-tailwindcss|bra|0.9.11
path-intellisense|chr|2.8.4
gitlens|eam|14.0.1
copilot|Git|1.95.246
copilot-chat|Git|0.3.2023070701
vscode-icons|vsc|12.4.0
volar|Vue|1.8.4
vscode-typescript-vue-plugin|Vue|1.8.4

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythontb:30258533
pythonptprofiler:30281269
vshan820:30294714
vscod805cf:30301675
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30404738
py29gd2263:30784851
vsclangdf:30492506
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30618038
pylantcb52:30590116
pyind779:30611226
pythonsymbol12:30651887
a9j8j154:30646983
showlangstatbar:30737417
pythonms35:30671666
24365598:30687740
pythonfmttext:30716741
pythoncmvfstr:30726892
fixshowwlkth:30771523
showindicator:30766888
pythongtdpath:30726887
i26e3531:30780429
gsofb:30778559
pythonnosmt12:30779711
pythonidxpt:30768918
pythondjangots:30768917
pythonnoceb:30776497
copilotsettingc:30767685
e537b577:30772214
h0f32768:30779712
asynctok:30783811
dsvsc013:30777762
dsvsc014:30777825
diffeditorv2:30786206

```

</details>

**Comment by aeschli** [comment]
The built-in css extension does not provide code lenses. I think `volar` is doing that.
Please file the issue there.
