### ISSUE TITLE
Add keyboard shortcuts 'Hide #{name panel}' and etc

### ISSUE THREAD

**Issue by maxdzyubak** [microsoft/vscode#187426]
Hello. Please add keyboard shortcuts on
1. 'Hide outline panel'
2. 'Resize outline panel'
3. 'Maximized outline panel'
4. 'Hide Open editors'
5. 'Hide source control'
6. 'Resized source control'
7. 'Maximized source control'
8. 'Hide timeline panel'
9. 'Resized timeline panel'
10. 'Hide hidden items'
11. 'Resized hidden items'

All features in screenshots:
[capture.dropbox.com/643eKtJHvyPTmOst](https://capture.dropbox.com/643eKtJHvyPTmOst)

Thank you

**Comment by sbatten** [comment]
Thanks for taking time to file an issue. However, we have 1 GH issue to 1 product issue guidance which this item has many requests. Looking at this list however, many of these can be bound to keybindings yourself in the keybindings editor.
