### ISSUE TITLE
My settings editor.tabSize: 2, doesn't work

### ISSUE THREAD

**Issue by andela-mmichael** [Microsoft/vscode#18748]
I don't know if this is a bug or not. My settings for indenting i.e. `editorTabSize: 2` doesn't take effect. After saving, it always revert to 4 spaces. This is getting me frustrated because it makes me have so many changes when committing to github

---

- VSCode Version: Code 1.8.1 (ee428b0eead68bf0fb99ab5fdc4439be227b6281, 2016-12-19T14:42:49.304Z)
- OS Version: Darwin x64 16.3.0
- Extensions:

|Extension|Author|Version|
|---|---|---|
|vscode-generate-getter-setter|DSKWRK|0.4.1|
|EditorConfig|EditorConfig|0.3.4|
|beautify|HookyQR|0.7.3|
|code-settings-sync|Shan|2.4.2|
|html-css-class-completion|Zignd|1.0.3|
|html-snippets|abusaidm|0.0.18|
|vscode-javascript-snippet-pack|akamud|0.1.5|
|vscode-eslint|dbaeumer|1.2.2|
|githistory|donjayamanne|0.1.5|
|python|donjayamanne|0.5.6|
|vscode-babel-coloring|dzannotti|0.0.4|
|vscode-html-css|ecmel|0.0.32|
|tslint|eg2|0.8.1|
|vscode-npm-script|eg2|0.1.8|
|vscode-angular2-emmet|jakethashi|1.0.10|
|Angular1|johnpapa|0.1.16|
|Angular2|johnpapa|1.0.2|
|vscode-JS-CSS-HTML-formatter|lonefy|0.2.2|
|prettify-json|mohsen1|0.0.3|
|PowerShell|ms-vscode|0.8.0|
|team|ms-vsts|1.108.0|
|debugger-for-chrome|msjsdiag|2.4.2|
|color-highlight|naumovs|1.3.0|
|seti-icons|qinjia|0.1.3|
|vscode-icons|robertohuertasm|7.0.1|
|sass-indented|robinbentley|1.3.0|
|Spell|seanmcbreen|0.9.1|
|bootstrap-3-snippets|wcwhitehead|0.0.9|
|JavaScriptSnippets|xabikos|1.2.0|
|ReactSnippets|xabikos|1.2.0|

**Comment by rebornix** [comment]
@andela-mmichael do you have any project level setting (which should be in your `.vscode` folder) that changes the tabSize setting somehow? Do you have this issue even if you run VS Code without any extension enabled?

**Comment by andela-mmichael** [comment]
I don't have any project level settings in my`.vscode` folder. The `settings.json` file is empty. 

However, everything works fine when I disabled all my extension.


Further troubleshooting indicates that one of my extension `vscode JS-CSS-HTML Formatter` was over-riding my default indentation style. Removing this extension fixed the issue.
