### ISSUE TITLE
Memory leak in tests: sinon.stub() without sinon.restore()

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#187471]
In short, if you use `sinon.stub()` without calling `sinon.restore()` you are leaking memory.

See https://github.com/sinonjs/sinon/issues/1866 for the details.

I'm seeing a lot of memory used in unit tests and it appears to be coming from sinon. This may be contributing to our unit test OOM issue on Windows 32 bit. Let's see if fixing this lets us run the unit tests again.

- [x] [instantionServiceMock.ts](https://github.com/microsoft/vscode/blob/8c8e8600b6ec20279e2fa977ff242d0238f486c0/src/vs/platform/instantiation/test/common/instantiationServiceMock.ts#L64) @alexr00 
- [x] [telemetryService.tst.ts](https://github.com/microsoft/vscode/blob/8c8e8600b6ec20279e2fa977ff242d0238f486c0/src/vs/platform/telemetry/test/browser/telemetryService.test.ts) @lramos15 
- [x] [extHostTesting.test.ts](https://github.com/microsoft/vscode/blob/8c8e8600b6ec20279e2fa977ff242d0238f486c0/src/vs/workbench/api/test/browser/extHostTesting.test.ts) @connor4312 
- [x] [searchModel.test.ts](https://github.com/microsoft/vscode/blob/8c8e8600b6ec20279e2fa977ff242d0238f486c0/src/vs/workbench/contrib/search/test/browser/searchModel.test.ts) @andreamah 
- [x] [searchResult.test.ts](https://github.com/microsoft/vscode/blob/8c8e8600b6ec20279e2fa977ff242d0238f486c0/src/vs/workbench/contrib/search/test/browser/searchResult.test.ts#L231-L232) @andreamah 
- [x] [configurationEditing.test.ts](https://github.com/microsoft/vscode/blob/8c8e8600b6ec20279e2fa977ff242d0238f486c0/src/vs/workbench/services/configuration/test/browser/configurationEditing.test.ts#L195-L196) @sandy081 

To fix `instatiationServiceMock.ts` I have made `TestInstantiationService` disposable, and there were some places where tests failed or the refactor seemed larger:

- [x] [installGalleryExtensionTask.test.ts](https://github.com/microsoft/vscode/blob/8c8e8600b6ec20279e2fa977ff242d0238f486c0/src/vs/platform/extensionManagement/test/node/installGalleryExtensionTask.test.ts) @sandy081 
- [x] [userDataSyncClient.ts](https://github.com/microsoft/vscode/blob/8c8e8600b6ec20279e2fa977ff242d0238f486c0/src/vs/platform/userDataSync/test/common/userDataSyncClient.ts) @sandy081 
- [x] [callStack.test.ts](https://github.com/microsoft/vscode/blob/8c8e8600b6ec20279e2fa977ff242d0238f486c0/src/vs/workbench/contrib/debug/test/browser/callStack.test.ts) @connor4312 
- [x] [editorGroupModel.test.ts](https://github.com/microsoft/vscode/blob/8c8e8600b6ec20279e2fa977ff242d0238f486c0/src/vs/workbench/test/browser/parts/editor/editorGroupModel.test.ts) @lramos15 
- [x] [browserKeyboardMapper.test.ts](https://github.com/microsoft/vscode/blob/8c8e8600b6ec20279e2fa977ff242d0238f486c0/src/vs/workbench/services/keybinding/test/browser/browserKeyboardMapper.test.ts) @rebornix 
- [x] [extensionsWorkbenchService.test.ts](https://github.com/microsoft/vscode/blob/8c8e8600b6ec20279e2fa977ff242d0238f486c0/src/vs/workbench/contrib/extensions/test/electron-sandbox/extensionsWorkbenchService.test.ts) @sandy081

**Comment by alexr00** [comment]
The biggest gain would be from fixing the leak from `instantionServiceMock.ts` as it is used _many_ places.

**Comment by alexr00** [comment]
@sandy081 I don't know if you own [instantionServiceMock.ts](https://github.com/microsoft/vscode/blob/8c8e8600b6ec20279e2fa977ff242d0238f486c0/src/vs/platform/instantiation/test/common/instantiationServiceMock.ts#L64), but I am looking into a fix for it since it will have the biggest impact.

**Comment by joaomoreno** [comment]
@lramos15 Reopened this.

**Comment by lramos15** [comment]
> @lramos15, I've reopened this.

Thanks. I should be careful to not do `Fixes X` and instead `Part of X` as that will prevent GitHub from auto closing it

**Comment by alexr00** [comment]
With https://github.com/microsoft/vscode/pull/187482, I have made `TestInstantiationService` disposable and handled disposing it in most tests. There are several places where the way to handle this isn't clear. I have added them in the issue above.

**Comment by andreamah** [comment]
@alexr00 the instance in `searchResult.test.ts` is already restored at https://github.com/microsoft/vscode/blob/fd63cf62b94bbfecb21fe4cb6006a7d6c04a5c96/src/vs/workbench/contrib/search/test/browser/searchResult.test.ts#L266, but the others _should_ be fixed in https://github.com/microsoft/vscode/pull/187489. Let me know if I miss any!

**Comment by sandy081** [comment]
@alexr00 For those tests where I am just using `TestInstantiationService`, should I have to still call `sinon.restore()` or I should wait for your change to dispose the `TestInstantiationService` ?

**Comment by alexr00** [comment]
You can wait for my change to dispose the `TestInstantiationService`.

**Comment by alexr00** [comment]
@lramos15 and @rebornix the only files left are yours. The `TestInstantiationService` is now disposable and should be disposed in these test files to properly restore `sinon` and prevent a memory leak.

**Comment by alexr00** [comment]
👏 Thank you for the fast response everyone!

**Comment by m-benmaan** [comment]
> In short, if you use `sinon.stub()` without calling `sinon.restore()` you are leaking memory.
> 
> See [sinonjs/sinon#1866](https://github.com/sinonjs/sinon/issues/1866) for the details.
> 
> I'm seeing a lot of memory used in unit tests and it appears to be coming from sinon. This may be contributing to our unit test OOM issue on Windows 32 bit. Let's see if fixing this lets us run the unit tests again.
> 
> * [x]  [instantionServiceMock.ts](https://github.com/microsoft/vscode/blob/8c8e8600b6ec20279e2fa977ff242d0238f486c0/src/vs/platform/instantiation/test/common/instantiationServiceMock.ts#L64) @alexr00
> * [x]  [telemetryService.tst.ts](https://github.com/microsoft/vscode/blob/8c8e8600b6ec20279e2fa977ff242d0238f486c0/src/vs/platform/telemetry/test/browser/telemetryService.test.ts) @lramos15
> * [x]  [extHostTesting.test.ts](https://github.com/microsoft/vscode/blob/8c8e8600b6ec20279e2fa977ff242d0238f486c0/src/vs/workbench/api/test/browser/extHostTesting.test.ts) @connor4312
> * [x]  [searchModel.test.ts](https://github.com/microsoft/vscode/blob/8c8e8600b6ec20279e2fa977ff242d0238f486c0/src/vs/workbench/contrib/search/test/browser/searchModel.test.ts) @andreamah
> * [x]  [searchResult.test.ts](https://github.com/microsoft/vscode/blob/8c8e8600b6ec20279e2fa977ff242d0238f486c0/src/vs/workbench/contrib/search/test/browser/searchResult.test.ts#L231-L232) @andreamah
> * [x]  [configurationEditing.test.ts](https://github.com/microsoft/vscode/blob/8c8e8600b6ec20279e2fa977ff242d0238f486c0/src/vs/workbench/services/configuration/test/browser/configurationEditing.test.ts#L195-L196) @sandy081
> 
> To fix `instatiationServiceMock.ts` I have made `TestInstantiationService` disposable, and there were some places where tests failed or the refactor seemed larger:
> 
> * [x]  [installGalleryExtensionTask.test.ts](https://github.com/microsoft/vscode/blob/8c8e8600b6ec20279e2fa977ff242d0238f486c0/src/vs/platform/extensionManagement/test/node/installGalleryExtensionTask.test.ts) @sandy081
> * [x]  [userDataSyncClient.ts](https://github.com/microsoft/vscode/blob/8c8e8600b6ec20279e2fa977ff242d0238f486c0/src/vs/platform/userDataSync/test/common/userDataSyncClient.ts) @sandy081
> * [x]  [callStack.test.ts](https://github.com/microsoft/vscode/blob/8c8e8600b6ec20279e2fa977ff242d0238f486c0/src/vs/workbench/contrib/debug/test/browser/callStack.test.ts) @connor4312
> * [x]  [editorGroupModel.test.ts](https://github.com/microsoft/vscode/blob/8c8e8600b6ec20279e2fa977ff242d0238f486c0/src/vs/workbench/test/browser/parts/editor/editorGroupModel.test.ts) @lramos15
> * [x]  [browserKeyboardMapper.test.ts](https://github.com/microsoft/vscode/blob/8c8e8600b6ec20279e2fa977ff242d0238f486c0/src/vs/workbench/services/keybinding/test/browser/browserKeyboardMapper.test.ts) @rebornix
> * [x]  [extensionsWorkbenchService.test.ts](https://github.com/microsoft/vscode/blob/8c8e8600b6ec20279e2fa977ff242d0238f486c0/src/vs/workbench/contrib/extensions/test/electron-sandbox/extensionsWorkbenchService.test.ts) @sandy081

need help
