### ISSUE TITLE
Can't edit a file with very long line

### ISSUE THREAD

**Issue by ccimage** [Microsoft/vscode#1874]
Eg.  a javascript file which is compressed.   When trying to type any letter, vscode changes into no response, while TextWrangler can do the editor job very well on this file. 
OS: mac osx10.11.2,   vscode:0.10.6,  file size: about 1.6M

**Comment by alexandrudima** [comment]
@ccimage Can you please share the file with me or point me to a similar file that reproduces the problem?

**Comment by alexandrudima** [comment]
Please reopen or file another issue with more information such that we can attempt to reproduce.
