### ISSUE TITLE
Unable to write file `../globalStorage/github.vscode-pull-request-github/temp/vscode/userIcons`

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode#187428]
1. Install GHPRI on a fresh VS Code install (new user data dir) on Windows
2. Create a PR
3. :bug: see the following error message
<img width="344" alt="image" src="https://github.com/microsoft/vscode-pull-request-github/assets/30305945/b401ff86-08ba-4aa4-95dc-7d23724824e8">

```
Unable to write file 'vscode-userdata:/c:/Users/huer/AppData/Roaming/Code - Insiders/User/globalStorage/github.vscode-pull-request-github/temp/vscode/userIcons/joyceerhl.jpg' (NoPermissions (FileSystemError): Error: EPERM: operation not permitted, rename 'c:\Users\huer\AppData\Roaming\Code - Insiders\User\globalStorage\github.vscode-pull-request-github\temp\vscode\userIcons\joyceerhl.jpg.vsctmp' -> 'c:\Users\huer\AppData\Roaming\Code - Insiders\User\globalStorage\github.vscode-pull-request-github\temp\vscode\userIcons\joyceerhl.jpg')
```

Filing this since there have been related bugs with vscode-userdata (e.g. code-insiders --install-extension doesn't work), maybe related  to https://github.com/microsoft/vscode/issues/180695

**Comment by sandy081** [comment]
@joyceerhl Would like to check if you are able to reproduce this consistently. I tried it in Mac and I cannot repro.

**Comment by joyceerhl** [comment]
I have not seen this recently

**Comment by sandy081** [comment]
Related / Duplicate

https://github.com/microsoft/vscode/issues/187245
