### ISSUE TITLE
Formatting on the fly to give Developer consistent formatting options across projects

### ISSUE THREAD

**Issue by sridmad** [Microsoft/vscode#18754]
- VSCode Version: 1.8.0
- OS Version: Windows 10

VS Code should allow switching between formatting on the fly. Let me describe the scenario and the behavior. 
* Project has preferred Formatting settings. All commits should follow these settings.
* User has preferred Formatting settings. As a developer I always want to use these settings while editing

When a developer works across source bases some of the formatting differences are glaring and should not have to worry about the different formats. Git already has the very basic formatting on the fly ability with respect to CRLF.

VS Code can take this all the way to help developer not have to worry about formatting.

* When VSCode loads a file, it applies the formatting settings of the user to the file.
* When VSCode saves the file, it applies the formatting setting of the Project to the file.

As a first step, VSCode Workspace formatting options are applied on save and VSCode User formatting options are applied on load and while editing.

**Comment by dbaeumer** [comment]
@jrieken FYI.

**Comment by jrieken** [comment]
This should be done as extension, indeed there already is the editorconfig-extension which covers these basic formattings
