### ISSUE TITLE
Command/keybinding to paste into editor without formatting

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode#187507]
In several applications you can use Ctrl+Shift+V to paste text without formatting. We already have that registered to `Markdown: Open Preview` unfortunately, but it would be great to introduce a dedicated command for the default paste handler that users could perhaps rebind to Ctrl+Shift+V for cases where there are multiple paste handlers and I know I just want the literal text on my clipboard.

**Comment by mjbvz** [comment]
Should mostly be possible using:

```
{
	"key": "cmd+shift+v",
	"command": "editor.action.pasteAs",
	"when": "editorTextFocus",
	"args": {
		"id": "text"
	}
}
```

But a dedicated command is a good idea

**Comment by jacobakkerboom** [comment]
> Should mostly be possible using:
> 
> ```
> {
> 	"key": "cmd+shift+v",
> 	"command": "editor.action.pasteAs",
> 	"when": "editorTextFocus",
> 	"args": {
> 		"id": "text"
> 	}
> }
> ```
> 
> But a dedicated command is a good idea

This keybinding doesn't seem to work, I get "command 'editor.action.pasteAs' not found" ( @mjbvz ).

I must say I find the settings confusing. It took me a long time before I realised that the setting "Editor: Format On Paste" was not the only one affecting this behaviour, but that there is also "Editor: Auto Indent" which "automatically adjusts the indentation when users paste". I hope at least something can be added (once again?) that makes a custom keybinding possible

**Comment by mjbvz** [comment]
@jacobakkerboom What VS Code version are you on?

**Comment by jacobakkerboom** [comment]
I'm on 1.77.1, which VS Code is telling me corresponds to "Date: 2023-04-04 (5 mos ago)". I guess maybe the behaviour your comment depends on was introduced in the meantime (I haven't given VS Code root privileges, so it can't auto update, I guess I forgot to update manually). If that's the case I'm looking forward to adding the shortcut :¬), thanks for your reply @mjbvz

**Comment by mjbvz** [comment]
Yes it was added in 1.79. Try updating and that command should then work
