### ISSUE TITLE
SCM doesn't ask to initiallize repos

### ISSUE THREAD

**Issue by bgashler1** [Microsoft/vscode#18753]
- VSCode Version: Insiders
- OS Version: macOS

Steps to Reproduce:

1. Open a folder that is not a Git repository (or under any other source control system)
2. Note that we no longer have a "Initialize Git Repository"

I feel like there should be a way to initialize version control for Git (and possibly whatever Git source control is available):

![initiallizerepo-2017-01-18-01-bg](https://cloud.githubusercontent.com/assets/11839736/22079310/35914d1a-dd70-11e6-8e31-1f3c1b583fcf.png)

**Comment by joaomoreno** [comment]
#18615
