### ISSUE TITLE
Vim Command Line

### ISSUE THREAD

**Issue by ImYuya** [microsoft/vscode#187530]
Type: <b>Feature Request</b>

In a recent update to VSCode Insiders, Vim Command Line was implemented. However, it is quite troublesome as it always requires changing to 'insert' when editing a file. Therefore, I believe it would be better without the Vim Command Line.

VS Code version: Code - Insiders 1.81.0-insider (Universal) (5150ef0ce77ef5516e55af4b8272f25907b55953, 2023-07-10T05:34:30.477Z)
OS version: Darwin arm64 22.5.0
Modes:

![スクリーンショット 2023-07-11 13 02 38](https://github.com/microsoft/vscode/assets/7827576/95b306ac-d408-4cdc-9900-71bb84ac575b)

**Comment by meganrogge** [comment]
pretty sure nothing has changed on our side related to vim - have you tried with all extensions disabled? a gif of before and after would help, thanks

**Comment by Tyriar** [comment]
You must have installed a vim extension as this isn't built in.
