### ISSUE TITLE
issue reporter authentication problems with github

### ISSUE THREAD

**Issue by RossBoylan** [microsoft/vscode#187532]
Type: <b>Bug</b>

I was unable to  use the "Preview on GitHub" button, and thus to submit a bug, before logging in to github independently.  I worked around it by logging in to github in my browser before hitting the Preview button.  Then I could submit the bug.

This may be a bit unclear without the specifics, which follow.
  1. Start VSCode, select Help |  Report an Issue
  2. Fill in the window that popped up, selecting Bug Report, filed on VSCode.
  3. Hit the "Preview on GitHub" button on the bottom right of that window.
  4. A new tab opened in my browser (FireFox) asking me to login to github.
  5. Filled in my account name (not an email address) and password and hit login.
  6. Immediately this moved me to a page saying I was unable to login because of authentication problems.  I don't recall the exact text.
  7. Shortly thereafter I got an email from github saying
    A sign in attempt requires further verification because we did not recognize your device. To complete the sign in, enter the verification code on the unrecognized device.    
    Device: Firefox on Windows
    Verification code: 199999
  but there was nowhere to enter that code.  The page did mention trying to refresh it, but that didn't help.
  8. I tried a fresh login, directly in the browser, to github using my account name and the verification code.  This failed too.

I tried several times, always with the same result.

Finally,
  9.  Login to github in the browser--not initiated from the Issue Reporter.
  10. This failed too, but it left me on a page for me to enter my verification code.
  11. Received another verification code by email and entered it in the form.
  12. This logged me in.
  13. Then I hit "Preview on GitHub" in the Issue Reporter window.  This created an issue in github and left me to finish the submission.  There was no login step at all.

One way of putting the problem is that when additional authentication is required the VSCode submission should leave you on a page for entry of the extra verification code, like step 10.  But it doesn't (step 6).

VS Code version: Code 1.80.0 (660393deaaa6d1996740ff4880f1bad43768c814, 2023-07-04T15:06:02.407Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10700 CPU @ 2.90GHz (16 x 2904)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.74GB (12.93GB free)|
|Process Argv|--crash-reporter-id 4f7bdb67-6d34-46d0-bf6e-0bea9483decf|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (17)</summary>

Extension|Author (truncated)|Version
---|---|---
markdown-checkbox|bie|0.4.0
data-workspace-vscode|ms-|0.5.0
mssql|ms-|1.19.1
sql-bindings-vscode|ms-|0.4.0
sql-database-projects-vscode|ms-|1.1.1
isort|ms-|2023.10.0
python|ms-|2023.12.0
vscode-pylance|ms-|2023.7.10
jupyter|ms-|2023.6.1001861915
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.17
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-slideshow|ms-|0.1.5
live-server|ms-|0.4.9
powershell|ms-|2023.6.0
markdown-preview-enhanced|shd|0.6.8
markdown-all-in-one|yzh|3.5.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
py29gd2263:30784847
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
vscccc:30610679
2e4cg342:30602488
pyind779:30671433
89544117:30613380
pythonsymbol12:30671437
showlangstatbar:30737416
vsctsb:30748421
pythonms35:30701012
03d35959:30757346
pythonfmttext:30731395
pythoncmvfstrcf:30756944
fixshowwlkth:30771522
hideindicator:30785051
pythongtdpath:30769146
i26e3531:30780429
pythonnosmt12:30779714
pythonidxpt:30784022
pythonnoceb:30776495
h7j2d465:30786200

```

</details>

**Comment by TylerLeonhardt** [comment]
This seems like it's a GitHub issue more than a VS Code issue... the issue here is that GitHub doesn't seem to handle 2FA well while you are trying to open an issue. I would recommend opening an issue on GitHub via GitHub Support: https://support.github.com/features/authentication

I'm not sure if this is the best link since I don't work at GitHub... but it seems like a good start.

**Comment by RossBoylan** [comment]
VS Code has an issue reporting flow that doesn't work in some cases.  To me, that's a VS Code issue; if github is broken in some way then VSCode needs at least a work-around, if only a message describing some other way to do it.

I know neither GitHub's API's nor how VSCode is using them.  Someone who does, and is confident that VSCode is using them properly, should submit a bug if appropriate.  That person is not me.
