### ISSUE TITLE
'tab' not working

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#187517]
This is driving me nuts today but I don't see anybody else who has mentioned it. Probably something to do with having both the suggest widget and inline suggestion visible.

- Press Tab to accept the suggestion
- Nothing happens

<img width="306" alt="image" src="https://github.com/microsoft/vscode/assets/323878/8b1cec28-669e-47d7-b093-e448e47a7d5c">

The log shows that `editor.action.inlineSuggest.commit` is being run

**Comment by hediet** [comment]
Fixed yesterday. Can you verify?
