### ISSUE TITLE
`/clear` sometimes re-inserts stale chat input editor contents

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode#187512]
I use `/clear` quite a lot and have noticed that sometimes earlier queries are restored after `/clear` runs. AFAICT it might be because when we run `clearChatSession`, the `IChatViewPane` restores the input value from the saved view state, which can be stale

**Comment by mjbvz** [comment]
Blocked on verifying by https://github.com/microsoft/vscode-copilot/issues/936

**Comment by joyceerhl** [comment]
@mjbvz you can work around that issue by manually typing /clear into the input box, that issue only applies to when /clear is selected from the suggest widget
