### ISSUE TITLE
Test Explorer shows old/wrong results results and does not reflect changes in tests

### ISSUE THREAD

**Issue by xtaje** [microsoft/vscode#187510]
Type: <b>Bug</b>

Test explorer may show old results when the test setup fails. To reproduce, first, create a test file and use pytest, like this:
```
def setup_module(module):
    #assert False
    pass

def test_add():
    assert 1+2 == 3
```
Run it using the Test Explorer and it should work as expected.

Next, edit the test so that it looks like this:
```
def setup_module(module):
    assert False
    pass

def test_add():
    assert 1+2 == 4
```
Run in the test explorer. The test explorer window on the left will update to show it's running, then report the test as passing (the last test result). There is no indication that the `setup_module` step failed.

If you look at the bottom window, no information is displayed in "Output". The only clue that anything went wrong is if you look at the "Test Results" window and notice that the last run in the run history did not complete.

If you run the test in debug mode, the behavior is the same, except that it will print a debug trace in "Debug Console" showing the error.

This is very surprising, since I expect the Test Explorer to always show the state of the last test run. This makes it hard to trust vscode.

VS Code version: Code 1.80.0 (660393deaaa6d1996740ff4880f1bad43768c814, 2023-07-04T13:39:33.766Z)
OS version: Darwin x64 22.1.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|2, 3, 3|
|Memory (System)|16.00GB (0.02GB free)|
|Process Argv|--crash-reporter-id 70b76804-fac2-4ccd-a6c8-bb476d9cd50f|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (36)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-ndjson|adr|0.100.0
asciidoctor-vscode|asc|2.9.8
prettier-vscode|esb|9.19.0
go|gol|0.39.0
vscode-test-explorer|hbe|2.21.1
vscode-docker|ms-|1.25.2
vscode-kubernetes-tools|ms-|1.3.13
black-formatter|ms-|2023.4.0
isort|ms-|2023.10.0
python|ms-|2023.12.0
vscode-pylance|ms-|2023.7.10
jupyter|ms-|2023.6.1001861915
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.17
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-slideshow|ms-|0.1.5
remote-containers|ms-|0.299.0
remote-ssh|ms-|0.102.0
remote-ssh-edit|ms-|0.86.0
remote-wsl|ms-|0.80.2
vscode-remote-extensionpack|ms-|0.24.0
remote-explorer|ms-|0.4.1
remote-server|ms-|1.2.1
test-adapter-converter|ms-|0.1.8
java|red|1.20.0
vscode-yaml|red|1.13.0
intellicode-api-usage-examples|Vis|0.2.7
vscodeintellicode|Vis|1.2.30
vscode-java-debug|vsc|0.52.0
vscode-java-dependency|vsc|0.23.0
vscode-java-pack|vsc|0.25.12
vscode-java-test|vsc|0.39.0
vscode-maven|vsc|0.41.0
vim|vsc|1.25.2
jinja|who|0.0.8
json|Zai|2.0.2

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263cf:30335440
vscorecescf:30445987
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
py29gd2263:30784847
vscaac:30438847
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
3biah626:30602489
pyind779:30671433
89544117:30613380
pythonsymbol12:30671437
a9j8j154:30646983
showlangstatbar:30737416
vsctsb:30748421
pythonms35:30701012
03d35959:30757346
pythonfmttext:30731395
pythoncmvfstrcf:30756944
fixshowwlkth:30771522
showindicator:30785052
pythongtdpath:30769146
i26e3531:30780429
pythonnosm12tcf:30779713
pythonidxpt:30784022
pythonnoceb:30776495
h7j2d465:30786200

```

</details>

**Comment by connor4312** [comment]
https://github.com/microsoft/vscode-python/issues/21579
