### ISSUE TITLE
JSX components have identical color as standard HTML tags.

### ISSUE THREAD

**Issue by tannerlinsley** [Microsoft/vscode#18752]
<img width="406" alt="screen shot 2017-01-18 at 12 11 36 pm" src="https://cloud.githubusercontent.com/assets/5580297/22078988/675a7734-dd77-11e6-8a9f-d3617f495029.png">

This is no so in Atom (which is honestly the last thing keeping me from moving all the way to vscode):
![screen shot 2017-01-18 at 12 13 50 pm](https://cloud.githubusercontent.com/assets/5580297/22079010/823ed78e-dd77-11e6-84d8-f144930c4cfa.png)

It doesn't seem to be fixed by using any theme, or installing the https://github.com/dzannotti/vscode-babel extension.

Any ideas?

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript-TmLanguage#415
