### ISSUE TITLE
Toggle Tab Key Moves Focus Stuck

### ISSUE THREAD

**Issue by nonsciencemark** [microsoft/vscode#187547]
Type: <b>Bug</b>

On two different computers I have accidentally seemingly pressed the shortcut for "Toggle Tab Key Moves Focus" and it is impossible to turn off. If I press the shortcut again, I can see that it "turns off" because the accessibility window in the bottom right where it says "Tab Moves Focus" disappears but the effects remain, and any time I press tab in editor it switches to a different window instead of inserting a tab.

VS Code version: Code 1.80.0 (660393deaaa6d1996740ff4880f1bad43768c814, 2023-07-04T15:06:02.407Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 2700X Eight-Core Processor          (16 x 3693)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.91GB (23.47GB free)|
|Process Argv|--crash-reporter-id 1e4235de-a239-4eb2-839e-73fc669626a5|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (27)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-javascript-repl|ach|0.7.4
jsoncrack-vscode|Ayk|1.0.8
speech|bie|0.1.0
compare-view|che|0.13.0
markdown-julia|col|0.0.1
vscode-markdownlint|Dav|0.51.0
vscode-dimmer|hoo|2.1.0
latex-workshop|Jam|9.12.3
language-julia|jul|1.47.2
octaveexecution|Luc|0.7.3
vscode-latex|mat|1.2.0
zotero|mbl|0.1.10
jupyter|ms-|2023.6.1001861915
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.17
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-slideshow|ms-|0.1.5
remote-wsl|ms-|0.80.2
wordcount|ms-|0.1.0
quarto|qua|1.89.0
r|REd|2.8.1
LiveServer|rit|5.7.9
vscode-julia-formatter|sin|0.6.3
rmarkdown|Tia|0.0.14
octave|toa|0.0.3
JavaScriptSnippets|xab|1.8.0
markdown-all-in-one|yzh|3.5.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
2e4cg342:30602488
pyind779:30671433
f6dab269:30613381
pythonsymbol12:30671437
a9j8j154:30646983
showlangstatbar:30737416
vsctsb:30748421
pythonms35:30701012
03d35959:30757346
pythonfmttext:30731395
pythoncmvfstrcf:30756944
fixshowwlkth:30771522
hideindicator:30785051
pythongtdpath:30769146
bgfeh915:30780428
pythonnosmt12:30779714
pythonidxpt:30784022
pythonnocebcf:30776496
e537b577:30786199

```

</details>

**Comment by meganrogge** [comment]
Reloading the window doesn't help? have you tried disabling all extensions?

**Comment by nonsciencemark** [comment]
I tried restarting but it didn't fix anything. I disabled all the extensions that I was actively using at the time (some may have remained enabled in the background, I'm not sure). 

On the second computer that this problem appeared on, I happened to have a markdown tab open and pressing tab seemed to still work within a Markdown script. So repeatedly pressing tab would cycle through open windows until it found one that was in Markdown, then stayed there and made tabs like expected. Markdown All in One plugin doesn't seem to have any settings related to the tab key, though.

I uninstalled VSCode and switched to the VSCode Insiders and have deactivated the keyboard shortcut. The problems have not resurfaced so far but I have a lot on my plate at the moment so I'm not willing to spend time deliberately breaking my VSCode to recreate the issue, sorry. 

Will update with more info if I accidentally do it again !

**Comment by ics90** [comment]
I've had the same problem! 
It occurred after upgrade vscode to  1.80.0 (Universal) on my macOS 13.4
Meanwhile, the store and debug button on left bar  always shows the clock icon  connecting to server

**Comment by meganrogge** [comment]
and you are encountering this with all extensions disabled? if so, can you run the toggle keyboard shortcuts troubleshooting command, use the keyboard shortcut to toggle tab key moves focus, and share the output?

**Comment by nonsciencemark** [comment]
I once again pressed the hotkey accidentally but because I'm now using VSCode Insider, the problem isn't persisting, so I guess this means that in future releases this won't be an issue?
