### ISSUE TITLE
Integrated terminal doesn't seem to be working at all

### ISSUE THREAD

**Issue by rafaelrinaldi** [Microsoft/vscode#18750]
- VSCode Version: 1.8.1
- OS Version: macOS Sierra 10.12.2
- [List of all my extensions](https://cloud.githubusercontent.com/assets/87162/22077911/23391350-dd84-11e6-9140-ef735ea736af.png)

Steps to Reproduce:

1. Open vscode
2. Hit `⌘⇧P`, search for "toggle terminal", hit enter
3. Prompt and input is fine on the integrated terminal, but I don't get any output at all

![kapture 2017-01-18 at 13 33 14](https://cloud.githubusercontent.com/assets/87162/22077884/04a133f0-dd84-11e6-8140-9ee5909c9bc4.gif)

I've tried both `fish` (which is the terminal I use daily) and `bash` without success.

Help?

**Comment by Tyriar** [comment]
Hmm, it looks like somehow your terminal is being sized to 1 row, do you have anything in your settings.json?

**Comment by rafaelrinaldi** [comment]
@Tyriar These are the only settings I have right now (project-specific):

```json
{
	"eslint.enable": true,
	"javascript.validate.enable": false
}
```

**Comment by Tyriar** [comment]
@rafaelrinaldi could you check the dev tools console (Help > Toggle Developer Tools) for errors as well as inspecting the panel? I'm particularly interested in the DOM structure of `.xterm-rows` (and its children) which should wrap the element containing the prompt.
