### ISSUE TITLE
when inline chat accessibility verbosity is disabled, don't include message about how to navigate to proposed changes

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#187594]
cc @rperez030

**Comment by joyceerhl** [comment]
I don't hear any messages about navigating to proposed changes, what are some steps to trigger this? I have not changed any default accessibility or inline chat settings

**Comment by meganrogge** [comment]
Sorry this was unclear

Make a mistake in an code editor. Use `fix with copilot`. Verify that you don't hear "navigate to the diff editor to review proposed changes" when verbosity is disabled. You should hear this when verbosity is enabled.
