### ISSUE TITLE
Hard crash (of everything) when debugging nodejs

### ISSUE THREAD

**Issue by chadbr** [Microsoft/vscode#18758]
- VSCode Version: Version 1.8.1 (1.8.1) - ee428b0eead68bf0fb99ab5fdc4439be227b6281 - 2016-12-19T14:40:36.266Z
- OS Version: macos 10.12.2
- Nodejs version: v6.7.0

Steps to Reproduce:

1. open code in empty folder
2. create an app.js with 2 console.writeline() functions
3. set breakpoints
4. go to debug pane, accept default setup
5. press f5 or debug button
6. when breakpoint is hit, press the stop button

On my colleges machine, vscode crashes. On my machine *everything* crashes (the shell, all applications, everything...) then the shell restarts.

repo gif attached... you don't see the crash because the app recording the gif gets killed...
![crashanim](https://cloud.githubusercontent.com/assets/3179452/22083145/65f62ffa-dd90-11e6-99cd-0193b4304e42.gif)

Anyone else???

**Comment by isidorn** [comment]
@chadbr I can not reproduce this behavior.

1. Do you see this all the time
2. Do you only see this when debugging Javascript or for all languages
3. Do you also see this when you disable all extensions in vscode
4. Do you see this with VSCode insiders also

ping @weinand for ideas

**Comment by chadbr** [comment]
@isidorn 

1) yes, every time.

for my colleague - this just started. He asked me to try to see if I had the same issues. 

He rolled back to the previous version of vscode and had the same result.

I haven't debugged any node code in a while -- so I'm not sure when it started on my machine.

2) only nodejs AFAIK. I debugged both .net core & angular2 tests very recently with no issues.

3) I'll try this today...

4) Same results with the insiders build.

**Comment by isidorn** [comment]
@weinand might it be that node-debug somehow terminates vscode by accident

@chadbr since this seems to be happening for your celleague and you (nobody else complained) can you distill what do those two machines have in come. Same node version? Same os version? Something special

**Comment by chadbr** [comment]
@isidorn @weinand 

Tried #3 - disabled all plugins - didn't help.

I don't have anything special going on -- typical mac dev box with 500 apps on it :)

I'm happy to let you remote in? or is there some telemetry I can enable or?

**Comment by chadbr** [comment]
could uninstalling / reinstalling potentially help? any instructions for "cleaning code" from a machine?

I hope to get this working soon - I use code all day every day!

**Comment by weinand** [comment]
Cannot reproduce either.
`console` does not have a function `writeline()`, but this doesn't explain the issue you are seeing...

Please add a `trace` property to your launch config like this:
```js
		{
			"type": "node",
			"request": "launch",
			"name": "Launch Program",
			"program": "${workspaceRoot}/test.js",
			"cwd": "${workspaceRoot}",
			"trace": "all"
		}
```
 and post the resulting debug console output here.

**Comment by weinand** [comment]
What happens if you do not press the 'terminate' button but the green 'continue' (play) button instead?

**Comment by chadbr** [comment]
if I press pause it crashes - let me play with above -

**Comment by weinand** [comment]
Please try our experimental node2 debugger by changing the value of the `type` attribute in your launch config to `node2`. Do you see the same behaviour?

**Comment by weinand** [comment]
More things you can try:
- reboot your Mac
- install a different version of node, e.g. 6.5
- open the "Console" application and then watch out for any suspicious entries that appear when pressing the 'terminate' button in VS Code.

**Comment by weinand** [comment]
Inside the VS Code app is a script "terminateProcess.sh" in `"/Applications/Visual\ Studio\ Code.app/Contents/Resources/app/extensions/ms-vscode.node-debug/out/node/terminateProcess.sh"`
This scripts uses the `pgrep` command. Do you have a different `pgrep` command  installed on your system?
If you don't know you could rename the "terminateProcess.sh" temporarily so that VS Code will not find it any more. Does the crash still occur?

**Comment by chadbr** [comment]
should I try any of the others?

**Comment by weinand** [comment]
@chadbr no, it seems that you found the culprit.
Now the question is why does it behave like this on your system?
Please type `which pgrep` in a terminal. What is the resulting path?

**Comment by chadbr** [comment]
@weinand 
$ which pgrep
/usr/local/bin/pgrep

**Comment by weinand** [comment]
Aha, the pgrep on my Mac lives at `/usr/bin/pgrep`.
So you seem to have a different version (and VS Code seems to call the wrong one which is clearly a bug on our side).

**Comment by lucas-natraj** [comment]
This was happening to me ([#14187](https://github.com/Microsoft/vscode/issues/14187)) although it only killed vscode. 
I wiped node, nvm, all node_modules, node_gyp, vscode and extensions, then restarted my machine and reinstalled everything (except the extensions).
It still takes ~12 seconds to stop debugging but at least it doesn't seem to kill vscode anymore.

With the 'trace' line in the launch config the time appears to be spent at 
```
...
shutdown: kill debugee and sub-processes
----------  *** Waits really long here *** ----------
disconnectRequest: send response
_terminated: socket end
_terminated: node v8protocol close
```

**Comment by weinand** [comment]
@lucas-natraj what is the path to your `pgrep`?

**Comment by lucas-natraj** [comment]
Same as @chadbr

**Comment by weinand** [comment]
Do you know what this `/usr/local/bin/pgrep` really is?

**Comment by lucas-natraj** [comment]
/usr/local/Cellar/proctools/0.4pre1/bin/pgrep

**Comment by weinand** [comment]
Could you try to change the `pgrep` in the "terminateProcess.sh" in "/Applications/Visual\ Studio\ Code.app/Contents/Resources/app/extensions/ms-vscode.node-debug/out/node/terminateProcess.sh" to `/usr/bin/pgrep` and check whether this makes a difference?

**Comment by lucas-natraj** [comment]
That seemed to fix it. Stops debugging immediately!

...Happiness...

Gratitudes!!

**Comment by weinand** [comment]
@lucas-natraj @chadbr thanks a lot for helping with the investigation!

**Comment by weinand** [comment]
I can easily reproduce the problem after running this `brew install proctools`

**Comment by lucas-natraj** [comment]
Good to hear.
Am curious to know why it was previously delaying and then crashing vscode, but after the reinstall only the delay remained.

**Comment by weinand** [comment]
`pgrep` is used to find all sub-processes launched by the debug target. For a simple node program it should not find any sub-processes. 

So if I launch node and then do a `ps` to find its process ID (e.g. 36915) and then use `/usr/bin/pgrep -P 36915` no process IDs are listed. This is the correct behaviour.

If I use the `pgrep` installed by `brew` I get a list of 456 process IDs. The "terminateProcess.sh" script then tries to kill all those processes (which takes a long time and most kills will fail due to missing permissions).

**Comment by lucas-natraj** [comment]
Cool. That explains the delay.
Was the crash occurring because of the missing kill permission? Or something else?

**Comment by weinand** [comment]
The crash of VS Code or the Finder etc. occurs because brew's pgrep returns the process IDs of many (all?) processes and the script tries to kill them all. The `-P` option should filter this list to only those processes that are child processes of the specified process.

**Comment by weinand** [comment]
Fixed in tomorrows Insiders build
