### ISSUE TITLE
SCM won't show all the repos when multiple folders are loaded

### ISSUE THREAD

**Issue by FernandoMiguel** [microsoft/vscode#187566]
Type: <b>Bug</b>

After todays update of the nightly, a workspace with multiple repos, is only showing the 1st one in the SCM tab

VS Code version: Code - Insiders 1.81.0-insider (6243562032a9a168df33c1b4dc84d5b2abbcb22d, 2023-07-11T05:51:51.128Z)
OS version: Darwin arm64 22.6.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|5, 6, 9|
|Memory (System)|32.00GB (0.51GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-base64|ada|0.1.0
inline-hasher|ale|1.1.0
spellright|ban|3.0.116
terraform|has|2.27.2023062109
vscode-kubernetes-tools|ms-|1.3.13
indent-rainbow|ode|8.3.1
ytt-lint|phi|0.3.1
vscode-yaml|red|1.13.0
vscode-gitweblinks|red|2.9.2
kubernator-vscode|smp|1.0.0
code-spell-checker|str|2.20.5
shellcheck|tim|0.32.6
sort-lines|Tyr|1.10.2
errorlens|use|3.11.1
vscode-icons|vsc|12.4.0

(1 theme extensions excluded)

</details>

**Comment by FernandoMiguel** [comment]
![image](https://github.com/microsoft/vscode/assets/168366/bb7bde48-ac84-4f53-be81-0eb3136e59a5)
![image](https://github.com/microsoft/vscode/assets/168366/0ac92c15-8c10-4b6e-acb3-4a04c14d15f2)

**Comment by lszomoru** [comment]
@FernandoMiguel could you please share the contents of [the git output window](https://code.visualstudio.com/docs/sourcecontrol/overview#_git-output-window) to see if there are any regressions with the code that does the repository discovery when opening a multi-root workspace.

**Comment by lszomoru** [comment]
@FernandoMiguel, never mind. This is indeed a regression and I am pushing a fix now.

**Comment by FernandoMiguel** [comment]
@lszomoru can someone trigger a build so I can test?
The current nightly is in a state that is affecting my work.

**Comment by lszomoru** [comment]
@FernandoMiguel, sorry about that. 
Yes, we are spinning a new Insiders build that should be available later today.

**Comment by lszomoru** [comment]
Please download the latest Insiders released as it contains the fix for this issue.

**Comment by FernandoMiguel** [comment]
I can confirm this is fixed on the latest build.
thank you

**Comment by lszomoru** [comment]
@FernandoMiguel, thanks for reporting the issue!
