### ISSUE TITLE
Accepting a suggestion in the repl submits the whole input

### ISSUE THREAD

**Issue by rebornix** [Microsoft/vscode#18751]
Not sure if it's valid but I find myself get it wrong quite often.

When we are typing in the editor and Code provides us a list of suggested keywords, I can press `tab` or `enter` to choose the highlighted keyword. My personal take is `enter`.

![editor-suggestion](https://cloud.githubusercontent.com/assets/876920/22077902/f5920150-dd6a-11e6-91fe-7a3e7fea6de8.gif)

While in the debug console, I pressed `enter` to pick the highlighted keyword on the list due to my muscle memory but it actually evaluated the keyword directly. Instead, I should use `tab` to choose the keyword.

![debug-suggestion](https://cloud.githubusercontent.com/assets/876920/22077955/2f1db7b6-dd6b-11e6-8dc5-3af27b7f00fa.gif)

Then I take a look at Chrome Dev Tools. If you press `enter` after typing the prefix of a keyword, it will just evaluate what you have just typed, not as smart as we do. If you use arrows to navigate in the list, and then press `enter`, it will pick the item instead of evaluating its value, which looks reasonable. 

![chrome-suggestion](https://cloud.githubusercontent.com/assets/876920/22078046/8cc517ce-dd6b-11e6-8e01-1e92822acdd0.gif)

File this issue to see if anyone other has the same feeling that the inconsistence really bothers.

cc @roblourens

**Comment by isidorn** [comment]
There are specific reasons for why we do exactly this behavior

1. Not aligned with the editor due to https://github.com/Microsoft/vscode/issues/11944
2. Not aligned with chrome dev tools due to us missing the feature that while you navage through the list of suggestions we fill in the content in the text editor with a shadow

So aligning with dev tools makes sense but it is a feature request

**Comment by joaomoreno** [comment]
In the repl: press <kbd>Cmd Space</kbd> and then <kbd>Enter</kbd>. It will open the suggest widget, choose the first suggestion and then submit that value. This is incredibly frustrating, especially if the value the user picks is a method. This is definitely a bug.
