### ISSUE TITLE
"meta.group.regexp" scope not highlighted anymore

### ISSUE THREAD

**Issue by Gama11** [Microsoft/vscode#18755]
- VSCode Version: Code - Insiders 1.9.0-insider (39d761bf1f4ce7ea605539bdba41a8727b3c7ce0, 2017-01-18T07:10:04.990Z)
- OS Version: Windows 10

It seems like regex groups (`"meta.group.regexp"` scope) are not being highlighted differently anymore. This can be observerd in TypeScript regex literals. Here in the insider build:

![](http://i.imgur.com/cZiE4j1.png)

1.8.1 colors `(in)` slightly differently, which helps readability:

![](http://i.imgur.com/9EqeBhA.png)

**Comment by alexandrudima** [comment]
It appears the theme does not target `meta.group.regex`.

**Comment by aeschli** [comment]
Ah, the problem is with the TS grammar which uses 'string.regex' instead of 'string.regexp' as other grammars.
I filed https://github.com/Microsoft/TypeScript-TmLanguage/issues/409
