### ISSUE TITLE
Design header bar for debug console/output window horizontal panel

### ISSUE THREAD

**Issue by stevencl** [Microsoft/vscode#1876]
We need a design for the header/title bar of the horizontal panel such that it is distinct from each editor and is not 'heavy' so as to avoid drawing attention away from the content inside the panel.
Details of the horizontal panel are captured in this issue: https://github.com/Microsoft/vscode/issues/1875

**Comment by bgashler1** [comment]
# Option 1
![image](https://cloud.githubusercontent.com/assets/11839736/12272197/f5519998-b913-11e5-8f95-fefe8386861e.png)
![image](https://cloud.githubusercontent.com/assets/11839736/12272201/f806bbaa-b913-11e5-93fb-0712b601ddd3.png)
![image](https://cloud.githubusercontent.com/assets/11839736/12272222/1cddaf74-b914-11e5-84f4-9bcc46564206.png)

**Comment by bgashler1** [comment]
# Option 2: _striped with no header_
See the animation concept I created below...
![horizontal-panel-option-2-brad](https://cloud.githubusercontent.com/assets/11839736/12278771/bff6fa30-b937-11e5-8c6c-ec8f9dc81476.gif)

![image](https://cloud.githubusercontent.com/assets/11839736/12278828/2c632aa4-b938-11e5-98bc-ea19a499f054.png)

**Comment by stevencl** [comment]
Good work Brad, I like the way you used colour in option 2 to indicate whether content in the panel is 'live' or 'hot' as you called it. That would be my preference.

How tall would the separator be? Tall enough to easily grab and resize with the mouse? Especially when the mouse is above the close button (would be good to avoid the user unintentionally closing the window for example when they try to grab the separator to resize it).

**Comment by isidorn** [comment]
Great work @bgashler1! This work has been merged into master so you can try it out

**Comment by roydondsouza** [comment]
Nice work everyone. In which stable version this does this roll out?

**Comment by isidorn** [comment]
@roydondsouza I have to disapoint you most of the designs posted here have not made it to the final version of the product. The current stable has the latest and nothing here is planned to change in the following milestone

**Comment by roydondsouza** [comment]
@isidorn Thank you, I understand. Will follow this :)

**Comment by roydondsouza** [comment]
@isidorn Thank you, I understand. Will follow this :) Splitting terminal into horizontal will be very beneficial for smaller screens like 13" Any plans to roll this out anytime?
