### ISSUE TITLE
Don't translated "Synchronize changes"

### ISSUE THREAD

**Issue by IgorNovozhilov** [Microsoft/vscode#18765]
- VSCode Version:
![image](https://cloud.githubusercontent.com/assets/3082812/22094958/5a8d87f2-de22-11e6-93bf-bf0c1b6500ed.png)

- OS Version: win7-pro

Steps to Reproduce:

1. Hover your mouse over the icon: "Synchronize changes"

![image](https://cloud.githubusercontent.com/assets/3082812/22095074/04d310f6-de23-11e6-88a6-513f176d8654.png)

2. Click on the icon: "Synchronizing changes..."

![image](https://cloud.githubusercontent.com/assets/3082812/22095075/0677c528-de23-11e6-8599-436398bd728c.png)

**Comment by joaomoreno** [comment]
Translation for the new SCM is not yet done, but tracked in #18615
