### ISSUE TITLE
Investigate to show combined confirm dialog for all close actions

### ISSUE THREAD

**Issue by gregvanl** [Microsoft/vscode#18763]
- VSCode Version: 1.9.0 Insiders
- OS Version: Windows 10

Steps to Reproduce:

1. Turn off Auto Save
2. Touch multiple files
3. From the editor group More (...) button, click Close All or View: Close All Editors in Group command

A dialog is still shown for each dirty file unlike Command Palette View: Close All Editors command

**Comment by bpasero** [comment]
@gregvanl there are many more ways how to close multiple editors at once (e.g. right click on a tab -> close others). I explicitly did not add this feature for other commands to close to see what users have to say about it. To be honest, not a single user so far complained about the fact that we ask to confirm 1 by 1 and some actually ask to improve this behaviour by opening the file to confirm and show it. So there may be many users expecting this behaviour.

**Comment by bpasero** [comment]
This feature request will not be considered in the next [6-12 months roadmap](https://github.com/Microsoft/vscode/wiki/Roadmap) and as such will be closed to keep the number of issues we have to maintain actionable. Thanks for understanding and happy coding!
