### ISSUE TITLE
Not rotating icon while updating SCM

### ISSUE THREAD

**Issue by IgorNovozhilov** [Microsoft/vscode#18766]
- VSCode Version:
![image](https://cloud.githubusercontent.com/assets/3082812/22095790/9cce98b2-de28-11e6-9888-746a5ee9efe8.png)

- OS Version: win7-pro

Steps to Reproduce:

1. In the current version
![2017-01-19_09h18_59](https://cloud.githubusercontent.com/assets/3082812/22095761/6edc8df6-de28-11e6-8b06-e9be7a70329b.gif)

2. In the oldest version:
![2017-01-19_09h24_59](https://cloud.githubusercontent.com/assets/3082812/22095866/2c6251ee-de29-11e6-9dee-4adc87dd0354.gif)

PS:
In the old version was prettier :smile:

**Comment by joaomoreno** [comment]
Agree!

**Comment by joaomoreno** [comment]
Done
