### ISSUE TITLE
Call stack context menu option sends internal URL

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#18761]
This is what I get for a script with a sourceReference and path:

![image](https://cloud.githubusercontent.com/assets/323878/22087006/7a89ea74-dd90-11e6-8acf-f1a058c12e38.png)

**Comment by isidorn** [comment]
@roblourens and what would you expect to get in that case? Only the path?

**Comment by roblourens** [comment]
Yeah, I think so. But then I don't know what to expect if there is a sourceReference, but no path. Maybe just the sourceReference. I'd also be ok with just getting the sourceReference whenever it's set, whether or not there's a path, since we have a pattern of the sourceReference taking precedence over the path.

Getting `debug://internal` feels like I'm seeing an implementation detail, but I could totally work with that too if it's never going to change.

**Comment by isidorn** [comment]
@roblourens I changed it for internal modules to return path if present otherwise return source reference. Fell free to edit here https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/debug/electron-browser/debugViewer.ts#L295
