### ISSUE TITLE
Suggest to add new panel for Peek Definition

### ISSUE THREAD

**Issue by xixiliguo** [Microsoft/vscode#18767]
- VSCode Version: 1.8.1
- OS Version: Mac

When we take lots of time to browse code for study, we often run “Peek Definition" to check definition of variable, function, type.  It is still not inconvenient to switch by run keyboard (via Alt+F12) 
Hope have dedicated panel for it. like context windows of SourceInsight. 
We can also add result of "Find All References" in this panel.

**Comment by dbaeumer** [comment]
@bpasero @jrieken @chrisdias

**Comment by jrieken** [comment]
@xixiliguo Not really sure what you mean by that. There is the `Peek Definition` in the context menu. Where else do you want to see that?

![screen shot 2017-01-19 at 09 15 40](https://cloud.githubusercontent.com/assets/1794099/22098669/f001591c-de27-11e6-9ae5-06294c3a8681.png)

**Comment by xixiliguo** [comment]
@jrieken As you see, we still need press (alt+F12) to get result
What i suggest is that when mouse hover variable, function, type etc, new panel show definition immediately.   

mouse hover convergeephemerons, it show function definition

 
![image](https://cloud.githubusercontent.com/assets/17514448/22131313/76c5906a-deed-11e6-9eee-4e2978007b3b.png)


mouse hover variable g, it show definition
![image](https://cloud.githubusercontent.com/assets/17514448/22131342/b5ccc24c-deed-11e6-847e-67dda77b67f4.png)

**Comment by jrieken** [comment]
You can kind of do this when pressing Cmd/Ctrl while hovering over a symbol

![jan-20-2017 09-20-34](https://cloud.githubusercontent.com/assets/1794099/22141310/bb23bb20-def1-11e6-806c-d1d0da27e27a.gif)

**Comment by xixiliguo** [comment]
Pressing Cmd can give preview, but it only show part when definition body is long and cannot scroll up/dow to browse

**Comment by alexandrudima** [comment]
This feature request will not be considered in the next [6-12 months roadmap](https://github.com/Microsoft/vscode/wiki/Roadmap) and as such will be closed to keep the number of issues we have to maintain actionable. Thanks for understanding and happy coding!
