### ISSUE TITLE
Surface dev tunnel usage limits more clearly

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#187649]
- Check dev tunnel limits asynchronously when we try to connect to a tunnel, and show a modal notification if they're exceeded
- Have a "Show Usage Limits" command for users to monitor their limits
- Link to documentation both places with more information

**Comment by joyceerhl** [comment]
I see this when I run Show Usage Limits 

```
2023-07-25 10:39:37.814 [info] =============== Usage limits:===============
2023-07-25 10:39:37.814 [info] No limits are currently in place
2023-07-25 10:39:37.814 [info] Learn more at https://aka.ms/vscode-dev-tunnel-limit
```

Does this mean that I haven't hit any limits yet, or that there are no limits in place for my account?

**Comment by connor4312** [comment]
Currently dev tunnels does not have any limits applied for VS Code since we did not previously surface them in a good way. I think that's all you can really verify in the current state.
