### ISSUE TITLE
Moved view title contains [Object object]

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#187651]
1. Have the [flame chart visualizer](https://marketplace.visualstudio.com/items?itemName=ms-vscode.vscode-js-profile-flame) installed and debug something JavaScript
2. Move the "Realtime Performance" view from the debug view into the Explorer view
3. Notice it's now the `[Object object]: Realtime Performance` view

![image](https://github.com/microsoft/vscode/assets/2230985/cb836d66-0e94-4c73-a061-29da60b69d9d)

**Comment by bpasero** [comment]
I cannot reproduce (anymore?):

<img width="600" alt="image" src="https://github.com/microsoft/vscode/assets/900690/faf6682b-94e2-49dd-a49f-9ae6dbf27541">

@connor4312 can you check?
