### ISSUE TITLE
cmd+click to go to definition doesn't work on mac anymore

### ISSUE THREAD

**Issue by marvinhagemeister** [microsoft/vscode#187639]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: Version: 1.81.0-insider (Universal), Commit: f8782370c90ec98467dc3590bcfa2eeb1f218107
- OS Version: 13.4.1 (22F82)

Steps to Reproduce:

1. Open any JS project with a couple of files that import each other like https://github.com/preactjs/preact
2. `cmd+click` on a function callsite to jump to its definition -> nothing happens

This only occurs in the insiders build and not in the stable release line. Disabling all extensions doesn't help either.

**Comment by mjbvz** [comment]
Please share a specific code location that demonstrates the issue

**Comment by marvinhagemeister** [comment]
@mjbvz Click on any function call or any variable usage in the project. I can reproduce it with all of them.

**Comment by mjbvz** [comment]
https://github.com/microsoft/vscode/assets/12821956/db7469fd-cb95-4442-ad5a-dd9c1349f568


What if you run `go to definition` from the command palette? Did you perhaps disable the built-in TypeScript / JavaScript extension?

**Comment by marvinhagemeister** [comment]
Found the culprit. For some reason `"editor.multiCursorModifier": "ctrlCmd",` was set. Changing that back to the default resolved it for me. 🙈
