### ISSUE TITLE
Performance Issue: Don't query all decorations

### ISSUE THREAD

**Issue by hediet** [microsoft/vscode#187695]
This method:
https://github.com/microsoft/vscode/blob/16098b1fe1936f7f8c31d2ae655f6f88dc6fbf42/src/vs/editor/contrib/inlayHints/browser/inlayHintsController.ts#L162

Calls this for loop:
https://github.com/microsoft/vscode/blob/16098b1fe1936f7f8c31d2ae655f6f88dc6fbf42/src/vs/editor/contrib/inlayHints/browser/inlayHintsController.ts#L556-L566

... querying all decorations in the file.
Because bracket pair colorization is implemented using decorations, this queries a ton of data for bigger files (for checker.ts there are `87.560` decorations).
Generally I think `getDecorationsInRange` should only be called for small ranges.

**Comment by jrieken** [comment]
In this a theoretical problem or something that shows up in the profiler?

**Comment by jrieken** [comment]
Is there a way to look up decorations by id? If I could do that I can turn the loop around: look up my decorations by id and check the range with the needs-update-range

**Comment by hediet** [comment]
There is `getDecorationRange(id: string): Range | null;` on `ITextModel`
