### ISSUE TITLE
Hello please contact me.

### ISSUE THREAD

**Issue by requim111** [microsoft/vscode#187647]
Type: <b>Bug</b>

Hello, I wrote an auto clicker and I installed plugins like pyinstaller, cx_Freeze, py2exe to convert it to exe file (from cmd.) and none of them work, I keep getting the same error please help me.
The error: pyinstaller : The term 'pyinstaller' is not recognized as the name of a cmdlet, function, script file, or operable 
program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ pyinstaller --onefile deneme.py
+ ~~~
    + CategoryInfo          : ObjectNotFound: (pyinstaller:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

VS Code version: Code 1.80.0 (660393deaaa6d1996740ff4880f1bad43768c814, 2023-07-04T15:06:02.407Z)
OS version: Windows_NT x64 10.0.19045
Modes:

**Comment by dbaeumer** [comment]
@requim111 none of those (pyinstaller, cx_Freeze, py2exe ) seem to be extensions for VS Code. You should better ask the Python community on StackOverflow for help since this repository is about features that are owned by VS Code.
