### ISSUE TITLE
Are choice snippets dangerous now? Breaking extensions completions

### ISSUE THREAD

**Issue by zardoy** [microsoft/vscode#187642]
Does this issue occur when all extensions are disabled?: Yes

Hi! Since 1.80.0 update I'm struggling with really weird vscode behavior. I tested it on insiders + empty profile and on different platforms.

### **STR**

1. Add snippet eg for `typescript`:
```json
"choice": {
    "prefix": "choice",
    "body": [
        "${1|test|}",
    ],
    "description": "Yes, its choice!"
}
```
2. Use this snippet

Actual: No TypeScript completions anymore until window reload. No completions from any extension.
Expected: no breakage

Might be related: https://github.com/microsoft/vscode/issues/180132

By the way how I can disable BUILTIN snippets features completely?! I have lots of extension that contribute these snippets and its too annoying to disable each snippet using eyeball (`editor.suggest.showSnippets` disables snippet-kind completions from other extensions as well)

//cc @jrieken

**Comment by jrieken** [comment]
Thanks @zardoy. This is a real good find.

**Comment by jrieken** [comment]
very likely also https://github.com/microsoft/vscode/issues/187312

**Comment by jrieken** [comment]
regression from https://github.com/microsoft/vscode/commit/3e232a82df4313fb8ca898471416763288c6827d

**Comment by testforstephen** [comment]
See the issue https://github.com/redhat-developer/vscode-java/issues/3194, the code completion feature of the Java extension (which uses choice snippet) stopped working after I upgraded to `vscode@1.80.0`. And it works fine again when I use the `1.81.0-insider (2023-07-12)` version.

@jrieken Any ETA for the June Recovery release? thanks.

**Comment by jrieken** [comment]
> @jrieken Any ETA for the June Recovery release? thanks.

Today, July 13th

**Comment by testforstephen** [comment]
@jrieken Great, appreciate for the quick fix, thank you. Look forward the new version.
