### ISSUE TITLE
Single click on peek view closing the peek window

### ISSUE THREAD

**Issue by droidsumit** [microsoft/vscode#187617]
Type: <b>Bug</b>

Steps to repro:
1. open reference of a function, it will open in peek view
2. do a single click in peek view, it closes instead going to the clicked line# of peek view (which was the earlier behavior)

VS Code version: Code 1.80.0 (660393deaaa6d1996740ff4880f1bad43768c814, 2023-07-04T13:40:17.963Z)
OS version: Darwin arm64 22.5.0
Modes:
Connection to 'ssh-remote+dev2' could not be established
Connection to 'SSH: bgl-kumsumi2-dev2' could not be established  Canceled
Connection to 'SSH: devxads-dev1' could not be established  Canceled
Remote OS version: Linux x64 4.18.0-425.3.1.el8.x86_64
Connection to 'SSH: devxads-dev3' could not be established  Canceled
Connection to 'SSH: devxads-dev3' could not be established  Canceled
Remote OS version: Linux x64 4.18.0-425.3.1.el8.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|9, 7, 6|
|Memory (System)|16.00GB (0.06GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

Connection to 'ssh-remote+dev2' could not be established

Connection to 'SSH: bgl-kumsumi2-dev2' could not be established  Canceled

Connection to 'SSH: devxads-dev1' could not be established  Canceled

|Item|Value|
|---|---|
|Remote|SSH: dev1|
|OS|Linux x64 4.18.0-425.3.1.el8.x86_64|
|CPUs|Intel(R) Xeon(R) Gold 6246R CPU @ 3.40GHz (16 x 3399)|
|Memory (System)|31.18GB (21.44GB free)|
|VM|100%|

Connection to 'SSH: devxads-dev3' could not be established  Canceled

Connection to 'SSH: devxads-dev3' could not be established  Canceled

|Item|Value|
|---|---|
|Remote|SSH: devxads-dev1|
|OS|Linux x64 4.18.0-425.3.1.el8.x86_64|
|CPUs|Intel(R) Xeon(R) CPU E5-2667 v3 @ 3.20GHz (16 x 3192)|
|Memory (System)|31.18GB (24.06GB free)|
|VM|100%|
</details><details><summary>Extensions (107)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|13.3.1
project-manager|ale|12.7.0
jam-for-zos|and|0.0.5
pythonsnippets|frh|1.0.2
better-cpp-syntax|jef|1.17.2
vscode-peacock|joh|4.2.2
yang|mar|0.1.3
vscode-boost-jam|mlo|0.0.2
remote-containers|ms-|0.299.0
remote-ssh|ms-|0.103.2023062115
remote-ssh-edit|ms-|0.86.0
remote-wsl|ms-|0.80.2
vscode-remote-extensionpack|ms-|0.24.0
remote-explorer|ms-|0.4.1
remote-server|ms-|1.3.0
iosxr|phi|1.0.3
material-icon-theme|PKi|4.28.0
vscode-autohide|sir|1.0.8
rewrap|stk|1.16.3
vim|vsc|1.25.2
material-theme|zhu|3.15.18
Bookmarks|ale|13.3.1
project-manager|ale|12.7.0
jam-for-zos|and|0.0.5
github-markdown-preview|bie|0.3.0
markdown-checkbox|bie|0.4.0
markdown-emoji|bie|0.3.0
markdown-footnotes|bie|0.1.1
markdown-mermaid|bie|1.19.0
markdown-preview-github-styles|bie|2.0.2
markdown-yaml-preamble|bie|0.1.0
blackbox|Bla|1.0.44
ccls|ccl|0.1.29
baseline-coverage|cis|0.0.8
cdets|cis|1.1.2
cisco-marketplace|cis|23.6.2
developer-workboard|cis|23.5.2
firex-vscode|cis|0.0.4
smartut-test-adapter|cis|0.2.14
xdev-ai|cis|0.1.8
xdev-clang-format|cis|1.0.6
xdev-earms|cis|0.0.5
xdev-indentor|cis|0.0.3
xdev-onboard|cis|0.0.8
xdev-persistent-terminal|cis|23.5.1
xdev-pull-requests|cis|23.5.2
xdev-pyats|cis|23.5.1
xdev-pyats-validator|cis|23.5.1
xdev-sa|cis|1.0.9
xdev-support|cis|2.1.8
xdev-topoviewer|cis|1.1.0
xdev-worktree|cis|23.6.2
xr-workspace|cis|1.6.0
doxdocgen|csc|1.4.0
vscode-markdownlint|Dav|0.51.0
githistory|don|0.6.20
gitlens|eam|14.0.1
vscode-test-explorer-diagnostics|emi|0.1.1
code-runner|for|0.12.0
c-cpp-runner|fra|7.0.2
pythonsnippets|frh|1.0.2
macros|ged|1.2.1
todo-tree|Gru|0.0.226
vscode-test-explorer|hbe|2.21.1
githd|hui|2.3.3
plantuml|jeb|2.17.5
better-cpp-syntax|jef|1.17.2
polacode-2019|jef|0.6.1
vscode-peacock|joh|4.2.2
auto-comment-blocks|kev|1.0.1
bash-ide-vscode|mad|1.37.0
git-patch-utility|mak|6.2.32
yang|mar|0.1.3
git-graph|mhu|1.30.0
vscode-boost-jam|mlo|0.0.2
isort|ms-|2023.10.0
python|ms-|2023.12.0
vscode-pylance|ms-|2023.7.10
cpptools|ms-|1.16.3
cpptools-extension-pack|ms-|1.3.0
live-server|ms-|0.4.9
test-adapter-converter|ms-|0.1.8
vsliveshare|ms-|1.0.5873
autodocstring|njp|0.6.1
vscode-python-typehint|njq|1.5.1
iosxr|phi|1.0.3
material-icon-theme|PKi|4.28.0
polacode|pnp|0.3.4
vscode-yaml|red|1.13.0
bash-debug|rog|0.3.9
vscode-coverage-gutters|rya|2.11.0
bash-beautify|sha|0.1.1
trailing-spaces|sha|0.4.1
vscode-autohide|sir|1.0.8
rewrap|stk|1.16.3
code-spell-checker|str|2.20.5
shellcheck|tim|0.32.6
yang-vscode|typ|2.2.0
sort-lines|Tyr|1.10.2
vscode-lldb|vad|1.9.2
intellicode-api-usage-examples|Vis|0.2.7
vscodeintellicode|Vis|1.2.30
codetour|vsl|0.0.59
clang-format|xav|1.9.0
codescope|xul|0.2.0
cisco-config-highlight|Y-Y|0.5.1
material-theme|zhu|3.15.18

(4 theme extensions excluded)

</details>

**Comment by jrieken** [comment]
Where do you click? Into the editor, the tree, or the title? I cannot reproduce no matter where I click

**Comment by droidsumit** [comment]
Hi,

I am clicking onto editor area of peek window.
I could able to figure it out, it seems the issue is with one of extension ([auto hide])(https://marketplace.visualstudio.com/items?itemName=sirmspencer.vscode-autohide) 
Thanks for your time and sorry for confusion, initially i couldn't realize it was due to the extension but later on through check i could able to figure it out.

Thanks,
Sumit M.
