### ISSUE TITLE
PR Create Flow - Weird Colors

### ISSUE THREAD

**Issue by hediet** [microsoft/vscode#187691]
(on windows)

![Code_-_Insiders_vNsVpbFwmG](https://github.com/microsoft/vscode/assets/2931520/979305cd-ab94-4725-81df-aa55a9b5fe2a)

**Comment by hbons** [comment]
Related to #188143

**Comment by santosh-kuchetti** [comment]
can you please add the reproducing steps to this issue @hediet. Thank you
