### ISSUE TITLE
PR Create Flow - Merge Method Label

### ISSUE THREAD

**Issue by hediet** [microsoft/vscode#187699]
I don't think I've seen a UI control like the merge method icon before.
It is a bit weird that it is a menu drop down without top level state:

![Code_-_Insiders_wOJ5bavusD](https://github.com/microsoft/vscode/assets/2931520/67731754-78f8-4251-b2ad-7ace228caa46)

When I click "create" without automerge, is the value of this setting even sent to GitHub?

Maybe we should show a label next to the icon, which could be "Merge Commit", "Squash" or "Rebase" to keep it short and a hover message explaining this setting is only considered for auto-merge.

This is the advantage of a auto-merge checkbox: Once you tick/untick it, you can show/hide other options (such as the merge style).

**Comment by alexr00** [comment]
I have removed the merge method button/menu and instead put the automerge options into the Create dropdown. The pre-release went out late today, but it's available there now.
