### ISSUE TITLE
.net MAUI: 

### ISSUE THREAD

**Issue by divikiran** [microsoft/vscode#187650]
Type: <b>Bug</b>

Maui App launch failed with below error, please help

Optimizing assemblies for size failed. Optimization can be disabled by setting the PublishTrimmed property to false. [/Users/divikiranravela/Documents/VSCode/MAUI/MauiApp1/MauiApp1.csproj::TargetFramework=net7.0-maccatalyst]

One of '--self-contained' or '--no-self-contained' options are required when '--runtime' is used. [/Users/divikiranravela/Documents/VSCode/MAUI/MauiApp1/MauiApp1.csproj::TargetFramework=net7.0-maccatalyst]

VS Code version: Code 1.80.0 (Universal) (660393deaaa6d1996740ff4880f1bad43768c814, 2023-07-04T13:39:33.766Z)
OS version: Darwin arm64 22.4.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Max (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|5, 10, 10|
|Memory (System)|64.00GB (4.31GB free)|
|Process Argv|--crash-reporter-id 9c8a45e8-b7ac-4cc3-bbe3-c2e4544c998f|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (27)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-sqlite|ale|0.14.1
prettier-vscode|esb|9.19.0
code-runner|for|0.12.0
remotehub|Git|0.60.0
rest-client|hum|0.25.1
ilspy-vscode|ics|0.15.0
csharpextensions|kre|1.7.3
vscode-azurefunctions|ms-|1.11.0
vscode-azureresourcegroups|ms-|0.7.5
csdevkit|ms-|0.1.103
csharp|ms-|2.0.248
dotnet-maui|ms-|0.1.34
vscode-dotnet-runtime|ms-|1.6.0
vscodeintellicode-csharp|ms-|0.1.26
data-workspace-vscode|ms-|0.5.0
mssql|ms-|1.19.1
sql-bindings-vscode|ms-|0.4.0
sql-database-projects-vscode|ms-|1.1.1
python|ms-|2023.12.0
vscode-pylance|ms-|2023.7.10
azure-account|ms-|0.11.5
azure-repos|ms-|0.36.0
remote-repositories|ms-|0.38.0
vscode-nuget-gallery|pat|0.0.24
material-icon-theme|PKi|4.28.0
msbuild-project-tools|tin|0.4.9
vscode-proto3|zxh|0.5.5

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263:30335439
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
py29gd2263:30784847
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
282f8724:30602487
pyind779:30671433
89544117:30613380
pythonsymbol12:30671437
2i9eh265:30646982
showlangstatbar:30737416
vsctsb:30748421
pythonms35:30701012
03d35959:30757346
pythonfmttext:30731395
pythoncmvfstrcf:30756944
fixshowwlkth:30771522
showindicator:30785052
pythongtdpath:30769146
i26e3531:30780429
pythonnosm12tcf:30779713
pythonidxpt:30784022
pythonnoceb:30776495
h7j2d465:30786200

```

</details>

**Comment by Netrixdesigns** [comment]
Anyone with solution plssss

**Comment by roblourens** [comment]
Please file this on the .net extension, thanks
