### ISSUE TITLE
Terminal: "Open file in editor" tooltip says "ctrl + click". Should say "ctrl + middle click"

### ISSUE THREAD

**Issue by mbenkmann** [microsoft/vscode#187640]
I'm on Linux. I thought the feature "Open file in editor" in the Terminal was broken or unsupported with my shell (zsh). But now I discovered that the tooltip is just wrong/imprecise. It says "ctrl + click", but the shortcut is actually "ctrl + MIDDLE click", not left click as I had assumed. The tooltip should reflect that, especially since ctrl + LEFT click does absolutely nothing (at least not on my system).

**Comment by Tyriar** [comment]
It should be left click, not sure what's you're seeing.

**Comment by mbenkmann** [comment]
It definitely is NOT left click here. Is there a setting in vscode that would change this?

**Comment by mbenkmann** [comment]
I just launched code on the naked Xorg server with no window manager, and it's left click. Once I start the window manager (fluxbox in my case) it turns into right click. For the same instance of code that's already running. There must be some incompatibility between VS Code and Fluxbox. I've never seen this in any other application. Nor does left click behavir weirdly in any part of VS Code. E.g. left clicking into the editor to place the mouse cursor works just fine as does left clicking on UI elements like the cog in the bottom left or the tabs of the editor or the menus. VS Code must do something really weird to get the mouse click in the Terminal window specifically.

**Comment by Tyriar** [comment]
I'd report this to fluxbox as I haven't seen anything like this reported before. Here's where we handle the tooltip+modifier fwiw:

https://github.com/microsoft/vscode/blob/ce2579718d6c6defd3382aaa3114ffac20c8a3c1/src/vs/workbench/contrib/terminalContrib/links/browser/terminalLinkManager.ts#L316-L340

**Comment by blueforesticarus** [comment]
meanwhile wtf is the modifier key tied to the setting for mutlicursor and even worse wtf is it set to the **opposite**

My alt key is used for system bindings I can't use it for this.

**Comment by Tyriar** [comment]
@blueforesticarus so the terminal matches the link modifier in the editor which `multiCursorModifier` controls. I've been waiting for https://github.com/microsoft/vscode/issues/3130 before improving this as that's the true fix for these mouse configuration problems.
