### ISSUE TITLE
Shortcut for clearing integrated Terminal is no longer mapped

### ISSUE THREAD

**Issue by simmo** [microsoft/vscode#187648]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.80.0 stable / 1.81.0 insiders
- OS Version: macOS Ventura 13.4

Steps to Reproduce:

1. Open Terminal
2. Focus the Terminal
3. Attempt shortcut [cmd]+[k]

Below shows that a keymapping for [cmd]+[k] exists.
<img width="1618" alt="image" src="https://github.com/microsoft/vscode/assets/265345/9035e589-ad64-479e-88c5-8f39664a5c13">

Below shows the context menu's clear command missing a shortcut.
<img width="357" alt="image" src="https://github.com/microsoft/vscode/assets/265345/e4ffbe91-c418-4ba6-9060-76b0ec791c7d">

<img width="361" alt="image" src="https://github.com/microsoft/vscode/assets/265345/39b22846-7eb9-4761-9245-23e150bc1f1c">
<img width="315" alt="image" src="https://github.com/microsoft/vscode/assets/265345/9ee5e026-8af3-4275-9680-9c77ede26902">

**Comment by meganrogge** [comment]
See https://code.visualstudio.com/docs/terminal/advanced#_macos-clear-screen for why cmd+k might stop working
