### ISSUE TITLE
VSCode starts a lot of git process at the same time and doesn't stopped them

### ISSUE THREAD

**Issue by arusakov** [Microsoft/vscode#18775]
- VSCode Version: 1.8.1
- OS Version: Mac OS X 10.12.2

I don't know how to reproduce it.
But it's happened when I work with with [TypeScript](https://github.com/Microsoft/TypeScript) repo.

<img width="657" alt="screen shot 2017-01-19 at 12 59 22" src="https://cloud.githubusercontent.com/assets/3473150/22102213/b32e0998-de47-11e6-8c52-93ce65a1a864.png">

**Comment by joaomoreno** [comment]
@arusakov Can you show me the output of `ps ax | grep git`? I want to check what those processes are doing.
