### ISSUE TITLE
vscode unresponsible with `debug.inlineValues: on` in large files

### ISSUE THREAD

**Issue by zardoy** [microsoft/vscode#187783]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.80.0
- OS Version: Windows/macOS

Steps to Reproduce:

0. Set `debug.inlineValues` to `on`
1. Install `typescript`, create `test.mjs` with:
```js
import pkg from 'typescript'

const { getSupportedCodeFixes } = pkg

getSupportedCodeFixes()
```
Place breakpoint at `getSupportedCodeFixes()`
2. In *Debug: JavaScript terminal* start debugging e.g. `node 1.mjs`
3. After breakpoint hit, press STEP INTO

actual: vscode freeze (and message popups after some delay)
expected: delay/skip showing values?

If there are technical limitation in implementing this feature e.g. too hard to implement behavior from above, can you please provide a setting to disable this feature on specific files set (or when it exceeds some limit)?

Of course I'd like to skip large files, but in some cases it can be opened randomly because of error, debugger or something else...

**Comment by connor4312** [comment]
This is still a bit slow in TypeScript because we tokenize the lines we want, which takes a minute, but it's not nearly as bad as before. At some point we'll have a proper, faster InlineValueProvider for TS.
