### ISSUE TITLE
Skip Version / Ask Again in N Hours/Days

### ISSUE THREAD

**Issue by mjmatthiesen** [microsoft/vscode#187758]
Update mode: default
Right now when there's a new update, you are constantly asked if you want to download it. If you select later, it doesn't actually do anything, it just dismisses the pop up. Later should not remind me of the new update for N hours/days/etc, depending on configuration.

Additionally, there should be an action to skip the update.

This would greatly increase the UX around updates. Right now, every time I open a new vs code instance, which happens several times a day, I get this update noise.

![image](https://github.com/microsoft/vscode/assets/16603906/a0883855-8b34-4bed-8319-808848042f3f)

**Comment by joaomoreno** [comment]
The `update.mode` setting gives you a little bit more flexibility as to when you see the updates notification.

Closing as won't implement.
