### ISSUE TITLE
[error] CodeWindow: renderer process gone (reason: crashed, code: -1)

### ISSUE THREAD

**Issue by youmustp** [microsoft/vscode#187791]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.80.0.0
- OS Version: Windows 11

Steps to Reproduce:

1. Open vs code

**Comment by rzhao271** [comment]
Hi @youmustp, could you attach a crash dump zip following the guide at [Creating a crash report](https://github.com/microsoft/vscode/wiki/Native-Crash-Issues#creating-a-crash-report)?

**Comment by youmustp** [comment]
its fixed now
