### ISSUE TITLE
JSDoc: @example tag does not parse inline tags like {@link myProperty}

### ISSUE THREAD

**Issue by nickyonge** [microsoft/vscode#187768]
# Bug Report

### 🕗 Version & Regression Information

Win 11, HP Spectre x360

Seen in VS Code 1.79.2, using JavaScript display formatting (.js file), "About" data from VS program:

Version: 1.79.2
Commit: 695af097c7bd098fbf017ce3ac85e09bbc5dda06
Date: 2023-06-14T08:57:04.379Z
Electron: 22.5.7
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Windows_NT x64 10.0.22621

Does occur when extensions are disabled 

### 🔎 Search Terms

JSDoc, example, @/example (without the slash), inline, vscode, tags, doctags

Found similar issues but couldn't find a non-closed duplicate. Some similar ones, #56223 #187663 #26338

(Also some similar stuff in the /typescript repo, eg [#15749](https://github.com/microsoft/TypeScript/issues/15749))

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/PQKhAIGMHsDsGcAu4BOBTAZuR1wHEUBLNAczRXABUiAHRAT0gAtCBDAG3AAUVoArNJESE44WKwC2aADTZWAazRUAEgEFK4eDTTt2hWCXATCSBWnjgQwALAAoNAA8a0FMhgJkJIqXLgAvOAA5F7EZCiBANx2dqAgdpb4aIgWiExK7kiomORosJBK4lLg0FipSiSEAG65Rqw04DS82q704AAUrJAwEhLQACaswgbgGC7gHIjk4pNikuYAlAB04ABKSQCuKAhi67rghFiw0Mij67B9i-FxtgkAAjSsKJLgAN5IRAYAvrX1hUolPwavAEQhEsHA9Gg63AAHdWLBEFdwLd0IhNuC3ogPiRvhI6kD+IJhKI-rJmlA4Jl0BgLINsNB6gC8TR4Is+PAkbdHJIaOwlABREiyfQ0daIIaGABEWMIdEYLA4kqyaK2Fhetz0sHk4BCPgoAG1dWEALqfTnwNBKdWa7XM+DfUYUDicSocQh9QF-fawUXJK42exOFwnM6g0RcR4WgCydTazPmr3i4GTwGA4D5yHd-kSiBjNAAkgARON1eZRG7J8Cp-ZYNpZgA84AADAmXkmU2nKxSENA+YtyLwUG1JfyVisAPIrABcFN2HqOyAeKAtgKVAGpARvJcLYK69B6i+B1-sPVvZKj0fpDLBduxJWX21XO5WL1sdrpy13q2aKx3leifngfV3WNfUAEZjXLH8YjTGAaFaAEyhGUNiXBVI6XzMRjkIfIPSQkx4HWf5wRgkYxl6dBvVGTRLU0FBIBGQg+UAtl4BnUimHFFkp1TCpUnWAAjRZumAPp1kgeRnHOJB1j6ERgGZZpgAE9hoAE4BWAwVgACYAE49IE3Sm1YAAOAAWABmMyzIAVjAtAbIAdgwAA2GyXLA3TWFYJs0D6KyMAsvobMgGzgHgejgHZBS6lZdkgA)

I just copied the function I linked but tbh this is overkill lol

### 💻 Code

```js
/** const ref to Grieger Triptychial Projection name, take THAT spelling mistakes */
export const grieger = 'grieger';

/**
 * Gets the const reference name of the given map property (accommodating for alternate names). Returns null if not found.
 *
 * @param {string} map name of map projection you want
 * @return {string} map projection name, per const refs at top of maps.js
 * @example Eg, inputting "triptychial" returns {@link grieger [grieger]}
 * @see {@link maps} for all valid map name inputs
 */
export function ParseMap(map) {
    // let id = GetMapID(map);
    // if (id < 0) {
    //     console.error("ERROR: could not parse map " + map + ", invalid ID " + id + ", returning null");
    //     return null;
    // }
    // return maps[id][1];
}

// copy of the function that I noticed the issue on 
// for more info see src file maps.js: 
// https://github.com/duckpondstudio/mapper/blob/afa2929b90a8434451e57f65619aa0ed34f3d5c5/src/js/maps.js
```

### 🙁 Actual behavior

Using an inline {@/link myProperty} jsdoc tag in an @/example tag does not render properly, instead rendering what looks like the full command input that _should_ turn into a hyperlink.

![image](https://github.com/microsoft/TypeScript/assets/2841909/1714c504-916a-40b3-8101-5936f20f7567)

### 🙂 Expected behavior

The @/link property should just be a clickable link to the linked property, like what's in the @/see tag just below the @/example

**Comment by mjbvz** [comment]
Minimal example:

```ts
/**
 * @example 1 + 1 {@link foo foo}
 */
const foo = 1;
```

`@example` tags render their content as code snippets. This [matches how JSDoc works](https://jsdoc.app/tags-example.html). So the bug here is that `{@link ...` should likely just be rendered as source text in this case

**Comment by nickyonge** [comment]
> `@example` tags render their content as code snippets. This [matches how JSDoc works](https://jsdoc.app/tags-example.html). So the bug here is that `{@link ...` should likely just be rendered as source text in this case

Thank you for clarifying!
