### ISSUE TITLE
insiders.vscode.dev loads stable version of GHPRI extension

### ISSUE THREAD

**Issue by lszomoru** [microsoft/vscode#187722]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 
- OS Version: 

Steps to Reproduce:

1. Navigate to https://insiders.vscode.dev/github/microsoft/vscode/pull/187713
2. Open the Extensions viewlet and I see the stable version of GHPRI extension
    <img width="722" alt="image" src="https://github.com/microsoft/vscode/assets/3372902/b1746f15-8775-4c4c-aff6-f065a5088710">

**Comment by rzhao271** [comment]
Same on github.dev. The issue seems to be more that the pre-release isn't offered on web.

**Comment by sandy081** [comment]
Bug is in vscode.dev and therefore fix will be done there
