### ISSUE TITLE
Cannot use PHP snippets with $this

### ISSUE THREAD

**Issue by tyx** [Microsoft/vscode#18778]
- VSCode Version: 1.8.1
- OS Version: ubuntu 16.04 x64
- No extensions (the gif show extensions but I also test without)

Cannot use PHP snippet with [$this](https://github.com/Microsoft/vscode/blob/9ddc76267002754e9b603d2a98de84b16b1102d8/extensions/php/snippets/php.json#L202-L211) here is a gif to illustrate the problem : 
![vokoscreen-2017-01-19_11-50-42](https://cloud.githubusercontent.com/assets/245494/22104124/1fcd1a44-de3e-11e6-8c3f-b3fd7edfb24d.gif)

Steps to Reproduce:

1. Type `this`
2. Press `tab`
3. Write your property name

**Comment by nomad-software** [comment]
Looks like the dollar sign needs escaping in the snippet file.

**Comment by regs01** [comment]
there was pull request for that few last month. left unapproved. 
#22354

**Comment by roblourens** [comment]
Merged that PR to fix this.
