### ISSUE TITLE
Cannot install copilot pre-release on stable

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#187731]
Steps:

- Open VS Code Stable
- Go to Extensions View and search for `GitHub.copilot`
- Install Pre-release version
<img width="588" alt="image" src="https://github.com/microsoft/vscode/assets/10746682/326afad7-089f-4e75-b10a-eb168c5f3041">

🐛  
<img width="513" alt="image" src="https://github.com/microsoft/vscode/assets/10746682/a679dad1-890e-4a9d-8f0b-b6396864a76a">

Cannot install copilot pre-release on stable because the copilot chat pre-release is not available for stable. This should not block installing copilot extension

**Comment by isidorn** [comment]
Works great now -> verified.
