### ISSUE TITLE
terminal +/split button toggled when alt is pressed even when terminal panel is not focused

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#187729]
https://github.com/microsoft/vscode/assets/29464607/870c493d-9143-400b-b366-336e779c733f

**Comment by meganrogge** [comment]
This also happens in the editor's split button, so maybe it's fine? seems odd to me though

**Comment by meganrogge** [comment]
notice how the single tab's icon also changes when this happens 🐛

**Comment by Tyriar** [comment]
This is by design, sending to @joaomoreno for feedback.

**Comment by joaomoreno** [comment]
Reached out in chat.

**Comment by meganrogge** [comment]
Now I understand the context, so think this can be closed if it respects `workbench.reduceMotion`
