### ISSUE TITLE
VSCode useless in macos with M1/M2 chips

### ISSUE THREAD

**Issue by jonataslaw** [microsoft/vscode#187765]
Type: <b>Bug</b>

After the last update VSCODE was unusable on macbook with silicon chips.

When stopping the mouse pointer over any variable, it closes with the following error.

The window terminated unexpectedly (reason: 'crashed', code: '5')
We are sorry for the inconvenience. You can reopen the window to continue where you left off.

VS Code version: Code 1.80.0 (660393deaaa6d1996740ff4880f1bad43768c814, 2023-07-04T13:40:17.963Z)
OS version: Darwin arm64 22.5.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Max (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|3, 10, 12|
|Memory (System)|32.00GB (8.31GB free)|
|Process Argv|--crash-reporter-id d69a85ec-abfe-4656-b8df-6c41252ad0b0|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (70)</summary>

Extension|Author (truncated)|Version
---|---|---
config-generator|aka|1.0.1
to-typescript|ale|0.3.0
vscode-sqlite|ale|0.14.1
vscode-django|bat|1.10.0
dart-data-class-generator|Ben|0.5.5
better-toml|bun|0.3.2
simple-react-snippets|bur|1.2.7
gitignore|cod|0.9.0
styled-components-snippets|dan|0.4.0
dart-code|Dar|3.68.1
flutter|Dar|3.68.0
flutter-auto-import|dav|0.0.1
vscode-eslint|dba|2.4.2
python-environment-manager|don|1.0.4
python-extension-pack|don|1.7.0
css-flexbox-cheatsheet|dzh|3.3.3
vscode-html-css|ecm|1.13.1
vsc-material-theme-icons|equ|2.8.0
prettier-vscode|esb|9.19.0
jsonl-converter|F-l|0.1.2
kotlin|fwc|0.2.31
get-snippets|get|4.3.0
copilot|Git|1.96.255
vscode-github-actions|git|0.25.8
go|gol|0.39.0
md-graph|ian|0.1.1
styled-components-snippets|jon|0.10.0
vsc-python-indent|Kev|1.18.0
rainbow-csv|mec|3.7.0
gitignore|mic|1.0.1
vscode-docker|ms-|1.25.2
playwright|ms-|1.0.13
black-formatter|ms-|2023.4.1
python|ms-|2023.12.0
vscode-pylance|ms-|2023.7.10
jupyter|ms-|2023.6.1101941928
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.17
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-slideshow|ms-|0.1.5
remote-containers|ms-|0.299.0
live-server|ms-|0.4.9
makefile-tools|ms-|0.7.0
vscode-react-native|msj|1.11.1
awesome-flutter-snippets|Nas|3.0.3
autodocstring|njp|0.6.1
dart-exports|nol|0.2.0
convert-css-in-js|pau|1.1.3
swift-playgrounds|pie|0.1.1
material-icon-theme|PKi|4.28.0
remove-comments|pli|1.2.2
prisma|Pri|5.0.0
prisma-insider|Pri|31.0.2437
sqlite-viewer|qwt|0.2.5
saveall|ruf|0.0.4
rust-analyzer|rus|0.3.1583
vs-code-prettier-eslint|rve|5.1.0
markdown-preview-enhanced|shd|0.6.8
swift-lang|ssw|1.4.0
vscode-styled-components|sty|1.7.8
vscode-stylelint|sty|1.2.4
vscode-lldb|vad|1.9.2
intellicode-api-usage-examples|Vis|0.2.7
vscodeintellicode|Vis|1.2.30
full-react-snippets|wal|1.4.2
jinja|who|0.0.8
vscode-import-cost|wix|3.3.0
pretty-ts-errors|yoa|0.4.1
markdown-all-in-one|yzh|3.5.1
propertylist|zho|0.0.2

(6 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
vsccc:30610678
2e4cg342:30602488
pyind779:30671433
f6dab269:30613381
vscrp:30673768
pythonsymbol12:30671437
2i9eh265:30646982
showlangstatbar:30737416
vsctsb:30748421
pythonms35:30701012
03d35959:30757346
pythonfmttext:30731395
pythoncmvfstrcf:30756944
fixshowwlkth:30771522
showindicator:30785052
pythongtdpath:30769146
i26e3531:30780429
pythonnosmt12:30779714
pythonidxpt:30784022
pythonnocebcf:30776496
h7j2d465:30786200
dsvsc013cf:30784101

```

</details>

**Comment by jonataslaw** [comment]
<img width="1134" alt="Screenshot 2023-07-12 at 18 44 13" src="https://github.com/microsoft/vscode/assets/35742643/9b01b674-78b4-4555-92b5-6aa2bcc8f1e4">

**Comment by jonataslaw** [comment]
Note: This doesn't happen in the insider version, only in the stable version.

**Comment by gjsjohnmurray** [comment]
Please use the Start Extension Bisect command to investigate whether the problem is being caused by one of your extensions.

**Comment by jonataslaw** [comment]
Thanks for your response! I found the problem. The crash was caused by the "Import Cost v3.3.0" extension
