### ISSUE TITLE
Debugger gets stuck when starting debug adapter on non-existing runtime executable

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#18773]
- VSCode Version: 1.9.x (Insiders)
- OS Version: macOS

Steps to Reproduce:

1. open node-debug project and
2. edit package.json and break the `runtime` attribute, e.g. by adding an 'x' in `"runtime": "nodex"`.
3. lauch debug session "extension"
4. in the new window start debugging a node program 

Observe: 
This expected error message appears:
![2017-01-19_10-27-20](https://cloud.githubusercontent.com/assets/1898161/22101026/e2393ac0-de31-11e6-9b7e-1d317d4c790d.png)
After dismissing this, the debugger is still in a session where pressing the terminate button has no effect.

**Comment by isidorn** [comment]
Fixed by 631e76f
