### ISSUE TITLE
when writing bash scripts, VSCode doesn't recognize that ;& is a valid operator to end a case in a switch/case statement

### ISSUE THREAD

**Issue by emp4506** [microsoft/vscode#187719]
Type: <b>Bug</b>

example in bash 4.0 or later, im in a WSL workspace aswell:

```
case $1 in
  build_all)
    make all
    # ;& is a fall through operator that should be recognized by VSCode as a
    # valid operator but it is whining at me saying there is wrong syntax
    ;&
  debug)
    make all debug=yes
    ;;
  *)
    make all
    ;;
esac
```

VS Code version: Code 1.80.0 (660393deaaa6d1996740ff4880f1bad43768c814, 2023-07-04T15:06:02.407Z)
OS version: Windows_NT x64 10.0.19044
Modes:
Remote OS version: Linux x64 5.10.16.3-microsoft-standard-WSL2
Remote OS version: Linux x64 5.10.16.3-microsoft-standard-WSL2
Remote OS version: Linux x64 3.10.0-327.el7.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|13th Gen Intel(R) Core(TM) i7-13700H (20 x 2918)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.69GB (16.15GB free)|
|Process Argv|--crash-reporter-id fca7cecf-7642-41ac-9135-435a175e7188|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 5.10.16.3-microsoft-standard-WSL2|
|CPUs|13th Gen Intel(R) Core(TM) i7-13700H (20 x 2918)|
|Memory (System)|24.81GB (24.02GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 5.10.16.3-microsoft-standard-WSL2|
|CPUs|13th Gen Intel(R) Core(TM) i7-13700H (20 x 2918)|
|Memory (System)|24.81GB (24.02GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: watson.rockwellcollins.com|
|OS|Linux x64 3.10.0-327.el7.x86_64|
|CPUs|Intel(R) Xeon(R) CPU E5-1620 0 @ 3.60GHz (8 x 1199)|
|Memory (System)|3.63GB (2.80GB free)|
|VM|0%|
</details><details><summary>Extensions (20)</summary>

Extension|Author (truncated)|Version
---|---|---
remotehub|Git|0.60.0
gitpod-desktop|git|0.0.136
remote-containers|ms-|0.299.0
remote-ssh|ms-|0.102.0
remote-ssh-edit|ms-|0.86.0
remote-wsl|ms-|0.80.2
vscode-remote-extensionpack|ms-|0.24.0
azure-repos|ms-|0.36.0
remote-explorer|ms-|0.4.1
remote-repositories|ms-|0.38.0
remote-server|ms-|1.3.0
svn-scm|joh|2.17.0
csharp|ms-|1.26.0
python|ms-|2023.12.0
vscode-pylance|ms-|2023.7.10
cmake-tools|ms-|1.14.34
cpptools|ms-|1.16.3
cpptools-extension-pack|ms-|1.3.0
makefile-tools|ms-|0.7.0
cmake|twx|0.0.17

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscorecescf:30445987
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
vscaac:30438847
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
vsccc:30610678
2e4cg342:30602488
pyind779:30671433
f6dab269:30613381
pythonsymbol12:30671437
showlangstatbar:30737416
vsctsb:30748421
pythonms35:30701012
03d35959:30757346
pythonfmttext:30731395
pythoncmv:30756943
fixshowwlkth:30771522
hideindicator:30785051
pythongtdpath:30769146
i26e3531:30780429
pythonnosmt12:30779714
pythonidxpt:30784022
pythonnocebcf:30776496
h7j2d465:30786200

```

</details>

**Comment by RedCMD** [comment]
@jeff-hykin

**Comment by roblourens** [comment]
If you see an error, that would be from an extension. VS Code doesn't do any validation on bash

**Comment by emp4506** [comment]
What extension would that be if you know? I basically only have microsoft extensions installed and none of them are specifically for bash so if you know which one handles bash validation I'd like to reach out to them to see if they could do a quick fix for it.

**Comment by RedCMD** [comment]
@roblourens I think he means the syntax highlighting
![image](https://github.com/microsoft/vscode/assets/33529441/d36ed627-4521-4b31-b374-43d3e5019ef2)
`;&` is not recognized the same as `;;`

`debug)` should be the same colour as `build_all)`

@emp4506 
prob best to open an issue in https://github.com/jeff-hykin/better-shell-syntax

**Comment by emp4506** [comment]
Ok I opened a ticket there, hopefully it get's fixed soon as it seems to be a minor detail :)

**Comment by RedCMD** [comment]
https://github.com/jeff-hykin/better-shell-syntax/issues/63
