### ISSUE TITLE
accessible view vertically aligned incorrectly

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#187753]
it should match that of the quickpick

![Screenshot 2023-07-12 at 1 06 04 PM](https://github.com/microsoft/vscode/assets/29464607/a573ac37-6112-4ad5-bc11-a8c97a2225e6)

**Comment by mjbvz** [comment]
I confirmed the new alignment but it also looks strange IMO to have it render under the window control icons on smaller screen sizes:


![Image](https://github.com/microsoft/vscode/assets/12821956/3e332132-c090-4c60-969a-0696076a5fd2)


Quick picks aren't effected by this as they don't get wide enough to overlap

**Comment by meganrogge** [comment]
@mjbvz we're tracking that issue here #188838

**Comment by meganrogge** [comment]
and here #186520
