### ISSUE TITLE
dont see open file option on open editor

### ISSUE THREAD

**Issue by lrn79** [microsoft/vscode#187793]
Type: <b>Bug</b>

Kinda weird problem .line when I open a file I cant see any coe. even by open editor I cant open any kind of file like I could do before ... There was  5 Icon may be before  and now just 2 . could you please solve the issu as first as possible

VS Code version: Code 1.80.0 (660393deaaa6d1996740ff4880f1bad43768c814, 2023-07-04T15:06:02.407Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-7020U CPU @ 2.30GHz (4 x 2304)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|7.77GB (0.93GB free)|
|Process Argv|--crash-reporter-id a165f50e-ada9-46ba-a581-3511c3e4ae68|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (17)</summary>

Extension|Author (truncated)|Version
---|---|---
codesnap|adp|1.3.4
vscode-tailwindcss|bra|0.9.11
npm-intellisense|chr|1.4.4
path-intellisense|chr|2.8.4
vscode-eslint|dba|2.4.2
vscode-npm-script|eg2|0.3.29
vsc-material-theme-icons|equ|2.8.0
copilot|Git|1.96.255
search-node-modules|jas|1.3.0
react-vscode-extension-pack|jaw|1.0.0
snapcode|moy|1.1.0
jupyter|ms-|2023.6.1101941928
LiveServer|rit|5.7.9
autoimport|ste|1.5.4
code-spell-checker|str|2.20.5
JavaScriptSnippets|xab|1.8.0
ReactSnippets|xab|2.4.0

(5 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
vscaac:30438847
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
vscccc:30610679
282f8724:30602487
pyind779:30671433
89544117:30613380
vscrp:30673768
pythonsymbol12:30671437
showlangstatbar:30737416
vsctsb:30748421
pythonms35:30701012
a2ce3375:30757347
pythonfmttext:30731395
pythoncmv:30756943
fixshowwlkth:30771522
hideindicator:30785051
pythongtdpath:30769146
i26e3531:30780429
pythonnosmt12:30779714
pythonidxpt:30784022
pythonnoceb:30776495
e537b577:30786199
dsvsc013:30784100

```

</details>

**Comment by lramos15** [comment]
`F1` -> `Reset View Locations`
