### ISSUE TITLE
SQL block-comment syntax highlighting, breaks with /* in the comment's text

### ISSUE THREAD

**Issue by Zeda** [microsoft/vscode#187721]
Type: <b>Bug</b>

1. Open a file, set language to SQL
2. Place a block comment around text containing `/*` (minimal example: `/*/**/`)
3. Syntax highlighting treats everything after as a comment.

In the prior version that I had installed, this did not cause an issue with syntax highlighting. I use this as a trick to quickly block-comment a query:

```sql
/*
SELECT foo
FROM bar;
/**/
SELECT foo2  -- VS Code is now highlighting these lines
FROM bar2;   -- as a comment, even though it is not.
```

The first SELECT statement is commented, the second is not. In the recent update, the second query is no longer highlighted as code, it is highlighted as if it is commented. 

To uncomment the first, I simply comment out the first `/*` like so:
```sql
-- /*
SELECT foo
FROM bar;
/**/
SELECT foo2
FROM bar2;
```
Now both are uncommented. In this case, the updated VSCode is working as expected. 

As a side note, github's markdown is displaying everything as I would expect. Hopefully this wasn't something I broke or has already been fixed!

VS Code version: Code 1.80.0 (660393deaaa6d1996740ff4880f1bad43768c814, 2023-07-04T15:06:02.407Z)
OS version: Windows_NT x64 10.0.19044
Modes:
Remote OS version: Linux x64 4.1.12-124.73.2.el7uek.x86_64
Remote OS version: Linux x64 4.1.12-124.73.2.el7uek.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.87GB (5.74GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: prod|
|OS|Linux x64 4.1.12-124.73.2.el7uek.x86_64|
|CPUs|Intel(R) Xeon(R) Platinum 8260L CPU @ 2.40GHz (4 x 2393)|
|Memory (System)|5.56GB (2.63GB free)|
|VM|100%|

|Item|Value|
|---|---|
|Remote|SSH: test|
|OS|Linux x64 4.1.12-124.73.2.el7uek.x86_64|
|CPUs|Intel(R) Xeon(R) Platinum 8260L CPU @ 2.40GHz (4 x 2393)|
|Memory (System)|7.53GB (4.41GB free)|
|VM|100%|
</details>Extensions: none

**Comment by alexr00** [comment]
I think what you are doing is technically not supported:

"Nested comments are supported. If the /* character pattern occurs anywhere within an existing comment, it is treated as the start of a nested comment and, therefore, requires a closing */ comment mark. If the closing comment mark does not exist, an error is generated."
-- https://learn.microsoft.com/en-us/sql/t-sql/language-elements/slash-star-comment-transact-sql?view=sql-server-ver16#remarks
