### ISSUE TITLE
Language pack files for some extensions not found

### ISSUE THREAD

**Issue by yiliang114** [microsoft/vscode#187795]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 
版本: 1.81.0-insider
提交: d568855b2a4ef75716cdaa9a52da5315f5100a5d
日期: 2023-07-12T11:13:11.418Z
浏览器: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36
- OS Version: Mac os 12.2.1 (21D62)

Steps to Reproduce:

1. Open `https://insiders.vscode.dev/`
2. Switch  Configuration Display Language to `zh-cn`.
3. Open devtools after page auto refresh

![image](https://github.com/microsoft/vscode/assets/11473889/ab79b95f-3fe5-453a-bd20-14913c8e5237)

**Comment by yiliang114** [comment]
eg.  `https://github.vscode-unpkg.net/GitHub/vscode-pull-request-github/0.69.2023071212/extension/dist/browser/extension/bundle.l10n.zh-CN.json` does not exist, but  `https://github.vscode-unpkg.net/GitHub/vscode-pull-request-github/0.69.2023071212/extension/dist/browser/extension/bundle.l10n.zh-cn.json`  exists.

**Comment by TylerLeonhardt** [comment]
@yiliang114 thanks for working on this. The true fix for this issue actually needs to be in vscode.dev's source code. I've made that fix and this should work for you now.

Let me know if you still see any trouble.
