### ISSUE TITLE
Cursor position messed up editing long terminal lines

### ISSUE THREAD

**Issue by ivannp** [microsoft/vscode#187778]
Does this issue occur when all extensions are disabled?: Not sure - vscode always runs on Windows, but development and terminals are on a Linux box, using the SSH extension.

- VS Code Version: More than a year of versions
- OS Version: Windows (the development is in Linux, using the ssh extension)

Steps to Reproduce:

1. Run a longer command line in terminal
2. Go back to it via up arrow
3. Start editing using left and right arrows by pressing and holding down (to move say 10-20 characters left or right)
4. Edit something at that position
5. Hit enter to run the command

The command looked correct. But ... What I get as a result is often an error. Looking at the error and at the command (after another up arrow), it is pretty clear that the location the cursor was editing is different than what was displayed. I.e. the repetitive left/right arrows seem to mess up the interaction between the visualized buffer and the actual buffer.

**Comment by meganrogge** [comment]
might be fixed when https://github.com/microsoft/vscode/issues/186904 happens and the textarea is synced
