### ISSUE TITLE
Mocha test `suite` factory function should not be async

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#187718]
We discovered in https://github.com/microsoft/vscode/pull/187482#discussion_r1259551063 that some of our `suite` factory methods are async and can impact other tests as a result. After discussion, we have decided that we should limit `suite` factory methods so they cannot be async.

The first step is to write an eslint rule to find async suite factory methods.

The second step is to fix all the places this occurs:
- [x] src\vs\editor\contrib\find\test\browser\findController.test.ts @alexdima 
- [x] src\vs\workbench\contrib\search\test\common\extractRange.test.ts @Tyriar 
- [x] src\vs\workbench\contrib\terminal\test\common\history.test.ts @Tyriar 
- [x] src\vs\workbench\contrib\terminal\test\node\terminalProfiles.test.ts @Tyriar 
- [x] src\vs\workbench\contrib\terminal\test\browser\xterm\decorationAddon.test.ts @meganrogge 
- [x] src\vs\workbench\contrib\terminal\test\browser\xterm\shellIntegrationAddon.test.ts @Tyriar 
- [x] src\vs\workbench\contrib\terminalContrib\quickFix\test\browser\quickFixAddon.test.ts @meganrogge

**Comment by alexr00** [comment]
Once the PR for the eslint rule is in, you should just be able to see a warning by opening the file listed. To fix, make the second argument to the `suite` factory function sync (example: https://github.com/microsoft/vscode/pull/188380).

If you need to run async code during your suite setup, consider using a `suiteSetup`.

**Comment by alexr00** [comment]
Now that debt week is beginning, please consider taking a look at the errors above so that we can merge this new eslint rule and prevent more unreliable tests to be written!

**Comment by Tyriar** [comment]
There were no awaits so I think we can just remove them all which I did in https://github.com/microsoft/vscode/pull/189171, merging that will close this out.

**Comment by alexr00** [comment]
Great, thanks @Tyriar!

**Comment by Tyriar** [comment]
Oh opps, this will auto close. I see you will need to update the branch on https://github.com/microsoft/vscode/pull/188378 and merge in before this is closed.
