### ISSUE TITLE
vscode.dev Cannot open a file in a folder

### ISSUE THREAD

**Issue by yiliang114** [microsoft/vscode#187826]
ADD ISSUE DESCRIPTION HERE

Version: 1.80.0
Commit: 660393deaaa6d1996740ff4880f1bad43768c814
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36
Embedder: vscode.dev

I got a link to a file through the local vscode

![image](https://github.com/microsoft/vscode/assets/11473889/d0c2b555-5b40-4932-ba32-7ebe24d57b0f)

Reproduction steps: 
1. Use the local vscode to open any project,
2. Right-click the file, select Share, and select `Copy vscode.dev link`
3. Paste it into browser to open `vscode.dev`
4. After the vscode is loaded, the file path carried by the url will be lost and cannot be recognized.
5. The same problem on `insider.vscode.dev`

![bug6](https://github.com/microsoft/vscode/assets/11473889/ed038f8f-a45c-41af-bb87-e79c8d5d23e2)

**Comment by yiliang114** [comment]
This problem is more common when sharing a file with others. Or is there any other good way？

**Comment by joyceerhl** [comment]
What is the result of `git remote -v` for you? I'm guessing you have two remotes, we're probably picking the wrong one when constructing the link

**Comment by yiliang114** [comment]
hi @joyceerhl I do have two remotes, but in fact, the link I copied carries the name of the source project group. just like 

![image](https://github.com/microsoft/vscode/assets/11473889/71edef72-310c-4d0d-9779-f058a4c3aae4)

And here is my remotes
![image](https://github.com/microsoft/vscode/assets/11473889/368fcc45-d930-4aa4-9ea1-10a8006c2afb)

**Comment by joyceerhl** [comment]
Thanks for confirming!

**Comment by joyceerhl** [comment]
@yiliang114 I cannot repro the behavior you describe. This is what I tried:

1. Have two remotes, `origin` is https://github.com/microsoft/vscode.git and `joyceerhl` is https://github.com/joyceerhl/vscode
2. Create a feature branch that is published to `joyceerhl`
3. Copy vscode.dev link from the editor gutter context menu
4. The link that is copied is for the joyceerhl remote

This is the relevant code which picks the remote that your branch was published to: https://github.com/joyceerhl/vscode/blob/5653420433692dc4269ad39adbc143e3438af179/extensions/github/src/links.ts#L152-L153

Can you please share your setup steps if they are different from the above steps? Thanks!

**Comment by yiliang114** [comment]
@joyceerhl 
Sorry, my previous description may not be clear enough. Is our difference due to the default remote branch?

![image](https://github.com/microsoft/vscode/assets/11473889/6993a6c5-ddb1-4b3b-ac3c-df94fa8a919c)

My previous operation was to clone the source of Microsoft first:
1. git clone `https://github.com/microsoft/vscode.git`
2. then git remote add `https://github.com/yiliang114/vscode.git`

**Comment by yiliang114** [comment]
> https://github.com/joyceerhl/vscode/blob/5653420433692dc4269ad39adbc143e3438af179/extensions/github/src/links.ts#L152-L153

https://github.com/joyceerhl/vscode/blob/5653420433692dc4269ad39adbc143e3438af179/extensions/github/src/links.ts#L149

Maybe `gitRepo.state.remotes.find` here use `find` and only the first remote was matched. So, in my case, the copied link is the remote of Microsoft.

**Comment by joyceerhl** [comment]
In the linked code AFAICT we would still loop over all the remotes, favoring a perfect match for the branch's upstream and falling back to one of the remotes if any are available. We don't match on just the first remote because the predicate we pass to `Array.prototype.find` always returns `undefined`.

I tried matching your setup and copying links still works as expected for me:
<img width="962" alt="image" src="https://github.com/microsoft/vscode/assets/30305945/f0b8ab78-ff37-4e62-908b-7adfaadc3153">

Does this happen for you on all branches or just the `magnificent-silkworm` branch? Can I double check that you are using the `Copy vscode.dev Link` context menu command from the editor gutter (right clicking on the editor line number)?

**Comment by yiliang114** [comment]
> In the linked code AFAICT we would still loop over all the remotes, favoring a perfect match for the branch's upstream and falling back to one of the remotes if any are available. We don't match on just the first remote because the predicate we pass to `Array.prototype.find` always returns `undefined`.
> 
> I tried matching your setup and copying links still works as expected for me: <img alt="image" width="962" src="https://user-images.githubusercontent.com/30305945/254085736-f0b8ab78-ff37-4e62-908b-7adfaadc3153.png">
> 
> Does this happen for you on all branches or just the `magnificent-silkworm` branch? Can I double check that you are using the `Copy vscode.dev Link` context menu command from the editor gutter (right clicking on the editor line number)?

It makes me a little confused. For me, the same is true for other branches, it will find Microsoft's remote instead of my own remote.

![bug8](https://github.com/microsoft/vscode/assets/11473889/1f39af01-1963-40ff-990b-a164847f7218)

Before pushing the new branch, this is the effect. After pushing the new branch to my remote, the link copied from the right-click menu is also Microsoft's remote.

![bug9](https://github.com/microsoft/vscode/assets/11473889/569731ae-c300-41d1-a53b-e6193fbbb658)

**Comment by sandy081** [comment]
@joyceerhl Does the steps in description are up to date to verify or has any other specific steps?

**Comment by joyceerhl** [comment]
1. Have a desktop git repo open with two remotes
2. From the terminal, create and push a branch to one of the remotes
3. Copy a link from the editor gutter
4. Ensure the link is valid
