### ISSUE TITLE
Diff editor: reverting a change expands the following collapsed region

### ISSUE THREAD

**Issue by rjra100** [microsoft/vscode#187844]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.80.0
- OS Version: Windows 10 (normally running with WSL + Docker, but behaves the same regardless)

I'm really liking the recent changes to the diff editor, but this is a bit of an annoyance which somewhat spoils the collapse unchanged regions feature. Steps to Reproduce:

1. Create a file (e.g. [dummy.txt](https://github.com/microsoft/vscode/files/12040462/dummy.txt))
2. Create a modified version of the same file with two changes some distance apart (e.g. [dummy2.txt](https://github.com/microsoft/vscode/files/12040472/dummy2.txt))
3. "Compare Selected" (or otherwise compare two files with separated changes): 
![Capture](https://github.com/microsoft/vscode/assets/75089897/14b9e29c-0b20-4684-8cd6-e8fd8495a480)
4. Revert the first change. The collapsed region of unmodified code immediately after the reverted change expands itself. 
![Capture2](https://github.com/microsoft/vscode/assets/75089897/ee385b30-cf1a-464c-8767-40bb0547bd55)

In the example, only a few lines get expanded, but this is a bit irritating when the unchanged region is large, because it pushes the next difference off the bottom of the window: now I have to navigate to find it, when it was previously right there in the window. 
Ideally, reverting a change would probably not change the collapsed state of anything, so the next diff would remain where it is in the window. On the other hand, after the revert there's a bigger section of identical content. Either behaviour leaves the window in a state inconsistent with what you'd get by closing and reopening it. I believe what most other diff editors (Vimdiff and Beyond Compare are the ones I've most experience with recently) do in a similar situation is to recalculate the previous "identical" section - which can be done by hand by un-collapsing and re-collapsing that, if there is one:
![Capture3](https://github.com/microsoft/vscode/assets/75089897/24219a6a-e677-4b5e-af18-40fd35e45317)
That does move the subsequent diff upwards in the window, but it does leave it visible (and, indeed, closer to the where the mouse will be after clicking the revert button). When selectively reverting a bunch of changes, that'd streamline things quite a bit.

**Comment by hediet** [comment]
At the moment, the hidden areas try to not hide something that was previously visible when the diff updates.
Because an entire Hidden Lines area disappears when a change is reverted, anaother Hidden Lines area has to account for that.

This is important when typing: When you manually "revert" a change by inserting back some deleted characters, the line the cursor is in shouldn't disappear out of a sudden.

I think we should try to keep Hidden Lines areas, even if between two of them is no change.
