### ISSUE TITLE
Remove unused audio cues

### ISSUE THREAD

**Issue by hediet** [microsoft/vscode#187837]
These audio cues do not seem to be used:

https://github.com/microsoft/vscode/blob/d40162dd41d14dfc23b3026edc0ff4b9a8eaeeb2/src/vs/platform/audioCues/browser/audioCueService.ts#L362-L380

They appear in `Help: List Audio Cues` and I'm sure the sound files blow up the installer size.

**Comment by meganrogge** [comment]
these are used when this is invoked

https://github.com/microsoft/vscode/blob/d7bdb0a08a3716a37ba958762be0091d519c01bc/src/vs/platform/audioCues/browser/audioCueService.ts#L60

**Comment by hediet** [comment]
Ahh, what threw me off are the 0 references:

![Code_-_Insiders_2Bb0r7ckyS](https://github.com/microsoft/vscode/assets/2931520/082f48d3-d6cf-4acb-8bb1-ac11d9506b5a)

I think we should allow audio cues to have random sounds, getting rid of the `groupId`.
