### ISSUE TITLE
Classes for styling - incompatible changes.

### ISSUE THREAD

**Issue by Webtakeme** [Microsoft/vscode#18786]
- VSCode Version: 1.9.x (Insiders) January 2017
- OS Version: all os

Steps to Reproduce:

1. Update VSCode to **January 2017 build (insiders)**. All previous build is fine.
2. Open "help"-->"Toggle developer tools"-->inspect different type of rendered code element (for example in javascript - const, let, class, import, function, block, expression ... etc). **Like "\<span class="token js meta var expr storage type">const\</span>"**.

Before january build each peace of code (each \<div>) in vscode had _special class on rendered element_. There was special class for each type of code element (constants, imports, object literal, keyword, variable, assignment, definition, brace, brace round, storage, punctuation, method, declaration ... ... ....). It system give us (developer and user) _huge possibility to customize our code_ (like extension "vscode-custom-css") and make themes for vscode. One of great advantages of vscode - is excellent font rendering.

The PROBLEM is now (from january build) all this system is broken. **Instead of huge additional classes we got only  small piece of classes:**

_.mtk1 { color: #B3B3D4; }
.mtk2 { color: #1D1D26; }
.mtk3 { color: #504E6E; }
.mtk4 { color: #CC66FF; }
.mtk5 { color: #00D364; }
.mtk6 { color: #FF3399; }
.mtk7 { color: #F8F8F0; }
.mtk8 { color: #00BFFF; }
.mtk9 { color: #FFCC66; }
.mtk10 { color: #00CED1; }
.mtki { font-style: italic; }
.mtkb { font-weight: bold; }
.mtku { text-decoration: underline; }_

and that's all we got now (no all the stuff that I describe before). See attached photo for compare "before" and "after".
**13 classes instead of about 40 and they combination** :-1: 

I really understand that in this way vscode creators make renders much more faster in the editor....
and some times we will have breaking changes... but you remove all this class system (EXTREMELY REDUCE CUSTOMIZATION POSSIBILITY )

**PLEASE BRING BACK CLASS SYSTEM !!!** :+1: 

Old **excellent** "class system":

![before-changes-with-class-system](https://cloud.githubusercontent.com/assets/14540860/22109568/f9c907a4-de60-11e6-9e20-36590927e056.png)

New **poor** classes:

![after update-no-classes](https://cloud.githubusercontent.com/assets/14540860/22109569/f9ce1af0-de60-11e6-90b4-7760568a03f7.png)

Feeling like moved _**from IDE**_ (IntelliJ IDEA‎, Visual Studio ....) _**to notepad**_ :-1: 

Code before update (each type of code **properly colorized**) + additional font-family for some type of code.

![before-update](https://cloud.githubusercontent.com/assets/14540860/22109076/d65b076a-de5e-11e6-8671-6f8865e79d03.png)

Code after update (**poor colorization** - half of code in the same color). Greeting for people with bad vision :(

![after-update](https://cloud.githubusercontent.com/assets/14540860/22109075/d657b4d4-de5e-11e6-8798-e4e6947d85df.png)

**PLEASE BRING BACK CLASS SYSTEM !!!** :+1:

**Comment by d3viant0ne** [comment]
I have to agree here. I'm not sure where this `feature` is coming from but it's going to break pretty much every theme in existence so one would hope there is a really good reason why.

That said, if you plan on breaking all the themes, I would suggest documentation on what is changing and providing at least minimal documentation on how to migrate.

**Comment by alexandrudima** [comment]
Please read https://github.com/Microsoft/vscode/issues/18357#issuecomment-271709334 and also follow the links in there.

It explains at length everything.
