### ISSUE TITLE
Cannot copy all content from debug console, only visible selected output is copied.

### ISSUE THREAD

**Issue by LambiekNL** [Microsoft/vscode#18788]
- VSCode Version:
Version 1.8.1
Commit ee428b0eead68bf0fb99ab5fdc4439be227b6281
Date 2016-12-19T14:41:20.664Z
Shell 1.4.6
Renderer 53.0.2785.143
Node 6.5.0

- OS Version:
Linux 3.13.0-24-generic #47-Ubuntu SMP Fri May 2 23:30:00 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

Steps to Reproduce:

1. Start debug session with more than a screen of output
2. (Try to ) select all output and copy to clipboard
3. Open text editor and paste clipboard

Result:

Only visible output in debug console is copied to clipboard. Even when it seems that all text is selected. You can scroll and see text is selected but when text is copied, only visible part will be in the clipboard.

**Comment by isidorn** [comment]
Dup of https://github.com/Microsoft/vscode/issues/2163
