### ISSUE TITLE
Add info about sticky scroll to editor accessibility help menu

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#187859]
related to #186659

**Comment by meganrogge** [comment]
To verify, focus an editor. Use `alt+f1` to open the accessibility help dialog. Ensure that there's info about focusing sticky scroll. Set a keybinding for the command to focus sticky scroll. Open the help dialog again and ensure that is included in the dialog. Disable sticky scroll. Ensure that info is no longer in the dialog.

**Comment by rzhao271** [comment]
After I disable sticky scroll, the accessibility help dialog still mentions Focus Sticky Scroll.

**Comment by meganrogge** [comment]
@rzhao271 did you close and reopen the help dialog? that's what is required here
