### ISSUE TITLE
Latest insiders don't have cmd.exe available as integrated terminal

### ISSUE THREAD

**Issue by pocesar** [microsoft/vscode#187866]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.81.0-insider (user setup)
- OS Version: Windows_NT x64 10.0.22621

> Version: 1.81.0-insider (user setup)
> Commit: dc142e4cd111b8f370d0549d8c207df7de55facd
> Date: 2023-07-14T10:43:06.630Z
> Electron: 22.3.14
> ElectronBuildId: 21893604
> Chromium: 108.0.5359.215
> Node.js: 16.17.1
> V8: 10.8.168.25-electron.0
> OS: Windows_NT x64 10.0.22621

![image](https://github.com/microsoft/vscode/assets/461084/694731bc-3bfc-4748-b441-1cec5e28fd0c)

It's also defaulting to Powershell

**Comment by meganrogge** [comment]
this is working for me - what's the path to command prompt for you?

**Comment by pocesar** [comment]
@meganrogge 
![image](https://github.com/microsoft/vscode/assets/461084/531805cc-0878-4a8c-a0ad-30e05bacadf2)

**Comment by meganrogge** [comment]
Yeah I'm asking where is cmd.exe on your computer ? 

Clearly not at the place we expect it to be

**Comment by pocesar** [comment]
@meganrogge PEBCAK, I deleted the C:\Windows\System32 from the PATH, all good
