### ISSUE TITLE
Debugger dropdown can be hidden and cannot be shown again

### ISSUE THREAD

**Issue by StarkillerX42** [microsoft/vscode#187873]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.80.1
- OS Version: MacOS Ventura 13.2.1

Steps to Reproduce:

1. On the lefthand side, go to the "Run and Debug" tab.
2. Right click on the dropdown menu
3. Click "Hide 'start debugging'"

I did this accidentally, and I can't figure out how to get the debug dropdown menu to come back. Without being able to pick which run configuration I want to run, it's almost impossible to use the debugger, although I can still press F5 and run the current (probably first) debug configuration.

The "Hide 'start debugger'" probably shouldn't even be a button, I'm not sure why you would use the debug panel without the dropdown as well.

**Comment by Hauntec** [comment]
Encountered this problem today - Posting here with bandaid fix for anyone currently affected (and might help dev to narrow down problem) -
Open the global storage `state.vscdb` file (Path on MacOS is _~/Library/Application Support/Code/User/globalStorage/state.vscdb_) in your preferred DB Browser (I use SQLite) and find the `menu.hiddenCommands` key. If you have the same bug that I had causing this, it will be an object that includes `{ workbench.action.debug.selectandstart }`. Just set this to an empty object, save the vscdb file and when you reopen VSCode you'll have the select and start dropdown back. :)
