### ISSUE TITLE
Debugger not showing value of variables

### ISSUE THREAD

**Issue by EHBrant** [Microsoft/vscode#18783]
- VSCode Version: Code - Insiders 1.9.0-insider (215a0af33046d3940e665d46ecaeac9623f2f769, 2017-01-19T07:12:16.209Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions:

|Extension|Author|Version|
|---|---|---|
|PowerShell|ms-vscode|0.8.0|

---

Steps to Reproduce:

Hello,
I am new to VS Code and want to use it to write/debug PowerShell scripts.  I normally use PowerGUI IDE for PowerShell, but want to move over to VS Code.

A simple but very useful feature in PowerGUI is the ability to see the value and type of any variables once they have been populated. Therefore if you write and execute some simple code like the following

$A = 10
$B = 1,2,3,4

once executed you can hover over the variable in question with your mouse and it will tell you the TYPE and current value/s of the variable.

I do not see this in VS Code and when using the debugger the variables pane (top left) is blank e.g. it also does not list any variables or their values.

It this because the PowerShell extension simply does not support this? 

Being able to see the current value (if any) of any variables in your script (once executed once) is a must have I would say otherwise it makes it very difficult indeed to debug a script.

Also if I set a break-point and start the debugger, the only option I get is to 'stop' the debugger and when I do I receive the following error: Debug adapter process has terminated unexpectedly
again I do not see the value of any variables.

Please advise
Thanks in advance
ErnestBrant@outlook.com

**Comment by weinand** [comment]
This is the PowerShell extension. Moving.

**Comment by weinand** [comment]
This issue was moved to PowerShell/vscode-powershell#452
