### ISSUE TITLE
terminal accessible buffer cycles through autocompletions when entering/exiting it without pressing enter while there's input

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#187875]
Reported by @rperez030

1. Open the terminal by pressing CTRL +` with screen reader mode on and nVDA running.
2. Type a command that generates some output such as 'ls'.
3. Press shift +Tab to move focus to the accessible buffer and check that the output is there. This step is not required but this is the way I'm doing it.
4. Press Tab to  move focus back in the input field and type 'cle'. The idea is to type a clear command but incomplete.
5. Without pressing Enter, press shift +Tab to move back to the accessible buffer.
6. explore the output. You will find that the string 'cle' is at the end, possibly folowed by something else.
7. Press Tab to move focus to  move back to the input field. The string 'cle' which you typed before appears to not be there anymore. At this tyme you can type 'clear' and press enter.
8. Instead of excecuting the clear command which you just typed, you will find that a command which could be something like this: 'Clear-WindowsCorruptMountPointclear' was excecuted. In summary, if we start typing something in the input field, and rather than pressing Enter we press shift +Tab to review the buffer, the entire flow breaks. 

This happens because `shift+tab` cycles through autocompletions for some programs/shells

https://github.com/microsoft/vscode/assets/29464607/e9957ab3-10a5-4837-b2c9-d4e6ed2fadf3

**Comment by meganrogge** [comment]
I believe this can be addressed when https://github.com/microsoft/vscode/issues/186904 is handled - likely same root cause - us not syncing with xterm's text-area. We might additionally need to do something special like `alert` with the content when the normal terminal is re-entered and there's input (it's changed?)

@Tyriar correct me if i'm misunderstanding

**Comment by jvesouza** [comment]
I couldn't reproduce using orca in my fedora environment. I typed 'cle', pressed shift+tab, inspected the contents of the accessible buffer, pressed tab, typed 'ar' and pressed the enter key. The clear command ran with no errors.

**Comment by meganrogge** [comment]
@jvesouza thanks for the input. This issue only occurs when the shell that is used has auto completion configured - whether built in as is the case for pwsh or via a plugin like oh-my-zsh for zsh

**Comment by Tyriar** [comment]
@meganrogge it looks unrelated to syncing of the textarea. The shift+tab is being passed through to the shell:

 
<img width="938" alt="Screenshot 2023-07-13 at 6 05 36 pm" src="https://github.com/microsoft/vscode/assets/2193314/590c2ea1-64e0-4d0d-828d-1fd8f378b18f">

**Comment by meganrogge** [comment]
I think we want it to pass through to the shell so autocompletions don't break for a user. 

What I was suggesting/ wondering is when we have synced the text area, if using arrow keys to navigate the content in the terminal input will work correctly and be read by the screen reader just as it will when pressing backspace works. 

Because the issue currently with this is from the screen reader user's perspective, when back in the terminal, there is no input (since it isn't announced when using arrow keys)

**Comment by meganrogge** [comment]
I believe this is happening because the textarea value is cleared on `blur`

https://github.com/meganrogge/xterm.js/blob/f4f4b90fac80b5d88ee292de3ac53205f23c8004/src/browser/Terminal.ts#L305

**Comment by meganrogge** [comment]
so maybe we should call `_syncTextArea` on focus of the text area?

**Comment by meganrogge** [comment]
And would the historical command issue be fixed simply by calling _syncTextArea when up arrow is used?

**Comment by Tyriar** [comment]
I don't actually see a way to make zsh's autocomplete accessible, instead the solution to that imo is native autocomplete https://github.com/microsoft/vscode/issues/154662

Also note that xterm.js knows nothing about shell integration currently, sync text area only positions the textarea so things like IMEs appear in the right spot:

https://github.com/xtermjs/xterm.js/blob/f79e9a1951c2f9fca8f5e1ba735555a1e7d4cb74/src/browser/Terminal.ts#L314-L338

**Comment by jvesouza** [comment]
It's working as I expected.

**Comment by meganrogge** [comment]
We can close this now since we're no longer using `Shift+Tab`
