### ISSUE TITLE
what's wrong with this ? errors : bugs

### ISSUE THREAD

**Issue by xgqfrms-GitHub** [Microsoft/vscode#18781]
why it auto format with error ?

https://twitter.com/xgqfrms/status/822054908551524352

**Comment by xgqfrms-GitHub** [comment]
![vscode-babel-format-error](https://cloud.githubusercontent.com/assets/18028768/22107216/8cde2b2a-de87-11e6-8a9b-7b363dab826c.gif)

**Comment by mjbvz** [comment]
@xgqfrms-GitHub From the gif, it is not clear what actions are being taking. Can you please list the steps to reproduce this.

**Comment by xgqfrms-GitHub** [comment]
settings.json
```
// Place your settings in this file to overwrite the default settings
{
    "editor.tabCompletion": true,
    "editor.mouseWheelZoom": true,
    "editor.lineHeight": 24,
    "editor.fontSize": 16,
    "editor.formatOnSave": false,
    "html.format.wrapLineLength": 80,
    "editor.wrappingColumn": 80,
    "html.format.enable": false,
    "html.format.extraLiners": "/body",
    "workbench.statusBar.visible": true,
    "editor.renderWhitespace": "all"
}
```

**Comment by xgqfrms-GitHub** [comment]
After I change the compiler from Javascript (babel) to  Javascript React , everything  is OK!

# vs-babel-format-error

![vs-babel-format-error react](https://cloud.githubusercontent.com/assets/18028768/22175460/f319573a-e02f-11e6-8d84-460245b763b3.gif)
