### ISSUE TITLE
Prevent opening new editor group when using focusNextGroup

### ISSUE THREAD

**Issue by sgronblo** [Microsoft/vscode#18785]
- VSCode Version: Version 1.8.1 (1.8.1)
- OS Version: MacOS 10.12.2

Steps to Reproduce:

1. Have less than three editor groups open with your cursor in the rightmost editor group
2. Activate command focusNextGroup
3. A new editor group will open to the right of your current editor group and the cursor will jump over there

It would be nice to be able to prevent this unwanted opening of an additional editor group which already has shortcuts like cmd+2 or cmd+3 if you really need one more. With the current behavior I end up opening and having to close the rightmost editor group multiple times in a day.

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/12833
