### ISSUE TITLE
Integration test failure:  task should start and shutdown successfully

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#187831]
Build: https://dev.azure.com/monacotools/a6d41577-0fa3-498e-af22-257312ff0545/_build/results?buildId=223029
Changes: https://github.com/Microsoft/vscode/compare/c719be7...429d6d2

```
  1) vscode API - tasks
       Tasks
         CustomExecution
           task should start and shutdown successfully:
     Error: Timeout of 60000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/Users/runner/work/1/s/extensions/vscode-api-tests/out/singlefolder-tests/workspace.tasks.test.js)
      at listOnTimeout (node:internal/timers:559:17)
      at processTimers (node:internal/timers:502:7)
```

**Comment by meganrogge** [comment]
I think this is probably because we now wait for all supported executions when `runTask` is called or timeout. Something to keep my 👁️ on

**Comment by meganrogge** [comment]
I cannot reproduce and haven't seen this again - I fixed a few things that could've been causing this. Will reopen if it's reported again
