### ISSUE TITLE
VS Code won't open

### ISSUE THREAD

**Issue by sambluca** [Microsoft/vscode#18789]
When I open VS Code it immediately crashes and closes without an explanation of the error being shown. Can anyone help

- VSCode Version: 1.8
- OS Version: 10.11.6

Steps to Reproduce:

1. Open VS Code
2. Uninstall VS Code
3. Reinstall

![giphy](https://cloud.githubusercontent.com/assets/13347652/22112102/b4762990-de59-11e6-9d3a-f1548e572ace.gif)

**Comment by bpasero** [comment]
@sambluca can you check in activity monitor if there is any running Code process hanging around maybe?

**Comment by sambluca** [comment]
@bpasero there was lots of Code Helpers, closed them all, reopened Code and it does the same again

**Comment by sambluca** [comment]
@bpasero I tried turning it off and on again (I had already tried that but I decided to try it again) and this time it has decided to open. Thanks for the help.
