### ISSUE TITLE
SignatureHelpProvider gets confused with similar parameter labels

### ISSUE THREAD

**Issue by Janne252** [Microsoft/vscode#18782]
SignatureHelpProvider seems to get confused with similar parameter labels and results in a weird render of the parameters:
![](https://raw.githubusercontent.com/Janne252/vscode-test-signatureHelpProvider/master/images/issue_before.png)
It should look like this:
![](https://raw.githubusercontent.com/Janne252/vscode-test-signatureHelpProvider/master/images/issue_after.png)

- VSCode Version: 1.8.1
- OS Version: Windows 10 Pro, 1607

Steps to Reproduce:

The "issue" can be reproduced with this test extension: [Janne252/vscode-test-signatureHelpProvide](https://github.com/Janne252/vscode-test-signatureHelpProvider) (see the readme for additional steps)

**Comment by jrieken** [comment]
Yeah, we do a simple `String.indexOf` which isn't very clever...

**Comment by Janne252** [comment]
I was going through my old repositories on github and came accross this issue. Looks like the issue has been fixed at some point. Closing.
