### ISSUE TITLE
workspace settings does not override specific exclude pattern of global settings

### ISSUE THREAD

**Issue by StoryDevOffical** [microsoft/vscode#187817]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version:  1.80.0
- OS Version: x64 W10

Steps to Reproduce:

1. Exclude all subFF in all node_modules in global settings.json   
// it works well and hide all subFF of each node_modules
```
"files.exclude": {
    "**/node_modules/*/": true
}
```
2. Set this exclude to false in workspaces settings
// it works well and display all subFF of each node_modules (so global settings overloaded)
```
"files.exclude": {
  "**/node_modules/*/": false,
}
```
3. Set this exclude to false for specific subfolder in workspaces settings
// **it does not works and all subFF of specific node_modules still excluded**
```
"files.exclude": {
  "sub_folder/node_modules/*/": false,
}
```

**Comment by rzhao271** [comment]
I'm able to reproduce this issue on the latest Insiders using the User and Workspace setting.json files.

**Comment by bpasero** [comment]
Settings that have an object form (such as this one) are merged on each level, so if you want to disable a pattern from one layer you need to explicitly repeat it again on that layer set to `false`.
