### ISSUE TITLE
TypeScript busy/blocked when typing a new import

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#18792]
* open a TypeScript file and JSON file from our workspace
* make sure hovers in both work
* in the TS file, *type* an import
* 😴 TypeScript is dead for ~45seconds, JSON still alive which hints to me there is a problem with tsserver

![jan-19-2017 16-47-00](https://cloud.githubusercontent.com/assets/1794099/22113557/f0463912-de66-11e6-844d-81e7f4002a96.gif)

**Comment by joaomoreno** [comment]
bump @mjbvz

**Comment by mjbvz** [comment]
Closing as duplicate of #20815
