### ISSUE TITLE
.m4a audio file cannot be played

### ISSUE THREAD

**Issue by lichangwei123** [microsoft/vscode#187976]
.mp3 audio file can be played, but .m4a audio file cannot be played. why?

![image](https://github.com/microsoft/vscode/assets/46671582/f4e4e12c-b401-45df-966f-8c39dabacadd)

**Comment by mjbvz** [comment]
We only support the following audio formats: https://code.visualstudio.com/api/extension-guides/webview#supported-media-formats

**Comment by lichangwei123** [comment]
> We only support the following audio formats: https://code.visualstudio.com/api/extension-guides/webview#supported-media-formats

Can you tell me why

**Comment by lichangwei123** [comment]
> .mp3 audio file can be played, but .m4a audio file cannot be played. why?

What do I need to do if I want to support.m4a audio files on my side
