### ISSUE TITLE
Git: bring back modal dialog when asking for confirmation

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#18790]
We should expose real API to bring up a modal dialog and use it in this case:

![image](https://cloud.githubusercontent.com/assets/900690/22112659/114b3f70-de64-11e6-9f64-522f6eb31c7e.png)

/cc @jrieken 

I can look into this / provide a PR if there are no objections.

**Comment by joaomoreno** [comment]
👍 

But the API might not be so easy to nail down

**Comment by jrieken** [comment]
yeah....

**Comment by bpasero** [comment]
```typescript
export interface IConfirmationMessage {
   message: string;
   detail?: string;
   primaryButton?: string;
}

export function showConfirmationMessage(confirmation: IConfirmationMessage): Thenable<boolean>;
```

Seems like what git is using [here](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/git/browser/gitActions.ts#L426).

**Comment by joaomoreno** [comment]
I would actually keep it simpler and [mimic the DOM](https://developer.mozilla.org/en-US/docs/Web/API/Window/confirm):

```typescript
namespace window {
  export function confirm(message: string): Thenable<boolean>;
}
```

**Comment by bpasero** [comment]
Not sure I agree we should align with the DOM. We already have `showInfoMessage`, `showWarningMessage` etc. An no matter what, we need the button label to be overidden.

**Comment by joaomoreno** [comment]
```typescript
export type ChoiceType = 'none' | 'info' | 'error' | 'question' | 'warning';

export interface ChoiceDialogOptions {
	type?: ChoiceType;
	message: string;
	detail?: string;
	defaultChoice: string;
	otherChoices?: string[];
}


export namespace window {
	export function showChoiceDialog(options: ChoiceDialogOptions, token?: CancellationToken): Thenable<string | undefined>;
}
```

**Comment by jrieken** [comment]
A couple of things:

* We have used enums over or-string types
* We have often used explicit names over enums, like `show[Information|Warning|Error]Message`
* No need for the cancelation token, the promise should return with `undefined` when the message is being dismissed

**Comment by bpasero** [comment]
@joaomoreno awesome, I think what is missing is to declare the option which is the "`cancelChoice`".

**Comment by jrieken** [comment]
Alternative proposal is to add options the `showXYZMessage` functions to allow for `{ modal: true }`. Pros are that it is similar to existing API and gives full flexibility, Con is that the signature go like `...items` and that another set of overloads is needed. Something like

```ts
export interface MessageOptions {
  modal: boolean;
}

export function showWarningMessage<T extends MessageItem>(message: string, options: MessageOptions, ...items: T[]): Thenable<T | undefined>;

```

**Comment by joaomoreno** [comment]
@jrieken I'm finding it hard to accommodate everything into that method interface.

Check out this Electron API doc snippet:

> cancelId Integer (optional) - The value will be returned when user cancels the dialog instead of clicking the buttons of the dialog. By default it is the index of the buttons that have “cancel” or “no” as label, or 0 if there is no such buttons. **On macOS and Windows the index of the “Cancel” button will always be used as cancelId even if it is specified.**

I can't implement the `isCloseAffordance` as we currently have it due to this restriction. The button must be called `Cancel`.

Additionally, the current API doesn't let callers decide what's the default option to take when the user simply presses <kbd>Enter</kbd>. Should we then come up with a `isAcceptAffordance`? What would that mean in a non-modal message?

**Comment by jrieken** [comment]
It's conflicting goals: simple, minimal API vs expressiveness. My thinking is that modal dialogs aren't used very frequent and therefore don't get large API exposure. Let's not yet give up. Some ideas

* we always make the first element the 'enter' element? or we don't support enter?
* we ignore the `isCloseAffordance` or use the `string` variant and have an option expressing if cancel is supported or not

**Comment by joaomoreno** [comment]
> we always make the first element the 'enter' element? or we don't support enter?

@bpasero actually just gave me that idea too! I like it.

> we ignore the isCloseAffordance or use the string variant and have an option expressing if cancel is supported or not

We could also do the following:

- Just like the non-modal variant, if no `isCloseAffordance` is in any of the options, we provide a `Cancel` option.
- Otherwise, pressing <kbd>Escape</kbd> just won't work and the user will have to <kbd>Tab</kbd> his way out, or use the mouse.

**Comment by joaomoreno** [comment]
PR in #19717, care to review?
