### ISSUE TITLE
VB.NET Windows Forms App (.NET Core) Project Issues after Visual Studio Update

### ISSUE THREAD

**Issue by winter001122** [microsoft/vscode#187966]
Hello,

I've been experiencing an issue with Visual Studio ever since updating to the latest version. When I open a VB.NET Windows Forms App (.NET Core) project, the Design View interface disappears and the Solution Explorer shows "0 projects", as if no project is open.

Interestingly, when I open a VB.NET Windows Forms App (.NET Framework) project, everything functions as expected. The Solution Explorer displays the project contents and I can use the Design View interface.

Prior to the update, no matter what type of project I opened, the Solution Explorer would correctly display the project content, and the Design View interface was accessible. However, this issue arises when I attempt to open .NET Core version of the Windows Forms project.

To solve this problem, I've tried the following:

Downgrading Visual Studio to a previous version.
Completely uninstalling and reinstalling Visual Studio.
Updating to the latest version again.
Resetting all settings in Visual Studio.
Checking for updates and ensuring both Visual Studio and .NET Core SDK are up-to-date.
Reinstalling .NET Core SDK.
Creating a new .NET Core Windows Forms project.
Unfortunately, none of these steps have resolved the issue. Interestingly, I installed Visual Studio on another machine following the same steps, and all the functions there work as expected, with the Design View interface and the Solution Explorer functioning properly regardless of the project type.

Any insights or assistance you can provide would be greatly appreciated. Thank you.
<img width="760" alt="1" src="https://github.com/microsoft/vscode/assets/132134234/9c28c679-c2f2-4e1b-ad1e-7810247ffac9">
<img width="1140" alt="2" src="https://github.com/microsoft/vscode/assets/132134234/18cffc99-5f57-4739-9c59-2155ffcda4b3">

**Comment by gjsjohnmurray** [comment]
You are asking in the wrong place. Visual Studio Code is not Visual Studio.
