### ISSUE TITLE
Some feedback for SCM

### ISSUE THREAD

**Issue by massimocode** [Microsoft/vscode#18798]
I understand it's beneficial for VSCode to abstract away SCM to allow multiple source control systems.

However, my initial reaction was that it's taken away some of the functionality I had with the Git module, which was awesome.

Is there a flag or something we can change to bring back Git? I miss are being able to undo my commit.

**Comment by massimocode** [comment]
Also one more thing I miss is that there used to be a button in the top right corner of the "diff" view that allowed you to switch to editor, and vice versa. It seems that button is missing now.

**Comment by joaomoreno** [comment]
All the features will be preserved. You can track the progress here: #18615

**Comment by joaomoreno** [comment]
We might introduce a temporary setting for switching between the two modes.
