### ISSUE TITLE
Quick Pick layout has changed

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#18793]
- VSCode Version: 1.9.x
- OS Version: macOS

The Quick Pick layout has changed in the latest.
Our (unchanged) Process Picker now looks like this:
![2017-01-19_16-49-55](https://cloud.githubusercontent.com/assets/1898161/22113705/79d3857c-de67-11e6-9dca-1a0d62ec39f7.png)

In the stable version of VS Code (1.8.1) the process picker looks like this:
![2017-01-19_16-47-50](https://cloud.githubusercontent.com/assets/1898161/22113724/8b46b98c-de67-11e6-99ff-7d423bdec923.png)

**Comment by bpasero** [comment]
Likely due to https://github.com/Microsoft/vscode/commit/aa522145aa6b16ca88414142c932935dd933f830

@joaomoreno @aeschli fyi
