### ISSUE TITLE
Explorer has disappeared and the shortcut key (Ctrl+Shift+E) in View menu is also gone

### ISSUE THREAD

**Issue by djg3412** [microsoft/vscode#187989]
Explorer has disappeared and the shortcut key (Ctrl+Shift+E) in View menu is also gone as shown below. 
<img width="357" alt="image" src="https://github.com/microsoft/vscode/assets/21034326/1da74e94-2c2a-40ae-9cec-fe2859317653">
The context menu (mouse right click) of the Activity Bar also does not have the Explorer option. 
<img width="269" alt="image" src="https://github.com/microsoft/vscode/assets/21034326/30bc6daa-84e2-4a74-a242-db0edc36971a">

<img width="319" alt="image" src="https://github.com/microsoft/vscode/assets/21034326/82e6e856-9616-42e0-a4bf-d1467bb05db1">

Please advise how I can get the Explorer back?

**Comment by lramos15** [comment]
`F1` -> `Reset View Locations`

**Comment by djg3412** [comment]
@lramos15 Thank you very much, problem solved!
