### ISSUE TITLE
Settings editor search results aren't sorted well

### ISSUE THREAD

**Issue by rzhao271** [microsoft/vscode#187959]
Ref https://github.com/microsoft/vscode/issues/187949#issuecomment-1636355066

1. Search `test` in the Settings editor in the User settings.
2. :bug: "Testing: Automatically Open Peak View" appears after "TypeScript > Preferences: Quote Style"? The "Testing" settings are not all grouped together, which could make users believe that there aren't as many Testing settings available as there really are.

**Comment by rzhao271** [comment]
Confirmed. The largest issue to me is that the setting `typescript.format.insertSpaceAfterOpeningAndBeforeClosingTemplateStringBraces` shows up as a search result.

I notice that some other test-related settings interject themselves between the Testing settings, but that happens because they contain whole-word matches for the word "test" elsewhere, such as in the description. CC @333fred

**Comment by balaji-sivasakthi** [comment]
@rzhao271 I would like to work on this bug.

**Comment by rzhao271** [comment]
Hi @balaji-sivasakthi, thanks for offering to work on the issue.
However, I've a PR up (#190453) that interferes with the search result code. After that PR is merged, I plan to address this issue myself.
I recommend looking through the [help wanted](https://github.com/microsoft/vscode/issues?q=is%3Aissue+is%3Aopen+label%3A%22help+wanted%22+) issues.

**Comment by rzhao271** [comment]
\closedWith 2db3132
