### ISSUE TITLE
Settings sync installs extensions which need to be migrated

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode#187947]
1. Have GitHub Copilot Nightly synced to settings sync
2. Create a codespace 
3. :bug: Copilot prerelease is installed and I get this notification

<img width="366" alt="image" src="https://github.com/microsoft/vscode/assets/30305945/39708868-20cd-4895-a7aa-371aecc441f9">

**Comment by sandy081** [comment]
> Copilot prerelease is installed and I get this notification

Do you mean Copilot nightly is installed?

**Comment by joyceerhl** [comment]
Yeah, I'm guessing first I get Copilot nightly, then it gets uninstalled in favor of Copilot prerelease because of the migration code

**Comment by sandy081** [comment]
> then it gets uninstalled in favor of Copilot prerelease because of the migration code

So this should remove the nightly extension from your synced data right?

**Comment by joyceerhl** [comment]
Not if the codespace only has read access to settings sync (which I believe is the default)
