### ISSUE TITLE
Diff Editor: New Files Have Weird Alignments

### ISSUE THREAD

**Issue by hediet** [microsoft/vscode#187939]
[repro](https://microsoft.github.io/monaco-editor/playground.html?source=v0.41.0-dev.20230714#XQAAAAKaAwAAAAAAAABBqQkHQ5NjdMjwa-jY7SIQ9S7DNlzs5W-mwj0fe1ZCDRFc9ws9XQE0SJE1jc2VKxhaLFIw9vEWSxW3yscw4fo2RgmSatbNyrNa50VLHWwDOn0YI7IfU0xJ0CGYU1vRtgnKPmZzQcQ1F9I-F9YcvQUj8HivueDk6xk10aTwajFUJtCUPrbJyYzhlPpkRS6VL5hsKJdCDPoibdd4UKQFbGKqNMIHksq_hj2dyWyjYzntQklYnJJKwNRqKTApNBR5J1oiPyejKtBJivpkmSkf-E1g1FMgCuUFNIW36YjPk8sJVzPe82AUe6t-Xf33cJqxOIybQEJmuh5_mc5aeduLggd51SbbXTkqp37nMDQgTW39IZLIcsKkwNsABPSrr6ojU32mYXAsF-VwW7gWTnVZqCZ8v-ArLmkoyzyJaGFFj7XB96fFAtRIxNoURzR5xi7gcPnV49PEDZepWXzDwgHRLAl7PaWaFZGufwxM7SMdf1zw9sp1hMZHr-IRowGKKw9GukWnp9tE2qFSfVqLzPFwkDK-_YcTpuLw9-wTJDExpKI0Toy4dvs4WTz1F_Mxc5HrZe_-42_6hQtrCHNw3vV_nVBg1kPXhT65TkeuZh_0H2moasver1pEtZduEnKXekOH7L-iBOq16Aa0CY2BSXnfCRLSIbxnXk2GGc_g0j_nGdlBrUZRDC0Euv8JM-xFPor3jnqC4LzcdEwzUYUg_gjPkg)

**Comment by rzhao271** [comment]
The issue still occurs in Monaco Editor v0.41.0-dev.20230719, but it seems to be fixed in VS Code Insiders. I'll add the verified label for now, but feel free to mark that as verification-found if it indicates there's a bug still.
