### ISSUE TITLE
Allow not focusing failed test lines

### ISSUE THREAD

**Issue by 333fred** [microsoft/vscode#187949]
Type: <b>Feature</b>

Today, when a test fails, the line with the failing assert is focused in the editor. This can sometimes be useful (when the assert is directly in the test), but very often in larger testbases the assert will be several levels down in a test helper. This is rather annoying, and I find myself immediately needing to hit back so that I can change the test I was working on, not the helper that failed. An ideal solution for me would be an option to allow one of a few things:

1. Focus the test that failed, or the line in the test that failed, _not_ through other methods.
2. Don't change the focus at all.

Moved from https://github.com/microsoft/vscode-dotnettools/issues/235.

Extension version: 0.2.128-g4ef54fe680
VS Code version: Code - Insiders 1.81.0-insider (31f183271b0d1f24a2052f6eccbb76bdef45d60b, 2023-07-07T05:33:42.326Z)
OS version: Linux x64 5.15.0-76-generic snap
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 9 5950X 16-Core Processor (32 x 3400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|3, 4, 4|
|Memory (System)|62.70GB (24.47GB free)|
|Process Argv|--no-sandbox . --crash-reporter-id 9e8cf102-e785-4922-93ba-24ac731cf9e4|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|regolith|
|XDG_CURRENT_DESKTOP|Regolith:GNOME-Flashback:GNOME|
|XDG_SESSION_DESKTOP|regolith|
|XDG_SESSION_TYPE|x11|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythontb:30258533
pythonptprofiler:30281269
vshan820:30294714
vscod805:30301674
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30404738
py29gd2263:30784851
vsclangdf:30492506
c4g48928:30535728
dsvsc012:30540252
pynewext54:30618038
pylantcb52:30590116
pyind779:30611226
pythonsymbol12:30651887
2i9eh265:30646982
showlangstatbar:30737417
pythonms35:30671666
ecj1e332:30687743
pythonfmttext:30716741
pythoncmvfstr:30726892
fixshowwlkth:30771523
hideindicator:30766887
pythongtdpath:30726887
i26e3531:30780429
gsofa:30778558
pythonnosmt12:30779711
pythonidxpt:30768918
pythondjangots:30768917
pythonnoceb:30776497
copilotsettingt:30767686
e537b577:30772214
h0f32768:30779712
asynctok:30783811
dsvsc013:30777762
dsvsc014:30777825

```

</details>

**Comment by 333fred** [comment]
@connor4312 thanks for pointing that out. Some minor feedback on settings search then: when I search for `test`, I see this:
![image](https://github.com/microsoft/vscode/assets/2371880/0557c5b8-27f9-485e-bb4f-55608c314c9a)

I have to scroll down past a number of settings contributed from extensions before I see that setting:
![image](https://github.com/microsoft/vscode/assets/2371880/023a25af-e50c-45ae-a57b-3b7b6190bd19)

I had assumed that search wouldn't reorder results like this, so I didn't bother scrolling down any further.

**Comment by connor4312** [comment]
fyi @rzhao271
