### ISSUE TITLE
[debug js] No variable preview with the rest syntax

### ISSUE THREAD

**Issue by zardoy** [microsoft/vscode#187943]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.80.1
- OS Version: 

You have to either type variable name in console or remove `...` to preview its value.

![image](https://github.com/microsoft/vscode/assets/46503702/1bcaf65d-1fcf-41e6-9d11-26e93439b62c)

**Comment by connor4312** [comment]
duplicates https://github.com/microsoft/vscode/issues/18058

**Comment by zardoy** [comment]
but the referenced issue is a feature request of showing evaluated value of arbitrary selection. This issue's screenshot doesn't involve any selections (variable has changed background because of semantic highlight), am I missing something? It's a regular variable preview that doesn't work in this specific case

**Comment by connor4312** [comment]
Both of the problems (and many others in the linked issues!) are solved by having an EvaluatableExpressionProvider for TS/JS. I pinged our person to see about getting it on the TypeScript team's roadmap, as they're the best people to implement that.
