### ISSUE TITLE
SearchViewlet is missing multi-line "surrounding context"

### ISSUE THREAD

**Issue by PoisonousJohn** [microsoft/vscode#18791]
In Sublime text when you search something in the whole project, you can see the so called "surrounding context" in results. This feature is really helpful when you're searching in large projects.

![Surrounding context in Sublime Text](http://www.macdrifter.com/uploads/2012/07/Screen%20Shot%2020120707_093317.jpg)

It would be great to have this feature in vscode

**Comment by sandy081** [comment]
We do show the surrounding context for search results in the search viewlet. 

![image](https://cloud.githubusercontent.com/assets/10746682/22140732/8b1a8a7e-deee-11e6-81b9-6156a3a87224.png)

Since we show in viewlet, It is restricted only to the line of the match. But do not show previous or next lines if they do not have matches.

**Comment by JohnPoison** [comment]
@sandy081 yes, this is what I'm talking about. One line is not enough for context. And the lack of this feature stops me from choosing VSCode as the only editor I use. It's essential for large projects.

**Comment by chesucr** [comment]
I agree with @IvanFateev . And I think it would be better to show the results in a new tab as a new text file like Sublime does. In this way we could do some search in this new text file again, it is very useful for big projects

**Comment by toadgeek** [comment]
Having more than one line would be very helpful.

**Comment by Luchanso** [comment]
Yeah, it will be great feature for search

**Comment by a7madgamal** [comment]
wow I expected some config to set not an issue :(

**Comment by jb510** [comment]
related https://github.com/Microsoft/vscode/issues/59458

Note, what I want is _exactly_ Sublime Text's behavior.  Moving search to the bottom tab helps, but is still very cumbersome.  Providing multi-line context will help, but I also want to see file paths and line numbers.  Trust all of this is in 50464 for "someday".

**Comment by a7madgamal** [comment]
FYI there is a setting for line numbers

**Comment by roblourens** [comment]
I don't think this fits in the search viewlet. It's not intended to be a place where you read your code, it's too narrow for that. But, when we support showing results in an editor, then we will have this.
