### ISSUE TITLE
El mouse no agarra la barra de navegacion del terminal en vs code

### ISSUE THREAD

**Issue by SebastianR24** [microsoft/vscode#187977]
Type: <b>Bug</b>

No se porque pero hace dos dias la barra de navegacion empezo a dejar de funcionar, y como la rueda del mouse esta mala esa barra era la unica forma de yo subir y bajar para ver la informacion, ahora la forma mia para subir y bajar es marcar el texto mientras subo el mouse. 
![Annotation 2023-07-15 064258](https://github.com/microsoft/vscode/assets/139417797/c0f3a763-b8e6-4967-ab62-e1bee4ce1f41)

VS Code version: Code 1.80.1 (74f6148eb9ea00507ec113ec51c489d6ffb4b771, 2023-07-12T17:22:07.651Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-5005U CPU @ 2.00GHz (4 x 1995)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|11.91GB (6.91GB free)|
|Process Argv|--crash-reporter-id 3d060ffb-dd34-4f19-8afe-31ea2b58e310|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (25)</summary>

Extension|Author (truncated)|Version
---|---|---
codesnap|adp|1.3.4
TabOut|alb|0.2.2
blackbox|Bla|1.0.45
path-intellisense|chr|2.8.4
doxdocgen|csc|1.4.0
c-cpp-compile-run|dan|1.0.48
prettier-vscode|esb|9.19.0
code-runner|for|0.12.0
vscode-google-translate|fun|1.4.13
better-cpp-syntax|jef|1.17.2
vscode-language-pack-es|MS-|1.80.2023071209
cmake-tools|ms-|1.14.34
cpptools|ms-|1.16.3
cpptools-extension-pack|ms-|1.3.0
vsliveshare|ms-|1.0.5873
indent-rainbow|ode|8.3.1
LiveServer|rit|5.7.9
docxreader|Sha|1.0.0
pdf|tom|1.2.2
cmake|twx|0.0.17
intellicode-api-usage-examples|Vis|0.2.7
vscodeintellicode|Vis|1.2.30
vscode-java-debug|vsc|0.52.0
vscode-java-dependency|vsc|0.23.0
vscode-maven|vsc|0.41.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
py29gd2263cf:30789497
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
vsccc:30610678
3biah626:30602489
pyind779:30671433
f6dab269:30613381
pythonsymbol12:30671437
2i9eh265:30646982
showlangstatbar:30737416
vsctsb:30748421
pythonms35:30701012
a2ce3375:30757347
pythonfmttext:30731395
pythoncmvfstrcf:30756944
fixshowwlkth:30771522
hideindicator:30785051
pythongtdpath:30769146
i26e3531:30780429
pythonnosmt12:30779714
pythonidxpt:30784022
pythonnocebcf:30776496
e537b577:30786199
dsvsc013:30789517

```

</details>

**Comment by meganrogge** [comment]
sorry for my delay, Pls open a new issue if you're still seeing this
