### ISSUE TITLE
do not pass "address" attribute to launchRequest

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#1879]
For the launchRequest the debugAdapter receives an argument object that has an "address" attribute:

![2016-01-08 16-19-45](https://cloud.githubusercontent.com/assets/1898161/12201345/25d84c76-b624-11e5-88b4-2a5e3035fcc4.png)

Since this is neither specified in the schema for "launch" nor is it one of the well-known attributes "type", "request", "debugServer", "name", or "preLaunchTask".

Please remove "address" and make sure that only the expected arguments are passed to the "launch" and "attach" requests.

**Comment by isidorn** [comment]
I believe this is fixed now, can you please give it a try and reopen if needed
