### ISSUE TITLE
Format action in XML files deletes spaces in content

### ISSUE THREAD

**Issue by davity** [Microsoft/vscode#188]
When you format an XML file, every group of more than one space is replaced by only one. For example, given this XML

```XML
<?xml version="1.0" encoding="UTF-8"?><parent><child>   A   B   C   D   </child></parent>
```
after execute `editor.action.format` action (`ctrl+shift+f` by default in Windows) the result is
```XML
<?xml version="1.0" encoding="UTF-8"?>
   <parent>
      <child> A B C D </child>
   </parent>
```
As it shows, all the spaces inside `child` tag have been trimmed, and now data is different.

**Comment by aeschli** [comment]
Sorry, we removed XML format from 0.10.1 due to the many bugs. We hope we can get a high quality formatter as an extension soon
