### ISSUE TITLE
Debug variable displays verbose info

### ISSUE THREAD

**Issue by laoshaw** [microsoft/vscode#188002]
While debugging python, the info under "Variables" displayed is too verbose and distracting most of the time, can I turn it off by default.

![image](https://github.com/microsoft/vscode/assets/18351761/bdec456f-01a3-4a07-a838-58466db021f8)

Turn off verbose info for debugging Variables such as object address etc, see the screenshot

**Comment by roblourens** [comment]
Please file this on the vscode-python extension repo
