### ISSUE TITLE
Not able create debug code - TypeError: Cannot read properties of undefined (reading 'map')

### ISSUE THREAD

**Issue by goc-nikul** [microsoft/vscode#188086]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 
- OS Version: 
Version: 1.80.1 (user setup)
Commit: 74f6148eb9ea00507ec113ec51c489d6ffb4b771
Date: 2023-07-12T17:22:07.651Z
Electron: 22.3.14
ElectronBuildId: 21893604
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Windows_NT x64 10.0.22621
Steps to Reproduce:

1.  Open vs connect and connect salesforce commerce cloud org.
2. Upload code to salesforce commerce cloud org
3.  Start debugger create launch.json file and add below code 
4. {
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "type": "prophet",
            "request": "launch",
            "name": "Attach to Sandbox"
        }
    ]
}
5 . Click on Run and Debug and attach to sandbox.
6  it give below error

typeError: Cannot read properties of undefined (reading 'map')
 TypeError: Cannot read properties of undefined (reading 'map')
    at \.vscode\extensions\sqrtt.prophet-1.4.40\dist\mockDebug.js:1:29557
    at \.vscode\extensions\sqrtt.prophet-1.4.40\dist\mockDebug.js:1:28332
    at new Promise (<anonymous>)
    at \.vscode\extensions\sqrtt.prophet-1.4.40\dist\mockDebug.js:1:28311
    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)SyntaxError: Unexpected token '<', "<a href="/"... is not valid JSON
 SyntaxError: Unexpected token '<', "<a href="/"... is not valid JSON
    at JSON.parse (<anonymous>)
    at \.vscode\extensions\sqrtt.prophet-1.4.40\dist\mockDebug.js:1:28346
    at new Promise (<anonymous>)
    at \.vscode\extensions\sqrtt.prophet-1.4.40\dist\mockDebug.js:1:28311
    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)SyntaxError: Unexpected token '<', "<a href="/"... is not valid JSON
 SyntaxError: Unexpected token '<', "<a href="/"... is not valid JSON
    at JSON.parse (<anonymous>)
    at \.vscode\extensions\sqrtt.prophet-1.4.40\dist\mockDebug.js:1:28346
    at new Promise (<anonymous>)
    at \.vscode\extensions\sqrtt.prophet-1.4.40\dist\mockDebug.js:1:28311
    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)SyntaxError: Unexpected token '<', "<a href="/"... is not valid JSON
 SyntaxError: Unexpected token '<', "<a href="/"... is not valid JSON
    at JSON.parse (<anonymous>)
    at \.vscode\extensions\sqrtt.prophet-1.4.40\dist\mockDebug.js:1:28346
    at new Promise (<anonymous>)
    at \.vscode\extensions\sqrtt.prophet-1.4.40\dist\mockDebug.js:1:28311
    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)SyntaxError: Unexpected token '<', "<a href="/"... is not valid JSON
 SyntaxError: Unexpected token '<', "<a href="/"... is not valid JSON
    at JSON.parse (<anonymous>)
    at \.vscode\extensions\sqrtt.prophet-1.4.40\dist\mockDebug.js:1:28346
    at new Promise (<anonymous>)
    at \.vscode\extensions\sqrtt.prophet-1.4.40\dist\mockDebug.js:1:28311
    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)Disconnecting...

**Comment by roblourens** [comment]
Looks like an issue with that extension

**Comment by goc-nikul** [comment]
@roblourens - i had completely remove vs code and its extension and installed it again. but still problem persist. Can you please tell me which extension causes the issue.

I had installed - https://marketplace.visualstudio.com/items?itemName=gkkirilov.salesforce-commerce-cloud-productivity-pack

**Comment by roblourens** [comment]
From the stack, I would start with `sqrtt.prophet`

**Comment by goc-nikul** [comment]
Hi @roblourens 

It is fixed now. It was hostname issue.
Thank you
