### ISSUE TITLE
vscode.ExtensionContext.storagePath is undefined the 1st time an extension is activated for a workspace

### ISSUE THREAD

**Issue by sean-mcmanus** [Microsoft/vscode#18808]
- VSCode Version: 1.8.1
- OS Version: Windows

Steps to Reproduce:

1. Debug the C++ extension C_Cpp.ts activate method.
2. context : vscode.ExecutionContext has a value of undefined for the storagePath the 1st time the extension is activated for a new workspace. It repros in all cases, such as when no other files are open, and the extension is activated after the workspace is opened.

The bug starts reproing again after the folder C:\Users\\<user\>\AppData\Roaming\Code\User\workspaceStorage\\<guid\> is deleted.

Seems like a bug in VS Code?

**Comment by dbaeumer** [comment]
@jrieken assigning to you due to the async work you did here.
