### ISSUE TITLE
SCM changed file count doesn't always update

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#188088]
Probably another way to repro this but while reproing https://github.com/microsoft/vscode/issues/188087 I was finding this

- Checkout vscode-copilot to c0910dd723d1a6625d181ee3fe5e434fe9718ba8
- Find context.ts, F2, rename the `Context` class to `ServicesAccessor`

This badge on "Changes" doesn't match the actual number of files that show up. Activity bar badge is correct

<img width="432" alt="image" src="https://github.com/microsoft/vscode/assets/323878/926bde3e-7191-48f7-a073-7a7c47a79880">

**Comment by roblourens** [comment]
I can still repro
<img width="489" alt="image" src="https://github.com/microsoft/vscode/assets/323878/5810a02d-c53a-4da2-bf60-0f348d321dc3">

Even clicking Refresh in the scm tree doesn't fix it

**Comment by lszomoru** [comment]
Closing this issue as I was not able to repro.
