### ISSUE TITLE
somehow, shift+tab is opening termminal

### ISSUE THREAD

**Issue by derekriemer** [microsoft/vscode#188014]
Type: <b>Bug</b>

I have screen reader mode enabled. Shift+tab is opening the terminal. Disabling screen reader optimizations causes shift+tab to work properly

VS Code version: Code - Insiders 1.81.0-insider (dc142e4cd111b8f370d0549d8c207df7de55facd, 2023-07-14T10:43:06.630Z)
OS version: Windows_NT x64 10.0.22621
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 9 6900HS with Radeon Graphics         (16 x 3294)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.23GB (9.24GB free)|
|Process Argv|--crash-reporter-id 28ba6424-1533-4280-b47a-bdf8edaf453d|
|Screen Reader|yes|
|VM|0%|
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythontb:30258533
pythonptprofiler:30281269
vshan820:30294714
vscod805cf:30301675
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30404738
py29gd2263:30784851
vscaat:30438846
vsclangdf:30492506
c4g48928:30535728
dsvsc012:30540252
pynewext54:30618038
pylantcb52:30590116
pyind779:30611226
pythonsymbol12:30651887
2i9eh265:30646982
showlangstatbar:30737417
pythonms35:30671666
24365598:30687740
pythonfmttext:30716741
pythoncmvfstr:30726892
fixshowwlkth:30771523
hideindicator:30766887
pythongtdpath:30726887
i26e3531:30780429
gsofa:30778558
pythonnosmt12:30779711
pythonidxpt:30768918
pythondjangots:30768917
pythonnoceb:30776497
copilotsettingt:30767686
e537b577:30772214
h0f32768:30779712
synctok:30783813
dsvsc013:30777762
dsvsc014:30777825
diffeditorv2:30786206

```

</details>

**Comment by jvesouza** [comment]
I've exactly the same problem.
Commit: dc142e4cd111b8f370d0549d8c207df7de55facd under fedora 38 and  orca as the screen reader.

Steps to reproduce:
1. Launch VSCode on an empty project.
2. Make sure that a screen reader  is active.
3. Create an empty editor by pressing ctrl+n.
4. Launcha terminal using vscode.
5. Return to the created empty editor by pressing ctrl+tab.
6. Press shift+tab.
Expected result: The focus should not be moved.
Actual result: The focus is moved to the terminal-accessible buffer.

There are other situations where this also happens, like for example when I'm in the file explorer or interacting with git.

cc: @meganrogge @isidorn

**Comment by meganrogge** [comment]
/duplicate #188081

the keybinding should only apply `when` the terminal is focused
