### ISSUE TITLE
Support link detection in test results terminal

### ISSUE THREAD

**Issue by longmaxx** [microsoft/vscode#188055]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: VSCode 1.80.1, 1.81.0-insider; plugin playwright test for VSCode 1.0.14
- OS Version: Windows 10

Steps to Reproduce:
- Run playwright TS test throwing an error. 
- Open test results viewer in vs code (see picture)
- Try Ctrl+Click on call stack item for the error 

**Expected**
We jump to source code line

**Actual**
Nothing happens.

It stopped to work ~ a week ago, I guess. But used to work in  vs code insider build. But today is stopped to work in the insider build too. (monday, 17.07.2023)
Doesn't reproduce in VSCode  1.79.2.

![Скриншот 17-07-2023 105240](https://github.com/microsoft/vscode/assets/11839300/b4debe61-81f9-45e0-892b-91bb1a211fcc)

**Comment by hsfzxjy** [comment]
Is this being worked on? I would like to file a PR for this.

**Comment by matter-it-does** [comment]
yes!!
