### ISSUE TITLE
naming of interactive window 

### ISSUE THREAD

**Issue by echaya** [microsoft/vscode#188031]
- VS Code Version: 1.80.1
- OS Version: Win-10
- Python extension: v2023.12.0

Steps to Reproduce:

1. create an empty `test.py` file with
``` python
###
import datetime
```
2. run cell => you will see the interactive window with tab name `interactive-1`, `interactive-2`...

Please confirm if this is work as designed. I remember it wasn't the case at the beginning of the year. This type of naming causes tremendous confusing when working on more than 2 interactive windows within a Workplace. 

Please let me know if I should report it to https://github.com/microsoft/vscode-python. Thanks!

**Comment by thupalo** [comment]
Probably the same error after last update.

VS Code Version: 1.80.1
OS Version: Ubuntu 22.04

"jupyter.interactiveWindow.creationMode": "perFile"
name of source python file is lost, only tab names 'interactive-1', 'interactive-2'

**Comment by amunger** [comment]
not intentional, it should still include the python filename in the interactive tab. investigating
