### ISSUE TITLE
New notebook.experimental.remoteSave setting isn't registered

### ISSUE THREAD

**Issue by ido-greenfeld** [microsoft/vscode#188044]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.80.1
- OS Version: Windows 11 / Ubuntu 20.04 LTS

Based on the change log of version 1.80 ([changelog](https://code.visualstudio.com/updates/v1_80#_improved-save-performance-for-remote-development)), a new option for enabling the improved notebook saving method should be available. However, this option is not appearing in the settings user interface.

Additionally, when I manually add notebook.experimental.remoteSave to the setting.json file, I receive an error message stating "Unknown Configuration Setting."

**Comment by gjsjohnmurray** [comment]
Already fixed in Insiders by https://github.com/microsoft/vscode/pull/187189

**Comment by gjsjohnmurray** [comment]
The setting ought to work on 1.80 even though it gets reported as unknown.

**Comment by rebornix** [comment]
Should be a valid setting now in Insiders.
