### ISSUE TITLE
Terminal Screen is all covered with  black cant even see the text

### ISSUE THREAD

**Issue by fantastic-yuvi** [microsoft/vscode#188022]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: newest by 16 july 2023  1.80.1
- OS Version:  windows 10
-
The terminal is all black cant see the commands im typing and i have tried uninstalling and app again and again but nothing is working
![photo_2023-07-16_19-40-15](https://github.com/microsoft/vscode/assets/91376948/7121b524-d450-47a4-9a96-55b7d0986406)

Steps to Reproduce:

1. 
2.

**Comment by Bhanu-Partap** [comment]
any solution for that  ??

**Comment by Bhanu-Partap** [comment]
i got the isuue and the solution is you have to degrade the version of vs code as its a bug in vs code
