### ISSUE TITLE
Error while encrypting the text provided to safeStorage.encryptString. Encryption is not available.

### ISSUE THREAD

**Issue by wilhelmklopp** [microsoft/vscode#188059]
From version 1.80 onwards, we've been getting CI failures when testing our vscode extension with this error message: "Error while encrypting the text provided to safeStorage.encryptString. Encryption is not available."

I suspect this is related to the move off keytar described in the release notes of 1.80 and here https://github.com/microsoft/vscode-discussions/discussions/662

For the purposes of testing our extension, we pass additional launchArgs to VSCode, notably `--disable-keytar`. As I understand it, this instructs VSCode to use some sort of in memory keytar so that the secrets are not actually persisted to disk? This is the desired behaviour for us so that no secrets persist after the the test suite concludes. This has been working well until now, and based on a quick search for `--disable-keytar` on GitHub, it seems like a popular approach when testing VSCode extensions.

Notably this only seems to happen in our linux CI. Mac and Windows continue to work without a problem (as also demonstrated below)

---

Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: [Latest insiders today (17 July)]( https://update.code.visualstudio.com/latest/linux-x64/insider), Same issue happens on 1.80.1
- OS Version: Ubuntu 22.04.2

Steps to Reproduce:

I've created a minimal repro here: https://github.com/kolofordjango/encryption-not-available-demo

The line that ends up resulting in the error: https://github.com/kolofordjango/encryption-not-available-demo/blob/efe774347bf9027e4f81c1ecf88bfaba617ecd78/src/test/suite/extension.test.ts#L21

GitHub Actions Build showing the error: https://github.com/kolofordjango/encryption-not-available-demo/actions/runs/5575232697/jobs/10184874439#step:5:82

PR demonstrating no errors happened on `1.79.2`: https://github.com/kolofordjango/encryption-not-available-demo/pull/1

**Comment by TylerLeonhardt** [comment]
When encryption isn't available, we use an in-memory store instead so I think the current behavior should give you the desired behavior, no?

**Comment by wilhelmklopp** [comment]
> Or does it actually throw instead and cause the extension to not function?

@TylerLeonhardt Yeah exactly, it just throws right now (on linux). Same code works without issue on 1.79

**Comment by TylerLeonhardt** [comment]
I think this is because you see a dialog in the product to ask you to do something. I need to make that dialog non-blocking.

In the meantime, you can do this:

https://code.visualstudio.com/docs/editor/settings-sync#_not-recommended-configure-basic-text-encryption

And configure basic text encryption which is fine because the container will be destroyed after.

**Comment by wilhelmklopp** [comment]
Thanks!

I added `--password-store="basic"` to the launchArgs, but seem to be getting the same error: https://github.com/kolofordjango/encryption-not-available-demo/pull/2

**Comment by TylerLeonhardt** [comment]
I think maybe you want `--password-store=basic` not `--password-store="basic"`. I just tried on my Ubuntu machine and `--password-store=basic` worked.

**Comment by TylerLeonhardt** [comment]
FYI I have opened https://github.com/microsoft/vscode/issues/188432 to track allowing an in memory secret storage. If we get you unblocked with `--password-store=basic` I'll dupe this to that.

**Comment by wilhelmklopp** [comment]
@TylerLeonhardt thanks for continuing to look into this!

I applied your suggestion (`--password-store=basic` without the quotes) but looks like on GitHub Actions (ubuntu) it still results in the same issue: https://github.com/kolofordjango/encryption-not-available-demo/pull/2/commits/9e3950d914e9c367e4d985710a8d937cc49a2975

**Comment by deepak1556** [comment]
@TylerLeonhardt it should be `basic` instead of `basic_text` in https://github.com/microsoft/vscode/blob/dad3c697b0e4f55b32fd0a831840db6ca8eef03b/src/vs/platform/encryption/electron-main/encryptionMainService.ts#L28C1-L30, without that `setUsePlainTextEncryption` will not be called and causes the above error to be thrown.

**Comment by wilhelmklopp** [comment]
Setting `--password-store=basic_text` seems to do the trick for me 🎉 – thank you!

 https://github.com/kolofordjango/encryption-not-available-demo/pull/2/commits/69d60b53abd67fc300c6f3a9afb3e66d9b22c8bb

**Comment by TylerLeonhardt** [comment]
FYI, I will change it to be `--password-store=basic` to align with what Electron actually accepts.
