### ISSUE TITLE
Terminal scroll is not working if you try to use the scroll bar manually.

### ISSUE THREAD

**Issue by zifahm** [microsoft/vscode#188085]
Does this issue occur when all extensions are disabled?: Yes/No

Version: 1.80.0
Commit: 660393deaaa6d1996740ff4880f1bad43768c814
Date: 2023-07-04T13:39:48.236Z
Electron: 22.3.14
ElectronBuildId: 21893604
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Linux x64 5.4.0-153-generic

Steps to Reproduce:

1. open terminal
2. execute a command to create length, try `ls -al`
3. scroll by manually holding the scroll bar. Up or down.

This does not seem to scroll! Very annoying, Started happening after update!

**Comment by meganrogge** [comment]
this works for me in insider's
