### ISSUE TITLE
VSCODE extension could not websocket connect to REMOTE websocket server

### ISSUE THREAD

**Issue by jcyrss** [microsoft/vscode#188008]
Type: <b>Bug</b>

I found the websocket in the webview of vscode extension could not establish connection with a `remote` websocket server. 

The url I used is like `ws://192.168.5.33:8081`, Developer tools console shows info like 

```py
WebSocket connection to 'ws://192.168.5.33:8081/' failed: 
```

It does not look like it violates any Content Security Policy, for otherwise, that will be displayed.

Developer tools Network tab shows like this, 

![image](https://github.com/microsoft/vscode-discussions/assets/10496014/963cd2da-26c6-42c5-a113-361b6980f438)

![image](https://github.com/microsoft/vscode-discussions/assets/10496014/65b97d80-8fa5-40f2-ae67-425f54256547)

![image](https://github.com/microsoft/vscode-discussions/assets/10496014/a0128763-ae3e-4e1d-a215-4a59a6a90cdc)

Just a request, no response. I'm sure websocket server works well, because I run the same code `in browser` instead of vscode webview extension, to connect with that remote server, and found it works well.

Also that extension webview works well with a **local** websocket server, like `ws://127.0.0.1:8081`

I run tcpdump on server host, trying to connect to ws server in vscode extension webview did not get any captured package. While it did when I connected in the browser.

So it seems vscode does not allow my webview code to contact with remote websocket server.

Later, I had to move the code of websocket client from webview to extension native with `const WebSocket = require('ws');` to use `ws` lib.

And get failure like the following

![image](https://github.com/microsoft/vscode/assets/10496014/18a1aba6-d5a6-4169-a84a-f4bea3fcb85f)

Again, it worked perfectly to run websocket client in Browser instead of vscode extension to connect remote server. So it's not server's problem.

From what I've googled, all successful websocket example of vscode extension is to connect with local websocket server.

Does vscode have any restriction on **extension** to websocket connect with A **REMOTE** server?

VS Code version: Code 1.80.1 (74f6148eb9ea00507ec113ec51c489d6ffb4b771, 2023-07-12T17:22:07.651Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 5600U with Radeon Graphics          (12 x 2296)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.31GB (5.06GB free)|
|Process Argv|--crash-reporter-id e6e61bd8-354e-4783-a9fe-e0919ba872fa|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (25)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-sqlite|ale|0.14.1
better-toml|bun|0.3.2
hytest|byh|0.0.8
indent4to2|Com|0.1.2
githistory|don|0.6.20
gitlens|eam|14.1.0
vscode-html-css|ecm|1.13.1
auto-rename-tag|for|0.1.10
go|gol|0.39.0
todo-tree|Gru|0.0.226
git-graph|mhu|1.30.0
isort|ms-|2023.10.1
python|ms-|2023.12.0
vscode-pylance|ms-|2023.7.20
remote-ssh|ms-|0.102.0
remote-ssh-edit|ms-|0.86.0
cmake-tools|ms-|1.14.34
cpptools|ms-|1.16.3
cpptools-extension-pack|ms-|1.3.0
remote-explorer|ms-|0.4.1
autodocstring|njp|0.6.1
LiveServer|rit|5.7.9
partial-diff|ryu|1.4.3
cmake|twx|0.0.17
markdown-all-in-one|yzh|3.5.1

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
py29gd2263:30789496
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyonecf:30548226
2e4cg342:30602488
pyind779:30671433
89544117:30613380
pythonsymbol12:30671437
showlangstatbar:30737416
vsctsb:30748421
pythonms35:30701012
a2ce3375:30757347
pythonfmttext:30731395
pythoncmv:30756943
fixshowwlkth:30771522
showindicator:30785052
pythongtdpath:30769146
bgfeh915:30780428
pythonnosm12tcf:30779713
pythonidxpt:30784022
pythonnocebcf:30776496
h7j2d465:30786200
dsvsc013cf:30789518

```

</details>

**Comment by gjsjohnmurray** [comment]
Is a proxy involved when your code running in a browser (as opposed to running in VS Code) successfully connects to that remote server?

**Comment by gjsjohnmurray** [comment]
Linking this issue to your existing one at https://github.com/microsoft/vscode-discussions/discussions/693

**Comment by tamuratak** [comment]
The message indicates that the server rejects the connection. I would review the configuration of the WebSocket server, paying particular attention to the allowed origins. WebSocket servers typically reject connections based on the origins provided by clients. 

> Error: Unexpected server response: 503

**Comment by jcyrss** [comment]
> Is a proxy involved when your code running in a browser (as opposed to running in VS Code) successfully connects to that remote server?

Oh,my. It turns out not due to the proxy in browser, but the proxy in vscode set long time ago. By turning the proxy off, everything goes well both in webview and in extension native. 

Thank you!

**Comment by gjsjohnmurray** [comment]
Glad to hear you solved it. Perhaps https://github.com/microsoft/vscode/issues/175494#issuecomment-1463500832 from @chrmarti is relevant.
