### ISSUE TITLE
Closes for everything

### ISSUE THREAD

**Issue by Xpsp** [microsoft/vscode#188000]
Type: <b>Bug</b>

To reproduce the bug
help -> about
or delete some file
or close some workspace

VSCode was working fine, and all of a sudden the bug started, searching the internet I found 
Snap crashes when native dialogs open #100940
but nothing works. Before uninstalling to see if that fixes the bug I send this report. 

VS Code version: Code 1.80.1 (74f6148eb9ea00507ec113ec51c489d6ffb4b771, 2023-07-12T17:22:25.257Z)
OS version: Linux x64 5.15.0-76-generic snap
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 3 PRO 4350G with Radeon Graphics (8 x 1400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|3, 2, 1|
|Memory (System)|15.52GB (10.99GB free)|
|Process Argv|--no-sandbox --force-user-env --unity-launch --crash-reporter-id 25c979e5-e698-418e-8c71-46e15795aa03|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (22)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|3.0.2
codesnap|adp|1.3.4
githistory|don|0.6.20
code-runner|for|0.12.0
copilot|Git|1.96.255
latex-workshop|Jam|9.13.0
vsc-python-indent|Kev|1.18.0
vscode-ros|ms-|0.9.2
python|ms-|2023.12.0
vscode-pylance|ms-|2023.7.20
jupyter|ms-|2023.6.1101941928
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.17
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-slideshow|ms-|0.1.5
cmake-tools|ms-|1.14.34
cpptools|ms-|1.16.3
language-ogre-script|par|0.9.4
urdf|smi|0.3.0
cmake|twx|0.0.17
vscode-icons|vsc|12.4.0
markdown-all-in-one|yzh|3.5.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263:30335439
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
py29gd2263:30789496
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
282f8724:30602487
pyind779:30671433
89544117:30613380
pythonsymbol12:30671437
showlangstatbar:30737416
vsctsb:30748421
pythonms35:30701012
03d35959:30757346
24365598:30736109
pythonfmttext:30731395
pythoncmv:30756943
fixshowwlkth:30771522
hideindicator:30785051
pythongtdpath:30769146
i26e3531:30780429
pythonnosm12tcf:30779713
pythonidxpt:30784022
pythonnocebcf:30776496
e537b577:30786199
dsvsc013cf:30789518

```

</details>

**Comment by Xpsp** [comment]
Uninstalling and reinstalling from snap solved the problem, my extensions and settings were not deleted.

**Comment by deepak1556** [comment]
Closing per above comment.
