### ISSUE TITLE
Explorer view auto closes after upgrade to 1.80.0

### ISSUE THREAD

**Issue by akhileshraju** [microsoft/vscode#188096]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.80.1
- OS Version: Ubuntu 18.04

## Steps to Reproduce:

Please see below recording

https://github.com/microsoft/vscode/assets/17533956/a606346f-20f9-4685-9eee-a86ce0964f72

## Notes

I tried doing the following from the command palette but see no different

- "View: Reset View Locations"
- "Developer: Reload With Extensions Disabled"

**Comment by aiday-mar** [comment]
Hey @lramos15, unsure if I should assign this to you, feel free to change

**Comment by lramos15** [comment]
If you right click the explorer when it's visible is there a check next to its name?

**Comment by akhileshraju** [comment]
@lramos15 It isn't checked.

![image](https://github.com/microsoft/vscode/assets/17533956/f923b6e9-5a62-4adc-8462-5aeecab72208)

Once I manually checked it, the issue no longer persists.

**Comment by lramos15** [comment]
Thanks for confirming, glad it's fixed 👍
