### ISSUE TITLE
Lack of lines or background color changes on panel/viewlet make it difficult to resize panes

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#18803]
- VSCode Version: code-oss-dev 1.9.0 (Commit unknown, Date unknown)
- OS Version: Linux x64 4.8.0-34-generic
- Extensions:

|Extension|Author|Version|
|---|---|---|

---

I noticed that the borders and background colors are gone in the light theme. This makes it very difficult to tell what is part of the panel and what is part of the editor. The viewlet and panel are also hard to grab since I needed to search for an invisible line to grab.

Master:

![image](https://cloud.githubusercontent.com/assets/2193314/22119887/21d81278-de32-11e6-93ea-bb3c7c9614fc.png)

Stable:

![image](https://cloud.githubusercontent.com/assets/2193314/22119845/f62f1cf2-de31-11e6-8344-16ddc91794d3.png)

The dark theme seems fine:

![image](https://cloud.githubusercontent.com/assets/2193314/22119931/48500ab4-de32-11e6-8fb3-6a5d017a5fcd.png)

**Comment by bpasero** [comment]
Maybe we should not remove the border we used to have given some themes might be broken now?

**Comment by bgashler1** [comment]
Yes, that doesn't look good in the "Quiet Light" theme.

We need to either 1) add back the top border or 2) use an equivalent rgba color that will always darken or lighten whatever it sits upon (depending on dark or light).

1 is simpler, judging that we are so close to code freeze.  We can work on exploring 2 or another option later.

**Comment by bpasero** [comment]
@bgashler1 to be fair, this does not look good either:

![image](https://cloud.githubusercontent.com/assets/900690/22138084/2b09f08e-dedf-11e6-907a-6eb91dfae6d8.png)

Maybe we should not have a separate background color at all then:

![image](https://cloud.githubusercontent.com/assets/900690/22138098/3ceac1d4-dedf-11e6-8d44-14bb71840233.png)

**Comment by bgashler1** [comment]
@bpasero perhaps until we have enabled full workbench UI theme awareness this might be the right choice.  Any word on when that will be in the product?  I think the red theme has always looked awful with our gray UI next to it.  Would be nice to get that in.

As a workaround, we could use an equivalent-looking alpha color that looks exactly as it does in light and dark theme today but would blend better in the color themes.
