### ISSUE TITLE
[go to reference] need some jump

### ISSUE THREAD

**Issue by JoeyZyuu** [microsoft/vscode#188033]
hello guys ,i dont know what i think is a feature or a bug?
what happen to me?

i use C/C++ EXTENSION for STM32 C language coding.
but when i push the button [go to reference ].it do not work ,it just show some REFERENCE at left by a new tab, do not jump ,do not report the error.
just show out at the left tab by a new page ,so i have to click the new tab page to see what i want.

is there a switch for show on reference tab or jump to reference?
i don't want my hands away from keyboard so when i just have to check out some reference.

thanks for watch ,have a nice day.
see yah.

BTW this is the png for what happen to me:
![image](https://github.com/microsoft/vscode/assets/31296263/920c7ae6-98c5-43ab-ba39-cf0d7d7cbbc2)

**Comment by jrieken** [comment]
You can use F4 and Shift+F4 to navigate the result of the references view
