### ISSUE TITLE
Cannot install extensions behind a Secure Web Gateway that enforces certificate checking

### ISSUE THREAD

**Issue by rdcoe** [Microsoft/vscode#18800]
Trying to install extensions to VsCode on RHEL in a VM that's behind a corporate SWG fails, even when the OS has a trusted root certificate.

VSCode
-
Version 1.8.1
Commit ee428b0eead68bf0fb99ab5fdc4439be227b6281
Date 2016-12-19T14:41:20.664Z
Shell 1.4.6
Renderer 53.0.2785.143
Node 6.5.0

OS
-
Linux localhost.localdomain 3.10.0-514.2.2.el7.x86_64 #1 SMP Wed Nov 16 13:15:13 EST 2016 x86_64 x86_64 x86_64 GNU/Linux

Steps to Reproduce:

1. Install RHEL in a virtualbox VM
2. Create a trusted root certificate that should get you through the inline proxy appliance, 
>$ sudo yum -y install ca-certificates
>$ sudo update-ca-trust enable
>$ sudo sh -c "cat > /etc/pki/ca-trust/source/anchors/internet-browsing-ca.crt" << "END"
>-----BEGIN CERTIFICATE-----
>...sha256...
>-----END CERTIFICATE-----
>END
>$ sudo update-ca-trust extract
3. launch vsCode and try to install an extension

What results:
getaddrinfo ENOTFOUND redhat.gallery.vsassets.io redhat.gallery.vsassets.io:443

**Comment by joaomoreno** [comment]
Can you join us in #18103?

**Comment by Bigous** [comment]
I would add that you cannot update or install or view readme behind any proxy (it was working prior to v1.8.1 and is not working after that version on any version).

![animation](https://cloud.githubusercontent.com/assets/6886560/26108316/86dde49e-3a22-11e7-927b-dbd74be25b8f.gif)

No error rises anywhere, yet it doesn't work... But VSCode itself updates very well, and can search and find extensions on the marketplace behind proxy...

**Comment by joaomoreno** [comment]
Merging with proxy documentation: #27838
