### ISSUE TITLE
Profile creation: choosing profile to Copy from sometimes unchecks all checkboxes

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#188139]
1. Create profile
2. Choose Copy from, select one of the profiles you already have
3. All the checkboxes get unchecked and there is an error message 🐛 

![Recording 2023-07-18 at 10 56 13](https://github.com/microsoft/vscode/assets/1926584/10d07f68-0c73-44b3-8361-e0a688c98cec)

**Comment by sandy081** [comment]
Fixed by 15af44e06f9a4de4dc7f3736001b380c386367d6
