### ISSUE TITLE
Automatically crrashed vscode

### ISSUE THREAD

**Issue by dipakp-logicrays** [microsoft/vscode#188155]
Type: <b>Bug</b>

Automatically crrashed vscode

VS Code version: Code 1.80.1 (74f6148eb9ea00507ec113ec51c489d6ffb4b771, 2023-07-12T17:22:25.257Z)
OS version: Linux x64 5.15.0-76-generic
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6440HQ CPU @ 2.60GHz (4 x 2600)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|3, 2, 2|
|Memory (System)|23.11GB (15.26GB free)|
|Process Argv|--unity-launch --crash-reporter-id 54ff3257-d3a4-4a4c-a514-754980f9f182|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|cinnamon|
|XDG_CURRENT_DESKTOP|X-Cinnamon|
|XDG_SESSION_DESKTOP|cinnamon|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (26)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|3.0.2
vscode-color|ans|0.4.5
vscode-intelephense-client|bme|1.9.5
jquerysnippets|don|0.0.1
xml|Dot|2.5.1
vsc-material-theme|Equ|33.8.0
vsc-material-theme-icons|equ|2.8.0
mithril-emmet|Fal|0.7.7
auto-close-tag|for|0.5.14
auto-rename-tag|for|0.1.10
vscode-graphql-syntax|Gra|1.2.2
php-awesome-snippets|hak|1.1.3
jquery-snippets|Hri|1.0.0
phpcs|ika|1.0.5
magento2-snippets|jer|0.1.2
php-constructor|Meh|0.1.2
vscode-apache|mrm|1.2.0
php-docblocker|nei|2.7.0
php-support-utils|ope|1.1.4
vscode-php-getters-setters|php|1.2.3
material-icon-theme|PKi|4.29.0
magento-devsearch|raf|1.0.0
phpcs|she|1.0.8
vscode-magento-wizard|vip|2.5.1
automagedev|Web|1.0.5
change-case|wma|1.0.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
vsccc:30610678
2e4cg342:30602488
pyind779:30671433
f6dab269:30613381
pythonsymbol12:30671437
showlangstatbar:30737416
vsctsb:30748421
pythonms35:30701012
a2ce3375:30757347
24365598:30736109
pythonfmttext:30731395
pythoncmv:30756943
fixshowwlkth:30771522
showindicator:30785052
pythongtdpath:30769146
i26e3531:30792625
pythonnosm12tcf:30779713
pythonidxpt:30784022
pythonnocebcf:30776496
e537b577:30786199
dsvsc013cf:30789518

```

</details>

**Comment by deepak1556** [comment]
Can you provide the crash report following the steps at https://github.com/microsoft/vscode/wiki/Native-Crash-Issues#creating-a-crash-report
