### ISSUE TITLE
Commenting shortcut

### ISSUE THREAD

**Issue by soljohnston777** [Microsoft/vscode#18812]
- VSCode Version: Code 1.8.1 (ee428b0eead68bf0fb99ab5fdc4439be227b6281, 2016-12-19T14:49:23.350Z)
- OS Version: Windows_NT ia32 10.0.10586
- Extensions:

|Extension|Author|Version|
|---|---|---|
|Bookmarks|alefragnani|0.10.2|
|numbered-bookmarks|alefragnani|0.6.0|
|code-gnu-global|austin|0.2.1|
|one-monokai|azemoh|0.2.4|
|vscode-icontheme-nomo-dark|be5invis|1.2.5|
|php-debug|felixfbecker|1.10.0|
|code-runner|formulahendry|0.6.5|
|rubyblue-theme|hirofumii|1.0.2|
|format-indent|Kasik96|1.3.0|
|cpptools|ms-vscode|0.9.3|
|autotrim|NathanRidley|1.0.6|
|theme-earlytorise|PasqNet|0.0.9|
|seti-icons|qinjia|0.1.3|
|code-spell-checker|streetsidesoftware|0.14.6|
|polscript|vitorfdl|2.1.0|

---

Steps to Reproduce:

1. comment a line ctrl /
2.highlight this line and the next line
3. press ctrl /

The first line will be // //  and the second line will be //.

Is there a  way to make it uncomment the first line then comment the second line when doing multiple lines?

**Comment by massimocode** [comment]
Yes there is a way. Highlight both lines, uncomment, then comment.

**Comment by soljohnston777** [comment]
Doesn't work unless you comment both lines then uncomment both lines.

**Comment by jangajack** [comment]
I think you're describing a behaviour change to toggle each line to the opposite comment state. I really don't see this happening because it introduces a new problem. e.g.

Step 1:
```
var x = 9;
// legitimate comment
x+= 45;
console.log(x);
```

Step 2: select all lines and _Ctrl-/_
```
// var x = 9;
legitimate comment
// x+= 45;
// console.log(x);
```

Under what conditions do you see this working properly?

**Comment by soljohnston777** [comment]
That's the whole point.  To comment and uncomment whole groups of code at a time.  It would be nice if it at least was an option :true false.  I go between new code and old code and switch back and forth for debugging.  So this would be a really handy feature to  toggle between commenting.

**Comment by jangajack** [comment]
I understand what you're asking for, and it may get added, or you could write it as an extension and map it to a different key command, but I don't think it would end up as a modification to the current Ctrl-/ command because of the above issue of making legitimate comments live code. There are at least 2 workarounds for your scenario that I can think of that would avoid the commenting and uncommenting the mentioned. The easiest is to add your 2 candidate blocks to an if else statement and toggle the variable that controls the statement.

**Comment by soljohnston777** [comment]
Even the option of an extension would be great! :)

**Comment by alexandrudima** [comment]
This feature request will not be considered in the next [6-12 months roadmap](https://github.com/Microsoft/vscode/wiki/Roadmap) and as such will be closed to keep the number of issues we have to maintain actionable. Thanks for understanding and happy coding!
