### ISSUE TITLE
Feature request: multiple cursors case retaining editing

### ISSUE THREAD

**Issue by wmertens** [Microsoft/vscode#18818]
Many times when I'm adjusting code, I'm copying it from some other code and then changing names that appear at different locations in camelCase. E.g. changing `userType` and `getUserMode` to `playerType` and `getPlayerMode`.

Using multiple cursors, you can case-insensitively match `user`, but when you then type `player`, the second word becomes `getplayerMode` and you need to go hunt for all the places were you need to fix it.

It would be great if multicursor could have a case retaining mode so that uppercase letters would be replaced with an uppercase letter. So, you'd select `user`, and the upper/lower shape of the selected words is retained while you are typing.

**Comment by wmertens** [comment]
I have come to the conclusion that all this feature would need is retaining the capitalization of the first letter of the selections that are being replaced.

The reason is that camelCase is consistent inside words, just not at the beginning of words.

If multiple cursors are used but no longer select something, there shouldn't be any capitalization retaining.

**Comment by cdfuller** [comment]
Related: #9798

**Comment by wmertens** [comment]
Hmm indeed this is a duplicate of #9798. Maybe just retaining initial case is a simpler feature but I'll close this anyway.
