### ISSUE TITLE
While editing multiline using ctrl + d if a right import suggestion is accepted, it will only effect on the first occurrence's spelling.

### ISSUE THREAD

**Issue by MirwaisAkrami** [microsoft/vscode#188151]
Does this issue occur when all extensions are disabled?: Not sure

While editing multiline using ctrl + d if a right import suggestion is accepted, it will only affect on the first occurrence's spelling.

- VS Code Version: 1.80.1
- OS Version: Windows 11  

Steps to Reproduce:

1. For example, in a file, I have a variable type called `UserService `and I want to change it to `CustomUserService` and there are at least two mentions of it, the type.
2. I select both of them using `ctrl + d` and start typing `Customuserservice`  **(Notice the small letter u and s in the name).**
After that I `ctrl + .` it for suggestions and when I accept the suggestion it will update the spelling of the first occurrence only and will leave the subsequent occurrences just like that.

**Comment by ArturoDent** [comment]
What command is `ctrl + .` bound to in the Keyboard Shortcuts editor?

**Comment by jrieken** [comment]
> After that I ctrl + . it for suggestions and when 

Please clarify if you mean: code actions, suggestions, or ghost text inline suggestions

**Comment by MirwaisAkrami** [comment]
Greetings @ArturoDent.
Sorry for the late reply, I was away for some time.
So here is the key bindings configured in my vs code.
![vscode-keybindings](https://github.com/microsoft/vscode/assets/34417742/703e8e68-79fe-434d-90d2-18a87d46891b)

And @jrieken, the action is a code suggestion, like you would import an object which you mentioned in your code.
