### ISSUE TITLE
Import profile does not install extensions in SSH remote

### ISSUE THREAD

**Issue by zero41120** [microsoft/vscode#188116]
Does this issue occur when all extensions are disabled?: N/A

```
Version: 1.81.0-insider (user setup)
Commit: 2f1013a310bbd74410e74fad99497841edad0eda
Date: 2023-07-13T05:33:32.822Z
Electron: 22.3.14
ElectronBuildId: 21893604
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Windows_NT x64 10.0.19045
```

Steps to Reproduce:

1. SSH into a remote server. 
2. Install extension in local, such as `Github theme`
3. Install extensions in the remote server, such as `Github Copilot`
4. Execute command: `Profiles: Export Profiles`, save the result on your local machine. 
5. SSH into another remote server.
6. Execute command: `Profiles: Import profiles`
7. In the preview, we will see the `Github theme` and `Github Copilot`
8. Confirm the import
9. Observe that `Github Copilot` is not installed

Many extension needs to be installed on the server for it to work.

**Comment by sandy081** [comment]
This is working for me. Please retry again with latest version and report back.
