### ISSUE TITLE
Extensions API consumption

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#1881]
- [x] win @SofianHn 
- [x] mac @jrieken 
- [x] linux @weinand 

We changed how extensions consume our vscode.d.ts file. Previously the vscode.d.ts file was always present in the node module and needed to be updated manually. With the new solution, we will download the right version of vscode.d.ts for the extension. See also: https://github.com/Microsoft/vscode/issues/970

**PreReq**: `npm install --g generator-code@next`

* Verify you can generate extensions in TS and JS and you get intellisense for our current stable release properly
* Verify you can specify a specific VS Code engine in `package.json` and after `npm install` you see intellisense for this specific version (e.g. `0.10.3`)
* Verify you can pick the same version as on our master branch and it gets downloaded from master (same works when picking * as version)
* Verify the version of the vscode.d.ts picked is the semver-minimal-matching versions of our released versions!

You can watch for the output of the `npm install` command to see what is going on under the hood:

```
> node ./node_modules/vscode/bin/install

Detected VS Code engine version: ^0.10.6
Found minimal version that qualifies engine range: 0.10.6
Fetching vscode.d.ts from: https://raw.githubusercontent.com/Microsoft/vscode/0.10.6/src/vs/vscode.d.ts
vscode.d.ts successfully installed!
````

**Comment by weinand** [comment]
@bpasero `node ./node_modules/vscode/bin/install` does not work for me since there is no `install`in the bin directory.

**Comment by bpasero** [comment]
@weinand I think something is still weird with your code generator. lets skip that generator and use the following generated sample (right click > save as and then rename from *.gif to *.zip):

![sample](https://cloud.githubusercontent.com/assets/900690/12588087/57ff114e-c457-11e5-9c0e-a85be32d724c.gif)

**Comment by weinand** [comment]
@bpasero yes, I had problems with the code generator. After two hours of investigation and removing npm modules from various locations I've learned the following:
On OS X and linux do not install npm modules globally ("-g") by using "sudo". Instead use the shell script available here: https://github.com/glenpike/npm-g_nosudo to configure npm so that it stores global modules in your home directory (without requiring "sudo").
