### ISSUE TITLE
disable backspace to delete slash commands for screen reader users

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#188102]
1. turn on a screen reader on Windows (JAWS/NVDA)
2. type `/createWorkspace` in the chat view
3. hit backspace
4. 🐛 hear "space'

@jooyoungseo said this is typical of a screen reader. We discussed using an audio cue to indicate deletion. We have concluded it would be better and simpler to just disable this feature for screen reader users.

![Recording 2023-07-17 at 11 24 13 (1)](https://github.com/microsoft/vscode/assets/29464607/39dc8a0c-86a1-474c-9ddb-05b617b6e28b)

**Comment by jooyoungseo** [comment]
@meganrogge -- After this meeting, something came to mind. What if I love the current command deletion behavior and would like to keep it? would you like to add a user setting to toggle this behavior for some advanced users?

**Comment by meganrogge** [comment]
We try to add settings sparingly because we want the default experience to be very nice. I will leave this with @joyceerhl to decide.

We could keep this behavior and mention it in the chat's accessibility help menu so a screen reader user is aware of what's happening.

**Comment by joyceerhl** [comment]
@jooyoungseo do you personally anticipate that you would use this setting to preserve the command deletion behavior?
Do you know why the screenreader reads 'space' on a deletion? If we can avoid that, would it be more reasonable that hitting backspace results in the screenreader announcing 'exiting `createWorkspace` mode'?

**Comment by meganrogge** [comment]
@joyceerhl we discussed that approach and agreed it would be too verbose. We should either use an audio cue, disable the feature, or provide a setting.

**Comment by joyceerhl** [comment]
Or mention it in the chat's accessibility help?

**Comment by meganrogge** [comment]
This is great @joyceerhl 👏🏼
