### ISSUE TITLE
Chat icon appears in sidebar but content remains blank

### ISSUE THREAD

**Issue by digitarald** [microsoft/vscode#188179]
Happens to me a few times when a new window opens. It seems the windows usually have history, so it might be a race condition when past state is loaded.

After startup, I open the secondary sidebar. Chat remains blank until I click the icon. Then the previous history is loaded and shown as expected.

<img width="388" alt="image" src="https://github.com/microsoft/vscode-copilot-release/assets/8599/460d6d19-2946-4f55-a0ce-077ae7b26bbb">

No errors in output or devtools.

**Comment by ivy-lmu** [comment]
I have a similar problem. Some views such as the debug console are not rendered after reloading or restarting. Instead, "Drag a view here to display." is shown. If the size of the sidebar is changed, the view appears. We also have this issue with a custom webview that we use in our extension.

Is there a known workaround to make the views in the sidebar work?

![issue](https://github.com/microsoft/vscode/assets/93579455/9bbc9a6e-1731-4547-8fe8-7ac6ea5c2e55)

**Comment by roblourens** [comment]
@ivy-lmu I think yours is just with focusing the view after reload? Does it appear if you click the icon?

Does the original issue with chat still show up?

**Comment by ivy-lmu** [comment]
> @ivy-lmu I think yours is just with focusing the view after reload? Does it appear if you click the icon?

Agreed, it's a matter of focus and unrelated to your issue. Clicking the icon does not help in my case.
