### ISSUE TITLE
[Proposal] Fractional Line Number Locations

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#18811]
I'm investigating syncing the scrolling of the markdown preview window to the editor. I have an implementation working using the `revealLine` command, but it is fairly jittery. In order to smooth out scrolling and continue using `revealLine` or similar existing apis, I believe that one approach would be supporting revealing line numbers that are not whole numbers.

![screen shot 2017-01-19 at 12 49 00 pm](https://cloud.githubusercontent.com/assets/12821956/22124732/e286b75a-de45-11e6-9059-3ba4751202ce.png)

I see two possible ways we could implement this:

* Use fractional line numbers to indicate the view line to reveal. In the example, a reveal of line `12.5` in the above document would reveal the third viewport line of line 12 in the editor. This still not allow entirely smooth scrolling since it would be locked to viewport lines, but it would be better than our current approach.

* Use fractional line numbers to indicate the progress between two lines. In this case, a reveal of line `12.5` would reveal the position halfway between line 12 and line 13 in the editor. This would not map to a specific line, so scrolling could be smoother.

Of course we could also investigate creating a new api to support this use case. Just tossing out some initial thoughts here to see what people think.

@kieferrm @egamma  @bpasero @jrieken: Any thoughts?

**Comment by dbaeumer** [comment]
@alexandrudima FYI

**Comment by alexandrudima** [comment]
@dbaeumer Thanks for including me 👍 

@mjbvz `TextEditor.revealRange()` takes as argument a `Range`. This means you can target any individual character you want inside a line, simply create a range that contains the interesting character.

**Comment by mjbvz** [comment]
@alexandrudima That may work. Let me prototype using `revealRange` in the markdown preview to see if this would be good enough for an initial preview->editor scroll sync implementation. My only concern right now would be what happens for long lines if the user has text wrapping turned off

**Comment by alexandrudima** [comment]
@mjbvz Cool, do let me know if `revealRange()` does not reveal the range. It should cover all cases, including view zones, wrapped lines, etc.

**Comment by mjbvz** [comment]
It seems to be working well enough currently using `revealRange`. We may revisit this problem in the future but closing for now
