### ISSUE TITLE
SCM: new git is leaking git processes.

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#18810]
No steps to reproduce but somehow I had many many many of git.exe processes running. Took 100% of my CPU

![capture](https://cloud.githubusercontent.com/assets/1931590/22123302/6d4a1a22-de8b-11e6-8ba2-be16e51804e9.png)

**Comment by joaomoreno** [comment]
I believe this is the lack of askpass. Just to confirm, can you show me the full command line of each of those processes?

**Comment by dbaeumer** [comment]
I will capture the command line the next time it happens.

**Comment by CherryDT** [comment]
I encountered the same - every time something in my repository was changed, either through VSCode itself or by manually using git, VSCode spawned hundreds of processes with `git.exe show :currently_opened_file.txt`.

Screenshot: https://db.tt/TgQdBskA29

**Comment by joaomoreno** [comment]
@CherryDT Thanks for this!

**Comment by joaomoreno** [comment]
This should now be fixed given the askpass support.

**Comment by aeschli** [comment]
@joaomoreno Any steps to verify?
