### ISSUE TITLE
Allow webview context menus triggered by primary click

### ISSUE THREAD

**Issue by hbons** [microsoft/vscode#188143]
I'd like to be able to use platform native menus in extensions that use a web view. This would allow for more complex controls, such as split buttons and gear menus.

Currently it's possible for extensions to [provide a context menu](https://code.visualstudio.com/api/extension-guides/webview#context-menus), but the menu can only be triggered using a secondary click (and there's no way to hack around this).

The only way to pop up a native menu is through misusing a `<select>` element. However this causes different cross-platform interaction and styling inconsistencies. It would be much better to be able to use a real menu.

Perhaps an option to the `data-vscode-context` attribute could be added. Something like `deviceButton: primary|secondary`.

```html
<textarea data-vscode-context='{
    "webviewSection": "editor",
    "deviceButton": "primary",
    "preventDefaultContextMenuItems": true
}'>
</textarea>
```

It would also be useful to define multiple context menus using names.

Advantages:
- No need to implement own menus that look out of place (that can't extend outside the web view area)
- Good looking and accessible native menus on every platform
- More consistency across the IDE
- More flexibility for extension authors

cc @alexr00 @daviddossett

**Comment by mjbvz** [comment]
You can simulate the event using `dispatchEvent`:

```ts
// Update to be on correct target
 document.body.dispatchEvent(new MouseEvent('contextmenu', {bubbles:true}));
 ```

This will open the native context menu

**Comment by hbons** [comment]
@mjbvz Thanks, I will try this out. Though this still only allows you to have a single menu?

**Comment by mjbvz** [comment]
> Though this still only allows you to have a single menu?

No you should be able to use `data-vscode-context` on the target to control what shows in the context menu

**Comment by hbons** [comment]
@alexr00 solved this for our case in the GitHub Create PR view.

Leaving the solution here so people who want to do the same may find it:

```js
<button data-vscode-context='{"preventDefaultContextMenuItems": true }'
    onClick={(e) => {
        e.preventDefault();
        e.target.dispatchEvent(new MouseEvent('contextmenu', { bubbles: true, clientX: e.clientX, clientY: e.clientY }));
        e.stopPropagation();
    }}
>
    Menu Button
</button>
```

Still I think it would be nice to have a simple API and a mention in the docs for this so extension authors know this is a UI possibility. :)

**Comment by joaomoreno** [comment]
> Still I think it would be nice to have a simple API and a mention in the docs for this so extension authors know this is a UI possibility. :)

@hbons Please go ahead and update the docs as wished. 👍
