### ISSUE TITLE
Self-destruct button for Codespaces

### ISSUE THREAD

**Issue by jtmaveryk** [microsoft/vscode#188172]
I'd like to see the ability to self-destruct a GitHub code space from internally inside the Codespace (File -> Self-destruct) & command palette, rather than having to return to the Codespaces page or repo to destroy it.

**Comment by chrmarti** [comment]
Please post question and suggestions for GitHub Codespaces at https://github.com/orgs/community/discussions/categories/codespaces. Thanks!
