### ISSUE TITLE
Participants to be able to request read/write access in live share

### ISSUE THREAD

**Issue by BrennaKent** [microsoft/vscode#188193]
Hi,
I was thinking of using the Live Share option in a coding workshop. I would like for participants to be able to request read/write access. Is it possible to allow participants to request read/write access that the person who started the Live Share session then approves or denies?

Thanks!

**Comment by lszomoru** [comment]
Please file an issue in [the extension's repository](https://github.com/MicrosoftDocs/live-share/issues). Thank you!
