### ISSUE TITLE
Launch config for "chrome" looks to use incorrect node version with nvm.

### ISSUE THREAD

**Issue by dm-marimosa** [microsoft/vscode#188153]
Type: <b>Bug</b>

Hi all,

I'm recently having the following issue when upgrading from VS Code 1.79.2 -> v1.80.2.

I have a angular client project with the following launch config:
```
{
  "version": "0.2.0",
  "configurations": [
    {
      "name": "ng serve",
      "type": "chrome",
      "request": "launch",
      "trace": true,
      "preLaunchTask": "npm: serve",
      "url": "http://localhost:4200/",
      "webRoot": "${workspaceFolder}"
    }
}
```

The project contains a .nvmrc file which contains the correct version number for this project "v16.14.2".

As per the NVM docs I have a script in my .zshrc file which auto switches the node / npm version based on the existence of this file.
When opening the project I can confirm the integrated terminal and the system terminal both report the correct node version using "node -v".

After upgrading to VS Code v1.80.2 when I try to launch the debug config I get an error message related to unsupported SSL "ERR_OSSL_EVP_UNSUPPORTED" (as expected), but the error message states that this step in the build was run using a later version of node:

```
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v18.12.0
```

There have been no changes to the project files, or the NVM setup between upgrading VS Code.

I have rolled back to VS Code v1.79.2 and the project builds without issue.
I have launched VS Code without extensions, and I'm still seeing the issue.
I have also tried the latest VS Code Insiders version, and the issue persists.

I'm not sure if there is any config I need to change after upgrading?
Any help would be appreciated & if I can provide any more information please ask.

Version Info:
Version: 1.80.1 (Universal)
Commit: 74f6148eb9ea00507ec113ec51c489d6ffb4b771
Date: 2023-07-12T17:20:23.298Z
Electron: 22.3.14
ElectronBuildId: 21893604
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Darwin arm64 22.5.0

VS Code version: Code 1.80.1 (Universal) (74f6148eb9ea00507ec113ec51c489d6ffb4b771, 2023-07-12T17:20:23.298Z)
OS version: Darwin arm64 22.5.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|4, 3, 3|
|Memory (System)|16.00GB (0.64GB free)|
|Process Argv|--crash-reporter-id abca7518-f9f8-461a-bb57-def014080292|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
py29gd2263:30792226
vscaac:30438847
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
3biah626:30602489
pyind779:30671433
f6dab269:30613381
pythonsymbol12:30671437
showlangstatbar:30737416
vsctsb:30748421
pythonms35:30701012
03d35959:30757346
pythonfmttext:30731395
pythoncmv:30756943
fixshowwlkth:30771522
showindicator:30785052
pythongtdpath:30769146
i26e3531:30792625
pythonnosmt12:30779714
pythonidxpt:30784022
pythonnocebcf:30776496
h7j2d465:30786200
dsvsc013:30789517
dsvsc014:30791935

```

</details>

**Comment by connor4312** [comment]
It seems like you're saying the version of npm in the prelaunch task is wrong

**Comment by dm-marimosa** [comment]
I'm not really sure if its the pre launch version thats wrong, if theres anything I can do to confirm, please let me know.

Just to confirm, I can check the version of node thats currently "in use" by checking in in the VS code terminal, and in the system terminal, which chows the version i expect (v16.14.2), but when clicking the "play" button to launch the interactive debugger, it triggers a build, but the build fails as the version of node it seems to be using is a later version (which I have installed, but not "active" with NVM).

This didn't happen in VS code v1.79.2

Again, if its a config change I need to make or if theres any more info I can produce, let me know,

Thanks

**Comment by meganrogge** [comment]
see https://github.com/microsoft/vscode/issues/187332#issuecomment-1710900350, seems like the same issue
