### ISSUE TITLE
Add ability to mute a getting started page for the extensions being installed through an extension pack

### ISSUE THREAD

**Issue by minsa110** [microsoft/vscode#188104]
Extension packs install multiple extensions, so when I install an extension pack, multiple "Getting Started" pages appear, which feels disruptive. Could we add the ability to mute the pages from appearing (though still leaving them accessible through the Start Page)?

**Comment by eleanorjboyd** [comment]
What is an example of an extension that has an extension pack with multiple getting started pages? Also is this skip walkthrough set by default?

**Comment by rzhao271** [comment]
Discussed with Bhavya and verified the issue using the `SunilYadav.azdsextns` extension pack in an empty profile. The walkthroughs don't show up on their own but extension-specific welcome views and notifications still show up.
