### ISSUE TITLE
Profile creation: disable button on error, and use warning instead

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#188140]
When there is an error can we rendered as disabled the Create button?
Also should we use a warning here, and not an error? Red error just feels too strong imho

![Screenshot 2023-07-18 at 10 57 32](https://github.com/microsoft/vscode/assets/1926584/141bb399-cc94-4ba4-83a9-c0f578959633)

**Comment by sandy081** [comment]
Unfortunately disabling the quick pick button is not supported.

Changed the validation messages to warnings
