### ISSUE TITLE
Getting suspended from Settings Sync

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#188275]
Started seeing this yesterday:

<img width="489" alt="image" src="https://github.com/microsoft/vscode/assets/22350/75e952f3-e15a-4aca-82c4-039cda20f42d">

I have not modified any extensions and/or profiles, yet Settings Sync seems to be pushing Extensions related data very frequently.

![image](https://github.com/microsoft/vscode/assets/22350/a03695fd-5873-47b0-b9b3-c290481dce58)

cc @Tyriar

**Comment by Tyriar** [comment]
@joaomoreno could you verify this one?
