### ISSUE TITLE
inconsistent behaviour of delete command in debug console under nodejs

### ISSUE THREAD

**Issue by jangajack** [Microsoft/vscode#18825]
- VSCode Version: 1.8.1
- OS Version: 1607 build 14393.693

- Node Version: 6.5.0

Steps to Reproduce:

1. Create a new project with a simple _app.js_ file.
2. Copy snippet below to _app.js_
```
'use strict';
var x = {first: "j", last: "s", age: 35};
console.assert(x.age == 35);
delete x.first;
console.assert(x.age == 35);
delete x['last'];
console.assert(x.age == 35);
delete x['notexist'];
console.assert(x.age == 35);
delete x.notexist;
console.assert(x.age == 35);
```
3. Make a _launch.json_ configuration with **type:** _node_ or _node2_
4. The file will run and complete without errors.
5. Place a breakpoint in the code on **line 8:** _delete x['notexist'];_
6. Manually type the following code line by line into the **Debug Console**
```
delete x['notexist'];
x;
delete x.notexist;
x;
```
7. Match to the output I am recieving:
```
delete x['notexist'];
"true"
x;
Object {age: 35}
delete x.notexist;
TypeError: Cannot convert undefined or null to object
x;
undefined
```

The behaviour shown is well outside what I would expect. I would expect that under strict mode _delete x['notexist'];_ would return a _TypeError_ and leave object x unchanged. The second operation _delete x.notexist;_ does return the error, but it also sets object x to _undefined_.

**N.B.** This only occurs under strict mode.

I have searched for an explanation for this behaviour and can't find one. If it is intentional I would appreciate understanding why.

**Comment by 44886** [comment]
路过

**Comment by roblourens** [comment]
I see this with 'node' but not 'node2'. Can you confirm that you still see this when you use node2? I don't see it with Chrome devtools either, and node2 should work the same as that.

**Comment by jangajack** [comment]
I wasn't careful when I was diagnosing this issue and inadvertently ran this configuration,
```
{
  // Use IntelliSense to learn about possible Node.js debug attributes.
  // Hover to view descriptions of existing attributes.
  // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
  "version": "0.2.0",
  "configurations": [
    {
      "type": "node",
      "request": "launch",
      "name": "Launch Program",
      "program": "${workspaceRoot}/app.js",
      "cwd": "${workspaceRoot}"
    },
    {
      "type": "node",
      "request": "attach",
      "name": "Attach to Process",
      "port": 9229 // node2 port
    }
  ]
}
```

Essentially I ran the 'node' type with the 'node2' port, however this also causes the issue. Also, you're correct that I can't replicate this in Chrome Dev Tools either. I assume the port number directly controls which version of node runs the code, and that the debugger connects to?

**Comment by roblourens** [comment]
No, the only thing that determines which debug adapter runs is the 'type'

**Comment by jangajack** [comment]
I see. This is getting into territory of VS Code and node that I am unfamiliar with. I have tested several conditions and here is what I have found. I have intermittently or consistently generated this error under each of these configurations (abbreviated):

```
{  // node with default port
      "type": "node", ...
},
{
      "type": "node",
      ...
      "port": 5858
}

{  // node with node2's default port
      "type": "node", ...
},
{
      "type": "node",
      ...
      "port": 9229
}

{  // node2 with default port
      "type": "node2", ...
},
{
      "type": "node2",
      ...
      "port": 9229
}

{  // node2 with node's default port
      "type": "node2", ...
},
{
      "type": "node2",
      ...
      "port": 5858
}
```

Also, heads up that you need to vary the input to see the result. If you follow the above instructions, pause at the breakpoint, MANUALLY enter the delete command and get the error, and then do the following:
- Restart the session _(Ctrl-Shift-F5)_
- Press up arrow, until the the delete command is available
- Enter
- You should notice a different behaviour from the first run (i.e. responds with true, and object is unmodified).
- Press up arrow again, until the delete command is available
- Modify the property name being deleted
- Enter
- The aberrant behaviour is back.

I've attached a clip.


[app.js.webm.zip](https://github.com/Microsoft/vscode/files/722347/app.js.webm.zip)

**Comment by roblourens** [comment]
Ok, but your video only shows running with 'node', and I agree that it reproes there. I just don't see it with node2. The port number won't make any difference.

**Comment by jangajack** [comment]
Yes. Here's a video of the same behaviour under node2. it shows identical results including the difference between typing the delete command from the debug panel, and using up arrow to retrieve the previously used delete command.

I'm also receiving the same behaviour running outside of strict mode.

[launch.json - classes - Copy - Visual Studio Code 2017-01-23 5_49_05 PM.zip](https://github.com/Microsoft/vscode/files/722792/launch.json.-.classes.-.Copy.-.Visual.Studio.Code.2017-01-23.5_49_05.PM.zip)

**Comment by roblourens** [comment]
Oh, weird. And very weird that you see it with vscode but not Chrome devtools. I'll try again. Can you tell me which Node version you're using?

Also your change to the port won't have any effect - that was in the attach config, but you were running the launch config.

**Comment by jangajack** [comment]
Node --version: 6.9.1
V8 --version: 5.1.281.84

The first video also contains an expanded watch of global process versions if you need any other process variables. I will try updating node and see if that helps.

**Comment by roblourens** [comment]
This fell by the wayside. @jangajack is it still a problem in node8?
