### ISSUE TITLE
https://delinaboutique.com/ar/%D8%B9%D8%B7%D8%B1-%D8%AC%D9%8A%D9%84%D8%AA%D9%8A-%D8%A8%D9%84%D8%A7%D9%83-%D8%A8%D9%88%D8%B1-%D8%A7%D9%88%D9%85-%D9%85%D9%86-%D9%82%D9%88%D8%AA%D8%B4%D9%8A-%D9%84%D9%84%D8%B1%D8%AC%D8%A7%D9%84-%D8%A7%D9%88-%D8%AF%D9%88-%D8%AA%D9%88%D8%A7%D9%84%D9%8A%D8%AA-90%D9%85%D9%84/p2099891936

### ISSUE THREAD

**Issue by lianshup7** [microsoft/vscode#188229]
Type: <b>Bug</b>

GUCCI

VS Code version: Code 1.80.1 (74f6148eb9ea00507ec113ec51c489d6ffb4b771, 2023-07-12T17:22:07.651Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-2520M CPU @ 2.50GHz (4 x 2492)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: unavailable_off<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: unavailable_off<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|3.87GB (0.72GB free)|
|Process Argv|--crash-reporter-id 27788f48-5cdd-49cd-a90f-3732ee5fb20f|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (92)</summary>

Extension|Author (truncated)|Version
---|---|---
random-sample|1nV|1.3.2
htmlplay|bia|0.0.10
exe-runner|bra|0.2.1
python-logger-vscode|bri|0.2.6
console-wrap-php-js-python|Cod|0.0.7
logical-properties|cod|0.1.11
beyond-debug|coo|0.9.15
logger|Dan|0.1.1
console-colored-logs|dar|0.0.23
vscode-markdownlint|Dav|0.51.0
vscode-eslint|dba|2.4.2
vscode-deno|den|3.19.1
githistory|don|0.6.20
gitlens|eam|14.1.1
EditorConfig|Edi|0.16.4
prettier-vscode|esb|9.19.0
esp-idf-extension|esp|1.6.4
git-project-manager|fel|1.8.2
vscode-firefox-debug|fir|2.9.8
godot-tools|gee|1.3.1
copilot|Git|1.96.255
cloudcode|goo|1.22.0
gc-excelviewer|Gra|4.2.57
aiquickfix|has|0.0.4
vscode-test-explorer|hbe|2.21.1
vscode-htmlhint|HTM|1.0.5
Ionide-fsharp|Ion|7.7.1
elixir-ls|Jak|0.15.3
vsc-fastbin|joz|0.1.1
vscode-tsc|joz|1.1.0
better-php-error-logger|mar|0.1.38
rainbow-csv|mec|3.7.0
log-line-number|med|0.0.2
metabob|Met|1.0.18
HTMLHint|mka|0.10.0
vscode-docker|ms-|1.26.0
csharp|ms-|1.26.0
dotnet-interactive-vscode|ms-|1.0.4313020
vscode-dotnet-pack|ms-|1.0.12
vscode-edge-devtools|ms-|2.1.2
vscode-ros|ms-|0.9.2
vscode-kubernetes-tools|ms-|1.3.13
python|ms-|2023.12.0
jupyter|ms-|2023.6.1101941928
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.17
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-slideshow|ms-|0.1.5
remote-containers|ms-|0.299.0
remote-ssh|ms-|0.102.0
remote-ssh-edit|ms-|0.86.0
remote-wsl|ms-|0.80.2
cmake-tools|ms-|1.14.34
cpptools|ms-|1.16.3
mono-debug|ms-|0.16.3
remote-explorer|ms-|0.4.1
test-adapter-converter|ms-|0.1.8
cordova-tools|msj|2.6.4
html-meta-tags-hero|nad|1.0.2
godot-csharp-vscode|nei|0.2.1
log-booster|nvi|0.0.7
gitlab-mr-notice-vscode|ppg|0.1.3
extended-html5-boilerplate|raj|0.0.1
java|red|1.20.0
vscode-yaml|red|1.13.0
LiveServer|rit|5.7.9
php-debug|rob|1.14.0
sample-ext|Rol|0.0.2
salesforcedx-vscode-apex|sal|58.6.2
salesforcedx-vscode-apex-replay-debugger|sal|58.6.2
salesforcedx-vscode-core|sal|58.6.2
twilight-vscode-extension|Sal|1.0.10
json-to-js-object|sal|0.0.4
vscode-php-test-explorer-docker|sat|1.0.5
scala|sca|0.5.7
metals|sca|1.23.0
vscode-css-custom-properties|Toc|0.0.5
pdf|tom|1.2.2
cmake|twx|0.0.17
c-cpp-flag-debugging|uts|0.0.1
intellicode-api-usage-examples|Vis|0.2.7
vscodeintellicode|Vis|1.2.30
vscode-java-debug|vsc|0.52.2023063003
vscode-java-dependency|vsc|0.23.0
vscode-java-test|vsc|0.39.0
vscode-maven|vsc|0.41.0
vscode-spring-initializr|vsc|0.11.2
vscode-icons|vsc|12.4.0
php-debug|xde|1.32.1
vsmarketplace-badges|Xua|1.0.3
markdown-pdf|yza|1.4.4
material-theme|zhu|3.15.18

(10 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
py29gd2263cf:30792227
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
2e4cg342:30602488
89544117:30613380
a9j8j154:30646983
showlangstatbar:30737416
vsctsb:30748421
a2ce3375:30757347
pythonfmttext:30731395
pythoncmv:30756943
fixshowwlkth:30771522
showindicator:30785052
pythongtdpath:30769146
i26e3531:30792625
pythonnosmt12:30779714
pythonidxpt:30784022
pythonnocebcf:30776496
h7j2d465:30786200
dsvsc013:30789517

```

</details>

```[tasklist]
### Tasks
- [x] ?
- [ ] https://github.com/microsoft/vscode/issues/188227
```

**Comment by starball5** [comment]
@sandy081 what is this issue ticket? spam? how often does spam happen in this repo?
