### ISSUE TITLE
Code --uninstall-extension shows Cancelled

### ISSUE THREAD

**Issue by jamarw** [Microsoft/vscode#18826]
- VSCode Version: 1.8.1
- OS Version: Windows 10 Version 1607

**Steps to Reproduce (--list-extensions) :**

1. Install two or more extensions using either the Marketplace or vsix packages.
2. Open a command prompt.
3. Run '--list-extensions'.

Result: Only the first installed extension is returned.  Screenshot below.

**Steps to Reproduce (--uninstall-extension) :**

1. Open a command prompt.
2. Run '--uninstall-extension [extension]'.

Result: The uninstall process appears to start but then is immediately cancelled. Screenshot below.

I am using the instructions found here: https://code.visualstudio.com/Docs/editor/extension-gallery#_command-line-extension-management

Thanks and please let me know if you need any additional information.

**Screenshot**
![image](https://cloud.githubusercontent.com/assets/11825888/22135140/1eec64c0-de81-11e6-8ef5-0e60f18ff844.png)

**Comment by joaomoreno** [comment]
The first problem: #17343 

I've renamed the issue for the second problem only.

**Comment by joaomoreno** [comment]
@sandy081 We can't have a choice service in Windows CLI: Jam3/devtool#58. stdin is just useless there.

**Comment by sandy081** [comment]
Saw that it is an issue in Electron. Did not know that our CLI is an electron process.. I thought it was just a node process. But good to know. Thanks.

**Comment by joaomoreno** [comment]
It is `electron.exe` which runs as Node. But still has this limitation, unfortunately.
