### ISSUE TITLE
保存.vue文件出现死循环，文件内容变成null

### ISSUE THREAD

**Issue by 44886** [Microsoft/vscode#18823]
- VSCode Version: Code 1.8.1 (ee428b0eead68bf0fb99ab5fdc4439be227b6281, 2016-12-19T14:49:23.350Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

|Extension|Author|Version|
|---|---|---|
|aessoft-class-autocomplete|AESSoft|0.1.0|
|php-autocomplete|bschulte|0.4.2|
|tortoise-svn|fantasytyx|0.1.1|
|auto-rename-tag|formulahendry|0.0.11|
|vscode-flatland-icon-theme|gebilaoxiong|0.0.6|
|format-on-save|gyuha|0.0.10|
|beautify|HookyQR|0.7.3|
|path-autocomplete|ionutvmi|1.4.1|
|format-indent|Kasik96|1.3.0|
|vue|liuji-jim|0.1.5|

---

Steps to Reproduce:

我安装的插件有：
![插件列表](https://pic4.zhimg.com/v2-8fc76e4e4b293f5e4d7fa281e960e5db_b.png)

**好了，下面是出现问题的具体过程：**

我在更新完home.vue之后，按ctrl+s保存，我开了保存时自动格式化代码。
![nothing](https://pic3.zhimg.com/v2-21b29e07d27692c22512933c3d7e16c6_b.png)

按了ctrl+s后，代码真的格式化了，但是上面标签中，文件名后面还是有个圆点：
![nothing](https://pic1.zhimg.com/v2-fdee0af967908137e20a737ba0ab7040_b.png)

然后，不管怎么按 ctrl+s，上面的加点都在，代码也没变动。
![nothing](https://pic2.zhimg.com/v2-1ddf5aaa9e79f2b551ab37c48f11ea65_b.png)

这个时候，电脑的风扇转速加快，看看任务管理器：
![nothing](https://pic2.zhimg.com/v2-5c2e70bbf517542b227a403179015d19_b.png)

如果现在在任务管理器中，强制结束vs code 进程，再去看 home,vue 文件内容就变成了 null

我把 beautify插件禁用掉，就没问题了，但是就不能格式化代码了。

我初步怀疑是：按下ctrl+s 后，保存会自动格式化代码，代码变动触发了自动保存，这样进入了死循环。

但，我把代码自动保存取消了，还是没解决问题。。。。。

**Comment by King66** [comment]
插件的锅吧，有些第三方写的插件有bug是会造成freeze的

**Comment by 44886** [comment]
有可能的，把 beautify 禁用了就好了

**Comment by King66** [comment]
你都找到问题了还提什么ISSUE

**Comment by innerlee** [comment]
translation:

Save a dirty file ``home.vue`` with ``auto format on save`` option on. The file will be formated. However, it is not saved even with more ``ctrl+s``. In the mean time, CPU will go crazy. Force terminate vscode, this file ``home.vue`` will become null. This will not happen if the ``beautify`` extension is disabled. The cost is that the file cannot be formatted...

**Comment by dbaeumer** [comment]
This issue was moved to HookyQR/VSCodeBeautify#93

**Comment by dbaeumer** [comment]
Moving to the beautify extension since this only happens if the extension is installed. It does do the formatting in this case.

**Comment by dbaeumer** [comment]
@innerlee thanks a lot for the translation.
