### ISSUE TITLE
new underlines for markdown headers cut into the scrollbar

### ISSUE THREAD

**Issue by amunger** [microsoft/vscode#188282]
create new notebook and add a markdown cell with
`# header`
ctrl+enter to preview the markdown

A new underline was added recently, and it cuts into the scrollbar slightly.

![image](https://github.com/microsoft/vscode/assets/2019016/b9a420ac-944a-4620-8014-6c25d63129dd)

**Comment by daviddossett** [comment]
This should be reverted now but @rebornix can confirm!

**Comment by mjbvz** [comment]
Fixed by #188335
