### ISSUE TITLE
Port User Settings functionality to Keyboard Shortcuts

### ISSUE THREAD

**Issue by tschwartz** [Microsoft/vscode#18822]
The User Settings as a single tab with search functionality works really well for exploring the Default Settings and adding them to your User Settings. It would be great if this same functionality was ported over to Keyboard Shortcuts.

This:
![image](https://cloud.githubusercontent.com/assets/1513268/22132461/0d6fd0a4-de6f-11e6-93e4-19e69d3cb0c9.png)
vs the current layout/functionality:
![image](https://cloud.githubusercontent.com/assets/1513268/22132449/f5680d78-de6e-11e6-9a3b-2d17c42b5146.png)

**Comment by dbaeumer** [comment]
@sandy081 FYI.

**Comment by sandy081** [comment]
This was planned for this milestone but got deferred to February.

**Comment by tschwartz** [comment]
Excellent, thanks!

**Comment by sandy081** [comment]
Duplicates #18095
