### ISSUE TITLE
terminal clear

### ISSUE THREAD

**Issue by MS-CZ** [microsoft/vscode#188287]
Type: <b>Bug</b>

Hi,
working with integrated terminal, I try to make keybinding to clear terminal/console. But when I try to use command via shortcut and then type some command/text in the terminal, it will add some extra lines. When I use command from upper right corrner (three dots)-> clear terminal, this does not happen. Also when I type directly command in the terminal "clear" or "cls" sometimes some text remains in the terminal (if I scroll up with mouse).

thx

VS Code version: Code 1.80.1 (74f6148eb9ea00507ec113ec51c489d6ffb4b771, 2023-07-12T17:22:07.651Z)
OS version: Windows_NT x64 10.0.19044
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10850H CPU @ 2.70GHz (12 x 2712)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.34GB (5.97GB free)|
|Process Argv|--crash-reporter-id 70b77f03-7a10-4082-9e67-aa309829d8a4|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
cortex-debug|mar|1.12.0
debug-tracker-vscode|mcu|0.0.15
memory-view|mcu|0.0.23
peripheral-viewer|mcu|1.4.6
rtos-views|mcu|0.0.7
cmake-tools|ms-|1.14.34
cpptools|ms-|1.16.3
cpptools-extension-pack|ms-|1.3.0
makefile-tools|ms-|0.7.0
vscode-serial-monitor|ms-|0.10.0
cmake|twx|0.0.17

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
py29gd2263cf:30792227
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
2e4cg342:30602488
f6dab269:30613381
showlangstatbar:30737416
vsctsb:30748421
03d35959:30757346
pythonfmttext:30731395
pythoncmvfstrcf:30756944
fixshowwlkth:30771522
showindicator:30785052
pythongtdpath:30769146
i26e3531:30792625
pythonnosmt12:30779714
pythonidxpt:30784022
pythonnocebcf:30776496
h7j2d465:30786200
h0f32768:30792100
dsvsc013cf:30789518

```

</details>

**Comment by MS-CZ** [comment]
Hi,
negative. Just tried with the latest and issue still persist.

![prtscrn](https://github.com/microsoft/vscode/assets/113538321/5fde202b-7235-48cc-877a-644c9dd22757)

**Comment by meganrogge** [comment]
a gif would help
