### ISSUE TITLE
can allow the badges from the following URL prefixes raw.githubusercontent.com,this is github user address

### ISSUE THREAD

**Issue by Liboq** [microsoft/vscode#188242]
Excuse me, can allow the badges from the following URL prefixes `raw.githubusercontent.com`,
like this `https://raw.githubusercontent.com/onekjs/onek-ui/c802217ddb48a6c3fd4afb3fe80fa4f2a8b27943/packages/onekjs-icons/src/svg/B.svg` 
![image](https://github.com/microsoft/vscode/assets/99778162/29a2f2dc-6d39-4c74-96eb-13091e696618)

**Comment by jrieken** [comment]
Not sure I understand what badges you mean. In extension's readme files or with the file decoration provider API?

**Comment by Liboq** [comment]
![image](https://github.com/microsoft/vscode/assets/99778162/2b694cab-7e50-4dbb-ac71-b1226be79227)
https://code.visualstudio.com/api/references/extension-manifest,this url :`raw.githubusercontent.com` want to  use

**Comment by jrieken** [comment]
Not really sure who owns this, starting with @joaomoreno

**Comment by joaomoreno** [comment]
We won't do this, since it defeats the purpose of this filter, since anyone can upload content to raw.githubusercontent.com
