### ISSUE TITLE
Trigger IntelliSense(code completions) like Copilot 

### ISSUE THREAD

**Issue by LeGi0N09** [microsoft/vscode#188239]
Can you add inbuild Bing Copilot to the visual studio code
It's Easy to people analyze cod end help in suggestion.
Features like this are already available in visual studio for suggestions and more.
It helps people to write code in and fast way
```[tasklist]
### Tasks
- [ ] new in-build Feature suggestion for vs code
```

**Comment by gjsjohnmurray** [comment]
Extensions already exist, perhaps most notably [GitHub Copilot](https://marketplace.visualstudio.com/items?itemName=GitHub.copilot).

**Comment by LeGi0N09** [comment]
> Extensions already exist, perhaps most notably [GitHub Copilot](https://marketplace.visualstudio.com/items?itemName=GitHub.copilot).

I mean VS Code In build Bing Copilot, not Github Copilot

**Comment by digitarald** [comment]
As commented before, [GitHub Copilot](https://marketplace.visualstudio.com/items?itemName=GitHub.copilot) provides AI-based code suggestions.
