### ISSUE TITLE
.ipynb Please border-hilight executing/active cell

### ISSUE THREAD

**Issue by p-i-** [microsoft/vscode#188295]
Type: <b>Feature Request</b>

I'm hitting shift+enter to execute cells in my notebook.
But it's _really_ hard to see which cell is currently executing, and when execution is finished it's _really_ hard to see which cell is now the active cell.

This could be solved so simply by using a thick yellow border around the OUTPUT of a currently-executing cell, and a thick GREEN border around the BODY of a currently active cell if no cell is executing.

Also, how about smooth-scrolling to make sure the currently-executing or currently-active(if none executing) cell remains on-screen?

Really, the current setup makes it needlessly hard to simply execute a notebook and track where I am in it.

You'd get such a massive bang-for-buck by tidying this up.

PS how about a minimap for the notebook that reflects this? And if we're debugging, and a breakpoint is hit that's NOT in the currently-executing cell, give it a dashed-yellow border.

PPS how about reddening the background for the OUTPUT of a cell that has terminated due to an error/exception?

VS Code version: Code 1.80.1 (74f6148eb9ea00507ec113ec51c489d6ffb4b771, 2023-07-12T17:20:23.298Z)
OS version: Darwin x64 22.5.0
Modes:

**Comment by amunger** [comment]
configuring `notebook.scrolling.revealNextCellOnExecute` could help with how the notebook is scrolled after execute.

Closing this as there hasn't been any supporting comments/votes
