### ISSUE TITLE
The counter should always have width >= height

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#1882]
IMHO, in the one digit case, there should be a min-width set to the oval such that the oval is either a circle or has its width larger than its height.

![image](https://cloud.githubusercontent.com/assets/5047891/12202793/dea2e656-b62b-11e5-9205-1e64ac201c3a.png)

**Comment by isidorn** [comment]
I made the count badge a bit rounder, so that it looks better in the single digit case.
Let me know what you think, imho now it looks better
