### ISSUE TITLE
VSCode Segfault when starting on Arch Linux

### ISSUE THREAD

**Issue by FirelightFlagboy** [microsoft/vscode#188254]
Does this issue occur when all extensions are disabled?: Yes

## Versions

- VS Code Version: 

  ```txt
  1.80.1
  74f6148eb9ea00507ec113ec51c489d6ffb4b771
  x64
  ```

- OS Version: 

  ```txt
  OS: Arch Linux x86_64
  Kernel: 6.4.3-arch1-2 
  DE: Hyprland
  ```

## Notable configuration

```json
{
  "password-store": "kwallet5",
  "enable-features": "UseOzonePlatform",
  "oxone-platform": "wayland",
  "enable-crash-reporter": true,
  "crash-reporter-id": "3c24d65b-3046-4b68-a003-e0c855714dd1"
}
```

## Steps

I'm able to sometime reproduce the issue with the following steps:

1. Start vscode (sometime it crash) 

My point of view when it crash:

vscode open a window, then the window is close instantly

## Logs

- [vscode-crash.log](https://github.com/microsoft/vscode/files/12092868/vscode-crash.log)
- [journalctl.log](https://github.com/microsoft/vscode/files/12092851/journalctl.log)
- [vscode-coredump-info.txt](https://github.com/microsoft/vscode/files/12092850/vscode-coredump-info.txt)

  > I can provide the core dump, if required

**Comment by deepak1556** [comment]
We don't support `"enable-features"` and `"ozone-platform"` in the runtime configure arguments, are you using a custom build of VSCode ? You would instead need to start with `code --ozone-platform=wayland`. Can you attach the crash report following the steps at https://github.com/microsoft/vscode/wiki/Native-Crash-Issues#creating-a-crash-report

**Comment by FirelightFlagboy** [comment]
Are you using a custom build of VSCode ?

No, i'm using the aur package `visual-studio-code-bin`

```
Name            : visual-studio-code-bin
Version         : 1.80.1-1
Description     : Visual Studio Code (vscode): Editor for building and debugging modern web and cloud applications (official binary version)
Architecture    : x86_64
URL             : https://code.visualstudio.com/
Licenses        : custom: commercial
Groups          : None
Provides        : code  vscode
Depends On      : libxkbfile  gnupg  gtk3  libsecret  nss  gcc-libs  libnotify  libxss  glibc  lsof  shared-mime-info  xdg-utils  alsa-lib
Optional Deps   : glib2: Needed for move to trash functionality [installed]
                  libdbusmenu-glib: Needed for KDE global menu
                  org.freedesktop.secrets: Needed for settings sync [installed]
                  icu69: Needed for live share
Required By     : None
Optional For    : None
Conflicts With  : code
Replaces        : None
Installed Size  : 337,82 MiB
Packager        : Unknown Packager
Build Date      : 2023-07-17T08:32:58 CEST
Install Date    : 2023-07-17T08:33:11 CEST
Install Reason  : Explicitly installed
Install Script  : Yes
Validated By    : None
```

---

What do you mean by 

> We don't support `enable-features` and `ozone-platform`

? Did you mean that we can't configure those option in `argv.json` ?

For me it work as expected :thinking: `vscode` don't use xwayland

Maybe they work because I have `~/.config/code-flags.conf` with the following content :thinking:

```
--enable-features=UseOzonePlatform
--ozone-platform=wayland
```

> Those parameters are from <https://wiki.hyprland.org/Getting-Started/Master-Tutorial/#force-apps-to-use-wayland>

---

Following <https://github.com/microsoft/vscode/wiki/Native-Crash-Issues#creating-a-crash-report>

Without any other configuration other than running `code` with `crash-reporter-directory`, I've the following `dmp` file inside the zip: [vscode-crash-dump.zip](https://github.com/microsoft/vscode/files/12168894/vscode-crash-dump.zip)

**Comment by deepak1556** [comment]
> Did you mean that we can't configure those option in argv.json ?

Yes that is correct, the aur package possibly added support for reading those values from `~/.config/code-flags.conf` which works in your case.

Thanks for the crash logs, the stack is similar to https://github.com/microsoft/vscode/issues/184124, I will merge this issue.
