### ISSUE TITLE
redundant info provided for chat slash commands

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#188200]
1. start typing a slash command
2. see or hear the slash command's description
3. accept it via tab
4. see or hear the slash command's description (ghost text) 🐛 

I think it would be better if the one we show as ghost text provides an example of what one might want to type

https://github.com/microsoft/vscode/assets/29464607/d3e0b0d2-3424-4e43-a0f2-58b96bc040ae

**Comment by roblourens** [comment]
I don't think that seeing the same description in the placeholder is an issue- there's many reasons I may not have seen or memorized the detail from the suggest widget and would find it useful to look at while I think about what to type. But showing an example might be nice too. Reminds me of the glob examples in the search view 

<img width="264" alt="image" src="https://github.com/microsoft/vscode/assets/323878/83709cb9-8ee1-4897-a545-84e6cc0b4ddc">

**Comment by meganrogge** [comment]
Yeah and tbh I struggle to sometimes know what to type when demo-ing so I imagine beginners are really puzzled without an example
