### ISSUE TITLE
Viewing images: limit background (check pattern) to image size

### ISSUE THREAD

**Issue by mac-pro** [Microsoft/vscode#18830]
- VSCode Version: 1.8.1
- OS Version: Fedora 24, 64 bit

Steps to Reproduce:

1. Open an image.
2. The background (check pattern) expands to the whole window.
3. ![screenshot_2017-01-20_14-27-10](https://cloud.githubusercontent.com/assets/21136418/22140050/b15a464c-df1c-11e6-86f6-dbddc6de9c3e.png)

Would you please limit the background to the image size only? The rest could be normal window color. It will help me a lot.

Thanks,

**Comment by bpasero** [comment]
This feature request will not be considered in the next [6-12 months roadmap](https://github.com/Microsoft/vscode/wiki/Roadmap) and as such will be closed to keep the number of issues we have to maintain actionable. Thanks for understanding and happy coding!
