### ISSUE TITLE
Cannot run tasks

### ISSUE THREAD

**Issue by skazarynau** [Microsoft/vscode#18838]
- VSCode Version: 1.8.1
- OS Version: Windows 7, 64bit

I have tasks.json that I use on several machines. But I cannot run tasks from it on one of machines.
vscode sees tasks from tasks.json but it doesn't perform them ("Ctrl+P", "task taskname"). When I press "Ctrl+Shift+B" I get an error:
spawn UNKNOWN

I tried to fully reinstall vscode (with deletion of %USER%/.vscode and and AppData/Roaming/Code). It doesn't help.

tasks.json:
{
    // See https://go.microsoft.com/fwlink/?LinkId=733558
    // for the documentation about the tasks.json format
    "options": {
        "cwd": "${workspaceRoot}/afolder"
    },
    "version": "0.1.0",
    "command": "cmd",
    "isShellCommand": true,
    "args": ["/C"],
    "showOutput": "always",
    "suppressTaskName": true,
    "tasks": [
        {
            "taskName": "cleanall",
            "args": ["python waf cleanall"]
        },
        {
            "taskName": "configure",
            "args": ["python waf configure"]
        },
        {
            "taskName": "buildall",
            "isWatching": false,
            "problemMatcher": {
                "owner": "cpp",
                "fileLocation": ["relative", "${workspaceRoot}/afolder"],
                "pattern": {
                    "regexp": "\\x22(.*)\\x22,\\s+line\\s+(\\d+):\\s+(Warning|Error):\\s+(.*)$",
                    "file": 1,
                    "line": 2,
                    "severity": 3,
                    "message": 4
                }
            },
            "isBuildCommand": true,
            "args": ["python waf buildall"]
        },
        {
            "taskName": "pwd",
            "args": ["cd"]
        }
    ]
}

**Comment by dbaeumer** [comment]
@skazarynau does it work if you open a command prompt and type the command on the Windows machine that is failing ?

**Comment by skazarynau** [comment]
Yes, all commands work from command prompt on that machine:
python waf cleanall
python waf configure
python waf buildall

There is following in env vars:
ComSpec=C:\Windows\system32\cmd.exe

**Comment by dbaeumer** [comment]
@skazarynau can you share a workspace that demonstrates the problem. That would ease tracking it down. Best a GitHub URL to clone :-)

**Comment by skazarynau** [comment]
@dbaeumer  Unfortunately I don't know how to reproduce this issue on other machines. I use the same vscode version, the same code and tasks.json on six machines. Two of them have this issue. Unfortunately I cannot share this code, but actually this issue doesn't depend on code. Because on these two machines I can create empty project, add tasks.json (this tasks.json or other) and I'll get this issue.

**Comment by skazarynau** [comment]
@dbaeumer When I'm trying to run task from task bar (using Status Bar Tasks extension), I get error "Error. Running the contributed command:'extension.run0' failed"

**Comment by dbaeumer** [comment]
@skazarynau one thing I noticed is that the command is cmd and isShellCommand is true. Since you start cmd.exe as the command isShellCommand should be false. Does that make a difference?

**Comment by skazarynau** [comment]
@dbaeumer I set isShellCommand false, but the result is the same.

**Comment by dbaeumer** [comment]
@skazarynau we have a new execution engine now that executes the task in the terminal having a more comparable environment to the command prompt.

Can you do the following:

- execute the command from the integrated terminal. Does it work ?
- switch the task runner to use the terminal (e.g. put `"version": "2.0.0") into the tasks.json. Does it work ?

**Comment by skazarynau** [comment]
@dbaeumer Unfortunately I don't have access to the machines with this issue any more. Sorry, I can't check it. So I think you can close this issue.

**Comment by dbaeumer** [comment]
@skazarynau thanks. Closing then.
