### ISSUE TITLE
cannot open settings

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#18836]
- VSCode Version: 1.9.x
- OS Version: macOS

Trying to open Settings now always results in this error:
![2017-01-20_09-47-12](https://cloud.githubusercontent.com/assets/1898161/22142296/07524e04-def6-11e6-9c4a-0f15b3244b79.png)

Before that I was able to open settings, searched for "update" in user settings, then switched to workspace settings where the problem occurred first.

**Comment by sandy081** [comment]
Duplicates #18557
