### ISSUE TITLE
Editor suggest widget should allow customizing filtering behavior

### ISSUE THREAD

**Issue by shadowCow** [microsoft/vscode#188301]
We maintain a custom scripting language and we use monaco as our code editor. We have our own language server that provides completion items for the suggest widget using the monaco.languages.registerCompletionItemProvider.

Our language has many statements with multiple words separated by whitespace. Example syntax:
```
I <action> in <context>

# such as...
I eat donuts in bed
```

Our language server has fuzzy matching logic to provide suggestions. It matches whole words regardless of their ordering.
Using the above example, if the user types:
```bed donuts```
we suggest
```I eat donuts in bed```.
We supply the correct fuzzy suggestions to monaco, but the suggest widget does not show them.

The reason it does not show them appears to be due to the built in filtering, specifically the `fuzzyScore` function in this file:
https://github.com/microsoft/vscode/blob/main/src/vs/base/common/filters.ts
That function filters out any suggestions which do not have the characters in the same order. So in our case, `donuts bed` would show our suggestion, but `bed donuts` will not.

We are able to work around this by populating the `filterText` field on the CompletionItem with the text that would be replaced. In the above example, the user has typed 'bed donuts', and if we set the `filterText` to 'bed donuts' it effectively bypasses the logic in `fuzzyScore`. 

We would like to have more direct control over what shows up in the suggest widget. In our case, ideally, we would like a way to say 'just show the suggestions that are provided by our CompletionItemProvider as-is'.

One solution might be to add a configuration option for the suggest widget to completely turn off the built in filtering.
e.g.
```
export interface ISuggestOptions {
  /**
   * Turn off built in filtering, so the suggest widget will always show all suggestions provided by the CompletionItemProvider
   */
  filter?: boolean;
```

**Comment by jrieken** [comment]
`filterText` is the way to go for this and it already allows to disable filtering or tweak it in other ways
