### ISSUE TITLE
Debugging Python Library ignores Breakpoints if File is outside of Directory

### ISSUE THREAD

**Issue by michaelweinold** [microsoft/vscode#188356]
Does this issue occur when all extensions are disabled?: N/A (Python extension required).

- VS Code Version: Version: 1.80.1 (Universal), Commit: 74f6148eb9ea00507ec113ec51c489d6ffb4b771
- OS Version: macOS, 13.4.1 (22F770820d)

Given this simple file structure:

```
.
├── vscode_debugging_test/
│   ├── debugging.py
│   ├── mylib_samedir.py/
│   └── subdir/
│       └── mylib_subdir.py
└── other_dir/
    └── mylib_otherdir.py
```

If I debug a cell in `debugging.py` and step into either `mylib_samedir.py` or `mylib_subdir.py`, everything works as expected. However, stepping into `mylib_otherdir.py` will ignore all set breakpoints. This is the case even if all directories are part of the same workspace. If 'step into' is selected, a new tab is opened that contains *a copy* of the `mylib_otherdir.py` file (located nowhere, according to the tab path hint):

<img width="436" alt="Screenshot 2023-07-20 at 11 22 13" src="https://github.com/microsoft/vscode/assets/23102087/effe7c86-c3c6-4262-a078-b09a77d56b0c">

Steps to Reproduce:

1. Create a sample Python script and set some breakpoints (🔴). Store in different locations as `mylib_samedir.py`, etc. according to the sample file structure.:

```python
def calculate_sum(a, b):
    result = a + b
    return result

def main():
    num1 = 10
    num2 = 20
🔴  print(f"Numbers: {num1}, {num2}")

    # Call the function with breakpoints
    sum_result = calculate_sum(num1, num2)
🔴  print(f"Sum: {sum_result}")

    return sum_result
```

2. Create a debugging file:

```python
import os
import sys
mylibrary_local_path = os.path.join(
    os.path.expanduser("~"),
    "github/vscode_debugging_test/mylibrary"
)
sys.path.append(mylibrary_local_path)

import mylibrary

# %%
test_result= mylibrary.main()
```

3. Debug the respective cells.

**Comment by michaelweinold** [comment]
@roblourens, were you able to replicate the issue, or should I provide further information?

**Comment by roblourens** [comment]
Please file this on the python extension, thanks
