### ISSUE TITLE
createTerminal shellArgs seems no effect 

### ISSUE THREAD

**Issue by guogaigai** [Microsoft/vscode#18835]
- VSCode Version: v1.8.1
- OS Version: Ubuntu 12.04 

Steps to Reproduce:

1. I try to use the createTerminal API to create a new terminal, and passed the args which used to set the environment , my code is below 
var shellArgs = ['PATH=/home/guogaigai/visualstudio/ReleaseCode/tizentvapp/tools/sdb/linux:$PATH'];
var sdbTerminal = vscode.window.createTerminal('SDB Command Prompt','' ,shellArgs);
sdbTerminal.show();

The terminal can display ,but the args I set seems no effect , but if I input PATH=/home/guogaigai/visualstudio/ReleaseCode/tizentvapp/tools/sdb/linux:$PATH in the terminal manually,it take effect . I think my args have no problem , but why it cannot effect directly , Can someone explain for me or told me the right form if I want to set environment when I creating a new terminal

**Comment by Tyriar** [comment]
Try this:

```ts
var sdbTerminal = vscode.window.createTerminal('SDB Command Prompt', null, shellArgs);
```

**Comment by guogaigai** [comment]
I have try the command ,var sdbTerminal = vscode.window.createTerminal('SDB Command Prompt', 'bash', shellArgs);  but error occured .
![fail1](https://cloud.githubusercontent.com/assets/18524505/22179026/7d1ef2e4-e082-11e6-802f-efed6768f9d2.png)

And If I used this var sdbTerminal = vscode.window.createTerminal('SDB Command Prompt', '/bin/bash', shellArgs);  error occured also 
![fail2](https://cloud.githubusercontent.com/assets/18524505/22179056/280714e8-e083-11e6-9f1f-56b0885a0ce0.png)

**Comment by guogaigai** [comment]
If I just want use your default integrated terminal , but I want to set environment  by command 'PATH=/home/guogaigai/visualstudio/ReleaseCode/tizentvapp/tools/sdb/linux:$PATH '  on linux and ' set  path=z:\visualstudio\ReleaseCode\tizentvapp\tools\sdb\win;%path%'  on windows when create terminal use your createTerminal API ,how should I do . These command are all effective if I input in the terminal manually, but  when I passed in the shellArgs , it just not effective .@Tyriar

**Comment by guogaigai** [comment]
By doing many tests , I found that the the shellArgs is only useful for the  shell passed , but I just want to use your default terminate and passed the shellArgs to it .  Is there any way to realize my request ? thanks @Tyriar

**Comment by Tyriar** [comment]
You're trying to modify `$PATH` when calling the terminal? It's not supported in VS Code's settings however you could probably tell bash/cmd to do it for you, something like this:

```
"terminal.integrated.shell.windows": "bash",
"terminal.integrated.shellArgs.windows": ["--rcfile", "<(echo '. ~/.bashrc; PATH=/home/guogaigai/visualstudio/ReleaseCode/tizentvapp/tools/sdb/linux:$PATH')"],
```

Which should run your .bashrc, then the `$PATH` change via:

```
bash --rcfile <(echo '. ~/.bashrc; PATH=/home/guogaigai/visualstudio/ReleaseCode/tizentvapp/tools/sdb/linux:$PATH')
```

Please refer to the bash man page and cmd's documentation for how to run a command and keep the shell open.

**Comment by guogaigai** [comment]
Yes , I want to modify $PATH when create terminal , and hope the modified $PATH take effect at the same time . I have tried your suggestion on linux , it just still not take effect.  I just don't now which form shellArgs can be accept by your API .@Tyriar

**Comment by Tyriar** [comment]
It's an array of string args. There are examples above and elsewhere online.
