### ISSUE TITLE
VS Code not respecting `editor.foldingImportsByDefault` for Java

### ISSUE THREAD

**Issue by wil93** [microsoft/vscode#188382]
Does this issue occur when all extensions are disabled?: Yes (tested on the vscode.dev instance)

- VS Code Version: vscode.dev
- OS Version: Mac OS

Steps to Reproduce:

1. Try folding the imports of a Java file (either with the `>` button or by setting `editor.foldingImportsByDefault` to true
2. The imports won't be folded (there is no `>` button)

<img width="664" alt="image" src="https://github.com/microsoft/vscode/assets/1285361/e238a350-a23f-4d8b-b798-7dba57da316c">

According to [this information](https://github.com/microsoft/vscode-docs/blob/9f69164ec2c1d8c9009e092c4637dfb1f06310ae/release-notes/v1_59.md#automatically-fold-imports), this should work out of the box for Java (i.e. with the default indent-based folding strategy)

<img width="1086" alt="image" src="https://github.com/microsoft/vscode/assets/1285361/ca9b9bef-69fd-4609-945e-6346b6c81925">

**Comment by aeschli** [comment]
Is the Java extension installed? It's the Java extension that will create the folding range for the imports.

**Comment by wil93** [comment]
No, I thought this was supposed to work without the Java extension (from the documentation linked above it sounds like it should...)

If it's not, then I guess the bug can be closed.

**Comment by aeschli** [comment]
No, with the Java extension you only get indentation based folding ranges
