### ISSUE TITLE
Can we add more compare options for diff3 merge conflictstyle

### ISSUE THREAD

**Issue by ZNackasha** [microsoft/vscode#188304]
Currently, when we have a conflict we have the option to compare changes. this will simply compare HEAD with the Incoming Change. Using diff3 as a conflict style you will also have the ability to see the base branch. we currently don't have a way to compare changes with the base branch. This can be very useful when you simply want to know what was changed between the base and the selected change.

my suggestion is to simply add two more options. "compare current changes with Base" and "compare incoming changes with Base"

here is a basic example

![image](https://github.com/microsoft/vscode/assets/11307112/16958732-7eb4-4d05-ba20-979f9b55d305)

**Comment by hediet** [comment]
Did you try the 3 way merge editor?

**Comment by ZNackasha** [comment]
> Did you try the 3 way merge editor?

3 way merge editor does not support diff3 conflictstyle very well

**Comment by hediet** [comment]
> 3 way merge editor does not support diff3 conflictstyle very well

How so? You can show the base!
