### ISSUE TITLE
Integrated Terminal can't paste anything(1.9.0-insider)

### ISSUE THREAD

**Issue by yyjazsf** [Microsoft/vscode#18833]
- VSCode Version: 1.9.0-insider f9e19d80f342779b49386fcf37b89387b3c353ac
- OS Version: 10.12.2 (16C67)

Steps to Reproduce:

1. copy any text
2. open Integrated Terminal
3. command + v or right click menu->paste
4. there's nothing
5. press return(enter) key ,the value success pasted here

the first time I open Integrated Terminal and paste,it's work, if I delete anything, It will doesn't work

setting.json
```
//terminal
    "terminal.external.osxExec": "iTerm.app",
    "terminal.integrated.shell.osx": "/bin/zsh",
    "terminal.integrated.fontFamily": "Menlo, Monaco, 'Courier New', monospace",
    "terminal.integrated.fontSize": 12,
```

**Comment by Tyriar** [comment]
By delete do you mean pressing the <kbd>delete</kbd> key break pasting? Are there any errors in dev tools console (Help > Toggle Developer Tools)?

**Comment by yyjazsf** [comment]
the last bug```if I delete anything, It will doesn't work``` I can't Reproduction，please deal with
1. copy any text
2. open Integrated Terminal
3. command + v or right click menu->paste(the Terminal has nothing)
5. press return(enter) key ,the value success pasted here

**Comment by Tyriar** [comment]
I can't repro, do you have any other details on your environment that may be useful in finding a repro?

Did you see any errors in the dev tools console?

**Comment by richarddavenport** [comment]
I'm having the same problem. [Here is what's happening.](https://drive.google.com/file/d/0BzemVqjE9kQoeFliaHIwakFWLVk/view?usp=sharing)
I have macOS 10.12.2
VS Code: 
<img width="284" alt="screen shot 2017-01-21 at 2 37 26 pm" src="https://cloud.githubusercontent.com/assets/3596012/22177624/2c2e406a-dfe7-11e6-9935-0f2f60283775.png">
I'm using oh-my-zsh.
So far what I can see is that four characters or less will work (keyboard or with the mouse), but five or more characters won't paste anything. However after you paste five or more characters and press enter, the pasted text shows up. At the end of my screen shot you can see it happen. Let me know if you need more info.

**Comment by Tyriar** [comment]
Hmm, well all 3 people who repro use zsh so that is probably the issue.

@yyjazsf do you use oh-my-zsh?

@rebornix have you been able to repro something like this?

**Comment by rebornix** [comment]
@Tyriar I can reproduce what @yyjazsf described.

**Comment by yyjazsf** [comment]
@Tyriar  year,i use Oh my zsh

**Comment by Tyriar** [comment]
Upstream issue: https://github.com/sourcelair/xterm.js/issues/511

**Comment by Tyriar** [comment]
Temporary workaround is to unbind oh-my-zsh's ctrl+s and ctrl+q keybindings with:

```
bindkey -r ^Q ^S
```

**Comment by maxruby** [comment]
Workaround (`bindkey -r ^Q ^S`) seems to work, but is there a timeline when this is likely to be "fixed" in the released version?  Thank you!

**Comment by yyjazsf** [comment]
@maxruby Version 1.10.0-insider  ad605ea39a832e4be2cbf77670781654056ef027  is ok,if you use Code - Insiders

**Comment by maxruby** [comment]
ok. Thanks, I will try.
