### ISSUE TITLE
Showing "end of central directory record signature not found" while installing extensions - Fedora 25, Proxy: None 

### ISSUE THREAD

**Issue by farhanali** [Microsoft/vscode#18831]
- VSCode Version: 1.8.1
- OS Version: Fedora 25
- Proxy: None

Steps to Reproduce:

1. Choose or search for extension
2. Tap install 

Listing extensions properly, not able to install any of those.

**Comment by joaomoreno** [comment]
Are you behind a proxy? Can you help us in #18103?

**Comment by farhanali** [comment]
No, I am not running behind a proxy

**Comment by joaomoreno** [comment]
You are very likely behind a proxy. Please help us in  #18103
