### ISSUE TITLE
Request `inlineValues` also on document open/change

### ISSUE THREAD

**Issue by bastiandoetsch** [microsoft/vscode#188339]
In the spec for LSP InlineValues are not restricted for debugging purposes. While the feature historically comes from debugging, this is rather a restrictive use for it not covered by the spec. 

Unfortunately, VSCode does not send the `textDocument/inlineValues` request to retrieve inline values when opening/changing a document or when receiving the refresh callback from the server. So, instead of the current, limited, behaviour, VSCode should treat inline values similar to CodeLenses and request them for a document, independent of debugging.

**Comment by dbaeumer** [comment]
This is independent of LSP.

**Comment by jrieken** [comment]
> In the spec for LSP InlineValues are not restricted for debugging purposes. 

They are specially designed for debugging purposes. 


Tho, you can use the inlay hint API which is similar but for general purpose use
