### ISSUE TITLE
Double finger click error

### ISSUE THREAD

**Issue by qqharry21** [microsoft/vscode#188352]
Type: <b>Bug</b>

Just use touchpad double finger in one click at the left/right sidebar to show the dropdown will cause some shadow error.

VS Code version: Code 1.80.1 (Universal) (74f6148eb9ea00507ec113ec51c489d6ffb4b771, 2023-07-12T17:20:23.298Z)
OS version: Darwin arm64 22.4.0

**Comment by andreamah** [comment]
Can you share a screen recording of this?

**Comment by qqharry21** [comment]
Here is the video!! Thanks for the reply

https://github.com/microsoft/vscode/assets/48307775/bdc3b6c5-ecb8-4a8a-9a72-1c05ce5001fe

**Comment by andreamah** [comment]
Where is the shadow issue in the screen recording?

**Comment by qqharry21** [comment]
I mean there were some afterimages when I used a double finger to click the bar icon, it caused touch-move behavior

**Comment by sandy081** [comment]
@bpasero I believe you were looking into touch related issues, hence assigning to you.

**Comment by bpasero** [comment]
I am/was not. I worked on trying to position the context menu properly, I think that is unrelated to this issue here.

**Comment by sandy081** [comment]
@qqharry21 Can you please provide the exact steps, video is unclear

**Comment by qqharry21** [comment]
Hey guys, sorry, so late to reply.
This issue has been solved. The issue arises from a Mac app called Swish, which has settings related to two-finger tapping on the top of windows. This causes problems with the SideNav in VSCode as it is considered part of the top area of the window.
