### ISSUE TITLE
keybinding conflict in inline chat

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#188317]
from @jooyoungseo

Say, you asked the first question “Create a simple JS function” [hit enter] and the second question “Create a simple Python function.” [hit enter] After then, you can navigate your prompt history in the multi-line input field via up/down/left/right standard arrows. This means the standard CMD+Left/Right/Up/Down navigation should be expected to be working as well.

Let’s say you want to go to the very first or last prompt history. On Windows, you can do this via Ctrl+Home/End. However, on Mac, you can’t achieve this via CMD+Up/Down arrow because of the key conflicts.

https://github.com/microsoft/vscode/assets/29464607/b5d0e8b9-7312-4271-a49d-09ceebb8751d

**Comment by jooyoungseo** [comment]
This applies to Jupyter Notebook as well. The discussion point here is then what would be the best alternative keybindings to go between input and output areas.

**Comment by meganrogge** [comment]
couldn't we solve this w a context key that indicates one is on the last line, last char in the input box for the down arrow case or the first line, first char for the up case ?

**Comment by meganrogge** [comment]
just like was done here https://github.com/microsoft/vscode/pull/187077

**Comment by jrieken** [comment]
> couldn't we solve this w a context key that indicates one is on the last line, 

Yes and not - you are on the last "model line" but not on the last "view line". The latter is the logic that accounts for line wrapping and the editor doesn't expose an API to know about view or wrapped lines. 

For now you can only disable the keybinding that does history navigation
