### ISSUE TITLE
Caret at wrong position when editing

### ISSUE THREAD

**Issue by FloMaetschke** [Microsoft/vscode#18832]
- VSCode Version: Code - Insiders 1.9.0-insider (f9e19d80f342779b49386fcf37b89387b3c353ac, 2017-01-20T07:12:07.780Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions:

|Extension|Author|Version|
|---|---|---|
|vscode-opennewinstance|chrisdias|0.0.4|
|npm-intellisense|christian-kohler|0.1.4|
|vscode-npm-source|dkundel|0.0.3|
|githistory|donjayamanne|0.1.2|
|KillTasksButton|dtrajano|0.0.4|
|CreateModule|HookyQR|0.0.5|
|task-master|ianhoney|0.1.37|
|output-colorizer|IBM|0.0.8|
|debugger-for-phantomjs|iradul|0.1.1|
|csharpextensions|jchannon|1.1.0|
|csharp|ms-vscode|1.5.3|
|debugger-for-chrome|msjsdiag|2.3.2|
|color-highlight|naumovs|1.2.1|
|material-icon-theme|PKief|1.1.4|
|qub-msbuild|qub|0.5.0|
|Material-theme|zhuangtongfa|1.0.3|
|html-css-class-completion|Zignd|1.0.3|

---

Steps to Reproduce:

1. Open any file in editor. 
2. Select any position in file an start editing

The caret is moved to the right in different distances depending on the position. (increase y = more distance to actual edit position)
When you click at e.g. position 4,20, the caret is moved to the right.. 

When you enter a key, the editor is editing at the correct position.

**Comment by alexandrudima** [comment]
@FloMaetschke Can you please share all your settings so I can try to reproduce?

**Comment by FloMaetschke** [comment]
Monday morning, back in office. The bug is gone. Maybe it is a problem with citrix? I will check it this evening from home again.

**Comment by alexandrudima** [comment]
@FloMaetschke I think it could be fontFamily / fontSize / zoomLevel related. Perhaps you were using a combination that triggers this?

**Comment by FloMaetschke** [comment]
yes.
	"editor.tabSize": "5",
	"editor.fontSize": 14,
	"window.zoomLevel": 1.0,
	"explorer.enableDragAndDrop": true,
	"explorer.autoReveal": true,
	

The thing is, it worked the whole time before when i was working from home.

**Comment by alexandrudima** [comment]
@FloMaetschke 

I have tried with today's build:
![image](https://cloud.githubusercontent.com/assets/5047891/22205977/75912130-e179-11e6-8c91-be5098e9ee0d.png)

on a fresh Windows7 machine with the settings:

```
{
"editor.tabSize": "5",
"editor.fontSize": 14,
"window.zoomLevel": 1.0,
"explorer.enableDragAndDrop": true,
"explorer.autoReveal": true
}
```

But I could not reproduce. I also tried zooming in/zooming out and I could also not reproduce. Is there anything more to it?

Please let me know, I'd like to get to the bottom of this.

**Comment by FloMaetschke** [comment]
I tried the citrix access again today from home. The problem is gone. I guess i had something to do with the citrix session or anything related to the remote access. 
The broken program was still running when i tried it at work, and the bug was not present.

Thx anyways.
