### ISSUE TITLE
[1.9.0-insider] text/x-code-output no longer works to identify identify output

### ISSUE THREAD

**Issue by formulahendry** [Microsoft/vscode#18839]
- VSCode Version: 1.9.0-insider
- OS Version: Windows 10

I use `text/x-code-output` (https://github.com/formulahendry/vscode-code-runner/blob/master/package.json#L196) to identify output window for output highlight.

Previously, it works like below:
![image](https://cloud.githubusercontent.com/assets/1050213/22146705/8465a9c8-df40-11e6-9f8f-2717bb481e46.png)

For 1.9.0-insider, it no longer works:
![image](https://cloud.githubusercontent.com/assets/1050213/22146672/6ddac152-df40-11e6-9fa6-d0873b02b383.png)

Is this change by design? If yes, is there other ways to do highlight for output window?

**Comment by bpasero** [comment]
Another popular colorer for output seems to behave differently but still shows colors, so I speculate this to be an issue with our changes in the editor.

Before:
![image](https://cloud.githubusercontent.com/assets/900690/22147840/0526d7d4-df0b-11e6-88b5-a1618248fdc3.png)

Now:
![image](https://cloud.githubusercontent.com/assets/900690/22147849/0a819b92-df0b-11e6-8ae7-17a43b2a858b.png)

**Comment by alexandrudima** [comment]
This is caused by the "loss" of the implicit `info-token`, `debug-token`, etc (that were coming from css). that we would have for all themes.

We could add these rules to all themes in the themeService.

https://github.com/formulahendry/vscode-code-runner/blob/master/syntaxes/code-runner-output.tmLanguage

**Comment by formulahendry** [comment]
Thanks @alexandrudima @bpasero @aeschli for the quick turnaround! Most of the colors are working now, while `token.string` is not working for Dark theme (it is working before).
Dark and Dark+ theme:
![image](https://cloud.githubusercontent.com/assets/1050213/22318420/6a0ee9b2-e3b5-11e6-920f-c6b29fec390e.png)
Abyss theme:
![image](https://cloud.githubusercontent.com/assets/1050213/22318471/e44bb372-e3b5-11e6-8e81-0ee5b3e04a94.png)
Kiebie Dark theme:
![image](https://cloud.githubusercontent.com/assets/1050213/22318482/0579ade2-e3b6-11e6-974e-0effa65eefe4.png)

BTW, is there any docs or code to guide how to use these token name in tmLanguage? 
I want to know:
* if any other token name I could use for colorizing
* wonder if I could use Color Code (e.g. `#FF0000`) directly in tmLanguage (the color of `token.string` for Abyss theme is too close to `token.info-token`)

Thanks a lot!

**Comment by aeschli** [comment]
Use 'string' instead of 'token.string'.
[Here](https://www.sublimetext.com/docs/3/scope_naming.html) is a list of common text mate scopes.
I added 'token.info-token' ... to stay compatible. Ideally you could use only standardised scopes.

**Comment by aeschli** [comment]
Marked as verified based on comment from formulahendry

**Comment by formulahendry** [comment]
Thanks @aeschli for the info! It is very helpful! 😄
