### ISSUE TITLE
Cannot type anywhere while webview is opened

### ISSUE THREAD

**Issue by alexdima** [microsoft/vscode#188354]
* I'm using GHPR which opens webviews for PRs
* Sometimes, when switching windows, focusing out, sleeping the laptop (I don't know exactly which steps), when I return to a window which has a webview opened, **I cannot type anywhere** until I close the webview.
* I'm raising this in case you know of any code done by the webview implementation which would "steal" inputs. The keydown events make it to main window, but text is never produced.

```
Version: 1.81.0-insider
Commit: c85bf61a82b0c39886b032d2634108782a55c637
Date: 2023-07-19T05:51:08.739Z
Electron: 22.3.14
ElectronBuildId: 21893604
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Darwin arm64 22.5.0
```

**Comment by mjbvz** [comment]
Webviews should not be able to steel input if another part of the editor is focused. When a webview is focused, then the webview gets the keyboard events and has to dispatch these events back to VS Code for them to be handled. Again though it should only be possible for that to kick in when the webview is focused (we just use the normal keyboard event apis)

Let me know if you are still seeing this. Haven't seen other reports
