### ISSUE TITLE
Diff editor flashes on save

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#188385]
* use on-save actions, esp remove unused imports
* edit inside diff
* save
* :bug: the editor flashes it diff-decoration on the scrollbar

```
"editor.codeActionsOnSave": {
    "source.fixAll.eslint": true,
    "source.removeUnusedImports": true,
  },
```

https://github.com/microsoft/vscode/assets/1794099/2751b901-0dea-40d4-b509-d1520ffc919f

**Comment by hediet** [comment]
I think this is also a bug in the code actions, as they emit an edit that has replaces text with the same text, effectively causing no change.

**Comment by jrieken** [comment]
> I think this is also a bug in the code actions, as they emit an edit that has replaces text with the same text, effectively causing no change.

Well, extension do what they do but it might be that for workspace edit we don't apply the "make more minimal" trick

**Comment by jrieken** [comment]
@hediet I have pushed change for the bulk edit service but leaving this open (and with you) in case you wanna tweak anything with the diff editor for this

**Comment by hediet** [comment]
This does not happen anymore (as I removed the optimistic update for now).
