### ISSUE TITLE
Move Debug console to menu bar

### ISSUE THREAD

**Issue by iamkartiknayak** [microsoft/vscode#188451]
As a Visual Studio Code user, I would like to request that the Debug Console be moved to the menu bar. Currently, the Debug Console is a floating window that can be overlap opened tabs. This can be inconvenient, especially when debugging large or complex applications.

Moving the Debug Console to the menu bar would solve this problem. The menu bar has plenty of unused space, and it would be a convenient location for the Debug Console. This would also make it easier to move around the Debug Console in the available free space.

**Comment by gjsjohnmurray** [comment]
I suggest you try `"debug.toolBarLocation": "docked"`

**Comment by iamkartiknayak** [comment]
I tried it but it makes the debug console hidden. I'm running code v1.80.1 on Debian  based Pop OS

**Comment by gjsjohnmurray** [comment]
As the setting description says, when docked the debug toolbar (it's not called the debug console) is only visible when you have picked Debug view on the Activity Bar.

**Comment by roblourens** [comment]
Yes there are a few options for that setting, find one that you prefer or drag the toolbar out of the way. Thanks @gjsjohnmurray
