### ISSUE TITLE
Terminal link tooltips are no longer showing up

### ISSUE THREAD

**Issue by jaminthorns** [microsoft/vscode#188435]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.80.1
- OS Version: 13.4.1 (c)

## Steps to Reproduce

1. Open the integrated terminal.
2. Bring up some content that has a link (e.g. a URL or a file path).
3. Hover over a link.
4. No tooltip is shown, unlike [in the documentation](https://code.visualstudio.com/docs/terminal/basics#_links).

## Video

https://github.com/microsoft/vscode/assets/6618434/1327966b-7494-4ebc-b31b-687d4802c1ef

**Comment by jaminthorns** [comment]
You're absolutely right, I completely forgot that I had enabled `terminal.integrated.showLinkHover` 🤦‍♂️ My bad, and thanks for looking at this!

**Comment by Tyriar** [comment]
Phew 😅
