### ISSUE TITLE
Keep commit box input while committing

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#18846]
1. Have a dirty file
2. Commit it -> while commit is in progress the file is still shown in the git viewlet
3. This is different than our stable behavior when the file would immediatly dissepear with the progress

The current behavior is acceptable but the problem is that I as many users are used to the previosu behavior and might think something is wrong (did commit take my file into account?)

**Comment by joaomoreno** [comment]
Please double check

**Comment by isidorn** [comment]
The difference is that the commit message in input disappears.
It should stay there as long as commit is in progress
