### ISSUE TITLE
Do we need the "Marketplace has extensions that can help with FILE_EXTENSION" flow?

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#188467]
When a user opens a file extension that does not have a specific recommendation tied to it, we show the general notification that points users to the marketplace. This has the following flaws:

- Most popular file types are already covered by specific extensions, so what gets left in this experience is leftovers
- For most of the extensions there is no good extension to handle this experience. Thus opening the Extension page does not provide value
- This is adding un-needed pings to the Marketplace service

Also we had a bug that this feature was not available in stable and only 3 users found it is not there https://github.com/microsoft/vscode/issues/180826

Would love for us to get some telemetry on this actions to see if this is actually bringing value to users. If not, we should either:
* Remove this flow completely
* Have a pre-defined set of file extensions for which we show this. Checking with tags seems to be very faulty. In my example below there is not an extension that helps with PowerPoint files.

![Screenshot 2023-07-21 at 10 44 36](https://github.com/microsoft/vscode/assets/1926584/cdfe2334-dac9-4a9e-b672-ed4f8597ff86)

**Comment by isidorn** [comment]
Majority of users do not click on the Search Marketplace.
Only 1.8% of these notifications end up being clicked on Search Marketplace

![Screenshot 2023-07-21 at 17 20 36](https://github.com/microsoft/vscode/assets/1926584/73196cdc-b318-4a85-8b7d-07848e97cc07)

When it is actually clicked here are the top extensions
![Screenshot 2023-07-21 at 17 23 08](https://github.com/microsoft/vscode/assets/1926584/65e7dd1c-5f8f-4d7b-87a0-50a98fb2ce67)

Thus I suggest that we:
* Remove this dialog
* Add explicit extension recommendation for `csv` and `pdf`. Since those seem to be missing.

@sandy081 what do you think?

**Comment by sandy081** [comment]
Sounds good to me 👍

**Comment by isidorn** [comment]
Great. Ok, you remove the dialog when you find time, I will add the recommendations for csv and pdf. 
Thanks 🙏

**Comment by sandy081** [comment]
Feel free to remove it in August, otherwise I can also do it in September. 

Here it is https://github.com/microsoft/vscode/blob/5e0c49cc9ece55017822d18720990be105412760/src/vs/workbench/contrib/extensions/browser/fileBasedRecommendations.ts#L160-L164
