### ISSUE TITLE
Cannot Apply Multiple Filters in the Extension Search

### ISSUE THREAD

**Issue by ltptnt** [microsoft/vscode#188483]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.80.1
- OS Version: Windows 11 Pro 22H2

Steps to Reproduce:

1. Select the Extensions tab and apply a filter
2. Apply another filter

![Steps](https://github.com/microsoft/vscode/assets/39490366/35e7401d-7ce8-4b92-b945-f5572176e4bc)

**Comment by gjsjohnmurray** [comment]
To apply multiple filters I think you need to type them in directly rather than using the menu-pick technique. Use that technique to learn about what is available.

**Comment by sandy081** [comment]
Please try the option @gjsjohnmurray mentioned.
