### ISSUE TITLE
no such file or directory

### ISSUE THREAD

**Issue by pythagoras512** [microsoft/vscode#188425]
Type: <b>Feature Request</b>

no such file or directory problem when i try to run a simple "hello world" on the visual studion code 

VS Code version: Code 1.80.1 (74f6148eb9ea00507ec113ec51c489d6ffb4b771, 2023-07-12T17:22:25.257Z)
OS version: Linux x64 5.15.108-18910-gab0e1cb584e1
Modes:

**Comment by raunakkumarsingh** [comment]
your terminal directory might wrong. can you send photo/ screenshot of your vs code
