### ISSUE TITLE
Syntax highlighting chooses incorrect style for theme with CSS child combinators

### ISSUE THREAD

**Issue by ambrosiogabe** [microsoft/vscode#188410]
Type: <b>Bug</b>

If you install this [grammar](https://marketplace.visualstudio.com/items?itemName=ms-vscode.js-atom-grammar) and this [theme](https://marketplace.visualstudio.com/items?itemName=akamud.vscode-theme-onedark) then you type in the following code (while using the theme installed and the language grammar installed):

```javascript
`${this.a + this.b}`;
this.a + this.b;
```

You can see that the `.`s in the interpolated string are colored green, where as the `.`s in the regular source code are colored gray. I believe this is wrong based on matched scopes for the dots in the interpolated string and the the theme.

Here's a screenshot illustrating this:
![Incorrect Syntax Highlighting](https://github.com/microsoft/vscode/assets/24964392/5b5ede8c-e6ca-4d4a-bf2a-24d9106d7da9)

If you take a look at the textmate scopes for the dot in `this.a` in the interpolated string, you should see the following scopes and styles matched:

```
textmate scopes   meta.delimiter.property.period.js
                  source.js.embedded.source
                  string.quoted.template.js
                  source.js

foreground        string
                  { "foreground": "#98C379" }
```

I believe this is wrong and should be:

```
textmate scopes   meta.delimiter.property.period.js
                  source.js.embedded.source
                  string.quoted.template.js
                  source.js

foreground        string > source
                  { "foreground": "#ABB2BF" }
```

There's a rule in the atom theme that looks like this:

```json
{
    "name": "String > Source,string Embedded",
    "scope": [
        "string > source",
        "string embedded"
    ],
    "settings": {
        "foreground": "#ABB2BF"
    }
},
```

You can see that if this theme is matched, then the token should be appropriately colored `#ABB2BF` , but it looks like the best match that is actually getting taken is just `string`. I believe the foreground color should be taken from the match `string > source` instead since the scopes for this specific char would indicate that this is a `source` that is a direct child of a `string`.

It could be that I'm misunderstanding how the CSS selection is supposed to work here, but based on the way the line is colored without the syntax highlighting, I believe that the CSS selection is misbehaving here. 

The reason I ran into this is because I'm developing my own syntax highlighter based off of Oniguruma's library and the Textmate grammars/themes. I was using VSCode to verify that my syntax highlighter is generating the correct styles, and realized that my syntax highlighter generated a different style in this case.

I hope this is helpful, and if there's any clarifications or additional context needed I'd be happy to provide it :)

VS Code version: Code 1.80.1 (74f6148eb9ea00507e
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz (8 x 3600)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|47.93GB (27.57GB free)|
|Process Argv|--crash-reporter-id fe9aaf51-02f5-427b-938f-45822f1d4a2b|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
py29gd2263cf:30792227
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
3biah626:30602489
f6dab269:30613381
2i9eh265:30646982
showlangstatbar:30737416
vsctsb:30748421
03d35959:30757346
pythonfmttext:30731395
pythoncmvfstrcf:30756944
fixshowwlkth:30771522
hideindicator:30785051
pythongtdpath:30769146
i26e3531:30792625
pythonnosmt12:30779714
pythonidxpt:30784022
pythonnoceb:30776495
h7j2d465:30786200
dsvsc013:30789517
cmakesidepanelv2:30779593

```

</details>

**Comment by aeschli** [comment]
Our text mate engine doesn't support the `>` operator.
Issue is https://github.com/microsoft/vscode-textmate/issues/123
