### ISSUE TITLE
Debugger state does not restore on page load/reload

### ISSUE THREAD

**Issue by bosmart** [microsoft/vscode#188413]
Python/Jupyter debugger state does not restore on page load/reload. Reproduce by:
1. put a breakpoint anywhere in your .py or .ipynb file
2. run the debugger and wait for it to hit the breakpoint
3. reload the page or paste the URL into another browser window - the debugger is off

Looks like it's not a Python/Jupyter issue but a general debugger issue - see https://github.com/coder/code-server/issues/6173

Version: 1.80.1
Commit: 74f6148eb9ea00507ec113ec51c489d6ffb4b771
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.5.2 Safari/605.1.15
Embedder: codespaces

**Comment by bosmart** [comment]
Actually, it's even worse - if you have running cell in Jupyter and reload, the cell is no longer running.

**Comment by roblourens** [comment]
What do you mean by "page" here? The vscode window? The python file will not actually still be running after a reload

**Comment by bosmart** [comment]
Yes, I mean when I reload the browser tab. How come Python won't be running anymore, I would have thought be using the same exact URL I am connecting to the same "session"?

**Comment by roblourens** [comment]
No, your program will stop running when vscode is disconnected
