### ISSUE TITLE
file explorer 

### ISSUE THREAD

**Issue by hibee-code** [microsoft/vscode#188469]
Type: <b>Feature Request</b>

i cant create a new folder, also can't view my side bar where i can find source code and open a new folder

VS Code version: Code 1.80.1 (74f6148eb9ea00507ec113ec51c489d6ffb4b771, 2023-07-12T17:22:07.651Z)
OS version: Windows_NT x64 10.0.19045
Modes:

**Comment by gjsjohnmurray** [comment]
I suggest you press F1 to get the Command Palette, then run `View: Reset View Locations`

**Comment by hibee-code** [comment]
I press f1 but directed me to browser direct me to browser not showing the command palette

**Comment by lramos15** [comment]
Try `CTRL + SHIFT + P`

**Comment by lramos15** [comment]
Closing for lack of update
