### ISSUE TITLE
alt+F3 accessibility shortcut conflicts with "Show next change"

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#188442]
I think may be a somewhat popular command so you might want to rethink this

![image](https://github.com/microsoft/vscode/assets/323878/c7239288-a887-4a07-b606-ce9c0015beb2)

**Comment by meganrogge** [comment]
i'm struggling to find a keybinding that's not in use

**Comment by meganrogge** [comment]
maybe `Shift + alt + f1`

**Comment by Tyriar** [comment]
Shift+alt+f1 is nice 👍
