### ISSUE TITLE
window.onDidWriteTerminalData should listen to all future terminal data events test failure

### ISSUE THREAD

**Issue by TylerLeonhardt** [microsoft/vscode#188436]
Build: https://dev.azure.com/monacotools/a6d41577-0fa3-498e-af22-257312ff0545/_build/results?buildId=224469
Changes: https://github.com/Microsoft/vscode/compare/28e972e...696f968

specifically: https://dev.azure.com/monacotools/Monaco/_build/results?buildId=224469&view=logs&j=9833cdaa-2e92-5f8d-56a8-239fd18fd628&t=efbaf268-cf98-50c2-bb3c-7950770fd6bc&s=a56e7651-4213-56af-9488-c25fe636c10c

**Comment by bpasero** [comment]
This looks like https://github.com/microsoft/vscode/issues/188375

**Comment by TylerLeonhardt** [comment]
Yep a duplicate
