### ISSUE TITLE
install,open,fail

### ISSUE THREAD

**Issue by littleboss01** [microsoft/vscode#188473]
VS Code Version:Microsoft Windows 10 企业版 LTSC（10.0.19044）
VS Code Version:1.80.1(user setup)

Steps to Reproduce:
1.Install
2。open

```
C:\Program Files\Microsoft VS Code>
[main 2023-07-21T07:24:55.271Z] update#setState idle
[6636:0721/152456.525:ERROR:electron_api_utility_process.cc(123)] Failed to create null handle: 系统找不到指定的文件。 (0x2)


```

**Comment by shellvon** [comment]
please see https://github.com/microsoft/vscode/issues/185298#issuecomment-1736864708

**Comment by Jonte9210** [comment]
> VS Code Version:Microsoft Windows 10 企业版 LTSC（10.0.19044） VS Code Version:1.80.1(user setup)
> 
> Steps to Reproduce: 1.Install 2。open
> 
> ```
> C:\Program Files\Microsoft VS Code>
> [main 2023-07-21T07:24:55.271Z] update#setState idle
> [6636:0721/152456.525:ERROR:electron_api_utility_process.cc(123)] Failed to create null handle: 系统找不到指定的文件。 (0x2)
> ```

**Comment by rzhao271** [comment]
Closing due to lack of response from the issue author. Let us know if the issue still occurs for you on VS Code 1.96.
