### ISSUE TITLE
Git - viewlet doesn't update after a git init 

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode#18840]
In a fresh workspace: 
- git init
- git add .

The changes do not do not show up in the SCM viewlet and I have to reload the window.

**Comment by joaomoreno** [comment]
Fixed in 163267821cf7d2b6b8b556778ceace1ea742ed0b

**Comment by bpasero** [comment]
Does not work for me:
* empty folder
* add 1 file
* open SCM viewlet
* open integrated terminal
* git init & git add .

=> nothing happens

Btw in the console I also see this: 

![image](https://cloud.githubusercontent.com/assets/900690/23306478/01f854d4-faa4-11e6-81d1-050553cad231.png)
