### ISSUE TITLE
Revisit `isSaving` change for notebooks and custom editors

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#188452]
Filing this issue here to keep https://github.com/microsoft/vscode/issues/140069#issuecomment-1645085159 in mind and planned for the current iteration.

**Comment by amunger** [comment]
good call - custom editors do not get saved if they are closed <1s after an edit, so I'll just revert that change.

Notebooks do get saved tho, and we have reduced to only a simple provider now, so it's probably taken care of through the working copy service. I can keep looking to make sure we're not trying to dispose of it early tho

**Comment by amunger** [comment]
For notebooks, it looks like an extra reference is held to the working copy while it is dirty, so it isn't disposed until after it is saved and becomes non-dirty. https://github.com/microsoft/vscode/blob/main/src/vs/workbench/contrib/notebook/common/notebookEditorModelResolverServiceImpl.ts#L97

So, this looks safe for notebooks from what I can see, but let me know if there's still something else I should be looking at.

**Comment by bpasero** [comment]
@amunger yes, that piece is critical and should be sufficient from a working copy perspective.

Working copies are meant to be somewhat independent from the editors they are edited in. For example, you can change working copies and save them all without any opened editor. We do this for example in text files to support workspace edits over many files, such as search/replace.

For notebook working copies, the key question is whether there is anything setup/disposed during the lifecycle of a notebook editor that is required for the save to function? In other words, is there any kind of disposal happening when a notebook editor closes that is required to implement the methods that the working copy needs for saving? Essentially, does [`snapshot`](https://github.com/microsoft/vscode/blob/ab8498ab2a4bb8772034fad14a48b0a41b635caa/src/vs/workbench/services/workingCopy/common/fileWorkingCopy.ts#L77) continue to work to retrieve the contents from the extension? And with the relative new changes we did to make saving of large remote notebooks faster, does the optional [`save`](https://github.com/microsoft/vscode/blob/ab8498ab2a4bb8772034fad14a48b0a41b635caa/src/vs/workbench/services/workingCopy/common/storedFileWorkingCopy.ts#L80) method work (cc @rebornix)?

**Comment by bpasero** [comment]
@amunger oh, I forgot one other case: it is possible for the save operation to fail. In that case, we force reopen the file (at least as far as I can remember). So the additional test to make is whether this works:
* auto save is on
* notebook is changed and quickly closed
* save fails (something we probably can best test running out of sources)
* does the notebook reopen? how does the user deal with the error now?

**Comment by amunger** [comment]
I played around with this myself and I'm planning to revert because:
after the save fails, the file no longer shows dirty at all - there is no error state for the notebook editor, so it always claims that it is just about to save.
That makes it hard to understand that there are unsaved changes.
