### ISSUE TITLE
Misleading error message when Language Server doesn't support range formatting

### ISSUE THREAD

**Issue by rotu** [microsoft/vscode#188441]
Type: <b>Bug</b>

1. Install extension `denoland.vscode-deno` and enable it for a project.
2. Open a TypeScript file.
3. Select a range, choose "Format Selection With..." and choose the Deno extension

Observe the error message:
> Extension 'Deno' is configured as formatter but it cannot format 'TypeScript'-files

This is misleading, as the Deno Language Server does support TypeScript files. It supports [document formatting](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textDocument_formatting) but not [range formatting](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textDocument_rangeFormatting).

Further, setting `editor.formatOnSaveMode: "modificationsIfAvailable"` or `"modifications"` gives the same misleading error message on save.

Originally reported at https://github.com/denoland/vscode_deno/issues/860

VS Code version: Code 1.80.1 (74f6148eb9ea00507ec113ec51c489d6ffb4b771, 2023-07-12T17:20:58.115Z)
OS version: Darwin arm64 23.0.0
Modes:

**Comment by jrieken** [comment]
> Select a range, choose "Format Selection With..." and choose the Deno extension

This doesn't reproduce for me, having TS and deno installed and I do not see that option because not two or more range formatter are installed, it's just TS

**Comment by jrieken** [comment]
To verify follow these steps https://github.com/microsoft/vscode/issues/188441#issuecomment-1838998422 and ensure the message is good
