### ISSUE TITLE
Add ability to run multiple background/watching tasks

### ISSUE THREAD

**Issue by trsrm** [Microsoft/vscode#18842]
Currently, it is possible to run only one watching task.
But often it is required to run multiple background tasks to start the project (e.g. "`npm run-script start-server`" and "`npm run-script start-client`").

**Comment by dbaeumer** [comment]
This is in the pipeline...

**Comment by dbaeumer** [comment]
This got addressed by the new terminal runner. To make use of the new terminal runner please see: https://code.visualstudio.com/docs/editor/tasks#_convert-from-010-to-200
