### ISSUE TITLE
Diffing two empty files shows them as having changes

### ISSUE THREAD

**Issue by troy351** [microsoft/vscode#188470]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.80.1
- OS Version: macOS 13.4.1

Steps to Reproduce:

1. Diff two empty file
2. Notice the diff view shows "removed" and "added" lines

This issue is the same as #113318 but happens again

**Comment by hediet** [comment]
Can you share a screenshot?

**Comment by troy351** [comment]
An empty file compare to itself
<img width="1033" alt="image" src="https://github.com/microsoft/vscode/assets/8372385/05cc0b4b-9147-4081-8b47-3974cfdfc59b">

**Comment by hediet** [comment]
I see, thanks!

**Comment by hediet** [comment]
To verify:
Select latest dev version and notice there is no red/green in this [playground example](https://microsoft.github.io/monaco-editor/playground.html?source=v0.42.0-dev-20230809#XQAAAAJeAgAAAAAAAABBqQkHQ5NjdMjwa-jY7SIQ9S7DNlzs5W-mwj0fe1ZCDRFc9ws9XQE0SJE1jc2VKxhaLFIw9vEWSxW3yscw1xCuRgmSatbNyrNa50VLHWwDOn0YI7IfU0xJ0CGYU1vRtgnKPmZzQcQ1IYSLB-5f-1dobOlrSyV9lhyCGfRbJKMlXoXkAdw6yLc98V7O9Hqvl4iUtnQbNbQkCHeHnpPvtuLhi58mq60wYB1vMf4QmkKnGznhGL8li6dWhWKShyzCwTC7CsUc34JvxSeg3uQQWJy8qUS5MVxSIg5_dsRpy-utvR_90McuCFiEpwHBassyKchKAzkeVzAo7onzbpIV1433I2FlkhVMISJCmgnaVWBAEGd4IkMzB1W4dRFuSHSnye-ZfY9wglAutTQVSFy2iEcL1Rp_3rDCQ3MTdJkW_j-1Vv0kbN5wRE6dtLa2O_rs4y5UGfv_JYrPAA).

**Comment by aiday-mar** [comment]
The issue is verified. I am wondering if we want to see the commands starting with `Compare active file with` when there is no active file? I see this command while I have no active text editor.
