### ISSUE TITLE
VS code keeps terminal hostage when launching

### ISSUE THREAD

**Issue by Ceelbc** [microsoft/vscode#188426]
Type: <b>Bug</b>

Go to your project folder in Windows 11.
Right click & press 'open in terminal' (alternatively: 'open powershell here')
type the powershell command: code ./; exit
This should launch vs code with the current folder as project root, and close the terminal window.
However, it keeps the terminal window opend.
When closing vs code; the terminal does close as well.

VS Code version: Code 1.80.1 (74f6148eb9ea00507ec113ec51c489d6ffb4b771, 2023-07-12T17:22:07.651Z)
OS version: Windows_NT x64 10.0.22621
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-10210U CPU @ 1.60GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.76GB (6.36GB free)|
|Process Argv|./ --crash-reporter-id 343c61fb-4136-4991-8224-0b18616cfa50|
|Screen Reader|yes|
|VM|50%|
</details><details><summary>Extensions (27)</summary>

Extension|Author (truncated)|Version
---|---|---
dart-code|Dar|3.68.1
flutter|Dar|3.68.0
gc-excelviewer|Gra|4.2.57
todo-tree|Gru|0.0.226
vue-snippets|hol|1.0.4
vscode-docker|ms-|1.26.0
isort|ms-|2023.10.1
python|ms-|2023.12.0
vscode-pylance|ms-|2023.7.30
jupyter|ms-|2023.6.1101941928
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.17
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-slideshow|ms-|0.1.5
remote-containers|ms-|0.299.0
remote-wsl|ms-|0.80.2
vsliveshare|ms-|1.0.5877
r|REd|2.8.1
stardog-rdf-grammars|sta|0.2.1
vscode-langserver-shacl|sta|0.2.0
vscode-langserver-sms|sta|0.2.0
vscode-langserver-sparql|sta|0.2.1
vscode-langserver-trig|sta|0.2.0
vscode-langserver-turtle|sta|0.2.1
vscode-stardog-languages|sta|0.1.0
rainbow-bracket|tal|1.0.2
volar|Vue|1.8.5

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
vsccc:30610678
2e4cg342:30602488
f6dab269:30613381
2i9eh265:30646982
showlangstatbar:30737416
vsctsb:30748421
03d35959:30757346
pythonfmttext:30731395
pythoncmvfstrcf:30756944
fixshowwlkth:30771522
showindicator:30785052
pythongtdpath:30769146
i26e3531:30792625
pythonnosm12tcf:30779713
pythonidxpt:30784022
pythonnocebcf:30776496
e537b577:30786199
dsvsc013:30795093
cmakesidepanelv2:30779593

```

</details>

**Comment by meganrogge** [comment]
can you share your settings.json?

**Comment by Ceelbc** [comment]
[settings.json.txt](https://github.com/microsoft/vscode/files/12130742/settings.json.txt)
Here you have my settings.json file.
Because GitHub doesn't support json files; I changed the file extension to txt.

**Comment by KnisterPeter** [comment]
I do see the same in WSL. When running `code .` from folder the command is kept running since the last release.
Previously it did terminate and frees the terminal for other interaction.
