### ISSUE TITLE
[Wayland] Crash on opening new instances

### ISSUE THREAD

**Issue by MabezDev** [microsoft/vscode#188481]
Type: <b>Bug</b>

Run `/usr/bin/vscode --enable-features=UseOzonePlatform --ozone-platform=wayland --unity-launch --verbose --disable-extensions` and then run various instances, eventually one will crash and force close all vscode windows.

VS Code version: Code 1.80.1 (74f6148eb9ea00507ec113ec51c489d6ffb4b771, 2023-07-12T17:22:25.257Z)
OS version: Linux x64 6.1.38-gentoo
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 3800XT 8-Core Processor (16 x 4210)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|3, 3, 2|
|Memory (System)|31.29GB (24.44GB free)|
|Process Argv|--enable-features=UseOzonePlatform --ozone-platform=wayland --unity-launch --crash-reporter-id b24feb01-b114-419c-8b48-0178359c133e|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|/usr/share/wayland-sessions/hyprland|
|XDG_CURRENT_DESKTOP|Hyprland|
|XDG_SESSION_DESKTOP|Hyprland|
|XDG_SESSION_TYPE|wayland|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
vscccc:30610679
2e4cg342:30602488
f6dab269:30613381
a9j8j154:30646983
showlangstatbar:30737416
vsctsb:30748421
03d35959:30757346
ecj1e332:30736112
pythonfmttext:30731395
pythoncmv:30756943
f8hc8238:30694864
fixshowwlkth:30771522
showindicator:30785052
pythongtdpath:30769146
i26e3531:30792625
pythonnosm12tcf:30779713
pythonidxpt:30784022
pythonnocebcf:30776496
e537b577:30795824
dsvsc013:30795093

```

</details>

I have two dmp files, one where it happens with all extensions enabled and another with all extensions disabled:

[dumps.zip](https://github.com/microsoft/vscode/files/12122951/dumps.zip)

**Comment by rxmmah** [comment]
i cant open any vs code app on Wayland, it crash in 2 seconds
