### ISSUE TITLE
Search: selection lags behind focus

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#18841]
When I quickly move the arrow keys up/down through search results I see the selection is lagging behind the focus. I know we have some timeout logic to prevent too many opens from happening but I think every second or so you still decide to let that timeout win. Imho the debouncing is not working correctly:

![untitled](https://cloud.githubusercontent.com/assets/900690/22148833/bf977b3c-df10-11e6-8bf7-a4ff78d7f571.gif)

**Comment by roblourens** [comment]
It is working correctly - the goal is to not toast your CPU just from moving through the search results, so it rate-limits how quickly it will change the selected result.

**Comment by roblourens** [comment]
I wonder if we should 

- Only limit the rate at which we switch between files in this situation, rather than rate-limiting navigating results within a file, as that may not be very CPU-intensive
- Or just ditch this in favor of F4/space/enter

**Comment by roblourens** [comment]
Closing in favor of #19307
