### ISSUE TITLE
Highlights not appearing after opening notebook search result

### ISSUE THREAD

**Issue by andreamah** [microsoft/vscode#188554]
[![Image from Gyazo](https://i.gyazo.com/8bae9b2cb958078e012750a6b29546e9.gif)](https://gyazo.com/8bae9b2cb958078e012750a6b29546e9)

1. Have a notebook with rendered markdown or outputs. Close it.
2. Search for something in it using the search widget.
3. Open the result. Sometimes, the decoration won't be there. I've also seen instances where it's there and then it disappears suddently.

**Comment by andreamah** [comment]
Strange, I now see the decorations there, but the results get doubled. Will try to fix this in this issue.

**Comment by eleanorjboyd** [comment]
seeing search flicker when I click on a notebook output search result. Also are the search options ever supposed to render two lines- like in this case I searched for something with two lines but there was a single line for the search result.

https://github.com/microsoft/vscode/assets/26030610/85d648da-65a3-473a-b2af-1e3ebbcb2a91

**Comment by andreamah** [comment]
Hmm, that's a weird flicker, I think this is part of https://github.com/microsoft/vscode/issues/191568#issuecomment-1698227903, so I'll track the flicker there.

Seems that the decoration persists after the flicker, which should be good enough for this issue.
