### ISSUE TITLE
Test: accessible view improvements

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#188537]
Refs #184612 
Refs #187477
Refs #188187
Refs #188188
Refs #188319

- [x] Windows @hediet
- [x] macOS @roblourens  
- [x] linux @lramos15

Complexity: 5

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23188537%0A%0A&assignees=meganrogge)

---

Last iteration, we introduced an accessible view, which provides screen reader users with the ability to inspect elements char by char, line by line. This was adopted for editor hovers and panel chat responses in June. 

An accessible view can be opened via `alt+f2` or with the command `Open Accessible View` while focusing an element for which this is supported.

Use a screen reader - with speech enabled as sometimes the text viewer doesn't pick up on things / interferes.

Hover updates:

We have added support for workbench hovers (like ones in the GHPR view or terminal). 
1. Focus a hover (workbench or editor).
2. You should hear a hint about opening the notification in the accessible view. 
3. Open the accessible view via `alt+f2` and verify the expected contents are rendered in it.
4. Disable `accessibility.verbosity.hover`.
5. Focus a hover.
6. You shouldn't hear the hint about opening the item in the accessible view. 

Chat updates:

Inline chat support:
- Run `Start code chat`
- With the input box focused, use `alt+f1` to view accessibility help info which should include how to inspect the response content.
- Run a request, and with the input box still focused, use `alt+f2` to review the response.
- Next, focus the response item and invoke `alt+f2`. It should display the response in the accessible view.

Panel chat improvements:
- In the panel chat input box, use `alt+f1` to verify there's info about inspecting response content.
- Run some chat requests.
- Focus one response.
- Verify that with `accessibility.verbosity.chat` enabled, you hear a hint about navigating between responses. With it disabled, you should not. 
- Navigate to the next/previous responses while in the accessible view via `alt + [` and `alt + ]`. Escaping should reveal that response item and focus it.

**Comment by hediet** [comment]
Blocked on https://github.com/microsoft/vscode/issues/188750

**Comment by roblourens** [comment]
Maybe there's nothing you can do about this, so I didn't open an issue, but in VoiceOver, some keyboard shortcuts are not actually read because it doesn't want to read brackets. So the "alt+[" shortcut is just read as "option plus"
