### ISSUE TITLE
Disconnect all connections in Oracle connection pool when killing Python Debug Console

### ISSUE THREAD

**Issue by netwang** [microsoft/vscode#188527]
I am using Visual Studio Code to debug Python web app with asyncio and cx-Oracle-async. 

After I kill Python Debug Console, all connections in Oracle connection pool still alive. Trigger a lot of Oracle Sessions alive. How disconnect these connections and close connection pool when killing Python Debug Console?

Which event can I get in python code when killing Python Debug Console?

Thanks!

**Comment by roblourens** [comment]
Please file this on the Python extension, thanks
