### ISSUE TITLE
Add Warning Message When Renaming Active .ipynb Files

### ISSUE THREAD

**Issue by c0m** [microsoft/vscode#188593]
Currently, when a .ipynb file is renamed, VSCode starts a new kernel session without warning. This is abrupt and could disrupt user workflow, especially when working with large notebooks that take a significant amount of time to initialize. 

This could be mitigated by having a warning message pop up when the user tries to rename an active .ipynb file. 

This would reduce surprises if a user is changing file names while waiting for something in their notebook to complete. 

Another potential solution could be to maintain the kernel session after the name change.

**Comment by amunger** [comment]
This also applies to saving an untitled file

**Comment by rebornix** [comment]
Let's merge this into https://github.com/microsoft/vscode-jupyter/issues/11010
