### ISSUE TITLE
Environment variables such as PATH only for a workspace, in settings.json

### ISSUE THREAD

**Issue by windmillcode0** [microsoft/vscode#188578]
Is there a way to have a workspace specific path, added to settings.json for common executables. Were working on an extension where go is installed in the extension location, it would be nice to have env var support only for the workspace

**Comment by windmillcode0** [comment]
I see there is terminal.integrated.env does that do what I need it to do

**Comment by Tyriar** [comment]
See the `EnvironmentVariableCollection` API.
