### ISSUE TITLE
Installing extension from VSIX after installing from location deletes original directory

### ISSUE THREAD

**Issue by eeroel** [microsoft/vscode#188582]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.80.1 
- OS Version: Mac OS 13.4.1

Steps to Reproduce:

1. Set up extension
2. Use `Developer: Install Extension From Location` to install the extension from the root path of the extension (the one with package.json etc)
3. Package the extension into vsix
4. Use `Developer: Install Extension From VSIX` and select the newly created vsix (this file can be anywhere)
5. The extension directory gets deleted

**Comment by sandy081** [comment]
This is not fixed completely after reverting the fix (https://github.com/microsoft/vscode/pull/190074). 

Hence reopened it.

**Comment by sandy081** [comment]
1. Set up extension
2. Use `Developer: Install Extension From Location` to install the extension from the root path of the extension (the one with package.json etc)
3. Open `extensions.json` file from extensions installation folder (Use command F1> Open Extensions Folder) and make sure the installed extension location is the location of the extension.
4. Package the extension into a vsix and move the VSIX to a location other than the extension location.
5. Use `Developer: Install Extension From VSIX` and select the newly created vsix
6. Open `extensions.json` file from extensions installation folder (Use command F1> Open Extensions Folder) and make sure the installed extension location is the location of the extracted VSIX in the extensions installation folder.
7. Restart VS Code and make sure source location of the extension in the disk is not deleted.
