### ISSUE TITLE
TypeScript confused?

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#18850]
Often, unsure when and how, I find TypeScript being very confused. For instance, below screen shots show it not knowing `lib.d.ts` anymore. I have no repo steps, but my suspect is 'large' git operations, like switching branches.

![screen shot 2017-01-20 at 15 43 28](https://cloud.githubusercontent.com/assets/1794099/22153355/4a5c64ba-df27-11e6-9f4e-9b5796ea9372.png)
![screen shot 2017-01-20 at 15 43 39](https://cloud.githubusercontent.com/assets/1794099/22153354/4a3e6564-df27-11e6-90ce-20a9dbc99bbc.png)

**Comment by Tyriar** [comment]
I've seen stuff like this quite a bit recently. Closing and reopening the file normally fixes it.

**Comment by joelday** [comment]
This is especially problematic after changing project.json. Usually have to reload the entire window instead of just the TypeScript project.

**Comment by mjbvz** [comment]
Closing due to lack of recent activity. Please open new issues with repo steps if you still see this happening regularly
