### ISSUE TITLE
Test: Git - Support opening repositories that have a symbolic link on their path

### ISSUE THREAD

**Issue by lszomoru** [microsoft/vscode#188584]
Refs: https://github.com/microsoft/vscode/issues/5970

- [x] macOS @bhavyaus
- [x] linux @connor4312
- [x] windows @sandy081

Complexity: 3

Authors: @lszomoru, @joaomoreno

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23188584%0A%0A&assignees=lszomoru,joaomoreno)

---

This milestone we have addressed a long standing issue with supporting git repositories that contain a symbolic link on their path.

### Pre-requisites
1. Install the latest VS Code Insiders
2. Ensure that you are using git `2.31` or later
3. Close a git repository (ex: microsoft/vscode)
4. Create a symbolic link (soft link) that points to the **folder** where the repository is cloned.
    * Windows - `mklink /D Link Target`
    * macOS/Linux - `ln -s /path/to/original /path/to/link`

### Basic git functionality
1. From the terminal run `code-insiders ABSOLUTE_PATH_CONTAINING_SYMBOLIC_LINK`. 💡 You have to use the terminal and the absolute path as there are some cases in which the OS (ex: open file dialog) would resolve the symbolic link before passing it to VS Code. 
    * Confirm that the repository has been discovered and appears in the "Source Control" view  
2. Open a file from the folder/workspace, and hover over the tab of the opened file
    * Confirm that the hover contains the path that is using the symbolic link
3. Make a change to the file
    * Confirm that the dirty diff decorators (added/edited/deleted) appear in the editor gutter
    * Confirm that the file appears in the "Source Control" view as a changed resource
4. Click on the file in the "Source Control" view
    * Confirm that the diff editor is opened and the diff is correct
5. Close the folder/workspace

### Repository deduplication
1. From the terminal run `code-insiders ABSOLUTE_PATH_CONTAINING_SYMBOLIC_LINK`.
    * Confirm that the repository has been discovered and appears in the "Source Control" view  
2. Go to File -> Add Folder to Workspace. In the dialog select the folder where the repository has been cloned. This is the path that **does not** contain the symbolic link.
    * Confirm that the folder is added to the workspace. At this point you should have two workspace folders with different names but their contents should be the same.
3. Switch to the "Source Control" view
    * Confirm that the repository appears only once as both workspace folders point to the same git repository

**Comment by connor4312** [comment]
Works nice :)

**Comment by bhavyaus** [comment]
When both the original and the symlink are opened in the same workspace (Repository deduplication):
- the editor gutter decorator for a file with edits only appear for files from the symlink.  If I open the same file from the original repo and edit it, no editor decorators appear.
- The file markers in the explorer also behave similarly. Editing files from the original repo, cause the symlink file markers to be updated with an `M`

Is this the expected behavior? I'm not familiar with this scenario of when someone will have both the original and symlink open in the same workspace.
