### ISSUE TITLE
[WelcomeUX] Elements get cut off when resize window

### ISSUE THREAD

**Issue by mousetraps** [Microsoft/vscode#18858]
Testing #18091
See below, where the top of the welcome screen is cut off. Scrolling using mouse wheel also doesn't work. 

![image](https://cloud.githubusercontent.com/assets/762848/22159282/feeb7f66-def4-11e6-8808-0e017b90f83a.png)

**Comment by bgashler1** [comment]
@chrmarti it seems we have some custom scroll capability (not standard `overflow:scroll-y`

Can you tell me how to enable vertical scrolling for this?

**Comment by chrmarti** [comment]
It should do that automatically. I think you only need to make sure the outer div grows with the content and doesn't stop at 100%. The reason we're doing something custom made is that we want our custom scrollbars. /cc @joaomoreno

**Comment by chrmarti** [comment]
ScrollableElement doesn't work with absolute positioned content. This seems to work better (needs proper selector):
```
.monaco-workbench > .part.editor > .content .monaco-scrollable-element > div {
  align-items: center;
  display: flex;
  justify-content: center;
}
```

**Comment by joaomoreno** [comment]
@chrmarti If you just want lookalike scrollbars, check the `::-webkit-scrollbar*` styles in https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/html/browser/webview.ts

**Comment by joaomoreno** [comment]
I've assigned this to January, move it out if not applicable.

**Comment by chrmarti** [comment]
@joaomoreno I have already hacked up my own pageUp/Down actions. Should I turn back now? :D

**Comment by joaomoreno** [comment]
@chrmarti Why the `candidate` tag? It's meant to be used for candidate issues for a recovery build.

**Comment by chrmarti** [comment]
@joaomoreno I need to read the instructions again, thought we start adding `candidate` on Thursday's fixes.
