### ISSUE TITLE
Some regex metacharacters like \A and \z not supported in folder (Ctrl + Shift + F) search

### ISSUE THREAD

**Issue by Destroy666x** [microsoft/vscode#188547]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.80.1
- OS Version: WIndows 10 22H2

Steps to Reproduce:

1. Press Ctrl + Shift + F to go to folder search.
2. Enable regex search.
3. Try searching for e.g. `\Asomething` which would normally find `something` only at the start of the file/whole string.
4. Popup with `Invalid regular expression: /\Asomething/: Invalid escape` appears.

AFAIK that part uses either Rust or PCRE2 engines, both of which support the mentioned metacharacters. I guess this is related to multiline matching then, but not sure why it'd throw an error either way, even if attempts to run the regex on each line, they should work.

**Comment by andreamah** [comment]
Regexes aren't supported by JS won't pass validation, as we use JS regexes to search open files. [See here](https://github.com/microsoft/vscode/wiki/Search-Issues#notes-on-regular-expression-support)

**Comment by Destroy666x** [comment]
So it uses ECMAScript engine in the end? Is Rust/PCRE2 used somewhere else or was that info outdated?

**Comment by andreamah** [comment]
It uses both the JS engine (for open files) and Rust/PCRE2 (for searching closed files). Therefore, it must compile in both to search in both. I believe that that's what the stackoverflow answer was referring to. Mentioning PCRE2 was more for the sake of a regex being interpreted differently in open vs. closed files by accident.

**Comment by Destroy666x** [comment]
Why this approach? Why not e.g. use Rust/PCRE2 for everything?

**Comment by andreamah** [comment]
The functionality for finding within a file was already using JS-based regexes and this was reused for searching in open editors. For example, if you have unsaved changes in the current file, these appear in the search view as its unsaved state since we also consider the state of open files in the editor.
