### ISSUE TITLE
Test: generalized keybindings for navigating input / result of widgets

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#188536]
Refs #179967

- [x] Windows @joyceerhl
- [x] macOS @hbons  
- [x] Linux @alexr00

Complexity: 4

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23188536%0A%0A&assignees=meganrogge)

---

For screen reader users, consistency across components is very helpful.

We now have a generalized way of navigating to / from the results / input of widgets. 

Test that this works and doesn't break any functionality in the following areas:
- Extensions
- Keybindings editor
- Comments
- Problems
- Debug

**Comment by alexr00** [comment]
I think this is ctrl+up arrow and ctrl+down arrow should let you navigate between an input and it's results. @meganrogge is that what we should be testing?

**Comment by hbons** [comment]
On macOS `Ctrl+DownArrow` and `Ctrl+DownArrow` opens Mission Control. When I use the `Cmd+Down` key instead from Search I can navigate to the `files to include` and `files to exclude` fields and after that the search results list. I can navigate back to the previous fields using `Cmd+Up`.

**Comment by meganrogge** [comment]
Sorry for the unclear instructions - yes, cmd (mac) or ctrl + up/down arrow should allow you to go from the input to the results for each of the views
