### ISSUE TITLE
[WelcomeUX] 'Clone git repository' errors when new SCM is enabled

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#18857]
Testing #18091 

- Ensure new SCM experience is enabled
- Click 'Clone git repo...'

Error notification says 'Unable to open 'workbench.action.git.clone': Could not resolve any model with provided uri.'

**Comment by isidorn** [comment]
I have verified that the clone git repository link is gone
But I would have expected that the git clone link is still there and that it actually works.
In the future we will only use this version of git and we should still have this funcionality in the welcome page

**Comment by chrmarti** [comment]
It's still there is you disable SCM preview. Stable will ship with it disabled. Adding the link back with the new SCM is on my list.
