### ISSUE TITLE
dasdas

### ISSUE THREAD

**Issue by wclub-dev** [microsoft/vscode#188656]
Type: <b>Bug</b>

dasdasdasdasdasda

VS Code version: Code 1.80.1 (Universal) (74f6148eb9ea00507ec113ec51c489d6ffb4b771, 2023-07-12T17:20:23.298Z)
OS version: Darwin arm64 21.3.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|7, 9, 6|
|Memory (System)|32.00GB (6.20GB free)|
|Process Argv|--crash-reporter-id 23723ad0-0bdc-415a-b14a-fcc8d59c4e44|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (22)</summary>

Extension|Author (truncated)|Version
---|---|---
classdiagram-ts|Ale|0.1.67
jsonl|Alp|0.0.1
markdown-preview-github-styles|bie|2.0.2
gitignore|cod|0.9.0
githistory|don|0.6.20
gitlens|eam|2023.7.2105
prettier-vscode|esb|9.19.0
vscode-pull-request-github|Git|0.68.1
go|gol|0.39.1
terraform|has|2.27.0
vscode-drawio|hed|1.6.6
svg|joc|1.5.3
vs-color-picker|lih|1.0.0
git-graph|mhu|1.30.0
vscode-filesize|mkx|3.1.0
vscode-docker|ms-|1.26.0
vscode-language-pack-ko|MS-|1.80.2023071209
remote-containers|ms-|0.299.0
color-highlight|nau|2.5.0
vscode-thunder-client|ran|2.9.2
vscode-xml|red|0.26.1
LiveServer|rit|5.7.9

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
py29gd2263:30792226
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
vscccc:30610679
282f8724:30602487
f6dab269:30613381
2i9eh265:30646982
showlangstatbar:30737416
vsctsb:30748421
pythonfmttext:30731395
pythoncmv:30756943
fixshowwlkth:30771522
hideindicator:30785051
pythongtdpath:30769146
i26e3531:30792625
pythonnosm12tcf:30779713
pythonidxpt:30784022
pythonnocebcf:30776496
e537b577:30795824
dsvsc013:30795093

```

</details>

**Comment by aiday-mar** [comment]
Hi please add more comprehensible information. Currently this issue is labelled as spam.
