### ISSUE TITLE
Test: Load CAs from OS for http2 requests in the extension host

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode#188686]
Refs: #185098

- [x] macOS @connor4312
- [x] linux @sbatten
- [x] windows @TylerLeonhardt 

Complexity: 3

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23188686%0A%0A&assignees=chrmarti)

---

- Create a local certificate:
```
openssl req -x509 -newkey rsa:4096 -keyout server_localhost_key.pem -out server_localhost_crt.pem -days 365 -nodes -subj /CN=localhost
```
- Install the certificate in the OS.
  - Windows: `Manage Computer Certificates` > `Trusted Root Certification Authorities`
  - Mac: `Keychain Access` > `System` > `Certificates`
  - Linux: Distro dependent. Ubuntu: https://ubuntu.com/server/docs/security-trust-store
- Run an HTTP2 server using the certificate:
```js
const http2 = require('http2');
const fs = require('fs');

const options = {
  key: fs.readFileSync('./server_localhost_key.pem'),
  cert: fs.readFileSync('./server_localhost_crt.pem')
};

const server = http2.createSecureServer(options);

server.on('error', (error) => {
  console.error(error);
});

server.on('stream', (stream, headers) => {
  stream.respond({
    'content-type': 'text/plain',
    ':status': 200
  });
  stream.end('Hello, HTTP2 world!');
});

server.listen(3000);
```
- Install the "Network Proxy Test" extension: https://marketplace.visualstudio.com/items?itemName=chrmarti.network-proxy-test
- Run the `Network Proxy Test: Test Network Connection (HTTP2)` command entering `https://localhost:3000` and verify there is no "self signed certificate" error in the output.

**Comment by connor4312** [comment]
For future reference, https://github.com/FiloSottile/mkcert is a wonderful tool :)
