### ISSUE TITLE
Run button/Cell Toolbar covered by Sticky Scroll

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#188690]
Does this issue occur when all extensions are disabled?: Yes/No

With sticky scroll enabled, the run button and cell toolbar no longer correctly move its position to say visible when we move a cell partially out of the viewport.

**Comment by rebornix** [comment]
<img width="1366" alt="image" src="https://github.com/microsoft/vscode/assets/876920/a93935fc-39b2-4760-b8df-d9b0c356e688">

**Comment by aiday-mar** [comment]
Looking good. The toolbar appears to move. I am just wondering if the toolbar should perhaps have a lower z-index than the sticky scroll? To avoid the following case

<img width="868" alt="Screenshot 2023-07-27 at 17 47 37" src="https://github.com/microsoft/vscode/assets/61460952/91a81052-b68d-4161-b8d3-e7d397295bea">

**Comment by Yoyokrazy** [comment]
> I am just wondering if the toolbar should perhaps have a lower z-index than the sticky scroll?

Yep, that's being tracked [here](https://github.com/microsoft/vscode/issues/188974). Likely being taken care of during the next debt cycle.
