### ISSUE TITLE
Only one diff editor is opened when invoking `vscode.diff` multiple times.

### ISSUE THREAD

**Issue by AkatQuas** [microsoft/vscode#188670]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.80.1
- OS Version: Darwin x64 22.5.0

Steps to Reproduce:

In an extension, invoking `vscode.diff` commands for several times.

1. 
```ts
dupList.forEach(async ({ dup, old }) => {
    const left = Uri.file(dup);
    const right = Uri.file(old);
    await commands.executeCommand(
      'vscode.diff',
      left, 
      right,
    );
    await sleep(500);
  });
```

2. 
**Actual Result**: there's only one diff editor opened with files from last pair.

**Expectation**: each command invocation would open one diff editor.

**Comment by gjsjohnmurray** [comment]
Please try this:
```ts
    await commands.executeCommand(
      'vscode.diff',
      left, 
      right,
      undefined,
      { preview: false },
    );

```
