### ISSUE TITLE
Test: large notebook output performance

### ISSUE THREAD

**Issue by amunger** [microsoft/vscode#188699]
Refs: https://github.com/microsoft/vscode/issues/182636

- [x] macOS @isidorn
- [x] linux @ulugbekna
- [x] windows @Yoyokrazy

Complexity: 3

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23188699%0A%0A&assignees=amunger)

---

## Summary

We made some performance improvements for scrollable notebook outputs with large amounts of streaming output while a cell is being executed by appending to the DOM rather than replacing large amounts of elements. All other behavior should remain the same.

### Setup (If you don't have python set up to run notebooks)

1. ensure python is installed on your machine
2. open a workspace where you will be running tests for this TPI
3. `Create: new jupyter notebook` and run `print(1)` in a cell. 
  a. If the cell runs successfully, you're already set up, 
  b. otherwise select "change kernel" in the pop-up that informs you about missing packages (unless the kernel picker opened in the quick pick, then just go to step 4)
4. The kernel picker should open, select "Python Environments..." -> "Create Python Environment..." and select the base interpreter to use
  a. All necessary packages should be installed and the cell should run successfully

## Testing

1. ensure "notebook.output.scrolling": true
2. Run some cells that will force a lot of rendering actions to happen quickly, which can be done by making a `flush` call to push the updated output content to the renderer. Pushing the numbers too high will still cause slowdowns, but should still be improved. examples:

#### Lots of rendering

```
import sys
for i in range(5000):
    print('{!r} {!r}'.format(list(range(10)), i), file=sys.stderr)
    sys.stderr.flush()
```

#### Lots of previous data per render

```
for i in range(300000):
    print('{!r} {!r}'.format(list(range(10)), i), file=sys.stderr)

import sys
for i in range(100):
    print('{!r} {!r}'.format(list(range(10)), i), file=sys.stderr)
    sys.stderr.flush()
```

#### Lots of new data per render

This one is still pretty slow since it still often needs to replace a large amount DOM structure

```
import sys
itr = 0
for i in range(10):
    for j in range(4444):
        itr = itr +1
        print('{!r} {!r} {!r}'.format(itr, j, i), file=sys.stderr)
    sys.stderr.flush()
```

**Comment by ulugbekna** [comment]
worked quite fast for me, cool work!
