### ISSUE TITLE
Should drop down button toggle primary action?

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#188653]
I was slightly confused that picking an alternative value from the dropdown was executing that value:

![image](https://github.com/microsoft/vscode/assets/900690/7f8fcaf4-9340-440f-a0fd-ea8dbda8fd5b)

I think from my memory a dropdown button would change its primary action when you pick a different thing from the dropdown but not just execute it. Rather, you would still need to click the button, but the button has now changed and remembers your choice.

Would be good to check with HIG across OS, maybe I am wrong.

**Comment by alexr00** [comment]
The new dropdown button now matches the way we do split buttons/dropdown buttons in core VS Code (ex. in the commit view). I have an item to move other PR view buttons to work this way too: https://github.com/microsoft/vscode-pull-request-github/issues/3785
