### ISSUE TITLE
Rename the currently open file

### ISSUE THREAD

**Issue by pcgeek86** [Microsoft/vscode#1886]
It would be really nice if there was a "rename current file" command in Visual Studio Code.

I'm running VS Code on Mac OS X, version `0.10.6`.

![screen shot 2016-01-08 at 2 30 26 pm](https://cloud.githubusercontent.com/assets/466713/12210027/68a5ac48-b614-11e5-9c6d-e182ae43742e.png)

![screen shot 2016-01-08 at 2 31 56 pm](https://cloud.githubusercontent.com/assets/466713/12210056/98407c1c-b614-11e5-91c4-a7f29ca7e188.png)

Cheers,
Trevor Sullivan
Microsoft MVP: PowerShell

**Comment by joaomoreno** [comment]
@bpasero ping

**Comment by drewda** [comment]
I agree, this would be a useful addition.

Currently in the Mac version, it's only possible to rename files by focusing to the Explorer sidebar, moving up or down to the current file, and pressing Enter to edit the name.

**Comment by bpasero** [comment]
Why not try an extension? Try https://marketplace.visualstudio.com/items?itemName=sleistner.vscode-fileutils

**Comment by bpasero** [comment]
Closing, extensions.

**Comment by iddan** [comment]
The face an extension can be used doesn't yields it should not be merged
