### ISSUE TITLE
Test Closed Notebook Search

### ISSUE THREAD

**Issue by andreamah** [microsoft/vscode#188695]
Refs #173726

- [x] macOS @DonJayamanne
- [ ] linux @digitarald 
- [x] windows @karrtikr

Complexity: 4

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23188695%0A%0A&assignees=andreamah)

---
## Intro:
Hi! 👋 

This has to do with using the search widget to search for notebook content. Like in [previous TPIs](https://github.com/microsoft/vscode/issues/179922), the search widget should be able to search fully in open notebooks. However, when a notebook was closed, the search widget always searched the raw source text of the notebook. In the TPI linked above, you could see how opening a search result changed the search result preview's text so that it matches the "rich" version of the text that you view from the notebook editor. With my changes, I'm aiming to show "rich" results before you open the notebooks. These will be limited to only searching notebook INPUTS for now (code and markdown input) when a notebook is closed. This means that it's normal to see extra results appear (or results changing preview text) when you open a notebook (either from a result or not) because opening a notebook triggers another search that should also show results for outputs and rendered content.

DEMO:

https://github.com/microsoft/vscode/assets/31675041/3bac4bba-2a48-4322-bae5-14f2930340e4

## Set up: 
Enable `search.experimental.closedNotebookRichContentResults`. Just to be sure that you're in a good state, please also reload the window after you do this.

## Testing:
Test that:
1. searching in closed notebooks shows only matches that are in notebook inputs and not notebook outputs.
2. searching in closed notebooks shows "rich" content. 

For example, you can have a cell that contains the python:

```python
    print('hello')
            print('hello')
        print('hello')
```

And the search result in the closed notebook should NOT have quotes.

Incorrect:
<img width="355" alt="image" src="https://github.com/microsoft/vscode/assets/31675041/7054f787-ff83-4a5a-9105-3a28f62559ae">

Correct:
<img width="367" alt="image" src="https://github.com/microsoft/vscode/assets/31675041/86263719-1e42-4436-ba07-3bb6151b7f10">

3. Clicking on a search result should open the document at the appropriate location. Please be aware that this might not always work upon opening the notebook due to [this bug](https://github.com/microsoft/vscode/issues/188557). Also, [this bug](https://github.com/microsoft/vscode/issues/188558) might prevent the current match from being highlighted correctly upon clicking on a search result.
4. searching in non-notebooks is as expected still. 
5. Please just play around the feature and leave feedback on what you think!

## Future work 
For the future, I'm planning on improving on these two areas:
- Performance of the notebook search (especially in remote scenarios). [Issue here](https://github.com/microsoft/vscode/issues/188556)
- Potentially adding support for searching outputs in closed notebooks.
    - In this case, possibly facilitating better switch between closed and open notebook search (since filter icon suddenly appears for searching open notebooks, but not closed).

**Comment by karrtikr** [comment]
Nice addition, works great.

**Comment by DonJayamanne** [comment]
Works as expected, awesome

**Comment by digitarald** [comment]
Sweet, love how well this worked in my data science workspace.
