### ISSUE TITLE
Create PR primary buttons are quite far away now

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#188649]
![image](https://github.com/microsoft/vscode/assets/900690/166b44c4-5a74-4b0f-b5ff-2945239dd194)

I think the main button used to be more to the top, but now the text area seems to stretch all the way down.

**Comment by alexr00** [comment]
We did make the text area larger. @hbons has looked into moving the buttons to the top.

**Comment by alexr00** [comment]
I've increased the size of the changes views and given them all new IDs. This will make the webview smaller.
