### ISSUE TITLE
[WelcomeUX] File icon for welcome page tab is the html icon

### ISSUE THREAD

**Issue by mousetraps** [Microsoft/vscode#18860]
Testing #18091
![image](https://cloud.githubusercontent.com/assets/762848/22159404/8f089494-def5-11e6-9964-096c9d560e99.png)

Would be nice if we had a custom icon for this

**Comment by bgashler1** [comment]
I vote our product logo.

**Comment by chrmarti** [comment]
@bgashler1 We can overwrite the icon theme:
```
.show-file-icons .welcomepage\.html-name-file-icon.html-ext-file-icon.html-lang-file-icon.file-icon::before {
    content: ' ';
    background-image: url('welcomePageIcon.svg');
}
```
(And similar for the walkthrough.)

We would need SVG icons for the OSS, the insider and the stable version. Do we have these or can you create these?

The insider and stable icons will need to go into the distro repo and we will need to update the build to copy these to the right place depending on which variant is being built.

**Comment by chrmarti** [comment]
On second thought, this might not be robust enough. @bpasero Is there a good way to overwrite the icon for a specific editor?

@seanmcbreen Do we have SVG icons for the insider and stable logos?

**Comment by bpasero** [comment]
@chrmarti we just pick the icon up from the resource of the editor. Maybe we could teach the icon service a specific rule to use for this particular resource? @aeschli might know if that is possible.

**Comment by aeschli** [comment]
Hardcoding it in the theme service is probably the same like the css rule above.
Given that this is only about the editor icon, I'd recommend the css overwrite.
Hover 'welcome.html' is a common file name. Any chance you can give it a different, more unique name, or any chance that you can but a unique css class on the editor?

**Comment by bpasero** [comment]
+1 for just using CSS override. Since the class name is derived from the resource path I suggest to name this resource something like vs_code_welcome.code.

**Comment by chrmarti** [comment]
I have a unique classname I can use. Thanks!

**Comment by bpasero** [comment]
@chrmarti can we not use our default file icon (see it in the first tab) when you need one for welcome? yours looks quite off from the rest of the icon set:

![image](https://cloud.githubusercontent.com/assets/900690/22362931/dd1ca168-e466-11e6-9d20-50036b00276b.png)

**Comment by joaomoreno** [comment]
Actually looks pretty cool on my machine. 👍

**Comment by chrmarti** [comment]
@chrisdias I forgot: I'd also need an SVG of the OSS icon.

**Comment by chrisdias** [comment]
i'm on it!
