### ISSUE TITLE
settings.json - integrated shell does not respect nested keys

### ISSUE THREAD

**Issue by anabelle2001** [microsoft/vscode#188624]
## Steps to Reproduce:

1. Open an integrated terminal (<kbd>ctrl</kbd>+<kbd>`</kbd>), and select a shell (eg: bash) that supports [shell decorations][1] 
2. Paste the following lines into an empty settings.json file
```
    // "terminal": {"integrated.shellIntegration.decorationsEnabled": "never"},
    // "terminal.integrated": {"shellIntegration.decorationsEnabled": "never"},
    // "terminal.integrated.shellIntegration": {"decorationsEnabled": "never"},
    // "terminal.integrated.shellIntegration.decorationsEnabled": "never"
```
2. Uncomment the lines one at a time, from top to bottom

## Expected Behavior:
Uncommenting lines 1, 2, and 3 should each be sufficient to disable shell decorations, like the examples in [Get Started > Settings > Changing settings.json][2]

## Actual Behavior:
Lines 1-3 don't do anything, line 4 disables shell decorations.

## More Info:
I originally discovered this on Fedora 38 on the de-microsofted vscodium package, but confirmed it was present on the current flathub version of visual studio code (1.80), as well as the .deb package listed on microsoft's website. Intelisense also does not work for "nested" keys in settings.json

- Does this issue occur when all extensions are disabled?: Yes
- VS Code Version: 1.80.1
- OS Version:  Debian 12, fresh install

[1]: https://code.visualstudio.com/docs/terminal/shell-integration#_command-decorations-and-the-overview-ruler
[2]: https://code.visualstudio.com/docs/getstarted/settings#_changing-settingsjson

**Comment by rzhao271** [comment]
The docs example is misleading.
`editorLineNumber.foreground` is the name of the colour, and not part of a setting. `"workbench.colorCustomizations.editorLineNumber": { "foreground": "#00ff00" }` doesn't work.

**Comment by sandy081** [comment]
This is not supported in settings.json file. One has to provide a complete setting key.
