### ISSUE TITLE
VSCode shows error for WPF project: "The name 'InitializeComponent' does not exist in the current context (RoslynCS0103)

### ISSUE THREAD

**Issue by HyVong007** [microsoft/vscode#188678]
Type: <b>Bug</b>

1/ Install .NET Core 7.0
2/ Create WPF project with "dotnet new wpf"
3/ VSCode > Open Folder.

After awhile, VSCode shows many errors: 
- "The name 'InitializeComponent' does not exist in the current context"
- Moreover, any variables declared in .XAML file will cause error if these variables are used in .CS file

Hope VSCode Dev Team will fix bugs soon, thank you very much !

VS Code version: Code 1.80.1 (74f6148eb9ea00507ec113ec51c489d6ffb4b771, 2023-07-12T17:22:07.651Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6300U CPU @ 2.40GHz (4 x 2496)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|3.92GB (0.71GB free)|
|Process Argv|C:\\Users\\Tam\\Desktop\\PCLauncher\\PCLauncher.csproj --crash-reporter-id ba2693d4-c257-4db8-bdd5-f5830602b873|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
csdevkit|ms-|0.3.5
csharp|ms-|2.0.283
dotnet-maui|ms-|0.1.34
vscode-dotnet-runtime|ms-|1.6.0
vscodeintellicode-csharp|ms-|0.1.26
remote-wsl|ms-|0.80.2
cmake-tools|ms-|1.14.34
cpptools|ms-|1.16.3
cpptools-extension-pack|ms-|1.3.0
cmake|twx|0.0.17

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
282f8724:30602487
89544117:30613380
showlangstatbar:30737416
vsctsb:30748421
a2ce3375:30757347
pythonfmttext:30731395
pythoncmv:30756943
fixshowwlkth:30771522
hideindicator:30785051
pythongtdpath:30769146
i26e3531:30792625
pythonnosm12tcf:30779713
pythonidxpt:30784022
pythonnocebcf:30776496
e537b577:30795824
dsvsc013:30795093

```

</details>

**Comment by DonJayamanne** [comment]
This looks like its related to teh csharp extension, please file an issue on the corresponding repo (https://github.com/dotnet/vscode-csharp)

If you feel that disabling all exetnsions still repros this issue, then feel free to ping here and I'll reopen this or feel free to create a new issue
