### ISSUE TITLE
[WelcomeUX] Walk-through vertical scroll position resets when switching editors

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#18868]
Testing #18091

**Comment by chrmarti** [comment]
Maybe remember scroll position like BaseTextEditor.saveTextEditorViewState().
![screen shot 2017-01-20 at 4 09 48 pm](https://cloud.githubusercontent.com/assets/9205389/22169695/eed88a66-df2a-11e6-9e87-5265dbf90f85.png)

**Comment by bpasero** [comment]
@chrmarti can we not use our default file icon when you need one for welcome? yours looks quite off from the rest of the icon set:

![image](https://cloud.githubusercontent.com/assets/900690/22362931/dd1ca168-e466-11e6-9d20-50036b00276b.png)
