### ISSUE TITLE
Test quick pick item icon API

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#188683]
Refs: https://github.com/microsoft/vscode/issues/176049

- [x] macOS @TylerLeonhardt
- [x] linux @roblourens
- [x] windows @sandy081

Complexity: 4

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23188683%0A%0A&assignees=alexr00)

---

We have finalized the quick pick item icon API. To test the API, you'll need to write an extension that uses quick pick or start from the quick input sample extension. You can see where the sample extension set up some quick pick items here: https://github.com/microsoft/vscode-extension-samples/blob/f7b27a91779e770b8f8f0e6791bcefc5d9c64035/quickinput-sample/src/quickOpen.ts#L73-L84. If you use the sample, you can just try adding an icon to those quick pick items.

This is the new API: 
https://github.com/microsoft/vscode/blob/de6839abe8ba06d86bd1f0827dc2b60e53e5dac4/src/vscode-dts/vscode.d.ts#L1736-L1739

Verify:
- That you can use the API to add an icon to quick pick item. Try with both a codicon and with a URI.
- That the JS doc makes sense.

**Comment by TylerLeonhardt** [comment]
![Recording 2023-07-25 at 12 08 34](https://github.com/microsoft/vscode/assets/2644648/c7740dc6-4bc7-4122-a0aa-4e7508d6f93f)
My silly extension based on https://www.dicebear.com/how-to-use/http-api 😄
