### ISSUE TITLE
Test Partial Profiles

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#188613]
Refs: https://github.com/microsoft/vscode/issues/156144

- [x] win @aiday-mar
- [X] mac @anthonykim1
- [x] linux @connor4312

Complexity: 4

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23188613%0A%0A&assignees=sandy081)

---

### Introduction

You can now create a partial profile, ie., a profile in which you can customise only some configurations (Settings, Keyboard Shortcuts, User Snippets, User Tasks, Extensions). When such a profile is active, VS Code uses the customisations from default profile for those configurations which are not part of the profile. For example: You can have a Profile with all configurations except for Keyboard Shortcuts, and use Default Profile for it.

You can create such a profile using the new Create Profile flow (Settings Gear > Profile > Create Profile...) in which you can select what can be configured in the profile. 

#### Creating

Test creating a partial profile with various options available in the create profile flow

- Empty (Copy from None)
- Copying from a template
- Copying from existing profile

and make sure the partial profile is created and applied as expected.  Please play around with this flow and provide feedback. 

#### Editing

You can update these options after creating the profile using `Settings Gear > Profile > Edit Profile...` action. Try editing the profile and changing the options and test if the update is working as expected.

#### Other Features

- Test exporting such a profile
- Test such profiles are synced as expected across machines (You can use different `user-data-dir` and `extensions-dir` and launch VS Code for testing syncing)

**Comment by tanishqmanuja** [comment]
Use case: https://github.com/microsoft/vscode/issues/156144#issuecomment-1642405219

Is there a PR associated for partial profiles or will it be in Insiders for testing?

**Comment by sandy081** [comment]
@tanishqmanuja This is the issue you might want to comment in - https://github.com/microsoft/vscode/issues/188612

**Comment by aiday-mar** [comment]
Hey @sandy081, I am testing the partial profiles. While testing, I had the following thoughts:

1. I created an empty profile that only configures the settings and the keyboard shortcuts, meaning that the extensions were inherited from the default profile. Upon creation, I noticed that all my extensions were enabled, while in the default profile some were disabled. Do you think it would make sense to inherit also the disabled/enabled states from the default profile?
2. When I clicked on `Edit Profile...`, I noticed that the checkboxes that are enabled are not always the same as the ones that were previously checked during profile creation. Here is a video showing what I mean:

https://github.com/microsoft/vscode/assets/61460952/c8b7caab-ceda-4bac-9154-488e9cd2b508

I was wondering if this was intended? For my `Test Python` profile, on clicking `Edit profile...`, I expected to see only `settings`, `user tasks` and `extensions` checked.
