### ISSUE TITLE
Loading infinitely 

### ISSUE THREAD

**Issue by Stefan-ULS** [microsoft/vscode#188607]
ADD ISSUE DESCRIPTION HERE
After connecting on cs50 IDE it seems like it still loading something and I can't start working on. What should I do?

Version: 1.80.1
<img width="661" alt="Screen Shot 2023-07-23 at 14 16 48" src="https://github.com/microsoft/vscode/assets/107550724/5bbb22f6-dd78-4837-8ac3-9c90588deea8">
<img width="661" alt="Screen Shot 2023-07-23 at 14 16 48" src="https://github.com/microsoft/vscode/assets/107550724/f4b72405-a55c-4958-8a77-4c95aafe9a37">

Commit: 74f6148eb9ea00507ec113ec51c489d6ffb4b771
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36
Embedder: codespaces

**Comment by aiday-mar** [comment]
Hey @deepak1556, not sure who to assign for this. Feel free to reassign.

**Comment by joaomoreno** [comment]
@Stefan-ULS What is "cs50 IDE"? Do you have instructions on how to connect?
