### ISSUE TITLE
Multiple Extensions Folders based on development language

### ISSUE THREAD

**Issue by RoyBradley** [microsoft/vscode#188621]
I develop in 6 different languages, it would be nice if, based on the language that I pick to develop in, I could also pick an extension folder, that would only load the extensions for that language. That way I would not have to have hundreds of extensions loaded every time I open Visual Studio Code. There should be something like a global extension file that would automatically load no matter what language extension folder is selected.

**Comment by gjsjohnmurray** [comment]
I suggest you try Profiles. See https://code.visualstudio.com/updates/v1_75#_profiles for information.
