### ISSUE TITLE
VS Code sets itself as the default xdg-mime inode/directory application. Makes applications use it for "browse to folder" function.

### ISSUE THREAD

**Issue by Veprovina** [microsoft/vscode#188634]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.80.1 (flatpak)
- OS Version: Arch linux

I'm not sure where to report this so apologies if it's the wrong place.
VS Code sets itself as the default application for "browse to folder" functions for apps that use xdg. 

In terminal:
`xdg-mime query default inode/directory`

returns `com.visualstudio.code.desktop`.

This makes Steam use VS code instead of the native file browser when using the "browse to folder" function (right click on game, manage, browse to folder).

To fix this, i needed to set nautilus back to being default by this command:
`xdg-mime default org.gnome.Nautilus.desktop inode/directory`

This breaks the functionality, as i can't do much with files in VS code in that context. VS code shouldn't be used as a file manager app.
I'm not sure how this happened, and i've found a fix, but i thought i'd report it, in case you want to review the flatpak app, and why it was setting itself as the default file browser for "browse to" function. 

Firefox and other native apps were unaffected.
The only affected apps were Steam and Unity. Probably because they use xdg.

Steps to Reproduce:

1. Install VS Code flatpak version on linux
2. Open Steam and use browse to folder function

**Comment by hgfernan** [comment]
That's a disgusting feature of vscode. Since it's primarily a code editor, why should it try to replace some specialized inode/directory viewer ? 

I've tried not to use the words bug, bug by design, Microsoft style...

**Comment by Tyriar** [comment]
@hgfernan see the linked issue https://github.com/microsoft/vscode/issues/114425#issuecomment-762812281, all we do is register ourselves as an app that can open directories. To me this always seemed like a bug on certain distro sides as it works as expected on some but not others, but regardless it needs an expert to help.
