### ISSUE TITLE
When developing VSCode plug-in, I want to install this plug-in with other plug-ins bundled. What should I do

### ISSUE THREAD

**Issue by QinZiWeiS** [microsoft/vscode#188658]
When developing VSCode plug-in, I want to install this plug-in with other plug-ins bundled. What should I do

**Comment by gjsjohnmurray** [comment]
Are you aware of [Extension Packs](https://code.visualstudio.com/api/references/extension-manifest#extension-packs)?

**Comment by QinZiWeiS** [comment]
> Are you aware of [Extension Packs](https://code.visualstudio.com/api/references/extension-manifest#extension-packs)?

Thanks
