### ISSUE TITLE
[html] Links with fragment can't be Ctrl+clicked

### ISSUE THREAD

**Issue by anthonyvdotbe** [microsoft/vscode#188623]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: Version: 1.80.1 (user setup) (74f6148eb9ea00507ec113ec51c489d6ffb4b771)
- OS Version: Windows_NT x64 10.0.19045

Steps to Reproduce:

1. create `foo.html` with content: `<a href="bar.html#baz">baz</a>`
2. create `bar.html` in the same folder
3. Ctrl+click on the link in `foo.html`

Expected behavior: the link is followed
Actual behavior: an error is shown

![image](https://github.com/microsoft/vscode/assets/15714253/72a66207-7281-4fb3-81ff-55c2fe4414c2)

**Comment by aeschli** [comment]
Looka like the fix for https://github.com/microsoft/vscode-html-languageservice/pull/180 isn't working.
