### ISSUE TITLE
Notebook Sticky Scroll clicking on entry doesn't fully reveal markdown header

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#188688]
Does this issue occur when all extensions are disabled?: Yes/No

https://github.com/microsoft/vscode/assets/876920/c752eb5a-9f69-4a65-b8e1-1cd19175986a

**Comment by Yoyokrazy** [comment]
Think this is an edge case with two Markdown header cells in a row. Will address this week.

**Comment by Yoyokrazy** [comment]
Fixed via #201837
