### ISSUE TITLE
Test installing incompatible pre-release versions

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#188618]
Refs: https://github.com/microsoft/vscode/issues/187487, https://github.com/microsoft/vscode/issues/187734

- [x] anyOS @DonJayamanne
- [x] anyOS @Tyriar

Complexity: 4

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23188618%0A%0A&assignees=sandy081)

---

You can now install a pre-release of an extension even if its latest pre-release version is not compatible with the client. 

## Set up

[Setup](https://code.visualstudio.com/api/working-with-extensions/publishing-extension) for publishing an extension

- Publish an extension say **Extension A** with version `0.0.1` that is compatible with current client (VS Code Insiders)
- Publish a pre-release version for the same extension and make it not compatible with current client. Set following in package.json and publish with `--pre-release` flag - https://code.visualstudio.com/api/working-with-extensions/publishing-extension#prerelease-extensions
```json
"version": "0.0.2",
	"engines": {
		"vscode": "^1.300.0"
	},
```
- Publish an extension say **Extension Pack A** with version `0.0.1` that is compatible with current client (VS Code Insiders) and include above extension as extension pack. Set following in package.json:
```
"extensionPack": [
		`${extensionIdentifier}`
	]
```
- Bump the version of **Extension Pack A** to `0.0.2` and publish it as Pre release version.

## Testing

- Install **Extension A** from VS Code and make sure the compatible release version `0.0.1.` is installed.
- Uninstall **Extension A**
- Install **Extension Pack A** from VS Code and make sure **Extension A** with version `0.0.1.` is installed.
- Now publish a compatible pre-release version for **Extension A**
```json
"version": "0.0.3",
	"engines": {
		"vscode": "^1.80.0"
	},
```
- If you have auto updates for extensions enabled, the extension should be auto updated to the pre-release version `0.0.3` or you should see **Update** button and updating it should install `0.0.3` version

**Comment by Tyriar** [comment]
@sandy081 I needed to install the pre-release version of Extension A manually for the last step as it never said to use the pre-release version. This seems correct to me.

**Comment by DonJayamanne** [comment]
Similar comment, in the last step, I do not get any message there's an update, except a button `Switch to pre-release version` which showed up even earlier.
I agree with @Tyriar I do not think I should get an update button either, manually installing the pre-release ended up installing 0.0.3 version.
