### ISSUE TITLE
Test: Paste Markdown Links with the Smart Setting

### ISSUE THREAD

**Issue by MeghanKulkarni** [microsoft/vscode#188632]
Refs: https://github.com/microsoft/vscode/pull/188437

- [x] macOS @isidorn
- [x] windows @deepak1556 
- [x] linux @ulugbekna

Complexity: 3

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23188632%0A%0A&assignees=MeghanKulkarni)

----

Description:  The automatic pasting of links into the Markdown editor is now be smart by default. The smart feature will detect when the user is pasting within a markdown link, whether the link is in between some text, and more.
Known Issue: https://github.com/microsoft/vscode/issues/188636

Testing: You can test the following with the setting markdown.editor.pasteUrlAsFormattedLink as always, smart, and never. In Code OSS when switching to a new setting, it takes some time to actually update.

- Highlight some text and paste a link over the text.
- Paste a link with multiple cursors.
- Paste the link over text with brackets and of multiple lines.
- Paste the link within a snippet (image (only images within the workspace), code block, inline math, etc.).
- Paste the link on top of an existing markdown link. 
- Any other protential use cases.

Verify that all of the following steps paste markdown links in an intuitive manner.

**Comment by zhouxinghong** [comment]
It would be perfect if the following features could be added, as so far `VSCode Markdown` does not support the following features:

Copying webpage content and pasting it into a markdown editor cannot retain the source format of webpage content, such as hyperlinks, emoticons, emoticons, bold, italic, images, and other original webpage content formats and information.

Windows 10
VSCode 1.81

**Comment by isidorn** [comment]
@MeghanKulkarni works great. Thank you for these improvement, they make this feature more pleasurable to use than before :)
