### ISSUE TITLE
[WelcomeUX] Help overlay is misaligned

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#18861]
Testing #18091 

It also doesn't account for my rearranged icons. Will be in the right order for the first run experience though.

![image](https://cloud.githubusercontent.com/assets/323878/22159403/8efbc872-def5-11e6-954d-a957d7039854.png)

**Comment by roblourens** [comment]
![image](https://cloud.githubusercontent.com/assets/323878/22159447/c963b68c-def5-11e6-940c-e2a58be1dab3.png)

**Comment by chrmarti** [comment]
Vertical misalignment is tracked as #18854. We will keep it static for now and improve on that later.

**Comment by roblourens** [comment]
You're probably right, the horizontal misalignment is tricky though because the branch name can be different widths, or absent.

**Comment by bgashler1** [comment]
One thing we can do is listen for the class `no-workspace`.  When this class is present, we can hide the arrow that points to problems.

**Comment by chrmarti** [comment]
It will look fine as long as the user does not have a Git repo initialized (or anything else adding to the status bar).

**Comment by IllusionMH** [comment]
Moreover it points to the left even when `workbench.sideBar.location` is set to `"right"`

**Comment by Tyriar** [comment]
Consider fixing this for the recovery build, the errors and warning in particular will probably happen very frequently.

**Comment by chrmarti** [comment]
Merging with #19491.
