### ISSUE TITLE
gopls not working

### ISSUE THREAD

**Issue by Kartikeya-Vanamali** [microsoft/vscode#188654]
I'm unable to resolve the issue of gopls in my VS Code. gopls gets installed but throws following errors following installation.

gopls client: couldn't create connection to server.

The gopls server failed to initialize.

runtime: pcHeader: magic= 0xfffffff1 pad1= 0 pad2= 0 minLC= 1 ptrSize= 8 pcHeader.textStart= 0x0 text= 0x10094e5e0 pluginpath= 
fatal error: invalid function symbol table
runtime: panic before malloc heap initialized

runtime stack:
runtime.throw({0x10145a8e1?, 0x7ff84c2f2360?})
	/usr/local/go/src/runtime/panic.go:1047 +0x5d fp=0x7ff7bf5b5e88 sp=0x7ff7bf5b5e58 pc=0x10098413d
runtime.moduledataverify1(0x0?)
	/usr/local/go/src/runtime/symtab.go:627 +0x806 fp=0x7ff7bf5b5f88 sp=0x7ff7bf5b5e88 pc=0x1009a25a6
runtime.moduledataverify(...)
	/usr/local/go/src/runtime/symtab.go:613
runtime.schedinit()
	/usr/local/go/src/runtime/proc.go:710 +0x3a fp=0x7ff7bf5b5fe0 sp=0x7ff7bf5b5f88 pc=0x100987b9a
runtime.rt0_go()
	/usr/local/go/src/runtime/asm_amd64.s:349 +0x11e fp=0x7ff7bf5b5fe8 sp=0x7ff7bf5b5fe0 pc=0x1009b819e
[Info  - 11:08:00] 
true
[Error - 11:08:00] gopls client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
runtime: pcHeader: magic= 0xfffffff1 pad1= 0 pad2= 0 minLC= 1 ptrSize= 8 pcHeader.textStart= 0x0 text= 0x1066a35e0 pluginpath= 
fatal error: invalid function symbol table
runtime: panic before malloc heap initialized

runtime stack:
runtime.throw({0x1071af8e1?, 0x7ff84c2f2360?})
	/usr/local/go/src/runtime/panic.go:1047 +0x5d fp=0x7ff7b9860e88 sp=0x7ff7b9860e58 pc=0x1066d913d
runtime.moduledataverify1(0x0?)
	/usr/local/go/src/runtime/symtab.go:627 +0x806 fp=0x7ff7b9860f88 sp=0x7ff7b9860e88 pc=0x1066f75a6
runtime.moduledataverify(...)
	/usr/local/go/src/runtime/symtab.go:613
runtime.schedinit()
	/usr/local/go/src/runtime/proc.go:710 +0x3a fp=0x7ff7b9860fe0 sp=0x7ff7b9860f88 pc=0x1066dcb9a
runtime.rt0_go()
	/usr/local/go/src/runtime/asm_amd64.s:349 +0x11e fp=0x7ff7b9860fe8 sp=0x7ff7b9860fe0 pc=0x10670d19e
[Error - 11:08:00] The gopls server failed to initialize.
[Error - 11:08:00] gopls client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
Error starting language server: Error: Pending response rejected since connection got disposedFailed to stop client: Error: Client is not running and can't be stopped. It's current state is: startFailed
runtime: pcHeader: magic= 0xfffffff1 pad1= 0 pad2= 0 minLC= 1 ptrSize= 8 pcHeader.textStart= 0x0 text= 0x109bbd5e0 pluginpath= 
fatal error: invalid function symbol table
runtime: panic before malloc heap initialized

runtime stack:
runtime.throw({0x10a6c98e1?, 0x7ff84c2f2360?})
	/usr/local/go/src/runtime/panic.go:1047 +0x5d fp=0x7ff7b6346e58 sp=0x7ff7b6346e28 pc=0x109bf313d
runtime.moduledataverify1(0x0?)
	/usr/local/go/src/runtime/symtab.go:627 +0x806 fp=0x7ff7b6346f58 sp=0x7ff7b6346e58 pc=0x109c115a6
runtime.moduledataverify(...)
	/usr/local/go/src/runtime/symtab.go:613
runtime.schedinit()
	/usr/local/go/src/runtime/proc.go:710 +0x3a fp=0x7ff7b6346fb0 sp=0x7ff7b6346f58 pc=0x109bf6b9a
runtime.rt0_go()
	/usr/local/go/src/runtime/asm_amd64.s:349 +0x11e fp=0x7ff7b6346fb8 sp=0x7ff7b6346fb0 pc=0x109c2719e
[Info  - 11:08:07] 
true
[Error - 11:08:07] gopls client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
runtime: pcHeader: magic= 0xfffffff1 pad1= 0 pad2= 0 minLC= 1 ptrSize= 8 pcHeader.textStart= 0x0 text= 0x1015245e0 pluginpath= 
fatal error: invalid function symbol table
runtime: panic before malloc heap initialized

runtime stack:
runtime.throw({0x1020308e1?, 0x7ff84c2f2360?})
	/usr/local/go/src/runtime/panic.go:1047 +0x5d fp=0x7ff7be9dfe58 sp=0x7ff7be9dfe28 pc=0x10155a13d
runtime.moduledataverify1(0x0?)
	/usr/local/go/src/runtime/symtab.go:627 +0x806 fp=0x7ff7be9dff58 sp=0x7ff7be9dfe58 pc=0x1015785a6
runtime.moduledataverify(...)
	/usr/local/go/src/runtime/symtab.go:613
runtime.schedinit()
	/usr/local/go/src/runtime/proc.go:710 +0x3a fp=0x7ff7be9dffb0 sp=0x7ff7be9dff58 pc=0x10155db9a
runtime.rt0_go()
	/usr/local/go/src/runtime/asm_amd64.s:349 +0x11e fp=0x7ff7be9dffb8 sp=0x7ff7be9dffb0 pc=0x10158e19e
[Error - 11:08:07] The gopls server failed to initialize.
[Error - 11:08:07] gopls client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
Error starting language server: Error: Pending response rejected since connection got disposedFailed to stop client: Error: Client is not running and can't be stopped. It's current state is: startFailed
runtime: pcHeader: magic= 0xfffffff1 pad1= 0 pad2= 0 minLC= 1 ptrSize= 8 pcHeader.textStart= 0x0 text= 0x1047865e0 pluginpath= 
fatal error: invalid function symbol table
runtime: panic before malloc heap initialized

runtime stack:
runtime.throw({0x1052928e1?, 0x7ff84c2f2360?})
	/usr/local/go/src/runtime/panic.go:1047 +0x5d fp=0x7ff7bb77de58 sp=0x7ff7bb77de28 pc=0x1047bc13d
runtime.moduledataverify1(0x0?)
	/usr/local/go/src/runtime/symtab.go:627 +0x806 fp=0x7ff7bb77df58 sp=0x7ff7bb77de58 pc=0x1047da5a6
runtime.moduledataverify(...)
	/usr/local/go/src/runtime/symtab.go:613
runtime.schedinit()
	/usr/local/go/src/runtime/proc.go:710 +0x3a fp=0x7ff7bb77dfb0 sp=0x7ff7bb77df58 pc=0x1047bfb9a
runtime.rt0_go()
	/usr/local/go/src/runtime/asm_amd64.s:349 +0x11e fp=0x7ff7bb77dfb8 sp=0x7ff7bb77dfb0 pc=0x1047f019e
[Info  - 11:18:01] 
true
[Error - 11:18:01] gopls client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
runtime: pcHeader: magic= 0xfffffff1 pad1= 0 pad2= 0 minLC= 1 ptrSize= 8 pcHeader.textStart= 0x0 text= 0x10b55b5e0 pluginpath= 
fatal error: invalid function symbol table
runtime: panic before malloc heap initialized

runtime stack:
runtime.throw({0x10c0678e1?, 0x7ff84c2f2360?})
	/usr/local/go/src/runtime/panic.go:1047 +0x5d fp=0x7ff7b49a8e58 sp=0x7ff7b49a8e28 pc=0x10b59113d
runtime.moduledataverify1(0x0?)
	/usr/local/go/src/runtime/symtab.go:627 +0x806 fp=0x7ff7b49a8f58 sp=0x7ff7b49a8e58 pc=0x10b5af5a6
runtime.moduledataverify(...)
	/usr/local/go/src/runtime/symtab.go:613
runtime.schedinit()
	/usr/local/go/src/runtime/proc.go:710 +0x3a fp=0x7ff7b49a8fb0 sp=0x7ff7b49a8f58 pc=0x10b594b9a
runtime.rt0_go()
	/usr/local/go/src/runtime/asm_amd64.s:349 +0x11e fp=0x7ff7b49a8fb8 sp=0x7ff7b49a8fb0 pc=0x10b5c519e
[Error - 11:18:01] The gopls server failed to initialize.
[Error - 11:18:01] gopls client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
Error starting language server: Error: Pending response rejected since connection got disposedFailed to stop client: Error: Client is not running and can't be stopped. It's current state is: startFailed
runtime: pcHeader: magic= 0xfffffff1 pad1= 0 pad2= 0 minLC= 1 ptrSize= 8 pcHeader.textStart= 0x0 text= 0x1081235e0 pluginpath= 
fatal error: invalid function symbol table
runtime: panic before malloc heap initialized

runtime stack:
runtime.throw({0x108c2f8e1?, 0x7ff84c2f2360?})
	/usr/local/go/src/runtime/panic.go:1047 +0x5d fp=0x7ff7b7de0e58 sp=0x7ff7b7de0e28 pc=0x10815913d
runtime.moduledataverify1(0x0?)
	/usr/local/go/src/runtime/symtab.go:627 +0x806 fp=0x7ff7b7de0f58 sp=0x7ff7b7de0e58 pc=0x1081775a6
runtime.moduledataverify(...)
	/usr/local/go/src/runtime/symtab.go:613
runtime.schedinit()
	/usr/local/go/src/runtime/proc.go:710 +0x3a fp=0x7ff7b7de0fb0 sp=0x7ff7b7de0f58 pc=0x10815cb9a
runtime.rt0_go()
	/usr/local/go/src/runtime/asm_amd64.s:349 +0x11e fp=0x7ff7b7de0fb8 sp=0x7ff7b7de0fb0 pc=0x10818d19e
[Info  - 12:26:36] 
true
[Error - 12:26:36] gopls client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
runtime: pcHeader: magic= 0xfffffff1 pad1= 0 pad2= 0 minLC= 1 ptrSize= 8 pcHeader.textStart= 0x0 text= 0x10b2b95e0 pluginpath= 
fatal error: invalid function symbol table
runtime: panic before malloc heap initialized

runtime stack:
runtime.throw({0x10bdc58e1?, 0x7ff84c2f2360?})
	/usr/local/go/src/runtime/panic.go:1047 +0x5d fp=0x7ff7b4c4ae58 sp=0x7ff7b4c4ae28 pc=0x10b2ef13d
runtime.moduledataverify1(0x0?)
	/usr/local/go/src/runtime/symtab.go:627 +0x806 fp=0x7ff7b4c4af58 sp=0x7ff7b4c4ae58 pc=0x10b30d5a6
runtime.moduledataverify(...)
	/usr/local/go/src/runtime/symtab.go:613
runtime.schedinit()
	/usr/local/go/src/runtime/proc.go:710 +0x3a fp=0x7ff7b4c4afb0 sp=0x7ff7b4c4af58 pc=0x10b2f2b9a
runtime.rt0_go()
	/usr/local/go/src/runtime/asm_amd64.s:349 +0x11e fp=0x7ff7b4c4afb8 sp=0x7ff7b4c4afb0 pc=0x10b32319e
[Error - 12:26:36] The gopls server failed to initialize.
[Error - 12:26:36] gopls client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
Error starting language server: Error: Pending response rejected since connection got disposed

**Comment by roblourens** [comment]
You can file this on the Go extension repo
