### ISSUE TITLE
[WelcomeUX] Find all references looks weird in walkthrough

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#18875]
Testing #18091 

Maybe we don't care, or maybe we want to disable it or something in those little editors.
![jan-20-2017 10-04-24](https://cloud.githubusercontent.com/assets/323878/22159923/04f2a436-def8-11e6-8301-1a30a3b0a43c.gif)

**Comment by mjbvz** [comment]
Disabled this via 5b25934bace96443d24687344aee96ae0432f348

**Comment by roblourens** [comment]
Cool, thanks. That seems like a very specific flag to have in common editor code though? I wonder if it should be 'disableInsetEditor' or something else generic.

**Comment by mjbvz** [comment]
@roblourens Maybe `isInEmbeddedEditor` so the clause here would be `!isInEmbeddedEditor`?

@chrmarti any thoughts?

**Comment by mjbvz** [comment]
Renamed context to isInEmbeddedEditor

**Comment by chrmarti** [comment]
Sounds good, thanks.

**Comment by roblourens** [comment]
Yeah 'embedded' was the word I was looking for. Sounds good.
