### ISSUE TITLE
Test: Notebook Sticky Scroll

### ISSUE THREAD

**Issue by Yoyokrazy** [microsoft/vscode#188728]
Refs: #182444

- [x] anyOS @hbons
- [x] anyOS @karrtikr
- [x] anyOS @gregvanl

Complexity: 3

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23188728%0A%0A&assignees=Yoyokrazy)

--- 
## Summary:

Notebooks now support a sticky scroll, resembling the standard editor experience. The notebook will track sticky "headers" based on markdown headers present in notebook md cells. 

## Steps to Test:
- Enable sticky scroll via either of the following -- preferably try both :)
  - Use command palette `View: Toggle Notebook Sticky Scroll` 
  - Use setting in UI or json `notebook.stickyScroll.enabled`
- Ensure that you can toggle the setting via the command palette
- Open a notebook with an assortment of markdown headers
  - Endgame notebooks work great, and you can find a couple examples littered in [my testing repo](https://github.com/Yoyokrazy/ipynb-playground).
- Scroll until you have a sticky line/header rendered, and ensure you can right click, finding a context menu, and toggle the sticky scroll.
- Click on the sticky line to focus the md cell with that header, ensure it is visible in the viewport.
- Scroll up and down throughout various header sections and ensure there is no pop-in or out of multiple lines at a time. transitions are not animated as nicely as the editor sticky scroll, work for future here, but they should appear 1 at a time. 

- If you find any issues, I would greatly appreciate a gif of the bug, alongside the file you are using to test!
- Any overall UX feedback is appreciated! This is early stages, and polish will be coming.

## Known Bugs/Planned Work: 
(feel free to reference or comment on these to bring attention/provide more examples)
- https://github.com/microsoft/vscode/issues/188690
- https://github.com/microsoft/vscode/issues/188703
- https://github.com/microsoft/vscode/issues/188688
   
--- 
Thanks so much for testing!

**Comment by hbons** [comment]
* Confirmed I can toggle the setting via the command palette.
* Confirmed I can see sticky headers opening https://github.com/Yoyokrazy/ipynb-playground/sticky_test.ipynb
* Confirmed I can toggle off the setting using the context menu on the sticky header.
<img width="330" alt="image" src="https://github.com/microsoft/vscode/assets/103326/6777302a-fbb8-4470-aa02-90a0942888c4">
* Confirmed I can click on the sticky line and the header becomes visible in the viewport
* Confirmed sticky headers pop in/out as I'm scrolling the document.

What feels a bit weird to me that sticky headers can sometimes disappear. I don't get the logic behind it. Sticky headers should stick around. :)

**Comment by gregvanl** [comment]
Yep, I also found it confusing as to when a sticky header would appear. 
Scrolling through woooooo.ipynb in the testing repo, I had to scroll several times past `Sec` before it would appear in the sticky scroll UI. 
I would have expected the header to be displayed right after it scrolled out the top of the view port.
