### ISSUE TITLE
Increase the default contrast of command window

### ISSUE THREAD

**Issue by pcgeek86** [Microsoft/vscode#1887]
The default coloring of the Command Palette looks nice, but on one of my monitors, at certain viewing angles, it is impossible to see the selected item. I have pretty good eyes, and it's mostly the fault of the monitor, but since there are lots of cruddy monitors out there, it would probably be advisable to increase the default contrast of the Command Palette.

![screen shot 2016-01-08 at 2 33 49 pm](https://cloud.githubusercontent.com/assets/466713/12210109/ee24cf5c-b614-11e5-9610-78cb92b9fd11.png)

The monitor I'm having trouble with is the Samsung PX2370. Generally speaking, the monitor is quite gorgeous, but as I mentioned, contrast is problematic at certain angles.

http://www.amazon.com/Samsung-PX2370-23-Inch-Widescreen-Backlight/dp/B003HFG6S0

Cheers,
Trevor Sullivan

**Comment by bgashler1** [comment]
@pcgeek86 Thanks for bringing this to our attention.  Are there any other colors that you are having trouble with?

**Comment by pcgeek86** [comment]
@bgashler1 Of course, happy to help. I'm not aware of any others that I'm currently having trouble with. I'm sure I'll discover any other challenges over time, and will report them accordingly.

Cheers,
Trevor Sullivan
Microsoft MVP: PowerShell

**Comment by bgashler1** [comment]
I just experienced this myself on a similar monitor with light theme.  I'll be addressing these contrast issues soon.  Just wanted to give you an update.

**Comment by pcgeek86** [comment]
@bgashler1 Great, thanks for your recognition and commitment to improving the VS code experience. I'm really impressed with how your team handles feedback. It should be used as an example across Microsoft.

Cheers,
Trevor Sullivan

**Comment by bpasero** [comment]
Closing, with theming you can install a theme that changes this contrast. You can also actually configure this via settings now.
