### ISSUE TITLE
[WelcomeUX] Checkbox should be aligned with text

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#18879]
Testing #18091

![image](https://cloud.githubusercontent.com/assets/2193314/22160054/9c08eb28-def8-11e6-91c2-7e60b9fff2ed.png)

**Comment by bgashler1** [comment]
This doesn't seem to be an issue now that the serif font bug is gone.

**Comment by Tyriar** [comment]
@bgashler1 I saw this on Linux, I couldn't see styles that made an effort to align so it could differ between platforms.

**Comment by ramya-rao-a** [comment]
Still an issue in Windows, not so much in Mac

![image](https://cloud.githubusercontent.com/assets/16890566/22308340/64c40bf0-e2fb-11e6-93c9-f21372197560.png)

**Comment by bpasero** [comment]
Not aligned on Windows:

![image](https://cloud.githubusercontent.com/assets/900690/22363504/0dda7f2e-e46b-11e6-9cb0-00eade42eb8b.png)

@chrmarti try playing around with `line-height` on the parent div, e.g. 20px gives me this:

![image](https://cloud.githubusercontent.com/assets/900690/22363517/21454f30-e46b-11e6-8bd8-d194f4ee2ea6.png)

**Comment by chrmarti** [comment]
On OSX:

1.9:
![screen shot 2017-01-30 at 1 45 29 pm](https://cloud.githubusercontent.com/assets/9205389/22443060/66408a4e-e6f2-11e6-9c4e-5a7135968564.png)

With line-height 20px on parent:
![screen shot 2017-01-30 at 1 47 16 pm](https://cloud.githubusercontent.com/assets/9205389/22443118/a4be8cb2-e6f2-11e6-94d1-71c4d30a0c39.png)

With line-height 18px on parent:
![screen shot 2017-01-30 at 1 49 29 pm](https://cloud.githubusercontent.com/assets/9205389/22443206/f312c3ba-e6f2-11e6-9b83-b9548377cf95.png)

One would think there must be a canonical way of doing this, but I haven't found one yet.

**Comment by Tyriar** [comment]
This seems to do the trick, looks right on Windows at least http://stackoverflow.com/a/719545/1156119

```css
input[type=checkbox] {
  vertical-align: middle;
  position: relative;
  bottom: 1px;
}
```

Could also try this one which has the most votes: http://stackoverflow.com/a/306593/1156119

**Comment by chrmarti** [comment]
Thanks @Tyriar for looking into it. Unfortunately this doesn't work well on Mac:
![image](https://user-images.githubusercontent.com/9205389/46401772-3ea82580-c6fe-11e8-8feb-3c11aebda54e.png)

**Comment by chrmarti** [comment]
Reverting for now. On Mac:
![image](https://user-images.githubusercontent.com/9205389/46479238-ec92fd00-c7ee-11e8-96e0-f2999aa8769a.png)

**Comment by Tyriar** [comment]
Not sure there's a nice way to do this without OS-specific CSS rules 😕
