### ISSUE TITLE
Possibility to create composit profiles

### ISSUE THREAD

**Issue by m-thalmann** [microsoft/vscode#188759]
I have created multiple profiles for the different technologies I use (e.g. Angular, PHP, Python, etc.). But sometimes I have workspaces where I use multiple different technologies at the same time. It would be great to be able to create a profile that consists of multiple other selected profiles, merging the settings from them.

An example for me would look like the following:
- Base Profile (includes Settings, Keyboard, base extensions)
- PHP Profile (includes PHP extensions)
- Angular Profile (includes Angular extensions)
- Angular + PHP Profile (base profile + php profile + angular profile)

The benefit of this would be, that the extensions for a single technology could be managed inside of one profile, which would then propagate to all of the depending ones (of course also all other settings).
Of course it would be possible to create separate profiles and manually adding the required extensions for each stack individually, but that is not really a viable option for me.

I hope the description explains my problem well enough, otherwise please ask.

Would that be something realistic to add to VSCode? Or is there any other way something like that could be achieved?

Thanks for considering it!

**Comment by sandy081** [comment]
Does the following works for you?

- Create a Profile that uses Default Profile for settings and keyboard shortcuts
- This Profile has extensions for the workspace - PHP, Angular

**Comment by m-thalmann** [comment]
Well it does work, but not in the way I need.
If I use any new extension, which I want to use across multiple profiles, I will have to add it to each one individually (simply adding it to the "Default Profile" does not work). The same problem occurs when wanting to add an extension to a specific technology, which is used in multiple profiles.

Currently my "workflow" is to disable all non-basic extensions and enable them for each workspace individually (without using profiles). It would be much nicer to use the profiles for this, but is currently not an option for me.

I hope this clarifies things... thanks!

**Comment by sandy081** [comment]
> If I use any new extension, which I want to use across multiple profiles

There is a feature which we implemented in this milestone to apply an extension for all profiles.

Check this test plan item for more details - https://github.com/microsoft/vscode/issues/188614

**Comment by m-thalmann** [comment]
I see! Yeah that is somewhat what I am looking for. Altough this only works for when I want to apply something to all profiles, not just a subset of them.
Are there any plans of only applying those settings/extensions onto some selected profiles? If that were the case, all of my problems would be solved

**Comment by sandy081** [comment]
> Are there any plans of only applying those settings/extensions onto some selected profiles? If that were the case, all of my problems would be solved

Unfortunately not. From the above use case you mentioned, this should work for your scenario right?

**Comment by m-thalmann** [comment]
Hmm. It would only work for a part of the problem. I have not fully shown my scenario, sorry! Here is what profiles I would have in total:

- Default
- Angular
- PHP
- C
- Python
- Laravel (PHP + some extension)
- Laravel + Angular
- Python + Angular
(and maybe some more)

If I now found a new extension I wanted to use for Angular I would have to add it to all the profiles using Angular seperately.

But that should not be too big of an issue. The bigger problem was applying an extension to all profiles, which should be possible soon, right?

In that case I think we can close this issue. Thank you very much!
