### ISSUE TITLE
Unable to download extension from within VSCode, but manual download works

### ISSUE THREAD

**Issue by bangbambang** [microsoft/vscode#188734]
Type: <b>Bug</b>

Step to reproduce:
- Go to extension, search for an extension from Marketplace
- VSCode will show broken list of extension. Where list of search result is fetched successfully, but icons and extension details are missing.
- Pick one from list of extension, fetching extension detail will time out.
- Click install from the list of extension on the left side and wait, the request will fail and a prompt to manually download VSIX file will be displayed.
- Download and install the extension manually without problem.

![Screenshot 2023-07-25 073521](https://github.com/microsoft/vscode/assets/412919/2378d568-ffd3-44de-b3b7-632563418615)

![Screenshot 2023-07-25 072831](https://github.com/microsoft/vscode/assets/412919/c0a67bc5-154c-47fc-b660-bc543f3e764c)

Referring to https://github.com/microsoft/vscode/issues/97131#issuecomment-625320517 that mention DNS issue, I've whitelisted related domain referred on [the documentation](https://code.visualstudio.com/docs/setup/network#_common-hostnames) to no avail. 

![Screenshot 2023-07-25 072900](https://github.com/microsoft/vscode/assets/412919/7399c77e-62cd-48cd-9e2f-e5556d37dde5)

Visiting the failed URL directly from browser also didn't work, nor ping-ing vsassets.io. Resetting my DNS to DHCP also failed to remedy the situation. At this point, I'm stuck on how to trace the error. Any help would be appreciated.

VS Code version: Code 1.80.1 (74f6148eb9ea00507ec113ec51c489d6ffb4b771, 2023-07-12T17:22:07.651Z)
OS version: Windows_NT x64 10.0.22621
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8350U CPU @ 1.70GHz (8 x 1896)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.88GB (14.40GB free)|
|Process Argv|--crash-reporter-id 96ad111e-4051-4b0c-b9af-6a47b07ad0e9|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
rainbow-csv|mec|3.7.0
powershell|ms-|2023.6.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
vsccc:30610678
2e4cg342:30602488
f6dab269:30613381
a9j8j154:30646983
showlangstatbar:30737416
vsctsb:30748421
03d35959:30757346
pythonfmttext:30731395
pythoncmv:30756943
fixshowwlkth:30771522
hideindicator:30785051
pythongtdpath:30769146
i26e3531:30792625
pythonnosmt12:30779714
pythonidxpt:30784022
pythonnoceb:30776495
e537b577:30795824
dsvsc013:30795093
dsvsc014cf:30791936
cmakesidepanelv2:30779593

```

</details>

**Comment by bangbambang** [comment]
Clean install (includes removing `.vscode`) apparently solved the problem.

Will see if this issue resurface later.

**Comment by sandy081** [comment]
This seems to be a networking issue. 

> Clean install (includes removing .vscode) apparently solved the problem.
Will see if this issue resurface later.

Please reopen if you can reproduce it again
