### ISSUE TITLE
Feature Request - Shortcut for pasteUrlAsFormattedLink

### ISSUE THREAD

**Issue by Linhieng** [microsoft/vscode#188736]
Description:

The recently added `markdown.editor.pasteUrlAsFormattedLink.enabled` feature is very useful, but I believe there is room for improvement.

I hope there is a shortcut key for `markdown.editor.pasteUrlAsFormattedLink.enabled: true` setting in Visual Studio Code. This way, when I paste with the normal paste shortcut `ctrl+v`, it recognizes it as text. But **when I paste with the new shortcut(like `alt+v`), vscode recognizes it as a link**.

This approach would address the issue in Visual Studio Code where certain text strings, such as `start:end:step`, are mistakenly recognized as links and converted to `[Title](start:end%253Astep)`.

![image](https://github.com/microsoft/vscode/assets/73024851/ae488355-069f-4695-bc55-4de2b0a0dae8)

(I have reviewed the submission guidelines and searched for similar suggestions, but haven't found any identical proposals. If there are any aspects of my submission that do not meet the guidelines, please let me know, and I will make the necessary improvements.)

**Comment by Linhieng** [comment]
I saw "smart paste should be disabled if the user hasn't made a selection" in [#188871](https://github.com/microsoft/vscode/issues/188871)

Yes, this is a good method, but not enough. Consider this scenario: When the user wants to modify a link, the user tends to select and then paste, instead of deleting link and then paste.

**Comment by Linhieng** [comment]
The problem has fix. But the staff didn't seem to want to add a shortcut key feature?

So should I close this issue?

**Comment by Linhieng** [comment]
Maybe one day I can PR this issue by myself in the future? 😀

**Comment by mjbvz** [comment]
To insert a markdown link (not from the clipboard, you can create a new keybinding for `insertSnippet`:

```
    {
		"key": "cmd+shift+v",
		"command": "editor.action.insertSnippet",
		"when": "editorLangId == 'markdown'",
		"args": {
			"langId": "markdown",
			"name": "Insert link" 
		}
	}
```

To use create a link from the url in the clipboard, you can use this keybinding in the current VS Code insiders:

```
    {
		"key": "cmd+shift+v",
		"command": "editor.action.pasteAs",
		"when": "editorLangId == 'markdown'",
		"args": {
			"id": "vscode.markdown-language-features.insertMarkdownLink"
		}
	},
```

However this keybinding will only work if you have a valid url in the clipboard

**Comment by Linhieng** [comment]
The final resolution I took is so follows:

Edit the `settings.json`.

```json
"markdown.editor.pasteUrlAsFormattedLink.enabled": "always",
```

And then add the follow code to the `keybindings.json`: 

```json
    {
        "key": "ctrl+shift+v",
        "command": "editor.action.pasteAs",
        "when": "editorLangId == 'markdown'",
        "args": {
            "id": "text"
        }
    },
```

Now when you want to paste a link as plain text, just type `ctrl+shift+v`, otherwise type `ctrl+v`.

---

In addition, the "smart pasteUrlAsFormattedLink" seems to be getting dumber. There is a example: 

I want add a link to the sentence "可视化学习 git", but when the sentence is not in a single line, it is not smart.

- Bad situation:

paste before:
![image](https://github.com/microsoft/vscode/assets/73024851/0ba08556-289c-48ba-8c15-d340433ce9e2)

paste after:
![image](https://github.com/microsoft/vscode/assets/73024851/29ee0e45-0a80-4b94-8734-d8a7fd659ed1)

- Good situation:

paste before:
![image](https://github.com/microsoft/vscode/assets/73024851/b8a49c81-f84e-4e68-bdad-dc453f628877)

paste after:
![image](https://github.com/microsoft/vscode/assets/73024851/c8f8305b-aa7d-4baa-b1ab-201fe7a5a6fc)

**Comment by andreamah** [comment]
Are the steps to verify this issue as described in https://github.com/microsoft/vscode/issues/188736#issuecomment-1898088614?

**Comment by mjbvz** [comment]
@andreamah  Try the second keybinding in https://github.com/microsoft/vscode/issues/188736#issuecomment-1888186502

**Comment by andreamah** [comment]
I got 
<img alt="image" src="https://github.com/microsoft/vscode/assets/31675041/e7d1553f-b525-45ed-ac7e-b7ed320ad0ae">

but that's the same thing when I do a regular paste (ctrl+v). Is this expected?

**Comment by chrmarti** [comment]
I get the following with `https://microsoft.com` in the clipboard:

![Image](https://github.com/microsoft/vscode/assets/9205389/0d99187f-5865-41df-917e-3c4d75f30a83)

It works with `"id": "text"`.

Version: 1.86.0-insider
Commit: 3dea5cbbcb88d7f6dad71148f3d3f98b853ab836
Date: 2024-01-25T08:11:55.952Z
Electron: 27.2.3
ElectronBuildId: 26495564
Chromium: 118.0.5993.159
Node.js: 18.17.1
V8: 11.8.172.18-electron.0
OS: Darwin arm64 22.6.0

**Comment by mjbvz** [comment]
@chrmarti Seems to work for me. Did you disable `markdown.editor.pasteUrlAsFormattedLink.enabled`?

**Comment by chrmarti** [comment]
Indeed, it works when I change that to something else than `never`. A bit surprising that the setting takes precedence over the keybinding assignment maybe, but I understand this is expected then. Closing as verified with that. Thanks.
