### ISSUE TITLE
The Explorer Icon does not show on Activity Bar and when right click it

### ISSUE THREAD

**Issue by phinqomt** [microsoft/vscode#188740]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.80.1
- OS Version: Mac OS 13.4.1 (c)

Steps to Reproduce:

1. Open VS Code (it still show on image-1.png)
![image-1](https://github.com/microsoft/vscode/assets/102004992/3bd94a54-7d79-4034-b87d-c829c797f165)
2. Open any Project (it not show on image-2.png)
![image-2](https://github.com/microsoft/vscode/assets/102004992/f0a6b76d-5e1d-4e96-a44c-61e8b9444579)

**Comment by gjsjohnmurray** [comment]
Please use the Reset View Locations command from the Command Palette.

**Comment by phinqomt** [comment]
It's not working
![Screenshot 2023-07-25 at 10 51 06](https://github.com/microsoft/vscode/assets/102004992/d23f34bc-6ee3-4a91-b1db-e73ea2a8c840)

**Comment by phinqomt** [comment]
I tried with Reset Explorer and working now. Thank you guys
![Screenshot 2023-07-25 at 10 52 35](https://github.com/microsoft/vscode/assets/102004992/766a07c5-d3f0-411d-9869-df70c66cc9c3)

**Comment by gjsjohnmurray** [comment]
> It's not working

Do you remember if you had the problem "project" open when you ran that command?

**Comment by phinqomt** [comment]
@gjsjohnmurray No, I have not get any problem

**Comment by lramos15** [comment]
If you create a new folder on your desktop and open that in VS Code is it gone too?

**Comment by phinqomt** [comment]
@lramos15 I'm not sure, btw now it's working fine.

**Comment by lramos15** [comment]
✨ Magic ✨
