### ISSUE TITLE
Ctrl+alt+m to create terminal with profile does not show quick pick

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#188771]
Testing #188528

Repro:

1. Enable screen reader mode
2. Focus terminal
3. Press ctrl+alt+m, 🐛 git bash on my machine was opened, there was no quick pick

**Comment by meganrogge** [comment]
Are you suggesting that by using the steps in the TPI before this, it somehow interfered with this unrelated command?

**Comment by Tyriar** [comment]
I found this bug while testing the TPI, they're only related because it's called out in a11y help

**Comment by meganrogge** [comment]
this is working for me - and you provide no arg for that keybinding?

https://github.com/microsoft/vscode/assets/29464607/c449939a-6747-4bb5-9930-992748ec103b

**Comment by Tyriar** [comment]
🤦 for some reason I have this in my keybindings:

```
{ "key": "ctrl+alt+m",       "command": "workbench.action.terminal.newWithProfile", "args": { "profileName": "Git Bash" } }
```
