### ISSUE TITLE
Behavior of user installed extension in vscode.dev as built-in extensions

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#188758]
Testing #188615

I have the Live Share extension installed in insiders.vscode.dev already. I have disabled it. When I tried the `/liveshare/SESSIONID` route, I found the extension still disabled. 

I was also able to uninstall it.

After uninstalling and reloading, Live Share was correctly installed as built-in and enabled.

**Comment by sandy081** [comment]
> I have the Live Share extension installed in insiders.vscode.dev already. I have disabled it. When I tried the /liveshare/SESSIONID route, I found the extension still disabled.

There is embedder API that this route uses to force enable the extension. If this is not happening this should be a bug on VS Code.

> I was also able to uninstall it.

This is currently designed if user has extension installed.

**Comment by sandy081** [comment]
> I have the Live Share extension installed in insiders.vscode.dev already. I have disabled it. When I tried the /liveshare/SESSIONID route, I found the extension still disabled.

I cant reproduce this. Can you please provide the steps?

**Comment by alexr00** [comment]
I'm pretty sure these were my steps:
1. Turn on settings sync on desktop
2. Install live share
3. Disable live share
4. Open insiders.vscode.dev/github/microsoft/vscode
5. Turn on settings sync and let things sync
6. See that live share is installed + disabled
7. Go to insiders.vscode.dev/liveshare/SESSIONID

I am trying again now.

**Comment by alexr00** [comment]
Confirmed. Those steps do reproduce the issue.

**Comment by sandy081** [comment]
> Go to insiders.vscode.dev/liveshare/SESSIONID

What do you see when open this URL? If `SESSIONID` is invalid, following dialog is shown 

<img width="779" alt="image" src="https://github.com/microsoft/vscode/assets/10746682/98aeed48-831f-429c-bdb9-005d5013b8b3">

You have to press `x` on the dialog. Pressing OK will redirect to "https://insiders.vscode.dev"

**Comment by alexr00** [comment]
I pressed neither, it just goes away quickly on it's own then redirects to "https://insiders.vscode.dev/"

**Comment by alexr00** [comment]
If I'm very quick and hit the `x` then this issue does not repro.
