### ISSUE TITLE
Empty notification center requires show notifications to be called twice before it is focused

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#188763]
Testing #188528

Repro:

1. Enable screen reader mode
2. Focus the editor
3. Run the show notification command, :bug: the editor is still focused
3. Run the show notification command, the notification center is now focused?

**Comment by bamurtaugh** [comment]
My notification was read once fully, then the screen reader started reading it a second time. Part way through that second time, the notification no longer seemed selected (didn't have a blue box around it), and the screen reader just stopped reading it.

**Comment by meganrogge** [comment]
the `document.activeElement` looks correct here, but I can repro the focus getting stuck in the editor
