### ISSUE TITLE
Test: Only launch pty host when needed

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#188720]
Refs: https://github.com/microsoft/vscode/issues/182637

- [x] macOS @eleanorjboyd
- [x] linux @chrmarti
- [x] windows @brettcannon (Optional)
- [x] windows @amunger

Complexity: 3

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23188720%0A%0A&assignees=Tyriar)

---

The "pty host" process that owns all the shell processes launched by the terminal now no longer launches eagerly on startup. This should make very little difference to the user but we expect startup to be slightly faster (~in the 10s of milliseconds) and to save 50-100mb of RAM when no terminal is used.

For the following test cases, open the process explorer via the help menu and ensure the pty host only appears when the first terminal starts:

- Close all terminals, restart VS Code, ensure pty host did not start, open the terminal, pty host should start
- Create 1 terminal, run any command, restart VS Code, ensure pty host _did_ start (due to revived process)
- Anything other edge case you can think of that could cause bugs/race conditions.

**Comment by eleanorjboyd** [comment]
Thank you for the very clear steps!
