### ISSUE TITLE
open remote workspace from command line

### ISSUE THREAD

**Issue by cdornan** [microsoft/vscode#188738]
I have searched the docs and issue tracket for this but could not find anything -- apologies if I missed this.

The request is a simple one. Working on remote systems over ssh works so well that I am making heavy use of it, which makes it increasingly desirable to be able to initiate a session from the command line.

I am looking for something like:
```
code ssh://dev.remote.com/work
```
or perhaps
```
code dev.remote.com:work
```
which would be equivalent to `Remote-SSH: Connect to host...` and selecting `dev.remote.com` and opening the `work` folder.

[Thanks for all of your brilliant work, btw; it is very much appreciated.]

**Comment by jpiland16** [comment]
Is this link what you were looking for?

https://code.visualstudio.com/docs/remote/troubleshooting#_connect-to-a-remote-host-from-the-terminal

**Comment by cdornan** [comment]
Yes, that is exactly what i was looking for &msash; thanks.
