### ISSUE TITLE
[WelcomeUX] Arrows have different font weight than rest of overlay text

### ISSUE THREAD

**Issue by mousetraps** [Microsoft/vscode#18873]
Testing #18091

![image](https://cloud.githubusercontent.com/assets/762848/22159859/c1aa64b6-def7-11e6-8d7d-1e298ad32359.png)

**Comment by bgashler1** [comment]
This is fixed in the design but not implemented yet.  Will update when done.

**Comment by bgashler1** [comment]
I think we were using a mismatch of fonts.  Closing for now, but feel free to reopen if you notice this again from the latest.
