### ISSUE TITLE
Error Load

### ISSUE THREAD

**Issue by marroq** [Microsoft/vscode#18876]
- VSCode Version: Code 1.7.2 (7ba55c5860b152d999dda59393ca3ebeb1b5c85f, 2016-11-21T22:06:37.428Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions:

|Extension|Author|Version|
|---|---|---|
|javadebugger|donjayamanne|0.0.2|
|php-debug|felixfbecker|1.10.0|
|crane|HvyIndustries|0.2.2|
|format-indent|Kasik96|1.3.0|
|csharp|ms-vscode|1.6.2|

---

Does not open the file when double-clicking, only opens the editor.

**Comment by dbaeumer** [comment]
@marroq can you please provide steps how to reproduce. Which file doesn't open. Can you attach a screen cast showing the problem.

**Comment by marroq** [comment]
I do double click in the file but visual studio code can't open the file, only opens the editor

![vsc](https://cloud.githubusercontent.com/assets/8166309/22351403/5a5a87f6-e3dd-11e6-8633-f139a91a0265.PNG)

**Comment by dbaeumer** [comment]
Not sure if the is an installer problem or a workbench problem.

**Comment by bpasero** [comment]
I think we fixed this in 1.9.
