### ISSUE TITLE
VSCode seems to disappear from the computer

### ISSUE THREAD

**Issue by LucasVati** [microsoft/vscode#188893]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.80.1
- OS Version: Windows 11 (Ubuntu 22.04 in WSL2)

The issue is the same as described in https://github.com/microsoft/vscode/issues/154726. The issue has been closed but the problem seams to remain. 

1. I had VSCode installed for more than a year, it was working perfectly fine. I could see the icon in the taskbar.
2. Yesterday when I started the computer I saw the icon changed to blank, and it showed that 'code.exe' had been moved
![image](https://github.com/microsoft/vscode/assets/79976388/33dda7c6-45b6-4c4a-ad89-155097ca576a)
3. Since I couldn't find vscode anywhere in the PC i installed it again. After work, I shut down the computer.
4. Today I start the computer, but the icon on the taskbar VSCode disappears.

EDIT :  I saw a tip in the previous github issue so I could find the app in `%localappdata%\Programs\Microsoft VS Code`.
However it is still strange that the icon disappears !

**Comment by joaomoreno** [comment]
Are you creating that shortcut yourself manually?

**Comment by LucasVati** [comment]
No it was automatically created at the installation

**Comment by joaomoreno** [comment]
Are you using the user or the system setup?

**Comment by LucasVati** [comment]
I have only one user on my PC and I picked the default installation. 
Based on the description of both (https://code.visualstudio.com/docs/setup/windows) and the fact I don't need to use admin rights to launch vscode, I would say I'm using the user setup

**Comment by joaomoreno** [comment]
And when this happens, does `Code.exe` exist in `%localappdata%\Programs\Microsoft VS Code`? Can you share a screenshot of the contents of that folder, in that situation?

**Comment by joaomoreno** [comment]
So... if `Code.exe` is there, but Windows complains that it's not there...

What path _exactly_ does the shortcut point to?

**Comment by LucasVati** [comment]
Hello, I read the whole thing again and I haven't been very clear, so I'm sorry about that, I try to explain using other words.

The issue of vscode that disappears happened at the day n, and i couldn't find it on the pc.  So installed vscode again. 

The day n+1 the shortcut disappeared again. I thought initially that I would have to install it again and I didn't want to have to do it everyday, so I started to write this issue to share to you. Once I finished to write the issue, I found that I could try to find vscode by going in the path `%localappdata%\Programs\Microsoft VS Code`. It worked so I could open vscode and pin it in the taskbar, and it is good for me now. 

So the problem is solved for me, and that is what i tried to explain in the EDIT in the first post, but I think it hasn't been understood.

I kept the issue because it isn't normal that vscode uninstalls itself at the beginning, so I wanted you to know that this happens sometimes. But I can't reproduce the issue since I installed vscode again after the issue happened.

**Comment by AndreaJsy** [comment]
I had the same issue too. I restart my windows 11 laptop, then vscode disappeared without any notice. After I look for this path (`%localappdata%\Programs\Microsoft VS Code`) in my File Expolorer, it becomes this (screenshot), which makes no sense to me. 
![image](https://github.com/microsoft/vscode/assets/97689754/08135a1b-a94b-4736-8b0f-699ba225d1f6)

**Comment by balaji-sivasakthi** [comment]
@AndreaJsy Could you share your windows version?

**Comment by joaomoreno** [comment]
@LucasVati Thanks for the update. So it isn't Code which disappears, but its shortcut. Glad to know that it decided to stick around this time.

@AndreaJsy You're hitting a known update bug, sadly, #47841. As a workaround, please disable Windows background updates by setting `update.enableWindowsBackgroundUpdates` to `false`.
