### ISSUE TITLE
Run Test Task no-ops

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode#188807]
Testing #188684

1. Open VS Code repo
2. Run Test Task from command palette (I'm not sure what this command does)
3. :bug: nothing happens

**Comment by meganrogge** [comment]
any errors in the `Tasks` output channel? does it always repro for you?

https://github.com/microsoft/vscode/assets/29464607/4836b5bf-dade-427a-9d4c-76007dc90d8c

**Comment by joyceerhl** [comment]
Always repros, no errors in tasks output channel even after enabling debug logging

**Comment by joyceerhl** [comment]
What is that recording supposed to show? It has length 0 for me, I only see the default build tasks getting run?

**Comment by meganrogge** [comment]
> What is that recording supposed to show?

That something happens for me when I call `Run test task` as opposed to "🐛 nothing happens"

I see why the default build task is running for me - pretty sure that's not what's supposed to happen here and likely a recent regression.

https://github.com/microsoft/vscode/blob/8820c6f381578a1bd07d6608f003223e041fd78a/src/vs/workbench/contrib/tasks/browser/abstractTaskService.ts#L2973-L2975

**Comment by meganrogge** [comment]
Expectation to verify: the vscode test script gets run when that command is invoked
