### ISSUE TITLE
`workbench.editorAssociations` does not respect full filenames

### ISSUE THREAD

**Issue by max06** [microsoft/vscode#188804]
Type: <b>Bug</b>

Extension installed: `stateful.runme`

Goal: Open all `*.md`-Files with the default editor, except for `Container.md` which should be opened with `runme`.

Configuration:

```json
				"workbench.editorAssociations": {
					"*.md": "default",
					"Container.md": "runme"
				},
```

The setting for `*.md` is respected, the second one isn't. No matter how I change the config, it's always the same result. I can assign all markdown files to runme, or all to default. Specifying full filenames doesn't have any noticable effect. 

VS Code version: Code - Insiders 1.81.0-insider (fda972663af87b4d1dab87845e36c357738b44f9, 2023-07-25T08:12:53.439Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Remote OS version: Linux x64 5.15.0-1041-azure

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 9 3950X 16-Core Processor             (32 x 3493)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|63.92GB (24.33GB free)|
|Process Argv|--crash-reporter-id ecbd11e2-224f-4385-94f0-5b494aa6300d|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|Dev Container: Node.js & TypeScript @ ssh://gec|
|OS|Linux x64 5.15.0-1041-azure|
|CPUs|AMD Ryzen 7 5700X 8-Core Processor (16 x 3393)|
|Memory (System)|12.09GB (9.83GB free)|
|VM|0%|
</details>

**Comment by bpasero** [comment]
My guess is that we go through the list and pick the first that matches, not looking for more specific matches. Maybe the editor resolver should prefer a match that does not use wildcards over those with wildcards, assuming it is a more specific match.

**Comment by bpasero** [comment]
Oh, I think some logic like that already exists?

https://github.com/microsoft/vscode/blob/9ce6f947b4290a7aaa51134c476d6d660b1ecd3a/src/vs/workbench/services/editor/browser/editorResolverService.ts#L359-L362

**Comment by max06** [comment]
> My guess is that we go through the list and pick the first that matches, not looking for more specific matches. 

I tested for that case by putting the full filename first in the list - no change. It doesn't even match if it's the only entry in that list.
