### ISSUE TITLE
Prepending fails on zsh with only shell integration enabled

### ISSUE THREAD

**Issue by karrtikr** [microsoft/vscode#188875]
Testing #182970

```typescript
envVarCollection.prepend('PS1', '(.venv) ', {
    applyAtProcessCreation: false,
    applyAtShellIntegration: true,
});
```
seems to fail on zsh shell:

![image](https://github.com/microsoft/vscode/assets/13199757/fefb9aa1-2c4a-48f5-ba96-8caba6714b15)

**Comment by karrtikr** [comment]
Let me know if we're unable to fix this in time, in which case I'll stop prepending for zsh in Python extension.

**Comment by Tyriar** [comment]
Looking into it now
