### ISSUE TITLE
Markdown url smart paste should be disabled inside of html blocks

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#188868]
1. Copy `http://example.com`
1. In a md file:
```md
<b>

</b>
```
3. Paste between the html elements 

**bug**
This inserts markdown syntax even though markdown typically isn't supported inside of html like this:

```md
<b>
[Title](http://example.com/)
</b>
```

**Comment by mjbvz** [comment]
Likely requires a proper markdown parser to fix

**Comment by andreamah** [comment]
Uploading markdown link test.mp4…

I don't know if this is the expected result, since I don't see any difference pasting in the tags. I tried using two versions of `markdown.editor.pasteUrlAsFormattedLink.enabled`.

**Comment by mjbvz** [comment]
@andreamah Thanks for testing. I think there's still a bug with `smart`. In this case it should likely not paste as a markdown link. Somewhat weird case because it's the pasting itself that makes the html span multiple lines. With the newlines it's two entirely separate html blocks according to markdown
