### ISSUE TITLE
Allow an ability to resize the quick question window

### ISSUE THREAD

**Issue by andreamah** [microsoft/vscode#188847]
Testing #188542

[![Image from Gyazo](https://i.gyazo.com/b3a2359b2f1b6207b417b98010b7a968.gif)](https://gyazo.com/b3a2359b2f1b6207b417b98010b7a968)

With `"chat.experimental.quickQuestion.mode": "inputOnTopChat"`, having a really short last question makes the window small and hard to scroll. Not too sure what the fix would be for this, but it'd be nice not to be so limited by the popup size.

**Comment by TylerLeonhardt** [comment]
@roblourens and I had a prototype where as you scroll up, it pulllllllls the list down like a drawer. That way you had more real estate to scroll back.

I need to bring that prototype to life

**Comment by TylerLeonhardt** [comment]
This was covered on a TPI back in August. https://github.com/microsoft/vscode/issues/191496
