### ISSUE TITLE
No Decorators or file markers appear for files from original repo when testing repository deduplication

### ISSUE THREAD

**Issue by bhavyaus** [microsoft/vscode#188828]
Testing #188584

When both the original and the symlink are opened in the same workspace (Repository deduplication):

 - The editor gutter decorator for a file with edits only appear for files from the symlink. If I open the same file from the original repo and edit it, no editor decorators appear.
- The file markers in the explorer also behave similarly. Editing files from the original repo, cause the symlink file markers to be updated with an M

Is this the expected behavior? I'm not familiar with this scenario of when someone will have both the original and symlink open in the same workspace. I'd expect the file markers and edits to show up in both places.

**Comment by joaomoreno** [comment]
Same for TS errors:

<img width="612" alt="image" src="https://github.com/microsoft/vscode/assets/22350/e85b6beb-b5bf-4c5b-8710-8a738dfe7bb6">

Something tells me we shouldn't start optimizing for this unrealistic scenario. It's a never ending source of edge cases, for very little gain.
