### ISSUE TITLE
cut off text in quick question box

### ISSUE THREAD

**Issue by amunger** [microsoft/vscode#188809]
Testing #188542

<img width="452" alt="image" src="https://github.com/microsoft/vscode/assets/2019016/7d63d2d6-d29e-4040-962a-4998a307b49a">

**Comment by amunger** [comment]
oh, I just didn't realize there was a scrollbar, even though I specifically remember the conversation about showing cut-off text to imply that there is text above that can be scrolled to.

**Comment by TylerLeonhardt** [comment]
Yeah the cut off text is intentional. Similar to what we do in the Command Palette at the bottom:
![image](https://github.com/microsoft/vscode/assets/2644648/8f82d653-bc77-4f9d-8e8f-8b7cb6d0c50e)

This helps the user understand that you are able to scroll back... in addition to the scrollbar.

**Comment by TylerLeonhardt** [comment]
I'm gonna close this as `by-design` but will keep in mind that it is a bit jarring.
