### ISSUE TITLE
test quick question: quick question button with layout controls

### ISSUE THREAD

**Issue by andreamah** [microsoft/vscode#188848]
Testing #188542

When I set `"chat.experimental.defaultMode": "quickQuestion"`, I was really confused on where the button was, since I disabled layout controls on my title bar. Eventually, I found it, but it was a little confusing. I'm not too sure if it should be toggled on and off by the "Layout Controls`

<img width="129" alt="image" src="https://github.com/microsoft/vscode/assets/31675041/c1c94fa7-2445-4e86-91e3-bb6f0b7cd1ab">

**Comment by TylerLeonhardt** [comment]
The button isn't there anymore and is instead in the Command Center when opened.

![Image](https://github.com/microsoft/vscode/assets/2644648/50636d20-b1e9-4ba1-8e1e-50f9a8fd1358)
