### ISSUE TITLE
[WelcomeUX] Recent paths would be better truncated from left side

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#18885]
Testing #18091

Since the right-side is the most specific it might be better to use `.../foo/bar`?

![image](https://cloud.githubusercontent.com/assets/2193314/22160265/7f0f41ce-def9-11e6-9151-f34d05747b4b.png)

**Comment by chrmarti** [comment]
I'm not sure if there is an easy way to do this. If this can't be done in CSS, we will have to measure the text and do the truncation ourselves.

**Comment by Tyriar** [comment]
Yeah after thinking about it I can't think of a nice way to do this either. It probably wouldn't have that much impact anyway due to the size of monitors these days and the fact the actual folder name is in blue. Don't worry about this one :smiley:

**Comment by bgashler1** [comment]
Yeah, I wanted to do this, too, but I couldn't think of a simple way.

Later, if this is an issue, we could apply `::before` pseudo elements over the strings that add an ellipses on the left-hand side.  Then clip on the left by absolutely positioning to the right and using an internal flex box.  Sounds kind of complicated but maybe possible.
