### ISSUE TITLE
Segmentation failure

### ISSUE THREAD

**Issue by Souradeephazra123** [microsoft/vscode#188815]
Type: <b>Bug</b>

When i go to run a program in c++, it always show segmentation fault,but it is absolutely correct.

VS Code version: Code 1.80.1 (74f6148eb9ea00507ec113ec51c489d6ffb4b771, 2023-07-12T17:22:07.651Z)
OS version: Windows_NT x64 10.0.22621
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 3 5300U with Radeon Graphics          (8 x 2595)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|7.33GB (0.95GB free)|
|Process Argv|--crash-reporter-id d3496f69-4b8d-4663-8461-4174f23813f3|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (40)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|3.0.2
ReactSnippets|ale|1.2.1
blackbox|Bla|1.0.48
path-intellisense|chr|2.8.4
vscode-eslint|dba|2.4.2
denigma|den|0.0.15
javascript-ejs-support|Dig|1.3.3
chatgpt-gpt4-gpt3-vscode|Eas|1.0.2
vscode-toggle-column-selection|eri|1.0.6
prettier-vscode|esb|9.19.0
file-icons|fil|1.1.0
auto-close-tag|for|0.5.14
code-runner|for|0.12.0
vscode-pull-request-github|Git|0.68.1
stylelint-plus|hex|0.56.6
vscode-styled-components-snippets|lXS|1.0.2
vscode-language-babel|mgm|0.0.39
graphql|mqu|0.1.2
remote-containers|ms-|0.299.0
cmake-tools|ms-|1.14.34
cpptools|ms-|1.16.3
cpptools-extension-pack|ms-|1.3.0
color-highlight|nau|2.5.0
vscode-graphql|ors|0.3.18
vscode-rapidapi-client|Rap|1.10.2
vscode-services|rap|1.0.2
java|red|1.20.0
LiveServer|rit|5.7.9
tabnine-vscode|Tab|3.6.77
cmake|twx|0.0.17
intellicode-api-usage-examples|Vis|0.2.7
vscodeintellicode|Vis|1.2.30
vscode-java-debug|vsc|0.52.0
vscode-java-dependency|vsc|0.23.0
vscode-java-pack|vsc|0.25.12
vscode-java-test|vsc|0.39.0
vscode-maven|vsc|0.41.0
vscode-icons|vsc|12.4.0
vscode-todo-highlight|way|1.0.5
markdown-all-in-one|yzh|3.5.1

(4 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
2e4cg342:30602488
89544117:30613380
2i9eh265:30646982
showlangstatbar:30737416
vsctsb:30748421
03d35959:30757346
pythonfmttext:30731395
pythoncmv:30756943
fixshowwlkth:30771522
showindicator:30785052
pythongtdpath:30769146
i26e3531:30792625
pythonnosm12tcf:30779713
pythonidxpt:30784022
pythonnocebcf:30776496
e537b577:30795824
dsvsc013:30795093
dsvsc014cf:30791936
cmakestatusbarv2:30779594

```

</details>

**Comment by roblourens** [comment]
This sounds like an issue with your code or configuration
