### ISSUE TITLE
[WelcomeUX] Scrollbar temporarily can't scroll up in editor walkthrough

### ISSUE THREAD

**Issue by mousetraps** [Microsoft/vscode#18882]
Testing #18091

1. Scroll to the very top of the page

2. Click one of the options below to visit the relative link
![image](https://cloud.githubusercontent.com/assets/762848/22160110/d00f1d16-def8-11e6-88cf-fb7604396a98.png)

3. Navigation succeeds, but in order to scroll back up, you must first scroll down

**Comment by chrmarti** [comment]
Tracked with #18864
