### ISSUE TITLE
Settings are included in a partial profile export even if not enabled

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#188811]
Testing #188613

1. Create a partial profile that .e.g only contains extensions
2. Export the profile
3. 🐛 notice the exported profile contains user settings even though I didn't include this. Importing the profile will suggest importing the settings

**Comment by sandy081** [comment]
It is not included by default. It is shown in the UI and unselected by default. It is up to the user to include them or not.

<img width="326" alt="image" src="https://github.com/microsoft/vscode/assets/10746682/8af4177d-1a61-4534-9916-2cbe1a5e1397">

Are you seeing differently?

**Comment by connor4312** [comment]
That is the state in the UI, but the settings are still present in the exported `.code-profile` file even if it's unchecked. Then importing offers to import the settings.

This could be concerning as a user especially if I have private details like auth tokens in my settings.

**Comment by sandy081** [comment]
Got it. Good catch.
