### ISSUE TITLE
Error starting from command line

### ISSUE THREAD

**Issue by paulacamargo25** [microsoft/vscode#188855]
Testing #188689

I follow the steps for Mac. But i got a weird behaviour.
1. The first time I ran `code-exploration` in an external terminal a new window appeared, but with the same tabs as the one already open, so I thought it was a bug as I don't see the point of having two instances with the same tabs.
2. I tried to reproduce the first error, so I closed the new window. When I run `code-exploration` again in an external terminal. A new window appears, that is, another icon, and after a few seconds it disappears, and the old one focuses.

<img width="1792" alt="Screenshot 2023-07-25 at 3 01 44 PM" src="https://github.com/microsoft/vscode/assets/17892325/cf1e7acc-d3d8-49d5-b565-8d0178af7ba7">
<img width="1792" alt="Screenshot 2023-07-25 at 3 01 54 PM" src="https://github.com/microsoft/vscode/assets/17892325/42fd4012-ff3f-4858-871d-53e0586b7016">

**Comment by deepak1556** [comment]
Can you provide a screen capture of the steps you tried, I am unable to repro the issue.

> A new window appears, that is, another icon, and after a few seconds it disappears, and the old one focuses.

This is the expected flow. But if takes longer than 1-2s for the second icon to disappear then there is a bug.

**Comment by paulacamargo25** [comment]
Hi @deepak1556 , i just follow the steps in the TPI, but as I mentioned, that only happened the first time I tried it.

**Comment by deepak1556** [comment]
Thanks for clarifying, I will close this issue for now due to lack of repro. Can reopen if there are new reports.
