### ISSUE TITLE
Should markdown url smart paste be disabled if the user hasn't made a selection?

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#188871]
1. Copy `http://example.com`
2. Paste into a md file without any making any selection

**Bug**
Currently this inserts a markdown link. However this is different from what GitHub does. Github seems to only create a link if you have a selection

We should at least think about:

- Matching GitHub's behavior
- Adding a setting that lets us match GitHub's behavior

**Comment by mjbvz** [comment]
Last iteration I think @isidorn had another related idea: disabling smart paste if you are inside of a word #186289

**Comment by isidorn** [comment]
I agree we should think about selection + smart paste. It boils down to - how often do users want to have a URL in markdown as a full https link? If the answer is > 30% then I think we should only have smart paste on selection.
To get a sense for this question - we could analyse top markdown repos on GitHub and see how often is a http link in Markdown without it being rendered as a markdown [link]().

As for disabling smart paste if in a word - I still think this makes sense. I like that we have disable smart paste if in a link - thanks for that!

**Comment by af4jm** [comment]
I'm seeing that same behavior, even though I have `"markdown.editor.pasteUrlAsFormattedLink.enabled": "never"` in my settings... which is obviously getting ignored... if I paste a link at `[test](|)` (where | marks the cursor position, I also get the smart link

**Comment by lgarron** [comment]
This also keeps tripping me up. I assumed I had chosen a bad configuration, but it sounds like this actually can't be configured easily. Both "always" and "smart" will try to create linked text, making it annoying to paste a URL directly.

I also agree that GitHub behaviour is much more practical.

If anyone has a combination of shortcuts and settings that matches GitHub, I'd love to know. Else, I'd love to learn a way to set ⌥⌘V to paste the link without formatting.

**Comment by lgarron** [comment]
> Else, I'd love to learn a way to set ⌥⌘V to paste the link without formatting.

Okay, I figured out how to do this:

```jsonc
// keybindings.json
[
  // Disable existing ⌥⌘V shortcuts — modify to taste
  {
    "key": "shift+cmd+v",
    "command": "-notebook.cell.pasteAbove",
    "when": "notebookEditorFocused && !inputFocus"
  },
  {
    "key": "shift+cmd+v",
    "command": "-markdown.showPreview",
    "when": "!notebookEditorFocused && editorLangId == 'markdown'"
  },
  // Enable ⌥⌘V for plain text paste
  {
    "key": "shift+cmd+v",
    "command": "editor.action.pasteAs",
    "args": {
      "id": "text"
    },
    "when": "editorLangId == 'markdown'"
  }
]
```

In theory it should be possible to use `editorHasSelection` to match GitHub's behaviour, but the following doesn't seem to work:

```json
[
  {
    "key": "shift+v",
    "command": "editor.action.pasteAs",
    "args": {
      "id": "text"
    },
    "when": "!editorHasSelection && editorLangId == 'markdown'"
  }
]
```

The next approach would be to trigger "smart" paste only when `editorHasSelection`, but I haven't figured out a way to do that yet.

**Comment by lgarron** [comment]
> The next approach would be to trigger "smart" paste only when `editorHasSelection`, but I haven't figured out a way to do that yet.

Okay, I think I've got it:

```jsonc
// keybindings.josn
[
  {
    "key": "cmd+v",
    "command": "editor.action.pasteAs",
    "args": {
      "id": "text"
    },
    "when": "!editorHasSelection && editorLangId == 'markdown'"
  },
  {
    "key": "cmd+v",
    "command": "editor.action.clipboardPasteAction",
    "args": {},
    "when": "editorHasSelection || editorLangId != 'markdown'"
  },
  {
    "key": "cmd+v",
    "command": "-editor.action.clipboardPasteAction"
  }
]
```

But this took over half an hour of experimentation + digging through the VS Code source code and documentation. And it still doesn't take into account notebook editors. I'd much rather see this as the default behaviour.

I presume this would involve adding an early `return` here, when there is currently no selection:
https://github.com/microsoft/vscode/blob/11bfd76a61a299156a9f3138ecfad70937af3527/extensions/markdown-language-features/src/languageFeatures/copyFiles/pasteUrlProvider.ts#L18

**Comment by lgarron** [comment]
> * `notebookEditorFocused`
> * `editorTextFocus`
> * ⌥⌘V to swap the default replacement behaviour with the opposite.

Here's a try for a version that takes these into account:

```jsonc
[
  {
    "key": "cmd+v",
    "command": "editor.action.pasteAs",
    "args": {
      "id": "text"
    },
    "when": "inputFocus && !editorHasSelection && editorLangId == 'markdown'"
  },
  {
    "key": "cmd+v",
    "command": "-editor.action.clipboardPasteAction",
    "when": "inputFocus && !editorHasSelection && editorLangId == 'markdown'"
  },
  {
    "key": "shift-cmd+v",
    "command": "editor.action.pasteAs",
    "args": {
      "id": "text"
    },
    "when": "inputFocus && (editorHasSelection || editorLangId != 'markdown')"
  },
  {
    "key": "shift-cmd+v",
    "command": "editor.action.clipboardPasteAction",
    "when": "inputFocus && !editorHasSelection && editorLangId == 'markdown'"
  },
  {
    "key": "shift+cmd+v",
    "command": "-notebook.cell.pasteAbove",
    "when": "notebookEditorFocused && !inputFocus"
  }
]

It still has issues with incorrect text selection after paste.

**Comment by Alecton4** [comment]
Can we rename the current `smart` option to something like `selectionOnly` and restore the behavior of the previous `smart` option? According to [this comment](https://github.com/microsoft/vscode/issues/189767#issuecomment-1673694847), `smart` now only creates a markdown link if some text is selected beforehand, which I guess is not "smart" enough.

I'm using Markdown to write notes, and reference links to other websites are often used. With the current `smart` option, I have to 1) type/paste the site title, 2) **select the title**, and 3) paste URL. But with the previous `smart` behavior, it's 1) paste URL, 2) **press `Tab`**, and 3) type/paste the site title. Selecting is more painful than just pressing `Tab` especially when lots of links need to be inserted.

**Comment by mjbvz** [comment]
This is now the default. You can then use the paste widget to switch after the paste has taken place

@Alecton4 Good idea. I think I'll add a new option called `smartWithSelection` that enables that. However the default will remain `smart` as this matches what Github does

**Comment by Alecton4** [comment]
> Then `smart` will be a new option that always applies

@mjbvz Thanks for making an improvement! But may I ask what is "always applies"? Will it apply even when pasting URLs inside inline codes/math, code/math blocks, comments, and existing ref links?
