### ISSUE TITLE
ASP.NET CORE MVC - HOT-RELOAD in launch.json acts buggy

### ISSUE THREAD

**Issue by bernd4** [microsoft/vscode#188894]
Type: <b>Bug</b>

Folders and files:
~/.vscode/launch.json
~/ProjectFolder/Properties/launchSettings.json

WHEN setting a configuration in launch.json for running a watch-command (with hot-reload), "AND" setting the parameter "launchSettingsProfile": "xxxxx"

THEN the desired launchProfile is only selected when there is a "comment" "somewhere" in the properties/launchSettings.json-file.

-----
WHEN there is no "comment" somewhere in the properties/launchSettings.json-file...

THEN the desired launchProfile set in the launch.json is NOT selected.

-----
It seems that,
IF the system can parse the properties/launchSettings.json-file properly,

THEN is doesn't take the launch.json specific configuration into account.

WHEN the system CAN'T properly parse the properties/launchSettings.json-file,

THEN it "does" take the launch.json specific configuration into account.

-----
What is going on here?
What am I doing wrong?
How can I properly create a hot-reload action WITH selecting a specific launchprofile configuration?

-----
I could just set a specific launchProfile in the properties/launchSettings,
and then set it as the first profile.
And call this with a vscode-task.
But then I don't use the lanch.json specific configuration functionality.
What is best practice here?
Or is this behaviour a bug?

-----
Files
[launch.json.txt](https://github.com/microsoft/vscode/files/12169165/launch.json.txt)
[launchSettings.json.txt](https://github.com/microsoft/vscode/files/12169159/launchSettings.json.txt)

-----

VS Code version: Code 1.80.1 (74f6148eb9ea00507ec113ec51c489d6ffb4b771, 2023-07-12T17:22:07.651Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 5700U with Radeon Graphics          (16 x 1797)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.34GB (8.27GB free)|
|Process Argv|--crash-reporter-id 346df053-e9a5-4980-8054-b942de19a289|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|16.1.4
vscode-html-css|ecm|1.13.1
dotnet-test-explorer|for|0.7.8
remotehub|Git|0.60.0
csharpextensions|kre|1.7.3
csharp|ms-|1.26.0
azure-repos|ms-|0.36.0
remote-repositories|ms-|0.38.1
vsliveshare|ms-|1.0.5877
material-icon-theme|PKi|4.29.0
LiveServer|rit|5.7.9

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
py29gd2263cf:30792227
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
vscccc:30610679
282f8724:30602487
89544117:30613380
a9j8j154:30646983
showlangstatbar:30737416
vsctsb:30748421
a2ce3375:30757347
57b77579:30736110
pythonfmttext:30731395
pythoncmvfstrcf:30756944
fixshowwlkth:30771522
showindicator:30785052
pythongtdpath:30769146
i26e3531:30792625
pythonnosmt12:30797651
pythonnoceb:30797650
e537b577:30795824
dsvsc013:30795093
dsvsc014cf:30797590
cmakestatusbarv2:30779594

```

</details>

**Comment by BerndBroos** [comment]
Here are the two *json files.

When there is a comment somewhere in the launchSettings.json,
Then is acts as expected.

When I there is NO comment in the launchSettings.json,
Then is acts NOT as expected.


C:\Users\Bernd\Documents\VSCProjecten\ASP.NET Core MVC\YouTube - DotNetMastery\BulkyProject\.vscode\settings.json

C:\Users\Bernd\Documents\VSCProjecten\ASP.NET Core MVC\YouTube - DotNetMastery\BulkyProject\BulkyWeb\Properties\launchSettings.json

**Comment by BerndBroos** [comment]
Here are the two *json files.

When there is a comment somewhere in the launchSettings.json,
Then is acts as expected.

When I there is NO comment in the launchSettings.json,
Then is acts NOT as expected.

[launch.json.txt](https://github.com/microsoft/vscode/files/12169127/launch.json.txt)
[launchSettings.json.txt](https://github.com/microsoft/vscode/files/12169130/launchSettings.json.txt)

**Comment by roblourens** [comment]
Please file this on the repo for the C# extension, thanks
