### ISSUE TITLE
Should markdown url smart paste disable / deprioritize itself when we don't paste markdown links?

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#188862]
Type: <b>Bug</b>

1. In a md file:

~~~md
```code

```
~~~

2. Paste a url inside the fence code blocks
3. Click the paste as widget that shows up

**bug**
<img width="745" alt="Screenshot 2023-07-25 at 3 31 41 PM" src="https://github.com/microsoft/vscode/assets/12821956/7cc7ffe5-6626-4ac4-83c6-ba279359bd16">

The paste as widget says that the url was pasted as a markdown link but really from the user's point of view it was just pasted the link as plain text

Some ideas on how to fix this if smart paste detects that we aren't actually going to insert a markdown link:

- Don't return any result from `PasteLinkEditProvider`. This will prevent the paste as widget from showing up

- `PasteLinkEditProvider` should always return an edit that inserts a `[text](link)` markdown link. However if smart paste detects that we are not in a valid link location (such as inside a code block) the markdown link pasting should be deprioritized so that the default paste happens first. Take a look at `DocumentPasteEdit.priority` for this

VS Code version: Code - Insiders 1.81.0-insider (Universal) (fda972663af87b4d1dab87845e36c357738b44f9, 2023-07-25T08:15:40.243Z)
OS version: Darwin x64 22.5.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|3, 3, 4|
|Memory (System)|32.00GB (0.10GB free)|
|Process Argv|--crash-reporter-id 48781ca2-1705-4f64-9bab-325055aab55d|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by alexr00** [comment]
I still see this:



![Image](https://github.com/microsoft/vscode/assets/38270282/2cff338e-5fb2-4ecb-b8a9-d430d74a6e9c)

**Comment by MeghanKulkarni** [comment]
So the new functionality is supposed to have the 'Smartly Insert Link' label which was previously the 'Insert as Markdown Link' label. This is a fix so that neither paste function is deprioritized and the labels still make sense to the user!

> I still see this:
> 
> ![Image](https://user-images.githubusercontent.com/38270282/256839576-2cff338e-5fb2-4ecb-b8a9-d430d74a6e9c.png)
