### ISSUE TITLE
test quick question: `inputOnBottomChat` has extra line at bottom

### ISSUE THREAD

**Issue by andreamah** [microsoft/vscode#188845]
Testing #188542

This is a nitpick, but when using `inputOnBottomChat`, I see an extra bottom border on the chat box area:
<img width="328" alt="image" src="https://github.com/microsoft/vscode/assets/31675041/ab414b47-1dcb-4d33-bd17-936148bd3190">

It's really faint, but I don't really see the point of having it? What does it separate?

**Comment by TylerLeonhardt** [comment]
This mode no longer exists.
