### ISSUE TITLE
[WelcomeUX] Walkthrough should be one word

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#18881]
Testing #18091 

![image](https://cloud.githubusercontent.com/assets/2193314/22160169/1392a922-def9-11e6-8d80-d62af09e9af7.png)

**Comment by chrmarti** [comment]
I have seen both and felt walk-through was more common.

**Comment by Tyriar** [comment]
Might be a locale thing? Looks really strange to me as en-AU. en-UK is likely the same as it's very similar.

Some data:

- `"walk through"` in Google -> 59,700,000 results
- `walkthrough` in Google -> 102,000,000 results
- There is no walk-through wikipedia page, but there is walkthrough https://en.wikipedia.org/wiki/Walkthrough
- http://www.wordwebonline.com/en/WALKTHROUGH seems to indicate "walkthrough" is used in particular within computing?

**Comment by bgashler1** [comment]
Stylistically, I like `walkthrough` better.  I don't like capitalizing more letters, and that helps us avoid that.

**Comment by seanmcbreen** [comment]
I adopted walkthru where I did see it in the content.

**Comment by ramya-rao-a** [comment]
Not a bug anymore since it is now called "Interactive Playground"
