### ISSUE TITLE
Light version is always used for `iconPath`

### ISSUE THREAD

**Issue by TylerLeonhardt** [microsoft/vscode#188830]
Testing #188683

Using the following code:
```ts
vscode.window.showQuickPick([{
			label: 'sample',
			iconPath: {
				light: vscode.Uri.parse('https://api.dicebear.com/6.x/pixel-art/png?seed=light'),
				dark: vscode.Uri.parse('https://api.dicebear.com/6.x/pixel-art/png?seed=dark')
			}
		}]);
```

I expect https://api.dicebear.com/6.x/pixel-art/png?seed=dark (green hair) to be rendered when I use a dark theme but instead I see https://api.dicebear.com/6.x/pixel-art/png?seed=light (red hair).

**Comment by alexr00** [comment]
Took a look at this, and I don't want to add a dependency on a service where there shouldn't be one. Will fix in August with @TylerLeonhardt's help.
