### ISSUE TITLE
Install pre-release button is available when the pre-release version is incompatible

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#188844]
Testing #188618

Following the steps on https://github.com/microsoft/vscode/issues/188618#event-9906146503, when extensions are verified by the marketplace it shows pre-release as an option to install:

<img width="868" alt="Screenshot 2023-07-25 at 11 47 27 am" src="https://github.com/microsoft/vscode/assets/2193314/47706ea3-d9f4-43c7-9985-ca9dd3a1967e">

Clicking it installs the stable version and opens up the ext detail page which also has a pre-release button:

<img width="608" alt="Screenshot 2023-07-25 at 11 49 07 am" src="https://github.com/microsoft/vscode/assets/2193314/ec400e7d-2c91-44b5-9e70-a2d4e52fad41">

Clicking this says loading and then shows the install pre-release button again

**Comment by sandy081** [comment]
This is as designed. Because we do the compatibility check after clicking on the instal button because it needed to fetch all versions of the extension which is expensive to do before installing.

**Comment by Tyriar** [comment]
It should be cached after you do it once then (at least for the lifetime of the window session) and/or have a some message telling the user what happened as it looks very broken when you press the button now.

**Comment by sandy081** [comment]
Showing a message is the best option. 

Before doing any changes, I will see how users react to this and wait for the feedback.

**Comment by Tyriar** [comment]
The chances a user will bother reporting this seem pretty low, it seems like an obviously confusing experience to me though.
