### ISSUE TITLE
Rerun Last Task prompts me for a task to run

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode#188805]
Testing #188684

1. Run any task in VS Code repo, e.g. npm: eslint
2. Run Rerun Last Task from command palette
3. :bug: get prompted to choose a task to run, I would expect that last task to be automatically selected

**Comment by meganrogge** [comment]
this was working in v1.77  - broken in v1.80 so a regression but not this iteration

**Comment by meganrogge** [comment]
interesting - this doesn't happen for certain tasks - like `npm: eslint`

**Comment by meganrogge** [comment]
does repro for `VS Code - Build`

**Comment by meganrogge** [comment]
Ok so for background / watch tasks that are currently running, like `VS Code - Build`, the command to use instead is `Restart Running Task`. 

For tasks with start/stop executions, if a user invokes `Rerun task` while that task is in progress, it currently shows a quickpick. We should instead do nothing. 

That command is meant to be used for tasks that have ceased execution.

**Comment by joyceerhl** [comment]
> interesting - this doesn't happen for certain tasks - like `npm: eslint`

fyi, I did repro this for `npm: eslint` specifically

**Comment by meganrogge** [comment]
Yes I could ultimately repro when that task was in progress 👍🏼 @joyceerhl
