### ISSUE TITLE
Alt+F2 should open the a11y view in the terminal

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#188927]
Even better than just adding the keybinding would be to unify these two systems so that the terminal actually uses the same a11y view mechanism. This would need a bit of work moving the features from the terminal's a11y view into the generic one (but then they would be available for other components to potentially use).

**Comment by meganrogge** [comment]
One difference is for the terminal, you can have several accessible views showing simultaneously
![Screenshot 2023-07-26 at 7 52 12 AM](https://github.com/microsoft/vscode/assets/29464607/55953f05-d900-4d5d-8554-cfb7f59bb076)

**Comment by meganrogge** [comment]
Now that we have go to symbol in the accessible view, the terminal can have a provider of the symbols via shell integration

**Comment by jvesouza** [comment]
Perhaps this information is not important, but alt+f2 is used in gnome to activate run dialog in which we can type a command to be executed.
