### ISSUE TITLE
[WelcomeUX] Scrollbars don't disappear after undoing all text changes

### ISSUE THREAD

**Issue by mousetraps** [Microsoft/vscode#18893]
Testing #18091

Type a bunch of text and new lines to make scrollbars appear
![image](https://cloud.githubusercontent.com/assets/762848/22160432/45e707be-defa-11e6-844c-434f42a8dd39.png)

After undoing  changes, scrollbars will remain in place even though content fits fine
![image](https://cloud.githubusercontent.com/assets/762848/22160498/a15f57f4-defa-11e6-982d-bc03efeb5061.png)

This also happens in the normal editor, but is more of an issue when you have limited space to work with.

**Comment by mousetraps** [comment]
Also, the page updates after switching tabs - not sure if that's expected
![image](https://cloud.githubusercontent.com/assets/762848/22160577/09f2812e-defb-11e6-84b0-0e74327b8881.png)

**Comment by chrmarti** [comment]
The last screenshot looks like not all changes were undone. Aren't line numbers only shown for existing lines?

**Comment by chrmarti** [comment]
Fixed by automatically growing/shrinking embedded editor's height. #18899
