### ISSUE TITLE
Electron: backport DPI related Windows fix

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#188911]
Refs: https://github.com/electron/electron/issues/10862

Upstream: https://chromium-review.googlesource.com/c/chromium/src/+/4673217

**Comment by gallegosdamian505** [comment]
```shell

```

**Comment by gallegosdamian505** [comment]
<details><summary>Details</summary>
<p>



</p>
</details>

**Comment by bpasero** [comment]
The upstream change will be available in Electron 27 with Chromium 117, so we can then do an exploration build to try it out.

https://chromiumdash.appspot.com/commits?commit=5bf7cfd44326bbaad9b85f9500151013b1d65c43&platform=Mac

![image](https://github.com/microsoft/vscode/assets/900690/5ec3c1c0-63cb-47f6-98ef-31331aaaef02)

**Comment by bpasero** [comment]
Oh, turns out that there is Electron `27` alpha out. I created an exploration build: https://builds.code.visualstudio.com/builds/exploration?commit=fe65440775961556476b03a8c764b18971f48784

**Comment by bpasero** [comment]
I tested the build on Windows and unfortunately I see no improvement around this hack:

https://github.com/microsoft/vscode/blob/bf1f6a2298fdfdd09060336417a5e892176200c7/src/vs/platform/windows/electron-main/windowImpl.ts#L354-L372

We still need it, otherwise the window opens with bad dimensions on a secondary monitor with `175%` scaling.

I suggest to not pursue this with a backport but wait for the official release.
