### ISSUE TITLE
Accessibility help doesn't show when message in chat editor is focused

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#188954]
Repro:

1. `Chat: Open Session in Editor`
2. Click the intro message
3. Alt+f1, :bug: nothing happens
4. Click the textbox
5. Alt+f1, the help shows

**Comment by rzhao271** [comment]
The original issue of Alt+F1 not showing when the intro message is focused still repros for me.

**Comment by meganrogge** [comment]
Yes, I actually misread the issue and fixed the bug where the accessible view wouldn't open, but not the one where accessibility help does not when this is focused.

**Comment by meganrogge** [comment]
The context key is false when I click the intro message. 

<img width="243" alt="Screenshot 2023-09-06 at 3 29 42 PM" src="https://github.com/microsoft/vscode/assets/29464607/e861e8c5-3021-47b1-9a18-547ae07ab88a">
