### ISSUE TITLE
Create a set of icons+colors for custom profiles

### ISSUE THREAD

**Issue by hbons** [microsoft/vscode#188972]
This will help to distinguish between profiles.

**Comment by hbons** [comment]
prototype: https://www.figma.com/proto/UUds5Y8NbX1C6Uce3maIwk/Public-ShareOut-%E2%80%93-Custom-Profiles-Icons%2FColors?page-id=1103%3A121377&type=design&node-id=1161-7037&viewport=274%2C433%2C0.25&t=ckLP7hOlFwtoqKlP-1&scaling=min-zoom&starting-point-node-id=1161%3A7037&mode=design

<img width="527" alt="image" src="https://github.com/microsoft/vscode/assets/103326/bc42b4e1-f301-4639-a378-1f18bcbd19b0">
<img width="493" alt="image" src="https://github.com/microsoft/vscode/assets/103326/5e6426b4-8f7c-4bc5-8cda-d5b119eed0f5">

**Comment by hbons** [comment]
New proposal for profile colours.

<img width="1653" alt="image" src="https://github.com/microsoft/vscode/assets/103326/ce101b36-8893-469f-a233-985d5178317d">

Added magenta, cyan, brown, and two greys for variety.

Removed the dark blue/indigo  as it doesn't provide enough contrast on dark backgrounds. Also removed purple because it looks too much like a

**Comment by hbons** [comment]
Here's a subset of the codicons we can use for the initial set of profile icons. There are mostly everyday objects, and avoids abstract concepts/actions. Will add a couple more later for diversity, specially in the hardware and languages areas.

hardware/devices:
`vm`, `server`, `record keys`, `device mobile`, `watch`

languages:
`ruby`, `python`, `html`, `code`, `react`

project types:
`window`, `library`,  `extensions`, `terminal`, `beaker`, `package`, `cloud`, `book`, `globe`, `database`, `notebook`

misc:
`gift`, `send`, `briefcase`, `megaphone`, `comment`, `telescope`, `credit card`, `map`, `device camera`, `device camera video`, `unmute`, `law`, `graph line`, `heart`, `home`, `index`, `mortar board`, `rocket`, `magnet`, `lock`, `milestone`, `tag`, `pulse`, `radio tower`, `smiley`, `symbol event`, `squirrel`, `symbol color`, `mail`, `key`, `pie chart`, `organization`, `preview`, `wand`, `star empty`, `lightbulb`, `symbol ruler`, `dashboard`, `calendar`, `shield`, `flame`, `compass`, `paintcan`, `archive`

<img width="564" alt="image" src="https://github.com/microsoft/vscode/assets/103326/5bec2ff4-3a78-41da-a2f7-d50513ac92f4">

**Comment by hbons** [comment]
@gjsjohnmurray Not yet. This is just the design prep work. We'll probably implement this month.

**Comment by Tyriar** [comment]
FYI the current list is not compatible with use in the terminal as key icons are missing like powershell, debian, ubuntu, etc. https://github.com/microsoft/vscode/issues/171076

**Comment by Tyriar** [comment]
If we add all the `terminal*` codicons to this the list will be sufficient for use in the terminal (https://github.com/microsoft/vscode/issues/171076). A good thing about the terminal is we don't need to worry too much about breaking existing users since they use codicon ids in the settings so their old selections will continue to work.

**Comment by starball5** [comment]
What's the rationale for not opening up to [all product icons](https://code.visualstudio.com/api/references/icons-in-labels)? Somebody asked about this on SO: https://stackoverflow.com/q/77242748/11107541

**Comment by Tyriar** [comment]
Reopening so the concerns above get looked at, forcing a subset when there's a reference doc seems like we're just introducing an inconsistency. We want a general icon picker, not just one exclusively for profiles.

**Comment by hbons** [comment]
Closing this as the original task has been completed. We should definitely share code for this for Terminals and support icon subsets.
