### ISSUE TITLE
Perf: understand slow renderer process creation on macOS

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#188913]
Even though our macOS perf bot is the best hardware, it runs slowest for the time to open a window until we load code:

![image](https://github.com/microsoft/vscode/assets/900690/1c85782e-044e-4fe2-a461-be82b9330979)

We should understand why that is, as it blocks the critical startup path.

**Comment by bpasero** [comment]
Looking at chrome traces, specifically `LaunchProcess` is not any slower compared to other processes (around `10-20ms`). I found the last `LaunchProcess` to be significantly slower (`100ms`) but that does not seem to be the renderer process from the timings.

One thing that stands out is that from the `NavigationControllerImpl::LoadURLWithParams` (starting around `1.467s`) until we load the `workbench.desktop.main.js` script (starting around `1.813s`), around `346ms` pass, which matches our perf dashboard observations.

Chrome Trace for reference from the perf bot with categories `navigation,base,disabled-by-default-base,disabled-by-default-v8.compile`:

[chrometrace_1717746025694.log.zip](https://github.com/user-attachments/files/15722077/chrometrace_1717746025694.log.zip)

**Comment by deepak1556** [comment]
> One thing that stands out is that from the NavigationControllerImpl::LoadURLWithParams (starting around 1.467s) until we load the workbench.desktop.main.js script (starting around 1.813s), around 346ms pass, which matches our perf dashboard observations.

As you have noted the renderer process launch only took 13ms, the main contributor here is the navigation stack the time from the render process got picked `FrameTreeNode::DidStartLoading` around 1.4s till the navigation got committed to the process `RenderFrameHostImpl::CommitNavigation` around 1.8s and in this phase `WillStartRequest` takes around 240ms. This function is mostly affected by what the registered navigation throttlers does, and in Electron we register a throttler to emit `will-navigate` and `will-frame-navigate` requests https://github.com/electron/electron/blob/c3b4cd987c618ee72d32f996a8f3ae9e3e80c2bf/shell/browser/electron_navigation_throttle.cc#L25-L63. It is very likely the cost we are paying comes from the sync event entering JS and awaiting the response. A next step here would be to disable the Electron throttler and see how the timing is affected.

**Comment by bpasero** [comment]
@deepak1556 what is the purpose of this throttler and is our code impacting the slowness somehow?

**Comment by deepak1556** [comment]
For Electron it serves the purpose of providing navigation events `will-navigate` and `will-frame-navigate` so that applications can control any navigation from the renderer process and abort requests before they are sent out to the network. Currently the throttler is not set to do much for browser initiated navigations like `loadURL` but given there is no other code that could impact `willStartRequest`, it is would be good to measure without the throttler.

**Comment by bpasero** [comment]
@deepak1556 great find, it sounds like for VS Code this throttler should be entirely disabled since we never change the navigation after `loadURL` is called.

It still would probably not explain though why we had 2 days of really fast renderer process creation.

**Comment by deepak1556** [comment]
> it sounds like for VS Code this throttler should be entirely disabled since we never change the navigation after loadURL is called.

Ideally yeah but we do need it for preventing any third-parties triggering a navigation from the renderer https://github.com/microsoft/vscode/blob/db4e4ff980f9061bb4d8455e617531f46d518328/src/vs/code/electron-main/app.ts#L402-L407, ex: `window.location`

**Comment by deepak1556** [comment]
> Currently the trace data lacks what is happening inside the throttler for main process initiated navigation, so I am adding that first

Nvm, the trace had the data for time inside throttler
<img width="1206" alt="Screenshot 2024-06-10 at 15 54 33" src="https://github.com/microsoft/vscode/assets/964386/4732f03d-a212-451b-aa1e-f0c21c8e9120">

it is sane 46us. From the time when `WillStartRequest` till are registered throttlers are run is the difference between `OnStartChecksComplete` - `WillStartRequest` and from the trace it ends up 512us but how is that `WillStartRequest` overall in the async stack ends up to around 250ms. It is actually calculated by https://source.chromium.org/chromium/chromium/src/+/main:content/browser/renderer_host/navigation_request.cc;l=693-701 , so it would be time from when `NavigationRequest::willStartRequest` was issued till the next child event was entered and in the navigation cycle that would be `NavigationRequest::onResponseStarted`. So it would be that the something on the response loading side has an effect. This data is missing from the current trace,

@bpasero next time can you capture a trace from the perf machine with categories "navigation,loading,network,renderer,blink,browser,base,disabled-by-default-loading,v8,disabled-by-default-network"

**Comment by bpasero** [comment]
@deepak1556 thanks for investigations! find the trace attached, I did it 3 times to ensure its not a one-off:

[traces.zip](https://github.com/user-attachments/files/15758446/traces.zip)

**Comment by deepak1556** [comment]
Yeah the delay is definitely in the loading, time from `OnStartChecksComplete` till `ThrottlingURLLoader::OnReceiveResponse` matches the async `WillStartRequest` stack.

<img width="1208" alt="Screenshot 2024-06-10 at 17 53 28" src="https://github.com/microsoft/vscode/assets/964386/71bdffcc-1f8e-4cb8-ad72-e115283f92e8">

We use custom protocols and the resource paths are passed into Electron for reading from the asar archives. We don't have trace points for the Electron loaders, I will add them next. We might have chances to optimize stuff at the best we will know exactly where the time is spent most in these loaders.

Something to try in parallel, how much difference does it make to read the workbench file using Node.js with [StreamProtocol](https://github.com/electron/electron/blob/main/docs/api/protocol.md#protocolregisterstreamprotocolscheme-handler-deprecated)

**Comment by bpasero** [comment]
@deepak1556 I was thinking that our current approach of returning the path as it is on disk must be the fastest:

https://github.com/microsoft/vscode/blob/db4e4ff980f9061bb4d8455e617531f46d518328/src/vs/platform/protocol/electron-main/protocolMainService.ts#L94-L120

Are you suggesting to instead try to read the file into memory and return that to see if it makes it faster?

**Comment by deepak1556** [comment]
Yeah I expect the current implementation to be faster but the alternative is also something I want to measure. Once I have loader trace points, I will compare both the numbers. The primary goal is to find where the 200ms is spent in the loader.

**Comment by bpasero** [comment]
It turns out that this does not reproduce anymore, as soon as the macOS perf machine is locked (i.e. the user login dialog shows). So this really seems to be OS related and not so much under our control, I think its OK to close this.
