### ISSUE TITLE
[WelcomeUX] Editor theme button refers to the theme using two words

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#18891]
Testing #18091

Is it the syntax theme or the editor theme?

![image](https://cloud.githubusercontent.com/assets/2193314/22160478/7be7c2b8-defa-11e6-92d3-f994e12dd395.png)

**Comment by bgashler1** [comment]
Technically it's "Color Theme" in both the product and documentation.  I'll make the change.
