### ISSUE TITLE
Notebook markdown search results not restored when showing find sidebar

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#188965]
Type: <b>Bug</b>

From #185289

1. Open a notebook with some rendered markdown
2. Do a workspace search for the rendered markdown
3. Hide the sidebar
4. Show the side bar again

**Bug**
The markdown search results don't show again

Search results in code cells are highlighted again when the sidebar is shown

VS Code version: Code - Insiders 1.81.0-insider (Universal) (862fa13002d8018c328931ee1edccfd4ca76447d, 2023-07-26T05:36:43.574Z)
OS version: Darwin x64 22.5.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|4, 4, 4|
|Memory (System)|32.00GB (0.25GB free)|
|Process Argv|--crash-reporter-id 48781ca2-1705-4f64-9bab-325055aab55d|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by osortega** [comment]
This doesn't repro anymore
https://github.com/user-attachments/assets/6be1eaef-eba6-4208-97cc-aa91ce64514a

Closing the issue
