### ISSUE TITLE
[WelcomeUX] Editor height in Walk-Through

### ISSUE THREAD

**Issue by rebornix** [Microsoft/vscode#18899]
Testing #18091 

Add new lines to any editor in the Walk-Through, we don't adjust the height the editor, instead we use scrollbar. 

However if you go the Welcome page and click Interactive Playground again, we restore what's in that particular editor with full height

![screen shot 2017-01-20 at 10 36 22 am](https://cloud.githubusercontent.com/assets/876920/22160841/4f5d67b4-defc-11e6-996b-eb25a10e5509.png)

Reload the window will flush the content and everything is back to normal.

**Comment by chrmarti** [comment]
Maybe we could adjust the editor's height on-the-fly to avoid having a vertical scrollbar in such a small text area.

**Comment by Tyriar** [comment]
The number of rows needs to be capped at a certain amount, ideally determined by the amount of space in the viewport because if the editor gets too large the cursor goes off screen with no way of viewing what you're typing (since the viewport is scrolled to top of editor when you type).

**Comment by chrmarti** [comment]
A cap would result in nested vertical scrollbars. I will instead let the main editor follow the cursor's position.

**Comment by Tyriar** [comment]
The problem still occurs where an editor larger than the viewport does not center on the cursor when typing.

**Comment by chrmarti** [comment]
Remaining issue tracked with #19458.
