### ISSUE TITLE
Invoke 'Rename' on delayed double click

### ISSUE THREAD

**Issue by NiklasGustafsson** [Microsoft/vscode#1889]
If I select a file or folder in the explorer pane, then select it again, typical UI behavior would be to take that as a 'Rename' intent. In VS Code, it appears to be a no-op, which feels counterintuitive.

**Comment by Tyriar** [comment]
FWIW Sublime and Atom (on Ubuntu) don't trigger a rename on a delayed second click either.

**Comment by isidorn** [comment]
This feature request will not be considered in the next 6-12 months roadmap and as such will be closed to keep the number of issues we have to maintain actionable. Thanks for understanding and happy coding!
