### ISSUE TITLE
Maximize button closes app on kde wayland

### ISSUE THREAD

**Issue by estnml** [microsoft/vscode#188907]
Type: Bug
Does this issue occur when all extensions are disabled?: Yes

Description: When opening vscode with flags "--enable-features=WaylandWindowDecorations --ozone-platform-hint=auto" placed in ~/.config/code-flags.conf, if i hit the maximize button or double click to title bar the application crashes in wayland session.

https://github.com/microsoft/vscode/assets/57932905/d53d45d9-d61e-48d2-9bde-c06c0ef148fd
- VS Code Version: 1.80.1-1
- OS Version: Linux arch 6.1.39-1-lts x86_64 GNU/Linux
- Electron Version: electron25.1

Steps to Reproduce:

1. Edit or create ~/.config/code-flags.conf
2. Append these two flags in seperate lines "--enable-features=WaylandWindowDecorations --ozone-platform-hint=auto"
3. Start the application. (if app is pinned to taskbar, start it by searching the app. Starting directly from the taskbar icon may open the app in x11 mode)
4. Click maximize button

**Comment by bpasero** [comment]
How does it work when you configure `window.titleBarStyle` to `custom`?

**Comment by deepak1556** [comment]
Thanks for the repro steps, merging to https://github.com/microsoft/vscode/issues/184124
