### ISSUE TITLE
Typescript crashes when I open a .ts file

### ISSUE THREAD

**Issue by AmilcarM11** [microsoft/vscode#188905]
Type: <b>Bug</b>

when I open a .ts file

VS Code version: Code 1.80.1 (74f6148eb9ea00507ec113ec51c489d6ffb4b771, 2023-07-12T17:22:07.651Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Remote OS version: Linux x64 5.15.90.1-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz (16 x 2304)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.71GB (6.16GB free)|
|Process Argv|--crash-reporter-id bcd1ea7d-e14d-4b1c-9e84-f13241a34a19|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-22.04|
|OS|Linux x64 5.15.90.1-microsoft-standard-WSL2|
|CPUs|11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz (8 x 2303)|
|Memory (System)|9.72GB (7.23GB free)|
|VM|0%|
</details><details><summary>Extensions (54)</summary>

Extension|Author (truncated)|Version
---|---|---
terraform|4op|0.2.5
better-comments|aar|3.0.2
Bookmarks|ale|13.4.1
Handlebars|and|0.4.1
jest-snippets|and|1.9.1
auto-rename-tag|for|0.1.10
vuetify-snippets|Gai|0.1.2
vue|jcb|0.1.5
vscode-peacock|joh|4.2.2
dotenv|mik|1.0.1
remote-containers|ms-|0.299.0
remote-ssh|ms-|0.102.0
remote-ssh-edit|ms-|0.86.0
remote-wsl|ms-|0.80.2
vscode-remote-extensionpack|ms-|0.24.0
remote-explorer|ms-|0.4.1
remote-server|ms-|1.3.0
material-icon-theme|PKi|4.29.0
vue-vscode-snippets|sdr|3.1.1
jenkinsfile-support|sec|0.1.0
svg-preview|Sim|2.8.3
vscode-todo-list|thi|1.0.4
vscode-icons|vsc|12.4.0
vuetify-vscode|vue|0.2.0
vscode-nginx|wil|0.7.2
JavaScriptSnippets|xab|1.8.0
TabOut|alb|0.2.2
vscode-zipfs|arc|3.0.0
npm-intellisense|chr|1.4.4
vscode-eslint|dba|2.4.2
gitlens|eam|14.1.1
prettier-vscode|esb|9.19.0
vscode-jest-runner|fir|0.4.66
gitlab-workflow|Git|3.69.0
gc-excelviewer|Gra|4.2.57
todo-tree|Gru|0.0.226
terraform|has|2.27.0
rest-client|hum|0.25.1
kubernetes-snippets|ipe|0.1.9
vscode-env|Iro|0.1.0
mongodb-vscode|mon|1.1.0
vscode-docker|ms-|1.26.0
vscode-kubernetes-tools|ms-|1.3.13
python|ms-|2023.12.0
vscode-pylance|ms-|2023.7.30
live-server|ms-|0.4.9
vsliveshare|ms-|1.0.5877
vetur|oct|0.37.3
docker-compose|p1c|0.5.0
vscode-yaml|red|1.14.0
vscode-coverage-gutters|rya|2.11.0
markdown-preview-enhanced|shd|0.6.8
vscode-helm|tec|0.4.0
markdown-all-in-one|yzh|3.5.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscoreces:30445986
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
vscccc:30610679
282f8724:30602487
f6dab269:30613381
2i9eh265:30646982
showlangstatbar:30737416
vsctsb:30748421
03d35959:30757346
ecj1e332:30736112
pythonfmttext:30731395
pythoncmvfstrcf:30756944
fixshowwlkth:30771522
showindicator:30785052
pythongtdpath:30769146
i26e3531:30792625
pythonnosmt12:30797651
pythonnoceb:30797650
e537b577:30795824
dsvsc013:30795093
dsvsc014cf:30797590

```

</details>

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?
