### ISSUE TITLE
[WelcomeUX] The bottom 50% of the bottom embedded editor lines cannot be clicked

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#18896]
Testing #18091

I cannot click on the last half of the #p3 line in the first editor.

**Comment by chrmarti** [comment]
Also in the regular editor. Maybe for the horizontal scrollbar and the bug is that it behaves the same when there is no horizontal scrollbar. @rebornix ?

**Comment by Tyriar** [comment]
Yes that's appears to be the reason
![image](https://cloud.githubusercontent.com/assets/2193314/22162218/981a4782-df02-11e6-8f65-30b0475a19a3.png)

Possible solutions:
- Always add an extra row?
- Force word wrap?

**Comment by rebornix** [comment]
These embeded editors don't inherit settings from User Setting or Workspace one but we can definitely have a good customized one for them.

**Comment by chrmarti** [comment]
Adding an extra row sounds reasonably simple.

**Comment by chrmarti** [comment]
Done as part of #18899
