### ISSUE TITLE
[WelcomeUX] command palette and sidebar behavior inconsistent in interface overview

### ISSUE THREAD

**Issue by rebornix** [Microsoft/vscode#18892]
Testing #18091

It might not be a valid issue, I just find it annoying. In Interface Overview, pressing `ctrl+shift+p` will launch the command palette under the overlay, and I can still type in the palette. While if I want to play around with the sidebar, I have click twice, the first one dismiss the overlay and the second one does the trigger.

**Comment by chrmarti** [comment]
Tracked with #18869
