### ISSUE TITLE
[WelcomeUX] Change default keyboard shortcuts button wording could use some work

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#18894]
Testing #18091

I was under the impression it was going to open keybindings.json. How about something like "Use/Load Another Editor's Keybindings"?

![image](https://cloud.githubusercontent.com/assets/2193314/22160491/957ad5a8-defa-11e6-929d-1747cc114ce2.png)

**Comment by bgashler1** [comment]
Changed to
![screen shot 2017-01-20 at 2 01 52 pm](https://cloud.githubusercontent.com/assets/11839736/22167075/10a7669c-df19-11e6-8a1f-87ea5bbbbc87.png)

**Comment by ramya-rao-a** [comment]
This is what it currently says:

![image](https://cloud.githubusercontent.com/assets/16890566/22308511/225b98fe-e2fc-11e6-9e66-2cf89a06e6e1.png)

**Comment by Tyriar** [comment]
I'm happy with the new one, the description is much better now :+1:
