### ISSUE TITLE
Code is not detecting changed files

### ISSUE THREAD

**Issue by mwherman2000** [microsoft/vscode#188922]
Type: <b>Bug</b>

If I edit and change a source file (e.g. .cs) inside or outside of Code, Code is not detecting that the file is changed so that I can check it in. The file doesn't appear in the list of changed files.  This is on Windows 11.

VS Code version: Code 1.80.1 (74f6148eb9ea00507ec113ec51c489d6ffb4b771, 2023-07-12T17:22:07.651Z)
OS version: Windows_NT x64 10.0.22621
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz (8 x 2803)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.68GB (0.71GB free)|
|Process Argv|--crash-reporter-id cca77810-2b69-4717-8e8a-757e4dfeafde|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (20)</summary>

Extension|Author (truncated)|Version
---|---|---
json|Mee|0.1.2
csharp|ms-|2.0.283
vscode-dotnet-runtime|ms-|1.6.0
cmake-tools|ms-|1.14.34
cpptools|ms-|1.16.3
cpptools-extension-pack|ms-|1.3.0
powershell|ms-|2023.6.0
vscode-print|pdc|0.11.15
java|red|1.20.0
vscode-yaml|red|1.14.0
code-spell-checker|str|2.20.5
code-spell-checker-canadian-english|str|1.0.3
cmake|twx|0.0.17
intellicode-api-usage-examples|Vis|0.2.7
vscodeintellicode|Vis|1.2.30
vscode-java-debug|vsc|0.52.0
vscode-java-dependency|vsc|0.23.0
vscode-java-pack|vsc|0.25.12
vscode-java-test|vsc|0.39.0
vscode-maven|vsc|0.41.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263:30335439
vscoreces:30445986
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
py29gd2263:30792226
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
3biah626:30602489
f6dab269:30613381
showlangstatbar:30737416
vsctsb:30748421
03d35959:30757346
pythonfmttext:30731395
pythoncmv:30756943
fixshowwlkth:30771522
showindicator:30785052
pythongtdpath:30769146
i26e3531:30792625
pythonnosmt12:30797651
pythonnoceb:30797650
e537b577:30795824
dsvsc013:30795093
dsvsc014:30797589

```

</details>

**Comment by mwherman2000** [comment]
Closing the folder in Code and reopening it causes my local files to be rescanned and the changed file is found. ...and only then can it be checked in.

**Comment by gjsjohnmurray** [comment]
Are these files on a local drive? Or on OneDrive or similar? Or a mapped drive letter?

Does the issue also occur after running the VS Code command to reload with all extensions temporarily disabled?

**Comment by mwherman2000** [comment]
1. Files are on my local C: drive (under `c:\Web7\...`)
2. What is the command option to "reload with all extensions temporarily disabled"?

**Comment by mwherman2000** [comment]
> Does the issue also occur after running the VS Code command to reload with all extensions temporarily disabled?

The issue goes away "after running the VS Code command to reload with all extensions temporarily disabled" because the local folder is "rescanned".  Using this command has the same effect as closing and reopening the folder: rescanning the local folder causes Code to detect the changed files.

**Comment by gjsjohnmurray** [comment]
But if you make changes after disabling extensions do those changes get detected?

**Comment by mwherman2000** [comment]
Yes! ...so it must be an extension? ...perhaps the most recently installed extension? How do I figure out which one? Uninstall them one at a time?

**Comment by gjsjohnmurray** [comment]
Use the `Start Extension Bisect ` command.

**Comment by mwherman2000** [comment]
Documentation: https://code.visualstudio.com/blogs/2021/02/16/extension-bisect

I think I'll simply disable one extension at a time.  Thank you

**Comment by mwherman2000** [comment]
Found the problem extension: It was a _pre-release_ version of a C# extension from Microsoft. Closing.  Thank you

**Comment by mwherman2000** [comment]
Found the problem extension: It was a pre-release version of a C# extension from Microsoft. Closing. Thank you
