### ISSUE TITLE
[WelcomeUX] Editor walkthrough errors pollute workspace problems view

### ISSUE THREAD

**Issue by mousetraps** [Microsoft/vscode#18897]
Testing #18091

![image](https://cloud.githubusercontent.com/assets/762848/22160748/e446f918-defb-11e6-90d6-d516dad0d7c3.png)

**Comment by rebornix** [comment]
Clicking the error will open a separate tab

![screen shot 2017-01-20 at 10 55 26 am](https://cloud.githubusercontent.com/assets/876920/22161388/f9474c98-defe-11e6-8059-ee6d8ee37eda.png)

**Comment by chrmarti** [comment]
@sandy081 I'm told we can filter problems from the view based on URI scheme (here: walkThroughSnippet:)? /cc @bpasero

**Comment by chrmarti** [comment]
We would also want to filter these from the statusbar stats.

**Comment by sandy081** [comment]
@chrmarti First of all welcome to the ever known issue :)

I do not think there is any filtering being in done in problems view, also we do not filter any documents we send to extension host. What ever documents we open, we send them across extension host. Extensions read them and generate markers. There is also no filtering in our markers management layer.

This was a tricky problem and filtering it in any layer is contradicted. In short, these can be filtered in
- Markers management 
- Ext host document management
- Extensions ignoring the unknown schemas or read only documents

When I had this issue in Default Settings, I fixed it by fixing Default Settings model/content to be valid.  

I am sorry that I am not very helpful here. 

@jrieken @dbaeumer FYI

**Comment by jrieken** [comment]
Yes, filtering a to be avoided. The errors seem to come from TypeScript since we are dealing with files on disk. You might get away with this by changing the scheme because TypeScript reacts to the `file`-scheme only. So, using a different scheme will make TypeScript not validate this and therefore no errors show...

**Comment by chrmarti** [comment]
We want the markers to show up in the embedded editors. Also, the scheme is already custom, we changed the TypeScript extension to handle that, the TypeScript service already supported custom schemes.

**Comment by jrieken** [comment]
Yeah, you want something we don't support. Also, note that markers show in the status bar and are passed around to code action providers.

**Comment by chrmarti** [comment]
Using same approach as for `Schemas.inMemory` for now.

**Comment by chrmarti** [comment]
Added second change. @kieferrm Could you verify the lint problems no longer show up in the next insiders build?
