### ISSUE TITLE
Markdown pasting occurs in code block that is not closed

### ISSUE THREAD

**Issue by MeghanKulkarni** [microsoft/vscode#188993]
<img width="402" alt="image" src="https://github.com/microsoft/vscode/assets/29208738/fe1ca341-ebe0-4065-bbdd-64411059ccb3">

<img width="414" alt="image" src="https://github.com/microsoft/vscode/assets/29208738/813e0c66-1d02-4f24-8201-7d5a3f8947c0">

**Comment by mjbvz** [comment]
This is likely ok since the code block will not actually be considered a code block until it is closed
