### ISSUE TITLE
Electron: backport node.js Linux spawn perf improvement fix

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#188912]
Refs: https://github.com/nodejs/node/pull/48523

Upstream: https://bugs.chromium.org/p/v8/issues/detail?id=7381#c10

**Comment by deepak1556** [comment]
Refs https://github.com/electron/electron/pull/39253

**Comment by deepak1556** [comment]
Upstream PR has been merged, this will be available with Electron 28

**Comment by bpasero** [comment]
I am fine to close this issue then.
