### ISSUE TITLE
Some command names are not shown in screencast mode

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#188938]
Found while verifying https://github.com/microsoft/vscode/issues/179541

https://github.com/microsoft/vscode/assets/10746682/7d0e2c47-e97b-4b16-8922-618c64c4e5c7

**Comment by joaomoreno** [comment]
Yeah this has always been the case. I think it's due to registerAction vs registerCommand. Very confusing. Let me see if I can find any way that I'm missing.

**Comment by ronakj** [comment]
@joaomoreno @sandy081 Take a look at this PR https://github.com/microsoft/vscode/pull/193033 fixing this. Let me know if you have feedback for how the issue is solved.

**Comment by joaomoreno** [comment]
**Verification:** Some commands are still not showing up since they register against the command registry without any description. This needs fixing at each command registration. But the fix makes sure certain commands start getting labels, like pressing <kbd>Cmd N</kbd> to create a new untitled file.

**Comment by jaktestowac** [comment]
@joaomoreno as you mentioned some shortcut like `Ctrl` + `.` or  `Ctrl` + `/` are still not visible - is there issue where that this shortcuts can be reported or progress regarding this fix tracked?

```
Version: 1.83.0-insider (user setup)
Commit: 109e1f8d8afb754ed31317f79937a44e98d5063b
Date: 2023-09-25T10:41:26.295Z
Electron: 25.8.2
ElectronBuildId: 23977753
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.22621
```
