### ISSUE TITLE
my code space takes a lot of time te connect so what can i do? the explorer takes a lot of time to start 

### ISSUE THREAD

**Issue by Abdelrahman284** [microsoft/vscode#188931]
ADD ISSUE DESCRIPTION HERE

Version: 1.80.1
Commit: 74f6148eb9ea00507ec113ec51c489d6ffb4b771
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36 Edg/115.0.1901.183
Embedder: codespaces

**Comment by chrmarti** [comment]
Please post your questions about GitHub Codespaces here: https://github.com/orgs/community/discussions/categories/codespaces. Thanks!
