### ISSUE TITLE
Use full line decorations for comment range

### ISSUE THREAD

**Issue by hediet** [microsoft/vscode#188901]
I think a full range decoration would look nicer here:

![chrome_JMi1ujG2v5](https://github.com/microsoft/vscode/assets/2931520/80ca2cd6-34ac-420f-9400-9c2c7f07eecd)

You can also use `shouldFillLineOnLineBreak`:

[Example](https://microsoft.github.io/monaco-editor/playground.html?source=v0.41.0-dev.20230719#XQAAAAJ3AgAAAAAAAABBqQkHQ5NjdMjwa-jY7SIQ9S7DNlzs5W-mwj0fe1ZCDRFc9ws9XQE0SJE1jc2VKxhaLFIw9vEWSxW3yscw1nNbLRiS2N9aGkduDPa_npiUhFZYzDsd-RvVGRY6r9dEzEL7CkVjXYfXEqCOPATLbFEW071fq2LLkY3j_GIwxB8diu32atWGIyNp79zpmSP1QyvMXFCv9xv-1Hw0nDakYpkRwC2mV9j5c9qMh28Vv3TwQVndbf9Kya_HJNzzfhPrCDCYKQ7HKkiBGhVY_1A1SBvtvwECV1zotJRAVUSIs0ala79yya4u3jtKcx0e_ZxLBM9x-ELPy3KqCzqoczYiJ_WQriOV--DHnzv0IEccFkyPfprWPM-jCoY3nHszMoRil1hm_Utj3ai_7oEad5T3nY2f6h_gUZsW2OlhrdIYxOtpd3ba63WFtkEvcffwXcsO6_E7QRE9D52iY0S1u0TtjTzmoc1kHav1lBWyT4iUs0tHJWbkgXF8vnBKXl2dZcXf3HfpKInKLcU7QdhUe9IdRkkbLvh9JULWWorFQGY-hEunl_79G-w)

**Comment by alexr00** [comment]
Last time I looked at this I didn't know about `shouldFillLineOnLineBreak`. With `shouldFillLineOnLineBreak`, I like this much more.

**Comment by hediet** [comment]
> shouldFillLineOnLineBreak

I added this last milestone!

**Comment by alexr00** [comment]
Is there any way to make the border only go around the outside of the selected area? Here's an example with the border as it currently is: [Example](https://microsoft.github.io/monaco-editor/playground.html?source=v0.41.0-dev.20230719#XQAAAAK0AgAAAAAAAABBqQkHQ5NjdMjwa-jY7SIQ9S7DNlzs5W-mwj0fe1ZCDRFc9ws9XQE0SJE1jc2VKxhaLFIw9vEWSxW3yscw1v1DLRiS2N9aGkduDPa_nphCLwTjKAmpfIQJUhRZ_qarljn44uHUpLnwpFNF9vNfG1Ntp_F0GcBzMJ1yXbVcHjlMfeIefPbGYivywbbnI4-8mj9ukD-yo9ZS8_PseIeZuy6M4jSt120UWqI_Sj2Lohwaog_FkBmZpuV-AxA2GDAE_090SXmZyoaJzEL7n6mKsHC4lQeTwpvmH7F4xmWuwYDfZ79d_fJFdJG8dZFPhDY7j9xCgHain6vViQg7W4gOr0LW8OjMj8PQkJtMTOWak3B1_gWLAbO1EcLFWDCvMHlcjZVwJ5g5xMnTVGyWncukOuc5IzSmI5HloQQ6ep3iGo1jmyhOWSXtK0dWQKvkTnVWHgnAV3Nb3T69ojCRwzg1FouE7_Ps_qiVcgy1aaI9UeUNZ2o-yhv_o5TWVznIBBPocYNBfWNVtymRl-W6Ldd5YaDjr1-cS-vD7CklE0J0O7F-SWY8nGDotxg3CcWpmCyypOdKqLSlvnTcO_uYfmrK_8Jq52Y)

**Comment by hediet** [comment]
Unfortunately not, and it would be very complex to do that. I would just not use a border.
