### ISSUE TITLE
Goto definition acts too early in some cases

### ISSUE THREAD

**Issue by maritz** [Microsoft/vscode#189]
When pressing the mouse button down then holding control and then releasing the mouse button, VS Code jumps to the definition. This should only happen if you are holding down CTRL before the mouse down.

One of the problems this causes: When selecting text and copying/cutting/pasting it via CTRL+X/C/V you have to be sure to let go of the mouse button before you press CTRL.

Another issue with CTRL is that when navigating through recent files with CTRL+TAB and you go backwards in the list via CTRL+SHIFT+TAB, but then decide you actually didn't need to go backwards: You release SHIFT and get immediately thrown into the currently selected file. I think this should only happen when letting go of CTRL in that case.

In my opinion the Jump To Definition probably shouldn't happen regardless of modifier keys pressed when you have a text selection created with that mouse action.

(this was reported in https://code.visualstudio.com/issues/detail/18527, but I guess github issues are the way forward, right?!)

**Comment by gclifford** [comment]
Please do this. It gets really annoying when you are selecting text to copy and then it takes you to definition. Currently this is my biggest beef with vscode.

Is there away to turn this off. I have searched the setting files and cannot find a setting that would match the click to definition behavior.

**Comment by bpasero** [comment]
The quick open situation will be fixed for the next release.

I am having a hard time finding a solution for the "Go to definition" problem though. I could disable the entire feature as soon as text is selected but that will likely frustrate other users.

If you are curious how this is implemented, check it out in https://github.com/Microsoft/vscode/blob/master/src/vs/editor/contrib/goToDeclaration/browser/goToDeclaration.ts#L226

**Comment by maritz** [comment]
Hm, I kinda doubt there are many people that start a text selection, then press ctrl+mouseup to go to the definition. But of course I have 0 evidence for this.

So how could we resolve this? I suppose making this a setting is a bit overkill and bloats the settings.
The same goes for completely turning off "Go to definition" on CTRL+Click.

I don't have many other editors to test this with, but WebStorm for example does not do this jump. Instead it just ends the selection, as I would expect.

**Comment by bpasero** [comment]
Well what about people that double click to select a word and then want to Ctrl+click to goto definition? I don't think text selection is limited to just copy/paste.

Unfortunately at the time the mouse button is released, i don't really know if you have pressed another key (V or C).

**Comment by maritz** [comment]
> Well what about people that double click to select a word and then want to Ctrl+click to goto definition?

Translates to

    mousedown > mouseup > mousedown > mouseup > ctrl down > mousedown > mouseup

That's perfectly fine and should always go to definition.

What I'm referring to is for example this sequence: 

    mousedown > mousemove > ctrl down > mouseup

Notice that I haven't completed the text selection before I press ctrl down. This immediately causes a "go to definition" on mouseup when in my opinion it should not.

My issue with copy/pasting for example was just how I regularly run into this issue. In practice any action performed after the mouseup will be executed in the definition instead of where you had your text selection.

Of course it works fine if you do it the normal way:

    mousedown > mousemove > mouseup > ctrl down > whatever action you want

But since copy/pasting for example is often a very quick action, I often fail it.

**Comment by RGBKnights** [comment]
I have to add my weight to this ticket as well. When copy and pasting code I often end up at the definition and replace completely the wrong things. (Often in framework files) This is extremely annoying.

**Comment by bpasero** [comment]
Ok I think I found an elegant fix, thanks to the comments! Now, when you press and hold the mouse button without pressing Ctrl/Cmd, releasing the mouse button will not trigger the navigation even when Ctrl/Cmd are still pressed.

In other words, goto definition with mouse will only work if you first press Ctrl/Cmd and then mouse down. We will do some selfhosting on the change to see if it is causing regressions, but I think its fine.

**Comment by maritz** [comment]
Perfect! :+1:

**Comment by maritz** [comment]
@bpasero Works as you described. :)

**Comment by gclifford** [comment]
Yes it does :smile:

**Comment by RandScullard** [comment]
I just noticed that "Ctrl + click to follow link" on a URL still uses the old behavior, so the behavior is now inconsistent between Go to Definition and URLs.

**Comment by alexandrudima** [comment]
@RandScullard Please create a new issue so we can track it.

**Comment by jbeaudoin11** [comment]
I don't know why but the fix doesn't work for me... I posted a on stackoverflow my issue and i'm searching to disable this feature for at least 1 yeah or so...

http://stackoverflow.com/questions/37683703/how-to-disable-ctrl-click-in-vs-code

Just found this issue and i don't know why it's not working for me !
This is pretty annoying :/ !

**Comment by alexdima** [comment]
ctrl+click does not select a word in VS Code. Currently, only double click does word selection. #3130 tracks that mouse bindings can be customized.
