### ISSUE TITLE
vscode.dev/theme preview notification buttons actions reversed

### ISSUE THREAD

**Issue by gregvanl** [microsoft/vscode#189016]
- VS Code Version: 1.80 stable
- OS Version: Edge, Chrome browser

Steps to Reproduce:

1. Go to the 1.80 release notes in-product or at https://code.visualstudio.com/updates/v1_80#_terminal-output-support and click the "preview on vscode.dev" link to preview a theme such as https://vscode.dev/theme/connor4312.codesong
2. Once vscode.dev launches in the browser, a notification appears with the options to "Keep" or "Don't Keep"

![image](https://github.com/microsoft/vscode/assets/12818376/98cdefc6-9fc1-4c25-88cb-73e2dc6eda6c)

3. Selecting "Keep" restarts vscode.dev and loses the preview theme
4. Selecting "Don't Keep" dismisses the notification and leaves the preview theme.

The buttons appears to be reversed unless I am misunderstanding the "Keep" and "Don't Keep" actions.

**Comment by aeschli** [comment]
This seems to work for me.

When the page is showing, we preview the new theme, but do not install the theme nor modify the `workbench.colorTheme` setting.
On `Keep`, the extension is installed and the setting applied. In the end there's a window reload. As the settings has been updated, the new theme should now be shown
On 'Don't Keep` we just show the old theme again (no settings changed)

@gregvanl Can you open the settings and see what happens with the setting? Maybe applying the setting doesn't work?

Also, I think the reload is confusing. I'm working on a PR to remove the reload and to replace it with a notification
'The theme is now installed and configured in the user settings.'

**Comment by aeschli** [comment]
This seems to work for me.

When the page is showing, we preview the new theme, but do not install the theme nor modify the `workbench.colorTheme` setting.
On `Keep`, the extension is installed and the setting applied. In the end there's a window reload. As the settings has been updated, the new theme should now be shown
On `Don't Keep` we just show the old theme again (no settings changed)

@gregvanl Can you open the settings and see what happens with the setting? Maybe applying the setting doesn't work?

Also, I don't know if the reload is a good idea. I'm working on a PR to remove the reload and to replace it with a notification
'The theme is now installed and configured in the user settings.'

**Comment by aeschli** [comment]
closing. 
https://github.com/microsoft/vscode-theme-tester/pull/18 implements the wording changes
