### ISSUE TITLE
Clicking "ignore" when using the merge editor makes the editor freeze/hang

### ISSUE THREAD

**Issue by pocesar** [microsoft/vscode#189096]
Does this issue occur when all extensions are disabled?: Yes/No

- Version: 1.81.0-insider (user setup)
- Commit: 268f34992c5d826a08e4b72013f95af9683044ea
- Date: 2023-07-27T08:12:55.311Z
- Electron: 22.3.17
- ElectronBuildId: 22432899
- Chromium: 108.0.5359.215
- Node.js: 16.17.1
- V8: 10.8.168.25-electron.0
- OS: Windows_NT x64 10.0.22621

Steps to Reproduce:

1. Diff a file
2. Open the merge editor
3. Click "ignore"

**Comment by hediet** [comment]
Verification steps:
* Use `Open Merge Editor State From JSON`

JSON:
```
{
    "languageId": "markdown",
    "base": "# DEVELOPMENT\n\nThis is the readme for the development branch\n\n## Heading 1\n- some issue\n- another issue",
    "input1": "# DEVELOPMENT\n\nThis is the readme for the development branch\n\n## Heading 1\n- some issue\n- another issue\nfee\n",
    "input2": "# DEVELOPMENT\n\nThis is the readme for the development branch\n\n## Heading 1\n- some issue\n- another issue\nfoo\n",
    "result": "# DEVELOPMENT\n\nThis is the readme for the development branch\n\n## Heading 1\n- some issue\n- another issue\n",
    "initialResult": "# DEVELOPMENT\n\nThis is the readme for the development branch\n\n## Heading 1\n- some issue\n- another issue\n"
}
```

Click on "Ignore".
Notice VS Code does not freeze.

**Comment by andreamah** [comment]
unsure why this is marked as `unreleased`, since the latest commit for insiders is 9800cf6dd6bf4634889d60720ef46a400f3a7298. I'll manually remove the unreleased tag.

**Comment by hediet** [comment]
Sorry, I pasted the wrong JSON. I updated the JSON and verified that it works, but it would be nice to have an independent verification.
