### ISSUE TITLE
[WelcomeUX] Why is the editor walkthrough background color fixed?

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#18905]
Testing #18091

On the red theme is should be a red background:

![image](https://cloud.githubusercontent.com/assets/2193314/22161091/afcbbf78-defd-11e6-9498-5b962fbf0937.png)

This could make the text look awkward/inconsistent on some themes (which could easily be set on welcome page before going to walkthrough).

**Comment by Tyriar** [comment]
On a related note, shouldn't the preview be the regular workbench color so that proper contrast and colors can be ensured? The same applies to the welcome page:

![image](https://cloud.githubusercontent.com/assets/2193314/22161184/246fe520-defe-11e6-873f-df4408e39ffb.png)

The blue links may also clash with the theme background.

**Comment by chrmarti** [comment]
Using CSS for the embedded editor's background. That limits us to one color per base theme. We could instead compute one from the theme's background color.
