### ISSUE TITLE
[WelcomeUX] Emmet cheat sheet URL is wrong

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#18900]
Testing #18091

http://http//docs.emmet.io/cheat-sheet/ is giving me:

> This site can’t be reached
>
> http’s server DNS address could not be found.

**Comment by seanmcbreen** [comment]
doh fixed

**Comment by ramya-rao-a** [comment]
![image](https://cloud.githubusercontent.com/assets/16890566/22306824/917548cc-e2f5-11e6-8379-134f86c99fbb.png)

@seanmcbreen Why is a pair of [] around settings? :)

**Comment by ramya-rao-a** [comment]
@chrmarti Does "setting" have to be a link here?

**Comment by chrmarti** [comment]
I think that was @seanmcbreen 's intention. Haven't checked with him though.
