### ISSUE TITLE
`Run Build Task...` menu with only one item has no configure button

### ISSUE THREAD

**Issue by adam-fowler** [microsoft/vscode#189055]
Does this issue occur when all extensions are disabled?: No, you need an extension that generates build tasks to see this.

- VS Code Version: 1.81.0-insider
- OS Version: macOS 13.4.1

To replicate this you need an extension that generates build tasks. You also need a situation where it will only produce one task. The reproduction steps below use the `sswg.swift-lang` extension

Steps to Reproduce:

1. Ensure you have swift installed
2. Make a new folder and enter it
3. Run `swift package init`
4. Run `code .`
5. Wait for extension to load package (Loading package message in bottom bar will disappear)
6. Press `Cmd+Shift+B` to bring up `Run Build Task...` menu
7. It should only have one entry and it will have no configure button

**Comment by meganrogge** [comment]
we now automatically run the task if there's just one
