### ISSUE TITLE
[WelcomeUX] Not sure what I did but CSS color swatches disappeared

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#18904]
Testing #18091

![image](https://cloud.githubusercontent.com/assets/2193314/22161063/8195a740-defd-11e6-8930-0da377554320.png)

**Comment by chrmarti** [comment]
You broke it.

**Comment by chrmarti** [comment]
This appears to be the only report. Assuming fixed or very rare. Closing.
