### ISSUE TITLE
[WelcomeUX] Scrollbar is not a good thing for playaround sometimes

### ISSUE THREAD

**Issue by rebornix** [Microsoft/vscode#18907]
Testing #18091

Take snippet as example

![screen shot 2017-01-20 at 10 49 42 am](https://cloud.githubusercontent.com/assets/876920/22161222/4e63b53c-defe-11e6-8854-8385a18a5627.png)

Before users type `try`, we can see five lines with an ending line `end`. After users insert the snippet

![screen shot 2017-01-20 at 10 49 52 am](https://cloud.githubusercontent.com/assets/876920/22161248/645a54e0-defe-11e6-9c7f-c8f036190e3c.png)

The ending line `end` is missing, which makes it somehow useless. Scrollbar is the catch.

**Comment by chrmarti** [comment]
Fixed with #18899
