### ISSUE TITLE
is it possible to transfer vscode extension publisher account?

### ISSUE THREAD

**Issue by zqfan** [microsoft/vscode#189029]
The publisher registered a few years ago with a personal account, https://marketplace.visualstudio.com/publishers/TencentCloud
Now the employee has left for years and I am now maintaining the https://github.com/tencentcloud , I don't want to creat a new publisher, so if it is posible to transfer it to my account?
Thanks a lot.

**Comment by isidorn** [comment]
Please send an email to vsmarketplace@microsoft.com And the marketplace team will try to help.
Thank you
