### ISSUE TITLE
[WelcomeUX]  Go To Definition opens a new tab

### ISSUE THREAD

**Issue by rebornix** [Microsoft/vscode#18906]
Testing #18091

![screen shot 2017-01-20 at 10 48 23 am](https://cloud.githubusercontent.com/assets/876920/22161145/fe709054-defd-11e6-96c9-81d8055a0618.png)

While we don't have issues with other intellisense action like Rename or Find references.

**Comment by mjbvz** [comment]
Fixed via 5b25934bace96443d24687344aee96ae0432f348

**Comment by ramya-rao-a** [comment]
@mjbvz I am guessing the fix was to disable Go to Definition?

**Comment by mjbvz** [comment]
Yes, we disabled those commands in the embedded editor context. Not perfect, but it unblocked the welcome experience

**Comment by ramya-rao-a** [comment]
@mjbvz Got it. Thanks!
