### ISSUE TITLE
Unknown property `text-wrap: balance`

### ISSUE THREAD

**Issue by mrleblanc101** [microsoft/vscode#189086]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.80.1
- OS Version: macOS 13.4.1

Steps to Reproduce:

1. Create a sass/scss file
2. Create a selector
3. Add the `text-wrap: balance` property

<img width="1392" alt="Capture d’écran, le 2023-07-27 à 14 29 52" src="https://github.com/microsoft/vscode/assets/17392251/e8d5e1eb-072c-46a2-9250-066c6fab3c94">

<img width="559" alt="Capture d’écran, le 2023-07-27 à 14 26 36" src="https://github.com/microsoft/vscode/assets/17392251/179fb22f-6cd0-4774-add2-fde024617e6a">

**Comment by aeschli** [comment]
`text-wrap` is an experimental property: https://developer.mozilla.org/en-US/docs/Web/CSS/text-wrap
We will support it when it is added to the spec.

In the meantime you can allow it by adding it to setting `css.lint.validProperties`

**Comment by mrleblanc101** [comment]
Text-wrap balance is part of Text Module lvl 4 and already shipped by some browser.
