### ISSUE TITLE
Intermittent Unresponsiveness during Large Build Tasks with High CPU Usage

### ISSUE THREAD

**Issue by awmorgan** [microsoft/vscode#189065]
Does this issue occur when all extensions are disabled?: Yes/No
The issue is intermittent. I did try disabling the extensions for a short while and did not see the issue, but that does not prove that the issue is related to an extension because most of the time the issue does not occur even with extensions enabled.

Version: 1.80.1 (user setup)
Commit: 74f6148eb9ea00507ec113ec51c489d6ffb4b771
Date: 2023-07-12T17:22:07.651Z
Electron: 22.3.14
ElectronBuildId: 21893604
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Windows_NT x64 10.0.19045

Steps to Reproduce:
Have a large build task that compiles many files and then as the output scrolls to the terminal sometimes the UI will become unresponsive. This is intermittent. 
When it happens I've noticed that the code.exe is consuming about 2.8% CPU constantly.
It seems to be stuck in cppgc::internal::WriteBarrier::DijkstraMarkingBarrierRangeSlow as shown in this screenshot which is a capture from process explorer with a stack trace. 
The only method of recovery is killing the code.exe process.
![image](https://github.com/microsoft/vscode/assets/1335269/1c7a2717-56d3-4621-91af-858dd5ffaba5)

**Comment by meganrogge** [comment]
what's your terminal scrollback set to?

**Comment by awmorgan** [comment]
![image](https://github.com/microsoft/vscode/assets/1335269/0722e8ea-96b0-439d-bd05-dd2fe37b2117)

**Comment by meganrogge** [comment]
this is expected given the large scroll-back that you have set - since that consumes memory. decrease this value and you should see the perf improve

**Comment by awmorgan** [comment]
Decrease to what? Pretty the system had plenty of memory available.

**Comment by awmorgan** [comment]
@meganrogge I reduced my scroll back to 1000 but that did not fix the issue. It happened again today:
[Window Title]
Visual Studio Code

[Main Instruction]
The window is not responding

[Content]
You can reopen or close the window or keep waiting.

[ ] Don't restore editors  [Reopen] [Close] [Keep Waiting]
![image](https://github.com/microsoft/vscode/assets/1335269/34c9f347-899b-4bc8-943f-a4ee9d4d0adf)
![image](https://github.com/microsoft/vscode/assets/1335269/7956be41-7275-4029-bbbd-f1f0bebe6109)

**Comment by awmorgan** [comment]
fyi: this issue still exists in this version

Version: 1.81.0 (user setup)
Commit: 6445d93c81ebe42c4cbd7a60712e0b17d9463e97
Date: 2023-08-02T12:37:13.485Z
Electron: 22.3.18
ElectronBuildId: 22689846
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Windows_NT x64 10.0.19045

**Comment by meganrogge** [comment]
I believe this is already fixed, can you see if you can reproduce in the [Insiders build](https://code.visualstudio.com/insiders)?
/label info-needed

**Comment by awmorgan** [comment]
> I believe this is already fixed, can you see if you can reproduce in the [Insiders build](https://code.visualstudio.com/insiders)? /label info-needed

Thanks!

I have been testing today and haven't been able to reproduce it yet but since it was intermittent I won't know for sure. I'll keep testing and let you know. 

What was the fix? 

testing with this version:
Version: 1.85.0-insider (user setup)
Commit: af28b32d7e553898b2a91af498b1fb666fdebe0c
Date: 2023-12-06T11:15:22.766Z
Electron: 25.9.7
ElectronBuildId: 25551756
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.19045

**Comment by awmorgan** [comment]
> Alot of improvements have been made to tasks since you created this issue

Are these improvements included in 1.85.0 or only in Insiders?
