### ISSUE TITLE
New feature request: Show live preview of a markdown cell's output while editing it in VS Code Jupyter Notebooks

### ISSUE THREAD

**Issue by VachanVY** [microsoft/vscode#189082]
# Markdown Cells in Google Colab 
* Shows the output of markdown cells while editing itself

* [![enter image description here][1]][1]

# Markdown Cells in VS Code 
* Does'nt show the output of markdown while editing markdown but colab shows it while editing as shown above

* [![enter image description here][2]][2]

I want a feature like this in VS Code like in colab.

  [1]: https://i.stack.imgur.com/rnOAJ.png
  [2]: https://i.stack.imgur.com/njRyq.png

**Comment by VachanVY** [comment]
@mjbvz When will this feature be implemented to vscode any idea?

**Comment by mjbvz** [comment]
Closing as this feature request hasn't gotten enough upvotes since it was opened
