### ISSUE TITLE
can't update to latest version

### ISSUE THREAD

**Issue by projectAI21** [microsoft/vscode#189038]
I could not update to the latest version which is 17.6.5, because I have no check for the update option. could you give me a solution as soon as possible?

**Comment by joaomoreno** [comment]
Are you running as Admin? If so, run it as the normal user to enable the update notifications.

**Comment by IlanZ93** [comment]
If needed just run again the installer it will update your VSCode : http://go.microsoft.com/fwlink/?LinkID=534107
