### ISSUE TITLE
💥Settings sync cannot be turned on[urgency]

### ISSUE THREAD

**Issue by heartacker** [microsoft/vscode#189010]
Settings sync cannot be turned on because the current version (1.80.1, 74f6148eb9ea00507ec113ec51c489d6ffb4b771) is not compatible with the sync service. Please update before turning on sync.

**Comment by sandy081** [comment]
Wondering if you are syncing with the insiders data?

**Comment by heartacker** [comment]
> Wondering if you are syncing with the insiders data?

yes  I use stable and insider both
