### ISSUE TITLE
Settings Sync was automatically permanently disabled

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#189032]
As I verified https://github.com/microsoft/vscode/issues/188275, I noticed my Settings Sync was turned off. I'm pretty sure I didn't manually turn it off. Is there any chance that situation can get me into a permanently turned off state, even if the notification says it should be temporarily only?

**Comment by sandy081** [comment]
These are the scenarios we turn off settings sync automatically:

- Client session is invalid. This can happen if the end point to which that client points to has changed or settings sync was turned off from another machine and opted to turn off completely in all other devices.
- Too many requests to the server - If server detects client is making too many requests (rate limit exceeded on server)
- If client is incompatible - server has data with newer version and client is still dealing with older data version
- If client is making unsupported requests

Client logs this information in the settings sync log when it happens. Is it possible to find the log where the setting sync is turned off on your machine?

**Comment by sandy081** [comment]
Unfortunately I didn't find the logs causing this on the client. Closing this for now and when we see this next time, lets try to get the logs immediately.
