### ISSUE TITLE
Implement directional window splitting

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#1890]
While VSCode allows splitting of windows to the left using <kbd>ctrl</kbd>+<kbd>\\</kbd>, Atom allows splitting in 4 directions with the shortcut <kbd>ctrl</kbd>+<kbd>k</kbd>, <kbd>&lt;arrow&gt;</kbd>. The main advantage this has over the current `workbench.action.splitEditor` command is that it enables splitting the editor to allow both horizontal and vertical layouts.

Note: VSCode currently uses <kbd>ctrl</kbd>+<kbd>k</kbd>, <kbd>up</kbd> and <kbd>ctrl</kbd>+<kbd>k</kbd>, <kbd>down</kbd> for opening the previous and next working file.

**Comment by AndrewNatoli** [comment]
I agree horizontal splitting would be awesome :D

**Comment by joaomoreno** [comment]
@stevencl @bgashler1 @bpasero not sure if there's a dupe for this already

**Comment by bpasero** [comment]
#1749
