### ISSUE TITLE
Extension API to show all Walkthroughs contributed by extension

### ISSUE THREAD

**Issue by glouischandra** [microsoft/vscode#189005]
Hi, 

VSCode provides a command to open a specific walkthrough contributed by an extension such as workbench.action.openWalkthrough(fullyQualifiedWalkthroughID: string, toSide?: boolean)

Is there a command to show all Walkthroughs contributed by an extension?

Thanks!

**Comment by gjsjohnmurray** [comment]
I suggest you use `vscode.extensions.getExtension(extensionId).packageJSON?.contributes?.walkthroughs`

**Comment by glouischandra** [comment]
Thanks @gjsjohnmurray I was hoping there's an API that can show the filtered list of walkthrough in a quickpick. But it seems that the capability doesn't exist yet?

We can use that command to build our own quickpick then. Thanks!
