### ISSUE TITLE
[WelcomeUX] Go-to-definition opens file in separate tab rather than navigating within embedded editor

### ISSUE THREAD

**Issue by mousetraps** [Microsoft/vscode#18909]
Testing #18091

Press F12 in sandbox
![image](https://cloud.githubusercontent.com/assets/762848/22161276/78aadd70-defe-11e6-9579-d4ecb5b105ba.png)

Get navigated to separate read-only page:
![image](https://cloud.githubusercontent.com/assets/762848/22161205/37a0f6ac-defe-11e6-9b9c-378dc5c62046.png)

Also loses your place within the Walkthrough

**Comment by chrmarti** [comment]
Tracked with #18906
