### ISSUE TITLE
Do not render < 1/1 > in Ghost Text hover when there is only one suggestion

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#189057]
Where there is only one ghost text suggestion there is no need to render the < 1/1 > part.
Could we not render it in this case? Or you only find out async, and you think it might cause too much flicker?

![Screenshot 2023-07-27 at 16 33 57](https://github.com/microsoft/vscode/assets/1926584/fa40b8a4-8f67-4c78-92ea-40f46ef46035)

**Comment by hediet** [comment]
> Or you only find out async, and you think it might cause too much flicker?

If you want to remove the first 3 UI elements if there is only one suggestion, then there might be significant flicker.

If you only want to hide the label, there might be a lot of empty space.

**Comment by isidorn** [comment]
I think only this option makes sense:
> Unless we show the hover only after the provider sent us all the results, but then it might take a while until the hover shows.

The hover already shows with a hover delay. If it needs an additional delay it might not be noticeable. Can we configure how fast the hover is triggered for ghost text, if yes we could decrease this time and with the delay we introduce the experience might be the same.

**Comment by hediet** [comment]
> if yes we could decrease this time

This would increase the number of accidental hovers though! (And thus increasing the number of requesting all suggestions)

**Comment by isidorn** [comment]
Good idea. 
Is it worth it - not sure. I think the other issue I filed is more important as it is clearly a bug https://github.com/microsoft/vscode/issues/189058

I leave this one up to you to decide. Feel free to close as designed.

**Comment by hediet** [comment]
> If the providers answer in that time, I don't show the label if there is only one suggestion. Otherwise, I show the label.

Thinking about it, this could be perceived as buggy (if it only sometimes shows).

> Feel free to close as designed.

🫡
