### ISSUE TITLE
VS code doesn't gray out unused variables

### ISSUE THREAD

**Issue by Fouadbkh** [microsoft/vscode#189056]
VS code doesn't gray out unused variables in javascript for exaple of i write :

let name = "Y"

the name it comes white not grey and if i put it in console.log(name) it stays the same thing white

**Comment by mjbvz** [comment]
This is by design. If the variable is the global scope in a non-module file, it can be used by other files. We don't track unused variables across files like this so instead always show this type of variable as being used
