### ISSUE TITLE
[WelcomeUX] Add empty spaces in editors for ppl to play around in Walk-Through

### ISSUE THREAD

**Issue by rebornix** [Microsoft/vscode#18901]
Testing #18091 

![screen shot 2017-01-20 at 10 37 47 am](https://cloud.githubusercontent.com/assets/876920/22160876/8179687e-defc-11e6-8e78-138ba552ac71.png)

If ppl want to play with this feature, he/she has to move the cursor to the end of the third line, press enter and then type. A better way is add an empty line at the end of the editor and put cursor there, then ppl can directly type and play.

![screen shot 2017-01-20 at 10 40 57 am](https://cloud.githubusercontent.com/assets/876920/22160964/f51152ce-defc-11e6-8631-a23052338432.png)

**Comment by chrmarti** [comment]
Related: #18899
