### ISSUE TITLE
Navigate accessible buffer doesn't give feedback when there are no commands to navigate

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#189050]
Repro:

1. Run some commands in a terminal
2. Reload (which will remove all shell integration decorations atm)
3. Shift+tab in terminal
4. ctrl+shift+g, 🐛 nothing happens

Maybe a notification should show saying there are no commands found to navigate between?

**Comment by meganrogge** [comment]
I feel like notifications are noisy. If we're thinking about screen reader users here being disoriented with the no-op, we could use `alert` instead?

**Comment by meganrogge** [comment]
Sometimes for no-ops like this, we show the quick pick with only one item or placeholder - maybe we could do that instead?

**Comment by Tyriar** [comment]
That would just mean more work as the user needs to exit with enter or escape?

**Comment by meganrogge** [comment]
I haven't heard feedback about this from screen reader users. I think we can close this.
