### ISSUE TITLE
[WelcomeUX] Walkthrough gives bad keybinding advice on some platforms

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#18902]
Testing #18091

In Ubuntu/Unity, ctrl+shift+alt+up/down moves the foreground application to another desktop. We need to be more platform aware as several keybindings don't work on Linux.

![image](https://cloud.githubusercontent.com/assets/2193314/22160913/bd23fd62-defc-11e6-98e5-7d5d9a158b3c.png)

**Comment by Tyriar** [comment]
Alt+click is another big one https://github.com/Microsoft/vscode/issues/3091

**Comment by chrmarti** [comment]
The walk(-)through just shows the existing keybinding. I suggest to fix this with #3091 and related issues. @seanmcbreen fyi

**Comment by Tyriar** [comment]
There has been no movement on these issues for 11 months though, not the best thing to highlight bugs (that likely won't be fixed anytime soon) as part of the welcome experience.

**Comment by Tyriar** [comment]
Reopening as this leads to a terrible introductory experience on Linux. Omitting certain sections on Linux would be a fine workaround. Another potential fix: adding a "?" icon next to the troublesome keybindings/mouse shortcuts with `title` attributes explaining when on the problem platform(s) when moused over.

**Comment by chrmarti** [comment]
@Tyriar Is there a keybinding we could use on Linux for copying lines that doesn't have conflicts with OS shortcuts? What do you use?

**Comment by Tyriar** [comment]
I don't rebind/use it because I have no room on my keyboard :stuck_out_tongue:

**Comment by chrmarti** [comment]
On Windows and Mac copyLinesUp/DownAction are bound to `Shift+Alt+Up/Down`. On Linux these are taken by insertCursorAbove/Below, which on Windows and Mac are bound to `Ctrl+Alt+Up/Down`. On Linux these are taken by Unity for switching between workspaces/desktops.

On Linux insertCursorAbove/Below have secondary bindings `Ctrl+Shift+Up/Down`. Maybe we should only use these for insertCursorAbove/Below and let copyLinesUp/DownAction also have `Shift+Alt+Up/Down` on Linux. Thoughts? @Tyriar

**Comment by chrmarti** [comment]
Fun fact: `Ctrl+Shift+Up/Down` is bound to cursorUp/DownSelect on Windows (same as `Shift+Up/Down`) and taken by the OS on Mac. (Which makes it a good escape on Linux, I think.) /fyi @waderyan

**Comment by Tyriar** [comment]
We should probably look into the commit history for those keybindings to see if they document why the decision was made. We need to be weary of changing keybindings like this at this point as it's bound to annoy a bunch of people.

@alexandrudima do you know/recall why `editor.action.insertCursorAbove` defaults to ctrl+shift+arrow *and* shift+alt+arrow on Linux?

**Comment by chrmarti** [comment]
Trying to think of our options:
1. Don't let insertCursorAbove/Below have the keybindings that copyLinesUp/DownAction has on other OSes and annoy a bunch of people with changed keybindings.
2. Keep existing keybindings, add a additional keybindings (without conflicts!) for copyLinesUp/DownAction on Linux and annoy ourselves with increasingly unmaintainable defaults.
3. Keep things as they are and keep annoying a bunch of people.

Also: Currently, moving an app to a different workspace/desktop simultaneously triggers copyLinesUp/DownAction in VSCode, so 2. and 3. are really not solving anything unless we find a way around this.

**Comment by alexandrudima** [comment]
I am open to any help I can get to find good keybindings on Linux. I think we should target Ubuntu. There is no reason keybindings are assigned the current way except for me trying (and failing) to find free modifiers + arrow keys combinations. Please @chrmarti @Tyriar PR welcome for #509

**Comment by chrmarti** [comment]
Changed the 'copy line above/below' hint to 'copy entire line' on Linux. 🤷
