### ISSUE TITLE
[WelcomeUX] Editor walkthrough problems persist even when it's closed

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#18913]
Testing #18091

I don't have the walkthrough tab open anymore but still have entries in problems view:

![image](https://cloud.githubusercontent.com/assets/2193314/22161472/4dff6c5c-deff-11e6-8968-e60651f87568.png)

Clicking these open the backing file.

**Comment by chrmarti** [comment]
Let me know if you have any steps to reproduce.

**Comment by Tyriar** [comment]
Yes having trouble reproducing now. Clicking on the problems is still an issue though as that will open the readonly files in new editors

**Comment by chrmarti** [comment]
I agree it might be best to not show them for now. Having them not disappear might indicate a leak though.

**Comment by chrmarti** [comment]
We don't show these problems in the problems view anymore.
