### ISSUE TITLE
[WelcomeUX] Console error while opening any of the recent folders

### ISSUE THREAD

**Issue by ramya-rao-a** [Microsoft/vscode#18917]
Testing #18091 on OS X El Capitan

<img width="528" alt="screen shot 2017-01-20 at 11 06 41 am" src="https://cloud.githubusercontent.com/assets/16890566/22161739/903d84c2-df00-11e6-9fa5-c970c0181a01.png">

**Comment by gregvanl** [comment]
Appears to happen when you try to open the already opened folder.

**Comment by chrmarti** [comment]
Tracked with #18856
