### ISSUE TITLE
Add compare editor keyboard shortcut to merge (revert) change

### ISSUE THREAD

**Issue by hb20007** [microsoft/vscode#189127]
It seems that we have the following keyboard shortcuts defined for the compare editor:
![screenshot 1](https://github.com/microsoft/vscode/assets/8860322/0e779069-871e-462f-be56-ab214eba1843)

I can cycle through the changes with my keyboard using `workbench.action.compareEditor.nextChange` and `workbench.action.compareEditor.previousChange`. However, it seems that there is no way to revert or merge the change which I am on using the keyboard.

If I hover on the arrow button using the mouse, again there is no keyboard shortcut suggested in the tooltip:
![screenshot 2](https://github.com/microsoft/vscode/assets/8860322/0a42603c-b847-47cb-a18a-73ae81a1f954)

**PS**: In case a "left arrow" is introduced in the future, to merge changes in the opposite direction, a keyboard shortcut would be great to have there as well.

**Comment by raunakkumarsingh** [comment]
assign it to me. I can resolve it.
