### ISSUE TITLE
workbench.action.focusRightEditor splits the view when 2 views are open

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#1891]
**Steps to reproduce**

1. Open a file
2. Split the editor <kbd>ctrl</kbd>+<kbd>\\</kbd>
3. Command palette <kbd>ctrl</kbd>+<kbd>shift</kbd>+<kbd>p</kbd>
4. Type `"focus right"`
5. <kbd>enter</kbd>

**Expected**

The second text editor on the right is focused.

**Actual**

A third text editor is split (from the second text editor) and focused.

**Notes**

- `workbench.action.focusRightEditor` does nothing when there is only a single editor.
- `workbench.action.focusRightEditor` appears to function correctly when there are 3 text editors, just not 2.

**Comment by bpasero** [comment]
This action is the thing that runs on Cmd+3 (Ctrl+3) and is used to bring up a third editor or focus it if 2 are open. This works as designed.

**Comment by Tyriar** [comment]
@bpasero focus**Third**Editor is the one that is bound to <kbd>ctrl</kbd>+<kbd>3</kbd>, it does seem to act exactly the same as focus**Right**Editor though.

Given that <kbd>ctrl</kbd>+<kbd>3</kbd> already acts like this, this keybinding doesn't seem to provide much utility at all? A user could use <kbd>ctrl</kbd>+<kbd>1</kbd>/<kbd>2</kbd>/<kbd>3</kbd> to focus all 3 editors or <kbd>ctrl</kbd>+<kbd>shift</kbd>+<kbd>alt</kbd>+<kbd>left</kbd> or <kbd>right</kbd> to only focus the left most or right most?

**Comment by bpasero** [comment]
@Tyriar sorry I confused the actions, "Focus into Next Editor on the Right" is distinct from Cmd+3. For me it works like this:
* 0 editor open: opens a first editor
* 1 editor open: opens a second editor and focus it
* 2 editor open: opens a third editor and focus it
* 3 editors open: nothing

What puzzles me is why no editor opens for you when 1 is open?

Btw in your example the second editor already has focus when you call the split action. That is why a third editor opens. If you give focus to the first editor and then invoke the action, it works as expected.

**Comment by Tyriar** [comment]
@bpasero It appears I got a little confused too, I just looked again and I think I was indeed running `focusThirdEditor` because I was running it through the command palette. While this issue seems fine now, my confusion was due to 2 problems:

- `focusRightEditor` conflicts with Ubuntu's default OS hotkeys, this is captured in https://github.com/Microsoft/vscode/issues/509
- I was using the command palette with the search string "focus right" which was only matching "Focus into Right Hand Editor", even if I waited "Focus into Next Editor on the Right" was not matching. I think this is a legitimate bug with the command palette's fuzzy search. Not sure if an issue exists yet.

**Comment by bpasero** [comment]
Yes, that explains it. Fuzzy find is not enabled in anything but the file picker (opt in).

**Comment by Tyriar** [comment]
@bpasero it did do a fuzzy match though on "**Focus** into **Right** Hand Editor"

**Comment by bpasero** [comment]
That is actually a conicidence from our camel case matcher :)

**Comment by Tyriar** [comment]
Ah, well no issue apart from #509 then :) thanks for looking into it.

**Comment by bpasero** [comment]
:+1:
