### ISSUE TITLE
Debug - SELECT AND START DEBUG - nog showing on status bar

### ISSUE THREAD

**Issue by BerndBroos** [microsoft/vscode#189128]
Type: <b>Bug</b>

When opening an existing project,
the select and start debug - button is not showing in the status bar.

It only appears when you have run a first debug-session,
even with an existing workspace.

-----
Also it would be nice not have separate buttons for,
RUN and RUN+DEBUG

-----
![image](https://github.com/microsoft/vscode/assets/132269491/5b08a238-5a12-4c26-bd07-8b28c3216468)

VS Code version: Code 1.80.2 (2ccd690cbff1569e4a83d7c43d45101f817401dc, 2023-07-27T20:40:28.909Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|16.1.4
vscode-html-css|ecm|1.13.1
dotnet-test-explorer|for|0.7.8
remotehub|Git|0.60.0
csharpextensions|kre|1.7.3
csharp|ms-|1.26.0
azure-repos|ms-|0.36.0
remote-repositories|ms-|0.38.1
vsliveshare|ms-|1.0.5877
material-icon-theme|PKi|4.29.0
LiveServer|rit|5.7.9

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
py29gd2263cf:30792227
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
vscccc:30610679
282f8724:30602487
89544117:30613380
a9j8j154:30646983
showlangstatbar:30737416
vsctsb:30748421
a2ce3375:30757347
57b77579:30736110
pythonfmttext:30731395
pythoncmvfstrcf:30756944
fixshowwlkth:30771522
showindicator:30785052
pythongtdpath:30769146
i26e3531:30792625
pythonnosmt12:30797651
pythonnoceb:30797650
e537b577:30795824
dsvsc013:30795093
dsvsc014cf:30797590
cmakestatusbarv2:30779594

```

</details>

**Comment by roblourens** [comment]
Yeah, this is by design. I don't want to bug everyone with that status bar item when they haven't ever used the debugger

**Comment by BerndBroos** [comment]
Ok thank you for your response.

But I can't see why it would be a problem if it were set by default.
... because it shows anyway after the first debug session.
... and debugging is a huge part of programming.

Anyway for future readers.
I've found a settings where you can default this button appearance.

![image](https://github.com/microsoft/vscode/assets/132269491/8c0600bd-7e6f-4bfe-adc3-df4d514d7543)
