### ISSUE TITLE
vs code cs50dev file keeps loading 

### ISSUE THREAD

**Issue by karboteen** [microsoft/vscode#189179]
ADD ISSUE DESCRIPTION HERE
![Screenshot 2023-07-28 191124](https://github.com/microsoft/vscode/assets/139865022/7b8978e4-f1a8-430f-81cb-b94e98457c8b)eb issue reporter -->
![image](https://github.com/microsoft/vscode/assets/139865022/0414f5b2-53e8-4da4-82df-e3371d8cbf63)
vs code cs50dev file keeps loading to tell me at the end "the file is not displayed in the text editor because it is a directory"or "the codespace is not available

**Comment by JajarGaming** [comment]
that's a github issue not a vscode issue

**Comment by gjsjohnmurray** [comment]
I suggest you contact your cs50 course support.

**Comment by aeschli** [comment]
Please file the issue against cs50
