### ISSUE TITLE
[Bug] Help popups sometime overlap the text behind the cursor

### ISSUE THREAD

**Issue by fwolff** [microsoft/vscode#189173]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.80.2
- OS Version: MacOs Ventura 13.4.1

Steps to Reproduce:

1. Open a Typescript code file (or, I guess, any other code file).
2. Move your cursor over the name of an object, not far from the top of the editor window ('dossierSliceActions' in this example):
<img width="820" alt="image" src="https://github.com/microsoft/vscode/assets/527445/40050d9a-0aaf-4251-8ff5-c3cf2f2c148e">
<img width="869" alt="image" src="https://github.com/microsoft/vscode/assets/527445/5070fa5a-fa9f-48a6-8492-cbeb632f2b81">
The popup describing the object overlaps the text behind the cursor ('dossierSliceActions').

However, this issue doesn't occur on all variable or function names:
<img width="646" alt="image" src="https://github.com/microsoft/vscode/assets/527445/46ddbd0b-52ef-49d0-b242-ebabd48f55e3">

The only workaround is to scroll up or down so the panel pops up correctly before or after the text under the cursor.

**Comment by aiday-mar** [comment]
Hi thank you for filing the issue. Could you post here a minimally reproducible example of the issue? Thank you.

**Comment by fwolff** [comment]
Hi,

Here is a minimal example. Copy-paste this code in a TS file (eg. Test.ts):

```
type Properties = {
    property1: string
    property2: string
    property3: string
    property4: string
    property5: string
    property6: string
    property7: string
    property8: string
    property9: string
}


















function doSomething() {

    const properties: Properties = {
        property1: "",
        property2: "",
        property3: "",
        property4: "",
        property5: "",
        property6: "",
        property7: "",
        property8: "",
        property9: "",
    }

    const names = Object.keys(properties)
}
```

Open it with vscode, scroll down so the line 29 is at the top of the viewport of the editor:

<img width="553" alt="image" src="https://github.com/microsoft/vscode/assets/527445/cf3c64de-e8df-4449-bb75-46ae9125354b">

Put your cursor over the type "Properties":

<img width="497" alt="image" src="https://github.com/microsoft/vscode/assets/527445/64fbc14d-b5b5-4f55-a441-ed2a2106a072">

The info popup covers the text "Properties", preventing to edit this part of the code, unless you scroll down.

Hope this helps, thanks!

**Comment by aiday-mar** [comment]
Hi thanks for the example. I am trying to reproduce the example, and currently I see the following. The hover widget appears below the properties variable as follows:

<img width="648" alt="Screenshot 2023-08-02 at 13 45 52" src="https://github.com/microsoft/vscode/assets/61460952/6f0169f5-20b8-4718-ab4b-10d128854c9c">

In your example above, where exactly are you hovering? On the properties variable?

Can you install VS Code insiders which is updated on a nightly basis and let me know if you see the same behavior? https://code.visualstudio.com/insiders/

**Comment by fwolff** [comment]
Thanks for your answer. I tried to use vscode insider with no success (still the same overlap):

Version: 1.80.2 (Universal)
Commit: 2ccd690cbff1569e4a83d7c43d45101f817401dc
Date: 2023-07-27T21:05:41.366Z
Electron: 22.3.14
ElectronBuildId: 22695494
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Darwin arm64 22.5.0

> In your example above, where exactly are you hovering? On the properties type?

Yes.

**Comment by aiday-mar** [comment]
That is rather curious, I will look into it

**Comment by aiday-mar** [comment]
Hi may I ask you if you still see this issue happening ever since you filed it?
