### ISSUE TITLE
settings.json - nested keys are inconsistently honored

### ISSUE THREAD

**Issue by anabelle2001** [microsoft/vscode#189113]
## Version Info
Does this issue occur when all extensions are disabled?: Yes
Version: 1.80.1
Commit: 74f6148eb9ea00507ec113ec51c489d6ffb4b771
Date: 2023-07-12T17:22:25.257Z
Electron: 22.3.14
ElectronBuildId: 21893604
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Linux x64 6.2.9-300.fc38.x86_64
### 1. Add this to `settings.json`
```json
{
    "editor": {
        "rulers": [2,3,6,7],
        "fontSize": 30,
        "fontFamily": "Arial"
    },

    "workbench": {
            "colorTheme": "Default High Contrast Light", //WARNING: BRIGHT
    }

    "files": {
        "simpleDialog":{
            "enable":true
        },
        "dialog":{
            "defaultPath":"/away"
        },
    },
}
```
### 2. Observe changes 
- The values will update in "Settings (UI)", and the editor's appearance / behavior will change
### 3. Use the syntax to change `terminal.integrated.shellIntegration.decorationsEnabled`:
```
// "terminal": {"integrated.shellIntegration.decorationsEnabled": "never"}, //doesn't work
// "terminal.integrated": {"shellIntegration.decorationsEnabled": "never"}, //doesn't work
// "terminal.integrated.shellIntegration": {"decorationsEnabled": "never"}, //doesn't work
// "terminal.integrated.shellIntegration.decorationsEnabled": "never"       //works
```
### 4. Verify that the second example doesn't work 
- The values do not update in "Settings (UI)", and the terminal's behavior does not change
## Expected Behavior
Either:
- Examples 1 and 2 both change the editor's settings, OR
- Neither Examples 1 nor 2 change the editor's settings (accords with resolution to # 188624)  

Instead,
- The second example does not work, but the first example does

**Comment by Tyriar** [comment]
@sandy081 do we support handling nested settings like this?

**Comment by anabelle2001** [comment]
No:
> This is not supported in settings.json file. One has to provide a complete setting key.

see #188624 for full context

**Comment by Tyriar** [comment]
I think right now we do indeed just not support this, by inconsistent support I'm guessing you're referring to things like `terminal.integrated.env.windows` which takes an object, but that's different to breaking up the keys. I'll pass this over to @sandy081 again as the owner of settings to confirm whether we need any doc updates.

**Comment by sandy081** [comment]
Here is the documentation for `settings.json` - https://code.visualstudio.com/docs/getstarted/settings#_settingsjson 

Please take a look and let me know if it is not clear enough. Feel free to contribute to the documentation in this repo - https://github.com/microsoft/vscode-docs
