### ISSUE TITLE
Your 'github' credentials do not have the required access

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#189178]
Yesterday I logged out of github and back in, to test something with copilot auth. Since then I get this notification over and over. I click “reauthenticate” but nothing changes, do you know what it means?

<img width="477" alt="image" src="https://github.com/microsoft/vscode/assets/323878/f1699964-371b-49b2-bce0-9ce869fee707">

**Comment by TylerLeonhardt** [comment]
My guess is that you're opening a repo that the token isn't SAML'd for and GitLens detects this and asks for auth again... however, it's likely not using the correct options to force the recreation of the token and ends in an infinite loop.

@eamodio can you check to see if you're using forceNewSession here?

**Comment by roblourens** [comment]
This stopped happening at some point

**Comment by eamodio** [comment]
@TylerLeonhardt From looking at the code we are using `forceNewSession` in those cases, but there was a relatively recent bug that could caused that path not to be taken. So hopefully this should be fixed now.
