### ISSUE TITLE
Vue.js is getting a lot of weird errors now

### ISSUE THREAD

**Issue by 22289d** [microsoft/vscode#189108]
Type: <b>Bug</b>

I believe there is a Vue.js related bug. 

When going into files, including those I have not edited, a red line will show up under imported components saying that the file is already imported but with different casing (it hadn't been). If I restart VSC this goes away but will return later.

And when using a Pinia store, if is telling me 'cannot read properties of undefined' when attempting to access the store in a Component via this.store. I am 100% sure this not true and I've imported the store correctly.

I have never seen these types of issues with Vue or VSC before.

VS Code version: Code 1.80.1 (Universal) (74f6148eb9ea00507ec113ec51c489d6ffb4b771, 2023-07-12T17:20:23.298Z)
OS version: Darwin arm64 22.3.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M2 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|1, 2, 2|
|Memory (System)|8.00GB (0.25GB free)|
|Process Argv|--crash-reporter-id 116ea124-4c70-4955-993a-492bfdb90d54|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
project-manager|ale|12.7.0
vscode-intelephense-client|bme|1.9.5
vscode-tailwindcss|bra|0.9.11
prettier-vscode|esb|9.19.0
gc-excelviewer|Gra|4.2.57
cpptools|ms-|1.16.3
multi-command|ryu|1.6.0
php-debug|xde|1.33.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
2e4cg342:30602488
89544117:30613380
a9j8j154:30646983
showlangstatbar:30737416
vsctsb:30748421
a2ce3375:30757347
pythonfmttext:30731395
pythoncmv:30756943
fixshowwlkth:30771522
hideindicator:30785051
pythongtdpath:30769146
i26e3531:30792625
pythonnosmt12:30797651
pythonnoceb:30797650
e537b577:30795824
dsvsc013:30795093
dsvsc014cf:30797590

```

</details>

**Comment by mjbvz** [comment]
Please start by filing this issue against your vue extension (VS Code doesn't ship with built-in vue support)

**Comment by 22289d** [comment]
I turned off all of those extensions and the problem persists.
