### ISSUE TITLE
markdown preview: add settings option to stop auto-escaping special characters

### ISSUE THREAD

**Issue by jeffreyyjp** [microsoft/vscode#189122]
Does this issue occur when all extensions are disabled?: Yes

Version: 1.80.2 (user setup)
Commit: 2ccd690cbff1569e4a83d7c43d45101f817401dc
Date: 2023-07-27T20:40:28.909Z
Electron: 22.3.14
ElectronBuildId: 22695494
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Windows_NT x64 10.0.19045

Steps to Reproduce:

1. Open a markdown file
2. Click the button right top of the UI: `Open Preview to the Side`
3. Check the render page

If my file contains some special characters like `<`, `>`, `|`. When it renders in VS Code， it okay without `\` backslash to add before them.
But when my code deploys on gitlab/github page, or render online markdown previewer, it can't display the right result.

Example:
`<cluster_id> | <cluster_name> | <cluster_location>` will render in VS Code like this:
![image](https://github.com/microsoft/vscode/assets/17985592/ad7a7a76-91ed-4fb0-8959-91a4ab620488)

but when it displays in gitlab page or some online markdown render, it shows like this:
![image](https://github.com/microsoft/vscode/assets/17985592/4da60038-5108-4027-8a61-95383948a3bb)

So I need to use this to make both okay when render in VS Code or some otherwise:

`\<cluster_id\> \| \<cluster_name\> \| \<cluster_location\>`

**Comment by mjbvz** [comment]
Our markdown preview uses markdown-it and the rendering you describe [matches how markdown it renders that text](https://markdown-it.github.io/#md3=%7B%22source%22%3A%22%3Ccluster_id%3E%20%7C%20%3Ccluster_name%3E%20%7C%20%3Ccluster_location%3E%5Cn%22%2C%22defaults%22%3A%7B%22html%22%3Afalse%2C%22xhtmlOut%22%3Afalse%2C%22breaks%22%3Afalse%2C%22langPrefix%22%3A%22language-%22%2C%22linkify%22%3Atrue%2C%22typographer%22%3Atrue%2C%22_highlight%22%3Atrue%2C%22_strict%22%3Afalse%2C%22_view%22%3A%22html%22%7D%7D)

Other markdown renderers may be doing something different but that doesn't make our rendering incorrect. There are lots of flavors of markdown but our built-in support tries to stick to a fairly standard one. Extensions can customize our markdown rendering if they wish
