### ISSUE TITLE
Add snippets as a language

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#189176]
There's a good community grammar for snippets at https://github.com/jeff-hykin/better-snippet-syntax, which would improve our snippets experience. We could include this as one of our built in languages.

**Comment by hustLer2k** [comment]
hey @alexr00 i would like to start working on it could you link some source files related to built in languages pls? thanks in advance

**Comment by alexr00** [comment]
To verify, open a snippets file and verify that you see placeholders get special highlighting like in https://github.com/jeff-hykin/better-snippet-syntax#before-and-after-xd-theme.
