### ISSUE TITLE
 Data Loss (stable -> insiders) smoke test fail

### ISSUE THREAD

**Issue by andreamah** [microsoft/vscode#189192]
```
    Data Loss (stable -> insiders)
      1) verifies opened editors are restored
      2) verifies that "hot exit" works for dirty files (without delay)
##[error]The task has timed out.
````

I get this twice when trying to build stable on the release branch https://dev.azure.com/monacotools/Monaco/_build/results?buildId=225735&view=logs&j=eb0ed907-d5fa-57af-e5f4-b64d416225ca&t=ddea3b83-4e41-52ab-b228-fbc50a616da5

Can this timeout be mitigated?

**Comment by alexr00** [comment]
Closing for verification

**Comment by alexr00** [comment]
The stable build succeeds now. Verified.

**Comment by bpasero** [comment]
The underlying reason is a blocking login dialog triggered by `safeStorage`.
