### ISSUE TITLE
Revert use of new certificate loading

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode#189133]
Still investigating two issues:
- https://github.com/microsoft/vscode/issues/188676
- https://github.com/github/codespaces/issues/14593

It will be safest to revert to the old certificate loading for now until we get more time for investigating and testing fixes for these issues.

**Comment by alexr00** [comment]
Closing for verification.

**Comment by chrmarti** [comment]
To verify:
- Set log level to trace.
- Reload window.
- Check that the Extension Host output channel does not contain any `ProxyResolver#connect` entries.
- (To cross-check you can re-enable the reverted behavior with the user setting: `"http.experimental.systemCertificatesV2": true`)
