### ISSUE TITLE
The debug module freezes due to a debug command execution failure

### ISSUE THREAD

**Issue by ZhangYaoan** [microsoft/vscode#189175]
Type: <b>Bug</b>

When debugging C++, after completing the compilation, the debug command execution failed because I mistakenly pasted the text in the terminal. Then the debug module freezes. It won't work until I restart VSCode.
![vscode-bug](https://github.com/microsoft/vscode/assets/110913909/d03a7ff9-5be2-430a-8fd7-19b93859d6b9)

VS Code version: Code 1.80.2 (2ccd690cbff1569e4a83d7c43d45101f817401dc, 2023-07-27T20:40:28.909Z)
OS version: Windows_NT x64 10.0.19045
Modes:
Remote OS version: Linux x64 5.15.90.1-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 5800H with Radeon Graphics          (16 x 3194)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.40GB (5.79GB free)|
|Process Argv|--crash-reporter-id ef874757-d569-41b2-bed5-74d30a05c9c1|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Debian|
|OS|Linux x64 5.15.90.1-microsoft-standard-WSL2|
|CPUs|AMD Ryzen 7 5800H with Radeon Graphics (16 x 3193)|
|Memory (System)|7.46GB (6.55GB free)|
|VM|0%|
</details><details><summary>Extensions (25)</summary>

Extension|Author (truncated)|Version
---|---|---
emojisense|bie|0.10.0
better-cpp-syntax|jef|1.17.2
vsc-python-indent|Kev|1.18.0
jupyter-keymap|ms-|1.1.2
remote-wsl|ms-|0.80.2
background|sha|1.2.12
pdf|tom|1.2.2
jinja|who|0.0.8
vscode-django|bat|1.10.0
python-environment-manager|don|1.0.4
python-extension-pack|don|1.7.0
code-runner|for|0.12.0
vsc-python-indent|Kev|1.18.0
vscode-language-pack-zh-hans|MS-|1.80.2023071209
python|ms-|2023.12.0
vscode-pylance|ms-|2023.7.40
cmake-tools|ms-|1.14.34
cpptools|ms-|1.16.3
cpptools-extension-pack|ms-|1.3.0
hexeditor|ms-|1.9.12
autodocstring|njp|0.6.1
cmake|twx|0.0.17
intellicode-api-usage-examples|Vis|0.2.7
vscodeintellicode|Vis|1.2.30
jinja|who|0.0.8

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscoreces:30445986
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
vsccc:30610678
3biah626:30602489
f6dab269:30613381
showlangstatbar:30737416
vsctsb:30748421
pythonfmttext:30731395
pythoncmvfstrcf:30756944
fixshowwlkth:30771522
hideindicator:30785051
pythongtdpath:30769146
i26e3531:30792625
gsofa:30797621
pythonnosmt12:30797651
e537b577:30795824
dsvsc013:30795093
dsvsc014:30797589

```

</details>

**Comment by roblourens** [comment]
I don't quite understand what happened here, but I think you should start by filing this on the C++ debug extension's repo, thanks
