### ISSUE TITLE
[WelcomeUX] "View Local Changes" in overlay doesn't do justice to the viewlet

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#18915]
Testing #18091

It sounds like it's just the open editors view at the top of the explorer, the overlay should mention the fact it deals with SCMs.

**Comment by seanmcbreen** [comment]
I will update this agree - I also think we need the keybindings) @bgashler1 is still working on layout right now so I'll leave this open.

**Comment by seanmcbreen** [comment]
Updated to Source Code Managment
