### ISSUE TITLE
In Codespaces JS/TS keeps crashing with a large Pulumi Typescript project

### ISSUE THREAD

**Issue by htgarym** [microsoft/vscode#189189]
ADD ISSUE DESCRIPTION HERE

Version: 1.80.2
Commit: 2ccd690cbff1569e4a83d7c43d45101f817401dc
User Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36
Embedder: codespaces

**Comment by mjbvz** [comment]
See https://github.com/pulumi/pulumi-azure-native/issues/2251
