### ISSUE TITLE
notebook sticky scroll overlapping issue

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#189195]
when using light HC theme 

![Screenshot 2023-07-28 at 2 21 22 PM](https://github.com/microsoft/vscode/assets/29464607/8bde8334-e9fe-4154-b081-1d1a5717eeee)

**Comment by meganrogge** [comment]
I think this should be labeled `bug` and closed @Yoyokrazy and @andreamah ?

**Comment by meganrogge** [comment]
also labeled `candidate`

**Comment by Yoyokrazy** [comment]
huh the PR merge didn't close this. Thanks for the ping.
