### ISSUE TITLE
Add "New Workspace File" action

### ISSUE THREAD

**Issue by moostad** [Microsoft/vscode#1892]
Currently new file command (cmd+N) will specify an  __untitled__ chunk in memory which need to be saved immediately (cmd+S) if we want to use VSCode intellisense*.
I think new file command should open a text input (not os file dialog) and ask for a path relative to current active file/directory to create the new file and after that active the editor.
for example if i'm editing ```./src/db/base.ts``` path ```../config.json``` should create json file in ```./src/config.json``` or path ```./company/ford.ts``` create ```company``` directory and then add ```ford.ts``` into that so finally we will have ```./src/db/company/ford.ts``` . It's make a huge difference especially because right now it's necessary to use mouse for saving file in different directory.

*Just changing Language Mode (cmd+K M) doesn't work because intellisense for modular systems need to know where file will be saved. 
for example in new __untitled__ file ```import { person } from '../info'``` where is ```../``` directory? because of that VSCode is unable to deliver intellisense for ```person```.

**Comment by Tyriar** [comment]
What about when the user doesn't want to save the file? Part of my workflow is to use my text editor to take notes which I'll either save/delete/action later.

**Comment by moostad** [comment]
@Tyriar I'm pretty sure the main purpose of this feature is not what you're referring to. However that can be good separate feature.

**Comment by joaomoreno** [comment]
I agree with @moostad. Let's transform this issue into a feature request. I think it's a good idea.

@bpasero fyi

**Comment by bpasero** [comment]
@moostad this sounds like a good example for an extension :)

**Comment by joaomoreno** [comment]
:+1:

**Comment by bpasero** [comment]
![image](https://cloud.githubusercontent.com/assets/900690/12231588/11e31f34-b859-11e5-8380-7b5a36ad3d84.png)

Seems to exist, closing.
