### ISSUE TITLE
Text search result messages not shown in search view

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode#189288]
1. Go to github.dev/microsoft/vscode, run a text search
2. While search is running, hit cancel on the "downloading repository index..." notification in the bottom right corner
3. :bug: search view should show two messages (see below) but only the first one shows up

![image](https://github.com/microsoft/vscode/assets/30305945/e2568187-d2f4-41a8-99f3-6daed128f7d7)

**Comment by eleanorjboyd** [comment]
Saw the notification about indexing but it was before I clicked search and now whenever I click search I don't see the notification come up.

**Comment by andreamah** [comment]
I believe that you can try to do this with a larger repo (like https://github.dev/electron/electron), and there should be enough time to cancel the index. Not too sure how to remove the index once it's downloaded, but you can try that first!

**Comment by joyceerhl** [comment]
You can delete the downloaded index with the Delete All Repository Indexes command

**Comment by rzhao271** [comment]
The search result message changed but I see two messages at least
![No results found message followed by Partial Results shown message](https://github.com/microsoft/vscode/assets/7199958/7438ca9d-e421-4b6a-94c1-46ae099cd6e7)
