### ISSUE TITLE
Provide a way to disable specific formatters

### ISSUE THREAD

**Issue by jylin** [microsoft/vscode#189221]
I would like a way to disable specific code formatters like "vscode.json-language-features". They are not part of an extension I can uninstall, and it always comes up as a conflict with the prettier formatter (which comes in an extension).

I currently have to configure prettier as default for a bunch of file types manually, but it would be simpler if I can disable the built-in "vscode.json-language-features" formatter, then prettier will just be the default without needing to set a default formatter for a bunch of file types (e.g. [json], [html], [typescript], etc).

**Comment by jrieken** [comment]
@aeschl the contract is that extensions that contribute a formatter along with other things should come with a setting to disable their formatter.

**Comment by aeschli** [comment]
Thanks @jrieken. In deed we already have such a setting: `json.format.enable`
@jylin Please set it to false.
