### ISSUE TITLE
When in codespaces (using github.dev via browser) the Web bundle (VSIX) gets installed instead of the desktop bundle

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode#189280]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:  Latest
- OS Version: N/A

Steps to Reproduce:

1. Open a repo in codespaces from the browser
2. Install the Jupyter extension
3. The Web VSIX is installed instead of the appropriate platform (desktop) bundle, as a result a number of features no longer work in Jupyter extension.

**Comment by ucovcoder** [comment]
@DonJayamanne @sandy081 might be a dumb question, but from the description it seems maybe there is a workaround for installing the "right" VSIX in Codespaces?

**Comment by DonJayamanne** [comment]
The work around is to publish a universal vsix. 
That's what we do in Jupyter extension for now.

**Comment by ucovcoder** [comment]
Thanks @DonJayamanne, I meant is there a workaround for us as users of github.dev to somehow install the right VSIX without having to wait for the fix?

**Comment by ucovcoder** [comment]
@DonJayamanne thanks again, I am using the Jupyter extension. 
I opened #189276 and it was linked here, but I am still unable to use the kernel picker on github.dev despite reinstalling the Jupyter extension.

**Comment by DonJayamanne** [comment]
It is working on github.dev, as you can see here (tried this just now)
![Screenshot 2023-08-11 at 02 17 11](https://github.com/microsoft/vscode/assets/1948812/36a92490-66a0-45be-9c73-1b6dd8de7fc4)

**Comment by sandy081** [comment]
@DonJayamanne Are you still seeing this issue? If so, does adding `extensionKind` to the manifest worked for you?

**Comment by DonJayamanne** [comment]
@sandy081 I haven't tried this recently. I do not want to modify the Juptyer extension to test this out.
I was able to verify this ws a bug in core by creating and publishing a personal extension

**Comment by sandy081** [comment]
Can you please verify if adding `extensionKind` fixes this problem?

**Comment by DonJayamanne** [comment]
I’m not keen on modifying Jupyter extension and publishing that to the marketplace  to test this,

I would have thought publishing another (separate) private extension to test this would be a better way to test

**Comment by DonJayamanne** [comment]
I will create a separate extension and test this tomorrow

**Comment by sandy081** [comment]
yes - set it to `workspace`

**Comment by sandy081** [comment]
@DonJayamanne I tried installing `donjayamanne.sample-testing-ext` in a codespace and it installed rightly on the server. Can you please double check?

**Comment by rebornix** [comment]
I can confirm the latest `donjayamanne.sample-testing-ext` is installed and running in workspace (other than running in web worker).

**Comment by sandy081** [comment]
@rebornix Thanks for confirmation.

Please add the `extensionKind` set to `workspace` for jupyter extension to get this fixed.

**Comment by DonJayamanne** [comment]
> Please add the extensionKind set to workspace for jupyter extension to get this fixed.

I thought the default value for this setting is ‘workspace’
Or isn’t it?
Probably best to document this somewhere on vscode docs  for the benefit of others,

**Comment by sandy081** [comment]
Defaults are computed using package.json. In case of Jupyter you have different package.json per target platform. For eg., the package.json for web vsix has only `browser` value and no `main` value. In this case, extensionKind is computed to be `web`. At present, in codepsaces we are fetching the package.json of any VSIX to determine the extensionKind which also determines where to install. We are assuming that package.json is same across platforms. I agree that we should be changing our logic to fetch package.json that is compatible first with remote and then to web. But if this can be fixed by setting the extensionKind, I would go with that. I will also document that in our platform specific extensions documentation when extensions started having different package.jsons per target.
