### ISSUE TITLE
How to provide for base tag href related url

### ISSUE THREAD

**Issue by shigomany** [microsoft/vscode#189214]
Does this issue occur when all extensions are disabled?: Yes

Hello. 

## Introduction

I'm trying to create a UI in VS Code using Flutter Web

## Question

I have a question about how I can set the **base** **href** via `vscode-webview-resource` and the `uuid `that is assigned there like [here](https://github.com/microsoft/vscode/issues/98542).

I used the **asWebViewUrl** function as in this [example](https://code.visualstudio.com/api/extension-guides/webview#loading-local-content).

But when I set the value for **base href** here, I get an HTTP (see below) address, although the example says that in debug mode I will get a **vscode-resource**

```html
<base href='https://file+.vscode-resource.vscode-cdn.net/Users...' />
```

Therefore, I get this error:
<img width="660" alt="image" src="https://github.com/microsoft/vscode/assets/43740557/5acf99ce-d76c-4742-bf67-221ce453e49f">

## Env

- VS Code Version: 1.80.2
- OS Version: Apple M1 Pro, Ventura 13.4

## Test case

Steps to Reproduce:

1. Clone [repo](https://github.com/shigomany/vscode-extension-webview-flutter)
2. `npm i`
3. In VS Code launch `Run Extension`
4. Open DevTools in VS Code
5. Cmd + Shift + P -> Tap `ARB Part`.

**Comment by Adichillsat11** [comment]
I think it might be just an installation issue

**Comment by shigomany** [comment]
What do you mean by **installation**?

**Comment by shigomany** [comment]
I also noticed if you don't overwrite the base tag, then for scripts that are inserted through js, you get an error **ERR_FILE_NOT_FOUND** like [here](https://stackoverflow.com/questions/64443590/flutter-web-err-file-not-found-in-release). 

But only this problem occurs when flutter.js is trying to add a script to the body [here](https://github.com/shigomany/vscode-extension-webview-flutter/blob/main/build/flutter.js#L306)

**Comment by shigomany** [comment]
Up

**Comment by mjbvz** [comment]
`<base>` works fine with `asWebviewUrl` as [shown here in the built-in markdown extension](https://github.com/microsoft/vscode/blob/8f7590dbc0879557e6a0d0ff64c0d3b8d64f60b4/extensions/markdown-language-features/src/preview/documentRenderer.ts#L104)

Don't try checking the actual url returned from `asWebviewUrl`. It's intentionally meant to be opaque and varies between desktop and web

As for the security error, that's a question for dart
