### ISSUE TITLE
CommandNotFoundException

### ISSUE THREAD

**Issue by hermakab** [microsoft/vscode#189227]
Type: <b>Performance Issue</b>

Hello,

I´m having a issue as described below. I tried some google-fixes but didn´t help. Also tried these ones: https://stackoverflow.com/questions/48602324/the-term-go-is-not-recognized-as-the-name-of-a-cmdlet-function-script-file
Does anyone please have any fixes?

PS C:\Users\xxx\booking-app> main.go
main.go : The term 'main.go' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spe
lling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ main.go
+ ~~~~~~~
    + CategoryInfo          : ObjectNotFound: (main.go:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

Suggestion [3,General]: The command main.go was not found, but does exist in the current location. Windows PowerShell does not load commands from the current location by default. If you trust this command, instead type: ".\main.go". See "get-help about_Command_Precedence" for more details.

**Comment by gjsjohnmurray** [comment]
Maybe https://github.com/microsoft/vscode/issues/189183#issuecomment-1656781045 will help you.

**Comment by hermakab** [comment]
> Maybe [#189183 (comment)](https://github.com/microsoft/vscode/issues/189183#issuecomment-1656781045) will help you.

Thanks, but unfortunately that didn´t make any difference. I had CMD already set as default profile, tried to switch PS just in case as well but still same error. I see that arg387 posted recently too, so might be a fresh bug?

**Comment by arg387** [comment]
@hermakab can you send a screenshot of the terminal in vscode?

**Comment by roblourens** [comment]
Did you type that in the terminal or are you using the Go extension?

**Comment by roblourens** [comment]
You will have to type the name of a program before the file name, I suggest checking the Go docs
