### ISSUE TITLE
Custom colour of brackets is ignored

### ISSUE THREAD

**Issue by DimanNe** [microsoft/vscode#189262]
Does this issue occur when all extensions are disabled?: **Yes**

- VS Code Version:

```
Version: 1.80.2
Commit: 2ccd690cbff1569e4a83d7c43d45101f817401dc
Date: 2023-07-27T20:41:52.615Z
Electron: 22.3.14
ElectronBuildId: 22695494
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Linux x64 5.15.0-78-generic
```

- OS Version: 

```
Description:    Ubuntu 22.04.2 LTS
Release:        22.04
```

## Steps to Reproduce

1. Create a file (for example, c++) with curly and round brackets, such as this:

    ```cpp
    namespace {

    class SparcOperand;

    class SparcAsmParser : public MCTargetAsmParser {
      MCAsmParser &Parser;

      /// @name Auto-generated Match Functions
      /// {

    #define GET_ASSEMBLER_HEADER
    #include "SparcGenAsmMatcher.inc"

      /// }

      // public interface of the MCTargetAsmParser.
      bool MatchAndEmitInstruction(SMLoc IDLoc, unsigned &Opcode,
                                   OperandVector &Operands, MCStreamer &Out,
                                   uint64_t &ErrorInfo,
                                   bool MatchingInlineAsm) override;
    ```

3. Open settings and set colours of brackets:

    ```
    { "scope": "punctuation.section.block.begin.bracket.curly"                  , "settings": { "foreground": "#ff0000", "fontStyle": "bold" } },
    { "scope": "punctuation.section.parameters.begin.bracket.round"             , "settings": { "foreground": "#ff0000", "fontStyle": "bold" } },
    ```

    I also attached my entire [settings.json](https://github.com/microsoft/vscode/files/12209200/settings.json.txt) file.

4. You should now be able to observe two issues:
    * actual colours of bracket does not match request/specified in the settings
    * open "Developer Inspect Editor Tokens and Scopes", and see that the information provided there also does not match actual colour.
        * For example, the dialog states that the colour is `"foreground": "#FF0000"`, while in reality it is not.

    Please, see attached screenshots:
    * png for [curly brackets](https://github.com/microsoft/vscode/assets/279056/2fde4b41-b6a1-402d-b716-2491753820f1)
    * png for [round brackets](https://github.com/microsoft/vscode/assets/279056/4faa89d5-103f-4fea-8abf-adc7dc2259fa)

### I was not able to upload files with extension `json` to github, because they "*do not support files with such extensions*", so, I had to append `.txt` to them. In order to view them, just remove the `.txt` extension.

<details>
<summary>System information</summary>

Item | Value
-- | --
GPU 0 | NVIDIA GeForce RTX 3080
CPUs | AMD Ryzen 9 5950X 16-Core Processor (32 x 2200)
GPU Status | 2d_canvas: unavailable_software canvas_oop_rasterization: disabled_off direct_rendering_display_compositor: disabled_off_ok gpu_compositing: disabled_software multiple_raster_threads: enabled_on opengl: disabled_off rasterization: disabled_software raw_draw: disabled_off_ok video_decode: disabled_software video_encode: disabled_software vulkan: disabled_off webgl: unavailable_software webgl2: unavailable_software webgpu: disabled_off
Load (avg) | 0, 1, 1
Memory (System) | 125.70GB (108.83GB free)
Process Argv | --disable-extensions /home/dimanne/devel/scripts/contrib/llvm-project/llvm/lib/Target/Sparc/AsmParser/SparcAsmParser.cpp --crash-reporter-id 1b2bf8d1-5d0e-42d4-a5d9-6e937acf6abe
Screen Reader | no
VM | 0%
</details>

<details>
<summary>Extensions</summary>
Extensions are disabled
</details>

<details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
py29gd2263cf:30792227
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
2e4cg342:30602488
f6dab269:30613381
showlangstatbar:30737416
vsctsb:30748421
03d35959:30757346
pythonfmttext:30731395
pythoncmv:30756943
fixshowwlkth:30771522
hideindicator:30785051
pythongtdpath:30769146
i26e3531:30792625
pythonnosmt12:30797651
pythonnoceb:30797650
e537b577:30795824
dsvsc013:30795093
dsvsc014:30797589
cmakestatusbarv2:30779594
```

</details>

**Comment by IllusionMH** [comment]
Do you have Brackets pair colorization enabled?
https://code.visualstudio.com/updates/v1_60#_high-performance-bracket-pair-colorization

If yes, they would override code theme.
`"editor.bracketPairColorization.enabled": false` to disable

**Comment by DimanNe** [comment]
I did!

Thank you for super-quick resolution (I disabled it, and everything works as expected).
