### ISSUE TITLE
[WelcomeUX] When settings.json not valid JSON: Console error while checking/unchecking check box

### ISSUE THREAD

**Issue by ramya-rao-a** [Microsoft/vscode#18923]
Testing #18091 on OS X El Capitan

<img width="578" alt="screen shot 2017-01-20 at 11 12 37 am" src="https://cloud.githubusercontent.com/assets/16890566/22161987/7c8585dc-df01-11e6-9041-d9fcf8967d08.png">

**Comment by chrmarti** [comment]
Is your settings.json not valid JSON?

**Comment by ramya-rao-a** [comment]
Ah! There was a trailing comma.
This would be related to #16780
