### ISSUE TITLE
Pls. make a feature to drag and place a tab exactly between two tabs

### ISSUE THREAD

**Issue by Sancetiano** [microsoft/vscode#189213]
I would like VSCode devs to implement a new feature for the user to drag and place a tab exactly between two tabs. This will be useful when there are many tabs currently open in the editor and the user want to group each of the tabs based on their respective importance and usage from left to right across the tab bar.

**Comment by gjsjohnmurray** [comment]
Are you not already able to resequence tabs by dragging?
