### ISSUE TITLE
VSCode Not Invoked When Creating GitHub Codespace

### ISSUE THREAD

**Issue by conradwt** [microsoft/vscode#189290]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.81.0-insider (Universal)
- OS Version: macOS 13.5

Steps to Reproduce:

1. Create GitHub Codespace
2. I see "Launching Visual Studio Code" message

![Screenshot 2023-07-30 at 11 21 01 PM](https://github.com/microsoft/vscode/assets/20219/f9e190ca-4a34-45df-838b-640399ccefbe)

**Comment by lszomoru** [comment]
@conradwt, thank you very much for filling this issue and apologies for not getting back to you on this until now. Based on the provided information, this seems to be an issue with GitHub Codespace so could you please file an issue in the [Codespaces issue tracker](https://github.com/orgs/community/discussions/new?category=codespaces). Thank you!
