### ISSUE TITLE
Remote - SSH with tmux, disable ssh -T option

### ISSUE THREAD

**Issue by maxencefaldor** [microsoft/vscode#189220]
Currently, the Remote - SHH extension connects to remote using:
``[12:00:00.350] > local-server-1> Running ssh connection command: "-v -T -D 57426 -o ConnectTimeout=15 remote"``
The issue is that the use of -T option prevents the use of tmux.

Example:
In my ``~/.ssh/config``, I have:
```
Host remote
        RemoteCommand tmux new-session -As remote "singularity shell container.sif"
        RequestTTY yes
```

When I do ``ssh remote``, I get a tmux session:
```
Singularity> 
```

But when I do ``ssh -T remote`` (like VSCode does when connecting to remote), I get the following error:
```
open terminal failed: not a terminal
```

I would like to know if something knows a workaround, because I need to connect to remote with VSCode using Remote - SSH with tmux, and currently, the -T option used by VSCode is preventing this.

Thank you!

**Comment by roblourens** [comment]
Tracking in this issue https://github.com/microsoft/vscode-remote-release/issues/7558
