### ISSUE TITLE
Allow to embed SVGs to enable accessing VS Code theme colors for `fill` and `stroke` properties

### ISSUE THREAD

**Issue by christian-bromann** [microsoft/vscode#189201]
Currently VS Code allows to define SVGs for light and dark mode. While it allows to align to the users theming it still has a lot of limits especially when other colors than black and white are used, e.g.:

![image](https://github.com/stateful/vscode-runme/assets/54253524/862b9cce-5764-42c1-a6f7-f9a8e22a04c7)

As you can see the VS Code icons adopt to the color scheme but our icon on the left stays white.

### Solution

SVGs allow to define `fill` and `stroke` values based on CSS variables which would enable to set the stroke color based on the foreground color e.g. `stroke="var(--vscode-foreground)"`. This would provide much better ways to align the icon according to the user theme. All what is needed for that to happen is to embed the SVG into the document rather than setting it via `background-color`.

Would the team be open to a PR that would embed the SVG into the document? In the `package.json` you could add an `embed` property to the `icon` one e.g.

```json
      {
        "command": "runme.openAsRunmeNotebook",
        "category": "Runme",
        "title": "Open markdown as Runme",
        "icon": {
          "embed": true,
          "light": "assets/runme-logo-light.svg",
          "dark": "assets/runme-logo-dark.svg"
        }
```

Or a user could provide the raw SVG like this:

```json
      {
        "command": "runme.openAsRunmeNotebook",
        "category": "Runme",
        "title": "Open markdown as Runme",
        "icon": "<svg width=\"18\" height=\"18\" viewBox=\"0 0 18 18\" fill=\"none\" xmlns=\"http://www.w3.org/2000/svg\"><path d=\"M16 1H2C1.44772 1 1 1.44772 1 2V16C1 16.5523 1.44772 17 2 17H16C16.5523 17 17 16.5523 17 16V2C17 1.44772 16.5523 1 16 1Z\" fill=\"var(--vscode-errorForeground)\" stroke=\"var(--vscode-errorForeground)\" stroke-width=\"0.5\" />  <path d=\"M6 11.9842V6.00137C6 5.92847 12 8.92125 12 8.9928C12 9.06434 6 12.0776 6 11.9842Z\" fill=\"var(--vscode-errorForeground)\" stroke=\"var(--vscode-errorForeground)\" stroke-width=\"0.5\" /></svg>\""
      },
```

What do you think?

**Comment by aeschli** [comment]
This is a bug in the editor toolbar: It should render the SVG with the icon color.

We have a method to render SVG with a specific color using masks.

I'm aware of the possibility to use variables in SVG. That's powerful, but too much for our use case given that we want icons to be singe-color (foreground/background).

If you need an immediate fix, you can switch to use icon fonts for your icons:
https://code.visualstudio.com/api/references/icons-in-labels#icon-contribution-point

Once you have defined an icon, you can then reference it by `"icon": "$(your_icon)"`

If you have many icons in your extension then it's worth the effort.

**Comment by aeschli** [comment]
To reproduce:
- install git lense
- set 
```
	"workbench.colorCustomizations": {
		"editorWarning.background": "#F5EAC144",
		"icon.foreground": "#ff0000"
	},
```
- open an editor
![image](https://github.com/microsoft/vscode/assets/6461412/bf02656c-2af1-466a-848c-2cd32e1d3a30)

**Comment by aeschli** [comment]
I created a new issue in favour of this one. We have currently no plans to support CSS variables in SVGs

**Comment by christian-bromann** [comment]
> If you need an immediate fix, you can switch to use icon fonts for your icons:

Great advice, thank you!
