### ISSUE TITLE
[Bug] Standalone color picker not working with Hex alpha

### ISSUE THREAD

**Issue by StephaneAdeso** [microsoft/vscode#189270]
Does this issue occur when all extensions are disabled?: Yes

The standalone color picker don't works well with hexadecimal alpha. No matter how much alpha you select, the color picker totally ignores it. 

There is two possible solutions: 
 1. Fix it and make the color picker use correctly the alpha level.
 2. Add hexadecimal with alpha to the supported color system and disable the alpha option in the normal hexadecimal.

- VS Code Version:  1.80.2     2ccd690cbff1569e4a83d7c43d45101f817401dc     x64
- OS Version: Windows 11 pro

Steps to Reproduce:

1.  Open color picker
3.  select any hexadecimal value with alpha
4.  press replace

![image](https://github.com/microsoft/vscode/assets/55595063/01e28fdb-f9f6-4d6d-a05c-21e66de0b617)

**Comment by aiday-mar** [comment]
This if fixed

**Comment by aiday-mar** [comment]
Hi I believe this should be fixed in the next stable release when it comes out
