### ISSUE TITLE
bring back the paste-to-markdown-link functionality in code-insiders

### ISSUE THREAD

**Issue by noahehall** [microsoft/vscode#189228]
I really enjoyed the copy-paste link to markdown feature

with the latest code-insiders the feature has been removed.

perhaps we could put the feature behind a flag?

**Comment by gjsjohnmurray** [comment]
I think this is controlled by the `markdown.editor.pasteUrlAsFormattedLink.enabled` setting. It's default changed very recently.

**Comment by noahehall** [comment]
thanks @gjsjohnmurray 

setting it to "smart" worked perfectly!
