### ISSUE TITLE
Typo on Feedback page: "X's your feedback"

### ISSUE THREAD

**Issue by SamuelChih** [microsoft/vscode#189203]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.80.2
- OS Version:  Windows_NT x64 10.0.22621

Steps to Reproduce:
![image](https://github.com/microsoft/vscode/assets/30818360/f344f248-84ad-4e1b-97f7-38231f4fc6cc)

1.  Go to bottom right, click on "Tweet feedback"

The text on the Feedback button presently reads as "Tweet us your feedback" which appears to be a typing error. According to a recent x's by [Elon Musk](https://twitter.com/elonmusk/status/1683365872323133442?), the accepted format should now be "X's us your feedback." There's a need to review and correct this typo to maintain a professional and consistent user interface.

**Comment by gjsjohnmurray** [comment]
Resolved by #189027

**Comment by bpasero** [comment]
Yes, we removed any trace of Twitter from VS Code, but only in insiders, so it needs a month before appearing in stable.
