### ISSUE TITLE
[WelcomeUX] Recent folders that no longer exist should be handled more gracefully

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#18924]
Testing #18091

![image](https://cloud.githubusercontent.com/assets/2193314/22162002/8670c142-df01-11e6-990e-206b49dd1568.png)

![image](https://cloud.githubusercontent.com/assets/2193314/22162011/8e009964-df01-11e6-8314-ebccbceeafc5.png)

**Comment by chrmarti** [comment]
This is the same behavior as with Ctrl+R. The error 'void(0)' has been fixed. Closing.
