### ISSUE TITLE
Failed to load Extensions gallery behind proxy with ERR_INSECURE_RESPONSE

### ISSUE THREAD

**Issue by iamitava** [Microsoft/vscode#18920]
- VSCode Version: Code 1.8.1 (ee428b0eead68bf0fb99ab5fdc4439be227b6281, 2016-12-19T14:55:32.357Z)
- OS Version: Linux ia32 3.19.0-32-generic
- Extensions:

|Extension|Author|Version|
|---|---|---|

---

Hi, I'm on a corporate network that requires a proxy that injects it's own SSL cert. I have the following user settings:

```js
{
    "http.proxy": "http://proxy:port",
    "http.proxyStrictSSL": false,
}
```

Based on #69 etc, it seems setting `proxyStrictSSL` to false should work for self-signed certificates, but I am unable to even browse the extensions gallery. Console shows the following error:

```
https://marketplace.visualstudio.com/_apis/public/gallery/extensionquery
Failed to load resource: net::ERR_INSECURE_RESPONSE
```

I haven't seen _that_ error code in the issues here yet!

Let me know what other information I could provide to debug this. Thanks!

**Comment by joaomoreno** [comment]
That definitely is a new error code. Can you join us in #18103?

**Comment by xapienz** [comment]
Hi @iamitava, will you please check that workaround with certutil in #17360 helps to resolve the problem?
I think these two problems are the same.

**Comment by joaomoreno** [comment]
Please check #22214 

Closing this as a duplicate
