### ISSUE TITLE
Unable to open 'settings.json': t.toLowerCase is not a function.

### ISSUE THREAD

**Issue by eamodio** [Microsoft/vscode#18933]
- VSCode Version: `1.9.0-insider` ee9d91c05fa571de56c41383cceee30b05b0a2f6
- OS Version: macOS Sierra `10.12.2`

Steps to Reproduce:

1. Open settings
2. Type into the search box and press enter (nothing happens -- this is another bug -- searching doesn't work)
3. Switch to another tab, and then try to switch back to settings (or close the settings tab and reopen and you will see the following
![image](https://cloud.githubusercontent.com/assets/641685/22162194/a37ee402-df1b-11e6-9349-5519b9dea7a5.png)
4. From now on until you close this window, you will get that same error when trying to open the settings -- and the settings won't open

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/18557 /cc @sandy081
