### ISSUE TITLE
"singleThread" is not activated even though "supportsSingleThreadExecutionRequests" is set true

### ISSUE THREAD

**Issue by lhMountainHigh** [microsoft/vscode#189313]
Hi,
    I got a problem while developing debug tool based on vsode. I wanted my tool support "single thread continue".
    To achieve this, in the initializeResponse from Adapter to vscode I set the  "supportsSingleThreadExecutionRequests" to be true. However, when I click the continue button on VScode, the continue request sent out from  vscode does not contain  "singleThread" which I wanted to activated.
    Could you tell me why I faild to activate the "singleThread" argument in continue requests?
    Thanks!

The singleThread I wanted to activated
![image](https://github.com/microsoft/debug-adapter-protocol/assets/108442047/92e92b93-98d4-4607-9013-5016b9baca79)

My initializeResponse is like this,
![image](https://github.com/microsoft/debug-adapter-protocol/assets/108442047/11a20bd2-b5bf-4f2d-a05b-89cba56aa14e)

The continue Request from vscode is like this,
![image](https://github.com/microsoft/debug-adapter-protocol/assets/108442047/52f163d6-80c8-4fe3-874b-d64ca50dd23b)

The continue button I clicked.
![image](https://github.com/microsoft/debug-adapter-protocol/assets/108442047/1c29b0fb-3499-4912-96dd-4db73e5ed95f)

**Comment by roblourens** [comment]
This is not implemented yet in vscode, sorry https://github.com/microsoft/vscode/issues/166450
