### ISSUE TITLE
adjust function of "Find All Impliment"

### ISSUE THREAD

**Issue by abc19899** [microsoft/vscode#189386]
Currently:  the popup menu command: "Find All Implimentations"  only show method impl by detrived class.  
My suggest: show all impl by detrived class and detrived of detrived class  recersively. 
Reason:  when i use this command "Find All Impl", I want to see all impl. currently, i need to navigate to impl of detrived class and use "Find All Impl" on each detrived class to see more impl.

**Comment by dbaeumer** [comment]
In which language are you seeing this since the real implementation of that feature is subject to the respective language server.

**Comment by abc19899** [comment]
I am using C++.   and LSP  is clangd.

**Comment by dbaeumer** [comment]
OK. Can you then please file the issue against this repository: https://github.com/microsoft/vscode-cpptools. They provide the implementation of that feature.
