### ISSUE TITLE
[WelcomeUX] Should the first editor in walkthrough not be focused for accessibility?

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#18931]
Testing #18091

**Comment by chrmarti** [comment]
It is given focus and that seems to work. Are you asking to not do that?

**Comment by Tyriar** [comment]
I believe screen readers would skip the intro section since the editor gets focus.

**Comment by chrmarti** [comment]
Also doesn't go well with the full-editor scroll actions.
