### ISSUE TITLE
Insiders is no longer removing obsolete (superseded) extension folders

### ISSUE THREAD

**Issue by gjsjohnmurray** [microsoft/vscode#189334]
I think this got broken very recently by 12e03adf6e77eb3c9ae7299f35ae4707c1d39638 (PR #188917 by @sandy081)

The arguments passed to `isEqualOrParent` here are reversed.

https://github.com/microsoft/vscode/blob/e1b9eedbbb5d8247ce2caba92d0d9a2277ca5400/src/vs/platform/extensionManagement/node/extensionManagementService.ts#L573-L575

**Comment by rzhao271** [comment]
The PR LGTM but I'd like to confirm what the repro/verification steps are. Also, if the folder stays there, do you know whether it's just taking up space, or whether it immediately starts to interfere with other extension-related functions?

**Comment by roblourens** [comment]
My extensions folder is packed full of stuff like this from the last week
<img width="346" alt="image" src="https://github.com/microsoft/vscode/assets/323878/a9e373b4-2d01-4852-83bf-74dab3b476d1">

I think that is the issue, and I agree re:candidate

**Comment by gjsjohnmurray** [comment]
A repro is to use the "Install Another Version...` option several times from the extension's gearwheel, restart VS Code a few times to give the normal cleanup a chance to do its stuff, then observe that your extensions folder still has obsolete entries. Here are some of mine from testing earlier today (UK timezone)

![image](https://github.com/microsoft/vscode/assets/6726799/0b397e74-e57f-4a43-8ab6-b835bac8510c)

**Comment by gjsjohnmurray** [comment]
I guess the verification of the issue that the bad PR was intended to fix ([Installing extension from VSIX after installing from location deletes original directory](https://github.com/microsoft/vscode/issues/188582)) confirmed that the unwanted deletion didn't happen but didn't verify the inverse (i.e. that wanted deletions continued to happen).

**Comment by gjsjohnmurray** [comment]
Please will someone label this Candidate so it doesn't get overlooked?

**Comment by alexdima** [comment]
@roblourens @rzhao271 Could you please help verify this?

**Comment by gjsjohnmurray** [comment]
I have verified this in the new Insiders.
