### ISSUE TITLE
[WelcomeUX] Editor Theme, also tell me how do get there myself?

### ISSUE THREAD

**Issue by ramya-rao-a** [Microsoft/vscode#18938]
Testing #18091 on OS X El Capitan

Clicking on "Editor theme" quick link opens the command pallet for user to change the theme.
But, this doesn't help the user learn how to do it the next time.

May be include the command (Preferences: Color Theme) in the text or the menu route 
Code -> Preferences -> Color Theme.

Same thing for "Show All Commands". We can include the keyboard shortcut there.
And for "Change Settings"

**Comment by seanmcbreen** [comment]
I agree this would be good to do (we just added all the shortcuts to the overlay) but I don't think we can do it cleanly in the design currently.  So we may have to wait for the next update.

**Comment by chrmarti** [comment]
It's most important for Show All Commands, that is not usable (in any reasonable way) without the shortcut.

**Comment by chrmarti** [comment]
@bgashler1 We can add shortcuts using, e.g., `<span class="shortcut" data-command="workbench.action.showCommands"></span>`. These will need some styling. Could you consider that for the January release?

**Comment by chrmarti** [comment]
Adding it to Show All Commands for now.

**Comment by chrmarti** [comment]
Verifier: Please check Windows and Linux.
