### ISSUE TITLE
System fonts can't be used as the editor font

### ISSUE THREAD

**Issue by SoMuchForSubtlety** [microsoft/vscode#189346]
Type: <b>Bug</b>

Steps to Reproduce:

1. install vscode from https://packages.microsoft.com/yumrepos/vscode
2. try to change the editor font
3. the font stays the default "monospace" font

Even changing the CSS manually with the dev tools does not work, so it seems like the fonts are not being picked up at all.

They do work in other applications (chrome, firefox, jetbrains IDEs) and in vscode installed from [flathub](https://flathub.org/apps/com.visualstudio.code)

![image](https://github.com/microsoft/vscode/assets/15961647/9049e91a-f9d5-4636-b7da-fe3f55fbab87)

<details>
<summary>VS Code version</summary>

```
Version: 1.81.0-insider
Commit: 9800cf6dd6bf4634889d60720ef46a400f3a7298
Date: 2023-07-28T12:07:54.339Z
Electron: 22.3.18
ElectronBuildId: 22689846
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Linux x64 6.4.6-200.fc38.x86_64
```

</details>

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 9 7950X3D 16-Core Processor (32 x 4853)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|1, 0, 0|
|Memory (System)|61.93GB (57.48GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|gnome|
|XDG_CURRENT_DESKTOP|GNOME|
|XDG_SESSION_DESKTOP|gnome|
|XDG_SESSION_TYPE|wayland|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
live-server|ms-|0.5.2023072001

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythontb:30258533
pythonptprofiler:30281269
vsdfh931:30280409
vshan820:30294714
vscod805:30301674
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30404738
py29gd2263:30784851
vsclangdf:30492506
c4g48928:30535728
dsvsc012:30540252
pynewext54:30618038
vscrpc:30624061
2i9eh265:30646982
showlangstatbar:30737417
ecj1e332:30687743
pythonfmttext:30716741
pythoncmvfstr:30726892
fixshowwlkth:30771523
hideindicator:30766887
pythongtdpath:30726887
i26e3531:30792625
gsofa:30797620
welcomedialog:30800244
pythonnosmt12:30779711
pythonidxpt:30768918
pythonnoceb:30776497
copilotsettingt:30767686
e537b577:30772214
h0f32768:30792099
asynctokenver:30799129
dsvsc013:30777762
dsvsc014:30777825
diffeditorv2:30786206

```

</details>

**Comment by SoMuchForSubtlety** [comment]
Is there any way I can help debug this?

**Comment by rzhao271** [comment]
Hi, I'm unable to confirm your issue.

I installed the latest code-insiders package using yum and verified that I could set the value of the `editor.fontSize` setting in the Settings editor under the User tab to `sans-serif`, then `serif`, and then reset the setting to get it back.

1. Are there workspace or folder-specific settings that set the editor font to an invalid font?
2. Can you try setting the `editor.fontSize` setting to just `sans-serif` or just `serif`, and seeing whether that changes the editor font? If it does, then I wonder whether the font is missing or whether VS Code is unable to detect the installed font?

**Comment by SoMuchForSubtlety** [comment]
>     1. Are there workspace or folder-specific settings that set the editor font to an invalid font?

There are no overrides, this also happens in a new blank workspace.

>     2. Can you try setting the `editor.fontSize` setting to just `sans-serif` or just `serif`, and seeing whether that changes the editor font? If it does, then I wonder whether the font is missing or whether VS Code is unable to detect the installed font?

Setting `editor.fontFamily` to `serif` and `sans-serif` works, but referencing fonts I have installed by name has no effect.

The font is definitely there and works with other programs
```
$ fc-list | grep "/usr/share/fonts/jetbrains-mono-fonts/"
/usr/share/fonts/jetbrains-mono-fonts/JetBrainsMono-ExtraLightItalic.otf: JetBrains Mono,JetBrains Mono ExtraLight:style=ExtraLight Italic,Italic
/usr/share/fonts/jetbrains-mono-fonts/JetBrainsMono-ExtraBoldItalic.otf: JetBrains Mono,JetBrains Mono ExtraBold:style=ExtraBold Italic,Italic
/usr/share/fonts/jetbrains-mono-fonts/JetBrainsMono-BoldItalic.otf: JetBrains Mono:style=Bold Italic
/usr/share/fonts/jetbrains-mono-fonts/JetBrainsMono-MediumItalic.otf: JetBrains Mono,JetBrains Mono Medium:style=Medium Italic,Italic
/usr/share/fonts/jetbrains-mono-fonts/JetBrainsMono-LightItalic.otf: JetBrains Mono,JetBrains Mono Light:style=Light Italic,Italic
/usr/share/fonts/jetbrains-mono-fonts/JetBrainsMono-Regular.otf: JetBrains Mono:style=Regular
/usr/share/fonts/jetbrains-mono-fonts/JetBrainsMono-ExtraBold.otf: JetBrains Mono,JetBrains Mono ExtraBold:style=ExtraBold,Regular
/usr/share/fonts/jetbrains-mono-fonts/JetBrainsMono-Light.otf: JetBrains Mono,JetBrains Mono Light:style=Light,Regular
/usr/share/fonts/jetbrains-mono-fonts/JetBrainsMono-Bold.otf: JetBrains Mono:style=Bold
/usr/share/fonts/jetbrains-mono-fonts/JetBrainsMono-ExtraLight.otf: JetBrains Mono,JetBrains Mono ExtraLight:style=ExtraLight,Regular
/usr/share/fonts/jetbrains-mono-fonts/JetBrainsMono-Thin.otf: JetBrains Mono,JetBrains Mono Thin:style=Thin,Regular
/usr/share/fonts/jetbrains-mono-fonts/JetBrainsMono-ThinItalic.otf: JetBrains Mono,JetBrains Mono Thin:style=Thin Italic,Italic
/usr/share/fonts/jetbrains-mono-fonts/JetBrainsMono-SemiBoldItalic.otf: JetBrains Mono,JetBrains Mono SemiBold:style=SemiBold Italic,Italic
/usr/share/fonts/jetbrains-mono-fonts/JetBrainsMono-Italic.otf: JetBrains Mono:style=Italic
/usr/share/fonts/jetbrains-mono-fonts/JetBrainsMono-SemiBold.otf: JetBrains Mono,JetBrains Mono SemiBold:style=SemiBold,Regular
/usr/share/fonts/jetbrains-mono-fonts/JetBrainsMono-Medium.otf: JetBrains Mono,JetBrains Mono Medium:style=Medium,Regular
```

**Comment by rzhao271** [comment]
I'm still unable to repro the issue.
I downloaded JetBrains Mono and placed the regular font in `/usr/share/fonts/jetbrainsmono/JetBrainsMono-Regular.ttf`, opened the latest code-insiders, and changed the font setting to `'JetBrains Mono', 'Droid Sans Mono', 'monospace', monospace`. I then noticed that the font changed in an untitled text file.
I got code-insiders through dnf.

Running the "Help: About" command I see that I'm on version 1.83.0-insider commit 5a400e5, though I seem to be on an older OS install: Linux x64 6.2.9-300.fc38.x86_64.

**Comment by SoMuchForSubtlety** [comment]
I tested this again with code-insiders 1.82, and it looks like it works there now. Using the exact same settings with code 1.81.1 does not work.

![image](https://github.com/microsoft/vscode/assets/15961647/d506e583-9f0e-4c54-82c3-3d3be5db8fbe)

When I tested this initially, I was using code-insiders 1.81. Was there a change with 1.82 that could have fixed this?

**Comment by rzhao271** [comment]
If the settings and extensions are the same, then it might have to do with the user data dir.
You can try deleting or moving all the folders listed under [Clean uninstall](https://code.visualstudio.com/docs/setup/uninstall#_clean-uninstall).

**Comment by SoMuchForSubtlety** [comment]
A clean reinstall did the trick, thanks.
