### ISSUE TITLE
Multiline object previews in console

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#18937]
In #17333 this was fixed for object prop names, but I think it needs to be fixed for object previews as well.

![image](https://cloud.githubusercontent.com/assets/323878/22162437/9777ce0c-df03-11e6-9c23-8c8e8fee11f9.png)

**Comment by isidorn** [comment]
To verify:

1. Check the case specified above
2. Check if long string are nicely shown in the repl
3. Check if whitespace characters are replaced where it makes sense and that the size preserved for such elements is always appropriate
