### ISSUE TITLE
Cursor and typed words does not match positions in the editor

### ISSUE THREAD

**Issue by johncruise** [Microsoft/vscode#18932]
The latest updates of VS Code insider (version information below) is behaving very badly with the cursor position and what is being typed in.  There were no new extensions downloaded before this happened.  A restart after the vscode update showed this bug right away.

![croppercapture 1](https://cloud.githubusercontent.com/assets/135095/22162067/dfb0d58a-df01-11e6-8288-1f0f50251d74.Gif)

- VSCode Version: Code - Insiders 1.9.0-insider (ee9d91c05fa571de56c41383cceee30b05b0a2f6, 2017-01-20T15:08:19.064Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions:

|Extension|Author|Version|
|---|---|---|
|Bookmarks|alefragnani|0.10.2|
|vscode-instant-markdown|dbankier|0.2.1|
|python|donjayamanne|0.5.6|
|xml|DotJoshJohnson|1.7.0|
|live-html-previewer|hdg|0.0.1|
|vscode-todo|MattiasPernhult|0.8.0|
|vscode-apache|mrmlnc|1.1.0|
|cpptools|ms-vscode|0.9.3|
|code-settings-sync|Shan|2.4.2|
|guides|spywhere|0.6.1|

---

Steps to Reproduce:

1. Download vscode insider per version above.
2. Start typing or selecting or deleting.
2.

**Comment by rebornix** [comment]
@johncruise are you seeing this with latest version? I didn't reproduce this and seems the one you are using is kind of old.

**Comment by alexandrudima** [comment]
@johncruise Can you please include here all the settings you have configured?

**Comment by mathiasvr** [comment]
I have a similar problem after updating to v1.9.0.
My temporary fix is to disable font ligatures as suggested by @scatcher, but it would be nice to have it work again.

**Comment by alexandrudima** [comment]
This should work (already in the 1.10 stable release)
