### ISSUE TITLE
Align macOS run recent command keybinding with others

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#189340]
ATM, `ctrl+r` is used for mac. We should go with `cmd+r` per the suggestion of @jooyoungseo to reduce cognitive burden

**Comment by DonJayamanne** [comment]
I'm not sure whether this applies to terminals or regular command palette.
Perhaps some instructions are required here.

**Comment by rzhao271** [comment]
Verified by enabling the accessibility support setting, running a few commands in a terminal, and pressing cmd+r to pull up the quick pick.
