### ISSUE TITLE
Markdown preview doesn't honor editor font-size (or have a way to bump up its font size) 

### ISSUE THREAD

**Issue by eamodio** [Microsoft/vscode#18935]
- VSCode Version: `1.9.0-insider` ee9d91c05fa571de56c41383cceee30b05b0a2f6
- OS Version: macOS Sierra `10.12.2`

Steps to Reproduce:

1. Change the font-size in settings
2. Open markdown preview -- it is unaffected

**Comment by mjbvz** [comment]
The preview does not use the `editor.fontSize`. We have another setting called `markdown.preview.fontSize` for adjusting this. Please give it a try and let me know if you run into any problems

Thanks
