### ISSUE TITLE
SQLite: use `VACUUM` to reduce DBs sizes from unused data

### ISSUE THREAD

**Issue by SimonSiefke** [microsoft/vscode#189352]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.80.2
- OS Version: Ubuntu 23.04

## Steps to Reproduce:

1. Open the VSCode workspace storage folder (`~/.config/Code/User/workspaceStorage`)
2. Locate the largest of the folders (e.g. `~/.config/Code/User/workspaceStorage/4353aa36f371150f91d45ebca3f74f06`)
3. Compare the database size to its content size, for example

```
sqlite3 -json ./state.vscdb "select * from ItemTable" > out.json && wc -c ./out.json && wc -c ./state.vscdb
85290 ./out.json
774144 ./state.vscdb // 900% larger 
```

4. Notice that the database size (`state.vscdb`) is much larger than the database content size (`out.json`)

## Example workspace data

This is the workspace data above: `85 kB` of content stored,  `774 kB` database size. 

[workspace-data.zip](https://github.com/microsoft/vscode/files/12221810/workspace-data.zip)

## Expected behaviour

The workspace storage database size is equal or similar to workspace storage content size.

## Actual behaviour

The workspace storage database is sometimes more than 900% larger than workspace storage content size. I'm not exactly sure why there would be so much extra data.

**Comment by bpasero** [comment]
This is currently expected, because we do not use `VACUUM` command in SQLite and thus DBs just grow.

We tried to add that command, but it resulted in test failures: https://github.com/microsoft/vscode/issues/146280
