### ISSUE TITLE
Restart TS server command not available in PR diffs

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#189394]
![image](https://github.com/microsoft/vscode/assets/2193314/5d80d505-2427-4b5f-9182-7aef45a67b7f)

![image](https://github.com/microsoft/vscode/assets/2193314/7c5c38a5-039a-4f90-acb5-df4989f62af9)

**Comment by ctsstc** [comment]
It seems you have to be on a TS file, but it would be nice to be able to restart the TS server independent of any file or lack of file that you're on.

**Comment by Tyriar** [comment]
The restriction was added intentionally, I hit this rarely and it not being there for json a lot personally.

**Comment by ctsstc** [comment]
I guess my concern is that independent of what file I'm on I may have red tabs or errors throughout my codebase because the TS Language Server needs to be restarted, so hunting down a random ts file to restart the server seems odd in that scenario.

**Comment by mjbvz** [comment]
Duplicate of #201734
