### ISSUE TITLE
[Accessibility] Change command history default keybindings in terminal buffer on Windows to align with Mac

### ISSUE THREAD

**Issue by jooyoungseo** [microsoft/vscode#189358]
Type: <b>Feature Request</b>

I am educating blind folks how to use VSCode with screen readers. It is confusing to have two different keys. On Mac, Alt+Up/DownArrow are used in terminal buffer to navigate executed commands whereas Windows uses Ctrl+Up/DownArrow.

I suggest using Alt+Up/DownArrow on Windows by default to align with Mac keybindings. There will be another benefit of saving Ctrl+Up/DownArrow for Windows that will be described in a separate feature request.

VS Code version: Code - Insiders 1.81.0-insider (9800cf6dd6bf4634889d60720ef46a400f3a7298, 2023-07-28T12:08:04.472Z)
OS version: Windows_NT x64 10.0.22621
Modes:

**Comment by meganrogge** [comment]
To verify:
1. On Windows, with screen reader mode enabled, run some commands in the terminal.
2. Focus the accessible buffer (`alt+f2` or `ctrl/cmd+upArrow`)
3. Use `alt/option+up/down arrows` to move between commands.
