### ISSUE TITLE
Code Insiders linux arm64 doestn't have tunnel binary

### ISSUE THREAD

**Issue by Young-Lord** [microsoft/vscode#189383]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.81.0-insider
- OS Version: -

Steps to Reproduce:

1. Download arm64 linux favor Visual Studio Code [from the official website](https://code.visualstudio.com/insiders/)
2. tar xvf xxx.tar.gz
3. No code tunnel binary found
4. Remote Tunnel cannot be launched, with the following error message

```text
2023-08-01 14:31:40.225 [error] status error(undefined): + Error: spawn /opt/visual-studio-code-insiders/bin/code-tunnel-insiders ENOENT 
2023-08-01 14:31:40.231 [error] undefined
2023-08-01 14:31:57.278 [info] No authentication session available, not starting tunnel
```

**Comment by arvislacis** [comment]
@connor4312 Same problem also for the stable build and x64 architecture - https://code.visualstudio.com/#alt-downloads

**Comment by connor4312** [comment]
Yea, this was a thing for all stable Linux archives. The next stable build will have the binary.
