### ISSUE TITLE
[WelcomeUX] Better grouping for actions that customize experience

### ISSUE THREAD

**Issue by ramya-rao-a** [Microsoft/vscode#18944]
Testing #18091

The "Keyboard shortcuts" links takes you to the reference guide, but doesn't tell you how to change the keyboard binding.
There are 2 quicklinks about keyboard short cut, neither telling you how to change the keyboard binding.

How about having a new section called "Customize your VS Code" and add the below there
- Change Editor Theme
- Change Editor Settings
- Change Keyboard Bindings
- Map keyboard shortcuts to another editor's style

The Quick Links can have
- Interface Overview (which I'd rather name as "Visual Studio Code Overview". The current name is not intuitive)
- Reference guide for common keyboard shortcuts
- Show all commands
- Interactive playground

cc @bgashler1

**Comment by seanmcbreen** [comment]
I do actually think there could be some merit in this suggestion - but I think for now we should just go out with the flat list as we have today.  In part as we are a little short on time and I'd love to get more external feedback.  I did clean up (well in my mind) number of the titles so it's crisper around what to expect.
