### ISSUE TITLE
Downloading extension from GH: ms-vscode.js-debug@1.81.0 fault

### ISSUE THREAD

**Issue by weartist** [microsoft/vscode#189447]
Sorry this may not be a bug, but I'm having some trouble compiling vscode, and I thought it might be appropriate to mention an issue here, and if this shouldn't, I'm sorry and will close it

When I tried to run the latest vscode source code, I found that its precompile time was very long, and it looked like it had been waiting for download extension e.g.:
![image](https://github.com/microsoft/vscode/assets/17105034/69f57d82-19a9-45b3-a475-16b99c275cdd)

I tried to trace the code and found that three extensions need to be synchronized, then I open the downloaded path and find that there are only two, debug-js does not exist：
![image](https://github.com/microsoft/vscode/assets/17105034/3ee43014-3671-49f2-9921-393096d31e2a)

![image](https://github.com/microsoft/vscode/assets/17105034/3a02986b-20e5-43ca-b8dc-a19c6389a931)

Would appreciate if anyone knows what the problem was, or what might have gone wrong

**Comment by connor4312** [comment]
Looks like this is probably some kind of network issue between you and Github since the other two extensions downloaded sucessfully

**Comment by weartist** [comment]
> Looks like this is probably some kind of network issue between you and Github since the other two extensions downloaded sucessfully看起来这可能是您和 Github 之间的某种网络问题，因为其他两个扩展已成功下载



> Looks like this is probably some kind of network issue between you and Github since the other two extensions downloaded sucessfully

Strangely, it looks like fetch always makes mistakes when downloading this file, but my other programs are fine, even the other two extensions download normally 

![image](https://github.com/microsoft/vscode/assets/17105034/9f1b796d-6f59-42fc-9ce1-cc2f59e53bd2)

**Comment by weartist** [comment]
It was indeed my network issue, I adjusted the manual timeout abort a little longer, solved, the network is too poor
