### ISSUE TITLE
Cannot follow the troubleshoot steps for Using SSH keys

### ISSUE THREAD

**Issue by 2jiwon** [microsoft/vscode#189453]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.80.2
- OS Version: Windows10

Steps to Reproduce:

1. `icacls "privateKeyPath" /grant :R`
2. 

I am having a issue that cannot connect SSH without password only in VSCode and WSL2 environment.
So I tried to follow the troobleshooting as this page shows.
https://code.visualstudio.com/docs/remote/troubleshooting#_restrict-the-permissions-on-the-private-key-file

However, I am stuck at this step.  

```
For Windows, run the following command in powershell to grant explicit read access to your username:

icacls "privateKeyPath" /grant :R
```

While I was following the steps in this page, I met this error message.

```
PS C:\Users\ljw> New-Variable -Name Key -Value "\\wsl.localhost\Ubuntu-18.04\home\jiwon\.ssh\id_rsa"
PS C:\Users\ljw> icacls $Key /c /t /Inheritance:d
\\wsl.localhost\Ubuntu-18.04\home\jiwon\.ssh\id_rsa: 잘못된 기능입니다.
0 파일을 처리했으며 1 파일은 처리하지 못했습니다.
```

In this page, it says the key file's location would be like this, for example` C:\Users\your-user\.ssh\id_ed25519.pub.  `
However, in WSL2, the location is totally different.
The location I can find is like `\\wsl.localhost\Ubuntu-18.04\home\jiwon.ssh\id_rsa` , and it doesn't work If I use this path.  
Also, I cannot find 'Security' tab when I right clicked on the key file as the page says as below.  
```
Then navigate to the private key file in Windows Explorer, right click and select properties.   
Click the security tab -> Advanced -> Disable Inherited -> remove all inherited permissions.
```
The file only has 3 tabs, General, Details, Previous version. So that I cannot follow those steps either.

**Comment by roblourens** [comment]
For keys in WSL, I think you will need to operate on them in WSL and not by running powershell commands. You would want to look up steps for linux instead.
