### ISSUE TITLE
[WelcomeUX] Interactive Playground: Click on File explorer, recent file opens

### ISSUE THREAD

**Issue by ramya-rao-a** [Microsoft/vscode#18945]
Testing #18091

- Open the interactive playground
- Click on the icons in the side bar (Git, extensions, search, .. explorer)
- Notice that when you click on explorer, 
   - if no other file is open, then previously most recent opened file opens in a new editor.
   - if there was an editor with a file open, then that editor becomes the active editor

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/7024
