### ISSUE TITLE
Saved searches for 'Search and Replace' Tab (Ctrl+H)

### ISSUE THREAD

**Issue by AaronRoyan** [microsoft/vscode#189451]
Sometimes we have to keep copying and pasting replacements for code or text
if we have like a second drop-down like how we have for stashes in the git source control, to have old or saved changes.
Cause sometimes we forget regex but if we saved it, it would most definitely save time!

**Comment by andreamah** [comment]
To reduce bloat in the search viewlet tablet, we probably wouldn't add something like "starred searches". However, you could do the following:

1. Use the `up` and `down` arrows to go through the history of your search. 
2. Assign a keybinding to `search.action.findInFiles` with the regex that you use often. 
3. Use the search editor to save queries and re-populate them into the editor.
