### ISSUE TITLE
Open Accessible Diff Viewer command always displayed in an open editor

### ISSUE THREAD

**Issue by gregvanl** [microsoft/vscode#189444]
- VS Code Version: 
- OS Version: 

Steps to Reproduce:

1. Open a Markdown file without pending changes and check the More Actions menu in the upper right of the editor.

The Open Accessible Diff Viewer command is visible. Selecting the command has no effect.

![image](https://github.com/microsoft/vscode/assets/12818376/bbbe7970-69a0-422a-861e-45a89ab9c136)

2. Open the Markdown preview for the file and check the More Actions menu.

The Open Accessible Diff Viewer command is visible.

![image](https://github.com/microsoft/vscode/assets/12818376/326a4bce-c12e-4a38-90bf-1d701d529f5b)

**Comment by hediet** [comment]
Thanks for finding this! I don't know how I missed this.

**Comment by hediet** [comment]
Fixed by https://github.com/microsoft/vscode/pull/189459 and https://github.com/microsoft/vscode/pull/189460
