### ISSUE TITLE
[WelcomeUX] When overlay appears, can we get a blank editor behind it?

### ISSUE THREAD

**Issue by ramya-rao-a** [Microsoft/vscode#18941]
Testing #18091 on OS X El Capitan

The text on the overlay fights for attention with the text under the overlay.
Usually when websites have overlays, the background is greyed out/blurred and the text on the overlay can be clearly read.

<img width="411" alt="screen shot 2017-01-20 at 11 20 22 am" src="https://cloud.githubusercontent.com/assets/16890566/22162660/6f43cfb6-df04-11e6-816e-087d020d6fa0.png">

**Comment by bgashler1** [comment]
We haven't implemented the new design for this, but it essentially does what you're describing.  It's coming :)
