### ISSUE TITLE
[WelcomeUX] Create new file should make the overlay disappear

### ISSUE THREAD

**Issue by ramya-rao-a** [Microsoft/vscode#18943]
Testing #18091 on OS X El Capitan

- Click on the interface overview and wait for the overlay to appear
- Use either the keyboard shortcut or the File menu to create a new file
- New file gets created and you can type there !! And overlay is still there too!

- Or use the command pallet to open a file (Cmd+P)
- The file opens and you can type!! And overlay is still there too!

**Comment by chrmarti** [comment]
Tracked with #18869
