### ISSUE TITLE
[WelcomeUX] Abbreviate user home directory?

### ISSUE THREAD

**Issue by bgashler1** [Microsoft/vscode#18950]
Testing #18091

Should we replace the users home directory path prefix for Recent files with `~/`? on Mac/Linux and `$\" or nothing on Windows?  Just an idea

**Comment by Tyriar** [comment]
Yeah this would be nice on linux/mac to save some space. It's not very common on Windows though.

**Comment by chrmarti** [comment]
The Recent menu already does that.
