### ISSUE TITLE
Integrated Terminal with Fish shell - Line wrapping ignored when copy-pasting long commands

### ISSUE THREAD

**Issue by sabishiii** [microsoft/vscode#189566]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.80.2
- OS Version: Up-to-date ArchLinux
- Fish Version: 3.6.1

Steps to Reproduce:

1. Open the VSCode integrated shell with Fish and type a long command that requires line wrapping
2. Copy-paste the line-wrapped command into the editor - the line wraps will be treated as newlines. This breaks copy-pasting of commands to other shells or systems
This issue is reproducible with and without the Shell Integration feature
![integrated_terminal_fish_line_wrap](https://github.com/microsoft/vscode/assets/36694953/f29205ba-744c-4499-85b2-57064efd17e0)

**Comment by meganrogge** [comment]
can reproduce the issue, but there's a nice workaround: use this context menu action


![Image](https://github.com/microsoft/vscode/assets/29464607/1f2fde25-b36a-4901-9c97-df3913a8ac11)

**Comment by moffatman** [comment]
You have to go all the way to click on the little dot to use that. It's a lot easier to double triple click anywhere in the line and use keyboard shortcut to copy. I hope this could be re-opened and fixed :+1:
