### ISSUE TITLE
No quick shortcut to open git repository

### ISSUE THREAD

**Issue by timheuer** [microsoft/vscode#189521]
Type: <b>Bug</b>

When working with a workspace that is a git/github respository there is no quick way to get to the repo URL. Tons of links for PRs, etc. but no link to just "Open on GitHub" quickly.

VS Code version: Code - Insiders 1.81.0-insider (6445d93c81ebe42c4cbd7a60712e0b17d9463e97, 2023-08-02T12:36:29.806Z)
OS version: Windows_NT x64 10.0.22621
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 9 3900X 12-Core Processor             (24 x 3793)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|127.92GB (82.20GB free)|
|Process Argv|--crash-reporter-id 74df45a5-f7a7-4adf-9c39-530910c9f1e2|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (74)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|3.0.2
tsl-problem-matcher|amo|0.6.2
npm-intellisense|chr|1.4.4
path-intellisense|chr|2.8.4
esbuild-problem-matchers|con|0.0.2
vscode-markdownlint|Dav|0.51.0
vscode-eslint|dba|2.4.2
npm-browser|den|1.1.4
vsc-material-theme-icons|equ|2.8.0
azure-storage-explorer|for|0.1.2
codespaces|Git|1.14.14
copilot|Git|1.100.306
copilot-chat|Git|0.7.2023072802
remotehub|Git|0.60.0
vscode-github-actions|git|0.25.8
vscode-pull-request-github|Git|0.70.0
rest-client|hum|0.25.1
svg|joc|1.5.3
fluent-icons|mig|0.0.18
dotenv|mik|1.0.1
lipsum-generator|MrA|1.2.3
language-gettext|mro|0.2.2
azure-pipelines|ms-|1.208.0
azure-dev|ms-|0.7.0
vscode-azureappservice|ms-|0.25.0
vscode-azurecontainerapps|ms-|0.5.1
vscode-azurefunctions|ms-|1.12.2
vscode-azureresourcegroups|ms-|0.7.5
vscode-azurestaticwebapps|ms-|0.12.2
vscode-azurestorage|ms-|0.15.3
vscode-azurevirtualmachines|ms-|0.6.5
vscode-bicep|ms-|0.20.4
vscode-cosmosdb|ms-|0.19.4
vscode-docker|ms-|1.26.0
extension-manifest-editor|ms-|0.1.5
csdevkit|ms-|0.4.2
csharp|ms-|2.0.320
dotnet-maui|ms-|0.2.12
vscode-dotnet-pack|ms-|1.0.12
vscode-dotnet-runtime|ms-|1.6.0
vscode-dotnet-sdk|ms-|0.8.0
vscodeintellicode-csharp|ms-|0.1.26
aks-devx-tools|ms-|0.1.2
vscode-aks-tools|ms-|1.3.13
vscode-kubernetes-tools|ms-|1.3.13
playwright|ms-|1.0.15
python|ms-|2023.12.0
jupyter|ms-|2023.7.1002162226
remote-containers|ms-|0.305.0
remote-wsl|ms-|0.80.2
azure-account|ms-|0.11.5
azure-repos|ms-|0.36.0
azurecli|ms-|0.5.0
cpptools|ms-|1.17.0
powershell|ms-|2023.6.0
remote-repositories|ms-|0.38.1
azurerm-vscode-tools|msa|0.15.10
vscode-jest|Ort|5.2.3
vscode-versionlens|pfl|1.5.0
material-icon-theme|PKi|4.29.0
quicktype|qui|12.0.46
vscode-thunder-client|ran|2.10.0
vscode-yaml|red|1.14.0
vscode-marketplace-preview|rob|1.5.0
ghost-ai|sav|0.0.13
code-spell-checker|str|2.20.5
base-ext-sample|Tim|0.0.11
dotnet-containerizer|Tim|0.0.21
mympclient|tim|0.1.6
resx-editor|tim|0.2.21
es6-string-html|Tob|2.12.1
application-insights|Vis|0.4.2
vscode-icons|vsc|12.4.0
cron-tasks|zok|0.1.2

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythontb:30258533
pythonptprofiler:30281269
vshan820:30294714
vscod805:30301674
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30404738
py29gd2263:30784851
vsclangdf:30492506
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30618038
showlangstatbar:30737417
24365598:30687740
pythonfmttext:30716741
pythoncmvfstr:30726892
fixshowwlkth:30771523
showindicator:30805243
pythongtdpath:30726887
i26e3531:30792625
gsofa:30797620
pythonnosmt12:30779711
pythonidxpt:30768918
pythonnoceb:30776497
copilotsettingt:30767686
e537b577:30772214
h0f32768:30792099
asynctokenver:30799129
dsvsc013:30777762
dsvsc014:30777825
diffeditorv2:30786206

```

</details>

**Comment by gjsjohnmurray** [comment]
https://marketplace.visualstudio.com/items?itemName=antfu.open-in-github-button by @antfu adds a clickable Status Bar panel to do this. The extension installs https://marketplace.visualstudio.com/items?itemName=fabiospampinato.vscode-open-in-github which @fabiospampinato created, and it's that which actually launches the repo page in your external browser.

Other extensions are available but I haven't tried them.

**Comment by lszomoru** [comment]
@joyceerhl, would it make sense to add an action to the "Share" menu for this?

**Comment by joyceerhl** [comment]
You can click on the status bar item and select Open on GitHub for the main branch to do this: 
<img width="749" alt="image" src="https://github.com/microsoft/vscode/assets/30305945/f116501a-33bc-48aa-92fb-d54acf72213c">
