### ISSUE TITLE
Debug Console not displaying text

### ISSUE THREAD

**Issue by WorikQCI** [microsoft/vscode#189592]
```
Version: 1.81.0 (Universal)
Commit: 6445d93c81ebe42c4cbd7a60712e0b17d9463e97
Date: 2023-08-02T12:40:02.782Z
Electron: 22.3.18
ElectronBuildId: 22689846
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Darwin arm64 22.5.0
```

Does happen with all extensions disabled 
Steps to Reproduce:

1. Debugging a Flutter programme
```json
{
            "name": "thenameichoose",
            "request": "launch",
            "type": "dart",
            "flutterMode": "debug",
            "args": [
                "-d",
                "chrome"
            ],
            "toolArgs": [
                "--dart-define",
                "WEB=Encapsulation"
            ]
        },
```

Make a break point on a function where there is a variable in scope with a long string.
In my case 5252495 characters: `dataStr`

Inspect that variable in Debug consloe
`> dataStr`
This kills the console.  The variable name appears, but there is no data displayed

E.g:  Enter `> 1 + 2` in the debug console and nothing is displayed

Clear the console 

Enter `> 1 + 2` in the debug console and it is working again: can see:

```
1 + 2
3
```

**Comment by roblourens** [comment]
Likely this just leads to the DA trying to send a huge amount of data back the vscode, and that's probably going to cause issues. js-debug limits the output size to 100000 characters and that seems slow but usable. We could try to set a limit on the frontend, but it might be better for the DA to do this, like js-debug, to avoid having to pass the data around at all? I'd recommend filing an issue for the Dart extension then.
