### ISSUE TITLE
Editor selection jitters every 2nd character selected

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#18954]
- VSCode Version: Code - Insiders 1.9.0-insider (39d761bf1f4ce7ea605539bdba41a8727b3c7ce0, 2017-01-18T07:21:35.814Z)
- OS Version: Linux x64 4.8.0-34-generic
- Extensions:

|Extension|Author|Version|
|---|---|---|
|EditorConfig|EditorConfig|0.3.4|
|lorem-ipsum|Tyriar|1.0.0|
|theme-glacier|Tyriar|0.0.10|
|theme-material-neutral|bernardodsanderson|0.9.0|
|vscode-svgviewer|cssho|1.3.0|
|python|donjayamanne|0.5.6|
|gitlens|eamodio|1.4.3|
|tslint|eg2|0.8.1|
|git-project-manager|felipecaputo|1.0.1|
|vsc-travis-ci-status|felixrieseberg|1.0.5|
|md-navigate|jrieken|0.0.1|
|vscode-scss|mrmlnc|0.6.0|
|csharp|ms-vscode|1.6.2|
|seti-icons|qinjia|0.1.3|
|java|redhat|0.0.9|
|annotator|ryu1kn|0.10.1|

---

Notice the right-side of the selection differs by 1px, this 1px jump happens whenever the selection grows/reduces. Probably a rounding error?

![image](https://cloud.githubusercontent.com/assets/2193314/22160720/bb9f19aa-defb-11e6-8c12-406017b1c439.png)

![image](https://cloud.githubusercontent.com/assets/2193314/22160731/cc00b416-defb-11e6-9a95-cc666a4cf4a5.png)

**Comment by alexandrudima** [comment]
@Tyriar: Can you please share your settings?

**Comment by Tyriar** [comment]
```js
{
  "editor.autoClosingBrackets": false,
  "editor.fontFamily": "Hack",
  "editor.renderWhitespace": "boundary",
  "editor.renderIndentGuides": true,
  "editor.roundedSelection": false,
  "editor.rulers": [ 80, 100, 120 ],
  "explorer.autoReveal": false,
  "explorer.openEditors.visible": 0,
  "extensions.autoUpdate": true,
  "workbench.editor.enablePreviewFromQuickOpen": false,
  "workbench.editor.showTabs": true,
  "terminal.integrated.scrollback": 4000,
  "terminal.integrated.lineHeight": 1.2,
  
  // Extensions
  "gitlens.codeLens.visibility": "off",
  "gitProjectManager.baseProjectsFolders": [
    "$HOME/dev",
    "%USERPROFILE%\\Documents\\dev"
  ],

"gitProjectManager.maxDepthRecursion": 2,
"typescript.check.tscVersion": false,
"window.zoomLevel": 0,
"editor.wordWrap": true,
"typescript.check.workspaceVersion": false
}
```

**Comment by Tyriar** [comment]
This appears to be a regression from 1.8.1 and it's quite distracting. It also appears to happen on the matching selection highlights:

![jitter](https://cloud.githubusercontent.com/assets/2193314/22168511/f27f5752-df21-11e6-87d7-7a43b125597b.gif)

**Comment by alexandrudima** [comment]
Very nice find, thank you!

**Comment by Tyriar** [comment]
Thanks for the quick fix :smile:
