### ISSUE TITLE
Walkthrough images are being duplicated

### ISSUE THREAD

**Issue by angelasu97** [microsoft/vscode#189518]
Does this issue occur when all extensions are disabled?: No

- VS Code Version: 1.80.2 ([June 2023 Recovery 2](https://github.com/microsoft/vscode/releases/tag/1.80.2))
- OS Version: Windows 11

https://github.com/microsoft/vscode/assets/56371631/dcf04d38-93b4-4f3d-ae09-6040638305e0

Steps to Reproduce:

1. Open up an extension walkthrough with the same media image across all steps.
2. Clicking on the next step or re-clicking any of the steps duplicates the image.
3. Dragging the bar at the bottom seems to reset the duplicate images.

**Comment by bhavyaus** [comment]
This has been resoloved in the most recent release.
