### ISSUE TITLE
Cannot hide the new top bar (command center)

### ISSUE THREAD

**Issue by alesmenzel** [microsoft/vscode#189532]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: Latest
- OS Version: MacOS Latest

**Steps to Reproduce:**

I have already disabled the following

```js
"window.commandCenter": false,
"workbench.layoutControl.enabled": false,
```

but I still have an empty top bar taking space in fullscreen mode, whereas before this change I could have removed the topbar completely.

Before 😆 
<img width="1439" alt="Screenshot 2023-08-03 at 10 13 57" src="https://github.com/microsoft/vscode/assets/8976542/07682f89-381b-44c9-8628-8c6aaf8495ae">

After 😢 
<img width="1439" alt="Screenshot 2023-08-03 at 10 13 32" src="https://github.com/microsoft/vscode/assets/8976542/94d5506a-e5d5-423f-b857-ae2b362ba7fd">

Similar issue: #166295 @daviddossett

**Comment by alesmenzel** [comment]
Workaround: It seems to be fixed once I exit/enter the fullscreen mode again.

**Comment by daviddossett** [comment]
To clarify--this is the issue you're running into?

https://github.com/microsoft/vscode/assets/25163139/66bbab43-0979-4e56-ae20-41fd8fb4da90

**Comment by srdjan-medjo** [comment]
@daviddossett actually that worked, how to go outside of fullscreen and now in fullscreen it correctly disappears. Cheers ;)

**Comment by daviddossett** [comment]
Yeah, I don't think this is intentional but just wanted to confirm the issue.
