### ISSUE TITLE
Prompts aren't focused for keyboard selection.

### ISSUE THREAD

**Issue by JarvisPrestidge** [Microsoft/vscode#18953]
- VSCode Version: 1.8.1
- OS Version: Windows 10 Pro

The default behaviour is for the focus is to remain on the editor and not move to the prompt for easy selection using the keyboard (i.e. left & right arrow keys). This forces users to have to reach for their mouse.

Example:
![Alt Text](http://i.imgur.com/7kvh9ta.png "grr")

Steps to Reproduce:

1. Do anything that causes a prompt to be displayed (i.e. try to run a task without terminating an existing task)
2. Result, focus returns to the text editor view and not to the prompt.

This would be really great if this could be implemented and I don't think anyone would disapprove.

**Comment by bpasero** [comment]
@JarvisPrestidge you mean prompts like these?

![image](https://cloud.githubusercontent.com/assets/900690/22175677/22398584-dffa-11e6-9828-83b2f6d35d85.png)

**Comment by JarvisPrestidge** [comment]
Prompts such as these: 

![Alt Text](http://i.imgur.com/7kvh9ta.png "grr")

**Comment by bpasero** [comment]
@JarvisPrestidge this is really intended because there can be many messages and we do not want to distract the user by taking focus away. You can chose to ignore the message and continue typing.

Now, for keyboard access, see https://github.com/Microsoft/vscode/issues/5538
