### ISSUE TITLE
OmniSharp gone, F12 in VSCode no longer works

### ISSUE THREAD

**Issue by simongidney** [microsoft/vscode#189539]
Type: <b>Bug</b>

Launch VSCode in the same manner as every time in the last several years.
Notice that OmniSharp has been replace by Language Server.
Realise that your ASP.NET (Web Forms, CLR4, .NET 4.8) solutions are unlikely to work in this new LSP world and you'll need to revert back to VS again.
Realise that even the most basic 'Go To Definition' stuff doesn't even work, even in plain vanilla C# projects and no amount of restart language server (like restart omni) will make it work.
Experiment with 'Switch to use the Omnisharp server' option.
Look at clock and realise your deadline is looming and real work needs to happen.
Give up and just use Visual Studio again and all the pain that involves.

VS Code version: Code 1.80.2 (2ccd690cbff1569e4a83d7c43d45101f817401dc, 2023-07-27T20:40:28.909Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|13.4.1
path-intellisense|chr|2.8.4
todo-tree|Gru|0.0.226
csdevkit|ms-|0.3.21
csharp|ms-|2.0.320
vscode-dotnet-runtime|ms-|1.6.0
vscode-edge-devtools|ms-|2.1.3
remote-ssh|ms-|0.102.0
remote-ssh-edit|ms-|0.86.0
remote-explorer|ms-|0.4.1
debugger-for-edge|msj|1.0.15
svelte-vscode|sve|107.9.0

</details>

**Comment by NCLnclNCL** [comment]
Use 1.2.6.x version

**Comment by RoboPhred** [comment]
Same issue.  No C# functionality at all.  No references, no navigation, no intellisense, most syntax tokens remain unhighlighted, no errors indicated.  All the .net logs in the output tab are completely empty.  I can't find any sign that vscode is even recognizing the language beyond the "C#" in the current language status indication.

This is the case for every C# project I try.  The projects I work with are on github, but unfortunately require shared libraries from a game plus a few third party mods so it is not the best reproduction example.
Just in case, here's one of them
https://github.com/RoboPhred/autoccultist

**Comment by RoboPhred** [comment]
I had the same issue.  It seems all of those features have moved into the "C# Dev Kit" extension.  I did not try the omnisharp server option, but installing the dev kit extension got everything working again.
