### ISSUE TITLE
The size of the breakpoint is too small.

### ISSUE THREAD

**Issue by wiltchamberian** [microsoft/vscode#189527]
The size of the breakpoint of vscode is too small. I commit a bug report for it but someone reply:
"Sorry, but it's already most of the height of the line. A theme with better color contrast, or zooming in, might help you?"
I don't think it is already most of the height of the line. And logically it is obvious not because, when I open vscode and visual studio both, and make the size of the text the same, obviously the size of the breakpoint of the visual studio is bigger than vscode.

**Comment by gjsjohnmurray** [comment]
> I commit a bug report for it but

Please reference that issue. If you include the pound/hash prefix on the number when you put it in your reply GitHub will create a clickable link to it.

**Comment by roblourens** [comment]
Will merge this into https://github.com/microsoft/vscode/issues/177221
