### ISSUE TITLE
New tasks.json variable request for re-running tasks.

### ISSUE THREAD

**Issue by JarvisPrestidge** [Microsoft/vscode#18957]
- VSCode Version: 1.8.1
- OS Version: Windows 10 pro

Feature request: essentially an additional boolean variable supported in the tasks.json file which when set would stop vscode from prompting you to terminate an existing task (see below) when trying to re-run a task. 

![Alt Text](http://i.imgur.com/7kvh9ta.png "grr")
Instead running a new task while another still exists would first terminate the existing, then cleanly run the new without presenting a jarring prompt.

Reasoning: I would like to be able to re-run a task without first terminating it, or being forced through this prompt.

**Comment by alexr00** [comment]
Covered by this issue: #32264
