### ISSUE TITLE
Task auto-run conflicts with task reconnection

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#189504]
- Open the vscode-copilot repo, the build task auto-runs
- Reload the window
- The previous instance is reconnected to, and also the auto-run apparently kicks in, now I have two instances running

<img width="305" alt="image" src="https://github.com/microsoft/vscode/assets/323878/120d8b78-8353-40e8-9706-8430bf953a54">

I would guess that the task auto-run doesn't check whether the task was reconnected to. Sometimes instead I get an error notification, something like "this task is already running". Will grab a screenshot next time.

**Comment by meganrogge** [comment]
same as / a way to repro #188806

let's track this there
