### ISSUE TITLE
Cannot read properties of null (reading 'command')

### ISSUE THREAD

**Issue by CoderJason123** [microsoft/vscode#189570]
Does this issue occur when all extensions are disabled?: Yes/No

Version: 1.80.2
Commit: 2ccd690cbff1569e4a83d7c43d45101f817401dc
Date: 2023-07-27T20:57:59.134Z
Electron: 22.3.14
ElectronBuildId: 22695494
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Darwin arm64 22.5.0
Steps to Reproduce:

1. Create a blazor hosted web assembly app.
2. Try to run it.

This error message pops up when you try to run the app, the browser will no longer open.  I've disabled all extensions, cleared any caches from vs code, reinstalled vs code, added all extensions back.  I can successfully run console apps, but i can't start and debug a blazor wasm app.

If there's a way to find the source of this message, that might help.  I've looked through every single log.

Assistance appreciated.

**Comment by roblourens** [comment]
Assuming you are running a launch config for the blazor app, please file this on the C# extension repo

**Comment by CoderJason123** [comment]
@roblourens  sorry, you are correct, will do.
