### ISSUE TITLE
Multiple search in multiple files

### ISSUE THREAD

**Issue by Vih6460** [microsoft/vscode#189554]
Type: <b>Feature Request</b>

Would be nice if we can put more than one word on the finder in multiples files. Let me give an example, I have a lot of files on the folder of my project and I need to find the files who match with two words independents, but today I can find just per one word, and do it in a thousand of files is impracticable

VS Code version: Code 1.80.2 (2ccd690cbff1569e4a83d7c43d45101f817401dc, 2023-07-27T20:40:28.909Z)
OS version: Windows_NT x64 10.0.19045
Modes:

**Comment by andreamah** [comment]
Sorry, I don't think I really understand. Can you give an example?
