### ISSUE TITLE
"jump to bracket" doesn't scroll to reveal cursor

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#18956]
- Have a file with some matched brackets:

```
function foo() {

}
```

- Scroll so that one bracket is out of the viewport
- Put the cursor on the other bracket and press cmd+shift+\

The cursor goes to the other bracket out of the viewport, but the editor doesn't scroll to bring it into the viewport. If I press an arrow key, then it's revealed.

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/18540
