### ISSUE TITLE
[WelcomeUX] Welcome page should not show up when files are restored

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#18955]
Testing #18091 

1. Open a folder and files:

  ![image](https://cloud.githubusercontent.com/assets/2193314/22168016/c96741b6-df1e-11e6-9b7f-e441d3b233c3.png)

2. Close VS Code
3. Relaunch and the welcome page steal focus
 
  ![image](https://cloud.githubusercontent.com/assets/2193314/22168027/df31331c-df1e-11e6-8002-b239045d33d6.png)

**Comment by bgashler1** [comment]
Agreed, handing off for the logic to get implemented.

**Comment by chrmarti** [comment]
@bgashler1 The checkbox currently refers to 'startup' without qualification. How can we make this easy to understand? Should we just check if any files are open and not open the Welcome page in that case? Would appreciate your thoughts on this.

**Comment by bgashler1** [comment]
Hmmm... I'm not sure.  I wouldn't expect it to pop up being an experienced user, but I'm not sure about new users.  My gut tells me we should only show it for new sessions (i.e. if you open a workspace, it won't come back until you close that workspace).  Not sure how the rest of everyone feels.

**Comment by Tyriar** [comment]
If it shows when you restore a folder it would be annoying and people would turn it off, if you kept it to only on new windows that were not restored then it would still be useful and non-intrusive.

**Comment by bpasero** [comment]
I think the fix is still not good, when I have a dirty untitled file open, the welcome just takes over.

**Comment by chrmarti** [comment]
This was fixed with #19492, available in 1.9.
