### ISSUE TITLE
Port forwarding is not working propertly, from a Tunnel in vscode.dev

### ISSUE THREAD

**Issue by aleleba** [microsoft/vscode#189513]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 
- OS Version: 

Attaching Issue on vscode-remote repo: https://github.com/microsoft/vscode-remote-release/issues/8771

**Comment by bamurtaugh** [comment]
Thanks for opening! Let's keep the discussion in https://github.com/microsoft/vscode-remote-release/issues/8771.
