### ISSUE TITLE
X11 primary buffer ignored after cut and paste of file in explorer

### ISSUE THREAD

**Issue by toppk** [microsoft/vscode#189536]
Does this issue occur when all extensions are disabled?: Yes

- Version: 1.80.2
- Commit: 2ccd690cbff1569e4a83d7c43d45101f817401dc
- Date: 2023-07-27T20:41:52.615Z
- Electron: 22.3.14
- ElectronBuildId: 22695494
- Chromium: 108.0.5359.215
- Node.js: 16.17.1
- V8: 10.8.168.25-electron.0
- OS: Linux x64 6.4.6-200.fc38.x86_64

Steps to Reproduce:

1.  Go to explorer (Ctrl-Shift-E)
2. select a file
3. make a copy of the file.  Ctrl-C + Ctrl-V
4. go into any file.
5.  highlight some text.   try to middle click paste (primary paste)
6. what is pasted is the original file name that was copied
7.  to clear the issue, select some text.  
8. Ctrl-C to copy it into the buffer.
9.  highlight some text.   try to middle click paste (primary paste)
10.  now the primary paste will work like normal

I think this is somewhat similar to [this](https://github.com/microsoft/vscode/issues/130208) issue, but it seems worse, because the only way to get primary buffer working again is to do a clipboard copy of text, and then load the primary buffer again.

**Comment by lramos15** [comment]
I believe this is already covered by 
https://github.com/microsoft/vscode/issues/167266
 and 
https://github.com/microsoft/vscode/issues/130208

**Comment by toppk** [comment]
this is a totally different symptom, although it might have the same root cause
