### ISSUE TITLE
Each time message to connect to synchronise the parameters

### ISSUE THREAD

**Issue by Jacques2101** [microsoft/vscode#189636]
- VS Code Version: 1.81.0 (Universal)
- OS Version: MacOS Ventura

Steps to Reproduce:
After launching VsCode I always have the message to connect to synchronise the parameters (cf picture). 
Each time I need to do that I don't know why ? 

<img width="1680" alt="Capture d’écran 2023-08-04 à 14 36 50" src="https://github.com/microsoft/vscode/assets/49912455/0045b395-0ab8-44bb-b260-0599103693ae">
<img width="1680" alt="Capture d’écran 2023-08-04 à 14 41 33" src="https://github.com/microsoft/vscode/assets/49912455/8e07aa82-557b-433b-8f93-21d78af416e8">

**Comment by roblourens** [comment]
Sorry, I don't know what that says in English, but I think it is saying that you can enable the "Settings Sync" service

**Comment by Jacques2101** [comment]
Hi,
Yes but each time I launch vscode. Isn’t it to much ?

Cordialement
________________________
Jacques Tebeka
Mobile : +33 6 28 69 19 01
