### ISSUE TITLE
Terminal find highlights aren't correct

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#189600]
See how only `pp` is highlighted for the search term `app`

<img width="577" alt="Screenshot 2023-08-03 at 7 40 08 pm" src="https://github.com/microsoft/vscode/assets/2193314/fbecec59-19e9-4249-bd7d-96abd8dbdcea">

**Comment by aiday-mar** [comment]
Verified on a couple of examples with gpu acceleration off.
