### ISSUE TITLE
Sticky scroll improve

### ISSUE THREAD

**Issue by andreit-sst** [microsoft/vscode#189614]
Type: <b>Feature Request</b>

The sticky scroll is really cool but I think it would use to have a differentiator between the part of to code that was stuck from above (function declaration, class declaration etc) AND the actual code being scrolled trough.

I feel like a slighly bigger padding between the scrolled content and the stucked part would give a better appeal.

VS Code version: Code 1.81.0 (6445d93c81ebe42c4cbd7a60712e0b17d9463e97, 2023-08-02T12:36:11.334Z)
OS version: Linux x64 6.1.0-1017-oem snap
Modes:

**Comment by gjsjohnmurray** [comment]
Something you can already do to help with differentiation is to tweak the `editorStickyScroll.background` color of your theme by adding an entry to `workbench.colorCustomizations`

**Comment by andreit-sst** [comment]
> 

Heh, sounds good. That should do it. Thanks
