### ISSUE TITLE
VS code won't run anything

### ISSUE THREAD

**Issue by Karanveer2202** [microsoft/vscode#189608]
Type: <b>Bug</b>

Anything i type in the VS code terminal gives me the same error: 

git : The term 'git' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, 
verify that the path is correct and try again.
At line:1 char:1
+ git clone --single-branch -b "react-mini" https://github.com/safak/yo ...
+ ~~~
    + CategoryInfo          : ObjectNotFound: (git:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

git is just an example, it gives the same error in pip and everything else as well. Please help. 

I checked everywhere on the internet and the most common answer i got was check the PATH in the Environment Variables, but the PATH is correct, i've checked it multiple times.

https://stackoverflow.com/questions/76832586/vs-code-doesnt-want-to-run-anything?noredirect=1#comment135451468_76832586

VS Code version: Code 1.81.0 (6445d93c81ebe42c4cbd7a60712e0b17d9463e97, 2023-08-02T12:37:13.485Z)
OS version: Windows_NT x64 10.0.22621
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 5800H with Radeon Graphics          (16 x 3194)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|13.86GB (6.78GB free)|
|Process Argv|--crash-reporter-id afa7e0e3-e800-4e6a-913b-30e6c57b357a|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (39)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|3.0.2
vscode-django|bat|1.10.0
doxdocgen|csc|1.4.0
python-environment-manager|don|1.0.4
python-extension-pack|don|1.7.0
es7-react-js-snippets|dsz|4.4.3
vsc-material-theme|Equ|33.8.0
vsc-material-theme-icons|equ|2.8.0
prettier-vscode|esb|10.1.0
mithril-emmet|Fal|0.7.7
auto-close-tag|for|0.5.14
auto-rename-tag|for|0.1.10
code-runner|for|0.12.0
better-cpp-syntax|jef|1.17.2
vsc-python-indent|Kev|1.18.0
isort|ms-|2023.10.1
python|ms-|2023.14.0
vscode-pylance|ms-|2023.8.10
jupyter|ms-|2023.7.1002162226
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.17
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-slideshow|ms-|0.1.5
remote-containers|ms-|0.299.0
remote-ssh|ms-|0.102.0
remote-wsl|ms-|0.80.2
cmake-tools|ms-|1.14.34
cpptools|ms-|1.16.3
cpptools-extension-pack|ms-|1.3.0
remote-explorer|ms-|0.4.1
color-highlight|nau|2.5.0
autodocstring|njp|0.6.1
vscode-css-peek|pra|4.4.1
LiveServer|rit|5.7.9
pytorch-snippets|SBS|1.0.2
cmake|twx|0.0.17
intellicode-api-usage-examples|Vis|0.2.7
vscodeintellicode|Vis|1.2.30
jinja|who|0.0.8

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
py29gd2263cf:30792227
vscaac:30438847
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
vscccc:30803845
2e4cg342:30602488
89544117:30613380
showlangstatbar:30737416
vsctsb:30748421
03d35959:30757346
pythonfmttext:30731395
pythoncmvfstrcf:30756944
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
gsofb:30804716
pythonnosmt12:30797651
pythonidxptcf:30805731
pythonnoceb:30805159
e537b577:30795824
dsvsc013:30795093
dsvsc014:30804076

```

</details>

**Comment by gjsjohnmurray** [comment]
Are you using PowerShell for your terminals? Do you get the same result if you open a PowerShell shell directly from the Windows Start button?

**Comment by gjsjohnmurray** [comment]
> Anything i type in the VS code terminal gives me the same error:

Please confirm that your VS Code terminal is using the same PowerShell as your non-VS Code testing is. My Terminal tab's shells menu offers both "PowerShell" and "Windows PowerShell".

**Comment by Tyriar** [comment]
> I checked everywhere on the internet and the most common answer i got was check the PATH in the Environment Variables, but the PATH is correct, i've checked it multiple times.

The error means that git cannot be found, so it must not be on the PATH (run `$env:PATH` in the terminal). So you need to investigate why that is. If you think git is indeed on the PATH then it would be a bug in PowerShell, but I doubt this is the case.
