### ISSUE TITLE
Click "scrollable element" in notebook without reaction.

### ISSUE THREAD

**Issue by virtualobserver** [microsoft/vscode#189699]
Type: <b>Bug</b>

In notebook, there is a message "Output is truncated. View as a scrollable element or open in a text editor. Adjust cell output settings..." when output result is too long, but click the "scrollable element" without reaction

VS Code version: Code 1.81.0 (6445d93c81ebe42c4cbd7a60712e0b17d9463e97, 2023-08-02T12:37:13.485Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz (8 x 2803)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.73GB (21.32GB free)|
|Process Argv|C:\\Users\\abc\\Desktop\\py --crash-reporter-id 7b0c9b7b-b5cd-424e-94e8-383ead705316|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (25)</summary>

Extension|Author (truncated)|Version
---|---|---
doxdocgen|csc|1.4.0
vscode-office|cwe|3.1.6
markmap-vscode|ger|0.1.1
vscode-docker|ms-|1.26.0
vscode-language-pack-zh-hans|MS-|1.81.2023080209
vscode-dotnet-runtime|ms-|1.6.0
vscode-edge-devtools|ms-|2.1.3
python|ms-|2023.14.0
vscode-pylance|ms-|2023.8.10
jupyter|ms-|2023.7.1002162226
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.17
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-slideshow|ms-|0.1.5
remote-containers|ms-|0.304.0
remote-ssh|ms-|0.102.0
remote-ssh-edit|ms-|0.86.0
remote-wsl|ms-|0.81.0
hexeditor|ms-|1.9.12
powershell|ms-|2023.6.0
remote-explorer|ms-|0.4.1
pdf|tom|1.2.2
html-mason|via|1.0.0
markdown-pdf|yza|1.4.4
markdown-all-in-one|yzh|3.5.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263cf:30335440
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
vscccc:30803845
3biah626:30602489
89544117:30613380
2i9eh265:30646982
showlangstatbar:30737416
vsctsb:30748421
pythonfmttext:30731395
pythoncmv:30756943
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
gsofb:30804716
pythonnosmt12:30797651
pythonidxpt:30805730
pythonnoceb:30805159
e537b577:30795824
dsvsc013:30795093
dsvsc014:30804076

```

</details>

**Comment by arnaudlegout** [comment]
I experience the same issue. It used to work on the previous versions of vscode, since 1.81.0 it does not work anymore

**Comment by arnaudlegout** [comment]
![image](https://github.com/microsoft/vscode/assets/7670869/789c9931-55f6-451e-9c59-c98830f58efd)

Here is a screenshot of the nonfunctioning "scrollable element" link.

**Comment by arnaudlegout** [comment]
And here is the screen recording of the problem
![Recording 2023-08-08 at 10 44 43](https://github.com/microsoft/vscode/assets/7670869/d2ef2850-1263-488a-a283-c8a8d07a64ba)

**Comment by samraul** [comment]
+1 Experiencing the same since the last update.

**Comment by Ansebi** [comment]
I just wish that this gets resolved. Thus, adding my +1 this way. Currently I had to uninstall vscode, reinstall an older version and  reinstall Jupyter to a fomer one

**Comment by 95anantsingh** [comment]
+1, facing since last update

**Comment by devus377** [comment]
Please advise where to go to correct this VSC error

**Comment by amunger** [comment]
This was fixed in https://github.com/microsoft/vscode/pull/190273, available in insiders.
you can also use the command `notebook.cell.toggleOutputScrolling`, bound to `ctrl+y` `k` by default
