### ISSUE TITLE
Failed to connect to WSL over tunnels

### ISSUE THREAD

**Issue by bamurtaugh** [microsoft/vscode#189663]
- VS Code Version: 
Version: 1.82.0-insider (user setup)
Commit: 83fc3ad9bd553869e8fea3d370d1d2bd438f9e54
Date: 2023-08-04T05:35:09.023Z
Electron: 22.3.18
ElectronBuildId: 22689846
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Windows_NT x64 10.0.25387

- OS Version: Windows 11 Insider

Steps to Reproduce:

1. Start a tunnel via CLI on Windows machine: `code-insiders tunnel`
2. Open VS Code Insiders, open Remote Explorer
3. In Tunnels/SSH view, select connect to WSL under the tunnel that's running
4. VS Code reloads, but gets stuck on `Starting VS Code in WSL (Ubuntu-20.04)`
5. See in the VS Code terminal: `VS Code CLI is running in WSL...
[2023-08-04 16:16:46.473] Installing server in Ubuntu-20.04`
6. See in my Windows terminal where I'm running the tunnel: `[2023-08-04 09:16:46] warn [rpc.1] failed to authenticate with child process failed to handshake spawned process: Custom { kind: InvalidData, error: "invalid type: integer `70`, expected struct PartialIncoming" }`

**Comment by connor4312** [comment]
I'm not able to reproduce this. Can you get the output from the WSL log on the window you're connecting from?

**Comment by connor4312** [comment]
`String.fromCharCode(70)` is "F" so I think rather than the protcol bash logged some "Failed to execute..." process when it tried running the CLI in WSL. But I would need a log to help diagnose things 🙂

**Comment by bamurtaugh** [comment]
Yeah sorry about not grabbing the full log! I'll be sure to share if this happens again. I just tried this flow again in a few scenarios (killed the server and ran again, with and without refreshing the list of tunnels in the Remote Explorer), and I still can't repro.

Also just to double check: Should the remote explorer only say `WSL` rather than `WSL // tunnel  <x>` or `WSL: Ubuntu // tunnel: <x>`? Is there a feature request for showing more info (similar to how we show container and SSH info when using Dev Containers + Remote-SSH together)?

![image](https://github.com/microsoft/vscode/assets/25310137/aacde279-b888-4e0f-8c28-c68f6934a3c9)

**Comment by connor4312** [comment]
good reminder -- had to do the last approval on the build from yesterday that fixes that
