### ISSUE TITLE
Javascript and Typescript errors don't show up

### ISSUE THREAD

**Issue by DianaY-a11y** [microsoft/vscode#189689]
Type: <b>Bug</b>

When I have errors in my code, like missing a semicolon, it is not marked by vscode. I also cannot click into file paths to go to that file. 

VS Code version: Code 1.81.0 (Universal) (6445d93c81ebe42c4cbd7a60712e0b17d9463e97, 2023-08-02T12:40:02.782Z)
OS version: Darwin arm64 22.5.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Max (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|9, 32, 21|
|Memory (System)|64.00GB (41.23GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-typescript-next|ms-|5.2.20230803

</details>

**Comment by mjbvz** [comment]
> like missing a semicolon

This is almost always a style issue that would be handled by a linter such as eslint. Try installing and configuring eslint if you want that to show as an error
