### ISSUE TITLE
Search disappear from SideBar

### ISSUE THREAD

**Issue by viclafouch** [microsoft/vscode#189669]
How to get back my search icon ? No extension, no theme.. No search :(

<img width="287" alt="image" src="https://github.com/microsoft/vscode/assets/23353836/8d7377bd-adb0-4f49-9814-3fbfd33206ec">

Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.81.0
- OS Version: Ventura 13.4

**Comment by gjsjohnmurray** [comment]
Use Command Palette to run the command to rest view locations.

**Comment by viclafouch** [comment]
Ok but if I want to use the sidebar, how ?

**Comment by gjsjohnmurray** [comment]
The exact command to run is ` View: Reset View Locations`
