### ISSUE TITLE
VSIX extension fails to install

### ISSUE THREAD

**Issue by usernamehw** [microsoft/vscode#189632]
I'm using this code from another extension to quickly install the vsix file:

```js
const vsixPath = path.join(folder.uri.fsPath, vsixFile);
await commands.executeCommand('workbench.extensions.command.installFromVSIX', [Uri.file(vsixPath)]);
```

The same thing happens when installing from File Explorer context menu item `Install Extension VSIX`.

After that extension is installed and working until window reload. After window reload - it's never activated, none of the commands are registered, and installing from marketplace activates it once and then it's gone again (after window reload or restart):

![Animation](https://github.com/microsoft/vscode/assets/9638156/d4e4fdd8-1792-4065-a143-1cc72ee9ef85)

---

Version: 1.81.0
Commit: 6445d93c81ebe42c4cbd7a60712e0b17d9463e97
Date: 2023-08-02T12:37:13.485Z
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Code/1.81.0 Chrome/108.0.5359.215 Electron/22.3.18 Safari/537.36

Version: 1.82.0-insider (user setup)
Commit: 83fc3ad9bd553869e8fea3d370d1d2bd438f9e54

**Comment by zephimir** [comment]
similar issue on m2 pro, I'm unable to install any extension from the explorer, they will automatically uninstall like seen in the  clip from @usernamehw

**Comment by bpasero** [comment]
Are profiles involved here? Possibly with the option to "Apply extension to all profiles"?

**Comment by joyceerhl** [comment]
This may be a duplicate of https://github.com/microsoft/vscode/issues/189877. Can you please try out the latest VS Code Insiders and let us know whether it's fixed there: https://code.visualstudio.com/insiders

**Comment by usernamehw** [comment]
Seems to be fixed in Insiders. Commit: d62534a60f7eb4280bcbee66bbd84a2e15f13765
