### ISSUE TITLE
missing dependency on 'libxss1' for Debian/Ubuntu package

### ISSUE THREAD

**Issue by d0ru** [Microsoft/vscode#18968]
Hi

- VSCode Version: 1.8.1-1482158209
- OS Version: Debian 7.11 (x86_64)

Steps to Reproduce:

1. Launch VS Code
```
doru@r2:~$ code
/usr/share/code/bin/../code: error while loading shared libraries: libXss.so.1: cannot open shared object file: No such file or directory
```

Steps to Fix:

1. Install missing package
`root@r2:~# apt-get install libxss1`

Thanks

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/13089
