### ISSUE TITLE
User snippet should take precedent

### ISSUE THREAD

**Issue by unional** [Microsoft/vscode#18963]
vscode: 1.8.1

When there is an user snippet, it should take precedent over available completion.

For example: `import`.
I like to define a snippet as follow:

```js
{
	"import": {
		"prefix": "import",
		"body": [
                  "import { $2 } from '$1'",
                  "$0"
                ]
	}
}
```

Currently, typing import (or "i", "im", "imp" and so on), would complete the "import" keyword.
IMO it should trigger the snippet instead.

**Comment by unional** [comment]
Btw I know there is an "import statement" snippet predefined that does the same thing. And it is also taking priority over the "import" keyword. Making it not really useful.

And how can I change / update those predefined snippet.

**Comment by kaiwood** [comment]
There's a setting for this: `"editor.snippetSuggestions": "top"`

**Comment by Jasonlhy** [comment]
@kaiwood didn't realize there is a setting for this

**Comment by unional** [comment]
Thanks. That is what I'm looking for.

Do you know how to customize predefined snippets?

**Comment by CoenraadS** [comment]
I modified the inbuilt for-each snippet by copying it from here: https://github.com/Microsoft/vscode/blob/cf5c0115290ce65ab7bd3933e17df9649f14e2bc/extensions/typescript/snippets/typescript.json

And put it in user defined snippets. It works well (user defined snippet takes precedent for me), but I did not like that I had to search the code from the predefined snippets. It would be nice if the default snippets were maybe in user-defined snippets, so the user can remove/modify default snippets easily.

**Comment by jscissr** [comment]
In my case, I made a snippet for `if`. But when I type `if`, the keyword option is preselected instead of the snippet.
I tried `"editor.snippetSuggestions": "top"`. It does put the snippets at the top of the list. But when intellisense triggers, it does not actually preselect the first item in the list, it still preselects the `if` keyword, so I don't see the point in this setting.

**Comment by unional** [comment]
Actually, using `editor.snippetSuggestions` is not optimal. It should go below instance property and above keywords. e.g.:

```ts
import^  // snippet "import" should go before the import keyword

function foo(option: SomeFooOptions) { ... }
foo({ ^ } // properties in "SomeFooOptions" should go before user snippets.
```

**Comment by capaj** [comment]
@unional exactly like they have in sublime text snippets: https://snippets.now.sh/

**Comment by geddski** [comment]
glad "top" is a setting, seems like that should be the default in my opinion but whatevs.
