### ISSUE TITLE
welcome page GitHub walkthrough example image bug

### ISSUE THREAD

**Issue by Sekomer** [microsoft/vscode#189613]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 
1.80.2
2ccd690cbff1569e4a83d7c43d45101f817401dc
arm64
- OS Version: 
darwin22.0
ProductName:            macOS
ProductVersion:         13.4.1
ProductVersionExtra:    (c)
BuildVersion:           22F770820d

Steps to Reproduce:

1. Open Visual Studio Code
2. On the welcome page, click to Github Copilot via Walkthrough panel
3. Click to 'You are in control' section.
4. Until now everything is normal, but when you click again to the 'you are in control' section, the javascript isPositive example image on the right is doubled. As you continue to click, the number of examples on the right is increasing, I don't think this is the expected behavior

Expected Behavior:
Don't add that image to the page more than once
<img width="1728" alt="SCR-20230804-jrjf" src="https://github.com/microsoft/vscode/assets/61659936/1c58d40d-d392-4242-aa6d-acdf571b44b4">
<img width="1728" alt="SCR-20230804-jrlg" src="https://github.com/microsoft/vscode/assets/61659936/e57add79-7013-44c8-bf17-1e6b85e22840">
<img width="1728" alt="SCR-20230804-jrpq" src="https://github.com/microsoft/vscode/assets/61659936/e614d573-2f6c-4602-b6b5-9d2fe759dac6">

**Comment by bhavyaus** [comment]
This has been resolved in the most recent release.
