### ISSUE TITLE
Cannot connect to runtime process (reason: getaddrinfo ENOTFOUND localhost undefined:32974)

### ISSUE THREAD

**Issue by ngprasad** [Microsoft/vscode#18960]
- VSCode Version: 1.8.1
- OS Version: 10.11.6

Steps to Reproduce:

I am not sure how I got into this state but I am not able to run my electron app anymore. I tried restarting VSCode and also restarting my computer but it didn't help.

Any help will be appreciated.

**Comment by dbaeumer** [comment]
Which electron app can't you run anymore.

**Comment by mousetraps** [comment]
Closing as we haven't heard back, but happy to reopen if you have more details to share. Happy coding!
