### ISSUE TITLE
Simple browser debugger

### ISSUE THREAD

**Issue by fer-rouco** [microsoft/vscode#189637]
I loved the embedded "Simple browser", but it is not useful for me because it doesn't allow me to debug my Javascript/Typescript code.
So I would like to be able to create a configuration in the launch.json file like this...
        {
            "name": "Run Simple Browser",
            "type": "simple-browser",
            "request": "launch",
            "url": "http://localhost:3000",
            "webRoot": "${workspaceFolder}"
        }
run it and be able to do my development and debug my code without leaving vscode.

**Comment by gjsjohnmurray** [comment]
If you run the command to open DevTools for webviews does this give you access to the scripts?
