### ISSUE TITLE
[Bug] Thunder Client extension fails to connect to localhost when not using IP

### ISSUE THREAD

**Issue by Esked-chan** [microsoft/vscode#189629]
Does this issue occur when all extensions are disabled?: No

- VS Code Version: 1.81.0
- OS Version: Windows 10 Home 22H2

Steps to Reproduce:

1. Install the Thunder Client extension, and try to connect to localhost (localhost:PORT/path)
2. Wait for eternity while the extension processes the request.

This bug appeared since the latest VSCode update (1.81.0). Downgrading to the previous version (1.80.2) fixes the problem. It also only happens if we try to use localhost. When we use the local IP address, there is no issue.
![Untitled](https://github.com/microsoft/vscode/assets/70443831/ee3d6f7d-22da-45cb-835a-65cd3e6bc69f)
![Untitled2](https://github.com/microsoft/vscode/assets/70443831/0a27673e-aa14-4ea3-bf80-41e76a059a78)

Further information can be found on Thunder Client's GitHub page: https://github.com/rangav/thunder-client-support/issues/1251

**Comment by srisrinu1** [comment]
I'm also facing the same issue.I see few other's are also facing this issue with latest update of VS code.

Please check the bug raised in the Thunderclient repo about this issue [https://github.com/rangav/thunder-client-support/issues/1251](url)

**Comment by srisrinu1** [comment]
I'm also facing the same issue.I see few other's are also facing this issue with latest update of VS code.

Please check the bug raised in the Thunderclient repo about this issue  https://github.com/rangav/thunder-client-support/issues/1251

**Comment by rangav** [comment]
Here is the error screenshot in developer tools when I run localhost url
![image](https://github.com/microsoft/vscode/assets/8637550/09ee868e-4e27-4f50-8eed-bdf3fbf8751d)

**Comment by gumernus** [comment]
Ye a I have the same issue. Doesn't work with 0.0.0.0 nor localhost. Needed to pass in the actual ip.

**Comment by srisrinu1** [comment]
Thunderclient has released a new version 2.10.2.It's working.

**Comment by rangav** [comment]
Hi All,

We just now published a new version Thunder Client to fix this issue.

Please update the extension to version - `v2.10.2`

so you can close this issue

**Comment by mfurseroberts** [comment]
I am still getting "connect EADDRNOTAVAIL 127.0.0.1:80" despite using ThunderClient v2.11.1. 127.0.0.1:80 resolves in the browser and elsewhere.

**Comment by rangav** [comment]
@mfurseroberts try the solution in comment https://github.com/rangav/thunder-client-support/issues/1086#issuecomment-1664276140
