### ISSUE TITLE
Make tunnel forwarding built-in, instead of using separate remote-tunnels extension

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#189678]

**Comment by OneCyrus** [comment]
@connor4312 in the iteration plan from august this issue is linked as "Local port forwarding should be built-in". does this address local ports mapped on the local system instead of just linking to a remote domain? I tried this with the current insider version but doesn't seem to work (yet?). Is this supposed to work like it does with SSH or GitHub Codespaces port forwarding?

**Comment by connor4312** [comment]
> does this address local ports mapped on the local system instead of just linking to a remote domain?

I'm not sure what you mean by that

This feature is currently working as intended for our internal testers...

**Comment by OneCyrus** [comment]
Codespaces maps the forwarded ports to local ports (accessible on 127.0.0.1)

![image](https://github.com/microsoft/vscode/assets/7747800/8a255b44-1e05-4ae0-9bfa-55a30620de7a)

DevTunnels forwards the traffic to devtunnels.ms and is not mapped to a local port (accessible only on https://xg5t5q8g-5173.euw.devtunnels.ms in this example and not on 127.0.0.1:5173)
![image](https://github.com/microsoft/vscode/assets/7747800/2d1c585d-cd6b-45da-821d-2f89eb581bb4)

is this how it should be?

**Comment by connor4312** [comment]
Local forwarding makes a local port accessible remotely, it doesn't make a remote port accessible locally. This is similar to something like [localtunnel](https://theboroer.github.io/localtunnel-www/). Though I see that the label in that table is confusing, I'll make a change to tweak it.

**Comment by OneCyrus** [comment]
i don't mean something like localtunnel (which would be the reverse of the feature here). It's all about the implementation detail how the port on the server is accessible on the client. codespaces and the SSH extension make the port accessible on the client itself.

The tunnel implementation makes the port accessible on a complete different server (devtunnel.ms) and the browser needs to connect to this different server instead to a local port on the client (where vscode is running)

**Comment by OneCyrus** [comment]
this is how it behaves with codespaces on the client (where vscode desktop is running)

running the webserver in codespaces (listening on port 8123 on the codespace server). listed with the column name "port" in the table. the column "local address" is the port where vscode desktop is listening (in this example 127.0.0.1:8123)

![image](https://github.com/microsoft/vscode/assets/7747800/3e414367-a939-4f37-8464-c07115075ea9)



and if we look into the listening ports opened on the client (vscode desktop) we can see that code.exe is listeing on port 8123 which is then forwarded to codespaces through the extension. This allows to forward any TCP traffic and not just HTTP.

![image](https://github.com/microsoft/vscode/assets/7747800/cce18bf7-566a-4b41-96cc-cd4749a37a0e)
