### ISSUE TITLE
remote ssh password loop

### ISSUE THREAD

**Issue by fahadalisarwar1** [microsoft/vscode#189609]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 
- OS Version: 

Steps to Reproduce:

1. try remote login
2. it keeps asking for password

I tried to login to a remote linux machine from my windows pc, it keeps asking for password again and again, although i have no trouble connecting to machine via ssh through terminal.

**Comment by roblourens** [comment]
If this is still an issue, please share the log from the Remote-SSH output channel. Can reopen if needed
