### ISSUE TITLE
docker extension doesnot detect available docker context in host

### ISSUE THREAD

**Issue by so-schen** [microsoft/vscode#189728]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:  1.81.0 (Universal)
- OS Version: macos Version 13.5 (22G74)

Steps to Reproduce:

1. install docker CLI only - brew install docker
2. create docker context - my macos host has below context 
```
NAME                        DESCRIPTION                               DOCKER ENDPOINT               ERROR
default *                   Current DOCKER_HOST based configuration   unix:///var/run/docker.sock   
remote-docker-on-vm                                            ssh://xyz@192.168.100.99

```
3. open vscode, and I can only see default, but "remote-docker-on-vm" cannot find,

**Comment by chrmarti** [comment]
/causedByExtension

This is caused by the Docker extension. Please file a new issue for it: https://github.com/microsoft/vscode-docker/issues
