### ISSUE TITLE
latest code insiders: pasteUrlAsFormattedLink no longer smart formatting as markdown link

### ISSUE THREAD

**Issue by noahehall** [microsoft/vscode#189767]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 
```sh
$ code-insiders --v
1.82.0-insider
83fc3ad9bd553869e8fea3d370d1d2bd438f9e54
x64
```

- OS Version: 
```sh
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.3 LTS
Release:	22.04
Codename:	peanut-butter jammy
```
Steps to Reproduce:

1.  install latest code-insiders
2. add this to config: `"markdown.editor.pasteUrlAsFormattedLink.enabled": "smart"`
3. paste a link inside somefile.md
4. instead of automatically formatting as markdown link, a popup icon forces you to choose

```[tasklist]
### Tasks
- [ ] make github copilot free again
```

**Comment by noahehall** [comment]
FYI: setting it to `always` works, is `smart` no longer supported?

**Comment by MeghanKulkarni** [comment]
With the `smart` setting, the default is now to only create a markdown link if some text is selected beforehand.
