### ISSUE TITLE
Partial Profile created by settings unchecked (thus Settings using default profile) doesn't respect setting items which is described  with "Applies to all profiles"

### ISSUE THREAD

**Issue by wrlssqi** [microsoft/vscode#189798]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.82.0-insider
Commit: 1606401f5b761397488f53b75130809fba073194
Date: 2023-08-07T05:34:01.211Z
Electron: 22.3.18
ElectronBuildId: 22689846
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Linux x64 5.15.0-78-generic
- OS version: ubuntu 22.04.3 LTS

Steps to Reproduce:

1. change "Title Bar Style" settings of default profile to "custom"
2.  create a new profile, and uncheck settings(means using default profile settings). 
![image](https://github.com/microsoft/vscode/assets/9946624/d6128b6b-c395-4ad4-aa78-f73d1e324613)

3.  when click creat button, a pop up windows says "a settings has changed that requires a restart to take effect  vscode"
![image](https://github.com/microsoft/vscode/assets/9946624/2c42dd76-9fb3-48b3-aaaf-6562a78ec6a7)

4. click restart, and check "Title Bar Style" settings, find it is native ,and can't be changed. 
5. every time switch  profiles between default and other created profiled will popup the annoying  "a settings has changed that requires a restart to take effect  vscode" window, and only the default profile shows the custom title bar.

**Comment by wrlssqi** [comment]
i start use user profile since 1.81.0, and i don't know if such bug also appears on early version.  besides, vscode don't have this bug  when on windows 11.

**Comment by wrlssqi** [comment]
actually this bug is very annoying ,because, when switch to user profile whose "Title Bar Style" settings is forced to native,  it has no menu bar at all! user can't do many operation throuth menu bar, because it is not there at all.  every thing is right when in default profile.

![image](https://github.com/microsoft/vscode/assets/9946624/fd4a3ced-e463-4c42-a3f7-1f1ec6a925ce)

**Comment by wrlssqi** [comment]
it seems that windows 11 also has this problems. but the default "Title Bar Style" settings on windows is "custom",so it appears normally when switch between profiles (default profile "Title Bar Style" setting is custom ).   
i also find that when in user profile, change "Title Bar Style" settings in UI dose change settings.json contents, but it just don't influence the user profile currently on , it only influence default profile.

**Comment by wrlssqi** [comment]
a guess is that when a profile is created with settings unchecked(use default profile settings), all settings with description " Applies to all profiles" will be forced to default value when the profile is switched on.

![image](https://github.com/microsoft/vscode/assets/9946624/398d596f-54b0-4e63-b679-56a58c5ab991)

**Comment by wrlssqi** [comment]
it seems that this issue #189725  is the same bug with me

**Comment by memchr** [comment]
I suggest toggling `[ ] Settings` and using symlink as a workaround for now.

```bash
ln -srf ~/.config/Code/User/settings.json ~/.config/Code/User/profiles/<profile id>/settings.json
```
![image](https://github.com/microsoft/vscode/assets/118117622/d7489551-5d44-4c6b-b055-514428054853)

**Comment by br14n-sol** [comment]
Default profile
![image](https://github.com/microsoft/vscode/assets/60621046/54620c1a-e785-4b6d-9ee6-fa65d7ca9d63)

Other profile
![image](https://github.com/microsoft/vscode/assets/60621046/596ea774-ff0f-4cc0-a216-3bda726ae922)

**Comment by sandy081** [comment]
To verify:

- Open window with default profile
- Change `update.mode` setting to non default value
- Restart application
- Create a profile that uses settings from default profile
- Make sure the application is not asked to restart
- Make sure the value of `update.mode` setting is set to the value that was set before.

**Comment by wrlssqi** [comment]
> To verify:
> 
> * Open window with default profile
> * Change `update.mode` setting to non default value
> * Restart application
> * Create a profile that uses settings from default profile
> * Make sure the application is not asked to restart
> * Make sure the value of `update.mode` setting is set to the value that was set before.

yeah，I follow your steps, change default profile  update.mode to "manual", and when create a new profile that uses settings from default profile,  vscode does ask to restart!  and even worse is after restart, vscode is still in default profile, can't be changed to other profile. It seems that update.mode settings prohibits vscode swithing to created user profile. 
All tested on windows version , with vscode version 1.81.1
