### ISSUE TITLE
 Background color support for notebook cells

### ISSUE THREAD

**Issue by HaoHoo** [microsoft/vscode#189719]
Hi Experts,
I'm using the notebooks in VS Code for lots of Data and ML work. Yes, we always have to create lots of cells in the notebook and edit them at the same time. So I think that it is possible to set up the cells using different background colors. For example, use light green as the Python code cell and use light blue as the Markdown cell, etc.
It may help us more rapidly locate the cell which needs to edit and can be used with cell tags together.

**Comment by rebornix** [comment]
This can be customized by settings

```
"workbench.colorCustomizations": {
    "notebook.cellEditorBackground": "#fff"
  },
```
