### ISSUE TITLE
File Content Index became massive

### ISSUE THREAD

**Issue by wrexbe** [microsoft/vscode#189736]
Not sure how, or when. I was trying to free up space, and noticed it

<img width="482" alt="Screenshot 2023-08-05 at 4 38 03 PM" src="https://github.com/microsoft/vscode/assets/81056464/2a531776-552b-4c23-ba65-fd647a52f236">

This was in one of the files.

bplist00�XUTI-Data�_$com.apple.traditional-mac-plain-text_public.utf8-plain-text_public.utf16-plain-textOp/Users/dev/repos/work/VaultTech/.vs/VaultTech/FileContentIndex/merges/ffff80bd-09c9-4968-bd77-becd1f95c796.vsidx_p/Users/dev/repos/work/VaultTech/.vs/VaultTech/FileContentIndex/merges/ffff80bd-09c9-4968-bd77-becd1f95c796.vsidxO�/Users/dev/repos/work/VaultTech/.vs/VaultTech/FileContentIndex/merges/ffff80bd-09c9-4968-bd77-becd1f95c796.vsidxB[u�[	>

If this is already solved, or not enough info to do anything, feel free to close this.

**Comment by lramos15** [comment]
This is visual studio not VS Code.
See 
https://learn.microsoft.com/en-us/visualstudio/ide/how-to-report-a-problem-with-visual-studio?view=vs-2022
