### ISSUE TITLE
[Feature Request] GUI for enabling / disabling LSP features per extension

### ISSUE THREAD

**Issue by fiveNinePlusR** [microsoft/vscode#189730]
Some extensions only implement some parts of the LSP spec and they may overlap or clobber some other extension that enables a feature. Right now it's unknown or unclear as to which language server is handling a given feature or if there are conflicts. 

Ideally a GUI would be made available that you could look at to see what LSP servers are active for a given filetype and what they offer/which one take precedence if they are not combined. Being able to toggle the feature on a per extension basis would be nice as well.

an example of this is the solargraph lsp for ruby and the shopify lsp for ruby. both enable some features that overlap in some ways that as a user we don't understand where the features are coming from or if they conflict at all.

**Comment by mjbvz** [comment]
Please file individual feature requests against the extension where you want to see this
