### ISSUE TITLE
[Accessibility] Add a custom setting always moving focus to terminal buffer after sending selection to terminal

### ISSUE THREAD

**Issue by jooyoungseo** [microsoft/vscode#189776]
Type: <b>Feature Request</b>

For screen reader users, terminal buffer is the great landing area where they can verify executed commands.

Currently, the focus always moves to terminal input when we use the following command:

> Terminal: Run Selected Text In Active Terminal

Given the immediate need of accessing the terminal buffer for screen reader users, please add a custom setting to always move focus in terminal buffer area instead of the terminal input. This will greatly improve the accessibility, navigability, and alertability for screen reader users.

VS Code version: Code - Insiders 1.82.0-insider (83fc3ad9bd553869e8fea3d370d1d2bd438f9e54, 2023-08-04T05:35:09.023Z)
OS version: Windows_NT x64 10.0.22621
Modes:

**Comment by jooyoungseo** [comment]
CC @meganrogge This benefit would be far reaching including Python repl and any terminal-based interpreters.

**Comment by meganrogge** [comment]
@jooyoungseo we have a new way to do this sort of thing. You can set up `runCommands` in a custom keybinding. For example:

```
{
		"key": "ctrl+3",
		"runCommands": [
			"workbench.action.terminal.runSelectedText",
			"workbench.action.terminal.focus"
		],
	}
```

Note that I couldn't get this to work for me cc @hediet

**Comment by jooyoungseo** [comment]
@meganrogge I have found that the following works:

``` json
  {
    "key": "ctrl+3",
    "command": "runCommands",
    "args": {
      "commands": [
        "workbench.action.terminal.runSelectedText",
        "workbench.action.terminal.focusAccessibleBuffer"
      ]
    }
  }
```

However, this is not novice-SR-user-friendly. Let's discuss further for better usability.

**Comment by meganrogge** [comment]
would it suffice to focus the active terminal automatically for screen reader users after that command is run?

**Comment by jooyoungseo** [comment]
If you are referring to the current active terminal’s a11y buffer, I would say “Yes”. If you are talking about the active terminal input area, I would say, it might not be helpful.

**Comment by meganrogge** [comment]
@jooyoungseo, I discussed with @Tyriar and we want to prevent the screen reader user's experience from diverging from the sighted user's experience.

ATM, run selected text in active terminal keeps the focus in the editor so that a user can run additional lines of code. When I test this, the output gets announced via the screen reader. 

In the terminal buffer, we now have better support for reviewing the terminal input #190294. 

What part of your flow is not well covered by this?

**Comment by jooyoungseo** [comment]
@MeganRogge and @Tyriar -- Thank you for giving me the opportunity to expand on this topic:

1. **Configurable Setting**: I propose the addition of a configurable setting for this feature. By default, the system could set the focus to move to the terminal input area. However, this behavior would be adjustable, allowing screen reader (SR) users to customize it according to their needs. This ensures that any divergence in user experience between sighted and visually impaired individuals is purely a matter of personal choice.

2. **Focus After Execution**: Consider the following scenario—You have written your code in a scratch pad editor and then sent it to the terminal for execution. After the code has been executed, where does your focus naturally shift? Is it the input field or the output display? In most cases, it's the latter. Although 'aria-live' capabilities exist within the terminal input, these primarily provide instantaneous speech information that may be difficult to absorb, particularly if the output is complex or lengthy. For this reason, screen reader users often prefer to manually navigate through the terminal output, rather than relying on 'aria-live' alerts.

**Comment by Tyriar** [comment]
> Focus After Execution

@jooyoungseo the way I think about it is that a user doesn't necessarily want to look at the accessible buffer immediately after running a command, the `aria-live` alerts will often be sufficient. So why wouldn't we treat this just like running a regular command where you type and press enter, ie. focus the terminal, but not the a11y buffer.

**Comment by jooyoungseo** [comment]
@Tyriar `aria-live` is fantastic for short and simple notifications, but it's not a one-size-fits-all solution. Imagine you're working in a data science context, and your output isn't just a single sentence but rather a complex data structure. It can be quite a challenge to remember all that information after hearing it just once, can't it?

Another thing to consider is the buffer size of `aria-live` alerts. Longer outputs could get truncated, and that's definitely not ideal when the information is crucial. So, in scenarios like these, it might be more user-friendly to direct the focus straight to the terminal buffer. This would allow the user to navigate through the data at their own pace and comfort level.

What do you think? Would love to hear your thoughts on this!

**Comment by Tyriar** [comment]
@jooyoungseo but we don't necessarily know whether the command will produce short or long output, and we don't know if the user will want to enter a command after, return to the editor, or view the accessible buffer. To me focusing the terminal and getting the regular behavior of running a command seems like the best compromise and most general behavior.

Having said that, I've been on the fence for a setting for this behavior even when screen reader mode is disabled, so this is just another reason to add that. I would prefer if we kept the default to focus the terminal though because of the reasons above.

**Comment by jooyoungseo** [comment]
@Tyriar Yes, absolutely. I am not against keeping the default behavior. I was wondering if you could consider adding a custom user setting for those who want to change the default behavior.

**Comment by meganrogge** [comment]
If we add a setting, perhaps it could be "runTextInTerminalFocus": "terminal", "accessible buffer", or "none"

**Comment by Tyriar** [comment]
@meganrogge how about `"focusAfterRun": "auto" | "terminal" | "accessibleBuffer" | "none"`, where `"auto"` is terminal if in screen reader mode, otherwise `"none"`?

**Comment by meganrogge** [comment]
@Tyriar Your proposal sounds good except we'd want to go with `"accessibleBuffer"` for screen reader users as JooYoung has indicated that just focusing the terminal would not be helpful.

**Comment by Tyriar** [comment]
@meganrogge see https://github.com/microsoft/vscode/issues/189776#issuecomment-1694341099 and the comment below. That's @jooyoungseo's preference but it's not necessarily the typical use case, so let's focus the terminal just like when running a command (typing and enter into shell).

**Comment by meganrogge** [comment]
To verify, enable screen reader mode and use the command `Terminal: Run selected text in active terminal`. It should run the text then focus the terminal by default. Disable screen reader mode and do that again. The terminal shouldn't be focused. Change the setting with and without screen reader mode on and make sure it gets applied and that each setting description makes sense.

**Comment by meganrogge** [comment]
@andreamah the setting takes one of a few values: `"terminal", "accessible-buffer", or "none"`

**Comment by meganrogge** [comment]
yeah that's working for you in your screenshot above

**Comment by andreamah** [comment]
ok, I'll just mark this as `verified` and you can handle that separately
