### ISSUE TITLE
[json] Quick Suggestions support for locally installed NPM Modules

### ISSUE THREAD

**Issue by sr229** [Microsoft/vscode#18978]
Back then, code has an ability to provide quick suggestions/Intellisense for NPM modules, but this proves to have a strain on the NPM registry so the VS Code team has disabled it.

I am suggesting that we should have Quick Suggestions/Intellisense for **Locally-Installed** Modules instead of querying through the NPM Registry. 

This feature is evident of some popular IDEs like JetBrains Webstorm which proves to increase efficiency and reduces the need to always have documentation opened for a specific module.

**Comment by dbaeumer** [comment]
@aeschli not sure if you are the right person ?

**Comment by aeschli** [comment]
Intellisense for NPM modules is available, we haven't disabled anything.
![image](https://cloud.githubusercontent.com/assets/6461412/22197230/571f8e1c-e151-11e6-8f91-886df00c93fc.png)

Looking at locally installed node modules would add a dependencies on npm, which I'd rather avoid.
