### ISSUE TITLE
Extensions Not loading if WSL is opened first

### ISSUE THREAD

**Issue by ThomasHovey** [microsoft/vscode#189785]
Type: <b>Bug</b>

If WSL is opened before launching vs code all the wsl extensions are gone once launched.

If vs code is launched first then the extensions show up. 

VS Code version: Code - Insiders 1.82.0-insider (e8b1e2bea88d34a813405a176148dd9fd17cbb1f, 2023-08-03T17:09:22.928Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Remote OS version: Linux x64 5.15.90.1-microsoft-standard-WSL2
Remote OS version: Linux x64 5.15.90.1-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz (8 x 2419)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|7.85GB (0.45GB free)|
|Process Argv|--crash-reporter-id 80a60588-a1a1-4595-8cb3-2e78a65be689|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 5.15.90.1-microsoft-standard-WSL2|
|CPUs|11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz (8 x 2419)|
|Memory (System)|3.75GB (1.82GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 5.15.90.1-microsoft-standard-WSL2|
|CPUs|11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz (8 x 2419)|
|Memory (System)|3.75GB (1.82GB free)|
|VM|0%|
</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
remote-wsl|ms-|0.80.2
strictdoc|Str|0.0.2
vim|vsc|1.25.2
copilot|Git|1.100.309
copilot-chat|Git|0.7.2023072802
cpptools|ms-|1.16.3
cpptools-extension-pack|ms-|1.3.0
live-server|ms-|0.5.2023080101
sonarlint-vscode|Son|3.20.2

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes516:30244333
vslsvsres303:30308271
pythontb:30258533
pythonptprofiler:30281269
vshan820:30294714
vscod805cf:30301675
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30404738
py29gd2263:30784851
vsclangdf:30492506
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30618038
showlangstatbar:30737417
ecj1e332:30687743
pythonfmttext:30716741
pythoncmvfstr:30726892
fixshowwlkth:30771523
showindicator:30805243
pythongtdpath:30726887
i26e3531:30792625
gsofa:30797620
welcomedialogc:30800245
pythonnosmt12:30779711
pythonidxpt:30768918
pythonnoceb:30776497
copilotsettingt:30767686
e537b577:30772214
h0f32768:30792099
asynctokenver:30799129
dsvsc013:30777762
dsvsc014:30777825
diffeditorv2:30786206

```

</details>

![Untitled picture](https://github.com/microsoft/vscode/assets/14326395/4acce7b1-6507-4f43-b335-fa34013008d7)

**Comment by aeschli** [comment]
What do you mean by `If WSL is opened before launching vs code `? So you mean for example a WSL terminal is opened?
The WSL extension are located in the WSL filesystem at `~/.vscode-server/extensions`
It should not matter how WSL is started; they should always be found there.

Can you check that starting WSL from a terminal uses the same user as when VS Code opens WSL?

**Comment by aeschli** [comment]
Closing the issue, I need more information.
