### ISSUE TITLE
Feature request: add API to add custom icons and functionality behind it to left bar.

### ISSUE THREAD

**Issue by Webtakeme** [Microsoft/vscode#18977]
Currently on **left side bar** VSCode have **only 5 icons** (explorer, search, git, debug, extensions).
**Below** this icons there is really huge **empty area**.

It would we great if we will have some **API to add custom icons** to this area and assign some command to it (as I know there is _such possibility but only for bottom bar_).

 Some action require couple step to perform it (run some command):
 - _open command palette_
 - _search some command and perform it_
 - _if in current command there is subcommands we need to perform couple command selection..._

We can avoid this buy adding special icon with assigned action to left bar - **only on click** to perform some **command** (it will save us a lot of time during development).

For example on _Atom_ there is extension _"tool-bar"_ https://atom.io/packages/tool-bar that implement such functionality:

![1485005635732](https://cloud.githubusercontent.com/assets/14540860/22174786/169c74d0-dfef-11e6-91f9-0e9d09fa22eb.png)
  

**Huge empty area:**

![1485005292896](https://cloud.githubusercontent.com/assets/14540860/22174824/44fa5f62-dff0-11e6-99ff-cd9c2c197707.png)

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/710
