### ISSUE TITLE
Error: EPERM: operation not permitted, stat 'g:\System Volume Information'

### ISSUE THREAD

**Issue by blackburn9** [microsoft/vscode#189766]
Type: <b>Bug</b>

i am keep getting this error when i click any where in my visual studio window. 

VS Code version: Code 1.81.0 (6445d93c81ebe42c4cbd7a60712e0b17d9463e97, 2023-08-02T12:37:13.485Z)
OS version: Windows_NT x64 10.0.22621
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|7.89GB (1.48GB free)|
|Process Argv|--crash-reporter-id 9f86ce41-1075-496b-9853-71ec7458f6e4|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2023.14.0
vscode-pylance|ms-|2023.8.10

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263cf:30335440
vscoreces:30445986
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
vscccc:30803845
2e4cg342:30602488
f6dab269:30613381
showlangstatbar:30737416
vsctsb:30748421
03d35959:30757346
pythonfmttext:30731395
pythoncmvfstrcf:30756944
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
gsofb:30804716
pythonnosmt12:30797651
pythonidxpt:30805730
pythonnoceb:30805159
e537b577:30795824
dsvsc013:30795093
dsvsc014:30804076

```

</details>

**Comment by DaiZack** [comment]
Just update vscode to 1.18.0. And unable to start it with the similar error. 

![image](https://github.com/microsoft/vscode/assets/45176371/109d8a59-cfc3-4284-88e5-ac86886b15ed)

Confirmed that the two paths listed above are writable.

```
C:\Users\xxx\AppData\Local\Programs\Microsoft VS Code>Code.exe --verbose

C:\Users\xxx\AppData\Local\Programs\Microsoft VS Code>
[main 2023-08-09T14:06:29.334Z] PolicyConfiguration#initialize
[main 2023-08-09T14:06:29.338Z] PolicyConfiguration#updatePolicyDefinitions [
  'http.proxy',
  'http.proxyStrictSSL',
  'http.proxyKerberosServicePrincipal',
  'http.proxyAuthorization',
  'http.proxySupport',
  'http.systemCertificates',
  'telemetry.telemetryLevel',
  'telemetry.enableTelemetry',
  'update.mode',
  'update.channel',
  'update.enableWindowsBackgroundUpdates',
  'update.showReleaseNotes'
]
[main 2023-08-09T14:06:29.343Z] NativePolicyService#_updatePolicyDefinitions - Found 1 policy definitions
[main 2023-08-09T14:06:29.351Z] [File Watcher (node.js)] Request to start watching: \\group\users\Roaming\V7\xxxx\AppData\Roaming\Code\User (excludes: <none>, includes: <all>),\\group\users\Roaming\V7\xxx\AppData\Roaming\Code\User\settings.json (excludes: <none>, includes: <all>)
[main 2023-08-09T14:06:29.353Z] NativePolicyService#_onDidPolicyChange - Updated policy values: {}
[main 2023-08-09T14:06:29.354Z] PolicyConfiguration#update [ 'update.mode' ]
```

**Comment by DaiZack** [comment]
Downgrade to 1.80 there is no issue with lanch, I think it is a bug in 1.81.0

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/
