### ISSUE TITLE
Process explorer CPU churn can't be spotted in child processes

### ISSUE THREAD

**Issue by jpike88** [microsoft/vscode#189787]
Does this issue occur when all extensions are disabled?: No

- VS Code Version: 1.81.0
- OS Version: macOS 14.0 Beta (23A5301h)

Steps to Reproduce:

1. no idea but see screenshot
<img width="1622" alt="Screenshot 2023-08-07 at 10 24 14" src="https://github.com/microsoft/vscode/assets/9585787/d27bc478-2da3-4169-a742-008fd61d91a5">
<img width="1032" alt="Screenshot 2023-08-07 at 10 26 02" src="https://github.com/microsoft/vscode/assets/9585787/4875b5e9-f83b-4269-813c-60f8c9932b31">

The process explorer in vscode is not showing the complete story... shouldn't the cpu of a parent be based on the aggregate of child processes and not independent from that?

**Comment by Tyriar** [comment]
No it's meant to be independent as it's a different process
