### ISSUE TITLE
Unable to use Ctrl+C shortcut to terminate tasks in the terminal on some Mac machines (using VSCode Remote SSH)

### ISSUE THREAD

**Issue by Arkycher** [microsoft/vscode#189786]
On certain Mac machines, I am unable to use the Ctrl+C keyboard shortcut to terminate tasks running in the integrated terminal within Visual Studio Code when connected via Remote SSH. However, using other terminal applications, the Ctrl+C shortcut works as expected.

### Mac Version:

```
ProductName: Mac OS X
ProductVersion: 10.14.6
BuildVersion: 18G103
```
### VSCode Version:

```
Version: 1.81.0 (system setup)
Commit: 6445d93c81ebe42c4cbd7a60712e0b17d9463e97
Date: 2023-08-02T12:37:13.485Z
Electron: 22.3.18
ElectronBuildId: 22689846
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Windows_NT x64 10.0.17763
```
## Additional Context:

The issue occurs when using VSCode's Remote SSH extension to connect to the Mac machine.
The Ctrl+C shortcut works as expected in other terminal applications on the same Mac machine.
## Steps to Reproduce:

1. Open Visual Studio Code on a local machine.
2. Connect to an affected Mac machine using the Remote SSH extension.
3. Launch the integrated terminal.
4. Run a task or command in the terminal.
5. Attempt to use the Ctrl+C keyboard shortcut to terminate the task.
### Expected Behavior:
The task should be terminated when pressing Ctrl+C.

### Actual Behavior:
The task does not terminate when pressing Ctrl+C.

Please let me know if there are any workarounds or if additional information is needed. Thank you!

**Comment by deepak1556** [comment]
Thanks for the repro steps, merging to https://github.com/microsoft/vscode/issues/184713
