### ISSUE TITLE
Allow to theme foreground color of status bar entries on hover

### ISSUE THREAD

**Issue by StephaneAdeso** [microsoft/vscode#189706]
Hi. i am creating a theme pack for VSCode. 
I have discovered that there is a  ` "statusBarItem.hoverBackground" ` to customize the background color of a status bar hovered item but there is no option to customize the color of the hovered item foreground color. Something like ` "statusBarItem.hoverForeground" `

![image](https://github.com/microsoft/vscode/assets/55595063/b014bcce-fc58-4979-a332-b31c9b42b4f5)

**Comment by bpasero** [comment]
Yeah there seems to be colors like `statusBarItem.hoverBackground` but not the relevant foreground colors.

//cc @daviddossett @hbons

**Comment by daviddossett** [comment]
Added `statusBarItem.hoverForeground` with values defaulting to `statusBar.foreground` in #190906. You'll be able to set that manually in your settings.json or in the theme itself.

**Comment by bpasero** [comment]
@daviddossett nice, but we do have more hover backgrounds:

<img width="725" alt="image" src="https://github.com/microsoft/vscode/assets/900690/a8f15a28-a46c-4d11-9bfc-e42deb9645eb">

I am not sure about the compact one but maybe prominent one needs it too?

**Comment by daviddossett** [comment]
Added via #190925
