### ISSUE TITLE
"Disconnected. Attempting to Reconnect" 

### ISSUE THREAD

**Issue by Huda-tulip** [microsoft/vscode#189758]
Hello,
 I am just trying to open the codespace of cs50 but it is not connecting correctly, it keeps showing up an error message of disconnection, I press connect again and it keeps loading and the error shows up again and again. It is not an internet issue because I tried and tied my laptop to a hotspot.
I wish you could  help me though, 
Thank you.
Version: 1.81.0
Commit: 6445d93c81ebe42c4cbd7a60712e0b17d9463e97
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36
Embedder: codespaces

**Comment by okkotssu** [comment]
same here, did you please find a solution ?

**Comment by chrmarti** [comment]
Thanks for your feedback. Since it concerns GitHub Codespaces, could you please start a discussion about it here: https://github.com/community/community/discussions/categories/codespaces
