### ISSUE TITLE
VSCode Not Displaying Merge Conflicts In Editor

### ISSUE THREAD

**Issue by conradwt** [microsoft/vscode#189700]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.82.0-insider
- OS Version: macOS 13.5

Steps to Reproduce:

1. generate merge conflict

Expected

- See old-style merge editor

Actual

- See only links to GitHub

**Comment by hediet** [comment]
Thanks for reporting! Can you share a screenshot/screenrecording?

**Comment by conradwt** [comment]
@hediet Here's a screenshot:

![Screenshot 2023-08-10 at 3 32 12 AM](https://github.com/microsoft/vscode/assets/20219/9dd3666c-aed2-4837-93e3-f554f87f1895)

**Comment by hediet** [comment]
The merge editor only solves conflicts produced by git, not by github. You have to solve the conflict locally.

**Comment by conradwt** [comment]
@hediet This is odd because this functionality used to work from VSCode.  Now, you're telling me that it doesn't work because it's GitHub even though it uses `git`.  Then I don't understand why there's `git` integration within the VSCode because I doubt that people are only using `git` locally.

**Comment by hediet** [comment]
> This is odd because this functionality used to work from VSCode. 

The merge editor only works with locally checked out branches and with conflicts that git reported.
