### ISSUE TITLE
New titlebar doesn't work with hyperdock on mac

### ISSUE THREAD

**Issue by MuhsinFatih** [Microsoft/vscode#18971]
I know this is an extreme case but I would be happy if this was fixed. I use [hyperdock](https://bahoom.com/hyperdock/) to bring the snapping window functionality that windows has to mac. Only vscode doesn't respect the snapping feature. I am not exactly sure after which update this issue started, but as far as I know it started after the titlebar got its custom look.

- VSCode Version: 1.8.1
- OS Version: MacOS Sierra 10.12.2

Steps to Reproduce:

1. Download [hyperdock](https://bahoom.com/hyperdock/) . It is free to try, you can download to reproduce the bug
2. Snap other windows like your web browser etc to make sure it's working
3. Try snapping vscode to a side. It won't work

**Comment by bpasero** [comment]
Workaround: configure `"window.titleBarStyle": "native"`

**Comment by bpasero** [comment]
Btw I am using [Better Snap Tool](https://itunes.apple.com/ch/app/bettersnaptool/id417375580?mt=12) and it seems to work just fine with the custom title.

**Comment by MuhsinFatih** [comment]
Wow. such quick response. Thanks :)

**Comment by bpasero** [comment]
Closing, workaround exists.

**Comment by MuhsinFatih** [comment]
Oh, just a sidenote: shortcuts do work: ctrl+alt+arrowkeys
