### ISSUE TITLE
Unable to install extension update

### ISSUE THREAD

**Issue by zlispositive** [microsoft/vscode#189701]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.81.0 (Universal)
- OS Version: Darwin arm64 22.6.0

Commit: 6445d93c81ebe42c4cbd7a60712e0b17d9463e97
Date: 2023-08-02T12:40:02.782Z
Electron: 22.3.18
ElectronBuildId: 22689846
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0

After the latest update, I am unable to install any extension update, neither from clicking the update button or from VSIX file.

**Comment by Oguidan** [comment]
Dude try to update again you vs code or reinstall because I have the last version and I don't have this problem.

**Comment by zlispositive** [comment]
It may seems like a network issue. I am able to update everything when I am in office.
