### ISSUE TITLE
JSDoc `@api` tag

### ISSUE THREAD

**Issue by aweebit** [microsoft/vscode#189812]
I have been looking for documentation on the `@api` tag used to mark private API methods in [tj/commander.js](https://github.com/tj/commander.js), but I could not find any. However, VSCode clearly has support for it because the words `private`, `protected` and `public` following the tag are highlighted differently than other words. I would like to find the code responsible for the highlighting so as to learn about how and why it was added. Could you please point me in the right direction?

**Comment by aweebit** [comment]
I found 9ad4bcd66f8c7d9bd71a400efd07f1fdaa454ab2 introducing support for the `@api` tag, but the commit does not seem to be included in any PR, and since there is also no commit description, I could not find any explanation on why the support was added. I would be grateful if you could explain it to me. Is there documentation on the tag somewhere I could not find,  or was it simply added to support some de facto usage like the one in the aforementioned Commander library?

**Comment by mjbvz** [comment]
The grammar that provides jsdoc highlighting lives in https://github.com/microsoft/TypeScript-TmLanguage
