### ISSUE TITLE
`'setTrafficLightPosition'` is deprecated and will be removed. Please use `'setWindowButtonPosition'` instead.

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#189849]
![image](https://github.com/microsoft/vscode/assets/900690/93497ee1-4a52-4b1c-8cb1-06fc8c86b4a6)

**Comment by deepak1556** [comment]
Refs https://github.com/electron/electron/blob/main/docs/breaking-changes.md#deprecated-browserwindowsettrafficlightpositionposition
