### ISSUE TITLE
debug v0.10.6 launch chrome attach to wrong tab

### ISSUE THREAD

**Issue by gertcuykens** [Microsoft/vscode#1898]
When you launch chrome in debug mode, it opens a new tab but vcode attaches to soon to the already opened tab that can be any website. It should attach to the tab it created instead.

```json
{
	"version": "0.10.6",
	"configurations": [
        {
            "name": "Launch chrome",
            "type": "chrome",
            "request": "launch",
            "url": "http://localhost:8080/",
            "webRoot": "default",
            "sourceMaps": true
        }
	]
}
```

**Comment by isidorn** [comment]
This is an issue with the vscode chrome debug extension not vscode itself, please file it under this repo https://github.com/Microsoft/vscode-chrome-debug
fyi @roblourens

**Comment by gertcuykens** [comment]
https://github.com/Microsoft/vscode-chrome-debug/issues/79
