### ISSUE TITLE
Unified, customizable schedule for all updates

### ISSUE THREAD

**Issue by mcandre** [microsoft/vscode#189890]
VSCode bugs me continuously throughout the day with all manner of annoying updates.

I request an option to set a more predictable update schedule, such as once a day or once a week. That way, I can conserve network resources and maintain focus on development.

This applies to polling for plugin updates, as well as polling for updates to the text editor application itself.

**Comment by joaomoreno** [comment]
The `update.mode` lets you change to a `manual` mode. The `extensions.autoCheckUpdates` and `extensions.autoUpdate` settings allow you to control that for extensions.
