### ISSUE TITLE
Explore using sysroot instead of LTS containers for building native modules in CI

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#189885]
Currently, these (the `vscode-linux-build-agent:*` images) are still on Node 16.

**Comment by deepak1556** [comment]
I believe this was opened as a follow-up to https://github.com/microsoft/vscode/pull/189886, I have added short-term workarounds in https://github.com/microsoft/vscode/pull/189904. As mentioned in https://github.com/microsoft/vscode/pull/189886#issuecomment-1668988402 we cannot make the switch to Node 18 on these images without bumping the base image which won't happen soon. I can explore the long term solution of using sysroots as part of this issue instead.

**Comment by deepak1556** [comment]
Started work here https://github.com/microsoft/vscode/pull/192513, overall looking good with nice results. Need some cleanup before it can be merged.
