### ISSUE TITLE
Running bash in the integrated terminal fails to delete characters

### ISSUE THREAD

**Issue by robertohuertasm** [Microsoft/vscode#18985]
- VSCode Version: 1.9.0-insider
- OS Version: Windows 10

Steps to Reproduce:

1. Open the integrated terminal.
2. Type `bash` (I use the Git for Windows terminal here)
3. Write something and try to delete it.
4. Instead of deleting the previous characters it seems to write empty spaces.

A similar erratic behavior is also present into the latest stable version but it's not that bad. In the stable version, if you delete some characters, it can happen that some of them are really deleted although still visible.

**Comment by Tyriar** [comment]
Hmm, this specific problem should have been fixed recently, are you on today's insiders build?

**Comment by robertohuertasm** [comment]
I'm in the latest version, yes

**Comment by Tyriar** [comment]
I can repro, something must have gone wrong with a recent dependency upgrade.

**Comment by Tyriar** [comment]
As a workaround it should work by setting `$TERM`:

```bash
TERM=xterm
```

**Comment by robertohuertasm** [comment]
Hi @Tyriar, what do you mean with setting `$TERM`? 😥

**Comment by Tyriar** [comment]
In your (broken) git bash setting just run `TERM=xterm`, that should fix the backspace issue.

**Comment by robertohuertasm** [comment]
It's working! I guess this will be fixed in the next stable release?

**Comment by Tyriar** [comment]
Yes it should be, it should be fixed in next Insiders as well.
