### ISSUE TITLE
Search in notebooks perf issues when using ssh

### ISSUE THREAD

**Issue by amunger** [microsoft/vscode#189845]
I can confirm the search issue only happens with ssh remote, and when the connection is not stable. I've tried locally, doing the notebook as large as possible, or with a notebook with problems when in remote, and everything is fine. I'm sure the other issue comes from the same cause. In general, I have many problems with VScode with an unstable connection. I'm now during holidays in a house that has a mobile connection only, and I can literally watch youtube videos, but VScode sometimes gets blocked with a notebook in remote to EC2...

_Originally posted by @marctorsoc in https://github.com/microsoft/vscode-jupyter/issues/13338#issuecomment-1662319184_

**Comment by marctorsoc** [comment]
FWIW, I found a trick to fix this which is:
- I want to search for "get_matches"
- I search for it but get no results
- I remove the "s" and write it again
- Now it shows the results

This happens esp. with long notebooks. Not sure if only in ssh or would happen in local too

**Comment by rebornix** [comment]
We have made improvements to how search works with notebooks (when the notebook is open), it would be great if you can give this a try and see if you still have issues.
