### ISSUE TITLE
The terminal becomes full back (including the fonts.)

### ISSUE THREAD

**Issue by alienvelin** [microsoft/vscode#189833]
Type: <b>Bug</b>

Recently, started using the VS code and my terminal is full black, text, anything i write etc.
I tried reinstalling the whole application, remove all extentions and tried to delete all the setting i have ever had on the VS code, nothing helped. I check all of the forums i could set a hand on, but nothing helped. 
The terminal is running, i mean i see the cursor of what i am writing, i am able to copy from it, but i have to write blind and i dont see the results.

I will really appriciate if anyone give me a hand of fixing that.

Thank you in advance.

VS Code version: Code 1.81.0 (6445d93c81ebe42c4cbd7a60712e0b17d9463e97, 2023-08-02T12:37:13.485Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9900 CPU @ 3.10GHz (16 x 3096)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.92GB (21.76GB free)|
|Process Argv|--crash-reporter-id 2deaacf1-a55c-466f-97e1-5605a625d5b6|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
powershell|ms-|2023.6.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
py29gd2263cf:30792227
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
vscccc:30803845
3biah626:30602489
f6dab269:30613381
showlangstatbar:30737416
vsctsb:30748421
03d35959:30757346
pythonfmttext:30731395
pythoncmv:30756943
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
gsofa:30804715
pythonnosmt12:30797651
pythonidxptcf:30805731
pythonnoceb:30805159
e537b577:30795824
dsvsc013:30795093
dsvsc014:30804076

```

</details>

**Comment by Tyriar** [comment]
Does tweaking gpu acceleration help? https://code.visualstudio.com/docs/terminal/appearance#_gpu-acceleration

**Comment by alienvelin** [comment]
> Does tweaking gpu acceleration help? https://code.visualstudio.com/docs/terminal/appearance#_gpu-acceleration

I changed the setting GPU acceleration to off and everything went back to normal. 

Thank you!
