### ISSUE TITLE
SCSS formatting issue when using "vscode.css-language-features"

### ISSUE THREAD

**Issue by Casimodo72** [microsoft/vscode#189801]
I' getting an SCSS formatting issue when using "vscode.css-language-features".

Does this issue occur when all extensions are disabled?: Yes

- VS Code Version:  1.81.0 
- OS Version: Windows_NT x64 10.0.19045 

Steps to reproduce:

Ensure  "vscode.css-language-features" is used.
In my Settings.json I have:
```json
"[scss]": {
    "editor.defaultFormatter": "vscode.css-language-features"
}
```
Add something like this to your SCSS file:
```scss
$my-theme: mat.define-dark-theme((
    color: (
        primary: $my-primary,
        accent: $my-accent,
        warn: $my-warn,
    ),
    typography: $my-typography,
    density: 0,
));
```
After formatting the SCSS file, it gets formatted to:
```scss
$my-theme: mat.define-dark-theme((color: (primary: $my-primary,
                accent: $my-accent,
                warn: $my-warn,
            ),
            typography: $my-typography,,
            density: 0,
        ));
```

**Comment by aeschli** [comment]
We use [beautifyjs](http://jsbeautifier.org/) as the underlying SCSS formatter. Would you mind filing this request directly against https://github.com/beautify-web/js-beautify ?
