### ISSUE TITLE
Please expose TerminalInstance.onClose on ITerminalInstance

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#18986]
I am experimenting with reusing the terminal and to make this work when the user actually closes the terminal (presses the garbage bin button) I need to capture this and remove the terminal from my list of reusable terminals.

**Comment by Tyriar** [comment]
Exposed and renamed to `onDisposed` so it's more consistent with surrounding code.

**Comment by dbaeumer** [comment]
Thanks
