### ISSUE TITLE
Tab title switches to English on click

### ISSUE THREAD

**Issue by levrik** [Microsoft/vscode#18989]
- VSCode Version: 1.9.0-insider ee9d91c05fa571de56c41383cceee30b05b0a2f6
- OS Version: Windows 10

Steps to Reproduce:

![2017-01-21_22-28-20](https://cloud.githubusercontent.com/assets/9491603/22177918/0cf34b5e-e029-11e6-8b55-06124bb29a95.gif)
This issue also occurs if you click directly on the first tab. Just clicked through the other tabs to demonstrate that they are not affected.

**Comment by bpasero** [comment]
Thanks, this will be fixed once we got our english strings localized. In this case there was a new string added that is not yet translated.
