### ISSUE TITLE
[WelcomeUX]  Misaligned keyboard Shortcut in Interface Overview

### ISSUE THREAD

**Issue by seanmcbreen** [Microsoft/vscode#18983]
Testing #18091 

MacOS

the shortcut is not centered with the text for problems view.  All other seam ok...

![image](https://cloud.githubusercontent.com/assets/1051190/22176538/f63e4330-dfc1-11e6-9d9d-4381c4a132ac.png)

**Comment by chrmarti** [comment]
Fixed with #19164
