### ISSUE TITLE
Allow the ability to "preview" large files

### ISSUE THREAD

**Issue by drusellers** [Microsoft/vscode#18981]
- VSCode Version: 1.8.1
- OS Version: Mac OSX Sierra

I often have to deal with large text files and currently if I want to just take a peek at one I have to drop to powershell and remember how `Get-Content` works so I can pull off the top 100 lines of the file then open it in VS Code. I have this problem in most editors due to the size of the files. Say 500MB+ CSV dumps.

I would love if VS Code could look at the file size and suggest a "peek" of the Top 100/500 lines etc.

**Comment by mjbvz** [comment]
Closing. We have improved our large file support recently. Please try more recent VS Code builds and let us know if you run into any problems
