### ISSUE TITLE
Adopting dns result order changes with Node v18 update

### ISSUE THREAD

**Issue by deepak1556** [microsoft/vscode#189805]
The [change](https://github.com/nodejs/node/commit/1b2749ecbe) comes in via Electron 25 update https://github.com/microsoft/vscode/pull/188268 which bumps our Node.js version from v16 -> v18. Node.js no longer sorts the DNS lookup results from the OS. This might break situations where one might expect to connect to a ipv4 localhost but OS resolves `localhost` to ipv6 address, which would result in `ECONNREFUSED`. Node.js has provided a couple of different settings to control this behavior

i) Process wide cli flag [--dns-result-order=ipv4first|verbatim](https://nodejs.org/dist/latest-v18.x/docs/api/cli.html#--dns-result-orderorder)
ii) Per thread API in the dns module, [dns.setDefaultResultOder](https://nodejs.org/dist/latest-v18.x/docs/api/dns.html#dnssetdefaultresultorderorder)
iii) Socket option [autoSelectFamily](https://nodejs.org/dist/latest-v18.x/docs/api/net.html#socketconnectoptions-connectlistener) to use happy eyeballs algorithm that will attempt to connect with ipv4 and ipv6 addresses until a connection is established.

I have adopted (i) in [src/vs/server/node/extensionHostConnection.ts](https://github.com/microsoft/vscode/blob/93d3731736cc6fefbd63810d5fb2d57bedc84ca0/src/vs/server/node/extensionHostConnection.ts#L259) and [src/vs/workbench/services/extensions/electron-sandbox/localProcessExtensionHost.ts](https://github.com/microsoft/vscode/blob/93d3731736cc6fefbd63810d5fb2d57bedc84ca0/src/vs/workbench/services/extensions/electron-sandbox/localProcessExtensionHost.ts#L253) to provide the old behavior in extension host spawned from both client and server. @alexdima let me know if we want to plan an action item to remove this workaround in future releases of VSCode.

This issue is created for callsites that are binding to `127.0.0.1` to verify if they are impacted by the Node.js change when connecting to these servers,

- [x] [cli/src/commands/tunnels.rs](https://github.com/microsoft/vscode/blob/dd4c9da8593873263d96bb2f7d36f4e722cd2808/cli/src/commands/tunnels.rs#L161) @connor4312 
- [x] [cli/src/tunnels/control_server.rs](https://github.com/microsoft/vscode/blob/dd4c9da8593873263d96bb2f7d36f4e722cd2808/cli/src/tunnels/control_server.rs#L926-L929) @connor4312 
- [x] [extensions/github-authentication/src/node/authServer.ts](https://github.com/microsoft/vscode/blob/dd4c9da8593873263d96bb2f7d36f4e722cd2808/extensions/github-authentication/src/node/authServer.ts#L176) @TylerLeonhardt 
- [x] [extensions/microsoft-authentication/src/node/authServer.ts](https://github.com/microsoft/vscode/blob/dd4c9da8593873263d96bb2f7d36f4e722cd2808/extensions/microsoft-authentication/src/node/authServer.ts#L176) @TylerLeonhardt 
- [x] [extensions/vscode-test-resolver/src/extension.ts](https://github.com/microsoft/vscode/blob/main/extensions/vscode-test-resolver/src/extension.ts) @aeschli 
- [x] [src/vs/base/node/ports.ts](https://github.com/microsoft/vscode/blob/dd4c9da8593873263d96bb2f7d36f4e722cd2808/src/vs/base/node/ports.ts#L63) @alexdima 
- [x] [src/vs/platform/tunnel/node/tunnelService.ts](https://github.com/microsoft/vscode/blob/dd4c9da8593873263d96bb2f7d36f4e722cd2808/src/vs/platform/tunnel/node/tunnelService.ts#L87) @alexr00 
- [x] [src/vs/platform/webview/common/webviewPortMapping.ts](https://github.com/microsoft/vscode/blob/dd4c9da8593873263d96bb2f7d36f4e722cd2808/src/vs/platform/webview/common/webviewPortMapping.ts#L47) @mjbvz

**Comment by TylerLeonhardt** [comment]
The auth extensions spin up servers that get open in the user's web browser. I verified the flows still work post-electron update.

**Comment by aeschli** [comment]
I'm quite sure this still works as the test resolver is used for run our remote integration tests.
