### ISSUE TITLE
The Copilot chat tab is empty.

### ISSUE THREAD

**Issue by zalewskigrzegorz** [microsoft/vscode#189831]
Type: <b>Bug</b>

Open Visual Studio Code for Insiders and open Copilot Chat.

VS Code version: Code - Insiders 1.82.0-insider (1606401f5b761397488f53b75130809fba073194, 2023-08-07T05:36:30.820Z)
OS version: Darwin arm64 22.5.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M2 Pro (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|4, 2, 3|
|Memory (System)|16.00GB (0.04GB free)|
|Process Argv|--crash-reporter-id c241e72a-ae9b-418b-976b-96e1f8e981fd|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (60)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-openapi|42C|4.18.6
better-comments|aar|3.0.2
vscode-languagetool|ada|3.8.0
numbered-bookmarks|ale|8.4.0
aws-toolkit-vscode|ama|1.83.0
cypress-snippets|and|1.2.0
vs-redoc-viewer|Ati|0.0.3
markdown-preview-github-styles|bie|2.0.2
turbo-console-log|Cha|2.9.6
test-utils|chr|1.0.2
npm-intellisense|chr|1.4.4
regex|chr|0.4.0
cypress-snippets|Cli|0.0.5
codeque|Cod|0.25.1
vscode-eslint|dba|2.4.2
xml|Dot|2.5.1
gitlens|eam|14.2.0
vscode-html-css|ecm|1.13.1
EditorConfig|Edi|0.16.4
prettier-vscode|esb|10.1.0
vscode-firefox-debug|fir|2.9.8
vscode-jest-runner|fir|0.4.66
auto-rename-tag|for|0.1.10
copilot|Git|1.101.317
copilot-chat|Git|0.7.2023080701
vscode-pull-request-github|Git|0.70.0
vscode-jsonnet|Gra|0.3.3
hcl|has|0.3.2
terraform|has|2.27.2023071109
cypress-fixture-intellisense|Jos|1.2.0
intellij-idea-keybindings|k--|1.5.9
template-string-converter|meg|0.6.1
vscode-cypress-extension-pack|mik|0.1.1
vscode-docker|ms-|1.26.0
remote-containers|ms-|0.305.0
vsliveshare|ms-|1.0.5877
vscode-streamdeck|nic|4.1.6
angular-console|nrw|18.6.0
vscode-css-peek|pra|4.4.1
prisma|Pri|5.1.0
vscode-yaml|red|1.14.0
openapi-vs-code|Red|0.2.24
vscode-nomad-pack-go-template|Ric|0.2.0
LiveServer|rit|5.7.9
vscode-cy-helper|She|1.2.2
sonarlint-vscode|Son|3.20.2
code-spell-checker|str|2.20.5
vscode-extension-open-cypress|tnr|0.0.14
sort-lines|Tyr|1.10.2
errorlens|use|3.12.0
intellicode-api-usage-examples|Vis|0.2.7
vscodeintellicode|Vis|1.2.30
console-ninja|Wal|0.0.193
quokka-vscode|Wal|1.0.551
wallaby-extension-pack|Wal|1.0.1
wallaby-vscode|Wal|1.0.364
vscode-import-cost|wix|3.3.0
bracket-lens|wra|1.5.3
eno|Wsc|2.3.53
markdown-all-in-one|yzh|3.5.1

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythontb:30258533
pythonptprofiler:30281269
vshan820:30294714
vscod805:30301674
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30404738
py29gd2263:30784851
vscaac:30438845
vsclangdf:30492506
c4g48928:30535728
dsvsc012:30540252
pynewext54:30618038
showlangstatbar:30737417
24365598:30687740
pythonfmttext:30716741
pythoncmvfstr:30726892
fixshowwlkth:30771523
showindicator:30805243
pythongtdpath:30726887
i26e3531:30792625
gsofa:30797620
welcomedialog:30800244
pythonnosmt12:30779711
pythonidxpt:30768918
pythonnoceb:30776497
copilotsettingt:30767686
e537b577:30772214
h0f32768:30792099
asynctokenver:30799129
dsvsc013:30777762
dsvsc014:30777825
diffeditorv2:30786206

```

</details>

**Comment by joyceerhl** [comment]
\closedWith https://github.com/microsoft/vscode/commit/f69859cd30a82cda6ac6fe1c5f63688a3a5d0c2c
