### ISSUE TITLE
Copilot diff overlaid on Code

### ISSUE THREAD

**Issue by henrychris** [microsoft/vscode#189880]
Type: <b>Bug</b>

When using Copilot, I asked for a fix for a code I selected in-editor. This opened the Copilot chat overlay and showed a diff between the current code and the proposed change. I hit the send icon, by accident, then the Esc key, as I didn't want the change.
The diff overlay stayed, even after I closed the file and opened another file.
The discard button has no effect.

VS Code version: Code 1.81.0 (6445d93c81ebe42c4cbd7a60712e0b17d9463e97, 2023-08-02T12:37:13.485Z)
OS version: Windows_NT x64 10.0.22621
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-10110U CPU @ 2.10GHz (4 x 2592)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.81GB (7.89GB free)|
|Process Argv|C:\\Users\\user\\Documents\\GitHub\\epBackOffice\\epAgentBackoffice\\Core\\MappingProfile.cs --crash-reporter-id 7952371c-8d10-42bd-ad4e-3799d5c2c9aa|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (27)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|3.0.2
npm-intellisense|chr|1.4.4
gitlens|eam|14.2.0
code-runner|for|0.12.0
copilot|Git|1.101.317
copilot-chat|Git|0.6.0
todo-tree|Gru|0.0.226
csharpextensions|kre|1.7.3
blazorwasm-companion|ms-|1.1.4
csdevkit|ms-|0.3.21
csharp|ms-|2.0.328
vscode-dotnet-runtime|ms-|1.6.0
vscodeintellicode-csharp|ms-|0.1.26
black-formatter|ms-|2023.4.1
python|ms-|2023.14.0
vscode-pylance|ms-|2023.8.10
vscode-jupyter-cell-tags|ms-|0.1.8
remote-wsl|ms-|0.81.0
hexeditor|ms-|1.9.12
sqltools|mtx|0.28.0
sqltools-driver-mssql|mtx|0.4.1
sqltools-driver-mysql|mtx|0.6.0
sqltools-driver-sqlite|mtx|0.5.0
vscode-nuget-gallery|pat|0.0.24
material-icon-theme|PKi|4.29.0
vscode-thunder-client|ran|2.10.2
LiveServer|rit|5.7.9

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
py29gd2263cf:30792227
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
vsccc:30803844
3biah626:30602489
89544117:30613380
showlangstatbar:30737416
vsctsb:30748421
03d35959:30757346
57b77579:30736110
pythonfmttext:30731395
pythoncmv:30756943
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
gsofb:30804716
pythonnosmt12:30797651
pythonidxptcf:30805731
pythonnoceb:30805159
e537b577:30795824
dsvsc013:30795093
dsvsc014:30804076

```

</details>

**Comment by lvasuraju-ebay** [comment]
Experiencing the same annoying issue

**Comment by ulugbekna** [comment]
This should be fixed.
