### ISSUE TITLE
Command Center does not respond to clicks

### ISSUE THREAD

**Issue by daviddossett** [microsoft/vscode#189973]
Insiders 1.82.0

Looks like the command center and associated toolbar buttons aren't functioning when clicked. Weirdly it seems like I can sometimes(?) get a hover state but it doesn't always work. Repeated clicks minimizes the window which makes me think the events are going straight to the titlebar and being handled as such.

https://github.com/microsoft/vscode/assets/25163139/1fd9ef02-c479-4d81-aa00-8a28d9d80185

**Comment by jrieken** [comment]
I can reproduce 😱

**Comment by bpasero** [comment]
Maybe an Electron 25 update regression with draggable regions and custom title bar?

//cc @deepak1556

**Comment by deepak1556** [comment]
@jrieken looks like `--webkit-app-region: drag` behavior on macOS is now aligned with windows and linux, the region no longer emits events. Behavior changed with this commit https://github.com/electron/electron/commit/8a926ffde4ce4af49ce833b97c884636074b0a1f and verified with the following fiddle https://gist.github.com/deepak1556/bfbc55d08a7dc4453a263d6e8d712277

Looks like we would need to revert this change https://github.com/microsoft/vscode/pull/161340 to align with Windows and Linux.

**Comment by jrieken** [comment]
Yeah, looks like drag and click isn't working for macOS anymore. It always seems like an oversight/bug but a wanted one. To enable clicking again I have added the `-webkit-app-region: no-drag;` for the CC even for mac. On the downside it means that the window cannot be repositioned from the CC anymore

**Comment by bpasero** [comment]
Slack is the same, you cannot drag from their command center either.
