### ISSUE TITLE
GitSavvy experience

### ISSUE THREAD

**Issue by mercurykd** [microsoft/vscode#189952]
https://github.com/timbrel/GitSavvy
please port this experience to the world of vscode. this is the best experience with git

**Comment by lszomoru** [comment]
@mercurykd, while I really appreciate you filing this issue it's not really actionable as it's scope is too broad in this form. It would be more helpful if you would file feature requests issue(s) with explicit features that exist in the referenced plugin that are not available in VS Code. Thank you in advance!
