### ISSUE TITLE
IDiffEditorConstructionOptions.renderSideBySide is not honored

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#189975]
On the latest Insiders, or OSS

1. Run a test that produces a diff output, e.g. with `assert.deepStrictEquals('foo', 'bar')`
2. Notice the diff editor for testing, where `renderSideBySide: true`, does not actually get rendered side by side

![Image](https://github.com/microsoft/vscode/assets/2230985/1718ff8b-b939-4fdb-b225-72e4ceb39f9f)

**Comment by connor4312** [comment]
Seems to have been caused by https://github.com/microsoft/vscode/commit/4ae1914ef14d7e17c15ebcf18bfe0aad6d295fe8

Can this this perhaps be some enum for `Never / Auto / Always`?

**Comment by hediet** [comment]
you can set `useInlineViewWhenSpaceIsLimited` to `false` in the construction options.

> Can this this perhaps be some enum like Never / Auto / Always?

Lets track that here:
* #190150
