### ISSUE TITLE
Add .npmignore as a known file type

### ISSUE THREAD

**Issue by thomas-darling** [Microsoft/vscode#18999]
- VSCode Version: 1.8.1
- OS Version: Windows 10

In Windows Explorer, when you choose to always open `.npmignore` files with VS Code, they do not get the code file icon like `.gitignore` does, but just the generic VS Code app icon. Would be nice to add this as a known file type, so those files also get the correct icon.

Meanwhile, here's a registry hack to fix it:
```
Windows Registry Editor Version 5.00

[HKEY_CLASSES_ROOT\VSCode.npmignore]
@="NPM Ignore Source File"
"AlwaysShowExt"=""

[HKEY_CLASSES_ROOT\VSCode.npmignore\DefaultIcon]
@="C:\\Program Files (x86)\\Microsoft VS Code\\resources\\app\\resources\\win32\\code_file.ico"

[HKEY_CLASSES_ROOT\VSCode.npmignore\shell]

[HKEY_CLASSES_ROOT\VSCode.npmignore\shell\open]

[HKEY_CLASSES_ROOT\VSCode.npmignore\shell\open\command]
@="\"C:\\Program Files (x86)\\Microsoft VS Code\\Code.exe\" \"%1\""

[HKEY_CLASSES_ROOT\.npmignore]

[HKEY_CLASSES_ROOT\.npmignore\OpenWithProgids]
"VSCode.npmignore"=""
```

**Comment by joaomoreno** [comment]
Care to submit a PR?

https://github.com/Microsoft/vscode/blob/master/build/win32/code.iss#L311
