### ISSUE TITLE
GET https://code.visualstudio.com/raw/css/inproduct_releasenotes.css net::ERR_BLOCKED_BY_RESPONSE.NotSameOriginAfterDefaultedToSameOriginByCoep 200

### ISSUE THREAD

**Issue by tamuratak** [microsoft/vscode#189995]
Does this issue occur when all extensions are disabled?: Yes

Version: 1.82.0-insider (Universal)
Commit: 85daa35afb86202badbee79532537bf226961f25
Date: 2023-08-08T07:43:56.448Z
Electron: 25.4.0
ElectronBuildId: 22901934
Chromium: 114.0.5735.248
Node.js: 18.15.0
V8: 11.4.183.27-electron.0
OS: Darwin arm64 20.6.0

Steps to Reproduce:

1. Start VS Code Insiders with COI. `code-insiders --enable-coi`
2. Open the release note.
3. Developer Tools console says:

```
GET https://code.visualstudio.com/raw/css/inproduct_releasenotes.css net::ERR_BLOCKED_BY_RESPONSE.NotSameOriginAfterDefaultedToSameOriginByCoep 200
```

Related to #22668

**Comment by joaomoreno** [comment]
cc @jrieken

**Comment by PotatoLu666** [comment]
+1 I have the same error in insider.vscode.dev

**Comment by jrieken** [comment]
@rzhao271 This is an issue with `https://code.visualstudio.com/` - it needs to set the [CORP](https://developer.mozilla.org/en-US/docs/Web/HTTP/Cross-Origin_Resource_Policy) header. 

I have added this for September because for vscode.dev we'll ship COI enabled by default this month. Let me know if you need further help or explanation

**Comment by joaomoreno** [comment]
It seems that the only thing this breaks is the "Scroll to Top" action in the bottom right corner:

<img width="505" alt="image" src="https://github.com/microsoft/vscode/assets/22350/ab1822cf-d996-4157-9e74-0c7401531f10">

An alternative quick fix to this, unrelated to COI, would be to just drop that request altogether, two options:

1. Drop the whole "Scroll to Top" action;
2. Move that to core.

**Comment by rzhao271** [comment]
Moving the issue to October
CC @sbatten

**Comment by rzhao271** [comment]
Fixed with the latest website deploy
