### ISSUE TITLE
Dragging file from remote explorer to local produces strange ssh-remote+<name>/.inetloc file

### ISSUE THREAD

**Issue by 3f6a** [microsoft/vscode#189966]
When I try to drag a file from the Explorer side bar, on a remote (SSH) vscode instance, to a local directory on Finder (macOS), it produces a file named:

```
ssh-remote+<name>/.inetloc file
```

where `<name>` is the remote name. I instead would like that the file I dragged from the remote, gets copied to my local computer, at the location where I dragged it.

Does this issue occur when all extensions are disabled?: Yes (only Remote-SSH extension enabled)

- VS Code Version: 
- Version: 1.81.0 (Universal)
Commit: 6445d93c81ebe42c4cbd7a60712e0b17d9463e97
Date: 2023-08-02T12:40:02.782Z (6 days ago)
Electron: 22.3.18
ElectronBuildId: 22689846
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Darwin arm64 22.6.0

- OS Version: macOS

**Comment by q99433** [comment]
I am also encountering this problem now. Is there any progress?

**Comment by lramos15** [comment]
Duplicate https://github.com/microsoft/vscode/issues/93599
