### ISSUE TITLE
Display warning when extension node version constraint is not met

### ISSUE THREAD

**Issue by felixfbecker** [Microsoft/vscode#1899]
I've had [several issues](https://github.com/felixfbecker/vscode-php-debug/issues/9) where people reported my debug adapter was not working and the reason was they had an old Node version installed. I have therefor added a `node` version constraint to my package.json, but testing this with some very high version, VS Code doesn't seem to read this value. It would be nice if it would display a warning in that case, as the version VS Code uses doesnt even always match the installed one (I have 5.3 installed and Code uses 4.1.1, on Windows that is).

**Comment by joaomoreno** [comment]
@alexandrudima is this feasible?

**Comment by weinand** [comment]
@felixfbecker VSCode always runs debug adapters in the node version that the underlying electron is using (because is forks them). So the node version used for running the debug adapter should be independent from the node version installed. Only if you run the debug adapter in server mode, does the installed node version matter.

**Comment by alexandrudima** [comment]
As @weinand mentions, VSCode (through Electron) embeds a certain node version. 

![image](https://cloud.githubusercontent.com/assets/5047891/12259937/32996718-b919-11e5-8812-96deeff6d5d3.png)

I think the documentation around debug adapters should be made more clear to signal than an extension author should try to setup the same node version as the VSCode it is targeting when using server mode for a debug adapter (which is only a development time mode for a debug adapter, once users install a debug adapter it doesn't run in server mode, right?).

@weinand  Perhaps we can document a command that uses Electron in node mode for server mode debug adapters (i.e. make even the server mode runtime of debug adapters use the same node version as VSCode)?

@felixfbecker Such a check on our side would not really help you. Imagine you would ask for `node >= 5`, we ship with `node` `v4.1.1`, so your extension will be disabled at startup and no users of VSCode would ever get to use your extension.

**Comment by felixfbecker** [comment]
@alexandrudima I see. I guess I have to limit this to a `vscode` version constraint - that means when you update Electron with a new major Node version, there has to be a new major VS Code version.

**Comment by alexandrudima** [comment]
@felixfbecker That is correct, a new major node version should force a new major VS Code version. However, I'm not sure how we're really going to handle that given a new major VS Code version would invalidate all published extensions.

fyi @egamma

**Comment by felixfbecker** [comment]
@alexandrudima Also to note, while Code is on 0.x it is technically not under semver. But the convention is on 0.x to treat minor versions like breaking changes, so NPM will match a constraint like `^0.10.6` to `0.10.7`, but not `0.11.0`
