### ISSUE TITLE
VS Code crashes on startup unless --no-sandbox is passed as cmd arg

### ISSUE THREAD

**Issue by derekantrican** [microsoft/vscode#189949]
Does this issue occur when all extensions are disabled?: Yes

Version: 1.81.0 (system setup)
Commit: 6445d93c81ebe42c4cbd7a60712e0b17d9463e97
Date: 2023-08-02T12:37:13.485Z
Electron: 22.3.18
ElectronBuildId: 22689846
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Windows_NT x64 10.0.22621

Very similar to this issue: [#81056](https://github.com/microsoft/vscode/issues/81056)

If I launch code (either from cmd as `code` or from start menu) I get the following error message dialog:

> The window terminated unexpectedly (reason: 'launch-failed', code: '18')

If I append `--no-sandbox` to my command, it seems to work just fine (plus, additional windows seem to recognize this has already been set for the currently-open window and don't need the additional arg).

There doesn't seem to be an option in the settings to disable the sandbox, so this is pretty annoying to encounter the crash and every time re-run my command with `--no-sandbox`

**Comment by deepak1556** [comment]
Please try the setting defined in https://code.visualstudio.com/updates/v1_80#_disable-chromium-sandbox

**Comment by derekantrican** [comment]
Thanks, but that didn't work - the behavior is the same

**Comment by deepak1556** [comment]
Can you share a recording of the above steps you tried ?

**Comment by derekantrican** [comment]
Well, I guess the "demo gods" are against me. I reset my argv.json and to show doing it again in a recording and then in the recording it works just fine. No idea what I did differently the first time - copied the arg & value straight from the docs.

Anyway, thanks for your help!
