### ISSUE TITLE
Consider adding ctrl/cmd+shift+. as go to symbol keybinding in accessible view

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#189974]
cc @jooyoungseo

**Comment by meganrogge** [comment]
With screen reader mode enabled, focus an item that has an accessible view provider such as a panel chat response element. Use `alt+f2` to open the accessible view. Verify that both `ctrl/cmd+shift+o` and `ctrl/cmd+shift+.` work to go to symbol.

**Comment by alexr00** [comment]
Both keybindings work, but I see a difference between them:
`ctrl/cmd+shift+o` will toggle between "go to symbol" and escaping "go to symbol"
`ctrl/cmd+shift+.` takes you to "go to symbol" but doesn't escape out of "go to symbol" if you run it again.
