### ISSUE TITLE
add title bar to accessible view / help

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#189981]
to align with quickpick

**Comment by meganrogge** [comment]
Use `alt+f1` and `alt+f2` and verify that an "accessibility help" / "accessible view" title, respectively, appears

**Comment by alexr00** [comment]
Verified, but I think it would be more helpful it if said what the view/help is for (ex. Accessible View: Notifications).

**Comment by meganrogge** [comment]
@alexr00 I think that's not necessary here because the user invokes it from that particular context. Same for the aria label
