### ISSUE TITLE
Extension could  not be loaded in Web VSCode.

### ISSUE THREAD

**Issue by liu-lihua** [microsoft/vscode#189916]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.81.0
- OS Version: Windows10

Steps to Reproduce:

1. Start VS Code
2. Install VS Code SAS extension
3. In "Accounts" left side menu item, turn on remote tunnel access
4. Copy url link generaged by remote tunnel
5. In "Settings" left side menu item, sync settings
6. Start a browser and access the url link in step number 4, such as access 

Get error as attachment.
![error](https://github.com/microsoft/vscode/assets/120003978/9c9c92d8-4608-417b-86a8-4e3eb6825b4a)

**Comment by liu-lihua** [comment]
Even I do not execute step #2, I still got error. And the remote tunnel could not be setup.
![image](https://github.com/microsoft/vscode/assets/120003978/07857e7d-fed6-4db0-a25c-827275d0ccd4)

**Comment by liu-lihua** [comment]
Even if I logout and login with my credential to Github, it does not work. The tunnel could not be used.
![image](https://github.com/microsoft/vscode/assets/120003978/a7cee607-85a6-46a9-af0c-897d01db8acf)

**Comment by liu-lihua** [comment]
In my browser, I found the remote connection information is displayed.

![image](https://github.com/microsoft/vscode/assets/120003978/efe6667e-4fe9-4995-b8b9-8440c5f48760)

**Comment by TylerLeonhardt** [comment]
@connor4312 I think you can help more here based on the last couple messages. Let me know if it's not tunnel related.

**Comment by connor4312** [comment]
That issue was fixed by https://github.com/microsoft/vscode/pull/190110

It can be worked around by going to the Remote Explorer in some VS Code instance, right clicking on the tunnel with the conflicting name and hitting "Unregister"

The original issue looks like some vscode.dev thing; it didn't even try to load the workbench. Just googling the text it seems like that message is from the Azure Web App, maybe a WAF thing?

**Comment by liu-lihua** [comment]
Thank you both very much for the help. I tried to open another VSCode instance and connect to the tunnel. But I failed by below error. 
![image](https://github.com/microsoft/vscode/assets/120003978/d6bb51e6-f45c-4c82-954c-de839ba230eb)
I reinstalled VSCode and cleared its caches but it did not work either.

Below is what I operated and saw.
![image](https://github.com/microsoft/vscode/assets/120003978/a797350c-99ca-4b74-ac62-c2ea9ec1d716)

**Comment by liu-lihua** [comment]
Now I could connect to my desktop VSC in remote  browser successfully. I unregistered all the tunnels and turned on a new one. This issue could be closed. Thank you both very much for the help!
