### ISSUE TITLE
code still formats on save even if formatOnSave is disabled

### ISSUE THREAD

**Issue by sr229** [Microsoft/vscode#18992]
- VSCode Version: Code - Insiders 1.9.0-insider (ee9d91c05fa571de56c41383cceee30b05b0a2f6, 2017-01-20T15:08:19.064Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

|Extension|Author|Version|
|---|---|---|
|code-gnu-global|austin|0.2.1|
|npm-intellisense|christian-kohler|1.2.1|
|vscode-eslint|dbaeumer|1.2.2|
|vscode-npm-script|eg2|0.1.8|
|node-module-intellisense|leizongmin|1.3.0|
|vscode-JS-CSS-HTML-formatter|lonefy|0.2.2|
|Go|lukehoban|0.6.52|
|cpptools|ms-vscode|0.9.3|
|csharp|ms-vscode|1.6.2|
|PowerShell|ms-vscode|0.9.0|
|vscode-versionlens|pflannery|0.12.1|

---

Steps to Reproduce:

1. disable formatOnSave
2. try to save when trying to fix indentation errors from ESLint

**Comment by dbaeumer** [comment]
@sr229 does this reproduce with all extensions disabled ? I suspect an extension not honoring the formatOnSave.

**Comment by sr229** [comment]
@dbaeumer seems to be an extension since i get the expected behaviour with all extensions disabled

**Comment by dbaeumer** [comment]
@sr229 can you please file the issue against the extension then.

**Comment by mikew** [comment]
For me it was ESLint

**Comment by dbaeumer** [comment]
@mikew: do you have autoFix on save enabled. This is different than formatOnSave. ESLint doesn't format any code on save only autoFix
