### ISSUE TITLE
Test Results tab in VS Code keep popping up even if closed after each test run

### ISSUE THREAD

**Issue by maxsudik** [microsoft/vscode#189943]
Type: <b>Bug</b>

**Context:**
- Playwright Version:1.36.2
- Operating System: Mac
- Node.js version: v20.4.0
- Visual Studio Code version: Version: 1.81.0
Commit: 6445d93c81ebe42c4cbd7a60712e0b17d9463e97
Date: 2023-08-02T12:38:28.722Z
Electron: 22.3.18
ElectronBuildId: 22689846
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Darwin arm64 22.6.0
- Playwright for VSCode extension version: v1.0.15

When running a test - the tab with Test Results always pops-up.
This started happening with recent VS Code update. No matter what I do - it keeps popping-up. Before it was never showed up if not on demand.

VS Code version: Code 1.81.0 (6445d93c81ebe42c4cbd7a60712e0b17d9463e97, 2023-08-02T12:38:28.722Z)
OS version: Darwin arm64 22.6.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|4, 4, 5|
|Memory (System)|32.00GB (0.40GB free)|
|Process Argv|--crash-reporter-id 3dc3f68f-23e6-4d9e-a0b7-614e6fcd461a|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (27)</summary>

Extension|Author (truncated)|Version
---|---|---
atlascode|atl|3.0.4
vscode-generate-getter-setter|DSK|0.5.0
gitlens|eam|14.2.0
prettier-vscode|esb|10.1.0
code-runner|for|0.12.0
rainbow-csv|mec|3.7.0
template-string-converter|meg|0.6.1
vscode-azureresourcegroups|ms-|0.7.5
vscode-azurevirtualmachines|ms-|0.6.5
playwright|ms-|1.0.15
remote-containers|ms-|0.304.0
remote-ssh|ms-|0.102.0
remote-ssh-edit|ms-|0.86.0
remote-wsl|ms-|0.81.0
vscode-remote-extensionpack|ms-|0.24.0
azure-account|ms-|0.11.5
powershell|ms-|2023.6.0
remote-explorer|ms-|0.4.1
remote-server|ms-|1.4.0
vsliveshare|ms-|1.0.5877
vscode-thunder-client|ran|2.10.2
vscode-yaml|red|1.14.0
code-spell-checker|str|2.20.5
icons|tal|3.7.0
tcv-typescript-constructor-generator|toa|0.2.0
colonize|vms|2.2.2
gistfs|vsl|0.4.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263:30335439
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
py29gd2263:30792226
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
vsccc:30803844
2e4cg342:30602488
89544117:30613380
a9j8j154:30646983
showlangstatbar:30737416
vsctsb:30748421
03d35959:30757346
7ij38806:30736111
pythonfmttext:30731395
pythoncmv:30756943
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
gsofa:30804715
pythonnosmt12:30797651
pythonidxpt:30805730
pythonnoceb:30805159
e537b577:30795824
dsvsc013:30795093
dsvsc014:30804076

```

</details>

![image](https://github.com/microsoft/vscode/assets/40281293/e0e57d99-14f8-4336-830b-a5168aa04ce1)

**Comment by connor4312** [comment]
You can use the setting `testing.openTesting` to change this behavior.
