### ISSUE TITLE
Problem with auto SAVE using Chrome Dev tool and Sass Live Compiler

### ISSUE THREAD

**Issue by lukasdancak** [microsoft/vscode#189920]
Type: <b>Performance Issue</b>

Hello I am reporting this problem, described here:
https://github.com/glenn2223/vscode-live-sass-compiler/issues/306

VS Code version: Code 1.81.0 (6445d93c81ebe42c4cbd7a60712e0b17d9463e97, 2023-08-02T12:37:13.485Z)
OS version: Windows_NT x64 10.0.19045
Modes:

**Comment by aeschli** [comment]
See https://github.com/glenn2223/vscode-live-sass-compiler/issues/306#issuecomment-1682155067

**Comment by glenn2223** [comment]
_Duplicate comment from: https://github.com/glenn2223/vscode-live-sass-compiler/issues/306#issuecomment-1683081953 (my reply)_

---

@aeschli, just wondering how you'd implement this as every character added is triggering `onDidChangeTextDocument`. As I'm sure you can imagine, I can't compile with every character as the SASS would be invalid 90% of the time.

Even saving the file triggers the event - which is, obviously, duplicating the event on normal text editing. I have no problem removing the `onDidSave..` event if I/we can figure something solid out

Surely just saving the file in dev tools could trigger the "onDidSave..." event? VS Code is clearly already watching the files and could trigger the save event if the date modified changes?? 🤷

**Comment by lukasdancak** [comment]
@aeschli 

> See [glenn2223/vscode-live-sass-compiler#306 (comment)](https://github.com/glenn2223/vscode-live-sass-compiler/issues/306#issuecomment-1682155067)



> See [glenn2223/vscode-live-sass-compiler#306 (comment)](https://github.com/glenn2223/vscode-live-sass-compiler/issues/306#issuecomment-1682155067)
@aeschli 
Hi, I think that you closed my issue prematurely.....
