### ISSUE TITLE
Open folder as a workspace in Explorer View

### ISSUE THREAD

**Issue by jooyoungseo** [microsoft/vscode#189982]
Type: <b>Feature Request</b>

While navigating some folders in Ctrl+Shift+E Explorer View via arrow keys, I sometimes want to open a highlighted folder as a separate workspace. I right-clicked (shift+F10 on Windows) to see if I can find a menu like "open in a new workspace," but unfortunately, there was not any similar command.

Could you please consider adding this feature?

VS Code version: Code - Insiders 1.82.0-insider (85daa35afb86202badbee79532537bf226961f25, 2023-08-08T07:41:53.755Z)
OS version: Windows_NT x64 10.0.22621
Modes:

**Comment by lramos15** [comment]
Duplicate https://github.com/microsoft/vscode/issues/41860
