### ISSUE TITLE
Trimming trailing spaces based on file type

### ISSUE THREAD

**Issue by grafa** [Microsoft/vscode#18998]
Hi there,

I love auto trimming trailing spaces but I had to turn it off because in certain file types it breaks the syntax. For instance Jade/Pug.
It would be great if I could specify where the trimming would be disabled. Something like:

```json
files.trimTrailingWhitespaceExclude: [
    ".jade",
    ".pug",
]
```

Just simple extension recognition would do the job.

Thank you in advance.

**Comment by ramya-rao-a** [comment]
@grafa Nice timing. With #1587 you should be able to this.
@sandy081 #1587 is shipping in Jan correct?

**Comment by sandy081** [comment]
@ramya-rao-a Yes #1587 is being targetted for January. But this is scoped only to language based settings. In the above case, you can achieve this by configuring languages to file types and customizing settings per language.

For example

### File association to language
.jade -> jade
.pug-> pug

### Language based settings (In Settings)
"[jade]" : {
   file.trimTrailingWhitespace: false
},
"[pug]" : {
   file.trimTrailingWhitespace: false
}

**Comment by sandy081** [comment]
Duplicates #1587
