### ISSUE TITLE
Extensions: "add to devcontainer.json" not working

### ISSUE THREAD

**Issue by dlandry** [microsoft/vscode#189927]
Type: <b>Bug</b>

WLS2 terminal (Ubuntu 22,04) created directory and ran 'code .'

Ctrl-Shift-p
Dev Containers: New Dev Container
Python 3

Opened Extensions View
RIght click on extension and select 'add to devcontainer.json' contenxt menue option.

EXPECTED: Extension added to devcontainer,json file

RESULTS: Nothing was added.

WORKAROUND: Manually add the necessary sections and exxtension IDs

	"customizations": {
		"vscode": {
			"extensions": [
				"KevinRose.vsc-python-indent",
				"ms-azuretools.vscode-docker",
				"felipecaputo.git-project-manager",
				"GitHub.copilot",
				"GitHub.copilot-chat",
				"ZainChen.json",
				"DavidAnson.vscode-markdownlint"
			]
		}
	}

VS Code version: Code 1.81.0 (6445d93c81ebe42c4cbd7a60712e0b17d9463e97, 2023-08-02T12:37:13.485Z)
OS version: Windows_NT x64 10.0.25921
Modes:
Remote OS version: Linux x64 5.15.90.1-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.53GB (7.65GB free)|
|Process Argv|--folder-uri=vscode-remote://wsl+Ubuntu-22.04/home/dlandry/code/CCWM --remote=wsl+Ubuntu-22.04 --crash-reporter-id 69d3745c-6fac-4ca0-aa58-41fa2df7499e|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|Dev Container: CCWM Python 3|
|OS|Linux x64 5.15.90.1-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (12 x 2592)|
|Memory (System)|15.39GB (12.57GB free)|
|VM|0%|
</details><details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
project-manager|ale|12.7.0
codespaces|Git|1.14.14
vsc-python-indent|Kev|1.18.0
remote-containers|ms-|0.304.0
remote-wsl|ms-|0.81.0
jinja|who|0.0.8
vscode-markdownlint|Dav|0.51.0
vscode-eslint|dba|2.4.2
git-project-manager|fel|1.8.2
copilot|Git|1.101.317
copilot-chat|Git|0.6.0
vsc-python-indent|Kev|1.18.0
vscode-docker|ms-|1.26.0
python|ms-|2023.14.0
vscode-pylance|ms-|2023.8.10
json|Zai|2.0.2

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263cf:30335440
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
vsccc:30803844
3biah626:30602489
f6dab269:30613381
vscrp:30673768
showlangstatbar:30737416
vsctsb:30748421
a2ce3375:30757347
pythonfmttext:30731395
pythoncmvfstrcf:30756944
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
gsofb:30804716
pythonnosmt12:30797651
pythonidxptcf:30805731
pythonnoceb:30805159
e537b577:30795824
dsvsc013:30795093
dsvsc014:30804076

```

</details>

**Comment by chrmarti** [comment]
Fixed in recent versions.
