### ISSUE TITLE
Notification "task already active" can be "never seen again" 

### ISSUE THREAD

**Issue by ulugbekna** [microsoft/vscode#189912]
Currently, one can have a task that runs on folder open (startup), but if window is reloaded, they get a notification "The task '<myTask>' is already active." with options to terminate or restart the task. It would be great to have an option to never see this notification either as a button or within gear-icon context menu on the notification.

**Comment by meganrogge** [comment]
Yeah this is happening because of automatic tasks / reconnected tasks each trying to start the same one. We should ignore the request if it's coming from one or the other source (reconnection or automatic) and the task is already running

**Comment by meganrogge** [comment]
Workaround for now is to remove the folderOpen property or disable reconnection

**Comment by joyceerhl** [comment]
🤔 I do not see my `folderOpen` task getting run either on first open or window reload

**Comment by meganrogge** [comment]
@joyceerhl found that this does not work in old Codespaces, which we are tracking here #194423.
