### ISSUE TITLE
Ghost resize borders in code completion 

### ISSUE THREAD

**Issue by SKPG-Tech** [microsoft/vscode#189911]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version:  1.81.0 (user setup)
- OS Version:  Windows_NT x64 10.0.19045

1. Make VSCode show code completion with a message
![image](https://github.com/microsoft/vscode/assets/42890752/99af7b79-f92d-4729-8088-512e09a4aef2)
2. Go to a suggestion without extra info
3. See ghost resize borders
![image](https://github.com/microsoft/vscode/assets/42890752/c2820419-9818-4ec5-bb7e-6710aa4acaba)

The ghost borders are there where the previously selected code completion option was, so it changes with each suggestion, and if you resize them with the ghost borders, it will apply to the suggestions.

**Comment by MiraynaMckinney** [comment]
@jrieken I'd like to take a look into this

**Comment by jrieken** [comment]
To verify

* in a TS file, type `let a:numb`
* trigger suggest
* focus the 2nd entry, show and resize suggest details
* without moving you mouse select the first entry (`number`) that doesn't have details
* make sure no ghost borders are shown
