### ISSUE TITLE
OSS crashes on load under debugger

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#189970]
1. DEbug OSS
2. If you don't get a crash immediately, reload a couple time
3. Get a crash on load. (Does not require breakpoints to be set or any special state)

![Image](https://github.com/microsoft/vscode/assets/2230985/532fc2d3-c88a-4562-9fc0-12a90ae7043a)

Crash report:

[crashes.zip](https://github.com/microsoft/vscode/files/12295503/crashes.zip)

**Comment by rzhao271** [comment]
Symbolicated

[symbolicated-88.log](https://github.com/microsoft/vscode/files/12296360/symbolicated-88.log)

**Comment by deepak1556** [comment]
@connor4312 I would like to repro this issue to try some fixes from chromium, can you check if I am missing any steps in the recording.


https://github.com/microsoft/vscode/assets/964386/df8d39f5-2c65-446a-bb4c-4d9ee19e7d53

**Comment by deepak1556** [comment]
Does it repro with a clean profile ? Given the crash is happening in page style recalc, wonder if a particular file / some settings are the trigger. It would be great if you can narrow down a reliable repro.

**Comment by connor4312** [comment]
This is in a new profile, yea.

This seems to happen 100% of the time on reload _if_ the Test Results view was the last focused view. That will default to opening the console output of the last run, in the terminal. If I comment out the line where I append the terminal to the DOM, the crash doesn't happen

https://github.com/microsoft/vscode/blob/e766158f04cc5aeba903766ff644102326677aea/src/vs/workbench/contrib/testing/browser/testingOutputPeek.ts#L1440

**Comment by deepak1556** [comment]
Thanks a lot for narrowing down the test case, but for some reason I am unable to repro with having test results view as the last focused view. Luckily, I am able to repro https://github.com/microsoft/vscode/issues/189753 that shares the same root issue, so I will work with that for now.

**Comment by connor4312** [comment]
yea, that sounds quite similar, as we disable gpu acceleration in the test results terminal too

**Comment by deepak1556** [comment]
Merging to https://github.com/microsoft/vscode/issues/189753, issue has been narrowed down so I can confidently close this issue. Please subscribe to that issue for updates.
