### ISSUE TITLE
macOS: Cmd+A does not work in menu help input field

### ISSUE THREAD

**Issue by ronyeh** [microsoft/vscode#19003]
- VSCode Version: 1.8.1
- OS Version: macOS 10.12.2 Sierra

Steps to Reproduce:

1. Make sure you have an editor open with your most valuable code.
2. Click on the Help menu item in the menu bar.
3. Start typing to search the menus. For example, type: "occur"
4. Realize you wanted to search for something else... so hit CMD+A, DELETE.
5. ....where did my code go?

Note, this does not happen in Xcode. When you hit CMD+A, the Help menu stays open.

In VSCode, CMD+A closes the Help menu and then selects all of your current editor's contents.

**Comment by bpasero** [comment]
Tough for us to find out that focus is up there, we still think the editor has focus. I think eventually we would need to use roles in our menu items, but that is not fun either because our commands are custom implemented.

**Comment by roblourens** [comment]
Still reproes following original steps

**Comment by bpasero** [comment]
@roblourens yeah I realize that this bug talks about 2 issues and only one is solved, can you verify this:
* click save on an untitled file
* in the dialog try to use Select All, Cut, Copy, Paste via keyboard
=> it should work

Looks like the help menu is not covered by my fix but I also argue that this one is much less of an issue compared to the native dialogs.

**Comment by bpasero** [comment]
@roblourens I suggest to verify this in https://github.com/Microsoft/vscode/issues/22696

**Comment by benface** [comment]
Any progress on this? It's bitten me a few times already and I've only been using VSC for one day.

**Comment by sbatten** [comment]
reverted bab47f0ffde4692b5a738c915bd823ef7ebc8d39 due to https://github.com/Microsoft/vscode/issues/60443

**Comment by ronyeh** [comment]
I keep running into this bug :-). I think my solution should be to stop using the Help menu to search through VSCode menu items. I did realize that hitting ESC does what I want. So I need to train myself to stop using CMD+A, DELETE to enter a new query, and instead press ESC.
