### ISSUE TITLE
Setup context menues when installing with winget

### ISSUE THREAD

**Issue by Squazz** [microsoft/vscode#190036]
When I'm installing vscode through winget, context menus are not added. Is that the expected behavior? Can one send extra parameters along when installing through winget?

**Comment by gjsjohnmurray** [comment]
Related - https://github.com/microsoft/vscode/issues/134470

**Comment by IllusionMH** [comment]
There is existing discussion in winget repo https://github.com/microsoft/winget-cli/discussions/1798

However, if you on Win11 be aware that it's not available in stable yet - see #183297 so you'll need to install Insiders version

**Comment by joaomoreno** [comment]
https://github.com/microsoft/winget-cli/discussions/1798#discussioncomment-1805552
