### ISSUE TITLE
The escape button doesn't work

### ISSUE THREAD

**Issue by 1ogifenix** [microsoft/vscode#190004]
Type: <b>Bug</b>

The issue occurs when I "add a conditional breakpoint" or a "log point" to the editor, the opened input doesn't close when pressing "escape," and the "enter" button doesn't work either.

VS Code version: Code 1.81.0 (6445d93c81ebe42c4cbd7a60712e0b17d9463e97, 2023-08-02T12:37:13.485Z)
OS version: Windows_NT x64 10.0.19045

![Captura de pantalla 2023-08-08 211248](https://github.com/microsoft/vscode/assets/141604517/340409c8-fba2-4501-aeba-6259e7e84273)

**Comment by 1ogifenix** [comment]
It seems I mistakenly configured the "closeBreakpointWidget" command. I just left it on default and the issue was resolved. How silly of me.

**Comment by gjsjohnmurray** [comment]
Glad to hear you solved it. Please close your issue.
