### ISSUE TITLE
Bad selection color

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#190016]
Settings:

```json
"workbench.colorCustomizations": {
    "focusBorder": "#F3F3F3",
    "inputOption.activeBackground": "#007acc1f",
    "inputOption.activeBorder": "#007acc1f",
    "editorLineNumber.activeForeground": "#2b91af",
    "list.focusHighlightForeground": "#fff",
    "activityBar.activeBorder": "#2c2c2c",
    "sideBarSectionHeader.border": "#0000",
    "list.activeSelectionBackground": "#3399FF",
    "list.highlightForeground": "#0066BF",
    "list.activeSelectionIconForeground": "#fff",
    "diffEditor.insertedTextBackground": "#9bb95533"
},
"workbench.colorTheme": "Default Light+"
```

![Image](https://github.com/microsoft/vscode/assets/900690/30c7f364-255b-4b82-92c9-b68e75fba3bc)

**Comment by bpasero** [comment]
How it should be:

<img width="442" alt="image" src="https://github.com/microsoft/vscode/assets/900690/0e1aec84-82bd-4246-9501-bf97ee0030e2">

**Comment by daviddossett** [comment]
Hm, strange. I haven't made any changes here lately. I'm noting that `list.activeSelectionForeground` is not having an effect on the foreground color used on the tree within Explorer. It does however affect other lists like the one used in the quick pick.

```
export const listActiveSelectionForeground = registerColor('list.activeSelectionForeground', { dark: Color.white, light: Color.red, ...
```

I also noticed the terminal tabs tree flicker to use that red before being stomped on again. Not sure what's going on here yet.

https://github.com/microsoft/vscode/assets/25163139/4bfeb127-37bc-4023-a722-e52c781557f1

**Comment by daviddossett** [comment]
Looks like this is from 49ac847cc899736737fdb3a1f977754a5303da0f
