### ISSUE TITLE
July 2023 Recovery 1

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#190082]
- [x] Create a milestone `July 2023 Recovery 1` **@alexr00**
- [x] Bump the version number **@alexr00**
- [x] [🔖candidate issues](https://github.com/issues?q=is%3Aissue%20label%3Acandidate%20repo%3Amicrosoft%2Fvscode%20repo%3Amicrosoft%2Fvscode-remote-release%20repo%3Amicrosoft%2Fvscode-js-debug%20repo%3Amicrosoft%2Fvscode-pull-request-github%20repo%3Amicrosoft%2Fvscode-github-issue-notebooks%20repo%3Amicrosoft%2Fvscode-internalbacklog%20repo%3Amicrosoft%2Fvscode-dev%20repo%3Amicrosoft%2Fvscode-unpkg%20repo%3Amicrosoft%2Fvscode-references-view%20repo%3Amicrosoft%2Fvscode-anycode%20repo%3Amicrosoft%2Fvscode-hexeditor%20repo%3Amicrosoft%2Fvscode-extension-telemetry%20repo%3Amicrosoft%2Fvscode-livepreview%20repo%3Amicrosoft%2Fvscode-remotehub%20repo%3Amicrosoft%2Fvscode-settings-sync-server%20repo%3Amicrosoft%2Fvscode-remote-repositories-github%20repo%3Amicrosoft%2Fmonaco-editor%20repo%3Amicrosoft%2Fvscode-vsce%20repo%3Amicrosoft%2Fvscode-dev-chrome-launcher%20repo%3Amicrosoft%2Fvscode-emmet-helper%20repo%3Amicrosoft%2Fvscode-livepreview%20repo%3Amicrosoft%2Fvscode-livepreview%20repo%3Amicrosoft%2Fvscode-python%20repo%3Amicrosoft%2Fvscode-python-debugger%20repo%3Amicrosoft%2Fvscode-jupyter%20repo%3Amicrosoft%2Fvscode-jupyter-internal%20repo%3Amicrosoft%2Fvscode-github-issue-notebooks%20repo%3Amicrosoft%2Fvscode-l10n%20repo%3Amicrosoft%2Fvscode-remote-tunnels%20milestone%3A%22July%202023%20Recovery%201%22)
- [x] Assign candidate issues to the recovery milestone **team**
- [x] Review the `candidate` issues, and if they pass the review assign them to the recovery milestone **team**
- [x] All `candidate` fixes are peer reviewed and pushed to `main` and then cherry-picked into the release branch **team**
- [x] Initiate `insiders` build from `main`
- [x] Issues are tested in the `insiders` **team**
- [x] Build `stable` for all platforms from release branch **@andreamah**
- [x] Issues are verified on `stable` build and the `verified` label is added **@andreamah**
- [x] Check `https://github.com/Microsoft/vscode/compare/release/<x.y>` to ensure no other commits have been made in the release branch **@andreamah**
- [x] Update the release notes and include a link to a query for the fixed issues **@gregvanl**
- [x] [Sanity Testing](https://github.com/microsoft/vscode/wiki/Sanity-Check)
  - [x] Windows 32 bit @dbaeumer 
    - [x] System Installer
    - [x] User Installer
    - [x] Archive
    - [x] Server
    - [x] CLI
  - [x] Windows 64 bit @dbaeumer 
    - [x] System Installer
    - [x] User Installer
    - [x] Archive
    - [x] Server
    - [x] CLI
  - [x] Windows ARM64 @deepak1556 
    - [x] System Installer
    - [x] User Installer
    - [x] Archive
    - [x] CLI
  - [x] macOS Intel @bpasero 
    - [x] Archive
    - [x] Universal Archive
    - [x] Server
    - [x] CLI
  - [x] macOS ARM64 @aiday-mar 
    - [x] Archive
    - [x] Universal Archive
    - [x] Server
    - [x] CLI
  - [x] Linux x64 @deepak1556 
    - [x] Archive
    - [x] DEB
    - [x] RPM
    - [x] Snap
  - [x] Linux Server @bpasero _(can be tested from any OS with Docker)_
    - [x] x64
    - [x] ARM32
    - [x] ARM64
    - [x] x64 Alpine
    - [x] ARM64 Alpine
  - [x] Linux CLI @bpasero _(can be tested from any OS with Docker)_
    - [x] x64
    - [x] ARM32
    - [x] ARM64
    - [x] x64 Alpine
    - [x] ARM64 Alpine
- [x] Publish website **@gregvanl**
- [x] Publish stable build **@andreamah**
- [x] Create an official release **@andreamah**
  - [x] Create a tag (make sure you pull the release branch first): `git tag <x.y.z> release/<x.y>`
  - [x] Push the tag: `git push origin <x.y.z>`
  - [x] Create a GitHub release: [Open the GitHub tags](https://github.com/microsoft/vscode/tags), and click far right `... > Create Release`. Use the correct title and description from our release notes. [Example](https://github.com/microsoft/vscode/releases/tag/1.39.1)
- [x] Close the milestone on [GitHub](https://github.com/microsoft/vscode/milestones) **@andreamah**

**Comment by Amindofastoner0312** [comment]
If the binaries match or collab with the original DEVICE'S "About Phone" info and license/policy agreements of the manufacturered product/device.

**Comment by Amindofastoner0312** [comment]
This seems like a patch for the creative commons policy? 
That would be great! 👍
