### ISSUE TITLE
Net 6/7 Debugger Fails To Attach to Process for Test Project

### ISSUE THREAD

**Issue by gabe-calabro** [microsoft/vscode#190089]
Does this issue occur when all extensions are disabled?: Well it requires the C# extension to discover tests. But disabling all but the C# extension it still happens.

- MacOS Ventura 13.5
- VS Code 1.18.0
- .NET Core SDK 7.0.400 x64
- .NET Core Runtime 7.0.10 x64
- C# Extension v2.0.328

Steps to Reproduce:

1. dotnet new sln -n foo
2. dotnet new webapi -n web
3. dotnet new mstest - n test
4. dotnet sln ./foo.sln add ./web.csproj
5. dotnet sln ./foo.sln add ./test.csproj
6. code .
7. set a break point on the sample test operation
8. click debug test
9. fails, with unable to start debugging: failed to attach to process

Other details:

I have no test extensions installed what-so-ever, vanilla install of VS Code. This was working for years and then just stopped.

I have rolled back to the previous .NET Core SDK and runtimes. I have rolled back to the previous VS Code as well. All with the same results. I have tried a fresh install nuking everything top to bottom for VS Code, NET Core SDK and Runtimes. I have tried this on a second Mac machine.

Everything restores and builds successfully. I can run tests, just can't debug tests. Randomely, it will work but if I try it again it fails again. Then it doesnt work until a random attempt, but only once.

I should also note that I CAN debug tests in Visual Studio for Mac.

So ultimately the problem seems to be specifically with VS Code attaching to a process for test projects.

<img width="502" alt="Screenshot 2023-08-09 at 1 01 27 PM" src="https://github.com/microsoft/vscode/assets/101517882/fc78c94d-73ba-480e-a3b0-0e2e872288cf">

When I click Debug Test in the unit test file it has the same result every time now.

**Comment by gabe-calabro** [comment]
When I roll back the C# Extension to v1.26.0 everything seems to work again...

**Comment by roblourens** [comment]
Please file an issue on the C# extension repo
