### ISSUE TITLE
[Request] Make findFiles "include", "exclude" an array of strings

### ISSUE THREAD

**Issue by JimiC** [Microsoft/vscode#19004]
Curently `findFiles` only accepts `string` as `include` and `exclude`.
There are cases where we need to either include or exclude more than one pattern.

In my case, I need to do a search for `**/package.json` but want to exclude `node_modules`, `bin`, `out`, `build`, `dist`, etc folders from the search.

**Comment by bpasero** [comment]
@JimiC just use comma to separate multiple include/exclude, that should just work.

**Comment by JimiC** [comment]
@bpasero Well, that's the thing. I tried that (first thing that came to mind) but it doesn't work. It results to exclude pattern being ignored.
What I use is `'**/node_modules/**, **/bin/**'`, or even `'**/node_modules/**, bin/**'` but the result is the same in both cases. All files found are returned, ignoring the exclude pattern.

Am I doing something obviously wrong here? Can you give an example of a working pattern?
The docs only have the `'**/node_modules/**'` which isn't helpful in this case.

**Comment by bpasero** [comment]
Then you are likely hitting https://github.com/Microsoft/vscode/issues/930

**Comment by JimiC** [comment]
So it's actually a bug. Thanks for clarifying.
