### ISSUE TITLE
Add ability to remove `rootNameShort` in window title if `rootNameShort` is empty string

### ISSUE THREAD

**Issue by nikitavoloboev** [microsoft/vscode#190006]
I have a workspace that is an empty space ` `. In VSCode the title bar with this will look like:

<img width="421" alt="image" src="https://github.com/microsoft/vscode/assets/6391776/e8c6626d-651d-453f-b505-14c4342a57b0">

I would like so that the title bar only shows the file name in this case.

So just `readme.md` in above case.

And in case of a workspace with some name like `rust` instead of below:

<img width="392" alt="image" src="https://github.com/microsoft/vscode/assets/6391776/a22ad3ee-b2fc-44f5-9c69-22d9442dfd92">

It should be `main.rs - rust`. No need to show the `(Workspace)`. 

Is it possible to customise the window title in this way?

**Comment by nikitavoloboev** [comment]
So my current window title is: `${activeEditorShort}${separator}${rootName}${separator}${profileName}`

<img width="987" alt="image" src="https://github.com/microsoft/vscode/assets/6391776/9d2f53bb-ac5d-4d7c-953a-6e926ff2c2f5">

I don't see how I can remove `- (Workspace)` in available options.

**Comment by nikitavoloboev** [comment]
I basically want to modify `rootName` I think. Have it stop showing `(Workspace)` in it as an option.

Would be so amazing if you can add this. ♥️

**Comment by nikitavoloboev** [comment]
Ok actually this: `${activeEditorShort}${separator}${rootNameShort}${separator}${profileName}` is what I was looking for.

<img width="479" alt="image" src="https://github.com/microsoft/vscode/assets/6391776/04d3e5d6-e9e1-46b7-b75d-3084458c9c5a">

It shows separator as there is `empty` space name as the workspace and it still shows that.

Is there by chance a way to make the window title more dynamic? So if the name is ` ` empty space, it won't show `rootNameShort` and thus not show the separator?

**Comment by sbatten** [comment]
Are you saying your workspace name is all whitespace?

**Comment by nikitavoloboev** [comment]
Yes basically I have a default workspace I often run and dislike having `(Workspace) there.

I would like to hide the `(Workplace)` in general from the name. Can I do that?

<img width="503" alt="image" src="https://github.com/microsoft/vscode/assets/6391776/0857e82b-8cdd-4a8a-b72f-5ebb968db201">

So have above showing. Even when in a workspace. No additional `(Workplace)` appended. 

Thanks a lot.

**Comment by sbatten** [comment]
${rootNameShort} seems to be what you want but I'm not sure about the workspace name being all whitespace. how did you set that up?

**Comment by nikitavoloboev** [comment]
> how did you set that up?

<img width="260" alt="image" src="https://github.com/microsoft/vscode/assets/6391776/853d1f2e-13b4-4e03-83fd-d65b85f79b1e">

you can have empty space in a file

**Comment by nikitavoloboev** [comment]
I have this as name now:

`  "window.title": "${activeEditorShort}${separator}${rootNameShort}${separator}${profileName}",`

Not sure which part I have to remove.

**Comment by benibenj** [comment]
You can set `window.title` in your workspace's `.vscode/settings.json` file. The title you configure will then only apply in that workspace
