### ISSUE TITLE
Select color theme according to current color theme in dev mode

### ISSUE THREAD

**Issue by harbin1053020115** [microsoft/vscode#190034]
When developing extensions with color themes, the VS Code will initialize the color theme with the first color theme defined in the extension's package.json. The code shows as below: 
![image](https://github.com/microsoft/vscode/assets/2869750/a2c8d5c4-e096-4a22-a68b-b69eaa7ae6ae)
As I want to switch to anthor color theme and refresh browser page to debug anthor color theme, it seems only to switch the color theme again after the browser page refreshed.

**Comment by aeschli** [comment]
Verify by:
- create a theme extension ( use yo code)
- in the theme extension define a light and a dark theme
- run the extension.
- Verify that VS Code window that opens has the theme in development open that matches the current color scheme
