### ISSUE TITLE
Git Bash integrated terminal odd behaviour

### ISSUE THREAD

**Issue by antmerlino** [Microsoft/vscode#19005]
A few integrated terminal commands using Git Bash have some odd behavior right off the bat with this newest release of Insider.

The `clear` command results in:
```
$ clear
'bash.exe': unknown terminal type.
```

`vim` results in:
```
$ vim Vagrantfile
E437: terminal capability "cm" required
Press ENTER or type command to continue
```
Then after pressing enter, vim launches but all the spacing is messed up.

Also, backspace just adds spaces now.  And it seems like the up/down keys just keep appending previous commands rather than cycling through them.

Let me know if there is any testing needed on my end.

- VSCode Version: Code - Insiders 1.9.0-insider (ee9d91c05fa571de56c41383cceee30b05b0a2f6, 2017-01-20T15:08:19.064Z)
- OS Version: Windows_NT ia32 10.0.14986
- Extensions:

|Extension|Author|Version|
|---|---|---|
|vscode-instant-markdown|dbankier|0.2.1|
|python|donjayamanne|0.5.6|
|cpptools|ms-vscode|0.9.3|
|vscode-docker|PeterJausovec|0.0.11|
|vscode-icons|robertohuertasm|7.0.1|
|vim|vscodevim|0.4.11|
|vscode-todo-highlight|wayou|0.3.3|

---

Steps to Reproduce:

1.  Set C:\\Program Files\\Git\\bin\\bash.exe as integrated windows terminal
2.  Launch integrated terminal
3.  Type commands to view odd behaviour

**Comment by Tyriar** [comment]
This should be fixed in next Insiders, in the meantime typing this into the terminal should fix it on a per-session basis:

```
TERM=xterm
```

**Comment by antmerlino** [comment]
@Tyriar Not sure if this is a separate issue or maybe is resolved through the more permanent fix, but the `clear` command does not act properly even with the
```
TERM=xterm
```
The cursor moves back to the top but doesn't clear any of the text

**Comment by Tyriar** [comment]
@antmerlino the new build is out in ~4 hours I think, could you test it after then?

**Comment by antmerlino** [comment]
@Tyriar Surely, I'll let you know

**Comment by antmerlino** [comment]
@Tyriar Fixed 👍

**Comment by Tyriar** [comment]
Awesome 😄

**Comment by adil-waqar** [comment]
Any fix for this issue? I am still facing it with backspace adding spaces and clear being an unknown terminal type.

**Comment by adil-waqar** [comment]
@antmerlino @Tyriar What build fixed this issue? I just used the latest git bash and vscode.

**Comment by Tyriar** [comment]
@adil-waqar this was closed back in January. Do you have the latest version installed?
