### ISSUE TITLE
Source control tab > branches section > pull action not working

### ISSUE THREAD

**Issue by felipewesley** [microsoft/vscode#190048]
Type: <b>Bug</b>

For example: I am in the "dev" git branch, but when I go to the source control tab and runs the "fetch remote origin" action, all branches that have updates are highlighted with orange color, and the number of commits to pull are showed too. The "pull" button is turned on for all unupdated branches, but, if I try pull a branch diferent of "dev" (current branch), the pull is not done and the branch is not updated. If I really want updates the desired branch, I need switch to branch, and there do the pull action to work correctly. In the previous version of VSCode, this feature was working perfectly, but I found this bug in the current version (1.81.0). Just that. Thanks!

VS Code version: Code 1.81.0 (6445d93c81ebe42c4cbd7a60712e0b17d9463e97, 2023-08-02T12:37:13.485Z)
OS version: Windows_NT x64 10.0.22621
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-10210U CPU @ 1.60GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|7.83GB (1.01GB free)|
|Process Argv|--crash-reporter-id 36021977-22d1-4deb-8336-1080c35b6b54|
|Screen Reader|no|
|VM|50%|
</details><details><summary>Extensions (17)</summary>

Extension|Author (truncated)|Version
---|---|---
codesnap|adp|1.3.4
Bookmarks|ale|13.4.1
vscode-angular2-files|ale|1.6.4
ng-template|Ang|16.1.4
vscode-intelephense-client|bme|1.9.5
vscode-tailwindcss|bra|0.9.11
gitlens|eam|14.2.0
prettier-vscode|esb|10.1.0
auto-rename-tag|for|0.1.10
vscode-docker|ms-|1.26.0
vscode-language-pack-pt-BR|MS-|1.81.2023080209
isort|ms-|2023.10.1
python|ms-|2023.14.0
vscode-pylance|ms-|2023.8.10
color-highlight|nau|2.5.0
material-icon-theme|PKi|4.29.0
LiveServer|rit|5.7.9

(3 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
py29gd2263cf:30792227
vscaac:30438847
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
vsccc:30803844
3biah626:30602489
f6dab269:30613381
showlangstatbar:30737416
vsctsb:30748421
03d35959:30757346
pythonfmttext:30731395
pythoncmv:30756943
f8hc8238:30694864
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
gsofb:30804716
pythonnosmt12:30797651
pythonidxptcf:30805731
pythonnoceb:30805159
e537b577:30795824
dsvsc013:30795093
dsvsc014:30804076

```

</details>

**Comment by gjsjohnmurray** [comment]
It sounds like you are describing a feature that the GitLens extension contributes. To verify this please disable that extension. If the feature disappears, re-enable that extension, raise the issue on the GitLens repo and close this one.
