### ISSUE TITLE
Not recogninsing git in my mac 

### ISSUE THREAD

**Issue by Nausheen95** [microsoft/vscode#190026]
![Screenshot 2023-08-09 at 4 03 53 PM](https://github.com/microsoft/vscode/assets/55658909/9731b61d-4774-453f-a4a4-043f1cb6516a)
![Screenshot 2023-08-09 at 4 04 56 PM](https://github.com/microsoft/vscode/assets/55658909/c0ccb656-804e-4888-8f89-603c79b1b768)
Type: <b>Bug</b>

its not able to recognise git evn though its installed in my machine

VS Code version: Code 1.81.0 (6445d93c81ebe42c4cbd7a60712e0b17d9463e97, 2023-08-02T12:40:02.782Z)
OS version: Darwin x64 21.6.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5350U CPU @ 1.80GHz (4 x 1800)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|5, 8, 7|
|Memory (System)|8.00GB (0.24GB free)|
|Process Argv|--crash-reporter-id d9be9939-7eab-487f-aa4a-b7d05acb038d|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|2.4.2
githistory|don|0.6.20
es7-react-js-snippets|dsz|4.4.3
gitlens|eam|14.1.1
prettier-vscode|esb|10.1.0
copilot|Git|1.101.317
remote-ssh|ms-|0.102.0
remote-ssh-edit|ms-|0.86.0
remote-explorer|ms-|0.4.1
vscode-react-native|msj|1.11.2

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263:30335439
vscoreces:30445986
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
py29gd2263cf:30792227
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
vscccc:30803845
2e4cg342:30602488
89544117:30613380
a9j8j154:30646983
showlangstatbar:30737416
vsctsb:30748421
a2ce3375:30757347
pythonfmttext:30731395
pythoncmvfstrcf:30756944
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
gsofb:30804716
pythonnosmt12:30797651
pythonidxptcf:30805731
pythonnoceb:30805159
e537b577:30795824
dsvsc013:30795093
dsvsc014:30804076

```

</details>

**Comment by lszomoru** [comment]
Could you please share the contents of the [git output window](https://code.visualstudio.com/docs/sourcecontrol/overview#_git-output-window)?
Also, could you please run `which git` from the terminal? Thanks!

**Comment by allenap** [comment]
This is affecting me after relaunching VSCode today.

I launch VSCode from an external terminal using `code .`. In the shell (`bash`) in that terminal I can use `git` without problem:

```shellsession
$ which git
/opt/homebrew/bin/git

$ type -a git
git is /opt/homebrew/bin/git
git is /usr/bin/git

$ git --version
git version 2.42.0
```

I get the same as above when running the commands in the VSCode terminal.

<img width="224" alt="image" src="https://github.com/microsoft/vscode/assets/348564/d9172e19-2cdc-4270-96db-fbc034a40aed">

The Git integration shows an error:

<img width="181" alt="image" src="https://github.com/microsoft/vscode/assets/348564/b77e268e-ecf2-4785-a250-1d61a8adfb85">

Setting `"git.path": "/opt/homebrew/bin/git"` in `settings.json` and relaunching VSCode works around this problem, but nevertheless there's something awry.

**Comment by lszomoru** [comment]
@allenap, that indeed does not look good and I would love to get to the bottom of it. Could you please remove the `git.path` setting so that we are able to reproduce the problem. Can you please send me the contents of the [git output channel](https://code.visualstudio.com/docs/sourcecontrol/overview#_git-output-window), as well as any errors that are in the developer tools console? Thanks!

**Comment by allenap** [comment]
@lszomoru Here's the output:

<img width="461" alt="image" src="https://github.com/microsoft/vscode/assets/348564/abc728d6-dc58-43ec-ab44-b4483754c414">

Sorry, I should have included that first time around. I also restarted VSCode with `code --log vscode.git:trace .` but the output was the same: just that one "Git installation not found" message.

**Comment by lszomoru** [comment]
@allenap, there are some errors that occur during extension activation that are being written into the developer tools console. Can you please invoke the "Developer: Toggle Developer Tools" command from the command palette and share any errors/warnings that are written into the console? Thanks!

**Comment by allenap** [comment]
@lszomoru Here it what I see:

```
log.ts:441   ERR Extension 'github.copilot' appears in product.json but enables LESS API proposals than the extension wants.
package.json (LOSES): inlineCompletionsAdditions, terminalDataWriteEvent
product.json (WINS): inlineCompletionsAdditions
TMScopeRegistry.ts:46 Overwriting grammar scope name to file mapping for scope source.js.jsx.
Old grammar file: file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/extensions/javascript/syntaxes/JavaScriptReact.tmLanguage.json.
New grammar file: file:///Users/gavin/.vscode/extensions/dzannotti.vscode-babel-coloring-0.0.4/syntaxes/Babel%20Language.json
register @ TMScopeRegistry.ts:46
TMScopeRegistry.ts:46 Overwriting grammar scope name to file mapping for scope source.yaml.
Old grammar file: file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/extensions/yaml/syntaxes/yaml.tmLanguage.json.
New grammar file: file:///Users/gavin/.vscode/extensions/redhat.vscode-yaml-1.14.0/syntaxes/yaml.tmLanguage.json
register @ TMScopeRegistry.ts:46
console.ts:137 [Extension Host] Git installation not found.
p @ console.ts:137
mainThreadExtensionService.ts:113 Activating extension 'GraphQL.vscode-graphql-execution' failed: The argument 'filename' must be a file URL object, file URL string, or absolute path string. Received undefined.
$onExtensionActivationError @ mainThreadExtensionService.ts:113
console.ts:137 [Extension Host] ACTIVATE
TMScopeRegistry.ts:46 Overwriting grammar scope name to file mapping for scope source.js.jsx.
Old grammar file: file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/extensions/javascript/syntaxes/JavaScriptReact.tmLanguage.json.
New grammar file: file:///Users/gavin/.vscode/extensions/dzannotti.vscode-babel-coloring-0.0.4/syntaxes/Babel%20Language.json
register @ TMScopeRegistry.ts:46
TMScopeRegistry.ts:46 Overwriting grammar scope name to file mapping for scope source.yaml.
Old grammar file: file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/extensions/yaml/syntaxes/yaml.tmLanguage.json.
New grammar file: file:///Users/gavin/.vscode/extensions/redhat.vscode-yaml-1.14.0/syntaxes/yaml.tmLanguage.json
register @ TMScopeRegistry.ts:46
console.ts:137 [Extension Host] autodetectElmJson 201ms
log.ts:421  INFO [perf] Render performance baseline is 18ms
console.ts:137 [Extension Host] rejected promise not handled within 1 second: Error: Git model not found
p @ console.ts:137
console.ts:137 [Extension Host] stack trace: Error: Git model not found
    at s.getAPI (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/git/dist/main.js:2:1141320)
    at new ql (/Users/gavin/.vscode/extensions/github.vscode-pull-request-github-0.70.0/dist/extension.js:1772:27151)
    at Function.createProvider (/Users/gavin/.vscode/extensions/github.vscode-pull-request-github-0.70.0/dist/extension.js:1772:27796)
    at fg (/Users/gavin/.vscode/extensions/github.vscode-pull-request-github-0.70.0/dist/extension.js:1772:33860)
    at Vp (/Users/gavin/.vscode/extensions/github.vscode-pull-request-github-0.70.0/dist/extension.js:1835:5584)
    at V0 (/Users/gavin/.vscode/extensions/github.vscode-pull-request-github-0.70.0/dist/extension.js:1835:6689)
p @ console.ts:137
mainThreadExtensionService.ts:81 [vscode.git]Git model not found
$onExtensionRuntimeError @ mainThreadExtensionService.ts:81
mainThreadExtensionService.ts:82 Error: Git model not found
    at s.getAPI (vscode-file://vscode-app/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/git/dist/main.js:2:1141320)
    at new ql (vscode-file://vscode-app/Users/gavin/.vscode/extensions/github.vscode-pull-request-github-0.70.0/dist/extension.js:1772:27151)
    at Function.createProvider (vscode-file://vscode-app/Users/gavin/.vscode/extensions/github.vscode-pull-request-github-0.70.0/dist/extension.js:1772:27796)
    at fg (vscode-file://vscode-app/Users/gavin/.vscode/extensions/github.vscode-pull-request-github-0.70.0/dist/extension.js:1772:33860)
    at Vp (vscode-file://vscode-app/Users/gavin/.vscode/extensions/github.vscode-pull-request-github-0.70.0/dist/extension.js:1835:5584)
    at V0 (vscode-file://vscode-app/Users/gavin/.vscode/extensions/github.vscode-pull-request-github-0.70.0/dist/extension.js:1835:6689)
$onExtensionRuntimeError @ mainThreadExtensionService.ts:82
console.ts:137 [Extension Host] [vscode-icons] v12.5.0 activated!
```

**Comment by lszomoru** [comment]
@allenap, thank you very much for the additional information. I have looked at the code, and I have to say that I am a little puzzled. Based on the logs that are emitted, my hypothesis is that we run into an error while VS Code spawns a child process to call `which git`. Unfortunately we do not currently log the error in this particular error condition. We are getting ready for the August 2023 release but I will look at adding additional logging in September to try to track down what is happening here.

**Comment by allenap** [comment]
@lszomoru Seems this bug – for me, at any rate – has gone away. I removed the `git.path` setting from `settings.json`, restarted VSCode, and it was fine 🤷

**Comment by lszomoru** [comment]
@allenap, thanks for the update. That is quite unfortunately as I really want to get to the bottom of this issue. Did you just restart VS Code or did you restart the machine? Did you make any changes to your `PATH` variable or any changes to your terminal profile?

**Comment by allenap** [comment]
@lszomoru I just restarted VSCode. I have also, subsequent to that, restarted my machine, but the issue went away without a reboot. I had changed `PATH`, but reverting those changes doesn't cause the bug to reappear.

**Comment by lszomoru** [comment]
@allenap, thanks for the update. It's a pity that we have lost the repro as in the latest Insiders release (1.83) I have added some additional logging to the code path that detects the location and version of git. I will go ahead and close this issue but please feel free to reopen it in case the issue comes back. Thanks!
