### ISSUE TITLE
Add 'Extension Pack' as a supported category

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode#19002]
@waderyan pls correct if needed.

`Extension Pack` was recently added as a category and it should be supported in the `package.json`.

![image](https://cloud.githubusercontent.com/assets/172399/22184981/ec1e8f88-e0dc-11e6-8969-adfbee84b5ae.png)

**Comment by egamma** [comment]
I'm sorry, but @waderyan just pointed out that it should be plural 'Extension Packs'.

**Comment by waderyan** [comment]
I made a PR https://github.com/Microsoft/vscode/pull/19069

**Comment by aeschli** [comment]
PR delivered
