### ISSUE TITLE
Chat input error: `Overwriting a content widget with the same id.`

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#190043]
* have a pill rendered
* continue typing
* see warnings on the console `Overwriting a content widget with the same id.`

The is triggered from this line https://github.com/microsoft/vscode/blob/51d17f84e38fb49eba662de4cf980ce94ba6a0be/src/vs/workbench/contrib/chat/browser/chatSlashCommandContentWidget.ts#L36

**Comment by joyceerhl** [comment]
@jrieken I cannot repro this in either panel or inline chat, does this consistently repro for you / do you have some more specific steps?
