### ISSUE TITLE
Triggering random filechanges for ".gitignore" file

### ISSUE THREAD

**Issue by laggingreflex** [Microsoft/vscode#19001]
- VSCode Version: 1.8.1
- OS Version: Win 10

Steps to Reproduce:

1. Run chokidar file watcher to monitor all file changes in current directory (use this [repro](https://github.com/laggingreflex/chokidar-vscode-test))
2. Have a `.gitignore` file
3. Open VSCode in current dir
4. Make changes to any file, other than `.gitignore`
5. chokidar randomly logs file changes for `.gitignore` file

![vscode-gitignore](https://cloud.githubusercontent.com/assets/2523987/22184656/3dc6f1b2-e0fc-11e6-8075-eb3b27066067.gif)

PS: It's not related to `chokidar` as I've tried with other editors and VSCode is the only one that this happens in. Even with `--disable-extensions`

**Comment by dbaeumer** [comment]
@joaomoreno starting with you since it is a .gitignore file. Not sure if it is git related so.

**Comment by joaomoreno** [comment]
@laggingreflex Does chokidar report read events too? Do you see the same events when running `git status` from the command line? Code calls `git status` which possibly touches the `.gitignore` file.

**Comment by laggingreflex** [comment]
yeah that's it I think.  `git status` produces very similar events on `.gitignore` file.
