### ISSUE TITLE
Setting sync with codespace removing local extensions

### ISSUE THREAD

**Issue by imranbarbhuiya** [microsoft/vscode#190011]
Type: <b>Bug</b>

Hi, I'm experiencing an issue similar to https://github.com/microsoft/vscode/issues/155990. I enabled setting sync in GitHub codespaces and after that, my extensions started to get removed automatically. I had 49 extensions and now I've only 21. After that, I tried to restore the extensions from the sync tab and it got restored properly but within a few seconds, it gets removed again. I tried installing manually and only 3 extensions got added properly (unocss, gitlense, and copilot chat), other extensions get installed but when u refresh the extension tab, they get deleted. I'm not sure how can I provide more details of this error, if someone knows how can I give some logs then lmk. I uninstalled the GitHub codespace extension, and disabled setting sync from codespace settings but still it's not working

VS Code version: Code - Insiders 1.82.0-insider (bf9c8105647b1e9d244f0f00155c21298e7554cf, 2023-08-09T05:33:07.510Z)
OS version: Windows_NT x64 10.0.22621
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|12th Gen Intel(R) Core(TM) i7-12700F (20 x 2112)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.84GB (8.08GB free)|
|Process Argv|--crash-reporter-id 2a515175-97ab-457e-94e2-d5dadae50b98|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (22)</summary>

Extension|Author (truncated)|Version
---|---|---
unocss|ant|0.54.2
npm-intellisense|chr|1.4.4
vscode-eslint|dba|2.4.2
gitlens|eam|2023.8.805
prettier-vscode|esb|10.1.0
copilot|Git|1.101.317
copilot-chat|Git|0.7.2023080701
vscode-pull-request-github|Git|0.71.2023080809
discord-vscode|icr|5.8.0
theme-pink-candy|kub|1.4.0
MagicPython|mag|1.1.0
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.17
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-slideshow|ms-|0.1.5
remote-ssh|ms-|0.102.0
remote-ssh-edit|ms-|0.86.0
cpptools|ms-|1.16.3
remote-explorer|ms-|0.4.1
vscode-thunder-client|ran|2.10.2
rust-analyzer|rus|0.3.1615
markdown-all-in-one|yzh|3.5.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vslsvsres303:30308271
pythontb:30258533
vsc_aacf:30263846
pythonptprofiler:30281269
vsdfh931cf:30280410
vshan820:30294714
vscod805cf:30301675
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30404738
py29gd2263:30784851
vsclangdf:30492506
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30618038
2i9eh265:30646982
showlangstatbar:30737417
7ij38806:30687742
pythonfmttext:30716741
pythoncmvfstr:30726892
fixshowwlkth:30771523
showindicator:30805243
pythongtdpath:30726887
i26e3531:30792625
gsofa:30797620
pythonnosmt12:30779711
pythonidxpt:30768918
pythonnoceb:30776497
copilotsettingt:30808721
e537b577:30772214
h0f32768:30792099
asynctokenver:30799129
dsvsc013:30777762
dsvsc014:30777825
diffeditorv2:30786206

```

</details>

**Comment by bpasero** [comment]
Are profiles involved here? Possibly with the option to "Apply extension to all profiles"?

**Comment by joyceerhl** [comment]
This may be a duplicate of https://github.com/microsoft/vscode/issues/189877. Can you please try out the latest VS Code Insiders and let us know whether it's fixed there: https://code.visualstudio.com/insiders

**Comment by imranbarbhuiya** [comment]
Yeah it's fixed, thanks ❤️
