### ISSUE TITLE
GitHub Copilot could not connect to server. Extension activation failed: "Timed out waiting for authentication provider to register"

### ISSUE THREAD

**Issue by mountain731027** [microsoft/vscode#190037]
I can not enable GitHub Copilot

**Comment by mountain731027** [comment]
Yes, it is working.  Thank you 😊

Tyler James Leonhardt ***@***.***> 於 2023年8月10日 週四 00:01 寫道：

**Comment by TylerLeonhardt** [comment]
@mountain731027 Copilot is now working for you? Just want to confirm.

**Comment by mountain731027** [comment]
Yes, it worked when I enabled the GitHub Authentication
Thanks a lot again. 😀

Tyler James Leonhardt ***@***.***> 於 2023年8月10日 週四 上午5:02寫道：
