### ISSUE TITLE
Why is it showing red lines under these pieces of code?

### ISSUE THREAD

**Issue by Legitgamer264** [Microsoft/vscode#19007]
- VSCode Version: 1.9.0 Insider
- OS Version: Windows 10 Insider build 15014

This is only happening in this project. But I am seeing this http://imgur.com/I98eOwV
in my alert.js file. I just installed jslint by running "npm install jslint" in my project, which all that seems to have done is add green squiggle lines in places.

Anyone know how to fix it?
Here is an image of the extensions that I have installed - http://imgur.com/RXVZKUz

This project is pulled from the Reddit-Enhancement-Suite github, so I highly doubt there are errors in the code like what it is showing with the red lines

**Comment by dbaeumer** [comment]
@Legitgamer264 the file looks like the TS file (it has type annotations). JS Hint is for linting JS files wo it complains about the unknown type annotations (e.g. : string). If you want to lint TS files tslint is the way to go.
