### ISSUE TITLE
Hope to Adding features

### ISSUE THREAD

**Issue by BryantZhou** [Microsoft/vscode#19009]
like with webstorm, hint the variable not used

**Comment by rozzzly** [comment]
Please read the [Submitting Bugs and Suggestions](https://github.com/Microsoft/vscode/wiki/Submitting-Bugs-and-Suggestions) from the wiki.

You don't mention what language you're talking about... But if you're talking about JavaScript, or TypeScript then google how to configure **`vscode`** to work with **`eslint`**, or **`tslint`**, respectively.
