### ISSUE TITLE
configuration.update doesn't do anything on malformed json

### ISSUE THREAD

**Issue by WebFreak001** [Microsoft/vscode#19006]
Example user settings:
```json
{
  "editor.renderWhitespace": "all",
}
```
It does get treated by vscode correctly (correctly parsed and used). However when calling
```ts
getConfiguration("test").update("foo", "bar", true);
```
now it won't do anything unless I remove that comma at the end of the line.

People who never edited the settings manually complained about my extension not correctly working because the config doesn't update.

**Comment by ramya-rao-a** [comment]
@sandy081 Would this be due to #16780?

**Comment by sandy081** [comment]
@ramya-rao-a Yes partially. This was fixed for internal usage but not in API. Will need to adopt and fix it.

**Comment by sandy081** [comment]
This got fixed with https://github.com/Microsoft/vscode/issues/19625
