### ISSUE TITLE
The command updateCellMetadata does not work

### ISSUE THREAD

**Issue by HatemMn** [microsoft/vscode#190160]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.78.2 / Insiders version 1.78.0
- OS Version: Windows 11

Steps to Reproduce:

1. Make a simple extension and add this code : 
```
  let someCommand = commands.registerCommand(
    "vscode-some-extension.notebookcommand",
    async () => {
      const activeNotebookEditor = vscode.window.activeNotebookEditor;
      const currentNotebook = activeNotebookEditor?.notebook;
      if (currentNotebook) {
        const edit = new vscode.WorkspaceEdit();

        edit.set(currentNotebook.uri, [
          vscode.NotebookEdit.updateCellMetadata(0, {
            ["custom.metadata"]: "value",
          }),
        ]);

        await vscode.workspace.applyEdit(edit).then((success) => {
          if (success) {
            console.log("success"); // gets printed
          } else {
            console.log("failure");
          }
        });
      }
    },
  );
```
2. Do not forget to register the command "vscode-some-extension.notebookcommand" in the package.json when you will try it
3. Open the extension development host, then choose a notebook of your choice with some cells, and select a cell
4. Launch the command
5. Vscode will show that icon meaning the file has changed and should be saved, press Ctrl+S to save.
6. Now check your notebook, **the metadata was not written !**

I would also like to say that this command is not documented i.e. no tutorial explains how to use "updateCellMetadata"
If we replace it with deleteCells, the cell ( or cells ) will get deleted, so the method looks correct.

**Comment by r3m0t** [comment]
Try 
```typescript
const ne = new NotebookEdit(new NotebookRange(0, 1), []);
ne.newCellMetadata = {
            ["custom.metadata"]: "value",
          };
```

**Comment by amunger** [comment]
The metadata object has a specific structure with a `custom` and inner `metadata` field, and should probably be typed better. You can look at the result of `currentNotebook.cellAt(0).metadata` in the debugger to see it (easier to see when your cell has metadata)

slight alteration to your code to make it work:

```
const edit = new vscode.WorkspaceEdit();

const metadata = currentNotebook.cellAt(0).metadata;
metadata.custom.metadata.myKey = 'value';

edit.set(currentNotebook.uri, [
	vscode.NotebookEdit.updateCellMetadata(0, {
		...metadata,
	}),
]);
```

I'll leave this issue open though to see if we can improve the typing, or report a failure when we don't successfully update the metadata.

**Comment by HatemMn** [comment]
thank you for this last reply, it works !
I wanted to add that you should save the notebook now, so if some reader copies my code above, do not forget to add : 
`currentNotebook.save()`
