### ISSUE TITLE
Editors are identified case-sensitively on case-insensitive file systems leading to multiple editors for the same underlying file

### ISSUE THREAD

**Issue by jacobdufault** [Microsoft/vscode#19014]
- VSCode Version: 1.8.1
- OS Version: Windows 10

Steps to Reproduce:

On Windows:
1. Open the same file twice via the command line but using different case, ie, `code foo` and `code FOO`.
2. There will be two editors open despite being backed by the same underlying file.

This is not limited to just the command line API, ie, a debugger can open up a file with a different case than what is present on the file-system which ends up causing breakpoints to not display properly.

**Comment by bpasero** [comment]
#12448
