### ISSUE TITLE
Installed extensions, their settings windows open empty

### ISSUE THREAD

**Issue by knitdv** [microsoft/vscode#190132]
I run vscode server on docker https://hub.docker.com/r/linuxserver/code-server. Installed extensions, their settings windows open empty, tried different browsers.

Cose-server not use SSL certificate

![image](https://github.com/microsoft/vscode/assets/120610336/628e924e-3039-4884-a604-bcb6ad6f28c4)

**Comment by roblourens** [comment]
We don't support code-server officially
