### ISSUE TITLE
CSRF 

### ISSUE THREAD

**Issue by mdd228** [microsoft/vscode#190177]
Getting this error message no matter the changes

"""
Forbidden (403)
CSRF verification failed. Request aborted.

Help
Reason given for failure:

    Origin checking failed - https://localhost:8000 does not match any trusted origins.
"""

The login/register landing page in all python/Django app on Github codespaces mdd228 Humble Memory and all others are as of now getting this error message. I've done all the things like having csrf token in forms and have from the beginning it seems to be someone in the github environment that has changed.

Please help!

Kindly,

Mike

ADD ISSUE DESCRIPTION HERE

Version: 1.82.0-insider
Commit: d62534a60f7eb4280bcbee66bbd84a2e15f13765
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36 Edg/115.0.1901.200
Embedder: codespaces

**Comment by mdd228** [comment]
The register and login pages were working and then they stopped and no changes in the code were made that I'm aware of.

Upon investigation it is found that all apps in the github codespaces "Humble Memory" are working yet all of them are showing CSRF errors

**Comment by lszomoru** [comment]
@mdd228, based on the description this does not seem like an issue with VS Code. Could you please file an issue [here](https://github.com/orgs/community/discussions/new?category=codespaces) so that the Codespaces team can investigate further? Thanks!
