### ISSUE TITLE
Can i add external property for git push command

### ISSUE THREAD

**Issue by inchara-1998** [microsoft/vscode#190174]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 
- OS Version: 

Steps to Reproduce:

1. We can add issues/JIRA number which we are working to push command from command prompt.
Please refer below screenshot

![image](https://github.com/microsoft/vscode/assets/118963451/55d76ce7-711c-4b0f-874d-2db86fa8343f)

Same thing i want to do from vs code using git extension once we open any git repository i am activating extension i am building and trying to show the issues/JIRA which user is working. but once they select that i should add selected issue in push command.

Can i know how to do is it possible.

please refer below image i am loading issues in workitem tab i need to pass that issue number as mentioned in error log.

![image](https://github.com/microsoft/vscode/assets/118963451/c4e85bef-7ce6-4b35-bb6a-c590611d17ec)

**Comment by lszomoru** [comment]
@inchara-1998, thank you very much for filing this issue. No, at the moment there is not way to control the `--push-option` to the `git push` command that is executed by VS Code. At the moment we do not have any plans to expand the capabilities of the git extension API.
