### ISSUE TITLE
Confusing tooltip and action on default notification API

### ISSUE THREAD

**Issue by timheuer** [microsoft/vscode#190190]
Repo: use the default notifications API sample to see this behavior (https://github.com/microsoft/vscode-extension-samples/blob/main/notifications-sample/src/extension.ts#L24C3-L28C4)

When a notification is shown there is a "settings" icon on the notification window.  Upon hover you get a tooltip that says "Configure Notification" (english version).  When you click on the icon the action is "Manage Extensions" -- these are not the same meaning.

Consider re-wording the tooltip to match what that actually actions available are.

![image](https://github.com/microsoft/vscode/assets/4821/4e2a0964-7e6b-42f2-b7d1-54490ed66202)

**Comment by bpasero** [comment]
To what?

**Comment by timheuer** [comment]
> To what?

Well I'll defer to the product owners...especially since I've only seen one menu from that settings button ever in my personal usage...but questions I had/have as a user...

- What does "Configure Notification" mean, I don't see any option to configure anything about this notification?
- What else goes in that menu when I click it from a notification? Is it only "Manage Extension" if so, then just make the tooltip match that
- What is the intent of "Manage Extension" from a notification window as a primary action? Is that a natural place one would expect to find that? When does it make sense?
- Why does it show persistently when I have actions, but not if I just show an info/error message with no actions (but shows on hover)? Why the difference?
- The action itself seems to just launch the extension page and not the settings...not knowing what "manage extension" meant I expected to take it to Settings->Extension-> my extension settings...but it doesn't.

So I dunno, but based on my experience, I think I'd just change it to match what appears to be the only available option from that icon - "Manage Extension"

**Comment by bpasero** [comment]
But that is not the only available option in the menu. Notifications from core are free to provide any secondary actions they want. Only extensions get the single entry.

**Comment by timheuer** [comment]
> Notifications from core are free to provide any secondary actions they want.

I assume 'core' here refers to the shell, this is not an exposable API that extension authors can add their own secondary actions in that menu location (or at least if it is I cannot find it in the API docs).

Putting my PM hat on -- do we have data to show how many times only the single action is shown in the menu versus additional ones from the core?

I guess to me, so far all I've seen is one option ever and so the tip and action are confusing to me as a user.  The "do not show again" i've always seen as a checkbox within the notification not in the subsequent action drop-downs.

But I'll make a few suggestions since the it might appear the only one that is truly "configure notification" is really the 'don't show me again' (which as I've said I've never experienced it hidden in that menu) and others that **I've experiences** have nothing to do with configuring the notification.

Suggestions:
- if only one menu option will be shown, match the tooltip to be that of the only menu option shown.  So default it would look like this would mean the tooltip would get "Manage Extension" and the only action is "Manage Extension"
- Genericize it more since it is mixing things that you indicate may come from the core that _might?_ be actual notification configuration, but also may not.  Change it to "Additional options" or "Additional actions"
- combine the two above.  have the if() check if only one option, then if it isn't choose a better generic term.

I guess in the end I'm just saying as a user the 98% case I've seen (giving myself room for error I may have missed) is that it is only one option and has nothing to do with actually configuring the notification.

**Comment by bpasero** [comment]
I am fine changing the tooltip, but I do not think it makes any sense to change the tooltip based on what actions are in the dropdown. Think about the gear icon as a way to access secondary actions for the notification that are not shown as primary buttons. So the name would have to reflect that and be static, not depending on the contents.

**Comment by timheuer** [comment]
> the gear icon as a way to access secondary actions for the notification that are not shown as primary buttons

I guess I'm just sharing feedback that my lived experience with the product is that it has never been this.  Would love to see the scenarios where it does this, but I've just never seen it outside of the reason I logged this feedback.

> So the name would have to reflect that and be static, not depending on the contents.

Yeah I think this is the best as well (localization easier, etc., etc.)

**Comment by bpasero** [comment]
Going with "More Actions..." which is what we use in all other places where we have a "..." dropdown menu.
