### ISSUE TITLE
Customizable Explorer model

### ISSUE THREAD

**Issue by AstroJaga** [Microsoft/vscode#19019]
Please allow customization of the Explorer (files & folders side bar) model to allow opening files from sources other than the plain file system/directory structure.

Examples include allowing to view/edit the contents of a ZIP file containing the project files or viewing/editing code packaged in proprietary binary formats like Oracle's FMB or PLL files.

**Comment by mousetraps** [comment]
Nice idea! I think a few other folks may have also had the same idea, though, so closing as a duplicate of one of the following:
* https://github.com/Microsoft/vscode/issues/6328
* https://github.com/Microsoft/vscode/issues/15485

Let me know if you were thinking something else, though, and we can reopen.
