### ISSUE TITLE
3 high severity Chromium vulnerabilities in VSCode 1.81 - patched in Electron 22.3.20

### ISSUE THREAD

**Issue by lorand-horvath** [microsoft/vscode#190140]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.81.0
- OS Version: Windows 10 x64

Steps to Reproduce:

The latest VSCode July 1.81 includes Electron 22.3.18 which has 3 high severity vulnerabilities in Chromium.
https://github.com/advisories/GHSA-6f46-9vvr-v3j5
https://github.com/advisories/GHSA-fxgf-5cm8-2f8q
https://github.com/advisories/GHSA-2gmm-4f9j-mw4p

These have been patched/backported in Electron 22.3.20 https://github.com/electron/electron/releases/tag/v22.3.20
@deepak1556 Would you please include these fixes in the new July Recovery?

**Comment by deepak1556** [comment]
Thanks for bringing this up, we don't have internal builds available yet for `22.3.20` so it won't make the cut for `1.81.1` but I will try to get it in for `1.81.2` instead.

**Comment by deepak1556** [comment]
Out of the 3 issues the only relevant one for VSCode is https://github.com/advisories/GHSA-6f46-9vvr-v3j5

**Comment by lorand-horvath** [comment]
> Thanks for bringing this up, we don't have internal builds available yet for `22.3.20` so it won't make the cut for `1.81.1` but I will try to get it in for `1.81.2` instead.

@deepak1556 That would be good, but will there even be a 1.81.2? I don't see any sign of one being created in milestones https://github.com/microsoft/vscode/milestones

**Comment by deepak1556** [comment]
Yeah we don't have plans for `1.81.2` at this time, after looking at the CVE we have decided it to not be a candidate. Thanks again for raising the issue!

**Comment by lorand-horvath** [comment]
@deepak1556 Please reconsider incorporating the latest `Electron 22.3.22` backports into `VSCode 1.81.2`. Several high severity vulnerabilities have been corrected.
https://github.com/electron/electron/releases/tag/v22.3.22
