### ISSUE TITLE
Multiuser (liveshare) autosaves makes editing incredibly frustrating

### ISSUE THREAD

**Issue by pbiggar** [microsoft/vscode#190183]
Does this issue occur when all extensions are disabled?: No

- VS Code Version: 
```
Version: 1.81.0
Commit: 6445d93c81ebe42c4cbd7a60712e0b17d9463e97
Date: 2023-08-02T12:40:02.782Z
Electron: 22.3.18
ElectronBuildId: 22689846
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Darwin x64 22.4.0
```

I'm working in a liveshare, editing as guest. Host has autosave to "after-delay", I have autosave "onFocusChange".

If I type a space, then pause (eg to think, or let copilot generate code), the host's machine autosaves, removing the space(s), and resetting my cursor to a different position.

This causes me to type two words without a space, or moves my cursor to the start of a line. Often it will imply to copilot to stop inferring as well. It even pops me out of Vim mode's insert mode.

It makes VSCode basically unusable.

It would seem that VSCode should only autosave for the author of an edit perhaps?

**Comment by bpasero** [comment]
Please report this to the LiveShare extension to get their opinion and weather this is something they can control. I do not fully see how VS Code could change this.

**Comment by pbiggar** [comment]
My bad, I thought LiveShare was part of the core product. Sorry for the noise!
