### ISSUE TITLE
Intellisense does not work for Javascript in Polygot notebook

### ISSUE THREAD

**Issue by alokkr016** [microsoft/vscode#190129]
I am writing to bring to your attention a feature request that, I believe, will significantly enhance the utility of the Polyglot Notebook, especially for JavaScript developers like myself. The current lack of Intellisense support for JavaScript in the notebook is a limitation that affects the coding experience and productivity.

**Comment by gjsjohnmurray** [comment]
I think your Polyglot Notebook is contributed by an extension, so I suggest you raise the issue with the extension authors.
