### ISSUE TITLE
Search & Replace text with blank string does not work

### ISSUE THREAD

**Issue by santanu-biswas** [Microsoft/vscode#19013]
- VSCode Version: 1.9.0 - insider
- OS Version: macOS Sierra Version 10.12.2

Steps to Reproduce:

1. Select a text to replace with blank string (zero length string).
2. Press cmd-opt-F to open search-replace box.
3. Ensure that the selected text is now in the first textbox of search-replace box.
4. Ensure nothing is typed in second textbox (Replace) of search-replace box.
5 Click on 'Replace' or 'Replace All' buttons (adjacent to replace textbox).

**Expected Result**: 
Occurrences of text on search box should get replaced by blank zero length string (regular normal behaviour in any rext editor).

**Actual Result**:
Nothing happens!

**Comment by alexandrudima** [comment]
This has been fixed via 8289f6fa059d580ec063386ccebb4bde2354bb89
