### ISSUE TITLE
Terminal color looks weird when `terminal.ansiWhite` is set to `#dbd7caee`

### ISSUE THREAD

**Issue by so1ve** [microsoft/vscode#190153]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.82.0-insider bf9c8105647b1e9d244f0f00155c21298e7554cf
- OS Version: Windows 11 22H2 22621.1992

Steps to Reproduce:

1. Add these configuration:

```json
"workbench.colorCustomizations": {
	"terminal.foreground": "#dbd7caee"
},
```

The opacity matters. If you remove `ee`, this issue will disappear.

2. Then trigger auto complete in you terminal:

![](https://github.com/microsoft/vscode/assets/58381667/46932836-b0b0-4ed3-be09-e328e5faeb71)

**Comment by Tyriar** [comment]
Oh you're not allowed to use opacity there, we should handle this gracefully. Upstream: https://github.com/xtermjs/xterm.js/issues/4660
