### ISSUE TITLE
 "Go to Definition" - Path Resolution Problem

### ISSUE THREAD

**Issue by JKamsker** [microsoft/vscode#190159]
Type: <b>Bug</b>

While working on a C# project using Microsoft's "C# Dev Kit" in Visual Studio Code, I encountered an error when trying to navigate to a specific file using the "Go to Definition" feature. The error prevents the file from being loaded. However, manually opening the file from the explorer works without any problems.

**Steps to reproduce**:
1. In a C# file, navigate to a piece of code that references another file or definition.
2. Right-click and select "Go to Definition" or use the appropriate keyboard shortcut.
3. Observe the error when Visual Studio Code tries to open the target file.

**Expected behavior**: 
The target file should open without any issues when using "Go to Definition."

**Actual behavior**:
Received an error message:
```
Unable to open 'SourceFile.cs'
Unable to resolve resource c:%5CUsers%5CMyUser%5Csource%5Crepos%5Cwork[...]SourceFile.cs
```

**System Information**:
- OS: Windows 10 Pro 22H2 (19045.3208)
- Visual Studio Code Version: 1.81.0
- C# Dev Kit Version: v0.3.21

**Possible cause**:
There seems to be a path resolution issue specifically when using the "Go to Definition" functionality. The encoded characters in the error message path (e.g., `%5C`) suggest a problem in interpreting the path.

**Additional Information**:
- Opening the file directly from the explorer works correctly.

VS Code version: Code 1.81.0 (6445d93c81ebe42c4cbd7a60712e0b17d9463e97, 2023-08-02T12:37:13.485Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 9 3900X 12-Core Processor             (24 x 3793)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|63.92GB (31.90GB free)|
|Process Argv|--folder-uri file:///c%3A/Users/W31rd0/source/repos/work/Apro/Apro.AutoUpdater --crash-reporter-id ee7f0ea2-039d-49cd-a2ce-8a645856b957|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (66)</summary>

Extension|Author (truncated)|Version
---|---|---
azurite|Azu|3.25.1
vscode-intelephense-client|bme|1.9.5
smali|cra|1.0.1
csharpier-vscode|csh|1.3.6
dscodegpt|Dan|2.1.15
es7-react-js-snippets|dsz|4.4.3
gitlens|eam|14.2.0
prettier-vscode|esb|10.1.0
vscode-diff|fab|1.4.2
copilot|Git|1.101.317
copilot-labs|Git|0.14.884
vscode-format-context-menu|lac|1.0.4
smalise|Loy|0.0.12
graphql|mqu|0.1.2
vscode-azureresourcegroups|ms-|0.7.5
vscode-azurestorage|ms-|0.15.3
vscode-cosmosdb|ms-|0.19.4
vscode-docker|ms-|1.26.0
vscode-language-pack-de|MS-|1.81.2023080209
csdevkit|ms-|0.3.21
csharp|ms-|2.0.346
vscode-dotnet-runtime|ms-|1.6.0
vscodeintellicode-csharp|ms-|0.1.26
isort|ms-|2023.10.1
python|ms-|2023.14.0
vscode-pylance|ms-|2023.8.20
jupyter|ms-|2023.7.1002162226
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.17
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-slideshow|ms-|0.1.5
remote-containers|ms-|0.304.0
remote-ssh|ms-|0.102.0
remote-ssh-edit|ms-|0.86.0
remote-wsl|ms-|0.81.0
vscode-remote-extensionpack|ms-|0.24.0
azure-account|ms-|0.11.5
cmake-tools|ms-|1.15.31
cpptools|ms-|1.16.3
cpptools-extension-pack|ms-|1.3.0
hexeditor|ms-|1.9.12
powershell|ms-|2023.6.0
remote-explorer|ms-|0.4.1
remote-server|ms-|1.4.0
sqltools|mtx|0.28.0
sqltools-driver-mssql|mtx|0.4.1
batch-runner|Nil|1.1.2
vetur|oct|0.37.3
ngrok-for-vscode|phi|1.10.1
csv-to-table|php|1.4.0
gptcommit|pww|0.3.0
java|red|1.21.0
vscode-xml|red|0.26.1
vscode-yaml|red|1.14.0
ReliableWebhook|Rel|1.0.5
LiveServer|rit|5.7.9
rust-analyzer|rus|0.3.1615
bash-beautify|sha|0.1.1
vscode-il|sol|0.0.1
apklab|Sur|1.7.0
zip-file-system|Tom|2.0.0
cmake|twx|0.0.17
gistfs|vsl|0.4.1
vscode-wakatime|Wak|24.2.0
markdown-all-in-one|yzh|3.5.1
t4-support|zbe|0.7.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
py29gd2263cf:30792227
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
vsccc:30803844
2e4cg342:30602488
f6dab269:30613381
showlangstatbar:30737416
vsctsb:30748421
a2ce3375:30757347
pythonfmttext:30731395
pythoncmv:30756943
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
gsofa:30804715
pythonnosmt12:30797651
pythonidxpt:30805730
pythonnoceb:30805159
e537b577:30795824
dsvsc013:30795093
dsvsc014:30804076

```

</details>

**Comment by hastarin** [comment]
This appears to be a bug in the preview version of the C# extension.  csharp v2.0.346

**Comment by dbaeumer** [comment]
As pointed out by @hastarin this is a problem with the C# Dev Kit extension . Please file the issue here: https://github.com/microsoft/vscode-dotnettools/issues
