### ISSUE TITLE
每次打开vs都要下载这些

### ISSUE THREAD

**Issue by dsc6636926** [Microsoft/vscode#19016]
![image](https://cloud.githubusercontent.com/assets/7552492/22196589/e6aaeeb4-e188-11e6-8e8a-d441cb81c0e7.png)
这个怎么办，我感觉这些应该都属于全局性的东西，下载一次也就可以了，但是为啥每次打开vscode都要下载这一堆插件，要等他们都下载完才能调试代码

**Comment by dbaeumer** [comment]
Can someone help translating this. We don't speak the language used.

**Comment by dsc6636926** [comment]
everytime I start vscode，it will download these tools，so I must wait for a long time to debug my code

**Comment by dbaeumer** [comment]
@dsc6636926 thanks !

Moving to OmniShapr then.

**Comment by dbaeumer** [comment]
This issue was moved to OmniSharp/omnisharp-vscode#1139
