### ISSUE TITLE
editor should not be dimmed when navigating search results

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#190102]
https://github.com/microsoft/vscode/assets/29464607/c8df8483-b7bb-48a7-80f7-d05ad7d6f203

**Comment by Tyriar** [comment]
@andreamah is there any class or something other CSS class we could use to disable this opacity rule for the editor when a search is active?

https://github.com/microsoft/vscode/blob/91acb9551bd962df44717294b8b02909e3f72e8d/src/vs/workbench/contrib/accessibility/browser/unfocusedViewDimmingContribution.ts#L49

**Comment by andreamah** [comment]
> editor.mov

this is loading for me as a 1-second video. could you re-attach the video? I'm not sure where that opacity rule is referenced in search.

**Comment by Tyriar** [comment]
@andreamah it's not referenced in search, it's a small workbench contrib that currently depends on terminal and editor. We also want to include search in the rule to ensure the editor with the active match also shows up, even when it's not focused.

**Comment by andreamah** [comment]
What are the repro steps to seeing the dimmed editor when viewing search results? I don't think I see it.

**Comment by meganrogge** [comment]
set `accessibility.unfocusedViewOpacity` and open the search panel, search for something and click through the results

**Comment by andreamah** [comment]
Ah, I see it now. Can we check for context keys? If `hasSearchResult` & `searchViewletFocus`, then don't dim the editor?

**Comment by Tyriar** [comment]
We could use `IContextKeyChangeEvent.onDidChangeContext` but that would involve setting up a listener and replacing the CSS. That's an option, but it would be preferable if there's something like `.has-search-results`. If that doesn't exist that's fine, we can go the event route.

**Comment by andreamah** [comment]
Sorry for the late reply on this. I don't think there's anything like `.has-search-results` since search uses the context key to make changes to the view. We could probably have to do a `IContextKeyChangeEvent.onDidChangeContext` for `hasSearchResult`

**Comment by Tyriar** [comment]
Merging into https://github.com/microsoft/vscode/issues/236576

/duplicate
