### ISSUE TITLE
Double edit action in settings

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#19021]
1. Open settings, have a cursor on some line
2. Move the mouse over some other lines
3. Notice there are two edit action appearing in the margin

Why do we show the edit action in the margin on the line where the cursor is?
I thought this edit action is asociated with user clicking on it, thus it should follow the mouse.

As an unrelated bug you can also see that glyphMargin: false looks bad with your edit actions, but I already filled that

![screen shot 2017-01-23 at 11 24 32](https://cloud.githubusercontent.com/assets/1926584/22200264/ac1e8ffa-e15e-11e6-9a25-5b2c31f0ea44.png)

**Comment by sandy081** [comment]
Thanks for the feedback.

> Why do we show the edit action in the margin on the line where the cursor is?

This is similar to how light bulb behaves. Light bulb shows on the line where the cursor is. It helps in discovering the action while navigating with keyboard.

> As an unrelated bug you can also see that glyphMargin: false looks bad with your edit actions, but I already filled that

Fixed

**Comment by isidorn** [comment]
Not sure I am a fan of that - showing two light bulbs / edit actions at once.
Did we try to only show one always - namely if there is a cursor active show it, but the mouse takes priority - if you hover over a line with a margin action do not show the one at the cursor?

**Comment by sandy081** [comment]
I have to correct myself here.. Two light bulbs are not shown at a time. Light bulb is only shown when the current line is active. This behavior is added to Edit actions on top of Mouse move.

**Comment by isidorn** [comment]
My point stays the same I would prefer not to see two of these actions at once :)

**Comment by bpasero** [comment]
+1 for not seeing 2 actions at the same time ever
