### ISSUE TITLE
[Bug][Comparison View] Saving the file in the active editor will cause both files to be saved.

### ISSUE THREAD

**Issue by cyan33** [microsoft/vscode#190210]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 
- OS Version: 

Steps to Reproduce:

1. Open VS Code, select two files, right click on one of them and "Compare Selected Files"
2. Editing one of the file, observe the other file also get saved, and trigger watchman as a file change.

Hi team, we use [watchman](https://facebook.github.io/watchman/) to monitor file changes on the disk. When using the comparison view functionality provided by vs code, I've verified that editing -> saving one file in the comparison view will trigger the compared file also getting saved, which becomes a false signal to watchman that some content has changed for that file.

I'm not sure if it's a bug, but it'd be ideal if we can update this behavior and only save the file for the **active editor**. Thoughts?

**Comment by bpasero** [comment]
Saving both sides is expected when both are dirty, but I see how it maybe confusing when the left hand side is not dirty to save it then.

**Comment by cyan33** [comment]
> Saving both sides is expected when both are dirty, but I see how it maybe confusing when the left hand side is not dirty to save it then.

Yeah, this seems like essentially a race condition. For some context this causes some degree of problem when we build a service/extension that copys the file content from a file to the compared file. And within comparison view, this behavior races with the service which resulted in an error "file content in the disk is newer, overwrite or compare" error.

Any thoughts on how to mitigate it?

**Comment by bpasero** [comment]
I think I can see to make a change to not save the left hand side when it is not dirty. But note that an explicit save triggered by the user will always flush the contents to disk even when the file is not dirty. This has been the standard behaviour of VS Code for a long time and allows to trigger external file watchers.

**Comment by cyan33** [comment]
> But note that an explicit save triggered by the user will always flush the contents to disk even when the file is not dirty

I agree with this, but not quite with the part that it always saves the primary/right side of the editor. Why can't just the active (the file the is currently being edited) file be saved?

I guess the challenge to even hack around this is that, regardless whether the left or right editor is saved, the actual file i/o is always that the primary/right editor gets saved first, then the left. This makes it hard for anything outside of vscode to actually tell where the change is actually coming from. 😞

**Comment by cyan33** [comment]
> I think I can see to make a change to not save the left hand side when it is not dirty.

but if this change can be made, I think I have a hacky way to workaround this issue.

**Comment by bpasero** [comment]
I think it needs to work predictably based on the state of the diff editor:
* both sides dirty: saving saves both sides irrespective where focus is
* no side is dirty: saving saves only the side that has focus?
* one side is dirty: what should happen based on focus?

Currently it is predictable in a way that saving will always just save both sides, irrespective of dirty state. So if we change that, we should change to a new predictable state.

Can you make a suggestion based on this? And as for the order of saves: is that relevant for you as well?

**Comment by bpasero** [comment]
I think we cannot do that. First of all, which editor has focus is very subtle. And then we have always had save trigger a save on the right hand side irrespective of focus even before we added the support for saving both sides. So you would degrade the experience for existing users.

The more I think about it the more I feel the current behaviour is the only consistent one actually. 

What exactly is the issue with this behaviour? It is the first time I hear someone complain about it?

**Comment by cyan33** [comment]
I don't think I agree w/ the rational here. If you have multiple editors open, saving one wouldn't save others. From the code authoring perspective I don't think the comparison view is anything different from seeing the files from separate editors. 

What makes diff view special that we need to save both of them?

**Comment by bpasero** [comment]
Decided to push a change to only consider the left hand side of a diff editor for saving when it is dirty.

**To verify:**
* compare 2 files that are editable
* change the left hand side
* verify you see a dirty editor opening as tab in the background
* save the diff editor (`Cmd+S`)
* verify the dirty editor in the background is saved
* change the right hand side
* verify the diff editor gets dirty
* save the diff editor (`Cmd+S`)
* verify the dirty diff editor is saved
* change both sides
* save the diff editor (`Cmd+S`)
* verify the 2 dirty indicators went away

**Finally verify this issue in particular:**
* compare 2 editable files
* take note of the modification timestamp on the file system using OS explorer
* save the diff editor (`Cmd+S`)
* verify that the right hand ("primary") side file updated its modification timestamp
* verify that the left hand ("secondary") side file modification timestamp did not change
