### ISSUE TITLE
Unable to run `tunnel` command for Linux build

### ISSUE THREAD

**Issue by christian-bromann** [microsoft/vscode#190274]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.81.1
- OS Version: Ubuntu

```
    OS: Linux 5.15 Ubuntu 22.04.3 LTS 22.04.3 LTS (Jammy Jellyfish)
    CPU: (10) arm64 unknown
    Memory: 12.73 GB / 15.61 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
```

Steps to Reproduce:

1. Start environment e.g. via `docker run -ti --rm ubuntu /bin/bash` 
1. Install build-essentials `apt install build-essential`
1. download provided version of VS Code
1. run tunnel command
```sh
/path/to/dir/.vscode-test/vscode-linux-arm64-1.81.1/bin/code tunnel --no-sandbox --accept-server-license-terms rename machine-169177573586 --user-data-dir ./foo
```

Which returns:

```
spawn /fixme/.vscode-test/vscode-linux-arm64-1.81.1/bin/code-tunnel ENOENT
```

Note: this only happens on Linux.

**Comment by connor4312** [comment]
Duplicates https://github.com/microsoft/vscode/issues/189383
