### ISSUE TITLE
ITerminalInstance doesn't sent onExit if terminal is disposed with running process

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#19026]
Steps to reproduce:

- create a terminal with a running process 
- dispose the terminal by pressing the garbage bin button

Observe:

you get ITerminalInstance.onDisposed() but no ITerminalInstance.onExit(). Since the process exists as well I would expect to first receive the onExit and then the onDisposed event.

**Comment by dbaeumer** [comment]
@Tyriar this one would be important for me for the January milestone.

**Comment by Tyriar** [comment]
I'm seeing `onExit` fire, it's just giving a `null` exitCode? I added this:

```ts
		terminalInstance.onExit(code => {
			console.log('onExit: ' + code);
		});
```

to `TerminalService.createInstance` and hit the trash button and see `onExit: null` in output?

There is this in `TerminalInstance.dispose` which should fire the listener.

```ts
		if (this._process) {
			if (this._process.connected) {
				this._process.kill();
			}
			this._process = null;
		}
```
I can see why this would not happen when you call `reuseTerminal` though? Is that the case you mean? What platform are you on if not?

**Comment by dbaeumer** [comment]
Happens for me under Windows even if the terminal is created the first time. Here is my tasks.json

```json
{
    "version": "0.1.0",
    "_runner": "terminal",
    "tasks": [
        {
            "taskName": "tsc",
            "command": "tsc -w",
            "isShellCommand": true,
            "isBackground": true,
            "problemMatcher": "$tsc-watch"
        }
    ]
}
```

Mt tsconfig.json
```json
{
	"compilerOptions": {
		"module": "commonjs",
		"sourceMap": true,
		"target": "es6"
	}
}
```

and a ts file with some errors

- Start the task and set a breakpoint in terminalTaskRunner.ts line #257 & #290 (exit callback) #410 (dispose callback). I even set a breakpoint in terminalInstance#_onPtyProcessExit
- Dispose the terminal by pressing the garbage bin. 

Observe: breakpoint in dispose is hit but none of the exit callbacks are hit.

**Comment by dbaeumer** [comment]
I added a console.log statement and that is printed. Looks like a debugger problem.

**Comment by dbaeumer** [comment]
OK. Adding console.log statements only I get the following sequence:

Dispose called terminalTaskSystem.ts:412 
Dispose called terminalTaskSystem.ts:412 
Exit called terminalTaskSystem.ts:257 

So I do get the exit but I do get dispose twice. Changed title.

**Comment by dbaeumer** [comment]
Not critical for January anymore since I protected myself against the second dispose call.
