### ISSUE TITLE
Space inserted before "!" in .ts file

### ISSUE THREAD

**Issue by awerlang** [Microsoft/vscode#19027]
- VSCode Version: 1.8.1
- OS Version: Windows 10

Steps to Reproduce:

1. Type this code:

```
const myVar = alert()!;
```
2. You'll see that when you type the ";", an space is introduced before the "!".

The "Format" command also leads to the same result.

**Comment by mousetraps** [comment]
By golly, you're right! 

@mjbvz - looks like a JS/TS issue - interestingly enough, this only seems to affect the `!` unary operator, and not others like `++`, and it only manifests after a function call (e.g. `const myVar = a!;` is fine)

**Comment by mjbvz** [comment]
This is fixed in TS 2.2.

You can start using a preview of TS 2.2 by installing `typescript@next` in your workspace: `npm install typescript@next` and updating the `typescript.tsdk` setting to use this local copy: `"typescript.tsdk": "./node_modules/typescript/lib"
