### ISSUE TITLE
Git error message should include git output

### ISSUE THREAD

**Issue by felixfbecker** [Microsoft/vscode#1902]
Currently, when I try to switch branches while my work tree is dirty, I get a message "There was an issue doing a git operation. Please look at the git output." When I open the output, there is a one-line message, highlighted in red because it's printed to stderr, "could not switch branches because you have uncommited changes. Please stash or commit them." This error would have fit perfectly inside the Code error message. So, when there is an error, please just take what's printed to stderr, truncate it if needed, and show "Git error: <message>". If message is long, just truncate with ellipsis. The user can click Show Output to get the full message.

**Comment by joaomoreno** [comment]
@felixfbecker The reason why we don't do it is that git errors come in many different shapes or sizes. If you truncate many of the git errors, you won't get anything meaningful. This generic approach works for most cases.

What we can do instead is catch each error individually and provide a good UX for them. The specific case you mention (checkout with dirty tree) also happens to me quite often, so let's catch that and display a better error message when it happens.

**Comment by felixfbecker** [comment]
Maybe you can then inspect git exit code?

**Comment by joaomoreno** [comment]
We should just have a logger... then we'd have somewhere where to send this.

**Comment by joaomoreno** [comment]
Error handling is now improved. All git output ends in the Git Output channel.
