### ISSUE TITLE
Go to File includes files that are excluded by files.exclude/search.exclude

### ISSUE THREAD

**Issue by sjelfull** [Microsoft/vscode#19029]
My build process compiles files to public/*.html, and i'm trying to exclude the compiled files from search and Go to File.

My workspace settings looks like this:

```json
{
    "search.exclude": {
        "**/.git": true,
        "**/node_modules": true,
        "**/public": true,
        "**/bower_components": true
    },

    "files.exclude": {
        "**/public": true
    }
}
```

The settings seems to be applied to search and file explorer, but it's still appearing in the Go to File results.

I can't find any option in the default config that applies specifically to the Go to File results.

- VSCode Version: 1.8.1
- OS Version: OSX Sierra 10.12.1

Steps to Reproduce:

1. Apply the settings above to your workspace
2. Create a couple `.html` files in a folder called `public`

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/6502

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: http://code.visualstudio.com/Download#insiders

**Comment by sjelfull** [comment]
@bpasero Thanks, this is fixed in the insiders build.
