### ISSUE TITLE
Style misalignment between search widget input box and settings input box

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#19023]
Why do we have the lense icon in the settings search, while this icon is nowhere else present in our UI? This is not aligning well with our search viewlet input. This icon should be removed as we nowhere else use it in our UI and the placeholder text makes it clear to the user what is going on.

![screen shot 2017-01-23 at 11 29 18](https://cloud.githubusercontent.com/assets/1926584/22200393/3c080f9c-e15f-11e6-8c83-be2220636950.png)

**Comment by sandy081** [comment]
@bgashler1 FYI
