### ISSUE TITLE
add line to accessible view which indicates that shift+tab can be used to explore various actions that are available

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#190287]
cc @jooyoungseo, @rperez030 

similar to "Exit this dialog with the escape key", we could add this at the bottom so it's very clear to the user

**Comment by meganrogge** [comment]
this has happened

**Comment by aeschli** [comment]
Trying to verify, I don't see that hint...

**Comment by meganrogge** [comment]
Changed my mind here and instead included it in the aria label

![Screenshot 2023-08-31 at 8 29 00 AM](https://github.com/microsoft/vscode/assets/29464607/999637eb-9e15-43c2-b023-b4731e2b35fe)
