### ISSUE TITLE
Style misalingment between settings tabs and panel tabs

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#19024]
We should use the same design for our tabs in settings and in the panel. Namely USER SETTINGS and WORKSPACE SETTINGS need to have the same design as the PROBLEMS, OUTPUT... in the panel

Notice that in the panel the unfocused titles color is not so strong and the font used is smaller.

![screen shot 2017-01-23 at 11 31 57](https://cloud.githubusercontent.com/assets/1926584/22200512/b2444946-e15f-11e6-91f0-9b85277095ed.png)

**Comment by bpasero** [comment]
@sandy081 please also do not draw the blue line on :active, it should only show on :focus same as in the panel.

**Comment by ramya-rao-a** [comment]
The font-size for the settings is still bigger than the panel headings

**Comment by sandy081** [comment]
Fixed yesterday in an other issue
