### ISSUE TITLE
font ligatures not working

### ISSUE THREAD

**Issue by dallgoot** [microsoft/vscode#190252]
Type: <b>Bug</b>

since update to v 1.81 :
font ligatures are not showing even when enabled in settings.json
FYI :
it was working before this update with font Cascaydia Code

VS Code version: Code 1.81.1 (6c3e3dba23e8fadc360aed75ce363ba185c49794, 2023-08-09T22:22:42.175Z)
OS version: Windows_NT x64 10.0.25926
Modes:
Remote OS version: Linux x64 5.15.90.2-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz (4 x 2904)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.89GB (2.56GB free)|
|Process Argv|--crash-reporter-id bcd605bf-1222-4856-9b81-f609bb437696|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 5.15.90.2-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz (4 x 2903)|
|Memory (System)|7.70GB (5.26GB free)|
|VM|0%|
</details><details><summary>Extensions (32)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|3.0.2
vscode-babel-coloring|dza|0.0.4
vscode-firefox-debug|fir|2.9.8
vscode-graphql-syntax|Gra|1.2.2
remote-containers|ms-|0.304.0
remote-wsl|ms-|0.81.0
sublime-keybindings|ms-|4.0.10
php-docblocker|nei|2.7.0
material-icon-theme|PKi|4.29.0
vscode-nginx|sha|0.6.0
vscode-icons|vsc|12.5.0
twig|wha|1.0.2
vscode-apollo|apo|1.19.11
vscode-intelephense-client|bme|1.9.5
vscode-eslint|dba|2.4.2
gitlens|eam|14.2.1
vscode-html-css|ecm|1.13.1
code-runner|for|0.12.0
psalm-vscode-plugin|get|2.7.0
vscode-todo-parser|min|1.9.1
vscode-docker|ms-|1.26.0
autopep8|ms-|2023.6.0
python|ms-|2023.14.0
vsliveshare|ms-|1.0.5877
vsliveshare-pack|ms-|0.4.0
composer-Intelephense|mua|1.0.1
php-docblocker|nei|2.7.0
vscode-thunder-client|ran|2.10.2
vscode-yaml|red|1.14.0
rust-analyzer|rus|0.3.1615
tabnine-vscode|Tab|3.7.0
php-allfactor|tra|1.3.4

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
vscccc:30803845
3biah626:30602489
f6dab269:30613381
showlangstatbar:30737416
vsctsb:30748421
03d35959:30757346
pythonfmttext:30731395
pythoncmv:30756943
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
gsofb:30804716
pythonnosmt12:30797651
pythonidxpt:30805730
pythonnoceb:30805159
dsvsc013:30795093
dsvsc014:30804076
diffeditorv2:30810526

```

</details>

**Comment by rzhao271** [comment]
I'm unable to reproduce the issue locally or with the WSL extension with the following settings:
```json
"editor.fontFamily": "Cascadia Code",
"editor.fontLigatures": true
```

Does the issue continue to occur on a new empty profile with just those two settings and no other extensions installed?

**Comment by dallgoot** [comment]
thanks for the response.
It has reverted back and i check the VS Code version that was the same so my guess is that was extension related.
