### ISSUE TITLE
Background color in settings number of results not needed IMHO

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#19025]
Did you try this without the background color?
I do not see the need for the background color as this is already quite seperated from the input as it is on the other end of a huge input field.
Also we do not use background color like this anywhere else in our input boxes

![screen shot 2017-01-23 at 11 34 40](https://cloud.githubusercontent.com/assets/1926584/22200621/16bf2b8e-e160-11e6-8f81-d9ac997a2b29.png)

**Comment by sandy081** [comment]
@bgashler1 FYI

**Comment by sandy081** [comment]
It looks good to me with bg color. But I would wait if it is not appealing and remove it.
