### ISSUE TITLE
Style misalignment between settings search no results and find widget

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#19022]
Notice how the find widget uses a discrete red color in the text, not the background red which looks too ugly and prominent imho
Setting should use the same style which we already have in find widget

Also why is Settings capital case and matched lower case? Maybe we should just say 'No Results'

![screen shot 2017-01-23 at 11 27 09](https://cloud.githubusercontent.com/assets/1926584/22200346/056aec84-e15f-11e6-9b1b-07241686551a.png)

**Comment by ramya-rao-a** [comment]
@sandy081 Just a note on the addition of tooltips
When tooltips have the same text as the link text and link text is not being truncated, there is no benefit of such tooltips. 
If there is more information we'd like to provide, like describing the link, then by all means, you can use the tooltip
