### ISSUE TITLE
Hiding Accounts in activity bar is broken

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#190224]
* latest insiders
* right click the accounts icon
* select/unselect to hide/show it
* 🐛 nothing happens

Note that this also happens when previously hidden, e.g you cannot bring it back anymore

https://github.com/microsoft/vscode/assets/1794099/713ff00e-b90d-4754-96ac-3db60f139aef

**Comment by bpasero** [comment]
Thanks, I think a regression from my changes I did early in the milestone 🙏
