### ISSUE TITLE
[Windows] Error opening a file path with anchor from WSL terminal

### ISSUE THREAD

**Issue by pit00** [microsoft/vscode#190288]
In terminal, ctrl+click at `/mnt/c/Folder/file.txt`, will open the file without problems, but using an anchor `/mnt/c/Folder/file.txt#5`, gives the following error:
![image](https://github.com/microsoft/vscode/assets/12652738/57eb929e-1508-47e2-be84-6e2b3d567eed)

**Comment by Tyriar** [comment]
This is actually a request for `#` to indicate line number which we haven't had requested before.
