### ISSUE TITLE
VS Code shows custom title bar in macOS fullscreen

### ISSUE THREAD

**Issue by vainamov** [microsoft/vscode#190362]
When `window.titleBarStyle` was set to `custom` and the application was in macOS fullscreen mode, it would use the native title bar behavior (show none, until moving the cursor to the top border). This was great, because it increased the screen estate available. Once you left the fullscreen, the custom title bar would reappear. (See previous behaviour below, emulated by switching to `native`)

<img width="1512" alt="grafik" src="https://github.com/microsoft/vscode/assets/11841072/e79a7fb6-a3d0-413b-9331-3fb9a3194c39">

When moving the cursor to the top, the macOS menu and title bar appeared:

<img width="1512" alt="grafik" src="https://github.com/microsoft/vscode/assets/11841072/73b030eb-3e30-451d-aeff-f33121fb447d">

Now, when using the `custom` option, the full title bar is shown, regardless of windowed or fullsize mode.

<img width="1512" alt="grafik" src="https://github.com/microsoft/vscode/assets/11841072/57b7d600-b3ae-4281-854f-4ca2a4159af9">

I tried all settings at my disposible to remove the bar:
```json
"window.commandCenter": false,
"window.title": "",
"workbench.layoutControl.enabled": false,
```
But even then, the full bar with "Visual Studio Code" remains on screen the whole time.

<img width="1512" alt="grafik" src="https://github.com/microsoft/vscode/assets/11841072/5442ea95-4073-4f5b-8b0b-3b09cde1de97">

The bar takes up valuable space and has no use to me, I don't need the command center (I use the keybind) or the layout controls. All it does is show me some text, which I was more than happy to trade-in for 1-2 additional lines of code on my screen (not a loss, if I _ever_ needed the text from the title, I could just move the cursor to the top).

If this isn't a bug please consider this a feature request, to be able to specify a different `window.titleBarStyle` for fullscreen.

While using `native` does solve my problem for the moments where I'm using VS Code in fullscreen, the native title bar is hideous in windowed mode. I wouldn't consider switching them when switching the window mode an option, because changing the setting requires a restart of VS Code and besides feels really cumbersome.

Does this issue occur when all extensions are disabled?: Yes

Version: 1.81.1
Commit: 6c3e3dba23e8fadc360aed75ce363ba185c49794
Datum: 2023-08-09T22:40:25.698Z
Electron: 22.3.18
ElectronBuildId: 22689846
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
Betriebssystem: Darwin arm64 21.6.0 (macOS Monterey 12.6.7)

Steps to Reproduce:

1. Make sure `window.titleBarStyle` is set to `custom`
2. Enter fullscreen

**Comment by sbatten** [comment]
I believe this is fixed by https://github.com/microsoft/vscode/issues/189532
