### ISSUE TITLE
Clicking git sync icon should only push when there are local changes

### ISSUE THREAD

**Issue by felixfbecker** [Microsoft/vscode#1903]
When I clone a github repo, I often dont have write permissions to it. VS Code shows me in the bottom left corner how many different commits I have here and on the remote. When I click the sync icon, it first pulls, and then, even though it shows that I have zero new commits, does a push, which results in a git error.

Git output:
```
git fetch
git show HEAD:adapter/src/debugSession.ts
git show HEAD:adapter/src/debugSession.ts
git pull
git show HEAD:adapter/src/debugSession.ts
git show HEAD:adapter/src/debugSession.ts
git push
ERROR: Permission to Microsoft/vscode-debugadapter-node.git denied to felixfbecker.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

**Comment by joaomoreno** [comment]
Very interesting and common scenario... we need to fix that.

**Comment by bpasero** [comment]
:heart:
