### ISSUE TITLE
Breakpoint is not enabling for Groovy files

### ISSUE THREAD

**Issue by jyo111** [microsoft/vscode#190364]
Type: <b>Feature Request</b>

I am trying to put Breakpoints for Groovy files debugging, but this Breakpoints feature is not working.

VS Code version: Code 1.81.1 (6c3e3dba23e8fadc360aed75ce363ba185c49794, 2023-08-09T22:22:42.175Z)
OS version: Windows_NT x64 10.0.22000
Modes:

**Comment by roblourens** [comment]
Please file this on the repo for whichever extension is responsible for this, I assume the Java debug extension
