### ISSUE TITLE
[Windows] [UX] Content shift in welcome page

### ISSUE THREAD

**Issue by lssbq** [microsoft/vscode#190338]
Type: <b>Bug</b>

One action item in Start section 'Connect to...' is lazy load, may cause false click when I select one 'Recent' project in the bottom below. 

VS Code version: Code 1.81.1 (6c3e3dba23e8fadc360aed75ce363ba185c49794, 2023-08-09T22:22:42.175Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Remote OS version: Linux x64 5.10.16.3-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9850H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.73GB (5.05GB free)|
|Process Argv|--crash-reporter-id da3275a8-3377-414b-84e0-3eb93e88f55a|
|Screen Reader|no|
|VM|40%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 5.10.16.3-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i7-9850H CPU @ 2.60GHz (12 x 2592)|
|Memory (System)|15.50GB (14.09GB free)|
|VM|0%|
</details><details><summary>Extensions (23)</summary>

Extension|Author (truncated)|Version
---|---|---
jsonl|Alp|0.0.1
postcss|css|1.0.9
vscode-eslint|dba|2.4.2
gitlens|eam|14.2.1
prettier-vscode|esb|10.1.0
playwright|ms-|1.0.15
black-formatter|ms-|2023.4.1
isort|ms-|2023.10.1
python|ms-|2023.14.0
vscode-pylance|ms-|2023.8.20
jupyter|ms-|2023.7.1002162226
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.17
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-slideshow|ms-|0.1.5
remote-wsl|ms-|0.81.0
hexeditor|ms-|1.9.12
ortoni|ort|1.0.1
material-icon-theme|PKi|4.29.0
vscode-xml|red|0.26.1
LiveServer|rit|5.7.9
lit-plugin|run|1.3.0
jestRunIt|ves|0.6.0

</details>

**Comment by lssbq** [comment]
![vscode](https://github.com/microsoft/vscode/assets/17997151/01d78515-1c10-43e7-8f34-981204027839)

**Comment by bhavyaus** [comment]
This issue has been fixed in insiders and is pending release.
