### ISSUE TITLE
Test: 'Add configuration' debug select dropdown

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#19033]
- [x] @jrieken 
- [x] @ramya-rao-a 

Complexity: 1

We have added a 'Add configuration' option in the debug select drop down in the debug viewlet. Verify:
* Clicking on this options opens launch.json and triggers intelli-sens so you can easily add a new launch configuration. VSCode will ask for the environment first if it can not auto detect it (namely will not ask if you have a .js file open)
* You can do this even if there is no launch.json

**Comment by ramya-rao-a** [comment]
@pjmeyer Taking this one off your plate, as I was done with my share of test items.

**Comment by ramya-rao-a** [comment]
@isidorn 

When you say

> You can do this even if there is no launch.json

I am assuming you mean in a workspace and not while debugging single files with no folder open

**Comment by isidorn** [comment]
@ramya-rao-a yes, sorry for not making that clear.

**Comment by ramya-rao-a** [comment]
No problem at all
