### ISSUE TITLE
of course. Okay I tried multiple things, I disabled all extensions, uninstalled the newest extensions and uninstalled vs code and reinstalled it again but still the same so I will follow the steps of `Visual Studio Code starts up slowly`

### ISSUE THREAD

**Issue by Akmal5041** [microsoft/vscode#190352]
of course. Okay I tried multiple things, I disabled all extensions, uninstalled the newest extensions and uninstalled vs code and reinstalled it again but still the same so I will follow the steps of `Visual Studio Code starts up slowly`

## Two files of the startup CPU profile
[prof-3Sj321Ml.main.cpuprofile.txt](https://github.com/microsoft/vscode/files/11152467/prof-3Sj321Ml.main.cpuprofile.txt)

[prof-3Sj321Ml.renderer.cpuprofile.txt](https://github.com/microsoft/vscode/files/11152469/prof-3Sj321Ml.renderer.cpuprofile.txt)

## System Info

* Code: 1.77.0 (7f329fe6c66b0f86ae1574c2911b681ad5a45d63)
* OS: win32(10.0.22621)
* CPUs: Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz(12 x 2208)
* Memory(System): 15.81 GB(8.84GB free)
* Memory(Process): 191.26 MB working set(128.03MB private, 2.82MB shared)
* VM(likelihood): 0%
* Initial Startup: true
* Has 0 other windows
* Screen Reader Active: false
* Empty Workspace: false

## Performance Marks

| What                                                            | Duration | Process                   | Info                                                        |
| --------------------------------------------------------------- | -------- | ------------------------- | ----------------------------------------------------------- |
| start => app.isReady                                            | 7018     | [main]                    | initial startup: true                                       |
| nls:start => nls:end                                            | 0        | [main]                    | initial startup: true                                       |
| require(main.bundle.js)                                         | 73       | [main]                    | initial startup: true                                       |
| start crash reporter                                            | 6966     | [main]                    | initial startup: true                                       |
| serve main IPC handle                                           | 2        | [main]                    | initial startup: true                                       |
| create window                                                   | 24       | [main]                    | initial startup: true, state: 0ms, widget: 12ms, show: 11ms |
| app.isReady => window.loadUrl()                                 | 135      | [main]                    | initial startup: true                                       |
| window.loadUrl() => begin to require(workbench.desktop.main.js) | 20696    | [main->renderer]          | NewWindow                                                   |
| require(workbench.desktop.main.js)                              | 286      | [renderer]                | cached data: YES, node_modules took 0ms                     |
| wait for window config                                          | 0        | [renderer]                | -                                                           |
| init storage (global & workspace)                               | 14       | [renderer]                | -                                                           |
| init workspace service                                          | 26       | [renderer]                | -                                                           |
| register extensions & spawn extension host                      | 190      | [renderer]                | -                                                           |
| restore viewlet                                                 | 11       | [renderer]                | workbench.view.explorer                                     |
| restore panel                                                   | 0        | [renderer]                | -                                                           |
| restore & resolve visible editors                               | 70       | [renderer]                | 1: workbench.editors.gettingStartedInput                    |
| overall workbench load                                          | 375      | [renderer]                | -                                                           |
| workbench ready                                                 | 28545    | [main->renderer]          | -                                                           |
| renderer ready                                                  | 704      | [renderer]                | -                                                           |
| shared process connection ready                                 | 0        | [renderer->sharedprocess] | -                                                           |
| extensions registered                                           | 28787    | [renderer]                | -                                                           |

## Every time I start vs code
this message in the screenshot is showing every time I start vsCode (of course after taking sometime to see vs code itself).
![vscode-msg](https://user-images.githubusercontent.com/15058781/229903918-fddbb023-b003-4a71-8ef4-0fdf61a75856.png)

_Originally posted by @ObadaMoustafa in https://github.com/microsoft/vscode/issues/178962#issuecomment-1496530894_

**Comment by gjsjohnmurray** [comment]
Are you using McAfee antivirus? If so, please see https://github.com/microsoft/vscode/issues/178962
