### ISSUE TITLE
Very Slow on Windows Server 2012 R2

### ISSUE THREAD

**Issue by ChaseKnowlden** [microsoft/vscode#190337]
CPU is 100% in task manager.

Version: 1.81.1
Commit: 6c3e3dba23e8fadc360aed75ce363ba185c49794
User Agent: Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36
Embedder: github.dev

**Comment by Tyriar** [comment]
Please see https://github.com/Microsoft/vscode/wiki/Performance-Issues for creating actionable performance problem issues.
