### ISSUE TITLE
Quick sugessions not coming

### ISSUE THREAD

**Issue by Trishanu123** [microsoft/vscode#190340]
Type: <b>Bug</b>

After i copy and paste something the quick suggestions in vs code is not working in ipynb notebook.

VS Code version: Code 1.81.1 (6c3e3dba23e8fadc360aed75ce363ba185c49794, 2023-08-09T22:22:42.175Z)
OS version: Windows_NT x64 10.0.23516
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|7.75GB (0.98GB free)|
|Process Argv|--crash-reporter-id f937af3b-bd78-47c4-9d95-18c8e978db0f|
|Screen Reader|no|
|VM|50%|
</details><details><summary>Extensions (36)</summary>

Extension|Author (truncated)|Version
---|---|---
code-gnu-global|aus|0.2.2
exe-runner|bra|0.2.1
external-pdf|cha|1.2.0
phptools-vscode|DEV|1.37.13534
profiler-php-vscode|DEV|1.37.13534
code-runner|for|0.12.0
codespaces|Git|1.14.15
remotehub|Git|0.60.0
CppSnippets|har|0.0.15
cpp-pack|jew|0.0.2
python|ms-|2023.14.0
vscode-pylance|ms-|2023.8.21
jupyter|ms-|2023.7.1002162226
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.17
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-slideshow|ms-|0.1.5
cmake-tools|ms-|1.15.31
cpptools|ms-|1.16.3
cpptools-extension-pack|ms-|1.3.0
remote-explorer|ms-|0.4.1
remote-repositories|ms-|0.38.1
remote-server|ms-|1.4.0
java|red|1.21.0
cpp-compile|tch|0.0.2
open-in-browser|tec|2.0.0
pdf|tom|1.2.2
cmake|twx|0.0.17
vscode-java-debug|vsc|0.53.0
vscode-java-dependency|vsc|0.23.1
vscode-java-pack|vsc|0.25.13
vscode-java-test|vsc|0.39.1
vscode-maven|vsc|0.42.0
php-debug|xde|1.33.0
php-pack|xde|1.0.3
php-intellisense|zob|1.3.2

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
py29gd2263cf:30792227
vscaat:30438848
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
vsccc:30803844
3biah626:30602489
f6dab269:30613381
a9j8j154:30646983
showlangstatbar:30737416
a2ce3375:30757347
pythonfmttext:30731395
pythoncmv:30756943
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
gsofa:30804715
pythonnosmt12:30797651
pythonidxpt:30805730
pythonnoceb:30805159
dsvsc013:30795093
dsvsc014:30804076

```

</details>

**Comment by rebornix** [comment]
It's likely a dup of https://github.com/microsoft/pylance-release/issues/4742
