### ISSUE TITLE
[Bug] Make hover disappear after some time outside of the hover

### ISSUE THREAD

**Issue by aiday-mar** [microsoft/vscode#190394]
Currently the hover disappear as soon as the mouse leaves the content hover. Sometimes the user leaves briefly the content hover. The ask is to wait until some times (ex. 500 ms) has passed before measuring whether the mouse is within the hover or not, then make the hover disappear or not.

**Comment by ulugbekna** [comment]
This would be quite helpful in resizing the hover (because it's easy to go out of the hover when aiming for the angle to hover with a mouse). But I would think 500 ms is too much for that use case
