### ISSUE TITLE
Do not show welcome experience in no folder workspace

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#19036]
1. open command prompt `code-insiders`
2. No folder workspace is opened and there is the welcome experience

In this case we should not show the welcome experience, we are an editor the user just wanted to edit a new untitiled file, welcome experience is not needed in this case.

Another strange scenario
1. Open new window
2. An no folder workspace is opened and there is the welcome experience

We should only show the welcome experience for the folder workspace
fyi @bpasero

**Comment by chrmarti** [comment]
The first time the workbench opens is without a folder and we want to show the Welcome experience specifically there.

The current logic is to show it if the setting (and the experiment) is enabled unless there is a file (other than the untitled one) open.
