### ISSUE TITLE
Your First Extension page instructions throw errors on install

### ISSUE THREAD

**Issue by evilgeniuscreative** [microsoft/vscode#190324]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.81.1
- OS Version: MacOS Ventura 13.5

Steps to Reproduce:

1. Follow steps on https://code.visualstudio.com/api/get-started/your-first-extension
2. npm install -g yo generator-code >>> leads to various warnings and errors
3. 15 vulnerabilities (5 moderate, 10 high)
4. Cannot find the file @humanwhocodes/config-array even though it is in the npm repo at https://www.npmjs.com/package/@humanwhocodes/config-array ...  but may not be in the registry?
5. Numerous deprecated dependencies:
`npm WARN deprecated @npmcli/move-file@1.1.2: This functionality has been moved to @npmcli/fs
npm WARN deprecated readdir-scoped-modules@1.1.0: This functionality has been moved to @npmcli/fs
npm WARN deprecated debuglog@1.0.1: Package no longer supported. Contact Support at https://www.npmjs.com/support for more info.
npm WARN deprecated @npmcli/move-file@2.0.1: This functionality has been moved to @npmcli/fs
`
6. At least one other outright error other than the one mentioned at #4:
`npm ERR! code ENOLOC 
npm ERR! audit This command requires an existing lockfile.
npm ERR! audit Try creating one first with: npm i --package-lock-only
npm ERR! audit Original error: loadVirtual requires existing shrinkwrap file`
7. `yo code` has a warning: 
`npm WARN tarball tarball data for @aashutoshrathi/word-wrap@https://registry.npmjs.org/@aashutoshrathi/word-wrap/-/word-wrap-1.2.6.tgz (sha512-1Yjs2SvM8TflER/OD3cOjhWWOZb58A2t7wpE2S9XfBYTiIl+XFhQG2bjy4Pu1I+EAlCNUzRDYDdFwFYUKvXcIA==) seems to be corrupted. Trying again.`

I would hope that the documents on how to create extensions would be kept up to date and make sure that dependencies are secure and error-free.

**Comment by aeschli** [comment]
I updated the the generator-code yesterday.
Please update with `npm i -g generator-code`

I verified that (running today) there are no vulnerabilities reported.
The dependencies to npmcli are coming in through the yeoman generator framework. 



![Image](https://github.com/microsoft/vscode/assets/6461412/6b37189d-e9f0-4724-a9c0-cdb21ed6bb81)



![Image](https://github.com/microsoft/vscode/assets/6461412/7fe4f644-f99f-463d-83ce-43292179009d)
