### ISSUE TITLE
Welcome overlay does not respect if I have viewlets hidden

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#19037]
1. Hide explorer
2. Click on the welcome overview
3. Notice how all the arrows are pointing to the wrong viewlets -> very confusing

![screen shot 2017-01-23 at 16 20 23](https://cloud.githubusercontent.com/assets/1926584/22209749/edebe698-e187-11e6-842d-0e2aa9db6e0c.png)

**Comment by chrmarti** [comment]
Tracked with #18861
