### ISSUE TITLE
vscode insiders not rendering correctly on KDE/X Server

### ISSUE THREAD

**Issue by BMWestrich** [microsoft/vscode#190327]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version:
Version: 1.82.0-insider
Commit: 76985ae7814f7cb28e2df6f1025d279bb77cbec1
Date 2023-08-11T17:10:45.392Z
Electron: 25.4.0
ElectronBuildId: 22958381
Chromium: 114.0.5735.248
Node.js: 18.15.0
V8: 11.4.183.27-electron.0
- OS Version:  Linux x64 6.4.9-1-default

Steps to Reproduce:

1.  Startup from any method, command line, shortcut etc.
2. Vscode will not render correctly

Screenshot below

![grafik](https://github.com/microsoft/vscode/assets/7254721/e1ded686-7f3b-4030-b0a7-91dd1606343a)

**Comment by deepak1556** [comment]
Is stable `v1.81` rendering fine on the same setup ? Can you provide the output of `code --verbose` ?

**Comment by BMWestrich** [comment]
Let me try with the latest update

**Comment by BMWestrich** [comment]
> Is stable `v1.81` rendering fine on the same setup ? Can you provide the output of `code --verbose` ?

Yes, stable code renders ok.

Regarding the output of `code --verbose`: Does that contain any sensible information? It seems to list github auth tokens etc...

Do you want to know anything specific?

**Comment by BMWestrich** [comment]
I do see e.g.

```log
Errors:
link failed but did not provide an info log
[9415:0815/131910.112903:WARNING:angle_platform_impl.cc(48)] ProgramGL.cpp:989 (checkLinkStatus): Program link or binary loading failed with no info log.
[9415:0815/131910.113128:ERROR:shared_context_state.cc(81)] Skia shader compilation error
```

**Comment by deepak1556** [comment]
Thanks for the logs, those are definitely related to the issue. Can you try starting with `code-insiders --disable-gpu-driver-bug-workarounds` and see if the issue persists ?

**Comment by deepak1556** [comment]
Merging to https://github.com/microsoft/vscode/issues/190437, since the error logs match.

**Comment by BMWestrich** [comment]
Yeah

Version: 1.82.0-insider
Commit: ccb95fd921349023027a0df25ed291b0992b9a18
Date: 2023-08-17T05:33:22.719Z
Electron: 25.5.0
ElectronBuildId: 23084831
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
Linux x64 6.4.9-1-default

fixes the issue.
