### ISSUE TITLE
PHP else: highlight not working

### ISSUE THREAD

**Issue by petercannon** [microsoft/vscode#190333]
Type: <b>Bug</b>

Using PHP's if (): else: endif; syntax.
Expected result:
else: keyword will be highlighted with the current theme's colour
Actual result:
else: keyword is not highlighted with the current theme's colour.

Issue is not present with else {} syntax or with else on its own

VS Code version: Code 1.81.1 (6c3e3dba23e8fadc360aed75ce363ba185c49794, 2023-08-09T22:22:42.175Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7 CPU         930  @ 2.80GHz (8 x 2806)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: unavailable_off<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: unavailable_off<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.99GB (4.30GB free)|
|Process Argv|--crash-reporter-id 7a1c5235-5c4a-4acb-8ae6-7e575dcc703c|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (47)</summary>

Extension|Author (truncated)|Version
---|---|---
ACF-Snippet|ant|1.9.0
vscode-django|bat|1.10.0
wordpress-snippets|cal|1.1.1
vscode-eslint|dba|2.4.2
xslt-xpath|del|1.5.14
composer-php-vscode|DEV|1.37.13534
phptools-vscode|DEV|1.37.13534
profiler-php-vscode|DEV|1.37.13534
python-environment-manager|don|1.0.4
python-extension-pack|don|1.7.0
xml|Dot|2.5.1
EditorConfig|Edi|0.16.4
prettier-vscode|esb|10.1.0
html-snippets|gey|0.2.3
wordpress|hri|1.0.1
vscode-nuget-package-manager|jmr|1.1.6
vsc-python-indent|Kev|1.18.0
unity-code-snippets|kle|2.2.5
csharpextensions|kre|1.7.3
vscode-xslt-snippets|mar|0.1.0
vscode-docker|ms-|1.26.0
csdevkit|ms-|0.3.21
csharp|ms-|2.0.357
vscode-dotnet-runtime|ms-|1.6.0
vscodeintellicode-csharp|ms-|0.1.26
isort|ms-|2023.10.1
python|ms-|2023.14.0
vscode-pylance|ms-|2023.8.20
jupyter|ms-|2023.7.1002162226
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.17
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-slideshow|ms-|0.1.5
azure-account|ms-|0.11.5
powershell|ms-|2023.6.0
autodocstring|njp|0.6.1
laravel-blade|one|1.34.0
material-icon-theme|PKi|4.29.0
vscode-xml|red|0.26.1
html5-boilerplate|sid|1.1.1
xslt-transform|Sve|0.0.4
wordpress-snippet|tun|1.1.5
intellicode-api-usage-examples|Vis|0.2.7
vscodeintellicode|Vis|1.2.30
quokka-vscode|Wal|1.0.555
jinja|who|0.0.8
wordpress-toolbox|wor|1.3.15

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263:30335439
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
vscccc:30803845
282f8724:30602487
f6dab269:30613381
2i9eh265:30646982
showlangstatbar:30737416
vsctsb:30748421
03d35959:30757346
pythonfmttext:30731395
pythoncmvfstrcf:30756944
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
gsofb:30804716
pythonnosmt12:30797651
pythonidxptcf:30805731
pythonnoceb:30805159
dsvsc013:30795093
dsvsc014:30804076

```

</details>

**Comment by roblourens** [comment]
Please give a code example

**Comment by roblourens** [comment]
I think I see it- added a couple screenshots to an upstream issue here https://github.com/KapitanOczywisty/language-php/issues/9, comment there if you have anything to add
