### ISSUE TITLE
Pull Request from Winget-pkgs Needs to be Reviewed

### ISSUE THREAD

**Issue by CoolPlayLin** [microsoft/vscode#190392]
- I have opened a PR in microsoft/winget-pkgs#113843. This PR needs @lszomoru reviewing

Thanks.

**Comment by CoolPlayLin** [comment]
@lszomoru

**Comment by lszomoru** [comment]
Closing this issue as this work is being tracked in https://github.com/microsoft/vscode/issues/185512.
