### ISSUE TITLE
View containers with lazy contents don't get restored as active

### ISSUE THREAD

**Issue by carlz32** [microsoft/vscode#190349]
Type: <b>Bug</b>

When I move **OUTLINE** and **TIMELINE** together to the **Secondary Side Bar**, then each time I open vscode, the **Search** panel shows up by defaut in the **Activity Bar** instead of the **Explorer** panel.

Reset the layout or don't move both of them solves the problem.

Thank you.

VS Code version: Code 1.81.1 (6c3e3dba23e8fadc360aed75ce363ba185c49794, 2023-08-09T22:22:42.175Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Remote OS version: Linux x64 5.15.90.1-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-10400 CPU @ 2.90GHz (12 x 2904)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.87GB (5.56GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 5.15.90.1-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i5-10400 CPU @ 2.90GHz (12 x 2904)|
|Memory (System)|7.69GB (6.77GB free)|
|VM|0%|
</details><details><summary>Extensions (17)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|3.0.2
jupyter-keymap|ms-|1.1.2
remote-wsl|ms-|0.81.0
material-icon-theme|PKi|4.29.0
errorlens|use|3.13.0
vim|vsc|1.25.2
vscode-eslint|dba|2.4.2
gitlens|eam|14.2.1
EditorConfig|Edi|0.16.4
code-runner|for|0.12.0
copilot|Git|1.101.317
copilot-chat|Git|0.6.0
codesnap-plus|hui|1.4.1
live-server|ms-|0.4.9
vscode-fileutils|sle|3.10.3
code-spell-checker|str|2.20.5
markdown-all-in-one|yzh|3.5.1

</details>

**Comment by zljmms32** [comment]
![vscode-activitybar-layout](https://github.com/microsoft/vscode/assets/29087439/3a2c6126-2fdc-4ba9-8e73-1baba164d61d)

The screenshot here.

**Comment by sbatten** [comment]
@zljmms32 does this repro even if not using WSL?

**Comment by zljmms32** [comment]
Sorry for the delay.
After several tries, I found this problem only reproduces when using WSL,
