### ISSUE TITLE
January Endgame 

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode#19031]
## Endgame Schedule
- *January 23* Code freeze for the endgame
- *Febuary 1* Endgame done

#### Monday, January 23
- [x] Code freeze at 2am CET / 5pm PT
- [x] All test items contain sufficiently comprehensive test descriptions by 3am CET / 6pm PT
- [x] Ensure we have a green build on all platforms

#### Tuesday, January 24
- [x] Test build starts at 7am CET / 10pm PT Monday
- [x] Test plan ready by 8am CET / 11pm PT Monday
- [x] Testing

#### Wednesday, January 25
- [x] Morning issue triage
- [x] Testing, Fixing
- [x] [Verification](https://github.com/Microsoft/vscode/wiki/Issue-Tracking#verification) Since there are quite some old bugs to verify we verify by age, youngest first. The queries are:
  - [Verification needed](https://github.com/Microsoft/vscode/issues?q=is%3Aissue+-label%3Averified+is%3Aclosed+label%3Averification-needed)
  - [Issues To Verify](https://github.com/Microsoft/vscode/issues?q=is%3Aissue+label%3Abug+-label%3Averified+is%3Aclosed+-label%3Aduplicate+-label%3Ainvalid+-label%3Aas-designed+milestone%3A%22January+2017%22)

#### Thursday, January 26
- [x] Fixing last issues
- [x] Verification
- [x] Add/update shrink-wrap files for built-in extensions if needed (see [instructions](https://github.com/Microsoft/vscode/issues/8570#issuecomment-229669456))  - **endgame master**
- [x] Run [OSS tool](https://github.com/Microsoft/vscode-distro/blob/master/distro-tools/README.md) after merging shrink-wrap findings - **endgame master**
  - *The LCA review of the ThirdPartyNotices.txt files is not needed anymore*
- [x] Check new OSS usage is entered into the [OSS registry](https://ossmsft.visualstudio.com/_apps/hub/ms.vss-oss-web.hub-oss) - **endgame master**

#### Friday, January 27
- [x] [Acknowledge Pull Requests](https://github.com/Microsoft/vscode-tools/tree/master/thankyou) in release notes. - **endgame master**
- [x] Satellite modules/npm packages ready, version updated, smoke tested, [PRs acknowledged](https://github.com/Microsoft/vscode-tools/tree/master/thankyou)
  - [x] [vscode](https://github.com/Microsoft/vscode-extension-vscode) **@bpasero**
  - [x] [vscode-generator-code](https://github.com/Microsoft/vscode-generator-code) **@aeschli**
  - [x] [vsce](https://github.com/Microsoft/vsce) **@joaomoreno**
  - [x] [node debug](https://github.com/Microsoft/vscode-node-debug) **@weinand**
- [x] Translation input - **@dbaeumer**
- [x] [Smoketest](https://github.com/Microsoft/vscode/wiki/Smoke-Test)
  - [x] Windows - @dbaeumer 
  - [x] OS X - @sandy081 
  - [x] Linux - @joaomoreno
- [x] Update the [Release Notes](https://github.com/Microsoft/vscode-docs/blob/vnext/release-notes/) (including **notable fixes**) and [documentation](https://github.com/Microsoft/vscode-docs/tree/vnext/docs).
  - [x] @alexandrudima
  - [x] @weinand
  - [x] @chrmarti
  - [x] @tyriar
  - [x] @dbaeumer
  - [x] @bpasero
  - [x] @egamma
  - [x] @isidorn
  - [x] @joaomoreno
  - [x] @jrieken
  - [x] @kieferrm
  - [x] @aeschli
  - [x] @rebornix
  - [x] @ramya-rao-a
  - [x] @roblourens
  - [x] @sandy081
  - [x] @mjbvz
  - [x] @mousetraps
- [x] Freeze `insider` builds - **endgame master**
- [x] Branch code to `release/<x.y>` and release `master` - **endgame master**
- [x] Bump up the version in `package.json` - **endgame master**

#### Preparation

- [x] Polish release notes **@gregvanl**
- [x] Merge translations **@dbaeumer**
- [x] Build stable - **endgame master**
- [x] Smoketest stable, sanity check all release bits
  - [x] Windows - @jrieken 
  - [x] OS X - @isidorn 
  - [x] Linux - @aeschli 

#### Release

- [x] Tag the release: `x.y.z` - **endgame master**
- [x] Unfreeze insider channel - **endgame master**
- [x] Publish website **@gregvanl**
- [x] Release stable
- [x] Tweet about the release - **@seanmcbreen**

**Comment by chrisdias** [comment]
done!

**Comment by daviwil** [comment]
This update is really incredible, great work everyone!
