### ISSUE TITLE
Private SSH keys in a remote vscode-server instance 

### ISSUE THREAD

**Issue by 3f6a** [microsoft/vscode#190367]
I would like to access a remote server via the Remote Tunnels extension. This server is shared so I would not want to store private SSH keys indefinetely.

Rather, it would be nice if the VS Code Server instance that Tunnels creates offered a simple way for me to store private SSH keys, in a secure manner, such that those keys are only accessible by me, when I login to the Tunnel instance using my Github account.

Related: https://github.com/microsoft/vscode-remote-release/issues/8810.

**Comment by connor4312** [comment]
This is something you'd want to do by running each `code tunnel` server under a separate Linux user, with appropriate permissions. Multi-user tunnels are not something that we (currently) plan to formally support.
