### ISSUE TITLE
The add item button presents when additionalProperties is false

### ISSUE THREAD

**Issue by geniuszxy** [microsoft/vscode#190365]
Type: <b>Bug</b>

This is the property in my contributes.configuration:

```
"HelloWorld.test": {
	"type": "object",
	"patternProperties": {
		".*" : { "type": "boolean" }
	},
	"additionalProperties": false,
	"default": { "a": true }
},
```

Here is a screenshot, as you can see the add item button presents and I can use it to add new properties, but the additionalProperties=false property should prevent this from happenning.

![add item button](https://github.com/microsoft/vscode/assets/2471200/10ca8498-9eca-4282-a16e-5d247dda2ba5)

VS Code version: Code 1.81.1 (6c3e3dba23e8fadc360aed75ce363ba185c49794, 2023-08-09T22:22:42.175Z)
OS version: Windows_NT x64 10.0.19045
Modes:

**Comment by rzhao271** [comment]
I believe the patternProperties key causes the UI to continue to render that button.
The current behaviour makes sense to me, especially when both additionalProperties and patternProperties exist and patternProperties _doesn't_ have a pattern that matches on everything. Let me know what the Settings editor could do differently in general when both keys are present.
