### ISSUE TITLE
A small suggestion involving UI

### ISSUE THREAD

**Issue by BraveHL** [microsoft/vscode#190469]
A small suggestion involving the UI suggests adjusting the width of the "Open Remote Window" button in the lower left corner so that it aligns with the sidebar, which is now almost aligned and very non-typing, which is very important for OCD

<img width="960" alt="e147832714a2a610d1749fbbb16ba40c" src="https://github.com/microsoft/vscode/assets/22335503/c7ec9c16-66c5-4556-8e49-08d8dbdc1e81">

**Comment by jeffreyyjp** [comment]
![image](https://github.com/microsoft/vscode/assets/17985592/84e9a4a0-16b8-4d4e-b320-ca383ae53b2c)


Don't forget we have this situation.

**Comment by gjsjohnmurray** [comment]
@BraveHL do you use it ever / much? If not then you may like to hide it by right clicking.

**Comment by roblourens** [comment]
- It's not part of the activity bar
- It can change width
- The activity bar can hide or change sides

So I think we will leave it as is, thanks for the feedback though
