### ISSUE TITLE
Find for whole project -> All folders

### ISSUE THREAD

**Issue by soljohnston777** [Microsoft/vscode#19041]
I have seen one extension for finding in the current folder.  A global find, that searches all folders in your current project, would be extremely useful.

Thanks.

**Comment by mousetraps** [comment]
Hey @soljohnston777! Gotta admit, I'm a little confused by the request. Would this be something different than the global find that's built into VS Code?
![image](https://cloud.githubusercontent.com/assets/762848/22228448/1351cd46-e186-11e6-93fc-6ab3dd89311b.png)

**Comment by soljohnston777** [comment]
It already exists!  Great!  I didn't realize it expanded that way.

**Comment by mousetraps** [comment]
Rock on! 🚀
