### ISSUE TITLE
Inform user about workspace tsdk.

### ISSUE THREAD

**Issue by infacto** [microsoft/vscode#190416]
### Problem

Due to security restrictions, we cannot overwrite the tsdk without user consent. It's annoying, but understandable...
The problem is that this is not really visible to the user. This can causes several issues for the team members...
For example, some plugins just stop working when using the build-in version instead of the workspace TSDK version.
The dev doesn't know about this and may only notice it much later. It's annoying and time consuming. Just avoidable.

**.vscode/settings.json** (workspace)
```json
{
  "typescript.tsdk": "node_modules\\typescript\\lib",
}
```

[Docs](https://code.visualstudio.com/docs/typescript/typescript-compiling#_using-newer-typescript-versions)

### Solution

This feature reqeust or improvement is about implementing a better way to inform the user about the workspace setting and make it easier to switch the correct version. 

We could display a bold blinking modal in the center of the screen, similar to ad banners. "Click here to win." But seriously... It must be prominent visible and intuitively understandable. We could show a persistent notification until the user makes a choice. ...

What's exactly the problem with the workspace setting? Potentially everyone could set any value? A path to an NPM package with vulnerabilities or other problems? We could validate the value of `typescript.tsdk` with a allow list like "mode_modules/typescript/lib" which is the official typescript package. But ok, this does not cover to outdated versions that may have security risks... Anyway, this should be visible to the user. Setting the tsdk in the workspace settings is done for serious reasons and should be used within the whole dev team. 

It might look like the "Do you trust the authors of the files in this folder?" dialog. Something like:

> This project recommends using the workspace's TypeScript TSDK. Do you trust this project and want to allow that?

And check this on every start. It seems sometimes, the version is switched back for some reasons. I cannot reproduce. But checking that on every start is not a bad idea. And remain displayed until the user makes a decision.

![demo](https://github.com/microsoft/vscode/assets/60390085/cc4e07c6-6466-443a-abfd-ce01ab36d8ba)

We could also say, just load the tsdk setting of the workspace if the user confirmed the already existing trust-dialog.

### Info

Version: 1.81.1 (user setup)
Electron: 22.3.18
Chromium: 108.0.5359.215
Node.js: 16.17.1
OS: Windows_NT x64 10.0.19045

**Comment by mjbvz** [comment]
Try the `typescript.enablePromptUseWorkspaceTsdk` setting. It sounds like what you're looking for

**Comment by infacto** [comment]
Yes, it looks like what I was looking for. Thanks. But I would prefer this notification to have no duration so it stays open until the user makes a choice. It looks like another irrelevant notification. It's better than nothing though. However, it can still be easily overlooked. So I would either stay it open, make it more prominent or show it as a modal dialog as the trust-dialog.

**Comment by twoco** [comment]
The prompt notification disappears after seconds and is easy to miss. Why not just display it until the user makes a decision? Like the recommended extension notification.
