### ISSUE TITLE
I dont konw how to dev vscode sourcecode in the github codespace

### ISSUE THREAD

**Issue by ckmilse** [microsoft/vscode#190406]
ADD ISSUE DESCRIPTION HERE

Version: 1.81.1
Commit: 6c3e3dba23e8fadc360aed75ce363ba185c49794
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36
Embedder: codespaces

1. I tried to run vscode codeserver sourcecode in  in the github codespace,  I installed the dependency , build the output and ran `./scripts/code-server.sh --host=0.0.0.0`, just like the image shows, but I cant aceess the service
<img width="829" alt="屏幕快照 2023-08-14 下午8 35 34" src="https://github.com/microsoft/vscode/assets/10125008/7d56892e-d18e-472a-8634-7dac735e41e0">
<img width="1195" alt="屏幕快照 2023-08-14 下午8 36 48" src="https://github.com/microsoft/vscode/assets/10125008/e94bcbb8-ee09-46e8-9071-000686edcc03">
I don't know how to  access the service

<img width="893" alt="屏幕快照 2023-08-14 下午8 37 16" src="https://github.com/microsoft/vscode/assets/10125008/744cae82-202a-4804-beb3-ea19ebd390b7">

**Comment by chrmarti** [comment]
I see the port forward is private, there seem to be restrictions on when that can be used: https://docs.github.com/en/codespaces/developing-in-codespaces/forwarding-ports-in-your-codespace#sharing-a-port-1

Please also ask at https://github.com/orgs/community/discussions/categories/codespaces as this seems to be specific to Codespaces.

**Comment by ckmilse** [comment]
> https://docs.github.com/en/codespaces/developing-in-codespaces/forwarding-ports-in-your-codespace#sharing-a-port-1

thanks. it work

**Comment by chrmarti** [comment]
Closing this issue then, thanks!

**Comment by alexr00** [comment]
https://github.com/orgs/community/discussions/categories/codespaces would be the best place to ask about this.
