### ISSUE TITLE
test inserting snippet via keybinding

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#19045]
- [x] @rebornix 
- [x] @mjbvz 

re #17780

We can now insert a snippet by just  pressing a key combination. Test that the `insertSnippet` command can be configured in `keybindings.json` with argument which can be the following:

1. `snippet: foo$0bar` such that the argument itself defines the snippet
2. `name: someName` such that is references an existing snippet by name
3. `name: someName, langId: someLangId` to reference an existing snippet from a different language.

A sample would be
```json
{
  "key": "cmd+k '",
  "command": "editor.action.insertSnippet",
  "args": {
    "name": "in quotes" // name of a snippet defined by an extension or user
  }
},
```

**Comment by Raydir** [comment]
Hi all
I try to insert this into a package so the keybindings are pre-defined for my language extension.
I managed to call the snippet selector (topmenu of vsc) when a user is pressing the defined keybinding.

My problem is, that can't call a specific snippet by the defined keybinding... 

My language extensions package.json contains the following:

```
    "contributes": {
        "languages": [{
            "id": "f-script",
            "aliases": ["F-Script", "f-script"],
            "extensions": [".ff",".fs",".fss",".fx",".lb",".lbd",".lbf",".lbe",".lbi",".lbx",".config"],
            "configuration": "./language-configuration.json"
        }],
        "keybindings" : [
            {
                "key": "ctrl+oem_2",
                "command": "editor.action.insertSnippet",
                "when": "editorTextFocus",
                "args" : {
                    "name" : "SNIPPETA",
                    "langId" : "f-script"
                }
            }
        ],
        "snippets": [
            {
                "language": "f-script",
                "path": "./snippets/f-script.json"
            }
        ],
...
```
the snippet file is containing 2 snippets:
```
{
"SNIPPETA":
	{
		"prefix": "SNIPPETA",
		"body": 
		["DO SOMETHING A"],
		"description": "SNIPPETA"
	},
"SNIPPETB":
	{
		"prefix": "SNIPPET",
		"body": 
		["DO SOMETHING B"],
		"description": "SNIPPETB"
	}
}
```
why isn't it calling SNIPPETA directly?
