### ISSUE TITLE
Test: 'restart' option for 'launch' requests

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#19040]
Test for #17381:
Complexity: 2

- [x] Windows - @dbaeumer 
- [x] OS X - @joaomoreno
- [x] Linux - @alexandrudima 

For quite some time the VS Code node debugger supported a 'restart' attribute on 'attach' configurations. See https://code.visualstudio.com/docs/editor/node-debugging#_attaching-to-nodejs for details.
With this release we now support the 'restart' attribute on 'launch' configurations as well.
If this feature is enabled, VS Code will restart a debug session whenever it detects the termination of node.js.

An example for how to verify this feature uses nodemon and the following test program `app.js`:
```js
let i = 0;

setInterval(() => {
	console.log('hello:' + i++);
}, 1000);
```
In your launch config you can use Intellisense snippets to create a  'Nodemon setup' launch config.
After launching this you can edit `app.js` and VS Code should restart the debug session automatically.

Try to verify another scenario that uses 'restart' in a 'launch' configuration.

**Comment by dbaeumer** [comment]
The other scenario I verified it a node application that I killed by hand. Restarted as well.

**Comment by joaomoreno** [comment]
This is very cool!
