### ISSUE TITLE
Single nested directory rename breaks explorer UI in both Windows and WSL:Ubuntu

### ISSUE THREAD

**Issue by adeturner** [microsoft/vscode#190489]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.81.1
- OS Version: Windows 10.0.19044 Build 19044  with 5.10.16.3-microsoft-standard-WSL2 / Ubuntu

Steps to Reproduce:

1. In WSL
3. mkdir empty; cd empty; mkdir -p dir1/subdir dir2; touch dir1/subdir/file1 dir2/file2
4. code --disable-extensions .
5. in explorer, note that dir1/subdir display on the same line. 
6. Click on subdir. Try to rename via F2 or rightclick-Rename
7. Note that rename has no apparent effect (does not highlight the word for changing)
8. Now select dir2/file2. Note that it does not open in the editor
9. Nothing really works any more

Same thing occurs on the Windows side
This regression started in the last 7 days

**Comment by lramos15** [comment]
This should be fixed in the current insiders
