### ISSUE TITLE
Set default git editor to VSCode in integrated terminal

### ISSUE THREAD

**Issue by BMBurstein** [microsoft/vscode#190486]
I would like to be able to set VSCode to be the default git editor, but only when using the integrated terminal.
I develop remotely using the remote-ssh plugin. The remote machine does not have vscode (it is a headless server with no gui). I work on it using both vscode and the integrated terminal, as well as direct ssh.
When in the integrated terminal, I can open a file in vscode using `code <file>`. This command does not work in a direct ssh session. I would like to be able to set code as my default git editor (for example, for doing interactive rebases) when it is available, i.e. when using the integrated terminal.

**Comment by BMBurstein** [comment]
even if there is just some way to run a script when starting an integrated terminal could be enough for me. Something like `~/.vscode-server/bashrc`

**Comment by lszomoru** [comment]
@BMBurstein, you can do that by enabling the `git.terminalGitEditor` setting. When this setting is enabled the `GIT_EDITOR` environment variable is set in the integrated terminal.

**Comment by BMBurstein** [comment]
that works or me. Thanks
