### ISSUE TITLE
MacOS M1 VScode Github copilot chat icon no show

### ISSUE THREAD

**Issue by ck0099** [microsoft/vscode#190474]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 
- OS Version: 

Steps to Reproduce:

1. After installed "Github copilot chat" and reloaded vscode, no extension on side bar

<img width="1335" alt="Screen Shot 2023-08-15 at 2 15 46 PM" src="https://github.com/microsoft/vscode/assets/132270603/8d9d9b89-bcc8-4998-9ecb-0960facd9852">

Versions:
macoOS: 12.6.8

vscode: 

Version: 1.81.1
Commit: 6c3e3dba23e8fadc360aed75ce363ba185c49794
Date: 2023-08-09T22:40:25.698Z (5 days ago)
Electron: 22.3.18
ElectronBuildId: 22689846
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Darwin arm64 21.6.0

Copilot Chat: Both of below version do not work:
v0.7.2023081101 (Pre-Release)
v0.6.0

**Comment by connor4312** [comment]
You will want to open an issue on https://github.com/microsoft/vscode-copilot-release/issues
