### ISSUE TITLE
Test: support to launch an adapter through an extension

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#19043]
Test for #8645:
Complexity: 3

- [x] Windows - @bpasero  
- [x] Linux - @roblourens

Previously VS Code has launched a debug adapter by using the (static) attributes `program`,  `args`, `runtime` and `runtimeArgs` from the package.json of the corresponding extension.
With this milestone this information can be dynamically calculated by a command implemented in an extension.

To verify:
- check out any debug extension, e.g. vscode-node-debug
- remove the attributes `program`,  `args`, `runtime` and `runtimeArgs` from the package.json (not all are used in all extensions)
- set a new attribute `adapterExecutableCommand` to an ID of a command that is registered in the extension.
- make this command return a structure with this format:
  ```json
  command: "<executable>",
  args: [ "<argument1>", "<argument2>", ... ]
  ```
The attribute "command" must be a either an absolute path to an executable or a name of executable looked up via the PATH environment variable. The special value`node` will be mapped to VS Code's built-in node runtime without being looked up on the PATH.

Verify that VS Code shows appropriate error messages when the command is invalid.

**Comment by bpasero** [comment]
@weinand from the description I am having issues understanding how to test this. I checked out vscode-node-debug and opened package.json. There are many of these attributes mentioned, do I just remove them all? And then should I run an extension host with the debug adapter as extension and from there start a debug session? Sorry, I am clueless how to test this.

**Comment by weinand** [comment]
In vscode-node-debug the attributes to replace by extension code are only these two:

![2017-01-26_10-26-46](https://cloud.githubusercontent.com/assets/1898161/22326245/268fbc78-e3b2-11e6-992b-8e0e39c96caf.png)

Yes, run an extension host with the debug adapter as extension and from there start a debug session. VS Code should be able to launch the adapter.

In addition please see (and verify) this related issue (which I fixed last night): https://github.com/Microsoft/vscode/issues/19386

Is it really true, that vs/base/common/paths.IsAbsolute() does not handle `C:/Program Files/nodejs/node.exe`?correctly?

**Comment by bpasero** [comment]
@weinand our internal path library should be replaced by node.js if possible (see https://github.com/Microsoft/vscode/issues/18350).

**Comment by bpasero** [comment]
@weinand I was not able to test this successfully on Windows 10.

**Comment by bpasero** [comment]
This was tough to verify...
