### ISSUE TITLE
Syntax highlighter confused by class properties with optional type

### ISSUE THREAD

**Issue by kevinbarabash** [Microsoft/vscode#19048]
- VSCode Version: 1.8.1
- OS Version: Mac OS X, 10.11.5

Steps to Reproduce:
1. Write a class containing class properties, e.g.
```
class Foo {
    state = {
        bar: (null: ?Bar),
    }

    toString() {
        const bar = this.state.bar;
        console.log(`bar = ${bar}`);

        // the rest of the file is in a string
    }
}
```
<img width="387" alt="screen shot 2017-01-23 at 10 54 46 am" src="https://cloud.githubusercontent.com/assets/1044413/22211203/5462dd38-e15a-11e6-9974-b43aaf39ca36.png">

The line `const bar = this.state.bar;` is also incorrectly highlighted.

Changing `?Bar` to`Bar` fixes the highlighting.

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript-TmLanguage#410
