### ISSUE TITLE
VS Code Fails to Update

### ISSUE THREAD

**Issue by TildenWinston** [microsoft/vscode#190458]
Type: <b>Bug</b>

Accept the prompt to restart VS Code to install updates, VS Code closes, the update starts, then I get the error:

"There was an error while Opening file handle: "C:\\Users\\[Username]\\AppData\\Local\\Programs\\Microsoft VS Code Insiders\\resources\\app\\out\\bootstrap-amd.js"

Failed to create the file handle: Access is denied.

Please verify there are no Visual Studio Code processes still executing."

VS Code version: Code - Insiders 1.80.0-insider (79c4092768e41b16fd823e80c874dbfafdc08f55, 2023-06-13T05:21:23.732Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-10900 CPU @ 2.80GHz (20 x 2808)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|63.71GB (32.58GB free)|
|Process Argv|--crash-reporter-id a4f5313c-2173-4b0b-ae0d-6e6f3e322b32|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (33)</summary>

Extension|Author (truncated)|Version
---|---|---
markdown-extension-pack|bat|0.7.0
emojisense|bie|0.10.0
markdown-checkbox|bie|0.4.0
markdown-emoji|bie|0.3.0
markdown-preview-github-styles|bie|2.0.2
excel-to-markdown-table|csh|1.3.0
markdown-table-prettify|dar|3.6.0
vscode-markdownlint|Dav|0.51.0
vulnerability-extension|dev|1.2023.807004
docs-markdown|doc|1.0.2
gitlens|eam|2023.8.1205
mdmath|goe|2.7.4
gc-excelviewer|Gra|4.2.57
path-autocomplete|ion|1.24.1
markdown-shortcuts|mdi|0.12.0
csharp|ms-|2.0.357
vscode-dotnet-runtime|ms-|1.7.0
isort|ms-|2023.11.12061012
python|ms-|2023.15.12191008
vscode-pylance|ms-|2023.8.20
sarif-viewer|MS-|3.4.0
jupyter|ms-|2023.6.1101941928
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.17
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-slideshow|ms-|0.1.5
powershell|ms-|2023.9.0
vsliveshare|ms-|1.0.5877
vscode-sanddance|msr|4.1.0
markdown-preview-enhanced|shd|0.6.8
vscode-markdown-paste-image|tel|1.0.0
markdown-pdf|yza|1.4.4
markdown-all-in-one|yzh|3.5.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythontb:30258533
pythonptprofiler:30281269
vshan820:30294714
vscod805cf:30301675
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30404738
py29gd2263:30784851
vsclangdf:30492506
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30618038
a9j8j154:30646983
showlangstatbar:30737417
ecj1e332:30687743
pythonfmttext:30716741
pythoncmvfstr:30726892
fixshowwlkth:30771523
showindicator:30805243
pythongtdpath:30726887
i26e3531:30792625
gsofa:30797620
welcomedialog:30812478
pythonnosmt12:30779711
pythonidxpt:30768918
pythonnoceb:30776497
copilotsettingt:30808721
dsvsc013:30777762
dsvsc014:30777825
diffeditorv1:30786205

```

</details>

**Comment by joaomoreno** [comment]
/duplicate #47841

As a workaround, please disable Windows background updates by setting `update.enableWindowsBackgroundUpdates` to `false`.
