### ISSUE TITLE
lost title bar sometimes

### ISSUE THREAD

**Issue by HomyeeKing** [microsoft/vscode#190468]
Does this issue occur when all extensions are disabled?: Yes/No

Version: 1.81.1 (Universal)
Commit: 6c3e3dba23e8fadc360aed75ce363ba185c49794
Date: 2023-08-09T22:20:33.924Z
Electron: 22.3.18
ElectronBuildId: 22689846
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Darwin arm64 22.5.0

Steps to Reproduce:

it happens most of time after updating the vscode, the exist vscode window will close then restore after update is finished.

the restored window maybe lost title bar, I have to exit vscode then reopen the window, `Close Window`  not works

![image](https://github.com/microsoft/vscode/assets/49113249/9c8c1ec2-8529-4a64-ba76-1102b619b3a1)

![image](https://github.com/microsoft/vscode/assets/49113249/0b44ec89-f9ee-4ba6-b716-d35b99321847)

**Comment by sbatten** [comment]
@deepak1556 dupe?
