### ISSUE TITLE
asdf-vm

### ISSUE THREAD

**Issue by PHAredes** [microsoft/vscode#190481]
Type: <b>Bug</b>

Nao consigo usar o vscode junto com o asdf-vm, e o Java: Configure Classpath não funciona

VS Code version: Code 1.81.1 (6c3e3dba23e8fadc360aed75ce363ba185c49794, 2023-08-09T22:18:39.991Z)
OS version: Linux x64 6.1.44-1-MANJARO
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz (4 x 2893)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|2, 2, 2|
|Memory (System)|11.15GB (8.07GB free)|
|Process Argv|--unity-launch --crash-reporter-id e6f79f83-8d8a-41b1-8780-ec01b577c755|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|plasma|
|XDG_CURRENT_DESKTOP|KDE|
|XDG_SESSION_DESKTOP|KDE|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (35)</summary>

Extension|Author (truncated)|Version
---|---|---
rtf|ale|2.7.0
jdk-setter|And|1.0.1
ruby-on-rails-snippets|ate|0.0.1
google-translate-ext|ben|2.2.2
vscode-gemfile|bun|0.4.2
ruby-debug|cas|0.3.5
vscode-translate|chu|0.1.5
vscode-markdownlint|Dav|0.51.0
vscode-google-translate|fun|1.4.13
gc-excelviewer|Gra|4.2.57
google-translate|han|1.2.8
vscode-language-pack-pt-BR|MS-|1.81.2023080209
remote-wsl|ms-|0.81.0
fabric8-analytics|red|0.3.10
java|red|1.21.0
vscode-xml|red|0.26.1
markdown-preview-enhanced|shd|0.6.8
ruby-lsp|Sho|0.4.4
slim|sia|0.1.2
pdf|tom|1.2.2
vscode-boot-dev-pack|vmw|0.2.1
vscode-spring-boot|vmw|1.48.0
vscode-java-debug|vsc|0.53.2023081505
vscode-java-dependency|vsc|0.23.2023080400
vscode-java-pack|vsc|0.25.2023062906
vscode-java-test|vsc|0.39.1
vscode-lombok|vsc|1.1.0
vscode-maven|vsc|0.42.2023080103
vscode-spring-boot-dashboard|vsc|0.13.1
vscode-spring-initializr|vsc|0.11.2
vscode-ruby|win|0.28.0
txt-syntax|xsh|0.2.2
ooxml-viewer|yue|2.0.0
markdown-all-in-one|yzh|3.5.1
material-theme|zhu|3.16.0

(3 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
py29gd2263:30792226
vscaac:30438847
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
vsccc:30803844
2e4cg342:30602488
f6dab269:30613381
vscrpc:30673769
a9j8j154:30646983
showlangstatbar:30737416
pythonfmttext:30731395
pythoncmvfstrcf:30756944
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
gsofb:30804716
pythonnosmt12:30797651
pythonidxptcf:30805731
pythonnoceb:30805159
dsvsc013:30795093
dsvsc014:30804076
diffeditorv2:30812749

```

</details>

**Comment by mariafcknt** [comment]
Type: Bug

I can't use vscode together with asdf-vm, and Java: Configure Classpath does not work

VS Code version: Code 1.81.1 (https://github.com/microsoft/vscode/commit/6c3e3dba23e8fadc360aed75ce363ba185c49794, 2023-08-09T22:18:39.991Z)
OS version: Linux x64 6.1.44-1-MANJARO
Modes:

<details><summary>System info</summary>
<p>
<html>
<body>


Item | Value
-- | --
CPUs | Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz (4 x 2893)
GPU Status | 2d_canvas: enabledcanvas_oop_rasterization: disabled_offdirect_rendering_display_compositor: disabled_off_okgpu_compositing: enabledmultiple_raster_threads: enabled_onopengl: enabled_onrasterization: enabledraw_draw: disabled_off_okvideo_decode: enabledvideo_encode: disabled_softwarevulkan: disabled_offwebgl: enabledwebgl2: enabledwebgpu: disabled_off
Load (avg) | 2, 2, 2
Memory (System) | 11.15GB (8.07GB free)
Process Argv | --unity-launch --crash-reporter-id e6f79f83-8d8a-41b1-8780-ec01b577c755
Screen Reader | no
VM | 0%
DESKTOP_SESSION | plasma
XDG_CURRENT_DESKTOP | KDE
XDG_SESSION_DESKTOP | KDE
XDG_SESSION_TYPE | x11


</body>
</html>

</p>
</details> 

<details><summary>Extensions (35)</summary>
<p>
<html>
<body>


Extension | Author (truncated) | Version
-- | -- | --
rtf | ale | 2.7.0
jdk-setter | And | 1.0.1
ruby-on-rails-snippets | ate | 0.0.1
google-translate-ext | ben | 2.2.2
vscode-gemfile | bun | 0.4.2
ruby-debug | cas | 0.3.5
vscode-translate | chu | 0.1.5
vscode-markdownlint | Dav | 0.51.0
vscode-google-translate | fun | 1.4.13
gc-excelviewer | Gra | 4.2.57
google-translate | han | 1.2.8
vscode-language-pack-pt-BR | MS- | 1.81.2023080209
remote-wsl | ms- | 0.81.0
fabric8-analytics | red | 0.3.10
java | red | 1.21.0
vscode-xml | red | 0.26.1
markdown-preview-enhanced | shd | 0.6.8
ruby-lsp | Sho | 0.4.4
slim | sia | 0.1.2
pdf | tom | 1.2.2
vscode-boot-dev-pack | vmw | 0.2.1
vscode-spring-boot | vmw | 1.48.0
vscode-java-debug | vsc | 0.53.2023081505
vscode-java-dependency | vsc | 0.23.2023080400
vscode-java-pack | vsc | 0.25.2023062906
vscode-java-test | vsc | 0.39.1
vscode-lombok | vsc | 1.1.0
vscode-maven | vsc | 0.42.2023080103
vscode-spring-boot-dashboard | vsc | 0.13.1
vscode-spring-initializr | vsc | 0.11.2
vscode-ruby | win | 0.28.0
txt-syntax | xsh | 0.2.2
ooxml-viewer | yue | 2.0.0
markdown-all-in-one | yzh | 3.5.1
material-theme | zhu | 3.16.0


</body>
</html>
(3 theme extensions excluded)
</p>
</details> 

<details><summary>A/B Experiments</summary>
<p>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
py29gd2263:30792226
vscaac:30438847
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
vsccc:30803844
2e4cg342:30602488
f6dab269:30613381
vscrpc:30673769
a9j8j154:30646983
showlangstatbar:30737416
pythonfmttext:30731395
pythoncmvfstrcf:30756944
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
gsofb:30804716
pythonnosmt12:30797651
pythonidxptcf:30805731
pythonnoceb:30805159
dsvsc013:30795093
dsvsc014:30804076
diffeditorv2:30812749

``` 

</p>
</details>

**Comment by dbaeumer** [comment]
This sounds more like a problem with the Java extension. Can you please report the issue with them.
