### ISSUE TITLE
Reproduction

### ISSUE THREAD

**Issue by fame71** [microsoft/vscode#190418]
Type: <b>Bug</b>

*Context*
- Managed Dependencies: on
- Cloud SDK Version: Not installed
- Skaffold Version: Not installed
- minikube Version: Not installed

VS Code version: Code - Insiders 1.82.0-insider (Universal) (2d9cc42045edf3458acbddf3d645bba993f82696, 2023-08-14T05:34:57.526Z)
OS version: Darwin arm64 22.6.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|1, 2, 2|
|Memory (System)|8.00GB (0.05GB free)|
|Process Argv|--crash-reporter-id 1894c93d-69c7-4744-bca2-dbf5ebd0f8ec|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (51)</summary>

Extension|Author (truncated)|Version
---|---|---
terminal-commands|adr|1.0.5
askia-qexml-generator-extension|Ask|1.0.1
vscode-to-photoshop|bia|0.0.3
mc-net-scripting|CNC|0.1.14
logical-properties|cod|0.1.11
conda-env-activator|Ctc|0.0.1
dscodegpt|Dan|2.1.15
vscode-markdownlint|Dav|0.51.0
python-environment-manager|don|1.0.4
xml|Dot|2.5.1
gitlens|eam|14.2.1
vscode-html-css|ecm|1.13.1
codespaces|Git|1.14.15
copilot|Git|1.101.329
copilot-chat|Git|0.7.2023081401
remotehub|Git|0.60.0
vscode-github-actions|git|0.26.1
cloudcode|goo|1.22.0
vscode-docker|ms-|1.26.0
csharp|ms-|2.0.357
vscode-kubernetes-tools|ms-|1.3.13
python|ms-|2023.14.0
vscode-pylance|ms-|2023.8.20
jupyter|ms-|2023.7.1002162226
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.17
vscode-ai|ms-|0.34.0
vscode-ai-remote|ms-|0.32.0
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-slideshow|ms-|0.1.5
remote-containers|ms-|0.304.0
remote-ssh|ms-|0.102.0
remote-ssh-edit|ms-|0.86.0
atom-keybindings|ms-|3.3.0
azure-account|ms-|0.11.5
azure-repos|ms-|0.36.0
cmake-tools|ms-|1.15.31
cpptools|ms-|1.17.1
cpptools-extension-pack|ms-|1.3.0
remote-explorer|ms-|0.4.1
remote-repositories|ms-|0.38.1
remote-server|ms-|1.4.0
batch-runner|Nil|1.1.2
vscode-yaml|red|1.14.0
vscode-css-custom-properties|Toc|0.0.5
cmake|twx|0.0.17
vscode-inline-values-powershell|Tyl|0.0.7
datex-workbench|uny|0.0.6
cscs-debugger|vas|0.7.2
vim|vsc|1.25.2
vscode-glyphs|xia|0.0.2

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythontb:30258533
vsc_aacf:30263846
pythonptprofiler:30281269
vshan820:30294714
vscod805cf:30301675
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30404738
py29gd2263:30784851
vscaac:30438845
vsclangdf:30492506
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30618038
vscrp:30624060
showlangstatbar:30737417
24365598:30687740
pythonfmttext:30716741
pythoncmvfstr:30726892
fixshowwlkth:30771523
showindicator:30805243
pythongtdpath:30726887
i26e3531:30792625
gsofa:30797620
welcomedialog:30812478
pythonnosmt12:30779711
pythonidxpt:30768918
pythonnoceb:30776497
copilotsettingt:30808721
dsvsc013:30777762
dsvsc014:30777825
diffeditorv2:30786206

```

</details>

**Comment by DonJayamanne** [comment]
Thank you for filing this issue, however there isn't any information in here that is actionable.
Closing this for now, please feel free to file a new issue or update this with missing information about the issue you are running into.
