### ISSUE TITLE
Unity Support with C# Dev Kit

### ISSUE THREAD

**Issue by wlewis55** [microsoft/vscode#190449]
Type: <b>Bug</b>

I have been using the official Unity support since it was released, and I have run into an error multiple times that I cannot seem to fix. With all of the correct versions (Unity 2022.3.2f1, Unity Visual Studio Editor 2.0.20, no Unity VS Code Editor package, VSCode Unity Support 0.9.0, C# Dev Kit 0.3.21, C# 2.0.357) I continue to see a pop up that says:

```
Failed at 'command: "dotnet.exe" restore <file_path>.sln --interactive' (382ms) with error: ERROR ExitCode(2147516561)
Details
The command could not be loaded, possibly because:
  * You intended to execute a .NET application:
      The application 'restore' does not exist.
  * You intended to execute a .NET SDK command:
      No .NET SDKs were found.
```

This causes intellisence to fail, making VSCode useless for Unity development. I have verified that my .NET SDK's are installed properly.

VS Code version: Code 1.81.1 (6c3e3dba23e8fadc360aed75ce363ba185c49794, 2023-08-09T22:22:42.175Z)
OS version: Windows_NT x64 10.0.19044

**CURRENT FIX:**
[How to fix "No .NET SDKs were found." error--VSCode](https://stackoverflow.com/questions/73247933/how-to-fix-no-net-sdks-were-found-error-vscode)

Deleting everything in the `C:\Program Files (x86)\dotnet` folder and reloading the VSCode window allows for a `Completed command: "dotnet.exe" restore <file_path>.sln --interactive (15270ms)`

**Comment by roblourens** [comment]
Please file an issue on the Unity extension (or C#, or whatever seems appropriate)
