### ISSUE TITLE
[Bug] Sticky scroll sometimes shows empty lines

### ISSUE THREAD

**Issue by aiday-mar** [microsoft/vscode#190409]
This is a regression due to the work done on making sticky scroll sideways scrollable

**Comment by rzhao271** [comment]
Hi, what are some verification steps for this issue?

**Comment by aiday-mar** [comment]
Hi @rzhao271 ! Apologies for the lack of steps. So previously when you would sideways scroll, jump from file to file, this would cause the sticky widget to not have lines. It would be blank. So some verifications steps are:

1. Enable sticky scroll with `editor.stickyScroll.enabled`
1. Open several files which create sticky lines
2. scroll sideways in these files using the editor horizontal scrollbar. You may have to enable `editor.stickyScroll.scrollWithEditor`
3. Move from file to file
4. Verify that the sticky lines are rendered correctly
