### ISSUE TITLE
Editor Playground - Box Selection

### ISSUE THREAD

**Issue by Sockemboffer** [microsoft/vscode#190494]
Type: <b>Bug</b>

I'm not sure if it's a configuration issue but the box selection commands Shift+UpArrow and the other directions are only selecting one character at a time using left and right and then whole lines moving up and down.

According to this page https://code.visualstudio.com/docs/editor/codebasics in section "Column (box) selection" the behavior I was expecting seems correct for box selection. Those commands are issued using Ctrl+Shift+Alt+Down, up, left, etc. Even with those keys I was hoping there'd be a way to select words at a time with each left and right arrow but I could deal with a character at a time going left and right I suppose.

I wouldn't call this a bug (I suspect user error and or configuration) but there wasn't a sort of general documentation/confusion about instructions option.

![Code_Sz8F6FyOoy](https://github.com/microsoft/vscode/assets/12025354/661b5bcf-e777-4535-ac6a-3a79194ecf2c)

VS Code version: Code 1.81.1 (6c3e3dba23e8fadc360aed75ce363ba185c49794, 2023-08-09T22:22:42.175Z)
OS version: Windows_NT x64 10.0.22621
Modes: Restricted

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2208)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.85GB (3.75GB free)|
|Process Argv|--crash-reporter-id f6b85b30-6b58-4c0a-8c3e-480273f3ee1f|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
gitlens|eam|14.2.1
remotehub|Git|0.60.0
vscode-dotnet-runtime|ms-|1.7.0
python|ms-|2023.14.0
vscode-pylance|ms-|2023.8.20
azure-repos|ms-|0.36.0
remote-repositories|ms-|0.38.1
lua|sum|3.6.26

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscoreces:30445986
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
py29gd2263cf:30792227
vscaat:30438848
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
vsccc:30803844
282f8724:30602487
89544117:30613380
a9j8j154:30646983
showlangstatbar:30737416
03d35959:30757346
pythonfmttext:30731395
pythoncmvfstrcf:30756944
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
gsofb:30804716
pythonnosmt12:30797651
pythonidxptcf:30805731
pythonnoceb:30805159
dsvsc013:30795093
dsvsc014:30804076
diffeditorv1:30812748

```

</details>

**Comment by chrmarti** [comment]
`Ctrl+Shift+Left/RightArrow` should select words.
