### ISSUE TITLE
Indentation detection fails on .tsv/.csv files

### ISSUE THREAD

**Issue by anthonyvdotbe** [microsoft/vscode#190407]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.81.1 (6c3e3dba23e8fadc360aed75ce363ba185c49794)
- OS Version: Windows_NT x64 10.0.22621

Steps to Reproduce:

1. open `numbers.tsv`, a file with the following contents:
```
1	one	I
2	two	II
3	three	III
```

Expected: tab indentation is detected
Actual: spaces indentation is detected

**Comment by hediet** [comment]
Indentation is only the space before the first non-space character in a line.
