### ISSUE TITLE
Git stashing

### ISSUE THREAD

**Issue by felixfbecker** [Microsoft/vscode#1904]
I often need to switch branches while still having some launch.json file silightly modified etc. Currently, I now either have to clean the changes before I can switch branches or have to open a terminal instead (which breaks the workflow) and type `git stash`, `git checkout`, `git stash pop`. It would be nice if Code had buttons for stashing, either next to "Clean All" ("Stash"), or in the "..." menu. The "..." menu should have a "Pop" submenu, that expands to all listed stashs with their messages to instantly apply them. Stashing in git is great because it's nothing but a quick stack to put temporary changes while doing stuff like checking out another branch.

**Comment by choidamdam** [comment]
+1

**Comment by chriskacerguis** [comment]
:+1:

**Comment by felixfbecker** [comment]
Imo with the integrated terminal this can be easily done now without leaving VS Code.

**Comment by jahewson** [comment]
Integrating Git stash into the VSCode's Git GUI would be much appreciated.

**Comment by BenBarber** [comment]
+1

**Comment by mattcrooks** [comment]
+1

**Comment by scgm11** [comment]
+1

**Comment by sanglnv** [comment]
+1

**Comment by joaomoreno** [comment]
**FYI:** Writing +1 doesn't call out our attention. Adding a 👍 to the first post does.

**Comment by tanakh** [comment]
+1

**Comment by serjKim** [comment]
+1

**Comment by IndianOcean** [comment]
+1 for integrating it with GUI

**Comment by cleidigh** [comment]
@joaomoreno 
I've been looking at this as another possible contribution as I would like to use it as well. I see a lot of votes/comments and no volunteers. is this an item that makes sense to sign up for?

**Comment by doomleika** [comment]
+1

I would like this feature to be implemented as well.

**Comment by joaomoreno** [comment]
This is already implemented.
