### ISSUE TITLE
vscode website: footer doesn't cover bottom part of the page fully

### ISSUE THREAD

**Issue by xy69** [microsoft/vscode#190591]
On the https://code.visualstudio.com/ website, the footer height doesn't cover the bottom part fully.
Only happens on wider screens, on smaller screens, the footer doesn't leave a gap.

Preview of the issue:
![image](https://github.com/microsoft/vscode/assets/22749383/b39b998b-07f4-4d0e-925d-4531211eabed)

Element in question: `body > footer`

Suggested change:
from
```
@media (min-width: 1200px)
footer {
    height: 90px;
}
```
to
```
@media (min-width: 1200px)
footer {
    height: fit-content;
}
```

Preview of the fix:
![image](https://github.com/microsoft/vscode/assets/22749383/645783ac-a123-4d0d-ae7d-f76248a42ad2)

edit:
Happens on:
Windows 10 22H2 (OS Build 19045.3324)
Chrome 116.0.5845.111 64-bit

**Comment by daviddossett** [comment]
Here's what I see. It looks similar in terms of the padding-bottom to what you have in your fix. What OS/browser are you on where you're seeing the issue in the original picture?

<img width="606" alt="CleanShot 2023-08-21 at 09 13 12@2x" src="https://github.com/microsoft/vscode/assets/25163139/160b0d88-4d19-4add-a773-fc4cb17423eb">

**Comment by connor4312** [comment]
New website doesn't have this issue
