### ISSUE TITLE
Test User/Workspace Settings Improvements #18094

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode#19059]
Test for #18094

- [x] any OS @alexandrudima 
- [x] any OS @ramya-rao-a 

Complexity : 3

Test this by verifying following. Once verified, please mark them as verified so that they wont appear in verification list.

- [x] [Edit Action improvements](https://github.com/Microsoft/vscode/issues/17292)
- [x] [Search improvements](https://github.com/Microsoft/vscode/issues/17646)
- [x] [Settings UI improvements](https://github.com/Microsoft/vscode/issues/18132)

**Comment by ramya-rao-a** [comment]
@sandy081 The linked items do not have the "verification-needed" label or the "bug" label, so they won't be appearing in the verification list at all I believe.
