### ISSUE TITLE
Wrong highlight for  raw string

### ISSUE THREAD

**Issue by AuroraTea** [microsoft/vscode#190519]
Type: <b>Bug</b>

# Behaviour
## Expected vs. Actual

Expected
![image](https://github.com/microsoft/vscode-python/assets/43649460/6284027d-f216-4cad-9932-4d606e4040d1)

Actual: The `\` of a raw string is the `\` and not the escape character, but the hignlight still treats them as escapes.
![image](https://github.com/microsoft/vscode-python/assets/43649460/996209ca-1244-47aa-a4d3-d1fd75587958)

## Steps to reproduce:

1. use raw string

# Diagnostic data

-   Python version (& distribution if applicable, e.g. Anaconda): 3.10.9
-   Type of virtual environment used (e.g. conda, venv, virtualenv, etc.): Poetry
-   Value of the `python.languageServer` setting: Default

<details>

<summary>Output for <code>Python</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Python</code>)
</summary>

<p>

```
XXX
```

</p>
</details>

<details>

<summary>User Settings</summary>

<p>

```

languageServer: "Pylance"

```

</p>
</details>

Extension version: 2023.15.12191008
VS Code version: Code 1.80.2 (2ccd690cbff1569e4a83d7c43d45101f817401dc, 2023-07-27T20:40:28.909Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-10210U CPU @ 1.60GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.76GB (1.73GB free)|
|Process Argv|--crash-reporter-id fddc7df4-857f-48b6-a8a4-5314435f9fbe|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
py29gd2263cf:30792227
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
vscccc:30803845
282f8724:30602487
f6dab269:30613381
showlangstatbar:30737416
pythonfmttext:30731395
pythoncmvfstrcf:30756944
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
gsofb:30804716
pythonnosmt12:30797651
pythonidxptcf:30805731
pythonnoceb:30805159
dsvsc013:30795093
dsvsc014:30804076

```

</details>

**Comment by AuroraTea** [comment]
> Unfortunately this is dependent on VS Code itself. In order to make a change it will require a change upstream. If you would like to see such a change then please open an issue at https://github.com/microsoft/vscode.

OK, Thanks

**Comment by AuroraTea** [comment]
> Thanks for creating this issue! It looks like you may be using an old version of VS Code, the latest stable release is 1.81.1. Please try upgrading to the latest version and checking whether this issue remains.

Now is 1.81.1, but already

**Comment by alexr00** [comment]
I've opened https://github.com/MagicStack/MagicPython/issues/259 on the upstream repo for this.

**Comment by DG119** [comment]
I know this is closed but check this out: https://github.com/MagicStack/MagicPython/issues/114#issuecomment-349115524

r"" is fore RE, use R"" for raw string

**Comment by DG119** [comment]
> > I know this is closed but check this out: [MagicStack/MagicPython#114 (comment)](https://github.com/MagicStack/MagicPython/issues/114#issuecomment-349115524)
> > r"" is fore RE, use R"" for raw string
> 
> Thank you, I didn't even know about this until you told me. But this is not grammar for python and is not part of pep. As a specially provided feature, at least it should be turned off by default ,or use R for RE.
> 
> I've noticed a lot of debate on the MagicPython side as well, and dissatisfied with status quo.

Here's the reason. https://github.com/MagicStack/MagicPython/issues/114#issuecomment-349122131
Yeah pretty annoying to me as well, and most of the themes follow this rule.
