### ISSUE TITLE
[WelcomeUX] Interface overview in light theme is too opaque 

### ISSUE THREAD

**Issue by kieferrm** [Microsoft/vscode#19051]
- VSCode Version: Code - Insiders 1.9.0-insider (882244ea24cb0b89a9a0c6c649c8f857fb0bc408, 2017-01-23T07:04:50.102Z)
- OS Version: Darwin x64 15.6.0

See attached screenshot:

![screen shot 2017-01-23 at 7 57 18 am](https://cloud.githubusercontent.com/assets/4674940/22211420/cbe098a0-e141-11e6-802b-9a076649cb7f.png)

**Comment by chrmarti** [comment]
Reducing blur and increasing opacity of the background a bit.

**Comment by chrmarti** [comment]
Updating to:

![screen shot 2017-02-21 at 3 38 42 pm](https://cloud.githubusercontent.com/assets/9205389/23190310/fa19bbb8-f84b-11e6-95b6-736ec8c622c2.png)

![screen shot 2017-02-21 at 3 41 48 pm](https://cloud.githubusercontent.com/assets/9205389/23190381/551ab2d8-f84c-11e6-807d-c4e0035b1c16.png)
