### ISSUE TITLE
can not show ssh tag after VS code update from 1.78.2

### ISSUE THREAD

**Issue by weirb02** [microsoft/vscode#190561]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.81.1
- OS Version: win10

Steps to Reproduce:

1. install new version vscode after 1.78.2
2. set remote connection 

before vscode 1.78.2 in win 10 right click win10 taskbar show remote connect like 

![20230816-162639](https://github.com/microsoft/vscode/assets/47615748/20c6ad45-09bc-4bfd-996e-039ac9027876)

but recently I update my vscode to 1.81.1, the information for remote node disapear.

![image](https://github.com/microsoft/vscode/assets/47615748/07445d85-5a32-4cc7-b061-4bdfcd02a204)

This bug is quite inconvenience， when I have many projects with the same name in different remote nodes.

**Comment by hongwen000** [comment]
Same Issue Here

**Comment by roblourens** [comment]
Do you own this part of the label service @aeschli? Aware of any changes?
