### ISSUE TITLE
Configure the color of file paths and links in VS Code's integrated terminal

### ISSUE THREAD

**Issue by yaocunhao** [microsoft/vscode#190504]
At present, the color of the output content from the VS Code terminal is the same. I want to match the output content from the PyCharm terminal: the color of the output file path will be specially marked, how should I set it?

such as : The "/xxx/file/path" color is red 
<img width="1827" alt="image" src="https://github.com/microsoft/vscode/assets/74170863/bb706f40-afee-4af1-b2df-bad98f162c9f">

**Comment by Tyriar** [comment]
This is not possible given the way we do links since we evaluate them lazily only on mouse hover in order to improve performance. You could request the Python CLI to improve the formatting of the files
