### ISSUE TITLE
Can we move externalTerminal back to a workbench contrib?

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#190596]
https://github.com/microsoft/vscode/pull/122871 moved externalTerminal from a pure workbench contrib to live partially in platform. I wouldn't expect it to need to be in platform so we should move it back if it's unnecessary.

**Comment by meganrogge** [comment]
I just tried to do this and I'm either doing something wrong or layering rules prevent this.

**Comment by Tyriar** [comment]
@meganrogge what was the issue you hit? It looks like the `electron-main/` parts can be moved to `node/`

**Comment by meganrogge** [comment]
Cannot import from `node` in `app.ts`

![Screenshot 2023-09-29 at 3 35 22 PM](https://github.com/microsoft/vscode/assets/29464607/8f4a8e78-d186-4f6c-a7d8-9cce885c61b2)

**Comment by Tyriar** [comment]
You're right, we can't actually do it. It's already basically as good as we can get it in platform since that needs to be instantiated in app.ts now, my bad🤦.
