### ISSUE TITLE
can't use Ctrl+. or Ctrl+; as a keyboard shortcut

### ISSUE THREAD

**Issue by phord** [microsoft/vscode#190539]
Does this issue occur when all extensions are disabled?: Yes

```
Version: 1.81.1
Commit: 6c3e3dba23e8fadc360aed75ce363ba185c49794
Date: 2023-08-09T22:18:39.991Z
Electron: 22.3.18
ElectronBuildId: 22689846
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
```

Steps to Reproduce:

1. Open Keyboard Shortcuts
2. Change the Keybinding for "Show All Commands" by double-clicking it
3. Press `Ctrl + .` to set the keybinding
4. Notice that the display shows "Ctrl + Unknown"
![image](https://github.com/microsoft/vscode/assets/123908/9b3d3049-a7af-4d46-bf37-d7840b798a7d)

5. Press `Enter` to save it
6. Notice that the Keybindings.json shows "Ctrl + Unknown"

        {
                "key": "ctrl+unknown",
                "command": "workbench.action.showCommands"
        },

7. Change the Keybindings.json to read "Ctrl + ." and save it
8. Notice that `Ctrl + .` does not perform the bound action

Note: The same problem occurs for `Ctrl+;`.  I could not find any other keys that have this behavior.

**Comment by gjsjohnmurray** [comment]
Please use the advice at https://github.com/microsoft/vscode/wiki/Keybinding-Issues to investigate and add Information here.

**Comment by phord** [comment]
Dup of #142583
