### ISSUE TITLE
[themes] follow `window.autoDetectColorScheme` when switching profiles

### ISSUE THREAD

**Issue by Frozen-hc** [microsoft/vscode#190548]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.81.1
- OS Version: windows11 23H2 22631.2191

Steps to Reproduce:

1. Switching to the Default profile 
2. Switching the Windows to dark theme
3.  Switching to the other profile, but the VS Code remains the light theme

**Comment by aeschli** [comment]
Do you have the settings `window.autoDetectColorScheme` set to true?

**Comment by Frozen-hc** [comment]
> Do you have the settings `window.autoDetectColorScheme` set to true?

Yes, I've set it to true and also specified the workbench.preferredLightColorTheme and workbench.preferredDarkColorTheme settings.
As far as I know, VS Code achieves the effect of changing the theme by changing the workbench.colorTheme setting in the settings.json, and switching the light/dark theme of Windows only changes the workbench.colorTheme of the currently used profile, so when I then switch to other So when I switch to another profile, the theme display error occurs.
