### ISSUE TITLE
Chat view empty after restart

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#190581]
* I have the chat view dragged into the alternative side bar into its own view
* I reload
* 🐛 the view is empty (despite the extension being active and running)

Switching the view back and forth, e.g from outline back to chat renders the view. It seems some view-activation/restoration is missing here

<img width="1578" alt="Screenshot 2023-08-16 at 13 58 01" src="https://github.com/microsoft/vscode/assets/1794099/fcd0330d-3da9-448a-beb8-0fbe8e3a3aaf">

**Comment by roblourens** [comment]
Whoa

**Comment by roblourens** [comment]
I can't repro in OSS. Any suggestions @sbatten?

**Comment by roblourens** [comment]
It happens when there is also another view in the secondary sidebar, so I can repro in OSS with the Outline view also in the secondary sidebar

**Comment by sbatten** [comment]
duplicate of https://github.com/microsoft/vscode/issues/185179
