### ISSUE TITLE
Pressing on "View as a scrollable element" does not work for Notebooks

### ISSUE THREAD

**Issue by gavriil-deshaw** [microsoft/vscode#190599]
Does this issue occur when all extensions are disabled?: Yes

- Version: 1.81.0 (system setup)
- Commit: 6445d93c81ebe42c4cbd7a60712e0b17d9463e97
- Date: 2023-08-02T12:37:13.485Z
- Electron: 22.3.18
- ElectronBuildId: 22689846
- Chromium: 108.0.5359.215
- Node.js: 16.17.1
- V8: 10.8.168.25-electron.0
- OS: Windows_NT x64 10.0.19045

Steps to Reproduce:

1. Create an .ipynb notebook
2. Write and execute the following code:
```python
for i in range(5005):
    print(i)
```
3. The following message is given:
![image](https://github.com/microsoft/vscode/assets/142399377/35499fa3-cbe0-45fb-be8b-171dc5d58e70)
```(Output is truncated. View as a [scrollable element](command:cellOutput.enableScrolling?0924c3c6-2804-4618-8adc-8088f42b65b2) or open in a [text editor](command:workbench.action.openLargeOutput?0924c3c6-2804-4618-8adc-8088f42b65b2). Adjust cell output [settings](command:workbench.action.openSettings?%5B%22%40tag%3AnotebookOutputLayout%22%5D)...)```
4. Press on the "scrollable element" part and nothing happens

Notes:
- I suspect this https://github.com/microsoft/vscode/pull/183608 might have something to do with it
- Enabling scrollable output by default (`Notebook › Output: Scrolling`) works
- When tested on a previous version of VSCode (1.79.2) the issue didn't exist

**Comment by AmevinLS** [comment]
Having the same issue after updating to VSCode version 1.81.1

**Comment by jnns** [comment]
Duplicate of https://github.com/microsoft/vscode/issues/189699

**Comment by gavriil-deshaw** [comment]
Ah, thanks for spotting that. Closing this issue then.
