### ISSUE TITLE
Allow to change command prompt via setting

### ISSUE THREAD

**Issue by felixfbecker** [Microsoft/vscode#1905]
VS Code has an option to open a command prompt in a directory by right-clicking, but this is always `cmd.exe` on Windows. It would be nice if we could change this to `powershell.exe` through a setting.

**Comment by felixfbecker** [comment]
I would consider this a a feature request, not a bug ;)

**Comment by joaomoreno** [comment]
Absolutely. :+1:

**Comment by felixfbecker** [comment]
I think this is implemented already :)
