### ISSUE TITLE
Settings header links differ from panel header links

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#19053]
- VSCode Version: Code - Insiders 1.9.0-insider (882244ea24cb0b89a9a0c6c649c8f857fb0bc408, 2017-01-23T07:12:16.134Z)
- OS Version: Windows_NT ia32 10.0.14986
- Extensions:

|Extension|Author|Version|
|---|---|---|
|vscode-svgviewer|cssho|1.3.0|
|EditorConfig|EditorConfig|0.3.4|
|git-project-manager|felipecaputo|1.0.1|
|md-navigate|jrieken|0.0.1|
|vscode-scss|mrmlnc|0.6.0|
|seti-icons|qinjia|0.1.3|
|lorem-ipsum|Tyriar|1.0.0|
|terminal-tabs|Tyriar|0.1.1|
|theme-glacier|Tyriar|0.0.10|

---

Inconsistencies:

- Panel headers have title attributes showing name and keybinding
- Settings text is larger than panel text (despite being lower in the hierarchy)
- Panel has no mousedown feedback
- Active item underline differs
- Inactive item text color differs

**Panel**

Hover debug console:

![image](https://cloud.githubusercontent.com/assets/2193314/22212268/dd510b44-e144-11e6-9195-0dcab5cc4564.png)

**Settings**

![image](https://cloud.githubusercontent.com/assets/2193314/22212294/f7980ae8-e144-11e6-9639-328ee4a63301.png)

Hover workspace settings:

![image](https://cloud.githubusercontent.com/assets/2193314/22212273/e5e59e64-e144-11e6-8a49-de622ebc56a4.png)

Mouse down workspace settings:

![image](https://cloud.githubusercontent.com/assets/2193314/22212307/09c43bf6-e145-11e6-9174-b467531ab5f1.png)

User settings focused without mouse over:

![image](https://cloud.githubusercontent.com/assets/2193314/22212388/5f6d1afa-e145-11e6-9ace-3c79a6a0869b.png)

**Comment by bpasero** [comment]
I think @sandy081 just fixed that?

**Comment by sandy081** [comment]
Duplicates #19022

**Comment by Tyriar** [comment]
@sandy081 thanks for fixing, https://github.com/Microsoft/vscode/issues/19022 appears to be the wrong issue though.

**Comment by sandy081** [comment]
@Tyriar Thanks for mentioning. Corrected it.
