### ISSUE TITLE
Starting a debug session always switches to the problems tab.

### ISSUE THREAD

**Issue by MartinNikolovMarinov** [microsoft/vscode#190572]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.81.1
- OS Version: Ubuntu 22.04.3 LTS x86_64 

## More info for the VSCode version:
  Version: 1.81.1
  Commit: 6c3e3dba23e8fadc360aed75ce363ba185c49794
  Date: 2023-08-09T22:18:39.991Z
  Electron: 22.3.18
  ElectronBuildId: 22689846
  Chromium: 108.0.5359.215
  Node.js: 16.17.1
  V8: 10.8.168.25-electron.0
  OS: Linux x64 6.2.0-26-generic

## Problem:

When launching a debugging session, and a build task fails, the editor focus is switched to the Problems tab ignoring options like "revealProblems: never".

In cases where the build process depends on custom sequence of tasks this is incredibly annoying, because the problem tab can't tell you what the actual problem is.

## Suggestion 

This does not happen when simply running the task specifically. Adding an option to disable this in the `launch.json` might be reasonable here. I assume, whatever is handling `launch.json` can't tell which tasks have this option and which don't, so providing an option to disable it all together might* be a solution.

## Steps to Reproduce:

The example is a bit contrived but it demonstrates the problem.

1. Create a `task.json` like the following:

```json
{
  "tasks": [
    {
      "type": "shell",
      "label": "Build Project",
      "command": "/usr/bin/make", // can be any program that returns an error code (I think*)
      "presentation": {
        "revealProblems": "never",
        "reveal": "never",
        
        // The rest should not matter, but this is what I set:
        "echo": true,
        "focus": true,
        "panel": "shared", // Any option here changes nothing
        "showReuseMessage": false,
        "clear": true,
        "close": false
      },
      "args": [
        "-j", 
        "-C",
        "${workspaceFolder}/build",
      ],
      "options": {
        "cwd": "${workspaceFolder}"
      },
      "group": {
        "kind": "build",
        "isDefault": true
      }
    }
  ],
  "version": "2.0.0"
}
```
2.  Create `launch.json` like the following:

```json
{
  "name": "Run LLDB Debugger",
  "type": "lldb", // same with cppdbg
  "request": "launch",
  "program": "${workspaceFolder}/build/some_executable",
  "internalConsoleOptions":"neverOpen",
  "preLaunchTask": "Build Project"
}
```

3. Start debugging session
4. If there is a build error focus switches to problems tab.

**Comment by roblourens** [comment]
You can customize the behavior with this setting, does that help?

<img width="514" alt="image" src="https://github.com/microsoft/vscode/assets/323878/2ee760e9-3ffe-45d9-9307-ff60c6acfd31">

**Comment by MartinNikolovMarinov** [comment]
Setting `Debug: On Task Errors` to abort is reasonably close to a solution for this.
