### ISSUE TITLE
Test improved multicursor actions experience

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#19058]
- [x] any OS @egamma 
- [x] any OS @kieferrm 

Complexity: 2

Test item for #18973

The following actions:

| Label | Default Keybinding |
|---|---|
| Add Selection To Next Find Match | <kbd>Ctrl</kbd>+<kbd>D</kbd><br/><kbd>Cmd</kbd>+<kbd>D</kbd> (Mac) |
| Move Last Selection To Next Find Match | <kbd>Ctrl</kbd>+<kbd>K</kbd>,<kbd>Ctrl</kbd>+<kbd>D</kbd><br/><kbd>Cmd</kbd>+<kbd>K</kbd>,<kbd>Cmd</kbd>+<kbd>D</kbd> (Mac) | 
| Add Selection To Previous Find Match | - | 
| Move Last Selection To Previous Find Match | - |
| Select All Occurrences of Find Match | <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>L</kbd><br/><kbd>Cmd</kbd>+<kbd>Shift</kbd>+<kbd>L</kbd> (Mac) |
| Change All Occurrences | <kbd>Ctrl</kbd>+<kbd>F2</kbd><br/><kbd>Cmd</kbd>+<kbd>F2</kbd> (Mac) |

**change their behaviour based on the find input state even if the find widget is hidden**:
![image](https://cloud.githubusercontent.com/assets/5047891/22174179/50a696ae-dfd8-11e6-8a54-4042ad1b1e05.png)

Moreover, the two toggles can be changed via keybindings **even when the find widget is hidden**:

| Option | Default keybinding |
|---|---|
| `Match Case` | <kbd>Alt</kbd>+<kbd>C</kbd><br/><kbd>Cmd</kbd>+<kbd>Alt</kbd>+<kbd>C</kbd> (Mac) |
| `Match Whole Word` | <kbd>Alt</kbd>+<kbd>W</kbd><br/><kbd>Cmd</kbd>+<kbd>Alt</kbd>+<kbd>W</kbd> (Mac) |

---

Please test that:

### The find widget options appear by themselves briefly when executing these actions (including toggling via keyboard) 
 * they show up by themselves
 * you can interact with the mouse with them
 * you can hover and learn about the keybindings
 * they track the exact same state as the find widget options.

**Comment by kieferrm** [comment]
Tested on macOS.

**Comment by egamma** [comment]
Tested on Windows
