### ISSUE TITLE
Allow extensions to define settings order in Preferences

### ISSUE THREAD

**Issue by reddy1508** [microsoft/vscode#190666]
Currently, extension settings show alphabetically in Preferences even if ordered differently in package.json.
Request ability for extensions to define/configure the order of their settings in the Preferences UI.
This would allow better organization and priority of settings for complex extensions.
Extension manifest could specify settings order, e.g. new "settingsOrder" attribute in package.json.

**Comment by reddy1508** [comment]
Yes the order key works 
In preference settings if we go there and search the extension it showing correct order but when we go directly to extension settings the order became alphabetical order

**Comment by reddy1508** [comment]
![Screenshot (99)](https://github.com/microsoft/vscode/assets/116274586/0cfeb02f-3490-4534-986e-fc98f797e65e)
![Screenshot (100)](https://github.com/microsoft/vscode/assets/116274586/27b953f3-e6bb-4d7f-90e9-4f79ab3fdd7f)
the above screenshots are showing for extension settings

![Screenshot (98)](https://github.com/microsoft/vscode/assets/116274586/1b913829-5c62-4c50-af43-76fc2e4cdf99)
![Screenshot (101)](https://github.com/microsoft/vscode/assets/116274586/1ea4d307-2ee1-4aa4-9a5c-aad294c77a39)
the above screenshot's are preferences settings and tis what my intended behavior is

**Comment by reddy1508** [comment]
Here the the below screenshots 
These Screenshots below show that the Extension Settings this how user will access the 
![Screenshot (99)](https://github.com/microsoft/vscode/assets/116274586/f3b99846-f8fc-4e5b-85a5-88d3a947b886)
![Screenshot (100)](https://github.com/microsoft/vscode/assets/116274586/5bc773ee-d618-449d-b1f4-3672b2b63e17)

the below screen shot shows that the Preferences settings this is what the intended behavior we are expecting
![Screenshot (102)](https://github.com/microsoft/vscode/assets/116274586/9e4f5f8e-e8ef-4dca-afee-fb788fce2625)

other than order key word is there any Programmatical access to get the expected behavior for configurations properties please provide

**Comment by rzhao271** [comment]
Closing in favour of #187959
