### ISSUE TITLE
Improvement of serverInstallPath

### ISSUE THREAD

**Issue by skwde** [microsoft/vscode#190633]
Related / FollowUp to <https://github.com/microsoft/vscode-remote-release/issues/472>.

To specify a different install path for `~/.vscode-server` we can use

```json
"remote.SSH.serverInstallPath": {
    "<host1>": "<install path 1>",
    "<host2>": "<install path 2>",
    <...>
}
```

It would be nice to also have a general setting which only changes the `~/` part of the install location.
This avoids the need to configure the same install path for many different servers.

Note, <https://github.com/microsoft/vscode-remote-release/issues/472#issuecomment-564809468> suggests to use symlinks to the location, but this still requires modification of each machine separately.

**Comment by roblourens** [comment]
I don't quite follow, can you give an example?
