### ISSUE TITLE
No update

### ISSUE THREAD

**Issue by RodrigoAbrao** [microsoft/vscode#190670]
Type: <b>Bug</b>

Meu VSCODE não está atualizando, não tem botão de solicitar o update. Sem o update não posso usar o copilot.

VS Code version: Code 1.70.1 (6d9b74a70ca9c7733b29f0456fd8195364076dda, 2022-08-10T06:08:33.642Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 1600X Six-Core Processor            (12 x 3593)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.92GB (7.64GB free)|
|Process Argv|--crash-reporter-id 6a5d4a27-9311-47d2-8a06-cee998e11911|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
code-runner|for|0.12.0
copilot|Git|1.84.51
kite|kit|0.147.0
vscode-docker|ms-|1.23.3
vscode-language-pack-pt-BR|MS-|1.70.8170916
python|ms-|2022.16.1
vscode-pylance|ms-|2023.1.10
jupyter|ms-|2022.7.1102252217
jupyter-keymap|ms-|1.1.0
jupyter-renderers|ms-|1.0.9
quicktype|qui|12.0.46
sonarlint-vscode|Son|3.13.0
tabnine-vscode|Tab|3.7.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263:30335439
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
py29gd2263:30792226
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
2e4cg342:30602488
f6dab269:30613381
showlangstatbar:30737416
pythonfmttext:30731395
pythoncmv:30756943
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
gsofa:30804715
pythonnosmt12:30797651
pythonidxptcf:30805731
pythonnoceb:30805159
dsvsc013:30795093
dsvsc014:30804076
diffeditorv2:30812749

```

</details>

**Comment by RodrigoAbrao** [comment]
This is the problem, I can't update. There is no button to update or alert to update.

**Comment by gjsjohnmurray** [comment]
I guess you are using "Run as Administrator" to start VS Code. Please start it normally instead.

**Comment by Ahmedraza-fyntune** [comment]
just download the latest version of vscode  dont make things complex for your self

**Comment by RodrigoAbrao** [comment]
> just download the latest version of vscode from vebsite dont make things complex for your self

Why do you need to be rude? I'm just reporting a issue. I should be able to just update it. Don't know about you, but I already have many configs in my vscode and I don't want to risk it. Anyway, thanks for the obvious solution.

**Comment by RodrigoAbrao** [comment]
> I guess you are using "Run as Administrator" to start VS Code. Please start it normally instead.

That's what happened! Thanks for the comment!

**Comment by Ahmedraza-fyntune** [comment]
sorry bro if i sound like rude  i am also here to provide the solution if u have configs you just need to export then like keypappings and user generated snippets and settings .json and if u need all of your extensions also just copy the .extension folder from user/.vscode folder
