### ISSUE TITLE
Cmd+c for copying to clipboard doesn't work when word is selected

### ISSUE THREAD

**Issue by FelixNeilc** [Microsoft/vscode#1906]
OS: mac
SW: Version 0.10.6 (0.10.6)
1. select a word
2. cmd+c
3. The Command Palette  pops up.

**Comment by alexandrudima** [comment]
@FelixNeilc Are you sure you don't have any custom keybindings in your `keybindings.json` user file? Did you install extensions that perhaps bind `cmd+c` to show the command palette?

@joaomoreno @jrieken @bpasero Is copying a word on the mac really not working?

**Comment by bpasero** [comment]
Works for me.

**Comment by jrieken** [comment]
Works for me

**Comment by alexandrudima** [comment]
Thanks for checking! :+1:

**Comment by joaomoreno** [comment]
Me 2.

**Comment by alexandrudima** [comment]
I think this is a dup of #1850
