### ISSUE TITLE
Variable Paths for Settings Sync between Computers

### ISSUE THREAD

**Issue by MrSamples** [microsoft/vscode#190683]
Add the option to specify computer-specific paths in the synced settings.json file.

ex: I hook/integrate neovim into VS Code using [this extension](https://marketplace.visualstudio.com/items?itemName=asvetliakov.vscode-neovim). The extension requires that you specify the path to both the executable (`C:\\Users\\*NAME*\\AppData\\Local\\Programs\\Neovim\\bin\\nvim.exe`) and the config file (`C:\\Users\\*NAME*\\AppData\\Local\\nvim\\init.vim`). The *NAME* on my work computer and *NAME* on my desktop at home are different, meaning that I have to change the path every time I open VS Code on a machine different from the one I most recently used it on because the settings.json file syncs every time I edit it.

Having a feature to lock certain lines from changing on one's system or somehow marking that a path is a path and that it should not sync like the rest of the file would be awesome.

**Comment by gjsjohnmurray** [comment]
The gearwheel alongside a setting in Settings Editor should offer you the option to exclude it from Settings Sync.

**Comment by MrSamples** [comment]
> The gearwheel alongside a setting in Settings Editor should offer you the option to exclude it from Settings Sync.

Thank you for the explanation. As you can see, I almost always use the JSON files for editing settings (settings.json, keybindings.json, etc.) and thus am not too familiar with the more abstract settings menu.

It would still be cool to have this feature be accessible while editing the JSON file directly (through a flag or a gear button to the left of the line numbers or through some other way) but this has solved my issue. Thank you!
