### ISSUE TITLE
Github CodeSpaces does not open 

### ISSUE THREAD

**Issue by erickrod54** [microsoft/vscode#190644]
Github CodeSpaces does not open, in my desktop stucks in retrieving the data from the repository, and in my ipad pro stucks in the window of settingg up the workspace it didn't appear the vscode editor

Ipad Pro 12.9
![IMG_0039](https://github.com/microsoft/vscode/assets/2977461/036cf7cb-8b7e-4016-b023-cd6d94603b9a)

Desktop
![desktop](https://github.com/microsoft/vscode/assets/2977461/2ba8cbac-b8ca-4514-8f79-874fe6c78520)

Version: 1.81.1
Commit: 6c3e3dba23e8fadc360aed75ce363ba185c49794
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36
Embedder: codespaces

**Comment by erickrod54** [comment]
Hello guys ! I solved, this issue is related with a memory consumption… it is not caused by vscode, the issue happen when the memory RAM it is consumed around 4GB.. in both factors 8GB and 16GB… if get to that memory consumption won’t open, even if you start to delete apps to release the memory that won’t work either, in my case I had to lose all my info by applying a factory reset and then release the RAM consumption

![IMG_0001](https://github.com/microsoft/vscode/assets/2977461/aa3a01a1-fd02-475f-8eb9-45c66633c644)


And now works nicely, I tested already under low connection conditions and works good

Tested on 

iPad Pro 12.9-inch 2021

**Comment by lszomoru** [comment]
This should sill be looked at. @alexdima could you help with routing this issue? Thanks!

**Comment by alexdima** [comment]
Please start a thread at http://gh.io/ghcs-feedback

**Comment by erickrod54** [comment]
what extension cause the error @alexdima ?
