### ISSUE TITLE
Doing basic stuff is delayed and feels so unresponsive

### ISSUE THREAD

**Issue by alifkaputra** [microsoft/vscode#190654]
Type: <b>Performance Issue</b>

Typing, scrolling, and highlighting text feels so unresponsive. Even after fresh install and turning off every extensions. And only opening 1 css file with 400 lines of code.

But this behavior doesn't occure in Visual Studio Code web (https://vscode.dev/). It also running fine in Windows Safe Mode. So I guess it is Windows problem.
I already did everything I could to find the progblem within Windows, from turning off every startup apps, rollback some driver version that I though might be the problem like Nvidia, also turning off Hyper-V. I also try different version of VSCode, x64 or x86, even insider version. But that doesn't solve the problems.

I hope you guys can help me by seeing all data I could provide through this Report.

Thank you.

VS Code version: Code 1.79.2 (695af097c7bd098fbf017ce3ac85e09bbc5dda06, 2023-06-14T08:57:04.379Z)
OS version: Windows_NT x64 10.0.22621
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 5600H with Radeon Graphics          (12 x 3294)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.41GB (5.56GB free)|
|Process Argv|--crash-reporter-id 7ab56e34-aadc-4e6f-ba3d-451503688977 --crash-reporter-id 7ab56e34-aadc-4e6f-ba3d-451503688977|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    1	   300	 27380	code main
    0	    82	  3640	   crashpad-handler
    0	    91	  3956	fileWatcher [2]
    0	   149	  8404	extensionHost [2]
    0	   104	  4296	     electron-nodejs ("C:\Users\Alifka\AppData\Local\Programs\Microsoft VS Code\Code.exe" --ms-enable-electron-run-as-node "c:\Users\Alifka\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\json-language-features\server\dist\node\jsonServerMain" --node-ipc --clientProcessId=8404)
    0	    91	 28956	     electron-nodejs ("C:\Users\Alifka\AppData\Local\Programs\Microsoft VS Code\Code.exe" --ms-enable-electron-run-as-node "c:\Users\Alifka\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\css-language-features\server\dist\node\cssServerMain" --node-ipc --clientProcessId=8404)
    0	    86	 10056	   utility-network-service
    0	    90	 11436	fileWatcher [1]
    0	    96	 14772	ptyHost
    0	     7	 14828	     console-window-host (Windows internal process)
    0	    81	 18080	     C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe -noexit -command "try { . \"c:\Users\Alifka\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\contrib\terminal\browser\media\shellIntegration.ps1\" } catch {}"
    0	   158	 17064	extensionHost [1]
    0	    92	 12400	     electron-nodejs ("C:\Users\Alifka\AppData\Local\Programs\Microsoft VS Code\Code.exe" --ms-enable-electron-run-as-node "c:\Users\Alifka\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\css-language-features\server\dist\node\cssServerMain" --node-ipc --clientProcessId=17064)
    0	   123	 19792	     electron-nodejs ("C:\Users\Alifka\AppData\Local\Programs\Microsoft VS Code\Code.exe" --ms-enable-electron-run-as-node "c:\Users\Alifka\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\json-language-features\server\dist\node\jsonServerMain" --node-ipc --clientProcessId=17064)
    0	   340	 18780	   gpu-process
    0	   100	 21140	window [3] (Issue Reporter)
    0	   280	 23004	   window
    0	    96	 26256	   utility-process
    0	   112	 27816	shared-process
    0	     7	 28152	   "C:\Program Files\Google\Drive File Stream\79.0.2.0\crashpad_handler.exe" --database=C:\Users\Alifka\AppData\Local\Google\DriveFS\Crashpad --url=https://clients2.google.com/cr/report --annotation=application=Code.exe --annotation=prod=DriveFS --annotation=ver=79.0.2.0 --initial-client-data=0x1bcc,0x1bb8,0x1bb4,0x1bac,0x1ba4,0x7ff85709eff0,0x7ff85709f000,0x7ff85709f010
    0	    12	 28720	   C:\Users\Alifka\AppData\Local\Temp\vscode-stable-user-x64\CodeSetup-stable-6c3e3dba23e8fadc360aed75ce363ba185c49794.exe /verysilent /log /update="C:\Users\Alifka\AppData\Local\Temp\vscode-stable-user-x64\CodeSetup-stable-6c3e3dba23e8fadc360aed75ce363ba185c49794.flag" /nocloseapplications /mergetasks=runcode,!desktopicon,!quicklaunchicon
    0	    42	 27552	     "C:\Users\Alifka\AppData\Local\Temp\is-OQ344.tmp\CodeSetup-stable-6c3e3dba23e8fadc360aed75ce363ba185c49794.tmp" /SL5="$30C3A,92319961,828416,C:\Users\Alifka\AppData\Local\Temp\vscode-stable-user-x64\CodeSetup-stable-6c3e3dba23e8fadc360aed75ce363ba185c49794.exe" /verysilent /log /update="C:\Users\Alifka\AppData\Local\Temp\vscode-stable-user-x64\CodeSetup-stable-6c3e3dba23e8fadc360aed75ce363ba185c49794.flag" /nocloseapplications /mergetasks=runcode,!desktopicon,!quicklaunchicon
    0	   212	 28888	window [1] (global.css - Visual Studio Code)
    0	   242	 29520	window [2] (global.css - Visual Studio Code)
```

</details>
<details>
<summary>Workspace Info</summary>

```
;
```

</details>
Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
vscaac:30438847
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
vsccc:30803844
282f8724:30602487
89544117:30613380
vscrp:30673768
showlangstatbar:30737416
a2ce3375:30757347
pythonfmttext:30731395
pythoncmv:30756943
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
gsofa:30804715
pythonnosmt12:30797651
pythonidxptcf:30805731
pythonnoceb:30805159
dsvsc013:30795093
dsvsc014:30804076
diffeditorv1:30812748

```

</details>

[Profile-20230817T163526.txt](https://github.com/microsoft/vscode/files/12367701/Profile-20230817T163526.txt)

**Comment by Ahmedraza-fyntune** [comment]
have u tried the clean installation of vscode 
or have u tried the other version of vs code 
try visual code insider and then please let me know

**Comment by Ahmedraza-fyntune** [comment]
dont do system changes like rollback and driver changes for small issues you may break your system

**Comment by Ahmedraza-fyntune** [comment]
Some extensions can slow down VSCode. Disable or uninstall any extensions that you're not actively using

**Comment by Ahmedraza-fyntune** [comment]
r u running the vscode as administrator
if yes please dont use as normal user

**Comment by alifkaputra** [comment]
> dont do system changes like rollback and driver changes for small issues you may break your system

Thank you. But don't worry I do backup beforehand.

<br>

> Some extensions can slow down VSCode. Disable or uninstall any extensions that you're not actively using

I tried fresh install VScode with no extensions, doesn't solve the problem.

<br>

> r u running the vscode as administrator if yes please dont use as normal user

I'm not.

**Comment by deepak1556** [comment]
Thanks for the profile, at high level most of the frame drops are associated with long animation tasks rather than impacted by scripting tasks. Can you please test the behavior with our insiders version http://code.visualstudio.com/insiders that comes with an updated version of the runtime.

**Comment by alifkaputra** [comment]
Thank you @deepak1556 but I already solve the problem (after tinkering EVERY SETTINGS AVAILABLE ON MY WINDOWS ╚(•⌂•)╝)

I goto Nvidia control panel > Manage 3D settings > "Program Settings" tab. I select Visual Studio Code and change the "2. Select the preffered graphics processor for this program" to "Integrated Graphics" from "High-performance NVIDIA processor".
Si I guess the problem is cause by Nvidia(?)

Thank you all. I'll close this issue then.

**Comment by alifkaputra** [comment]
I actually found the real culprit here.
It's this setting in Nvidia control panel > Manage 3D settings called "Background Application Max Frame Rate". I set it to 20 FPS to save power. But apparently Nvidia still detect VSCode as "Background Application" even when I'm using it, so it always run at 20 FPS.
I just turn it off for VSCode, and everything back to normal.
