### ISSUE TITLE
Html related

### ISSUE THREAD

**Issue by anany-more09** [microsoft/vscode#190692]
Type: <b>Performance Issue</b>

Hello sir/mam im my vs code "HTML" file is not opening in liver server or in  any browser, on clicking on "start live server" code is not runing not showing not showing anything, it is just showing my html code itself so please suggest me what should i do, please help.
Thank you.

VS Code version: Code 1.81.1 (6c3e3dba23e8fadc360aed75ce363ba185c49794, 2023-08-09T22:22:42.175Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-6006U CPU @ 2.00GHz (4 x 1992)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|3.92GB (0.48GB free)|
|Process Argv|--crash-reporter-id 77c4a753-291f-4f5d-a02d-3c37e27ac11e|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    2	    46	 10684	code main
    0	   103	  3684	window [1] (index.html - WEB_deve - Visual Studio Code)
    0	     5	  4940	fileWatcher [1]
    1	    94	  7616	   gpu-process
    0	     1	  8088	   crashpad-handler
    0	    16	  8284	extensionHost [1]
    0	     3	 13512	     electron-nodejs ("C:\Users\hp\AppData\Local\Programs\Microsoft VS Code\Code.exe" --ms-enable-electron-run-as-node "c:\Users\hp\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\json-language-features\server\dist\node\jsonServerMain" --node-ipc --clientProcessId=8284)
    0	     2	 14228	     electron-nodejs ("C:\Users\hp\AppData\Local\Programs\Microsoft VS Code\Code.exe" --ms-enable-electron-run-as-node "c:\Users\hp\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\html-language-features\server\dist\node\htmlServerMain" --node-ipc --clientProcessId=8284)
    1	    10	  8944	   utility-network-service
    1	    56	 16804	window [2] (Issue Reporter)
    0	    36	 18956	shared-process
    0	     4	 20220	ptyHost
    0	     1	  2876	     C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -noexit -command "try { . \"c:\Users\hp\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\contrib\terminal\browser\media\shellIntegration.ps1\" } catch {}"
    0	     1	  7536	     conpty-agent
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (index.html - WEB_deve - Visual Studio Code)
|    Folder (WEB_deve): 1 files
|      File types: html(1)
|      Conf files:;
```

</details>
<details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-html-css|ecm|1.13.1
code-runner|for|0.12.0
theme-monokai-pro-vscode|mon|1.2.1
cmake-tools|ms-|1.15.31
cpptools|ms-|1.17.3
cpptools-extension-pack|ms-|1.3.0
html-live-server|nav|0.1.0
live-server-preview|neg|0.1.4
LiveServer|rit|5.7.9
cmake|twx|0.0.17
material-theme|zhu|3.16.0
html-css-class-completion|Zig|1.20.0

(3 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263cf:30335440
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
py29gd2263:30792226
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
vsccc:30803844
3biah626:30602489
89544117:30613380
a9j8j154:30646983
showlangstatbar:30737416
03d35959:30757346
pythonfmttext:30731395
pythoncmvfstrcf:30756944
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
gsofa:30804715
pythonnosmt12:30797651
pythonidxpt:30805730
pythonnoceb:30805159
dsvsc013:30795093
dsvsc014:30804076
diffeditorv2:30812749

```

</details>

**Comment by aeschli** [comment]
Please make sure your HTML is valid and working by opening the page in a browser.

If it shows correctly there, then it's an issue of the live-server extension.
Please file the issue against: https://github.com/ritwickdey/vscode-live-server/issues

There is also the live preview extension, maybe it works with that one: https://marketplace.visualstudio.com/items?itemName=ms-vscode.live-server
