### ISSUE TITLE
Support JSON5 syntax by treating it as JS, but without validating it

### ISSUE THREAD

**Issue by giacomorebonato** [microsoft/vscode#190678]
## Context 

Mentioning this intro:

> ESLint is a great linter for JavaScript.
Since [JSON](https://json.org/) is a subset of JavaScript, the same parser and rules can be applied to [JSON](https://json.org/).
Also, [JSONC](https://github.com/microsoft/node-jsonc-parser) and [JSON5](https://json5.org/), which are variants of [JSON](https://json.org/), are more similar to JavaScript than [JSON](https://json.org/). Applying a JavaScript linter to [JSON](https://json.org/) is more rational than creating a JSON-specific linter.

From the good [eslint-plugin-jsonc](https://github.com/ota-meshi/eslint-plugin-jsonc).
Which states how [JSON5](https://json5.org) is more similar to JavaScript rather than JSON.

That's why JavaScript syntax highlight works very well with JSON5 and because of that, this is indeed the setting that I use to leverage that:

```json
  "files.associations": {
    "*.json5": "javascript"
  },
```

The problem that I have now is that to **not** get the following error:

<img width="393" alt="test-json5" src="https://github.com/microsoft/vscode/assets/630796/8fb68288-1755-44d1-a534-11529f60bea7">

I also have to disable JavaScript validation:

```json
"javascript.validate.enable": false
```

Which makes syntax highlighting working perfectly for JSON5... but now I disabled validation also for real JS files that could benefit from it.
I think that the issue is due to the lack of `module.exports = ` at the beginning of JSON5 files.

## Question 

How difficult would it be to solve this issue by introducing integrated support for JSON5?

## Notes 

* [JSON5 extension for VSCode](https://github.com/mrmlnc/vscode-json5) is not well maintained and doesn't provide as good syntax highlight
* Intellij [supports JSON5 out of the box](https://www.jetbrains.com/help/idea/json.html#ws_json_choose_version)

**Comment by aeschli** [comment]
The support has to come from an extension. We have no plans of adding JSON5 support to the core extensions of VS Code.
