### ISSUE TITLE
Process manager does not expose process memory usage reliably

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#190687]
Context: https://github.com/microsoft/vscode/issues/190618

![Image](https://github.com/microsoft/vscode/assets/2193314/c474be2b-172b-44f8-a2c4-825878b2fd9d)

**Comment by harbanero5** [comment]
> Context: #190618
> 
> ![Image](https://user-images.githubusercontent.com/2193314/261366551-c474be2b-172b-44f8-a2c4-825878b2fd9d.png)

**Comment by legomushroom** [comment]
Closing as dup of https://github.com/microsoft/vscode/issues/194322 since it has more activity on it.
