### ISSUE TITLE
can not build and run from source on Windows11

### ISSUE THREAD

**Issue by allenzoe** [microsoft/vscode#190651]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:  1.82.0
- OS Version: 

Steps to Reproduce:

1. enviroment:  windows11  node.js 18.17.1  python 3.11.4  vs 2022
2. command:  yarn
3. error:  
![image](https://github.com/microsoft/vscode/assets/48663314/0a6dd201-bf13-4610-9f6b-cfd826b1df11)

How can I resolve this?

**Comment by Ahmedraza-fyntune** [comment]
try these things 
rm -rf node_modules
yarn cache clean
yarn
yarn start

**Comment by Ahmedraza-fyntune** [comment]
look for yarn update and also delete the yarn.lock file

**Comment by Ahmedraza-fyntune** [comment]
If nothing else helps, add SKIP_PREFLIGHT_CHECK=true to an .env file in your project. That would permble this preflight check in case you want to proceed anyway.

**Comment by allenzoe** [comment]
Tried many times，however nothing else helps, An error occurs when the yarn command is executed to the preinstall.js file
![image](https://github.com/microsoft/vscode/assets/48663314/66e8b94f-55db-4369-aeaf-efe08924385f)

**Comment by allenzoe** [comment]
> If nothing else helps, add SKIP_PREFLIGHT_CHECK=true to an .env file in your project. That would permble this preflight check in case you want to proceed anyway.



> try these things rm -rf node_modules yarn cache clean yarn yarn start
nothing else helps, i have tried many times

**Comment by DonJayamanne** [comment]
I'm very sorry for missing this issue.

**Comment by deepak1556** [comment]
Can you provide the output of `yarn install --cwd build\npm\gyp --verbose`

**Comment by allenzoe** [comment]
> Can you provide the output of `yarn install --cwd build\npm\gyp --verbose`

the output can not find any error , it is too long , only provide part of the output

**Comment by allenzoe** [comment]
i delete the preinstall script, then excute yarn, the output contains error
![image](https://github.com/microsoft/vscode/assets/48663314/3e2115bd-e210-4cd2-870f-a37496647605)

**Comment by allenzoe** [comment]
It has been bothering me for a few days and I hope to help solve it as soon as possible&nbsp;Thank you so much




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "microsoft/vscode"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年8月28日(星期一) 上午10:46
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [microsoft/vscode] can not build and run from source on Windows11 (Issue #190651)





 
I'm very sorry for missing this issue.

**Comment by deepak1556** [comment]
Seems like an issue with your node installation or an encoding issue, lets simplify the error. Please provide the output of following steps

```
> cd D:\trunk\projects
> git clone https://github.com/nodejs/node-addon-api
> cd node-addon-api
> nvm use v18.16.0
> node -p "require('.').include"
```

**Comment by allenzoe** [comment]
![image](https://github.com/microsoft/vscode/assets/48663314/529a8cd2-4e50-4df6-9b76-e67065ab7f18)

**Comment by allenzoe** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年8月28日(星期一) 中午1:16
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [microsoft/vscode] can not build and run from source on Windows11 (Issue #190651)





 
Seems like an issue with your node installation or an encoding issue, lets simplify the error. Please provide the output of following steps
 &gt; cd D:\trunk\projects &gt; git clone https://github.com/nodejs/node-addon-api &gt; cd node-addon-api &gt; nvm use v18.16.0 &gt; node -p "require('.').include"

**Comment by deepak1556** [comment]
@allenzoe your last response is unclear, can you provide the results of the command from https://github.com/microsoft/vscode/issues/190651#issuecomment-1695023786, thanks!

**Comment by allenzoe** [comment]
@deepak1556 i solved the problem by referring to it [https://stackoverflow.com/questions/59512968/call-to-node-e-requirenan-returned-exit-status-1-when-installing-drivel](url)

**Comment by deepak1556** [comment]
Thanks for confirming, closing per above comment.
