### ISSUE TITLE
Feature request: Make font style independent of color theme

### ISSUE THREAD

**Issue by atombender** [Microsoft/vscode#19064]
Today, the entire style of tokens is left to the mercy of the color theme.

That means that you might, like me, find the perfect _color_ combination, but the theme doesn't render keywords bold and it renders comments without italics. In other words, there are permutations of settings that aren't solved by the one-size-fits-all approach of today.

The only way to fix is to fork the theme and edit it, which shouldn't be necessary. For example, if I release my forked theme, then I'm forcing all users to accept italic comments, but this might be the one detail that isn't to their liking. This further leads to a proliferation of themes that make just minor changes to other themes.

To me, "color theme" does not imply something that should control how tokens are styled. In particular, I'd love to be able to tweak the font sizes of individual keywords.

As an aside, there's considerable inconsistency in themes. If I enable "Solarized Dark" (one of the few themes that uses bold styling), some languages (JavaScript) will render bold keywords, whereas others (Go) will not. What's the explanation for this?

**Comment by mousetraps** [comment]
Sorry to hear TM grammars/themes are getting you down - that's no fun. 

As to your inconsistency question, @alexandrudima or @rebornix could probably share more, but my guess is that there's some naming mismatch between the TM grammars (individually defined for each language) and the themes themselves. Is it just the styling that's off, or is it the colors too?

**Comment by atombender** [comment]
@mousetraps The colours are different. Here's with "Solarized Dark":

*JavaScript*

![screen shot 2017-01-23 at 18 36 56](https://cloud.githubusercontent.com/assets/50314/22227775/fdcfeb0a-e19a-11e6-8e5b-d47dfec90213.png)

*Go*

![screen shot 2017-01-23 at 18 36 15](https://cloud.githubusercontent.com/assets/50314/22227776/fdd56a4e-e19a-11e6-9885-a7f18fd42eaa.png)

* In Go, `type` and `struct` are keywords, mapped to `keyword.type.go`.
* In JS, `class` and `extends` are keywords, mapped to `storage.type.class.js`, as far as I can tell. I don't know what "storage" is supposed to mean here.
* In JS, `return` maps to `keyword.control.flow.js`.
* It's also worth asking why, in, `React.Component`, `React` and `Component` are styled differently.

**Comment by alexandrudima** [comment]
There are two main issues here:

1. to add the ability of the end user to contribute rules to the current theme without creating a new theme. The exact same reasoning applies for changing a single color: i.e. I love a theme except for one color, I'd like to change the one color that bothers me without creating a new theme. fyi @aeschli 

2. Different grammars produce different tokens for the same underlying concept (e.g. keyword), for example the TS/JS grammar. fyi @sheetalkamat

**Comment by atombender** [comment]
@alexandrudima: I don't think the reasoning applies to a single colour, for one pedantic reason and a conceptual one: Pedentically, a "color theme" has the word "color" in it; it goes without saying that it should only provide colours. But conceptually, a colour theme's value is the complete set of combination of colours that are _designed to fit together_.

A colour scheme is orthogonal to font styles, which are as relevant to a colour scheme as, say, `editor.fontFamily` or `editor.fontSize`.

As for your second point: Surely that is a matter of pattern matching (although I think it would be a good idea to _fix_ this inconsistency), e.g. a configuration option such as:

```json
{
  "editor.syntaxFontStyles": {
    "^(keyword|storage\\.type)\\.": "bold",
    "^comment\\.line": ["bold", "italic"]
  }
}
```

**Comment by epicgirl1998** [comment]
big +1

i am having a hard time finding a good color theme that doesn't have **bold keywords** or *italic comments*

ideally there should be an option like `allow >color< themes to change text boldness/italicity`

i find comments in italics almost as inconsistent and bad as mixing different fonts (they're usually already colored differently)

and having bold keywords reminds me of one of those old websites with links that become bold (and change the proportions) when you hover them

oh and underlines too, i don't like them in my color themes

**Comment by alexandrudima** [comment]
@aeschli Is it possible to configure the italicness/boldness via configuration ?

**Comment by aeschli** [comment]
Yes:
```json
	"editor.tokenColorCustomizations": {
		"textMateRules": [
			{
				"scope": "comment",
				"settings": {
					"fontStyle": "italic bold"
				}
			}
		]
	}
```

**Comment by alexandrudima** [comment]
:+1: Then, I believe this issue is completely covered
