### ISSUE TITLE
Flutter Create app

### ISSUE THREAD

**Issue by Oyewumi-Marvellous-Oluwaseun** [microsoft/vscode#190664]
Type: <b>Bug</b>

Launching lib\main.dart on Windows in debug mode...
main.dart:1
CMake Error at CMakeLists.txt:3 (project):
  Failed to run MSBuild command:

    C:/Program Files/Microsoft Visual Studio/2022/Community/MSBuild/Current/Bin/amd64/MSBuild.exe

  to get the value of VCTargetsPath:

    Unhandled Exception: System.BadImageFormatException: Could not load file or assembly 'MSBuild.exe' or one of its dependencies. An attempt was made to load a program with an incorrect format.

  Exit code: -532462766

VS Code version: Code 1.81.1 (6c3e3dba23e8fadc360aed75ce363ba185c49794, 2023-08-09T22:22:42.175Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3437U CPU @ 1.90GHz (4 x 2395)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|11.87GB (9.07GB free)|
|Process Argv|--crash-reporter-id a07f1408-23d7-4ee4-b82a-82ca59218179|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (187)</summary>

Extension|Author (truncated)|Version
---|---|---
monokai-charcoal-high-contrast|74t|3.4.0
better-comments|aar|3.0.2
codesnap|adp|1.3.4
vscode-flutter-helper|aks|0.2.5
TabOut|alb|0.2.2
Bookmarks|ale|13.4.1
project-manager|ale|12.7.0
flutter-snippets|ale|3.0.0
auto-add-brackets|ali|0.12.2
aws-toolkit-vscode|ama|1.84.0
better-tests|and|0.3.1
All-Autocomplete|Ati|0.0.26
vscode-django|bat|1.10.0
auto-align|bla|0.0.13
java-run|cao|1.1.4
npm-intellisense|chr|1.4.4
path-intellisense|chr|2.8.4
regex|chr|0.4.0
ccs-flutter-color|cir|1.0.2
codeium|Cod|1.2.66
gitignore|cod|0.9.0
dart-code|Dar|3.70.0
flutter|Dar|3.70.0
vscode-markdownlint|Dav|0.51.0
flutter-auto-import|dav|0.0.1
vscode-eslint|dba|2.4.2
vscode-faker|dee|2.0.0
auto-open-markdown-preview-single|Don|1.0.0
githistory|don|0.6.20
javadebugger|don|0.1.5
java-debug|DSn|0.0.2
es7-react-js-snippets|dsz|4.4.3
gitlens|eam|2023.8.1505
EditorConfig|Edi|0.16.4
flutter-extensions|edu|0.0.1
vsc-material-theme|Equ|33.9.0
vsc-material-theme-icons|equ|2.8.0
carbon-now-sh|eri|1.2.0
prettier-vscode|esb|10.1.0
vscode-flutter-i18n-json|ess|0.28.0
pubspec-dependency-search|eve|1.1.0
vscode-todo-plus|fab|4.19.1
bloc|Fel|6.6.4
auto-close-tag|for|0.5.14
auto-complete-tag|for|0.1.0
auto-rename-tag|for|0.1.10
code-runner|for|0.12.0
workspace-formatter|fra|1.0.0
chatgpt-vscode|gen|0.0.8
codespaces|Git|1.14.15
copilot|Git|1.103.338
copilot-chat|Git|0.6.0
copilot-labs|Git|0.14.884
heygithub|Git|0.21.1441
remotehub|Git|0.60.0
vscode-github-actions|git|0.26.1
vscode-pull-request-github|Git|0.70.0
flutter-stylizer|gml|0.1.16
gobystrok|GoB|0.0.1
vscode-flutter-files|gor|4.7.1
vscode-graphql|Gra|0.8.17
vscode-graphql-syntax|Gra|1.2.2
todo-tree|Gru|0.0.226
complete-flutter-extension-pack|Gul|1.1.0
mayukaithemevsc|Gul|3.2.4
google-translate|han|1.2.8
vs-code-runner|Har|2.0.1
json-to-dart|hir|3.5.8
vscode-auto-open-markdown-preview|hnw|0.0.4
rest-client|hum|0.25.1
json-to-dart-enhanced|Huo|3.6.0
dart-data-class-generator|hzg|0.5.4
path-autocomplete|ion|1.24.1
RelativePath|jak|1.5.0
fontawesome-autocomplete|Jan|1.3.1
pubspec-assist|jer|2.3.2
svg|joc|1.5.3
vscode-peacock|joh|4.2.2
vscode-colorize|kam|0.11.1
auto-comment-blocks|kev|1.0.1
vscode-gutter-preview|kis|0.30.0
fast-coding|kni|0.1.1
LambdaTest-Cloud|Lam|0.3.1
auto-commit-ai|Leo|0.0.5
pomodoro|lky|1.1.3
dart-import|lua|0.3.1
flutter-mvvm-architecture-generator|mad|1.6.0
flutter-tree|mar|1.0.0
auto-build|mar|2.1.45
flutter-snippets|Mar|1.0.5
general-extensions-pack|Mat|0.0.2
metago|met|4.3.3
MetaJump|met|1.4.4
MetaWord|met|1.3.2
git-graph|mhu|1.30.0
dart-barrel-file-generator|miq|6.1.1
vuex-suggest|mis|1.1.1
vscode-extension-auto-import|mop|1.3.3
snapcode|moy|1.1.0
graphql|mqu|0.1.2
flutter-extension-pack|MrC|1.7.1
vscode-duplicate|mrm|1.2.1
vscode-docker|ms-|1.26.0
python|ms-|2023.14.0
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-slideshow|ms-|0.1.5
remote-containers|ms-|0.304.0
remote-ssh|ms-|0.102.0
remote-ssh-edit|ms-|0.86.0
remote-wsl|ms-|0.81.0
vscode-remote-extensionpack|ms-|0.24.0
azure-repos|ms-|0.36.0
cpptools|ms-|1.17.2
hexeditor|ms-|1.9.12
notepadplusplus-keybindings|ms-|1.0.7
remote-explorer|ms-|0.4.1
remote-repositories|ms-|0.38.1
remote-server|ms-|1.4.0
resharper9-keybindings|ms-|1.1.0
vsliveshare|ms-|1.0.5877
awesome-flutter-snippets|Nas|4.0.1
color-highlight|nau|2.5.0
indent-rainbow|ode|8.3.1
dartgettersetter|Pet|1.0.2
explorer-exclude|Pet|1.3.2
vscode-versionlens|pfl|1.5.0
material-icon-theme|PKi|4.29.0
platformio-ide|pla|3.3.1
remove-comments|pli|1.2.2
polacode|pnp|0.3.4
vscode-css-peek|pra|4.4.1
auto-rename-tag|pra|0.1.5
quicktype|qui|12.0.46
java|red|1.21.0
vscode-yaml|red|1.14.0
create-flutter-widgets-and-classes|ric|3.21.0
dart-data-class-tools|ric|0.5.9
flutter-development-extensions-pack|ric|1.11.0
flutter-print|ric|1.7.2
LiveServer|rit|5.7.9
gi|rub|0.2.11
partial-diff|ryu|1.4.3
code-settings-sync|Sha|3.4.3
trailing-spaces|sha|0.4.1
markdown-preview-enhanced|shd|0.6.8
svg-preview|Sim|2.8.3
vscode-fileutils|sle|3.10.3
vscode-multiclip|sle|0.1.5
codify|sma|1.0.48
java-generate-setters-getters|soh|8.0.0
autoimport|ste|1.5.4
code-spell-checker|str|2.20.5
code-autocomplete|svi|1.2.1
auto-correct|syg|0.2.2
tabnine-vscode|Tab|3.7.0
rainbow-bracket|tal|1.0.2
even-better-toml|tam|0.19.2
open-in-browser|tec|2.0.0
rainbow-brackets-2|tej|1.1.0
pdf|tom|1.2.2
java-imports-snippets|tus|0.0.1
java-snippets|tus|0.0.1
todo-list|Tza|1.6.0
errorlens|use|3.13.0
highlight-matching-tag|vin|0.11.0
intellicode-api-usage-examples|Vis|0.2.7
vscodeintellicode|Vis|1.2.30
vscode-java-debug|vsc|0.53.0
vscode-java-dependency|vsc|0.23.1
vscode-java-pack|vsc|0.25.13
vscode-java-test|vsc|0.39.1
vscode-maven|vsc|0.42.0
vscode-icons|vsc|12.5.0
gitblame|wad|10.4.0
vscode-wakatime|Wak|24.2.1
vscode-todo-highlight|way|1.0.5
flutter-assets-gen2|wee|0.1.4
jinja|who|0.0.8
vscode-import-cost|wix|3.3.0
change-case|wma|1.0.0
vscode-jumpy|wma|0.3.1
code-debuger|wow|0.1.2
JavaScriptSnippets|xab|1.8.0
just-print-it|Xua|1.1.1
chatgpt-ai|Yal|0.7.12
fast-dart|Yas|1.0.2
markdown-all-in-one|yzh|3.5.1

(9 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
vscccc:30803845
3biah626:30602489
89544117:30613380
showlangstatbar:30737416
03d35959:30757346
pythonfmttext:30731395
pythoncmv:30756943
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
gsofa:30804715
pythonnosmt12:30797651
pythonidxptcf:30805731
pythonnoceb:30805159
asynctok:30810527
dsvsc013:30795093
dsvsc014:30804076
diffeditorv1:30812748

```

</details>

**Comment by Oyewumi-Marvellous-Oluwaseun** [comment]
Please i need help. . . .

**Comment by roblourens** [comment]
Please file on the Flutter/dart extension
