### ISSUE TITLE
The number of files in the source control does not change when adding a file to the staging area

### ISSUE THREAD

**Issue by michael-schantin** [microsoft/vscode#190638]
Type: <b>Bug</b>

Have a list of changed files in a git repository (e.g. 7 Staged Changes, 13 Changes)
Press the + to stage another file
Expected: 8 Staged Changes, 12 Changes
Observed: The file is staged but the number does not update, still 7 Staged Changes, 13 Changes. Upon restart the numbers update.

VS Code version: Code 1.81.1 (Universal) (6c3e3dba23e8fadc360aed75ce363ba185c49794, 2023-08-09T22:20:33.924Z)
OS version: Darwin x64 23.0.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|4, 5, 4|
|Memory (System)|32.00GB (3.88GB free)|
|Process Argv|--crash-reporter-id de1c6361-feb7-4af0-81cc-7e1d3d7c6107 --crash-reporter-id de1c6361-feb7-4af0-81cc-7e1d3d7c6107|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (78)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|3.0.2
codesnap|adp|1.3.4
cucumberautocomplete|ale|2.15.2
preview-mp4|ana|0.0.1
iconify|ant|0.6.1
smart-clicks|ant|0.1.5
atlascode|atl|3.0.4
markdown-emoji|bie|0.3.0
vscode-toggle-quotes|Bri|0.3.6
turbo-console-log|Cha|2.9.6
test-utils|chr|1.0.2
npm-intellisense|chr|1.4.4
path-intellisense|chr|2.8.4
cucumber-official|Cuc|1.7.0
es7-react-js-snippets|dsz|4.4.3
bracket-pair-toggler|dzh|0.0.3
EditorConfig|Edi|0.16.4
LogFileHighlighter|emi|2.16.0
vsc-material-theme|Equ|33.9.0
vsc-material-theme-icons|equ|2.8.0
vscode-postman|eri|2.1.0
prettier-vscode|esb|10.1.0
vscode-macros|EXC|1.4.1
vscode-coding-tools-extension-pack|fra|0.8.0
vscode-typescript-extension-pack|fra|0.2.1
workspace-formatter|fra|1.0.0
gitlab-workflow|Git|3.73.0
gc-excelviewer|Gra|4.2.58
shifter|Gru|0.0.6
mediawiki|jas|0.0.4
vscode-peacock|joh|4.2.2
cypress-fixture-intellisense|Jos|1.2.0
blockman|leo|1.7.5
expand-region|let|0.1.4
pop-n-lock-theme-vscode|Lux|3.32.188
cucumberautocomplete-behat|mar|1.0.0
import-sorter|mik|3.3.1
vs-media-player|mkl|3.1.0
prettify-json|moh|0.0.3
vscode-hybris-tools|moj|0.4.0
language-gettext|mro|0.2.2
vscode-language-pack-de|MS-|1.81.2023081609
playwright|ms-|1.0.15
remote-containers|ms-|0.304.0
remote-ssh|ms-|0.102.0
vscode-remote-extensionpack|ms-|0.24.0
hexeditor|ms-|1.9.12
vs-keybindings|ms-|0.2.1
copy-file-name|nem|1.2.0
vscode-streamdeck|nic|4.1.6
indent-rainbow|ode|8.3.1
open-html-in-browser|pea|2.1.10
vscode-versionlens|pfl|1.5.0
material-icon-theme|PKi|4.29.0
tsimporter|pmn|2.0.1
postman-for-vscode|Pos|0.5.5
vscode-yaml|red|1.14.0
LiveServer|rit|5.7.9
wikitext|Row|3.8.0
partial-diff|ryu|1.4.3
impex-support|sim|0.2.5
sonarlint-vscode|Son|3.20.2
es6-mocha-snippets|spo|0.2.2
code-spell-checker|str|2.20.5
code-spell-checker-german|str|2.2.1
vscode-extension-open-cypress|tnr|0.0.14
pdf|tom|1.2.2
errorlens|use|3.13.0
code-navigation|vik|0.2.0
vscode-fold-level|vik|0.0.14
vscode-svg-previewer|vit|0.7.0
windicss-intellisense|voo|0.21.6
vscode-java-debug|vsc|0.53.0
vscode-java-dependency|vsc|0.23.1
vscode-java-pack|vsc|0.25.13
vscode-icons|vsc|12.5.0
JavaScriptSnippets|xab|1.8.0
markdown-all-in-one|yzh|3.5.1

(4 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscorecescf:30445987
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
vscccc:30803845
2e4cg342:30602488
89544117:30613380
showlangstatbar:30737416
03d35959:30757346
pythonfmttext:30731395
pythoncmv:30756943
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
gsofb:30804716
pythonnosmt12:30797651
pythonidxptcf:30805731
pythonnoceb:30805159
dsvsc013:30795093
dsvsc014:30804076
diffeditorv2:30812749

```

</details>

**Comment by gjsjohnmurray** [comment]
Is that message "7 Staged Changes, 13 Changes" being contributed by one of your extensions? One way to check is to run the `Start Extension Bisect` command.

**Comment by michael-schantin** [comment]
Thanks for the tip. I can no longer reproduce the problem (both with extensions and without extensions).
