### ISSUE TITLE
Crash after debug

### ISSUE THREAD

**Issue by Vince6700** [microsoft/vscode#190671]
Type: <b>Bug</b>

Debug tests
after a few times it starts crashing

VS Code version: Code - Insiders 1.82.0-insider (Universal) (ccb95fd921349023027a0df25ed291b0992b9a18, 2023-08-17T05:35:00.633Z)
OS version: Darwin arm64 22.5.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Max (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|32.00GB (4.17GB free)|
|Process Argv|--crash-reporter-id cfd38a2f-1646-4343-bc02-11256edf0938|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-sql-formatter|adp|1.4.4
npm-intellisense|chr|1.4.4
path-intellisense|chr|2.8.4
vscode-eslint|dba|2.4.2
gitlens|eam|2023.8.1505
vsc-material-theme-icons|equ|2.8.0
prettier-vscode|esb|10.1.0
vscode-jest-runner|fir|0.4.66
copilot|Git|1.103.338
copilot-chat|Git|0.7.2023081701
vscode-pull-request-github|Git|0.71.2023081709
vscode-docker|ms-|1.26.0
remote-containers|ms-|0.305.0
vs-code-prettier-eslint|rve|5.1.0
code-spell-checker|str|2.20.5
gitblame|wad|10.4.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes516:30244333
vslsvsres303:30308271
pythontb:30258533
pythonptprofiler:30281269
vshan820:30294714
vscod805cf:30301675
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30404738
py29gd2263:30784851
vsclangdf:30492506
c4g48928:30535728
dsvsc012:30540252
pynewext54:30618038
showlangstatbar:30737417
57b77579:30687741
pythonfmttext:30716741
pythoncmvfstr:30726892
fixshowwlkth:30771523
showindicator:30805243
pythongtdpath:30726887
i26e3531:30792625
gsofa:30797620
welcomedialog:30812478
pythonnosmt12:30779711
pythonidxpt:30768918
pythonnoceb:30776497
copilotsettingt:30808721
dsvsc013:30777762
dsvsc014:30777825
diffeditorv2:30786206
pythonmpsinfo:30815194

```

</details>

**Comment by william-wallace-simplisafe** [comment]
The jest debugger hangs and eventually crashes vscode in vscode version 1.81.1
Version: 1.81.1 (Universal)
Commit: 6c3e3dba23e8fadc360aed75ce363ba185c49794
Date: 2023-08-09T22:20:33.924Z (1 wk ago)
Electron: 22.3.18
ElectronBuildId: 22689846
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Darwin x64 22.6.0


A workaround is to downgrade to 1.80.2:
Here are instructions to downgrade
https://stackoverflow.com/questions/49346733/how-to-downgrade-vscode

**Comment by roblourens** [comment]
Please file an issue on the jest extension you're using

**Comment by william-wallace-simplisafe** [comment]
A new issue has been filed with Jest Runner: [Issue #327](https://github.com/firsttris/vscode-jest-runner/issues/327)

**Comment by william-wallace-simplisafe** [comment]
Why was this issue closed?  It is evident that the upgrade to version 1.81.1 broke something.  I don't think this issue should be closed until there is a root cause

**Comment by william-wallace-simplisafe** [comment]
Here is a zip file containing all the logs after running `code --log trace` then reproducing the issue:
[logs.zip](https://github.com/microsoft/vscode/files/12380821/logs.zip)
