### ISSUE TITLE
An unexpected error occurred that requires a reload of this page.

### ISSUE THREAD

**Issue by DanielSet91** [microsoft/vscode#190632]
### Applies To

- [ ] Notebooks (.ipynb files)
- [ ] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

Github dev doesnt load up.

The workbench failed to connect to the server (Error: connection record disposed by ConnectionHub: {
"errorMessage": "Failed to start VS Code Remote server.",
"originalErrorType": "<no original type>",
"errorCode": -1,
"errorType": "GenericError",
"stack": "Error: Failed to start VS Code Remote server.\n at [CODESPACE_URL]\n at [CODESPACE_URL]\n at [CODESPACE_URL]\n at [CODESPACE_URL]\n at d ([CODESPACE_URL]\n at a ([CODESPACE_URL]"
} $1 $1)

### VS Code Version

1

### Jupyter Extension Version

1

### Running Jupyter locally or remotely?

None

**Comment by connor4312** [comment]
The Github codespaces issue tracker is here, please report this there: https://gh.io/ghcs-feedback
