### ISSUE TITLE
Settings list item wrapping towards next line causes the list to overflow

### ISSUE THREAD

**Issue by hsfzxjy** [microsoft/vscode#190720]
Type: Bug
Does this issue occur when all extensions are disabled?: Yes

Version: 1.81.1
Commit: 6c3e3dba23e8fadc360aed75ce363ba185c49794
Date: 2023-08-09T22:18:39.991Z
Electron: 22.3.18
ElectronBuildId: 22689846
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Linux x64 5.15.0-76-generic

Steps to Reproduce:

1. Open Settings, find a block comprised of a list of items;
2. Shrink the column size so that some of the items wrap towards next line, and you can observe the list overflows.

https://github.com/microsoft/vscode/assets/4702188/d3e69b6a-85a6-4cdb-9ab4-1406a62bfadc

**Comment by Ahmedraza-fyntune** [comment]
is that u r using some go extension

**Comment by hsfzxjy** [comment]
The screencast did, but it's merely for demostrating the bug. The bug itself is irrelevant to any extension.
