### ISSUE TITLE
Test terminal performance and Windows support improvements

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#19071]
Testing #13625, #17875

- [x] Linux @roblourens 
- [x] OSX @bpasero 
- [x] Windows @dbaeumer 

Complexity: 4 (ideally someone fairly familiar with terminals and curses apps)

Much of the terminal frontend xterm.js was rewritten for performance this version, here is a summary of what happened:

- The parser was rewritten for performance
- A catch up mechanism was added which utilizes XOFF/XON signals to tell the pty process to stop while the parser and renderer catch up
- Rendering is now done asynchronously in an animation frame callback
- Additional frame skipping was added to prevent printing to the viewport when the result would change 20ms later anyway
- A circular list is now used to manage the buffer, promoting memory reuse, reducing GCs and automatically handling trimming of the buffer to conform with the scrollback value (amount of lines kept in the buffer)
- General rendering performance improvements

Additionally on Windows the library used to simulate pseudoterminals has been upgraded several versions and cleaned up which was a huge change that should fix many bugs such as:

- Arrow keys wording in Bash on Windows https://github.com/Microsoft/vscode/issues/10163
- Git Bash, Bash on Windows prompt and other shells having their prompt getting out of sync when using backspace https://github.com/Microsoft/vscode/issues/7345
- Prompt screwing up when using tab https://github.com/Microsoft/vscode/issues/16914
- Many other issues https://github.com/Microsoft/vscode/issues/14613

As a result a fairly broad test would be ideal. Here are some areas to focus on:

- Running commands that generate a lot of output, I used `ls -lR` extensively to test during development
- Applications such as less, vim, nano, git, etc. act as expected
- The scroll bar accurately represents the current viewport
- The terminal behaves when the terminal buffer is not full (new terminal) and full (buffer length = scrollback)
- Test with different shells
  - Linux/OSX: bash, zsh
  - Windows: cmd, powershell, Git Bash, Bash on Windows (may require Windows Insiders)

**Comment by dbaeumer** [comment]
Tested with PowerShell & cmd.exe. I tested it with Bash from the Windows Subsystem started from a PowerShell command prompt. Couldn't get it to work using bash natively.

**Comment by dbaeumer** [comment]
Did get bash to work using `"terminal.integrated.shell.windows": "C:\\WINDOWS\\Sysnative\\bash.exe"`
