### ISSUE TITLE
extensions not available, return code from server 500

### ISSUE THREAD

**Issue by estubid** [microsoft/vscode#190702]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:  1.81.1 Code - OSS
- OS Version: KDE/Arch

![Screenshot_20230817_133953](https://github.com/microsoft/vscode/assets/134380481/8f4c6715-a3eb-4d70-8b16-515511981f14)

**Comment by estubid** [comment]
works fine with insider

**Comment by sandy081** [comment]
Extensions from MP are not supported with Code-OSS version
