### ISSUE TITLE
Stop supporting suppressSuggestions API

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#190727]
Based on strong user feedback ghost text should not be able to suppress suggestions. Let's stop supporting the suppressSuggestion flag:

https://github.com/microsoft/vscode/blob/b0abdbeadc01b0f922284843a5bdc1594b19201a/src/vscode-dts/vscode.proposed.inlineCompletionsAdditions.d.ts#L68

**Comment by isidorn** [comment]
Removing feature-request so we do not have to verify this, since we already have other issue covering this

**Comment by devm33** [comment]
Hi @isidorn and @hediet is there a migration path planned for this removal?

**Comment by isidorn** [comment]
@devm33 no. This was proposed API, and proposed API updates usually do not have a migration plan.
In case you work on Copilot this issue has a broader discussion https://github.com/github/copilot/issues/4794

Thank you!
