### ISSUE TITLE
Shell command (`code-insiders`) frequently disappears on Darwin

### ISSUE THREAD

**Issue by carterhimmel** [microsoft/vscode#190753]
Hi there! On my computer, the `code-insiders` command frequently disappears without a trace. `which` and `whereis` are inconclusive. The only fix is runing `workbench.action.uninstallCommandLine` then `workbench.action.installCommandLine`. 
 
Though https://github.com/microsoft/vscode/issues/42051 exists, this is different, as it disappears when the devices goes into sleep.  

When `/usr/local/bin/code-insiders` is present, the file content is https://github.com/microsoft/vscode/blob/6336ee75304eaac32897d8e74c451863d877cb28/resources/darwin/bin/code.sh.

Does this issue occur when all extensions are disabled?: ~~Yes/No~~ **N/A**

```
Version: 1.81.0-insider (Universal)
Commit: 862fa13002d8018c328931ee1edccfd4ca76447d
Date: 2023-07-26T05:36:43.574Z
Electron: 22.3.17
ElectronBuildId: 22432899
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Darwin arm64 22.6.0
```

**Comment by joaomoreno** [comment]
What does this return?

```
$ realpath /usr/local/bin/code-insiders
```

**Comment by carterhimmel** [comment]
```console
$ realpath /usr/local/bin/code-insiders
/private/var/folders/vl/phcynyz15vlflt875ljhvb280000gn/T/AppTranslocation/DAE0D032-5C60-4A00-B64F-0BBD2019DADD/d/Visual Studio Code - Insiders.app/Contents/Resources/app/bin/code
```
