### ISSUE TITLE
[Accessibility] Exclude redundant info from aria alert in Accessible View

### ISSUE THREAD

**Issue by jooyoungseo** [microsoft/vscode#190718]
Type: <b>Bug</b>

Pressing Alt+] and Alt+[ in Accessible View includes redundant aria alert before new content. On Windows, NVDA and JAWS users hear the following info first whenever they press Alt+] and Alt+[ in Accessible View:

> Inline Completions Accessible View edit

I have tested with Accessible View against inline suggestion.

Please exclude this message from the aria alert.

VS Code version: Code - Insiders 1.82.0-insider (ccb95fd921349023027a0df25ed291b0992b9a18, 2023-08-17T05:33:29.141Z)
OS version: Windows_NT x64 10.0.22621
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz (8 x 2611)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.71GB (5.67GB free)|
|Process Argv|. --crash-reporter-id b05b88e5-8894-4031-ae34-fa034ebddea9|
|Screen Reader|yes|
|VM|0%|
</details><details><summary>Extensions (89)</summary>

Extension|Author (truncated)|Version
---|---|---
android-dev-ext|ade|1.3.2
Bookmarks|ale|13.4.1
openscad|Ant|1.2.1
spellright|ban|3.0.116
zoterolatex|bna|0.4.1
mermaid-markdown-syntax-highlighting|bpr|1.5.2
doxdocgen|csc|1.4.0
vscode-markdownlint|Dav|0.51.0
vscode-eslint|dba|2.4.2
vscode-quick-select|dba|0.2.9
vscode-deno|den|3.20.0
gitlens|eam|14.2.1
EditorConfig|Edi|0.16.4
prettier-vscode|esb|10.1.0
vscode-google-translate|fun|1.4.13
codespaces|Git|1.14.15
copilot|Git|1.104.343
copilot-chat|Git|0.7.2023081701
remotehub|Git|0.60.0
vscode-github-actions|git|0.26.1
vscode-pull-request-github|Git|0.70.0
easy-snippet|inu|0.6.3
path-autocomplete|ion|1.24.1
latex-workshop|Jam|9.13.4
lilypond-syntax|jea|0.1.1
scheme|jea|0.2.0
better-cpp-syntax|jef|1.17.2
google-search|kam|0.0.1
vscode-lua-format|Koi|1.3.8
lilypond-formatter|lhl|0.2.3
lilypond-pdf-preview|lhl|0.2.8
lilypond-snippets|lhl|0.1.1
vslilypond|lhl|1.7.3
zotero|mbl|0.1.10
git-graph|mhu|1.30.0
vscode-docker|ms-|1.26.0
black-formatter|ms-|2023.4.1
flake8|ms-|2023.6.0
isort|ms-|2023.11.12061012
python|ms-|2023.14.0
vscode-pylance|ms-|2023.8.30
jupyter|ms-|2023.7.1002162226
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.17
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-slideshow|ms-|0.1.5
remote-containers|ms-|0.305.0
remote-ssh|ms-|0.105.1
remote-ssh-edit|ms-|0.86.0
remote-wsl|ms-|0.81.0
vscode-remote-extensionpack|ms-|0.24.0
azure-repos|ms-|0.36.0
cmake-tools|ms-|1.15.31
cpptools|ms-|1.17.3
cpptools-extension-pack|ms-|1.3.0
js-debug-nightly|ms-|2023.8.1117
powershell|ms-|2023.6.0
remote-repositories|ms-|0.38.1
vscode-github-issue-notebooks|ms-|0.0.129
vscode-selfhost-test-provider|ms-|0.3.16
vscode-serial-monitor|ms-|0.10.0
vsliveshare|ms-|1.0.5877
resourcemonitor|mut|1.0.7
autodocstring|njp|0.6.1
pandocciter|not|0.10.3
shiny-python|Pos|0.1.2
shinyuieditor|pos|0.4.3
quarto|qua|1.94.0
r-debugger|RDe|0.5.4
java|red|1.21.0
vscode-xml|red|0.26.1
r|REd|2.8.1
multi-command|ryu|1.6.0
vscode-deepl|soe|1.0.6
abc-music|sof|0.4.0
lua|sum|3.6.26
latex-utilities|tec|0.4.10
cmake|twx|0.0.17
errorlens|use|3.13.0
intellicode-api-usage-examples|Vis|0.2.7
vscodeintellicode|Vis|1.2.30
vscode-arduino|vsc|0.6.0
vscode-java-debug|vsc|0.53.0
vscode-java-dependency|vsc|0.23.1
vscode-java-pack|vsc|0.25.13
vscode-java-test|vsc|0.39.1
vscode-maven|vsc|0.42.0
markdown-all-in-one|yzh|3.5.1
grammarly|znc|0.22.1

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vslsvsres303:30308271
pythontb:30258533
pythonptprofiler:30281269
vshan820:30294714
vscod805cf:30301675
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30404738
py29gd2263:30784851
vsclangdf:30492506
c4g48928:30535728
dsvsc012:30540252
pynewext54:30618038
a9j8j154:30646983
showlangstatbar:30737417
ecj1e332:30687743
pythonfmttext:30716741
pythoncmvfstr:30726892
fixshowwlkth:30771523
showindicator:30805243
pythongtdpath:30726887
i26e3531:30792625
gsofa:30797620
welcomedialog:30812478
pythonnosmt12:30779711
pythonidxpt:30768918
pythonnoceb:30776497
copilotsettingt:30808721
dsvsc013:30777762
dsvsc014:30777825
diffeditorv2:30786206
pythonmpsinfo:30815194

```

</details>

**Comment by meganrogge** [comment]
@jooyoungseo can you pls try in insider's? I made some changes yesterday that should've fixed this.

**Comment by jooyoungseo** [comment]
This issue still exists in the latest insider that I have updated today.

**Comment by meganrogge** [comment]
That info, 'Inline Completions Accessible View' was formerly provided via the aria label. With this change, 
https://github.com/microsoft/vscode/pull/190693#issue-1855424055, it just says 'Accessible View', but when I use the keybindings to go to next/previous, I only hear the new suggestion via `alert` as expected.

**Comment by jooyoungseo** [comment]
That’s odd. I still hear that redundant label info in Accessible View for inline suggestion when pressing Alt+[ and Alt+]. I have tested with NVDA and JAWS on Windows 11.

**Comment by meganrogge** [comment]
What happens for me is:

1. trigger inline completion
2. open accessible view 
3. hear "Accessible View, edit text...."
4. use `alt+[ or ]`
5. there's some delay before the screen reader moves on from reading the initial text then I'm alerted with the new suggestion

**Comment by meganrogge** [comment]
If we wanted to prevent this delay, we'd need to hide the context view, wait 50 ms, reshow it. The issue with that is then it would do exactly what you describe and read the aria label + edit text before reading the new suggestion. That's what was happening in insider's yesterday and I realized was not ideal, so changed it.

**Comment by meganrogge** [comment]
@rperez030 can you reproduce this in today's Insider's?

**Comment by rperez030** [comment]
@meganrogge  it is working for me as @jooyoungseo  described. I also debug with NVDA, and confirmed that it is processing the focus events before the liveRegionChange event. However, if I use Alt + left or right brackets, it behaves as we expect. If you hide the accessible view for 50 ms it might work, simply because NVDA will not receive any focus event before the alert.

**Comment by rperez030** [comment]
@jooyoungseo  I get slightly nervous about being so prescriptive when it goes to screen reader behavior. You just need a small change in the way the screen reader handle things for all these hacks to turn against us. There are a few that I feel comfortable recommending.

**Comment by meganrogge** [comment]
Thanks for confirming @rperez030. I've only tried macOS/ VoiceOver, so maybe the repro happens only when using NVDA.

Here was the change where I had added that delay 

https://github.com/microsoft/vscode/pull/190694

**Comment by meganrogge** [comment]
I can bring that change back if it seems reasonable to you. It's just like the other one that you tested and said works well

**Comment by meganrogge** [comment]
@jooyoungseo we still need to setup self hosting for you 😄.

**Comment by rperez030** [comment]
> Thanks for confirming @rperez030. I've only tried macOS/ VoiceOver, so maybe the repro happens only when using NVDA.
> 

That's because Voiceover deliberately ignores the focus event since it "believes" that it doesn't make sense to process it when the destination object is the same that initiated the change. You will also observe it with JAWS, and there is almost nothing to do in that case because JAWS actively prioritizes a focus event against an aria live change when they are nearby, and I don't know what the threshold is.

**Comment by rperez030** [comment]
> @jooyoungseo we still need to setup self hosting for you 😄.

Oh yes. self-hosting is fun.
