### ISSUE TITLE
VS Code cannot access Extension Marketplace (vsassets.io)

### ISSUE THREAD

**Issue by Crazypersonalph** [microsoft/vscode#190797]
Does this issue occur when all extensions are disabled?: Yes/No
Yes

- Version: 1.81.1 (user setup)
- Commit: 6c3e3dba23e8fadc360aed75ce363ba185c49794
- Date: 2023-08-09T22:22:42.175Z
- Electron: 22.3.18
- ElectronBuildId: 22689846
- Chromium: 108.0.5359.215
- Node.js: 16.17.1
- V8: 10.8.168.25-electron.0
- OS: Windows_NT x64 10.0.23521

Steps to Reproduce:

1. Open VS Code
2. Go to extensions
3. Some extension icons load in, after a few seconds they disappear
4. Nothing loads in except the names of extensions
5. No details load in, nothing
6. Console errors out with Error: `net::ERR_CONNECTION_TIMED_OUT`

I acknowledge that there have been issues reported here similar to this, but nothing there has fixed my issue.

In the developer tools, there is no response to a lot of the requests

I've tried loading VS Code in Arch Linux, and it is working perfectly fine, and accessing normal websites/other applications works fine.

**Comment by gjsjohnmurray** [comment]
Can you browse the Microsoft Marketplace directly at https://marketplace.visualstudio.com/vscode from your Windows machine?

IIRC the Arch Linux variant of VS Code uses a different marketplace, Open VSX.

**Comment by Crazypersonalph** [comment]
> Can you browse the Microsoft Marketplace directly at https://marketplace.visualstudio.com/vscode from your Windows machine?
> 
> IIRC the Arch Linux variant of VS Code uses a different marketplace, Open VSX.

Oh yeah, I forgot about the Open VSX thing 😅

About browsing the marketplace, I can, the body of the extension page is loading in, but no icons

As for VS Code itself, nothing is loading in, except for the title and how many users have downloaded it.

**Comment by gjsjohnmurray** [comment]
I guess something in your Internet is blocking access to a site.

**Comment by Crazypersonalph** [comment]
> I guess something in your Internet is blocking access to a site.

I don't know what though, everything is clean, vs code was working just a few days ago, when I used to have a Microsoft VS Code build on linux that was working.

All the troubleshooting advice I've seen across the internet hasn't helped; I'm not using any proxies/vpns whatsoever

**Comment by Crazypersonalph** [comment]
Looks like an issue with my specific network, may be my ISP doing funny things

Thank you
