### ISSUE TITLE
 Uncaught TypeError: Cannot read property 'length' of null

### ISSUE THREAD

**Issue by vscodeerrors** [Microsoft/vscode#19072]
Issue Id: <b>564d6ff8-9eed-59a1-253f-c7cf5855951c</b><br /><br />*Versions* <br />- 1.9.0-insider (1/20/2017 3:02:37 PM)<br />*Stack* <br />TypeError: Cannot read property 'length' of null<br />[/vs/editor/contrib/find/common/replacePattern.ts#L47:37 (length)](https://github.com/microsoft/vscode/blob/ee9d91c05fa571de56c41383cceee30b05b0a2f6/src/vs/editor/contrib/find/common/replacePattern.ts#L47:37 (length))<br />[/vs/editor/contrib/find/common/findModel.ts#L389:38 (buildReplaceString)](https://github.com/microsoft/vscode/blob/ee9d91c05fa571de56c41383cceee30b05b0a2f6/src/vs/editor/contrib/find/common/findModel.ts#L389:38 (buildReplaceString))<br />[/vs/editor/contrib/find/common/findController.ts#L243:15 (replaceAll)](https://github.com/microsoft/vscode/blob/ee9d91c05fa571de56c41383cceee30b05b0a2f6/src/vs/editor/contrib/find/common/findController.ts#L243:15 (replaceAll))<br />[/vs/editor/contrib/find/browser/findWidget.ts#L583:21 (replaceAll)](https://github.com/microsoft/vscode/blob/ee9d91c05fa571de56c41383cceee30b05b0a2f6/src/vs/editor/contrib/find/browser/findWidget.ts#L583:21 (replaceAll))<br />[/vs/editor/contrib/find/browser/findWidget.ts#L728:14 (onTrigger)](https://github.com/microsoft/vscode/blob/ee9d91c05fa571de56c41383cceee30b05b0a2f6/src/vs/editor/contrib/find/browser/findWidget.ts#L728:14 (onTrigger))<br />[/vs/base/browser/ui/widget.ts#L16:102 (listener)](https://github.com/microsoft/vscode/blob/ee9d91c05fa571de56c41383cceee30b05b0a2f6/src/vs/base/browser/ui/widget.ts#L16:102 (listener))<br />

**Comment by alexandrudima** [comment]
This has been fixed in the meantime.
