### ISSUE TITLE
Tasks take ~1 second to stop, attempt #2

### ISSUE THREAD

**Issue by CrendKing** [microsoft/vscode#190704]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.55.2, 1.56.2, 1.57.1, 1.81.1
- OS Version: Windows 11 build 22621.2134

Steps to Reproduce:

Two years ago, @macromaniac reported this issue https://github.com/microsoft/vscode/issues/137066, showing that in 1.62.2, even no-op task takes more than 1 second to stop. He provided a test tasks.json to reproduce the issue. Two years later, this issue still exists in the latest 1.81.1 and even insider 1.82.0.

This issue makes it really frustrating to debug C/C++ programs with fast iterations, because even no source code is changed and no rebuild is needed, since it's recommended to put a `preLaunchTask` in launch config, it means we always have to wait at least 2 seconds to launch. Can't we do better than this? There used to be no such problem before 1.56.0.

Here is the bisect result:

1. Create a directory with the tasks.json from https://github.com/microsoft/vscode/issues/137066.
2. Download [1.55.2](https://update.code.visualstudio.com/1.55.2/win32-x64-archive/stable). Extract. Open that directory. Run displayTimes task. My result is averaged at 400ms. This is last known good version. And 400ms is reasonably tolerable.
3. Try the same with [1.56.2](https://update.code.visualstudio.com/1.56.2/win32-x64-archive/stable), the number jumps to average 700ms. Presumably this is due to the ["Tasks 2.0.0"](https://code.visualstudio.com/updates/v1_56#_removal-of-tasks-010-with-upgrade) change?
4. Try the same with [1.57.1](https://update.code.visualstudio.com/1.57.1/win32-x64-archive/stable), the number finally jumps to average 1700ms. The biggest change of this version is the [Workspace Trust](https://code.visualstudio.com/updates/v1_57#_workspace-trust), but even if I set `"security.workspace.trust.enabled": false` the delay remains.
5. Every version upward shares the same problem as 1.57.

**Comment by meganrogge** [comment]
cc @sbatten for workspace trust

**Comment by CrendKing** [comment]
A little update: I wrote a minimum exe that just print current timestamp to stdout, to make sure the delay is not introduced by the PowerShell script. After that, I tested this on a clean Windows 10 virtual machine and I can still repro the issue there. However, when I tested this on a clean MacBook the delay is not there. So something is problematic just on Windows.

**Comment by lszomoru** [comment]
> Try the same with [1.57.1](https://update.code.visualstudio.com/1.57.1/win32-x64-archive/stable), the number finally jumps to average 1700ms. The biggest change of this version is the [Workspace Trust](https://code.visualstudio.com/updates/v1_57#_workspace-trust), but even if I set "security.workspace.trust.enabled": false the delay remains.

@meganrogge, is there any reason why we believe that this is due to workspace trust given this comment?

**Comment by meganrogge** [comment]
I misread that - thanks @lszomoru. I am going to close this as I haven't had any other reports of this.
