### ISSUE TITLE
Nested Folder Renaming does not work

### ISSUE THREAD

**Issue by yashsway** [microsoft/vscode#190744]
Type: <b>Bug</b>

1. Create a folder
2. Create another folder underneath it
3. Right click the nested folder and select "Rename" from the context menu. Nothing happens.

VS Code version: Code 1.81.1 (Universal) (6c3e3dba23e8fadc360aed75ce363ba185c49794, 2023-08-09T22:20:33.924Z)
OS version: Darwin x64 22.5.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|6, 5, 5|
|Memory (System)|32.00GB (0.22GB free)|
|Process Argv|--crash-reporter-id 186c8783-af82-4ffb-94d4-5fad30605de1|
|Screen Reader|yes|
|VM|0%|
</details><details><summary>Extensions (39)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-javascript-repl|ach|0.7.4
emojisense|bie|0.10.0
markdown-mermaid|bie|1.19.0
vscode-tailwindcss|bra|0.9.13
vscode-modelines|chr|2.0.6
path-intellisense|chr|2.8.4
vscode-css-modules|cli|0.5.1
postcss|css|1.0.9
vscode-eslint|dba|2.4.2
gitlens|eam|14.2.1
EditorConfig|Edi|0.16.4
prettier-vscode|esb|10.1.0
vscode-jest-runner|fir|0.4.66
todo-tree|Gru|0.0.226
svg|joc|1.5.3
vscode-peacock|joh|4.2.2
auto-comment-blocks|kev|1.0.1
graphql-for-vscode|kum|1.15.3
node-module-intellisense|lei|1.5.0
vscode-language-babel|mgm|0.0.39
vscode-scss|mrm|0.10.0
playwright|ms-|1.0.15
vscode-typescript-next|ms-|5.3.20230817
vsliveshare|ms-|1.0.5877
indent-rainbow|ode|8.3.1
quicktype|qui|12.0.46
LiveServer|rit|5.7.9
vscode-javascript-booster|sbu|14.0.1
vscode-standard|sta|2.1.3
rewrap|stk|1.16.3
move-ts|str|1.12.0
vscode-status-bar-format-toggle|tom|3.1.1
vscode-mdx|uni|1.4.0
vscode-sort-package-json|uni|1.5.0
intellicode-api-usage-examples|Vis|0.2.7
vscode-icons|vsc|12.5.0
pretty-ts-errors|yoa|0.5.1
markdown-all-in-one|yzh|3.5.1
material-theme|zhu|3.16.0

(7 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
vsccc:30803844
282f8724:30602487
89544117:30613380
showlangstatbar:30737416
03d35959:30757346
7ij38806:30736111
pythonfmttext:30731395
pythoncmv:30756943
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
gsofb:30804716
pythonnosmt12:30797651
pythonidxptcf:30805731
pythonnoceb:30805159
dsvsc013:30795093
dsvsc014:30804076
diffeditorv1:30812748

```

</details>

**Comment by lramos15** [comment]
This has been fixed in insiders
https://code.visualstudio.com/insiders/

**Comment by yashsway** [comment]
awesome, thank you for the heads up!
