### ISSUE TITLE
It does not work on Mountain Lion

### ISSUE THREAD

**Issue by inigosola** [Microsoft/vscode#1907]
VSCODE crashes when I try to run it on Mountain Lion

**Comment by rhires** [comment]
While the system requirements are not front and center, they are listed, and the minimum version for Mac OS X is Yosemite. So, it won't work on Mountain Lion. See https://code.visualstudio.com/docs/supporting/requirements for more details.

**Comment by inigosola** [comment]
I would like to support mountain lion, VSCODE is a text editor, it is not an IDE. I think it is very important support old machines.

How I can help about this issue?

**Comment by joaomoreno** [comment]
@chrisdias ping

**Comment by chrisdias** [comment]
@inigosola thanks for you interest in VS Code!  We currently don't have plans to look into this as the version of OSX is a few years old now.  

However, given your passion for Mountain Lion, we are happy to look at Pull Requests to fix issues. To get started, you can clone and attempt to [build and run VS Code locally](https://github.com/Microsoft/vscode/wiki/How-to-Contribute) and then start to investigate bugs that are blocking on Mountain Lion. If you can submit issues, or better yet fixes in PRs, we'll be happy to look at them.

**Comment by inigosola** [comment]
I have read https://github.com/Microsoft/vscode/wiki/How-to-Contribute but I cant build anything (I have received no error), I dont see vscode app anywhere.

**Comment by chrisdias** [comment]
@inigosola when you run `./scripts/code.sh` what happens, anything?

**Comment by inigosola** [comment]
```
./scripts/code.sh
[07:53:50] Using gulpfile /Volumes/v1/vscode/gulpfile.js
[07:53:50] Starting 'electron'...
[07:53:51] Finished 'electron' after 40 ms
Received signal 11 SEGV_MAPERR 000000000000
 [0x000109b241a7]
 [0x7fff8901490a]
 [0x7fff8482c63e]
 [0x000109a14b40]
 [0x00010a00ddd3]
 [0x00010a0135dc]
 [0x00010a00d5c7]
 [0x000109f974dc]
 [0x000109f96b36]
 [0x00010999c84d]
 [0x000109998e56]
 [0x7fff899587e1]
```
