### ISSUE TITLE
Terminal doesn't honor quoted command lines.

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#19078]
## VSCode Version: Windows.

-create a new terminal with the following shell args
![capture](https://cloud.githubusercontent.com/assets/1931590/22220218/149cfa86-e1ae-11e6-9c47-1ac8ed995532.png)

Executing this on a folder that contains a folder `test folder` results in the following error message:
```
The system cannot find the file specified.
```
Using the following args (observer the additional quote around the command) results in the same error

![capture](https://cloud.githubusercontent.com/assets/1931590/22220398/d44eecc2-e1ae-11e6-8298-ec3206314b52.png)

Executing this in a command shell (cmd.exe) works:

![capture](https://cloud.githubusercontent.com/assets/1931590/22220431/f3f2bc70-e1ae-11e6-92f9-0ded88c58fdf.png)

As does on powershell (without the extra double quotes):

![capture](https://cloud.githubusercontent.com/assets/1931590/22220464/1bcd33c4-e1af-11e6-9905-ef0470194351.png)

**Comment by dbaeumer** [comment]
Could it be that the command line somehow get changed / corrupted until it is passed to the cmd.exe process.

**Comment by Tyriar** [comment]
I'm guessing this is an issue with the [`argvToCommandLine`](https://github.com/Tyriar/node-pty/blob/a3416484232c1d830f56a2d18f2ffdb15d19d849/src/windowsPtyAgent.ts#L94) function in node-pty.

**Comment by dbaeumer** [comment]
Could be, but please note that I pass one arg for the command line. So instead of ["dir", "test folder"] which would need proper escaping I pass ["\"dir \"test folder\"\""] which is exactly one arg and already proper escaped.

**Comment by dbaeumer** [comment]
I inspected the cmd.exe's command line when spawned and it looks like this (removed /c to keep it alive)

![capture](https://cloud.githubusercontent.com/assets/1931590/22255679/62b2559a-e258-11e6-9581-c438293aa892.png)

Looks like some double quotes got escaped :-)

**Comment by dbaeumer** [comment]
Actually I didn't quote the command correctly. It should be quoted `dir "test folder"` so the JS string in debugger looks like `"dir \"test folder\""`. Passing this to the terminal still results in \ characters on the command line:

![capture](https://cloud.githubusercontent.com/assets/1931590/22257793/628bbcbc-e25f-11e6-87ae-62ce5975e4ae.png)

Executing `cmd.exe /d /k dir "test folder"` from a powershell command prompt results in 

![capture](https://cloud.githubusercontent.com/assets/1931590/22257848/901db892-e25f-11e6-973e-0eec695f0b95.png)

which looks correct (no \ to escape ")

**Comment by Tyriar** [comment]
I think I can reproduce this in node-pty by running the following:

```js
var os = require('os');
var pty = require('..');

var ptyProcess = pty.spawn('cmd.exe', ['/c', 'dir "a b"'], {
  name: 'xterm-color',
  cols: 80,
  rows: 30,
  cwd: "C:\\Users\\daimms\\Documents",
  env: process.env
});

ptyProcess.on('data', function(data) {
  console.log(data);
});

setTimeout(ptyProcess.kill.bind(ptyProcess), 5000);
```

Output:

```
C:\Users\daimms\Documents\dev\Tyriar\node-pty>node .\demo\quotes_commands_demo.js
The system cannot find the file specified.

C:\Users\daimms\Documents>dir "a b"
 Volume in drive C is OSDisk
 Volume Serial Number is 34DE-8099

 Directory of C:\Users\daimms\Documents\a b

02/24/2017  12:20 PM    <DIR>          .
02/24/2017  12:20 PM    <DIR>          ..
02/24/2017  12:20 PM    <DIR>          test
               0 File(s)              0 bytes
               3 Dir(s)  72,050,741,248 bytes free
```

A similar example however works fine on Linux using `pty.spawn('bash', ['-c', 'ls "a b"'], ...`

**Comment by Tyriar** [comment]
Fixed upstream https://github.com/Tyriar/node-pty/issues/41, still want to verify it within VS Code before pushing it.

**Comment by Tyriar** [comment]
@dbaeumer this should be good to go now, you'll want to update node_modules/node-pty and then set `IShellLaunchConfig.args` as a `string` that will be used as is. Example:

```ts
const config: IShellLaunchConfig = {
  executable: 'cmd.exe',
  args: '/d /c "dir "test folder""'
};
```

Let me know if you have any issues.

**Comment by dbaeumer** [comment]
@Tyriar why is the string option only supported under Windows. You need to escape under Mac and Linux as well. Under these OSes there are even three different kind of space escapings so the code can't simply take one (see http://wiki.bash-hackers.org/syntax/quoting). IMO we need to let users control this.

**Comment by Tyriar** [comment]
@dbaeumer I was under the impression this only really applies to cmd/Windows.

> As node-pty presents an Unix-like interface to conlole applications, it should also provide a unix-like argv[] calling mechanism instead of windows-like escape-Commandline-yourself way. Therefore the Commandline should be build in a way, that matches those rules.

From https://github.com/Tyriar/node-pty/issues/41#issuecomment-283022207

Do you have a particular use case that fails in `sh` on macOS or Linux?

**Comment by dbaeumer** [comment]
@Tyriar may be I am not understanding it correctly but here is what I like to allow users do to for an example to run a command in a shell that takes args with spaces in it:

`command  dirk\ baeumer`: escpae using \ for a single space
`command "dirk baeumer"`: escape using weak quoting
`command 'dirk baeumer'` : escape using strong quoting

How would I pass such a command line to a shell I start.

**Comment by Tyriar** [comment]
Aren't they all basically the same thing? Is there a reason for using anything other than `["dirk baeumer"]`? That's all the terminal shell/shellArgs support and I haven't seen any complaints so far.

**Comment by dbaeumer** [comment]
According to http://wiki.bash-hackers.org/syntax/quoting " and ' have a very different semantic. 

So is there a way for me to pass args and tell the shell to not do any quoting. So if I pass `ls -ls 'dirk baeumer'` will it respect the quoting and leave the string untouched?

**Comment by Tyriar** [comment]
Is this what you mean?

![image](https://cloud.githubusercontent.com/assets/2193314/24368533/9ae82a0e-12d5-11e7-8e49-12edd0d92f4a.png)

Force `waitOnExit` in dev build.

Add this to settings.json:

```ts
    "terminal.integrated.shell.linux": "/bin/bash",
    "terminal.integrated.shellArgs.linux": [
    "-c",
    "ls -ls 'a b'"
    ]
```

![image](https://cloud.githubusercontent.com/assets/2193314/24368564/befdfef0-12d5-11e7-824d-23b902eb0bef.png)

**Comment by dbaeumer** [comment]
Yes. So how would I pass this to a shellLaunchConfig in code in terms of args? Like this: ["-c", "ls -ls 'a b'"] and not one string args like under Windows ?

**Comment by Tyriar** [comment]
Yes, `terminal.integrated.shell.linux` and `terminal.integrated.shellArgs.linux` map 1:1 to the `IShellLaunchConfig.executable` and `.args`

**Comment by dbaeumer** [comment]
@Tyriar thanks!
