### ISSUE TITLE
Settings Sync

### ISSUE THREAD

**Issue by zgaxddnhh** [microsoft/vscode#190724]
Type: <b>Bug</b>

i can't find ‘Settings Sync: Show Synced Data’ button. 

![image](https://github.com/microsoft/vscode/assets/40316182/08e4c236-3a44-4df6-b018-29c79d1f0145)

**Comment by gjsjohnmurray** [comment]
I think you need to run that as a command in the Command Palette (F1).

**Comment by zgaxddnhh** [comment]
> I think you need to run that as a command in the Command Palette (F1).

Thank you for your answer.
yeh, i use Command Palette(F1), there is no 'Settings Sync: Show Synced Data'.
![image](https://github.com/microsoft/vscode/assets/40316182/53656e52-26b3-4c94-ad4c-702c010b8e4c)

**Comment by gjsjohnmurray** [comment]
Does the "Configure..." command confirm that you are syncing some categories?

Does the "Show Log" command show any activity?

Does the context menu of the Accounts button at the bottom of the Activity Bar show that you are logged in?

**Comment by zgaxddnhh** [comment]
Thanks. I don't use Configure,now i have finding 'Settings Sync: Show Synced Data'.

**Comment by gjsjohnmurray** [comment]
Good. Please close the issue.

**Comment by zgaxddnhh** [comment]
ok! Thank you.
