### ISSUE TITLE
filepath links with '~' expand $USER instead of $HOME

### ISSUE THREAD

**Issue by thisiswhereitype** [microsoft/vscode#190770]
### Applies To

- [X] Notebooks (.ipynb files)
- [ ] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

![image](https://github.com/microsoft/vscode-jupyter/assets/17139430/76d38a04-a09c-4bda-af6b-25af7a40f144)
Then:
![image](https://github.com/microsoft/vscode-jupyter/assets/17139430/45cd1a07-3fb3-4a99-b43b-8cb49931f680)

### VS Code Version

Version: 1.81.1 (user setup) 

### Jupyter Extension Version

v2023.7.1002162226

### Running Jupyter locally or remotely?

Remote

**Comment by amunger** [comment]
this looks like a general issue - run a cell with `print('~/test.txt')`
the link will attempt to open /$USER/text.txt

**Comment by amunger** [comment]
verification steps
1. open a remote connection in vscode to a linux machine
2. create a file in your home directory `touch ~/test.txt`
3. run a cell with print('~/test.txt')
4. click the link in the cell output and verify it opens the correct file
