### ISSUE TITLE
Black Screen On Terminal

### ISSUE THREAD

**Issue by CaoAMinh** [microsoft/vscode#190834]
Type: <b>Bug</b>

After an update recently, when I re-open VS-Code, I no longer see the text in the terminal in the screen anymore, only black screen and the cursor (I still can type inside it)

VS Code version: Code 1.81.1 (6c3e3dba23e8fadc360aed75ce363ba185c49794, 2023-08-09T22:22:42.175Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 5600H with Radeon Graphics          (12 x 3294)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|7.36GB (1.41GB free)|
|Process Argv|--crash-reporter-id 2f03a13d-f2e1-471f-8522-918d5f4bc317|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
composer-php-vscode|DEV|1.37.13534
phptools-vscode|DEV|1.37.13534
profiler-php-vscode|DEV|1.37.13534
es7-react-js-snippets|dsz|4.4.3
vscode-react-native|msj|1.11.2
java|red|1.21.0
LiveServer|rit|5.7.9
es7-react-js-snippets|rod|1.9.3
intellicode-api-usage-examples|Vis|0.2.7
vscodeintellicode|Vis|1.2.30
vscode-java-debug|vsc|0.53.0
vscode-java-dependency|vsc|0.23.1
vscode-java-pack|vsc|0.25.13
vscode-java-test|vsc|0.39.1
vscode-maven|vsc|0.42.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
vsccc:30803844
282f8724:30602487
f6dab269:30613381
vscrp:30673768
showlangstatbar:30737416
a2ce3375:30757347
pythonfmttext:30731395
pythoncmvfstrcf:30756944
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
gsofb:30804716
pythonnosmt12:30797651
pythonidxpt:30805730
pythonnoceb:30805159
dsvsc013:30795093
dsvsc014:30804076
diffeditorv1:30812748

```

</details>

```[tasklist]
### Tasks
```

**Comment by CaoAMinh** [comment]
![image](https://github.com/microsoft/vscode/assets/99648604/76b2d2a2-b6e6-46b7-8300-61334a1f07ee)

**Comment by gjsjohnmurray** [comment]
Maybe suggestions in https://github.com/microsoft/vscode/issues/187198 will help you.
