### ISSUE TITLE
Test: Go To Implementation

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#19086]
OS: 
- [x] any @egamma 
- [x] any @kieferrm 

Complexity: 2

1. Create a new TS project with a `main.ts` of:
```ts
interface Foo {
    abc(): number
}

class Bar implements Foo {
    abc() {
        return 2;
    }
}

class Car implements Foo {
    abc() { return 2; }
}
```
1. In the TS file, ensure that the `go to implementation` commands do not show up. (They should not be enabled for TS 2.1.5)
1. Create a `package.json`: `$ npm init -y`
1. Install TS 2.2 next using `$ npm install typescript@next`
1. Point the `typescript.tsdk` setting to the local typescript install.
1. Reload the window.
1. Open the TS file again.
1. Select `Foo` in  `interface Foo` and run `go to implementation`
    -  ⭐️ A peek window with two implementations should show up, one for `Bar` and one for `Car`
1. Try the same with the method `abc` in the interface definition

**Comment by kieferrm** [comment]
Tested on macOS.
