### ISSUE TITLE
Unchecking Extensions when copying an existing profile into a new one behaves unexpectedly

### ISSUE THREAD

**Issue by abstractionmage** [microsoft/vscode#190827]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.81.1
- VS Code Insiders Version: 1.82.0-insider
- OS Version: Arch linux (rolling)

Steps to Reproduce:

1. Install any extension (if you don't already have one installed)
2. Click on the Settings button in the bottom left corner of the application, select "Profiles" -> "Create Profile"
3. In the "Copy from" field, select the profile you are currently on (most liekly "Default")
4. In the "Choose what to configure in your Profile" list, uncheck "Extensions"
5. Give your new profile a name and click "Create"

Expected behavior:

- VSCode creates and switches to a new profile with no extensions installed/enabled

Actual behavior:

- VSCode creates and switches to a new profile in which all previously installed and enabled extensions are also installed and enabled.

Gif screencast of the bug in action:
![extensions and profiles](https://github.com/microsoft/vscode/assets/37195767/5f3c3fcf-9166-4b0f-abd8-1e3365b431be)

**Comment by gjsjohnmurray** [comment]
When you clear the Extensions checkbox (or any on the Create New Profile picker, a message appears alongside to tell you that by unselecting this the new profile will always have the same extensions as the Default profile.

If you want your profile to have an independent set of extensions (even none), leave the checkbox set when you create the profile, or use Edit Profile to set it later. Then disable some/all extensions from Extensions view or Command Palette.

**Comment by abstractionmage** [comment]
Ah yeah I didn't see that. But even if it's not a software bug I still find the checkbox element intuitively misleading, as it visually conveys the message "Copy extensions or not", not "Copy extensions from this profile or the default profile". 
I'm not a UI/UX designer but I believe a different design element may be better suited to convey the intended message.

**Comment by sandy081** [comment]
Unchecking will cause it to fallback to default profile. I would wait for more feedback before changing anything here.
