### ISSUE TITLE
Gulp task detection failed

### ISSUE THREAD

**Issue by geniuszxy** [microsoft/vscode#190833]
Type: <b>Bug</b>

I have a gulpfile.js in the root folder, it has a simple copy task shown in the screenshot.
When I clicked Terminal > Configure Tasks..., vscode failed to detect the task and showed some messy characters in the output window.
My default system code page is 936, I guess this could be the issue, but I don't know how to change the output encoding of that window (or the extension?).

![gulpmessy](https://github.com/microsoft/vscode/assets/2471200/902ae03d-f84a-400d-a416-794bfac97604)

VS Code version: Code 1.81.1 (6c3e3dba23e8fadc360aed75ce363ba185c49794, 2023-08-09T22:22:42.175Z)
OS version: Windows_NT x64 10.0.19045
Modes:

**Comment by geniuszxy** [comment]
I think I already know the problem because I did not add the nodejs user directory to PATH. This detection plugin should attempt to run the `gulp` command, and the shell tells it that it cannot find the executable. The plugin then prints the error to the output window. The error was in Chinese, resulting in messy characters.

I still want to know how to solve the problem of messy characters, after all, I can't always rely on guessing to fix problems.

**Comment by meganrogge** [comment]
that error message and output is coming from the gulp extension, so pls create an issue for them.

**Comment by geniuszxy** [comment]
@meganrogge it's a builtin extension, I see the publisher is vscode, could you tell me which repository should I create an issue for?

**Comment by meganrogge** [comment]
I believe this is already fixed, can you see if you can reproduce in the [Insiders build](https://code.visualstudio.com/insiders)?
/label info-needed

**Comment by geniuszxy** [comment]
@meganrogge yes I can.

![not-fixed](https://github.com/microsoft/vscode/assets/2471200/0ac228f7-4b42-480a-bb03-377be7e526b9)

Version: 1.84.0-insider
Commit: 18b7f75a9fab40499744c2e9c6ba9af64d5c6744
Date: 2023-10-25T05:35:48.331Z
Electron: 25.9.2
ElectronBuildId: 24603566
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.19044
