### ISSUE TITLE
Not able to open workspace

### ISSUE THREAD

**Issue by bsptim** [microsoft/vscode#190842]
![VS Code access error](https://github.com/microsoft/vscode/assets/72366579/71086fce-ec12-4702-8538-1b03ef22205c)
Trying to open a workspace just created.  Getting this error message and cannot go any further.

Version: 1.81.1
Commit: 6c3e3dba23e8fadc360aed75ce363ba185c49794
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36
Embedder: codespaces

**Comment by bpasero** [comment]
Sounds like a Codespaces issue to me, please open a thread at https://github.com/orgs/community/discussions/categories/codespaces

**Comment by bsptim** [comment]
Thanks Benjamin.  Yes, it was a Codespaces issue, and it seems to have cleared itself up.

Tim G.
