### ISSUE TITLE
improper escaping in Markdown preview

### ISSUE THREAD

**Issue by af4jm** [microsoft/vscode#190804]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 
- OS Version: 

Steps to Reproduce:

1. I have a block of HTML in a Markdown file (using elements that don't have MD equivalents), a sample that represents the issue is...

``` html
<details><summary>Jackson Motorplex</summary>
<code>[![Google Maps](/icons/google_maps.png)](https://www.google.com/maps/@?api=1&map_action=map&basemap=satellite&center=43.6275351,-94.9760521)</code>
</details>
```

2. In the Markdown preview, `&center` is incorrectly rendered as `¢er`, that rendering should only happen if the html were `&cent;er` HTML escape sequences that do not end with `;` should be ignored, especially when there are other alphabetic characters immediately following

I notice the same issue in FireFox with a local html file, so it is likely an issue in a dependency, not in VSCode itself. In both cases (VSCode & FF), this escaping was not happening a few days ago.

**Comment by mjbvz** [comment]
> I notice the same issue in FireFox with a local html file

This means that it's not an issue with VS Code. It also seems unrelated to markdown and it happens in other browsers too so I'm guessing it's the expected behavior for html
