### ISSUE TITLE
Editor group resizing still available after closing all groups but one.

### ISSUE THREAD

**Issue by ackvf** [microsoft/vscode#190809]
Type: <b>Bug</b>

I can consistently reproduce this behavior with this repo even after VSCode restart.
I could not find a way to reproduce it in a clean VSCode or in another repository. I tried tinkering with the editor groups, resizing them, closing vscode, reopening and I could not reproduce it.

I am happy to share my screen during an online session if you want, since I could not reproduce it outside of this repo.

Double clicking the editor name will not maximize the editor group as it is perhaps already considered maximized.

https://github.com/microsoft/vscode/assets/2313018/76055a84-55d9-4309-88d0-7fb29c73bac1

VS Code version: Code 1.81.1 (6c3e3dba23e8fadc360aed75ce363ba185c49794, 2023-08-09T22:22:42.175Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz (8 x 2803)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.71GB (12.37GB free)|
|Process Argv|C:\\Users\\Qwerty\\repos\\CXIP\\cxip-core-web --crash-reporter-id e177b269-931e-4cfd-8c2c-bc1dce7bd867|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (92)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-css-formatter|aes|1.0.2
Bookmarks|ale|13.4.1
copy-relative-path|ale|0.0.2
vscode-styled-jsx-languageserver|And|1.0.1
svelte-intellisense|ard|0.7.1
jsdoc-markdown-highlighting|bie|0.0.1
vscode-styled-jsx|bla|2.1.1
vscode-tailwindcss|bra|0.9.13
simple-react-snippets|bur|1.2.7
npm-intellisense|chr|1.4.4
path-intellisense|chr|2.8.4
js-codeformer|cms|2.6.1
jsrefactor|cms|3.0.1
codesandbox-projects|Cod|0.2.94
bracket-pair-colorizer-2|Coe|0.2.4
dscodegpt|Dan|2.1.15
vscode-eslint|dba|2.4.2
vscode-quick-select|dba|0.2.9
overtype|DrM|0.5.0
es7-react-js-snippets|dsz|4.4.3
gitlens|eam|14.2.1
EditorConfig|Edi|0.16.4
prettier-vscode|esb|10.1.0
vscode-svelte-snippets|fiv|0.5.0
vscode-sql-template-literal|for|0.1.0
codespaces|Git|1.14.15
copilot|Git|1.104.341
copilot-chat|Git|0.6.0
copilot-labs|Git|0.14.884
remotehub|Git|0.60.0
vscode-pull-request-github|Git|0.70.0
gc-excelviewer|Gra|4.2.58
vscode-graphql|Gra|0.8.17
vscode-graphql-execution|Gra|0.2.4
vscode-graphql-syntax|Gra|1.2.2
todo-tree|Gru|0.0.226
realtime-debugging|hed|0.1.0
vscode-drawio|hed|1.6.6
vscode-settings-cycler|hoo|1.0.1
error-gutters|Igo|1.0.1
search-editor-apply-changes|jak|0.1.1
relativepathrefactor|jak|0.9.0
jbockle-format-files|jbo|3.4.0
svg|joc|1.5.3
solidity|Jua|0.0.165
rainbow-csv|mec|3.7.0
git-graph|mhu|1.30.0
dotenv|mik|1.0.1
vscode-open-in-sublime-merge|mor|0.6.0
vscode-docker|ms-|1.26.0
autopep8|ms-|2023.6.0
isort|ms-|2023.10.1
python|ms-|2023.14.0
vscode-pylance|ms-|2023.8.30
jupyter|ms-|2023.7.1002162226
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.17
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-slideshow|ms-|0.1.5
remote-containers|ms-|0.304.0
remote-ssh|ms-|0.105.2023080715
remote-ssh-edit|ms-|0.86.0
remote-wsl|ms-|0.81.0
vscode-remote-extensionpack|ms-|0.24.0
azure-repos|ms-|0.36.0
remote-explorer|ms-|0.5.2023071709
remote-repositories|ms-|0.38.1
remote-server|ms-|1.4.0
vscode-js-profile-flame|ms-|1.0.5
vsliveshare|ms-|1.0.5877
color-highlight|nau|2.5.0
abracadabra|nic|8.1.4
vscode-versionlens|pfl|1.5.2
material-icon-theme|PKi|4.29.0
tsimporter|pmn|2.0.1
polacode|pnp|0.3.4
ethereum-remix|Rem|0.0.12
LiveServer|rit|5.7.9
multi-command|ryu|1.6.0
vscode-csstree|sme|1.1.0
code-spell-checker|str|2.20.5
svelte-vscode|sve|107.10.0
language-stylus|sys|1.16.0
json-utils|ted|1.0.8
errorlens|use|3.13.0
transpose|v4r|0.0.6
vscode-wakatime|Wak|24.2.1
vscode-import-cost|wix|3.3.0
pretty-ts-errors|yoa|0.5.1
markdown-all-in-one|yzh|3.5.1
sort-js-object-keys|zen|1.0.6
vscode-open-in-github|ziy|1.3.6

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
py29gd2263:30792226
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
vscccc:30803845
2e4cg342:30602488
89544117:30613380
showlangstatbar:30737416
03d35959:30757346
7ij38806:30736111
pythonfmttext:30731395
pythoncmvfstrcf:30756944
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
gsofb:30804716
pythonnosmt12:30797651
pythonidxptcf:30805731
pythonnoceb:30805159
dsvsc013:30795093
dsvsc014:30804076
diffeditorv2:30812749

```

</details>

**Comment by ackvf** [comment]
I suspect that it might have something to do with these changes, because I have not observed this behavior before https://github.com/microsoft/vscode/issues/187431

**Comment by bpasero** [comment]
You seem to be in editor Zen mode in that workspace?

<img width="501" alt="image" src="https://github.com/microsoft/vscode/assets/900690/11147006-a09e-444e-a38b-d0dc73b77bd3">

**Comment by ackvf** [comment]
I never used these modes and I am not in a Zen Mode, but I am in a "Centered Layout"?
![image](https://github.com/microsoft/vscode/assets/2313018/787a4849-beaa-4b9d-afba-89978270e0aa)

**Comment by ackvf** [comment]
Yep, that's it. Thank you. I don't even know what that is and how it got turned on. Disabling it fixed my "issue". Thank you for solving my mystery.

**Comment by ackvf** [comment]
What puzzles me though, is why it would only behave like this in this particular repo and not anywhere else. I don't have this anywhere in the settings.
