### ISSUE TITLE
Suggest doesn't work in presence of inline suggest even with "suppress suggestions" disabled

### ISSUE THREAD

**Issue by ulugbekna** [microsoft/vscode#190882]
# Description

Suggest/completion isn't offered when there's an inline suggestion. Disabling the extension offering the inline suggestions fixes the problem. 

https://github.com/microsoft/vscode/assets/16353531/884f33e1-b068-461d-8c2c-7551314b2f9a

# Version 

```
Version: 1.82.0-insider
Commit: f125afbc800ec611f5a9ab1333c769832ce424b3
Date: 2023-08-21T05:34:23.256Z
Electron: 25.5.0
ElectronBuildId: 23084831
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Darwin arm64 22.6.0
```

**Comment by hediet** [comment]
/duplicate If copilot sets the flag, it overrides the setting. However, we just removed the flag, so this should be fixed. This also has been reported in some other issue.

**Comment by hediet** [comment]
See here: https://github.com/microsoft/vscode/issues/131940#issuecomment-1686181564
