### ISSUE TITLE
I can't sigin by github account 

### ISSUE THREAD

**Issue by hickeyhub** [microsoft/vscode#190884]
Type: <b>Bug</b>

the following log prompt me network error ,but  I can visit  github.com by brower:

GitHub Copilot could not connect to server. Extension activation failed: "network error"

VS Code version: Code 1.81.1 (Universal) (6c3e3dba23e8fadc360aed75ce363ba185c49794, 2023-08-09T22:20:33.924Z)
OS version: Darwin arm64 22.6.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|4, 9, 5|
|Memory (System)|16.00GB (5.90GB free)|
|Process Argv|--crash-reporter-id 39ce8627-fc7b-4073-937b-9ad9240c3262|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
npm-intellisense|chr|1.4.4
gitlens|eam|14.2.1
EditorConfig|Edi|0.16.4
prettier-vscode|esb|10.1.0
auto-rename-tag|for|0.1.10
code-runner|for|0.12.0
shell-format|fox|7.2.5
copilot|Git|1.105.350
copilot-chat|Git|0.6.0
vetur|oct|0.37.3
vscode-css-navigation|puc|1.13.3
LiveServer|rit|5.7.9
sass-indented|syl|1.8.27

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscoreces:30445986
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
py29gd2263cf:30792227
vscaac:30438847
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
vscccc:30803845
3biah626:30602489
f6dab269:30613381
2i9eh265:30646982
showlangstatbar:30737416
03d35959:30757346
pythonfmttext:30731395
pythoncmv:30756943
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
gsofa:30804715
pythonnosmt12:30797651
pythonidxpt:30805730
pythonnoceb:30805159
dsvsc013:30795093
dsvsc014:30804076
diffeditorv2:30812749

```

</details>

**Comment by chrmarti** [comment]
Are you behind a network proxy?

**Comment by hickeyhub** [comment]
> 
I am not use a network proxy,

**Comment by hickeyhub** [comment]
> Are you behind a network proxy?

i'm not useing any,    on the browser devTool's network panel would look like this...

<img width="1512" alt="image" src="https://github.com/microsoft/vscode/assets/27677166/c97f61de-5849-446e-aeca-591d32cfc0a4">

**Comment by chrmarti** [comment]
Make sure that any corporate firewall allows outgoing connections to the hostnames listed here: https://code.visualstudio.com/docs/setup/network#_common-hostnames

**Comment by hickeyhub** [comment]
> Make sure that any corporate firewall allows outgoing connections to the hostnames listed here: https://code.visualstudio.com/docs/setup/network#_common-hostnames

in fact, in corp netork everythin is fine, in home network  I can't use copilot,
