### ISSUE TITLE
RPM package has incomplete list of dependencies

### ISSUE THREAD

**Issue by mattzink** [Microsoft/vscode#19087]
- VSCode Version: 1.8.1
- OS Version: CentOS 7.3 (x64)

Steps to Reproduce:

1. Install CentOS 7.3 minimal ISO to a new VM
2. sudo yum install code-1.8.1-1482158209.el7.x86_64.rpm
3. code .

Expected:
VS Code to start

Actual:
VS Code crashes, saying it cannot find libgtk-2.0.so
I then manually installed the "gtk2" rpm to meet the missing dependency.

VS Code still crashes, saying it cannot find libXtst.so.
I installed the "libXtst" rpm

VS Code still crashes, saying it cannot find libgconf-2.0.so
I installed the "GConf2" rpm

VS Code starts, but immediately and silently exits. Running with the --verbose option eventually points to a failure to locate a "sans" font.

I installed the "gnu-free-sans-fonts" rpm
VS Code successfully starts and is operational.

So it seems like the above 4 packages should be added as package dependencies, to avoid the user having to manually find/install additional packages.

**Comment by mousetraps** [comment]
Thanks for reaching out! Interestingly, it seems that all four of those packages appear in [dependencies.json](https://github.com/Microsoft/vscode/blob/master/resources/linux/rpm/dependencies.json), so not sure what's up. @Tyriar, any ideas?

**Comment by Tyriar** [comment]
This is fixed Insiders, coming in 1.9.0 😄 https://github.com/Microsoft/vscode/issues/17142
