### ISSUE TITLE
Poor UI for Search/Replace

### ISSUE THREAD

**Issue by FastieSystems** [microsoft/vscode#190835]
Type: <b>Feature Request</b>

Search/Replace has a poor UI, inconsistent behavior, and hidden features.

For reference, the best S/R UI I have used is from the discontinued product Expression Web 4.  If modeled after EW4, VSC's S/R would be much better.

I present a few poor behaviors here.

1. If a selection is made in code and Ctrl+F or Ctrl+H is pressed, the selected text is not always automatically inserted into the find field automatically. It should be.

2. When using Replace, tabbing between the search and replace fields should highlight the entire field.

3. I only recently came to the realization that VSC was remembering previous search and replace strings. That's because the UI has no intuitive controls for moving between them. Instead of choosing specific keystrokes to move up and down, the up- and down-arrows were overloaded, a poor practice. EW4 provides a dropdown for both the S&R fields that displays the last 15 strings for each.

You can examine EW4's S/R UI by downloading EW4 from https://www.oldergeeks.com/downloads/file.php?id=3571 or finding it at its last resting place on the WayBack machine.

Here is what the EW4 dialog looks like.

![EW4 Search and Replace Dialog](https://github.com/microsoft/vscode/assets/1882942/e4e5ccf1-3435-4f57-9e94-675050ac669c)
![EW4 Search and Replace Dropdown](https://github.com/microsoft/vscode/assets/1882942/74030927-478a-4bde-a1f0-565513f18b64)

VS Code version: Code 1.81.1 (6c3e3dba23e8fadc360aed75ce363ba185c49794, 2023-08-09T22:22:42.175Z)
OS version: Windows_NT x64 10.0.19045
Modes:

**Comment by goyalyashpal** [comment]
whst more, triggering "find/replace in selection" is also an unwieldy path

1. select whole text 
2. ctri + f (then enter iguess? will confirm tomorrow)
3. press alt + `l`
4. presh ctrl + f again
5. type text
6. press ctrl + h
7. ... proceed

**Comment by amunger** [comment]
> the selected text is not always automatically inserted into the find field automatically

check your `editor.find.seedSearchStringFromSelection` setting. If setting that to always doesn't always seed the find widget, please open a bug.

Dropdown for search history is covered in https://github.com/microsoft/vscode/issues/23099

And here is a related request to revamp the UI https://github.com/microsoft/vscode/issues/116827

**Comment by FastieSystems** [comment]
New information after experimentation: If the search text selected for find/replace contains a newline, the text will not be inserted into the find field. Otherwise, it will.
