### ISSUE TITLE
Tunnel - insider - stuck on Opening Remote...

### ISSUE THREAD

**Issue by ilteoood** [microsoft/vscode#190853]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: code-cli 1.82.0 (commit 501baeb5e07b5a404f862d922bacb93771d91331)
- OS Version: Docker image

Steps to Reproduce:

I've built [this Docker image](https://github.com/ilteoood/vscode-remote-tunnels) in order to deploy a remote vscode server instance on my Raspberry PI.

 The operations I do are:
- Create the container using the following compose file
```
version: "2"
configs:
services:
  vscode:
    image: ilteoood/vscode-remote-tunnels:insider
    container_name: vscode-remote-tunnels
    environment:
      - MACHINE_NAME=raspberry
    restart: unless-stopped
    dns:
      - 1.1.1.1
```
- Complete the authorization process;
- Try to access the VSCode instance using the provided link.

On the browser, VSCode is stuck to `Opening Remote...`, while the container doesn't display any other output.
These are the only logs I receive:
```
To grant access to the server, please log into https://github.com/login/device and use code ****-****
[2023-08-21 06:51:07] info Creating tunnel with the name: raspberry
[2023-08-21 06:51:08] info Adopting existing tunnel (ID=ID { cluster: "***", id: "********" })
Open this link in your browser https://insiders.vscode.dev/tunnel/raspberry/home/workspace
```

**Comment by connor4312** [comment]
Can you please open the browser devtools and share what you see in the Console?

**Comment by chtsai0105** [comment]
Please checkout this threads. https://github.com/microsoft/vscode-remote-release/issues/8864 It probably caused by the latest Remote tunnels update.
