### ISSUE TITLE
Batch set (or unset) multiple break-points based on a search-pattern

### ISSUE THREAD

**Issue by dimension-zero** [microsoft/vscode#190801]
I have a Python project that calls `logging.error()` frequently.  I'd like to be able to set (or un-set) a break-point on these calls all at once.
Find in Files lets me find the calls but then I have to set a breakpoint manually on each one.
This is very laborious and strikes me as a nice opportunity for automation.
It would be great to be able to automate batch setting (or unsetting) of breakpoints based on a search-pattern.

**Comment by gjsjohnmurray** [comment]
Are you able to use the [function breakpoints](https://code.visualstudio.com/docs/editor/debugging#_function-breakpoints) feature?

**Comment by dimension-zero** [comment]
> Are you able to use the [function breakpoints](https://code.visualstudio.com/docs/editor/debugging#_function-breakpoints) feature?

Very interesting - will investigate

**Comment by roblourens** [comment]
Or a normal breakpoint inside the function?

Otherwise an extension could also do this kind of thing
