### ISSUE TITLE
Can't install any plugin - SyntaxError: Unterminated string in JSON at position 49152

### ISSUE THREAD

**Issue by Nowaker** [microsoft/vscode#190813]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: any, including 1.81.1
- OS Version: Linux/irrelevant

Steps to Reproduce:

1. Garble `~/.vscode/extensions/extensions.json`
2. Try installing any plugin.

```
2023-08-19 15:08:46.940 [error] Unterminated string in JSON at position 49152: SyntaxError: Unterminated string in JSON at position 49152
    at JSON.parse (<anonymous>)
    at Object.factory (/opt/visual-studio-code/resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:82:84553)
```

I was getting this error for a day and looking at `sharedProcessMain.js:82:84553` wasn't very helpful since it's minified. But I figured out it's reading *something* so I started poking around `~/.vscode` and found my `extensions.json` is garbled. Basically, ENOSPACE must have caused the file to be garbled.

This issue is very hard to diagnose for a regular mortal. The log should indicate what file exactly it has an issue parsing at the very minimum.

**Comment by wyctorfogos** [comment]
Hi. It happens to me too. I cleared the extension.json file to make it recognizable again. I hope it helps you :)

**Comment by wyctorfogos** [comment]
Hi. It happens to me too. I cleared the extension.json file to make it recognizable again. I hope it helps you :)

**Comment by sandy081** [comment]
Can you please share the content of the `extensions.json` file ?

**Comment by Nowaker** [comment]
@sandy081 Take your own `extensions.json` and remove the `}` from the end, for example. Or remove half of the content of your `extensions.json`.

**Comment by Nowaker** [comment]
@sandy081 This happens when you hit `ENOSPC` and the unfortunate file that is affected by it is `extensions.json`. https://www.gnu.org/software/libc/manual/html_node/Error-Codes.html#index-ENOSPC

**Comment by sandy081** [comment]
This will be fixed by https://github.com/microsoft/vscode/issues/180695 - using atomic write feature. It will avoid writing partial data.

**Comment by Nowaker** [comment]
@sandy081 Thank you, much appreciated. I think that's probably half of the fix. The other half would be using one of defensive programming techniques to handle unexpected exceptions with friendly messages, e.g. if JSON is expected in a given file, and JSON won't parse, the error should indicate what file the invalid content came from. In current situation, when you see `SyntaxError: Unterminated string in JSON at position 49152`, the follow up questions are `Where did it come from?`.
