### ISSUE TITLE
Showing Theme and Font

### ISSUE THREAD

**Issue by kmurray24** [microsoft/vscode#190814]

**Comment by kmurray24** [comment]
We love our Themes and Fonts as creative developers.  We are obsessed actually!    
Please add what the current themem and font are being used at the bottome of the screen!  Or at least the option!   
Thanks!

**Comment by gjsjohnmurray** [comment]
https://marketplace.visualstudio.com/items?itemName=homiecoder.vscode-themeanager sounds like it might do what you want.

**Comment by kmurray24** [comment]
Thank you 🙏.  Fairly new to VS Code 👨‍💻

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by gjsjohnmurray** [comment]
Glad to help. Please close your issue.
