### ISSUE TITLE
✨ Auto sync config, extensions, keybindings, etc from base profile

### ISSUE THREAD

**Issue by jd-solanki** [microsoft/vscode#190856]
Hi 👋🏻 

Thanks so much for working on profiles. It's such time saver. I created several profiles all of them are created from my default profile. Later I added new keybinding to the default profile and there's no option to auto inherit these new keybinding to my other profiles.

## Solution

Provide syncing from base profile. If extended profile need to change the existing config it can get overriden at profile level and will discard the future syncs for that particular config.

## Workaround like extensions 
I did noticed there's option in extension where we can enable extension for all profiles but that doesn't existing in keybindings.

**Comment by tbontb-iaq** [comment]
Can something like inheritance or import be added?
```plain text
global
├── web dev
│ ├── vue
│ ├── react
│ └── vanilla
├── python
│ ├── data mining
│ └── deep learning
└── c/cpp
```
When adding a plugin to `global`, it means that a plugin is installed globally.
When certain settings are added in `web dev`, this applies to all web development.

**Comment by sandy081** [comment]
Please try this newly implemented enhancements in the profiles and file separate issue if you have any gaps - https://code.visualstudio.com/updates/v1_81#_support-for-partial-profiles

**Comment by jd-solanki** [comment]
Hi @sandy081 I'm already using partial profiles feature and create the profiles based on it. I guess you didn't get what I was trying to mean by syncing the base profile. I was trying to say similar to #191224

I created my profile "python" from profile "default" and got all the settings & keybindings from the "default" profile in "python" profile. I also created profile "dummy" for testing. Now, when I add new keybinding in "default" profile I want to get this **auto included** in "python" (child) profile via some kind of **sync or inherit feature** but this shouldn't get included in "dummy" profile (where I will disable syncing the base/partial profile).

I hope you got the idea. I kindly request you to reopen the issue 🙏🏻

**Comment by sandy081** [comment]
> ow, when I add new keybinding in "default" profile I want to get this auto included in "python" (child) profile via some kind of sync or inherit feature but this shouldn't get included in "dummy" profile (where I will disable syncing the base/partial profile).

In this case, you can create the "dummy" profile by copying the keybindings from the default profile instead of using the default profile always. Did you try this?

**Comment by jd-solanki** [comment]
@sandy081 Sorry if this is get more confusing but thing to focus is not "dummy" profile. It's about "default" profile & "python" profile. When I add new keybinding to "default" profile I want to automatically get that in "python" profile because "python" profile is based on "default" profile. I hope this is simplest form and you can understand what I'm trying to convey.

**Comment by sandy081** [comment]
> When I add new keybinding to "default" profile I want to automatically get that in "python" profile because "python" profile is based on "default" profile. 

This is exactly what partial profiles are for. If the python profile is configured to use the default profile for keybindings then you should get this behaviour.

![image](https://github.com/microsoft/vscode/assets/10746682/148ae29e-8f8a-4635-b0f9-935564947deb)

**Comment by jd-solanki** [comment]
@sandy081 Thanks for quick response and following up. Oh I see, We need to set "copy from" option to "None" and uncheck the keyboard shortcuts 👍🏻 

There's one thing still missing it if we want inherit everything from base config (by unchecking all the checkbox) we get warning:
![image](https://github.com/microsoft/vscode/assets/47495003/7323a5f2-73f5-49bc-bb7d-189e7fc72be3)

"default" profile will be my base profile where I store common things uncluding settnigs, keyboard shortcuts, etc. Later, I'll create language based profiles like "python", "vue", etc. With your suggestion I can auto inherit keyboard shortcuts but not all of them. (settings, shortcuts, snippets, tasks, extensions). Is there any way to inherit all of them?

**Comment by sandy081** [comment]
> Is there any way to inherit all of them?

There is not. This option does not makes sense because this is same as using default profile.

**Comment by sandy081** [comment]
As said, we do not support inheritance. So without inheritance this feature does not makes sense
