### ISSUE TITLE
Code command line add a --list-enabled-extensions

### ISSUE THREAD

**Issue by egamma** [microsoft/vscode#19083]
Currently you can only list all extensions. It would be useful to only list the enabled extensions.

**Comment by cleidigh** [comment]
@egamma 
trolling around for things to help out on... I think this is still open, I don't see it on the command line options yet.
Shall I do a PR on this ?

**Comment by bpasero** [comment]
This cannot be help wanted unless we provide SQLite storage access for CLI which is something to build with care.

**Comment by alteredorange** [comment]
Just ran into this problem, would love this feature, but I have no idea how to upvote this, do I do it here on this issue?

**Comment by Cinabutts** [comment]
This should've BEEN a thing since `--list-extensions` became a thing. ie `code --list-extensions --enabled` / `code --list-extensions --disabled` was first thing i tried expecting it to work lol
