### ISSUE TITLE
Variable substitution when no file is opened

### ISSUE THREAD

**Issue by anseki** [Microsoft/vscode#1908]
Common variables such as `${file}`, `${fileBasename}`, etc. in `*.json` files are handled wrongly when any files are not opened.
`${file}`, `${fileBasename}` and `${fileExtname}` are not replaced. `${fileDirname}` is replaced to `'.'`.

I think that these should be replaced to empty string (`''`) to let a command know that a target file is not specified, when any files are not opened.

**Comment by joaomoreno** [comment]
@dbaeumer I assume this is task related.

**Comment by anseki** [comment]
One of problems is that a command can't know that a passed argument means "no-file".  A task script such as `gulpfile.js` that is customized easily by user can check that, for example `arg !== '${file}'`. Others can't, and the command throws an error "${file} is not found".

If we can write `tasks` that are listed depending on the situation, it might be solved.
For example, I want to do `compass compile` only a file I am editing now:

```
{
  "version": "0.1.0",
  "command": "compass",
  "isShellCommand": true,
  "args": ["compile", "${workspaceRoot}"],
  "tasks": [
    {
      "context": "edit",          // This task is shown in list when a file is opened.
      "taskName": "compile this file",
      "args": ["${file}"],
      "suppressTaskName": true
    },
    {
      "context": "no-open",       // This task is shown in list when a file is not opened.
      "taskName": "compile all scss files",
      "args": [],
      "suppressTaskName": true
    }
  ]
}
```

**Comment by anseki** [comment]
If it's a possible, I hope that tasks are listed depending on the name of opened file also.
For example, a `context` property above accept `file:/\.md$/`. That is, this task is shown in the list only when markdown file is opened.

I wrote a small script to convert specified file to HTML and pass it to web browser.
We need previewing markdown, but we don't need HTML files (i.e. we don't need to save HTML files after checking these. and we don't need converting all markdown files at one time).
Therefore converting only a current opened markdown is useful.

**Comment by dbaeumer** [comment]
This got already addressed. Closing.
