### ISSUE TITLE
Test: Markdown Editor Document Link Provider

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#19089]
OS
- [x] Windows @dbaeumer 
- [x] any @mousetraps 

Complexity: 1

1. Clone and open the VSCode-docs repo: https://github.com/Microsoft/vscode-docs
1. Open a markdown file.
1. Look for a link of the format `[link text](path/file.ext)`
1. Hover over the `path/file.ext` part of the link.
     - ⭐A blue underline should appear under the link along with a message about ctrl-clicking the link
1. Try ctrl clicking the link
     - ⭐If the link is a local link, it should open that file in the editor. Links of the form `./path` or `path` should resolve to a path relative to the current file. Links of the form `/path` should resolve relative to the current workspace

**Comment by dbaeumer** [comment]
Looks good to me: one think I noticed which is different than the description but I thought it is the better behavior: hovering over a link doesn't turn it blue right away. It gets blue when Ctrl is pressed. 

![cast](https://cloud.githubusercontent.com/assets/1931590/22242432/a96f1d7c-e223-11e6-8a35-7c6317f777da.gif)

**Comment by mjbvz** [comment]
@dbaeumer Thanks.

Yes, this is the expected behavior for links inside documents. They should behavior the same as other links inside of documents. If you notice some discrepancy, please let me know
