### ISSUE TITLE
Test: Markdown Preview -> Editor Scroll Sync

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#19082]
- [x] Any OS @mousetraps 
- [x] Any OS @alexandrudima 

Complexity: 2

1. Clone and open the VSCode-docs repo: https://github.com/Microsoft/vscode-docs
1. Open a markdown file.
1. Preview the file 
1. Scroll the markdown preview and scroll around. (on top of the editor, not to the side)
1. Switch back to editor
    -  ⭐️ The editor should not have been scrolled.
1. Move the preview to a side tab so that both it and the editor are showing.
1. Scroll the preview
    -  ⭐️ When the preview is scrolled, the top of the editor is synchronized with the top of the preview. Make sure to scroll over images and other elements to check correct mapping
1. Open a second editor so that you have three tabs: two editors and a preview
    -  ⭐️ The preview should scroll both editor now. Also check this in horizontal layout mode and with line wrapping off.
1. Disable the setting `markdown.preview.scrollEditorWithPreview` and try scrolling the preview again
    - ⭐️ The scroll sync should no longer be enabled.

**Comment by alexandrudima** [comment]
Very nice !
