### ISSUE TITLE
file: line xxx link cannot be recognized in pwsh terminal

### ISSUE THREAD

**Issue by pizikuan** [microsoft/vscode#190847]
Type: <b>Bug</b>

file: line xxx link cannot be recognized in pwsh terminal. 

In pwsh terminal, if the program return error (eg.    ObjectStore.Save(f"chart" in chart.py: line 35) chart.py: line 35, when you hold ctrl and try to click "chart.py: line 35" to navigate to the error code line, it always fails. But it's OK in cmd terminal.

Please fix this issue for pwsh is more powerful and easy to use than CMD. Thanks.

VS Code version: Code 1.81.1 (6c3e3dba23e8fadc360aed75ce363ba185c49794, 2023-08-09T22:22:42.175Z)
OS version: Windows_NT x64 10.0.22621
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 5800U with Radeon Graphics          (16 x 1896)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|35.84GB (16.67GB free)|
|Process Argv|--crash-reporter-id 05940909-a3ea-41de-9676-d4c27b4e75d8|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (22)</summary>

Extension|Author (truncated)|Version
---|---|---
format-json|Cle|1.0.3
gitlens|eam|14.2.1
git-project-manager|fel|1.8.2
copilot|Git|1.104.347
copilot-chat|Git|0.7.2023081101
copilot-labs|Git|0.14.884
rainbow-csv|mec|3.7.0
vscode-docker|ms-|1.26.0
csharp|ms-|2.0.376
vscode-dotnet-runtime|ms-|1.7.0
python|ms-|2023.14.0
vscode-pylance|ms-|2023.8.30
jupyter|ms-|2023.7.1002162226
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.17
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-slideshow|ms-|0.1.5
remote-containers|ms-|0.304.0
remote-wsl|ms-|0.81.0
autodocstring|njp|0.6.1
intellicode-api-usage-examples|Vis|0.2.7
vscodeintellicode|Vis|1.2.30

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
vscccc:30803845
282f8724:30602487
f6dab269:30613381
a9j8j154:30646983
showlangstatbar:30737416
03d35959:30757346
24365598:30736109
pythonfmttext:30731395
pythoncmvfstrcf:30756944
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
gsofb:30804716
pythonnosmt12:30797651
pythonidxpt:30805730
pythonnoceb:30805159
dsvsc013:30795093
dsvsc014:30804076
diffeditorv1:30812748

```

</details>

**Comment by Tyriar** [comment]
@pizikuan what command did you run to get that output?

**Comment by Tyriar** [comment]
Looking into this more, this would actually be a feature request. We do support the format `"absolute_path": line x` for validated links, but we are not smart about including the line/col number when searching for a file like with a word link.

The current behavior when clicking `"terminalEnvironment.ts": line 35` is:

![image](https://github.com/microsoft/vscode/assets/2193314/a30112b8-d636-4f19-8fd0-68ed3cf08041)

Ideal:

![image](https://github.com/microsoft/vscode/assets/2193314/9eb740a4-25c0-408a-b80c-b3f09ba9f403)

If anyone wants to give this a shot, it would involve hooking up `detectLinkSuffixes` in terminalWordLinkDetector.ts:

https://github.com/microsoft/vscode/blob/d2163dce8eb0a7b1cd8c5da389bd92d7bba267b0/src/vs/workbench/contrib/terminalContrib/links/browser/terminalLinkParsing.ts#L150-L164

https://github.com/microsoft/vscode/blob/d2163dce8eb0a7b1cd8c5da389bd92d7bba267b0/src/vs/workbench/contrib/terminalContrib/links/browser/terminalWordLinkDetector.ts
