### ISSUE TITLE
VS Code 1.80 to 1.82 freezes on startup in Pop!_OS 22.04 LTS

### ISSUE THREAD

**Issue by Iomys** [microsoft/vscode#190864]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.80 to 1.82.0-1692597271 (Insider version)
- OS Version: Pop!Os 22.04 LTS x86_64

Steps to Reproduce:

1. Run `code-insiders --verbose --disable-extensions`
2. Observe that the GUI loads but becomes unresponsive shortly after.

Description:
Upon running VS Code (versions from 1.80 onwards that I've tested), the GUI opens and responds briefly before freezing. After a while, the "VS Code is not responding" window appears, but I'm unable to close it. I have to open a terminal and use the `killall` command twice to terminate the process.

Additional Context:

[Log of the verbose output (Gist)](https://gist.github.com/Iomys/d67acb794a8991fedb4f67954a3e03a8)

<details>
  <summary>More system information</summary>

```
iomys@iomys-x1e4
----------------
OS: Pop!_OS 22.04 LTS x86_64
Host: 20Y5CTO1WW ThinkPad X1 Extreme Gen 4i
Kernel: 6.4.6-76060406-generic
Uptime: 3 hours, 27 mins
Packages: 3713 (dpkg), 54 (flatpak), 8 (snap)
Shell: zsh 5.8.1
Resolution: 1920x1200, 1920x1080
DE: GNOME 42.5
WM: Mutter
WM Theme: Pop
Theme: Pop [GTK2/3]
Icons: Pop [GTK2/3]
Terminal: x-terminal-emul
CPU: 11th Gen Intel i7-11800H (16) @ 4.600GHz
GPU: NVIDIA GeForce RTX 3060 Mobile / Max-Q
GPU: Intel TigerLake-H GT1 [UHD Graphics]
Memory: 5838MiB / 31805MiB
```

  </details>

**Comment by Iomys** [comment]
Yet it works again. I think it was perhaps a problem from a dependence.

**Comment by deepak1556** [comment]
Thanks for following-up, closing per above comment.
