### ISSUE TITLE
terminal: var(...) fallback requires var()

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#190965]
These rules don't work currently:

![Image](https://github.com/microsoft/vscode/assets/2193314/aaddbd16-df2b-4542-b5b6-02455efaeed4)

For fallback variables you need to use `var(--variable1, var(--variable2))`

**Comment by aiday-mar** [comment]
By verifying this with the following regex: `var\(--.*,.*--.*\)`, there remains one instance using the old syntax in the file `interactiveEditor.css` file on line 20

**Comment by Tyriar** [comment]
@aiday-mar I created separate issues to track each case: https://github.com/microsoft/vscode/issues/190966
