### ISSUE TITLE
How to detect if there is a snippets list in the editor?

### ISSUE THREAD

**Issue by zch-cc** [microsoft/vscode#190928]
How to detect if there is a snippets list in the editor as user type keystrokes? By meaning snippets list, I mean dropdown menu in the picture. Thanks. I am building a completion provider which want to trigger only when there is no dropdown suggestions list. How to achieve it?

![Screenshot 2023-08-21 at 4 39 57 PM](https://github.com/microsoft/vscode/assets/136044586/171cccfa-b274-4b12-accd-6df17e10ef09)

**Comment by jrieken** [comment]
>  I am building a completion provider which want to trigger only when there is no dropdown suggestions list. How to achieve it?

You cannot do that but I would like to to know why you would want to to this?

**Comment by zch-cc** [comment]
I want to build a incline completion provider but I do not want to send request to the server everytime there is suggestion list since it conflicts and confuse to user. May I ask how to achieve this kind of functionality? Should I only trigger the completion when the context key suggestWidgetVisible is false?

**Comment by jrieken** [comment]
A completion item provider cannot fully control how and when it is being triggered, the editor/user decide that. To avoid confusion to users make sure to only return good results or none (which is totally valid)
