### ISSUE TITLE
zombie untitled files when attempting to close vs code

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode#190926]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: Insiders
- OS Version: 

Steps to Reproduce:

1. Install Jupyter extension
2. Open VS Code and ensure there are no documents open
3. Create a new untitled notebook via the command `Create: New Jupyter Notebook`
4. Select a kernel
5. Close the notebook
6. Open the explorer view and you'll see that `1 unsaved` item is displayed
7. Attempt to close VS Code or use the command to close all editors (even though there are none) and now you're prompted to save the changes, even when no notebook is open.

**Comment by amunger** [comment]
possible regression from the implementation of `onWillSave` in the notebook editor - The tab should be dirty as the file is untitled
