### ISSUE TITLE
Feature Request: API access to terminal output

### ISSUE THREAD

**Issue by ykdojo** [microsoft/vscode#190941]
### Problem Statement

The current VS Code API allows extensions to interact with terminal instances but lacks the ability to directly read the content or selected text within the terminal.

### Proposed Solution

I propose adding an API endpoint to access the terminal's output, including selected text. This would enable extensions to read terminal content, enhancing automation and integration possibilities.

### Use Case

This feature could allow an extension to send selected text from the terminal to other parts of the extension or external services, providing seamless integration and a more intuitive user experience.

### Potential Implementation

The API could offer methods to:

- Retrieve the entire content of the terminal.
- Retrieve the currently selected text within the terminal.

### Conclusion

API access to the terminal output would enhance extension development capabilities within VS Code, improving productivity and user experience. I kindly request the VS Code team to consider this feature.

Thank you!

**Comment by Tyriar** [comment]
Selection is happening: https://github.com/microsoft/vscode/issues/188173

Content via "commands" will probably happen soon: https://github.com/microsoft/vscode/issues/145234, raw buffer access is unlikely to happen as there are performance problems with that.

/duplicate
