### ISSUE TITLE
vscode's developer tools fail to debug CSS

### ISSUE THREAD

**Issue by wangmings** [microsoft/vscode#190988]
# vscode's developer tools fail to debug CSS
> Is this problem a bug caused by adding a sandbox

## demonstration operation
<img width="1551" alt="截屏2023-08-22 22 22 34" src="https://github.com/microsoft/vscode/assets/44308153/b564cc54-ca03-4a16-ba6a-1d84039095c6">

![text2](https://github.com/microsoft/vscode/assets/44308153/26afd778-8429-479d-8ec0-390f6688304e)

**Comment by roblourens** [comment]
I can't repro this. But this is out of our control anyway, these are just the chrome devtools attached to electron.
