### ISSUE TITLE
Electron symbol files don't exist anymore

### ISSUE THREAD

**Issue by lukehutch** [microsoft/vscode#190932]
My VS Code instance is crashing. The address given on this page for Electron symbols is broken:

https://github.com/microsoft/vscode/wiki/Native-Crash-Issues#creating-a-crash-report

The link is https://github.com/microsoft/vscode-electron-prebuilt/releases . This project doesn't exist anymore.

**Comment by deepak1556** [comment]
Please ignore the `Symbolicating Crash dump` section in the above page, it is only meant for the team members as the symbols are private, updated the wiki to reflect this. I see you have filed https://github.com/microsoft/vscode/issues/190933, attach `*.dmp` files or send them by email next time the crash happens.
