### ISSUE TITLE
Tasks often don't show statuses

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#190987]
This never really stopped happening:

![Image](https://github.com/microsoft/vscode/assets/2193314/81d65a2a-81b7-4518-848a-4688dd8ba38a)

Version: 1.82.0-insider (user setup)
Commit: f125afbc800ec611f5a9ab1333c769832ce424b3
Date: 2023-08-21T05:32:43.957Z
Electron: 25.5.0
ElectronBuildId: 23084831
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.22621

**Comment by meganrogge** [comment]
No reload:
![Screenshot 2023-09-12 at 10 51 57 AM](https://github.com/microsoft/vscode/assets/29464607/4640a888-6173-4a99-ae68-d9e79fe32afd)

First reload:
Lacks `dependsOnStarted`, spinner never completes for the second (dependent) task
![Screenshot 2023-09-12 at 10 54 51 AM](https://github.com/microsoft/vscode/assets/29464607/c45a8daf-5e1c-4d24-98c5-23307d170b21)

Second reload:
`Timeout getting tasks from npm`
![Screenshot 2023-09-12 at 10 56 14 AM](https://github.com/microsoft/vscode/assets/29464607/5f029048-4c05-44ba-b9a9-7a336d7b91ba)

**Comment by meganrogge** [comment]
This is happening because for the initial run, we are running `VS Code - Build` which contains dependency tasks. On reload, `Core - Build` and `Extensions - Build` are getting run individually, so `dependsOnStarted` doesn't happen.

![Screenshot 2023-09-12 at 11 05 56 AM](https://github.com/microsoft/vscode/assets/29464607/b521a378-dabf-478d-9b72-f8e1b32f787f)

**Comment by meganrogge** [comment]
One issue is we use `isBackground` to determine if we should persist a task. since that is false for `VS Code - Build`, it doesn't get saved and only it's components do.

**Comment by Tyriar** [comment]
@meganrogge I sometimes see this not just after a reload, and saving to trigger a new watch doesn't update it to a tick still

**Comment by meganrogge** [comment]
Can you reproduce that without reloading? I haven't been able to.

**Comment by meganrogge** [comment]
linked PR just fixes the issue in which one reloads the window after running the build task (or any task with dependencies)

**Comment by meganrogge** [comment]
Actually, I believe it's the `active` and `inactive` events that are needed here.

**Comment by Tyriar** [comment]
@meganrogge it's hard to repro unfortunately. We can go with this fix and I'll keep an eye out

**Comment by meganrogge** [comment]
Verify that clicking on the terminal tabs of task terminals does not remove the statuses.
