### ISSUE TITLE
CTRL+S is slow

### ISSUE THREAD

**Issue by boxHiccup** [Microsoft/vscode#1909]
Saving file by pressing CTRL+S (and, of course by saving it through the menu) makes VS Code freeze for about a second

**Comment by bpasero** [comment]
@boxHiccup is this with any file?

**Comment by boxHiccup** [comment]
@bpasero Yes, even che smallest sized file

**Comment by bpasero** [comment]
@boxHiccup can you start a profile from developer tools before pressing ctrl+s and stop if after it is done to see where time is spend. let me know if you need help how to start it.

**Comment by boxHiccup** [comment]
I can do it, but I'm out the city by now, tomorrow I'll be available to post a screenshot. Thanks for your availability to resolve the issue

**Comment by bpasero** [comment]
@boxHiccup thanks!

**Comment by bpasero** [comment]
@boxHiccup ping

**Comment by boxHiccup** [comment]
I'm sorry, I forgot to do that.
By now, If I click "Start CPU profiling" everything gets freezed, editor does is completely blocked and Developer Tools are freezed (for example I click "Stop CPU profiling" and the result is that continues recording)
![screenshot_101](https://cloud.githubusercontent.com/assets/16635005/12530259/3d55abf8-c1d9-11e5-8edf-0e6db2ce14e7.png)
(The button in the top right of the screenshot should be red, but I clicked that to stop profiling and the profile is still recording)

**Comment by bpasero** [comment]
@boxHiccup that is crazy, does it also not work if you close all editors, restart code and then try to profile? is your machine very slow?

**Comment by boxHiccup** [comment]
My computer is ok, I tried with only Code open and it doesn't work.
Presario CQ56-110SL is my computer model, if you want to check technical specifications

**Comment by bpasero** [comment]
@boxHiccup when you just start code, is the CPU already going up high and stays? Are you opening a very large folder?

**Comment by boxHiccup** [comment]
The CPU stays low (usage at 10-15% range). It happens both with a single file and an entire folder, but that folder isn't so big to cause something like that.
By the way, I just noticed that freezing (at save process) happens only with PHP files (size doesn't matter, apparently)

**Comment by bpasero** [comment]
@boxHiccup so you say saving is only slow for PHP files?

**Comment by boxHiccup** [comment]
Yeah

**Comment by bpasero** [comment]
@boxHiccup are you on Code 0.10.6? Can you check if it is also slow when you run `code --disableExtensions` to disable any installed extension?

**Comment by boxHiccup** [comment]
Yes, Code version is 0.10.6. However by using Command Palette (-> Show Installed Extension) I don't see any installed extension, I also tried to run Code with that parameter, nothing changes

**Comment by bpasero** [comment]
Ok. If we cannot get the profile to run, I am not able to help, sorry :-/

**Comment by boxHiccup** [comment]
No problem, thanks anyway!
