### ISSUE TITLE
Diff Editor: Don't align just whitespace

### ISSUE THREAD

**Issue by hediet** [microsoft/vscode#190961]
![Image](https://github.com/microsoft/vscode/assets/2931520/5c41d7b3-9475-4459-8f78-5af7767735b0)

[Repro](https://microsoft.github.io/monaco-editor/playground.html?source=v0.42.0-dev-20230809#XQAAAAKOBwAAAAAAAABBqQkHQ5NjdMjwa-jY7SIQ9S7DNlzs5W-mwj0fe1ZCDRFc9ws9XQE0SJE1jc2VKxhaLFIw9vEWSxW3yscxB_hCRgmSatbNyrNa50VLHWwDOn0YI7IfU0xJ0CGYU1vRtgnKPmZzQcQ1F9I-F9YcvQUj8HivueDk6xk10aTtNR3RAJjdvBxfoTGfcszve9sgLIoLXVmtphjl9ux0scTbqn8xJDJ_Vu3bQ0F0nkf4EFAzrz_o4urR-zwk3aaM_5g8NtmF0aIDYBdEIX1-uzWDGO8qM9NqETpjA77g4aeC2ouBFbqtZXc4BgMMq0rMeL2_ytGNfhnELoRtIMy01Fd-x9jvDYURVNW4XXqOKmYcNwywXX_EVXHKGESPwbWe76pI7_e2JadX9zPm8E6nWRqm6D1mnsZ480SeVg-yAEwblWLefKvKYP26ylb9duVmsKAZV6x3CXMzq57bBTtGhKaFanDsAwFtV1JjAApPKUq_EWzmTAVMNdp2Fay6AkJW_nNLZQsWMzo57zFXeFPhBLL_PADIxBHwsclGemqttG5gGybiSvsivuOUBZaE8tWMT3ULAFUlGxLAiDA6mw35w3ez-8Q5GfENNUCkg_bJ0EM4dhVuXRCs072DINsB9jAblUw2nA5fdLFHZdRn6D8JSNRoHD4j_oQUpeCG2IbRNIQoMDSE46etnzw4ByBuFj8yEufW4xciyUpn9VrQtPzbAmaOtdBX_ItJgajY3E-448EdliKgcdxsFq0B5xgasx0MTWKqAX5xt6Xar3gNBBQPnsUi2MJJLulgJ3Ro36oGtMMBEa0kp5QDK-iH2kjUvwzcMOunlklCcYCFbZNVi_IAzT1BfRXgw3ZkN5UV2QgTl5zRi4DRQJEeE6jxRmKSI_QEuBfpdwUEx_rD4Jg)

**Comment by alexr00** [comment]
I still see the same diff in the Monaco playground. Is there something else I need to do to verify?

![image](https://github.com/microsoft/vscode/assets/38270282/0695e15a-c67d-41cf-a208-7ac20067ec4b)

**Comment by hediet** [comment]
Before:
![chrome_ryDlDnNJA6](https://github.com/microsoft/vscode/assets/2931520/51e0a06d-8286-4811-8f3c-c68589bf3527)

After (which matches your screenshot):
![mn8lam3jNy](https://github.com/microsoft/vscode/assets/2931520/7edd48e7-6471-45cc-93f6-68c04ade92f7)
