### ISSUE TITLE
Changing view icon not working on extension creation.

### ISSUE THREAD

**Issue by StephaneAdeso** [microsoft/vscode#191076]
I am making a vscode extension. 
I'm trying to understand how to use the built-in icons without having to import any dependencies. I have read your documentation and have asked on [StackOverflow](https://stackoverflow.com/questions/76956225/change-tree-view-icon-in-vscode?noredirect=1#comment135665177_76956225), but it seems that there is no answer at the moment.
I'm trying to change the icon of a view, but despite having set it in the package.json, I don't see any change.

So I have 2 questions. How can I use the built-in icons without having to import dependencies?

How do I change the view icon?

This is my view configuration in the package.json:
```json
"views": {
      "my-sidebar": [
        {
          "id": "my-collections-tree",
          "name": "Collections",
          "contextualTitle": "Collections",
          "type": "tree"
        },
        {
          "id": "my-history-tree",
          "name": "History",
          "contextualTitle": "History",
          "type": "tree",
          "icon": "$(briefcase)"
        }
      ]
    },
```
This is the icon that I intend to change for didactic reasons and learn how to use those icons.
![image](https://github.com/microsoft/vscode/assets/55595063/a8157f29-fa8f-43b3-9581-17b427bce26c)

**Comment by gjsjohnmurray** [comment]
I think that icon property only has an effect if you drag its view onto the Activity Bar to give it a standalone presence there instead of it being in the view container you are contributing.

**Comment by StephaneAdeso** [comment]
Thank you so much. That is not in the documentation. Do you know how to modify the icon of the view?

**Comment by gjsjohnmurray** [comment]
> Do you know how to modify the icon of the view?

I don't think it's possible.

**Comment by StephaneAdeso** [comment]
ok thank you

**Comment by aeschli** [comment]
Thanks @gjsjohnmurray for the reply
