### ISSUE TITLE
Allow developers to bind to any keypress

### ISSUE THREAD

**Issue by thekalinga** [microsoft/vscode#19105]
IntelliJ have this extension called [Presentation Assistant](https://github.com/JetBrains/resharper-presentation-assistant) that displays the keys pressed.

This will help during presentation/pair programming.

AFAIK, currently vscode only have provision to bind to a given key combination. In order to implement an extension of this sort, we need extension point for plugins to hook into any keypress.

It would be better to allow users to hook into mouse activity aswell. I'm not sure about the usecase, but someone might comeup with a usecase :)

**Comment by mousetraps** [comment]
Cool idea! Ultimately it sounds like for this case, you don't necessarily want to listen to every keystroke - that might be a lot of noise, but you want to be able to know when specific events occur. 

Are there any other practical scenarios you can think of (other than Presentation Assistant, where this might be useful?)

cc @waderyan @chrmarti @alexandrudima @jrieken

**Comment by thekalinga** [comment]
@mousetraps You are right. Since the extension needs to show the actions, getting notified about events should serve the purpose here.

> Are there any other practical scenarios you can think of
I think developing a vim based navigation can be another usecase

**Comment by thekalinga** [comment]
One usecase I have in mind is binding to `shift+shift` & `ctrl+ctrl`. Intellij uses double shift to search thru all actions.

Since this is a special case, the editor should expose this instead of letting the user do this.

FYI, I'm not sure if vscode already allows people to bind to the above combination

**Comment by thekalinga** [comment]
Its is mentioned [here](https://stackoverflow.com/questions/39481386/how-to-create-a-custom-dialog-in-vscode) that you cannot create custom dialogs in vscode.

I'm not sure about the veracity of this response.

If true, extension developers also need to have a provision to create custom dialog like the one in the original intellij extension

**Comment by tkissing-work** [comment]
Has there been any progress on this? Presentation Assistant is super useful when doing workshops or local pair programming. If all the hooks (events for registered shortcuts, a way to show notifications as overlay) are there, I would even consider learning how to write an extension to put it together.

**Comment by alexilyaev** [comment]
Another year passed, I'm an educator, want to move from WebStorm to VS Code, but I can't find a similar feature to Presentation Assistant.

Was there any progress in the underlying API's to make this possible?

**Comment by alexandrudima** [comment]
fyi @joaomoreno

**Comment by joaomoreno** [comment]
This is done: `Developer: Toggle Screencast Mode`

**Comment by alexilyaev** [comment]
> This is done: `Developer: Toggle Screencast Mode`

That's really great!
