### ISSUE TITLE
Enchance the scroll-down logic when executing cells

### ISSUE THREAD

**Issue by ZeroRin** [microsoft/vscode#191086]
For my experiments, when shift+enter to run a cell, the window moves in the following logic:
1. the window scrolls down until the next cell is fully visible or the header of the next cell reaches the top of the screen
2. during execution, the position of the topmost cell whose header is within the screen remain fixed, others may move as the output increases.

I believe users usually want to focus on the end of the output cell as it contains the most recent information, but such logic would make it invisible in two scenarios:
1. if the next cell is long enough to occupy the whole screen, all outputs would be out of the screen.
2. if the head of the current cell is still in the screen, its position would be fixed and the output may run out of the end of the current screen.

I would suggest scrolling in the following manner:
1. the window scrolls down until the first line of the next cell is visible
2. during execution, the position of the next cell remain fixed

Here are some examples, the left is the status before execution, the middle is the actual behaviour and the right is what I expect
![QQ图片20221226145236](https://user-images.githubusercontent.com/14952735/209514510-4e988068-fbf6-41f5-8378-9528748c2f69.png)
![QQ图片20221226145243](https://user-images.githubusercontent.com/14952735/209514566-348f2aa7-421b-4e3b-9bcc-0485e672ed0c.png)

**Comment by amunger** [comment]
more discussion happening in https://github.com/microsoft/vscode/issues/169038 to polish the behavior
