### ISSUE TITLE
False error with sass in Ionic2 project

### ISSUE THREAD

**Issue by peterennis** [Microsoft/vscode#19108]
![capture025](https://cloud.githubusercontent.com/assets/140737/22234942/fdbeabfe-e1b0-11e6-9995-1636ac8b1fac.PNG)

- VSCode Version:
1.8.1

- OS Version:
Windows 10

Steps to Reproduce:
See example

**Comment by mousetraps** [comment]
Good news! Support for SCSS maps was [recently added](https://github.com/Microsoft/vscode/issues/1758) - check out the latest [Insiders Build](https://code.visualstudio.com/insiders) to try it out, and let us know what you think!
