### ISSUE TITLE
Terminal content appears delayed

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode#191056]
Version: 1.82.0-insider
Commit: ad94cf18189746d2e942fda257950901049b3af3
Date: 2023-08-23T05:33:07.513Z
Electron: 25.5.0
ElectronBuildId: 23084831
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Linux x64 5.15.0-79-generic

Ubuntu 22.04.3 LTS Gnome 42.9

- New empty profile, no settings, no extensions installed
- open an internal terminal
- type some command. Cursor moves, not all characters are visible. They appear after typing more

![Image](https://github.com/microsoft/vscode/assets/6461412/f682bbc8-9797-408b-b0d4-6f80ca1403cb)

**Comment by Tyriar** [comment]
/duplicate https://github.com/xtermjs/xterm.js/issues/4665

If you can get trace logs for the Terminal output channel when this happens that would be helpful.

**Comment by aeschli** [comment]
![Peek 2023-08-23 14-24](https://github.com/microsoft/vscode/assets/6461412/fd05b5a1-df5a-4f1c-99eb-1947d309976e)

**Comment by Tyriar** [comment]
Thanks, I just realized I didn't hook up the trace log level to xterm.js yet 🤦

**Comment by Tyriar** [comment]
https://github.com/microsoft/vscode/pull/191071
