### ISSUE TITLE
Electron icon is incorrect on final .exe

### ISSUE THREAD

**Issue by Alex313031** [microsoft/vscode#191077]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.81.1
- OS Version: Windows 10 22H2

Steps to Reproduce:

1. Build vscode via instructions in the contributing docs (I have made a successful build many times before)
2. Installer and archive build OK, and they open OK, but the icon is wrong.
3. The icon of the installer .exe and `Code - OSS.exe` is the default Electron one, rather than the [code.ico](https://raw.githubusercontent.com/microsoft/vscode/main/resources/win32/code.ico) one.
Otherwise, the app runs OK, and the icon is correct within the UI, it is just the .exe. Taskbar icon is incorrect, and using resourcehacker, I can verify via the RC header data that the .exe still has the Electron icons.

![Capture](https://github.com/microsoft/vscode/assets/45863095/da8f1d9d-2afe-45ce-806a-7ba7c82fd223)

**Comment by Alex313031** [comment]
@VSCodeTriageBot The issue remains

**Comment by Alex313031** [comment]
@sergei-dyshel I see you have an active fork. Have you had this issue?

**Comment by joaomoreno** [comment]
https://github.com/microsoft/vscode-gulp-electron/issues/16
