### ISSUE TITLE
Large files: Disable tokenization

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#191065]
I think we used to do this. The below profile was generated by opening a ~100mb typescript file and copy and pasting its contents. The editor locked up for about 2-3 minutes before tokenization finished. After it finished it was reasonably fast but a slower computer may crash from this and waiting minutes for something to finish is not reasonable.

![Image](https://github.com/microsoft/vscode/assets/2193314/21b8532c-e8c2-45f9-aa14-3a67eb7e2dba)

Version: 1.82.0-insider (user setup)
Commit: f125afbc800ec611f5a9ab1333c769832ce424b3
Date: 2023-08-21T05:32:43.957Z
Electron: 25.5.0
ElectronBuildId: 23084831
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.22621

**Comment by Tyriar** [comment]
I had `"editor.experimental.asyncTokenization": true` set, even though it's async we still shouldn't be doing it for files this large unless the user force enables it.

**Comment by hediet** [comment]
> The editor locked up for about 2-3 minutes before tokenization finished. 

As in freezed? In the profile it looks it just reacts on the onmessage event, the UI shouldn't freeze.

**Comment by Tyriar** [comment]
You can see the task in the screenshot takes ~600ms, so the editor dropped to ~2 fps for 3 minutes or less when other things were happening in the same task.
