### ISSUE TITLE
some things like "clear" and  "screen" are now broken in terminal

### ISSUE THREAD

**Issue by bobmagicii** [Microsoft/vscode#19100]
```
bob@devweb1 dmanetwork (master) $ screen -r
Cannot find terminfo entry for 'cmd.exe'.
```
```
bob@devweb1 dmanetwork (master) $ clear
'cmd.exe': unknown terminal type.
```

windows 10, code 1.9.0-insider, cmd.exe > `ssh dev` (ubuntu 14.04)

these used to work, a few insiders builds ago. i do the screen all the time to check in on a long running rsync. let me know what kind of debugging info you may need.

i feel like this happen at the same time that powershell became the default. probably not relevant for anything except carbon dating the issue.

**Comment by mousetraps** [comment]
I can't reproduce it myself, but maybe @Tyriar has a clue what's might going on.

**Comment by Tyriar** [comment]
@bobmagicii does ssh under Windows 10 like this work fine on the stable build?

**Comment by bobmagicii** [comment]
will follow up. don't actually have any machines with stable been on insider since the day code was announced.

**Comment by bobmagicii** [comment]
indeed this got cleared up a release or two after

**Comment by Tyriar** [comment]
Good to hear :smiley:
