### ISSUE TITLE
Notebook still visible when making terminal full screen

### ISSUE THREAD

**Issue by successar** [microsoft/vscode#191026]
Type: <b>Bug</b>

Notebook content is still visible if I have a notebook open and then create a terminal in full screen mode.

Steps to reproduce:
1. Open a notebook
2. Create a terminal
3. Click ^ on RHS to expand the terminal.

Output: Top portion of notebook still visible underneath the terminal.

https://github.com/microsoft/vscode/assets/1499824/c123a2a0-2d99-42b3-839f-1e621640bd69

VS Code version: Code 1.81.1 (Universal) (6c3e3dba23e8fadc360aed75ce363ba185c49794, 2023-08-09T22:20:33.924Z)
OS version: Darwin arm64 22.6.0
Modes:
Remote OS version: Linux x64 5.4.250-173.369.amzn2int.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|3, 3, 2|
|Memory (System)|32.00GB (1.30GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: cd-gpu|
|OS|Linux x64 5.4.250-173.369.amzn2int.x86_64|
|CPUs|Intel(R) Xeon(R) CPU E5-2686 v4 @ 2.30GHz (64 x 2724)|
|Memory (System)|480.24GB (467.79GB free)|
|VM|0%|
</details><details><summary>Extensions (22)</summary>

Extension|Author (truncated)|Version
---|---|---
jupyter-keymap|ms-|1.1.2
remote-containers|ms-|0.304.0
remote-ssh|ms-|0.102.0
remote-ssh-edit|ms-|0.86.0
remote-wsl|ms-|0.81.0
vscode-remote-extensionpack|ms-|0.24.0
remote-explorer|ms-|0.4.1
remote-server|ms-|1.4.3
shell-format|fox|7.2.5
copilot|Git|1.105.350
gc-excelviewer|Gra|4.2.58
bash-ide-vscode|mad|1.39.0
vscode-kubernetes-tools|ms-|1.3.13
isort|ms-|2023.10.1
python|ms-|2023.14.0
vscode-pylance|ms-|2023.8.30
jupyter|ms-|2023.7.1002162226
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.17
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-slideshow|ms-|0.1.5
vscode-yaml|red|1.14.0

(2 theme extensions excluded)

</details>

**Comment by rebornix** [comment]
Will be fixed via https://github.com/microsoft/vscode/pull/188226
