### ISSUE TITLE
tsc: build step stuck on "Building..."

### ISSUE THREAD

**Issue by USMortality** [microsoft/vscode#191042]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.81.1 (Universal)
- OS Version: MacOS Ventura 13.5

Debugging without previous build step works, but with build step via: 
`"preLaunchTask": "tsc: build - tsconfig.json",` it's stuck on "Building..." - I cannot see any error or output being shown!

Steps to Reproduce:

1. Load project minimal reproducible project here: https://github.com/USMortality/ts-starter
2. Start Configuration "Launch Program" - it will be stuck on "Building", when disabling the above line it will work.

WORKING:
<img width="1608" alt="Screenshot 2023-08-22 at 6 32 17 PM" src="https://github.com/microsoft/vscode/assets/94856880/34aef56e-8a85-4152-94de-5937a7226754">

<img width="1608" alt="Screenshot 2023-08-22 at 6 32 30 PM" src="https://github.com/microsoft/vscode/assets/94856880/c18ee0da-fe28-4c84-9b83-e5a2f32bd787">

NOT WORKING:
<img width="1608" alt="Screenshot 2023-08-22 at 6 43 08 PM" src="https://github.com/microsoft/vscode/assets/94856880/e8c9ea5e-2d86-430f-8c9e-7c4c66347f99">
<img width="1608" alt="Screenshot 2023-08-22 at 6 43 13 PM" src="https://github.com/microsoft/vscode/assets/94856880/fe4dbd37-c4f2-4676-9381-ce874d7fe6fa">

It's stuck forever on "Building..." any ideas?

**Comment by roblourens** [comment]
It looks like your task didn't actually run, and your shell prompt loaded instead. I assume it has something to do with your shell configuration, can you tell us about that?

**Comment by USMortality** [comment]
> It looks like your task didn't actually run, and your shell prompt loaded instead. I assume it has something to do with your shell configuration, can you tell us about that?

Hah, indeed - Thx. I'm using fish shell, so commenting the line, which launches it: `fish` in my `~/.profile` made it work.
I removed that line, and configured my Mac Terminal, to launch fish instead, which should not interfere with VS.

<img width="779" alt="Screenshot 2023-08-23 at 4 53 00 PM" src="https://github.com/microsoft/vscode/assets/94856880/cbd4a154-7a8e-4429-b075-abec169c5c1c">
