### ISSUE TITLE
Keyboard focus disappears when TAB key is pressed when leaving a view

### ISSUE THREAD

**Issue by kisantia** [microsoft/vscode#191027]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.81.1
- OS Version: macOS 13.5

Steps to Reproduce:

1. Start with focus on a view and navigate using TAB key
2. After the end of the view is reached, the focus disappears until TAB is pressed again and focus goes to Problems.

expected: keyboard focus does not disappear after pressing TAB

User Impact:
Keyboard users will get confused here as they will not understand where the focus is.

Nothing showing as the focused element after tabbing to the end of the view, until TAB is pressed again and "Problems" gets the focus:
![tabFocusNoScreanreader](https://github.com/microsoft/vscode/assets/31145923/3dc4e7c3-d855-4ec0-abae-f6ecea112278)

If a screen reader is on, then you can see that the focus goes to the empty pane:
![tabFocusWithScreenreader](https://github.com/microsoft/vscode/assets/31145923/3a385418-1081-4feb-8368-f9c30c79a958)

**Comment by meganrogge** [comment]
This is working as designed cc @isidorn
