### ISSUE TITLE
Slow ssh connection in VS Code terminal

### ISSUE THREAD

**Issue by thistlillo** [microsoft/vscode#191066]
These days I am working in a place with an incredibly bad internet connection. It is very slow. I usually work with a remote-ssh connection to a server.

Now the problem:
- when connected via SSH with a real terminal, the connection is slow but usable.
- when connected via SSH with the terminal integrated in VSC, the connection is incredibly slow and completely unusable.
- everything done via VSC takes ages, even saving a file. Indeed, I am not even able to close the remote-ssh connection because unsaved changes cannot be saved.

So internet is slow, but usable with all apps but VSC. VSC is unusable. I tried to disable some extensions, but the problem stayed.

I do not know how to debug this issue, so I came here to ask for help.

Some details:
- remote server, Ubuntu 20.04 LTS

My local machine:
- Macbook Air M1
Version: 1.81.1
Commit: 6c3e3dba23e8fadc360aed75ce363ba185c49794
Date: 2023-08-09T22:40:25.698Z
Electron: 22.3.18
ElectronBuildId: 22689846
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Darwin arm64 22.6.0

**Comment by roblourens** [comment]
Working with remote-ssh is very different than working with ssh in a terminal. There is sometimes a lot of data that has to be transferred to navigate a workspace, open and save files, etc. We could probably be more resilient to bad connections than we are currently but as it is, a somewhat stable internet connection is basically just a requirement. Sorry that it isn't working for you.
