### ISSUE TITLE
Intellisense and linting crash when opening a specific file

### ISSUE THREAD

**Issue by MihailDimitrovK** [microsoft/vscode#191062]
Type: <b>Bug</b>

I am experiencing issues with Intellisense and linting when I open a specific file. Everything works correctly before opening this file, but afterwards, all files lose Intellisense and linting. The file in question is a .tsx file.

VS Code version: Code 1.81.1 (6c3e3dba23e8fadc360aed75ce363ba185c49794, 2023-08-09T22:18:39.991Z)
OS version: Linux x64 5.15.0-79-generic
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2200)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|4, 5, 5|
|Memory (System)|15.34GB (7.32GB free)|
|Process Argv|--new-window --crash-reporter-id c5469317-467b-40a7-ac9c-0dd2cfd72b03|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|cinnamon|
|XDG_CURRENT_DESKTOP|X-Cinnamon|
|XDG_SESSION_DESKTOP|cinnamon|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (22)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-tailwindcss|bra|0.9.13
npm-intellisense|chr|1.4.4
path-intellisense|chr|2.8.4
vscode-eslint|dba|2.4.2
es7-react-js-snippets|dsz|4.4.3
prettier-vscode|esb|10.1.0
auto-rename-tag|for|0.1.10
rest-client|hum|0.25.1
svg|joc|1.5.3
vscode-docker|ms-|1.26.0
vsliveshare|ms-|1.0.5883
color-highlight|nau|2.5.0
paste-and-indent|par|0.1.0
vscode-css-peek|pra|4.4.1
LiveServer|rit|5.7.9
vscode-paste-and-indent|Rub|0.0.8
code-spell-checker|str|2.20.5
intellicode-api-usage-examples|Vis|0.2.7
vscodeintellicode|Vis|1.2.30
console-ninja|Wal|0.0.204
vscode-import-cost|wix|3.3.0
JavaScriptSnippets|xab|1.8.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
py29gd2263cf:30792227
vscaac:30438847
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
vscccc:30803845
2e4cg342:30602488
89544117:30613380
showlangstatbar:30737416
03d35959:30757346
ecj1e332:30736112
pythonfmttext:30731395
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
gsofb:30804716
pythonnosmt12:30797651
pythonidxptcf:30805731
pythonnoceb:30805159
dsvsc013:30795093
dsvsc014:30804076
diffeditorv2:30812749

```

</details>

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)? 

Also can you share the file?

**Comment by MihailDimitrovK** [comment]
Hi,

I managed to fix it. The problem comes from the UseFormReturn of react-hook-form.

Thank you for your help.

**Comment by MihailDimitrovK** [comment]
Hi,

I managed to fix it. The problem comes from the UseFormReturn of react-hook-form.

Thank you for your help.
