### ISSUE TITLE
Erasing should erase with tab size

### ISSUE THREAD

**Issue by tinganho** [Microsoft/vscode#1910]
If there are no characters between the caret and column 0 in the current line. Hitting the erase keyboard button should erase the amount of columns of the defined tab size and not 1 column.

```typescript
class A {
        | // if press erase here
-----------------------------------
    | // the caret should land here
}
```

**Comment by egamma** [comment]
There is an extension for this: https://marketplace.visualstudio.com/items/jrieken.backspace-plusplus. Can you pls give it a try and let us know how it works for you?

**Comment by tinganho** [comment]
@egamma it works perfectly.

**Comment by egamma** [comment]
CC @jrieken

**Comment by jrieken** [comment]
@tinganho Thanks - you made my day :dancers:

**Comment by tinganho** [comment]
@jrieken :+1:

**Comment by JetLua** [comment]
I think this should be in a core package.

**Comment by alexandrudima** [comment]
Thanks to PR #5423 by @outcoldman it will be in the core with the May release.
