### ISSUE TITLE
React Native (Color)

### ISSUE THREAD

**Issue by Wahaj-Khan** [microsoft/vscode#191080]
Type: <b>Feature Request</b>

In html css or React, whenever we use any color property like color, background color etc, it shows the color(as a little square box) with its color code or color name. But in react native, whenever I use any color it doesnt shows the color square box where on hover I can change/choose different color.

VS Code version: Code 1.81.1 (6c3e3dba23e8fadc360aed75ce363ba185c49794, 2023-08-09T22:22:42.175Z)
OS version: Windows_NT x64 10.0.22621
Modes:

**Comment by aeschli** [comment]
Can you add a small code sample that illustrates this?

**Comment by Wahaj-Khan** [comment]
> Can you add a small code sample that illustrates this?
