### ISSUE TITLE
Support binding to a unix domain socket instead of a TCP address in serve-web

### ISSUE THREAD

**Issue by leifwalsh** [microsoft/vscode#191043]
>It doesn't look like this new CLI supports serving on a UNIX domain socket. Could we please get that added in too, like in https://github.com/microsoft/vscode-remote-release/issues/6940? We're going to need it in order to handle auth in a proxy. (I'm happy to open a new issue for that if you need)

_Originally posted by @leifwalsh in https://github.com/microsoft/vscode/issues/191014#issuecomment-1689095808_

**Comment by leifwalsh** [comment]
Nice, thanks!

**Comment by roblourens** [comment]
I can do this

```
$ code-insiders serve-web --socket-path /tmp/mysock
*
* Visual Studio Code Server
*
* By using the software, you agree to
* the Visual Studio Code Server License Terms (https://aka.ms/vscode-server-license) and
* the Microsoft Privacy Statement (https://privacy.microsoft.com/en-US/privacystatement).
*
Web UI available on /tmp/mysock
```

what now?

**Comment by roblourens** [comment]
Also is it an issue that the socket file wasn't release/deleted after a ctrl+C? `[2023-08-29 11:24:41] error could not listen on socket/pipe: Os { code: 48, kind: AddrInUse, message: "Address already in use" }` or do I clean that up manually?
