### ISSUE TITLE
SocketException only via VS Code - not Android Studio

### ISSUE THREAD

**Issue by remsysinc** [microsoft/vscode#191005]
Type: <b>Bug</b>

During an http REST call using http package, I receive the error:
     "SocketException (SocketException: Failed host lookup: 'somedomain.com' (OS Error: No address associated with hostname, errno = 7))".

this is strictly happening on an x86 emulator when running/debugging (F5) in VS Code (VSC). 

- it does NOT happen with the SAME emulator running through Android Studio (AS). 
- it does NOT happen on any APK install built from VSC or AS when run on a PHYSICAL device.
- it does NOT happen when run from command prompt using "flutter run".

App has Internet access and the setting in AndroidManifest.xml ('<uses-permission android:name="android.permission.INTERNET"/>') in both manifest files.

Others have indicated the issue is related to how VSC is running the app.  I've looked at the launch.json, tried deleting it altogether, tried various settings to no avail.  Current launch.json is:
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "my_project",
            "request": "launch",
            "type": "dart"
        },
        {
            "name": "my_project (profile mode)",
            "request": "launch",
            "type": "dart",
            "flutterMode": "profile"
        },
        {
            "name": "my_project (release mode)",
            "request": "launch",
            "type": "dart",
            "flutterMode": "release"
        }
    ]
}

Another piece of info which may help... if I use an x86_64 emulator (which I guess is 64-bit), and set the "run/debug" setting in VSC to either "profile" or "release" (option defined in this launch.json file), the app runs fine without error via VSC.  It's only when I run the other emulator (x86) through VSC I get the error.

VS Code version: Code 1.81.1 (6c3e3dba23e8fadc360aed75ce363ba185c49794, 2023-08-09T22:22:42.175Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz (8 x 4200)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|63.95GB (36.94GB free)|
|Process Argv|C:\\Flutter\\projects\\VS Code Projects\\myapps\\my_project|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
dart-data-class-generator|Ben|0.5.5
dart-code|Dar|3.70.0
flutter|Dar|3.70.0
vsc-material-theme|Equ|33.1.2
vsc-material-theme-icons|equ|1.2.2
json-to-dart|hir|3.5.8
adb-filesystem|Mak|0.0.3
regionfolder|map|1.0.22
jsontodart|Muh|0.2.2
awesome-flutter-snippets|Nas|4.0.1
dartgettersetter|Pet|1.0.2
arcade|tha|1.3.16
vscode-terminal-here|Tyr|0.2.4

(3 theme extensions excluded)

</details>

**Comment by kaggabba** [comment]
I have the same issue since august 15th.
The emulator runs in normal way if you uncheck "Uncaught Exception"

**Comment by remsysinc** [comment]
Yes!  That was around the time I started experiencing it.  Sorry for you, but also happy that others see same thing - that way it's not just my end and hopefully can be addressed.

You saved me on the short-term however... turning off "uncaught exceptions".  I must say it makes me a bit uneasy for other things slipping through, but I'll take it for now and fingers crossed a solution is found soon.

**Comment by roblourens** [comment]
Please file this on the dart extension repo

**Comment by remsysinc** [comment]
> Please file this on the dart extension repo

Happy to!  Can you please point me where to do that?

**Comment by remsysinc** [comment]
> I have the same issue since august 15th. The emulator runs in normal way if you uncheck "Uncaught Exception"

They closed this issue and asked to re-post on "dart extension repo".  I've Googled and have no idea where to do this.  You?
