### ISSUE TITLE
Extensions view scroll to top button icon uses wrong foreground colour

### ISSUE THREAD

**Issue by greenie** [microsoft/vscode#191030]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.81.1
- OS Version: macOS 13.5.1

Steps to Reproduce:

1. Switch to a theme that uses similar primary button background and secondary button foreground colours (I've used Bikkuri in the screenshots)
2. Observe that the scroll to top button icon in the Extensions view has low contrast due to the mixing of primary and secondary button variables

Primary and secondary buttons in a theme where primary and secondary buttons have similar background and foreground colours:
<img width="255" alt="Screenshot 2023-08-22 at 23 27 07" src="https://github.com/microsoft/vscode/assets/286404/50ba4f08-5bcc-4b8d-a50f-ba1f592df642">

Leading to a scroll to top button looking like this:
<img width="75" alt="Screenshot 2023-08-22 at 23 27 33" src="https://github.com/microsoft/vscode/assets/286404/db543fe4-e891-4493-bc79-6a3729909f40">

**Comment by sandy081** [comment]
Sure. I assumed this is a general webview issue.
