### ISSUE TITLE
Review `security.workspacesTrustedToSpecifyExecutables` setting

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#19113]
![image](https://cloud.githubusercontent.com/assets/22350/22238238/b3382140-e210-11e6-8150-1f44e0dc595e.png)

Related to #19112

This setting is:

1. Way too ambiguous.
2. Lost when I rename my workspace.
3. Not shareable between machines.

It needs some serious review.

cc @Microsoft/vscode for opinions

**Comment by jrieken** [comment]
We also keep in mind that for every extension we have generated (and in the future will) using our yeoman generator contains this: 

```json
 "typescript.tsdk": "./node_modules/typescript/lib" // we want to use the TS server from our node_modules folder to control its version
```

So, everyone that creates a new extension and starts VS Code will see this. Not the nicest greeting if you ask me.

**Comment by isidorn** [comment]
Also using the message service is always a big pain for the user as it is very spammy. Not sure if there is a better alternative in this case

**Comment by joaomoreno** [comment]
Agreed: that popup is cringe material.

I wonder how urgent that choice really is. Shouldn't choosing the TypeScript version a simple matter of clicking the status bar version number, and having the quick open interface open up with the choices?

![image](https://cloud.githubusercontent.com/assets/22350/22248461/f9875dcc-e23e-11e6-9c94-a90596c08b18.png)

**Comment by Tyriar** [comment]
It would be a lot more portable if it supported environment variables. For example I use the following extension config which works great across my Windows, Mac and Linux machines (where my username differs):

```json
  "gitProjectManager.baseProjectsFolders": [
    "$HOME/dev",
    "%USERPROFILE%\\Documents\\dev"
  ],
```

It would be nice if the trust workspace button would automatically use `$HOME` or `%USERPROFILE%` if we went this way too.

**Comment by mjbvz** [comment]
Here's a prototype of a new `typescript.tsdk` flow: #19329

The new flow removes the initial warning message and moves the config actions to the status bar. It does not add an explicit version selector as @joaomoreno suggested, but instead has different messages based on how the user's workspace is configured.

Take a look and let me know if you have any suggestions on making the flow better

**Comment by mjbvz** [comment]
Closing this issue since we have removed the `security.workspacesTrustedToSpecifyExecutables` setting
