### ISSUE TITLE
Revisit TypeImplementation and TypeImplementationProvider names

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#19119]
After confusion about what this feature is supposed to do we seemingly landed on 'go to implementation'. Internally and in the API we talk about 'TypeImplementationProvider' which I would like to revisit. My proposal is to just call it `ImplementationProvider` similar to how we call it `ReferenceProvider` and not TypeReferenceProvider

**Comment by mjbvz** [comment]
Ok, reverting to original ImplementationProvider name since it matches the existing naming scheme.

Fixed by #19282
