### ISSUE TITLE
Remove spanish on VS Code

### ISSUE THREAD

**Issue by Naxuh** [microsoft/vscode#191163]
Hi, I was trying for the first time Codespaces and there was a pre-installed extension named "Spanish Language Pack for Visual Studio Code" that I wanted to uninstall, but when I do so, nothing changes; in fact, the extension still appears to be installed. How can I have Codespaces completely in English?

Version: 1.81.1
Commit: 6c3e3dba23e8fadc360aed75ce363ba185c49794
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36 Edg/116.0.1938.54
Embedder: codespaces

**Comment by TylerLeonhardt** [comment]
You can run the `Configure Display Language` to set the language back to English.

Here are the docs on that:

https://code.visualstudio.com/docs/getstarted/locales#_changing-the-display-language

**Comment by Naxuh** [comment]
Thanks
