### ISSUE TITLE
No bash control in shell; unable to use ctrl+c to get out of processes

### ISSUE THREAD

**Issue by davemohla12** [microsoft/vscode#191158]
Type: <b>Bug</b>

bash: no job control in this shell

VS Code version: Code 1.81.1 (6c3e3dba23e8fadc360aed75ce363ba185c49794, 2023-08-09T22:20:33.924Z)
OS version: Darwin x64 18.7.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3720QM CPU @ 2.60GHz (8 x 2600)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|3, 2, 3|
|Memory (System)|8.00GB (0.06GB free)|
|Process Argv|-psn_0_13155467 --crash-reporter-id 49b716f6-b6e1-4ffc-8bd1-85243bc84f14|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
dart-code|Dar|3.70.0
flutter|Dar|3.70.0
awesome-flutter-snippets|Nas|4.0.1
LiveServer|rit|5.7.9
svelte-vscode|sve|107.10.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
vsccc:30803844
282f8724:30602487
89544117:30613380
showlangstatbar:30737416
03d35959:30757346
57b77579:30736110
pythonfmttext:30731395
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
gsofa:30804715
pythonnosmt12:30797651
pythonidxptcf:30805731
pythonnoceb:30805159
dsvsc013:30795093
dsvsc014:30804076
diffeditorv2:30812749

```

</details>

**Comment by davemohla12** [comment]
Sorry for my short ticket description.

Here's more information.

I have a MacBook Pro running Mojave OS and am running Visual Studio Code 1.8.1.

When I open up my terminal, it says "bash: no job control in this shell". See the attached screenshot. 

When I start a process such as "npm run dev", I am unable to stop it using ctrl+c. Instead, it just shows ^C and keeps the process running as shown in the attached screenshot.

To exit the process, I have to click the trash can next to the terminal which crashes VS Code and causes me to have to restart it. 

I have searched on Google for a fix and tried adding "set -m" to my .bash_profile file and to my .bashrc file but neither of those solved the issue. 

My standard Mac terminal works fine and ctr+c works there so it seems like an issue with VS Code. VS Code was working fine in earlier releases. I tried downgrading but I am unable to. When I download an earlier version and try to install it, it says I'm still on 1.8.1. 

Appreciate any help you can provide. 

![1](https://github.com/microsoft/vscode/assets/13370303/fc1fd942-24f3-4f36-8bf6-6b3b5b3feefb)
![3](https://github.com/microsoft/vscode/assets/13370303/fb5d2072-717f-44f2-b676-65f9b91df22b)

**Comment by meganrogge** [comment]
try updating vs code

**Comment by davemohla12** [comment]
I clicked 'Check for updates' and it says there are currently no updates available. See screenshot.

![Screen Shot 2023-08-24 at 3 54 17 PM](https://github.com/microsoft/vscode/assets/13370303/bc0765c7-b907-4d5c-b41d-26acb987a32e)

Also, I'm on 1.81.1 and per the VS Code download site [here](https://code.visualstudio.com/updates/v1_81), it looks like it's the latest version.  

![Screen Shot 2023-08-24 at 3 55 52 PM](https://github.com/microsoft/vscode/assets/13370303/9db858e9-2061-424d-b4f4-f33887dd3523)

**Comment by meganrogge** [comment]
@deepak1556 any thoughts?

**Comment by deepak1556** [comment]
Merging to https://github.com/microsoft/vscode/issues/184713
