### ISSUE TITLE
Unexpected attempts to execute a command

### ISSUE THREAD

**Issue by Kitomanari** [microsoft/vscode#191152]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.81.1
- OS Version: Windows_NT ia32 10.0.19044

Steps to Reproduce: -

I'm developing my extension and I encountered some unexpected bug which is being going on for a long time during my development process of the new update.

Whenever I select an item in the Tree View "Command List", VS Code throws me an error stating that the command `undefined` wasn't found, trying to execute it. **I don't** have any commands which should be executed by selecting an item. Moreover, **I don't** even have something related to executing a command in my code:

```ts
const commandList: CommandItem[] = [];
for (const command of await Command.list({ authToken, botID })) commandList.push(new CommandItem(command));

const commandListProvider = new CommandListProvider(commandList);

createTreeView(TreeView.CommandList, { treeDataProvider: commandListProvider })
        .onDidChangeSelection(async (selectedCommand) => {
            const selection = selectedCommand.selection[0];
            if (!selection) return;

            const { commandID } = selection.command;
            const { commandCode } = await Command.get({ authToken, botID }, commandID);
            
            console.log(`Opening a command (${commandID})...`);
            await openTextDocument({
                content: commandCode,
                language: 'bds'
            });
            console.log(`The command was opened: ${commandID}`);
        });

class CommandListProvider implements TreeDataProvider<CommandItem> {
    constructor(public readonly commandList: CommandItem[]) {}

    getTreeItem(element: CommandItem): TreeItem | Thenable<TreeItem> {
        return element;
    }

    getChildren(): ProviderResult<CommandItem[]> {
        return this.commandList;
    }
}

class CommandItem extends TreeItem {
    constructor(public readonly command: Request.Response.Commands) {
        const { commandName, commandTrigger } = command;

        super(commandName, TreeItemCollapsibleState.None);
        this.description = commandTrigger;
    }
}
```
![image-249.png](https://github.com/microsoft/vscode/assets/70456337/dab844e5-eddc-4bfb-b813-751838f1ee39)

**Comment by alexr00** [comment]
@Kitomanari it looks like your `CommandItem`, which appears to extend `vscode.TreeItem` has a bad type overlap with `vscode.TreeItem`:

https://github.com/microsoft/vscode/blob/d79823e42c70da0f5f43b0586b8b3dd13c1011a9/src/vscode-dts/vscode.d.ts#L11575-L11582

If you change the name of your `command` property in `CommandItem` then you should stop getting this error.
