### ISSUE TITLE
code-tunnel / code-tunnel-oss is not built under any circumstances

### ISSUE THREAD

**Issue by etna** [microsoft/vscode#191166]
Does this issue occur when all extensions are disabled?: N.A

- VS Code Version: All versions
- OS Version: All OSes

Steps to Reproduce:

1. Build and package VScode using the instructions in https://github.com/microsoft/vscode/wiki/How-to-Contribute
2. Check the output directory
3. /path/to/output/<OS type>/bin contains a code-oss binary, but no code-tunnel-oss binary, causing code-oss tunnel to fail with ENOENT

**Comment by connor4312** [comment]
You will separately need to build the CLI and include it with your package (`cargo build` in the CLI folder).
