### ISSUE TITLE
Quick search - text highlighting not disappearing in notebooks

### ISSUE THREAD

**Issue by andreamah** [microsoft/vscode#191125]
1. Create a notebook that has the following string: `tex text` and open it.
2. Use the quick text search to look for `tex` by entering `% tex` in the file quickpick. Let this load.
3. Add a `t` at the end of the string so that it says `% text`
4. Notice that the highlight for `tex` is still there despite how the current query is for `text`

**Comment by osortega** [comment]
Closing in favor of: https://github.com/microsoft/vscode/issues/195165
