### ISSUE TITLE
[html] autocomplete should produce more context-specific results

### ISSUE THREAD

**Issue by smalllong** [Microsoft/vscode#19114]
- VSCode Version: 1.8.1

Steps to Reproduce:

When I type '<' in a &lt;html&gt;&lt;/html&gt;, the full version visual studio would give me an assist of &lt;head&gt; and &lt;body&gt;. However, in vscode, all the tags(including inappropriate tags) will appear, which is not concise.

**Comment by aeschli** [comment]
duplicate of #375
