### ISSUE TITLE
do not support EventSource

### ISSUE THREAD

**Issue by rocketRobin** [Microsoft/vscode#19117]
- VSCode Version: Code 1.8.1 (ee428b0eead68bf0fb99ab5fdc4439be227b6281, 2016-12-19T14:49:23.350Z)
- OS Version: Windows_NT ia32 6.1.7601

---

Steps to Reproduce:

1. javascript intellesence do not support EventSource
2.

**Comment by mousetraps** [comment]
@mjbvz - looks like [EventSource](https://developer.mozilla.org/en-US/docs/Web/API/EventSource) is missing from [lib.dom.d.ts](https://github.com/Microsoft/TypeScript/blob/master/lib/lib.dom.d.ts)

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript#13666
