### ISSUE TITLE
Handle right arrow on quick search menu

### ISSUE THREAD

**Issue by andreamah** [microsoft/vscode#191110]
repro:

1. use the quick search by opening the file picker and typing `% ` followed by any text you want to search. ie: `% text`
2. wait for result. On a result, press the right arrow on your keyboard.
3. :bug: nothing happens, but this should open the editor in the background.

**Comment by eleanorjboyd** [comment]
do I have to enable something / set a setting? Not seeing those search results come up.

**Comment by andreamah** [comment]
You can just run the `Quick Text Search` command in the command palette and it should set up the picker for it. Then, beginning to type should show results.
