### ISSUE TITLE
Port forwarding not working to remote ssh host

### ISSUE THREAD

**Issue by dales** [microsoft/vscode#191169]
@connor4312 I have tried the latest version

```
Version: 1.82.0-insider (Universal)
Commit: a0377f0c51dbb2d3188565cdf35e89929f864e65
```

And I still cannot connect to my react dev server using port forwarding into my ssh remote

_Originally posted by @dales in https://github.com/microsoft/vscode/issues/190859#issuecomment-1691121307_

**Comment by connor4312** [comment]
Duplicates https://github.com/microsoft/vscode/issues/190859
