### ISSUE TITLE
Typescript: "This workspace specifies executables."

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#19112]
I just got the latest version opened in our repo and the following popup came up:

![image](https://cloud.githubusercontent.com/assets/22350/22238198/70071bf6-e210-11e6-896d-4d7c576245d8.png)

I had no idea where it came from or why it was happening. Only after having opened the settings I found similar language, so I deduced this must be TypeScript.

The message is at best very ambiguous. It doesn't even mention what feature it belongs to.

cc @dbaeumer

**Comment by joaomoreno** [comment]
Additionally, when clicking Review Settings, the basic JSON experience for `settings.json` opens up, not the recently created settings UI. cc @sandy081

**Comment by dbaeumer** [comment]
cc @kieferrm as well.

**Comment by sandy081** [comment]
@joaomoreno JSON file opens because of the setting `workbench.settings.openDefaultSettings` is set to `false`.

**Comment by kieferrm** [comment]
This is not specific to typescript. The platform checks if a workspace defines settings that are being used to determine executables. In your workspace this was the `typescript.tsdk` setting.  Please file separate feature requests with how to improve the messaging.
