### ISSUE TITLE
Test: Chrome extension

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#19110]
We have never done a bug bash/testplan-item for the Chrome extension, so I'd really appreciate someone taking a few minutes to look at it.

Complexity: 3

- [x] Any OS @joaomoreno 
- [x] Any OS @isidorn 

I'm especially interested in the experience of getting started. Grab a web project that you have sitting around, or clone some random hello world project, and see if you can debug it with the extension, with sourcemaps and everything working. Or you can look at the [other debug testplan-items for this sprint](https://github.com/Microsoft/vscode/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20label%3Atestplan-item%20label%3Adebug), especially #19096.

Use this vsix for testing: 
[debugger-for-chrome-2.4.3.vsix.zip](https://github.com/Microsoft/vscode/files/725800/debugger-for-chrome-2.4.3.vsix.zip)

**Comment by chrisdias** [comment]
@roblourens is there a new version of the extension to test? i think i'm hitting https://github.com/Microsoft/vscode-chrome-debug/issues/333 I simply get "debug adapter process has terminated unexpectedly".

i'm using insiders 1.9.0-insider, commit fbea777 and v 2.4.3 of the extension from above.
