### ISSUE TITLE
Can't set c files to open with vscode as default option on windows 11

### ISSUE THREAD

**Issue by VedresDavid** [microsoft/vscode#191194]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:  1.81.1
- OS Version: Windows 11 22621.2215

Steps to Reproduce:

1.  Right click on a file with a .c extension
2.  Click on open with,  then select visual studio code
3.  The option to always use vscode and not just once does not appear, even though it does for other file types like java

I did check the windows settings for default apps, went to the "by file extension" menu and .c was not there as an option either.

I attached 3 images. One showing that you can't set vscode to be used always for c files (it wants to use notepad instead).
The second image shows the same method works for a java file. The third image shows that in the windows settings there's no .c option to set default apps by file extension.
![Screenshot 2023-08-24 123605](https://github.com/microsoft/vscode/assets/72158592/0296198e-3ab3-47cf-ab80-5a59347ab0fb)
![Screenshot 2023-08-24 123622](https://github.com/microsoft/vscode/assets/72158592/ed744566-43df-4127-88d9-c05d6e952831)
![Screenshot 2023-08-24 123722](https://github.com/microsoft/vscode/assets/72158592/c8e96f5e-e04c-4c9a-8d87-4e69434a5f0a)

**Comment by joaomoreno** [comment]
I have no idea why that is on your machine, seems to work fine for me:

![image](https://github.com/microsoft/vscode/assets/22350/16ccb7c9-10d2-422f-8506-4f41ca9efaf4)

Please open a support ticket with the Windows team. Thanks!
