### ISSUE TITLE
Tabs in editor not work

### ISSUE THREAD

**Issue by cmplx** [Microsoft/vscode#1911]
The editor does not work tab, open only one tab

**Comment by AndrewNatoli** [comment]
I've never seen tabs in vscode. You're referring to how Sublime and Atom look, right? VSCode gives you the "working files" menu on the sidebar and also the ability to flip between recent files with ctrl+tab, but I don't recall seeing physical tabs.

**Comment by joaomoreno** [comment]
Code doesn't have tabs.

**Comment by thiagolucio** [comment]
I think tabs is basic on web editors. I dont understand why is a problem to put inside vscode this option. Sorry mi english.

**Comment by egamma** [comment]
duplicate of #224
