### ISSUE TITLE
Existing launch.json not recognized

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode#19124]
Version 1.9.0-insider
Commit 61a56dbf6e80b6732381349e4654e3ae5f0710f4
Date 2017-01-24T08:05:06.845Z

- clone https://github.com/Microsoft/vscode-css-languageservice.git
- open workspace, go to the debug viewlet

The config drop down says: 'No configurations', not recognizing the existing Node launch config.
![image](https://cloud.githubusercontent.com/assets/6461412/22241501/e809e444-e21f-11e6-9abc-6f8b6a37511a.png)

**Comment by isidorn** [comment]
Dup of https://github.com/Microsoft/vscode/issues/19130
