### ISSUE TITLE
Markdown header panel doesnt reveal 4th level header previews

### ISSUE THREAD

**Issue by noahehall** [microsoft/vscode#191257]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.82.0-insider
ad94cf18189746d2e942fda257950901049b3af3
x64
- OS Version:  ubuntu

Steps to Reproduce:

1.  open a super long markdown
2. in the reveal panel, the 4th level headers and beyond are skipped

- header panel thingy
![image](https://github.com/microsoft/vscode/assets/10324554/b10cd784-59f5-418a-b570-fa4d782237eb)

- outline view
![image](https://github.com/microsoft/vscode/assets/10324554/a3407920-5dee-40c1-af3e-3495b3b59f0c)

**Comment by mjbvz** [comment]
Please share the text of a markdown file that demonstrates this issue

**Comment by noahehall** [comment]
Here is the file in the screenshot

https://github.com/noahehall/multicloud/blob/develop/providers/aws/services/Storage/ebs.md

**Comment by mjbvz** [comment]
Thanks. Seems to work for me:

<img width="536" alt="Screenshot 2023-08-31 at 11 03 11 AM" src="https://github.com/microsoft/vscode/assets/12821956/4bac22e9-7e61-49dc-ba16-584b23eda867">

Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

**Comment by noahehall** [comment]
@mjbvz it doesn't work in the header panel

**Comment by noahehall** [comment]
@mjbvz this issue seems to be fixed with the latest code-insiders

![image](https://github.com/microsoft/vscode/assets/10324554/3cb0604a-3efb-49d8-8ed2-8e75293920ff)
