### ISSUE TITLE
Close pages that match regex or pattern

### ISSUE THREAD

**Issue by Luviz** [microsoft/vscode#191235]
Hi! 
This is more like a extension then a feature, however currently I don't have time to develop the extension although it sounds like good hobby project to learn how vs-code extensions works.

It's exactly as the title mentions, you get a prompt where you write something like the examples blow and for each match on open editors it will close them.

e.g.
```
// close all test files
specs
```
```
// close  all typescript files    
*ts
```
```
 // a bit to long to type but closes all file open under that folder
**/components/**/*.*
```
Here I don't have a regex example but having the support would be nice as well.

Another feature would be a history. 

As I mention ATM moment I'm too busy with work, but I think I might pick it up around December. That is if nobody have developed by then.

To whoever decides to pick this up. 
You are awesome, thank you!

**Comment by aiday-mar** [comment]
Hi @andreamah, not sure if I should assign this to you. Feel free to change.

**Comment by andreamah** [comment]
You should be able to make an extension for this using the `TabGroups` API https://stackoverflow.com/a/75192905/16253823. Unfortunately, since there isn't any action for our team on this issue, I will close it as unplanned.

**Comment by Luviz** [comment]
That looks simple enough. Thanks for the reference, I think I'll be able to develop an extension based on the reference.

Thank you for your time.
