### ISSUE TITLE
China State-owned enterprises plagiarize the software

### ISSUE THREAD

**Issue by TestLi01** [microsoft/vscode#191279]
Only Chinese ip can access this website : [CEC-IDE](https://cecide.digitalgd.com.cn/monorepo/app-front/developer)

![微信图片_20230825125832](https://github.com/microsoft/vscode/assets/143157610/4625dafa-5fbe-435e-aa40-26e43c072ce6)

**Comment by pbuff07** [comment]
Really？I also can not access the website via vpn.

**Comment by panmili** [comment]
![image](https://github.com/microsoft/vscode/assets/38884335/34f8cb98-87ac-4855-974c-d452935e8d2d)
I am from China and cannot visit now. I am moved and ashamed of this matter

**Comment by Phoebe0** [comment]
Eeeeee.
it's like a joke

**Comment by TestLi01** [comment]
The web site is temporarily down.But the download link is still there: [CEC-IDE](https://cecide-static.digitalgd.com.cn/cecide/release/prod/CEC-IDE-Setup-win32-x64.exe);
![up-ce9a6ee89ba763170d876cadbb6a710f7f8](https://github.com/microsoft/vscode/assets/143157610/5ecd3bff-063a-446a-b5df-7b0e74d32b93)
The company name is [China Electronics Information Industry Group Co](https://www.cec.com.cn/en)

**Comment by so1ve** [comment]
Shame...

**Comment by FeletexGee** [comment]
Some Chinese officials and some ignorance Chinese always claim projects like this are independently developed by China,e.g.Harmony OS.However they are just implement of existing open-source projects.Actions like this are seemingly ridiculous,and I hate them.They actually harm the healthy growth of Chinese software industry.🤣

**Comment by FeletexGee** [comment]
> Really？I also can not access the website via vpn.

Yup,do you know GFW?Just use proxy services providing nodes in China.That would be helpful

**Comment by justlazydog** [comment]
China No.1, vscode suck. 😆

**Comment by rhwong** [comment]
This pirated software even requires payment to use the premium version.
### Mocking
But there's no need to be ashamed, it's not us who did it.
Many self righteous fools in this world.

**Comment by GCS-ZHN** [comment]
Shamed on it!

**Comment by yusancky** [comment]
duplicated #191229

**Comment by bmphjhu906** [comment]
暗示红色要完

**Comment by HyalineSoft** [comment]
The shameful Chinese product

**Comment by zijiwork** [comment]
That's strange  https://github.com/dnsjia/luban

**Comment by TestLi01** [comment]
> duplicate #191229

**Comment by MicroCBer** [comment]
请不要再继续用此事件轰炸 vscode issue 区了，特别是在[已经有 issue](https://github.com/microsoft/vscode/issues/191229) 报告了此问题的基础上，这将会对 VSCode Maintainer 造成很大困扰，并且也不能实际解决问题。如果你对此感到失望，应该对此部门进行投诉，而不是在 vscode 评论区投放垃圾 issue 和评论。

Please refrain from bombarding the VSCode issue tracker with this incident, especially considering that the issue has already been reported [here](https://github.com/microsoft/vscode/issues/191229). Continuing to do so will cause significant distress to the VSCode Maintainer and will not effectively solve the problem. If you are disappointed with this situation, I suggest filing a complaint against the department instead of creating spammy issues and comments in the VSCode comment section.

**Comment by hecktlaspha** [comment]
![I~C1M96Y3JCB{5U8FP_OF$P](https://github.com/microsoft/vscode/assets/102513399/3099143e-5d99-4a9a-bcb6-bb9926353e96)
I think this is the most powerful plugin in the world.
i wonder what if somebody write WebGL or Rust with this IDE(?)
`javascript::Float64Array`, `rust::{f64, i64, u64}` might come in the blacklist for the sensitive '64'.

**Comment by Jai-wei** [comment]
支持国产！支持中国！收复台湾！统一世界！

**Comment by yuluoqianmu** [comment]
No wonder that America executes sanctions to China,  as a Chinese developer， I feel shame of this.

**Comment by johnfans** [comment]
> 请不要再继续用此事件轰炸 vscode issue 区了，特别是在[已经有 issue](https://github.com/microsoft/vscode/issues/191229) 报告了此问题的基础上，这将会对 VSCode Maintainer 造成很大困扰，并且也不能实际解决问题。如果你对此感到失望，应该对此部门进行投诉，而不是在 vscode 评论区投放垃圾 issue 和评论。
> 
> Please refrain from bombarding the VSCode issue tracker with this incident, especially considering that the issue has already been reported [here](https://github.com/microsoft/vscode/issues/191229). Continuing to do so will cause significant distress to the VSCode Maintainer and will not effectively solve the problem. If you are disappointed with this situation, I suggest filing a complaint against the department instead of creating spammy issues and comments in the VSCode comment section.
只要别发新的issue不就行了。在同一个issue下面叫评论comment，就是用来发表意见的，对maintainer没啥影响，又没违反社区规范。而且有新的证据尽管提交没啥毛病。

**Comment by Hcreak** [comment]
狗日的自主研发 丢人丢到国外了

**Comment by SnowGuest** [comment]
Please do not discuss irrelevant issues in the issue area, which will cause trouble for the vscode team to solve product problems

**Comment by c-poet** [comment]
对国内套壳现象感到恶心，从芯片、浏览器、开发语言到现在的IDE都标榜“自研”。国内又禁了github大部分IP，担心后面这些人直接从github搬代码到国内收费，希望国际上所有向开源致敬的公司和个人能联合起来打压这些“强盗”公司。

**Comment by F7YM** [comment]
丢脸……

**Comment by Mr-Blue-a** [comment]
丢脸

**Comment by houzinu** [comment]
oh oh
