### ISSUE TITLE
Editor viewport should not jump around when typing

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#19126]
Testing #19082 

* Set up a markdown file side-by-side with its preview
* Go to a certain location in the editor
* Press Enter
> Notice: The editor viewport jumps around.

![jumpy-editor](https://cloud.githubusercontent.com/assets/5047891/22241718/e16e94b2-e220-11e6-9737-9ccb1e9aa264.gif)

**Comment by alexandrudima** [comment]
This also happens when typing any text (not just newline)

![jumpy-editor-2](https://cloud.githubusercontent.com/assets/5047891/22241848/6f50444c-e221-11e6-8cfe-8390d46bc13f.gif)

**Comment by alexandrudima** [comment]
This is a lot worse when editing comments for example (the viewport will jump in a way that the cursor is not visible anymore):

![jumpy-editor-3](https://cloud.githubusercontent.com/assets/5047891/22242947/a3e80c4a-e225-11e6-8ace-9adad698dda4.gif)

**Comment by mjbvz** [comment]
Thanks. Certainly annoying.

I think i've identified and fixed the root cause (`webview-pre.js` also scrolls the preview page which was not being correctly handled). Let me know if you still see this.
