### ISSUE TITLE
window.openFilesInNewWindow  not working as excpected

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#19125]
Refs: https://github.com/Microsoft/vscode/issues/18609

- VSCode Version: 1.9 insider
- OS Version: Windows 10

Steps to Reproduce:

See screen cast. I would have expected to see the file opened in the new window. 

![cast](https://cloud.githubusercontent.com/assets/1931590/22241666/a476e6d6-e220-11e6-947f-977b4b81bf38.gif)

In addition I think it is not clear what should happen if the setting is on and a file from the same workspace is opened with File > New. Should it open in a new window or in the existing one.

**Comment by dbaeumer** [comment]
Same is true for window.openFoldersInNewWindow. If set to true Open Folder is still replacing the current folder in the active window instead of opening a new one.

**Comment by bpasero** [comment]
@dbaeumer you seem to be setting this as workspace setting and not user setting. Unfortunately this can not be defined in workspace settings. Once we have a story to not show some workspace settings I would add it there (https://github.com/Microsoft/vscode/issues/8772)

**Comment by dbaeumer** [comment]
@bpasero would have help if part of the test description :-)

**Comment by bpasero** [comment]
@dbaeumer took me a while to figure this out myself ;)
