### ISSUE TITLE
KeyBoard binding to last edited cursor Feature Request

### ISSUE THREAD

**Issue by akshayat** [Microsoft/vscode#19120]
- VSCode Version: Code 1.8.1 (ee428b0eead68bf0fb99ab5fdc4439be227b6281, 2016-12-19T14:49:23.350Z)
- OS Version: Windows_NT ia32 10.0.14393

Best if last edited location key board binding is available in visual studio code. The same was eclipse has <kbd>Ctrl + q</kbd>.

**Comment by mousetraps** [comment]
You mean like this? 
![image](https://cloud.githubusercontent.com/assets/762848/22271526/d31a2d26-e249-11e6-822e-769b745eb9e1.png)

I'm on a Mac right now, but the Windows equivalent should be `Alt + LeftArrow` or `Alt + RightArrow` - see https://code.visualstudio.com/shortcuts/keyboard-shortcuts-windows.pdf

Closing since it appears we already have this behavior, but lmk if you were meant something different, and we can reopen. Happy coding!

**Comment by akshayat** [comment]
Not this, This feature lets you navigate to the previous location where your cursor was. 

Suppose you have written some code and you went to many files to debug some related code. Now you want to go to the place you were editing/writing last, it would be tedious to navigate back many time. Better if we have a key binding which instead of getting to last location take us to last edited location skipping all last traveled locations.

Let me know if you want to understand more.

**Comment by mousetraps** [comment]
Aha! Cool idea - thanks for clarifying :smiley:

**Comment by borekb** [comment]
Just want to confirm that this is indeed a very useful feature when one gets used to it :)

<kbd>Ctrl+Q</kbd> currently conflicts with `workbench.action.quickOpenView` but it's probably the most standard shortcut out there; IntelliJ IDEs use <kbd>Ctrl+Shift+Backspace</kbd> which is also quite a nice shortcut.

**Comment by akshayat** [comment]
<kbd>Ctrl+q</kbd> is occupied, that was example how eclipse uses. According to me `Backspace` signifies something to delete.

So I suggest <kbd>Alt+Shift+LeftArrow</kbd> because <kbd>Alt+LeftArrow</kbd> takes us back and this will take us long back.

However developers can design and chose the more appropriate key bindings.

**Comment by chengtie** [comment]
Hello, I would like to know if this feature has been added... It is a very useful feature, and exists in most of the IDEs...

Cheers

**Comment by tlvenn** [comment]
Same question as @chengtie , is this supported already somehow ? I am really missing this.

**Comment by borekb** [comment]
I use [this extension](https://marketplace.visualstudio.com/items?itemName=krizzdewizz.goto-last-edit-location) as a workaround, works relatively well although I still think this should be a core feature of VSCode :)

**Comment by tlvenn** [comment]
Ya using this extension as well now however I wish it would maintain a list of the last edited locations and pressing multiple times the shortcut would allow you to go back to those. I think this is how Intellij is working if I am not mistaken.

**Comment by edvinv** [comment]
For current editor you can use CTRL+Z, CTRL+Y.

**Comment by akshayat** [comment]
@edvinv What if you are in different file?

**Comment by edvinv** [comment]
@akshayat yes of course, it works only for current opened file.

any way, it will be great to have two separate keybindigs: for current file last edit position and for overall last edit position.

**Comment by wcamarao** [comment]
Would love to see this too, one of the features I miss the most from IntelliJ.
Could be `Ctrl/Cmd + Alt/Opt + [` to go back and `Ctrl/Cmd + Alt/Opt + ]` forward.

**Comment by thernstig** [comment]
@mousetraps Any progress on this? This is definitely one of the most useful productivity features I miss from other editors. Once you have this in place, you can drill down into definitions/files and look around code to learn something and then in one fell swoop get back to where you left off.

**Comment by kkorus** [comment]
+1

**Comment by raskri** [comment]
+1

**Comment by jaynadeau** [comment]
ctrl plus or minus modifies window zoom level for me...
would also like to see ctrl+q behaviour

**Comment by dingbo8128** [comment]
I like this short cut very much in eclipse, hope there also has in vscode

**Comment by bpasero** [comment]
@alexandrudima I have this almost working, but I need a better event from the editor to find out that a position change happened because of editing.

**Comment by bpasero** [comment]
Added a new command "Go to Last Edit Location" (workbench.action.navigateToLastEditLocation) with keybinding (chord) `Cmd+K Cmd+Q`

**Comment by noinkling** [comment]
@bpasero Can you explain how this is different to the "soft undo" command already implemented?

**Comment by sibay** [comment]
whats the difference to "workbench.action.navigateBack"? I used this before to jump to the last edit location.

**Comment by Borg8** [comment]
> Added a new command "Go to Last Edit Location" (`workbench.action.navigateToLastEditLocation`) with keybinding (chord) `Cmd+K Cmd+Q`

Thank you, this is very useful feature.
But if you already implemented it, do it 100%. Not navigate to only last edit location (like it implemented in eclipse), but navigate deeper in edit location history when pressed again (like it, in very useful way, implemented in inteliJ).
