### ISSUE TITLE
testing.openTesting is not working for testing explorer now

### ISSUE THREAD

**Issue by jdneo** [microsoft/vscode#191272]
Version: 1.82.0-insider (user setup)
Commit: a0377f0c51dbb2d3188565cdf35e89929f864e65
Date: 2023-08-24T05:32:35.024Z
Electron: 25.5.0
ElectronBuildId: 23084831
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.19045

Noticed that this setting is now controlling the `TEST RESULT` panel. Some users hoping that this setting can still work for the testing explorer: https://github.com/microsoft/vscode-java-test/issues/1597

**Comment by Tyriar** [comment]
This works, but it might be good to deprecate and go with a more robust approach? For example I don't think it's possible to open both the panel and explorer on start/fail, or open just the explorer on fail.
