### ISSUE TITLE
tasks.json support buggy?

### ISSUE THREAD

**Issue by MrAndMrsK** [Microsoft/vscode#1913]
I have the tasks.json file below.  I wish there was an integrated deploy task, and that we could natively have multiple top-level tasks defined that each can have their own command but according to various posts out there, we cannot and this kind of workaround is recommended.  But it isn't working for me.  

You can see that I'm asking to show the output, but when I run the build task via the keyboard shortcut or the <kbd>ctrl</kbd>+<kbd>shift</kbd>+<kbd>p</kbd> menu, the spinner spins, the first command seems to get run (because I can see the output files get created) but the second doesn't run and doesn't generate any output to the output pane which VSCode makes visible.  The third never runs either.  If I move the `echo 42` to the first position then I'll see 42 in the output window *sometimes* but it is inconsistent.  If `echo 42` is first and `tsc` is second, tsc does not get run.  The deploy.sh does generate output when run in the terminal, but even if it is first, it doesn't get run or generate output 

Also sometimes, the busy spinner in the bottom left corner gets stuck in the spinning mode, but the "Terminate Running Task" does nothing to fix it.  I don't know if this is a task that is really still running, or just a UI that falls out of sync.  Restarting VSCode fixes it.

I even tried wrapping the args like `"args": ["\"echo 42\""]` because in the terminal `bash -c "echo 42"` and `bash -c ".\Deploy.sh"` work fine.  This seems to have no effect sometimes but other times I get "bash: echo 42: command not found" in the output pane.  I suspect there's some kind of delay in refreshing the tasks.json contents into VSCode's memory or something but I haven't really figured it out - I'm mostly just baffled.

```json
{
    "version": "0.1.0",
    "command": "bash",
    "isShellCommand": true,
    "showOutput": "always",
    "args": [ "-c" ],
    "tasks": [
        {
            "taskName": "Typescript Compile",
            "suppressTaskName": true,
            "isBuildCommand": true,
            "args": ["tsc"],
            "problemMatcher": "$tsc",
            "showOutput": "always"
        },
        {
            "taskName": "Deploy",
            "suppressTaskName": true,
            "isBuildCommand": true,
            "showOutput": "always",
            "args": ["${workspaceRoot}/Deploy.sh"]
        },
        {
            "taskName": "Done",
            "suppressTaskName": true,
            "isBuildCommand": true,
            "showOutput": "always",
            "args": ["echo 42"]
        } ]
}
```

**Comment by dbaeumer** [comment]
You can only mark one task as a build task. The system should report and error if you mark more than one. So Ctrl+Shift+B can only trigger the Typescript Compile OR Deploy OR Done. Not all of them.

The not stopping spinner is a different problem. I will look into it.

**Comment by dbaeumer** [comment]
I fixed the problem with not echoing 42. Will be available in the next release.

**Comment by MrAndMrsK** [comment]
Ok, thanks, but then how are the other build tasks get invoked?  Are we supposed to have multiple files instead or something?  I don't get it.

**Comment by dbaeumer** [comment]
The only way to call additional task is to use F1 > Run Task > .... We currently don't support to bind arbitrary keyboard shortcuts to tasks.

If you want to call all three tasks with on short cut all I can recommend is to have a task entry all which calls a script that runs all three tasks.
