### ISSUE TITLE
executing vscode in wsl throws error

### ISSUE THREAD

**Issue by jonnytest1** [microsoft/vscode#191309]
- VS Code Version: 1.81.1
- OS Version: windows_NT x64 10.0.22621
    - "Ubuntu 22.04.2 LTS (WSL)

Steps to Reproduce:

1. run `code .`
2. get 
![image](https://github.com/microsoft/vscode/assets/13507796/2696d355-5e8d-4d80-8876-2aa569eb101f)
(yesterday it still worked)

🤔 is that the wrong executable ?

**Comment by jonnytest1** [comment]
small update the code binary over at C:\Program Files\Microsoft VS Code\bin\code is the one calling the Code.exe

**Comment by aeschli** [comment]
This is a WSL issue: https://github.com/microsoft/WSL/issues/9905
