### ISSUE TITLE
Node 

### ISSUE THREAD

**Issue by Manderindlii** [microsoft/vscode#191399]
Type: <b>Feature Request</b>

Hello everyone

I try to start coding on my main pc but i can't run Javascript programms. Because of the following error:
PS C:\Andrin\Coding\Code\Tutorials> node "c:\Andrin\Coding\Code\Tutorials\FreeCodeCampTut.js"
node : Die Benennung "node" wurde nicht als Name eines Cmdlet, einer Funktion, einer Skriptdatei oder eines ausführbaren Programms erkannt. Überprüfen Sie die Schreibweise des Namens, oder ob der Pfad 
korrekt ist (sofern enthalten), und wiederholen Sie den Vorgang.
In Zeile:1 Zeichen:1
+ node "c:\Andrin\Coding\Code\Tutorials\FreeCodeCampTut.js"
+ ~~~~
    + CategoryInfo          : ObjectNotFound: (node:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

I tried everything to get rid of that but I wasn't able to.

Could you please help me find a solution. I would be very glad.

Thanks you and have a good day

VS Code version: Code 1.81.1 (6c3e3dba23e8fadc360aed75ce363ba185c49794, 2023-08-09T22:22:42.175Z)
OS version: Windows_NT x64 10.0.22621
Modes:

**Comment by dbaeumer** [comment]
@Manderindlii it looks like you don't have node installed. See https://nodejs.org/en

**Comment by Manderindlii** [comment]
> @Manderindlii it looks like you don't have node installed. See https://nodejs.org/en

I had node installed thats why I was so confused. I was able to solve the Problem by manually running my program in the terminal, with the command "node programm.js". After this code runner also worked. 
Regardless thanks for your help.
