### ISSUE TITLE
Cannot open settings in non-folder mode

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#19135]
- VSCode Version: 1.9.x
- OS Version: macOS

Steps to Reproduce:

1. create new window
2. open settings

Observe:
![2017-01-24_11-09-36](https://cloud.githubusercontent.com/assets/1898161/22242940/99fe357e-e225-11e6-8b32-cb7641b1ef45.png)

**Comment by sandy081** [comment]
Duplicates #19121
