### ISSUE TITLE
Nerd Fonts using the Material set should take up only one character but does two

### ISSUE THREAD

**Issue by trajano** [microsoft/vscode#191379]
Type: <b>Bug</b>

The Material set of nerd fonts as documetned in https://github.com/ryanoasis/nerd-fonts/wiki/Glyph-Sets-and-Code-Points are at `f0001` tp `f1af0` note that may be represented by two unicode characters but only one should appear.

This results in an extra gap when using material nerd fonts on the intergrated terminal

VS Code version: Code 1.81.1 (6c3e3dba23e8fadc360aed75ce363ba185c49794, 2023-08-09T22:22:42.175Z)
OS version: Windows_NT x64 10.0.22621
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz (12 x 3696)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.94GB (8.15GB free)|
|Process Argv|C:\\Users\\trajano\\AppData\\Local\\Packages\\Microsoft.WindowsTerminal_8wekyb3d8bbwe\\LocalState\\settings.json|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (29)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-autohotkey-plus|cwe|2.7.1
eslint-disable-snippets|drK|1.4.1
EditorConfig|Edi|0.16.4
prettier-vscode|esb|10.1.0
vscode-monorepo-workspace|fol|1.3.1
selected-lines-count|gur|1.4.0
terraform|has|2.27.1
plantuml|jeb|2.17.5
azure-pipelines|ms-|1.208.0
vscode-docker|ms-|1.26.0
python|ms-|2023.14.0
vscode-pylance|ms-|2023.8.40
remote-containers|ms-|0.304.0
remote-ssh|ms-|0.105.2023080715
remote-ssh-edit|ms-|0.86.0
remote-wsl|ms-|0.81.0
azure-account|ms-|0.11.5
powershell|ms-|2023.6.0
remote-explorer|ms-|0.5.2023071709
vsliveshare|ms-|1.0.5883
vscode-react-native|msj|1.11.2
vscode-xml|red|0.26.1
vscode-yaml|red|1.14.0
sonarlint-vscode|Son|3.20.2
even-better-toml|tam|0.19.2
vscode-mdx|uni|1.4.0
volar|Vue|1.8.8
vscode-typescript-vue-plugin|Vue|1.8.8
vscode-proto3|zxh|0.5.5

</details>

**Comment by trajano** [comment]
Also no issues with Windows Terminal

**Comment by Tyriar** [comment]
This looks like an issue with our old terminal backend "winpty", going forward we are focusing our efforts on the new backend "conpty" which is build by the Console team at Microsoft and should fix many issues with the terminal under Windows. You will need to upgrade Windows to use conpty. You can read more about ConPTY [here](https://github.com/Microsoft/vscode/issues/57803#issuecomment-449495423) and [here](https://github.com/microsoft/vscode/wiki/Terminal-Issues#why-did-you-close-my-issue).

/duplicate https://github.com/Microsoft/vscode/issues/45693
