### ISSUE TITLE
[theme] avoid flashing when starting up with a new OS color scheme

### ISSUE THREAD

**Issue by vaibhavshn** [microsoft/vscode#191307]
Type: <b>Bug</b>

When I have light and dark mode themes configured and have a default theme which is light in my config, and I turn on dark mode in my system (macOS), and then start VS code, I see the default theme which is light flash before turning black. Ideal behaviour would be no flash of default theme when starting up.

Duplicate of https://github.com/microsoft/vscode/issues/95190.

Edit: reopened as the previous issue was locked.

VS Code version: Code 1.81.1 (6c3e3dba23e8fadc360aed75ce363ba185c49794, 2023-08-09T22:40:25.698Z)
OS version: Darwin arm64 23.0.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|4, 2, 2|
|Memory (System)|16.00GB (0.04GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
astro-vscode|ast|2.3.0
vscode-tailwindcss|bra|0.9.13
vscode-eslint|dba|2.4.2
gitlens|eam|14.2.1
prettier-vscode|esb|10.1.0
figma-vscode-extension|fig|0.2.7
fluent-icons|mig|0.0.18
vscode-filesize|mkx|3.1.0
color-highlight|nau|2.5.0
vscode-mdx|uni|1.4.0
errorlens|use|3.13.0
vim|vsc|1.25.2

</details>

**Comment by aeschli** [comment]
Themes come with theme files, and we need to load them. As we can only do this once the extension host is up and loading can take a while, we show the colors that we had on shutdown.
That's why you see the flashing.

The fix would be to cache the preferred light/dark themes as well.

**Comment by aeschli** [comment]
To verify:
- have the OS is dark mode
- in VS Code, set `"window.autoDetectColorScheme": true`
- theme switches to dark theme based on the OS color mode
- close VS Code
- switch the OS theme from dark to light 
- open VS Code
- verify that the VS Code window starts with light theme, without any flickering
