### ISSUE TITLE
Terminal multiple action icons overlap

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#191332]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:  Insiders
- OS Version: macOS

![Image](https://github.com/microsoft/vscode/assets/876920/421798b0-dd84-4399-b7eb-ceab65ffdb0a)

**Comment by joyceerhl** [comment]
@tyriar how can this be verified?

**Comment by Tyriar** [comment]
@joyceerhl oh it can't anymore as the feature is disabled in copilot. I'll move it to September to be verified then

**Comment by rzhao271** [comment]
Hi @Tyriar, is the issue verifiable now?
