### ISSUE TITLE
Synchronized scrolling should follow selection.active and not selection.start

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#19133]
Testing #19082

`selection.active` is where the cursor is

* make a multiline selection going up: in this case selection.start == selection.active. The preview is correctly synchronized with the editor's cursor.
* make a multiline selection going down: in this case selection.end == selection.active. The preview is not scrolling.

![selection-active](https://cloud.githubusercontent.com/assets/5047891/22242666/8273db80-e224-11e6-9f24-c2988bb2ea39.gif)

**Comment by mjbvz** [comment]
Thanks! The change looks good
