### ISSUE TITLE
Launches are not shown

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode#19130]
- Make sure that you have some programs to launch in your launch.json
- Go to Debug view
- There are no launches

**Comment by sandy081** [comment]
@kieferrm FYI. Looks like re-filtering scoped config models is not appending the root scope to the contents. For now, I excluded re-filtering the scoped models. 

But, I think filtering/re-filtering is very specific to Workspace settings, so right thing is to make filtering local to Workspace settings rather than making it generic to all configs. I will be adding tests to these models in the debt week. I will clean it up then and also add tests.

**Comment by kieferrm** [comment]
@sandy081 There are pros and cons for pushing it up or down the abstraction ladder. I'd be in favor of keeping the original loose coupling. That would mean to redefine `refilter` within scope models.
