### ISSUE TITLE
Toggling Command Center does not resize the title bar

### ISSUE THREAD

**Issue by daviddossett** [microsoft/vscode#191325]
Toggling the command center works, but the title bar height is stuck until the window is resized. I also noticed some issues where I had to click twice to open the command center once enabled. The command center input then disappears while the command center quick pick opens.

https://github.com/microsoft/vscode/assets/25163139/a36320d8-bc21-4479-9401-5154b49e8a4d

**Comment by jrieken** [comment]
Maybe an electron update regression
