### ISSUE TITLE
can't save a file with ".cpp" or ".py"

### ISSUE THREAD

**Issue by shubham4039** [microsoft/vscode#191368]
Type: <b>Feature Request</b>

i can't provide ".py" OR ".cpp" to any file because whenever i try to open these files it shows "unable to write file 'file path' (No Permissions(FileSystemError): Error: EPERM: operation not permitted, open 'file path')

VS Code version: Code 1.81.1 (6c3e3dba23e8fadc360aed75ce363ba185c49794, 2023-08-09T22:22:42.175Z)
OS version: Windows_NT x64 10.0.16299
Modes:

**Comment by lramos15** [comment]
Does this work when you try to do it via the windows explorer? These errors come from the file system and not VS Code.
