### ISSUE TITLE
Vscode, have you collaborated with CEC-IDE?!

### ISSUE THREAD

**Issue by JesseZ332623** [microsoft/vscode#191361]
![v2-c189827c9980e58d7d5040eb20ca7abb_720w](https://github.com/microsoft/vscode/assets/101250851/e0398280-c7bf-4533-9281-96f9fb806b20)

像啊，很像啊。。。。。

**Comment by JesseZ332623** [comment]
> Does this issue occur when all extensions are disabled?: Yes/No

**Comment by Y-ASLant** [comment]
哈哈哈
