### ISSUE TITLE
Feature Request: Add Built-in Text Search API for Extensions

### ISSUE THREAD

**Issue by ykdojo** [microsoft/vscode#191383]
# Feature Request for VS Code: Text Search API

## Summary

VS Code currently lacks a built-in API for text-based search within files. While the `findFiles` method allows for file discovery based on glob patterns, there is no straightforward way to perform text-based searches within those files programmatically.

## Problem Statement

Developers often have to resort to using Node.js file system APIs or other libraries to read file content and then apply their own search algorithms. This adds extra overhead and complexity to extensions that aim to provide advanced search features.

## Proposed Solution

Introduce a new API method, tentatively named `findTextInFiles`, that allows for text-based search within files. This method could accept parameters like search query, file type, and directory, and return a list of matches with their respective line numbers.

## Use Cases

1. Advanced search features in custom extensions.
2. Automated code analysis and refactoring.
3. Enhanced navigation features.

## Benefits

- Simplifies the development process for extension developers.
- Provides a unified way to perform text-based searches.
- Could potentially speed up search operations by leveraging VS Code's internal optimizations.

## Additional Context

This feature request aims to fill a gap in the current VS Code API and make it more robust and developer-friendly.

**Comment by ArturoDent** [comment]
There are two proposed api's you can test now:

```plaintext
findTextInFiles
textSearchProvider
```

See if they what you want.  Not a lot has happened with them lately though.  There must be issues about them here.

**Comment by ykdojo** [comment]
Thank you @andreamah. Are they currently only available in Insiders, or is it available in all current versions of VS Code?
