### ISSUE TITLE
Files using CRLF breaks shows as having no line breaks in Search Results in Editor

### ISSUE THREAD

**Issue by falkonline** [microsoft/vscode#191347]
Does this issue occur when all extensions are disabled?: Yes

Version: 1.81.1 (user setup)
Commit: 6c3e3dba23e8fadc360aed75ce363ba185c49794
Date: 2023-08-09T22:22:42.175Z
Electron: 22.3.18
ElectronBuildId: 22689846
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Windows_NT x64 10.0.19044

If searching files and use Search Results to Editor with files with CRLF line breaks, The Results in Editor tab  shows the entire file as on one line (no line breaks). 

Particularly noticeable if using Regex $ or \n. The line breaks are not matched. 

- VS Code Version: 1.81.1
- OS Version: Windows 10

Steps to Reproduce:

1.  have file(s) with CRLF
2. Go to Search mode (Control Shift F)
3. Use Regex mode (alt-R)
4. type in $
5. Alt Enter to have Results to Editor
6. No end of lines found

**Comment by Cnily03** [comment]
"xxxx\r\nxxx\r\n" won't match `/$/`. `$` means end of the string, but not end of a line. And cannot using independently. You can try `\r?\n` when searching in regex mode.

**Comment by falkonline** [comment]
Always used $ for end of line, but just looked it up and its 'engine dependent'.

Tried with \r?\n or even \n, and its doesn't find a match. 

You can see in the attached screen shot, the search results tab seems to consider the file as all one line (some crude censoring by me). 

![vscode001](https://github.com/microsoft/vscode/assets/57379123/074fc613-0842-4b75-b63c-9569a838c531)

Even with Line Context at zero, the entire document is in the result.  (test.txt, has regular line breaks, the M8N03268 is the demonstration).

**Comment by andreamah** [comment]
I can't seem to reproduce the bug where it's all on one line. `$` seems to be matching okay.
![Recording 2023-08-28 at 12 53 00](https://github.com/microsoft/vscode/assets/31675041/3036dd8a-307c-41d9-a496-63522aaaddea)

**Comment by falkonline** [comment]
Looks like a titled this incorrectly, I appears to be only for files that use a single 0D (CR) for line break.  CRLF (0D0A) has no issue.

**Comment by andreamah** [comment]
I believe that CR line endings aren't supported. See here: https://github.com/microsoft/vscode/issues/35797

**Comment by falkonline** [comment]
Would the best course to close this as duplicate?

**Comment by andreamah** [comment]
Yes. /duplicate https://github.com/microsoft/vscode/issues/35797
