### ISSUE TITLE
Link detection fails around punctuation characters in Output windows

### ISSUE THREAD

**Issue by kriswuollett** [microsoft/vscode#191398]
I'd think that any quote-like character that appears before a detected URL in places like the Terminal or Output windows should be trimmed from the end of the URL as a heuristic. Because for example, currently the trailing backtick is included in the file URL, so an error of "Cargo.toml`" is not will appear in a dialog upon click following:

```
Caused by:
  failed to parse manifest at `/Users/kris/Code/some-project/Cargo.toml`
```

See https://github.com/rust-lang/rust-analyzer/issues/15518

**Comment by kriswuollett** [comment]
Also noticed absolute file paths that have a trailing comma because it is middle of a sentence also doesn't work. Even if this like this are legal paths or URLs, it would be more likely wrong contextually if it was sentence punctuation. A bare question mark also probably wouldn't hurt being dropped from contextual links since that would be an empty query anyways.

**Comment by Tyriar** [comment]
This should already be working:

<img width="645" alt="Screenshot 2023-08-28 at 9 14 12 AM" src="https://github.com/microsoft/vscode/assets/2193314/7123bcde-ec5d-490d-b18d-3e088ea50d19">

The panic links you showed at the bottom also should work:

<img width="674" alt="Screenshot 2023-08-28 at 9 15 52 AM" src="https://github.com/microsoft/vscode/assets/2193314/f81159c6-9fff-4d0e-9dda-cdbfff41f696">
<img width="505" alt="Screenshot 2023-08-28 at 9 16 27 AM" src="https://github.com/microsoft/vscode/assets/2193314/8b095144-604a-4f6a-a752-cc1f066d0187">

It's not clear if the first one is relative to the workspace or some rust internals, if it's the latter a link provider could be implemented in the rust extension to handle this.

Any more details on reproducing this? Could you see if this happens in Insiders also? https://code.visualstudio.com/insiders

If it still does not work on Insiders you can enable the trace log level via the command palette, hover the lines in question and then copy the Output > Terminal output channel.

**Comment by kriswuollett** [comment]
> Any more details on reproducing this? Could you see if this happens in Insiders also? https://code.visualstudio.com/insiders
> 
> If it still does not work on Insiders you can enable the trace log level via the command palette, hover the lines in question and then copy the Output > Terminal output channel.

I'll try and get back soon with more info on how to reproduce. However your tests above are with a user shell Terminal. My examples were from things like the `Rust Analyzer Client` and `Rust Analyzer Language Server` output windows. I assume they share a lot of code, but technically not the same thing. I think it may be as easy as checking out a Rust open-source project that uses a Rust workspace, and just changing one of the sub-crates to specify a crate dependency that does not exist to get that cannot read `Cargo.toml` error.

**Comment by Tyriar** [comment]
@kriswuollett oh do you mean they're in the output panel, not the terminal panel? The output panel is totally separate and lacks a lot of the features of the terminal.

**Comment by kriswuollett** [comment]
> @kriswuollett oh do you mean they're in the output panel, not the terminal panel? The output panel is totally separate and lacks a lot of the features of the terminal.

Yes, let me update the title since I made an assumption that the Terminal would behave the same where I saw the issue in the Output windows.

Would it be rather straightforward for the Output windows to be brought to parity with the Terminal windows w.r.t. link detection?

Would it be something like the following such that the responsibility can be taken over by the extension owner of the output window(s):

https://github.com/microsoft/vscode/blob/42ce7b7a2eeaa102ee40605a446174fce71c285a/src/vs/workbench/contrib/terminalContrib/links/browser/terminalLinkProviderService.ts#L22-L35

**Comment by Tyriar** [comment]
@kriswuollett it would be quite tough unfortunately as they're completely separate codebases (output based on monaco, terminal based on [xterm.js](https://github.com/xtermjs/xterm.js)). Here's the out of scope request that tracked what you're asking for https://github.com/microsoft/vscode/issues/107314, and some more link requests https://github.com/microsoft/vscode/issues/163778, https://github.com/microsoft/vscode/issues/149153.

If you need good link detection you need to use a terminal, something an extension can do which might be relevant is to create a background terminal and then show it on command:

https://github.com/microsoft/vscode/blob/cd7388f4dad4c7102713db8ebb16488f070433ea/src/vscode-dts/vscode.d.ts#L11012-L11019

Or just buffer the data and delay creating the terminal all together until asked.

Closing this out as it's up to an extension to route the content to the terminal for good link support.
