### ISSUE TITLE
sticky scroll widget: Improve the code that prevents folding indicator flickering

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode#191319]
Follow up from https://github.com/microsoft/vscode/pull/190873

[_setFoldingHoverListeners](https://github.com/microsoft/vscode/blob/0a3bb7ef2db3b52f6c88d864e1c000e3acff3604/src/vs/editor/contrib/stickyScroll/browser/stickyScrollWidget.ts#L184-L185)

has overly complex code to prevent that folding indicator transition in again after a refresh when the mouse is still on top of the folding marker

Clicking on a folding marker refreshes the sticky scroll widget. New folding indicators nodes are created. The transition is activated.

This is how it looks without the current fix:
![Image](https://github.com/microsoft/vscode/assets/6461412/e5e55413-2496-4f3f-b400-086b30f90210)

Ideally rebuilding the sticky scroll widget can be minimized.

**Comment by aiday-mar** [comment]
This has ever since been fixed
