### ISSUE TITLE
Support regex and other search types in quick search

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#191328]
These and their keybindings would be handy:

![Image](https://github.com/microsoft/vscode/assets/2193314/779c05a8-1b46-4554-ac0e-696f70e2368b)

For example I just tried to do this:

- ctrl+shift+f (open quick search)
- Type `on.+Command`
- alt+r (attempting to toggle regex)

**Comment by eleanorjboyd** [comment]
Thank you for submitting your feature request and everyone who considered it! Unfortunately, this issue did not receive enough votes over the allotted time, and so we are closing the issue. @Tyriar if you feel this is important enough feel free to re-open but I will close for now, thanks!
