### ISSUE TITLE
Selecting in the markdown preview with the mouse should set the selection in the .md editor

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#19131]
Testing #19082

I would expect that double clicking a word or selecting some words in the markdown preview would:
1. Select the corresponding .md source range
2. Reveal the range

![editor-selection-not-set](https://cloud.githubusercontent.com/assets/5047891/22242241/e13d4f0e-e222-11e6-8a96-906704a7e3b2.gif)

**Comment by Naereen** [comment]
It could help but this is somewhat not mandatory.

**Comment by mjbvz** [comment]
This could now be implemented by a [markdown extension](https://code.visualstudio.com/docs/extensionAPI/api-markdown)

Closing as extension candidate
