### ISSUE TITLE
Download extension only for current project

### ISSUE THREAD

**Issue by eccentricOrange** [microsoft/vscode#191362]
How can I download an extension in VS Code and make sure that it doesn't apply across the current profile?

Use case: I have a Python profile, and I've set it up to usually not install Jupyter extensions. However, I need them for one project. So how can I install the Jupyter extensions to just this one workspace, and not affect my Python profile?

**Comment by sandy081** [comment]
You can disable that extension and enable it only for the current workspace.

<img width="701" alt="image" src="https://github.com/microsoft/vscode/assets/10746682/9e6f95eb-2941-4953-bb78-e2afcf629ac1">
