### ISSUE TITLE
Unhelpful description of 'hotExit' setting values 

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#19137]
- VSCode Version: 1.9.x
- OS Version: macOS

The descriptions of the three value "off", "onExit", "onExitAndWindowClose" are identical and sound rather awkward: "Whether hot exit is enabled...".

![2017-01-24_11-12-06](https://cloud.githubusercontent.com/assets/1898161/22243139/54977c6a-e226-11e6-8cdd-98d0306ae16b.png)

Why not use a similar wording as all the other multi valued settings: "Controls whether unsaved files are remembered."

**Comment by Tyriar** [comment]
I copied auto save's implementation that doesn't have individual value descriptions:

![image](https://cloud.githubusercontent.com/assets/2193314/22258999/8ae286b0-e218-11e6-8676-b2d3e2960800.png)

Do we support this?

![image](https://cloud.githubusercontent.com/assets/2193314/22259060/b614296a-e218-11e6-9e05-962823087707.png)

I'll make the change to "Controls...", as it's no longer a boolean.

**Comment by weinand** [comment]
@aeschli is there a way to have different descriptions for the individual enum values?

**Comment by aeschli** [comment]
Yes, use enumDescriptions as seen [here](https://github.com/Microsoft/vscode/blob/87ae03d9804350f195395e5362a78289d8d14d9b/extensions/html/package.json#L146)

**Comment by Tyriar** [comment]
Thanks @aeschli :smile:

**Comment by Tyriar** [comment]
@aeschli that's for extensions, it doesn't appear to be supported in `IConfigurationNode` though?

```ts
export interface IConfigurationNode {
	id?: string;
	order?: number;
	type?: string | string[];
	title?: string;
	description?: string;
	properties?: { [path: string]: IConfigurationPropertySchema; };
	allOf?: IConfigurationNode[];
	overridable?: boolean;
}
```

**Comment by aeschli** [comment]
It is part of the IConfigurationPropertySchema  (extends IJSONSchema, where enumDescriptions is defined)

**Comment by Tyriar** [comment]
Ah it's working now, I think this may have been a case of TypeScript being flaky as intellisense was telling me it wasn't there and there was an error.

**Comment by bpasero** [comment]
I was not aware we could have description for individual setting values, that is very cool. I will adopt that for my settings next sprint 👍
