### ISSUE TITLE
Test: actions in the notifications accessible view

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#191344]
Refs #189486

- [x] Windows @andreamah 
- [x] macOS @ulugbekna 
- [x] Linux @chrmarti 

Complexity: 3

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23191344%0A%0A&assignees=meganrogge)

---

Last iteration, we introduced an accessible view for notifications https://github.com/microsoft/vscode/issues/187114.

This iteration, we have actions in the accessible view so a screen reader user can take those from there. 

These actions include:
- navigating to the `next` or `previous` notification
- dismissing the notification
- taking any action present on the notification toast
- disabling the accessible view hint

To test this:
- Trigger some notifications and focus one.
- You should hear a hint about opening the notification in the accessible view.
- Open the accessible view via `alt+f2`.
- `Shift+tab` to the actions and try them out.
- Verify that as you take actions, the notifications are closing properly.

**Comment by andreamah** [comment]
👏
