### ISSUE TITLE
Open the file in a new tab when Ctrl and click on the variable

### ISSUE THREAD

**Issue by arunkumar413** [microsoft/vscode#191301]
Currently if I press Ctrl and click on the react component instead of opening the file in a new tab it's replacing the currently opened tab.  Could yo u please allow it to open the file in a new tab

**Comment by IllusionMH** [comment]
That's because your current file is just preview (you should see cursive file name in tab)

VS Code replaces previews, but won't replace opened file.
You can disable preview editors or double click on the tab to make it opened before navigation.

**Comment by arunkumar413** [comment]
@IllusionMH I'd like the ctrl click work similar to how we open a link in a new browser tab. Currently it's replacing the currently opened tab.

**Comment by mjbvz** [comment]
@IllusionMH is correct. Try setting `"workbench.editor.enablePreview": false` to disable [preview editors](https://code.visualstudio.com/docs/getstarted/userinterface#_preview-mode)
