### ISSUE TITLE
[Bug] Tela preta no terminal do VS Code 

### ISSUE THREAD

**Issue by murillobtw** [microsoft/vscode#191426]
Type: <b>Bug</b>

o meu terminal do vscode ficou todo preto derrepente, ele esta normal e quando fui abri-lo estava preto, nao consigo resolver e nao posso voltar a minha rotina por causa disso.

My vscode terminal suddenly went all black, is that normal and when I opened it was black, I can't resolve it and I can't get back to my routine because of this.
![2023-08-23](https://github.com/microsoft/vscode/assets/90806102/43143f05-3de3-445d-9bba-bf31db8cb0ca)

VS Code version: Code 1.81.1 (6c3e3dba23e8fadc360aed75ce363ba185c49794, 2023-08-09T22:22:42.175Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 5600X 6-Core Processor              (12 x 3700)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.89GB (6.67GB free)|
|Process Argv|--crash-reporter-id 74ce9143-439b-4406-a24f-d6f86ccdd59a|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
turbo-console-log|Cha|2.9.6
gitlens|eam|14.2.1
auto-rename-tag|for|0.1.10
copilot|Git|1.105.350
prettify-json|moh|0.0.3
vscode-language-pack-pt-BR|MS-|1.81.2023081609
vscode-thunder-client|ran|2.10.5
vscode-icons|vsc|12.5.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
py29gd2263:30792226
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
vsccc:30803844
282f8724:30602487
89544117:30613380
showlangstatbar:30737416
pythonfmttext:30731395
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
gsofb:30804716
pythonnosmt12:30797651
pythonidxpt:30805730
pythonnoceb:30805159
dsvsc013:30795093
dsvsc014:30804076
diffeditorv2:30821572

```

</details>

**Comment by murillobtw** [comment]
![2023-08-23](https://github.com/microsoft/vscode/assets/90806102/1a206a94-fda1-403b-adca-61b3d20fca82)

**Comment by jcbritobr** [comment]
Please write the pn in english.

**Comment by Tyriar** [comment]
@jcbritobr can you share your settings.json file?

**Comment by jcbritobr** [comment]
> @jcbritobr can you share your settings.json file?

here it is
```json
{
    "editor.minimap.enabled": false,
    "window.titleBarStyle": "custom",
    "window.zoomLevel": 0.0,
    "go.toolsManagement.autoUpdate": true,
    "editor.fontFamily": "JetBrains Mono",
    "editor.fontSize": 13,
    "editor.fontWeight": "700",
    "terminal.integrated.fontSize": 13,
    "go.inlayHints.assignVariableTypes": true,
    "go.inlayHints.compositeLiteralFields": true,
    "go.inlayHints.compositeLiteralTypes": true,
    "go.inlayHints.functionTypeParameters": true,
    "go.inlayHints.parameterNames": true,
    "go.inlayHints.rangeVariableTypes": true,
    "workbench.iconTheme": "vscode-icons",
    "terminal.integrated.commandsToSkipShell": [
        "language-julia.interrupt"
    ],
    "julia.symbolCacheDownload": true,
    "julia.enableTelemetry": true
}
```

**Comment by rzhao271** [comment]
Confirmed that `terminal.integrated.enableImages` is disabled by default.
I have now enabled terminal gpu acceleration and images, though I'm not sure whether I'll run into the issue on this machine.
