### ISSUE TITLE
Test: Shift hover on sticky scroll shows the last line of the scope

### ISSUE THREAD

**Issue by aiday-mar** [microsoft/vscode#191449]
Refs https://github.com/microsoft/vscode/issues/178987

- [x] anyOS @kieferrm 
- [x] anyOS @hediet 

Complexity: 1

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23191449%0A%0A&assignees=aiday-mar)

---

This iteration it has been made possible to show the last line of a scope from sticky scroll. To test this feature do the following:

1. Enable sticky scroll and make sticky lines appear.
2. Press the shift key and hover over a sticky line. You should notice that the instead of seeing the first line of the scope, you see the last line of the scope.
3. Click on the line while pressing on shift, verify that the editor cursor jumps to the last line of the scope and displays it in the middle of the viewport. 

:warning: There is a known issue which is that if the mouse is already on the widget, and you press shift, it will not render the last line until you move the mouse slightly. This happens because we re-render on the editor.onMouseMove event. This issue is tracked here: https://github.com/microsoft/vscode/issues/191450.

**Comment by kieferrm** [comment]
This works nicely.
