### ISSUE TITLE
VSCode hangs when right-clicking on the activity bar with WSL plugin enabled

### ISSUE THREAD

**Issue by Larvan2** [microsoft/vscode#191419]
Does this issue occur when all extensions are disabled?: No

- Version: 1.81.1 (system setup)
- Commit: 6c3e3dba23e8fadc360aed75ce363ba185c49794
- Date: 2023-08-09T22:22:42.175Z
- Electron: 22.3.18
- ElectronBuildId: 22689846
- Chromium: 108.0.5359.215
- Node.js: 16.17.1
- V8: 10.8.168.25-electron.0
- OS: Windows_NT x64 10.0.22621
- **All previous setting has been clean up**

![image](https://github.com/microsoft/vscode/assets/78135608/3695458c-767b-40b3-9436-c30da5aeaa70)

### Description
When opening VSCode and the WSL plugin is enabled, right-clicking on the activity bar on the left side （position 1. in figure） will cause VSCode to freeze completely.

After this happens, VSCode becomes unresponsive to any clicks or key presses. The only way to recover is to right-click on the top menu bar for serval times （position 2. in figure）.

### Steps to Reproduce:

1. Open a project using VSCode （whether in WSL or not）
2. Enable the WSL plugin
3. Right click on the activity bar on the left side of the interface 
4. VSCode will hang and become unresponsive

![image](https://github.com/microsoft/vscode/assets/78135608/4a51d3d0-9157-49ed-9546-7b7504667511)

**Comment by Larvan2** [comment]
> it also happens in a local Window?  

Yes.

> It you disable the WSL extension, this does not happen?

This does not happen when WSL extension disable.

This is the error output in the devtools console, hopefully it will be helpful for resolving this issue.
![image](https://github.com/microsoft/vscode/assets/78135608/5eb53209-8010-4920-8697-185e6a3626a4)

**Comment by Larvan2** [comment]
The Remote Explorer in WSL extension my cause this issue, it has a different label filed.

I recorded this it might be helpful.

https://github.com/microsoft/vscode/assets/78135608/7709be91-1bfa-490b-8094-2f93007d3d63

**Comment by aeschli** [comment]
@Larvan2 Thank you very much!!

The bug is here: https://github.com/microsoft/vscode/blob/90a6fa75f940370737e4249b603886b4a9743011/src/vs/workbench/api/browser/viewsExtensionPoint.ts#L540

**Comment by Larvan2** [comment]
Thank you for solving this issue.
