### ISSUE TITLE
I would expect tab area to shrink when tabCloseButton: "off"

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#19147]
Refs #18771

1. "workbench.editor.tabCloseButton": "off"
2. Tab area still leaves an empty space in the right for the close button even though I just disabled it
3. I would expect the tab area to shrink as I believe that is the primary motive for hiding the clsoe button - to save space!

I know that you keep that space to show when a file is dirty, but if a file gets dirty the tab area should grow automatically imho

**Comment by bpasero** [comment]
The primary motivation for not showing the close button is actually to prevent accidental closing. Otherwise https://github.com/Microsoft/vscode/issues/15364
