### ISSUE TITLE
vscode thinks that folder with multiple line name are fo=

### ISSUE THREAD

**Issue by ttoommxx** [microsoft/vscode#191417]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.81.1
- OS Version: Linux

Steps to Reproduce:

1. create a folder with multiple lines (in my case, I created a file called """
new
line
"""
2. right click and open with VScode
3. VScode removed the new line in between and thinks that it's called "new line". Because this file does not exists it creates it opens a new file called "new line" and ignore the fact that I was trying to open the folder

![Screenshot from 2023-08-27 15-26-02](https://github.com/microsoft/vscode/assets/58073175/cd3ddd24-a109-47eb-accb-3a93fa49dad4)

**Comment by ttoommxx** [comment]
@bpasero yes. Or better, if I do `mkdir 'new\n line'` it will just create a folder with such name (won't escape "n"), if instead I do `mkdir new\n line` it will give me an error. But if I create a folder on Nautilus copying pasting the lines above, then it will create a folder with 2 lines and the bug will be reproducible. Now sure how Nautilus interprets the new line. Maybe an hidden flag? This might explain why VScode panics

**Comment by bpasero** [comment]
I can open such a folder just fine from the command line. For that to work I need to run the path like this:

`code-insiders ./Hello\ World$'\n'$'\n'More\ Things`

For a folder called "Hello World<new line>More Things"

How do you get an "Open in VS Code" option to appear in the context menu?

![image](https://github.com/microsoft/vscode/assets/900690/5388506d-aa45-479b-afb4-81e2ec7d717e)

**Comment by ttoommxx** [comment]
On Fedora Gnome, the context menu has a "open with" entry
![Screenshot from 2023-09-04 13-48-07](https://github.com/microsoft/vscode/assets/58073175/c40af4b1-7679-43cd-aabf-852a116445bc)

**Comment by bpasero** [comment]
Given it works from the command line, I suspect its an issue with how Gnome calls us.
