### ISSUE TITLE
Right click on tab close button immediatly closes the tab

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#19145]
Refs: #18771

1. showTabs
2. right click on the tab X button. The tab is immediatly closed on mouse down
3. I would expect the context menu to be shown as is in all editors

**Comment by isidorn** [comment]
Right click on tab close button still enlarges the x as if it is being clicked on -> reopening, removing milestone

**Comment by bpasero** [comment]
I will piggy back on https://github.com/Microsoft/vscode/issues/19369 if you want to remove that it reacts on right click :).
