### ISSUE TITLE
Test: sorting JSONC on save 

### ISSUE THREAD

**Issue by aiday-mar** [microsoft/vscode#191455]
Refs https://github.com/microsoft/vscode/issues/175893

- [x] anyOS @mjbvz 
- [x] anyOS @alexdima 
- [x] anyOS @brettcannon (Optional) 

Complexity: 1

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23191455%0A%0A&assignees=aiday-mar)

---

This iteration it has been made possible to sort JSONC files on save using the inbuilt JSONC sorting mechanism.

1. Enable the setting `json.sortOnSave.enable`.
2. Open a JSON or JSONC file, make some changes to make the file dirty. You can add comments (block or line) in the file.
3. Save the file and verify that the file is sorted in alphabetical order and formatted. 
4. Verify that the sorting behaves as expected:
- Is the json object sorted alphabetically?
- Is the json object formatted as you would expect?
- Are the comments in the JSONC files sorted as you would expect? Currently the comments are associated to the JSON properties below them. The only exceptions are when the comments start on the same line as a property or are the last comment in a JSON scope, in which case they are associated to the last property before them. 

:warning: There is a known issue which is that when there is a trailing comma in the file, the sorting mechanism fails its sorting. This issue is tracked here: https://github.com/microsoft/vscode/issues/178229

**Comment by brettcannon** [comment]
One thing that surprised me is when there's no way to have a section comment, e.g.:
```jsonc
{
    // Big block comment

    "b": false, // more B stuff
    "C": 42, // C stuff
    // stuff
    "A": true
    // B stuff
}
```

will sort `// Big block comment` with `"b"` instead of leaving it in-place.
