### ISSUE TITLE
'reindent all lines' removes leading space in comment

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode#19142]
Testing #19091:
In a typescript file:
```typescript file
/*---------------------------------------------------------------------------------------------
 *  Copyright (c) Microsoft Corporation. All rights reserved.
 *  Licensed under the MIT License. See License.txt in the project root for license information.
 *--------------------------------------------------------------------------------------------*/

'use strict';
class A {
}
```
- use the 'Reindent all lines' command
- check out the file comment. The space before '*' has been removed
```
/*---------------------------------------------------------------------------------------------
*  Copyright (c) Microsoft Corporation. All rights reserved.
*  Licensed under the MIT License. See License.txt in the project root for license information.
*--------------------------------------------------------------------------------------------*/
```

**Comment by rebornix** [comment]
Block comment's indentation is currently handled by onEnterRules and not filtered out in Indentation Rules. There are actually two ways to mitigate this issue

1. Honor onEnterRules in Reindent lines, which is a breaking change
2. Enhance Indentation Rules for TypeScript. The indentation rule set I mentioned in https://github.com/Microsoft/vscode/issues/19140#issuecomment-274913963 still doesn't fix this problem. A proper fix is likely filtering block comments in `unIndentPattern` if possible.

**Comment by NearAutomata** [comment]
Just wanted to ask whether this is still being worked on as it is still buggy even more than one year after the initial report of the issue.

**Comment by JayAndCatchFire** [comment]
FWIW, this affects pretty much all languages with doc comments, not just typescript.  I experienced this bug today in a PHP file.

**Comment by jpw** [comment]
Yes, I'm not sure the `typescript` label is relevant here.

My use case is I'm about to sort out lots of formatting issues in a rough-looking ES6 codebase that does at least have JSDoc comments, and I cant use "Reindent lines" to do so without messing up the comments (thereby annoying linters, and/or changing the code style). I will have to subsequently do a regexp find & replace on all the block comments (also regexp may vary per file), or a lot of copy & pasting around :(


Also see [this stackoverflow issue](https://stackoverflow.com/questions/54137002/how-can-i-change-how-vs-code-indent-multi-line-comments) (I am not the author of that).
