### ISSUE TITLE
Cannot quit VSCode

### ISSUE THREAD

**Issue by scolear** [microsoft/vscode#191445]
Type: <b>Bug</b>

Steps to reproduce:
- open vscode from a terminal, using `code .` in a local folder
- try to close window using CMD+W, or CMD+Q, or by clicking red button on window header, or Menu bar-> Close Window, or Menu bar -> Close Folder, or Menu bar -> Quit Visual Studio Code. 
- nothing happens
- even after closing terminal where `code` was opened from

VS Code version: Code 1.81.1 (Universal) (6c3e3dba23e8fadc360aed75ce363ba185c49794, 2023-08-09T22:20:33.924Z)
OS version: Darwin arm64 22.5.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|2, 3, 2|
|Memory (System)|16.00GB (0.03GB free)|
|Process Argv|--crash-reporter-id 119aebae-8248-479f-b12d-893ac5f1205e|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (42)</summary>

Extension|Author (truncated)|Version
---|---|---
systemd-unit-file|coo|1.0.6
vscode-eslint|dba|2.4.2
gitlens|eam|14.2.1
LogFileHighlighter|emi|2.16.0
prettier-vscode|esb|10.1.0
copilot|Git|1.105.350
copilot-chat|Git|0.6.0
vscode-github-actions|git|0.26.1
vscode-pull-request-github|Git|0.70.0
terraform|has|2.27.1
clarity-lsp|hir|1.7.2
latex-workshop|Jam|9.13.4
vscode-docker|ms-|1.26.0
vscode-dotnet-runtime|ms-|1.7.1
isort|ms-|2023.10.1
python|ms-|2023.14.0
vscode-pylance|ms-|2023.8.40
jupyter|ms-|2023.7.1002162226
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.17
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-slideshow|ms-|0.1.5
remote-containers|ms-|0.304.0
remote-ssh|ms-|0.102.0
remote-ssh-edit|ms-|0.86.0
cmake-tools|ms-|1.15.31
cpptools|ms-|1.17.4
cpptools-extension-pack|ms-|1.3.0
live-server|ms-|0.4.9
makefile-tools|ms-|0.7.0
remote-explorer|ms-|0.4.1
vsliveshare|ms-|1.0.5883
hardhat-solidity|Nom|0.7.3
postman-for-vscode|Pos|0.6.1
rust-analyzer|rus|0.3.1631
even-better-toml|tam|0.19.2
ayu|tea|1.0.5
cmake|twx|0.0.17
vscode-lldb|vad|1.9.2
vscode-todo-highlight|way|1.0.5
eno|Wsc|2.3.53
markdown-all-in-one|yzh|3.5.1

(3 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscorecescf:30445987
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
vscccc:30803845
282f8724:30602487
f6dab269:30613381
2i9eh265:30646982
showlangstatbar:30737416
03d35959:30757346
pythonfmttext:30731395
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
gsofa:30804715
pythonnosmt12:30797651
pythonidxpt:30805730
pythonnoceb:30805159
dsvsc013:30795093
dsvsc014:30804076
diffeditorv2:30812749

```

</details>

**Comment by scolear** [comment]
Maybe I should add that it only happens with this particular folder, as I have found. It has nothing special in it, two python scripts and two shell scripts. Nothing is running/being debugged, or anything like that.

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by scolear** [comment]
Thanks, I could not reproduce it with nightly.

Strangely enough, I cannot reproduce it anymore with regular `code .` now either. Going to try more and report back

**Comment by bpasero** [comment]
Ok, we can reopen then if you found steps to reproduce.
