### ISSUE TITLE
Test: Polished UX of Quick Chat

### ISSUE THREAD

**Issue by TylerLeonhardt** [microsoft/vscode#191496]
Refs: https://github.com/microsoft/vscode/issues/191491

- [x] macOS: @bpasero 
- [x] linux @rzhao271
- [x] windows: @Tyriar

Complexity: 4

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23191496%0A%0A&assignees=TylerLeonhardt)

---

This iteration we've finally settled on a UX of Quick Chat... and I want YOU to try it out. This is a very open ended TPI because I want you to explore the UX and let me know what you think...

First things first, you can open this experience with either:
* `cmd`+`shift`+`i` on macOS, `ctrl`+`shift`+`i` on Windows, `ctrl`+`alt`+`shift`+`i` on Linux
* `Chat: Open Quick Chat` command in the Command Palette
* Typing in the Command Palette a question and choosing the `Ask Copilot: blahblahblah` option
* Choosing the `Open Quick Chat` option in the Command Center

Main things that have changed/been added:
* More condensed UX: Quick Chat specific styles in the chat list
* Buttons are no longer in the title bar of the quick pick but rather inline with the input box
* "scroll-down-to-grow" behavior
* sash at the bottom of the chat
* chat no longer hides when it loses focus

Play around with it and give me any feedback you might have! Feel free to use Quick Chat for any Chat related TPIs.

**Comment by bpasero** [comment]
Love it!
