### ISSUE TITLE
Sashes in centered layout too small 

### ISSUE THREAD

**Issue by ShalokShalom** [microsoft/vscode#191408]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.81.1
- OS Version: Garuda rolling (Arch)

Steps to Reproduce:

1. Go into centered layout
2. Try to grab the sashes

I do think this happens across all display sizes, etc, but just to be sure: 

I am using a 12.5 inch at 1366x768.

Reproducibility:

Change into centered layout: View > Appearance > Centered Layout

See the handles on the side. You can resize the viewpoint with them.

In my case, they are invisible, you get the drift:

![Screenshot_20230827_083255](https://github.com/microsoft/vscode/assets/6344099/4815d999-dbdc-46c3-b03d-d8f131903ec7)

Can we increase the thickness of them, so it is simple to grab them?

They can be finicky to grab them now, since the area to do so is insanely small.

**Comment by sbatten** [comment]
Does this setting address the issue `workbench.sash.size`?

**Comment by ShalokShalom** [comment]
Yes, thanks!

**Comment by ShalokShalom** [comment]
I set it to 12. Do you consider increasing the default size? 4 seems very low as default, tbh. 
Thanks!
