### ISSUE TITLE
Sticky scroll should show the last line of the scope as soon as shift is pressed

### ISSUE THREAD

**Issue by aiday-mar** [microsoft/vscode#191450]
Currently sticky scroll shows the last line of the scope only when shift is pressed followed by a mouse move event. Pressing on shift does not automatically show the last line of the scope which it should.

**Comment by aiday-mar** [comment]
The question is how to do this, detect onkeydown and onkeyup events without listening to the document's onkeyup and onkeydown?

**Comment by aiday-mar** [comment]
Verification steps are as follows:

- Toggle editor sticky scroll
- Make sticky lines appear
- Place the mouse on the sticky line
- Press shift
- The line should immediately rerender and show the last line of the scope represented by the line

**Comment by justschen** [comment]
this is cool! didn't know we could do this + verified!
