### ISSUE TITLE
[css] text-wrap: balance is css(unknownProperties)

### ISSUE THREAD

**Issue by dzienisz** [microsoft/vscode#191458]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.81.1
- OS Version: Ventura 13.5

<img width="480" alt="Screenshot 2023-08-28 at 14 05 44" src="https://github.com/microsoft/vscode/assets/3521624/6db91cec-b712-4fa2-870e-98714ad13be0">

Steps to Reproduce:

1. write text-wrap: balance
2. observer error

**Comment by aeschli** [comment]
Support for text-wrap just got added and is in the next build.
