### ISSUE TITLE
How to implement "rename" functionality for Files and Folders - TreeView API

### ISSUE THREAD

**Issue by lucasnatanmelo** [microsoft/vscode#191484]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.81.1
- OS Version: Windows_NT x64 10.0.19042

Steps to Reproduce:

*Description:*

I am currently working on a VSCode extension where I'm using the TreeView sample and the fileExplorer.ts to create a visualization of folders within the TreeView. 
The default Explorer in VSCode provides the convenient "rename" functionality, which allows users to click on a file, select "rename" from the context menu, and then edit the file's name with it's own input UI. However, I can't find the respective API to "rename" file or folders, neither in TreeView Documentation and neither in index.d.ts, where the APIs are defined. Could you please, provide me how to achieve it or this API is not allowed for external developers?

**Comment by alexr00** [comment]
There's a feature request to allow the input box: https://github.com/microsoft/vscode/issues/97190
