### ISSUE TITLE
Unable to ssh to remote host

### ISSUE THREAD

**Issue by sarodz** [microsoft/vscode#191469]
Type: <b>Bug</b>

Note: I was unable to create a bug report after I choose the "An extension" option in the dropdown in the "Help: Report Issue..." window as it does not show any of my extensions (I do have extensions for whatever reason the bug report does not show them)

After installing 1.82.0 (insiders), I started to get the following error message:

notificationsAlerts.ts:42 Failed to connect to the remote extension host server (Error: WrappedError(WrappedError { message: "server exited without writing socket", original: "channel closed" }))

And

Could not fetch remote environment

When I use an older version (via regular VsCode) this issue does not happen.

VS Code version: Code - Insiders 1.82.0-insider (f7973f357e7c316a88e8817886f41a843021fe74, 2023-08-28T05:35:52.131Z)
OS version: Windows_NT x64 10.0.19044
Modes:
Connection to 'SSH: devlab.linepulse.ca' could not be established  WrappedError(WrappedError { message: "server exited without writing socket", original: "channel closed" })

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.72GB (6.99GB free)|
|Process Argv|--crash-reporter-id 857fed38-4fa8-49ff-b2f3-bbf104e17732|
|Screen Reader|no|
|VM|0%|

Connection to 'SSH: devlab.linepulse.ca' could not be established  WrappedError(WrappedError { message: "server exited without writing socket", original: "channel closed" })
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythontb:30258533
pythonptprofiler:30281269
vshan820:30294714
vscod805:30301674
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30404738
py29gd2263:30784851
vsclangdf:30492506
c4g48928:30535728
dsvsc012:30540252
pynewext54:30618038
vscrp:30624060
2i9eh265:30646982
showlangstatbar:30737417
ecj1e332:30687743
pythonfmttext:30716741
fixshowwlkth:30771523
showindicator:30805243
pythongtdpath:30726887
i26e3531:30792625
gsofa:30797620
welcomedialog:30812478
pythonnosmt12:30779711
pythonidxpt:30768918
pythonnoceb:30776497
copilotsettingt:30808721
dsvsc013:30777762
dsvsc014:30777825
diffeditorv2:30786206
pythonmpsinfo:30815194
dsvsc015:30821418

```

</details>

**Comment by connor4312** [comment]
Please share the full output of `Remote SSH` in the Output panel when you get into this state

**Comment by connor4312** [comment]
Thanks! What happens if you SSH in manually and run the server using this command?

```
/home/srodrigue/.vscode-server-insiders/cli/servers/Insiders-f7973f357e7c316a88e8817886f41a843021fe74/server/bin/code-server-insiders --connection-token=remotessh --accept-server-license-terms --start-server --enable-remote-auto-shutdown --socket-path=/tmp/code-insiders-49873d1b-2bdd-444c-b074-678dc2bcd959
```

**Comment by sarodz** [comment]
My bash output
```
/home/srodrigue/.vscode-server-insiders/cli/servers/Insiders-f7973f357e7c316a88e8817886f41a843021fe74/server/bin/code-server-insiders: 12: /home/srodrigue/.vscode-server-insiders/cli/servers/Insiders-f7973f357e7c316a88e8817886f41a843021fe74/server/node: not found
```

**Comment by connor4312** [comment]
It looks like the server perhaps did not get extracted fully. We can add some checks around that. I suspect deleting the `/home/srodrigue/.vscode-server-insiders/cli/servers` directory would fix it

**Comment by sarodz** [comment]
That worked thank you

**Comment by sarodz** [comment]
That worked thank you

**Comment by connor4312** [comment]
We should do an integrity check before finalizing the server directory however

**Comment by aeschli** [comment]
Verified that the SSH log contains the message `Server integrity verified` which got added by the fix
