### ISSUE TITLE
Test: Sticky Scroll Sideways Scrollable

### ISSUE THREAD

**Issue by aiday-mar** [microsoft/vscode#191446]
Refs https://github.com/microsoft/vscode/issues/163691

- [x] anyOS @meganrogge 
- [x] anyOS @hediet 
- [x] anyOS @brettcannon (Optional) 

Complexity: 1

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23191446%0A%0A&assignees=aiday-mar)

---

This iteration, it has been made possible to scroll sideways the sticky scroll widget. The setting that enables this behavior is `editor.stickyScroll.scrollWithEditor`. Follow the following steps:

1. Make sure `editor.stickyScroll.scrollWithEditor` is enabled and enable sticky scroll. Scroll in the file so that the sticky scroll text overflows (you can not see the end of the sticky lines). 
2. Scroll the editor horizontal scrollbar and make sure that in this manner you can scroll to see the full text of the sticky lines.
3. Do the following several times: scroll vertically in the editor to different scroll top positions, refresh the editor and make sure you can still see the full text of the sticky line by scrolling.
5. Disable the setting `editor.stickyScroll.scrollWithEditor`. This reverts sticky scroll behavior to the previous behavior, when sticky scroll can no longer be scrolled with the editor scrollbar. Verify that as you scroll horizontally in the editor, sticky scroll is not scrolled.

**Comment by brettcannon** [comment]
> enable sticky scroll

To help the poor managers out, do include what all the settings are as I had to go looking for what the setting was for sticky scroll. 😅 I also had to look up what "sticky scroll" was (luckily Burke had a YT short to remind me).
