### ISSUE TITLE
Refine `EnvironmentVariableScope` API

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#191438]
Some small tweaks are needed for the new `EnvironmentVariableScope`-type

* it should be an interface, not a type. 
* it lacks a jsdoc comment
* it's not clear why `workspaceFolder` can be optional?

**Comment by karrtikr** [comment]
Will correct it right away 👍

> it's not clear why workspaceFolder can be optional?

It's not something we expect all consumers to consider, as many folks may not care about applying env variables to a particular workspace. In future we may introduce other parameters as well, and consumers who don't care about it, can simply omit them:

```typescript
/**
 * The scope object to which the environment variable collection applies to.
 */
export interface EnvironmentVariableScope {
	/**
	 * Any specific workspace folder to get collection for.
	 */
	workspaceFolder?: WorkspaceFolder;
	/**
	 * Returned env collection will only be applied to these shell paths.
	 */
	shell?: string;
}
```

A consumer who only cares about shell:
```typescript
const collection = context.environmentVariableCollection.getScoped({ shell })
```

cc/ @Tyriar
