### ISSUE TITLE
macOS 11 (1107) or later required, have instead 11 (1106)

### ISSUE THREAD

**Issue by nosacs** [microsoft/vscode#191422]
Type: <b>Bug</b>

I am trying to debug a Python program/script.  It does work and I am able to run debug in an Eclipse Python perspective.   I am running w/ Python 3.10.12.

Scotts-MacBook-Pro:tk scason$ pyenv versions
  system
  3.7.7
  3.8.2
  3.9.1
* 3.10.12 (set by /Users/scason/.python-version)
  3.11.4

The following is basically the essential code...

#!/usr/bin/env python3
import random
##
from tkinter import *
from tkinter import ttk
from tkinter import messagebox

def genPW ():
    root = Tk()    <=== this is where I get the error 

    root.mainloop()

def main() :
    genPW()

if __name__ == '__main__':
    main ()

VS Code version: Code 1.81.1 (Universal) (6c3e3dba23e8fadc360aed75ce363ba185c49794, 2023-08-09T22:20:33.924Z)
OS version: Darwin x64 20.6.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4960HQ CPU @ 2.60GHz (8 x 2600)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.16GB free)|
|Process Argv|--crash-reporter-id 10247e34-3bc5-49c0-a1df-b4484583bed3|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (28)</summary>

Extension|Author (truncated)|Version
---|---|---
nodejs-bundle|1Yi|1.0.0
svelte-bundle|1Yi|1.0.0
svelte-intellisense|ard|0.7.1
vscode-django|bat|1.10.0
python-environment-manager|don|1.0.4
python-extension-pack|don|1.7.0
vscode-svelte-snippets|fiv|0.5.0
svg|joc|1.5.3
vsc-python-indent|Kev|1.18.0
python|ms-|2023.14.0
vscode-pylance|ms-|2023.8.40
jupyter|ms-|2023.7.1002162226
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.17
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-slideshow|ms-|0.1.5
cmake-tools|ms-|1.15.31
cpptools|ms-|1.17.4
cpptools-extension-pack|ms-|1.3.0
autodocstring|njp|0.6.1
vs-code-prettier-eslint|rve|5.1.0
vscode-standard|sta|2.1.3
svelte-vscode|sve|107.10.0
cmake|twx|0.0.17
intellicode-api-usage-examples|Vis|0.2.8
vscodeintellicode|Vis|1.2.30
jinja|who|0.0.8
vscode-surround|yat|1.5.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
vscaac:30438847
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyonecf:30548226
vscccc:30803845
3biah626:30602489
f6dab269:30613381
vscrp:30673768
showlangstatbar:30737416
03d35959:30757346
pythonfmttext:30731395
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
gsofa:30804715
pythonnosmt12:30797651
pythonidxptcf:30805731
pythonnoceb:30805159
synctok:30821570
dsvsc013:30795093
dsvsc014:30804076
diffeditorv2:30821572

```

</details>

**Comment by nosacs** [comment]
Previous post was not explicit that I am trying to debug using VS Code IDE.

**Comment by roblourens** [comment]
You can file this on the vscode-python extension, but please describe the problem clearly, I don't think that is spelled out in your post
