### ISSUE TITLE
Clicking on search result sets the selection in the cell and not in the output

### ISSUE THREAD

**Issue by alexdima** [microsoft/vscode#191568]
Testing #191488

* open https://github.com/donnemartin/data-science-ipython-notebooks
* enable `"search.experimental.closedNotebookRichContentResults": true`
* search for `[1, 2, 3, 4, 5]`
* click on a result in `02.08-Sorting.ipynb`
* observe the selection is set on the input code and not on the output

https://github.com/microsoft/vscode/assets/5047891/bdce58d0-66b1-48c6-91e2-283cccffcc85

```
Version: 1.82.0-insider
Commit: ebd67244fb2da33ab078bb2baa96106fda29f336
Date: 2023-08-29T05:48:32.218Z
Electron: 25.5.0
ElectronBuildId: 23084831
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Darwin arm64 22.6.0
```

**Comment by andreamah** [comment]
Seems that navigating to the result also causes it to flicker (~13 seconds in to the sceencap).
