### ISSUE TITLE
The 1st Find All References result isn't in sorted order if the UI is in a cleared state

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode#191511]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: Version: 1.81.1 (user setup)
Commit: 6c3e3dba23e8fadc360aed75ce363ba185c49794
Date: 2023-08-09T22:22:42.175Z
Electron: 22.3.18
ElectronBuildId: 22689846
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Windows_NT x64 10.0.22621
Or today's insiders.

Steps to Reproduce:

1. With TypeScript or C++, do find all references on the 2nd+ reference with the references view in it's initial or cleared state.

```typescript
function main() {
        let iii: number = 0;
        iii = 1;
        iii = 2; // find all refs here or the line above
}
```

```cpp
int main()
{
    int iiii = 0;
    iiii = 1;
    iiii = 2; // find all refs here or the line before
    return iiii;
}
```

Bug: The reference that is used to trigger the operation is placed at the top instead of being sorted by line number as expected/desired. This gets fixed the 2nd time Find All References is invoked, but starts again after the Clear button is used. I initially thought this was a bug with our C++ extension, but the existence of the issue for TypeScript leads me to believe it's a VS Code bug, but I haven't debugged it. See the screenshot:

<img width="126" alt="image" src="https://github.com/microsoft/vscode/assets/19859882/1ecbbed9-e9f3-4b7e-aecf-576beb1f57f1">

**Comment by jrieken** [comment]
@alexr00 Could this be an issue with the tree API? I have debugged this and see that I am always returning the elements sorted by line

**Comment by alexr00** [comment]
Yes, looks like it's an issue with the tree. The reference view is calling `reveal` to show the tree item before the item has been rendered (which is fine), but a side effect of that is that the item is first.
