### ISSUE TITLE
Debugging yeoman: no breakpoint is hit

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#19159]
Refs: https://github.com/Microsoft/vscode/issues/19039

* check out our code generator (https://github.com/Microsoft/vscode-generator-code)
* npm install
* generate a config to debug the yo man generator
* add a breakpoint e.g. into index.js line 43 or even the constructor
* run it
=> no breakpoint hit for me

**Comment by weinand** [comment]
@bpasero when running yeoman from the project, it was always using the globally installed code generator in `~/.npm-packages/lib/node_modules`.
After removing `~/.npm-packages/lib/node_modules/generator-code` and running `npm link` in the project folder (which creates a symbolic link in `~/.npm-packages/lib/node_modules`, hitting breakpoints worked fine.
Using `npm link` is the official way to develop and test yeoman generators.
