### ISSUE TITLE
edit text in accessible text does not match the inline completeion

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#191584]
Testing #191346

See how the word result has split into res and ult (this is placed at the end)

![Image](https://github.com/microsoft/vscode/assets/10746682/13170299-d8bf-46e4-9b51-270bf6b57d1e)

**Comment by meganrogge** [comment]
fixed

<img width="903" alt="Screenshot 2023-10-23 at 9 17 20 AM" src="https://github.com/microsoft/vscode/assets/29464607/72a14178-24bd-467c-aa52-2216b4cb9015">
