### ISSUE TITLE
Invalid PHP snippets

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#191592]
When starting VS Code is a warning about bad PHP snippets

```
[vscode.php]: One or more snippets from the extension 'php' very likely confuse snippet-variables and snippet-placeholders (see https://code.visualstudio.com/docs/editor/userdefinedsnippets#_snippet-syntax for more details)
```

I am pretty sure this the snippet below because it uses `$a` and `$b` which aren't valid variable names

https://github.com/microsoft/vscode/blob/26f41a49948c6da4eec5c93836c1c331364b54f2/extensions/php/snippets/php.code-snippets#L22-L26

**Comment by roblourens** [comment]
https://github.com/microsoft/vscode/issues/189561
