### ISSUE TITLE
Windows title flickers when changing views

### ISSUE THREAD

**Issue by lszomoru** [microsoft/vscode#191588]
Testing #191341

Switching views in the "Explorer" view - no flicker
https://github.com/microsoft/vscode/assets/3372902/4d1438a0-cb37-4815-a0e8-97ff0114d77f

Switching views in the Panel - flicker
https://github.com/microsoft/vscode/assets/3372902/b50a8bab-dfe6-41a0-8138-ebbaa5503199

Switching views in the Secondary Side Bar - flicker
https://github.com/microsoft/vscode/assets/3372902/71c2921d-4d02-4165-be50-b77104738fe1

**Comment by sandy081** [comment]
@meganrogge I am not aware of the implementation of this feature, so I do not know what to do here. I am happy to give suggestions or involve if you can give me the context.

**Comment by meganrogge** [comment]
I'll investigate. @joaomoreno also saw this issue and recommended I debounce something, so i'll start there

https://github.com/microsoft/vscode/issues/191750

**Comment by meganrogge** [comment]
This is happening because `onBlur` clears it and `onFocus` sets it. We do this so that if any component which is not a view is clicked, the focused view title will be cleared. Thus, I'm not sure this is something that can be changed.
