### ISSUE TITLE
Test: basic WAT debugging in js-debug

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#191545]
Refs: https://github.com/microsoft/vscode-js-debug/issues/1789

- [x] anyOS @chrmarti
- [x] anyOS @luabud

Complexity: 3

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23191545%0A%0A&assignees=connor4312)

---

This iteration js-debug learned to debug WebAssembly by automatically disassembling WASM into WAT (the WebAssembly text format). Give it a shot:

0. Install [js-debug-nightly](https://github.com/microsoft/vscode-js-debug#nightly-extension)
1. Clone https://github.com/torch2424/wasm-by-example and `code-insiders wasm-by-example/examples/reading-and-writing-graphics/demo/rust`
2. Run `npx serve` in the terminal
3. Use `Debug: Open Link` to debug localhost:3000, or wherever `serve` is serving from
4. Set a breakpoint on L51. Step in.
5. Verify you see the decompiled WebAssembly .
6. Set a breakpoint elsewhere in the WebAssembly (like on L78). See that it is verified, continue and check that it gets hit.
7. Check that the Variables view is populated and the Debug Console works. The variables are pretty low-level, but they should be there.
8. Stop debugging and start debugging again. Verify the breakpoint you set in the WASM before is hit again (restored across sessions.)

**Comment by luabud** [comment]
Tested with WSL and works as expected :)
