### ISSUE TITLE
Intellisense "Error squiggles"  doesn't work properly

### ISSUE THREAD

**Issue by gbonacini** [microsoft/vscode#191594]
Type: <b>Bug</b>

- Error squiggles shown non-existent errors in "using" section (C++20 on MAcOS Ventura 13.5, M1), example:

using          debugmode::Debug,
                   debugmode::DEBUG_MODE,
                   stringutils::mergeStrings;

- The error was signaled on the row:

                   debugmode::DEBUG_MODE,

  that was marked red;

- The header file related to that symbol was correctly included, and no real problem was present : as demostration compiling the program launching 'make clean all' , no error at all was shown;

- I tried :
-- to refresh Intellisense, no effect;
-- to restart VSCode, no effect;
-- to disable and re-enable the Intellisense extensions (workspace), no effect;
-  I  also was trying to disable and enable again "error sguiggles" , no effect.

- I'm confident this problem raised after recent updates.

- Extension active on the Workspace:

- Microsoft Remote SSH / Export
-  vscodevim
- and obviously Microsoft Intellisense

VS Code version: Code 1.81.1 (6c3e3dba23e8fadc360aed75ce363ba185c49794, 2023-08-09T22:40:25.698Z)
OS version: Darwin arm64 22.6.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.05GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
remote-ssh|ms-|0.102.0
remote-ssh-edit|ms-|0.86.0
cpptools|ms-|1.17.5
remote-explorer|ms-|0.4.1
vim|vsc|1.25.2

</details>

**Comment by gbonacini** [comment]
Further information:
- Intellisense Error:
"identifier "debugmode" is undefinedC/C++(20)"

**Comment by roblourens** [comment]
Please file this on the C++ extension repo, thanks
