### ISSUE TITLE
Debugger behaves weird in this case

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#19157]
Refs: https://github.com/Microsoft/vscode/issues/19039

* clone https://github.com/expressjs/express
* npm install
* create an empty launch.json and fill it with mocha
* use test as folder not tests
* set a breakpoint into app.render.js line 20
* hit F5
* notice how things work and break
* stop debugging
* open settings and change to show inline values
* click on app.render.js
* hit F5
=> now you suddenly hit an error that "describe" is not defined?
=> you cannot debug the tests anymore

**Comment by isidorn** [comment]
@bpasero Can not repro.
Can you always repro? Can you repro without enabling inline values (this seems unrelated to me)

![screen shot 2017-01-24 at 14 26 50](https://cloud.githubusercontent.com/assets/1926584/22248929/2a57eaa0-e241-11e6-91cf-7296c2a1a155.png)

**Comment by bpasero** [comment]
Seems to be working now, weird.
