### ISSUE TITLE
Double clicking the Markdown preview should scroll unnecessarily

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#19153]
Testing #19085 

Notice the text editor scrolling around in the left. IMO the cursor should change, but if it's already in view, the editor shouldn't scroll.

![kapture 2017-01-24 at 11 53 51](https://cloud.githubusercontent.com/assets/22350/22244417/c9e8bd12-e22b-11e6-9887-ec633e487293.gif)

**Comment by mjbvz** [comment]
I like having the markdown preview double click go to a know location in the editor. It also helps us handle cases with long paragraphs of text (where multile editor lines map to a single block paragraph)

With  #19324 I changed the behavior to instead have double click to the center of the editor. This improves the experience and seems like a good compromise for now
