### ISSUE TITLE
Replace in settings shows wrong search decoration

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#19154]
Testing #19059 

Related: #19152

Notice how the editor decoration is out of position, as if the 4 spaces were a tab (i.e. off by 3 chars).

![replace-in-settings-spaces](https://cloud.githubusercontent.com/assets/5047891/22244404/c06b6b90-e22b-11e6-94cc-061fc7552cf2.gif)

**Comment by sandy081** [comment]
Fixed by 55b5430
