### ISSUE TITLE
Quick search should auto fill the search term if there's a selection

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#191513]
Repro:

1. Add keybinding `{ "key": "ctrl+shift+f", "command": "workbench.action.experimental.quickTextSearch" }`
2. Open an editor
3. Select a word
4. ctrl+shift+f

Expected

![Image](https://github.com/microsoft/vscode/assets/2193314/eca6b1bb-004e-4eba-8fe6-9c2bbc8db907)

Actual

![Image](https://github.com/microsoft/vscode/assets/2193314/a5598fc8-eb07-4ac9-aee2-5fa3c04b752f)

**Comment by weartist** [comment]
@andreamah  Will the request accept external pr, if so, I would like to try to resolve this issue

**Comment by Tyriar** [comment]
@weartist this looks like a good issue for an external contributor to me 👍

**Comment by weartist** [comment]
The problem seems to be here:
https://github.com/microsoft/vscode/blob/6b49d155ca9f2547e9e8ddfdb324db47da97411b/src/vs/workbench/contrib/search/browser/searchActionsTextQuickAccess.ts#L32C1-L33C1
At the moment it is just a simple stitching of `%` to the QuickAccess, I plan to get the selected content of the currently active editor first, and then stitch it to the back, is this solution feasible?

**Comment by andreamah** [comment]
I would like this to only happen if it would also happen for the search view (ie: checking the setting for `Seed Search String From Selection`) https://github.com/microsoft/vscode/blob/e34a26097d763548bf220da77b74922765c12fa2/src/vs/workbench/contrib/search/browser/searchView.ts#L1092

**Comment by andreamah** [comment]
> The problem seems to be here:
> 
> https://github.com/microsoft/vscode/blob/6b49d155ca9f2547e9e8ddfdb324db47da97411b/src/vs/workbench/contrib/search/browser/searchActionsTextQuickAccess.ts#L32
> 
> 
> At the moment it is just a simple stitching of `%` to the QuickAccess, I plan to get the selected content of the currently active editor first, and then stitch it to the back, is this solution feasible?

Yes, that will make sure that the selection is searched in when executing QuickSearch from a command. Thanks for looking into this! :)
