### ISSUE TITLE
window.title setting feedback

### ISSUE THREAD

**Issue by lszomoru** [microsoft/vscode#191579]
Testing #191341

* "Controls the window title `based on the active editor`. Variables are substituted based on the context." I would probably remove the "based on the active editor" part since the context variables provide much broader capabilities. 
* I think that it would be nice to sort the variables alphabetically

**Comment by bpasero** [comment]
I would keep the order of items, they are not meant to be sorted by alphabet, but rather likelyhood of being used.

**Comment by lszomoru** [comment]
> I would keep the order of items, they are not meant to be sorted by alphabet, but rather likelyhood of being used.

That makes it pretty difficult to decide "where" in the list to add a new variable.
