### ISSUE TITLE
Built-in JavaScript extension gets disabled by disabling an extension that depends on it

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode#19158]
Version 1.9.0-insider
Commit 61a56dbf6e80b6732381349e4654e3ae5f0710f4
Date 2017-01-24T08:05:06.845Z

- install the 'JavaScript Atom grammar' extension from the market place
- disable the grammar
- The dialog asks if dependencies should be disabled as well. Say yes.
- After starting VSCode open a .js file.
The editor does not detect the file type but shows 'plain text' instead.

The built-in JavaScript extension is a dependency of JavaScript Atom grammar as it defines the javascript language id.

There is no UI to see that the JavaScript extension is disabled, and no UI to enable again.

**Comment by aeschli** [comment]
It look like the extensionValidator rejects the extension.

**Comment by sandy081** [comment]
Good catch @aeschli
