### ISSUE TITLE
Test: local port forwarding

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#191540]
Refs: https://github.com/microsoft/vscode/issues/190097

- [x] macOS @hbons
- [x] Windows @joyceerhl
- [x] Linux @joaomoreno

Complexity: 3

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23191540%0A%0A&assignees=connor4312)

---

The Ports view is now available to forward locally-running applications over the internet.

1. Run some local server, such as with `npx serve`
2. Use the Ports view to forward the relevant port
3. You'll be asked to sign in. The port is private by default, and going to its "Forwarded Address" URL will require sign in. Do so and verify it works.
4. Right click on the port and change its Port Visibility to public. Open an incognito window and verify you can access the URL there without signin.
5. Forward and unforward several ports, verify things still work.
6. Ensure the commands `Port Forwarding: Show Log` and `Port Forwarding: Restart Forwarding System` work as you would expect

**Comment by joaomoreno** [comment]
Taking over from @deepak1556 since he's blocked due to https://github.com/microsoft/vscode/issues/191749
