### ISSUE TITLE
Internal Error Caused. Invalid checksum

### ISSUE THREAD

**Issue by Jaya-Madhavi-GEA** [microsoft/vscode#191555]
Type: <b>Bug</b>

Whenever & Whereever I'm creating a project with manifest. initially it works fine but the next day or couple of days the deploy to source command fails with internal error caused. Invalid checksum error.
I'm not connect to Github and don't operate commits there.
I have uninstalled the extensions, CLI & VSCode also and reinstalled but nothing changed. I keep seeing this error.
Attached the screenshot of the error.

VS Code version: Code 1.81.1 (6c3e3dba23e8fadc360aed75ce363ba185c49794, 2023-08-09T22:22:42.175Z)
OS version: Windows_NT x64 10.0.19044
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz (8 x 1805)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.39GB (3.59GB free)|
|Process Argv|--crash-reporter-id 3eb8061b-4a2f-48b6-b43f
<img width="743" alt="MicrosoftTeams-image (13)" src="https://github.com/microsoft/vscode/assets/118355458/8df5478e-7601-40bb-a9f2-04e55e2baea3">
-37e65cb5e020|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|2.4.2
LiveServer|rit|5.7.9
salesforce-vscode-slds|sal|1.4.8
salesforcedx-vscode|sal|58.13.1
salesforcedx-vscode-apex|sal|58.13.1
salesforcedx-vscode-apex-debugger|sal|58.13.1
salesforcedx-vscode-apex-replay-debugger|sal|58.13.1
salesforcedx-vscode-core|sal|58.13.1
salesforcedx-vscode-lightning|sal|58.13.1
salesforcedx-vscode-lwc|sal|58.13.1
salesforcedx-vscode-soql|sal|58.13.1
salesforcedx-vscode-visualforce|sal|58.13.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
vsccc:30803844
2e4cg342:30602488
f6dab269:30613381
vscrpc:30673769
2i9eh265:30646982
showlangstatbar:30737416
962ge761:30823813
03d35959:30757346
pythonfmttext:30731395
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
gsofb:30804716
pythonnosmt12:30797651
pythonidxpt:30805730
pythonnoceb:30805159
synctok:30821570
dsvsc013:30795093
dsvsc014:30804076
diffeditorv2:30821572

```

</details>

**Comment by gjsjohnmurray** [comment]
/causedByExtension

Please seek assistance in Salesforce channels.
