### ISSUE TITLE
Header appears with a lag after sticky scroll has scrolled over it

### ISSUE THREAD

**Issue by aiday-mar** [microsoft/vscode#191558]
Testing #191546

Hey @Yoyokrazy, great work here! I was testing the notebook sticky scroll and noticed the following behavior in the GIF. The header `h5 - 1.2.2.2` appears when the bottom of the sticky widget is midway through the cell containing code. I think I would have expected the header to appear as soon as the bottom of header h4 in the sticky widget hits the top of the header h5 in the editor.

In this testing I am using the file `sticky-test` in your testing repo.

https://github.com/microsoft/vscode/assets/61460952/ff622f98-acc5-420e-bb0a-c6b561289b90

**Comment by Yoyokrazy** [comment]
Thanks for the gif! Yeah, this is something I've been working to address, and is a bit of work in progress. More fine-tuned transitions will likely come alongside animations as I fine tune the padding values I use to time the rendering.

**Comment by Yoyokrazy** [comment]
fixed via #201837
