### ISSUE TITLE
Profiles Inheritance 

### ISSUE THREAD

**Issue by hamaney** [microsoft/vscode#191516]
Currently, VSCode allows for profile inheritance at the creation time of a new profile, which is a fantastic feature. However, I'd like to suggest taking it a step further by allowing profiles to build upon each other dynamically.

Here's a practical scenario to illustrate this concept: Imagine I have a 'Base' profile with specific settings, and I create a 'PythonWindows' profile derived from the 'Base' profile. When I make changes to the 'Base' profile, such as deleting an extension or adjusting the font size, these modifications should automatically propagate to the 'PythonWindows' profile since it's built upon the 'Base' profile.

In essence, I envision this as a cascading effect where changes made to a parent profile naturally flow down to child profiles, unless the child profiles have deliberately overridden these settings. This way, managing profiles becomes more efficient, akin to the hierarchy of user, machine, and workspace settings we are already familiar with.

Furthermore, to enhance user experience and reduce redundancy, I propose that the child profiles only display settings that are unique or have been explicitly overridden, rather than duplicating all settings from the parent profile. This streamlined approach would make profiles cleaner and more intuitive to work with.

I believe that implementing this feature enhancement would not only simplify profile management but also empower users to customize their development environments with even greater ease and precision. It aligns well with the user-centric philosophy that VSCode embodies.

**Comment by sandy081** [comment]
If you want this behaviour only for settings here is the issue tracking this - https://github.com/microsoft/vscode/issues/188612

Otherwise in general profile inheritance is a feature which we would not like to support in near future - https://github.com/microsoft/vscode/issues/191224

**Comment by hamaney** [comment]
Thank you for addressing this feature request! I believe the current behaviour, where the "settings" files extend or overwrite the base profile, is sensible. However, I also believe it could be useful for extensions to have a similar capability. Shortcuts generally don't change significantly, so manually managing them is acceptable. On the other hand, the UI state often undergoes significant changes in profiles, so it may be acceptable for it not to be synchronized. What are your thoughts on this?

**Comment by sandy081** [comment]
May be - that this is useful for extensions. Please add your use case for extensions in the profile inheritance issue.
