### ISSUE TITLE
Test: Further Notebook Sticky Scroll Tests (behavior tweaks)

### ISSUE THREAD

**Issue by Yoyokrazy** [microsoft/vscode#191546]
Refs: #182444, #191543

- [x] anyOS @aiday-mar
- [x] anyOS @karrtikr 

Complexity: 3

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23188728%0A%0A&assignees=Yoyokrazy)

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23191546%0A%0A&assignees=Yoyokrazy)

--- 
## Summary:

Notebook Sticky Scroll now more closely matches editor behavior. Much of this TPI will remain the same as the previous, but the behavior should now feel more familiar and closer to editor sticky scroll. TLDR: point out behavior that feels buggy, just kinda "off", or not what you would expect intuitively.

## Steps to Test:
- Enable sticky scroll via either of the following -- preferably try both :)
  - Use command palette `View: Toggle Notebook Sticky Scroll` 
  - Use setting in UI or json `notebook.stickyScroll.enabled`
- Ensure that you can toggle the setting via the command palette
- Open a notebook with an assortment of markdown headers
  - You can find a couple examples littered in [my testing repo](https://github.com/Yoyokrazy/ipynb-playground).
- Scroll until you have a sticky line/header rendered, and ensure you can right click, finding a context menu, and toggle the sticky scroll.
- Click on the sticky line to focus the md cell with that header, ensure it is visible in the viewport.
- Scroll up and down throughout various header sections and ensure there is no pop-in or out of multiple lines at a time. transitions are not animated as nicely as the editor sticky scroll, work for future here, but they should appear 1 at a time. 
  - For this point, if scrolling between two of the same level headers (an H3 followed by another H3 for example), the sticky line for the initial H3 should collapse and disappear before the new one is rendered. Previously, the next header would render without first collapsing the above header, creating an effect that just the text changes. This should feel closer to the standard editor experience. **See bottom known bug for exception to this**
- If you find any issues, I would greatly appreciate a gif of the bug, alongside the file you are using to test!
- Any overall UX feedback is appreciated! Polish with animations is coming in the future.

## Known Bugs/Planned Work: 
(feel free to reference or comment on these to bring attention/provide more examples)
- https://github.com/microsoft/vscode/issues/188703
- https://github.com/microsoft/vscode/issues/188688
- Small papercut when scrolling into new top level header section. If two nested headers (H1 followed by H2 for ex) are the first in a new section, they will pop in together. 
   
--- 
Thanks so much for testing!

**Comment by aiday-mar** [comment]
Great work!
