### ISSUE TITLE
Test: Command Palette Natural Language Search with new API

### ISSUE THREAD

**Issue by TylerLeonhardt** [microsoft/vscode#191506]
Refs: https://github.com/microsoft/vscode/issues/190909

- [x] anyOS @Tyriar
- [x] anyOS @alexr00

Complexity: 2

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23191506%0A%0A&assignees=TylerLeonhardt)

---

This iteration we moved away from one API in favor of another that will be more extensible later. This TPI acts as a sanity test to make sure the feature still works as intended.

#### Prerequisites

* latest Copilot Chat pre-release & Insiders, of course
* `workbench.commandPalette.experimental.enableNaturalLanguageSearch` set to `true` (it's the default)

#### Testing

Open the Command Palette and start typing. You should get similar results to pop up, if they exist. Here are some examples:
* `change language to french` -> `Configure Display Language`
* `where is my terminal` -> `Focus on Terminal View`

#### Known issues

This work depends on the Copilot Chat extension downloading and loading a fairly large index. If you don't get any `similar results` in the Command Palette, check the `GitHub Copilot Chat` Output Channel. You need to see a line like:
```
[DEBUG] [CommandIdIndex] Embeddings for commandEmbeddings calculated in Xms
```

You may need to turn of debug logging to see this:
```
"github.copilot.advanced": {
    "debug.overrideLogLevels": {
      "*": "DEBUG"
    }
  },
```

It's important to note that once the index is downloaded (which happens once a week for insiders), loading the model takes less than a second... so you should be able to reload your window and it be relatively snappy to start working.

**Comment by alexr00** [comment]
This works, but usually I don't get results until I've entered the last word of my search, which makes it good for discovery, but slower than knowing the command.
