### ISSUE TITLE
Cannot search for word file

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#191581]
Testing #191521

- Searching for `file` always takes to the action with term `field`

https://github.com/microsoft/vscode/assets/10746682/1eb9a80c-fc89-442e-a7ba-a8fc9f60c73f

**Comment by justschen** [comment]
Strange. I believe it's an issue with how fuzzy matching is giving the score `file` and `field` since both have f, i, l, e, in it so it might be getting confused. Goot catch thank you.
