### ISSUE TITLE
Test: Handle missing notebook cell language support

### ISSUE THREAD

**Issue by amunger** [microsoft/vscode#191507]
Refs: https://github.com/microsoft/vscode/issues/187516

- [x] macOS @DonJayamanne 
- [x] windows @Yoyokrazy 

Complexity: 3

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23191507%0A%0A&assignees=amunger)

---

### Custom notebooks

install an extensions with custom notebooks like 'github issues notebook'

1. Create a custom notebook contributed by an extension (e.g. .github-issues) and save it
2. swith to a profile without that extension avaiable with that notebook open.
a. ensure the notebook is not dirty
b. the cell language should not switch to plain text
3. click the warning next to the cell language and ensure it opens a search for related extensions.
4. switch back to the original profile or install the extension
a. ensure the language error eventually goes away

### Unknown languages within builtin notebooks

Install an extension that contributes additional languages to .ipynb notebooks like 'Polyglot notebooks'

1. Create an .ipynb and select a kernel from an extension with their own cell languages and save it
2. Swith to a profile without that extension avaiable with that notebook open.
a. ensure the notebook is not dirty
b. the cell language should not switch to plain text (it may still change to the raw value)
3. click the warning next to the cell language and ensure it opens a search for related extensions.
4. switch back to the original profile or install the extension
a. ensure the language error eventually goes away

**Comment by DonJayamanne** [comment]
Easy peasy steps, works well without any hickups.

**Comment by Yoyokrazy** [comment]
Works perfectly 👍
