### ISSUE TITLE
Make last sticky line disappear gradually before sticky widget before next one appears

### ISSUE THREAD

**Issue by aiday-mar** [microsoft/vscode#191559]
Testing #191546

I was thinking about how to make the transition look nicer in the notebook sticky scroll. In the editor sticky scroll, when the bottom of sticky scroll reaches the end of a scope, the last line of the sticky scroll starts disappearing gradually behind the sticky widget until it is completely behind it.

Perhaps a similar mechanism could be implemented here, so that when scrolling from one h5 header to a second h5 header, the first one first completely disappears before the second one appears. 

An example of what I mean:

https://github.com/microsoft/vscode/assets/61460952/7be5e98d-8fee-4cba-b676-7a07bf3d3bcb

**Comment by Yoyokrazy** [comment]
Thanks for the feedback! This is definitely in the plan, and there's already good progress going in a different branch. Hoping it can be polished up pretty soon and rolled out.

**Comment by Yoyokrazy** [comment]
Closing this as there are some other issues tracking the visual behavior of nb sticky scroll.
