### ISSUE TITLE
JavaFX

### ISSUE THREAD

**Issue by LegioN7** [microsoft/vscode#191562]
Type: <b>Bug</b>

When I create a new project from Java for JavaFX, it does not install the JavaFX Plugin for Maven so i can not run a JavaFX program

VS Code version: Code 1.81.1 (6c3e3dba23e8fadc360aed75ce363ba185c49794, 2023-08-09T22:22:42.175Z)
OS version: Windows_NT x64 10.0.22621
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 6800H with Radeon Graphics          (16 x 3194)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.19GB (6.48GB free)|
|Process Argv|--crash-reporter-id bb26668c-cd75-40fc-bf7b-d04e2ef22a87|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (46)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eclipse-keybindings|alp|0.16.1
es7-react-js-snippets|dsz|4.4.3
vscode-html-css|ecm|1.13.1
prettier-vscode|esb|10.1.0
code-runner|for|0.12.0
intellij-idea-keybindings|k--|1.5.10
mp-rest-client-generator-vscode-ext|Mic|0.1.2
mp-starter-vscode-ext|Mic|0.2.9
vscode-microprofile-pack|Mic|0.1.3
csharp|ms-|2.0.416
vscode-dotnet-runtime|ms-|1.7.1
python|ms-|2023.14.0
vscode-pylance|ms-|2023.8.40
jupyter|ms-|2023.7.1002162226
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.17
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-slideshow|ms-|0.1.5
cmake-tools|ms-|1.15.31
cpptools|ms-|1.17.5
cpptools-extension-pack|ms-|1.3.0
powershell|ms-|2023.6.0
vsliveshare|ms-|1.0.5883
vsliveshare-pack|ms-|0.4.0
fabric8-analytics|red|0.3.10
java|red|1.21.0
vscode-community-server-connector|red|0.26.13
vscode-microprofile|red|0.9.0
vscode-quarkus|red|1.15.0
vscode-rsp-ui|red|0.24.8
LiveServer|rit|5.7.9
javafx-support|shr|0.0.1
sonarlint-vscode|Son|3.20.2
cmake|twx|0.0.17
intellicode-api-usage-examples|Vis|0.2.8
vscodeintellicode|Vis|1.2.30
vscode-boot-dev-pack|vmw|0.2.1
vscode-spring-boot|vmw|1.48.0
vscode-gradle|vsc|3.12.7
vscode-java-debug|vsc|0.54.0
vscode-java-dependency|vsc|0.23.1
vscode-java-pack|vsc|0.25.13
vscode-java-test|vsc|0.39.1
vscode-maven|vsc|0.42.0
vscode-spring-boot-dashboard|vsc|0.13.1
vscode-spring-initializr|vsc|0.11.2

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
vsccc:30803844
2e4cg342:30602488
f6dab269:30613381
a9j8j154:30646983
showlangstatbar:30737416
03d35959:30757346
pythonfmttext:30731395
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
gsofa:30804715
pythonnosmt12:30797651
pythonidxpt:30805730
pythonnoceb:30805159
dsvsc013:30795093
dsvsc014:30804076
diffeditorv1:30821571

```

</details>

**Comment by roblourens** [comment]
Please file this on the Java extension repo, thanks
