### ISSUE TITLE
No diff highlightings inside moved lines

### ISSUE THREAD

**Issue by Igorgro** [microsoft/vscode#191518]
Tesing #191508

When there are moved moved lines which contains change inside them (`audio` -> `audiooo` in example), then the moved lines are highlighted with "bright" colors and the change is not highlighted at all. Meanwhile, regular diff lines (`Input` -> `Inputtt` in example) are highlighted with "dimmed" colors which makes the change itself visible.

- VS Code Version: 
  Version: 1.82.0-insider
  Commit: f7973f357e7c316a88e8817886f41a843021fe74
  Date: 2023-08-28T05:03:24.392Z (15 hrs ago)

Steps to Reproduce:

1. Make moved code lines with the change inside of one of the moved line

[Example](https://microsoft.github.io/monaco-editor/playground.html?source=v0.42.0-dev-20230828#XQAAAALeCAAAAAAAAABBqQkHQ5NjdMjwa-jY7SIQ9S7DNlzs5W-mwj0fe1ZCDRFc9ws9XQE0SJE1jc2VKxhaLFIw9vEWSxW3yscxE3VlFEChkmZ_i818hfkoqOpFQHEvIxUC2MltD4RrsefaY-dWUozyzjhjaNhLTMC_Igv4t660m7K-kjCQbkK5uLUYbkexhOoeUaoQquHvon1NihTA_6yWQzyG7w4Npa97wcDfSr5khrPGIcc24bZraWG82zNjLOhWWTAKuqocJxPuGM_2PxTYuVqbTmfVhQKzgF-vZQyz2n7-cO6PhCoqwCiHn3IrIyMGTvL2kpWrYl_7lta7r2JM-86l2MGqB03YnmFtU8t5oMkyVjE5c4RlenSiFqYu7pP7yD7kZT6wm1-lfTAvra7DdKG8q4_M6XudjLy5kIYM4HQzjyOZvnXei7dErNjBueQHf2pZ4IY_9LfzQq-ZlYInR55Pg3FwVhC1s2bhJbgOp_ZFQ5-VdPxUNqtqr189U2yee1QIUUWpB0P_gkotlVN1XFfjt0W1XEJQxBO-BMoJmdB83iZKCXfDxDw75WtSqTZ0R0U1QMkg2jTdujPJ6fUSugy4f057ccWXXyL0tT9VSfBnGGK-ZHenOv41Pzjt63Cr-Qvmyg76KPof1QODsqliOMOqN-LUS2vCsi2Jg2Uaj_4Ie90U3mv7aj0J5s8eXMcs40k3UdEmRg3ElSvN4Qqp9k1XiKsoZSmdMC7zsVuwIMla0CqqHe5rmvlhTzJmAE9coNMKcVGi1CXO8YYoqeKQBUS9c8J_FA3GYZqo3RZNF7IoAu31fd9Dg8z4v4pYnyMYpqMJPvqqW_qWXhdFptRybd7Lii46cE8v_tpVB5TdlDu8vqJSDZE-Ewf_1ItfcQ)

**Comment by Igorgro** [comment]
Oh, I found, that what "Compare mode" made for :)

**Comment by hediet** [comment]
Exactly! I'm open to change this, but for now outside of the compare mode, the diff decorations are rendered as if there weren't any moves.
