### ISSUE TITLE
Replace in Settings introduces spaces in file indented with tabs

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#19152]
Testing #19059

My `settings.json` is correctly formatted with tabs.
Choose any "Replace in Settings" action causes the `settings.json` to contain spaces.

![replace-in-settings-spaces](https://cloud.githubusercontent.com/assets/5047891/22244404/c06b6b90-e22b-11e6-94cc-061fc7552cf2.gif)

**Comment by sandy081** [comment]
@alexandrudima Do you have conf `editor.insertSpaces` set to `true` ? Because, I can only reproduce it when it is true

**Comment by alexandrudima** [comment]
The settings are visible in the bottom right: the user settings.json is detected/configured in the editor with Tabs @ 4. Just look in the bottom right of the gif when focus moves to the file
