### ISSUE TITLE
Test: workbench.view.dimUnfocused.*

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#191527]
Refs: https://github.com/microsoft/vscode/issues/30522

- [x] macOS @bhavyaus
- [x] linux @bpasero
- [x] windows @justschen

Complexity: 2

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23191527%0A%0A&assignees=Tyriar)

---

There are new settings `workbench.view.dimUnfocused.enabled` and `workbench.view.dimUnfocused.opacity`, read the settings and verify they work as expected.

**Comment by bpasero** [comment]
Having tested this I am actually not happy about the way it works currently and feel we should spend more time on it to really fix the rough edges:
* why does this only apply to text editors and terminals but for example not notebooks?
* why does it apply to terminals in the panel but not other panels?
* why does it not apply to the sidebar?

I guess I am not really understanding what we want to solve here: if the idea is to make the focussed part stand out more from other parts, then I would argue we should consistently highlight the "thing" that has keyboard focus and dim everything else. The current solution seems half-baked.

**Comment by Tyriar** [comment]
> why does this only apply to text editors and terminals but for example not notebooks?

I guess this is because I rarely use editors other than the text editor 😅. I don't expect editors other than the webviews to be hard to implement.

> why does it apply to terminals in the panel but not other panels?
> why does it not apply to the sidebar?

@bpasero let's discuss this in https://github.com/microsoft/vscode/issues/191610

**Comment by justschen** [comment]
Some of these may have been mentioned, but no unfocus on some other views in the workbench including gitlens, ports, comments, refactor preview. 

Other than that it looks solid in a bunch of the themes I tried it in as well.
