### ISSUE TITLE
Show error "Cannot find module" although I have typings folder

### ISSUE THREAD

**Issue by lovedota** [Microsoft/vscode#1915]
Hi My VS Code is *0.10.6*
- I got a problem with VS Code Error, It shows error although about *Cannot Find Module*
![step1](https://cloud.githubusercontent.com/assets/417914/12226279/282f9f0e-b84c-11e5-908d-e9a171f25b9e.png)

- I already got the *typings* folder
![step2](https://cloud.githubusercontent.com/assets/417914/12226271/0d64cdca-b84c-11e5-9b97-9f6304387050.png)

**Comment by lukefan6** [comment]
+1 I've got similar error and only way to get around it is to close vscode and open it again
btw my vscode is v 0.10.11

**Comment by dbaeumer** [comment]
@lovedota how does your tsconfig.json file look like. And if you compile the src using tsc on a command line do you see the same errors.

**Comment by lukefan6** [comment]
here's my tsconfig.json
```
{
    "compilerOptions": {
        "target": "es5",
        "module": "commonjs",
        "noImplicitAny": false,
        "removeComments": true,
        "noLib": false,
        "preserveConstEnums": true,
        "declaration": false,
        "suppressImplicitAnyIndexErrors": true,
        "jsx": "react",
        "sourceMap": true
    },
    "filesGlob": [
        "./src/**/*.ts",
        "./src/**/*.tsx",
        "!./node_modules/**"
    ],
    "files": [
        "./src/main.tsx",
        "./typings/main.d.ts"
    ]
}
```

and if I type 

> tsc --outDir ./temp

 there's no error and the temp folder contains compiled js files.
however vscode remains the same, saying cannot find module.
I had to close vscode and open it again
(v0.10.11 on Mac 10.10.5)
hope these info helps

**Comment by dbaeumer** [comment]
@lukefan6 since I don't know your files layout hard to tell. All I can say is that the filesGlob will not work with VSCode. It is not supported. And since you list files directly I suspect that your typings will not be included in the project defined by the tsconfig.json file.Can you share your project ?

**Comment by Mosho1** [comment]
This is happening to me as well.

Here's the tsconfig file:

```
{
    "compilerOptions": {
        "jsx": "react",
        "target": "es5",
        "module": "commonjs",
        "experimentalDecorators": true
    },
    "files": [
        "./typings/main.d.ts"
    ]
}
```

However, if I place the following line at the top of the file:

```
/// <reference path="../typings/main.d.ts" />
```

The modules are resolved correctly.

**Comment by dbaeumer** [comment]
@Mosho1: your problem is the files section. You are creating a project with exactly one file in it the ./typings/main.d.ts'. If you open another file it doesn't see the main.d.ts. You either need to list all files in the tsconfig.json file or none. Then VSCode takes considers all *.ts files (including d.ts) under the tsconfig.json file part of the project.

**Comment by dbaeumer** [comment]
I close this issue since i haven't heard back from the initial creator of the issue and the other comments relate to tsconfig.json issues.

**Comment by bezreyhan** [comment]
@dbaeumer This has been an issue for me. 
```
src
  - index.tsx
typings
 - index.tsx
tsconfig.json
```

My tsconfig looks like this: 
```
{
  "compilerOptions": {
    "sourceMap": true,
    "noImplicitAny": true,
    "strictNullChecks": true,
    "module": "commonjs",
    "target": "es6",
    "jsx": "react"
  },
  "include": [
    "./typings/index.d.ts",
    "./src/index.tsx"
  ]
}
```

When I run tsc I do not get any errors but in VS code I am getting the following error: `can't find module ...` any time I import a module from node_modules. (e.g `import * as React from 'react';`)

**Comment by dbaeumer** [comment]
@bezreyhan 

The include is a TS 2.0 beta feature. VS Code still ships with the official 1.8.10 version. If you want to use VS Code with TS 2.0 you need to use the `typescript.tsdk` setting.

**Comment by mohsen1** [comment]
@dbaeumer is right, in `.vscode/settings.json` add:

```json
"typescript.tsdk": "node_modules/typescript/lib",
```

**Comment by cypherq** [comment]
Only thing I can't understand is that if I'll put @mohsen1 option into global config, VSC is complaining about missing `tsdk` even in non TS projects. 

Can't it detect somehow whether it's TS project or not?

**Comment by jaredmahan** [comment]
This is still not working for me. My project still compiles correctly but it cannot find any of my custom d.ts files

**Comment by Kramins** [comment]
I am also having the same issue. if the Type Definitions are not part of the @types then TypeScript does not file the .d.ts file in the corresponding module folder.

Example is fuse.js, it is packaged with it's own .d.ts file but vsCode is unable to find the module on import.

**Comment by nguoihocnghe** [comment]
Hi, I got this problem recently and it's driving me nuts. I described it here: https://github.com/Microsoft/TypeScript/issues/17351#issuecomment-343823342
