### ISSUE TITLE
'reindent all lines': wrong indent with object literal

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode#19150]
Testing #18958:
- in the vscode repo, open 'themeService.ts'
- run 'reindent all lines'.
- Note the change on defaultThemeColors:
```
let defaultThemeColors: { [baseTheme: string]: IThemeSetting[] } = {
	'vs': [
	{ scope: 'token.info-token', settings: { foreground: '#316bcd' } },
	{ scope: 'token.warn-token', settings: { foreground: '#cd9731' } },
	{ scope: 'token.error-token', settings: { foreground: '#cd3131' } },
	{ scope: 'token.debug-token', settings: { foreground: 'purple' } }
	],
```

**Comment by rebornix** [comment]
This is part of https://github.com/Microsoft/vscode/issues/19140#issuecomment-274913963

**Comment by rebornix** [comment]
Reindent all lines and reindent selected lines now take care of this case. For other issues we still track in #19140.

![19150](https://user-images.githubusercontent.com/876920/45835357-ba49b180-bcbe-11e8-819e-6adc2e70bbac.gif)
