### ISSUE TITLE
Context menu on simple text editor does not have the standard options

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#191628]
Testing #191496

I was expecting more of these:

![Image](https://github.com/microsoft/vscode/assets/900690/41c6b971-5d8d-4acc-b632-640dc8ac9859)

But got:

![Image](https://github.com/microsoft/vscode/assets/900690/028127cc-8010-49f6-9f76-01d32a195fcd)

**Comment by TylerLeonhardt** [comment]
![image](https://github.com/microsoft/vscode/assets/2644648/8f0b2682-a841-4ae0-8924-5df8d14be0f6)

seems like a generic chat input issue.

**Comment by roblourens** [comment]
All the simple editor inputs are like that

<img width="213" alt="image" src="https://github.com/microsoft/vscode/assets/323878/30ff2ad1-1527-4c5f-9021-59761517c10a">

I don't know whether "select all" comes from us on the native inputs, that's probably just from the browser

**Comment by roblourens** [comment]
And the full code editor doesn't have those options. I think this probably isn't worth trying to fix, lmk if you disagree

**Comment by bpasero** [comment]
@roblourens we actually have a central place to provide these actions for all `input` fields:

https://github.com/microsoft/vscode/blob/c7e08e78dc57c65999f0a52a49774aa0184aacfa/src/vs/workbench/browser/actions/textInputActions.ts#L19

It feels a bit inconsistent that those input fields that are implemented with a text editor are different from that.
