### ISSUE TITLE
Icons in Accessible view don't seem right

### ISSUE THREAD

**Issue by karthiknadig** [microsoft/vscode#191684]
Testing #191345

![image](https://github.com/microsoft/vscode/assets/3840081/fd38d13b-6a60-4e7d-95a1-223400bba803)

The bell icon for manage extension does not seem correct here, gear icon might be better.
The shown next and show previous should swap places.  `>` and `<` should probably be `<` and `>`
I would expect `x` to be at the end.

**Comment by meganrogge** [comment]
> I would expect x to be at the end.

This is at the start of the default actions by design bc it is the most important one. I'm going to change the icon from an `X` to something else (tracked in a different issue)

**Comment by meganrogge** [comment]
> The shown next and show previous should swap places. > and < should probably be < and >
![Screenshot 2023-08-29 at 12 37 14 PM](https://github.com/microsoft/vscode/assets/29464607/92cb2656-72af-4d8b-8a32-4656fb741500)


Re the order, you'd usually want to go to the `next` before the `previous`, so I think we should leave that as is. You're not on the latest insider's FYI, the icons are now up and down arrows.

**Comment by meganrogge** [comment]
I agree, we should use the gear for manage extension.

**Comment by meganrogge** [comment]
Verify that if a notification has "Manage Extension", it uses a `gear` icon in the accessible view.

**Comment by karthiknadig** [comment]
![image](https://github.com/microsoft/vscode/assets/3840081/1bb36e96-c7a1-463c-bfb4-bded4aaecde7)

Verified that the gear icon is for configuring. It looks like we are re-using the bell(slash) icon for disable accessible view hint. That same icon is used for Do not disturb.  @daviddossett should this be a different icon?
