### ISSUE TITLE
Moved code widget does not get highlighted when is moved over cursor

### ISSUE THREAD

**Issue by Igorgro** [microsoft/vscode#191617]
Testing #191508

Steps to Reproduce:

1. Create two copies of the same lines. One of this copy will be connected with arrow
2. Select the connected copy and past some symbols, so that arrow jumps to another copy
3. Remove those symbols, so the arrow jumps again over the block where cursor is located
4. . 🐛 Now the moved lines frame is located so that the cursor is inside of it but it is not highlighted untill the cursor is moved

https://github.com/microsoft/vscode/assets/22894169/a281ff19-7299-4816-bb88-38b0e9ca0e41

[Example](https://microsoft.github.io/monaco-editor/playground.html?source=v0.42.0-dev-20230828#XQAAAAJACQAAAAAAAABBqQkHQ5NjdMjwa-jY7SIQ9S7DNlzs5W-mwj0fe1ZCDRFc9ws9XQE0SJE1jc2VKxhaLFIw9vEWSxW3yscxFeeC3VciAJM8XEuX7Os378jBGtVLkr6ryuhqvky-XZ9Sy0vyFSI1m9lYQpwqOsaKmhydYWIo-9hGbv_4wlPHJE32WwJQXiHR3looR_fkyQDM0QL-JXDok5ge95iYvjHlF3FxmJhq-ML2Mv0DrG9odUt0RyrqVQLLqqsyWIhAOnmJlHmgVKAkVlHyT9q1aDx3m-fUO12m6oja-Zn9-fj1Z1wWKXs-cw34GUHYz47IEQnvaKMYJfd4WtH1vQwjkqpt_WUupRACsfidP_pQTwOWuhB5MT-Ge5-i-iAKSo3RMckpFZil2ux1-zHD8sd10NJ0CY7MNyUK-EbLWHtl2oJLbqlWUE_AJSCTcAPwGERCKy27cRn4JON6GXoG8c9Hd7bIdtmXIWLAy9h0QK9K7KFa2mEue088OXS8Tg6mo5JUeJS0Ffh3GgqGwGh-Wk3P8MmoxDLm9l9hhhti984QwibNzk1JFX_Ma43tG1C9W4Mqqz_0vs_ltlShgywXYBTS6GzySwVCSdp00GejQ3KovaylCG9yM_HjlQB0QRAkc2B89HyjRS-UpIbpM0fsHPV6px2HIVvc8KdbT7nNVDYlb-dqx55ma4jOZpt9nsULRxtlBTreNr7bFbAi4RMZE0mxW4SeSWg-FArsLghaXlPjwLHLiYJeBfPXTZDCBypbv-q5zRvpjZO2CwhXdTiroYGQfoqhSEMhgWsSRusn3vXdy66DdBlU7ntEgMmhVvP-lQGT7bNQionJOaZ3ORsTwey35X_0cv_FS8W0)

**Comment by hediet** [comment]
That's a great find! There also was the bug that changing the focused editor, but not the position wouldn't update the selected moved block, I hope that is now fixed as well.
