### ISSUE TITLE
Syntax highlighting for C23/Gnu23 C language updates

### ISSUE THREAD

**Issue by danthedev123** [microsoft/vscode#191622]
The C23 update to the C specification is slowly becoming a thing, and GCC/Clang already support it. My request is for the new keywords (`bool`/`true`/`false`, `constexpr`, etc) to be added to the C syntax highlighting of VSCode, or an option for users to add their own keywords for this purpose. I may be wrong about there not being an option for this already (sorry if that is the case!) but I haven't been able to find any documentation on this. Although C23 is still bleeding-edge, I think this would be a useful feature. Thanks!

**Comment by alexr00** [comment]
Copied to https://github.com/jeff-hykin/better-c-syntax/issues/10, which is where we pull our C syntax highlighting grammar from.
