### ISSUE TITLE
Test `serve-web`- no extensions installed

### ISSUE THREAD

**Issue by andreamah** [microsoft/vscode#191641]
Testing #191542

1. Run `code-insiders serve-web` (on linux)
2. Wait for everything to initialize.
3. Go to extension tab, nothing under `127.0.01:8000-installed` :bug:

![Image](https://github.com/microsoft/vscode/assets/31675041/1d1605b0-88ba-4a67-8162-a27e838cf8a6)

Originally, I wasn't sure if the extensions were supposed to be imported, but I saw in the help options that you can specify an extensions dir, so I assumed it used the default one if this wasn't specified?

**Comment by connor4312** [comment]
The server will use its own extensions directory. It's not expected to reuse desktop extensions.

**Comment by matifali** [comment]
How can we install an extension for the server using CLI only?
