### ISSUE TITLE
Unfocused editors should regain focus (be un-dimmed) on scroll

### ISSUE THREAD

**Issue by bhavyaus** [microsoft/vscode#191671]
Testing #191527
 
 In the gif, you can see that after picking a file to be opened in the editor, I can scroll in the dimmed editor. This feels weird to me.  

https://github.com/microsoft/vscode/assets/25044782/c37fc52f-869c-45a9-abd4-4a737f85dc0e

**Comment by Tyriar** [comment]
Right now the feature uses a set of CSS rules, I don't think it would be possible to fix this problem without hooking up some events. For example if we could listen to an editor scroll event and treat it as focused for x seconds after that?

**Comment by lobsterkatie** [comment]
> I can scroll in the dimmed editor. This feels weird to me.

FWIW, this matches the native behavior in OS X. (Notice how I can scroll in the other Chrome window, even though the one with this issue in it is in front and focused.) I thought it was a little weird when I first discovered it in OS X, too, but you get used to it pretty quickly.

https://github.com/microsoft/vscode/assets/14812505/8fd5d70a-1b46-408e-b9de-637be8e72c66

**Comment by Destroy666x** [comment]
It's not the scrolling part which is weird. That's normal in all popular window systems. The dimming part is quite annoying though. It's clear you're using that part of the  window and want to see the contents better, IMO.

So I don't think it should necessarily "regain focus" as the issue suggest, but more like "regain brightness". If not by default then with a setting.

**Comment by lobsterkatie** [comment]
> It's not the scrolling part which is weird. That's normal in all popular window systems. The dimming part is quite annoying though. 

Ah - that makes more sense. Thanks for clarifying.

> I don't think it should necessarily "regain focus" as the issue suggest, but more like "regain brightness". If not by default then with a "Scrolling unfocused editor disables dimming" kind of setting.

Could be a setting, but FWIW, now that I've started using the feature, I like the way it works currently. The high-level objective of the feature to is make it clear to the user which view will be affected by keyboard input (so I can stop typing `git push` into random files, for example), and the answer to that question doesn't change if I scroll an unfocused view.

**Comment by JimGitFE** [comment]
### In case someone is wondering **how to disable Dim Unfocused**

1. Open the Command Palette <kbd>Ctrl</kbd> + <kbd>Shift</kbd> + <kbd>P</kbd> (Windows/Linux) 
2. Type `Open Accessibility Settings` 
3. Uncheck `Accesibility > Dim Unfocused`

As per [vscode August Release](https://code.visualstudio.com/updates/v1_82#_dim-unfocused-editors-and-terminals)
```json
"accessibility.dimUnfocused.enabled": false,
"accessibility.dimUnfocused.opacity": 1,
```

**Comment by Tyriar** [comment]
Merging into https://github.com/microsoft/vscode/issues/236576

/duplicate
