### ISSUE TITLE
Notebook output accessible view has go to symbol action

### ISSUE THREAD

**Issue by anthonykim1** [microsoft/vscode#191689]
Testing #191345

(Mac)
Pressing option (alt in windows) + f2, 
on a jupyter output yields accessible view, 
and going over to "go to symbol" (by pressing command+shift+o in Mac) from there yields a go to symbol tabs with unintended 
"(paragraph) Exit this dialog via the Escape key."

<img width="883" alt="Screenshot 2023-08-29 at 11 47 21 AM" src="https://github.com/microsoft/vscode/assets/62267334/79866660-5c50-44e8-af56-5346560f5a80">
<img width="875" alt="Screenshot 2023-08-29 at 11 47 40 AM" src="https://github.com/microsoft/vscode/assets/62267334/37f58efa-7d46-4651-9d09-5b1684cc02ba">

**Comment by meganrogge** [comment]
This is actually working as designed IMO as @amunger does not provide other symbols, so it's using the default `markdown` provider.
