### ISSUE TITLE
Settings feedback

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#191618]
Testing #191527

Two polish items:
* the link to the setting does not seem to work
* you talk about "making the focused view more obvious" but that is not true, this feature only works for "text editors" and "terminals", so I would clarify that

![Image](https://github.com/microsoft/vscode/assets/900690/082040dc-9868-455e-ac17-82d5d77835ed)

**Comment by bpasero** [comment]
Btw should this move under a settings category for accessibility rather than "View"? Is that maybe the intent of this setting to improve accessibility?

**Comment by Tyriar** [comment]
> Btw should this move under a settings category for accessibility rather than "View"? Is that maybe the intent of this setting to improve accessibility?

That's actually where it was initially, see https://github.com/microsoft/vscode/issues/30522#issuecomment-1681231319 and follow up comments. It does have the accessibility tag fwiw, I don't feel too strongly about the setting name though.

> you talk about "making the focused view more obvious" but that is not true, this feature only works for "text editors" and "terminals", so I would clarify that

This is already covered? "View" is referring to the aforementioned views:

![image](https://github.com/microsoft/vscode/assets/2193314/d2e3eebb-c26c-4b3b-b513-95a7ff264bc1)

**Comment by bpasero** [comment]
My settings description suggestion: "Whether to dim unfocussed text editors and terminals, making the focused text editor or terminal more obvious"

**Comment by Tyriar** [comment]
That just reads awkwardly to me repeating the same words multiple times.

> Once all editors are supported, we can leave out "text".

Planning on fixing the majority of editors this week 👌

**Comment by Tyriar** [comment]
After the discussion in the other issues I do agree we should move this back to accessibility to further avoid confusion about it applying to all views.

**Comment by Tyriar** [comment]
I will also clarify in the setting description that it's purpose is to help the user know where input is going to go.
