### ISSUE TITLE
Dragging panel out shows terminal dimmed

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#191609]
Testing #191527

I think currently dimming is based on focus but imho it should be based on active view/editor. Here dragging the panel out shows the terminal dimmed, even though it is active:

![Image](https://github.com/microsoft/vscode/assets/900690/56e39dce-ea09-427a-83f3-1d7245cffc39)

**Comment by bpasero** [comment]
I guess this actually works as implemented but maybe is not nice. My intent was to reveal the terminal and it appears dimmed because we do not seem to pass in focus when we do so.

**Comment by Tyriar** [comment]
After thinking about this and the purpose for the setting (where is typing going to input text), this is working as designed imo.
