### ISSUE TITLE
z-index issues with notebooks sticky scroll

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#191632]
* have side by side editors
* open a notebook in the 2nd tab group
* scroll so that NB sticky scroll shows
* it overlays the editor sash

<img width="520" alt="Screenshot 2023-08-29 at 16 44 41" src="https://github.com/microsoft/vscode/assets/1794099/55040b7b-8264-45d4-8992-2d8fcb973c62">

**Comment by jrieken** [comment]
fyi @joaomoreno for sash

**Comment by joaomoreno** [comment]
FYI the sash is actually invisible. That line is owned by the workbench editor widget AFAIK.
