### ISSUE TITLE
Copy image output doesn't work on Linux

### ISSUE THREAD

**Issue by lramos15** [microsoft/vscode#191658]
Testing #191502

1. Have a cell with an image
2. Copy the cell output
3. Paste in something like Gimp
4. 🐛 Nothing happens

Both `xclip` and Gimp don't see anything written to the clipboard. Copying images from a browser works so I know the clipboard can be written with images.

**Comment by amunger** [comment]
are you able to right click copy an image from markdown preview?

**Comment by lramos15** [comment]
This seems to work, yes.

**Comment by amunger** [comment]
error of "Could not copy image, document not focused", so the focus might not be set correctly when using the toolbar.
