### ISSUE TITLE
[WelcomeUX] Shows up in command palette but not Help  menu

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#19163]
Refs: https://github.com/Microsoft/vscode/issues/19111

There is an entry to show "Welcome" from the command palette but I do not find an entry in the Help menu.

**Comment by chrmarti** [comment]
Does this reproduce after restart? Might have been temporary after I started using localStorage to mirror the "telemetry.experiments.*" settings (to have them available during startup).

**Comment by bpasero** [comment]
I suggest to never hide the "Welcome" entry under the help menu, no matter what.
