### ISSUE TITLE
Only show `Open Accessible View` when there is an accessible view to open

### ISSUE THREAD

**Issue by andreamah** [microsoft/vscode#191663]
Testing #191344

I'm not sure if you considered this already, but it would be nice to have the `Open Accessible View` in the command palette only when you're focused on something that supports it. When running the command in a random place, it just does nothing, which might be confusing to people who are trying to learn what the command does.

**Comment by meganrogge** [comment]
We want it in the command palette for discoverability purposes, but I agree with you that a no-op could be confusing.

**Comment by meganrogge** [comment]
This would be involved to fix because currently, we don't have a concept of `focusedItemWithAccessibleView`. We might have this one day when there's an audio cue played to indicate that.
