### ISSUE TITLE
Should  json sorting be a source action instead of a setting

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#191647]
Testing #191455

Should `json.sortOnSave.enable` be exposed using a code action (specifically a source action) instead of as a setting? Some advantages:

- We can reuse the existing `editor.codeActionsOnSave` setting instead of adding a new one
- Sorting will play nicer with other source actions since users can configure the order in which the actions run
- Users can trigger source actions through the `source action` context menu or with keybindings

**Comment by aiday-mar** [comment]
Hey @mjbvz, that's a good idea! I'll take note of it for implementation later

**Comment by aeschli** [comment]
Yes, makes sense!
