### ISSUE TITLE
Welcome content behavior of Quick Chat

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#191630]
Testing #191496

At the point where I ask something, whats the value of still showing the welcome text?

![Image](https://github.com/microsoft/vscode/assets/900690/16560674-d1cf-445b-91df-d6d077f617a2)

**Comment by bpasero** [comment]
Why not have a `/welcome` chat command to show it?

**Comment by TylerLeonhardt** [comment]
The welcome _text_ is out of our control. It's contributed by the Copilot Chat extension. I think it would be odd to have API for "quickWelcome" vs "chatViewWelcome"...

`/welcome` is an idea, although that's kinda what `/help` is suppose to be... but `/help` is crazy long.

@roblourens @daviddossett any thoughts?

**Comment by TylerLeonhardt** [comment]
related https://github.com/microsoft/vscode/issues/191626

**Comment by TylerLeonhardt** [comment]
It's not possible, today, to have a different welcome message for Quick Chat vs Chat View... and I'm not sure I'm sold on that differentiation existing because that seems like an odd API.

**Comment by TylerLeonhardt** [comment]
Talked to @joyceerhl about this and I think we're good here. we simplified the welcome message and now also provide a setting to disable it. That was plan work so it's verified through the usual process. No additional work needed here.
