### ISSUE TITLE
Welcome: overlay is not in sync with what is going on in the workbench

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#19165]
Testing: https://github.com/Microsoft/vscode/issues/19111

Our UI is dynamic, not only in the viewlet bar but also status bar. The overlay will quickly get out of sync:

![image](https://cloud.githubusercontent.com/assets/900690/22245696/9f18ccac-e231-11e6-9fcd-dc36b2451aa8.png)

**Comment by chrmarti** [comment]
Tracked with #18861
