### ISSUE TITLE
Unclear what part of the editor is dimmed

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#191608]
Testing #191527

The setting seems to suggest the editor gets dimmed, but I was also expecting breadcrumbs and maybe tabs to get dimmed. Also, editor controls (like find input) do not seem to get dimmed.

![Image](https://github.com/microsoft/vscode/assets/900690/eeea71fc-8841-466c-8b15-40b7e0f6e2d4)

**Comment by Tyriar** [comment]
Reopening breadcrumbs not dimming due to https://github.com/microsoft/vscode/pull/191852

**Comment by Tyriar** [comment]
Merging into https://github.com/microsoft/vscode/issues/236576

/duplicate
