### ISSUE TITLE
How to vote down a chat response isn't obvious

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#191623]
My response got filtered and the message says to vote down, but I don't see a way to vote down. I did realize that I could scroll up and then vote down, but this isn't obvious and it seems like the action that I'm being asked to take should be visible. 

![image](https://github.com/microsoft/vscode/assets/38270282/97448ea5-13fe-4382-8233-7830c196db5c)

**Comment by roblourens** [comment]
I think the main problem is that filtering is completely broken and should very rarely happen

**Comment by roblourens** [comment]
I don't want to do UX changes here, I'd just consider the issue to be overactive filtering which is known
