### ISSUE TITLE
Consider to revert dynamic grow from scroll when reopening

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#191627]
Testing #191496

I think that growing quick chat when you scroll is an interesting idea, but I would reset the size back to how it was when you reopen quick chat because its harder to manage the size to make it small again. You cannot just scroll to get back where you were.

**Comment by TylerLeonhardt** [comment]
Ahhh I struggle with this one because it might be that you wanna:
* scroll back to a former question
* switch to your editor
* switch back to that former question

which you get with the current behavior. You _can_ get back to the original size if you double click the sash... but that's maybe not obvious.

**Comment by TylerLeonhardt** [comment]
cc @Tyriar would love your thoughts.

**Comment by bpasero** [comment]
Actually had forgotten that a double click on the sash quickly restores the size, so maybe its not as bad...

**Comment by Tyriar** [comment]
I think we'd want some other way to reset as double clicking the sash isn't widely known. Do we reset the height when the question session times out? If so I think it's fine as is.

**Comment by Tyriar** [comment]
I guess something like 30 seconds before revert would work alright, either that or some button shows up which lets the user go back to auto.

**Comment by rzhao271** [comment]
What are some verification steps for this issue?
Here's what I see so far:
- If I ask a question, it starts from the top and starts growing downwards again
- If I close the chat and then reopen it a minute later, the answer is still there, and the chat is still expanded. If I ask another question, it starts from the top again, but that's true even if I don't wait 30 seconds
- If I manually move the sash, it seems like it's just stuck at that size

**Comment by TylerLeonhardt** [comment]
Verification steps:
* Ask a question like `reverse a linked list in TS`
* Get a long answer:
![image](https://github.com/microsoft/vscode/assets/2644648/e928cff5-515b-44eb-b34e-a2652ceba9ba)
* scroll down to make it bigger 
![image](https://github.com/microsoft/vscode/assets/2644648/dca45454-96e3-4308-a598-2c51dbad79a6)
* hide it and show it again quickly. It should still look like screenshot 2
* hide it and wait 1min and show it again. It should look like screenshot 1
