### ISSUE TITLE
Notebooks are not dimming

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#191615]
Testing #191527

![Image](https://github.com/microsoft/vscode/assets/900690/b3cc192b-e056-4fd1-b6ab-abfbf2e9b0f3)

**Comment by Tyriar** [comment]
Similar to https://github.com/microsoft/vscode/issues/189650, notebooks use a webview to isolate outside content. I don't see a way to hook this up using existing classes currently.

**Comment by Tyriar** [comment]
Merging into https://github.com/microsoft/vscode/issues/236576

/duplicate
