### ISSUE TITLE
The presentations style always defaults to text/plain even when images are displayed.

### ISSUE THREAD

**Issue by bhavyaus** [microsoft/vscode#191685]
Testing #191502

It requires an additional step by the user to change the presentation style.

**Comment by amunger** [comment]
can you clarify the behavior - is it displaying the text output instead of an image?

**Comment by bhavyaus** [comment]
Yes. It always defaults to displaying text. I have to manually change the presentation style to match the image.

**Comment by amunger** [comment]
I never have seen this myself or had any other reports of it happening, so I'm just closing this for now.
