### ISSUE TITLE
Weird wording: Toggle skipping this file

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#19168]
re #19096

The context menu contains an entry 'Toggle skipping this file' which is very weird wording. Toggle shouldn't be in the label but the label should toggle: 'Skip this file' and 'Antonyms(skip) this file' (whatever the reverse of skip should be, include?)

**Comment by roblourens** [comment]
Would like to do that but I can't change the label, or dynamically add/remove options in that context menu. cc @isidorn

**Comment by isidorn** [comment]
I do not think so but @jrieken would know best as he designed the extension menu contribution point

**Comment by roblourens** [comment]
I'm also curious if anyone has any thoughts on wording, whether we have one label or two. /cc @weinand 

This is also related to https://github.com/Microsoft/vscode/issues/19180

To have two labels, we would probably need a 'when' clause for a stack frame's presentation hint or something like that.

**Comment by jrieken** [comment]
re https://github.com/Microsoft/vscode/issues/19168#issuecomment-274886708: you need to have two commands which show depending on some context

**Comment by roblourens** [comment]
I'll leave it at least for now since we have UI for the skip status - presentationHint and tooltip. Keeping #19180.
