### ISSUE TITLE
Find and replace does nothing

### ISSUE THREAD

**Issue by rzhao271** [microsoft/vscode#191636]
Testing #191488

I tried a find and replace on a closed Jupyter notebook to see what would happen.

There were four matches for the query "to", and I tried replacing "to" with "from".
I got the dialog "Replace 4 occurrences across 1 file with 'from'?"
I hit "Replace" and the search results disappeared, but they showed up again when I hit the Refresh button.

**Comment by andreamah** [comment]
were these results in the inputs or the outputs of cells?

**Comment by rzhao271** [comment]
One result was in an input and three were in an output. Will see if I can link the notebook later.

**Comment by andreamah** [comment]
I see this bug, seems that replace is broken when the experimental setting is on.
