### ISSUE TITLE
Integrated terminal is not showing keystrokes

### ISSUE THREAD

**Issue by asilverman** [microsoft/vscode#191668]
Type: <b>Performance Issue</b>

When I open the integrated terminal and begin typing, the keystrokes are not showing until the 6th keystroke... (see video below)

https://github.com/microsoft/vscode/assets/9611108/02cc14e6-edd1-49a3-b633-83e5c135ea91

VS Code version: Code - Insiders 1.82.0-insider (f7973f357e7c316a88e8817886f41a843021fe74, 2023-08-28T05:35:52.131Z)
OS version: Windows_NT x64 10.0.22621
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) Platinum 8370C CPU @ 2.80GHz (16 x 2793)|
|GPU Status|2d_canvas: unavailable_software<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>opengl: disabled_off<br>rasterization: disabled_software<br>raw_draw: disabled_off_ok<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software<br>webgpu: unavailable_software|
|Load (avg)|undefined|
|Memory (System)|63.95GB (46.16GB free)|
|Process Argv|--folder-uri=vscode-remote://wsl+Ubuntu/home/asilverman/src/azure/bicep-types-az --remote=wsl+Ubuntu --crash-reporter-id 6054b85a-d2e2-41b9-9243-64629b4f1aa2|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	    95	 12936	code-insiders main
    0	    54	  4056	shared-process
    0	   131	  6932	extensionHost [2]
    0	   120	  7464	   gpu-process
    0	    99	 10252	ptyHost
    0	     5	  7664	     conpty-agent
    0	     6	 16772	     conpty-agent
    0	     5	 16956	     conpty-agent
    0	    99	 21848	     "C:\Program Files\PowerShell\7\pwsh.exe" -noexit -command "try { . \"c:\Users\asilverman\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\contrib\terminal\browser\media\shellIntegration.ps1\" } catch {}"
    0	     9	 11260	   crashpad-handler
    0	     6	 15024	   C:\Users\ASILVE~1\AppData\Local\Temp\vscode-insider-user-x64\CodeSetup-insider-ebd67244fb2da33ab078bb2baa96106fda29f336.exe /verysilent /log /update="C:\Users\ASILVE~1\AppData\Local\Temp\vscode-insider-user-x64\CodeSetup-insider-ebd67244fb2da33ab078bb2baa96106fda29f336.flag" /nocloseapplications /mergetasks=runcode,!desktopicon,!quicklaunchicon
    0	    25	 11404	     "C:\Users\ASILVE~1\AppData\Local\Temp\is-S8O68.tmp\CodeSetup-insider-ebd67244fb2da33ab078bb2baa96106fda29f336.tmp" /SL5="$420680,93144040,827904,C:\Users\ASILVE~1\AppData\Local\Temp\vscode-insider-user-x64\CodeSetup-insider-ebd67244fb2da33ab078bb2baa96106fda29f336.exe" /verysilent /log /update="C:\Users\ASILVE~1\AppData\Local\Temp\vscode-insider-user-x64\CodeSetup-insider-ebd67244fb2da33ab078bb2baa96106fda29f336.flag" /nocloseapplications /mergetasks=runcode,!desktopicon,!quicklaunchicon
    0	    91	 18088	fileWatcher [2]
    0	    19	 19220	   utility-network-service
    0	   227	 22372	window [2] (Welcome - Visual Studio Code - Insiders)
    0	   101	 24200	window [3] (Issue Reporter)
```

</details>
<details>
<summary>Workspace Info</summary>

```
;
```

</details>
Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythontb:30258533
pythonptprofiler:30281269
vshan820:30294714
vscod805:30301674
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30404738
py29gd2263:30784851
vscaat:30438846
vsclangdf:30492506
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30618038
2i9eh265:30646982
showlangstatbar:30737417
57b77579:30687741
pythonfmttext:30716741
fixshowwlkth:30771523
showindicator:30805243
pythongtdpath:30726887
i26e3531:30792625
gsofa:30797620
welcomedialog:30812478
pythonnosmt12:30779711
pythonidxpt:30768918
pythonnoceb:30776497
copilotsettingt:30808721
dsvsc013:30777762
dsvsc014:30777825
diffeditorv2:30786206
pythonlinttypecf:30823782
pythonmpsinfo:30815194
dsvsc015:30821418

```

</details>

**Comment by meganrogge** [comment]
does changing `terminal.integrated.gpuAcceleration` help?
