### ISSUE TITLE
Unable to write to dirty settings file

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#19161]
Now we have more and more menu actions that write immediatly to settings, for instance toggle word wrap.
If you have a dirty settings.json all these actions are broken as I always get the erros that I am unable to write to a dirty settings file

I believe this can hurt a lot of our users as they usualy do not have auto save on, and showing an error message in this case looks bad imho.

![screen shot 2017-01-24 at 12 26 32](https://cloud.githubusercontent.com/assets/1926584/22245529/a03d01b2-e230-11e6-97d5-b88235a0befb.png)

**Comment by sandy081** [comment]
Related to #19625

**Comment by sandy081** [comment]
We can write into the opened buffer but saving the file automatically might be problematic. Because user might have changes which he does not want to save. 

One approach is to inform user about saving the Settings for the action to take affect 
Or to enable auto save for the settings always

**Comment by isidorn** [comment]
Enable auto save for settings

**Comment by sandy081** [comment]
Provided an option to save and retry settings in this case. This is a good compromise and helps users to quickly fix it. 

![image](https://cloud.githubusercontent.com/assets/10746682/26062110/31e33ef0-398a-11e7-87c4-8984710ee20d.png)

**Comment by isidorn** [comment]
@sandy081 I get a nice error dialog to open settings, however I do not get the option to `save and retry`.
I am trying with user settings, latest insider

**Comment by sandy081** [comment]
@isidorn Please try when the file is dirty without any errors. If there are errors, then I show a message to open and fix errors.

**Comment by lynochka** [comment]
Hei, similary, would not allow to rewrite because of diry file {
    "terminal.integrated.shell.windows": "C:\\Windows\\System32\\cmd.exe"
}

please help
