### ISSUE TITLE
Dim unfocused setting link does not work

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#191643]
Forked off from https://github.com/microsoft/vscode/issues/191618

The link in settings does not work:

![Image](https://github.com/microsoft/vscode/assets/2193314/042441b1-8a56-4c29-8504-e8ee8833b221)

I'm pretty sure I'm following this reference exactly though:

https://github.com/microsoft/vscode/blob/64f1488b7e388e744cd80cd1bf5b238c9f193b0a/src/vs/workbench/contrib/files/browser/files.contribution.ts#L259

Config is defined here:

https://github.com/microsoft/vscode/blob/64f1488b7e388e744cd80cd1bf5b238c9f193b0a/src/vs/workbench/contrib/accessibility/browser/accessibilityConfiguration.ts#L127-L139

**Comment by rzhao271** [comment]
Found the issue; use the key `markdownDescription` instead of just `description`

**Comment by Tyriar** [comment]
This is not the first time I made that mistake 🤦
