### ISSUE TITLE
Removing a large answer should shrink the size again?

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#191631]
Testing #191496

I am left with quite some whitespace otherwise:

![Image](https://github.com/microsoft/vscode/assets/900690/2be3aed2-ecb8-410c-b43c-2fb5426254cd)

**Comment by TylerLeonhardt** [comment]
I can't seem to repro this... did you use the sash to resize? We currently have the sash take over resize when you use it (so dynamic height changes are disabled)

[Screencast from 08-29-2023 05:17:32 PM.webm](https://github.com/microsoft/vscode/assets/2644648/d066350b-88ca-4709-b62a-8d3c172509ab)

**Comment by bpasero** [comment]
I had actually put a lot of words into my question and after removal the space did not remove:

![Recording 2023-08-30 at 09 11 51](https://github.com/microsoft/vscode/assets/900690/a4d8fa28-cdd1-4539-b5f3-6de6bc73b877)

**Comment by TylerLeonhardt** [comment]
No but you used the sash. If you use the sash, then you are saying "I don't want the dynamic feature" I want a stable height. This was requested by @Tyriar & @rebornix and implemented in: https://github.com/microsoft/vscode/pull/191533
