### ISSUE TITLE
Link detection captures pwd shell prompt >

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode#191682]
1. Have a shell prompt which prints the current working directory
2. Run Terminal: Open Detected Link...
3. :bug: the > caret is included, so the link is not deduplicated

![Image](https://github.com/microsoft/vscode/assets/30305945/474e9b24-091b-44f9-b30d-6533b6ddcd05)

**Comment by Tyriar** [comment]
This is working as designed and working around this would go against how it works as the workspace search links is driven by the `terminal.integrated.wordSeparators` setting. They're low priority and at the bottom already so it's a pretty minor thing
