### ISSUE TITLE
Progressive rendering freezes sometimes

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#191728]
![Image](https://github.com/microsoft/vscode/assets/323878/7dff60ed-8650-4b65-8a30-f0af15203336)

I thought I noticed this happening from time to time after we made changes to how rendering works, but in this case with my test extension it's pretty obvious, I will investigate

**Comment by roblourens** [comment]
This is due to losing https://github.com/microsoft/vscode/blob/6c3e3dba23e8fadc360aed75ce363ba185c49794/src/vs/workbench/contrib/chat/common/chatViewModel.ts#L347-L351. `isFullyRendered` means that it was fully rendered _so far_ and was reset when we get more content. So now if we render everything in a markdown chunk then get more data, this https://github.com/microsoft/vscode/blob/1b4eb0de701e14ba66fc208b177886b85c78eadb/src/vs/workbench/contrib/chat/browser/chatListRenderer.ts#L452 keeps it from getting rendered.

It's a bit more complicated with our new way of not constantly re-rendering. The view model doesn't currently know which chunks changed, so it can't reset that flag. The renderer only knows that the chunk was previously fully rendered but doesn't know that it has different data now.

We could go back to rerendering everything all the time (don't really want to do that now that we have the nice optimization) or I think the model has to communicate what changed when it fires `onDidChange`, it would have to include which response changed and which chunks of data. Or maybe there is a solution where we always rerender all markdown blocks but keep the rendered tree data?

**Comment by joyceerhl** [comment]
> I think the model has to communicate what changed when it fires 

That seems reasonable, I'll look into a fix
