### ISSUE TITLE
Welcome: shorten home path with ~ (Linux, macOS)

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#19175]
Testing: https://github.com/Microsoft/vscode/issues/19111

Just an idea to maybe align our display of recent paths to use "~" if it matches the home path:

![image](https://cloud.githubusercontent.com/assets/900690/22246149/a94985ca-e233-11e6-9fde-d197ba60ed13.png)

**Comment by chrmarti** [comment]
Tracked as #18950
