### ISSUE TITLE
[WelcomeUX] Clicking into welcome editor does not make it active

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#19177]
Testing: https://github.com/Microsoft/vscode/issues/19111

* move the welcome editor to another group and make the first group active
* click into welcome editor
=> group that belongs to welcome editor is not getting active

This works for markdown preview so there is something missing to make the focus work. I wonder if this is `tabindex`, though I do not see it defined in the webview part either.

Could also be this: https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/html/browser/webview-pre.js#L46

**Comment by chrmarti** [comment]
@bpasero Not sure I got this one right, care to take a look at the fix? https://github.com/Microsoft/vscode/commit/5cd3c8f15c5a1007bc777092e2e6e7d5791d1ccb
