### ISSUE TITLE
Cannot undo skipping of file

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#19174]
re #19096

<img width="1129" alt="screen shot 2017-01-24 at 12 48 26" src="https://cloud.githubusercontent.com/assets/1794099/22246115/7c9d2d60-e233-11e6-8df1-c9729a6d5ba1.png">

See above screen shot: Once I have skipped `applib.js` I can never undo that because it won't ever appear in my call stack. I need to restart the debugger

**Comment by jrieken** [comment]
actually not true

**Comment by roblourens** [comment]
I'm curious how you undid it. You can set a breakpoint in it at least but I thought this might confuse people at some point.

**Comment by jrieken** [comment]
It would still stop there and then I could toggle skipping from the call stack view
