### ISSUE TITLE
bad input box styling in quick chat UI

### ISSUE THREAD

**Issue by amunger** [microsoft/vscode#191704]
![image](https://github.com/microsoft/vscode/assets/2019016/5c6d5e3d-b671-49bd-b3da-7292c926ac10)

I'm not sure how I got to this point, but resizing the window just makes it worse:

![image](https://github.com/microsoft/vscode/assets/2019016/b248a12c-4f82-45c0-b659-b89195d10819)

**Comment by TylerLeonhardt** [comment]
I was able to repro this. This seems to happen when you hide Quick Chat while a response is being written in.

It appeared with recording because when you hide Quick Chat, recording doesn't stop. It keeps listening and will accept a question.
