### ISSUE TITLE
[WelcomeUX] Typos in Interactive Playground

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#19178]
While testing #19111:

our" -> "out":
![2017-01-24_13-01-14](https://cloud.githubusercontent.com/assets/1898161/22246454/5c468f78-e235-11e6-8bfa-a1c6c987112b.png)

"Thats" -> "That's"  and "th" -> "the":
![2017-01-24_13-05-45](https://cloud.githubusercontent.com/assets/1898161/22246626/ef7088b2-e235-11e6-893f-1e1ba681cca8.png)

"require api" -> "Request API":
![2017-01-24_13-56-54](https://cloud.githubusercontent.com/assets/1898161/22248031/04fec246-e23d-11e6-899a-fe518a9f5f05.png)

"Since" missing at the start of sentence:
![2017-01-24_14-03-49](https://cloud.githubusercontent.com/assets/1898161/22248271/10b36000-e23e-11e6-8383-8384a1595efc.png)

"thorough" -> "through":
![2017-01-24_14-08-18](https://cloud.githubusercontent.com/assets/1898161/22248386/a823e4d2-e23e-11e6-9e0a-c1c55d496909.png)

"you" -> "your":
![2017-01-24_14-11-36](https://cloud.githubusercontent.com/assets/1898161/22248488/18a3bc3c-e23f-11e6-9ee6-464cb2ff1d74.png)

"is" -> "it":
![2017-01-24_14-13-43](https://cloud.githubusercontent.com/assets/1898161/22248550/5ef5759a-e23f-11e6-9019-025404f4c56a.png)

"unbound"?
![2017-01-24_14-15-08](https://cloud.githubusercontent.com/assets/1898161/22248588/8ee1b6b0-e23f-11e6-94e4-007b44a318d9.png)

**Comment by ramya-rao-a** [comment]
2 things are still pending from the original list


"Since" missing at the start of sentence:
![2017-01-24_14-03-49](https://cloud.githubusercontent.com/assets/1898161/22248271/10b36000-e23e-11e6-8383-8384a1595efc.png)


"unbound"?
![2017-01-24_14-15-08](https://cloud.githubusercontent.com/assets/1898161/22248588/8ee1b6b0-e23f-11e6-94e4-007b44a318d9.png)

**Comment by chrmarti** [comment]
@ramya-rao-a Did you have SCM preview enabled? That is tracked as #19337.

**Comment by ramya-rao-a** [comment]
I had SCM enabled yes. That leaves the missing "since"
