### ISSUE TITLE
Quick search: No feedback when a search results in 0 results

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#191799]
I searched for the wrong word here but I needed to wait several seconds to make sure the search had completed:

![Image](https://github.com/microsoft/vscode/assets/2193314/baaca2b3-ba54-4d0d-9195-13e14ddca440)

There should be some indicator for no results in the quick search

**Comment by andreamah** [comment]
I previously relied on the progress indicator to show that the search was no longer running, but it'd be nice to visually see the `0 results` note

**Comment by Tyriar** [comment]
It feels a little too subtle to rely on the loading bar as it might search so fast it doesn't show at all
