### ISSUE TITLE
Moving the VS Code repo dev container

### ISSUE THREAD

**Issue by bamurtaugh** [microsoft/vscode#191726]
In archiving https://github.com/microsoft/vscode-dev-containers, the main remaining step is to move the VS Code repo config somewhere else: https://github.com/microsoft/vscode-dev-containers/tree/main/repository-containers/images/github.com/microsoft/vscode.

**Comment by alexdima** [comment]
A lot of other definitions live at https://github.com/microsoft/vscode-linux-build-agent

**Comment by chrmarti** [comment]
We are not using that image anymore.
