### ISSUE TITLE
Clicking on arrows in diff editor adds breakpoint

### ISSUE THREAD

**Issue by aiday-mar** [microsoft/vscode#191771]
I like the arrow feature in the diff editor. Unfortunately when I click on the arrow to transfer code from one side to the other, it adds a breakpoint in the gutter often.

https://github.com/microsoft/vscode/assets/61460952/e1b6d5ea-59c5-45aa-a5d4-5f6270796eac

**Comment by joyceerhl** [comment]
@hediet, @alexdima and I added the glyph margin widget so that the diff editor revert decoration and the breakpoint decoration can register onclick handlers on their own DOM nodes, which if adopted would address this issue

**Comment by hujghc** [comment]
i have the same issue
