### ISSUE TITLE
No accessibility help for markdown cell in preview mode

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode#191718]
1. Focus a markdown cell in preview mode like https://insiders.vscode.dev/github/microsoft/vscode/blob/main/.vscode/notebooks/my-endgame.github-issues#C6:L1
2. Open Accessibility Help
3. :bug: accessibility help does not appear 

If I focus a code cell I get the help view

**Comment by meganrogge** [comment]
IMO, this should not be working at all for github issue notebooks

**Comment by joyceerhl** [comment]
Why is that? The notebooks UI and keybindings/commands are generic (though can be overridden by extensions)
