### ISSUE TITLE
Notification Accessible View: Go to Symbol toolbar item does not work

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode#191708]
Testing #191344

The Go to Symbol toolbar item opens a  quick input and when I enter a word that is in the notification text it highlights that, but pressing enter doesn't go there. (At least that's what I expected it to do.)

**Comment by chrmarti** [comment]
<img width="619" alt="image" src="https://github.com/microsoft/vscode/assets/9205389/19cf03c4-af13-4645-8d06-b275b619efc6">
After pressing enter:
<img width="623" alt="image" src="https://github.com/microsoft/vscode/assets/9205389/e4bd6ee2-a9fc-4d5f-9e23-d81ea05af07b">

**Comment by meganrogge** [comment]
@chrmarti here's what I'm seeing, what are you seeing?
https://github.com/microsoft/vscode/assets/29464607/a1ccd0a2-d0ac-45c9-8697-09a26f6bc3bf

**Comment by meganrogge** [comment]
that's working as designed - it's taking you to that entry

**Comment by meganrogge** [comment]
it won't go to the word that's highlighted - I don't think that happens for the editor's go to symbol either. reopen if you think it does
