### ISSUE TITLE
Focused view doesn't show when focusing the extensions view

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#191748]
Testing #191341

1. Append `${separator}${focusedView}` to the `window.title` setting
2. Focus the Extensions view

🐛 It doesn't show the view's name in the title. It seems to work for all other views.

https://github.com/microsoft/vscode/assets/22350/00728a91-b72f-4cea-b494-22afe31c88e5

**Comment by meganrogge** [comment]
@sandy081 since you own both the views service and extensions editor, could you pls take this one as I'm not sure if it's by design?

**Comment by sandy081** [comment]
Search input is not part of any view, hence there is no view in focus. If there is no view in focus, we should show the view container in focus.

**Comment by sandy081** [comment]
@meganrogge Moving this back to you, since you have implemented this feature. I am happy to review.

**Comment by meganrogge** [comment]
This now works - it shows `Installed` by default
