### ISSUE TITLE
Quick Text Search: Improve the experience when there are many matches

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode#191754]
Testing #191499

- open the vscode repo
- open command palette, type `% semantic`

![Image](https://github.com/microsoft/vscode/assets/6461412/36846027-ed1c-4232-bd75-f8a2303d2577)

There are many matches which makes the quick view less practical
Some suggestions:
- show the total number of matches in a description (`50 matches in 7 files`)
- reduce the number of matches per file if the list is long (e.g. 3 matches). 
- allow to filter for the file name as well

**Comment by andreamah** [comment]
posted this on https://github.com/microsoft/vscode/issues/191683 to group together similar issues
