### ISSUE TITLE
Indentation is not being identified and giving the error (IndentationError: expected an indented block after 'if' statement on line 1)

### ISSUE THREAD

**Issue by Jonathan50** [microsoft/vscode#191740]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.81.1
- OS Version: 

Steps to Reproduce:

1. if 52 > 9:
2.    print('sky')
3. 
Even when i indent properly i still get the error (IndentationError: expected an indented block after 'if' statement on line 1)

**Comment by rebornix** [comment]
You can probably turn on `editor.renderWhitespace` rendering to check if the indentation/spaces are correct.
