### ISSUE TITLE
Sluggish performance on vs code

### ISSUE THREAD

**Issue by JamesWallinder** [microsoft/vscode#191752]
Type: <b>Performance Issue</b>

Since I downloaded vs code it has been performing sluggishly. There is a noticeable input lag with scrolling, and it feels like the program is running at a slow frame rate. I have tried uninstalling all extensions, and doing a clean reinstall of vs code, but the sluggishness persists. Upon using the performance profiler, I noticed I had many dropped frames. When I enable smooth carat animation, it makes the input latency higher when typing

VS Code version: Code 1.81.1 (6c3e3dba23e8fadc360aed75ce363ba185c49794, 2023-08-09T22:22:42.175Z)
OS version: Windows_NT x64 10.0.22621
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 5600 6-Core Processor               (12 x 3493)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.89GB (8.44GB free)|
|Process Argv|--crash-reporter-id 737d8d01-50ca-4c5a-97a8-62d13e01c652|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	   107	 22664	code main
    0	   117	  2768	extensionHost [1]
    0	   118	  4588	     electron-nodejs ("C:\Users\User\AppData\Local\Programs\Microsoft VS Code\Code.exe" --ms-enable-electron-run-as-node --max-old-space-size=3072 "c:\Users\User\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js" --useInferredProjectPerProjectRoot --enableTelemetry --cancellationPipeName C:\Users\User\AppData\Local\Temp\vscode-typescript\16c1df4326f00a6ac4eb\tscancellation-9f4260ef2b4546b50a9c.tmp* --locale en --noGetErrOnBackgroundUpdate --validateDefaultNpmLocation --useNodeIpc)
    0	    82	 15492	       electron-nodejs ("C:\Users\User\AppData\Local\Programs\Microsoft VS Code\Code.exe" --ms-enable-electron-run-as-node "c:/Users/User/AppData/Local/Programs/Microsoft VS Code/resources/app/extensions/node_modules/typescript/lib/typingsInstaller.js" --globalTypingsCacheLocation C:/Users/User/AppData/Local/Microsoft/TypeScript/5.1 --enableTelemetry --typesMapLocation "c:/Users/User/AppData/Local/Programs/Microsoft VS Code/resources/app/extensions/node_modules/typescript/lib/typesMap.json" --validateDefaultNpmLocation)
    0	   108	  5932	     electron-nodejs ("C:\Users\User\AppData\Local\Programs\Microsoft VS Code\Code.exe" --ms-enable-electron-run-as-node --max-old-space-size=3072 "c:\Users\User\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js" --serverMode partialSemantic --useInferredProjectPerProjectRoot --disableAutomaticTypingAcquisition --cancellationPipeName C:\Users\User\AppData\Local\Temp\vscode-typescript\16c1df4326f00a6ac4eb\tscancellation-dfb6bc27ef695f24c977.tmp* --locale en --noGetErrOnBackgroundUpdate --validateDefaultNpmLocation --useNodeIpc)
    0	   238	  6568	window [1] (● defensive.js - 1 - Web Development Essentials - Visual Studio Code)
    0	    77	 10740	fileWatcher [1]
    0	    89	 13580	   utility-process
    0	    45	 13864	   utility-network-service
    0	    97	 17484	window [4] (Issue Reporter)
    0	    90	 20844	shared-process
    0	   134	 21112	   gpu-process
    0	    28	 23760	   crashpad-handler
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (● defensive.js - 1 - Web Development Essentials - Visual Studio Code)
|    Folder (1 - Web Development Essentials): 179 files
|      File types: js(54) pdf(38) html(29) txt(4) jpg(4) png(4) json(1)
|      Conf files: launch.json(1);
```

</details>
<details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
prettier-vscode|esb|10.1.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
py29gd2263:30792226
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
vsccc:30803844
2e4cg342:30602488
f6dab269:30613381
2i9eh265:30646982
showlangstatbar:30737416
03d35959:30757346
pythonfmttext:30731395
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
gsofa:30804715
pythonnosmt12:30797651
pythonidxpt:30805730
pythonnoceb:30805159
synctok:30821570
dsvsc013:30795093
dsvsc014:30804076
diffeditorv2:30821572

```

</details>

[Profile-20230830T090229.zip](https://github.com/microsoft/vscode/files/12472992/Profile-20230830T090229.zip)

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by JamesWallinder** [comment]
The insider build gave me the same sluggish performance. The option to enable smooth carat animation for the cursor made my input latency noteceably high. Upon saving the performance profile I was also given this message in the dev tools console: Failed to save timeline: The request is not allowed by the user agent or the platform in the current context. (NotAllowedError)
[Trace-20230831T091541.zip](https://github.com/microsoft/vscode/files/12483430/Trace-20230831T091541.zip)

**Comment by bpasero** [comment]
@JamesWallinder so is this only related to smooth caret animation, when you turn it off its OK?

**Comment by JamesWallinder** [comment]
The smooth carat animation makes my typing input latency high, when it is disabled it isn't high, but the scroll is still slugish even with it turned off

**Comment by bpasero** [comment]
@JamesWallinder this is about scrolling in the editor only? Or is for example explorer scrolling also slow?

**Comment by JamesWallinder** [comment]
The explorer also scrolls slowly yes

**Comment by bpasero** [comment]
Can you see if it still reproduces when disabling the GPU support in VSCode? You can do that by running VSCode from the command line like this: `code --disable-gpu`

If that helps, you can permanently configure this option via:
* Command Palette search for "Configure Runtime Arguments"
* Set `disable-hardware-acceleration: true`
* Restart

**Comment by JamesWallinder** [comment]
After doing this it has fixed the issue. Thank you so much! The application is very snappy now.

**Comment by bpasero** [comment]
Ok thats odd. Its safe to keep the setting enabled.
