### ISSUE TITLE
NotebookEditorStickyScroll - test0: should render empty on macOS

### ISSUE THREAD

**Issue by andreamah** [microsoft/vscode#191712]
>   1) NotebookEditorStickyScroll
>        test0: should render empty, 	scrollTop at 0:
>      
>   
> 
> 
> 
> 2023-08-29T19:06:19.740Z pw:browser [pid=6370] <gracefully close start>
> 2023-08-29T19:06:19.784Z pw:browser [pid=6370] <process did exit: exitCode=0, signal=null>
> 2023-08-29T19:06:19.785Z pw:browser [pid=6370] starting temporary directories cleanup
> 2023-08-29T19:06:22.945Z pw:browser [pid=6370] finished temporary directories cleanup
> 2023-08-29T19:06:22.946Z pw:browser [pid=6370] <gracefully close end>
> The followings tests are failing:
>  - NotebookEditorStickyScroll test0: should render empty, 	scrollTop at 0 (reason: Timeout of 30000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (vs/workbench/contrib/notebook/test/browser/notebookStickyScroll.test))

https://dev.azure.com/monacotools/Monaco/_build/results?buildId=229592&view=logs&j=eb0ed907-d5fa-57af-e5f4-b64d416225ca&t=9c99b310-4ae0-5cc3-0e4d-89398f1323c8

Not sure if this is a flaky error, but it's causing the build to fail.

**Comment by Yoyokrazy** [comment]
Flakey, and likely related to webkit and playwright. Working on another branch to see if bumping @playwright/test might address the problem.

For now, skipping this test suite on web.

cc: @connor4312

**Comment by Yoyokrazy** [comment]
Closing, as it was fixed previously with https://github.com/microsoft/vscode/pull/193711
