### ISSUE TITLE
Font ligatures and Haxe function types

### ISSUE THREAD

**Issue by Gama11** [Microsoft/vscode#19183]
- VSCode Version: Code - Insiders 1.9.0-insider (4265f5e35cb3ea8ba7e0cf6b14ec606b6f8647ea, 2017-01-24T10:37:36.620Z)
- OS Version: Windows_NT ia32 10.0.14986

I'm using the Haxe grammar from the [Haxe Support](https://marketplace.visualstudio.com/items?itemName=nadako.vshaxe) extension. Font ligatures don't always behave like I would expect them to - the reply to [this issue](https://github.com/Microsoft/vscode/issues/17306#issuecomment-267346855) suggests that they are based on the grammar's tokens.

However, Haxe function types with type parameters don't use the correct ligatures, here it groups `>-` instead of `->`:

![](http://i.imgur.com/3kZxdXn.png)

Adding a space, the arrow uses the ligature I would expect:

![](http://i.imgur.com/eYMgSgj.png)

Our grammar groups them into scopes correctly.

http://i.imgur.com/ZuTZ3w1.png
http://i.imgur.com/JBhllzd.png

With the Java grammar, it suddenly works like expected:

![](http://i.imgur.com/bkqYTZh.png)

The difference seems to be that `>` is scoped as `storage.type.generic.java` there, which doesn't seem correct to me. For Haxe, we use the same one that TS uses, `punctuation.definition.typeparameters.end.hx`.

___________

Another example:

`=>` is turned into a ligature, despite being two different tokens.

http://i.imgur.com/x3j0ryM.png
http://i.imgur.com/vqWMkMV.png

Am I simply misunderstanding how font ligatures work / are we using incorrect scopes?

**Comment by alexandrudima** [comment]
Font ligatures are rendered at a lower level, by Chromium. Chromium is not aware of tokens, except perhaps if they would have different colors.

I am thinking the font has two rules here:
* `>-` should be rendered with a ligature
* `->` should be rendered with a ligature
* now the problem appears that `>->` can be interpreted both as `(>-)>` or `>(->)` when ligatures are rendered

I can only guess that we are observing `>->` being interpreted as `(>-)>`.

One possible way to workaround this problem would be to:
1. have a grammar that gives different scopes to `>` and `->` in `>->`
2. have a theme that gives different colors to those different scopes (even if the color would be different by an indistinguishable shade)

**Comment by Gama11** [comment]
I'm not sure since when exactly (I haven't tried font ligatures in a while), but this case now works as expected in VSCode 1.22.2. :)

![](https://i.imgur.com/nSEKHQE.png)
