### ISSUE TITLE
run configration button

### ISSUE THREAD

**Issue by AbdullahMahmoud2003** [microsoft/vscode#191894]
Type: <b>Bug</b>

i accedintly hided the green run button in the left top corner and i cant get it back ,i dont meaan the"run and debug" button on the left bar
i mean the configration one, and i "more actions"button doesnt have unhide for it please help

VS Code version: Code 1.81.1 (6c3e3dba23e8fadc360aed75ce363ba185c49794, 2023-08-09T22:22:42.175Z)
OS version: Windows_NT x64 10.0.22621
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i5-11400H @ 2.70GHz (12 x 2688)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|7.74GB (0.87GB free)|
|Process Argv|--crash-reporter-id cef74b74-0043-4ded-9a91-daee09bea5c1|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (18)</summary>

Extension|Author (truncated)|Version
---|---|---
gen-multi-types-images|aim|0.0.4
dart-code|Dar|3.70.0
flutter|Dar|3.70.0
emulate|Die|1.6.0
vscode-html-css|ecm|1.13.1
prettier-vscode|esb|10.1.0
vscode-peacock|joh|4.2.2
material-icon-theme|PKi|4.30.1
LiveServer|rit|5.7.9
iconfont-preview|stx|0.0.5
intellicode-api-usage-examples|Vis|0.2.8
vscode-gradle|vsc|3.12.7
vscode-java-debug|vsc|0.54.0
vscode-java-dependency|vsc|0.23.1
vscode-maven|vsc|0.42.0
vscode-icons|vsc|12.5.0
chat-gpt|zha|1.6.62
material-theme|zhu|3.16.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
vscccc:30803845
3biah626:30602489
89544117:30613380
2i9eh265:30646982
showlangstatbar:30737416
0bi6i642:30823812
03d35959:30757346
pythonfmttext:30731395
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
gsofb:30804716
pythonnosmt12:30797651
pythonidxpt:30805730
pythonnoceb:30805159
synctok:30821570
dsvsc013:30795093
dsvsc014:30804076
diffeditorv1:30821571

```

</details>

**Comment by roblourens** [comment]
Try F1 > the "Reset All Menus" command

**Comment by AbdullahMahmoud2003** [comment]
It worked well
Thank you sir

في الجمعة، ١ سبتمبر ٢٠٢٣, ٢:٣٨ ص Rob Lourens ***@***.***> كتب:
