### ISSUE TITLE
Renaming nested subdirectory in SSH freezes file explorer

### ISSUE THREAD

**Issue by danwdart** [microsoft/vscode#191823]
Type: <b>Bug</b>

In SSH, have  directory/subdirectory/file. Then try to rename the subdirectory via right click or shortcut. The file explorer view still allows selection of files and context menu but no longer responds to any command.

VS Code version: Code 1.81.1 (Universal) (6c3e3dba23e8fadc360aed75ce363ba185c49794, 2023-08-09T22:20:33.924Z)
OS version: Darwin arm64 22.5.0
Modes:
Remote OS version: Linux arm64 6.4.11
Remote OS version: Linux arm64 6.4.12

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M2 Max (12 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|32.00GB (0.07GB free)|
|Process Argv|--crash-reporter-id 84e05e62-7adc-4d6e-81f7-f9f6d2bb492d|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: zhang|
|OS|Linux arm64 6.4.11|
|CPUs|Neoverse-N1 (1 x 0)|
|Memory (System)|5.77GB (3.20GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: alderamin-forwarded|
|OS|Linux arm64 6.4.12|
|CPUs|unknown (8 x 0)|
|Memory (System)|15.58GB (13.04GB free)|
|VM|0%|
</details><details><summary>Extensions (18)</summary>

Extension|Author (truncated)|Version
---|---|---
Nix|bbe|1.0.1
arm|dan|1.7.4
dotenv|mik|1.0.1
remote-containers|ms-|0.304.0
remote-ssh|ms-|0.102.0
remote-ssh-edit|ms-|0.86.0
remote-explorer|ms-|0.4.1
linkerscript|Zix|1.0.3
nix-env-selector|arr|1.0.9
vscode-ghc-simple|dra|0.2.3
vscode-github-actions|git|0.26.1
haskell|has|2.4.1
haskell-linter|hoo|0.0.6
language-haskell|jus|3.6.0
vscode-docker|ms-|1.26.0
haskell-ghcid|ndm|0.3.1
vscode-direnv|Rub|0.0.2
stylish-haskell|vig|0.0.10

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
vsccc:30803844
2e4cg342:30602488
89544117:30613380
a9j8j154:30646983
showlangstatbar:30737416
0bi6i642:30823812
03d35959:30757346
pythonfmttext:30731395
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
gsofb:30804716
pythonnosmt12:30797651
pythonidxpt:30805730
pythonnoceb:30805159
dsvsc013:30795093
dsvsc014:30804076
diffeditorv2:30821572

```

</details>

**Comment by lramos15** [comment]
Can you try insiders? https://code.visualstudio.com/insiders/

**Comment by danwdart** [comment]
Ah yes, of course. Will do

**Comment by danwdart** [comment]
It's fine on insiders, actually. I guess that means it'll be fixed in next stable release or so. Cheers
