### ISSUE TITLE
Problem with `setBreakPointsRequest`

### ISSUE THREAD

**Issue by Krzysztof-Cieslak** [Microsoft/vscode#19185]
I've been recently working on creating .Net Framework debugger for Windows. So far everything has been pretty OK, and working well with one small exception - I can't get breakpoints working at all.

As far as I can tell `setBreakPointsRequest` method of my `DebugSession` is never hit. Any idea what I'm doing wrong?

Code of debugger adapter is here: https://github.com/ionide/ionide-vscode-fsharp/blob/debugger/src/Debugger/debugger.fs.

**Comment by weinand** [comment]
@isidorn in what conditions does the VS Code debug UI **not** call setBreakPointsRequest?

**Comment by isidorn** [comment]
If the 'initialized' event is never recieved from the debug adapter 
If a file is dirty for which a breakpoint is added.

More details https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/debug/electron-browser/debugService.ts#L904

**Comment by Krzysztof-Cieslak** [comment]
OK, looks like I'm not sending initialized event https://github.com/ionide/ionide-vscode-fsharp/blob/debugger/src/Debugger/debugger.fs#L30-L36

**Comment by weinand** [comment]
from https://code.visualstudio.com/docs/extensionAPI/api-debugging#_the-vs-code-debug-protocol-in-a-nutshell:

> Since VS Code persists breakpoints on behalf of the debug adapter, it has to register the breakpoints with the debug adapter when a session starts. Since VS Code does not know when is a good time for this, the debug adapter is expected to send an initialize event to VS Code to announce that it is ready to accept breakpoint configuration requests.

**Comment by Krzysztof-Cieslak** [comment]
Can confirm that breakpoints are working without any problem after sending `InitializedEvent`. Thanks for help.
