### ISSUE TITLE
Bracket colorization for markdown links with mismatched parenthesizes 

### ISSUE THREAD

**Issue by eleanorjboyd** [microsoft/vscode#191843]
![image](https://github.com/microsoft/vscode/assets/26030610/2fe78b57-ffcb-4c35-9a80-72e3cef54c97)

issue surfaced when testing: https://github.com/microsoft/vscode/issues/188867

It correctly displays with <> but the rightmost parenthesis is still highlighted red. Likely the bracket pair colorization isn't working properly in this case.

**Comment by DibyodyutiMondal** [comment]
I am not sure if this is a problem with vs code or the language service, but I'm assuming it is the language service. Apologies in advance if I'm wrong.

The following snippet works fine, and the code highlighting in the editor works fine too, except when I wrap the type parameter.

### snippet
```typescript
export const mapResponse = {
  blogPost: <I extends { created: string; updated: string; }>(input: I) => {
    return {
      ...input,
      created: DateTime.fromISO(input.created),
      updated: DateTime.fromISO(input.updated)
    };
  }
};
```
#### `return` keyword is correctly identified as a keyword
![image](https://github.com/typescript-language-server/typescript-language-server/assets/50345677/92707eff-52c4-4a02-b4c1-97a5a91e1e70)

#### `return` keyword is incorrectly identified as a type(?)
![image](https://github.com/typescript-language-server/typescript-language-server/assets/50345677/9965189b-6936-4b67-a21e-eaa9b616a7cb)

**Comment by DibyodyutiMondal** [comment]
I have a similar issue. I am unsure if this is a related problem, or a separate one. Apologies in advance if I'm wrong.


The following snippet works fine, and the code highlighting in the editor works fine too, except when I wrap the type parameter.

### snippet
```typescript
export const mapResponse = {
  blogPost: <I extends { created: string; updated: string; }>(input: I) => {
    return {
      ...input,
      created: DateTime.fromISO(input.created),
      updated: DateTime.fromISO(input.updated)
    };
  }
};
```
#### `return` keyword is correctly identified as a keyword
![image](https://github.com/typescript-language-server/typescript-language-server/assets/50345677/92707eff-52c4-4a02-b4c1-97a5a91e1e70)

#### `return` keyword is incorrectly identified as a type(?)
![image](https://github.com/typescript-language-server/typescript-language-server/assets/50345677/9965189b-6936-4b67-a21e-eaa9b616a7cb)
