### ISSUE TITLE
Though i see every file as saved.But i see my VS code still shows as one unsaved file.

### ISSUE THREAD

**Issue by srisrinu1** [microsoft/vscode#191856]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.81.1
- OS Version: Windows 10(Version 22H2 (OS Build 19045.3324))

Steps to Reproduce:

1.I see that Visual Studio Code is showing one file as unsaved, but all of my files seem to be saved when I check them individually.

I'm attaching the snapshot.Please check it.

![image](https://github.com/microsoft/vscode/assets/60247258/c8c0ced3-1495-4130-b174-ff66bda2aa42)

**Comment by lramos15** [comment]
Looks like you have an untitled file open. It's the one with the black dot in open editors. Seems like `/* global .../`

**Comment by srisrinu1** [comment]
Thanks for pointing it out.Fixed it!
