### ISSUE TITLE
Add new scope to VS Code settings for only workspace configurable

### ISSUE THREAD

**Issue by nturinski** [microsoft/vscode#191834]
I was hoping we could add a new scope to VS Code settings. Currently, VS Code settings have the following scopes:
 
![image](https://github.com/microsoft/vscode/assets/5290572/1c1dfac4-1ea7-4e4b-a494-845de31ca18b)

None of these scopes describe a setting that is only workspace configurable. We were hoping we could have a scope that would only show up in the workspace and not in Global and User settings.

For context as to why we want this: we use vscode settings to help save default Azure resources that users want to deploy that specific project to. This setting doesn't really make sense to show as a user setting since what resource you want to deploy to is generally always going to be tied to the workspace/project.

We're worried that users may end up in a scenario where they have accidentally altered their user setting rather than their workspace setting, and now they will deploy every new project to whatever that resource is

**Comment by gjsjohnmurray** [comment]
When fetching the setting your extension could use inspect() instead of get(), then check that there's a value at workspace level.

**Comment by nturinski** [comment]
Thanks for the tip! 

We'll do that in the interim, but we think that it could be valuable to have a `workspace` level scope. Having the setting exist in `User Settings` is a bit confusing and would be especially confusing for a user to configure a setting in `User Settings` rather than `Workspace Settings`, but having the setting be ignored.

**Comment by sandy081** [comment]
Let us know if workaround mentioned by @gjsjohnmurray works for you?

**Comment by MicroFish91** [comment]
This workaround works for us, thank you!
