### ISSUE TITLE
The hover shouldn't know so much about the color picker

### ISSUE THREAD

**Issue by alexdima** [microsoft/vscode#191808]
re https://github.com/microsoft/vscode/blob/4538c811ebacf7eee5defab22d560dd57fdcd785/src/vs/editor/contrib/hover/browser/hover.ts#L198-L206

The code has a number of flaws, some are small:
1. it inlines a CSS class name as a string which might change somewhere else but forget to be updated here
2. it brings in knowledge about the color picker straight into the hover, which tries to avoid having a lot of knowledge about the individual hover parts
3. it hides the hover when the mouse moves over a color box even if the hover is currently showing an error

To reproduce 3. the following extension can be used:

```
const col = vscode.languages.createDiagnosticCollection('test');
col.set(vscode.window.activeTextEditor.document.uri, [
    new vscode.Diagnostic(new vscode.Range(0, 0, 1000, 1000), 'A diagnostic!', vscode.DiagnosticSeverity.Error)
]);
```

**Comment by aiday-mar** [comment]
This has been fixed in a recent refactoring
