### ISSUE TITLE
After the command is localized, it cannot be searched by keywords.

### ISSUE THREAD

**Issue by yiliang114** [microsoft/vscode#191880]
ADD ISSUE DESCRIPTION HERE

Version: 1.81.1
Commit: 6c3e3dba23e8fadc360aed75ce363ba185c49794
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36
Embedder: vscode.dev

![bug3](https://github.com/microsoft/vscode/assets/11473889/68161483-efe2-42cc-adce-b77f5d434eae)

Steps:
1. Open vscode.dev or VS Code App
2. Switch to a language other than the default, for example, Simplified Chinese.
3. Search command by shortcut key, for example, search `toggle`, some matching commands will appear.
4. But I search the keyword directly (incomplete command keyword), nothing will be matched.

**Comment by yiliang114** [comment]
However, in the English environment, commands can be searched through keywords.
![bug4](https://github.com/microsoft/vscode/assets/11473889/3699712a-327d-42f0-bf2b-7c333a961842)

**Comment by TylerLeonhardt** [comment]
This is similar to https://github.com/microsoft/vscode/issues/157015 but easier to fix.

It isn't just scoped to Output.
![image](https://github.com/microsoft/vscode/assets/2644648/68e027f4-eda4-4e50-9ae4-d51c9fc0dd4c)

There are a lot of these... and it all comes back to this allowing `string` here:
https://github.com/microsoft/vscode/blob/79277e0b8f045483a49f8a6834d476410c0d3cba/src/vs/workbench/common/views.ts#L78

when I make that only accept `ILocalizedString` I get 47 compilation errors 😅 

So, to fix this... we just need to:
* Remove `string` as an option for `title` in `IViewContainerDescriptor`
* Fix all compilation errors which really just means replacing all `string` titles with `ILocalizedString` titles

**Comment by yiliang114** [comment]
> This is similar to #157015 but easier to fix.
> 
> It isn't just scoped to Output. ![image](https://user-images.githubusercontent.com/2644648/264791057-68e027f4-eda4-4e50-9ae4-d51c9fc0dd4c.png)
> 
> There are a lot of these... and it all comes back to this allowing `string` here:
> 
> https://github.com/microsoft/vscode/blob/79277e0b8f045483a49f8a6834d476410c0d3cba/src/vs/workbench/common/views.ts#L78
> 
> when I make that only accept `ILocalizedString` I get 47 compilation errors 😅
> 
> So, to fix this... we just need to:
> 
> * Remove `string` as an option for `title` in `IViewContainerDescriptor`
> * Fix all compilation errors which really just means replacing all `string` titles with `ILocalizedString` titles

@TylerLeonhardt I have already followed your suggested steps and have dealt with it.
