### ISSUE TITLE
VSCode Jupyter Notebook is not importing functions from .py file

### ISSUE THREAD

**Issue by saurav-thakur** [microsoft/vscode#191871]
Type: <b>Bug</b>

I am currently working on vscode jupyter notebook and on the same directory I have a .py file as presprocessing_function.py and when I try to import certain function it does not recognize it.

VS Code version: Code 1.81.1 (6c3e3dba23e8fadc360aed75ce363ba185c49794, 2023-08-09T22:22:42.175Z)
OS version: Windows_NT x64 10.0.22621
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 3500U with Radeon Vega Mobile Gfx   (8 x 2096)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|9.95GB (3.23GB free)|
|Process Argv|--crash-reporter-id 3e2709b4-74be-41dc-9ab2-6dfc4e1a495d|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (14)</summary>

</details><details>

</details>

When I import the function into ipynb file. Some functions imports while others don't.
The Screenshot is attached below.

The preprocessing function is attached below
![preprocessing](https://github.com/microsoft/vscode/assets/46792248/b7122ec1-0813-4239-905d-e3f9b2777ccf)

The ipynb file screenshot is attached below.
![ipynb file](https://github.com/microsoft/vscode/assets/46792248/c48faca2-3fd7-4782-a9aa-1fb6bf077d22)

**Comment by DonJayamanne** [comment]
If you make changes to the python for after you execute a cell, then you have to restart the kernel so that the changes are imported.

If that doesn't work, please let me know

Optionally check the following 
* https://ipython.readthedocs.io/en/stable/config/extensions/autoreload.html
* Orr the following sample
import my_module
# make changes to my_module
import imp
imp.reload(my_module)
