### ISSUE TITLE
Disable "Previous Change" and "Next Change" buttons in the diff view when there are no differences

### ISSUE THREAD

**Issue by kripper** [microsoft/vscode#191847]
Please disable the "Previous Change," "Next Change," and similar buttons in the diff view when there are no differences (both files are equal). This would be a swift way to ensure that no differences exist, especially when cheking between local and remote files. Such clarity can be crucial in certain situations.

On the right side, it's also possible to observe the differences on the "file map." However, at times, this map might be cluttered with additional markings, such as code warnings, which can lead to confusion.

Typically, I find myself clicking the "Next Change" button when I need to verify the presence of differences. If the file doesn't scroll, I can be confident that none exist. Yet, this workaround is unnecessary.
Furthermore, adhering to good UX practices involves displaying buttons as disabled when they lack any action.

![image](https://github.com/microsoft/vscode/assets/1479804/ecbe531c-c6ae-42c5-8e9e-57687ecb6209)

**Comment by kripper** [comment]
> When you are scrolled away from the single diff in a file, you can use these buttons to scroll back again to the diff. If there buttons would be disabled, this does not work anymore.

If there are no differences (both files are equal) the buttons are useless (there is no diff to scroll to) and should be disabled to follow good UI practices.

**Comment by hediet** [comment]
![Image](https://github.com/microsoft/vscode/assets/2931520/fdf7c7ff-21f0-40fb-8723-8acfc2cea887)
