### ISSUE TITLE
Show the selected header in the preview at the same view prot height as the header in the editor

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode#19182]
Testing #19085 

- VSCode Version: Insiders 
- OS Version: OSX

Steps to Reproduce:

1. Open a markdown file and its preview side by side in two editors
2. Select an header in the markdown file

Observed that the preview scrolls and show the corresponding header. But the position it shows is not same as where the selected header is in the main editor. If you start scrolling the preview then you can see a jump in the main editor. Instead showing the selected header at the same view position as in main editor will give better experience

**Comment by mjbvz** [comment]
Our api currently does not let us know an editor selection is in the viewport. We cannot align the editor selection position with the preview position in the editor -> preview case.

When going from the preview -> editor, we align everything to the top of the screen. This may result is some unexpected jumping around, but this is how the experience is designed using current apis.
