### ISSUE TITLE
Extensions viewlet leaks memory

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#191899]
* run OSS
* open extensions viewlet
* take heap snapshot
* search for "python" 10 times, note that it doesn't matter that no marketplace-url is defined
* take another heap snapshot
* 💧 ~1.5MB are leaked

It looks like the leak is happening via `SearchMarketplaceExtensionsView`, I see an instance per query I have typed

<img width="1296" alt="Screenshot 2023-08-31 at 14 25 13" src="https://github.com/microsoft/vscode/assets/1794099/6c75f7c7-9609-4b82-b072-21d17b2d7970">

I am pretty sure the leak is happening via this call: https://github.com/microsoft/vscode/blob/6e7ea55068066538fcb33d23c16ef0797fd25ea8/src/vs/workbench/browser/parts/views/viewPaneContainer.ts#L863

On each newly added pane two DND listeners are added. Those are tracked/registered but not for the respective pane but "globally" with the lifecycle of the container.

**Comment by jrieken** [comment]
I pretty confident that I have fixed this as part of fixing the debug session leakage, see https://github.com/microsoft/vscode/pull/191913 and https://github.com/microsoft/vscode/pull/191913/commits/7ce48dafb0ee42643e76b4d7504f84539ec097fd

**Comment by sandy081** [comment]
I also believe the change fixes the leak. Thanks.

**Comment by sandy081** [comment]
@jrieken Is this fixed with your change?

**Comment by jrieken** [comment]
Likely, but someone else should verify

**Comment by sandy081** [comment]
Verified that there are zero instances of `SearchMarketplaceExtensionsView`
