### ISSUE TITLE
Can't format C# code

### ISSUE THREAD

**Issue by darktutu** [Microsoft/vscode#1918]
version 0.10.6
![image 032](https://cloud.githubusercontent.com/assets/1868626/12229877/a00d59fa-b886-11e5-9dd1-e0fcc02caa02.png)

**Comment by isidorn** [comment]
Not sure if we support C# formating, joh?

**Comment by jrieken** [comment]
@darktutu What does the OmniSharp log read (press Cmd+L, L)?

**Comment by darktutu** [comment]
@jrieken  nothing in omnisharp log

**Comment by jrieken** [comment]
do you have a project.json file or a  set of csproj/sln files? otherwise it won't work

**Comment by FaicSilier** [comment]
Hello, I have kind of the same problem with formatting javascript: Nothing happens if I format it.

How can I add a project.json file or set a csproj/sln file so that formatting works. (as a suggestion: would be great if you wouldn't need to create files to format code)

**Comment by jrieken** [comment]
@FaicSilier JavaScript is independent of that. If you see issue with formatting JS please file a separate bug

**Comment by darktutu** [comment]
@jrieken  I open a solution. but  it didn't work。is vscode support c# format ?

**Comment by jrieken** [comment]
@darktutu What does the OmniSharp log read (press Cmd+L, L)? It should not be empty

**Comment by jrieken** [comment]
This issue was moved to OmniSharp/omnisharp-vscode#5

**Comment by deadlyfingers** [comment]
For others encountering the same issue in VSCode on a Mac with the "Format Document" command missing when editing C# script try adding a "project.json" file in the root project folder with a version tag worked as suggested by @jrieken 
```
{
  "version": "1.0.0"
}
```
