### ISSUE TITLE
Settings: cannot drag scrollbar in some cases

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#19189]
In some cases dragging the scrollbar on the left hand side of settings does not move it. It seems to happen when mouse is over a line that is collapsed.

**Comment by sandy081** [comment]
@bpasero I am not able to reproduce it.. Can you help in getting into this scenario ?

**Comment by bpasero** [comment]
@sandy081 ![kapture 2017-02-10 at 11 42 49](https://cloud.githubusercontent.com/assets/900690/22823908/13576946-ef86-11e6-9c5c-f3d052c03496.gif)

**Comment by sandy081** [comment]
Thanks @bpasero. Do you also have zoom level set to `1`?

**Comment by bpasero** [comment]
@sandy081 yes!
