### ISSUE TITLE
Cannot select a path outside the workspace to save the file

### ISSUE THREAD

**Issue by yiliang114** [microsoft/vscode#191877]
ADD ISSUE DESCRIPTION HERE

Version: 1.81.1
Commit: 6c3e3dba23e8fadc360aed75ce363ba185c49794
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36
Embedder: vscode.dev

![bug1](https://github.com/microsoft/vscode/assets/11473889/29f86a05-8305-4511-a1f1-3df582d21324)

Steps:
1. Open a repo on vscode.dev
2. Open a file in any directory
3. Double-click the blank space to create a new file and use the shortcut key to save it
4. You can find the path to save the file can directly click on the previous level

Although the path beyond the current workspace is not saved successfully, in theory, it should not be possible to choose such a path.

**Comment by yiliang114** [comment]
The code to determine whether you can continue to select the upper directory is here：

https://github.com/microsoft/vscode/blob/9e927a6111882ef550806e06efb82be9b1b55571/src/vs/workbench/services/dialogs/browser/simpleFileDialog.ts#L956

**Comment by yiliang114** [comment]
@alexr00 Is it possible to add an attribute to `ISaveDialogOptions` to indicate that paths outside the workspace cannot be selected?

**Comment by alexr00** [comment]
We now show an error in the simple file picker if you try to safe in a place that doesn't support it with Remote Repositories.
