### ISSUE TITLE
Editor flickers while double clicking a header in the preview 

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode#19186]
Testing #19085

![jan-24-2017 14-03-14](https://cloud.githubusercontent.com/assets/10746682/22248231/ed4d5bac-e23d-11e6-9392-51e3e29850f4.gif)

**Comment by mjbvz** [comment]
I'm having trouble reproducing this. Can you try out the latest builds and let me know if you still see this. 

Thanks
