### ISSUE TITLE
Java Default Launch configuration Not Working

### ISSUE THREAD

**Issue by milic-marko** [microsoft/vscode#191837]
Type: <b>Bug</b>

I am using the gradle dependency management tool with Spring Boot, however when I try to build and run application it does not use default gradle output dir which is "build", instead it uses "bin", and on top of that it is compiling all the code, tests and main. 

The Java Launch configuration should use Gradle default config to build and run the app.

VS Code version: Code 1.81.1 (6c3e3dba23e8fadc360aed75ce363ba185c49794, 2023-08-09T22:18:39.991Z)
OS version: Linux x64 6.4.12-zen1-1-zen
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 PRO 4650U with Radeon Graphics (12 x 1397)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|10, 3, 1|
|Memory (System)|38.55GB (32.23GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|gnome|
|XDG_CURRENT_DESKTOP|GNOME|
|XDG_SESSION_DESKTOP|gnome|
|XDG_SESSION_TYPE|wayland|
</details><details><summary>Extensions (28)</summary>

Extension|Author (truncated)|Version
---|---|---
swagger-viewer|Arj|3.1.2
path-intellisense|chr|2.8.4
EditorConfig|Edi|0.16.4
shell-format|fox|7.2.5
kotlin|fwc|0.2.31
copilot|Git|1.106.367
copilot-chat|Git|0.6.0
vscode-auto-open-markdown-preview|hnw|0.0.4
Kotlin|mat|1.7.1
vscode-docker|ms-|1.26.0
vscode-kubernetes-tools|ms-|1.3.13
sqltools|mtx|0.28.0
java|red|1.21.0
vscode-xml|red|0.26.1
vscode-yaml|red|1.14.0
sonarlint-vscode|Son|3.20.2
vscode-h2o|tet|0.2.11
shellcheck|tim|0.34.0
intellicode-api-usage-examples|Vis|0.2.8
vscodeintellicode|Vis|1.2.30
vscodeintellicode-completions|Vis|1.0.22
vscode-gradle|vsc|3.12.7
vscode-java-debug|vsc|0.54.0
vscode-java-dependency|vsc|0.23.1
vscode-java-pack|vsc|0.25.13
vscode-java-test|vsc|0.39.1
vscode-maven|vsc|0.42.0
gitblame|wad|10.5.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscoreces:30445986
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
vsccc:30803844
282f8724:30602487
f6dab269:30613381
a9j8j154:30646983
showlangstatbar:30737416
03d35959:30757346
pythonfmttext:30731395
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
gsofa:30804715
pythonnosmt12:30797651
pythonidxptcf:30805731
pythonnoceb:30805159
dsvsc013:30795093
dsvsc014:30804076
diffeditorv2:30821572

```

</details>

**Comment by roblourens** [comment]
Please file on the Java extension repo

**Comment by milic-marko** [comment]
Oh, apologies, will do.
