### ISSUE TITLE
Copy plain text to clipboard

### ISSUE THREAD

**Issue by AlanJacobsSandnet** [microsoft/vscode#191896]
Type: <b>Feature Request</b>

I am using VSCode in conjunction with a proprietary application and need to paste text back from a VSCode editor into a cell in the UI of the application. If I paste text from a language editor (for, example, C# or JavaScript), the line breaks are not pasted into my application but if I change the "language" to Plain Text in the VSCode editor, copy to the clipboard again and then paste into the cell in the application, the line breaks are pasted. 
I've looked into this in more detail and it seems to be related to the way the text in the clipboard is tagged. If I paste text into Word from a language editor, the syntax colouring is reproduced. Unfortunately my application does not have a Paste As Plain Text option, so I think it is seeing the text formatted for syntax colouring and not treating it correctly.
In fact I can work around the issue by installing a Clipboard Manager extension (for example, Ditto) and set up a hot key (Win+V) to paste as plain text.
**My question**: can I add a command to VSCode to implement a "**_copy as plain text_**" ability, which I could invoke in VSCode with a custom keyboard shortcut from any editor?
Is this a capability already built-in?

VS Code version: Code 1.81.1 (6c3e3dba23e8fadc360aed75ce363ba185c49794, 2023-08-09T22:22:42.175Z)
OS version: Windows_NT x64 10.0.22621
Modes:

**Comment by rebornix** [comment]
This can be disabled by setting `editor.copyWithSyntaxHighlighting` to false.
