### ISSUE TITLE
Multiple sessions (context) save/restore support.

### ISSUE THREAD

**Issue by deryagin** [Microsoft/vscode#19184]
It would be nice to add sessions to vscode. Because most of us need to work on several tasks/issues at the same time. Sessions will help us to remember and quickly switch/restore the context of tasks. Possible operations may consist of (by Ctrl+Shift+P):
1. `session save <name>` (default `<name>` -- current git branch)
2. `session load <name>` (default `<name>` -- current git branch, or may be `<last>` session)
3. `session drop <name>` (default `<name>` -- current git branch)
4. `session list [pattern]`

Possible information to remember and restore when session will be loaded could be:
1. Current opened directory (or directories, when it will be possible).
2. A list of opened files with their's cursor positions.
3. A list of recently used files.
4. Current git brunch.
5. Break points, may be?

Perhaps it makes sense to do sessions operations accessible from command line interface. I.e.:
1. `code -s load <name>` -- load session `<name>`
2. `code -s show <name>` -- show preserved session information
3. `code -s list [pattern]` -- list preserved sessions (possible matched to `pattern`)
4. `code -s drop <name>` -- drop session `<name>`
5. `code -s merge <name>` -- open session `<name>` within current vscode editor and not to close already opened files.

vscode version: 1.8.1

**Comment by mousetraps** [comment]
Nice idea! @waderyan was actually looking into this recently, but I can't seem to find the relevant issue.

**Comment by waderyan** [comment]
@deryagin thanks for opening this up. I did look into this feature recently and shared a recommendation with the team for how we could implement it in our tool. There is not an existing issue, although there is a lot of interest in issues that are adjacent. For example: https://github.com/Microsoft/vscode/issues/396

**Comment by Knightwisp** [comment]
I have been looking for [notepadplusplus-like session support](http://docs.notepad-plus-plus.org/index.php/Sessions_And_Projects) in vs code.

Very handy to keep all related files (regardless of directory location) as one session.
