### ISSUE TITLE
Double click in preview does not show the corresponding section at same position always

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode#19187]
Testing #19085 

Steps to Reproduce:

When doing double click in preview editor, it shows the corresponding section in the main editor sometimes on top and sometimes one third (approx.) height down from top.

**Comment by mjbvz** [comment]
Can you please provide an example document and where to click to reproduce this. I'm have trouble doing so

**Comment by sandy081** [comment]
I used the 1.8 release notes in vscode docs repository. And I clicked on `Configurable Activity Bar` section

**Comment by mjbvz** [comment]
Try with the latest build. I can't repo this but did fix a few issues yesterday that may have been causing this..
