### ISSUE TITLE
[serve-web] In-app Github sign-in link rotates ports and cannot be preset with --port, breaking SSH local forwarding

### ISSUE THREAD

**Issue by thekeith** [microsoft/vscode#191867]
Summary: The sign-in link for Github in VSCode running through serve-web rotates ports in the 54xxx range, breaking any pre-set port forwarding for users connecting via SSH. This occurs regardless of any port option set with --port (taken from my comment in #168492)

Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: Insiders 1.82.0
- OS Version: Mac OS 13.3

Steps to Reproduce:

1. Connect to the device hosting code via SSH, with local port forwarding for port 8000 enabled
2. On the remote device, launch serve-web with ```code-insiders serve-web```
3. Open a browser window and navigate to the URL given by serve-web
4. Turn on settings sync, showing a github sign-in URL. Note the port is different than the default, requiring you to reconnect and add a new forwarded port 

Expected behavior:

Setting the port with --port should (a) also determine the port used for sign-in, or (b) be a separate option so that SSH port forwarding does not require updating SSH config and reconnecting each time you need to sign in

**Comment by TylerLeonhardt** [comment]
This flow shouldn't actually happen in the remote case and instead the user should get the device code flow. Fixed this by disabling the local server flow in https://github.com/microsoft/vscode/pull/191930

**Comment by TylerLeonhardt** [comment]
Verification:

* `code-insiders serve-web`
* turn on Settings Sync using GitHub
* when you go through the auth flow, you should get the Device Code Flow first
