### ISSUE TITLE
Cursor should be on the selected section in main editor when double clicking in the preview

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode#19190]
Testing #19085 

![jan-24-2017 14-10-39](https://cloud.githubusercontent.com/assets/10746682/22248450/ef0f1b6e-e23e-11e6-808a-e2944eee7d1b.gif)

**Comment by mjbvz** [comment]
Thanks. Fixed with d0163a1

The new implementation Moves the cursor to the head of the line on double click. We can investigate more fine grained mapping new sprint
