### ISSUE TITLE
Clicking on move to top button in preview has inconsistent scrolling on the main editor page

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode#19196]
Testing #19085 

In the following video, I was just clicking on the blue button on the bottom. And the editor on the left scrolls some times

![jan-24-2017 14-22-12](https://cloud.githubusercontent.com/assets/10746682/22248794/942732e8-e240-11e6-9b09-17bcca317285.gif)

**Comment by mjbvz** [comment]
No easy way to prevent this in the general case. Our in-product release notes use a custom html element for that button:

```js
<a id="scroll-to-top" role="button" aria-label="scroll to top" onclick="scroll(0,0)"><span class="icon"></span></a>
<link rel="stylesheet" type="text/css" href="css/inproduct_releasenotes.css"/>
```

The onclick should capture the event instead of allowing it to continue bubbling up. I'll update the release notes to do this

**Comment by mjbvz** [comment]
Nevermind that last commend. I think we can handle this a bit better. 

I've added logic to not track double clicks on `<a>` elements in the markdown preview, so that double clicking on links cannot trigger a switch to the editor
