### ISSUE TITLE
Preview flickers while editing

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode#19198]
Testing #19085 

![jan-24-2017 14-28-58](https://cloud.githubusercontent.com/assets/10746682/22249011/86e29c84-e241-11e6-86e3-78e62b1718e2.gif)

**Comment by mjbvz** [comment]
This could be improved but does not look like a regression. I see the same flickering on 1.8

**Comment by mjbvz** [comment]
Fixed by #19394
