### ISSUE TITLE
Where would I start if I wanted to write some code that would sort the launch.json entries alphabetically?

### ISSUE THREAD

**Issue by vinli-mark** [microsoft/vscode#191914]
I have a pretty long launch.json file and I know there were some additions that will allow you to group the entries in the launch.json file and I use them, but I would like to have the list sorted automatically that way I don't have to scan the list to find what I am looking for. 

What code generates that list? I wouldn't mind taking a crack at adding an option for auto sorting

**Comment by roblourens** [comment]
Are you asking to sort the contents of the launch.json file itself, or just the displayed entries? If the first, you can use an extension for that.

**Comment by vinli-mark** [comment]
Whatever is easiest. I didn't think to look into extensions

**Comment by roblourens** [comment]
Yeah, I'm sure there are json sorting extensions or non-vscode-specific cli tools, this would be the right approach
