### ISSUE TITLE
Unable to switch sync accounts, VSCode always directly opens the Microsoft account login page

### ISSUE THREAD

**Issue by hellohejinyu** [microsoft/vscode#191948]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.81.1
- OS Version: 13.5.1 (22G90)

Steps to Reproduce:

1. 

https://github.com/microsoft/vscode/assets/8766034/5c710de1-b690-42bb-9ab1-4527e47040d3

**Comment by sandy081** [comment]
I am suspecting that you do not have multiple authentication providers. Can you please try the flow by turning off settings sync (F1 > Settings Sync: Turn off) and turn on again and record the flow and share?

**Comment by hellohejinyu** [comment]
> I am suspecting that you do not have multiple authentication providers. Can you please try the flow by turning off settings sync (F1 > Settings Sync: Turn off) and turn on again and record the flow and share?

Awesome, this solved my problem, thanks😊
