### ISSUE TITLE
[Accessibility] Consider removing "terminal.integrated.tabFocusMode"

### ISSUE THREAD

**Issue by jooyoungseo** [microsoft/vscode#191938]
Type: <b>Feature Request</b>

Now that tabindex is removed from the terminal buffer area, I was wondering if "terminal.integrated.tabFocusMode" would be still useful. If not, please consider removing this option to officially deprecate this.

VS Code version: Code - Insiders 1.82.0-insider (3cd6f481266dcbd2ca2fcff43b4465d747c78e2f, 2023-08-31T17:34:55.916Z)
OS version: Windows_NT x64 10.0.22621
Modes:

**Comment by meganrogge** [comment]
Verify that toggling tab moves focus applies to the workbench, terminal, and editor.
