### ISSUE TITLE
Remote-SSH connect to Host with non-22 port

### ISSUE THREAD

**Issue by BossaMelon** [microsoft/vscode#191984]
Type: <b>Feature Request</b>

Hello dear developer, 

I would like to know, whether there is a way to connect to ssh with other port than 22 in the "Remote-SSH connect to Host"  window? 
<img width="600" alt="image" src="https://github.com/microsoft/vscode/assets/38517713/bd315819-09af-4273-9d48-1135023ce32c">

For now I can use add ssh host first, then connect to it, but my workflow involves tools like slurm and will assign me different machine with random port, if every time I need to add a ssh host info to the .ssh/config, the config file will get quite messy. It would be better that I can choose a port in Remote-SSH connect to Host rather than only able to choose username and host.

Thanks a lot!
Best
Yuehao

VS Code version: Code 1.81.1 (6c3e3dba23e8fadc360aed75ce363ba185c49794, 2023-08-09T22:40:25.698Z)
OS version: Darwin arm64 22.5.0
Modes:
Connection to 'SSH: de' could not be established  Canceled
Remote OS version: Linux x64 5.4.247-162.350.amzn2.x86_64
Connection to 'ssh-remote+10.34.46.227' could not be established
Remote OS version: Linux x64 5.4.247-162.350.amzn2.x86_64

**Comment by roblourens** [comment]
You will need to use an ssh config for this
