### ISSUE TITLE
TypeScript doesn't react to referencesCodeLens config change

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#19195]
Testing #19088

1. Open the settings
2. Open a TypeScript file to the side
3. Change `typescript.referencesCodeLens.enabled` to `true`

The TypeScript file will not show the code lens. Only when switching to another file and switching back will the references come up.

**Comment by mjbvz** [comment]
I think this a limitation of the VSCode API. The TypeScript references code lens will return an empty set of code lens if it is not enable. Once it is enabled, it has no way to tell vscode to call `provideCodeLenses` again. Editing the document or switching documents calls `provideCodeLenses` again

**Comment by mjbvz** [comment]
Nevermind, I see an new `onDidChangeCodeLenses` event was added to the api to support this use case. #19343 updates the references code lens to use it
