### ISSUE TITLE
Quick search needs folder names

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#191994]
Searching for tsconfig target just now:

![Image](https://github.com/microsoft/vscode/assets/2193314/1df35d32-f6c3-4952-9f09-79d30813ceab)

I think we need the full path as detail to the right of the path (same color but not bold?)

**Comment by andreamah** [comment]
I actually put the folder names in the tooltips, but they don't appear for separators. I am considering putting them in the description if we adopt more complete-looking section separators. https://github.com/microsoft/vscode/issues/191681#issuecomment-1699911508

**Comment by andreamah** [comment]
<img width="657" alt="image" src="https://github.com/microsoft/vscode/assets/31675041/4d86dfd3-9306-4952-8fa7-418fa1d449c3">

This was added by Tyler this iteration 👍
