### ISSUE TITLE
Quick Chat layout issue on resize

### ISSUE THREAD

**Issue by rzhao271** [microsoft/vscode#191942]
On the latest Insiders on Windows

1. Open Quick chat.
2. Close it.
3. Zoom in or out of the editor.
4. Open Quick Chat again.
5. :bug: Layout issue

**Comment by TylerLeonhardt** [comment]
example layout issue:
![image](https://github.com/microsoft/vscode/assets/2644648/1baa5f83-8ab4-4aec-9312-c91630f19996)
