### ISSUE TITLE
Wiki: update Related Projects

### ISSUE THREAD

**Issue by rootsmusic** [microsoft/vscode#191935]
[Related Projects](https://github.com/microsoft/vscode-wiki/blob/main/Related-Projects.md) should be updated with repos like [vscode-python](https://github.com/microsoft/vscode-python/), [vscode-data-wrangler](https://github.com/microsoft/vscode-data-wrangler) and [vscode-jupyter](https://github.com/Microsoft/vscode-jupyter).

**Comment by joyceerhl** [comment]
https://github.com/microsoft/vscode-wiki/commit/c6dd1f2081e70987456e15b650b2d62e7684ba72
