### ISSUE TITLE
Disassembly memory references should be treated as opaque strings

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#191925]
Currently VS Code assumes the memoryReference in the context of disassembly is a decimal address, but this is a constraint not dictated by DAP. See discussion: https://github.com/microsoft/vscode-discussions/discussions/712

**Comment by rzhao271** [comment]
What are some verification steps for this issue?
I've attached a pic of what I'm seeing in case that verifies the issue immediately.
![Disassembly view showing some instructions](https://github.com/microsoft/vscode/assets/7199958/55fc4f54-5438-47b8-9749-a1a0f5159849)

**Comment by connor4312** [comment]
this actually dupes https://github.com/microsoft/vscode/issues/129655
