### ISSUE TITLE
Explore capturing heap snapshot in CI and analyzing potential memory leaks

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#191920]
Currently we are manually hunting down memory leaks through Dev Tools. For some areas/components (e.g., notebook), this even needs to be done repeatedly. It would be helpful if we can capture the memory snapshots in CI and write some queries against the snapshot to analyze if there is any potential leaks.

A typical manual memory leak analysis for notebook

* Setup
  * Open OSS
  * Open notebook document A
  * Open notebook document B
  * Close both notebook documents
* Open Dev Tools, take a heap snapshot
  * Search `NotebookTextModel` object, there should be none 
  * Search `NotebookCellTextModel` object, there should be none 
  * Search `NotebookEditor` object, there should not be more than one (the editor group still holds a reference to the last editor)

![Image](https://github.com/microsoft/vscode/assets/876920/01a4b78c-33d5-43b0-b37b-1b83bb0df84a)

cc @jrieken @connor4312 @Tyriar

**Comment by rebornix** [comment]
The dev tools also show how an object is leaked, we could analyze the dependencies tree and figure out who is the "culprit"

**Comment by deepak1556** [comment]
[process.takeHeapSnapshot](https://github.com/electron/electron/blob/main/docs/api/process.md#processtakeheapsnapshotfilepath) would be a good API for CI use case on desktop to capture from any non-sandboxed process embedding V8 without using external CDP calls. In the case of sandboxed render process, prefer [webContents.takeHeapSnapshot](https://github.com/electron/electron/blob/main/docs/api/web-contents.md#contentstakeheapsnapshotfilepath)

**Comment by SimonSiefke** [comment]
I find this topic super interesting as well! I have a prototype project https://github.com/SimonSiefke/vscode-memory-leak-finder that tries to find memory leaks by looking for leaking event listeners. 

https://github.com/microsoft/vscode/assets/23744935/b4da7ea2-5de0-4623-8ea4-634d99e5e420

In the screencast, the event listener count increases from 1175 to 1206 which indicates that there might be a memory leak when opening and closing a notebook editor.

The project is in the early phases and in the future I'm hoping to display more detailed output for the event listeners as well as making the tests less flaky.

(sorry if I'm interrupting the discussion. I'm hoping that perhaps this could be useful for you)
