### ISSUE TITLE
Debounce F4/shift F4

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#19199]
Testing #19094

1. Have many search results in the search viewlet
2. Select the first
3. Hold <kbd>Down Arrow</kbd> key

You'll notice that a file will open every 300ms or so, demonstrating the rate limiting.

This UI interaction should use debouncing instead of limiting the rate. We have a [few](https://github.com/Microsoft/vscode/blob/master/src/vs/base/common/event.ts#L308) [utils](https://github.com/Microsoft/vscode/blob/master/src/vs/base/common/async.ts#L246) for this.

**Comment by joaomoreno** [comment]
Additionally why are the arrow keys rate limiting, but <kbd>F4</kbd> and <kbd>Shift F4</kbd> are not? IMO they should all work the same way: debounced.

**Comment by roblourens** [comment]
I tried debouncing originally but thought it was even more annoying than rate limiting because typically with a debounce, there's a delay before the first one takes effect. I'll play around with this some more though since it doesn't look great as is. Good point on F4

**Comment by roblourens** [comment]
Fixed in #19307 but will also do this for F4

**Comment by joaomoreno** [comment]
Cool. 👍  Just finely tune the debouncing delay to fix the annoyance.

**Comment by roblourens** [comment]
Actually this probably won't happen for January. When using F4, the editor is focused. When you hold F4, we would want to see each next result being focused, like when holding the down arrow, but currently the focused result isn't highlighted in the search viewlet when it doesn't have focus. Only the selected result (which is open in the editor) is highlighted. So I'd have to change that. Will look at it for February.
