### ISSUE TITLE
Does package.json configuration properties pattern regex support unicode?

### ISSUE THREAD

**Issue by isc-bsaviano** [microsoft/vscode#191906]
I have a configuration property in my extension's package.json with the following definition:

```json
"objectscript.unitTest.autoload.folder": {
  "markdownDescription": "When running client-side test classes, automatically load the contents of sub-directories with this name. See the [%UnitTest /autoload qualifier documentation](https://docs.intersystems.com/irislatest/csp/documatic/%25CSP.Documatic.cls?LIBRARY=%25SYS&CLASSNAME=%25UnitTest.Manager#RunTest) for details.",
  "type": "string",
  "default": "_autoload",
  "scope": "resource",
  "pattern": "^[\\p{L}\\d_. -]*$"
}
```

That regex is a valid unicode regex that works in the node REPL, but it doesn't work properly in the VS Code settings editor:

<img width="474" alt="Screenshot 2023-08-31 at 9 11 30 AM" src="https://github.com/microsoft/vscode/assets/44776135/2df4e58b-29bd-41d7-a892-e520133abc02">

Are these patterns evaluated with the unicode flag on? If not, can that feature be added or enabled?

**Comment by rzhao271** [comment]
The Unicode flag isn't used at this time.
Code pointer https://github.com/microsoft/vscode/blob/0b4fd719e3dd53c436e8456985b2bcfb202ca002/src/vs/workbench/services/preferences/common/preferencesValidation.ts#L135

**Comment by isc-bsaviano** [comment]
@rzhao271 Is this something that is going to be picked up in an upcoming release?

**Comment by isc-bsaviano** [comment]
@rzhao271 Thanks for fixing this so quickly! It works for me on:

Version: 1.83.0-insider
Commit: 109e1f8d8afb754ed31317f79937a44e98d5063b
Date: 2023-09-25T10:44:46.038Z
Electron: 25.8.2
ElectronBuildId: 23977753
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Darwin arm64 22.6.0

**Comment by sandy081** [comment]
Marking this as verified based on author's comment
