### ISSUE TITLE
Terminal: interesting behaviour when setting terminal.integrated.scrollback to 10

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#19193]
Refs: https://github.com/Microsoft/vscode/issues/19071

* set `terminal.integrated.scrollback: 10`
* run command with lots of output
* resize the terminal

=>

![untitled](https://cloud.githubusercontent.com/assets/900690/22248737/5597a2e2-e240-11e6-9e44-2f41076a8c5c.gif)

**Comment by Tyriar** [comment]
Upstream issue filed: https://github.com/sourcelair/xterm.js/issues/506

**Comment by parisk** [comment]
This should be fixed via sourcelair/xterm.js#749.
