### ISSUE TITLE
Notebook shows up in search results while not in include files

### ISSUE THREAD

**Issue by rzhao271** [microsoft/vscode#191922]
On the latest VS Code Insiders on Windows:

1. Open the vscode repository.
2. Open a notebook such as the endgame notebook.
3. Search `s` in the find view with "files to include set" to `extensions/**/*.ts`.
4. :bug: Matches to the endgame notebook still show up even though it's not under `extensions/`.

Found while verifying #187056

**Comment by andreamah** [comment]
Seems that this repros on stable- I'll fix this in september.

**Comment by rzhao271** [comment]
Looks like I can still repro


![The include field should restrict the search to TypeScript files, but GitHub issue notebooks continue to show up](https://github.com/microsoft/vscode/assets/7199958/cccb200d-4aa2-426d-817a-300e9979bd9c)

**Comment by andreamah** [comment]
Yes, it still repros when the notebook is open.
