### ISSUE TITLE
Rename `scrollPreviewWithEditorSelection`?

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#19192]
Testing #19085

Changing that setting to `false` disables all features in #19085, not just the scrolling. Given that, shouldn't it be named something lighter and more encompassing such as:

- `markdown.preview.linked`
- `markdown.preview.tracked`
- etc.

**Comment by mjbvz** [comment]
This looks like a bug. Let me investigate why this one setting disables everything

**Comment by mjbvz** [comment]
Thanks @joaomoreno. This was indeed a bug. The settings are all supposed to operate more or less independently.  eba0fc9 and 042285d fixes a few cases where this was not the problem

Let me know if you still feel strongly about renaming the settings
