### ISSUE TITLE
Rename `typescript.referencesCodeLens.enabled`

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#19197]
Testing #19088

Having `.enabled` seems redundant. The editor setting is `editor.codeLens`. This one should be: `typescript.referencesCodeLens`.

**Comment by mjbvz** [comment]
@joaomoreno Thank you for the input.

The thinking here was to allow adding additional settings for the references code lens, such as a setting to disable references on private members or one to add references on all top scope variables. I feel that having `referencesCodeLens` as a namespace makes sense for this. These settings would be called something like: `typescript.referencesCodeLens.showPrivateMembers` or `typescript.referencesCodeLens.showAllTopLevelReferences`

Let me know if you have thoughts on better ways to implement the above.

Thanks
