### ISSUE TITLE
'node' is not recognized as an internal or external command, operable program or batch file

### ISSUE THREAD

**Issue by deadlyfeet001** [microsoft/vscode#191939]
Type: <b>Feature Request</b>

still have this error:   'node' is not recognized as an internal or external command,
operable program or batch file

VS Code version: Code 1.81.1 (6c3e3dba23e8fadc360aed75ce363ba185c49794, 2023-08-09T22:22:42.175Z)
OS version: Windows_NT x64 10.0.23531
Modes:

**Comment by roblourens** [comment]
Sounds like node is not on your path
