### ISSUE TITLE
Invoking choice from `Show CodeLens Commands For Current Line` may require multiple Enters or clicks

### ISSUE THREAD

**Issue by gjsjohnmurray** [microsoft/vscode#191908]
Type: <b>Bug</b>

1. Set `"typescript.referencesCodeLens.enabled": true`
2. Open a  .ts file.
3. Put cursor on a line that has an `N references` CodeLens above it.
4. Open Command Palette and run `Show CodeLens Commands For Current Line`.
5. Press Enter to try and run the selected (only) entry (N references).

:bug: nothing happens until you press Enter a second time (or more...).

Results of using a mouse-click to try and run the CodeLens from the quickpick is the same. First click does nothing, and a second click is required.

This also happens in 1.81.1 so it is not a 1.82 regression.

VS Code version: Code - Insiders 1.82.0-insider (e7756c8870ee1df7360e6624e220534174039b02, 2023-08-31T05:33:59.698Z)
OS version: Windows_NT x64 10.0.22621
Modes:

**Comment by jrieken** [comment]
I can reproduce. The code lens model is disposed because the focus lost/gain cycle retriggers its computation and then the picker restarts (to make sure a fresh item is selected)...

**Comment by andreamah** [comment]
Added `verified` tag, as this was author-verified
