### ISSUE TITLE
Previewing a Tunnel url in the Simple Browser doesn't work

### ISSUE THREAD

**Issue by TylerLeonhardt** [microsoft/vscode#191928]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 
- OS Version: 

Steps to Reproduce:

1. run a simple express app
2. forward port
3. open in Simple Browser

You get a blank screen:
![Image](https://github.com/microsoft/vscode/assets/2644648/ce2e1808-4b08-4c7d-80b0-85c061d483c2)

but in the browser it works.

I think this is because there is a screen that you need to click on to accept the port forwarding... and for whatever reason the Simple Browser doesn't like this.

We should see what's possible to allow the Simple Browser to work in this case, or remove that button for devtunnels Urls since we own that logic.

**Comment by gjsjohnmurray** [comment]
Could it be related to #185204?

**Comment by connor4312** [comment]
duplicates https://github.com/microsoft/vscode-remote-release/issues/8800#issuecomment-1669808991
