### ISSUE TITLE
Add support for font ligatures

### ISSUE THREAD

**Issue by klingtnet** [Microsoft/vscode#192]
[Fira Code](https://github.com/tonsky/FiraCode) and [others](https://github.com/i-tu/Hasklig) are monospaced fonts that use [ligatures](https://en.wikipedia.org/wiki/Typographic_ligature) to combine multi-character symbols, e.g. `->` will result in an arrow symbol `→`. This is quite nice and [atom](https://github.com/atom/atom) supports this font feature since `1.2.0`, so it should work with vscode, too.

**Comment by jordwalke** [comment]
:+1:

**Comment by TheInitializer** [comment]
+1

**Comment by coreh** [comment]
:+1: I would really like this feature.

**Comment by bgashler1** [comment]
I'm looking into this with the team and will keep you guys updated :).  Thanks for the idea!

**Comment by satya164** [comment]
+1

**Comment by clojj** [comment]
:+1:

**Comment by bgashler1** [comment]
## Good News
I got ligatures to work by changing my user settings in VS Code with `"editor.fontFamily": "Fira Code"` and then adding the simple CSS rule below
```
div.monaco-editor.vs-dark {    
text-rendering: optimizeLegibility;
}
```
## Temporary Bad News
There's a side-effect we need to work through.
![test](https://cloud.githubusercontent.com/assets/11839736/11825475/1070fe3a-a334-11e5-89e5-07ea190ef062.png)

The problem I’m getting is that when I use this rule I get a glitch when clicking at the end of a line.  Clicking at the end of a line past the last character normally would put the cursor after the last cursor on the line, but as you can see, it’s putting my cursor at the beginning of the line.  However, when I enter text, it is appearing at the end of the line as it should (except the cursor is not in the right spot).
  
Atom had a similar problem in September for a while, when they enabled ligatures.  Apparently ligatures can cause problems with character spacing, even though they are still multiple ASCII characters, they render differently and this can affect spacing.  Perhaps this anchor on the page is relevant. @alexandrudima could you help with this?
 
By the way, this is only a problem if you click past the last character of any line (as if it is making the cursor position undefined???).  Anywhere else it’s fine.

**Comment by clojj** [comment]
How can I add this CSS rule ?

**Comment by mattblagden** [comment]
With that CSS style, the editing cursor renders in an incorrect position when moved to the end of a line. This happens regardless of whether it was placed there with the mouse or the keyboard.

![broken cursor](http://i.imgur.com/MHFc0HL.gif)

I put up a hacky pull request with a workaround, but if you're like me, and want those sweet sweet ligatures right now, you can cram the fix into existing versions of VS Code.

For example, on OSX:

1. Close VS Code.

2. Enable ligature rendering by opening `/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.css` and adding the following to the end:

```
.monaco-editor {
        text-rendering: optimizeLegibility;
}
```

Now you have ligatures and a broken editing cursor.

3. Apply the workaround to the broken cursor position by opening `Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js` and changing:

```
u.setStart(h,n),u.setEnd(p,r);var f=u.getClientRects(),m=null;return f.length>0&&(m=this._createRawVisibleRangesFromClientRects(f,o,s,a)),m
```

to

```
u.setStart(h,n),u.setEnd(p,r);var f=u.getClientRects(),m=null;return f.length>0&&(m=this._createRawVisibleRangesFromClientRects(f,o,s,a)),(h === p && n === r && r === p.textContent.length) ? (m[0].left = Math.max(0, p.parentElement.getBoundingClientRect().right - a)) : 0,m
```

Of course, the exact names used in this change depend entirely on the minification, so you may have to adjust accordingly if you have a different version (this example is from the latest version of VS Code for OSX, as of the time of writing). You can refer to the pull request above to get a better idea of what the (minified) change is doing.

If all went well, you now have some lovely ligatures, with a functioning editing cursor.

![working cursor](http://i.imgur.com/1m6p4L8.gif)

**Comment by klingtnet** [comment]
```js
u.setStart(h,n),u.setEnd(p,r);var f=u.getClientRects(),m=null;return f.length>0&&(m=this._createRawVisibleRangesFromClientRects(f,o,s,a)),m
```
Does anybody have an idea where this line (above) is in the unminified source code?
All I can say is, that it's not in [`/src/vs/workbench/workbench.main.js`](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/workbench.main.js).

**Comment by mattblagden** [comment]
The line you pasted is the minified version of [the code here](https://github.com/Microsoft/vscode/blob/014193f5043999ab80579fbd763a3171e22638cf/src/vs/editor/browser/viewParts/lines/viewLine.ts#L350).

As mentioned in my earlier comment, the workaround is implemented in #1510. You can refer to #1510 to see the change in its un-minified form.

**Comment by clojj** [comment]
Will #1510 be compatible with the chromium version, which has fixed this ?
I mean, if Code will eventually update to the fixed chromium.....

**Comment by clojj** [comment]
What a great holiday present !!
![firacode-vscode](https://cloud.githubusercontent.com/assets/4367963/11927018/a4ea5e3c-a7c9-11e5-9bde-36a184320b0b.png)

Patch works as advertised here (Mac OSX, VSC 0.10.5)

**Comment by clojj** [comment]
BTW... I really don't want to bash Atom, it is a great editor.

But...
Opening the minified .js from this patch inside 'Visual Studio Code.app' and searching for that replacement + replacing it worked without a flaw in VSCode.

That same operation crashed Atom (V 1.3.2) unfortunately.
(had other crashes in Atom recently too, so it's not just a problem of minified js I guess)

**Comment by jstclair** [comment]
The way I did it without having to fix the editor itself was to edit `workbench.main.css` and add the `text-rendering: optimizeLegibility;` to a new selector: `token.keyword.operator` - if you use Code's Developer Tools, you can see that these are defined per-language/token type (for instance, the span surrounding `!=` in my Javascript file has the class `token comparison keyword operator js`).

This works, and avoids the broken line-selection in the editor, but there's a small tokenizing bug in JS: `!==` is not a single span, but rather 2:
`<span>!=</span><span>=</span>` 
and this prevents the ligature from matching.

**Comment by mattblagden** [comment]
@clojj Glad you're enjoying it :smile:. I just discovered these ligature fonts recently, and also had to have them, heh. I believe #1510 would continue to work with the newer Chromium as it does with the current version. It doesn't add an offset to correct the bad coordinate; it outright replaces it with a new value calculated via other means (the element client box). The code would be wasteful (and probably confusing, heh) with newer Chromium, but shouldn't behave differently.

@jstclair That's an interesting approach as well, trying to select a subset of elements that need the style but won't appear in locations that break the cursor. Unfortunately, only applying it to operators does still produce some odd behavior; if operators appear at the end of a line, the cursor still breaks. e.g. in the following code, moving the cursor to the right side of the `&&` makes it render in incorrect locations.

```
result = something &&
         somethingElse &&
         lastThing;
```

Additionally, applying it only to the operator class won't render ligatures in anything but operators; ligatures won't be displayed in other JS elements (comments, hexadecimal prefixes, etc.), nor will they appear in other languages (HTML, C#, etc.)

**Comment by bgashler1** [comment]
Just wanted to update everyone.  This feature will be supported soon in the main branch.  We are planning a temporary fix (based on the one above) while we wait for the fixed Chromium v48 to trickle down through an Electron Shell update soon.

**Comment by alexandrudima** [comment]
IMHO the challenge here is that the implementation of `text-rendering: optimizeLegibility` in Chromium is buggy. Here's some random excerpt I've found at [MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/text-rendering#Browser_compatibility) -- besides the client rects being wrong -- [Chromium 487028](https://code.google.com/p/chromium/issues/detail?id=487028):

> <p>[1] The implementation has known bugs on Windows and Linux, which can break <a href="http://crbug.com/114719" class="external external-icon">font substitition</a>, <a href="http://crbug.com/51973" class="external external-icon">small-caps</a>, <a href="http://crbug.com/55458" class="external external-icon">letter-spacing</a> or cause <a href="http://crbug.com/149548" class="external external-icon">text to overlap</a>.</p>

So while PR #1510 includes a workaround for [Chromium 487028](https://code.google.com/p/chromium/issues/detail?id=487028) that works for LTR text, I cannot deliver this change in its current form -- making `text-rendering: optimizeLegibility` the default for everybody. The unresolved Chromium issues above look like they would cause a lot of issues to CJK text, RTL text, and bi-di.

I am looking into enabling `text-rendering: optimizeLegibility` via a setting which will be off by default.

**Comment by alexandrudima** [comment]
Kudos to @mattblagden for his PR #1510 that I used as a great inspiration source. :heart:

**Comment by sanmai-NL** [comment]
@alexandrudima: You can use the `font-variant-ligatures: common-ligatures;` CSS property instead. It works for me in Chrome with the Hasklig font. See: http://thenewcode.com/547/Make-Your-Web-Pages-More-Legible-With-Ligatures-and-Kerning-Pairs

**Comment by alexandrudima** [comment]
@sanmai-NL We ended up with:
```css
.monaco-editor.enable-ligatures {
	-webkit-font-feature-settings: "liga" on, "calt" on;
	font-feature-settings: "liga" on, "calt" on;
}
```

Let's revisit these and use `font-variant-ligatures: common-ligatures` if any issues pop up.

**Comment by siegebell** [comment]
An alternative to ligatures is to use [prettify-symbols-mode](http://emacsredux.com/blog/2014/08/25/a-peek-at-emacs-24-dot-4-prettify-symbols-mode/), which [I've implemented as a plugin](https://github.com/siegebell/vsc-prettify-symbols-mode) for the insider's build of vscode (but note that it is of beta quality right now).

**Comment by PunchyRascal** [comment]
I will just leave this here - enable font ligatures in settings with:
```js
"editor.fontLigatures": true
```
(and also using appropriate font)

**Comment by HelloMihai** [comment]
@PunchyRascal is correct.  Here are all the settings together.
make sure your system has `FiraCode` font and add change the following settings

```
{
    "editor.fontFamily": "FiraCode-Retina",
    "editor.fontLigatures": true
}
```

FiraCode is an example.. there are other fonts that support Ligatures now

**Comment by ConsoleTVs** [comment]
It's diferent on the current version.

```javascript
{
    "editor.fontFamily": "Fira Code",
    "editor.fontSize": 18,
    "editor.fontLigatures": true
}
```
