### ISSUE TITLE
Search does not obey .gitignore if "files to include" field is populated

### ISSUE THREAD

**Issue by Diggsey** [microsoft/vscode#192045]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.81.1
- OS Version: Windows 10

Steps to Reproduce:

1. Add an entry to .gitignore file ignoring `foo/bar`
2. Perform a search, and specify `foo` in "files to include"

Expected:
I should only see results from `foo` excluding any results from `foo/bar`

Actual:
I see all results from `foo` including those from `foo/bar`

Reason:
VSCode passes the option `-g foo` to Ripgrep, which overrides any ignore options:
>     -g, --glob <GLOB>...
>            Include or exclude files and directories for searching that match the given
>            glob. This always overrides any other ignore logic.

This has been reported previously here: https://github.com/microsoft/vscode/issues/149349 but the issue was closed due to lack of activity.

cc @BurntSushi

**Comment by andreamah** [comment]
As mentioned in your comment, we would need to change upstream ignore logic to best address this. You can file a feature request there, but there are no immediate plans to try to do this only on the vscode side.
