### ISSUE TITLE
Using mouse for workbench.action.navigateBack results in browser back navigation

### ISSUE THREAD

**Issue by CoenraadS** [microsoft/vscode#192046]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:  `Web Version`
Version: 1.81.1
Commit: 6c3e3dba23e8fadc360aed75ce363ba185c49794
Date: 2023-08-09T22:27:10.293Z (3 wks ago)
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/117.0

- OS Version: Firefox 117.0 on Windows 10

Steps to Reproduce:

1. Go to Github, open browser code editor using `.` keys
2. Navigate around a little bit
3. Press 'back' button on the mouse (mouse button 3 I think)
4. Browser refreshes the page instead of navigation in file

In regular VSCode mouse 3 & 4 are bound to navigation, and it would be nice if it worked the same in the brower (or some popup first time button is clicked asking for preferred behaviour)

**Comment by bpasero** [comment]
We cannot override browser behaviour, so its up to browsers to allow us to do it.

We install a mouse listener here:

https://github.com/microsoft/vscode/blob/f1d871dbf12839d14720003226752b580a71d97c/src/vs/workbench/services/history/browser/historyService.ts#L127-L140

It may only work in fullscreen or PWA mode.
