### ISSUE TITLE
Stop doesn't kill debugged `restart` app

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#19203]
Testing #19040

1. Create Nodemon debug sample
2. <kbd>F5</kbd>
3. Hit stop

The terminal will read 

```
[nodemon] app crashed - waiting for file changes before starting...
```

Which indicates nodemon is still running, when it shouldn't.

The problem aggravates once the user presses `F5` again: nothing happens because some input is sent to the Terminal, but it's nodemon and not the shell that handles it. To get out of this state, the user must go to the terminal and <kbd>Ctrl C</kbd>.

Also, in that stopped state, a change in the JavaScript file will restart the server, since nodemon is still running.

![image](https://cloud.githubusercontent.com/assets/22350/22249544/bd078dd6-e243-11e6-9b58-27730299e4fb.png)

**Comment by weinand** [comment]
@joaomoreno VS Code does not try to control (terminate) 'nodemon' because its lifecycle is much longer than that of the debuggee. So pressing the Terminate button only terminates the debuggee but leaves nodemon alone.

This issue is documented here:  https://code.visualstudio.com/docs/editor/node-debugging#_attaching-to-nodejs:

> Tip: Pressing the Stop button stops the debug session and disconnects from Node.js, but nodemon (and Node.js) will continue to run. To stop nodemon, you will have to kill it from the command line.

**Comment by weinand** [comment]
IMO the [doc](https://code.visualstudio.com/docs/editor/node-debugging#_attaching-to-nodejs) explains this case sufficiently.

We cannot improve the implementation (and kill nodemon) because we do not know the process ID of nodemon since it was started from an integrated terminal.
