### ISSUE TITLE
Support Markdown in Intellisense documentation

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#1920]
![image](https://cloud.githubusercontent.com/assets/22350/12230771/d60ff67c-b852-11e5-8f3d-dde5d56a3d63.png)

**Comment by joaomoreno** [comment]
Related to #2330

**Comment by anatsegev** [comment]
It would be great to have full markdown support in the intellisense documentation!
:+1:

**Comment by simonvizzini** [comment]
Just wanted to say that it would be really awesome to have Markdown in Intellisense completion items. Hover tooltips already support markdown. Are there any technical difficulties that prevent implementing this for completion items? If not then I might take a stab at it this weekend if I have enough time.

**Comment by mjbvz** [comment]
Markdown intellisense is now enabled for JS/TS:

<img width="907" alt="screen shot 2017-09-21 at 9 33 22 pm" src="https://user-images.githubusercontent.com/12821956/30729461-935ff5b6-9f14-11e7-8554-415297a1af4b.png">

This uses the new `MarkdownString` type. Other language/extensions will have to onboard to `MarkdownString` to support this
