### ISSUE TITLE
Allow the use of environmental variables for setting port in launch.json for Node debugging

### ISSUE THREAD

**Issue by RobertBarachini** [microsoft/vscode#192014]
When trying to debug multiple (Node + Docker) services at the same time, I've started using environment variables for a more flexible setup when creating a complete dev environment which is not bound to a hard-coded config (example: hostname+port, as defined in launch.json).

Similar to [https://github.com/microsoft/vscode-python/issues/18841](url) and [https://github.com/microsoft/vscode-java-debug/issues/962](url) I'd like to use environment variables to set "port" and "hostname". Using environment variables to set different values within the launch.json configuration would be extremely useful for creating dynamic configs for developers on the team (this would allow us to change some parts of our dev environment without having to change tracked code - in this case launch.json; the same variable is also used within docker-compose.yml when defining a forwarded debug port) - even a way to turn off (or override) validation for types within launch.json (in general, not just for this Node configuration) would help a lot.

Example configuration:
```json
{
	"version": "0.2.0",
	"configurations": [
		{
			"name": "Attach to Docker port",
			"type": "node",
			"request": "attach",
			// "port": 9230,
			"port": "${env:PORT_SOME_SERVICE_DEBUG}",
			//"address": "localhost"
			"address": "${env:ADDRESS_SOME_SERVICE}",
			"localRoot": "${workspaceFolder}",
			"remoteRoot": "/usr/src/app",
			"restart": true,
			"sourceMaps": true,
			"skipFiles": [
				"<node_internals>/**"
			]
		}
	]
}
```
gives the following validation error: `Incorrect type. Expected "number".` even though the evaluated variable is a number.

Allowing the use of environmental variables (or even allowing numbers as string) for setting port would help a lot.

**Comment by roblourens** [comment]
I assume that the environment variable is resolved, but js-debug could parse a number from a string?

**Comment by RobertBarachini** [comment]
The message `Incorrect type. Expected "number".` comes up under "Warnings" in "PROBLEMS" panel (and is underlined in the editor accordingly). Not sure if the variable is being evaluated for the "port" key at all (or how it works under the hood), however it can be resolved under other references which support the "env" syntax. End result is debugger not being attached to the running Docker process - I assumed it automatically reverts to the default port number (9229), however the little debug controls window still pops up without actually being attached to anything.

**Comment by HelmerBarcos** [comment]
This is still a bug

**Comment by roblourens** [comment]
This is the case it's supposed to handle, right? Getting this warning but I see you updated the schema

<img width="423" alt="image" src="https://github.com/microsoft/vscode/assets/323878/33c743fc-0592-4f00-b24d-2a35d7b9b523">

**Comment by roblourens** [comment]
Oh I think I need to not just have nightly installed but also disable the builtin one. Now I see the right thing.

I do that then from time to time I end up reenabling the stable one for whatever reason
