### ISSUE TITLE
Invalid value and behavior of the terminal.external.windowsExec parameter when switching profiles

### ISSUE THREAD

**Issue by konstantinovaleksej** [microsoft/vscode#192033]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.81.1
- OS Version: Windows 10 Pro
- Extensions: PowerShell v2023.6.0 from Microsoft

Steps to Reproduce:

1. Set in **Default profile** `terminal.external.windowsExec` to `wt.exe` (`settings.json`: `"terminal.external.windowsExec": "wt.exe"`);
2. Create a **New profile** and uncheck **Settings** (then: _Using Default Profile_);
3. Restart Visual Studio Code with **New profile**;
4. Go to File > Preferences > Settings and search parameter `terminal.external.windowsExec`;
5. Its value will be: `C:\WINDOWS\System32\cmd.exe`.

P.S. First run - `wt.exe`. All other - `cmd.exe`

**Comment by sandy081** [comment]
Can you please try our latest release 1.82.1 and see if the problem still exists?

**Comment by konstantinovaleksej** [comment]
I have tested the latest version (1.82.2) and everything is fine. The error has been fixed!
