### ISSUE TITLE
Build failed in compilation

### ISSUE THREAD

**Issue by justschen** [microsoft/vscode#192008]
Build: https://dev.azure.com/monacotools/a6d41577-0fa3-498e-af22-257312ff0545/_build/results?buildId=230205
Changes: https://github.com/Microsoft/vscode/compare/4f424db...37390a8

```
src/vs/workbench/browser/parts/editor/editorPart.ts(528,7): error TS2663: Cannot find name 'options'. Did you mean the instance member 'this.options'?
```
I see its commented out now, but everything is still red so just making an issue just in case.

https://github.com/microsoft/vscode/blob/47649b9c26f598e257b99bd8983bc9e2cb8dd534/src/vs/workbench/browser/parts/editor/editorPart.ts#L528

edit: ref https://github.com/microsoft/vscode/pull/192004 https://github.com/microsoft/vscode/commit/812643de4b3679950a4e92bb19f3f2bb9c08bab4. thanks @jrieken

**Comment by bpasero** [comment]
Thanks. This is because our PRs just merge wild-wild-west style and not in order.
