### ISSUE TITLE
Can't login to vscode using microsoft account

### ISSUE THREAD

**Issue by raceychan** [microsoft/vscode#192089]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.81.1
- OS Version: windows 11

BUG:
as the title suggests, i can't find anyway to login using microsoft account,
![image](https://github.com/microsoft/vscode/assets/75417963/d45fbde7-5fac-4185-8f10-743a04422ee4)
everytime when i log out and click "sign in to sync settings", the chrome browser to pop up a github authentification page.

Steps to Reproduce:
1. don't know how to reproduce
2.

**Comment by sandy081** [comment]
Please Turn off Settings Sync using command - F1 > Settings Sync: Turn off - and retry again
