### ISSUE TITLE
vscode.DebugSession.customRequest modifies paths making them incorrect

### ISSUE THREAD

**Issue by tooltitude-support** [microsoft/vscode#192063]
Does this issue occur when all extensions are disabled?: No

- VS Code Version: 1.81.1 
- OS Version: OSX 13.5.1 / Ubuntu Linux 22.04

Steps to Reproduce:

1.  Create an extension
2. Launch from OSX remote ssh session with Ubuntu host
3.  Invoke vscode.DebugSession.customRequest involving path, for example SetBreakpoint, from the extension
4. Observe that the paths there are broken, i.e. vscode-local: is prepended to each of them, and as a result, nothing works

**Comment by roblourens** [comment]
Is it possible that you sent a URI instead of a string?

Please share some code to repro the issue, if this still happens

**Comment by tooltitude-support** [comment]
@roblourens It was pretty long time ago, so I don't have a repro :( I managed to do what I wanted somehow.
