### ISSUE TITLE
Hide exit code output in terminal

### ISSUE THREAD

**Issue by rainlizard** [microsoft/vscode#192037]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.81.1
- OS Version: Windows 10

Steps to Reproduce:

1. In tasks.json use `exit 1`
2. Observe that it floods your terminal and there's no way to stop it from doing so.

`"terminal.integrated.showExitAlert": false` doesn't stop it from appearing, I want to say that this is a bug, or perhaps it was overlooked. I'm not sure.

I created an error message for others to see, but it gets drowned out by VSCode's output. This is bad because the message can be missed. How do I hide VSCode's output?
![Untitled](https://github.com/microsoft/vscode/assets/15337628/753ec4e1-cbf6-4dd0-b603-f68ff650d691)

Another way to look at this issue is:
```
"presentation": {
    "echo": false,
}
```
Since I'm using this "presentation" setting I care about what it looks like and "echo" means I don't want my code spat back at me. So you could say that the bug lies here, echo:false should prevent exit 1 from spamming the terminal.

**Comment by meganrogge** [comment]
This is by design as we definitely want to show a user error output. @Tyriar lmk if i'm wrong.

**Comment by Tyriar** [comment]
Yes it's by design imo. This is a similar problem to https://github.com/microsoft/vscode/issues/187853, but for this you could just move the command into a script.
