### ISSUE TITLE
Is moved code range correct?

### ISSUE THREAD

**Issue by Igorgro** [microsoft/vscode#192019]
@hediet not sure if it a bug report or question, but I notcied that moved lines range is not correct:

![image](https://github.com/microsoft/vscode/assets/22894169/42b9b243-0b4c-4158-a941-b29ced5d18c8)

why it is written that lines are moved from 16-21? Shouldn't they be marked as "moved from 16-20"? The same question is about "moved to".

**Comment by hediet** [comment]
Verification steps:

Notice that the line numbers are correct [here](https://microsoft.github.io/monaco-editor/playground.html?source=v0.42.0-dev-20230911#XQAAAAIcZgAAAAAAAABBqQkHQ5NjdMeMm-jY7SIQ9S7DNlzs5W-mwj0fe1ZCDRFc9ws9XQE0SJE1jc2VKxhaLFIw9vEWdz-byeCFNuM1_tvkzrqWV8uiNY5Zk5mcQbvzm7H2CWGlqS-HtwsMRGPBK2qtHBXISCKyWdmWDo4f_D-LKC3uhee2ZxcqcB5MkD5moWlZcGQQWqTjmeKV8-IVx6eK6BmBfwufGyTQtm9HgzSWpX8Ej5M1SXX7n40Wsf_4N8arTXVlIucKRzLqnNIFnZeyagC4nZGcQD-KpeHXt9IMv8vcFhZKCkciVtekYiphUkmQoMOZaABa0otJW23zyvhlC5xHXuleR8ryJV7hVMw82E43UC3XpYyvj4rvD5C0RIvplCLHVlv0Rtj4rb_IEiYYEqR-pq7MMpDug7EP45AEpyhc_CoEu3xxwcbXcEroNqYhUaPwP_qivU0ch1dCpM-Dsej8SeObHawsIRYbk5DCdqsMDtyBd6V8RD37L1496-Riu0Kw4BgP9i5E6Yu9mwXH6HEoonEwNZ_r7OIKXNqh7MU5zOv5ZP4gf-KT97mA0WWZ9JAx5BySyTmk-ogI3rWvvIF1vPn4zyDUt6gh3k_SHdHSet65lGsVb98VTyPA_tuIKK-8bZLEy0XbTLUVX_2-5YFwf83ApxfKYyxezkSpfBYiKprL7GM7JyAdZYt0lfRb4B6uGb_g3Jq80wTSttUaColYpjYKM_ihL0qNY9Hrlor76luUGppD8gpG94V6Dtg-LniOk2phtnsWrokhsFjo0h48MlEChAd4VJNnm2wkBNpHmZ3LOs9pey6daF1KtvvKDBVUjt7clGBMqcSr8NeUoMYv6hgVkQqoCsRzHAfWKL-iIUXREQL8N9lnovbHUOfxvP3CiAHfXfUa548yALtPUvRgjpP3CooNh1rci_IUHnrdJzLfP4lXEZ3WrDgzXacwStcKULOJL8rZqwULJWJgWyx34uq_OCCiawq33HsFQeotT8omcuYfcV4mNQqKGnXb7xEPqEBmE-6oAxdkUQkWMrADPboNEtNgZqd8dlJugIZI5gCAciyE5QGVKUqc8QAuB2jNeyuSg0XXgsEXQ-xN0KpmAIUVPWpn8Gsj_le3hv-Kngf2IP4Rd636HXoS26BRIyICcsdPgYRqdd9BwElPooL3FSy50RABNVMnMKP6jXIEJCBRNNfenNZbVGYrGkXmaVWkNOgFPFXMI6podXx_P6VO1sWKTrwnWdNKeKkN8cMDchIF4Bi2DwzdZiM1fJGFvP2eeq636tQUr_8BNmVdbcBA6hITwPtjjkWWXUIQLETE7oDBuRIjyNsv3VME8ucdQTjkqdQNQm8MaT4c6Ep9t6xRopinQ9uZcyoRUGk8pk-mEeIQOoUPs46623AgpOREL1dWlsqdMPlFRuI3uUokzkKGfYB_uNo-1GjuHp74MffFFsilS7FZGB8ccj6dmPnWuc3zu1EgolaDxa3_CJkIcXamQ58uoHaqd3_Zd09mYeltrF362B1uZvcTRWVCbYEus6wUvgKhXc-KjCwDHhtov764uD1GiNY-dhoeoWboL7InGpqlPAxML8orNbywggsf_iXmiowSV5wbxv5S72maZhML89NBlH9ZpdTGVgZvWXfDpp9PAeWFPI05hDdiOUfZ-TdHeR9z-y1Pt5KLCR7sRNFYhNkJy6aKEtAnWcJxyMKJ8ZJe4nuf3jKClJaw-s6XH_s-x0i3a24AYvfY0VLCwA0enIc2eljln1WLyiBHHCgXqqCVoUjLez_-MueV-9SXqdu5cESxvh8TzORMRwSBqIvIg2EooRiG7VD2biibLWjnofdYUm1lGwSpCQOn3mm9t13iUep5zTD8A0qaqPcLMYyq8AqYW6VkN_XtTKnRyHCmX2mXmpN9RXmmdpnMsAizQDEblLUMw4DYTyU46CdPS8o7r1z7LSnPil9e6Dz-KRUf7tjkUlYQ4XFCSu25Xh6RikM8nUrNXd9GgjgPTsGhuhI-CnxSGeBTqPyuXlDn4INPr7chV1r7Ffusixc52IdHOJXcOJqizdL-VoFPP9IaFVrmEr5Lq1S6Fy8YQL3XPuk2Xr3PD_IwHm_4sa0dI8mrD7DFz_jXmWqJEw_cuwcUDq03kUx9LZ9cTJ6Z9TD9ySlwWsDhKdbnnyDQqcFnTOHfl91BL09g65nIZMwC2x_WTLaiDCVL_f9ID49TQ7ElAimF9g61M4k7nHLysSTdSS56KbcjH_mIxJab4BVhaFYyuWQdCA_qYS-ILR0Ppkpz7gE-ev7R2-Yx6IwedvP2ljM2yDT-juqBZYahq14m0Bb23cclNE_j2Ux-QmcHnk7DPL7rU1_Y-PCex_FRJH-B2CAWp_GSvMSC0i178FRb-vfAsf9YnrIf68NvIDsSfz99vHJfwOsczAlXVoLQqPdBzBRj2y6Y6lubkPphaBZuO4ERsX24oTmQggdy18wdcAecgiJuHzeYhXAapLMxVqyAMgUJUabE2uIp8z0JikBFyUGzr4RBk-uynOO9McjbiFlGbYHGRkjaxIWqo1UNbl_xN4J8mdvytaZofS2L1fgooUWdHFV4S8rLq_6HlFgCmS_IR-pL03ZsbQ2DUx9bJnrrdZfel-W4e7HUAH-Zh4J-aRREeclks5McyWcSXdPG9HcEoiLMf3BgmLrpmpXcfOV06c-m6grzRB_bZjrrlJgExXs0RQf4Xj8u_y-V-7IjuVvqkwagTXdd2Qsgkkm93A6aP3mDe6scv5JSzCpREgrBeQOyCzk1lm0dzIMpC5tytI4gaFoEWX4Mvro--aC6haQ5uQCTXY-Iw60XA6UT2DgQ-GNUZJPLoX3fu_1EdbuWx17LItl8AG5nh8HEugEqe8pmW4GC2XA4DZdZCvXOs-Yh__BNvxFJRycF7x_rNnuzoAOguiw8ICEark46GLCjPFDKxspW1FG9FlggQ4BSZtmqfvjtzH89e73jfWhZzAQu7KLgv3sBopjuX9Cs6zH9V16mS5VIlHuobbDUlvWP29DXwuxNJhOl1d7Obf7iciY9QI7DusZhJ5vK0U0wek5JkFEFPolqIYS9iV8Fayk4aOSNLelsDeo_iWPT7ftCVF-IjD2lh5UpCOfiKcATsKQC0GIar7ZeBOulmnAZ8U6eaUxMIEcPuuFpbNmAHck0CBsX4E2YJxP7caN19rgXjd6dtc-2VjBEgOa81_Dc66Hxg3W-t-ToBp_Lbo1Kv76M3skR5CaWcyQP9H6PUbePJtpTNc-XNkrE_mp9Gf9YUsCVm0ALuWdrFxgF8OLQZeNyvnvUXTwczkIm1u6fIIDQcysywux4s2soTyFKYRks0_hFY1R8_TrUHHXyrC3fRBvUu1ahnI95a9gJyT2ojywVH2csAHo5YhcsD7xlj8f09gXSY4nHLJyRVnSO6rzDMHp4cwwzATRf0wqiABxgrQ7j4OYB7EDWsLLma5_5jTsxitH06pE5Y7gWFxBvrToEoFnBkURJq5bEcWKmGGC-ewXMKrQYsIwva3bPjuZOdTMqt2E7IOk1JpKNdqrPYTT8e7n8ohFp1HYb__QiYtRopR2J6ZvANp3mzzOfsYs04A_EOo5KCN8Q-BnHO3z889wkyGkszkk7gZ2ad5ARrkV4wlUTfrvTir6qlqRUD09aNPoGaRhc3uel7zZswzRnbkiF9cliTA7kSoCEO7nXk4nAcCp4vjPFLm2-C4LT0ZjB7qO2zlqDoPUXTj4kQl_JwUvt5AknJZHtd-amXg2LQTMpGRuIHPJu9T6IoD1Z7SIpixshHG4_c8-cQ4QhOvIQykT1dgdd4naPuc1MdGGPU5l_kiLWnIziLXSxbI2VtkIqd3Jix-GUsGSIixxDIXbtfcAiVu4n-kBkQU7pplC4oeaFStz1fX0JdPGLIE10tNLBmO3j0JGkP9FflrTLUQe-ZP9GqRRm6v_2DuH5x9HMOEcHQQj41PRFBgj4wd_s33Y1RqtiSeFtObLIVprfV3zmN7QNQV6yCV2gYQ5BP3V-OAEwP2XvpdXUTLR9M01fLDEUntPRvyaRjqz7E9P8YRrigI7yCvo45TyWqK204_s8UZ_nqc3YBnMdv39Qb38DEdrn_zqsjIRHzDLw5TN4DsEqyKTc_CTaoLUi4nckO7tlkVVhn7-pC1myroQ8-ovTUBEULfbikjIAJX9-8WcMqaW0L3e-M2qPQXcV4C88_k7U0fVLXMbQ5eMrdy1M1MCkdM2rQfeARI7sTNrFiLbThsYdWsktmYIWyG4i7cEzqUPcdXgM5N6rhioMjR8oF37k-_QZWSal9tP_5y7If7Lhn6coeSYV4IyRrZa_GE6trAhGyLMHjA0cdQp2AmsLstS7W2aQOdNhxr91zgoSTXOX7jThvPtpuIcC2qEtMDZVnLmte5_mZd0F-4Q3dt9i9JNh0A0xHi9Wc7JxjcD1GMNxkQVMHdA3-IyZbw-bAg2pWumlwn4soayvaQWLvIEKrZXoC31Qbsdz2y-u80CzOrh6xP46GNzNxPWDpOpU2noh2zg5DNHyKzk4QZ6WG4_-vyIugrbE0YY48n99vb8B7HvOWeB6RRIet4l4IeZwC9aHO6OsG7ssrulCkcce0wRNgF-6zgExgrvYz73J7MnbUT6hJisFEjKroubmWtqVcNwJa1zDKJo0EPR3SBoq2bksJqK6XcdgEQ-06nFh87BQHrNpqZ-KE0pAqRBK-4MP-hAKHqsC6NizP6fXi3zwLrIMxrhcrozf0NoWuV6LoBUIE5_IOj2i2XDGsPdNM5KoYBIVf5Kxlqh_1qN9Md05Edn-gZ13bzCs9nNzuKQXtho0NaboaM3re6ww95NVSagF9RnZzWRgGUCMvS1FAWotEJzioywT0QyAx3zUJp10FL-_l657KbEnx_M6Buds4_uvdmToDzFW8Pk2FfoE3LIWNifVmuO8HjAm1m0xtJjAn3BbobsmY8a8eNxfkVFTe9XF6KFZr-7shFNrYlyKi7dcuRhPZnWsw9BaJ2u9g5FnFflWjFj7gSBBQOEc0XAv8kUxcuWjQFm5pfKF993rjcvfmaj-3wB6iGI1sbAs-ksvP6g5c5F4YacSh9mqiYwXzq6O8dGQOW1XXudoU2m37JgwiewYUG7-oJcaMsiI0j0TfMUUQNRu6Q1zzCkGvY8Tt7pYk5HqZ5o3uLoQ1rOcVpx02ceyVo516LvPhQfGDYG1_l_9dG2BZhGU8affoQT5J1sI8pa0n1QYTttY_Ih20VccdLRvZe6kG2sxUEwDAJo6z9fWTxQQpxq22vfoxBULL04hVISmmu_AY9Y3fBJSmlhhBC9lV7Yso5w_6oIdq99aRfM__1Wfuc_149StFf3QblVy5eM-XtQO0UIP2VrQHtmhqXPjnDzzFmuDx1d4O5lWbvRkrECfaS7jU1QEYKfdfjARKEP-d9wz) (click on compare with latest-dev).
