### ISSUE TITLE
Markdown files doesn't show as expected

### ISSUE THREAD

**Issue by ankr2808** [microsoft/vscode#192022]
Type: <b>Feature Request</b>

I'm testing IntelliJ after using VS Code for a year and I've noticed that md-files display more like I expect in IntelliJ. That's a pitty. Both are not opimal though since marked lists are not very visible i IntelliJ and absent in VS code.

https://www.markdownguide.org/cheat-sheet/

Example
- [x] Write the press release
- [ ] Update the website
- [ ] Contact the media

Definition lists
: definition

VS Code version: Code 1.81.1 (6c3e3dba23e8fadc360aed75ce363ba185c49794, 2023-08-09T22:22:42.175Z)
OS version: Windows_NT x64 10.0.22621
Modes:

**Comment by gjsjohnmurray** [comment]
Does https://github.com/microsoft/vscode/issues/74540#issuecomment-497057053 help you?

**Comment by ankr2808** [comment]
Just what I needed. Thanks!
(But do I need a plug in for every feature in the Markdown?)

**Comment by mjbvz** [comment]
> But do I need a plug in for every feature in the Markdown?

If it's not a standard part of markdown, yes
