### ISSUE TITLE
Process explorer not show

### ISSUE THREAD

**Issue by npv2k1** [microsoft/vscode#192064]
Type: <b>Bug</b>

1. Go help
2. Select Open Process Explorer
3. can't select windowsto show Open Process Explorer

VS Code version: Code 1.81.1 (6c3e3dba23e8fadc360aed75ce363ba185c49794, 2023-08-09T22:22:42.175Z)
OS version: Windows_NT x64 10.0.22621
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|23.80GB (9.15GB free)|
|Process Argv|--crash-reporter-id e8436cd7-b6ac-43b0-8f60-eef1dd366ae6|
|Screen Reader|no|
|VM|29%|
</details><details><summary>Extensions (29)</summary>

Extension|Author (truncated)|Version
---|---|---
astro-vscode|ast|2.3.1
htmltagwrap|bra|1.0.0
vscode-tailwindcss|bra|0.10.0
turbo-console-log|Cha|2.9.6
gitlens|eam|14.2.1
prettier-vscode|esb|10.1.0
auto-close-tag|for|0.5.14
auto-rename-tag|for|0.1.10
copilot|Git|1.108.376
vscode-github-actions|git|0.26.1
svg|joc|1.5.3
vsc-python-indent|Kev|1.18.0
document|min|2.2.1
python|ms-|2023.14.0
vscode-pylance|ms-|2023.8.50
jupyter|ms-|2023.7.1002162226
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.17
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-slideshow|ms-|0.1.5
remote-containers|ms-|0.304.0
remote-ssh|ms-|0.102.0
remote-wsl|ms-|0.81.0
color-highlight|nau|2.5.0
material-icon-theme|PKi|4.30.1
prisma|Pri|5.2.0
svelte-vscode|sve|107.10.0
vscodeintellicode|Vis|1.2.30
volar|Vue|1.8.8

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
vscccc:30803845
282f8724:30602487
f6dab269:30613381
showlangstatbar:30737416
0bi6i642:30823812
03d35959:30757346
pythonfmttext:30731395
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
pythonnosmt12:30797651
pythonidxpt:30805730
pythonnoceb:30805159
asynctok:30821568
dsvsc013:30795093
dsvsc014:30804076
diffeditorv1:30821571

```

</details>

**Comment by Tyriar** [comment]
Please provide a screenshot or [a gif](https://gifcap.dev/) illustrating the problem (attaching images won't work via email, you need to go to github.com). See [this wiki page](https://github.com/microsoft/vscode/wiki/Terminal-Issues) for more general info on how to report actionable terminal issues.

/label "info-needed" terminal

**Comment by npv2k1** [comment]
![Recording 2023-09-11 at 22 13 20](https://github.com/microsoft/vscode/assets/73846954/042ace39-1ab2-4047-b87d-a65766f1cf5c)

**Comment by Tyriar** [comment]
@deepak1556 the window which is marked as always on top isn't showing here 😕

**Comment by npv2k1** [comment]
I know where the problem is. I'm using 2 screens, I changed the position of the 2 screens and vscode remembers the old screen position so its window appears outside the 2 screens that's why it doesn't appear. Thank!

**Comment by Tyriar** [comment]
Ah ok, when I hit that problem in Windows on other apps I focus the window and use win+shift+left/right to get it on the right monitor
