### ISSUE TITLE
Launch/Task Configuration Options in User Settings being Added to Debug: Add Configuration

### ISSUE THREAD

**Issue by Seraphendipity** [microsoft/vscode#192060]
Version: 1.81.1 (user setup)
Commit: 6c3e3dba23e8fadc360aed75ce363ba185c49794
Date: 2023-08-09T22:22:42.175Z
Electron: 22.3.18
ElectronBuildId: 22689846
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Windows_NT x64 10.0.22621

When either selecting Debug: Add Configuration, or one of its many shortcuts such as "create a build file" on the Run and Debug panel, a list of potential configurations drop down, typically including a launch.json and tasks.json. Many extensions add onto this list with varying options. Additionally, users may add a launch config in their user settings, which will thus act as if added to all projects.

The problem, however, is the former is not modifiable by users easily, requiring creating an entire extension themselves for minute changes, and the latter only works on that users' systems. Where the .vscode builds files would want to be shared with others, neither of these solutions work.

A simple change would be to add any launch configuration from the user settings to the Add Configuration dropdown menu as well (instead of being usable, but not attachable to the project without manual copy/paste).

**Comment by roblourens** [comment]
What I would suggest here is using a normal snippet, registered for the `jsonc` language. This will show up in launch.json and let you take advantage of the normal snippet infrastructure to fill in your preferred launch config. The disadvantage is that it will show up in other json files as well, but I don't want to try to reinvent snippets just for launch.json.
