### ISSUE TITLE
Compress single test messages in the Test Results tree view

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#192010]
@connor4312 testing this out and it looks better to me - although is it the case that now there will always be only a single child in the tree below the test?

![image](https://github.com/microsoft/vscode/assets/1078012/996afa2d-231b-4e0e-9d42-aa1fa69deff0)

If so, could the output not be shown against the test node and the child removed? Currently it seems like clicking on the test name doesn't do anything (except maybe expand/collapse) which I find confusing. I feel like clicking on the test name and seeing the output (and it having no children) would be better - but I'm not sure if there are cases where there are more children.

Thanks!

_Originally posted by @DanTup in https://github.com/microsoft/vscode/issues/187104#issuecomment-1700873018_

**Comment by DanTup** [comment]
@connor4312 thank you! I found this window really confusing before (and had lots of complaints about it), but it's so much clearer what this tree is now :-)

![image](https://github.com/microsoft/vscode/assets/1078012/efc6492a-098e-46cb-b0cd-bc7918cd76aa)
