### ISSUE TITLE
[html] disable formatter for cshtml

### ISSUE THREAD

**Issue by alvipeo** [Microsoft/vscode#19206]
- VSCode Version: Code - Insiders 1.9.0-insider (4265f5e35cb3ea8ba7e0cf6b14ec606b6f8647ea, 2017-01-24T10:37:36.620Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

|Extension|Author|Version|
|---|---|---|
|Bookmarks|alefragnani|0.10.2|
|vscode-stylesheet-formatter|dbalage|0.2.0|
|githistory|donjayamanne|0.1.5|
|xml|DotJoshJohnson|1.7.0|
|tslint|eg2|0.8.1|
|Angular2|johnpapa|1.0.2|
|csharp|ms-vscode|1.6.2|
|debugger-for-chrome|msjsdiag|2.4.2|
|stylelint|shinnn|0.21.2|

---

Steps to Reproduce:

I have an MVC View with the following markup:

```
@{ Layout = "~/Views/Shared/_LayoutOthers.cshtml"; } @section logoMobile {
<a href="/realassets"><img src="~/images/real-assets.jpg" alt="" /></a>
} @section logoDesktop { @* two images because this logo doesn't change on hover *@
<a href="/realassets">
    <img src="~/images/real-assets.jpg" alt="" />
    <img src="~/images/real-assets.jpg" alt="" />
</a>
} @section mobilemenuItems {
<li><a href="/realassets/news">News</a></li>
<li><a href="/realassets/videos">Videos &amp; Podcasts</a></li>
<li><a href="/realassets/advertising">Advertising</a></li>
} @section deskmenuItems {
<li><a href="/realassets/news">News</a></li>
<li><a href="/realassets/videos">Videos &amp; Podcasts</a></li>
<li><a href="/realassets/advertising">Advertising</a></li>
}
[... regular HTML with Razor goes here ...]

```
This is a formatted version (Alt+Shift+F). As you can see it's a mess.

**Comment by mousetraps** [comment]
Oh wow, this is a fun one! So, I have a feeling what's happening is that for some reason, "cshtml" is actually getting treated as "html" from the formatter's perspective - so when you try to format, it's actually invoking the HTML formatter - the reason I think this is that the two file types seem to get formatted in the same way. 

The bad news is that even when we fix this, you won't actually be able to format .cshtml - see https://github.com/Microsoft/vscode/issues/10236

cc @aeschli

**Comment by alvipeo** [comment]
Can you create a formatter for .cshtml by improving HTML formatter?

**Comment by aeschli** [comment]
At the moment we have the html formatter active for cshtml. It is not aware of the cshtml syntax.
All I can do at this tim is disabling the formatter. We hope that an extension can provide a good cshtml formatter.
