### ISSUE TITLE
Add a comfortable way to search filenames with regex etc. support

### ISSUE THREAD

**Issue by Destroy666x** [microsoft/vscode#192024]
This issue: https://github.com/microsoft/vscode/issues/127723 got closed even though people support it, few more got closed after, so creating a new one.

I don't know how this isn't a feature already - most, even basic editors like Notepad++, can search filenames fairly easily. Searches in VSCode are generally very lacking in comparison to other features, however, this is the worst - searching for names right now:
- is uncomfortable and rather hidden
- doesn't support basics like regexes

Rejecting adding this to search panel because of complexity is nonsense, you can always hide additional options under some `Advanced options` dropdown if needed.

**Comment by andreamah** [comment]
https://github.com/microsoft/vscode/issues/127723#issuecomment-881711911 

To add to this, we use [ripgrep](https://github.com/BurntSushi/ripgrep) to search through files, which uses globs to filter out files. Something like this would require changes on upstream dependencies, which we do not plan on doing soon for this case.
