### ISSUE TITLE
Can't search for files starting with "task " in the name in CTRL+P window

### ISSUE THREAD

**Issue by diath** [microsoft/vscode#192072]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.81.1 6c3e3dba23e8fadc360aed75ce363ba185c49794 x64
- OS Version: Arch Linux / x86_64 Linux 6.4.12-arch1-1

Steps to Reproduce:

1. Press CTRL+P in a workspace that contains a file whose name starts with "task ". 
2. Type "task " in the search input.
3. Observe the palette changing from file search to task launch instead of finding files matching the name.

https://github.com/microsoft/vscode/assets/1154021/51722174-607b-4355-94a0-dde1ca832fe4

**Comment by gjsjohnmurray** [comment]
Maybe try putting doublequotes around your search phrase.

**Comment by diath** [comment]
That seems to work however I fully expect to search for just files when using CTRL+P ("Navigate to file") and not a command palette by adding `>` prefix in my search query. It's really counter-intuitive and seems unintended especially that `task` seems to be the only word I've encountered that triggers this behavior when using CTRL+P for navigation exhaustively. Unless it's actually fully intended behavior.

**Comment by gjsjohnmurray** [comment]
It is intended. Enter `?` to see which other prefixes have special meaning in Command Palette.

**Comment by diath** [comment]
Alright, thanks for clearing it up.
