### ISSUE TITLE
Make LoadedSources in debug view editable if they are served as a virtual document

### ISSUE THREAD

**Issue by tzAcee** [microsoft/vscode#192131]
I'm developing a debugger extension, which get's the sources from a server. Those sources are displayed in the Loaded Scripts entry of the vscode debug view as virtual documents (scheme like "server_src:/blabla.ts"). Now because those sources are not really existing the files are only served internally from a TextDocumentContentProvider and the content from the provider is read only.

Now I want to edit those sources and send the edited document back to the server (on save/change or whatever).

I've read that such a things could be solved by a FileSystemProvider, but since the sources are getting loaded from the Debug View, I assume I cant use that. Atleast I was not able to register the FileSystemProvider for the files from the Loaded Scripts Tab.

**Comment by roblourens** [comment]
> Atleast I was not able to register the FileSystemProvider for the files from the Loaded Scripts Tab.

I would assume this would work. What was the problem?

**Comment by tzAcee** [comment]
Hi,
the issue is that the debug view set's an own scheme (**debug:**) for Loaded Scripts before my file scheme and also appends some kind of session info (everything after the '**?**').
![image](https://github.com/microsoft/vscode/assets/50580688/6b0a7080-f33b-4e9d-8eb9-cf805685e170)

So Im not able to register the fileprovider on my scheme, but have to register it on the "debug" scheme to make this to work,
But for the session stuff: I cannot create a file afterwards (for getting the full document uri) in my custom provider. Since the "broken" editor doesn't callback any function (e.g. onDidChangeVisibleTextEditors)

**Comment by tzAcee** [comment]
> > Atleast I was not able to register the FileSystemProvider for the files from the Loaded Scripts Tab.
> 
> I would assume this would work. What was the problem?

The main problem is that I dont really have control about the file scheme ("debug" is the scheme from the debug view, so my own scheme is invalid) and the full Document URI (meta information after the filename).

![image](https://github.com/microsoft/vscode/assets/50580688/fba03f16-6388-4fa5-9db7-51f0489a3fd8)

I cannot create the file in my custom filesystem afterwards, since no callback get's called for the "broken" editor.

**Comment by roblourens** [comment]
We only use the `debug` scheme when the script's path couldn't be parsed as a uri. What do your loaded source events look like?

**Comment by tzAcee** [comment]
> We only use the `debug` scheme when the script's path couldn't be parsed as a uri. What do your loaded source events look like?


Ah okay.
My LoadedSourceEvents look like this:  `this.session.sendEvent(new LoadedSourceEvent("new", source));`
where source is defined like this:
`new Source(path.basename(url), url, sourceRef ? sourceRef.sourceRef : undefined, undefined, 'uart-debugger-data');`

When I log "new Source" that's the output: 
```
creating source:  Source2 {name: 'Module1-Module.js', path: 'uart_script:/global_modules/Module1-Module.js', sourceReference: 1000, adapterData: 'uart-debugger-data'}
extensionHostProcess.js:108
creating source:  Source2 {name: 'Context1-Module.js', path: 'uart_script:/script_modules/MOD1::SCRIPTS/Context1-Module.js', sourceReference: 1001, adapterData: 'uart-debugger-data'}
```

**Comment by gjsjohnmurray** [comment]
It looks to me like your url strings are malformed Uris as they lack an `authority` component.

Instead of, say, `uart_script:/global_modules/Module1-Module.js` I suggest you use `uart_script:///global_modules/Module1-Module.js`

**Comment by tzAcee** [comment]
> It looks to me like your url strings are malformed Uris as they lack an `authority` component.
> 
> Instead of, say, `uart_script:/global_modules/Module1-Module.js` I suggest you use `uart_script:///global_modules/Module1-Module.js`
![image](https://github.com/microsoft/vscode/assets/50580688/be6ed5ff-2146-4a91-af9e-64a9d7327e0d)


I have tried to modify it that way, output is now accordingly:
```
creating source:  Source2 {name: 'Module1-Module.js', path: 'uart_script:///global_modules/Module1-Module.js', sourceReference: 1000, adapterData: 'uart-debugger-data'}
extensionHostProcess.js:108
creating source:  Source2 {name: 'Context1-Module.js', path: 'uart_script:///script_modules/MOD1::SCRIPTS/Context1-Module.js', sourceReference: 1001, adapterData: 'uart-debugger-data'}
```

But I can still register the FileSystemProvider to the debug-scheme (with the above error editor).

**Comment by gjsjohnmurray** [comment]
I'm not clear whether you have registered `uart_script` as a FileSystemProvider that you implement.

Nor whether after amending the url strings you're still getting exactly the same "editor could not be opened" message when you try and open one of the Loaded Scripts entries.

**Comment by tzAcee** [comment]
Yes, I have registered uart_script as a FileSystemProvider with my implementation.
![image](https://github.com/microsoft/vscode/assets/50580688/c241aea0-f634-4b65-b680-86d8098c6f03)
Im also creating the file structure testwise beforehand.
![image](https://github.com/microsoft/vscode/assets/50580688/0be08e2a-6f10-47b8-aad8-2e0f89b30f31)
But the files aren't getting opened from this FileSystemProvider.

If I add something like this and open one of the loaded scripts:
![image](https://github.com/microsoft/vscode/assets/50580688/47b5f40b-13ad-4f77-a88e-d2bc3469fdb7)
I get this output:
![image](https://github.com/microsoft/vscode/assets/50580688/2018c94d-3bdb-4a58-ace8-631449ac9ca8)

If I uncomment the filesystemprovider with the debug-scheme the error message is still the same, even though I changed the url strings:
![image](https://github.com/microsoft/vscode/assets/50580688/74ea10e9-1dd2-44b3-8850-16595063b5ff)

... to go a bit further. If I write and open a random file manually, starting with the uart_script scheme, then the file get's opened with my uart_script filesystem provider.
![image](https://github.com/microsoft/vscode/assets/50580688/8b1fd842-dafa-47ac-8624-1ab02b560214)

**Comment by gjsjohnmurray** [comment]
> We only use the `debug` scheme when the script's path couldn't be parsed as a uri. What do your loaded source events look like?

@roblourens, any ideas now @tzAcee seems to be supplying a uri-conformant script path?

**Comment by tzAcee** [comment]
I assume a possible solution would be to register the FileSystemProvider on "debug".
And serve the files like so /uart_script/modules/bla.js. So the complete Uri would be "debug:/uart_script/modules/bla.js".

But I dont know whether this is a bulletproof solution.

**Comment by roblourens** [comment]
If you provide a `sourceReference`, then we assume that you want us to request the source from the debug adapter via the `sourceReference`. Try not sending that. Thanks for asking the right questions @gjsjohnmurray!

**Comment by tzAcee** [comment]
> If you provide a `sourceReference`, then we assume that you want us to request the source from the debug adapter via the `sourceReference`. Try not sending that. Thanks for asking the right questions @gjsjohnmurray!

That's what I found out yesterday evening! 
In addition to that, an uri-scheme with a "-" character is not allowed.

When taking both things in account, I can register a FileSystemProvider on my own scheme 😃 

Thank you very much for your help and input.
