### ISSUE TITLE
extension not installing

### ISSUE THREAD

**Issue by asdghklnvvj** [microsoft/vscode#192147]
Type: <b>Bug</b>

i try to install extension in vs code this show error while installing any  extension name please check the log for more detalis and try to manully download extension remenber show my screen eperm:operation not permitted,mkdir c/user/sshiva/vscode/extension plz solve this problem

VS Code version: Code 1.81.1 (6c3e3dba23e8fadc360aed75ce363ba185c49794, 2023-08-09T22:22:42.175Z)
OS version: Windows_NT x64 10.0.22621
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|12th Gen Intel(R) Core(TM) i7-12650H (16 x 2688)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.63GB (9.29GB free)|
|Process Argv|--crash-reporter-id a0a220e3-4875-411b-949a-3c0e05c2a5fe|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
py29gd2263:30792226
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
vsccc:30803844
3biah626:30602489
f6dab269:30613381
showlangstatbar:30737416
0bi6i642:30823812
03d35959:30757346
24365598:30736109
pythonfmttext:30731395
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
pythonnosmt12:30797651
pythonidxpt:30805730
pythonnoceb:30805159
dsvsc013:30795093
dsvsc014:30804076
diffeditorv1:30821571

```

</details>

**Comment by zeedeezz** [comment]
Try re-installing vs code on your computer

**Comment by ffyhnh** [comment]
Not working I try this

**Comment by ffyhnh** [comment]
> Try re-installing vs code on your computer
Not working I try this

**Comment by sandy081** [comment]
> eperm:operation not permitted,mkdir c/user/sshiva/vscode/extensions 

Looks like you do not have necessary permissions to write into this folder. Please fix the permissions of this folder and allow to make it writeable which will fixes the problem.
