### ISSUE TITLE
Highlighted character jumps around when highlighting text.

### ISSUE THREAD

**Issue by pushkin-** [Microsoft/vscode#19218]
- VSCode Version: 1.8.1
- OS Version: Windows 10

Steps to Reproduce:

1. In the output window, highlight some text
![gif](https://cloud.githubusercontent.com/assets/6374473/22253248/77f23476-e216-11e6-9efd-f8025b82bc53.gif)
- cursor/selected char lags behind and sometimes jumps to the right when highlighting left.

I have the VSCodeVim extension; maybe it's causing problems.

**Comment by mousetraps** [comment]
Thx for reporting! Couple Qs to help narrow it down - 
1. does the issue go away when your run VS Code with `code --disable-extensions`?
2. Does the issue occur only in the output window, or in the editor as well?

**Comment by rebornix** [comment]
I run into the problem @pushkin- mentioned sometimes in output or debug panel without Vim extension and I just give a thorough test and figured out that why I had the issue: while moving the cursor the the left of the line, I happen to move cursor to one line below or anywhere between current line and next line.

A good way to check whether you are having the same issue is seeing whether you can reproduce what I mentioned above and see if it's the same thing you are running into.

**Comment by pushkin-** [comment]
@mousetraps It's the same thing in the editor. I've disabled the extension and I can't reproduce the issue in VSCode, so it looks like it's a problem with the extension.
