### ISSUE TITLE
Inline values are not shown for a variable assignment from a function

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode#19216]
Testing #18670 

Using Node

See line no 22 in the following screenshot. Variable a is assigned to a value returned by a function. But value of a is not shown on that line.

![image](https://cloud.githubusercontent.com/assets/10746682/22252742/7c3f31ee-e24f-11e6-918c-1b1f82c7118b.png)

**Comment by isidorn** [comment]
```
var express = require('express');
var router = express.Router();

function c() {
  return {
    a: 1
  }
}

/* GET home page. */
router.get('/', function(req, res, next) {

  var a = 1234;

  if (a === 1234) {
    a = 3;
    var b = 2345;
    var a = 4;
  } else {
    var b = 5678;
  }
  a = c().a;
  a = 5678;

  console.log(c);
  res.render('index', { title: 'Express' });

});

module.exports = router;
```

**Comment by isidorn** [comment]
This is the rare case that variables from different scopes are on the same line. That case the current implemntation does not handle well.

**Comment by isidorn** [comment]
Closing as will not fix
