### ISSUE TITLE
`vscode.TreeView.dispose` doesn't clean up in the renderer

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#192126]
I went after some later callers of `Disposable#_register` (see [dev-discuss](https://vscodeteam.slack.com/archives/C03ERNTC03X/p1693495534466199?thread_ts=1693487218.646529&cid=C03ERNTC03X)) and I noticed that `$registerTreeViewDataProvider` uses the disposable of its container object, not one specific to the tree view (id). It's likely a theoretical bug but it seems that extensions calling dispose of their view don't achieve anything and that repeated create calls for the same id could leak some memory

**Comment by sandy081** [comment]
Verified via code review
