### ISSUE TITLE
i can't add folder (open it and working with it) in vs code 

### ISSUE THREAD

**Issue by H88-H** [microsoft/vscode#192158]
Type: <b>Bug</b>

I disabled every extension, but it didn't fix the issue. When I add the folder, it simply doesn't do anything (it's still not working). I can see the folder name at the top, but I can't see the folder or work with it.

VS Code version: Code 1.81.1 (6c3e3dba23e8fadc360aed75ce363ba185c49794, 2023-08-09T22:22:42.175Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Celeron(R) N4020 CPU @ 1.10GHz (2 x 1094)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: disabled_off<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|3.81GB (0.43GB free)|
|Process Argv|--crash-reporter-id 7f693cf4-9944-4034-9a6c-cf7a4e9524d6|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (18)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|3.0.2
codesnap|adp|1.3.4
vscode-html-css|ecm|1.13.1
prettier-vscode|esb|10.1.0
auto-close-tag|for|0.5.14
auto-rename-tag|for|0.1.10
vscode-dotnet-runtime|ms-|1.7.2
python|ms-|2023.14.0
jupyter|ms-|2023.7.1002162226
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.17
vscode-jupyter-slideshow|ms-|0.1.5
live-server|ms-|0.4.9
autodocstring|njp|0.6.1
indent-rainbow|ode|8.3.1
LiveServer|rit|5.7.9
rainbow-brackets-2|tej|1.1.0
vscode-icons|vsc|12.5.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263:30335439
vscoreces:30445986
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
vscccc:30803845
2e4cg342:30602488
f6dab269:30613381
a9j8j154:30646983
showlangstatbar:30737416
03d35959:30757346
57b77579:30736110
pythonfmttext:30731395
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
pythonnosmt12:30797651
pythonidxptcf:30805731
pythonnoceb:30805159
synctok:30821570
dsvsc013:30795093
dsvsc014:30804076
diffeditorv2:30821572

```

</details>

**Comment by ArturoDent** [comment]
Just as a guess, try `View: Show Explorer` or `View: Rest View Locations`.

Did you previously move the Explorer to a different location?

**Comment by H88-H** [comment]
> no i did not move it, i meant i can't add the file, it is a video of it i know you don't understand me well  [https://youtu.be/7tHSk3F4tD8](url), i will appreciate your help <3

**Comment by H88-H** [comment]
I figured it out, when i add a folder it isn't showing on explorer i have to right click on the screen and then use "open file"
to use the file in that folder
