### ISSUE TITLE
Duplicate Lines In Search Editor

### ISSUE THREAD

**Issue by hediet** [microsoft/vscode#192113]
Search for `private .* = derived\(` in https://github.com/microsoft/vscode/blob/71dd6e73a04a26645550c5120187b5cdbbbb5f7f/src/vs/editor/browser/widget/diffEditorWidget2/diffEditorDecorations.ts#L30-L31

Notice Line 30 appears twice for first search result:

![Image](https://github.com/microsoft/vscode/assets/2931520/662b1616-7798-4254-a3ad-da708c02c077)

**Comment by andreamah** [comment]
<img width="554" alt="image" src="https://github.com/microsoft/vscode/assets/31675041/4d81fcb1-d419-4b50-85c3-c7c949140a58">

That's strange, I can't seem to repro. Does it happen every time you do this?

**Comment by hediet** [comment]
It happens consistently when I search for `private .* = derived\(.*\n`

**Comment by goldo** [comment]
same here (search editor), it happens on context lines I suppose.
When it happens, I cant option + click on the search editor to open the file

My config:

```
  "search.searchEditor.defaultNumberOfContextLines": 3,
  "search.exclude": {
    "**/package-lock.json": true,
    "**/yarn.lock": true
  },
  "search.searchEditor.reusePriorSearchConfiguration": true,
  "search.showLineNumbers": true,
  "search.useIgnoreFiles": true,
  "search.smartCase": true,

```

**Comment by andreamah** [comment]
<img width="505" alt="image" src="https://github.com/microsoft/vscode/assets/31675041/4095e948-b97c-4fe0-be37-b2bf1514abb9">
Hmm, I see this now, I'll look into it.

**Comment by yougotwill** [comment]
@andreamah When you toggle the number of context lines it resolves in some places and breaks in others. I'm guessing the last line within each context result is being duplicated somehow.

https://github.com/microsoft/vscode/assets/14887287/e1a32f6e-6e1a-4800-b46d-9b0934b3ca5d

**Comment by svipas** [comment]
Could easily repro on VS Code (desktop & web). Seems like recent regression.
