### ISSUE TITLE
Inline values are shown for a variable in different scope if it has same name in current scope

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode#19215]
Testing #18670 

Using Node

See the inline values for variable `a` under function `c` scope and in current scope.

![image](https://cloud.githubusercontent.com/assets/10746682/22252605/104515a8-e24f-11e6-8d62-864b88a06c4e.png)

**Comment by isidorn** [comment]
@sandy081 please provide this repository so I can easily reporduce this - thanks

**Comment by sandy081** [comment]
@isidorn It's our smoke test express repository and modified the file `index.js`. Here is the code 
```javascript
var express = require('express');
var router = express.Router();

function c() {
  return {
    a: 1
  }
}

/* GET home page. */
router.get('/', function(req, res, next) {

  var a = 1234;

  if (a === 1234) {
    a = 3;
    var b = 2345;
    var a = 4;
  } else {
    var b = 5678;
  }
  a = c().a;
  a = 5678;

  console.log(c);
  res.render('index', { title: 'Express' });

});

module.exports = router;

```

**Comment by isidorn** [comment]
@sandy081 thank you

**Comment by sandy081** [comment]
@isidorn  Updated the description it is happening with Node not with Node2. If scopes are not supported by Node, please close it

**Comment by isidorn** [comment]
Scopes are not supported by node
