### ISSUE TITLE
Language specific settings overwrite all or nothing from User to Workspace

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#19219]
Test: https://github.com/Microsoft/vscode/issues/19060

- VSCode Version: 1.9
- OS Version: Windows

Steps to Reproduce:

User settings:

```
	"[markdown]": {
		"editor.wordWrap": true,
		"editor.lineNumbers": "off"
	}
```

Workspace settings:
```
	"[markdown]": {
	}

```

Displays mardown files with wordwarp false and lineNumbers on

**Comment by dbaeumer** [comment]
The means I can't add a markdown setting for something in a workspace. For example
```
	"[markdown]": {
		"files.insertFinalNewline": true
	}
```

I personally find this very confusing since I still specific single settings and we always merged single setting from User - Workspace. If we would have chosen a different syntax like `"markdown[editor.wordWrap]"` our current implementation would have merged user and workspace specific markdown settings

So I think we should not depend this on our implementation but should define the expected behavior and then implement it.

**Comment by sandy081** [comment]
@dbaeumer After giving more thinking, I also felt that merging the language specific settings from user to workspace is a better strategy and user experience. 

@bpasero FYI, Mentioning you as I remember that when we discussed, you were inclined towards overriding than merging.

**Comment by bpasero** [comment]
@sandy081 we must merge and NOT override, sorry if I was not clear from the beginning 👍 . This is also what happens for other settings like `files.exclude`.

**Comment by sandy081** [comment]
Its fine @bpasero, Thanks for clarification.
