### ISSUE TITLE
Pasting is not selecting the newly pasted text

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#192196]
This happens after a regular ctrl+v:

![Image](https://github.com/microsoft/vscode/assets/2193314/253f6723-704c-43fc-b070-52d4f12a583d)

It's very easy to reproduce.

버전: 1.82.0-insider (user setup)
커밋: f1302be1e67e3af5fbeb8bbb2ea784de7bc96150
날짜: 2023-09-01T11:08:40.414Z
Electron: 25.8.0
ElectronBuildId: 23503258
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.22621

**Comment by Tyriar** [comment]
More examples with screencast:

![Recording 2023-09-05 at 06 16 48](https://github.com/microsoft/vscode/assets/2193314/e483d5bd-6f31-40f8-a35a-6cb51ee3b555)

**Comment by mjbvz** [comment]
Simply repo:

```
some language stuff

natural language search
```

1. Copy `natural language search`
2. Select `language` on the first line and paste

**Comment by mjbvz** [comment]
Seems ok in 1.81. Also fixed by disabling `editor.pasteAs.enabled`

**Comment by alexr00** [comment]
Verified that the behavior matches 1.81 (nothing is selected after paste).
