### ISSUE TITLE
Color settings for selected text (single-click, double-click)

### ISSUE THREAD

**Issue by steveareeno** [Microsoft/vscode#19211]
- VSCode Version: 1.8.1
- OS Version: Windows 7

Is there a way to prevent Visual Studio Code from highlighting editor text, specifically  when single clicking on it? The difference in highlight color between single clicking and double clicking (to fully select the text) is too subtle for me as I am color blind. I struggle with being able to tell if the word is actually selected for copy/paste operations (for example). A setting to change the colors associated with the click and double click would also be adequate

Thanks

**Comment by steveareeno** [comment]
Disregard this request. It turns out that the issue is only with HTML and I think that can be turned off by setting the matching tag setting

**Comment by mousetraps** [comment]
Sweet! Glad you've got it figured out! Closing as this appears to be resolved, but let us know if you run into any other issues. Happy coding!
