### ISSUE TITLE
Multiline search using regex fails to return all results

### ISSUE THREAD

**Issue by paymand** [Microsoft/vscode#19217]
- VSCode Version: Code 1.8.1 (ee428b0eead68bf0fb99ab5fdc4439be227b6281, 2016-12-19T14:49:23.350Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions:

|Extension|Author|Version|
|---|---|---|

Hi,
I'm trying to find all occurences of:
''LTS+/\r&
''IGNORED\r&

I use the following regex:

`''LTS\+/\\r&[\r\n].*''IGNORED.*[\r\n]
`

which seems to work in sublime text, for instance.
On VSCode, it only returns one hit.
---

Steps to Reproduce:

1.
2.

**Comment by roblourens** [comment]
Our text search in general only works line-by-line

**Comment by paymand** [comment]
Oh, well. At least I know why it isn't working :)
:+1:  for the feature request.

**Comment by danwulff** [comment]
Atom does not have multi-line regex searching atm it seems: https://github.com/atom/find-and-replace/issues/303

But I wouldn't mind seeing it implemented. I personally don't care for line breaks in the middle of code but I could see it being useful for others.

**Comment by roblourens** [comment]
Actually there is an existing feature request for this: https://github.com/Microsoft/vscode/issues/13155

**Comment by steviesama** [comment]
@danwulff I don't know if it still isn't supposed to have multiline regex, but I have made it work.  Here is where I posted about it with explanation and screen shots:

[https://github.com/atom/find-and-replace/issues/303#issuecomment-319508730](url)
