### ISSUE TITLE
Glob `<node_internals>/**/fs.js` in skipFiles doesn't seem to work

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#19210]
Testing #19042

I was able to get `<node_internals>/fs.js` to work, but not `<node_internals>/**/fs.js` when using the `skipFiles` feature of debug.

**Comment by weinand** [comment]
@joaomoreno is this a problem with `node` or `node2`?

**Comment by joaomoreno** [comment]
Great question, only seems to happen in `node2`.

**Comment by weinand** [comment]
Aha, IIRC 'node2' only supports regular expressions at the moment. This explains why the '**' part doesn't work.

**Comment by roblourens** [comment]
I do support `**`, but have to map it to a regex, and I don't do that right for this node_internals case
