### ISSUE TITLE
Shell script syntax highlight issue for values beginning with a number

### ISSUE THREAD

**Issue by dnicolson** [microsoft/vscode#192157]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.81.1
- OS Version: macOS 14

Steps to Reproduce:

1. Set language mode to "Shell Script"
2. Paste the following:
```
VAR1=xxx000
VAR2=000xxx
```

VS Code 1.75.1:
![PixelSnap 2023-09-04 at 19 06 17@2x](https://github.com/microsoft/vscode/assets/2276355/e19c85a2-178f-4858-8e16-9847768d5dfd)

VS Code 1.76.2:
![PixelSnap 2023-09-04 at 19 06 34@2x](https://github.com/microsoft/vscode/assets/2276355/874d2d4d-86eb-419e-b2ec-b438a99ffc14)

VS Code 1.78.2+ and latest Insiders:
![PixelSnap 2023-09-04 at 19 06 51@2x](https://github.com/microsoft/vscode/assets/2276355/c30fd344-7bc0-4362-9596-bf80057a77d8)

**Comment by alexr00** [comment]
I can repro the issue. I've copied it to https://github.com/jeff-hykin/better-shell-syntax/issues/65, which is where we pull our shellscript syntax highlighting grammar from.
