### ISSUE TITLE
Terminal: White bar on top of terminal

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode#192136]
Version: 1.82.0-insider (user setup)
Commit: f1302be1e67e3af5fbeb8bbb2ea784de7bc96150
Date: 2023-09-01T11:08:40.414Z
Electron: 25.8.0
ElectronBuildId: 23503258
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.22631

 A white bar is hiding the first characters of the last line:

![Recording 2023-09-04 at 15 18 55](https://github.com/microsoft/vscode/assets/6461412/cce87b8a-a1d6-4dc7-8d50-ded57b604a24)

![Image](https://github.com/microsoft/vscode/assets/6461412/ce15937d-78b0-40ef-a465-24c78d40bf38)

Last week I tested some terminal accessibility issues, using the terminal buffer, maybe that's related.

**Comment by meganrogge** [comment]
do you have `terminal.integrated.developer.devMode` enabled in your settings.json?

**Comment by aeschli** [comment]
Thanks that was it.
