### ISSUE TITLE
Cannot drag a terminal to become a "main terminal"

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#192152]
* have a terminal
* press the split terminal btn to create another one
* use DND and try to drag it so that it becomes a main, non-split terminal
* doesn't work, despite the DND feedback

https://github.com/microsoft/vscode/assets/1794099/f51333cb-dd20-4a44-8b12-bd98c38d5729

**Comment by Tyriar** [comment]
This is actually working as designed. We decided to make dragging in the list only rearrange the tabs and restrict "unsplitting" to the context menu. If we combine the two behaviors in dragging in the list it becomes ambiguous what dragging is going to do.

For example If dragging to the bottom area "unsplit" a terminal, it would not be possible to move the terminal group to the bottom and it's unclear what dragging in the middle of the list would do (move the group to that spot or unsplit and move only the unsplit tab?

**Comment by jrieken** [comment]
>  it would not be possible to move the terminal group to the bottom

How about making the group draggable, e.g by using multi-select of each item. I am obviously biased but I believe rearranging items is less common the split/unsplit.

**Comment by Tyriar** [comment]
> I am obviously biased but I believe rearranging items is less common the split/unsplit.

I'm the opposite, I rearrange quite a bit because I like tasks on top and I never unsplit.

> How about making the group draggable, e.g by using multi-select of each item

Do you mean to require selecting all splits individually to rearrange the group together?
