### ISSUE TITLE
Add functionality that copies command and output, as opposed to just copying command, or just copying output

### ISSUE THREAD

**Issue by hamirmahal** [microsoft/vscode#192216]

**Comment by hamirmahal** [comment]
It'd be nice if VSCode users had a way to copy the last command's output, and the command itself, in one click, as opposed to having to click each button separately.

**Comment by hamirmahal** [comment]
# Current behavior

https://github.com/microsoft/vscode/assets/43425812/fcd61bc5-eaba-4b80-abd0-7add01fac695

**Comment by hamirmahal** [comment]
# Current behavior
https://github.com/microsoft/vscode/assets/43425812/505b95e6-df13-4089-ab76-e45171fb1fb9

**Comment by Tyriar** [comment]
Related: https://github.com/microsoft/vscode/issues/178154

**Comment by 0x303** [comment]
I am glad I am not the only one who thinks this would be a great feature. More information is in the issue the Tyriar commented.

**Comment by Tyriar** [comment]
To verify run a command in the terminal and then run Copy Command and Output on the shell integration decoration to the left.
