### ISSUE TITLE
How to get around "JS" debugging output limit?

### ISSUE THREAD

**Issue by 11875258** [Microsoft/vscode#19221]
- VSCode Version: Code 1.8.1 (ee428b0eead68bf0fb99ab5fdc4439be227b6281, 2016-12-19T14:49:23.350Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

|Extension|Author|Version|
|---|---|---|
|vscode-standard-format|chenxsan|0.0.12|
|gitignore|codezombiech|0.5.0|
|javadebugger|donjayamanne|0.0.2|
|git-project-manager|felipecaputo|1.0.1|
|php-debug|felixfbecker|1.10.0|
|terminal|formulahendry|0.0.6|
|file-ext-switcher|JohannesRudolph|2.0.1|
|mssql|ms-mssql|0.2.0|
|cpptools|ms-vscode|0.9.3|
|csharp|ms-vscode|1.6.2|
|PowerShell|ms-vscode|0.9.0|
|debugger-for-chrome|msjsdiag|2.4.2|
|debugger-for-edge|msjsdiag|0.4.1|
|debugger-for-ios-web|msjsdiag|0.1.2|
|qub-xml|qub|0.3.0|
|yo|samverschueren|0.9.3|
|python-extended-snippets|tushortz|0.0.1|
|unity-debug|Unity|1.1.0|
|html-css-class-completion|Zignd|1.0.3|

---

Steps to Reproduce:

1.
2.

**Comment by 11875258** [comment]
使用“JS”进行调试时，遇到输出限制。请问如何解决该问题？

**Comment by mousetraps** [comment]
@11875258 - I don't know Chinese, but I'll do my best with Google translate. It sounds like you were asking: 
> When using "JS" for debugging, you encounter an output limit. How to solve the problem?

How many characters is the text you're printing out? I found this previous issue that notes the output limit to be 10,000 characters for Node debugging - does that sound like what you're seeing? https://github.com/Microsoft/vscode/issues/4952

**Comment by 11875258** [comment]
@mousetraps 
Thank you very much for your answer, I am a novice in this regard. 
Also hope that after a lot of exhibitions, thank you.

**Comment by mousetraps** [comment]
Great! Happy to help. Closing as it sounds like this issue is resolved, but happy to reopen if you think otherwise. Happy coding!

**Comment by 11875258** [comment]
Communication stops in front of the language
