### ISSUE TITLE
Integrated Shell does not match Shortcut keys in linux terminal-emulator

### ISSUE THREAD

**Issue by cbluth** [Microsoft/vscode#19228]
- VSCode Version: `Version 1.8.1`
- OS Version: `Linux MBP 4.8.0-34-generic #36-Ubuntu SMP Wed Dec 21 17:24:18 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux`

Steps to Reproduce:

1. do `echo test@test` in ubuntu/gnome terminal emulator
2. doubleclick to select whole string
3. do `echo test@test` in vscode integrated shell
4. doubeclick only selects partial string, `@` character breaks selection

1. CTRL+K and CTRL+U works as expected in ubuntu/gnome terminal emulator
2. CTRL+K and CTRL+U has odd behaviour in vscode integrated shell

**Comment by mousetraps** [comment]
Potentially related: https://github.com/Microsoft/vscode/issues/9958

**Comment by Tyriar** [comment]
Yes #9958 is for the double clicking, there are issues with pursuing this though as it needs to continue to work in a browser setting. 

For ctrl+k I created this today https://github.com/Microsoft/vscode/issues/19248
