### ISSUE TITLE
Word wrap for variables during debug

### ISSUE THREAD

**Issue by LumiereDeLOmbre** [microsoft/vscode#192289]
Hi,

Could it be possible to have the watched variables benefit from word wrap for their value via an opt in option (next to the "collapse all" icon in the watch section ?

I have a long namespaces in C++ and I have to expand the panel (about half the screen) to see the end of the variable value and then put it back because it is too large for my screen.

Is it an option that could be added ? That way a single click could help keeping the debugged code section untouched.

Thanks :)

**Comment by roblourens** [comment]
You can enable `workbench.list.horizontalScrolling`, if that helps

**Comment by roblourens** [comment]
I don't think that word wrap in a narrow tree is the right way to go though, other views in vscode don't work this way and I don't remember seeing UX like that in other apps

**Comment by LumiereDeLOmbre** [comment]
This is actually perfectly sufficient for my needs. Thanks a lot!
