### ISSUE TITLE
Selecting of large folded regions is slow. Time spent in `writeScreenReaderContent`

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode#192278]
Investigating https://github.com/microsoft/vscode/issues/192257

- open https://vscode.dev/, create an untitled file
- create a large JSON array. Add `[]`and insert the content of https://github.com/microsoft/vscode/blob/1e528d7a4cba563f465265344e260394e2e8f332/cgmanifest.json  multiple times separated by commas
- fold the content (Ctrl + K CTRL + 0), expand the top level
- go to the end of the file and slowly select to the top. Note that the selection gets sloppier the longer you do that.

**Comment by aeschli** [comment]
![image](https://github.com/microsoft/vscode/assets/6461412/921e1453-6c81-45a8-91b2-b6f9e6f66eab)

Big contents of selected text are written to the screenreader content, which seems to take a long time to render.
I don't have a screenreader enabled.

**Comment by aeschli** [comment]
[Trace-20230906T105957.zip](https://github.com/microsoft/vscode/files/12535702/Trace-20230906T105957.zip)

**Comment by meganrogge** [comment]
cc @alexdima
