### ISSUE TITLE
Provide available context keys for all DebugConfiguration members

### ISSUE THREAD

**Issue by alestiago** [microsoft/vscode#192277]
## Description

I would like to have available context keys for all DebugConfiguration members. Currently, the only member with an available context key is ["debugType"](https://code.visualstudio.com/api/references/when-clause-contexts#available-context-keys). I would like to have an available context key for accessing the _name_, _request_, and if possible, the additional debug type _specific properties_.

This would help to discriminate debug sessions with the same debugType. Consider the example where there are two running debug sessions, both with the same debug type. The extension would like to contribute only to the second debug session and not the first one because the second debug session is debugging a project that follows a specific setup/configuration or has a different request. The _name_ of the second debug session, _request_ or additional _specific properties_ might be enough to discriminate each other but there are no available context key to perform this check.

## Use case

I'm adding additional buttons to the debug toolbar. I would like to add a custom button only to Dart projects that follow a specific project configuration. The debug session is started through my extension via `debug.startDebugging`, so I have access to specifying the name or any other debug type specific properties. Users might have more than one Dart debug session running at the time, I don't want to add my custom button to other Dart debug session that do not follow the specific project configuration.

Is there an existing way to tackle this?

## References

- [Documented available context keys](https://code.visualstudio.com/api/references/when-clause-contexts#available-context-keys)

**Comment by roblourens** [comment]
Seems kinda tricky because this should probably be controlled by some property on the config, not the name of the config, right? But we don't have a good way to check values on an arbitrary object in a when clause, and we don't want to have context keys with arbitrary names for each launch config property.

You could use `onDidChangeActiveDebugSession` to drive your own context key maybe?

**Comment by alestiago** [comment]
@roblourens any updates here?

**Comment by roblourens** [comment]
I'm not planning on making the whole debug config available as a context key, I prefer more targeted context keys. It wouldn't be too hard to build a small extension that does this, however.
