### ISSUE TITLE
Vscode creates a chat_history folder with db file on every project !!

### ISSUE THREAD

**Issue by issam-seghir** [microsoft/vscode#192241]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.81.1
- OS Version: Windows pro 22H2 (OS Build 19045.3324)

Vscode creates a chat_history folder with db file on every project !!

![image](https://github.com/microsoft/vscode/assets/74573675/8dfaba16-b3fe-485d-8631-a354a4db04ca)

**Comment by gjsjohnmurray** [comment]
Maybe one of your extensions is doing this.

**Comment by tamuratak** [comment]
Duplicate of #191797

**Comment by issam-seghir** [comment]
it caused by the Sourcery extension

**Comment by AIfrontier** [comment]
issam-seghir is correct.
when i encountered this problem, i also uninstalled Sourcery so that solve this issue.
