### ISSUE TITLE
Config edit service: Remove the setting when it has the default value

### ISSUE THREAD

**Issue by egamma** [microsoft/vscode#19220]
Testing #18316

Toggle wordwrap is false by default.

1) enable Toggle wordwrap -> the setting is inserted into the file with the value: true
2) toggle wordwrap again, the setting is back to the default value.

Since the user didn't insert the setting I would have expected that the setting is removed again so that the settings stay as clean as possible.

**Comment by alexandrudima** [comment]
Perhaps `IConfigurationEditingService` should do that under the hood or expose a method for it.

i.e. if someone writes a configuration key `K` with the value `V` and `V` is the default value, then the key can simply be removed from the json file.

AFAIK None of our toggle-like actions that write to configuration have this minimal footprint behavior.

**Comment by bpasero** [comment]
Yeah, would probably make sense to remove it automatically.

**Comment by sandy081** [comment]
This api is also used by the edit action in Settings editor. Doing it under the hood with the current API might cause unexpected behavior in this scenario. But I can add another method to do that. 

In the mentioned scenario, what if user added wordWrap setting manually and toggling it will remove it from the settings file?

**Comment by mmzoo** [comment]
> In the mentioned scenario, what if user added wordWrap setting manually and toggling it will remove it from the settings file?

To add to the headache: by default I'd like `wordWrap` to be `off` but when I toggle it, I'd like it to be `bounded` 🙄 But that's probably stretching it a little too far 😄 

Thank you for your hard work.
