### ISSUE TITLE
Theme names should have transated name and untranslated name like the command palette

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#192223]
See in the list below:

- Dark+ (no localization)
- Kimbie 어둡게 (only dark translated)
- 다크 모던 (all translated with loan words "daku modeon")

![Image](https://github.com/microsoft/vscode/assets/2193314/9140bef0-9dbf-4063-993a-418ab77fef19)

Ideally this would act like commands where we provide the original if they differ:

![Image](https://github.com/microsoft/vscode/assets/2193314/99b734c7-f12d-4c22-9de5-d0ad4a726d21)

**Comment by TylerLeonhardt** [comment]
Verification steps:
* Install a language pack
* switch to said language pack
* run `Color Theme` command

Ensure that both the localized and id are displayed.
