### ISSUE TITLE
Test failure peek isn't ergonomic

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#192281]
* work on adopting `ensureNoDisposablesAreLeakedInTestSuite`
* run a suite that leaks something
* 😕 you loose context and end-up in the leak util. I wanna stay in the current file instead

(this is basically the same as https://github.com/microsoft/vscode/issues/135388)

**Comment by jrieken** [comment]
should be a separate issue but it seems that those stack traces are off by one

**Comment by connor4312** [comment]
We should prefer to stay in the current file if there's any frame in the stacktrace that is in the current file (and within those, prefer the location that's inside the range of the test)
