### ISSUE TITLE
Easily copy formatted variables from Run & Debug

### ISSUE THREAD

**Issue by badjuice** [microsoft/vscode#192291]
I'd like to be able to copy the information that shows up in Run & Debug.
The data could be copied in a structured/organized way (children should be indented).
It would be cool to also be able to just copy this information starting from any level of the data being displayed.
![image](https://github.com/microsoft/vscode/assets/25462821/186678ac-f12d-44bf-8d92-e3204dee8c98)

**Comment by badjuice** [comment]
Currently we can copy the values but if you want to copy several items in, say, a list (as show on my screenshot) the you gotta do it one by one.

It would be very useful when debugging and analyzing data.

**Comment by roblourens** [comment]
This functionality is controlled by the debug extension, please file this on the debug extension you're using
