### ISSUE TITLE
Improve Settings Sync diagnostics tooling

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#192271]
The settings sync tooling that allows to inspect what happened must be improved. I do understand that bugs like https://github.com/microsoft/vscode/issues/192267 happen but I see myself being unable to file good issues (and as a consequence I observe that things don't get better). The sync view with all its viewlets, diff editors, and logs is overwhelming, esp when you must use in an unpleasant situation. There should be a single command which collects all the information needed (it can ask for my input) so that it can create a (zip)-file which allows the respective owners to investigate issues

**Comment by Tyriar** [comment]
FWIW my ability to investigate client-side issues was hampered with the loss of the shared process electron window as the network requests output channel is very minimal. One of the bigger issues I have is that it sanitizes auth tokens from the requests.

**Comment by sandy081** [comment]
> One of the bigger issues I have is that it sanitizes auth tokens from the requests.

You can always get the auth token by debugging - keeping the breakpoint here

https://github.com/microsoft/vscode/blob/7ab575fe3288bc74aa39c0a73277400fadd672cd/src/vs/platform/userDataSync/common/userDataSyncStoreService.ts#L470

**Comment by Tyriar** [comment]
@sandy081 but there's no way in Insiders?

**Comment by sandy081** [comment]
May be we can have a developer command to log the TOKEN?

**Comment by sandy081** [comment]
To verify:

- Make sure you have settings sync turned on
- Run command `Developer: Download Settings Sync Activity`
- Make sure it downloads a folder with following contents
  - remoteActivity.json
  - localActivity folder
  - settings sync logs
- Run command `Settings Sync: Show Synced Data` and enable **Sync Activity (Developer)** view
<img width="417" alt="image" src="https://github.com/microsoft/vscode/assets/10746682/d19542c0-fbaf-4fbb-9cf6-9ae72f5fe3f7">
- Click on **Extract Sync Activity** action and upload `remoteActivity.json` file and make sure remote activity is displayed
