### ISSUE TITLE
No copy path for (non-workspace) file

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#192266]
* opened a log file
* missing reveal in finder
* missing copy path

<img width="1112" alt="Screenshot 2023-09-06 at 09 19 10" src="https://github.com/microsoft/vscode/assets/1794099/0ce54464-aa64-471f-84db-bb4f7f013a55">

**Comment by bpasero** [comment]
Sandy can you check, I think this came in from https://github.com/microsoft/vscode/issues/40575. I wonder why we don't just open the file on disk and why this needs a custom log viewer. We can mark the editor as readonly.

**Comment by jrieken** [comment]
also related to https://github.com/microsoft/vscode/issues/192271

**Comment by sandy081** [comment]
Yeah, this is opened as log viewer to make it readonly. If we can mark readonly for normal files, then we do not need this spl log viewer.

**Comment by bpasero** [comment]
@sandy081 I think there are 2 options here:
* make the setting `files.readonlyInclude` dynamic by adding the logs folder by default
* ad-hoc configure the logs folder or logs file to open as readonly via the new `IFilesConfigurationService.updateReadonly` method

I think I would go with the second choice because that is quite straightforward.

**Comment by sandy081** [comment]
Adopted to ad-hoc readonly state change, but it is allowing user to write into the file

![image](https://github.com/microsoft/vscode/assets/10746682/4b555ea6-e4fd-4d6e-a5b7-e14ad311d7cf)

Is it possible to prevent that? I know user can open the file directly from the folder and can edit, but I would like to prevent this action when opened using the action in output

**Comment by bpasero** [comment]
currently not, but I don't think its a big deal
