### ISSUE TITLE
Invalid regex for package.json name field

### ISSUE THREAD

**Issue by dec0dOS** [microsoft/vscode#192250]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.81.1
- OS Version: macOS 13.5.1

Steps to Reproduce:

1. Create package.json file with the following content:
```
{
  "name": "@some-org/_default"
}
```
2. Receive warning `String does not match the pattern of "^(?:@(?:[a-z0-9-*~][a-z0-9-*._~]*)?/)?[a-z0-9-~][a-z0-9-._~]*$".`

![Screenshot 2023-09-06 at 01 21 02](https://github.com/microsoft/vscode/assets/14824142/56643ddf-7c3b-41c2-96e5-c3475b88c0d6)

This name seems to be allowed for the package name
https://docs.npmjs.com/cli/v9/configuring-npm/package-json#name

![Screenshot 2023-09-06 at 01 25 59](https://github.com/microsoft/vscode/assets/14824142/c5355155-f752-4185-a51b-e63cc6d759be)

**Comment by aeschli** [comment]
We use the schema that come from https://www.schemastore.org/

Please file an issue there:

The regex for name is found here:
https://github.com/SchemaStore/schemastore/blob/2991ef67756c3bacfaa1bcb490c08922c13ca3f1/src/schemas/json/package.json#L205-L206
