### ISSUE TITLE
Error dialog when reindenting JSON file

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode#19223]
Testing #19091.

- Create a JSON file:
```json
{
}
```
- Invoke 'Reindent lines'
- Error dialog: ' Cannot read property 'length' of undefined'

**Comment by aeschli** [comment]
Same for other extensions like 'c', bat',...

**Comment by jrieken** [comment]
swapping `bug` and `verification-needed` labels because the latter should be used for small feature requests that don't deserve a test plan item whereas all bug need verification by default
