### ISSUE TITLE
Extending VSCode API to Enable Control of Activity Bar Icons

### ISSUE THREAD

**Issue by Ranamzes** [microsoft/vscode#192262]
Dear VSCode Development Team,
I recently embarked on a project to create an extension that allows users to control the sequence of icons in the activity bar based on the extension of the active file. This feature aims to make the editor more intuitive and customizable, aligning the available tools in the activity bar with the context of the work being done.

With a large number of extensions, it becomes inconvenient to use the Activity Bar. The icons become cluttered and it's challenging to quickly locate and access the tools relevant to the current task. This issue amplifies the need for better customization options.

Unfortunately, I've hit a roadblock. The current VSCode Extension API doesn't provide a way to manipulate the order of icons in the activity bar. While it allows for the creation of custom views and buttons, the control over the existing UI elements is limited.

This limitation is affecting not only my project but also stifles the creativity of other extension developers who wish to offer a more tailored experience to VSCode users.

I kindly request you to consider extending the API to allow for this kind of customization. Providing this capability would open new avenues for extension development, enhancing the overall utility and user experience of VSCode.

Thank you for your time and consideration. I am hopeful that you will consider this feature request as a valuable addition to the upcoming iterations of the API.

Best regards,
Ranamzes

**Comment by sandy081** [comment]
A user can customise these icons by toggling their visibility and dnd the positions.
