### ISSUE TITLE
Reindent command should not modify HEREDOC

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode#19227]
Testing #19091

- have a ruby file:
```ruby
expected_result = <<HEREDOC
This would contain specially formatted text.
  This indent is important

That might span many lines
HEREDOC
```
- invoke 'Reindent lines'
- the indent inside the here doc is removed

**Comment by rebornix** [comment]
For this one we may need to leverage onEnterRules or have a new indentation rule called `undentNextLine` or something similar.

**Comment by aeschli** [comment]
To me it seems that this shows the limits of the smart editing indent rules. They were originally designed to be a editing help when adding a new line. Now the 'reindent all lines' uses them on existing code, changing potentially thousand lines of code, putting more pressure on the rules to be complete and correct in every case.
I'd suggest to rather use the formatter to implement this feature. Formatter are typically implemented based on language specific scanners and parsers, and have a full understanding of the syntax.
For editing indent rules to have the same correctness, the regexes become very complex, hard to maintain and a duplication of the language scanner and parser.
Note also that smart editing indent rules by design have to run in the UI process, so adding too much complexity on the regexp is problematic.

**Comment by alexandrudima** [comment]
@aeschli 

Language experiences in VS Code fall into two classes:

### Languages backed up by a smart language server
These languages include: TypeScript, Go, CSS, etc. etc.
As a user in these languages I have Format Selection, Format Document, Format on Type, Format on Paste and Format on Save to help me format my code

### The long tail
e.g. Ruby, Bash, etc.
As a user in these languages I don't have any Format, therefore this Reindent command targets these languages.

### Discussion
The Reindent command is of course severely limited, but it can go quite far (in a way, it is similar to our tokenization that cannot do proper type colorization, but it can go quite far). It cannot be held to the same accountability as a Format action implemented via an AST.

How we could make this clear to end users, how to improve these indent rules, if we should "hide" the Reindent command from languages with a format provider, is of course something that needs to be investigated, but nobody is working on a Ruby language server AFAIK, so perhaps "something" is better than "nothing" in these cases.

**Comment by aeschli** [comment]
The problem of 'reindent all lines' is with big files where it touches a lot of lines. As with the example above it changes the semantics of the program, by adding whitespace into a string literal.
That's fine if it happens on one line, right in from of you eyes, but is a problem if it happens on line 5000 and you don't use any SCM.

**Comment by rebornix** [comment]
Let's track this issue in https://github.com/microsoft/vscode/issues/19847 .
