### ISSUE TITLE
Documentation: error on "Tips & Tricks" page

### ISSUE THREAD

**Issue by mikeriepe** [microsoft/vscode#192231]
Type: <b>Bug</b>

How do you want us to point out mistakes in the VSCode documentation?  I suggest you have a "docs" option in the "File on" category menu to distinguish them from functionality issues.  And/or a button for feedback directly on the doc page.

I see an error in the Tips & Tricks page (https://code.visualstudio.com/docs/getstarted/tips-and-tricks).  Under the "Getting started" header, it refers to the Help->Get Started menu to find the overview.  But no such option exists under the Help menu in the latest v1.81.1 version.  It seems to have moved to Help->Welcome, and the screen differs from the screenshot on the page.  This is confusing.

VS Code version: Code 1.81.1 (6c3e3dba23e8fadc360aed75ce363ba185c49794, 2023-08-09T22:22:42.175Z)
OS version: Windows_NT x64 10.0.19045
Modes:
Connection to 'ssh-remote+fe27.achronix.local' could not be established
Remote OS version: Linux x64 3.10.0-1160.6.1.el7.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|12th Gen Intel(R) Core(TM) i7-1265U (12 x 2688)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.44GB (16.05GB free)|
|Process Argv|--crash-reporter-id c9c2d243-860c-4a75-a60a-b21270e53001|
|Screen Reader|no|
|VM|0%|

Connection to 'ssh-remote+fe27.achronix.local' could not be established

|Item|Value|
|---|---|
|Remote|SSH: fe27.achronix.local|
|OS|Linux x64 3.10.0-1160.6.1.el7.x86_64|
|CPUs|Intel(R) Xeon(R) CPU E5-2690 v2 @ 3.00GHz (8 x 2999)|
|Memory (System)|31.39GB (16.80GB free)|
|VM|0%|
</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
remote-ssh|ms-|0.102.0
remote-ssh-edit|ms-|0.86.0
remote-explorer|ms-|0.4.1
tcl|ras|0.1.0
doxdocgen|csc|1.4.0
perforce|mjc|4.15.7
cmake-tools|ms-|1.15.31
cpptools|ms-|1.17.5
cpptools-extension-pack|ms-|1.3.0
makefile-tools|ms-|0.7.0
veriloghdl|msh|1.13.0
rainbow-brackets-2|tej|1.1.0
cmake|twx|0.0.17

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263cf:30335440
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
vscccc:30803845
2e4cg342:30602488
f6dab269:30613381
2i9eh265:30646982
showlangstatbar:30737416
03d35959:30757346
pythonfmttext:30731395
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
pythonnosmt12:30797651
pythonidxpt:30805730
pythonnoceb:30805159
dsvsc013:30795093
dsvsc014:30804076
diffeditorv2:30821572

```

</details>

**Comment by gjsjohnmurray** [comment]
One way is to use the pencil icon on the page to create a PR containing the correction.

Another is to open an issue at https://github.com/microsoft/vscode-docs

**Comment by mikeriepe** [comment]
Thanks John!  I didn't notice the edit button.  I should have known this
would be markup.  I submitted a PR.  You can close this issue.

**Comment by gjsjohnmurray** [comment]
That's good. I don't have the power to close your issue here, but you do.

**Comment by mikeriepe** [comment]
done
