### ISSUE TITLE
Editor drop-down not working in no-tabs mode

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#19232]
- VSCode Version: Code - Insiders 1.9.0-insider (4265f5e35cb3ea8ba7e0cf6b14ec606b6f8647ea, 2017-01-24T10:29:13.076Z)
- OS Version: Darwin x64 15.6.0
- Extensions: None

Steps to Reproduce:

1. Switch to no-tabs mode
2. Open two files
3. Click on editor title bar
4. Expect: Open Files drop-down, actual: it is not shown

**Comment by bpasero** [comment]
@chrmarti I cannot reproduce, any more hints?

![image](https://cloud.githubusercontent.com/assets/900690/22279077/975dc0de-e2c8-11e6-82ea-cf10c186d119.png)

**Comment by chrmarti** [comment]
Yes, I wasn't specific enough. I don't mean the context menu. I meant the drop-down when you left-click on the editor's title `window.ts`. That used to open the Quick Open drop-down (works in 1.8).

**Comment by bpasero** [comment]
I see it 👍
