### ISSUE TITLE
Improve Comments accessibility 

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#192377]
- [x] Indicate when a document has commentable ranges
  - Aria status when a document is opened
- [x] Add keyboard shortcut for adding a comment
- [x] Provide commands to go to next and previous commentable range
- [ ] Add an accessible help menu to the comment widget
  - Esc dismisses widget
  - Lists go to next/previous commentable range commands + keyboard shortcuts
  - Lists command and keyboard shortcut to add a comment
  - Lists keyboard shortcut to execute the comment primary action and what the primary action is
- [x] The Comments view should respect the enter/space = reveal+focus/reveal
- [x] Make the comment widget toolbar always visible when in screen reader mode

**Comment by joaomoreno** [comment]
Related to https://github.com/microsoft/vscode-pull-request-github/issues/1930

**Comment by alexr00** [comment]
https://github.com/microsoft/vscode/pull/193420 is the last part of this, and it's almost done!

**Comment by MeekeawandNoppakun** [comment]
62521176 Mr.KITSANAPAN MEEKEAW
