### ISSUE TITLE
uncaught exception from ProxyChannel.fromService

### ISSUE THREAD

**Issue by mroch** [microsoft/vscode#192365]
this code requires that `IServerChannel.call` returns a promise:

https://github.com/microsoft/vscode/blob/9c17df54bd27cf9976e30a09749519bfc4e3a815/src/vs/base/parts/ipc/common/ipc.ts#L420-L428

otherwise, the `then()` call fails. in the example below, it returns `undefined`, which does not have a `.then` property.

but `ProxyChannel.fromService` is unsound. it is typed to return a Promise, but if `target()` doesn't return a promise then its return type is a lie:

https://github.com/microsoft/vscode/blob/9c17df54bd27cf9976e30a09749519bfc4e3a815/src/vs/base/parts/ipc/common/ipc.ts#L1108-L1123

this `ProxyChannel.fromService` is a problem:

https://github.com/microsoft/vscode/blob/9c17df54bd27cf9976e30a09749519bfc4e3a815/src/vs/code/node/sharedProcess/sharedProcessMain.ts#L398-L400

because it has methods that don't return promises:

https://github.com/microsoft/vscode/blob/9c17df54bd27cf9976e30a09749519bfc4e3a815/src/vs/platform/telemetry/common/telemetry.ts#L65-L66

this leads to, in my case at least, an uncaught exception in sharedProcess.

I added this in ipc.ts and it logged this while debugging extensions:

```ts
if (!promise) {
  throw new Error(`Call returned undefined: ${request.channelName}.${request.name}(${request.arg})`);
}
```

`Call returned undefined: customEndpointTelemetry.publicLog([object Object],js-debug/launch,[object Object])`

**Comment by billti** [comment]
I've just spent quite a while debugging my own trivial extension and why it was failing to launch under the debugger to arrive at exactly this issue. Below is the call stack and some custom logging I added at the start when promise is undefined. It matches the above analysis.

```
Promise is:  undefined
channel is:  {}
request.channel name is: customEndpointTelemetry
ctx is:  window:1
request name is  publicLog
  ERR [uncaught exception in sharedProcess]: Cannot read properties of undefined (reading 'then'): TypeError: Cannot read properties of undefined (reading 'then')
    at ChannelServer.onPromise (/Users/billti/src/vscode/out/vs/base/parts/ipc/common/ipc.js:301:21)
    at ChannelServer.onRawMessage (/Users/billti/src/vscode/out/vs/base/parts/ipc/common/ipc.js:266:33)
    at UniqueContainer.value (/Users/billti/src/vscode/out/vs/base/parts/ipc/common/ipc.js:217:73)
    at Emitter._deliver (/Users/billti/src/vscode/out/vs/base/common/event.js:891:26)
    at Emitter._deliverQueue (/Users/billti/src/vscode/out/vs/base/common/event.js:902:22)
    at Emitter.fire (/Users/billti/src/vscode/out/vs/base/common/event.js:925:22)
    at MessagePortMain.fn (/Users/billti/src/vscode/out/vs/base/common/event.js:455:44)
    at MessagePortMain.emit (node:events:513:28)
    at MessagePortMain._internalPort.emit (node:electron/js2c/utility_init:2:367)
    at Object.callbackTrampoline (node:internal/async_hooks:130:17)
```

**Comment by billti** [comment]
Note: Turns out the extension was failing for a different reason, but this error led me on a wild goose chase for quite a few hours thinking it was the problem, so would be good to fix :)

**Comment by bpasero** [comment]
@mroch @billti good findings, would you like to contribute a PR with a fix? Maybe here we should check on the return type and wrap into a `Promise` if not already one?

https://github.com/microsoft/vscode/blob/e95fca143d86caba79d31565ecdd5aae1a0600f9/src/vs/base/parts/ipc/common/ipc.ts#L1132
