### ISSUE TITLE
How should dropdown buttons work?

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#192379]
In SCM, we have a dropdown button that executes the action when you choose an action from a dropdown:

![image](https://github.com/microsoft/vscode/assets/38270282/e9a245ab-5bd6-445c-8700-88cc1ebcc79c)

In the GitHub Pull Request and Issues extension, we have a similar button, which until recently behaved differently: when you choose an action from the dropdown, the action associated with the button changes and then you must click the button to execute the action (https://github.com/microsoft/vscode-pull-request-github/issues/3785). I recently changed this to match the behavior in SCM.

There has been discussion around which approach is better. @joaomoreno, @bpasero, and @hediet I know you all had feedback on this.

**Comment by bpasero** [comment]
Maybe for me its more about how we show the additional options to pick from. Doing it in a menu to the side (I am on macOS) makes me feel I am not triggering the action when I select one.

**Comment by chenasraf** [comment]
Definitely prefer changing the button state than immediately activating the effect, for these reasons:

1. Confirmation - to be sure you want to activate it now, especially for destructive actions such as pushing commits
2. Some button states might change a leading or trailing form element, for example resetting a form field or removing irrelevant fields, adding an info box, changing a form label or info box content, etc... I am speaking generally, not for this specific case
3. Maybe there need to be extra warnings or caveats to consider, I would expect to be able to see them before my selection is final

**Comment by bpasero** [comment]
Btw one thing that is also quite important: you cannot undo this operation. In Word for example, from the dropdown - even if it triggers the action immediately - it is easy to undo a formatting change. 

So maybe the rule needs to be if an operation can easily be undone or not.

**Comment by alexr00** [comment]
I haven't gotten any feedback from users of GHPRI outside the team that the single click behavior is confusing. I would also say that in both SCM and in the GitHub Pull Requests and Issues extension, the button doesn't change a default, it just causes the action to be taken. Then, the button keeps your most recently used action for ease of use next time. 

Right now, we are consistent between SCM and GHPRI. I would wait and see if we have other users notice and ask for a change.

**Comment by alexr00** [comment]
I have since had one user notice, and they were happy with my explanation that it was to reduce clicks. Closing, as we've been consistent here for a couple months now.
