### ISSUE TITLE
I get signed out all the time

### ISSUE THREAD

**Issue by Atair1** [microsoft/vscode#192397]
Type: <b>Bug</b>

I get signed out all. the. time. I did a fresh install - deleted all things hidden away in library folders and whatnot.. still the same.. and on top of that, the new C# Dev Kit somehow logs me in with a different account using the same email.. I have only one account at microsoft, yet i see two in the settings. 

But this is unrelated to the log-outs because it happened before i had to migrate to the dev kit.. (had to, because unity)

VS Code version: Code 1.81.1 (Universal) (6c3e3dba23e8fadc360aed75ce363ba185c49794, 2023-08-09T22:20:33.924Z)
OS version: Darwin arm64 22.6.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Max (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|3, 2, 2|
|Memory (System)|32.00GB (0.87GB free)|
|Process Argv|--crash-reporter-id 5f158cb4-4820-441c-a747-d7a9b79cd830|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
github-markdown-preview|bie|0.3.0
markdown-checkbox|bie|0.4.0
markdown-preview-github-styles|bie|2.0.2
phpserver|bra|3.0.2
shaderlabformatter|lit|0.4.3
processing-vscode|Luk|2.5.1
theme-monokai-pro-vscode|mon|1.2.1
csdevkit|ms-|0.4.10
csharp|ms-|2.0.436
vscode-dotnet-runtime|ms-|1.7.2
autopep8|ms-|2023.6.0
python|ms-|2023.14.0
vscode-pylance|ms-|2023.8.50
LiveServer|rit|5.7.9
vstuc|vis|0.9.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscorecescf:30445987
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
py29gd2263cf:30792227
vscaat:30438848
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
vscccc:30803845
2e4cg342:30602488
f6dab269:30613381
a9j8j154:30646983
showlangstatbar:30737416
0bi6i642:30823812
03d35959:30757346
57b77579:30736110
pythonfmttext:30731395
9b8hh234:30694863
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
pythonnosmt12:30797651
pythonidxpt:30805730
pythonnoceb:30805159
dsvsc013:30795093
dsvsc014:30804076
diffeditorv2:30821572

```

</details>

**Comment by Atair1** [comment]
Thanks for the reply, but - i had this for months - daily 10x.. and suddenly its not happening anymore! I don't know if it was the latest update yesterday, or maybe even that i clicked 'Report Issue' and that did some redirect to github.. no Idea.
But i swear it was all the time, and now not once in the last 20 hours!

**Comment by TylerLeonhardt** [comment]
Glad to hear you're unblocked! If you see this again, don't hesitate to reach back out!
