### ISSUE TITLE
git.stageChange shortcut does not work

### ISSUE THREAD

**Issue by KenMSK** [microsoft/vscode#192399]
Does this issue occur when all extensions are disabled?: No

- VS Code Version: 1.81.1
- OS Version: MacOS 12.4

Steps to Reproduce:

1. Create a keyboard shortcut for git.stageChange command (ensure that there is no duplicate shortcut mapping)
2. Trigger the change compare editor
3. Use the shortcut for git.stageChange
4. The `Stage Change(Shift+Cmd+C)` is shown on mouse hover, but on pressing the keyboard shortcut, it does nothing.

![Screenshot 2023-09-07 at 19 44 13](https://github.com/microsoft/vscode/assets/51538854/ee38a923-1d90-409c-b38b-dba606144352)
![Screenshot 2023-09-07 at 19 50 33](https://github.com/microsoft/vscode/assets/51538854/7cb4328f-8429-4f22-a312-0413a2593169)

**Comment by helperman** [comment]
Duplicate:  #136387

**Comment by JoraGevorgyan** [comment]
I'm interested in fixing this issue. If someone can guide me or provide some pointers, I'd love to work on it.
