### ISSUE TITLE
Hover popups are getting obnoxious and can not be disabled.

### ISSUE THREAD

**Issue by tyler-stark-MRI** [microsoft/vscode#192351]
Type: <b>Bug</b>

1. Open a terraform (.tf) file and begin editing it.
2. Use the concat() function
3. Get a hover popup explaining what concat does, in spite of all hover being disabled in settings.

I have disabled every hover-related popup and have still not gotten rid of the hover popups offering """"useful""" information about the code I'm writing. What's worse is they persist even as I continue typing, forcing me to hit escape to get rid of it... until I start a new line, and then it comes back. It specifically seems to be the "concat" popup that is bugged, though maybe that's related to my code rather than the part of vscode that's screwing up.

VS Code version: Code 1.81.1 (6c3e3dba23e8fadc360aed75ce363ba185c49794, 2023-08-09T22:22:42.175Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz (8 x 2611)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.71GB (5.31GB free)|
|Process Argv|--crash-reporter-id dde7165b-1a54-4099-ad11-81ec49e26022|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
terraform|has|2.27.2
remote-wsl|ms-|0.81.2
azure-account|ms-|0.11.5
indent-rainbow|ode|8.3.1
vscode-yaml|red|1.14.0
vscode-pets|ton|1.25.0
vscode-todo-highlight|way|1.0.5

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263cf:30335440
vscorecescf:30445987
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
py29gd2263cf:30792227
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyonecf:30548226
vsccc:30803844
2e4cg342:30602488
89544117:30613380
a9j8j154:30646983
showlangstatbar:30737416
0bi6i642:30823812
03d35959:30757346
57b77579:30736110
pythonfmttext:30731395
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
pythonnosmt12:30797651
pythonidxpt:30805730
pythonnoceb:30805159
dsvsc013:30795093
dsvsc014:30804076
diffeditorv1:30821571
dsvsc015:30829745

```

</details>

**Comment by aiday-mar** [comment]
Hi, thank you for filing the issue. Could you please add a snapshot of the hover popup you are referring to? You may be seeing the suggest widget.

**Comment by tyler-stark-MRI** [comment]
> Hi, thank you for filing the issue. Could you please add a snapshot of the hover popup you are referring to? You may be seeing the suggest widget.

Yes, absolutely:
![vscode popup](https://github.com/microsoft/vscode/assets/107651483/766edb63-dd4a-4249-a43b-250b7fdf4622)

**Comment by ArturoDent** [comment]
Those might be `parameter hints`, which can be disabled in the settings.

**Comment by aiday-mar** [comment]
@ArturoDent, thanks for the help. Indeed it appears so. Could you please turn off `editor.parameterHints.enabled` in your settings? This should solve your issue.

**Comment by tyler-stark-MRI** [comment]
Yep, that seems to have done the trick! Thank you for the help.
