### ISSUE TITLE
wslServer.sh stays running after vscode closes

### ISSUE THREAD

**Issue by zyrain** [microsoft/vscode#192318]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.81.1
- OS Version: Linux nixos 5.15.90.1-microsoft-standard-WSL2 #1 SMP

The closed issue here: https://github.com/microsoft/vscode/issues/183086#issue-1718692746
is still happening on my machine:

> ps ef

>    PID TTY      STAT   TIME COMMAND
>  12306 pts/14   Ss+    0:00 sh /mnt/c/Users/Neal/.vscode/extensions/ms-vscode-remote.remote-wsl-0.81.2/scripts/wslServer.sh 6c3e3dba23e8fadc360aed75ce363ba185c49794
>  12323 pts/14   S+     0:00  \_ sh /home/zyrain/.vscode-server/bin/6c3e3dba23e8fadc360aed75ce363ba185c49794/bin/code-server --host=127.0.0.1 --port=0 --connection-t
> 12327 pts/14   Sl+    0:00      \_ /home/zyrain/.vscode-server/bin/6c3e3dba23e8fadc360aed75ce363ba185c49794/node /home/zyrain/.vscode-server/bin/6c3e3dba23e8fadc36
>  12378 pts/14   Sl+    0:00          \_ /home/zyrain/.vscode-server/bin/6c3e3dba23e8fadc360aed75ce363ba185c49794/node /home/zyrain/.vscode-server/bin/6c3e3dba23e8fa
>  11161 pts/5    Ss+    0:00 sh /mnt/c/Users/Neal/.vscode/extensions/ms-vscode-remote.remote-wsl-0.81.2/scripts/wslServer.sh 6c3e3dba23e8fadc360aed75ce363ba185c49794
>  11178 pts/5    S+     0:00  \_ sh /home/zyrain/.vscode-server/bin/6c3e3dba23e8fadc360aed75ce363ba185c49794/bin/code-server --host=127.0.0.1 --port=0 --connection-t
>  11182 pts/5    Sl+    0:01      \_ /home/zyrain/.vscode-server/bin/6c3e3dba23e8fadc360aed75ce363ba185c49794/node /home/zyrain/.vscode-server/bin/6c3e3dba23e8fadc36
>  11943 pts/5    Sl+    0:00          \_ /home/zyrain/.vscode-server/bin/6c3e3dba23e8fadc360aed75ce363ba185c49794/node /home/zyrain/.vscode-server/bin/6c3e3dba23e8fa

Steps to Reproduce:

1.  Launch code from WSL command line
2.  Quit code
3.  ps shows the pts still running

**Comment by aeschli** [comment]
The server only stays for around 5 more seconds, to handle window reloads.

I verified this using the latest build.
