### ISSUE TITLE
Poorly rendered fonts on the welcome screen

### ISSUE THREAD

**Issue by rodrigoreis** [microsoft/vscode#192301]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 
Version: 1.81.1
Commit: 6c3e3dba23e8fadc360aed75ce363ba185c49794
Date: 2023-08-09T22:18:39.991Z
Electron: 22.3.18
ElectronBuildId: 22689846
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Linux x64 6.2.0-32-generic

- OS Version: 
Ubuntu 23.04 (lunar) Linux x64 6.2.0-32-generic

Steps to Reproduce:

1. Just open vscode

Evidence:

Without extensions:
![image](https://github.com/microsoft/vscode/assets/324262/fa5a3e7f-811e-4e02-af1c-f2889a5e61e2)

With extensions:
![image](https://github.com/microsoft/vscode/assets/324262/8d9cae3f-1b1c-418c-a7bb-622cd1de3090)

**Comment by bhavyaus** [comment]
This should be fixed in more recent builds
