### ISSUE TITLE
Easy way to Open file (in edit mode) from the Changes (Diff) View

### ISSUE THREAD

**Issue by jimkring** [microsoft/vscode#192345]
I would like an easy way to open a file for editing, when I am in the "Changes" view for the file.  Often, I will open a file to show changes and I cannot edit the file because it's a read-only view of Staged changes.  I would expect an easy way to open the project file so that I can edit it. However, it's quite cumbersome -- I have to navigate into the Explorer View of the project files and then open it from there.  Why not a right-click open on the Changes tab to Open the file in the editor?  Right now, it's two steps: "Reveal in Explorer View" then open the file.  Why not just "Open" or "Open to the Side"?

**Comment by IllusionMH** [comment]
Jus in case: There is Open in editor button in toolbar in tabs row. It would open file in editor with cursor in same position.

**Comment by jimkring** [comment]
@lszomoru thank you for working on this. Can you share a little about the status? I only see it was marked as “completed” but no git commits/PRs etc.  thanks!

**Comment by lszomoru** [comment]
@jimkring, sorry about that. I did post a comment but for some reason I am not seeing it in the history.

Each resource in the "Staged Changes" and "Changes" group contain an action in the action bar that appears on the right hand side of each row to "Open File". One can use that action to open the file in the normal editor. You can also use the `git.openDiffOnClick` setting to control whether to open a resource in the diff editor or normal editor when you click on it. Do let me know if this does not address your needs. Thanks!

**Comment by jimkring** [comment]
@lszomoru. Thanks for the explanation and it'll be very helpful to my use of vscode.

From a usability perspective, it would be great to *also* have something more "front and center" -- I'm an experienced developer and I could not figure out how to easily get from the Diff tab to the Editor tab for a file in my project.

For example, what I would love is something easy like in PyCharm where I can easily open the file in the editor when navigating through the diffs  (and, I believe this is also what @IllusionMH was referring to, when he said he wanted an "Open in editor button in toolbar in tabs row".)

![Screen Shot 2023-09-07 at 9 12 38 AM](https://github.com/microsoft/vscode/assets/381432/8cdf0edf-a3b7-460e-ab2c-d8ab2d9c0baf)

**Comment by IllusionMH** [comment]
Yep, VS Code has this Open file button right next to Previous/Next Change buttons
![image](https://github.com/microsoft/vscode/assets/1312662/50d12fad-623f-4791-831c-e6901ce3bdf0)
Screenshot for staged file

**Comment by jimkring** [comment]
OK, that's great! I guess I missed that completely!  Thanks a bunch.
