### ISSUE TITLE
Allow having more than 3 code windows open simultaneously

### ISSUE THREAD

**Issue by bryanwinstead** [Microsoft/vscode#19230]
This limitation seems fairly arbitrary, and when working with "skinnier?" files it'd be nice to have more than 3 open at once. Especially with ultra-wide monitors.

**Comment by ZombieProtectionAgency** [comment]
I think you mean editor groups, not code windows. 

Anywho, based on the discussion on issue #1749 (and these, specifically, https://github.com/Microsoft/vscode/issues/1749#issuecomment-252752464 and https://github.com/Microsoft/vscode/issues/1749#issuecomment-243729311) I would assume they were already considering more than three. It looks like they planned on all of the group-related features in steps.

**Comment by mousetraps** [comment]
Yep, I know for a fact, you can open *way* [more than just three windows](https://github.com/Microsoft/vscode/issues/16882) :wink:.

But I think I get what you're saying. Do https://github.com/Microsoft/vscode/issues/2686 or https://github.com/Microsoft/vscode/issues/367 cover this scenario, or do you feel like this is something different?

**Comment by bryanwinstead** [comment]
I'm not sure the technical term for the UI item, but if you click "split editor" you can only make 3 different editor panes. I would like that limit to be larger.

**Comment by ZombieProtectionAgency** [comment]
@mousetraps As far as I understand their request I dont think either of those issues cover this one.

They just dont like the static limit of three EditorGroups. 

It would be great if you could split the editor three (or more) times for four (or more) groups, especially for larger monitors. Like this.
![image](https://cloud.githubusercontent.com/assets/9204874/22343587/ab424b98-e3c6-11e6-91de-e0565b6f8d30.png)

In addition to https://github.com/Microsoft/vscode/issues/14909 the grouping would be amazing.

**Comment by mousetraps** [comment]
Gotcha, thanks for the additional detail! cc @bpasero

**Comment by bpasero** [comment]
This issue has already been reported. Please use the search function next time before reporting an issue and/or this time if you are curious about the progress of the issue.

**Comment by ZombieProtectionAgency** [comment]
If you dont mind me asking @bpasero, what issue #? I actually looked around before i replied because I assumed it would be a duplicate but I couldnt find one that matched.

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/10859, https://github.com/Microsoft/vscode/issues/2105, https://github.com/Microsoft/vscode/issues/9872
