### ISSUE TITLE
IntelliSense filtering has become slow again in huge lists

### ISSUE THREAD

**Issue by Wosi** [Microsoft/vscode#1923]
Copied from the inital issue (https://github.com/Microsoft/vscode-extensionbuilders/issues/80)

>
Let's see this scenario:
 - The cursor is placed on whitespace inside a method
 - The user asks for completions by pressing `CTRL + Space`
 - The language service is being asked to provide all suggestions
 - The suggestion box pops up containing all 20k symbols
 - The user types the character `f`
 - **VSCode hangs for ~8 seconds** until the letter is displayed and the suggestion box shows only suggestions containing an `f`. (VSCode doesn't ask for suggestions twice. All the time is spent outside the language service. )
 - typing the next letter is being processed faster but it's still slow. 

@joaomoreno fixed this issue on 2015-11-06 telling that there were too many event listeners. With the December update it has become slow again. VSCode hangs now for **~10 seconds** working on the same suggestion list. 
I really hope it's going to be fast again with the January update. It's not funny to work in huge projects now.

**Comment by joaomoreno** [comment]
I can't really reproduce the 10 second hang on a 20k suggestion filter, but I do see some slowness. More like 1-2 seconds here.

**Comment by Wosi** [comment]
May be it has something to do with the camel case smart search? I face the slowdowns with OmniPascal (case insensitive language and all symbols use PascalCase or UPPER_CASE).

With JavaScript I can reproduce it with a hang of ~5 seconds using the following file: https://gist.github.com/Wosi/0487f72965a26de07c92 

See the instructions in the comments. The speed of filtering depends strongly on the typed characters. Filtering for "2" is very slow in this case.

**Comment by joaomoreno** [comment]
Excellent, I can now reproduce, thanks for the sample!

**Comment by Wosi** [comment]
Here is a much slower real world example: https://gist.github.com/Wosi/9603b02b0fc4268abc16

**Comment by alexandrudima** [comment]
This is almost blocking my selfhosting:

Here I am typing "_updateMatchesCount"

![image](https://cloud.githubusercontent.com/assets/5047891/12513642/98dc25c2-c127-11e5-8f74-5e3ee777f7ae.png)

![image](https://cloud.githubusercontent.com/assets/5047891/12513691/d2219e0c-c127-11e5-9f61-d94254792ed9.png)

**Comment by alexandrudima** [comment]
Here is a saved profile
[CPU-20160125T170756.cpuprofile.txt](https://github.com/Microsoft/vscode/files/103378/CPU-20160125T170756.cpuprofile.txt)

**Comment by joaomoreno** [comment]
We might have to move from `localeCompare(label, otherLabel)` to `label < otherLabel ? -1 : 1` for comparisons.

**Comment by joaomoreno** [comment]
Did a bunch of optimisations:

- moved the sorting and filtering out of the tree and into the model
- dropped `localeCompare` in favour of `<` and `>`
- moved cleanup of suggestions to happen on `hide` instead of `show`
- added a heuristic on whether the diff algorithm should run
- added another heuristic on whether the diff algorithm results should be used at all
- cached the previous list of suggestions for quicker narrowing down
- tightened the heuristic for camel case suggestions

@Wosi it would be cool if you could give it a try, building from our sources. Both your examples take just under 1 second on my machine now.

I have a few more ideas of how to make this faster, by dropping a lot of the tree machinery and just implementing a virtual list, but this'll do for now.

**Comment by alexandrudima** [comment]
Thank you, can't wait to try them out :heart:

**Comment by Wosi** [comment]
@joaomoreno First of all: **Thank you!** When the real world example runs in under a second then it's a powerful improvement. Unfortunately I can't build VSCode from source **and** check it against the real world project until wednesday evening. Since the insider channel will be updated tomorrow I think it's better to test against the insider build, isn't it? I'll give you feedback as soon as possible!

P.S: The real world example is a full adaptation of the completion items I receive from the OmniPascal language service to JavaScript. So it's  a good indicator when it works nicely now.

**Comment by joaomoreno** [comment]
@Wosi sure, let's do that then!

Here are my results on the real world example, when triggering Intellisense and then typing `abcde`.

The first peak is the trigger and takes `526ms`. Second peak is the `a` and takes `886ms`. Third peak is the `b` and goes for `543ms`. The rest of the letters are pretty much instant.

![image](https://cloud.githubusercontent.com/assets/22350/12575612/1c263b50-c40e-11e5-907e-cf4e89b9217e.png)

**Comment by dbaeumer** [comment]
With the test case from https://github.com/Microsoft/vscode/issues/1923#issuecomment-171665362 I see a ~ 1 second delay

**Comment by Wosi** [comment]
Sorry, I wasn't able to setup a proper dev environment in order to build VSCode on my own.
I see a ~ 1 second delay with the insiders build, too.

Thanks a lot! it's a big improvement even though it's still not working fluently.

**Comment by joaomoreno** [comment]
@Wosi I'm currently working on a separate widget implementation for this. :+1:

**Comment by joaomoreno** [comment]
Given the changes in #2702, here are some updated results: `237ms` for the first letter, `86ms` for the second, `29ms` for the third, etc... :+1: 

![screen shot 2016-02-08 at 16 23 10](https://cloud.githubusercontent.com/assets/22350/12889660/44510638-ce80-11e5-9105-9ad3e6520c83.png)

**Comment by Wosi** [comment]
Awesome! Good job, @joaomoreno!

**Comment by nrj** [comment]
I'm still seeing really long load times on version 1.0.0 when using as my external editor for Unity. For example triggering IntelliSense via hotkey with my cursor at the end of `Mathf.Clamp` takes 8 seconds to offer me suggestions. Consecutive invocations do not get any faster.

**Comment by dbaeumer** [comment]
@joaomoreno moving back to you to response to additional comments.

**Comment by nrj** [comment]
[
![screen-shot-2016-04-21-at-10 44 28](https://cloud.githubusercontent.com/assets/149472/14703103/50591814-07ae-11e6-89ae-784642f1cf1a.png)
](url)

Even a variable in the same scope takes ~5 seconds of loading.

**Comment by Wosi** [comment]
@nrj Your screenshot shows the initial loading process for code completion which is handled by a plugin. VSCode's internal code completion filtering (= the topic of this ticket) takes place after the plugin has delivered the suggestion items. The bahviour you are facing seems to be an issue of the plugin which provides the code completion (I guess it's OmniSharp).

**Comment by joaomoreno** [comment]
Thanks @Wosi, you are absolutely right.

@nrj You should file an issue to the page of the extension which provides those suggestions.
