### ISSUE TITLE
Emmet expansions: implicit tag names not expanding correctly

### ISSUE THREAD

**Issue by stevencl** [Microsoft/vscode#19236]
Found while testing: https://github.com/Microsoft/vscode/issues/19079

- VSCode Version: 1.9.0 4265f5e3
- OS Version: Mac Sierra

Steps to Reproduce:

1. Inside an html file, enter the following emmet expression: ul>.class then press tab
2. Expect:

```
<ul>
    <li class="class"></li>
</ul>
```
Actual: 
```
<ul>
    <li class></li>
</ul>
```

**Comment by ramya-rao-a** [comment]
This is an upstream issue with emmet itself

**Comment by ramya-rao-a** [comment]
This issue was moved to emmetio/emmet#481
