### ISSUE TITLE
Test failure in NotebookRendererMessaging: 43 leaking disposables

### ISSUE THREAD

**Issue by alexdima** [microsoft/vscode#192342]
This just failed for a PR which was unrelated. On a retry, it passed

https://dev.azure.com/vscode/VSCode/_build/results?buildId=102654&view=logs&j=f3dd96f0-7bf9-51c6-1e87-22c4cfa2ad69&s=96ac2280-8cb4-5df5-99de-dd2da759617d&t=dc9350bd-9972-5ec1-4dbd-7003b29c63a7&l=12256

**Comment by rebornix** [comment]
Based on offline discussion with Connor, this can happen before we ensure all disposables are tracked in tests.
