### ISSUE TITLE
Build task status indicator not reappearing on window reload

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#192398]
Steps to Reproduce:

1.  I use the default build task in `vscode` on a multi root workspace
2. I see a "2" appearing in the status bar, indicating the 2 runs (see pic [1])
3. I reload the window
4. everything is fine
5. I open 2 more terminals (see pic [2])
6. I hide the panel
7. I reload window

=> 🐛 there is no more a "2" in my status bar

[1]

![Image](https://github.com/microsoft/vscode/assets/900690/8615f520-ca94-47d7-8cd9-66fdf4c77bbb)

![Image](https://github.com/microsoft/vscode/assets/900690/ad262d89-840a-414b-94df-39c88c2157d2)

[2]

![Image](https://github.com/microsoft/vscode/assets/900690/415511c3-fd68-4b3b-a29d-ae3bf259be5d)

**Comment by meganrogge** [comment]
This is slightly different

**Comment by meganrogge** [comment]
here, the number of terminals is zero.  https://github.com/microsoft/vscode/blob/c49ecf7d5c9f4ff2543ed87fa0fd4e1b4edbf1cc/src/vs/workbench/contrib/tasks/browser/abstractTaskService.ts#L351

**Comment by meganrogge** [comment]
@tyriar and I have investigated this before. The panel will need to open for this case.

**Comment by meganrogge** [comment]
@tyriar and I have investigated this in the past. the panel will need to open for this to work
