### ISSUE TITLE
Can't open VSCode anymore with UNC path mapped user

### ISSUE THREAD

**Issue by Dudeplayz** [microsoft/vscode#192302]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 
```
1.81.1
6c3e3dba23e8fadc360aed75ce363ba185c49794
x64
```
- OS Version: Windows Server 2019

Steps to Reproduce:

1. Use mapped roaming profile with unc path
2. Open VSCode
<img width="510" alt="Bildschirmfoto 2023-09-06 um 17 00 39" src="https://github.com/microsoft/vscode/assets/15174076/0f8c18c3-42ae-4a41-a21b-d066a77a41bb">

Recently everything worked, after upgrading to the latest version, VSCode can't be started anymore.
`NODE_UNC_HOST_ALLOWLIST` is set accordingly.

**Comment by bpasero** [comment]
This needs more exact steps for how to reproduce, from reading the description I have no clue how I would reproduce this on Windows. For example:
* is this a mapped network drive
* if not, why not? does it work?
* do you start with any command line arguments such as `--user-data-dir`
* is the folder writeable?
* can you try with the previous version wheather this really regressed?

**Comment by bpasero** [comment]
We have a command to test out previous builds to find the day of breakage. It will start previous releases of VS Code insiders to see where the regression was introduced:
* `npx --yes vscode-bisect@latest`
* follow the instructions until you found the offending build
* report back the commit range in this issue

Thanks!
