### ISSUE TITLE
Toggle Light/Dark theme ignores user's specified themes

### ISSUE THREAD

**Issue by chambliss** [microsoft/vscode#192353]
Type: <b>Bug</b>

I have the following in my settings:

```
  "window.autoDetectColorScheme": true,
  "workbench.preferredLightColorTheme": "Bearded Theme Milkshake Mango",
  "workbench.preferredDarkColorTheme": "Bearded Theme Arc Blueberry",
  "workbench.preferredHighContrastColorTheme": "Bearded Theme Arc Blueberry",
  "workbench.preferredHighContrastLightColorTheme": "Bearded Theme Milkshake Mango",
```

However, when I use "Toggle Light/Dark theme" (without the HC theme settings), VS Code switches my theme to the default light/dark High Contrast color theme. 

I tried to fix this by setting my preferred themes for the "preferred HC themes" settings, which I previously was not using. However, this causes the toggle command to stop working completely.

See video. I recorded what happens with each combination (first with all the settings enabled, which causes nothing to happen, and second with the HC settings disabled, which causes the HC themes to be toggled). 

This feature used to work until about a month or two ago with the Bearded themes, so I'm not sure what has changed. I also used the Insider build until recently and it was not yet fixed there (in fact I first noticed this on Insider, and later switched back to Stable).

Let me know if I can produce any other logs/info that would be helpful.

VS Code version: Code 1.81.1 (6c3e3dba23e8fadc360aed75ce363ba185c49794, 2023-08-09T22:40:25.698Z)
OS version: Darwin arm64 22.6.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|7, 7, 6|
|Memory (System)|32.00GB (0.35GB free)|
|Process Argv|--crash-reporter-id 7cf80222-545f-41aa-a792-e9ef6f9755bc|
|Screen Reader|yes|
|VM|0%|
</details><details><summary>Extensions (93)</summary>

Extension|Author (truncated)|Version
---|---|---
terraform|4op|0.2.5
Bookmarks|ale|13.4.1
beardedicons|Bea|1.13.2
turbo-console-log|Cha|2.9.6
ruff|cha|2023.34.0
visubezier|chr|1.6.1
npm-intellisense|chr|1.4.4
path-intellisense|chr|2.8.4
flask-snippets|cst|0.1.3
macros|ctf|0.1.2
vscode-markdownlint|Dav|0.51.0
macos-modern-theme|dav|2.3.19
vscode-eslint|dba|2.4.2
githistory|don|0.6.20
python-environment-manager|don|1.0.4
gitlens|eam|14.2.1
vscode-html-css|ecm|1.13.1
prettier-vscode|esb|10.1.0
vscode-open-multiple-files|fab|1.4.0
figma-vscode-extension|fig|0.2.7
shell-format|fox|7.2.5
copilot|Git|1.109.388
copilot-chat|Git|0.6.0
remotehub|Git|0.60.0
vscode-github-actions|git|0.26.2
vscode-pull-request-github|Git|0.70.0
vscode-graphql|Gra|0.8.17
vscode-graphql-syntax|Gra|1.2.2
todo-tree|Gru|0.0.226
output-colorizer|IBM|0.1.2
applescript|idl|0.24.3
vscode-react-typescript|inf|1.3.1
svg|joc|1.5.3
vscode-gutter-preview|kis|0.30.0
bash-ide-vscode|mad|1.39.0
rainbow-csv|mec|3.7.0
template-string-converter|meg|0.6.1
vscode-language-babel|mgm|0.0.39
git-graph|mhu|1.30.0
fluent-icons|mig|0.0.18
dotenv|mik|1.0.1
vscode-docker|ms-|1.26.0
vscode-dotnet-runtime|ms-|1.7.2
playwright|ms-|1.0.15
black-formatter|ms-|2023.4.1
debugpy|ms-|2023.3.12121004
isort|ms-|2023.11.12061012
mypy-type-checker|ms-|2023.2.0
python|ms-|2023.15.12301911
vscode-pylance|ms-|2023.8.51
datawrangler|ms-|0.17.1
jupyter|ms-|2023.7.1002162226
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.17
vscode-jupyter-cell-tags|ms-|0.1.8
remote-containers|ms-|0.308.0
remote-ssh|ms-|0.102.0
remote-ssh-edit|ms-|0.86.0
remote-explorer|ms-|0.4.1
remote-repositories|ms-|0.38.1
vsliveshare|ms-|1.0.5883
vsliveshare-pack|ms-|0.4.0
vscode-sanddance|msr|4.1.0
gremlins|nho|0.26.0
css-grid-snippets|oha|0.0.5
htmx-tags|oto|0.0.7
vscode-versionlens|pfl|1.6.0
postman-for-vscode|Pos|0.6.2
text-power-tools|qcz|1.41.0
reactree|Rea|1.0.8
vscode-commons|red|0.0.6
vscode-xml|red|0.26.1
vscode-yaml|red|1.14.0
LiveServer|rit|5.7.9
bash-debug|rog|0.3.9
partial-diff|ryu|1.4.3
markdown-preview-enhanced|shd|0.7.3
vscode-fileutils|sle|3.10.3
cody-ai|sou|0.10.0
sourcegraph|sou|2.2.16
sass-indented|syl|1.8.27
even-better-toml|tam|0.19.2
shellcheck|tim|0.34.0
vscode-counter|uct|3.2.1
intellicode-api-usage-examples|Vis|0.2.8
vscodeintellicode|Vis|1.2.30
vscodeintellicode-completions|Vis|1.0.22
vscodeintellicode-insiders|Vis|1.1.10
vscode-icons|vsc|12.5.0
vscode-postcss|vun|2.0.2
vscode-import-cost|wix|3.3.0
pretty-ts-errors|yoa|0.5.1
vscode-proto3|zxh|0.5.5

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
vscccc:30803845
282f8724:30602487
f6dab269:30613381
a9j8j154:30646983
showlangstatbar:30737416
962ge761:30823813
03d35959:30757346
pythonfmttext:30731395
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
pythonnosmt12:30797651
pythonidxpt:30805730
pythonnoceb:30805159
dsvsc013:30795093
dsvsc014:30804076
diffeditorv1:30821571
dsvsc015:30829745

```

</details>

**Comment by chambliss** [comment]
Video:

https://github.com/microsoft/vscode/assets/43484165/62c3c4e4-7ddb-4f8f-bc53-5b6308de219a

**Comment by aeschli** [comment]
The command looks at the type of the currently configured theme and picks the opposite.
`Bearded Theme Milkshake Mango` is configured as `dark high contrast`. So when you are in Mango, we go to `preferredHighContrastLightColorTheme` which is Mango again.

btw `Bearded Theme Arc Blueberry` is marked as Dark

So I suggest to file an issue against [Bearded Theme](https://github.com/BeardedBear/bearded-theme) to correctly mark as light high constant theme.

Not sure how to improve this on our end.
We don't want to restrict the 'preferred' themes. This normally doesn't matter, except for the `toggle` command.

**Comment by chambliss** [comment]
Ah, you're right, the problem is actually specific to the Bearded themes. I tested this out with a light and dark non-Bearded theme and it works as expected. I'll close this and reopen with them. Thanks!
