### ISSUE TITLE
"Show Previous/Next Change" should set cursor

### ISSUE THREAD

**Issue by fabb** [microsoft/vscode#192389]
The actions "Show Previous Change" and "Show Next Change" are pretty handy to jump to changed but not yet committed code locations in a file. It's not nicely usable with keyboard navigation only, because it does not set the cursor to that changed code block. It's necessary to click with the mouse to set the cursor there. IntelliJ has the same feature, but it directly sets the cursor which makes it much more helpful.

**Comment by lszomoru** [comment]
@hediet, could you please take a look at this one? Thanks!

**Comment by alexr00** [comment]
To verify:
1. Open a diff
2. Use the commands "Show Previous Change" and "Show Next Change"
3. Verify that your cursor is moved to the change.

**Comment by andreamah** [comment]
[![Image from Gyazo](https://i.gyazo.com/967eda8831bf46f02f482fdeb9bdf232.gif)](https://gyazo.com/967eda8831bf46f02f482fdeb9bdf232)

This still does not set the cursor for the left side of the diff, only the right side for me.

**Comment by sandy081** [comment]
Verified with latest steps
