### ISSUE TITLE
zoom challenge

### ISSUE THREAD

**Issue by Isaaco3349** [microsoft/vscode#192370]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 
- OS Version: 

Steps to Reproduce:

1. 
2. 
![vsc](https://github.com/microsoft/vscode/assets/92901571/e8c81ba4-2f60-4115-8890-e317d73bed7f)

**Comment by Isaaco3349** [comment]
after I set my zoom level to 10, I couldn't zoom out anymore Even after reinstalling a new one and deleting the files is still glitching

**Comment by deepak1556** [comment]
zoom levels are persisted in your user data directory, you can delete them at `C:\Users\<username>\AppData\Roaming\Code`
