### ISSUE TITLE
Web: cannot right click into custom title

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#192407]
Steps to Reproduce:

1. open https://insiders.vscode.dev/ 
2. notice the custom title shows by default (probably because of command center enabled by default?)
3. right click into empty space of custom title

=> 🐛 the menu does not open (or quickly closes)

![Image](https://github.com/microsoft/vscode/assets/900690/d7eadf67-588e-43c9-8601-7e967cc227c5)

**Comment by bpasero** [comment]
Right click into the command center actually works:

![image](https://github.com/microsoft/vscode/assets/900690/38d45bf9-59f0-4d4d-ac8b-8e54183e8fd2)

**Comment by bpasero** [comment]
This seems to be caused by the following code:

https://github.com/microsoft/vscode/blob/2f1fcb0b1860caca5a0fbafef25fcb15911c7d67/src/vs/workbench/browser/parts/titlebar/titlebarPart.ts#L329-L333

**Comment by jrieken** [comment]
🙈 

<img width="951" alt="image" src="https://github.com/microsoft/vscode/assets/1794099/51f2b58f-24f4-4e58-9e27-e302cbcccf1f">

**Comment by bpasero** [comment]
When I take out that code that was added for https://github.com/microsoft/vscode/issues/30967, I can not reproduce the issue anymore. And https://github.com/microsoft/vscode/issues/30967 does not reproduce either, so maybe something changed in Chrome that `body` element no longer gets focus when clicking into an element that has no `tabIndex` 🤷
