### ISSUE TITLE
Unexpected logs in TelemetryService unit tests

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#192433]
```
  TelemetryService
    + Disposing
    + Simple event
    + Event with data
    + common properties added to *all* events, simple event
    + common properties added to *all* events, event with data
    + TelemetryInfo comes from properties
    + telemetry on by default
[15408:0907/082312.721:INFO:CONSOLE(768)] "FakeTimers: clearTimeout was invoked to clear a native timer instead of one created by this library.
To automatically clean-up native timers, use `shouldClearNativeTimers`.", source: C:\Github\microsoft\vscode\node_modules\sinon\node_modules\@sinonjs\fake-timers\src\fake-timers-src.js (768)
```

**Comment by lramos15** [comment]
Am I running these wrong? I just run them using the test UI and see no output
<img width="921" alt="image" src="https://github.com/microsoft/vscode/assets/4544166/8a37a503-81d8-40e1-9c74-c6f6b4cf05c6">

**Comment by Tyriar** [comment]
I normally run via `./scripts/test.bat` which runs everything

**Comment by lramos15** [comment]
Yeah I still can't get any console output 🤔 
<img width="921" alt="image" src="https://github.com/microsoft/vscode/assets/4544166/bf546086-e93b-42cb-b6c4-cf2600b1cea9">

**Comment by Tyriar** [comment]
I did a full run and can't see it. Likely fixed with one of the recent leak changes
