### ISSUE TITLE
VSCode warning 64 bit Windows users about deprecated 32 bit Windows support

### ISSUE THREAD

**Issue by axefrog** [microsoft/vscode#192479]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.82.0
- OS Version: Windows 10 Pro - 64 bit

My VSCode just updated this morning to 1.82.0 and now it's warning me that I won't be able to use it on Windows 32 bit anymore. Except I'm _not_ using 32 bit Windows, I'm using 64 bit Windows.

![image](https://github.com/microsoft/vscode/assets/298883/c6898685-2868-4345-bf26-7045c383acc9)

![image](https://github.com/microsoft/vscode/assets/298883/b1ef7306-b901-4f22-bf7f-603d598a80c6)
![image](https://github.com/microsoft/vscode/assets/298883/938e717f-ddc3-4692-8ba6-86ba072801c5)
![image](https://github.com/microsoft/vscode/assets/298883/49e4bbdc-4f72-4515-9279-172ee4f4e590)

**Comment by deepak1556** [comment]
Sorry the wording is definitely misleading, the notification is not about your OS but rather the application is 32-bit. You would need to switch to 64-bit version of VSCode.

/cc @joaomoreno maybe the wording can be fixed.

**Comment by axefrog** [comment]
@deepak1556  @joaomoreno It's not just the wording in the bar. Look at what you're linking people to:
![image](https://github.com/microsoft/vscode/assets/298883/d808d198-a97c-46ba-8e54-91f1a6c614b8)

**Comment by axefrog** [comment]
Also, when I go to install the x64 version, I remember why I never got around to upgrading it. It just stonewalls me with "Please uninstall the 32 bit version before upgrading to the 64 bit version". Okay... so... will I lose my settings? Will I have to resync everything? Does uninstalling leave my settings on the local machine ready for the x64 version to pick up?

**Comment by axefrog** [comment]
Cool. So I tried uninstalling and got this:
![image](https://github.com/microsoft/vscode/assets/298883/e197aa8d-4419-43ca-99cb-4a6d63989c49)

So now every time I start VSCode, I'm being nagged to upgrade and yet the entire process of resolving the issue is blanketed in friction and roadblocks.

**Comment by axefrog** [comment]
I also tried installing VSCode (x86) over the top of my current install, hoping it would restore the corrupted uninstall data, but it failed to fix the issue. And VSCode does not come with a way to repair the installation, so I'm basically out of luck.

My suggestion would be to remove the nag for now, then make sure that what you're asking people to do is actually relatively frictionless, then reintroduce the nag when that is done.

**Comment by joaomoreno** [comment]
Thanks for all your details, we really appreciate your passing!

I'm pretty sure the uninstallation issue you're hitting isn't related at all to having been on x86 all this time. We won't remove the nag since we plan on deprecating x86 in October, that means people will just stop getting updates.

As for the documentation, I think people won't have a hard time finding the 32-bit paragraph on that documentation setting. Not convinced that lot of change is required there.

As for the uninstallation suggestion, here's a change that will help keep users related: https://github.com/microsoft/vscode/pull/192993

**Comment by axefrog** [comment]
@joaomoreno Could you point me in the right direction for my issue? It's really frustrating being nagged to upgrade but being prevented from doing so, as per what I described.

**Comment by joaomoreno** [comment]
Sure. I don't think I have a better suggestion than to simply delete the `%localappdata%\Programs\Microsoft VS Code` folder. Then, go to Control Panel and try to uninstall it, it will simply remove VS Code from the list. Then you should be able to install the 64 bit version.

**Comment by axefrog** [comment]
@joaomoreno Okay, thankyou, I'll try that!
