### ISSUE TITLE
Output of localhost URLs in terminal creates unwanted port forwarding

### ISSUE THREAD

**Issue by morganwdavis** [microsoft/vscode#192485]
Does this issue occur when all extensions are disabled?: No (because that disables remote ssh access which is not a fix)

- VS Code Version: 
Version: 1.82.0 (system setup)
Commit: 8b617bd08fd9e3fc94d14adb8d358b56e3f72314
Date: 2023-09-06T22:07:07.438Z
Electron: 25.8.0
ElectronBuildId: 23503258
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0

- OS Version: 
OS: Windows_NT x64 10.0.22621

Steps to Reproduce:

1. Use VS Code Remote SSH to connect to remote server
2. In the Terminal panel, cause the server to echo a localhost URL with a port number.  Merely typing it into the command line can cause this.  Example:

`echo "https://localhost:1337"`

3. VS Code will open a forwarded port

![image](https://github.com/microsoft/vscode/assets/4434533/54a71965-8015-4ea9-a4bc-3f2abd80680a)

Editing files on the server in the terminal can cause this to occur if the editing buffer contains such URLs.

(This was discovered when using `diff` to find changes between the latest and previous versions of the VS Code server directories on a remote host. Many of the files in `.vscode-server` contain these localhost URL strings.)

**Comment by alexr00** [comment]
If you want to disable auto port forwarding all together:
```
"remote.autoForwardPorts": false
```

If you want to keep auto forwarding ports, but only want those that we can find processes (and your remote is not Windows)
```
"remote.autoForwardPortsSource": "process"
```
