### ISSUE TITLE
User Snippets not showing up in quickSuggestions

### ISSUE THREAD

**Issue by BrandonRice** [Microsoft/vscode#19244]
- VSCode Version: Code 1.8.1 (ee428b0eead68bf0fb99ab5fdc4439be227b6281, 2016-12-19T14:49:23.350Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

|Extension|Author|Version|
|---|---|---|
|html-snippets|abusaidm|0.0.18|
|vscode-color|anseki|0.2.2|
|asp|ilich8086|0.0.1|
|htmltagwrap|bradgashler|0.0.3|
|vscode-html-css|ecmel|0.0.33|
|vscode-npm-script|eg2|0.1.8|
|vs-code-xml-format|fabianlauer|0.1.4|
|beautify|HookyQR|0.7.3|
|classic-asp|ilich8086|0.0.2|
|vscode-todo|MattiasPernhult|0.8.0|
|vscode-icons|robertohuertasm|7.1.2|
|Spell|seanmcbreen|0.9.1|
|JavaScriptSnippets|xabikos|1.2.0|
|html-css-class-completion|Zignd|1.0.3|

---

Is anyone else having issues with user defined Snippets?  
I am coding in basic HTML and I have the below HTML Snippets defined:
```
"Tech Option": {
        "prefix": "techoption",
        "body": [
            "<%=strTechOut%>"
        ],
        "description": "Tech Option"
    },
    "Tech All": {
        "prefix": "techall",
        "body": [
            "<option value=\"%\">All</option>",
            "<%=strTechOut%>"
        ],
        "description": "Tech All"
    },
    "Center": {
        "prefix": "centerthis",
        "body": [
            "<Center>",
            "   ${Data}",
            "</Center>"
        ],
        "description": "Places a center tag with caller to enter data in code"
    },
    "myOption": {
        "prefix": "myoption",
        "body": [
            "<option value=${Value}>${Text}</option>"
        ],
        "description": "Places an option tag with callers to enter data in code"
    },
    "mySelect": {
        "prefix": "mySelect",
        "body": [
            "<select id=${id} name=${name} size=\"1\">",
            "   <option value=${Value}>${Text}</option>",
            "</select>"
        ],
        "description": "Places a select tag with option block including callers in code"
    },
    "myNoWrap": {
        "prefix": "myNoWrap",
        "body": [
            "&nbsp;"
        ],
        "description": "Places a no wrap tag in code"
    },
    "Validation": {
        "prefix": "Validation",
        "body": [
            "validation=${Validation}"
        ],
        "description": "Enters a validation script into code."
    },
    "MyInput": {
        "prefix": "MyInput",
        "body": [
            "<input type=${Type} name=${Name} id=${Name} value=${Value}>"
        ],
        "description": "Enters a full input tag into code."
    },
    "MyDocument":{
        "prefix": "MyDocument",
        "body": [
            "document.getElementById(${ID})"
        ],
        "description": "Enters document java tag into code"
    }
```
When I type MySel or MyIn, the autoCompletions used to show my defined Snippets and allow me to select it.  Now, my Snippets aren't even showing up. I would attach an image to this but I also just noticed that when VSCode has the focus of my mouse, my PrintScreen button doesn't work so I can't capture the auto suggestions that are appearing in the list.

**Comment by mousetraps** [comment]
@BrandonRice sounds frustrating, thanks for reaching out! Unfortunately I can't seem to reproduce the issue. Just to be absolutely, positively sure we're doing the same thing - you have additional braces around the code block you provided, correct? (otherwise it's not valid json)

Assuming everything is a-okay on that front, a couple additional Qs:
1. Does this happen for *just* html snippets, or all snippet types?
2. Does it happen in all *.html files or only some of them?

**Comment by BrandonRice** [comment]
Yes, I have extra braces around the code I sent in.

It's only happening on this one specific html file.  I tested it on 5 additional html files and the snippets work fine.  I reopen the file I'm working on updating and the snippets do not work.  Could it be an issue with the code prior to the snippets being called that is causing an error and forcing he snippets to not be triggered?

**Comment by mousetraps** [comment]
@BrandonRice Interesting. Does it work if you try changing the name of the html file? How about if you move it around? Any additional detail you could provide around what's special about this file would be awesome.

**Comment by jrieken** [comment]
@BrandonRice Please check the developer console for errors and/or share both files as they are with me. Thanks

**Comment by BrandonRice** [comment]
I'm guessing I must have had some issue with my code because I took the
time to rewrite the page and it works now.  Thank you for your time.

Thank you,

Brandon Rice
Web/Db Application Developer
Office: (817) 200-2374

**Comment by jrieken** [comment]
Ok. Thanks to getting back. Closing for now, please comment if you still see this
