### ISSUE TITLE
[WelcomeUX] Welcome page - Interface overview is tough to see in some cases

### ISSUE THREAD

**Issue by waderyan** [Microsoft/vscode#19247]
I think we need to increase the opacity of the backdrop. Its tough to see the interface overview if I have extensions open (such as when I click to install a keymap).

![image](https://cloud.githubusercontent.com/assets/2449568/22260548/7485a45a-e21e-11e6-9e87-14da6427c08e.png)

OS: Windows

**Comment by chrmarti** [comment]
Will fix with #19247.
