### ISSUE TITLE
Terminating terminal task moves focus to output panel (and doesn't terminate)

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#19243]
Testing #19057

- VSCode Version: Code - Insiders 1.9.0-insider (4265f5e35cb3ea8ba7e0cf6b14ec606b6f8647ea, 2017-01-24T10:29:13.076Z)
- OS Version: Darwin x64 16.3.0
- Extensions:

|Extension|Author|Version|
|---|---|---|
|EditorConfig|EditorConfig|0.3.4|
|lorem-ipsum|Tyriar|1.0.0|
|sort-lines|Tyriar|1.2.0|
|theme-glacier|Tyriar|0.0.10|
|vscode-svgviewer|cssho|1.3.0|
|gitlens|eamodio|1.4.3|
|git-project-manager|felipecaputo|1.0.1|
|md-navigate|jrieken|0.0.1|
|vscode-scss|mrmlnc|0.6.0|
|seti-icons|qinjia|0.1.3|

---

Related: https://github.com/Microsoft/vscode/issues/19241

Running a task in the terminal and trying to relaunch it will send focus to output and give this message:

<img width="620" alt="screen shot 2017-01-24 at 10 02 09 am" src="https://cloud.githubusercontent.com/assets/2193314/22259974/4215edb0-e21c-11e6-81ef-6d4a7b7b010c.png">

I expect the message box to appear without focus change to the output panel since I have `_runner` set to terminal. It also doesn't appear to terminate the watch task.

I was using the build task in the following file on [xterm.js](https://github.com/sourcelair/xterm.js):

```js
{
    // See https://go.microsoft.com/fwlink/?LinkId=733558
    // for the documentation about the tasks.json format
    "version": "0.1.0",
    "command": "npm",
    "isShellCommand": true,
    "showOutput": "always",
    "suppressTaskName": true,
    "_runner": "terminal",
    "tasks": [
        {
            "taskName": "install",
            "args": ["install"]
        },

        {
            "taskName": "update",
            "args": ["update"]
        },

        {
            "taskName": "test",
            "args": ["run", "test"]
        },
        {
          "taskName": "watch",
          "args": ["run", "dev"],
          "isBuildCommand": true
        }
    ]
}
```

**Comment by dbaeumer** [comment]
Dups #19267. I added the focus problem to #19267
