### ISSUE TITLE
Tree rendering cheese

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#19242]
I was scrolling up in the explorer and it gave me the following:

<img width="308" alt="screen shot 2017-01-24 at 9 49 20 am" src="https://cloud.githubusercontent.com/assets/2193314/22259511/76c35d56-e21a-11e6-9b19-1ef342ee024d.png">

After seeing this, I scrolled down to the bottom and back up and everything was fine:

<img width="245" alt="screen shot 2017-01-24 at 9 50 51 am" src="https://cloud.githubusercontent.com/assets/2193314/22259561/a9779ee2-e21a-11e6-9227-46e5ba8c7039.png">

Info on state:

- I had the following repo/commit open: https://github.com/Tyriar/xterm.js/tree/dd761bcc9dca967e6d5d190e312887bc36ce02b4
- Deps and build was done (`npm i && npm run build`)
- `lib` and `src` directories were expanded
- No errors in console

I believe I've seen this before about a week ago but it fixed itself like this and couldn't repro again.

**Comment by joaomoreno** [comment]
UGLY!

**Comment by Tyriar** [comment]
Saw this again in today's Insiders 40fecfaa77f01672e8a147be71f6f7ccb9cf8a12, I've seen it maybe 6 or so times now.

**Comment by Tyriar** [comment]
Just happened again with similar repro steps, it might be related to `npm run dev` in the project which cleans a folder and recreates all the files between `tsc` runs.
