### ISSUE TITLE
Why doesn't reflow work in test view output?

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#192438]
When I resize this down and back up again:

![Image](https://github.com/microsoft/vscode/assets/2193314/1d75b734-3f0a-4a83-b9a9-f036e4693fa7)

I see this:

![Image](https://github.com/microsoft/vscode/assets/2193314/40421dee-e3a6-4344-9619-a87e70956bed)

Why isn't reflow working here?

Does the terminal not have scrollback by chance as it will be disabled if so:

https://github.com/xtermjs/xterm.js/blob/19c760a20470c26666efad770fe82496c4a9bf1e/src/common/buffer/Buffer.ts#L292-L294

**Comment by connor4312** [comment]
Stepping into it with the debugger, it seems that reflow is enabled, and resizing it smaller gets into `_reflowSmaller`. I'm not very versed in xterm internals to see what's going on past there. Perhaps we should look at this together?

**Comment by Tyriar** [comment]
This might be because you're not printing `\r` at the end of the line 🤔. Should be a quick call if you want to go that route

**Comment by Tyriar** [comment]
Double clicking the line will tell you whether the line is correctly marked as wrapped.

**Comment by connor4312** [comment]
Yea, I think before we didn't add a line break at the end of the message. This seems to work now that we adopted `formatMessageForTerminal` (which uses CRLF) and I see that selfhost test output which uses CRLF does wrap correctly. Is this issue now fixed?

**Comment by Tyriar** [comment]
Yep, seems to be working 👍
