### ISSUE TITLE
CatCoding Webview tutorial broken

### ISSUE THREAD

**Issue by mclacore** [microsoft/vscode#192474]
Does this issue occur when all extensions are disabled?: Yes/No

- Version: 1.81.1 (system setup)
- Commit: 6c3e3dba23e8fadc360aed75ce363ba185c49794
- Date: 2023-08-09T22:22:42.175Z
- Electron: 22.3.18
- ElectronBuildId: 22689846
- Chromium: 108.0.5359.215
- Node.js: 16.17.1
- V8: 10.8.168.25-electron.0
- OS: Windows_NT x64 10.0.22621

Steps to Reproduce:

1. Go here: https://code.visualstudio.com/api/extension-guides/webview
2. Follow directions to set up CatCoding webview
3. Open command palette to run webview

Error that appears:
![2023-09-07 12_19_52-Visual Studio Code](https://github.com/microsoft/vscode/assets/8037512/e00d8d1f-6ec6-4dff-9e56-d93834de34ee)

I'm trying to follow the webview guide so I can add webview to my actual extension, and ran into the same error. Decided to just create a fresh extension and follow your guide. I think it's broken.

**Comment by mjbvz** [comment]
You can find the complete sample code here: https://github.com/microsoft/vscode-extension-samples/tree/main/webview-sample

**Comment by mclacore** [comment]
> You can find the complete sample code here: https://github.com/microsoft/vscode-extension-samples/tree/main/webview-sample

@mjbvz shocker, I cloned the repo and ran the extension without making a single modification, same error. But thanks for closing without confirming that the issue has been resolved or not.

**Comment by mjbvz** [comment]
![Screenshot 2023-09-07 at 3 26 24 PM](https://github.com/microsoft/vscode/assets/12821956/8bd432e6-d671-4bc2-b60a-4936edff4d49)

My guess is that you didn't build the extension. If you did built it but it didn't run, then check for errors in the dev tools as well

**Comment by mclacore** [comment]
> ![Screenshot 2023-09-07 at 3 26 24 PM](https://user-images.githubusercontent.com/12821956/266454406-8bd432e6-d671-4bc2-b60a-4936edff4d49.png)
> 
> My guess is that you didn't build the extension. If you did built it but it didn't run, then check for errors in the dev tools as well

https://github.com/microsoft/vscode-webview-ui-toolkit/blob/main/docs/getting-started.md#test-that-everything-works

I followed these instructions (listed in your docs) to test it and it's not working. Do you have some additional configurations in your VS Code not listed in the docs? Is that why it's working for you?
