### ISSUE TITLE
Emmet Expansion CSS exit point should be at end of inserted property

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#19246]
Test item #19079

- VSCode Version: Code - Insiders 1.9.0-insider (4265f5e35cb3ea8ba7e0cf6b14ec606b6f8647ea, 2017-01-24T10:29:13.076Z)
- OS Version: Darwin x64 15.6.0
- Extensions: None

Steps to Reproduce:

1. Start with:
```
body {
    bgsz
}
```
2. Expand after `z`
3. Type in some size
4. `<enter>`
5. Expected:
```
body {
    -webkit-background-size: 12px;
    background-size: 12px;<caret>
}
```
6. Actual:
```
body {
    -webkit-background-size: 12px<caret>;
    background-size: 12px;
}
```

Same goes for single line expansions, although there it is not as bad because it is just one arrow-left key to correct.

**Comment by chrmarti** [comment]
Another CSS example is `c:r`. Pressing `<enter>` when done should land the caret at the end of the line.

**Comment by ramya-rao-a** [comment]
This is due to the way snippets get expanded.

Take the below example of a snippet

```
"tryme": {
        "prefix": "tryme",
        "body": [
            "My name is ${0:me} What is yours?${0};"
        ]
    }
```

When you use the above in any file and after you enter the placeholder followed by ENTER, the cursor remains where the entry was made and does not go to end of line

cc @jrieken

**Comment by jrieken** [comment]
Yes, `$0` is the final cursor position which default to the end of the snippet. The sample above it is used to place the cursor elsewhere. Changing above to `...${1:me}...` should do it. http://code.visualstudio.com/docs/editor/userdefinedsnippets#_snippet-syntax

**Comment by ramya-rao-a** [comment]
@jrieken 

![image](https://cloud.githubusercontent.com/assets/16890566/24621664/214118d2-1857-11e7-8f66-abcb9497283e.png)

So the `$0` being the final cursor position is a standard behavior for snippets in general or is this VS Code specific rule?

The reason I ask is, in order to fix this bug if I make an update to https://github.com/emmetio/emmet/blob/master/lib/snippets.json then I wonder if I will be breaking any other editor that uses emmet

If it is vscode specific, then I'll make the fix on our end

**Comment by jrieken** [comment]
That's a good question. It is default Textmate behaviour but I don't know if emmet is also Textmate...

**Comment by ramya-rao-a** [comment]
emmet does borrow from text mate

https://docs.emmet.io/customization/snippets/#text-snippets

**Comment by jrieken** [comment]
Very cool!

**Comment by jrieken** [comment]
> Note that ${0} or $0 tabstop has a special meaning in some editors like TextMate or Eclipse and is used as a final caret position after leaving “tabstops mode” so you’d better use tabstops staring from 1.
