### ISSUE TITLE
Test Results view misses separator between editor and list

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#192409]
There's no separator line between the two components.

![Image](https://github.com/microsoft/vscode/assets/22350/7b85aa3e-e29c-47a9-99d1-1ae118ed330f)

**Comment by bhavyaus** [comment]
Seeing the seperator:
<img width="69" alt="image" src="https://github.com/microsoft/vscode/assets/25044782/5d04c3ec-68e3-4c9d-a4f9-80652531d63f">
