### ISSUE TITLE
[WelcomeUX] Interactive Playground - keybinding design isn't great

### ISSUE THREAD

**Issue by waderyan** [Microsoft/vscode#19249]
This may simply be my opinion, but I find the styling for the keybindings tough on the Interactive Playground. 

![image](https://cloud.githubusercontent.com/assets/2449568/22260685/f37f878a-e21e-11e6-895a-8ec7a35b4ae1.png)

Some ideas to improve
- Instead of showing `shift+ctrl+up`, `shift+ctrl+down`, `shift+ctrl+left`, and `shift+ctrl+right` change to `shift+ctrl+<arrow key>` (I don't love this approach, but something to keep it tighter)
- style similar to what Github does for `kbd` tags (e.g. <kbd>shift+ctrl+left</kbd>

**Comment by chrmarti** [comment]
I tried to align with the release editor for now.
