### ISSUE TITLE
Task reuse of terminal is inconsistent

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#19251]
Testing #19057

- VSCode Version: Code - Insiders 1.9.0-insider (4265f5e35cb3ea8ba7e0cf6b14ec606b6f8647ea, 2017-01-24T10:29:13.076Z)
- OS Version: Darwin x64 16.3.0
- Extensions:

|Extension|Author|Version|
|---|---|---|
|EditorConfig|EditorConfig|0.3.4|
|lorem-ipsum|Tyriar|1.0.0|
|sort-lines|Tyriar|1.2.0|
|theme-glacier|Tyriar|0.0.10|
|vscode-svgviewer|cssho|1.3.0|
|gitlens|eamodio|1.4.3|
|git-project-manager|felipecaputo|1.0.1|
|md-navigate|jrieken|0.0.1|
|vscode-scss|mrmlnc|0.6.0|
|seti-icons|qinjia|0.1.3|

---

I ran 4 lint tasks, only the 3rd one reused the 2nd terminal instance.

<img width="727" alt="screen shot 2017-01-24 at 10 31 36 am" src="https://cloud.githubusercontent.com/assets/2193314/22261074/67fcc7f2-e220-11e6-8929-21fcfd9df7bb.png">

**Comment by dbaeumer** [comment]
I improved the behavior for March by having a primary terminal that is always resued. However there is more to do here before I can close this:

- allow users to control this. This is requested in other issues as well
- reuse a terminal id idle if marked to be able to. For example users want to mark a terminal to not be resued to for example don't loose the result of a test run.

**Comment by dbaeumer** [comment]
This got improved in the final implementation by giving the user a property to control this. It can either be 'shared', 'dedicated', 'new'. If shared the terminal is shared between all tasks, if dedicated it is only shared between runs of the same task and if new it is never shared.
