### ISSUE TITLE
Command Center > Make window draggable

### ISSUE THREAD

**Issue by BerndHme** [microsoft/vscode#192548]
Type: <b>Feature Request</b>

When clicking and dragging in the title-bar > command-center box  
... make the entire vscode window draggable.

Now, if your window is resized to a small size, the command-center-box is taking up a lot of space.
When you want to drag your window to somewhere else, it is not possible when clicking on the box.

I refer to the search-box of ms outlook desktop, where this click+drag option ***does*** exist.

----
VS Code version: Code 1.82.0 (8b617bd08fd9e3fc94d14adb8d358b56e3f72314, 2023-09-06T22:07:07.438Z)
OS version: Windows_NT x64 10.0.19045
Modes:

**Comment by deepak1556** [comment]
This is a limitation in the runtime and cannot be worked around, you can check https://github.com/microsoft/vscode/issues/157437 for context.
