### ISSUE TITLE
Changes to Emmet config files not picked up without reload

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#19253]
Test item #19079

- VSCode Version: Code - Insiders 1.9.0-insider (4265f5e35cb3ea8ba7e0cf6b14ec606b6f8647ea, 2017-01-24T10:29:13.076Z)
- OS Version: Darwin x64 15.6.0
- Extensions: None

Steps to Reproduce:

1. Configure "emmet.extensionsPath" with the three config files
2. Notice that the path is picked up without reload, but changes to any of the three config files require a reload.
(E.g., switch between xhtml and html, between pt and px, change a snippet.)

**Comment by ramya-rao-a** [comment]
This is by design.

Note the note in the test plan item
> Changes to the external files will get reflected only on VS Code reload.

Changes to these files are very infrequent. Therefore, adding complex code to watch these files for changes was thought have less ROI.

**Comment by stevencl** [comment]
For what it is worth, this really threw me too. I didn't expect to have to reload VS Code to have this take effect.

**Comment by ramya-rao-a** [comment]
I'll wait for feedback once this is released, and revisit this.
