### ISSUE TITLE
VS Code cannot load extension with prerelease version if earlier, non-prerelease version is installed

### ISSUE THREAD

**Issue by daviwil** [Microsoft/vscode#19259]
- VSCode Version: VS Code Stable 1.8.1 and VS Code Insiders 1.9.0
- OS Version: Windows 10 Anniversary

Steps to Reproduce:

1. Install the PowerShell extension from the Marketplace
2. Install this VSIX using `code --install-extension filename.vsix`: https://ci.appveyor.com/api/buildjobs/kqjgav8i2q1nowlq/artifacts/PowerShell-0.9.1-insiders-17.vsix
3. Start VS Code and open the Extensions pane
4. Observe that the new extension is recognized but it always shows the "Reload" button:

![image](https://cloud.githubusercontent.com/assets/79405/22262038/2943c052-e224-11e6-8694-814747e5f07c.png)

You can also see that this message is in the dev console:

```
Overwriting extension C:/Users/daviwil/.vscode-insiders/extensions/ms-vscode.PowerShell-0.9.1-insiders-16 with C:/Users/daviwil/.vscode-insiders/extensions/ms-vscode.PowerShell-0.9.0.
```

If you uninstall both extensions and then *only* install the "insiders" extension, everything works fine.  Maybe the version comparison code for prerelease extensions isn't respecting the greater patch version digit?

**Comment by joaomoreno** [comment]
We don't currently support this.

An extension which is installed manually through a VSIX and an extension with the same ID that gets fetch from the gallery are not considered to be the same extension.

We should maybe work towards supporting this, since people expect this to just work. #17290 #15756

@sandy081

**Comment by daviwil** [comment]
It'd be really nice if it worked, I want to give my users extension packages straight out of my CI build so they can verify fixes and try new features.  The inability to update the extension if an earlier version is installed as VSIX is also a problem, though I understand the concerns that you mentioned on another issue.

I'm trying to avoid having to have an additional "preview" version of extension on the marketplace just for CI builds but if the team thinks that's the right way to do it then I can do that instead.  Thanks!

**Comment by jchannon** [comment]
Would it be possible to load a specific version of an extension eg `code -ext csharp@1.70` if you had multiple versions installed. I would really like that option

**Comment by joaomoreno** [comment]
@daviwil Can you still repro this in the latest Insiders? I believe @sandy081 fixed it in #17290.

@jchannon That is another feature request, which likely we won't support. We always delete older versions of extension, in the face of newer onces.

**Comment by daviwil** [comment]
Sorry for the delay!  Just tried this out in today's Insider's update following these steps:

1. Make sure PowerShell 0.11.0 is installed
2. [Download the VSIX from here](https://ci.appveyor.com/api/buildjobs/v3esuivx35jgp50v/artifacts/PowerShell-insiders.vsix) and use `Extensions: Install from VSIX` to install it
3. Reload VS Code
4. Prerelease version is not loaded, seems to have maintained the old version (should show 0.11.0-insiders-110):

![image](https://cloud.githubusercontent.com/assets/79405/24383373/6aab28aa-1311-11e7-8e21-462826805252.png)

**Comment by joaomoreno** [comment]
Thanks @daviwil !

@sandy081 You'll check it out?

**Comment by sandy081** [comment]
@joaomoreno Will investigate.

**Comment by joaomoreno** [comment]
@sandy081 Any updates?

**Comment by sandy081** [comment]
@joaomoreno Not yet.. have to look.

**Comment by sandy081** [comment]
@joaomoreno I think this is because we wont support beta component in version and our semver compare ignores that.

**Comment by joaomoreno** [comment]
I know the Marketplace doesn't support it, but we could. 👍

**Comment by sandy081** [comment]
This will be taken care by #39024
