### ISSUE TITLE
terminal display error 

### ISSUE THREAD

**Issue by yeqiaojun** [microsoft/vscode#192511]
after update 1.82.0, vscode  terminal display error.
![QQ图片20230908114626](https://github.com/microsoft/vscode/assets/2228474/c69d2644-f4c3-444f-baa6-64b4155d17fd)

**Comment by meganrogge** [comment]
It looks like your report is missing some important information, See [this wiki page](https://github.com/microsoft/vscode/wiki/Terminal-Issues) for more info on how to report actionable terminal issues.
/label info-needed terminal

**Comment by ClebersonAlves** [comment]
Hello, you need to change the color of "editor.background" on settings.json file.
Click on menu File, Preferences, Settings.
