### ISSUE TITLE
Welcome -> Recent -> More... no longer works

### ISSUE THREAD

**Issue by fjeldstad** [microsoft/vscode#192533]
Type: <b>Bug</b>

After updating to the latest version, the "More..." link in the "Recent" section on the Welcome page no longer works - nothing happens when clicking on it. It is supposed to open a dropdown/search box with more recent projects that you have worked on.

VS Code version: Code 1.82.0 (8b617bd08fd9e3fc94d14adb8d358b56e3f72314, 2023-09-06T22:09:41.364Z)
OS version: Darwin x64 22.6.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2200)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|3, 3, 2|
|Memory (System)|32.00GB (1.25GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (22)</summary>

Extension|Author (truncated)|Version
---|---|---
emojisense|bie|0.10.0
markdown-emoji|bie|0.3.0
vscode-markdownlint|Dav|0.51.0
vscode-eslint|dba|2.4.2
vscode-axe-linter|deq|4.7.2
gitlens|eam|14.3.0
EditorConfig|Edi|0.16.4
prettier-vscode|esb|10.1.0
vscode-github-actions|git|0.26.2
vscode-pull-request-github|Git|0.70.0
rainbow-csv|mec|3.7.0
dotenv|mik|1.0.1
vscode-docker|ms-|1.26.0
vscode-kubernetes-tools|ms-|1.3.13
vsliveshare|ms-|1.0.5883
vscode-yaml|red|1.14.0
code-spell-checker|str|3.0.0
intellicode-api-usage-examples|Vis|0.2.8
vscodeintellicode|Vis|1.2.30
vscode-todo-highlight|way|1.0.5
vscode-import-cost|wix|3.3.0
vscode-caddyfile-syntax|zam|1.0.4

</details>

**Comment by gjsjohnmurray** [comment]
It works for me, though I'm on Windows.

If you try it after running the `Developer: Toggle Developer Tools` command in the palette do you get any clues?

**Comment by gjsjohnmurray** [comment]
Might also be worth testing after running the command to disable all installed extensions temporarily.

**Comment by fjeldstad** [comment]
Thanks @gjsjohnmurray, I have tried both of your suggestions but unfortunately the result is the same, nothing happens. No output in the developer console either.

**Comment by bzuu-ic** [comment]
I am seeing the same issue on Windows.

Version: 1.82.2 (user setup)
Commit: abd2f3db4bdb28f9e95536dfa84d8479f1eb312d
Date: 2023-09-14T05:55:25.390Z
Electron: 25.8.1
ElectronBuildId: 23779380
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.22621

**Comment by bzuu-ic** [comment]
The functionality itself seems to be working fine, as I can access the complete list without any issues through the ```File > Open Recent > More...``` menu

**Comment by mill1000** [comment]
Also been noticing this issue over the last few weeks. Disabling extensions has no effect.

```
Version: 1.82.2 (user setup)
Commit: abd2f3db4bdb28f9e95536dfa84d8479f1eb312d
Date: 2023-09-14T05:55:25.390Z
Electron: 25.8.1
ElectronBuildId: 23779380
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.19045
```

**Comment by pozil** [comment]
Same issue here for at least a month (probably more).

```
Version: 1.83.1 (Universal)
Commit: f1b07bd25dfad64b0167beb15359ae573aecd2cc
Date: 2023-10-10T23:46:55.789Z (5 days ago)
Electron: 25.8.4
ElectronBuildId: 24154031
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Darwin arm64 22.6.0 (macOS Ventura 13.5.2)
```

**Comment by pozil** [comment]
Sharing an [X thread about this issue](https://twitter.com/hey_amandam/status/1713940940384055332).
It looks like people who experience the issue might the ones who see the GitHub Copilot ad on the right side of the welcome page.

**Comment by burkeholland** [comment]
Commented about this on X, but would be helpful if someone could run a Bisect here and see if that isolates the issue.

**Comment by pozil** [comment]
I ran a Bisect and issue is still present.
![Screenshot 2023-10-16 at 18 50 01](https://github.com/microsoft/vscode/assets/5071767/5b615822-92ca-4d8f-a51b-9ba0b6e8a092)

**Comment by bhavyaus** [comment]
I'm unable to repro this scenario also but investigating recent changes in this area to see if there are any side effects.

**Comment by burkeholland** [comment]
Can you open the developer tools and search for `showMoreRecents`. This should be found in `gettingStarted.ts`. Slap a break point on that method (~line 366) and see what happens when you click "More".

**Comment by pozil** [comment]
Just did this but it looks like it's not reaching the breakpoint. In fact, it's not even reaching the parent method `runDispatchCommand`.

Should there the be a third `click` handler on the More button?
![Screenshot 2023-10-16 at 19 48 29](https://github.com/microsoft/vscode/assets/5071767/bd959c2b-8cc0-4268-aad8-1e90c7d7a2b7)

**Comment by bhavyaus** [comment]
Thanks for checking. I'll dig deeper to see what could be happening. I'm still no repro for the scenario though.

**Comment by bhavyaus** [comment]
We've disabled featured extensions. This issue should also be fixed in the upcoming release.
