### ISSUE TITLE
Saving .vscode/task.json should always refresh task list

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#19250]
Testing #19057

- VSCode Version: Code - Insiders 1.9.0-insider (4265f5e35cb3ea8ba7e0cf6b14ec606b6f8647ea, 2017-01-24T10:29:13.076Z)
- OS Version: Darwin x64 16.3.0
- Extensions:

|Extension|Author|Version|
|---|---|---|
|EditorConfig|EditorConfig|0.3.4|
|lorem-ipsum|Tyriar|1.0.0|
|sort-lines|Tyriar|1.2.0|
|theme-glacier|Tyriar|0.0.10|
|vscode-svgviewer|cssho|1.3.0|
|gitlens|eamodio|1.4.3|
|git-project-manager|felipecaputo|1.0.1|
|md-navigate|jrieken|0.0.1|
|vscode-scss|mrmlnc|0.6.0|
|seti-icons|qinjia|0.1.3|

---

I have the following file saved, no errors show up but the task list still shows the old values, even when I close and open the file.

```js
{
    // See https://go.microsoft.com/fwlink/?LinkId=733558
    // for the documentation about the tasks.json format
    "version": "0.1.0",
    "command": "npm",
    "isShellCommand": true,
    "showOutput": "always",
    "suppressTaskName": true,
    "_runner": "terminal",
    "tasks": [
        {
            "taskName": "install",
            "args": ["install"]
        },
        {
            "taskName": "lint",
            "args": ["run", "tslint"]
        },
        {
            "taskName": "test",
            "args": ["run", "test"]
        },
        {
          "taskName": "watch",
          "args": ["run", "dev"],
          "isBuildCommand": true
        }
    ]
}
```

After creating this issue the list refreshed (window focus?)

**Comment by dbaeumer** [comment]
This now works for the _runner -> terminal. It does not for the old output task runner mainly because I can't hot swap the configuration due to state assigned to a running task. Since the output runner will fade out no further action is planned.

**Comment by aeschli** [comment]
@dbaeumer Do you have verification steps?

**Comment by dbaeumer** [comment]
@aeschli sorry for not adding them

```json
{
    "version": "0.1.0",
    "echoCommand": true,
    "_runner": "terminal",
    "tasks": [
        {
            "taskName": "tsc",
            "command": "tsc -w",
            "isShellCommand": true,
            "isBackground": true,
            "problemMatcher": "$tsc-watch",
            "isBuildCommand": true
        },
        {
            "taskName": "dir",
            "command": "dir",
            "isShellCommand": true
        }
    ]
}
```

* Start the watch task by pressing Ctrl+Shift+B. 
* Change the name of the dir task to something else. 
* F1 > Run Task <enter> should show the new name.

**Comment by mattflix** [comment]
Does "verified" mean still broken?

I am using the "terminal" runner and changes to tasks.json are not reflected unless I close/open the folder, or exit/restart Code.  Old versions of Code would auto update but I can't remember when this broke.

Software:
- VS Code 1.13.1
- Windows 10

**Comment by Tyriar** [comment]
@mattflix verified means it was testing in the version it was released in (Jan 2017). If you are seeing this again please create a new issue and reference this one.
