### ISSUE TITLE
"emmet.syntaxProfiles" setting does not overwrite all in syntaxProfiles.json

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#19258]
Test item #19079

- VSCode Version: Code - Insiders 1.9.0-insider (4265f5e35cb3ea8ba7e0cf6b14ec606b6f8647ea, 2017-01-24T10:29:13.076Z)
- OS Version: Darwin x64 15.6.0
- Extensions: None

The test item suggests that having "emmet.syntaxProfiles" in your settings overwrites all (not just the specified) settings. It says: "HTML elements that do not have closing tags are back to the old behaviour of not getting self closing tags"

I cannot verify that, I still get self-closing tags, also after reloading the workbench.

**Comment by ramya-rao-a** [comment]
@chrmarti Can you share the contents of the `syntaxProfiles.json` and the value of `emmet.syntaxProfiles` setting?

**Comment by chrmarti** [comment]
I believe this is what the test item asked me to do:

Settings (workspace):
```
    "emmet.syntaxProfiles": {
        "html": {
            "attr_quotes": "single"
        }
    },
```

syntaxProfiles.json:
```
{
    "html": "xhtml"
}
```

**Comment by ramya-rao-a** [comment]
We synced offline. There was a mistake in the test steps.
Changing the settings to below overrides the self_closing_tag behavior from the file
```
    "emmet.syntaxProfiles": {
        "html": {
            "attr_quotes": "single",
           "self_closing_tag": false
        }
    },
```
