### ISSUE TITLE
Sticky scroll: folding icons missing from some sticky headers

### ISSUE THREAD

**Issue by gjsjohnmurray** [microsoft/vscode#192535]
Type: <b>Bug</b>

> Issue troubleshooting has identified that the issue is with Visual Studio Code - Insiders. 

If the sticky scroll header shows only one line, that line has no folding indicator.

If it shows 2 or more lines, only the last line has the indicator.

![junk](https://github.com/microsoft/vscode/assets/6726799/e76de0d7-e8f0-4b86-bea5-4b96c3bdb4d2)

This is working correctly in 1.82.0 Stable.

VS Code version: Code - Insiders 1.83.0-insider (5a400e53e985dc5e24f6ee574b07ab23943841c5, 2023-09-07T17:35:42.740Z)
OS version: Windows_NT x64 10.0.22621
Modes:

**Comment by aiday-mar** [comment]
Hi @gjsjohnmurray, thank you for filing the issue. I was looking at this issue right at the moment and was about to file a bug but you did it before me. I think this issue may have been caused by https://github.com/microsoft/vscode/pull/188499, I will work on a fix.
