### ISSUE TITLE
Add JSON schemas for Emmet config files

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#19255]
Test item #19079

- VSCode Version: Code - Insiders 1.9.0-insider (4265f5e35cb3ea8ba7e0cf6b14ec606b6f8647ea, 2017-01-24T10:29:13.076Z)
- OS Version: Darwin x64 15.6.0
- Extensions: None

Not sure if there is an easy way to do that since the file names are not Emmet-specific, but given the "emmet.extensionsPath" we know what they are. /cc @aeschli

**Comment by ramya-rao-a** [comment]
I personally vote this down

The new apis from Emmet 2.0 follow a different format and @sergeche has plans to make it easier for people to write these files. 

Given this and the fact that there are current instructions in the emmet website
(https://docs.emmet.io/customization/) , I'd say there is not much ROI in us maintaining schemas for emmet customization files
