### ISSUE TITLE
Ctrl+1 and Ctrl+2 not working

### ISSUE THREAD

**Issue by sinkeat** [microsoft/vscode#192591]
Type: <b>Bug</b>

default keyboard shortcuts to focus editor tab1, tab2, tab3
using "control+1", "control+2", "control+3"

Only "control+1" and "control+2" are broken, cannot resolve to corresponding "ctrl+[Digit]" in keyboard shortcuts troubleshooting too. "control+3" and up works fine.

Also found that pressing "fn" with the "control+1" or "control+2" would trigger their "ctrl+[Digit]" and correctly focus to editor tab

VS Code version: Code 1.82.0 (Universal) (8b617bd08fd9e3fc94d14adb8d358b56e3f72314, 2023-09-06T22:09:41.364Z)
OS version: Darwin arm64 22.6.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|8.00GB (0.26GB free)|
|Process Argv|--crash-reporter-id aea7b2c8-ab99-4036-9376-d7008bb4466b|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
py29gd2263:30792226
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
vscccc:30803845
282f8724:30602487
f6dab269:30613381
a9j8j154:30646983
showlangstatbar:30737416
962ge761:30831758
03d35959:30757346
pythonfmttext:30731395
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
pythonnosmt12:30797651
pythonidxpt:30805730
pythonnoceb:30805159
synctok:30821570
dsvsc013:30795093
dsvsc014:30804076
diffeditorv2:30821572
dsvsc015:30829745

```

</details>

**Comment by ulugbekna** [comment]
Hi @sinkeat ,

Thanks for filing the issue. 

Could you please press the keyboard shortcuts that you mentioned (working & not working) on this website and send the screenshot? https://w3c.github.io/uievents/tools/key-event-viewer.html

Also, could you send the logs printed by keyboard shortcut troubleshooting for the those shortcuts?

**Comment by sinkeat** [comment]
![w3c github io_uievents_tools_key-event-viewer-html](https://github.com/microsoft/vscode/assets/16041170/32b5b2c9-e010-4bb7-94f2-855f5e96297d)

<img width="1178" alt="image" src="https://github.com/microsoft/vscode/assets/16041170/eea8bbe9-740b-4704-9211-be74756cc393">

Hi @ulugbekna,

Thank you for following up. 

From the result it seems the problem is on OS level. Sorry for not isolating the issue in advance.
