### ISSUE TITLE
Unwanted line breaks in debug console output

### ISSUE THREAD

**Issue by felixfbecker** [Microsoft/vscode#19256]
- VSCode Version: VS Code Insiders 1.9

Actual:

![image](https://cloud.githubusercontent.com/assets/10532611/22261642/f824dd7c-e26d-11e6-9c8b-d515784b8a09.png)

Expected:

![image](https://cloud.githubusercontent.com/assets/10532611/22261666/146a30c2-e26e-11e6-9d01-65a0fda38313.png)

**Comment by isidorn** [comment]
Dup of #17526
