### ISSUE TITLE
DOMParser.parseFromString().documentElement type incorrect

### ISSUE THREAD

**Issue by AGluk** [microsoft/vscode#192576]
Does this issue occur when all extensions are disabled?: Yes
Steps to Reproduce:

```
let parser = new DOMParser(),
let vr = parser.parseFromString(data, 'image/svg+xml').documentElement;
```

according to lib.dom.d.ts, documentElement declared as:
`readonly documentElement: HTMLElement;`

But should be:
`readonly documentElement: Element;`

because you can use parser.parseFromString on svg elements!

**Comment by IllusionMH** [comment]
You should check if similar issue already reported in TypeScript repo and report there if not.
VS Code does not control type definitions that are shipped with TS package.

**Comment by AGluk** [comment]
You right!
This problem was already mentioned in the TypeScript repo:

https://github.com/microsoft/TypeScript/issues/29052

Thank you!
