### ISSUE TITLE
Java debug console left empty

### ISSUE THREAD

**Issue by ollikoponenbel** [microsoft/vscode#192543]
Type: <b>Bug</b>

Since the august update, i get randomly no output to debug console when restarting java via key shortcut ctrl + shift + f5.

Manually stopping (shift + f5) and starting (f5) seems to usually fix the issue.

VS Code version: Code 1.82.0 (8b617bd08fd9e3fc94d14adb8d358b56e3f72314, 2023-09-06T22:07:18.759Z)
OS version: Linux x64 6.2.0-32-generic
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz (8 x 2800)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|5, 2, 1|
|Memory (System)|15.32GB (7.28GB free)|
|Process Argv|--unity-launch --crash-reporter-id 058641ec-6c83-4f22-873d-961543d63c45|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|wayland|
</details><details><summary>Extensions (29)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|3.0.2
vscode-sql-formatter|adp|1.4.4
Bookmarks|ale|13.4.1
aurelia|Aur|2.1.4
vscode-django|bat|1.10.0
django-html|bib|1.3.0
path-intellisense|chr|2.8.4
vscode-eslint|dba|2.4.2
githistory|don|0.6.20
EditorConfig|Edi|0.16.4
vscode-ember-unstable|lif|3.0.51
isort|ms-|2023.10.1
python|ms-|2023.16.0
vscode-pylance|ms-|2023.9.10
tsimporter|pmn|2.0.1
java|red|1.21.0
vscode-xml|red|0.26.1
scala|sca|0.5.7
django-intellisense|sha|0.0.2
sonarlint-vscode|Son|3.21.0
autoimport|ste|1.5.4
svelte-vscode|sve|107.10.1
vscodeintellicode|Vis|1.2.30
vscode-java-debug|vsc|0.54.0
vscode-java-dependency|vsc|0.23.1
vscode-java-pack|vsc|0.25.13
vscode-maven|vsc|0.42.0
volar|Vue|1.8.10
vscode-typescript-vue-plugin|Vue|1.8.10

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes516:30244333
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
vscaac:30438847
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyonecf:30548226
vsccc:30803844
2e4cg342:30602488
89544117:30613380
a9j8j154:30646983
showlangstatbar:30737416
0bi6i642:30831757
03d35959:30757346
57b77579:30736110
pythonfmttext:30731395
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
pythonnosmt12:30797651
pythonidxpt:30805730
pythonnoceb:30805159
synctok:30821570
dsvsc013:30795093
dsvsc014:30804076
diffeditorv2:30821572
dsvsc015cf:30829746

```

</details>

**Comment by readwr** [comment]
Same here.

**Comment by juliussimonelli** [comment]
I'm getting this with Python as well.

**Comment by roblourens** [comment]
https://github.com/microsoft/vscode/issues/192653 
Can you check the developer tools for errors (Help > Toggle Developer Tools)?
