### ISSUE TITLE
Can't find Component usage in the project 

### ISSUE THREAD

**Issue by GIT-MDW** [microsoft/vscode#192547]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 
- OS Version: 

Steps to Reproduce:
Watch video. 
1. 
2.

I think this connected with default export. It appears that VsCode works bad with default exports

with webstorm 
![image](https://github.com/microsoft/vscode/assets/94377644/df4e7380-23d0-4bf3-b4ce-6d26acf7ed32)

with VS Code 
![image](https://github.com/microsoft/vscode/assets/94377644/d07c4bb2-c3d8-4e89-ba2f-5afc99d5a3b9)

**Comment by GIT-MDW** [comment]
At times it shows less found items than in webstorm, its potential bug that you need to fix.

**Comment by IllusionMH** [comment]
Are all of these files with imports in the same TS project?

I suppose that you have monorepo with separate componets, in this case you need to have config for composite TS project that includes all components.

**Comment by GIT-MDW** [comment]
Yeah its monorepo but in WebStorm everything works great, for VsCode its problem

**Comment by IllusionMH** [comment]
Webstorm does a lot of things it their own way.

VS Code uses TS and you need proper configuration to make TS work with all packages in monorepo.
See example from https://github.com/RyanCavanaugh/learn-a

**Comment by mjbvz** [comment]
Closing as a question. Also please share example code with steps to reproduce the issue. Videos are a pain to review
