### ISSUE TITLE
Failing unit test skipped in `userDataAutoSyncService.test.ts`

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#192539]
@sandy081 can you please check out this test which now seems to fail, I am not entirely sure why but it seams to have started to leak now.

_Originally posted by @bpasero in https://github.com/microsoft/vscode/pull/192530#discussion_r1319527143_

**Comment by sandy081** [comment]
Fixed by a4f08120caff7f645e5432bc84504ecc70a4c1d3
