### ISSUE TITLE
[UX] Command center and search/command palette visual noise

### ISSUE THREAD

**Issue by ashemedai** [microsoft/vscode#192520]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.82.0
- OS Version: 10 22H2

Steps to Reproduce:

1. Open a window
2. Ctrl+P/Ctrl+Shift+P to get the search or Command Palette

Whilst the Command Center is absolutely centered, taking into account the arrows on its left-hand side, it causes distracting visual noise when regularly using the search/Command Palette. See below screenshot of why.

![image](https://github.com/microsoft/vscode/assets/610865/442755ee-0b52-4235-a8e2-09ffb65db48e)

I am fully cognizant this will only be annoying for a percentage of people using VSCode. Unfortunately I am one of them as it causes an annoying relative shift left for me. Especially since the search/Command Palette seems to be the same size as the Command Center bar. And since I use the search/Command Palette a lot, this will irritate me more and more, visually. So I will need to turn the Command Center off.

I think it makes sense to get some UX experts' advice on this, if possible.

**Comment by jrieken** [comment]
It depends on what you look at. The alignment happens wrt to whole things, including the arrows and other (optional) CC buttons

**Comment by gjsjohnmurray** [comment]
@ashemedai is your screenshot a composite? It shows the placeholder with the magnifier icon above the quickpick.

Here's what I see.

![junk](https://github.com/microsoft/vscode/assets/6726799/3e796ed2-eaa7-447e-870a-00df5f3b35b8)

**Comment by ashemedai** [comment]
@gjsjohnmurray It was my way of showing the misalignment since I didn't have any recording software installed on this system. So I layered two windows on top of each other, with one showing the command center and the other the search/palette.

Interestingly, your search/palette width seems smaller than the command center's width.

**Comment by ashemedai** [comment]
> It depends on what you look at. The alignment happens wrt to whole thing, including the arrows and other (optional) CC buttons

Thanks for clarifying that. So in some situations it might happen to align depending on what's in the bar and width of the window?

Anyway. for someone like me it's distracting as heck and despite wanting to use it, as it seems like a useful feature, I wish I could just ignore it, but seems my brain just cannot, so I had to disable it.

I think it's because it feels like an extension of the command center as it appears to come from there, but I am sure someone with UX expertise knows the proper reasoning why.

**Comment by ashemedai** [comment]
Apologies to belabour the point, but just to make it clarify what I meant:

![image](https://github.com/microsoft/vscode/assets/610865/922f535b-a6f4-435b-9bda-d8d6057da8cd)

Visually you get anchored to the sides of the text bar above, so when you see the search/palette bar appear the sides are quite misaligned to what you previously saw.

Whether it's this smaller 2 windows I just tested with or the bigger full width ones from my initial screenshot.

**Comment by gjsjohnmurray** [comment]
Does it get any better if you use the context menu to hide Command Center's back and forward buttons?

**Comment by jrieken** [comment]
Looking at the capture in https://github.com/microsoft/vscode/issues/192520#issuecomment-1711371911 suggests that this is a case in which the window is narrow which makes use not align the CC in the centre anymore. This is to make space for the global menu. Tho, it also decided to collapse into the burger which means we can go back to centre alignment

**Comment by ashemedai** [comment]
> Does it get any better if you use the context menu to hide Command Center's back and forward buttons?

It actually does, yes. Both for the small windows as well as the full-width ones.
Thanks for pointing out those can be hidden.

**Comment by benibenj** [comment]
Closing as we aren't planning to change anything here. You can hide all the actions to the left and or right of the command center which will help alignment
