### ISSUE TITLE
Missing or invalid credentials. Error: connect ENOENT /run/user/1000/vscode-git-6fc6e74986.sock

### ISSUE THREAD

**Issue by Pnlvfx** [microsoft/vscode#192551]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: latest
- OS Version: Ubuntu 22.04
- Missing or invalid credentials. Error: connect ENOENT /run/user/1000/vscode-git-6fc6e74986.sock  at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1494:16) {   errno: -2,   code: 'ENOENT',   syscall: 'connect',   address: '/run/user/1000/vscode-git-6fc6e74986.sock' } Missing or invalid credentials. Error: connect ENOENT /run/user/1000/vscode-git-6fc6e74986.sock     at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1494:16) {   errno: -2,   code: 'ENOENT',   syscall: 'connect',   address: '/run/user/1000/vscode-git-6fc6e74986.sock' } remote: Repository not found.

Steps to Reproduce:

I'm not good at steps to reproduce, but it was working before the latest update,
All my nodejs projects are not able to do git pull or push, even if I can see the changes made.
I'm on ubuntu 22.04 with node 19.5.
Sorry but I cannot provide more info

**Comment by Pnlvfx** [comment]
I've tried to logout and login again, as well as restart the computer

**Comment by Pnlvfx** [comment]
The issue seems to be fixed now, after I've totally closed the directory and open it again (with only a restart it was not working). Sorry, you guys can ignore this issue.

**Comment by sudhirkumar-dev** [comment]
I have like 50 changes and there was this error showing like authentication failed Error: connect ENOENT /run/user/1000/vscode-git-fb00d917e3.sock  i closed the vs code and restarted the directory again it worked fine

**Comment by yoyo837** [comment]
Same here in latest stable version.

**Comment by Pnlvfx** [comment]
It's still randomly happens to me

**Comment by pigochu** [comment]
My env is win10 + WSL2 + vscode 1.82.2
If I start vs code and run git immediately, its works fine , after 1 minutes , its can not work.
I need shutdown wsl2 again , and run git immediately.

**Comment by canstand** [comment]
@lszomoru same to me as @pigochu say, os win11

**Comment by AlexKomzzz** [comment]
similar situation. ubuntu 22.04 + vscode 1.82.2

**Comment by pigochu** [comment]
I don’t know if this is really a bug of VS CODE. Maybe it’s a bug of Ubuntu itself, because /run/user/1000 will be deleted entirely inexplicably. My current solution is run
```bash
sudo loginctl enable-linger username
```

**Comment by lszomoru** [comment]
@deepak1556, does this ring a bell?

**Comment by deepak1556** [comment]
Can affected users check if the issue is present with out latest insiders https://code.visualstudio.com/insiders, I feel this might be a side effect of https://github.com/microsoft/vscode/issues/192742

**Comment by seunghkong** [comment]
> I don’t know if this is really a bug of VS CODE. Maybe it’s a bug of Ubuntu itself, because /run/user/1000 will be deleted entirely inexplicably. My WSL has enabled systemd. My current solution is run
> 
> ```shell
> sudo loginctl enable-linger username
> ```
> 
> then restart wsl

had the same problem with /run/user/1000, and this solution worked for win11 + WSL2(ubuntu 22.04) + vscode 1.83
