### ISSUE TITLE
Undisposed disposable in state service node.js unit test

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode#192635]
Build: https://dev.azure.com/monacotools/a6d41577-0fa3-498e-af22-257312ff0545/_build/results?buildId=231244
Changes: https://github.com/Microsoft/vscode/compare/338e449...fbdc92c

```
  1) StateService
       "after each" hook for "Multiple ops (Immediate Strategy)":
     There are 1 undisposed disposables!

```

**Comment by bpasero** [comment]
Hopefully addressed via https://github.com/microsoft/vscode/commit/41c6343f84e12869e4f26ccd189c6e4b916d770a
