### ISSUE TITLE
Issue while finding type

### ISSUE THREAD

**Issue by GIT-MDW** [microsoft/vscode#192621]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 
- OS Version: 

Steps to Reproduce:

1. Click at type and if you have component with the same name it goes to the component instead of type
2. Also noticed that clicking at default exported component doesn't open usage location, sometimes when clicking it shows unneeded index file off some package

![image](https://github.com/microsoft/vscode/assets/94377644/35568e91-2ec4-422d-b347-8bf7807fa4d6)

**Comment by GIT-MDW** [comment]
Here is the example with index file. I clicked at the component 
![Uploading image.png…]()

**Comment by mjbvz** [comment]
Please share example code (as text) that demonstrates the issue

**Comment by GIT-MDW** [comment]
import React, { FC, ReactNode } from 'react'

import classNames from 'classnames'

import Label from '@components/Label/Label'

import './textArea.css'

const rootClass = 'textarea'

export interface TextAreaProps {
  onChange?: (event: React.ChangeEvent<HTMLTextAreaElement>) => void
  onBlur?: (event: React.ChangeEvent<HTMLTextAreaElement>) => void
  onFocus?: (event: React.ChangeEvent<HTMLTextAreaElement>) => void
  children?: ReactNode
  error?: boolean
  name: string
  label?: ReactNode
  rows?: number
  cols?: number
  id?: string
  defaultValue?: string
  register?: any
  className?: string
  dataTest?: string
  disabled?: boolean
  value?: string
  placeholder?: string
  resize?: boolean
}

const TextArea: FC<TextAreaProps> = (props: TextAreaProps) => {
  const {
    dataTest = rootClass,
    name,
    label,
    rows,
    cols,
    onChange,
    onBlur,
    onFocus,
    defaultValue,
    register,
    className,
    placeholder,
    error,
    disabled,
    value,
    resize = true,
  } = props
  return (
    <>
      {label && <Label label={label} htmlFor={name} />}
      <textarea
        className={classNames(rootClass, className, {
          [`${rootClass}__error`]: error,
          [`${rootClass}__no-resize`]: !resize,
        })}
        name={name}
        id={name}
        data-test={dataTest}
        rows={rows}
        cols={cols}
        onChange={onChange}
        disabled={disabled}
        value={value}
        onBlur={onBlur}
        onFocus={onFocus}
        defaultValue={defaultValue}
        placeholder={placeholder}
        {...register}
      >
        {props.children}
      </textarea>
    </>
  )
}

export default TextArea
