### ISSUE TITLE
not debugging in C/Cpp

### ISSUE THREAD

**Issue by dhk527** [microsoft/vscode#192616]
Type: <b>Feature Request</b>

when I run c/cpp runner debug file, it can not run. and show the below sentence.

root@KDH:/#  /usr/bin/env /bin/sh /tmp/Microsoft-MIEngine-Cmd-zohriyxh.unb 
/usr/bin/env: line 123: syntax error near unexpected token `)'
/usr/bin/env: line 123: `     (`), and backslash (\).  The backslash inside double quotes is historically weird, and serves to quote only the following'

I didn't handle any env, sh, code etc...
I can not solve this problem.

please let me know how to solve it for running the debug file :(

VS Code version: Code 1.82.0 (8b617bd08fd9e3fc94d14adb8d358b56e3f72314, 2023-09-06T22:07:07.438Z)
OS version: Windows_NT x64 10.0.19045
Modes:
Remote OS version: Linux x64 5.15.90.1-microsoft-standard-WSL2

**Comment by dhk527** [comment]
reinstalled

**Comment by roblourens** [comment]
Please file on the C++ extension repo
