### ISSUE TITLE
After upgrading to 1.82, vscode parse .wasm file location of vscodeintellicode-completions failure, lead to the extention cannot work

### ISSUE THREAD

**Issue by hoho51** [microsoft/vscode#192663]
Type: <b>Bug</b>

The plugin had no problems with version 1.81, but after upgrading it outputs the following error message, from which it appears that the new version of nodejs is unable to resolve the address of the file used by the plugin

```[Worker thread] Unhandled rejection error: Failed to parse URL from /home/xxx/.vscode/extensions/visualstudioexptteam.vscodeintellicode-completions-1.0.22/dist/tree-sitter.wasm
[Worker thread] Unhandled rejection error stack: TypeError: Failed to parse URL from /home/xxx/.vscode/extensions/visualstudioexptteam.vscodeintellicode-completions-1.0.22/dist/tree-sitter.wasm
    at Object.fetch (node:internal/deps/undici/undici:11413:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[Worker thread] Unhandled rejection error: Failed to parse URL from /home/xxx/.vscode/extensions/visualstudioexptteam.vscodeintellicode-completions-1.0.22/dist/blingfire.wasm
[Worker thread] Unhandled rejection error stack: TypeError: Failed to parse URL from /home/xxx/.vscode/extensions/visualstudioexptteam.vscodeintellicode-completions-1.0.22/dist/blingfire.wasm
    at Object.fetch (node:internal/deps/undici/undici:11413:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Extension version: 1.0.22 034a5c7
```

VS Code version: Code 1.82.0 (8b617bd08fd9e3fc94d14adb8d358b56e3f72314, 2023-09-06T22:07:18.759Z)
OS version: Linux x64 6.2.0-32-generic
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5200U CPU @ 2.20GHz (4 x 2495)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|0, 0, 0|
|Memory (System)|3.74GB (1.99GB free)|
|Process Argv|--unity-launch --crash-reporter-id 73e498f3-193b-4bc4-9391-119f845bf602|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|Lubuntu|
|XDG_CURRENT_DESKTOP|LXQt|
|XDG_SESSION_DESKTOP|undefined|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
python-environment-manager|don|1.2.1
gitlens|eam|14.3.0
vsc-python-indent|Kev|1.18.0
python-path|mge|0.0.14
flake8|ms-|2023.6.0
isort|ms-|2023.10.1
mypy-type-checker|ms-|2023.2.0
python|ms-|2023.16.0
vscode-pylance|ms-|2023.9.10
remote-ssh|ms-|0.106.2
remote-ssh-edit|ms-|0.86.0
remote-explorer|ms-|0.4.1
vscode-python-typehint|njq|1.5.1
intellicode-api-usage-examples|Vis|0.2.8
vscodeintellicode|Vis|1.2.30
vscodeintellicode-completions|Vis|1.0.22

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
vsccc:30803844
2e4cg342:30602488
89544117:30613380
showlangstatbar:30737416
962ge761:30831758
a2ce3375:30757347
24365598:30736109
pythonfmttext:30731395
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
pythonnosmt12:30797651
pythonidxptcf:30805731
pythonnoceb:30805159
dsvsc013:30795093
dsvsc014:30804076
diffeditorv2:30821572
dsvsc015:30829745

```

</details>

**Comment by mjbvz** [comment]
Please file this issue against Intellicode
