### ISSUE TITLE
Setting to control the terminal's buffer size

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#19262]
Test: https://github.com/Microsoft/vscode/issues/19071

- VSCode Version: 1.9
- OS Version: Windows

An option to control the buffer size of the terminal would be helpful.

**Comment by Tyriar** [comment]
This is configurable by the user via `terminal.integrated.scrollback`.

**Comment by dbaeumer** [comment]
Interesting name :-)

**Comment by Tyriar** [comment]
Seemed to be the common term at least in Unix-like environments which is why I chose it over something like `bufferSize`.
