### ISSUE TITLE
insertCursorAtEndOfEachLineSelected: Should not add cursor to last line if that line's selection is empty

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#19261]
Test item #19063

- VSCode Version: Code - Insiders 1.9.0-insider (4265f5e35cb3ea8ba7e0cf6b14ec606b6f8647ea, 2017-01-24T10:29:13.076Z)
- OS Version: Darwin x64 15.6.0
- Extensions: None

Steps to Reproduce:

1. Select, e.g., two complete lines (including the newline, i.e., the caret is at the beginning of the third line)
2. Run insertCursorAtEndOfEachLineSelected
3. Expected: Cursors at end of line 1 and 2
4. Actual: Cursors at ends of lines 1, 2 and 3

**Comment by aeschli** [comment]
verified in 3af0e9d6b79145011a7be3970c1d4b83d69b0443
