### ISSUE TITLE
SSH Port Forwarding for Ports 443 and 80 No Longer Functional After macOS Update, Requires Sudo with VSCode for Operation

### ISSUE THREAD

**Issue by farissi** [microsoft/vscode#192601]
Type: <b>Bug</b>

After updating my macOS system, I've noticed that SSH port forwarding for ports 443 and 80 has ceased to function correctly (redirection to another port). The only workaround I've found so far is running VSCode in sudo mode.

VS Code version: Code 1.82.0 (8b617bd08fd9e3fc94d14adb8d358b56e3f72314, 2023-09-06T22:08:29.670Z)
OS version: Darwin arm64 22.6.0
Modes:
Remote OS version: Linux x64 6.1.31-2-MANJARO

**Comment by farissi** [comment]
`sudo code` doesn't work either, I have to run `sudo /Applications/Visual\ Studio\ Code.app/Contents/MacOS/Electron`

**Comment by destroyer5656** [comment]
I also experienced this, but on ubuntu 22.04 with vscode 1.82.0. I also had this broken in a previous release and then it was fixed again afterwards. Seems like maybe ssh forwarding needs a better test suite to stop breakage.

**Comment by Ashesh3** [comment]
Possible duplicate of https://github.com/microsoft/vscode/issues/192521

**Comment by farissi** [comment]
Duplicate of https://github.com/microsoft/vscode/issues/192521, downgrading to [1.81](https://code.visualstudio.com/updates/v1_81) temporarily resolves the issue.
