### ISSUE TITLE
SSH connection keeps asking for password

### ISSUE THREAD

**Issue by shehanmunasinghe** [microsoft/vscode#192677]
Type: <b>Bug</b>

SSH connection keeps asking for password every couple of seconds until the below message is displayed 

"Cannot reconnect. Please reload the window"

VS Code version: Code 1.82.0 (8b617bd08fd9e3fc94d14adb8d358b56e3f72314, 2023-09-06T22:08:29.670Z)
OS version: Darwin arm64 22.1.0
Modes:
Connection to 'ssh-remote+10.127.30.110 could not be established

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|4, 3, 3|
|Memory (System)|16.00GB (0.11GB free)|
|Process Argv|--crash-reporter-id 0a64b77d-d353-46c5-8819-b79a87bb5020|
|Screen Reader|no|
|VM|0%|

Connection to 'ssh-remote+10.127.30.110(salman)' could not be established
</details><details><summary>Extensions (39)</summary>

Extension|Author (truncated)|Version
---|---|---
cmake-format|che|0.6.11
doxdocgen|csc|1.4.0
docs-markdown|doc|1.0.2
githistory|don|0.6.20
python-environment-manager|don|1.2.1
vscode-diff|fab|1.4.2
codespaces|Git|1.15.1
vscode-pull-request-github|Git|0.72.0
latex-workshop|Jam|9.13.4
better-cpp-syntax|jef|1.17.2
vsc-python-indent|Kev|1.18.0
rainbow-csv|mec|3.7.0
vscode-docker|ms-|1.26.0
csharp|ms-|2.1.2
vscode-dotnet-runtime|ms-|1.7.2
black-formatter|ms-|2023.4.1
isort|ms-|2023.10.1
python|ms-|2023.16.0
vscode-pylance|ms-|2023.9.10
jupyter|ms-|2023.8.1002501831
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.17
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-slideshow|ms-|0.1.5
remote-containers|ms-|0.309.0
remote-ssh|ms-|0.106.2
remote-ssh-edit|ms-|0.86.0
remote-wsl|ms-|0.81.2
vscode-remote-extensionpack|ms-|0.24.0
cmake-tools|ms-|1.15.31
cpptools|ms-|1.17.5
cpptools-extension-pack|ms-|1.3.0
remote-explorer|ms-|0.4.1
remote-server|ms-|1.4.3
vsliveshare|ms-|1.0.5883
vscode-yaml|red|1.14.0
cmake|twx|0.0.17
vscode-lldb|vad|1.9.2
markdown-all-in-one|yzh|3.5.1

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
vsccc:30803844
3biah626:30602489
f6dab269:30613381
2i9eh265:30646982
showlangstatbar:30737416
0bi6i642:30831757
03d35959:30757346
ecj1e332:30736112
pythonfmttext:30731395
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
pythonnosmt12:30797651
pythonidxpt:30805730
pythonnoceb:30805159
dsvsc013:30795093
dsvsc014:30804076
diffeditorv2:30821572
dsvsc015:30829745

```

</details>

**Comment by ChitturiSaiSuman** [comment]
You can switch to the pre-release version and continue with your work. There is an issue with the new release. It keeps asking for a password despite having already connected to the host.

**Comment by roblourens** [comment]
This should be fixed in the latest
