### ISSUE TITLE
renaming an .ipynb file with different case will re-open the old filename on edit

### ISSUE THREAD

**Issue by amunger** [microsoft/vscode#192641]
Steps to Reproduce:

1. open a file named 'test.ipynb' and rename to 'Test.ipynb'
2. make an edit in the file
:bug: an editor for 'test.ipynb' will open, so that both versions of the filename have a tab

**Comment by amunger** [comment]
the workingCopyModel does not get an updated URI when the file is renamed with only a case difference, so `notebookEditorManager._openMissingDirtyNotebookEditors` will reopen the old filename every time there is an edit.

**Comment by amunger** [comment]
For a text file rename, the editor is seen as already [existing editor](https://github.com/microsoft/vscode/blob/b4f975a422b1e909dda4c015f3682ee79560ec8a/src/vs/workbench/common/editor/editorGroupModel.ts#L407), and it is moved in place

For notebooks, it looks like a new editor, so the editor resource is the new case, and the model is the old case because it used the canonical URI service to retrieve the previous format.

**Comment by amunger** [comment]
@bpasero - Do you have any thoughts on resolving this? There is a mismatch in the URI in the model and the editor, but perhaps the resource used for the tab should be kept separate?

**Comment by bpasero** [comment]
Text file editor inputs carry a `resource` and a `preferredResource`:

https://github.com/microsoft/vscode/blob/ef9643997e1a5c3480cc79317e0125cc0adcd2f2/src/vs/workbench/contrib/files/browser/editors/fileEditorInput.ts#L87-L88

Maybe notebooks need to apply something similar. A case rename does not change the `resource` unless you are on Linux. However `preferredResource` can change and is used as label info.

https://github.com/microsoft/vscode/blob/ef9643997e1a5c3480cc79317e0125cc0adcd2f2/src/vs/workbench/common/editor/resourceEditorInput.ts#L84-L90
