### ISSUE TITLE
Popup to chose environment shouldnt show up when file type is supported by debugger from an extension

### ISSUE THREAD

**Issue by ramya-rao-a** [Microsoft/vscode#19269]
Testing #18397 on Windows

- I have the Go extension installed and Go workspace opened with no launch.json file.
- There is a Go file opened in the active editor.
- I click on the gear button in the debug side pane to create the launch.json file and there is a pop up asking me to choose the environment.

According to the test plan, the Go environment should have been automatically chosen:

> Once you want to generate the launch.json it will only ask to choose the environment if the currently open file type is not supported by any debugger. 

In case you don't have Go and the Go extension installed, follow the below steps:
1. Install [Go](https://golang.org/doc/install#install)
2. Setup GOPATH
       1. Choose a folder where you will be having the Go projects
       2. Add env variable GOPATH with value as the above folder path
       3. Create 3 folders "src", "bin" and "pkg"
3. Run `go get github.com/golang/example/hello`
4. Install the Go extension by lukehoban and open the folder $GOPATH/src/GitHub.com/golang/example/hello in VS Code
5. Open the `hello.go` file. You will see "Analysis Tools Missing" in the status bar. Click on it to install the Go tools that the extension needs.

**Comment by isidorn** [comment]
Exactly! However this need to be suported by the go debug extension, namely the go extension needs to contribute to the debugger that it is interested in .go files.
Node does that in the [following way](https://github.com/Microsoft/vscode-node-debug/blob/master/package.json#L96)
More about `lanugages` contribution can be found [here](https://github.com/Microsoft/vscode/issues/285#issuecomment-271324742)

Assigning to @ramya-rao-a to adopt this in the go extension

**Comment by ramya-rao-a** [comment]
Done https://github.com/Microsoft/vscode-go/commit/b809acd817b75a8e3f8275eb75043502957e34a6
Thanks @isidorn
