### ISSUE TITLE
Callback functions don't have the expected indentation

### ISSUE THREAD

**Issue by battmanz** [Microsoft/vscode#19260]
In TypeScript (maybe other languages too), callback functions don't have the expected indentation when placed on a new line. Such is the case when using the `subscribe` method on an `Observable` in [rxjs](https://github.com/ReactiveX/rxjs).

- VSCode Version: 1.8.1
- OS Version: macOS Sierra

Steps to Reproduce:

1. The following file was formatted using the keyboard shortcut. Notice how the `onNext` and `onError` callbacks line up with the `subscribe` method.
![screen shot 2017-01-24 at 12 07 33 pm](https://cloud.githubusercontent.com/assets/1054833/22262322/b6b4c180-e22d-11e6-99fc-0945be261180.png)

2. I would rather see those two callbacks indented one more level like so:
![screen shot 2017-01-24 at 12 09 00 pm](https://cloud.githubusercontent.com/assets/1054833/22262386/ea693128-e22d-11e6-980b-bd522fbe02a8.png)

**Comment by mousetraps** [comment]
Thanks for reporting! Confirmed this issue impacts both javascript and typescript. 
```js
function the() {
	return quick
		.brown(
		fox => console.log('jumped'),
		over => console.log('the'),
		lazy => console.log('dog')
		);
}
```
cc @mjbvz

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript#13688
