### ISSUE TITLE
add-zsh-hook: function definition file not found

### ISSUE THREAD

**Issue by aremmell** [microsoft/vscode#192680]
Type: <b>Bug</b>

Start VS Code with zsh as your integrated shell. These lines in your .zshrc (186, 187 here) are triggering this to appear every time I start the terminal:

add-zsh-hook precmd __vsc_precmd
add-zsh-hook preexec __vsc_preexec

VS Code version: Code 1.82.0 (Universal) (8b617bd08fd9e3fc94d14adb8d358b56e3f72314, 2023-09-06T22:09:41.364Z)
OS version: Darwin x64 22.6.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) W-2140B CPU @ 3.20GHz (16 x 3200)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|64.00GB (42.23GB free)|
|Process Argv|--crash-reporter-id aa025d80-5453-4b0c-a506-907ee0172e23|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (29)</summary>

Extension|Author (truncated)|Version
---|---|---
codesnap|adp|1.3.4
vscode-intelephense-client|bme|1.9.5
path-intellisense|chr|2.8.4
vsc-material-theme|Equ|33.10.5
copilot|Git|1.110.389
php-cs-fixer|hig|1.2.7
output-colorizer|IBM|0.1.2
better-cpp-syntax|jef|1.17.2
icons-octicons|joa|0.1.0
vscode-peacock|joh|4.2.2
fluent-icons|mig|0.0.18
python|ms-|2023.16.0
vscode-pylance|ms-|2023.9.10
remote-ssh|ms-|0.106.2
cmake-tools|ms-|1.15.31
cpptools|ms-|1.17.5
cpptools-extension-pack|ms-|1.3.0
hexeditor|ms-|1.9.12
color-highlight|nau|2.5.0
material-icon-theme|PKi|4.30.1
vscode-xml|red|0.26.1
vscode-yaml|red|1.14.0
bootstrap-product-icons|rub|1.0.2
rust-analyzer|rus|0.3.1649
ayu|tea|1.0.5
python-docs-opener|Tho|1.1.1
vscode-icons|vsc|12.5.0
material-theme|zhu|3.16.0
swig|zhu|0.0.5

(13 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscorecescf:30445987
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
py29gd2263:30792226
vscaac:30438847
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
vsccc:30803844
2e4cg342:30602488
f6dab269:30613381
2i9eh265:30646982
showlangstatbar:30737416
0bi6i642:30831757
03d35959:30757346
pythonfmttext:30731395
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
pythonnosmt12:30797651
pythonidxpt:30805730
pythonnoceb:30805159
dsvsc013:30795093
dsvsc014:30804076
diffeditorv2:30821572
dsvsc015cf:30829746

```

</details>

**Comment by aremmell** [comment]
FWIW, `type add-zsh-hook` says 'add-zsh-hook is an autoload shell function'

**Comment by meganrogge** [comment]
do you know where your function definitions are defined? I think that needs to be on your `$fpath` for this to work.

**Comment by aremmell** [comment]
Update: I broke this myself somehow; I found some half-written bit of script in my `.zshrc` that was munging up fpath. You can forget this. I apologize.
