### ISSUE TITLE
"Press ctrl+I to ask Copilot ...` message showing in empty output channel

### ISSUE THREAD

**Issue by andreamah** [microsoft/vscode#192619]
Steps:
1. Open an empty output channel. To do this, you can open an HTML file from a fresh reload and then check the HTML language server output channel.
2. The output channel says "Press `CTRL`+`I` to ask Copilot to do something. 

![Image](https://github.com/microsoft/vscode/assets/31675041/129778b6-a686-4336-9ce2-9347c09bd0da)

**Comment by joyceerhl** [comment]
\closedWith 079d0abf1cdfa6b46f64c8dcbaea4d6925d7e4fc

**Comment by P-polycephalum** [comment]
How do i disactivate this, it doesnt allows me to choose my langauge of preference
