### ISSUE TITLE
Debug Console can not reflush automatically

### ISSUE THREAD

**Issue by youxiaotu** [microsoft/vscode#192655]
Type: <b>Bug</b>

When I use DEBUG CONSOLE, the window does not pop up with the appropriate result after entering the command. But the result can be refreshed passively by switching windows.

VS Code version: Code 1.82.0 (8b617bd08fd9e3fc94d14adb8d358b56e3f72314, 2023-09-06T22:07:07.438Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Remote OS version: Linux x64 6.2.0-26-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|12th Gen Intel(R) Core(TM) i9-12900H (20 x 2918)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.73GB (16.71GB free)|
|Process Argv|--crash-reporter-id 69028db2-871f-4d16-8a87-8a4f6640cde7|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: SURF-LINUX|
|OS|Linux x64 6.2.0-26-generic|
|CPUs|13th Gen Intel(R) Core(TM) i9-13900K (32 x 3000)|
|Memory (System)|62.57GB (54.99GB free)|
|VM|0%|
</details><details><summary>Extensions (23)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|3.0.2
vscode-drawio|hed|1.6.6
jupyter-keymap|ms-|1.1.2
remote-containers|ms-|0.309.0
remote-ssh|ms-|0.106.2
remote-ssh-edit|ms-|0.86.0
remote-explorer|ms-|0.4.1
swdc-vscode|sof|2.7.0
pdf|tom|1.2.2
vscode-icons|vsc|12.5.0
gitlens|eam|14.3.0
copilot|Git|1.110.389
copilot-chat|Git|0.7.0
todo-tree|Gru|0.0.226
python|ms-|2023.17.12511005
vscode-pylance|ms-|2023.9.10
jupyter|ms-|2023.8.1002501831
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.17
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-slideshow|ms-|0.1.5
autodocstring|njp|0.6.1
vscode-wakatime|Wak|24.2.2

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscoreces:30445986
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
vscccc:30803845
3biah626:30602489
f6dab269:30613381
a9j8j154:30646983
showlangstatbar:30737416
0bi6i642:30831757
03d35959:30757346
pythonfmttext:30731395
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
pythonnosmt12:30797651
pythonidxpt:30805730
pythonnoceb:30805159
dsvsc013:30795093
dsvsc014:30804076
diffeditorv2:30821572
dsvsc015:30829745

```

</details>

**Comment by youxiaotu** [comment]
Further findings: This bug can only be triggered when clicking the restart button during a debugging process

**Comment by jevnikar** [comment]
Same issue, intermittently. Trying to debug Python 

Version: 1.82.0 (user setup)
Commit: 8b617bd08fd9e3fc94d14adb8d358b56e3f72314
Date: 2023-09-06T22:07:07.438Z
Electron: 25.8.0
ElectronBuildId: 23503258
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.19045

**Comment by roblourens** [comment]
https://github.com/microsoft/vscode/issues/192653 Can you check the developer tools for errors (Help > Toggle Developer Tools)?
