### ISSUE TITLE
Terminal cursor doesn't change when in override / insert mode 

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#19263]
Test: https://github.com/Microsoft/vscode/issues/19071

- VSCode Version: 1.9
- OS Version: Windows

Steps to Reproduce:

1. start cmd.exe
2. toggle between insert and override mode (insert key)

Observe: the cursor stays the same however the functionality works as expected. Would be nice if the cursor would change like in cmd.exe

**Comment by Tyriar** [comment]
How other terminals behave:

Windows 10:

- cmd.exe: Toggle insert mode
- powershell: Ignore
- git bash: Paste

**Comment by Tyriar** [comment]
Linux:

gnome-terminal/bash: Add `~`
gnome-terminal/zsh: Ignore

**Comment by Tyriar** [comment]
@dbaeumer is this more of a completeness request or is there a good reason for it? I'm hesitant to add since it's only cmd and I wouldn't think that many people would rely on it.

**Comment by dbaeumer** [comment]
CMD.exe behaves correct however the feedback is missing. For sure not critical.

**Comment by Tyriar** [comment]
Support for this would need to be added in https://github.com/rprichard/winpty, closing off since it's a minor feature request.
