### ISSUE TITLE
Cannot connect to the server after update

### ISSUE THREAD

**Issue by LOLIN-G** [microsoft/vscode#192646]
The updated version is:

Version: 1.82.0 (Universal)
OS: Darwin arm64 22.1.0

The issue is "Cannot reconnect. Please reload the window."

But as I reload the window, it shows "waiting for port forwarding to be ready"

=================
Update: I uninstalled the extension "WSL" and it solves the problem.

=================
Update:
Per #192740 , changing the SSH extension to the pre-release version can also help

**Comment by binnn6** [comment]
https://github.com/microsoft/vscode/issues/192647 mybe same problem.

**Comment by RTnhN** [comment]
I had the same problem. I had to roll back to the last version: 1.81.1

**Comment by ronen-fr** [comment]
same here...

**Comment by RTnhN** [comment]
> For me, I remove the extension "WSL" then it solves the problem.

That worked for me too. I run Ubuntu, so it's a bit strange that it was enabled in the first place.

**Comment by BIAOXYZ** [comment]
> For me, I remove the extension "WSL" then it solves the problem.

Thx, after uninstall the WSL extension, all goes well.

**Comment by perone** [comment]
Just disabling (without removing) the WSL extension works fine as well, this seems to be a bug introduced in the 1.82.

**Comment by gopiextrahop** [comment]
Thanks so much. Uninstalling WSL extension solved it. vscode has been causing a lot of issues with every upgrade recently. I detest doing upgrades. The quality of releases is down the drain particularly for MacOS users.

**Comment by roblourens** [comment]
What was the issue here @connor4312? Can someone confirm that it is now works even when the WSL extension is installed?

**Comment by connor4312** [comment]
0. Be on macOS and have the WSL extension installed
1. Set `remote.SSH.useExecServer: false` in your settings
2. Connect to a remote SSH host and verify things work

**Comment by roblourens** [comment]
Ok I wasn't sure if it was as simple as it sounded 😆
