### ISSUE TITLE
debug issue

### ISSUE THREAD

**Issue by Rakeshkohli** [microsoft/vscode#192673]
Type: <b>Feature Request</b>

When i compile the c program it shows an error. (The prelaunchTask 'c/c++:g++.exe build active file terminated with exit code -1. and error are show in terminal not in problems column. Please solve this issue,

VS Code version: Code 1.82.0 (8b617bd08fd9e3fc94d14adb8d358b56e3f72314, 2023-09-06T22:07:07.438Z)
OS version: Windows_NT x64 10.0.19045
Modes:

**Comment by roblourens** [comment]
This sounds like an issue with the C++ extension's task
