### ISSUE TITLE
Vs code startup issue

### ISSUE THREAD

**Issue by vusal5555** [microsoft/vscode#192670]
Type: <b>Performance Issue</b>

When I close vs code and start it immediatelly it takes some time to open. At first it opens fast but then when I close and try to reopen it, it lags a bit. This would not happen before.

VS Code version: Code 1.82.0 (8b617bd08fd9e3fc94d14adb8d358b56e3f72314, 2023-09-06T22:07:07.438Z)
OS version: Windows_NT x64 10.0.22621
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10700F CPU @ 2.90GHz (16 x 2904)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.92GB (8.47GB free)|
|Process Argv|--crash-reporter-id 794ebb75-3150-45d2-ba79-244d0342617a|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	   130	 11432	code main
    0	   198	  1328	window [1] (Vusal's workspace (Workspace) - Visual Studio Code)
    0	    87	  1904	window [2] (Issue Reporter)
    0	    85	  4296	fileWatcher [1]
    0	    72	  5656	   utility-network-service
    0	    70	  5688	   crashpad-handler
    0	   213	 13052	extensionHost [1]
    0	    82	  2176	     electron-nodejs ("C:\Users\vusal\AppData\Local\Programs\Microsoft VS Code\Code.exe" --ms-enable-electron-run-as-node c:\Users\vusal\.vscode\extensions\kisstkondoros.vscode-gutter-preview-0.30.0\dist\server.js --node-ipc --clientProcessId=13052)
    0	    80	  7484	     electron-nodejs ("C:\Users\vusal\AppData\Local\Programs\Microsoft VS Code\Code.exe" --ms-enable-electron-run-as-node "c:\Users\vusal\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\json-language-features\server\dist\node\jsonServerMain" --node-ipc --clientProcessId=13052)
    0	    78	  7964	     electron-nodejs ("C:\Users\vusal\AppData\Local\Programs\Microsoft VS Code\Code.exe" --ms-enable-electron-run-as-node c:\Users\vusal\.vscode\extensions\formulahendry.auto-rename-tag-0.1.10\packages\server\dist\serverMain.js --node-ipc --clientProcessId=13052)
    0	   125	 13440	   gpu-process
    0	   126	 14420	shared-process
```

</details>
<details>
<summary>Workspace Info</summary>

```
;
```

</details>
<details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-tailwindcss|bra|0.10.0
es7-react-js-snippets|dsz|4.4.3
prettier-vscode|esb|10.1.0
auto-close-tag|for|0.5.14
auto-rename-tag|for|0.1.10
vscode-gutter-preview|kis|0.30.0
dotenv|mik|1.0.1
color-highlight|nau|2.5.0
material-icon-theme|PKi|4.30.1

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
py29gd2263cf:30792227
vscaat:30438848
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
vsccc:30803844
282f8724:30602487
f6dab269:30613381
a9j8j154:30646983
showlangstatbar:30737416
962ge761:30831758
03d35959:30757346
pythonfmttext:30731395
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
pythonnosmt12:30797651
pythonidxpt:30805730
pythonnoceb:30805159
synctok:30821570
dsvsc013:30795093
dsvsc014:30804076
diffeditorv2:30821572
dsvsc015:30829745

```

</details>

**Comment by liu-zw** [comment]
I have similar issue.  Vscode always startup slow on even number of times while it startup normally on odd number of times.
VS Code version: 1.82.2 abd2f3db4bdb28f9e95536dfa84d8479f1eb312d 2023-09-14T05:51:20.981Z
OS version: Fedora Linux 38 X64

System Info:
CPUs | Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 4000)
-- | --
GPU Status | 2d_canvas: enabled canvas_oop_rasterization: disabled_off direct_rendering_display_compositor: disabled_off_ok gpu_compositing: enabled multiple_raster_threads: enabled_on opengl: enabled_on rasterization: enabled raw_draw: disabled_off_ok video_decode: enabled video_encode: disabled_software vulkan: disabled_off webgl: enabled webgl2: enabled webgpu: disabled_off
Load (avg) | 0, 0, 0
Memory (System) | 15.39GB (12.01GB free)
Process Argv | --unity-launch --crash-reporter-id da996669-10c6-47aa-b6a8-92ffd0b7577b
Screen Reader | no
VM | 0%

A/B Experiments
```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
py29gd2263cf:30792227
vscaac:30438847
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
vscccc:30803845
2e4cg342:30602488
f6dab269:30613381
2i9eh265:30646982
showlangstatbar:30737416
0bi6i642:30835152
03d35959:30757346
pythonfmttext:30731395
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
pythonnosmt12:30797651
pythonidxpt:30805730
pythonnoceb:30805159
synctok:30821570
dsvsc013:30795093
dsvsc014:30804076
diffeditorv2:30821572
dsvsc015cf:30829746
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
py29gd2263cf:30792227
vscaac:30438847
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
vscccc:30803845
2e4cg342:30602488
f6dab269:30613381
2i9eh265:30646982
showlangstatbar:30737416
0bi6i642:30835152
03d35959:30757346
pythonfmttext:30731395
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
pythonnosmt12:30797651
pythonidxpt:30805730
pythonnoceb:30805159
synctok:30821570
dsvsc013:30795093
dsvsc014:30804076
diffeditorv2:30821572
dsvsc015cf:30829746
```

I have used Startup Performance to gather some information, the following is the main difference between startup an odd number of times and an even number of times.
![image](https://github.com/microsoft/vscode/assets/58103058/3347a4fd-90e4-4cc8-b69e-affc510e9f0c)
![image](https://github.com/microsoft/vscode/assets/58103058/a3e67a00-3a4a-4a88-82da-57cb157422d8)

I have already tried to disable all extensions and disable gpu, but it reproduced.

**Comment by bpasero** [comment]
Do you have AV software installed such as https://github.com/microsoft/vscode/issues/178962 ?

**Comment by liu-zw** [comment]
> Do you have AV software installed such as #178962 ?

There is no AV software installed.

**Comment by bpasero** [comment]
Can you follow this wiki and post the results back here to understand more about why performance is so bad for you: https://github.com/Microsoft/vscode/wiki/Performance-Issues

Thanks!

**Comment by x-hgg-x** [comment]
Same issue as https://github.com/microsoft/vscode/issues/192493.
