### ISSUE TITLE
Rectangular selection doesn't work

### ISSUE THREAD

**Issue by ayeressian** [Microsoft/vscode#1926]
I hold alt and click and hold left mouse button. It doesn't select the text in rectangular way.
I am running OSX elcapitan.

**Comment by isidorn** [comment]
This is a feature that for instance sublime text supports, but we do not have it yet. I noticed that sublime text inserts multi cursors

**Comment by glen-84** [comment]
Duplicate of #84?

**Comment by alexandrudima** [comment]
:+1: I'll keep this one around, as it gives a great concise description of what should be implemented
