### ISSUE TITLE
Terminal should inherit fontFamily and fontSize from editor

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#19265]
Test: https://github.com/Microsoft/vscode/issues/19071

- VSCode Version: 1.9
- OS Version: Windows

Steps to Reproduce:

1. Have the following settings
```
	"editor.fontFamily": "hack",
	"editor.fontSize": 13,
```

2. Open the terminal

The fontSize seems to be 14. The font is not fully clear to. Would be nice if the terminal inherits the settings from the editor.

**Comment by Tyriar** [comment]
It was in 1.7.0 but I removed it since it was weird that the terminal was scaling with the editor when it was part of the workbench (when output, debug console, problem, etc. don't).
