### ISSUE TITLE
PowerShell terminal is displaying dark colors as bright colors

### ISSUE THREAD

**Issue by SetTrend** [microsoft/vscode#192640]
Even though I set the minimum contrast ratio to "1", PowerShell terminal is displaying dark colors as bright colors:

![No dark colors PowerShell](https://github.com/microsoft/vscode/assets/9283914/d32382b2-a80c-4704-80fe-dee4e4ee8695)

## VS Code/OS Version:

```
Version: 1.82.0 (user setup)
Commit: 8b617bd08fd9e3fc94d14adb8d358b56e3f72314
Datum: 2023-09-06T22:07:07.438Z
Electron: 25.8.0
ElectronBuildId: 23503258
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
Betriebssystem: Windows_NT x64 10.0.19045
```

## Steps to Reproduce:

1. Type
   ```ps
   Write-Host -ForegroundColor Yellow 'Test'
   ```
1. Type
   ```ps
   Write-Host -ForegroundColor DarkYellow 'Test'
   ```

**Comment by Tyriar** [comment]
This is working as designed because it's up to the theme to control these colors:

![image](https://github.com/microsoft/vscode/assets/2193314/5c631ef2-963a-4a99-bc02-efe1e91297a0)

@daviddossett a slight differentiation of these colors would be nice in the new modern themes

**Comment by SetTrend** [comment]
Thank you.

This is particularly necessary to test and verify the output of a PowerShell script that's supposed to be published.

Without these dimmed colors, it is impossible to highlight portions of a text, and the setting `terminal.integrated.drawBoldTextInBrightColors` doesn't make sense.

**Comment by Tyriar** [comment]
@SetTrend VS Code supports it fine, just the default themes don't. So in the meantime you should change your theme to one that has different colors for the bright colors, or set them manually via the `workbench.colorCustomizations` setting
