### ISSUE TITLE
Shellscript syntax issues when case clauses are terminated with `;&` or `;;&`

### ISSUE THREAD

**Issue by rhenescu** [microsoft/vscode#192701]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.82.0 (and lower)
- OS Version: Windows, Linux (various versions)

According to the [Bash Reference Manual](https://www.gnu.org/software/bash/manual/bash.html#index-case), a case clause must be terminated with `;;`, `;&`, or `;;&`. Currently, the shellscript grammar only supports `;;`. Using `;&` or `;;&` affects the coloring of subsequent comments or clause patterns:

![Shellscript issue](https://github.com/microsoft/vscode/assets/6264315/67ed920e-a1a8-446e-ba1a-470cd89ea421)

**Comment by alexr00** [comment]
Copied to https://github.com/jeff-hykin/better-shell-syntax/issues/66, which is where we get our shellscript syntax highlighting grammar from.
