### ISSUE TITLE
Open folder from explorer by context menu

### ISSUE THREAD

**Issue by zewwo-boi** [microsoft/vscode#192734]
It would be nice if I could open a folder from the Explorer directly by adding a button to the context menu. This would prevent me from having to use the **Open Folder** function and going through the native file explorer all over again.

**Comment by gjsjohnmurray** [comment]
Does this extension do what you want?

https://marketplace.visualstudio.com/items?itemName=chrisdias.vscode-opennewinstance

**Comment by zewwo-boi** [comment]
> Does this extension do what you want?
> 
> https://marketplace.visualstudio.com/items?itemName=chrisdias.vscode-opennewinstance

That's pretty nice! But I wonder if it could be integrated into vs code itself. For a feature so simple, it would be great to have native support.
