### ISSUE TITLE
Why the ... at the end of "Add Configuration" ?

### ISSUE THREAD

**Issue by ramya-rao-a** [Microsoft/vscode#19274]
Testing #19033

![image](https://cloud.githubusercontent.com/assets/16890566/22264628/910a256a-e22d-11e6-8808-b132c7bc3a45.png)

It might be because there is more user input needed. 
In that case, we should add the dots to the button as well?

![image](https://cloud.githubusercontent.com/assets/16890566/22264612/7c10161a-e22d-11e6-993c-53d3a42c6085.png)

**Comment by isidorn** [comment]
We always use dots in our ux to notify the user that the action will require another action to be executed after that. In this case inteli-sense will get opened after this is clicked. Due to that I also added the dots in the blue button
