### ISSUE TITLE
Interactive editor session is not released

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode#192748]
Version: 1.83.0-insider
Commit: 3c133b63c6e17e2fe33f37db93a6d43e78a262c5
Date: 2023-09-11T05:32:58.945Z
Electron: 25.8.0
ElectronBuildId: 23503258
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Linux x64 5.15.0-79-generic

- Implement an extension with a InteractiveEditorSessionProvider
```
	vscode.interactive.registerInteractiveEditorSessionProvider({
		label: 'Test',
		prepareInteractiveEditorSession(context, token) {
			console.log(`prepareInteractiveEditorSession`, context);
			return { placeholder: "Test it now" } as vscode.InteractiveEditorSession;
		},
		provideInteractiveEditorResponse(request, token) {
			return { edits: [] };
		},
		releaseInteractiveEditorSession(session) {
			console.log(`releaseInteractiveEditorSession`, session);
		}
	});
```
- In the editor, start a code chat (Ctrl+K I)
- `prepareInteractiveEditorSession` is invoked
- leave the window with `escape`. I would expect that `releaseInteractiveEditorSession` is called
- same after interacting with the chat and accepting or discarding

**Comment by jrieken** [comment]
Yeah, that's on purpose. We keep the session around for the case of hitting ESC by accident. In that case undo will restore it. Once you start typing or do other things will be released

**Comment by aeschli** [comment]
What about on accepting or discarding? Or editor close?
