### ISSUE TITLE
Merging of args of tasks

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode#19278]
Testing #19044:

Not sure if I undertstood the mergin of args correctly
```json
{
    "version": "0.1.0",
    "showOutput": "always",
    
    "tasks": [
        {
            "taskName": "list",
            "command": "ls",
            "args": [ "-X"],
            "linux": {
                "command": "ls",
                "args": [ "-l"],
                "isShellCommand": true
            }
        }       
    ],
    "_runner": "terminal" 
}
```

Shouldn't this (on linux) run `ls -X -l` ?
It seems only `ls -l` is used

**Comment by dbaeumer** [comment]
Actually it should execute `ls -X -l`. Will look into it to understand what goes wrong here. I merge the args since I always merged them if the command was global. So I wanted to keep the same behavior.

**Comment by dbaeumer** [comment]
I tested it and the arguments are merged. I added a test case as well.
