### ISSUE TITLE
Preview Mode Rendering Incorrectly in Dark Mode Themes

### ISSUE THREAD

**Issue by jvanord** [microsoft/vscode#192777]
[Type:](url) <b>Bug</b>

1. Open VS Code and create a new document that could be viewed in Preview (e.g. a Markdown document)
2. Switch to and dark theme in VS Code
3. Open the document created above in Preview. 
    Expected result: document renders with dark background and light foreground as per theme
   Actual result: document renders with dark background and dark foreground (after a very brief moment where the rendering seems correct)
4. Change to any light theme and the Preview renders correctly
5. Change back to any dark theme and the incorrect rendering continues

https://github.com/microsoft/vscode/assets/17397251/c72acca6-6d35-4add-9143-e6db452ab5ce

VS Code version: Code 1.82.0 (8b617bd08fd9e3fc94d14adb8d358b56e3f72314, 2023-09-06T22:07:07.438Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

https://github.com/microsoft/vscode/assets/17397251/c72acca6-6d35-4add-9143-e6db452ab5ce

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2808)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|63.83GB (53.31GB free)|
|Process Argv|--folder-uri file:///c%3A/Users/Jay/Desktop/TODO --crash-reporter-id e86416f8-cd77-45ee-bfdf-3adc49a83d84|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
markdown-mermaid|bie|1.19.0
vscode-eslint|dba|2.4.2
miniprettier|dua|0.1.0
gitlens|eam|14.3.0
dotnet-test-explorer|for|0.7.8
vscode-edit-csv|jan|0.8.2
select-highlight-minimap|mde|0.1.0
csharp|ms-|2.1.2
vscode-dotnet-runtime|ms-|1.7.2
remote-wsl|ms-|0.81.2
cpptools|ms-|1.17.5
vs-keybindings|ms-|0.2.1
markdown-all-in-one|yzh|3.5.1

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
vsccc:30803844
282f8724:30602487
89544117:30613380
showlangstatbar:30737416
962ge761:30831758
03d35959:30757346
pythonfmttext:30731395
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
pythonnosmt12:30797651
pythonidxpt:30805730
pythonnoceb:30805159
synctok:30821570
dsvsc013:30795093
dsvsc014:30804076
diffeditorv2:30821572
dsvsc015:30829745

```

</details>

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

**Comment by jvanord** [comment]
It _does not_ reproduce in 1.38.0-insider. It _does_ reproduce in 1.82.0 with all extensions disabled.

**Comment by mjbvz** [comment]
Are you sure it's not one of your markdown extensions? Disable them and then restart VS Code to make sure

**Comment by jvanord** [comment]
It was indeed an extension. Even opening a new window with `code --disable-extensions` didn't change the behavior, but a full restart helped reveal the true culprit: "Markdown Preview Enhanced" (shd101wyy.markdown-preview-enhanced). 

Thanks! Closing ...
