### ISSUE TITLE
Test suite `InteractiveChatController` instantiates a real code editor

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#192778]
Steps to Reproduce:

1. debug the `InteractiveChatController` by having a breakpoint in `CodeEditorWidget` constructor
2. notice how you end up in the full code editor widget via:

```
CodeEditorWidget (/Users/bpasero/Development/Microsoft/vscode/src/vs/editor/browser/widget/codeEditorWidget.ts:286)
EmbeddedCodeEditorWidget (/Users/bpasero/Development/Microsoft/vscode/src/vs/editor/browser/widget/embeddedCodeEditorWidget.ts:43)
_createInstance (/Users/bpasero/Development/Microsoft/vscode/src/vs/platform/instantiation/common/instantiationService.ts:119)
createInstance (/Users/bpasero/Development/Microsoft/vscode/src/vs/platform/instantiation/common/instantiationService.ts:85)
InlineChatWidget (/Users/bpasero/Development/Microsoft/vscode/src/vs/workbench/contrib/inlineChat/browser/inlineChatWidget.ts:217)
_createInstance (/Users/bpasero/Development/Microsoft/vscode/src/vs/platform/instantiation/common/instantiationService.ts:119)
createInstance (/Users/bpasero/Development/Microsoft/vscode/src/vs/platform/instantiation/common/instantiationService.ts:85)
InlineChatZoneWidget (/Users/bpasero/Development/Microsoft/vscode/src/vs/workbench/contrib/inlineChat/browser/inlineChatWidget.ts:806)
_createInstance (/Users/bpasero/Development/Microsoft/vscode/src/vs/platform/instantiation/common/instantiationService.ts:119)
createInstance (/Users/bpasero/Development/Microsoft/vscode/src/vs/platform/instantiation/common/instantiationService.ts:85)
<anonymous> (/Users/bpasero/Development/Microsoft/vscode/src/vs/workbench/contrib/inlineChat/browser/inlineChatController.ts:132)
get value (/Users/bpasero/Development/Microsoft/vscode/src/vs/base/common/lazy.ts:30)
getWidgetPosition (/Users/bpasero/Development/Microsoft/vscode/src/vs/workbench/contrib/inlineChat/browser/inlineChatController.ts:186)
<anonymous> (/Users/bpasero/Development/Microsoft/vscode/src/vs/workbench/contrib/inlineChat/test/browser/inlineChatController.test.ts:156)
callFn (/Users/bpasero/Development/Microsoft/vscode/node_modules/mocha/mocha.js:23248)
Runnable.run (/Users/bpasero/Development/Microsoft/vscode/node_modules/mocha/mocha.js:23234)
Runner.runTest (/Users/bpasero/Development/Microsoft/vscode/node_modules/mocha/mocha.js:24862)
<anonymous> (/Users/bpasero/Development/Microsoft/vscode/node_modules/mocha/mocha.js:24992)
next (/Users/bpasero/Development/Microsoft/vscode/node_modules/mocha/mocha.js:24769)
<anonymous> (/Users/bpasero/Development/Microsoft/vscode/node_modules/mocha/mocha.js:24779)
```

I think this should be using the test code editor that we have for this purpose to speed up the test.

![image](https://github.com/microsoft/vscode/assets/900690/d3db0a31-cbfd-46f6-bd7b-b4c022576bc9)

**Comment by jrieken** [comment]
I don't think this can be done. The first editor is the test editor but the controller creates embedded editors (for the embedded diff, input etc). This problem isn't unique to inline chat, all parts that create downlevel editor will have this problem

**Comment by bpasero** [comment]
Yeah tricky, I was hoping that the test code editor could help:

https://github.com/microsoft/vscode/blob/406fab60ac8f62b9032afc79fb15c5122ebd19f9/src/vs/workbench/contrib/inlineChat/test/browser/inlineChatController.test.ts#L122

But in the end the real code editor gets created from here:

https://github.com/microsoft/vscode/blob/406fab60ac8f62b9032afc79fb15c5122ebd19f9/src/vs/workbench/contrib/inlineChat/browser/inlineChatWidget.ts#L217

I only noticed this because of the Chrome spam output on macOS (`CoreText note..`) which is the same we get when running VSCode normally from the command line (upstream Chrome [bug](https://bugs.chromium.org/p/chromium/issues/detail?id=1131559&q=NewYork-Regular&can=2)).

Btw enabling `ensureNoDisposablesAreLeakedInTestSuite()` seems to work fine now in that test, even with the real code editor.

**Comment by jrieken** [comment]
closing without action
