### ISSUE TITLE
"terminal.integrated.scrollback": 0 results in funny terminal behavior

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#19277]
Test: https://github.com/Microsoft/vscode/issues/19071

- VSCode Version: 1.9
- OS Version: Windows

May be we should have a minimal scrollback value.

**Comment by dbaeumer** [comment]
All values lower than the view port height cause funny behavior.

**Comment by dbaeumer** [comment]
Actually it didn't hang. The problem was that the screen goes blank after a cls. Same happens in bash.

![cast](https://cloud.githubusercontent.com/assets/1931590/22265435/51a4fcca-e27c-11e6-9735-ebe69492796b.gif)

In the screen cast I was pressing cursor keys and enter

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/19193
