### ISSUE TITLE
tsconfig.json references navigation doesn't understand folder references

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#192772]
Navigating to the valid `./src` goes to `<folder>/src.json`, not the expected `<folder>/src/tsconfig.json`

![Image](https://github.com/microsoft/vscode/assets/2193314/8938ffc6-1381-40e2-8d6b-27385d45c636)

**Comment by ronakj** [comment]
Fixed it in this PR #192851 (my first contribution to vscode 🎉)

**Comment by AP1400** [comment]
> Navigating to the valid `./src` goes to `<folder>/src.json`, not the expected `<folder>/src/tsconfig.json`
> 
> ![Image](https://user-images.githubusercontent.com/2193314/267036145-8938ffc6-1381-40e2-8d6b-27385d45c636.gif) [ ![Image](https://user-images.githubusercontent.com/2193314/267036145-8938ffc6-1381-40e2-8d6b-27385d45c636.gif) ](https://user-images.githubusercontent.com/2193314/267036145-8938ffc6-1381-40e2-8d6b-27385d45c636.gif) [ ](https://user-images.githubusercontent.com/2193314/267036145-8938ffc6-1381-40e2-8d6b-27385d45c636.gif)

Get f out

**Comment by GetPsyched** [comment]
Please close this issue if it has been already fixed in a PR.
