### ISSUE TITLE
Task runner writes to output and terminal

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode#19276]
Testing #19044
```json
{
    "version": "0.1.0",
    "showOutput": "always",
    
    "tasks": [
        {
            "taskName": "list",
            "command": "ls",
            "options": {
                "cwd": "./.."
            },
            "linux": {
                "command": "ls",
                "args": [ "-l"],
                "isShellCommand": true
            }
        }       
    ],
    "_runner": "terminal" 
}
```
When executing this, the following message is written to the output view:
The task list is a shell command and specifies arguments. To ensure correct command line quoting please merge args into the command.

The output is in the terminal.
Maybe better everything in the terminal?
Also I'm not really sure what the message means. Maybe that information should better be shown in the task.json.

**Comment by dbaeumer** [comment]
@aeschli I like the idea of showing a message in the tasks.json. Is the possible with JSON schema or do I need to implement my own validation provider. I would like to express if propery `isShellCommand` args should be [] or undefined. 

I should also improve the error handling and only warn if the args or the command contain spaces. Otherwise the simply join will do the right thing.

**Comment by aeschli** [comment]
It's tricky with the schema but you should try it with a oneOf. Maybe it works. I didn't try it out, but the code should validate based on the most specific option.
```javascript
{
oneOf: [{ 
   properties: {
       isShellCommand: {
          enum: ['true']
       },
       args: {
          deprecatedMessage: 'do not use args for shell commands'
       }
},
{ 
   properties: {
       isShellCommand: {
          enum: ['false']
       },
       args: {
       }
}
]
}
```

**Comment by dbaeumer** [comment]
I change the structure quite a lot for the API. I need to see how to fix this when the API is final.

**Comment by dbaeumer** [comment]
Slips because of the Task API focus.

**Comment by alexr00** [comment]
@dbaeumer, is this still an issue in 2.0.0?

**Comment by dbaeumer** [comment]
@alexr00 actually no. A command now supports args even in the shell case. 

Closing.
