### ISSUE TITLE
Node related configuration snippets showing up in non Node environment

### ISSUE THREAD

**Issue by ramya-rao-a** [Microsoft/vscode#19275]
Testing #19039

- I have the Go extension installed and Go workspace opened with no launch.json file.
- There is a Go file opened in the active editor.
- I click on the "Add Configuration" option in the debug drop down and there is a pop up asking me to choose the environment.
- I choose Go
- The default launch.json is created by the Go extension.
- The snippets for adding new configuration have nothing to do with Go. Why are they even showing up?

In case you don't have Go and the Go extension installed, follow the below steps:
1. Install [Go](https://golang.org/doc/install#install)
2. Setup GOPATH
       1. Choose a folder where you will be having the Go projects
       2. Add env variable GOPATH with value as the above folder path
       3. Create 3 folders "src", "bin" and "pkg"
3. Run `go get github.com/golang/example/hello`
4. Install the Go extension by lukehoban and open the folder $GOPATH/src/GitHub.com/golang/example/hello in VS Code
5. Open the `hello.go` file. You will see "Analysis Tools Missing" in the status bar. Click on it to install the Go tools that the extension needs.

**Comment by weinand** [comment]
@ramya-rao-a a launch.json is not connected to a specific debugger. It can contain launch configurations for any type of debugger, e.g. one of type `go` for a backend, and another of type `chrome` for client code running in a browser. To help with building heterogenous launch.json files VS Code shows all launch config snippets.

/cc @isidorn

**Comment by isidorn** [comment]
Created https://github.com/Microsoft/vscode-go/issues/744
