### ISSUE TITLE
MacOS: Trouble quitting VS Code (stable + insider)

### ISSUE THREAD

**Issue by rojadesign** [microsoft/vscode#192753]
Does this issue occur when all extensions are disabled?: Yes

Type: **Performance Issue**

# This is a regression of #172967.

- VS Code **Stable**: [1.82.0](https://github.com/microsoft/vscode/commit/8b617bd08fd9e3fc94d14adb8d358b56e3f72314) (latest)
- VS Code **Insider**: 1.83.0-insider (latest)
- OS Version: MacOS Ventura 13.5.2
- Macbook Pro M1 2021

VS Code has trouble quitting with the cmd+Q shortcut on macOS. When I use cmd+Q or quit it by using the menu, VS Code hangs and remains open for some time. I can tell that VS Code is open by the indicator dot under its icon in the dock. Also, after quitting, I can open VS Code again before it quits completely - then it will kill both instances, of course. But all of that is described in #172967 thoroughly.

Steps to reproduce:

- Open VS Code on macOS
- use cmd+Q to quit VS Code
- Notice that the "Code" title in the macOS menubar flashes
- Notice the dot under VS Code's icon in the dock and that VS Code remains open

Only solution for now is to disable `telemetry` as suggested in https://github.com/microsoft/vscode/issues/172967#issuecomment-1432497558.

@jungaretti @klaussner FYI, would be interesting if you can reproduce this.

**Comment by klaussner** [comment]
I could reproduce the issue with 1.83.0-insider. 👍

**Comment by jungaretti** [comment]
This _feels_ more pervasive than #172967. That one was tricky to reproduce. This issue happnes every time I `Cmd`+`Q` to quit VS Code.
