### ISSUE TITLE
In latest VSCode insiders, typing text fast breaks with Karabiner (crucial for my workflow to work)

### ISSUE THREAD

**Issue by nikitavoloboev** [microsoft/vscode#192707]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 

Version: 1.83.0-insider
Commit: b257cce9e7fa2d5f475ac16c15b40280d0b97957
Date: 2023-09-08T17:38:26.218Z
Electron: 25.8.0
ElectronBuildId: 23503258
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Darwin arm64 22.5.0

Steps to Reproduce:

1. download https://karabiner-elements.pqrs.org 
2. inside `~/.config/karabiner/karabiner.json` put this JSON:

```
{
  "global" : {
    "ask_for_confirmation_before_quitting" : true,
    "check_for_updates_on_startup" : true,
    "show_in_menu_bar" : true,
    "show_profile_name_in_menu_bar" : false,
    "unsafe_ui" : false
  },
  "profiles" : [ {
    "complex_modifications" : {
      "parameters" : {
        "basic.simultaneous_threshold_milliseconds" : 30,
        "basic.to_delayed_action_delay_milliseconds" : 0,
        "basic.to_if_alone_timeout_milliseconds" : 80,
        "basic.to_if_held_down_threshold_milliseconds" : 50
      },
      "rules" : [ {
        "description" : "test",
        "manipulators" : [ {
          "from" : {
            "key_code" : "a"
          },
          "to" : [ {
            "key_code" : "c"
          }, {
            "key_code" : "o"
          }, {
            "key_code" : "n"
          }, {
            "key_code" : "s"
          }, {
            "key_code" : "o"
          }, {
            "key_code" : "l"
          }, {
            "key_code" : "e"
          }, {
            "key_code" : "period"
          }, {
            "key_code" : "l"
          }, {
            "key_code" : "o"
          }, {
            "key_code" : "g"
          }, {
            "key_code" : "9",
            "modifiers" : [ "left_shift" ]
          }, {
            "key_code" : "0",
            "modifiers" : [ "left_shift" ]
          }, {
            "key_code" : "left_arrow"
          } ],
          "conditions" : [ {
            "name" : "dot-mode",
            "value" : 1,
            "type" : "variable_if"
          } ],
          "type" : "basic"
        }, {
          "type" : "basic",
          "parameters" : {
            "basic.simultaneous_threshold_milliseconds" : 250
          },
          "to" : [ {
            "set_variable" : {
              "name" : "dot-mode",
              "value" : 1
            }
          }, {
            "key_code" : "c"
          }, {
            "key_code" : "o"
          }, {
            "key_code" : "n"
          }, {
            "key_code" : "s"
          }, {
            "key_code" : "o"
          }, {
            "key_code" : "l"
          }, {
            "key_code" : "e"
          }, {
            "key_code" : "period"
          }, {
            "key_code" : "l"
          }, {
            "key_code" : "o"
          }, {
            "key_code" : "g"
          }, {
            "key_code" : "9",
            "modifiers" : [ "left_shift" ]
          }, {
            "key_code" : "0",
            "modifiers" : [ "left_shift" ]
          }, {
            "key_code" : "left_arrow"
          } ],
          "from" : {
            "simultaneous" : [ {
              "key_code" : "period"
            }, {
              "key_code" : "a"
            } ],
            "simultaneous_options" : {
              "detect_key_down_uninterruptedly" : true,
              "key_down_order" : "strict",
              "key_up_order" : "strict_inverse",
              "key_up_when" : "any",
              "to_after_key_up" : [ {
                "set_variable" : {
                  "name" : "dot-mode",
                  "value" : 0
                }
              } ]
            }
          }
        } ]
      } ]
    },
    "devices" : [ {
      "disable_built_in_keyboard_if_exists" : false,
      "fn_function_keys" : [ ],
      "identifiers" : {
        "is_keyboard" : true,
        "is_pointing_device" : false,
        "product_id" : 834,
        "vendor_id" : 1452
      },
      "ignore" : false,
      "manipulate_caps_lock_led" : true,
      "simple_modifications" : [ ],
      "treat_as_built_in_keyboard" : false
    }, {
      "disable_built_in_keyboard_if_exists" : false,
      "fn_function_keys" : [ ],
      "identifiers" : {
        "is_keyboard" : false,
        "is_pointing_device" : true,
        "product_id" : 834,
        "vendor_id" : 1452
      },
      "ignore" : true,
      "manipulate_caps_lock_led" : false,
      "simple_modifications" : [ ],
      "treat_as_built_in_keyboard" : false
    }, {
      "disable_built_in_keyboard_if_exists" : false,
      "fn_function_keys" : [ ],
      "identifiers" : {
        "is_keyboard" : true,
        "is_pointing_device" : false,
        "product_id" : 34304,
        "vendor_id" : 1452
      },
      "ignore" : false,
      "manipulate_caps_lock_led" : true,
      "simple_modifications" : [ ],
      "treat_as_built_in_keyboard" : false
    } ],
    "fn_function_keys" : [ {
      "from" : {
        "key_code" : "f1"
      },
      "to" : [ {
        "consumer_key_code" : "display_brightness_decrement"
      } ]
    }, {
      "from" : {
        "key_code" : "f2"
      },
      "to" : [ {
        "consumer_key_code" : "display_brightness_increment"
      } ]
    }, {
      "from" : {
        "key_code" : "f3"
      },
      "to" : [ {
        "apple_vendor_keyboard_key_code" : "mission_control"
      } ]
    }, {
      "from" : {
        "key_code" : "f4"
      },
      "to" : [ {
        "apple_vendor_keyboard_key_code" : "spotlight"
      } ]
    }, {
      "from" : {
        "key_code" : "f5"
      },
      "to" : [ {
        "consumer_key_code" : "dictation"
      } ]
    }, {
      "from" : {
        "key_code" : "f6"
      },
      "to" : [ {
        "key_code" : "f6"
      } ]
    }, {
      "from" : {
        "key_code" : "f7"
      },
      "to" : [ {
        "consumer_key_code" : "rewind"
      } ]
    }, {
      "from" : {
        "key_code" : "f8"
      },
      "to" : [ {
        "consumer_key_code" : "play_or_pause"
      } ]
    }, {
      "from" : {
        "key_code" : "f9"
      },
      "to" : [ {
        "consumer_key_code" : "fast_forward"
      } ]
    }, {
      "from" : {
        "key_code" : "f10"
      },
      "to" : [ {
        "consumer_key_code" : "mute"
      } ]
    }, {
      "from" : {
        "key_code" : "f11"
      },
      "to" : [ {
        "consumer_key_code" : "volume_decrement"
      } ]
    }, {
      "from" : {
        "key_code" : "f12"
      },
      "to" : [ {
        "consumer_key_code" : "volume_increment"
      } ]
    } ],
    "name" : "goku",
    "parameters" : {
      "delay_milliseconds_before_open_device" : 1000
    },
    "selected" : true,
    "simple_modifications" : [ {
      "from" : {
        "key_code" : "caps_lock"
      },
      "to" : [ {
        "key_code" : "escape"
      } ]
    } ],
    "virtual_hid_keyboard" : {
      "country_code" : 0,
      "indicate_sticky_modifier_keys_state" : true,
      "mouse_key_xy_scale" : 100
    }
  } ]
}
```

Then go open VSCode Insiders and press on `dot` key then press `a`. You should see this written out:

<img width="233" alt="image" src="https://github.com/microsoft/vscode/assets/6391776/b1806a6d-368b-402d-b385-4d7706fda97a">

Instead you will see this on VSCode Insiders:

<img width="408" alt="image" src="https://github.com/microsoft/vscode/assets/6391776/90add12f-3373-4bca-a21c-0ccebda93666">

This only happens in VSCode Insiders.

In normal VSCode it works correctly. As seen below:

<img width="302" alt="image" src="https://github.com/microsoft/vscode/assets/6391776/bea3cf45-4343-41b9-9300-9ba85d591530">

I don't know what happened on latest insiders but this breaking is a huge deal breaker for me. Please revert the change.

It seems VSCode Insiders broke entering symbols into the editor fast or something.

Thank you.

**Comment by nikitavoloboev** [comment]
<img width="388" alt="image" src="https://github.com/microsoft/vscode/assets/6391776/32fb0495-97cd-4d54-8ae6-f92a20ea4bae">

If I do this in https://www.keyboardmaestro.com/main/

It also will mess up.

<img width="699" alt="image" src="https://github.com/microsoft/vscode/assets/6391776/4d64471f-0299-40dc-b4b0-7a4fdc0ad707">

Basically something you've done to editor that completely messes up typing symbols fast. It just eats some symbols completely.

Please please revert this change.

**Comment by nikitavoloboev** [comment]
Just to prove its issue with latest VSCode. Here is me doing same action (Karabiner or KM macro `insert by typing` action)

In sublime text:

<img width="438" alt="image" src="https://github.com/microsoft/vscode/assets/6391776/57eb2b8d-e3f6-4dbf-bb8a-62fd713b5c9f">

In Warp terminal:

<img width="261" alt="image" src="https://github.com/microsoft/vscode/assets/6391776/ca3a653d-5a25-44d9-bbe8-8fa24ee5724c">

Literally all other inputs it works. Just VSCode breaks. Maybe some update to monaco editor breaks it?

**Comment by nikitavoloboev** [comment]
Also to prove its a regression with latest VSCode and not any other software, here I try use the `insert text by typing` in https://www.cursor.sh

<img width="497" alt="image" src="https://github.com/microsoft/vscode/assets/6391776/05125f17-40ba-4519-823b-c6536f4e897d">

As can be seen it enters it correctly.

**Comment by nikitavoloboev** [comment]
From scanning the latest commits, I think this commit can be the cause

https://github.com/microsoft/vscode/commit/41e940f76f5deda197bc5930b044c55607ba1cbc

But I can't be sure. 

It's a huge deal breaker to my workflow to be able to enter text with typing using programs like KM or Karabiner so please help me resolve the issue.

Thank you lots.

**Comment by nikitavoloboev** [comment]
Ok this is a deeper issue.

When I type things normally in VSCode, occasionally VSCode just eats the symbols. I can replicate it 100% of times.

<img width="658" alt="image" src="https://github.com/microsoft/vscode/assets/6391776/a8b773cd-e3bc-4121-ab13-6fddf9f278ed">

For example, I was just typing normally there. 

Specifically I can replicate it when I type `t` followed by `h`. The `h` will never show up. VSCode will not let me enter the symbol.

If I type `h` alone it works.

This is a huge regression as you can imagine.

Is my env setup:

```
Version: 1.83.0-insider
Commit: https://github.com/microsoft/vscode/commit/b257cce9e7fa2d5f475ac16c15b40280d0b97957
Date: 2023-09-08T17:38:26.218Z
Electron: 25.8.0
ElectronBuildId: 23503258
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Darwin arm64 22.5.0
```

I can provide any further details needed to resolve it. Thank you and I hope this can be resolved soon.

**Comment by nikitavoloboev** [comment]
Okay the issue is actually on @tekezo Karabiner Elements.

<img width="415" alt="image" src="https://github.com/microsoft/vscode/assets/6391776/86a11d4c-e571-4a38-9987-78b326e1408c">


Top is with [Karabiner Elements](https://karabiner-elements.pqrs.org) quit.

Bottom is with Karabiner Elements active. With Karabiner it eats the symbols up. 

Contacting tekezo and seeing how it can be resolved by him.

**Comment by nikitavoloboev** [comment]
<img width="654" alt="image" src="https://github.com/microsoft/vscode/assets/6391776/704da9c1-ae26-44d6-a070-87a2b17207b7">

Tested it on Monaco editor and things worked. It's something with VSCode app itself thats breaking.

**Comment by nikitavoloboev** [comment]
Ok I think the issue is with Karabiner Elements latest version, not VSCode as tested on a separate mac. 

Described it here: https://github.com/pqrs-org/Karabiner-Elements/issues/3595#issuecomment-1712873313

Will keep the issue open until @tekezo replies. In case he will need information from VSCode team to fix the issue for latest Karabiner version.

**Comment by DonJayamanne** [comment]
> Ok I think the issue is with Karabiner Elements latest version, not VSCode as tested on a separate mac.

thank you
I’m closing this issue as you have confirmed it’s not related to vscode
There are other means of communication other than just leaving this issue open
