### ISSUE TITLE
Improve 'Press any key to close the terminal' 

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode#19271]
Testing #19057

- When a task terminates, the terminal says:
'Press any key to close the terminal' 

Maybe better 'Press any key to close'.
It just closes the terminal instance. The terminal stays open if there are other instances.

**Comment by dbaeumer** [comment]
The message comes from the terminal. I only control it via a Boolean.

@Tyriar best would be if I could control the message shown. The I could show something like:

`The task xxx has finished with code: nnn. Press any key to close the terminal.`

**Comment by Tyriar** [comment]
I believe I already show a message when the task terminates with a non 0 code as well. Currently there is no way outside to send text only to the front end for rendering (bypassing the terminal process). We should try avoid adding this to the api (where tasks will be eventually) unless absolutely necessary as it could cause confusion for both the user and extension author.

**Comment by Tyriar** [comment]
Closing this as designed, it's closing the terminal, not the terminal panel. "Terminal instance" is terminology only used within code.
