### ISSUE TITLE
Decorations offset horizontally after zooming in

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#19273]
Test item #19061 

- VSCode Version: Code - Insiders 1.9.0-insider (4265f5e35cb3ea8ba7e0cf6b14ec606b6f8647ea, 2017-01-24T10:37:36.620Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: None

Steps to Reproduce:

1. Arial, zoom 0
2. Select some css property
3. Zoom in one step
4. Decorations are offset horizontally:

![image](https://cloud.githubusercontent.com/assets/9205389/22264446/d76299c6-e22c-11e6-8cfb-aeaa034ca8f1.png)

**Comment by chrmarti** [comment]
Also when zooming out. Here's the cursor movement when I repeatedly press arrow-right.
![cursormovement](https://cloud.githubusercontent.com/assets/9205389/22267848/23531a4c-e23a-11e6-948a-9a9b0d97bc2b.gif)

**Comment by chrmarti** [comment]
Marking as important for awareness.

**Comment by alexandrudima** [comment]
Yes, lines are not repainted when changing zoom level, which leads to their previous offset caches being used. Scrolling the line up and back down in the viewport is a possible workaround or typing, etc.
