### ISSUE TITLE
Changing branch for submodule does not work

### ISSUE THREAD

**Issue by Omcsesz** [microsoft/vscode#192795]
Type: <b>Bug</b>

Hello, Team!

When I try to change the current branch in Source Control view, I get an error (see attached gif). Can you please fix this?
[ChangeSubmoduleBranchFails](https://github.com/microsoft/vscode/assets/1839739/654a60b4-158d-4597-8624-502035e50d22)

VS Code version: Code - Insiders 1.83.0-insider (3c133b63c6e17e2fe33f37db93a6d43e78a262c5, 2023-09-11T05:33:26.767Z)
OS version: Windows_NT x64 10.0.22621
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.81GB (2.30GB free)|
|Process Argv|--crash-reporter-id 46a474c1-bb0b-418e-9983-038a8b8f2595|
|Screen Reader|no|
|VM|67%|
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythontb:30258533
vsc_aa:30263845
pythonptprofiler:30281269
vshan820:30294714
vscod805cf:30301675
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30404738
py29gd2263:30784851
vscaat:30438846
vsclangdf:30492506
c4g48928:30535728
dsvsc012:30540252
pynewext54:30618038
a9j8j154:30646983
showlangstatbar:30737417
7ij38806:30687742
pythonfmttext:30716741
fixshowwlkth:30771523
showindicator:30805243
pythongtdpath:30726887
i26e3531:30792625
welcomedialog:30812478
pythonnosmt12:30779711
pythonidxpt:30768918
pythonnoceb:30776497
copilotsettingt:30808721
dsvsc013:30777762
dsvsc014:30777825
diffeditorv2:30786206
pythonlinttypecf:30823782
pythonmpsinfo:30815194
dsvsc015:30821418
pythontestfixt:30826906
pythonfb280951:30830809

```

</details>

**Comment by lszomoru** [comment]
This does not seem to be specific to a submodule but to the fact that you are trying to checkout `origin/HEAD`.

**Comment by lszomoru** [comment]
Verification steps:
* Open a folder/workspace that contains a git repository
* Run the "Checkout to..." command from the command palette 
  * Confirm that the list does not contains `origin/HEAD`
* Run the "Checkout to (Detached)..." command from the command palette
  * Confirm that the list does contains `origin/HEAD` that can be checked out
