### ISSUE TITLE
Coming back to an incomplete extension walkthrough tab resets it to the Welcome screen.

### ISSUE THREAD

**Issue by darshanraju** [microsoft/vscode#192726]
Does this issue occur when all extensions are disabled?: No

- VS Code Version: 1.82.0
- OS Version: Windows 11

Steps to Reproduce
1. Open the VSCode Welcome screen.
2. From the welcome screen, navigate to a VSCode extension walkthrough.
3. Open a separate unrelated file in a new tab.
4. Navigate back to the editor tab that had the walkthrough open.

Expectation:
1. The walkthrough that was previously open, prior to opening the unrelated file should be open.

Reality:
1. The walkthrough tab now has reset back to the Welcome screen.

**Comment by bhavyaus** [comment]
This should be fixed in the latest insiders.
