### ISSUE TITLE
Debug Console not clearing

### ISSUE THREAD

**Issue by rohanjariwala03** [microsoft/vscode#192782]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: Version: 1.82.0 (Universal)
- OS Version: Apple M1 13.4.1

Steps to Reproduce:

1. Run any of the app in Debug mode
2. Press on `Clear Console` button.
3. Not clearing console.

https://github.com/microsoft/vscode/assets/34390549/edad17c8-c48e-4443-882c-4d6dc57caa09

**Comment by roblourens** [comment]
Could you check for errors in the developer tools when you do that? (Help > Toggle Developer Tools)

**Comment by rohanjariwala03** [comment]
**No Error in console**

**Additional points to the issue**

When your app is running and you press clear button then it will clear out. But the issue is after close the app it's not clearing.
For your context: I'm working with Flutter

**Comment by rohanjariwala03** [comment]
It's working perfectly with the Version: 1.82.2 (Universal).
Thanks for all the support and now I'm closing this issue.
