### ISSUE TITLE
DEBUG CONSOLE 

### ISSUE THREAD

**Issue by yinweixx** [microsoft/vscode#192737]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.82.0
- OS Version: mac os 13.5.2 

Steps to Reproduce:

When developing a Go language project, use the debug mode to start it for the first time. The debug console page will be displayed normally. Once restarted, the debug console will not be displayed normally. You need to constantly switch to other tabs and switch back to display the previous data. In addition, There is also an error message, Detaching and terminating target process
connection error: Error: read ECONNRESET, how to deal with this

**Comment by s-diaco** [comment]
Same problem developing a python project. If I restart debugging, no new output in "DEBUG CONSOLE" tab wil be shown unless I switch to another tab and switch back to "DEBUG CONSOLE" tab.

**Comment by dpoetzschke** [comment]
Same Problem on Windows 11. 
VSCode Version: 1.82.0

**Comment by Aatroy** [comment]
Same problem on Ubuntu 22.04  VSCode Version: 1.82.0

**Comment by rybalkoss** [comment]
same issue, but with the python interactive debugging

Version: 1.82.0-insider
Commit: 16e9205452dd417e32f164325b589b94892846b4
Date: 2023-09-06T08:16:41.476Z (5 days ago)
Electron: 25.8.0
ElectronBuildId: 23503258
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Darwin arm64 22.6.0

**Comment by DarioHett** [comment]
same issue as @rybalkoss 

Version: 1.82.0 (user setup)
Commit: 8b617bd08fd9e3fc94d14adb8d358b56e3f72314
Date: 2023-09-06T22:07:07.438Z
Electron: 25.8.0
ElectronBuildId: 23503258
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.19045

**Comment by roblourens** [comment]
https://github.com/microsoft/vscode/issues/192653 would appreciate if you check for errors in the developer tools (Help > Toggle Developer Tools)

**Comment by yinweixx** [comment]
ERR [Extension Host] (node:35226) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `Code Helper (Plugin) --trace-deprecation ...` to show where the warning was created)
workbench.desktop.main.js:sourcemap:132 [Extension Host] (node:35226) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `Code Helper (Plugin) --trace-deprecation ...` to show where the warning was created)
m @ workbench.desktop.main.js:sourcemap:132
workbench.desktop.main.js:sourcemap:132 [Extension Host] Server: {
  "Commands": [
    "gopls.add_dependency",
    "gopls.add_import",
    "gopls.apply_fix",
    "gopls.check_upgrades",
    "gopls.edit_go_directive",
    "gopls.fetch_vulncheck_result",
    "gopls.gc_details",
    "gopls.generate",
    "gopls.go_get_package",
    "gopls.list_imports",
    "gopls.list_known_packages",
    "gopls.mem_stats",
    "gopls.regenerate_cgo",
    "gopls.remove_dependency",
    "gopls.reset_go_mod_diagnostics",
    "gopls.run_go_work_command",
    "gopls.run_govulncheck",
    "gopls.run_tests",
    "gopls.start_debugging",
    "gopls.start_profile",
    "gopls.stop_profile",
    "gopls.test",
    "gopls.tidy",
    "gopls.toggle_gc_details",
    "gopls.update_go_sum",
    "gopls.upgrade_dependency",
    "gopls.vendor",
    "gopls.workspace_stats"
  ],
  "Name": "gopls",
  "Version": "v0.13.2",
  "GoVersion": "go1.21.0"
}
workbench.desktop.main.js:sourcemap:630   ERR semantictokens are disabled: Error: semantictokens are disabled
    at handleResponse (/Users/yw/.vscode/extensions/golang.go-0.39.1/dist/goMain.js:2126:40)
    at handleMessage (/Users/yw/.vscode/extensions/golang.go-0.39.1/dist/goMain.js:1936:11)
    at processMessageQueue (/Users/yw/.vscode/extensions/golang.go-0.39.1/dist/goMain.js:1951:13)
    at Immediate.<anonymous> (/Users/yw/.vscode/extensions/golang.go-0.39.1/dist/goMain.js:1927:11)
    at processImmediate (node:internal/timers:476:21)
workbench.desktop.main.js:sourcemap:132 [Extension Host] [vscode-cpptools-api] C/C++ extension is not installed
m @ workbench.desktop.main.js:sourcemap:132
default.exp-tas.com/vscode/ab:1     Failed to load resource: net::ERR_CONNECTION_CLOSED
workbench.desktop.main.js:sourcemap:630  INFO [perf] Render performance baseline is 23ms
workbench.desktop.main.js:sourcemap:630   ERR semantictokens are disabled: Error: semantictokens are disabled
    at handleResponse (/Users/yw/.vscode/extensions/golang.go-0.39.1/dist/goMain.js:2126:40)
    at handleMessage (/Users/yw/.vscode/extensions/golang.go-0.39.1/dist/goMain.js:1936:11)
    at processMessageQueue (/Users/yw/.vscode/extensions/golang.go-0.39.1/dist/goMain.js:1951:13)
    at Immediate.<anonymous> (/Users/yw/.vscode/extensions/golang.go-0.39.1/dist/goMain.js:1927:11)
    at processImmediate (node:internal/timers:476:21)
workbench.desktop.main.js:sourcemap:132 [Extension Host] error sending data:  Or: request to https://t.tooltitude.com/telemetry failed, reason: Client network socket disconnected before secure TLS connection was established
    at ClientRequest.<anonymous> (/Users/yw/.vscode/extensions/tooltitudeteam.tooltitude-0.34.3-darwin-arm64/out/extension.js:50:36112)
    at ClientRequest.emit (node:events:525:35)
    at TLSSocket.socketErrorListener (node:_http_client:502:9)
    at TLSSocket.emit (node:events:513:28)
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at processTicksAndRejections (node:internal/process/task_queues:82:21)
workbench.desktop.main.js:sourcemap:132 [Extension Host] [vscode-icons] v12.5.0 activated!
workbench.desktop.main.js:sourcemap:630   ERR semantictokens are disabled: Error: semantictokens are disabled
    at handleResponse (/Users/yw/.vscode/extensions/golang.go-0.39.1/dist/goMain.js:2126:40)
    at handleMessage (/Users/yw/.vscode/extensions/golang.go-0.39.1/dist/goMain.js:1936:11)
    at processMessageQueue (/Users/yw/.vscode/extensions/golang.go-0.39.1/dist/goMain.js:1951:13)
    at Immediate.<anonymous> (/Users/yw/.vscode/extensions/golang.go-0.39.1/dist/goMain.js:1927:11)
    at processImmediate (node:internal/timers:476:21)
workbench.desktop.main.js:sourcemap:630   ERR semantictokens are disabled: Error: semantictokens are disabled
    at handleResponse (/Users/yw/.vscode/extensions/golang.go-0.39.1/dist/goMain.js:2126:40)
    at handleMessage (/Users/yw/.vscode/extensions/golang.go-0.39.1/dist/goMain.js:1936:11)
    at processMessageQueue (/Users/yw/.vscode/extensions/golang.go-0.39.1/dist/goMain.js:1951:13)
    at Immediate.<anonymous> (/Users/yw/.vscode/extensions/golang.go-0.39.1/dist/goMain.js:1927:11)
    at processImmediate (node:internal/timers:476:21)
leojhonsong.gallerycdn.vsassets.io/extensions/leojhonsong/ccpp-extension-pack/2.1.0/1661929205147/Microsoft.VisualStudio.Services.Icons.Default:1     GET https://leojhonsong.gallerycdn.vsassets.io/extensions/leojhonsong/ccpp-extension-pack/2.1.0/1661929205147/Microsoft.VisualStudio.Services.Icons.Default net::ERR_CONNECTION_CLOSED
Image (async)
renderElement @ workbench.desktop.main.js:sourcemap:2575
renderElement @ workbench.desktop.main.js:sourcemap:210
renderElement @ workbench.desktop.main.js:sourcemap:210
X @ workbench.desktop.main.js:sourcemap:177
R @ workbench.desktop.main.js:sourcemap:177
splice @ workbench.desktop.main.js:sourcemap:177
(anonymous) @ workbench.desktop.main.js:sourcemap:4
splice @ workbench.desktop.main.js:sourcemap:4
(anonymous) @ workbench.desktop.main.js:sourcemap:210
bufferEvents @ workbench.desktop.main.js:sourcemap:70
splice @ workbench.desktop.main.js:sourcemap:210
set model @ workbench.desktop.main.js:sourcemap:210
Qc @ workbench.desktop.main.js:sourcemap:2575
(anonymous) @ workbench.desktop.main.js:sourcemap:2575
await in (anonymous) (async)
y @ workbench.desktop.main.js:sourcemap:132
show @ workbench.desktop.main.js:sourcemap:2575
show @ workbench.desktop.main.js:sourcemap:2575
(anonymous) @ workbench.desktop.main.js:sourcemap:2635
qb @ workbench.desktop.main.js:sourcemap:2635
(anonymous) @ workbench.desktop.main.js:sourcemap:2528
w @ workbench.desktop.main.js:sourcemap:70
x @ workbench.desktop.main.js:sourcemap:70
fire @ workbench.desktop.main.js:sourcemap:70
F @ workbench.desktop.main.js:sourcemap:2313
D @ workbench.desktop.main.js:sourcemap:2313
(anonymous) @ workbench.desktop.main.js:sourcemap:2313
w @ workbench.desktop.main.js:sourcemap:70
fire @ workbench.desktop.main.js:sourcemap:70
(anonymous) @ workbench.desktop.main.js:sourcemap:68
w @ workbench.desktop.main.js:sourcemap:70
x @ workbench.desktop.main.js:sourcemap:70
fire @ workbench.desktop.main.js:sourcemap:70
resume @ workbench.desktop.main.js:sourcemap:70
bufferChangeEvents @ workbench.desktop.main.js:sourcemap:623
dc @ workbench.desktop.main.js:sourcemap:2635
(anonymous) @ workbench.desktop.main.js:sourcemap:2635
(anonymous) @ workbench.desktop.main.js:sourcemap:132
Promise.then (async)
trigger @ workbench.desktop.main.js:sourcemap:132
ac @ workbench.desktop.main.js:sourcemap:2635
(anonymous) @ workbench.desktop.main.js:sourcemap:2635
w @ workbench.desktop.main.js:sourcemap:70
fire @ workbench.desktop.main.js:sourcemap:70
(anonymous) @ workbench.desktop.main.js:sourcemap:2029
(anonymous) @ workbench.desktop.main.js:sourcemap:712
w @ workbench.desktop.main.js:sourcemap:70
x @ workbench.desktop.main.js:sourcemap:70
fire @ workbench.desktop.main.js:sourcemap:70
endDeferredEmit @ workbench.desktop.main.js:sourcemap:721
pushEditOperations @ workbench.desktop.main.js:sourcemap:719
c @ workbench.desktop.main.js:sourcemap:646
executeCommands @ workbench.desktop.main.js:sourcemap:646
C @ workbench.desktop.main.js:sourcemap:645
(anonymous) @ workbench.desktop.main.js:sourcemap:646
H @ workbench.desktop.main.js:sourcemap:646
type @ workbench.desktop.main.js:sourcemap:646
(anonymous) @ workbench.desktop.main.js:sourcemap:727
O @ workbench.desktop.main.js:sourcemap:727
N @ workbench.desktop.main.js:sourcemap:727
type @ workbench.desktop.main.js:sourcemap:727
Lb @ workbench.desktop.main.js:sourcemap:729
type @ workbench.desktop.main.js:sourcemap:729
type @ workbench.desktop.main.js:sourcemap:666
(anonymous) @ workbench.desktop.main.js:sourcemap:705
w @ workbench.desktop.main.js:sourcemap:70
fire @ workbench.desktop.main.js:sourcemap:70
(anonymous) @ workbench.desktop.main.js:sourcemap:599
w @ workbench.desktop.main.js:sourcemap:70
x @ workbench.desktop.main.js:sourcemap:70
fire @ workbench.desktop.main.js:sourcemap:70
k @ workbench.desktop.main.js:sourcemap:70
jbenden.gallerycdn.vsassets.io/extensions/jbenden/c-cpp-flylint/1.13.1/1692238220742/Microsoft.VisualStudio.Services.Icons.Default:1     GET https://jbenden.gallerycdn.vsassets.io/extensions/jbenden/c-cpp-flylint/1.13.1/1692238220742/Microsoft.VisualStudio.Services.Icons.Default net::ERR_CONNECTION_CLOSED
Image (async)
renderElement @ workbench.desktop.main.js:sourcemap:2575
renderElement @ workbench.desktop.main.js:sourcemap:210
renderElement @ workbench.desktop.main.js:sourcemap:210
X @ workbench.desktop.main.js:sourcemap:177
R @ workbench.desktop.main.js:sourcemap:177
splice @ workbench.desktop.main.js:sourcemap:177
(anonymous) @ workbench.desktop.main.js:sourcemap:4
splice @ workbench.desktop.main.js:sourcemap:4
(anonymous) @ workbench.desktop.main.js:sourcemap:210
bufferEvents @ workbench.desktop.main.js:sourcemap:70
splice @ workbench.desktop.main.js:sourcemap:210
set model @ workbench.desktop.main.js:sourcemap:210
Qc @ workbench.desktop.main.js:sourcemap:2575
(anonymous) @ workbench.desktop.main.js:sourcemap:2575
await in (anonymous) (async)
y @ workbench.desktop.main.js:sourcemap:132
show @ workbench.desktop.main.js:sourcemap:2575
show @ workbench.desktop.main.js:sourcemap:2575
(anonymous) @ workbench.desktop.main.js:sourcemap:2635
qb @ workbench.desktop.main.js:sourcemap:2635
(anonymous) @ workbench.desktop.main.js:sourcemap:2528
w @ workbench.desktop.main.js:sourcemap:70
x @ workbench.desktop.main.js:sourcemap:70
fire @ workbench.desktop.main.js:sourcemap:70
F @ workbench.desktop.main.js:sourcemap:2313
D @ workbench.desktop.main.js:sourcemap:2313
(anonymous) @ workbench.desktop.main.js:sourcemap:2313
w @ workbench.desktop.main.js:sourcemap:70
fire @ workbench.desktop.main.js:sourcemap:70
(anonymous) @ workbench.desktop.main.js:sourcemap:68
w @ workbench.desktop.main.js:sourcemap:70
x @ workbench.desktop.main.js:sourcemap:70
fire @ workbench.desktop.main.js:sourcemap:70
resume @ workbench.desktop.main.js:sourcemap:70
bufferChangeEvents @ workbench.desktop.main.js:sourcemap:623
dc @ workbench.desktop.main.js:sourcemap:2635
(anonymous) @ workbench.desktop.main.js:sourcemap:2635
(anonymous) @ workbench.desktop.main.js:sourcemap:132
Promise.then (async)
trigger @ workbench.desktop.main.js:sourcemap:132
ac @ workbench.desktop.main.js:sourcemap:2635
(anonymous) @ workbench.desktop.main.js:sourcemap:2635
w @ workbench.desktop.main.js:sourcemap:70
fire @ workbench.desktop.main.js:sourcemap:70
(anonymous) @ workbench.desktop.main.js:sourcemap:2029
(anonymous) @ workbench.desktop.main.js:sourcemap:712
w @ workbench.desktop.main.js:sourcemap:70
x @ workbench.desktop.main.js:sourcemap:70
fire @ workbench.desktop.main.js:sourcemap:70
endDeferredEmit @ workbench.desktop.main.js:sourcemap:721
pushEditOperations @ workbench.desktop.main.js:sourcemap:719
c @ workbench.desktop.main.js:sourcemap:646
executeCommands @ workbench.desktop.main.js:sourcemap:646
C @ workbench.desktop.main.js:sourcemap:645
(anonymous) @ workbench.desktop.main.js:sourcemap:646
H @ workbench.desktop.main.js:sourcemap:646
type @ workbench.desktop.main.js:sourcemap:646
(anonymous) @ workbench.desktop.main.js:sourcemap:727
O @ workbench.desktop.main.js:sourcemap:727
N @ workbench.desktop.main.js:sourcemap:727
type @ workbench.desktop.main.js:sourcemap:727
Lb @ workbench.desktop.main.js:sourcemap:729
type @ workbench.desktop.main.js:sourcemap:729
type @ workbench.desktop.main.js:sourcemap:666
(anonymous) @ workbench.desktop.main.js:sourcemap:705
w @ workbench.desktop.main.js:sourcemap:70
fire @ workbench.desktop.main.js:sourcemap:70
(anonymous) @ workbench.desktop.main.js:sourcemap:599
w @ workbench.desktop.main.js:sourcemap:70
x @ workbench.desktop.main.js:sourcemap:70
fire @ workbench.desktop.main.js:sourcemap:70
k @ workbench.desktop.main.js:sourcemap:70
leojhonsong.gallery.vsassets.io/_apis/public/gallery/publisher/LeoJhonSong/extension/ccpp-extension-pack/2.1.0/assetbyname/Microsoft.VisualStudio.Services.Icons.Default:1     GET https://leojhonsong.gallery.vsassets.io/_apis/public/gallery/publisher/LeoJhonSong/extension/ccpp-extension-pack/2.1.0/assetbyname/Microsoft.VisualStudio.Services.Icons.Default net::ERR_TIMED_OUT
Image (async)
c.extensionDisposables.push.once @ workbench.desktop.main.js:sourcemap:2575
error (async)
o @ workbench.desktop.main.js:sourcemap:132
u @ workbench.desktop.main.js:sourcemap:132
renderElement @ workbench.desktop.main.js:sourcemap:2575
renderElement @ workbench.desktop.main.js:sourcemap:210
renderElement @ workbench.desktop.main.js:sourcemap:210
X @ workbench.desktop.main.js:sourcemap:177
R @ workbench.desktop.main.js:sourcemap:177
splice @ workbench.desktop.main.js:sourcemap:177
(anonymous) @ workbench.desktop.main.js:sourcemap:4
splice @ workbench.desktop.main.js:sourcemap:4
(anonymous) @ workbench.desktop.main.js:sourcemap:210
bufferEvents @ workbench.desktop.main.js:sourcemap:70
splice @ workbench.desktop.main.js:sourcemap:210
set model @ workbench.desktop.main.js:sourcemap:210
Qc @ workbench.desktop.main.js:sourcemap:2575
(anonymous) @ workbench.desktop.main.js:sourcemap:2575
await in (anonymous) (async)
y @ workbench.desktop.main.js:sourcemap:132
show @ workbench.desktop.main.js:sourcemap:2575
show @ workbench.desktop.main.js:sourcemap:2575
(anonymous) @ workbench.desktop.main.js:sourcemap:2635
qb @ workbench.desktop.main.js:sourcemap:2635
(anonymous) @ workbench.desktop.main.js:sourcemap:2528
w @ workbench.desktop.main.js:sourcemap:70
x @ workbench.desktop.main.js:sourcemap:70
fire @ workbench.desktop.main.js:sourcemap:70
F @ workbench.desktop.main.js:sourcemap:2313
D @ workbench.desktop.main.js:sourcemap:2313
(anonymous) @ workbench.desktop.main.js:sourcemap:2313
w @ workbench.desktop.main.js:sourcemap:70
fire @ workbench.desktop.main.js:sourcemap:70
(anonymous) @ workbench.desktop.main.js:sourcemap:68
w @ workbench.desktop.main.js:sourcemap:70
x @ workbench.desktop.main.js:sourcemap:70
fire @ workbench.desktop.main.js:sourcemap:70
resume @ workbench.desktop.main.js:sourcemap:70
bufferChangeEvents @ workbench.desktop.main.js:sourcemap:623
dc @ workbench.desktop.main.js:sourcemap:2635
(anonymous) @ workbench.desktop.main.js:sourcemap:2635
(anonymous) @ workbench.desktop.main.js:sourcemap:132
Promise.then (async)
trigger @ workbench.desktop.main.js:sourcemap:132
ac @ workbench.desktop.main.js:sourcemap:2635
(anonymous) @ workbench.desktop.main.js:sourcemap:2635
w @ workbench.desktop.main.js:sourcemap:70
fire @ workbench.desktop.main.js:sourcemap:70
(anonymous) @ workbench.desktop.main.js:sourcemap:2029
(anonymous) @ workbench.desktop.main.js:sourcemap:712
w @ workbench.desktop.main.js:sourcemap:70
x @ workbench.desktop.main.js:sourcemap:70
fire @ workbench.desktop.main.js:sourcemap:70
endDeferredEmit @ workbench.desktop.main.js:sourcemap:721
pushEditOperations @ workbench.desktop.main.js:sourcemap:719
c @ workbench.desktop.main.js:sourcemap:646
executeCommands @ workbench.desktop.main.js:sourcemap:646
C @ workbench.desktop.main.js:sourcemap:645
(anonymous) @ workbench.desktop.main.js:sourcemap:646
H @ workbench.desktop.main.js:sourcemap:646
type @ workbench.desktop.main.js:sourcemap:646
(anonymous) @ workbench.desktop.main.js:sourcemap:727
O @ workbench.desktop.main.js:sourcemap:727
N @ workbench.desktop.main.js:sourcemap:727
type @ workbench.desktop.main.js:sourcemap:727
Lb @ workbench.desktop.main.js:sourcemap:729
type @ workbench.desktop.main.js:sourcemap:729
type @ workbench.desktop.main.js:sourcemap:666
(anonymous) @ workbench.desktop.main.js:sourcemap:705
w @ workbench.desktop.main.js:sourcemap:70
fire @ workbench.desktop.main.js:sourcemap:70
(anonymous) @ workbench.desktop.main.js:sourcemap:599
w @ workbench.desktop.main.js:sourcemap:70
x @ workbench.desktop.main.js:sourcemap:70
fire @ workbench.desktop.main.js:sourcemap:70
k @ workbench.desktop.main.js:sourcemap:70

**Comment by yinweixx** [comment]
https://github.com/microsoft/vscode/assets/19992329/59456ad2-1f85-4a88-8180-ac41ccbed9de
