### ISSUE TITLE
Swedish characters are lost in Internal Console in C# (not debug)

### ISSUE THREAD

**Issue by karye** [microsoft/vscode#192767]
Steps to Reproduce:

1. Coding in C# with .net7

> dotnet --info         
> .NET SDK:
>  Version:   7.0.400
>  Commit:    73bf45718d
> 
> Runtime Environment:
>  OS Name:     Windows
>  OS Version:  10.0.22621
>  OS Platform: Windows
>  RID:         win10-x64
>  Base Path:   C:\Program Files\dotnet\sdk\7.0.400\
> 
> Host:
>   Version:      7.0.10
>   Architecture: x64
>   Commit:       a6dbb800a4
> 
> .NET SDKs installed:
>   3.1.426 [C:\Program Files\dotnet\sdk]
>   5.0.214 [C:\Program Files\dotnet\sdk]
>   5.0.408 [C:\Program Files\dotnet\sdk]
>   6.0.406 [C:\Program Files\dotnet\sdk]
>   6.0.413 [C:\Program Files\dotnet\sdk]
>   7.0.400 [C:\Program Files\dotnet\sdk]
> 
> .NET runtimes installed:
>   Microsoft.AspNetCore.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
>   Microsoft.AspNetCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
>   Microsoft.AspNetCore.App 6.0.14 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
>   Microsoft.AspNetCore.App 6.0.21 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
>   Microsoft.AspNetCore.App 7.0.10 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
>   Microsoft.NETCore.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 6.0.21 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 7.0.10 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.WindowsDesktop.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
>   Microsoft.WindowsDesktop.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
>   Microsoft.WindowsDesktop.App 6.0.14 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
>   Microsoft.WindowsDesktop.App 6.0.21 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
>   Microsoft.WindowsDesktop.App 7.0.10 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
> 
> Other architectures found:
>   x86   [C:\Program Files (x86)\dotnet]
>     registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]
> 
> Environment variables:
>   Not set

3. Reading input with Console.ReadLine()

> Console.Write("Ange en färg (röd, grön , blå): ");
> string färg = Console.ReadLine();
> 
> if (färg == "röd")
> {
>     Console.WriteLine("Du valde färgen röd");
> }
> else
> {
>     Console.WriteLine($"Färgen är _{färg}_");
> }

4. Typing **swedish characters** in internal console, these characters are "lost":

> Ange en färg (röd, grön , blå): röd
> Färgen är _rd_

6. But when debugging is on all works ok.

Version: 1.82.0 (user setup)
Commit: 8b617bd08fd9e3fc94d14adb8d358b56e3f72314
Date: 2023-09-06T22:07:07.438Z
Electron: 25.8.0
ElectronBuildId: 23503258
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.22621

**Comment by roblourens** [comment]
What do you mean by "Internal Console", is this the "Integrated Terminal"? Maybe translated differently?

Do you still see this in the latest version?

**Comment by karye** [comment]
Yes, I meant "Integrated Terminal".

Adding these lines to make it work:
Console.OutputEncoding = System.Text.Encoding.Unicode;
Console.InputEncoding = System.Text.Encoding.Unicode;

Using:
Version: 1.85.1 (user setup)
Commit: 0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2
Date: 2023-12-13T09:49:37.021Z
Electron: 25.9.7
ElectronBuildId: 25551756
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.22000

**Comment by karye** [comment]
I meant in "Integrated Terminal".

Adding these lines to make it work:
Console.OutputEncoding = System.Text.Encoding.Unicode;
Console.InputEncoding = System.Text.Encoding.Unicode;
