### ISSUE TITLE
Command navigation stops working when terminal history is restored 

### ISSUE THREAD

**Issue by levotiger** [microsoft/vscode#192710]
Type: <b>Bug</b>

Steps to reproduce:
1. Enable Persistent Sessions in terminal settings.
2. Type some commands via integrated terminal.
3. Close and reopen Visual Studio Code; history from previous terminal session must be restored.
4. `Ctrl+Up`, `Ctrl+Down` aren't working now.

Expected result: command navigation should jump between commands.

VS Code version: Code 1.82.0 (8b617bd08fd9e3fc94d14adb8d358b56e3f72314, 2023-09-06T22:07:07.438Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 5600U with Radeon Graphics          (12 x 2296)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|13.86GB (6.85GB free)|
|Process Argv|--crash-reporter-id 72997f5d-29ed-4ce3-a244-768c8e441e95|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (20)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|3.0.2
vscode-markdownlint|Dav|0.51.0
gitlens|eam|14.3.0
prettier-vscode|esb|10.1.0
figma-vscode-extension|fig|0.2.7
auto-close-tag|for|0.5.14
auto-rename-tag|for|0.1.10
vscode-pull-request-github|Git|0.72.0
vscode-gutter-preview|kis|0.30.0
git-graph|mhu|1.30.0
vscode-edge-devtools|ms-|2.1.3
brackets-pack|ms-|0.1.1
live-server|ms-|0.4.9
live-server-preview|neg|0.1.4
material-icon-theme|PKi|4.30.1
polacode|pnp|0.3.4
LiveServer|rit|5.7.9
trailing-spaces|sha|0.4.1
code-spell-checker|str|3.0.0
html-css-class-completion|Zig|1.20.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
py29gd2263cf:30792227
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
vscccc:30803845
2e4cg342:30602488
89544117:30613380
a9j8j154:30646983
showlangstatbar:30737416
0bi6i642:30831757
a2ce3375:30757347
pythonfmttext:30731395
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
pythonnosmt12:30797651
pythonidxptcf:30805731
pythonnoceb:30805159
dsvsc013:30795093
dsvsc014:30804076
diffeditorv2:30821572
dsvsc015cf:30829746

```

</details>

**Comment by Tyriar** [comment]
No plans any time soon to restore command history after we revive a process so closing out of scope.
