### ISSUE TITLE
Update to 1.82.0, VSCode takes more time to kill processes after quit

### ISSUE THREAD

**Issue by hua03** [microsoft/vscode#192742]
Type: <b>Bug</b>

In this video, I quit VSCode at 7 seconds, but it (Dock Icon) was killed at 12 seconds.

https://github.com/microsoft/vscode/assets/19561959/8c970026-b060-4062-83af-f61e0219cfc4

VS Code version: Code 1.82.0 (8b617bd08fd9e3fc94d14adb8d358b56e3f72314, 2023-09-06T22:09:41.364Z)
OS version: Darwin x64 22.5.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-1038NG7 CPU @ 2.00GHz (8 x 2000)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|32.00GB (13.43GB free)|
|Process Argv|--crash-reporter-id 25337f27-0fd6-4ad2-a343-d23e45e01d53|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
astro-vscode|ast|2.3.3
vscode-language-pack-zh-hans|MS-|1.82.2023090609

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
vsccc:30803844
2e4cg342:30602488
f6dab269:30613381
2i9eh265:30646982
showlangstatbar:30737416
0bi6i642:30831757
pythonfmttext:30731395
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
pythonnosmt12:30797651
pythonidxptcf:30805731
pythonnoceb:30805159
dsvsc013:30795093
dsvsc014:30804076
diffeditorv1:30821571
dsvsc015:30829745

```

</details>

**Comment by jungaretti** [comment]
#192753 and #172967 include lots of information about this bug

**Comment by deepak1556** [comment]
Initial findings:

* Main process is delayed waiting on the [shutdownPromise](https://github.com/microsoft/vscode/blob/f766dc2c35cbdfd3a846a72a5a3ebe07d35c0b59/src/vs/platform/lifecycle/electron-main/lifecycleMainService.ts#L319) to resolve.
* Delay comes from exiting long running extension host in [waitForExit](https://github.com/microsoft/vscode/blob/f766dc2c35cbdfd3a846a72a5a3ebe07d35c0b59/src/vs/platform/utilityProcess/electron-main/utilityProcess.ts#L429)
* Profiling the extension host shows that the Node.js is delayed in its cleanup of exit callbacks at https://github.com/nodejs/node/blob/b45e196bec407c9db30ffe5490bb86be692a1579/src/env.cc#L1180-L1186
* ⚠️ Disabling telemetry resolves the slow shutdown of the extension host `"telemetry.telemetryLevel": "off"`

@bpasero @lramos15 this is a return of https://github.com/microsoft/vscode/issues/172967 but we have reliable repro this time. @lramos15 do we run any telemetry network requests from inside the extension host, if so can you point me to the code.

<img width="1436" alt="Screenshot 2023-09-13 at 2 11 43" src="https://github.com/microsoft/vscode/assets/964386/f6e082c7-6370-49c7-b7d7-43f03e8d279e">

**Comment by bpasero** [comment]
Great findings 👏 , I am not sure if this is relevant here, but I do have noticed for quite some time now that quitting "Code OSS" (i.e. when I run out of sources and develop) takes a lot longer now to return back to the terminal. I was almost about to file an issue but maybe its the same? Would this repro even out of sources?

**Comment by deepak1556** [comment]
Yup it repos in out of sources as well as the product builds

**Comment by lramos15** [comment]
> @lramos15 this is a return of #172967 but we have reliable repro this time. @lramos15 do we run any telemetry network requests from inside the extension host, if so can you point me to the code.

Extensions can run telemetry from within the ext host (including built-in ones), but our core telemetry is all proxied over IPC
https://github.com/microsoft/vscode/blob/f766dc2c35cbdfd3a846a72a5a3ebe07d35c0b59/src/vs/workbench/api/browser/mainThreadTelemetry.ts#L16-L17

**Comment by deepak1556** [comment]
> Extensions can run telemetry from within the ext host (including built-in ones)

Where do the network requests for these originate from, do they still get issued from the shared process ? Can you point to this code path as well.

**Comment by lramos15** [comment]
> Where do the network requests for these originate from, do they still get issued from the shared process ? Can you point to this code path as well.

I'm just talking about how each extension can send telemetry by instantiating its own reporter which uses the built-in http node module.

**Comment by justschen** [comment]
on m2 pro - speed for the close out is somewhat variable (not sure if this is an issue, it's still faster, but anywhere from 3-4 seconds).

**Comment by lramos15** [comment]
> on m2 pro - speed for close out in the dock is somewhat variable (not sure if this is an issue, it's still faster, but anywhere from 3-4 seconds).

Did you disable all extensions?

**Comment by justschen** [comment]
correction: works fine in insiders, very quick within 2 seconds of quitting.
