### ISSUE TITLE
Windows is ignore terminal titles unless they look like paths

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#192771]
From @NoelAbrahams in https://github.com/microsoft/vscode/issues/172821#issuecomment-1712935578

> I've been trying to programmatically set the title of a bash terminal without success, and glad that I chanced upon this issue.
> 
> Here is the repro:
> 
> System: Windows 11.
> Git Bash installed.
> VSCode version:  1.82.0
> 
> VSCode Workspace Settings:
> 
> ![image](https://github.com/microsoft/vscode/assets/1106823/597a9727-bbac-41bc-81cd-0a73a723787f)
> 
> 
> **.bashrc**
> ```shell
> echo -en "\033]0;New terminal title\a"
> ```
> 
> The title of the bash terminal window remains stubbornly unchanged as `bash myworkspacefolder`.
> 
> I'm assuming this issue will fix my use case.
> 
> Thanks

---

This section is setting it to undefined:

https://github.com/microsoft/vscode/blob/41e940f76f5deda197bc5930b044c55607ba1cbc/src/vs/workbench/contrib/terminal/browser/terminalInstance.ts#L1933-L1946

We want to keep the path trimming behavior above, but only when it looks like a path.

**Comment by NikoRaisanen** [comment]
Hey Tyriar! Do you mind if I tackle this one?

**Comment by Tyriar** [comment]
@NikoRaisanen sure 👍

**Comment by NoelAbrahams** [comment]
@NikoRaisanen in your WIP PR I see some code like this: 

`title.match(/^MINGW(32|64):.*/)`

I'm sure I'm wrong (I haven't looked into the code at all) but I hope this does not depend on there being 'MINGW64' in the title because that is customisable via `.bashrc`.

eg

```shell
	PS1="$PS1"'\n'                 # new line
	PS1="$PS1"'\[\033[32m\]'       # change to green
	PS1="$PS1"'\u@\h '             # user@host<space>
	PS1="$PS1"'\[\033[35m\]'       # change to purple
 #	PS1="$PS1"'$MSYSTEM '          # show MSYSTEM  # Do not show MINGW64
	PS1="$PS1"'\[\033[33m\]'       # change to brownish yellow
	PS1="$PS1"'\w'                 # current working directory
```

**Comment by Tyriar** [comment]
@NoelAbrahams I was thinking something more along the lines of:

``
if windows
  if looksLikePath(title)
    // current behavior
  else
    // don't change title at all
```

**Comment by NikoRaisanen** [comment]
Thanks for bringing up that example @NoelAbrahams 

About that thought @Tyriar, starting a WSL or GitBash terminal fires 2 events on Windows that hit that TitleEventSource.Sequence case.

The first event is an absolute Windows path to the terminal
The second event is `username@hostname: <PATH>` for WSL terminals, and `MINGW<32|64>:<PATH>` for GitBash

I tried your recommendation Tyriar, and I attached a screenshot of the result. In the screenshot I just opened a wsl terminal and a gitbash terminal, you can see that this second event overwrites the title
![issueAfterBug](https://github.com/microsoft/vscode/assets/57982138/a8f4e086-64a6-4657-860e-dccd549e696e)

After seeing what Noel brought up, my current train of thought with having a regex to capture those second events isn't a valid solution.

Let me know if you have ideas on how to handle this or if anybody else wants to take a crack at this problem!

**Comment by NoelAbrahams** [comment]
So, the second event is overwriting the title. But I sort of agree with @Tyriar: Why not just let Git Bash or WSL apply the title they want? I feel the only problem that this section of code is concerned with is to parse out the file name if there is a full path.

So something like:

```ts

this._sequence = title;
if (this._processManager.os === OperatingSystem.Windows &&
        title.match(/^[a-zA-Z]:\\.+\.[a-zA-Z]{1,3}/)) {
	this._sequence = path.win32.parse(title).name;
} 
// Leave title alone. 
break;
```
The bug is that the current code is setting it to `undefined`.

![image](https://github.com/microsoft/vscode/assets/1106823/e2aeb181-af74-4b0a-a18c-96136c2eaad0)

**Comment by Tyriar** [comment]
@NoelAbrahams yep you're right, that sounds good to me 👍 The main thing is we need to cover the case where pwsh's full (sometimes very lengthy) path is truncated.

**Comment by NikoRaisanen** [comment]
Thanks again for the input, added @NoelAbrahams as co-author because you hand-held me through it 😄 
@Tyriar The PR is up, let me know if you think this should have an associated test

**Comment by Tyriar** [comment]
Marking as feature as I'll probably mention this on the release notes

**Comment by rzhao271** [comment]
I tried the steps in the original comment and get New Terminal Title for a second, but the title of the terminal changes back to "MINGW64:/c/Users/raymondzhao/work/vscode" after.

**Comment by Tyriar** [comment]
@rzhao271 that's working as designed since the shell tells us to do it. The fact that you see a title that is not in the form `C:\...` verifies the issue
