### ISSUE TITLE
Add restart buttons and different outputs navigation (similar to the terminal) in the debug console

### ISSUE THREAD

**Issue by delphinemlcarlson** [microsoft/vscode#192791]
If you launch something without the debugger, e.g. a test, it runs in the "Terminal" panel which already has a rerun button:
![AmSYoLvmrHMqSSi](https://github.com/microsoft/vscode/assets/118260292/60bbf729-61dd-4f4d-91c2-38d872752f90)

But the  "Debug Console" panel does not have this button: 
![6nfpFkdphqFAt3x (1)](https://github.com/microsoft/vscode/assets/118260292/0dd20a79-7693-4bd8-bfcf-09605a99f1ae)

What is the rationale for splitting the Debug Console from the Terminal? What are VS Code's plan with the debug console in the future?

What about adding the restart button also to the Debug Console? And also add to the the panel on the right side the possibility to navigate between different debug console outputs (as done for the terminal)?  
![ryVQFV9DbvKFhaC](https://github.com/microsoft/vscode/assets/118260292/28646252-3b40-46d9-a4b5-377a27694b18)

```[tasklist]
### Tasks
```

**Comment by roblourens** [comment]
The debug console has a dropdown where you will see outputs from different debug sessions.

The restart button is in the debug toolbar with the rest of the debug commands
