### ISSUE TITLE
Remote SSH unresponsive when saving notebook with large images

### ISSUE THREAD

**Issue by TimKuipersRobinRadar** [microsoft/vscode#192746]
Type: <b>Bug</b>

I am running some diffusion NNs remotely and want to visualize the steps in between. The output is being shown quite well, but then I am unable to rerun the cells, it keeps hanging on the very first line to execute. I am not able to save the file: it is hanging.

VScode is responsive and I can edit files and use all menus and everything. It's just that execution never starts and I am unable to save the file.

The only current workaround is to copy paste all cells into another text editor, quite vscode without saving, restart, copy paste edits into the file again.

Also: When restarting vscode starting up takes forever.

In it's current change I am unable to use vscode to work on diffusers at all. Only my remote workstation has enough GPU power, but this bug makes it impossible to actually see the output of what Im with the diffusers.

Steps:
Execute this cell:
```
import torch
from PIL import Image
from IPython.display import display, Image as IPImage
import numpy as np
import io

batch = torch.randint(0, 256, (10, 1024, 1024, 3), dtype=torch.uint8)
frames = [Image.fromarray(img.numpy(), 'RGB') for img in batch]
buffer = io.BytesIO()
frames[0].save(buffer, format='GIF', save_all=True, append_images=frames[1:], loop=0, duration=100)
buffer.seek(0)
display(IPImage(data=buffer.read(), format='png'))
buffer.close()
```
- Try to save.
- Try [Clear Cell Outputs]
- Try to save the file again
- Try to run the cell again

Results:
Never actually saves, execution never starts

Expected:
Save succeeds, cell is executed again.

Related:
https://github.com/microsoft/vscode/issues/140116 marked as fixed, but problem still occurs
https://github.com/microsoft/vscode/issues/138784 was a catch-all issue, but didn't catch this issue
https://github.com/nmamlm/Nay-Myo-Aung/issues/1 might be about this issue. (Not sure what this fork is.)

VS Code version: Code 1.82.0 (8b617bd08fd9e3fc94d14adb8d358b56e3f72314, 2023-09-06T22:07:18.759Z)
OS version: Linux x64 5.15.0-82-generic
Modes:
Remote OS version: Linux x64 5.15.0-83-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz (16 x 2500)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|1, 1, 1|
|Memory (System)|62.01GB (47.74GB free)|
|Process Argv|--unity-launch --crash-reporter-id 18920a42-ff0f-4b00-977c-cfc22a6b2b39|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|

|Item|Value|
|---|---|
|Remote|SSH: 10.200.100.65|
|OS|Linux x64 5.15.0-83-generic|
|CPUs|13th Gen Intel(R) Core(TM) i9-13900K (32 x 3000)|
|Memory (System)|62.57GB (52.44GB free)|
|VM|0%|
</details><details><summary>Extensions (20)</summary>

Extension|Author (truncated)|Version
---|---|---
jupyter-keymap|ms-|1.1.2
remote-containers|ms-|0.309.0
remote-ssh|ms-|0.107.2023090815
remote-ssh-edit|ms-|0.86.0
remote-wsl|ms-|0.81.2
vscode-remote-extensionpack|ms-|0.24.0
remote-explorer|ms-|0.4.1
remote-server|ms-|1.4.3
copilot|Git|1.110.389
copilot-chat|Git|0.7.0
copilot-labs|Git|0.15.1019
isort|ms-|2023.10.1
python|ms-|2023.16.0
vscode-pylance|ms-|2023.9.10
jupyter|ms-|2023.8.1002501831
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.17
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-slideshow|ms-|0.1.5
makefile-tools|ms-|0.7.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
py29gd2263cf:30792227
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
vsccc:30803844
282f8724:30602487
89544117:30613380
a9j8j154:30646983
showlangstatbar:30737416
a2ce3375:30757347
pythonfmttext:30731395
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
pythonnosmt12:30797651
pythonidxpt:30805730
pythonnoceb:30805159
dsvsc013:30795093
dsvsc014:30804076
diffeditorv2:30821572
dsvsc015:30829745

```

</details>

**Comment by roblourens** [comment]
https://github.com/microsoft/vscode/issues/172345
