### ISSUE TITLE
No debugging without launch.json file when using debugger from extension

### ISSUE THREAD

**Issue by ramya-rao-a** [Microsoft/vscode#19284]
Testing #18397 on Windows

- I have the Go extension installed and Go workspace opened with no launch.json file.
- There is a Go file opened in the active editor.
- I have added a breakpoint
- I click on the gear button in the debug side pane to create the launch.json file and there is a pop up asking me to choose the environment.
- I chose Go

Nothing happens. Debugger is not started.

In case you don't have Go and the Go extension installed, follow the below steps:
1. Install [Go](https://golang.org/doc/install#install)
2. Setup GOPATH
       1. Choose a folder where you will be having the Go projects
       2. Add env variable GOPATH with value as the above folder path
       3. Create 3 folders "src", "bin" and "pkg"
3. Run `go get github.com/golang/example/hello`
4. Install the Go extension by lukehoban and open the folder $GOPATH/src/GitHub.com/golang/example/hello in VS Code
5. Open the `hello.go` file. You will see "Analysis Tools Missing" in the status bar. Click on it to install the Go tools that the extension needs.

**Comment by isidorn** [comment]
dup of https://github.com/Microsoft/vscode-go/issues/745
