### ISSUE TITLE
Menu: `getOpenRecentActions` called very often

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#192840]
Steps to Reproduce: just open and close the same file over and over. Notice a call to:

https://github.com/microsoft/vscode/blob/35425d369ada2ba625304f9adb626332f13d1753/src/vs/workbench/browser/parts/titlebar/menubarControl.ts#L243

Each time because the menu is updated (even though these actions are not even visible?).

The `Action` is actually created here:

https://github.com/microsoft/vscode/blob/35425d369ada2ba625304f9adb626332f13d1753/src/vs/workbench/browser/parts/titlebar/menubarControl.ts#L334-L342

But I think is never disposed when `getOpenRecentActions` is called again.

Logging what kind of actions get created just by switching between 2 editors:

![Image](https://github.com/microsoft/vscode/assets/900690/02958056-9ba1-48a0-96a6-46f51c76525e)

I think it would be best if we could simply avoid this call and defer it to when the menu opens?

**Comment by sbatten** [comment]
> I think it would be best if we could simply avoid this call and defer it to when the menu opens?

We have to pro-actively update menus on the native titlebar so i don't think this is possible?

**Comment by bpasero** [comment]
Fyi I was able to resolve the leak by switching to `toAction` and using `IAction` instead of `Action`. But left this issue open to understand why we need to call this method so often, esp. since the "Open Recent" menu is hidden under the "File" menu.

**Comment by sbatten** [comment]
okay, the reason we call it is because native menus need to be updated proactively. we could at least buffer the call perhaps?

**Comment by bpasero** [comment]
^
