### ISSUE TITLE
Documentation issue: Source map authentication

### ISSUE THREAD

**Issue by johncrim** [microsoft/vscode#192895]
This issue is to obtain sufficient documentation for a claimed new feature to be used.

The [release notes from the newest (Aug 2023) VS Code release](https://code.visualstudio.com/updates/v1_82) says:

> Source maps can now be automatically loaded from authenticated endpoints

That's great! But to use this, we need some more info:

 * What types of authentication are supported? Basic Authentication, Digest Authentication, Client certs, OAuth/OpenID? Does it just figure it out really (if so I'm impressed!)? Is there a way to provide redirects eg for OpenID Connect?
 * Does this work for multiple browser extensions? Eg can I use both the Chrome and MSEdge extensions to debug apps, while loading sourcemaps from authenticated endpoints?

I haven't been able to find any info on this in the release notes or VS Code docs. I would expect more info [on the browser debugging page](https://code.visualstudio.com/docs/nodejs/browser-debugging) or [the Node debugging page](https://code.visualstudio.com/docs/nodejs/nodejs-debugging#_source-maps). This seems like a browser debugging feature, b/c securing source maps seems more critical for front-end code than back-end code.

**Comment by connor4312** [comment]
I'm not sure what it'd be useful to say in the docs about it -- there's no configuration available for this behavior, it 'just happens'. What information about it do you think would be relevant for users?

**Comment by johncrim** [comment]
I was thinking something along the lines of:

> ### Source Map Request Authentication
> 
> The VS Code JavaScript debugger uses the Chromium (Chrome or Edge) browser's network stack to make requests for source map files as of v1.82. This enables forms of authentication that are supported by the browser to be used for source map requests - for example cookie authentication using cookies that were previously set, or client certificates. In other words, if the source map request is authenticated when requested from browser dev tools, the same authentication should be used when VS Code requests the file.

I think this should go on the [browser debugging page](https://code.visualstudio.com/docs/nodejs/browser-debugging). I searched and searched for any info on what sourcemap authentication is supported by User Agents and couldn't find anything useful.
