### ISSUE TITLE
Warning: `webviewElement.ts:512 An iframe which has both allow-scripts and allow-same-origin for its sandbox attribute can escape its sandboxing. mountTo @ webviewElement.ts:512`

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#192853]
I am seeing this warning printed also in integration tests for notebooks and webviews:

```
webviewElement.ts:512 An iframe which has both allow-scripts and allow-same-origin for its sandbox attribute can escape its sandboxing.
mountTo @ webviewElement.ts:512
```

![image](https://github.com/microsoft/vscode/assets/900690/8a480f57-7b26-4d70-8c35-fd9b1fc84037)

**Comment by mjbvz** [comment]
We need both of these attributes for our webviews to function. It does not appear to be a real security issue with how our webviews work
