### ISSUE TITLE
Add right padding to tabs when tabs wrap to prevent hectic updates

### ISSUE THREAD

**Issue by hanieljazzar** [microsoft/vscode#192859]
Type: <b>Feature Request</b>

Hello, please can you add some right padding to tab names so that when there's an error and the number of errors shows at the end of the tab name, it doesn't overflow the tab menu and cause the tabs to move and flick. it's really annoying. showing number of errors next to tab name should NOT increase the length of the tab. Thanks!

VS Code version: Code 1.82.0 (8b617bd08fd9e3fc94d14adb8d358b56e3f72314, 2023-09-06T22:07:07.438Z)
OS version: Windows_NT x64 10.0.22621
Modes:

**Comment by hanieljazzar** [comment]
![image](https://github.com/microsoft/vscode/assets/109519090/dd68df1d-9e8c-408e-a511-0d5a87890578)
this small number causes tabs to move up and down when multiple tab lines is enabled

**Comment by bpasero** [comment]
Just to clarify: is this when you have tabs configured to wrap and being annoyed by tabs moving to the next line or even without tabs wrapping?

**Comment by MrAndersen1** [comment]
Just adding a gif for the case when it aligns with creating a new line of tabs.
The place you're writing at moves up and down to adjust.
![Recording 2023-09-12 at 15 38 38](https://github.com/microsoft/vscode/assets/4050133/f3fcf367-9286-466e-b58e-62aa0a2a9781)
But the case when it's moving to and from an existing line is also very distracting as all the following tabs also move around.

**Comment by hanieljazzar** [comment]
Exactly great example thanks for sharing it @MrAndersen1

**Comment by bpasero** [comment]
Btw I believe a workaround is to configure `workbench.editor.tabSizing: fixed` (which is a relatively new setting) and maybe bump up the `workbench.editor.tabSizingFixedMinWidth` to a higher value. This will make all tabs have the same size and never grow, even when the label gets larger.

![image](https://github.com/microsoft/vscode/assets/900690/d2bd6e37-31ec-44f7-b1df-19015868217a)

**Comment by hanieljazzar** [comment]
Ah nice workaround, i didn't really know this exists. Though some spacing is wasted for short files such as .env but seems fine, thanks for sharing!

**Comment by benibenj** [comment]
No further plans here

**Comment by MrAndersen1** [comment]
That's unfortunate as it is an annoying issue.
