### ISSUE TITLE
Linux: "Open with Code" doesn't work when a Code window is already open

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#19285]
Testing https://github.com/Microsoft/vscode/issues/18609

- On Ubuntu 14.04
- Open a Code window
- Open whatever you call the file explorer in Ubuntu
- Right click some file > Open With > Code Insiders
- A new Code window opens, but it has an untitled file, not the selected one

If I set `"window.openFilesInNewWindow": "off"`, it opens the actual file in the open Code window correctly.

**Comment by roblourens** [comment]
Works from the command line, but not from the file explorer.

**Comment by Tyriar** [comment]
This is a regression from 1.8.1, probably related to .desktop changes. Will look at it for Jan if there's time.

**Comment by Tyriar** [comment]
Yes this is due to the `--new-window-if-not-first` arg and only happens on the second+ window.
