### ISSUE TITLE
Support menu bar mnemonics with an overlay while alt is held

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#192878]
Currently the menu bar is super ugly in some display languages:

![Image](https://github.com/microsoft/vscode/assets/2193314/fc0b384f-9fff-47aa-b7ab-4b6d5fb48601)

I can turn it off with `window.enableMenuBarMnemonics`, but then I lose the ability to access them with alt all together:

![Image](https://github.com/microsoft/vscode/assets/2193314/3f465c32-e03e-4075-a330-0d6dfa248949)

I proposed we move to something like Notepad where you press alt and get an overlay like this when the menu bar is focused:

![Image](https://github.com/microsoft/vscode/assets/2193314/2e7d2272-8b94-4121-8fe9-7d6953d5cabc)

We could do exactly this, where the overlay shows when in this state:

![Image](https://github.com/microsoft/vscode/assets/2193314/2c632053-ba13-469b-a020-1f78a46c79cc)

We could also show it when holding alt but it would probably be too noisy.

**Comment by bpasero** [comment]
I feel this is not going to happen anytime soon, sorry.
