### ISSUE TITLE
SCSS differences in coloring

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#19289]
Test item #18318

- VSCode Version: Code - Insiders 1.9.0-insider (4265f5e35cb3ea8ba7e0cf6b14ec606b6f8647ea, 2017-01-24T10:29:13.076Z)
- OS Version: Darwin x64 15.6.0
- Extensions: None

Dark+, source:
```
$font-family:      Helvetica Neue, Arial, Helvetica, sans-serif;
$fixed-font-family:'andale mono', 'lucida console', monospace;
$thick-border:               8px solid black;
$dotted-border:              1px dotted #999999;
$paging-background-color:    black;
```

1.8:
![screen shot 2017-01-24 at 2 15 15 pm](https://cloud.githubusercontent.com/assets/9205389/22269265/952793be-e23f-11e6-82fb-c6df8c8fa6e4.png)

1.9:
![screen shot 2017-01-24 at 2 16 20 pm](https://cloud.githubusercontent.com/assets/9205389/22269314/b9806d3a-e23f-11e6-9351-727a82a4cdfe.png)

**Comment by chrmarti** [comment]
Reloading 1.9 produced the same result.

**Comment by alexandrudima** [comment]
I've confirmed that the dark+ theme contains no selectors targeting these scopes (i.e. theme matching appears to function OK).

@aeschli I leave it up to you to decide if this was a case of CSS bad matching (i.e. text was getting blue due to the variable declaration) or if we should change the themes.

**Comment by ramya-rao-a** [comment]
Well, now we have this:

![image](https://cloud.githubusercontent.com/assets/16890566/22346398/c8529b7e-e3b8-11e6-83bf-7012baefbf56.png)

Why is "Neue" in a different color?

**Comment by aeschli** [comment]
The grammar has a list of known property values. These are shown in red. All others in white.
The idea is to help with invalid or misspelled values. 
Obviously it doesn't know all fonts...
Previously this didn't work as designed by the grammar, now it does.
