### ISSUE TITLE
Failed to parse remote port from server output

### ISSUE THREAD

**Issue by samuelbaizg** [microsoft/vscode#192869]
The same problem with below issue.  the issue occurs in vscode 1.82.0 and remote ssh 0.106 and 0.107. when rolling back to 0.105 the issue is fixed.  but this issue should be fixed in the latest version. thanks. 

_Originally posted by @hmica in https://github.com/microsoft/vscode/issues/192834#issuecomment-1715169598_

**Comment by saeidamiri1** [comment]
I have the same issue after upgrading to 1.82.0 (I am using mac-intel)

**Comment by roblourens** [comment]
This should be fixed with the latest version of the Remote-SSH extension
