### ISSUE TITLE
Copy and pasting issues

### ISSUE THREAD

**Issue by StefanMoore** [microsoft/vscode#192867]
Type: <b>Bug</b>

When I'm copying and pasting text from Onenote into VS Code editor it comes up like this `![Alt text](image.png)`.  How do I correct this

VS Code version: Code 1.82.0 (8b617bd08fd9e3fc94d14adb8d358b56e3f72314, 2023-09-06T22:07:07.438Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details><summary>Extensions (59)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|3.0.2
aws-toolkit-vscode|ama|1.89.0
LinkCheckMD|bla|0.3.1
excel-to-markdown-table|csh|1.3.0
vscode-markdownlint|Dav|0.51.0
docs-article-templates|doc|1.0.3
docs-authoring-pack|doc|1.0.0
docs-build|doc|0.4.1
docs-images|doc|1.0.1
docs-linting|doc|0.0.13
docs-markdown|doc|1.0.2
docs-metadata|doc|1.0.9
docs-preview|doc|1.0.3
docs-scaffolding|doc|1.0.0
docs-yaml|doc|1.0.1
gitlens|eam|14.3.0
pythonsnippets|frh|1.0.2
codespaces|Git|1.15.1
remotehub|Git|0.60.0
vscode-github-actions|git|0.26.2
vscode-pull-request-github|Git|0.72.0
go|gol|0.39.1
terraform|has|2.27.2
vsc-python-indent|Kev|1.18.0
vscode-docker|ms-|1.26.0
vscode-kubernetes-tools|ms-|1.3.13
data-workspace-vscode|ms-|0.5.0
mssql|ms-|1.20.1
sql-bindings-vscode|ms-|0.4.0
sql-database-projects-vscode|ms-|1.2.0
isort|ms-|2023.10.1
python|ms-|2023.16.0
vscode-pylance|ms-|2023.9.10
jupyter|ms-|2023.8.1002501831
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.17
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-slideshow|ms-|0.1.5
remote-containers|ms-|0.309.0
remote-ssh|ms-|0.106.3
remote-ssh-edit|ms-|0.86.0
remote-wsl|ms-|0.81.3
vscode-remote-extensionpack|ms-|0.24.0
powershell|ms-|2023.6.0
remote-explorer|ms-|0.4.1
remote-repositories|ms-|0.38.1
remote-server|ms-|1.4.3
vscode-markdown-notebook|ms-|0.0.26
vsliveshare|ms-|1.0.5883
vsliveshare-pack|ms-|0.4.0
vscode-sanddance|msr|4.1.0
autodocstring|njp|0.6.1
vscode-yaml|red|1.14.0
vscode-taskexplorer|spm|2.13.2
code-spell-checker|str|3.0.1
intellicode-api-usage-examples|Vis|0.2.8
vscodeintellicode|Vis|1.2.30
vscodeintellicode-completions|Vis|1.0.22
vscode-icons|vsc|12.5.0

(7 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscorecescf:30445987
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
vscccc:30803845
2e4cg342:30602488
89544117:30613380
showlangstatbar:30737416
a2ce3375:30757347
57b77579:30736110
pythonfmttext:30731395
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
pythonnosmt12:30797651
pythonidxptcf:30805731
pythonnoceb:30805159
dsvsc013:30795093
dsvsc014:30804076
diffeditorv2:30821572
dsvsc015cf:30829746

```

</details>

**Comment by Gobinath-B** [comment]
@mjbvz Can i work on this issue?
