### ISSUE TITLE
Github pull request fails to login after reload window when used with Vscode on browser 

### ISSUE THREAD

**Issue by mmohdnowfal** [microsoft/vscode#192868]
Does this issue occur when all extensions are disabled?: Yes/No
No, since the issue is related to Github pull request extension 

- VS Code Version: 1.82.0 (Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36)
- OS Version: Linux xxxx-xxxx-xxxx 4.18.0-372.13.1.el8_6.x86_64 #1 SMP Mon Jun 6 15:05:22 EDT 2022 x86_64 x86_64 x86_64 GNU/Linux

Steps to Reproduce:

1.  Build vscode in the remote machine using ` yarn gulp  vscode-reh-web-linux-x64`
2.  launch vscode server from the generated yarn build in remote machine using `cd ../vscode-reh-web-linux-x64;./bin/code-server-oss --port 3005`
4. Connect to vscode from the browser and open any git workspace
5. Install github pull request extension 
6. Sign In and authenticate the extension
7. Reload window
8. Check Github panel (it doesn't remember the extension login, and asks for login again)

Screenshot before Reload
-------------------------
<img width="295" alt="Screenshot 2023-09-12 at 4 24 42PM" src="https://github.com/microsoft/vscode/assets/15832093/029c782b-9965-43b6-b0fd-d658fdf72081">

Screen shot after reload
------------------------
<img width="295" alt="Screenshot 2023-09-12 at 4 24 41 PM" src="https://github.com/microsoft/vscode/assets/15832093/20b956bd-df4b-4e5f-a5ad-c2e925fa2e15">

<img width="1303" alt="Screenshot 2023-09-12 at 4 24 36 PM" src="https://github.com/microsoft/vscode/assets/15832093/794f81df-ae2a-49d2-a7c8-2d2db6ac4a3d">

**Comment by TylerLeonhardt** [comment]
This is expected. We do not have a way to store the GitHub access token in a secure way so we store it in memory.

Persisted storage in the web only works in:
* vscode.dev, the client talks to the server to get an encryption key.
* `code serve-web` because the client talks to a server that the `code` CLI spins up to get an encryption key.
