### ISSUE TITLE
SCM doesn't persist diff view - inline vs side-by-side

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#19287]
Testing https://github.com/Microsoft/vscode/issues/19049

With SCM preview enabled,
- Make a change to a file
- Click the file in the SCM viewlet to open the diff view
- In the `...` editor dropdown, click "switch to inline view" (or side-by-side) to toggle the diff view style
- Close the diff editor
- Open the diff editor again
- See that the diff view style has reverted to the previous style, and now the option under the `...` menu doesn't match:

![image](https://cloud.githubusercontent.com/assets/323878/22268815/cde770f4-e23d-11e6-99b7-a34ec7dd7923.png)

**Comment by joaomoreno** [comment]
I believe this Switch is a temporary one for that specific editor. There is a `diffEditor.renderSideBySide` setting which you can change to make it apply to all the diff editors.

**Comment by roblourens** [comment]
But it's persisted in that dropdown label, just not in the actual editor - you can see in the screenshot that it's now already in side by side view, but says 'switch to side by side view'. I don't know whether the label should be reset or the diff view should be persisted.

**Comment by joaomoreno** [comment]
Oh, makes sense! This is kind of strange.

**Comment by joaomoreno** [comment]
@bpasero This toggle state is [kind of strange](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/browser/parts/editor/textDiffEditor.ts#L286), and doesn't work at all if the diff editor is opened from the API.

**Comment by schmuli** [comment]
Using 1.10.0-insider
0b27b528a7aac070bced1239310144d0763823bd

@bpasero, currently, I'm unable to view inline diff view at all, the menu doesn't change and the view doesn't update. This is also true when not using the SCM Preview too, so I don't know if this is related to your commit.

**Comment by bpasero** [comment]
Yeah, I fixed that too via https://github.com/Microsoft/vscode/commit/a765e68c7272af19bcd4f645424297c8f6575cfa
