### ISSUE TITLE
Why show total # of settings or # of settings matched at all?

### ISSUE THREAD

**Issue by ramya-rao-a** [Microsoft/vscode#19280]
Testing #19059

What does the user gain by knowing that there are 448 settings?
![image](https://cloud.githubusercontent.com/assets/16890566/22266037/45891f1e-e233-11e6-96ae-d4fdefcbb4a4.png)

While searching, we match both on LHS and the RHS. The settings matched number I believe is only from LHS. Isnt that misleading?
![image](https://cloud.githubusercontent.com/assets/16890566/22266064/5c7605ca-e233-11e6-97f2-334efd93d277.png)

**Comment by sandy081** [comment]
@ramya-rao-a It is necessary to show the number of matches while searching. But showing the total   is just to be nicer and always showing the badge.

Regarding the count, it shows the number of unique settings matching. I see there is a duplication in if a setting is in commonly used and others which will be fixed here #16699
