### ISSUE TITLE
Explore Electron.net API support in the utility process

### ISSUE THREAD

**Issue by deepak1556** [microsoft/vscode#192899]
It would provide us with the possibility of using chromium network stack which has better support for proxies directly from the utility process. Currently chromium transfers URLLoaderFactories to renderer process which allows blink to make network requests directly from the network service without having the need to go through the browser process, we will try to follow the same principle in this exploration.

- [x] Validate the exploration using a simple prototype
- [x] Scaffold [Electron.net](https://github.com/electron/electron/blob/main/docs/api/net.md) for the utility process

## Prototype Implementation:

Let's create a interface on the NodeService utility process which accepts a URLLoaderFactory from the browser process and uses it to create a URLLoader to issue simple http(s) requests and outputs the response to a file.

## Consists of 3 components
* Declaring a mojo interface to transfer the URLLoaderFactory
* Defining the interface in the Utility Process
* Invoking the interface from the Browser Process

/cc @devm33

**Comment by deepak1556** [comment]
Steps for verification:

* Add the following setting `"github.copilot.advanced": { "debug.useElectronFetcher": true }`
* Reload Window
* Open `Github Copilot Chat` output panel and check for the following log `FetcherService] Using Electron fetcher`
* Test that chat requests are fullfilled without any network issues.

**Comment by joaomoreno** [comment]
<img width="740" alt="image" src="https://github.com/microsoft/vscode/assets/22350/080ebb74-8b80-4579-9af5-ca5e82843559">
