### ISSUE TITLE
Auto import code fix does not appear when being fast

### ISSUE THREAD

**Issue by alexdima** [microsoft/vscode#192890]
Steps to Reproduce:

1. Open a test file where ensureNoDisposablesAreLeakedInTestSuite is not imported
2. Paste it and press cmd+. quickly
3. The auto-import quick fix doesn't show
4. Pressing cmd+. again will show the auto-imoprt quick fix

Obs: Sorry that it took me a long time to file this, but I run into this all the time, at least a few times every day since months if not years.

https://github.com/microsoft/vscode/assets/5047891/1d2b4d44-031a-4ca1-9190-741bd0ac4c05

**Comment by bpasero** [comment]
Same for me, not really a new regression, but for a long time.

**Comment by mjbvz** [comment]
See https://github.com/microsoft/TypeScript/issues/46249. The current TS server protocol requires adding more code to the VS Code side. I'd prefer shifting this over to TS instead (which will also help TS align more with the LSP)

**Comment by mjbvz** [comment]
Actually already tracked by #117812
