### ISSUE TITLE
Windows remote integration tests crash

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#192857]
https://dev.azure.com/monacotools/Monaco/_build/results?buildId=231540&view=artifacts&pathAsName=false&type=publishedArtifacts

[f9d2ddab-06ef-4936-a9ca-fb864b020a8b.dmp.zip](https://github.com/microsoft/vscode/files/12584867/f9d2ddab-06ef-4936-a9ca-fb864b020a8b.dmp.zip)

**Comment by rzhao271** [comment]
Symbolicated 

[symbolicated-f9.log](https://github.com/microsoft/vscode/files/12611110/symbolicated-f9.log)

**Comment by rzhao271** [comment]
Potential duplicate of #192119

**Comment by deepak1556** [comment]
Merging to https://github.com/microsoft/vscode/issues/192119
