### ISSUE TITLE
v1.82.0 regression:  http.proxySupport = fallback 

### ISSUE THREAD

**Issue by GordonSmith** [microsoft/vscode#192810]
Type: <b>Bug</b>

Setting `http.proxySupport = fallback` no longer works as documented.

Specifcally my VSCode extension uses code equivilant to:  

```
const https = require("https");
const agent = new https.Agent({ rejectUnauthorized: false });
fetch("https://localhost/", { agent: agent });
```

Which was reliant on setting `http.proxySupport = fallback` to work.

VS Code version: Code 1.82.0 (8b617bd08fd9e3fc94d14adb8d358b56e3f72314, 2023-09-06T22:07:07.438Z)
OS version: Windows_NT x64 10.0.23541
Modes:
Remote OS version: Linux x64 5.15.90.4-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 9 5950X 16-Core Processor             (32 x 3400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|63.91GB (37.41GB free)|
|Process Argv|--crash-reporter-id 207c1fc7-7e56-401a-9747-9b1568649f1b|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-22.04|
|OS|Linux x64 5.15.90.4-microsoft-standard-WSL2|
|CPUs|AMD Ryzen 9 5950X 16-Core Processor (28 x 3400)|
|Memory (System)|54.92GB (47.88GB free)|
|VM|0%|
</details><details><summary>Extensions (64)</summary>

Extension|Author (truncated)|Version
---|---|---
webassembly|trf|0.2.0
rankedcodehelper|bin|1.0.5
mermaid-markdown-syntax-highlighting|bpr|1.5.2
vscode-eslint|dba|2.4.2
githistory|don|0.6.20
typescript-notebook|don|2.0.6
vscode-wasm|dts|1.4.1
rust-syntax|dus|0.6.1
codespaces|Git|1.15.1
copilot|Git|1.110.389
copilot-chat|Git|0.7.0
copilot-labs|Git|0.15.1019
remotehub|Git|0.60.0
vscode-github-actions|git|0.26.2
vscode-pull-request-github|Git|0.72.0
js-notebook-extension-pack|Gor|1.0.6
observable-js|Gor|0.4.37
ecl|hpc|2.23.3
latex-workshop|Jam|9.13.4
better-cpp-syntax|jef|1.17.2
vscode-graphviz|joa|0.0.6
svg|joc|1.5.3
git-graph|mhu|1.30.0
vscode-docker|ms-|1.26.0
vscode-dotnet-runtime|ms-|1.7.2
vscode-edge-devtools|ms-|2.1.3
vscode-kubernetes-tools|ms-|1.3.13
python|ms-|2023.16.0
vscode-pylance|ms-|2023.9.10
datawrangler|ms-|0.16.0
jupyter|ms-|2023.8.1002501831
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.17
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-slideshow|ms-|0.1.5
remote-containers|ms-|0.309.0
remote-ssh|ms-|0.106.3
remote-ssh-edit|ms-|0.86.0
remote-wsl|ms-|0.81.3
vscode-remote-extensionpack|ms-|0.24.0
azure-repos|ms-|0.36.0
cmake-tools|ms-|1.15.31
cpptools|ms-|1.17.5
cpptools-extension-pack|ms-|1.3.0
remote-explorer|ms-|0.4.1
remote-repositories|ms-|0.38.1
remote-server|ms-|1.4.3
vscode-react-native|msj|1.11.2
vscode-sanddance|msr|4.1.0
vscode-streamdeck|nic|4.1.6
fabric8-analytics|red|0.7.0
java|red|1.21.0
vscode-xml|red|0.26.1
vscode-yaml|red|1.14.0
code-spell-checker|str|3.0.1
cmake|twx|0.0.17
intellicode-api-usage-examples|Vis|0.2.8
vscodeintellicode|Vis|1.2.30
vscode-java-debug|vsc|0.54.0
vscode-java-dependency|vsc|0.23.1
vscode-java-pack|vsc|0.25.13
vscode-java-test|vsc|0.39.1
vscode-maven|vsc|0.42.0
gitblame|wad|10.5.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263:30335439
vscoreces:30445986
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
py29gd2263cf:30792227
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
vsccc:30803844
282f8724:30602487
f6dab269:30613381
showlangstatbar:30737416
0bi6i642:30831757
03d35959:30757346
pythonfmttext:30731395
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
pythonnosmt12:30797651
pythonidxptcf:30805731
pythonnoceb:30805159
asynctok:30821568
dsvsc013:30795093
dsvsc014:30804076
diffeditorv2:30821572
dsvsc015:30829745

```

</details>

**Comment by gjsjohnmurray** [comment]
Maybe the issue is related to the change documented at https://code.visualstudio.com/updates/v1_82#_update-highlights-for-nodejs

**Comment by GordonSmith** [comment]
> Maybe the issue is related to the change documented at https://code.visualstudio.com/updates/v1_82#_update-highlights-for-nodejs

I suspect its related, but entering an IP address also fails.  Feels like the setting is just ignored.

**Comment by chrmarti** [comment]
What does `fetch` refer to? Can you post a minimal reproducible case including the server code?

**Comment by chrmarti** [comment]
Does it work with plain Node 18? (VS Code 1.82 comes with Node 18 that includes `fetch`. VS Code 1.81 was using Node 16.)

**Comment by GordonSmith** [comment]
Turns out it was a conflict between the NodeJS fetch and a third party library that was also using node-fetch (but ended up calling NodeJS fetch)...
