### ISSUE TITLE
Debug Console super slow

### ISSUE THREAD

**Issue by cemde** [microsoft/vscode#192823]
Type: <b>Bug</b>

I am having an issue with the debug console. I am debugging Python and typing simple expressions into the debug console, such as `a=5` and `a > 5`. These statements sometimes take minutes to display in the debug console. However, `print(a > 5)` immediately appears in the terminal and the variables in the left panel respond fast when I try to investiage attributes of more complex models. This makes me conclude, that this really is about the `Debug Console`. Restarting the VSCode window helps for 2-3 debug console prompts, then the error returns.

VS Code version: Code 1.82.0 (Universal) (8b617bd08fd9e3fc94d14adb8d358b56e3f72314, 2023-09-06T22:09:41.364Z)
OS version: Darwin x64 22.6.0
Modes:
Remote OS version: Linux x64 5.4.0-156-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 2900)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (0.20GB free)|
|Process Argv|--crash-reporter-id cfb0c38a-a34d-420e-b562-0be959202ed2|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: PSSR2|
|OS|Linux x64 5.4.0-156-generic|
|CPUs|Intel(R) Xeon(R) Gold 5218 CPU @ 2.30GHz (64 x 2313)|
|Memory (System)|739.78GB (730.71GB free)|
|VM|0%|
</details><details><summary>Extensions (21)</summary>

Extension|Author (truncated)|Version
---|---|---
jupyter-keymap|ms-|1.1.2
remote-containers|ms-|0.311.0
remote-ssh|ms-|0.106.3
remote-ssh-edit|ms-|0.86.0
remote-wsl|ms-|0.81.3
vscode-remote-extensionpack|ms-|0.24.0
remote-explorer|ms-|0.4.1
remote-server|ms-|1.4.3
ruff|cha|2023.35.12491300
gitlens|eam|14.3.0
copilot|Git|1.110.389
vscode-pull-request-github|Git|0.72.0
vscode-docker|ms-|1.26.0
black-formatter|ms-|2023.5.12511009
python|ms-|2023.17.12541009
vscode-pylance|ms-|2023.9.12
jupyter|ms-|2023.8.1002501831
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.17
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-slideshow|ms-|0.1.5

</details>

**Comment by doyled-it** [comment]
I am also experiencing this.

**Comment by senayuki** [comment]
Also 1.82.0 under macOS. 
I my case, what I print wont refresh immediately. I encountered both in remote SSH and local debugging. When switching to other tabs and come back, which is effective in most cases, but sometimes it also does not work.

**Comment by roblourens** [comment]
https://github.com/microsoft/vscode/issues/192653 would appreciate checking for errors in the developer tools (Help > Toggle Developer Tools)
