### ISSUE TITLE
Atomic write should not be enabled for all usages of `vscode-userdata`

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#192970]
While looking into @rebornix question in https://github.com/microsoft/vscode/issues/167719#issuecomment-1716900371, I noticed how now all writes triggered from `vscode-userdata` scheme have `atomic: true`:

https://github.com/microsoft/vscode/blob/d649d877f48664eee857dcb93dd4c331bd8908a1/src/vs/platform/userData/common/fileUserDataProvider.ts#L88-L93

Since backups use this scheme, every time an editor is dirty and backs up, it will write atomically. I think we need to be careful here because atomic writes have a significant performance overhead in that they write the entire contents in one `VSBuffer` to disk at once and skip streaming.

For now I would suggest to really scope `atomic: true` only to those specific cases we wanted to fix, such as settings.

Steps:
* open a file
* make it dirty
* notice how `DiskFileSystemProvider.doWriteFileAtomic` is triggered with the entire contents

**Comment by sandy081** [comment]
> Since backups use this scheme...

I was not expecting this. Why is backups using this scheme? I believe backups are not part of user data.

**Comment by bpasero** [comment]
@sandy081 yeah also came to my surprise to be honest.

**Comment by sandy081** [comment]
yeah, that could be the reason. Is it possible not to use userdata scheme in desktop?

**Comment by rebornix** [comment]
While testing medium size files, I found backing up dirty files can cause the UI to freeze as it's not streamed, the whole process is stuck at encoding the whole string. As you can see in the perf log below, the file saving is doing fine as it's chunk-by-chunk so it doesn't hurt the frame rate. 


<img width="984" alt="image" src="https://github.com/microsoft/vscode/assets/876920/84b254a3-aead-4e80-953e-3eb8f9c3ba56">

**Comment by sandy081** [comment]
Scoped atomic write to following resources:

- Settings
- Keybindings
- Tasks
- Extensions
