### ISSUE TITLE
inline debuging shows incomplete json parse result

### ISSUE THREAD

**Issue by rebornix** [Microsoft/vscode#19297]
Testing #18670 

Steps to Reproduce:

1. Debugging https://github.com/rebornix/vscode-project-snippet
2. Add breakpoint to Line 23 in `extension.ts`
3. Debug and hit breakpoints.

![screen shot 2017-01-24 at 2 49 02 pm](https://cloud.githubusercontent.com/assets/876920/22270412/466042f8-e244-11e6-919a-dc58d32bed81.png)

The value of JSON parse is incomplete as `"{`

**Comment by isidorn** [comment]
This is how inline css values are treating `\n`characters in string.
Forwarding to @aeschli I would like the inline css to preserve my escaped new line character
If I double escape it on my side I get an `n` character which is also not good

Good old escaping

**Comment by aeschli** [comment]
Not sure what you mean by inline css...

**Comment by aeschli** [comment]
@isidorn Isi, do you have more information?

**Comment by isidorn** [comment]
Yes, sorry for not making it clear in my previous comment.
Have the following string 'hello \n martin' as the `contentText` for an end of line decoration. Add that decoration to the editor and notice that only the 'hello' is decorated. 
I would expect the whole string to be contained in the decoration (the newline escaped)

**Comment by aeschli** [comment]
You should do that on your side. Maybe replace all new lines with spaces, or cut it.
The before/after decorator can only render one line. Passing multiple lines is an invalid use of the API and the implementation now just takes the first line.

**Comment by isidorn** [comment]
@aeschli But if I escape the \n with \\n you show just the n, not \n. We are back in escaping hell.
I could just remove it, but showing \n would be better

**Comment by isidorn** [comment]
PRs accepted 
Code pointer https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/debug/electron-browser/debugEditorContribution.ts#L48

**Comment by weinand** [comment]
Passing more than one line to the end of line decoration is an "invalid use of the API" which is a bug.
I suggest to fix it by replacing the newline by a space (and to file a new issue "backslash not shown in end of line decoration")
