### ISSUE TITLE
Dates are broken in git history view of source control view

### ISSUE THREAD

**Issue by RichardJECooke** [microsoft/vscode#192984]
Type: <b>Bug</b>

Open any folder with a git repository.
Open the git sidebar in VS Code (ctrl-shift-g).
Click on the counterclockwise arrow (Git: View history (git log)).
Notice that all the dates are broken. They are swapping the month and day incorrectly so every date is backwards.

VS Code version: Code 1.82.1 (6509174151d557a81c9d0b5f8a5a1e9274db5585, 2023-09-08T08:41:36.199Z)
OS version: Linux x64 6.2.0-1012-lowlatency snap
Modes:

**Comment by gjsjohnmurray** [comment]
I think that feature is contributed by the GitLens extension. You can verify this by disabling it temporarily. Assuming I am correct please report it to the extension author.

**Comment by RichardJECooke** [comment]
Ah, it's  not gitlens, I have something called 'git history' installed. Thanks, didn't realise this was a plugin

**Comment by RichardJECooke** [comment]
Ah, no, actually it is a VS Code issue that affects all extensions - https://github.com/microsoft/vscode/issues/56995
