### ISSUE TITLE
Linux: 'Git: pull' and 'Git: push' commands have no effect

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#19292]
Testing https://github.com/Microsoft/vscode/issues/19049

- Have a git repo with new commits and SCM Preview enabled
- Do 'Git: push' from the command palette
- Watching the Git output log, no new output appears, and the commits are not pushed

Same for git pull

**Comment by joaomoreno** [comment]
Merging into #18615

https://github.com/Microsoft/vscode/blob/master/extensions/git/src/commands.ts#L390
