### ISSUE TITLE
Log files created should be created under the log home folder of the process by default

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#192930]
A logger file created in the window (renderer) process should create the log file scoped to that window. For example, following should create the view log file under the current window

```ts
loggerService.createLogger('view', { name: 'view' })
```

If a component wants to create the logger shared across windows, one should provide the log file while creating the logger as follows

```ts
loggerService.createLogger(joinPath(environmentService.logsHome, `${LOG_ID}.log`), { id: LOG_ID, name: LOGGER_NAME })
```

**Comment by sandy081** [comment]
@Tyriar @joyceerhl 

It seems, terminal and editSessions loggers are shared across windows. I have adopted them accordingly. If they are not intended to be shared across windows, feel free to revert my change.

Thanks.

**Comment by Tyriar** [comment]
@sandy081 this is great, thanks!
