### ISSUE TITLE
SSH not working in code snap revision 139

### ISSUE THREAD

**Issue by jacopo-salvalaggio** [microsoft/vscode#192978]
Type: <b>Bug</b>

This is a report on (maybe) both Code and the SSH extension. Since I have refreshed my Code snap to revision 139 I cannot connect to my ssh server anymore. It either keeps retrying to connect and fails or prompts a message saying that the page needs to be reloaded. Reverting back to revision 137 and to the pre-release version of the extension solves the problem entirely.

VS Code version: Code 1.81.1 (6c3e3dba23e8fadc360aed75ce363ba185c49794, 2023-08-09T22:18:39.991Z)
OS version: Linux x64 6.2.0-32-generic snap
Modes:
Remote OS version: Linux x64 3.10.0-693.el7.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz (16 x 2289)|
|GPU Status|2d_canvas: unavailable_software<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>opengl: disabled_off<br>rasterization: disabled_software<br>raw_draw: disabled_off_ok<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software<br>webgpu: disabled_off|
|Load (avg)|2, 1, 1|
|Memory (System)|15.29GB (8.73GB free)|
|Process Argv|--no-sandbox --force-user-env --unity-launch --crash-reporter-id 09b4b659-f367-4d8d-a52f-416848f278c3|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|wayland|

|Item|Value|
|---|---|
|Remote|SSH: amonra|
|OS|Linux x64 3.10.0-693.el7.x86_64|
|CPUs|Intel(R) Xeon(R) Silver 4114 CPU @ 2.20GHz (40 x 800)|
|Memory (System)|251.37GB (230.89GB free)|
|VM|0%|
</details><details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
vsc-material-theme|Equ|33.10.5
vsc-material-theme-icons|equ|3.0.4
better-cpp-syntax|jef|1.17.2
theme-monokai-pro-vscode|mon|1.2.1
jupyter-keymap|ms-|1.1.2
remote-containers|ms-|0.309.0
remote-ssh|ms-|0.105.2023080715
remote-explorer|ms-|0.4.1
synthwave-blues|sab|0.0.5
python|ms-|2023.14.0
vscode-pylance|ms-|2023.9.10
jupyter|ms-|2023.7.1002162226
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.17
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-slideshow|ms-|0.1.5

(32 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
py29gd2263:30792226
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
vsccc:30803844
2e4cg342:30602488
f6dab269:30613381
showlangstatbar:30737416
a2ce3375:30757347
pythonfmttext:30731395
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
pythonnosmt12:30797651
pythonidxptcf:30805731
pythonnoceb:30805159
dsvsc013:30795093
dsvsc014:30804076
diffeditorv2:30821572
dsvsc015:30829745

```

</details>

**Comment by MarvinQuevedo** [comment]
I receive the same error, I downgrade to 1.81 in mac for can work, but many extensions not working in It

**Comment by roblourens** [comment]
Please make sure you have the latest version of vscode and the Remote-SSH extension, and share the log from the Remote-SSH output channel, thanks

**Comment by jacopo-salvalaggio** [comment]
Updated to snap revision 140 and release version of Remote-SSH extension. It works now! Thanks :)
