### ISSUE TITLE
R plot appears in VSCode panel, then panel turns blank gray.

### ISSUE THREAD

**Issue by terence-patrick** [microsoft/vscode#192927]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.82.1
- OS Version: MacOS 13.5.2

Steps to Reproduce:

1. Open R session
2. Load a .csv dataset
3. Load librarys tidyverse, httpgd
4. Use ggplot2 to create a scatterplot of data
5. Scatterplot opens in VSCode R Plot window
6. Window turns blank gray after several seconds.
7. Scatterplot can be opened in external browser window without issue.

![Screenshot 2023-09-12 at 1 54 18 PM](https://github.com/microsoft/vscode/assets/130315086/1eb7375a-452c-4ae5-b96a-985cbcf54c85)

**Comment by deepak1556** [comment]
Should be reported to the R extension https://github.com/REditorSupport/vscode-R, please open a issue in their repo.
