### ISSUE TITLE
Command center not showing when switched from off to on

### ISSUE THREAD

**Issue by busy-duck** [microsoft/vscode#192937]
Type: <b>Bug</b>

1. Setting the command center as off using the pop-up menu in the title bar
2. Setting it on only displays the two arrows and not the search bar (see screenshot below)

<img width="1024" alt="git" src="https://github.com/microsoft/vscode/assets/144853664/d82dc8a5-c133-4923-8d65-48be4240bbdd">

VS Code version: Code 1.82.1 (Universal) (6509174151d557a81c9d0b5f8a5a1e9274db5585, 2023-09-08T08:49:32.930Z)
OS version: Darwin arm64 22.6.0
Modes:

<details><summary>Extensions (20)</summary>

Extension|Author (truncated)|Version
---|---|---
gitlens|eam|14.3.0
RunOnSave|eme|0.2.0
latex-workshop|Jam|9.13.4
vscode-vector-aquarium|le-|0.0.2
json|Mee|0.1.2
python|ms-|2023.16.0
vscode-pylance|ms-|2023.9.10
jupyter|ms-|2023.8.1002501831
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.17
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-slideshow|ms-|0.1.5
indent-rainbow|ode|8.3.1
r|REd|2.8.1
code-spell-checker|str|3.0.1
code-spell-checker-french|str|0.4.0
vscode-pets|ton|1.25.0
intellicode-api-usage-examples|Vis|0.2.8
vscodeintellicode|Vis|1.2.30
console-ninja|Wal|0.0.218

(1 theme extensions excluded)

</details>

**Comment by jrieken** [comment]
Yeah, it's a bit confusing but there are two things that are both named command center: 

* command center (via the setting) is the whole title bar toolbar
* command center is the quick pick entry of that toolbar. this can be configured via the context menu

**Comment by busy-duck** [comment]
Oh ok thanks I tried setting it on and off using the two options but the command center stays the same when setting it on from both sources.
Just to be clear, the context menu is the thing portrayed in the screenshot I took ?
<img width="145" alt="vscode" src="https://github.com/microsoft/vscode/assets/144853664/79c479bb-43dd-43bd-a61a-eb1fffba655d">

**Comment by jrieken** [comment]
> Just to be clear, the context menu is the thing portrayed in the screenshot I took ?

It's more confusing 🙈 there is another context menu on the arrows

**Comment by busy-duck** [comment]
Wow I did not know that 🫠 !
Yes it did fix the issue I had (see in the photos I added).

Thanks a lot
<img width="149" alt="context" src="https://github.com/microsoft/vscode/assets/144853664/979b9623-007c-4533-920a-db84d553f4ac">
<img width="1019" alt="vscode" src="https://github.com/microsoft/vscode/assets/144853664/b5fae614-f29e-40ba-b08e-f1587fb9b60c">
