### ISSUE TITLE
VS Code window is not responding after update and has black and white formations

### ISSUE THREAD

**Issue by xaristeidou** [microsoft/vscode#192985]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.82.1
- OS Version: Ubuntu 20.04

VS Code was working properly while an update popped up from snap store. The update was installed, and when I re-opened vscode the window is now showing almost anything except the ribbon on the top. Whatever I click doesn't do anything, and has white and black rectangle boxes in the window. 

I installed manually a previous version of vscode (1.81.1) and it did work but Python extension mentioned that it was not supported and needed  > 1.81

![Screenshot from 2023-09-13 11-47-32](https://github.com/microsoft/vscode/assets/65918758/5754ea5f-ba64-4af0-a417-9214873c7632)

**Comment by shu512** [comment]
Experiencing the same issue after the latest update 
VS Code Version: 1.82.1
OS Version: Ubuntu 20.04

**Comment by rienk-git** [comment]
Same here:
VS Code Version: 1.82.1
OS Version: Ubuntu 20.04

Seems to be related to this:

link failed but did not provide an info log
[11819:0913/111619.223859:WARNING:angle_platform_impl.cc(48)] ProgramGL.cpp:989 (checkLinkStatus): Program link or binary loading failed with no info log.
[11819:0913/111619.223884:ERROR:shared_context_state.cc(81)] Skia shader compilation error

**Comment by nicklyk** [comment]
/duplicate https://github.com/microsoft/vscode/issues/190437

Please delete the GPUCache as mentioned in https://code.visualstudio.com/updates/v1_82#_update-highlights-for-chromium

**Comment by shu512** [comment]
Thanks @nicklyk
`rm -rf ~/.config/Code/GPUCache`

**Comment by deepak1556** [comment]
Merging to https://github.com/microsoft/vscode/issues/190437
