### ISSUE TITLE
"window.newWindowDimensions": "fullscreen" opens with menubar visible

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#19299]
Test item #18632 

- VSCode Version: Code - Insiders 1.9.0-insider (4265f5e35cb3ea8ba7e0cf6b14ec606b6f8647ea, 2017-01-24T10:37:36.620Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: None

Steps to Reproduce:

1. Toggle Fullscreen in non-fullscreen window -> fullscreen without menubar
2. Open new window with "window.newWindowDimensions": "fullscreen" -> fullscreen with menubar

Seems inconsistent.

**Comment by bpasero** [comment]
Good catch 👍
