### ISSUE TITLE
Closing parenthesis dedents the line, but Format Document re-indents it

### ISSUE THREAD

**Issue by andy-ms** [Microsoft/vscode#19291]
- VSCode Version: 1.9.0-insider
- OS Version: Linux Mint 18

Steps to Reproduce:

1. Open a TypeScript file and type:
```ts
Math.max(
    1,
    2
```

2. Type `)`.
3. You will see:

```ts
Math.max(
    1,
2)
```

4. Use the "Format Document" command to bring back correct formatting (with an indent before `2)`).

**Comment by mousetraps** [comment]
Thx for reporting! I can reproduce the same behavior on my machine as well.

**Comment by rebornix** [comment]
This is the electric part of our typing intercepters. When we see a closing paired characters defined by the language, we'll try to align the indentation to the one of the opening paired characters. This is also why when you press `}`, it can be automatically aligned the `{` you write before. To some extent, this one is false positive.

**Comment by alexandrudima** [comment]
We could change the electric brackets to only work on whitespace only lines.
