### ISSUE TITLE
inline debugging is showing result in other paths that the code doesn't go into

### ISSUE THREAD

**Issue by rebornix** [Microsoft/vscode#19298]
Testing #18670 

Steps to Reproduce:

1. Debugging smoke test project and set the launch type as `node2`
2. Add breakpoint to `normalizePort` in `www`
3. Debug and hit breakpoints.

![screen shot 2017-01-24 at 3 07 49 pm](https://cloud.githubusercontent.com/assets/876920/22270925/e456c96c-e246-11e6-85dc-643710eac268.png)

The if statement in line 40 is false so line 41 doesn't get executed however we are still showing value for it.

**Comment by isidorn** [comment]
As designed.
We can not improve this since we do not have static langugage interpretation of the code execution.
I could leave this as open feature request but I do not think it will ever happen thus closing
