### ISSUE TITLE
inline debugging shows variable value even the line is not executed

### ISSUE THREAD

**Issue by rebornix** [Microsoft/vscode#19295]
Testing #18670 

Steps to Reproduce:

1. Debugging https://github.com/rebornix/vscode-project-snippet
2. Add breakpoint to ReadAndRegisterSnippets
3. Debug and hit breakpoints.

![screen shot 2017-01-24 at 2 43 08 pm](https://cloud.githubusercontent.com/assets/876920/22270325/d6769cee-e243-11e6-96f8-0c6448ba9cd9.png)

From the image above you can see a lot of `vscode = ...` values.

**Comment by rebornix** [comment]
The functions above the breakpoint are actually parsed when loaded so technically it make senses that `vscode ...` are there but they are annoying somehow.

**Comment by isidorn** [comment]
We limit the size of each object preview to improve readability.
Otherwise one long object would just clutter the whole line and nothing else could be seen

Closing as designed
