### ISSUE TITLE
August 2023 Recovery 2

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode#192900]
- [x] Create a milestone `August 2023 Recovery 2` @chrmarti
- [x] Bump the version number @chrmarti
- [x] [🔖candidate issues](https://github.com/issues?q=is%3Aissue%20label%3Acandidate%20repo:microsoft/monaco-editor%20repo:microsoft/vscode%20repo:microsoft/vscode-anycode%20repo:microsoft/vscode-copilot%20repo:microsoft/vscode-copilot-release%20repo:microsoft/vscode-dev%20repo:microsoft/vscode-dev-chrome-launcher%20repo:microsoft/vscode-emmet-helper%20repo:microsoft/vscode-extension-telemetry%20repo:microsoft/vscode-github-issue-notebooks%20repo:microsoft/vscode-hexeditor%20repo:microsoft/vscode-internalbacklog%20repo:microsoft/vscode-js-debug%20repo:microsoft/vscode-jupyter%20repo:microsoft/vscode-jupyter-internal%20repo:microsoft/vscode-l10n%20repo:microsoft/vscode-livepreview%20repo:microsoft/vscode-pull-request-github%20repo:microsoft/vscode-python%20repo:microsoft/vscode-python-debugger%20repo:microsoft/vscode-references-view%20repo:microsoft/vscode-remote-release%20repo:microsoft/vscode-remote-repositories-github%20repo:microsoft/vscode-remote-tunnels%20repo:microsoft/vscode-remotehub%20repo:microsoft/vscode-settings-sync-server%20repo:microsoft/vscode-unpkg%20repo:microsoft/vscode-vsce%20milestone%3A%22August%202023%20Recovery%202%22)
- [x] Assign candidate issues to the recovery milestone **team**
- [x] Review the `candidate` issues, and if they pass the review assign them to the recovery milestone **team**
- [x] All `candidate` fixes are peer reviewed and pushed to `main` and then cherry-picked into the release branch **team**
- [x] Initiate `insiders` build from `main`
- [x] Issues are tested in the `insiders` **team**
- [x] Build `stable` for all platforms from release branch @chrmarti
- [x] Issues are verified on `stable` build and the `verified` label is added @chrmarti
- [x] Check `https://github.com/Microsoft/vscode/compare/release/1.82` to ensure no other commits have been made in the release branch @chrmarti
- [x] Update the release notes and include a link to a query for the fixed issues **@gregvanl**
- [x] [Sanity Testing](https://github.com/microsoft/vscode/wiki/Sanity-Check)
  - [x] Windows 32 bit @hediet 
    - [ ] System Installer
    - [ ] User Installer
    - [ ] Archive
    - [ ] Server
    - [ ] CLI
  - [x] Windows 64 bit @hediet 
    - [ ] System Installer
    - [ ] User Installer
    - [ ] Archive
    - [ ] Server
    - [ ] CLI
  - [x] Windows ARM64 @alexdima 
    - [x] System Installer
    - [x] User Installer
    - [x] Archive
    - [x] CLI
  - [x] macOS Intel @bpasero 
    - [x] Archive
    - [x] Universal Archive
    - [x] Server
    - [x] CLI
  - [x] macOS ARM64 @jrieken 
    - [x] Archive
    - [x] Universal Archive
    - [x] Server
    - [x] CLI
  - [x] Linux x64 @aeschli 
    - [x] Archive
    - [x] DEB
    - [x] RPM
    - [x] Snap
  - [x] Linux Server @alexr00  _(can be tested from any OS with Docker)_
    - [x] x64
    - [x] ARM32
    - [x] ARM64
    - [x] x64 Alpine
    - [x] ARM64 Alpine
  - [x] Linux CLI @sandy081  _(can be tested from any OS with Docker)_
    - [x] x64
    - [x] ARM32
    - [x] ARM64
    - [x] x64 Alpine
    - [x] ARM64 Alpine
- [x] Publish website **@gregvanl**
- [x] Publish stable build @chrmarti
- [x] Create an official release @chrmarti
  - [x] Create a tag (make sure you pull the release branch first): `git tag 1.82.2 release/1.82`
  - [x] Push the tag: `git push origin 1.82.2`
  - [x] Create a GitHub release: [Open the GitHub tags](https://github.com/microsoft/vscode/tags), and click far right `... > Create Release`. Use the correct title and description from our release notes. [Example](https://github.com/microsoft/vscode/releases/tag/1.39.1)
- [x] Close the milestone on [GitHub](https://github.com/microsoft/vscode/milestones) @chrmarti

**Comment by daiyam** [comment]
Hello, why was the `1.82.2` tag was deleted?

**Comment by chrmarti** [comment]
@daiyam Just added it. Thanks.
