### ISSUE TITLE
please allow for multiple tunnels on same machine

### ISSUE THREAD

**Issue by fordflip** [microsoft/vscode#192946]
It would be amazing if remote tunneling didn't force us into one server per machine (i.e. allow optional work around of https://github.com/microsoft/vscode/issues/171520)

An amazing feature of tunnel is to be able to use it in HPC environments, for example starting up a tunnel through an sbatch job with specific allocated resources. This allows users to connect to the newly created tunnel and use vscode's debugging with specific resources managed through cluster management systems like slurm. 

The issue is that if this happens more than once on a machine, any slurm allocation after the first will just point users to the tunnel of the first allocation, leading to conflict of resources. This would be an easy solution to workflow issues described in https://github.com/microsoft/vscode-remote-release/issues/1722 . 

Could supporting multiple tunnels on a machine be brought back?

**Comment by connor4312** [comment]
You can do this by passing different `--cli-data-dir`'s when starting the tunnel.
