### ISSUE TITLE
Formatting broken while copying settings

### ISSUE THREAD

**Issue by ramya-rao-a** [Microsoft/vscode#19294]
Testing #19059

Have some settings set in your user/workspace settings and format the file.
Ensure one of the settings is such that it needs a json object as value.
For eg:

![image](https://cloud.githubusercontent.com/assets/16890566/22270197/5c7e5c10-e243-11e6-8e08-393ebe139255.png)

Now copy a setting from the default settings view

![image](https://cloud.githubusercontent.com/assets/16890566/22270217/6d9b51ce-e243-11e6-858f-6b82505e976d.png)

Formatting is broken :(

**Comment by sandy081** [comment]
Duplicates #17195
