### ISSUE TITLE
command line --help does not show cli help

### ISSUE THREAD

**Issue by ewerybody** [microsoft/vscode#192914]
Type: <b>Bug</b>

Hello VS Code crew 🤘
## Found:
The documentation https://code.visualstudio.com/docs/editor/command-line
shows one shall type `code --help` to get help for the command line interface. But this seems broken. What I get is:

```
C:\Users\eric\AppData\Local\Programs\Microsoft VS Code>code --help

C:\Users\eric\AppData\Local\Programs\Microsoft VS Code>
[14780:0912/210820.464:ERROR:cache_util_win.cc(20)] Unable to move the cache: Access is denied. (0x5)
[14780:0912/210820.464:ERROR:disk_cache.cc(205)] Unable to create cache
```
and then a new VS Code window opens.
The short `-h` works just the same way.

## Expected:
* the [CLI options](https://code.visualstudio.com/docs/editor/command-line#_core-cli-options) are printed
* no window opens
* no confusing errors

VS Code version: Code 1.82.1 (6509174151d557a81c9d0b5f8a5a1e9274db5585, 2023-09-08T08:45:05.575Z)
OS version: Windows_NT x64 10.0.22621
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz (8 x 1498)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.74GB (6.50GB free)|
|Process Argv|--crash-reporter-id acdf514f-7def-4641-88b6-fa6e0a8d7631|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-office|cwe|3.1.6
vscode-autohotkey-plus-plus|mar|5.0.3
perforce|mjc|4.15.7
black-formatter|ms-|2023.4.1
pylint|ms-|2023.7.12211006
python|ms-|2023.17.12551009
vscode-pylance|ms-|2023.9.10
hexeditor|ms-|1.9.12
material-theme|zhu|3.16.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
vsccc:30803844
282f8724:30602487
89544117:30613380
showlangstatbar:30737416
962ge761:30835153
03d35959:30757346
pythonfmttext:30731395
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
pythonnosmt12:30797651
pythonidxpt:30805730
pythonnoceb:30805159
dsvsc013:30795093
dsvsc014:30804076
diffeditorv2:30821572
dsvsc015cf:30829746

```

</details>

**Comment by deepak1556** [comment]
Please use the shell script that lauches the command line wrapper `C:\Users\eric\AppData\Local\Programs\Microsoft VS Code>bin\code.cmd --help`
