### ISSUE TITLE
OS X: no selection occurances in scrollbar (scroll-map) after ~260 lines

### ISSUE THREAD

**Issue by bobcho** [Microsoft/vscode#193]
When a text/variable is selected, its other occurances in the file are marked in the scrollbar. Unfortunately, occurrences after the first 260 lines are not shown in the scrollbar.

Is this a setting or a bug?

**Comment by joaomoreno** [comment]
It is a performance precaution. :zap:

**Comment by bobcho** [comment]
Maybe make it a configuration option? Is this documented somewhere?

**Comment by joaomoreno** [comment]
@alexandrudima Could not find the limit anywhere to make it into a configuration option. Is there such a hard limit after all?

**Comment by alexandrudima** [comment]
Yes, there is a hard limit imposed while computing of 1000 occurences in 
https://github.com/Microsoft/vscode/blob/497788c0bcd20859f736d585b49c208af8dd518f/src/vs/editor/common/modes/abstractModeWorker.ts#L253
