### ISSUE TITLE
cannot push to git remote

### ISSUE THREAD

**Issue by JiriProkop** [microsoft/vscode#193085]
happens even without extensions
- VS Code Version:  happened on versions 1.82.1 and 1.82.2.    1.81.1 works fine
- OS Version: Ubuntu 22.04.3 LTS x86_64 
                        happened on Fedora 38 too

Steps to Reproduce:

1.  trying to push to remote repo that needs authentification 

terminal error output with extensions:
$ git push
Missing or invalid credentials.
Error: connect ENOENT /run/user/1002/vscode-git-6d80ff007e.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1494:16) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'connect',
  address: '/run/user/1002/vscode-git-6d80ff007e.sock'
}
Missing or invalid credentials.
Error: connect ENOENT /run/user/1002/vscode-git-6d80ff007e.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1494:16) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'connect',
  address: '/run/user/1002/vscode-git-6d80ff007e.sock'
}
remote: HTTP Basic: Access denied. The provided password or token is incorrect or your account has 2FA enabled and you must use a personal access token instead of a password. See https://gitlab.ics.muni.cz/help/topics/git/troubleshooting_git#error-on-git-fetch-http-basic-access-denied
fatal: Authentication failed for -remote-name

terminal error output without extensions:
$ git push
remote: HTTP Basic: Access denied. The provided password or token is incorrect or your account has 2FA enabled and you must use a personal access token instead of a password. See https://gitlab.ics.muni.cz/help/topics/git/troubleshooting_git#error-on-git-fetch-http-basic-access-denied
fatal: Authentication failed for -remote-name

installed extentions:
DEVSENSE.composer-php-vscode
DEVSENSE.phptools-vscode
DEVSENSE.profiler-php-vscode
esbenp.prettier-vscode
GitLab.gitlab-workflow
Gruntfuggly.todo-tree
ms-azuretools.vscode-docker
ms-python.black-formatter
ms-python.python
ms-python.vscode-pylance
ms-vscode-remote.remote-ssh
ms-vscode-remote.remote-ssh-edit
ms-vscode.cmake-tools
ms-vscode.cpptools
ms-vscode.cpptools-extension-pack
ms-vscode.cpptools-themes
ms-vscode.remote-explorer
rust-lang.rust-analyzer
twxs.cmake
vadimcn.vscode-lldb
vscodevim.vim
WakaTime.vscode-wakatime
xaver.clang-format
zhuangtongfa.material-theme

**Comment by lszomoru** [comment]
@JiriProkop, am I understanding correctly that you are getting these errors when you try to push your changes using the Terminal? If that is the case, this seems to be an git auth issue and not an issue with VS Code. I would suggest that you visit the troubleshooting link provided in the error message. Thank you!
