### ISSUE TITLE
improvements in autocomplete 

### ISSUE THREAD

**Issue by victorschinaider** [Microsoft/vscode#19304]
- VSCode Version: 1.8.1
- OS Version: Ubuntu 16.04

Steps to Reproduce:
![ezgif com-631dcaef81](https://cloud.githubusercontent.com/assets/16581931/22270561/ef51c04c-e26e-11e6-9c85-2d0d56cea7b1.gif)

I'm using the VSCode to work with Angular 2 and Typescript.
When i'm in the Component decorator definition, i'm getting this strange behavior.
The autocomplete don't work when the vscode Interprets an error in syntax (see the gif), only autcompletes if there is no "error", but wheni think vscode needs to autocomplete when there was an error, to correct it.

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript#13850

**Comment by mjbvz** [comment]
@victorschinaider I'm have trouble reproducing this issue using this code:

```ts
import { Component } from '@angular/core'

@Component({
    selector: 'fdsa',
    s|
    templateUrl: 'ad'
})
export class X {}
```

Trying to autocomplete at the `|`, I see the correct properties.

A few questions to help investigate this:

* Do you have extensions installed? Does this repo when you run code using `--disable-extensions`?
* What does your `tsconfig.json` look like?

**Comment by victorschinaider** [comment]
![](http://im2.ezgif.com/tmp/ezgif.com-d9cf2abd14.gif)

I was able to reproduce.

You need to put template string in the right after property of component.

**Comment by mjbvz** [comment]
Thanks for the follow up. Looks like a ts exception. Reopening Microsoft/TypeScript#13850
