### ISSUE TITLE
install extension output Unexpected token 'I', "INDX( 

### ISSUE THREAD

**Issue by wangzongming** [microsoft/vscode#193089]
Does this issue occur when all extensions are disabled?: Yes/No
Yes

- VS Code Version: 
![image](https://github.com/microsoft/vscode/assets/27466569/472a112f-05f9-4d4a-b2ce-7c779d0044f7)

- OS Version: window 11

Steps to Reproduce:

1.  Install the extension
2. ouput Unexpected token 'I', "INDX( 
![image](https://github.com/microsoft/vscode/assets/27466569/6b21b04e-7184-48e2-a6e4-7a3b7b4e9cec)

I tried to uninstall vs code and reinstall it, but it still didn't work.

Thank you for taking the time to review and solve my problem. 🌹

**Comment by sandy081** [comment]
Can you please open extensions.json file in the extension folder and share the content of that file? You can open the extensions folder using the command `F1 > Open Extensions Folder`

**Comment by wangzongming** [comment]
When I opened it, it was as follows:
![image](https://github.com/microsoft/vscode/assets/27466569/b8633db7-3aba-4986-812c-1ca8501ce1f0)

> Can you please open extensions.json file in the extension folder and share the content of that file? You can open the extensions folder using the command `F1 > Open Extensions Folder`

**Comment by wangzongming** [comment]
I don't know why that happened. I can't remember what I did.

**Comment by sandy081** [comment]
Try deleting this file and restart VS Code?

**Comment by wangzongming** [comment]
> Try deleting this file and restart VS Code?

Thank you. It was like magic.
