### ISSUE TITLE
CLI uses underscore and not dash (`vscode_cli_darwin_x64_cli`)

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#193091]
All our other assets use dashes, such as `vscode-server-darwin-x64`

**Comment by connor4312** [comment]
Our other assets do use underscores as well in the CI pipeline -- are you looking somewhere different?

<img width="516" alt="image" src="https://github.com/microsoft/vscode/assets/2230985/dca0f873-bb88-4cf8-ba14-b4728b87ecfd">

**Comment by bpasero** [comment]
@connor4312 yeah I am looking here: https://builds.code.visualstudio.com/builds/insider

**Comment by connor4312** [comment]
All the builds there are using dashes 🤔 

<img width="380" alt="image" src="https://github.com/microsoft/vscode/assets/2230985/2270dcbd-5e50-46b1-97a7-5fada5787fd8">

**Comment by bpasero** [comment]
Ok then feel free to close, not sure what I was seeing. I think I reported this when I sanity tested during endgame.
