### ISSUE TITLE
VSCode can not work when opened

### ISSUE THREAD

**Issue by kev26** [microsoft/vscode#193067]
I have this problem after updating vs code in Ubuntu Software, tried to uninstall and reinstall but seems the error has not been resolved
Ubuntu: 20.04 LTS
![image](https://github.com/microsoft/vscode/assets/25315610/1d1995e6-f353-4c11-8be7-6639c2258ac3)

**Comment by kevinlaw31** [comment]
Same here

**Comment by kevinlaw31** [comment]
@kev26 ,Check on the following solution. It works for me
[https://github.com/microsoft/vscode/issues/192985](#193037)

**Comment by kev26** [comment]
> @kev26 ,Check on the following solution. It works for me [https://github.com/microsoft/vscode/issues/193037](url)

I don't see anything on that link, please help me update it. thank you

**Comment by kevinlaw31** [comment]
> > @kev26 ,Check on the following solution. It works for me [https://github.com/microsoft/vscode/issues/193037](url)
> 
> I don't see anything on that link, please help me update it. thank you

Try again. Basically you need to delete the GPUCache

**Comment by kev26** [comment]
> > > @kev26 ,Check on the following solution. It works for me [https://github.com/microsoft/vscode/issues/193037](url)
> > 
> > 
> > I don't see anything on that link, please help me update it. thank you
> 
> Try again. Basically you need to delete the GPUCache

Fixed, thank you so much.
