### ISSUE TITLE
im not able to find the explorer in left side of the window

### ISSUE THREAD

**Issue by Ymathkeerti** [microsoft/vscode#193021]
Type: <b>Bug</b>

im not able to find the explorer in left side of the window

VS Code version: Code 1.82.1 (6509174151d557a81c9d0b5f8a5a1e9274db5585, 2023-09-08T08:45:05.575Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz (4 x 2712)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|7.71GB (1.93GB free)|
|Process Argv|--crash-reporter-id da7f9b99-85f5-4fd8-a5d6-c8a0112b6478|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (24)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
compulim-vscode-closetag|Com|1.2.0
vscode-babel-coloring|dza|0.0.4
react-native-react-redux|EQu|2.0.6
prettier-vscode|esb|10.1.0
code-runner|for|0.12.0
html-preview-vscode|geo|0.2.5
vscode-import-formatter|hen|0.1.8
vscode-lebab|jer|1.1.0
tag-inserter|l7s|1.4.0
quickstart|lol|0.1.0
vscode-html-format|moh|0.1.2
html-fmt-vscode|Nik|0.9.3
inline-html|pus|0.3.8
LiveServer|rit|5.7.9
html5-boilerplate|sid|1.1.1
es6-mocha-snippets|spo|0.2.2
react-redux-es6-snippets|tim|2.1.0
es6-string-html|Tob|2.12.1
ES6-extension-pack|wal|1.0.0
HTML5-extension-pack|wal|1.0.0
JavaScriptSnippets|xab|1.8.0
emmet-live|yse|1.0.0
html-css-class-completion|Zig|1.20.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263:30335439
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
py29gd2263:30792226
vscaat:30438848
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
vscccc:30803845
3biah626:30602489
f6dab269:30613381
2i9eh265:30646982
showlangstatbar:30737416
0bi6i642:30835152
03d35959:30757346
pythonfmttext:30731395
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
pythonnosmt12:30797651
pythonidxptcf:30805731
pythonnoceb:30805159
synctok:30821570
dsvsc013:30795093
dsvsc014:30804076
diffeditorv1:30821571
dsvsc015:30829745

```

</details>

**Comment by lramos15** [comment]
`F1 -> Reset View Locations`
