### ISSUE TITLE
How to open a new folder in the Extension Host window with window.openFoldersInNewWindow

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#19301]
Testing https://github.com/Microsoft/vscode/issues/18609

- Set `"window.openFoldersInNewWindow": true`
- Debug an extension
- The extension host window opens. I want to open a different folder, but it only opens in a new window.

Do I have to change that setting to do this or is there a workaround?

**Comment by bpasero** [comment]
@roblourens well, this setting cannot (and should not) be set inside a workspace so best you can do in this case is to change your launch.json to add the path to the folder you want to open as argument. I do not think we should treat the extension host window any different, that would only ask for confusion.

**Comment by roblourens** [comment]
Agreed, and I found a workaround - even with that setting true, I can drag a folder onto the window to open it instead.

**Comment by bpasero** [comment]
@roblourens yeah true, that works.
