### ISSUE TITLE
Microsoft Auth Provider should support overriding Redirection URI

### ISSUE THREAD

**Issue by rahulten** [microsoft/vscode#193006]
The Microsoft Auth Provider in VS Code allows overriding the Client ID and Tenant ID, using the properties VSCODE_CLIENT_ID and VSCODE_TENANT respectively. However, the auth provider requires the Client to be configured with the Redirection URI https://vscode.dev/redirect. If it's not so, then the token acquisition fails with error, such as this one,

AADSTS50011: The redirect URI 'https://vscode.dev/redirect' specified in the request does not match the redirect URIs configured for the application 'cf710c6e-dfcc-4fa8-a093-d47294e44c66'. Make sure the redirect URI sent in the request matches one added to your application in the Azure portal. Navigate to https://aka.ms/redirectUriMismatchError to learn more about how to fix this.

If we're allowing the overriding of Client ID, can we also allow the overriding of Redirection URI for completeness?

**Comment by TylerLeonhardt** [comment]
For this, you can simply add https://vscode.dev/redirect as an additional redirect url to your application and then auth flows in VS Code will just work.
 
Adding such a feature would mean you would need to be responsible for redirecting back to VS Code which is challenging considering there are multiple different locations VS Code could be (VS Code Desktop, VS Code Insiders Desktop, vscode.dev, insiders.vscode.dev, Codespaces, etc)
