### ISSUE TITLE
"window.newWindowDimensions": "inherit" does not inherit fullscreen/zen mode

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#19300]
Test item #18632

- VSCode Version: Code - Insiders 1.9.0-insider (4265f5e35cb3ea8ba7e0cf6b14ec606b6f8647ea, 2017-01-24T10:37:36.620Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: None

Steps to Reproduce:

1. Set "window.newWindowDimensions": "inherit"
2. In fullscreen (or zen) mode, a new window will get default size

**Comment by bpasero** [comment]
Good catch. Note that zen mode is not part of this settings support, but fullscreen should work now.
