### ISSUE TITLE
`code .` stopped working in Windows Terminal

### ISSUE THREAD

**Issue by christianboyle** [microsoft/vscode#193029]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.82.1 (user setup)
- OS Version: Windows_NT x64 10.0.19045

Steps to Reproduce:

1. Open Windows Terminal and run `code .` - notice VSCode doesn't open
2. Open Command Prompt and run `code .` - notice VSCode does open

Like the title states, `code .` stopped working with Windows Terminal after a recent update (last few days). There have been no changes to my PATH (in Ubuntu or Windows) or environment variables.

`code .` still works with Command Prompt (cmd), but when trying it in Windows Terminal it just returns, without error, to the command-line (VSCode never opens).

I tried reinstalling VSCode, but the same behavior persists.

Prior to this `code .` has worked in Windows Terminal (Ubuntu 18.04) for years, without issue.

**Comment by meganrogge** [comment]
works for me - how about you @Tyriar ?

![Recording 2023-09-13 at 10 18 09](https://github.com/microsoft/vscode/assets/29464607/2f4b347b-cf72-4713-a2a4-8a813fb97b3e)

**Comment by gjsjohnmurray** [comment]
Is #192506?

**Comment by christianboyle** [comment]
https://github.com/microsoft/vscode/assets/1605754/c380faeb-680a-4296-bc8e-d5e53165a80d

**Comment by christianboyle** [comment]
@gjsjohnmurray That does sound the same.

**Comment by christianboyle** [comment]
Closing as dupe of https://github.com/microsoft/vscode/issues/192506

**Comment by christianboyle** [comment]
I just confirmed that the prior version (1.80.2) works as expected and 1.81.1 breaks it.

Will wait to see if 1.82.2 fixes it.
