### ISSUE TITLE
Sash variables end up on the HTML element

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#193088]
I would have expected maybe the workbench element if this needs to be global?

![Image](https://github.com/microsoft/vscode/assets/900690/345163aa-9713-4525-bcd5-6ffbeb7bb5bb)

**Comment by joaomoreno** [comment]
Do you know of a good way to grab hold of the workbench dom node, [from a contribution](https://github.com/microsoft/vscode/blob/b2388cebc348cc2ccd74a10e0f7f1d60d3bb356d/src/vs/workbench/contrib/sash/browser/sash.ts#L37-L39)?

**Comment by bpasero** [comment]
@joaomoreno there is `ILayoutService.container`
