### ISSUE TITLE
Cannot install latest VSCode (1.82.1) on Ubuntu 16.04

### ISSUE THREAD

**Issue by benknight-paxton** [microsoft/vscode#193086]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: `code/stable 1.82.1-1694163687 amd64 [upgradable from: 1.81.1-1691620686]`
- OS Version: `Ubuntu 16.04`

Steps to Reproduce:

1. Update VSCode to v1.82.1 on Ubuntu 16.04 (`sudo apt-get install code`)
2. `The following packages have unmet dependencies:
 code : Depends: libnss3 (>= 2:3.30) but 2:3.28.4-0ubuntu0.16.04.14 is to be installed`

Latest libnss3 available for Ubuntu 16.04 is 2:3.28.4 which is lower than the version VSCode requires.

**Comment by sun-xm** [comment]
I've got the same problem. Repro on VSCode 1.82.2.

**Comment by marcofornasini** [comment]
Same problem, same libnss3.

**Comment by deepak1556** [comment]
The dependency comes from the runtime, there is not much we can do here. You can use our tunnels setup as an alternative https://code.visualstudio.com/docs/remote/tunnels

**Comment by benknight-paxton** [comment]
If this is the case you need to update requirements so that Ubuntu 16.04 is no longer listed as supported: https://code.visualstudio.com/docs/supporting/requirements

**Comment by deepak1556** [comment]
Updated in https://github.com/microsoft/vscode-docs/pull/6686

**Comment by benknight-paxton** [comment]
Also may be worth reverting the publishing apt package to the version that is supported so people can't download an unsupported version.
