### ISSUE TITLE
Terminal: Run Recent Command not work for gitBash in windows

### ISSUE THREAD

**Issue by PraneshBalasubramaniam** [microsoft/vscode#193070]
Hi,  
The `Terminal: Run Recent Command` is not working for `gitBash` in windows.

#### VSCode

- Version: `1.82.1`
- Commit: 6509174151d557a81c9d0b5f8a5a1e9274db5585

#### Operating System

- Edition: `Windows 10 Enterprise`
- Version: `22H2`
- OS build: `19045.3393`

#### List of extensions installed

1. Name: [Fluent Icons](https://marketplace.visualstudio.com/items?itemName=miguelsolorio.fluent-icons)  
   Id: `miguelsolorio.fluent-icons`  
   Description: Fluent product icons for Visual Studio Code  
   Version: `0.0.18`  
   Publisher: Miguel Solorio
2. Name: [Material Icon Theme](https://marketplace.visualstudio.com/items?itemName=PKief.material-icon-theme)  
   Id: `PKief.material-icon-theme`  
   Description: Material Design Icons for Visual Studio Code  
   Version: `4.30.1`  
   Publisher: Philipp Kief

> [!NOTE] Tried disabling all extension and checked but still got the issue

#### Steps to Reproduce the issue

1. Open VSCode in windows.
2. Open internal gitBash terminal.
3. execute some command in it.
4. Now open command palette and search `Terminal: Run Recent Command` command and click enter.

#### Expected to see

Recent commands executed in gitBash.

#### Actually saw

The command palette closed and nothing happened.

#### Errors from the Dev Tools Console

I didn't get any error in dev tools console

> [!NOTE] Also, can we add a `feature` to `edit recent terminal commands` instead of just choosing from recent commands.  
> Because sometimes there is a need to edit the command slightly before executing.

**Comment by Tyriar** [comment]
@PraneshBalasubramaniam have you installed shell integration manually for git bash as it's not automatically activated like in other shells https://code.visualstudio.com/docs/terminal/shell-integration#_manual-installation

> [!NOTE] Also, can we add a feature to edit recent terminal commands instead of just choosing from recent commands.
Because sometimes there is a need to edit the command slightly before executing.

I've wanted something similar, can you create a new issue? You can delete some of the entries (those where the source of truth is in vscode), but not shell history files for example:

![image](https://github.com/microsoft/vscode/assets/2193314/62d07400-62a7-4f3f-93ab-4cc363f2b80b)

**Comment by PraneshBalasubramaniam** [comment]
Hi, thanks for the replay,

The `manually shell integration` for git bash worked for me,  
Sorry I didnt notice it in vscode documentation.

As for `edit recent terminal commands` I will create new issue.

I have a doubt about task,  
When running a command using tasks like `npm start` or `npm run dev`, and reload window in VSCode the task ends.
I know it is a duplicate issue, I have gone through those issues but I don't understand what happened to that issue.
Is there any option to enable task to persist after reload. 
It would be so useful as we don't have to restart the task every time we reload VSCode.
Sorry for asking this question here, I just wanted to know whether it is possible.

**Comment by Tyriar** [comment]
Closing off as this was just a matter of enabling shell integration.

@meganrogge can you follow up with @PraneshBalasubramaniam about the task question?

**Comment by PraneshBalasubramaniam** [comment]
Hi, @meganrogge ,
Sorry for asking again , but is there a way to make tasks like `npm start` or `npm run dev` persist after reload .

**Comment by meganrogge** [comment]
Hi @PraneshBalasubramaniam there is not currently. We only persist background tasks that have problem matchers. You can set them to run on folder open though like this:

`	"runOptions": {"runOn": "folderOpen"},`

**Comment by PraneshBalasubramaniam** [comment]
ok, Thanks for the help.
