### ISSUE TITLE
Configuration php.validate.executablePath is not included in exported profile

### ISSUE THREAD

**Issue by BartolomeSintes** [microsoft/vscode#193052]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.82.1
- OS Version: Windows

Steps to Reproduce:
1. My settings.json file includes the following two lines:
  "php.validate.executablePath": "C:/xampp/php/php.exe",
  "php.validate.run": "onType",
3. When I export the profile to a gist or a file, the first setting is lost. If I import the profile, the new settings.json file includes only the second line:
  "php.validate.run": "onType",

Thanking you in advance

**Comment by BartolomeSintes** [comment]
The answer is in the VSCode docs
[Why are some settings not exported when exporting a profile?](https://code.visualstudio.com/docs/editor/profiles#_why-are-some-settings-not-exported-when-exporting-a-profile)
When exporting profiles, machine-specific settings are not included because these setting would not be applicable on another machine. For example, settings that point to local paths are not included.

Anyway, I am not sure if losing a setting is better than having a setting that is not applicable. By the way, machine-specific settings in tasks.json are not lost (please, do not remove them ;-)
Is there any workaround?

**Comment by roblourens** [comment]
> If the setting is present, perhaps it can work in another machine, but if the setting is lost, it can not work, never.

Or maybe it has confusing, unintended or dangerous behavior, since a file with the same path on a different machine isn't necessarily the same file, it may just be at the same path by coincidence. I think this is the right choice, and you'll need to configure machine-specific settings on the new machine
