### ISSUE TITLE
Skip Files not working after initial attempt at stepping into skipped code

### ISSUE THREAD

**Issue by ramya-rao-a** [microsoft/vscode#19308]
Testing #19096

Below are the 2 typescript files in my workspace and my launch.json

![image](https://cloud.githubusercontent.com/assets/16890566/22272737/ddd354ac-e250-11e6-87b0-2492e34784c6.png)

As you can see I have listed `hello.ts` as a skipped file.

Now with the `greetings.ts` as the file in the active editor, I hit F5.
- Breakpoint is hit
- Step in
- Callstack shows `sayHello` and is greyed out
- Step Over

I expect to go to the next line (line 5) in greetings.ts, but every step over actually goes thru each line in the `hello.ts` which was supposed to be skipped.
Call stack shows `sayHello` greyed out but like line numbers incrementing with each step over

**Comment by weinand** [comment]
node-debug does not yet support to skip non-JavaScript source files, e.g. TypeScript.

**Comment by seanpoulter** [comment]
@weinand, this doesn't seem to be working for regular JS in 1.19.1. Is there a relevant use case in the docs I can try for reference?

**Comment by weinand** [comment]
This works now with the new js-debug.
