### ISSUE TITLE
Add a 'wordwise' option for the diff inline view

### ISSUE THREAD

**Issue by bhmarscheck** [microsoft/vscode#193083]
As kind of requested in issue #103285 and visible in the mentioned issues attached image I'd like the option to only display the changed part of the line.

The idear is to not have a read line and a green line underneeth each other but rather a single line where only the parts are highlighted that have acually changed.

Maybe the option could be added to the "More Actions..." drop down menu as "Inline Word View", "Wordwise View" or "Word Diff View"

**Comment by hediet** [comment]
I think this makes sense for the inline view!

I reopened the original issue.

/duplicate https://github.com/microsoft/vscode/issues/103285
