### ISSUE TITLE
Test continue on for PR comments

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#193104]
Refs: https://github.com/microsoft/vscode/issues/183449

- [x] macOS @joaomoreno
- [x] linux @ulugbekna
- [x] windows @bpasero

Complexity: 3

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23193104%0A%0A&assignees=alexr00)

---

When you checkout a PR with GitHub Pull Requests and Issues and write a comment without submitting the comment, we now save these unsubmitted comments for "continue on".

Setup:
You will need two machines that you can install desktop VS Code insiders on. **vscode.dev can't be used to test this.**
NOTE: **Make sure you have the same version of VS Code and GitHub Pull Requests and Issues on both machines**
Install the GitHub Pull Requests and Issues extension on both machines.
Install the GitHub Repositories extension on both machines.
Turn on "Cloud changes" from the Account menu on both machines.

To verify:
1. Check out a PR on machine one using the GitHub Repositories + Remote Repositories extension. 
   a. Run the command: "Remote Repositories: Open Remote Repository..."
   b. Choose the option to "Open a Pull Request from GitHub"
   c. Find your PR in the list and choose it
2. On machine two, check out the same PR with the GitHub Repositories extension.
3. Back to machine one: Start to write a comment. Do not submit the comment.
4. On machine one, make a small edit in a file. (@joyceerhl, this seems to be needed for the "Store working changes in cloud" command)
5. On machine one, Command: "Cloud Changes: Store Working Changes in Cloud"
7. On machine two, open the file that you were leaving a comment in on machine one in step two.
8. On machine two, "Cloud Changes: Resume Latest Changes from Cloud"
9. Verify that the comment from machine one now shows on machine two

Once you have this working some other good things to test (**Each time you test you will need to close the old comment, make a new comment, and make a new small edit**):
- Does the sync still work if the file is closed at the time that you "Resume"?
- Does "Resuming" an unsubmitted reply to a submitted comment work?
- Does "Resuming" multiple unsubmitted comments work?

**Comment by bpasero** [comment]
@alexr00 that did not work for me at least on macOS. I had tried with https://insiders.vscode.dev/github/microsoft/vscode/pull/191241 having previously added a comment from desktop. Is there a way to figure out?

**Comment by ulugbekna** [comment]
Didn't work for me either. 
I checked out a PR on insiders.vscode.dev, started typing in a comment, but didn't submit. 
Opened insiders desktop, checked out same PR - no comments

**Comment by alexr00** [comment]
Looks like I have some missing steps. In the setup:

> Turn on "Cloud changes" from the Account menu

And steps 3, 4, and 7.

**Comment by alexr00** [comment]
There's still an issue with this feature. This TPI is currently blocked.

**Comment by chrmarti** [comment]
Trying on mac without luck:

Desktop:
<img width="780" alt="image" src="https://github.com/microsoft/vscode/assets/9205389/856c4216-5f2f-4758-b15f-eeb7380b6fbf">

insiders.vscode.dev:
<img width="420" alt="image" src="https://github.com/microsoft/vscode/assets/9205389/995ab12a-0e74-4d85-89f7-7a4369e3d7b1">

Both are on today's Insiders build and the latest PR extension pre-release from yesterday.

**Comment by ulugbekna** [comment]
Works when testing with insiders open in two tabs

**Comment by alexr00** [comment]
@bpasero and @anthonykim1 could you please test by opening a PR in insiders.vscode.dev in two different browser tabs instead of 1 insiders.vscode.dev instance and one VS Code desktop instance?

**Comment by bpasero** [comment]
It also does not work for me between 2 browser tabs (the change restores, but not the comment). I suggest to move this feature and testing into October.

**Comment by alexr00** [comment]
Moving to October so we can figure out the URI mismatch.

**Comment by anthonykim1** [comment]
Let me know @alexr00  if you still wanted me to test this

**Comment by alexr00** [comment]
For now, no further testing is needed. We'll test again during the October endgame.

**Comment by ulugbekna** [comment]
It still doesn't work for me, sorry :-(

**Comment by anthonykim1** [comment]
I tried multiple times trying to get this work, but still having some trouble. Tried to use more of the "store in cloud" and the "show cloud changes" but can't seem to see the comments even after actually submitting the comments from different device.
<img width="1026" alt="Screenshot 2023-10-24 at 3 24 26 PM" src="https://github.com/microsoft/vscode/assets/62267334/5daa8297-0181-4169-b92f-4877869929a9">

**Comment by joaomoreno** [comment]
Following the steps very closely actually works. But the entire flow feels flimsy.

- I kinda expected this to just work in regular checked out repos, not only using Remote Repositories.
- I also kinda expected it to just work without the `Store` and `Resume` commands
- Do we already have an issue for _this seems to be needed for the "Store working changes in cloud" command_?
- Is there any way to test this as it's intended for users to use it, not via all these steps?

**Comment by bpasero** [comment]
This worked only once for me and the things I have to remember to test this are incredibly complex: why do I have to make an edit, why do I have to run a command to sync, why does this not happen automatically? Think about settings sync: it just works.

@alexr00 @joyceerhl I would suggest you two sit together, test the flow end to end, improve the user experience and then we test this again.

**Comment by alexr00** [comment]
Thank you everyone for your persistence in testing this!
