### ISSUE TITLE
Extensions profiles 

### ISSUE THREAD

**Issue by Bakaji** [microsoft/vscode#193141]
**_I'm not expert in development neither I seen the source code of vscode_**, this is my first time suggesting a feature... but I think it will be awesome if my suggestion was implemented

### Problem

my extensions list was very crowded and Impact the performance of vscode since I'm a junior full-stack web developer, extensions for html, css, js, c# and python...themes... linting... etc.

### Solution
organize extensions in profiles, user can create a profile and select some extensions that will be activated if this profile is selected, profiles are user defined and synchronized using user GitHub accounts with other settings, then for when a workspace is started he can select a extension profile
**this can improve performance of vscode**

### Examples

**frontend profile** : contains only frontend related extensions, no c# or ocaml extensions
**api profile** : contains only api development related extensions no css or bootstrap extensions

### implementation scenario

1. user create, edit, delete multiple profiles 
2. user add / remove extensions from a profile
3. user select a profile to run with workspace (in workspace settings)
4. user reload window to activate profile

**Comment by gjsjohnmurray** [comment]
Have you reviewed what already exists?

https://code.visualstudio.com/docs/editor/profiles
