### ISSUE TITLE
Links in "Select branch/tag" menu always point to upstream

### ISSUE THREAD

**Issue by jakoch** [microsoft/vscode#193182]
Type: <b>Bug</b>

Steps to reproduce:
1. you need a git repo with origin (your fork) and upstream (the project you forked). now you have: origin/main and upstream/main
2. on the VSCode statusbar click "Select Branch/Tag...", so that the menu with "Select branch or tag for checkout..." opens
3. This menu contains additional links for "origin/main" and "upstream/main" entries:
the first icon is Github - "Open on Github"
the second icon is World - "Checkout on vscode.dev"

Issue:
When you click the "Open on Github" icon for the `origin/main` repo
it will open the repository website for `upstream/main` = URL `https://github.com/hikogui/hikogui/tree/main`.
This is also true for all other branches.
In other words: all links point to the webpage of the parent repo `upstream/main`. You can not open webpages for branches like `origin/my-fix`. This results in 404, because it tries to open the webpage for branch `my-fix` on `upstream`, which exists only on the child repo.

Output of `git remove -v`:
```
origin  https://github.com/jakoch/hikogui.git (fetch)
origin  https://github.com/jakoch/hikogui.git (push)
upstream        https://github.com/hikogui/hikogui.git (fetch)
upstream        https://github.com/hikogui/hikogui.git (push)
```

Expected:
When clicking "Open on Github" for `origin/main` the webpage for the origin repo should open.
When clicking "Open on Github" for `upstream/main` the webpage for the upstream repo should open.

![Screenshot 2023-09-15 101719](https://github.com/microsoft/vscode/assets/85608/28ff6d4a-6f90-4eac-a910-e92b66c0231c)

VS Code version: Code 1.82.2 (abd2f3db4bdb28f9e95536dfa84d8479f1eb312d, 2023-09-14T05:55:25.390Z)
OS version: Windows_NT x64 10.0.19045
Modes:

**Comment by gjsjohnmurray** [comment]
I see the opposite behaviour. I forked https://github.com/microsoft/vscode-extension-samples and cloned my fork locally, then opened the folder in VS Code. In the branch quickpick I typed `main` and was offered `main`, `origin/main` and `upstream/main`. The GH buttons on the latter two both take me to my fork in a browser (i.e. origin/main).

Here's my `git remote -v` info:
```
origin  https://github.com/gjsjohnmurray/vscode-extension-samples.git (fetch)
origin  https://github.com/gjsjohnmurray/vscode-extension-samples.git (push)
upstream        https://github.com/microsoft/vscode-extension-samples.git (fetch)
upstream        https://github.com/microsoft/vscode-extension-samples.git (push)
```

**Comment by lszomoru** [comment]
I am able to reproduce the issue using a fork of https://github.com/joaomoreno/gifcap. 
@joyceerhl , could you please take a look? Thanks!
