### ISSUE TITLE
VSCode broken on wayland

### ISSUE THREAD

**Issue by SkyLissh** [microsoft/vscode#193165]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.82.2
- OS Version: Fedora 38 - Linux Kernel 6.4.15

Steps to Reproduce:

1.  Login to the desktop with a Wayland session
2. Run vscode from the terminal with flags --enable-features=UseOzonePlatform and --ozone-platform wayland

Edit: I tried previous versions of vscode, and seems that the problem starts from 1.82.0 to the latest

![image](https://github.com/microsoft/vscode/assets/72633267/2bcfee38-474c-4e0c-b71c-b1d495fcc1b1)

**Comment by gjsjohnmurray** [comment]
Is https://github.com/microsoft/vscode/issues/193096#issuecomment-1719977876 relevant?

**Comment by SkyLissh** [comment]
> Is [#193096 (comment)](https://github.com/microsoft/vscode/issues/193096#issuecomment-1719977876) relevant?

Yes deleting the items of the folder "~/.config/Code/GPUCached" worked for me, thank you
