### ISSUE TITLE
unable to select popup window while debugging

### ISSUE THREAD

**Issue by ocie** [microsoft/vscode#193149]
Type: <b>Bug</b>

set a breakpoint
start debugging
wait to hit the breakpoint
edit the code to introduce a problem (prettier, etc.)
hover over the problem code

expected results: I should be able to select the suggestion (quick fix) from the popup window.

actual results: The popup disappears when I try to move towards it.

workaround: I have to stop the debugging session before I can select the quick fix.

VS Code version: Code 1.82.2 (Universal) (abd2f3db4bdb28f9e95536dfa84d8479f1eb312d, 2023-09-14T05:59:47.790Z)
OS version: Darwin arm64 22.6.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M2 Pro (12 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|3, 2, 2|
|Memory (System)|32.00GB (0.68GB free)|
|Process Argv|--crash-reporter-id e2e14547-12af-412e-946f-d92aa5c7b542|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|2.4.2
gitlens|eam|14.3.0
copilot|Git|1.111.404
python|ms-|2023.16.0
vscode-pylance|ms-|2023.9.10
powershell|ms-|2023.6.0
vscode-jest|Ort|5.2.3
vscode-twoslash-queries|Ort|1.2.2

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
vsccc:30803844
282f8724:30602487
f6dab269:30613381
a9j8j154:30646983
showlangstatbar:30737416
0bi6i642:30835152
03d35959:30757346
pythonfmttext:30731395
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
pythonnosmt12:30797651
pythonidxptcf:30805731
pythonnoceb:30805159
asynctok:30821568
dsvsc013:30795093
dsvsc014:30804076
diffeditorv2:30821572
dsvsc015cf:30829746

```

</details>

**Comment by roblourens** [comment]
Can you share a screenrecording or image? I fixed a similar-sounding bug several months ago, I can't repro an issue now, but it's possible that you've hit a certain case with how the error is layed out that still breaks.

**Comment by ocie** [comment]
I hope this screen capture file isn't too big.

https://github.com/microsoft/vscode/assets/4504240/d5a1b69f-6e9e-4b68-b817-6b10d20d7814

I sometimes find it hard to navigate to the "quick fix" even without the debugger.  If I start moving the mouse diagonally towards the "quick fix", the window disappears before I get there.

**Comment by ocie** [comment]
https://github.com/microsoft/vscode/assets/4504240/a9149570-269c-4be5-bfc4-4910d0018be4

This is an example without the debugger running.  I'm not sure if it is a related problem or not.

**Comment by roblourens** [comment]
Any different if you start vscode with extensions disabled? `--disable-extensions` or the command "Reload with extensions disabled"

**Comment by ocie** [comment]
I saw the same behavior with the extensions disabled.

**Comment by roblourens** [comment]
Ok. I can't repro this but I'll watch out for it. Would be helpful if you notice any other patterns, like if there are some errors/files/languages where it happens, but not others, etc.

**Comment by ocie** [comment]
I primarily use typescript.  I notice the same thing in python.

https://github.com/microsoft/vscode/assets/4504240/cde1b616-7a7d-452d-bd41-eb3b7b91b9b4

**Comment by ocie** [comment]
I thought there might be some interaction with the "bettertouchtool" extension I have on the mac.  I still see the problem with this extension disabled.

**Comment by quirm** [comment]
@ocie I experienced the same problem after an update. It turned out that the "Editor > Hover: Sticky" settings got disabled, once checked it works again as expected.

**Comment by connor4312** [comment]
This appears to duplicate https://github.com/microsoft/vscode/issues/182213
