### ISSUE TITLE
Kill terminal does not hide it, so open terminal does not work (using hotkeys)

### ISSUE THREAD

**Issue by mstv** [microsoft/vscode#193109]
Steps to Reproduce:

My workaround for the not released #183419 is to kill the terminal and to reopen it using hotkeys.
1. Open a terminal
2. Kill the terminal using an assigned hotkey
--> The terminal text disappears, but the terminal pane is not hidden.
3. Open a terminal using an assigned hotkey
--> nothing happens

mouse-only workarounds:
a) close the terminal using the `X` button
b) open a terminal using the `+` button

Does this issue occur when all extensions are disabled?: N/A It worked in the previous version 1.81.1 with these standard extensions.
I am not allowed to install insider's on that machine.

Version: 1.82.1 (system setup)
Commit: 6509174151d557a81c9d0b5f8a5a1e9274db5585
Date: 2023-09-08T08:45:05.575Z
Electron: 25.8.0
ElectronBuildId: 23503258
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.19045

<html>
<body>

Screen Reader | no
VM | 0%

</body>
</html>

<html>
<body>
<div class="block block-extensions" style="box-sizing: border-box; font-size: 12px; color: rgb(97, 97, 97); font-family: &quot;Segoe WPC&quot;, &quot;Segoe UI&quot;, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><div class="block-info" id="systemInfo" style="box-sizing: border-box; background-color: rgb(255, 255, 255); color: rgb(97, 97, 97); width: 581.391px; font-size: 12px; overflow: auto; overflow-wrap: break-word; margin: 5px 5px 1.5em; padding: 10px;">

Extension | Author (truncated) | Version
-- | -- | --
python | ms- | 2023.16.0
vscode-pylance | ms- | 2023.9.10
cpptools | ms- | 1.17.5
cpptools-extension-pack | ms- | 1.3.0

(1 theme extensions excluded)</div></div><div class="block block-experiments" style="box-sizing: border-box; font-size: 12px; color: rgb(97, 97, 97); font-family: &quot;Segoe WPC&quot;, &quot;Segoe UI&quot;, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><input checked="" id="includeExperiments" type="checkbox" aria-label="Include A/B experiment info" class="sendData" style="box-sizing: border-box; font-family: inherit; border: none; margin-top: 0px; background-color: rgb(60, 60, 60); color: rgb(204, 204, 204); width: auto; display: inline-block; vertical-align: middle; cursor: pointer;"><span> </span><label class="caption" style="box-sizing: border-box; user-select: none;">Include A/B experiment info (<a class="showInfo" href="vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-sandbox/issue/issueReporter.html#" style="box-sizing: border-box; cursor: pointer; border: 1px solid transparent; color: rgb(0, 106, 177); text-decoration: none;">hide</a>)</label><pre class="block-info" style="box-sizing: border-box; background-color: rgb(255, 255, 255); color: rgb(97, 97, 97); width: 581.391px; font-size: 12px; overflow: auto; overflow-wrap: break-word; margin: 5px; padding: 10px;">No current experiments.</pre></div>
</body>
</html>

**Comment by DonMiller9294** [comment]
You might have to report this issue to Visual code studio  or delete and reinstall everything.

**Comment by mstv** [comment]
They shortcuts work in 1.82.2 again.
Thank you!
