### ISSUE TITLE
[Testing]: Get selected default Run/Debug TestProfile(s)

### ISSUE THREAD

**Issue by mxschmitt** [microsoft/vscode#193160]
Is it possible to get the currently selected default run profile(s)? In this case the first and last.

We tried [RunProfile.isDefault](https://code.visualstudio.com/api/references/vscode-api#TestRunProfile), but thats not getting the needed updates from the user when he selects/de-selects.

![image](https://github.com/microsoft/vscode/assets/17984549/2a3d5867-d6c5-4500-822a-a764934b6e98)

Thanks!

**Comment by connor4312** [comment]
I propose the following additional APIs:

```ts
	export namespace tests {
		/**
		 * The list of {@link TestRunProfile} the user has selected as their default
		 * profiles when running tests.
		 */
		// implementors's note: for a given extension, this shows only the
		// TestRunProfiles that extension has created
		export let activeTestRunProfiles: readonly TestRunProfile[];

		/**
		 * Fired when a user has changed their default test run profiles. The
		 * new value is also reflected in {@link activeTestRunProfiles}.
		 */
		export const onDidChangeActiveTestRunProfiles: Event<readonly TestRunProfile[]>;
	}
```

**Comment by jrieken** [comment]
Sync-Feedback

* have `TestRunProfile.isSelected`
* have `TestRunProfile#onDidSelect`

**Comment by connor4312** [comment]
Updated API, will be available to try out in the next Insiders:

```
declare module 'vscode' {
	export interface TestRunProfile {
		/**
		 * Whether this profile is currently selected as a default by the user
		 */
		readonly isSelected: boolean;

		/**
		 * Fired when a user has changed whether this is a selected profile. The
		 * event contains the new value of {@link isSelected}
		 */
		onDidChangeSelected: Event<boolean>;
	}
}
```

@mxschmitt please [try it out](https://code.visualstudio.com/api/advanced-topics/using-proposed-api) and let us know if it works for you!

**Comment by mxschmitt** [comment]
I tried it out and it works for us!

(We just check then if isSelected is true rather than attaching to the event listener.)

**Comment by jrieken** [comment]
@connor4312 is this only about the _default_ run profile or generally when selecting a profile w/o running it?

**Comment by connor4312** [comment]
This is about the profile the user has selected as their chosen profile to be used when clicking the "run" or "debug" buttons.

**Comment by connor4312** [comment]
Also, got in-person confirmation last week from @mxschmitt that this API is good for playwright :)

**Comment by jrieken** [comment]
So, I need to go through "Select Default", right? I am confident this API is working but I wonder if the name and/or commend should be refine to express that this is only about the default

<img width="849" alt="Screenshot 2023-12-19 at 09 25 54" src="https://github.com/microsoft/vscode/assets/1794099/280a8458-f870-49ae-ac44-bb2619775f6d">

**Comment by connor4312** [comment]
Yea, that's right. The confusing thing is that we already has an extension-definable `isDefault` property on the profile to control whether, if a user has not manually selected profiles before, that one is the default.

One kind of clever thing we could do, though it's questionably breaking, is to have `isDefault` start being a managed property, set it when the user selection updates, and update the selection when it's updated, rather than introducing a new property...

**Comment by jrieken** [comment]
I like that

**Comment by connor4312** [comment]
So in that case I would revise this proposal with only the additional property in the .d.ts, along with docs changes:

```ts
declare module 'vscode' {
	export interface TestRunProfile {
		/**
		 * Fired when a user has changed whether this is a default profile. The
		 * event contains the new value of {@link isDefault}
		 */
		onDidChangeDefault: Event<boolean>;
	}
}
```
