### ISSUE TITLE
Creating split terminals with `TerminalProfileProvider` and `ExtensionTerminalProfile`

### ISSUE THREAD

**Issue by trond-snekvik** [microsoft/vscode#193183]
When the user starts an extension defined terminal through the "Split Terminal" submenu of "New Terminal", the new terminal is always created in a new terminal tab, instead of a split.

When the user opens a terminal through this menu, VS Code should override the `location` field of the new terminal profile to make it  split, as the user requested.

**Comment by Tyriar** [comment]
@trond-snekvik is this not what you're seeing or am I doing something wrong?

![Recording 2023-09-18 at 08 14 01](https://github.com/microsoft/vscode/assets/2193314/7bd18610-4cbd-4031-bbd9-053fa5a485f6)

**Comment by trond-snekvik** [comment]
Only when the custom terminal profile is created with `TerminalOptions`. 
I have a terminal profile that is created with `ExtensionTerminalProfile`, that looks like this:

https://github.com/microsoft/vscode/assets/7857838/7c332031-c4a3-4879-87a8-56e80e1992f3

This terminal profile is created like this:
```ts
    vscode.window.registerTerminalProfileProvider('nrf-terminal.serial', {
        provideTerminalProfile: () =>
            new vscode.TerminalProfile({
                name: 'DevKit (VCOM0)',
                // pty makes this a ExtensionTerminalOptions object:
                pty: {
                    open() {
                        // ...
                    },
                    close() {
                        // ...
                    },
                    onDidWrite: new vscode.EventEmitter<string>().event,
                },
            }),
    });
```
