### ISSUE TITLE
Document links not very high contrast in high contrast mode

### ISSUE THREAD

**Issue by mousetraps** [Microsoft/vscode#19311]
Testing #19089 

![image](https://cloud.githubusercontent.com/assets/762848/22272911/1271616c-e252-11e6-91b2-0892cb0f677b.png)

**Comment by mjbvz** [comment]
This does not seem to be markdown specific. I see the same styling in other document types as well

**Comment by mjbvz** [comment]
Detected links are now cyan:

<img width="232" alt="screen shot 2017-01-24 at 10 44 21 pm" src="https://cloud.githubusercontent.com/assets/12821956/22280581/aa25b86c-e286-11e6-8883-2ffee475f6af.png">
