### ISSUE TITLE
disable launch of VScode when installing with /verysilent

### ISSUE THREAD

**Issue by udayankumar** [Microsoft/vscode#19319]
I am performing an unattended install of VS code on windows server 2016 using a PowerShell script which continues to install other tools that are dependent on VS code. The relevant script to install VS code is  

`Start-Process ".\VSCode.exe" -ArgumentList "/verysilent /norestart" -wait`

This command installs VS code in silent mode, however, it launch VS code after installation is complete, hence my script, which is waiting for the installation to complete, continues to wait and cannot proceed to install other tools depended on vs code. 

Launching the VS code after installation in an interactive install is a great idea, however, it should be disabled in the silent install. 

My setup:
- VSCode Version: 1.8.1
- OS Version: Windows Server 2016

**Comment by joaomoreno** [comment]
Have you tried `/silent`?

**Comment by daviwil** [comment]
`/mergetasks=!runcode` works great, I use it in an installation script.

**Comment by udayankumar** [comment]
Yes. Confirmed that /mergetasks=!runcode works

By itself /silent still launches the editor



On Jan 25, 2017 11:42 AM, "David Wilson" <notifications@github.com> wrote:

/mergetasks=!runcode works great, I use it in an installation script.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/Microsoft/vscode/issues/19319#issuecomment-275178368>,
or mute the thread
