### ISSUE TITLE
Restarting after changing the display language doesn't restart

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#193184]
1. Install a language pack
2. Change the display language
3. Get a modal dialog saying you have to restart
4. Choose the restart button.
5. VS Code closes, but doesn't reopen. It must be manually started. 

This is on Windows with a system install.

**Comment by TylerLeonhardt** [comment]
I'm just calling the `NativeHostService::restart()` of whatever that abstraction is the restart vscode.

I'm gonna hand this off to maybe @bpasero for electron advice... but I wonder if it'll be good to know if:
* there's a lingering process preventing the full restart
* if a vscode update works fine
* if change a setting that requires restart works fine

**Comment by deepak1556** [comment]
@alexr00 if you have log level set for an extension, ex: `--log github.vscode-pull-request-github:debug` in command args, remove them and it should address the issue.

Merging to https://github.com/microsoft/vscode/issues/188769

**Comment by alexr00** [comment]
The log level is more important to me than the restart so I'll just live with the bug for now.
