### ISSUE TITLE
Edit sidebars layout

### ISSUE THREAD

**Issue by Ardianii1** [microsoft/vscode#193154]
Hello, I want to change the layout of sidebars for example I want to set the secondary Side bar next to primary Side bar or somewhere else like on top  for GitHub Copilot chat , I want it to be more flexible to move around .

**Comment by gjsjohnmurray** [comment]
See also #142742

**Comment by sbatten** [comment]
You can move views and containers via drag and drop and you can swap the side bar positions, but setting them next to each other is out of scope. You can alternatively use the panel position (left/right) to get something similar.
