### ISSUE TITLE
Update Request for tmLanguage.json to the latest vscode-css update

### ISSUE THREAD

**Issue by FifthTundraG** [microsoft/vscode#193196]
Updates to the microsoft/vscode-css repo, namely support for `container`, `container-name`, `container-type`, and `auto-fill` & `auto-fit` for the `repeat()` function, warrant an update to the tmLanguage.json file to include these changes.

I apologize if this was not the correct way of requesting this, as "update request" in tmLanguage.json was quite vague.

**Comment by alexr00** [comment]
This is a fine way to request an update. Update is here: https://github.com/microsoft/vscode/pull/193333
