### ISSUE TITLE
Source Control Repositories window pane does not support scroll, and gets too tall

### ISSUE THREAD

**Issue by erikschul** [microsoft/vscode#193245]
When working with many repositories, the "Source Control Repositories" window pane gets too tall, and occupies too much space:

<img width="557" alt="image" src="https://github.com/gitkraken/vscode-gitlens/assets/128804597/a8e602f5-d79d-45c7-98b4-0261946bd768">

It should be height-adjustable, and scrollable.

### VS Code Version

Version: 1.81.1

**Comment by gjsjohnmurray** [comment]
Is the `scm.repositories.visible` setting of any use to you?

**Comment by erikschul** [comment]
Beautiful, thank you!
