### ISSUE TITLE
yarn typescript monorepo fails to find references across folders

### ISSUE THREAD

**Issue by runfaj** [microsoft/vscode#193241]
Type: <b>Bug</b>

Hi there - I've been running into an issue that has wracked my brain for many hours and no solutions after scanning hundreds of articles/issues/etc. I've narrowed it down to something wrong with vscode, but not exactly sure what to look at further.

I have setup this monorepo: https://github.com/runfaj/monorepo-issue. The issue is relatively simple to explain. After setting this up, if you go to the services/db-service/routes/v1/user/index.ts file, vscode will show no issues. If you comment out one or both of the imports from "shared-xxxx", you'll see the correct red underline. However, if you try to right click to fix imports, vscode can't find those. Manually typing will never bring up the suggestions for those either. When you first opened the file, it was clear they are exported and all references are correct, but vscode can't seem to find them for the suggestions/auto imports.

Where does it work? Webstorm
Where doesn't it work? Vscode on any platform. I've tried on an M1 mac, intel mac, and windows 11 with ubuntu wsl2 and all of them have the same issue.

Here's just a handful of things I've tried to no avail:
- A fresh install of vscode with no additional extensions (other than the bare minimum)
- Several of the vscode monorepo extensions.
- Every possible typescript setting in vscode available that even remotely looked like it could deal with auto imports
- Changing every setting in the tsconfig files related to references, paths, modules, targets, declarations, etc
- Structuring the repo to use single level folders (instead of the nested apps/services/packages ones in the example)
- Adding different yarn workspace and package.json naming formats
- Different patterns of package imports for the workspace folders with different aliases, version numbers, etc.
- Probably a dozen other things that aren't coming to mind because this has now broken my brain

I'm at a loss at what else to try. I'm happy to try whatever you recommend, but at this point I'm thinking it is just a vscode bug.

VS Code version: Code 1.82.2 (abd2f3db4bdb28f9e95536dfa84d8479f1eb312d, 2023-09-14T05:55:25.390Z)
OS version: Windows_NT x64 10.0.22631
Modes:
Remote OS version: Linux x64 5.10.102.1-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2808)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.89GB (11.09GB free)|
|Process Argv|--crash-reporter-id 10d747f9-1beb-40be-859f-a1379ddf2d04|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 5.10.102.1-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2807)|
|Memory (System)|17.57GB (15.16GB free)|
|VM|0%|
</details><details><summary>Extensions (32)</summary>

Extension|Author (truncated)|Version
---|---|---
remote-containers|ms-|0.309.0
remote-ssh|ms-|0.106.4
remote-ssh-edit|ms-|0.86.0
remote-wsl|ms-|0.81.3
vscode-remote-extensionpack|ms-|0.24.0
atom-keybindings|ms-|3.3.0
remote-explorer|ms-|0.4.1
remote-server|ms-|1.4.3
reopenclosedtab|uyi|1.1.0
material-theme|zhu|3.16.0
vscode-zipfs|arc|3.0.0
vscode-better-align|cho|1.4.2
npm-intellisense|chr|1.4.4
path-intellisense|chr|2.8.4
vscode-css-modules|cli|0.5.1
jison-syntax-highlight|cru|0.1.1
vscode-eslint|dba|2.4.2
githistory|don|0.6.20
gitlens|eam|14.3.0
vscode-npm-script|eg2|0.3.29
vscode-search-open-all-results|fab|1.0.3
vscode-pull-request-github|Git|0.72.0
vscode-duplicate|mrm|1.2.1
vscode-docker|ms-|1.26.0
atom-keybindings|ms-|3.3.0
vsliveshare|ms-|1.0.5883
color-highlight|nau|2.5.0
gremlins|nho|0.26.0
vscode-stylelint|sty|1.2.4
reopenclosedtab|uyi|1.1.0
vscode-fold-level|vik|0.0.14
vscode-svg-previewer|vit|0.7.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263:30335439
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
py29gd2263cf:30792227
vscaac:30438847
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
vscccc:30803845
2e4cg342:30602488
f6dab269:30613381
2i9eh265:30646982
showlangstatbar:30737416
0bi6i642:30835152
a2ce3375:30757347
pythonfmttext:30731395
9b8hh234:30694863
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
pythonnosmt12:30797651
pythonidxpt:30805730
pythonnoceb:30805159
dsvsc013:30795093
dsvsc014:30804076
diffeditorv2:30821572
dsvsc015:30829745

```

</details>

**Comment by IllusionMH** [comment]
Webstorm does a lot of things it their own way.

VS Code uses TS and you need proper configuration to make TS work with all packages in monorepo.
See example from https://github.com/RyanCavanaugh/learn-a
