### ISSUE TITLE
Find In Files stalls in folder with 40000+ files, doesn't show results unless cancelled

### ISSUE THREAD

**Issue by garychapman** [Microsoft/vscode#19321]
- VSCode Version: 1.8.1
- OS Version: Windows 10 Pro Version 1511

I am working on a folder containing a fork of a large Meteor.js project (https://github.com/RocketChat/Rocket.Chat) that contains 40000+ files.

When I first open VS Code, Find In Files works as expected: the blue SEARCH progress bar moves from left to right, search results appear as they are found, and the search ultimately concludes.

However, after several searches, the operation stalls when the progress bar is at about 90%,  and results don't appear until the search is cancelled. Even then, usually only a single result is shown.

I then need to close and restart VS Code for Find In Files to work again.

This doesn't seem to happen when working on folders with fewer (e.g. 5000) files

**Comment by roblourens** [comment]
This looks like #17718. Can you grab the Insider's build and see if it works there? Would really appreciate it. Or get 1.9 next week.

**Comment by garychapman** [comment]
Insiders build seems to fix it. Thanks @roblourens and sorry for the duplicate report - I searched existing issues, but it was a bit like a needle in a haystack.

**Comment by roblourens** [comment]
Glad to hear it! No worries, finding related issues from a pile of 20,000 is not easy.
