### ISSUE TITLE
notebook scrolls up incorrectly when adjusting output heights

### ISSUE THREAD

**Issue by amunger** [microsoft/vscode#193231]
1. create a notebook that has several cells, and put this code in the second to last cell

```
import time
time.sleep(2)
for i in range(18):
    print(i)
print('end of output')
```

2. execute the cell so that it has output, and shrink the window so that the single cell+output takes up the whole scrollable region
3. execute the cell again with shift+enter

:bug: the notebook ends up scrolling up, instead of showing the full output and next cell.

![Recording 2023-09-15 at 11 31 00](https://github.com/microsoft/vscode/assets/2019016/bbad3cdf-0ecf-4acb-b63a-7b2be2b8f576)

**Comment by amunger** [comment]
The current behavior of the list view is to use the second visible element as an anchor which can cause some strange behavior. 

In this scenario: 
1. The next cell is focused and revealed, making that cell the anchor as second visible, since the executing cell takes up the rest of the visible region.
2. The output is removed, moving more elements into view from above
3. Output is added and the initial anchor is no longer the second element, so it is scrolled out of view

I'll try to play around with some options, but my initial thought would be to use the executing cell as the anchor. The output could expand and push the next cell out of view, but typing in that cell will bring it back into view.

cc @joaomoreno

**Comment by amunger** [comment]
I actually don't know what causes the initial scroll-up when the output is removed. When debugging, the element shrinks and pulls more cells down before any call to `_rerender` or `setScrollTop` from what I can tell.

It only happens when the executing output is the first element though, which made me suspect `listView_rerender` with the comment about anchoring the second element

**Comment by joaomoreno** [comment]
I really can't seem to repro this, my notebook stays pretty stable as the cell shrinks and grows:

https://github.com/microsoft/vscode/assets/22350/76546d45-616f-4c30-89a6-a271faa83575

**Comment by joaomoreno** [comment]
@amunger I believe you have `editor.scrollBeyondLastLine` disabled, am I correct? Can you reproduce this flipping that setting back to the default value of `true`?

**Comment by amunger** [comment]
It repro's with or without `editor.scrollBeyondLastLine` - you just need to scroll down enough so that the resized cell is only partially visible.

The strange behavior is due to the notebook cell list setting different anchors depending on whether the element top is above the render top. https://github.com/microsoft/vscode/blob/main/src/vs/workbench/contrib/notebook/browser/view/notebookCellList.ts#L1219C2-L1219C2

**Comment by joaomoreno** [comment]
As I looked into the remaining open issues https://github.com/microsoft/vscode/pull/193530, https://github.com/microsoft/vscode/issues/193835 and PR https://github.com/microsoft/vscode/pull/193530, I was trying to grasp what the issue really is, what has been actually fixed and what's left to fix.

Then, I pulled latest and ran out of sources and this is even worse than my last recording:

https://github.com/microsoft/vscode/assets/22350/d2628127-ffac-4c5a-9ece-5543dd275831

Did https://github.com/microsoft/vscode/pull/193833 just break this even more?

@amunger I suggest pausing, simplifying the problem, narrowing in on a solution and possibly merging this only in debt week so as to not cause regressions during this endgame week.

**Comment by rebornix** [comment]
@joaomoreno thanks for the testing, the two recordings you posted above were using different execution commands so I want to ensure we refer to the same behavior:

* in https://github.com/microsoft/vscode/issues/193231#issuecomment-1731171343, it's re-executing the active cell (ctrl+enter), which should always stay visually stable. I think it still works this way out from source
* in the latest https://github.com/microsoft/vscode/issues/193231#issuecomment-1733046390, from what I saw, it's running shift+enter: run cell and move to next
  * This command moves focus to the next cell, so the `def sum` cell is now the focused cell
  * Then the output of the previous cell (which is no longer focused) starts to grow
  * The change introduced via @amunger 's last PR was to ensure that the focused cell stay visually stable, once they are revealed into view

@joaomoreno can you confirm if this is what you are seeing?

**Comment by rebornix** [comment]
I captured a recording for what probably @joaomoreno was comparing, right side is Stable and left side Insiders

* In both setup, the next cell is fully visible
* In Stable, shift+enter moves the next cell up, and then push it down, but the new focused cell is still visible in the viewport at the end
* In Insiders, shift+enter moves the next cell up, and when the previous starts to grow, it does not move the focused cell downwards

https://github.com/microsoft/vscode/assets/876920/944b1173-b05f-4553-89df-bd78af75928c

Even though the new behavior is more self explanatory (from our perspective), but unluckily is not the same as Jupyter Lab. It means we are changing from one custom behavior (our previous heuristics) to another (always keep focused cell stable)

**Comment by joaomoreno** [comment]
Thanks for clarifying this @rebornix. It was not clear to me that (1) shift+enter and clicking the run cell action did different things, nor that (2) this bug was only about one of these actions.

**Comment by amunger** [comment]
fixed by https://github.com/microsoft/vscode/pull/195283
