### ISSUE TITLE
Allow text in error message popups to be copied or at least selected

### ISSUE THREAD

**Issue by torbjorn** [microsoft/vscode#193243]
The possibility to copy the message in an error popup (the one with a red X in a circle. This would be nice for:

* searching error messages
* getting key info to resolve the error oneself

Below is my specific usecase:
![Untitled](https://github.com/microsoft/vscode/assets/4111/f2d3a726-6c89-4d2d-bba6-aa2feb345449)

The server I work on does not have ftp access, so I need to download that file on my workstation and scp it onto the server.

As it is I cannot select that text to copy the url, so I'm left with typing a 100 character ftp url by hand. Which is painful enough that I'm writing this issue.

**Comment by bpasero** [comment]
This makes sense 👍
