### ISSUE TITLE
Disabling Extensions on your local device across all workspace without disabling extensions present on other devices

### ISSUE THREAD

**Issue by EpicBirb** [microsoft/vscode#193299]
Disabling extensions for a device and ONLY that device, other devices are unaffected. This could be useful if your trying to use vscode on low-end devices. This also prevents the usage of disabling extensions for each and every workspace.

**Comment by sandy081** [comment]
You can use Disable (Workspace) action

<img width="359" alt="image" src="https://github.com/microsoft/vscode/assets/10746682/6f50c324-003d-47ab-ae0d-ab2e79068ced">
