### ISSUE TITLE
About Interface

### ISSUE THREAD

**Issue by SR-72-Dark-Star** [microsoft/vscode#193221]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.82
- OS Version: Windows 11
<img width="960" alt="image" src="https://github.com/microsoft/vscode/assets/145148138/c22b9215-5d6b-47b7-be1e-3c2a2f482983">

My Interface is looking like this , it showing no option like this one
<img width="631" alt="image" src="https://github.com/microsoft/vscode/assets/145148138/f9e4bd9a-7dc5-49e7-976b-b2df078ed9a9">

Steps to Reproduce:

1. 
2.

**Comment by gjsjohnmurray** [comment]
Can you click here and turn UI features on?

![image](https://github.com/microsoft/vscode/assets/6726799/75829275-ae2d-43b3-af1a-cef74d7d85fa)
