### ISSUE TITLE
[ruby] Bug in regex character class syntax highliting

### ISSUE THREAD

**Issue by prehor** [Microsoft/vscode#1932]
regex_sub character-class begin match contains mistakenly closing square brackets.

Patch for vscode/extensions/ruby/syntaxes/Ruby.plist attached.
[Ruby.plist.diff.txt](https://github.com/Microsoft/vscode/files/86143/Ruby.plist.diff.txt)

**Comment by isidorn** [comment]
Please create a pull request
https://github.com/Microsoft/vscode/pulls

**Comment by egamma** [comment]
CC @aeschli
