### ISSUE TITLE
Can't use my compiler

### ISSUE THREAD

**Issue by Casaca7** [microsoft/vscode#193280]
An unexpected error occurred that requires a reload of this page.
The workbench failed to connect to the server (Error: connection record disposed by ConnectionHub: {
"errorMessage": "Failed to start VS Code Remote server.",
"originalErrorType": "<no original type>",
"errorCode": -1,
"errorType": "GenericError",
"stack": "Error: Failed to start VS Code Remote server.\n at [CODESPACE_URL]\n at [CODESPACE_URL]\n at [CODESPACE_URL]\n at [CODESPACE_URL]\n at d ([CODESPACE_URL]\n at a ([CODESPACE_URL]"
} $1 $1)

**Comment by alexdima** [comment]
Could you please open a discussion at http://gh.io/ghcs-feedback?
