### ISSUE TITLE
Crashing when trying to open new window on Wayland

### ISSUE THREAD

**Issue by wooque** [microsoft/vscode#193216]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.82.2
- OS Version: Debian 12 with Sway 1.8.1 (Wayland compositor)

Steps to Reproduce:

1. Open VS Code with `/usr/share/code/code --unity-launch --ozone-platform=wayland`
2. Click `File -> New Window`

This was not happening in 1.81.1, regression was introduced in 1.82.0

**Comment by gjsjohnmurray** [comment]
Is #184124 relevant?

**Comment by wooque** [comment]
@gjsjohnmurray I don't think so, that issue is older. 
In **1.81** I can open `New Window` with both `native` and `custom` titlebars. There is no problems.
In **1.82** I can't even open VS Code at all with `native` titlebar, it crashes instantly. With `custom` titlebar it crashes after trying to open `New Window`.

**Comment by deepak1556** [comment]
Can you attach the crash report following the steps from https://github.com/microsoft/vscode/wiki/Native-Crash-Issues#creating-a-crash-report

**Comment by wooque** [comment]
@deepak1556 Here it is
[a50299f6-7498-4d11-bbfd-5fb01efe3a99.dmp.zip](https://github.com/microsoft/vscode/files/12646582/a50299f6-7498-4d11-bbfd-5fb01efe3a99.dmp.zip)

**Comment by stlaz** [comment]
Confirming that after an update to 1.82.2, vscode crashes upon startup.

**Comment by phlash** [comment]
Can confirm, after updating from 1.81.1 to 1.82.0, I get this crash just after startup when moving the pointer over the GUI.

[3da3c2f0-d16c-478e-884b-25af21d188a5.zip](https://github.com/microsoft/vscode/files/12686441/3da3c2f0-d16c-478e-884b-25af21d188a5.zip)

As per OP, Debian stable (bookworm) with Sway 1.7-6 (default version, Xwayland disabled. HTH!

**Comment by deepak1556** [comment]
Thanks for the crash logs, stacks share the same root cause as https://github.com/microsoft/vscode/issues/184124. Please follow the other issue for updates.
