### ISSUE TITLE
Debugging yeoman generator doesn't launch on Windows

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#19325]
Testing #19039

Steps to reproduce:

1. clone https://github.com/Microsoft/vscode-generator-code
2. npm install
3. npm link
4. Add Yeoman generator debug config
5. Try launch

![image](https://cloud.githubusercontent.com/assets/2193314/22275318/c19fc238-e260-11e6-939c-c2c1185a02d0.png)

Also note that I would not have known to `npm link` without the checked in header comment (which isn't included in the snippet).

**Comment by weinand** [comment]
@Tyriar yes, it would be great if we could add the comment about how to use `npm link` to the snippet template in the package.json. But this is not yet supported.
