### ISSUE TITLE
Some files do not show git modification hint

### ISSUE THREAD

**Issue by Zhoucheng133** [microsoft/vscode#193294]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:  1.82.2
- OS Version:  macOS 13.4.1

Steps to Reproduce:

1.  Modify the code NOT included in .gitignore
2. I can find the change in git panel but it doesn't show code area
3. NOT all files like this, and I can't fix it through restart vs code

Here is the screenshot:
![截屏2023-09-17 18 02 44](https://github.com/microsoft/vscode/assets/54197427/c836bf3c-9f96-463a-aa67-459c8e258209)
![截屏2023-09-17 18 05 44](https://github.com/microsoft/vscode/assets/54197427/9b3f6639-0e05-43c4-81b9-50186400181e)

**Comment by lszomoru** [comment]
@Zhoucheng133, could you try to reproduce with the latest [Insiders release](https://code.visualstudio.com/insiders/)? Thanks!

**Comment by Zhoucheng133** [comment]
I find it works on preview version. Thank you and waiting for the stable release!
