### ISSUE TITLE
Can't open terminal using ctrl + `

### ISSUE THREAD

**Issue by marArcz** [microsoft/vscode#193258]
Type: <b>Bug</b>

When few minutes passed pressing 'ctrl + ` ' to open the terminal does not work anymore but opening new terminal using 'alt + shift + `' works.

VS Code version: Code 1.82.2 (abd2f3db4bdb28f9e95536dfa84d8479f1eb312d, 2023-09-14T05:55:25.390Z)
OS version: Windows_NT x64 10.0.19044
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-2500 CPU @ 3.30GHz (4 x 3300)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: unavailable_off<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: unavailable_off<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|7.88GB (1.31GB free)|
|Process Argv|--crash-reporter-id 7738a3d5-2ee3-4624-86bb-12992172a715|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (44)</summary>

Extension|Author (truncated)|Version
---|---|---
laravel-extra-intellisense|ami|0.6.3
vscode-intelephense-client|bme|1.9.5
vscode-tailwindcss|bra|0.10.0
laravel-goto-view|cod|1.3.9
es7-react-js-snippets|dsz|4.4.3
vscode-html-css|ecm|1.13.1
EditorConfig|Edi|0.16.4
prettier-vscode|esb|10.1.0
figma-vscode-extension|fig|0.2.7
auto-rename-tag|for|0.1.10
live-sass|gle|6.1.1
laravel-create-view|gli|0.0.6
laravel-blade-wrapper|IHu|1.0.1
dotenv|mik|1.0.1
python|ms-|2023.16.0
vscode-pylance|ms-|2023.9.10
jupyter|ms-|2023.8.1002501831
jupyter-keymap|ms-|1.1.2
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-typescript-next|ms-|5.3.20230915
laravel-goto-components|nao|1.2.0
laravel-blade|one|1.34.0
laravel-extension-pack|one|1.2.0
laravel5-snippets|one|1.17.0
laravel-jump-controller|pgl|0.0.33
material-icon-theme|PKi|4.30.1
vscode-css-peek|pra|4.4.1
java|red|1.22.1
format-html-in-php|rif|1.7.0
LiveServer|rit|5.7.9
laravel-artisan|rya|0.0.31
vscode-blade-formatter|shu|0.23.1
ayu-green|Sir|1.0.1
jinja-extension-pack|sug|1.0.3
sass-indented|syl|1.8.28
intellicode-api-usage-examples|Vis|0.2.8
vscodeintellicode|Vis|1.2.30
vscode-java-debug|vsc|0.54.0
vscode-java-dependency|vsc|0.23.1
vscode-java-pack|vsc|0.25.14
vscode-maven|vsc|0.42.0
jinja|who|0.0.8
php-pack|xde|1.0.3
html-css-class-completion|Zig|1.20.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
py29gd2263:30792226
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
vscccc:30803845
3biah626:30602489
f6dab269:30613381
a9j8j154:30646983
showlangstatbar:30737416
0bi6i642:30835152
03d35959:30757346
57b77579:30736110
pythonfmttext:30731395
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
pythonnosmt12:30797651
pythonidxpt:30805730
pythonnoceb:30805159
dsvsc013:30795093
dsvsc014:30804076
diffeditorv2:30821572
dsvsc015:30829745

```

</details>

**Comment by mohammadamin16** [comment]
@gjsjohnmurray Can I try on this?

**Comment by meganrogge** [comment]
I cannot reproduce, use the command `Toggle keyboard shortcuts troubleshooting` to figure out what's going on for you.
