### ISSUE TITLE
Moving divider side-to-side in markdown preview sync is choppy

### ISSUE THREAD

**Issue by mousetraps** [Microsoft/vscode#19322]
Testing #19082

1. Open md file side by side w/ preview md file (choose a decently sized file like the cpp docs)
2. Try resizing preview horizontally by moving divider side-to-side

-> choppy experience

**Comment by mjbvz** [comment]
Removed this feature with 8396a11  as it is too choppy. It helped maintain your position in the document better but I'll investigate another approach
