### ISSUE TITLE
Debug item options are being shown at the back of the Developer tools panel.

### ISSUE THREAD

**Issue by lucasnatanmelo** [microsoft/vscode#193206]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.82.2 
- OS Version: Windows 10 Pro 64-bit

Steps to Reproduce:

1. Create a VSCode extension and console.log something in your root code.
2. Run in terminal `npm run watch` and Start Debugging with `F5`.
3. Open developer tools with `Ctrl + Shift + I`.
4. Filter the console.log item, and try to right click in this to display it's options like copy or expand or else. The Options are displayed in the back of developer Tools making it impossible to reach them.
![Screenshot_9](https://github.com/microsoft/vscode/assets/100950738/6617127c-8190-4dd3-a22c-5630836ba030)

**Comment by roblourens** [comment]
Not sure whether there is anything we can do about this, adding @deepak1556 in case you know whether something changed. I suggest using the Debug Console in vscode when debugging your extension though 😁

**Comment by deepak1556** [comment]
Its an issue in the runtime https://github.com/electron/electron/issues/38790

**Comment by SamB** [comment]
<https://github.com/electron/electron/issues/38790#issuecomment-1592911862> looks promising:

> Looks like it's this: https://chromium-review.googlesource.com/c/chromium/src/+/4356117 For now, this can be worked around by adding:
> 
> ```js
> app.commandLine.appendSwitch('disable-features', 'WidgetLayering');
> ```
> 
> to your code.

**Comment by amunger** [comment]
this seems to be fixed in the latest insiders with electron 29

**Comment by deepak1556** [comment]
Thanks for confirming.
