### ISSUE TITLE
Searching triggers OneDrive on demand download

### ISSUE THREAD

**Issue by gernophil** [microsoft/vscode#193297]
Does this issue occur when all extensions are disabled?: Does not apply

- VS Code Version: 1.82.2 (arm64)
- OS Version: macOS 13.5.2

Steps to Reproduce:

1. Add a folder within OneDrive to you workspace
2. Search that folder

Searching within a OneDrive folder triggers download of all files in that folder (an subfolders) that are on demand. This can lead to downloading huge amount of unneeded data.

**Comment by IllusionMH** [comment]
How would you expect search to be performed without downloading files?

**Comment by gernophil** [comment]
Well, if you have for example a subfolder with large files that are just a backup and therefore not locally stored those could be just excluded from the search. But starting a search automatically triggering downloading all of them could maybe just after after a prompt.

**Comment by IllusionMH** [comment]
You can exclude folders from search in settings.

**Comment by gernophil** [comment]
Then maybe consider this more as a feature request then a bug. You could also have single files that are not in a subfolder that are on demand. Normal OS search with Finder/Explorer also doesn't trigger downloading them (of course, it's a different kind of search). On top of that downloading by OneDrive can be a pain since often you have to wait for the downloading to complete before you can set it to on demand again (which is of course a OneDrive issue and not VSCode). However, it's just not expected I guess and it would be more convenient, if this wouldn't happen.

**Comment by andreamah** [comment]
Tracking on-demand files might be too demanding (and not very predictable) for the search functionality. I would probably just try to use `search.exclude` to exclude OneDrive folders in this case, since you don't want to scan that folder. Since we need to text results within all of the files, we unfortunately need to download them from OneDrive in this case.
