### ISSUE TITLE
Incorrect modifyPosition causes performance issue in monaco-editor.

### ISSUE THREAD

**Issue by wanghanzhen** [microsoft/vscode#193262]
Does this issue occur when all extensions are disabled?: Yes

That issue first happened in monaco-editor@0.35.0-dev.20221020 and it still exist in latest version.
Here is the reproducible demo. Scroll to 100000+ line,click and change cursor.
[monaco-editor@0.35.0-dev.20221020](https://microsoft.github.io/monaco-editor/playground.html?source=v0.35.0-dev.20221020#XQAAAAJQAgAAAAAAAABBqQkHQ5NjdPVqbEvRyz_S6KDWGp7GOOqAFxn31EH6uPXqQiDdJasbstSsLJ3WW6a15BmkjOqc9RGIlNYy7x5jRUyPY2HtrCO--wrybzIx-XOFEbcf3JUW9U-8lO7xlrnR45xB82CD3SXsCIQQtUvbxnE8foJyuiap55U04t97XNyR_iEhuDrQDgvypS7ivvxKDAhhadBW8nxhMjCr-sINQcFxQ2SgxA9ZJGoiHT6gA3Bx_x6MMiLoSNGOG-C2LDV7ztCEaroUwkbnZ2rslTg6QfL1yugmU-gmuHRgQEbswK42yxpm3x77oq5L29R53IHgVvEDbp1FdtYXkElBG9bmbE5BqrzUVxxHaKDViFapp4qEwWhf50fBY46d3mBB4EDYFM_F1nTMfzR6kUx-8oV9XEW_OvFMLD296vbyvwy1A3BEX9wjSutr4sH673MXREIFQcJ5qJvNFvaOg9hCxP8e0CACevUgWEb317URTV6gqU9CLFNj2nO-gWVMdVvwWy3rX1bcIaMHtEqBAAnugoFTaG8yqM8aj1fdZ6Rsvoz14TveJOLJO2uXYNTA82ZH8axIOuOp3SOOh9eK_P74BdJKPSneOZvDdcQGSdwrYvsATDI)
I recorded a perfomace in devtools and saw a long task layout.
<img width="1186" alt="image" src="https://github.com/microsoft/vscode/assets/25301012/a406114c-61e4-44a8-8b30-b5c6f32be7c5">

The 0.35.0-dev.20221019 version worked well.

So I tried to find the difference between these two versions and finally I found it out. Here is the [diff](https://github.com/microsoft/vscode/compare/9d3fbb3d9a50055be0a8c6d721625d02c9de492d...929c645c9a3727541c8fb30f4d62765f5c672ff9).
<img width="894" alt="image" src="https://github.com/microsoft/vscode/assets/25301012/5eb87ff0-6dbe-467f-afca-75d76f47ba41">
<img width="1160" alt="image" src="https://github.com/microsoft/vscode/assets/25301012/a180cebd-1175-4683-b91c-52f52593a2a0">

I think the problem is in this [`modifyPosition` function] (https://github.com/microsoft/vscode/compare/9d3fbb3d9a50055be0a8c6d721625d02c9de492d...929c645c9a3727541c8fb30f4d62765f5c672ff9#diff-61400b9c77c0373aa731ab138cf1b2e4345a47991855da838fa4074d031e92f4) which modifies a ViewPosition and returns a ModelPosition but ViewPosition and that will get a huge different lineNumber so that the above performance issue happened
<img width="1216" alt="image" src="https://github.com/microsoft/vscode/assets/25301012/27975bdc-0da8-4ad7-840c-b9a2b793ef0f">

The following is the right one, isn't it? Maybe I can make a PR.
<img width="1118" alt="image" src="https://github.com/microsoft/vscode/assets/25301012/25fdc80f-c5b2-4d84-8bb5-33ef8b62a7d7">

**Comment by wanghanzhen** [comment]
😁 Hopefully @alexdima could give some opinions

**Comment by wanghanzhen** [comment]
The problem still exists.

**Comment by wanghanzhen** [comment]
> So I tried to find the difference between these two versions and finally I found it out. Here is the [diff](https://github.com/microsoft/vscode/compare/9d3fbb3d9a50055be0a8c6d721625d02c9de492d...929c645c9a3727541c8fb30f4d62765f5c672ff9).
@alexdima Can you take a look at this issue? Thank you.
Currently skipping problematic logic through `accessibilitySupport: "off"`
<img width="1354" alt="image" src="https://github.com/microsoft/vscode/assets/25301012/ee06aaa4-59d1-4515-b612-0320bf87b260">

**Comment by alexdima** [comment]
Thank you! You're absolutely correct, `modifyPosition` was returning model positions instead of view positions.
