### ISSUE TITLE
Edit terminal commands in `Run Recent Commands` 

### ISSUE THREAD

**Issue by PraneshBalasubramaniam** [microsoft/vscode#193227]
Feature to edit recent terminal commands in `Terminal: Run Recent Commands` instead of just choosing from commands listed.
Because sometimes there is a need to edit the command slightly before executing.

**Comment by Tyriar** [comment]
You can now remove entries from previous session:

![Image](https://github.com/user-attachments/assets/aabb310b-d0f5-4346-b80a-71b3d172dace)

And edit the files easily when they're sources from a file (coming v1.96):

![Image](https://github.com/user-attachments/assets/e94eec35-7d91-49a0-a486-e52f860e048b)

No plans to add edit
