### ISSUE TITLE
Cannot Render on Second Startup

### ISSUE THREAD

**Issue by drfrostongithub** [microsoft/vscode#193223]
Type: <b>Bug</b>

Cannot render when second time startup, and even after uninstall and re-install still same. 

VS Code version: Code 1.82.2 (abd2f3db4bdb28f9e95536dfa84d8479f1eb312d, 2023-09-14T05:51:20.981Z)
OS version: Linux x64 5.15.0-83-generic snap
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 3400G with Radeon Vega Graphics (8 x 3699)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|1, 1, 1|
|Memory (System)|13.59GB (11.32GB free)|
|Process Argv|--no-sandbox --force-user-env --unity-launch --crash-reporter-id 53ceb0bc-ff95-414b-8303-1a94170d35b4|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-elixir-mix-formatter|ani|1.0.1
react-native-react-redux|EQu|2.0.6
prettier-vscode|esb|10.1.0
vscode-pull-request-github|Git|0.72.0
elixir-ls|Jak|0.16.0
vscode-react-native|msj|1.11.2
vetur|oct|0.37.3
material-icon-theme|PKi|4.30.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
vscccc:30803845
2e4cg342:30602488
89544117:30613380
showlangstatbar:30737416
0bi6i642:30835152
03d35959:30757346
pythonfmttext:30731395
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
pythonnosmt12:30797651
pythonidxpt:30805730
pythonnoceb:30805159
dsvsc013:30795093
dsvsc014:30804076
diffeditorv2:30821572
dsvsc015:30829745

```

</details>

**Comment by DonJayamanne** [comment]
> Cannot render 

thank you for filling this issue and sorry you are running into this

to better help you, please can you explain what you mean by ‘cannot render’
Can you send some screen samples and whether this issue exists even after you disable all extensions

**Comment by ganfao** [comment]
> > Cannot render
> 
> thank you for filling this issue and sorry you are running into this
> 
> to better help you, please can you explain what you mean by ‘cannot render’ Can you send some screen samples and whether this issue exists even after you disable all extensions


[Screencast from 2023-09-17 11-13-24.webm](https://github.com/microsoft/vscode/assets/112717913/bbff1e66-6c39-47be-9a3e-f2c691ee4583)

Faced the same issue, the first startup of vscode is absolutely normal.

But on second startup graphics of vscode turns into this (check attached screencast)

Info:
OS: Fedora release 38 (Thirty Eight) x
Kernel: 6.4.15-200.fc38.x86_64 
GPU: AMD ATI Radeon RX 6600/6600 XT/66
CPU: AMD Ryzen 7 5700X (16) @ 3.400GHz
Memory: 3517MiB / 15882MiB

**Comment by DonJayamanne** [comment]
I’m sorry but I cannot open the file
Please can you stack a screenshot (png, jpeg or other image formats)

that will be much simpler to help identify the issue and help you

**Comment by ganfao** [comment]
> I’m sorry but I cannot open the file Please can you attach a screenshot (png, jpeg or other image formats)
> 
> that will be much simpler to help identify the issue and help you

https://github.com/microsoft/vscode/assets/112717913/3b8fa0ce-cafc-4059-ab5f-91e0523a4b80
![image](https://github.com/microsoft/vscode/assets/112717913/eb4b4a7d-82d8-4e19-ad59-63c7fdef13f2)
![image](https://github.com/microsoft/vscode/assets/112717913/65c005a9-c8aa-4de3-9435-3310a77da3de)

**Comment by tamuratak** [comment]
Similar to  #190437.

See https://code.visualstudio.com/updates/v1_82#_update-highlights-for-chromium

> Certain [Mesa](https://mesa3d.org/) version updates cause broken shader compilation leading to artifacts in application UI. The issue is tracked in [issue #190437](https://github.com/microsoft/vscode/issues/190437), which also contains the link to the Chromium bug report. You can identify this issue by running with --verbose and looking for the following line ERROR:shared_context_state.cc(81)] Skia shader compilation error in the logs. If you are affected by this issue, the current workaround is to delete the GPU cache located at ~/.config/Code/GPUCache.

**Comment by deepak1556** [comment]
Please attach the output of `code --verbose`

**Comment by drfrostongithub** [comment]
> > Cannot render
> 
> thank you for filling this issue and sorry you are running into this
> 
> to better help you, please can you explain what you mean by ‘cannot render’ Can you send some screen samples and whether this issue exists even after you disable all extensions

As @ganfao comment, I had them.

> > > Cannot render
> > 
> > 
> > thank you for filling this issue and sorry you are running into this
> > to better help you, please can you explain what you mean by ‘cannot render’ Can you send some screen samples and whether this issue exists even after you disable all extensions
> 
> Faced the same issue, the first startup of vscode is absolutely normal.
> 
> But on second startup graphics of vscode turns into this (check attached screencast)
> 
>  Screencast.from.2023-09-17.11-13-24.webm 
> system info
> Info: OS: Fedora release 38 (Thirty Eight) x
> Kernel: 6.4.15-200.fc38.x86_64
> 
> GPU: AMD ATI Radeon RX 6600/6600 XT/66
> 
> CPU: AMD Ryzen 7 5700X (16) @ 3.400GHz
> 
> Memory: 3517MiB / 15882MiB
> 
> extensions.json
> [{"identifier":{"id":"bierner.color-info","uuid":"0f8bd812-5d52-4fff-bd1c-6b0a7ee9cad9"},"version":"0.7.2","location":{"$mid":1,"path":"/home/mikhail/.vscode/extensions/bierner.color-info-0.7.2","scheme":"file"},"relativeLocation":"bierner.color-info-0.7.2","metadata":{"id":"0f8bd812-5d52-4fff-bd1c-6b0a7ee9cad9","publisherId":"f164f116-e2aa-496b-84dc-2451248e8beb","publisherDisplayName":"Matt Bierner","targetPlatform":"undefined","isApplicationScoped":false,"updated":false,"isPreReleaseVersion":false,"installedTimestamp":1679838640728,"preRelease":false}},{"identifier":{"id":"formulahendry.auto-rename-tag","uuid":"6e440e71-8ed9-4f25-bb78-4b13096b8a03"},"version":"0.1.10","location":{"$mid":1,"path":"/home/mikhail/.vscode/extensions/formulahendry.auto-rename-tag-0.1.10","scheme":"file"},"relativeLocation":"formulahendry.auto-rename-tag-0.1.10","metadata":{"id":"6e440e71-8ed9-4f25-bb78-4b13096b8a03","publisherId":"38bbe3f0-5204-4170-845e-c2f966d979b8","publisherDisplayName":"Jun Han","targetPlatform":"undefined","isApplicationScoped":false,"updated":false,"isPreReleaseVersion":false,"installedTimestamp":1679838642964,"preRelease":false}},{"identifier":{"id":"anseki.vscode-color","uuid":"37d7747f-e652-4eac-83de-f2939f7e2121"},"version":"0.4.5","location":{"$mid":1,"path":"/home/mikhail/.vscode/extensions/anseki.vscode-color-0.4.5","scheme":"file"},"relativeLocation":"anseki.vscode-color-0.4.5","metadata":{"id":"37d7747f-e652-4eac-83de-f2939f7e2121","publisherId":"438bb7a7-6997-47eb-b23b-72c3ba845702","publisherDisplayName":"anseki","targetPlatform":"undefined","isApplicationScoped":false,"updated":false,"isPreReleaseVersion":false,"installedTimestamp":1679838644439,"preRelease":false}},{"identifier":{"id":"formulahendry.auto-close-tag","uuid":"d3836729-9cc1-42c1-b2af-d50071f57d29"},"version":"0.5.14","location":{"$mid":1,"path":"/home/mikhail/.vscode/extensions/formulahendry.auto-close-tag-0.5.14","scheme":"file"},"relativeLocation":"formulahendry.auto-close-tag-0.5.14","metadata":{"id":"d3836729-9cc1-42c1-b2af-d50071f57d29","publisherId":"38bbe3f0-5204-4170-845e-c2f966d979b8","publisherDisplayName":"Jun Han","targetPlatform":"undefined","isApplicationScoped":false,"updated":false,"isPreReleaseVersion":false,"installedTimestamp":1679838645541,"preRelease":false}},{"identifier":{"id":"naumovs.color-highlight","uuid":"121396ad-85a1-45ec-9fd1-d95028a847f5"},"version":"2.5.0","location":{"$mid":1,"path":"/home/mikhail/.vscode/extensions/naumovs.color-highlight-2.5.0","scheme":"file"},"relativeLocation":"naumovs.color-highlight-2.5.0","metadata":{"id":"121396ad-85a1-45ec-9fd1-d95028a847f5","publisherId":"e9a76d04-24d4-44eb-a202-964f71acf59e","publisherDisplayName":"Sergii N","targetPlatform":"undefined","isApplicationScoped":false,"updated":false,"isPreReleaseVersion":false,"installedTimestamp":1679838646986,"preRelease":false}},{"identifier":{"id":"xabikos.javascriptsnippets","uuid":"a2cec723-5349-460d-9de9-0fd1f8d3456f"},"version":"1.8.0","location":{"$mid":1,"path":"/home/mikhail/.vscode/extensions/xabikos.javascriptsnippets-1.8.0","scheme":"file"},"relativeLocation":"xabikos.javascriptsnippets-1.8.0","metadata":{"id":"a2cec723-5349-460d-9de9-0fd1f8d3456f","publisherId":"8961c3fe-3ec6-429d-886a-50b5af362a88","publisherDisplayName":"charalampos karypidis","targetPlatform":"undefined","isApplicationScoped":false,"updated":false,"isPreReleaseVersion":false,"installedTimestamp":1679838648601,"preRelease":false}},{"identifier":{"id":"mrmlnc.vscode-autoprefixer","uuid":"70159dd5-3ca5-4ccc-a7ae-011a662e08c2"},"version":"3.0.1","location":{"$mid":1,"path":"/home/mikhail/.vscode/extensions/mrmlnc.vscode-autoprefixer-3.0.1","scheme":"file"},"relativeLocation":"mrmlnc.vscode-autoprefixer-3.0.1","metadata":{"id":"70159dd5-3ca5-4ccc-a7ae-011a662e08c2","publisherId":"c958976e-9702-4f1a-8bdf-26b7bc012d65","publisherDisplayName":"mrmlnc","targetPlatform":"undefined","isApplicationScoped":false,"updated":false,"isPreReleaseVersion":false,"installedTimestamp":1679838653343,"preRelease":false}},{"identifier":{"id":"bmewburn.vscode-intelephense-client","uuid":"ffda6552-0ad5-431b-a4fa-0905a7e4f3f0"},"version":"1.9.5","location":{"$mid":1,"path":"/home/mikhail/.vscode/extensions/bmewburn.vscode-intelephense-client-1.9.5","scheme":"file"},"relativeLocation":"bmewburn.vscode-intelephense-client-1.9.5","metadata":{"id":"ffda6552-0ad5-431b-a4fa-0905a7e4f3f0","publisherId":"3209eeb0-2b1a-4484-8c83-2627b29db88e","publisherDisplayName":"Ben Mewburn","targetPlatform":"undefined","isApplicationScoped":false,"updated":false,"isPreReleaseVersion":false,"installedTimestamp":1679838654659,"preRelease":false}},{"identifier":{"id":"ritwickdey.liveserver","uuid":"b63c44fd-0457-4696-99e9-dbfdf70d77de"},"version":"5.7.9","location":{"$mid":1,"path":"/home/mikhail/.vscode/extensions/ritwickdey.liveserver-5.7.9","scheme":"file"},"relativeLocation":"ritwickdey.liveserver-5.7.9","metadata":{"id":"b63c44fd-0457-4696-99e9-dbfdf70d77de","publisherId":"17fd9a78-e430-4a78-add2-ade4a8830352","publisherDisplayName":"Ritwick Dey","targetPlatform":"undefined","isApplicationScoped":false,"updated":false,"isPreReleaseVersion":false,"installedTimestamp":1679838660151,"preRelease":false}},{"identifier":{"id":"natizyskunk.sftp","uuid":"fe74bfaf-4260-454f-981c-6541d1d31822"},"version":"1.16.3","location":{"$mid":1,"path":"/home/mikhail/.vscode/extensions/natizyskunk.sftp-1.16.3","scheme":"file"},"relativeLocation":"natizyskunk.sftp-1.16.3","metadata":{"id":"fe74bfaf-4260-454f-981c-6541d1d31822","publisherId":"f2b732c2-92e5-4eff-b876-efe87a56ec56","publisherDisplayName":"Natizyskunk","targetPlatform":"undefined","isApplicationScoped":false,"updated":true,"isPreReleaseVersion":false,"installedTimestamp":1686900375655,"preRelease":false}},{"identifier":{"id":"pranaygp.vscode-css-peek","uuid":"0b8f8d63-11a2-4194-969c-ca7488b3413a"},"version":"4.4.1","location":{"$mid":1,"path":"/home/mikhail/.vscode/extensions/pranaygp.vscode-css-peek-4.4.1","scheme":"file"},"relativeLocation":"pranaygp.vscode-css-peek-4.4.1","metadata":{"id":"0b8f8d63-11a2-4194-969c-ca7488b3413a","publisherId":"3975bc66-f8bb-46a9-b8b6-430f013e4fa5","publisherDisplayName":"Pranay Prakash","targetPlatform":"undefined","updated":false,"isPreReleaseVersion":false,"installedTimestamp":1689148905669,"preRelease":false}},{"identifier":{"id":"esbenp.prettier-vscode","uuid":"96fa4707-6983-4489-b7c5-d5ffdfdcce90"},"version":"10.1.0","location":{"$mid":1,"path":"/home/mikhail/.vscode/extensions/esbenp.prettier-vscode-10.1.0","scheme":"file"},"relativeLocation":"esbenp.prettier-vscode-10.1.0","metadata":{"id":"96fa4707-6983-4489-b7c5-d5ffdfdcce90","publisherId":"d16f4e39-2ffb-44e3-9c0d-79d873570e3a","publisherDisplayName":"Prettier","targetPlatform":"undefined","isApplicationScoped":false,"updated":true,"isPreReleaseVersion":false,"installedTimestamp":1690821677721,"preRelease":false}},{"identifier":{"id":"glenn2223.live-sass","uuid":"137c3643-510d-4a1f-a737-793c72e8b411"},"version":"6.1.1","location":{"$mid":1,"path":"/home/mikhail/.vscode/extensions/glenn2223.live-sass-6.1.1","scheme":"file"},"relativeLocation":"glenn2223.live-sass-6.1.1","metadata":{"id":"137c3643-510d-4a1f-a737-793c72e8b411","publisherId":"ee3335b0-2909-465b-ac95-ac4972a4bf1d","publisherDisplayName":"Glenn Marks","targetPlatform":"undefined","isApplicationScoped":false,"updated":true,"isPreReleaseVersion":false,"installedTimestamp":1692360998508,"preRelease":false}},{"identifier":{"id":"syler.sass-indented","uuid":"466468c3-1861-4ad1-bf3e-f9ad46545ebb"},"version":"1.8.28","location":{"$mid":1,"fsPath":"/home/mikhail/.vscode/extensions/syler.sass-indented-1.8.28","external":"file:///home/mikhail/.vscode/extensions/syler.sass-indented-1.8.28","path":"/home/mikhail/.vscode/extensions/syler.sass-indented-1.8.28","scheme":"file"},"relativeLocation":"syler.sass-indented-1.8.28","metadata":{"id":"466468c3-1861-4ad1-bf3e-f9ad46545ebb","publisherId":"e88a3a32-0abb-4d89-a45b-aff60e1432f5","publisherDisplayName":"Syler","targetPlatform":"undefined","isApplicationScoped":false,"updated":true,"isPreReleaseVersion":false,"installedTimestamp":1694254951921,"preRelease":false}}]
> If any other info needed, I can attach it as soon as possible.

What I'm doing, basically remove every trace of vscode, and the logs of it. 
This is happen because my linux updated.

**Comment by ganfao** [comment]
> code --verbose

[0918/220453.798691:ERROR:file_io_posix.cc(152)] open /home/mikhail/.config/Code/Crashpad/pending/4c867e79-c849-4822-a7f9-fcd289420298.lock: File exists (17)
[8361:0918/220453.847251:WARNING:bluez_dbus_manager.cc(247)] Floss manager not present, cannot set Floss enable/disable.
[main 2023-09-18T20:04:53.893Z] [File Watcher (node.js)] Request to start watching: /home/mikhail/.config/Code/User (excludes: <none>, includes: <all>),/home/mikhail/.config/Code/User/settings.json (excludes: <none>, includes: <all>)
[main 2023-09-18T20:04:53.898Z] Sending env to running instance...
[main 2023-09-18T20:04:53.899Z] [File Watcher (node.js)] Started watching: '/home/mikhail/.config/Code/User'
[main 2023-09-18T20:04:53.899Z] [File Watcher (node.js)] Started watching: '/home/mikhail/.config/Code/User/settings.json'
[8407:0918/220453.921253:WARNING:sandbox_linux.cc(393)] InitializeSandbox() called with multiple threads in process gpu-process.
[main 2023-09-18T20:04:53.928Z] Sent env to running instance. Terminating...
[main 2023-09-18T20:04:53.928Z] Lifecycle#kill()
[main 2023-09-18T20:04:53.928Z] Lifecycle#onWillShutdown.fire()

**Comment by soonee** [comment]
The same symptoms are occurring on all versions, regardless of the current version (1.18.2).

**Comment by deepak1556** [comment]
@soonee can you provide the output of `code --verbose`
