### ISSUE TITLE
I shouldn't have a specify a problem matching pattern for a background task

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#193234]
I just want to have a background task that runs a web server when I start debugging (as in https://github.com/microsoft/vscode/issues/193233). I don't know what 'problem' pattern might be emitted and I don't really care for ad-hoc work, but omitting the problem `pattern` results in a task error, so I have to put in some dummy pattern. We should just not require the pattern.

**Comment by meganrogge** [comment]
```
	{
  "label": "serve",
  "type": "shell",
  "command": "npx -y serve -p 8080 dist",
  "isBackground": true,
},
```

Using the above works for me now, can you still repro @connor4312 ?

**Comment by connor4312** [comment]
This works for me now as well, maybe it was related to the other issue somehow 🤷
