### ISSUE TITLE
Unable to change Output font / font family doesnt change notebook font. 

### ISSUE THREAD

**Issue by Yajanth** [microsoft/vscode#193269]
![image](https://github.com/microsoft/vscode/assets/82897011/4e69120c-a9d2-41d2-a4f6-579b5f340638)

I just updated VScode. Jupyter Notebook has got this default font and even after changing the font family the font of the output doesn't change.

**Comment by amunger** [comment]
I'm not seeing this, updating `notebook.output.fontFamily` still changes the output font

![Recording 2023-09-19 at 10 52 07](https://github.com/microsoft/vscode/assets/2019016/9750c668-9a43-42e1-b2bb-eaaddf46058f)

did you update to the latest version? Is that the built in output renderer (Do you see a change presentation option in the output menu)?

**Comment by Yajanth** [comment]
No othe option isn't available. No updates available, after hitting check
for updates.

**Comment by amunger** [comment]
what font family are you trying to use?

**Comment by Yajanth** [comment]
Droid Sans Mono . also tried Jetbrainsmono, monospace

**Comment by Yajanth** [comment]
Problem fixed , used JetBrains Mono.
