### ISSUE TITLE
Most of the screen elements are not visible  or distorted inside the window of code application

### ISSUE THREAD

**Issue by solita-jukkakoskimaki** [microsoft/vscode#193236]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.82.2

- OS Version: Fedora Linux 38 KDE Spin 

Steps to Reproduce:

1. Start code
2. See the visual distortion
![Screenshot_20230915_231845](https://github.com/microsoft/vscode/assets/90411379/0340b806-8f5f-4321-a5e3-8b2b521067cb)

![Screenshot_20230915_231845](https://github.com/microsoft/vscode/assets/90411379/41f04407-db37-4784-a55e-e74d2d9d9323)

**Comment by solita-jukkakoskimaki** [comment]
I have used code successfully during last year. But now after code upgrade or maybe due Fedora Linux upgrade, the drawing of the code is not OK anymore. Fedora Linux is totally uptodate

**Comment by gjsjohnmurray** [comment]
Maybe related to https://code.visualstudio.com/updates/v1_82#_update-highlights-for-chromium which includes advice about deleting GPU cache.

**Comment by solita-jukkakoskimaki** [comment]
Installed Packages
Name         : code
Version      : 1.82.2
Release      : 1694671900.el7
Architecture : x86_64
Size         : 365 M
Source       : code-1.82.2-1694671900.el7.src.rpm
Repository   : @System
From repo    : code

**Comment by solita-jukkakoskimaki** [comment]
Thank You Very Very Much, Sir! 
That was quick by you!

I wonder a little bit why deletion of GPUCache is called as a workaround, because it was just a cache and thus replaceable. And I guess, that from now on code works as well as usually ?

_"the current workaround is to delete the GPU cache located at ~/.config/Code/GPUCache."_

**Comment by gjsjohnmurray** [comment]
I think deletion is a one-time requirement on affected systems, but @deepak1556 can probably confirm.

**Comment by deepak1556** [comment]
Yes deleting the gpu cache is a one time step due to bug in the runtime, the release notes has relevant details to the upstream bug.
