### ISSUE TITLE
Vscode latest broken after fedora update

### ISSUE THREAD

**Issue by ullaskunder3** [microsoft/vscode#193291]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.82.2 
- OS Version: CPE OS Name: cpe:/o:fedoraproject:fedora:38
 Kernel: Linux 6.4.15-200.fc38.x86_64

1. I updated the fedora as I got prompted there's an update 
2. Right after that vs code just all blank

- I tried command to kill code `killall code` then there was a popup
![Screenshot from 2023-09-17 12-34-59](https://github.com/microsoft/vscode/assets/66258652/95359cdf-c521-400e-a460-030f686cc751)

![Screenshot from 2023-09-17 12-27-19](https://github.com/microsoft/vscode/assets/66258652/ec78fd30-ca1c-49f8-8641-e142272d3a1b)
![Screenshot from 2023-09-17 12-26-38](https://github.com/microsoft/vscode/assets/66258652/41e65964-185f-4e82-a939-8c1b178f1d76)

**Comment by ullaskunder3** [comment]
[dxlord.🐼.007] v4final$ killall code
[dxlord.🐼.007] v4final$ code --disable-gpu
[dxlord.🐼.007] v4final$ 


it worked

**Comment by Bohooslav** [comment]
This is a better solution https://github.com/microsoft/vscode/issues/193165#issuecomment-1720758749

**Comment by ullaskunder3** [comment]
deleting ? `~/.config/Code/GPUCached` do you think that's good idea, I don't think so may be I don't know
@mjbvz what do you think ?
`flag` or removing `cache` file

**Comment by ullaskunder3** [comment]
this fix fixed because i have to do this every time

[dxlord.🐼.007] v4final$ killall code
[dxlord.🐼.007] v4final$ code --disable-gpu
[dxlord.🐼.007] v4final$

**Comment by deepak1556** [comment]
/duplicate https://github.com/microsoft/vscode/issues/190437

Refs https://code.visualstudio.com/updates/v1_82#_update-highlights-for-chromium
