### ISSUE TITLE
Can't kill the vscode build task

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#19328]
- Start the build task for the vscode repo
- Run "Terminate running task"
- See error `"The tasks are executed in the intergrated terminal. Use the terminal to manage the tasks."`

I assume that's not supposed to show up here, since the task is not running in the terminal. Now there's no way to stop the task.

**Comment by roblourens** [comment]
Also I fixed the "intergrated" typo

**Comment by dbaeumer** [comment]
Looks like I broke something :-)

**Comment by depl0y** [comment]
Came across the same issue, when I start a grunt build task with a watch attached. Normally using "Terminate running task" (workbench.action.tasks.terminate) would kill the task, but now I need to restart VS Code.
