### ISSUE TITLE
warning when installing on fedora38

### ISSUE THREAD

**Issue by vikyw89** [microsoft/vscode#193254]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 
- OS Version: 

Steps to Reproduce:

1. Followed this install step https://code.visualstudio.com/docs/setup/linux
2. ![image](https://github.com/microsoft/vscode/assets/112059651/90d0dde3-f230-4b09-b8ac-4d7790e88c25)

**Comment by Searge** [comment]
I have updated vscode yesterday, and now it looks like this:

![зображення](https://github.com/microsoft/vscode/assets/2125311/69d55b16-aba0-483d-8f4c-8e80a9c6d088)

- VS Code Version: 1.82.2
- OS Version: Fedora Linux 38

**Comment by gjsjohnmurray** [comment]
@Searge Maybe related to https://code.visualstudio.com/updates/v1_82#_update-highlights-for-chromium which includes advice about deleting GPU cache.

**Comment by Searge** [comment]
@gjsjohnmurray It helped, thank you.

**Comment by nakrovati** [comment]
@gjsjohnmurray Thank you so much.

**Comment by rzhao271** [comment]
Hi @vikyw89 is the issue still occurring with v1.83.0? I'm unsure if it's a transient network issue.

**Comment by vikyw89** [comment]
I didn't check again. But, the only issue is just the warning, aside from that everything else looks great.   You can close the issue if you like.

**Comment by vikyw89** [comment]
I didn't check again. But, the only issue is just the warning, aside from that everything else looks great.   You can close the issue if you like.

Looks like a similar problem to this one.
https://github.com/openresty/openresty-packaging/issues/75

**Comment by rzhao271** [comment]
Closing as out of scope
