### ISSUE TITLE
Opening VSCode changes the scrolling speed globally

### ISSUE THREAD

**Issue by stuglaser** [microsoft/vscode#193287]
When I open VSCode, the touchpad two-finger scroll speed becomes slower globally.

I know this issue sounds strange, but I've verified that happens every time I open VSCode (and only vscode), and that it applies to multiple other applications (Chrome, Libreoffice). Closing vscode does not revert scrolling to the correct speed; a restart is needed.

I am running Xubuntu, with Ubuntu 22.04.3 (jammy), XFCE 4 (xfwm4 4.16.1).

I admit that it's very difficult to tell whether this is a vscode issue or a packaging issue.

Version: 1.82.2
Commit: abd2f3db4bdb28f9e95536dfa84d8479f1eb312d
Date: 2023-09-14T05:51:20.981Z
Electron: 25.8.1
ElectronBuildId: 23779380
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Linux x64 5.15.0-78-generic snap

**Comment by deepak1556** [comment]
Can you confirm if the issue happens with deb package of VS Code ?

**Comment by stuglaser** [comment]
Thanks for the suggestion. Looks like this problem does not occur with the deb package (1.82.2-1694671812), so it must be a weird snap issue.

For anyone debugging the snap, `synclient` shows that VertScrollDelta goes from 28 to 200 when I launch VS code from a snap.
