### ISSUE TITLE
Missing common properties in extension telemetry when logging error event

### ISSUE THREAD

**Issue by Joouis** [microsoft/vscode#193205]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.82.2
- OS Version: macOS Ventura 13.5.2

Steps to Reproduce:

1. Install the `@vscode/extension-telemetry`, then use this extension in any other extension, for example we're building [Prompt flow for VS Code](https://marketplace.visualstudio.com/items?itemName=prompt-flow.prompt-flow) now.
2. Trigger any uncaught error in our own extension.
3. Check the Kusto query result of configured App Insight service.

<img width="1035" alt="image" src="https://github.com/microsoft/vscode/assets/8896124/1f88a0b4-f200-4399-be47-684d82161617">

This is not the first issue I submitted, actually I found [unsanitized issue](https://github.com/microsoft/vscode-extension-telemetry/issues/179) before and @lramos15 helped to fixed it. I also learned from his PR then **take a deep look today to figure out if this bug is belong to the telemetry extension or the VSCode host**. After the investigation, not only submit a issue here, **I will also create a PR to fix it ASAP**. For more technical details, I will describe in the PR.

**Comment by lramos15** [comment]
Extension tests are now failing

**Comment by Joouis** [comment]
We also have a table showing the version where the error first and last occurred for investigation. And it doesn't work for unhandled error.
<img width="913" alt="image" src="https://github.com/microsoft/vscode/assets/8896124/7468f257-3c84-4876-9e68-c61ac110cfb8">
