### ISSUE TITLE
key realted issue 

### ISSUE THREAD

**Issue by Devanshbhawsar85** [microsoft/vscode#193214]
Type: <b>Bug</b>

i am not able to use my key v , whenver i press it .. it shows waiting for second key chord 

VS Code version: Code 1.82.2 (abd2f3db4bdb28f9e95536dfa84d8479f1eb312d, 2023-09-14T05:55:25.390Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz (8 x 2419)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|7.73GB (1.46GB free)|
|Process Argv|--crash-reporter-id b3c9d819-6058-4c27-a7e2-3950f3c9ba95|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (39)</summary>

Extension|Author (truncated)|Version
---|---|---
path-intellisense|chr|2.8.4
doxdocgen|csc|1.4.0
vscode-eslint|dba|2.4.2
prettier-vscode|esb|10.1.0
auto-close-tag|for|0.5.14
auto-rename-tag|for|0.1.10
code-runner|for|0.12.0
c-cpp-runner|fra|8.1.0
vscode-pull-request-github|Git|0.72.0
better-cpp-syntax|jef|1.17.2
vscode-gutter-preview|kis|0.30.0
dotenv|mik|1.0.1
vscode-pugbeautify|mrm|1.0.2
vscode-scss|mrm|0.10.0
isort|ms-|2023.10.1
python|ms-|2023.16.0
vscode-pylance|ms-|2023.9.10
jupyter|ms-|2023.8.1002501831
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.17
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-slideshow|ms-|0.1.5
remote-containers|ms-|0.309.0
remote-ssh|ms-|0.106.4
remote-ssh-edit|ms-|0.86.0
remote-wsl|ms-|0.81.3
cmake-tools|ms-|1.15.31
cpptools|ms-|1.17.5
cpptools-extension-pack|ms-|1.3.0
js-debug-nightly|ms-|2023.9.1317
remote-explorer|ms-|0.4.1
color-highlight|nau|2.5.0
LiveServer|rit|5.7.9
vscode-paste-and-indent|Rub|0.0.8
tabnine-vscode|Tab|3.13.0
cmake|twx|0.0.17
vscode-lldb|vad|1.9.2
vscode-todo-highlight|way|1.0.5
html-css-class-completion|Zig|1.20.0

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
vscccc:30803845
282f8724:30602487
89544117:30613380
showlangstatbar:30737416
962ge761:30835153
a2ce3375:30757347
pythonfmttext:30731395
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
pythonnosmt12:30797651
pythonidxpt:30805730
pythonnoceb:30805159
dsvsc013:30795093
dsvsc014:30804076
diffeditorv2:30821572
dsvsc015:30829745

```

</details>

**Comment by ulugbekna** [comment]
Please, check your `keybindings.json` (to open it, invoke command `Open Keyboard Shortcuts (JSON)` from the Command Palette (press `F1`)) for a keybinding that includes keys that don't work for you. I think you have a custom keybinding that overrides the keys you are interested in.
