### ISSUE TITLE
Extensions Do Not Sync with My GitHub Account

### ISSUE THREAD

**Issue by ZubairARooghwall** [microsoft/vscode#193285]
Type: <b>Bug</b>

I recently installed vscode on my Windows machine but when I want to sync my settings and extensions with my GitHub account, it syncs my settings but not extensions. I saw the logs and this is the error I get: 
"2023-09-17 05:30:49.086 [info] Extensions: Last sync data state does not exist.
2023-09-17 05:31:12.198 [error] Error: net::ERR_HTTP2_PROTOCOL_ERROR
    at SimpleURLLoaderWrapper.<anonymous> (node:electron/js2c/browser_init:2:49830)
    at SimpleURLLoaderWrapper.emit (node:events:513:28)
2023-09-17 05:31:12.198 [error] extensions: net::ERR_HTTP2_PROTOCOL_ERROR"

Also, I checked it with Microsoft Account, it worked.
Thanks for reviewing!

VS Code version: Code 1.82.2 (abd2f3db4bdb28f9e95536dfa84d8479f1eb312d, 2023-09-14T05:55:25.390Z)
OS version: Windows_NT x64 10.0.22621
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4310U CPU @ 2.00GHz (4 x 2594)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|7.91GB (2.86GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by sandy081** [comment]
>  Error: net::ERR_HTTP2_PROTOCOL_ERROR

Looks like you have network issues on that machine. Can you please check if you are able to install any extension manually?
