### ISSUE TITLE
Terminal tab change color does not work with multi-select

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#193379]
Repro:

- Open multiple terminals
- Select multiple terminal tabs
- Right click and change color
- Change color 🐛 only a single terminal is changed

https://github.com/microsoft/vscode/blob/d878a801801af60a91b8b50c16032386f40bdcc3/src/vs/workbench/contrib/terminal/browser/terminalActions.ts#L731-L737

Real context stored with the action was done recently as part of https://github.com/microsoft/vscode/issues/79034

Related: https://github.com/microsoft/vscode/issues/193378

**Comment by Tyriar** [comment]
Tracking each action separately

**Comment by meganrogge** [comment]
@Tyriar I'm not sure this is worth fixing as color is meant to differentiate between tabs. Same for the icon/ renaming.

**Comment by Tyriar** [comment]
@meganrogge you might want multiple red though, right now it doesn't work as expected. We were actually doing this wrong by querying which tabs were selected also, after https://github.com/microsoft/vscode/issues/79034 we get the actual instances this was triggered on passed into the action, so we can probably remove the special tab instance command as part of this.
