### ISSUE TITLE
Debug console using integrated terminal should not run under the user defined shell

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#19334]
Testing #19039

The command should be launched using `bash -c` or `cmd /c` (I think), which will run it under a consistent shell and exit upon completion. You can also now tell the terminal to wait on exit using the `waitOnExit` arg on `TerminalInstance`.

Starting debug under git bash:

![image](https://cloud.githubusercontent.com/assets/2193314/22276962/8ef11ec0-e26c-11e6-8bf2-e56a5dda55d8.png)

Support for reusing terminals is also on the way which could be useful.

**Comment by weinand** [comment]
@Tyriar if a user decides to run his debuggee in the Integrated Terminal (instead of the debug console), why shouldn't we honor the user defined shell he has configured for the Integrated Terminal?

**Comment by Tyriar** [comment]
@weinand because under Git Bash or WSL on windows debugging will be broken as above. People could also be using Powershell on Linux which would break as well.

Is the main purpose of the integration to leverage the escape sequence parsing?

**Comment by weinand** [comment]
hmm, configuring Powershell for the integrated terminal on macOS works just fine.
The main purpose of the integration is to support debugging of command line applications. The "debug console" does not support reading input and doesn't behave like a tty. So users have to use use the "integrated terminal" for this.

**Comment by Tyriar** [comment]
Ah ok, well since this the debugger is not an extension maybe you could grab the configured shell and handle the common cases (cmd, powershell, bash/zsh) like that instead of just by OS?

**Comment by weinand** [comment]
That's exactly what this [code](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/debug/electron-browser/terminalSupport.ts#L72) is supposed to do.

**Comment by Tyriar** [comment]
Ah, I guess I was experiencing bash -> Windows path conversion problems. Using a relative path and using `/` instead of `\` under Windows/bash.exe sould fix the Git Bash/WSL case.

**Comment by sethlivingston** [comment]
Hoping this stays in the queue. I prefer to use the bash shell on Windows, but it can't debug because of the path problems.

**Comment by ndelacruz** [comment]
@sethlivingston So, no way of debug right now using the bash shell on windows? 😢

**Comment by weinand** [comment]
This should work now in Insiders.
