### ISSUE TITLE
Node debug Print of Function Object generates errors for `arguments` and `caller`

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#19332]
Testing #15901

1. start debugging any node program
1. Print out a function object: `() => 0`

**Error**
![screen shot 2017-01-24 at 7 03 15 pm](https://cloud.githubusercontent.com/assets/12821956/22276366/ebd39082-e267-11e6-8ddf-dabba7e9a685.png)

`arguments` and `callee` both generate errors when the parent function is expanded

**Comment by mjbvz** [comment]
For reference, Chrome and Safari both seem to just print out the function definition itself in these cases

**Comment by roblourens** [comment]
Fixing this would be kind of a pain.
