### ISSUE TITLE
[TypeScript] Syntax highlight problems when missing semicolons

### ISSUE THREAD

**Issue by santiagohdzb** [Microsoft/vscode#1933]
I'm writing TypeScript code and everything is fine. But when I don't write semicolons this happens:
![captura](https://cloud.githubusercontent.com/assets/8533075/12242292/7834045a-b855-11e5-8398-accc3bbafced.PNG)
IntelliSense works fine, no errors are shown (as expected) but i get this weird syntax highlighting

VSCode: 0.10.6
Platform: Windows 8.1

**Comment by aeschli** [comment]
Reproduced with snippet
```
export class UI {
    public searchbar: SearchBar
    public console: Console
    
    constructor() {
        
    }
}
```

**Comment by aeschli** [comment]
This issue was moved to Microsoft/TypeScript-TmLanguage#47
