### ISSUE TITLE
Terminal tab rename does not work with multi-select

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#193380]
Repro:

- Open multiple terminals
- Select multiple terminal tabs
- Right click and rename
- Rename🐛 only a single terminal is changed
  https://github.com/microsoft/vscode/blob/d878a801801af60a91b8b50c16032386f40bdcc3/src/vs/workbench/contrib/terminal/browser/terminalActions.ts#L754-L769

Real context stored with the action was done recently as part of https://github.com/microsoft/vscode/issues/79034

Related: https://github.com/microsoft/vscode/issues/193378, https://github.com/microsoft/vscode/issues/193379

**Comment by tisilent** [comment]
@Tyriar I feel that using a single text box for modification is quite practical. 😈
