### ISSUE TITLE
JS -> TS sourcemaps aren't working for me when debugging tests

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#19330]
I created the following launch.json to try get debugging working on [xterm.js](https://github.com/sourcelair/xterm.js)' tests:

```js
{
  // Use IntelliSense to learn about possible Node.js debug attributes.
  // Hover to view descriptions of existing attributes.
  // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
  "version": "0.2.0",
  "configurations": [
    {
      "type": "node",
      "request": "launch",
      "name": "Mocha Tests",
      "cwd": "${workspaceRoot}",
      "runtimeExecutable": "${workspaceRoot}/node_modules/.bin/mocha",
      "windows": {
        "runtimeExecutable": "${workspaceRoot}/node_modules/.bin/mocha.cmd"
      },
      "runtimeArgs": [
        "--colors",
        "--recursive",
        "${workspaceRoot}/lib"
      ],
      "sourceMaps": true,
      "internalConsoleOptions": "openOnSessionStart"
    }
  ]
}
```

While debugging works I cannot put breakpoints on the source TS files, I have to put them on the JS files at which point the TS files are hit. Breakpoints on the TS files look like this:

![image](https://cloud.githubusercontent.com/assets/2193314/22276070/172d5346-e266-11e6-8277-c4dfa7706359.png)

Which tells me there could be a sourcemap problem but I don't know how to fix it  This is how the sourcemaps link to the TS file:

```
{"version":3,"sources":["../src/Viewport.ts"]
```

The project is laid out like this:

`src/Viewport.ts`
`src/Viewport.test.ts`

Which compiles to:

`lib/Viewport.js`
`lib/Viewport.test.js`

**Comment by weinand** [comment]
@Tyriar you have to tell node-debug where the generated JavaScript files live.
Just add this glob pattern to your launch config (after the `sourceMaps` attribute):
```json
"outFiles": [ "${workspaceRoot}/lib/**/*.js" ]
```

**Comment by Tyriar** [comment]
Thanks @weinand
