### ISSUE TITLE
Inline chat provider API

### ISSUE THREAD

**Issue by Zane-XY** [microsoft/vscode#193334]
I would like to know if there is an inline chat API available for extension developers to create and extend the inline popup, and add functionalities similar to those of Copilot inline chat?

**Comment by jrieken** [comment]
Yes, there is a proposal that we are currently work on. Today it is together with the chat panel API proposal but might move out into its own proposal. You can find it here: https://github.com/microsoft/vscode/blob/c9e43572d1f938cec80c1c26200092c01b2dce2e/src/vscode-dts/vscode.proposed.interactive.d.ts

**Comment by sushicw** [comment]
@jrieken as a followup: how is the Github Copilot extension able to use this proposed API without requiring VSCode Insiders?

**Comment by luhc228** [comment]
> @jrieken as a followup: how is the Github Copilot extension able to use this proposed API without requiring VSCode Insiders?

@jrieken I have the same question too. And when will the inline chat API be available in released VSCode?
