### ISSUE TITLE
typescript formater randomly adds and removes spaces

### ISSUE THREAD

**Issue by OneOfOne** [Microsoft/vscode#19335]
- VSCode Version: 1.8.1
- OS Version: Linux

Steps to Reproduce:

1. Create a typescript file with something that has a callback function (not a lambda), example:
```
$('.onoffswitch').click(function () {
	//....
});
```
2. Watch tslint complain about `Spaces before function parens are disallowed (space-before-function-paren)`.

3. Save the file, watch the space between the function and parens disappear, edit something and save the file again and watch it randomly get back.

**Comment by mjbvz** [comment]
It looks like the TypeScript formatter may be clashing with the TSLint formatter. A few questions to help investigate:

* Can you try reproducing this issue with extensions disabled (run code with `--disable-extensions`)
* Do you have `"tslint.autoFixOnSave"` or `"editor.formatOnSave"` enabled in your settings?
* Do you have any other typescript settings or tslint settings in your user or workspace settings?
* Do you have any tslint configuration files?

Thanks

**Comment by OneOfOne** [comment]
I had `"javascript.format.insertSpaceAfterFunctionKeywordForAnonymousFunctions": false`, I needed `"typescript.format.insertSpaceAfterFunctionKeywordForAnonymousFunctions": false` instead.

Sorry for the noise.
