### ISSUE TITLE
Incorrect Comment Highlighting for "ini".

### ISSUE THREAD

**Issue by sprinkle131313** [Microsoft/vscode#19336]
It seems github has the same highlight error. The ";" character doesn't indicate a comment in the following context:

```ini
; comment
[Something]
VAR=%VAR%;addition
;        ^~~~~~ not a comment
```

**Comment by mousetraps** [comment]
Indeed, you're right! Comments must be on their own lines in INI grammar

**Comment by aeschli** [comment]
This issue was moved to textmate/ini.tmbundle#2
