### ISSUE TITLE
Bad Diff

### ISSUE THREAD

**Issue by hediet** [microsoft/vscode#193370]
Notice the confusing import:

![Image](https://github.com/microsoft/vscode/assets/2931520/714c15c5-801d-4a48-90b0-8801263fac66)

[Monaco Editor Repro](https://microsoft.github.io/monaco-editor/playground.html?source=v0.44.0-dev-20230918#XQAAAAKuAwAAAAAAAABBqQkHQ5NjdMjwa-jY7SIQ9S7DNlzs5W-mwj0fe1ZCDRFc9ws9XQE0SJE1jc2VKxhaLFIw9vEWSxW3yscw4m0lEfGetoVyYgiB3WIAyGCL4buFPFOLc1lAy95RUKo06z2t3AsctLSHAcjORfYRN1yg400RgiDpSRk10aTwvQv6zU0xdTpaj6zSTK7O5w1Odpy7ndjoSj3ma3YVF3_FmBOgOwiopFHNNBPqMbq-v0RvCX2wcDNfJrORPwG1VK7vtKAvoDnL6nqm0qcLeCox2Vcd-zngBrgzSqiTgEXQEGrD3g7gonOqEAOByAGd_oCugkOt3ao7jXzQd3w4Fy-4lLimVF3_GvmNjyR7YPne-K0XCQvOZEr9A5yeBu954aGEYPtU0P7tS7ZI7XdPVWp_7Vx2LCz8OoMuuTAYZTfq_ZGyKuBTW_m2-yc_3ERGu8lnSsV9_kZXkpX9zk4UDmZemygf6VkJ5wo45Sstklpfb8Z8bTlqETeOfyLOVckLmu1MlZ26HwaiabpFkfqVf5VDfHsrfXn5RGiDRliyDdZrtECrEiRwdjhhRx-4_z-Exv_uPW5o)

**Comment by aiday-mar** [comment]
verified in the monaco editor playground with 'latest dev'
