### ISSUE TITLE
Markdown Preview: Links to markdown files in the workspace should also open in the preview

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#19339]
VSCode 1.9 added support for workspace links in the markdown preview. These currently open an editor window. Instead, I think clicking a link to a file in the workspace in the markdown preview should open that file in a new markdown preview.

**Comment by mjbvz** [comment]
I've prototyped this feature but am still trying to figure out the specifics of how clicking on a link to a local file in the preview should work. The two options that I've investigated:

* Close the current preview and open a new preview for the linked page. This behavior is more like a web browser. However, I'm not a huge fan because this approach loses navigation history.

* Open a new preview in the current editor column and switch to it. This matches the existing behavior but may clutter up the editor workspace with lots of preview pages if you are just browsing around.

Overall, I'm in favor of the second approach. Let me know if you have any thoughts one way or the other, or if you have any other suggestions here

**Comment by danuw** [comment]
Don't know if this is too late, but in favor of second approach too - it is especially about testing the link is working in my opinion, so no worries if it open previews in new tabs. Hope that helps and thanks (and comment on how to test - if that goes in a specific build of the insiders version?)

**Comment by CTLaChance** [comment]
Add an option to switch between the two methods. I would use the first method for ensuring link navigation works like GitHub wiki documentation. 

_Also thanks for working on this. It's desperately missing from the current build._

**Comment by mike-north** [comment]
@mjbvz I think you've discovered that there's a case to be made for either approach. It would be fantastic if the default action could be customized with workspace config.

My use case: navigable documentation that's comprised of folders & markdown files. Ideally, I'd love for vscode to provide a similar experience to what developers would get from browsing the same files on github. 

Fair point RE: navigation history -- personally I solve this with `< Back to Home` links at the top of each page. I don't think anyone expects vscode to turn into a full web browser -- just a slightly more complete story around links.

**Comment by mac-pro** [comment]
I think you can have it like a web browser. These are common:

- Single click: open in same window.
- Ctrl + click: open in new window.

For history, user can open tree in left side bar. Adding new button `Back to Home` would be complicated.

**Comment by ColinRCasto** [comment]
is this features still being considered at this point?
