### ISSUE TITLE
[Enhancement Request] Remove specific sub-folder from Explorer

### ISSUE THREAD

**Issue by ManGupt** [Microsoft/vscode#19338]
- VSCode Version: Code 1.8.1 (ee428b0eead68bf0fb99ab5fdc4439be227b6281, 2016-12-19T14:49:23.350Z)
- OS Version: Windows_NT ia32 10.0.10586
- Extensions:

|Extension|Author|Version|
|---|---|---|
|vim|vscodevim|0.5.2|

---

Steps to Reproduce:

1. Select a folder (A) through Open Folder...
2. From list of sub-folders of A select a folder (B).
3. Right-click to open sub-menu.
4. "Remove" option required besides "Del", that removes B from the open list but not remove from the hard-disk to Trash/Recycle bin.

**Comment by kumarharsh** [comment]
By remove, I'm assuming you mean `Hide this folder from project`? Similar to what is achieved by putting the mentioned sub-folder in the `"files.exclude"` option in workspace settings?

I can work on this, given that the core team would like to implement such a feature.

**Comment by mousetraps** [comment]
Cool idea! Another related scenario might also be a unified interface for "right click folder to exclude from indexing" (e.g. for language services)

@bpasero @dbaeumer - thoughts?

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/16855
