### ISSUE TITLE
Cannot Expand Thrown Errors in Node Debug Console

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#19333]
Testing #15796

1. Start debugging a node2 program
1. Run `throw {x: 2}` in the debug console

**Expected**
When running `console.error({x: 2})`, an expandable object is printed

**Actual**
Only prints the error text in this case

![screen shot 2017-01-24 at 7 13 04 pm](https://cloud.githubusercontent.com/assets/12821956/22276525/2711771c-e269-11e6-99a9-31787968a8c6.png)

**Comment by roblourens** [comment]
The reason it's a string is that an Error object doesn't look very good when you try to read the multiline stack as an object property. Definitely something to improve in the future though, especially for throwing other objects like this.

**Comment by roblourens** [comment]
This would be a feature request on vscode + debug protocol to give a better way to visualize a multiline string (error + stack) plus an object with expandable props. Feel free to close it though.

Chrome devtools lets me expand the object inline with the error message:

![image](https://user-images.githubusercontent.com/323878/33046231-fa4ae1cc-ce04-11e7-912b-b4153269fdc1.png)

![image](https://user-images.githubusercontent.com/323878/33046241-007baa18-ce05-11e7-9063-7b62aca4c4cd.png)
