### ISSUE TITLE
Terminal link detection: support `file:line:col-col` format

### ISSUE THREAD

**Issue by jmoore34** [microsoft/vscode#193384]
When working on Haskell code, `ghcid` may produce error output in the following format:

```
/Users/jon/myproject/domain/Cost.hs:115:84-114: error:
    • Couldn't match expected type ‘time-1.11.1.1:Data.Time.Calendar.Days.Day’
                  with actual type ‘Data.Text.Internal.Text’
```

It would be nice to have terminal link detection support for this `file:line:startcolumn-endcolumn` format (or, to discard the `-endcolumn` part and just jump to the start column). Currently, this format seems to trip up the parser: it detects the file, line number, and start column correctly, but then it seems to select backwards to near the start of the file.

(Note: ghcid seems to treat the end column index as inclusive, i.e. the cursor is before the last notable character.)

**Comment by Tyriar** [comment]
Can reproduce:
![image](https://github.com/microsoft/vscode/assets/2193314/22059e77-9181-4f24-aa2e-d92804f87b81)

Selects from 1:3 to 115 🤔 

![image](https://github.com/microsoft/vscode/assets/2193314/a34979f5-0536-47f1-b2e7-ca3ea518af3e)

**Comment by Tyriar** [comment]
Caused by a bad regex match:

![image](https://github.com/microsoft/vscode/assets/2193314/7beb8aa3-f549-43a5-a0ea-4cfadee3b4e9)
