### ISSUE TITLE
VS Code GUI not working

### ISSUE THREAD

**Issue by aayushi-2003** [microsoft/vscode#193340]
Does this issue occur when all extensions are disabled?: Yes it does

'
- VS Code Version: 1.82.2
- OS Version: Ubuntu 20.04.6 LTS

Issue: 
1) Open VS Code through GUI or CLI both result in the graphics shown in the images
2) Reinstalled vs code several times, yet the issue persists

Screenshots:
![Screenshot from 2023-09-18 14-14-07](https://github.com/microsoft/vscode/assets/98167798/08b0b804-cec2-4d18-b77d-ce479ffb863f)

After disabling extensions:
![Screenshot from 2023-09-18 14-58-54](https://github.com/microsoft/vscode/assets/98167798/b13b667f-9f35-4bc6-8544-10f106853a92)

**Comment by freaktechnik** [comment]
Launching with `--disable-gpu` fixes this for me.

**Comment by gjsjohnmurray** [comment]
Maybe you need to clear the GPU cache. See https://code.visualstudio.com/updates/v1_82#_update-highlights-for-chromium
