### ISSUE TITLE
Interface error with latest update on Ubuntu 20.04.6 LTS

### ISSUE THREAD

**Issue by PatrikHorvatic** [microsoft/vscode#193375]
Does this issue occur when all extensions are disabled?: Can't determine

- VS Code Version: 1.82.2
- OS Version: Ubuntu 20.04.6 LTS

Steps to Reproduce:

1. Start VS code
2. Wait

Hello, 
after installing the latest update of VS code, only window and toolbar are visible. I tried reinstalling VS code but the problem remains.
Error is attached.
![vs_code_bug](https://github.com/microsoft/vscode/assets/80419964/4ad5f7fc-7de7-4f3a-ad97-33e15b76f7ca)

**Detailed instalation info:**
Version: 1.82.2
Commit: abd2f3db4bdb28f9e95536dfa84d8479f1eb312d
Date: 2023-09-14T05:51:20.981Z
Electron: 25.8.1
ElectronBuildId: 23779380
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Linux x64 5.15.0-83-generic snap

**Device information:**
Ubuntu 20.04.6 LTS
AMD Ryzen 7 5700U (integrated graphics not used)
NVIDIA 1650 GTX (latest driver)

**Comment by gjsjohnmurray** [comment]
Please see https://code.visualstudio.com/updates/v1_82#_update-highlights-for-chromium and try the deletion of GPU cache it recommends.

**Comment by PatrikHorvatic** [comment]
This has resolved my issue. It is working fine now. Thank you sir!
