### ISSUE TITLE
Go to Definition/Implementation not working

### ISSUE THREAD

**Issue by leopascual** [microsoft/vscode#193469]
Type: <b>Bug</b>

Since last versions error presented; working with C#, dotnet core 6 latest on fwk, extentions and vscode versions. When I right click anything that is navigatable function, variable, etc. and select Go to Def or implementation, it only popups a message/tooltip No definition found for '[what I clicked]'. Or No Implementation found for....

VS Code version: Code 1.82.2 (abd2f3db4bdb28f9e95536dfa84d8479f1eb312d, 2023-09-14T05:55:25.390Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) Platinum 8268 CPU @ 2.90GHz (6 x 2900)|
|GPU Status|2d_canvas: unavailable_software<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>opengl: disabled_off<br>rasterization: disabled_software<br>raw_draw: disabled_off_ok<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software<br>webgpu: unavailable_software|
|Load (avg)|undefined|
|Memory (System)|16.00GB (10.64GB free)|
|Process Argv|--crash-reporter-id 11df044b-fdec-4d04-bd44-525683665957|
|Screen Reader|no|
|VM|33%|
</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|16.1.8
vscode-eslint|dba|2.4.2
gitlens|eam|14.3.0
EditorConfig|Edi|0.16.4
prettier-vscode|esb|10.1.0
vscode-jest-runner|fir|0.4.66
vbnet|gor|1.0.2
Angular2|joh|16.0.1
csharp|ms-|2.1.2
vscode-dotnet-runtime|ms-|1.7.3
remote-containers|ms-|0.309.0
angular-console|nrw|18.8.1
vscode-vba|ser|0.9.1
vscode-icons|vsc|12.5.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263:30335439
vscoreces:30445986
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
py29gd2263:30792226
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
vscccc:30803845
282f8724:30602487
89544117:30613380
a9j8j154:30646983
showlangstatbar:30737416
962ge761:30835153
03d35959:30757346
ecj1e332:30736112
pythonfmttext:30731395
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
pythonnosmt12:30797651
pythonidxpt:30805730
pythonnoceb:30805159
copilotsettingc:30839828
dsvsc013:30795093
dsvsc014:30804076
diffeditorv2:30821572
dsvsc015cf:30829746

```

</details>

**Comment by ulugbekna** [comment]
I believe this has to be a problem on the C# extension side. Please, report this issue with them. Thanks!
