### ISSUE TITLE
Duplicate content

### ISSUE THREAD

**Issue by green961** [microsoft/vscode#193473]
Does this issue occur when all extensions are disabled?: Yes/No

https://code.visualstudio.com/docs/nodejs/nodejs-debugging#_additional-configuration

![搜狗截图20230919223611](https://github.com/microsoft/vscode/assets/81228933/2ba853bf-de08-43ff-9052-9294c0f7f951)

## The same content appears below

![搜狗截图20230919223740](https://github.com/microsoft/vscode/assets/81228933/1311d94c-837f-4b34-a3a5-043163ed9e8d)

**Comment by roblourens** [comment]
I think this is right, one is about auto attach and onen is about the debug terminal.

@connor4312 is `debug.javascript.terminalOptions` the right setting for configuring auto attach?

**Comment by connor4312** [comment]
Yea, it applies to both.

The duplication is intentional so that a user can read each section in one go without having to cross-reference elsewhere.
