### ISSUE TITLE
Display issue in VS Code terminal

### ISSUE THREAD

**Issue by sebastienthibaud** [microsoft/vscode#193437]
Type: <b>Bug</b>

Since the latest update of VSCode, I've been experiencing a display issue in my terminal. I'm using zsh and Oh My Zsh.

Thank you in advance for your help.

Before : 

<img width="216" alt="image" src="https://github.com/microsoft/vscode/assets/4547111/ea6c1a52-b21c-4cbc-bb1d-4520dca0c55f">

After : 

![image](https://github.com/microsoft/vscode/assets/4547111/86d74e25-4d8e-41b8-93ee-b28554253666)

VS Code version: Code 1.82.2 (abd2f3db4bdb28f9e95536dfa84d8479f1eb312d, 2023-09-14T06:00:27.244Z)
OS version: Darwin arm64 22.5.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Max (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|3, 4, 5|
|Memory (System)|32.00GB (0.37GB free)|
|Process Argv|--crash-reporter-id b826ac38-6a3e-4126-8f2d-ac44d55fe598|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
project-manager|ale|12.7.0
Bito|Bit|1.1.7
vscode-eslint|dba|2.4.2
es7-react-js-snippets|dsz|4.4.3
gitlens|eam|14.3.0
prettier-vscode|esb|10.1.0
copilot|Git|1.112.420
vscode-pull-request-github|Git|0.72.0
code-coverage|mar|1.11.0
git-graph|mhu|1.30.0
vscode-language-pack-fr|MS-|1.82.2023091309
vscode-graphql|ors|0.3.18
material-icon-theme|PKi|4.30.1
vs-code-prettier-eslint|rve|5.1.0
intellicode-api-usage-examples|Vis|0.2.8
console-ninja|Wal|0.0.225

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
py29gd2263cf:30792227
vscaat:30438848
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
vsccc:30803844
2e4cg342:30602488
f6dab269:30613381
a9j8j154:30646983
showlangstatbar:30737416
0bi6i642:30835152
a2ce3375:30757347
pythonfmttext:30731395
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
pythonnosmt12:30797651
pythonidxptcf:30805731
pythonnoceb:30805159
copilotsettingc:30839828
synctok:30821570
dsvsc013:30795093
dsvsc014:30804076
diffeditorv2:30821572
dsvsc015:30829745

```

</details>

**Comment by meganrogge** [comment]
does changing `terminal.integrated.gpuAcceleration` help?
