### ISSUE TITLE
[TypeScript] Bracket pair colorization fails when wraping type parameters

### ISSUE THREAD

**Issue by Alecton4** [microsoft/vscode#193433]
Does this issue occur when all extensions are disabled?: Yes (using extension bisect)

Version: 1.82.2
Commit: abd2f3db4bdb28f9e95536dfa84d8479f1eb312d
Date: 2023-09-14T05:51:20.981Z
Electron: 25.8.1
ElectronBuildId: 23779380
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Linux x64 6.4.12-1-default

Bracket pair colorization works fine if type parameters stay on the same line:

![image](https://github.com/microsoft/vscode/assets/43232804/30b4eb5c-8bb6-459e-945c-dc80d8b2bde9)

But fails if we wrap the type parameters:

![image](https://github.com/microsoft/vscode/assets/43232804/b05063e2-d0c3-4730-a855-239d179dda38)

A good minimal code snippet for this (from the comment under [another issue](https://github.com/microsoft/vscode/issues/191843#issuecomment-1706054463)):

```typescript
export const mapResponse = {
  blogPost: <I extends { 
    created: string; 
    updated: string; 
  }>(input: I) => {
    return {
      ...input,
      created: DateTime.fromISO(input.created),
      updated: DateTime.fromISO(input.updated)
    };
  }
};
```

**Comment by hediet** [comment]
This is a known issue (search for existing issues).

**Comment by Alecton4** [comment]
@hediet Sorry I did search but couldn't find a related one. Is this not going to be fixed as closed as "not planned"?
