### ISSUE TITLE
Red Theme no longer applies fully

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#19344]
Extracted from https://github.com/Microsoft/vscode/issues/19293#issuecomment-274983592

It appears to only apply to editor tokens, but not the background, whitespace, cursor, etc

Before (1.8):
![image](https://cloud.githubusercontent.com/assets/5047891/22282718/823ae874-e2de-11e6-9b72-fcd3969831d3.png)

After (insiders):
![image](https://cloud.githubusercontent.com/assets/5047891/22282740/9592dbfc-e2de-11e6-8cab-7873d2261d24.png)

**Comment by jfaustino** [comment]
It seems to me every theme is now a generic light or dark one.

**Comment by markgoodyear** [comment]
I'm seeing this too using the `Atom One Dark (Sublime Babel)` theme, with the `Sublime Babel` plugin:

<img width="1198" alt="code-differences" src="https://cloud.githubusercontent.com/assets/346098/22287848/567c3a36-e2ec-11e6-8bd6-4ff417ada600.png">

I've switched back to 1.8.1 as the difference is too contrasty and harsh on my eyes—not just on  `Atom One Dark (Sublime Babel)` theme, but for all themes.

**Comment by markgoodyear** [comment]
Looks like this has re-surfaced in the latest Insiders release today.
