### ISSUE TITLE
Allow users to do copy paste in the integrated terminal using ctrl+c, ctrl+v

### ISSUE THREAD

**Issue by thekalinga** [Microsoft/vscode#19348]
- VSCode Version:
All versions
- OS Version:
Ubuntu

Within terminal if you need to copy text, currently we need to use `ctrl+insert` & for pasting `shift+insert`

However, this is a strange way to do this especially in an editor.

Intellij allows you to copy & paste text within terminal using `ctrl+c` & `ctrl+v`

If text is selected within terminal using mouse, `ctrl+c` would trigger copy. If no text is selected & `ctrl+c` is pressed, this would lead to usual cancellation of the running program, i.e exactly the way it is behaving now.

`ctrl+v` should paste the text bindly from clipboard

So, `ctrl+c` should selection sensitive `copy/cancel` & `ctrl+v` is blind paste

**Comment by mousetraps** [comment]
Hey @thekalinga, thanks for reaching out! It looks like we already have something like what you're looking for: https://code.visualstudio.com/docs/editor/integrated-terminal#_copy-paste

Note that on Linux, it should be Ctrl+Shift+C and Ctrl+Shift+V - perhaps @Tyriar could share a little more insight on that design decision.

**Comment by Tyriar** [comment]
Yes ctrl+shift+c/v are the defaults on Linux to align with `gnome-terminal`'s defaults. You can configure your settings to do a bunch of cool stuff with copy and paste though. Just add this to your keybindings.json file to get the behavior you're after:

```js
{ "key": "ctrl+c", "command": "workbench.action.terminal.copySelection", "when": "terminalFocus && terminalTextSelected" },
{ "key": "ctrl+v", "command": "workbench.action.terminal.paste", "when": "terminalFocus" }
```

You may also be interested in the `terminal.integrated.rightClickCopyPaste` setting which adopts the new cmd.exe's behavior to copy on right click with a selection and paste when there is no selection.

**Comment by thekalinga** [comment]
Looks like I am consistently missing on doing my home work w.r.t existing actions that are already available.

Will make sure I've done my background work before posting next issue :)

Sorry for the trouble.

Thanks in anycase
