### ISSUE TITLE
API: Allow disablement for contributable menu commands

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#19345]
It would be cool to be able to hide commands from the command palette based on context keys.

**Comment by joaomoreno** [comment]
The `when` clause could be an option, although it signifies `disablement` for menus. This would still be consistent if we consider that `enablement === visibility` when in the Command Palette menu. This makes sense to me.

So, one idea would be to simply add a `when` clause to the command itself.

Another idea, which I find very appealing, would be to say:

- Every command always appears in the command palette, just as now
- Except when included in a special menu (`global`, `commandPalette`). When doing so, the `when` clause would control its visibility (given that `enablement === visibility` in the command palette).

What do you think?

**Comment by isidorn** [comment]
I have a similar issue which could profit from this, namely I have an action which I want to always appear in the command pallete but only when a precondition is met to appear in the context menu. Currently we do not have a solution for this as far as I am aware.

However if I could hide the actions from the command pallete then I could register two actions which do the same thing, one would take care of the context menu and the other of the comand palette.
An alternative solution for me is to have precondition only for the context menu.

**Comment by joaomoreno** [comment]
@jrieken Given any thought to this? I really like **Idea 2**.

**Comment by jrieken** [comment]
I have thought about something like idea 1 but more for something like a precondition under which we don't attempt to run a command. Idea 2 make sense as today the command palette is already the default menu. Once explicitly configured you get more control

**Comment by joaomoreno** [comment]
Should I sketch something up for **Idea 2**? Any preference on the menu name?

- `default`
- `global`
- `commandPalette`
- etc.

**Comment by jrieken** [comment]
I would go with `commandPalette`

**Comment by letmaik** [comment]
I'm a bit confused about this. For custom views I need to contribute some commands for the menu items of the view entries. The menu item commands then show up in the command palette where they don't make sense. How can I hide those commands from the palette?

**Comment by isidorn** [comment]
@letmaik I believe they will always show up in the command palette and that is not configurable. However you should be able to control when they show up in the context menu with the `when` clause

**Comment by letmaik** [comment]
Right, I use the `when` clause already. Shouldn't hiding from the command palette be a feature? Otherwise it's getting littered with unusable commands.

**Comment by isidorn** [comment]
@letmaik it seems like the command palette is not respecting the when clause unfortunenetly. You can file a new issue regarding this.
