### ISSUE TITLE
Faster TextModel/TextBuffer access

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#193427]
## Background

The core data structure powering the code editor is the PieceTree structure, as detailed in this ([blog post](https://code.visualstudio.com/blogs/2018/03/23/text-buffer-reimplementation)). It has been carefully crafted to strike an optimal balance between file reading speed, editing performance, and memory efficiency. However, there are trade-offs, including line reading speed. When a file is pulled into memory from the disk, we maintain the buffer as received from Node.js in its original state, accessing line content only upon request. This approach ensures swift file loading, with the cost of line content reading deferred to a later point.

The recent [memory cage update](https://www.electronjs.org/blog/v8-memory-cage) from Electron introduced another dimension to consider beyond just reading file content performance: memory usage on the heap (relevant issue [#167719](https://github.com/microsoft/vscode/issues/167719)). While our concerns previously centered around speed (and for clarity, when comparing to other implementations like string arrays, in practice, line reading is only a matter of milliseconds), there's now an additional impact on memory footprint. When we call `model.getValue()` or `model.getLineContent()`, a substring is created on the heap, which is constrained by the memory cage. Furthermore, this substring is discarded after its use, leading to inefficiencies and an increased load on the Garbage Collector (GC).

Given these nuances, it's recommended to avoid using `getValue()` or `getLineContent()`. For instance, to get the text length of a line, use `getLineLength()` instead of `getLineContent().length`.

## Ask

There are dozens of instances where accessing the text model content is unnecessary and could also lead to an OOM crash. These instances have been categorized by severity below. Please prioritize the high-severity items assigned to you. For items of medium or low severity, please allocate some time for them during the upcoming debt week.

### High

Using `getValue()` with large files in the following instances can result in an OOM crash

- [x] [src/vs/workbench/browser/dnd.ts](https://github.com/microsoft/vscode/blob/a6403e4552d39c1de87a24ad953d7d33be08cd74/src/vs/workbench/browser/dnd.ts#L299) @bpasero
- [x] [src/vs/workbench/contrib/files/browser/editors/fileEditorInput.ts](https://github.com/microsoft/vscode/blob/a6403e4552d39c1de87a24ad953d7d33be08cd74/src/vs/workbench/contrib/files/browser/editors/fileEditorInput.ts#L437) @bpasero

### Mid

`getValue() === ''` could be replaced by `getValueLength()`

- [x] [src/vs/workbench/contrib/chat/browser/chatInputPart.ts](https://github.com/microsoft/vscode/blob/a6403e4552d39c1de87a24ad953d7d33be08cd74/src/vs/workbench/contrib/chat/browser/chatInputPart.ts#L228) @roblourens
- [x] [src/vs/workbench/contrib/searchEditor/browser/searchEditor.ts](https://github.com/microsoft/vscode/blob/a6403e4552d39c1de87a24ad953d7d33be08cd74/src/vs/workbench/contrib/searchEditor/browser/searchEditor.ts#L686-L687) @andreamah
- [x] [src/vs/workbench/contrib/chat/browser/chatQuick.ts](https://github.com/microsoft/vscode/blob/a6403e4552d39c1de87a24ad953d7d33be08cd74/src/vs/workbench/contrib/chat/browser/chatQuick.ts#L160-L168) @TylerLeonhardt
- [x] [src/vs/workbench/contrib/codeEditor/browser/emptyTextEditorHint/emptyTextEditorHint.ts](https://github.com/microsoft/vscode/blob/a6403e4552d39c1de87a24ad953d7d33be08cd74/src/vs/workbench/contrib/codeEditor/browser/emptyTextEditorHint/emptyTextEditorHint.ts#L181) @joyceerhl
- [x] [src/vs/workbench/contrib/comments/browser/simpleCommentEditor.ts](https://github.com/microsoft/vscode/blob/a6403e4552d39c1de87a24ad953d7d33be08cd74/src/vs/workbench/contrib/comments/browser/simpleCommentEditor.ts#L65) @alexr00

`getLinesContent()` splits the file into a string array, using `getValue()` or iterating through the lines with `getLineContent()` could be more efficient.

- [x] [src/vs/workbench/contrib/chat/browser/chatListRenderer.ts](https://github.com/microsoft/vscode/blob/a6403e4552d39c1de87a24ad953d7d33be08cd74/src/vs/workbench/contrib/chat/browser/chatListRenderer.ts#L999) @joyceerhl
- [x] [src/vs/workbench/contrib/mergeEditor/browser/mergeEditorInputModel.ts](https://github.com/microsoft/vscode/blob/a6403e4552d39c1de87a24ad953d7d33be08cd74/src/vs/workbench/contrib/mergeEditor/browser/mergeEditorInputModel.ts#L317-L318) @hediet

`getLineContent()`, in following cases, `getLineLength()` or `getCharCodeAt()` could be more efficient

- [x] [src/vs/editor/common/cursor/cursorMoveCommands.ts](https://github.com/microsoft/vscode/blob/a6403e4552d39c1de87a24ad953d7d33be08cd74/src/vs/editor/common/cursor/cursorMoveCommands.ts#L446) @alexdima
- [x] [src/vs/editor/contrib/linesOperations/browser/linesOperations.ts](https://github.com/microsoft/vscode/blob/a6403e4552d39c1de87a24ad953d7d33be08cd74/src/vs/editor/contrib/linesOperations/browser/linesOperations.ts#L711-L712)
- [x] [src/vs/editor/contrib/linesOperations/browser/linesOperations.ts](https://github.com/microsoft/vscode/blob/a6403e4552d39c1de87a24ad953d7d33be08cd74/src/vs/editor/contrib/linesOperations/browser/linesOperations.ts#L867)
- [x] [src/vs/workbench/contrib/codeEditor/browser/suggestEnabledInput/suggestEnabledInput.ts](https://github.com/microsoft/vscode/blob/a6403e4552d39c1de87a24ad953d7d33be08cd74/src/vs/workbench/contrib/codeEditor/browser/suggestEnabledInput/suggestEnabledInput.ts#L447) @connor4312
- [x] [src/vs/workbench/contrib/comments/browser/commentNode.ts](https://github.com/microsoft/vscode/blob/a6403e4552d39c1de87a24ad953d7d33be08cd74/src/vs/workbench/contrib/comments/browser/commentNode.ts#L491) @alexr00
- [x] [src/vs/workbench/contrib/interactive/browser/interactiveEditor.ts](https://github.com/microsoft/vscode/blob/a6403e4552d39c1de87a24ad953d7d33be08cd74/src/vs/workbench/contrib/interactive/browser/interactiveEditor.ts#L509) @amunger
- [x] [src/vs/workbench/contrib/preferences/common/smartSnippetInserter.ts](https://github.com/microsoft/vscode/blob/a6403e4552d39c1de87a24ad953d7d33be08cd74/src/vs/workbench/contrib/preferences/common/smartSnippetInserter.ts#L37) @bpasero
- [x] [src/vs/workbench/contrib/scm/browser/scmViewPane.ts](https://github.com/microsoft/vscode/blob/a6403e4552d39c1de87a24ad953d7d33be08cd74/src/vs/workbench/contrib/scm/browser/scmViewPane.ts#L2083) @meganrogge

**Comment by bpasero** [comment]
@rebornix thanks for finding these instances but what is the suggested fix here? Is the editor component now throwing an error eagerly before allocating too much memory and basically clients have to handle this exception now?

**Comment by bpasero** [comment]
@alexdima the reason we store the value into the drag operation is to be able to get it out at the drop target again (which can be a different VS Code instance). So for this to work we would need to leverage streaming support as data transfer if possible.

**Comment by TylerLeonhardt** [comment]
I don't see a `getValueLength()`? 
![image](https://github.com/microsoft/vscode/assets/2644648/1ba57648-6e31-460e-804a-3c444edcc013)

**Comment by joyceerhl** [comment]
@TylerLeonhardt I think you need `.getModel()?.getValueLength()`

**Comment by rebornix** [comment]
> In any case, I would expect getValue (or any of these methods) to throw if the model is large so that we are sure we do not hit the limits by new code in the future. Alternatively, return undefined or null to indicate this or a new type.

@bpasero both `getValue` and `getLinesContent` will throw an error when the buffer is too large as we are very likely using the API wrong or it might crash. 

> thanks for finding these instances but what is the suggested fix here? Is the editor component now throwing an error eagerly before allocating too much memory and basically clients have to handle this exception now?

You are right, the suggested fix is 

* either checking `isTooLargeForHeapOperation()` and avoid calling `getValue()`, like https://github.com/microsoft/vscode/blob/main/src/vs/editor/contrib/find/browser/findController.ts#L396
* or handling the potential exception to ensure that your component still works fine after the exception (and does not mess up the whole workbench)

**Comment by bpasero** [comment]
via https://github.com/microsoft/vscode/pull/193510
