### ISSUE TITLE
AutoHotkey (Windows)/Keyboard Maestro (OS X) text replacements don't work in Visual Studio Codek

### ISSUE THREAD

**Issue by bjarte** [Microsoft/vscode#1934]
I have the exact same issue with AutoHotkey in Windows and Keyboard Maestro in OS X:

I have a setup where **btw** is automatically replaced with **by the way**.

In every application I have tested, except VSCode, this works. Every time I type **btw**, these three characters are deleted and **by the way** inserted instead. In VSCode the three characters are deleted, but **by the way** is never inserted.

I'm no expert on text replacement apps, but I think the text replacements apps work by simulating three presses on the backspace key, then simulating a press on each character key in **by the way** or by adding **by the way** to the clipboard and then pasting it into the active window.

If you want to recreate the bug, try the following AutoHotkey file:

    :?*:btw::by the way

**Comment by bjarte** [comment]
I'm not sure when it disappeared, but I no longer have the issue on OS X with Keyboard Maestro.

But I still have the same issue on Windows with AutoHotkey.

**Comment by alexandrudima** [comment]
Just tried it, I think a1bd50f63fd8185a13495ff3d4c67396109e4e71 fixed this too.

**Comment by bjarte** [comment]
Thanks for the update. 

I found a workaround for the bug, which is to add a 100 ms pause between deleting the keyword, "btw", and inserting the replacement "by the way".

My AutoHotkey script:
 :?*:btw::{Sleep 100}by the way

I'm glad you managed to find the bug!
