### ISSUE TITLE
Notebook editor doesn't scroll when arrow up moves the selected cell under the sticky scroll header

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#193404]
- Have a few headers in the sticky scroll header of the notebook editor
- Press arrow up, to move the selected cell up
- If the selected cell is out of the viewport, then the notebook editor should scroll to ensure it's visible, but when the selected cell is hidden under the sticky scroll area, then apparently we think it's within the viewport and don't scroll, so I can't see the selected cell

![Image](https://github.com/microsoft/vscode/assets/323878/66f4b590-5804-4aae-889a-3eb895b71e4d)

**Comment by Yoyokrazy** [comment]
Thanks for spotting that, I think we brought in the height of the sticky scroll into the nbEditorWidget so I can likely take a look at accounting for this.

**Comment by Yoyokrazy** [comment]
fixed via #201837
