### ISSUE TITLE
Editor does not properly update folder structure when changing to different git branch

### ISSUE THREAD

**Issue by Elmeri** [Microsoft/vscode#19341]
- VSCode Version: Code 1.8.1 (ee428b0eead68bf0fb99ab5fdc4439be227b6281, 2016-12-19T14:42:49.304Z)
- OS Version: Darwin x64 16.1.0
- Extensions:

|Extension|Author|Version|
|---|---|---|
|python|donjayamanne|0.5.6|
|robotframework|vivainio|0.1.2|

---

Steps to Reproduce:

1. Create Subfolder(s) to one git branch and commit
2. Change to another branch
3. Change back branch mentioned in step 1. 

Restarting editor fixes this

**Comment by mousetraps** [comment]
Hey, thanks for reporting this! Unfortunately, I can't seem to reproduce the issue on either the Insiders or 1.8 build. A few Qs:
1. Just to clarify, you mean that the folder that you created in the branch no longer appears in the VS Code UI?
2. Are you using the command prompt or UI when switching branches?
3. Does it happen in a small sample project with a few files as well, or is there something special about your workspace in particular?
4. When you say create a "subfolder" and commit, do you mean a subfolder with a file inside (so technically you are committing the file, not the folder), or something else?

cc @bpasero

**Comment by bpasero** [comment]
@Elmeri 
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: http://code.visualstudio.com/Download#insiders

**Comment by Elmeri** [comment]
1. The folder that I created in the branch no longer appeared on VS Code UI.
2. Command prompt
3. I cannot reproduce this issue with a small sample project.
4. Subfolder with a file inside ( so, yes committing the file inside the folder).

Anyhow, the I can't reproduce the issue with small sample project and not in the original project (since after restarting the editor the folder structure is showing correctly).
