### ISSUE TITLE
How to use or disable problemMatcher when there no stdout/stderr output

### ISSUE THREAD

**Issue by taikulawo** [microsoft/vscode#193442]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 
```
Version: 1.82.2 (Universal)
Commit: abd2f3db4bdb28f9e95536dfa84d8479f1eb312d
Date: 2023-09-14T05:59:47.790Z
Electron: 25.8.1
ElectronBuildId: 23779380
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Darwin arm64 22.5.0
```
- OS Version: 
```
MacOS M1 Pro Ventura Version 13.4
```

`launch.json` call `start qemu` as preLaunchTask,  But my `start qemu` don't have any stdout/stderr, it just run silently.

The https://code.visualstudio.com/docs/editor/tasks#_background-watching-tasks say:

> If you have a background task, you must have problemMatcher which match stdout to decide whether the  `background task` is failed.

But how I can run the task in background when it don't have any stdout?  I don't want use problemMatcher, I just want to start a background task, I will take care this process and kill it when main process exit.

It if don't add problemMatcher, there always annoying popup showing

![image](https://github.com/microsoft/vscode/assets/24750337/e6527340-c73d-4b2f-9c58-50e081d3b478)

I don't want click `Remember my choices for this task`, I want to solve it in `tasks.json`

```
{
    // See https://go.microsoft.com/fwlink/?LinkId=733558
    // for the documentation about the tasks.json format
    "version": "2.0.0",
    "tasks": [
        {
            "label": "stop qemu",
            "type": "shell",
            "command": "pkill qemu-system-x86_64 -f",
            "problemMatcher": []
        },
        {
            "label": "start qemu",
            "type": "process",
            "isBackground": true,
            "command": "qemu-system-x86_64",
            "args": [
                "--kernel",
                "./arch/x86_64/boot/bzImage",
                "-initrd",
                "./rootfs.cpio",
                "-device",
                "e1000,netdev=eth0",
                "-netdev",
                "user,id=eth0,hostfwd=tcp::5555-:22,net=192.168.76.0/24,dhcpstart=192.168.76.9",
                "-append",
                "nokaslr console=ttyS0",
                "-S",
                "-nographic",
                "-gdb",
                "tcp::1234",
                "-virtfs",
                "local,path=/,security_model=none,mount_tag=guestroot"
            ]
        }
    ]
}

```

Steps to Reproduce:
1.  just run above `start qemu` as `preLaunchTask` in launch.json

Thanks

**Comment by meganrogge** [comment]
What if you set the problem matcher to `[]`?

**Comment by iamwwc** [comment]
not works

![image](https://github.com/microsoft/vscode/assets/24750337/2eb7b0fc-47c2-422d-86fc-60a54d66f8ea)

**Comment by iamwwc** [comment]
Does't work.

If I don't add `"isBackground": true, `start qemu` never stopped. launch never run.
`start qemu` should run backrgound but not blocking

**Comment by iamwwc** [comment]
add `isBackground`
![image](https://github.com/microsoft/vscode/assets/24750337/935a2e70-8314-4dc9-82d9-cdb50e003f77)

only `presentation`, blocking here
![image](https://github.com/microsoft/vscode/assets/24750337/d3f0c2fd-6c5f-4e25-b8c7-b89cfdb85c1d)

**Comment by iamwwc** [comment]
does have any progress

**Comment by meganrogge** [comment]
https://github.com/microsoft/vscode/blob/3fb1091bf57d8c11c828ac54337a5783d5226e91/src/vs/workbench/contrib/tasks/browser/abstractTaskService.ts#L1378

I think you can set this when you run the task - select `never` here

**Comment by meganrogge** [comment]
lmk if that does not work for you

**Comment by taikulawo** [comment]
@meganrogge 
![image](https://github.com/microsoft/vscode/assets/24750337/8a7fe446-fb2d-40cc-aa3e-15d3e9d24386)
not work
