### ISSUE TITLE
Tasks using `"runOn": "folderOpen"` are broken

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#193475]
* have a task with `"runOn": "folderOpen"`, like https://github.com/microsoft/vscode-github-issue-notebooks/blob/e017704a5eb4bb6080322a3d489c76d421089111/.vscode/tasks.json#L18
* make sure it ran once
* reload/reopen folder
* 🐛 task doesn't run

**Comment by meganrogge** [comment]
do you have task reconnection enabled?

**Comment by Hyperclaw79** [comment]
@meganrogge Not sure if this is related but Google Cloud Code's terminal contribution stopped working at the same time as this issue. Please guide me on how I can validate if the issues are unrelated (in which case, I'll open an issue on the extension repo).

**Comment by meganrogge** [comment]
You can test it in tomorrow's insider's.
