### ISSUE TITLE
1.82.2 on Linux Does Not Load Properly | Shader Errors In Log

### ISSUE THREAD

**Issue by jimbo2150** [microsoft/vscode#193472]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.82.2 (installed via Microsoft vscode repository)
- OS Version: OpenSUSE Tumbleweed 2023-09-15

Steps to Reproduce:

1. Open vscode normally via menu or via command line with no arguments

The main window opens but is just empty rectangles, nothing actually populates other than the file menu at top.

Attached the verbose log file with errors about shaders not working (gzipped as the uncompressed file is 6MB from having the window open for a couple seconds).
This issue occurs in 1.82.2 but not in previous versions.

Disabling extensions does not fix the issue. Running `code --disable-gpu` from command line fixes the issue and the window loads normally.
![vscode-display-bug](https://github.com/microsoft/vscode/assets/25777094/76620083-3741-48af-b7aa-e27e46da5f31)
[vscode.error.tar.gz](https://github.com/microsoft/vscode/files/12662194/vscode.error.tar.gz)

**Comment by gjsjohnmurray** [comment]
Please see https://code.visualstudio.com/updates/v1_82#_update-highlights-for-chromium and try the deletion of GPU cache it recommends.

**Comment by jimbo2150** [comment]
@gjsjohnmurray That fixed it, thanks!

**Comment by foxilated** [comment]
@gjsjohnmurray  That fixed it for me too! thanks
