### ISSUE TITLE
WSL2 mirrored network mode slows VSCode

### ISSUE THREAD

**Issue by BurgerTown** [microsoft/vscode#193436]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.82.2
- OS Version: WIN11 23H2

Steps to Reproduce:

1. Change WSL2 network mode to mirrored
2. Open project that inside WSL2 with VSCode

**Comment by aeschli** [comment]
@BurgerTown I haven't yet been able to look into this issue. Is it resolved?
