### ISSUE TITLE
copied text does not honor line ending setting

### ISSUE THREAD

**Issue by kuhlaid** [microsoft/vscode#193481]
**EDIT**, adding repro steps:

1. set `"files.eol": "\n"`
2. create a new file and add a few lines
3. copy and paste to something that will show hidden characters, e.g. https://www.soscisurvey.de/tools/view-chars.php 
:bug: copied lines end in `/r/n`

**Original post**

There is a problem with copying rendered Jupyter notebook markdown from VsCode into say another notebook within Jupyter Lab (which is running on Linux and expecting LF line ending). Is this a problem with VsCode, I don't think so. I suspect it is an issue with Windows in general. I am using Windows 11 with VsCode (which I doubt is relevant at all):
```
Version: 1.81.1 (user setup)
Commit: 6c3e3dba23e8fadc360aed75ce363ba185c49794
Date: 2023-08-09T22:22:42.175Z
Electron: 22.3.18
ElectronBuildId: 22689846
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Windows_NT x64 10.0.22621
```

I don't know enough about the internal Windows 11 settings for copy and paste but recently I have noticed that if I copy blocks of code from VsCode and paste it into say an Outlook for web email message that it does not simply paste the text from VsCode but also the background from VsCode and the color formatting (below is a example):
![image](https://github.com/microsoft/vscode-jupyter/assets/41551429/637e3b4f-0382-43b6-80e8-8bd79b3101ae)

Why is this a problem? Well Windows is obviously not simply copying the text from VsCode to paste into Outlook (or whatever I am pasting into), but also the background and visual formatting (which is in addition to the text). 

My Jupyter notebook does not have CRLF line endings. The corresponding underlying JSON code for the text above that is copied from VsCode is:

```
    "for i in 1\n",
    "do\n",
    "    sudo mount -t drvfs C: /mnt/c\n",
    "    sudo mount -t drvfs F: /mnt/f\n",
    "    sudo mount -t drvfs G: /mnt/g\n",
    "done\n",
```

However, if I copy this rendered Jupyter markdown over to another Jupyter notebook within Jupyter Lab (which is browser based) Windows seems to have added CRLF line endings to the copied text even though the text in VsCode is NOT CRLF when I copied it. Below is the process captured in a screenshot (low res):

https://github.com/microsoft/vscode-jupyter/assets/41551429/e4b00817-4212-4e24-8814-222ac9a245ad

The resulting text as pasted in the other notebook is (notice the added `\r`):

```
    "for i in 1\r\n",
    "do\r\n",
    "    sudo mount -t drvfs C: /mnt/c\r\n",
    "    sudo mount -t drvfs F: /mnt/f\r\n",
    "    sudo mount -t drvfs G: /mnt/g\r\n",
    "done"
```

Again, this does not feel like a VsCode issue but maybe VsCode has some control over this (I have no idea). There is a separate bug logged in JupyterLab regarding notebook corruption as a result of this copy and paste issue, which is super annoying - https://github.com/jupyterlab/jupyterlab/issues/14752.

**Comment by bberto** [comment]
I think this behaviour was introduced by https://github.com/microsoft/vscode/issues/22688.
IMHO there should be a preference to switch-off automatic LF->CRLF conversion on Windows when copying content.
