### ISSUE TITLE
Feature Request [Editor] [Preview] with different Themes

### ISSUE THREAD

**Issue by konqui** [Microsoft/vscode#19350]
Feature Request

It would be nice to have the possibility to select two different themes for the Editor and the Preview.
Even better it would be if you can set this on a per Language Base.

I d' like to use my Editor always set to dark theme but the preview i'd like to have in light mode.
Espacially for Markdown

**Comment by mjbvz** [comment]
You can use the `markdown.styles` setting to use any CSS to customize the markdown preview: https://code.visualstudio.com/Docs/languages/markdown#_using-your-own-css

Take a look at how we do styling for the light theme for the markdown preview [here](https://github.com/Microsoft/vscode/blob/master/extensions/markdown/media/markdown.css) for help writing your own style  (just look for any rules that use `.vscode-light`)


Other extensions that provide a preview would be responsible for providing their own styling mechanisms.
