### ISSUE TITLE
Feature requests for Test Result panel

### ISSUE THREAD

**Issue by eleanorjboyd** [microsoft/vscode#193589]
As python moves to use the Test Result panel, there are a few feature requests I thought might make the experience better. Open to your thoughts / feedback as I don't understand all the use cases for this panel! Thanks

1. When you click on a test that has succeeded there is no change in the display, this felt confusing to me because it doesn't signal to the user that there was no output from this test. It also may make people may get mixed up because in the list the successful test is highlighted but the output shown is from a failed test.

https://github.com/microsoft/vscode/assets/26030610/c085a796-9a32-437c-83fc-c6bd8653bfaf

2. ✅ (complete) The output in the test result panel is not searchable when you have the test run dropdown selected. I think our users  would value being able to search through this output

when I press cmd+F with the different test header selected I get a search box from one but not the other
<img width="1564" alt="image" src="https://github.com/microsoft/vscode/assets/26030610/ac6f26df-12cc-4996-8afa-28e00d0b0899">
<img width="1572" alt="image" src="https://github.com/microsoft/vscode/assets/26030610/4c911229-1cef-4ea6-a615-43470e6e7afc">

3. I found myself frequently wanting to click on a single test then go back to the whole test run output. I kept getting confused when clicking on the Test Run item in the list collapsed the block vs open the output. This is just different from the individual tests which clicking on them loads their output. I know you can right-click on the TestRun to get back there but it is not very discoverable. (resolved)
<img width="1102" alt="image" src="https://github.com/microsoft/vscode/assets/26030610/72c62187-7b72-4d75-bfec-7b54945aec7c">

**Comment by connor4312** [comment]
> I found myself frequently wanting to click on a single test then go back to the whole test run output. I kept getting confused when clicking on the Test Run item in the list collapsed the block vs open the output. This is just different from the individual tests which clicking on them loads their output. I know you can right-click on the TestRun to get back there but it is not very discoverable.

You can also click the "terminal" icon in the inline actions. There's not a great way to handle this without making it hard to figure out how to collapse/expand the item.

**Comment by eleanorjboyd** [comment]
Ah yes, that makes sense I missed that icon initially. Thanks

**Comment by connor4312** [comment]
The find widget (2) is now available in the Test Results terminal

**Comment by connor4312** [comment]
@eleanorjboyd the find widget always worked in the former case where we show a text editor. Can you confirm that you're on the latest version of VS Code Insiders?

**Comment by eleanorjboyd** [comment]
hm yeah I am seeing it now- sorry about that I am not sure what was wrong. Thanks

**Comment by connor4312** [comment]
This is only currently on VS Code Insiders.

**Comment by connor4312** [comment]
We should release to stable in 6-7 days https://github.com/microsoft/vscode/issues/198893

**Comment by connor4312** [comment]
# 1 is what I fixed in my last PR. We now show the message/output associated with a successful test, if any, otherwise we show that there was no output

**Comment by eleanorjboyd** [comment]
Thanks again for these fixes it looks great!
