### ISSUE TITLE
`terminal.integrated.automationProfile.windows` not working at all

### ISSUE THREAD

**Issue by RalfReddings** [microsoft/vscode#193595]
Does this issue occur when all extensions are disabled? Yes

- VS Code Version: 1.78.1 (user setup)
- OS Version:  Windows 11

Steps to Reproduce:

1. configure `terminal.integrated.automationProfile.windows` setting as shown below
2. with no terminal open, start a debugging session
3. the newly spawned debugging terminal does not respect the  `terminal.integrated.automationProfile.windows` setting.

I want to pass command line arguments to the shell the debugger terminal is about to use (PowerShell). The documentation, [Configuring the task/debug profile](https://code.visualstudio.com/docs/terminal/profiles#_configuring-the-taskdebug-profile), states I can use the key, `terminal.integrated.automationProfile.<platform>` to do this. 

This simply does not seem to work at all, I have tried several different set ups (fresh code, different machines etc), nothing works. 

All extensions are disabled accept for The **PowerShell-ms** extension (version `2023.6.0`), in order to demonstrate this issue.

If in my user settings I only have the following:
```
{
 "terminal.integrated.automationProfile.windows": {
	  
	  "path": "C:\\Program Files\\PowerShell\\7\\pwsh.exe",
	  "args": [
			"-noexit",
		 "-command",
		 "Get-ChildItem",     //I know this makes no sense, its just for an example
	]
  },
}
```
and a single config in my `launch.json` file:
```
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "PowerShell: Launch Current File",
            "type": "PowerShell",
            "request": "launch",
            "script": "${file}",
            "args": []
        }
    ]
}
```

With no terminals open, starting a debugging session with the active file, `shell.ps1` spawns a new terminal but it is run as if the setting `terminal.integrated.automationProfile.windows` is not in place:

![](https://i.imgur.com/Jy3rV2D.png)

In fact, entirely different command line arguments are being passed to the PowerShell executable, as shown here:

![](https://i.imgur.com/SZtggyr.png)

I have run into this issue with the Python-ms Debugger and PowerShell-ms Debugger.

With the standard Code terminal I can pass command line arguments to its PowerShell executable like this, and it works as shown [HERE](https://i.imgur.com/s4l2fW0.png):

```swift
"terminal.integrated.profiles.windows": {
 "General": {
    "path": "C:\\Program Files\\PowerShell\\7\\pwsh.exe",
    "args": [
        "-noexit",
      "-command",
      "Get-ChildItem",
  ]
 }
}
```

# VSCode information 
```
Version: 1.78.1 (user setup)
Commit: 6a995c4f4cc2ced6e3237749973982e751cb0bf9
Date: 2023-05-04T09:48:08.683Z (4 mos ago)
Electron: 22.5.1
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Windows_NT x64 10.0.22621
Sandboxed: No
```
# System information
```
CPUs	AMD Ryzen 9 5950X 16-Core Processor (32 x 3400)
GPU Status	2d_canvas: enabled canvas_oop_rasterization: disabled_off direct_rendering_display_compositor: disabled_off_ok gpu_compositing: enabled multiple_raster_threads: enabled_on opengl: enabled_on rasterization: enabled raw_draw: disabled_off_ok video_decode: enabled video_encode: enabled vulkan: disabled_off webgl: enabled webgl2: enabled webgpu: enabled
Load (avg)	
Memory (System)	127.93GB (98.70GB free)
Screen Reader	no
VM	0%
```
# A/B experiment info
```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
vsccc:30803844
3biah626:30602489
f6dab269:30613381
a9j8j154:30646983
showlangstatbar:30737416
a2ce3375:30757347
pythonfmttext:30731395
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
pythonnosmt12:30797651
pythonidxpt:30805730
pythonnoceb:30805159
asynctok:30821568
dsvsc013:30795093
dsvsc014:30804076
diffeditorv1:30821571
dsvsc015:30829745
```

**Comment by Tyriar** [comment]
@roblourens @connor4312 does debugging respect the automation shell? I'm pretty sure it did in the past if not.

This is where tasks uses it for example:

https://github.com/microsoft/vscode/blob/5a031b7f040363a3039da6cd9e4b80326c43d015/src/vs/workbench/contrib/tasks/browser/terminalTaskSystem.ts#L1086-L1090

**Comment by roblourens** [comment]
I think something is wrong, we ask for the automation profile here https://github.com/microsoft/vscode/blob/main/src/vs/workbench/api/node/extHostDebugService.ts#L85

and I set

```
"terminal.integrated.automationProfile.osx": {
  "path": "/bin/bash",
},
```

but that profile isn't returned, I get the default zsh profile. Am I missing something?

**Comment by Tyriar** [comment]
@roblourens do you have a simple launch.json that I could test this against that doesn't use the pwsh extension?

I see tasks is working fine:

```json
  "terminal.integrated.automationProfile.windows": {
	  "path": "C:\\Users\\Daniel\\AppData\\Local\\Microsoft\\WindowsApps\\Microsoft.PowerShell_8wekyb3d8bbwe\\pwsh.exe",
	  "args": [
			"-noexit",
		  "-command",
		  "Get-ChildItem",     // I know this makes no sense, its just for an example
	  ]
  },
```

![image](https://github.com/microsoft/vscode/assets/2193314/aa0cbadf-a348-40fe-bcaa-ef812a7f3c38)

**Comment by roblourens** [comment]
I just used something like this

```
{
"name": "Run",
"type": "node",
"request": "launch",
"program": "${file}",
"console": "integratedTerminal",
},
```

**Comment by Tyriar** [comment]
The automation profile on the ext host doesn't have the args in it:

![image](https://github.com/microsoft/vscode/assets/2193314/fd514cbc-02ee-4d69-9060-3242d6069a92)

**Comment by Tyriar** [comment]
Looks like we just don't react to changes when automation profile changes, updating the default profile after setting the automation profile will trigger the update and then work properly.

**Comment by RalfReddings** [comment]
@RalfReddings  Hello, looks like this issue got completed. I am not very familiar with Github. Is it safe to assume that the fix will be present in the next VSCode update? Also thank you both for working on this, I really appreciate it.

**Comment by Tyriar** [comment]
@RalfReddings we're just about to release 1.83 and it won't be in that one unfortunately, it'll be shipped in a month to VS Code, or in a few days to [VS Code insiders](https://code.visualstudio.com/insiders/).

**Comment by RalfReddings** [comment]
Okay, got it!
