### ISSUE TITLE
inline values do not work with mono-debug

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#19358]
While testing #18670:

Mono debug combines the variable type and name in the Variable's 'name' attribute. This seems to prevent the 'inline values' feature from finding values for variables.

Since variable hovers work (and they rely on the same lookup mechanism), it seems that the 'inline values' feature does not use the same code.

**Comment by isidorn** [comment]
@weinand the current implementation on the vscode side feels like a hack, namely the debug hover looks for the last word in the name of the variable and that matches that agains the text that is being hovered over. I agree that we should use the same heuristics between the hover and inline variables, but what feels like a better solution to me is that mono debug should return the `type` as part of the [`type`](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/debug/common/debugProtocol.d.ts#L1122) argument in the variable and not as part of the name.

If this is not possible then I can look into sharing the hacky heuristic between hover and inline values - though I would prefer to remove it from both places.

**Comment by weinand** [comment]
@isidorn that makes sense.

**Comment by isidorn** [comment]
@weinand great. Once mono debug starts supporting this I can remove the hacky heuristic on the vscode side.

**Comment by weinand** [comment]
@isidorn do you know whether any other debug extension uses the same approach as mono-debug?

**Comment by isidorn** [comment]
@weinand I do not know of any other extension that uses this approach.

**Comment by weinand** [comment]
fixed.
The latest mono-debug from the Marketplace (v0.13.0) shows inline values.

**Comment by isidorn** [comment]
@weinand great!

**Comment by isidorn** [comment]
Verified by code review of https://github.com/Microsoft/vscode-mono-debug/commit/d85fe27ccc085aba08d3ee3c928b78a93d1a3e22 and by understanding how inline values are computed and what was the initial issue
