### ISSUE TITLE
Launching VSCode from WSL2 CLI causes `code` to block the terminal

### ISSUE THREAD

**Issue by briceo** [microsoft/vscode#193537]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.82.2
- OS Version: Windows 11 22H2 (Build 22621.2283)

Steps to Reproduce:

1. Install VSCode 1.82.2
2. Run `code .` from a WSL2 instance (I was using Windows Terminal)
3. the CLI instance is blocked until the VSCode window that was launched is closed
4. Running `code .` from a windows command prompt works as expected (meaning the VSCode windows launches, and the command prompt returns back to the prompt to run other commands).
5. Downgrading to 1.82.0 and the problem goes away.

**Comment by jedmallen** [comment]
I'm getting the same issue. Even uninstalled/deleted all extensions, reinstalled vscode in WSL2.
Will downgrade for now.
