### ISSUE TITLE
Build status indicators are not appearing in status bar

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#193556]
I did a window reload (without terminals being visible), using latest insiders:

![Image](https://github.com/microsoft/vscode/assets/900690/15c8abe8-152c-4eb4-b048-7cea862ca936)

```
ERR Unexpected token 'i', "file:///Use"... is not valid JSON: SyntaxError: Unexpected token 'i', "file:///Use"... is not valid JSON
    at JSON.parse (<anonymous>)
    at x.bc (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1926:10965)
    at x.getSavedTasks (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1926:11391)
    at x.Ib (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1926:3589)
    at vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1926:3537
```

**Comment by meganrogge** [comment]
I'm not seeing that error, and am seeing them in the status bar, but can reproduce them not showing up on the terminal tabs.
<img width="1207" alt="Screenshot 2023-09-20 at 8 14 47 AM" src="https://github.com/microsoft/vscode/assets/29464607/ca1230d0-fd3d-49d9-9c22-c87db074addd">

Uploading status.mov…

**Comment by meganrogge** [comment]
@bpasero did they statuses happen eventually for you? at first, I thought I could repro this. The status bar indicator ultimately appeared for me, as did one of the statuses. 

@Tyriar has reported seeing this before where the one for the `Ext - Build` isn't applied

<img width="1230" alt="Screenshot 2023-09-20 at 8 16 02 AM" src="https://github.com/microsoft/vscode/assets/29464607/6f0fe3a4-0a06-4409-ba25-fbed86512e46">

**Comment by meganrogge** [comment]
if you can reproduce, a gif would be helpful 🙏🏼

**Comment by bpasero** [comment]
Cannot repro now, but I am sure I miss a step. These issues are incredibly hard for me to figure out the root cause, can we just add some `logService.info` temporary so that I can share logs next time?

**Comment by meganrogge** [comment]
Tasks doesn't use a log service currently. I tried to add that this iteration and couldn't get some tests to pass. ATM, it just uses the output service which doesn't have log level. #192195

**Comment by meganrogge** [comment]
If you have difficulty reproducing, that is a good thing, so it mustn't happen very frequently. I'll try to reproduce it again in October.

**Comment by meganrogge** [comment]
there's also the issue of the statuses not appearing on the tabs there. that will be fixed by this and will provide information for us https://github.com/microsoft/vscode/pull/193598

**Comment by bpasero** [comment]
@meganrogge could the stacktrace of the error at all be related?

Here are some details about my setup:
* always in a multi-root workspace with `vscode`, `vscode-docs` and `vscode-distro`
* always on macOS
* always running the build task via keybinding (`workbench.action.tasks.build`)
* often rerunning the build task [1]
* very often reloading the window with terminal panels hidden

[1]

```
{
    "key": "cmd+shift+alt+b",
    "command": "workbench.action.tasks.runTask",
    "args": "Restart VS Code - Build"
}
```

**Comment by meganrogge** [comment]
I never use `Restart VS Code - Build` so that could be related

**Comment by bpasero** [comment]
Error stack trace:

```
ERR Unexpected token 'i', "file:///Use"... is not valid JSON: SyntaxError: Unexpected token 'i', "file:///Use"... is not valid JSON
    at JSON.parse (<anonymous>)
    at x.bc (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1926:10965)
    at x.getSavedTasks (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1926:11391)
    at x.Ib (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1926:3589)
    at vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1926:3537
```

I had then opened the `tasks.json` and could not find an error.

**Comment by meganrogge** [comment]
that error would be coming from here. Maybe somehow bad data gets stored then we try to parse it?... https://github.com/microsoft/vscode/blob/fa08b9aa6065873a9e458dc0fae368d9999132ae/src/vs/workbench/contrib/tasks/browser/abstractTaskService.ts#L1009

**Comment by bpasero** [comment]
I am able to reproduce and it seems to be a file string trying to be parsed as JSON: https://github.com/microsoft/vscode/issues/193974

**Comment by meganrogge** [comment]
I believe something was stored incorrectly for you. I noticed that the task map was not getting cleared on disabling persistence, addressed here #194509. Once insiders reflects the latest on main, could you pls disable reconnection, re-enable it (clearing the cache), and see if you can repro?

**Comment by meganrogge** [comment]
Just tried to reproduce with your keybinding above, reloading the window a few times, hiding the panel, and nothing

**Comment by bpasero** [comment]
https://github.com/microsoft/vscode/issues/193974 reproduces even with latest after toggling reconnection.

**Comment by meganrogge** [comment]
@bpasero can you reproduce after my fix?

**Comment by bpasero** [comment]
I think `Unexpected token` no longer happens for me.

**Comment by meganrogge** [comment]
Pls reopen if you can reproduce it and provide the logs. Thanks
