### ISSUE TITLE
Wrong padding in suggest widget in notebook

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#193597]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.83-Insiders
- OS Version: macOS

* Reload VS Code
* Open a notebook
* Cmd+I

![Image](https://github.com/microsoft/vscode/assets/876920/eda7ce8b-57dd-46d6-a46e-1b70a9c08624)

![Image](https://github.com/microsoft/vscode/assets/876920/1fb5839b-0d5f-43b8-9f09-2b4666e65a53)

**Comment by Yoyokrazy** [comment]
no longer can repro + inline widget redesign
