### ISSUE TITLE
My run and debug doesnt work

### ISSUE THREAD

**Issue by elliotwatt** [microsoft/vscode#193535]
Type: <b>Bug</b>

Everytime I hit f5 or manually hit run or debug, literally nothing happens. I'm trying to work here but it won't work.

VS Code version: Code 1.82.2 (abd2f3db4bdb28f9e95536dfa84d8479f1eb312d, 2023-09-14T05:55:25.390Z)
OS version: Windows_NT x64 10.0.22621
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|12th Gen Intel(R) Core(TM) i5-12600K (16 x 3686)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.75GB (24.60GB free)|
|Process Argv|--crash-reporter-id 56a860db-a34c-45fb-a454-61f84df17332|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
code-runner|for|0.12.0
intellij-idea-keybindings|k--|1.5.10
rainbow-csv|mec|3.7.1
data-workspace-vscode|ms-|0.5.0
mssql|ms-|1.20.1
sql-bindings-vscode|ms-|0.4.0
sql-database-projects-vscode|ms-|1.2.0
python|ms-|2023.16.0
vscode-pylance|ms-|2023.9.10
jupyter|ms-|2023.8.1002501831
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.17
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-slideshow|ms-|0.1.5
r|REd|2.8.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
py29gd2263:30792226
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
282f8724:30602487
89544117:30613380
a9j8j154:30646983
showlangstatbar:30737416
0bi6i642:30841073
03d35959:30757346
57b77579:30736110
pythonfmttext:30731395
f8hc8238:30694864
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
pythonnosmt12:30797651
pythonidxpt:30805730
pythonnoceb:30805159
copilotsettingc:30839828
synctok:30821570
dsvsc013:30795093
dsvsc014:30804076
diffeditorv1:30821571
dsvsc015cf:30829746

```

</details>

**Comment by roblourens** [comment]
What langauge? Do you have a launch.json set up? Any output or anything show up in the debug console or terminal?

**Comment by mauriciotozo** [comment]
The same problem happens here with this version and xdebug php. No message appears just doesn't work. I can verify that port 9000 is in use after pressing f5 but it doesn't work

**Comment by roblourens** [comment]
Sounds like the debug extension was called and the app was started, so please file an issue on the repo for the debug extension that you're using, thanks
