### ISSUE TITLE
Rendering issue

### ISSUE THREAD

**Issue by Redhawk18** [microsoft/vscode#193519]
Does this issue occur when all extensions are disabled?: Yes

Version: 1.82.0
Commit: 8b617bd08fd9e3fc94d14adb8d358b56e3f72314
Date: 2023-09-06T22:07:18.759Z
Electron: 25.8.0
ElectronBuildId: 23503258
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Linux x64 6.5.3-1-default

Steps to Reproduce:
1. Open vscode on OpenSuse linux

**Comment by gjsjohnmurray** [comment]
Please see https://code.visualstudio.com/updates/v1_82#_update-highlights-for-chromium and try the deletion of GPU cache it recommends.

**Comment by Redhawk18** [comment]
that fixed it
