### ISSUE TITLE
Mouse hover on a file path and press "Command + click" can't go to source definition

### ISSUE THREAD

**Issue by BernardZhang** [microsoft/vscode#193557]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 
-  1.82.2 (Universal)
- OS Version: 
- macOS Ventura 13.2

Steps to Reproduce:

1. Open a index.js file which content looks like below:
```js
import { get } from './utils';

console.log(get({ name: 'Hello' }, 'name'))
```
2. Mouse hover on './utils' and press 'Command+click'; expect: jump to 'utils.js' file but actually not
![image](https://github.com/microsoft/vscode/assets/3273449/750d85f2-09ca-4704-8d02-1745621c299c)

**Comment by BernardZhang** [comment]
If modify the index.js and utils.js files to index.ts and utils.ts, this feature works fine.

**Comment by mjbvz** [comment]
Did you just recently rename these files from `index.ts` to `index.js`? 

Also what happens if you right click on the path and run the `go to definition`

**Comment by BernardZhang** [comment]
@mjbvz 
1. I just rename index.js to index.ts then "Command + click" work fine.
2. Right click then click "Go to Source Definition" in context menu, this work fine in ts and js.
3. I also checked the Keyboard Shortcuts "Go to Source Definition" keybinding which is empty and same as my friend's config but this feature work fine on his macbook(VScode version is the same with mine, the difference is macOS version and chip).

**Comment by BernardZhang** [comment]
@mjbvz 
1. I just rename index.js to index.ts then "Command + click" work fine.
2. Right click then click "Go to Source Definition" in context menu, this work fine in ts and js.

Other info from my two colleagues
Colleague A: macbook apple chip M2, vscode 1.82.2 (same as mine), "Command + click" also not working in js.
Colleague b: mocbook intel chip, vscode 1.82.2 (vsocode is the same, and chip is different), this feature work fine on his computer.
 
4. I also checked the Keyboard Shortcuts "Go to Source Definition" keybinding which is empty and same as my two colleague's vscode config but this feature work fine on his macbook(VScode version is the same with mine, the difference is macOS version and chip).

**Comment by mjbvz** [comment]
What about running `go to definition` from the command palette or right click menu? (not `go to source definition`)

**Comment by BernardZhang** [comment]
@mjbvz go to definition also not working in js but working in ts.

**Comment by BernardZhang** [comment]
@mjbvz I find vscode-flow-ide extension cause break the go to source definition feature, after I disabled the extension "go to definition and source definition" features both ok now. Thanks for your pation:)
