### ISSUE TITLE
[Feature Request] Add workbench action to split editor terminal below

### ISSUE THREAD

**Issue by lcrownover** [microsoft/vscode#193596]
I currently have the following actions available:

```
workbench.action.createTerminalEditor
workbench.action.createTerminalEditorSameGroup
workbench.action.createTerminalEditorSide
```

I'd like to be able to split an editor terminal below. It seems like the UI can do this, because I can drag a terminal editor below another and have a horizontal split:

<img width="1624" alt="image" src="https://github.com/microsoft/vscode/assets/15133041/9694066a-e177-404b-8b1e-e3337a57fc90">

So I would love to have a `workbench.action.createTerminalEditorBelow` action to split it below 😊

**Comment by Tyriar** [comment]
You can actually use the split editor group below command for this, provided you have a terminal focused: `workbench.action.splitEditorToBelowGroup`

**Comment by Tyriar** [comment]
> but sometimes don't count as editors.

@lcrownover can you elaborate a little more on this? Do you just mean some keybindings don't work because they would conflict with shell keybindings, for example ctrl+w is sent to the shell? The `terminal.integrated.commandsToSkipShell` setting is available to configure that as the right behavior differs from person to person.

**Comment by lcrownover** [comment]
Sure, I think my confusion comes from the difference between an editor terminal and the panel terminal. Specifically, the `when` conditions. 

For example, is an editor terminal considered `terminalFocus` or `editorFocus`? It seems like it's `terminalFocus`, because I have a keybinding that kills the active terminal session in the panel:

`{ "key": "cmd+w", "command": "workbench.action.terminal.kill", "when": "terminalFocus" },`

However, this keybinding does not work with an editor terminal. I'm assuming this is something where the editor terminals don't support multiple sessions like the panel terminal does, but then how do I have a common keybinding to close the focused editor terminal or focused panel terminal session? Probably using some more conditions, but I haven't found a good way to discover these other than `cmd+f` through the default keyboard shortcuts json file.

Also, it turns out that it'd still be useful to have a `workbench.action.createTerminalEditorBelow` because the `splitEditorToBelowGroup` command will split whatever is current, be it an editor, or a terminal, so I'm unable to create a new terminal below an existing editor (assuming this editor is a text editor, not a terminal editor [see confusion above 😊])

**Comment by Tyriar** [comment]
`terminalFocus` applies to any. You can use `activeEditor == 'terminalEditor'` and `editorFocus` to determine if the terminal editor is  the focused one, similar to determining other editor types. There's some documentation on the context keys available at https://code.visualstudio.com/api/references/when-clause-contexts#available-context-keys, not sure if we have examples on doing more complex keybindings like this.

> Also, it turns out that it'd still be useful to have a workbench.action.createTerminalEditorBelow because the splitEditorToBelowGroup command will split whatever is current, be it an editor, or a terminal, so I'm unable to create a new terminal below an existing editor (assuming this editor is a text editor, not a terminal editor [see confusion above 😊])

My concern is that it's not sustainable to do this for every editor type. For example there is no split _text_ editor below (or notebook, etc.). I think what you're after can be done by linking commands together via the `runCommands` command:

```json
{
	"key": "ctrl+shift+alt+down",
	"command": "runCommands",
	"args": {
		"commands": [
			"workbench.action.focusBelowGroup",
			"workbench.action.createTerminalEditor"
		]
	}
},
```
