### ISSUE TITLE
August 2023 x64 user setup executable VSCodeUserSetup-x64-1.82.2.exe breaks extension 'PowerShell v2023.6.0' from microsoft.com (Windows 10 x64)

### ISSUE THREAD

**Issue by ShaunMitchellPRBUK** [microsoft/vscode#193526]
Does this issue occur when all extensions are disabled?: No

- VS Code Version: VSCodeUserSetup-x64-1.82.2.exe
- OS Version: Microsoft Windows [Version 10.0.19045.3448]

Steps to Reproduce:

1. Install latest (August 2023) x64 user setup executable VSCodeUserSetup-x64-1.82.2.exe.
2. Install extension 'PowerShell  v2023.6.0' from microsoft.com
3. Watch the extension crash when trying to use PowerShell features with a PoSh script.
4. Uninstall VSCodeUserSetup-x64-1.82.2.exe.  
5. Re-install previous VSCode (July 2023) x64 user setup executable VSCodeUserSetup-x64-1.81.1.exe.
6. Install extension 'PowerShell v2023.6.0' from microsoft.com and the PowerShell extension features work with a PoSh script.
7. Goto 1 to repeat the process and outcomes.

**Comment by lszomoru** [comment]
@ShaunMitchellPRBUK, please reach out to the extension author to investigate this issue. Thank you!
