### ISSUE TITLE
Terminal only offers 8 bit color

### ISSUE THREAD

**Issue by lunndal** [microsoft/vscode#193562]
Type: <b>Bug</b>

When I disable or uninstall the PowerShell extension, choose *any* PowerShell Terminal Default Profile and restart VS Code, the terminal only displays 8 bit color when running the supplied test script. When running the same script in the Windows PowerShell terminal, outside of VS Code, the result is as expected.

_Edit: I'm running VS Code and the external PowerShell window inside a Remote Desktop session. It does not seem to matter for the external window, but maybe it bears an impact on how VS Code handles colors?_

**Colors in use**
```
$ wmic path Win32_VideoController get VideoModeDescription
VideoModeDescription
1250 x 1188 x 4294967296 colors
```

_(Edit2: Screenshot corrected. Thanks @Tyriar)_
![image](https://github.com/microsoft/vscode/assets/121591464/91552265-da09-4055-b51e-976f209742fc)

**Code to test**
```
$esc = "$([char]0x1b)"
$out = (232..255) | ForEach-Object { "$esc[48;5;$($_)m $esc[0m" }
$out -join ""
```

**settings.json**
```
{
    "http.proxy": "http://aaa.bbb.ccc:NNNN",
    "http.proxyAuthorization": null,
    "http.proxyStrictSSL": false,
    "editor.minimap.enabled": false,
    "terminal.integrated.tabs.enabled": false,
    "terminal.integrated.enableMultiLinePasteWarning": true,
    "terminal.integrated.localEchoStyle": "dim",
    "workbench.colorTheme": "Visual Studio Dark",
    "terminal.integrated.minimumContrastRatio": 1,
    "terminal.integrated.profiles.windows": {
        "PowerShell": {
            "source": "PowerShell",
            "icon": "terminal-powershell"
        },
        "Command Prompt": {
            "path": [
                "${env:windir}\\Sysnative\\cmd.exe",
                "${env:windir}\\System32\\cmd.exe"
            ],
            "args": [],
            "icon": "terminal-cmd"
        },
        "Git Bash": {
            "source": "Git Bash"
        },
        "Windows PowerShell": {
            "path": "C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe"
        }
    },
    "terminal.integrated.defaultProfile.windows": "PowerShell",
    "terminal.integrated.gpuAcceleration": "off"
}
```

VS Code version: Code 1.82.2 (abd2f3db4bdb28f9e95536dfa84d8479f1eb312d, 2023-09-14T05:55:25.390Z)
OS version: Windows_NT x64 10.0.17763
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) Gold 6240 CPU @ 2.60GHz (2 x 2594)|
|GPU Status|2d_canvas: unavailable_software<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: disabled_software<br>multiple_raster_threads: disabled_off<br>opengl: disabled_off<br>rasterization: disabled_software<br>raw_draw: disabled_off_ok<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software<br>webgpu: unavailable_software|
|Load (avg)|undefined|
|Memory (System)|8.00GB (1.61GB free)|
|Process Argv|--crash-reporter-id a9d6709a-eae5-4b26-98ad-c63feee23ee3|
|Screen Reader|no|
|VM|100%|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
xml|Dot|2.5.1
markdown-all-in-one|yzh|3.5.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
py29gd2263:30792226
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
3biah626:30602489
f6dab269:30613381
2i9eh265:30646982
showlangstatbar:30737416
0bi6i642:30841073
03d35959:30757346
7ij38806:30736111
pythonfmttext:30731395
9b8hh234:30694863
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
pythonnosmt12:30797651
pythonidxptcf:30805731
pythonnoceb:30805159
copilotsettingc:30839828
dsvsc013:30795093
dsvsc014:30804076
diffeditorv2:30821572
dsvsc015:30829745

```

</details>

**Comment by Tyriar** [comment]
The screenshot shows you're using the PowerShell extension here, not a regular powershell terminal. Does it all work fine if you create it using standard pwsh?

![image](https://github.com/microsoft/vscode/assets/2193314/f933c1c7-f75f-42e5-93aa-e7a962a22c8d)

**Comment by lunndal** [comment]
> The screenshot shows you're using the PowerShell extension here, not a regular powershell terminal. Does it all work fine if you create it using standard pwsh?

Thanks for taking the time to reply. I seem to have attached the wrong screenshot. As mentioned I disabled the PowerShell Extension and the result comes out the same with or without the extension. 

Here is the correct screenshot:
![image](https://github.com/microsoft/vscode/assets/121591464/10a7ad6c-fb0b-48e1-b6eb-9533b7cad4e5)

**Comment by lunndal** [comment]
Sure thing!

[terminal.log](https://github.com/microsoft/vscode/files/12684577/terminal.log)

**Comment by Tyriar** [comment]
I see this line:

```
2023-09-21 14:37:55.521 [debug] [15782cd] parsing data "  [0;37;40;100m              [0;37;47;8m      [0;7m  [0m[0K[?25l
```

This ends up running essentially this:

```pwsh
Write-Host "  `e[0;37;40;100m              `e[0;37;47;8m      `e[0;7m  `e[0m"
```

![image](https://github.com/microsoft/vscode/assets/2193314/a2d8ed14-ec91-479e-89e3-f1b1905198bb)

I was just writing up a detailed explanation of how to look into this but then I realized you're on an old version of Windows 10. Unfortunately that version of Windows does not ship conpty which is the new, much improved pty emulator developed by the Windows Terminal team:

![image](https://github.com/microsoft/vscode/assets/2193314/a5c7cb40-942b-403f-998a-09f37c7485f9)

You will need up upgrade Windows to fix this as we depend on the OS component.

**Comment by lunndal** [comment]
There might be some misunderstanding here. I'm on Windows Server 2019 Standard (10.0.17763 Build 17763), as the screenshot in the OP shows. Also, in the screenshot you can see that the Windows PS Terminal in the OS, _outside of VS Code_, does not have this problem.

**Comment by Tyriar** [comment]
@lunndal that's expected, it works in Windows Terminal because they ship their own version of conpty in product, separate to the one distributed with Windows. We would like to do the same but they don't ship a package yet that we can embed (tracked in https://github.com/microsoft/node-pty/issues/490)

**Comment by lunndal** [comment]
I see. But is conpty enabled terminal supporten in VS Code on Windows Server 2019 Standard (10.0.17763 Build 17763), as I am running?

**Comment by Tyriar** [comment]
@lunndal it's only available in build 18309+, and that's also quite an old version as this point

**Comment by lunndal** [comment]
Thanks for your help, @Tyriar. Upgrade it is then.
