### ISSUE TITLE
UriError when doing a project search

### ISSUE THREAD

**Issue by matthieubal** [microsoft/vscode#193515]
Type: <b>Bug</b>

When trying to use the project search, an error message appears that '[UriError]: If a URI contains an authority component, then the path component must either be empty or begin with a slash ("/") character'. Also without plugins loaded this happens. Project search works fine in other projects and used to in this specific project too.

VS Code version: Code 1.82.2 (abd2f3db4bdb28f9e95536dfa84d8479f1eb312d, 2023-09-14T05:55:25.390Z)
OS version: Windows_NT x64 10.0.19045
Modes:
Remote OS version: Linux x64 4.18.0-477.21.1.el8_8.x86_64
Remote OS version: Linux x64 4.18.0-477.21.1.el8_8.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz (16 x 2496)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.71GB (1.14GB free)|
|Process Argv|--crash-reporter-id 623a1c16-d7a7-4ec9-9ab1-b4a2ee37480a|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: 192.168.200.3|
|OS|Linux x64 4.18.0-477.21.1.el8_8.x86_64|
|CPUs|11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz (12 x 2495)|
|Memory (System)|21.06GB (9.54GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|Container radonc-docker-virtual.artifactory-ehv.ta.philips.com/common-images/centos_07/c-compiler-image.gcc10:edge (midposition_docker) @ ssh://192.168.200.3|
|OS|Linux x64 4.18.0-477.21.1.el8_8.x86_64|
|CPUs|11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz (12 x 2495)|
|Memory (System)|21.06GB (9.54GB free)|
|VM|0%|
</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
project-manager|ale|12.7.0
remote-containers|ms-|0.309.0
remote-ssh|ms-|0.106.4
remote-ssh-edit|ms-|0.86.0
remote-explorer|ms-|0.4.1
vscode-markdownlint|Dav|0.51.0
cmake-tools|ms-|1.15.31
cpptools|ms-|1.17.5
cpptools-extension-pack|ms-|1.3.0
cmake|twx|0.0.17
clang-format|xav|1.9.0

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
282f8724:30602487
f6dab269:30613381
a9j8j154:30646983
showlangstatbar:30737416
962ge761:30841074
03d35959:30757346
pythonfmttext:30731395
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
pythonnosmt12:30797651
pythonidxpt:30805730
pythonnoceb:30805159
copilotsettingc:30839828
synctok:30821570
dsvsc013:30795093
dsvsc014:30804076
diffeditorv2:30821572
dsvsc015cf:30829746

```

</details>

**Comment by roblourens** [comment]
https://github.com/microsoft/vscode/issues/193213
