### ISSUE TITLE
Auto suggestion dialog moving up & down as I navigate between suggestions

### ISSUE THREAD

**Issue by thekalinga** [Microsoft/vscode#19357]
- VSCode Version:

Version 1.9.0-insider
Commit 4265f5e35cb3ea8ba7e0cf6b14ec606b6f8647ea
Date 2017-01-24T10:27:29.525Z
Shell 1.4.6
Renderer 53.0.2785.143
Node 6.5.0

- OS Version:

Ubuntu 14.04

Steps to Reproduce:

Look at the screen cap

![dancing suggestions](https://cloud.githubusercontent.com/assets/452518/22291729/dc85b9cc-e32d-11e6-95ae-c28a35fbffcf.gif)

**Comment by mousetraps** [comment]
Whoaaa 😵 

Unfortunately I can't reproduce the behavior. Does this happen for all completion lists, or just sometimes? Any chance you could share some simple code or zoom/window settings that helps reproduce the issue?

**Comment by alexandrudima** [comment]
The widget changes its height based on the current selection having a doc comment or not. When the current selection has a doc comment, the height of the widget is larger. When the height of the widget is larger, it does not fit under the line. When the height of the widget is smaller, it does fit under the line.

**Comment by joaomoreno** [comment]
#11579

**Comment by thekalinga** [comment]
This did not happen before. This is a one off thing.

Sorry.. I could reproduce it once. But not again.
