### ISSUE TITLE
Items in Problems panel are jumpy and unusable

### ISSUE THREAD

**Issue by ulugbekna** [microsoft/vscode#193566]
# Description 

I click on a problem item/diagnostic (from TS server) in the Problems panel and it jumps up/down, other items disappear or appear in the panel -- everything is very jumpy and hard to use -- see: 

https://github.com/microsoft/vscode/assets/16353531/a57e3479-366d-4f3a-b4a7-2372c43b54f6

I guess this is the TS extension changing diagnostics on files open (cc @mjbvz), but maybe we could do something about the jumpiness in the problems panel

# Version 

```
Version: 1.83.0-insider
Commit: 7c7f7eee860e299499a3bd2915ad716f09f2d6a6
Date: 2023-09-19T08:58:04.117Z
Electron: 25.8.1
ElectronBuildId: 23779380
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Darwin arm64 22.6.0
```

**Comment by sandy081** [comment]
Thanks for sharing the gif. Can you please provide steps to reproduce? It is hard to reproduce the issue by looking at the video.
