### ISSUE TITLE
Add snippets to the terminal

### ISSUE THREAD

**Issue by youra-h** [microsoft/vscode#193547]
I work both in Windows and Ubuntu, and I gradually forget the commands, for example, turning on Wireguard and others. I would like to have a set of grouped commands that could be launched with one click

**Comment by meganrogge** [comment]
You can do this already via our `Run Recent Command` command, which allows pinning of commands.

<img width="703" alt="Screenshot 2023-09-20 at 8 26 18 AM" src="https://github.com/microsoft/vscode/assets/29464607/970db84f-fab3-4991-814c-1c446a793c11">
