### ISSUE TITLE
the same flashing "[D[D" in #180377 back

### ISSUE THREAD

**Issue by clor09** [microsoft/vscode#193637]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version:  
版本: 1.82.2 (user setup)
提交: abd2f3db4bdb28f9e95536dfa84d8479f1eb312d
日期: 2023-09-14T05:55:25.390Z
Electron: 25.8.1
ElectronBuildId: 23779380
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.22621
- OS Version: Windows_NT x64 10.0.22621

Steps to Reproduce:

1. Press Ctrl+` to open terminal panel or anyway to call out it
2. press alt key and hold down, then mouse click at the terminal, you got it

previous issue #180377

**Comment by meganrogge** [comment]
does this still happen if you comment out your settings.json file?

**Comment by clor09** [comment]
> does this still happen if you comment out your settings.json file?

yes, always

**Comment by clor09** [comment]
oh, my shell is pwsh(major version 7) on windows 11 platform.
this wont happen if vscode run in wsl & zsh/bash. but, pwsh in wsl ubuntu will.

**Comment by Tyriar** [comment]
AFAICT this is pwsh and/or conpty misbehaving when receiving these events. If it bothers you I'd recommend just turning the feature off (`terminal.integrated.altClickMovesCursor`) as it's unfortunately inherently unreliable due to how it works.
