### ISSUE TITLE
Opened editors: right-click on close button invokes close

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#19369]
I think we should be in sync with tabs where I just fixed that you can right click on the close button and get the context menu for the editor instead of closing it.

**Comment by isidorn** [comment]
Haha nice revenge bug

**Comment by isidorn** [comment]
The proper fix would be that the actionbar does not handle the right click as the left click - which is currently not the case. So currently all our actions get executed on right click - and I do not think this makes sense
It will be a bigger change -> february

**Comment by bpasero** [comment]
Yeah I was not brave enough to do that change :P

**Comment by isidorn** [comment]
Hopefully this does not break down the world.
Double checked and https://github.com/Microsoft/vscode/issues/1011 seems to work fine even though I removed your code that fixed that.
