### ISSUE TITLE
Shortcut to focus "Message" box in Source Control panel in sidebar

### ISSUE THREAD

**Issue by hollie-w** [microsoft/vscode#193692]
Type: <b>Feature Request</b>

It would be useful to have a keybinding to focus the "Message" box in the Source Control panel in the sidebar. I currently have a shortcut to focus the source control panel, but then I have to manually click the "Message" box to enter a commit message. My workflow would be slightly smoother if I could focus the message box with a keybinding.

VS Code version: Code 1.82.2 (abd2f3db4bdb28f9e95536dfa84d8479f1eb312d, 2023-09-14T05:55:25.390Z)
OS version: Windows_NT x64 10.0.22000
Modes:

**Comment by ArturoDent** [comment]
See https://github.com/microsoft/vscode/issues/131006 It is an open issue, but there may be a workaround there for you.

**Comment by jakelevi1996** [comment]
Thanks! Very useful. Following [this StackOverflow answer](https://stackoverflow.com/a/76886742/8477566) there is a very similar solution which uses `runCommands` instead of requiring an extra extension:

```json
    {
        "key": "ctrl+g",
        "command": "runCommands",
        "args": {
            "commands": [
                "workbench.scm.focus",
                "list.focusFirst",
                "list.select",
            ],
        },
        "when": "workbench.scm.active"
    },
```

**Comment by lszomoru** [comment]
Ctrl+Shift+G should open the "Source Control" view and focus the commit input field. There is a known bug with this behaviour at the moment which I will look at fixing in the upcoming milestone so I am closing this issue as s duplicate (https://github.com/microsoft/vscode/issues/184155)
