### ISSUE TITLE
Integrated terminal link/file hovering doesn't include :line:column in file:// links

### ISSUE THREAD

**Issue by connorskees** [microsoft/vscode#193629]
When the `file://` prefix is added to a file path, the line number and column number fields are not included when alt-clicking to open the file.

![image](https://github.com/microsoft/vscode/assets/39542938/1b9fc997-e074-492d-8733-ad3e1b6e831c)

vs

![image](https://github.com/microsoft/vscode/assets/39542938/f23c1b36-4b23-46b4-95e1-d9ebd1dbc7a5)

**Comment by ssalbdivad** [comment]
This has been nagging at me forever- would love to see it fixed if it's relatively simple!

Is there any setting I can configure in the meantime to change what text is selected for these links?

Currently I'm stuck with either no position:

![image](https://github.com/microsoft/vscode/assets/10645823/8a1d8077-43c2-4f1c-9ade-2fc18a58a754)


Or it highlights the whole thing, but when I click to navigate it omits `file:///` and won't resolve unless I manually prepend a `/`:

![image](https://github.com/microsoft/vscode/assets/10645823/f8b3411a-fe8d-41d7-a019-6106738603a8)
