### ISSUE TITLE
Git: status bar after window reload is gray first, then white?

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#19367]
![untitled](https://cloud.githubusercontent.com/assets/900690/22294577/1286c940-e314-11e6-92d4-cef62a81963d.gif)

What the devil 👿

**Comment by joaomoreno** [comment]
I SAW IT TOO 😨

**Comment by joaomoreno** [comment]
Füxed

**Comment by bpasero** [comment]
BUT HOW?!

**Comment by joaomoreno** [comment]
Who knows.
