### ISSUE TITLE
Clean all and Stage all options should be disabled when there are no changes

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode#19360]
Testing #19049 

![jan-25-2017 14-32-00](https://cloud.githubusercontent.com/assets/10746682/22292375/240dbf92-e30b-11e6-9679-810bfb684e2a.gif)

**Comment by joaomoreno** [comment]
I can't disable yet due to #19345, but I can make it not show the quick open experience.

**Comment by joaomoreno** [comment]
To keep the number of issues in our inbox on a manageable level, we're closing issues that have been on the backlog for a long time but haven't gained traction: We look at the number of votes the issue has received and the number of duplicates issues filed.

Thanks for your understanding. Happy coding!
