### ISSUE TITLE
vscode not rendering correctly on KDE/X Server

### ISSUE THREAD

**Issue by neoacevedo** [microsoft/vscode#193627]
Does this issue occur when all extensions are disabled?: Yes 

- VS Code Version: 
Versión: 1.82.2
Confirmar: abd2f3db4bdb28f9e95536dfa84d8479f1eb312d
Fecha: 2023-09-14T05:51:20.981Z
Electron: 25.8.1
ElectronBuildId: 23779380
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
SO: Linux x64 6.5.3-1-default
- OS Version: openSUSE Tumbleweed 20230915

Steps to Reproduce:

1. Startup from any method, command line, shortcut etc.
2. Vscode will not render correctly

This bug is exactly the same in https://github.com/microsoft/vscode/issues/190327 but the version I have from vscode is the stable version. The workaround is to run it with the flag `--disable-gpu-driver-bug-workarounds`

**Comment by gjsjohnmurray** [comment]
Please see https://code.visualstudio.com/updates/v1_82#_update-highlights-for-chromium and try the deletion of GPU cache it recommends.

**Comment by deepak1556** [comment]
Merging to https://github.com/microsoft/vscode/issues/190437

**Comment by neoacevedo** [comment]
> Please see https://code.visualstudio.com/updates/v1_82#_update-highlights-for-chromium and try the deletion of GPU cache it recommends.

Then, on each GPU driver update I will have to do it?
