### ISSUE TITLE
malfunction entering rgb code in css file

### ISSUE THREAD

**Issue by slestak** [Microsoft/vscode#1936]
I was trying to replace one rgb value with another, and VSC 0.10.6 just would not let me key #1493C9.  First the number keys above my keyboard would not enter input.  I used the keypad to right and got everything in until I got to C and Intellisense was presenting to me colors that were already in the file.

I had to paste the value in to get my editing done.

**Comment by isidorn** [comment]
I can not reproduce this. Do you see it all the time for any .css file?
Can you share the .css file for which you can repro this?

**Comment by isidorn** [comment]
Closing until we get reproducable steps. or more users complain
