### ISSUE TITLE
Sticky scroll in output is the wrong color

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#193674]
Repro:

- Use a theme that has the editor as a different color to the panel
- Print a json object to an output channel

![Image](https://github.com/microsoft/vscode/assets/2193314/aab63b98-47f1-424b-b855-8f1c21e6dbd5)

**Comment by aiday-mar** [comment]
Hi @Tyriar, thank you for posting this issue. It is a bit unclear from the screen-shot what the expected output should be. Are you referring to what looks like the terminal sticky scroll?

**Comment by Tyriar** [comment]
@aiday-mar that's output (monaco) sticky scroll, not terminal. The bottom has a dark sticky scroll color and looks odd when the panel background is different to the editor.

**Comment by aiday-mar** [comment]
I am investigating how to detect if a specific editor is the editor in the output view. I was initially considering looking at the classList to find if `pane-body` or `output-view` is there, but the editor dom node class list appears to be undefined for the output view. I was wondering if there is perhaps another way to detect this? @bpasero

**Comment by bpasero** [comment]
> I am investigating how to detect if a specific editor is the editor in the output view.

I am not aware of a method to get the editor of the output view, but it should be easy to add:

https://github.com/microsoft/vscode/blob/587e0545330bdbd0adbc32dc51b1c8bd6dd7a011/src/vs/workbench/contrib/output/browser/outputView.ts#L41

Is that what you need?

**Comment by aiday-mar** [comment]
Ah maybe I can directly access the editor of the output view pane and verify that the current editor is equal to this editor

**Comment by bpasero** [comment]
But you are inside an editor contribution or? Not sure how that would work given layering violations.

**Comment by bpasero** [comment]
Not sure if it helps, but we can control the options we pass in to the editor for output and do so here:

https://github.com/microsoft/vscode/blob/cffff4c0da1b920e6324dafb71674d0773e55e83/src/vs/workbench/contrib/output/browser/outputView.ts#L180-L212

**Comment by Tyriar** [comment]
It's a bit of a tricky problem if you want this to work well across all themes. You probably need to support null or transparent values for the bg and hover bg keys and then resolve the colors manually into opaque colors by combining them with the bg color underneath.

This might be the right internal API to do that?

https://github.com/microsoft/vscode/blob/66c869c41f95221f297172dea95892381b19dbaf/src/vs/base/common/color.ts#L429-L434

**Comment by aiday-mar** [comment]
I was investigating the uri of the output editor, and noticed it has a scheme equal to 'output'. I can just use it in order to detect if the current editor is an output view editor and change the background accordingly.
