### ISSUE TITLE
inline values do not work in mock-debug

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#19365]
While debugging #18670:

- VSCode Version: 1.9
- OS Version: macOS

Steps to Reproduce:

1. install Mock debug extension
2. start debugging a markdown file and observe the names in the Variables view
3. sprinkle some variable names from the Variable view over the markdown file
4. start debugging

Observe: when stepping over a line containing a variable its value should be shown at the end of the line, but it is not.

**Comment by isidorn** [comment]
@weinand Is this the same issue as with mono that mock is passing made up types as part of the name?

**Comment by weinand** [comment]
The problem is that the inline value feature relies on specific tokenTypes that are produced by the syntax colouring. Only tokens of type "string" or "number" are considered for inline values.
Since the Markdown file used in the mock debugger does not define these tokenTypes, inline values don't show up.

So this issue is not a bug but more a documentation problem.
