### ISSUE TITLE
Warning in default settinsg

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#19364]
I know this is a topic discussed a billion times but I do see a warning I cannot get rid of:

* install https://marketplace.visualstudio.com/items?itemName=samverschueren.final-newline which defines the `files.insertFinalNewLine` setting
* open settings editor
* 🐛 you see a warning because vscode also defines that settings

![screen shot 2017-01-25 at 15 04 20](https://cloud.githubusercontent.com/assets/1794099/22293445/d188f5c0-e30f-11e6-8ec4-4a2d7d212a09.png)

**Comment by sandy081** [comment]
IMO solution here is not to show the warning, instead fix the root cause. Because, it seems, the config `files.insertFinalNewline` is being defined by our files component and also by the extension. I would suggest the extension to rename its config with proper prefix. @bpasero FYI

**Comment by bpasero** [comment]
Yes, I was not expecting that an extension can just come up with a config name that already exists, e.g. it should always be prefixed with the extension ID imho.

**Comment by jrieken** [comment]
Sorry @sandy081 but I don't see how this is invalid unless you prohibit extensions redeclaring existing configuration settings (indeed in this case we overwrote the extension which was first). I see a warning which I cannot dismiss whenever I open settings, so will the 9k other users of that extension.

How about the configuration service merging identical settings? There is no difference in them, that's why they shouldn't be duplicated in the first place

**Comment by sandy081** [comment]
Agreed that we should not accept and show the duplicate settings. But the thing which I am not sure here is that how does we convey to the users that a setting is overridden or ignored because of duplication?
