### ISSUE TITLE
SCM Sync view: focus lost from the tree on mouse click

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#193606]
Nice view 👍 

Noticed that when you click on a file with the mouse, focus moves into the editor immediately. Maybe connect with @alexr00 and custom trees to learn how you can get opening behaviour that is consistent for free.

**Comment by alexr00** [comment]
@lszomoru here's how we do this in the tree.  Specifically see line 750: 

https://github.com/microsoft/vscode/blob/76e43679aeda335bfdf6949809915895f71637a4/src/vs/workbench/browser/parts/views/treeView.ts#L738-L762

**Comment by lszomoru** [comment]
Thank you both! This has already been fixed in the latest Insiders release.
