### ISSUE TITLE
Profile icon search should be more fuzzy

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#193683]
The search should work more like the quick pick, where it has fuzzy matching such that `prvm` would match `profile-icon-vm`:

![Image](https://github.com/microsoft/vscode/assets/2193314/8c3e779a-f85d-4458-803c-09d438b22fcc)

**Comment by sandy081** [comment]
Contiguous search is enough for icons widget filtering. Also icon ids are simple one word strings. We can get back to this if needed.
