### ISSUE TITLE
Reconnect doesn't pass on the added skipFiles argument

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode#19366]
- VSCode Version: Code - Insiders 1.9.0-insider (fbea777a881523bc01a1358d115b16673dc5942e, 2017-01-25T07:12:18.506Z)
- OS Version: Windows_NT ia32 10.0.14393

Testing #19042

## Setup

`test.js`
```js
const path = require('path');

let c = path.join('a', 'b');
```

`launch.json`

```json
{
    "version": "0.2.0",
    "configurations": [

        {
            "type": "node",
            "request": "launch",
            "name": "Launch Program",
            "program": "${file}",
            "cwd": "${workspaceRoot}",
            "skipFiles": [
                "<node_internals>/**/*.js"
            ]
        }
    ]
}
```
1) Set a break point on the line with `path.join`
2) launch a node program using F5
3) in the launch config add the `skipFiles` argument
4) reconnect
5) the break point is hit
6) step into
➡️ the skipFiles attribute is ignored you end up in the node internal code

7) stop the program
8) launch the program again, the break point is hit
9) step into
➡️the skipFiles attribute is honored

**Comment by weinand** [comment]
'restart' really restarts the current session with the original attributes. It does not pick up any edits made to the launch.json in the meantime.
I think the semantic is correct, but I understand the confusion when editing of the launch.json occurs.
May be we should detect that it changed and inform that the old launch config will be used.
