### ISSUE TITLE
Window reload required after enabling `scm.experimental.showSyncView`

### ISSUE THREAD

**Issue by gjsjohnmurray** [microsoft/vscode#193646]
Type: <b>Bug</b>

When I first enabled `scm.experimental.showSyncView` nothing new appeared in SCM view until I ran `Developer: Reload Window`. This conjured up the SOURCE CONTROL SYNC section there, and now it disappears and reappears immediately as I toggle that experimental setting.

VS Code version: Code - Insiders 1.83.0-insider (11bfd76a61a299156a9f3138ecfad70937af3527, 2023-09-21T05:34:38.227Z)
OS version: Windows_NT x64 10.0.22621
Modes:

**Comment by lszomoru** [comment]
Closing this issue as the setting has been removed along with the Sync View.
