### ISSUE TITLE
Scroll lock icon does not fit with the rest of the icon set

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#19362]
![image](https://cloud.githubusercontent.com/assets/900690/22292577/3f2a562c-e30c-11e6-8816-876b378eb326.png)

Is this temporary until we have a real icon? Imho it does not fit to any other icon we have there, neither in size nor in shape.

**Comment by isidorn** [comment]
This is the final icon which we got from the icon people. I agree it looks alien, but I think we can ship with it.
@chrisdias do we have a contact from the icon folk that we can ping for issues like this?

**Comment by isidorn** [comment]
@kieferrm do we have a contact from the icon folk who we can ping for issues like this?

**Comment by chrisdias** [comment]
@bpasero @isidorn is it the clear output icon or the scroll lock icon that is out of place?  the same "clear" icon is used in the debug console, the Find viewlet, and the extension viewlet.

the scroll lock icon looks out of place to me compared to the others.

**Comment by bpasero** [comment]
Sorry, the **scroll lock** is what I meant.

**Comment by isidorn** [comment]
@chrisdias yeah the scroll lock. Do we have someone to bother for icons or should I invest in icon designing skills :)

**Comment by chrisdias** [comment]
@isidorn @bpasero 

I updated the icon with bolder ones, but i still don't like it.

Why not use a lock?  Something like these? 

When "on" it is in the locked state:

![image](https://cloud.githubusercontent.com/assets/1487073/22533347/6a22e5c4-e8a2-11e6-8701-fd50a3b0e2e0.png)

when "off" use the open lock icon:

![image](https://cloud.githubusercontent.com/assets/1487073/22533353/792f76ea-e8a2-11e6-818b-2ed40d7cf52d.png)

Here is what it would look in the locked state on the light theme:

![image](https://cloud.githubusercontent.com/assets/1487073/22533408/daaf20aa-e8a2-11e6-9aa1-8cfa40367084.png)

thoughts?

**Comment by bpasero** [comment]
Looks good, I also like that there are two versions. Currently we keep the button with a blue outline when clicked which imho looks too much like the focus outline.

**Comment by isidorn** [comment]
Look at @chrisdias closing bugs like a boss left and right - thanks a lot!
I agree that I prefer just the lock as it is simpler, though the empty lock might be my choice as it is not so heavy

![screen shot 2017-02-02 at 10 48 31](https://cloud.githubusercontent.com/assets/1926584/22544476/2ef05dae-e935-11e6-8829-cf3f34335a61.png)

The only issue I encountered while browsing through https://vsicons.azurewebsites.net/ is that I could not find the inverse version of the icons - in our case for the use in the dark theme. How can I get those?
Ping @chryw as I understand he is responsible for that site

fyi @ArtemGovorov for possible feedback on the icon

**Comment by chrisdias** [comment]
We have to get the inverse icon created. 

I'll do that for the empty lock icons and give you the open and the close so that you can toggle it instead of using the blue outline.

**Comment by chryw** [comment]
@isidorn that site only shows standard light theme icons created for Visual Studio. VS Code icons are similar in concept but produced in a slightly different way. If there is any icon need for VS Code, a Microsoft member will reach out to the UX and the UX will create proper light theme and dark theme svg files.

**Comment by chrisdias** [comment]
@isidorn here are the lock/unlock icons:

[lockicons.zip](https://github.com/Microsoft/vscode/files/749227/lockicons.zip)

**Comment by isidorn** [comment]
Thanks @chrisdias for the icons! What is the process of making the inverse - just manual work in some tool? Asking because I would like to be able to do that myself :)
You can try this out in tomorrow's insiders. Feels good imho

**Comment by chryw** [comment]
@isidorn I have some gulp tasks to make VS Code icon from a regular VS icon. 
https://github.com/chryw/iconutil/blob/master/gulpfile.js#L104

Inversion is just find & replace. You can see the hex color mapping here
https://github.com/chryw/iconutil/blob/master/gulpfile.js#L135

**Comment by isidorn** [comment]
@chryw awesome - thanks a lot!
