### ISSUE TITLE
breakpoints not working on vscode extension development

### ISSUE THREAD

**Issue by StephaneAdeso** [microsoft/vscode#193710]
Type: <b>Bug</b>

I'm developing an extension for vscode and breakpoints don't work. I can set them without any problem, but when I launch F5, it just won't stop on them.

I have tried disabling all the extensions and it still happens.

Related to https://github.com/microsoft/vscode/issues/192507.

VS Code version: Code 1.82.2 (abd2f3db4bdb28f9e95536dfa84d8479f1eb312d, 2023-09-14T05:55:25.390Z)
OS version: Windows_NT x64 10.0.22621
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz (16 x 2304)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.79GB (17.12GB free)|
|Process Argv|--crash-reporter-id ccedd11e-cbe3-4aab-835a-b81d8cc295d7|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (40)</summary>

Extension|Author (truncated)|Version
---|---|---
codesnap|adp|1.3.4
tsl-problem-matcher|amo|0.6.2
ng-template|Ang|16.1.8
cssrem|cip|3.1.1
continue|Con|0.0.394
vscode-eslint|dba|2.4.2
es7-react-js-snippets|dsz|4.4.3
gitlens|eam|14.3.0
prettier-vscode|esb|10.1.0
fetch-client|Gan|1.3.0
todo-tree|Gru|0.0.226
Angular2|joh|16.0.1
vscode-peacock|joh|4.2.2
vscode-colorize|kam|0.11.1
git-graph|mhu|1.30.0
isort|ms-|2023.10.1
python|ms-|2023.16.0
vscode-pylance|ms-|2023.9.20
live-server|ms-|0.4.9
vsliveshare|ms-|1.0.5883
vscode-versionlens|pfl|1.7.3
postman-for-vscode|Pos|0.9.0
vscode-thunder-client|ran|2.12.1
fabric8-analytics|red|0.7.0
java|red|1.22.1
vscode-xml|red|0.26.1
vscode-yaml|red|1.14.0
vs-code-prettier-eslint|rve|5.1.0
partial-diff|ryu|1.4.3
errorlens|use|3.13.0
intellicode-api-usage-examples|Vis|0.2.8
vscodeintellicode|Vis|1.2.30
vscode-java-debug|vsc|0.54.0
vscode-java-dependency|vsc|0.23.1
vscode-java-pack|vsc|0.25.14
vscode-java-test|vsc|0.39.1
vscode-maven|vsc|0.42.0
vscode-icons|vsc|12.5.0
JavaScriptSnippets|xab|1.8.0
markdown-all-in-one|yzh|3.5.1

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
3biah626:30602489
89544117:30613380
a9j8j154:30646983
showlangstatbar:30737416
03d35959:30757346
pythonfmttext:30731395
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
pythonnosmt12:30797651
pythonidxptcf:30805731
pythonnoceb:30805159
copilotsettingc:30839828
synctok:30821570
dsvsc013:30795093
dsvsc014:30804076
diffeditorv2:30821572
dsvsc015cf:30829746

```

</details>

**Comment by StephaneAdeso** [comment]
this is the log file
[vscode-debugadapter-f18a293c.json.gz](https://github.com/microsoft/vscode/files/12689381/vscode-debugadapter-f18a293c.json.gz)

**Comment by StephaneAdeso** [comment]
this is my `webpack.config.js`:
```
//@ts-check

'use strict';

const path = require('path');
const terserPlugin = require('terser-webpack-plugin');
const miniCssExtractPlugin = require('mini-css-extract-plugin');

//@ts-check
/** @typedef {import('webpack').Configuration} WebpackConfig **/

const commonConfig = (webpackEnv) => {
  const isEnvDevelopment = webpackEnv === 'development';
  const isEnvProduction = webpackEnv === 'production';

  return {
    mode: isEnvProduction ? 'production' : isEnvDevelopment && 'development',
    bail: isEnvProduction,
    devtool: isEnvProduction
      ? 'source-map'
      : isEnvDevelopment && 'eval-cheap-module-source-map',
    resolve: {
      extensions: ['.ts', '.tsx', '.js', '.jsx']
    },
    module: {
      rules: [
        {
          test: [/\.bmp$/, /\.gif$/, /\.jpe?g$/, /\.png$/, /\.svg$/],
          type: 'asset/resource'
        },
        {
          test: /\.tsx?$/,
          exclude: /node_modules/,
          use: [
            {
              loader: require.resolve('ts-loader')
            }
          ]
        },
        {
          test: /\.(woff|woff2|eot|ttf|otf)$/i,
          type: 'asset/resource'
        },
        {
          test: /\.m?js/,
          resolve: {
            fullySpecified: false
          }
        },
        {
          test: /\.css$/i,
          use: [miniCssExtractPlugin.loader, 'css-loader']
        }
      ]
    },
    optimization: {
      minimize: true,
      minimizer: [
        new terserPlugin({
          terserOptions: {
            format: {
              comments: false
            }
          },
          extractComments: false
        })
      ]
    },
    plugins: [new miniCssExtractPlugin()]
  };
};

// extension sources
const extensionConfig = (webpackEnv) => {
  return {
    ...commonConfig(webpackEnv),
    target: 'node',
    entry: './src/extension.ts',
    output: {
      path: path.resolve(__dirname, 'dist'),
      filename: 'extension.js',
      libraryTarget: 'commonjs2'
    },
    externals: {
      vscode: 'commonjs vscode',
      // eslint-disable-next-line @typescript-eslint/naming-convention
      'better-sqlite3': 'commonjs better-sqlite3'
    }
  };
};

// react sources
const seekerUIConfig = (webpackEnv) => {
  return {
    ...commonConfig(webpackEnv),
    entry: './src/infraestructure/views/SeekerUI/index.tsx',
    output: {
      path: path.resolve(__dirname, 'dist'),
      filename: 'seeker-ui.js'
    }
  };
};

module.exports = [extensionConfig, seekerUIConfig];
```

this is my `tsconfig.json`:
```
{
  "compilerOptions": {
    "module": "CommonJS",
    "target": "ES2020",
    "lib": ["ES2020", "DOM"],
    "sourceMap": true,
    "rootDir": "src",
    "outDir": "dist",
    "strict": true /* enable all strict type-checking options */,
    /* Additional Checks */
    // "noImplicitReturns": true, /* Report error when not all code paths in function return a value. */
    // "noFallthroughCasesInSwitch": true, /* Report errors for fallthrough cases in switch statement. */
    // "noUnusedParameters": true,  /* Report errors on unused parameters. */

    "jsx": "react",
    "esModuleInterop": true
  },
  "exclude": ["src/test/**/*"]
}
```
this is my `launch.json` ( none of them works):
```
 {
  "version": "0.2.0",
  "configurations": [
    {
      "name": "Launch Extension",
      "args": [
        "--extensionDevelopmentPath=${workspaceFolder}",
        "--disable-extensions"
      ],
      "preLaunchTask": "npm: watch",
      "request": "launch",
      "type": "extensionHost"
    },
    {
      "name": "Run Extension",
      "type": "extensionHost",
      "request": "launch",
      "args": [
        "--extensionDevelopmentPath=${workspaceFolder}",
        "--disable-extensions"
      ],
      "outFiles": ["${workspaceFolder}/dist/**/*.js"],
      "preLaunchTask": "${defaultBuildTask}"
    },
    {
      "name": "Extension Tests",
      "type": "extensionHost",
      "request": "launch",
      "args": [
        "--extensionDevelopmentPath=${workspaceFolder}",
        "--extensionTestsPath=${workspaceFolder}/out/test/suite/index"
      ],
      "outFiles": [
        "${workspaceFolder}/out/**/*.js",
        "${workspaceFolder}/dist/**/*.js"
      ],
      "preLaunchTask": "tasks: watch-tests"
    },
    {
      "name": "Launch Extension with logs",
      "args": [
        "--extensionDevelopmentPath=${workspaceFolder}",
        "--disable-extensions"
      ],
      "preLaunchTask": "npm: watch",
      "request": "launch",
      "type": "extensionHost",
      "trace": true
    }
  ]
}
```

**Comment by connor4312** [comment]
It looks like the trace log you collected got corrupted, could you try grabbing another one for us? Thanks!

**Comment by StephaneAdeso** [comment]
There you have
[vscode-debugadapter-4d1cf32b.json.gz](https://github.com/microsoft/vscode/files/12703111/vscode-debugadapter-4d1cf32b.json.gz)

**Comment by connor4312** [comment]
Same corruption there 🤔 you can capture a .txt to avoid issues by using `"trace": {"logFile": "${workspaceFolder/log.txt" },`

But, I'm curious if removing your terser plugin fixes the issue for you?

**Comment by StephaneAdeso** [comment]
> "trace": { "logFile": "${workspaceFolder/log.txt" }

The `workspaceFolder` didn't work. was unable to see where the logs was saved. I changed to `"trace": { "logFile": "c:/log.txt" }` but the log is still not created.

At this point I removed the terser plugin from webpack.

I ran the launch again with the configuration: `"trace": { "logFile": "c:/log.txt" }` but again, no log was created.

So i runed it again but with the `"trace": true`. So this is the new logs with terser removed from webpack.config.json
[vscode-debugadapter-798d1511.json.gz](https://github.com/microsoft/vscode/files/12704043/vscode-debugadapter-798d1511.json.gz)

**Comment by connor4312** [comment]
Apologies, I was missing a curly brace there. `${workspaceFolder}/log.txt` will save the file in your workspace folder. It looks like that log has the same corruption issue.

**Comment by StephaneAdeso** [comment]
There you have the log with terser off and the "trace": {"logFile": "${workspaceFolder}/log.txt" }:
[log.txt](https://github.com/microsoft/vscode/files/12704288/log.txt)

I am curious about why all previous logs are corrupted.

**Comment by connor4312** [comment]
THere we go.

From the logs I can see that your resulting `c:/workspace/adeso-seeker/dist/extension.js` does not have an associated sourcemap. Something in your build setup is probably dropping the sourcemap in the processing step.

As a quick check, you should be able to see a line containing "sourceMappingURL" in that file when sourcemaps are present.

**Comment by StephaneAdeso** [comment]
Sorry. With your last comment I'm not sure what I should do. 

My project is an extension with TypeScript and Webpack. There is a front end with React. 

In webpack the 2 parts are divided (react and the rest of the extension) because I am a junior developer and it was the only example on how to set react in an extension I found.

source map is declared on the webpack.cong and the tsconfig. ( look above).
Can I do something else? I'm sorry for not being more helpful, but I don't see anything strange.

**Comment by connor4312** [comment]
I would confirm that the value of `webpackEnv` is what you expect. If it's neither development nor production you would not make a sourcemap.

It's also strange (and would make debugging worse anyway) to set minimization in `optimization` when you're in development, though I don't think that would be removing the sourcemap (if you don't have the terser plugin enabled.)
