### ISSUE TITLE
Syntax highiling missing most colors (C#)

### ISSUE THREAD

**Issue by tymtam2** [microsoft/vscode#193750]
Type: <b>Bug</b>

Classes, methods and functions stopped having the usual colors (e.g. yellow for methods). Please see attached screenshots. 

VS Code Insiders 1.83.0-insiders, C# Dev Kit v0.5.98
![image](https://github.com/microsoft/vscode/assets/1097613/1654c318-3fb4-45ee-9613-77e85d961242)

In VS Code 1.82.2  - not insiders, with c# Dev Kit v0.4.10
![image](https://github.com/microsoft/vscode/assets/1097613/ef162f86-607a-4e86-b377-ab78e9403e60)

The same file opened in non-insiders VS Code has the expected colors. 

VS Code version: Code - Insiders 1.83.0-insider (11bfd76a61a299156a9f3138ecfad70937af3527, 2023-09-21T05:34:38.227Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|7.81GB (1.10GB free)|
|Process Argv|--crash-reporter-id 4f577441-a09c-4562-9eb0-9213dfe79067|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (17)</summary>

Extension|Author (truncated)|Version
---|---|---
gitlens|eam|2023.9.2105
copilot|Git|1.115.431
copilot-chat|Git|0.8.2023092101
copilot-labs|Git|0.15.1019
csdevkit|ms-|0.5.98
csharp|ms-|2.3.27
dotnet-interactive-vscode|ms-|1.0.4461040
vscode-dotnet-pack|ms-|1.0.12
vscode-dotnet-runtime|ms-|1.7.3
vscodeintellicode-csharp|ms-|0.1.26
python|ms-|2023.17.12650220
vscode-pylance|ms-|2023.9.20
jupyter|ms-|2023.9.1002661100
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.17
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-slideshow|ms-|0.1.5

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256198
vstes516:30244333
vslsvsres303:30308271
pythontb:30258533
pythonptprofiler:30281269
vshan820:30294714
vscod805:30301674
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30404738
py29gd2263:30784851
vsclangdf:30492506
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30618038
showlangstatbar:30737417
24365598:30687740
pythonfmttext:30716741
fixshowwlkth:30771523
showindicator:30805243
pythongtdpath:30726887
i26e3531:30792625
welcomedialogc:30812479
pythonnosmt12:30779711
pythonidxpt:30768918
pythonnoceb:30776497
copilotsettingc:30808720
dsvsc013:30777762
dsvsc014:30777825
diffeditorv2:30786206
pythonlinttypecf:30823782
pythonmypywwcf:30841057
pythonmpsinfo:30842935
dsvsc015:30821418
pythontestfixt:30826906
pythonfb280951:30830809
pythonregdiag:30842812
pythonmypyd1:30841190

```

</details>

**Comment by aeschli** [comment]
Can it be that in the first screenshot you are using the `Dark (Visual Studio)` theme? That's the most minimal theme we have.
The second looks like the Dark+ theme.

If that's not the case, please paste your code snippet.

**Comment by tymtam2** [comment]
@aeschli Thank you. You are correct, my theme was set to `Dark (Visual Studio)` and after changing to `Dark Modern` the highlighting is what I desire :). 

I'm going to retreat into the hedge in a Homer Simpson style now but my last words before disappearing are: 
*Could I suggest renaming `Dark (Visual Studio)` to `Dark (minimal)`?*

**Comment by aeschli** [comment]
Glad I guessed right. You are right, Minimal would have been a better name. Renaming the theme would just cause a swirl with existing users, so we have no plans for that.
