### ISSUE TITLE
FeatureLint not found.  And is required

### ISSUE THREAD

**Issue by stenaksel** [microsoft/vscode#193769]
Type: <b>Bug</b>

in vscode I get:
`FeatureLint not found.  And is required.`
When I click `Install` button. I get: 
```
Failed to install with error: Command failed: dotnet tool install -g UnderTest.FeatureLint
The command could not be loaded, possibly because:
  * You intended to execute a .NET application:
      The application 'tool' does not exist.
  * You intended to execute a .NET SDK command:
      No .NET SDKs were found.

Download a .NET SDK:
https://aka.ms/dotnet-download

Learn about SDK resolution:
https://aka.ms/dotnet/sdk-not-found
```

VS Code version: Code 1.82.2 (abd2f3db4bdb28f9e95536dfa84d8479f1eb312d, 2023-09-14T05:55:25.390Z)
OS version: Windows_NT x64 10.0.22621
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz (16 x 2304)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.73GB (11.44GB free)|
|Process Argv|--crash-reporter-id 3145418d-25f5-403c-adc1-0f7fa6d0047c|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (41)</summary>

Extension|Author (truncated)|Version
---|---|---
cucumberautocomplete|ale|2.15.2
featurehighlight|Blo|1.8.0
codeium|Cod|1.2.90
cucumber-official|Cuc|1.7.0
vscode-markdownlint|Dav|0.51.0
vscode-eslint|dba|2.4.2
gitlens|eam|2023.9.2105
EditorConfig|Edi|0.16.4
prettier-vscode|esb|10.1.0
auto-rename-tag|for|0.1.10
shell-format|fox|7.2.5
vscode-pull-request-github|Git|0.73.2023091209
todo-tree|Gru|0.0.226
jbockle-format-files|jbo|3.4.0
intellij-idea-keybindings|k--|1.5.10
vsc-python-indent|Kev|1.18.0
xml-format|mik|1.1.3
vscode-docker|ms-|1.26.1
csharp|ms-|2.3.27
vscode-dotnet-runtime|ms-|1.7.3
playwright|ms-|1.0.15
autopep8|ms-|2023.6.0
black-formatter|ms-|2023.5.12561007
isort|ms-|2023.10.1
pylint|ms-|2023.6.0
python|ms-|2023.16.0
vscode-pylance|ms-|2023.9.20
remote-containers|ms-|0.309.0
vscode-typescript-next|ms-|5.3.20230921
indent-rainbow|ode|8.3.1
material-icon-theme|PKi|4.30.1
vscode-formatall|rat|0.0.2
bash-beautify|sha|0.1.1
cucumber|ste|0.14.0
svelte-vscode|sve|107.11.0
even-better-toml|tam|0.19.2
pypi-assistant|twi|1.2.4
undertest-featurelint|und|0.0.37
vscode-icons|vsc|12.5.0
bdd|vte|0.3.18
change-case|wma|1.0.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263cf:30335440
vscoreces:30445986
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
vscaac:30438847
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
3biah626:30602489
f6dab269:30613381
2i9eh265:30646982
showlangstatbar:30737416
03d35959:30757346
pythonfmttext:30731395
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
pythonnosmt12:30797651
pythonidxpt:30805730
pythonnoceb:30805159
copilotsettingc:30839828
dsvsc013:30795093
dsvsc014:30804076
diffeditorv1:30821571
dsvsc015cf:30829746

```

</details>

**Comment by stenaksel** [comment]
(I'm writing code in Python and not .net)

**Comment by sandy081** [comment]
I assume this message is coming from an extension you installed. Hence I would recommend to file issue against that extension.
