### ISSUE TITLE
Test Explorer badge does not clear after clearing all test results

### ISSUE THREAD

**Issue by isc-bsaviano** [microsoft/vscode#193701]
Type: <b>Bug</b>

Steps to reproduce:

1. Pull the [test-provider-sample extension source code](https://github.com/microsoft/vscode-extension-samples/tree/main/test-provider-sample). 
2. Follow the steps in the README to install dependencies and run the extension.
3. Open the Test Explorer view and run all tests in the workspace. Observe at one of the tests fails.
4. In the bottom view, select the `TEST RESULTS` tab and click the trash icon to clear all results.
5. Observe that the results have been cleared, but the Test Explorer view container still has a `1` badge for the failed test result.

VS Code version: Code - Insiders 1.83.0-insider (11bfd76a61a299156a9f3138ecfad70937af3527, 2023-09-21T05:51:12.735Z)
OS version: Darwin arm64 22.6.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Max (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|6, 6, 6|
|Memory (System)|32.00GB (1.50GB free)|
|Process Argv|--enable-proposed-api intersystems-community.vscode-objectscript --crash-reporter-id e7ae9334-8d82-4160-81f6-e148e14ff8dd|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
objectscript-pack|int|1.0.3
servermanager|int|3.4.2
vscode-objectscript|int|2.10.3-unittest.6
language-server|int|2.3.6
cpptools|ms-|1.17.5
vscode-lldb|vad|1.10.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythontb:30258533
pythonptprofiler:30281269
vshan820:30294714
vscod805cf:30301675
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30404738
py29gd2263:30784851
vsclangdf:30492506
c4g48928:30535728
dsvsc012:30540252
pynewext54:30618038
showlangstatbar:30737417
57b77579:30687741
pythonfmttext:30716741
fixshowwlkth:30771523
showindicator:30805243
pythongtdpath:30726887
i26e3531:30792625
welcomedialog:30812478
pythonnosmt12:30779711
pythonidxpt:30768918
pythonnoceb:30776497
copilotsettingt:30808721
dsvsc013:30777762
dsvsc014:30777825
diffeditorv2:30786206
pythonlinttypecf:30823782
pythonmypywwcf:30841057
pythonmpsinfo:30815194
dsvsc015:30821418
pythontestfixtcf:30826907
pythonfb280951:30830809
pythonmypyd1cf:30841191

```

</details>

**Comment by isc-bsaviano** [comment]
Thanks for triaging this @connor4312! Is there any chance that this could be fixed in time for the September or October release?

**Comment by connor4312** [comment]
Fixed in https://github.com/microsoft/vscode/pull/194852
