### ISSUE TITLE
vscode reports warning on constructor guards

### ISSUE THREAD

**Issue by jandrieu** [Microsoft/vscode#1937]
Error code 2350
"Only a void function can be called with the 'new' keyword."

This warning is shown when using the guard pattern to prevent accidental invocation of the class object without using new:

```
function Podcast() {
    if(false === (this instanceof Podcast)) {
        return new Podcast();
    }

    this.title = 'Astronomy Cast';
    this.description = 'A fact-based journey through the galaxy.';
    this.link = 'http://www.astronomycast.com';
}
```
Example is from http://elegantcode.com/2010/12/21/basic-javascript-part-4-enforcing-new-on-constructor-functions/ 

Since this is good practice, how do we turn off that warning?

P.S. Google https://www.google.com/search?q=vscode+"only+a+void+function+can+be+called+with+the+%27new%27+keyword" turned up https://vscode.trafficmanager.net/Issues/Detail/19591 when I searched for an open issue, but that redirects to this issues list, where I couldn't find any issues mentioning the warning.

**Comment by jrieken** [comment]
Closed with the adoption of Salsa (https://code.visualstudio.com/Updates#_languages-javascript).
