### ISSUE TITLE
Clicking into diff editor doesn't always focus it

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#193784]
* open diff editor
* resize it to show side-by-side
* focus another editor group
* click onto the stripes
* 🐛 no focus
* resize to show inline diff
* click onto remove parts
* 🐛 no focus

https://github.com/microsoft/vscode/assets/1794099/25ce15a1-e144-4aeb-a5d3-1e8937db28b2

**Comment by hediet** [comment]
To reproduce, open [this playground](https://microsoft.github.io/monaco-editor/playground.html?source=v0.44.0-dev-20230925#XQAAAAJQJQAAAAAAAABBqQkHQ5NjdMjwa-jY7SIQ9S7DNlzs5W-mwj0fe1ZCDRFc9ws9XQE0SJE1jc2VKxhaLFIw9vEWSxW3yscyJyzeM7dlg3VBq2R8_14-2mwCsHUPY8aq-qOG-vxdGhskmQiJZesSPs4etOWthx7O8cQpBQkbTp_JvI85pfqfzl1ts42UwI94cc82tRW2i2fidFACR0F-nwUnnCfbpXhDxohUomO6AnBPHBZgqiEVsrnHbTJLWzZr6Ydek3aQMTTClQ6KDkxn-8jK4BNbjp7yqPjb1ycDpMlzJsBOljtT8amfx-r1XhZvBNI4VIN5KsH6AJ5affFyNOHzgKYz7Zit6ME6p2vaYWBHkR1-jILMK16aa02heelHMRjGDjixGoE6mKwStAqWLV3SJsIKktTA83hVGEbZzp08RYzh2dZHoFfbqxD2DKa7Nr9bIJQ6A8MrrUJmMRHpZGdC04g35lT6_lOox9PRYKZbNvDUi3skrrBANmhqxCppqB8kvgv-b7g5tZDsyy4_rn7_hgGPVG_7svix9u-qzfFKnsd37WW8H6jjSDzl4P61Fo5H-js4zFNBOYD3ue0fRyLa50FPS0zA_nW5L2vd8K12xCQJJ9818M-FVRU5gf2ILB8kKI4pwdyKos0T-5YysxPWrQav8QASk_WpvXraCTKAF2WEVaMgczbxNTg6bPJ38NMM7isXR-YjJLHumVGsvc0TMRwcMN1-qCD0aRnHozx0wOtKQTXo-cDlqUuXcSMxwXpgEb7BFEmZYwSJzrWHC1MzXouXFtv-XvDogcXlXqR0ZNdyFPr9F8L15RRnS0WhSa_fze1ayGvFKAh9V0Q0ovH52uFaVdb6b12Nf76IPJO75MqC7b4fYC6rzWiK2Y-olY6FEJ8yl1FhePy5q4HVVIfoMynOGNQgRt9MThr-CObyiGUggQMHGPMg17EuyKFY9F1EDA9QVyZYvsLI-6DHocBmzcKUIA6jojvyiMGqXKIZQDNcjVlBYQm7Qd1Bo_dI4u8fg1f5uE_MyWODosg01iMGPtRGAaaiywrYvC-CtJ2C7UHPyQkn3uF2oZQkYqyWbWBgEjjS6fvJBriBf8J_BNN-mzr35GFhvVPL6qosteLwOuEHJOdAYZt95Qin-Eg0iePFX5Ey8NTxJ8KEABi9rGC1d07l4K3phtI4IoQ3_eYSDT1bYsOwRxu69mY14O_qvTmId3uKZfg4dXe1zHOD1dBFmshzDdpylckRmPqfqo6o4OeB8TBTlGXWY_xO1PVEaj_5jCsGyBCJ_ontv0xY_ampvFeUvsj-FfnM8g435dkClxj_8KxB2v000h0ejUNEG_gAjaQNxgVg0XIeqpBa2nfpifZeP_2xrfqH2goYVgkELzu9jUBQy3XAfUn3NinL2W1SjDlmpPoHUWrp9zfBiu7kwJQdselJ8mWaAlAchbyHQn25yNgpaBOKZtVNwVk1OkPNSwSfFVZ0_IkUiI_nDNjgtGuSTWH3vvLqLA7gCHrBKqN7NigWztBqF4bkSYRA1rG0p3U7V7OzCKM0ML5Jn7JFzNvCu-Wg_uPBTZX72mMc_pSgRT44LLEAgPek7V_rHBjLU_gQz10ZkQYSMmJqjbRY11V-M1WC5vNWTbB7FjRxjyPYXlzaO75hkPcblDmzyjzCzZQKXoKuN8tULOgmBxOGvwCINiG5YHY7u_agAE2V8NwJA752RH8ZNUKX2QAXeC9qvFmixd79igPxm3BjVtmnVkFFCpZyZdxSWz4DC1cQ5K13uwct6_oBW-C6B9L8wJkpZCGAbrIwtiIxwfGlT-Hm-BbgOmrfFMw7DBDgYVfKXM6CtE2MpDoZFgWkjR8fl469CDpXPOebF8LysgS11W-tgishLDqz-3w7vItUMtzj8MKUh26o1kGHGWVi6AFWJVRkAAA-H3XaJmrbFotw2t7XNPiVWLGb58_qQpx4EbnyRc2tEfvZMouWGSRpoTI8S0Mxk6cUmnBB00_0Y4uq6or30POsBMftPI5yxxNx-SbeY2ufjZ92cHFcfSKfXpBv_yH0jZtDboc9tDI_76orUT9Qij9XgAUjmHDFCCvwdTbCzHNO4UmsSqCaDBSEIKkAWbl4yFqZ-O_5agIXqK42P5X5cnpMBixYoUQEIW6s2SLrstxfxVrRP5owcm7qJwoOegg5hMfqidZeg_UX3gFOLaM-aALWTe1VcoPNGvc3agoBYsa3G5eFZZJ_VavP-pEwj6xCV3umb9EziYaSUA5UMoNYubdA1H7eXirjbc6g287iPXBEhZOUh0l4k_YkJCRUNXVVWJSO3DFMqeM6i4WtOj-uSwom48UcAh5GwB1ztGOjlCfjg-UDsyO20MAdIAs1Cfa03UN9KA_cEqv6dpDFrXQ1nuu6e8Ku6xiB9GI96rCC96_fECXpLLJUSzUZZ34zLAjNF633YbuV-VaNHH2weqcQ4i2EwZ0Mx2GW4iSWu-8hu-ZWalOcvNgt1y101nJILQhZwoFM6Say5OhUJgaA7h3azFjiwnG9ieI4iOkmIcCEjLvuD6oy2G0UpW_UuNDmUyxd5AqFdWFcyQlD9vReoTswPWnl8CZGL5P7Jb0higxZlH5PLXsDmieAVmLT-e3fU9jDIbPcZTFkgABab_wc8FWjNA7wtH8zBYlm9qmsSwy_Q3q2TbLGarBuCXZ0vwocpCHi8jNezN32DJUsjWVrcsuJtumUwRyH1z7YOEXRAph5T2Swx35IShvs9NSwtu9PsMWkeQ0ZgTAwjLw6fAPdo2bJQUYgfTBxYHrVCZIJZLtQyHBOYHNwymCs969tieDBt-83mY0vhKAyG8nIJk7BcAmAy7xudbVEspeMn1BI7h48OwuTEd3y5SO_rss9vlC0MqcaVHwWnuB6sJr76suEAp6NAbKQ-rEof3VuVvV4j025rF1fZI8_LV2Q212FcImSVAoVI8yfW4emGJLoUPMekWfgcfs_v_HUoTQndpORvXgfXnBhd-IFN2LgWJid8LB6Zq7063YS_vNo5MeMF8Gsq5mbJtYMbovQNqUSYQxzyBaEq0pL8s7hWTcqJDIXMNBAPtXkzV9mozgj9y5iHGrl44CDZr6u9YqZVlhGKwxU55xJ8155RO4zJAzwIuAG_eiZDZzkHAd0dFLSl_aNHa16m3ahKDd50uuZtnxdyR2GUmvzQxJGttitztkiDoxyA9Y7GAcEHE5AIcuwftNbPvUuZQnsU1fUZJ34aCjtiFMYIqMcOhGGVbWqOvdW_ytnale_4KqU9VA3pPHOpiu_ONfPLicjMvEXqiaq_sSzl7buRM8J9xEa0SwXO17ifrB6UFIkLRuBtE82sOJNvaTjF5SpOsicM-chwbXMfdSNkiBkJSubjaEHl0wXUY2Xl_bJ1OD4oWAwBUatNkr5gMug0ihTt1OZ2nzJIe7KJ6m8wlM0gnoV0inSeWuECftsY6LIHxmW3PDo2EGzeKO5XS0H7gHdtTVn-eBWrh44GQT0yAmtiskdX807Qzinpoa6x1KQWXtPDEBHydfAyYADaF9sqFSNWy6DaF3rjH8fLeIMBn5mtD5jF7htklmlYKjw6InS3gx2SePtaio8se5ZIYeNo0mIlUDQdSjIqCxm6olfRphcVJR8mRubZ-aeZcvLt9cjArJgIltlBypqahIrHhSgqZSkQUbrbVr5Zmf_foMZxo0Xe1i24inVAZRiXBTWZXSxIh1kHcQPtenqoDbPyNG6a2t5XStxxd-jarH40YWctT3TxyZXWXNWgYwvwZWLsDXYgng4bwYqBfg6TdNUhb5-dRW0LYfRx6-ezh4NrEZb96EFWlKKiLkv0LqgTIAja2Myf0JM0f0NV6LIyBvrz-3q5Bd8_drA-BWtbhj52KDd3rdgRGKSDlFNqEH__XXlhw) and click into the stripes on the right. Notice that the diff editor does not get focus.
