### ISSUE TITLE
Editor actions toolbar should always show "Close" button

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#193723]
With the new diff editor I am now hitting what seems to be a limit of primary actions that we are willing to display. I think the limit makes good sense. However, I think the close action should probably always be visible because when you have tabs disabled, that is essentially the one action that is always at a stable location (at the end):

![Image](https://github.com/microsoft/vscode/assets/900690/c4f5dad8-933f-43c2-9416-cd17d3fd8121)

However with the limit hit, that action moves out of view:

![Image](https://github.com/microsoft/vscode/assets/900690/b7dee944-550e-485b-9e91-f4f743d6233a)

I think it would be nice if somehow I could instruct the menu to always make sure the close action is visible, even when the menu has many entries.

**Comment by jrieken** [comment]
Also a longstanding issue when using gitlens. Stretch for September. Workaround is to hide actions that aren't needed that often

**Comment by bpasero** [comment]
Related, @hediet I wonder if the action to toggle between showing unchanged regions or not in a diff editor could be an action that lives inside the "..." menu, similar to changing between inline diff and side by side?

**Comment by jrieken** [comment]
@bpasero pushing a change for close but I wonder if we should do the same for split?

**Comment by bpasero** [comment]
@jrieken yeah good point: https://github.com/microsoft/vscode/pull/193778
