### ISSUE TITLE
Enable vim usage in all (text) input fields

### ISSUE THREAD

**Issue by JustAGabriel** [microsoft/vscode#193759]
hi there!
for the sake of convenience it would be nice to be able to use VIM in all input fields.
i currently only have the text input fields in mind.

background:
i just realised that i can not use VIM in the git commit message input field, that's why i created this feature request.

**Comment by lszomoru** [comment]
@JustAGabriel, could you please elaborate further on this feature request? How are you expecting to use VIM to edit the commit input field in VS Code? If you would like to author your commit message using VIM, you would have to commit from the VS Code integrated terminal, or an external Terminal.

**Comment by JustAGabriel** [comment]
hi @lszomoru!

thanks for your reply! 

i thought it would be intuitiv/practical to have vim motions in all text fields available while being in _vim_ mode.

just realized that's most likely something that would then have to be enabled/handled by the vim plugin.
i will create a feature request there.

sorry for wasting your time.

br
gabriel
