### ISSUE TITLE
[Insiders today] Previously configured icon for a profile is missing

### ISSUE THREAD

**Issue by gjsjohnmurray** [microsoft/vscode#193763]
Type: <b>Bug</b>

Earlier this week I set `rocket` as the icon for one of my profiles and was pleased to see it replace the gearwheel in Activity Bar.

After updating this morning there is now no icon at that position. I can still get the Manage menu, go to Profiles and pick Edit. The rocket icon doesn't show there either, but if I click in exactly the right place (see screenshot) I can get the icon picker again.

![image](https://github.com/microsoft/vscode/assets/6726799/ecb0f4ce-3f87-431b-83d7-ce968167b077)

VS Code version: Code - Insiders 1.83.0-insider (444399e23bda3e216152098d848bd7b95d80b0e5, 2023-09-22T05:34:48.628Z)
OS version: Windows_NT x64 10.0.22621
Modes:

**Comment by gjsjohnmurray** [comment]
Off-topic, IMO the icon in this screenshot is too far right:

![image](https://github.com/microsoft/vscode/assets/6726799/64c95770-4557-4759-9b81-d309dabe0145)

**Comment by sandy081** [comment]
> I'm guessing it's a one-time consequence of https://github.com/microsoft/vscode/pull/193694, and as an early adopter of profile icons I don't mind having to set my choice again. But I decided to report the issue in case it's a symptom of something else being wrong.

Yes, that's the reason. (I too noticed that). If you can fix it yourself, I would not make a change. Thanks.

**Comment by gjsjohnmurray** [comment]
Yes, I was able to set the icon again. Closing.

**Comment by sandy081** [comment]
Fixed the width

![image](https://github.com/microsoft/vscode/assets/10746682/94e474ea-98e9-44bb-bbb1-98080f794336)
