### ISSUE TITLE
Code action provider not called on initial open

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#19371]
Test: https://github.com/Microsoft/vscode/issues/19046

- VSCode Version: 1.9
- OS Version: Windows

Steps to Reproduce:

1. Test case
``` ts
class A {

}

class B extends A {
	constructor() {
        super();
    }
}
```
2. have the cursor inside super
3. reload the window

Observe: the code action provider is not called. Note that there is no error on super(); The code action provider is call if the token under the cursor has an error.

**Comment by roblourens** [comment]
I don't understand the bug - should there be a code action on `super()`? It looks like there shouldn't be.

**Comment by jrieken** [comment]
You need an extension that registers a `CodeActionProvider`. It should be called for actions not only one typing also when the file initially loads.

**Comment by roblourens** [comment]
Got it, verifying
