### ISSUE TITLE
VS Code sluggish typing & interaction experience

### ISSUE THREAD

**Issue by Yerenzter** [microsoft/vscode#193793]
Type: <b>Performance Issue</b>

When I type my code to the editor the response time delays about 500-600 ms plus when I used VS Code in my Ubuntu 22 (Jammy Jellfish) Linux in my Dell Chromebook 11 it became sluggish all the time even though when I saw the usage of VS Code in task manager the memory usage is less.

VS Code version: Code 1.82.2 (abd2f3db4bdb28f9e95536dfa84d8479f1eb312d, 2023-09-14T05:51:20.981Z)
OS version: Linux x64 4.4.275-20726-g204ae1828356
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Celeron(R) CPU  N2840  @ 2.16GHz (2 x 2582)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: disabled_off<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|2, 1, 1|
|Memory (System)|3.77GB (2.01GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|xfce|
|XDG_CURRENT_DESKTOP|XFCE|
|XDG_SESSION_DESKTOP|undefined|
|XDG_SESSION_TYPE|undefined|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    1	   143	  6212	code main
    0	    43	  6217	   zygote
    1	    81	  6276	     gpu-process
    0	     0	  6218	   zygote
    0	    43	  6224	     zygote
    0	     8	  6227	       zygote
    0	   216	  6308	window [1] (● +page.svelte - lgub-hrms - Visual Studio Code)
    3	    93	  6819	window [2] (Issue Reporter)
    0	    58	  6286	   utility-network-service
    0	   120	  6412	extensionHost [1]
    0	   205	  6466	     electron-nodejs (/usr/share/code/code --ms-enable-electron-run-as-node --experimental-modules /home/yerenzter/.vscode/extensions/svelte.svelte-vscode-107.11.0/node_modules/svelte-language-server/bin/server.js --node-ipc --clientProcessId=6412)
    0	    81	  6423	shared-process
    0	     0	  6833	     /bin/sh -c /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0	     0	  6834	       /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0	    73	  6424	fileWatcher [1]
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (● +page.svelte - lgub-hrms - Visual Studio Code)
|    Folder (lgub-hrms): 28 files
|      File types: js(6) json(2) svelte(2) eslintignore(1) cjs(1) gitignore(1)
|                  npmrc(1) prettierignore(1) prettierrc(1) md(1)
|      Conf files: jsconfig.json(1) package.json(1);
```

</details>
<details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
materialize-snippets|len|1.4.5
svelte-vscode|sve|107.11.0

</details>

**Comment by amanos1022** [comment]
I'm experiencing similar issues. Typing fast drops some key strokes. I _think_ it started in the last week or so (so after the August 2023 release). I'm on Debian 10 (buster) Dell XPS i7.

**Comment by connor4312** [comment]
Please collect some profile information using these instructions: https://github.com/microsoft/vscode/wiki/Performance-Issues#sluggish-ui

**Comment by amanos1022** [comment]
> Please collect some profile information using these instructions: https://github.com/microsoft/vscode/wiki/Performance-Issues#sluggish-ui

I tried this but the `Trace-*.json` files had 0 bytes. Tried a couple things; export from google-chrome works as expected, tried to search for solutions, found no help. Obviously a different issue, but didn't want to leave you hanging.

**Comment by connor4312** [comment]
Closing as we have not heard from the reporter
