### ISSUE TITLE
No longer possible to backspace to delete a slash command in panel chat input

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode#193702]
This still works in the inline chat input

https://github.com/microsoft/vscode/blob/a67f43546714f007d23e8df228b04f4c492cce5e/src/vs/workbench/contrib/chat/browser/chatSlashCommandContentWidget.ts#L60-L78

**Comment by roblourens** [comment]
I'm not using the content widget anymore, but we will probably go back to a content widget, so I didn't get around to fixing it for an editor decoration
