### ISSUE TITLE
Squiggly Lines and Errors

### ISSUE THREAD

**Issue by ZavierHoward** [microsoft/vscode#193718]
Type: <b>Bug</b>

My VSCode will not report any errors I have for C# code I am writing for Unity. I turned the enable error squiggles command to enable, but still nothing.

VS Code version: Code 1.82.2 (abd2f3db4bdb28f9e95536dfa84d8479f1eb312d, 2023-09-14T05:55:25.390Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.73GB (2.94GB free)|
|Process Argv|C:\\Users\\zavie\\Downloads\\Majestic Signs -g C:\\Users\\zavie\\Downloads\\Majestic Signs\\Assets\\Wizard.cs:1:0 --crash-reporter-id 0608d524-eaf9-4aac-b71b-9e4801438004|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
auto-using|Fud|0.7.15
csdevkit|ms-|0.4.10
csharp|ms-|2.1.2
vscode-dotnet-runtime|ms-|1.7.3
vscodeintellicode-csharp|ms-|0.1.26
python|ms-|2023.16.0
vscode-pylance|ms-|2023.9.20
cpptools|ms-|1.17.5
vstuc|vis|0.9.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vstes627:30244334
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
3biah626:30602489
89544117:30613380
a9j8j154:30646983
showlangstatbar:30737416
03d35959:30757346
pythonfmttext:30731395
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
pythonnosmt12:30797651
pythonidxptcf:30805731
pythonnoceb:30805159
copilotsettingt:30839829
asynctok:30821568
dsvsc013:30795093
dsvsc014:30804076
diffeditorv2:30821572
dsvsc015cf:30829746

```

</details>

**Comment by roblourens** [comment]
Please file this on the C# extension or check their docs
