### ISSUE TITLE
Black rectangles which disappear on hover-induced repaint

### ISSUE THREAD

**Issue by notduncansmith** [Microsoft/vscode#19376]
- VSCode Version: Code 1.8.1 (ee428b0eead68bf0fb99ab5fdc4439be227b6281, 2016-12-19T14:42:49.304Z)
- OS Version: Darwin x64 16.3.0
- Extensions:

|Extension|Author|Version|
|---|---|---|
|base16-themes|AndrsDC|1.0.6|
|vscode-multi-line-tricks|bigous|0.0.3|
|Theme-OceanKit|chipcollier|0.0.2|
|vscode-babel-coloring|dzannotti|0.0.4|
|theme-base16-ocean|golf1052|1.0.1|
|spacegray-vscode|ionutvmi|1.1.4|
|sublime-babel-vscode|joshpeng|0.2.4|
|theme-charcoal-oceanicnext|joshpeng|1.1.4|
|vscode-colorize|kamikillerto|0.1.2|
|Oceanic-Next|mhartington|0.0.1|
|theme-oceanicnext|naumovs|0.0.4|
|vscode-parinfer|shaunlebron|0.4.0|

---

Steps to Reproduce:

1. Open sidebar
2. Not sure exactly...
3. Close sidebar
4. A wild Black Rectangle appears on the right-hand side of the screen
5. Hover over said rectangle
6. Rectangle disappears

I'm not sure exactly what triggers it but I will update with details and screenshots if I notice it again. I'm hoping this is a known or recognizable issue from this description. Thanks for your hard work, VSCode folks! It has been a pleasure to use so far.

**Comment by bpasero** [comment]
#12473

**Comment by notduncansmith** [comment]
Sorry, visually this appears different from what I'm seeing in that thread and related ones. Might still be the same bug, though.
