### ISSUE TITLE
MarkdownString.appendCodeblock is not escaping code block border.

### ISSUE THREAD

**Issue by DiscreteTom** [microsoft/vscode#193746]
Does this issue occur when all extensions are disabled?: Yes

Version: 1.82.2 (user setup)
Commit: abd2f3db4bdb28f9e95536dfa84d8479f1eb312d
Date: 2023-09-14T05:55:25.390Z
Electron: 25.8.1
ElectronBuildId: 23779380
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.22621

Steps to Reproduce:

````js
console.log(new vscode.MarkdownString().appendCodeblock('```', txt")).value
````

Got:

`````txt
```txt
```
```
`````

Expected(code block border is escaped with more `` ` `` or `~`):

`````txt
````txt
```
````
`````

**Comment by lifez** [comment]
I would like to work on this.
