### ISSUE TITLE
Consider make tab file path truncations for paths out of the folder show the drive/root

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#19384]
- VSCode Version: Code - Insiders 1.9.0-insider (fbea777a881523bc01a1358d115b16673dc5942e, 2017-01-25T07:19:27.879Z)
- OS Version: Linux x64 4.8.0-34-generic
- Extensions:

|Extension|Author|Version|
|---|---|---|
|EditorConfig|EditorConfig|0.3.4|
|Ionide-fsharp|Ionide|2.20.0|
|lorem-ipsum|Tyriar|1.0.0|
|sort-lines|Tyriar|1.2.0|
|theme-glacier|Tyriar|0.0.10|
|vscode-svgviewer|cssho|1.3.0|
|gitlens|eamodio|1.4.3|
|tslint|eg2|0.8.1|
|git-project-manager|felipecaputo|1.0.1|
|md-navigate|jrieken|0.0.1|
|vscode-scss|mrmlnc|0.6.0|
|seti-icons|qinjia|0.1.3|

---

Testing https://github.com/Microsoft/vscode/issues/12040

Consider the following example:

![image](https://cloud.githubusercontent.com/assets/2193314/22302986/17cb5818-e2e6-11e6-90e7-1ec3158cb186.png)

There is no way of telling whether gulpfile.js that said .../vscode-docs is in or out of the opened folder. These would be preferable to make clear they're outside the folder:

- `/.../vscode-docs`
- `C:\...\vscode-docs`

**Comment by bpasero** [comment]
Yeah I like that 👍

**Comment by bpasero** [comment]
@Tyriar maybe you could verify this one
