### ISSUE TITLE
deleted project

### ISSUE THREAD

**Issue by mora12p** [microsoft/vscode#193860]
Type: <b>Feature Request</b>

i enter a code by mistake and i exit from the file and it saved please help me it is a big problem  I work in a big company  and it be finished tomorrow

VS Code version: Code 1.82.2 (abd2f3db4bdb28f9e95536dfa84d8479f1eb312d, 2023-09-14T05:55:25.390Z)
OS version: Windows_NT x64 10.0.22000
Modes:

**Comment by lramos15** [comment]
If you have local history you can likely look in the timeline view under the explorer.
