### ISSUE TITLE
VS Code insiders breaks C# and C++ debuggers with 'Cannot determine executable for debug adapter' error

### ISSUE THREAD

**Issue by gregg-miskelly** [Microsoft/vscode#19386]
- VSCode Version: 1.9.0-insider, Commit fbea777a881523bc01a1358d115b16673dc5942e
- OS Version: Windows 10 (10.0.14393)

Steps to Reproduce:
1. Follow instructions on https://github.com/OmniSharp/omnisharp-vscode/blob/master/debugger.md for installing .NET Core, creating a sample project, and getting the debugger
2. After the debugger is installed, restart VS Code
3. Try to debug

Result:
Cannot determine executable for debug adapter 'C:/Users/\<username\>/.vscode-insiders/extensions/ms-vscode.csharp-1.6.2/.debugger/OpenDebugAD7.exe'.

**Comment by pieandcakes** [comment]
@weinand @isidorn I wonder if this has to do with commit: 95d1342bbeef6fce6b2cf075ce024bdb860f4cef

**Comment by weinand** [comment]
The problem is a broken `isAbsolute()` method from `vs/base/common/paths` which does not recognise a path "C:/Program Files/nodejs/node.exe" as absolute.
I've fixed this by using node's `isAbsolute()` method.
