### ISSUE TITLE
markdown previews in notebooks should use markdown.preview.lineHeight config

### ISSUE THREAD

**Issue by amunger** [microsoft/vscode#193857]
How do I control the line height of Markdown cells in Jupyter in VS Code? The editor cell line height is fine. However, when I click the check mark to see the formatted text, the lines are very close to one another and quite hard to read. By contrast, regular VS Code (non-Jupyter) Markdown Preview line height is fine. Also, the same notebooks shown in (non-VS Code) Juypter are fine.

I'm using the latest VS Code and Jupyter extension, latest Linux Mint OS.

There is a `markdown.preview.lineHeight` setting in VS code, however that does not appear to apply to Jupyter.

Is there some other setting somewhere that will solve the issue?

_Originally posted by @paul-rogers in https://github.com/microsoft/vscode-jupyter/discussions/14306_

**Comment by paul-rogers** [comment]
It seems the problem may be that the notebook extension is missing a Markdown output line height that would parallel the setting for Markdown preview.

The following works for Markdown preview (for `.md` files):

```json
"markdown.preview.lineHeight": 1.6
```

Changing the value to, say, 3, causes the expected result in Markdown preview. However, the above _does not_ affect the markdown output in notebooks. Perhaps this makes sense as Markdown preview is a separate extension from notebooks?

The following correctly adjusts the font size for Markdown output in notebooks:

```json
"notebook.markup.fontSize": 18
```

The following correctly adjusts the _output_ line height, where "output" means the output of a Python cell:

```json
"notebook.output.lineHeight": 3
```

The above has _no effect_ on Markdown output.

Conclusion: the notebook extension is missing a "markdown line height" setting that works like the one for Markdown preview.

**Comment by paul-rogers** [comment]
To make clear the issue, here is a sample of notebook Markdown output. Note how the lines are a bit too close together:

![VS_Code_Output](https://github.com/microsoft/vscode/assets/3248881/b617d49a-5f8e-4c54-b2c3-7a718f35b81d)

Here is the same text after exporting the notebook to HTML and opening it in Firefox:

![Firefox_Export_output](https://github.com/microsoft/vscode/assets/3248881/133eab97-7227-407d-9487-37761dc625b1)

Note that the line spacing is different in the two renders. I fiddled with the various line settings: none change the line spacing in the exported HTML. Instead, it seems formatting is controlled by Jupyter-provided style sheets inlined into the HTML file.

The Markdown line height in the exported HTML file is controlled by this CSS:

```css
.jp-RenderedHTMLCommon {
 ...
  line-height: var(--jp-content-line-height);
  ...
}
```

Which is set as:

```css
--jp-content-line-height: 1.6;
```

**Comment by paul-rogers** [comment]
Debugging question: the above note located the style sheet information by exporting to HTML. However, it is appears that the HTML output is a bit different than the HTML used within VS Code. For example, none of the VS Code settings I fiddled with seemed to change the format of the exported HTML.

Is there a way to see the HTML source or the VS Code notebook view? Searched around and could not see anything. Seeing the source might let us track down how the Markdown line height is supposed to be set.

**Comment by amunger** [comment]
I believe you're looking for "Developer: Toggle developer tools "

**Comment by mjbvz** [comment]
This should be a new setting like `notebook.markup.fontSize`. `markdown.preview.lineHeight config` is specially for the markdown preview

**Comment by lifez** [comment]
I would like to work on this.

**Comment by kamransoomro84** [comment]
I would really like this too. The current output is too dense and looks really ugly.

**Comment by DatN99** [comment]
@lifez Are you still working on this?

**Comment by lifez** [comment]
@DatN99 I didn't

**Comment by paul-rogers** [comment]
Would be great if someone could pick this one up. Might be a good starter issue for someone who wants to work out the plumbing behind the scenes. A good first step would be to identify if there is some CSS file that use users could modify as a workaround.

**Comment by DatN99** [comment]
Sounds good! I can pick this one up

**Comment by paul-rogers** [comment]
Thanks for the fix above! I just noticed another odd discrepancy: if one uses even trivial Latex in a Markdown element within a notebook, one gets very nice spacing. See below, which uses the trivial `$k$` Latex element.

![Example](https://github.com/microsoft/vscode/assets/3248881/c93d13be-373f-49a6-be52-1b992659259f)

**Comment by amunger** [comment]
verification:
- use the `"notebook.markdown.lineHeight"` to change the displayed line height in the markdown preview within a notebook.
- ensure the setting does not affect markdown preview outside of notebooks

**Comment by paul-rogers** [comment]
@DatN99, thanks for the fix!

Confirmed that, on my system, setting the `notebook.markdown.lineHeight` value to 20 produces much more readable text in Markdown cells in notebooks.

The value is in pixels. This means it is dependent on the value set for the font, which is a bit fiddly. Elsewhere in VS code we can use the value of "1.6" which means "1.6 times the font height."That is, the software, not a human, works out the math to figure out the line height in pixels.

If I try to use 1.6 as the value for `notebook.markdown.lineHeight`, I get lines which horribly overlap, so the setting apparently must be in pixels, forcing me to do the math based on the font size selected elsewhere.

I wonder, as a future enhancement, can we apply that trick to Notebook markdown cells to avoid the awkward explicit dependency of `lineHeight` on the selection of font size?

**Comment by gwbx** [comment]
to add to @paul-rogers points : lineheight in pixels doesn't work with variable font size within the same notebook. For instance section titles :  

![Screenshot 2024-06-28 at 09 51 31](https://github.com/microsoft/vscode/assets/9652899/69069923-8875-490c-88b2-f849b156687d)

**Comment by paul-rogers** [comment]
Thanks, @DatN99, I had noticed the same problem: As you showed, a multi-line title section (Markdown "#") has overlapping text. (Workaround: use only single-line titles.)

I very much appreciate the partial fix: regular text is now much easier to read. Would be great if we can add the bells and whistles before too many other folks start using the feature.

**Comment by DatN99** [comment]
@paul-rogers @gwbx Great catch! Working with multiple lines with titles involved may be a bit complicated, because even though titles _may_ have different font sizes, I'm not sure how I can access their exact value to do appropriate calculations. For example, if `notebook.markup.fontSize` was set to 20, the title and body paragraph would each size up to 20, but the title would appear much bigger. Therefore, if I were to set `notebook.markdown.lineHeight` to 2, the overall calculated value would be (20 * 2)px for both the title and the body paragraph. 

<img width="2514" alt="Screenshot 2024-07-01 at 8 23 52 PM" src="https://github.com/microsoft/vscode/assets/86983871/f930dbf8-506a-4add-997b-2d69b69908c2">

While the calculated line-height for both the title and body paragraph is both 40px, the title still appears crammed because its font value will be larger as a result of its title tag. If  you have any suggestions, I'd love to discuss them!

**Comment by paul-rogers** [comment]
@DatN99, I'm afraid I've not taken the time to understand the details of how VS Code or Jupyter handle fonts.

Maybe we can make progress by starting with CSS. Let us hope that the layout is controlled by a CSS style sheet, using the [`line-height`](https://www.w3.org/TR/CSS2/visudet.html#propdef-line-height) attribute. If so, then the value can be specified in a variety of formats. Perhaps the current fix uses pixels: `10px`. It is also possible to use percent: `160%`. Or using a "number" (such as 1.6).

We can also see how other bits of VS Code handle line height:

> **Terminal › Integrated: Line Height** <br>
> Controls the line height of the terminal. This number is multiplied by the terminal font size to get the actual line-height in pixels. 
>
> **Editor: Line Height** <br>
> Controls the line height.
>
> Use 0 to automatically compute the line height from the font size.
> Values between 0 and 8 will be used as a multiplier with the font size.
> Values greater than or equal to 8 will be used as effective values.
>
> **Markdown › Preview: Line Height**<br>
> Controls the line height used in the Markdown preview. This number is relative to the font size.

For the last one, Markdown preview, I use a value of 1.6 (as suggested in a post somewhere) to get a pleasant spacing. One can imagine that the CSS value is `str(int(line_height * 100)) + '%'`. Perhaps a search of the code would reveal the actual logic.

Now, given all that, what options might you have for the Notebook Markdown output line height?

Given that the feature already exists and uses the pixel (`px`) units, perhaps a bit of parsing could allow the CSS syntax. Something like:

* `160%` (for height in percent)
* `10px` (for height in pixels)
* `16pt` (for height in points)
* < 8, e.g. `1.6`, for the "number" form of CSS `line-height
* &gt;= 8 for pixels (for backward compatibility with the current functionality)

At a bare minimum, maybe just do the last two which _may_ be what `Editor: Line Height` does. If so, you can just grab that code.  The others would be useful if someone wants to control the explicit size.

Also, if the VS Code config `line-height` property is blank (which should be the default), don't override the notebook `line-height` CSS property.

Might something like this work here?
