### ISSUE TITLE
SCM Sync view - move Tree/List choice to action button

### ISSUE THREAD

**Issue by gjsjohnmurray** [microsoft/vscode#193815]
Type: <b>Feature Request</b>

At the moment it is exposed as two options on the `...` dropdown menu, with a checkmark against one or the other.

For consistency with the equivalent feature in the main SCM view title bar please reimplement as an action button whose icon changes as you switch state.

VS Code version: Code - Insiders 1.83.0-insider (c72447e8d8aaa7497c9a4bd68bc4301584b92beb, 2023-09-22T09:29:47.641Z)
OS version: Windows_NT x64 10.0.22621
Modes:

**Comment by lszomoru** [comment]
Thanks for the feedback. The "Source Control" view exposes the Tree/List view mode in two places: 1) the title bar, and 2) the `...` menu (View & Sort). I did not want to place it in both locations and I did not think that switching between List/Tree is an action that warrants a prominent place in the title bar. Having said that, let's keep this issue opened to continue to gather feedback.

**Comment by gjsjohnmurray** [comment]
Sync view has been removed.
