### ISSUE TITLE
Errors when debugging a bash script

### ISSUE THREAD

**Issue by francotiveron** [microsoft/vscode#193866]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 
- - OS Version: 
- Version: 1.83.0-insider (user setup)
Commit: c72447e8d8aaa7497c9a4bd68bc4301584b92beb
Date: 2023-09-22T09:29:47.641Z
Electron: 25.8.1
ElectronBuildId: 23779380
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.19045

Steps to Reproduce:

1. Install Bash Debug
![image](https://github.com/microsoft/vscode/assets/8280970/94b3303d-e2f8-40c2-90a0-b197b00d0c3e)

1. Create a bash script
![image](https://github.com/microsoft/vscode/assets/8280970/607c3461-5eb9-45b7-9774-013a61cdc13f)

3. Run debug F5
![image](https://github.com/microsoft/vscode/assets/8280970/db0d7c78-0f85-451f-889a-eb570f6ca895)

**Comment by roblourens** [comment]
Please file an issue on that extension, thanks
