### ISSUE TITLE
Lose terminal scrollback after resizing in vim

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#19385]
Testing https://github.com/Microsoft/vscode/issues/19071

Not sure if this is a bug or expected, but it doesn't repro in the terminal

In Ubuntu 14.04

- Have some output in the terminal like from `ls -l`
- Open vim
- `:q`
- You can still see the output from `ls`, good
- Open vim again
- Resize the terminal
- `:q`
- The vim text is still on screen, and I can't scroll to see the output from `ls`.

**Comment by Tyriar** [comment]
Wow great find! Looks like resize needs to be made aware of the alt buffer.

**Comment by Tyriar** [comment]
Upstream issue https://github.com/sourcelair/xterm.js/issues/510

**Comment by Tyriar** [comment]
Should be fixed
