### ISSUE TITLE
Predict undefined parameters' properties after first run in nodejs

### ISSUE THREAD

**Issue by jd1378** [Microsoft/vscode#19389]
Somewhere in my code i define a function with an object parameter that can be anything ,
somewhere else i call that function with a specific object from a nodejs module ,
now i wan't to add some code to the function , and i wan't visual studio code to know what's gonna used as function parameter.
is it possible ? is it already implemented in vs code or will you add it ?

**Comment by mousetraps** [comment]
So what you're looking for is inference about the type of a parameter based off of having run your code once? Don't think that's planned, but we'll keep it in mind! cc @weinand, @roblourens, @isidorn

**Comment by roblourens** [comment]
I think @jd1378 is asking for static type inference like Flow based on what type is passed to the function, right?

**Comment by jd1378** [comment]
right , i want to run and use the function once and then when i'm not running i want Intellisense to show suggestions about the parameter based on what it was in the last run .

**Comment by roblourens** [comment]
Ok nvm I guess you are asking for what @mousetraps describes.

**Comment by weinand** [comment]
This feature request will not be considered in the next [6-12 months roadmap](https://github.com/Microsoft/vscode/wiki/Roadmap) and as such will be closed to keep the number of issues we have to maintain actionable.
Thanks for understanding and happy coding!
