### ISSUE TITLE
VSCode silently strips prefixed whitespace in file name when saving file.

### ISSUE THREAD

**Issue by RokeJulianLockhart** [microsoft/vscode#193895]
Does this issue occur when all extensions are disabled?: Yes

-	VS Code Version:	

	> Version: 1.83.0-insider

-	OS Version:

	> OS: Linux x64 6.5.3-1-default

	More specifically, cpe:/o:opensuse:tumbleweed:20230920

<blockQuote>
	
Commit: c72447e8d8aaa7497c9a4bd68bc4301584b92beb
Date: 2023-09-22T09:29:40.641Z
Electron: 25.8.1
ElectronBuildId: 23779380
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
	
</blockQuote>

Steps to Reproduce:

0.	Save a file with the name

	```txt
		`{name: "rules",	id: "s1grux"}`{.json5}.txt.md
	```

0.	The prefixed tab shall be silently removed (yet the middle one remains).

This is erroneous because it is both unnecessary on BTRFS, per https://en.wikipedia.org/wiki/Comparison_of_file_systems#:~:text=any%20byte%20except%20'%2F'%20and%20nul%20

> **Allowable characters**  
> Any byte except '/' and NUL 

and OS/kernel, but more importantly, because **it is not communicated to the user**.

I expect that this is a holdover from Windows, where the Win32 API doesn't like them, per https://superuser.com/a/738008.

> Do not end a file or directory name with a space. Although the underlying file system may support such names, the Windows shell and user interface does not.

**Comment by bpasero** [comment]
@RokeJulianLockhart you use the VS Code explorer to create this name? Or some other way in VS Code?

**Comment by RokeJulianLockhart** [comment]
> create this name?

"Create" it? I'm confused by what this means. I typed it, like most text. It's all only ASCII, after all (albeit indeed transcoded to Unicode obviously). If you're asking how I entered a tab into the GTK file manager (since VSCode doesn't use the XDG portal) I just typed it in VSCode, copied it, then pasted it.

Is usage of any of these characters unusual perhaps?

**Comment by bpasero** [comment]
Yeah I am curious where the whitespace is stripped, if its from a native file dialog or our file explorer.

/gifPlease

**Comment by RokeJulianLockhart** [comment]
> https://github.com/microsoft/vscode/issues/193895#issuecomment-1733938622

In retrospect, @bpasero, this might be caused by https://docs.gtk.org/gtk4/class.FileDialog.html.

Using

> ```txt
> 	`{comment: "temporary",	id: ""}`{.json5}.dir
> ```

I tested it again

https://github.com/microsoft/vscode/assets/42837531/aadd2d5d-f36e-442e-91ca-92fc4070c00a

Yes, I know the depicted filesystem layout is unique. XD

**Comment by RokeJulianLockhart** [comment]
https://download.opensuse.org/repositories/openSUSE:/Factory/standard/src/gnome-text-editor-45.0-1.1.src.rpm behaves identically, despite using the GTK4 (rather than GTK3) dialog, so it's probably caused by GTK. Unfortunately, I can't *confirm* due to https://github.com/microsoft/vscode/issues/50386#issue-326016102 meaning I can't force VSCode to use Dolphin.

**Comment by bpasero** [comment]
So it does not seem like an issue VS Code can solve?

**Comment by RokeJulianLockhart** [comment]
It saves correctly with `files.simpleDialog.enable` enabled. So can you just reiterate what you consequently believe to be causing it, @bpasero? I ask because I didn't consider that KDE was the sole other option than VSCode, because a bug in GTK appears to me to be a more probable cause.

**Comment by RokeJulianLockhart** [comment]
https://gitlab.gnome.org/GNOME/gtk/-/issues/6119

**Comment by RokeJulianLockhart** [comment]
https://bugs.kde.org/show_bug.cgi?id=474950

**Comment by RokeJulianLockhart** [comment]
Per https://www.reddit.com/r/openSUSE/comments/u0n233/comment/k2lcl0o/?utm_source=share&utm_medium=web2x&context=3,

> ```sh
> GTK_USE_PORTAL=1 code-insiders
> ```

I've been able to verify whether this occurs using the KDE portal, and a different but identically caused error indeed occurs.

![Screenshot_20231001_205521](https://github.com/microsoft/vscode/assets/42837531/f5265ba9-5b90-42a4-90aa-6e8b81b53bf3)
