### ISSUE TITLE
workspacesTrustedToSpecifyExecutables squiggles decoration is not updated when save

### ISSUE THREAD

**Issue by rebornix** [Microsoft/vscode#19388]
- VSCode Version: 1.9.0-insiders
- OS Version: macOS

Steps to Reproduce:

1. Add executable related configuration to workspace setting and save
2. The popup window shows immediately.
3. The squiggle will only show after switching tabs. So after the warning message displayed in the popup and click Review Setting to see which one is actually leading to the problem, ppl still have no idea as the inline warning is missing.

 However if you add an unknown setting, the green squiggle shows up the moment you save.

**Comment by kieferrm** [comment]
Doesn't apply anymore as we change the functionality.
