### ISSUE TITLE
Test: terminal accessible view

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#193852]
Refs #192338

- [x] Windows @bamurtaugh 
- [x] macOS @sandy081 
- [x] Linux @justschen 

Complexity: 3

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23193852%0A%0A&assignees=meganrogge)

---

The terminal's accessible view was formerly overlaid on the xterm instance and accessed with `Shift+Tab`. Now, we use the accessible view like other components (chat, notebook, notifications, etc.).

With focus in the terminal, this can be accessed via `alt+f2` or `cmd/ctrl+up arrow`. It can be exited via `exit` or `cmd/ctrl+down arrow`.

Use the terminal accessibility help dialog (`alt+f1`) to find what actions can be taken and verify that all of these work. 

Move a terminal to the editor area and repeat your testing.

**Comment by bhavyaus** [comment]
@justschen if you're the last one on test plan, you can close it out after unassigning yourself.
