### ISSUE TITLE
Tab file path truncation of files in folder root should show `.`

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#19382]
- VSCode Version: Code - Insiders 1.9.0-insider (fbea777a881523bc01a1358d115b16673dc5942e, 2017-01-25T07:19:27.879Z)
- OS Version: Linux x64 4.8.0-34-generic
- Extensions:

|Extension|Author|Version|
|---|---|---|
|EditorConfig|EditorConfig|0.3.4|
|Ionide-fsharp|Ionide|2.20.0|
|lorem-ipsum|Tyriar|1.0.0|
|sort-lines|Tyriar|1.2.0|
|theme-glacier|Tyriar|0.0.10|
|vscode-svgviewer|cssho|1.3.0|
|gitlens|eamodio|1.4.3|
|tslint|eg2|0.8.1|
|git-project-manager|felipecaputo|1.0.1|
|md-navigate|jrieken|0.0.1|
|vscode-scss|mrmlnc|0.6.0|
|seti-icons|qinjia|0.1.3|

---

Testing https://github.com/Microsoft/vscode/issues/12040

I think this was meant to be done in https://github.com/Microsoft/vscode/pull/18575 but latest Insiders doesn't show that:

![image](https://cloud.githubusercontent.com/assets/2193314/22302892/af5740bc-e2e5-11e6-915b-7bc9bb7d7711.png)

The reason for wanting this is to easily be able to check that you have multiple files with the same name open at the same time since not all tabs may be visible at once.

/cc @hun1ahpu

**Comment by bpasero** [comment]
PR welcome.
