### ISSUE TITLE
Executing cell can resize itself out of view

### ISSUE THREAD

**Issue by amunger** [microsoft/vscode#193835]
1. Create a notebook with and execute a cell with the code
```
import time
time.sleep(2)
for i in range(10):
    print(i)
print('the result')
```
2. scroll down so just the output is visible
3. select the cell and press ctrl+enter to execute it again
:bug: cell is gone, you have to scroll up to see the output you were expecting
![Recording 2023-09-22 at 11 25 53](https://github.com/microsoft/vscode/assets/2019016/f43ca980-96ee-43e9-a536-8c30d9eb698f)

**Comment by joaomoreno** [comment]
Pending on https://github.com/microsoft/vscode/issues/193231

**Comment by amunger** [comment]
fixed by https://github.com/microsoft/vscode/pull/195283
