### ISSUE TITLE
In-file search does not reveal hidden unchanged regions

### ISSUE THREAD

**Issue by schonarth** [microsoft/vscode#193834]
Type: <b>Bug</b>

Steps to reproduce:
1. Configure Diff Editor to hide unchanged regions
2. Open a file's diff so that parts of it will be hidden
3. Ctrl/cmd+F and search for something that is in the hidden portions of the document

Expected result:
- Found text should be revealed (and some lines around it preverably as well)
- Searching for pieces of text/code should make it easy to spot occurrences of the search term immediately

Actual result: 
- Found text remains in hidden portions of the file, making it difficult to locate it
- It took me some time to realize it was hidden; until then I was just searching among the visible portions of the file
- Search functionality that does not make it easy to quickly reach found terms becomes frustrating; even more so than having to scan a long document without hidden regions

VS Code version: Code 1.82.2 (Universal) (abd2f3db4bdb28f9e95536dfa84d8479f1eb312d, 2023-09-14T05:59:47.790Z)
OS version: Darwin arm64 22.5.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|2, 3, 3|
|Memory (System)|8.00GB (0.05GB free)|
|Process Argv|--crash-reporter-id d4b76660-9f36-4272-adde-460b64a90944|
|Screen Reader|yes|
|VM|0%|
</details><details><summary>Extensions (81)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-nvm|abu|0.0.1
Bookmarks|ale|13.4.1
vscode-css-modules|and|1.2.3
lit-html|bie|1.11.1
vscode-intelephense-client|bme|1.9.5
mermaid-markdown-syntax-highlighting|bpr|1.5.2
vscode-tailwindcss|bra|0.10.0
vscode-toggle-max-editor|cbu|0.0.2
js-auto-backticks|cha|1.0.0
path-intellisense|chr|2.8.4
package-json-upgrade|cod|2.1.0
meld-diff|dan|1.4.1
vscode-eslint|dba|2.4.2
xml|Dot|2.5.1
es7-react-js-snippets|dsz|4.4.3
gitlens|eam|14.3.0
vscode-html-css|ecm|1.13.1
EditorConfig|Edi|0.16.4
vscode-npm-script|eg2|0.3.29
prettier-vscode|esb|10.1.0
auto-close-tag|for|0.5.14
auto-rename-tag|for|0.1.10
copilot|Git|1.115.430
copilot-chat|Git|0.7.1
vscode-pull-request-github|Git|0.73.2023091209
vscode-graphql-syntax|Gra|1.2.2
json2ts|Gre|0.0.6
todo-tree|Gru|0.0.226
debug-visualizer|hed|2.4.0
output-colorizer|IBM|0.1.2
css-to-jss|inf|1.0.7
path-autocomplete|ion|1.25.0
vscode-peacock|joh|4.2.2
sftp|lix|1.12.10
ts-extension-pack|loi|0.3.0
call-graph|Luo|1.1.2
layout-editor|luv|0.0.1
camelcasenavigation|map|1.1.5
syntax-project-pbxproj|mar|0.1.3
git-graph|mhu|1.30.0
dotenv|mik|1.0.1
vscode-docker|ms-|1.26.1
vscode-kubernetes-tools|ms-|1.3.13
isort|ms-|2023.10.1
python|ms-|2023.16.0
jupyter|ms-|2023.8.1002501831
remote-containers|ms-|0.309.0
remote-ssh|ms-|0.106.4
remote-ssh-edit|ms-|0.86.0
remote-wsl|ms-|0.81.4
vscode-remote-extensionpack|ms-|0.24.0
powershell|ms-|2023.6.0
remote-explorer|ms-|0.4.1
remote-server|ms-|1.4.3
vsliveshare|ms-|1.0.5883
vscode-react-native|msj|1.12.0
sftp|Nat|1.16.3
back-n-forth|nic|3.1.1
fix-json|oli|0.1.2
tsimporter|pmn|2.0.1
vscode-css-peek|pra|4.4.1
vscode-thunder-client|ran|2.12.1
vscode-yaml|red|1.14.0
jsrelativeimport|rom|1.0.8
partial-diff|ryu|1.4.3
text-marker|ryu|1.11.0
svg-preview|Sim|2.8.3
diff-ui|sol|0.0.5
move-ts|str|1.12.0
vscode-editor-group-minimizer|suh|1.3.2
vscode-mermaid-editor|tom|0.19.1
vscode-mdx|uni|1.4.0
errorlens|use|3.13.0
highlight-matching-tag|vin|0.11.0
console-ninja|Wal|0.0.226
quokka-vscode|Wal|1.0.565
wallaby-vscode|Wal|1.0.370
vscode-todo-highlight|way|1.0.5
fig|wit|0.0.7
vscode-import-cost|wix|3.3.0
pretty-ts-errors|yoa|0.5.2

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
py29gd2263cf:30792227
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
282f8724:30602487
89544117:30613380
showlangstatbar:30737416
962ge761:30841074
a2ce3375:30757347
7ij38806:30736111
pythonfmttext:30731395
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
pythonnosmt12:30797651
pythonidxpt:30805730
pythonnoceb:30805159
copilotsettingc:30839828
synctok:30821570
dsvsc013:30795093
dsvsc014:30804076
diffeditorv2:30821572
dsvsc015:30829745

```

</details>

**Comment by adamsol** [comment]
This seems to have been slightly improved recently, i.e. text is revealed, but together with potentially hundreds of other lines, which is impractical. I guess that only a small fragment of `contextLineCount` lines surrounding the text should be revealed instead.

The current behaviour can be reproduced in the [Monaco Playground](https://microsoft.github.io/monaco-editor/playground.html?source=v0.50.0#XQAAAALxEQAAAAAAAABBqQkHQ5NjdMjwa-jY7SIQ9S7DNlzs5W-mwj0fe1ZCDRFc9ws9XQE0SJE1jc2VKxhaLFIw9vEWSxW3yscxahHbk_7RaxvTpxkYn3V-u8LX9aoCz6W93JdE-E7gNRYqv4Nj7ofd3sXvMZS3Q7wGKETF2-D42O7I090YntPxQ__nU7ZppDAgCRPFaAjVbn6Dsgc08REFK388tlMPtBfCLR0x19cPb-syrihplIz8m_ed63MK9FH47qVi9VukSPo6IIPihyEOnUrQFF7Ip5Rj_zevWe5zEfzLa3VdAtBoBuUvHkO7u-bfplmwMpG5fR5X09NRagFPV9BxT1xMA8Jkoio0oKUhHd7xlNBWPjCvqRfY25oSsFjaAAcRNavvB6NEMPjAnGW2Q9iPhxm36qPk4YdlLB07NUjeB_uGrVdrX1-Be2QbietkL68IPya1lJZthHNKndkIQddGCBj5O1g7Uajvxsq5Ft2arze4A__pCMAq).

**Comment by adamsol** [comment]
For clarity, currently the effect in my example is like this:

![current](https://github.com/user-attachments/assets/349fd111-b9b9-4e09-95f7-e0db24419d41)

And what one would most probably expect is this:

![expected](https://github.com/user-attachments/assets/30f5e743-dfd0-4614-8d32-74e2a5dd6c2e)

Since the whole folding machinery is already in place, I thought it would be an easy fix to reveal just the small fragment around the text instead of those large sections. But if for some reason it's more complicated and the current behaviour is on purpose, then I guess this issue can just be closed, as the original problem seems to be resolved.

**Comment by hediet** [comment]
@adamsol can you create a new issue? I like the idea, but it is not trivial.
