### ISSUE TITLE
Search Editor: Can't open result with any keybindings, only with double-click

### ISSUE THREAD

**Issue by jdanbrown** [microsoft/vscode#193855]
Type: <b>Bug</b>

Repro:
- Open Search Editor → make a search with results
- Double-click a result to open it → correctly opens editor for the result
- Do any keybinding on a result to open it → fails to open the result
  - cmd+enter → inserts a blank line in the Search Editor buffer
  - cmd+down → jumps to the bottom of the Search Editor buffer
  - enter → inserts a blank line in the Search Editor buffer
  - ctrl+enter → nothing happens

It seems like the Search Editor is mapping all these keys to normal editing commands instead of the search actions? (Should the Search Editor be editable in the first place?)

<img width="876" alt="image" src="https://github.com/microsoft/vscode/assets/627486/50fd4c98-cc72-4f2c-8137-ff8ccb362f53">

VS Code version: Code - Insiders 1.83.0-insider (Universal) (11bfd76a61a299156a9f3138ecfad70937af3527, 2023-09-21T05:35:46.439Z)
OS version: Darwin arm64 22.6.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Max (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|64.00GB (1.42GB free)|
|Process Argv|--crash-reporter-id cb425818-8a3a-4635-a2ba-c031aec9b12c|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythontb:30258533
pythonptprofiler:30281269
vshan820:30294714
vscod805:30301674
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30404738
py29gd2263:30784851
vsclangdf:30492506
c4g48928:30535728
dsvsc012:30540252
pynewext54:30618038
2i9eh265:30646982
showlangstatbar:30737417
7ij38806:30687742
pythonfmttext:30716741
fixshowwlkth:30771523
showindicator:30805243
pythongtdpath:30726887
i26e3531:30792625
welcomedialog:30812478
pythonnosmt12:30779711
pythonidxpt:30768918
pythonnoceb:30776497
copilotsettingt:30808721
synctok:30821570
dsvsc013:30777762
dsvsc014:30777825
diffeditorv2:30786206
pythonlinttypecf:30823782
pythonmpsinfo:30842935
dsvsc015:30821418
pythontestfixt:30826906
pythonfb280951:30830809
pythonregdiag:30842812
pythonmypyd1:30841190

```

</details>

**Comment by andreamah** [comment]
These are actually shortcuts for the search viewlet (which can be accessed from the sidebar). For example, from the sidebar search viewlet, you can use cmd+enter to show the equivalent results in the search editor. This is different from double-clicking a result when you're already in the search editor.

**Comment by jdanbrown** [comment]
Oh thanks. I just found the paragraph in the docs that explains how to use the Go To Definition keybindings to open results from the Search Editor, that's what I was missing:
- https://code.visualstudio.com/docs/editor/codebasics#_search-editor

> <img width="775" alt="image" src="https://github.com/microsoft/vscode/assets/627486/16496107-93a2-457f-a83e-aa1b3c6cfcc2">

**Comment by jdanbrown** [comment]
Turned my question into a feature request:
- https://github.com/microsoft/vscode/issues/194044
