### ISSUE TITLE
Typescript language server intellisense does not activate or work in VsCode Notebooks

### ISSUE THREAD

**Issue by tonescones** [microsoft/vscode#193846]
I am currently looking for a way to set up notebooks to be able to activate and work with native vscode typescript language server so that essentially when a user opens a notebook with a Ts/Js kernel that initialization of Ts language server begins and the user is able to do basic intellisense autocompletion, jump to definition/implementation from their notebook just like they would if they opened a javascript or typescript file.

In our specific use case we essentially have our own DSL language which generates d.ts files which are interpretted by the native typescript language server which gives us the custom intellisense we are looking for.

Screenshot showing autocomplete for .js file -- UiTestType1 shows up since it is defined in UiTestType1.d.ts.
![](https://user-images.githubusercontent.com/60113255/195960243-99cb76b0-ec41-4117-aae5-86b6bbf36157.png)

I would expect the same autocomplete to appear for .ipynb files such as in screenshot below
![](https://user-images.githubusercontent.com/60113255/195960312-349f09c5-5a93-4125-8367-89ffac3849a7.png)

**Comment by IllusionMH** [comment]
Most likely .ipnb is not part of same TS project and it won't suggest something unknown.

**Comment by mjbvz** [comment]
That screenshot shows that the Typescript server is active in the cell (otherwise you'd see no suggestions). Instead it's likely what @IllusionMH suggests: notebook cells aren't part of your tsconfig project. This falls under #129482

**Comment by c3danielxu** [comment]
@mjbvz @IllusionMH How do you add notebook cells to tsconfig project? We tried this but it didn't work:
<img width="385" alt="Screenshot 2023-09-26 at 12 30 21 PM" src="https://github.com/microsoft/vscode/assets/111001237/036ef49f-75e7-4eb4-8cf1-7d1d6dbff93f">

**Comment by c3danielxu** [comment]
Not sure if this has an effect but we tried restarting TypeScript language server - although this doesn't actually show up when having `.ipynb` file as the current active tab.

<img width="1160" alt="Screenshot 2023-09-26 at 12 36 07 PM" src="https://github.com/microsoft/vscode/assets/111001237/bdb05bce-8738-40b6-ae78-818702f71bf4">

**Comment by tonescones** [comment]
@mjbvz  @IllusionMH anything we can do here?
