### ISSUE TITLE
Extend scenarios when dynamic configuration providers will be shown for Run and Debug

### ISSUE THREAD

**Issue by WardenGnaw** [microsoft/vscode#193828]
Automatic (dynamic) debug providers are only displayed when there is an active file. If a user tries to Run and Debug without an active file, the dynamic debug providers are not shown.

This feature request is looking to enhance the hueristic used to determine when to show the automatic debug configuration providers.

Hueristic proposals:
- Look at the open folder file types and enable dynamic providers for those file / languages.
- Combine an activation event and a dynamic configuration provider.

I'm also open to other heurestics other folks might have in mind.

**Comment by isidorn** [comment]
fyi @connor4312 for ideas

**Comment by timheuer** [comment]
Hot take: the same problems we think we're trying to solve already exist for non-dynamic debuggers.  NodeJS shows up for me when I'm in a .NET app today, so it's already not 'smart' in that sense, and I just feel that showing dynamic providers could map to the same model.

**Comment by WardenGnaw** [comment]
> the same problems we think we're trying to solve already exist for non-dynamic debuggers.

Two questions from this:
1. Are we using dynamic configuration providers correctly? We are using dynamic configurations just so we don't have to write these configurations to `launch.json`
2. If we are not, is there a way to make initial configuration providers use the machine storage instead of `launch.json`. 

E.g.
https://github.com/microsoft/vscode/blob/720fb55092665562fec8fa2ae27f5eeb5561510e/src/vs/workbench/contrib/debug/browser/debugConfigurationManager.ts#L432C10-L432C10

**Comment by isidorn** [comment]
@timheuer yes - that is a correct hot take! We have this heuristic to determine what debugger to use, and we use that heuristic whenever there is NO launch.json file. Thus we use it to decide what dynamic configuration provider to use, what debug extension to ask to try to launch without a launch.json etc...

No, there is not way to make initial configuration provider use the machine storage instead of launch.json.

What I tried to say in my initial comment, is that we have to improve the general heuristic for auto-picking a debugger. However since this is a problem that we have for all languages since day 1 of vscode I suggest that we wait for @roblourens to chime in. He is currently focused on Copilot Chat work so it might take a bit of time. Thanks for understanding.

**Comment by roblourens** [comment]
> Automatic (dynamic) debug providers are only displayed when there is an active file.

I don't think that's true, isn't this a dynamic debug config provider?

<img width="1271" alt="image" src="https://github.com/microsoft/vscode/assets/323878/48f5eb74-f417-42c0-be59-8c84172cf9f4">

Maybe you aren't activating your extension on `onDebugDynamicConfigurations:...`?

**Comment by WardenGnaw** [comment]
C# Dev Kit has it in its `package.json`

![image](https://github.com/microsoft/vscode/assets/3953714/9a595641-105a-451d-8cf8-1dd1a5e3593a)

**Comment by roblourens** [comment]
I don't think the automatic config providers are shown in that case though?

But here we will invoke your DA with no file open
<img width="1177" alt="image" src="https://github.com/microsoft/vscode/assets/323878/170ce74b-f1bb-45fb-a498-7692d02a8b16">

**Comment by WardenGnaw** [comment]
> I don't think the automatic config providers are shown in that case though?

Thats the issue, we want F5 to show the `C#` dynamic provider instead of the initial configuraiton providers of .NET5+ and .NET Core since those will be hidden if C# Dev Kit is installed.

We dont use initial configuration providers because we want the configurations to be saved in the machine memory.

**Comment by roblourens** [comment]
A couple somewhat related issues 

- https://github.com/microsoft/vscode/issues/150663
- https://github.com/microsoft/vscode/issues/146338#issuecomment-1128248014
