### ISSUE TITLE
Reveal in explorer context item is confusing on Windows

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#19381]
- VSCode Version: Code - Insiders 1.9.0-insider (fbea777a881523bc01a1358d115b16673dc5942e, 2017-01-25T07:19:27.879Z)
- OS Version: Linux x64 4.8.0-34-generic
- Extensions:

|Extension|Author|Version|
|---|---|---|
|EditorConfig|EditorConfig|0.3.4|
|Ionide-fsharp|Ionide|2.20.0|
|lorem-ipsum|Tyriar|1.0.0|
|sort-lines|Tyriar|1.2.0|
|theme-glacier|Tyriar|0.0.10|
|vscode-svgviewer|cssho|1.3.0|
|gitlens|eamodio|1.4.3|
|tslint|eg2|0.8.1|
|git-project-manager|felipecaputo|1.0.1|
|md-navigate|jrieken|0.0.1|
|vscode-scss|mrmlnc|0.6.0|
|seti-icons|qinjia|0.1.3|

---

Testing https://github.com/Microsoft/vscode/issues/16930

I didn't actually test this on Windows but I suspect it may be a problem, just close it off if it's not an issue/already been considered :smile:

If the tab context menu items display the following on Windows it would be confusing:

- Reveal in explorer
- Show in explorer

**Comment by bpasero** [comment]
![image](https://cloud.githubusercontent.com/assets/900690/22305409/bda6b4ee-e33b-11e6-9688-5e2da5f76fe9.png)
