### ISSUE TITLE
Code reopens after exit when update installs

### ISSUE THREAD

**Issue by StevenH237** [microsoft/vscode#193882]
Type: <b>Bug</b>

If I try to close VSCode via File → Exit because I'm done using it, if an update is available it may (but doesn't seem to always) immediately relaunch.

It almost feels intentional, so I've asked for the ability to update without reopening as a [feature request](https://github.com/microsoft/vscode/issues/173450) before, and that issue was misinterpreted as a request to exit without updating. I AM NOT ASKING FOR THAT. I want to be able to exit VSCode and have it not pop back up ten seconds later because it updated.

VS Code version: Code - Insiders 1.83.0-insider (5a400e53e985dc5e24f6ee574b07ab23943841c5, 2023-09-07T17:35:42.740Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i5-11600KF @ 3.90GHz (12 x 3912)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.89GB (1.84GB free)|
|Process Argv|--crash-reporter-id eaa957b1-6421-4350-86e9-44de8f4ee528|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (49)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-sqlite|ale|0.14.1
nugetpackagemanagergui|ali|2.0.6
language-mcfunction|arc|0.18.0
asl-extension|B0s|1.1.0
gitignore|cod|0.9.0
vscode-autohotkey-plus|cwe|2.7.1
gitlens|eam|2023.9.2105
scs-script|Fra|0.0.2
craftos-pc|Jac|1.2.2
vscode-computercraft|Jac|1.1.1
vscode-nuget-package-manager|jmr|1.1.6
rainbow-csv|mec|3.7.1
vscode-json5|mrm|1.0.0
csharp|ms-|2.3.27
vscode-dotnet-runtime|ms-|1.7.4
isort|ms-|2023.10.1
python|ms-|2023.16.0
vscode-pylance|ms-|2023.9.20
jupyter|ms-|2023.8.1002501831
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.17
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-slideshow|ms-|0.1.5
remote-ssh|ms-|0.106.4
remote-ssh-edit|ms-|0.86.0
hexeditor|ms-|1.9.12
remote-explorer|ms-|0.4.1
vsliveshare|ms-|1.0.5883
fix-json|oli|0.1.2
geo-data-viewer|Ran|2.6.0
java|red|1.22.1
se-csproj-extensions|sel|0.0.7
markdown-preview-enhanced|shd|0.7.9
shopify-liquid|sis|3.2.2
vscode-zipexplorer|sle|0.3.1
datapack-language-server|SPG|3.4.16
lua|sum|3.7.0
even-better-toml|tam|0.19.2
open-in-browser|tec|2.0.0
vscode-autohotkey2-lsp|thq|2.1.6
intellicode-api-usage-examples|Vis|0.2.8
vscodeintellicode|Vis|1.2.30
vscode-java-debug|vsc|0.54.0
vscode-java-dependency|vsc|0.23.1
vscode-java-pack|vsc|0.25.14
vscode-java-test|vsc|0.39.1
vscode-maven|vsc|0.42.0
markdown-all-in-one|yzh|3.5.1
vscode-autohotkey-debug|zer|1.11.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythontb:30258533
pythonptprofiler:30281269
vshan820:30294714
vscod805cf:30301675
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30404738
py29gd2263:30784851
vsclangdf:30492506
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30618038
showlangstatbar:30737417
57b77579:30687741
pythonfmttext:30716741
fixshowwlkth:30771523
showindicator:30805243
pythongtdpath:30726887
i26e3531:30792625
welcomedialog:30812478
pythonnosmt12:30779711
pythonidxpt:30768918
pythonnoceb:30776497
copilotsettingc:30808720
asynctok:30821568
dsvsc013:30777762
dsvsc014:30777825
diffeditorv2:30786206
pythonlinttypecf:30823782
pythonmpsinfo:30842935
dsvsc015:30821418
pythontestfixt:30826906
pythonfb280951:30830809
pythonregdiag:30842812

```

</details>

**Comment by joaomoreno** [comment]
https://github.com/microsoft/vscode/issues/129168
