### ISSUE TITLE
Folder is not showing up when typing src attribute

### ISSUE THREAD

**Issue by ilovecoding69420** [microsoft/vscode#193880]
Does this issue occur when all extensions are disabled?: Yes

Version: 1.82.2 (user setup)
Commit: abd2f3db4bdb28f9e95536dfa84d8479f1eb312d
Date: 2023-09-14T05:55:25.390Z
Electron: 25.8.1
ElectronBuildId: 23779380
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.22621

Steps to Reproduce:

1, Install vue.js using `npm create vue@latest`
2. Create `.vue` file in copmonents
3. Create `img` element in template
4. Try using autocomplete in src attribute

![image](https://github.com/microsoft/vscode/assets/97043299/6eadf170-ec46-475d-8279-c5100f75b6b5)
![image](https://github.com/microsoft/vscode/assets/97043299/b3399550-e3c6-4f39-9a3f-05f9ce992932)

**Comment by mjbvz** [comment]
Please file this against your vue extension
