### ISSUE TITLE
experimentalDecorators not recognized in vscode

### ISSUE THREAD

**Issue by marvinhagemeister** [Microsoft/vscode#19392]
- VSCode Version: 1.9.0-insider fbea777a881523bc01a1358d115b16673dc5942e
- OS Version: MacOS Sierra

Steps to Reproduce:

1. Create Typescript file with decorators (like [mobx](https://github.com/mobxjs/mobx/))
2. Enable `experimentalDecorators` in `tsconfig.json`

```json
{
  "compilerOptions": {
    "experimentalDecorators": true
  }
}
```

Result (reloading vscode doesn't help):

<img width="344" alt="screen shot 2017-01-25 at 21 02 15" src="https://cloud.githubusercontent.com/assets/1062408/22307030/c746265a-e341-11e6-9531-6c89d669dd42.png">

Warning still says:
```
[ts] Experimental support for decorators is a feature that is subject to change in a future release. Set the 'experimentalDecorators' option to remove this warning.
```

**Comment by mjbvz** [comment]
I just tested this and see decerators working as expected. A few questions to help investigate:

* What version of TypeScript are you using? The builtin version or another one?
* What the the rest of the project structure look like?
* Does this repo in a simple project with just a `tsconfig.json` and a single `ts` file as well?

Thanks

**Comment by marvinhagemeister** [comment]
@mjbvz Thanks for having a look. I narrowed the issue down to a minimal `tsconfig.json` which shows the described problem.

```json
{
  "compilerOptions": {
    "noImplicitAny": true,
    "experimentalDecorators": true
  }
}
```

single ts file:

```ts
import { observable } from "mobx";

class Model {
  @observable foo;
}
```

When I remove the `noImplicitAny` property, the error message disappears.

**Comment by marvinhagemeister** [comment]
@mjbvz Thanks for having a look at this issue. It is reproduceable for me with a minimal project setup with TypeScript 2.1.5.

There is a single ts file in the project
```ts
import { observable } from "mobx";

class Model {
  @observable foo: string;
}
```

The warning doesn't seem to be tied to a specific option in `tsconfig.json`, although it does occur rather sporadically. Here is a small gif showing the issue:
 
![out](https://cloud.githubusercontent.com/assets/1062408/22323859/d6289180-e3a5-11e6-8260-8ce4d63146f4.gif)

**Comment by awerlang** [comment]
Take the output (ctrl+shift+u) for TypeScript and attach to this issue.

**Comment by mjbvz** [comment]
I can repo this as well. It does not seem related to `mobx` since I see it using a custom decorator function as well.

To help investigate, please:

* Add `"typescript.tsserver.trace": "verbose",` to your settings.
* Reload VSCode and repo the issue
* Go to the `TypeScript` section of the output view
* Paste up output from there.

Please also enable logging for the tsserver itself by setting the [`TSS_LOG`](https://github.com/Microsoft/TypeScript/wiki/Standalone-Server-(tsserver)#logging) env var, and starting vscode from the same environment. This will generate a log file that can help us investigate the issue

Thanks

**Comment by mjbvz** [comment]
I believe this is another manifestation of https://github.com/Microsoft/TypeScript/issues/12618. Closing this issue since we're tracking the root problem the TypeScript side
