### ISSUE TITLE
Inconsistent context menu order: "Reveal in Explorer View" and "Reveal in File Explorer"

### ISSUE THREAD

**Issue by AioiLight** [microsoft/vscode#193980]
In the Source Control panel, "Reveal in Explorer View" of context menu is above "Reveal in File Explorer".
<img src="https://github.com/microsoft/vscode/assets/13918537/c021327f-32d1-4044-b24a-a67291e3c687" width="300">

But context menu of the tabs, "Reveal in Explorer View" is below "Reveal in File Explorer".
<img src="https://github.com/microsoft/vscode/assets/13918537/1168622b-ef42-442d-8050-eac9f7c10b67" width="300">

It's not consistent. It will occur mis-clicking.

**Comment by AioiLight** [comment]
@justschen Could you triage the issue?

**Comment by sbatten** [comment]
@lszomoru would you be up to swap the order you contribute from the git extension?
