### ISSUE TITLE
Test Pinned Tabs on Separate Row

### ISSUE THREAD

**Issue by benibenj** [microsoft/vscode#193991]
Refs: #98160

- [x] anyOS @jrieken
- [x] anyOS @devinvalenciano

Complexity: 2

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23193991%0A%0A&assignees=benibenj)

---

With the setting `workbench.editor.pinnedTabsOnSeparateRow` pinned tabs are displayed on a separate row.

![pinnedTabBar](https://github.com/microsoft/vscode/assets/44439583/72ba266f-9613-4853-8270-629f16d3f95d)

While testing the following contract should always hold:
- If all tabs are unpinned, there should be only a single tab bar and the action menu should be visible to the right
- If all tabs are pinned,     there should be only a single tab bar and the action menu should be visible to the right
- If there are both pinned and unpinned tabs, two tab bars should be visible, the tab bar at the top should contain all tabs which are pinned. This tab bar should not have the action menu to it's right. The second tab bar bellow the first one should contain all tabs which are not pinned. This tab bar should have the action menu to it's right.

1. Set `workbench.editor.pinnedTabsOnSeparateRow: true` (`workbench.editor.showTabs` must be set to true)
2. Play around with pinning and unpinning tabs by using the context menu on the tabs (right click tab). Pinning a tab with the context menu should always move it to the last pinned tab. Unpinning a tab should always move it to the first unpinned tab.
3. Now try drag and dropping the tabs between the tab bars. The contract mentioned above should always hold. Make sure to test the edge cases:
    - First Unpinned tab onto last pinned tab 
    - First Unpinned tab onto container of pinned tab bar (to the right of the last pinned tab)
    - Last Pinned tab onto first unpinned tab
    - First Pinned tab onto last pinned tab
    - First Pinned tab onto container of pinned tab bar (to the right of the last pinned tab)
4. Toggle `breadcrumbs.enabled`, Is everything still rendered fine?
5. Lastly, try different tab settings. Make sure they always apply and work on both tab bars (`workbench.editor.pinnedTabSizing`(applies to only pinned tabs), `workbench.editor.tabSizing`, `workbench.editor.wrapTabs`, `workbench.editor.tabHeight`)

**Comment by jrieken** [comment]
This works great!
