### ISSUE TITLE
[bug/reopening of #165352] vscode markdown preview not showing images

### ISSUE THREAD

**Issue by o314** [microsoft/vscode#193901]
Suppose we have a dir with a readme.md and some imgs
readme.md content is
```
# Hello Imaged World

![](foo.jpg)

![](subdir/bar.jpg)

![](../baz.jpg)
```

more precisely the files layout is
```
./readme.md
./foo.jpg
./subdir/bar.jpg
../baz.jpg
```

markdown preview is able to render foo and bar but not baz
while editor opens the whole three correctly if we ctrl click each link in markdown

#165352 has introduced  a `getMdPath` that seems somewhat misleading there

PS Change Preview Security Settings seems to not apply any distinctions

**Comment by shashankrp** [comment]
Hi o314, i tried to recreate the same scenario that you have specified but i am able to render all three images in the preview and i am even attaching the screenshot of it. Along with the Explorer window in the left. So i didn't face any issue here,
![image](https://github.com/microsoft/vscode/assets/30649674/1661d9b8-eb6c-41ba-a1a2-549fa3d98f33)

**Comment by o314** [comment]
Hi @shashankrp  Thanks for the quick feedback !
I will have a look at your proposal as fast as i can (tonight ?)
BTW this was reported from a Windows 10 os

**Comment by shashankrp** [comment]
I tried to recreate the issue and i didn't face any issue related to that so here i am attaching the screenshot below. ok thanks but i tried it on windows 11 OS
![image](https://github.com/microsoft/vscode/assets/30649674/fd30429f-738f-4e3a-aa6d-615a25f815e8)

**Comment by o314** [comment]
![Capture](https://github.com/microsoft/vscode/assets/4026002/10018965-87d6-4b59-861b-c03be45b4010)
That still puzzles me here !

A note about the env : vscode running on windows 10
may be useful too: the workspace file is on a different drive than those files

**Comment by shashankrp** [comment]
Hi o314, can you please recheck if the image is in the actual path specified because i think vs code would work similar in all the different operating systems.

**Comment by mjbvz** [comment]
@o314 What folder did you open? VS Code will only load images from the current workspace. You can't use `..` to traverse out of it

**Comment by o314** [comment]
Hi @shashankrp,
> if your using ../ then you could traverse only one folder back

Well, it does not seem to fail anymore in my case. I use `![](../../whatever)` that works well.

@mjbvz it seems to be related with an over narrowed workspace effectively.
I have not seen this point on the doc page @ https://code.visualstudio.com/docs/languages/markdown ; it is very interaction oriented (as too often) and skips this important point IMO. 

I will close this issue since everything works as expected on my machine.
*May be a mention in doc could be useful*

Thanks for your feedback anyway gentlemen.
