### ISSUE TITLE
MSYS2 UCRT64 terminal profile can't integrate under TERMINAL tab

### ISSUE THREAD

**Issue by HuandongNB** [microsoft/vscode#193947]
Does this issue occur when all extensions are disabled?: Yes/No
Yes

- VS Code Version:  1.82.2
- OS Version: Microsoft Windows 10 家庭中文版

Steps to Reproduce:

1. Installed MSYS2.
2. Adding following in settings.json:
```javascript
        "terminal.integrated.profiles.windows": {
        "UCRT64": {
          "path": "D:\\Program Files\\msys64\\ucrt64.exe"
        }
  	},
    "terminal.integrated.defaultProfile.windows":  "UCRT64",
``` 
3.  Click 'UCRT64' in terminal profiles dropdown:

![image](https://github.com/microsoft/vscode/assets/50125911/f01acc3f-0224-4d11-96f8-2014ddc026d0)

4.  The UCRT64 terminal run but not under the TERMINAL tab
    
![image](https://github.com/microsoft/vscode/assets/50125911/ffe340d3-4148-4e58-99a3-e6bef377e5e3)

**Comment by Tyriar** [comment]
You're pointing vscode to run the _terminal_ which pops out the window, not the _shell_. This is working as expected, you need to find the shell executable to point it to, probably bash.exe somewhere in ucrt64's install path.

**Comment by HuandongNB** [comment]
Thanks, Tyriar.
Following added into settings.json works:
`    "terminal.integrated.profiles.windows": {
      "MSYS2_UCRT64": {
        "path": "D:\\Program Files\\msys64\\usr\\bin\\bash.exe",
        "args": [
          "--login",
          "-i"
        ],
        "env": {
          "MSYSTEM": "UCRT64",
          "CHERE_INVOKING": "1",
        }
      }
  	},`
ref: [https://stackoverflow.com/questions/45836650/how-do-i-integrate-msys2-shell-into-visual-studio-code-on-window/48016561#48016561](url)
