### ISSUE TITLE
the gutter for breakpoints

### ISSUE THREAD

**Issue by Talgat012** [microsoft/vscode#193900]
Type: <b>Bug</b>

Hello, 
i'm going through a Go course and during it i couldn't mark breakpoints like my instructor did. I just don't have the gutter like everybody has.
Instead, I can only right-click on the line numbers and get the dropdown menu to add and remove breakpoints. But it is very inconvenient comparing to the gutter function.
I tried to search but couldn't find any information. Looks like i'm the only one having this problem.
Please advise how to bring the gutter to work visually with breakpoints. Thanks.

VS Code version: Code 1.82.2 (abd2f3db4bdb28f9e95536dfa84d8479f1eb312d, 2023-09-14T05:55:25.390Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-2600 CPU @ 3.40GHz (8 x 3392)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|7.98GB (1.32GB free)|
|Process Argv|--crash-reporter-id 85a4c322-e199-4f58-9ce7-06592140c882|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (22)</summary>

Extension|Author (truncated)|Version
---|---|---
arepl|alm|2.0.5
All-Autocomplete|Ati|0.0.26
auto-complete-tag|for|0.1.0
code-runner|for|0.12.0
go|gol|0.39.1
easy-less|mrc|2.0.0
vscode-language-pack-ru|MS-|1.82.2023091309
autopep8|ms-|2023.6.0
isort|ms-|2023.10.1
python|ms-|2023.16.0
vscode-pylance|ms-|2023.9.20
jupyter|ms-|2023.8.1002501831
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-slideshow|ms-|0.1.5
remote-wsl|ms-|0.81.4
autodocstring|njp|0.6.1
material-icon-theme|PKi|4.30.1
LiveServer|rit|5.7.9
vscode-multiclip|sle|0.1.5
intellicode-api-usage-examples|Vis|0.2.8
vscodeintellicode|Vis|1.2.30
vscode-import-cost|wix|3.3.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vstes627:30244334
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263:30335439
vscoreces:30445986
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
vscaat:30438848
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
2e4cg342:30602488
89544117:30613380
showlangstatbar:30737416
0bi6i642:30841073
03d35959:30757346
pythonfmttext:30731395
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
pythonnosmt12:30797651
pythonidxpt:30805730
pythonnoceb:30805159
copilotsettingc:30839828
asynctok:30821568
dsvsc013:30795093
dsvsc014:30804076
diffeditorv2:30821572
dsvsc015cf:30829746

```

</details>

**Comment by gjsjohnmurray** [comment]
Please use the Settings Editor to check `editor.glyphMargin`

**Comment by Talgat012** [comment]
This was so easy, thanks!

**Comment by gjsjohnmurray** [comment]
Glad I could help. Please close your issue.
