### ISSUE TITLE
real device debugging using cable not showing in VSCode

### ISSUE THREAD

**Issue by pujakhalika** [microsoft/vscode#193928]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.82.2
- OS Version: windows 10

Steps to Reproduce:

1. i want to debug my flutter app with my real device but my device not showing. I tried install screen mirroring with vysor is work and already detected but with vscode cannot. 
![bug](https://github.com/microsoft/vscode/assets/73125355/42efc308-5233-485c-a4a9-456e3c38cb27)

2. 
![bug2](https://github.com/microsoft/vscode/assets/73125355/922d5e56-3555-4886-8ed9-ec1886dbf913)

**Comment by roblourens** [comment]
Please file an issue on the flutter extension repo
