### ISSUE TITLE
Allow running `code tunnel` as root in docker

### ISSUE THREAD

**Issue by 0rphon** [microsoft/vscode#193932]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 
```
1.83.0-insider
c72447e8d8aaa7497c9a4bd68bc4301584b92beb
x64
```
- OS Version (in docker): 
```
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.3 LTS
Release:        22.04
Codename:       jammy
```

## Steps to Reproduce:
building and running the following dockerfile
```dockerfile
FROM ubuntu:latest
RUN apt update && apt install -y curl gpg
RUN curl -L -o code.deb https://az764295.vo.msecnd.net/insider/c72447e8d8aaa7497c9a4bd68bc4301584b92beb/code-insiders_1.83.0-1695376229_amd64.deb \
    && apt install -y ./code.deb

CMD code-insiders tunnel
```

gives the following: 
```
You are trying to start Visual Studio Code - Insiders as a super user which isn't recommended. If this was intended, please add the argument `--no-sandbox` and specify an alternate user data directory using the `--user-data-dir` argument.
```

changing the command in the docker file to `CMD code-insiders tunnel --no-sandbox --user-data-dir bla` gives the following:

```
error: unexpected argument '--no-sandbox' found

Usage: code-tunnel-insiders tunnel [OPTIONS] [COMMAND]

For more information, try '--help'.
```

creating a non-sudo user in the docker container and running it from that works, but that leads to a headache of problems with other parts of my docker image. ideally, the fix suggested by code in the first example would solve this but it doesnt.

**Comment by 0rphon** [comment]
related to #168692

**Comment by connor4312** [comment]
`--no-sandbox` doesn't apply to `code tunnel`. That's an option for electron, and `code tunnel` doesn't run electron. Just omit that argument and run the command.

**Comment by 0rphon** [comment]
@connor4312 omitting `--no-sandbox` just makes it complain about `--user-data-dir` being unexpected. and if i omit `--user-data-dir` then it it goes back to complaining about being run as root.

**Comment by connor4312** [comment]
What code `code-insiders --version` print?

**Comment by 0rphon** [comment]
i put the output of `code-insiders --version` at the top of my issue, but here it is again:
```
1.83.0-insider
c72447e8d8aaa7497c9a4bd68bc4301584b92beb
x64
```

**Comment by 0rphon** [comment]
would it be possible to reopen this? it seems like there is no solution based on whats been said so far

**Comment by connor4312** [comment]
Looks like a workaround would be setting `CAN_RUN_AS_ROOT=1` when you call `code-insiders`. But the better solution is just to use the CLI (https://code.visualstudio.com/docs/?dv=linux64cli&build=insiders) instead of the full desktop install. This will be fixed when the desktop install uses the native CLI as its primary entrypoint.

**Comment by zandercodes** [comment]
> @connor4312 omitting `--no-sandbox` just makes it complain about `--user-data-dir` being unexpected. no combination of arguments fixes this as far as i can tell
> 
> * `code-insiders tunnel` causes `You are trying to start Visual Studio Code - Insiders as a super user`
> * `code-insiders tunnel --no-sandbox --user-data-dir bla` causes `error: unexpected argument '--no-sandbox' found`
> * `code-insiders tunnel --user-data-dir bla`causes `error: unexpected argument '--user-data-dir' found`
> * `code-insiders tunnel --no-sandbox`causes `error: unexpected argument '--no-sandbox' found`

Works with `code --user-data-dir=/home/code/ tunnel`. The `=` is important, otherwise it will be misinterpreted.

**Comment by aeschli** [comment]
I still get the same error:

```
You are trying to start Visual Studio Code - Insiders as a super user which isn't recommended. If this was intended, please add the argument `--no-sandbox` and specify an alternate user data directory using the `--user-data-dir` argument.
```

adding CAN_RUN_AS_ROOT=1 did not make a difference.

**Comment by connor4312** [comment]
I cannot repro, @aeschli can you share the exact command you ran?

```
➜  ~ code-insiders --version
1.86.0-insider
3dea5cbbcb88d7f6dad71148f3d3f98b853ab836
x64
➜  ~ sudo code-insiders serve-web
*
* Visual Studio Code Server
*
* By using the software, you agree to
* the Visual Studio Code Server License Terms (https://aka.ms/vscode-se...
```

**Comment by aeschli** [comment]
All is good, sorry, I tested against an old version!

**Comment by aiday-mar** [comment]
This issue will be closed because it appears to be verified
