### ISSUE TITLE
Please have an option for "No Terminal" in the which terminal to launch

### ISSUE THREAD

**Issue by Panzerbjrn** [microsoft/vscode#193906]
Hi, I'd really like to be able to chose "No Terminal" in the dropdown where you ask which kind of terminal to open automatically.
![2023-09-24 11_28_23-Settings - GitHub - Visual Studio Code  Administrator](https://github.com/microsoft/vscode/assets/10132417/d0f0677a-d394-49f3-8072-d97575d7b185)

It is really annoying that there doesn't seem to be a way to prevent this annoying behaviour. And a quick search shows that I'm not alone in wanting a way of turning this off. To be honest, it should be off by default.

**Comment by meganrogge** [comment]
If I'm understanding your request correctly, you can do that already.

https://code.visualstudio.com/updates/v1_82#_control-how-terminals-restore-on-startup

**Comment by meganrogge** [comment]
I'd need a gif to understand what you're describing

**Comment by Panzerbjrn** [comment]
> I'd need a gif to understand what you're describing

Maybe wait until you have a better command of English before engaging in English language topics then? ¯\_(ツ)_/¯ 
But yes, I can see how "I'd really like to be able to chose "No Terminal" is difficult to understand for a certain type of person...

**Comment by Tyriar** [comment]
@Panzerbjrn maybe read the [code of conduct](https://opensource.microsoft.com/codeofconduct/) before creating an issue.
