### ISSUE TITLE
Files need to ignore hash/query portion of URIs and only check for fsPath

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#19398]
- VSCode Version: 1.9

Repo:

Using an extension, try opening the same file multiple times but using different hash fragments: `file.js#L10`, `file.js#L20`, `file.js#L30`

I believe i used the `vscode.open` command

**Bug**
We open a new document in each case instead of switching to an already open copy.

I also notice multiple entries for the same file in the quick open view:

![screen shot 2017-01-25 at 2 07 28 pm](https://cloud.githubusercontent.com/assets/12821956/22311397/2d101a8e-e308-11e6-937b-7fadc5a758b8.png)

**Comment by bpasero** [comment]
This is a related issue to https://github.com/Microsoft/vscode/issues/12448

**Comment by bpasero** [comment]
Into https://github.com/Microsoft/vscode/issues/12448
