### ISSUE TITLE
File > Open Recent > recent workspace no longet opens in new window when Ctrl or Shift used in VS Code Insiders

### ISSUE THREAD

**Issue by IllusionMH** [microsoft/vscode#193997]
Type: <b>Bug</b>

Opening in new window straing from File > Open Recent menu is great tool to quickly get to another workspace wiithout loosing curren open one, and much faster then New Window and searching same workspace in new window.
So I hope this change is not intentional.

Steps to reproduce:
1. Have history of several opened workspaces
1. Open File > Open Recent submenu.
1. Press <kbd>Ctrl</kbd> or <kbd>Shift</kbd> and click on some of recent workspaces
1. Workspace in active window is replaces with selection from recent

Expecte behavior:
New window should be opened with new workspace instead of replacing workspace in active window.

This is behavior is reproducible in standalone(zip) Insiders intallation but not not reprodusible in standalone(zip) Stable intallation. However in stable <kbd>Ctrl</kbd>(<kbd>Shift</kbd>) sometimes does nothing, but never replaces current workspace.

VS Code version: Code - Insiders 1.83.0-insider (109e1f8d8afb754ed31317f79937a44e98d5063b, 2023-09-25T10:41:26.295Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz (8 x 2996)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.50GB (15.50GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by bpasero** [comment]
If this is a confirmed regression, it would help to know which change caused it. We maintain a node.js based CLI tool  [`vscode-bisect`](https://github.com/microsoft/vscode-bisect) that automatically downloads and runs previous VS Code insiders and asks for each build if the issue reproduces. It takes up to 8 steps to find exactly the build that caused the regression.

**Steps:**
* install [node.js](https://nodejs.org/en/download) (if not yet done)
* `npx --yes @vscode/vscode-bisect@latest`
* follow the instructions until you found the offending build (its fine to leave the commit empty)
* report back the commit range in this issue

Thanks!

**Comment by IllusionMH** [comment]
That's a relief😌 Thanks

Will bisect after working hours

**Comment by IllusionMH** [comment]
@bpasero
Bisect showed this range https://github.com/microsoft/vscode/compare/f36df69328ed10f76d4be03e8a82b61794b49711...491ddd816e03051785226aa389f32a6cf4ccfdf2

May be related to https://github.com/microsoft/vscode/commit/d649d877f48664eee857dcb93dd4c331bd8908a1

---

However it feels that some builds also had problem where only odd (1,3...) attempts opened new window. Will bisect this as well

**Comment by IllusionMH** [comment]
Works as expected in today's Insiders build.
Thanks, @bpasero!
