### ISSUE TITLE
rpm doesn't run update-desktop-database

### ISSUE THREAD

**Issue by hsenag** [microsoft/vscode#193951]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.82.2
- OS Version: CentOS Linux 7.9.2009

Steps to Reproduce:

1. Install the rpm on CentOS 7 following the [official instructions](https://code.visualstudio.com/docs/setup/linux#_rhel-fedora-and-centos-based-distributions)
2. Run `xdg-open vscode://.`, or do something that requires a `vscode://` URL to work such as logging into GitHub
3. You'll get an error like "The specified location is not supported" (`xdg-open`) or "We can't connect" (from the browser - it'll be reported on a `github.com` URL that is supposed to be redirecting to `vscode://`)

It all works fine on Ubuntu. 

I was able to fix it by running `sudo update-desktop-database`.

I unpacked the deb and rpm files and looked in the post-install scripts and indeed the .deb runs `update-desktop-database` and the .rpm doesn't.

**Comment by rzhao271** [comment]
Hi @hsenag, thanks for noticing the missing command!

The team is currently preparing for a new Stable version, and so I'll add the missing command to the package next month, after the new Stable has been released.

Also, I'm wondering whether to also add the update-desktop-database command to the postrm scripts?

**Comment by hsenag** [comment]
> Also, I'm wondering whether to also add the update-desktop-database command to the postrm scripts?

Yeah, that makes sense. Although I just had a quick look and I think `.deb` doesn't do that either, which might be a bug there too.

**Comment by hsenag** [comment]
And now I realise you probably also meant that when you said "scripts" :-)

**Comment by deepak1556** [comment]
Hi @hsenag , thanks for the analysis on the bug. I tried the rpm installation steps on Fedora 38 and when I check for url handler for `vscode` I do see one installed without any need to invoke `update-desktop-database`. Is this only an issue for CentOS ?

```
[parallels@fedora ~]$ xdg-settings get default-url-scheme-handler vscode
code-url-handler.desktop
```

**Comment by hsenag** [comment]
@deepak1556 that's interesting, I didn't try Fedora. I'll give it a go in a VM now.

Both myself and the user I was helping reproduced it on CentOS. Also it seems it is a standard thing to do as the `.deb` packages run it.

**Comment by hsenag** [comment]
Yeah, confirmed it also works in Fedora for me, maybe that has some mechanism to do it automatically? Not sure what though! `/usr/share/applications/mimeinfo.cache` also gets updated when I do `rpm -e`.

On the other hand `update-desktop-database` seems harmless including on Fedora so maybe it doesn't hurt to have it anyway for the wider compatibility?

**Comment by deepak1556** [comment]
I was not able to find when they inject `update-desktop-database` scriptlet as part of dnf in https://github.com/rpm-software-management, however I was able to validate that it does get invoked with `dnf install code --verbose --rpmverbosity=debug`, so seems like something available with newer versions of dnf. I am good with the idea of explicitly invoking `update-desktop-database` scriptlet as part of the installation scripts.

```
D: running post-transaction scripts
D: %transfiletriggerin(shared-mime-info-2.2-3.fc38.aarch64): scriptlet start
D: %transfiletriggerin(shared-mime-info-2.2-3.fc38.aarch64): execv(/bin/sh) pid 8086
D: Plugin: calling hook scriptlet_fork_post in selinux plugin
D: setexecfilecon: (/bin/sh, rpm_script_t) 
+ update-mime-database -n /usr/share/mime
D: %transfiletriggerin(shared-mime-info-2.2-3.fc38.aarch64): waitpid(8086) rc 8086 status 0

D: %transfiletriggerin(desktop-file-utils-0.26-8.fc38.aarch64): scriptlet start
D: %transfiletriggerin(desktop-file-utils-0.26-8.fc38.aarch64): execv(/bin/sh) pid 8088
D: Plugin: calling hook scriptlet_fork_post in selinux plugin
D: setexecfilecon: (/bin/sh, rpm_script_t) 
+ update-desktop-database
D: %transfiletriggerin(desktop-file-utils-0.26-8.fc38.aarch64): waitpid(8088) rc 8088 status 0

  Verifying        : code-1.82.3-1696243983.el7.aarch64                                                                                   1/1 
Completion plugin: Generating completion cache...
Installed: code-1.82.3-1696243983.el7.aarch64

```

**Comment by hsenag** [comment]
Ah, the log entries gave me the clue how to find it - they've got [triggers in the desktop-file-utils package](https://src.fedoraproject.org/rpms/desktop-file-utils/blob/rawhide/f/desktop-file-utils.spec#_42).
