### ISSUE TITLE
Javascript Intellisense not working in VS Code

### ISSUE THREAD

**Issue by Bhavik47** [microsoft/vscode#193915]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.82.2
- OS Version: Windows_NT x64 10.0.22621

Commit: abd2f3db4bdb28f9e95536dfa84d8479f1eb312d
Date: 2023-09-14T05:55:25.390Z
Electron: 25.8.1
ElectronBuildId: 23779380
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0

Features like code suggestion and error highlighting is not working for Javascript in my Visual Studio Code. No javascript emmet is being shown in the suggestions. It seems like Javascript intellisense is not working.
The code is running completely fine but features like code suggestion or completion , error highlighting , etc is not working.
Please help ->

**Comment by codespearhead** [comment]
@Bhavik47 Those features don't come built-in. You have to install the [appropriate extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.vscode-typescript-next).

**Comment by Bhavik47** [comment]
https://github.com/microsoft/vscode/assets/116140035/848ab754-fdb8-405d-bd73-1a07c0c55b2b

VS Code is showing no suggestions or errors even with all the javascript extensions. Here's the problem as you can see its not recommending document or any functions in document like getElementById() or getElementsByClassName()  even after writing document. Nor is it recommending objects like console.

**Comment by mjbvz** [comment]
> Those features don't come built-in. You have to install the [appropriate extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.vscode-typescript-next).

@codespearhead  This is wrong. These features are built in 

--- 

@Bhavik47 Did you disable the builtin Javascript support. In the extensions view, search for `@builtin javascript` and confirm that the `TypeScript and JavaScript Language Features` extension is enabled

**Comment by Bhavik47** [comment]
Thankyou, It worked now
TypeScript and JavaScript Language Features were disabled
