### ISSUE TITLE
Cmd+Q / Quit on macOS with high delay

### ISSUE THREAD

**Issue by yeahitsjan** [microsoft/vscode#193930]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.82.2 (Universal) (commit abd2f3db4bdb28f9e95536dfa84d8479f1eb312d)
- OS Version: macOS Ventura (tested on 13.5 & 13.6)

Steps to Reproduce:

1. Open up Code in whatever view.
2. Press Cmd+Q or click on Quit Visual Studio Code.
3. Delay happens, the dot in dock still exists. After around 3-5s app quits.

This also happens when updating the application. The application delays the restart, if you then accidentially click the app icon again the update needs to be redone.

What also happens is, if you Cmd+Q the application and while the white dot is still visible (or app active in task overview), and you start the app again, Code shows its window, and then quits when the application *should have quitted with delay*.

This problem occurs since / started with **version 1.82.0**.

If you need anymore information please let me know.

**Comment by deepak1556** [comment]
Merging to https://github.com/microsoft/vscode/issues/192742

This is addressed in insiders and will be available with `1.83` release.

**Comment by yeahitsjan** [comment]
Hi @deepak1556, hope you not mind asking but is there any ETA when 1.83 arrives?

**Comment by deepak1556** [comment]
Expected release date is `10/5`, refs https://github.com/microsoft/vscode/issues/193938
