### ISSUE TITLE
When will CLS finally work as expected in the terminal???

### ISSUE THREAD

**Issue by zzador** [microsoft/vscode#193965]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: Latest
- OS Version: Windows 10

Steps to Reproduce:

1. Open "Command prompt"-terminal (cause nobody wants powershell) and type "dir + [enter]" 3 times
2. Then type "cls + [enter]" to delete the terminal -> terminal seems cleared
3. Type "dir + [enter]" again -> all deleted text is back again.

This buggy terminal behaviour is now persistent since 2017 or so. PLEASE FIX IT!!!! Clearing the command prompt is essential to me.

**Comment by meganrogge** [comment]
This works for me, so maybe is because of your windows version.

![Recording 2023-09-25 at 09 05 21](https://github.com/microsoft/vscode/assets/29464607/24271ed6-72cb-4f15-8c7d-fda70ad54c9a)
