### ISSUE TITLE
layout preferences reset on startup

### ISSUE THREAD

**Issue by usotsukki** [microsoft/vscode#193984]
Impossible to permanently close this "panel" thing

<img width="792" alt="Screenshot 2023-09-25 at 16 33 20" src="https://github.com/microsoft/vscode/assets/94716961/f801918f-4827-48f6-b6ed-5cec6a32c00c">

**Comment by sbatten** [comment]
@usotsukki are you saying the X button in the top right does not close it?

**Comment by sbatten** [comment]
That is not expected behavior. Have you tried with all extensions disabled?

**Comment by sbatten** [comment]
Can you try on the latest insiders? https://code.visualstudio.com/insiders/

**Comment by sbatten** [comment]
Closing as this was apparently fixed in insiders
