### ISSUE TITLE
Show git tag in bottom left corner instead of commit hash when checking out a tag

### ISSUE THREAD

**Issue by felixfbecker** [Microsoft/vscode#1939]
When you checkout a tag, `git status` will show that you are on the tag name. VS Code shows the commit hash of the commit instead.

**Comment by joaomoreno** [comment]
:+1:

**Comment by ChrisLynchHPE** [comment]
I'd also like to see VSCode add the ability to create a tag from the Command Palate. Sure, I can drop to Git cli or Git Bash, but if you provide a lot of other Git commands from the Command Palate, it would be helpful to see Create Tag to a Commit be added.

**Comment by joaomoreno** [comment]
@ChrisLynchHPE Please file a separate issue for that.
