### ISSUE TITLE
(JavaScript) Auto-complete for block comments doesn't work since 0.10.1

### ISSUE THREAD

**Issue by kristofferostlund** [Microsoft/vscode#194]
In previous versions of VS Code block comments have been finished after typing `/**`, which now seems not to be the case.

![comments](https://cloud.githubusercontent.com/assets/9280031/11267902/56c89662-8eae-11e5-8441-ec57738f55d0.gif)

**Comment by alexandrudima** [comment]
@kristofferostlund I can reproduce the issue in 0.10.3, but on `master` this works again as expected. I am not really sure who from the team has fixed it already, but the December drop will have it fixed.

**Comment by kristofferostlund** [comment]
@alexandrudima I completely missed your response, thank you so much for the help!
