### ISSUE TITLE
`scm.providerBorder` color no longer seems to be used

### ISSUE THREAD

**Issue by gjsjohnmurray** [microsoft/vscode#194068]
https://github.com/microsoft/vscode/blob/1b5c0af328b5f4c6ae940371e1e5f90877d64ecf/src/vs/workbench/contrib/scm/browser/scmViewPane.ts#L2605

Searching source located no references.

**Comment by gjsjohnmurray** [comment]
Mentioned at https://code.visualstudio.com/api/references/theme-color#source-control-colors

Perhaps @joaomoreno remembers.

**Comment by joaomoreno** [comment]
This broke it: https://github.com/microsoft/vscode/commit/cf6efa68b5569bc240840abdcb799746357a79fb#diff-a29d112f7e1fecae5536543510588375d7283d06e96a4cf64325e8b600f30356L1888

Came from the exploration in: https://github.com/microsoft/vscode/issues/101103

We can just delete it.

**Comment by lszomoru** [comment]
Thanks! Will clean up the code and docs next milestone.
