### ISSUE TITLE
Exporting + Importing a profile with an icon doesn't preserve the icon

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#194095]
Testing #194038

1. On machine 1, create an empty profile "Zap" with the squirrel icon.
2. Export the profile to a file
3. On machine 2, import the profile. After clicking the "Create Profile" button, you'll see this:
![image](https://github.com/microsoft/vscode/assets/38270282/a27486ae-e413-4b2b-8764-074c7fec0445)
The gear icon is shown in the "Create New Profile" quick pick, not the squirrel icon.

**Comment by sandy081** [comment]
@alexr00 It is working for me. Can you please check if insiders is on latest on the second machine?

**Comment by alexr00** [comment]
Yes, They were both on latest yesterday.

**Comment by sandy081** [comment]
I tried again and it is working for me. Can you please share the profile?

**Comment by alexr00** [comment]
[Zap.code-profile.txt](https://github.com/microsoft/vscode/files/12736263/Zap.code-profile.txt)

**Comment by sandy081** [comment]
Closing this issue as we can no longer repro it
