### ISSUE TITLE
env.onDidChangeShell API naming feedback

### ISSUE THREAD

**Issue by lszomoru** [microsoft/vscode#194097]
Testing #194028

Most probably it's too late for this but I did notice some inconsistencies where both "shell" and "profile" are being used:
* The even is called "onDidChangeShell"
* The field tied to the event is called "shell"
* The command in VS Code that results in the event being fired is called "Select Default Profile"
* There is already existing API to register a profile provider - registerTerminalProfileProvider

It would be nice if we would settle on one of them and use it consistently across the API surface

**Comment by Tyriar** [comment]
These are different concepts though; a profile is a combination of a name, executable, arguments, env, icon, etc. and a shell is just the executable.
