### ISSUE TITLE
Test: Notebooks respect file whitespace settings

### ISSUE THREAD

**Issue by Yoyokrazy** [microsoft/vscode#194078]
Refs: #181905

- [x] anyOS @roblourens
- [x] anyOS @aiday-mar

Complexity: 2

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23194078%0A%0A&assignees=Yoyokrazy)

--- 
## Summary:

Notebooks now respect the following settings:
- `files.insertFinalNewLine`
- `files.trimTrailingWhitespace`
- `files.trimFinalNewlines`

## Steps to Test:
- Enable the settings above in any/all combinations.
- Open a notebook (feel free to use anything in [here](https://github.com/Yoyokrazy/ipynb-playground)).
- Ensure that these settings work as expected via explicit saving and autosaving.

--- 
Thanks so much for testing!

**Comment by aiday-mar** [comment]
`files.trimTrailingWhitespace` appears to be mentioned twice in the description above, I suppose one should be `files.trimFinalNewlines` ?

Otherwise works well on explicit save. For me it didn't work on auto-save, I opened an issue about this.

**Comment by roblourens** [comment]
If it is `files.trimFinalNewlines`, I don't see that working, can you confirm @Yoyokrazy?

**Comment by Yoyokrazy** [comment]
Yep, was a typo that was supposed to be `files.trimFinalNewLines`. 

@roblourens, I do see this setting working correctly on explicit and autosaves though. Could you give more details on where it's breaking on your end?

**Comment by roblourens** [comment]
I'm expecting it to trim the newlines on this cell. I'm pressing cmd+s too
![Recording 2023-09-26 at 10 48 31](https://github.com/microsoft/vscode/assets/323878/7e4b0191-d8ce-4b34-b309-b271b9913c69)

**Comment by Yoyokrazy** [comment]
Okay, yep confirmed that's a bug. Seems like the final newline trimming is bundled into the trim whitespace setting. Going to look into that implementation and see where things went sideways. Could you file an issue for that? Thanks
