### ISSUE TITLE
Test: Similar Commands feature the Command Palette

### ISSUE THREAD

**Issue by TylerLeonhardt** [microsoft/vscode#194021]
Refs: https://github.com/microsoft/vscode/issues/194017

- [x] anyOS @isidorn
- [x] anyOS @karrtikr
- [x] anyOS @aeschli

Complexity: 3

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23194021%0A%0A&assignees=TylerLeonhardt)

---

This iteration we introduced a section in the Command Palette called "similar commands" which shows up when your query doesn't exactly match an item with fuzzy matches but is similar. Implementation-wise, this uses TF-IDF to rank results based on frequency and whatnot.

However, you might recall that we already had a "similar commands" section that was entirely provided by Copilot Chat using ADA embeddings... because of this, we have two scenarios to test with this TPI:

### Scenario 1: Prerequisites

Disable Copilot Chat

### Scenario 2: Prerequisites

Enable Copilot Chat

#### Search for a few commands using natural language. For example:

> how do I change my language

_Should show `Change Language Mode` and `Configure Display Language`_

#### Search for a few commands swapping up words. For example:

> permalink copy

_Should show `GitHub Issues: Copy GitHub Permalink`_

#### Search for a few commands using synonyms. For example:

> use french locale

* _For Scenario 1, this should yield nothing because TF-IDF doesn't know anything about synonyms_
* _For Scenario 2, this should yield `Configure Display Language`._

#### Play!

Play around with the feature. Couple things to note:

1. synonyms support can be improved in TF-IDF... tracked here https://github.com/microsoft/vscode/issues/194020
2. You can visibly see the ADA results come in after TF-IDF. This is because we debounce 200ms because we have to make a web request to calculate the embeddings of the query. This is expected.

**Comment by isidorn** [comment]
Works great - love this feature 👏
