### ISSUE TITLE
Test debug toolbar in command center

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#194001]
Refs: https://github.com/microsoft/vscode/issues/192592  

- [x] anyOS @anthonykim1
- [x] anyOS @hediet

Complexity: 3

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23194001%0A%0A&assignees=jrieken)

--- 

There is a new experimental setting that allows to show the debug toolbar inside the command center. Test that

* the "debug.toolBarLocation" setting has a "commandCenter" option
* the setting is well documented and mentions/links to the command center setting
* debugging via the command center works
* simple and complex debug configurations work
* the debug toolbar never shows when not debugging

**Comment by hediet** [comment]
I think I like the debug buttons in the title bar, but I'm still not best friends with the command center (I never click on it, as I need to type in the F1 menu anyway, so it just adds visual noise).
Would be nice to have the debug buttons in the title bar without the command center.

**Comment by anthonykim1** [comment]
I do appreciate leaving the search file functionality right next to the debug toolbar, but I wish the search button was at the end of the bar(perhaps at the most righthand side position), with the debug toolbar placed more centered out. Love the feature by the way!

**Comment by jrieken** [comment]
Thanks for the nice feedback everyone

> with the debug toolbar placed more centered out. Love the feature by the way!

This is how I started but the challenge is that the title width is dynamic (because it shows file names) which makes the debug buttons reposition while stepping through code. That can be very frustrating because for every click/step you need to make sure you still over the right button
