### ISSUE TITLE
I can't run any of my code 

### ISSUE THREAD

**Issue by RaafaayaliRIT** [microsoft/vscode#194064]
Type: <b>Feature Request</b>

I downloaded both the python extension and code runner and I still can't find the run button. I tried looking up videos online but it seems no one has ran into the same issue as me. When I use another machine to code that has VS code I see the run button and it's very easy to find it but for somereason on my laptop it just doesn't show up. This bug happens everytime I try to clone a new repository, this is very annoying. 

VS Code version: Code 1.82.2 (abd2f3db4bdb28f9e95536dfa84d8479f1eb312d, 2023-09-14T05:55:25.390Z)
OS version: Windows_NT x64 10.0.22621
Modes: Restricted

**Comment by roblourens** [comment]
Please file this on the python extension repo, and maybe share a screenshot
