### ISSUE TITLE
Detect `const arrow function` as function

### ISSUE THREAD

**Issue by unional** [Microsoft/vscode#19401]
- VSCode Version: 1.8.1

This behavior exists for a while, that `type`, `let` and `const` is displayed with the wrench icon while `var` and `function` uses different icons.

This issue is specific to `const arrow function`, i.e.:
![image](https://cloud.githubusercontent.com/assets/3254987/22312421/93ad3548-e30c-11e6-8b8c-009a8e57f67c.png)

Since it is `const`, `foo` will always be an arrow function and it should be safe to disregard it as a `const` and consider it as a `function` directly:
![image](https://cloud.githubusercontent.com/assets/3254987/22312459/c89cf446-e30c-11e6-93c5-033baf03d28e.png)

There is a live example:

```ts
export interface AuthenticatePayload {
  authenticating: boolean
  authenticated: boolean,
  username?: string,
  errorMessage?: string
}

export function isAuthenticateAction(action: any)
  : action is FluxStandardAction<AuthenticatePayload, any> {
  return action.type.indexOf(AuthenticateActionType) === 0
}

export const isAuthAction = createActionTypeGuard<AuthenticatePayload>(AuthenticateActionType)

function createActionTypeGuard<Payload>(type: string) {
  return (action: any): action is FluxStandardAction<Payload, void> => {
    return action.type.indexOf(type) === 0
  }
}
```

![image](https://cloud.githubusercontent.com/assets/3254987/22312204/c1b57ce4-e30b-11e6-970d-df22627a5487.png)

**Comment by mjbvz** [comment]
Opened https://github.com/Microsoft/TypeScript/issues/14830 to track this upstream on the TypeScript side
