### ISSUE TITLE
Remove xtermTerminal.clearActiveSearchDecoration

### ISSUE THREAD

**Issue by tisilent** [microsoft/vscode#194098]
Version: 1.83.0-insider (user setup)
Date: 2023-09-26T06:31:13.416Z

![1](https://github.com/microsoft/vscode/assets/48614781/b0eceb8d-cbf9-43b8-b66a-847570b5f99a)

**Comment by tisilent** [comment]
Reproducible terminal ctrl + f

**Comment by Tyriar** [comment]
This was removed in https://github.com/xtermjs/xterm.js/commit/57db72d287f76632f0b4464b7668e7fe317fa6d2
