### ISSUE TITLE
Test: Settings editor search improvements

### ISSUE THREAD

**Issue by rzhao271** [microsoft/vscode#194026]
Refs: https://github.com/microsoft/vscode/issues/187959

- [x] anyOS @hbons
- [x] anyOS @bhavyaus
- [x] anyOS @sbatten

Complexity: 3

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23194026%0A%0A&assignees=rzhao271)

---

I have changed the search behaviour in the Settings editor to restrict the number of local and remote search results shown,
and to sort the results by their order within the table of contents (ToC) when the ToC is shown.

## Part 1: Sanity testing

1. Navigate to the Settings editor.
2. Set workbench.settings.settingsSearchTocBehavior to filter.
3. Do a search.
4. Verify that there are fewer results than or the same number of results as on Stable.
5. Verify that the search results are sorted by ToC order.
6. Set workbench.settings.settingsSearchTocBehavior to hide.
7. Clear the search query.
8. Do another search.
9. Verify that the ToC hides and that the search results are not grouped by category. For example, a Python setting could appear between two TS settings now.
10. Set workbench.settings.settingsSearchTocBehavior to filter again.
11. Clear the search query.
12. Do another search.
13. Verify that the ToC shows up and that the search results are in ToC order again.

## Part 2: Open-ended testing

Try out different queries in the Settings editor and confirm that the search results make sense.
If a search result doesn't seem to make sense, add the search result that showed up along with the query used to an issue for this TPI.
If a search result seems to be missing, add the the search result that didn't show up along with the query used to an issue for this TPI.

**Comment by hbons** [comment]
I can confirm all the steps on macOS. 

Noticed a some strange things however:

1. When I search for `workbench.settings.settingsSearchTocBehavior` and change it from `hide` to `filter`, I first need to clear the search field using Backspace for it to take effect on the category sidebar. When I select the search text and immediately start typing without clearing the field first, the sidebar stays empty.

2. I expect the sidebar to actually hide when in hide mode. It looks weird to have it empty:

<img width="632" alt="image" src="https://github.com/microsoft/vscode/assets/103326/ae111ca9-251e-4708-a628-640f4e0f87da">
