### ISSUE TITLE
Test: Terminal context menu contributions

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#194029]
Refs: #79034

- [x] anyOS @hbons
- [x] anyOS @Yoyokrazy

Complexity: 3

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23194029%0A%0A&assignees=Tyriar)

---

To test:

1. Create a test extension
2. Verify docs on `terminal/context` and `terminal/title/context` looks good: https://github.com/microsoft/vscode-docs/blob/vnext/api/references/contribution-points.md#contributesmenus
3. Add new menu entries for `terminal/context` and `terminal/title/context`, hook them up to commands in the extension
4. Verify intellisense works in package.json for the menu entries
5. Verify the commands are called with the first argument being the focused terminal
6. Verify the commands are called with the second argument being an array of all selected terminals

**Comment by hbons** [comment]
Confirmed on macOS I can add menu items to both terminal menus in a new extension:

<img width="383" alt="image" src="https://github.com/microsoft/vscode/assets/103326/429e32ff-6767-4b25-9feb-c61ed7a473b7">

<img width="383" alt="image" src="https://github.com/microsoft/vscode/assets/103326/a2bd3b83-0d29-49bb-b229-76fa677fcec4">

I've used this snippet in `extension.ts` to check the arguments passed by the command:

```
	let disposable = vscode.commands.registerCommand('test.helloWorld', (...args: any[]) => {
		vscode.window.showInformationMessage("test: " + JSON.stringify(args));
	});
```

Result:

<img width="506" alt="image" src="https://github.com/microsoft/vscode/assets/103326/ab68d3e3-32e8-4630-9685-18b962920149">
