### ISSUE TITLE
Quiet Light is very pink

### ISSUE THREAD

**Issue by andy-hanson** [Microsoft/vscode#19407]
- VSCode Version: 1.9.0-insider
- OS Version: Linux Mint 17.3

Steps to Reproduce:

1. Open a TypeScript File
2. Set Theme to Quiet Light

Everything is pink!

![screenshot](https://cloud.githubusercontent.com/assets/5387404/22316344/69902602-e321-11e6-89b1-e81984e5f5b4.jpg)

C# and Python seem to use black text a lot more in comparison.

**Comment by isidorn** [comment]
PRs that fix this are welcome
[Code pointer](https://github.com/Microsoft/vscode/blob/master/extensions/theme-quietlight/themes/quietlight-color-theme.json#L3)

**Comment by aidantwoods** [comment]
Just incase someone else finds this issue (like me) wondering why the recent update to VSCode made the window borders on quiet light very pink
![screen shot 2017-05-06 at 20 58 13](https://cloud.githubusercontent.com/assets/3288888/25775528/d4e0e1c2-329e-11e7-8a49-c32f250221bf.png)

Sticking this in your user `settings.json` should revert the border colours back to what they were 😉 
```json
"workbench.colorCustomizations": {
        "activityBar.background": "#2c2c2c",
        "activityBar.foreground": "#ffffff",
        "titleBar.activeBackground": "#e6e6e6"
    }
```
![screen shot 2017-05-06 at 20 58 34](https://cloud.githubusercontent.com/assets/3288888/25775529/d7424c1c-329e-11e7-9e68-a435059f8d23.png)
