### ISSUE TITLE
Test comments accessibility

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#194012]
Refs: https://github.com/microsoft/vscode-pull-request-github/issues/1930, https://github.com/microsoft/vscode/issues/192377

- [x] macOS @DonJayamanne
- [x] linux @connor4312
- [x] windows @joyceerhl

Complexity: 4

Authors: @alexr00, @meganrogge 

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23194012%0A%0A&assignees=alexr00,meganrogge)

---

Comments can be tested using the GitHub Pull Requests and Issues extension.

1. Install the pre-release version of GitHub Pull Requests and Issues.
2. Check out a PR that has some comments, or expand a PR that has comments in the "Pull Requests" view. 
3. Toggle "Screen reader accessibility" mode on. 
4. Using a screen reader, verify that when you open a file with commenting ranges that you hear a status read that the editor has commenting ranges.
5. Verify that if you open the editor accessibility help menu `(alt + F1)` in a file with commenting ranges that the help menu include useful information about navigating comments.
6. Try out the comment help from the accessibility help menu. Verify that you can use the listed keyboard shortcuts for comments. 
7. Open the "Comments" view. Use your keyboard to navigate through the "Comments" view. Verify that enter causes the comment to be revealed and focused. Verify that space just reveals the comment.
8. When a comment widget gets focused, verify that you hear about accessibility help. Trigger that `(alt + F1)` and verify it has useful information / walks a person through what they should expect.
9. Disable `accessibility.verbosity.comments` and verify that you no longer hear the hint to open accessibility help when you focus a comment widget, an editor with comments, or a diff editor with comments.

**Comment by DonJayamanne** [comment]
Ok. I can see why complexity is 4, sure does take time, not really complicated but time consuming.
Works well, just as descrived.
