### ISSUE TITLE
Test: SCM Sync view

### ISSUE THREAD

**Issue by lszomoru** [microsoft/vscode#194016]
Refs: #192290

- [x] anyOS @joaomoreno 
- [x] anyOS @Yoyokrazy 

Complexity: 4

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23194016%0A%0A&assignees=lszomoru)

---

This milestone we have added a new view, "Source Control Sync", that displays incoming/outgoing commits between the current local branch and the upstream, or the base branch. The view is currently experimental but I would like to get it tested in order to understand the issues that should be fixed before we can remove the "experimental" label. The primary action buttons to publish/sync branch have been moved to the "Sync view". The "Source Control" view is now limited to committing.

### Prerequisites
* Install the latest VS Insiders release
* Enable the `scm.experimental.showSyncView` setting

### View
* Launch VS Code Insiders and open a folder/workspace that contains a git repository
* Switch to the "Source Control" viewlet
  * Confirm that the new "Source Control Sync" view appears and is expanded by default
  * Confirm that you are able to use the `...` menu to hide/show and "Sync view"
  * Confirm that you are able to move the "Sync view" to the secondary side bar, and panel

### Publish branch flow
* Launch VS Code Insiders and open a folder/workspace that contains a git repository
* Ensure that you have a clean working tree and you are currently on the default branch (ex: main)
* Create a new topic branch (ex: topic-branch), and switch to the "Sync view"
  * Confirm that the incoming/outgoing nodes contain 0 entries
  * Confirm that the incoming node is set to the correct branch (ex: main)
* Create several commits with additions, modifications, deletions 
  * Confirm that the commits appear in the "Outgoing Changes" node
  * Expand the summary node under "Outgoing Changes" and confirm that all files appear that were changed
  * Expand each commit and confirm that they contain the correct information
  * Confirm that the file decorations (a: A, M, D) appear correctly for each resource
* Make some more changes and use "Commit (Amend)" in the commit action button
  * Confirm that the commit entry under "Outgoing Changes" is updated correctly
* Click the "Publish Branch" primary action in the "Sync view"
  * Confirm that the branch has been published to the remote
  * Confirm that the "Incoming Changes" node was switched to the upstream (ex: origin/topic-branch)
  * Confirm that both "Incoming Changes" and "Outgoing changes" nodes have 0 children
  * Confirm that the action button is now a disabled "Sync Changes" button

### Sync changes flow
* Make some more changes locally and commit them
* Open https://gihub.com and make some changes and commit them
* Switch back to VS Code and manually run the "Git: Fetch" command
  * Confirm that the "Incoming Changes" node is updated correctly
* Expand the nodes under "Incoming Changes"
  * Confirm that the summary node contains all the changes
  * Confirm that the commit nodes contain the correct data
* Click the "Sync Changes" primary action in the "Sync view"
  * Confirm that changes are pulled from the repository, and pushed to the upstream
  * Confirm that "Incoming Changes" and "Outgoing Changes" have 0 children
  * Confirm that the "Sync Changes" button is being disabled 

### Branch base detection
* Launch VS Code Insiders and open a folder/workspace that contains a git repository
* Ensure that you have a clean working tree and you are currently on the default branch (ex: main)
* Create a new topic branch (ex: featureA) using the "Create Branch..." command from the command palette
  * Confirm that the "Incoming Changes" is set to the default branch (ex: main)
* Make some changes in the featureA branch and commit them
* Create a new topic branch (ex: featureB) using the "Create Branch..." command from the command palette
  * Confirm that the "Incoming Changes"is set to the featureA branch
* Which on the featureB branch, invoke the "Create Branch From..." command. Select featureA as the source and specify a name for the new branch (ex: featureC)
  * Confirm that the "Incoming Changes"is set to the featureA branch 

### View mode (list vs. tree)
* Launch VS Code Insiders and open a folder/workspace that contains a git repository
* Ensure that you have a clean working tree and you are currently on the default branch (ex: main)
* Make some changes and create multiple commits
* Expand the summary node, and the commit nodes until the "Outgoing Changes" node
* From the "..." menu of the view switch between Tree/List view modes
  * Confirm that the Tree/List is rendered correctly (expansion, selection)
  * Confirm that the file decorations appear correctly in both modes

**Comment by joaomoreno** [comment]
Very cool!

**Comment by Yoyokrazy** [comment]
Joao was thorough, great work! Will definitely be using this.
