### ISSUE TITLE
Support more default debugging browsers besides Chrome/Edge for Linux arm64

### ISSUE THREAD

**Issue by allisonchou** [microsoft/vscode#194051]
Transferring from https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1889132/ (MSFT internal)
According to [this doc](https://code.visualstudio.com/docs/nodejs/browser-debugging#:~:text=The%20simplest%20way%20to%20debug,it%20to%20open%20the%20page.), VS Code only has Chrome & Edge supported as default debugging browsers, which prevents the scenario below from working as expected on Linux arm64 (since Linux ARM64 reportedly doesn't support Edge/Chrome).

---

Affected Build:
VSCode 1.82.2: https://code.visualstudio.com/download

C# extension 2.4.4
C# DevKit extension 0.5.93
OS: Ubuntu arm64, Red Hat ARM64 and SLES ARM64

Steps to reproduce:
1. Install the VSCode and C#/CDK.
2. Create blazorwasm projects and open it in VSCode.
3. Right Click project > Debug > Start New Instance

Expected:
After installing the Chrome or Edge browser, the blazorwasm projects should run successfully.

Actual:
The Chrome and Edge browsers aren't supported on Linux arm64.
[677140 - Chrome (official, not chromium) does not support armhf or arm64 - chromium](https://bugs.chromium.org/p/chromium/issues/detail?id=677140)
[Arm64 linux support? · Issue #697 · MicrosoftEdge/Status (github.com)](https://github.com/MicrosoftEdge/Status/issues/697)

**Comment by roblourens** [comment]
So what are you expecting to happen here, given that those browsers aren't supported at all?

**Comment by allisonchou** [comment]
@roblourens I would envision VS Code eventually supporting other browsers such as Firefox for debugging (which from my research seems to be supported on Linux arm64 machines).

**Comment by roblourens** [comment]
There is a firefox debug extension. I don't think we will support this out of the box
