### ISSUE TITLE
No indication that there's a search box for SR user

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#194042]
Testing: #194040

The first icon gets focused, skipping over the input box.

https://github.com/microsoft/vscode/assets/29464607/5feb703d-c2d6-440a-a54d-75bc64a3c74a

**Comment by meganrogge** [comment]
I think focus should go to the search field first then tab should take a user to the icons. For the aria label, we could say "search icons, tab to explore icons"

**Comment by sandy081** [comment]
I followed the same pattern as quick pick here. We do the same when we open command pallette for eg

**Comment by meganrogge** [comment]
yeah I see that the quick pick behaves similarly. I'm a bit surprised we don't read the quick pick placeholder 🤔. @TylerLeonhardt do you know how we expect SR users to realize they can type in the input box?

**Comment by TylerLeonhardt** [comment]
NVDA does read the placeholder.

**Comment by meganrogge** [comment]
Not working for me with VoiceOver

**Comment by meganrogge** [comment]
Would setting the tab index to 0 on the input box fix this?

**Comment by TylerLeonhardt** [comment]
@meganrogge if you hit `shift+tab` which will no longer highlight an active item, do you hear the placeholder?

**Comment by TylerLeonhardt** [comment]
But also, if it works in NVDA then we should get VoiceOver to fix their behavior, no? My guess is that because we use `aria-activedescendant` VoiceOver doesn't handle that as well as NVDA.

**Comment by meganrogge** [comment]
> @meganrogge if you hit shift+tab which will no longer highlight an active item, do you hear the placeholder?

unfortunately not

**Comment by sandy081** [comment]
Closing this as this is following the same pattern as quick pick.
