### ISSUE TITLE
Snippet insert expansion is incorrect in some cases

### ISSUE THREAD

**Issue by waderyan** [Microsoft/vscode#19406]
VS Code Version - Insiders
OS Version - macOS

```
var fs = require('fs');

fs.readFile
```

Type opening paren `(`

I expect to see 

```
fs.readFile(file, options, callback)
```
 
Instead I see

![image](https://cloud.githubusercontent.com/assets/2449568/22316059/72d75980-e31f-11e6-8511-74bbd4740056.png)

```
fs.readFile((file), options, callback, err, data)
```

Notice how `err` and `data` are flattened. Also the parens around file don't seem correct. You can see a similar thing when you type `console.log(`

**Comment by sandy081** [comment]
@mjbvz I see `err` and `data` attributes are replaced by `callback` which is good. But I still see the parenthesis around `file`. Hence reopening.

**Comment by mjbvz** [comment]
@sandy081 Thanks. We're now tracking that specific bug here: #19820
