### ISSUE TITLE
Missing coloring on method parameter reference

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#19403]
- VSCode Version: Code - Insiders 1.9.0-insider (fbea777a881523bc01a1358d115b16673dc5942e, 2017-01-25T07:04:54.108Z)
- OS Version: Darwin x64 15.6.0
- Extensions:

|Extension|Author|Version|
|---|---|---|
|EditorConfig|EditorConfig|0.3.4|
|autofilename|JerryHong|0.1.3|
|vscode-docker|PeterJausovec|0.0.11|
|azure-cli|chrmarti|0.2.0|
|regex|chrmarti|0.0.7|
|vscode-eslint|dbaeumer|1.2.2|
|ghlink|dt|0.0.4|
|tslint|eg2|0.8.1|
|vscode-scss|mrmlnc|0.6.0|
|PowerShell|ms-vscode|0.8.0|
|cpptools|ms-vscode|0.9.3|
|debugger-for-chrome|msjsdiag|2.4.2|
|diff|rafaelmaiolla|0.0.1|
|vscode-open-in-github|sysoev|1.3.1|

---

In our source, using Dark+:
![screen shot 2017-01-25 at 4 21 07 pm](https://cloud.githubusercontent.com/assets/9205389/22315234/67331b50-e31a-11e6-93d0-9f76592bee2d.png)

A regression from 1.8, marking as important.

**Comment by alexandrudima** [comment]
Just checked from a TM matching point of view:

Before it was matching the rule for support.class which IMHO was unexpected. The token is not a class name, it is a variable name. 

@aeschli 1.8.1 was actually weird here, making an argument the same color as a type name.

![image](https://cloud.githubusercontent.com/assets/5047891/22325059/b7c67b2e-e3ac-11e6-963a-1bcd6592032c.png)

**Comment by aeschli** [comment]
The typescript grammar has just removed the support.module.node scope.
It was a source of trouble as it could stand for a variable, function or type.

I'd rather do the grammar update later as to not invalidate our testing.
