### ISSUE TITLE
Test icon selection widget

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#194040]
- [x] Windows @hediet 
- [x] macOS @meganrogge 
- [x] Linux @justschen 

Complexity: 3

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23194040%0A%0A&assignees=sandy081)

---

Please do an exploratory testing of the icon selection widget that is available via creating or editing profile (Gear > Profiles > Create). 
- Test the mouse/keyboard interactions
- Test filtering
- Test accessibility

**Comment by hediet** [comment]
Nice job!
