### ISSUE TITLE
Crazy tons of Just My Code log text in debug output windows; VS Code for Mac

### ISSUE THREAD

**Issue by SogoGolf** [microsoft/vscode#194080]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.82.2 (Universal)
- OS Version:  Darwin arm64 22.6.0

Steps to Reproduce:

When I am debugging a C# console app in VS Code on Mac (latest version of VS Code) I get TONS and TONS of this yellow logger text in the debug window !! It is SO annoying as it is so hard to weed out my own Console.Writeline statements. How can I turn this off? There should be some really obvious way to do this in VS Code on Mac.

here is some of what i see in the debug console:
oaded '/usr/local/share/dotnet/shared/Microsoft.NETCore.App/7.0.11/Microsoft.Win32.Primitives.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Loaded '/usr/local/share/dotnet/shared/Microsoft.NETCore.App/7.0.11/System.Net.NameResolution.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Loaded '/usr/local/share/dotnet/shared/Microsoft.NETCore.App/7.0.11/System.Threading.ThreadPool.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Loaded '/usr/local/share/dotnet/shared/Microsoft.NETCore.App/7.0.11/System.Threading.Thread.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Loaded '/usr/local/share/dotnet/shared/Microsoft.NETCore.App/7.0.11/System.Collections.NonGeneric.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Loaded '/usr/local/share/dotnet/shared/Microsoft.NETCore.App/7.0.11/System.Diagnostics.Process.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Loaded '/usr/local/share/dotnet/shared/Microsoft.NETCore.App/7.0.11/System.Text.Encoding.CodePages.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Loaded '/usr/local/share/dotnet/shared/Microsoft.NETCore.App/7.0.11/System.Net.Quic.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
found user xxx@yyyy.com with uid yyyyy43-f11111-4cc9-9917-cdd902aa9fff

**Comment by roblourens** [comment]
Please file this on the C# extension, thanks

**Comment by mfg-aj** [comment]
sure but which one of the 5,800 MS repo's is that ? :-)
