### ISSUE TITLE
notebook.scrolling.anchorToFocusedCell is allowing cell to scroll off viewport

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#194153]
Testing #194069

Provided I understand the setting, the focused cell shouldn't be able to scroll off the page without user input as I've said to anchor the focused cell:

![Image](https://github.com/microsoft/vscode/assets/2193314/3a261b04-b9b2-4be9-b91f-99648591401f)

I was expecting as the setting said, for the selected cell to remain steady and not move at all, while the content above changed and the scroll position was adjusted each time.

**Comment by Tyriar** [comment]
I think I might be seeing https://github.com/microsoft/vscode/issues/193231

**Comment by Tyriar** [comment]
The anchoring also doesn't work when both cells are fully in the viewport:

![Recording 2023-09-26 at 08 21 39](https://github.com/microsoft/vscode/assets/2193314/37b5b2d8-0748-4811-abba-adaf57008c95)

**Comment by TylerLeonhardt** [comment]
This seems to be working for me for some reason if the cell underneath the executing cell has a long output that causes a scroll bar.
![image](https://github.com/microsoft/vscode/assets/2644648/abad9b4a-5d8b-43b8-ace2-18745d4dc642)

**Comment by amunger** [comment]
yeah this is completely broken after my late change yesterday, sorry about that

**Comment by TylerLeonhardt** [comment]
Why wouldn't auto have the same behavior as true in this case?

**Comment by amunger** [comment]
no, we left auto as the old behavior because we couldn't decide on a good default behavior so we're looking to get some feedback with the setting.

auto is currently:
If the cell being resized is partially visible at the top of the viewport, anchor to the focused cell. Otherwise anchor to the resizing cell.

**Comment by amunger** [comment]
OK, I just wanted to make sure you still felt that way after trying it out first hand (I'm not a fan of that behavior in certain senarios)
