### ISSUE TITLE
Is notebook.scrolling.anchorToFocusedCell really necessary?

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#194158]
Testing #194069

This setting seems like overkill to me and there is a good behavior we should be aiming towards which is notebook.scrolling.anchorToFocusedCell = auto. You could also do something clever like disable the anchoring when a user starts scrolling, and when they focus a cell or type it re-enables the anchoring. I rarely use notebooks but to me this seems like a setting that will see very low usage and is not worth the cost of an extra setting imo.

Note that anchorToFocusedCell = auto doesn't work as expected currently, the setting only seems to do anything after I scroll:

![Image](https://github.com/microsoft/vscode/assets/2193314/38b5b365-5bca-4a1f-a338-1d56e26e1365)

🤷

**Comment by amunger** [comment]
I can change the setting to be experimental to give more leniency to change/remove it, but the behaviors are very different, so we'd like to give users a way to both experiment and revert back in case we missed some case of bad behavior

**Comment by Tyriar** [comment]
@amunger I like the idea of using experimental and seeing how many users change it to see if it's worth a setting
