### ISSUE TITLE
Vertical alignment on tab icons seems unaligned when compact

### ISSUE THREAD

**Issue by andreamah** [microsoft/vscode#194180]
Testing #193981

![Image](https://github.com/microsoft/vscode/assets/31675041/163ce537-45da-4793-8582-abd5c62cf8fb)

1. Set `window.density.editorTabHeight` to `compact` 
2. Notice that the icon almost looks too high compared to the text. For example, in my screenshot, the `S` in settings seems to not be aligned with the icon (off by a few pixels if you look closely).

**Comment by benibenj** [comment]
This has always been this way as it uses the line height to vertically align the text. It's just a bit more noticeable with the reduced tab height. @bpasero is there a reason why line-height is used instead of flexbox?

**Comment by bpasero** [comment]
@benibenj I actually do not remember, but feel free to explore alternatives and see if that improves it.

We also have https://github.com/microsoft/vscode/issues/162995 opened which talks about a similar problem in the status bar I believe.

**Comment by daviddossett** [comment]
It may be because the line height of the text and the dimensions of the icon don't match. I run into this within Figma all the time :)

**Comment by bpasero** [comment]
Related :) https://tonsky.me/blog/centering/
