### ISSUE TITLE
Download VS Code shows SSL error

### ISSUE THREAD

**Issue by Hanneses** [microsoft/vscode#194181]
- VS Code Version: latest
- OS Version: Windows 11
- Browser: Firefox (117.0.1), Chrome (117.0.5938.92), Edge (117.0.2045.41)

**Steps to Reproduce:**

1. Go to https://code.visualstudio.com/Download
2. Click any download link (blue buttons), which leads to page *https://code.visualstudio.com/docs/?dv=win64* and directs to *https://az764295.vo.msecnd.net/stable/abd2f3db4bdb28f9e95536dfa84d8479f1eb312d/VSCodeSetup-x64-1.82.2.exe*

**Error Behavior:**

Firefox shows following SSL error:
  > Beim Verbinden mit az764295.vo.msecnd.net trat ein Fehler auf. SSL hat einen Eintrag erhalten, der die maximal erlaubte Länge überschritten hat.
  > 
  > Fehlercode: SSL_ERROR_RX_RECORD_TOO_LONG

**Comment by joaomoreno** [comment]
Can you update to the latest Firefox?

**Comment by HannesScheffel** [comment]
> Can you update to the latest Firefox?
> 
> https://support.mozilla.org/en-US/questions/1222739

Yes, the error occures also with Firefox latest version 118.0 - and as mentioned also with Chrome and Edge.

**Comment by joaomoreno** [comment]
Can you show me a screenshot of the error in Chrome?

**Comment by Hanneses** [comment]
Thats the error in Chrome (latest version 117.0.5938.150):

![grafik](https://github.com/microsoft/vscode/assets/123950376/60a42314-5301-496a-983b-6307f69c838f)

**Comment by joaomoreno** [comment]
This is a system misconfiguration. Please talk to to your system administrator, since something is messing with SSL certificates between your machine and our servers.
