### ISSUE TITLE
Custom code actions that run on save don't get drop down UI

### ISSUE THREAD

**Issue by dbaeumer** [microsoft/vscode#194112]
Testing #194031

ESlint contributes the code action `source.fixAll.eslint` which doesn't have code complete in the JSON editor nor the drop down in the UI.

![Image](https://github.com/microsoft/vscode/assets/1931590/3caa771a-38d2-4f39-9e7a-92a9ac8b301f)

**Comment by justschen** [comment]
Related to https://github.com/microsoft/vscode/issues/161284
