### ISSUE TITLE
Reconsider `editor.codeActionsOnSave` change

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#194119]
Testing #194077

It seems that the `editor.codeActionsOnSave` setting has changed its value type. There are a couple of issues with this

* no automatic migration happened, e.g. all existing usages are now flagged as errors (see below). This isn't user-friendly and if we stick with this we should make sure to use our auto-migration logic. Check [`IConfigurationMigrationRegistry`](https://github.com/microsoft/vscode/blob/af0f0398694cb1411318615383db98933ea24cf6/src/vs/workbench/common/configuration.ts#L48-L50) for this
* I fail to understand the added value of this, the new values are as expressive as the old ones
* For `editor.codeActionsOnSave` there is no IntelliSense of the value set

<img width="693" alt="Screenshot 2023-09-26 at 11 42 20" src="https://github.com/microsoft/vscode/assets/1794099/172f3c49-9624-4cf5-9601-2d2a0c7334a0">

**Comment by justschen** [comment]
intellisense issue related to https://github.com/microsoft/vscode/issues/161284

**Comment by jrieken** [comment]
There is an unfortunate regression... It looks like the migration code that I have recommended isn't working great. I revert your changes and we need a path forward: either we get a fix for the migration or the setting is defined as boolean or string enum

**Comment by justschen** [comment]
resolved in https://github.com/microsoft/vscode/issues/194437. Migration to happen in next milestone with https://github.com/microsoft/vscode/issues/194427 👍
