### ISSUE TITLE
notebook.gotoSymbols.showAllSymbols has no effect

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#194120]
Testing #194053

1. Use https://github.com/microsoft/vscode/files/12718836/symbols.ipynb.txt
2. Open it in a notebook. Select kernel. Open outline
3. Now open settings and enable notebook.gotoSymbols.showAllSymbols 
4. Go back to notebook and open outline
5. Same results as in step 2 🐛 

I do not see any difference in enabling this settings. Am I doing something wrong?
Also why do we have a setting for this? Why not just enable it by default?

![Screenshot 2023-09-26 at 12 18 08](https://github.com/microsoft/vscode/assets/1926584/5dda4930-f848-478f-a4a1-f04ceba56378)

**Comment by amunger** [comment]
Can you run a cell successfully?
Do you have `python.languageServer` set for some reason?
Are symbols working correctly - if you have the following cell and press f12 on the second `var`, does it navigate to the first
```
var = 'foo'
print(var)
```

**Comment by andreamah** [comment]
I have this same problem. the languageServer isn't set, but goto definition isn't working despite being able to run code.
<img width="573" alt="image" src="https://github.com/microsoft/vscode/assets/31675041/ed13cb83-ae21-46df-8a10-bc9314dec21d">

**Comment by amunger** [comment]
@isidorn - can you also make sure the Pylance extension is installed - that's why Andrea didn't have symbol support.
Found by trying in a fresh temp profile with the python extension installed.

**Comment by isidorn** [comment]
I did not have pylance. Works great now. Thank you!

My last question before we close this issue :)
> Also why do we have a setting for this? Why not just enable it by default?

**Comment by amunger** [comment]
> why do we have a setting for this? Why not just enable it by default?

Notebook users have a pretty strong affinity with an outline view that focuses on Markdown headers, so I was worried about adding a lot of noise in the quickpick goto in the case that they used that as well.

We can definitely look at trying to remove the setting in the future tho

**Comment by isidorn** [comment]
Ok. I would be sad if this gets hidden under a setting and users do not find it.
