### ISSUE TITLE
Align wording in context menu

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#194128]
Testing #193991

The context menu shows configuration entries. They are called

* Enable Tab
* Separate Pinned Tabs

The wording isn't aligned, e.g it could be "Enable Separate Pinned Tabs" but IMO it shouldn't, the "_Enable_" prefix shouldn't be there for the former (the check mark implies that). How about

* ✔️ Tabs 
* ✔️ Separate Pinned Tabs 

Alternative idea: Editor Tabs, Pinned Editor Tabs on Separate Row

---

<img width="261" alt="Screenshot 2023-09-26 at 14 36 24" src="https://github.com/microsoft/vscode/assets/1794099/2524e41b-5f28-4587-80ee-7fb7a2edecc1">

**Comment by bpasero** [comment]
I like `Editor Tabs` and `Separate Pinned Editor Tabs`

**Comment by jrieken** [comment]
As for implementing this: The `Action2` world allows to define a special title when a command is rendered with a check mark, see [this](https://github.com/microsoft/vscode/blob/a8b25726159c5f4414012bcd292dc7fafcfce3a6/src/vs/platform/action/common/action.ts#L79)
