### ISSUE TITLE
Terminal text is weirdly spaced

### ISSUE THREAD

**Issue by ulugbekna** [microsoft/vscode#194156]
# Description

Text in the terminal is weirdly spaced. (more [info](https://vscodeteam.slack.com/archives/C03ERNTC03X/p1695375586931459)) 

Changing zoom fixes it, eg zooming in. 

I don't know how to repro, unfortunately. 

# Version

```
Version: 1.83.0-insider
Commit: 8ecf5453e8e8f98cca0f9a661d3a6457d8a0e703
Date: 2023-09-26T05:51:48.388Z
Electron: 25.8.2
ElectronBuildId: 23977753
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Darwin arm64 22.6.0
```

**Comment by ulugbekna** [comment]
When this happens, the cursor size becomes larger. Killing the terminal and opening a new one fixes the problem. Resizing vscode also helps to fix the issue.


https://github.com/microsoft/vscode/assets/16353531/62d61227-dab2-441c-918e-6d5c08228ee8

**Comment by Tyriar** [comment]
@ulugbekna what's in your settings.json?

**Comment by ulugbekna** [comment]
```json
{
  "[javascript]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode",
    "editor.codeActionsOnSave": {}
  },
  "[json]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode"
  },
  "[jsonc]": {
    "editor.defaultFormatter": "vscode.json-language-features"
  },
  "editor.accessibilitySupport": "off",
  "editor.codeLensFontFamily": "\"Jetbrains Mono\"",
  "editor.experimental.asyncTokenization": true,
  "editor.fontFamily": "JetBrains Mono, Menlo, Monaco, 'Courier New', monospace",
  "editor.fontLigatures": true,
  "editor.fontSize": 14,
  "editor.renderWhitespace": "all",
  "editor.smartSelect.selectSubwords": true,
  "errorLens.gutterIconSet": "circle",
  "errorLens.gutterIconSize": "50%",
  "explorer.fileNesting.expand": false,
  "explorer.fileNesting.patterns": {
    "*.ts": "${basename}.test.ts"
  },
  "files.insertFinalNewline": true,
  "files.simpleDialog.enable": true,
  "git.branchPrefix": "ulugbekna/",
  "git.branchRandomName.enable": true,
  "git.confirmSync": false,
  "git.pullBeforeCheckout": true,
  "githubPullRequests.pullBranch": "never",
  "githubPullRequests.pushBranch": "always",
  "githubPullRequests.quickDiff": false,
  "gitlens.codeLens.authors.enabled": false,
  "gitlens.codeLens.enabled": false,
  "interactiveWindow.alwaysScrollOnNewCell": false,
  "keyboard.dispatch": "keyCode",
  "notebook.cellToolbarLocation": {
    "default": "right",
    "jupyter-notebook": "right"
  },
  "python.experiments.optInto": [
    "pythonTestAdapter"
  ],
  "redhat.telemetry.enabled": false,
  "testExplorer.useNativeTesting": true,
  "typescript.implementationsCodeLens.enabled": true,
  "typescript.inlayHints.enumMemberValues.enabled": true,
  "typescript.inlayHints.functionLikeReturnTypes.enabled": true,
  "typescript.inlayHints.parameterNames.enabled": "all",
  "typescript.inlayHints.parameterTypes.enabled": true,
  "typescript.inlayHints.propertyDeclarationTypes.enabled": true,
  "typescript.inlayHints.variableTypes.enabled": true,
  "typescript.tsserver.experimental.enableProjectDiagnostics": true,
  "typescript.tsserver.web.projectWideIntellisense.enabled": false,
  "vim.easymotion": true,
  "vim.highlightedyank.enable": true,
  "window.autoDetectColorScheme": true,
  "workbench.colorCustomizations": {
    "editorIndentGuide.activeBackground1": "#f5ffd0",
    "editorIndentGuide.activeBackground2": "#f5ffd0",
    "editorIndentGuide.activeBackground3": "#f5ffd0",
    "editorIndentGuide.activeBackground4": "#f5ffd0",
    "editorIndentGuide.activeBackground5": "#f5ffd0",
    "editorIndentGuide.activeBackground6": "#f5ffd0",
    "editorIndentGuide.background1": "#005f5f",
    "editorIndentGuide.background2": "#005f5f",
    "editorIndentGuide.background3": "#005f5f",
    "editorIndentGuide.background4": "#005f5f",
    "editorIndentGuide.background5": "#005f5f",
    "editorIndentGuide.background6": "#005f5f",
  },
  "workbench.colorTheme": "Default Dark+",
  "workbench.commandPalette.experimental.useSemanticSimilarity": true,
  "workbench.editor.splitSizing": "split",
  "workbench.experimental.share.enabled": true,
  "workbench.preferredDarkColorTheme": "Default Dark+",
  "workbench.preferredLightColorTheme": "Default Light+",
  "zenMode.centerLayout": false,
  "zenMode.hideLineNumbers": false,
  "zenMode.hideTabs": false,
  "typescript.tsserver.log": "off",
  "githubPullRequests.experimental.createView": true,
  "[typescript]": {
    "editor.defaultFormatter": "vscode.typescript-language-features",
    "editor.codeActionsOnSave": {}
  },
  "editor.stickyScroll.enabled": true,
  "editor.formatOnSave": true,
  "editor.codeActionsOnSave": {
    "source.fixAll": true,
    "source.fixAll.eslint": true
  },
  "azure.resourceFilter": [
    "72f988bf-86f1-41af-91ab-2d7cd011db47/9b16b0df-65b6-46d3-b9c9-e4fbc86b1fa7"
  ],
  "output.smartScroll.enabled": false,
  "githubIssues.queries": [
    {
      "label": "My Issues",
      "query": "default"
    },
    {
      "label": "Created Issues",
      "query": "author:${user} state:open repo:${owner}/${repository} sort:created-desc"
    },
    {
      "label": "Recent Issues",
      "query": "state:open repo:${owner}/${repository} sort:updated-desc"
    }
  ],
  "editor.minimap.enabled": false,
  "errorLens.enabled": true,
  "notebook.diff.ignoreMetadata": true,
  "notebook.diff.ignoreOutputs": true,
  "markdown.editor.pasteUrlAsFormattedLink.enabled": "smart",
  "notebook.lineNumbers": "on",
  "workbench.tree.indent": 16,
  "workbench.tree.renderIndentGuides": "always",
  "accessibility.unfocusedViewOpacity": 0.9,
  "terminal.integrated.windowsEnableConpty": false,
  "terminal.integrated.showExitAlert": false,
  "terminal.integrated.gpuAcceleration": "off",
  "terminal.integrated.environmentChangesRelaunch": false,
  "typescript.referencesCodeLens.enabled": true,
  "remote.autoForwardPorts": true,
  "remote.autoForwardPortsSource": "output",
  "extensions.ignoreRecommendations": true,
  "diffEditor.experimental.showMoves": true,
  "diffEditor.experimental.showEmptyDecorations": false,
  "github.copilot.editor.iterativeFixing": false,
  "[typescriptreact]": {
    "editor.defaultFormatter": "vscode.typescript-language-features"
  },
  "github.copilot.enable": {
    "*": true,
    "plaintext": true,
    "markdown": false,
    "scminput": false
  },
  "workbench.editor.empty.hint": "hidden",
  "python.analysis.logLevel": "Trace",
  "gitlens.blame.toggleMode": "window",
  "debug.toolBarLocation": "commandCenter",
  "scm.experimental.showSyncView": true,
  "editor.largeFileOptimizations": false,
  "ocaml.trace.server": "verbose",
  "git.suggestSmartCommit": false,
  "task.reconnection": false
}
```

**Comment by ulugbekna** [comment]
Still experience this

<img width="1141" alt="image" src="https://github.com/microsoft/vscode/assets/16353531/d30fd21f-3616-4440-9e2b-5629f1ab402c">


```
Version: 1.84.0-insider
Commit: df7d3d054020b0775fc2445c25ada7450c508524
Date: 2023-10-06T05:36:30.353Z
Electron: 25.8.4
ElectronBuildId: 24154031
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Darwin arm64 23.0.0
```

**Comment by ulugbekna** [comment]
I see it all the time, so if there're logs that I can send to you, let me know.

**Comment by Tyriar** [comment]
@ulugbekna are there exceptions in devtools console when this happens?

**Comment by ulugbekna** [comment]
> are there exceptions in devtools console when this happens?

Nope. I see this issue all the time, surprised no one else is reporting this issue. One of the unique things about my setup and fonts could be these settings: 

```
  "editor.codeLensFontFamily": "\"Jetbrains Mono\"",
  "editor.experimental.asyncTokenization": true,
  "editor.fontFamily": "JetBrains Mono, Menlo, Monaco, 'Courier New', monospace",
  "editor.fontLigatures": true,
  "editor.fontSize": 14,
```

but I had them before the bug appeared.

**Comment by klaussner** [comment]
I have the same problem. After trying out a few different settings, I think that it's related to the `"terminal.integrated.gpuAcceleration": "off"` setting. I'm not sure if it's always the case, but it looks like the issue only occurs if the terminal content changes while it's not visible, for example, if the panel is hidden or if a second terminal is opened.

**Comment by ulugbekna** [comment]
> it looks like the issue only occurs if the terminal content changes while it's not visible, for example, if the panel is hidden or if a second terminal is opened.

This matches my experience with this bug

**Comment by Delay-n-days** [comment]
I also encountered this problem

**Comment by tisilent** [comment]
I know some related information, such as DomRenderer and letterSpacing, but I cannot reproduce...

**Comment by jdneo** [comment]
Any update on this?

**Comment by nickzhums** [comment]
Hi @ulugbekna, just wondering if there's any progress on this issue. We have customers reporting this issue to us, so any updates would be highly appreciated, thanks :)

**Comment by iamakhildabral** [comment]
This is really annoying especially when you are trying to debug a issue.
Kindly take this on priority.

**Comment by ulugbekna** [comment]
I now see this bug quite rarely these days. Are you on latest vscode? If yes, I think it would make sense if you create new issues with your specific info to get better idea how to reproduce this problem.  Please, see all the things @Tyriar asked me in this issue

**Comment by iamakhildabral** [comment]
Yes I am on latest and I am seeing it on projects having log of info on console.

**Comment by ulugbekna** [comment]
Again, please create new issues with your setup info for reproducibility.

**Comment by connor4312** [comment]
I have a report of reproduction on the latest Insiders from the Java team: https://github.com/microsoft/vscode/issues/200703

**Comment by starball5** [comment]
Deja vu? #120004 had tons of duplicates on SO https://stackoverflow.com/q/66910984/11107541

**Comment by connor4312** [comment]
Verification:

1. Turn off testing.openTesting so the "test results" view is not immediately revealed when tests start. Clear all test results.
1. Open the bottom panel so the tests results view gets instantiated when it's created (but it's not rendered yet)
1. Run tests that have console output (VS Code unit tests work fine for this.) Observe terminal data getting written via logs.
1. Open the Test Results view, and see the bug

**Comment by rzhao271** [comment]
It looks like the spacing issue is still there.
I'm on the latest Insiders on Windows, and I'm running the VS Code unit tests.

![Text explorer shows text that is still weirdly spaced](https://github.com/microsoft/vscode/assets/7199958/5487c630-c3c8-4bbe-9fa0-1a2fb97e3c4a)

**Comment by connor4312** [comment]
@rzhao271 did you use different steps that those from my comment? With those I got 100% repro but I no longer do on my machines

**Comment by ulugbekna** [comment]
I also still get this problem but much more rarely than before — don’t have
a repro however

**Comment by rzhao271** [comment]
To clarify on my steps:

1. I set testing.openTesting to "neverOpen".
2. I opened the bottom panel but focused it on the terminal.
3. I ran the VS Code unit tests. I'm not sure what "Observe terminal data getting written via logs" means -- was I supposed to navigate to the output view? The terminal didn't seem to do anything during this step.
4. I navigated to the Test Results view and saw the bug.

**Comment by ulugbekna** [comment]
I get the bug in terminal with tasks running 👀

**Comment by Tyriar** [comment]
I also see a few duplicate issues, none of which have been reported since Feb.
