### ISSUE TITLE
Provide `${execPathFolder}` for variable substitution in Debugging and Task configuration files [feature request]

### ISSUE THREAD

**Issue by Diogo-Rossi** [microsoft/vscode#194143]
We already have the `${execPath}` variable (the path to the running VS Code executable). Which is great.

Could you provide a new variable `${execPathFolder}` with the path to the running VS Code executable **_folder_**?

This is used for variable substitution in Debugging and Task configuration files.

Some workaround exists, [like this one using PowerShell](https://stackoverflow.com/questions/68880358/use-portable-vscode-with-portable-powershell) but for other terminals it is not suitable.

**Comment by roblourens** [comment]
What do you want it for?

**Comment by Diogo-Rossi** [comment]
> What do you want it for?

To work with portable version of VSCode. Situation very similar to [the referenced question](https://stackoverflow.com/questions/68880358/use-portable-vscode-with-portable-powershell)

Imagine I have a custom task, with the following setting:

```json
{
    "version": "2.0.0",
    "tasks": [
        {
            [...]
            "windows": {
                [...]
                "options": {
                    "cwd": "${execPath}/../data/"
                }
                [...]
            },
            [...]
            "linux": {
                [...]
                "options": {
                    "cwd": "${execPath}/../data/"
                }
                [...]
            }
            [...]
        }
    ]
}
```

This works  on Windows because it uses CMD or PowerShell. But doesn't work on Linux because it uses bash.

The syntax `"${execPath}/../data/"` for `cwd` seems not working on bash. It expects the direct folder path.

Is there a work around?

**Comment by roblourens** [comment]
Hm, can you tell me what kind of script you want to run in the data dir? I wouldn't expect you to be touching the data inside that folder manually, since vscode manages that state.

**Comment by Diogo-Rossi** [comment]
Let's say I want to store a portable powershell inside that folder, and use it in a Linux system to use a Usb version of VSCode. How do I do that?

**Comment by roblourens** [comment]
I don't think that scripts should generally be messing with that folder. If you really want to get the path, I suppose you can extract it manually in your script, eg using `dirname`?
