### ISSUE TITLE
SCM Sync: Consider showing short diff, per commit and file

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#194137]
Testing #194016

We currently show `2 files changed, 8 insertions(+), 11 deletions(-)` only in the `All Changes` group, and nothing for commits and files:

![Image](https://github.com/microsoft/vscode/assets/22350/99aec3dd-601d-4651-b904-9e407c77609b)

I would suggest simplifying and unifying this information, showing it on all 3 levels. A short label like `+8 -11 (2)`. The user should be able to hover this label and see the full description of it.

**Comment by hbons** [comment]
`+8 -11 (2)` makes sense to me!

**Comment by lszomoru** [comment]
That makes sense to me as well. What I think we are struggling with is that:
1. Commit - on one line we have to fit commit message, author, and short diff
2. File - on one line we have to fit file name, file path, short diff and file decoration

This quite some information that we need to fit in one line so I would like for us to explore some other potential layouts (ex: maybe use two lines for commits) that enables us to include more information.

**Comment by lszomoru** [comment]
Closing this issue as now we should a statistics pill for each commit.
