### ISSUE TITLE
Git: Base branch detection should maybe prefer remote heads

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#194138]
Testing #194016

Start from `main`, on a repo:

```
git checkout -b foo
git push -u origin foo
git checkout -b bar
```

The git extension will associate `foo` as the most likely candidate for `bar`'s base. But since `foo` does have an upstream, `origin/foo`, which, at the point `bar` was created, was pointing to the same commit as `foo` itself... wouldn't `origin/foo` be a better base candidate instead?

**Comment by lszomoru** [comment]
@joaomoreno, I think that this makes sense to me however would you favour the remote branch (origin/foo) just because it points to the same commit as `for` when `bar` was created or should it be a general rule that if a remote is present, we would favour it?

**Comment by lszomoru** [comment]
Will mark this `under-discussion` and look out for additional feedback.

**Comment by lszomoru** [comment]
Though more about this and since we are adding `Fetch` and `Pull` actions to the incoming node, it does make sense for it to be an upstream branch.
