### ISSUE TITLE
[Feature Request] Auto-Update options per Extension

### ISSUE THREAD

**Issue by Stanzilla** [microsoft/vscode#194188]
I saw https://github.com/microsoft/vscode/issues/52116 and created this issue anyway because I think that issue is a) too old b) has too many other things going on.

For me, personally, I'd like a simple way to enable/disable automatic extension updates per extension. I really care about updates for many of them and want to read the changelog before I update but for some, like Copilot, who get several updates a day, I really just want to always be on the latest.

Copying section 7 from the above:

## Auto-Update options per Extension

- Users could opt-out of Auto-Update for specific extensions, with toggle button next to Disable/Uninstall in Extensions Sidebar (under gear icon menu) and next to those buttons in Extensions Detail Page.
- This could allow users to stick with previous versions before new high-risk permissions became required
- This could allow avoiding updating to problematic versions of extensions until issues are resolved.
- This could allow users to manually review/approve updates based on reviews and changelog for higher (security or reliability) risk extensions
- This could be controlled per extension without disabling globally as may be desired by default for most extensions.
- Can be set per extension to "Default" vs Auto-Update vs. Disable Automates, like with Firefox, with Default behavior controlled through global setting.
- Could provide Undo Update button or choose from version history (like with Chrome/Firefox extension stores) on extension details page, to enable rollback to previous version after an update causes issues, instead of just disabling until if/when ever fixed.

**Comment by IllusionMH** [comment]
Have you tried to select specific version for extension? This should effectively force version and prevent updates.

**Comment by Stanzilla** [comment]
> Have you tried to select specific version for extension? This should effectively force version and prevent updates.

No, would that still show if there was an update available?

**Comment by IllusionMH** [comment]
It should show.
Also September 22 update had few updates to [Extensions](https://code.visualstudio.com/updates/v1_72?ref=dailydevbytes.com#_extensions) including [Ignore updates for an extension](https://code.visualstudio.com/updates/v1_72?ref=dailydevbytes.com#_ignore-updates-for-an-extension). Check it out

**Comment by sandy081** [comment]
Supported auto updating options per extension/publisher

<img width="550" alt="image" src="https://github.com/microsoft/vscode/assets/10746682/7d193212-802c-4d37-8a7f-ca68349d1892">

This is enabled when auto update mode is disabled or set to `onlySelectedExtensions` (new config)
