### ISSUE TITLE
Emoji broken in 1.18.2, everyting OK in 1.81.1

### ISSUE THREAD

**Issue by soustruh** [microsoft/vscode#194172]
Type: <b>Bug</b>

1. Open any file in VSCode
2. Try to enter 🌈 🦄
3. Emojis show up in B/W instead of their pretty colorful versions.
4. The issues does not occur with the same user settings in previous version. I downloaded both versions as ZIP files and when I overwrite all their contents in my VSCode folder, I can switch the new broken version with the old working one back and forth. The issue also does not occur on vscode.dev.

VS Code version: Code 1.82.2 (abd2f3db4bdb28f9e95536dfa84d8479f1eb312d, 2023-09-14T05:55:25.390Z)
OS version: Windows_NT x64 10.0.19045
Modes:
Connection to 'ssh-remote+###' could not be established

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3820 CPU @ 3.60GHz (8 x 3602)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.94GB (14.64GB free)|
|Process Argv|--crash-reporter-id 3b8fa839-8e7d-4b20-8f3b-501067d01e6c|
|Screen Reader|no|
|VM|0%|

Connection to 'ssh-remote+krasty' could not be established
</details><details><summary>Extensions (20)</summary>

Extension|Author (truncated)|Version
---|---|---
xml|Dot|2.5.1
font-switcher|eva|4.1.0
beautify|Hoo|1.5.0
vscode-autohotkey-plus-plus|mar|5.0.3
isort|ms-|2023.10.1
mypy-type-checker|ms-|2023.2.0
python|ms-|2023.16.0
vscode-pylance|ms-|2023.9.20
jupyter|ms-|2023.8.1002501831
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.17
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-slideshow|ms-|0.1.5
remote-ssh|ms-|0.106.4
remote-explorer|ms-|0.4.1
autodocstring|njp|0.6.1
rewrap|stk|1.16.3
sort-lines|Tyr|1.10.2
errorlens|use|3.14.0
markdown-all-in-one|yzh|3.5.1

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
py29gd2263cf:30792227
vscaat:30438848
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
282f8724:30602487
f6dab269:30613381
showlangstatbar:30737416
0bi6i642:30841073
03d35959:30757346
pythonfmttext:30731395
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
pythonnosmt12:30797651
pythonidxptcf:30805731
pythonnoceb:30805159
copilotsettingt:30839829
dsvsc013:30795093
dsvsc014:30804076
diffeditorv2:30821572
dsvsc015:30845448

```

</details>

![obrazek](https://github.com/microsoft/vscode/assets/3732416/aae4005b-a826-465d-ab1b-76206dfa8b4e)

**Comment by soustruh** [comment]
Hi guys, any progress on this one please? 🙏 Is this an intended behavior?

**Comment by miguelfito** [comment]
Hey @soustruh, I had a similar problem on issue https://github.com/microsoft/vscode/issues/198124 and seems to be a font cache issue.

It's true I'm running VS Code on Fedora Linux and I don't have any idea how Windows manages font cache, but it could be a good clue to take a look on that way...

**Comment by soustruh** [comment]
OK guys, sorry I took to long to comment on this, I found the cause of the issue: I had multiple versions of the same font installed in my Windows system. It was enough to remove one of the font versions and restart VSCode. Strangely enough the problem was somehow connected to certain VSCode version, but as it is not caused by VSCode, I think we can safely consider this one as closed.
