### ISSUE TITLE
[WelcomeUX] Contrast is low in light theme

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#19419]
Suggest to make the background even more dimmed so that the foreground has more contrast:

![image](https://cloud.githubusercontent.com/assets/900690/22324925/04b45308-e3ac-11e6-9b6f-5a6e67fa1ac1.png)

**Comment by chrmarti** [comment]
#19051 is asking for the opposite.

**Comment by chrmarti** [comment]
The problem here is that the sidebar isn't dimmed.

**Comment by chrmarti** [comment]
Updating to:

![screen shot 2017-02-21 at 3 40 51 pm](https://cloud.githubusercontent.com/assets/9205389/23190355/3123101e-f84c-11e6-9b0f-017de39d7209.png)

![screen shot 2017-02-21 at 3 42 59 pm](https://cloud.githubusercontent.com/assets/9205389/23190402/77cf541e-f84c-11e6-82a8-04bed516bdc3.png)
