### ISSUE TITLE
Inline notebook hint to use AI too distracting in notebooks

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#194114]
Testing #194053

1. F1 > Create New Jupyter Notebook
2. Notice what I see (image below). There is only one line visible and it is covered by the hint, the notebook does not have focus. 
3. I do not have any space where I can click just to pass focus inside the notebook to start typing 🐛  If I click below, the focus is passed to this weird mini status bar (image 2)

imho this is a ux bug. The point of the hint is not to be in your way. It works better in the regular VS Code editor because there are more lines visible. If there is only one line, it is very much in user's face.

![Screenshot 2023-09-26 at 12 06 10](https://github.com/microsoft/vscode/assets/1926584/26162fe0-7cbd-42b2-b089-7ff58f9cae00)

![Screenshot 2023-09-26 at 12 08 51](https://github.com/microsoft/vscode/assets/1926584/310a7d5e-a9c9-4e5d-9db4-57bd92829543)

fyi @amunger @joyceerhl

**Comment by rebornix** [comment]
Makes good sense to me. I pushed a change to disable this for Stable first. I'd like to provide a non-clickable editor hint in empty cell once the main is open for business/Insiders again.

**Comment by rebornix** [comment]
We disabled mouse clicking now

<img width="1187" alt="image" src="https://github.com/microsoft/vscode/assets/876920/c62f5961-cd3d-4118-84f7-0238608d767e">
