### ISSUE TITLE
No prompt to install Dwarf extension

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#194144]
Testing #194071

I followed steps from https://github.com/microsoft/vscode/issues/194071
And got into .wasm files but no prompt appeared to install the Dwarf extension 🐛 

![Screenshot 2023-09-26 at 15 45 24](https://github.com/microsoft/vscode/assets/1926584/886d2393-b9eb-4972-87c5-2c2aaf239544)

**Comment by connor4312** [comment]
@isidorn I realized I forgot to add the usual instructions to install [js-debug nightly](https://github.com/microsoft/vscode-js-debug#nightly-extension) to the TPI. Are you on that version of the extension?

**Comment by joyceerhl** [comment]
I was on nightly and did not have stable, still didn't see a prompt to install

**Comment by connor4312** [comment]
This is how I'm getting into the WAT file -- are you doing something different? (Note that you'd need to uninstall the DWARF extension in order for the prompt to appear again)


https://github.com/microsoft/vscode/assets/2230985/cd35f83d-5b2d-42ac-8f08-570589de70f2

**Comment by joyceerhl** [comment]
OK I get the notification now, though I had the extension installed and disabled

<img width="437" alt="image" src="https://github.com/microsoft/vscode/assets/30305945/0c0601b4-8f83-4a83-8fa8-df2b0ed33f7d">
