### ISSUE TITLE
VSCode 1.8.1 ships with insecure node.dll 6.5.0

### ISSUE THREAD

**Issue by iki** [Microsoft/vscode#19410]
- VSCode Version: Code 1.8.1 (ee428b0eead68bf0fb99ab5fdc4439be227b6281, 2016-12-19T14:49:23.350Z)
- OS Version: Windows_NT ia32 6.2.9200
---

Steps to Reproduce:

1. Install VSCode 1.8.1.
2. Check version of `C:\Program Files (x86)\Microsoft VS Code\node.dll`.

See https://nodejs.org/en/blog/release/v6.9.0/

It also causes reports in desktop vulnerability scanners like Secunia PSI. https://secunia.com/vulnerability_scanning/personal/

**Comment by mousetraps** [comment]
Thanks for reporting! We'll look into it. @Microsoft/vscode

**Comment by bpasero** [comment]
Let's continue in the already reported https://github.com/Microsoft/vscode/issues/13619
