### ISSUE TITLE
notebook.scrolling.revealCellBehavior jumps back to original cell

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode#194161]
Version: 1.83.0-insider
Commit: 8ecf5453e8e8f98cca0f9a661d3a6457d8a0e703
Date: 2023-09-26T05:34:22.077Z
Electron: 25.8.2
ElectronBuildId: 23977753
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Linux x64 5.14.0-1048-oem

Also tested on the Mac

Testing #194069

- create a cell contains the following content
```
import time
for i in range(20):
    time.sleep(.5)
    print(i)
````
- add a cell behind it
- set "notebook.scrolling.revealCellBehavior": "first"
- run cell with `shift + enter`
- the cell behind it is revealed (first line, as configured✅ )
- but shortly after the editor scroll back to the first cell with the output

Revealing the next cell but jumping back doesn't make much sense. Not sure what's the user expectation of Shift+Enter.

Should revealing to the next cell wait for the evaluation to complete? Or should output never be revealed?

![Image](https://github.com/microsoft/vscode/assets/6461412/49c99acd-5c22-4ba5-a485-be7ec9e93118)

Interestingly, with `"notebook.scrolling.revealCellBehavior": "fullCell"` the no revealing of output happens

**Comment by amunger** [comment]
this looks like https://github.com/microsoft/vscode/issues/193231
the current context based scrolling in default can behave pretty strangly
