### ISSUE TITLE
Go to prev/next commands keybindings are not working in terminal

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#194104]
Testing #193852

![Image](https://github.com/microsoft/vscode/assets/10746682/9a4a42e4-2e12-4577-b8b2-7a43819299ca)

Option + Down/Up arrow in terminal is not navigating between commands. These are working only in accessibility view. In terminal the keybindings are cmd + Down/Up arrow.

**Comment by bamurtaugh** [comment]
I'm experiencing the same issue testing on Windows 11.

**Comment by meganrogge** [comment]
This text should say in the accessible view - the keybinding is meant to work there, not in the terminal.

**Comment by justschen** [comment]
same issue! All the other commands work fine, arrows/screen reader work fine in the quick pick after command is run.

**Comment by meganrogge** [comment]
Everyone, the prev/next commands must be run in the terminal's accessible view - not the terminal. Can you pls test that? I plan to make that clear by tweaking the dialog's text.

**Comment by bamurtaugh** [comment]
Yes, it worked in the accessibility view for me (as it sounds like it did for @sandy081 too).

**Comment by justschen** [comment]
Worked fine for me too! Sorry for the mixup

**Comment by meganrogge** [comment]
Thanks 👍🏼 definitely see why you were confused though, so will fix that

**Comment by meganrogge** [comment]
to verify, open the accessibility help dialog by focusing a terminal and using `alt+f1`. verify that the `next/previous commands` specify that they're to be applied in the terminal accessible view.
