### ISSUE TITLE
Allow opening OS finder at sync download location

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#194165]
https://github.com/microsoft/vscode/issues/192271

Repro:

1. Run command `Developer: Download Settings Sync Activity`

I get this notification, but then I had to manually open Windows Explorer and find the folder I selected:

![Image](https://github.com/microsoft/vscode/assets/2193314/d32fc5bd-737e-478b-b827-575af6e89f06)

**Comment by sandy081** [comment]
Added **Open Folder** command only for desktop
