### ISSUE TITLE
Keyboard stops working after holding a key down in an editor

### ISSUE THREAD

**Issue by soulplant** [Microsoft/vscode#19418]
- VSCode Version: Code 1.8.1 (ee428b0eead68bf0fb99ab5fdc4439be227b6281, 2016-12-19T14:42:49.304Z)
- OS Version: Darwin x64 15.6.0
- Extensions:

|Extension|Author|Version|
|---|---|---|
|dart-code|DanTup|0.14.9|
|fish|TeddyDD|0.0.4|
|Bookmarks|alefragnani|0.10.2|
|project-manager|alefragnani|0.13.0|
|python|donjayamanne|0.5.6|
|flow-for-vscode|flowtype|0.4.0|
|Go|lukehoban|0.6.52|
|java|redhat|0.0.9|
|vscode-icons|robertohuertasm|7.1.2|
|Material-theme|zhuangtongfa|1.0.3|

---

Steps to Reproduce:

1. Open a new vs code window.
2. With the focus in an editor, hold the 'j' key down (or any letter).

Expected: To see multiple 'j's
Actual: Window stops responding to any key presses that don't have a meta-key held down as well (e.g. command-z still works)

**Comment by mousetraps** [comment]
Oh no! Unfortunately I can't reproduce on my machine, so we're going to need your help to narrow it down. A few Qs:
* does the issue still occur when you run VS Code w/ extensions disabled? from the command line: `code --disable-extensions`
* just to clarify, when you say command-z works, you mean holding down command-z?
* when the window stops responding, do keypresses outside of the editor still work? (e.g. in the terminal or find window?)
* do you see a cpu spike while holding down the key or when the keyboard stops responding?

**Comment by rebornix** [comment]
@abist does this link https://github.com/VSCodeVim/Vim#j-k-and-others-dont-repeat-when-i-hold-them-down help you out with the problem?

**Comment by soulplant** [comment]
Thanks so much for the prompt reply! Unfortunately it looks like I can't repro this any more.

Last night I could trigger this behaviour consistently by opening a new window and performing the steps I outlined above. This morning I awoke to the spinning beach ball on VS Code, so I force quit it and now observe that holding down keys produces no ill-effects.

Some more context in case this surfaces again:

- When I said command-z works, I meant that if I hold command and press z then an undo is performed. I was able to fix the state when I was in this condition by pressing command+shift+p to bring up the command palette and then doing command+v to paste the text "reload window" into it, then pressing enter.

- When the editor stopped responding keystrokes the command palette and in terminals also stopped responding (I didn't specifically try the find window). In fact, I first noticed this when I was using vim in the terminal, and I was holding down 'j' to go down, which triggered the freeze.

- I didn't notice any CPU spike while the problem was occurring, though earlier I had noticed the flow process going crazy with the CPU for no apparent reason, so I killed it. Perhaps this put me into a weird state?

@rebornix Thanks for the tip! This is a relatively new machine and I'd forgotten about those settings.

While I'm here, I'd just like to say thanks for vs code! As a long-time vim lover (even to the point of writing my own vim clone and using it to hack for years) vs code successfully brought me into the modern world where all other modern text editors failed. Can't wait to see where you all take the project :)

**Comment by alexandrudima** [comment]
Given input was not reaching the command palette, nor the terminal, I believe this is some sort of Electron/Chromium issue: the input did not reach the renderer process at all.

If you find some reproducible steps, we should let Electron / Chromium know about it.
