### ISSUE TITLE
Have an icon for DWARF extension

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#194145]
Testing #194071

https://marketplace.visualstudio.com/items?itemName=ms-vscode.wasm-dwarf-debugging

Maybe @hbons could help?

**Comment by connor4312** [comment]
Used this for now:


![Screenshot 2023-09-26 at 12 43 38 PM](https://github.com/microsoft/vscode/assets/2230985/0cbd3f15-8d16-4df6-88ca-d8705fc2230f)
