### ISSUE TITLE
Cursor is black in dark theme

### ISSUE THREAD

**Issue by abist** [Microsoft/vscode#19416]
- VSCode Version: 1.8.1
- OS Version: Windows 10 Enterprise

This happens when you remote into Windows 10 from Mac OS. The cursor is black in color in the dark theme which makes it really hard to see where it is.

**Comment by mousetraps** [comment]
Oh no! That's no good. Unfortunately I can't seem to reproduce the issue on my machine. A few Qs to help narrow it down:
* Does the issue still occur when you launch VS Code w/ extensions disabled? From the command line: `code --disable-extensions`
* Is this the `Dark` or `Dark+` theme?
* Does the same issue occur on other themes?

**Comment by rebornix** [comment]
@abist does this link https://github.com/VSCodeVim/Vim#j-k-and-others-dont-repeat-when-i-hold-them-down help you out with the problem?

**Comment by alexandrudima** [comment]
@abist This most likely sounds like an issue with the remote desktoping software you use.

When you run other software in the Windows 10 machine you remote into, do you experience the same issue?

**Comment by abist** [comment]
Actually you're right! It seems to be a bug in Microsoft Remote Desktop.
