### ISSUE TITLE
Icon options are not keyboard accessible

### ISSUE THREAD

**Issue by lramos15** [microsoft/vscode#194179]
Testing #194038

This may be because hover is used in the background, but I can open the picker using the keyboard but then I cannot select an icon using the keyboard.

**Comment by sandy081** [comment]
It is working for me. 

https://github.com/microsoft/vscode/assets/10746682/6383826f-42b2-4e32-a747-5001d340faff

Can you please let me know if you are trying to do differently?

**Comment by lramos15** [comment]
Ah I was using tab. I guess things are more accessible than I thought. Some issues I still see
1. Do search such as `e` now you can only use the up and down arrows to cycle because left and right are tied to the input box
2. Hit tab, you've now exited the hover and there is no way to get back in.

**Comment by sandy081** [comment]
> Do search such as e now you can only use the up and down arrows to cycle because left and right are tied to the input box

https://github.com/microsoft/vscode/issues/194217

> Hit tab, you've now exited the hover and there is no way to get back in.

Will be fixed by this - https://github.com/microsoft/vscode/issues/194094
