### ISSUE TITLE
Issue installing extensions behind authenticated proxy

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#1942]
From @FloMaetschke:

I have set http.proxy, https.proxy and http.proxyStrictSSL = false,

I want to install extensions:
CTRL + P: enter: > inst .. wait a moment, select "Extensions: Install Extensions".

With the latest decembe release: I get a blue loading bar after a few seconds it says: 
"ERROR Unable to verify the first certificate"

With your first build you posted here: 
https://github.com/Microsoft/vscode/issues/155#issuecomment-169963541

I just get an endless loading bar and nothing happens.

With your second build you posted here:
https://github.com/Microsoft/vscode/issues/155#issuecomment-170519605

I just happens nothing, it instantly closes the prompt without any result.

Any idea?

UPDATE:

I have had a look into the developer console.
With both of your builds, vs code tries to load the extensions stuff. But our enterprise proxy returns 
a 
```
  Access Denied (authentication_failed)

  Your credentials could not be authenticated: "Credentials are missing.". You will not be permitted    access until your credentials can be verified.

  This is typically caused by an incorrect username and/or password.
```
My settings.json looks like this:

```
// Place your settings in this file to overwrite default and user settings.
{
     	//-------- HTTP configuration --------

	// The proxy setting to use. If not set will be taken from the http_proxy and https_proxy environment variables
	"http.proxy": "http://myusername:mypassword@123.123.123.123:8080",
	"https.proxy": "http://myusername:mypassword@123.123.123.123:8080",

	// Whether the proxy server certificate should be verified against the list of supplied CAs.
	"http.proxyStrictSSL": false,
}
```

The thing is, i am acutally using the same source of the http.proxy value in my git, npm and bower proxy config. I Also set this up for HTTP_PROXY and HTTPS_PROXY. Thats where i copy/pasted it from. And well, it just works fine there.

**Comment by joaomoreno** [comment]
First: we don't have the setting `https.proxy`. Only `http.proxy`, that will be enough. Also, make sure `http.proxyStrictSSL` stays `false`.

It won't probably fix the whole issue but please try out [this build](https://ticino.blob.core.windows.net/build/20ff90c932596961c710ae7d0441705694e2b0a9/VSCode-win32.zip?st=2016-01-11T08%3A46%3A00Z&se=2016-01-18T08%3A46%3A00Z&sp=r&sv=2015-02-21&sr=b&sig=i0EWsjejoKGWGrQdKkA9TLH%2Fm7b5XC9wO7EBuXIaZEc%3D). Let me know if you still see the `ERROR Unable to verify the first certificate`.

**Comment by FloMaetschke** [comment]
I dont see anything. I just get an error logged in console: showing

Your credentials could not be authenticated: "Credentials are missing.". You will not be permitted access until your credentials can be verified.
<BR>
This is typically caused by an incorrect username and/or password.

But username/password is correct.

To verfiy this, i also tried it with fiddler2 using proxy auto authentication and using fiddler localhost proxy as proxy. same result. using chrome or any other app, it works fine.

**Comment by joaomoreno** [comment]
Alright, give [this one](https://ticino.blob.core.windows.net/build/17682edf40b43a84ac798bff2952cb6821c95e44/VSCode-win32.zip?st=2016-01-11T16%3A09%3A00Z&se=2016-01-18T16%3A09%3A00Z&sp=r&sv=2015-02-21&sr=b&sig=NwmjNC1YW7BfAg6zOEE5sfLH5GIeuxQgOD8BgyOqiJU%3D) a try.

**Comment by FloMaetschke** [comment]
It works! I got a list of extensions now. (Yeah! ;) )
But the installation still fails with: unable to verify the first certificate: Error: unable to verify the first certificate,    at Error (native),    at TLSSocket.<anonymous> (_tls_wrap.js:1000:38),    at emitNone (events.js:67:13),    at TLSSocket.emit (events.js:166:7),    at TLSSocket._finishInit (_tls_wrap.js:567:8)

But its going in the right direction. Thx man, would be nice to try the next build for you.

**Comment by joaomoreno** [comment]
Excellent, one step closer. Wanna try [this one](https://ticino.blob.core.windows.net/build/0e17d138ca2e7f5a342e049836a2b2b0beb54685/VSCode-win32.zip?st=2016-01-12T14%3A43%3A00Z&se=2016-01-19T14%3A43%3A00Z&sp=r&sv=2015-02-21&sr=b&sig=8F9%2BNvY94xaMZKEtGfXDc4QEXH%2Fn26dXs1%2BnMIqjHm8%3D)?

**Comment by FloMaetschke** [comment]
I have just installed the angular.js snippets extensions.
Thank you very much! It's working now.

**Comment by joaomoreno** [comment]
:fireworks: Official fix will come with the next release!
