### ISSUE TITLE
Excluded files still available in peek definition

### ISSUE THREAD

**Issue by zeleniy** [microsoft/vscode#194299]
Version: 1.82.2 (Universal)
Commit: abd2f3db4bdb28f9e95536dfa84d8479f1eb312d
Date: 2023-09-14T05:59:47.790Z
Electron: 25.8.1
ElectronBuildId: 23779380
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Darwin x64 17.7.0

![Screen_Shot_2023-09-27_at_12_06_03](https://github.com/microsoft/vscode/assets/2780617/11478209-13f3-4748-941c-13806d8132d1)

**Comment by mjbvz** [comment]
Thanks @gjsjohnmurray

@zeleniy Please file this issue against your php extension. However `search.exclude` may not be right setting for controlling `go to definition`
