### ISSUE TITLE
codicon shown in filtered go to symbol view

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#194215]
Testing #194053

1. In a notebook with one python cell:

```py
myvar = 3
```

2. open `go to symbol` and type `s`

**Bug**

![Image](https://github.com/microsoft/vscode/assets/12821956/7d2aa7e6-cec4-4310-8847-f80e9e9d2889)

**Comment by amunger** [comment]
I had copied from the [text document goto symbols implementation](https://github.com/microsoft/vscode/blob/main/src/vs/editor/contrib/quickAccess/browser/gotoSymbolQuickAccess.ts#L255-L257), but that's doing it's own filtering, so it can keep track of what part of the label to use for sorting/filtering.

Also curious about @jrieken's comment [here](https://github.com/microsoft/vscode/blob/main/src/vs/workbench/contrib/notebook/browser/contrib/outline/notebookOutline.ts#L165-L172) about codicons not working with icon classes. That makes it sound like this will be tough to fix
