### ISSUE TITLE
Different colour icon for different types of breakpoint

### ISSUE THREAD

**Issue by PraneshBalasubramaniam** [microsoft/vscode#194206]
### display different types of breakpoints with different colour like in chrome dev tools

Hi, when creating normal breakpoints, conditional breakpoints and logpoint , we couldn't identify the difference easily, so it would be much better to have different color for each type like in chrome dev tools

**Comment by roblourens** [comment]
We do have different shapes, I know they are subtle, but I don't think we plan to change the colors as well
