### ISSUE TITLE
Pick a forever theme color for the quick fix highlight and allow styling both background and borders

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#194225]
Testing #194072

We cover bg and border for the majority of highlights, for example:

```
		"editor.lineHighlightBorder": "#263040",
		"editor.rangeHighlightBackground": "#ffffff0d",
		"editor.selectionBackground": "#399ef440",
		"editor.selectionHighlightBackground": "#399ef420",
		"editor.wordHighlightBackground": "#00000000",
		"editor.wordHighlightBorder": "#399ef4",
		"editor.wordHighlightStrongBackground": "#00000000",
		"editor.wordHighlightStrongBorder": "#399ef4",
```

We should look into whether one of those is suitable and use that, or make our own and choose a good base to derive from. Provided there's no conflicts, I'll likely make my theme use the bright accent border I use for word highlight:

![Image](https://github.com/microsoft/vscode/assets/2193314/35031ff8-8c85-4f90-98de-4e90f42a131d)

We want to make sure that it behaves correctly when there is for example find in files, find in the current file, etc. already active.

**Comment by justschen** [comment]
example here (since i'm using 'editor.findMatchHighlightBackground` with no changes):

![Screenshot 2023-10-03 at 10 38 04 AM](https://github.com/microsoft/vscode/assets/54879025/95e943dc-9535-4d76-9200-c983db671d07)

**Comment by justschen** [comment]
will be addressed as part of https://github.com/microsoft/vscode/issues/199608
