### ISSUE TITLE
Extension magically got reenabled

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#194265]
* I have rust-analyzer installed but disabled
* It's now enabled without me doing something
* I blame it on settings sync because yesterday I reenabled that and I have onboarded a bunch of clients (vscode.dev, separate mac, etc)

## Steps to Repro

- Open VS Code
- Install an extension A and disable it
- Install older version of the extension using `Install Another Version...` action
- Open VS Code using different user data directory but same extensions directory - `code --user-data-dir <folder>`
- Update the extension from this instance
🐛 Extension is enabled in other instance

Note that this is nothing to do with Settings Sync

**Comment by bhavyaus** [comment]
verified that the extension in the old version stays disabled.
