### ISSUE TITLE
Inlay hints do not show when using Workspace TypeScript version

### ISSUE THREAD

**Issue by adam-smith-23** [microsoft/vscode#194279]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.82.2
- OS Version: macOS 13.5.2

Steps to Reproduce:

1. Have a `.vscode/settings.json` with 
```json
{
    "typescript.tsdk": "node_modules/typescript/lib",
}
``` 
2. Command Palette -> 'TypeScript: Select TypeScript Version'. Choose between workspace + default VS code version

When default TS version is selected (5.2.2):
<img width="289" alt="image" src="https://github.com/microsoft/vscode/assets/146182459/3e180137-9c48-4546-b507-cfa4bae1bc16">

When workspace TS is selected (4.0.8):
<img width="265" alt="image" src="https://github.com/microsoft/vscode/assets/146182459/904e56bf-8373-4d66-8929-3b547c099194">

However, TS definitely knows what type it is, since when I hover over, it displays the type correctly:
<img width="258" alt="image" src="https://github.com/microsoft/vscode/assets/146182459/5857d8d9-8d95-48ed-aeea-a148ca8b46d3">

**Comment by mjbvz** [comment]
That version doesn't support inline hints, they were added in 4.4
