### ISSUE TITLE
Chat view not active after reload

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#194280]
continues https://github.com/microsoft/vscode/issues/185179 - it's less severe but equally annoying

* move chat view to secondary sidebar
* interact with it
* reload window
* the chat view isn't active, it needs another click

**Comment by jrieken** [comment]
https://github.com/microsoft/vscode/assets/1794099/566a038e-9574-49be-a5cf-c6776a8d586b

**Comment by sbatten** [comment]
fixed with @joyceerhl changes
