### ISSUE TITLE
Unable to deny Built-in Port Forwarding

### ISSUE THREAD

**Issue by nilesh-ava** [microsoft/vscode#194219]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.82.2
- OS Version: Windows 11 22H2 

Issue: [Release notes](https://code.visualstudio.com/updates/v1_82) specify the new "Built-in port forwarding" feature that allows users to forward port from within VS Code and make it available publicly. 
The [documentation](https://code.visualstudio.com/docs/editor/port-forwarding) specifies that we can allow/deny access to domain `global.rel.tunnels.api.visualstudio.com` to be able to control this feature. 
During our testing it seems the feature still works even after we denied the domain `global.rel.tunnels.api.visualstudio.com` on our enterprise DNS secure gateway Cisco Umbrella. 

Steps to Reproduce:

1. Denied domain `global.rel.tunnels.api.visualstudio.com` through our enterprise DNS secure gateway Cisco Umbrella. 
2. Validated that the domain `global.rel.tunnels.api.visualstudio.com` is blocked by trying to browse to it - shows the blocked message from opendns. 
3. Tried steps to 'Forward a Port' and it still allows the user to forward port.

**Comment by connor4312** [comment]
If users already signed into and set up local forwarding, that 'global' domain will no longer be hit. You can block all regional domains with the pattern `*.rel.tunnels.api.visualstudio.com`
