### ISSUE TITLE
Keyboard Shortcuts

### ISSUE THREAD

**Issue by Samyak-Bumb** [microsoft/vscode#194204]
1. **Customization**: Many users customize their shortcuts to streamline their workflow, making it more efficient. However, this customization can lead to confusion when they refer to the official VS Code shortcuts PDF.
2. **Productivity**: By incorporating a **button in the keyboard settings that allows users to export their customized shortcuts**, you're empowering them to maintain a copy of their personalized shortcuts easily. This feature will significantly enhance their productivity and workflow efficiency.

Thank You

**Comment by IllusionMH** [comment]
Not sure what expected action items here are.
1. If you change Shortcuts they may be different from defaults (and PDF). What's the problem here?
2. Shortcuts can be synced using settings sync already. Alternatively you have actions to open `keybindings.json` file and copy it if you need to share in other way.

**Comment by Samyak-Bumb** [comment]
> Not sure what expected action items here are.
> 
> 1. If you change Shortcuts they may be different from defaults (and PDF). What's the problem here?
> 2. Shortcuts can be synced using settings sync already. Alternatively you have actions to open `keybindings.json` file and copy it if you need to share in other way.

Now see, You've modified some shortcuts in Visual Studio Code, and it's challenging to remember them. You noticed that the official PDF documentation has different shortcuts (which you have Modified), and you'd like to create a custom printable PDF of your modified shortcuts to make them more accessible and easy to remember. You're not looking for sync functionality, just a way to have your personalized shortcuts in a printable and convenient format.

My simple question is why did vscode created a pdf for shortcuts? I think your answer will be easy, to access the shortcuts.

**Comment by IllusionMH** [comment]
So second point in OP about

> export their customized shortcuts,

is to get PDF and reuse shortcuts?

**Comment by Samyak-Bumb** [comment]
> So second point in OP about
> 
> > export their customized shortcuts,
> 
> is to get PDF and reuse shortcuts?

I apologize, could you please provide a more detailed explanation of what you're trying to convey?

**Comment by IllusionMH** [comment]
I'm trying to understand what's your feature requests actually is.

References to "export" doesn't sound like Print to PDF on first glance. Second item in your original post looks like a way to move/share changes, not to just print them.

**Comment by ulugbekna** [comment]
> Customization: Many users customize their shortcuts to streamline their workflow, making it more efficient. However, this customization can lead to confusion when they refer to the official VS Code shortcuts PDF.

You can view your keyboard shortcuts by invoking the command "Preferences: Open Keyboard Shortcuts". You can search by command or keyboard shortcut. 

> Productivity: By incorporating a button in the keyboard settings that allows users to export their customized shortcuts, you're empowering them to maintain a copy of their personalized shortcuts easily. This feature will significantly enhance their productivity and workflow efficiency.

You keyboard shortcuts are already copy-pasteable from keybindings.json file that you can open by invoking command "Preferences: Open Keyboard Shortcuts (JSON)"

**Comment by Samyak-Bumb** [comment]
> > Customization: Many users customize their shortcuts to streamline their workflow, making it more efficient. However, this customization can lead to confusion when they refer to the official VS Code shortcuts PDF.
> 
> You can view your keyboard shortcuts by invoking the command "Preferences: Open Keyboard Shortcuts". You can search by command or keyboard shortcut.
> 
> > Productivity: By incorporating a button in the keyboard settings that allows users to export their customized shortcuts, you're empowering them to maintain a copy of their personalized shortcuts easily. This feature will significantly enhance their productivity and workflow efficiency.
> 
> You keyboard shortcuts are already copy-pasteable from keybindings.json file that you can open by invoking command "Preferences: Open Keyboard Shortcuts (JSON)"

I wanted to suggest a convenient option, so I submitted this feature request instead of opting for a more complex approach.
And, I know I can search in Keyboard Shortcuts type or find the name of function & then see the shortcut and close it, this is too long & reduce productivity of developer's

**Comment by Samyak-Bumb** [comment]
@ulugbekna Hello, plz work on this cuz I have a lot of shortcuts changed & I've to find it in keyboard shortcuts that's way more hard, plz I want a Handy option
Plz reopen it & work plz
