### ISSUE TITLE
Settings editor should allow custom input without needing all default values specified

### ISSUE THREAD

**Issue by lramos15** [microsoft/vscode#194220]
Testing #194031

For `editor.codeActionsOnSave` I must have values defined for both the predefined keys before I can enter custom keys. It would be nice if I was able to type in something here without needing to define the defaults.

It's similarily confusing that the custom entries allow me to specify arbitrary key values when the values themselves must be of an expected type. I wonder if there is a way to get a list of all possible code actions so the dropdown just contains every possible code action id @justschen

**Comment by justschen** [comment]
partly related to https://github.com/microsoft/vscode/issues/161284

looking into allowing typing in the table + not having to select predefined keys first
