### ISSUE TITLE
Only the nearest problem is considered with quick fixes

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#194222]
Testing #194072

I was expecting quick fixes for the whole line to be included, ranked by distance to the cursor, up to a certain maximum

![Image](https://github.com/microsoft/vscode/assets/2193314/c766bf69-f683-4ee4-88c5-cb74a471551b)

**Comment by justschen** [comment]
Yep! That was one thing I was experimenting with, and atm it does just find the closest one. 

Played around with allowing all quickfixes as well, but was unsure what would feel better. Will likely work on a version where we show all potential quickfixes in the line.
