### ISSUE TITLE
[web][ff] web socket breaks when changing network

### ISSUE THREAD

**Issue by akosyakov** [microsoft/vscode#194284]
At Gitpod we received bug requests that in FireFox (117-118) VS Code Web (1.82) sometimes became unresponsive. See [Loom](https://www.loom.com/share/c028fe3b10814f5f90b00255625eaac6?sid=5aa5fdaa-1d65-4581-bc45-5a1153dcafda) for what unresponsive means.

It is hard to reproduce, but I was able with following:

1. Leave FF tab in the background.
2. Trigger reconnects by toggling your wifi for instance.
3. After a while come back to FF tab.

Debugging web part showed that frontend is keep asking to replay missing messages, but server keeps replaying with the same message. Unfortunately I was not able to debug the server part.

**Comment by akosyakov** [comment]
It is wort to mention that we observed this issue also without reconnection as well. Would maybe make sense to cycle a web socket if after replay the first replayed message don't satisfy this criteria: https://github.com/microsoft/vscode/blob/d532fad7425a5f2e17d321ee7a3c074595d093b7/src/vs/base/parts/ipc/common/ipc.net.ts#L1003 Otherwise it goes to loop forever?

**Comment by akosyakov** [comment]
I was able to reproduce it reliably with VS Code Server from sources by toggling VPN exit nodes. I've enabled server side diagnostics and noticed that server gets `read` and `webSocketNodeSocketReadData` events after toggling, but there are not more `protocolHeaderRead` and `protocolMessageRead` diagnostic traces. This loop does not seem to hit: https://github.com/microsoft/vscode/blob/63b61dc2a71f5763483d7f17da5f1c03e57aba43/src/vs/base/parts/ipc/common/ipc.net.ts#L363

cc @alexdima does it ring any bell? Would it help if i share such traces?

**Comment by akosyakov** [comment]
Here are traces one from Chrome and another from FireFox with the same test. You can see that at the end of FF log there are no anymore tracing for `protocolHeaderRead` and `protocolMessageRead`. (just a note I disabled compression while testing it here but it did not change results)

[server.chrome.log](https://github.com/microsoft/vscode/files/12748119/server.chrome.log)
[server.ff.log](https://github.com/microsoft/vscode/files/12748118/server.ff.log)

**Comment by akosyakov** [comment]
I've tested a workaround that effectively resolves the issue; you can view the changes in our fork [[1](https://github.com/gitpod-io/openvscode-server/commit/d1d1be7b45a771c8705899badfae2ef5133e754b)]. Should I send a pull request?

I've also filed a bug report for Firefox: [1855692](https://bugzilla.mozilla.org/show_bug.cgi?id=1855692).

**Comment by alexdima** [comment]
Hmm, it's possible Firefox is sending a control opcode that we don't handle well https://datatracker.ietf.org/doc/html/rfc6455#section-5.2

**Comment by alexdima** [comment]
@akosyakov If you still have an easy repro, could you perhaps log the opcode:

```diff
diff --git a/src/vs/base/parts/ipc/node/ipc.net.ts b/src/vs/base/parts/ipc/node/ipc.net.ts
index ed30467961b..e1f14c2361a 100644
--- a/src/vs/base/parts/ipc/node/ipc.net.ts
+++ b/src/vs/base/parts/ipc/node/ipc.net.ts
@@ -390,6 +390,8 @@ export class WebSocketNodeSocket extends Disposable implements ISocket, ISocketT
                                const firstByte = peekHeader.readUInt8(0);
                                const finBit = (firstByte & 0b10000000) >>> 7;
                                const rsv1Bit = (firstByte & 0b01000000) >>> 6;
+                               const opcode = (firstByte & 0b00001111);
+                               console.log(`opcode: ${opcode}`);
                                const secondByte = peekHeader.readUInt8(1);
                                const hasMask = (secondByte & 0b10000000) >>> 7;
                                const len = (secondByte & 0b01111111);
```

**Comment by akosyakov** [comment]
@alexdima here is output:
<img width="729" alt="Screenshot 2023-09-28 at 15 54 22" src="https://github.com/microsoft/vscode/assets/3082655/da60a8fb-169b-48fa-915d-a9439b947922">

**Comment by jeanp413** [comment]
Created a PR fixing it https://github.com/microsoft/vscode/pull/194436 cc @alexdima

**Comment by akosyakov** [comment]
Thank you both! I confirm that handling ping control code resolves the issue. @alexdima I verified that @jeanp413's PR work both with Chrome and FireFox.

**Comment by alexdima** [comment]
Thank you! ❤️

**Comment by TylerLeonhardt** [comment]
Marking as verified due to @akosyakov's confirmation.
