### ISSUE TITLE
elf_dynamic_array_reader.h(64) tag not found

### ISSUE THREAD

**Issue by NelDav** [microsoft/vscode#194272]
Does this issue occur when all extensions are disabled?: Yes

__VS Code Version:__
1.82.0
8b617bd08fd9e3fc94d14adb8d358b56e3f72314
x64

__OS Version:__
* Kernel: 6.1.53-1-MANJARO
* arch: x86_64
* bits: 64
* Desktop: sway
* v: 1.8.1
* Distro: Manjaro Linux

Steps to Reproduce:

When running `code`, a Warning is generated:

```
Warning: 'ozone-platform-hint' is not in the list of known options, but still passed to Electron/Chromium.
```

When running `code --verbose` in a terminal I get the following error and code crashes.

```
[17102:0927/112020.240175:INFO:CONSOLE(630)] "%cTRACE color: #888 Renderer->SharedProcess#connect", source: vscode-file://vscode-app/usr/lib/code/out/vs/workbench/workbench.desktop.main.js (630)
[0927/112020.251987:ERROR:elf_dynamic_array_reader.h(64)] tag not found
```

I know that there is another Issue with the same problem: #180648
But this issue is closed an I cannot reopen it.

**Comment by deepak1556** [comment]
Merging to https://github.com/microsoft/vscode/issues/184124

**Comment by NelDav** [comment]
I didn't find #184124 before. Looks like the same error. Thank you for merging.
