### ISSUE TITLE
Make it obvious that the version details in the About box can be copied

### ISSUE THREAD

**Issue by BillDenton** [Microsoft/vscode#19424]
- VSCode Version: Code - Insiders 1.9.0-insider (61a56dbf6e80b6732381349e4654e3ae5f0710f4, 2017-01-24T08:13:13.694Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions:

|Extension|Author|Version|
|---|---|---|

---

Steps to Reproduce:

1. Help, About
2. How do I get the text? I found out by accident that pressing Ctrl+C copied the details. Not obvious. Please add a button for copying the information.

**Comment by bpasero** [comment]
This feature request will not be considered in the next [6-12 months roadmap](https://github.com/Microsoft/vscode/wiki/Roadmap) and as such will be closed to keep the number of issues we have to maintain actionable. Thanks for understanding and happy coding!
