### ISSUE TITLE
Top tab border wrong size with Pinned Tab Sizing shrink when scrolling/wrapping

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#194202]
Testing #193991

Enable `workbench.editor.highlightModifiedTabs` and make a pinned editor dirty. Notice how the blue color appears over the entire tab bar:

![Image](https://github.com/microsoft/vscode/assets/900690/364847e8-0e94-4a17-9702-a8ef9bb81c15)

VS in stable:

![Image](https://github.com/microsoft/vscode/assets/900690/32ed3afd-604f-4d6b-94b6-ef18bab0970e)

**Comment by benibenj** [comment]
My investigation: `workbench.editor.highlightModifiedTabs` is not causing this but the pinned tab sizing. It causes the `tabBorderTopContainer` to have the wrong width only when the tab bar starts scrolling/wrapping. Not sure how having two tab rows is causing this. Still working on it...

**Comment by benibenj** [comment]
So the bug is actually also in stable, however, it's likelier to occur when using the two tab bars feature.

**Comment by benibenj** [comment]
[.monaco-workbench .part.editor > .content .editor-group-container > .title .tabs-container.disable-sticky-tabs > .tab.sizing-fit.sticky-compact,](https://github.com/microsoft/vscode/blob/2c34b239ca45419760f44bb1191032fe6a299ae5/src/vs/workbench/browser/parts/editor/media/multieditortabscontrol.css#L190-L197)

**Comment by bpasero** [comment]
Hm, from my memory `position: static` is to let pinned tabs stay positioned even when a scrollbar is needed. In that case, essentially all unpinned tabs would scroll "under" the pinned tabs.

But when tabs wrap, I believe we would not need `position: static` at all unless there are so many tabs that we fallback to scrolling.

**Comment by benibenj** [comment]
This is stable release

![Image](https://github.com/microsoft/vscode/assets/44439583/bfc23537-7f62-43f7-9bcf-26f0b6cd3d0e)

**Comment by bpasero** [comment]
Wow! I wonder why nobody reported this so far 🤔
