### ISSUE TITLE
macOS: native crash in integration tests

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#194257]
https://dev.azure.com/monacotools/Monaco/_build/results?buildId=233756&view=results

[f3ab860c-b223-45a6-8027-ac0323019acd.dmp.zip](https://github.com/microsoft/vscode/files/12735290/f3ab860c-b223-45a6-8027-ac0323019acd.dmp.zip)

**Comment by deepak1556** [comment]
Merging to https://github.com/microsoft/vscode/issues/192119
