### ISSUE TITLE
Unable to debug using custom debug command

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#19426]
Testing: https://github.com/Microsoft/vscode/issues/19043

* Windows 10
* follow steps and implement a command that returns:

```typescript
context.subscriptions.push(vscode.commands.registerCommand('extension.node-debug.debugCommand', config => {
	return {
		command: "C:\\Program Files\\nodejs\\node.exe",
		args: ["--debug"]
	};
}));
```

* try to run a node.js application
* I never see the debugger starting

**Comment by weinand** [comment]
You'll have to pass the entry point of the debug adapter as an argument, e.g.
```js
context.subscriptions.push(vscode.commands.registerCommand('extension.node-debug.debugCommand', config => {
	return {
		command: "C:\\Program Files\\nodejs\\node.exe",
		args: [ "./out/node/nodeDebug.js" ]
	};
}));
```
It is not necessary to pass"--debug" because we don't want to debug the adapter but the target.
But use `context.asAbsolutePath()` to make the entry point path absolute.

**Comment by bpasero** [comment]
@weinand doing so I now get this when trying to debug:

![image](https://cloud.githubusercontent.com/assets/900690/22328047/884d3b68-e3ba-11e6-81e2-4f816018d0d5.png)

**Comment by weinand** [comment]
Yes, this error occurs if a relative entrypoint path is used. That's the reason why I mentioned `context.asAbsolutePath` above.
This extension code works fine for me on Windows 10:
```js
	context.subscriptions.push(vscode.commands.registerCommand('extension.node-debug.debugCommand', config => {
		return {
			command: "C:\\Program Files\\nodejs\\node.exe",
			args: [ context.asAbsolutePath("./out/node/nodeDebug.js") ]
		};
	}));
``` 
We cannot verify the args passed back from the extension because we do not no their semantics.
