### ISSUE TITLE
Parameter hint has less clear docs than the tsDoc

### ISSUE THREAD

**Issue by amunger** [microsoft/vscode#194228]
Testing #194028

I don't think this is specific to this particular method doc, but the parameter hint that appears after autocompleting the method is different (and confusing/vague) than just hovering over the method name:

type `vscode.env.onDidChangeShell(` and let the parameter hints pop up:

![image](https://github.com/microsoft/vscode/assets/2019016/ed66024e-d99d-4f51-98ed-9150158b9780)

vs mouse hover on the method

![image](https://github.com/microsoft/vscode/assets/2019016/5197530f-5587-4880-8029-0e7c7f387c52)

**Comment by Tyriar** [comment]
Correct me if I'm wrong, but I think this is just the shared doc for all event listeners as they are all `Event<T>`s:

<img width="882" alt="Screenshot 2023-09-26 at 2 18 55 PM" src="https://github.com/microsoft/vscode/assets/2193314/eb5b9479-b7a4-42e9-bf74-c79fe365fd9c">

**Comment by amunger** [comment]
yeah, looks like it. Pretty strange
