### ISSUE TITLE
Not possible to trigger actions below reply input as a keyboard user?

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode#194235]
Testing #194012

After I focus a comment, I can tab to the actions in the comments title area, but I don't see a way to get focus to the 'Resolve Conversation' button or the 'Make a Suggestion' button. 'Resolve Conversation' is at least exposed in the command palette, so it is triggerable with a keybinding, but I would expect the other actions to also be focusable or triggerable from the palette:
- Make a Suggestion
- Start Review
- Add Comment

![Image](https://github.com/microsoft/vscode/assets/30305945/adb9f18f-39cf-4d5d-b529-de4ce610e847)

**Comment by meganrogge** [comment]
You need to enable tab moves focus mode, `ctrl+m` on windows. 

We should probably add a keybinding for each of the actions.

**Comment by meganrogge** [comment]
From a visual standpoint, the tab order looks funny (right to left), but IMO, it makes the most sense to have them prioritized as they are:

- Add comment
- Start review
- Make a suggestion

**Comment by meganrogge** [comment]
We should also mention here that there are actions to be tabbed to and state that to reach them, use tab moves focus mode.

![Screenshot 2023-09-26 at 3 14 04 PM](https://github.com/microsoft/vscode/assets/29464607/88137167-4bef-4c64-980b-994146a47d00)

**Comment by joyceerhl** [comment]
I don't think we necessarily need keybindings for these, just exposing the functionality as commands in the palette would help

**Comment by alexr00** [comment]
These actions are contributed by GHPRI. I'll update their context so they show in the command palette when you're editing a comment.

**Comment by alexr00** [comment]
Actually, we close the comment editor when the command palette is shown, so I can't just make this change in the extension. I can look into this in October if we want to change it.

**Comment by alexr00** [comment]
I've looked into this further:
- All the buttons are accessible when you use tab moves focus ✅
- I _can_ make the comment editor stay open when the command palette is opened, but any command executed from the command palette at this time will not have the correct comment context.

Since the buttons are accessible I'm going to close.
