### ISSUE TITLE
Toggling file node in Comments view focuses comment

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode#194236]
Testing #194012

1. Checkout https://github.com/microsoft/vscode/pull/193812
2. Open comments view
3. Have `debug.contribution.ts` open and scrolled to the top of the file
4. Hit enter in the `debug.contribution.ts` node
5. :bug: I get scrolled to the first comment

**Comment by joyceerhl** [comment]
This also happens if I expand the node after collapsing it, which I found a bit surprising, as I didn't hit enter on a specific comment, just the file node

**Comment by alexr00** [comment]
There are a couple problems here:
- We should only expand/collapse the file node when the twisty is clicked/entered (we should have both an action and an expand/collapse with the file is clicked/entered)
- We should just open the file and not scroll to a comment when the file node is clicked/entered.

**Comment by alexr00** [comment]
Actually, since you're opening the file from the Comments view, it makes sense to reveal the first comment. I'm just going to fix the expand/collapse + action issue.

**Comment by andreamah** [comment]
I just verified this by making sure that clicking on the node doesn't expand/collapse the node (only the twistie can). Please lmk if that's sufficient!

**Comment by alexr00** [comment]
That is sufficient!
