### ISSUE TITLE
Inform the user that switching the used TypeScript version requires a restart

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode#19427]
See the attached movie. Notice that switching to the locally installed TypeScript version has only an effect after a restart since the typescript server is already running. We should inform the user that the change is in effect after restart.

![ts-version](https://cloud.githubusercontent.com/assets/172399/22327734/fdb0258e-e3b8-11e6-8aca-57492edbf785.gif)

**Comment by kylecordes** [comment]
This seems additionally problematic because "has this workspace been set to use the TypeScript version specified in the workspace?" does not appear to be visible anywhere in the UI or file system.

**Comment by egamma** [comment]
In the latest version the user is informed that a Reload is required. My original issue is addressed and I'm closing this issue.
