### ISSUE TITLE
Debug console with DWARF debugging isn't printing the expected value

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#194232]
Testing #194071

See top left `a` and debug console `a`:

![Image](https://github.com/microsoft/vscode/assets/2193314/5c6ca24a-73e7-4424-8373-1d73ac57ce91)

**Comment by connor4312** [comment]
This isn't something that really works, as we can't compile language X into code that we can execute to evaluate an expression.

I don't think we can wholesale disable the debug console input when in WASM locations, but we could print some more helpful error message.

**Comment by Tyriar** [comment]
I kind of wasn't expecting it to work, what confused me the most was it was saying `b` was a thing

**Comment by connor4312** [comment]
It looks like we actually can evaluate some expressions and the DWARF debugger includes [lldb-eval](https://github.com/google/lldb-eval). So we just need to delegate execution there, and complex expressions will error appropriately. Should be easily enough.

**Comment by connor4312** [comment]
@joyceerhl can you confirm the DWARF debugging extension is installed and emailed, and if so set `trace: true` and share your logs?

**Comment by joyceerhl** [comment]
Works well, I forgot I'd disabled it for verifying another issue 🤦
