### ISSUE TITLE
Go to next comment thread focuses visible comment when first invoked

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode#194237]
Testing #194012

1. Have a comment from https://github.com/microsoft/vscode/pull/193812 visible in the editor
2. Run Alt+F9
3. :bug: I don't get scrolled to the next comment thread, it just focuses the one that's already visible in the editor

**Comment by alexr00** [comment]
We find the next comment thread based on where your cursor is. If your cursor is above the comment that's visible in the editor, then we consider the next comment to be the one that's already visible.  The built in diff command for Next and Previous Change work the same way.
