### ISSUE TITLE
i have a problem with vsCODE

### ISSUE THREAD

**Issue by YahyaEssid** [microsoft/vscode#194309]
ADD ISSUE DESCRIPTION HERE
It takes too much time to load and after waiting it says that i need to reload and it failed to connect.
i can't use the debugger also.
Version: 1.82.2
Commit: abd2f3db4bdb28f9e95536dfa84d8479f1eb312d
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36
Embedder: codespaces

**Comment by roblourens** [comment]
Sounds like you're having an issue with codespaces, see the docs here https://docs.github.com/en/codespaces/troubleshooting/troubleshooting-github-codespaces-clients or buttons at the bottom for extra help
