### ISSUE TITLE
Keep getting a change on workspace open

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#194375]
* I guess this a regression from https://github.com/microsoft/vscode/pull/194345
* Have workspace setting like below
* Reload the window
* :bug: you get change in `.vscode/settings.json` which is a spread of those compact settings

### Before
```
 "[typescript][javascript]": {
    "editor.insertSpaces": false,
    "editor.defaultFormatter": "vscode.typescript-language-features",
    "editor.formatOnSave": true,
    "editor.codeActionsOnSave": {
      "source.organizeImports": "always"
    }
  },
```

### After
```
{
  "[typescript][javascript]": {
    "editor.insertSpaces": false,
    "editor.defaultFormatter": "vscode.typescript-language-features",
    "editor.formatOnSave": true,
    "editor.codeActionsOnSave": {
      "source.organizeImports": "always"
    }
  },
// ....
  "[javascript]": {
    "editor.codeActionsOnSave": {
      "source.organizeImports": "always"
    }
  },
  "[typescript]": {
    "editor.codeActionsOnSave": {
      "source.organizeImports": "always"
    }
  },
}
```

<img width="1512" alt="Screenshot 2023-09-28 at 10 29 54" src="https://github.com/microsoft/vscode/assets/1794099/6f691b07-c6dd-461a-915f-869104de26dd">

**Comment by bpasero** [comment]
✋ I actually thought this was intentional and have pushed the change to `vscode-docs@vnext` branch.

**Comment by sandy081** [comment]
@justschen There should not be migration happening in this case right?

**Comment by sandy081** [comment]
I would suggest to check the new value and write only if it is changed.

**Comment by justschen** [comment]
Sounds look. Looking into this atm.

**Comment by justschen** [comment]
Resolved the settings changing in scenarios where migration is not needed, but in scenarios where migration _is_ needed, the above change still happens. Ends up looking like this:
```
{
	"files.autoSave": "onFocusChange",
    "editor.accessibilitySupport": "on",
	"workbench.colorTheme": "Solarized Light",
	"editor.detectIndentation": false,
	"editor.codeActionWidget.showInlineQuickfixes": true,
	"editor.codeActionWidget.includeNearbyQuickfixes": true,
	"[typescript][javascript]": {
		"editor.insertSpaces": false,
		"editor.defaultFormatter": "vscode.typescript-language-features",
		"editor.formatOnSave": true,
		"editor.codeActionsOnSave": {
		  "source.organizeImports": true
		}
	  },
   "editor.codeActionsOnSave": {
	"source.removeUnusedImports": "explicit"
},
"[javascript]": {
	"editor.codeActionsOnSave": {
		"source.removeUnusedImports": "explicit",
		"source.organizeImports": "explicit"
	}
},
"[typescript]": {
	"editor.codeActionsOnSave": {
		"source.removeUnusedImports": "explicit",
		"source.organizeImports": "explicit"
	}
},
}
```

Digging into it further, this is because `registerEditorSettingMigration` doesn't have the concept of anything outside of it's current scope (in this case, `editor.codeActionsOnSave`), seems to find the setting multiple times for each language. 

@sandy081 @jrieken Not sure if there is a better way to handle the migrations but would appreciate some thoughts/insight - some of the more complex examples in https://github.com/microsoft/vscode/blob/main/src/vs/editor/browser/config/migrateOptions.ts are still a tad different from what we want to accomplish here.

**Comment by sandy081** [comment]
```json
{
	"[typescript][javascript]": {
		"editor.insertSpaces": false,
		"editor.defaultFormatter": "vscode.typescript-language-features",
		"editor.formatOnSave": true,
		"editor.codeActionsOnSave": {
		  "source.organizeImports": true
		}
	},
	"[javascript]": {
		"editor.codeActionsOnSave": {
			"source.removeUnusedImports": "explicit",
			"source.organizeImports": "explicit"
		}
	},
	"[typescript]": {
		"editor.codeActionsOnSave": {
			"source.removeUnusedImports": "explicit",
			"source.organizeImports": "explicit"
		}
	},
}

```

To confirm, even though value is migrated to each language independently, the effective value is correct and will be the migrated value. I mean, the value of `editor.codeActionsOnSave` for `typescript` and `javascript` languages will be 

```json
{
        "source.removeUnusedImports": "explicit",
        "source.organizeImports": "explicit"
}
```

**Comment by justschen** [comment]
closing and deferring rest of issue to https://github.com/microsoft/vscode/issues/194427

**Comment by justschen** [comment]
@joyceerhl repro:

setting is this:

```
 "[typescript][javascript]": {
            "editor.insertSpaces": false,
            "editor.defaultFormatter": "vscode.typescript-language-features",
            "editor.formatOnSave": true,
            "editor.codeActionsOnSave": {
                "source.organizeImports": true,
                "source.fixAll": false
            }
          },
```


should end up like this without duplicating the settings:
```
 "[typescript][javascript]": {
            "editor.insertSpaces": false,
            "editor.defaultFormatter": "vscode.typescript-language-features",
            "editor.formatOnSave": true,
            "editor.codeActionsOnSave": {
                "source.organizeImports": "explicit",
                "source.fixAll": "never"
            }
          },
```

**Comment by sandy081** [comment]
Found following bug while verifying - https://github.com/microsoft/vscode/issues/199736
