### ISSUE TITLE
"task.allowAutomaticTasks": "off" doesn't work in workspace settings?

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#194338]
I have a multiroot workspace that contains vscode and vscode-copilot, which has an auto-run task. I have `"task.allowAutomaticTasks": "off"` in my workspace config settings, but when I reload the window, the build task autoruns anyway. I thought this was working earlier, maybe not.

**Comment by meganrogge** [comment]
do you have `task.allowAutomaticTasks: on` in your folder settings for `vscode-copilot`? I would think that would override the workspace setting

**Comment by meganrogge** [comment]
here's where we check that, hasn't changed https://github.com/microsoft/vscode/blob/e4ef0a913dabd9f239a24b38531d4ee462dca6f6/src/vs/workbench/contrib/tasks/browser/runAutomaticTasks.ts#L43

**Comment by roblourens** [comment]
Nope. Maybe I can set a breakpoint on that line

**Comment by meganrogge** [comment]
maybe we should be using `getConfigurationData` there and first checking the workspace value and then checking the user value

**Comment by meganrogge** [comment]
@roblourens I cannot reproduce. I set that to off in my workspace settings, have a repo with a task set to run on folder open, reload the window, it does not run.

**Comment by roblourens** [comment]
Hm, it's happening in Insiders for me but not OSS, so I will debug a little more

**Comment by roblourens** [comment]
Ah, debugging showed that it's not automatic tasks, it's task reconnection. But, I always kill these tasks, and it seems like reconnection is starting them from scratch?

![Recording 2023-10-04 at 14 37 43](https://github.com/microsoft/vscode/assets/323878/8cbbee8a-a773-49f2-a20a-33cf4d3fd87f)

**Comment by meganrogge** [comment]
hm, if you disable reconnection, reload, does that get fixed?

**Comment by roblourens** [comment]
Yeah. I disabled reconnection, reloaded, enabled it, reloaded again, and it didn't start the tasks. So I think I have cleared whatever bad state was stuck in there.
