### ISSUE TITLE
AutoFill Option in Debug Console in debugging mode

### ISSUE THREAD

**Issue by komal436** [Microsoft/vscode#19430]
- VSCode Version: 1.81.
- OS Version: Windows-10

Steps to Reproduce:

1. Running powershell script with break point
2. The variables initialized in the propgram space are not auto filled on pressing tab.

**Comment by mousetraps** [comment]
Hey @komal436, thanks for reporting! Quick question to help narrow down the issue - are you getting no completions at all, or are the completions not what you expect them to be?

**Comment by komal436** [comment]
1. I am not getting any autofill option.
<img width="960" alt="temp" src="https://cloud.githubusercontent.com/assets/2834974/22361486/328cc48e-e480-11e6-918d-af2052e0e4b8.png">

**Comment by isidorn** [comment]
Please file this against the powershell extension here https://github.com/PowerShell/vscode-powershell
Thanks!
