### ISSUE TITLE
Open Editors pane - closes wrong file when clicking the close icon

### ISSUE THREAD

**Issue by redtopia** [microsoft/vscode#194326]
Type: <b>Bug</b>

When clicking on the Close icon to the left of a file in the Open Editors pane, the currently selected file closes instead of the file that is being closed.

To reproduce:

1. Open several files, show the Open Editors pane
2. Select the first file in the Open Editors pane
3. In the Open Editors pane, click on the Close icon to the left of any of the other files
4. The selected file will close instead of the one you clicked on

![screenshot](https://github.com/microsoft/vscode/assets/812777/f13fc0f0-6153-4624-8b6c-3cc975fef96c)

VS Code version: Code 1.82.2 (abd2f3db4bdb28f9e95536dfa84d8479f1eb312d, 2023-09-14T05:55:25.390Z)
OS version: Windows_NT x64 10.0.22621
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.79GB (7.33GB free)|
|Process Argv|--crash-reporter-id 1d9325a9-6575-4e45-8014-8aa12809d09c|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
aws-toolkit-vscode|ama|1.91.0
gitlens|eam|14.3.0
copilot|Git|1.116.440
copilot-chat|Git|0.7.1
copilot-labs|Git|0.15.1019
todo-tree|Gru|0.0.226
vscode-cfml|Kam|0.5.4
vscode-docker|ms-|1.26.1
remote-containers|ms-|0.309.0
vscode-yaml|red|1.14.0
markdown-preview-enhanced|shd|0.7.10
vscode-todo-highlight|way|1.0.5

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
py29gd2263:30792226
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
282f8724:30602487
89544117:30613380
2i9eh265:30646982
showlangstatbar:30737416
03d35959:30757346
pythonfmttext:30731395
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
pythonnosmt12:30797651
pythonidxptcf:30805731
pythonnoceb:30805159
copilotsettingt:30839829
asynctok:30821568
dsvsc013:30795093
dsvsc014:30804076
diffeditorv2:30821572
dsvsc015:30845448

```

</details>

**Comment by lramos15** [comment]
This should be fixed in the next release :)
