### ISSUE TITLE
Snippet mode is left on editor blur

### ISSUE THREAD

**Issue by konqui** [Microsoft/vscode#19433]
- VSCode Version: 1.8.1
- OS Version: Windows 7

Steps to Reproduce:

1. inserting a snippet to be more specific one with more than one tab trigger ($1,$2,$3 etc.)
2. insert the snippet 
3. insert text at first ($1) possition
4. change to another windows window e.g. Browser Window or a Notpad Window (no difference between switching via mouse or alt+tab)
5.  copy somthing you wanna past into vscode
6. switch back to vscode window
7. press tab to go to next position ($2)

at this point it fails instead of going to next position ($2) it does the normal context based thing as if the file already existed

i thought this whole thing may be caused due to the fact that i have set my vscode to save/persist file on loosing focus - it isn't i have tested this already by disabling autosave at all (also i have restarted the editor after this change sinze it may be affecting only new sessions) - still the same it looses the focus

can someone check if its only me or also for others

**Comment by alexandrudima** [comment]
Reduced steps:
* insert a snippet (e.g. for loop in JS)
* focus a different editor
> Observe: The original editor is no longer in snippet mode.

**Comment by jrieken** [comment]
This is the designed behaviour because wand the snippet mode not to be too sticky.

**Comment by jrieken** [comment]
With the May release we won't leave snippet mode when the editor blurs. This makes our snippet experience more aligned with other editors too

**Comment by jrieken** [comment]
fixed with https://github.com/Microsoft/vscode/pull/26042
