### ISSUE TITLE
Built-in functions for R are stale

### ISSUE THREAD

**Issue by MichaelChirico** [microsoft/vscode#194350]
https://github.com/microsoft/vscode/blob/c965b118a67c0f22895d2af899736d0e0aa82ffd/extensions/r/syntaxes/r.tmLanguage.json#L592C2-L592C2

Latest R contains more functions, e.g. this includes `isTRUE()` but not `isFALSE()`.

`isFALSE()` was part of R 3.5.0, circa April 2018:

https://github.com/r-lib/backports#backports-for-r-versions-prior-to-350
https://github.com/wch/r-source/tree/tags/R-3-5-0

**Comment by alexr00** [comment]
Moved to https://github.com/REditorSupport/vscode-R/issues/1429
