### ISSUE TITLE
Tune new colors added for dark+ & light+ themes

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode#1943]
For the light and dark theme we added for new colors. We'd need a pass from the UX team to tune them where necessary. Especially in the light themes, some of the colors don't differ very much from the existing colors.
To tune, make changes to extensions/theme-colorful-defaults/themes/dark_plus.tmTheme and light_plus.tmTheme 

Theme  | Control flow keywords | Type names | Function names | Variable & Parameter names
------------ | ------------- | ------------- | ------------- | -------------
Light | Pink AF00DB ***WCAG AA pass*** | Turquoise 2B91AF ***Insufficient Contrast!!*** | Light gray 404040 | Dark blue 001080
Dark | Pink C586C0 ***WCAG AA pass*** | Turquoise ***4EC9B0*** | Yellow-brown DCDCAA | Light blue 9CDCFE

The base colors are (I wouldn't make any changes to these):

Theme | Background | Default foreground | Comments | Keywords | Strings | Numbers
------------ | ------------- | ------------- | ------------- | ------------- | ------------- | -------------
Light | White FFFFFF | Black 000000 | Green 008000 | Blue 0000FF | Red A31515 | Green 09885A
Dark | Black 000000 | White D4D4D4 | Green 608B4E ***Insufficient Contrast!!*** | Blue 569CD6 | Red CE9178 | Green B5CEA8

![image](https://cloud.githubusercontent.com/assets/6461412/12259402/d1e1bfa4-b915-11e5-9647-917575d7f136.png)
![image](https://cloud.githubusercontent.com/assets/6461412/12259277/d52209f4-b914-11e5-93dd-0ea11d612010.png)

Snippet:
```typescript
export module Conway {
	export class Cell {
		private row: number;
        private col: number;
        
		public countNeighbors(cell: Cell) : number {
			var neighbors = 0;
			for (var row = -1; row <= 1; row++) {
				for (var col = -1; col <= 1; col++) {
					if (row == 0 && col == 0) continue;
					if (this.isAlive(cell.row + row, cell.col + col)) {
						neighbors++;
					}
				}
			}
			return neighbors;
		}
        
        private isAlive(row: number, col: number) : boolean {
            return true;
        }
    }
}
```

**Comment by bgashler1** [comment]
@aeschli glad to help!

While I'm working on this, I wanted to point out a bug I noticed.

#Classic theme (both light and dark) differs from VS
Our classic theme is not coloring types of functions and function parameters.  It also is not coloring a module name (see below).  Is this going to be addressed?

***VS Code***
![vscoded copy](https://cloud.githubusercontent.com/assets/11839736/12280631/5b2ace9e-b944-11e5-976e-243b01dfe6b2.png)

***Visual Studio***
![vs](https://cloud.githubusercontent.com/assets/11839736/12280573/cd6c7260-b943-11e5-845c-895f6f894881.png)

**Comment by bgashler1** [comment]
#Accessibility Analysis
I've checked all the colors against ***Web Content Accessibility Guidelines [WCAG 2.0](http://www.w3.org/TR/WCAG20/)***.

I've updated your [comment above](#issue-126131234) with annotations as to which colors could be improved (i.e. ones that only got a AA-rating, or minimum requirements) and which ones did not pass with sufficient contrast.

I will provide updated alternatives in a little bit that will fix the ones not passing minimum contrast.

# Aesthetic Analysis
The colors look good on dark, but on light theme the function/method names are not clearly colored (especially for people that have trouble seeing faint colors). We could also improve contrast on type annotations on the light theme.  I'll provide some updated colors momentarily.

**Comment by bgashler1** [comment]
# Suggested Replacement Colors for Dark+ and Light+

Theme  | Control flow keywords | Type names | Function names | Variable & Parameter names
------------ | ------------- | ------------- | ------------- | -------------
Light | Pink AF00DB ***WCAG AA pass*** | Turquoise ***267f99*** | Dark brown ***#777759*** | Dark blue 001080
Dark | Pink C586C0 ***WCAG AA pass*** | Turquoise C586C0 ***WCAG AA pass*** | Yellow-brown DCDCAA | Light blue 9CDCFE

**Comment by aeschli** [comment]
Thanks @bgashler1.
I updated the light theme according to your suggestions.
I realized that I had a wrong RGB value in the table above. It's Turquoise 4EC9B0 (not C586C0).
4EC9B0 is also what you see in the screenshots.
Can you confirm that 4EC9B0 is fine?

**Comment by isidorn** [comment]
I do not like the gray color for the ligth+ theme for method names.
It makes it look **blury** compared to the nice black text that the rest of the document has.
I would like a special color but something that looks sharp

Just my opinion as an every day light+ theme user

**Comment by bgashler1** [comment]
@isidorn, what do you think of `#795E26` (***Proposal 2*** below) instead?  I think this is a good balance.  It correlates with the dark theme's color, but it's much more crisp and has a much stronger contrast ratio.

<img width="629" alt="color proposal 2" src="https://cloud.githubusercontent.com/assets/11839736/12342377/bae3e37a-bade-11e5-97c7-1ba3f4441ead.png">

**Comment by isidorn** [comment]
:+1:

**Comment by Boyhan78** [comment]
Dikirim dari ponsel cerdas Samsung Galaxy saya.

-------- Pesan asli --------
Dari: Isidor Nikolic <notifications@github.com> 
Tanggal:15/01/2016  14:37  (GMT+07:00) 
Ke: Microsoft/vscode <vscode@noreply.github.com> 
Cc:  
Subjek: Re: [vscode] Tune new colors added for dark+ & light+ themes (#1943)

**Comment by aeschli** [comment]
795E26 looks good to, I updated the code

**Comment by bgashler1** [comment]
Awesome!  Thanks guys.

**Comment by aeschli** [comment]
![image](https://cloud.githubusercontent.com/assets/6461412/12658657/a833fa44-c60a-11e5-93d6-51f5fc2cee8c.png)

**Comment by aeschli** [comment]
![image](https://cloud.githubusercontent.com/assets/6461412/12658696/e1744d72-c60a-11e5-80a0-c3f97ddead1a.png)
