### ISSUE TITLE
"Reveal in File Explorer" from explorer context menu is broken on WSL

### ISSUE THREAD

**Issue by cl1107** [microsoft/vscode#194359]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.82.2
- OS Version: windows 11 22H2 OS内部版本 22621.2361
- WSL Version: 1.2.5.0
- WSL extension version: v0.81.5

Steps to Reproduce:

1. vscode connect to wsl
2. open a folder
3. right click a file in the context menu and select Reveal in File Explorer

nothing happens

**Comment by xqm32** [comment]
I also have this problem. It seems to be an issue with WSL extension v0.81.5. After downgrading to v0.81.4, I no longer have this problem. One workaround could be:
1. Open the command palette.
2. Type "ext install spec" to install WSL extension v0.81.4 version.

**Comment by cl1107** [comment]
#https://github.com/microsoft/vscode-remote-release/issues/9037

**Comment by realiti4** [comment]
I am not sure if it is because of the new file explorer update or wsl, but this is no longer working.

**Comment by Nikolai2038** [comment]
> I also have this problem. It seems to be an issue with WSL extension v0.81.5. After downgrading to v0.81.4, I no longer have this problem. The workaround could be:
> 
>     1. Open the command palette (ctrl+shift+p).
> 
>     2. Type "ext install spec" to install WSL extension v0.81.4 version.
> 
> 
> VS Code Version: 1.82.2 (user setup) commit [abd2f3d](https://github.com/microsoft/vscode/commit/abd2f3db4bdb28f9e95536dfa84d8479f1eb312d) OS Version: Windows 11 Enterprise 22H2 build 22621.2283 WSL version: 1.2.5.0 WSL extension version: v0.81.5

Worked for me, Thanks!!

**Comment by alexmillman23** [comment]
> 1. Open the command palette (ctrl+shift+p).
> 2. Type "ext install spec" to install WSL extension v0.81.4 version.

Was broken for me and this fixed. Thanks!
