### ISSUE TITLE
[regression] CodeAction on save is broken

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#194397]
Version: 1.83.0-insider
Commit: aad333b878b4cfce2f4152d48552fb6f980d7daf

* have the user setting spec'd below
* open `src/vs/editor/contrib/stickyScroll/test/browser/stickyScroll.test.ts`
* remove the semicolon on line 29
* save via `Cmd+S`, semi column isn't inserted

```
  "editor.codeActionsOnSave": {
    "source.fixAll.eslint": "explicit",
    "source.removeUnusedImports": "explicit"
  },
```

**Comment by bhavyaus** [comment]
Related: https://github.com/microsoft/vscode/issues/194437
