### ISSUE TITLE
Cannot navigate to top command in accessible buffer

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#194321]
1. Run `ls` twice
2. Ctrl+up to open terminal accessible buffer
3. Alt+up twice 🐛 it only moves up once

**Comment by Tyriar** [comment]
Windows yeah, it's working now that I try it again though 😕 

Pretty sure I saw the blue dot, will reopen if I see it again

**Comment by meganrogge** [comment]
I have seen flaky-ness on windows, though not sure what we can do about that.
