### ISSUE TITLE
lodash in bundled git extensions takes 4.8M

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode#19438]
Looking at the latest [VSCode-darwin-insider](https://az764295.vo.msecnd.net/insider/6ba4282fd27bacacbf8482472a0519560720fb9c/VSCode-darwin-insider.zip) build, it shows that the new git extension takes 5.4M.
From that 4.8M is the lodash node module.

 20K	/extensions/git/node_modules/denodeify/test
 40K	/extensions/git/node_modules/denodeify
1.6M	/extensions/git/node_modules/lodash/fp
4.8M	/extensions/git/node_modules/lodash
 12K	/extensions/git/node_modules/vscode-nls/lib
 28K	/extensions/git/node_modules/vscode-nls
4.9M	/extensions/git/node_modules
4.0K	/extensions/git/out/typings/globals/denodeify
4.0K	/extensions/git/out/typings/globals/lodash
8.0K	/extensions/git/out/typings/globals
8.0K	/extensions/git/out/typings
328K	/extensions/git/out
 48K	/extensions/git/resources/icons/dark
 48K	/extensions/git/resources/icons/light
 96K	/extensions/git/resources/icons
 96K	/extensions/git/resources
5.4M	/extensions/git

**Comment by joaomoreno** [comment]
Great catch, we should remove it, it's not needed for much.
