### ISSUE TITLE
Add window.restoreZenMode option

### ISSUE THREAD

**Issue by itsravenous** [Microsoft/vscode#19431]
I'd like code to open in Zen mode so I'm distraction-free immediately. There's already a `window.restoreFullscreen` which does the equivalent for fullscreen mode, but it would be great to be able to go that one step further and "boot up" in zen mode.

**Comment by mousetraps** [comment]
Nice idea! cc @isidorn

**Comment by isidorn** [comment]
I have added `zenMode.restore`. Feedback on the name is welcome
Alternative was `zenMode.restoreOnStart`

@bpasero maybe you have an idea for a better name

**Comment by bpasero** [comment]
Thats ok, we have `window.restoreFullscreen` for the fullscreen state.

**Comment by itsravenous** [comment]
I assumed it would be `window.restoreZenMode` but I really don't mind as long as it's there ;)

**Comment by isidorn** [comment]
All zenMode settings are under `zenMode.`

**Comment by isidorn** [comment]
Fixed in latest, there was an issue which @sandy081 uncovered. Will be in tomorrows build
