### ISSUE TITLE
missing viewtype for interactive window

### ISSUE THREAD

**Issue by mmann1123** [microsoft/vscode#194479]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: vscode 1.82.2
- OS Version:  Pop!_OS 22.04 LTS

extensions: jupyter (microsoft)

Steps to Reproduce:
Description
I am routinely running into a problem with ipython cells and notebooks.  Sometimes this is temporarily resolved in a vscode update and sometimes it becomes a problem again. 

When I add a cell in my py files:
```
#%%
import pandas
#%%
```
and execute the cell i get `Missing viewType for 'vscode-interactive:/Interactive-1.interactive'` a popup with the following. 

Attempts to fix
I have tried closing all vcode windows as well as restarting
I have reinstalled the jupyter extension

**Comment by amunger** [comment]
The error message shows a file schema that we removed quite a while ago (`vscode-interactive`), and I'm not really sure how it could show up in v1.82. 

Is the Jupyter extension up to date?
Does this repro if you only have the Jupyter and python extensions enabled? (You can use a temporary profile to help test that `Profiles: Create a temporary profile`)
Do you see any other errors in the Developer tools console - `Developer: Toggle developer tools`

**Comment by mmann1123** [comment]
I just tried creating a new empty profile and only installed jupyter extension from microsoft.  Same thing.  

Sorry not sure how to access the developer tools. Do I need to install an extension first?  Not seeing anything in my command pallete

**Comment by amunger** [comment]
workbench.action.toggleDevTools is a core command, so it should be available. `ctrl+shift+i` is the default keybinding

**Comment by mmann1123** [comment]
I ended up doing another restart because of an issue I was having with docker daemon but somehow it has resolved this issue (despite having tried restarting earlier).  So... not sure what's going on. Would docker hanging be an issues for ipython?

**Comment by mmann1123** [comment]
I guess we can close this for now until it crops again if you want

**Comment by amunger** [comment]
I don't see how that could be related. We did just release a new version a few hours ago though, so perhaps it was the update again. 
Let us know if you see it again
