### ISSUE TITLE
MacOS VSCode multiple workspaces in a window

### ISSUE THREAD

**Issue by Viranchee** [microsoft/vscode#194441]
Would it be possible that there are multiple tabs of workspaces on the very top where there is a search bar

<img width="2048" alt="image" src="https://github.com/microsoft/vscode/assets/9246095/3435ae49-0d00-48b5-9842-77e280b88cce">

**Comment by roblourens** [comment]
See `window.nativeTabs`

**Comment by Viranchee** [comment]
Thank you @roblourens 
Btw I meant multiple workspaces visible at the very top.
NativeTabs dedicates 1 window to a particular workspace
1 VSCode Window hosts multiple workspaces : is there such a solution?

**Comment by roblourens** [comment]
Maybe I don't understand what you mean by "workspace" then. Instead of having multiple vscode windows, this lets you combine those into one window with tabs.
