### ISSUE TITLE
Intellisence should not be active when entering in comments.

### ISSUE THREAD

**Issue by xucaen** [Microsoft/vscode#19444]
- VSCode Version: Code 1.8.1 (ee428b0eead68bf0fb99ab5fdc4439be227b6281, 2016-12-19T14:49:23.350Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions:

|Extension|Author|Version|
|---|---|---|

---

Steps to Reproduce:

1. create a PHP file.
2. create a comment
3. as you type in the comment, intellisence keeps choosing new words.

**Comment by Wosi** [comment]
Possible duplicate of https://github.com/Microsoft/vscode/issues/719

**Comment by druellan** [comment]
Just to point out that this is also an issue on SCSS files.

**Comment by roblourens** [comment]
I no longer see this.
