### ISSUE TITLE
Keys requiring ALT-GR don't work in ghci with the integrated terminal on Windows

### ISSUE THREAD

**Issue by jhony1104** [Microsoft/vscode#19440]
- VSCode Version: 1.8.1 _and_ 1.9.0-insider 6ba4282
- OS Version: Windows 10 1607 Pro _and_ Education

Steps to Reproduce:

1. Start `ghci` or `stack ghci` in the integrated Terminal
2. try to type anything requiring ALT-GR

related to #12444

**Comment by mousetraps** [comment]
Thanks for reporting! Just so we're on the same page... does ALT-GR not work within the integrated terminal in general, or do you only notice this issue with ghci?

cc @Tyriar

**Comment by jhony1104** [comment]
This issue only exists within ghci. Key work in the integrated terminal otherwise and work with ghci in the Windows Console.

**Comment by Tyriar** [comment]
Related: https://github.com/Microsoft/vscode/issues/13809

**Comment by Chadehoc** [comment]
This issue also exists for Powershell.

**Comment by Tyriar** [comment]
Nothing we can do here so closing it off. This would be an upstream issue in winpty https://github.com/rprichard/winpty

**Comment by rprichard** [comment]
This issue should be fixed now in upstream in winpty's master branch.
