### ISSUE TITLE
ES2015 Classes not highlighting correctly

### ISSUE THREAD

**Issue by synthecypher** [Microsoft/vscode#19442]
For some reason VSCode will not highlight the ES2015 class seen on the left in the same way it does in the traditional class on the right. Is this intended? Can I make it highlight in the same way?

![image](https://cloud.githubusercontent.com/assets/1833542/22334007/d43f13d2-e3d0-11e6-8537-712a8eb9bf58.png)

**Comment by mjbvz** [comment]
We expect somewhat different highlighting in these cases, but the difference should not be that drastic. Can you please provide:

* What color theme you are using?
* Are you using any extension? Try running code with `--disable-extensions` to see if this still repos.
* Provide the example code for the two files.

Thanks

**Comment by mjbvz** [comment]
@synthecypher Please provide the requested information so that we can investigate this

**Comment by synthecypher** [comment]
@mjbvz I was using the [*Base16 Themes*](https://marketplace.visualstudio.com/items?itemName=AndrsDC.base16-themes) extension.

It appears to no longer be a problem, maybe they fixed it.
