### ISSUE TITLE
Performance regression while starting up

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#19443]
Our telemetry data shows that the startup performance of `1.9.0-insider` is worse than that of `1.8.1`. Drilling into this shows that it takes a lot longer to get the extension host ready event, so the timespan between the `perfBeforeExtensionLoad` and `perfAfterExtensionLoad` timer ticks. The profiler shows that the configuration service takes ~230ms doing something once the extensions have registered their configurations (with 1.8 this takes ~30ms).

![screen shot 2017-01-26 at 15 03 24](https://cloud.githubusercontent.com/assets/1794099/22334005/329e0ff2-e3d9-11e6-9ae8-3cc8a3dd9744.png)

The offender is `lookup` and isn't new to me. I might be wrong but I remember that there was already a similar perf issue a while back. 

![screen shot 2017-01-26 at 15 01 41](https://cloud.githubusercontent.com/assets/1794099/22333999/2d2e7854-e3d9-11e6-9a67-c427fc4d9ea8.png)

[master-exthost-ready.cpuprofile.zip](https://github.com/Microsoft/vscode/files/732456/master-exthost-ready.cpuprofile.zip)
[release1.8-exthost-ready.cpuprofile.zip](https://github.com/Microsoft/vscode/files/732457/release1.8-exthost-ready.cpuprofile.zip)

**Comment by bpasero** [comment]
Maybe some recent changes to the configuration service model makes this more expensive now? @sandy081 did some heavy refactoring in that area to support language specific settings.

**Comment by sandy081** [comment]
Refactoring did not change any logic of how the configuration is being loaded before and now. It introduced proper models and logic separation. AFIK it should not impact. Quick thingies that come from my mind is following additional steps during start up

- Security fix needed to re-filter (note only re-filter and not parsing) the workspace config contents whenever there is a base config change.
- In the blamed look up method, workspace value and consolidate value are cloned now which were not before.

**Comment by sandy081** [comment]
Worked with @jrieken and figured out the [root cause](https://github.com/microsoft/vscode/blob/master/src/vs/platform/configuration/common/model.ts#L276). 

Will provide the fix

**Comment by bpasero** [comment]
Awesome-

**Comment by jrieken** [comment]
Verified with a built from master
