### ISSUE TITLE
Code suggestions not appearing for function parameters in C

### ISSUE THREAD

**Issue by JeffreyCA** [Microsoft/vscode#19445]
- VSCode Version: 1.8.1
- OS Version: macOS 10.12.3

Steps to Reproduce:

1. Define a C function with multiple parameters (any type)
2. In the function body, begin to type one of the parameter names

Expected:

Parameter name should appear in suggestions.

Observed:

Parameter name does not appear in suggestions.

**Comment by sean-mcmanus** [comment]
Do you have the C++ extension installed? Is the autocomplete setting enabled (the default)? The C++ autocomplete (and Go to definition, etc.) do not work on local variables currently. We're working on an implementation that should fix it.

**Comment by JeffreyCA** [comment]
Yes, I have it installed and the autocomplete setting is as follows:

`"C_Cpp.autocomplete": "Default",`

Here is a sample of autocomplete dialog:

<img width="592" alt="screenshot 2017-01-26 12 55 48" src="https://cloud.githubusercontent.com/assets/9157833/22343682/0270b364-e3c7-11e6-8572-9ffbe3754254.png">
<img width="439" alt="screenshot 2017-01-26 12 55 53" src="https://cloud.githubusercontent.com/assets/9157833/22343683/02725c00-e3c7-11e6-9413-440b65fc8da4.png">

So currently method parameters do not work? Is there somewhere I can track the issue? Thanks.
