### ISSUE TITLE
VSCode is ignoring H:\.gitconfig

### ISSUE THREAD

**Issue by BrianL-STCU** [microsoft/vscode#194450]
Type: <b>Bug</b>

1. Open the Source Control panel
2. Hundreds of files that should be ignored are listed as Updated ![Source Control panel showing hundreds of files that should be ignored](https://github.com/microsoft/vscode/assets/20843057/042acb48-43a3-4fa2-971d-580e5b1d64f7)
3. Try to commit a change, get an error 
![Visual Studio Code: Make sure you configure your "user.name" and "user.email" in git.](https://github.com/microsoft/vscode/assets/20843057/8eade2d4-774e-4837-b87a-943710fdb803)
4. Check git via the command line:

    ```text
    PS>git status        
    On branch master
    Your branch is up to date with 'origin/master'.

    nothing to commit, working tree clean
    PS>git config user.name
    Brian Lalonde
    PS>git config user.email
    ███████@██████████ (my valid email)
    ```

I can't help but notice that this has started not long after some pretty aggressive permission blocking on network drives, and my _.gitconfig_ is on a mapped network drive.

VS Code version: Code 1.82.2 (abd2f3db4bdb28f9e95536dfa84d8479f1eb312d, 2023-09-14T05:55:25.390Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|12th Gen Intel(R) Core(TM) i7-1265U (12 x 2688)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.69GB (1.86GB free)|
|Process Argv|-n --crash-reporter-id 28c14034-c924-4116-b63d-855abe2e2cb7|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (42)</summary>

Extension|Author (truncated)|Version
---|---|---
markdown-mermaid|bie|1.20.0
insert-unicode|bru|0.15.1
flip|Chr|0.0.4
vscode-markdownlint|Dav|0.52.0
githistory|don|0.6.20
EditorConfig|Edi|0.16.4
vscode-github-actions|git|0.26.2
vscode-pull-request-github|Git|0.72.0
vscode-guid|hea|1.7.0
rest-client|hum|0.25.1
azure-dev|ms-|0.7.0
vscode-azureappservice|ms-|0.25.0
vscode-azurecontainerapps|ms-|0.5.1
vscode-azurefunctions|ms-|1.13.1
vscode-azureresourcegroups|ms-|0.7.5
vscode-azurestaticwebapps|ms-|0.12.2
vscode-azurestorage|ms-|0.15.3
vscode-azurevirtualmachines|ms-|0.6.5
vscode-bicep|ms-|0.21.1
vscode-cosmosdb|ms-|0.19.4
csdevkit|ms-|0.4.10
csharp|ms-|2.4.2
dotnet-interactive-vscode|ms-|1.0.4461040
vscode-dotnet-runtime|ms-|1.8.0
vscodeintellicode-csharp|ms-|0.1.26
jupyter|ms-|2023.8.1002501831
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.17
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-slideshow|ms-|0.1.5
azure-account|ms-|0.11.5
powershell|ms-|2023.6.0
vscode-node-azure-pack|ms-|1.2.0
vscode-octopusdeploy|Oct|0.1.4
vscode-xml|red|0.26.1
vscode-yaml|red|1.14.0
todotasks|san|0.5.0
gitmoji-vscode|sea|1.2.4
vscode-mermaid-editor|tom|0.19.1
win-ca|uko|3.5.0
markdown-all-in-one|yzh|3.5.1
cursorCharCode|zei|0.2.4

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263:30335439
vscoreces:30445986
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
py29gd2263cf:30792227
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyonecf:30548226
3biah626:30602489
f6dab269:30613381
showlangstatbar:30737416
0bi6i642:30841073
03d35959:30757346
pythonfmttext:30731395
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
pythonnosmt12:30797651
pythonidxptcf:30805731
pythonnoceb:30805159
copilotsettingc:30839828
asynctok:30821568
dsvsc013:30795093
dsvsc014:30804076
diffeditorv2:30821572
pythonmpsinfo:30842941
dsvsc015:30845448
pythonfb280951cf:30830811

```

</details>

**Comment by gjsjohnmurray** [comment]
Info at https://code.visualstudio.com/docs/setup/windows#_working-with-unc-paths suggests using a mapped drive to overcome UNC path restrictions, but does your problem remain if you also follow the steps to permit the UNC target of your mapped drive?

Any clues in the Git channel of the Output tab on the Panel?

**Comment by BrianL-STCU** [comment]
I'm already using a mapped drive letter (H:) for the drive that has my _.gitconfig_, but it appears that after the last update, the problem has resolved itself. Thanks!

**Comment by gjsjohnmurray** [comment]
Thanks for confirming 1.83 has resolved this for you. 

BTW, you wrote 

> 2\. Hundreds of files that should be ignored are listed as Updated

I believe that the `U` letter is short for Untracked.
