### ISSUE TITLE
textEditor.insertSnippet: snippet not inserted when text is the same

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode#19449]
Testing #15952

Create the following extension:
```typescript

'use strict';
import * as vscode from 'vscode';

export function activate(context: vscode.ExtensionContext) {
    let disposable = vscode.commands.registerCommand('extension.sayHello', () => {
        if (!vscode.window.activeTextEditor) {
            console.log('No editor');
            return;
        }
        let doc= vscode.window.activeTextEditor.document;
        let p = vscode.window.activeTextEditor.insertSnippet(new vscode.SnippetString('for (var ${1:i}=0; ${1:i}<len; ${1:i}++) { $0 }'), new vscode.Position(0, 0));
        p.then(_ => {
            vscode.window.activeTextEditor.insertSnippet(new vscode.SnippetString('for (var ${1:i}=0; ${1:i}<len; ${1:i}++) { $0 }'), new vscode.Position(0, 0));
        });
    });

    context.subscriptions.push(disposable);
}
```
- run the extension, open an editor and run the 'hello world' command.
Only one snippet is inserted. 

- When changing the snippet text of the second snippet,  (e.g. 'let to 'var') more is inserted, except for the common prefix.

**Comment by jrieken** [comment]
Well, `insertSnippet` returns a promise on which you must wait until further changes are performed. I'll add a guard to make sure the second call is a noop when the version numbers don't match anymore

**Comment by aeschli** [comment]
Ok, I updated the code example above to use the promise. Bug is still there.

**Comment by jrieken** [comment]
I guess that happens because the editor is still in snippet mode. Unsure if, the promise should only resolve when snippet mode has finished, if snippet mode should be aborted and restarted, or if the second snippet should be blocked (promise resolving to `false`)
