### ISSUE TITLE
Splitting task terminal on web fails with error

### ISSUE THREAD

**Issue by colin-grant-work** [microsoft/vscode#194439]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.82.2
- OS Version: Windows 10

Steps to Reproduce:

0. From a Windows machine,
1. In something like GitHub Codespaces
2. Create a task with a configuration like this:
```
{
    "version": "2.0.0",
    "tasks": [
        {
           "type": "shell",
           "label": "Do little",
           "command": "sleep 30 && echo 'Good sleep'",
           "options": {
            "cwd": "/repo"
           }
        }
    ]
}
```
3. Run that configuration, and try to split the task terminal it runs in by clicking the icon
![image](https://github.com/microsoft/vscode/assets/62660806/d9129f84-4724-4d6d-af1c-6aea306da71e)
4. No new terminal will be spawned and the dev tools will show an error like this, which may also appear in a notification:
![image](https://github.com/microsoft/vscode/assets/62660806/a5b557df-1727-475f-9f51-23fa32972033)

When I debug the case, it appears that when the code reaches here,

https://github.com/microsoft/vscode/blob/411d2984aea5080fe0cf3c00b13e12732b2caa62/src/vs/workbench/contrib/terminal/browser/terminalService.ts#L1070

 the two options are the same, but with different path separators. `shellLaunchConfig.cwd` has a Windows-type path separator while `parent.shellLaunchConfig.cwd.path` has a Posix path separator:

![image](https://github.com/microsoft/vscode/assets/62660806/c13ccabd-b136-4a42-9f77-efd31133df2d)

Since the former is favored over the latter, a 'malformed' path is passed to the `URI.from` call.

**Comment by meganrogge** [comment]
works for me on web, when using your steps

possible something's been fixed 

![Image](https://github.com/microsoft/vscode/assets/29464607/4a3557f7-d24e-47f4-90eb-e63fbfd0edf5)

**Comment by colin-grant-work** [comment]
@meganrogge, I'm still able to reproduce with a new Codespace cerated a few moments ago:

![image](https://github.com/microsoft/vscode/assets/62660806/ffe14537-6279-4f2b-b7aa-4d3b76f97851)

**Comment by meganrogge** [comment]
Hard to investigate when I cannot reproduce. Thoughts @Tyriar ?

![Image](https://github.com/microsoft/vscode/assets/29464607/15c9da5b-dbca-4255-892b-266be0a15f1d)
