### ISSUE TITLE
Don't sync the visibility part of workbench.panel.pinnedPanels

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#194489]
I believe the `workbench.panel.pinnedPanels` storage key currently ends up triggering sync every time a view visibility is changed:

https://github.com/microsoft/vscode/blob/9df7d42604f1663599fa6f312e5a042742b0cd34/src/vs/workbench/browser/parts/panel/panelPart.ts#L878-L880

Can we split out the visibility part here? As a user I would only expect the pinned part to be synced anyway.

**Comment by sandy081** [comment]
Agreed, this is not needed to be synced.
