### ISSUE TITLE
'Show' vs. 'reveal' word in settings and commands

### ISSUE THREAD

**Issue by borekb** [Microsoft/vscode#19441]
I got recently confused by this:

- There is an explorer.auto**Reveal** settings that implements this behavior: https://github.com/Microsoft/vscode/issues/3062. I set that value to `false`.
- To **reveal** the file in manually, I searched the command palette and indeed found "**Reveal** Active File in Windows Explorer".
- I didn't notice that it mentions _Windows_ Explorer specifically (my bad) and was confused by the resulting action.
- I had somewhat hard time to find the right command. It turned turned out to be "**Show** Active File in Explorer".

I think that more consistent would be if **reveal** a file would always mean in VSCode's explorer while for opening anything externally, I'd use the word **open**. For example, "Open Active File in Windows Explorer".

**Comment by borekb** [comment]
Related issues:

- _Provide an option to stop scrolling revealing active file in explorer_ https://github.com/Microsoft/vscode/issues/3062
- _'Show active file in explorer' should be 'Reveal active file in explorer'_ https://github.com/Microsoft/vscode/issues/5837
- _New autoReveal setting for explorer_ #5329

**Comment by bpasero** [comment]
Settled on "Reveal in Side Bar" across all OS. I left the other "Reveal in Finder" because it is also about revealing and not opening.

**Comment by antonydenyer** [comment]
In case anyone stumbles accross this the ID for it is:

```workbench.files.action.showActiveFileInExplorer```

Would be nice to have a full list of commands somewhere

**Comment by bpasero** [comment]
If you open keybindings you see a list of unassigned keys at the bottom. We plan to improve the UX around keybinding editing for this milestone though to make this easier overall.

**Comment by antonydenyer** [comment]
Thanks @bpasero 

I was looking for 'reveal' in the keybinding and was thinking this list isn't the full list. Then I ended up searching the code base for 'Reveal Active File in Side Bar' to find the ID. 

There's another strange thing about the behaviour, it seems to be sticky rather than a one time reveal.

**Comment by bpasero** [comment]
What?

**Comment by antonydenyer** [comment]
Apologies, I was being stupid. I'll edit the comment and delete this :)

**Comment by Falieson** [comment]
"explorer.autoReveal": false,

is the command and setting to be added to your user settings.json
