### ISSUE TITLE
[extension] VSTS (old TFS) integration on MacOS

### ISSUE THREAD

**Issue by ricfwolff** [microsoft/vscode#194430]
I'm not sure this is the right place to ask for it.
But I've searched everywhere and cannot find a good - or working - answer.
I guess I just want to make sure VSTS is completely abandoned indeed... :(

I work on a company that has all its source code in Azure DevOps VSTS (previously TFS) and it's not supported on VSCode. I cannot get the repositories' latest version or commit changes to it.
From the answers I found online, there was an old version of the "Azure Repos" extension that allowed that to work, but it was deprecated and the extension changed.
There are some people talking about a "Team Explorer Everywhere" app that would work on MacOS and allow some extensions to work, but that is deprecated as well. And, even installing the deprecated version, it didn't work.

So... I know most of the effort is being done towards Git integration, but lots of companies have their source code in VSTS. It would be nice to be able to get files and commit (check-in) to VSTS.

This will hardly be implemented, but it's good for future readers to know that they're not alone and this was a decision, not a random bug. 😅 

If someone knows how to actually make that work, please point me to the correct direction, as I have lost hours trying several different solutions and none worked.

Thank you!

**Comment by aeschli** [comment]
The Azure DevOps team would have to answer that.
@lszomoru Do you have any contacts?

**Comment by lszomoru** [comment]
@ricfwolff have you tried [this](https://marketplace.visualstudio.com/items?itemName=argutec.argutec-azure-repos) 3rd party extension?

**Comment by ricfwolff** [comment]
Yep, I did try that, but I keep getting Unauthorized:
![image](https://github.com/microsoft/vscode/assets/9446182/c558ca28-2ea0-4d37-b409-65ef54a6f94e)
This made me think it was deprecated as well.

But if you say this one should work, I can invest more time on debugging and/or contact their GitHub page.

**Comment by lszomoru** [comment]
@ricfwolff, I think that this extension is your best bet at this point. Looking at the extension it seems that the extension is built and published from a fork of the https://github.com/microsoft/azure-repos-vscode repository which is the original repository of the official extension that has been deprecated.
