### ISSUE TITLE
`codeActionsOnSave` missing some proposals

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode#194461]
Verifying #194437

E.g., `source.fixAll.eslint` and `source.removeUnusedImports` are missing from the proposals:

![Image](https://github.com/microsoft/vscode/assets/9205389/1d816a62-cfe8-40f3-81db-218f51914262)

**Comment by justschen** [comment]
yep! this is an issue we'll be taking a look at. duplicate of https://github.com/microsoft/vscode/issues/161284

**Comment by chrmarti** [comment]
Missing completely for notebooks:
<img width="560" alt="image" src="https://github.com/microsoft/vscode/assets/9205389/44c8ab79-ed62-4a5e-82ad-e3a58f26b3a4">

**Comment by chrmarti** [comment]
> yep! this is an issue we'll be taking a look at. duplicate of #161284

ok, closing as duplicate, thanks.
