### ISSUE TITLE
focus cell output with ctrl+down does not visually select the output

### ISSUE THREAD

**Issue by amunger** [microsoft/vscode#194432]
found testing for https://github.com/microsoft/vscode/issues/111255#issuecomment-1739961604

1. run a cell to get output
2. press ctrl+down to focus the output
:bug: visually, it looks like the cell container is focused.

**Comment by rohanshardha** [comment]
in the insiders build of 1.83.0, NVDA 2023.2 does read the output but like @amunger  said it doesn't visually focus it. Unlike NVDA JAWS 2023.2307 doesn't even read the output. And even pressing alt+F2 while using JAWS, accessible view is not even pulled up/JAWS doesn't do anything. While both of these issues are not found in version 1.81.1 with JAWS 2023.2307. Seems like VS Code bug.

**Comment by aiday-mar** [comment]
So this worked but with the keybindings `command+control+arrowDown` on Mac. Not sure if the keybinding you mentioned is the keybinding on another platform like windows?

**Comment by amunger** [comment]
yes sorry, didn't notice that mac keybinding was different 

```
primary: KeyMod.CtrlCmd | KeyCode.DownArrow,
mac: { primary: KeyMod.WinCtrl | KeyMod.CtrlCmd | KeyCode.DownArrow, },
```
