### ISSUE TITLE
Execution_Policies

### ISSUE THREAD

**Issue by Skoteh90** [microsoft/vscode#194445]
Type: <b>Bug</b>

"cannot be loaded because running scripts is disabled on this system. For more information"

Every time I set up a VS Code environment I get this, and every time it's a pain to fix because there are no straightforward accurate answers online because things keep changing.

Make this easier, every developer has to go through this step why is this not streamlined?

VS Code version: Code 1.82.2 (abd2f3db4bdb28f9e95536dfa84d8479f1eb312d, 2023-09-14T05:55:25.390Z)
OS version: Windows_NT x64 10.0.22621
Modes:

**Comment by roblourens** [comment]
I think that what you're seeing is a powershell policy, not a VS Code one
