### ISSUE TITLE
lldb no response when debugging c/c++ scripts

### ISSUE THREAD

**Issue by ehrmantraut5** [microsoft/vscode#194406]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.82.2 (Both Intel and Universal)
- OS Version: macOS 14.0
- Hardware : MacBook Pro 16" 2019 with i7 intel chip with 16gb ram

Steps to Reproduce:

1. update macOS to Sonoma
2. get newest command line tools
3. command line tools version - clang : 15.0.0 , lldb : 1500.0.22.8
4. make any c/c++ script including 2nd dimensional character array
5. make breakpoint after input and start debug with lldb
6. after you get large amount of input to character array
7. tile including local variables make spinning circle for tens of seconds
8. In task manager, lldb-mi 's cpu usage is 100% and no response
9. Can't proceed debugging there is also terrible lag whenever go down each line
10. this is same in Ventura and after reset my Mac
11. probably this occurs after updating command line tools
12. this is critical error for c/c++ developer using Mac. we can't conduct debugging with c/c++ scripts

extension : C/C++ extension Pack

**Comment by lszomoru** [comment]
Please file [this issue](https://github.com/Microsoft/vscode-cpptools/issues) in the extension's repository. Thank you!
