### ISSUE TITLE
`openLabel` not rendered for simple file dialog

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode#194519]
1. Call `vscode.window.showOpenDialog({ openLabel: 'some message' })` in a remote window or with `"files.simpleDialog.enable": true`
2. :bug: `openLabel` isn't rendered anywhere

**Comment by alexr00** [comment]
@TylerLeonhardt it looks like the quick input doesn't support overriding the label of the "OK" button. Am I reading that correctly? I know about the custom button for quick input, but I can't use it in this case because the simple file picker already uses it for something else.

**Comment by alexr00** [comment]
The simple file dialog fills the input box with the path, so `placeholder` won't work. The `title` is always set to "Open File", but we can use the open label if it's set.

**Comment by TylerLeonhardt** [comment]
Fair enough. Yeah I think it's a fair ask to be able configure the `OK` button's text. Honestly we really should have like:
* `primaryButton` (aka `ok`) - this fires the `onDidAccept` event
* `secondaryButton` (aka `custom`) - this fires the `onDidCustom` (which could be renamed to `onDidSecondary`)

or maybe any number of buttons... but that could be more cumbersome as one would need to be marked primary so to ensure something fires `onDidAccept`
