### ISSUE TITLE
Extension host should not terminate unexpectedly if an uncaughtException handler throws

### ISSUE THREAD

**Issue by ulugbekna** [microsoft/vscode#194588]
The OCaml Platform extension was registering an uncaughtException handler that rethrows the exception, which would terminate the extension host. EH shouldn't terminate on an exception from such a handler. 

cc @jrieken

**Comment by jrieken** [comment]
@ulugbekna I have tried to trigger this with a custom uncaughtException handler but was never able to do. Can you please share you repro setup so that we can get this fixed

**Comment by jrieken** [comment]
To verify:

* have an extension with code below
* load the extension
* make sure the EH doesn't crash

```ts
process.on('uncaughtException', function (err: Error) {
	console.log('HERER', err.message)
	throw new Error('Bad');
});
setInterval(() => {
	throw new Error('Hello Bad World')
}, 1000 * 8);

```
