### ISSUE TITLE
Workspace settings fail to load when opening root

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#19452]
This is the same as #18183, but for Mac/Linux instead of Windows.

- I open `/` in vscode
- Press the gear to create a launch config, fill it out and save it
- The dropdown still says "no configurations"

If I reload the window, the configs appear
If I rename a config and save it, the dropdown label doesn't update until I reload the window.

**Comment by bpasero** [comment]
I do not have a setup where I can test this properly without insane CPU activity on my VM, if someone wants to check this, PR welcome.

**Comment by bpasero** [comment]
@roblourens is this still happening?

**Comment by roblourens** [comment]
I must have been running with `sudo` before, otherwise I can't create the .vscode folder at all. But when I start with sudo, I see the same thing. 

If I relaunch not with sudo, so the launch.json is already created, then it works as expected.

This is a dumb bug...

**Comment by bpasero** [comment]
Ok, I was asking because I fixed an issue for 1.10.0 with `path.dirname` for files which are in root (like the `.vscode` folder).

**Comment by bpasero** [comment]
Closing, if someone wants to jump in, PR me.
