### ISSUE TITLE
Scroll Sync from Markdown Editor To Markdown Preview

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#19459]
From  #5047

VSCode 1.9 add scroll sync from the markdown preview to the markdown editor, along with selection view sync from the editor to the preview. The remaining feature would be: scroll the markdown editor scrolls the markdown preview

**Comment by eaglexiang** [comment]
I checked the settings where scrollEditorWithPreview is true, but no sync works.

**Comment by vladamx** [comment]
Sync seems to **only** work in workspace mode. 

You need to open folder first.

It won't work when it is context free.

**Comment by mjbvz** [comment]
@eaglexiang and @vladamx, this is unrelated to what this issue is tracking.

A bug prevented 1.9's markdown synchronization from working in some cases due to a drive letter casing issue on Windows #20064. This should be fixed in insiders and 1.9.1. If you still see problems after updating, please open a new issue and I'll take a look.

**Comment by eaglexiang** [comment]
I tried to use workspace settings instead of default settings, the sync did worked. However, I guess users would be happy if sync from editor to preview could work like from preview to editor. I mean **scroll sync** but not selection sync. Anyway, **Thank you very much! : )**

**Comment by jingniao** [comment]
vscode version is 1.10.1
when typing in
the preview page always switch back and forth between header and focus

**Comment by kachkaev** [comment]
How difficult would it be to implement this? I can try submitting a PR after a small hint.

Have been working in VSCode since the last week after switching from Atom. Still can't get used to the fact that the preview does not follow the scrolling of the markdown source. This works pretty smoothly in Atom.

**Comment by mjbvz** [comment]
@kachkaev I don't think we can't fix this until we have an API the lets an extension know the current editor viewport

**Comment by kachkaev** [comment]
Thanks @mjbvz for clarifying that, understood. It'll be awesome to see this moved out of the backlog one day – I'm sure that the markdown preview is not the only feature that can benefit!

These days there are very few bits that a bit worse in VSCode than in Atom, especially after a recent introduction of multi-project workspaces! Just a couple of more steps including this one and VSCode will leave Atom behind the [Pareto frontier](https://en.wikipedia.org/wiki/Pareto_efficiency)! 👍 😄

**Comment by sandorfr** [comment]
I noticed that having markdown preview extensions such as [https://marketplace.visualstudio.com/items?itemName=bierner.markdown-mermaid](mermaid) or [https://marketplace.visualstudio.com/items?itemName=geeklearningio.graphviz-markdown-preview](graphviz) make the scrolling a bit unpredictable. I think this something to take into account if there's rework on markdown preview scroll.
