### ISSUE TITLE
vscode.workspace.workspaceFolders is undefined when debugging an extension if the folder is open in another window

### ISSUE THREAD

**Issue by geajack** [microsoft/vscode#194551]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.82.2
- OS Version: Ubuntu 20

Steps to Reproduce:

1. Create an extension project and a launch configuration with something like the snippet below.
2. Open `some/folder` in another VSCode window.
3. Try to debug the extension.
4. `vscode.workspace.workspaceFolders` is undefined

```json
{
    "version": "0.2.0",
    "configurations": [
        {
            "args": [
                "--extensionDevelopmentPath=${workspaceFolder}",
                "/home/jack/Code/some/folder"
            ],
            "name": "Launch Extension",
            "outFiles": [
                "${workspaceFolder}/out/**/*.js"
            ],
            "request": "launch",
            "type": "pwa-extensionHost"
        }
    ]
}
```

**Comment by roblourens** [comment]
You can only have a folder open in one window at a time. If you try to open a second one, it will just open an empty window instead of opening that folder. That's what you are seeing here.
