### ISSUE TITLE
vscode snapshot tests not failing when snapshots don't match

### ISSUE THREAD

**Issue by ulugbekna** [microsoft/vscode#194570]
# Description 

My snapshot test isn't failing even when the snapshot stored and the actual value are not equal.

https://github.com/microsoft/vscode/assets/16353531/4400c161-49fc-4f18-8488-dc741bbabfd0

# Repro

1. Create a new snapshot test 
2. Run the new test, which will create a snapshot file
3. Change the output of your test to something else 
4. Run the test again - it doesn't fail

# Version

```
Version: 1.83.0-insider
Commit: 4268e464763087044d0c1b5bdd37ebbe683cadfa
Date: 2023-09-29T20:44:05.310Z
Electron: 25.8.4
ElectronBuildId: 24154031
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Darwin arm64 22.6.0
```

**Comment by connor4312** [comment]
You're missing an `await` on assertSnapshot. I admit that I forgot to do that a few times myself. Maybe we should have a lint rule for "must use/await result".
