### ISSUE TITLE
[WelcomeUX] Empty Recent section shown when only current folder in MRU list

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#19456]
Steps:
- Start with a new --user-data-dir and open a folder, such that this folder is the only folder entry in File > Open Recent.
- Recent section is shown empty

**Comment by bpasero** [comment]
I still see the recent section as being empty when I start like this:

`code-insiders --user-data-dir ./src ~/Desktop/test-js/`

**Comment by chrmarti** [comment]
That is now by design (#19473). The important part is that it is not only an empty list, which was the bug that was fixed here.
