### ISSUE TITLE
[WelcomeUX] Color of buttons on welcome page

### ISSUE THREAD

**Issue by kieferrm** [Microsoft/vscode#19454]
- VSCode Version: Code - Insiders 1.9.0-insider (6ba4282fd27bacacbf8482472a0519560720fb9c, 2017-01-26T07:26:32.304Z)
- OS Version: Darwin x64 15.6.0
- Extensions:

|Extension|Author|Version|
|---|---|---|
|vscode-docker|PeterJausovec|0.0.11|
|theme-toothpaste|aalaap|0.0.1|
|vscode-eslint|dbaeumer|1.2.0|
|githistory|donjayamanne|0.1.5|
|tslint|eg2|0.8.1|
|vscode-npm-script|eg2|0.1.8|
|vsc-travis-ci-status|felixrieseberg|1.0.5|
|Go|lukehoban|0.6.52|
|csharp|ms-vscode|1.6.2|
|debugger-for-chrome|msjsdiag|2.4.2|
|better-merge|pprice|0.5.1|
|Ruby|rebornix|0.10.4|
|java|redhat|0.0.9|
|kustovscode|seanmcbreen|0.0.1|
|php-syntax-visualizer|vscode|0.0.1|
|gitblame|waderyan|1.3.0|
|vscode-open-in-github|ziyasal|1.2.3|

---

Steps to Reproduce:

1. Use toothpaste color theme.
2. The buttons on the welcome page don't fit well with the theme. We should try to derive the color from the background color of the theme.

![screen shot 2017-01-26 at 10 05 28 am](https://cloud.githubusercontent.com/assets/4674940/22344008/36383676-e3af-11e6-8851-b57c731ab77f.png)

**Comment by bpasero** [comment]
+1 or fixing this for this sprint since we want to push our theming to broader audience and not having welcome look themed is counter productive to sell this feature.

**Comment by bpasero** [comment]
Thanks @chrmarti !

**Comment by chrmarti** [comment]
Anytime! :D

**Comment by Tyriar** [comment]
Looks great! 👌
