### ISSUE TITLE
lag with cursor and screen reader

### ISSUE THREAD

**Issue by RonnyG2121** [microsoft/vscode#194503]
Type: <b>Performance Issue</b>

Hello.

When I type in the code editor, I have a delay when I move lines with the directional arrows with my screen reader.
I don't know if I have an error in the configuration.
thanks for helping.

VS Code version: Code 1.82.2 (abd2f3db4bdb28f9e95536dfa84d8479f1eb312d, 2023-09-14T05:55:25.390Z)
OS version: Windows_NT x64 10.0.22621
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Celeron(R) N4000 CPU @ 1.10GHz (2 x 1094)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: disabled_off<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|3.83GB (0.51GB free)|
|Process Argv|C:\\Users\\RonnyG2121\\Documents\\Web\\Javascript\\Javascript.code-workspace --crash-reporter-id ebe70f17-e335-44d9-afea-bcc35f431670|
|Screen Reader|yes|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	   107	  9280	code main
    0	    82	  1440	ptyHost
    0	    79	  1200	     C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe -noexit -command "try { . \"c:\Users\RonnyG2121\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\contrib\terminal\browser\media\shellIntegration.ps1\" } catch {}"
    0	     7	  7620	     conpty-agent
    0	   153	  1452	extensionHost [1]
    0	    79	  5608	     electron-nodejs ("C:\Users\RonnyG2121\AppData\Local\Programs\Microsoft VS Code\Code.exe" --ms-enable-electron-run-as-node "c:\Users\RonnyG2121\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\json-language-features\server\dist\node\jsonServerMain" --node-ipc --clientProcessId=1452)
    0	    72	  3160	fileWatcher [1]
    0	    93	  3656	shared-process
    0	   172	  6508	window [1] (Javascript (área de trabajo) - Visual Studio Code)
    0	    40	  7936	   utility-network-service
    0	    28	  8128	   crashpad-handler
    0	   109	  8704	   gpu-process
    0	    92	  9256	window [2] (Notificador de problemas)
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (Javascript (área de trabajo) - Visual Studio Code)
|    Folder (Javascript): 516 files
|      File types: html(234) js(49) php(48) jpg(41) css(21) png(14) gif(12)
|                  json(7) code-workspace(4) DS_Store(4)
|      Conf files:;
```

</details>
<details><summary>Extensions (38)</summary>

Extension|Author (truncated)|Version
---|---|---
bs5|aja|0.7.0
vscode-intelephense-client|bme|1.9.5
vscode-mysql-client2|cwe|6.7.4
composer-php-vscode|DEV|1.39.13943
vscode-html-css|ecm|1.13.1
vscode-firefox-debug|fir|2.9.10
code-runner|for|0.12.0
vscode-pull-request-github|Git|0.72.0
vscode-language-pack-es|MS-|1.82.2023091309
csharp|ms-|2.4.4
vscode-dotnet-pack|ms-|1.0.12
vscode-dotnet-runtime|ms-|1.8.0
vscode-dotnet-sdk|ms-|0.8.0
vscode-postgresql|ms-|0.3.0
autopep8|ms-|2023.6.0
isort|ms-|2023.10.1
python|ms-|2023.16.0
vscode-pylance|ms-|2023.9.30
jupyter|ms-|2023.8.1002501831
jupyter-renderers|ms-|1.0.17
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-slideshow|ms-|0.1.5
remote-wsl|ms-|0.81.7
cmake-tools|ms-|1.15.31
cpptools|ms-|1.17.5
cpptools-extension-pack|ms-|1.3.0
vscode-thunder-client|ran|2.12.4
java|red|1.23.0
LiveServer|rit|5.7.9
intellicode-api-usage-examples|Vis|0.2.8
vscodeintellicode|Vis|1.2.30
vsc-php-snippets|vsc|0.0.30
vscode-java-debug|vsc|0.54.0
vscode-java-dependency|vsc|0.23.1
vscode-java-pack|vsc|0.25.14
vscode-java-test|vsc|0.40.0
vscode-maven|vsc|0.42.0
php-debug|xde|1.33.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263cf:30335440
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
py29gd2263cf:30792227
vscaat:30438848
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyonecf:30548226
282f8724:30602487
f6dab269:30613381
showlangstatbar:30737416
pythonfmttext:30731395
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
pythonnosmt12:30797651
pythonidxpt:30805730
pythonnoceb:30805159
dsvsc013:30795093
dsvsc014:30804076
diffeditorv1:30821571
dsvsc015:30845448

```

</details>

**Comment by meganrogge** [comment]
If you can, a gif would be appreciated so I'm sure I know what you mean by "move lines with the directional arrows"

**Comment by RonnyG2121** [comment]
It's when I move to read my code that I wrote.When scrolling in the editor to read the code, a delay occurs when I scroll.I have to move several times for the reader to tell me what is on the next line, since it repeats what is on the line it was on several times.  Enviado desde Correo para Windows De: Megan RoggeEnviado: viernes, 29 de septiembre de 2023 21:12Para: microsoft/vscodeCC: Ronny Gonzalez; AuthorAsunto: Re: [microsoft/vscode] lag with cursor and screen reader (Issue #194503) If you can, a gif would be appreciated so I'm sure I know what you mean by "move lines with the directional arrows"—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by meganrogge** [comment]
are you using JAWS or NVDA? Sometimes JAWS has some problems.

**Comment by RonnyG2121** [comment]
I use NVDA in the last version

**Comment by meganrogge** [comment]
@rperez030 do you experience a lag when navigating in an editor with the cursor? I cannot reproduce. I'm wondering if it's maybe something with the NVDA configuration?

**Comment by RonnyG2121** [comment]
Yes I do. I'm going to uninstall the reader to configure it from 0, since I don't understand where the problem comes from

**Comment by meganrogge** [comment]
@RonnyG2121 are you still experiencing the issue?
