### ISSUE TITLE
Search: Exclude setting is not being respected in my workspace.

### ISSUE THREAD

**Issue by fmotion1** [microsoft/vscode#194534]
Does this issue occur when all extensions are disabled?: Yes/No
Yes

- VS Code Version: 
Version: 1.82.2 (user setup)
Commit: abd2f3db4bdb28f9e95536dfa84d8479f1eb312d
Date: 2023-09-14T05:55:25.390Z
Electron: 25.8.1
ElectronBuildId: 23779380
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.19045

- OS Version: 
Windows 10 Pro x64 Version 22H2 (Build 19045.3448)

Steps to Reproduce:

1. Add workspace folders to the Search: Exclude setting:

![Code_jwUfH9QIIh](https://github.com/microsoft/vscode/assets/33441569/63ac05cd-1e8a-4785-8132-bf8d82f1fe66)

2. Perform a search and notice that search results are still returning results from the excluded folders:

![bikC9x1ug3](https://github.com/microsoft/vscode/assets/33441569/3718c77a-e8f0-49ae-84f1-cb810d7e603a)

3. Just to add some additional information, this is my workspace settings file:

![Code_qXfovJYeWY](https://github.com/microsoft/vscode/assets/33441569/1219182f-453a-4440-b204-657d693d14e8)

Am I doing something wrong? Why isn't this working?

**Comment by andreamah** [comment]
There currently isn't any way of excluding a whole workspace root in a multi-root workspace from those settings. You'd need to use the `files to exclude` field in the search widget and exclude it like `./00 External/*`. Adding the ability to exclude in `search.exclude` is tracked here https://github.com/microsoft/vscode/issues/50638

/duplicate https://github.com/microsoft/vscode/issues/50638
