### ISSUE TITLE
Emmet expands dots in PHP comments to unrelated elements on Enter

### ISSUE THREAD

**Issue by rusproject** [microsoft/vscode#194529]
Hello!

Emmet snippets behave strangely when Emmet is enabled (with default settings), particularly when trying to use the "." (dot character) inside PHPDoc blocks or in comments. When you type a dot and hit `Enter` to add a new line, Emmet expands the dot into random elements based on the preceding word.

Here's a demonstration:

https://github.com/microsoft/vscode/assets/62891105/20d88367-4c12-4c61-ab4b-b31cccdd4790

As you can see, when Emmet encounters the `object.` sequence inside a PHPDoc block, it expands it into an `<object>` tag. This behavior is somewhat understandable; there might be cases where someone would find it useful. However, the issue worsens when using Cyrillic characters: sequences like `и т.д.` expand into a `<div>` for no apparent reason.

Is there a way to disable "expand on Enter"? I only see an "Expand on Tab" setting that can be disabled.

Thanks.

**Comment by alexchexes** [comment]
Can confirm that the behavior is easily reproducible in `PHP` and `Vue` files with the default VSCode settings:

https://github.com/microsoft/vscode/assets/49966773/86b708f4-894a-41e9-b790-bbeb730853ef


https://github.com/microsoft/vscode/assets/49966773/11c29818-bb73-49c5-a541-6a48a2be0766


To reproduce, all you need is to have latest letter in the comment line to be Cyrillic (possibly other Unicode character). Or start typing dot (`.`) on a new line inside the comment like this:


https://github.com/microsoft/vscode/assets/49966773/58dfbb7d-f4eb-45a6-931b-33cf8d629a4f

**Comment by rzhao271** [comment]
I'm considering this a duplicate of https://github.com/microsoft/vscode/issues/51537
