### ISSUE TITLE
Settings pane is blank unless reload the window

### ISSUE THREAD

**Issue by wein2001** [microsoft/vscode#194579]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.82.2 
- OS Version: Windows 10.0.22621.2361

Steps to Reproduce:
![test](https://github.com/microsoft/vscode/assets/146553949/425ebeab-182a-4292-8cbd-6d8d881b471d)

**Comment by rzhao271** [comment]
Any output in the devtools console during the first load?

To get to the devtools console, press Ctrl+Shift+P to open the command palette, and then run the "Developer: Toggle Developer" Tools command.

**Comment by wein2001** [comment]
![test](https://github.com/microsoft/vscode/assets/146553949/e5bbccd4-c04d-4b44-aa1b-0b6307aea0cb)

I've found that this problem occurs when I'm not connected to the internet, and it shows up fine when connected.

**Comment by rzhao271** [comment]
I'm unable to reproduce the issue. Does it occur with extensions disabled?

**Comment by wein2001** [comment]
yes

**Comment by rzhao271** [comment]
Got it. What must've happened last time was my device reconnected me to the Internet while I was confirming the issue.
