### ISSUE TITLE
Vscode crashes(code 132) with "disable-chromium-sandbox" enabled in argv.json

### ISSUE THREAD

**Issue by krisharrison** [microsoft/vscode#194575]
Does this issue occur when all extensions are disabled?: Yes

System Info
Kernel version: 6.5.5-200.fc38.x86_64
Fedora 38
GNOME 44.5
Window Manager: Mutter
Shell: bash 5.2.15

Vs Code Extensions:
C/C++ v1.17.5
Code Runner v0.12.0
Dev Containers v0.309.0
Docker v1.26.1
Embedded Tools v0.7.0
Go v0.39.1
isort 2023.v10.1
Kubernetes v1.3.15
Live Server v5.7.9
MySql Management Tool v0.4.1
Pylance v2023.9.30
Python v2023.16.0
Remote SSH 0.106.4
Remote - SSH: Editing Configuration Files v0.86.0
Remote - Tunnels v1.4.3
Remote Development v0.24.0
Remote Explorer v0.4.1
Rust Syntax v0.6.1
Rust-analyzer v0.3.1673
Serial Monitor v0.10.0
SQL Tools v0.29.9

VS Code Version: 182.2
I initially had an issue with running any commands with root privileges in the Vs Code terminal. Used the 'Disable Chromium Sandbox' workaround provided by the Updates section from Vs Code site: https://code.visualstudio.com/updates/v1_80.

I added 'Disable Chromium Sandbox' to the bottom of the ~/.vscode/argv.json file:
![arvjson_enabled](https://github.com/microsoft/vscode/assets/33849103/cae45736-b9d6-4329-9255-598c3fe8d37a)

After closing Vs Code and relaunching the application, I received the error code 132:
![Vscode_error](https://github.com/microsoft/vscode/assets/33849103/358e238f-4555-44ce-9c39-c2f59bcd044e)

When commenting the 'Disable Chromium Sandbox' line out, Vs Code launches successfully again. Even though the line 'Disable Chromium Sandbox' is commented out in the ~/.vscode/argv.json file, I now have root privileges. This issue also occurs with the code-insider version.

Linux journal logs from VS Code Crashing:
Sep 29 19:55:37 fedora code.desktop[9321]: [0929/195537.211209:ERROR:file_io_posix.cc(152)] open /home/kh/.config/Code/Crashpad/pending/b693e937-d558-4750-bf82-0bcfbd472012.lock: File exists (17)
Sep 29 19:55:37 fedora code.desktop[9383]: [9383:0929/195537.506758:ERROR:platform_shared_memory_region_posix.cc(214)] Creating shared memory in /dev/shm/.org.chromium.Chromium.25lfL8 failed: No such file or directory (2)
Sep 29 19:55:37 fedora code.desktop[9383]: [9383:0929/195537.506910:ERROR:platform_shared_memory_region_posix.cc(217)] Unable to access(W_OK|X_OK) /dev/shm: No such file or directory (2)
Sep 29 19:55:37 fedora code.desktop[9383]: [9383:0929/195537.506956:FATAL:platform_shared_memory_region_posix.cc(219)] This is frequently caused by incorrect permissions on /dev/shm.  Try 'sudo chmod 1777 /dev/shm' to fix.
Sep 29 19:55:37 fedora audit[9383]: ANOM_ABEND auid=1000 uid=1000 gid=1000 ses=3 subj=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023 pid=9383 comm="code" exe="/usr/share/code/code" sig=4 res=1
Sep 29 19:55:37 fedora code.desktop[9321]: [0929/195537.518503:ERROR:directory_reader_posix.cc(42)] opendir /home/kh/.config/Code/Crashpad/attachments/bd5caa4b-d14a-4bf3-a486-e538fba6a6da: No such file or directory (2)
Sep 29 19:55:37 fedora kernel: traps: code[9383] trap invalid opcode ip:55bb047b0e05 sp:7ffc7a7fe4a0 error:0 in code[55bb014e9000+72ec000]
Sep 29 19:55:37 fedora audit: BPF prog-id=114 op=LOAD
Sep 29 19:55:37 fedora audit: BPF prog-id=115 op=LOAD
Sep 29 19:55:37 fedora audit: BPF prog-id=116 op=LOAD
Sep 29 19:55:37 fedora systemd[1]: Started systemd-coredump@2-9402-0.service - Process Core Dump (PID 9402/UID 0).
Sep 29 19:55:37 fedora audit[1]: SERVICE_START pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='unit=systemd-coredump@2-9402-0 comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
Sep 29 19:55:37 fedora audit[1]: SERVICE_START pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='unit=systemd-hostnamed comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
Sep 29 19:55:37 fedora systemd[1]: Started systemd-hostnamed.service - Hostname Service.
Sep 29 19:55:37 fedora systemd-coredump[9404]: Process 9383 (code) of user 1000 dumped core.
Sep 29 19:55:37 fedora systemd[1]: systemd-coredump@2-9402-0.service: Deactivated successfully.
Sep 29 19:55:37 fedora audit[1]: SERVICE_STOP pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='unit=systemd-coredump@2-9402-0 comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
Sep 29 19:55:37 fedora code.desktop[9300]: [main 2023-09-29T23:55:37.907Z] CodeWindow: renderer process gone (reason: crashed, code: 132)
Sep 29 19:55:37 fedora audit: BPF prog-id=116 op=UNLOAD
Sep 29 19:55:37 fedora audit: BPF prog-id=115 op=UNLOAD
Sep 29 19:55:37 fedora audit: BPF prog-id=114 op=UNLOAD
Sep 29 19:55:38 fedora code.desktop[6714]: [main 2023-09-29T23:55:38.413Z] Extension host with pid 6861 exited with code: 0, signal: unknown.
Sep 29 19:55:38 fedora systemd[3720]: app-gnome-code-6714.scope: Consumed 1min 15.063s CPU time.
Sep 29 19:55:38 fedora abrt-server[9441]: Package 'code' isn't signed with proper key
Sep 29 19:55:38 fedora abrt-server[9441]: 'post-create' on '/var/spool/abrt/ccpp-2023-09-29-19:55:38.208013-9383' exited with 1
Sep 29 19:55:38 fedora abrt-server[9441]: Deleting problem directory '/var/spool/abrt/ccpp-2023-09-29-19:55:38.208013-9383'
Sep 29 19:55:38 fedora code.desktop[9321]: [0929/195538.545397:ERROR:file_io_posix.cc(152)] open /home/kh/.config/Code/Crashpad/pending/b693e937-d558-4750-bf82-0bcfbd472012.lock: File exists (17)
Sep 29 19:55:39 fedora code.desktop[9300]: [9300:0929/195539.392870:ERROR:service_worker_storage.cc(2016)] Failed to delete the database: Database IO error

ACTION: Launch VsCode with '"disable-chromium-sandbox":' set to True in the argv.json
EXPECTED: Vs Code to launch
OBSERVED: Vs Code crashes, displaying error code 132. Commenting the  '"disable-chromium-sandbox" attribute out in the ~/.vscode/argv.json file allows the application to launch, but I still have root privileges even though the attribute is commented out completely

Steps to Reproduce:
1. Disable all VsCode extensions 
2. Add '"disable-chromium-sandbox": true' to the ~/.vscode/argv.json file 
3. Close the VSCode Desktop application
4. Attempt to reopen the  VSCode Desktop Application
5. VS Code displays an error 'Code 132'
6. Comment out the "disable-chromium-sandbox": true' line in the ~/.vscode/argv.json file. 
7. Launch the Vs Code application again
8. Open the terminal, run a command with sudo.

**Comment by deepak1556** [comment]
Can you clarify if you are launching VSCode as a sudo user or is the issue only about launching sudo programs from the VSCode terminal ? If it is the latter, then you don't require to add `disable-chromium-sandbox`. Based on the logs the runtime is unable to create shared memory regions very likely permission issues `This is frequently caused by incorrect permissions on /dev/shm`, if you are unable to fix permission issue then launch with `--disable-dev-shm-usage`.

**Comment by deepak1556** [comment]
Thanks for clarifying, you can remove `'disable-chromium-sandbox'` if you are not launching VSCode itself as sudo user.
