### ISSUE TITLE
You're running in a GNOME environment but the OS keyring is not available for encryption.

### ISSUE THREAD

**Issue by Delicious-Bacon** [microsoft/vscode#194530]
Does this issue occur when all extensions are disabled?: **Yes**/No

- VS Code Version: 
```
$ code --version
1.82.2
abd2f3db4bdb28f9e95536dfa84d8479f1eb312d
x64
```

- OS Version: 
```
$ cat /etc/os-release
NAME="Rocky Linux"
VERSION="9.2 (Blue Onyx)"
ID="rocky"
ID_LIKE="rhel centos fedora"
VERSION_ID="9.2"
PLATFORM_ID="platform:el9"
PRETTY_NAME="Rocky Linux 9.2 (Blue Onyx)"
ANSI_COLOR="0;32"
LOGO="fedora-logo-icon"
CPE_NAME="cpe:/o:rocky:rocky:9::baseos"
HOME_URL="https://rockylinux.org/"
BUG_REPORT_URL="https://bugs.rockylinux.org/"
SUPPORT_END="2032-05-31"
ROCKY_SUPPORT_PRODUCT="Rocky-Linux-9"
ROCKY_SUPPORT_PRODUCT_VERSION="9.2"
REDHAT_SUPPORT_PRODUCT="Rocky Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="9.2"
```

## Issue 
VSCode requires login on start each time a new window is open.

Error notification upon logging in:
```
You're running in a GNOME environment but the OS keyring is not available for encryption.
Ensure you have gnome-keyring or another libsecret compatible implementation installed and running.
```

I have `gnome-keyring` installed and running:
```
$ gnome-keyring version
gnome-keyring: 40.0
```

Following [docs](https://code.visualstudio.com/docs/editor/settings-sync#_troubleshooting-keychain-issues) led me to open an issue.

Verbose log:
```
$ code --verbose --vmodule="*/components/os_crypt/*=1" | grep -Ei "key_storage_"
[17413:0930/095213.824691:VERBOSE1:key_storage_util_linux.cc(54)] Password storage detected desktop environment: GNOME
[17413:0930/095214.748536:VERBOSE1:key_storage_util_linux.cc(54)] Password storage detected desktop environment: GNOME
[17413:0930/095214.748543:VERBOSE1:key_storage_linux.cc(128)] Selected backend for OSCrypt: GNOME_ANY
[17413:0930/095214.749140:WARNING:key_storage_linux.cc(183)] OSCrypt tried Libsecret but couldn't initialise.
[17413:0930/095214.749195:WARNING:key_storage_linux.cc(196)] OSCrypt tried Keyring but couldn't initialise.
[17413:0930/095214.749208:VERBOSE1:key_storage_linux.cc(148)] OSCrypt did not initialize a backend.
```

If it's worth anything, `libsecret` is installed:
```
$ sudo dnf install libsecret
Last metadata expiration check: 0:59:18 ago on Sat 30 Sep 2023 09:09:51 AM CEST.
Package libsecret-0.20.4-4.el9.x86_64 is already installed.
```

Launching it with argument `code --password-store="gnome"` does not change anything.

`password-store` field in `argv.json` is not allowed:
![image](https://github.com/microsoft/vscode/assets/78080236/c1f3a1dd-1d86-4646-996d-9754d772ba10)

**Comment by TylerLeonhardt** [comment]
The logs are helpful but not _so_ helpful

> [17413:0930/095214.749140:WARNING:key_storage_linux.cc(183)] OSCrypt tried Libsecret but couldn't initialise.
> [17413:0930/095214.749195:WARNING:key_storage_linux.cc(196)] OSCrypt tried Keyring but couldn't initialise.

You've configured your client correctly because it is `GNOME_ANY` getting picked up.

@deepak1556 any ideas on how we could get more logs on what's going on.

**Comment by Delicious-Bacon** [comment]
So, this is what I had to do:
1. Make sure dbus service is running: `service dbus status`
2. Export bus address to DBUS_SESSION_BUS_ADDRESS environment variable: `export $(dbus-launch)`

This is probably because I'm running a Rocky Linux.
