### ISSUE TITLE
can't copy description on completionUI

### ISSUE THREAD

**Issue by BleyChen** [Microsoft/vscode#1945]
I am developing an plugin for vscode ,Anyone know why can't copy description on completionUI ,where I can found the code in vscode souce that deal with that ?
![copyclouse](https://cloud.githubusercontent.com/assets/15098626/12260166/27b8ce10-b955-11e5-98fc-c5b0c00b16ec.png)

**Comment by isidorn** [comment]
This was just fixed yesterday and will be available with the January release cc19a2d
@alexandrudima fyi :smile:

**Comment by joaomoreno** [comment]
@BleyChen says:

> #1945 ,anyone know when this feature will release?

**Comment by alexandrudima** [comment]
@joaomoreno I don't see how cc19a2d could fix copying a description from the suggestWidget

**Comment by isidorn** [comment]
My mistake, I thought that allowing content widgets to be selectable will solve this issue. But suggest widget uses the tree which disables selection.

**Comment by joaomoreno** [comment]
@BleyChen You can select the text, but you can't copy. Did I get this correctly?

**Comment by BleyChen** [comment]
@joaomoreno  i can't select the text and also can't copy

**Comment by joaomoreno** [comment]
Closing as not supported.
