### ISSUE TITLE
Warning for c_cpp_properties.json

### ISSUE THREAD

**Issue by neilyoung** [Microsoft/vscode#19450]
- VSCode Version: Version 1.9.0-insider (1.9.0-insider)
- OS Version: Mac OSX Sierra

Steps to Reproduce:

1. Install cpp extension cpptools

2. Create a c_cpp_properties.json by following the instructions here https://code.visualstudio.com/docs/languages/cpp

3.Watch problem output. I get this warning/error there
file: 'file:///Users/me/Documents/Arduino/Navimote/.vscode/c_cpp_properties.json'
severity: 'Warnung'
message: 'Problems loading reference 'file:///Users/me/.vscode-insiders/extensions/ms-vscode.cpptools-0.10.0/boolean': Unable to load schema from '/Users/me/.vscode-insiders/extensions/ms-vscode.cpptools-0.10.0/boolean': '
at: '1,1'
source: ''

**Comment by sean-mcmanus** [comment]
This is a bug with our C++ extension (0.10.0). The warning shown should have no negative effect. We'll have a fix in the next update. Removing lines 62-65 from c_cpp_properties.schema.json should remove the warning.

**Comment by neilyoung** [comment]
Thanks. I don't have such a long file. Mine is just this:

> 
{

    "configurations": [
        {
            "name": "Mac",
            "includePath": 
				["/Users/me/.platformio/packages/framework-arduinoespressif8266/cores/esp8266/", 
				"/Users/me/.platformio/packages/framework-arduinoespressif8266/libraries/",
				"/Users/me/.platformio/packages/framework-arduinoespressif8266/tools/sdk/include/"],
            "browse" : {
                "limitSymbolsToIncludedHeaders" : true,
                "databaseFilename" : ""
            }
        }
    ]
}

**Comment by sean-mcmanus** [comment]
The bug is not inside the c_cpp_properties.json it's inside the schema file that is installed inside the root of the extension folder. Your c_cpp_properties.json is okay and doesn't need to be changed. You can safely ignore the warning and closing the file should remove the warning message.

**Comment by neilyoung** [comment]
Ah ok. Thanks for elaborating

**Comment by mousetraps** [comment]
This issue was moved to Microsoft/vscode-cpptools#467
