### ISSUE TITLE
Remote explorer - Switch Remote button not working

### ISSUE THREAD

**Issue by dexslender** [microsoft/vscode#194569]
Type: <b>Bug</b>

For some reason I decided that hiding the Swich Remote button was a good idea.
To repeat this:
1.- Go to Remote Explorer section
2.- Hide the "Swich Remote" button
3.- Now, ¿how to show again?
4.- Go to more options and select "Swich Remote", vscode display an interesting error

VS Code version: Code 1.82.2 (abd2f3db4bdb28f9e95536dfa84d8479f1eb312d, 2023-09-14T05:55:25.390Z)
OS version: Windows_NT x64 10.0.22623
Modes:

![image](https://github.com/microsoft/vscode/assets/91853649/837970bf-26d5-493b-9d7b-5eebfa684549)
![image](https://github.com/microsoft/vscode/assets/91853649/0ace58f3-a200-4f88-b959-f6e0c27f20f9)

**Comment by DonJayamanne** [comment]
Not sure how to get the `Swtich Remote` menu item.
I've tried this in both local environments as well as remote containers, still do not see such an item

**Comment by alexr00** [comment]
To verify:
1. Install at least 2 extensions that provide remote functionality. No need to connect to a remote.
2. Open the Remote Explorer.
3. Right click on the dropdown that lists remotes at the top of the Remote Explorer
4. From the context menu that shows, choose the option to "Hide Switch Remote"
5. Verify that there's now a "Switch Remote" in the ... menu of the Remote Explorer
6. Verify that you can use that to actually switch remote
7. Verify that you can get the dropdown back by right clicking on the ... menu and selecting "Switch Remote"
