### ISSUE TITLE
More notebook scroll on execute polish

### ISSUE THREAD

**Issue by amunger** [microsoft/vscode#194516]
Ideas to experiment with:

- Don't shrink a cell while it is executing -> less jumpy as output is replaced
- change the anchor heuristic from "if the resizing cell is partially visible" to "if the cell's output will shrink out of view"
- Anchor to a focused cell if the focus is in the cell's editor

cc @rebornix

**Comment by rebornix** [comment]
For the new heuristics we are adding (growing upwards or downwards), they should probably be interrupted the moment users start to scroll, for example, if I scroll manually to a specific position, I would expect the scroll top not to change.

**Comment by amunger** [comment]
I disagree - That could mean if you have a cell focused and anchored, and you scroll to get it higher in the view, it would then start getting pushed down as the previous cell grows.

**Comment by rebornix** [comment]
> you scroll to get it higher in the view, it would then start getting pushed down as the previous cell grows

If I scroll to get it lower in the view, as I want to read the cells above, and since it's still in the view and focused/anchored, the cells I was reading will then pushed upwards, right? 

https://github.com/microsoft/vscode/assets/876920/e93672ff-a425-4751-8613-8f6e4c68dbf7
