### ISSUE TITLE
Cmd+P no longer cycles through files

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#19457]
- VSCode Version: Code - Insiders 1.9.0-insider (6ba4282fd27bacacbf8482472a0519560720fb9c, 2017-01-26T07:26:32.304Z)
- OS Version: Darwin x64 15.6.0
- Extensions:

|Extension|Author|Version|
|---|---|---|
|EditorConfig|EditorConfig|0.3.4|
|autofilename|JerryHong|0.1.3|
|vscode-docker|PeterJausovec|0.0.11|
|azure-cli|chrmarti|0.2.0|
|regex|chrmarti|0.0.7|
|vscode-eslint|dbaeumer|1.2.2|
|ghlink|dt|0.0.4|
|tslint|eg2|0.8.1|
|vscode-scss|mrmlnc|0.6.0|
|PowerShell|ms-vscode|0.8.0|
|cpptools|ms-vscode|0.9.3|
|debugger-for-chrome|msjsdiag|2.4.2|
|diff|rafaelmaiolla|0.0.1|
|vscode-open-in-github|sysoev|1.3.1|

---

Steps to Reproduce:

1. Press Cmd+P multiple times
2. Expected: Cycles through recent files
3. Actual: Stays put on first file

**Comment by bpasero** [comment]
I took it out in favour of Cmd+E/Ctrl+E. To bring it back:

{ "key": "Cmd+P", "command": "workbench.action.quickOpenNavigateNext", "when": "inQuickOpen" }

**Comment by chrmarti** [comment]
Why not keep it? Did that conflict with something?

**Comment by chrmarti** [comment]
Btw., I don't see `Cmd+E/Ctrl+E` replacing it on Mac. `Cmd+E` is bound to Find and `Ctrl+E` is bound to End.

**Comment by bpasero** [comment]
@chrmarti I restored it, please verify in todays insiders.
