### ISSUE TITLE
[WelcomeUX] Welcome page: / as recent workspace

### ISSUE THREAD

**Issue by kieferrm** [Microsoft/vscode#19453]
- VSCode Version: Code - Insiders 1.9.0-insider (6ba4282fd27bacacbf8482472a0519560720fb9c, 2017-01-26T07:26:32.304Z)
- OS Version: Darwin x64 15.6.0
- Extensions:

|Extension|Author|Version|
|---|---|---|
|vscode-docker|PeterJausovec|0.0.11|
|theme-toothpaste|aalaap|0.0.1|
|vscode-eslint|dbaeumer|1.2.0|
|githistory|donjayamanne|0.1.5|
|tslint|eg2|0.8.1|
|vscode-npm-script|eg2|0.1.8|
|vsc-travis-ci-status|felixrieseberg|1.0.5|
|Go|lukehoban|0.6.52|
|csharp|ms-vscode|1.6.2|
|debugger-for-chrome|msjsdiag|2.4.2|
|better-merge|pprice|0.5.1|
|Ruby|rebornix|0.10.4|
|java|redhat|0.0.9|
|kustovscode|seanmcbreen|0.0.1|
|php-syntax-visualizer|vscode|0.0.1|
|gitblame|waderyan|1.3.0|
|vscode-open-in-github|ziyasal|1.2.3|

---

Steps to Reproduce:
 I recently opened vscode on '/'. This is unsupported on the welcome page.

![screen shot 2017-01-26 at 10 03 35 am](https://cloud.githubusercontent.com/assets/4674940/22343948/e581a870-e3ae-11e6-8028-1be1f43d0451.png)

**Comment by chrmarti** [comment]
Fixed with #19448
