### ISSUE TITLE
Fuzzy searching in the new quickTextSearch 

### ISSUE THREAD

**Issue by lcrownover** [microsoft/vscode#194522]
Splitting off from https://github.com/microsoft/vscode/issues/194448

I'd *love* if the quickTextSearch bar would be fuzzy matching! 😊

**Comment by eleanorjboyd** [comment]
Thank you for submitting your feature request and everyone who considered it! Unfortunately, this issue did not receive enough votes over the allotted time, and so we are closing the issue.
