### ISSUE TITLE
debug timeout

### ISSUE THREAD

**Issue by eddhyne** [microsoft/vscode#194540]
Type: <b>Bug</b>

Running the debugger I get :
pydevd warning: Computing repr of special variables () was slow (took 3.96s)
Customize report timeout by setting the `PYDEVD_WARN_SLOW_RESOLVE_TIMEOUT` environment variable to a higher timeout (default is: 0.5s)

**Comment by roblourens** [comment]
Please file this on the vscode-python extension repo, thanks
