### ISSUE TITLE
Settings Editor overlaps with editor group highlight

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#194582]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 
- OS Version: 

The bottom of the setting editor overlaps with the border of the editor group

![Image](https://github.com/microsoft/vscode/assets/876920/0fac6b1e-1a6e-43b3-9aed-bc6c4260eb37)

**Comment by rzhao271** [comment]
Duplicate of #183503
