### ISSUE TITLE
PHP punctuation has no theme selectors

### ISSUE THREAD

**Issue by smlombardi** [Microsoft/vscode#19465]
- VSCode Version: Code - Insiders 1.9.0-insider (6ba4282fd27bacacbf8482472a0519560720fb9c, 2017-01-26T07:26:32.304Z)
- OS Version: Darwin x64 16.4.0
- Extensions:

|Extension|Author|Version|
|---|---|---|
|material-icon-theme|PKief|1.2.0|
|code-settings-sync|Shan|2.4.2|
|sort-lines|Tyriar|1.2.0|
|html-css-class-completion|Zignd|1.0.3|
|Bookmarks|alefragnani|0.10.2|
|project-manager|alefragnani|0.13.0|
|vscode-angular-files|alexiv|1.3.7|
|one-monokai|azemoh|0.2.4|
|vscode-icontheme-nomo-dark|be5invis|1.2.5|
|vscode-eslint|dbaeumer|1.2.2|
|githistory|donjayamanne|0.1.5|
|tslint|eg2|0.8.1|
|vscode-great-icons|emmanuelbeziat|1.1.40|
|auto-rename-tag|formulahendry|0.0.11|
|Angular2|johnpapa|1.0.2|
|theme-karyfoundation-themes|karyfoundation|10.3.0|
|ftp-sync|lukasz-wronski|0.3.2|
|HTMLHint|mkaufman|0.3.3|
|vscode-csscomb|mrmlnc|4.0.0|
|vscode-postcss-sorting|mrmlnc|2.2.1|
|vscode-stylefmt|mrmlnc|2.2.2|
|Theme-1337|ms-vscode|0.1.2|
|angular2-inline|natewallace|0.0.17|
|nonbreakingspace|smlombardi|0.0.1|
|vscode-icons|robertohuertasm|7.1.2|
|stylelint|shinnn|0.21.2|
|darcula-extended|smlombardi|3.3.2|
|theme-tesla|smlombardi|6.0.0|
|theme-espresso|smlombardi|0.0.0|
|change-case|wmaurer|1.0.0|

---

Steps to Reproduce:

1. unlike JS or CSS, there's no way to set the punctuation in embedded PHP:

<img width="639" alt="screen shot 2017-01-26 at 6 41 50 pm" src="https://cloud.githubusercontent.com/assets/835148/22355199/5045ef02-e3f7-11e6-9dd7-7bf639979964.png">

I can set a base color with `meta.embedded.block.php source.php` but it seems incomplete not to have `punctuation.*`

**Comment by roblourens** [comment]
It looks like we have `punctuation.*` selectors with the new grammar.
