### ISSUE TITLE
vscode.tasks.executeTask error Unexpected: Task does not exist after task.terminate()

### ISSUE THREAD

**Issue by vaclavHala** [microsoft/vscode#194618]
Type: <b>Bug</b>

* clone repro from https://github.com/vaclavHala/vscode-workspace-race and open project folder `corrupted-tasks`
* run the repro extension from vscode
* open two folders in the workspace (these will not be touched by the repro code, the problem was encounterd in multi-folder workspace and this just reproduces that environment)
* run command `Run tasks.json race`
* after some time popup with error `Unexpected: Task does not exist.` will appear

Expected beahvior: 
the loop running the dummy task will keep running indefinitely

This seems to be caused by using `TaskExecution.terminate()` in combination with changes of the workspace folders. When the `while(true)` loop in the repro is changed to only keep writing the `tasks.json` file and running the tasks the problem never appears

VS Code version: Code - Insiders 1.82.0-insider (f1302be1e67e3af5fbeb8bbb2ea784de7bc96150, 2023-09-01T11:05:38.381Z)
OS version: Linux x64 4.19.0-18-amd64
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 2700 Eight-Core Processor (16 x 2484)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|1, 1, 1|
|Memory (System)|31.43GB (12.42GB free)|
|Process Argv|--crash-reporter-id f8df83a3-a85f-44ab-903a-d2a2cb362dd0|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|xfce|
|XDG_CURRENT_DESKTOP|XFCE|
|XDG_SESSION_DESKTOP|xfce|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (0)</summary>

Extension|Author (truncated)|Version
---|---|---

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythontb:30258533
pythonptprofiler:30281269
vsdfh931:30280409
vshan820:30294714
vscod805:30301674
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30404738
py29gd2263:30784851
vsclangdf:30492506
c4g48928:30535728
dsvsc012:30540252
pynewext54:30618038
showlangstatbar:30737417
ecj1e332:30687743
pythonfmttext:30716741
fixshowwlkth:30771523
showindicator:30805243
pythongtdpath:30726887
i26e3531:30792625
welcomedialog:30812478
pythonnosmt12:30779711
pythonidxpt:30768918
pythonnoceb:30776497
copilotsettingt:30808721
dsvsc013:30777762
dsvsc014:30777825
diffeditorv2:30786206
pythonmpsinfo:30842935
dsvsc015:30821418
pythontestfixt:30826906
pythonfb280951:30830809
pythonregdiag:30842812
pythonmypyd1cf:30850306
pythoncet0:30848247

```

</details>

**Comment by meganrogge** [comment]
I'm not seeing the task you said to run in that folder

![Image](https://github.com/microsoft/vscode/assets/29464607/b2c6f999-d89e-4218-8ab6-e7ba5315cdc0)

**Comment by vaclavHala** [comment]
The repro steps say to run **command** `Run tasks.json race`, not a task. The command runs the task itself via the vscode.tasks API.

Here is the command in the command pallette
![Screenshot_2023-10-20_19-29-45](https://github.com/microsoft/vscode/assets/12083193/79e46c00-f787-485b-b34b-a52f8d0242e9)

And here is the error it produces
![Screenshot_2023-10-20_19-30-40](https://github.com/microsoft/vscode/assets/12083193/5e415f68-2ae0-4ace-a4f2-158fdc653958)

Please try the repro steps again and let me know if you still can't see what I show in the screenshots @meganrogge

**Comment by meganrogge** [comment]
I get this error, which is interesting because the workspace contains two folders.

![Image](https://github.com/microsoft/vscode/assets/29464607/c4cad2c5-e178-4d30-ba12-9997b6b055d5)

**Comment by vaclavHala** [comment]
From the screenshot it seems like you have one workspace folder containing two file system folders - that still means the workspace is a single root workspace
You need to have a multi-root workspace by calling `File > Add Folder to Workspace...`
I hope the terminology I use is correct, it is taken from this doc https://code.visualstudio.com/docs/editor/multi-root-workspaces

**Comment by jeanp413** [comment]
PR fixing it https://github.com/microsoft/vscode/pull/200872
