### ISSUE TITLE
Opening quick text search in a diff editor doesn't put selected text in input

### ISSUE THREAD

**Issue by TylerLeonhardt** [microsoft/vscode#194675]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 
- OS Version: 

Steps to Reproduce:

1. set up a keybinding to launch quick text search
2. open a diff editor
3. select some text 
4. launch quick text search

Nothing in input:

![Image](https://github.com/microsoft/vscode/assets/2644648/da3a207b-a647-4380-8186-91671db3785b)

Expected:

![Image](https://github.com/microsoft/vscode/assets/2644648/55cab5f8-46de-461f-8caa-b61b5f20ce11)

**Comment by nikhilkarve** [comment]
Hi @TylerLeonhardt , I guess the PR has fixed this already. I tried reproducing it locally with the changes of my current PR, and it seems to be working fine. Attaching the screen recording for your reference.

https://github.com/microsoft/vscode/assets/46160625/ad5afe05-b043-4473-ba66-6fa0c3d8aac4

**Comment by TylerLeonhardt** [comment]
You need to open a diff editor. For example:
* open a folder that is a git repo
* Make a change in any file
* Go to the source control viewlet and click on the changed file:
<img width="1679" alt="Screenshot 2023-10-08 at 2 57 57 PM" src="https://github.com/microsoft/vscode/assets/2644648/528a4b7b-755c-4263-9387-0462a0a1e285">
* Select text in the right editor

The bug appears.

**Comment by nikhilkarve** [comment]
Got it, will try to correct it

**Comment by nikhilkarve** [comment]
Hi @TylerLeonhardt , I understand that you must be busy. Can you take a look any time you are available?
I need some help in figuring out where exactly the diff editor is interacting with search bindings. For example, I am not able to understand how hitting cmd+f calls the search function, or where it is getting called from. Similarly for the quickTextSearch, can you point me in the right direction?
