### ISSUE TITLE
vscode-uri: missing `URI.joinPath` 

### ISSUE THREAD

**Issue by olafurpg** [microsoft/vscode#194615]
I was going to report an issue in the https://github.com/microsoft/vscode-uri repo but the readme there says to report issues here instead.

I'm authoring a VS Code extension and I'm using vscode-uri `URI` implementation as a replacement for `vscode.Uri` in my tests. I noticed that `Uri.joinPath` has no equivalent `URI.joinPath`.

https://github.com/microsoft/vscode/blob/8f382227e0f9cb635601997c309a5c1b941e1fd0/src/vs/base/common/uri.ts#L356

It would be nice to update vscode-uri to include `URI.joinPath` so that it's feature compatible with `vscode.Uri`.

**Comment by jrieken** [comment]
It's there but as sibling symbol called `Utils`. That has join and many other function
