### ISSUE TITLE
When title updated, menu not resized until window resized

### ISSUE THREAD

**Issue by justanotheranonymoususer** [microsoft/vscode#194652]
Does this issue occur when all extensions are disabled?: Yes

Version: 1.82.2 (user setup)
Commit: abd2f3db4bdb28f9e95536dfa84d8479f1eb312d
Date: 2023-09-14T05:55:25.390Z
Electron: 25.8.1
ElectronBuildId: 23779380
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.22621

Steps to Reproduce:

1. Cause a title to change, and watch at the menu
2. See video below

https://github.com/microsoft/vscode/assets/5781692/82a890da-a9be-40a2-91e9-d866eec0e8da

**Comment by benibenj** [comment]
Should be fixed in todays insiders
