### ISSUE TITLE
Sometimes can't hover to statusBarItem tooltip at default zoom

### ISSUE THREAD

**Issue by RobbyCBennett** [microsoft/vscode#194624]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.83.0-insider
- OS Version: Windows 11

Steps to Reproduce:

1. Install the rust-analyzer extension (`rust-lang.rust-analyzer`)
2. Open a Rust project
3. Run the command "View: Reset Zoom"
4. Hover on the edge rust-analyzer (mouse cursor is a hand) status bar item on the bottom left
5. Try to hover up to the tooltip
6. Repeat steps 4 - 6 until the tooltip disappears

Video:

https://github.com/microsoft/vscode/assets/22121365/c6982b47-23c6-4f14-b106-0bdeb703255b

Notes:

This is an edge-case of another [issue that was already closed](https://github.com/microsoft/vscode/issues/181606) where it wasn't working at all. However, the issue now only happens for me when the mouse is on the edge, and the zoom is at the default. My screen is 3840 x 2160 and the Windows scaling setting is 125%.

**Comment by RobbyCBennett** [comment]
Yes, it does.

**Comment by RobbyCBennett** [comment]
https://github.com/microsoft/vscode/assets/22121365/62a7abed-5ea7-4ecb-93bd-aafb0ea62c06

**Comment by benibenj** [comment]
Closing as it seems to work well, possibly due to some recent changes

**Comment by RobbyCBennett** [comment]
This issue still occurs for me on the latest release, which is currently 1.95.3.
