### ISSUE TITLE
clicking on the Node.js link results in a 404

### ISSUE THREAD

**Issue by deepakdahal** [Microsoft/vscode#19461]
- VSCode Version:
- OS Version:

Steps to Reproduce:

1. Click on https://code.visualstudio.com/Docs/editor/debugging#_next-steps
2. Click on the Node.js link

**Comment by mousetraps** [comment]
Thanks! Just made a PR to fix this, so it should be updated soon. 
https://github.com/Microsoft/vscode-docs/pull/814
