### ISSUE TITLE
Solarized Dark Theme token colours changed

### ISSUE THREAD

**Issue by israel-oye** [microsoft/vscode#194612]
Type: <b>Bug</b>

After updating my VS Code, I noticed that the foreground colour of Python's builtin constants like 'None' and 'True' are being overridden by the semantic analyzer and it set them as variables instead of constants.
I have tried to edit the TextMate but from what I've found the semantic analyzer token colour takes precedence.
This was not the case before I updated my VS Code.

VS Code version: Code 1.82.2 (abd2f3db4bdb28f9e95536dfa84d8479f1eb312d, 2023-09-14T05:55:25.390Z)
OS version: Windows_NT x64 10.0.22621
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|7.89GB (1.38GB free)|
|Process Argv|--crash-reporter-id 52b13eb1-5299-422c-99b1-051da3ff011b|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (37)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-sqlite|ale|0.14.1
python-preview|don|0.0.4
vscode-html-css|ecm|1.13.1
vsc-material-theme-icons|equ|3.0.4
prettier-vscode|esb|10.1.0
code-runner|for|0.12.0
codespaces|Git|1.15.4
csharpextensions|jch|1.3.1
vscode-csharp-snippets|jor|1.1.0
vscode-JS-CSS-HTML-formatter|lon|0.2.3
gitignore|mic|1.0.1
theme-monokai-pro-vscode|mon|1.2.1
vscode-docker|ms-|1.26.1
csharp|ms-|2.4.4
vscode-dotnet-runtime|ms-|1.8.0
isort|ms-|2023.10.1
python|ms-|2023.16.0
vscode-pylance|ms-|2023.9.30
jupyter|ms-|2023.8.1002501831
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.17
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-slideshow|ms-|0.1.5
live-server|ms-|0.4.9
vsliveshare|ms-|1.0.5883
material-icon-theme|PKi|4.30.1
prettier-vscode|Sim|2.0.7
vscode-field-lights|sve|0.0.11
ayu|tea|1.0.5
open-in-browser|tec|2.0.0
vscode-icons|vsc|12.5.0
vscode-todo-highlight|way|1.0.5
jinja|who|0.0.8
php-debug|xde|1.33.0
php-pack|xde|1.0.3
material-theme|zhu|3.16.0
php-intellisense|zob|1.3.3

(14 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
py29gd2263cf:30792227
6c1a3589:30846784
vscaat:30438848
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
2e4cg342:30602488
f6dab269:30613381
a9j8j154:30646983
showlangstatbar:30737416
962ge761:30841074
03d35959:30757346
pythonfmttext:30731395
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
pythonnosmt12:30797651
pythonidxptcf:30805731
pythonnoceb:30805159
copilotsettingc:30839828
asynctok:30821568
dsvsc013:30795093
dsvsc014:30804076
diffeditorv1:30821571
dsvsc015:30845448

```

</details>

**Comment by aeschli** [comment]
Semantic tokens always had preference, no change there. Maybe a different semantic are generated?

Here's what I see in the latest insiders when I use the `Developer: Inspect Editor Tokens and Scopes` command:
![image](https://github.com/microsoft/vscode/assets/6461412/a792c70a-73de-41f9-b166-d86f8b0e156d)

All looks fine here. What do you get when using that command?

**Comment by israel-oye** [comment]
This is what I got:
![solarized-1](https://github.com/microsoft/vscode/assets/97196057/37fdb16b-d2a8-418a-b6fc-ad22c8118020)

I tried to edit the textmate all to no avail. Just like you said and as it is in the docs, semantic analyzer takes precedence.
![solarized-2](https://github.com/microsoft/vscode/assets/97196057/99af02ac-0f5b-420c-acd8-623264f7720d)

What is baffling to me is how I didn't experience this until some days ago when I was trying different `Color Themes` and after my VS Code updated.

**Comment by aeschli** [comment]
Maybe the Python language server added these semantic tokens only recently, I don't know.

There's also a way to change the color for semantic tokens.
```
	"editor.semanticTokenColorCustomizations": {
		"[Solarized Dark]": {
			"rules": {
				"builtinConstant": "#ff0000"
			}
		}
	}	
```

**Comment by aeschli** [comment]
Closing issue. I think the Python extension had some issues regarding semantic tokens
