### ISSUE TITLE
Build fails with node-gyp error after Node 18.18

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#194665]
Today, the Monaco Editor build task and the insiders task in main fail with this error

```
[1/4] Resolving packages...
error /home/runner/work/vscode/vscode/node_modules/@parcel/watcher: Command failed.
Exit code: 1
Command: node-gyp-build
Arguments: 
Directory: /home/runner/work/vscode/vscode/node_modules/@parcel/watcher
Output:
node:events:495
      throw er; // Unhandled 'error' event
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
      ^

Error: spawn node-gyp ENOENT
    at ChildProcess._handle.onexit (node:internal/child_process:284:19)
    at onErrorNT (node:internal/child_process:477:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:[21](https://github.com/microsoft/vscode/actions/runs/6382475800/job/17321168923#step:9:22))
Emitted 'error' event on ChildProcess instance at:
    at ChildProcess._handle.onexit (node:internal/child_process:[29](https://github.com/microsoft/vscode/actions/runs/6382475800/job/17321168923#step:9:30)0:12)
    at onErrorNT (node:internal/child_process:477:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'spawn node-gyp',
  path: 'node-gyp',
  spawnargs: [ 'rebuild' ]
}
```

It seems that this is related to getting Node 18.18, which came in last week. The tasks only started failing today because they were getting cached node modules before and the caches were only invalidated this morning.

This fix went in previously https://github.com/microsoft/vscode/pull/194494/files but we need the same for the other build configs.

I'm wondering whether you have any context on what changed in 18.18, @chrmarti?

For now I have changed the failing configs to use 18.17, https://github.com/microsoft/vscode/pull/194663 and https://github.com/microsoft/vscode/pull/194677. I don't understand how `node-gyp` got into the build previously- was it included with the node install but not with 18.18?

It might make sense to keepthe node build version pinned to the same version that we use locally, in which case we should keep https://github.com/microsoft/vscode/pull/194663 and also change all other node version specifiers in other build configs

Or, we can revert that and adopt the change to install node-gyp manually. But I'd still like to understand what actually changed. If we are going to install node-gyp manually we should add it as a vscode dev dependency so that it is pinned to some version.

**Comment by deepak1556** [comment]
This is a side effect of npm removing the binary scripts to find node-gyp starting with v9.7.2 in https://github.com/npm/cli/commit/3a7378d889707d2a4c1f8a6397dda87825e9f5a3, node-gyp is always bundled with npm it is just that the packages have to specify the path to the binary now.

Node v18.18 updated to v9.7.2 of npm https://github.com/nodejs/node/blob/main/doc/changelogs/CHANGELOG_V18.md and hence we are starting to see this breakage now.

**Comment by roblourens** [comment]
```
- Removes the unused `node-gyp-bin` files. Those are remnants from
  before `@npmcli/run-script` was introduced in `npm@7`. Now that
  package is responsible for setting `PATH` with the appropriate
  `node-gyp` bin.
```

Thanks for the context! So... `npm run` is supposed to be putting node-gyp on the PATH?

**Comment by roblourens** [comment]
Is us using `yarn` part of the problem?

**Comment by deepak1556** [comment]
> So... npm run is supposed to be putting node-gyp on the PATH?

Yes, the npm run packages `node-gyp` and they force resolve path to it when spawning run scripts using `npm_config_node_gyp` https://github.com/npm/run-script/commit/e4c7cb33eba987e30637006178172e67801f9e92

> Is us using yarn part of the problem?

Yeah I would think so, but we have two options

1) Install `node-gyp` globally so that the binary scripts would be available on `PATH` by default, refs https://github.com/microsoft/vscode/blob/503634675f4b3b623bc157b9442b7383369d1abb/build/azure-pipelines/darwin/product-build-darwin.yml#L80
2) We also depend on `node-gyp` during preinstall step to download headers on windows https://github.com/microsoft/vscode/tree/main/build/npm/gyp, we can now change to resolve this package on all platforms and set `npm_config_node_gyp` to this package path.

**Comment by roblourens** [comment]
Would it work to just add node-gyp as a devDependency to the root package.json? Is that what you are suggesting in 2?

**Comment by deepak1556** [comment]
No I don't think adding as devDependency would help here since yarn will not pick it up, to expand on 2) a bit more it would look something like the following

```
- script: |
      set -e
      yarn i --cwd build/npm/gyp
      export npm_config_node_gyp=`pwd`/build/npm/gyp/node_modules/node-gyp/bin/node-gyp.js
 displayName: Configure node-gyp binary path
```

We already configure a custom node-gyp for [product-build-win32](https://github.com/microsoft/vscode/blob/46c45d2f67b60b398de23881080c35fc5f9795b2/build/azure-pipelines/win32/product-build-win32.yml#L110-L123) and [sdl-scan](https://github.com/microsoft/vscode/blob/46c45d2f67b60b398de23881080c35fc5f9795b2/build/azure-pipelines/sdl-scan.yml#L112-L123), so these two pipelines can remain untouched. The rest of the pipelines will need a step like above.

**Comment by chrmarti** [comment]
Thanks for deciphering this, we hadn't figured out the NPM update causing this while getting builds out. /cc @joaomoreno

**Comment by chrmarti** [comment]
Yarn is prepared for installing `node-gyp` automatically (maybe as a fix for the NPM change?), but seems to fail to do so in our build setup:
```
info This package requires node-gyp, which is not currently installed. Yarn will attempt to automatically install it. If this fails, you can run "yarn global add node-gyp" to manually install it.
```

Source: https://github.com/yarnpkg/yarn/blob/158d96dce95313d9a00218302631cd263877d164/src/util/execute-lifecycle-script.js#L317
Log: https://dev.azure.com/monacotools/Monaco/_build/results?buildId=234623&view=logs&j=bd1e231b-cef9-51a2-e461-b67194c0a817&t=2d3f0051-710b-5b61-3f5e-02dc278899ee&l=62

The log doesn't show `yarn global add node-gyp` being executed or any error from it. 🤷‍♂️

**Comment by chrmarti** [comment]
Maybe it installs successfully but yarn's bin folder (`yarn global bin`) is not on the `PATH`? I would still expect yarn to pick it up.

**Comment by roblourens** [comment]
I missed this yesterday but I see that it did try to install node-gyp, but only after it failed to build `@parcel/watcher` for some reason?

```
info This package requires node-gyp, which is not currently installed. Yarn will attempt to automatically install it. If this fails, you can run "yarn global add node-gyp" to manually install it.
[1/4] Resolving packages...
error /home/runner/work/vscode/vscode/node_modules/@parcel/watcher: Command failed.
Exit code: 1
Command: node-gyp-build
Arguments: 
Directory: /home/runner/work/vscode/vscode/node_modules/@parcel/watcher
Output:
node:events:495
      throw er; // Unhandled 'error' event
      ^

Error: spawn node-gyp ENOENT
    at ChildProcess._handle.onexit (node:internal/child_process:284:[19](https://github.com/microsoft/vscode/actions/runs/6384727250/job/17327971301#step:9:20))
    at onErrorNT (node:internal/child_process:477:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:[21](https://github.com/microsoft/vscode/actions/runs/6384727250/job/17327971301#step:9:22))
Emitted 'error' event on ChildProcess instance at:
    at ChildProcess._handle.onexit (node:internal/child_process:[29](https://github.com/microsoft/vscode/actions/runs/6384727250/job/17327971301#step:9:30)0:12)
    at onErrorNT (node:internal/child_process:477:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'spawn node-gyp',
  path: 'node-gyp',
  spawnargs: [ 'rebuild' ]
}

Node.js v18.18.0
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Installed "node-gyp@9.4.0" with binaries:
      - node-gyp
```

Anyway, I think I prefer the solution of just installing node-gyp ourselves. I can switch to that, but I just think we should be installing a specific version, so `npm i -g node-gyp@9.4.0`? If no objections, I can do that.

**Comment by roblourens** [comment]
And Steven pointed out that the NodeTool devops task can take a path to a nvmrc file. That would keep our CI config in sync with the local build version, so I can do that as well.

**Comment by chrmarti** [comment]
> I missed this yesterday but I see that it did try to install node-gyp, but only after it failed to build `@parcel/watcher` for some reason?

Missed that too.

@joaomoreno It first announces it would install node-gyp, but only finishes doing so after the first package install has already failed. This looks like it is running the node-gyp install in parallel with building the packages. Could this be some optimization on our side causing it?

> Anyway, I think I prefer the solution of just installing node-gyp ourselves. I can switch to that, but I just think we should be installing a specific version, so `npm i -g node-gyp@9.4.0`? If no objections, I can do that.

Letting yarn handle it automatically might be slightly preferred. Otherwise 👍

**Comment by roblourens** [comment]
https://github.com/microsoft/vscode/pull/194836
