### ISSUE TITLE
help

### ISSUE THREAD

**Issue by min1974** [microsoft/vscode#194682]
Type: <b>Performance Issue</b>

I downloaded .net 7.0 today. Then I reroaded vscode, and this caution(?) arose. 
Error message is  : There were problems loading project Assembly-CSharp.csproj. See log for details.
and I downloaded old version of .net by using pip several months ago.
I don't know anything, plz help me ㅠㅠ 

VS Code version: Code 1.82.3 (fdb98833154679dbaa7af67a5a29fe19e55c2b73, 2023-10-02T10:51:22.294Z)
OS version: Windows_NT x64 10.0.22621
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz (8 x 2419)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|7.69GB (1.77GB free)|
|Process Argv|--crash-reporter-id 16e0e625-4250-4b5e-b05e-dca6cd80344b|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	   124	  2484	code main
    0	   186	  4484	extensionHost [1]
    0	    88	  6024	     electron-nodejs ("C:\Users\bossm\AppData\Local\Programs\Microsoft VS Code\Code.exe" --ms-enable-electron-run-as-node c:\Users\bossm\.vscode\extensions\formulahendry.auto-rename-tag-0.1.10\packages\server\dist\serverMain.js --node-ipc --clientProcessId=4484)
    0	   243	  6700	     "C:\Program Files\dotnet\dotnet.exe" c:\Users\bossm\.vscode\extensions\ms-dotnettools.csharp-2.4.4-win32-x64\.roslyn\Microsoft.CodeAnalysis.LanguageServer.dll --logLevel Information --telemetryLevel all --extensionLogDirectory c:\Users\bossm\AppData\Roaming\Code\logs\20231003T113329\window1\exthost\ms-dotnettools.csharp
    0	    99	  4636	shared-process
    0	    91	  6172	fileWatcher [1]
    0	    83	  8660	   utility-network-service
    0	    99	 11608	window [2] (문제 보고자)
    0	   260	 12916	   gpu-process
    0	    80	 12920	   crashpad-handler
    0	   189	 14884	window [1] (Background.cs - xx7 - Visual Studio Code)
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (Background.cs - xx7 - Visual Studio Code)
|    Folder (xx7): 19852 files
|      File types: meta(6035) cs(3756) png(1667) md(509) dll(239) mvfrm(192)
|                  txt(157) pdb(152) json(132) rsp(132)
|      Conf files: package.json(55) settings.json(1) csproj(1) sln(1);
```

</details>
<details><summary>Extensions (23)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-django|bat|1.14.0
python-environment-manager|don|1.2.4
python-extension-pack|don|1.7.0
prettier-vscode|esb|10.1.0
auto-close-tag|for|0.5.14
auto-complete-tag|for|0.1.0
auto-rename-tag|for|0.1.10
vsc-python-indent|Kev|1.18.0
unity-code-snippets|kle|2.2.5
python-path|mge|0.0.14
vscode-language-pack-ko|MS-|1.82.2023091309
csharp|ms-|2.4.4
vscode-dotnet-runtime|ms-|1.8.0
python|ms-|2023.16.0
vscode-pylance|ms-|2023.9.30
vsliveshare|ms-|1.0.5883
autodocstring|njp|0.6.1
LiveServer|rit|5.7.9
unity-tools|Tob|1.2.12
intellicode-api-usage-examples|Vis|0.2.8
vscodeintellicode|Vis|1.2.30
jinja|who|0.0.8
copy-python-path|yar|1.0.4

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes516:30244333
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
282f8724:30602487
89544117:30613380
vscrpc:30673769
showlangstatbar:30737416
pythonfmttext:30731395
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
pythonnosmt12:30797651
pythonidxptcf:30805731
pythonnoceb:30805159
dsvsc013:30795093
dsvsc014:30804076
diffeditorv2:30821572
dsvsc015:30845448

```

</details>

**Comment by lszomoru** [comment]
Please file [an issue](https://github.com/dotnet/vscode-csharp/issues) in the C# extension's repository. Thank you!

**Comment by min1974** [comment]
When running, only this log appears:
Using dotnet configured on PATH
Dotnet path: C:\Program Files\dotnet\dotnet.exe
Activating C# standalone...
waiting for named pipe information from server...
[stdout] {"pipeName":"\\\\.\\pipe\\7fc4a3ef-95ce-4357-ba5f-0772743d0831"}
received named pipe information from server
attempting to connect client to server...
client has connected to server
[Info  - 오후 5:16:38] [Program] Language server initialized
[Info  - 오후 5:16:38] [LanguageServerProjectSystem] Loaded MSBuild in-process from C:\Program Files\dotnet\sdk\7.0.401
[Info  - 오후 5:16:38] [LanguageServerProjectSystem] Loading c:\Users\bossm\Desktop\unityfiles\My project\My project.sln...
[Error - 오후 5:16:39] [LanguageServerProjectSystem] Exception thrown while loading c:\Users\bossm\Desktop\unityfiles\My project\Assembly-CSharp.csproj StreamJsonRpc.RemoteInvocationException: 시퀀스에 요소가 없습니다.
   at StreamJsonRpc.JsonRpc.InvokeCoreAsync[TResult](RequestId id, String targetName, IReadOnlyList`1 arguments, IReadOnlyList`1 positionalArgumentDeclaredTypes, IReadOnlyDictionary`2 namedArgumentDeclaredTypes, CancellationToken cancellationToken, Boolean isParameterObject)
 at Microsoft.CodeAnalysis.LanguageServer.HostWorkspace.LanguageServerProjectSystem.LoadOrReloadProjectAsync(ProjectToLoad projectToLoad, BuildHostProcessManager buildHostProcessManager, BuildHost inProcessBuildHost, CancellationToken cancellationToken) in /_/src/Features/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/HostWorkspace/LanguageServerProjectSystem.cs:line 241
RPC server exception:
System.InvalidOperationException: 시퀀스에 요소가 없습니다.
      위치: System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
      위치: Microsoft.CodeAnalysis.Workspaces.MSBuild.BuildHost.BuildHost.EnsureMSBuildLoaded(String projectFilePath)
      위치: Microsoft.CodeAnalysis.Workspaces.MSBuild.BuildHost.BuildHost.IsProjectFileSupportedAsync(String projectFilePath, CancellationToken cancellationToken)

[Info  - 오후 5:16:39] [LanguageServerProjectSystem] Completed (re)load of all projects in 00:00:00.6612935

**Comment by lszomoru** [comment]
Please file an issue in the repository linked in [this comment](https://github.com/microsoft/vscode/issues/194682#issuecomment-1744311913).
