### ISSUE TITLE
Notebook find/replace corrupts notebook

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#194632]
Type: <b>Bug</b>

From #194629

1. In vscode repo with notebook search enabled
2. Search `September 2023` (or maybe `October 2023` if we've updated milestones)
3. Add some replacement text and confirm the preview looks good

![Screenshot 2023-10-02 at 10 41 26 AM](https://github.com/microsoft/vscode/assets/12821956/0320f61e-a6c8-4608-8d87-72e3bd580738)

4. Do the replacement

**Bug**
Some of the replacements seem to corrupt the notebook. For example, here it's editing text in the wrong area which ends up breaking the notebook:

![Screenshot 2023-10-02 at 10 45 02 AM](https://github.com/microsoft/vscode/assets/12821956/8271834a-7c67-4c96-80e1-dc098238b69c)

VS Code version: Code - Insiders 1.83.0-insider (Universal) (4268e464763087044d0c1b5bdd37ebbe683cadfa, 2023-09-29T20:44:15.716Z)
OS version: Darwin arm64 23.0.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M2 Max (12 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|4, 4, 4|
|Memory (System)|64.00GB (0.75GB free)|
|Process Argv|--crash-reporter-id 0fffb5da-9cd7-46fd-9e7f-a1564e8c5fda|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by amunger** [comment]
this also applies to general .ipynb files, but it looks like it existed since 1.81, which I think was when the relevant setting was introduced

**Comment by andreamah** [comment]
Can confirm that this only happens with `search.experimental.closedNotebookRichContentResults` enabled, which is only on by default on insiders. I was able to repro this with the setting on, but since it's an experimental setting, I don't think this needs to be a candidate.

**Comment by andreamah** [comment]
I need to add support to https://github.com/microsoft/vscode/blob/7906b2bb614754f39a12bb4aa2d143e637f47694/src/vs/workbench/contrib/search/browser/replaceService.ts#L116-L128 such that we can save the nth cell with the range given. 

Since the notebook editor model doesn't exist yet, we need to figure out a good way to either create one or find a different, more minimal way to do this.

I'd prefer to merge in https://github.com/microsoft/vscode/pull/192358 before I do this so that I don't have two large PRs in these files at once.

**Comment by andreamah** [comment]
I have a temp fix in https://github.com/microsoft/vscode/pull/194932 that disabled replace on closed notebook results. The full fix is tracked in https://github.com/microsoft/vscode/issues/194931
