### ISSUE TITLE
Process no longer attaching to Javascript Debug Terminal

### ISSUE THREAD

**Issue by justinasfour04** [microsoft/vscode#194659]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 
1.82.3
fdb98833154679dbaa7af67a5a29fe19e55c2b73
x64
- OS Version: 
Edition	Windows 10 Enterprise
Version	22H2
Installed on	‎11/‎24/‎2022
OS build	19045.3448
Experience	Windows Feature Experience Pack 1000.19044.1000.0

Steps to Reproduce:

1. Start a javascript debug terminal
2. npm run start project
3. notice that debugger does not attach
4. put breakpoints and nothing happens

**Comment by connor4312** [comment]
Please share:

- The `node --version` you're using
- The value of the `NODE_OPTIONS` environment variable in the JavaScript Debug Terminal
- The shell you're using (cmd/powershell/something else)

**Comment by justinasfour04** [comment]
node --version
v18.18.0
echo $NODE_OPTIONS
--max_old_space_size=4096
echo "$SHELL"
/usr/bin/zsh

**Comment by connor4312** [comment]
It looks like you're overwriting NODE_OPTIONS with `--max_old_space_size`. This prevents debugging from attaching. You will want to append rather than overwrite that variable.
