### ISSUE TITLE
iMac and weird background

### ISSUE THREAD

**Issue by ainstushar** [Microsoft/vscode#19462]
- VSCode Version: 1.8.1
- OS Version: 10.12.2

Steps to Reproduce:

1. Open any file in VS Code on an iMac with high resolution display.
2. See background color shift when you click around a file. See attachments.

<img width="1157" alt="screen shot 2017-01-26 at 4 41 58 pm" src="https://cloud.githubusercontent.com/assets/7689996/22351519/67b54284-e3e6-11e6-918f-b579d1b742f6.png">
<img width="2277" alt="screen shot 2017-01-26 at 4 39 45 pm" src="https://cloud.githubusercontent.com/assets/7689996/22351526/6b8ddcb8-e3e6-11e6-92f6-ccfc7422a9cb.png">
<img width="2276" alt="screen shot 2017-01-26 at 4 39 34 pm" src="https://cloud.githubusercontent.com/assets/7689996/22351530/6f7c9530-e3e6-11e6-8eec-30a7048289e9.png">

**Comment by mousetraps** [comment]
I can't seem to reproduce this issue myself. @chrmarti, @bpasero - any ideas?

**Comment by chrmarti** [comment]
An issue with electron on OSX Sierra, tracked on our side with #12473. That issue talks about possible workarounds with --disable-gpu or --force-gpu-rasterization.
