### ISSUE TITLE
`workbench.editor.untitled.hint` migration is buggy

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#194642]
I have a setting `"workbench.editor.untitled.hint": "hidden"` in my settings. Everytime I reload, I see a setting `"workbench.editor.empty.hint": "hidden"` being added. This keeps on happening, the old setting is never removed.

![Recording 2023-10-02 at 20 30 30](https://github.com/microsoft/vscode/assets/900690/f3c5fe38-5b56-41df-88a9-b0b540f0f791)

Not sure if this should be a candidate.

@sandy081 does this code look right to you? Or does migration also need to remove the old setting?

https://github.com/microsoft/vscode/blob/60562530f063f305fd601e76a80c81690d502142/src/vs/workbench/contrib/codeEditor/browser/emptyTextEditorHint/emptyTextEditorHint.ts#L41-L53

**Comment by sandy081** [comment]
@joyceerhl If you want to remove the old setting you should explicitly mention that in the migration like below

```ts
key: 'workbench.editor.untitled.hint',
		migrateFn: (value, _accessor) => ([
			[emptyTextEditorHintSetting, { value }],
			['workbench.editor.untitled.hint', { value: undefined }],
		])
```

**Comment by bpasero** [comment]
Can the migration function be made in a way that people do not forget this?
