### ISSUE TITLE
expose command to preview/render html

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#1946]
We should expose and document our commands to preview/render html from a text document, like preview markdown or render html from doc etc.

**Comment by jrieken** [comment]
@bpasero fyi

**Comment by bpasero** [comment]
:+1: 

I think there is something missing currently to make this work from the workbench. The base input is `iFrameEditorInput` with subclasses for `HTMLFrameEditorInput` (which works by showing a URL) and `MarkdownEditorInput` (which works by just setting the content directly to the iframe).

For this it seems to me we have the content to show as a string (from the code editor model) and we do not have a URL to show. 

If we follow a similar model as with `ResourceInput`, then we can create an input (`ResourceFrameEditorInput` ?) for the iframe editor that gets its contents from the code editor model that the user provided before hand.

Another thing is how to update the iframe from changes to the code editor model. The input could register to changes on the code editor model and just refresh an opened editor with the input when this happens. This is somewhat we do for markdown today.

**Comment by jrieken** [comment]
closing a duplicate of #1308
