### ISSUE TITLE
I tried "Go to definition" and you won't believe what happened next

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#19467]
- In vscode repo
- Open telemetryUtils.ts
- Line 270, `return configurationService.onDidUpdateConfiguration...`
- Cursor on `onDidUpdateConfiguration`
- Press F12
- It goes to the definition of the `Event` interface instead, in `vs/base/common/event`

**Comment by mjbvz** [comment]
This has been fixed in TypeScript 2.2 nightly. Not sure we can work around it on our side, so closing as fixed upstream.
