### ISSUE TITLE
[c#] Syntax highlighting problem with SQL text strings

### ISSUE THREAD

**Issue by mikestre** [Microsoft/vscode#19464]
- VSCode Version: Code 1.8.1 (ee428b0eead68bf0fb99ab5fdc4439be227b6281, 2016-12-19T14:41:20.664Z)
- OS Version: Linux x64 3.10.0-514.6.1.el7.x86_64
- Extensions:

|Extension|Author|Version|
|---|---|---|
|vscode-docker|PeterJausovec|0.0.11|
|csharp|ms-vscode|1.6.2|
|mono-debug|ms-vscode|0.12.0|

---

Steps to Reproduce:

1.Reading  the .NET Core in Action eBook and entered the following code:
![codesyntaxhighlightingproblem](https://cloud.githubusercontent.com/assets/4304832/22353653/6e447dbc-e419-11e6-82cd-3df2ddb90d05.jpg)

[CodeSample.txt](https://github.com/Microsoft/vscode/files/733835/CodeSample.txt)

2.Syntax highlighting is incorrect for the SQL syntax strings. 
Code sample provided as a text file.

**Comment by aeschli** [comment]
This issue was moved to OmniSharp/omnisharp-vscode#1157
