### ISSUE TITLE
Fine tune `clear` alert

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#194672]
@jooyoungseo, @rperez030 I've just merged a PR that will `alert` "cleared" when the terminal or chat history has been cleared. This won't be in insider's until late this week - after our release FYI.

I noticed that we handle this differently across components:

Search says "the search results have been cleared".

Debug console says "Debug console cleared"

Chat/terminal say "Cleared"

The output channel says "Output cleared". 

Do you prefer the including the feature's name in the `alert` or keeping it concise?

**Comment by jooyoungseo** [comment]
IMO, there is no need to contain the feature name and we can make it concise like “Cleared.”

**Comment by rperez030** [comment]
I agree 200%.

**Comment by meganrogge** [comment]
Thanks, we'll go with "cleared" everywhere and consolidate this so that it would be trivial to add an audio cue someday @afre100

**Comment by rzhao271** [comment]
Search still says "The search results have been cleared"

**Comment by meganrogge** [comment]
@rzhao271 that's a case that I didn't think about, i'll make an issue
