### ISSUE TITLE
Tunnel not accessible via vscode

### ISSUE THREAD

**Issue by samxu29** [microsoft/vscode#194749]
Type: <b>Bug</b>

- Login and register the code cli with github account
- Start the code tunnel using ./code tunnel --accept-server-license-terms
- Tunnel accessible with web ui at vscode.dev/tunnel/xxx
- Not server accessible via vscode gui "connect to tunnel"

VS Code version: Code 1.82.3 (fdb98833154679dbaa7af67a5a29fe19e55c2b73, 2023-10-02T10:49:50.455Z)
OS version: Linux x64 6.4.6-76060406-generic
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz (8 x 3800)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|1, 2, 1|
|Memory (System)|15.32GB (4.65GB free)|
|Process Argv|--unity-launch --crash-reporter-id 35064eee-bc85-4fb8-b63d-1df5abd1c3cc|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|pop|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|pop|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (21)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-django|bat|1.14.0
python-environment-manager|don|1.2.4
python-extension-pack|don|1.7.0
vsc-python-indent|Kev|1.18.0
rainbow-csv|mec|3.7.1
python|ms-|2023.16.0
vscode-pylance|ms-|2023.9.30
jupyter|ms-|2023.8.1002501831
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.17
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-slideshow|ms-|0.1.5
remote-ssh|ms-|0.106.4
remote-ssh-edit|ms-|0.86.0
cpptools|ms-|1.17.5
remote-explorer|ms-|0.4.1
remote-server|ms-|1.4.3
autodocstring|njp|0.6.1
intellicode-api-usage-examples|Vis|0.2.8
vscodeintellicode|Vis|1.2.30
jinja|who|0.0.8

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
6c1a3589:30846784
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
3biah626:30602489
f6dab269:30613381
a9j8j154:30646983
showlangstatbar:30737416
0bi6i642:30841073
03d35959:30757346
pythonfmttext:30731395
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
pythonnosmt12:30797651
pythonidxpt:30805730
pythonnoceb:30805159
copilotsettingc:30839828
dsvsc013:30795093
dsvsc014:30804076
diffeditorv1:30821571
dsvsc015:30845448

```

</details>

**Comment by samxu29** [comment]
Might be a duplicate? 
https://github.com/microsoft/vscode-remote-release/issues/9057

**Comment by connor4312** [comment]
Duplicate indeed
