### ISSUE TITLE
[scss] Hover tooltip should show media queries

### ISSUE THREAD

**Issue by hb20007** [microsoft/vscode#194707]
Currently, the SCSS hover tooltip does not show media queries. For example:
![screenshot](https://github.com/microsoft/vscode/assets/8860322/38e1d058-cb77-4d8b-bba5-197b48ab7344)

In a long CSS file, I rely on the tooltip to understand which selector I am looking at. Showing the media query in the tooltip would be very helpful in cases where the media query was declared several lines before. This will avoid having to scroll up to understand if there are any applicable media queries.

**Comment by balaji-sivasakthi** [comment]
@aeschli  I would like to work on this

**Comment by balaji-sivasakthi** [comment]
@hb20007, please confirm whether your feature works on the Atom editor because it relies on https://github.com/atom/language-sass/blob/master/grammars/scss.cson.

**Comment by hb20007** [comment]
@balaji-sivasakthi I am not familiar with Atom. I tried to download it and I don't see any hover tooltip at all. I also tried searching for any CSS or PostCSS packages but there were no results.

Also, please note that there is at least one other issue related to the SCSS tooltip: https://github.com/microsoft/vscode/issues/72608

**Comment by balaji-sivasakthi** [comment]
@hb20007 It would be a better option to wrap up with a `@media`  signature when hovering over a specific selector, thus it will ensure that the CSS selector is in the media body.

![image](https://github.com/microsoft/vscode/assets/65065614/ff511b77-c59f-4695-af6d-4ede63519df0)

![image](https://github.com/microsoft/vscode/assets/65065614/32ac9638-5038-4c0b-aed3-14911090e7d0)

**Comment by balaji-sivasakthi** [comment]
> Also, please note that there is at least one other issue related to the SCSS tooltip: https://github.com/microsoft/vscode/issues/72608 

Thanks for sharing, I hope it will help a lot.

**Comment by balaji-sivasakthi** [comment]
![image](https://github.com/microsoft/vscode/assets/65065614/1ea2e3de-ba2d-4016-83f8-5a2a359a4189)

@hb20007 Is this ok?

**Comment by hb20007** [comment]
@balaji-sivasakthi, how will it look in the following scenarios?
1. If the media query is nested between other selectors? For example, <ol> @media .class
2. If the media query has minimum width and height? (I believe that those need to be shown on the tooltip, including "only screen")

**Comment by balaji-sivasakthi** [comment]
```scss
@media only screen {
    .foo {
        &-bar {
  
        }
    } 
}
```

![image](https://github.com/microsoft/vscode/assets/65065614/d940f688-7f68-4003-926c-73b1376e6cf5)

**Comment by hb20007** [comment]
@balaji-sivasakthi, it looks great, but what about if the media query is nested between `.foo` and `&-bar`? I hope that in that case it will also be shown correctly on the tooltip.

**Comment by balaji-sivasakthi** [comment]
@hb20007 there are some problems with that case, I couldn't place the media query label in-between the two selectors. Actually I just appended the media declaration, before the markdown string once I find `@media`. Thus it returns the top of the tooltip.

**Comment by balaji-sivasakthi** [comment]
> but what about if the media query is nested between .foo and &-bar? I hope that in that case it will also be shown correctly on the tooltip.
![image](https://github.com/microsoft/vscode/assets/65065614/1e92d53b-4464-43d2-97e4-1394dbd42ca0)

**Comment by hb20007** [comment]
-@balaji-sivasakthi Ah okay, so it will be shown on top instead of in the same order. It looks fine to me, as the important thing is to know that the media query is applicable to the selector which you are editing, and not where exactly it is in the hierarchy. Even like this, it would be great to have this feature in VS Code.

**Comment by hb20007** [comment]
It's worth noting that the sticky scroll feature (`editor.stickyScroll.enabled`) already pins media queries to the top along with class names, so this change will align the tooltip behavior with the existing sticky scroll behavior.
