### ISSUE TITLE
vscode tunnels not showing up

### ISSUE THREAD

**Issue by DaneHou** [microsoft/vscode#194724]
<img width="385" alt="image" src="https://github.com/microsoft/vscode/assets/14223172/3b18ff76-b0cf-4633-b347-3316a196f6a4">

checked this on multiple devices and even webpage ones, tunnels not showing up in the list

there were events yesterday that tunnel servers could not be setup due to connection issues with main server (by vscode)? it was gone last night but since then even the server is back, the list is still gone

**Comment by shane-graham** [comment]
I can confirm this issue started for me yesterday.  The registered tunnels do not show up in the Remotes (Tunnels/SSH) UI element in vscode on macos or in vscode.dev.  However if I navigate in the browser to https://vscode.dev/tunnel/[tunnel_name] vscode.dev can connect to the tunnel.

**Comment by connor4312** [comment]
Duplicates https://github.com/microsoft/vscode-remote-release/issues/9054, should be fixed quite soon
