### ISSUE TITLE
Close window dialogue gets shown multiple times on pressing 'Cancel'

### ISSUE THREAD

**Issue by brookjordan** [Microsoft/vscode#19471]
- VSCode Version: 1.8.1
- OS Version: Sierra 10.12.2

**Steps to Reproduce:**

1. Create a new file
2. Put something into that file so that it brings up a dialogue when trying to close it
3. Press cmd-w (close window) multiple times
4. Click cancel

The same dialogue will come up multiple times rather than cancelling the rest of the stack of close commands.

**Possible expected results:**
- The rest of the commands are removed
- The focus moves to the next tab upon pressing cancel and that one is attempted to be closed instead

**Comment by mousetraps** [comment]
Thanks for reporting! Indeed, I can also reproduce this using the insiders build on Mac (but not Windows.)

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/11928
