### ISSUE TITLE
"Looking for remote tunnel" on fresh user startup

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#194799]
After starting up VS Code for the first time, something strange appears in the status bar:

![Image](https://github.com/microsoft/vscode/assets/22350/f7b918c0-70d5-400d-80f9-ad901b580a3a)

Click it. Then click the notification link. The output opens empty. Wait long enough and an error comes up:

![Image](https://github.com/microsoft/vscode/assets/22350/c376ff17-c32a-4e70-9f5c-cc8266401a9c)

**Comment by connor4312** [comment]
- The "syntax error" will log the output, so if you see that again, please share more details
- @aeschli what do you think about not showing the "Looking for tunnel" progress on startup? Most users don't use remote tunnels, so this is just noise.
