### ISSUE TITLE
Markdown: slight flickering in preview while editing

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#19475]
Follow up from https://github.com/Microsoft/vscode/issues/19351, there is still a little bit of flickering when editing a markdown file while having the preview open.

My setup:
* editing our release notes (that is some good amount of text with images)
* zoom level 1

Would be awesome if it was possible to avoid flicker alltogether.

**Comment by mjbvz** [comment]
This at least partially seems to be caused by the badge icons in the release notes being reloaded on each update. I have noticed it more in documents that have images, especially when those images cannot be cached

**Comment by mjbvz** [comment]
This should be fixed by recent changes to how the markdown previews replaces its contents
