### ISSUE TITLE
The integrated terminal uses fish shell and it lacks the auto completion. Also the working directory doesn't mounts by itself ,have to cd into the directory.

### ISSUE THREAD

**Issue by krtkeyan** [Microsoft/vscode#19472]
- VSCode Version: Code 1.8.1 (ee428b0eead68bf0fb99ab5fdc4439be227b6281, 2016-12-19T14:49:23.350Z)
- OS Version: Windows_NT ia32 10.0.15014
The integrated terminal uses fish shell and it lacks the auto completion. Sometimes the terminal hangs for few seconds on tab completion. Also, the working directory doesn't mount by itself , have to cd into the directory.

**Comment by mousetraps** [comment]
Hey @krtkeyan, thanks for reporting! Unfortunately I can't reproduce the issue. A few Qs to help narrow it down:
1. when yous say it "uses fish shell", do you mean you've configured it to use fish on bash on Windows? Or something else?
When you say the working directory doesn't automount itself - what's the directory that it starts you in? And what's the directory that you expect to start in?
2. When you say it "lacks auto completion" - is this for everything you try, or only some things? Does it include tab completion as well?
3. When you say "the terminal hangs for a few seconds on tab completion", what happens after the hang? Does what you were typing complete correctly? Is this behavior reproducible, or somewhat flaky?

Thanks in advance!
