### ISSUE TITLE
Vscode flashing black box cannot be opened "launch failed", code "18“

### ISSUE THREAD

**Issue by sclang007** [microsoft/vscode#194773]
After reinstalling the Win10 22H2 system, the vscode installed on a non system disk could not be opened, and multiple methods were tried
1. Download the latest versions 1.82.3 and 1.82.1 of x86 and x64. Delete the. vscode folder after uninstallation.
2. Use compatibility mode
Error Image
1. Without using compatibility mode, there will be black box flickering, sometimes 4 such black boxes, sometimes one.
![1](https://github.com/microsoft/vscode/assets/46955708/fa262da0-030a-4100-8744-071c6ca75962)
2. Use compatibility mode (administrator mode+win7, win8, vsta) and pure administrator mode,
Compatibility mode will pop up the black box in the figure above, and adding administrator mode or pure administrator mode will pop up the launch delivered code 18 in the figure below. Error
![2](https://github.com/microsoft/vscode/assets/46955708/ef213c31-b3e2-4c52-a5f8-b41906df2ce7)
3. Using the netsh winsock reset command resulted in no response

**Comment by deepak1556** [comment]
> the vscode installed on a non system disk could not be opened

Can you clarify this statement. Which path is VSCode being installed to ?

Compatibility mode with win7, win8, vsta is not tested to work with latest version of VS Code since we dropped support for these platforms.

Can you launch without compatibility mode using the following arguments `code --verbose` and attach the output in this issue.

**Comment by sclang007** [comment]
Yes, it has been installed in 'D: Program Files Microsoft VS Code' and cannot be opened without using compatibility mode. Multiple versions cannot be opened

But now it can be opened without using startup parameters. I only modified the "null. sys" file today, and the previous version was revoked by the certification authority. I guess it should be due to the "null. sys" file,

It should have been modified by the driver of a certain device,



thank you

**Comment by deepak1556** [comment]
Thanks for confirming, closing since issue is resolved.

/duplicate https://github.com/microsoft/vscode/issues/185298
