### ISSUE TITLE
Theme colour applied to SVG icons 

### ISSUE THREAD

**Issue by pouyakary** [microsoft/vscode#194710]
Type: <b>Bug</b>

The Flutter extension (as well as many other extensions) put extra icons in the debug controls:

<img width="543" src="https://github.com/microsoft/vscode/assets/2157285/24732cea-03c9-4fdd-a0ce-a066ea58dac0">

Now that the controls can be placed on the command center (#192592) it seems that some of them break:

<img width="750" src="https://github.com/microsoft/vscode/assets/2157285/3ae0d013-bc83-4954-9f98-bd8145b73f24">

I don't know if this is something that the author should fix or it is due to the changes in the vscode (Perhaps @DanTup should have a look as well) but I think its a breaking change that effects many other extensions as well.

VS Code version: Code - Insiders 1.83.0-insider (4268e464763087044d0c1b5bdd37ebbe683cadfa, 2023-09-29T20:44:05.310Z)
OS version: Darwin arm64 23.0.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|8.00GB (0.09GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|13.4.1
dart-code|Dar|3.75.20231002
flutter|Dar|3.74.0
copilot|Git|1.121.461
copilot-chat|Git|0.8.2023092902
todo-tree|Gru|0.0.226
comment|kar|23.3.0
justifier|kar|0.0.5
moves|kar|1.0.1
theme-karyfoundation-themes|kar|34.3.0
virtuous-vscode|kar|0.0.7
code-spell-checker|str|3.0.1
tldraw-vscode|tld|2.0.11

</details>

**Comment by jrieken** [comment]
@DanTup does your extension use an icon font or SVGs?

**Comment by DanTup** [comment]
It's an SVG:

https://github.com/Dart-Code/Dart-Code/blob/97cd316e830d9265768c578f0246255a1fab06d9/package.json#L534-L537

https://github.com/Dart-Code/Dart-Code/blob/master/media/commands/hot-reload.svg

**Comment by DanTup** [comment]
This came up at https://github.com/dart-lang/sdk/issues/53690, although this just looks like an undocked toolbar and not specific to the command center?

**Comment by jrieken** [comment]
Yes - it unrelated to CC but a consequence (regression) from https://github.com/microsoft/vscode/issues/190679 which applies theming colors to SVG based icons too.

**Comment by jrieken** [comment]
So, we did this change on purpose so that theme colors (for icons) can be applied to uniformly across the different icon types. Tho, I do acknowledge 
* how it makes the dart icon look bad,
*  and how it doesn't allow for the toggled trick (@pflannery we do have a separate FR for that. somewhere...)

**Comment by DanTup** [comment]
> so that theme colors (for icons) can be applied to uniformly across the different icon types

What's the correct way to colour icons with specific colours in this case? (for example the stop button is still red)?

It also seems like the icon has been stretched in some way - do you know what's causing that?

**Comment by pflannery** [comment]
@jrieken I've been looking at this today and I've discovered that when loading svg's using `-webkit-mask` the svg colours are interpreted as an alpha value. I.E. where black is invisible and white is fully visible.

It also seems that this change has made the light and dark options under `contributes\commands` in the package.json obsolete? as now there isn't really anything we can do with those options.

I've found a way to make svg icons to appear enabled or not. This involves using the svg mask element to create a semi transparent background. 

![image](https://github.com/microsoft/vscode/assets/1727302/df0c8efc-7470-4e16-834c-80c6e2bc8598)

![image](https://github.com/microsoft/vscode/assets/1727302/69ef2c28-3659-4bed-b7e6-ce6fcc9ac598)

![image](https://github.com/microsoft/vscode/assets/1727302/6ce68275-3c91-4146-9976-44c793a2e157)

[enabled svg sample](https://gitlab.com/versionlens/vscode-versionlens/-/blob/master/images/icons/toggle-active.svg?ref_type=heads&plain=1) 

[disabled svg sample](https://gitlab.com/versionlens/vscode-versionlens/-/blob/master/images/icons/toggle-inactive.svg?ref_type=heads&plain=1)

I'm not able to resolve the red error icon that versionlens previously used so I've had to change the icon to look like a warning.

![image](https://github.com/microsoft/vscode/assets/1727302/d94409de-ee5c-47c8-b0e6-1d2ed96edcca)

imo I think it would be better that an extension author has ownership over their icons. Users can create requests with those authors regarding theme compatibility. Perhaps vscode could even allow extension icons to be overridden by theme authors or users similar to how [Product Icons](https://code.visualstudio.com/api/extension-guides/product-icon-theme) are?

**Comment by DanTup** [comment]
> imo I think it would be better that an extension author has ownership over their icons

I agree. Some of the built-in icons already have their own colours, so it seems clear that making them all the same isn't a good option.

If this must be supported, perhaps it could be done with a flag that says whether an icon should inherit a theme colour or not?

**Comment by DanTup** [comment]
@jrieken is there any workaround we could apply until this is resolved? We have multiple icons that show up in different contexts and they all look pretty bad now:

![image](https://github.com/microsoft/vscode/assets/1078012/d1f0a6c4-7132-4e33-91d4-024fa07c8042)

**Comment by nvuillam** [comment]
Similar issue wwith VsCode SFDX Hardis.

Before:
![image](https://github.com/microsoft/vscode/assets/17500430/b1473c37-3ab9-4f91-b163-c3bbe935dc0e)

After:
![image](https://github.com/microsoft/vscode/assets/17500430/175b1b09-37b9-4a28-b421-4b0fc07333d3)

**Comment by jrieken** [comment]
> I agree. Some of the built-in icons already have their own colours, so it seems clear that making them all the same isn't a good option.

This wasn't about making them all the same but about making them configurable. The idea being that that "all yellow theme" can tweak the dart-debug-flash to a better fit. That's what motivated and justified this change. Tho, I do see the technical limitations of the mask-approach and therefore we should revisit this.

The gist is that

* we will revert the change (with 1.83.x)
* we will deprecate image-based icons, the recommendation will be to use icon fonts
* we will forward theming bugs to the respective extensions
* we invite extension authors to adopt our CSS variables for theming SVG

**Comment by aeschli** [comment]
Verified in 1.83.1 candidate
