### ISSUE TITLE
Reloading the window with active tasks briefly shows them localized and then shows the English version

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#194717]
Repro:

1. Install and activate a non-English language pack
2. Open vscode repo
3. Run default build task
4. Reload window

![Image](https://github.com/microsoft/vscode/assets/2193314/aacca971-5c45-42ae-8769-95dfa7b497c4)

**Comment by aiday-mar** [comment]
So I opened up the vscode-copilot repo and ran the watch compilation task. Am I supposed to see the word `Task` in ther terminal in French? It appears to always be in English.

https://github.com/microsoft/vscode/assets/61460952/5c572bdd-2b08-43f5-ba77-494389be04f5

I installed the official French language pack from Microsoft from the store.

**Comment by Tyriar** [comment]
@aiday-mar for now I think that is expected as the backing localized string changed location so it's now shared. Localization and new language pack publishes happen at the end of endgame I believe. Given this I'm not even sure we can verify this until next month, so I'll move it there.
