### ISSUE TITLE
Title bar color settings not applied when app not focused

### ISSUE THREAD

**Issue by mael-belval** [microsoft/vscode#194781]
Type: <b>Bug</b>

1. Open a workspace
2. In the workspace settings, add these : 
```json
	"settings": {
		"workbench.colorCustomizations": {
			"titleBar.activeBackground": "#1d00ad",
			"titleBar.activeForeground": "#fff",
		}
	}
```
3. When the app lose focus (move to another screen, or focus another app).
4. VS Code stop applying the settings.
5. Focus back the app, or hover it with your cursor.
6. The settings will be applied again.

VS Code version: Code - Insiders 1.83.0-insider (Universal) (e7e037083ff4455cf320e344325dacb480062c3c, 2023-10-03T13:49:12.793Z)
OS version: Darwin arm64 23.0.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|2, 3, 3|
|Memory (System)|16.00GB (0.04GB free)|
|Process Argv|--crash-reporter-id f5d6a7d5-a715-46e0-a808-b354719852e7|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vslsvsres303:30308271
pythontb:30258533
pythonptprofiler:30281269
vshan820:30294714
vscod805cf:30301675
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30404738
py29gd2263:30784851
vscaat:30438846
vsclangdf:30492506
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30618038
2i9eh265:30646982
showlangstatbar:30737417
pythonfmttext:30716741
fixshowwlkth:30771523
showindicator:30805243
pythongtdpath:30726887
i26e3531:30792625
pythonnosmt12:30779711
pythonidxpt:30768918
pythonnoceb:30776497
dsvsc013:30777762
dsvsc014:30777825
diffeditorv2:30786206
pythonmpsinfo:30842935
dsvsc015:30821418
pythontestfixt:30826906
pythonfb280951:30830809
pythonregdiag:30842812
pythonmypyd1cf:30850306
pythoncet0:30848247

```

</details>

**Comment by gjsjohnmurray** [comment]
I think this is why the color names include the term "active".

**Comment by mael-belval** [comment]
My bad indeed.
