### ISSUE TITLE
Problem filter for active file not working with Jupyter Notebook

### ISSUE THREAD

**Issue by k2pctdn** [microsoft/vscode#194786]
Type: <b>Bug</b>

Repoduce the problem steps:
1. Create an empty folder, e.g., C\Test
2. Create two empty jupyter notebook files, e.g., `test1.ipynb`, `test2.ipynb` in the same folder.
3. Making some simple errors so that the problem appears, e.g., `import nump as np` (should be `import numpy as np`)
4. The warning appears in the PROBLEMS tab for both files.
5. When use the filter `Toggle for Active File`, no warning shows. 

VS Code version: Code 1.82.3 (fdb98833154679dbaa7af67a5a29fe19e55c2b73, 2023-10-02T10:51:22.294Z)
OS version: Windows_NT x64 10.0.19044
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|12th Gen Intel(R) Core(TM) i7-12700H (20 x 2688)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.69GB (16.46GB free)|
|Process Argv|--crash-reporter-id 4a673871-7d42-4cd1-becf-b8b1db1ba427|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (36)</summary>

Extension|Author (truncated)|Version
---|---|---
catppuccin-vsc|Cat|3.3.0
vscode-markdownlint|Dav|0.52.0
vscode-pull-request-github|Git|0.72.0
latex-workshop|Jam|9.14.1
better-cpp-syntax|jef|1.17.2
git-graph|mhu|1.30.0
auto-commit-msg|Mic|0.26.2
csharp|ms-|2.4.4
vscode-dotnet-runtime|ms-|1.8.0
isort|ms-|2023.10.1
mypy-type-checker|ms-|2023.2.0
python|ms-|2023.16.0
vscode-pylance|ms-|2023.9.30
jupyter|ms-|2023.8.1002501831
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.17
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-powertoys|ms-|0.0.8
vscode-jupyter-slideshow|ms-|0.1.5
remote-containers|ms-|0.309.0
remote-ssh|ms-|0.106.4
remote-ssh-edit|ms-|0.86.0
cmake-tools|ms-|1.15.31
cpptools|ms-|1.17.5
cpptools-extension-pack|ms-|1.3.0
remote-explorer|ms-|0.4.1
vsliveshare|ms-|1.0.5883
rose-pine|mvl|2.9.0
indent-rainbow|ode|8.3.1
material-icon-theme|PKi|4.30.1
vscode-ltex|val|13.1.0
intellicode-api-usage-examples|Vis|0.2.8
vscodeintellicode|Vis|1.2.30
vscode-icons|vsc|12.5.0
jupyter-toc|xel|0.2.1
markdown-all-in-one|yzh|3.5.1

(5 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
2e4cg342:30602488
f6dab269:30613381
showlangstatbar:30737416
03d35959:30757346
pythonfmttext:30731395
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
pythonnosmt12:30797651
pythonidxpt:30805730
pythonnoceb:30805159
copilotsettingt:30839829
dsvsc013:30795093
dsvsc014:30804076
diffeditorv1:30821571
dsvsc015:30845448

```

</details>

**Comment by rebornix** [comment]
Let's merge this into https://github.com/microsoft/vscode/issues/99155
