### ISSUE TITLE
Vscode ver. 1.82.3 don't work on ubuntu 20.04.6 LTS

### ISSUE THREAD

**Issue by donebd** [microsoft/vscode#194725]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.82.3
- OS Version: Ubuntu 20.04.6 LTS x86_64

Steps to Reproduce:

1. Start vscode

Expected behavior:
- all works

Actual behavior:
- nothing works

![изображение](https://github.com/microsoft/vscode/assets/55058233/db1e2e10-d5d0-4a69-adf9-cce995457900)

**Comment by gjsjohnmurray** [comment]
Please see https://code.visualstudio.com/updates/v1_82#_update-highlights-for-chromium and try the deletion of GPU cache it recommends.

**Comment by donebd** [comment]
This solve the problem, thx.
