### ISSUE TITLE
New Terminal lost focus when opened by command "openInIntegratedTerminal"

### ISSUE THREAD

**Issue by cuongthm** [microsoft/vscode#194738]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.82.3
- OS Version: Windows_NT x64 10.0.22621

Steps to Reproduce:

1. right click on a file name on Explorer view
2. choose "Open in integrated Terminal" command
3. new Terminal opened without focused

I have the setting "terminal.integrated.defaultLocation" modified to **"terminal.integrated.defaultLocation": "editor"**

**Comment by meganrogge** [comment]
I believe this is already fixed, can you see if you can reproduce in the [Insiders build](https://code.visualstudio.com/insiders)?
/label info-needed

**Comment by cuongthm** [comment]
I don't use Insiders build. I can wait for new release of Stable build to check it.

Thanks for your quick fix.

**Comment by cuongthm** [comment]
> I believe this is already fixed, can you see if you can reproduce in the [Insiders build](https://code.visualstudio.com/insiders)? /label info-needed

In the latest build v1.83.0, this issue hasn't fixed. The terminal still hasn't had focus on first start.

**Comment by meganrogge** [comment]
it's fixed in insider's 
https://github.com/microsoft/vscode/assets/29464607/a8606e6f-14de-4e62-ab55-c65c15fe18ea
