### ISSUE TITLE
Application data spread out on disk (Win10)

### ISSUE THREAD

**Issue by csholmq** [Microsoft/vscode#19479]
Besides my installation directory, I have found that application data is stored in multiple places.

With the exception of my workspace specific stuff, I have found most (all?) of my settings in `%APPDATA%\Code - Insiders`. But then I find my extensions in `%USERPROFILE%\.vscode-insiders`.

Is this how it's supposed to be? Perhaps it's just me that find it cumbersome to locate everything.

**Comment by mousetraps** [comment]
Hey @csholmq, thanks for reaching out! Indeed, you're right that it's strange behavior on Windows, and we are currently revisiting this decision, so I suggest following https://github.com/Microsoft/vscode/issues/3884 for more updates. Hope that helps!
