### ISSUE TITLE
can support extension classification?

### ISSUE THREAD

**Issue by LoadLife** [microsoft/vscode#194720]
so far, i have installed plenty of  extensions in VSCode. Some of them are used for cpp, some are used for python, etc...If can have the feature that sort the extension in different folders that i can enable or disable according to my different working purpose. : o ), thanks!

**Comment by gjsjohnmurray** [comment]
Have you looked at Profiles?

https://code.visualstudio.com/docs/editor/profiles

**Comment by LoadLife** [comment]
> Have you looked at Profiles?
> 
> https://code.visualstudio.com/docs/editor/profiles
thanks, it's useful, i didn't notice these in the document.
