### ISSUE TITLE
[snippet] Ability to add snippets from `.vscode` directory

### ISSUE THREAD

**Issue by Alber70g** [Microsoft/vscode#1947]
Ability to add snippets from `.vscode` directory, instead of `%APPDATA%/Roaming/Code/User/snippets`.

This would be nice for working with snippets in a specific project, then there is no need to create a snippet extension for private snippets, and install it separately because it's included in the project

**Comment by moostad** [comment]
+1

**Comment by Alber70g** [comment]
Any chance this will be implemented anytime?

**Comment by aeschli** [comment]
Sorry, there are currently no plans. PR are welcome.

**Comment by szyhf** [comment]
+1

**Comment by chongchai** [comment]
+1

**Comment by jrieken** [comment]
close as dupe of #8102 which is younger but more busy.
