### ISSUE TITLE
Disabled Python extension is being incorrectly detected as not installed

### ISSUE THREAD

**Issue by ulugbekna** [microsoft/vscode#194843]
### Applies To

- [X] Notebooks (.ipynb files)
- [ ] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

When I have Python extension disabled, I get a quick-pick item to 'Install Python Extension' 

<img width="1082" alt="image" src="https://github.com/microsoft/vscode-jupyter/assets/16353531/d9599714-37a5-4150-b4a8-4aaef13e1b86">

### VS Code Version

Version: 1.79.0-insider Commit: 784e72bc4486b7ea5ad3447c506e31d949848592 Date: 2023-05-30T05:23:26.066Z Electron: 22.5.4 Chromium: 108.0.5359.215 Node.js: 16.17.1 V8: 10.8.168.25-electron.0 OS: Darwin arm64 22.4.0

### Jupyter Extension Version

v2023.5.1001511100

### Running Jupyter locally or remotely?

None

**Comment by rebornix** [comment]
We now present `Install/Enable suggested extensions`.
