### ISSUE TITLE
"editor.codeActionsOnSave": { "source.sort.json": true } - Error

### ISSUE THREAD

**Issue by GBrachetta** [microsoft/vscode#194866]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.83.0
- OS Version: MacOS Sonoma

Steps to Reproduce:

1. Add the setting below:

```json
{
  "editor.codeActionsOnSave": {
    "source.sort.json": true
  }
}
```

The expected behaviour is to sort json files on save. In my case attempting to sort `settings.json` (on a profile).

Instead, I receive an error:

> Request json/sort failed with message: Range#create called with invalid arguments[[object Object], [object Object], undefined, undefined]

![Screenshot 2023-10-05 at 09 33 48](https://github.com/microsoft/vscode/assets/57924268/a7120dca-5945-4ff8-8a6a-012f6c97375b)

**Comment by justschen** [comment]
reverted to https://github.com/microsoft/vscode/tree/5bd7ca8a17010f410de6e69a5757086d732207b2 - can confirm that this is unrelated to https://github.com/microsoft/vscode/issues/194861

**Comment by GBrachetta** [comment]
It may be the case that the error happens in json files that have trailing commas somewhere.
`settings.json` is of type `JSON with comments (jsonc)` and trailing commas are allowed in that type of files.
Comments don't cause an error, though.

**Comment by justschen** [comment]
@GBrachetta revisiting this now that 1.83.1 is out. If you've updated to the latest stable version, does this issue still occur?

**Comment by justschen** [comment]
fixed with migration to enums.
