### ISSUE TITLE
breaking: codeActionsOnSave

### ISSUE THREAD

**Issue by ilteoood** [microsoft/vscode#194861]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.83.0
- OS Version: *

Steps to Reproduce:

With version 1.83.0, codeActionsOnSave accepts only an object. Unfortunately for my use case is deal-breaker because I would like to apply format and sorting **before** the lint. With the object configuration, it is not possible anymore.

This is my actual configuration:
```
"editor.codeActionsOnSave": {
    "editor.formatOnSave": "always",
    "source.organizeImports": "always",
    "source.sortImports": "always",
    "source.fixAll": "always"
  }
```

There is an old issue that describes my exact same case: https://github.com/microsoft/vscode/issues/88131.

Do you have any workaround to achieve the same result, or can you please consider rolling back the array configuration?

**Comment by gjsjohnmurray** [comment]
Source seems to indicate that array is still allowed:

https://github.com/microsoft/vscode/blob/7d4027b62bb1e620e5454580450fa646682bc102/src/vs/workbench/contrib/codeActions/browser/codeActionsContribution.ts#L40-L62

**Comment by gjsjohnmurray** [comment]
Or maybe when 153335bd0611fcb46cf7d0e879eca53e11f5d960 from @justschen added `type` and `additionalProperties` in lines 55-59 above these overrode the `oneOf` array at lines 41+ ?

**Comment by ilteoood** [comment]
> Or maybe when [153335b](https://github.com/microsoft/vscode/commit/153335bd0611fcb46cf7d0e879eca53e11f5d960) from @justschen added `type` and `additionalProperties` in lines 55-59 above these overrode the `oneOf` array at lines 41+ ?

This is possible. If I try with an array this is the result:
![image](https://github.com/microsoft/vscode/assets/6383527/498aaef7-2e77-40e6-9b79-fa39dc7e3499)

And no actions are performed

**Comment by justschen** [comment]
Error is coming from https://github.com/microsoft/vscode/commit/153335bd0611fcb46cf7d0e879eca53e11f5d960 in `saveParticipants`. 

Interesting case - when there are Code Actions in the array, even with the error (saying `Incorrect type...`), do code actions still run?

**Comment by ilteoood** [comment]
> Error is coming from [153335b](https://github.com/microsoft/vscode/commit/153335bd0611fcb46cf7d0e879eca53e11f5d960) in `saveParticipants` (lines 283, where `string[]` was replaced)
> 
> Interesting case - when there are Code Actions in the array, even with the error (saying `Incorrect type...`), do code actions still run?

I tried rolling back to my previous conf:
![image](https://github.com/microsoft/vscode/assets/6383527/5f52f150-8647-46c3-b573-1a413d6772f3)

```
"editor.codeActionsOnSave": [
    "editor.formatOnSave",
    "source.organizeImports",
    "source.sortImports",
    "source.fixAll"
  ]
```

And unfortunately no actions are performed

**Comment by justschen** [comment]
roger. looking at it rn, and draft PR is mentioned here. will take a look at this again first thing in the morning.

**Comment by ArturoDent** [comment]
Probably same issue on SO: [editor.codeActionsOnSave does not run in order: changes form VSCode 1.82 to VSCode 1.83](https://stackoverflow.com/questions/77236747/editor-codeactionsonsave-changes-form-vscode-1-82-to-vscode-1-83/77239079#77239079)

**Comment by justschen** [comment]
@ArturoDent not sure if you are the OP, but I wasn't able to find a difference in current behavior vs. what happens in 1.82. Do you have a repro of this for expected vs. current behavior?

**Comment by rcb4t2** [comment]
@justschen Thanks for taking this on! 

The difference in current behavior vs 1.82 is that in 1.83 array values are silently ignored, and code actions are not run on save

As you have mentioned, an object config is not suitable because we can't specify the order. This broke our dev environment, and we look forward to a fix. Thank you!

**Comment by Planeshifter** [comment]
Running into this issue as well, so it is very much appreciated @justschen that you are looking into this. 

Specifically, we are using a combination of Prettier and ESLint for formatting and linting to enforce [JS Standard Style](https://standardjs.com), which depends on the order in which the actions are applied. 

```json  
  "editor.codeActionsOnSave": ["source.formatDocument", "source.fixAll.eslint"],
  "editor.defaultFormatter": "esbenp.prettier-vscode",
```

Being able to format the document via Prettier and then applying ESLint fixes does not seem to be possible with the object notation right now.

**Comment by ilteoood** [comment]
Hi @justschen, here is a repro. Consider this spec file: https://github.com/orchy-mfe/orchy-core/blob/main/packages/web-component/src/configuration-client/httpConfigurationClient.spec.ts

Here is the behaviour of vscode 1.82:
https://github.com/microsoft/vscode/assets/6383527/dbbea965-3d57-4393-87b4-77eff17da0e0

While this is the behaviour of vscode 1.83, without any change in the configuration:
https://github.com/microsoft/vscode/assets/6383527/6fd9ee90-3db2-4cf0-93d6-91df72ee297a

If I update the configuration to be an object, this is the final result:
https://github.com/microsoft/vscode/assets/6383527/0090e1ed-6b7e-495d-ab4d-becc65ac1588

As you can see, at each save imports are flickering but never really fixed.

**Comment by justschen** [comment]
Candidate PR will just add back support for arrays for now! Under discussion atm if orderings from objects will be considered.

**Comment by justschen** [comment]
tests candidate for https://github.com/microsoft/vscode/issues/194861. 
insiders PR (when released): https://github.com/microsoft/vscode/pull/194870
release branch PR: https://github.com/microsoft/vscode/pull/194930

Things to test:
1. Search in settings for `Code actions on save`
2. `edit in settings.json`
3. Test scenarios for `explicit`, `always`, and `never` when saving normally, and do so again when Auto Save is enabled for `Window change` and `Focus Change`, as well as when Auto Save is enabled after delay (in which case nothing would happen).
4. Test scenarios for `true` and `false` in same conditions.
5. Code Actions with the array (ensure no error, runs like `true` and `false`).
6. Edge Cases: Scenarios like https://github.com/microsoft/vscode/issues/194978 where multiple types of source actions are used. 

Example for arrays:
```typescript
"editor.codeActionsOnSave": [
    "editor.formatOnSave",
    "source.organizeImports",
    "source.sortImports",
    "source.fixAll"
  ]
```

Runs when code actions are in the array, does not run when code actions are excluded from the array.

## Known issues:
- Intellisense only shows `source.fixAll` and `source.organizeImports`: https://github.com/microsoft/vscode/issues/161284

**Comment by kferch-teamworks** [comment]
Arrays for codeactionsonsave were what allowed the "Format Code Action", rohit-gohri.format-code-action to work.  This was important because the array determines the order which you can't do with an object.

**Comment by andreamah** [comment]
verified on latest insiders

Version: 1.84.0-insider (user setup)
Commit: eb4f3c149f34d82b9763a08230907cf79e7fc103
Date: 2023-10-10T07:26:46.161Z
Electron: 25.8.4
ElectronBuildId: 24154031
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.22621
