### ISSUE TITLE
Pasting images into markdown cells no longer adds a notebook attachment

### ISSUE THREAD

**Issue by amunger** [microsoft/vscode#194809]
I tested on Win11 & Win10.  It works as long as you start a new workbook and don't save the jupyter notebook.  Once you save the notebook, your pastes of images from the clipboard will no longer be treated as inline attachments.

_Originally posted by @beckerben in https://github.com/microsoft/vscode-jupyter/discussions/14408#discussioncomment-7180960_

**Comment by amunger** [comment]
Possibly getting overridden by a markdown file paste provider? @mjbvz

**Comment by beckerben** [comment]
@amunger were you able to replicate my findings?

**Comment by Yoyokrazy** [comment]
With the above investigation, I believe this is likely an issue with markdown paste providers, assigning @mjbvz to take a look at this. 

@beckerben, to clarify, are you expecting the images to be created on-disk upon paste, and referenced via an image markdown link? Or are you looking for the `attachment:filename` experience, with images stored in the notebook itself. The latter can be achieved and still works properly with the setting `"ipynb.pasteImagesAsAttachments.enabled": true`

**Comment by beckerben** [comment]
I prefer the later, where the images are stored in the notebook, this makes it easier to share with others in these scenarios.  This used to be working and then stopped working in the build I noted in the original question refenced, but I just tested in the latest build and it is back to working as expected, so must have been a bug that has now been fixed:

The version I just tested with is updated now and and it is working as expected with the ```"ipynb.pasteImagesAsAttachments.enabled": true```

Version: 1.83.1 (system setup)
Commit: f1b07bd25dfad64b0167beb15359ae573aecd2cc
Date: 2023-10-10T23:48:05.904Z
Electron: 25.8.4
ElectronBuildId: 24154031
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.19045

**Comment by mjbvz** [comment]
Works fine for me too with the default settings. Will disable pasting into untitled notebooks with the setting off
