### ISSUE TITLE
Focus the browser on when the debugger toolbar is in the command center

### ISSUE THREAD

**Issue by usamazansari** [microsoft/vscode#194899]
With `"debug.toolBarLocation": "commandCenter"` settings, if I click on the `Start Debugging` in the Run and Debug view it errors out with the message `It looks like a browser is already running from an old debug session.`

How about changing the `Start Debugging` button to `Focus Browser` button in this case? This could be achieved either by clicking on it directly or <kbd>Alt + Click</kbd>.

**Comment by roblourens** [comment]
I don't think that would help the problem- you aren't debugging, you want to debug. The message is complaining about a stale browser process preventing us from launching a new browser to debug.
