### ISSUE TITLE
Incorrect formatting of text from traceback

### ISSUE THREAD

**Issue by david-waterworth** [microsoft/vscode#194844]
### Applies To

- [X] Notebooks (.ipynb files)
- [ ] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

When a `python` cell throws an exception, links to source files are inserted but this messes up text that should not be linked, for example

AttributeError: 'Australia/Sydney' object has no attribute 'key'

is displayed as

![image](https://github.com/microsoft/vscode-jupyter/assets/5028974/b3e58b53-ba89-4639-914c-7a4e93dc5289)

And the output is converted to

``` text
AttributeError: 'Australia[/Sydney](https://file+.vscode-resource.vscode-cdn.net/Sydney)' object has no attribute 'key'
```

To reproduce

```python
rasie AttributeError("'Australia/Sydney' object has no attribute 'key'")
```

This seem to occur when any text contains a forward slash. It makes it harder to share error messages with other library developers etc. since you cannot copy/paste the raw text of the traceback.

### VS Code Version

Version: 1.78.2 Commit: b3e4e68a0bc097f0ae7907b217c1119af9e03435 Date: 2023-05-10T14:47:05.613Z Electron: 22.5.2 Chromium: 108.0.5359.215 Node.js: 16.17.1 V8: 10.8.168.25-electron.0 OS: Linux x64 5.15.0-71-generic Sandboxed: No

### Jupyter Extension Version

v2023.4.1011241018

### Coding Language and Runtime Version

Pytohn 3.10

### Running Jupyter locally or remotely?

Local

**Comment by amunger** [comment]
this should be fixed in the latest version
