### ISSUE TITLE
Dollar sign not beeing highlighted when double clicking variable

### ISSUE THREAD

**Issue by stibay** [Microsoft/vscode#19483]
VS Code 1.8.1
Windows 7

When I try to double click any of the variable names with a dollar sign ($) in my angular code the dollar sign is not beeing highlighted.

For example double clicking on $scope here only marks scope.
`$scope.data = data;`

Is there an easy fix for this?

**Comment by mousetraps** [comment]
Interesting - the dollar sign is being tokenized as part of $scope, so not sure what's up. 
![image](https://cloud.githubusercontent.com/assets/762848/22400273/1d84c07e-e565-11e6-946b-8931dc4c93b2.png)

@alexandrudima @rebornix - any ideas?

**Comment by alexandrudima** [comment]
@stibay Please configure the setting `editor.wordSeparators` to your liking.

Here is the default (notice how `$` is listed as a word separator):
```
"editor.wordSeparators": "`~!@#$%^&*()-=+[{]}\\|;:'\",.<>/?",
```

**Comment by stibay** [comment]
Ah perfect :+1:  Maybe that should be standard (like it's in Visual Studio)?
