### ISSUE TITLE
Terminal find: right click execution error

### ISSUE THREAD

**Issue by tisilent** [microsoft/vscode#194814]
Version: 1.82.3 

https://github.com/microsoft/vscode/assets/48614781/b0afdac3-c0d3-408b-8a33-47cad81254ab

Right click on the text input box.

**Comment by meganrogge** [comment]
@tisilent thanks for looking into this - can you reproduce the issue in insider's? in this gif, I click the input box, right click, and it seems to work.


https://github.com/microsoft/vscode/assets/29464607/d44bd5ec-3221-40ed-8748-bd8b54c8e985

**Comment by tisilent** [comment]
@meganrogge Set right click behavior to copyPaste to reproduce. 
I think the context menu of the input box should not display the context menu of the term.
