### ISSUE TITLE
Changes for 1.83.0 incorrectly mention Perl 5

### ISSUE THREAD

**Issue by coke** [microsoft/vscode#194855]
Does this issue occur when all extensions are disabled?: N/A

- VS Code Version: 
- OS Version: 

Steps to Reproduce:

The notes say
>[Languages](https://code.visualstudio.com/updates/v1_83#_languages)
[Perl 5/Raku](https://code.visualstudio.com/updates/v1_83#_perl-5raku)
The Perl 5 language has been renamed to Raku (language identifier raku), and Raku will be automatically selected as the language for .raku files.

This should refer to Perl 6 and Raku instead.

Perl 5 remains its own separate language.

**Comment by duianto** [comment]
There's an open issue in the vscode-docs repo, which seems to handle the release notes:
Typo in release notes regarding Perl 6/Raku renaming https://github.com/microsoft/vscode-docs/issues/6712

**Comment by coke** [comment]
Closing this issue, thanks!
