### ISSUE TITLE
The View > Output menu item doesn't show its shortcut

### ISSUE THREAD

**Issue by eli-green** [Microsoft/vscode#19488]
- VSCode Version: Code 1.8.1 (ee428b0eead68bf0fb99ab5fdc4439be227b6281, 2016-12-19T14:41:20.664Z)
- OS Version: Linux x64 4.8.13-1-ARCH
- Extensions:

|Extension|Author|Version|
|---|---|---|
|EditorConfig|EditorConfig|0.3.4|
|fish|TeddyDD|0.0.4|
|vscode-eslint|dbaeumer|1.2.2|
|githistory|donjayamanne|0.1.5|
|python|donjayamanne|0.5.6|
|rest-client|humao|0.12.1|
|Go|lukehoban|0.6.52|
|MagicPython|magicstack|1.0.3|
|cpptools|ms-vscode|0.10.0|
|RustyCode|saviorisdead|0.19.1|
|vue|seanwash|0.4.2|
|vscode-lldb|vadimcn|0.3.2|

---

Despite the shortcut being part of the standard set of shortcuts (at least under Linux, it's Ctrl+K Ctrl+H)

Steps to Reproduce:

1. Check the default keybindings.json (Linux):
`{ "key": "ctrl+k ctrl+h",         "command": "workbench.action.output.toggleOutput" },`
2. Look at the View menu, the "Output" item has no shortcut listed. I spent a few minutes trying to add one only to find that it already existed, it just wasn't being shown in the menu.

**Comment by mousetraps** [comment]
Hey @eli-green, thanks for reporting. 

I couldn't reproduce this issue on Windows, so it might be OS-specific.

**Comment by chrmarti** [comment]
Upstream issue, we are tracking it with #14622.
