### ISSUE TITLE
Cannot rename a JSX component

### ISSUE THREAD

**Issue by saramorillon** [microsoft/vscode#194862]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.83.0
- OS Version: Windows 11

**Steps to Reproduce:**

1. Given the following jsx code:
```jsx
function Page() {
  return <Component />;
}

function Component() {
  return <div />;
}
```
2. Click on the word Component on line 2 and press F2 to rename. Enter Component2, press enter.

**Expected result**
The function Component is renamed to Component2

**Current result**
Nothing happens

_Note_
This seems not to be related to v1.83.0 as I get this issue with v1.80.2 as well. It seems related to JSX component. If I replace `return <Component />` by `return Component()`, I can rename the function.

**Comment by mjbvz** [comment]
Try setting `"typescript.preferences.renameMatchingJsxTags": false` or "`javascript.preferences.renameMatchingJsxTags": false`

By default renaming on jsx tags renames just the matching tag, not all references to it

**Comment by saramorillon** [comment]
Didn't know that, thanks!
