### ISSUE TITLE
Unable to open files when links to file paths are printed in Jupyter outputs ending with a period

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode#194839]
Create a file named `<fully qualified Path>xyz.txt`
Run the code `print("<fully qualified Path>xyz.txt")` in a notebook and you can open the file from the link in the output

Run the code `print("<fully qualified Path>xyz.txt.")` in a notebook and you  cannot open the file from the link in the output.

I know this was reported earlier a few times, but couldn't find the issue.
Creating this as Daniel has solved this in the terminal (back when it was reported in Jupyter, I think we decided to leave it as is, because it didn't work in the terminal either)

https://github.com/microsoft/vscode/issues/186661

**Comment by amunger** [comment]
duplicate of https://github.com/microsoft/vscode/issues/177854
