### ISSUE TITLE
no device

### ISSUE THREAD

**Issue by vandg55** [microsoft/vscode#194891]
Type: <b>Bug</b>

While I am running my flutter project through my emulator and it works completely fine and I rerun again my flutter project without any change in my code or any related files in my project suddenly the vscode failed to detect my device it continues to load. I have an extension for android and ios emulator.

VS Code version: Code 1.83.0 (e7e037083ff4455cf320e344325dacb480062c3c, 2023-10-03T16:12:16.321Z)
OS version: Windows_NT x64 10.0.22621
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 5700X 8-Core Processor              (16 x 3400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.89GB (2.14GB free)|
|Process Argv|--crash-reporter-id 1474977e-2f03-456d-a725-c4733e8abee1|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (29)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-django|bat|1.14.0
flask-snippets|cst|0.1.3
dart-code|Dar|3.74.0
flutter|Dar|3.74.0
composer-php-vscode|DEV|1.39.13943
phptools-vscode|DEV|1.39.13943
profiler-php-vscode|DEV|1.39.13943
emulate|Die|1.6.0
python-environment-manager|don|1.2.4
python-extension-pack|don|1.7.0
figma-vscode-extension|fig|0.2.7
vsc-python-indent|Kev|1.18.0
flutterflow-code-export|kra|0.0.7
csharp|ms-|2.5.30
vscode-dotnet-runtime|ms-|1.8.0
python|ms-|2023.16.0
vscode-pylance|ms-|2023.10.10
autodocstring|njp|0.6.1
java|red|1.23.0
vscode-yaml|red|1.14.0
intellicode-api-usage-examples|Vis|0.2.8
vscodeintellicode|Vis|1.2.30
vscode-gradle|vsc|3.12.7
vscode-java-debug|vsc|0.54.0
vscode-java-dependency|vsc|0.23.1
vscode-java-pack|vsc|0.25.14
vscode-java-test|vsc|0.40.0
vscode-maven|vsc|0.42.0
jinja|who|0.0.8

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
py29gd2263:30792226
vscaac:30438847
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
3biah626:30602489
f6dab269:30613381
a9j8j154:30646983
showlangstatbar:30737416
0bi6i642:30841073
03d35959:30757346
pythonfmttext:30731395
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
pythonnosmt12:30797651
pythonidxpt:30805730
pythonnoceb:30805159
copilotsettingc:30839828
dsvsc013:30795093
dsvsc014:30804076
diffeditorv1:30821571
dsvsc015:30845448

```

</details>

**Comment by roblourens** [comment]
Please file an issue on the Flutter extension, thank
