### ISSUE TITLE
Opening quick text search with a selection should select the text in the input by default

### ISSUE THREAD

**Issue by TylerLeonhardt** [microsoft/vscode#194835]
Steps to Reproduce:

* set up a keybinding to launch quick text search
* open a diff editor
* select some text
* launch quick text search

Expected:

The text to be highlighted:

![Image](https://github.com/microsoft/vscode/assets/2644648/d6b43f53-b25f-468d-9174-155b748027fb)

Actual:

The text is not highlighted:

![Image](https://github.com/microsoft/vscode/assets/2644648/87750492-5731-4c8a-854d-2459a8d0a8e3)

Highlighting it is good because if I _don't_ want my selection to be used, I just type over it. This aligns with the find widget:

![Image](https://github.com/microsoft/vscode/assets/2644648/80bc6a78-591f-4b5d-a34c-42318c0fa4a3)

**Comment by Gobinath-B** [comment]
@TylerLeonhardt can you share your system info and version informations

**Comment by TylerLeonhardt** [comment]
OS doesn't matter much for this issue, but I'm on macOS. And I always use the latest insiders :)

**Comment by andreamah** [comment]
I think this is a /duplicate https://github.com/microsoft/vscode/issues/195180
