### ISSUE TITLE
Debugging a node.js process under ext-host spawns a process under shared process

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#194878]
Not yet sure if its a bug in how we show processes or not. Steps:
* on macOS use insiders
* open process explorer
* right click on the first node process in extension host
* select "Debug"

🐛 notice how a child process appears under the shared process

<img width="1572" alt="image" src="https://github.com/microsoft/vscode/assets/900690/7511c67e-6f59-4cea-8e85-7df76606fa69">

//cc @joaomoreno

**Comment by connor4312** [comment]
Based on the scripts loaded in that process, it appears to be related to telemetry

<img width="600" alt="image" src="https://github.com/microsoft/vscode/assets/2230985/4ca1f83b-e5a6-4bc9-ae46-8bc47fcd1f79">

**Comment by lramos15** [comment]
Don't really plan to address this anytime soon unless we delete the debug adaptor telemetry process. Will call it wont fix for now. There should be no issues having multiple SDKs if that's something we want
