### ISSUE TITLE
Missing Window menu

### ISSUE THREAD

**Issue by oviano** [microsoft/vscode#194892]
Type: <b>Bug</b>

On the macOS version there is a handy Window menu at the top for switching between windows when you have opened projects in separate windows.

On Windows this is missing - instead you have to switch between the windows via the Windows taskbar.

Can we have a Window menu on Windows too, so I don't have to keep getting caught out when switching between the two environments?

VS Code version: Code 1.83.0 (e7e037083ff4455cf320e344325dacb480062c3c, 2023-10-03T16:12:16.321Z)
OS version: Windows_NT x64 10.0.22621
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|12th Gen Intel(R) Core(TM) i7-12700 (20 x 2112)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.79GB (24.49GB free)|
|Process Argv|--crash-reporter-id 3a0bc6fc-b3fb-49b5-9614-8f5d2eb0b200|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
cmake-tools|ms-|1.15.31
cpptools|ms-|1.17.5
cmake|twx|0.0.17

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
3biah626:30602489
89544117:30613380
2i9eh265:30646982
showlangstatbar:30737416
03d35959:30757346
pythonfmttext:30731395
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
pythonnosmt12:30797651
pythonidxptcf:30805731
pythonnoceb:30805159
copilotsettingc:30839828
synctok:30821570
dsvsc013:30795093
dsvsc014:30804076
diffeditorv1:30821571
dsvsc015:30845448

```

</details>

**Comment by sbatten** [comment]
That menu is part of macOS

**Comment by oviano** [comment]
So add it to the Windows version too then?

<img width="531" alt="Screenshot 2023-12-21 at 09 09 19" src="https://github.com/microsoft/vscode/assets/621629/a1332fbb-b390-4371-9669-b5c1799a4349">

<img width="361" alt="Screenshot 2023-12-21 at 09 09 29" src="https://github.com/microsoft/vscode/assets/621629/9e4460ce-9845-42e4-b7aa-56203d4e2c42">
