### ISSUE TITLE
update issue as addministrator

### ISSUE THREAD

**Issue by Sayed-NaseemHaidari** [microsoft/vscode#194818]
from SayedNaseem Haidari.
In the name of Allah, ar-Rahman,ar-Raheem.
email: sayednaseem.haidari@gmail.com

Hello; I am having an issue with VC code updates as administrator. 
When i try to open VS code it did not allowed me due some javascript error. I have not downloaded JavaScript at all but i dont know, why i had that error message. I unstilled VS code. After reinstalled. but some reason I could not install. but after sometime when I reinstalled.  I was get this message.  and i quote.
"Updates are disabled because you are running the user-scope installation of Visual Studio Code as Administrator." 

could please help with is issue.

Thank you

**Comment by joaomoreno** [comment]
Please use the system setup: https://code.visualstudio.com/docs/?dv=win64
