### ISSUE TITLE
Missing React syntax highlight for object-value

### ISSUE THREAD

**Issue by ThisIsManta** [Microsoft/vscode#19487]
- VSCode Version: 1.8.1
- OS Version: Windows 10 Home

**See this picture** https://1drv.ms/i/s!AopesDuNO8Zogp5mv8fihnigFgxJCQ

However, as soon as I wrap the React component inside a pair of parenthesis (...), the syntax highlighting works as expected.
```
content: (<AccountProfilePane user={this.props.currentUser} />)
```

I can confirm that it has **no syntax errors** and the language mode was set to **JavaScript React**.

**Comment by mousetraps** [comment]
@ThisIsManta thanks for reporting! Indeed I managed to reproduce this issue using the following code in the `Light (Visual Studio)` theme:
```jsx
const tabs = [
    {
        content: <AccountProfilePane user={ this.props.currentUser } />
    }
]
```

The good news is that this issue now appears to be addressed in the latest [insiders builds](https://code.visualstudio.com/insiders)! So please give it a spin, and lets us know what you think!

**Comment by ThisIsManta** [comment]
I'm glad to hear that it will be fixed in the next version of VS Code.
Thank you very much
