### ISSUE TITLE
Posibility to have second activity bar

### ISSUE THREAD

**Issue by rajzik** [microsoft/vscode#194882]
Currently secondary sidebar has tabs when I add multiple items to it, I would love to have secondary activity bar instead. 
Usually, I put stuff to the secondary sidebar that I don't use that often, like copilot labs and gitlens, so I don't have side bar opened that often, but I would love to have access directly not by opening the second sidebar and selecting tab after.

**Comment by atoshmukhamedov** [comment]
+1

**Comment by tuanphungcz** [comment]
👍👍👍
