### ISSUE TITLE
Accept Word does not work across lines

### ISSUE THREAD

**Issue by Mayanks0307** [microsoft/vscode#194883]
Issue
Currently, my top pain point with using Accept Word in inline suggestions is that it does not go across lines. Once I get to the end of the line I can not trigger it anymore to start accepting words from the second line.

The same happens in the accept line suggestion disappears due to line change.

Version: 1.82

This issue(https://github.com/microsoft/vscode/issues/172162) was fixed in 1.78.2

In this pull request https://github.com/microsoft/vscode/pull/179988

Which has reappeared again.

**Comment by mroch** [comment]
it still works for me in 1.83.0, at least in typescript with copilot. what happens when it reaches the end of the line? I wonder if something else like autoformatting is causing it to disappear.

**Comment by Mayanks0307** [comment]
https://github.com/microsoft/vscode/assets/98150135/25183bfe-7aa4-48db-b2c7-7a184950fae8

v-1.78.2 same working fine.



https://github.com/microsoft/vscode/assets/98150135/2d9167c1-05b6-4780-ae55-d0f20abc3e0e

version 1.83.0 same not working

**Comment by hediet** [comment]
I cannot verify as well. Can you disable all other extensions?

**Comment by Mayanks0307** [comment]
I tried after uninstalling every extension still facing the same issue should I share the video?

**Comment by hediet** [comment]
Can you create a new empty profile and try to reproduce? Maybe it is some setting

**Comment by Mayanks0307** [comment]
https://github.com/microsoft/vscode/assets/98150135/2444b0cc-8ef3-4fb6-9e1f-e6530556e992

I think accept word breaks when quick suggestion settings are made to inline instead of on also one more issue found after creating a new profile accept line works fine when the keyboard shortcut is pressed but breaks when clicked on the toolbar option as shown in the video.

**Comment by hediet** [comment]
Cannot reproduce

![Image](https://github.com/microsoft/vscode/assets/2931520/2f7970c3-fcae-443b-b3e7-2f19feb05ab7)
