### ISSUE TITLE
Provide a way to exempt a terminal from applying any env collections

### ISSUE THREAD

**Issue by karrtikr** [microsoft/vscode#194819]
We can provide:
- a terminal filter function to decide which terminals environment collection applies to
- an option to skip env collection in terminal startup options

Primary use case:

With https://github.com/microsoft/vscode/issues/145234 coming up, we would like to shift some commands which we run as a process to running in terminal instead, but we would like to run those in a deactivated terminal (similar to process spawn), instead of the one where envs are already set.

**Comment by karrtikr** [comment]
It was brought to my attention that environment collection isn't applied on hidden terminals:

https://github.com/microsoft/vscode/blob/443f8cc0861e6a4eadd04a65d722af2c45ac3eca/src/vs/workbench/contrib/terminal/browser/terminalProcessManager.ts#L438-L441

Which means they're deactivated already, so we can directly use them to run commands, i.e this feature should no longer be needed.

**Comment by Tyriar** [comment]
@karrtikr we could change it as it makes sense to me that `hideFromUser` would behave the same.

**Comment by karrtikr** [comment]
Umm I kind of like it because hidden terminals are generally extension specific (for eg. https://github.com/microsoft/vscode-remote-release/issues/1760), so it does not for environment collection for other extensions.

**Comment by karrtikr** [comment]
Reopening this issue as it would seem that we're also deciding to apply environment collection to hidden terminals: https://github.com/microsoft/vscode/issues/197187#issuecomment-1794963208.

**Comment by Tyriar** [comment]
Closing as hidden terminals will act like regular terminals with https://github.com/microsoft/vscode/issues/199611#issuecomment-2004698031.

**Comment by karrtikr** [comment]
If hidden terminal act like regular terminals and start applying environment collection, that is precisely what we want to avoid here. We want to launch a hidden terminal, which has shell integration capacities (fetch command results), but does **not** apply environment collection. How do we do that?

**Comment by karrtikr** [comment]
Basically, I think the right move should probably be to still have hidden terminals be private (not apply environments from other extensions), while still giving it shell integration capabilities.

**Comment by Tyriar** [comment]
They can be shown though, a common use case is to create a terminal in the background and show it after some time. It would be a weird inconsistency for that to not act like others.
