### ISSUE TITLE
Having parameters for tasks would be very useful

### ISSUE THREAD

**Issue by tdegrunt** [Microsoft/vscode#19498]
- VSCode Version: 1.8.1
- OS Version: macOS 10.12.3

It would be very useful to have a way of prompting for additional arguments to tasks.
Something similar to the [snippet style](https://code.visualstudio.com/docs/customization/userdefinedsnippets#_creating-your-own-snippets) could be used to prompt for additional arguments.
This way tasks, or commands like the following could be done straight from vscode:

- `bin/rails g migration AddHostNameToUrl host_name:string`
  could be defined as: `bin/rails g migration ${1:MigrationName} ${2:field:type}` 
- `bin/rails db:rollback STEP=2`
  could be defined as: `bin/rails db:rollback STEP=${1}` 

These are examples for rails/rake, but the same applies to yeoman generators

- `yo angular:controller MyNewController`
  could be defined as: `yo angular:controller ${1:ControllerName}`

**Comment by mousetraps** [comment]
@tdegrunt thanks for reaching out! Cool idea - looks like this feature request is already being tracked at https://github.com/Microsoft/vscode/issues/4758, but happy to reopen if you think otherwise. Happy coding!
