### ISSUE TITLE
Accept Notification Primary Action incorrectly accepts first notification instead of selected notification

### ISSUE THREAD

**Issue by jdanbrown** [microsoft/vscode#194927]
Does this issue occur when all extensions are disabled?:
- I needed an extension to repro the bug (Notification Tester), so I kept them enabled

VS Code Version / OS Version: 
```
Version: 1.84.0-insider (Universal)
Commit: 7d4027b62bb1e620e5454580450fa646682bc102
Date: 2023-10-05T05:38:01.671Z
Electron: 25.8.4
ElectronBuildId: 24154031
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Darwin arm64 22.6.0
```

Steps to Reproduce:
1. Trigger multiple notifications
    - I used `Notification Tester: Show All Messages` from extension https://github.com/svipas/vscode-notification-tester
2. Focus the middle notification

    <img width="383" alt="image" src="https://github.com/microsoft/vscode/assets/627486/5adc6fa8-2270-4106-b6f2-a17ab0692b3d">

3. Run `Notifications: Accept Notification Primary Action`
4. Observe that the _first_ notification is accepted instead of the selected one, which is surprising (and potentially dangerous)

    <img width="386" alt="image" src="https://github.com/microsoft/vscode/assets/627486/b2d3cf6e-d381-4203-b55b-fe931c958822">

**Comment by bpasero** [comment]
I am not aware of this action, seems like it was added from https://github.com/microsoft/vscode/commit/1606487f6ebfe224cdbb1d6803241c7326115a43

**Comment by jdanbrown** [comment]
In case helpful, my motivation is to make Notifications easy to use from the keyboard:
- Can already make keybindings to show/hide the notifications list (`notifications.showList`/`notifications.hideList`)
- Can already make keybindings to select a notification (`list.focusUp`/`list.focusDown`)
- But can't currenty make a keybinding to click the primary button on the selected notification
  - Can currently use `tab` to select a button, but can't use e.g. `enter` to just accept the primary one (like most UI toolkits do)

**Comment by DonJayamanne** [comment]
Still repros for me. 
The primary action of the first prompt is always selected
Could be because, when you move the mouse away the focus seems to be lost

**Comment by meganrogge** [comment]
@DonJayamanne you have the accessible view open when you're trying this?

**Comment by DonJayamanne** [comment]
> you have the accessible view open when you're trying this?

Nope.

**Comment by meganrogge** [comment]
disregarding my comment, it works for me. gif please?

https://github.com/microsoft/vscode/assets/29464607/e6372aef-9d60-4024-bd80-c13b19a0604a

**Comment by DonJayamanne** [comment]
![Recording 2023-10-26 at 05 22 29](https://github.com/microsoft/vscode/assets/1948812/321753f9-a77a-4a53-8f00-7969f9ecfc88)

**Comment by meganrogge** [comment]
Yep, you need to use the keyboard shortcut, `cmd+shift+a`
