### ISSUE TITLE
Smoke Test: replace in search strange behavior

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#19499]
- VSCode Version: 1.9.x
- OS Version: Windows

Steps to Reproduce:

1. Follow the smoke and search for body
2. Replace with body2
3. Select a match and press replace

Observe: the match is not removed since body still matches. I would not expect this.

**Comment by sandy081** [comment]
@dbaeumer Thanks for filing this but it is a known issue #9084. This is due to search being very dynamic and aggressive. This is not a very common issue (no user has not yet reported till now). 
I would update the smoke test to a much common scenario.

Duplicates #9084

**Comment by sandy081** [comment]
I see that the smoke test does not mention this case.
