### ISSUE TITLE
confusing signature in CodeLensProvider.onDidChangeCodeLenses

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode#19495]
Testing #10648:

The new API on the CodeLensProvider uses `Event<this>`.
```typescript
	export interface CodeLensProvider {
		onDidChangeCodeLenses?: Event<this>;
        }
```
Using `Event<CodeLensProvider>` would be more clear as we likely are not going to have a subclass of CodeLensProvider.
Is the event argument really necessary? The event is part of a specific provider instance already. 
It seems that I can fire the event with any argument value (playing around with sample code). Not sure if that's a bug. 

```
import * as vscode from 'vscode';

let onDidChangeCodeLensesEmmiter = new vscode.EventEmitter<vscode.CodeLensProvider>();

let counter = 0;

function provideCodeLenses(document: vscode.TextDocument): vscode.ProviderResult<vscode.CodeLens[]> {

    var lenses : vscode.CodeLens[] = [];
    var re = /^[ \t]*public/gm;
    var text = document.getText();
    var match;
    while ((match = re.exec(text)) != null) {
        let offset = match.index;
        var pos = document.positionAt(offset);
        var lens = new vscode.CodeLens(new vscode.Range(pos, pos));
        lens.command = {
            title: 'My code lens ' + counter,
            command: 'extension.sayHello'
        }
        lenses.push(lens);
    }
    return lenses;
}


// this method is called when your extension is activated
// your extension is activated the very first time the command is executed
export function activate(context: vscode.ExtensionContext) {

    let provider : vscode.CodeLensProvider = {
        provideCodeLenses,
        onDidChangeCodeLenses: onDidChangeCodeLensesEmmiter.event
    };

    vscode.languages.registerCodeLensProvider('java', provider);

    console.log('Congratulations, your extension "codelenstest" is now active!');

    let disposable = vscode.commands.registerCommand('extension.sayHello', () => {
            counter++;
            onDidChangeCodeLensesEmmiter.fire(null);
    });

    context.subscriptions.push(disposable);
}

**Comment by jrieken** [comment]
> ...new API on the CodeLensProvider uses Event. Using Event would be more clear as we likely are not

@aeschli Uses event, using event ?! 😵

**Comment by aeschli** [comment]
Sorry, brackets swallowed by markdown. Now they are back.

**Comment by jrieken** [comment]
Yeah, the generic type is meant to describe the actual event object, not the sender. Since in this case I didn't really have an event I went with `Event<this>` which is like `Event<CodeLensProvider>` and more... Unsure if should all for just an `Event`?

**Comment by jrieken** [comment]
`Event<void>` is the preferred solution after discussing with @alexandrudima. @aeschli likes?

**Comment by aeschli** [comment]
@jrieken Yes, looks good!

**Comment by gregvanl** [comment]
@jrieken This also fixes failing vscode-docs gulp task api-doc-json which didn't like `onDidChangeCodeLenses?: Event<this>;`

**Comment by jrieken** [comment]
@gregvanl Unrelated to that we did a change that turns it to `Event<void>` and my testing shows that `gulp generate-api-doc` not works
