### ISSUE TITLE
Unresponsive behaviour of Visual Studio Code

### ISSUE THREAD

**Issue by kumargaurav0688** [microsoft/vscode#194994]
Type: <b>Bug</b>

The Visual Studio Code opens a dialog box stating " The window is not responding". Everytime I open it it throws an error. Please resolve this issye as soon as possibe

VS Code version: Code 1.83.0 (e7e037083ff4455cf320e344325dacb480062c3c, 2023-10-03T16:12:16.321Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-6006U CPU @ 2.00GHz (4 x 1992)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|7.89GB (3.30GB free)|
|Process Argv|--crash-reporter-id 7385aca3-9297-4612-a54a-be4e80094709|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
rainbow-csv|mec|3.7.1
python|ms-|2023.18.0
vscode-pylance|ms-|2023.10.10
jupyter|ms-|2023.9.1102792234
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.17
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-slideshow|ms-|0.1.5

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscorecescf:30445987
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
py29gd2263cf:30792227
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
2e4cg342:30602488
f6dab269:30613381
showlangstatbar:30737416
03d35959:30757346
pythonfmttext:30731395
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
pythonnosmt12:30797651
pythonidxptcf:30805731
pythonnoceb:30805159
copilotsettingt:30839829
dsvsc013:30795093
dsvsc014:30804076
diffeditorv2:30821572
dsvsc015:30845448

```

</details>
![Screenshot (121)](https://github.com/microsoft/vscode/assets/34794356/36bca3a8-4264-47c0-89b1-8129996fdb82)

**Comment by abhijit-chikane** [comment]
have you tried this?
https://github.com/microsoft/vscode/issues/178962#issuecomment-1497300531

**Comment by deepak1556** [comment]
Does the unresponsiveness happen for opening any file or is there a particular file that triggers the error ?

**Comment by kumargaurav0688** [comment]
Whenever I am opening VS code then it opens a dialog box stating " The window is not responding". It throws an error. Please resolve this issue ASAP because it is impacting my business criticality. Thanking you in advance

**Comment by deepak1556** [comment]
Can you confirm if the issue happens when launching with a new user data directory `code.cmd --user-data-dir C:\Users\<username>\AppData\Local\Temp\vscode-test` replace `<username>` with appropriate value.

**Comment by deepak1556** [comment]
Do you have Mcafee installed ?

**Comment by kumargaurav0688** [comment]
yes

**Comment by kumargaurav0688** [comment]
I am not able to add Code.exe file in the Add Section of Real Time Scanning

**Comment by kumargaurav0688** [comment]
After adding Code.exe in the McAfee still the problem persists
