### ISSUE TITLE
Expandable objects in locals cannot be modified

### ISSUE THREAD

**Issue by adelphes** [Microsoft/vscode#19494]
- VSCode Version: 1.8.1
- OS Version: Ubuntu 16, Linux x64
- Node: 6.5.0

The locals window allows direct modification (setting the value) of variables by double-clicking the value or using the "Set Value" context menu option.

But you can't do this with objects or arrays. Because they're expandable, there are no options available for modifying them directly in locals - instead you have to manually evaluate an assignment expression to set the appropriate value.

On a related note, setting locals to object literals fails - they can only be set to primitives, strings or array literals. What's more annoying is that if you set a local to an array literal, you can't set it back! (because it becomes expandable).

Can you allow double-click and the context menu "Set Value" to expandable variables?

**Comment by mousetraps** [comment]
Hey @adelphes, thanks for reporting! Indeed, this feature would be helpful, and would go along well with https://github.com/Microsoft/vscode/issues/13969. As to your second issue, I've filed #19553 to track that. 

cc @weinand, @roblourens, @isidorn

**Comment by weinand** [comment]
This sounds like a regression to me. IIRC this was possible previously.

**Comment by isidorn** [comment]
To verify: have a debug session and make sure a primitive variable can be set to an array, and that an array can be set back to a primitive variable
