### ISSUE TITLE
Interactive window (Python) code entry box truncated

### ISSUE THREAD

**Issue by iibadshah** [microsoft/vscode#194942]
Type: <b>Bug</b>

Selecting (python) code in editor and executing in interactive window, or typing into code entry box of interactive window causes the code entry box to become truncated. Typing into code entry box does not expand to accommodate new lines.

Switching to another interactive window tab and then returning resolves the issue.

Python 3.9.13

VS Code version: Code 1.83.0 (e7e037083ff4455cf320e344325dacb480062c3c, 2023-10-03T16:12:16.321Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10610U CPU @ 1.80GHz (8 x 2304)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|63.78GB (42.95GB free)|
|Process Argv|--crash-reporter-id 23808434-da51-475d-832b-df3daa77569b|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (19)</summary>

Extension|Author (truncated)|Version
---|---|---
code-runner|for|0.12.0
vscode-cython|ktn|0.3.10
black-formatter|ms-|2023.4.1
isort|ms-|2023.10.1
pylint|ms-|2023.6.0
python|ms-|2023.16.0
vscode-pylance|ms-|2023.10.10
jupyter|ms-|2023.9.1102792234
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.17
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-slideshow|ms-|0.1.5
remote-wsl|ms-|0.81.7
cmake-tools|ms-|1.15.31
cpptools|ms-|1.17.5
cpptools-extension-pack|ms-|1.3.0
material-icon-theme|PKi|4.30.1
intellicode-api-usage-examples|Vis|0.2.8
vscodeintellicode|Vis|1.2.30

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vstes627:30244334
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263:30335439
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
vscaac:30438847
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
2e4cg342:30602488
f6dab269:30613381
showlangstatbar:30737416
0bi6i642:30841073
03d35959:30757346
pythonfmttext:30731395
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
pythonnosmt12:30797651
pythonidxptcf:30805731
pythonnoceb:30805159
copilotsettingc:30839828
dsvsc013:30795093
dsvsc014:30804076
diffeditorv2:30821572
dsvsc015:30845448

```

</details>

**Comment by iibadshah** [comment]
![image](https://github.com/microsoft/vscode/assets/73265507/6afa662b-bc21-4c56-80f5-3949c3d2d7c1)

**Comment by amunger** [comment]
I'm not seeing this issue, can you try to see if it occurs in a temporary profile with only the python and juypter extensions installed - `Profile: Create a Temporary Profile`

**Comment by iibadshah** [comment]
I cannot reproduce the bug. As I am unable to, and I have not witnessed it since, should I close this issue?

**Comment by amunger** [comment]
ok, thanks for the update. I'll just close for now.
