### ISSUE TITLE
Migrated autoSaveDelay formatting issues

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode#1949]
See the placement of the `,` below

```json
// Place your settings in this file to overwrite the default settings
{
	"editor.renderWhitespace": true,
	"editor.wrappingColumn": 0

    // Migrated from previous File | Auto Save setting:
    , "files.autoSaveDelay": 1
}
```

**Comment by bpasero** [comment]
@egamma I do this to not get into the business of trying to find the right place of putting the comma. someone could have typed a complicated comment after a line, so I do not want to scan for the real end of the JSON part of the line.

**Comment by egamma** [comment]
I see the issue. 

How about generating the setting as follows. It makes it somewhat easier to fix the formatting (but I have no strong preference):

```json
// Place your settings in this file to overwrite the default settings
{
	"editor.renderWhitespace": true,
	"editor.wrappingColumn": 0

    , // Migrated from previous File | Auto Save setting:
    "files.autoSaveDelay": 1
}
```

**Comment by bpasero** [comment]
:+1:
