### ISSUE TITLE
[WelcomeUX] Revisit "Interface overview"

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#19491]
- The arrows are tiny, barely noticeable
- `view errors and warnings` points to the wrong spot. How do we maintain this, going forward?
- Where is `Find and run all commands` pointing to? There's nothing behind it to click.
- The text is hard to read because it overlays on top of existing text
- The text's content brings nothing new to the table
- I only noticed that keybindings are there after seeing my own screenshot in this issue

![image](https://cloud.githubusercontent.com/assets/22350/22368861/0721da88-e489-11e6-8b86-d60377aa17f9.png)

It just looks way out of style with everything else.

I suggest to open https://code.visualstudio.com/docs/editor/codebasics instead.

**Comment by joaomoreno** [comment]
Another thought: I believe the interactive playground is much more useful in bringing users up to speed with what we can do. Could we place that in the first position instead?

**Comment by chrmarti** [comment]
The reason we put the overview first and the playground last is our assumption that new users prefer to start with the most essential information and customization to make themselves feel "at home" and only after some exploring proceed to more detailed documentation like the playground.

Quick replies on the other points:
- Arrows need some more treatment, partly theme dependent (Dark+ looks better).
- `View errors and warnings`: Layout is currently static, tracked with #18861.
- `Find and run all commands` points at an image of the command palette IF the window is wide enough, might need some tweaking.
- On "hard to read": Agree, needs theme-specific tweaking.
- On "nothing new": To new users, everything is new.
- On "keybindings": Agree, more theme-specific tweaking.

**Comment by rakkarage** [comment]
also if you move side bar right then the arrows still point to left side of screen

**Comment by edburns** [comment]
```
We closed this issue because we don't plan to address it in the foreseeable future.
```

Can we at least get a little arrow pointing to the "remote" indicator in the lower left corner?

![message](https://user-images.githubusercontent.com/75821/73289593-fce09f80-41ca-11ea-91bf-45cfb6a72bd6.jpg)
