### ISSUE TITLE
"workbench.colorCustomizations" doesn't work

### ISSUE THREAD

**Issue by RokasKns** [microsoft/vscode#194996]
Type: <b>Bug</b>

"statusBar.background" and  "statusBarItem.remoteBackground" makes no difference to that annoying purple status bar, neither as a global setting, nor for a particular theme. I'm able to change "statusBarItem.remoteBackground" on some themes, for example the latest Modern theme. Apart from that it just doesn't work.

VS Code version: Code 1.83.0 (e7e037083ff4455cf320e344325dacb480062c3c, 2023-10-03T16:12:16.321Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6500U CPU @ 2.50GHz (4 x 2592)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|7.87GB (2.60GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
TabOut|alb|0.2.2
c-cpp-compile-run|dan|1.0.50
python|ms-|2023.18.0
vscode-pylance|ms-|2023.10.10
jupyter|ms-|2023.9.1102792234
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.17
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-slideshow|ms-|0.1.5
cpptools|ms-|1.17.5
solarized-high-contrast-light|tin|1.1.2

(5 theme extensions excluded)

</details>

**Comment by hirdeshKalmodiya20** [comment]
i a,m

**Comment by RokasKns** [comment]
IMPORTANT TO NOTE: This only seems to be the case while no folder is open! Once a folder is opened, things work just fine.

**Comment by aeschli** [comment]
Is this a window without an input folder or workspace? Try:
```
	"workbench.colorCustomizations": {
		"statusBar.noFolderBackground": "#ff0000"
	}
```
