### ISSUE TITLE
Cannot reveal in File Explorer

### ISSUE THREAD

**Issue by mengfong96** [microsoft/vscode#194960]
Type: <b>Bug</b>

1. Open any folder in VScode with WSL Ubuntu.
2. On the explorer, right click on any file, choose "Reveal in File Explorer".
3. File explorer is not starting.

VS Code version: Code 1.83.0 (e7e037083ff4455cf320e344325dacb480062c3c, 2023-10-03T16:12:16.321Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Remote OS version: Linux x64 5.15.90.1-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz (8 x 1690)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.75GB (4.32GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 5.15.90.1-microsoft-standard-WSL2|
|CPUs|11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz (2 x 1689)|
|Memory (System)|5.79GB (4.14GB free)|
|VM|0%|
</details><details><summary>Extensions (17)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|3.0.2
Bookmarks|ale|13.4.1
macos-modern-theme|dav|2.3.19
dotenv|mik|1.0.1
remote-wsl|ms-|0.81.7
laravel5-snippets|one|1.17.0
pdf|tom|1.2.2
vscode-icons|vsc|12.5.0
better-comments|aar|3.0.2
Bookmarks|ale|13.4.1
vscode-intelephense-client|bme|1.9.5
macos-modern-theme|dav|2.3.19
gitlens|eam|14.3.0
ftp-sync|luk|0.3.9
dotenv|mik|1.0.1
laravel5-snippets|one|1.17.0
vscode-icons|vsc|12.5.0

(4 theme extensions excluded)

</details>

**Comment by thatguy7** [comment]
I have this problem since 1.82.

My workaround is to open the directory in the integrated terminal and run "`explorer.exe .`".

**Comment by lramos15** [comment]
Duplicate https://github.com/microsoft/vscode-remote-release/issues/9037
