### ISSUE TITLE
Enable Panel (Terminal, Jupyter variables, etc.) position to be contained within a column

### ISSUE THREAD

**Issue by iibadshah** [microsoft/vscode#194947]
Type: <b>Feature Request</b>

Panel position is currently isolated to Bottom, Left, or Right of the whole application window.

**Motivation:**
Increase vertical height of Editor.

**Request:**
Add the ability to enable Bottom position to be contained to given column. For example with a 2 column Editor layout:
- Panel position Bottom spans the whole window width (as it does now).
- Panel position Bottom Column contains the Panel to a column; drag and drop to move between columns (as with Editor tabs).

VS Code version: Code 1.83.0 (e7e037083ff4455cf320e344325dacb480062c3c, 2023-10-03T16:12:16.321Z)
OS version: Windows_NT x64 10.0.22631
Modes:

**Comment by roblourens** [comment]
Hm, I think this probably doesn't fit into the way that view management works in vscode, but maybe there is an issue tracking this kind of thing

**Comment by sbatten** [comment]
I think the full breadth of this is out of scope. But we do support panel alignment, which is similar. It doesn't give you more vertical editor real estate however.
