### ISSUE TITLE
"window.reopenFolders": "all" doesn't work

### ISSUE THREAD

**Issue by simon387** [Microsoft/vscode#19497]
- VSCode Version: Code 1.8.1 (ee428b0eead68bf0fb99ab5fdc4439be227b6281, 2016-12-19T14:41:20.664Z)
- OS Version: Linux x64 4.9.5-200.fc25.x86_64
- Extensions:

|Extension|Author|Version|
|---|---|---|

---

Steps to Reproduce:

1.set "window.reopenFolders": "all",
2.open a file
3.restart  visual studio code

**Comment by mousetraps** [comment]
@simon387 Thanks for reporting! Quick question to help narrow it down - how exactly are you "restarting" Visual Studio Code? For instance, on Windows, when I right click in the task bar, and select "Close All Windows", not all my windows will start up in the next session (@bpasero do you know if there's any way around this?), but if I select `File > Exit` from the menu pane, they will restore.

**Comment by simon387** [comment]
Sorry for my late reply, 

anyway it looks resolved with the 1.9
