### ISSUE TITLE
The "ports" button is missing

### ISSUE THREAD

**Issue by AbrahamupSky** [microsoft/vscode#194973]
Type: <b>Bug</b>

In the lower panel I don't see the "ports" option, and I don't know how to activate it again, and it is not disabled.

VS Code version: Code 1.83.0 (e7e037083ff4455cf320e344325dacb480062c3c, 2023-10-03T16:12:16.321Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 5600X 6-Core Processor              (12 x 3700)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.93GB (16.42GB free)|
|Process Argv|--crash-reporter-id df9fb1bb-1693-4bb3-89c3-980ba767e2b0|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (114)</summary>

Extension|Author (truncated)|Version
---|---|---
python-image-preview|076|0.1.2
better-comments|aar|3.0.2
html-snippets|abu|0.2.1
open-folder-in-explorer|adr|1.2.0
vscode-javascript-snippet-pack|aka|0.1.6
folder-operations|Art|0.5.0
folder-indexing|ast|0.2.0
a-file-icon-vscode|ato|1.2.0
code-gnu-global|aus|0.2.2
jsoncrack-vscode|Ayk|2.0.2
vscode-icontheme-nomo-dark|be5|1.3.6
beardedicons|Bea|1.13.2
vscode-tailwindcss|bra|0.10.0
path-intellisense|chr|2.8.4
codeium|Cod|1.2.100
indent4to2|Com|0.1.2
doxdocgen|csc|1.4.0
flask-snippets|cst|0.1.3
vscode-simpler-icons|dav|1.6.5
vscode-eslint|dba|2.4.2
githistory|don|0.6.20
es7-react-js-snippets|dsz|4.4.3
gitlens|eam|14.3.0
vscode-html-css|ecm|1.13.1
sweet-vscode-icons|Eli|0.0.1
vscode-great-icons|emm|2.1.102
moxer-icons|Equ|5.11.0
vsc-material-theme-icons|equ|3.1.0
prettier-vscode|esb|10.1.0
pip-packages|etm|0.4.3
file-icons|fil|1.1.0
auto-rename-tag|for|0.1.10
code-runner|for|0.12.0
vscode-mysql|for|0.4.1
html-snippets|gey|0.2.3
remotehub|Git|0.62.0
vscode-pull-request-github|Git|0.74.0
gc-excelviewer|Gra|4.2.58
vscode-drawio|hed|1.6.6
rest-client|hum|0.25.1
html-tag-wrapper|hwe|0.2.3
output-colorizer|IBM|0.1.2
discord-vscode|icr|5.8.0
intalicons|int|1.5.0
vscode-picture|Jak|1.0.0
better-cpp-syntax|jef|1.17.2
gruvbox-material-icon-theme|Jon|1.1.5
vscode-icon-theme|jtl|1.6.6
vscode-colorize|kam|0.11.1
copy--include|Kar|0.0.6
vscode-gutter-preview|kis|0.30.0
MagicPython|mag|1.1.0
rainbow-csv|mec|3.7.1
template-string-converter|meg|0.6.1
fluent-icons|mig|0.0.18
symbols|mig|0.0.14
python-essentials|mik|1.0.1
mongodb-vscode|mon|1.2.1
theme-monokai-pro-vscode|mon|1.2.1
vscode-docker|ms-|1.26.1
data-workspace-vscode|ms-|0.5.0
mssql|ms-|1.21.0
sql-database-projects-vscode|ms-|1.3.1
isort|ms-|2023.10.1
python|ms-|2023.18.0
vscode-pylance|ms-|2023.10.10
jupyter|ms-|2023.9.1102792234
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.17
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-slideshow|ms-|0.1.5
remote-containers|ms-|0.315.1
remote-ssh|ms-|0.106.4
vscode-remote-extensionpack|ms-|0.24.0
cmake-tools|ms-|1.15.31
cpptools|ms-|1.17.5
cpptools-extension-pack|ms-|1.3.0
live-server|ms-|0.4.11
remote-explorer|ms-|0.4.1
remote-repositories|ms-|0.40.0
remote-server|ms-|1.4.3
vscode-typescript-next|ms-|5.3.20231005
vsliveshare|ms-|1.0.5883
autodocstring|njp|0.6.1
indent-rainbow|ode|8.3.1
docthis|oou|0.8.2
vscode-versionlens|pfl|1.8.0
material-icon-theme|PKi|4.30.1
material-product-icons|PKi|1.6.0
vscode-css-peek|pra|4.4.1
vscode-jsp|pth|0.0.3
sqlite-viewer|qwt|0.3.13
vscode-thunder-client|ran|2.12.7
python-template-snippets|Ric|1.3.0
LiveServer|rit|5.7.9
synthwave-vscode|Rob|0.1.15
sqlite-snippet|roh|2.0.1
html5-boilerplate|sid|1.1.1
pip-manager|sli|1.1.3
code-spell-checker|str|3.0.1
icons|tal|3.7.0
ejs-snippets|Tao|0.1.0
open-in-browser|tec|2.0.0
vscode-djaneiro|the|1.4.2
python|tht|0.2.3
pdf|tom|1.2.2
vscode-pets|ton|1.25.0
errorlens|use|3.14.0
vscode-icons|vsc|12.5.0
vscode-wakatime|Wak|24.2.3
HTML5-extension-pack|wal|1.0.0
vscode-todo-highlight|way|1.0.5
JavaScriptSnippets|xab|1.8.0
material-theme|zhu|3.16.0

(9 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
vscaat:30438848
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
2e4cg342:30602488
f6dab269:30613381
showlangstatbar:30737416
0bi6i642:30841073
03d35959:30757346
pythonfmttext:30731395
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
pythonnosmt12:30797651
pythonidxpt:30805730
pythonnoceb:30805159
copilotsettingt:30839829
asynctok:30821568
dsvsc013:30795093
dsvsc014:30804076
diffeditorv2:30821572
dsvsc015:30845448

```

</details>

**Comment by alexr00** [comment]
Are you connected to a remote using one of the remote extensions (ex. Remote SSH or GitHub Codespaces)?

Did you disable the built-in extension "Local Tunnel Port Forwarding"?

**Comment by AbrahamupSky** [comment]
![Code_TWCVj5KGC1](https://github.com/microsoft/vscode/assets/55633852/2d828b30-9eb9-4faa-a935-d444554646b6)

Just found this, it was disabled and I already hit enable, thank you very very much!!!
