### ISSUE TITLE
Regression in `workbench.action.tasks.reRunTask` behavior prior to running a task

### ISSUE THREAD

**Issue by jose-elias-alvarez** [microsoft/vscode#194935]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.83.0
- OS Version: macOS Sonoma 14.0

Steps to Reproduce:

1. Open a new editor window
2. Run `workbench.action.tasks.reRunTask` *before* actually running a task

In the current VS Code release, this sequence of steps does nothing. In the previous VS Code release (18.2.3), the same sequence prompts the user to choose a task, as if `workbench.action.tasks.runTask` was run instead, which (at least in my opinion) was more intuitive than a no-op.

I found #193043, which seems to imply that this change was intentional. But the linked issue, #188805, describes a different bug, in which the command did not automatically select the last task *after* running a task once.

It seems to me that the ideal behavior would be the following:

1. If the user has already run a task, rerun that task
2. If the user hasn't run a task, prompt them to choose a task

I'm happy to look into this more and put in a PR if there's agreement.

**Comment by meganrogge** [comment]
It's a little complicated because if there's a task currently in progress, we don't want to prompt but also don't want to rerun it. 

So I suggest this addition to what you describe above. 

- If there's a task in progress, no-op

Would accept a PR for this. Thanks

**Comment by jose-elias-alvarez** [comment]
Thanks for the quick turnaround on this!
