### ISSUE TITLE
Breakpoints not binding on typescript project on one machine

### ISSUE THREAD

**Issue by disambiguationuk** [microsoft/vscode#194988]
Hello, I'm having a bit of an issue with a project where none of my breakpoints want to bind to my react typescript application. I've got the exact same setup on a different machine and it works fine there. I've rebooted, reinstalled vs code etc. and no dice. 

Running:
VS Code: Version 1.83.0
OS: Linux x64 6.2.0-34-generic (Ubuntu)
Chromium: 114.0.5735.289

My launch.json looks like: 

```
{
  "version": "0.2.0",
  "configurations": [
    {
      "type": "chrome",
      "request": "launch",
      "name": "Launch Chrome against localhost",
      "url": "http://localhost:8000/login",
      "trace": true,
      "webRoot": "${workspaceFolder}/browser"
    }
  ]
}
```

And I've got a debug trace file: 
[vscode-debugadapter-8ffee509.json.gz](https://github.com/microsoft/vscode/files/12829335/vscode-debugadapter-8ffee509.json.gz)

**Comment by kbeeveer46** [comment]
I have this same issue in a React +TypeScript project. Tried restarting my computer and VS Code but nothing works. I can't get any of my breakpoints to work. I think the only difference from the other day when it worked fine was installing 1.83.0. My next step was to uninstall 1.83 and install the previous version.

**Comment by kbeeveer46** [comment]
Uninstalling 1.83 and installing 1.82.3 fixed my breakpoints issue https://code.visualstudio.com/updates/v1_82

**Comment by disambiguationuk** [comment]
Ah it works! Well that was a waste of productivity this week!

**Comment by connor4312** [comment]
It looks like this is a regression with the webpack `eval-*` devtool settings. I will put in a fix for the next [nightly build](https://github.com/microsoft/vscode-js-debug#nightly-extension) of the debugger.

Btw, I recommend setting your devtool to just `source-map` if reasonable, or at least avoiding `eval-*` source maps. Due to the way they're structured, they're a lot slower to load for the debugger than other maps.

**Comment by connor4312** [comment]
I'll also put this forward as a candidate for our 1.83.1 recovery release

**Comment by disambiguationuk** [comment]
Just noting this still appears to be broken in 1.83.1 for me.

**Comment by connor4312** [comment]
Please collect a new trace log for me to investigate. Thanks!

**Comment by kbeeveer46** [comment]
I was one of the people having breakpoint issues in 1.83. I just tested 1.83.1 and my breakpoints work now.
