### ISSUE TITLE
`editor.tokenColorCustomizations` should re-set theme tokens. 

### ISSUE THREAD

**Issue by T-256** [microsoft/vscode#194951]
I'm using old [Chromodynamics](https://marketplace.visualstudio.com/items?itemName=magicstack.Chromodynamics) theme, recently I decided to migrate to new `Dark Modern` theme.
I got used to old syntax colors, so I tried to bring back it by writing `"tokenColors"` from exported json into `editor.tokenColorCustomizations` settings, But it seems all other token colorization of `Dark Modern` theme is still there.

Currently I should create new theme extension with these config:
```json
{
	"$schema": "vscode://schemas/color-theme",
	"type": "dark",
	"colors": {<from Dark-Modern>},
	"tokenColors": [<from Chromodynamics>]
}
```
The downside of re-creating an extension is I should manually update extension each time `Dark-Modern` theme updated. Also it's hard to share it between platforms (As it's locally built).

I suggest adding an option to apply force re-set tokens in `editor.tokenColorCustomizations` instead of merging with current tokens.

**Comment by T-256** [comment]
I want to use only token colors from [Chromodynamics](https://marketplace.visualstudio.com/items?itemName=magicstack.Chromodynamics) without extra colors.
Currently I should do it with creating extension from scratch. Is there any simpler way?

**Comment by aeschli** [comment]
Creating a theme extension seems the easiest to me. Also you can share it on the Marketplace for easy consumption.
