### ISSUE TITLE
Mock node-gyp binary scripts for CI

### ISSUE THREAD

**Issue by deepak1556** [microsoft/vscode#194921]
https://github.com/microsoft/vscode/issues/194665 was resolved by adding global installation of `node-gyp` to pipelines that needed it. However, we have pipelines that require the use of custom node-gyp (ex: [product-build-win32](https://github.com/microsoft/vscode/blob/46c45d2f67b60b398de23881080c35fc5f9795b2/build/azure-pipelines/win32/product-build-win32.yml#L110-L123)) and any package that requires global `node-gyp` will result in an error in these pipelines, refs https://dev.azure.com/monacotools/Monaco/_build/results?buildId=235316&view=logs&jobId=8e733ce0-0c7b-5d06-69ef-2aad0d062863&j=8e733ce0-0c7b-5d06-69ef-2aad0d062863&t=026ea86d-03c9-5c19-dbc7-2fdf8bf45629 since it was the job of these binary scripts to redirect to the custom node-gyp in the first place. We can emulate this behavior, by adding the relevant scripts to `PATH` environment in CI.

```sh
#!/usr/bin/env sh
if [ "x$npm_config_node_gyp" = "x" ]; then
  node "`which node`/lib/node_moduels/npm/node_modules/node-gyp/bin/node-gyp.js" "$@"
else
  "$npm_config_node_gyp" "$@"
fi
```

**Comment by roblourens** [comment]
Losing my freakin mind over here. Here's the state of my PR

- Windows
  - When `npm_config_node_gyp` is set: works
  - When not set: my cmd script is not right, and I guess `where node` returns multiple options. See the results here: https://dev.azure.com/vscode/VSCode/_build/results?buildId=105104&view=logs&j=2d439be5-f03d-54e6-66eb-93d556f69561&t=c5f12ff4-a5cf-58e4-2e8f-afd5629d3c60
- Non-Windows
  - `node` on the path actually points at a script that invokes node in some other location. I don't think we can determine that without hardcoding the path to it. https://dev.azure.com/vscode/VSCode/_build/results?buildId=105104&view=logs&j=c7493abb-a1f4-533f-2d24-71780a69f247&t=f962f2f9-8c3f-5628-18de-c473779406e6

Probably we will have to hardcode the paths on both sides? `C:\hostedtoolcache\windows\node\<version>\<arch>` and `/opt/hostedtoolcache/node/<version>/<arch>`

**Comment by roblourens** [comment]
Would be worth checking if `which npm` returns the `/opt/hostedtoolcache` path, or maybe running a node command to print `process.argv[0]` would do it

**Comment by deepak1556** [comment]
Thanks for looking into this, yeah something like that should work. I think `npm root -g` should get the path we need

**Comment by deepak1556** [comment]
Closing in favor of the yarn -> npm move.
