### ISSUE TITLE
Format on save formats dust incorrectly

### ISSUE THREAD

**Issue by xoorath** [Microsoft/vscode#19503]
- VSCode Version: 1.8.1
- OS Version: Windows 10

Hey,

Format on save (and the formatting command in general) attempts to format `.dust` files from [dustjs](http://www.dustjs.com/), and does a poor job of it. It would be better if formatting was disabled on unknown filetypes.

Or if dust is a known filetype, it needs to work with partials. Here's an example file that's formatted badly.
```
{> "layout" /}

{<head}

{/head}
{<body}
  <h1>Test</h1>
{/body}
```

This gets formatted to
```
{> "layout" /} {

<head} {/head} {<body} <h1>Test</h1>
  {/body}
```
Which is undesirable.

**Comment by mousetraps** [comment]
Hey, thanks for reporting! Closing as we don't have any built-in support for dust, so it sounds like this issue is better suited for the extension repo cc @nemesarial, who I believe owns `nemesarial.dust`.
