### ISSUE TITLE
feature request to read the wsl files

### ISSUE THREAD

**Issue by afifafifafifafifali** [microsoft/vscode#195094]
feature request to read the wsl files

**Comment by aeschli** [comment]
What are the `WSL files` ?

**Comment by afifafifafifafifali** [comment]
the file that are in the ``wsl``

**Comment by aeschli** [comment]
Is https://learn.microsoft.com/en-us/windows/wsl/filesystems helpful?

**Comment by afifafifafifafifali** [comment]
no
