### ISSUE TITLE
Debug view is not showing the hit break point

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode#19507]
Followed steps in Smoke test and while debugging break point is hit but not getting shown in the editor

![jan-27-2017 14-52-26](https://cloud.githubusercontent.com/assets/10746682/22373072/703149e8-e4a0-11e6-8c64-1960bf1ebc7c.gif)

**Comment by joaomoreno** [comment]
Does not repro in Linux

**Comment by isidorn** [comment]
Can not repro on mac

**Comment by isidorn** [comment]
Sandeep what version of node do you have? What is the type in your launch.json.
In the call stack view - there appears to be an error - what does it say?

**Comment by sandy081** [comment]
node version is 6.1.0 and the launch is the one that is created by default

```
{
    // Use IntelliSense to learn about possible Node.js debug attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "type": "node",
            "request": "launch",
            "name": "Launch Program",
            "program": "${workspaceRoot}/bin/www",
            "cwd": "${workspaceRoot}"
        },
        {
            "type": "node",
            "request": "attach",
            "name": "Attach to Process",
            "port": 5858
        }
    ]
}
```

Error in call stack is

![image](https://cloud.githubusercontent.com/assets/10746682/22373534/7c611340-e4a2-11e6-930e-21bae2fd7635.png)

**Comment by isidorn** [comment]
This is some mistique error which Ben and me have investigate in the past.
Can you please update to node 6.5 for instance and try reproducing

**Comment by weinand** [comment]
That's an issue with some versions of node. Please try node 6.5.
