### ISSUE TITLE
Font changed returning to default upon restarting the machine and VS Code.

### ISSUE THREAD

**Issue by COR0NEL** [microsoft/vscode#195036]
Type: <b>Bug</b>

Font changed returning to default upon restarting the machine and VS Code.

I'm using JetBrains Mono, and I need to install it every day because it returns to default when launched.

Thank you.

VS Code version: Code 1.83.0 (e7e037083ff4455cf320e344325dacb480062c3c, 2023-10-03T16:12:16.321Z)
OS version: Windows_NT x64 10.0.22621
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|12th Gen Intel(R) Core(TM) i7-12700H (20 x 2688)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.80GB (2.31GB free)|
|Process Argv|--crash-reporter-id 066c201a-e8a4-4139-b5f8-4ee5dab3ea5b|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (21)</summary>

Extension|Author (truncated)|Version
---|---|---
python-image-preview|076|0.1.2
preview-mp4|ana|0.0.1
exclusive-translation|che|1.3.0
vscode-office|cwe|3.1.7
gitlens|eam|14.3.0
google-translate|han|1.2.8
vscode-language-pack-pt-BR|MS-|1.83.2023100409
black-formatter|ms-|2023.4.1
python|ms-|2023.18.0
vscode-pylance|ms-|2023.10.10
jupyter|ms-|2023.9.1102792234
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.17
vscode-ai|ms-|0.36.0
vscode-ai-remote|ms-|0.34.0
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-slideshow|ms-|0.1.5
azure-account|ms-|0.11.6
sqlite-viewer|qwt|0.3.13
r|REd|2.8.1
vscode-icons|vsc|12.5.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscoreces:30445986
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
vscaat:30438848
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
3biah626:30602489
89544117:30613380
showlangstatbar:30737416
pythonfmttext:30731395
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
pythonnosmt12:30797651
pythonidxpt:30805730
pythonnoceb:30805159
dsvsc013:30795093
dsvsc014:30804076
diffeditorv1:30821571
dsvsc015:30845448

```

</details>

**Comment by theRolento** [comment]
I confirm that. The last update broke the font management.
I use Victor Mono and I too have to install it every day because it reverts back to the default one.

**Comment by rzhao271** [comment]
Merging with #173543
