### ISSUE TITLE
GUI Becomes Unresponsive

### ISSUE THREAD

**Issue by ryancoppa** [Microsoft/vscode#19509]
- VSCode Version: 1.8.1
- OS Version: Ubuntu 14.04.5 (issue occurred on older versions of 14.04, and Windows 7)

Steps to Reproduce:

1. Load a folder with C++ code (~200k lines)
2. Compile, launch, and debug code (gcc) as usual
3. After leaving the tool open for somewhere between 24-48 hours, the GUI will eventually become unresponsive, sometimes sections of the window turn black. The GUI lockup usually occurs while navigating the code. The window can be resized, resulting in more black area. Button clicks still seem to have an effect. Keyboard commands will still trigger a builds. Hovering the mouse over areas where the buttons should appear bring up the hover-help text. The only recovery is to restart the window. Work is never lost because saving still works after the screen no longer updates.

**Comment by mousetraps** [comment]
Hey @ryancoppa, sorry to hear you're running into this. A couple Qs:
1. does the issue occur only when you're in debug mode? Or any time you have the editor open for long periods of time. 
2. Does the issue occur for every project (even a small project? Or just certain projects?)

Potentially related (but resolved) issue: https://github.com/Microsoft/vscode/issues/508

**Comment by bpasero** [comment]
@ryancoppa running inside a VM?

**Comment by ryancoppa** [comment]
@mousetraps 
1. The issue occurs only when I am browsing code in the editor, I've never need the issue when actively debugging. 
2. I've seen the issue with multiple project.

Are there any logs that would be helpful? I mainly run in an Ubuntu 14.04 VM.

**Comment by bpasero** [comment]
@ryancoppa you could try running `code --disable-gpu` to see if that makes it any better.

**Comment by ryancoppa** [comment]
I'm still testing Code with this option. So far I have not seen any issues. Typically I'll see the error within 24-48 hours.

**Comment by bpasero** [comment]
Assuming it is fine now.
