### ISSUE TITLE
android emulator

### ISSUE THREAD

**Issue by satanpgn** [microsoft/vscode#195052]
Type: <b>Bug</b>

why  android emulator in my vscode doesnt support. how can i add to my vscode

VS Code version: Code 1.83.0 (e7e037083ff4455cf320e344325dacb480062c3c, 2023-10-03T16:12:16.321Z)
OS version: Windows_NT x64 10.0.22621
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz (8 x 2419)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.73GB (4.94GB free)|
|Process Argv|--crash-reporter-id 2a0c9b15-b932-4db8-9177-1ad72afdcf02|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (55)</summary>

Extension|Author (truncated)|Version
---|---|---
chrome-extension-developer-tools|aar|2.0.4
Coderslang|Agi|0.5.7
cpp-extentions-pack|bou|0.3.0
vscode-devtools-for-chrome|cod|0.0.7
c-cpp-compile-run|dan|1.0.50
dart-code|Dar|3.75.20231002
flutter|Dar|3.74.0
bracket-pair-toggler|dzh|0.0.3
vsc-material-theme|Equ|33.10.5
vsc-material-theme-icons|equ|3.1.0
prettier-vscode|esb|10.1.0
file-icons|fil|1.1.0
code-runner|for|0.12.0
vscode-flutter-files|gor|4.7.1
vs-code-runner|Har|2.0.1
material-theme|Kan|1.0.0
cpptask|kay|0.0.1
live-code-runner|lab|4.5.0
dart-import|lua|0.3.1
vscode-git-push-progress|lui|1.0.4
mongodb-vscode|mon|1.2.1
python|ms-|2023.18.0
vscode-pylance|ms-|2023.10.10
jupyter|ms-|2023.9.1102792234
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.17
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-slideshow|ms-|0.1.5
cmake-tools|ms-|1.15.31
cpptools|ms-|1.17.5
cpptools-extension-pack|ms-|1.3.0
powershell|ms-|2023.6.0
live-server-preview|neg|0.1.4
dart-syntax-highlighting-only|osc|1.0.1
material-icon-theme|PKi|4.31.0
material-product-icons|PKi|1.6.0
postman-for-vscode|Pos|0.11.0
java|red|1.23.0
you-complete-me|Ric|1.1.0
LiveServer|rit|5.7.9
tabnine-vscode|Tab|3.17.0
youcompleteme-vscode|Tom|0.4.6
cmake|twx|0.0.17
intellicode-api-usage-examples|Vis|0.2.8
vscodeintellicode|Vis|1.2.30
vscode-boot-dev-pack|vmw|0.2.1
vscode-spring-boot|vmw|1.49.0
vscode-gradle|vsc|3.12.7
vscode-java-debug|vsc|0.54.0
vscode-java-dependency|vsc|0.23.1
vscode-java-pack|vsc|0.25.14
vscode-java-test|vsc|0.40.0
vscode-maven|vsc|0.42.0
vscode-spring-boot-dashboard|vsc|0.13.1
vscode-spring-initializr|vsc|0.11.2

(7 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
py29gd2263cf:30792227
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
2e4cg342:30602488
89544117:30613380
vscrpc:30673769
a9j8j154:30646983
showlangstatbar:30737416
0bi6i642:30841073
03d35959:30757346
7ij38806:30736111
pythonfmttext:30731395
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
pythonnosmt12:30797651
pythonidxptcf:30805731
pythonnoceb:30805159
copilotsettingt:30839829
dsvsc013:30795093
dsvsc014:30804076
diffeditorv2:30821572
dsvsc015:30845448

```

</details>

**Comment by aeschli** [comment]
There are various extensions on the VS Code Marketplace...
