### ISSUE TITLE
Trim Trailing Whitespace shouldn't affect multiline strings

### ISSUE THREAD

**Issue by kanishkbh** [microsoft/vscode#195010]
This is regarding the `files.trimTrailingWhitespace` setting.
While it is possible to set it to False for specific files e.g. markdown, there often cases where we have multiline strings in a code file.

for example:
```python
st.info("""
Line1  
Line2
""")
```

When `files.trimTrailingWhitespace` is set to True, it would remove the two whitespaces after Line1, which breaks their markdown rendering as two separate lines.

Would be great to have this setting ignore multilines strings.

**Comment by coreyward** [comment]
+1 — I am running into this as well. I'm writing a test for a function that is expected to handle user input (multiline string) and format it, and I need to test the behavior when there are trailing spaces. I can save the file without formatting, but that's a bit hard to maintain.

**Comment by vuon9** [comment]
When working with extensive files and many members, this issue can be quite annoying. Adding an option to enable/disable this behavior would provide more control within the workspace scope.

**Comment by 333fred** [comment]
This is particularly bad when writing tests for parsers and other things where the string content is _extremely_ important. I generally do want to have my trailing whitespace trimmed, but if it can be known syntactically (ie, from VSCode's grammar files, involving no LSP) that the current location is inside a string, VSCode should be able to avoid trimming the trailing content.
