### ISSUE TITLE
XHR Failed in getting extensions in remote-ssh

### ISSUE THREAD

**Issue by thistlillo** [microsoft/vscode#195093]
After the last update to:
```
Version: 1.83.0 (user setup)
Commit: e7e037083ff4455cf320e344325dacb480062c3c
Date: 2023-10-03T16:12:16.321Z
Electron: 25.8.4
ElectronBuildId: 24154031
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.22621
```
I am no longer able to access extensions (CTRL+SHIFT+X) when connected to a remote linux server with ssh.

I get the error:
```
Error while fetching extensions. XHR Failed
```

It used to work till two days ago, right before the update. After update, that broke jupyter/python, I was able to reinstall python-related extensions. Now I get this error.

As a minor notice, VSC updates are becoming frightening. Every update breaks, for example, my python settings, especially with remote servers. Every time I need to uninstall and reinstall plenty of extensions. Now also this. Many users cannot afford spending days in fixing incomprehensible error messages and weird behaviours every other month.

**Comment by thistlillo** [comment]
I am sorry but, since I am using VSC for meeting some deadlines I have, I reinstalled everything for solving the problem.

**Comment by sandy081** [comment]
Ok. I am closing this as you are not able to repro it. If you see the issue again, please share the requested information. Thanks.
