### ISSUE TITLE
Process picker only shows after first stop

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#19506]
* use launch.json and app from https://github.com/Microsoft/vscode/issues/16809
* have no breakpoint or pause reasons
* start two process
* 🐛 floater doesn't show drop down, only after pausing/breaking one of the processes

![jan-27-2017 14-53-40](https://cloud.githubusercontent.com/assets/1794099/22373070/6f331062-e4a0-11e6-89a7-748355e794dc.gif)

**Comment by joaomoreno** [comment]
Not sure how important this is for January.

**Comment by isidorn** [comment]
Agree - fine for february

**Comment by isidorn** [comment]
After assessing in the standup agreed this is not for january

**Comment by isidorn** [comment]
Fixed by https://github.com/Microsoft/vscode/pull/19551
