### ISSUE TITLE
Debugging Vite/SvelteKit in 1.83.0 Not Working (works in 1.82.3)

### ISSUE THREAD

**Issue by briandonahue** [microsoft/vscode#195039]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.83.0
- OS Version: MacOS Sonoma v14.0

Version 1.82.3 was working fine and hitting breakpoints in my server-side SvelteKit code.  After updating, these breakpoints would usually work if they existed at launch of the dev server, but any breakpoints added after launch would be "unbound" and not be reached.  Adding `debugger` statements works as expected.

Steps to Reproduce:

1. Create a new SvelteKit site `npm create svelte@latest`
2.  Add a `+page.server.ts` file behind the default `+page.svelte` file and add some code like `console.log` statements
3. Set a breakpoint on one of the `console.log` lines.  
4. Run `npm run dev` in a `Javascript Debug Terminal`
5. Breakpoint will be hit
6. Add another breakpoint, it will show as "unbound" and not be hit
7. Remove original breakpoint and re-add, it will be "unbound" and not be hit anymore

**Comment by porkopek** [comment]
Same with Nextjs app. Before the update worked as expected. With this new version, it doesn't set all the breakpoints. But, oddly, ones are set another don't.
I'm visiting the pages with the breakpoints that are not set.
Uninstalling and installing august version, allows to set the breakpoints

**Comment by shanewolff** [comment]
The same issue as described above is evident for React apps as well. Since VSCode `v1.83.0`, the debugger breakpoints are left unbound after the debug session is started with launch/attach debug configurations for both Chrome and Edge.

**Comment by connor4312** [comment]
Probably duplicates https://github.com/microsoft/vscode-js-debug/pull/1833, please try the [nightly extension](https://github.com/microsoft/vscode-js-debug#nightly-extension). Fix will be released to stable in a few days.
