### ISSUE TITLE
Invalid regex in an extension configuration pattern may cause all extension configurations in the settings ui to not be displayed

### ISSUE THREAD

**Issue by Gerrnperl** [microsoft/vscode#195054]
Does this issue occur when all extensions are disabled?: No

- VS Code Version: 1.83.0
- OS Version: Kubuntu 23.04

Steps to Reproduce:

1. create a new extension
2. add the following code to `contributes`
```json
"configuration":[
  {
    "title": "test-config",
    "properties": {
      "test-extension.test": {
        "type": "string",
        "pattern": "^https?://([\\w-]+\\.)+[\\w-]+(/[\\w-./]*)?/$"
      }
    }
  }
]
```
3. run this test extension and go to settings page
4. `Extensions` could not be displayed

I found this problem when using mxp131011.element-plus-doc v2.0.8. Installing this extension should also reproduce.

![enabled](https://github.com/microsoft/vscode/assets/64595686/54c06470-3a1d-4e65-a619-1035eca0540d)
(This extension has been enabled globally. `Extensions`(`扩展`) is not visible)
![disabled](https://github.com/microsoft/vscode/assets/64595686/66cff5fd-1fe8-4038-a46a-15c8cdb34041)
(This extension has been disabled globally)

Previous versions of vscode don't seem to report errors for this kind of regular expression, which appeared in version 1.83.0.

I have created an issue to that extension (mxp131011/element-plus-doc#7). But I think this error should be caught early, or at least should not interrupt the configurations of other extensions

**Comment by TylerLeonhardt** [comment]
It looks like `mxp131011.element-plus-doc v2.0.8` now installs fine and the Settings Editor works.
