### ISSUE TITLE
CS50 library not included on the cloud based version

### ISSUE THREAD

**Issue by yashikagupta7** [microsoft/vscode#195096]
ADD ISSUE DESCRIPTION HERE
I am on Week 2 of CS50 Introduction to Computer Science and yesterday some configuration took place and now I am not able to run codes since #include <cs50.h> is showing errors.
Please look into the matter and let me know how to proceed.
Version: 1.83.0
Commit: e7e037083ff4455cf320e344325dacb480062c3c
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36
Embedder: codespaces

**Comment by gjsjohnmurray** [comment]
Please raise this on the course support channel.
