### ISSUE TITLE
It seems to start really slow

### ISSUE THREAD

**Issue by gabrielwolfw** [microsoft/vscode#195050]
Type: <b>Performance Issue</b>

Since 2 months, I've been experincing some delay when I open the vscode, I've tried everything, since restarting my computer but the problem is still there.

VS Code version: Code 1.83.0 (e7e037083ff4455cf320e344325dacb480062c3c, 2023-10-03T16:12:16.321Z)
OS version: Windows_NT x64 10.0.22621
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 5700U with Radeon Graphics          (16 x 1797)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|7.35GB (1.29GB free)|
|Process Argv|--crash-reporter-id e346b334-073d-4b3d-90fd-a5a9e27b04f5|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	   111	 17140	code main
    0	   128	   892	extensionHost [1]
    0	    92	  3428	     electron-nodejs ("C:\Users\kevin\AppData\Local\Programs\Microsoft VS Code\Code.exe" --ms-enable-electron-run-as-node "c:\Users\kevin\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\html-language-features\server\dist\node\htmlServerMain" --node-ipc --clientProcessId=892)
    0	   198	 14636	     "C:\Program Files\dotnet\dotnet.exe" c:\Users\kevin\.vscode\extensions\ms-dotnettools.csharp-2.5.30-win32-x64\.roslyn\Microsoft.CodeAnalysis.LanguageServer.dll --logLevel Information --telemetryLevel all --extensionLogDirectory c:\Users\kevin\AppData\Roaming\Code\logs\20231006T231737\window1\exthost\ms-dotnettools.csharp
    0	   182	  1856	   gpu-process
    0	   100	 10864	shared-process
    0	    64	 12556	   crashpad-handler
    0	    67	 13304	   utility-network-service
    0	    89	 16924	window [2] (Issue Reporter)
    0	    84	 17588	fileWatcher [1]
    0	   166	 20212	window [1] (cliente-login.component.html - cinemaTec - Visual Studio Code)
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (cliente-login.component.html - cinemaTec - Visual Studio Code)
|    Folder (cinemaTec): 465 files
|      File types: json(296) dll(29) ts(23) css(11) html(11) cs(8) cache(7)
|                  txt(5) xlsx(5) props(4)
|      Conf files: launch.json(2) tasks.json(2) package.json(2)
|                  tsconfig.json(2) csproj(1)
|      Launch Configs: coreclr(2);
```

</details>
<details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
csharp|ms-|2.5.30
vscode-dotnet-runtime|ms-|1.8.0
python|ms-|2023.18.0
vscode-pylance|ms-|2023.10.10
cpptools|ms-|1.17.5

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
2e4cg342:30602488
f6dab269:30613381
a9j8j154:30646983
showlangstatbar:30737416
03d35959:30757346
pythonfmttext:30731395
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
pythonnosmt12:30797651
pythonidxptcf:30805731
pythonnoceb:30805159
copilotsettingc:30839828
dsvsc013:30795093
dsvsc014:30804076
diffeditorv1:30821571
dsvsc015:30845448

```

</details>

**Comment by tamuratak** [comment]
Do you have McAfee antivirus installed? See #178962
