### ISSUE TITLE
Explorer panel will not be the first panel on startup when moving Outline

### ISSUE THREAD

**Issue by Newex** [microsoft/vscode#195087]
Type: <b>Bug</b>

Steps to reproduce:

1) Open VSCode
2) Move "Outline" panel to right side bar
3) Close VSCode
4) Open VScode
5) Startup view now shows "Search" panel

---
Expected result:
5) Startup should still show "Explorer" panel but without the "Outline"

VS Code version: Code 1.83.0 (e7e037083ff4455cf320e344325dacb480062c3c, 2023-10-03T16:12:16.321Z)
OS version: Windows_NT x64 10.0.19045
Modes:
Remote OS version: Linux x64 5.15.90.1-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 3700X 8-Core Processor              (16 x 3600)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.95GB (18.45GB free)|
|Process Argv|--crash-reporter-id 18406b9f-26e7-471d-a972-6d263ba63d94|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-23.04|
|OS|Linux x64 5.15.90.1-microsoft-standard-WSL2|
|CPUs|AMD Ryzen 7 3700X 8-Core Processor (4 x 3600)|
|Memory (System)|7.76GB (6.26GB free)|
|VM|0%|
</details><details><summary>Extensions (27)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-firefox-debug|fir|2.9.10
auto-close-tag|for|0.5.14
goto-next-previous-member|mis|0.0.6
remote-wsl|ms-|0.81.7
material-icon-theme|PKi|4.31.0
vim|vsc|1.26.0
codesnap|adp|1.3.4
github-markdown-preview|bie|0.3.0
markdown-checkbox|bie|0.4.0
markdown-emoji|bie|0.3.0
markdown-footnotes|bie|0.1.1
markdown-mermaid|bie|1.20.0
markdown-preview-github-styles|bie|2.0.3
markdown-yaml-preamble|bie|0.1.0
vscode-tailwindcss|bra|0.10.0
gitlens|eam|14.3.0
dotnet-test-explorer|for|0.7.8
todo-tree|Gru|0.0.226
csharpextensions|kre|1.7.3
git-graph|mhu|1.30.0
csharp|ms-|2.5.30
vscode-dotnet-runtime|ms-|1.8.0
vscode-kubernetes-tools|ms-|1.3.15
bun-vscode|ove|0.0.11
vscode-yaml|red|1.14.0
svelte-vscode|sve|107.11.0
vitest-explorer|Zix|0.2.42

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
3biah626:30602489
f6dab269:30613381
showlangstatbar:30737416
962ge761:30841074
03d35959:30757346
pythonfmttext:30731395
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
pythonnosmt12:30797651
pythonidxpt:30805730
pythonnoceb:30805159
copilotsettingc:30839828
dsvsc013:30795093
dsvsc014:30804076
diffeditorv2:30821572
dsvsc015:30845448

```

</details>

**Comment by sbatten** [comment]
I am unable to reproduce this behavior. Is this still happening for you?

**Comment by Newex** [comment]
It seems to be working now!
