### ISSUE TITLE
create zone widget for my own vscode extension

### ISSUE THREAD

**Issue by lucifan** [microsoft/vscode#195095]
Hello.

I found that copilot chat display a zone widget inside textEditor when using fix feature.

![image](https://github.com/microsoft/vscode/assets/9302739/51d09789-9cfe-424b-bf9c-b4ea5cbbb1b4)

I want to invoke a zone widget like this in my own vscode extension and customize the ui, but I can't find any documents relevant. Is there any way to work around?

**Comment by gjsjohnmurray** [comment]
See #85682 for proposed API, though there's currently no timetable for finalization.
