### ISSUE TITLE
[Extension API] Drag and Drop controller for `text/uri-list` appears to be broken with multiple URIs

### ISSUE THREAD

**Issue by Luke-Callaghan23** [microsoft/vscode#195048]
Does this issue occur when all extensions are disabled?: Yes

Problem:

The [documentation](https://code.visualstudio.com/api/references/vscode-api#TreeDragAndDropController&lt;T&gt;) for the `TreeDragAndDropController<T>` interface function `handleDrag` says "The data for "text/uri-list" should be a string with `toString()`ed Uris separated by newlines" but it appears that this does not actually work.  It appears that when you provide two or more uris for the 'text/uri-list' MIME type (separated by newlines), it still attempts to open it as a single file with a single uri, as opposed to two separate URIs.  

Example, when providing the uri string to the `text/uri-list` data transfer:

```
file:///home/luke-callaghan/dev/node/vscode/wt/envs/test-color-context/data/chapters/chapter-1676055319229-52eb5f16-0986-4cea-a053-69983d27b07f/fragment-1676055319230-dec4e8b3-ee5b-4eb2-b6f6-13fa11f30af0.wt
file:///home/luke-callaghan/dev/node/vscode/wt/envs/test-color-context/data/chapters/chapter-1676055319229-52eb5f16-0986-4cea-a053-69983d27b07f/fragment-1696516859036-6177fe8c-fb36-487f-af66-e502420edfcc.wt
```
(ignore the absurdly long paths -- working on it)

I get this result: 

![image](https://github.com/microsoft/vscode/assets/56779108/6249cd17-a331-444e-a4fa-bb34a9e7aa31)

As you can see when I hover over the tab that vscode opened for me, the URI that vscode is attempting to read is the same literal string I pasted above, and not two separate tabs, like the documentation says it should.

I've confirmed that my drag/drop controller works well with single uris, but when I try to provide more than one it breaks.

- VS Code Version: Visual Studio Code - Insiders October 2023 (version 1.84)
- OS Version: Windows 11

Steps to Reproduce:

1. Create a tree view with Drag and Drop controller [Microsoft Example](https://github.com/microsoft/vscode-extension-samples/tree/main/tree-view-sample)
2. Make sure the value `'text/uri-list'` is in the `dragMimeTypes` and `dropMimeTypes` arrays
3. In `handleDrag` add the line `treeDataTransfer.set('text/uri-list', new vscode.DataTransferItem("<<URI 1>>\n<<URI 2>>"));` replacing "<< URI 1>>" and "<< URI 2>>" with the uris for two valid files on your file system.
5. Simulate a drag/drop of multiple items by dragging one of the items in your tree view into the editor.
6. An error screen will appear, as vscode attempted to open a file literally "<< URI 1 >>\n<< URI 2 >>" instead of two separate URIs (which is the behavior).

(NOTE: I've tried this on linux as well.  I've also tried this by escaping the newline's escape character ("<<URI 1>>\\n<<URI 2>>") -- does not work with either)

**Comment by ArturoDent** [comment]
Could it be that the Uri separator should be `\r\n` and not just `\n`?

**Comment by alexr00** [comment]
Per documentation elsewhere, it should be `\r\n`:

https://github.com/microsoft/vscode/blob/302857c98ab1bb48423f1e0245b65c498e6edf86/src/vscode-dts/vscode.d.ts#L11254-L11258

Updating the other documentation here: https://github.com/microsoft/vscode/pull/195133

**Comment by alexr00** [comment]
I think the website documentation is updated from the JS doc in the codebase periodically. @gregvanl how often is the website API doc updated?

**Comment by gregvanl** [comment]
@alexr00 We update the API reference each release when we set the vscode.d.ts commit ID to the release commit. The next update will be at the beginning of November for the 1.84 release.
We don't typically move to a new commit ID mid-milestone since this would include APIs not yet released.

**Comment by alexr00** [comment]
Updating next release makes sense!
