### ISSUE TITLE
Does vscode support textmate lookbehind feature ?

### ISSUE THREAD

**Issue by Alphapage** [Microsoft/vscode#1950]
Hello,

I'm trying to achieve this in my syntax without success:
```
            <key>match</key>
            <string>--(?!-)(?<!\---).*\n</string> 
            <key>name</key>
			<string>comment.line</string>
```
It always skips --- but highlights all after --.

This code is working with oniguruma regex.

Thanks in advance for your answers.

**Comment by alexandrudima** [comment]
@Alphapage VSCode uses [vscode-textmate](https://www.npmjs.com/package/vscode-textmate) that in turn uses [oniguruma](https://www.npmjs.com/package/oniguruma) that contains [Oniguruma 5.9.6](https://github.com/atom/node-oniguruma/tree/master/deps/onig).

One thing that could go wrong is that `<` should be replaced with `&lt;` if you use xml as the file format (we also support JSON, but there you need to escape even more):

```
<key>match</key>
<string>--(?!-)(?&lt;!\---).*\n</string>
<key>name</key>
<string>comment.line</string>
```

![image](https://cloud.githubusercontent.com/assets/5047891/12298860/804b82c4-ba14-11e5-9671-2e7cf22ab5d8.png)

I think most TM syntax authors use YAML as the input language and then have a tool that converts YAML to plist XML. Here is for example the TypeScript syntax authored in YAML: https://github.com/Microsoft/TypeScript-Sublime-Plugin/blob/master/TypeScriptReact.YAML-tmLanguage

**Comment by Alphapage** [comment]
Sorry for my mistake.
Thank you very much for your help.

**Comment by alexandrudima** [comment]
Happy I could help! :+1:
