### ISSUE TITLE
JSON default snippets should respect indentation in file

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#19508]
- VSCode Version: 1.9
- OS Version: Windows

Steps to Reproduce:

1. Launch config
```json
  // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
  "version": "0.2.0",
  "configurations":
   [
    {
      "type": "node",
      "request": "launch",
      "name": "Launch Program",
      "program": "${workspaceRoot}/bin/www",
      "cwd": "${workspaceRoot}"
    },
    {
      "type": "node",
      "request": "attach",
      "name": "Attach to Process",
      "port": 5858
    }
  ]
}
```
2. Add Configuration, pick Launch via npm

You get

![capture](https://cloud.githubusercontent.com/assets/1931590/22373806/bdf19d7e-e4a3-11e6-8b31-4d3239b66687.png)

**Comment by isidorn** [comment]
Currently each debug extension contributes these snippets but the formating is done in the JSON world. To be more precise, each of these snippets is a [default snippet](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/debug/electron-browser/debugConfigurationManager.ts#L257) in a json schema.
When inserting snippets json schema should respect the indentation of the file, thus forwarding to @aeschli

**Comment by aeschli** [comment]
Insertion of snippets is done in the SnippetControler. It is my understanding that the code there applies the correct indentation and indentation characters.

**Comment by jrieken** [comment]
The snippet controller takes the indentation of the cursor and massages the snippet according to that. It seems like the 'Add Configuration' command doesn't always adjust the cursor properly before insert the snippet, for instance when at column 0

**Comment by jrieken** [comment]
![feb-21-2017 14-39-44](https://cloud.githubusercontent.com/assets/1794099/23167170/9d924e62-f843-11e6-94a4-ab5f42da2075.gif)

**Comment by weinand** [comment]
This sounds like a bug to me.
