### ISSUE TITLE
Build task opens two terminals at the same time

### ISSUE THREAD

**Issue by dlschmidt** [microsoft/vscode#195041]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.83.0

Steps to Reproduce:

1. Configure the integrated terminal as default: `"terminal.integrated.defaultLocation": "editor"`
2. Start the build task i.e. `workbench.action.tasks.build`
3. Now both the view terminal as well as the editor terminal opens, although only the editor terminal is necessary

It seems to be that the `"reveal": "always"` setting in tasks.json always opens a view panel, regardless of the `terminal.integrated.defaultLocation` setting.

**Comment by meganrogge** [comment]
I believe this is already fixed, can you see if you can reproduce in the [Insiders build](https://code.visualstudio.com/insiders)?
/label info-needed
