### ISSUE TITLE
vscode window has a certain chance of getting stuck when pressing a button, unless restarted

### ISSUE THREAD

**Issue by 751620780** [microsoft/vscode#195102]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: All versions in the past six months
- OS Version: Windows 10 10.0.19045.2604 

Steps to Reproduce:

There are two Windows computers A and B, each with the latest version of VScode installed
1. Use computer A to open the vscode window, write a program, and maintain it for a period of time, such as 12 hours of use
2. Use mstsc.exe on computer B to remotely access computer A and continue writing programs using the VScode window on computer A,
3. When pressing a key on the keyboard under the vscode window, the vscode window is likely to get stuck, such as pressing the A key in the code editor window or file or content search window.
4. Click on the vsocde task bar on the Windows taskbar could make the VScode window work properly, but pressing any button still causes the window to get stuck. The problem can only be resolved by closing all VScode windows on computer A and restarting VScode.
5. If there are still no issues in steps 2, 3, and 4, then continuing to use the A computer (not using a remote desktop) and continuing to use the previously opened vscode window still has a high probability of steps 3 and 4 occurring.

**Comment by 751620780** [comment]
same issue occurs in Edge browser

**Comment by 809825706** [comment]
I have the annoying problem too！

**Comment by deepak1556** [comment]
Thanks for the detailed steps, merging to https://github.com/microsoft/vscode/issues/167556
