### ISSUE TITLE
moving the cursor causes text area sync to be off on windows

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#195195]
1. use a screen reader and run a few commands in the terminal
2. press up arrow and use the left arrow to navigate through the command
3. run the command
4. 🐛 text area is no longer synced correctly

**Comment by alexr00** [comment]
@meganrogge what is the "text area"? I tried to repro the issue on stable and I looked at the accessible view, but I'm not sure what I'm looking for.

**Comment by meganrogge** [comment]
Enable "terminal.integrated.developer.devMode" to check the contents are right

**Comment by meganrogge** [comment]
Or use a screen reader and ensure that when navigating w arrow keys, the right chars are announced. 

In either case, need to be in screen reader optimized mode

**Comment by Tyriar** [comment]
Very cool to see this actually working for history 👏
