### ISSUE TITLE
Text wrapping in ipynb notebook outputs

### ISSUE THREAD

**Issue by WillFrasier** [microsoft/vscode#195187]
I have a python notebook and the text I print out happens to be very wide. I would love the option / configurable setting to automatically wrap the text. We have that option in the code editor, just not the results output. For instance, in the screenshot we see text wrapping in the code editor which is great! But for the result outputs I need to scroll to the right - this is super annoying. Please give us a configurable setting to set this to on by default.

<img width="930" alt="Screenshot_1" src="https://github.com/microsoft/vscode/assets/9486825/2f32e7fa-311f-4844-b0ca-62627d12455e">

**Comment by amunger** [comment]
"notebook.output.wordWrap": true
