### ISSUE TITLE
Focus stuck in Code on raw X session without window manager

### ISSUE THREAD

**Issue by Terminus-IMRC** [Microsoft/vscode#1951]
Hello.

Normally, on the raw X (i.e. without window managers), a window under the mouse cursor is active:
![raw.gif](https://cloud.githubusercontent.com/assets/4298265/12261607/7a216b66-b965-11e5-9b99-198c6a7aedb1.gif)

However, VSCode doesn't allow other windows to focus on even if the mouse cursor is over other windows:
![vs](https://cloud.githubusercontent.com/assets/4298265/12261639/bbe60958-b965-11e5-83af-ce770e27a6a2.gif)

I'm using VSCode 0.10.6 on Linux.
Running VSCode with ```--disable-extensions``` didn't solve the problem.

This behavior is inconvenient.
Why is this occurring and could you fix this?

Thanks in advance for your answers.

Regards,
Terminus-IMRC.

**Comment by bpasero** [comment]
Nice, I did not know you could start VS Code just with X! Can you try with a hello world Electron application to see if this reproduces and then report this to Electron? https://github.com/atom/electron/releases

**Comment by Terminus-IMRC** [comment]
Thank you for your reply.

The weird behavior is reproducible on a simple electron app.
So this is nothing to do with VS Code.

Sorry for my lack of research.

Thanks,
Terminus-IMRC.

**Comment by bpasero** [comment]
@Terminus-IMRC np, did you file it against Electron?

**Comment by Terminus-IMRC** [comment]
Yes I did: https://github.com/atom/electron/issues/4083

**Comment by bpasero** [comment]
Thanks!
