### ISSUE TITLE
404 when attempting to access `http://json-schema.org/schema` (don't attempt to access it)

### ISSUE THREAD

**Issue by gregsdennis** [microsoft/vscode#195190]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: any
- OS Version: any

Steps to Reproduce:

1. Open a new editor file with JSON selected as the language
2. Paste
    ```json
    {
      "$schema": "http://json-schema.org/schema"
    }
    ```

Reported [here (github)](https://github.com/json-schema-org/website/issues/118), [here (slack)](https://json-schema.slack.com/archives/C5CF75URH/p1696249012584239), and [here (github)](https://github.com/jimblackler/jsonschemafriend/issues/29).

This error is due to a revamped https://json-schema.org where we are only hosting HTTPS content.  I believe we _are_ serving a 301 from the meta-schema URLs, though.

Problems:

1. `http://json-schema.org/schema` should never be used to identify a meta-schema.  This is not a valid meta-schema URI.  Historically this URL hosted the latest meta-schema, but that led to unpredictable behaviors as new versions were released and the "latest" was updated, so we decided to remove it.
2. The value of `$schema` is to be interpreted as a URI, not a URL.  If the value happens to also be a URL, it is not to be interpreted to actually _be_ at that location.  It is an identifier only.
3. Implementations (including editors) should not be downloading well-known meta-schemas.  They should be packaged with the implementation.  (@6nv, does the problem still occur if you use `http://json-schema.org/draft-07/schema#` or another well-known meta-schema URI?)

**Comment by 6nv** [comment]
I opened #195189 which is updated using the `https` protocol.

**Comment by gregsdennis** [comment]
I'll close this and post the guidance over there.
