### ISSUE TITLE
Activity bar top: double '...' can cause confusion

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#195132]
Move activity bar to top
If I do not have enough horizontal space we will render double '...'
This can cause confusion. I know this problem already exists in the panel, but here we have much less horizontal space and I expect it to happen more often.

Can we have a better ux solution here?
Should we somehow merge these two menus?

![Screenshot 2023-10-09 at 11 18 47](https://github.com/microsoft/vscode/assets/1926584/bc1298ff-e0e7-4cce-ab39-37c94b310aaf)

**Comment by sandy081** [comment]
Merging them might not be correct when there are actions contributed by view containers (for eg., debug)

<img width="513" alt="image" src="https://github.com/microsoft/vscode/assets/10746682/4bea386d-29ba-4d95-a715-f240317a8fc9">

May be we should use different icon for view containers overflow action?

**Comment by abhijit-chikane** [comment]
couple of issues related to this
1. I can drag the extension and source control panel to the secondary side bar only if it is empty.
2. Some extensions icons are not visible properly in the top bar
![image](https://github.com/microsoft/vscode/assets/50770619/eb4c42fc-1713-471a-82b5-f0f9a4524a0f)
![image](https://github.com/microsoft/vscode/assets/50770619/c78ee6a3-8ed9-47cc-aff3-af5c7b2cca4b)

3. The look of the top bar on secondary looks a bit different (would like to look and behave the same)
4. One feature request is allow to have activity bar for the secondary bar as well

**Comment by sandy081** [comment]
![image](https://github.com/microsoft/vscode/assets/10746682/551886f0-e197-45a4-b666-4e27f6d28f35)

@isidorn What do you think?

**Comment by isidorn** [comment]
That might work, but we usually use that UI to indicate something can be expanded. This would be a new UI metaphor.
Let's see what Hylke or others in the team say. Maybe present in standup tomorrow?

**Comment by gjsjohnmurray** [comment]
Maybe this initially:

![image](https://github.com/microsoft/vscode/assets/6726799/1e4c21a7-e39a-449c-aed0-89fe9f84b25b)

Turning to this when clicked:

![image](https://github.com/microsoft/vscode/assets/6726799/2efcfb92-5513-4e4c-9864-6c4ab61298fe)

**Comment by T-256** [comment]
You can also consider https://github.com/microsoft/vscode/issues/195903:
> 
> ### Before (now):
> ![image](https://user-images.githubusercontent.com/132141463/276246007-2b4ae1b0-b567-4055-b7b1-09dcaaeb924e.png)
> 
> ### After:
> ![image](https://user-images.githubusercontent.com/132141463/276247952-4feeb155-1cce-4ebf-8d0d-742bd7c12cd8.png)
