### ISSUE TITLE
Edit the value of variables at a breakpoint when debugging Dart

### ISSUE THREAD

**Issue by WorikQCI** [microsoft/vscode#195192]
* Debuging a Dart programme
* Stopped at a break point
* I want to be able to edit the value of a variable

```
Version: 1.81.0 (Universal)
Commit: 6445d93c81ebe42c4cbd7a60712e0b17d9463e97
Date: 2023-08-02T12:40:02.782Z
Electron: 22.3.18
ElectronBuildId: 22689846
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Darwin arm64 22.5.0
```

`Dart SDK version: 3.1.2 (stable) (Tue Sep 12 16:26:23 2023 +0000) on "macos_arm64"`

**Comment by roblourens** [comment]
VS Code supports this but the Dart extension would need to implement this if it doesn't work
