### ISSUE TITLE
old keybinding for resourceScheme "vscode-interactive" for `interactive.execute`

### ISSUE THREAD

**Issue by Aetf** [microsoft/vscode#195171]
### Applies To

- [ ] Notebooks (.ipynb files)
- [X] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

Shift+Enter doesn't execute the command in interactive window command line anymore, instead, it sends content to a new command line python interpreator.

```
INFO [KeybindingService]: | Resolving shift+Enter
INFO [KeybindingService]: \ From 16 keybinding entries, matched python.execSelectionInTerminal, when: editorTextFocus && !findInputFocussed && !jupyter.ownsSelection && !notebookEditorFocused && !replaceInputFocussed && editorLangId == 'python', source: user extension ms-python.python.
INFO [KeybindingService]: + Invoking command python.execSelectionInTerminal.
```

After debugging, it turns out that the when clause of the keybinding `Shift+Enter` for `interactive.execute` isn't matched, thus the next one for `python.execSelectionInCommandLine` is selected.

This is confirmed by inspecting the when clause context:

![image](https://github.com/microsoft/vscode-jupyter/assets/1519759/54875ff3-e7cd-453e-b2ea-25418daada89)

The `resourceScheme` is `untitled`, rather than `vscode-interactive` as expected.

I workedaround the issue by change the when clause to the following:

```
!notebookKernel && resourceExtname == '.interactive' || !notebookKernel && resourceScheme == 'vscode-interactive' || resourceExtname == '.interactive' && notebookKernel =~ /^ms-toolsai.jupyter\// || resourceScheme == 'vscode-interactive' && notebookKernel =~ /^ms-toolsai.jupyter\//
```

### VS Code Version

code-server: v4.16.1 Code: 1.80.2 Commit: 2ccd690cbff1569e4a83d7c43d45101f817401dc Date: 2023-07-31T17:15:21.760Z Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36 Edg/117.0.2045.47

### Jupyter Extension Version

2023.3.100

### Running Jupyter locally or remotely?

None

**Comment by Aetf** [comment]
Hi @amunger, so this will be solved by a newer jupyter extension version? Do you know which version specifically to look for?

**Comment by amunger** [comment]
I'm not sure which version had the right update. From the issue info, you are on `2023.3.100` and `2023.9.100` was just released last week.
