### ISSUE TITLE
Using Tab with multiple cursors

### ISSUE THREAD

**Issue by pjlamb12** [Microsoft/vscode#19518]
- VSCode Version: Code 1.8.1 (ee428b0eead68bf0fb99ab5fdc4439be227b6281, 2016-12-19T14:42:49.304Z)
- OS Version: Darwin x64 16.3.0
- Extensions:

|Extension|Author|Version|
|---|---|---|
|EditorConfig|EditorConfig|0.3.4|
|beautify|HookyQR|0.7.3|
|vscode-docker|PeterJausovec|0.0.11|
|code-settings-sync|Shan|2.4.2|
|Bookmarks|alefragnani|0.10.2|
|vscode-mocha-latte|cspotcode|0.2.0|
|vscode-eslint|dbaeumer|1.2.2|
|tslint|eg2|0.8.1|
|auto-close-tag|formulahendry|0.3.9|
|macros|geddski|1.2.0|
|vscode-auto-open-markdown-preview|hnw|0.0.3|
|icon-fonts|idleberg|1.3.1|
|path-autocomplete|ionutvmi|1.4.1|
|vscode-angular2-emmet|jakethashi|1.0.11|
|vscode-text-pastry|jkjustjoshing|1.1.0|
|Angular2|johnpapa|1.0.2|
|vscode-insertdatestring|jsynowiec|1.1.2|
|mssql|ms-mssql|0.2.0|
|debugger-for-chrome|msjsdiag|2.4.2|
|color-highlight|naumovs|1.3.0|
|vscode-fileutils|sleistner|2.3.3|
|pasteandformat|spoeken|0.0.5|
|es-quotes|vilicvane|0.2.4|
|expand-selection-to-scope|vittorioromeo|0.1.0|
|bootstrap-3-snippets|wcwhitehead|0.0.9|
|theme-cobalt2|wesbos|2.0.10|
|vscode-js-console-utils|whtouche|0.7.0|
|JavaScriptSnippets|xabikos|1.2.0|

---

Steps to Reproduce:

1. Place multiple cursors in the page
2. Go to beginning of line for each cursor
3. Press tab (\t)

Only the first, original cursor, tabs. I don't see why that functionality happens when I can edit and select text all over with the multiple cursors. Why does tab have different functionality?

**Comment by coreh** [comment]
It works normally for me... Do you have any settings that affect tabs enabled?

**Comment by egamma** [comment]
I assume this happens in an emmet enabled language when emmet consumes the the tab key. This would be issue #1050.

**Comment by pjlamb12** [comment]
This happens (still) to me when in a TypeScript file.

**Comment by alexandrudima** [comment]
@pjlamb12 

Unfortunately I cannot reproduce:

![19518](https://cloud.githubusercontent.com/assets/5047891/23702320/03c02cbe-03fb-11e7-82e9-d8cfa98752f0.gif)

Does the issue still occur when you launch VS Code w/ extensions disabled? From the command line: `code --disable-extensions`

**Comment by pjlamb12** [comment]
@alexandrudima I removed the jakethashi.vscode-angular2-emmet extension and now this works. Thanks for your help!
