### ISSUE TITLE
Crashed loading in WSL

### ISSUE THREAD

**Issue by stevenlafl** [microsoft/vscode#195162]
Type: <b>Bug</b>

No idea

VS Code version: Code - Insiders 1.84.0-insider (4a0e77678c0295b518151ae2d706436bab96ef4f, 2023-10-04T17:34:48.257Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Remote OS version: Linux x64 5.15.90.1-microsoft-standard-WSL2
Remote OS version: Linux x64 5.15.90.1-microsoft-standard-WSL2
Remote OS version: Linux x64 5.15.90.1-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 9 5950X 16-Core Processor             (32 x 3700)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|127.91GB (77.25GB free)|
|Process Argv|--crash-reporter-id 83eed0fe-cdfd-4558-a138-7d82f868fa95|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Debian|
|OS|Linux x64 5.15.90.1-microsoft-standard-WSL2|
|CPUs|AMD Ryzen 9 5950X 16-Core Processor (32 x 3700)|
|Memory (System)|62.75GB (58.55GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Debian|
|OS|Linux x64 5.15.90.1-microsoft-standard-WSL2|
|CPUs|AMD Ryzen 9 5950X 16-Core Processor (32 x 3700)|
|Memory (System)|62.75GB (58.55GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Debian|
|OS|Linux x64 5.15.90.1-microsoft-standard-WSL2|
|CPUs|AMD Ryzen 9 5950X 16-Core Processor (32 x 3700)|
|Memory (System)|62.75GB (58.55GB free)|
|VM|0%|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
remote-containers|ms-|0.317.0
remote-wsl|ms-|0.81.7
vscode-intelephense-client|bme|1.9.5
copilot|Git|1.123.471
copilot-chat|Git|0.9.2023100601
copilot-labs|Git|0.15.1019
vscode-github-actions|git|0.26.2
VS-code-drupal|mar|0.0.12
vscode-docker|ms-|1.26.1
php-debug|xde|1.33.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythontb:30258533
pythonptprofiler:30281269
vshan820:30294714
vscod805cf:30301675
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30404738
py29gd2263:30784851
vsclangdf:30492506
c4g48928:30535728
dsvsc012:30540252
pynewext54:30618038
a9j8j154:30646983
showlangstatbar:30737417
7ij38806:30687742
pythonfmttext:30716741
fixshowwlkth:30771523
showindicator:30805243
pythongtdpath:30726887
i26e3531:30792625
welcomedialog:30812478
pythonnosmt12:30779711
pythonidxpt:30768918
pythonnoceb:30776497
copilotsettingt:30808721
dsvsc013:30777762
dsvsc014:30777825
diffeditorv2:30786206
pythonmpsinfo:30842935
dsvsc015:30821418
pythontestfixt:30826906
pythonfb280951:30830809
pythonregdiag:30842812
pythonmypyd1cf:30850306
pythoncet0cf:30848248

```

</details>

**Comment by corbett5** [comment]
I'm just going to piggyback on this issue, but VSCode also crashes for me when trying to access WSL. This just started today after updating versions, but it was also right after a BSD crash that my guess was caused from within WSL.


```
benc@desktop:/mnt/c/Users/Ben$ VSCODE_WSL_DEBUG_INFO=true code .
+ COMMIT=e7e037083ff4455cf320e344325dacb480062c3c
+ APP_NAME=code
+ QUALITY=stable
+ NAME=Code
+ SERVERDATAFOLDER=.vscode-server
+ realpath /mnt/c/Users/Ben/AppData/Local/Programs/Microsoft VS Code/bin/code
+ dirname /mnt/c/Users/Ben/AppData/Local/Programs/Microsoft VS Code/bin/code
+ dirname /mnt/c/Users/Ben/AppData/Local/Programs/Microsoft VS Code/bin
+ VSCODE_PATH=/mnt/c/Users/Ben/AppData/Local/Programs/Microsoft VS Code
+ ELECTRON=/mnt/c/Users/Ben/AppData/Local/Programs/Microsoft VS Code/Code.exe
+ IN_WSL=false
+ [ -n Ubuntu ]
+ IN_WSL=true
+ [ true = true ]
+ export WSLENV=ELECTRON_RUN_AS_NODE/w:
+ wslpath -m /mnt/c/Users/Ben/AppData/Local/Programs/Microsoft VS Code/resources/app/out/cli.js
+ CLI=C:/Users/Ben/AppData/Local/Programs/Microsoft VS Code/resources/app/out/cli.js
+ WSL_EXT_ID=ms-vscode-remote.remote-wsl
+ ELECTRON_RUN_AS_NODE=1 /mnt/c/Users/Ben/AppData/Local/Programs/Microsoft VS Code/Code.exe C:/Users/Ben/AppData/Local/Programs/Microsoft VS Code/resources/app/out/cli.js --ms-enable-electron-run-as-node --locate-extension ms-vscode-remote.remote-wsl
+ cat /tmp/remote-wsl-loc.txt
+ WSL_EXT_WLOC=c:\Users\Ben\.vscode\extensions\ms-vscode-remote.remote-wsl-0.81.7
+ [ -n c:\Users\Ben\.vscode\extensions\ms-vscode-remote.remote-wsl-0.81.7 ]
+ wslpath -u c:\Users\Ben\.vscode\extensions\ms-vscode-remote.remote-wsl-0.81.7
+ WSL_CODE=/mnt/c/Users/Ben/.vscode/extensions/ms-vscode-remote.remote-wsl-0.81.7/scripts/wslCode.sh
+ /mnt/c/Users/Ben/.vscode/extensions/ms-vscode-remote.remote-wsl-0.81.7/scripts/wslCode.sh e7e037083ff4455cf320e344325dacb480062c3c stable /mnt/c/Users/Ben/AppData/Local/Programs/Microsoft VS Code/Code.exe code .vscode-server .
+ [ -z .vscode-server ]
+ [ .vscode-server = .vscode-insiders ]
+ [ ! -t 0 ]
+ VSCODE_REMOTE_BIN=/home/benc/.vscode-server/bin
+ AUTHORITY=wsl+default
+ [ Ubuntu ]
+ AUTHORITY=wsl+Ubuntu
+ dirname /mnt/c/Users/Ben/.vscode/extensions/ms-vscode-remote.remote-wsl-0.81.7/scripts/wslCode.sh
+ /mnt/c/Users/Ben/.vscode/extensions/ms-vscode-remote.remote-wsl-0.81.7/scripts/wslDownload.sh e7e037083ff4455cf320e344325dacb480062c3c stable /home/benc/.vscode-server/bin
+ [ ! -d /home/benc/.vscode-server/bin/e7e037083ff4455cf320e344325dacb480062c3c ]
+ RC=0
+ [ 0 -ne 0 ]
+ mktemp /tmp/vscode-distro-env.XXXXXX
+ STORED_ENV=/tmp/vscode-distro-env.qZV5DD
+ env
+ dirname /mnt/c/Users/Ben/.vscode/extensions/ms-vscode-remote.remote-wsl-0.81.7/scripts/wslCode.sh
+ VSCODE_CLIENT_COMMAND=/mnt/c/Users/Ben/AppData/Local/Programs/Microsoft VS Code/Code.exe VSCODE_CLIENT_COMMAND_CWD=/mnt/c/Users/Ben/.vscode/extensions/ms-vscode-remote.remote-wsl-0.81.7/scripts VSCODE_CLI_AUTHORITY=wsl+Ubuntu VSCODE_CLI_REMOTE_ENV=/tmp/vscode-distro-env.qZV5DD VSCODE_STDIN_FILE_PATH= WSLENV=VSCODE_CLI_REMOTE_ENV/w:ELECTRON_RUN_AS_NODE/w: /home/benc/.vscode-server/bin/e7e037083ff4455cf320e344325dacb480062c3c/bin/remote-cli/code .
Segmentation fault
+ exit 139
```

**Comment by aeschli** [comment]
Segmentation fault points to a WSL issue. I suggest to restart WSL:
- Close all programs running in WSL including VS Code and run `wsl --shutdown`
- Also worth checking is if the server install is corrupt. Close all instances of VS Code and on a WSL terminal run `rm -r ~./vscode-server/bin`
