### ISSUE TITLE
"Focus Activity Bar" when activity bar top produces double activity bar

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#195131]
1. Move activity bar to top
2. F1 > "Focus Activity Bar"
3. Activity bar on the left gets focused. And now I have 2 activity bars 🐛 

![Screenshot 2023-10-09 at 11 15 50](https://github.com/microsoft/vscode/assets/1926584/724c3ef6-fb77-4f19-be97-7a7db5c67d2d)

**Comment by sandy081** [comment]
Good catch
