### ISSUE TITLE
Feature Request: Hotkey to turn preview tab into real tab

### ISSUE THREAD

**Issue by krryan** [Microsoft/vscode#19512]
Very simple: I like preview mode a lot of the time. But sometimes I want to actually, for-real open several tabs using `Ctrl`+`P`. Currently, this means either an edit/undo cycle (ew), or grabbing the mouse and double-clicking the tab (even more ew).

I would therefore really like some way to turn a preview tab into a real tab without either editing the file or taking my hands off the keyboard.

**Comment by bpasero** [comment]
Ctrl+K Enter (`workbench.action.keepEditor`)
