### ISSUE TITLE
Missing content during and unfilled initial layout of terminal

### ISSUE THREAD

**Issue by tisilent** [microsoft/vscode#195167]
Version: 1.83.0 (user setup)

![bug](https://github.com/microsoft/vscode/assets/48614781/550e2d1b-c7f5-453c-b458-f573be3e6964)

Setps:
1. Create New Terminal
2. Reload Window
3. Selection

**Comment by meganrogge** [comment]
Hey, thanks for looking into this - can you clarify what step 3 is here to reproduce the issue?

> Selection

**Comment by tisilent** [comment]
Alternatively, by resizing the terminal through Sash, it will return to normal.

**Comment by meganrogge** [comment]
What step am I missing here?

https://github.com/microsoft/vscode/assets/29464607/a12807c9-0575-464e-850f-7493161cb3c1

**Comment by tisilent** [comment]
https://github.com/microsoft/vscode/assets/48614781/cf267048-04a0-469e-8e9f-545da447174b


I just found out that setting GUP to OFF is normal. Please take a look at your settings. :hushed:...

**Comment by meganrogge** [comment]
maybe this is a windows only issue, still not reproducing

https://github.com/microsoft/vscode/assets/29464607/0d0a26e6-033d-44ac-acc8-2717843f8035

**Comment by tisilent** [comment]
I think it's related to the shell.

**Comment by Tyriar** [comment]
This has been fixed since
