### ISSUE TITLE
Support activity bar on top when title bar is not shown

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#195137]
I like that when activity bar top is set that we move the Settings and Accounts to the title area.
However, if I do not have title area enabled, we do not show these actions anywhere?

My concern is that a lot of users do not have title area enabled, and now they might start missing on VS Code updates.
I think we need a solution for those users as well.

![Screenshot 2023-10-09 at 11 35 05](https://github.com/microsoft/vscode/assets/1926584/ae261126-a6cf-4398-97e5-5b214d1e7134)

**Comment by sandy081** [comment]
@isidorn At present, I do not support activity bar top position if there is no title bar mainly because of this reason. Activity bar remains on side in this case. Please try out.

**Comment by isidorn** [comment]
I see that the default title bar style is native on windows, and on macOS and Win is custom. Which makes sense.

@sbatten can you remind me - what is blocking us from having custom on Linux as default as well?
@sandy081 it would be cool if we also have a solution for activity bar top for our Linux users - in case we can not change the default title bar to be custom.

**Comment by bpasero** [comment]
One thing that I had discussed with @joaomoreno : our custom title bar becomes more than just a title container, we put command center in there and now more toolbar actions. But we have cases where native title bar is required, for example when macOS native tabs are enabled.

So how about making it possible to show both native and custom title at the same time? We sort of do this already in web actually.

**Comment by sandy081** [comment]
CC @sbatten @daviddossett 

What's your opinion?

**Comment by sbatten** [comment]
We don't use the custom title on native linux as WCO is not yet available on Linux. When that happens, we can consider adoption and moving over. As for showing both, I think it can be possible, but it is a lot of vertical real estate. In web, we adopted WCO asap to give a better web experience.

**Comment by bpasero** [comment]
> We don't use the custom title on native linux as WCO is not yet available on Linux.

Just to clarify: We do have a custom implementation of window buttons that work fine on Linux, when you configure `window.titleBarStyle` to `custom`. We are not dependent on Electron shipping WCO support on Linux only to have a functional custom title in VS Code for Linux.

**Comment by sbatten** [comment]
That's right, but because we force Windows styling on our custom controls and we can't re-implement the slew of Linux WM features, the WCOs would be a better solution to bringing the custom title bar to Linux.

**Comment by sandy081** [comment]
This is now supported with @benibenj improvements.

**Comment by benibenj** [comment]
verification steps for insiders:
1. set `window.titleBarStyle` to `native`
2. move activity bar to top `workbench.activityBar.location`
3. Should see the custom title bar below native title bar with activity bar actions in the top right
