### ISSUE TITLE
Unable to add second tab to secondary sidebar in current Insiders

### ISSUE THREAD

**Issue by gjsjohnmurray** [microsoft/vscode#195166]
Type: <b>Bug</b>

1. Launch Insiders
2. Run the command `Profiles: Create a Temporary Profile`
3. Select Explorer in Activity Bar.
4. Drag Timeline view to the right-hand edge of the window and drop it into the empty Secondary Sidebar that appears there.
5. Drag the Outline view and try to drop it alongside the Timeline tab that the previous step added to the top of Secondary Sidebar.

:bug: nothing happens.

The same steps work correctly in 1.83 Stable.

VS Code version: Code - Insiders 1.84.0-insider (55d1cfea45b665bb54e46d11bd3ccddf9e66108b, 2023-10-09T06:11:57.204Z)
OS version: Windows_NT x64 10.0.22621
Modes:

**Comment by sandy081** [comment]
@gjsjohnmurray I cannot reproduce it. Can you please revalidate the steps?

**Comment by gjsjohnmurray** [comment]
Looks like has already been fixed somewhere.
