### ISSUE TITLE
Badge decoration in Activity Bar top needs UX love

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#195130]
Move activity bar to the top. Notice how the badge decoration is the same size as any activity bar icon, and looks like a separate entry.

I think we need to make it look more aligned with the viewlet it belongs to (in this case SCM), and potentially make it smaller so users know it is a badge.

![Screenshot 2023-10-09 at 11 11 39](https://github.com/microsoft/vscode/assets/1926584/278aaa69-65a6-4c9b-8b95-5aaf99b15371)

**Comment by isidorn** [comment]
Also I think we need a bit more breathing room between icons. I suggest something two more pixels between each icon. Thus each icon needs 1px or 2px more padding. Here's how that could look

![Screenshot 2023-10-09 at 11 22 45](https://github.com/microsoft/vscode/assets/1926584/bef8b421-f11b-4f84-84ae-3a531aabed34)

**Comment by sandy081** [comment]
At present this is reusing the same design like in secondary side bar. I like that these tool bars in both side bars looks same. I do not see a reason to differentiate.

**Comment by isidorn** [comment]
Badges were not designed to be used inline in a horizontal activity bar.
I really think we need some ux love here. Due to the two reasons I mentioned above (not differentiated compared to regular items, and I can not say if a badge belongs to the left or right item from it).

also fyi @daviddossett @joaomoreno

**Comment by gjsjohnmurray** [comment]
Could the badge float under the icon by a few pixels?

**Comment by gjsjohnmurray** [comment]
Or set `border-bottom-left-radius: 0px; border-top-left-radius: 0px;`

**Comment by GBrachetta** [comment]
I don't see a way to move the activity bar to the top. Could you please let me know what's the setting for that? Thanks.

**Comment by gjsjohnmurray** [comment]
@GBrachetta are you using Insiders? It's only available there, and you access it from the Activity Bar context menu.

**Comment by gjsjohnmurray** [comment]
From #195140:
> if Git SCM performs periodic fetch all icons to the right of the SCM one get shifted right momentarily.

> Perhaps spin the SCM icon to denote in-progress activity, instead of adding a clock to the right of it.

**Comment by isidorn** [comment]
That looks great! Why just the progress badge, why not all badges like that?

**Comment by gjsjohnmurray** [comment]
> That looks great! Why just the progress badge, why not all badges like that?

Might be hard to read the count badge when scaled down small enough to overlay rather than obscure the tab icon.

**Comment by sandy081** [comment]
![CleanShot 2023-10-11 at 08 19 00@2x](https://github.com/microsoft/vscode/assets/10746682/61692943-5e58-441c-80c0-46361e6b0256)

This is the recommendation from UX sync which I liked - to show just dot

**Comment by gjsjohnmurray** [comment]
For some extensions the badge on their Activity Bar icon is the only place where the actual count number shows. For example, with the Bookmarks extension we would no longer be able to see how many bookmarks exist, not even if we select that tab.

**Comment by isidorn** [comment]
I like the dot. Especially if it will not push the other items when it shows up.

**Comment by sandy081** [comment]
<img width="335" alt="image" src="https://github.com/microsoft/vscode/assets/10746682/79ba4164-8bc7-407b-9bb7-19287a28dd3a">

@gjsjohnmurray You have a point about the badge content. Content is also shown in the hover, so I think this is a good compromise.
