### ISSUE TITLE
Activity bar location: capture telemetry

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#195136]
Let's capture in telemetry the location of the activity bar for a user.
I think we can use this information to decide in the future if we should change the default for new users.

**Comment by sandy081** [comment]
Since it is a setting, is it captured already when user changes the setting?

**Comment by isidorn** [comment]
Yes, but we can only see how many users changed the setting in past 28 days. We can not see how many users have this setting to on all the time.
Also we do not know what value the user actually set it to https://github.com/microsoft/vscode-internalbacklog/issues/4479

I do not think we need to tackle this issue right now. But if we see a compelling case to switch the default for new users in the future.
