### ISSUE TITLE
'noDebug' flag not passed to debug adapter

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#19517]
- VSCode Version: 1.9.0
- OS Version: macOS

Steps to Reproduce:

1. set a breakpoint in node program
2. start a node debug session with "Start without Debugging" action

Observe: breakpoint is hit

I've debugged this and I saw that the "noDebug" flag isn't passed to the DA.

If you add a `"noDebug": true` to the launch config, the breakpoint is not hit, so the DA is working fine.

**Comment by isidorn** [comment]
@weinand I cherry picked this on top of the 1.9 branch. Please verify run works as expected and the usual debug start works as before.

**Comment by weinand** [comment]
@isidorn I've verified the fix on the 1.9 branch and now "Start without Debugging" works fine.
