### ISSUE TITLE
Settings editor: hovering over a section doesn't look good in some themes

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode#19519]
From https://github.com/Microsoft/vscode/issues/17103#issuecomment-275406011

There is still some ugly grey e.g. when hovering over a section:

![image](https://cloud.githubusercontent.com/assets/900690/22335376/c8359a44-e3de-11e6-940e-4dbbb0707361.png)

![image](https://cloud.githubusercontent.com/assets/900690/22335437/0dfe6dee-e3df-11e6-90df-250745071b4c.png)

**Comment by sandy081** [comment]
@joaomoreno Applied your idea of grey with opacity. Following are screenshots for some themes, most of them looks good to me. If not I can tweak the colours more. 

Note: This is only when for hovering on section

![image](https://cloud.githubusercontent.com/assets/10746682/22823193/d22b6786-ef82-11e6-9834-4ecb04c48f64.png)

![image](https://cloud.githubusercontent.com/assets/10746682/22823213/e33c0b48-ef82-11e6-965a-b18f0df9997c.png)

![image](https://cloud.githubusercontent.com/assets/10746682/22823218/edbd360a-ef82-11e6-9861-0ab488e73749.png)

![image](https://cloud.githubusercontent.com/assets/10746682/22823237/04f89076-ef83-11e6-8ebb-8706a387ce68.png)

![image](https://cloud.githubusercontent.com/assets/10746682/22823249/0e1e1608-ef83-11e6-9adf-9d2c77c38cc9.png)

![image](https://cloud.githubusercontent.com/assets/10746682/22823263/1942f8d2-ef83-11e6-9ae7-ab06f80e8b7b.png)

![image](https://cloud.githubusercontent.com/assets/10746682/22823275/21eb5510-ef83-11e6-8114-a186c08daccb.png)

![image](https://cloud.githubusercontent.com/assets/10746682/22823279/2a3080c4-ef83-11e6-9964-0a6cfe16e319.png)

![image](https://cloud.githubusercontent.com/assets/10746682/22823283/32e24e32-ef83-11e6-82c2-a1bee8bf1c59.png)
