### ISSUE TITLE
Feature Request: Select while jumping to matching bracket.

### ISSUE THREAD

**Issue by krryan** [Microsoft/vscode#19513]
I would like some alternative version of the `Ctrl`+`Shift`+`\` command, which jumps to the matching bracket, that also selects while jumping. The obvious modifier key to use for that distinction would be `Shift`, which sadly is already used by the original function, so I suppose it would have to be `Ctrl`+`Shift`+`Alt`+`\` or something.

**Comment by mousetraps** [comment]
@krryan cool idea! Looks like this is already being tracked at https://github.com/Microsoft/vscode/issues/18322, so I'm going to go ahead and close this issue. Let me know if you meant something different, and we'll be happy to reopen. Happy coding!

**Comment by AbelaroJiang** [comment]
cool idea! Looking forward to include.
