### ISSUE TITLE
cs50 submit and check link doesn't work????

### ISSUE THREAD

**Issue by 6r0se6** [microsoft/vscode#195115]
I put the cs50 file checker thing and submit link but nothing works,why?

**Comment by gjsjohnmurray** [comment]
Please use the course support channel for assistance.

**Comment by 6r0se6** [comment]
> Please use the course support channel for assistance.

oh I didn't think of that, thank you ^^

**Comment by gjsjohnmurray** [comment]
Please close your issue here.
