### ISSUE TITLE
Feature release 1.83 pin tab

### ISSUE THREAD

**Issue by Eimantas23** [microsoft/vscode#195128]
Type: <b>Bug</b>

"When activated, pinned tabs are displayed on a separate row above the other tabs." 
They don't get a separate row above the other tabs. 
When pinning tab it just jumps to the start of same row.

VS Code version: Code 1.83.0 (e7e037083ff4455cf320e344325dacb480062c3c, 2023-10-03T16:12:16.321Z)
OS version: Windows_NT x64 10.0.19045
Modes:

**Comment by gjsjohnmurray** [comment]
Sounds like you haven't set your `workbench.editor.pinnedTabsOnSeparateRow` setting.

**Comment by Eimantas23** [comment]
Yes, you are right, thanks.
