### ISSUE TITLE
C# IntelliSense doesn't work

### ISSUE THREAD

**Issue by praeclarum** [microsoft/vscode#195104]
Type: <b>Bug</b>

I used to get C# intellisense for my projects, but it no longer appears.

VS Code version: Code 1.83.0 (e7e037083ff4455cf320e344325dacb480062c3c, 2023-10-03T16:13:15.449Z)
OS version: Darwin x64 23.0.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) W-2150B CPU @ 3.00GHz (20 x 3000)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|1, 2, 2|
|Memory (System)|32.00GB (12.29GB free)|
|Process Argv|. --crash-reporter-id 37e095d3-0123-4076-a4a2-4b2151a4e5e9|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (76)</summary>

Extension|Author (truncated)|Version
---|---|---
racket|Dmy|1.2.0
alexa-skills-kit-toolkit|ask|2.15.0
spellright|ban|3.0.118
yacc|car|1.3.1
gltf-vscode|ces|2.4.0
doxdocgen|csc|1.4.0
binary-plist|dni|0.11.3
prettier-vscode|esb|10.1.0
esp-idf-extension|esp|1.6.4
vs-code-xml-format|fab|0.1.5
copilot|Git|1.123.471
copilot-chat|Git|0.8.0
vscode-github-actions|git|0.26.2
vscode-pull-request-github|Git|0.74.0
vscode-graphql|Gra|0.8.19
vscode-graphql-execution|Gra|0.2.4
vscode-graphql-syntax|Gra|1.2.2
vscode-power-mode|hoo|3.0.2
ilspy-vscode|ics|0.16.1
Ionide-fsharp|Ion|7.13.0
better-cpp-syntax|jef|1.17.2
copy-markdown-as-html|jer|1.1.0
cmake-language-support-vscode|jos|0.0.9
vscode-cudacpp|kri|0.1.1
bison|lun|0.1.0
ninja-syntax|mel|1.0.0
fsharp-fsl-fsy|mnx|0.0.1
vscode-docker|ms-|1.26.1
csharp|ms-|2.5.30
vscode-dotnet-runtime|ms-|1.8.0
black-formatter|ms-|2023.5.12771008
isort|ms-|2023.10.1
python|ms-|2023.18.0
vscode-pylance|ms-|2023.10.10
jupyter|ms-|2023.9.1102792234
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.17
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-slideshow|ms-|0.1.5
remote-containers|ms-|0.315.1
remote-ssh|ms-|0.106.5
remote-ssh-edit|ms-|0.86.0
remote-wsl|ms-|0.81.7
cmake-tools|ms-|1.15.31
cpptools|ms-|1.17.5
cpptools-extension-pack|ms-|1.3.0
hexeditor|ms-|1.9.12
live-server|ms-|0.4.11
mono-debug|ms-|0.16.3
remote-explorer|ms-|0.4.1
vscode-serial-monitor|ms-|0.10.0
vsliveshare|ms-|1.0.5883
ufmt|omn|2023.4.3
vscode-jest|Ort|5.2.3
vscode-nuget-gallery|pat|0.0.24
wgsl|Pol|0.1.16
java|red|1.23.0
llvm|RRe|0.1.1
partial-diff|ryu|1.4.3
modelica|Sim|0.0.4
fish-vscode|sky|0.2.1
shader|sle|1.1.5
urdf|smi|0.3.0
cmake|twx|0.0.17
nisaba|UCL|1.4.1
intellicode-api-usage-examples|Vis|0.2.8
vscodeintellicode|Vis|1.2.30
vscode-arduino|vsc|0.6.0
vscode-java-debug|vsc|0.54.0
vscode-java-dependency|vsc|0.23.1
vscode-java-pack|vsc|0.25.14
vscode-java-test|vsc|0.40.0
vscode-maven|vsc|0.42.0
vscode-cil-complete|wk-|0.0.5
material-theme|zhu|3.16.0
vscode-proto3|zxh|0.5.5

(3 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscoreces:30445986
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
py29gd2263:30792226
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
3biah626:30602489
89544117:30613380
2i9eh265:30646982
showlangstatbar:30737416
03d35959:30757346
pythonfmttext:30731395
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
pythonnosmt12:30797651
pythonidxptcf:30805731
pythonnoceb:30805159
copilotsettingc:30839828
synctok:30821570
dsvsc013:30795093
dsvsc014:30804076
diffeditorv2:30821572
pythonmpsinfo:30842941
dsvsc015:30845448

```

</details>

**Comment by roblourens** [comment]
Please check your configuration or the C# docs, or file an issue on the C# extension repo
