### ISSUE TITLE
Navigate among the files while typing in the Explorer panel

### ISSUE THREAD

**Issue by DanZeuss** [Microsoft/vscode#19516]
- VSCode Version:1.8.1
- OS Version: Microsoft Windows [Version 10.0.14393]

Steps to Reproduce:
In Visual Studio, we could navigate between the files while typing to search the file or folder that we want to reach.

For example, let's suppose that we have the following structure on Explorer panel
- resources
- config
  + acl.php
  + app.php
  +benchmark.php
- config.testing
- database
- routes

If I start to type "c", "o", "n" with the focus inside the **Explorer bar**, so, the panel will set the focus to the **config** folder. Once inside the **config** folder and start to type "a", "p"... it will set the focus in the **app.php file**.

If the **Explorer** panel has the focus in the **resource** folder and we start to type "b", "e","n", the **Explorer** panel will set the focus to the **benchmark.php** or other file that starts with the chars "ben".

**Comment by mousetraps** [comment]
@DanZeuss nice idea! It sounds like this is already tracked by #10026 and #10839, so I'm going to go ahead and close this, and suggest following those issues for updates. Happy to reopen if you think otherwise. Happy coding!

**Comment by DanZeuss** [comment]
Thank you so much @mousetraps
