### ISSUE TITLE
Monaco>DiffEditor>inline view>clicking + dragging over original lines will select text from new, even if using scrollbar

### ISSUE THREAD

**Issue by tyrielv** [Microsoft/vscode#19525]
- Monaco-editor Version: 0.8.0
- OS Version: Windows 10 Insider preview

Steps to Reproduce:

1. Create a diff-editor, inline view, readonly, where a section is present in the original/left but deleted in the modified/right. (The [demo page](https://microsoft.github.io/monaco-editor/index.html) also shows this behavior.)
2. Scroll to the deleted section.
3. Click and drag on some of the red-highlighted text. **The editor will begin selecting before/after deleted section. This is expected and occurs in VSCode as well.**.
4. Scroll to a large deleted section, such that the red highlight of a deleted line is visible through the semi-transparent scrollbar.
5. Attempt to scroll by clicking and dragging on the scrollbar. **The editor will still attempt to highlight before/after the deleted text, which can make scrolling difficult if the deleted section is large because the editor will try to jump to the highlighted area**. This does not repro in VSCode, but does in recent versions of IE, Edge, and Chrome.

**Comment by tyrielv** [comment]
Update: Turns out I was using an old version of VSCode when trying to repro.

Latest version of VS code has same behavior of steps 1-3 (selects before/after), suggesting that is by design, but does not have the behavior for steps 4-5 (clicking on scrollbar works as expected).

**Comment by alexandrudima** [comment]
This has been fixed in the meantime.
