### ISSUE TITLE
Filter installed extensions

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#19526]
I want to search within my installed extensions. Is there a way to do this already?

- Have many extensions installed
- Type search query
- It searches the whole marketplace with no easy option to only see installed extensions that match

Searching like `@installed format` would be great.

**Comment by joaomoreno** [comment]
That's a pretty cool idea.

The alternative is just to break the current behaviour and search locally only when typing... which I'm not a big fan of.

**Comment by sandy081** [comment]
I think in majority of cases users search extensions in market place so current behaviour makes sense. Not sure if it is good idea to break it.

If users want to filter in installed, just like in other categories, they can follow the same pattern `@category filter`.
