### ISSUE TITLE
It takes 50 seconds to run my code 

### ISSUE THREAD

**Issue by VedangWajge** [microsoft/vscode#195242]
Type: <b>Performance Issue</b>

It happens everytime,

VS Code version: Code 1.83.0 (e7e037083ff4455cf320e344325dacb480062c3c, 2023-10-03T16:12:16.321Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|12th Gen Intel(R) Core(TM) i5-12400 (12 x 2496)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.75GB (8.41GB free)|
|Process Argv|--crash-reporter-id 4c016f03-228a-4daf-96c1-b364342d2f90|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	   125	 15452	code main
    0	    86	  3052	fileWatcher [1]
    0	   178	  3068	window [1] (main.c - CP - Visual Studio Code)
    0	   178	  3832	   gpu-process
    0	    40	  7084	   utility-network-service
    0	    28	 13584	   crashpad-handler
    0	   169	 15212	window [2] (Welcome - Visual Studio Code)
    0	    79	 15308	ptyHost
    0	    91	 15688	shared-process
    0	   118	 15748	extensionHost [2]
    0	    85	 16844	fileWatcher [2]
    0	    97	 17160	window [3] (Issue Reporter)
    0	   155	 17276	extensionHost [1]
    0	    33	 17392	     c:\Users\User\.vscode\extensions\ms-vscode.cpptools-1.17.5-win32-x64\bin\cpptools.exe
    0	     4	  6832	       "c:\Users\User\.vscode\extensions\ms-vscode.cpptools-1.17.5-win32-x64\bin\cpptools.exe"
    0	    15	  4796	         c:\Users\User\.vscode\extensions\ms-vscode.cpptools-1.17.5-win32-x64/bin/cpptools-srv.exe 17392 {83D05369-2D92-4928-A3AF-2EAB689011FE}
    0	    11	  5264	           C:\Windows\system32\conhost.exe 0x4
    0	    11	  7380	       C:\Windows\system32\conhost.exe 0x4
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (main.c - CP - Visual Studio Code)
|    Folder (CP): 126 files
|      File types: exe(19) obj(19) c(18) json(9) txt(5) cmake(5) xml(4)
|                  ninja(2) bin(2) cpp(2)
|      Conf files: cmake(5) tasks.json(2);
```

</details>
<details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
code-runner|for|0.12.1
ctrl-semicolon|Gfo|0.1.0
cmake-tools|ms-|1.15.31
cpptools|ms-|1.17.5
cpptools-extension-pack|ms-|1.3.0
easyzoom|Nab|0.1.0
LiveServer|rit|5.7.9
cmake|twx|0.0.17
vscode-lldb|vad|1.10.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263:30335439
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
py29gd2263cf:30856253
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
282f8724:30602487
f6dab269:30613381
showlangstatbar:30737416
03d35959:30757346
pythonfmttext:30731395
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
pythonnosmt12:30797651
pythonidxpt:30805730
pythonnoceb:30805159
copilotsettingt:30839829
dsvsc013:30795093
dsvsc014:30804076
diffeditorv1:30821571
dsvsc015:30845448

```

</details>

**Comment by tamuratak** [comment]
Do you have McAfee antivirus installed? See https://github.com/microsoft/vscode/issues/178962
