### ISSUE TITLE
Synchronizing `launch.json` via Settings Sync

### ISSUE THREAD

**Issue by shaperilio** [microsoft/vscode#195285]
Revisiting #122678.

I work on the same repo on multiple machines. It's a python project with a virtual environment so it's easy to use identical `launch.json` files across all these machines.

I feel like pushing this to the repo is not sustainable. I don't want to end up with 100 configurations because there's 30 people on the team.

Settings sync seems to be the best fit. Workspace settings are synched across machines. Couldn't the `launch.json` file be synched on a per-workspace basis in the same way?

**Comment by roblourens** [comment]
We already support adding launch configs via settings

```
"launch": {
    "configurations": [
...
    ]
}
```

**Comment by shaperilio** [comment]
lol what? you mean I can paste my `launch.json` in there and stop using `launch.json`?
