### ISSUE TITLE
Match the design of aria label with theme

### ISSUE THREAD

**Issue by RichardLuo0** [microsoft/vscode#195243]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.83.0
- OS Version: Windows 11

Steps to Reproduce:

1. move your mouse over some button on bottom panel (or over file)

![image](https://github.com/microsoft/vscode/assets/22096448/d7db63b2-427e-419e-b41d-e0cdfc74b462)
![image](https://github.com/microsoft/vscode/assets/22096448/aa11ec51-4e3c-405a-928f-d0ad00731cb5)
This is completely different from other UI elements (should have round corner and grey border). It does not follow the theme (keep dark UI in light theme)
I hope they all follow the design below:
![image](https://github.com/microsoft/vscode/assets/22096448/370d9340-b78c-45dd-8b34-cf4cd5c22871)

**Comment by daviddossett** [comment]
This may be a situation where we use both native and custom tooltips. @meganrogge would you have any insight here?

**Comment by meganrogge** [comment]
While I see the inconsistency here, I don't think it's an accessibility issue as the contrast is fine for both.

**Comment by connor4312** [comment]
Seems like these are now using native hovers
