### ISSUE TITLE
output issue

### ISSUE THREAD

**Issue by ppphhhuuurrr** [microsoft/vscode#195277]
![Screenshot 2023-10-10 224642](https://github.com/microsoft/vscode/assets/131389057/582b592a-35db-49f4-a9be-a9dcc02e813b)
Type: <b>Bug</b>

Output Terminal Doesn't take input.
My python program need user to enter his/her name. But output terminal doesn't take any input from the user 

VS Code version: Code 1.83.0 (e7e037083ff4455cf320e344325dacb480062c3c, 2023-10-03T16:12:16.321Z)
OS version: Windows_NT x64 10.0.22621
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 5600U with Radeon Graphics          (12 x 2296)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|7.31GB (1.41GB free)|
|Process Argv|--crash-reporter-id 34b862af-4cc7-4054-b87c-ad0f7fb0eca2|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (45)</summary>

Extension|Author (truncated)|Version
---|---|---
nodejs-bundle|1Yi|1.0.0
svelte-bundle|1Yi|1.0.0
codesnap|adp|1.3.4
svelte-intellisense|ard|0.7.1
bracket-pair-toggler|dzh|0.0.3
gitlens|eam|14.3.0
prettier-vscode|esb|10.1.0
vscode-svelte-snippets|fiv|0.5.0
code-runner|for|0.12.1
copilot-chat|Git|0.8.0
vscode-pull-request-github|Git|0.74.0
llama2-gpt-codepilot|Gra|0.0.3
svg|joc|1.5.3
vscode-docker|ms-|1.26.1
csharp|ms-|2.5.30
vscode-dotnet-runtime|ms-|1.8.0
black-formatter|ms-|2023.5.12831009
isort|ms-|2023.10.1
python|ms-|2023.18.0
vscode-pylance|ms-|2023.10.10
jupyter|ms-|2023.9.1102792234
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.17
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-slideshow|ms-|0.1.5
cmake-tools|ms-|1.15.31
cpptools|ms-|1.17.5
cpptools-extension-pack|ms-|1.3.0
live-server|ms-|0.4.11
indent-rainbow|ode|8.3.1
vscode-css-peek|pra|4.4.1
java|red|1.23.0
LiveServer|rit|5.7.9
vs-code-prettier-eslint|rve|5.1.0
vscode-standard|sta|2.1.3
svelte-vscode|sve|107.12.0
cmake|twx|0.0.17
vscodeintellicode|Vis|1.2.30
vscode-java-debug|vsc|0.54.0
vscode-java-dependency|vsc|0.23.1
vscode-java-pack|vsc|0.25.14
vscode-java-test|vsc|0.40.0
vscode-maven|vsc|0.42.0
vscode-icons|vsc|12.5.0
vscode-surround|yat|1.5.0

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263cf:30335440
vscoreces:30445986
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
py29gd2263cf:30856253
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
2e4cg342:30602488
f6dab269:30613381
showlangstatbar:30737416
03d35959:30757346
pythonfmttext:30731395
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
pythonnosmt12:30797651
pythonidxptcf:30805731
pythonnoceb:30805159
copilotsettingt:30839829
asynctok:30821568
dsvsc013:30795093
dsvsc014:30804076
diffeditorv2:30821572
pythonmpsinfo:30842941
dsvsc015:30845448

```

</details>

**Comment by benibenj** [comment]
What about the terminal? Generally, the output windows is only for displaying the output of different processes. How exactly are you executing the code? If you're utilizing the debugger or running the Python script through the terminal, you should be able to view all of your program's output and provide input directly within the terminal.

**Comment by meganrogge** [comment]
yeah the output is readonly by design

**Comment by ppphhhuuurrr** [comment]
> What about the terminal? Generally, the output windows is only for displaying the output of different processes. How exactly are you executing the code? If you're utilizing the debugger or running the Python script through the terminal, you should be able to view all of your program's output and provide input directly within the terminal.

> I can execute code in terminal panel but it doesn't work in output panel
