### ISSUE TITLE
[Accessibility] Allow users to configure the Accessible View transparent

### ISSUE THREAD

**Issue by jooyoungseo** [microsoft/vscode#195288]
Type: <b>Feature Request</b>

CC @meganrogge 

When presenting my screen or demoing my live-coding to sighted individuals, I often want to make the Accessible View invisible to my audience. This is particularly distracting for sighted audience when I use terminal and create a side-by-side visualizations. I just want to open the Accessible View for my own and make it transparent visually.

However, this does not mean that we have to make it transparent by default. I suggest adding a user configuration for them to choose between visible (default) and invisible mode.

VS Code version: Code - Insiders 1.84.0-insider (eb4f3c149f34d82b9763a08230907cf79e7fc103, 2023-10-10T07:26:46.161Z)
OS version: Windows_NT x64 10.0.22621
Modes:

**Comment by meganrogge** [comment]
I just realized that we might want to apply this to all of the accessible views? Not just the terminal's?

**Comment by jooyoungseo** [comment]
Yes, I agree with that.
