### ISSUE TITLE
Multiple process debug dropdown doesn't show up in widget consistently

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#19524]
- Start (for example) "Launch VS Code" config
- Start "Unit test" config
- Process picker dropdown doesn't show up

If I click "stop", then the first config is killed, and the second keeps running, and the process picker in the widget shows up at this point.

Or if I launch a third one, it shows up.

Or if I hit a breakpoint, it shows up.

**Comment by roblourens** [comment]
I'm talking about this, to be clear

![image](https://cloud.githubusercontent.com/assets/323878/22382251/b7e02268-e479-11e6-8094-401767333ddd.png)

**Comment by roblourens** [comment]
Both configs show up in the callstack correctly

**Comment by roblourens** [comment]
Jan candidate?

**Comment by isidorn** [comment]
Dup of #19506
Not a candidate imho
