### ISSUE TITLE
View commands and View Container menu missing after extension installation

### ISSUE THREAD

**Issue by vaclavHala** [microsoft/vscode#195246]
Type: <b>Bug</b>

After Installing extension from VSIX view container is missing the `...` menu for showing views in the group. Also commands for hiding the views and other auto-generated commands targetting views contributed by the extension are missing. 

Here is sample `package.json` which creates extension demonstrating this problem
```json
{
  "name": "initial-commands",
  "description": "",
  "version": "0.0.1",
  "engines": {
    "vscode": "^1.50.0"
  },
  "categories": [
    "Other"
  ],
  "contributes": {
    "viewsContainers": {
      "activitybar": [
        {
          "id": "mycontainer",
          "title": "My Container",
          "icon": "container.svg"
        }
      ]
    },
    "views": {
      "mycontainer": [
        {
          "id": "myview1",
          "name": "My View 1"
        },
        {
          "id": "myview2",
          "name": "My View 2"
        }
      ]
    },
    "viewsWelcome": [
      {
        "view": "myview1",
        "contents": "[Close View 1](command:myview1.removeView)"
      },
      {
        "view": "myview2",
        "contents": "[Close View 2](command:myview2.removeView)"
      }
    ]
  },
  "scripts": {
    "package": "vsce package --allow-missing-repository"
  },
  "devDependencies": {
    "@types/node": "20.2.5",
    "@types/vscode": "^1.50.0",
    "@vscode/vsce": "^2.21.1",
    "typescript": "^5.1.3"
  }
}

```
`container.svg`
```
<svg width="24" height="24" xmlns="http://www.w3.org/2000/svg">
<rect width="24" height="24"  fill="red" />
</svg>
```

![missing_commands](https://github.com/microsoft/vscode/assets/12083193/d7b16dc8-f796-435d-9498-2a25dacf39eb)

Notice the missing `...` menu, also the command buttons do not work (see error in console). After restarting vscode (or simply running `Developer: Reload Window`) both of these problems disappear. 

This is bad user experience right after install and it is especially causing us pain when testing our extension.

In latest Insiders this bug does not appear

VS Code version: Code 1.82.2 (abd2f3db4bdb28f9e95536dfa84d8479f1eb312d, 2023-09-14T05:51:20.981Z)
OS version: Linux x64 4.19.0-18-amd64
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 2700 Eight-Core Processor (16 x 1362)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|1, 1, 1|
|Memory (System)|31.43GB (14.48GB free)|
|Process Argv|--crash-reporter-id b7de6dff-a380-43b3-8eb5-e5e11c79fe00|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|xfce|
|XDG_CURRENT_DESKTOP|XFCE|
|XDG_SESSION_DESKTOP|xfce|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
initial-commands|und|0.0.1

</details>

**Comment by sandy081** [comment]
> In latest Insiders this bug does not appear

Thanks for confirming. This could be fixed in insiders then. Hence closing this.
You will get the fix in next release.
