### ISSUE TITLE
Task not finishing after window reload

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#195265]
I reloaded the window some time ago and saw just now there are spinners:

![Image](https://github.com/microsoft/vscode/assets/2193314/329df922-c533-43f0-aaae-c0b5b9d45df0)

Here are the logs shownig exactly what got printed
```
2023-10-10 08:52:07.452 [debug] [1b92721] parsing data "[?25l[Hptions'. Did you mean 'FileSystemWatcher'?  
[[90m08:00:39[m] Finished [32mcompilation [mwith 1 errors after [35m88 ms[K[m
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K[4;1H[?25h"
```

```
2023-10-10 08:52:07.452 [debug] [1b92721] parsing data "[?25l[Hefined'.[K
[[90m08:00:21[m] Finished [32mcompilation [34mextensions [mwith 2 errors after [35m27 ms[K[m
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K[4;1H[?25h"
```

Closing the terminals and re-running the build tasks works:

![Image](https://github.com/microsoft/vscode/assets/2193314/7d183c36-2c87-4be6-8a78-2feed63711dc)

Is it because the top ones are missing the starting message?

**Comment by meganrogge** [comment]
> Is it because the top ones are missing the starting message?

Yep, exactly. This will spin forever if `tryBegin` doesn't find a match.

https://github.com/microsoft/vscode/blob/e536224122243a1e1ee8c95fa510486516116641/src/vs/workbench/contrib/tasks/common/problemCollectors.ts#L497-L502

**Comment by meganrogge** [comment]
likely fixed with https://github.com/microsoft/vscode/pull/197381
