### ISSUE TITLE
GitHub Authentication: Sign in failed: Error: No auth flow succeeded

### ISSUE THREAD

**Issue by axosoft-ramint** [microsoft/vscode#195286]
- VS Code Version: 1.83.0
- OS Version: Windows 10 64-bit

The GitHub Auth extension is running into an issue with CORS, which results in an error when authenticating.

Devtools yields the following logs:

```
Access to fetch at 'https://github.com/login/oauth/access_token' from origin 'https://v--15coekdin4scjauo9v5fvhbspk3mi3ftteagqn81g3pkn9368ma8.vscode-cdn.net' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
webWorkerExtensionHostIframe.html:1 Access to fetch at 'https://github.com/login/oauth/access_token' from origin 'https://v--15coekdin4scjauo9v5fvhbspk3mi3ftteagqn81g3pkn9368ma8.vscode-cdn.net' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
webWorkerExtensionHostIframe.html:1 Access to fetch at 'https://github.com/login/oauth/access_token' from origin 'https://v--15coekdin4scjauo9v5fvhbspk3mi3ftteagqn81g3pkn9368ma8.vscode-cdn.net' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
Sign in failed: Error: No auth flow succeeded.
```

Requirements:
1. Must be authing with GitHub authentication **without having a stored secret** i.e. without a previously successful auth (can reset this with `Developer: Reset User Data` from the Command Palette).
2. Have an extension loaded which uses GitHub Auth (I used GitLens).

Steps to Reproduce:
1. Open github.dev to a repo, or whatever action triggers the GitHub auth flow for an extension.
2. See `The extension ____ wants to sign in using GitHub` modal. click `Allow`.
3. See error notification showing: `Sign in failed: Error: No auth flow succeeded.`

**Update:** The auth seems to work fine on vscode.dev; only able to reproduce the issue in github.dev.

![image](https://github.com/microsoft/vscode/assets/67011668/a7260305-78a9-4906-afd9-2b301de7e5dc)

**Comment by axosoft-ramint** [comment]
**Follow-up:** In case it is helpful/relevant, I am able to get around the issue by doing the following:

1. Hit `Cancel` on the initial auth prompt.

![image](https://github.com/microsoft/vscode/assets/67011668/4dab95ca-761f-4dd4-af24-074da7e0ca7f)

2. Grant access to the extension from the sidebar instead.

![image](https://github.com/microsoft/vscode/assets/67011668/7dd3b41e-2197-47b9-866d-3f2b7874bcfc)

3. Hit `Allow` on the new auth prompt.

![image](https://github.com/microsoft/vscode/assets/67011668/89fc9469-8716-4c19-8a03-3fbfd2d2f274)

4. Refresh the page.

**Comment by TylerLeonhardt** [comment]
@axosoft-ramint @eamodio what's the API call you make to `getSession`?

**Comment by TylerLeonhardt** [comment]
I have a potential fix for this... though, I'm a little suspicious of it. Can you try with github.dev targeting Insiders tomorrow?

**Comment by eamodio** [comment]
We call `getSession` in a few ways depending on the scenario. In this case because we are trying to work with a "virtual" GitHub folder/repo, we need the authentication to work at all, so we use `createIfNone`.

**Comment by axosoft-ramint** [comment]
Verifying that the issue no longer occurs for me when using the Insiders version. Thank you! 👍🏼
