### ISSUE TITLE
Crash in Windows VM after search

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#19521]
From #17718, reported by @isidorn 

> win 10, vscode insiders latest
> 
> I also get to 90% after a minute of searing on my root drive, after that some results pop up but progress remains at around 90% and vscode becomes > unresponsive 
> 8 minutes later vscode is not unresponsive but very slow and progress still around 90%
> After 10 minutes - vscode crashes
> 
> ![screen shot 2017-01-26 at 16 54 19](https://cloud.githubusercontent.com/assets/1926584/22338618/1bfabeb2-e3e8-11e6-8075-42f6b99635fd.png)
> 
> A bunch of errors in console
> ```
> ipc.cp.ts:152 [IPC Library: Search] Uncaught Exception:  SyntaxError: Unexpected token  in JSON at position 0(anonymous function) @ ipc.cp.ts:152e.invoke > @ callbackList.ts:63e.fire @ event.ts:118r @ event.ts:12emitTwo @ events.js:106emit @ events.js:191process.nextTick @ > internal/child_process.js:744_combinedTickCallback @ internal/process/next_tick.js:67_tickCallback @ internal/process/next_tick.js:98
> ipc.cp.ts:152 [IPC Library: Search] SyntaxError: Unexpected token  in JSON at position 0
>     at Pipe.channel.onread (internal/child_process.js:448:28)
> ```

> I can repro it easily on my vm which has 2gb ram.
> No cpu spikes, I guess the vm just runs out of memory since it has a 2gb limit

**Comment by isidorn** [comment]
I correct myself - I can not crash it every time! But freezes I repro constantly

**Comment by roblourens** [comment]
@isidorn Does this still repro for you? I never got another report.

**Comment by isidorn** [comment]
@roblourens yes I can still get vscode to freeze after searching for 'isidor' in my root folder.

**Comment by roblourens** [comment]
I'm going to push it out again since it's not freezing for me, and nobody has reported it, and I still hold hope that we will replace the search code with a third party solution.

**Comment by isidorn** [comment]
@roblourens sounds good to me

**Comment by roblourens** [comment]
Closing since ripgrep search is enabled by default, and hopefully this doesn't happen now.

**Comment by michelkaporin** [comment]
Does not happen with default ripgrep search, however still happens with the old search using `"search.useRipgrep": false` setting. In my case it stops at around 90% progress but does not crash (running Windows **not** in VM with 8GB RAM machine).

I am putting `verified` because we moved to ripgrep and it's working there.
