### ISSUE TITLE
[themes] Settings editor: input box container background doesn't look good in some themes

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode#19520]
Testing #17103:

![image](https://cloud.githubusercontent.com/assets/6461412/22379014/e03fa18c-e4b7-11e6-9a64-9ef12b6316a8.png)

Either we need a new theme setting or it can be done with opacity.

**Comment by sandy081** [comment]
I think this applies for all input boxes we have in workbench. Since we are theming our workbench now, we should be handling this too.

@bpasero @aeschli Assigning these to you as you are working on theming support for workbench.

**Comment by bpasero** [comment]
I think for February we should play with opacity.

**Comment by bpasero** [comment]
#3112
