### ISSUE TITLE
Extensions: Searching with extension name after @{group} filter

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#19527]
Cannot search by extension name along with a group filter `@disabled` or @`outdated`

- Disable a couple extensions
- In the extensions search box, enter `@disabled foo` replacing `foo` with a word in one extension
- enter
- All extensions still show

This works for other filters, for example `@recommended npm`

**Comment by sandy081** [comment]
@roblourens You reported that `@disabled foo` is not working but in the last line you said it works for all except `@recommended npm`. After trying out, I see last line is correct. So updated summary and description accordingly. If not, please report it with what is not working. Thanks.

**Comment by sandy081** [comment]
@roblourens Ignore my previous comment. I think what you reported initially makes sense and reverted summary and description
