### ISSUE TITLE
Why are unordered lists not rendered in the markdown preview?

### ISSUE THREAD

**Issue by dscottboggs** [microsoft/vscode#195237]
When you write a checkbox, with this syntax in a .md file with the "Preview to the Side" open,

```
 - [ ] list item
 - [x] in a list
```

I would expect the preview to appear like this:

 - [ ] list item
 - [x] in a list

But instead it looks like this

 • \[ \] list item
 • \[x\] in a list

**Comment by mjbvz** [comment]
Checkboxes are not standard markdown. Did you try installing https://marketplace.visualstudio.com/items?itemName=bierner.markdown-checkbox

**Comment by dscottboggs** [comment]
I would have thought it would make sense for things to be consistent across products (i.e. Github and VSCode) but :shrug: no skin off my back, your recommended extension is a fine solution, thanks.
