### ISSUE TITLE
Top activity bar can sometimes intermix with view title actions

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#195262]
In certain sizes the activity bar can intermix with the title actions. Two things:
* Can we have some minimal width between them, just so they do not look like one giant toolbar?
* Are they vertically aligned? Looks to me like the explorer actions are a bit higher. Might be just optical illusion due to the icon design

![Screenshot 2023-10-10 at 17 03 27](https://github.com/microsoft/vscode/assets/1926584/f798b314-1526-41b2-8d75-a85974055737)

**Comment by sandy081** [comment]
I just brought this up in todays UX Sync call, and one idea is to have a separator? Not sure if we have better ideas here. Having some fixed space is also a good idea.

Can you please try today's insiders? I have changed the activity bar icon size and spacing a bit - may be this helps or worsens :)

**Comment by isidorn** [comment]
I just got the latest update and I do not really notice a difference :)

For separator - how would you know when to render it?

**Comment by sandy081** [comment]
When there are actions on the right

**Comment by isidorn** [comment]
Might look weird if they are far apart. So not sure, I would have to see it to comment more :)

**Comment by T-256** [comment]
related https://github.com/microsoft/vscode/issues/195903
