### ISSUE TITLE
Dialogs in aux window show in main window and allow the aux window to continue to be used

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#195298]
Repro:

1. Open file
2. Create aux window
3. Edit file (no auto save)
4. Try close the editor

![Image](https://github.com/microsoft/vscode/assets/2193314/16240b3f-c11b-4b75-8563-c4b1f4523d07)

**Comment by bpasero** [comment]
It is somewhat easy to make sure to open the dialog in the window that currently has focus and I implemented that in https://github.com/microsoft/vscode/pull/195326/commits/895a9ff13055ddb528d0a4d34f36b6f6e3059b31 for custom dialogs (leveraging `ILayoutService.activeContainer`) and https://github.com/microsoft/vscode/pull/195326/commits/0c52fb443b1fbcc81d615f3715fc0ca322f0d269 for native dialogs but the real challenge is that the other windows remain functional while dialogs show up: so far, as a user you had to react on the dialog and could not use anything else in the window. Now, all other windows remain functional and worse you cannot bring up another dialog.

A pragmatic fix would be to somehow block all opened windows when a single dialog shows in one dialog, but its a bit ugly tbh. Thoughts?

**Comment by bpasero** [comment]
Closing for verification that when you close an editor in the aux window, you get a dialog in the aux window. Please test with default native dialogs as well as when configuring `window.dialogStyle: custom`.
