### ISSUE TITLE
vscode empty me unsave file and can't undo

### ISSUE THREAD

**Issue by brucexin** [microsoft/vscode#195211]
Type: <b>Bug</b>

Today morning, I changed some line and ready debug, a html file. But when I click 'Run and Debug' button, it is no response. I try again, still no response, but I can change to other file tab, it means VSCode UI not frozen. It is very strange and never happened before, I have no idea but try restart VSCode. When I click 'X' button, VS Code doesn't exit quickly but wait seconds then it exited. 
I opened 3 VSCode window before, so I change to other VS Code window try to reopen the project be exited, I select 'File' -> 'New WIndow', but the new window tell me has new updates, I click 'update now', all VSCode window exit and reopen, when I open my project then found my file become empty, file size become 0kb, no 'undo' buffer exist and I'm very sure I hadn't do 'delete' content action !!
My code lost and it can't be restore, only get old version from repository. I think it is a very badly issue!      

VS Code version: Code 1.83.0 (e7e037083ff4455cf320e344325dacb480062c3c, 2023-10-03T16:12:16.321Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Remote OS version: Linux x64 5.10.102.1-microsoft-standard-WSL2
Remote OS version: Linux x64 5.10.102.1-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz (8 x 2419)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.80GB (1.96GB free)|
|Process Argv|--crash-reporter-id 810391e7-23ef-47fe-9266-950a5e3850bd|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-22.04|
|OS|Linux x64 5.10.102.1-microsoft-standard-WSL2|
|CPUs|11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz (8 x 2419)|
|Memory (System)|7.66GB (4.60GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-22.04|
|OS|Linux x64 5.10.102.1-microsoft-standard-WSL2|
|CPUs|11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz (8 x 2419)|
|Memory (System)|7.66GB (4.60GB free)|
|VM|0%|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
copilot|Git|1.123.477
copilot-chat|Git|0.8.0
go|gol|0.39.1
vscode-docker|ms-|1.26.1
remote-containers|ms-|0.315.1
remote-wsl|ms-|0.81.7
cmake-tools|ms-|1.15.31
cpptools|ms-|1.17.5
cpptools-extension-pack|ms-|1.3.0
cmake|twx|0.0.17

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
py29gd2263cf:30856253
vscaat:30438848
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
2e4cg342:30602488
89544117:30613380
2i9eh265:30646982
showlangstatbar:30737416
962ge761:30841074
03d35959:30757346
pythonfmttext:30731395
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
pythonnosmt12:30797651
pythonidxpt:30805730
pythonnoceb:30805159
copilotsettingc:30839828
dsvsc013:30795093
dsvsc014:30804076
diffeditorv2:30821572
pythonmhint1:30842940
dsvsc015:30845448

```

</details>

**Comment by roblourens** [comment]
Sorry for the trouble. Was this a saved file or an untitled file? Is this still happening?
