### ISSUE TITLE
Long strings of random letters and numbers (again)

### ISSUE THREAD

**Issue by krishunt** [microsoft/vscode#195266]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.83.0
- OS Version: macOS 13.5.2

Steps to Reproduce:

1. Type anything
2. If the suggestions does not open automatically press ctrl+space

#163142 
This issue has resurfaced. You should not have been so quick to lock the thread.

<img width="764" alt="random" src="https://github.com/microsoft/vscode/assets/5502749/757d7cc9-88d1-4132-bded-334fc5140890">

**Comment by jrieken** [comment]
This can be controlled with the `editor.wordBasedSuggestionsMode` setting
