### ISSUE TITLE
bug: instant crash on wayland

### ISSUE THREAD

**Issue by stickyburn** [microsoft/vscode#195294]
Type: <b>Bug</b>

Start code in wayland (--ozone-platform-hint=auto), it crashes instantly.
Can be mitigated with `"window.titleBarStyle": "custom"`, but it crashes the moment a new window is opened.

VS Code version: Code 1.83.0 (e7e037083ff4455cf320e344325dacb480062c3c, 2023-10-03T16:11:49.843Z)
OS version: Linux x64 6.5.6-zen2-1-zen
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 5800X 8-Core Processor (16 x 4199)|
|GPU Status|2d_canvas: unavailable_software<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>opengl: disabled_off<br>rasterization: disabled_software<br>raw_draw: disabled_off_ok<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software<br>webgpu: disabled_off|
|Load (avg)|0, 0, 0|
|Memory (System)|15.53GB (12.12GB free)|
|Process Argv|--unity-launch --enable-features=WaylandWindowDecorations --ozone-platform-hint=auto --crash-reporter-id f2d9484c-7d8e-40c3-ad78-ee480fde444e|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|undefined|
|XDG_CURRENT_DESKTOP|Hyprland|
|XDG_SESSION_DESKTOP|undefined|
|XDG_SESSION_TYPE|wayland|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-tailwindcss|bra|0.10.0
vscode-eslint|dba|2.4.2
copilot|Git|1.124.0
copilot-chat|Git|0.8.0
gitlab-workflow|Git|3.80.0
go|gol|0.39.1
vsliveshare|ms-|1.0.5883
gitblame|wad|10.5.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263cf:30335440
vscorecescf:30445987
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
py29gd2263cf:30856253
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
3biah626:30602489
89544117:30613380
a9j8j154:30646983
showlangstatbar:30737416
0bi6i642:30841073
a2ce3375:30757347
pythonfmttext:30731395
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
pythonnosmt12:30797651
pythonidxpt:30805730
pythonnoceb:30805159
copilotsettingt:30839829
synctok:30821570
dsvsc013:30795093
dsvsc014:30804076
diffeditorv2:30821572
dsvsc015:30845448

```

</details>

**Comment by tennox** [comment]
Same issue - took me two hours after vscode update (from 1.81 to 1.82.2) to bisect what caused it.

**Comment by martisj** [comment]
This is the fix! `window.titleBarStyle: "custom"` :tada: :raised_hands:
Thank you @stickyburn for sharing your hard work and findings :pray:

**Comment by stickyburn** [comment]
@martisj all good! Hopefully the root cause is fixed soon.

**Comment by trustytrojan** [comment]
@martisj Thanks for the fix! This bug has annoyed me for weeks on end... What makes this even better is that now we have the title bar that I used to think was exclusive to Windows!

**Comment by paolomainardi** [comment]
It works just for a single instances, running multiple instances still crashes.

**Comment by Gavin-Niederman** [comment]
I can also only run one instance of vscode. 
I am running version 1.83.0 on Nixos.

**Comment by FedFer98123** [comment]
I'm also experiencing the same problem, the fix seems to work for me too but it doesn't seem to crash on multiple windows open.

**Comment by stickyburn** [comment]
@deepak1556 I believe the issue you mentioned is a part of this and not a complete duplicate. There are two things going on - instant crash with wayland flag on; and instant crash when titleBar fix is applied and a new window is opened.

**Comment by deepak1556** [comment]
@stickyburn the linked issue tracks the relevant issue in the runtime https://github.com/electron/electron/issues/39449 which covers both the cases you have reported.

**Comment by paolomainardi** [comment]
To anyone affected by this issue (i guess all Wayland users) the thread to follow is this one: https://github.com/electron/electron/issues/39449
