### ISSUE TITLE
VS Code Icons - Ignore Special Characters

### ISSUE THREAD

**Issue by Tride0** [microsoft/vscode#195299]
It may not be best practice but sometimes special characters are put into file and folder names. If none of the VS Code icons use a special character to select file names then it would be nice if VS Code would remove those special characters when deciding which folder/file icon to use.

Tools **vs** ~Tools **vs** 1. Tools
~Archive **vs** Archive
![image](https://github.com/microsoft/vscode/assets/34794736/53fd28a3-710d-435d-9ead-70c0ad2fd50c)

**Comment by TylerLeonhardt** [comment]
@Tride0  where would you want to remove the special characters? Can you give an example screenshot? Not sure I'm totally following you.

**Comment by Tride0** [comment]
![image](https://github.com/microsoft/vscode/assets/34794736/8362ef9c-c26b-49b7-8fd2-23c1edf923fd)

**Comment by TylerLeonhardt** [comment]
@Tride0  I see. So the ask is that `~Archive` would also have the "brown folder with the clock" icon?

**Comment by Tride0** [comment]
Correct

**Comment by aeschli** [comment]
The icon theme could choose to give a specific icon to a file name like `~Archive`.
I don't think stripping 'special' characters is a good idea. Also, what are special characters...

Closing as won't fix.
