### ISSUE TITLE
Error: EPERM

### ISSUE THREAD

**Issue by developedbyvictor** [microsoft/vscode#195201]
I've been facing this problem for several days, every time I try to change the name of a file/folder or try to move a folder/file to another location, I get this error. I've tried uninstalling vscode, installing another version, activating the necessary permissions in windows, but nothing has worked. It's only in vs code that this happens, I'm having to use studio code...

![Capture](https://github.com/microsoft/vscode/assets/145487967/f5de904b-1d44-44e1-9d86-3a21cd6f5038)

**Comment by gjsjohnmurray** [comment]
Similar to #194845

**Comment by bpasero** [comment]
Can you figure out what locks the path: https://learn.microsoft.com/en-us/windows/powertoys/file-locksmith
