### ISSUE TITLE
descriptions in source control

### ISSUE THREAD

**Issue by JajarGaming** [microsoft/vscode#195355]
Would be pretty nice if we could write the commit descriptions through the source control window as well

**Comment by gjsjohnmurray** [comment]
Doesn't this already happen if you press Enter twice after typing the commit message into the field in the SCM view, then type your description starting on line 3?

**Comment by JajarGaming** [comment]
> Doesn't this already happen if you press Enter twice after typing the commit message into the field in the SCM view, then type your description starting on line 3?

Just figured that one out - wouldn't say that this is very user-friendly as this feature isn't too easy to find on your own...

**Comment by lszomoru** [comment]
@JajarGaming, thank you very much for filing this issue. Another option is for you to press the commit button while there is not commit message specified. In those cases, you can leverage the editor to author the commit message.

At the moment we are not planning on making any changes to this area so I will close this issue.
