### ISSUE TITLE
Improve visual treatment for indicating changed variables in debug viewlet

### ISSUE THREAD

**Issue by stevencl** [Microsoft/vscode#1953]
As we discussed, we should explore different visual treatments for indicating the last changed variable in the variable window. Currently changed variables are indicated by colouring the value red but this can clash with the way that strings are represented. Some of the ideas we discussed are
* Bolding the name and/or value
* Highlighting the background then fading to a specific opacity
* Changing the colour of the name and/or value

**Comment by bgashler1** [comment]
Below is the visual treatment that we agreed on today (please disregard the inaccurate changes in variables).  I will be pushing these visual changes to master branch soon.
![conditional-breakpoint](https://cloud.githubusercontent.com/assets/11839736/12473614/8c10ae72-bfc8-11e5-99f1-8e39e56008fb.gif)
## Design Rationale
* Fading after a fixed amount of time emphasizes a change has occurred (while avoiding a misrepresentation that a change is in progress)
* Helps to visualize the order and timing in which each variable has been evaluated… may also help solving race condtions in ansynchronous code.
* Chrome DevTools uses this approach (combined with inline REPL)

**Comment by bgashler1** [comment]
Reopening until I have a commit to update this issue with

**Comment by bgashler1** [comment]
Resolved 1132f27e22b59b5bc4c57a61d9be23963354f05a

**Comment by bgashler1** [comment]
Although to make it flash on each change, we would need additional logic to re-flash a variable if its changed more than one time in a row.  For instance, we could apply a `.changing` and `.changed` class.
