### ISSUE TITLE
Keymap improvements

### ISSUE THREAD

**Issue by zhouxinghong** [microsoft/vscode#195310]
Shortcut key improvements

Currently if I assign a shortcut key multiple times it will conflict. Now we have to resolve this conflict.

The ideal solution is:
The activation of the shortcut key function is only for the currently opened file type (i.e. language). For example: I assigned Ctrl+B to Python and Ctrl+B to C#. At this time, in order to make the shortcut keys independent and not conflict with each other , then when I open a C# file, VSCode should disable the Ctrl+B I assigned for Python by default, and enable the Ctrl+B I assigned for C#, and the reverse is the same principle. This can well avoid the problem of conflicts if a shortcut key is assigned multiple times. 😜

Since VSCode supports up to 13 languages (i.e. 13 file types), this improvement can maximize the uniform distribution and use of the same keyboard mapping scheme (i.e. shortcut keys) in the 13 languages ​​😜

Windows10
VSCode 1.83

**Comment by zhouxinghong** [comment]
Since VSCode supports up to 13 languages (i.e. 13 file types), this improvement can maximize the uniform distribution and use of the same keyboard mapping scheme (i.e. shortcut keys) in the 13 languages ​​😜

**Comment by gjsjohnmurray** [comment]
Can you use the `editorLangId` context key in the when-clause of your keybindings?

**Comment by zhouxinghong** [comment]
> Can you use the `editorLangId` context key in the when-clause of your keybindings?

Hello! I don’t quite understand this! Please give an example of keyboard binding.

**Comment by zhouxinghong** [comment]
The situation now is: I have both C# and Python extensions installed in Code, and if I assign the same keymap scheme to C# and Python, it will only work for one of the languages. . .

**Comment by ulugbekna** [comment]
You can already do this using `when` property of your keybinding. Reference - https://code.visualstudio.com/docs/getstarted/keybindings#_when-clause-contexts
