### ISSUE TITLE
VSCode Extensions List on WSL Issue

### ISSUE THREAD

**Issue by nathanaelytj** [microsoft/vscode#195338]
Type: <b>Bug</b>

VSCode Extensions List on WSL keeps on loading.

VS Code version: Code 1.83.0 (e7e037083ff4455cf320e344325dacb480062c3c, 2023-10-03T16:12:16.321Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Connection to 'wsl+ubuntu-22.04' could not be established

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 5600H with Radeon Graphics          (12 x 3294)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.39GB (4.49GB free)|
|Process Argv|--crash-reporter-id 78a823a0-b4ea-4649-86bf-1f4b899ae590|
|Screen Reader|no|
|VM|40%|

Connection to 'wsl+ubuntu-22.04' could not be established
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
remote-ssh|ms-|0.106.5
remote-wsl|ms-|0.81.8
remote-explorer|ms-|0.4.1
resourcemonitor|mut|1.0.7
copilot|Git|1.125.0
copilot-chat|Git|0.8.0
git-graph|mhu|1.30.0
resourcemonitor|mut|1.0.7

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
py29gd2263cf:30856253
vscaat:30438848
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
3biah626:30602489
f6dab269:30613381
a9j8j154:30646983
showlangstatbar:30737416
a2ce3375:30757347
pythonfmttext:30731395
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
pythonnosmt12:30797651
pythonidxpt:30805730
pythonnoceb:30805159
copilotsettingc:30839828
dsvsc013:30795093
dsvsc014:30804076
diffeditorv2:30821572
dsvsc015:30845448

```

</details>

**Comment by nathanaelytj** [comment]
![image](https://github.com/microsoft/vscode/assets/26967808/4cc485a8-42e5-4588-8c03-29a6ca0b56b4)

Screenshoot for example of loading

**Comment by sandy081** [comment]
Looks like a remote connection issue

**Comment by nathanaelytj** [comment]
Waiting for a bit and the extension tab now loaded. I will close this now.
I will reopen when more info is available.
