### ISSUE TITLE
markdown: insert link to file in workspace not working since 1.8.2, all good in 1.8.1

### ISSUE THREAD

**Issue by boseoladipo** [microsoft/vscode#195349]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 
- OS Version: 

Steps to Reproduce:

1. Open a file in editor
2. open the command palette and select markdown: insert link to file in workspace
3. This pastes only the path to the file instead of the markdown link.

https://github.com/microsoft/vscode/assets/40306122/055740f9-156b-4979-8e88-55bd3339d85b

**Comment by Alecton4** [comment]
Also, smart pasting URLs as Markdown links does not work anymore. I have `"markdown.editor.pasteUrlAsFormattedLink.enabled": "smart"` but the URLs are under under no circumstance pasted as a Markdown link. Only `"markdown.editor.pasteUrlAsFormattedLink.enabled": "always"` works.
