### ISSUE TITLE
Documentation web site opens each time on launch

### ISSUE THREAD

**Issue by lyahdav** [Microsoft/vscode#19530]
- VSCode Version: 1.6.1
- OS Version: OS X El Capitan 10.11.6 (15G1217)

Steps to Reproduce:

1. Launch Visual Studio Code
2. A new tab opens in Chrome with https://code.visualstudio.com/docs?start=true. I don't see a way to suppress this.

Also not sure if it's related but each time I launch I get a popup telling me there's a new update to install but when I restart to install it just quits the app and when I reopen it, it seems it never upgrades.

**Comment by chrmarti** [comment]
The web site should only open once on the very first startup. It sounds like the application cannot write to local storage, maybe the malfunctioning update is related to that. /cc @joaomoreno 

@lyahdav Could you try renaming `~/Library/Application Support/Code` to `Code-old` or something and see if the problem persists?

**Comment by chrmarti** [comment]
Closing after no additional info was given.
