### ISSUE TITLE
InlineCompletion partialAccept not firing correctly with Suggest dropdown

### ISSUE THREAD

**Issue by marrej** [microsoft/vscode#195385]
TLDR; Accepting Suggest Item (CompletionItem) fires partialAccept, but next line/next token acceptance fails to trigger the partialAccept.

Repro steps:
1. Trigger inline completion
2. get Suggest Dropdown
3. Trigger accept next word (ctrl+right)
4. No PartialAccept notification sent

Expected:
PartialAccept message would be sent for the current shown completion Item

This seems to occur as the edit application causes model update, which triggers disposal of inlineCompletions due to suggestItem being cleared.

VS Code version: Code 1.83.0 
OS version: ChromeOS Version 117.0.5938.144 (Official Build) (64-bit)

**Comment by hediet** [comment]
Can you reproduce in the [monaco editor playground](https://microsoft.github.io/monaco-editor/playground.html?source=v0.45.0-dev-20231013#XQAAAAIqHAAAAAAAAABBqQkHQ5NjdMjwa-jY7SIQ9S7DNlzs5W-mwj0fe1ZCDRFc9ws9XQE0SJE1jc2VKxhaLFIw9vEWSxW3yscxyx-6HVciAKctgAboa7AaZZDHLgrLqPRv_fRv2RyIokydlTdTYccsu6v6jDrc8jQ8utukPwKUQ2RhhDEWkiejwvhCv6mI9f-mMWJ901Y9mnfbO1g9WbURsQKLj7If1bEqyfxshEfYmMsEBsZWDcvtviGwczYH-bGaY1q1RTksWprUaeb-7D9qk8sSZzNt4rv4OI9tPsXri4WDjMgCqcbDuFokXJzKy2gqmGmSPqpHgQIM0u8P3kyl2iDyOLRX7pffC0wtHHJbtk5Wp_jyMrpJQhlh4zrZoEKisNLyVy6r7velG7BULVOfeVyuQwec9LaEKXOW7WsrPRvPUXd6Mc-6NCjumphLE7e7qlpuD4U8a3tyNqUafePM05t3TUd5jHLGWAyJNlKsFrchjXEoUumGQ_461dRDaztbiGlpCzR3VJTXFCmH8oScjafsl5jj5eIzfi2-915tKakSFDv27UiLkjCItKT-Behj3gK9SSTNPzqj3unV95iGA4PZXZOJNQGsRDRZ1b5Nln9zL4YZ6TUSLpBxoj-eFljivVriY81Vm9c9VCNrpzx0_t9np7-g4X1rdNmxxz3sEGZhRg6DE31OlRMuU4nNu-arXPjKs0K56snZteJ29YKdWq3FI3ETCVzZ_TwZoTOhOEhkr7mI1LNtezFmBIDTjgucW_w_uPk3czeE-k65Ul-k-3GcSMG9Y03EPMKdoaPPAet1ikRlMobg0nPnFn5XqlzZcnKiqimCQs86lrbOOeQNMBnfVD41RVH6p_mZs-8THqT7j6gPzIfTAJ7jZ3SC7bTRxBAuHNkXJK6lb8AO0gcJcjyilwM7_tYTWwVg-D0YbPG4HvzaC9-egJJ3CbHm50VUKSTJCoQptXhBbrnVEa6Q7F8MOnVrWyKusAP-eX8NNss24XQQhdz2GB5j6ELJ66eekSIHt7cCN2-FUEmx1tf-VR8t3cmW5FgBznDeQAAojFzZ4jgSPW_bvVwIbg0Mk1SyEh7MEeOuegjfBj6FEUI9yKfuNMR7jF5PA87fx7-xB6ydHB-OWm14uH_9sXFn6P0n5dGDZEVoGBMZWb-sF9Jn9hdhrASGcmTcHSz9fzv9vgAaAF9u5Ubn4XJSp_bgfDGUTOSATxIDgRj9DHkvF8tIRugFPJPGxhd7vZj0lcm0ZemuP751sgqmj8FLicEcFHn43q-MMFP1urjATCDS_VMwLR_L4YvAx-GEVWxLqxRmb6bR00fdVr9D88t0Xb20bejJe7SBvM_vMEzqqInPlIC5JWJshR3OtmnNrE9boka4xJpnUy0YyD1yEi63j1TeYzSjL2WInktcJj7_M5L6jCyYg0fIH6_hmVZRaPH9PkMowCOEoFW-ftqpMXNpW7MFVRiZ4PLXAEDAFvgSfpJKu16sO-p2iVaDPCHM5R3Sq-Lu_kdXooT8qcAagpMyNL5ZdLF-q-8fRgWadzoklGONplwoU3J0ngeG5JQNTX3G4IWblQHnR3xAmw_ZZp9qg640zarmwbdbBfP9erXzv31t3Mo6TS6CpjCC2NNGpBEoYYuU-SXPPrpoaQ27etcZOl4lONdpp8y2j7OXF24RCjsk8B5LRjERL2t4dZ5wK0RDZvuTG9FL4G6loWAXX6yc3bCUaMYnh-Kb6DMKFgbOwo52NWadVksCNtG4pjIZBEBIhU41JPXcwf9Z55FdT6IUOgcUK_K1EXEzDKL5Zn9hu_lOeE7HtD5geYKcYn3e0eNZMC6r0bwHsP4T57DruS0kwbr2jy2EqVsg_GGfB1AHmIdrsSFTJz4wanEynUBmaVD4U4pihuQfvVpfCMkT2OKlH41ejHCzPyItLZGoYBVOA2pYBfUjdDd2bTbhGsJmYvCw8M4OPJ60ifu3emYNWQZTlDcEUTXB2q-1_kD86m-424P77lzmtdswcorbKu4SEKaunXRXdwSXieCiguZTacHbgZ8CqeWRI9b0vJYx9CQX7Al8lXAoLd3Hwr_2kb2HHIRW6qFDHnyGnX7CojYBtnQRM1-pxMz5vzPlz96AQcxdFS_2FKIVfzftLjmR3eraFQQtynlWFhgOEyL7mc-ptHvBLe748Rw__zX1Ca3Po5o2kYUli-dwpZBRocw-It0hp-joU62EKgQri1Q6ZyL5E_NHDuanyhr-_hZNB4XlLHRZdegtyFWwmcmBgbgh1kL5ZPx9IleapAVnE0fIMoaK2thH7mz51VcsSKbvmVbMu9QBcWDkbfGmWeAB_dqqC02YJLzzBCmTxcSu4T9MH7qlwsYKhumektALWnlInzMc_R427vBnYSvXhBpX0w2KkdzqCdAc7-WvOkQ2Ci8V1eEPkgdLnvci0qGqxE6dXJ1N-zuq5FlBmQTjpdy0nVKDkE1141me54IRy-t1_I4KR7rW1AUStUKvnIzKwWJ1wMppJ3lqh_vjwvVN5Fhsb3WHLRHhvLSafTLkgwpW2DQH_XSu2nBKkvHREbiyKiJAaeG86XPZMn-ek1k3MPsuaJkdYimQcctD6kRaPI6LBKkxK_4bHpU4mzPvXfva8rntn_MEhOheUi4WgtA8Db_QZAagvWozQIpJ9Y8NBlGPWJjFeEdJlBsvTu-_Thek_oXprxFSFP1Z6XYJcdPR1W90Fm-GKT2zDANNRGVRMMDJGwaXQg-GWuDuxdBzFbEXBHokVC_JUvYwSmEDLB7mSjFSJIvATVgZAwuWCY0LjPtqh3tqXqBKFEfQNzqfhf0fUrlOVdC1O8xqVAB-w_J_7LGwQGKWt2wFMvVtCbi0_3iphAA)?

**Comment by marrej** [comment]
I wasn't able to reproduce in the playground. Might be already fixed at head?
Closing as its already unrelevant, thanks!

**Comment by hediet** [comment]
We didn't touch that code for a while now. There might be an issue with the extension host or your extension though.

**Comment by marrej** [comment]
Might be, thanks for the pointers!

**Comment by marrej** [comment]
Hi @hediet . Sorry for reopening the issue, but I finally got to fixing it. It seems that the problem is in fact in the code, but its hard to reproduce in the playground, but here is the scenario:


[monaco playground](https://microsoft.github.io/monaco-editor/playground.html?source=v0.45.0-dev-20231013#XQAAAAITFgAAAAAAAABBqQkHQ5NjdMjwa-jY7SIQ9S7DNlzs5W-mwj0fe1ZCDRFc9ws9XQE0SJE1jc2VKxhaLFIw9vEWSxW3yscxkS7UaAEiAKctgAboa7AaZZDHLgrLqPRv_fRv2RyIokydlTdTYccsu6v6jDrc8jQ8utukPwKUQ2AAOQuX4rbhS2d5xDEFoRe38dagUBVaGjn3ZgqHnMNYlEr6IdBFeCWH7bDiThfkqa4v_SXRftGd6PTcl_DQ3nJFGUuqrJSN1LJdxigJMny7JoHrLCSiwJsP1IdNSTj4slEcFuqgCwq1yx2Xqf7FRNr7Hy3hSK-UgyGxgUn89I7M2-AN-rVBh9c_O-u0VH40vMRJMuD0UKedFVrNDO37slIWA7MKs2PUOtBqpYlzrpOlWn0D-gJj8GnHdAvpXzPlV7aTCBZszRMku-0YSsh7nb93gUDO2WXyIwe8PW7VXPa-73isZd_8qGsWqOu0tfSG1Y8uPUd8MUQb7vPw65k90yoXGgYbKLXUoL3kDrjUFAbOot9N2FVOLSdW17EUMuewYC-C_9zyOJ7sC9oN5RT7cbbJlNa1x3MCvD0O4bnQUbA-f8mvm9BzgZJpsbiuLLhL3eFw3WsTjkusQZTUYTFA8sZZaeLA5F5NDTaEdIHa4o8zXVClI9ITFdsi4UdhG1X0jVaE3q8mJKLxfCmqlUlB5_6e_wOdU-4kFO1WJBz4LTfaYEzM42P094e86ovTcICqjWhD6iy3GF6_tN1NuBsb4n3eGuQZ07s8KTPDMgkla-r5YrWAcSyhJOVimoLLD-bBvX6TVz_y5Z9mk3vOvm-tZSrTrhyaCSMx9xsqrVwNHPDC0mtxqfR-ALnS5Fe8Ghps2uOw5cQmdmsPSXSDobL2nzs9cnlJJk_SYM4BJSwkaH2hvDhk0ynRO0E0sMsWwk6wcYNri8v1Lpb8pk1e933snDhJltfNFN5-CsRmqnMjH5zIy7gKkZ135fvQL_KTMIycgRVDAEML1s_AnwTP7F7RNx3zruNOAVwkEA0MoC-46ZPqIPK-VsEeOZL1KgHCOY5NjkfZZ3A7O6EXZyhhe2DxjlIPPu-qBBZiGveUNazr0DR3fYuHqXw_V5pcASUTuVDY8rtjgkJwCVso9WX4nW_7NBtdUCEvY5QaqYkmhiNM7j4z5YJDH5PstIhEz8STkv6DinOkk1vpH0TfgkcT9p-U81Mu29_xVP68brBP1DkfDqGuVteN4djbVvZlXGxUgwNCJ2HJKbrqFFMasPuBHjJJGH6tNbL86g4pv5kjNC77TLAq4H4PTYNTlUkPDKCVbTydSkwhXA4mD0PViNMtVoCAtU8m69oPpDOtvtbv4lo3BpTruhFEz-g6u0z6K-br7j0BOjSA_Q5k7yhwNRmV5E5IJl1c2sqdO3_9CIbgqqoroBjPinE-M1bOYvah06Qaqpr7poHQ5dTYXJPmFGrQ6SPnTtfhhqazdFZXMRuKy5YyM2tC-HGoujiKvWB_GDLzTThYLiPTNvKbhryw2xLgRVCSRVx5LUk4a8AmP4SQVJDYilhQL31tw3Vahy6y6VCPpiFHe4pUx7UxV4kxbcUTZ-MEW-jbwVTLgx1ztxCrr5hmgrISh8byz7SXW0f9YfAcxQmoQ6-iWTXNEWJbpjj1bniBUX1aMRU0P8xZdFE7NlABC_raMuj3nwXDk38a2arAcPnLjqOMm3pMxBa7Jau7OwEv45ZJ6XALNcsBNwrhsIpXeK8jo0ED66p38Rr7J5l60kgFcO_wJKa4nPl9bHkSaq_M0DaqvROs74GDmr6Yfgi-deLJxykJ9NzIwJxumICyE8SwZ7xQP1pY1a8tpFMvlY5r-a-4KmWFEvAqfT2K6bDl1vzm0qvl4gWqUknbOmNgBX0rGTtj34O_dHqYXSRNKnou9huD-3HJJPOgjdZsbpba7vfOKO2JLn9HDiN1xOAuzpb0pBhRxVvjZRtFiiyGSYY_KQos_C6jdo-PJFoCC1rrQWC2C7eQJ_Yi4YmBUc0ZtimwSFVuG9QIOVFFZMRR14D51tKUuroG8vGVJlZmt7AQBC7X3eW536JJoL37HOlIyehvz-lTtvrKGyyEaU8MdlHAY94L8_Qa37UXyNFfG6XgoCb1xnLobHhhbfCp7nIsANM69zfy_F8SRiV2OPQl1910fkV0WSgZzh0bO4Th-FmGENnb6fGgIZslfGR5bVg3CaZOdUcr9bH7kNsZy9Im61srI7VMqcrld631LBYJhB6_Qf_y3p8smgJHuVWJJ2sgZtRGuJEYIFbAvQGpOHb3hexfDWEP7u1cHYATfsaicj8D2q9tLmwaXA1VoxYxuaf5ll0kCPk_853E8sikTHne_5-EkUQZM0dHj3lZsbAK4p-hMlwO04vPqSfYiFw5pY8l-GcWHc1Ye-_tbKSwInp8hxglhT1D2vmdfDFi9BowjLUEDcVfbF0uLZ6WTnydNRSNIfn-sCKoR2RfQCFIuQzYjK2H8lrRQLHGqIkWGxY4yikOA11EJMvxRxEwxu49QTEayWh66jcw-SbYoD_4pJVwdkOMwVoB8fZMoeaQXbIeUNyE2X03ZjdiFFWcyum-Mm2vVSAM3mBaYxUV__dlZUk)

Note that this occurs mainly if the SuggestDropdown is second to arrive. E.g. if explicitly invoking suggest dropdown (ctrl+space) this doesn't seem to occur at all

(Add breakpoints on the free & acceptPartial completion)
1. type `e` in the already existing `consol`
2. Once suggest dropdown `console` appears, accept next token/next line (e.g. ctrl+right)
3. Observe the order of events. The free completion for the id of the suggestion is called before the partialAccept

expected:
The partialAccept is called before free, otherwise the extHost reference to the item will get disposed prematurely.

This has the following effect. The Free calls dispose on [extension host](https://github.com/microsoft/vscode/blob/d576523abbbfb384f8235f0f58e4c9c165cde686/src/vs/workbench/api/common/extHostLanguageFeatures.ts#L1260) and only afterwards the partial accept comes, which tries to fetch the completion by ID but it doesn't exist anymore. So the event is lost.

The reason why its harder to reproduce in the playground environment is that the Extension host cleanup is not properly visible (we basically end at mainthread), as well as the suggest dropdown has to dissapear after the partial accept.


Diving in to the reason why this fails:
- running the partialAccept triggers edit application, which runs the cursor move on SuggestController which runs `clear` and disposes the Suggest dropdown
- This in place reruns the [fetch()](https://github.com/microsoft/vscode/blob/d576523abbbfb384f8235f0f58e4c9c165cde686/src/vs/editor/contrib/inlineCompletions/browser/inlineCompletionsModel.ts#L85) in the inlineCompletions model which on non existent dropdown removes the SuggestWidget reference
- That causes the free up of the InlineCompletion reference, as its bound to the SuggestInfo
- The partial accept resumes and sends the event to mainthread which pushes it to extHost and tries to fetch the completion item, but its already been removed so no event is sent

That raises 2 questions from my end. 

- Shouldn't we add some telemetry in the ExtHost for these conditional retrievals to be able to preemtively catch issues with the non-connectivity (or possible regressions?)
- Should we add a debouncer/transaction over the partialAccept so it can finish processing before the new completions are fetched??
