### ISSUE TITLE
Quick Input: Multiple Steps and File/Directory selection

### ISSUE THREAD

**Issue by goerlibe** [microsoft/vscode#195363]
✅ Quick Inputs allow to set `step` and `totalSteps` properties to allow a multi-step input selection.  
✅ There is also a convenient method to let the user select one or more directories or files using `showOpenDialog`.  
🟥 However I could not find a convenient way to do both. I want one of multiple steps to be a "file selection" and currently it seems I have to manually implement a QuickPick or InputBox and I cannot benefit of the many existing showOpenDialog features -- or use showOpenDialog and miss out on the step indicator.

i.e. it would be very helpful to have a `createOpenDialog` function, returning some Object that implements the QuickInput interface, on which I can also specify `step` and `totalSteps`:
showQuickPick --> createQuickPick, 
showInputBox --> createInputBox,
showOpenDialog --> ???

**Comment by TylerLeonhardt** [comment]
`showOpenDialog` does have a `.title` property which could be used to specify the `step` & `totalSteps` manually:

```
title: `My open step (${qp.step}/${qp.totalSteps}`
```

however, the problem with this `title` property is that on some OS's we can't use it... For example, on macOS there's no title:
![Image](https://github.com/microsoft/vscode/assets/2644648/62f5d851-2055-4d19-8a67-2be86d1163ef)
so having a `step` and `totalSteps` option wouldn't do much good on some platforms.

Another option is to have a step in your QuickPick have a single QuickPickItem called `Browse files` of which this would call `showOpenDialog`.

**Comment by TylerLeonhardt** [comment]
I think that those ^ options are your best bet... and also to 👍  this issue which I think is more likely a candidate for a `step`/`totalSteps` https://github.com/microsoft/vscode/issues/162810
