### ISSUE TITLE
Consider disabling the anchoring when a user starts scrolling

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#195324]
Originally suggested by @Tyriar in https://github.com/microsoft/vscode/issues/194158 

> You could also do something clever like disable the anchoring when a user starts scrolling, and when they focus a cell or type it re-enables the anchoring

I was playing around with the latest changes from https://github.com/microsoft/vscode/pull/195309 which anchors to the focused cell when previous cells are growing but found it a bit unnatural when scrolling upwards since scrolling doesn't interrupt the anchoring 

https://github.com/microsoft/vscode/assets/876920/e93672ff-a425-4751-8613-8f6e4c68dbf7

In Debug/Terminal/IW by default it anchors to the bottom of the editor content when streaming, but when users scroll upwards, it disables the anchoring and doesn't update the `scrollTop`, I'm wondering if the same technique can be applied here.

**Comment by rebornix** [comment]
To be more precise, the behavior right now is that it anchors to the focused cell when it's in the viewport. That means when scrolling upwards, the cells above the focused cell grow upwards (so it's fighting with users' scrolling) but when the focused cell goes out of the viewport, the _anchoring_ behavior is then disabled.

**Comment by amunger** [comment]
This is only the case for scrolling up. Once we stop anchoring, the cell growth will start fighting against the user scrolling down.

**Comment by rebornix** [comment]
> Once we stop anchoring, the cell growth will start fighting against the user scrolling down.

True, but doesn't it align with the "intent". Initially on `shift+enter`, the intent is running cell and starting working on the next cell, we want to anchor to the focused cell as users are likely to edit the cell. When users start to scroll, the intent changes to browsing, respecting users' desired scroll top is more important IMHO.

The focused cell can regain "anchoring" if users start to type, press escape to focus cell container, or mouse click / arrow keys to change focused cell, then the view can anchor to the focused cell again, since the "intent" is now switched back to "editing".

**Comment by amunger** [comment]
verification steps

create a cell that will grow output size over time:

```
import time
for i in range(25):
    print(i)
    time.sleep(.5)
```

clear the output if needed then run the cell with shift+enter
As the output grows, the next cell should not be pushed out of view, but scrolling up will prevent that behavior.

**Comment by amunger** [comment]
I put this on the testplan item instead
