### ISSUE TITLE
Add rootFolderNames & rootFolderNamesExpanded iconThemes definitions for root folders

### ISSUE THREAD

**Issue by harbin1053020115** [microsoft/vscode#195316]
We need to custom iconThemes of the workspace's root folders, we want to custom different iconThemes for each root folders according to the root folder's name: 
![image](https://github.com/microsoft/vscode/assets/2869750/b884e9a7-cd02-42eb-8b17-0ca5b4cd3b67)

**Comment by aeschli** [comment]
fixed by https://github.com/microsoft/vscode/pull/195319

**Comment by aeschli** [comment]
To verify:
- create a new file icon theme. You can use https://github.com/microsoft/vscode/tree/main/extensions/theme-defaults/fileicons as an example
- add properties rootFolderNames & rootFolderNamesExpanded

**Comment by DonJayamanne** [comment]
Gave it a good crack, but unable to get things working.
Hopefully someone else will have better luck

**Comment by joaomoreno** [comment]
Got it to work. Needed something like this in an icon theme file, in which `fakeproject` would be the name of a root folder:

```
	"rootFolderNamesExpanded": {
		"fakeproject": "_file_light"
	},
	"rootFolderNames": {
		"fakeproject": "_folder_open_light"
	},
```

@aeschli was suggesting to just edit the `extensions/theme-defaults/fileicons/vs_minimal-icon-theme.json` in our repo, so one could run out of sources, pick the Minimal icon theme and see the changes.

**Comment by DonJayamanne** [comment]
> suggesting to just edit the extensions/theme-defaults/fileicons/vs_minimal-icon-theme.json in our repo,

Thats the only difference, I created a new extension.
Rest was the same. 
Though its weird it didn't work, should have.

**Comment by aeschli** [comment]
Oh, sorry, this should have been a real test plan item with complexity 3.

I came up with this repo to test it: https://github.com/aeschli/icon-theme-test2

It implements an icon theme with the new feature
- clone the repo, opn in VS Code
- run the launch config. This should open on a test workspace with root folders and also select the theme
- Verify that the `root folder called `rootFolder1` has a different icon than `rootFolder2` (it's just some random image)
