### ISSUE TITLE
Unable to open Disassembly View when webview focused

### ISSUE THREAD

**Issue by colin-grant-work** [microsoft/vscode#195387]
Does this issue occur when all extensions are disabled?: Not really, since debugging with the disassembly view requires at least some extensions. But I'm quite confident that plugins are not the problem.

- VS Code Version: 1.83.0
- OS Version: Windows 10

Steps to Reproduce:

1. Start a debug session that supports disassembly and hit a breakpoint.
2. Focus some webview (even the Welcome View will do).
3. Run the `Open Disassembly View` command from the Call Stack view.
4. Nothing happens.

The problem appears to be in the fact that the `Open Disassembly View` command extends `EditorAction2`:

https://github.com/microsoft/vscode/blob/33876c27f082973adbddc027e0e532c3648099dd/src/vs/workbench/contrib/debug/browser/debugEditorActions.ts#L199

Which means that it only runs if one of these fields is defined:

https://github.com/microsoft/vscode/blob/33876c27f082973adbddc027e0e532c3648099dd/src/vs/editor/browser/editorExtensions.ts#L455-L459

When a webview is focused, line 455 returns `null`, so the command execution bails. I don't really see a reason for the `Open Disassembly View` command to care about the focused editor: none of its preconditions refer to anything to do with editors at all.

**Comment by connor4312** [comment]
Not sure why it's an editor action since the only thing it does with the editor is check editor.hasModel()... which isn't necessary for disassembly to work. Can be made an Action2. PR welcome.
