### ISSUE TITLE
Rename variable occurrence from cursor position

### ISSUE THREAD

**Issue by TudorHulban** [microsoft/vscode#195362]
hi,
hope this is not a duplicate and this feature request is not handled somewhere else.

currently with `F2` I can rename a variable, change that could affect everywhere this variable is used in the code base.
what I did not see is the option to rename from cursor position. 

say I am in a unit test file and just copy some test case in file A, say I copy lines 10 - 14.
now I am in line 16 with the cursor position pasting the copied code.
there is a variable, say `reconstructedABC` which is present in lines 10 - 14 several times and  now in lines 16 - 20.
I want to tailor another test case and need a variable `reconstructedDEF`.

the feature I am requesting should provide the option to rename  `reconstructedABC` in the same way like `F2` but from line 16 where I am with the cursor, thus preserving lines 10 - 14.
this would work as this variable is not used anywhere else as it is a unit test variable. if this could be limited to the scope of the current function, even safer.

thank you

**Comment by mjbvz** [comment]
Not 100% sure I understand this but I think what you want is right click and then select `rename...` in the editor context menu
