### ISSUE TITLE
Dockerfile COPY Command Fails When Target Folder is Listed in .gitignore, but Succeeds When Removed

### ISSUE THREAD

**Issue by kojima-takeo** [microsoft/vscode#195331]
Dear VS Code Team,

Firstly, I would like to express my deepest gratitude for developing and maintaining Visual Studio Code. It has been an indispensable tool in my development process and has significantly enhanced my productivity. 

I am writing to bring your attention to an issue that I believe could have a substantial impact on the development process of many. I consider it important enough to warrant immediate attention.

---

Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.83.0 (user setup)
- OS Version: Windows 11(Windows NT X64 10.0.22621)

### Steps to Reproduce:

1. Create a `.gitignore` file in your project directory.
2. Add `components/` to the `.gitignore` file.
3. Create a folder named `components` in the same directory as your `.gitignore` file.
4. Add a `Dockerfile` to your project, and include a `COPY` command targeting the `components/` folder. For example, `COPY ./components/CookieManager /app/components/CookieManager`.
5. Run the Docker build command.
6. Observe that the `COPY` command fails, stating that the `components/CookieManager` folder does not exist.
7. Remove `components/` from the `.gitignore` file.
8. Run the Docker build command again.
9. Observe that the `COPY` command now succeeds.

### Expected Behavior:

The `COPY` command in the `Dockerfile` should successfully copy the folder, as `.gitignore` should only affect Git operations.

### Actual Behavior:

The folder is not copied, and the `COPY` command fails, indicating that the folder does not exist. This happens even though the folder is present and only excluded by `.gitignore`.

---
I believe resolving this issue will further enhance the robustness and reliability of VS Code, a tool that so many of us depend on daily. Thank you for your attention to this matter.

Best regards,

**Comment by lszomoru** [comment]
I am not an expert but this does not seem to be an issue with VS Code itself. 
Adding @chrmarti as he should have more insight on how to progress this issue.

**Comment by chrmarti** [comment]
@kojima-takeo How does VS Code get into the picture here? I'm not aware of `docker build` somehow using `.gitignore`.
