### ISSUE TITLE
The terminal quick fix does not work

### ISSUE THREAD

**Issue by FinnChen** [microsoft/vscode#195341]
Does this issue occur when all extensions are disabled?: Yes

- Version: 1.83.0 (Universal)
- Commit: e7e037083ff4455cf320e344325dacb480062c3c
- Date: 2023-10-03T16:13:15.449Z
- Electron: 25.8.4
- ElectronBuildId: 24154031
- Chromium: 114.0.5735.289
- Node.js: 18.15.0
- V8: 11.4.183.29-electron.0
- OS: Darwin x64 22.1.0

Steps to Reproduce:

1. run command `git statux` in the terminal
2. click the quick fix action in the menu, and the action will not run 

https://github.com/microsoft/vscode/assets/1407599/78ce22d7-1652-4289-ba5c-84487bd76ca1

**Comment by meganrogge** [comment]
I believe this is already fixed, can you see if you can reproduce in the [Insiders build](https://code.visualstudio.com/insiders)?
/label info-needed

**Comment by FinnChen** [comment]
- When press the enter key, it will run the command. 
- It will not work if click the item in the menu. Is it designed this way?
