### ISSUE TITLE
Exception throws in startup layout code bricking the install

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#195390]
After updating I see this:

![Image](https://github.com/microsoft/vscode/assets/2193314/231a45af-3884-49fc-adfd-4f8e64ac39ef)

After some investigation with @sbatten we found that it's cause by this line in `initLayoutState`:

https://github.com/microsoft/vscode/blob/33876c27f082973adbddc027e0e532c3648099dd/src/vs/workbench/browser/layout.ts#L494-L497

Which calls into:

https://github.com/microsoft/vscode/blob/33876c27f082973adbddc027e0e532c3648099dd/src/vs/workbench/browser/layout.ts#L1538-L1540

Which calls in to `isVisible` which accesses `runtime` state. This is only initialized later in the `initLayoutState` method though.

Rough repro based on memory:

1. Machine 1 (Windows): Update client to latest
2. Machine 1: Set activity bar to top
3. Machine 1: Sync
4. Machine 2 (macOS, old client): Sync (pulls in activity bar top setting?)
5. Machine 2: Update to latest
6. Machine 2: Open client

**Comment by sandy081** [comment]
@sbatten Thanks for the fix. 

I got report of this bug from some users and I am asking for developer tools console log (thanks @Tyriar)
