### ISSUE TITLE
UI glitches when running clear all outputs

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#195325]
Does this issue occur when all extensions are disabled?: Yes/No

https://github.com/microsoft/vscode/assets/876920/2afb24c9-1b9d-4402-bd13-45a2917c3a47

It seems the cell heights are not updated properly when clearing outputs of cells that are not visible.

**Comment by alexr00** [comment]
I had trouble reproing the original issue, but I also can't repro in insiders so marking verified.
