### ISSUE TITLE
ServiceNow extension stops working after September update

### ISSUE THREAD

**Issue by pbodlev** [microsoft/vscode#195332]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 
- Version: 1.83.0
Commit: e7e037083ff4455cf320e344325dacb480062c3c
Date: 2023-10-03T16:13:10.518Z
Electron: 25.8.4
ElectronBuildId: 24154031
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Darwin arm64 23.0.0
- OS Version: MacOS Sonoma 14.0 (23A344)

Steps to Reproduce:

1. Open VSCode
2. If you dont have installed ServiceNow Extension - install it => ServiceNow.now-vscode
3. Every operation is not working now, e.g. Now: Setup Now Workspace, Now: Create Now Project and etc.
![Screenshot 2023-10-11 at 8 54 47](https://github.com/microsoft/vscode/assets/147049794/981430e5-34b5-46db-85e1-653347381e51)

**Comment by SureshKumar008** [comment]
Yeah, I am also facing same issue.
what we need to do?
 please assist

**Comment by sandy081** [comment]
I would recommend filing the issue against the extension so that the extension can analyse if it is a bug in extension.

**Comment by akshaykhanna** [comment]
Getting the same issue, how to fix it? I tried downgrading the VS Code extension to 1.5 but still got the same error
<img width="306" alt="image" src="https://github.com/microsoft/vscode/assets/12964174/97207637-19ee-46ad-b0b8-f25e2bcfcb8e">

**Comment by FlemmingRohde** [comment]
Had the same issue. Found the solution (workaround) in this post. https://www.servicenow.com/community/developer-forum/vs-code-extension-error-activating-extension-servicenow-now/m-p/2692847

Downgrade vscode to August release. 1.82.3 and the extension works.

In September release - 1.83.x the extension does not work
