### ISSUE TITLE
launch from console; console still open

### ISSUE THREAD

**Issue by Lucyfurnice** [microsoft/vscode#195357]
I need to set environment variables for GIT into the PATH via batch file so my PATH var is not confabulated by multiple things i don't need when a console opens.

@REM
@ECHO OFF
SET PATH=D:\Toolchain\binaries\Git\2.42.0.2\x64\bin;%PATH%
@START code.exe 1> nul 2>&1

This is what I'm using, however start keeps the console open because there is stdout/stderror text.
Is there any way for me to launch from command line, and also close the console that opens?

**Comment by roblourens** [comment]
I think you just want to set the `git.path` setting or change your PATH globally?
