### ISSUE TITLE
Word wrap work incorrect on txt file!

### ISSUE THREAD

**Issue by keyiis** [microsoft/vscode#195430]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: VSCodeSetup-x64-1.83.1
- OS Version: win11

Steps to Reproduce:

1. This is orign txt file,It has three paragraphs, each with a four-space indent at the top of the line.
<img width="602" alt="1697080761997" src="https://github.com/microsoft/vscode/assets/7766085/15ed7430-d103-4f4a-9431-b2e10259c143">

2. When I use vscode open it,The entire paragraph is indented by four Spaces, not just the first line
<img width="1031" alt="1697080949949" src="https://github.com/microsoft/vscode/assets/7766085/c8157884-fab2-4872-8bb8-e39843e78104">

3. This is my vscode config about word wrap
<img width="953" alt="1697081271602" src="https://github.com/microsoft/vscode/assets/7766085/3340684c-ebb7-4a97-9506-5abc4294af41">

I already tried to delete all data what about vscode then reinstall vscode, but nothing has changed, I want to know how to configure vscode to achieve the same effect as txt editor?

**Comment by alexdima** [comment]
It sounds like you would like to configure `"editor.wrappingIndent": "none"`
