### ISSUE TITLE
Command in integrated terminal shows up with "typewriter effect"

### ISSUE THREAD

**Issue by hungys** [Microsoft/vscode#19543]
- VSCode Version: 1.8.1
- OS Version: macOS 10.12.3

![](http://i.giphy.com/26gsvx5YU7M4WT9oA.gif)

I'm not sure if the title was well-explained...

But as you can see in the gif (sorry for the low fps), when I started debugging my program, the commands lunched by debugger showed up with **"typewriter effect"**, which was really annoying when a long command was executed.

After some investigation, I found it was caused by zsh's plugin [zsh-autosuggestions](https://github.com/zsh-users/zsh-autosuggestions). When I commented this plugin out from `.zshrc`, the command just showed up on the terminal immediately.

However, this issue didn't occurred when pasting command on iTerm2.

**Comment by Tyriar** [comment]
@hungys can you see if this is fixed on the [Insiders build](https://code.visualstudio.com/insiders)? A lot of work has happened around this area since v1.8.1

**Comment by hungys** [comment]
@Tyriar I've tried this on **1.9.0-insider**, and the issue is still there.

**Comment by Tyriar** [comment]
@hungys would you be able to test this in the upstream lib https://github.com/sourcelair/xterm.js by running this?

```
git clone https://github.com/sourcelair/xterm.js.git
cd xterm.js
npm i
npm run dev
``` 

Then open http://0.0.0.0:3000 to test it.

**Comment by hungys** [comment]
@Tyriar Sorry I just sent my laptop for repair today. If nobody can help with this, I'll try it next week.
