### ISSUE TITLE
Terminal Rename Failure

### ISSUE THREAD

**Issue by JL-jun** [microsoft/vscode#195431]
Type: <b>Bug</b>

Terminal left-click renaming fails
![image](https://github.com/microsoft/vscode/assets/55470574/8cf0b679-4e97-45d2-9344-79f678e4fc90)

VS Code version: Code 1.83.1 (f1b07bd25dfad64b0167beb15359ae573aecd2cc, 2023-10-10T23:48:05.904Z)
OS version: Windows_NT x64 10.0.22621
Modes:

**Comment by DeeHants** [comment]
Seeing the same here from a "full screen" terminal, rename dialog appears, and does nothing on submit.
![image](https://github.com/microsoft/vscode/assets/1443298/c86475e9-8d25-4350-b158-959b043d3757)


VS Code version: Code 1.84.0 (d037ac076cee195194f93ce6fe2bdfe2969cc82d, 2023-11-01T11:29:04.398Z)
OS version: Windows_NT x64 10.0.22000
Modes:
Remote OS version: Linux x64 5.15.90.1-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|12th Gen Intel(R) Core(TM) i5-1245U (12 x 2496)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.44GB (2.03GB free)|
|Process Argv|--file-uri vscode-remote://wsl%2Bubuntu/home/dearley/wsl.code-workspace --crash-reporter-id 20625c38-9677-4c2f-a086-11bd4eefd9c6|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 5.15.90.1-microsoft-standard-WSL2|
|CPUs|12th Gen Intel(R) Core(TM) i5-1245U (12 x 2496)|
|Memory (System)|7.48GB (5.98GB free)|
|VM|0%|
</details><details><summary>Extensions (17)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|13.4.2
mustache-syntax-vscode|att|0.1.0
crontab-syntax-highlight|hog|0.0.2
eml|lei|0.4.0
remote-containers|ms-|0.321.0
remote-ssh|ms-|0.107.0
remote-ssh-edit|ms-|0.86.0
remote-wsl|ms-|0.81.8
vscode-remote-extensionpack|ms-|0.24.0
remote-explorer|ms-|0.4.1
vscode-todo-highlight|way|1.0.5
overtype|DrM|0.5.0
perl-outline|hit|0.0.7
ecdc|mit|1.8.0
hexeditor|ms-|1.9.12
code-spell-checker|str|3.0.1
highlight-trailing-white-spaces|yba|0.0.2

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263cf:30335440
vscoreces:30445986
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
py29gd2263:30880072
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
3biah626:30602489
f6dab269:30613381
a9j8j154:30646983
showlangstatbar:30737416
pythonfmttext:30731395
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
pythonnosmt12:30797651
pythonidxpt:30866567
pythonnoceb:30805159
dsvsc013:30795093
dsvsc014:30804076
dsvsc015:30845448
pythontestfixt:30871694
pythonregdiag2:30871582
pyreplss1:30879912
pythonmypyd1:30879173
pythoncet00cf:30874137
pythontbext0:30879054
dsvsc016:30880769
dsvsc017cf:30880893
dsvsc018:30880894

```

</details>

**Comment by DeeHants** [comment]
Possibly related to #196447
