### ISSUE TITLE
Recommended extensions are not installed in VS Code Web

### ISSUE THREAD

**Issue by vitaliy-guliy** [microsoft/vscode#195472]
Recommended extensions are hot handled in VS Code web.
It guess it is because the extensions recognized as non-working for web, but earlier they were working fine without any issues.

![Screenshot from 2023-10-12 16-22-37](https://github.com/microsoft/vscode/assets/1655894/f427bf2a-f076-414f-955c-cfe19cb81b46)

A day before I wanted to report another issue I faced in VS Code desktop 1.82.2 - the extensions stuck in installing state.
But after updating it to 1.83.1 I do not see any issues with VS Code desktop. So at the moment it is actual only for web version.

There was a case (VS Code desktop 1.82.2) when one extension depends on another extension, VS Code started to install the extensions but left them in installing state.

![Screenshot from 2023-10-11 01-30-20](https://github.com/microsoft/vscode/assets/1655894/7a93d209-1d2b-4a2c-b14b-95e695bb7b8e)

I suppose the bug is still present in 1.84.0  as it's present at the moment in downstream project https://github.com/che-incubator/che-code, which is based now on VS Code 1.84.0

Does this issue occur when all extensions are disabled? - It is related to the extensions management, so no need to disable the extensions.

- VS Code Version: 1.84.0-insider
- OS Version: seems it does not matter

Steps to Reproduce:

1. Navigate to https://insiders.vscode.dev/
2. Open repository https://github.com/vitaliy-guliy/recommended-extensions-sample
It is a simple repository where I added `.vscode/extensions.json` file with few recommendations.

3. If `Restricted Mode` is appeared in the toolbar, click it and trust the folder
4. Open `Extensions` view and apply `@recommended` filter. At this step all the recommended extensions described in `.vscode/extensions.json` file should be present in `WORKSPACE RECOMMENDATIONS` section.

5. If I search for `redhat.java` (the first extension in ./vscode/extensions.json) I see the warning `The 'Language Support for Java(TM) by Red Hat' extension is not available in Visual Studio Code - Insiders for the Web.`

6. If i search for `java`, most (almost all) the extensions appeared not available for web.

**Comment by vitaliy-guliy** [comment]
Writing here another feedback about stuck the extensions in installing state.
I managed to reproduce it on VS Code desktop 1.83.1

![Screenshot from 2023-10-16 14-55-49](https://github.com/microsoft/vscode/assets/1655894/117aac88-9d80-4ae7-b7ca-4b086d4ef80a)

To reproduce the bug I mounted (1) a high-latency volume from my mobile to my home (Linux mint) with 
```
sudo curlftpfs -o allow_other vetal:vetal@192.168.71.101:2221 /home/vitaliy/ftp_phone/
```

Then I cloned (2) a sample repository to mounted folder, unmounted volume and then mounted it again (to prevent caching).

Opened terminal (3), navigated to `/home/vitaliy/ftp_phone/recommended-extensions-sample` and launched VS Code with `code .`.

Opened extensions (4) view, ensured all the recommendations were displayed and waited for starting the installation.

At this step, all the extensions are expected to be installed.

**Comment by sandy081** [comment]
Recommendations are shown only if they are installable. Since the extensions you configured as recommendations are not installable in web, they are not shown in the recommendations.

Can you please file a separate issue for extensions being stuck in installed phase. Please share following log in that issue:
F1 > Open View... > Shared
F1 > Open View... > Window

**Comment by vitaliy-guliy** [comment]
@sandy081 I found the VS Code on https://vscode.dev does not allow me to open a terminal while I can do everything I want on GitHub Codespaces (including installing the extensions from the sample above).

Do we consider https://vscode.dev as a working environment, or is it used mostly to demonstrate the web-based editor capabilities?

**Comment by sandy081** [comment]
It is a light weight web based editor without backed by any machine like in codespaces. Hence you cannot access features like terminal which require a machine.
