### ISSUE TITLE
run task in `command prompt` not work

### ISSUE THREAD

**Issue by WittonBell** [microsoft/vscode#195446]
Type: <b>Bug</b>

1.set VSCode default terminal is `command prompt`
`settings.json` configuration is:
```
"terminal.integrated.profiles.windows": {
    "PowerShell": {
      "source": "PowerShell",
      "icon": "terminal-powershell"
    },
    "Command Prompt": {
      "path": [
        "${env:windir}\\Sysnative\\cmd.exe",
        "${env:windir}\\System32\\cmd.exe"
      ],
      "args": ["/K chcp 65001 >nul"],
      "icon": "terminal-cmd"
    },
  },
  "terminal.integrated.defaultProfile.windows": "Command Prompt",
```
2.use default `tasks.json` to run task
```
{
	"version": "2.0.0",
	"tasks": [
		{
			"label": "echo",
			"type": "shell",
			"command": "echo Hello"
		}
	]
}
```
VSCode will report:
```
 *  正在执行任务: echo Hello 

参数格式不正确 - /d
```

execute cmd is: `C:\Windows\System32\cmd.exe '/K chcp 65001 >nul /d /c echo Hello'`

I found `"args": ["/K chcp 65001 >nul"]` conflict, but I remember it did work this way before.

VS Code version: Code 1.83.1 (f1b07bd25dfad64b0167beb15359ae573aecd2cc, 2023-10-10T23:48:05.904Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz (16 x 2496)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|23.87GB (8.63GB free)|
|Process Argv|D:\\net_dxs\\erlang\\hello --crash-reporter-id 64efb1b3-5f56-4252-955c-739cf30be5b5|
|Screen Reader|no|
|VM|67%|
</details><details><summary>Extensions (47)</summary>

Extension|Author (truncated)|Version
---|---|---
lua-debug|act|2.0.2
vscode-eslint|dba|2.4.2
EditorConfig|Edi|0.16.4
prettier-vscode|esb|10.1.0
code-runner|for|0.12.1
go|gol|0.39.1
headwind|hey|1.7.0
ts-debug|kak|0.0.6
i18n-ally|lok|2.12.0
mesonbuild|mes|1.12.1
dotenv|mik|1.0.1
vscode-less|mrm|0.6.3
vscode-docker|ms-|1.26.1
vscode-language-pack-zh-hans|MS-|1.83.2023101109
vscode-dotnet-runtime|ms-|1.8.1
vscode-edge-devtools|ms-|2.1.3
isort|ms-|2023.10.1
python|ms-|2023.18.0
vscode-pylance|ms-|2023.10.20
jupyter|ms-|2023.9.1102792234
jupyter-keymap|ms-|1.1.2
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-slideshow|ms-|0.1.5
remote-containers|ms-|0.315.1
remote-ssh|ms-|0.106.5
remote-ssh-edit|ms-|0.86.0
vscode-remote-extensionpack|ms-|0.24.0
cmake-tools|ms-|1.15.31
cpptools|ms-|1.17.5
cpptools-extension-pack|ms-|1.3.0
hexeditor|ms-|1.9.12
makefile-tools|ms-|0.7.0
remote-explorer|ms-|0.4.1
remote-server|ms-|1.4.3
vs-keybindings|ms-|0.2.1
proto|pet|0.0.4
erlang|pgo|0.9.7
nas-vscode|rig|0.0.1
vscode-stylelint|sty|1.2.4
lua|sum|3.7.0
vscode-md|Tob|0.6.2
cmake|twx|0.0.17
vscode-lldb|vad|1.10.0
volar|Vue|1.8.19
vscode-typescript-vue-plugin|Vue|1.8.19
php-debug|xde|1.33.0
php-intellisense|zob|1.3.3

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
py29gd2263:30856252
3ch9d444:30846783
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
282f8724:30602487
f6dab269:30613381
showlangstatbar:30737416
pythonfmttext:30731395
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
pythonnosmt12:30797651
pythonidxptcf:30805731
pythonnoceb:30805159
dsvsc013:30795093
dsvsc014:30804076
diffeditorv2:30821572
dsvsc015:30845448
pyreplss1:30858575

```

</details>

**Comment by meganrogge** [comment]
i'm confused - what is the issue?

**Comment by WittonBell** [comment]
sorry, it's maybe my mistake.
