### ISSUE TITLE
Comment does not preserve collapsed state

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#195459]
1. Have a PR in review
2. Open the PR in VS Code. Notice expanded comment. Collapse it
3. Open another editor. Go back to previous editor
4. Comment is expanded 🐛 

https://github.com/microsoft/vscode/assets/1926584/c36812e0-46fb-4f5d-aa18-b3a6957d2214

**Comment by alexr00** [comment]
It's re-expanding because there's content in the reply input box. Do you expect that the content of the reply input box is cleared when you manually collapse the comment thread?

**Comment by isidorn** [comment]
Ideally it is not cleared. It is just preserved there. Collapsing feels to me like a user signal this is no longer important. But if we can preserve the input to be potentially useful in the future then that sounds like the right thing to do.

And if it has content I do not think it should auto expand if I collapsed it.

**Comment by isidorn** [comment]
Thank you 🙏
