### ISSUE TITLE
[WelcomeUX] Copy `code-icon.svg` to near where it's used

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#19541]
- https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/walkThrough/electron-browser/walkThroughPart.css#L144
- https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/welcomePage/electron-browser/welcomePage.css#L263

The icon should be copied close to the CSS where it is being used, just like every icon and image we have.

The only reason this is working now is that @alexandrudima enabled SVG inlining *when* the SVG is small enough and the loader actually is able to escape the `vs` namespace during bundling.

**Comment by isidorn** [comment]
Removed candidate label since not user visible, up to Christof to decide wheather to fix today.

**Comment by chrmarti** [comment]
@alexandrudima @joaomoreno What is the size limit an SVG will be inlined? If this doesn't directly affect 1.9, I'll fix it for February.

**Comment by chrmarti** [comment]
Looks like the limit is 5k (3k for the editor), the files involved are below 1k (before minification). Moving to February.

**Comment by Tyriar** [comment]
Verified via code review
