### ISSUE TITLE
Hope to provide an interface to modify the status of the debugging suspension bar

### ISSUE THREAD

**Issue by Azurehuihui** [microsoft/vscode#195429]
Is it possible to provide an interface to modify the status of the debugging suspension bar, and to modify the highlighting and graying capabilities of run, single-step and other buttons?
![image](https://github.com/microsoft/vscode/assets/10072294/cc8462e0-048e-4e3a-ad24-265ca3e19fee) 

In certain scenarios, I hope that the run button can be grayed out, like the single-step run button.

**Comment by roblourens** [comment]
I don't understand what you're asking for
