### ISSUE TITLE
[Feature request] Silence option for "Are you sure" nag on delete.

### ISSUE THREAD

**Issue by rajinder-yadav** [Microsoft/vscode#19545]
- VSCode Version: Code 1.8.1 (ee428b0eead68bf0fb99ab5fdc4439be227b6281, 2016-12-19T14:41:20.664Z)
- OS Version: Linux x64 4.4.0-59-generic
- Extensions:

|Extension|Author|Version|
|---|---|---|
|vscode-markdownlint|DavidAnson|0.6.1|
|EditorConfig|EditorConfig|0.3.4|
|jslint|ajhyndman|1.2.1|
|jshint|dbaeumer|0.10.15|
|vscode-eslint|dbaeumer|1.2.2|
|tslint|eg2|0.8.1|
|cpptools|ms-vscode|0.10.0|
|Spell|seanmcbreen|0.9.1|
|vim|vscodevim|0.5.2|

---

I would like an option to silent the message, "Are you sure?" when I delete a file. Maybe add a checkbox for "Don't ask again."

![nag](https://cloud.githubusercontent.com/assets/439226/22397480/4596e724-e540-11e6-92f7-fb874cbaafeb.png)

Steps to Reproduce:

1. Select a file
2. Delete it

**Comment by cmodien** [comment]
+1

**Comment by hivaga** [comment]
+1 useless click

**Comment by King66** [comment]
need this, since we can get files back from trash..
just add a setting like promptOnDeleteFile: false

**Comment by emilas44** [comment]
Come on guys Please implement this...we need it!

**Comment by eric-parsons** [comment]
Agreed, this dialog is incredibly annoying. This is just flat out poor UX. Either prompt the user to confirm whether they really want to do something or (preferably) assume they know what they are doing and give them a way to undo it later if needed. But don't do *both*! That's just silly. The target audience here is developers who know how the trash/recycling bin works in their OS and should be using source control anyway as cmodien points out.

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/1538
