### ISSUE TITLE
Top activity bar isn't showing active item

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#195481]
Explorer focused:

![Image](https://github.com/microsoft/vscode/assets/2193314/0b970c74-d08b-4837-8942-34f3e795c650)

It's only working for debug:

![Image](https://github.com/microsoft/vscode/assets/2193314/a6ab8754-a9de-4a99-b7da-f11d93551a2b)

**Comment by sandy081** [comment]
It seems to working for me

<img width="370" alt="image" src="https://github.com/microsoft/vscode/assets/10746682/2bef6d70-2877-4221-b75a-dbdb82f5ccbc">

Do you have any special theme, or customisations or set up? Probably try trouble shooting?

**Comment by Tyriar** [comment]
Also the state can be frozen:

![image](https://github.com/microsoft/vscode/assets/2193314/1cf22535-fc71-4524-989e-c0098af7665f)
![image](https://github.com/microsoft/vscode/assets/2193314/7d4c4666-8de5-4620-ba5e-16e06988709f)

Same thing in dark modern.

No errors in console

**Comment by gjsjohnmurray** [comment]
Here's a repro that seems reliable:

1. Size the side bar narrow enough to make some of your activity icons get displaced into the ... menu.
2. Choose an option from that menu. Its icon appears and get selected with the underline correct.
3. Now drag that icon left to position it nearer the start of the set of tabs in order for it not to get displaced onto the ... menu again. It loses its underline and even when you switch to another icon and back to this one it doesn't get underlined.

**Comment by gjsjohnmurray** [comment]
To reset, move activity bar to side, then back to top again.

**Comment by Alecton4** [comment]
OFF TOPIC. May I ask how to move the activity bar from left to top? Tried searching for settings and Googling, but didn't get any results.

**Comment by Tyriar** [comment]
@Alecton4 if you're on the Insiders build you can right click the activity bar to change the position

**Comment by sandy081** [comment]
To verify:

- Move activity bar to top
- Reduce the width of sidebar so that activity bar actions are exactly fit
- Switch to Debug view container. All activity bar actions moved to overflow action
- From overflow action, select explorer
- Make sure explorer is shown active
