### ISSUE TITLE
Azure Functions Create in Python - Add Recommended Tag

### ISSUE THREAD

**Issue by shreyabatra4** [microsoft/vscode#195410]
For the workflow of creating a new Azure Function in VS Code using the v2 programming model for Python, add a 'Recommended' tag for the option of adding the new function to the main file.

![Screenshot 2023-10-11 at 3 59 07 PM](https://github.com/microsoft/vscode/assets/93732571/e887014f-d62b-47db-aa31-c30bee02598a)

**Comment by mjbvz** [comment]
Please file this against the azure functions extension
