### ISSUE TITLE
Resolve conversation should auto collapse the comment

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#195461]
Have a PR in review. Have some comments. Click on Resolve Conversastion. It should be auto collapsed. The current way I have to do two clicks instead of one.

**Comment by isidorn** [comment]
It is `comments.collapseOnResolve: true`
Which seems to be the default. Which makes sense.

Just curious, is there folk who do not want to collapse on resolve?

**Comment by alexr00** [comment]
It is new behavior added last month, so I wanted to give users a way out of it if they didn't like it. I don't know if there's anyone who doesn't want to collapse on resolve.

**Comment by isidorn** [comment]
Sorry for the slow response. No, nothing special in my setup. I was just reacting on reviews on this PR https://github.com/microsoft/vscode/pull/195377

Unfortunately I am no longer in this state. Is there something I can provide. Or what should I do the next time I see this? Thanks

**Comment by alexr00** [comment]
Errors from the dev console would be helpful if you see this again!
