### ISSUE TITLE
`code` CLI opens wrong files with `-g` option when spaces in the file path

### ISSUE THREAD

**Issue by imbant** [microsoft/vscode#195443]
Does this issue occur when all extensions are disabled?: Yes

## Environment
Version: 1.82.1 (user setup)
Commit: 6509174151d557a81c9d0b5f8a5a1e9274db5585
Date: 2023-09-08T08:45:05.575Z
Electron: 25.8.0
ElectronBuildId: 23503258
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.19045

### with white space
![code](https://github.com/microsoft/vscode/assets/17983739/8060df72-d331-4ff0-ad39-03476d7cbe2c)

### without white space
![code2](https://github.com/microsoft/vscode/assets/17983739/9d005b20-9e42-4697-b862-185196a1f460)

1. It's about `code` CLI, not the command-line tools inside VS Code
2. Open a folder with spaces in the path. It works well
3. Then use `-g` or `--goto` option to goto a file inside. Just open a new temporary file, even can not open the folder

If there is **no white space**, it works **as expected**

## Details

I tried to wrap the path with `"`, and escape white spaces with `\`. Still does't work.

**Comment by imbant** [comment]
Same thing in 1.83.1

Version: 1.83.1 (user setup)
Commit: f1b07bd25dfad64b0167beb15359ae573aecd2cc
Date: 2023-10-10T23:48:05.904Z
Electron: 25.8.4
ElectronBuildId: 24154031
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.19045

**Comment by bpasero** [comment]
Can anyone else reproduce?

**Comment by bpasero** [comment]
@imbant I can reproduce now but think the issue is that you are using `\'` at the end of the first path. On Windows, this seems to escape the quote and as such, everything that comes after (`-g ...`) becomes part of the path to open. When you remove that trailing backslash, it should work.

**Comment by imbant** [comment]
@bpasero Thanks for your answer. I delete the `\'` at the end of the path and it works as expected. I also tried move `-g ...` to the front of the first path and also works. 

It's just a little weird...is this a bug?

**Comment by bpasero** [comment]
The theory here is that powershell eventually calls our `code.cmd` which is interpreted by Windows command prompt where when you have `\"` or `\'`, you get the escaping.

I do not have a good answer here if we can address it, I believe we cannot.

**Comment by imbant** [comment]
@bpasero I got it. It doesn't affect my coding so I can accept the usage.

BTW, I have another question. Would you please tell me if the `code.cmd` you referred is [this file in vscode repo](https://github.com/microsoft/vscode/blob/main/resources/win32/bin/code.cmd)?

Thanks for your time. I will close this issue.

**Comment by bpasero** [comment]
Yeah that is the file we put in the global path so that when you type `code` we have a program to launch.
