### ISSUE TITLE
Is there a place to reveal the minimum supported browser version?

### ISSUE THREAD

**Issue by yiliang114** [microsoft/vscode#195552]
A few months ago (I kind of forgot how long ago) vscode.dev can still be opened normally on chrome 90. However, the latest vscode.dev does not work properly in chrome 90 (it cannot be opened).  

Related issues:  
1. #189712

So I was wondering if it's possible to show some official minimum supported version in the about dialog?

In addition, I would like to know whether each update of the electron version means that the minimum supported chrome version of vscode will also be increased?  

Related issues:  
1. #188268

Version: 1.83.1
Commit: f1b07bd25dfad64b0167beb15359ae573aecd2cc
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36
Embedder: vscode.dev

**Comment by yiliang114** [comment]
Another question is, where can I find the minimum supported chrome version? Is it based on the chrome version based in the CI tool?  For example, the 114.0.5735.199 here

https://github.com/microsoft/vscode/blob/1d7e01874fe0ad15e9dfc73f97eea9fa929fdd56/build/azure-pipelines/linux/install.sh#L10

**Comment by jrieken** [comment]
I don't believe it is formalised but rule of thumb: only latest and greatest is supported, definitely not something as old as Chrome 90 (118 is latest) but often N-1 or N-2 is OK. 

A good indication is the version of playwright that we are using. The browser versions it comes with is what our tests assume exists. Check [this file](https://github.com/microsoft/vscode/blob/58bdf2c7c40be6f4494ae35a09528708832cf357/package.json) at `devDependencies/@playwright/test`

**Comment by jrieken** [comment]
Passing on to @bamurtaugh for a formalised answer or for some other doc pointer

**Comment by bamurtaugh** [comment]
Thanks @jrieken, what you shared is my understanding too (we only guarantee support of the latest and greatest). I think we could express that more clearly in docs (and add the info you mentioned on Playwright version, that's a great idea), so opened a small docs PR: https://github.com/microsoft/vscode-docs/pull/6755
