### ISSUE TITLE
Add helper text to conditional breakpoint window that explains how to commit or cancel

### ISSUE THREAD

**Issue by stevencl** [Microsoft/vscode#1955]
As we discussed last week we should add helper text that explains how to commit or cancel changes made to the expression inside the conditional  breakpoint window.
For example: 'Press enter to commit the changes, Esc to cancel'
We may need to think more about how we represent uncommitted changes. Perhaps an expression that has been committed is shown in bold?

**Comment by isidorn** [comment]
This has been done. Suggestions on the wording are welcome
![screen shot 2016-01-12 at 17 33 16](https://cloud.githubusercontent.com/assets/1926584/12269614/971d1ebc-b952-11e5-9fd9-311aff785776.png)
