### ISSUE TITLE
`[object Object]` in Settings Sync

### ISSUE THREAD

**Issue by chrisdias** [microsoft/vscode#195518]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 
```
Version: 1.84.0-insider (user setup)
Commit: 9bb94efbe279580856897b63cc9417a3e875e405
Date: 2023-10-12T16:59:43.701Z
Electron: 25.8.4
ElectronBuildId: 24154031
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.23560
```
- OS Version: 
```
OS: Windows_NT x64 10.0.23560
```

Getting `[object Object]` when clicking on `Settings Sync is On` 

Steps to Reproduce:

1. Turn on Settings Sync Insiders
2. On gear, click on `Settings Sync is On`

Result: Quick Pick

![Image](https://github.com/microsoft/vscode/assets/1487073/f2008fa2-474e-41aa-a311-041482dafbc1)

I dont see anything in the devtools...

**Comment by sandy081** [comment]
@TylerLeonhardt Is this related to your recent NLS changes?
