### ISSUE TITLE
settings.json use variables from environment

### ISSUE THREAD

**Issue by Kurt-Shiwz** [microsoft/vscode#195545]
- VS Code Version: 1.83.1 (Universal)
- OS Version: macOs 14.0

Steps to Reproduce:

I have two Mac, one is Intel and the other is M1. When using vscode to sync settings, the locations of brew are different. For example, 
`go.goroot` is `/usr/local/opt/go/libexec` on Intel chips and `/opt/homebrew/opt/go/libexec` on M1.
I try to make something like `go.goroot`: `${env:HOMEBREW_PREFIX}/opt/go/libexec`, which can auto matically be compatible with different chips. 
However,it seems that it is not supported.
But `go.toolsGopath` supports such as `/Users/${env:USER}/go` and `clang−format.executable` supports such as `{env.HOMEBREW_PREFIX}/bin/clang-format`. 
In the vscode  settings.json, is there a unified way to read variables from environment?  
Is each plug-in implemented by itself?

**Comment by rzhao271** [comment]
It's up to the extension to do variable substitution for each setting.
If this has to do with the Go extension, you can file an issue on their repository for that setting.
I'll label this issue as caused-by-extension for now.
