### ISSUE TITLE
Allow selectively silencing error codes when terminating console

### ISSUE THREAD

**Issue by aryzing** [microsoft/vscode#195507]
When closing the terminal with `ctrl-d`, an error popup appears saying the terminal was terminated with error code 130. That's great, but after having seen this message many times, it doesn't help anymore. Rather than [silencing all terminal errors](https://github.com/microsoft/vscode/issues/106555#issuecomment-692014412), would it be possible to just silence particular error codes?

**Comment by meganrogge** [comment]
as indicated in the linked issue, we cannot do this.

**Comment by aryzing** [comment]
Thanks for letting me know. Seems the issue wasn't clear about what is possible. This next segment,

> I don't know how you can disable this on the shell side

makes it seem that perhaps something can be done on the VS Code side instead? In any case, disabling all error alerts can help keep the noise down.
