### ISSUE TITLE
Code Hot Swap not working for last 3 upgrades

### ISSUE THREAD

**Issue by arnjmllr** [microsoft/vscode#195520]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 
- OS Version: 
Version: 1.83.1 (user setup)
Commit: f1b07bd25dfad64b0167beb15359ae573aecd2cc
Date: 2023-10-10T23:48:05.904Z
Electron: 25.8.4
ElectronBuildId: 24154031
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.22621

Steps to Reproduce:

1.  write code
2.  make changes to code. 
3.  attempt to set break points
4.  attempt to debug code.

I have to stop running code, recompile and start debugger again .

**Comment by roblourens** [comment]
Please file an issue on whatever debug extension you're using
