### ISSUE TITLE
Setting locals to object literals fails

### ISSUE THREAD

**Issue by mousetraps** [Microsoft/vscode#19553]
_From @adelphes in #19494_ 
- VSCode Version: 1.8.1
- OS Version: Ubuntu 16, Linux x64
- Node: 6.5.0

On a related note, setting locals to object literals fails - they can only be set to primitives, strings or array literals. What's more annoying is that if you set a local to an array literal, you can't set it back! (because it becomes expandable).

**Comment by mousetraps** [comment]
Also related: https://github.com/Microsoft/vscode/issues/13969

I can reproduce the issue on Windows in the latest Insiders builds. Using the following code
```js
var a = 3;
console.log('hi');
```

Stop at the `console.log` statement, try to set `a` to `[ ]` in the locals window - it works. Trying to set `a` to `{ }` fails.

**Comment by weinand** [comment]
@isidorn this is a regression: in 1.7.2 it was possible to set a scalar to an array and back to a scalar.

**Comment by isidorn** [comment]
@weinand do you think this should be candidate since it is a regression?
This feature is not very user visible so I think it might be fine to ship without fixing it. Though we can also fix it if you prefer that.

**Comment by weinand** [comment]
Since this has not regressed in this milestone, it is not a candidate for January.

**Comment by isidorn** [comment]
This issue is about setting a local variable to an object `{}`, and as @mousetraps points out this fails - node debug returns 'undefined' as a value and this is shown in the UI. Thus forwarding to @weinand 

As for 'Set Value' is missing on structured variables - that is captured by #19494
