### ISSUE TITLE
Error: "link failed but did not provide an info log" on Ubuntu 20.04, VS Code Version 1.83.1

### ISSUE THREAD

**Issue by robrown** [microsoft/vscode#195502]
Does this issue occur when all extensions are disabled?: Yes
- VS Code Version: 1.83.1
- OS Version: Ubuntu 20.04

Steps to Reproduce:
1. Open Visual Studio Code.
![image](https://github.com/microsoft/vscode/assets/4173719/2bf9d008-12ba-4f28-86a4-613a299eb97f)
2. This is how visual studio code looks
3. Running the code --verbose command I get the following result
// Vertex SKSL
#extension GL_NV_shader_noperspective_interpolation: require
uniform float4 sk_RTAdjust;in float2 position;in half4 color;flat out half4 vcolor_S0;void main() {// Primitive Processor QuadPerEdgeAAGeometryProcessor
vcolor_S0 = color;sk_Position = position.xy01;}
// Fragment SKSL
#extension GL_NV_shader_noperspective_interpolation: require
flat in half4 vcolor_S0;void main() {// Stage 0, QuadPerEdgeAAGeometryProcessor
half4 outputColor_S0;outputColor_S0 = vcolor_S0;const half4 outputCoverage_S0 = half4(1);{ // Xfer Processor: Porter Duff
sk_FragColor = outputColor_S0 * outputCoverage_S0;}}
// Vertex GLSL
#version 300 es

#extension GL_NV_shader_noperspective_interpolation : require
precision mediump float;
precision mediump sampler2D;
uniform highp vec4 sk_RTAdjust;
in highp vec2 position;
in mediump vec4 color;
flat out mediump vec4 vcolor_S0;
void main() {
    vcolor_S0 = color;
    gl_Position = vec4(position, 0.0, 1.0);
    gl_Position = vec4(gl_Position.xy * sk_RTAdjust.xz + gl_Position.ww * sk_RTAdjust.yw, 0.0, gl_Position.w);
}

// Fragment GLSL
#version 300 es

#extension GL_NV_shader_noperspective_interpolation : require
precision mediump float;
precision mediump sampler2D;
out mediump vec4 sk_FragColor;
flat in mediump vec4 vcolor_S0;
void main() {
    mediump vec4 outputColor_S0;
    outputColor_S0 = vcolor_S0;
    {
        sk_FragColor = outputColor_S0;
    }
}

Errors:
link failed but did not provide an info log
[81471:1012/122040.002193:WARNING:angle_platform_impl.cc(48)] ProgramGL.cpp:989 (checkLinkStatus): Program link or binary loading failed with no info log.
[81471:1012/122040.002594:ERROR:shared_context_state.cc(81)] Skia shader compilation error

**Comment by jqhu27** [comment]
I'm experiencing the same problem, and reinstalling the software didn't resolve the issue.

**Comment by DerNils-git** [comment]
I experience the same problem on OpenSuse Tumbleweed.

VS Code Version: 1.83.1
OS Version: OpenSuse Tumbleweed ID:20231011

```
nils@laptop &> ./code --verbose --disable-extensions
<...>
Errors:
link failed but did not provide an info log
[6056:1013/091240.276752:WARNING:angle_platform_impl.cc(48)] ProgramGL.cpp:989 (checkLinkStatus): Program link or binary loading failed with no info log.
[6056:1013/091240.276901:ERROR:shared_context_state.cc(81)] Skia shader compilation error
```

**Comment by TheRealBecks** [comment]
*Solution*

Delete the `GPUCache` folder:
```
rm -r ~/.config/Code/GPUCache/
```

I found the solution [here](https://bbs.archlinux.org/viewtopic.php?id=285507), because there was also a rendering problem on Chromium some months ago.

**Comment by robrown** [comment]
> **Solution**
> 
> Delete the `GPUCache` folder:
> 
> ```
> rm -r ~/.config/Code/GPUCache/


This solution worked for me, thank you very much!
