### ISSUE TITLE
Remove Gear Icon for "Built-In" Extensions in the Extension Panel

### ISSUE THREAD

**Issue by rozzzly** [Microsoft/vscode#19554]
**VSCode Version**: Latest Nightly Build _(e68ab660a338a1ccefaa41a2fa010ebbfeeb8dba)_
**OS Version: OS**: Arch Linux _(Kernel: x86_64 Linux 4.9.6-1-ARCH)_

#### Steps to Reproduce:

1. Open extensions panel
2. Find extension marked as "built-in"
3. Click gear icon for that extension

#### Expected Behavior:
Some context menu appears. 

#### Actual Behavior:
Nothing happens. 

![Screen Grab](https://cloud.githubusercontent.com/assets/2515134/22400608/66d24958-e57f-11e6-830d-987024edf7b2.gif)

If you don't intend for users to be able to disable "built-in" extensions, then the gear icon serves no purpose. Therefor, I propose that it be hidden for "built-in" extensions.

> #### And if you're wondering why my editor's background is funky... It's not actually anything I've done to vscode. I run Arch Linux and have configured my window manager (compiz) to make the vscode window like 20% transparent. The design you're seeing is my desktop wallpaper. I've made no changes to vscode, so this behavior should be present on everybody else's machines too.

**Comment by mousetraps** [comment]
@rozzzly Thanks for reporting! Agreed it would be good to remove this UI for built-in extensions until we actually add the ability to disable them - https://github.com/Microsoft/vscode/issues/17068
