### ISSUE TITLE
Internal rewrite of task definition causes task error

### ISSUE THREAD

**Issue by colin-grant-work** [microsoft/vscode#195584]
Does this issue occur when all extensions are disabled?: No: it's a bug in the API.

- VS Code Version: 1.83.1
- OS Version: Windows 10

Steps to Reproduce:

1. Run any shell task using the `vscode.tasks.executeTask(new vscode.Task(...))` API.
2. For example, starting from the `yo code` basic template, modify the source code to look something like this:
```typescript
import * as vscode from 'vscode';

export function activate(context: vscode.ExtensionContext) {
	let disposable = vscode.commands.registerCommand('task-error-demo.helloWorld', () => {
		const command = 'echo';
		const args = ["Hello, World!"];
		const originalDefinition = { type: 'shell', command, args, label: 'Hello World' };
		const task = new vscode.Task(
			originalDefinition,
			vscode.TaskScope.Global,
			'Hello World',
			'task-error-demo',
			new vscode.ShellExecution(command, args),
			[]
		);
		// task.definition = originalDefinition; // This removes the error but seems a bit silly.
		vscode.tasks.executeTask(task);
	});

	context.subscriptions.push(disposable);
}

export function deactivate() { }
```
2. Run the command.
3. See the task execute.
4. Open the Tasks output channel
5. See something like this:

```
Error: the task 'task-error-demo: Hello World' neither specifies a command nor a dependsOn property. The task will be ignored. Its definition is:
{
    "type": "shell",
    "id": "shell,echo,Hello,, World!,",
    "problemMatcher": [],
    "label": "task-error-demo: Hello World"
}
```

The problem (if it is one) is that task definitions for the basic task types get rewritten:

https://github.com/microsoft/vscode/blob/c92dcc96b272a1624fa55fd8d7642e14f0df3070/src/vs/workbench/api/common/extHostTypes.ts#L2358-L2380

Since that rewrite effaces all the details of the original definition, when it is sent to the Main side, it falls afoul of these checks:

https://github.com/microsoft/vscode/blob/c92dcc96b272a1624fa55fd8d7642e14f0df3070/src/vs/workbench/contrib/tasks/common/taskConfiguration.ts#L1739-L1744

This doesn't have very dramatic consequences: mainly the task can't be rerun from the `task ` quick input or other task access mechanisms. But tasks of types other than the basic types are able to be rerun, because this only happens certain task types:

https://github.com/microsoft/vscode/blob/c92dcc96b272a1624fa55fd8d7642e14f0df3070/src/vs/workbench/api/common/extHostTypes.ts#L2426-L2428

and only happens because the execution happens to be assigned later in the constructor than the definition:

https://github.com/microsoft/vscode/blob/c92dcc96b272a1624fa55fd8d7642e14f0df3070/src/vs/workbench/api/common/extHostTypes.ts#L2301-L2319

If the definition is set later (for example by adding a manual `task.definition = originalDefinition`), then the error doesn't occur.

**Comment by colin-grant-work** [comment]
@VSCodeTriageBot, thanks for the help, but this doesn't actually have to do with new code; it's an older problem. I just knew that otherwise, you'd tell me to try the latest :-).

**Comment by meganrogge** [comment]
this might be by design, i'd have to look into it more

**Comment by colin-grant-work** [comment]
It certainly seems like the rewrite is deliberate, and missing the ability to rerun the tasks probably isn't too bad, since if the plugin is running a task this way, then the user probably has some way to get the plugin to do it again without going through the application UI, but if it's intentional, then the error output seems to be incorrect, since everything is working as expected. It also interferes some other interactions with the task system and causes a toast saying, 'There are task errors. See the output for details.' even if the actual action succeeded, so it ends up being a user-facing issue, as well.

**Comment by meganrogge** [comment]
Sounds right to me, i'd accept a PR if you're interested to fix the discrepancy you've found

**Comment by colin-grant-work** [comment]
Never mind, I think that toast doesn't appear because of the error I'm reporting here, but only when there's a task in the history without a resolver among the currently installed plugins. That's probably separate.

**Comment by meganrogge** [comment]
ok, so seems like this can be closed

**Comment by colin-grant-work** [comment]
@meganrogge, the original report still stands: the plugin API is doing something that causes the main-side code to report an error. Only this comment does not apply:

> It also interferes some other interactions with the task system and causes a toast saying, 'There are task errors. See the output for details.'
