### ISSUE TITLE
Aux window terminals offset mouse event coordinates when used on a different monitor

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#195577]
Repro:

1. 2 monitors each with different OS scaling
2. Open terminal editor
3. Pop out
4. Try select, 🐛 it's offset strangely

This is likely xterm.js' caching of `devicePixelRatio` not being multi-window/monitor aware

**Comment by Tyriar** [comment]
This never gets hit when changing monitors:

https://github.com/xtermjs/xterm.js/blob/4245283e051f7b838d85df99eabd55e324919c2a/addons/xterm-addon-webgl/src/WebglRenderer.ts#L154-L161

**Comment by MrYuto** [comment]
It seems that this issue also occurs when using a split view sash:

![Code_a96V27VSvO](https://github.com/microsoft/vscode/assets/75252297/c55254f0-6fe5-4f53-a259-e55d1e6dc8ce)
