### ISSUE TITLE
Loop in powershell terminal 

### ISSUE THREAD

**Issue by DANIELNAHUN** [microsoft/vscode#195523]
Type: <b>Bug</b>

I open Visual Studio Code and the Powershell terminal opens as if I pressed the Enter key repeatedly, I close the terminal, I open another and the same, if I open a Git terminal or some other, normal opens, but in the PowerShell terminal I present this loop

VS Code version: Code 1.83.1 (f1b07bd25dfad64b0167beb15359ae573aecd2cc, 2023-10-10T23:48:05.904Z)
OS version: Windows_NT x64 10.0.19044
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|7.92GB (2.14GB free)|
|Process Argv|--crash-reporter-id f22fc72e-91f6-4363-aaca-1dfc38f84af8|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (29)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-mysql-client2|cwe|6.7.7
vue-peek|dar|1.0.2
vscode-eslint|dba|2.4.2
prettier-vscode|esb|10.1.0
figma-vscode-extension|fig|0.2.7
auto-rename-tag|for|0.1.10
gc-excelviewer|Gra|4.2.58
autopreviewer|jaw|0.6.0
ftp-sync|luk|0.3.9
vscode-docker|ms-|1.26.1
vscode-language-pack-es|MS-|1.83.2023101109
black-formatter|ms-|2023.4.1
isort|ms-|2023.10.1
python|ms-|2023.18.0
vscode-pylance|ms-|2023.10.20
jupyter|ms-|2023.9.1102792234
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.17
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-slideshow|ms-|0.1.5
remote-wsl|ms-|0.81.8
live-server|ms-|0.4.11
live-server-preview|neg|0.1.4
vetur|oct|0.37.3
material-icon-theme|PKi|4.31.0
LiveServer|rit|5.7.9
vue-vscode-snippets|sdr|3.1.1
es6-string-html|Tob|2.12.1
volar|Vue|1.8.19

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
py29gd2263cf:30856253
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
2e4cg342:30602488
89544117:30613380
showlangstatbar:30737416
a2ce3375:30757347
pythonfmttext:30731395
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
pythonnosmt12:30797651
pythonidxptcf:30805731
pythonnoceb:30805159
copilotsettingc:30859502
synctok:30821570
dsvsc013:30795093
dsvsc014:30804076
diffeditorv2:30821572
dsvsc015:30845448
pythonregdiagcf:30859692
pyreplss1:30858575

```

</details>

**Comment by meganrogge** [comment]
Please provide [a gif](https://gifcap.dev/) illustrating the problem (attaching images won't work via email, you need to go to github.com). See [this wiki page](https://github.com/microsoft/vscode/wiki/Terminal-Issues) for more general info on how to report actionable terminal issues.
/label info-needed terminal

**Comment by DANIELNAHUN** [comment]
sorry, here is the gift

![2023-10-14-06-48-26](https://github.com/microsoft/vscode/assets/58575264/fafccf91-44f4-4731-a76d-d867a18378ff)

**Comment by DANIELNAHUN** [comment]
Sorry for the delay, I was traveling, no errors appear on the console
![image](https://github.com/microsoft/vscode/assets/58575264/0882ba0f-8552-4a7a-91b8-1846d1c763d2)

**Comment by meganrogge** [comment]
what happens if you disable all extensions?
