### ISSUE TITLE
"Follow link" not working

### ISSUE THREAD

**Issue by mavigozler** [microsoft/vscode#195514]
Type: <b>Bug</b>

1. Open an editor to a `tsconfig.json` file, or create a file accordingly.
2. Create a `files` property according to schema
3. Also include a `include` property that will include any file referenced in `files` (just in case, seen recommended by an A.I. agent)
4. In the `files` array, enter a few strings that are the absolute (full) paths.
5. The intellisense feature should create a clickable link and underline the text that represents a URI designator (file, URL, whatever), irrespective of whether it checks or confirms the existence of that resource. Hover the pointing device cursor to see a "Follow link" pop up, then click to follow (might have to press a modifier key like "Ctrl").
6. A dialog will open, "Unable to open..." even though you have verified the existence of the file. Note this may not be true for URL ("https://" protocol-specified), as they may open. Enter seveal strings to the array to show that existing paths are not being opened.

The expected case is for a file whose existence is checked several times will open to an editor. In an attached image, I show the path in the VS Code editor with the file, and in the File Explorer window, I show the breadcrumb path to a file. I have also verified using the Property page in Explorer.

![image](https://github.com/microsoft/vscode/assets/49463960/2dca3f35-7bb7-40b3-af73-1346737c941f)

![image](https://github.com/microsoft/vscode/assets/49463960/6e032c85-e57b-4a28-b588-b8a3279bb11b)

I have verified with this several entries in `files` and with shorter paths and using the "C:\" drive as well. I have used a single forward slash and doubled backward slashes for the path separator, no error shown by VS Code editor

VS Code version: Code 1.83.1 (f1b07bd25dfad64b0167beb15359ae573aecd2cc, 2023-10-10T23:48:05.904Z)
OS version: Windows_NT x64 10.0.22621
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-1035G1 CPU @ 1.00GHz (8 x 1190)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|11.82GB (3.14GB free)|
|Process Argv|--crash-reporter-id 72770bc9-9704-4ad5-8690-6709345d0a89|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (39)</summary>

Extension|Author (truncated)|Version
---|---|---
chrome-extension-developer-tools|aar|2.0.4
better-comments|aar|3.0.2
project-manager|ale|12.7.0
npm-intellisense|chr|1.4.5
gitignore|cod|0.9.0
vscode-markdownlint|Dav|0.52.0
vscode-eslint|dba|2.4.2
githistory|don|0.6.20
gitlens|eam|14.3.0
vscode-html-css|ecm|1.13.1
EditorConfig|Edi|0.16.4
code-runner|for|0.12.1
vscode-pull-request-github|Git|0.74.0
ftp-simple|hum|0.7.6
compareit|in4|0.0.2
start-git-bash|McC|1.2.1
vscode-language-babel|mgm|0.0.40
git-graph|mhu|1.30.0
vscode-docker|ms-|1.26.1
csharp|ms-|2.6.24
vscode-dotnet-runtime|ms-|1.8.1
vscode-edge-devtools|ms-|2.1.3
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-slideshow|ms-|0.1.5
remote-containers|ms-|0.315.1
cmake-tools|ms-|1.15.31
notepadplusplus-keybindings|ms-|1.0.7
powershell|ms-|2023.8.0
debugger-for-edge|msj|1.0.15
deepdark-material|Nim|3.3.1
vscode-jest|Ort|5.2.3
binary-viewer|Qia|1.1.1
LiveServer|rit|5.7.9
cmake|twx|0.0.17
errorlens|use|3.14.0
vscode-icons|vsc|12.5.0
vscode-todo-highlight|way|1.0.5
markdown-all-in-one|yzh|3.5.1
vscode-open-in-github|ziy|1.3.6

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
py29gd2263:30856252
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
3biah626:30602489
f6dab269:30613381
showlangstatbar:30737416
0bi6i642:30841073
03d35959:30757346
pythonfmttext:30731395
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
pythonnosmt12:30797651
pythonidxpt:30805730
pythonnoceb:30805159
copilotsettingc:30839828
dsvsc013:30795093
dsvsc014:30804076
diffeditorv2:30821572
dsvsc015:30845448

```

</details>

**Comment by dawitamene** [comment]
I couldn't reproduce it on Linux. Am I missing something, or is this a Windows-only issue?
