### ISSUE TITLE
wrong icon on the sidebar

### ISSUE THREAD

**Issue by 401819111** [microsoft/vscode#195689]
Type: <b>Bug</b>

i have two Source code manager icon on my sidebar,But one of the functions is search,i wanna get it back

VS Code version: Code 1.83.1 (f1b07bd25dfad64b0167beb15359ae573aecd2cc, 2023-10-10T23:48:05.904Z)
OS version: Windows_NT x64 10.0.22621
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 7840HS with Radeon 780M Graphics    (16 x 3793)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|27.69GB (16.16GB free)|
|Process Argv|--crash-reporter-id e8be7cd6-8965-4c82-897e-3e62bf4b0b49|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (48)</summary>

Extension|Author (truncated)|Version
---|---|---
nodejs-bundle|1Yi|1.0.0
better-comments|aar|3.0.2
vscode-css-formatter|aes|1.0.2
increment-selection|alb|0.2.0
vscode-tailwindcss|bra|0.10.1
chinese-clorem|cat|0.0.2
path-intellisense|chr|2.8.5
EnglishChineseDictionary|Cod|1.1.0
vscode-markdownlint|Dav|0.52.0
vscode-eslint|dba|2.4.2
githistory|don|0.6.20
xml|Dot|2.5.1
es7-react-js-snippets|dsz|4.4.3
gitlens|eam|14.4.0
EditorConfig|Edi|0.16.4
vsc-material-theme-icons|equ|3.1.4
prettier-vscode|esb|10.1.0
auto-close-tag|for|0.5.14
auto-rename-tag|for|0.1.10
shell-format|fox|7.2.5
json2ts|Gre|0.0.6
todo-tree|Gru|0.0.226
vue-snippets|hol|1.0.4
lorem-picsum-photos-snippets|hua|1.0.26
output-colorizer|IBM|0.1.2
comment-translate|int|2.3.2
easy-icons|jam|0.3.1
svg|joc|1.5.3
code-beautifier|mic|2.3.3
fluent-icons|mig|0.0.18
dotenv|mik|1.0.1
vscode-scss|mrm|0.10.0
vscode-language-pack-zh-hans|MS-|1.83.2023101109
python|ms-|2023.18.0
color-highlight|nau|2.5.0
indent-rainbow|ode|8.3.1
vscode-css-peek|pra|4.4.1
git-commit-plugin|red|1.2.1
vs-code-prettier-eslint|rve|5.1.0
firacode|Sey|2.2.1
markdown-preview-enhanced|shd|0.8.7
vscode-standard|sta|2.1.3
vscode-typescript-vue-plugin|Vue|1.8.19
vscode-import-cost|wix|3.3.0
vscode-surround|yat|1.5.0
vuter|yoy|0.1.2
markdown-all-in-one|yzh|3.5.1
material-theme|zhu|3.16.2

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263cf:30335440
vscorecescf:30445987
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
py29gd2263:30856252
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
2e4cg342:30602488
89544117:30613380
2i9eh265:30646982
showlangstatbar:30737416
962ge761:30841074
pythonfmttext:30731395
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
pythonnosmt12:30797651
pythonidxpt:30805730
pythonnoceb:30805159
dsvsc013:30795093
dsvsc014:30804076
diffeditorv1:30821571
dsvsc015:30845448
pythonregdiag:30859691
pyreplss1:30858575

```

</details>
![image](https://github.com/microsoft/vscode/assets/24718528/a137ed2b-7063-442f-b35f-6db1cea4ecb8)

**Comment by gjsjohnmurray** [comment]
I suggest you run the `Reset View Locations` command from the Command Palette.
