### ISSUE TITLE
The list of terminals

### ISSUE THREAD

**Issue by MendeIT** [microsoft/vscode#195628]
Type: <b>Bug</b>

Good afternoon!
The list of terminals is not displayed correctly!
Previously located on the far right side, it is now located behind the terminal window. It is not clear what terminal you are working with and how many terminals are running.

VS Code version: Code 1.83.1 (f1b07bd25dfad64b0167beb15359ae573aecd2cc, 2023-10-10T23:48:05.904Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz (8 x 2304)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.80GB (6.22GB free)|
|Process Argv|--crash-reporter-id 1efc4607-d462-407e-b48b-61c6b5addaac|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (27)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-django|bat|1.14.0
python-snippets|cst|0.1.2
githistory|don|0.6.20
vscode-html-css|ecm|1.13.1
copilot|Git|1.126.0
copilot-chat|Git|0.8.0
rest-client|hum|0.25.1
vscode-django-support|jun|1.0.26
kubernetes-yaml-formatter|ken|1.1.0
vscode-docker|ms-|1.26.1
vscode-language-pack-ru|MS-|1.83.2023101109
flake8|ms-|2023.8.0
isort|ms-|2023.10.1
python|ms-|2023.18.0
vscode-pylance|ms-|2023.10.21
jupyter|ms-|2023.9.1102792234
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.17
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-slideshow|ms-|0.1.5
remote-ssh-edit|ms-|0.86.0
remote-wsl|ms-|0.81.8
vscode-remote-extensionpack|ms-|0.24.0
remote-explorer|ms-|0.4.1
remote-server|ms-|1.4.3
vscode-python-typehint|njq|1.5.1
sqlite-viewer|qwt|0.3.13

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
py29gd2263cf:30856253
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
282f8724:30602487
89544117:30613380
2i9eh265:30646982
showlangstatbar:30737416
962ge761:30841074
pythonfmttext:30731395
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
pythonnosmt12:30797651
pythonidxptcf:30805731
pythonnoceb:30805159
asynctok:30821568
dsvsc013:30795093
dsvsc014:30804076
diffeditorv2:30821572
dsvsc015:30845448
pythonregdiagcf:30859692
pyreplss2:30858576
pythoncet00cf:30859750

```

</details>

**Comment by gjsjohnmurray** [comment]
Like in #195615?

If not, please paste a screenshot.

**Comment by MendeIT** [comment]
![image](https://github.com/microsoft/vscode/assets/122914060/45ffee74-53a4-4e16-9f4c-558adf8ac880)
@gjsjohnmurray

**Comment by MendeIT** [comment]
@gjsjohnmurray 
now works properly! thx
![image](https://github.com/microsoft/vscode/assets/122914060/991484a6-743f-42f3-8ffa-f5d676d5dbdf)
