### ISSUE TITLE
`Edit Condition...` on context menu of function breakpoint requires a second action

### ISSUE THREAD

**Issue by gjsjohnmurray** [microsoft/vscode#195696]
Type: <b>Bug</b>

1. Create a function breakpoint by using the `+` on the BREAKPOINTS view title.
2. Open the context menu of the new entry you created.
3. Choose `Edit Condition...`

:bug: a two-entry dropdown menu appears below the pencil icon on the function breakpoint's row, and you must select `Edit Condition..` again there before you get the inline UI for editing the condition.

VS Code version: Code - Insiders 1.84.0-insider (4678919d52909efc7c4ab958a2e5c8f45d50ffc3, 2023-10-13T05:34:13.175Z)
OS version: Windows_NT x64 10.0.22621
Modes:

**Comment by roblourens** [comment]
Need to do something here: https://github.com/microsoft/vscode/blob/358f15fb9bbcd59d83984d9ffca6fdbd82ea5866/src/vs/workbench/contrib/debug/browser/breakpointsView.ts#L1538-L1555

This shows the pencil with the two options, and also runs when picking "Edit Condition" from the context menu
