### ISSUE TITLE
after installing markdown pdf extension,my written md file is cleared

### ISSUE THREAD

**Issue by jiangqianyu** [microsoft/vscode#195614]
Type: <b>Bug</b>

i took hours writting a .md file.
i want to export as a pdf,so i install markdown pdf extension.
then,my written .md file is cleared,become 0KB.
i am so so sad.

VS Code version: Code 1.83.1 (f1b07bd25dfad64b0167beb15359ae573aecd2cc, 2023-10-10T23:48:05.904Z)
OS version: Windows_NT x64 10.0.22621
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 6800H with Radeon Graphics          (16 x 3194)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|13.69GB (2.14GB free)|
|Process Argv|--crash-reporter-id 05827a97-0c05-49d6-9361-6ca35fd2b210|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (25)</summary>

Extension|Author (truncated)|Version
---|---|---
aws-toolkit-vscode|ama|1.94.0
markdown-preview-github-styles|bie|2.0.3
prettier-vscode|esb|10.1.0
code-runner|for|0.12.1
copilot|Git|1.126.0
copilot-chat|Git|0.8.0
githd|hui|2.3.3
latex-workshop|Jam|9.14.1
vscode-gutter-preview|kis|0.30.0
black-formatter|ms-|2023.4.1
python|ms-|2023.18.0
vscode-pylance|ms-|2023.10.20
jupyter|ms-|2023.9.1102792234
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.17
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-slideshow|ms-|0.1.5
cmake-tools|ms-|1.15.31
cpptools|ms-|1.17.5
cpptools-extension-pack|ms-|1.3.0
cmake|twx|0.0.17
vscode-wakatime|Wak|24.2.3
vscode-todo-highlight|way|1.0.5
markdown-pdf|yza|1.5.0
markdown-all-in-one|yzh|3.5.1

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
py29gd2263cf:30856253
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
3biah626:30602489
f6dab269:30613381
vscrpc:30673769
showlangstatbar:30737416
03d35959:30757346
pythonfmttext:30731395
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
pythonnosmt12:30797651
pythonidxptcf:30805731
pythonnoceb:30805159
copilotsettingt:30859503
dsvsc013:30795093
dsvsc014:30804076
diffeditorv1:30821571
pythonmpsinfo:30842941
dsvsc015:30845448
pythonregdiag:30859691

```

</details>

**Comment by gjsjohnmurray** [comment]
When you open the empty file do any Local History entries show in the Timeline view, which is usually in the Explorer view container? If so, you may be able to recover the lost text.

I suggest you also report the problem to the extension author.

**Comment by mjbvz** [comment]
Please file this issue against the markdown pdf extension
