### ISSUE TITLE
Word Select: Treat newline as a word

### ISSUE THREAD

**Issue by JVimes** [microsoft/vscode#195631]
In VS, cursor movement-by-word treats newline as a word, which is handy. Suggest supporting that in VSCode.

When I started my selection with Ctrl, it's nicer to keep going than switch to Shift, and it matches my muscle memory better from many years in VS.

Here's an example:

### Current
(VSCode)

![2023-10-14_11h08_49](https://github.com/microsoft/vscode/assets/6148201/70db62c7-3f2e-4efa-8394-b99fbf9859f9)

### Suggested
(Visual Studio)

![2023-10-14_11h09_55](https://github.com/microsoft/vscode/assets/6148201/51ade133-4b0b-42c5-ac9f-0092ffb0cb51)

**Comment by TheBlckbird** [comment]
But why? Just press `Shift+Arrow`

**Comment by JVimes** [comment]
I should have specified, and given a better example. I'm often in the middle of a multi word selection with Ctrl. It's nicer to just keep going than to switch to Shift. I'll edit the post.

**Comment by JVimes** [comment]
I seem to have this fixed by changing key bindings.

```json
    {
        "key": "ctrl+right",
        "command": "cursorWordStartRight",
        "when": "textInputFocus"
    },
    {
        "key": "ctrl+shift+right",
        "command": "cursorWordStartRightSelect",
        "when": "textInputFocus"
    }
```
