### ISSUE TITLE
Double toolbar in search

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#195680]
* using today's insiders
* I have double titles and toolbars in search and SCM views (where I only have a single view)

<img width="688" alt="Screenshot 2023-10-16 at 11 13 13" src="https://github.com/microsoft/vscode/assets/1794099/cab61088-ffb6-49ad-b522-d301723fb2f4">

**Comment by sandy081** [comment]
To repro:

- Start with activity bar position on top, focus on search view
- Reload window
- Move activity bar to side
