### ISSUE TITLE
error when copying terminal

### ISSUE THREAD

**Issue by brerafael** [microsoft/vscode#195697]
Good morning guys. I am facing the error in my terminal in VS code that when I try to copy with the terminal with ctrl+c it ends my code and returns ^C. I've uninstalled and reinstalled but it doesn't change D:

**Comment by gjsjohnmurray** [comment]
This happens if the `terminal.integrated.sendKeybindingsToShell` setting has been set to `true`.

**Comment by brerafael** [comment]
How do I fix it?

**Comment by brerafael** [comment]
I'm new to this area and I'm learning

**Comment by gjsjohnmurray** [comment]
Please see https://code.visualstudio.com/docs/getstarted/settings

**Comment by brerafael** [comment]
Tks
