### ISSUE TITLE
Why "Error processing launch options at field: environment" ? (Windows)

### ISSUE THREAD

**Issue by lojian** [Microsoft/vscode#19565]
- VSCode Version: Code 1.8.1 (ee428b0eead68bf0fb99ab5fdc4439be227b6281, 2016-12-19T14:49:23.350Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

|Extension|Author|Version|
|---|---|---|
|python|donjayamanne|0.5.6|
|java-debug|DSnake|0.0.2|
|ftp-sync|lukasz-wronski|0.3.2|
|Go|lukehoban|0.6.52|
|cpptools|ms-vscode|0.10.0|
|java|redhat|0.0.9|
|RustyCode|saviorisdead|0.19.1|
|cmake|twxs|0.0.15|
|cmake-tools|vector-of-bool|0.9.0|

---

Steps to Reproduce:

1. I am debugging my program (which needs some environment variable setup before executing correctly)

Here is my launch.json

`{
    "version": "0.2.0",
    "configurations": [

        {
            "name": "C++ Launch (Windows)",
            "type": "cppvsdbg",
            "request": "launch",
            "program": "e:\\code\\prog1\\prog1.exe",
            "args": ["-v"],
            "stopAtEntry": false,
            "cwd": "e:\\code\\prog1\\",
            "environment": [
                {
                "Env1" : "Abc",
                "Env2" : "Cba",
                "Env3": "ccc"
                }   
            ],
            "externalConsole": false,
            "symbolSearchPath": "e:\\code\\prog1\\"
        },
        {
            "name": "C++ Attach (Windows)",
            "type": "cppvsdbg",
            "request": "attach",
            "processId": "${command.pickProcess}"
        }
    ]
}`
2. Always hitting "Error processing launch options at field: environment"?

I am running on Windows.

**Comment by bpasero** [comment]
This should probably be reported against the C++ extension.

**Comment by isidorn** [comment]
Please file this against the c++ extension here https://github.com/Microsoft/vscode-cpptools

**Comment by lojian** [comment]
thank you.
