### ISSUE TITLE
Code 1.83.1 rendering/graphical glitch (it works with --disable-gpu)

### ISSUE THREAD

**Issue by ryuzakyl** [microsoft/vscode#195629]
Type: <b>Bug</b>

Code fails to render properly:
![image](https://i.imgur.com/1Ny08DF.png)

One potential fix I've found is launching Code without GPU like: `code --disable-gpu` and everything renders perfectly.

**Expected result**:
Code renders flawlessly.

**VS Code version**: Code 1.83.1 (f1b07bd25dfad64b0167beb15359ae573aecd2cc, 2023-10-10T23:45:31.402Z)
**OS version**: Linux x64 6.5.4-76060504-generic

<details>

**System Info**:

|Item|Value|
|---|---|
|CPUs|13th Gen Intel(R) Core(TM) i7-1360P (16 x 1503)|
|GPU Status|2d_canvas: unavailable_software<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>opengl: disabled_off<br>rasterization: disabled_software<br>raw_draw: disabled_off_ok<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software<br>webgpu: disabled_off|
|Load (avg)|1, 1, 1|
|Memory (System)|62.64GB (50.67GB free)|
|Process Argv|--disable-gpu --crash-reporter-id 7a4b5d7b-9adb-44ff-a90a-901f1f359fa8|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|pop|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|pop|
|XDG_SESSION_TYPE|x11|

</details>

**Extensions**: none

**Comment by MCXFlow** [comment]
Maybe mesa problem

```shell
rm -r ~/.config/Code/GPUCache
```

Then restart your vscode

**Comment by MCXFlow** [comment]
https://github.com/microsoft/vscode/issues/190437

**Comment by ryuzakyl** [comment]
Thanks @MCXFlow!

I had found [https://github.com/microsoft/vscode/issues/190437](https://github.com/microsoft/vscode/issues/190437) when browsing the issues similar to mine. Your/this solution worked like a charm!

> Maybe mesa problem
> 
> ```shell
> rm -r ~/.config/Code/GPUCache
> ```
> 
> Then restart your vscode

Sorry I forgot to update/cancel the issue before.
Very grateful for all your help :wink: .
