### ISSUE TITLE
VS Code can't handle U+2028 in a JSON string

### ISSUE THREAD

**Issue by rmunn** [Microsoft/vscode#19568]
- VSCode Version: Version 1.8.1 (Commit ee428b0eead68bf0fb99ab5fdc4439be227b6281, Date `2016-12-19T14:41:20.664Z`, Shell 1.4.6, Renderer 53.0.2785.143, Node 6.5.0)
- OS Version: Ubuntu 14.04.5 LTS (Trusty)

## Steps to Reproduce

1. Go to the https://github.com/minimaxir/big-list-of-naughty-strings repo and download [`blns.json`](https://raw.githubusercontent.com/minimaxir/big-list-of-naughty-strings/8a115584931e0aef2965d8f2b6ab212a08a93a4c/blns.json).
2. Load that file into VS Code.
3. Look at line 96, which contains a U+2028 LINE SEPARATOR character near the end of the string.
4. The U+2028 character has been replaced by � (U+FFFD REPLACEMENT CHARACTER) visually. But if you copy and paste from that line, you still get the U+2028 character contained in the file; the replacement is only visual.
5. Line 96 has two wavy red lines indicating syntax errors in the JSON. The first one, to the left of the U+2028, reads "Unexpected end of string". The right one reads "Expected comma or closing bracket /
End of file expected". Neither error is correct; according to http://timelessrepo.com/json-isnt-a-javascript-subset, U+2028 is a perfectly valid character to embed in a JSON string and does not indicate the end of the string. (It is *not* a valid character in *Javascript* strings, though, which I suspect is the cause of VS Code's difficulty in dealing with this tricky string).

## Screenshots

Line 96 of the `blns.json` file:
![U+2028 part 1](https://cloud.githubusercontent.com/assets/90762/22411475/e58c3dd2-e6d6-11e6-8290-404ec75d643f.png)

First error message:
![U+2028 part 2](https://cloud.githubusercontent.com/assets/90762/22411514/3393a7ae-e6d7-11e6-8a22-9ebff0712f4a.png)

Second error message:
![U+2028 part 3](https://cloud.githubusercontent.com/assets/90762/22411523/58fdcf60-e6d7-11e6-911e-78f620ebf66c.png)

## Other VS Code versions

I happened to have an older version of the insiders' build lying around (Version 1.8.0-insider, Commit 2c8ab1a5ffc49ac26b2080bfbbbf9317fb8071bb), so I tested with it. While the U+2028 character is still replaced with U+FFFD visually in that version, commit 2c8ab1a5ffc49ac26b2080bfbbbf9317fb8071bb does *not* produce wavy red lines and error messages. (Which is the correct behavior since that string is valid JSON).

I then installed the latest (as of this writing) version of the insiders' build (Version 1.9.0-insider, Commit 3af0e9d6b79145011a7be3970c1d4b83d69b0443). This version DID exhibit the exact same bug as VS Code version 1.8.1: wavy red lines and the same two incorrect error messages.

**Comment by bpasero** [comment]
Not assuming this is an encoding issue, moving to Alex if this is just the editor not being able to display the character.

**Comment by rmunn** [comment]
The file was encoded in standard UTF-8 (without BOM).

**Comment by alexandrudima** [comment]
Regarding 4.
> The U+2028 character has been replaced by � (U+FFFD REPLACEMENT CHARACTER) visually. But if you copy and paste from that line, you still get the U+2028 character contained in the file; the replacement is only visual.

This is expected, when you copy code from the editor you get the exact string you copied. i.e. when you turn on render whitespace, copying to the clipboard will use spaces and tabs and not the visual replacement characters.

I think the only issue here is on the JSON language server that shows errors for a valid JSON string.
