### ISSUE TITLE
VS Codespaces not working

### ISSUE THREAD

**Issue by Muaz001** [microsoft/vscode#195619]
VS code spaces takes very long to load up. And then when it does and I start working, everything hangs, and it keeps showing me that its loading stuff. I've tried rebuilding, reloading, using different browsers with only 1 tab open. I've got a pretty decent PC and internet connection so there's no way this could be an issue.  
Kindly help me in this regard as soon as possible.

**Comment by alexdima** [comment]
Please open a discussion at http://gh.io/ghcs-feedback
