### ISSUE TITLE
Local history doesn't work in a codespace

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode#195607]
1. Run Local History: Find Entry to Restore
2. Choose any file and version
3. :bug: get an error 

![Image](https://github.com/microsoft/vscode/assets/30305945/ab45a2d5-bcb6-4421-bf5e-5ea2df0da4f6)

**Comment by bpasero** [comment]
Reproducible steps?

**Comment by joyceerhl** [comment]
Hm, seems to work now...
