### ISSUE TITLE
Newton worlod ®

### ISSUE THREAD

**Issue by RadaHugo7** [microsoft/vscode#195636]
![9f3827cb9174208836042a5d87a52748.png](https://github.com/microsoft/vscode/php
/142910273/fa9326e9-989c-47a6-b2b8-f57353537bc5)
- [radahugo7
 ]

**Comment by RadaHugo7** [comment]
> ![9f3827cb9174208836042a5d87a52748.png](https://github.com/microsoft/vscode/php
> /142910273/fa9326e9-989c-47a6-b2b8-f57353537bc5)
> - [radahugo7
>  ] 
>

**Comment by DonJayamanne** [comment]
Please could you file a new issue or update this  with information about what is wrong

Currently there’s not enough information to help you, hence closing this
