### ISSUE TITLE
Webviews and settings editor fail to move to an aux window

### ISSUE THREAD

**Issue by MrYuto** [microsoft/vscode#195651]
![image](https://github.com/microsoft/vscode/assets/75252297/57ca67ad-0f55-4a88-9d56-5ed0c2bf35cc)
![image](https://github.com/microsoft/vscode/assets/75252297/439769bb-eebf-46f1-9da7-787bcf7bb150)
![Code_-_OSS_ck5EBYSkYX](https://github.com/microsoft/vscode/assets/75252297/3be9edbf-47d8-480d-863a-67a7db03ed9a)

**Comment by MrYuto** [comment]
Also, there's a strange issue that's tricky to replicate, but it has happened to me multiple times. It stops commands from working.

**Comment by bpasero** [comment]
Thanks for testing this and reporting the issue. 

Supporting editors that are `iframe` based will be a larger task: https://github.com/microsoft/vscode/issues/195715

I have pushed changes to enable settings editor to move and prevent `iframe` based editors to open in floating windows to not break the workbench layout.

![image](https://github.com/microsoft/vscode/assets/900690/767426eb-6803-4c41-9a92-c9c23964671b)
