### ISSUE TITLE
Triggering Autocomplete overwrites contents.

### ISSUE THREAD

**Issue by manoharprabhu** [Microsoft/vscode#19560]
- VSCode Version: 1.8.1
- OS Version: Windows 7

Steps to Reproduce:

1. Create an HTML file
2. Have the following code snipped in the file
`<a href="#" class="btn btn-default btn-lg"><span class="glyphicon glyphicon-plus">Add a step</a>`
(The span ending tag is intentionally missed out)
3. Keep the cursor just before the "Add a step" text and type `</s` to list the autocomplete suggestion for `</span>` tag.
4. Press enter to accept the suggestion.

Expected content of line now:
`<a href="#" class="btn btn-default btn-lg"><span class="glyphicon glyphicon-plus"></span>Add a step</a>`

Actual content of line now:
`<a href="#" class="btn btn-default btn-lg"><span class="glyphicon glyphicon-plus"></span> a step</a>`

**Comment by aeschli** [comment]
You need to add a space before 'Add' before completing the close tag.
At the time of completion the content looks like that:
` ..glyphicon-plus"></sAdd a...` and it's difficult to decide if 'sAdd' is an existing tag or a contains part of useful text.

**Comment by aeschli** [comment]
Closing as I don't see a reliable way to decide whether intellisense should replace or insert in this scenario.
