### ISSUE TITLE
i will fix it in vscode download. How can i do this when the website is up? az764295.vo.msecnd.net  ERR_CONNECTION_TIMED_OUT

### ISSUE THREAD

**Issue by Godsunsa** [microsoft/vscode#195660]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.83
![Screenshot 2023-10-16 000138](https://github.com/microsoft/vscode/assets/148000136/b97a533f-ef29-4f3c-a207-1491f68d7ffc)

- OS Version: 

Steps to Reproduce:

1. 
2.

**Comment by joaomoreno** [comment]
We no longer use this CDN.
