### ISSUE TITLE
CodeActionsProvider no longer receives the full selection range

### ISSUE THREAD

**Issue by Gama11** [Microsoft/vscode#19562]
- VSCode Version: Code - Insiders 1.9.0-insider (3af0e9d6b79145011a7be3970c1d4b83d69b0443, 2017-01-27T10:46:43.625Z)
- OS Version: Windows_NT ia32 10.0.14986

The behavior of this code changed from 1.8.0 to the current Insider's build: the range received by `provideCodeActions` is no longer the full selection.

```ts
'use strict';
import * as vscode from 'vscode';

export function activate(context: vscode.ExtensionContext) {
    vscode.languages.registerCodeActionsProvider('haxe', {
        provideCodeActions(doc, range, message) {
            return [{
                title: doc.getText(range),
                command: ""
            }];
        }
    });
}
```

In the current Insider's build:

![](http://i.imgur.com/MHUtUra.gif)

In VSCode 1.8.0:

![](http://i.imgur.com/a0KClIk.gif)

_______________________________________

I stumbled over this when trying to implement an "Extract variable" feature for the Haxe extension, and noticed different behavior in 1.8.0 and the Insider's build.

In case this is an intentional change and not a bug: In theory, this could be worked around by just checking the selection of the active editor. However, it's not so simple if you want to implement this in a language server, since there doesn't seem to be any way to check what the current selection is (?).

**Comment by jrieken** [comment]
Yeah, there was a change that we should fallback to the current selection when there is not squiggle. We added asking for code actions for the word under cursor and forget to check if the current selection exceeds that word.
