### ISSUE TITLE
Aux window split view sash uses the main window mouse move events

### ISSUE THREAD

**Issue by MrYuto** [microsoft/vscode#195760]
Repro:
1. Open a text editor
2. Split editor in group
3. Move the active editor into a new window
4. Resize the split view if you can 🐛

![Code_a96V27VSvO](https://github.com/microsoft/vscode/assets/75252297/73e48796-9fac-4895-bd64-8b443108e4db)
![Code_ppclffiJnx](https://github.com/microsoft/vscode/assets/75252297/4a4efd40-8240-4b9d-a22b-d62f6b4faa1c)

**Comment by bpasero** [comment]
Thanks, maybe this is fixed by https://github.com/microsoft/vscode/pull/195778.

You seem to be running out of sources, could you check from that branch. If it still reproduces do you have more detailed steps how you do the dragging in the last step?

**Comment by MrYuto** [comment]
I've tested #195778, and I can confirm that it's fixed.
