### ISSUE TITLE
Add font configuration options for the Debug Console

### ISSUE THREAD

**Issue by Penryn** [Microsoft/vscode#1957]
**Background**
I can barely fit 40 lines from the debug console on my 1080p screen. I appreciate the large and spacious font sizes, but I'm not blind yet and would like to see more.

**Summary**
- Have the debug console follow the existing editor font options such as `editor.fontSize` and `editor.fontFamily`.

OR
- Add configuration options for the debug console such as:
  - `debug.console.fontSize`
  - `debug.console.fontFamily`
  - `debug.console.lineSpacing` for space between lines, because right now it's gigantic.

Better naming conventions are welcome.

_Windows 10, VSCode 0.10.6_

**Comment by isidorn** [comment]
We have changed the default for january release so you should be able to see more.
To make this configurable is a feature request that is not on our immediate plan

**Comment by Penryn** [comment]
@isidorn: Fair enough, thanks.
With that in mind, should this feature request be closed or remain open?

**Comment by isidorn** [comment]
We like to keep feature request opens since people outside the team might jump on it or we might change priorities in the future

**Comment by stefc** [comment]
I also search for a setting of the fontFamily and fontSize on the debug-console! 
Also in the case of C# programming I want to optional supress the 
`Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\1.0.1\System.Diagnostics.Debug.dll'. Cannot find or open the symbol file.
`
messages !

**Comment by hastebrot** [comment]
@stefc My temporary work-around is to use the Code Runner extension. This runs the code in the output console instead of the debug console. The output console font seems to use the editor font configuration.

**Comment by stefc** [comment]
@hastebrot But 'Code Runner' ext. is more for script languages or? How it replace the F5 key that also builds the project ?

**Comment by hastebrot** [comment]
@stefc Yeah, I think it's more for single files and not for projects. But it's not restricted to script languages.

**Comment by isidorn** [comment]
This feature request is dependent on https://github.com/Microsoft/vscode/issues/11462
You can read up on more details there as to what is techincal required to achieve this

**Comment by Gruntfuggly** [comment]
I would also like to be able to set a different font for the debugger. Seems odd that it's not configurable in the same was as other windows?

**Comment by joamag** [comment]
I think it's really important to be able to change the line height. Currently it's really huge (looks a bit ugly) and reduces the ammount of information in the screen.

**Comment by isidorn** [comment]
Assigning to february for an investigation

**Comment by pgobin** [comment]
I also support having better naming conventions for these. One setting that addresses all panels would be welcome in additional to the existing two for editor and terminal fonts.

**Comment by isidorn** [comment]
Investigated into this but there are some additional complications with caluclucating height of each repl element for word wrapping. Due to this pushing it out of february, and plan to tackl it as part of https://github.com/Microsoft/vscode/issues/11462 in march

**Comment by paniq** [comment]
Yup, would be really nice to fix the elephantasque font sizing in the debug window.
"To make this configurable is a feature request that is not on our immediate plan", hold the phone, how many man hours are we talking about here?

**Comment by haemse** [comment]
Do an extra setting!

**Comment by apkd** [comment]
I'd love to see this happen! There's a [proposal for a `fontWeight` setting for the terminal window](https://github.com/Microsoft/vscode/issues/29887) and it would be nice to include that option here as well.

**Comment by brandonrninefive** [comment]
I'm willing to help implement some of these if given the ok :).

**Comment by isidorn** [comment]
@brandonrninefive that is ok. However please keep in mind that this can get quite complex due to debug console using the tree and it wrapping strings to multiple lines. 
I would start with just `debug.console.fontSize` and that would prove tricikier than anticipated. Though I might be wrong.

Code pointer https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/debug/electron-browser/replViewer.ts#L113

**Comment by CTimmerman** [comment]
KeyError: 'G_value' displays without the underscore on my fully updated HP EliteBook 850 G4 with 64-bit Windows 10 Pro:
![afbeelding](https://user-images.githubusercontent.com/9662163/34172129-41ac7564-e4f1-11e7-824b-3fcc444f8373.png)

**Comment by brandonrninefive** [comment]
I've been a bit busy as of late - so I do not see myself working on this anytime soon. If anyone else would like to work on it, please feel free!

**Comment by LordHog** [comment]
Any chance this being bumped up on the priority scale?

**Comment by coldacid** [comment]
Along with this, the monstrous size of items in the Variables and Watch panes in the Debug panel should be adjustable, maybe even with the same prefs as Debug Console font size.

**Comment by earshinov** [comment]
Just in case someone does not know, there is an option to scale up/down the whole interface of VS Code with `window.zoomLevel` parameter. From my experience, font size in the Debug Console stopped bothering me when I started using `window.zoomLevel": -0.5,

**Comment by coldacid** [comment]
That scales everything, though.

**Comment by LordHog** [comment]
Yes, I know about the zoomLevel, but that is the hammer/carpet bombing solution.

**Comment by pakLebah** [comment]
This feature request is more than 2 years old now, but no progress seems to be made. 😟

**Comment by CTimmerman** [comment]
You can offer a bounty or set up the 17+ GB (?!) dev environment to work on it yourself.

If an app does not offer font configuration, it might be using default ones configured by the OS... Unfortunately Windows 10 lacks a font configuration panel as well.

**Comment by iddan** [comment]
What about colours behaviour?

**Comment by ManPython** [comment]
> This feature request is more than 2 years old now, but no progress seems to be made. worried
@pakLebah 
It is to advanced feature to realise :D   f...

**Comment by musm** [comment]
bump

**Comment by shengbeiniao** [comment]
wow,2 years

**Comment by johndpope** [comment]
@isidorn  - can you ask Microsoft for more resources to fix this - hire someone - with 70K stars - I'm sure some talented individual is able to fix this. I get that you don't have the time / energy - delegate this please.

**Comment by dromer** [comment]
Wow yes, I was looking for this option as well. The debug window font is so large and line-spacing is so big. I can't fit nearly enough data on the screen (and I'd like to be able to see my code as well ..)
Imo both these should be configurable so one can set optimal settings for these.

**Comment by nmaxcom** [comment]
Any chance to get this through? :)

**Comment by PhilipHassialis** [comment]
Comeon guys, still not able to change font/font size for Debug Console? Not only it is a different font which makes the uniformity of the environment go haywire PLUS it doesn't scale with the rest of the editor fonts. Is it really *that* hard?

**Comment by hayral** [comment]
bump

**Comment by heliomf-dev** [comment]
The debug messages shows very big in my 1080p display. Laptops already have small screen, so any space that can be saved is very welcome.

**Comment by likt0r** [comment]
I would love to change the size. Is there any estimation when this will be possible ?

**Comment by dromer** [comment]
@likt0r when someone modifies the code and does a pull request and it gets merged into master.

Do you see anyone making the attempt?
Unfortunately not.

**Comment by CTimmerman** [comment]
> I guess the huge trail of comments speaks for itself, still putting one more, can we please have this feature? It's such an important feature, I fail to understand why it's not being worked upon and getting priority even after 3 years.

I guess just like 14-yo Thunderbird bugs like spam triggering new mail notifications, this bug depends on other bugs being fixed first, which is too complex, not interesting enough, or too littered with "me too" comments that don't add anything of value. (Use the subscribe and thumbs up features instead of spamming everyone!)

**Comment by EmbeddedBacon** [comment]
> I guess just like 14-yo Thunderbird bugs like spam triggering new mail notifications, this bug depends on other bugs being fixed first, which is too complex, not interesting enough, or too littered with "me too" comments that don't add anything of value. (Use the subscribe and thumbs up features instead of spamming everyone!)

Sort of like this comment.  Perhaps you can unsubscribe so you don't get spam?  For me, any comment is beneficial.  I guess we view it differently and that is okay.  Don't turn the discussion thread negative.

**Comment by CTimmerman** [comment]
> > I guess just like 14-yo Thunderbird bugs like spam triggering new mail notifications, this bug depends on other bugs being fixed first, which is too complex, not interesting enough, or too littered with "me too" comments that don't add anything of value. (Use the subscribe and thumbs up features instead of spamming everyone!)
> 
> Sort of like this comment. Perhaps you can unsubscribe so you don't get spam? For me, any comment is beneficial. I guess we view it differently and that is okay. Don't turn the discussion thread negative.

Ironic, but i guess my thumbs-up on OP is sufficient. And y'all can keep asking why it's not fixed yet.

**Comment by isidorn** [comment]
Thanks to @joaomoreno awesome work on the tree dynamic heights we now have this!
Also thanks to @suside for creating a PR which inspired us to look into this.

**Comment by musm** [comment]
@joamag the hero we need, the hero we don't deserve
