### ISSUE TITLE
Visual Studio for Mac Preview Installation Not Ends

### ISSUE THREAD

**Issue by erhanyasar** [Microsoft/vscode#19576]
- VSCode Version: VSCode is ok but you don't have a separate library for Preview.
- OS Version: 10.12.3

Steps to Reproduce:

<img width="836" alt="ekran resmi 2017-01-30 11 45 15" src="https://cloud.githubusercontent.com/assets/11460444/22417228/ede8fd30-e6db-11e6-8857-6ae787ac9e51.png">

1. I just tried to setup a month ago VisualStudioforMacPreviewInstaller to my brand new Mac but it didn't allow me

2. As I checked out the whole library I couldn't find an another appropriate path to creating an issue but it doesn't respond to installation. It normally has to succeed to install but seems continue infinite loop as seen in the photo above.

**Comment by bpasero** [comment]
This seems to be the VS for Mac installer, not VS Code.

**Comment by erhanyasar** [comment]
there is no repository named even close to that. Can you look or show me any place for it? There is nothing contains word "Mac" or "Preview" @bpasero

**Comment by bpasero** [comment]
@erhanyasar I think you are trying to install this: https://developer.xamarin.com/visual-studio-mac/ but this repository is about VS Code: http://code.visualstudio.com/

**Comment by erhanyasar** [comment]
I see my friend but as I already stated from the beginning of my issue, there is no repository for that. There is just this link[(https://github.com/xamarin/xamarin-macios)] with the similar name but not has an option to create an issue @bpasero

**Comment by bpasero** [comment]
@erhanyasar sure, let me try to find the right place.

**Comment by bpasero** [comment]
What about here: https://bugzilla.xamarin.com/

**Comment by erhanyasar** [comment]
I'm issuing a new one, tx for a hand @bpasero!
