### ISSUE TITLE
[Bug] Sparkle icon appearing very close to commit text

### ISSUE THREAD

**Issue by aiday-mar** [microsoft/vscode#195773]
Does this issue occur when all extensions are disabled?: Yes/No

```
Version: 1.84.0-insider (Universal)
Commit: f1c3b1dcf85e3b6ddb24b7dce0e4b122e8ce6233
Date: 2023-10-17T05:38:23.658Z (3 hrs ago)
Electron: 25.8.4
ElectronBuildId: 24154031
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Darwin arm64 23.0.0
```

Steps to Reproduce:

1. Open a PR and make a change, go to the Source Control view
2. Type a message and notice that the text appears very close to the sparkle icon :bug:

Here is a gif showing the bug

https://github.com/microsoft/vscode/assets/61460952/015f97c0-b0d8-4c49-9849-3c43f47e9e9b

**Comment by lszomoru** [comment]
This has been fixed in Insiders 1.85.

**Comment by alexr00** [comment]
It now seems like there is too much extra space. This is as close as I could get to the sparkle:

<img width="322" alt="image" src="https://github.com/microsoft/vscode/assets/38270282/c2bf7051-1942-4d30-bdbd-9191c9bf94a9">

**Comment by lszomoru** [comment]
This is due to the fact that even should the vertical scrollbar is hidden, the space for it is still being reserved. This is a known issue (@hediet please correct me if I am wrong), and it is outside the scope of this particular bug.
