### ISSUE TITLE
Sticky scroll number not updating

### ISSUE THREAD

**Issue by Zivko992** [microsoft/vscode#195711]
Type: <b>Bug</b>

Sticky scroll number doesn't update with relative line numbers when moving from line to line.

VS Code version: Code 1.83.1 (f1b07bd25dfad64b0167beb15359ae573aecd2cc, 2023-10-10T23:48:05.904Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8350U CPU @ 1.70GHz (8 x 1896)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|23.65GB (9.59GB free)|
|Process Argv|--crash-reporter-id 5623fe57-80cb-42c5-b14d-3bd8f9de8ff5|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (32)</summary>

Extension|Author (truncated)|Version
---|---|---
project-manager|ale|12.7.0
vscode-django|bat|1.14.0
vscode-log-viewer|ber|0.14.0
turbo-console-log|Cha|2.9.6
python-environment-manager|don|1.2.4
python-extension-pack|don|1.7.0
gitlens|eam|14.4.0
LogFileHighlighter|emi|2.16.0
prettier-vscode|esb|10.1.0
copilot|Git|1.126.0
copilot-chat|Git|0.8.0
vsc-python-indent|Kev|1.18.0
expand-region|let|0.1.4
template-string-converter|meg|0.6.1
vscode-docker|ms-|1.27.0
csdevkit|ms-|0.5.150
csharp|ms-|2.6.24
vscode-dotnet-runtime|ms-|1.8.1
vscodeintellicode-csharp|ms-|0.1.26
isort|ms-|2023.10.1
python|ms-|2023.18.0
vscode-pylance|ms-|2023.10.20
material-icon-theme|PKi|4.31.0
vscode-thunder-client|ran|2.13.5
everforest|sai|0.3.0
toggle-boolean|sil|0.10.0
svelte-vscode|sve|107.12.0
errorlens|use|3.14.0
intellicode-api-usage-examples|Vis|0.2.8
vscodeintellicode|Vis|1.2.30
vim|vsc|1.26.1
jinja|who|0.0.8

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
py29gd2263cf:30856253
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
282f8724:30602487
89544117:30613380
showlangstatbar:30737416
a2ce3375:30757347
ecj1e332:30736112
pythonfmttext:30731395
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
pythonnosmt12:30797651
pythonidxpt:30805730
pythonnoceb:30805159
copilotsettingc:30859502
dsvsc013:30795093
dsvsc014:30804076
diffeditorv2:30821572
dsvsc015:30845448
pythonregdiag:30859691
pyreplss1:30858575
pythonmypyd1:30859726

```

</details>

**Comment by aiday-mar** [comment]
Hi thanks for filing this issue. It should be fixed.
