### ISSUE TITLE
Association for ".jslib" file script red underline(does not exist).

### ISSUE THREAD

**Issue by gtk2k** [Microsoft/vscode#19570]
- VSCode Version: 1.8.1
- OS Version: Win10 15007.1000

Steps to Reproduce:
I use VSCode for Unity.

1. ".jslib" file change language mode to JavaScript.
2. write "window.hoge = () => {};" in ".jslib" file and save file. 
3. "hoge" red underline(does not exist).
4. But, ".jslib" file red underline remove after ".js" file open.
5. Represent red underline VSCode reboot.

I want do not display red underline on change to JavaScript mode file.
![vscode_problem](https://cloud.githubusercontent.com/assets/309829/22413153/bd246708-e6f8-11e6-8899-f88299408daa.gif)

**Comment by mjbvz** [comment]
Thanks for the report. Can you please try this out the latest insiders builds. I believe that #20351 fixed this. 

Let me know if you still the issue and I'll reopen to investigate

**Comment by gtk2k** [comment]
I try latest insiders builds.
I confirmed that the problem was resolved.
Thanx!

**Comment by isidorn** [comment]
User verified -> adding verified label
