### ISSUE TITLE
Explorer: Search File Listing

### ISSUE THREAD

**Issue by elithrar** [Microsoft/vscode#19571]
- VSCode Version: Version 1.8.1 (1.8.1)
- OS Version: macOS 10.12.2 (16C67)

*Feature Request*

1. When focused within the [file] Explorer, it's not possible to search by the names of all directories & files starting at the root of the explorer itself.
2. It's also not possible to navigate up from the root directory in the Explorer.

Feature no. 1 is very similar to NERDTree in vim: when focused, you can /$searchterm for specific files and open them in the buffer with a quick <Enter> (amongst other things). Feature no. 2 is an extension of that: improving the general file navigation within the Explorer.

**Comment by bpasero** [comment]
This issue has already been reported. Please use the search function next time before reporting an issue and/or this time if you are curious about the progress of the issue.

**Comment by elithrar** [comment]
I did search for "search explorer" across open issues, but didn't find an
obvious open issue that matched this.

Mind doing me the favor of linking to it?


On Mon, Jan 30, 2017 at 5:36 AM Benjamin Pasero <notifications@github.com>
wrote:

Closed #19571 <https://github.com/Microsoft/vscode/issues/19571>.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/Microsoft/vscode/issues/19571#event-941328224>, or mute
the thread

**Comment by thekalinga** [comment]
https://github.com/Microsoft/vscode/issues/10026
