### ISSUE TITLE
Generate commit message not accessible via keyboard

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#195781]
1. Focus commit input box
2. No way to use the keyboard to focus the "Generate Commit Message" 🐛 

Ideally I should be able to press `tab` and focus would move to the ✨

**Comment by JOEMN96** [comment]
I analyzed this issue, it is related to CSS,

![image](https://github.com/microsoft/vscode/assets/56827756/8f403a6b-e1f1-4539-870b-e2b37c2a998d)

.scm-view .scm-input .actions .action-label {} --> we need to update CSS outline rule value with this variable var(--vscode-icon-foreground)

@lszomoru   Can you provide code pointer ? I was unable to find this piece of CSS in our repo.

**Comment by lszomoru** [comment]
@isidorn, @JOEMN96, are you able to reproduce this in VS Code Insiders?


Pressing `tab` focuses the SCM input action button for me:

![Image](https://github.com/microsoft/vscode/assets/3372902/bb37c82f-0815-4b68-a6d6-9bafaec4e00b)

**Comment by isidorn** [comment]
Yes, this works great now. Thank you. Closing.
