### ISSUE TITLE
Debuggers: Add a tooltip for value on key hoverover

### ISSUE THREAD

**Issue by Spown** [Microsoft/vscode#19578]
- VSCode Version: 1.8.1
- OS Version: Win10x64
- Observed on: Node2-, Chrome-, Firefox debuggers

There is a tooltip showing the value, when hover over the value, but no tooltip, when hovering on the corresponding key. So if the key is longer than the inspector width - there is no way to see the value other than to resize the inspector.

![](https://dl.dropboxusercontent.com/u/105338698/ShareX/2017-01/2017-01-30_12-31-56.gif)

Thank you.

**Comment by Spown** [comment]
Just noticed that the tooltip does show for non primitive values (i.e. the line is expandable)

![](https://dl.dropboxusercontent.com/u/105338698/ShareX/2017-01/Code_2017-01-30_12-46-07.png)

**Comment by isidorn** [comment]
On name hover we show the type of the variable (if it is provided by the debug extension).
If type is not provided we now show the name to accomodate for the use case you have described

**Comment by Spown** [comment]
Why?

**Comment by isidorn** [comment]
Can you elaborate please

**Comment by Spown** [comment]
Why does it have to be type? How is this useful? One rarely needs it and if so, it can be determined through value color (if primitive) or it is specifically named if it is complex typed one. Value is more important and as described in my OP it sometimes inaccessible unless the inspector is resized. Why is this bugfix is useless?.

**Comment by isidorn** [comment]
More details about this can be found here https://github.com/Microsoft/vscode/issues/8040
You can also find a lot of related issues linked
One of the main drivers for this is C# debugging
