### ISSUE TITLE
[Accessibility] Mute aria alert when "audioCues.format" is on

### ISSUE THREAD

**Issue by jooyoungseo** [microsoft/vscode#195799]
Type: <b>Feature Request</b>

CC @meganrogge 

Just like other audio cues, please reduce aria alert when "audioCues.format" is used.

VS Code version: Code - Insiders 1.84.0-insider (f1c3b1dcf85e3b6ddb24b7dce0e4b122e8ce6233, 2023-10-17T05:34:42.128Z)
OS version: Windows_NT x64 10.0.22621
Modes:

**Comment by meganrogge** [comment]
To verify, 
- Enable `audioCues.format`
- Enable a screen reader
- Format a document
- Verify that the screen reader doesn't alert `Formatted`

**Comment by joaomoreno** [comment]
Works somewhat: https://github.com/microsoft/vscode/issues/196594
