### ISSUE TITLE
The "editorGutter" element in the editor has disappeared

### ISSUE THREAD

**Issue by XenoMeri** [microsoft/vscode#195762]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.83.1
- OS Version: Windows 10

Steps to Reproduce:

The "editorGutter" element in the editor has disappeared, and the corresponding colors for Git changes cannot be displayed.

normal:
![image](https://github.com/microsoft/vscode/assets/69188637/0054e384-d516-4645-9b85-f531f322e4c3)
![image](https://github.com/microsoft/vscode/assets/69188637/a1e8ec3b-3ad8-45c2-9b5d-1e8678c77fcc)

wrong:
![image](https://github.com/microsoft/vscode/assets/69188637/54da82c2-75af-4e7f-9ca8-83be04251c2d)

**Comment by connor4312** [comment]
Do you have any settings related to gutters that you've modified?

**Comment by XenoMeri** [comment]
No, I haven’t modified any related settings. And after suspecting it was a git issue, I’ve upgraded git to the latest version, but the problem still hasn’t been resolved.

**Comment by XenoMeri** [comment]
I found a stable way to reproduce the problem:

Step:
1、Open a file
2、Click " Ctrl + \" （notebook.cell.split）
3、Close the split


https://github.com/microsoft/vscode/assets/69188637/56f88c60-3bf7-406a-b601-9c1d6ed682f4

**Comment by lszomoru** [comment]
@alexr00, do you mind taking an initial look at this? Thanks!

**Comment by alexr00** [comment]
@XenoMeri thanks for the repro steps!
