### ISSUE TITLE
Hung "Code Helper (Plugin)" Process, and "Goto Symbol in Editor" timeout

### ISSUE THREAD

**Issue by dkzsys** [microsoft/vscode#195756]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.83.1
- OS Version: MacOS 13.2.1

Steps to Reproduce:

1. Open a large markdown file; my example is a 1.6MB/~17,000 line markdown file.
2. Check Activity Monitor for "Code Helper (Plugin)" process status and CPU utilisation.
3. Select "Goto Symbol in Editor" in VSCode.

==================================

Hi there,

**_Context_**
I work with large markdown files, ~1.6MB/17,000+ lines, on a regular basis. And I use "Goto Symbol in Editor" feature to search or navigate to specific sections of a markdown file.

The large markdown file used to load without any issues; and the "Goto Symbol in Editor" used to work effortlessly, i.e. loaded with zero delay. 

![image](https://github.com/microsoft/vscode/assets/39715311/d6ae90a8-589e-4084-887c-22eb32517a36)

**_Problem statement_**

I noticed the unexpected behaviour today. After doing some diagnostics, the 2 symtoms of failures/problem statements are

1. Hung "Code Helper (Plugin)" Process with ~100% CPU after loading the large markdown file.
2. "Goto Symbol in Editor" have been trying to load all the symbols and eventually timeout.

**Note: the same file was working a few days ago (last usage before failure)** 

Re issue 1, even after I terminate vscode app, the hung "Code Helper (Plugin)" process is still there till I manually force terminate it/them. Some screenshots for reference.
![image](https://github.com/microsoft/vscode/assets/39715311/33d55ec6-e3cc-4038-ace2-7a4bc9efe7a4)

![image](https://github.com/microsoft/vscode/assets/39715311/53ebf004-d8c9-4648-899b-54cf942a6e93)

Re Issue 2, "Goto symbol in editor" not loading, it can be another symptom of issue 1. A screenshot below for demonstration.
![image](https://github.com/microsoft/vscode/assets/39715311/397161fc-ba88-434e-bdc0-a66142e7e6e7)

**_System Info_**
- vscode Version: 1.83.1 (Universal)
- Commit: f1b07bd25dfad64b0167beb15359ae573aecd2cc
- Date: 2023-10-10T23:46:55.789Z
- Electron: 25.8.4
- ElectronBuildId: 24154031
- Chromium: 114.0.5735.289
- Node.js: 18.15.0
- V8: 11.4.183.29-electron.0
- OS: Darwin arm64 22.3.0/MacOS 13.2.1

**_Triage_**
I do not recall making any manual changes recently; and I have auto-update on for both vscode app and the extensions. 

What I have attempted to troubleshoot:
- Downgrade VSCode to previous version 1.83.0 - both issues persist with large markdown file.
- Test a much smaller markdown file (a few hundred lines) - both issues gone: "Code Helper (Plugin)" Process CPU utilisation ~0%; "Goto Symbol in Editor" works (i.e. loading all the symbols).
- Disabling all extensions - both issues persist with large markdown file.

**_What I am seeking_**
I am seeking:
- if anyone has experienced this issue and has a resolution, who can shed some more light;
- any guidance on how to debug this further;
- any other suggestions.

Thanks.

**Comment by dkzsys** [comment]
I did some more testing and can confirmed that there is no debug dump in either "Output" or "Debug Console" - screenshots belw.

![image](https://github.com/microsoft/vscode/assets/39715311/20cde069-a16d-48eb-abe6-29f43f47b7e6)

![image](https://github.com/microsoft/vscode/assets/39715311/9474884b-59ab-4f04-9faa-1b08ddc0a1fa)

Another re-cap on the process status and cpu utilisation for 2 scenarios/states:

_Process Status and CPU Utilisation - After opening the markdown file in vscode_
![image](https://github.com/microsoft/vscode/assets/39715311/4c996900-ea11-4b92-8fca-a823b6218c41)

_Process Status and CPU Utilisation - After closing the markdown file in vscode, and then closing/terminating vscode app_
![image](https://github.com/microsoft/vscode/assets/39715311/10c2b743-8e38-40c9-9720-d134c03e536c)

**Comment by dkzsys** [comment]
With the same markdown file, I have also done a test with Sublime Text - no issues loading the file or with "Goto Symbol" feature. Screenshots below:
_Sublime Text - no issues_
![image](https://github.com/microsoft/vscode/assets/39715311/0b199a38-e6fb-4fe6-8b46-883a5337bd0a)


_vscode_
![image](https://github.com/microsoft/vscode/assets/39715311/1f028e8f-d532-4cd2-a37c-489de2b7682e)

**Comment by penghiang** [comment]
Experiencing a similar issue as issue 2 with markdown file that contains
```
# symbol
[\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
```

**Comment by dkzsys** [comment]
> Experiencing a similar issue as issue 2 with markdown file that contains
> 
> ```
> # symbol
> [\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
> ```

Issue 1 is also applicable to this.
![image](https://github.com/microsoft/vscode/assets/39715311/4ed20f40-9def-46eb-9cc0-9d23966e5612)

**Comment by dkzsys** [comment]
I have tried the beta/insider version and same issue.

![image](https://github.com/microsoft/vscode/assets/39715311/d196c758-c02b-4801-b347-a73faa8cd184)


`Version: 1.84.0-insider (Universal)
Commit: 8e11b537e3b091a8b52c7179fb623ecdeecaf4ea
Date: 2023-10-20T05:37:02.690Z
Electron: 25.9.1
ElectronBuildId: 24472542
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Darwin arm64 22.3.0`

**Comment by dkzsys** [comment]
I have downgraded to v1.80.0 as a workaround. FYI @mjbvz 

Version: 1.80.0 (Universal)
Commit: 660393deaaa6d1996740ff4880f1bad43768c814
Date: 2023-07-04T13:39:33.766Z
Electron: 22.3.14
ElectronBuildId: 21893604
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Darwin arm64 22.3.0

**Comment by mjbvz** [comment]
Fixed upstream by https://github.com/microsoft/vscode-markdown-languageservice/pull/157. Should also be in the current VS Cod insiders builds
