### ISSUE TITLE
Mouse wheel scrolling doesn't work when dragging a file in explorer view

### ISSUE THREAD

**Issue by JohnPoison** [Microsoft/vscode#19573]
- VSCode Version: 1.8.1
- OS Version: OS X 10.11.6

Steps to Reproduce:

1. Open explorer
2. Start dragging a file to other location
3. Try to scroll mouse wheel
4. Notice that mouse wheel doesn't work

**Comment by joaomoreno** [comment]
This is browser behaviour, can't fix while we use native dnd.
