### ISSUE TITLE
Close Folder opens a new instance of VS Code instead

### ISSUE THREAD

**Issue by galenus** [Microsoft/vscode#19575]
- VSCode Version: 1.9.0-insider
- OS Version: Windows 10 Pro (1511)

Steps to Reproduce:
1. Set "window.openFoldersInNewWindow": "on"
2. Open some project folder
3. Close the VS Code
4. Open VS Code - it launches with the last project open
5. In menu File -> Close Folder

Result: new instance of VS Code is launched

**Comment by bpasero** [comment]
Good catch!
