### ISSUE TITLE
Button and placeholder text overlap

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#195786]
* have a long branch name
* hover to see the toolbar
* 🧀 there is some overlap

<img width="437" alt="Screenshot 2023-10-17 at 10 57 15" src="https://github.com/microsoft/vscode/assets/1794099/506b41c6-1ac9-4f2e-9eac-6933addeda3c">

**Comment by lszomoru** [comment]
Closing as duplicate of https://github.com/microsoft/vscode/issues/195773.
