### ISSUE TITLE
Support `iframe` based editors to reparent into floating windows

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#195715]
With floating windows, users have the desire to move editors out of the main window into the child window. Some of our editors use an absolute positioned `iframe` element that is resized and moved to fit into the editor area it belongs to. This will not work anymore as soon as the editor moves out of the window.

I already made a pass and configured currently unsupported editors with the new `AuxWindowUnsupported` capability. 

This impacts custom editors as well as notebooks.

Steps to move an editor out to a floating window:
* remove the `AuxWindowUnsupported` capability for the editor of choice
* open such an editor
* trigger the "Move active editor into a new window" action from the command palette

//cc @Tyriar

**Comment by r3m0t** [comment]
Can I work on this one? My interest is in the notebook editor. 

Is it possible to use DOM appendChild to move the iframe from one window to another?

Maybe `retainContextWhenHidden: false` is an easy case that can be done first? In this case the editor iframe can be safely destroyed and a new one created.

**Comment by bpasero** [comment]
@r3m0t thanks for willing to chime in, I think @rebornix has already started on this so maybe he could comment

**Comment by r3m0t** [comment]
@bpasero any of these 'help wanted' or no? https://github.com/microsoft/vscode/issues?q=is%3Aopen+label%3Aworkbench-auxwindow

**Comment by bpasero** [comment]
Thanks for asking, maybe https://github.com/microsoft/vscode/issues/196148 or https://github.com/microsoft/vscode/issues/196579. The others seem rather complex to me.

**Comment by abrahan-munro** [comment]
This issue is hard to find as it doesn't contain the text of the error message, so I'm adding that now:

> This type of editor cannot be opened in other windows yet.

Also, an explicit list of windows that are affected would help with searching, e.g.

- markdown preview
- extensions

**Comment by rebornix** [comment]
> Is it possible to use DOM appendChild to move the iframe from one window to another?

@r3m0t thanks for offering help. Unfortunately we can't move/reparent iframe, it is always a re-create if we are moving the notebook editor to aux window. In addition to the challenge with iframe, we have a borrow-editor concept for notebook which needs to tweaked to get this working. I have a draft which I can send a PR for soon.

**Comment by jogibear9988** [comment]
But should the menu item to open in a new window be visible, even if it is not supported?

<img width="1249" alt="image" src="https://github.com/microsoft/vscode/assets/364896/1ea9394d-6cf1-4096-aebc-5407d327369d">

**Comment by bpasero** [comment]
I think thats fine given we plan on actually resolving this issue this month.

**Comment by bpasero** [comment]
Works now, minus bugs.
