### ISSUE TITLE
Aux window: move away from globals that need to be contextual

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#195888]
With floating windows, there is not just one `window` or `document` but one per window. Global use of `window` and `document` should cause a ESLint warning and utilities should be provided as alternatives.

**Adoptions**
* [ ] `$window`

//cc @alexdima

**Comment by bpasero** [comment]
More on `setTimeout`: we could patch the global window method to schedule the callback on all opened window and then cancel it for the first winner. We would in addition have to schedule it for new windows opening with the diff of the duration.

**Comment by bpasero** [comment]
The remaining usages of `$window` are covered in:
* https://github.com/microsoft/vscode/issues/195715
* https://github.com/microsoft/vscode/issues/203672

**Comment by rebornix** [comment]
@bpasero I fixed the $window usage in notebook now.
