### ISSUE TITLE
Operation not permitted when running bash script from task

### ISSUE THREAD

**Issue by spboyer** [Microsoft/vscode#19586]
VSCode Version: Version 1.8.1
OS Version: macOS Sierra 10.12.2 (16C67)

Steps to Reproduce:

1. clone repo https://github.com/spboyer/dockerdebugapp
2. open debug pane and run 
3. Console outputs: "/bin/bash: ./dockerTask.sh: Operation not permitted"

Can run bash script from terminal with no problems without sudo.

**Comment by egamma** [comment]
This issue was moved to OmniSharp/omnisharp-vscode#1162
