### ISSUE TITLE
Scroll markers should be focusable and snap into position

### ISSUE THREAD

**Issue by tinganho** [microsoft/vscode#1958]
I got some problem to scroll into view some error or whatever shown in my scrollbar as markers. They are very tiny and it is hard to position the scrollbar where the markers is.

I think the scroll markers should show a focused state(i.e. scaled up a bit) on hover. And on click they should scroll into view whatever they represent.

**Comment by inz-fms** [comment]
Also, there's not much value in them fading away. For file lists, you don't really know if a file has been removed or it's just that there's a hidden scroll bar to see more.
