### ISSUE TITLE
setting.json escape sequence not working

### ISSUE THREAD

**Issue by ujex256** [microsoft/vscode#195879]
Type: <b>Bug</b>

I attempted to create a terminal profile that establishes an alias using the doskey command upon terminal startup.
To achieve this, I modified the args array by adding a command involving double quotes utilizing an escape sequence. However, when I executed the terminal with the profile and checked it using the doskey /macros command, the escape sequence was inputted as-is.

I tested other escape sequences aside from double quotes and they all functioned properly.
```json
"terminal.integrated.profiles.windows": {
        "testProfile": {
            "path": "${env:windir}\\System32\\cmd.exe",
            "args": ["/K", "doskey atest=oj t -d ./tests/ -c \"python ./main.py\""],
            "overrideName": true,
            "icon": "terminal-cmd",
            "color": "terminal.ansiBlue"
        }
    }
```

VS Code version: Code 1.83.1 (f1b07bd25dfad64b0167beb15359ae573aecd2cc, 2023-10-10T23:48:05.904Z)
OS version: Windows_NT x64 10.0.22621
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|12th Gen Intel(R) Core(TM) i5-12400F (12 x 2496)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.84GB (18.36GB free)|
|Process Argv|--crash-reporter-id b70326e3-dae6-4aff-8e30-56acf6c648e2|
|Screen Reader|no|
|VM|50%|
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
py29gd2263:30856252
vscaac:30438847
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
2e4cg342:30602488
89544117:30613380
showlangstatbar:30737416
pythonfmttext:30731395
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
pythonnosmt12:30797651
pythonidxpt:30805730
pythonnoceb:30805159
dsvsc013:30795093
dsvsc014:30804076
diffeditorv2:30821572
dsvsc015:30845448
pythonmypyd1:30859726
pythontbext0cf:30864173

```

</details>

```[tasklist]
### Tasks
```

**Comment by ujex256** [comment]
![image](https://github.com/microsoft/vscode/assets/105550500/fff485dc-a04e-4d4e-8b2f-61835583d109)
I tried another pattern, both of which failed.

**Comment by meganrogge** [comment]
We escape the args using this

https://github.com/microsoft/node-pty/blob/8efcef6f5fcfe2a3f7bb9b20a97113d776cae06a/src/windowsPtyAgent.ts#L253-L306

**Comment by ujex256** [comment]
Thank you very much. Unfortunately, I was unable to achieve my intended result after multiple attempts with the code.  I created a new element and added the double-quoted "python . /main.py" command, but it resulted in two double quotes being inserted.

Sorry, could you provide an example?
![image](https://github.com/microsoft/vscode/assets/105550500/d0ecdc38-386a-4434-8572-e6d42e960648)

**Comment by Tyriar** [comment]
You may need to double escape the quotes which would get the `\` chars passed through?

```
 -c \\"python ./main.py\\""],
```

It's a bit unclear how to action this, if you have a more concrete suggestion on a simple case that doesn't work and what it should be doing we may be able to look into it further.
