### ISSUE TITLE
Aux window: Close aux window when last open tab is closed

### ISSUE THREAD

**Issue by IllusionMH** [microsoft/vscode#195880]
Currently when last tab in aux window is closed - aux window stays open but empty.
This is expected behavior for main window, but for aux windows it feels natural that it should be closed when there are no open editors.

I see how this might be not behavior that works for everyone, so it can be configurable in settings.

**Comment by MrYuto** [comment]
We should have a `closeEmptyWindows` option like `closeEmptyGroups` because it's a common pattern to close the window like in browsers.

**Comment by bpasero** [comment]
I wonder if `closeEmptyGroups` should just close the window? Do we need a new setting?

**Comment by MrYuto** [comment]
@bpasero I've thought about it more, and I think including explicit (`closeEmptyWindows`) and implicit (`closeEmptyGroups`) settings would help support users who have multiple monitors and don't like to keep groups but still want to continue using the command palette and etc.

**Comment by bpasero** [comment]
For now, will not introduce a new setting for this. There is also `window.closeWhenEmpty` which is currently unsupported but should eventually be supported that would allow to enable this without forcing to close empty groups.
