### ISSUE TITLE
Add ability to display icons in Code Lenses

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode#19582]
- VSCode Version: Insiders

Add ability to display Octicons in Code Lenses.
My plan is to display the results (as done [here](https://i-msdn.sec.s-msft.com/dynimg/IC814850.jpeg) in VS) of unittests against each method. 
Part of the functionality has been provided through #10648 (refreshing code lenses).
Now i'd like to display a red "X" or a green "Tick" (what ever the standard Octicons may be).

**Comment by mjbvz** [comment]
As a workaround, you may be able to use emoji or regular unicode symbols to achieve a similar effect:

<img width="474" alt="screen shot 2017-01-30 at 11 12 59 am" src="https://cloud.githubusercontent.com/assets/12821956/22437518/31e25ea4-e6dd-11e6-851b-a9063f65d0ff.png">

One downside to this is that these will vary somewhat between operating systems

**Comment by DonJayamanne** [comment]
Excellent, what Unicode characters have you used?

**Comment by DonJayamanne** [comment]
Thanks for the tip

**Comment by kondratyev-nv** [comment]
@jrieken I would like to try fixing it. Would that be ok? Maybe you can think of some pitfalls?

**Comment by jrieken** [comment]
Use the utils from [octiconLabel.ts](https://github.com/microsoft/vscode/blob/085e845f224d549ceab9c980effb1de8802d6fd2/src/vs/base/browser/ui/octiconLabel/octiconLabel.ts#L15) and wire things up here: [codelensWidget.ts#L78](https://github.com/microsoft/vscode/blob/085e845f224d549ceab9c980effb1de8802d6fd2/src/vs/editor/contrib/codelens/codelensWidget.ts#L78.) One thing to consider is that maybe not all users want octicons, e.g one might be using $(zap) and not want ⚡️ but we can consider that later
