### ISSUE TITLE
code-tunnel still broken on Ubuntu 18.04

### ISSUE THREAD

**Issue by cobalt2727** [microsoft/vscode#195842]
Sorry for the silence, I was on vacation. I will address the tunnel binary dependency this week.

_Originally posted by @deepak1556 in https://github.com/microsoft/vscode/issues/181720#issuecomment-1628636628_
            
```bash
ubuntu@oracle-vm:~$ code tunnel
/usr/share/code/bin/code-tunnel: /lib/aarch64-linux-gnu/libc.so.6: version `GLIBC_2.29' not found (required by /usr/share/code/bin/code-tunnel)
/usr/share/code/bin/code-tunnel: /lib/aarch64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by /usr/share/code/bin/code-tunnel)
```
Checked in a few months later and this still seems to be causing issues, unfortunately.

**Comment by deepak1556** [comment]
Tracked in https://github.com/microsoft/vscode/issues/192685
