### ISSUE TITLE
Consider adding all actions to chat context menu for screen reader users

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#195815]
@jooyoungseo said that blind users tend to rely heavily on context menus to avoid having to tab around a bunch. 

Currently, chat responses have only `Copy` and `Copy All`. We should consider adding `View References`, `Upvote`, `Downvote`, etc. to this when in screen reader mode.

![Image](https://github.com/microsoft/vscode/assets/29464607/31dde985-fe8c-46ea-85dd-29e7b807637a)

**Comment by jooyoungseo** [comment]
What if this feature is implemented for all users regardless of their screen reader settings? Would it be noisy?

**Comment by meganrogge** [comment]
@roblourens what do you think of this request?

**Comment by roblourens** [comment]
I'm not sure what "View References" would do, but upvote/downvote, sure it's fine with me
