### ISSUE TITLE
Single Quote in Param Validation for PowerShell treats everything following as string in highlighting.

### ISSUE THREAD

**Issue by animetauren** [Microsoft/vscode#19589]
- VSCode Version: Code 1.8.1 (ee428b0eead68bf0fb99ab5fdc4439be227b6281, 2016-12-19T14:49:23.350Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

|Extension|Author|Version|
|---|---|---|
|python|donjayamanne|0.5.6|
|PowerShell|ms-vscode|0.9.0|

---

Steps to Reproduce:

1. Include this param in your ps1 script param block
```powershell
        [parameter(Mandatory=$true, ParameterSetName="new", HelpMessage='Email Address associated with this Certificate.')][ValidatePattern('^[_a-z0-9-]+(\.[_a-z0-9-]+)*@[a-z0-9-]+(\.[a-z0-9-]+)*(\.[a-z]{2,4})$')]
        [String]$email,
```
2. Most of the lines of the script following this line will be color highlighted as strings, even if they are not string but rather variables, functions or even commented out lines. See screenshot below:

![image](https://cloud.githubusercontent.com/assets/1291811/22434874/e296be58-e6eb-11e6-8b24-7a309733a570.png)

**Comment by aeschli** [comment]
@daviwil David, FYI.

**Comment by daviwil** [comment]
This issue was moved to PowerShell/EditorSyntax#33
