### ISSUE TITLE
Update fwlink for unsupported workspace setting

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode#19581]
The fwlink https://go.microsoft.com/fwlink/?linkid=839878 needs to be update and point to the security explanation https://github.com/Microsoft/vscode-docs/blob/vnext/release-notes/v1_9.md#settings-and-security

**Comment by egamma** [comment]
// @dbaeumer fyi

**Comment by gregvanl** [comment]
fwlink updated to point to https://code.visualstudio.com/docs/customization/userandworkspace#_settings-and-security
