### ISSUE TITLE
ripgrep not working due to signing and group policies

### ISSUE THREAD

**Issue by maximiliank** [microsoft/vscode#195895]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.83.1
- OS Version: Windows 10, 10.0.19045

Global search functionality is not working
![image](https://github.com/microsoft/vscode/assets/9783517/1887bb6e-54d0-4d1e-8d00-864d8465aee0)

The reason is that ripgrep (resources\app\node_modules.asar.unpacked\\@vscode\ripgrep\bin\rg.exe) is not signed by Microsoft and hence may be blocked by group policies in enterprise environments.

Steps to Reproduce:

1. Do a global search

Would it be possible to sign rg.exe as well?

**Comment by andreamah** [comment]
I believe that we do sign `rg.exe`. Are you not seeing it? 
<img width="203" alt="image" src="https://github.com/microsoft/vscode/assets/31675041/1b2ac9cb-249f-4fbc-948a-e30c668aa911">

**Comment by maximiliank** [comment]
I just checked and you are right, it is signed. I will check with my administrator why Code.exe works but rg.exe is blocked by the group policy. Sorry for the inconvenience.
