### ISSUE TITLE
Adopt DOM.getWindow in terminal

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#195804]
These need to move over to `DOM.getWindow` to properly support aux windows.

![Image](https://github.com/microsoft/vscode/assets/2193314/bf864143-c90a-441d-b0f2-e91c24346619)

![Image](https://github.com/microsoft/vscode/assets/2193314/fe885d33-2eac-49e5-9f6e-63999ee4429c)

**Comment by bpasero** [comment]
Part of https://github.com/microsoft/vscode/issues/195888

The new `$window` uncovers a lot more usages that need to be revisited:

<img width="721" alt="image" src="https://github.com/microsoft/vscode/assets/900690/4c211c9e-2224-4298-aa22-46bd184bd390">

**Comment by bpasero** [comment]
Still seeing some:

<img width="749" alt="image" src="https://github.com/microsoft/vscode/assets/900690/f737b576-b86c-4ed3-80ab-7c37211fc5e5">

**Comment by Tyriar** [comment]
Ah thanks, I need to fix how I commonly search for terminal stuff now that we have the `terminalContrib` folder. Need to search with include `terminal*`, not `terminal` 🤦
