### ISSUE TITLE
Aux window: support to restore aux windows and editors

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#195887]
We should support to restore aux windows at their position and restoring the editors and layout within.

**Comment by IllusionMH** [comment]
Does this issue include "restoring" windows/editors after VS Code is closed and opened again (e.g. Update) or should I create separate one?
For example: I have main windows with 3 editors and Aux window with 2. When I click on Update I'd like to see same state as before update (main + aux). Currently it looks like all (Untitled in this case) editors moved to main window.

**Comment by bpasero** [comment]
Yes. When VSCode restarts or you reload a window, all auxiliary windows should restore at their location and size with the editors you had opened there 🤞

**Comment by bpasero** [comment]
Floating windows now restore on restart or reload, you can test this with todays insider build already: https://code.visualstudio.com/insiders/
