### ISSUE TITLE
no indication that search is in progress for screen reader users

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#195811]
cc @jooyoungseo

While witnessing JooYoung experience https://github.com/microsoft/vscode/issues/194008, it occurred to me that we don't have an in progress audio cue for the settings search. 

@Afre100 should we reuse the one for chat response pending here?

**Comment by AFre100** [comment]
@meganrogge  Thanks for flagging this. We're going to investigate and let you know what we recommend.
