### ISSUE TITLE
Debuggers: Add "copy path" to the context menu in the inspector

### ISSUE THREAD

**Issue by Spown** [Microsoft/vscode#19580]
- VSCode Version: 1.8.1
- OS Version: Win10x64

Currently there is a "Add to Watch" for all items in the variable inspector and "Copy/Set Value" for the primitive fields. Please add a "Copy Path" for all items. Right now the only way to do it is through a watch:

![](https://drive.google.com/uc?id=0B-OJBofmehO3eWw2UVZLZkJ4MmM)

Which is not only tiresome, but also creates a useless watch.

Thank you.

**Comment by isidorn** [comment]
This is a good opportunity for a PR

**Comment by bpasero** [comment]
"Copy Path" is a bit weird, maybe "Copy Name"?

**Comment by Spown** [comment]
> "Copy Path" is a bit weird, maybe "Copy Name"?

"Copy Name" usually means copying a particular property name, whereаs I need the whole chain starting from selected property/variable.

Actually "Copy Name" wouldn't harm to have as well. There is also a scenario when I go into prototype of an object (or even several levels of prototypes deep) and I need the path without ``__proto__`` in between - for this right now I need to do the thing depicted in the gif above and also manually remove any ``__proto__`` in the result (let's call it "Copy Path (inherited)" or something). 

But this may wait for another day. Right now it would be nice to have just the path. Thank you.

**Comment by isidorn** [comment]
@bpasero Copy Name does not work imho. We could go with "Copy Full Name", "Copy Evaluate Name"
@weinand thoughts?

**Comment by bpasero** [comment]
Yeah, up for ideas, "Copy Name" is not ideal either. I am just correlating "Copy Path" with file paths typically.

**Comment by Spown** [comment]
Well, people at [Lodash call it path sometimes](https://lodash.com/docs/4.17.5#toPath). [Mongoose does the same as well](http://devdocs.io/mongoose/api#document_Document-get)

**Comment by Spown** [comment]
Also copying path means capturing array indexes as well. In case of multidimensional arrays it would mean only indexes - ``[5][0][1][67][4][0]``. "Name" would be highly misleading in this case.

**Comment by weinand** [comment]
some ideas:
Copy expression
Copy expression path
Copy evaluation
Copy evaluation path
Copy eval expression

**Comment by isidorn** [comment]
"Copy expression path" and "Copy evaluation path" work for me

**Comment by weinand** [comment]
Variants:
Copy as expression path
Copy as evaluation path

**Comment by Spown** [comment]
I don't think "evaluation" is a good word for this? You probably use it internally, to get values to dispaly in the inspector. But from the consumption perspective it has nothing to do with eval. Or do I see it wrong?

**Comment by Spown** [comment]
Maybe "Copy path as/for expression"?

**Comment by weinand** [comment]
Any user that uses the REPL (aka debug console) knows what evaluation means because she is using it all the time...

**Comment by weinand** [comment]
"Copy path as" sounds strange because a user has selected a variable not a path.
So my variants from above tried to address this (but they left out the "variable").
The name would be
      Copy variable as expression
Or
      Copy variable as path expression

**Comment by Spown** [comment]
>Any user that uses the REPL (aka debug console) knows what evaluation means because she is using it all the time...
I'm not saying the user doesn't know what eval means - I'm saying the user associates evaluation with either evaling in console or through ``eval()`` method (if there is one in the language). I'm not speaking for everyone, but I do not associate eval with context inspection.

>Copy variable as expression
If I would see such a menu item - I would think it does value stringification or something like that.

**Comment by isidorn** [comment]
After a discussion with a tema we settled on "Copy as Expression"
Thanks for feedback.
