### ISSUE TITLE
Terminal Black/Unreadable After Sleep

### ISSUE THREAD

**Issue by DeJayDev** [microsoft/vscode#195861]
Type: <b>Bug</b>

After my device wakes from sleep, the VS Code Integrated Terminal is just: black. This issue occurs without any extension enabled.

I used `systemctl suspend` to trigger a suspend manually for this issue, but this issue also happens with "organic" suspends.

VS Code version: Code 1.83.1 (f1b07bd25dfad64b0167beb15359ae573aecd2cc, 2023-10-10T23:45:31.402Z)
OS version: Linux x64 6.5.7-arch1-1
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz (16 x 4700)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|2, 1, 1|
|Memory (System)|31.26GB (22.05GB free)|
|Process Argv|--disable-extensions --crash-reporter-id 62784a0d-97f8-4eb0-ad8b-1353643aa43e|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|gnome|
|XDG_CURRENT_DESKTOP|GNOME|
|XDG_SESSION_DESKTOP|gnome|
|XDG_SESSION_TYPE|x11|
</details>Extensions disabled<details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
py29gd2263cf:30856253
vscaat:30438848
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
2e4cg342:30602488
f6dab269:30613381
a9j8j154:30646983
showlangstatbar:30737416
03d35959:30757346
pythonfmttext:30731395
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
pythonnosmt12:30797651
pythonidxpt:30805730
pythonnoceb:30805159
copilotsettingt:30859503
asynctok:30821568
dsvsc013:30795093
dsvsc014:30804076
diffeditorv2:30821572
dsvsc015:30845448
pythontbext0:30864172

```

</details>

**Comment by DeJayDev** [comment]
Noting that I cannot reproduce this issue on Code - OSS, here's some more hopefully useful version information:

Electron: 25.8.4
ElectronBuildId: 25154031
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0

**Comment by antonymerle** [comment]
Hi. I have the same problem on Linux Mint 21.2 (kernel: 5.15.0-88-generic) and Ubuntu 23.10. I have a Nvidia GPU.
For a few monthes, adding ` "terminal.integrated.enableImages": false` in my settings solved the problem but a recent update (Nvidia drivers or VSCode) made it surface again.
