### ISSUE TITLE
Logitech MX Master Back Button does nothing on Mac, should (Go -> Back)

### ISSUE THREAD

**Issue by renzska** [Microsoft/vscode#19588]
- VSCode Version: 1.8.1
- OS Version: MacOS Sierra 10.12.3

Steps to Reproduce:

1. Using a Logitech MX Master Mouse, set any of the buttons to the "Back" functionality.
2. Click the back button after navigating in VSCode from one file to another.
3. Watch nothing happen.

Here are my settings in the Logitech Options software:

![image](https://cloud.githubusercontent.com/assets/13021263/22433512/d722cb22-e6d5-11e6-8903-184b1546371f.png)

Examples:
 - Spotify: Back Button goes back through the navigation (View -> Go Back).
 - Chrome: Navigates back through the pages (History -> Back).

Each of the above examples are using different keyboard shortcuts, but both are achieved by pressing the same  back button on the mouse.

I would love to see this functionality in VSCode on the Mac.

Thanks,

John

**Comment by bpasero** [comment]
Still happening?

**Comment by renzska** [comment]
It seems to be working now. An interesting aspect of testing this functionality is that the 'Go Back' functionality is different from Visual Studio for Mac and Visual Studio for Windows; Clicking on a file in the explorer bar counts as a step within the back history in VSCode, but is not considered a step in the history on VSfM and VSfW. For example, I click on .gitattributes, and then click on line 10. I click my mouse button bound to 'Back' and it moves the cursor to the first line in the file. In turn, traveling through files ends up requiring a second back button press to get through single files.

To note, when clicking on the file in explorer it does not show my cursor flashing on line 1 of that file.

So, as of now, the Back button now executes the "Go Back" functionality (and my new issue is that the go back functionality is different, though may not need to be changed if the differences are intended).

Let me know if you need more info.
