### ISSUE TITLE
Aux window: Open recent action opens editor in main window instead of aux one

### ISSUE THREAD

**Issue by IllusionMH** [microsoft/vscode#195876]
Type: <b>Bug</b>

Steps to Reproduce:

1. Open some editor in aux window
2. Use shortcut or Command palette to run `File: Open recent...`
3. Select file
4. File will be opened in main window (and main window will be brought to focus) instead of aux window.

At the same time `Go to file` works (almost) as expected and opens in aux window (however today it does in separate group for some files, not sure about pattern yet)

VS Code version: Code - Insiders 1.84.0-insider (58bdf2c7c40be6f4494ae35a09528708832cf357, 2023-10-18T05:50:15.982Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz (8 x 2996)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.50GB (17.06GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by bpasero** [comment]
This is actually quite hard to solve: the request to open these files travels to the main process and there we have logic to focus that window:

https://github.com/microsoft/vscode/blob/8c810ad98d21be2184dd3e9233d5c91f5ff102c2/src/vs/platform/windows/electron-main/windowsMainService.ts#L639

However this will focus the main window and thus the files will open there.

**Comment by IllusionMH** [comment]
/verified

@bpasero thanks!
