### ISSUE TITLE
Notebook Python import cell executable from toolbar

### ISSUE THREAD

**Issue by michaelstuffer98** [microsoft/vscode#195872]
When having a notebook, sometimes I need to restart the kernel or the kernel crashes. In these cases, I usually have to rerun the first cell with my Python imports. For me it would be handy to have a mechanism that e.g. defines a cell as imports and then let me execute this cell via the notebook tool bar, such that I don't have to scroll up and down all the time if i only need the imports.

**Comment by rebornix** [comment]
/duplicate of https://github.com/microsoft/vscode-jupyter/issues/14316
