### ISSUE TITLE
Don't show sparkle when inline chat is already active

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#195982]
* start inline chat (via any mechanism)
* :bug: the sparkle keeps showing which IMO we shouldn't

Note that there is `IInlineChatSessionService` with `onWillStart..` and `onDidEnd...` events

<img width="836" alt="Screenshot 2023-10-19 at 12 20 56" src="https://github.com/microsoft/vscode/assets/1794099/82c2ffdb-dafe-42b3-bcbc-7f0e7f71895b">

**Comment by rzhao271** [comment]
The sparkle flashes a bit but does disappear upon opening inline chat.
