### ISSUE TITLE
VSCODE POWERSHELL SERIOUS BUG !!!!!!!!!

### ISSUE THREAD

**Issue by nop4LOL** [microsoft/vscode#195924]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: all version , old_version - 1.83.1 (latest)
- OS Version: Windows 10

Steps to Reproduce:

I can't stand this serious problem any longer !

All versions of vscode have this problem for a long time, today I uninstalled the old version and then installed the latest version, the problem still exists !

Please see the following pictures：

![image](https://github.com/microsoft/vscode/assets/117899311/73fedad7-d55d-41f5-b547-331cd9798cb1)

![image](https://github.com/microsoft/vscode/assets/117899311/bbd8e043-acdc-48fc-88a9-95ccf1bc2a6b)

As you can see, just open the powershell terminal and type the command, and random characters will be selected Highlight !!!

I guess it's powershell's problem , but even though I installed the latest powershell, I still have the above problem .............

Anyone can help me solve this problem ???????????   thx a lot ~~~~~~~~~~~~~~~

**Comment by nop4LOL** [comment]
In powershell 5.1 version:

![image](https://github.com/microsoft/vscode/assets/117899311/b85843c9-dd9d-4923-b72f-db3310b0c4c0)

**Comment by nop4LOL** [comment]
This problem has been bothering me for years, and today I finally couldn't stand it anymore and raised the issue !!!!!!!!!!!!!!!!!!!

**Comment by meganrogge** [comment]
Do you have extensions installed? I cannot reproduce this

**Comment by devendrakanojiya** [comment]
> 
> 
> 
> 
> 
> 
> 
> Does this issue occur when all extensions are disabled?: Yes/No
> 
> 
> 
> - VS Code Version: all version , old_version - 1.83.1 (latest)
> - OS Version: Windows 10
> 
> Steps to Reproduce:
> 
> I can't stand this serious problem any longer !
> 
> All versions of vscode have this problem for a long time, today I uninstalled the old version and then installed the latest version, the problem still exists !
> 
> Please see the following pictures：
> 
> ![image](https://github.com/microsoft/vscode/assets/117899311/73fedad7-d55d-41f5-b547-331cd9798cb1)
> 
> ![image](https://github.com/microsoft/vscode/assets/117899311/bbd8e043-acdc-48fc-88a9-95ccf1bc2a6b)
> 
> As you can see, just open the powershell terminal and type the command, and random characters will be selected Highlight !!!
> 
> I guess it's powershell's problem , but even though I installed the latest powershell, I still have the above problem .............
> 
> Anyone can help me solve this problem ???????????   thx a lot ~~~~~~~~~~~~~~~
> 
> 
> 

So, you mean this rgblgbtq lights are serious problem
