### ISSUE TITLE
error notice preventing solution

### ISSUE THREAD

**Issue by freakypie** [Microsoft/vscode#19591]
I get an error popup that looks like this:

![selection_086](https://cloud.githubusercontent.com/assets/1542720/22438485/6bbe4d48-e6e9-11e6-81c0-538dc7f5df25.png)

the solution as far as i know is to press the revert to disk button found in the tab area. It's blue in this image: 

![selection_087](https://cloud.githubusercontent.com/assets/1542720/22438509/8848748e-e6e9-11e6-9cf7-9b2925bde153.png)

Unfortunately, the error notice hides the tab bar and therefore it can't be accessed without shuffling it to the right split panel. 

The error is not dismissed until that blue button is pressed.

- VSCode Version:
1.8.1
- OS Version:
Ubuntu 16.04

Steps to Reproduce:

1. open a git diff
2. change the file in the diff and save it
3. revert the file from the sidebar menu

**Comment by bpasero** [comment]
@freakypie I am not sure I understand the issue, the error message goes away once you click the Compare button and makes room for the buttons does it not?

**Comment by freakypie** [comment]
unfortunately no. the notice doesn't go away unless the blue button it overlaps it pressed. if you press compare another notice with the same text immediately appears

**Comment by freakypie** [comment]
if it happens again, ill make a giphy for you

**Comment by bpasero** [comment]
@freakypie yes there is a second notice that gives you hints how to solve the issue, it has a button to remove it. It is more of a help text that you can just dismiss.

**Comment by freakypie** [comment]
This is what it looks like for me:
![vscode_notice](https://cloud.githubusercontent.com/assets/1542720/22475746/2e1b2c90-e79d-11e6-934c-8184b3a5c9cd.gif)

**Comment by bpasero** [comment]
@freakypie wow that is crazy, I have never seen something like that! does it reproduce with our insider build? You can give our preview releases a try from: http://code.visualstudio.com/Download#insiders

**Comment by freakypie** [comment]
I'll try it and let you know

**Comment by freakypie** [comment]
In the insider build the "compare" notice won't appear unless you try to save, so the problem doesn't exist.

So it looks like it will be fixed in a future build. Thanks.
