### ISSUE TITLE
ESLint Fix all: VSCode September 2023 breaks, doesn't accept previous config

### ISSUE THREAD

**Issue by Dannymx** [microsoft/vscode#195965]
Previously to fix missing imports and autofix everything with eslint the config was the following:
```
"editor.codeActionsOnSave": [
    "source.addMissingImports",
    "source.fixAll.eslint"
  ],
```
Now I get an error: `Incorrect type. Expected "object".`

But adding this new object doesn't fix all the eslint errors anymore:
```
"editor.codeActionsOnSave": {
    "source.fixAll": "always"
  },
```

Reverting to previous monthly release until this is fixed.

**Comment by dbaeumer** [comment]
@justschen can you please have a look. Let me know if there is anything I can do in ESLint.

**Comment by justschen** [comment]
@Dannymx have you updated to 1.83.1?

**Comment by Dannymx** [comment]
@justschen My bad, when I saw VSCode update today on my machine to the September release I thought I had the latest, I just tried **1.83.1** and seems to be working fine again. Closing this issue. Thanks!
