### ISSUE TITLE
Pasting into a "Replace Preview" after dismissing "Save As..." causes a temporary freeze

### ISSUE THREAD

**Issue by mind-bending-forks** [microsoft/vscode#195977]
Type: <b>Performance Issue</b>

To reproduce (for me at least):

- Copy some text so that you can paste it later.
- Search for something in the code base.
- Define replacement text for the search term.
- Click on a match. It is opened in a "Replace Preview" window.
- Decide to edit the code within the left-hand pane of the "Replace Preview" instead (or before) accepting the highlighted replacement. There are some other things you want to change too.
- Out of habit after making changes, accidentally try to save your changes via CTRL-S while in the "Replace Preview". This doesn't work as expected! (I'm always getting tripped up by this. To save the changes, you have to close the "Replace Preview", switch to the original file - where those changes show up, and save the original file instead!) A "Save As..." dialog opens. (It is not visible or noticeable, because it opens *behind* the main VS Code window. This is probably a Linux annoyance. The main window becomes completely blocked, and you can't figure out why. Eventually, you realise that a "Save As" dialog is hidden behind.) Once you discover the "Save As..." window, you switch focus to it. Since you don't want to do a "Save As..." from the "Replace Preview", you cancel the dialog and *do not* save.
- So you return to the "Replace Preview" and make some further edits in the left-hand pane without having saved.
- As part of those edits, you paste the text from your buffer that you had previously copied.
- VS Code then freezes and becomes unresponsive. Keep getting asked whether you want to kill VS Code or wait. If you wait long enough (minutes), VS Code comes back to life and the copied text is eventually pasted.

A freeze on paste only seems to occur after dismissing the "Save As" window, not in other circumstances, so something weird is going on there.

This bug is because my expectation is that the text from the copy-paste buffer should be pasted instantly.

Yes, saving of edits made in a replace preview should work much better from a user experience point of view, and yes, the "Save As" dialog should open in front of VS Code, not hidden behind it, but those are not the issues I am reporting here. Those annoyances are easy to ignore/avoid once you get used to them! An IDE freeze is not.

VS Code version: Code 1.83.1 (f1b07bd25dfad64b0167beb15359ae573aecd2cc, 2023-10-10T23:45:31.402Z)
OS version: Linux x64 5.15.0-86-generic
Modes:

<details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
markdown-mermaid|bie|1.20.0
vscode-intelephense-client|bme|1.9.5
selected-lines-count|gur|1.4.0
csharp|ms-|2.7.25
vscode-dotnet-runtime|ms-|1.8.1
php-debug|xde|1.33.0

</details>

**Comment by andreamah** [comment]
Ah, I see this. Here are some repro steps:
1. Open replace preview from find+replace.
2. Try to put something in the left ('before') pane and try to save it.
3. Esc out of the modal that asks to save.
4. The editor still shows something loading :bug:

**Comment by mind-bending-forks** [comment]
> I'll need to make the editor read-only to remove this pain point - there's no reason that I know of that it is editable.

My understanding is:
- The left hand pane mirrors or is the source file. It represents the the state of the source file before replacements listed in the search results have been applied.
- The right hand side shows what the source would become should you choose to apply the replacement(s) listed in the search results.
 
At present, the left hand pane is editable. Editing it and saving it is just like editing and saving the source file. The right hand side is not editable.

If you were to make the left hand pane read-only too, then while undertaking replacements, you would no longer be able to just edit the source in place if something else that needed to be changed were to be spotted. You would have to find the corresponding source file, find the corresponding place within that source file corresponding to the particular replacement you were working on, make the change (without also being able to see what replacements are planned), then switch back to the search results to bring up that particular replacement again so you could pick up where you left off. It will be far less convenient from a usability point of view.

I'm pretty sure that until very recently (not sure exactly when) saving from the replacement window and then deciding to abort the save used to work just fine. Therefore, this is most likely a regression.

If possible, my preference would be for that regression to be identified and rectified. It would be a shame to lose the ability to edit the source in place entirely because a bug associated with changing your mind about whether to save from the replacement window has been introduced or emerged.

Alternatively, if it has to be done by making the left hand pane read-only, perhaps double-clicking or similar on the left hand pane could be made to take you directly to the corresponding point in the source file, so as to lessen the inconvenience?

**Comment by andreamah** [comment]
Ah okay, I see. I can look into why aborting isn't working.

**Comment by mind-bending-forks** [comment]
Thanks.

**Comment by osortega** [comment]
This doesn't seem to repro anymore.
Closing the issue but feel free to reopen if you are still seeing the problem
