### ISSUE TITLE
clicking links in notebook error output focus issue

### ISSUE THREAD

**Issue by amunger** [microsoft/vscode#195946]
1. run a cell that will produce an error `print(x)`
2. click a link in the stack trace
🐛 sometimes focus is not correctly given to the cell

![Recording 2023-10-18 at 16 16 07](https://github.com/microsoft/vscode/assets/2019016/4dd54cb1-4ba2-4167-aa84-38f3d3fb0d07)

**Comment by Devil7-coder** [comment]
Good
