### ISSUE TITLE
Panel badge should adopt style of activity bar

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#195998]
They now look quite different:

![Image](https://github.com/microsoft/vscode/assets/900690/24b8ef96-f0c2-4445-951f-e3ed26a40d73)

I would suggest a consistent style and color for all.

**Comment by bpasero** [comment]
Maybe just the positioning, it seems quite far away from the label. I guess we cannot really do the overlay...

I wonder why we never went with icons for the panel? or maybe icon and text and the badge could be over the icon?

**Comment by bpasero** [comment]
I think a wrongly referenced commit message.

**Comment by sandy081** [comment]
> I wonder why we never went with icons for the panel? or maybe icon and text and the badge could be over the icon?

Yeah, this is a very good thought

CC @hbons @daviddossett

**Comment by daviddossett** [comment]
I think this would be partly due to the difference between `activityBarBadge.background` and `badge.background` in our default themes. Aligning them could help here—I was already thinking of reverting back to that anyway. 

> Maybe just the positioning, it seems quite far away from the label.

Any specific reasoning for the gap between text and badge in panel tabs @Tyriar?

**Comment by Tyriar** [comment]
@daviddossett I think it's just been like that forever, before my time 🙂

**Comment by moritz-t-w** [comment]
I would love to have Icons in the panel!
Here's a mockup of the color scheme (Dark+ theme): I think a border would be needed between the side bars and the panel
![Mockup](https://github.com/microsoft/vscode/assets/90388353/ff4ee4a0-75d7-41ad-8d1c-bfc0a5e6656b)

**Comment by moritz-t-w** [comment]
Mistakenly referenced in f1b7a36601d8d0508704f3402ee9376128afcbcc

**Comment by joaomoreno** [comment]
These will be aligned with https://github.com/microsoft/vscode/issues/227076

**Comment by gjsjohnmurray** [comment]
> These will be aligned with #227076

This has brought us the option for icons instead of labels 👍, but the badge appearance hasn't been aligned with that of the side bars.

**Comment by sandy081** [comment]
That's correct and I can confirm

![Image](https://github.com/user-attachments/assets/03a1eeb6-29af-47a0-b4be-4e0217182db2)

**Comment by benibenj** [comment]
- reduced the the margin between badge and label
- made the badge a little smaller
- The badge is the same color as activity bar when the container is rendered as an icon

The only open question is if we should make the badge color the same in the default scenario. I don't think so as it feels very heavy, but I'm open to other opinions

**Comment by bpasero** [comment]
I think thats worth a try and collecting feedback.
