### ISSUE TITLE
Only show "AZURE" for the "AZURE: ACTIVITY LOG" window in the Visual Studio Code Insiders

### ISSUE THREAD

**Issue by v-xinda** [microsoft/vscode#195957]
**OS:** Win10
**Visual Studio Code Version:** 1.84.0-insider (user setup)

**Repro Steps:**
1. Install "Azure Storage" extension from Extensions.
2. Navigate to Azure view -> Open a new Terminal -> Click "AZURE" window.
3. Check whether shows "AZURE: ACTIVITY LOG".

**Expect:** 
Show "AZURE: ACTIVITY LOG".
![image](https://github.com/microsoft/vscode/assets/57662131/3e280d65-aab7-46ab-9aaa-7f24b85ec459)

**Actual:**
Show "AZURE".
![image](https://github.com/microsoft/vscode/assets/57662131/3059b89c-94af-4cd2-b363-f41768e4da33)

**More Info:**
This issue doesn't reproduce for the Visual Studio Code 1.83.1 (user setup).

**Comment by lszomoru** [comment]
Please file an issue in the [extension's repository](https://github.com/microsoft/vscode-azurestorage/issues). Thank you!
