### ISSUE TITLE
Expose API to add custom highlighting to explorer view

### ISSUE THREAD

**Issue by MaxKless** [microsoft/vscode#195985]
The explorer view is very useful. While navigating, you can quickly see what files are affected by SCM changes through custom highlights.
![image](https://github.com/microsoft/vscode/assets/34165455/ae8aac6a-1097-45d2-81da-751f59ab9032)

It would be really nice if VSCode exposed an API to let extensions provide their own file highlights here. Specific files might be important during certain workflows or for certain tools and warrant highlighting. 

To avoid clutter, this entire feature might have to be toggle-able. I understand too if this is something you won't consider because it risks heavily cluttering up the explorer view.

**Comment by gjsjohnmurray** [comment]
Did you explore the [FileDecorationProvider](https://code.visualstudio.com/api/references/vscode-api#FileDecorationProvider) API?
