### ISSUE TITLE
Stuck Installing Extensions

### ISSUE THREAD

**Issue by bdoyle8** [microsoft/vscode#195911]
Type: <b>Bug</b>

No matter what extension I select VS Code is stuck installing.
Version: 1.83.1 (user setup)
Commit: f1b07bd25dfad64b0167beb15359ae573aecd2cc
Date: 2023-10-10T23:48:05.904Z
Electron: 25.8.4
ElectronBuildId: 24154031
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.19045

VS Code version: Code 1.83.1 (f1b07bd25dfad64b0167beb15359ae573aecd2cc, 2023-10-10T23:48:05.904Z)
OS version: Windows_NT x64 10.0.19045
Modes:
Remote OS version: Linux x64 3.10.0-1160.102.1.el7.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 PRO 4650U with Radeon Graphics (12 x 2096)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.23GB (6.69GB free)|
|Process Argv|--crash-reporter-id 5f1c9ba4-1be8-4649-a669-f5915bbc8de6|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: Develop|
|OS|Linux x64 3.10.0-1160.102.1.el7.x86_64|
|CPUs|Intel(R) Xeon(R) Platinum 8272CL CPU @ 2.60GHz (4 x 2593)|
|Memory (System)|27.48GB (19.68GB free)|
|VM|0%|
</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
remotehub|Git|0.62.0
CppSnippets|har|0.0.15
remote-ssh|ms-|0.106.5
remote-ssh-edit|ms-|0.86.0
azure-repos|ms-|0.38.0
remote-explorer|ms-|0.4.1
remote-repositories|ms-|0.40.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
py29gd2263:30856252
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
3biah626:30602489
f6dab269:30613381
vscrp:30673768
showlangstatbar:30737416
a2ce3375:30757347
pythonfmttext:30731395
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
pythonnosmt12:30797651
pythonidxpt:30805730
pythonnoceb:30805159
copilotsettingt:30859503
dsvsc013:30795093
dsvsc014:30804076
diffeditorv1:30821571
pythonmhint1:30842940
dsvsc015:30845448
pyreplss1:30858575
pythoncet00cf:30859750
pythontbext0:30864172

```

</details>

**Comment by bdoyle8** [comment]
Here is the window log
[View_Window_Log_20231018.txt](https://github.com/microsoft/vscode/files/13031422/View_Window_Log_20231018.txt)

**Comment by sandy081** [comment]
It seems you are connecting to a remote - can you please share the server log?

**Comment by bdoyle8** [comment]
Here are the logs I found and the timestamp is for the directory it was found.  I think the server admin changed settings somewhere to not allow access to the marketplace, but I am not sure.  I did attach the  "window" log in a prior post and that's the only thing that "stuck" out for me.  I've contacted 2 other team members and they too cannot update existing extensions OR add new extensions.
[remoteagent_093636.log](https://github.com/microsoft/vscode/files/13043760/remoteagent_093636.log)
[ptyhost_090636.log](https://github.com/microsoft/vscode/files/13043761/ptyhost_090636.log)
[remoteagent_090636.log](https://github.com/microsoft/vscode/files/13043763/remoteagent_090636.log)
[network_093636.log](https://github.com/microsoft/vscode/files/13043764/network_093636.log)
[ptyhost_093636.log](https://github.com/microsoft/vscode/files/13043765/ptyhost_093636.log)

**Comment by sandy081** [comment]
> Is installing extensions in a local window (when not connected to remote) is working?

**Comment by bdoyle8** [comment]
I have not tried that, I will give that a try now.

**Comment by bdoyle8** [comment]
Yes, I have installed the 3 extensions, but will they work once I connect to the remote server?

**Comment by bdoyle8** [comment]
I am closing vs code and starting it up and letting it connect to the remote server

**Comment by bdoyle8** [comment]
It installed these extensions locally, but now it wants me to install them on the remote server. 
<img width="262" alt="image" src="https://github.com/microsoft/vscode/assets/148362745/36117379-f7d7-4275-ad22-dbe622dfc55c">

**Comment by bdoyle8** [comment]
Now, trying to install 1 of these on the server: 
<img width="265" alt="image" src="https://github.com/microsoft/vscode/assets/148362745/048666be-240a-40a3-8df1-c158575daffa">

**Comment by bdoyle8** [comment]
It is not installing... it is stuck

**Comment by bdoyle8** [comment]
I have been talking with our system architect and he needs to know what ports (open) and either ip address or URLs to access for remote ssh for me to install extensions on the remote server.  I don't have access on the server to set up these things.

**Comment by sandy081** [comment]
Looks like you have issues connecting to the network on the remote. Could be proxy related. As a workaround you can enable following setting which will download extensions locally from MP.

`remote.downloadExtensionsLocally`

**Comment by bdoyle8** [comment]
enabling that setting worked great, thank you so very much.

**Comment by chrmarti** [comment]
There is a list of hosts here (we don't have separate list for the remote setup): https://code.visualstudio.com/docs/setup/network
