### ISSUE TITLE
Device guard blocked this app?

### ISSUE THREAD

**Issue by d4sty27** [microsoft/vscode#195936]
Hello, i recently have installed vs code, and of course, msys as the compiler for c++, but now (around a week later from the installation), i cant even run a script, because it gets blocked by windows defender (the error called it "device guard") and when i clicked on "Show more", it basically said that windows defender blocked something that was not signed for security issues:

![Screenshot 2023-10-17 224744](https://github.com/microsoft/vscode/assets/148388914/f5690d73-b81f-40cf-9304-7c716f71b585)

Can i do something to prevent this? can i fix it?

Thanks

**Comment by lramos15** [comment]
You can add an exclusion to defender to not scan your programming folder
