### ISSUE TITLE
TS version prompt shows non-existent path when ts not present

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#19599]
- Ubuntu
- Have workspace settings with a tsdk set
- Have typescript not actually installed
- Open a ts file and click the version number

Strange that it shows this path, which doesn't exist:
![image](https://cloud.githubusercontent.com/assets/323878/22446155/fd05a16e-e6ff-11e6-94a7-8ec79664b819.png)

**Comment by mjbvz** [comment]
This is by design. When we cannot load TS, we print out the entire path that we try to check instead of just the version number
