### ISSUE TITLE
"Cannot read property 'toLowerCase' of undefined" during run task

### ISSUE THREAD

**Issue by fredrikaverpil** [Microsoft/vscode#19595]
- VSCode Version: Code - Insiders 1.9.0-insider (e68cede8b65dc918332493146c2572a7e132a451, 2017-01-27T20:36:09.447Z)
- OS Version: Darwin x64 16.4.0
- Extensions:

|Extension|Author|Version|
|---|---|---|
|vscode-clock|Compulim|0.0.1|
|mayaport|JonMacey|1.0.0|
|vscode-docker|PeterJausovec|0.0.11|
|code-settings-sync|Shan|2.4.2|
|project-manager|alefragnani|0.13.1|
|python|donjayamanne|0.5.6|
|vscode-material-theme|fredrikaverpil|0.0.3|
|theme-material-theme|jprestidge|1.0.1|
|prettify-json|mohsen1|0.0.3|
|mel|sator-imaging|0.1.1|
|trailing-spaces|shardulm94|0.2.11|
|jinja|wholroyd|0.0.7|

---

Steps to Reproduce:

1. Use provided `tasks.json` and cmd+shift+p "Run task" "Cross-OS executable"

```json
{
    "version": "0.1.0",
    "tasks": [
        {
            "taskName": "Cross-OS executable",
            "osx": {
                "command": "/foo/bar",
                "args": ["baz"]
            },
            "windows": {
                "command": "C:\\foo\\bar.exe",
                "args": ["baz"]
            },
            "isShellCommand": true,
            "isBackground": false,
            "echoCommand": true,
            "showOutput": "always"
        }
    ]
}
```

Expected behavior: Run `/foo/bar baz` on OS X and `C:\foo\bar baz` on Windows.
Actual behavior: Error: Cannot read property 'toLowerCase' of undefined (and the task seems to hang)

**Comment by fredrikaverpil** [comment]
I noticed this all works fine if you supply a "dummy" `command` key to the JSON, however, why would you want to do that?

```json
{
    "version": "0.1.0",
    "tasks": [
        {
            "taskName": "Cross-OS executable",
            "command": "dummy",
            "osx": {
                "command": "/foo/bar",
                "args": ["baz"]
            },
            "windows": {
                "command": "C:\\foo\\bar.exe",
                "args": ["baz"]
            },
            "isShellCommand": true,
            "isBackground": false,
            "echoCommand": true,
            "showOutput": "always"
        }
    ]
}

```

**Comment by chuckleplant** [comment]
Reporting the same behaviour:

- VSCode Version: Code 1.9.1 (f9d0c687ff2ea7aabd85fb9a43129117c0ecf519, 2017-02-08T23:31:51.320Z)
- OS Version: Darwin x64 16.4.0
- Extensions:

|Extension|Author|Version|
|---|---|---|
|vscode-color|anseki|0.2.3|
|python|donjayamanne|0.5.8|
|Theme-TwoStones|gerane|0.0.2|
|Theme-wild-cherry|gerane|0.0.3|
|theme-onedark-sublime|joshpeng|0.3.6|
|cpptools|ms-vscode|0.10.1|

---

Steps to Reproduce:

1. Use provided task.json
2. Output shows `Cannot read property 'toLowerCase' of undefined`
3. Add a `"command": "dummy"` as suggested by @fredrikaverpil 
4. Still not working
5. Reload VSCode
6. Prompt for task termination
7. After reload it works

```
{
    "version": "0.1.0",
    "showOutput": "always",
    "echoCommand": true,
    "tasks": [
        {
            "taskName": "build",
            "isBuildCommand": true,
            "isShellCommand": true,
            "windows": {
                "command": "echo",
                "args": ["you"]
            },
            "linux": {
                "command": "echo",
                "args": ["big"]
            },
            "osx": {
                "command": "echo",
                "args": ["cat"]
            }
        }
    ]
}
```

On top of the dummy command suggested above,  for me it was not fixed until the editor was reloaded, some task needed termination.
