### ISSUE TITLE
Getting error on launching VSCode.

### ISSUE THREAD

**Issue by mmmathur** [Microsoft/vscode#19590]
- VSCode Version:
1.6
- OS Version:
Windows 7

Steps to Reproduce:

1. Update VSCode.
2. Abort on error for opened application.
3. Now when you open VS Code, it gives error on opening.

Not able to upload error file screen shot so typing error main lines below:
**Error**:
Cannot find module 'C:\Program Files (x86)\Microsoft VS Code\resources\app\out\main'
at Module_resolveFileName(module.js455:15)

**Comment by bpasero** [comment]
@mmmathur can you download VS Code 1.8 fresh and reinstall to see if that helps?
