### ISSUE TITLE
Documentation does not say tsc must be installed

### ISSUE THREAD

**Issue by oleg-alexandrov** [microsoft/vscode#195953]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:  Insiders
- OS Version:  Linux

Steps to Reproduce:

I spent a lot of time trying to make my first extension. After hours of debugging, I found that tsc was not installed. The documentation at https://code.visualstudio.com/api/get-started/your-first-extension does not explain that.

The documentation should be amended to say that one should run:

sudo npm install typescript -g

**Comment by IllusionMH** [comment]
I'd say you shouldn't install TS globally, but use local version through npm scripts instead.
Minimal example has necessary scripts.
https://github.com/microsoft/vscode-extension-samples/blob/main/helloworld-sample/package.json

If you want to use local version manually - you can try `npx` instead

**Comment by oleg-alexandrov** [comment]
The problem is that package.json calls the tsc tool, and it is not found.

**Comment by IllusionMH** [comment]
Make sure you have `typescript` in `package.json` and that you installed dependencies.

**Comment by oleg-alexandrov** [comment]
I followed the instructions at https://code.visualstudio.com/api/get-started/your-first-extension. I did:

npm install -g yo generator-code

This wasn't enough though. It worked with .js extentions but not with .ts extensions because tsc could not be found. 

There was also no clear error message in the console. Only in the terminal it says: tsc not found.

**Comment by oleg-alexandrov** [comment]
To continue, here's a screenshot: 
<img width="557" alt="image" src="https://github.com/microsoft/vscode/assets/1325676/f478fc72-3345-4e0c-b2f7-b54061f61ff4">

This is with the example in vscode-extension-samples/helloworld-sample as I got it from the repository. I did not touch package.json or anything.

**Comment by IllusionMH** [comment]
Looks like something with your setup (maybe in general with VS Code/Node.js/npm) outside of extension tutorial.

Steps that worked fine On my Machine™:

`yo code`
with next answers
```
? What type of extension do you want to create? New Extension (TypeScript)
? What's the name of your extension? test-fresh
? What's the identifier of your extension? test-fresh
? What's the description of your extension? 
? Initialize a git repository? No
? Bundle the source code with webpack? No       
? Which package manager to use? npm
```

Opened `src/extension.ts` in new file and pressed <kbd>F5</kbd>
![image](https://github.com/microsoft/vscode/assets/1312662/a191a91c-57e8-4550-bf44-493410a78fe7)

no global `tsc`
![image](https://github.com/microsoft/vscode/assets/1312662/eaac45c6-65da-4a4c-a23a-cd79700a3455)


Your case looks more like #85753 and linked #88290
-----

Point stays - VS Code extension development (and any TS developments in general) shouldn't rely on global `tsc` installation.

**Comment by oleg-alexandrov** [comment]
Thank you. Likely something on my side. Good to know at least there's no systematic bug. I will close this.
