### ISSUE TITLE
Hide "Split Editor Right" command in `editor/title` when a webview is active

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode#195961]
Today when a webview is active there isn't any way to hook/support/etc the "Split Editor Right" command automatically added to the `editor/title` 

![image](https://github.com/microsoft/vscode/assets/641685/a218de03-2b28-429b-af58-fb047c1cab3c)

It would be nice to hook into that command (though that is significantly more involved) -- so could we hide that command on webviews? That way extensions could provide their own split command, which I am now doing in GitLens, but there will end up being 2 split buttons -- one that works (mine) and one that doesn't.

Related is there any way for an extension to open an editor "below" the current one, like the "Split Editor Down" command does?

**Comment by eamodio** [comment]
Normal webview

**Comment by mjbvz** [comment]
Closing since we don't plan to address this anytime soon but contributions are still welcome
