### ISSUE TITLE
Feature request: Enable find dialog on extension information panel

### ISSUE THREAD

**Issue by marcelopm** [Microsoft/vscode#19598]
- VSCode Version:
Version 1.8.1
Commit ee428b0eead68bf0fb99ab5fdc4439be227b6281
Date 2016-12-19T14:41:20.664Z
Shell 1.4.6
Renderer 53.0.2785.143
Node 6.5.0

- OS Version:
Gnome Ubuntu 16.10

Steps to Reproduce:

1. Open the extension panel
2. Click on an extension to open the information panel
3. Click on Edit menu, select find or use the keyboard shortcut (i.e ctrl+f) but no search dialog pops up in the information panel

It would be great to be able to search for terms in the extension information panel in any of its tabs: details, contributions, changelog, etc

**Comment by joaomoreno** [comment]
This will likely not happen in the near future. Workaround: open the extension's Marketplace page in a browser and search in there.

**Comment by usernamehw** [comment]
Find Widget works in `Details` & `Changelog` now.

Issue reference for search in `Contribution` tab is #56163.
