### ISSUE TITLE
A newly created terminal shouldn't come with a warning

### ISSUE THREAD

**Issue by ulugbekna** [microsoft/vscode#195902]
# Description 

The terminal icon has a warning next to it because git couldn't contribute to its environment. This happens when I launch vscode and do nothing else.

![Image](https://github.com/microsoft/vscode/assets/16353531/a342c8f5-7a72-449a-9dd4-52b7850d0c2b)

https://github.com/microsoft/vscode/assets/16353531/613156fe-334d-4c5f-ac05-5011cdac1615

# Version

```
Version: 1.84.0-insider
Commit: f1c3b1dcf85e3b6ddb24b7dce0e4b122e8ce6233
Date: 2023-10-17T05:45:00.205Z
Electron: 25.8.4
ElectronBuildId: 24154031
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Darwin arm64 23.0.0
```

**Comment by Tyriar** [comment]
The terminal will relaunch itself when git initialized for the first time for a workspace, sometimes that's not possible though, I'm guessing it's because you had a restored terminal which cannot be relaunched due to previous content
