### ISSUE TITLE
Aux window: editor global stylesheet does not work

### ISSUE THREAD

**Issue by alexandruavadanii** [microsoft/vscode#195969]
Type: <b>Bug</b>

Steps to reproduce:
1. clone https://github.com/microsoft/vscode-extension-samples
2. open the `decorator-sample` in vscode
3. Launch it in Extension host
4. Check the decorators are applied in a regular editor and in a second editor open in an Aux window

The Aux window does not seem to get any decorations.
GIF:

![aux_window_decorators](https://github.com/microsoft/vscode/assets/11544783/692575d0-55a0-4c74-9a2f-5f684f201652)

I found this in the wild with one of my (private) extensions that displays inline annotations for each line, similar to the inline blame feature in GitLens.

VS Code version: Code - Insiders 1.84.0-insider (58bdf2c7c40be6f4494ae35a09528708832cf357, 2023-10-18T05:50:15.982Z)
OS version: Windows_NT x64 10.0.18362
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.81GB (6.41GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by bpasero** [comment]
Is there anything in the developer tools console of any of the windows or in the network tab that could hint to the issue?

**Comment by alexandruavadanii** [comment]
Nothing in the debug console. I have 3 x `View not found` errors in the Developer Tools console, but I'm not sure those are related. They are definitely not triggered when I edit the document.

I can see that the `updateDecorations` function is triggered correctly, `activeEditor` is set, but it might be pointing to the editor in the main window ...

Unfortunately, I can't dig deeper right now.

**Comment by bpasero** [comment]
I can reproduce and it seems to be missing CSS styles:

<img width="792" alt="image" src="https://github.com/microsoft/vscode/assets/900690/2ac3656b-1c3d-4028-9365-b1987dadac5e">

Not even chrome devtools can tell me where this style is coming from 🤯 

@hediet @alexdima can you tell me?

**Comment by bpasero** [comment]
I think the styles cannot be found because they are in a global stylesheet that is not part of the DOM:

https://github.com/microsoft/vscode/blob/88ab0de44c994f03e62418af0963845157c8ad8f/src/vs/editor/browser/services/abstractCodeEditorService.ts#L129-L131

Can we this stylesheet part of the editor it is provided for?

Unfortunately global stylesheets like this will not be automatically synced to the floating windows.

**Comment by alexandruavadanii** [comment]
Nice find! Could this be related to _Developer: Toggle Screencast Mode_ only working in the main window, or is that a different issue?
The behavior is similar - pressing keys in the main window works like intended, pressing keys in the Aux window does not show the overlay.

**Comment by bpasero** [comment]
Can you report that as a new issue, I think screencast mode needs to adopt floating windows still.

**Comment by alexandruavadanii** [comment]
@bpasero Sure: https://github.com/microsoft/vscode/issues/196087

**Comment by alexandruavadanii** [comment]
I assume the missing `FileDecoration` (badge, color) is also related to the global stylesheet.
However, I don't know whether the missing `lock` icon is also related (the file is read-only in both editors though):

![image](https://github.com/microsoft/vscode/assets/11544783/4a6882fc-f0b5-4782-9492-50b00d83d043)

**Comment by bpasero** [comment]
Yeah it is all related to using stylesheets that are in the `head` element with using `style` and not `textContent`.

**Comment by alexandruavadanii** [comment]
I just noticed that in the latest build (9aacac64), this seems to have regressed.
@bpasero , I created https://github.com/microsoft/vscode/issues/197564 since this one is already closed.

**Comment by bpasero** [comment]
Thanks for the feedback!
