### ISSUE TITLE
Environment variable not expanded during task run

### ISSUE THREAD

**Issue by fredrikaverpil** [Microsoft/vscode#19594]
- VSCode Version: Code - Insiders 1.9.0-insider (e68cede8b65dc918332493146c2572a7e132a451, 2017-01-27T20:36:09.447Z)
- OS Version: Darwin x64 16.4.0
- Extensions:

|Extension|Author|Version|
|---|---|---|
|vscode-clock|Compulim|0.0.1|
|mayaport|JonMacey|1.0.0|
|vscode-docker|PeterJausovec|0.0.11|
|code-settings-sync|Shan|2.4.2|
|project-manager|alefragnani|0.13.1|
|python|donjayamanne|0.5.6|
|vscode-material-theme|fredrikaverpil|0.0.3|
|theme-material-theme|jprestidge|1.0.1|
|prettify-json|mohsen1|0.0.3|
|mel|sator-imaging|0.1.1|
|trailing-spaces|shardulm94|0.2.11|
|jinja|wholroyd|0.0.7|

---

Steps to Reproduce:

1. Use the provided `tasks.json` and cmd+shift+p "Run Task" `Expansion issue`

```json
{
    "version": "0.1.0",
    "tasks": [
        {
            "taskName": "Expansion issue",
            "command": "echo",
            "osx": {
                "args": ["$HOME"]
            },
            "windows": {
                "args": ["%HOMEDRIVE%%HOMEPATH%"]
            },
            "isShellCommand": true,
            "isBackground": false,
            "echoCommand": true,
            "showOutput": "always"
        }
    ]
}
```

Expected output is: `/Users/fredrik`
Actual output is: `$HOME`

I don't know if this is perhaps not a finished feature yet, but I figured I'd mention it as I'm able to use environment variables in vscode 1.8 - and this is super useful.

**Comment by dbaeumer** [comment]
The 1.9 release will have preliminary support to execute tasks in the terminal instead the output window which will do proper shell variable expansion. A tasks.json  that support this on 1.9 looks like this (observer the _runner property)

{
    "version": "0.1.0",
    "echoCommand": true,
    "_runner": "terminal",
    "tasks": [
        {
            "taskName": "Expand Issue",
            "command": "echo %HOMEDRIVE%%HOMEPATH%",
            "isShellCommand": true,
            "isBackground": false
        }
    ]
}

and prints:

![capture](https://cloud.githubusercontent.com/assets/1931590/22462692/a4eefcd2-e7ae-11e6-9e5c-bb50ca4019c8.png)

I will close the issue since it is covered by the execute task in terminal work.

**Comment by fredrikaverpil** [comment]
Ok, thank you.
