### ISSUE TITLE
Inline chat sparkle has no hover

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#195994]
* todays insiders
* hover over the sparke
* :bug: nothing... I would expect that it shows the title like "Start Inline Chat" and also the key binding

**Comment by rzhao271** [comment]
The current merged PR doesn't update the decoration keybinding when the keybinding changes.


![Difference shown between sparkle hover keybinding and inline suggested keybinding](https://github.com/microsoft/vscode/assets/7199958/206e8d12-c20c-4bf3-81a2-4155d8ee6752)

**Comment by aiday-mar** [comment]
Fixes

**Comment by aiday-mar** [comment]
To verify:

- set `inlineChat.showGutterIcon` to `always` or `mouseover` and verify that the keybinding appear in the hover
