### ISSUE TITLE
Sticky Parent folders in folder tree view

### ISSUE THREAD

**Issue by BenBE** [microsoft/vscode#195927]
When a project has many files in a folder it can become a bit cumbersome to navigate to the parent folder as that item may not usually be in view. To mitigate this it would be nice if all parent folders could be sticky at the top of the folder view similar to how function signatures and code blocks can be made sticky in the code view.

**Comment by lramos15** [comment]
Duplicate https://github.com/microsoft/vscode/issues/194903
