### ISSUE TITLE
[Accessibility] Document format is announcing aria alert even when audio cue is enabled

### ISSUE THREAD

**Issue by jooyoungseo** [microsoft/vscode#196039]
CC @meganrogge

When pressing alt+shift+F, I still hear aria alert even when audio format cue is enabled.

**Comment by meganrogge** [comment]
Oh interesting, VoiceOver isn't announcing aria alerts for me. I tried on Windows and see "Made 1 formatting edit on lin 178" etc. I wasn't aware this alert existed, but it can be removed entirely since we now alert the less verbose "Formatted".

**Comment by amunger** [comment]
I'm having "Saved" narrated for every auto-save. 
"Formatted" is announced when audio-cues are disabled (Sounds like that is expected).

**Comment by meganrogge** [comment]
@amunger that's expected
