### ISSUE TITLE
Ctrl+`  toggle terminal Shortcut key failure

### ISSUE THREAD

**Issue by legendlink** [Microsoft/vscode#19607]
- VSCode Version: 1.8.1
- OS Version: Windows 10.0.10586

Steps to Reproduce:

1. open vscode
2. switch to another program, then switch back to vscode, the **Ctrl+`** will out of action

It always happen. When I launch vscode, I can use the "Ctrl+`" normally. Once I switch to another program then switch back to, the "Ctrl+`" will out of action. I must use the Ctrl+Shift+P and enter ">view: toggle integrated terminal" to toggle terminal.

**Comment by Tyriar** [comment]
Is this a new problem or was it always like this? Also are you on a US keyboard layout?

**Comment by legendlink** [comment]
It always happen. When I launch vscode, I can use the "Ctrl+`" normally. Once I switch to another program then switch back to, the "Ctrl+`" will out of action. I must use the Ctrl+Shift+P and enter ">view: toggle integrated terminal" to toggle terminal.
