### ISSUE TITLE
Allow to disable auto format of specific block in source code

### ISSUE THREAD

**Issue by VadimPanov** [microsoft/vscode#196006]
Sometimes it is very important not to allow autoformat to touch certain block of code as it affects the way the developed application is working. In our case this is texts in .html files, for example, for us:

`<div>Some text here that shall be untouched</div>`

is not the same as

`<div>Some text here that \n
shall be untouched</div>`

Can something be implemented to prevent auto-formatting from processing a block of code? For example this may be implemented:

< !-- [vscode do-not-format-block-begin] -->
`<div>Some text here that shall be untouched</div>`
< !-- [vscode do-not-format-block-end] -->

?

**Comment by aeschli** [comment]
This depends on the formatter that is used.
For the built-in HTML formatter (based on JSBeautify) you can do this:
```
- add special comments
<!-- beautify ignore:start -->
<div>
    <p>Your HTML code here...</p>
</div>
<!-- beautify ignore:end -->
```
- exclude certain tags from being formatted:
Use the `html.format.unformatted` setting
