### ISSUE TITLE
The window terminated unexpectedly (reason: 'killed', code: '15')

### ISSUE THREAD

**Issue by CorneliusDeng** [microsoft/vscode#196057]
Does this issue occur when all extensions are disabled?: No

- VS Code Version: 1.83.1
- OS Version: macOS Sonama 14.0 with M2

Steps to Reproduce:

1. Install extension Jupyter, include 4 packs
2. Install extension Python、Pylance、MagicPython
3. Open any file in any folder, whether ipynb or py
4. The crash appears: 
![bug](https://github.com/microsoft/vscode/assets/107790129/56163f6e-db75-49ae-9351-69f3c73f9053)

Strangely enough, I don't disable any extensions, but instead use the "Remote-SSH" extension to connect to the remote server and go through the above steps, the bug doesn't show up. The server is 18.04.1-Ubuntu, by the way.

After executing “Extension Bisect”, I find the reason is extension "Pylance". After disabling it, the crash does not appear in local.

**Comment by RO-29** [comment]
I am having the same issue on my Mac but it does not stay open long enough even to run bisect, I am stuck on the termination screen with exact same message.

I am running the latest vs code on mac 14.0 (23A344)

**Comment by RO-29** [comment]
I finally manged to make it start by guessing that pylance is causing the crash after seeing above issue and voila it works !


```code --disable-extension ms-python.vscode-pylance```

**Comment by fakhar-github** [comment]
> I finally manged to make it start by guessing that pylance is causing the crash after seeing above issue and voila it works !
> 
> `code --disable-extension ms-python.vscode-pylance`

I am having the same issue. I tried to disable pylance but it did not work me

**Comment by CorneliusDeng** [comment]
> > I finally manged to make it start by guessing that pylance is causing the crash after seeing above issue and voila it works !
> > `code --disable-extension ms-python.vscode-pylance`
> 
> I am having the same issue. I tried to disable pylance but it did not work me

Maybe you should try “Extension Bisect” and check this question "Does this issue occur when all extensions are disabled?"

**Comment by flodaniel** [comment]
I also have this issue and Extension Bisect could not identify any issues with extensions.
As far as my observation goes, it happens if i have to separate windows of vscode open.

**Comment by deepak1556** [comment]
Should be addressed in next pylance release with https://github.com/microsoft/pylance-release/issues/4983, please follow that issue for updates.

**Comment by KayO-GH** [comment]
The issue was the pylance version from 19th October 2023 for me.
My window was not staying open long enough to disable it, so I opened a folder that had nothing to do with python in VS Code using `code .` in the terminal and then switched to the Pylance version from a week earlier.  
It's working okay now.

**Comment by neilyoung** [comment]
I'm having the same issue since today (Oct 20). Also on Mac OS 14. With all Python projects. 

```
code --disable-extension ms-python.vscode-pylance
```

did also work for me. What I saw all the time shortly before the crash was a red coloured "Select Interpreter" in the footer.

> Code using code . in the terminal and then switched to the Pylance version from a week earlier.

This also did the job.

**Comment by Ar4l** [comment]
Issue still occurs with all extensions disabled for me.

**Comment by Messjer** [comment]
I experienced the same issue. Thanks for posting it.

**Comment by modusCell** [comment]
I experienced the same issue.

`code --disable-extension ms-python.vscode-pylance`

Did also work for me.

**Comment by gbolla-sms** [comment]
> The issue was the pylance version from 19th October 2023 for me. My window was not staying open long enough to disable it, so I opened a folder that had nothing to do with python in VS Code using `code .` in the terminal and then switched to the Pylance version from a week earlier. It's working okay now.

This is working for me as well, and has benefit of not disabling the extension altogether.

**Comment by loda13** [comment]
The plugin has been updated and the issue has been resolved after the update.
