### ISSUE TITLE
Missing button hover animation for minimize, maximize/restore window buttons with custom window title bar style

### ISSUE THREAD

**Issue by uRohan** [microsoft/vscode#196080]
Type: <b>Bug</b>

1. Move your mouse pointer over the minimize, maximize/restore window buttons.
2. Observe the absence of the button hover animation.

[Example](https://github.com/microsoft/vscode/assets/11392016/1720ac53-7cf9-4999-8b70-a70765d4e5f2)

VS Code version: Code - Insiders 1.84.0-insider (8e11b537e3b091a8b52c7179fb623ecdeecaf4ea, 2023-10-20T06:55:34.457Z)
OS version: Linux x64 6.2.0-35-generic snap
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3610QM CPU @ 2.30GHz (8 x 1499)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|1, 1, 0|
|Memory (System)|7.63GB (5.53GB free)|
|Process Argv|--no-sandbox --force-user-env --unity-launch --crash-reporter-id 438f81b5-87e7-4af3-ab4d-00ca9dbb6ea3|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vslsvsres303:30308271
pythontb:30258533
pythonptprofiler:30281269
vshan820:30294714
vscod805:30301674
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30404738
py29gd2263:30784851
vscaat:30438846
vsclangdf:30492506
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30618038
a9j8j154:30646983
showlangstatbar:30737417
57b77579:30687741
pythonfmttext:30716741
fixshowwlkth:30771523
showindicator:30805243
pythongtdpath:30726887
i26e3531:30792625
welcomedialog:30812478
pythonnosmt12:30779711
pythonidxpt:30768918
pythonnoceb:30776497
copilotsettingt:30808721
asynctok:30821568
dsvsc013:30777762
dsvsc014:30777825
diffeditorv2:30786206
pythonmhint1:30859868
dsvsc015:30821418
pythontestfixt:30866404
pyreplss1:30865275
pythonmypyd1:30859725
pythoncet0:30859736
pythontbext0:30864172

```

</details>

**Comment by sbatten** [comment]
I was not able to reproduce with the latest snap release on ubuntu. please let me know if you continue to reproduce.

**Comment by uRohan** [comment]
I can still reproduce the issue, but only using the default "Light Modern" theme. So, it looks like this is the problem of the default "Light Modern" theme.

Initially, I thought the animation was missing, but if you look closely it's there. However, the transition states are so subtle, they're barely visible.

VS Code Version:

```text
Version: 1.85.1
Commit: 0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2
Date: 2023-12-13T09:47:11.635Z
Electron: 25.9.7
ElectronBuildId: 25551756
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Linux x64 6.2.0-39-generic snap
```

VS Code Insiders Version:

```text
Version: 1.86.0-insider
Commit: 9621add46007f7a1ab37d1fce9bcdcecca62aeb0
Date: 2023-12-20T05:36:34.875Z
Electron: 27.1.3
ElectronBuildId: 25612240
Chromium: 118.0.5993.159
Node.js: 18.17.1
V8: 11.8.172.18-electron.0
OS: Linux x64 6.2.0-39-generic snap
```

**Comment by alexr00** [comment]
I couldn't repro this with stable, but I also couldn't repro with insiders, so marking as verified.
