### ISSUE TITLE
Laravel codes shows issues

### ISSUE THREAD

**Issue by mukeshmtech** [microsoft/vscode#196061]
I am using Laravel for code development, but I am facing some issues. The steps to reproduce the issues are as follows:
**Steps1**
use Auth,Validator,Password,DB;
**Step2**
        \DB::beginTransaction();
         Auth::guard('vendor')->loginUsingId($login->vendoruserID);
DB, the Auth namespace shows a red mark error. I have used some extensions, but it still shows the error. However, actually it is not an error.

![image](https://github.com/microsoft/vscode/assets/139348021/4744df2c-675b-4835-8fbd-7fc7e36e22b3)

**Comment by roblourens** [comment]
Please file this on the extensions you're using
