### ISSUE TITLE
Markdown Snippets from "Markdown Language Basics" are not configured with a prefix

### ISSUE THREAD

**Issue by mjmatthiesen** [microsoft/vscode#196095]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.83.1
- OS Version: Windows 10

Steps to Reproduce:

1. Enable IntelliSense for markdown
2. Type common words like code or bold or list
3. Start getting bad snippet suggestions.
4. Snippets should be prefixed, often with t, but not having one at all is an issue for regular typing.

Temporary resolution, hide these awful snippets, make my own with a sensible prefix.

![image](https://github.com/microsoft/vscode/assets/16603906/b7cfe2a5-3283-4c6e-9b75-3d45f9828245)

**Comment by mjbvz** [comment]
I don't understand the issue. Is it just that you aren't seeing snippets suggestions when you type in a markdown file?

**Comment by mjmatthiesen** [comment]
> I don't understand the issue. Is it just that you aren't seeing snippets suggestions when you type in a markdown file?

No. The steps clearly state that intellisense is enabled, so I see snippet and snippet suggestions. The issue comes from the snippets not following what I would call the standard convention. Every other extension I've got installed prefixes their snippets so they don't overlap with words you may otherwise use. e.g. markdown uses the word code as a snippet, but there's like 8 million reasons I might type code, but zero for typing tcode.
