### ISSUE TITLE
php short open tags

### ISSUE THREAD

**Issue by phpfalcon** [Microsoft/vscode#19603]
- VSCode Version:Version 1.9.0-insider (1.9.0-insider)
- OS Version: MacOS 10.12.2

is it possible to disable "php" short open tags ( <? )

**Comment by roblourens** [comment]
This is late but, what do you mean "disable short open tags"?

**Comment by phpfalcon** [comment]
http://php.net/manual/en/language.basic-syntax.phptags.php

In vscode you can use <? Or the long tag <?php but you can’t config it to allow only the long tag .. however In php.ini you can disable the short tag <? and the editor won’t  care and handling it as everything works fine . if you run it in php you’ll get run time error  ... It’s an old issue anyway and I use both tags now 👍 thanks

**Comment by roblourens** [comment]
I see, didn't realize you could disable it. I think it would make the most sense for an extension to implement this.
