### ISSUE TITLE
Windows 10 Multiple Desktops issue

### ISSUE THREAD

**Issue by wessiyad** [Microsoft/vscode#19604]
On Windows 10 I have multiple desktops set up.  On desktop 1 I had an instance of VSCode open.  I switch to desktop 2 and try to start another instance of VSCode but it switches me back to desktop 1 and the previously opened instance of code.  Would expect to open another instance that is pinned to desktop 2.

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/14619
