### ISSUE TITLE
`Open File` action fails to restore editor position

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#196084]
When using the new diff editor with `diffEditor.hideUnchangedRegions.enabled` enabled, I very rarely get to the right editor position whenever I click the top `Open File` action, above the editor.

https://github.com/microsoft/vscode/assets/22350/e8c61efd-38da-4a5b-9e84-d7a7f27c0694

**Comment by hediet** [comment]
You mean go to reference is broken?

**Comment by bpasero** [comment]
@hediet diff editors have an action to open the original file (I think contributed from SCM?). When clicking that, expectation is that the current view state of the diff editors right hand side applies to the opening editor so that you stay in exactly the same view state.

<img width="140" alt="image" src="https://github.com/microsoft/vscode/assets/900690/0d576772-14d3-4a53-9314-9647b002e29c">

**Comment by mnoorenberghe** [comment]
I really like the collapsed diff editor but this is a very frustrating regression from it which make me want to shut it off. The issue is 100% reproducible in my usual workflow and I encounter this issue many times per hour.

**Comment by hediet** [comment]
I can reproduce. The "Open File" command is a mystery to me, and it never seemed to have worked properly.

Debugging shows me that `openEditor` is called twice, but both times with unhelpful stack traces:
https://github.com/microsoft/vscode/blob/10ddce6696c7a66b8f6d9965529ff00c97c967db/src/vs/workbench/services/editor/browser/editorService.ts#L517

![Code_-_Insiders_7lL70sf4Py](https://github.com/microsoft/vscode/assets/2931520/74ad50b9-68e7-49f0-9b87-d2ad20b53586)

![Code_-_Insiders_fCXav6g5y4](https://github.com/microsoft/vscode/assets/2931520/a33f69a3-f137-4681-9a0c-12eac5f8d83b)

The second invocation sets `options.selection`. However, there is no reveal mechanism.

**Comment by hediet** [comment]
Further investigation showed that the "Open File" action is actually implemented in the git extension (even when comparing two files on disk) :/
Which I think is very questionable design, as it should be a core diff editor feature.
