### ISSUE TITLE
Aux window: split window side by side isn't perfect

### ISSUE THREAD

**Issue by MrYuto** [microsoft/vscode#196062]
This issue comes from `window.open`. for some reason, it adds some margin on the sides except the top. I suspect maybe this is a Windows issue because Firefox has the same behavior.

![PowerToys MeasureToolUI_9gbefWRlV4](https://github.com/microsoft/vscode/assets/75252297/8c68ccf7-7f00-4d17-bab3-66f2a5962c06)

With some trial and error, I was able to remove the space between left and right, but the bottom only when I gave the top a `7px` offset. Although it's possible to give all sides the `7px` margin to make it even:

![explorer_JM7vuSL1s7](https://github.com/microsoft/vscode/assets/75252297/fda500f2-0952-4cb1-b3cc-fcfa6094615b)

```ts
// First position the active window which may involve
// leaving fullscreen mode and then split it.
await nativeHostService.positionWindow({
	x: 7,
	y: 7,
	width: activeWindow.screen.availWidth / 2 - 7,
	height: activeWindow.screen.availHeight - 14
}, { targetWindowId: activeWindowId });

// Then create a new window next to the active window
const auxiliaryEditorPart = await editorGroupService.createAuxiliaryEditorPart({
	position: {
		x: activeWindow.screen.availWidth / 2 - 7,
		y: 7,
		width: activeWindow.screen.availWidth / 2 + 7,
		height: activeWindow.screen.availHeight - 7
	}
});
```

**Comment by bpasero** [comment]
Yeah and on top of these issues I am thinking to change the command to split the window exactly in half or rename it to make the intent clear. It was added for now mainly to make development a bit easier because I constantly keep arranging my 2 windows when developing :-).

**Comment by alexandruavadanii** [comment]
I think I see the same behavior (and then some) on my machine (Windows 10):

Case A: vscode main window full screen on my primary monitor.
- Open a text file and use `View: Split Windows (Experimental)`;
- Main vscode window remains full screen, aux window appears occupying "approximately" half of the screen on the right, overlapping the main window; there is some unexpected margin both on the right side of the screen and the bottom;
- trying to use `Windows` + `right arrow` to move the main vscode window to the left half side of the screen sort of works, but the main vscode window is now confused about its size and seems to overlap with the taskbar and also go a bit outside the screen:

![image](https://github.com/microsoft/vscode/assets/11544783/88b830a2-d404-4e0d-89ca-c7c61ffe7831)

Case B: vscode main window full screen on my secondary monitor.
- Open a text file and use `View: Split Windows (Experimental)`;
- Main vscode window remains full screen, _but moves to the primary monitor_, aux window appears (also on the primary monitor) same as above;

**Comment by bpasero** [comment]
Since this is a dev action for now that I will likely remove, opened https://github.com/microsoft/vscode/issues/196579 for the actual feature. Feel free to post your ideas there.
