### ISSUE TITLE
Test: recursive file watcher with custom exclude rules

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#196194]
Refs: https://github.com/microsoft/vscode/issues/169609

- [x] macOS @ulugbekna 
- [x] linux @sbatten
- [x] windows @bhavyaus

Complexity: 4

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23196194%0A%0A&assignees=bpasero)

---

A new file watcher proposed API is added that allows fully recursive file watching even inside the workspace with custom exclude rules. Previously, we would simply ignore recursive watch requests for paths inside the workspace, because we already watch the workspace by default. However, we also exclude certain paths by default (such as `node_modules` folder) and so an extension in some cases has no way of watching these excluded paths that are inside the workspace.

**Setup:**
* [Create an extension guide](https://code.visualstudio.com/api/get-started/your-first-extension)
* [Extensions samples repo](https://github.com/Microsoft/vscode-extension-samples)
* Add a proposed API:
  * First add the proposed API to the `package.json` (see below)
  * Then run `npx vscode-dts dev` to get the typings
```json
	"enabledApiProposals": [
		"createFileSystemWatcher"
	],
```

**Testing:**
* make sure to leverage the new API of `createFileSystemWatcher` with the `FileSystemWatcherOptions` option
  * for testing you can simply print the file events to the console
* to enable recursive watching, make sure to use a `pattern` in the `RelativePattern` that contains `**` in any of the segments
* create recursive watchers for folders inside and outside the workspace and pass in `excludes` via the `FileSystemWatcherOptions` option
* verify you get file events for paths that are not excluded via your options
* create recursive watchers for folders inside and outside the workspace and do NOT provide `excludes` option
* verify that the default exclude rules of the `files.watcherExclude` setting apply now

**Comment by sbatten** [comment]
Unassigning for now, but since my issues either need to be addressed or I had user error, please reassign me if you want additional testing.

**Comment by meganrogge** [comment]
I'm going to wait for your reply on these issues @bpasero before testing further

**Comment by bhavyaus** [comment]
- Recursive file watching within the workspace worked for me. 
-  Watching files outside the workspace did not work for me as mentioned in: https://github.com/microsoft/vscode/issues/196466
- Default excludes from `files.watcherExclude` is respected when watching files.

**Comment by bpasero** [comment]
@meganrogge @sbatten sorry for some of the confusion, file watchers are quite complex to deal with. I think partially you ran into expected behaviour and for one issue there is a fix coming in today, so please test again tomorrow if possible.

If have commented in all of the issues you filed.

**Comment by ulugbekna** [comment]
@meganrogge I tested it to make sure TPI is completed today, but if you have time, maybe you could also test more
