### ISSUE TITLE
VSCode doesn't respond when opening a Git repo

### ISSUE THREAD

**Issue by RaphMar2021** [microsoft/vscode#196156]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: VSCodium 1.83.1 (tried to downgrade to 1.81 but same) (same happens with Microsoft's VSCode version)
- OS Version: Ubuntu 23.10.1

Steps to Reproduce:

1. Install Ubuntu 23.10.1 & VSCode
2. Open a Git repo in VSCode

Additional Infos:
* The bug seems to affect only Ubuntu 23.10.1 as it works fine when opening on Windows 11 build 23570

Screenshot:
![image](https://github.com/microsoft/vscode/assets/81994075/ef74f3db-8b2b-4268-b014-9abecf2286b8)

**Comment by hlovdal** [comment]
Does this happen for just one/some/all git repositories?

**Comment by RaphMar2021** [comment]
It's one but fixed the problem

**Comment by ThomasLeconte** [comment]
Hi ! How did you fixed the problem ? I have it too

**Comment by RaphMar2021** [comment]
I just installed GitHub extension by clicking on Codespaces
