### ISSUE TITLE
Test: protocol link confirmations

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#196192]
Refs: https://github.com/microsoft/vscode/issues/95670

- [x] macOS @daviddossett
- [x] linux @karthiknadig
- [x] windows @brettcannon (Optional)
- [x] windows @lszomoru

Complexity: 3

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23196192%0A%0A&assignees=bpasero)

---

This test plan item is for protocol links, both local and remote, of this form:
* local: `vscode-insiders://file/<path>`
* remote: `vscode-insiders://vscode-remote/<authority>/<path>`

You can trigger protocol links for example by pasting such a URL into the browser URL bar and confirming the operation from the browser. Alternatively you can have a markdown document in VS Code with a link element and then ctrl-click on the URL.

For this test, please:
* test with both `local` and `remote` links (`remote` links do not need a valid authority for the testing purpose here)
* test outside the app via browser and inside via markdown link

**Testing**
* you now get a dialog asking for confirm the opening of the link that you can confirm to proceed or cancel to cancel the opening
* you see a checkbox for permanently confirming
  * this will update a `security.promptForLocalFileProtocolHandling` setting for `local` links
  * this will update the `security.promptForRemoteFileProtocolHandling` for `remote` links
  * once set, you are no longer asked for `local` or `remote` links respectively
* verify the wording of the dialog and setting makes sense to you

**Comment by brettcannon** [comment]
I wasn't able to verify remote URLs due to not knowing what "authority" represented.

**Comment by bpasero** [comment]
An example would be: `vscode://vscode-remote/ssh-remote+[USER@]HOST[:PORT]/path/to/file`

**Comment by lszomoru** [comment]
Tested with local links and remote (WSL) links. Everything worked as expected.
