### ISSUE TITLE
Markdown scopes are broken after `<script></script>`

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#19612]
- VSCode Version: Code - Insiders 1.9.0-insider (3af0e9d6b79145011a7be3970c1d4b83d69b0443, 2017-01-27T10:36:54.755Z)
- OS Version: Linux x64 4.8.0-34-generic
- Extensions:

|Extension|Author|Version|
|---|---|---|
|EditorConfig|EditorConfig|0.3.4|
|lorem-ipsum|Tyriar|1.0.0|
|theme-glacier|Tyriar|0.0.10|
|theme-material-neutral|bernardodsanderson|0.9.0|
|vscode-svgviewer|cssho|1.3.0|
|python|donjayamanne|0.5.6|
|tslint|eg2|0.8.1|
|git-project-manager|felipecaputo|1.0.1|
|vsc-travis-ci-status|felixrieseberg|1.0.5|
|md-navigate|jrieken|0.0.1|
|vscode-scss|mrmlnc|0.6.0|
|csharp|ms-vscode|1.6.2|
|seti-icons|qinjia|0.1.3|
|java|redhat|0.0.9|
|annotator|ryu1kn|0.10.1|

---

Markdown scopes are broken after `<script></script>`

![image](https://cloud.githubusercontent.com/assets/2193314/22456123/53a45606-e745-11e6-8d0d-54bbe97a4243.png)

Test text:

```
<script src="something.js"></script>

[Markdown link](/not/scoped)
```

It should be scoped like this:

![image](https://cloud.githubusercontent.com/assets/2193314/22456140/7beff2a0-e745-11e6-9345-6ae983187b19.png)

**Comment by mjbvz** [comment]
Thanks @Tyriar 

Added logic to handle when the closing script tag is on the same line as the starting one

![screen shot 2017-01-31 at 11 26 41 am](https://cloud.githubusercontent.com/assets/12821956/22480971/294da7f0-e7a8-11e6-8b36-8941dd09e555.png)

**Comment by Tyriar** [comment]
Great! :smile:
