### ISSUE TITLE
Recommended extension is not displayed on the list

### ISSUE THREAD

**Issue by gorkem** [Microsoft/vscode#19613]
- VSCode Version: 1.8.1
- OS Version: MacOS 10.12.2

Steps to Reproduce:
0. Make sure that redhat.java extension is not installed
1. Open a .java file 
2. Observe that `It is recommended to install the 'Language Support for Java(TM) by Red Hat' extension.` message is displayed. Select `Show Recommendations`
3. redhat.java extension is not listed as part of the recommended extensions list, hence user can not install it.

**Comment by joaomoreno** [comment]
Great catch

**Comment by LeviDooley** [comment]
This isn't fixed.
![code_2017-04-05_14-35-24](https://cloud.githubusercontent.com/assets/18010173/24723468/43042894-1a0d-11e7-8def-fb3741cbedc9.png)
![code_2017-04-05_14-35-45](https://cloud.githubusercontent.com/assets/18010173/24723470/459a14ba-1a0d-11e7-9f15-e229c9e9bbfc.png)

Then, if I search for SQL, it isn't really clear what the proper extension is. If there even is one.

![code_2017-04-05_14-36-07](https://cloud.githubusercontent.com/assets/18010173/24723484/588cfd12-1a0d-11e7-9cfe-f41c9b519e11.png)

**Comment by KillyMXI** [comment]
1.13
Still here for SQL.

**Comment by sgronblo** [comment]
I think this still seems to be unfixed. I couldn't find any extension named "SQL" even when removing the `@recommendations` tag from the extension search.
