### ISSUE TITLE
Test: accessible view improvements

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#196124]
Refs #195288, #195401, #195990

- [x] Windows @andreamah 
- [x] macOS @isidorn 
- [x] Windows @joyceerhl 

Complexity: 4

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23196124%0A%0A&assignees=meganrogge)

---

The accessible view and accessibility help dialog can be opened by focusing a component (the terminal, chat response, etc.) and using `alt+f2` and `alt+f1`, respectively.

3 features have been added to make the accessible view flow more optimal, including:

---

A setting, `accessibility.hideAccessibleView` which allows a user to hide the accessible view while they interact with it. Imagine you are a blind professor and you're sharing your screen with your students. 

Verify that the accessible view can still be navigated:

- Enable a screen reader
- Focus a terminal
- Run some commands
- Open the accessible view (first try this without enabling the setting then with it enabled)
- Use arrow keys to navigate and make sure the screen reader is reading the contents

---

A setting, `terminal.integrated.accessibleViewPreserveCursorPosition`, which allows a user to determine what happens when they toggle between the terminal and the accessible view. 

- Verify that with the setting disabled, the accessible view always opens with the cursor on the last line of the buffer. -- Verify that with it enabled, the accessible view always opens with the cursor wherever you last had it (or is on the last line of the buffer on first open). 
- Verify if you focus a new terminal and open the accessible view, the cursor is on the last line of the buffer.
- Verify that information about this setting is included in the accessibility help dialog for the terminal.

--- 

A new behavior in which the accessible view will close when a single letter key is pressed - and is not part of a chord.

Verify that this works as expected by focusing a feature such as the terminal / chat response, opening the accessible view, and typing various keys. Make sure that accessible view actions like go to symbol still work (hover over the actions in the accessible view toolbar for ideas) and don't close the view.

**Comment by isidorn** [comment]
Works nicely 👏

**Comment by andreamah** [comment]
Awesome features!
