### ISSUE TITLE
Visual studio code terminal issue with screen reader 

### ISSUE THREAD

**Issue by yongshing32** [microsoft/vscode#196199]
Type: <b>Bug</b>

Hi team, 

I'm a screen reader user (using NVDA screen reader). 

Before this, on the terminal, I can press tab and shift tab to move between edit prompt and the output screen. Now, it doesn't work. the issue now is either tab or shift tab, it stuck on the edit prompt area. so I can't read the output. 

Could you fix that? 

VS Code version: Code 1.83.1 (f1b07bd25dfad64b0167beb15359ae573aecd2cc, 2023-10-10T23:48:05.904Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz (4 x 2712)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|7.90GB (1.37GB free)|
|Process Argv|--crash-reporter-id 3ad94506-bcb0-41d7-8972-76d97217466a|
|Screen Reader|yes|
|VM|0%|
</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-mysql|for|0.5.0
vsc-python-indent|Kev|1.18.0
vscode-docker|ms-|1.27.0
python|ms-|2023.18.0
vscode-pylance|ms-|2023.10.40
remote-containers|ms-|0.315.1
remote-wsl|ms-|0.81.8

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
py29gd2263cf:30856253
vscaat:30438848
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
3biah626:30602489
89544117:30613380
a9j8j154:30646983
showlangstatbar:30737416
03d35959:30757346
pythonfmttext:30731395
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
gsofa:30866041
pythonnosmt12:30797651
pythonidxpt:30866567
pythonnoceb:30805159
copilotsettingt:30859503
dsvsc013:30795093
dsvsc014:30804076
diffeditorv2:30821572
dsvsc015:30845448
pythontestfixtcf:30866406
pyreplss1:30865275
h48ei257:30867296
pythontbext0:30864172

```

</details>

**Comment by meganrogge** [comment]
We now allow using alt f2 / escape or ctrl / cmd up / down arrow to navigate between these to better align w other workbench components. 

You can add this blending if you prefer it.

**Comment by yongshing32** [comment]
Thanks so much for the info.
If you don't mind, I have a related question which is, how to clear
the history/buffer in the accessible output?
This is because, if I use command like cls or clear-host in powershell
terminal inside visual studio code, it doesn't clear the history
inside the accessible output (alt f2).
Therefore, how to clear the accessible output?

**Comment by meganrogge** [comment]
Good question. You can use the key binding associated with the command terminal: clear.

**Comment by yongshing32** [comment]
Yes, it works. Thank you so much.
