### ISSUE TITLE
CSP violation

### ISSUE THREAD

**Issue by b-wendo** [microsoft/vscode#196108]
Error loading webview: Error: Could not register service worker: SecurityError: Failed to register a ServiceWorker: The provided scriptURL ('https://0e667eqavdhf9u965fg8hb3th5tb61rmqg6kmq8c74h51rhj8amf.assets.github.dev/stable/f1b07bd25dfad64b0167beb15359ae573aecd2cc/out/vs/workbench/contrib/webview/browser/pre/service-worker.js?v=4&vscode-resource-base-authority=vscode-resource.vscode-cdn.net&remoteAuthority=codespaces+super-duper-acorn-wr74qj9w5p94f99w7') violates the Content Security Policy..

**Comment by mjbvz** [comment]
Closing as there's not enough context to investigate

**Comment by b-wendo** [comment]
Hello.
Sorry for the late reply.
The problem I am experiencing with my VS Code is that I am unable to
load/open any kind of images because of the error attached. I also not able
to open the CS50 Duck Debugger because of the same issue.

It says: The provided scriptURL violates Content Security  Policy.

**Comment by mjbvz** [comment]
Please follow this guide to provide additional information: https://github.com/microsoft/vscode/wiki/Submitting-Bugs-and-Suggestions

You can use the new issue template on GitHub to save time
