### ISSUE TITLE
Feature Request: I am using cucumber protractor for navigate cucumber to step definition 

### ISSUE THREAD

**Issue by harigowtham91** [Microsoft/vscode#19619]
Feature Request
I am not able to navigate to another method from feature file.  

scenario:
I have cucumber features in my feature file id i click or cont+click or double click this should not take to that method.

#cucumber #javascript #featurefile

**Comment by bpasero** [comment]
@harigowtham91 can you share what cucumber features is?

**Comment by rmunn** [comment]
Given that he mentioned Protractor, "cucumber features" are almost certainly `.feature` files as described here: https://cucumber.io/docs/reference

See also https://github.com/cucumber/cucumber-js and https://github.com/AndrewKeig/protractor-cucumber

**Comment by mjbvz** [comment]
We do not provide cucumber support out of the box. Please try filing this feature request against one of the cucumber extensions: https://marketplace.visualstudio.com/search?term=cucumber&target=VSCode&category=All%20categories&sortBy=Relevance
