### ISSUE TITLE
Python Debugger not showing numpy array values after update

### ISSUE THREAD

**Issue by graphic-goose** [microsoft/vscode#196159]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.83.1
- OS Version: Windows 11 22H2 build 22621.2428

Steps to Reproduce:

1. Create a simple Python script that generates a numpy array, such as:
    `import numpy as np
    
    test = np.zeros((3, 3))`

2. Set a breakpoint below the above code and run debug.

3. Expand the 'test' variable in the locals section of the 'Debug and Run' window.

5. Observe that below 'function variables' now no longer shows each row of the first axis of the array as it did in older versions. 

![VSCode_1_83_1](https://github.com/microsoft/vscode/assets/140783905/2a3032c3-c177-4e89-9989-bd528ab2b52d)

6. If the new 'T' item that's below 'function variables' is expanded, this just loops the information from the root level.

![VSCode_1_83_1_expand_loop](https://github.com/microsoft/vscode/assets/140783905/f9ed8d7f-7244-4b00-a82c-f39dd6924fd0)

For reference, this is what it looked like with version 1.80.2:

![VSCode_1_80_2](https://github.com/microsoft/vscode/assets/140783905/905d6d76-c80a-4f5e-a8cc-7ee632fbe60e)

**Comment by jaortizco** [comment]
I'm having the same issue using WSL2 (Ubuntu) on Windows 11.

VS Code Version: 1.83.1
Python extension version: v2023.18.0

**Comment by jav-ed** [comment]
I am having the same issue using linux manjaro with VSCode information, see below and Python 3.11.3

Version: 1.83.1
Commit: f1b07bd25dfad64b0167beb15359ae573aecd2cc
Date: 2023-10-10T23:45:31.402Z
Electron: 25.8.4
ElectronBuildId: 24154031
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Linux x64 5.15.128-1-MANJARO

**Comment by roblourens** [comment]
Please file this on the debugpy repo, thanks
