### ISSUE TITLE
Test: clear/format/save audio cues & alerts

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#196126]
Refs #189235, #195716, #194939

- [x] Windows @alexr00 
- [x] macOS @paulacamargo25 
- [x] Linux @TylerLeonhardt 

Complexity: 4

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23196126%0A%0A&assignees=meganrogge)

---

We have the following new settings:
- `audioCues.format`
- `audioCues.save`
- `audioCues.clear`
- `accessibility.alert.format`
- `accessibility.alert.save`

Verify that the format and save audio cues are described in the editor's accessibility help dialog `alt+f1` and as those setting values are changed, the text reflects that (on close and reopen of the dialog). 

Verify that the setting descriptions make sense and that the cues play / aria alerts are announced appropriately based on your configuration.  An example of an aria alert is the screen reader will say "formatted".

Try the format and save alert/cues in editors and notebooks. 

Try the clear alert/cues in the chat response panel, notifications list, and terminal.

**Comment by alexr00** [comment]
When should the clear audio cue play for the terminal?

**Comment by meganrogge** [comment]
@alexr00 when you the command: terminal clear.
