### ISSUE TITLE
Search Problems

### ISSUE THREAD

**Issue by rubenzablocki** [Microsoft/vscode#19611]
- VSCode Version: Code 1.8.1 (ee428b0eead68bf0fb99ab5fdc4439be227b6281, 2016-12-19T14:49:23.350Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

|Extension|Author|Version|
|---|---|---|
|vscode-angular2-files|alexiv|1.3.7|
|angulardoc-vscode|AngularDoc|1.2.0|
|vscode-opennewinstance|chrisdias|0.0.4|
|githistory|donjayamanne|0.1.4|
|code-beautifier|michelemelluso|1.6.2|

---

After of some new update there is a problem with serach engine. Search does't show any results. 
It has to be restarted to see any results.

Before restarting:
![image](https://cloud.githubusercontent.com/assets/8929046/22455672/6a794a00-e78e-11e6-9da4-9f2f0131333d.png)

After restarting: 
![image](https://cloud.githubusercontent.com/assets/8929046/22455698/90327aa0-e78e-11e6-8e31-288bd7813558.png)

**Comment by bpasero** [comment]
@rubenzablocki 
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: http://code.visualstudio.com/Download#insiders

**Comment by rubenzablocki** [comment]
Thank, i will test it and send you a feedback.

2017-01-31 10:05 GMT+01:00 Benjamin Pasero <notifications@github.com>:

**Comment by rubenzablocki** [comment]
No problems for now in version 1.9.0 Isider

2017-02-01 15:10 GMT+01:00 Ruben Zabłocki <ruben.zablocki@gmail.com>:
