### ISSUE TITLE
HTML TAG TRACK

### ISSUE THREAD

**Issue by PolymathWhiz** [Microsoft/vscode#19614]
- VSCode Version: 1.8.1
- OS Version: macOS 10.12.2

Steps to Reproduce:

1. Unable to track which where an HTML tag started and ended from.

**Comment by bpasero** [comment]
@PolymathWhiz can you be more specific what you want?

**Comment by PolymathWhiz** [comment]
When I create a tag in html, I can't tell where the tag is ended. For example, if i have four <p> </p> tags... I can't see where the second tag was ended in my program

**Comment by PolymathWhiz** [comment]
p tags* ... The html got deleted

**Comment by aeschli** [comment]
We currently highlight the start and ending tag. Are you saying that is not good enough, or not working?
Maybe add a screenshot that shows a problematic scenario and propose how an improvement would look like?

**Comment by PolymathWhiz** [comment]
It doesn't seem to work for me. I'm on vscode v1.9.1

**Comment by aeschli** [comment]
Screenshot? Are you sure you are in an HTML file or is it a PHP file?
![image](https://cloud.githubusercontent.com/assets/6461412/23248233/9c60ac62-f99e-11e6-9a08-3cf8f3064701.png)

**Comment by PolymathWhiz** [comment]
For instance, when you place your cursor on an "li" tag, It highlights all
"li" tags in the program instead of it matching the exact match of it

On 23 Feb 2017 7:04 a.m., "Martin Aeschlimann" <notifications@github.com>
wrote:

Screenshot? Are you sure you are in an HTML file or is it a PHP file?
[image: image]
<https://cloud.githubusercontent.com/assets/6461412/23248233/9c60ac62-f99e-11e6-9a08-3cf8f3064701.png>

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/Microsoft/vscode/issues/19614#issuecomment-281912193>,
or mute the thread

**Comment by aeschli** [comment]
![image](https://cloud.githubusercontent.com/assets/6461412/23250616/303265e2-f9aa-11e6-9dde-84415375ddea.png)

Are you sure you are in an HTML file or is it a PHP file?

**Comment by aeschli** [comment]
Closing. Please add a screenshot if you see something different, best along with a code snippet
