### ISSUE TITLE
Test runs when clicking on a breakpoint to remove it if it's on the same line as test run icon

### ISSUE THREAD

**Issue by mahmoudsalah1993** [microsoft/vscode#196138]
Does this issue occur when all extensions are disabled?: No

- VS Code Version: Version: 1.83.1 (Universal) Commit: f1b07bd25dfad64b0167beb15359ae573aecd2cc
- OS Version: MacOS ventura 13.6

Steps to Reproduce:

1. Open a test file with discovered tests.
2. Right click on the same line as the test run icon.
3. Right click on the gutter and select Add Breakpoint.
4. Click on the breakpoint to remove it.

Expected:
The breakpoint gets removed.

Actual:
The test is invoked as if the green test icon is clicked.

https://github.com/microsoft/vscode/assets/13228044/23570108-f8f2-4575-9233-32c5cef8efe1

**Comment by gjsjohnmurray** [comment]
Related to #185814

**Comment by connor4312** [comment]
Duplicating into there
