### ISSUE TITLE
Aux window: Chord timeout much smaller in aux window

### ISSUE THREAD

**Issue by alexandruavadanii** [microsoft/vscode#196184]
Type: <b>Bug</b>

Chords _do_ work in aux windows, as long as the second keypress is within a very short time window after the first key press (<1s ?).

How to reproduce, e.g. using `Ctrl`+`K`, `Ctrl`+`F` to format a text selection:
1. Open any source file in an aux window, break the formatting for demo purposes;
2. Press `Ctrl` + `K`, wait 1-2 seconds then press `Ctrl` + `F` and the `Find` input shows up;
3. Optionally, retry pressing `Ctrl` + `K`, then `Ctrl` + `F`, but this time really fast to see that the chord is working (in case you have custom keybindings);

Watching the main window status bar, which normally contains `(Ctrl+K) was pressed. Waiting for second key of chord...` for a few seconds, for the aux window the message goes away really fast after the first key was pressed.
You may repeat this in the main window for a comparison, the difference should be quite obvious.

I haven't customized the chord timeout.

Edit: as a simple user, I don't have the rights to add the https://github.com/microsoft/vscode/labels/workbench-auxwindow label, but mentioning it here might help with the triage.

VS Code version: Code - Insiders 1.84.0-insider (8e11b537e3b091a8b52c7179fb623ecdeecaf4ea, 2023-10-20T05:34:58.027Z)
OS version: Windows_NT x64 10.0.18362
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.81GB (5.98GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
cpptools|ms-|1.16.3

</details>

**Comment by bpasero** [comment]
I can reproduce 👍
