### ISSUE TITLE
Test: floating windows exploration

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#196195]
Refs: 

- [x] macOS @meganrogge
- [x] linux @chrmarti
- [x] windows @rzhao271
- [x] web @rebornix

Complexity: 5

Authors: @bpasero, @Tyriar 

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23196195%0A%0A&assignees=bpasero,Tyriar)

---

There is now limited support to move an editor into an auxiliary window to have it side by side to the main window. You can trigger the command "Move Active Editor into New Window" for this:

<img width="603" alt="image" src="https://github.com/microsoft/vscode/assets/900690/75e6235f-ae27-4e62-ba3b-acf1e61af4cb">

This feature is relatively new and currently only enabled in insiders. We use [`workbench-auxwindow`](https://github.com/microsoft/vscode/issues?q=is%3Aopen+is%3Aissue+label%3Aworkbench-auxwindow) label to track issues and some larger pieces are not there yet:
* no restoration of windows and editors
* `iframe` based editors are not supported yet
* no status bar or custom title bar

**Testing:**
* overall: give floating windows a good exploratory testing with as many windows as you like and watch for general issues or error output in the devtools console (errors from the floating window will be visible in the main window console)
* smoke test the text code editor in floating windows
  * keybindings should work properly
  * editor features such as selection, multi-cursor, inline-editors, minimap, decorations, etc. should work as usual
  * compare visual presentation of the editor in the floating window to the same editor in the main window and see if anything is missing
* smoke test terminal editors in floating windows (you can open a terminal via "Create new terminal in terminal area")
  * compare visual presentation of the terminal in the floating window to the same editor in the main window and see if anything is missing
* test editor UI features such as drag and drop of editors or editor groups across windows and make sure that works
* verify that `iframe` based editors such as notebooks or custom editors show an error when opening inside floating windows
* ensure that quick open and dialogs appear on the window that has focus
* ensure that the window title in each window always reflects the currently active editor of that window
* ensure CSS changes apply properly across all windows (you can test this by changing the theme)
* ensure window zoom setting is applied to all windows
* from the "Open Editors" view in the explorer (you might have to make it visible from the view menu), verify
  * that you see all editor groups across all windows, indicated by specific labels per-window as needed
  * clicking any editor will move the owning window to the top (desktop only unfortunately)
  * double-clicking any editor will focus on the editor from the owning window

**Comment by meganrogge** [comment]
Overall, really cool 👏
