### ISSUE TITLE
[themes] workbench.colorTheme written to settings despite autoDetectColorScheme being set

### ISSUE THREAD

**Issue by osnyx** [microsoft/vscode#196119]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: VSCodium
  Version: 1.83.1
  Release: 23285
  Commit: 36d13de33ac0d6c684f10f99cff352e2f58228b3
  Date: 2023-10-12T18:10:10.352Z
  Electron: 25.8.4
  ElectronBuildId: undefined
  Chromium: 114.0.5735.289
  Node.js: 18.15.0
  V8: 11.4.183.29-electron.0
  OS: Darwin arm64 22.6.0
- OS Version: macOS Ventura 13.6

I have configured my VSCode/VSCodium settings to make it follow the system's light/dark color scheme:

```json
{
  "window.autoDetectColorScheme": true,
  "workbench.preferredDarkColorTheme": "Default Dark Modern",
  "workbench.preferredLightColorTheme": "Default Light Modern"
}
```

I have explicitly __not__ set the key `"workbench.colorTheme"` in my settings.json.
Now, whenever the system color scheme changes (either automatically or manually triggered), code now modifies the settings.json and explicitly sets `"workbench.colorTheme"` to the respective preferred configured theme.
In my eyes, code **shall not** persist this derived setting to the file but instead just implicitly use it. In my particular setup, this actually causes issues (see below).

Steps to Reproduce:

1. Configure code the following way:
  ```
  {
  "window.autoDetectColorScheme": true,
  "workbench.preferredDarkColorTheme": "Default Dark Modern",
  "workbench.preferredLightColorTheme": "Default Light Modern"
  }
  ```  
  `"workbench.colorTheme"` **must not** be set in settings.json.
2. Change the system color scheme from the current one to the other one (light to dark or other way around), e.g. in macOS system settings.
3. Observe that settings.json now contains the key `"workbench.colorTheme"`.

In my - admittedly special – setup this results in an annoying issue:
My settings.json is a read-only file as I generate it declaratively from my configuration system (Nix with home-manager). Thus, every time code attempts to write this superfluous key to settings.json, it fails to do so and complains with the following error:

```
Error while writing to User Settings. Unable to write file 'vscode-userdata:/Users/os/Library/Application Support/VSCodium/User/settings.json' (EntryWriteLocked (FileSystemError): Error: EACCES: permission denied, open '/Users/os/Library/Application Support/VSCodium/User/settings.json')
```

Explicitly writing that key is unnecessary, as its state can be derived unambiguously from the preferred color scheme settings.

In the output below, `settings.json` is my read-only generated config, and `settings_foo.json` is how code wants it to look after manually changing the system color scheme.

```
$ diff settings.json settings_foo.json
57c57,58
<   "workbench.preferredLightColorTheme": "Default Light Modern"
---
>   "workbench.preferredLightColorTheme": "Default Light Modern",
>   "workbench.colorTheme": "Default Light Modern"
```

**Comment by IllusionMH** [comment]
Duplicate of few old reports. This is expected current behavior, however there is open issue #91231 that tracks explicit use of variable, instead of overriding value.

**Comment by osnyx** [comment]
Ah, thank you, I did not catch that issue. Will close as a duplicate and link it over at the main issue.
