### ISSUE TITLE
Missing margin between label and detail in completion item

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#196132]
```
vscode.languages.registerCompletionItemProvider('typescript', {
		provideCompletionItems(document, position, token, context) {
			return [
				{
					label: { label: 'label', detail: 'detail' }
				}
			]
		},
	});
```

![Image](https://github.com/microsoft/vscode/assets/323878/4afea2ce-7c5f-4088-9ed4-83f9dcdb073d)

**Comment by jrieken** [comment]
https://github.com/microsoft/vscode/blob/d2b1eb8a36e1d0fb4f294025fe6ae19b69d41a98/src/vscode-dts/vscode.d.ts#L4738-L4742


This is actually as designed and documented. The intent purpose of these fields are function name and function signature like `foo(b,a,r)` with name being foo and detail being the rest. Therefore no spacing from the renderer

**Comment by roblourens** [comment]
Oops, thanks
