### ISSUE TITLE
Bad font rendering on linux

### ISSUE THREAD

**Issue by searene** [Microsoft/vscode#19615]
- VSCode Version: 1.8.1
- OS Version: ubuntu 16.10

The font rendering on VSCode is pretty bad on linux. To find out the reason, I downloaded a simple electron app from [electron-quick-start](https://github.com/electron/electron-quick-start) and found out that the font rendering on it was pretty good, this small electron app used the following components:

* Node.js 6.5.0
* Chromium 53.0.2785.143
* Electron 1.4.15.

Screenshots(font: ubuntu):

VSCode
![vscode](https://cloud.githubusercontent.com/assets/3351317/22457420/5d42f5fe-e7d2-11e6-9ad9-adf0a4be0c17.png)

electron
![electron](https://cloud.githubusercontent.com/assets/3351317/22457437/6a347fee-e7d2-11e6-9bc3-0bfd38e0e10a.png)

Maybe this is not so obvious, but in my computer the font rendering in electron is a lot better than VSCode. Everything on the editor seems to be blurry in VSCode.

**Comment by bpasero** [comment]
@searene does it make any difference if you change the editor font?

@alexandrudima fyi not sure if you know about more options to configure this.

One idea is also to run `"code --disable-gpu"` to see if that makes a difference.

**Comment by searene** [comment]
@bpasero No, almost each font is rendered badly. And I think it's so obvious that I noticed it right away as soon as I opened Visual Studio on ubuntu.

**Comment by searene** [comment]
@bpasero Sorry that I just saw your suggestion. I tried `code --disable-gpu` and found that this time font-rendering was a lot better! I think it's almost the same as `electron` now. Is it due to my GPU driver?

**Comment by bpasero** [comment]
Could be, I think the situation will improve once we update to a newer Electron version which we plan to do soonish.

**Comment by assunluis80** [comment]
The same with me using Ubuntu 17.04. This problem has been persisting ever since on Linux.

**Comment by assunluis80** [comment]
Please correct this issue.

**Comment by hristod** [comment]
I am also experiencing this problem. From what I can see, this is an electron related problem, not only in VS Code...
