### ISSUE TITLE
Duplicate workspace setting warnings

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode#19627]
- Open the workspace settings from the `.vscode` folder
- Open the workspace settings using `File>Preferences>Settings`
- The warnings show up twice

![image](https://cloud.githubusercontent.com/assets/172399/22463771/d38167b0-e7b3-11e6-9dbe-d322be72b57a.png)

**Comment by sandy081** [comment]
I can reproduce this only when SCM preview is enabled.

@egamma Can you disable the SCM Preview and let me know if you are able to reproduce this?

**Comment by egamma** [comment]
@sandy081 yes I have the SCM preview enabled and cannot reproduce it otherwise.

**Comment by sandy081** [comment]
@joaomoreno Any insight what new SCM preview has to be done with this?

**Comment by joaomoreno** [comment]
Long discussions with @sandy081 @jrieken and @aeschli resulted in:

We will filter out non `file:` or `untitled:` resource markers from the problems view unless they appear in a visible editor.

**Comment by sandy081** [comment]
Pushed a fix to distinguish between the resources (files, git, vscode...) schemes. Default file schemes are not shown.

![image](https://cloud.githubusercontent.com/assets/10746682/22595106/5abcfe5a-ea26-11e6-8721-e0cff4bd4d29.png)

**Comment by sandy081** [comment]
@joaomoreno Let me know if this is sufficient enough for this issue. If so I will close it.

**Comment by bpasero** [comment]
Verified that we show the full resource URI for problems from git resources.
