### ISSUE TITLE
Debugger fails when offline

### ISSUE THREAD

**Issue by dotnetCarpenter** [Microsoft/vscode#1962]
When I run the debugger offline I get : `request 'launch': cannot connect to runtime process (reason: getaddrinfo ENOENT undefined:7004)`. As soon as I'm online, it works.

IMHO vscode, should be able to function offline...

Version: 0.10.6
Shell: 0.34.5
Node: 4.1.1

**Comment by isidorn** [comment]
I believe this has been fixed and should be available with the January update.
@weinand right?

**Comment by weinand** [comment]
@isidorn correct.
