### ISSUE TITLE
Maximize group: focus is not in group when restored

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#196285]
Steps to Reproduce:

1.  have 2 groups side by side
2. focus group 1
3. maximise it
4. hit `Ctrl+2`
5. group 2 becomes visible

=> 🐛 focus is still in group 1

**Comment by benibenj** [comment]
Unable to reproduce with the mentioned steps

![Recording 2023-10-23 at 17 36 44](https://github.com/microsoft/vscode/assets/44439583/37f4bcc3-f205-473e-afdd-364fba9953bf)

**Comment by benibenj** [comment]
we also do not set focus when maximizing a group which is not active. Looking into it
