### ISSUE TITLE
Test: Hide Editor Title (Tab Bar)

### ISSUE THREAD

**Issue by benibenj** [microsoft/vscode#196292]
Refs: #33607

- [ ] anyOS @daviddossett
- [x] anyOS @sandy081

Complexity: 2

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23196292%0A%0A&assignees=benibenj)

---

We migrated the `workbench.editor.showTabs` setting from a boolean to an enum with the following options:
- `multiple`: Each open editor has an own tab (old: showTabs=true)
- `single`: One single large tab (old: showTabs=false)
- `none`: (New) Hides the entire editor title

Testing:
- Open multiple editors
- Change between the different `showTabs` settings
- Make sure the editor title bar (editor tab bar) updates/rendered correctly
- Switch to `showTabs: none`
- Check that the filename is displayed in the command center. The filename is only shown if the `window.title` is set to the default value 
(default value: ${dirty}${activeEditorShort}${separator}${rootName}${separator}${profileName}${separator}${appName})
- Open settings editor
- Make sure the progress bar is rendered on the correct height. This can be tested by opening the settings editor and entering a text in the search field. The progress bar should be rendered at the top of the editor.

**Comment by sandy081** [comment]
Good job 👏

**Comment by daviddossett** [comment]
Works great!
