### ISSUE TITLE
Tasks don't work with substs

### ISSUE THREAD

**Issue by diegotrsl** [Microsoft/vscode#19620]
- VSCode Version: Code 1.8.1 (ee428b0eead68bf0fb99ab5fdc4439be227b6281, 2016-12-19T14:49:23.350Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

|Extension|Author|Version|
|---|---|---|
|cordova-tools|vsmobile|1.2.6|
|omnipascal|Wosi|0.12.0|

---

Steps to Reproduce:

1. I have the following substs:

CMD:
C:\>subst
G:\: => C:\ERP\5.8.master\framework\svcl-fontes\svcl\resources\hudson\delphi
K:\: => Z:\svcl-fontes\pkg
M:\: => C:\ERP\5.8.master\framework\svcl-fontes\runtime
P:\: => C:\ERP\5.8.master\gestao-empresarial-fontes\erp-g5-rec\fontes
Q:\: => C:\ERP\5.8.master\gestao-empresarial-fontes\erp-g5-rec
Z:\: => C:\ERP\5.8.master\framework

2. When i open the P:\ in vscode, even when i have a tasks.json configured (i tried with the documentation example below), the task don't appear with ctrl + p and writting "task ".

tasks.json:
{
    "version": "0.1.0",
    "command": "echo",
    "isShellCommand": true,
    "args": [],
    "showOutput": "always",
    "echoCommand": true,
    "suppressTaskName": true,
    "tasks": [
        {
            "taskName": "hello",
            "args": ["Hello World"]
        },
        {
            "taskName": "bye",
            "args": ["Good Bye"]
        }
    ]
}

3. When i access the absolute folder (without the subst), the tasks works fine.

**Comment by bpasero** [comment]
@diegotrsl Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: http://code.visualstudio.com/Download#insiders

**Comment by diegotrsl** [comment]
After last update to 1.9.0, it is now working.
