### ISSUE TITLE
Add hover to chat symbols/pills

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#196291]
It would be great if we could get some detailed help when hovering the symbols in chat

![Image](https://github.com/microsoft/vscode/assets/2193314/6ea46f8d-8ba5-4c38-bb19-764b9f87b4c4)

**Comment by isidorn** [comment]
I get hovers now. 

![Image](https://github.com/user-attachments/assets/7f6edc52-5ffb-4bcf-9bb5-ed7cd33195dc)
