### ISSUE TITLE
Aux window: Alt+f4 closes the workspace instead of the aux window

### ISSUE THREAD

**Issue by r3m0t** [microsoft/vscode#196239]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 
- OS Version: Version: 1.84.0-insider (user setup)
Commit: cbd09078e6221fa1553c5a59dd25e63ad767911a
Date: 2023-10-23T05:34:05.496Z
Electron: 25.9.1
ElectronBuildId: 24472542
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.19045

Steps to Reproduce:

1. Open two workspaces
2. Open a couple of files
3. Move Active Editor into a New Window
4. Click on the new window and  Press Alt+F4
5. Expected: aux window closes. Actual: VS Code closes the workspace and both windows associated with it.

**Comment by bpasero** [comment]
Can you see if `Alt+F4` is assigned as keybinding? I assume this goes through our global window close handler that has not yet adopted aux windows.

**Comment by r3m0t** [comment]
I have default keybindings `{ "key": "alt+f4",                "command": "workbench.action.closeWindow" },
`
