### ISSUE TITLE
Test: Maximize Editor Group

### ISSUE THREAD

**Issue by benibenj** [microsoft/vscode#196289]
Refs: #16927

- [x] anyOS @anthonykim1
- [x] anyOS @alexr00

Complexity: 4

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23196289%0A%0A&assignees=benibenj)

---

We newly allow users to fully maximize an editor group when multiple editor groups are present. This will make the editor group fill the entire editor part and hide all other editor groups. When a editor group is maximized, an editor action icon is rendered in the toggled state on the tab bar. Pressing this action/button allows the user to return out of the maximized state.

The following ways can be used to maximize a group:
- Command Palette: `Maximize Group` (If at least two groups are available)
- Editor Title Menu: `Maximize Group` (If at least two groups are available)
- Double Click Tab: Requires `workbench.editor.doubleClickTabToToggleEditorGroupSizes: 'maximize'`

The following ways can be used to maximize a group:
- Command Palette: `Unmaximize Group`
- Editor Title Menu: `Unmaximize Group`
- Double Click Tab: Requires `workbench.editor.doubleClickTabToToggleEditorGroupSizes: 'maximize'`
- Toggled unmaximize editor action in the tool bar
- Changes to the editor grid will result in unmaximizing the editor group (adding/removing an editor group, opening a different editor group, closing the maximized editor group)
- Changing the layout of the editor group with commands in the command palette:
    - Grid Editor Layout (2x2)
    - Reset Editor Group Sizes
    - ...

When unmaximizing we restore the layout/sizes of the editor groups as they were before maximizing. 
The maximized view persists across window reloads, however, unmaximizing the maximized view after reloading the window might not restore the correct sizes.

**Testing:**
Try different combinations of methods to maximize/unmaximizing editor groups.
Use different amount of editor groups in different layouts
Make sure the view is still maximized after reloading the window

![Recording 2023-10-23 at 17 23 26](https://github.com/microsoft/vscode/assets/44439583/a3392758-4033-4a17-8310-dcb1f7c01282)

**Comment by alexr00** [comment]
👏

**Comment by anthonykim1** [comment]
I love this feature!
