### ISSUE TITLE
Source control cahnges tree folder names rendering

### ISSUE THREAD

**Issue by ivanvoznyakovsky** [microsoft/vscode#196252]
Type: <b>Bug</b>

`,` is used as delimiter instead of `/`

<img width="499" alt="image" src="https://github.com/microsoft/vscode/assets/6418145/86905ec5-c8a3-48b1-98d3-f684e459bb87">

VS Code version: Code - Insiders 1.84.0-insider (cbd09078e6221fa1553c5a59dd25e63ad767911a, 2023-10-23T05:35:37.619Z)
OS version: Darwin arm64 23.0.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|4, 3, 3|
|Memory (System)|16.00GB (0.07GB free)|
|Process Argv|--crash-reporter-id 0c371d61-9c5f-4476-b10a-e0c314c08dd3|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (20)</summary>

Extension|Author (truncated)|Version
---|---|---
project-manager|ale|12.7.0
vscode-eslint|dba|2.4.2
gitlens|eam|14.4.0
EditorConfig|Edi|0.16.4
vscode-todo-plus|fab|4.19.1
code-runner|for|0.12.1
vscode-pull-request-github|Git|0.74.0
gitlab-workflow|Git|3.81.0
vscode-peacock|joh|4.2.2
vscode-random|jre|1.11.0
rainbow-csv|mec|3.8.0
dotenv|mik|1.0.1
remote-containers|ms-|0.318.0
remote-ssh|ms-|0.107.2023100615
remote-explorer|ms-|0.5.2023101809
material-icon-theme|PKi|4.31.0
partial-diff|ryu|1.4.3
code-spell-checker|str|3.0.1
sort-lines|Tyr|1.11.0
markdown-all-in-one|yzh|3.5.1

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythontb:30258533
pythonptprofiler:30281269
vsdfh931cf:30280410
vshan820:30294714
vscod805cf:30301675
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30404738
py29gd2263:30784851
vsclangdf:30492506
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30618038
showlangstatbar:30737417
24365598:30687740
pythonfmttext:30716741
fixshowwlkth:30771523
showindicator:30805243
pythongtdpath:30726887
i26e3531:30792625
welcomedialog:30812478
pythonnosmt12:30779711
pythonidxpt:30768918
pythonnoceb:30776497
copilotsettingc:30808720
dsvsc013:30777762
dsvsc014:30777825
diffeditorv1:30786205
pythonmhint1:30859868
dsvsc015:30821418
pythontestfixt:30866404
pyreplss1:30865275
pythonmypyd1:30859725
pythoncet0:30859736
pythontbext0:30864172

```

</details>

**Comment by gjsjohnmurray** [comment]
I am seeing it in Explorer too, in today's Insider, with all extensions disabled:

![image](https://github.com/microsoft/vscode/assets/6726799/943f4227-f9d6-48df-be69-cef4a6b9e6a4)

**Comment by gjsjohnmurray** [comment]
I am bisecting now...

**Comment by gjsjohnmurray** [comment]
Hmm, nothing found. Maybe I am doing it wrong.
```
PS C:\s\vscode-bisect> npx --yes @vscode/vscode-bisect@latest
√ Commit of released insiders build that reproduces the issue (leave empty to pick the latest build) ... cbd09078e6221fa1553c5a59dd25e63ad767911a
√ Commit of released insiders build that does not reproduce the issue (leave empty to pick the oldest build) ...
[build] total 173 builds with roughly 7 steps
[build] starting desktop build 6ea0992693ac60c1dc4f09a4d889d631f600fd1f...
√ Is 6ea0992693ac60c1dc4f09a4d889d631f600fd1f good or bad? » Good
[build] starting desktop build a744a00d8350533788faa6c90fc162947de23fd0...
√ Is a744a00d8350533788faa6c90fc162947de23fd0 good or bad? » Good
[build] starting desktop build 187fa0eff0029b8de7a7300f8f20b1545c74c368...
√ Is 187fa0eff0029b8de7a7300f8f20b1545c74c368 good or bad? » Good
[build] starting desktop build baafa5d537d0424115f222a1e6101ac603d3de14...
√ Is baafa5d537d0424115f222a1e6101ac603d3de14 good or bad? » Good
[build] starting desktop build c42f8961f9ba803175ccbb8260e8d70d561f8bee...
√ Is c42f8961f9ba803175ccbb8260e8d70d561f8bee good or bad? » Good
[build] starting desktop build 8847e90041af3e27493c7739557162d543f76968...
√ Is 8847e90041af3e27493c7739557162d543f76968 good or bad? » Good
[build] All builds are good!
PS C:\s\vscode-bisect>
```
