### ISSUE TITLE
Workspace trust icon position incorrect when compact window density

### ISSUE THREAD

**Issue by PraneshBalasubramaniam** [microsoft/vscode#196209]
When opening `Workspace Trust` when `window.density.editorTabHeight` is `compact` the icon is `not positioned` correctly.

Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.83.1
- OS Version: Windows 10 Enterprise 22H2 19045.3570

Steps to Reproduce:

1. Enable VSCode settings ` "window.density.editorTabHeight": "compact"`.
2. Open Workspace Trust, the icon in title is not positioned correctly.

![Workspace Trust image](https://github.com/microsoft/vscode/assets/44346322/9847b2e8-6516-4c7b-8143-7ad0777d5736)

**Comment by gjsjohnmurray** [comment]
This is a consequence of  #152904. I will submit a PR.

**Comment by bpasero** [comment]
fyi @benibenj
