### ISSUE TITLE
Breakpoints showing in Debug/Breakpoint but not in file

### ISSUE THREAD

**Issue by BillDenton** [Microsoft/vscode#19623]
- VSCode Version: Code 1.8.1 (ee428b0eead68bf0fb99ab5fdc4439be227b6281, 2016-12-19T14:49:23.350Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions:

|Extension|Author|Version|
|---|---|---|
|read-only-indicator|alefragnani|0.6.0|
|alignment|annsk|0.3.0|
|Doxygen|bbenoist|1.0.0|
|vscode-astyle|chiehyu|0.6.1|
|python|donjayamanne|0.5.6|
|EditorConfig|EditorConfig|0.3.4|
|copy-relative-path|enochc|0.1.1|
|matlab|Gimly81|0.4.0|
|status-bar-tasks|GuardRex|0.1.2|
|vscode-dimmer|hoovercj|2.1.0|
|docthis|joelday|0.3.10|
|cpptools|ms-vscode|0.10.0|
|copy-file-name|nemesv|1.0.0|
|vscode-clearcase|OpenNingia|1.5.0|
|vscode-icons|robertohuertasm|7.1.2|
|theme-cyanicpastels|SamuelLampa|0.0.9|
|indenticator|SirTori|0.2.1|
|vscode-hexdump|slevesque|1.1.4|
|code-spell-checker|streetsidesoftware|0.14.8|
|comment-snippets|Tobiah|0.2.0|
|dark-plus-material|vangware|0.1.4|
|change-case|wmaurer|1.0.0|
|highlight-trailing-white-spaces|ybaumes|0.0.2|

---

I have three breakpoints in the Debug/Breakpoint window, but only one showing as a red dot in the margin of the file. They are all in the same file.

**Comment by BillDenton** [comment]
I just went back and deleted one of the "missing" breakpoints. After that one was deleted the other "missing" breakpoint appeared in the file margin.

**Comment by BillDenton** [comment]
Looking again it is a bit more complex. I have the same file open twice with one breakpoint showing in each of the views. After using "File: Copy Path of Active File" I got the full paths of the two files:
C:\directory1\<directory 2 all in lower case>\<a few subdirectories>\file.cpp
C:\directory1\<directory 2 all in mixed case>\<a few subdirectories>\file.cpp
I'm using Windows 7 Professional 64 bit, so the file names are usually case insensitive. It looks that I have got two views of the same file with different case in one part of the filename. So this appears to be a case sensitivity problem.

**Comment by BillDenton** [comment]
The file on disk matches the mixed case path.

**Comment by BillDenton** [comment]
During a debug session I closed all the open files. Then I clicked on a breakpoint in Debug/Breakpoint. This opened the file but with all lower case path. So the debugger is losing the filename case. This means you can set breakpoints in the original window (with correct case) and in the debugger with the wrong path. The debugger must keep the correct case and should re-use existing editor windows.

**Comment by isidorn** [comment]
Dup of https://github.com/Microsoft/vscode/issues/12922
