### ISSUE TITLE
Getting started animates out of view as soon as I open a folder or workspace

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#196269]
Steps:
* run `vscode-bisect` to open any insiders on a fresh user dir
* open a folder
* 🐛 the getting start thing animates out of view

Tried to capture it:

![Recording 2023-10-23 at 15 04 40](https://github.com/microsoft/vscode/assets/900690/99b15928-b336-4643-88ac-4d0375ce4d11)

**Comment by bhavyaus** [comment]
This should be fixed in more recent issues.
