### ISSUE TITLE
Poor markdown sematic highlighting for equations

### ISSUE THREAD

**Issue by Saltsmart** [microsoft/vscode#196202]
Type: <b>Bug</b>

Here is content in Chinese and English, mixed with equations in $$ delimiters:
```
由$B(x_0;r)$为开集，$\exist r'>0, s.t., B(x^*;r') \subset B(x_0;r)$，又由$B(x_0;r) \cap M = \varnothing$，$B(x^*;r') \cap M = \varnothing$，这与$B(x^*;r') \cap M \neq \varnothing$矛盾。

Semantic highlighting is an addition to syntax highlighting as described in the Syntax Highlight guide $a=1$. Visual Studio Code $l^p$ uses TextMate grammars as the main tokenization engine. TextMate grammars work on a single file as input and break it up based on lexical rules expressed in regular expressions $\exist r'>0, s.t., B(x^*;r') \subset B(x_0;r)$.
```
![image](https://github.com/microsoft/vscode/assets/40828952/284daefc-eea4-4d01-8f82-5d4486422653)

I make notes for the problems, and they are just some examples for poor highlighting:
![image](https://github.com/microsoft/vscode/assets/40828952/f0cc14c6-138d-46ca-b87b-bb9a790ea90f)

The extensions `markdown-all-in-one` and `latex-workshop` have been installed, but I'm sure the problems have nothing related to them, since after disabling these extensions, the problems still exist.

VS Code version: Code 1.83.1 (f1b07bd25dfad64b0167beb15359ae573aecd2cc, 2023-10-10T23:48:05.904Z)
OS version: Windows_NT x64 10.0.22000
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2208)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.85GB (9.02GB free)|
|Process Argv|--crash-reporter-id deaad0bf-2897-480e-b8cf-04d2a61dc2e3|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
latex-workshop|Jam|9.14.1
markdown-all-in-one|yzh|3.5.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
py29gd2263:30856252
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
2e4cg342:30602488
f6dab269:30613381
showlangstatbar:30737416
0bi6i642:30841073
a2ce3375:30757347
pythonfmttext:30731395
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
gsofa:30866041
pythonnosmt12:30797651
pythonidxpt:30866567
pythonnoceb:30805159
copilotsettingt:30859503
dsvsc013:30795093
dsvsc014:30804076
diffeditorv1:30821571
dsvsc015:30845448
pyreplss1:30865275
pythontbext0cf:30864173

```

</details>

**Comment by mjbvz** [comment]
This is caused by the `markdown-all-in-one` extension. Please file the issue against them
