### ISSUE TITLE
Packages

### ISSUE THREAD

**Issue by raushanapp** [microsoft/vscode#196254]
Type: <b>Bug</b>

while installing  a packages  at the last point getting stuck and never end installations 

VS Code version: Code 1.83.1 (f1b07bd25dfad64b0167beb15359ae573aecd2cc, 2023-10-10T23:48:05.904Z)
OS version: Windows_NT x64 10.0.22621
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|12th Gen Intel(R) Core(TM) i5-1235U (12 x 2496)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.71GB (7.85GB free)|
|Process Argv|. --crash-reporter-id cbd23f19-044f-4230-bf91-873c40a081d8|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (19)</summary>

Extension|Author (truncated)|Version
---|---|---
es7-react-js-snippets|dsz|4.4.3
vscode-html-css|ecm|1.13.1
react-native-react-redux|EQu|2.0.6
prettier-vscode|esb|10.1.0
auto-close-tag|for|0.5.14
auto-rename-tag|for|0.1.10
code-runner|for|0.12.1
prettify-json|moh|0.0.3
vscode-edge-devtools|ms-|2.1.3
vscode-typescript-next|ms-|5.3.20231022
color-highlight|nau|2.5.0
material-icon-theme|PKi|4.31.0
LiveServer|rit|5.7.9
vscode-styled-components|sty|1.7.8
errorlens|use|3.15.0
vscode-gradle|vsc|3.13.0
quokka-vscode|Wal|1.0.572
JavaScriptSnippets|xab|1.8.0
pretty-ts-errors|yoa|0.5.2

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
py29gd2263cf:30856253
vscaac:30438847
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
282f8724:30602487
f6dab269:30613381
2i9eh265:30646982
showlangstatbar:30737416
03d35959:30757346
pythonfmttext:30731395
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
gsofa:30866041
pythonnosmt12:30797651
pythonidxpt:30866567
pythonnoceb:30805159
copilotsettingt:30859503
synctok:30869157
dsvsc013:30795093
dsvsc014:30804076
pythonmhint1:30842940
dsvsc015:30845448
pythontestfixt:30866405
pyreplss1:30865275
pythontbext0cf:30864173

```

</details>

**Comment by aiday-mar** [comment]
Hi can you please provide the exact terminal command you were installing and the output you are seeing?

**Comment by raushanapp** [comment]
yarn install

**Comment by raushanapp** [comment]
![image](https://github.com/microsoft/vscode/assets/60419872/8d2ffb7b-6a32-400a-b2dd-1e7320243eac)

**Comment by aiday-mar** [comment]
Hi this issue is not related to vscode, it has to do with your project setup. I will close this.
