### ISSUE TITLE
ES2017 Object rest spread yields "Property assignment expected" validation error when used in JS embedded in HTML

### ISSUE THREAD

**Issue by ronjouch** [Microsoft/vscode#19629]
This issue is a followup to @zoltanzf in https://github.com/Microsoft/vscode/issues/3804#issuecomment-275052588 saying:

> As I see the `.vue` files are recognized as HTML by vscode, so the HTML syntax need to be extended with object rest/spread support.

---

Since [this fix that landed in version 1.8](https://github.com/Microsoft/vscode/issues/3804#issuecomment-265021769), Code is fine with using [Object rest spread](https://babeljs.io/docs/plugins/transform-object-rest-spread/) in .js files.

However, in JS-embedded-in-HTML (~~or in [`.vue` files](https://vuejs.org/) via all of the [extensions supporting it](https://marketplace.visualstudio.com/search?term=vue&target=VSCode&sortBy=Relevance) -- I tried `vue`, `Vue Components`, `Vetur` --~~ *EDIT Vetur seems to be fine, see below discussion*), a JS validation error `Property assignment expected` continues to be returned.

- VSCode Version:
    - Version 1.9.0-insider
    - Commit fcac9b686abe4292e69a774f61c8c4ce17768bf5
    - Date 2017-01-31T01:06:33.637Z
    - Shell 1.4.6
    - Renderer 53.0.2785.143
    - Node 6.5.0
- OS Version:

# Steps to Reproduce:

1. Create two new files
2. In the first file, paste this plain JS code and save as `.js`:  
`var obj = { a:1, b: 2 }; var obj2 = { ...obj };`
2. In the second file, paste the code below and save as `.html`:

```html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <script>
        var obj = { a: 1, b: 2 };
        var obj2 = { ...obj };
    </script>
</head>
<body>
</body>
</html>
```

# Expected:

None of the files should yield errors.

# Actual

In the second case (js within html), Code's JS validator yields error `Property assignment expected.` on the `var obj2 = { ...obj };` line

**Comment by octref** [comment]
Just saying, works fine for me with vetur 0.3.1 and VSCode 1.9

![image](https://cloud.githubusercontent.com/assets/4033249/22808933/ca6c2ac0-eefc-11e6-91d2-82f0e81c3702.png)

**Comment by ronjouch** [comment]
> Just saying, works fine for me with vetur 0.3.1 and VSCode 1.9

@octref indeed, I can no longer reproduce what I wrote in my original post about Vetur. I don't know whether that was a misconfiguration of mine, or if Vetur started doing something smarter since :-/

At any rate though, I confirm the html test case from my original post still fails as of VSCode 1.9.1:

![vscode191-stillfails-html](https://cloud.githubusercontent.com/assets/522085/22809179/762c47a4-eefe-11e6-97b5-17f493159fca.png)

**Comment by mjbvz** [comment]
Adding @aeschli too since this behavior seems specific to javascript in html. I'm guessing the configuration options passed to tssserver for JavaScript in html are out of sync with those we use for regular javascript files

**Comment by mudrz** [comment]
@mjbvz Very likely, { "javascript.validate.enable": false } does not work for html files:

expected behavior: native VS Code validation is disabled, ES Lint worries about validation
actually happening: native Visual Studio Code validation continues to throw errors about ES next features

**Comment by aeschli** [comment]
To disable script validation in HTML set the following setting:
`"html.validate.scripts": false`

**Comment by aeschli** [comment]
JavaScript inside HTML has hardcoded compiler options and is configured to use the latest target (ES6 at the moment)

**Comment by mudrz** [comment]
@aeschli nice, thanks, I am pretty sure I searched for such setting, but didn't find it. Now it's there and I can confirm that it works

**Comment by mjbvz** [comment]
@aeschli I took a look and I believe the html extension is still using TypeScript 2.0.10, which did not  spread. I'm going to update it's version of TypeScript to 2.1.6 and see if that fixes things

**Comment by mjbvz** [comment]
Yep, that seems to have been the root cause:
 
<img width="327" alt="screen shot 2017-02-10 at 2 39 57 pm" src="https://cloud.githubusercontent.com/assets/12821956/22846926/dd5eb6dc-ef9e-11e6-9956-167c1e146179.png">

**Comment by aeschli** [comment]
Thanks @mjbvz !
