### ISSUE TITLE
Adopt "php.validate.executablePath" handling to new TS behaviour

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#19624]
- VSCode Version: 1.9.
- OS Version: all

"php.validate.executablePath" should behave in the following way:

- the setting can be set in the user and workspace settings
- if present in the workspace setting warn the user once that the setting starts an executable and that the user trust the executable.
- if the workspace setting changes (points to a different executable) ask again.

**Comment by dbaeumer** [comment]
@egamma @chrmarti please verify.

**Comment by chrmarti** [comment]
The question should mention that the path is from the workspace setting and that it will be used for all PHP files, not just the current one: "Do you allow /Users/chrmarti/Development/repos/canary2.sh to be executed to lint this file?"

This message is still mentioning Path status bar item: "Cannot validate since /foo/bar is not a valid php executable. Click on the Path status bar item to configure the executable."

When there are both a user and a workspace settings' executable and I answer 'No' to the question regarding the workspace's executable, I would expect the user settings' executable to be used. Instead none is used.

Note that the UI for the tsdk is using a drop-down, not a message.

Reopening for the wording.

/cc @kieferrm @mjbvz

**Comment by chrmarti** [comment]
Also: After rejecting the workspace setting, I'm asked again after restart/reload. That's unexpected. (I'm not asked again after accepting.)

**Comment by dbaeumer** [comment]
Made the following changes:

- the initial message is now Do you allow C:\apps\php\php.exe to be executed to lint PHP files?. I changed this already on Tuesday, but didn't make it into Tuesday's build
- removed the mentioning of the Path status bar item. It now says: .... Use the setting 'php.validate.executablePath' to configure the PHP executable.

@egamma and I discussed quite some time about what to do if the user says No. We decided to ask him on next startup since the alternate actions aren't easy to explain either. Options were:

- remember in the local store that the user doesn't trust this. How would the use then trust the path if he click no by accident. We would either need UI on the local store again or we need to teach the user to edit the second two times.
- remove the setting from the workspace settings.
- disabled PHP validation by adding a setting to the workspace settings.

Both last once would requires another message dialog since we shouldn't change workspace settings without confirmation.

Given the fact that we want to slow down Erich and I decided to not do any code changes anymore. I did the wording changes.

**Comment by chrmarti** [comment]
I'm fine with that, two thoughts:
- The question should mention that this executable is set in the workspace settings.
- There is no way to change a Yes to a No either. Have you considered using the same UI as for the tsdk? (Or maybe that's the plan now?)

**Comment by dbaeumer** [comment]
The tsdk UI doesn't work since the php setting points to a file which is usually not local to your workspace. And we don't have a file picker UI in the extension host :-). That is why editing the setting is still something users have to do in the settings file.

The way from yes to no is easy. Simply remove the setting from the .vscode/settings.json file. I am very reluctant to introduce another setting story. IMO all settings should be maintained in the settings store and the used settings should be clear to the user when he opens the settings editor. If I store additional information in the local store the user would open the .vscode/settings.json file sees a correct entry but no indication that he disabled the entry a while ago. Will be confusing IMO. 

I will tweak the question to point to the workspace setting.

**Comment by dbaeumer** [comment]
The message now reads: 

`'Do you allow {0} (defined as a workspace setting) to be executed to lint PHP files?'`

**Comment by chrmarti** [comment]
- VSCode Version: Code - Insiders 1.10.0-insider (f02f9930255b5804166bd26c804de474ebb96799, 2017-02-24T07:04:53.237Z)
- OS Version: Darwin x64 15.6.0
- Extensions: None

The message shows up twice:
![19624](https://cloud.githubusercontent.com/assets/9205389/23315254/586f84b0-fa7a-11e6-956e-9c287ea70d53.gif)

**Comment by chrmarti** [comment]
Changing a Yes to a No when you want to avoid local changes against the checked out repository is not that easy. It is not enough to remove the setting and then add it back - that just keeps the Yes (also with a reload in between). You have to set it to a different path (a non-existant works) and accept that with a Yes (a No won't do) before reverting back to the original.

I agree that the settings should be apparent from the settings.json, that does not seem to hold in this case yet.

Also:
- Could add a 'Open Workspace Settings' button to the message so the user can inspect what else is in there.
- The webpage linked to with 'Learn More' does not list / explain the special cases where the user is asked for confirmation. Maybe drop that button?

Reopening so you can decide if any this should be changed.

**Comment by bpasero** [comment]
Moving to March for consideration.

**Comment by dbaeumer** [comment]
I removed the Learn More. TS doesn't provide this anymore either and the setting is something the user edits anyways.

**Comment by dbaeumer** [comment]
I added an action to the command palette that lets you 'untrust' the php validation path. 

![capture](https://cloud.githubusercontent.com/assets/1931590/24356731/782de01e-12fb-11e7-8ca2-f434fcba727d.png)

The action is only available if the validation path has been trusted before.

**Comment by dbaeumer** [comment]
Best person to re-verify would be @chrmarti

**Comment by chrmarti** [comment]
Would it make sense to align the command's name with the message:

![screen shot 2017-03-31 at 11 24 12 am](https://cloud.githubusercontent.com/assets/9205389/24563873/cfbdb8b6-1604-11e7-97b8-b33171b59e97.png)

E.g.: PHP: Disallow PHP validation executable (defined as a workspace setting)

Marking verified.

**Comment by dbaeumer** [comment]
Yes makes sense.

**Comment by dbaeumer** [comment]
Done.
