### ISSUE TITLE
`"accessibility.alert.save": "userGesture"` isn't respected

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#196389]
Testing #196126

1. Toggle screen reader mode on, set `"accessibility.alert.save": "userGesture"` and `"audioCues.save": "never"`
2. Enable autosave
3. Make some edits in a file and wait for them to get auto saved
4. The audio clue plays when the file is auto saved. It's actually not played at all when I ctrl+s.

**Comment by meganrogge** [comment]
Based on your settings, the audio cue should never be played.

**Comment by alexr00** [comment]
In that case, the language of `accessibility.alert.save` is confusing: "When in screen reader mode, alerts when a file is saved. Note that this will be ignored when [Audio Cues: Save](vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/code/electron-sandbox/workbench/workbench.html) is enabled."

I haven't set `audioCues.save`, so it is still `never`. Since ``accessibility.alert.save` is only impacted by "enabling" `audioCues.save`, I don't expect the value of ``accessibility.alert.save` to influece the behavior.

**Comment by meganrogge** [comment]
It's an either or experience. You will be alerted "Saved" or hear an audio cue (sound)

**Comment by meganrogge** [comment]
"Alert" is a common / known term to screen reader users to mean that a verbal aria alert will be issues. 

Feel free to open if you have other ideas for the language.
