### ISSUE TITLE
macOS: trackpad zoom gesture should not scroll the editor

### ISSUE THREAD

**Issue by natesilva** [Microsoft/vscode#19637]
- VSCode Version: Code 1.8.1 (ee428b0eead68bf0fb99ab5fdc4439be227b6281, 2016-12-19T14:42:49.304Z)
- OS Version: Darwin x64 16.4.0
- Extensions:

|Extension|Author|Version|
|---|---|---|
|EditorConfig|EditorConfig|0.3.4|
|laravel-blade|KTamas|0.0.1|
|vscode-simple-icons|LaurentTreguier|0.8.1|
|vscode-javascript-snippet-pack|akamud|0.1.5|
|vscode-eslint|dbaeumer|1.2.2|
|vscode-dash|deerawan|1.3.0|
|githistory|donjayamanne|0.1.5|
|python|donjayamanne|0.5.6|
|vscode-babel-coloring|dzannotti|0.0.4|
|tslint|eg2|0.8.1|
|php-debug|felixfbecker|1.10.0|
|php-intellisense|felixfbecker|0.0.12|
|code-runner|formulahendry|0.6.7|
|rest-client|humao|0.12.1|
|phpcs|ikappas|0.6.1|
|easy-less|mrcrowl|1.3.4|
|debugger-for-chrome|msjsdiag|2.5.0|
|vscode-sql-beautify|sensourceinc|0.0.4|

---

Steps to Reproduce:

1. On a Mac with a trackpad, open a file (a larger file shows the problem better).
2. Make the “zoom” gesture (pinch or unpinch)

Expected Results:

Either: (1) the text should get larger and smaller; or (2) nothing should happen.

Actual Results:

The file is scrolled to a different location.

More Details:

For some reason, this happens to me a lot in VS Code when I did not intend to invoke the zoom gesture. I believe most other apps either do not support it or ignore it unless you make a “big enough” zoom gesture. But in VS Code any zoom gesture translates to a disorienting scroll.

**Comment by natesilva** [comment]
For the record, I’d like to see this gesture ignored. Making the text bigger/smaller based on the zoom gesture is weird. Other Mac text editors—including BBEdit, TextMate, and Sublime—ignore it.

**Comment by bpasero** [comment]
We do ignore the zooming but maybe some scroll event is still being fired. I am not sure we can detect the pinch gesture though.

**Comment by rebornix** [comment]
This feature request will not be considered in the next [6-12 months roadmap](https://github.com/Microsoft/vscode/wiki/Roadmap) and as such will be closed to keep the number of issues we have to maintain actionable. Thanks for understanding and happy coding!
