### ISSUE TITLE
Code action lightbulb covering code & hard to see

### ISSUE THREAD

**Issue by claudiaregio** [microsoft/vscode#196312]
The lightbulb appears to be in the wrong spot (usually it's off to the left between the code and line numbers, yes?) and covering code and hard to see. It is also showing up on the wrong line number? See picture below : If my cursor is on line 5 it shows up on line 4

![image](https://github.com/microsoft/vscode-dotnettools/assets/19276747/45214855-d59c-441d-894a-89b8e10ce024)

VS Code: 1.83.1

**Comment by mjbvz** [comment]
It's a best effort. We try to position it in blank space but if that can't be found, then it will overlap with the code
