### ISSUE TITLE
Nothing shown about audio cues in Accessibility Help when not in screen reader mode

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#196386]
Testing #196126

It doesn't seem to matter what I set the new settings to. They are never mentioned in the editor accessbility help.

![Image](https://github.com/microsoft/vscode/assets/38270282/bd5fd6b2-848d-4340-a1dd-e122694abf85)

![Image](https://github.com/microsoft/vscode/assets/38270282/f56394fb-cfcf-4a9c-90cf-4aa49bbf9b6d)

**Comment by meganrogge** [comment]
By design, you have to enable screen reader mode to see this @alexr00

**Comment by meganrogge** [comment]
Maybe we shld also include it when not in screen reader mode?

**Comment by alexr00** [comment]
Might be worth updating the TPI then, since I assumed it should always be there.

The language seems backwards:

<img width="478" alt="image" src="https://github.com/microsoft/vscode/assets/38270282/f341b325-96a5-45d4-80ea-bd511d1099c2">

**Comment by alexr00** [comment]
It also doesn't mention the `accessibility.alert` settings, and my understanding is that if the `audioCues.*` settings are disabled, then the `accessibility.alert.*` settings will take effect. I have those still turned on.

**Comment by meganrogge** [comment]
The reason I didn't mention those here is they're linked to in the ones I do mention, so a user will discover them.

**Comment by meganrogge** [comment]
I will use this issue to track making sure these show up in the help dialog regardless of screen reader optimized mode
