### ISSUE TITLE
Test: Multi Editor/Model Highlighting

### ISSUE THREAD

**Issue by Yoyokrazy** [microsoft/vscode#196342]
Refs: #30014, #184259

- [x] anyOS @jrieken 
- [x] anyOS @gregvanl 

Complexity: 3

author: @Yoyokrazy 

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23196342%0A%0A&assignees=Yoyokrazy)

--- 
## Summary:
Support for textual highlighting across multiple files is now supported once enabling `editor.multiDocumentOccurrencesHighlight`. Currently there is not a provider built for multi-file semantic highlights, so the functionality is word-based.

## Steps to Test:

The priority in this step of testing is to ensure no regression in the standard WordHighlighter. Open up various file types with the setting disabled and make sure you have all of the same highlighting behaviors and functionality that stable has. This will be single-editor, and is just to ensure the added provider support hasn't affected the base functionality. Once complete, move onto multiple-editor testing below.

- Open multiple files within VS Code side by side such that multiple editors are in view. Click or highlight a word in your editor and ensure that highlighting is carried across to the other visible editors.
- Click from Editor A to Editor B, ensuring the highlighting reacts to your selection in the other editor and is updated across all visible editors.
- Experiment with closing the focused or non-focused editor, and ensure that the highlighting behaves as expected relative to your cursor position and focus.
- Explore all of the above while also using notebooks, this may surface some bugs with models being disposed relative to the viewport.

Please leave comments that are related to the behavior you would intuitively expect as well!
 
## Known Issues:
- If testing this within a notebook across cells, only the cells currently within the viewport will be highlighted. Currently looking at a fix to query the highlighter using an off-screen model.

--- 
Thanks so much for testing!

**Comment by gregvanl** [comment]
Tested on Windows 11
