### ISSUE TITLE
terminal.integrated.accessibleViewPreserveCursorPosition should it be ON by default?

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#196368]
Testing #196124

We try to preserve cursor position whenever we can in our editor. So should `terminal.integrated.accessibleViewPreserveCursorPosition` be on by default? In fact, do we really need to make this configurable?

**Comment by meganrogge** [comment]
By default, we want to align w the behavior of the terminal - which always has the cursor on the last line. 

In particular this makes sense because someone might have reviewed their output from a command, run a new one, and upon reopening, expect to inspect their last command's output. That is also JooYoung's opinion. 

@Tyriar do you agree?

**Comment by Tyriar** [comment]
@isidorn the thinking here is that users will typically be reviewing the last run command:

1. Run a command
2. Ctrl+up to review last output
3. Run a command
4. Ctrl+up to review last output

@meganrogge can we retain the last position and reset the position when data is written to the terminal? Is that the best of both worlds?

**Comment by meganrogge** [comment]
The author of the issue specifically did not want the cursor position to be reset when a new command has been run. I think we're doing the right thing here.

Yes, the thinking is exactly what you said above @Tyriar , which is why that's the default behavior.

**Comment by isidorn** [comment]
Thanks for chimming in and for providing details. 

> can we retain the last position and reset the position when data is written to the terminal? Is that the best of both worlds?

This sounds like a great approach to me.

**Comment by meganrogge** [comment]
@isidorn in the original linked issue, I asked the author if that would work for them and they said no.

**Comment by isidorn** [comment]
That's good to know. But in general, we should not make decisions based on a sample of 1.
So ideally we check how other users are using it. Or we can add some telemetry to gain a better understanding into this.

**Comment by meganrogge** [comment]
I agree and think that getting some telemetry is a good idea.
