### ISSUE TITLE
Python REPL fails to open

### ISSUE THREAD

**Issue by pfmoore** [Microsoft/vscode#19631]
- VSCode Version: 1.8.1
- OS Version: Windows 7 Enterprise SP1

Python 3.6 (64-bit) installed and in PATH.

I wanted to try out VS Code, as I'd heard good things about it, but I had never used it or seen any tutorials on it. I installed it, and tried a few extensions that seemed like they would be useful to me (Python, Powershell, and Vim, although I then uninstalled the Vim extension until I had got some familiarity with the default behaviour). No more than half an hour's playing. I was interested in the "integrated terminal" and configured it to use Powershell, based on some comments on the web (why isn't Powershell the default if it's installed?).

Then I wanted to see if I could get the Python REPL in the integrated terminal (without going via Powershell). So I tried Python: Start REPL from the command palette, but I got the error messages reported below.

I'm not sure what else to add, as I'm very new with VS code. Happy to do extra debugging if needed.

Steps to Reproduce:

1. New install of VS Code.
2. Install "Python" extension.
3. Ctrl-Shift-P, select "Python REPL". Error command 'python.startREPL' not found.
4. Open a .py file, and repeat. Different error: The terminal process command `python` failed to launch (exit code: 1)

**Comment by bpasero** [comment]
Reading your description it seems that the issue originates from an extension and not VS Code itself. Thereby I will close this issue and kindly ask you to report this issue against the extension repository. 

Most extensions are on GitHub as well so it should be easy to file it against the extension. If you open an extension on the market place, click on the **Support** link to find out more.

<img width="196" alt="screen shot 2016-05-05 at 12 51 17" src="https://cloud.githubusercontent.com/assets/900690/15041943/263e2282-12c0-11e6-9a33-d2b3b500d61b.png">

Thanks again for your feedback!
