### ISSUE TITLE
The custom font in html view blink

### ISSUE THREAD

**Issue by Philofallever** [microsoft/vscode#196346]
Does this issue occur when all extensions are disabled?: Yes/No

版本: 1.83.1 (user setup)
提交: f1b07bd25dfad64b0167beb15359ae573aecd2cc
日期: 2023-10-10T23:48:05.904Z
Electron: 25.8.4
ElectronBuildId: 24154031
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.19045
Steps to Reproduce:

1. install extension 中文诗歌
2. click refresh 

![create (2)](https://github.com/microsoft/vscode/assets/15180187/b507b9c3-ace5-4e89-afb1-d250d4e086c1)

**Comment by aeschli** [comment]
Please file the issue against the `中文诗歌` extension.
