### ISSUE TITLE
"Apply Extension to all Profiles" does not work when selected in the "LOCAL - INSTALLED" window in case the extensions are installed in the remote extension host

### ISSUE THREAD

**Issue by thernstig** [microsoft/vscode#196351]
For reference: https://code.visualstudio.com/docs/editor/profiles#_applying-an-extension-to-all-profiles

I have found some peculiar things with the implementation, which I am not sure is by design or not. But here comes one:

When working with remotes, such as remote ssh, I can see an extension in the "local" windows (greyed out) and in the remote window (not greyed out) in case it prefers to run on the remote extension host. But when I right-click on the local extension and select "Apply Extension to all Profiles" it does nothing. If I click it in the remote extension window and do the same, it gets the check mark. (But still not in the local window). As I suspect the intention behind "Apply Extension to all Profiles" is to actually apply it to all profiles, I should be able to right click and select it, so it gets selected, in all views under "Extensions".

(https://github.com/microsoft/vscode/issues/188612 was also something I found needed.)

**Comment by sandy081** [comment]
@thernstig Thanks for the feedback.

First request is a valid request.

Can you please give more details about the second request? I would suggest to extract it into a new issue and provide exact steps to reproduce the issue.

**Comment by thernstig** [comment]
@sandy081 I broke up the second item to a new issue: https://github.com/microsoft/vscode/issues/196718

**Comment by thernstig** [comment]
@sandy081 is this an easy fix? I think it will clear up some confusion. I am surprised more people have not noticed and upvoted this, as local team members found this by themselves. It is causing quite a bit of confusion UX wise.

**Comment by sandy081** [comment]
To verify:

- Open a remote window (WSL or Dev Container or SSH)
- Have an extension installed locally and remotely
- In Local Installed Extensions Section, Right click on the extension and apply it to all profiles. Verify that it also applies for the extension is remote installed extensions section. 
- Verify vice-versa
