### ISSUE TITLE
Selective Collapse option to exclude comments getting collapsed or modifying default collapse behavior feature.

### ISSUE THREAD

**Issue by siniradam** [microsoft/vscode#196388]
I'm mostly coding in JS or TS and using Collapse by levels while browsing quickly. ( CMD+K CMD+[n] )
When I collapse 1st level it also collapses comments (JSDoc, TS Definitions) which I would like to exclude.

If possible, it would be helpful to exclude option for default collapse behaviour.

**Comment by aeschli** [comment]
duplicate of https://github.com/microsoft/vscode/issues/48556
