### ISSUE TITLE
"Stop listening" does not make it to stop listening

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#196360]
![Screenshot 2023-10-24 at 11 46 19](https://github.com/microsoft/vscode/assets/1926584/2e644180-3fa8-4ee3-9f97-01c12bfb8414)

Should we always clear out the "Stop listening" part at the end?
Also can we somehow make this more discoverable to the user. How would the user know what to say to stop. Might you know what Alex and does voice assistants do?

**Comment by bpasero** [comment]
We do not support any voice commands currently. To clarify: you want to have a voice command to stop recording?

**Comment by isidorn** [comment]
I misunderstood our chat, I thought this is already supported.

But yeah I think this might be useful. Anyways, nothing for now. Let's see if other folk feel this way. If not, feel free to close.

**Comment by bpasero** [comment]
We auto-trigger when you just pause saying anything for 1 second so I doubt this would actually be something people would use. But for sure other voice commands that are maybe even configurable.
