### ISSUE TITLE
.NET Android/iOS application

### ISSUE THREAD

**Issue by lbulegato** [microsoft/vscode#196376]
Type: <b>Feature Request</b>

Microsft is retiring Visual studio for Mac.
The alternatives listed here

https://devblogs.microsoft.com/visualstudio/visual-studio-for-mac-retirement-announcement/

are suggesting to use VS code, so I am using it

So now I have Xamarin.Android/iOS app I need to convert to .NET android/iOS

I am following this guide here

https://learn.microsoft.com/en-us/dotnet/maui/migration/native-projects

This guide is only for Visual Studio and it seems that I cant create a .NET Android/IOS application in Visual Studio Code, is this a missing feature in Visual Studio Code? Is there a plan to make possible to use Visual Studiod code for .NET Android/iOS development? Not interested in MAUI development.

VS Code version: Code 1.83.1 (f1b07bd25dfad64b0167beb15359ae573aecd2cc, 2023-10-10T23:46:55.789Z)
OS version: Darwin x64 22.6.0
Modes:

**Comment by isidorn** [comment]
I think MAUI is the suggested solution here.
However I suggest to reach out over to our friends at C# here https://github.com/microsoft/vscode-dotnettools/issues

**Comment by lbulegato** [comment]
Thank you I will write to them, even if as I wrote MAUI cant be the solution, it is something completely different :)

**Comment by lbulegato** [comment]
Just in case this can be useful for anyone, here you can find a related ticket

https://github.com/microsoft/vscode-dotnettools/issues/575
