### ISSUE TITLE
Merge `editor.occurrencesHighlight` and `editor.multiDocumentOccurrencesHighlight` setting

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#196353]
Testing #196342

There is two settings which is confusing because what should happen when occurrencesHighlight is off but multiDocumentOccurrencesHighlight is on? A better solution would be to change `editor.occurrencesHighlight` to accept `true | false ` (as today) and a new value set of `"off" | "singleFile" | "acrossFiles"` (names to be defined)

**Comment by Yoyokrazy** [comment]
Currently, word based suggestion settings are defined as follows: 
<img width="561" alt="image" src="https://github.com/microsoft/vscode/assets/12552271/379b3edd-49a3-4998-9460-15006516edcc">

I can quite easily mirror this approach with:
<img width="466" alt="image" src="https://github.com/microsoft/vscode/assets/12552271/f8ce7349-81c2-4b44-a937-7ba84d91211a">

This behave the exact same as before, simply with a more logical setting name and description. In the current approach, with `editor.occurrencesHighlight = false` and `editor.multiDocumentOccurrencesHighlight = true` there will be no occurrence highlighting at all.

Effectively, the following two settings json would be equivalent:
- current:
```json
{
    "editor.occurrencesHighlight": false
    "editor.multiDocumentOccurrencesHighlight": true
}
```
- proposed:
```json
{
    "editor.occurrencesHighlight": false,
    "editor.occurrencesHighlightMode": "multiFile"
}
```

If that works, then it's an easy merge of #197690
