### ISSUE TITLE
Aux window: "Window 1" is a bad label?

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#196394]
Testing #196195

1. Open floating windows
2. Open Editors View

Notice "Window 1" label. This should either be "Window 2", or even better "Floating Window 1".

![Screenshot 2023-10-24 at 15 14 17](https://github.com/microsoft/vscode/assets/1926584/23be6d04-45f8-41ca-8a0c-95153390eb87)

**Comment by Tyriar** [comment]
I kind of prefer Window 1 personally but I can see the problems with it. `Floating Window 1` would be much too long, plus I'm not sure that's the name we want for the feature in product. On the width you have the scroll bar you'd only see something like: `FLOATING WINDO...`

**Comment by bpasero** [comment]
I think "floating window" is not correct: the window is like the main window and can also be behind the current window, so it is not always floating above.

I think renaming it to begin with "2" could work.

**Comment by MrYuto** [comment]
Also, The window number keeps incrementing forever:
![image](https://github.com/microsoft/vscode/assets/75252297/b33c1593-fe1b-46b2-b684-56a65f9e5cdf)

**Comment by bpasero** [comment]
I am pushing 2 changes:
* the label begins with `Window 2`
* all labels now dynamically update based on the number of opened windows (basically a fix for https://github.com/microsoft/vscode/issues/196394#issuecomment-1777639274)

![image](https://github.com/microsoft/vscode/assets/900690/b7a7a308-8d78-480e-97a2-ceeafe62639d)

I wonder if we should also have a prefix for the main-window groups in case you have multiple windows open?

**Comment by isidorn** [comment]
Thanks! I like no prefix for main window.
