### ISSUE TITLE
Emmet parser deletes invalid blocks

### ISSUE THREAD

**Issue by romligCH** [Microsoft/vscode#19633]
- VSCode Version: 1.8.1
- OS Version: Windows 10

Steps to Reproduce:

Setting emmet.triggerExpansionOnTab must be enabled (default)
1. Open a new html file
2. Type `[?]` followed by the tab key

or

1. Open a new php file
2. Type `<? '[?]'` and place the cursor before the last quote
3. Press the tab key

Expected:
- TAB character is inserted

Actual:
- Everything between the first \[ and the last \] including is removed
- Cursor is sent back to line beginning

Seems to work with everything starting with \[ and ending with \] on a single line and containing no seemingly valid attribute name.
Examples:
- `[^ab]`
- `[\x00]`
- `[~]`

Note: `[]` or `[ ]` or `[][]` produce a warning shown on the top of the window and do nothing. This may be related
> \[Warn\] Cannot read property 'length' of undefined

**Comment by ramya-rao-a** [comment]
I can see the warning "Cannot read property 'length' of undefined" in 1.8.1 but not in 1.9 insiders. So that should be fixed in the upcoming release.

As for the rest of the issue, this is emmet behavior, also happens with the emmet plugin for sublime.
Will move the issue to be fixed in emmet.

**Comment by ramya-rao-a** [comment]
This issue was moved to emmetio/emmet#484
