### ISSUE TITLE
Provide an option to show editor title actions in custom title bar when editor tabs are hidden

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#196384]
Testing #196292

Provide an option to show editor title actions in custom title bar

**Comment by benibenj** [comment]
Moving this to next milestone. Will also address making a single title bar menu (#195293)

**Comment by benibenj** [comment]
verification steps:

1. Set `workbench.editor.showTabs: none`
2. Editor Actions will appear in the title bar
3. Right click title bar to open context menu, editor actions visibility can be hidden
