### ISSUE TITLE
having problem in running the code. and it is lagging a lot

### ISSUE THREAD

**Issue by Sharad-Bhatt** [microsoft/vscode#196393]
Type: <b>Performance Issue</b>

there is a major issuse that is ruining the performance . if some one is not even able to run it then how are you telling that your vs code give better performance . 

it is showing this then starts to lagg and did not work for sometime . 
![image](https://github.com/microsoft/vscode/assets/138997833/aa53f6de-ab68-4ca6-a127-a849a6f0dd6b)

VS Code version: Code 1.83.1 (f1b07bd25dfad64b0167beb15359ae573aecd2cc, 2023-10-10T23:48:05.904Z)
OS version: Windows_NT x64 10.0.22621
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i3-1115G4 @ 3.00GHz (4 x 2995)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|11.75GB (4.64GB free)|
|Process Argv|--crash-reporter-id a76bef76-7be1-440b-9c78-6d5ea151d774|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    1	   137	 14864	code main
    0	   153	  2192	extensionHost [1]
    0	    91	  3960	     electron-nodejs ("C:\Users\Uday\AppData\Local\Programs\Microsoft VS Code\Code.exe" --ms-enable-electron-run-as-node "c:\Users\Uday\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\json-language-features\server\dist\node\jsonServerMain" --node-ipc --clientProcessId=2192)
    0	    69	 14764	     c:\Users\Uday\.vscode\extensions\ms-vscode.cpptools-1.17.5-win32-x64\bin\cpptools.exe
    0	     4	  7604	       "c:\Users\Uday\.vscode\extensions\ms-vscode.cpptools-1.17.5-win32-x64\bin\cpptools.exe"
    0	    37	 12224	         c:\Users\Uday\.vscode\extensions\ms-vscode.cpptools-1.17.5-win32-x64/bin/cpptools-srv.exe 14764 {06F4B8B0-F4FB-424F-95BB-E8F216F0E595}
    0	    10	 15184	           C:\WINDOWS\system32\conhost.exe 0x4
    0	    10	  9832	       C:\WINDOWS\system32\conhost.exe 0x4
    0	   203	  3112	window [1] (dev1st.cpp - Untitled (Workspace) - Visual Studio Code)
    0	    88	  5576	window [2] (Issue Reporter)
    0	    96	  6932	shared-process
    0	    85	  7236	     electron-nodejs ("C:\Users\Uday\AppData\Local\Programs\Microsoft VS Code\Code.exe" --ms-enable-electron-run-as-node "c:\Users\Uday\AppData\Local\Programs\Microsoft VS Code\resources\app\out\bootstrap-fork" ms-vscode.cppdbg "{\"common.vscodemachineid\":\"e4c55be5897bb068b82138f431bc71dba504ac2baa12f9cd90a6dfe9f3f41e3c\",\"common.vscodesessionid\":\"f7136b3c-b516-400e-ab40-2fbcd032302d1698152610552\"}" 0c6ae279ed8443289764825290e4f9e2-1a736e7c-1324-4338-be46-fc2a58ae4d14-7255)
    0	   172	  7404	   gpu-process
    0	    28	  8076	   crashpad-handler
    0	    76	 10624	fileWatcher [1]
    0	    39	 15192	   utility-network-service
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (dev1st.cpp - Untitled (Workspace) - Visual Studio Code)
|    Folder (Apna college c++): 11 files
|      File types: cpp(4) json(3) exe(3)
|      Conf files: launch.json(1) settings.json(1)
|      Launch Configs: cppdbg
|    Folder (Desktop): 26 files
|      File types: lnk(5) cpp(4) json(3) exe(3) ini(1)
|      Conf files: launch.json(1) settings.json(1);
```

</details>
<details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
c-cpp-runner|fra|9.2.1
python|ms-|2023.18.0
vscode-pylance|ms-|2023.10.40
cmake-tools|ms-|1.15.31
cpptools|ms-|1.17.5
cpptools-extension-pack|ms-|1.3.0
cmake|twx|0.0.17
vscode-lldb|vad|1.10.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscorecescf:30445987
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
py29gd2263:30856252
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
282f8724:30602487
89544117:30613380
a9j8j154:30646983
showlangstatbar:30737416
962ge761:30841074
03d35959:30757346
pythonfmttext:30731395
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
pythonnosmt12:30797651
pythonidxpt:30866567
pythonnoceb:30805159
copilotsettingt:30859503
synctok:30869157
dsvsc013:30795093
dsvsc014:30804076
dsvsc015:30845448
pythontestfixt:30866405
pyreplss1:30865275
pythoncet0:30866520
2e7ec940:30869480
pythontbext0:30864172

```

</details>

**Comment by roblourens** [comment]
This sounds like an issue with your program or configuration

**Comment by Sharad-Bhatt** [comment]
um i don't  think lagging in app is related to program configuration
