### ISSUE TITLE
No executable selection when Tool Bar Location is set to 'commandCenter'

### ISSUE THREAD

**Issue by D4koon** [microsoft/vscode#196399]
When using the following setting:
"debug.toolBarLocation": "commandCenter"

I can no longer choose the executable like with the other options like "docked"
I really like the new possibility to put it in the command-center but this is a major flaw for me.
![image](https://github.com/microsoft/vscode/assets/13141819/01f92f93-179e-4a9a-b2b5-b01a4e9d4596)

Here we can see the executable selection dropdown when "docked" which is missing when "commandCenter" is used
![image](https://github.com/microsoft/vscode/assets/13141819/0ca029a3-3577-4c4e-844c-e0672c61c03d)

Please add this dropdown also to the command-center-variant.
Thanks

**Comment by roblourens** [comment]
Discussed recenlyt in https://github.com/microsoft/vscode/issues/194881
