### ISSUE TITLE
Debug console "value" foreground color is hardcoded and not themable

### ISSUE THREAD

**Issue by rehmsen** [microsoft/vscode#196398]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.83.1 (and head)
- OS Version: Chrome 118.0.5993.88 on OS X 13.6 (but should reproduce in any browser regardless)

I am working on VSCode for Google.

Steps to Reproduce:

1. Use the debug console in the browser (not possible in vscode.dev I believe)
2. Independent of the theme, this color is always the same grey, which has relatively low contrast with white and dark backgrounds.

See https://github.com/microsoft/vscode/blob/f1b07bd25dfad64b0167beb15359ae573aecd2cc/src/vs/workbench/contrib/debug/browser/media/debugHover.css#L69

Many other colors are configurable, see https://github.com/microsoft/vscode/blob/f1b07bd25dfad64b0167beb15359ae573aecd2cc/src/vs/workbench/contrib/debug/browser/debugColors.ts#L260

**Comment by roblourens** [comment]
You're talking about the repl input here? 

![Image](https://github.com/microsoft/vscode/assets/323878/3c42ecc7-b50e-4db0-b65e-d4dabbb4c704)


I see different colors for different themes, but it's the default editor foreground.

**Comment by rehmsen** [comment]
No, I am talking about when you input something, the debugger will respond to the evaluate DAP request with something like
```
{"seq":0,"type":"response","request_seq":8,"success":true,"command":"evaluate","body":{"result":"(lldb) bt\nerror: Command requires a process which is currently stopped.\n","variablesReference":0}}
```

And this gets rendered with the CSS selector `.monaco-editor .debug-hover-widget > .monaco-scrollable-element > .value` - I guess because usually the response to an evaluate request is a value and not an error. This one happens to have a fixed greyish color, as seen in the link above. I think that should be taken from the theme as other colors in the REPL (like the input you show the screenshot of).

Does that make sense?

**Comment by rehmsen** [comment]
I did some more digging, and I was actually mistaken. This location is unrelated - it just happens to use the same color:

https://github.com/microsoft/vscode/blob/f1b07bd25dfad64b0167beb15359ae573aecd2cc/src/vs/workbench/contrib/debug/browser/media/debugHover.css#L69

In fact that value is not hardcoded - it comes from here: 

https://github.com/microsoft/vscode/blob/f1b07bd25dfad64b0167beb15359ae573aecd2cc/src/vs/workbench/contrib/debug/browser/debugColors.ts#L38

The default values are pretty low contrast - but at least we know how to overwrite it now. Sorry for the confusion.
