### ISSUE TITLE
Back up service should use end of line from Model as Marker instead of hardcoding

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode#19635]
Currently [Back up service](https://github.com/microsoft/vscode/blob/master/src/vs/workbench/services/backup/node/backupFileService.ts#L174) is hardcoding the end of line marker to `\n`. This could change the end of line of the file after retrieving. For eg 
- File A has three lines. Two lines ends with `\r\n` and one ends with `\n`
- When this file is opened, EOL is detected as `\r\n`
- Back up service adds File name and `\n` as markers in first line while storing back up
- When it is retrieved, EOL will be detected as `\n` since there are as many `\n`s as `\r\n`s.

IMO Back up service should take the EOL from the model instead of hard coding it

**Comment by Tyriar** [comment]
This is only for the metadata line though which is removed before the file content is put into an editor. Have you run into any bugs because of this?

**Comment by sandy081** [comment]
@Tyriar I did not run into bugs, but, I see there could be a possibility for a bug because of this. 

Looks like you are always using `\n` as the marker on the first line during back up. This will change the semantics of the file. Because if the file has 2 lines ending with `\r\n`s and 1 line ending with`\n`, then before backup the computed EOL for this file is `\r\n`. 

After backup the computed EOL for this file changes to `\n`. Because while retrieving from backup the file will have 2 lines ending with `\r\n`s and 2 lines ending with`\n` which gives preference to `\n`. 

Looks like the content from the backup is being joined with a single EOL. So the content before backup and after backup might not be same.

**Comment by Tyriar** [comment]
But the file content is the string returned from https://github.com/Microsoft/vscode/blob/d6e7de0cea0be3d78d70fa4dcbf8180c05bf1ae1/src/vs/workbench/services/backup/node/backupFileService.ts#L224 which excludes the first line including the `\n`. While I see what you're saying I don't think a bug will appear and it would be difficult to change at this point. Also the `META_MARKER` must be a single character, regardless of the EOL used in the rest of the file, using `\n` is convenient as it's easy to [pull out the first line given existing function](https://github.com/Microsoft/vscode/blob/d6e7de0cea0be3d78d70fa4dcbf8180c05bf1ae1/src/vs/workbench/services/backup/node/backupFileService.ts#L224).
