### ISSUE TITLE
Settings change does not preserve highlights on the recently interacted model

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#196356]
Testing #196342

* have settings editor, and two code editors that show some symbols (e.g src/vs/workbench/contrib/inlineChat/common/inlineChat.ts and src/vs/workbench/contrib/inlineChat/common/inlineChatServiceImpl.ts)
* enable x-model highlights
* select a symbols that get highlighted across editors
* disable x-model highlights
* 😕 highlights in both editors disappear, it would be cool if the most recent editor could keep the highlights
* the same is true when enabling the setting again

**Comment by Yoyokrazy** [comment]
wordHighlighter will trigger a `this._run()` for each open and visible editor. also triggers a `_stopAll()` for one of these workerRequests
