### ISSUE TITLE
Drag and Dropping Activity Bar Icons On Side Bar Not As Expected

### ISSUE THREAD

**Issue by benibenj** [microsoft/vscode#196359]
Testing #196272

When I dragged one of the icons to the second side bar, I wanted it to be placed before the other icon, however, it was placed behind it even though the bar indicating where it would be placed was in front of the icon.

Also I noticed it's not possible to drop an icon on the top part of the side bar when the side bar is empty. It's only possible to drop it on the view part of the side bar. I think it should be possible to drop it everywhere in the second side bar when it is empty.

![Recording 2023-10-24 at 11 40 10](https://github.com/microsoft/vscode/assets/44439583/0f0d39e0-ef01-460a-b67c-423e880bac9d)

**Comment by sandy081** [comment]
> When I dragged one of the icons to the second side bar, I wanted it to be placed before the other icon, however, it was placed behind it even though the bar indicating where it would be placed was in front of the icon.

I cannot reproduce this. I see it is happening in the recording, but it would be great if you can give me steps you followed to repro.

> Also I noticed it's not possible to drop an icon on the top part of the side bar when the side bar is empty. It's only possible to drop it on the view part of the side bar. I think it should be possible to drop it everywhere in the second side bar when it is empty.

Agreed. This is not new and has been like this before.

But, I observed another bug in your recording that dropping the view container is not activating it - this used to be getting activated in older versions. Fixed that.
