### ISSUE TITLE
Notebook cell output: I should always see the output as it is coming in

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#196377]
Testing #196327

Have the following cell:
```
import time
for i in range(20):
    time.sleep(.5)
    print(i)
```
Have a bit of screen real estate at the bottom. Run the cell.
I would expect that we scroll as the results are coming in. That is not happening, and there is no scrolling 🐛 
All my notebook settings are turned to default.

We already keep the Output view nicely in sync as the results are coming in. This should mimic that behaviour.

https://github.com/microsoft/vscode/assets/1926584/3d3e4499-57ab-4fa9-a245-66174ce61b7f

**Comment by amunger** [comment]
I don't think this is a good idea, people have generally been asking for less scrolling, and in the case where output streams lines quickly, it would be scrolling too fast to read and therefore not useful.

**Comment by isidorn** [comment]
That's fair. Thanks
