### ISSUE TITLE
When replacing a debug console with an editor, the dropshadow header is missing

### ISSUE THREAD

**Issue by bgashler1** [Microsoft/vscode#1963]
![image](https://cloud.githubusercontent.com/assets/11839736/12272059/2533f562-b913-11e5-8d47-16bb9af3a202.png)

**Comment by isidorn** [comment]
We only show the drop shadow for the focused editor. If you would move focus to one of the other two files you would get the dropshadow header. This way we distinguish better which editor has focus.

I believe this is as designed, please reopen if you disagree.
