### ISSUE TITLE
Update Git name from the view menu and assign function when you click.

### ISSUE THREAD

**Issue by Tekbr** [Microsoft/vscode#19638]
- VSCode Version: 1.9.0 - insider fcac9b6
- OS Version: Windows 10

-- Sorry for the English, I used Google Translator --

Update Git name from the view menu and assign function when you click.. When the SCM Preview option is disabled. See gif.

![errogit](https://cloud.githubusercontent.com/assets/19866231/22478560/931a36de-e7d1-11e6-9902-8651e1b1ad8c.gif)

**Comment by joaomoreno** [comment]
Reviewed by @bpasero

**Comment by Tekbr** [comment]
@joaomoreno The correction when clicking on the view menu works, but the name in the view menu still continues 'SCM', when it is disabled. Would not the correct one be written 'Git'?

Another thing, or SCM search when it is active in Command Palette is duplicate.

VSCode 1.9.0 - insider 27240e7 Date 2017-02-01T11:45:10.153Z

See the above descriptions in the Gif. Sorry if I'm wrong.

![errogit2](https://cloud.githubusercontent.com/assets/19866231/22512455/32944034-e880-11e6-8e3c-dcc6e112b79d.gif)

**Comment by joaomoreno** [comment]
You are right, great catch.

**Comment by Tekbr** [comment]
-- Sorry for the English, I used Google Translator --

@joaomoreno Another thing I noticed is that the amount of item in the command palette on 'Git' when the SCM is disabled is less than the amount of item when SCM is active. Is that a problem too?

Disable SCM> Item Git Command Palette = 15
SCM Enabled> Item Git Command Palette = 23

Another example is the 'Git: Show Git Output' is not displayed when SCM is disabled, but appears when we open the Output. And when SCM is enabled it is displayed in the Command Palette, but it does not appear when opening the Output.

See the above descriptions in the Gif. Sorry if I'm wrong.

![errogit3](https://cloud.githubusercontent.com/assets/19866231/22519162/7bcaa64c-e896-11e6-9cdb-c948b574c4b3.gif)

**Comment by joaomoreno** [comment]
That is expected. The SCM is in Preview mode and isn't fully implemented. You can track its progress in #18615

**Comment by Tekbr** [comment]
@joaomoreno When SCM is active the name Git still remains in the menu instead of SCM. The SCM Shortcut is also not appearing in the Menu. VSCode Version 1.12.1

![git](https://cloud.githubusercontent.com/assets/19866231/25822474/15fc821c-340f-11e7-8a7d-9ebe29650251.gif)


I know Git is about to be "removed" in the next version. In VSCode Insiders - 1.13.0 it does not even appear anymore. The problem of not being able to click on the menu when SCM is active has happened again. The Git name is still there and you can not click on it and the shortcut is not appearing either.

![git2](https://cloud.githubusercontent.com/assets/19866231/25822478/1b05fb58-340f-11e7-8c7f-1f3488b643b0.gif)

**Comment by joaomoreno** [comment]
Oh forgot to update this, thanks @Tekbr
