### ISSUE TITLE
Could you facilitate dragging an image to a readme file line (from the explorer to intended line) for the relative link to be added automatically please?

### ISSUE THREAD

**Issue by danuw** [Microsoft/vscode#19632]
- VSCode Version: Code 1.8.1 (ee428b0eead68bf0fb99ab5fdc4439be227b6281, 2016-12-19T14:49:23.350Z)
- OS Version: Windows_NT ia32 10.0.10586
- Extensions:

|Extension|Author|Version|
|---|---|---|
|package-to-readme|anthony-y|0.0.3|
|scad|efbenson|1.0.1|
|csharp|ms-vscode|1.6.2|
|PowerShell|ms-vscode|0.9.0|

---

Steps to Reproduce:

1.
2.

**Comment by mjbvz** [comment]
Seems like a special case of #10895. We currently do not have the APIs in place for extensions to support this sort of functionality in the editor
