### ISSUE TITLE
Auto close main window when last tab closed. Useful when used as git commit core.editor

### ISSUE THREAD

**Issue by therealmarv** [Microsoft/vscode#19634]
- VSCode Version: 1.8.1
- OS Version: macOS 10.12.3

Steps to Reproduce:

1. Set VSCode as standard git commit/merge editor with: `git config --global core.editor "code -n -w"`.
2. Commit in your git repo of choice with `git commit -a`
3. VSCode will open and you can enter your commit message.
4. When I save and close this new window (with one tab) with e.g. `cmd+w` the main VSCode window stays open. I have to again press `cmd+w` which is redundant given that I've open VSCode with commandine options to wait for return and a new window: `code -n -w`

Please remove double press `cmd+w` to close a VSCode window entirely. At least when it was opened with `code -n -w`.

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/7930
