### ISSUE TITLE
Aux window: support a menu bar

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#196392]
Testing #196195

macOS
1. Open floating window, have it focused
2. Try any action from the main menu. No effect 🐛 

For example the Help > Welcome, does not open the Welcome view. And About dialog is not shown.

**Comment by bpasero** [comment]
We should maybe disable the menu for floating windows until we have figured this out.

**Comment by bpasero** [comment]
Leaving this issue open to generally support a menu bar in floating windows.
