### ISSUE TITLE
`Cant` shouldn't be written as such

### ISSUE THREAD

**Issue by jsoref** [microsoft/vscode#196343]
I don't know which precise instance of this I hit, but it doesn't matter...
https://github.com/microsoft/vscode/blob/7dff07893ac160244db210e574eccc05f1cba2cb/src/vs/base/browser/ui/splitview/splitview.ts#L671

<img width="490" alt="image" src="https://github.com/microsoft/vscode/assets/2119212/a2655e94-c4d1-42fd-b933-3186ec1236e1">

**Comment by gjsjohnmurray** [comment]
Why not? After all, you seem comfortable writing "doesn't matter".

**Comment by jsoref** [comment]
It'd be ok if it was `Can't` (admittedly, there are some style guides that argue against using contractions, but that's distinct from omitting the apostrophe entirely which is not OK)

**Comment by mjbvz** [comment]
Please submit a PR for small spelling fixes like this
