### ISSUE TITLE
Editor toolbar actions jump causes miss click

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#196361]
Testing #196289

1. Focus in editor group A
2. Try to double click on a tab in editor group B
3. Editor toolbar actions cause the tab to jump and my second click lands on a toolbar action

![Image](https://github.com/microsoft/vscode/assets/38270282/dd908cc7-4bcb-49f9-8478-1cb0d9a75885)

**Comment by benibenj** [comment]
This is already a problem with the expand editor group on double click which we already support for a while. It's a tricky one to fix.  Moving this out.

**Comment by benibenj** [comment]
Closing this as #115136 is very similar and so if we come up with a solution for the wrapping issue we will tackle this case as well.
