### ISSUE TITLE
TF-IDF in Settings editor search - searching for "larger text in the editor" does not show results

### ISSUE THREAD

**Issue by lszomoru** [microsoft/vscode#196369]
Testing #196328

* Open Settings editor
* Enter `larger text in the editor` in the search field and press ENTER
  * No results are being shown
  ![Image](https://github.com/microsoft/vscode/assets/3372902/994ffee2-9975-476e-bafe-64b813b751a5)
* Delete the "r" from the end, add it back, press ENTER
  * The expected results are being shown

**Comment by bamurtaugh** [comment]
I see the same exact behavior.

**Comment by rzhao271** [comment]
Merging into epic https://github.com/microsoft/vscode/issues/235852
