### ISSUE TITLE
Open Editors: Focusing the main window does not move it to the top

### ISSUE THREAD

**Issue by MrYuto** [microsoft/vscode#196462]
![Code_-_OSS_Oi1Kw4UA2D](https://github.com/microsoft/vscode/assets/75252297/243fce43-8be9-4e84-ac58-1c2d81b1ead2)

Running 7172fd9d54469f93211d8edae17d5c75776715f7

**Comment by lramos15** [comment]
Is this floating window?

**Comment by MrYuto** [comment]
Closing as duplicate #196473
