### ISSUE TITLE
Aux window: unexpected address bar

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#196481]
Testing #196195 on Edge with insiders.vscode.dev

It would be great if there is anyway to hide the address bar, or show the correct address: insiders.vscode.dev

<img width="912" alt="image" src="https://github.com/microsoft/vscode/assets/876920/90a40b36-1fac-490a-a580-132a67120ff0">

**Comment by bpasero** [comment]
Great idea, but this does not seem possible due to security concerns. I am already instructing the `window.open` call to open as `popup`.
