### ISSUE TITLE
Error downloading vscode with test CLI for path with spaces

### ISSUE THREAD

**Issue by andreamah** [microsoft/vscode#196426]
Testing #196332

After modifying the `package.json` and running `npm run test`, it seems I run into the following error: 
<img width="721" alt="image" src="https://github.com/microsoft/vscode/assets/31675041/86fcd8ad-29bb-480d-a537-905593afc25d">

Not sure why this happens. Is this because I have spaces in my pathname?

**Comment by andreamah** [comment]
Yeah, I tried with a path without spaces and it seemed to work fine.

**Comment by andreamah** [comment]
Hmm, it actually doesn't seem to be the issue. I tried running a test targeting insiders right after and ran into the issue again:

<img width="678" alt="image" src="https://github.com/microsoft/vscode/assets/31675041/fa99e114-4a98-40b0-812c-9f4566206211">

**Comment by andreamah** [comment]
<img width="826" alt="image" src="https://github.com/microsoft/vscode/assets/31675041/56095d42-9d9e-4fb2-b80e-b9443fd74ab3">

Using the test runner, it seems that there's some `Invalid Package` error. Let me know if this is a separate bug - I'm just unsure whether this is related.

**Comment by connor4312** [comment]
Duplicates https://github.com/microsoft/vscode-test/issues/233
