### ISSUE TITLE
Migration for activityBar.visible not working

### ISSUE THREAD

**Issue by justschen** [microsoft/vscode#196457]
Testing #196272

![Recording 2023-10-24 at 10 21 24](https://github.com/microsoft/vscode/assets/54879025/610f3833-3858-4075-bd1f-7e53bfec9908)

Not sure if this has to do with default values, but since default is `left`, expected it to convert it to `workbench.activityBar.location : hidden`

**Comment by sandy081** [comment]
Old `workbench.activityBar.visible` setting is a boolean setting. So if you have `"workbench.activityBar.visible" = true` migration sets `workbench.activityBar.location` to `hidden` and removes `workbench.activityBar.visible` setting.
