### ISSUE TITLE
Move terminal into editor area break terminal

### ISSUE THREAD

**Issue by MrYuto** [microsoft/vscode#196458]
![Code_-_OSS_heKUgv5Md8](https://github.com/microsoft/vscode/assets/75252297/816f70fe-b17a-4603-ba78-ee30feb358fd)

Running 7172fd9d54469f93211d8edae17d5c75776715f7

**Comment by meganrogge** [comment]
cannot reproduce, hbu @tyriar?

**Comment by meganrogge** [comment]
what prompt program are you using?

**Comment by MrYuto** [comment]
@meganrogge I think this issue is not valid anymore because I can't reproduce it anymore. I use starship but it was reproducible with cmd too.
