### ISSUE TITLE
Aux window: clicking on problems panel doesn't focus window

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#196497]
Testing #196195

Might be similar to File Explorer but clicking on a problem entry doesn't focus the editor's containing window.

**Comment by bpasero** [comment]
I cannot reproduce: the window moves to top on single click and focuses on double click

![Recording 2023-10-25 at 13 50 18](https://github.com/microsoft/vscode/assets/900690/40a84cec-599b-4708-97df-5444ce272cc1)
