### ISSUE TITLE
Focus stuck in quickpick / not accepting commands

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#196431]
Testing #196195

I opened a window with a terminal, moved it between the two windows a few times, opened the quick pick in the new window, closed the window, changed a few settings, focused a terminal editor, tried to run this command, and the quick pick won't accept via click or enter. 

![Image](https://github.com/microsoft/vscode/assets/29464607/a70b7fb3-cb77-4acd-bbbb-a015963c2ffd)

https://github.com/microsoft/vscode/assets/29464607/c12721cb-6fd6-4a1f-a646-801ee8d2e274

**Comment by bpasero** [comment]
I think we should get to the bottom of this. I had a similar issue that I though my fix in https://github.com/microsoft/vscode/commit/8b6ae4ade6fc43ce21e0004fcaf7885fc6ed8b99 would help, it had the same symptoms.

**Comment by bpasero** [comment]
I think this is not happening anymore.
