### ISSUE TITLE
De-duplicate settings namespace in Settings UI for copilot

### ISSUE THREAD

**Issue by karthiknadig** [microsoft/vscode#196463]
Type: <b>Bug</b>

Copilot namespace in settings shows up twice.

Repro steps:
1. Install Copilot and copilot chat
2. Open settings UI

<img width="118" alt="image" src="https://github.com/microsoft/vscode/assets/3840081/7457b208-a247-4f49-a3a5-6608330b7a1a">

VS Code version: Code - Insiders 1.84.0-insider (7dff07893ac160244db210e574eccc05f1cba2cb, 2023-10-24T05:33:54.929Z)
OS version: Windows_NT x64 10.0.22621
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) W-2133 CPU @ 3.60GHz (12 x 3600)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.73GB (16.36GB free)|
|Process Argv|. --crash-reporter-id 2dc83bb9-7be1-4f42-aae4-df697150aa38|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (22)</summary>

Extension|Author (truncated)|Version
---|---|---
tsl-problem-matcher|amo|0.6.2
vscode-eslint|dba|2.4.2
prettier-vscode|esb|10.1.0
copilot|Git|1.129.0
copilot-chat|Git|0.9.2023102401
remotehub|Git|0.62.0
vscode-pull-request-github|Git|0.75.2023102409
vscode-docker|ms-|1.27.0
black-formatter|ms-|2023.5.12831009
isort|ms-|2023.11.12711013
python|ms-|2023.19.12971007
vscode-pylance|ms-|2023.10.40
remote-containers|ms-|0.319.0
remote-ssh|ms-|0.106.5
remote-ssh-edit|ms-|0.86.0
remote-ssh-explorer|ms-|0.48.0
remote-wsl|ms-|0.81.8
vscode-remote-extensionpack|ms-|0.24.0
azure-repos|ms-|0.38.0
remote-explorer|ms-|0.4.1
remote-repositories|ms-|0.40.0
remote-server|ms-|1.4.3

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythontb:30258533
pythonptprofiler:30281269
vsdfh931:30280409
vshan820:30294714
vscod805cf:30301675
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30404738
py29gd2263:30784851
vsclangdf:30492506
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30618038
showlangstatbar:30737417
ecj1e332:30687743
pythonfmttext:30716741
fixshowwlkth:30771523
showindicator:30805243
pythongtdpath:30726887
i26e3531:30792625
welcomedialog:30812478
pythonnosmt12:30779711
pythonidxpt:30768918
pythonnoceb:30776497
copilotsettingc:30808720
synctok:30869157
dsvsc013:30777762
dsvsc014:30777825
pythonmhint1:30859868
dsvsc015:30821418
pythontestfixt:30866404
pyreplss1:30865275
pythonmypyd1:30859725
pythoncet0:30859736
pythontbext0:30864172

```

</details>

**Comment by rzhao271** [comment]
Resolved in a duplicate issue.
