### ISSUE TITLE
Shortcut for settings editor doesn't bring main window to front

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode#196492]
Testing #196195

Tested on Linux:
- Open Settings editor in main window.
- Focus aux window.
- `Ctrl + ,` appears to set the cursor in the settings editor, but it does not focus the main window nor does it bring it to the front.

This works as expected when the Settings editor is open in the aux window and the main window has focus when the shortcut is pressed.

**Comment by bpasero** [comment]
@chrmarti for me a second settings editor opens? not for you?

**Comment by bpasero** [comment]
@chrmarti I am doing this, if you do something different, it would be helpful to have the steps indicating as such:

![Recording 2023-10-26 at 15 47 51](https://github.com/microsoft/vscode/assets/900690/e3135f53-5650-4ea9-a831-11701f4bdf4e)

**Comment by chrmarti** [comment]
In the latest build focus is transferred and the main window is brought to front. The bug is fixed for me. I have `"workbench.editor.revealIfOpen": true` which explains why I only get a single Settings editor. Closing.
