### ISSUE TITLE
sign in to github waits forever

### ISSUE THREAD

**Issue by amunger** [microsoft/vscode#196464]
I remember seeing this a while ago, but after testing signing in and out of github today I've hit it twice.

Open an extension that needs to sign into github without being signed in. 
Click the sign in button
A blank page opens in the browser (edge) and vscode just sits there waiting for the response.

![image](https://github.com/microsoft/vscode/assets/2019016/86beb024-0fd5-4fdf-80bf-b7352fbbe780)

**Comment by amunger** [comment]
forgot to grab that, I'll try to remember next time I see it

**Comment by TylerLeonhardt** [comment]
My guess is that GH had an outage that was holding up the flow from finishing. I'm gonna optimistically close this, but if you see it again lmk!
