### ISSUE TITLE
Gutter sparkle icon not shown initially if moving cursor position with mouse clicks 

### ISSUE THREAD

**Issue by gregvanl** [microsoft/vscode#196489]
Testing #196258

1. Open a new file and move cursor with keyboard until on an empty line and see gutter sparkle icon.
2. Close file with the cursor still on the empty line.
3. Reopen the file.

No gutter sparkle icon visible.

4. Click on various empty lines with the mouse.

Still no gutter sparkle icon displayed.

5. Use the keyboard to move the cursor. 

Now gutter sparkle icon is displayed and mouse clicking on empty lines continues to display the sparkle icon.

If you mouse click on a line with text such that there is a selection, the next mouse click on an empty line will show the sparkle icon.

**Comment by aiday-mar** [comment]
Hi thank you for filing the issue. I believe this issue should be resolved in today's insiders with https://github.com/microsoft/vscode/pull/196412. Let me know if you continue seeing this issue.
