### ISSUE TITLE
Extension data and template not included in issue if extension is inactive

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode#196459]
Testing #180757

1. Edit https://github.com/Yoyokrazy/clean-nb-imports-ext to have no activation events
2. Help > Report Issue 
3. :bug: no template is prefilled, no extension data is included

Should there be an activation event or a package.json static contribution that you can look for to ensure that you can activate the extension and call its providers?

**Comment by justschen** [comment]
closed with https://github.com/microsoft/vscode/pull/197616
