### ISSUE TITLE
Orca causes audio cues to stop playing

### ISSUE THREAD

**Issue by TylerLeonhardt** [microsoft/vscode#196488]
Testing #196126

* In VS Code, enable some Audio Cues
* outside of vscode, open a terminal and run `orca`
* go back to VS Code and trigger an Audio Cue
* 🐛 no audio cue, but the screenreader says stuff
* Now go to the terminal and quit Orca Ctrl+C
* go back to VS Code and trigger an Audio Cue
* 🐛 still no audio cue

Enabling Orca somehow kills audio cues until I restart the machine. Other sounds from the OS work fine.

Sadly, nothing in dev tools or the output channels say anything about the audio cues not playing.

**Comment by meganrogge** [comment]
seems unrelated to orca based on your steps?

**Comment by TylerLeonhardt** [comment]
Turning on Ocra is what stops audio cues from working until I restart the machine.
