### ISSUE TITLE
Aux window: windows moved to the top stay on top over focused window

### ISSUE THREAD

**Issue by rzhao271** [microsoft/vscode#196473]
Testing #196195

I opened the Open Editors view, and noticed Group 1, Window 1: Group 1, and Window 2: Group 1.
When I click on an editor belonging to a group in Window 1 or Window 2, the window moves itself to the top.
When I click on an editor belonging to the "non-Window" Group 1, the non-floating window doesn't move itself to the top, and I have to move the other windows out of the way.

**Comment by bpasero** [comment]
@rzhao271 I cannot follow along: the open editors view is only showing in the non-floating window, so how can you click that without bringing it to the top?

**Comment by rzhao271** [comment]
![Screen capture showing that the non-floating window stays at the bottom](https://github.com/microsoft/vscode/assets/7199958/90435d87-5bb4-4ca6-969e-7d1afe9c52bb)

**Comment by bpasero** [comment]
Funky, I can reproduce. So windows decides to allow for windows to be on top of other windows even when not focused 🤯

**Comment by bpasero** [comment]
I had a check to only call `moveTop` when the window was not focused but here the issue is that the window is focused but not on top. So have to remove that check.
