### ISSUE TITLE
Testing #180757: Deactivate button when all necessary fields have not been filled in yet

### ISSUE THREAD

**Issue by aiday-mar** [microsoft/vscode#196408]
Testing #180757

In relation to https://github.com/microsoft/vscode/issues/196324

I think this is more an improvement and perhaps others won't agree. When the starred fields are not filled in, we can submit the issue. Perhaps we could just deactivate the create button with CSS, when at least one of the starred fields is empty. 

![Screenshot 2023-10-24 at 16 12 52](https://github.com/microsoft/vscode/assets/61460952/4e2bffff-2408-44e5-9b6a-04eef010385f)

**Comment by justschen** [comment]
Personally i kind of like that as well. When things aren't filled in, there will be the error message, but maybe I can explore the UX a little and see how people like this.

**Comment by justschen** [comment]
may revisit this in the future, but atm, i think its important to have the warnings so users can see what is necessary
