### ISSUE TITLE
FR Bunyan debug console enhancement

### ISSUE THREAD

**Issue by boardofchris** [Microsoft/vscode#19643]
I have a node project that uses [bunyan logging](https://github.com/trentm/node-bunyan). Bunyan outputs log messages as JSON, which is how output appears in the debug console now. JSON log outputs are somewhat human legible but the output filtered by the [bunyan command line tool](https://github.com/trentm/node-bunyan#cli-usage) is much easier to quickly scan.

It would be a nice addition to the debug functionality of VSC to specify a processor that debug output is piped through before display. This would convert JSON to nicely formatted and colored output for easier debugging.

**Comment by dgreene1** [comment]
Subscribing for updates. I'd also like to see this.

**Comment by weinand** [comment]
This feature request will not be considered in the next [6-12 months roadmap](https://github.com/Microsoft/vscode/wiki/Roadmap) and as such will be closed to keep the number of issues we have to maintain actionable.
Thanks for understanding and happy coding!
