### ISSUE TITLE
Terminal does not re-focus after Accessibility Help

### ISSUE THREAD

**Issue by andreamah** [microsoft/vscode#196436]
Testing #196124

1. Open a terminal.
2. alt-f1 -> gets terminal accessibility help
3. alt-f1 again -> gets another accessibility help menu.
4. escape -> closes terminal
5. Focus isn't on terminal. :bug: I thought that this might be confusing if a user wants to run alt-f2 right after this.

**Comment by meganrogge** [comment]
Yeah this flow is unlikely to occur. We should disable `alt+f1` when in a help dialog
