### ISSUE TITLE
Is the whitespace expected here?

### ISSUE THREAD

**Issue by TylerLeonhardt** [microsoft/vscode#196465]
Testing #196327

My notebook:

cell 1:
```
import time
time.sleep(3)
for i in range(29):
    print(i)
```

cell 2:
```
import time
for i in range(20):
    time.sleep(.5)
    print(i)
```

Steps:
* Shift+Enter cell 1
* scroll up
* Click into cell 1
* Shift+Enter cell 1
* scroll up fast **NOTICE CELL 1'S OUTPUT HAS NO LINES IN OUTPUT BEFORE IT RUNS**
* Now click into cell 2
* Shift+Enter cell 2
* scoll up fast to cell 1
* click into cell 1
* Shift+Enter cell 1 while cell 2 is running
* scroll up fast **NOTICE CELL 1'S OUTPUT HAS A BUNCH OF WHITESPACE IN OUTPUT BEFORE IT RUNS**

https://github.com/microsoft/vscode/assets/2644648/4cc01bfb-ae58-4016-90ab-568cd6983753

Is this expected? It doesn't look bad ... but the difference in behavior is interesting.

**Comment by amunger** [comment]
I think it's expected if I follow what's going on here. The whitespace is just holding the position for the output to re-appear and reduces the amount of jumpiness while re-executing cells.

prevents weird behavior like https://github.com/microsoft/vscode/issues/193231
