### ISSUE TITLE
Cannot paste into form inside iframe inside webview

### ISSUE THREAD

**Issue by isc-bsaviano** [microsoft/vscode#196415]
Steps to Reproduce:

1. Copy some text into your clipboard.
2. Download, unzip and install this test extension:
[webview-copy-test-0.0.1.vsix.zip](https://github.com/microsoft/vscode/files/13119655/webview-copy-test-0.0.1.vsix.zip)
3. When the extension installs, a webview will be shown with a `<textarea>` inside an `<iframe>`. Try to paste some text into it using `Ctrl/Cmd-V`. Observe that the text doesn't get pasted.

The webview's HTML is very simple:

```html
<!DOCTYPE html>
<html lang="en">
<head>
	<style type="text/css">
	body, html {
		margin: 0; padding: 0; height: 100%; overflow: hidden;
		background-color: white;
	}
	#content {
		position:absolute; left: 0; right: 0; bottom: 0; top: 0px;
	}
	</style>
</head>
<body>
	<div id="content">
		<iframe srcdoc="<body>Test page with form input<form><textarea cols=90 rows=8></textarea></form></body>" width="100%" height="100%" frameborder="0"></iframe>
	</div>
</body>
</html>
```

Our extension uses a cross-origin `<iframe>` (with a `src` attribute instead of `srcdoc`), and we can't avoid its use. 

*Orignially reported as https://github.com/intersystems-community/vscode-objectscript/issues/687*

**Comment by gjsjohnmurray** [comment]
Maybe related to #129178

**Comment by gjsjohnmurray** [comment]
Also #182011
