### ISSUE TITLE
files are not excluded

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#196477]
Testing #196194

I set:

```
	const fileWatcherOptions: vscode.FileSystemWatcherOptions = {		
		excludes: ['**/test/**'],		
	};
```

Created a folder, `test`, and this was logged:

```
/Users/meganrogge/VSCodeLaunchBug/test created. (at console.<anonymous> (/Users/meganrogge/Repos/vscode/vscode/out/vs/workbench/api/common/file:/Users/meganrogge/Repos/vscode/vscode/src/vs/workbench/api/common/extHostConsoleForwarder.ts:49:10))
```

**Comment by bpasero** [comment]
@meganrogge can you please share the full sample, including the call to create the file system watcher?

**Comment by bpasero** [comment]
https://github.com/microsoft/vscode/issues/196455 maybe related with a fix coming in only today.

**Comment by meganrogge** [comment]
Yeah @bpasero mine was very similar setup to that one, so believe this can be closed as a duplicate

**Comment by meganrogge** [comment]
It works for me in today's insider's
