### ISSUE TITLE
vscode-test showing errors in terminal

### ISSUE THREAD

**Issue by andreamah** [microsoft/vscode#196467]
Testing #196332

<img width="698" alt="image" src="https://github.com/microsoft/vscode/assets/31675041/c446d59f-f43d-446f-a199-e8b2236cef9a">
Running this on linux, I see this working, but I noticed that there are some terminal errors. Not sure if this is expected.

**Comment by connor4312** [comment]
We pass through the logs that VS Code writes to standard out, so these are expected (if unfortunately noisy)
