### ISSUE TITLE
invisibles tmTheme global setting does not work

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#19647]
/cc @sandy081 @aeschli 

The default `.vs-whitespace` style overrides any custom ones defined in the theme.

![image](https://cloud.githubusercontent.com/assets/2193314/22487831/d859b124-e7c3-11e6-9c25-d93c12985d6b.png)

See `EditorWhiteSpaceStyleRules.getCssRules`

**Comment by aeschli** [comment]
We used to have !important on the rule. The fix to bring it back is good.

**Comment by Tyriar** [comment]
:+1: pushed to `release/1.9`

**Comment by joaomoreno** [comment]
@aeschli Can you code review and verify this?

**Comment by aeschli** [comment]
Verified in 3e400cc8ceefbb4440fe00f1d58002feea20c333
