### ISSUE TITLE
Aux window: main menu not functional

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode#196402]
Testing #196195

The global menu is shown for the aux window, but its entries don't do anything. No console errors.

**Comment by bpasero** [comment]
Yeah good catch, I think when native title is enabled we should disable the menu for the aux windows.

**Comment by bpasero** [comment]
**Verifier: please ensure:**
* on Linux: child windows have no menu
* on Windows: enable native title bar style to get native menu and verify the same
