### ISSUE TITLE
NVDA reads 'blank' when navigating Accessibility Help

### ISSUE THREAD

**Issue by andreamah** [microsoft/vscode#196430]
Testing #196124

1. Open terminal.
2. Run alt-f1 to open accessibility help
3. Use up/down arrows to navigate help description.
4. Screen reader says "blank" every time I go to a new line despite the line not being blank :bug:

**Comment by andreamah** [comment]
Hmm, I noticed that My `editor.accessibilitySupport` was set to `off`, so I set it to `auto` and reloaded and now it works. Not sure if that helps to try to repro the problem.

**Comment by meganrogge** [comment]
Yeah, it won't work when that is set to `off`, so that's expected. Did you have it explicitly disabled in your settings file?

**Comment by andreamah** [comment]
Yeah, I did from testing. I just found it strange that the accessibility help menu still popped up, but the screen reader didn't work with it.

**Comment by meganrogge** [comment]
Would you expect the help menu to not pop up?

**Comment by andreamah** [comment]
Hmm, I think I was more thrown off that other parts of the editor worked okay with the screen reader, but this menu just read 'blank'  over and over. Maybe I'd expect it to read how to enable accessibility support at least?
If someone accidentally had `editor.accessibilitySupport` disabled, I feel that it might be confusing to know what's happening.

**Comment by meganrogge** [comment]
I had thought that we already set the aria label / alert when a user opens the accessibility help dialog with screen reader mode off. If not, I think that would be good to do.

**Comment by meganrogge** [comment]
when the accessibility help dialog is focused and screen reader mode is disabled, we indicate in the aria label how to enable screen reader mode, so this case is covered.

![Image](https://github.com/microsoft/vscode/assets/29464607/602d4093-27ec-4220-8f14-4b99e5160e0a)
