### ISSUE TITLE
Additional extension info field looks editable but isn't

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode#196445]
Testing #180757

The styling here makes it look like an editable text field (focused border, the fact that it's resizable), should it maybe look more like the system info and AB experiment fields?

![Image](https://github.com/microsoft/vscode/assets/30305945/86ad3c8a-abe9-4a60-9bb8-b2c24eee3561)

**Comment by justschen** [comment]
updated to match a/b info

![Screenshot 2023-10-26 at 11 09 38 AM](https://github.com/microsoft/vscode/assets/54879025/6dff15f7-87cd-4da7-8e6f-d0f21a844a1a)
