### ISSUE TITLE
css for terminal color quickpick not applied in new window

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#196451]
Testing #196195

1. Move a terminal to a new window
2. Run terminal: change color
3. 🐛 no colors in the quickpick

![Image](https://github.com/microsoft/vscode/assets/29464607/4cabba81-374b-4331-8f3b-cc29dfcf5679)

**Comment by bpasero** [comment]
@Tyriar I see that there is a `style` element in `body`:

![image](https://github.com/microsoft/vscode/assets/900690/8f151b7c-9799-4b4f-b956-39fb3e868bfb)

That is not a good place, why not `head`? We only track global styles in `head`.

**Comment by bpasero** [comment]
via https://github.com/microsoft/vscode/commit/47a0ab66a0310544896158f3f519bea13a31bdd7
