### ISSUE TITLE
Should the 'additional extension info' field clear when it's unchecked?

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode#196442]
Testing #180757

Toggling this checkbox doesn't appear to do anything

![Image](https://github.com/microsoft/vscode/assets/30305945/db693c1f-45f7-47c5-b17f-a8e7800d3c37)

**Comment by justschen** [comment]
Nope! similar to the two checks below, checking it will send data, unchecking it will not send the data. The main thing here is just showing/hiding the information.
