### ISSUE TITLE
Sometimes `firstLine` jumps to the whole cell

### ISSUE THREAD

**Issue by TylerLeonhardt** [microsoft/vscode#196469]
Testing #196327

Seems somewhat random... but `firstLine` doesn't seem to work between cell 1 and 2... but it works between cell 2 and 3.

https://github.com/microsoft/vscode/assets/2644648/b4ec1627-868b-4641-a840-9ab525d93a7e

Cell 1:

```
# 1
import time
time.sleep(3)
for i in range(29):
    print(i)
```
Cell 2:
```
# 2
import time
for i in range(20):
    time.sleep(.5)
    print(i)
```
Cell 3:
```
# 3
for i in range(20):
    print(i)
```

**Comment by bhavyaus** [comment]
I see the same behavior after resizing my window to a smaller size. In full screen mode, it works as expected
