### ISSUE TITLE
drag and drop to invalid location

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#196437]
Testing #196195

I think this should be a no-op 🤔 

https://github.com/microsoft/vscode/assets/29464607/75a3721f-5537-4635-a88e-fdeaf44e7b80

**Comment by meganrogge** [comment]
here's what happens when I try this with an editor

![Image](https://github.com/microsoft/vscode/assets/29464607/df2d45a8-b105-4ee9-86c2-ee9358ce5282)

**Comment by bpasero** [comment]
I can only speak to editors: we have a data transfer to allow for dragging an editor into another application to have its path pasted (works for example in ST). I assume the browser simply does not allow to open a local file on drop, but I would not remove this feature.

For terminals, leaving up to Daniel.
