### ISSUE TITLE
nbformat = 4.5 support is not working

### ISSUE THREAD

**Issue by stephenkraemer** [microsoft/vscode#196416]
Type: <b>Bug</b>

I have noticed two problems with my vscode-insiders installation which I assume may form one issue.

1. When a notebook in nbformat 4.5 is opened, new cells do not receive cell ids, even though this is required by the format spec and is a documented feature of vscode: #134834
2. When a new notebook is created, the format is always 4.2. I am not sure whether this is expected.

Steps to reproduce:
1. Generate a notebook with jupyterlab or any other way (jupytext etc.), and verify that it has nbformat = 4.5
2. Open the notebook in vscode, and generate a new cell, then save.
3. Inspect the JSON of the saved notebook - the new cell does not have a cell id.

Some additional points which may be of interest
- The issue persists when all extensions except jupyter/python are disabled.
- I have recent versions of nbformat etc. installed, but I would assume this is bundled with vscode anyway.
- The issue also exists on the current pre-release version of the jupyter extension.
- I haven't found any configuration option which would enable or disable support of notebook formats > 4.2 Maybe I have missed a configuration option which I should have set?

VS Code version: Code - Insiders 1.84.0-insider (cbd09078e6221fa1553c5a59dd25e63ad767911a, 2023-10-23T05:33:33.712Z)
OS version: Linux x64 6.2.0-35-generic
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz (8 x 3750)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|0, 1, 1|
|Memory (System)|15.34GB (6.03GB free)|
|Process Argv|--crash-reporter-id 7cb2c708-35ce-40c2-a5ee-5aa59d88c1f6|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|i3|
|XDG_CURRENT_DESKTOP|i3|
|XDG_SESSION_DESKTOP|i3|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (18)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-neovim|asv|0.9.1
vscode-eslint|dba|2.4.2
githistory|don|0.6.20
fuzzy-search|jac|0.0.3
black-formatter|ms-|2023.5.12831009
python|ms-|2023.19.12971007
vscode-pylance|ms-|2023.7.40
jupyter|ms-|2023.10.1002981100
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.17
vscode-jupyter-cell-tags|ms-|0.1.8
remote-ssh|ms-|0.107.2023100615
remote-ssh-edit|ms-|0.86.0
remote-explorer|ms-|0.5.2023101809
remote-server|ms-|1.5.2023102409
even-better-toml|tam|0.19.2
my-vscode-utils|und|0.0.2
pyexec|und|0.0.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythontb:30258533
pythonptprofiler:30281269
vshan820:30294714
vscod805cf:30301675
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30404738
py29gd2263:30784851
vsclangdf:30492506
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30618038
showlangstatbar:30737417
24365598:30687740
pythonfmttext:30716741
fixshowwlkth:30771523
showindicator:30805243
pythongtdpath:30726887
i26e3531:30792625
welcomedialog:30812478
pythonnosmt12:30779711
pythonidxpt:30768918
pythonnoceb:30776497
copilotsettingt:30808721
asynctok:30869155
dsvsc013:30777762
dsvsc014:30777825
pythonmpsinfo:30859869
dsvsc015:30821418
pythontestfixt:30866404
pyreplss1:30865275
pythonmypyd1:30859725
pythoncet0:30859736
pythontbext0:30864172

```

</details>

**Comment by DonJayamanne** [comment]
Thank you for filing this issue and sorry you are running into this.
I can replicate this at my end as well.
Will look into this.
