### ISSUE TITLE
can't open new editor if current directory at startup was deleted

### ISSUE THREAD

**Issue by skybrian** [Microsoft/vscode#19649]
- VSCode Version: 1.8.1
- OS Version: MacOS 10.12.2

Steps to Reproduce:

```
# shut down VS Code
mkdir foo
cd foo
code .
# close editor window
cd ..
rmdir foo
code .
# editor window is blank
```

The second time it starts, there is a blank (all black) window. Using 'Toggle Developer Tools' there is an error on the console:

Uncaught Error: ENOENT: no such file or directory, uv_cwd path.js:1144

The code looks like this:

```
if (cwd === undefined)
          cwd = process.cwd();
```

Apparently, this dies if the process's current directory at startup no longer exists.

To recover, quit out of VS Code (instead of just closing the editor window).

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/2259
