### ISSUE TITLE
execution or evaluation

### ISSUE THREAD

**Issue by satyamraja810** [microsoft/vscode#196410]
Type: <b>Feature Request</b>

the expression of any functions are evaluated from right to left which should be left to right. please fix it as it is causing much trouble i have to write separate lines to avoid this.
#include <stdio.h>
int main()
{
    int k=15;
    printf("\n%d %d",k!=15,k=20);
    return 0;
}         
for example output should be 0 20
but due to operating from right to left output is showing 1 20
please fix this ASAP.

VS Code version: Code 1.83.1 (f1b07bd25dfad64b0167beb15359ae573aecd2cc, 2023-10-10T23:48:05.904Z)
OS version: Windows_NT x64 10.0.22621
Modes:

**Comment by roblourens** [comment]
This sounds like an issue with your code or configuration, not the editor
