### ISSUE TITLE
Console.Write produces no output but Console.WriteLine does

### ISSUE THREAD

**Issue by dochoss** [microsoft/vscode#196428]
Type: <b>Bug</b>

Steps to Reproduce:

1. Create a new C# console app (`dotnet new console`)
2. Add the following:
```
Console.Write("What's your name?  ");
string name = Console.ReadLine();
```
3. Run with Debugging by pressing F5
4. No output is generated in Output, Debug Console, or Terminal window.

Changing to `Console.WriteLine("What's your name? ")` does generate output.  However, this behavior is not consistent in Visual Studio 2022.  In VS 2022, the initial output is as expected, a line of text with input cursor placed after the question mark and a space.  In a more detailed example with multiple `Console.Write()` statements, the only way to get the text to appear is to follow them with a `Console.WriteLine()` statement, even one with no parameters.  This behavior is only present in VS Code. 
 I would expect this behavior to be consistent across all IDEs.

This issue was reported previously but locked without any comment from the team.  See [Issue 124245](https://github.com/microsoft/vscode/issues/124245).

VS Code version: Code 1.83.1 (f1b07bd25dfad64b0167beb15359ae573aecd2cc, 2023-10-10T23:48:05.904Z)
OS version: Windows_NT x64 10.0.23570
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz (8 x 2995)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.84GB (12.44GB free)|
|Process Argv|--disable-extensions . --crash-reporter-id a832da33-6cce-46fb-94e4-eb74a4fa34d3|
|Screen Reader|no|
|VM|0%|
</details>Extensions disabled<details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
py29gd2263cf:30856253
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
3biah626:30602489
89544117:30613380
2i9eh265:30646982
showlangstatbar:30737416
0bi6i642:30841073
a2ce3375:30757347
pythonfmttext:30731395
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
pythonnosmt12:30797651
pythonidxpt:30866567
pythonnoceb:30805159
copilotsettingc:30859502
asynctok:30869155
dsvsc013:30795093
dsvsc014:30804076
dsvsc015:30845448
pythontestfixt:30866405
pyreplss1:30865275
pythoncet0:30866520
2e7ec940:30870395
pythontbext0cf:30864173

```

</details>

**Comment by roblourens** [comment]
Please file an issue on the C# extension repo, thanks
