### ISSUE TITLE
Aux window: support confirm on close

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#196433]
Testing #196195

1. set `window.confirmBeforeClose` to `always`
2. open a new window, for example, by moving a terminal into the new window
3. close the window
4. 🐛 no prompt to confirm the close

**Comment by bpasero** [comment]
**Verification:**
* open a floating window with some editors (e.g. by dragging an editor tab out of the window)
* configure `window.confirmBeforeClose: always`
* try to close the floating window from the window X button
* verify you see a confirmation dialog that you can proceed or cancel
* configure `window.confirmBeforeClose: keyboardOnly`
* try to close the floating window with keyboard shortcut
* verify you see a confirmation dialog that you can proceed or cancel
* try to close the floating window from the window X button
* verify you are not being asked
