### ISSUE TITLE
VS code does not load commit text when called from Windows git shell "commit" 

### ISSUE THREAD

**Issue by arnom-ms** [Microsoft/vscode#19652]
- VSCode Version: 1.8.1
- OS Version: Windows, 1607 (build 14393.693)
- Github desktop tools: Chocolate-Covered Yaks (3.3.3.0) bc4735a
 
 
Steps to Reproduce:
 
1.  Open a file/Edit a file with VS code, save. Leave the window open (simply opening a file a leaving the window open works as well)
2.  Use Windows Git Shell to commit (git commit -a or git commit)
3. A new VS code window will open but it will be empty. The git shell command will abort and no commit will have been made
 
Workaround: 
    * Close all VS Code instances
    * Issue a commit or commit -a 
    * VS code window will open and the commit message can be edited
    * Save and close 
    * Commit is done

**Comment by bpasero** [comment]
@arnom-ms did you setup Code to be the git editor? Can you explain your setup more?
