### ISSUE TITLE
Terminal hangs after launch - Pending response rejected since connection got disposed   Code: -32097 

### ISSUE THREAD

**Issue by Absoblogginlutely** [microsoft/vscode#196570]
Type: <b>Bug</b>

Terminal hangs  on launch of powershell.
It does go through my profile (twice). The first time it completes successfully and then starts the profile again but hangs after displaying the powershell editor version on the screen. (running my profile twice in a powershell window or Terminal does not have the same problem)
Pressing ctrl-c will popup the following error messages in the notification area and the output displays 

[Error - 6:51:27 AM] Server initialization failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 6:51:27 AM] Connection to PowerShell Editor Services (the Extension Terminal) was closed. See below prompt to restart!
[Error - 6:51:27 AM] PowerShell Editor Services client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097 

![Screenshot - 20231024-065437](https://github.com/microsoft/vscode/assets/21364480/7612a0e0-9db5-41ff-9260-46098bb0b2d0)

![Screenshot - 20231024-065459](https://github.com/microsoft/vscode/assets/21364480/3f41d8d4-0dae-4326-aabf-0f269893e8ab)

Log files attached
[vscode-powershell.zip](https://github.com/microsoft/vscode/files/13164343/vscode-powershell.zip)

Powershell extension version
ms-vscode.powershell@2023.8.0

[A] 07:08:39: C:\Users\helsb\.vscode> $psversionTable

Name                           Value
----                           -----
PSVersion                      7.3.8
PSEdition                      Core
GitCommitId                    7.3.8
OS                             Microsoft Windows 10.0.25977
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

VS Code version: Code 1.83.1 (f1b07bd25dfad64b0167beb15359ae573aecd2cc, 2023-10-10T23:48:05.904Z)
OS version: Windows_NT x64 10.0.25977
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 3700U with Radeon Vega Mobile Gfx   (8 x 2296)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|9.94GB (1.04GB free)|
|Process Argv|. --crash-reporter-id 18ac6969-deba-4137-b93c-524a202a2fb7|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (74)</summary>

Extension|Author (truncated)|Version
---|---|---
project-manager|ale|12.7.0
vscode-color|ans|0.4.5
color-info|bie|0.7.2
markdown-checkbox|bie|0.4.0
markdown-mermaid|bie|1.20.0
markdown-preview-github-styles|bie|2.0.3
LinkCheckMD|bla|0.3.1
vscode-better-align|cho|1.4.2
gitignore|cod|0.9.0
auto-dark-mode-windows|dan|1.0.11
vscode-markdownlint|Dav|0.52.0
docs-article-templates|doc|1.0.3
docs-authoring-pack|doc|1.0.0
docs-build|doc|0.4.2
docs-images|doc|1.0.1
docs-linting|doc|0.0.13
docs-markdown|doc|1.0.3
docs-metadata|doc|1.0.9
docs-preview|doc|1.0.3
docs-scaffolding|doc|1.0.3
docs-yaml|doc|1.0.1
git-extension-pack|don|0.1.3
githistory|don|0.6.20
gitlens|eam|14.4.0
EditorConfig|Edi|0.16.4
vs-code-xml-format|fab|0.1.5
git-project-manager|fel|1.8.2
vscode-github-actions|git|0.26.2
vscode-pull-request-github|Git|0.74.0
todo-tree|Gru|0.0.226
vscode-test-explorer|hbe|2.21.1
rest-client|hum|0.25.1
vscode-peacock|joh|4.2.2
powershell-extension-pack|jus|0.0.7
blockman|leo|1.7.5
regexp-preview|Lou|0.1.5
git-graph|mhu|1.30.0
gitignore|mic|1.0.1
vscode-azurefunctions|ms-|1.13.1
vscode-azureresourcegroups|ms-|0.7.5
vscode-bicep|ms-|0.22.6
vscode-docker|ms-|1.27.0
vscode-dotnet-runtime|ms-|1.8.1
mssql|ms-|1.21.0
sql-bindings-vscode|ms-|0.4.0
remote-containers|ms-|0.315.1
remote-ssh|ms-|0.106.5
remote-ssh-edit|ms-|0.86.0
remote-wsl|ms-|0.81.8
vscode-remote-extensionpack|ms-|0.24.0
azure-account|ms-|0.11.6
azurecli|ms-|0.5.0
powershell|ms-|2023.8.0
remote-explorer|ms-|0.4.1
remote-server|ms-|1.4.3
test-adapter-converter|ms-|0.1.8
vsliveshare|ms-|1.0.5883
azurerm-vscode-tools|msa|0.15.11
indent-rainbow|ode|8.3.1
vscode-github-projects|Pod|1.0.0
pester-test|psp|2023.7.7
vscode-thunder-client|ran|2.14.1
vscode-yaml|red|1.14.0
vscode-sort-json|ric|1.20.0
vscode-zipexplorer|sle|0.3.1
vscode-inline-values-powershell|Tyl|0.0.7
vscode-pester-test-adapter|Tyl|0.0.23
errorlens|use|3.15.0
vscode-icons|vsc|12.6.0
codetour|vsl|0.0.59
gistfs|vsl|0.4.1
gitdoc|vsl|0.1.0
markdown-all-in-one|yzh|3.5.1
vscode-open-in-github|ziy|1.3.6

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
py29gd2263:30856252
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
282f8724:30602487
f6dab269:30613381
showlangstatbar:30737416
962ge761:30841074
03d35959:30757346
pythonfmttext:30731395
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
pythonnosmt12:30797651
pythonidxpt:30866567
pythonnoceb:30805159
copilotsettingc:30859502
asynctok:30869155
dsvsc013:30795093
dsvsc014:30804076
dsvsc015:30845448
pythontestfixtcf:30866406
pyreplss1:30865275
2e7ec940:30869480
pythontbext0:30864172

```

</details>

**Comment by joyceerhl** [comment]
Does this repro when the Powershell extension is disabled?

**Comment by Absoblogginlutely** [comment]
Thanks for following up on this @joyceerhl , the issue has gone away by itself after an update of some kind. Not sure whether it was VSCode, PowerShell or Windows but all good now.
