### ISSUE TITLE
Multi file highlighting doesn't work in editor grid layout

### ISSUE THREAD

**Issue by gregvanl** [microsoft/vscode#196508]
Testing #196342

1. Switch the editor to Grid layout (View > Editor Layout > Grid (2x2))
2. Open the same file in each editor (for the repro I used Markdown file /docs/getstarted/userinterface.md in a local clone of the vscode-docs repo).
3. In the top left editor, click on "heart"

Only the top right editor displays "heart" as highlighted. "heart" is not highlighted in the other two bottom editors.

![image](https://github.com/microsoft/vscode/assets/12818376/389aedcd-12a8-4fc2-b3da-9e36fe009f4b)

Trying clicking on words in the other editors, only the top right seems to get highlighting.

**Comment by gregvanl** [comment]
Even with double-clicking to select the text (in this image below "the") again only the top right editor has highlighting.

![image](https://github.com/microsoft/vscode/assets/12818376/5fa1d723-2d95-4a27-ab94-a0724b903097)

**Comment by gregvanl** [comment]
Works better if different files are in the bottom grid positions. Cursor in on top left "the".

![image](https://github.com/microsoft/vscode/assets/12818376/ea60f5b6-608e-4e4a-bd3f-b99269122a4b)

**Comment by Yoyokrazy** [comment]
Closing as fixed, can't repro this and there have been a number of improvements to multi-doc highlighting since. Feel free to reopen with a repro or info of the current problem if it persists.
