### ISSUE TITLE
Contribution Offer: Can we add a startup scripts feature?

### ISSUE THREAD

**Issue by anasouardini** [microsoft/vscode#196595]
I'd love to see this feature where we could have a directory named "scripts" where one could store scripts that could run on startup or on an event.

It could be used like a config file, instead of JSON, a JS file could enable so much flexibility when configuring you VSCode setup. It could also be used like a tiny extension that requires low effort to make.

I've used similar feature in nVim/Vim for 12+ months and I think it's a really good idea to have such feature. Now that I'm switching back to VSCode, I think it would be nice to see this much flexibility in a code editor this stable.

Let me know what you think, I'm willing to work on this feature if it's something of an interest.

**Comment by roblourens** [comment]
The interesting question is what you want the script to do. The feature you want probably already exists via settings or an extension.

**Comment by anasouardini** [comment]
Pretty valid question. Well, settings are good enough, but they're not dynamic, a script would give me that.

For instance: changing the default terminal in my OS doesn't automatically change it accordingly in VSCode, I would love to write a script that checks for the default one and use it whenever I lunch the editor.

I also recently did some blogging and tried to make an extension that only runs locally to handle all the word count and other SEO metrics in a new tab/view. I thought it would be really simple to just start typing the code instead of the whole setup.

Thanks for consideration.
