### ISSUE TITLE
show tooltip on keyboard focus of status/activity bar

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#196500]
This ask is from the Copilot team in response to feedback they've received.

When something is represented via only an icon, and is focused via keyboard, we should automatically focus the tooltip.

**Comment by Tyriar** [comment]
cc @sandy081

**Comment by meganrogge** [comment]
related #132344

**Comment by meganrogge** [comment]
we would also want to do this for all toolbars 

<img width="202" alt="Screenshot 2023-11-01 at 10 12 16 AM" src="https://github.com/microsoft/vscode/assets/29464607/d56bb668-8089-40f0-b20f-8f573227f500">

**Comment by starball5** [comment]
Just out of curiosity, what does "focus the tooltip mean"? Does it mean "make the tooltip visible"? (sorry- the language is a bit confusing. tooltips are not actually focusable, right?)

**Comment by Tyriar** [comment]
@starball5 yes I think @meganrogge meant to show the hover, not focus it as that would break left/right navigation.
