### ISSUE TITLE
Multiple selected terminal tabs won't close on pressing delete, only the current one would

### ISSUE THREAD

**Issue by mitsukuri** [microsoft/vscode#196578]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: Version: 1.83.1
- OS Version: Ubuntu 22.04.3

Steps to Reproduce:

1. Add any number >1 of new terminals by clicking on `+` button in the terminal panel header
2. Select all terminal tabs with ctrl+click, shift+click or ctrl+A when the terminal tab panel is active
3. Press delete

Expected outcome: All selected terminals close at once - used to be this way in prior versions.

Actual outcome: Only the currently active terminal closes, and others get deselected and remain open.

[Screencast from 25.10.2023 13:32:17.webm](https://github.com/microsoft/vscode/assets/88905839/90eea603-e7e4-47c5-af4b-650a98bc7359)

**Comment by tisilent** [comment]
https://github.com/microsoft/vscode/blob/2ff3e98d7747f922188bb4c7eca2c28733f3ae51/src/vs/workbench/contrib/terminal/browser/terminalActions.ts#L1616-L1620

**Comment by tisilent** [comment]
In this way, multiple selections and deletions can only be made through the menu, and the shortcut keys will operate according to the previously accessed menu.

**Comment by tisilent** [comment]
In this way, multiple selections and deletions can only be made through the menu, and the shortcut keys will operate according to the previously accessed menu.
I'm not sure how to obtain the action source.

**Comment by amunger** [comment]
This still occurs for me when the terminals have the same name, i.e. selecting two terminals named pwsh and pressing delete only kills one of them. If I rename one and select both and press delete, they are both killed

**Comment by meganrogge** [comment]
weird, I cannot reproduce in OSS, only in insider's. 
Uploading Screen Recording 2023-12-06 at 3.56.52 PM.mov…

**Comment by meganrogge** [comment]
Ah, I see what's happening. I hadn't accessed either of these menus yet, so `lastAccessedMenu` is set to `inline-tab` here. 

https://github.com/microsoft/vscode/blob/0156e4e2df177395fbaefd04552277ceb717e39d/src/vs/workbench/contrib/terminal/browser/terminal.ts#L440

**Comment by meganrogge** [comment]
and then it returns here.

![Screenshot 2023-12-06 at 4 14 00 PM](https://github.com/microsoft/vscode/assets/29464607/03b58a9b-7dd4-4fbf-b6f6-ed14edfa3e34)

**Comment by meganrogge** [comment]
To verify/ reproduce, do not right click / open any terminal context menu before:

- create a few split terminals
- hit `delete` (or `cmd+backspace`)

**Comment by mitsukuri** [comment]
Still not fixed in 1.85.1

**Comment by tisilent** [comment]
Unpublished, only insiders version released
