### ISSUE TITLE
Intellisense for required modules doesn't work in .vscode-test.js

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode#196554]
Testing #196332

This would also enable IntelliSense. The only way I could get it working is by changing the `require` to an `import`, but that then fails at runtime suggesting to use `"type": "module"` in the package.json.

**Comment by connor4312** [comment]
I think this is something in TS. It seems like `require()` types recently(?) stopped working in commonjs .js files. For instance, making a new file `foo.js` in the vscode repo doesn't get types for requiring TypeScript. It also doesn't get types for built-in Node modules, in spite of them appearing as completions.

![image](https://github.com/microsoft/vscode/assets/2230985/eb7abad5-f7b3-4446-9c88-788043a702ab)

Intellisense did work in commonjs files when I first made it a few weeks ago.
