### ISSUE TITLE
Cryptic error message for presumably a malformed `vscode-remote` URL

### ISSUE THREAD

**Issue by brettcannon** [microsoft/vscode#196506]
Testing #196192

Triggered by trying `vscode-insiders://vscode-remote/https://github.com/brettcannon/microvenv/blob/main/.github/workflows/release.yml` :

![image](https://github.com/microsoft/vscode/assets/54418/77a7ce3e-b8f4-42d5-a0ec-b1eaa2bd413f)

**Comment by bpasero** [comment]
Can you clarify what better message you would have expected?

**Comment by brettcannon** [comment]
Probably something telling me how I messed the URL up. Is their an allowlist or some way to know what the valid authorities are so you can tell me how I specified the wrong one? For instance, I specified an HTTP URL that I wanted to open, so being told that some port isn't opened suggested to me that some unspecified port wasn't opened on the GitHub side, not that I have a malformed URL.

**Comment by bpasero** [comment]
Such a URL basically requires you to have an extension installed that can handle the remote authority. There is only very few: SSH, DevContainer, WSL and Codespaces I think.
