### ISSUE TITLE
Improve MD streaming for inline chat

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#196551]
We have a first version of MD streaming for inline chat but it doesn't smoothen out chunks of replies (as panel chat or progressive editing does). This needs to be done and further alignment/re-use with panel chat rendering should happen

**Comment by starball5** [comment]
Out of curiosity, what's "MD streaming"?

**Comment by aeschli** [comment]
Markdown

**Comment by aeschli** [comment]
Implemented by https://github.com/microsoft/vscode/pull/198525
