### ISSUE TITLE
Cursor in terminal is smaller than a character

### ISSUE THREAD

**Issue by uRohan** [microsoft/vscode#196512]
Type: <b>Bug</b>

Steps to Reproduce:

1. Type some character in the terminal and observe that the cursor is smaller than the entered character.

Here's what it looks like:
| A | B |
| -------- | ------- |
| ![Screenshot from 2023-10-25 00-59-39](https://github.com/microsoft/vscode/assets/11392016/d4a73984-2ffe-4777-a691-fefde3b89d21) | ![Screenshot from 2023-10-25 01-00-09](https://github.com/microsoft/vscode/assets/11392016/5fb0fcac-a68e-4efa-8bad-2210da16ad79) |
| ![Screenshot from 2023-10-25 00-59-53](https://github.com/microsoft/vscode/assets/11392016/10b16e95-720a-43c5-be28-a2b74ec24dfe) | ![Screenshot from 2023-10-25 00-59-58](https://github.com/microsoft/vscode/assets/11392016/5f58fba0-6d2f-45a7-95a9-0646c2cc2770) |

VS Code version: Code - Insiders 1.84.0-insider (7dff07893ac160244db210e574eccc05f1cba2cb, 2023-10-24T05:33:19.453Z)
OS version: Linux x64 6.2.0-35-generic snap
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3610QM CPU @ 2.30GHz (8 x 3093)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|1, 1, 1|
|Memory (System)|7.63GB (4.33GB free)|
|Process Argv|--no-sandbox --force-user-env --unity-launch --crash-reporter-id a7ecc774-f9b4-45e2-8a73-490f4d1c756d|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vslsvsres303:30308271
pythontb:30258533
pythonptprofiler:30281269
vshan820:30294714
vscod805:30301674
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30404738
py29gd2263:30784851
vscaat:30438846
vsclangdf:30492506
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30618038
a9j8j154:30646983
showlangstatbar:30737417
57b77579:30687741
pythonfmttext:30716741
fixshowwlkth:30771523
showindicator:30805243
pythongtdpath:30726887
i26e3531:30792625
welcomedialog:30812478
pythonnosmt12:30779711
pythonidxpt:30768918
pythonnoceb:30776497
copilotsettingt:30808721
asynctok:30869155
dsvsc013:30777762
dsvsc014:30777825
pythonmhint1:30859868
dsvsc015:30821418
pythontestfixt:30866404
pyreplss1:30865275
pythonmypyd1:30859725
pythoncet0:30859736
pythontbext0:30864172
accentitlementst:30870582

```

</details>

**Comment by meganrogge** [comment]
What are your settings?

**Comment by uRohan** [comment]
It's clean Visual Studio Code - Insiders installation to fill a report. I have observed it in regular 1.83.1 version.

**Comment by meganrogge** [comment]
Great, pls provide your settings.json file

**Comment by uRohan** [comment]
Okay, but like I said, in the case of Visual Studio Code - Insiders it's an empty file (I have no modified settings): [settings.json](https://github.com/microsoft/vscode/files/13166033/settings.json)

**Comment by uRohan** [comment]
In the case of my regular Visual Studio Code installation, it is: [settings.json](https://github.com/microsoft/vscode/files/13166101/settings.json).

**Comment by uRohan** [comment]
I initially identified a bug in the regular 1.83.1 version of Visual Studio Code. To confirm its presence, I conducted further testing with a clean installation of Visual Studio Code - Insiders and observed that the issue persists in the Insiders version as well.

Apologies if my initial explanation was unclear.

**Comment by uRohan** [comment]
It also occurs in the editor as well. Steps to reproduce:
1. Use [settings.json](https://github.com/microsoft/vscode/files/13166346/settings.json).
2. Write some characters in the editor.

Here's what it looks like:
| A | B |
| -------- | ------- |
| ![Screenshot from 2023-10-25 16-20-36](https://github.com/microsoft/vscode/assets/11392016/033f62a2-2647-48f1-a534-024ae0aaff92) | ![Screenshot from 2023-10-25 16-20-41](https://github.com/microsoft/vscode/assets/11392016/79470e67-53d1-4dc8-8a95-81d8a83a9cb6) |
| ![Screenshot from 2023-10-25 16-20-22](https://github.com/microsoft/vscode/assets/11392016/2e932465-2a5e-4557-aa79-a0e8efb4ec68) | ![Screenshot from 2023-10-25 16-20-27](https://github.com/microsoft/vscode/assets/11392016/5f53dd2c-d4c7-4bcd-a1e8-853e9ca2da34) |

**Comment by Tyriar** [comment]
This is fine, the font that you happen to be using just isn't truly monospace and the & is larger than the letters. Nothing we should do to workaround this as either the char would get clipped or each char would be wider than necessary.

**Comment by uRohan** [comment]
For example, here the JetBrains Mono font is used:
| A    | B |
| -------- | ------- |
| ![Screenshot from 2023-10-25 22-04-14](https://github.com/microsoft/vscode/assets/11392016/e927e664-a7e1-465c-aed6-a7624f66109e)  | ![Screenshot from 2023-10-25 22-04-37](https://github.com/microsoft/vscode/assets/11392016/1e9080be-0683-4ae3-925d-de27c57a8c66) |

**Comment by uRohan** [comment]
For example, here the Cascadia Mono font is used:

| A | B |
| -------- | ------- |
| ![Screenshot from 2023-10-25 22-35-43](https://github.com/microsoft/vscode/assets/11392016/0bcf5919-8318-45cb-85b7-0f4b83aed26c) | ![Screenshot from 2023-10-25 22-35-54](https://github.com/microsoft/vscode/assets/11392016/28bb468a-1e4e-4887-9530-9b5cafd9817d) |
