### ISSUE TITLE
When I switch another desktops, it bounces to old desktop.

### ISSUE THREAD

**Issue by teighteeng** [microsoft/vscode#196564]
Type: <b>Bug</b>

# Description
When I focus on vscode and then change the desktop to another one, the system bounces to the original desktop. If I focus on another program, I can change the desktop normally.

# Video Demo
https://drive.google.com/file/d/1gxXhv2IiUNEFqGFzQAb8_nu4uSc9aUSM/view?usp=sharing

# Computer
MacBook Pro M1 Pro 2021 16-inch

VS Code version: Code 1.83.1 (f1b07bd25dfad64b0167beb15359ae573aecd2cc, 2023-10-10T23:57:32.750Z)
OS version: Darwin arm64 23.0.0

**Comment by deepak1556** [comment]
This requires workspace support from the runtime, merging to https://github.com/microsoft/vscode/issues/123517
