### ISSUE TITLE
Screen Reader mode enabled without intent

### ISSUE THREAD

**Issue by digitarald** [microsoft/vscode#196505]
Type: <b>Bug</b>

Restarted Insiders for an update and Screen Reader mode is suddenly on, including audio cues while typing. I have no idea how to disable it, as the `Screen Reader Optimized` status bar icon is clickable (changes color), but doesn't do anything.

(Edit: I eventually found `editor.action.toggleScreenReaderAccessibilityMode` command, but I don't see any logs that I used that command before)

cc @meganrogge who recommended @deepak1556 as assignee.

![image](https://github.com/microsoft/vscode/assets/8599/6fa81229-ca70-4815-b307-f0054addc212)

VS Code version: Code - Insiders 1.84.0-insider (7dff07893ac160244db210e574eccc05f1cba2cb, 2023-10-24T05:35:10.309Z)
OS version: Darwin x64 23.0.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|4, 4, 4|
|Memory (System)|64.00GB (0.74GB free)|
|Process Argv|--log trace --crash-reporter-id 4cf0a6f0-aaf8-4da3-9b2b-81f6c639c12b|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by meganrogge** [comment]
@deepak1556 not aware of any changes on your end, so i'm just reverting the only relevant PR

**Comment by digitarald** [comment]
Just launched a fresh Insiders and got this notification:

![image](https://github.com/microsoft/vscode/assets/8599/db810682-a88e-4e7d-a014-5d1c2eece0dc)

I do see it detecting a11y for me in telemetry events

`telemetry/accessibility … "measurements":{"enabled":1`…`

Version: `18b7f75a9fab40499744c2e9c6ba9af64d5c6744`, 2023-10-25T05:37:06.169Z (9 hrs ago)

**Comment by meganrogge** [comment]
Indeed then, it seems an issue with detection @deepak1556 , not sure why this would be showing otherwise as nothing's changed on my side.

**Comment by deepak1556** [comment]
No changes have been made in the runtime with respect to a11y detection, on macOS the runtime can enter a11y mode in the following 2 scenarios,

1) Setting `AXEnhancedUserInterface` attribute on the application which is usually done by screen readers (VoiceOver)
2) Setting `AXManualAccessibility` attribute on the applications which is usually done by third party window managers

@digitarald are you using any custom window tiling managers ?

**Comment by digitarald** [comment]
I do run window managers, yes. So, I guess I'll close this for now as it might have been an update, like Bartender 5.
