### ISSUE TITLE
Aux window: terminal editor doesn't show underscore for links

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#196501]
Testing #196195

* Open a terminal in editor area
* Open in new window
* `ls`
* Press meta and hover on the file names, none of them are linkified and the mouse pointer doesn't change on hover. However clicking does open the file

**Comment by bpasero** [comment]
This seems to be within the `canvas`, I am not sure how that is done and if that needs multi-window support.

**Comment by MuhamedAbdalla** [comment]
@bpasero 
I'm interested in conquering this issue, Please.

I want to rephrase the issue again to just confirm my understanding
- When we open the terminal in vscode then we write ls.
1- the mouse pointer is not changing (change at the first press then not)
2- it's not linked to the path of the file & not opening the file in vscode window too

**Comment by bpasero** [comment]
@rebornix I cannot reproduce anymore?
