### ISSUE TITLE
Win11 context menus "Open with Code" not working

### ISSUE THREAD

**Issue by romulof** [microsoft/vscode#196567]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.83.1
- OS Version:  Win 11 (10.0.22621)

Steps to Reproduce:

1. Uninstall VSCode
2. Install VSCode (user mode), marking the options to create "Open with Code" context menus for both files and folders
3. Finish installation and open VSCode to check if everything is working fine
4. Restart Explorer.exe
5. Right click files or folders in Explorer and the option is not there, only hidden behind "Show more options"

Apparently there is a problem with current implementation and/or something broke between then and now:
https://github.com/microsoft/vscode/issues/127365

**Comment by gjsjohnmurray** [comment]
AFAIK it's currently only available on the first-level menu if you install Insiders.

**Comment by AzonInc** [comment]
I also tried it several times with every version. However only the Insiders Build is working properly. Did the change ever went into stable?

**Comment by gjsjohnmurray** [comment]
Not yet.

https://github.com/microsoft/vscode/issues/127365#issuecomment-1288635483

@joaomoreno any schedule update for this to land in Stable?

**Comment by carlosrmendes** [comment]
fresh windows 11 pro, windows insiders beta channel enabled, then fresh install of vscode insiders 1.85.0 and the "Open with Code Insiders" still not available on Windows 11 context menu:
![image](https://github.com/microsoft/vscode/assets/7363029/58d10a2b-162e-4ce7-85fd-718a81a28cca)

**Comment by gjsjohnmurray** [comment]
@carlosrmendes  Did you set the related checkboxes in the Insiders installer dialog?

**Comment by carlosrmendes** [comment]
> @carlosrmendes Did you set the related checkboxes in the Insiders installer dialog?

yes, all checkboxes set

**Comment by gjsjohnmurray** [comment]
@carlosrmendes  I just noticed you did a System Setup of Insiders. Are you able to uninstall this, then install the User Setup kit?

**Comment by carlosrmendes** [comment]
- vscode insiders system setup uninstalled 
- pc restarted
- vscode insiders user setup installed 
- pc restarted
- issue persits:
![image](https://github.com/microsoft/vscode/assets/7363029/eda8cc68-493b-4808-b0f6-aea631425f38)

**Comment by carlosrmendes** [comment]
not even in the old context menu does the option to open with vscode insiders appear, making this issue quite critical:
![image](https://github.com/microsoft/vscode/assets/7363029/f147642f-7eb8-4564-a689-b29a81798445)

**Comment by carlosrmendes** [comment]
vscode insiders v1.86.0 and the issue still occurs

**Comment by deepak1556** [comment]
Adding the feature to stable is tracked under https://github.com/microsoft/vscode/issues/183297, please follow that issue for updates.

@carlosrmendes if you are unable to see the menu with latest insiders, please follow the steps in https://github.com/microsoft/vscode/issues/171911#issuecomment-1882892289 as next step. Thanks!
