### ISSUE TITLE
Github extension fails to push (invalid password) with 35 length password

### ISSUE THREAD

**Issue by kidandcat** [Microsoft/vscode#1965]
The github extension fails doing push with (authentication failed) 35 characters only alphanumeric password, the git bash client in cmd does the push (and the authentication) correctly.

**Comment by joaomoreno** [comment]
Which OS?

**Comment by kidandcat** [comment]
Windows 10

**Comment by lv7777** [comment]
I think this bug related #1138

**Comment by joaomoreno** [comment]
Closing as duplicate of #1138
