### ISSUE TITLE
Performance Report

### ISSUE THREAD

**Issue by seanmcbreen** [Microsoft/vscode#19660]
- VSCode Version: <code>Code - Insiders 1.9.0-insider (e68cede8b65dc918332493146c2572a7e132a451, 2017-01-27T20:44:13.107Z)</code>
- OS Version: <code>Windows_NT ia32 10.0.14393</code>
- CPUs: <code>AMD Phenom(tm) II X6 1035T Processor (6 x 2593)</code>
- Memory (System): <code>12.00GB (4.78GB free)</code>
- Memory (Process): <code>133.61MB working set (141.84MB peak, 92.19MB private, 48.81MB shared)</code>
- Load (avg): <code>0, 0, 0</code>
- VM: <code>0%</code>
- Initial Startup: <code>yes</code>
- Screen Reader: <code>no</code>
- Empty Workspace: <code>yes</code>
- Timings:

|Component|Task|Time (ms)|
|---|---|---|
|main|start => app.isReady|160|
|main|app.isReady => window.loadUrl()|851|
|renderer|window.loadUrl() => begin to require(workbench.main.js)|535|
|renderer|require(workbench.main.js)|2597|
|renderer|create extension host => extensions onReady()|1400|
|renderer|restore viewlet|0|
|renderer|restore editor view state|848|
|renderer|overall workbench load|1924|
|main + renderer|start => extensions ready|5917|
|main + renderer|start => workbench ready|6095|

I also have included extensions here:

|Extension|Author|Version|
|---|---|---|
|rainbow-brackets|2gua|0.0.6|
|extension-leaderboard|formulahendry|0.0.2|
|mssql|Microsoft|0.1.5|
|java|redhat|0.0.7|
|todotasks|sandy081|0.4.0|
|kustovscode|seanmcbreen|0.0.3|
|Spell|seanmcbreen|0.9.1|
|vim|vscodevim|0.4.9|

---

Additional Steps to Reproduce (if any):

So I thought I would test this anything obvious here?  I opened via explorer a _empty_ text file.  This PC should rock on perf and I did this as it was noticeably slower...

**Comment by bpasero** [comment]
@seanmcbreen how about a warm start as comparison?

**Comment by bpasero** [comment]
A number of days has past without answer on the questions asked. I am thereby going to close this issue to clean up our backlog of issues. Once you can answer on the questions, the issue can be reopened again. Thanks for understanding this process!
