### ISSUE TITLE
Missing type information

### ISSUE THREAD

**Issue by MudulOzan** [microsoft/vscode#196675]
![image](https://github.com/microsoft/vscode/assets/29442243/ba261e94-1a05-42db-b1f8-66f9814045f3)
![image](https://github.com/microsoft/vscode/assets/29442243/7b647f5e-3502-4eb5-86ad-dbd73694f9c0)

First image from vscode and second from typescript playground https://www.typescriptlang.org/play
I must see number or null array but instead I see only number array which is misleading

**Comment by mjbvz** [comment]
Looks like you don't have strict null checks enabled in VS Code. They are on by default in the playground
