### ISSUE TITLE
Highlight terminal commands subtly when mousing over them

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#196634]
Highlighting a block would give the user a hint when hovering the terminal that it knows a lot more than a regular terminal. For example this part could be slightly darker or lighter depending on the theme:

![Image](https://github.com/microsoft/vscode/assets/2193314/02d7f08f-28af-4d55-a100-15d09b502468)

**Comment by Tyriar** [comment]
This needs https://github.com/xtermjs/xterm.js/issues/4855 and probably another API that forces the decoration to render on non-null cells

**Comment by Tyriar** [comment]
Another idea is to extends the solid bar on the left when hovering, right clicking could bring up the command's SI menu

**Comment by Tyriar** [comment]
I got a basic version of this working and it looked out of place:

![image](https://github.com/microsoft/vscode/assets/2193314/2608a19c-9f8b-444e-83bb-4741bcf0efb9)


Instead of background color I tried the re-use the command navigation focus bar on the left and it felt too noisy, especially when you compare it to what the editor looks like when you hover it.

Prototype: https://github.com/microsoft/vscode/pull/198219

I started a discussion with the team

**Comment by tocic** [comment]
Thank you for this feature, very useful for me! Is it possible to adjust the color of this bar? I can't find a setting [here](https://code.visualstudio.com/api/references/theme-color#integrated-terminal-colors).
