### ISSUE TITLE
[Debug] Make configurable attach timeout

### ISSUE THREAD

**Issue by Deilan** [Microsoft/vscode#19668]
- VSCode Version: 1.8.1
- OS Version: Windows 8.1 x64

Would like to have an option to change attach timeout because there are times when the app being debugged need more time to initialize before getting ready to accept attach request than hardcoded 10 seconds. Especially when using hybrid debugging and/or prelaunch task take up time.

Right now there is only a hacky way to change it - by opening the file
`c:\Program Files (x86)\Microsoft VS Code\resources\app\extensions\ms-vscode.node-debug\out\node\nodeDebug.js`

and changing `NodeDebugSession.ATTACH_TIMEOUT` constant's value to the desired.

**Comment by weinand** [comment]
Using Intellisense in a launch.json shows that we already support a `timeout` attribute for both 'launch' and 'attach':

![2017-02-01_16-58-03](https://cloud.githubusercontent.com/assets/1898161/22514476/c065a474-e89f-11e6-95a4-0f2ef419cd49.png)

**Comment by Deilan** [comment]
@weinand Sorry for not being specific enough right from the beginning. I've checked out, and `timeout` is there for "type": "node". But my case is about `"type": "chrome"`. And for that case there is no appropriate option:

![untitled](https://cloud.githubusercontent.com/assets/4777512/22517088/05e294e4-e8b9-11e6-9204-95ec1e6309f4.png)

**Comment by weinand** [comment]
But you said above that you've hacked `c:\Program Files (x86)\Microsoft VS Code\resources\app\extensions\ms-vscode.node-debug\out\node\nodeDebug.js` which is for the 'node' debug type. So your hack does not work for `"type": "chrome"`.

**Comment by weinand** [comment]
Please file the feature request against the Chrome debug extension: https://github.com/microsoft/vscode-chrome-debug
