### ISSUE TITLE
VS code can't find some files!!!

### ISSUE THREAD

**Issue by gene-liang** [microsoft/vscode#196601]
Some files opened in vs code can't be found when you hit ctrl + p, and you can't get the results from the file when searching it's text until you open the file in the text editor, both occurred in wsl2 and virtualbox linux, I kind of believe that's because I have created a dozens of file hard links which made vscode uncomfortable and it refused to work properly.
This prevent me from using the vscode, I wish this could be fixed asap.

I don't understand why it's a problem to find files, it looks to me you just need to replace your code with "find" command for wsl, that should solve everything.

I believe this is a very serious issue, because I believe a lot of people won't use vscode anymore if it has this kind of serious bug, because it returns the fake results to the user.

VS Code version: Code 1.83.1 (f1b07bd25dfad64b0167beb15359ae573aecd2cc, 2023-10-10T23:48:05.904Z)
OS version: Windows_NT x64 10.0.19045
Modes:
Remote OS version: Linux x64 5.15.90.1-microsoft-standard-WSL2

**Comment by andreamah** [comment]
Does this still happen with extensions disabled? What is your `search.excludes` setting set to?

**Comment by gene-liang** [comment]
> Does this still happen with extensions disabled? What is your `search.excludes` setting set to?

Hi, there is no extension installed in my vscode except for wsl. I have tried to load the project in vscode not by wsl, but still happened.
I don't set the exclude options in the search panel, and I make no change to search settings in the setting file.
The find command in linux can work, which I suggest you use in vscode directly for wsl.

**Comment by gene-liang** [comment]
The rpm version has the same bug, no extension installed, settings are all by default.

**Comment by andreamah** [comment]
Can you try this?

1. run `Developer: Set Log Level`  in the command palette and set `Trace`
2. do a search
3. In the bottom panel, check logs in the `Extension Host (Remote)` channel in the `Outputs` tab.

Is there a line that starts sort of like this?
```
RipgrepSearchEH#search c:\Users\andreamah\AppData\Local\Programs\Microsoft VS Code\resources\app\node_modules.asar.unpacked\@vscode\ripgrep\bin\rg.exe 
```

Then, if you invoke the rg executable directly from the command line, what happens?
