### ISSUE TITLE
Installation trigger for Python extension when Python language is selected in an untitled file 

### ISSUE THREAD

**Issue by cwebster-99** [microsoft/vscode#196640]
Current behavior: If a user opens a Python file (.py) or saves a file with a .py extension and does not have the Python extension installed, VS Code suggests installing the Python extension for Python support using the prompt below: 
<img width="236" alt="image" src="https://github.com/microsoft/vscode/assets/60238438/f741421e-7b59-485a-9056-2f3073faf228">

Proposed behavior: 
It would be nice if we could have an installation trigger/prompt to install the Python extension before a user saves the file with the appropriate file extension. In this case, if the user creates a new untitled file --> selects Python from the language dropdown --> the user is prompted to install the Python extension (flow depicted in the gif below)
![Python language selected in untitled file](https://github.com/microsoft/vscode/assets/60238438/7f752d61-d556-4ea5-b511-a3f3bb0e9158)

In user studies, we have observed users struggle to find where to install the Python extension (or do not realize they need an extension for Python support) and do not think to save the file in this case causing them to get stuck at this point.

**Comment by sandy081** [comment]
I remember this used to be supported and would have broken sometime back.

**Comment by sandy081** [comment]
Is not the other scenario same as this - At the end of both scenarios, the language mode of the file has changed to python.
Language mode change will trigger the recommendation.

**Comment by cwebster-99** [comment]
In the second scenario, the user has to click the lightbulb in order to get the language mode to change (or have the setting to automatically switch the language mode to the detected language enabled). The idea there was to prompt the user if the model detects their code to be Python, without the user having to click on the small lightbulb in the bottom corner. We haven't observed users engaging with or noticing the status bar much which was the motivator of that scenario.

**Comment by sandy081** [comment]
I see. I will reopen the other issue for that scenario. Can you please update the issue and mention the use case clearly. Thanks.
