### ISSUE TITLE
auto-completion annoyance

### ISSUE THREAD

**Issue by perdigao1** [microsoft/vscode#196605]
Type: <b>Feature Request</b>

in a jupyter notebook set to python.

Just type quickly

`a=""<enter>`

and it writes
`a=""ArithmeticError`

VS Code version: Code 1.83.1 (f1b07bd25dfad64b0167beb15359ae573aecd2cc, 2023-10-10T23:48:05.904Z)
OS version: Windows_NT x64 10.0.22621
Modes:

**Comment by jrieken** [comment]
@perdigao1 Can you reproduce this when the python language extension is disabled? Can you provide a screen recording of this? And overall can you still reproduce this?

**Comment by perdigao1** [comment]
Thank you for checking this problem. With VS code updated I still get the same problem.

This is the gif video of the occurrence
![Image](https://github.com/user-attachments/assets/810f8e72-5ec9-4393-900c-4b391d9759a5)


If I disable the Python extension the jupyter cell cannot be written in python, just plain text. Neither I can choose a conda environment.
