### ISSUE TITLE
Breadcrumbs Independent From showTabs Setting

### ISSUE THREAD

**Issue by benibenj** [microsoft/vscode#196695]
Allow Breadcrumbs to be shown when tabs are hidden and possibly also when using single tab.

// cc @bpasero

**Comment by bpasero** [comment]
Breadcrumbs already show in single-tab mode.

**Comment by benibenj** [comment]
verification steps:

1. Set `breadcrumbs.enabled: true`
2. Set `workbench.editor.showTabs: multiple`
3. Tab bar disappears but breadcrumbs can be seen. (Breadcrumbs did not used to render even though it was enabled)
