### ISSUE TITLE
Warning when trying to debug FastAPI

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#196621]
Testing microsoft/vscode-python#22301

Following https://github.com/microsoft/vscode-docs/pull/6760/files, I created main, pressed F5 and selected FastAPI

![Image](https://github.com/microsoft/vscode-python/assets/2193314/e5f9308e-fc80-4a74-b44d-78dc037b79a2)

I had v2023.18.0 installed:

![Image](https://github.com/microsoft/vscode-python/assets/2193314/6aa528bb-cadb-48d0-9350-4e18b3db6e9d)

Reloading seemed to have fixed it

**Comment by Tyriar** [comment]
It was activated, just the latest version wasn't installed for some reason (I created a new Codespace)

**Comment by luabud** [comment]
I've tried multiple times but I am unable to repro this in a new Codespace. I'll close this under the assumption this was a transient issue.
