### ISSUE TITLE
Handlerbars syntax highlight for comments is wrong and interfers with HTML code

### ISSUE THREAD

**Issue by rickysixx** [microsoft/vscode#196701]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.83.1
- OS Version: Windows 11 

Steps to Reproduce:

1. create an `.html` file and open it using VS Code;
2. add this content in the file:

```handlebars
<script>
    {{!-- Change document class from no-js to js so we can detect this in css --}}
    document.documentElement.className = document.documentElement.className.replace('no-js', 'js');
</script>
```

3. set the language of the file to `Handlebars` (using the bottom-right menu)

The result is this:

![image](https://github.com/microsoft/vscode/assets/51907568/fa693244-20ff-40b7-89a1-dc95b15efd4e)

As you can see, the comment is not properly colored. Some words are colored like keywords (e.g. `class`), even though they appear inside a comment.

Also, this seems to interfere with HTML code, because the closing `</script>` tag is colored differently than the opening `<script>` tag. If I remove the comment entirely, the `</script>` tag is corretly colored:

![image](https://github.com/microsoft/vscode/assets/51907568/f6bd2a7a-0a70-4e5b-a8e4-e3e41468aac5)

**Comment by alexr00** [comment]
According to https://github.com/daaain/Handlebars/issues/109 (that's the repo we pull our handlebars syntax highlighting grammar from), this is expected. Instead, you can add a type to the script:

```
<script type="text/x-handlebars">
    {{!-- Change document class from no-js to js so we can detect this in css --}}
    document.documentElement.className = document.documentElement.className.replace('no-js', 'js');
</script>
```
