### ISSUE TITLE
Border color - Where is it ?

### ISSUE THREAD

**Issue by sirCleSquare** [microsoft/vscode#196726]
Type: <b>Bug</b>

I configured Windows 10 so that the borders of the current application windows, when they are occupying part of the desktop (not maximized, not minimized), are blue (it could be any other color) but VS Code remains dark in color.
There is a serious problem in Windows and also in VS Code that they do not use these border colors and then it becomes very confusing to use multiple open windows because there is no delimitation of the current application being updated. Keeping up with the dark theme is a problem. Where are the active window borders?

VS Code version: Code 1.83.1 (f1b07bd25dfad64b0167beb15359ae573aecd2cc, 2023-10-10T23:48:05.904Z)
OS version: Windows_NT x64 10.0.19045
Modes: Restricted

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-2667 v4 @ 3.20GHz (16 x 3193)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.84GB (11.23GB free)|
|Process Argv|--crash-reporter-id 4c792baf-ea3a-4320-99ae-832f0afdccf2|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
remote-wsl|ms-|0.81.8

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
py29gd2263cf:30856253
vscaat:30438848
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
3biah626:30602489
f6dab269:30613381
showlangstatbar:30737416
962ge761:30841074
03d35959:30757346
7ij38806:30736111
pythonfmttext:30731395
f8hc8238:30694864
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
pythonnosmt12:30797651
pythonidxpt:30866567
pythonnoceb:30805159
copilotsettingt:30859503
dsvsc013:30795093
dsvsc014:30804076
dsvsc015:30845448
pythontestfixtcf:30871695
pythonregdiag2:30871582
pyreplss1:30865275
2e7ec940:30870395
pythontbext0:30864172

```

</details>

**Comment by gjsjohnmurray** [comment]
See https://code.visualstudio.com/api/references/theme-color#window-border for the names and https://code.visualstudio.com/docs/getstarted/themes#_customizing-a-color-theme for how you can customize the theme you are using.

**Comment by aeschli** [comment]
Thanks @gjsjohnmurray for the answer. Closing the issue.
