### ISSUE TITLE
Add button to close scope inspector

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode#19675]
- VSCode Version: Code - Insiders 1.9.0-insider (fcac9b686abe4292e69a774f61c8c4ce17768bf5, 2017-01-31T02:07:54.028Z)
- OS Version: Darwin x64 15.6.0
- Extensions:

|Extension|Author|Version|
|---|---|---|
|vscode-eslint|dbaeumer|1.2.2|
|tslint|eg2|0.8.1|
|debugger-for-chrome|msjsdiag|2.5.0|
|vetur|octref|0.2.1|
|language-stylus|sysoev|1.6.0|
|vim|vscodevim|0.5.2|

---

Currently there is no way to close it. Only switching to another tab seems to do it.
Maybe add a close button or use ESC for closing it?

**Comment by alexandrudima** [comment]
PR welcome.
