### ISSUE TITLE
Document how StandardTokenType is selected

### ISSUE THREAD

**Issue by DanTup** [microsoft/vscode#196725]
I'm trying to track down a bug with code completion not automatically triggering in a location where it's expected. The issue turns out to be that the "Standard Token Type" at this location is "String" but we're actually in an interpolated expression (and want "Other"):

![image](https://github.com/microsoft/vscode/assets/1078012/0cb77c6b-6093-45fb-97bc-12c80b6ca1b0)

I checked the equivalent in TypeScript and the standard token type is "Other":

![image](https://github.com/microsoft/vscode/assets/1078012/a45261cb-6e20-4cd1-b4ba-71eabbe0ff3a)

Looking through the code, I found this code that _appears_ to regex on the scope name:

https://github.com/microsoft/vscode/blob/10a184f69bc99b4aad5f5633c7cc5ba54c65c6dc/src/vs/editor/common/languages/supports/tokenization.ts#L247-L264

So I change the scope to no longer start with `string` (some of the parent scopes do, but that's also the case for TypeScript), using the same scope name TS did. However, this did not change the standard token type:

![image](https://github.com/microsoft/vscode/assets/1078012/307b9886-c59e-40c1-af35-168b35281478)

I can't find any documentation about this, but since it impacts things like code completion I think it should be clear what a language/grammar should do to ensure these things are categorised correctly.

Thanks!

**Comment by DanTup** [comment]
I also tried adding this to the grammar (since I found it noted in some files - even though TS doesn't have it):

```js
"tokenTypes": {
		"string.interpolated.expression.dart": "other"
	},
```

But that also didn't change anything, it's still `String`.

**Comment by DanTup** [comment]
@alexdima @alexr00 are you able to point me at how this works? I don't know whether there is a bug here, or whether there's a simple answer I wasn't able to find. Thanks :-)

**Comment by alexdima** [comment]
@DanTup It is possible to define custom scopes <-> types mappings when contributing a grammar. Here's how TS is doing it:

https://github.com/microsoft/vscode/blob/97082b0ca528e64fb1be0adcda9b1876fb223d05/extensions/typescript-basics/package.json#L76-L84

**Comment by DanTup** [comment]
@alexdima ah, I checked your link again and realise it was in `package.json` but I had tested with `tokenTypes` in the grammar file (that's why I didn't find it in TypeScripts - I looked in the wrong place!). Adding my example from above to `package.json` does work.

Thank you for the pointer, and sorry for the noise :-)
