### ISSUE TITLE
Got to bottom/top buttons for OUTPUT View

### ISSUE THREAD

**Issue by dyollb** [microsoft/vscode#196702]
When I run a build or configure a project with cmake, I often would like to see the latest messages. Currently, the OUTPUT view does not scroll so the newest message is always visible.

I would like to have either one or both of the following features:
- the OUTPUT view can be put into auto-scroll mode (e.g. a button near the X on the right)
- the OUTPUT view gets new buttons to jump to bottom/top.

**Comment by sandy081** [comment]
Please disable `output.smartScroll.enabled` this setting and check
