### ISSUE TITLE
Distortion in the main window: missing text

### ISSUE THREAD

**Issue by fsa** [microsoft/vscode#196747]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 
- OS Version: 

The versions cannot be divided because the window is empty. VSCode version 1.83.1. OS Version: Fedora 32.

Steps to Reproduce:

1.
sudo rpm --import https://packages.microsoft.com/keys/microsoft.asc
sudo sh -c 'echo -e "[code]\nname=Visual Studio Code\nbaseurl=https://packages.microsoft.com/yumrepos/vscode\nenabled=1\ngpgcheck=1\ngpgkey=https://packages.microsoft.com/keys/microsoft.asc" > /etc/yum.repos.d/vscode.repo'

Fedora 39 Beta.
lspci -k
00:01.0 VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] Trinity [Radeon HD 7640G]
	Subsystem: ASUSTeK Computer Inc. Device 10dc
	Kernel driver in use: radeon
	Kernel modules: radeon, amdgpu
 
Similar problems were observed with Google Chrome, but after the release of build updates, these problems disappeared.
![Screenshot_20231027_010757](https://github.com/microsoft/vscode/assets/1696211/cef6f0fe-d955-4a20-ab4d-22f391139ae0)
![Screenshot_20231027_010828](https://github.com/microsoft/vscode/assets/1696211/f1f50f93-6b57-4d37-9582-6b9fd8346356)

**Comment by gjsjohnmurray** [comment]
Please see https://code.visualstudio.com/updates/v1_82#_update-highlights-for-chromium for advice about clearing the GPU cache. I think this may need to be done after each VS Code update until the upstream issue gets fixed.

**Comment by fsa** [comment]
Problem solved by clearing the folder ~/.config/Code/GPUCache
Thank you!

**Comment by gjsjohnmurray** [comment]
Glad to hear that. Please close your issue.

**Comment by fsa** [comment]
Problem solved by clearing the folder ~/.config/Code/GPUCache
