### ISSUE TITLE
Unable to switch the version of the Python interpreter

### ISSUE THREAD

**Issue by 290qthfsgghredv** [microsoft/vscode#196719]
Type: <b>Bug</b>

Unable to switch the version of the Python interpreter. After selecting any Python version, nothing happens, no errors are output, and there is no effect. It is completely impossible to switch the version of the Python interpreter

VS Code version: Code 1.83.1 (f1b07bd25dfad64b0167beb15359ae573aecd2cc, 2023-10-10T23:48:05.904Z)
OS version: Windows_NT x64 10.0.22621
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.86GB (5.27GB free)|
|Process Argv|--crash-reporter-id fc54ce08-722a-4b69-af98-99216f847921|
|Screen Reader|no|
|VM|50%|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-language-pack-zh-hans|MS-|1.83.2023101109
python|ms-|2023.18.0
vscode-pylance|ms-|2023.10.40
jupyter|ms-|2023.9.1102792234
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.17
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-slideshow|ms-|0.1.5

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
py29gd2263:30856252
vscaac:30438847
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
3biah626:30602489
89544117:30613380
a9j8j154:30646983
showlangstatbar:30737416
03d35959:30757346
pythonfmttext:30731395
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
pythonnosmt12:30797651
pythonidxpt:30866567
pythonnoceb:30805159
copilotsettingt:30859503
dsvsc013:30795093
dsvsc014:30804076
dsvsc015:30845448
pythontestfixt:30871694
pythonregdiag2:30871582
pyreplss1:30865275
h48ei257:30870396
pythontbext0:30864172

```

</details>

**Comment by gjsjohnmurray** [comment]
Have you already worked through the information at https://code.visualstudio.com/docs/languages/python?

**Comment by 290qthfsgghredv** [comment]
> Have you already worked through the information at https://code.visualstudio.com/docs/languages/python?

Hi, I already know how to trigger this bug:
1. Create several new workspaces and set a Python interpreter version for them
2. Uninstall this version of Python
3. Create a new workspace without closing those workspaces
4. At this point, switch to the Python interpreter version and a bug will appear
Phenomena:
Unable to switch Python interpreter version, no error message, and nothing happened
How to avoid it?
Simply close the previously uninstalled Python workspaces and manually force them to tamper with their Python workspace path
Is this a bug? Perhaps, but it did drive me crazy, fortunately it has already been resolved.
