### ISSUE TITLE
Improvement: Applying an extension to all Profiles does not sync properly between machines

### ISSUE THREAD

**Issue by thernstig** [microsoft/vscode#196718]
## Problem

For reference: https://code.visualstudio.com/docs/editor/profiles#_applying-an-extension-to-all-profiles

I have found some peculiar things with the implementation, which I am not sure is by design or not. But here comes one:

I am using two computers, one private and one at work. I use Settings Sync for this, to sync settings, extensions etc. I wanted to start to use Profiles as well, which would also be synced between computers.

I setup the `Default` and then a `Web Profile` on the private computer. I made sure to right click and select `Apply Extension to all Profiles` to all extensions I wanted on all profiles, such as the [Kubernetes](https://marketplace.visualstudio.com/items?itemName=ms-kubernetes-tools.vscode-kubernetes-tools) extension. Others I removed from the `Default Profile` by uninstalling them, and then went into the `Web Profile` and installed them. So in essence my **Default Profile** contained no extensions, and my **Web Profile** contained web specific extensions. But both profiles in addition contained the ones enabled via `Apply Extension to all Profiles`.

When I later went to the work computer, it synced the Profiles. After the sync I expected that:

- When in the `Default` profile, only those extensions selected via `Apply Extension to all Profiles` would be installed both locally and remotely (and that the extension will run locally/remotely depending on which extension host it prefers to run)
- When in the `Web Profile`, I expected the the extensions selected via `Apply Extension to all Profiles` **as well as the** additional extension in the `Web Profile` to be installed and enabled.

Now I am not sure how the solution would work. I would maybe not really expect extensions to be uninstalled. But I would at least expect them to be enabled or disabled depending on the selected Profile. In reality I even expected that extensions would be uninstalled that were not part of any of the Profiles nor the `Apply Extension to all Profiles`. Rationale being that with Settings Sync and Profiles, the "extensions" is part of the sync. I mean, if I uninstalled an extension one one computer and it was not part of any Profile, I would probably not want it on any other computers?

Or they should as mentioned only be disabled/enabled depending on the Profile, and not uninstalled.

## Additional context

The rationale behind this is that some extensions, when installed, also require underlying parts in the OS to be installed. For example to Go extension throws a fault in case some Go-specific things are not installed. So when I move between Profiles, I do not wish the Go extension to be enabled anymore when using my `Web Profile`.

The fault shown by the Go extension is a notification with:
> The "gopls" command is not available. Run "go get -v golang.org/x/tools/gopls" to install.

**Comment by thernstig** [comment]
@sandy081 is there a chance you could confirm/deny if this is a sane improvement?

When checking around for people who have tried the "Profiles" feature, it is missing a few things to make it really workeable.

For this issue I think, after having contemplated it, the solution would be to **disable** extensions not part of a profile.

There are few issue for the Profile solution that is lacking in the DX apartment that I personally believe are needed to make it useable in a way I _guess_ it was intended:

https://github.com/microsoft/vscode/issues/196718 (this issue here: It seems quite important considering unwanted extensions do not disable when moving between machines?)
https://github.com/microsoft/vscode/issues/196351 (bug affecting DX)
https://github.com/microsoft/vscode/issues/188612 (very important issue in regards to settings and profiles)

It is almost like there should be a meta issue capturing all these to really put Profiles into a good shape.

**Comment by sandy081** [comment]
@thernstig Apologies that this issue went out of my radar. After going through the description, it was not clear to me what is not working for you? I believe the feature should work as you expected. If not, can you please explain the behaviour you are seeing now.

**Comment by thernstig** [comment]
@sandy081 I will try to re-phrase here with fewer words to see if it is understandable.

I have settings sync turned on. I have a computer A and a computer B. (If it has any bearing: on both computers I exclusively work on ssh remotes (but not against the same ssh remotes.))

On computer A) I add a `Default` and `Web Profile`. On this computer, for some extensions I select `Apply Extension to all Profiles`, for some others I do not. I also _uninstall_ the rest of the extensions where I did not select `Apply Extension to all Profiles`. I go into the `Web Profile` and install the same extensions I uninstalled from the `Default` profile.

I open up computer B. It syncs.

Questions about the sync:
- I can see that when I open the `Web Profile` it still has all extensions installed and enabled. I.e. the ones I uninstalled from computer A from when inside the `Default` profile. Is this expected?

General question about how profiles is supposed to behave:
What is actually supposed to happen in general here? Since we have a  `Apply Extension to all Profiles` for only some extensions, I would suspect that by default those extensions would be disabled completely in all other profiles. Is that not true? Do I need to uninstall **or** disable them in the non-default profiles?

**Comment by thernstig** [comment]
@sandy081 ?

**Comment by sandy081** [comment]
Settings Sync does not sync extensions on the remote, it installs only on the client. Can you please check if you see the same behaviour when syncing between two machines where remote is not involved?

**Comment by thernstig** [comment]
@sandy081 It works when a remote is not involved.

Is syncing extensions on the remote not something that should be fixed or at least documented? The entire extension host system is built around smartly running on the local or remote extension host, many users do not even discover/know this. Then we have this functionality where people then think they are doing something that do not work, and have no idea why.

Many of us solely work on remotes. Remote ssh, wsl, tunnels or even github codespaces.

Can this be fixed?

**Comment by sandy081** [comment]
May I know how you are installing extensions on the remote? Are they getting auto installed?

**Comment by sandy081** [comment]
> Many of us solely work on remotes. Remote ssh, wsl, tunnels or even github codespaces.
Can this be fixed?

We do not sync extensions automatically to remotes because that every remote is not same. Some remotes like dev containers or codespaces contain only workspace related extensions and syncing all user extensions is not expected. Hence, we let the remote extension to choose to automatically install client extensions on the server.

Related - https://github.com/microsoft/vscode/issues/90968

**Comment by thernstig** [comment]
@sandy081 the problem I have with closing both https://github.com/microsoft/vscode/issues/90968 is that there is no issue to tackle this in any sense. As mentioned, it is not even documented how extensions on remotes are not synced, and the profiles description completely misses explaining that profiles **cannot be used properly** if using remote extensions.

It feels like a very important, missing functionality in the implementation that makes much of the profiles useless in this scenario.

https://code.visualstudio.com/docs/editor/profiles even starts by stating:
> Visual Studio Code has hundreds of [settings](https://code.visualstudio.com/docs/getstarted/settings), thousands of [extensions](https://code.visualstudio.com/docs/editor/extension-marketplace), and innumerable ways to adjust the UI layout to customize the editor. VS Code Profiles let you create sets of customizations and quickly switch between them or share them with others. This topic explains how to create, modify, export, and import profiles.

This is not true for many, many people working on remotes.

There should be an issue to tackle this syncing issue, but it seems you are closing all issues.

**Comment by sandy081** [comment]
https://github.com/microsoft/vscode/issues/90968 is the main issue to track this. It is at present closed because we do not have plans to address it. Please check this comment - https://github.com/microsoft/vscode/issues/90968#issuecomment-1346317684. 

I believe most of the remote extensions provide a way to sync local extensions. For example remote ssh provides a setting to configure default extensions that should installed automatically on all SSH hosts.

**Comment by thernstig** [comment]
@sandy081 then should this not be explicitly documented in the ingress of https://code.visualstudio.com/docs/editor/profiles?

That comment referenced specifically mentions:
> If you disagree and feel that this issue is crucial: we are happy to listen and to reconsider.

There are +30 upvotes of the issue. This thread was created. Can it be reopened?

**Comment by sandy081** [comment]
> then should this not be explicitly documented 

Good point. Will do - https://github.com/microsoft/vscode-docs/issues/7221

> Can it be reopened?

It was not reopened because we do not have plans yet to consider it. Sorry about it.
