### ISSUE TITLE
IChatAccessibilityService isn't session aware

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#196735]
The IChatAccessibilityService has `acceptRequest` and `acceptResponse`. The former starts a long running operation, latter cancels _any_ of the operation. That means making two long-running queries in parallel (panel chat & inline chat or inline chat in two side by side editor) cancel each other out, e.g the first to finish cancels the audio for the second. 

Instead `acceptRequest` should return something that the caller needs to hold on to and call stop/response on.

**Comment by jrieken** [comment]
re https://github.com/microsoft/vscode/issues/194424

**Comment by jrieken** [comment]
I see how  `acceptResponse` now accepts a requestId but there is no validation, e.g calling it with any number or repeatedly will cancel the next audio cue. Maybe we are on different pages here but when doing two requests in parallel we should hear "chatResponsePending" twice and "chatResponseReceived" twice, right?

**Comment by meganrogge** [comment]
How does one trigger two requests in parallel?

**Comment by jrieken** [comment]
be quick and (1) open panel chat, ask a question, (2) open inline chat, ask a question. Or do two inline chat with side bar side editor or have mutiple chat editors
