### ISSUE TITLE
No way for viewpane content to know when it has become visible after showing welcome view

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#196777]
- My chat viewpane is rendered
- The welcome views are shown and my content is hidden
- The welcome views are hidden and my content is shown again
  - I don't see any way to know when my content has become visible. At this point chat needs to rerender the chat list and I need to do that when the content is visible in the DOM so that I can measure my chat rows correctly.

Is there a way to do this that I'm missing? `onDidChangeBodyVisibility` is never fired when the welcome view state changes. I might expect that to be false when the welcome view is up.

We did https://github.com/microsoft/vscode/pull/196742 to work around the fact that our list rows were all measured at 0px but this change isn't quite right.

Sorry I'm not sure who owns this but I see you guys have both worked on it

**Comment by sandy081** [comment]
> The welcome views are shown and my content is hidden
The welcome views are hidden and my content is shown again

I do not think this is controlled by the view pane because a view can have both welcome content and also view content. A view pane body comprises both. It is up to the view to control what should be rendered. Probably, you should be knowing when your welcome content and your content is being rendered.

**Comment by roblourens** [comment]
Sorry, I don't follow. From what I see, the viewpane superclass controls the visibility of the body content and the welcome view content. My ChatViewPane subclass doesn't know anything about it. Are you suggesting that I should implement it differently and not subclass ViewPane at all?

**Comment by sandy081** [comment]
Visibility of the body is nothing to do with the welcome content or your view content. It is visible whenever view is expanded and hidden when it is collapsed. It is not clear to me what you are looking for. Probably lets sync directly.

**Comment by roblourens** [comment]
> Visibility of the body is nothing to do with the welcome content or your view content. 

Right, but that's the problem. I need to know when the view content is _actually_ visible in the DOM so that my list with dynamicly sized elements can be properly layed out. I can't measure DOM elements when the view content is display=none. Feel free to call or schedule a meeting any time. I am also +2 hours for the next couple weeks so earlier is fine with me.

**Comment by sandy081** [comment]
> I need to know when the view content is actually visible in the DOM

ViewPane does not know about it. Implementor of ViewPane should. Will ping you.

**Comment by roblourens** [comment]
Specifically I think it's the `ViewWelcomeController` that knows? But I must be misunderstanding something

**Comment by joaomoreno** [comment]
@roblourens View panes are responsible for defining when welcome views are shown and for firing an event for whenever that definition changes. Here's the interface: https://github.com/microsoft/vscode/blob/a87d034b0d6c4f2e7c6352ec6448d5cfae8a1130/src/vs/workbench/browser/parts/views/viewPane.ts#L91-L95

**Comment by roblourens** [comment]
Ok, I realized that in my particular case, I can know that my content will become visible because of how `shouldShowWelcome` is defined for chat, so I should fire the event. https://github.com/microsoft/vscode/pull/198147 I'm not blocked BUT I still think the issue is valid.

That method only says whether a welcome view CAN be shown, my view pane still doesn't know whether a welcome view IS CURRENTLY being shown, that depends on whether there are welcome views registered and what their 'when' clauses are. I could return true from `shouldShowWelcome` but have my content suddenly become visible at some random point. https://github.com/microsoft/vscode/blob/eeaa4cca3850c615b870d13500092ed0785b0fc1/src/vs/workbench/browser/parts/views/viewPane.ts#L220-L226
