### ISSUE TITLE
Aux window: closing a last group in a window should close the window

### ISSUE THREAD

**Issue by rzhao271** [microsoft/vscode#196774]
On the latest Insiders on Windows, when I click on the close button for an empty aux window, it doesn't close.

![Close button next to the floating empty aux window](https://github.com/microsoft/vscode/assets/7199958/3c5dd46a-6335-4e2c-8506-4c1f75b49823)

**Comment by rzhao271** [comment]
I just noticed that even for the main group, it closes all the editors but leaves the window open.
The title of the icon is "Close Group". Should it be "Close all editors in group" instead?

**Comment by bpasero** [comment]
@rzhao271 you click the "Close Group" button you mean?

<img width="125" alt="image" src="https://github.com/microsoft/vscode/assets/900690/258ff708-098e-40bc-8831-1c7d7b94de66">

**Comment by rzhao271** [comment]
Yes

**Comment by bpasero** [comment]
**Verification:**
* ensure `workbench.editor.closeEmptyGroups: true`
* open a floating window, e.g. by dragging an editor tab out
* open more editor groups inside the floating window and open editors
* verify editor groups close when the last editor closes within
* verify the floating window closes when the last editor in the last group closes
