### ISSUE TITLE
Sound distorted when recording is starting

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#196700]
1. Have some music playing (e.g Spotify)
2. Click on our "Use Microphone" button
3. My music and the whole sound gets distorted

Probably an upstream issue, and we discussed but still wanted to have an issue to track this. Since it is a pain when I try to use voice.

**Comment by isidorn** [comment]
Yes I can. When I go to the Settings > Audio > Input. The same sound distortion happens...

**Comment by bpasero** [comment]
I see nothing we can do here. According to some research and asking folks at Azure Speech SDK, it could be the OS is switching Bluetooth profiles between `A2DP` for high fidelity audio streaming and `HFP` which has a lower supported bandwidth for playback.
