### ISSUE TITLE
Extend new `Tab Bar` menu to include a `Wrapped Tabs` option

### ISSUE THREAD

**Issue by gjsjohnmurray** [microsoft/vscode#196730]
This would set `"workbench.editor.showTabs": "multiple"` and `"workbench.editor.wrapTabs": true`

For consistency the existing `Multiple Tabs` option would set `"workbench.editor.showTabs": "multiple"` and `"workbench.editor.wrapTabs": false`

Doing this would increase the visibility of the tab-wrapping feature.

**Comment by gjsjohnmurray** [comment]
As an alternative to having some of the menu options affect two settings, the existing `workbench.editor.wrapTabs` boolean could be migrated to a new value of the new setting, e.g. `"workbench.editor.showTabs": "wrapped"`

**Comment by gjsjohnmurray** [comment]
I still think the tab wrapping feature deserves greater visibility.

Related, info at https://code.visualstudio.com/docs/getstarted/userinterface#_tabs still treats the showTabs setting as a boolean.

**Comment by benibenj** [comment]
Closing as not planning to add wrap tab options to Tab Bar Submenu.

Thanks for letting me about the docs being out of date, changed it
