### ISSUE TITLE
Settings sync appears as first walkthrough step on fresh install

### ISSUE THREAD

**Issue by daviddossett** [microsoft/vscode#196773]
I noticed this:

![Image](https://github.com/microsoft/vscode/assets/25163139/6a78f41c-24bf-4b07-8bfc-0dcdcbb2f0b4)

I was surprised to see that I was landed on the second step of the walkthrough, and that settings sync was listed first.

**Comment by daviddossett** [comment]
It sounds like the step ordering change was intentional, but this behavior of skipping step 1 is possibly a bug. @bhavyaus can confirm.

**Comment by sandy081** [comment]
I just noticed that the welcome page is jumping to the second step and settings sync step is not shown. IMO this is worse than before as it will reduce the number of people going to settings sync step. Hence tagging this as candidate.

**Comment by sandy081** [comment]
I can reproduce it consistently. Here are steps:

- Open VS Code Insiders using fresh user data dir and extensions dir
🐛 Welcome page jumps to themes

https://github.com/microsoft/vscode/assets/10746682/e1f1f3f4-aa94-4131-8503-cff95596e531

**Comment by chrmarti** [comment]
Verified in 1.84.2 release candidate.

**Comment by StefanXhunga** [comment]
Thank you for your support
