### ISSUE TITLE
Toggle Inline Chat Icon gutter item appears when inline chat isn't available

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode#196776]
1. Open a repo in insiders.vscode.dev
2. Right click on the gutter 
3. :bug: Toggle Inline Chat Icon is present in the context menu

**Comment by gjsjohnmurray** [comment]
Also #196739

**Comment by aiday-mar** [comment]
Good catch thanks

**Comment by aiday-mar** [comment]
The fix is not in the october stable release
