### ISSUE TITLE
Interactive playground shows ESLint errors

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#19671]
- VSCode Version: 1.9
- OS Version: Windows

Steps to Reproduce:

1. Have ESLint install and configured on a workspace
2. Open the interactive playground

Observe: the playground shows ESLint errors which might be quite confusing.
![capture](https://cloud.githubusercontent.com/assets/1931590/22511473/1866fa88-e896-11e6-854a-c421d4437296.png)

**Comment by chrmarti** [comment]
Tracking with #19171
