### ISSUE TITLE
Terminal textbox cursor is not in correct position when unfocusing and focusing again

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#196758]
Repro:

1. Windows (maybe not needed?)
2. Set `"terminal.integrated.developer.devMode": true`
3. Open terminal
4. Write some text, note the cursor location
5. Focus an editor
6. Focus the terminal, 🐛 the cursor is at the start of the textbox

![image](https://github.com/microsoft/vscode/assets/2193314/8961209c-2da5-4718-85ce-749e302e9af5)

**Comment by meganrogge** [comment]
Works on mac

**Comment by meganrogge** [comment]
It also works for me on Windows

**Comment by Tyriar** [comment]
I think the repro is fill the viewport such that there's a scroll bar, then type

**Comment by Tyriar** [comment]
Ctrl+c helps make it happen too

**Comment by Tyriar** [comment]
Some other repros too:

![image](https://github.com/microsoft/vscode/assets/2193314/d628bb71-320a-43a8-a949-909ddc8c1ed1)
![image](https://github.com/microsoft/vscode/assets/2193314/ef9b5c0e-5f21-4036-9738-d3f02b8306a7)
![image](https://github.com/microsoft/vscode/assets/2193314/051d984d-1630-43d7-b36b-1eeb99273de1)

**Comment by Tyriar** [comment]
I'm hitting this:

```
CommandDetectionCapability#_handleCommandStartWindows reached max attempts,  [true,null]
```

Looking into it
