### ISSUE TITLE
VSCode Settings Sync not activating extensions

### ISSUE THREAD

**Issue by colonelclaypoo** [microsoft/vscode#196793]
- VS Code Version: 1.83.1
- OS Version: Win 10 22H2

Steps to Reproduce:

1. Settings Sync automatically and successfully syncs lastSyncextensions.json. Across devices It's found in C:\Users\[USER]\AppData\Roaming\Code\User\sync\extensions

2. VSCode does not activate those extensions, they don't show up in the corresponding menu pane. It seems as if VSCode does not interpret the file correctly.

3. Here's the lastSyncextensions.json content:

`{"ref":"1bdfaf3f-51d4-47be-bc14-d504ed448143","syncData":{"version":6,"machineId":"f244711c-ce6d-438c-866f-ad923b1e0f47","content":"[{\"identifier\":{\"id\":\"vscode.bat\"},\"version\":\"1.0.0\",\"preRelease\":false,\"pinned\":false},{\"identifier\":{\"id\":\"vscode.clojure\"},\"version\":\"1.0.0\",\"preRelease\":false,\"pinned\":false},{\"identifier\":{\"id\":\"vscode.coffeescript\"},\"version\":\"1.0.0\",\"preRelease\":false,\"pinned\":false},{\"identifier\":{\"id\":\"vscode.configuration-editing\"},\"version\":\"1.0.0\",\"preRelease\":false,\"pinned\":false},{\"identifier\":{\"id\":\"vscode.cpp\"},\"version\":\"1.0.0\",\"preRelease\":false,\"pinned\":false},{\"identifier\":{\"id\":\"vscode.csharp\"},\"version\":\"1.0.0\",\"preRelease\":false,\"pinned\":false},{\"identifier\":{\"id\":\"vscode.css\"},\"version\":\"1.0.0\",\"preRelease\":false,\"pinned\":false},{\"identifier\":{\"id\":\"vscode.css-language-features\"},\"version\":\"1.0.0\",\"preRelease\":false,\"pinned\":false},{\"identifier\":{\"id\":\"vscode.dart\"},\"version\":\"1.0.0\",\"preRelease\":false,\"pinned\":false},{\"identifier\":{\"id\":\"vscode.debug-auto-launch\"},\"version\":\"1.0.0\",\"preRelease\":false,\"pinned\":false},{\"identifier\":{\"id\":\"vscode.debug-server-ready\"},\"version\":\"1.0.0\",\"preRelease\":false,\"pinned\":false},{\"identifier\":{\"id\":\"vscode.diff\"},\"version\":\"1.0.0\",\"preRelease\":false,\"pinned\":false},{\"identifier\":{\"id\":\"vscode.docker\"},\"version\":\"1.0.0\",\"preRelease\":false,\"pinned\":false},{\"identifier\":{\"id\":\"vscode.emmet\"},\"version\":\"1.0.0\",\"preRelease\":false,\"pinned\":false},{\"identifier\":{\"id\":\"vscode.extension-editing\"},\"version\":\"1.0.0\",\"preRelease\":false,\"pinned\":false},{\"identifier\":{\"id\":\"vscode.fsharp\"},\"version\":\"1.0.0\",\"preRelease\":false,\"pinned\":false},{\"identifier\":{\"id\":\"vscode.git\"},\"version\":\"1.0.0\",\"preRelease\":false,\"pinned\":false},{\"identifier\":{\"id\":\"vscode.git-base\"},\"version\":\"1.0.0\",\"preRelease\":false,\"pinned\":false},{\"identifier\":{\"id\":\"vscode.github\"},\"version\":\"0.0.1\",\"preRelease\":false,\"pinned\":false},{\"identifier\":{\"id\":\"vscode.github-authentication\"},\"version\":\"0.0.2\",\"preRelease\":false,\"pinned\":false},{\"identifier\":{\"id\":\"vscode.go\"},\"version\":\"1.0.0\",\"preRelease\":false,\"pinned\":false},{\"identifier\":{\"id\":\"vscode.groovy\"},\"version\":\"1.0.0\",\"preRelease\":false,\"pinned\":false},{\"identifier\":{\"id\":\"vscode.grunt\"},\"version\":\"1.0.0\",\"preRelease\":false,\"pinned\":false},{\"identifier\":{\"id\":\"vscode.gulp\"},\"version\":\"1.0.0\",\"preRelease\":false,\"pinned\":false},{\"identifier\":{\"id\":\"vscode.handlebars\"},\"version\":\"1.0.0\",\"preRelease\":false,\"pinned\":false},{\"identifier\":{\"id\":\"vscode.hlsl\"},\"version\":\"1.0.0\",\"preRelease\":false,\"pinned\":false},{\"identifier\":{\"id\":\"vscode.html\"},\"version\":\"1.0.0\",\"preRelease\":false,\"pinned\":false},{\"identifier\":{\"id\":\"vscode.html-language-features\"},\"version\":\"1.0.0\",\"preRelease\":false,\"pinned\":false},{\"identifier\":{\"id\":\"vscode.image-preview\"},\"version\":\"1.0.0\",\"preRelease\":false,\"pinned\":false},{\"identifier\":{\"id\":\"vscode.ini\"},\"version\":\"1.0.0\",\"preRelease\":false,\"pinned\":false},{\"identifier\":{\"id\":\"vscode.ipynb\"},\"version\":\"1.0.0\",\"preRelease\":false,\"pinned\":false},{\"identifier\":{\"id\":\"vscode.jake\"},\"version\":\"1.0.0\",\"preRelease\":false,\"pinned\":false},{\"identifier\":{\"id\":\"vscode.java\"},\"version\":\"1.0.0\",\"preRelease\":false,\"pinned\":false},{\"identifier\":{\"id\":\"vscode.javascript\"},\"version\":\"1.0.0\",\"preRelease\":false,\"pinned\":false},{\"identifier\":{\"id\":\"vscode.json\"},\"version\":\"1.0.0\",\"preRelease\":false,\"pinned\":false},{\"identifier\":{\"id\":\"vscode.json-language-features\"},\"version\":\"1.0.0\",\"preRelease\":false,\"pinned\":false},{\"identifier\":{\"id\":\"vscode.julia\"},\"version\":\"1.0.0\",\"preRelease\":false,\"pinned\":false},{\"identifier\":{\"id\":\"vscode.latex\"},\"version\":\"1.0.0\",\"preRelease\":false,\"pinned\":false},{\"identifier\":{\"id\":\"vscode.less\"},\"version\":\"1.0.0\",\"preRelease\":false,\"pinned\":false},{\"identifier\":{\"id\":\"vscode.log\"},\"version\":\"1.0.0\",\"preRelease\":false,\"pinned\":false},{\"identifier\":{\"id\":\"vscode.lua\"},\"version\":\"1.0.0\",\"preRelease\":false,\"pinned\":false},{\"identifier\":{\"id\":\"vscode.make\"},\"version\":\"1.0.0\",\"preRelease\":false,\"pinned\":false},{\"identifier\":{\"id\":\"vscode.markdown\"},\"version\":\"1.0.0\",\"preRelease\":false,\"pinned\":false},{\"identifier\":{\"id\":\"vscode.markdown-language-features\"},\"version\":\"1.0.0\",\"preRelease\":false,\"pinned\":false},{\"identifier\":{\"id\":\"vscode.markdown-math\"},\"version\":\"1.0.0\",\"preRelease\":false,\"pinned\":false},{\"identifier\":{\"id\":\"vscode.merge-conflict\"},\"version\":\"1.0.0\",\"preRelease\":false,\"pinned\":false},{\"identifier\":{\"id\":\"vscode.microsoft-authentication\"},\"version\":\"0.0.1\",\"preRelease\":false,\"pinned\":false},{\"identifier\":{\"id\":\"ms-vscode.js-debug\",\"uuid\":\"25629058-ddac-4e17-abba-74678e126c5d\"},\"version\":\"1.71.1\",\"preRelease\":false,\"pinned\":false},{\"identifier\":{\"id\":\"ms-vscode.js-debug-companion\",\"uuid\":\"99cb0b7f-7354-4278-b8da-6cc79972169d\"},\"version\":\"1.0.18\",\"preRelease\":false,\"pinned\":false},{\"identifier\":{\"id\":\"ms-vscode.vscode-js-profile-table\",\"uuid\":\"7e52b41b-71ad-457b-ab7e-0620f1fc4feb\"},\"version\":\"1.0.3\",\"preRelease\":false,\"pinned\":false},{\"identifier\":{\"id\":\"vscode.builtin-notebook-renderers\"},\"version\":\"1.0.0\",\"preRelease\":false,\"pinned\":false},{\"identifier\":{\"id\":\"vscode.npm\"},\"version\":\"1.0.1\",\"preRelease\":false,\"pinned\":false},{\"identifier\":{\"id\":\"vscode.objective-c\"},\"version\":\"1.0.0\",\"preRelease\":false,\"pinned\":false},{\"identifier\":{\"id\":\"vscode.perl\"},\"version\":\"1.0.0\",\"preRelease\":false,\"pinned\":false},{\"identifier\":{\"id\":\"vscode.php\"},\"version\":\"1.0.0\",\"preRelease\":false,\"pinned\":false},{\"identifier\":{\"id\":\"vscode.php-language-features\"},\"version\":\"1.0.0\",\"preRelease\":false,\"pinned\":false},{\"identifier\":{\"id\":\"vscode.powershell\"},\"version\":\"1.0.0\",\"preRelease\":false,\"pinned\":false},{\"identifier\":{\"id\":\"vscode.pug\"},\"version\":\"1.0.0\",\"preRelease\":false,\"pinned\":false},{\"identifier\":{\"id\":\"vscode.python\"},\"version\":\"1.0.0\",\"preRelease\":false,\"pinned\":false},{\"identifier\":{\"id\":\"vscode.r\"},\"version\":\"1.0.0\",\"preRelease\":false,\"pinned\":false},{\"identifier\":{\"id\":\"vscode.razor\"},\"version\":\"1.0.0\",\"preRelease\":false,\"pinned\":false},{\"identifier\":{\"id\":\"vscode.references-view\"},\"version\":\"1.0.0\",\"preRelease\":false,\"pinned\":false},{\"identifier\":{\"id\":\"vscode.restructuredtext\"},\"version\":\"1.0.0\",\"preRelease\":false,\"pinned\":false},{\"identifier\":{\"id\":\"vscode.ruby\"},\"version\":\"1.0.0\",\"preRelease\":false,\"pinned\":false},{\"identifier\":{\"id\":\"vscode.rust\"},\"version\":\"1.0.0\",\"preRelease\":false,\"pinned\":false},{\"identifier\":{\"id\":\"vscode.scss\"},\"version\":\"1.0.0\",\"preRelease\":false,\"pinned\":false},{\"identifier\":{\"id\":\"vscode.search-result\"},\"version\":\"1.0.0\",\"preRelease\":false,\"pinned\":false},{\"identifier\":{\"id\":\"vscode.shaderlab\"},\"version\":\"1.0.0\",\"preRelease\":false,\"pinned\":false},{\"identifier\":{\"id\":\"vscode.shellscript\"},\"version\":\"1.0.0\",\"preRelease\":false,\"pinned\":false},{\"identifier\":{\"id\":\"vscode.simple-browser\"},\"version\":\"1.0.0\",\"preRelease\":false,\"pinned\":false},{\"identifier\":{\"id\":\"vscode.sql\"},\"version\":\"1.0.0\",\"preRelease\":false,\"pinned\":false},{\"identifier\":{\"id\":\"vscode.swift\"},\"version\":\"1.0.0\",\"preRelease\":false,\"pinned\":false},{\"identifier\":{\"id\":\"vscode.theme-abyss\"},\"version\":\"1.0.0\",\"preRelease\":false,\"pinned\":false},{\"identifier\":{\"id\":\"vscode.theme-defaults\"},\"version\":\"1.0.0\",\"preRelease\":false,\"pinned\":false},{\"identifier\":{\"id\":\"vscode.theme-kimbie-dark\"},\"version\":\"1.0.0\",\"preRelease\":false,\"pinned\":false},{\"identifier\":{\"id\":\"vscode.theme-monokai\"},\"version\":\"1.0.0\",\"preRelease\":false,\"pinned\":false},{\"identifier\":{\"id\":\"vscode.theme-monokai-dimmed\"},\"version\":\"1.0.0\",\"preRelease\":false,\"pinned\":false},{\"identifier\":{\"id\":\"vscode.theme-quietlight\"},\"version\":\"1.0.0\",\"preRelease\":false,\"pinned\":false},{\"identifier\":{\"id\":\"vscode.theme-red\"},\"version\":\"1.0.0\",\"preRelease\":false,\"pinned\":false},{\"identifier\":{\"id\":\"vscode.vscode-theme-seti\"},\"version\":\"1.0.0\",\"preRelease\":false,\"pinned\":false},{\"identifier\":{\"id\":\"vscode.theme-solarized-dark\"},\"version\":\"1.0.0\",\"preRelease\":false,\"pinned\":false},{\"identifier\":{\"id\":\"vscode.theme-solarized-light\"},\"version\":\"1.0.0\",\"preRelease\":false,\"pinned\":false},{\"identifier\":{\"id\":\"vscode.theme-tomorrow-night-blue\"},\"version\":\"1.0.0\",\"preRelease\":false,\"pinned\":false},{\"identifier\":{\"id\":\"vscode.typescript\"},\"version\":\"1.0.0\",\"preRelease\":false,\"pinned\":false},{\"identifier\":{\"id\":\"vscode.typescript-language-features\"},\"version\":\"1.0.0\",\"preRelease\":false,\"pinned\":false},{\"identifier\":{\"id\":\"vscode.vb\"},\"version\":\"1.0.0\",\"preRelease\":false,\"pinned\":false},{\"identifier\":{\"id\":\"vscode.xml\"},\"version\":\"1.0.0\",\"preRelease\":false,\"pinned\":false},{\"identifier\":{\"id\":\"vscode.yaml\"},\"version\":\"1.0.0\",\"preRelease\":false,\"pinned\":false},{\"identifier\":{\"id\":\"ms-vscode-remote.remote-wsl-recommender\",\"uuid\":\"cb296d3c-017a-4dee-83af-ebb5a5a16e9a\"},\"version\":\"0.0.16\",\"preRelease\":false,\"pinned\":false},{\"identifier\":{\"id\":\"vscode.media-preview\"},\"version\":\"1.0.0\",\"preRelease\":false,\"pinned\":false},{\"identifier\":{\"id\":\"vscode.tunnel-forwarding\"},\"preRelease\":false,\"version\":\"1.0.0\",\"pinned\":false},{\"identifier\":{\"id\":\"github.vscode-pull-request-github\",\"uuid\":\"69ddd764-339a-4ecc-97c1-9c4ece58e36d\"},\"preRelease\":false,\"version\":\"0.74.1\",\"pinned\":false,\"installed\":true},{\"identifier\":{\"id\":\"ms-vscode.powershell\",\"uuid\":\"40d39ce9-c381-47a0-80c8-a6661f731eab\"},\"preRelease\":false,\"version\":\"2023.8.0\",\"pinned\":false,\"installed\":true}]"}}`

4. This is also a different syntax compared to the file named C:\Users\[USER]\.vscode\extensions\extensions.json which is in JSON format.

5. Log output for the sync action is:
2023-10-27 09:09:22.118 [info] Auto Sync: Triggered by Activity
2023-10-27 09:09:22.118 [info] Sync started.
2023-10-27 09:09:22.173 [info] Settings: No changes found during synchronizing settings.
2023-10-27 09:09:22.177 [info] Keybindings: No changes found during synchronizing keybindings.
2023-10-27 09:09:22.182 [info] Snippets: No changes found during synchronizing snippets.
2023-10-27 09:09:22.184 [info] Tasks: No changes found during synchronizing tasks.
2023-10-27 09:09:22.187 [info] GlobalState: No changes found during synchronizing ui state.
2023-10-27 09:09:22.233 [info] Extensions: No changes found during synchronizing extensions.
2023-10-27 09:09:22.235 [info] Profiles: No changes found during synchronizing profiles.
2023-10-27 09:09:22.236 [info] Sync done. Took 119ms
2023-10-27 09:09:35.941 [info] Auto Sync: Triggered by Activity
2023-10-27 09:09:35.942 [info] Sync started.
2023-10-27 09:09:36.006 [info] Settings: No changes found during synchronizing settings.
2023-10-27 09:09:36.010 [info] Keybindings: No changes found during synchronizing keybindings.
2023-10-27 09:09:36.015 [info] Snippets: No changes found during synchronizing snippets.
2023-10-27 09:09:36.018 [info] Tasks: No changes found during synchronizing tasks.
2023-10-27 09:09:36.024 [info] GlobalState: No changes found during synchronizing ui state.
2023-10-27 09:09:36.239 [info] Extensions: No changes found during synchronizing extensions.
2023-10-27 09:09:36.240 [info] Profiles: No changes found during synchronizing profiles.
2023-10-27 09:09:36.242 [info] Sync done. Took 303ms

**Comment by sandy081** [comment]
`lastSyncExtensions.json` is an implementation detail of settings sync. This is used as base version while merging. I do not understand why you are looking into this file and want this to be similar with `extensions.json` file. These are two different files. Can you please explain what is your use case or the bug you are seeing?

**Comment by sandy081** [comment]
> I was under the assumption that the contents of lastSyncExtensions.json is what VS Code uses to install/load extensions since this is the file being synced across devices. Same goes for lastSynckeybindings.json or lastSyncsettings.json. Both of those contents are correctly interpreted by VS Code.

This is not correct. As mentioned in my previous comment, this is the last sync version of that resource which is used for merging the resource while syncing.  

> So basically my question is why are extensions synced but not installed whereas settings, keybindigs etc. are correctly used in VS Code and up to date.

When extensions are synced they should be installed. Can you please provide the scenario where this is not happening for you?

**Comment by colonelclaypoo** [comment]
Alright. So it works if I add new extensions. They will get installed here:
C:\Users\[USER]\.vscode\extensions
![image](https://github.com/microsoft/vscode/assets/29123261/636e0807-3ef5-4e3e-a7a6-01992f09a54b)
But all the ones listed in the lastSyncExtensions.json are not and they do not exist in the C:\Users\[USER]\.vscode\extensions\extensions.json

Yes, I understand now the lastSyncExtensions.json is not responsible for the installation to ocurr but it does include the references to the extensions I would like to see installed again.

It seems as if the Github gist (or whatever it's called) does not contain the actual information from the "old" extensions. Newly added ones are synched across devices. Is there a way to get the old ones back, mentioned in the lastSyncExtensions.json merge file?

**Comment by colonelclaypoo** [comment]
I have to add:
Previously I mentioned that settings, keybindings etc were synced correctly and are in effect in VS Code. This not not the case after all. Back before I was made aware that the lastSyncExtensions.json etc. do not contain the actual configuration info, I saw that the keyboard shortcuts exist in this file. But taken a closer look shows me that the actual settings and keybindings have not been loaded into VS Code.

So this puts more emphasis on the question: How can I restore settings, keybindings, extensions if I only have the merge sync files?

**Comment by sandy081** [comment]
Are you looking for this - https://code.visualstudio.com/docs/editor/settings-sync#_restoring-data ?

**Comment by colonelclaypoo** [comment]
Thanks, this shows me the local backup okay. After further investigation I've come to the conclusion that none of my machine's local backup files contain the extension settings that I used to have. I believe I must have deleted the cloud files with that tickbox. Anyway, I have a better understanding now, it's not a bug and this ticket is now closed.
