### ISSUE TITLE
Monokai Theme bad-highlighting in  line wrap.

### ISSUE THREAD

**Issue by CaselIT** [Microsoft/vscode#19673]
- VSCode Version: 1.8.1
- OS Version: Win10
- Colour Theme: Monokai

There seem to be a unnecessary _ when a line wraps on a class type. see the img :
![image](https://cloud.githubusercontent.com/assets/16175304/20457311/acc06cb6-ae88-11e6-8412-b7e260374835.png)
Steps to Reproduce:

1. Enable line wrap
2. Make the line wrap on the type definition of a class.

This issue was previously in #14921 @aeschli

**Comment by aeschli** [comment]
Reproduced in 1.9:
```
interface MongoCallback<T> {

}

class A {
    static connect(u: string, callback: MongoCallback<string>): void {
    }
}
```

**Comment by jordanmkasla2009** [comment]
It appears the word wrapping indent is being prepended to the first token of each line that the word wrapping creates. 
Case in point, if one were to shrink the view smaller the wrapping indent is also applied to the _italicized_ variable name which isn't visibly noticeable but still exists

![capture1](https://cloud.githubusercontent.com/assets/1433775/22782088/7f7f12ca-ee93-11e6-8643-3121bb84bca1.PNG)

It should also be noted that the native indent (not the one from the word wrap) is represented in the DOM as its own token. 

![capture2](https://cloud.githubusercontent.com/assets/1433775/22782689/4ffe13cc-ee96-11e6-89ca-8d6638b3e404.PNG)

**Comment by CaselIT** [comment]
Cool, thanks @alexandrudima
