### ISSUE TITLE
Show extension page

### ISSUE THREAD

**Issue by theIDinside** [microsoft/vscode#196831]
It would be nice if the extension could be provided a way to open the "extension page" that is displayed when clicking the extension in the list of extensions. This way, the user could be queried if they want to open this (because, for instance, an extension has introduced breaking changes that they wish to notify the user of, which could be displayed on that front page under a news section in their markdown (README.md)).

**Comment by sandy081** [comment]
VS Code shows the extension read me already on clicking the extension. I am not sure what else you are looking for?

**Comment by theIDinside** [comment]
> VS Code shows the extension read me already on clicking the extension. I am not sure what else you are looking for?

To open for the extension itself to display that page, via som API. So

`extensionContext.showReadme()` (or whatever).

**Comment by theIDinside** [comment]
I suppose, one could just open a text document containing whatever information that is displayed in the extension page. So I will be closing this issue.
