### ISSUE TITLE
Unable to az login

### ISSUE THREAD

**Issue by beenadhami** [microsoft/vscode#196825]
Type: <b>Bug</b>

Hi, I am getting error while trying to login via command az login --tenant (with my tenant id) but getting error :decryption failed: key not valid for use in specified state.

Regards
Beena

VS Code version: Code 1.83.1 (f1b07bd25dfad64b0167beb15359ae573aecd2cc, 2023-10-10T23:48:05.904Z)
OS version: Windows_NT x64 10.0.22000
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz (8 x 2611)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|7.69GB (0.81GB free)|
|Process Argv|--crash-reporter-id 70e5e693-19c2-4337-a510-77329d8b7d2d|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (17)</summary>

Extension|Author (truncated)|Version
---|---|---
codespaces|Git|1.16.2
remotehub|Git|0.62.0
vscode-github-actions|git|0.26.2
vscode-pull-request-github|Git|0.74.1
go|gol|0.39.1
terraform|has|2.28.2
vscode-azurefunctions|ms-|1.13.1
vscode-azureresourcegroups|ms-|0.7.5
vscode-azureterraform|ms-|0.3.2
remote-ssh|ms-|0.106.5
remote-ssh-edit|ms-|0.86.0
azure-account|ms-|0.11.6
azure-repos|ms-|0.38.0
azurecli|ms-|0.5.0
remote-explorer|ms-|0.4.1
remote-repositories|ms-|0.40.0
vsliveshare|ms-|1.0.5883

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
py29gd2263cf:30856253
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
282f8724:30602487
f6dab269:30613381
showlangstatbar:30737416
a2ce3375:30757347
pythonfmttext:30731395
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
pythonnosmt12:30797651
pythonidxpt:30866567
pythonnoceb:30805159
copilotsettingt:30859503
dsvsc013:30795093
dsvsc014:30804076
dsvsc015:30845448
pythontestfixt:30871694
pythonregdiag2:30871582
pyreplss1:30865275
pythontbext0:30864172

```

</details>

**Comment by TylerLeonhardt** [comment]
Hi 👋  this looks like an issue with the Azure CLI. Can you please open an issue there: https://github.com/Azure/azure-cli/issues
