### ISSUE TITLE
Clicking on terminal decoration focus on sidebar

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#196856]
* Run a command in terminal
* Click on the decoration
* The sidebar gets focus ;(

https://github.com/microsoft/vscode/assets/876920/b643945b-15aa-4fec-9a50-50202daff828

**Comment by Tyriar** [comment]
This is a context menu problem, it also reproduces via click on the chat view, right click in the editor

**Comment by sbatten** [comment]
I don't reproduce this (tried windows and macos), please re-open if you still can.
