### ISSUE TITLE
python  3.12.0 

### ISSUE THREAD

**Issue by wpqipw** [microsoft/vscode#196873]

**Comment by wpqipw** [comment]
我表示安装了一个python 3.12.0，vscode不能运行python了。
中国朋友们谁懂啊？

**Comment by Young-Lord** [comment]
非VSCode问题请自行close。你就算在VSCode外运行也一样报错。
个人认为是你的项目内的模块文件夹名字与`tkinter`这个库名字相同导致报错。

Don't send any issue non-related to VSCode here. Close it plz.

**Comment by wpqipw** [comment]
| |
xin_702483
|
|
***@***.***
谢


|
---- Replied Message ----
| From | ***@***.***> |
| Date | 10/28/2023 11:49 |
| To | ***@***.***> |
| Cc | ***@***.***> ,
***@***.***> |
| Subject | Re: [microsoft/vscode] python 3.12.0 (Issue #196873) |

非VSCode问题请自行close。你就算在VSCode外运行也一样报错。
个人认为是你的项目内的模块文件夹名字与tkinter这个库名字相同导致报错。

Don't send any issue non-related to VSCode here. Close it plz.

**Comment by Young-Lord** [comment]
知道问题在哪了：你要把`re.py`重命名为别的什么名字，不然会影响Python内置库。

**Comment by wpqipw** [comment]
但是我好像没有 re.py
我的python自带的turtle：（附件）
| |
xin_702483
|
|
***@***.***
|
---- Replied Message ----
| From | ***@***.***> |
| Date | 10/28/2023 11:59 |
| To | ***@***.***> |
| Cc | ***@***.***> ,
***@***.***> |
| Subject | Re: [microsoft/vscode] python 3.12.0 (Issue #196873) |

知道问题在哪了：你要把re.py重命名为别的什么名字，不然会影响Python内置库。

**Comment by wpqipw** [comment]
idle里是可以正常运行的，可能是py3.12与vscode不协调的问题，
以前3.11是好好的（‘ ……’）


---- Replied Message ----
| From | ***@***.***> |
| Date | 10/28/2023 11:59 |
| To | ***@***.***> |
| Cc | ***@***.***> ,
***@***.***> |
| Subject | Re: [microsoft/vscode] python 3.12.0 (Issue #196873) |

知道问题在哪了：你要把re.py重命名为别的什么名字，不然会影响Python内置库。

**Comment by Young-Lord** [comment]
你报错日志里不是有"g:\re.py"吗？确定IDLE是Python3.12？
以及，要不给我发邮件具体说吧（ly-niko@qq.com）

**Comment by Young-Lord** [comment]
你报错日志里不是有"g:\re.py"吗？
而且，IDLE默认是[不会在文件所在目录](https://stackoverflow.com/questions/15821121/whats-the-working-directory-when-using-idle)查找库的（而VSCode，或者Code Runner，大概率会在当前目录查找），因此会出现IDLE能运行的情况
以及，要不给我发邮件具体说吧（[ly-niko@qq.com](mailto:ly-niko@qq.com)）
以及，建议先close issue

**Comment by xiyaowong** [comment]
无意间看到这个issue，确实让人感到无语，啥问题想都不想就发出来问

**Comment by wpqipw** [comment]
> 类型： Bug
> 
> 回溯（最近一次调用最后一次）：文件“g：\dfg.py”，第 1 行，在 import turtle 中作为 t 文件“D：\Download\c++\py\py\Lib\turtle.py”，第 101 行，在 import tkinter 中作为 TK 文件“D：\Download\c++\py\py\Lib\tkinter__init__.py”，第 41 行，在导入文件“g：\re.py”中，第 2 行，在 导入 tkinter.messagebox 中作为 msg 文件“D：\Download\c++\py\py\Lib\tkinter\messagebox.py“，第 25 行，从 tkinter.commondialog 导入对话框文件”D：\Download\c++\py\py\Lib\tkinter\commondialog.py“，第 13 行，从 tkinter 导入_get_temp_root，_destroy_temp_root ImportError：无法_从部分初始化的模块”tkinter“导入名称”get_temp_root“（很可能是由于循环导入）（D：\Download\c++\py\py\Lib\tkinter__init__.py）
> 
> VS 代码版本：代码 1.83.1 （[f1b07bd](https://github.com/microsoft/vscode/commit/f1b07bd25dfad64b0167beb15359ae573aecd2cc)， 2023-10-10T23：48：05.904Z） 操作系统版本：Windows_NT x64 10.0.19045 模式：
> 
> 系统信息
> 扩展 （10）
> A/B 实验

**Comment by wpqipw** [comment]
> _未提供说明。_

**Comment by wpqipw** [comment]
——
