### ISSUE TITLE
Tunnel connections are timing out

### ISSUE THREAD

**Issue by amunger** [microsoft/vscode#196845]
Found while trying to verify https://github.com/microsoft/vscode/issues/190425

both from the local machine, and a separate windows machine, I am stuck at this point

<img width="994" alt="image" src="https://github.com/microsoft/vscode/assets/2019016/7dbf7948-53e5-4f6a-81e0-1e66f0205353">

**Comment by connor4312** [comment]
Seems like a service issue in dev tunnels, for me it affects all tunnel connections. I pinged in their teams channel.
