### ISSUE TITLE
Only apply codicon font family/size to :before

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#196869]
I was trying to use a Codicon with an `IconLabel`, which normally is only used with the file icon classes. It doesn't really work because of rules 

https://github.com/microsoft/vscode/blob/b93639dfa3d6e86233fa9246ee5e45abf64b7505/src/vs/base/browser/ui/codicons/codicon/codicon.css#L12
and 
https://github.com/microsoft/vscode/blob/b93639dfa3d6e86233fa9246ee5e45abf64b7505/src/vs/workbench/browser/media/style.css#L145

that apply font props to the element and its children. But `IconLabel` wants to be structured like this

```
<div class="codicon ...">
:before <- icon content goes here
<div for name>
<div for description>
</div>
```

And I think I have run into this in the past as well. It seems like it would work the same to scope those font rules to `.codicon:before` like the content rule, instead of `.codicon`, is there any reason not to do that?

**Comment by bpasero** [comment]
I am not sure about the reasoning behind the Codicon CSS rules, maybe David?

**Comment by aeschli** [comment]
I also don't know the history. I agree that some rules could be more specific and use `::before` in the selector. But some rules will remain on the container, such as sizing.

I would rather not make any changes to this. 
- There are (unfortunately) a lot of CSS rules that include `.codicon` in some way, override one or more properties. For each we would have to refactor these as well.
- Instead IconLabel should use a span just for the codicon

No changes planed
