### ISSUE TITLE
Debug console links don't seem to work anymore

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#196844]
Clicking this link doesn't work anymore:

![image](https://github.com/microsoft/vscode/assets/2193314/c677fbe4-1b5b-4054-a974-295e0de5be64)

Here's an error on console:

> 상대 파일 경로 'c:\Github\microsoft\vscode\out\vs\base\common\lifecycle.js'(으)로 파일 시스템 공급자를 확인할 수 없습니다.: Error: 상대 파일 경로 'c:\Github\microsoft\vscode\out\vs\base\common\lifecycle.js'(으)로 파일 시스템 공급자를 확인할 수 없습니다.

> Unable to determine file system provider with relative file path 'c:\Github\microsoft\vscode\out\vs\base\common\lifecycle.js'.: Error: Could not determine file system provider with relative file path 'c:\Github\microsoft\vscode\out\vs\base\common\lifecycle.js'

Which seems to be thrown here:

https://github.com/microsoft/vscode/blob/62fdec2defe2d41d5eb06c45b7b185c7df3abbb3/src/vs/workbench/contrib/debug/browser/linkDetector.ts#L131

Here's the URI that fails the exists check:

![image](https://github.com/microsoft/vscode/assets/2193314/8b974ed7-f92b-46e1-835a-940f8a4cb5b6)

**Comment by roblourens** [comment]
There are two different errors here but you're having the issue with the 'file:' one right?

**Comment by roblourens** [comment]
Not new, I see it in stable. Have this general tracking issue to fix this all up

https://github.com/microsoft/vscode/issues/34026
