### ISSUE TITLE
VS code thinks a file is read only when it is not

### ISSUE THREAD

**Issue by emr8ye** [Microsoft/vscode#19682]
- VSCode Version: Code 1.7.2 (7ba55c5860b152d999dda59393ca3ebeb1b5c85f, 2016-11-21T22:06:37.428Z)
- OS Version: Windows_NT ia32 6.3.9600
- Extensions:

|Extension|Author|Version|
|---|---|---|
|python|donjayamanne|0.5.2|
|cpptools|ms-vscode|0.9.2|
|csharp|ms-vscode|1.5.1|
|PowerShell|ms-vscode|0.7.2|

---

Steps to Reproduce:

1. Edit a file in source depot (ie. sd edit <file>).
2. Open the file in vs code (ie. code <file>).
3. Make changes to file.
4. Try to save. I know that the file is not read only b/c notepad and visual studio have no qualms about saving the file.

**Comment by bpasero** [comment]
@emr8ye what is the error you are seeing?

**Comment by emr8ye** [comment]
A banner at the top that says: "Error: Failed to save <file name>: file is write protected. Select "override" to ..."

**Comment by emr8ye** [comment]
Also, full disclosure I work at Microsoft in C&E. I can send a screen shot tomorrow if that's more helpful.

**Comment by bpasero** [comment]
@emr8ye weird, do you have any other text editor installed besides notepad and VS that you could try to see if saving is possible?

**Comment by emr8ye** [comment]
Vim also has no trouble.

**Comment by bpasero** [comment]
@emr8ye can I ask you for a little experiment?
* make a backup of the file that seems to be write protected
* download node.js 6.5.0 from [here](https://nodejs.org/download/release/v6.5.0/node-v6.5.0-win-x86.zip)
* run it (`node`) from the command line, it will open a JS prompt
* type `fs.writeFileSync("<path to file>", "hello world")`
=> does it work?

**Comment by emr8ye** [comment]
I've seen this issue many times and it was driving me crazy, but now that I want to repro it to run this I can't. Can you close this bug? I'll open a new one if I see it again.

**Comment by bpasero** [comment]
That is weird indeed 👍
