### ISSUE TITLE
command 

### ISSUE THREAD

**Issue by in27sung** [microsoft/vscode#196880]
Type: <b>Bug</b>

It doesn't seem to work the command + K for clear my termial 

VS Code version: Code 1.83.1 (Universal) (f1b07bd25dfad64b0167beb15359ae573aecd2cc, 2023-10-10T23:46:55.789Z)
OS version: Darwin arm64 23.0.0
Modes:
Remote OS version: Linux x64 6.2.0-1015-azure

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.03GB free)|
|Process Argv|--crash-reporter-id c546db35-856e-4af6-a959-9ae5777a7d10|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|Codespaces: probable space barnacle|
|OS|Linux x64 6.2.0-1015-azure|
|CPUs|AMD EPYC 7763 64-Core Processor (2 x 2445)|
|Memory (System)|7.74GB (6.07GB free)|
|VM|0%|
</details><details><summary>Extensions (36)</summary>

Extension|Author (truncated)|Version
---|---|---
codespaces|Git|1.16.2
better-cpp-syntax|jef|1.17.2
jupyter-keymap|ms-|1.1.2
cs50|CS5|0.0.1
ddb50|CS5|2.0.0
explain50|CS5|1.0.0
extension-uninstaller|CS5|1.0.8
phpliteadmin|CS5|0.0.1
style50|CS5|0.0.1
codespaces|Git|1.16.2
vscode-pull-request-github|Git|0.74.1
prettier-sql-vscode|inf|1.6.0
vscode-pdf|mat|0.0.6
vscode-docker|ms-|1.27.0
vscode-language-pack-bg|MS-|1.48.3
vscode-language-pack-cs|MS-|1.83.2023101109
vscode-language-pack-de|MS-|1.83.2023101109
vscode-language-pack-es|MS-|1.83.2023101109
vscode-language-pack-fr|MS-|1.83.2023101109
vscode-language-pack-hu|MS-|1.48.3
vscode-language-pack-it|MS-|1.83.2023101109
vscode-language-pack-ja|MS-|1.83.2023101109
vscode-language-pack-ko|MS-|1.83.2023101109
vscode-language-pack-pl|MS-|1.83.2023101109
vscode-language-pack-pt-BR|MS-|1.83.2023101109
vscode-language-pack-ru|MS-|1.83.2023101109
vscode-language-pack-zh-hans|MS-|1.83.2023101109
vscode-language-pack-zh-hant|MS-|1.83.2023101109
python|ms-|2023.18.0
vscode-pylance|ms-|2023.10.50
cpptools|ms-|1.17.5
hexeditor|ms-|1.9.12
vsliveshare|ms-|1.0.5883
java|red|1.24.0
vscode-java-debug|vsc|0.54.0
gitdoc|vsl|0.1.0

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
py29gd2263:30856252
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
282f8724:30602487
f6dab269:30613381
2i9eh265:30646982
showlangstatbar:30737416
0bi6i642:30841073
03d35959:30757346
pythonfmttext:30731395
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
pythonnosmt12:30797651
pythonidxpt:30866567
pythonnoceb:30805159
copilotsettingc:30859502
synctok:30869157
dsvsc013:30795093
dsvsc014:30804076
dsvsc015:30845448
pythontestfixt:30871694
pythonregdiag2:30871582
pyreplss1:30865275
pythoncet00cf:30874137
2e7ec940:30870395
pythontbext0cf:30864173

```

</details>

**Comment by Tyriar** [comment]
See https://code.visualstudio.com/docs/terminal/advanced#_macos-clear-screen
