### ISSUE TITLE
anti virus

### ISSUE THREAD

**Issue by Nancy-byte** [microsoft/vscode#196819]
Type: <b>Performance Issue</b>

I AM TRYING TO CODE "HELLO WORLD" BUT IT'S NOT EXECUTING. IT'S SHOWING SOME "NATIVE ERROR OCURRED" EVERYTIME I TRY TO RUN MY CODE. KINDLY SOLVE THIS ISSUE.

VS Code version: Code 1.83.1 (Universal) (f1b07bd25dfad64b0167beb15359ae573aecd2cc, 2023-10-10T23:46:55.789Z)
OS version: Darwin arm64 22.4.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M2 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|8.00GB (0.09GB free)|
|Process Argv|--crash-reporter-id aa430bfb-d734-4e81-9f33-11b59756b6a4|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
   14	   106	  4953	code main
    0	    41	  4970	   gpu-process
    0	    16	  4971	   utility-network-service
    0	    49	  4996	shared-process
    0	     0	 15609	     /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0	    16	  5070	ptyHost
    0	   172	 14707	window [5] (Settings)
    0	    25	 15203	fileWatcher [5]
    0	    57	 15204	extensionHost [5]
    0	    25	 15228	     electron-nodejs (/private/var/folders/q3/yfmx44h95919959h6gn59zb40000gn/T/AppTranslocation/993B2B44-70B7-4B00-9BA5-091E8EFF87DD/d/Visual Studio Code-2.app/Contents/Frameworks/Code Helper (Plugin).app/Contents/MacOS/Code Helper (Plugin) --ms-enable-electron-run-as-node /private/var/folders/q3/yfmx44h95919959h6gn59zb40000gn/T/AppTranslocation/993B2B44-70B7-4B00-9BA5-091E8EFF87DD/d/Visual Studio Code-2.app/Contents/Resources/app/extensions/json-language-features/server/dist/node/jsonServerMain --node-ipc --clientProcessId=15204)
    1	    90	 15599	window [6] (Issue Reporter)
```

</details>
<details>
<summary>Workspace Info</summary>

```
;
```

</details>
<details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
gitlens|eam|14.4.1
code-runner|for|0.12.1
vscode-clangd|llv|0.1.24
cmake-tools|ms-|1.15.31
cpptools|ms-|1.17.5
cpptools-extension-pack|ms-|1.3.0
cmake|twx|0.0.17

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
py29gd2263:30856252
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
2e4cg342:30602488
f6dab269:30613381
2i9eh265:30646982
showlangstatbar:30737416
a2ce3375:30757347
pythonfmttext:30731395
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
pythonnosmt12:30797651
pythonidxpt:30866567
pythonnoceb:30805159
copilotsettingt:30859503
synctok:30869157
dsvsc013:30795093
dsvsc014:30804076
pythonmhint1:30842940
dsvsc015:30845448
pythontestfixtcf:30871695
pythonregdiag2cf:30871583
pyreplss1:30865275
h48ei257:30870396
pythontbext0:30864172

```

</details>

**Comment by roblourens** [comment]
This sounds like an issue with your code or project configuration, not with vscode
