### ISSUE TITLE
Jupyter Notebook Kernel on Remote SSH Server suddenly died SILENTLY while running code and cannot be restarted without reloading entire window

### ISSUE THREAD

**Issue by ductai199x** [microsoft/vscode#196855]
Does this issue occur when all extensions are disabled?: No

- VS Code Version: 1.83.1 (Latest)
- OS Version: Windows 11 (Latest)

Steps to Reproduce:

1. SSH into a remote server
2. Open an existing Jupyter Notebook with some code, in my case, Pytorch code
3. Run the code
4. Wait for a couple minutes
5. The Ipykernel of my notebook SILENTLY dies and CANNOT be restarted by clicking on the restart kernel button.

Note: This behavior doesn't always happen but rather, sporadically, so maybe harder to reproduce. Will update this thread if I can find a consistent way to cause this bug to happen

**Comment by AntoSave** [comment]
I apparently have the same problem working with WSL2

**Comment by wongws11** [comment]
I am having the same issue right now, it never happened before. This should be something new. 

Computer: Macbook Pro M2 Max
Client OS: macOS 14.0
Server OS (VM): Ubuntu 22.04.3 LTS
VS Code Version: 1.83.1

**Comment by ductai199x** [comment]
Just an update since it's been a week, Reverting Pylance back to v2023.10.40 resolves everything. So it's very likely that the new Pylance update v2023.10.50 broke it. I have seen same behavior consistently on 5 different remote ubuntu servers now.

**Comment by ductai199x** [comment]
Does anyone have any updates on this issue?

**Comment by ductai199x** [comment]
bumping this

**Comment by rebornix** [comment]
@ductai199x the latest Pylance extension should have this fixed now.
