### ISSUE TITLE
VSCode login 

### ISSUE THREAD

**Issue by Josemar95** [microsoft/vscode#196820]
I'm not sure if this functionality already exists, if it does, I'm not aware of it. It would be interesting for VSCode to have a login screen, with the main focus on safeguarding extensions. It's annoying to have to search for everything again, at least with login, everything would be linked to the user, avoiding losses.

**Comment by gjsjohnmurray** [comment]
Please see https://code.visualstudio.com/docs/editor/settings-sync

**Comment by TylerLeonhardt** [comment]
Yeah I think Settings Sync is what you're looking for which @gjsjohnmurray linked there.
