### ISSUE TITLE
[WelcomeUX] Don't open Untitled file when Welcome page is opened

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#19689]
Having both seems like too much. Instead we could add a New File action to the Start section. /cc @rebornix

**Comment by chrmarti** [comment]
@bpasero What do you think? (No untitled file if Welcome opens and New File in Welcome's Start section, screenshot below.)

![newfile](https://cloud.githubusercontent.com/assets/9205389/22605224/c6d4de32-ea03-11e6-905b-9d8b39d8db5e.png)

**Comment by bpasero** [comment]
Fine by me.
