### ISSUE TITLE
Wrong template formating

### ISSUE THREAD

**Issue by petrck** [Microsoft/vscode#19680]
I found problem with template formatting. In my razor View (.cshtml) press Shift + Alt + F, C# core is corrupted. More in attach. Is it bug or I have wrong setting of IDE? Thank you.

![before](https://cloud.githubusercontent.com/assets/9294613/22515817/1ccd5546-e8a4-11e6-90a2-f65f29407d08.png)
![after](https://cloud.githubusercontent.com/assets/9294613/22515818/1cd8bcce-e8a4-11e6-8c72-245d282814b3.png)

**Comment by bpasero** [comment]
Reading your description it seems that the issue originates from an extension and not VS Code itself. Thereby I will close this issue and kindly ask you to report this issue against the extension repository. 

Most extensions are on GitHub as well so it should be easy to file it against the extension. If you open an extension on the market place, click on the **Support** link to find out more.

<img width="196" alt="screen shot 2016-05-05 at 12 51 17" src="https://cloud.githubusercontent.com/assets/900690/15041943/263e2282-12c0-11e6-9a33-d2b3b500d61b.png">

Thanks again for your feedback!

**Comment by jdc1103** [comment]
That is a problem of vscode, it don't support cshtml auto indent and I can't find any extension to format that file :(
