### ISSUE TITLE
Extension Icons missing

### ISSUE THREAD

**Issue by brandondube** [Microsoft/vscode#19688]
- VSCode Version: 1.8.1
- OS Version: Windows 10

Steps to Reproduce:

1. Install VS Code with ninite
2. install any extension

<p align="left">
  <img alt="the bug" src="http://i.imgur.com/FsqOS0p.jpg">
</p>

A fresh install of the editor with Ninite results in extensions not having icons.  Clicking any of them to open their pages does show full markdown support, including images.

**Comment by mjbvz** [comment]
One quick question: if you expand the extension pane, do the icons show or are they always missing? The screenshots seems to show the extensions panel being too narrow to show the icons

**Comment by brandondube** [comment]
Well, doesn't that make me feel silly...  It was indeed too narrow.
