### ISSUE TITLE
[editor] Comment line also includes surrounding embedding language

### ISSUE THREAD

**Issue by DrYSG** [Microsoft/vscode#19686]
- VSCode Version: 1.8.1
- OS Version: win7 64 bit

Steps to Reproduce:

I am using Visual Studio Code, and it has a insert comment feature (CTRL-/) or SHFT-ALT-A

but it is inserting javascript style comments into my HTML file

original
```
<script src="./node_modules/react/dist/react.js"></script>
<script src="./node_modules/react-dom/dist/react-dom.js"></script>
```

result:
```
// <script src="./node_modules/react/dist/react.js"></script>
// <script src="./node_modules/react-dom/dist/react-dom.js"></script>

```
Which does not work, I searched prior issues, but I might have missed this.

**Comment by erocheleau** [comment]
I think I have a similar issue.

When I am in an HTML page, inside <script> tags, it inserts `<!-- -->` style comments instead of `//` or `/* */` style of comments.

**Comment by aeschli** [comment]
Given a cursor position or selection, we should only expand only to the start or end of the embedded range (not the start of the line)

**Comment by rebornix** [comment]
This issue was already fixed as proposed.
