### ISSUE TITLE
Settings Sync doesn't show configuration panel first?

### ISSUE THREAD

**Issue by rzhao271** [microsoft/vscode#196860]
On the latest Insiders on a CentOS 7 VM, I signed in to enable Settings Sync, but didn't get the option to configure it immediately, so now my VM is unresponsive while it installs several extensions.

![Several extensions being installed in the extensions viewlet](https://github.com/microsoft/vscode/assets/7199958/cb7b3bb5-1c6b-4155-919e-6d52db0f6f6e)

**Comment by sandy081** [comment]
I am seeing this when I click on button **Backup & Sync Settings**

<img width="634" alt="image" src="https://github.com/microsoft/vscode/assets/10746682/2fec519f-7eed-4430-a107-402c08568dc2">

Are not you seeing this?

**Comment by rzhao271** [comment]
Cannot repro on the latest Insiders.
