### ISSUE TITLE
VS Code quits on launch

### ISSUE THREAD

**Issue by lyahdav** [Microsoft/vscode#19687]
- VSCode Version: 1.8.1
- OS Version: OS X El Capitan 10.11.6

Steps to Reproduce:

1. In Finder, go to Applications folder and double click Visual Studio Code.
2. The app icon will show in the dock for a few seconds as if it's launching and then it will disappear and the app quits.

It seems kind of similar to https://github.com/Microsoft/vscode/issues/7927 in that my Console shows this error message:

> 2/1/17 11:17:03.998 AM com.apple.xpc.launchd[1]: (com.microsoft.VSCode.400352[31293]) Service exited with abnormal code: 1

It's different from that issue because I can't even launch VS Code from terminal.
VSCode was working before but I was having issues with the auto updater so I tried reinstalling it and then this issue started happening. If it matters, I installed the app through our company setup of [Managed Software Center](https://github.com/munki/munki).

**Comment by bpasero** [comment]
@lyahdav does it work after a full restart of macOS? Maybe a previous Code process is hanging around.

**Comment by jasvvinder** [comment]
I am also facing the same issue with VS Code. When i double click on VS Code in Application folder, the app icon shows in dock but quits automatically without displaying any error message.
I have tried Insider version also but facing the same issue.
Also tried launching using terminal command "code", it shows following error:
![screen shot 2017-02-02 at 1 09 55 pm](https://cloud.githubusercontent.com/assets/12081077/22540947/3f06da9c-e949-11e6-88a9-c47151db6a98.png)

Using:
VSCode Version: 1.8.1
OS Version: OS Sierra 10.12.3

**Comment by bpasero** [comment]
@lyahdav @jasvvinder and what if you try from the command line:

`/Applications/Visual Studio Code.app/Contents/MacOS> ./Electron --verbose`

**Comment by lyahdav** [comment]
@bpasero When I ran that from the command line it gave me this:

> Startup error: ,,,Error: EACCES: permission denied, mkdir '/Users/lironyahdav/Library/Application Support/Code/CachedData'

I checked and that folder didn't exist. I did have a `/Users/lironyahdav/Library/Application Support/Code` folder, but no `CachedData` folder underneath it. I also noticed that all subfolders in `/Users/lironyahdav/Library/Application Support` were owned by my user but the Code subfolder was owned by `root` for some reason. Possibly because VS Code was installed by [Managed Software Center](https://github.com/munki/munki).

So then I ran:
`sudo chown -R lironyahdav '/Users/lironyahdav/Library/Application Support/Code'`

And then when I launched VS code again everything worked correctly.

It looks like I'm still having an issue where I can't update the app though, which might also be related to Managed Software Center. I get the popup asking for my credentials to update:
![image](https://cloud.githubusercontent.com/assets/359157/22603764/975a40b2-e9fd-11e6-896c-f87435945070.png).
Afterwards I get the toast telling me to update now:
![image](https://cloud.githubusercontent.com/assets/359157/22603785/ac2c313a-e9fd-11e6-920f-431b893e5057.png)
When I click the Update Now button it quits VS code but never restarts. Then if I manually launch it I get the old version of the app. I'm trying to upgrade from 1.8.1 to 1.9.

Should I open a separate issue for the upgrade issues?

---

BTW the command you gave me to launch Electron was slightly off, it worked with:
```
/Applications/Visual\ Studio\ Code.app/Contents/MacOS/Electron --verbose
```

**Comment by bpasero** [comment]
@lyahdav it is a problem if you run Code once as root and then start it as other user for the obvious reasons that some data directories cannot be created. Your fix was the right one 👍 

The update issue sounds a lot like https://github.com/Microsoft/vscode/issues/17368 so I suggest you add your voice there.

**Comment by jasvvinder** [comment]
@bpasero @lyahdav  i have removed all previous versions of VS Code and downloaded the Latest version again from here https://code.visualstudio.com/docs/?dv=osx but the problem still exist. 
Also tried this Command:
`/Applications/Visual\ Studio\ Code.app/Contents/MacOS/Electron --verbose`

It shows this error:
![screen shot 2017-02-08 at 12 37 02 pm](https://cloud.githubusercontent.com/assets/12081077/22726734/07e95ad8-edfb-11e6-9f53-e17afd9a170a.png)

Then i ran this command as above said:
`sudo chown -R EF07 '/Users/EF07/Library/Application Support/Code'`
After this ran this command: `/Applications/Visual\ Studio\ Code.app/Contents/MacOS/Electron --verbose` again but it shows the same error.

**Comment by bpasero** [comment]
@joaomoreno any ideas?

**Comment by joaomoreno** [comment]
@jasvvinder Can you show us the output of

```
id
echo $USER
ls -lad ~
ls -lad ~/.vscode
```

**Comment by jasvvinder** [comment]
@joaomoreno 

![screen shot 2017-02-08 at 4 42 12 pm](https://cloud.githubusercontent.com/assets/12081077/22734865/3e90883c-ee1d-11e6-925b-e4c4fcedf9ee.png)

**Comment by jasvvinder** [comment]
@bpasero @joaomoreno  any solution?

**Comment by joaomoreno** [comment]
Can you `mkdir ~/.vscode` from the terminal?

**Comment by jasvvinder** [comment]
Yes, Here is screenshot.

![screen shot 2017-02-09 at 4 51 06 pm](https://cloud.githubusercontent.com/assets/12081077/22781221/89eae8d4-eee7-11e6-89be-8b1528ef665c.png)

**Comment by joaomoreno** [comment]
How about `ls -la ~/.vscode`

**Comment by jasvvinder** [comment]
@joaomoreno Here is the output:
![screen shot 2017-02-10 at 11 03 07 am](https://cloud.githubusercontent.com/assets/12081077/22815230/1538abe0-ef80-11e6-97b2-414d5072aae4.png)

**Comment by joaomoreno** [comment]
You seem to have a very strange file system issue:

- Your user (`EF07`) has permissions to write to `/Users/EF07`
- There isn't any folder of file called `/Users/EF07/.vscode`
- Yet, `mkdir /Users/EF07/.vscode` fails.

Is there anything special about your system?
