### ISSUE TITLE
Import and Go To Definition not working

### ISSUE THREAD

**Issue by Fayez-007** [microsoft/vscode#196828]
Type: <b>Bug</b>

One of my specific project not working Command + Space  import and Command + Click for navigate component is not working , I don't know what problem is

I'm using next js 13

VS Code version: Code 1.83.1 (Universal) (f1b07bd25dfad64b0167beb15359ae573aecd2cc, 2023-10-10T23:46:55.789Z)
OS version: Darwin arm64 22.5.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|10, 9, 7|
|Memory (System)|8.00GB (0.14GB free)|
|Process Argv|--crash-reporter-id 8257b3f8-4ecd-4fb7-a207-900e07045042|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (40)</summary>

Extension|Author (truncated)|Version
---|---|---
react-hooks-snippets|AlD|1.2.0
flutter-snippets|ale|3.0.0
emojisense|bie|0.10.0
vscode-tailwindcss|bra|0.10.1
turbo-console-log|Cha|2.9.6
path-intellisense|chr|2.8.5
ccs-flutter-color|cir|1.2.0
package-json-upgrade|cod|2.1.1
codeium|Cod|1.4.4
dart-code|Dar|3.74.0
flutter|Dar|3.74.0
vscode-eslint|dba|2.4.2
githistory|don|0.6.20
es7-react-js-snippets|dsz|4.4.3
gitlens|eam|14.4.1
vscode-html-css|ecm|1.13.1
prettier-vscode|esb|10.1.0
auto-close-tag|for|0.5.14
auto-rename-tag|for|0.1.10
code-runner|for|0.12.1
copilot|Git|1.130.0
copilot-chat|Git|0.8.0
vscode-flutter-files|gor|4.7.1
vscode-codemetrics|kis|1.26.1
git-graph|mhu|1.30.0
dotenv|mik|1.0.1
vscode-docker|ms-|1.27.0
vscode-react-native|msj|1.12.1
color-highlight|nau|2.5.0
material-icon-theme|PKi|4.31.0
vscode-react-refactor|pla|1.1.3
vscode-css-peek|pra|4.4.1
quicktype|qui|12.0.46
html-to-jsx|ria|0.0.1
LiveServer|rit|5.7.9
autoimport|ste|1.5.4
code-spell-checker|str|3.0.1
teamhub|Tea|16.1.5
vscode-icons|vsc|12.6.0
vscode-import-cost|wix|3.3.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263:30335439
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
py29gd2263:30856252
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
282f8724:30602487
f6dab269:30613381
showlangstatbar:30737416
962ge761:30841074
03d35959:30757346
pythonfmttext:30731395
f8hc8238:30694864
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
pythonnosmt12:30797651
pythonidxpt:30866567
pythonnoceb:30805159
copilotsettingt:30859503
asynctok:30869155
dsvsc013:30795093
dsvsc014:30804076
dsvsc015:30845448
pythontestfixtcf:30871695
pythonregdiag2cf:30871583
pyreplss1:30865275
pythoncet00cf:30866519
2e7ec940:30870395
pythontbext0:30864172

```

</details>

**Comment by Fayez-007** [comment]
![Screenshot 2023-10-27 at 6 02 38 PM](https://github.com/microsoft/vscode/assets/102020781/1076b04a-8447-4fb5-88fe-0f99ed4782f8)
![Screenshot 2023-10-27 at 6 02 12 PM](https://github.com/microsoft/vscode/assets/102020781/f4222392-5ba3-4ed3-9759-7a3b363e0c03)

Above two images are my attachments for reference 
One is jsconfig.json
Another one is javascript / typscript language feature error
and also newly showing error that Configure excludes

**Comment by mjbvz** [comment]
Looks like your project may be misconfigured. Have you tried configuring excludes and also making sure the files you are working in are part of the same project?

**Comment by Fayez-007** [comment]
Yes, I have excluded node_modules and .next folder still showing like "To enable project-wide JavaScript/TypeScript language features, exclude large folders with source files that you do not work on." 

Yes it is on the same project I have checked

**Comment by mjbvz** [comment]
Can you share the project or even better a minimal version which causes the issue?

**Comment by Fayez-007** [comment]
actually, the project is big.
 
if I exclude some javascript folders, it works fine.  I think Intelisense is not able to handle large javascript folders
I already excluded node_modules .next in jsconfig. still, I have to exclude one or more js project folder

I wanted to work on all my src folders except node_modules and .next folder

**Comment by mjbvz** [comment]
Hard to say without seeing your project

Closing for now but if you can share a project I can take a look
