### ISSUE TITLE
Can't edit. This is an inconvenience.

### ISSUE THREAD

**Issue by jmcclinton** [microsoft/vscode#196834]
Type: <b>Bug</b>

I can't edit in VS code. Why?

VS Code version: Code 1.83.1 (Universal) (f1b07bd25dfad64b0167beb15359ae573aecd2cc, 2023-10-10T23:46:55.789Z)
OS version: Darwin x64 23.1.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|1, 2, 2|
|Memory (System)|16.00GB (0.03GB free)|
|Process Argv|--crash-reporter-id b1d0e625-244c-44c2-820a-37ec8eaea553|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (153)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|3.0.2
emmet-keybindings|agu|1.2.1
react-vsc-essentials|agu|1.0.0
vscode-javascript-snippet-pack|aka|0.1.6
TabOut|alb|0.2.2
ng-template|Ang|16.1.8
vscode-color|ans|0.4.5
html-end-tag-labels|ant|1.0.0
vscode-mjml|att|1.6.0
vscode-django|bat|1.14.0
htmlplay|bia|0.0.10
color-info|bie|0.7.2
markdown-preview-github-styles|bie|2.0.3
snippets|Bin|2.0.0
vscode-intelephense-client|bme|1.9.5
file-browser|bod|0.2.11
bracket-pair-color-dlw|Bra|0.0.6
vscode-tailwindcss|bra|0.10.1
phpserver|bra|3.0.2
vscode-toggle-quotes|Bri|0.3.6
simple-react-snippets|bur|1.2.7
emmet-jss|car|1.0.0
directory-files|cas|0.0.5
npm-intellisense|chr|1.4.5
path-intellisense|chr|2.8.5
ccs-flutter-color|cir|1.2.0
mjml-editor|cyt|1.1.1
vae-tools|Dan|0.0.4
vscode-mjml|Dan|2.4.13
vscode-eslint|dba|2.4.2
composer-php-vscode|DEV|1.40.14103
intelli-php-vscode|DEV|0.10.14097
phptools-vscode|DEV|1.40.14103
profiler-php-vscode|DEV|1.40.14103
mjml-syntax|dig|0.0.1
githistory|don|0.6.20
python-environment-manager|don|1.2.4
python-extension-pack|don|1.7.0
es7-react-js-snippets|dsz|4.4.3
gitlens|eam|14.4.1
vscode-html-css|ecm|1.13.1
EditorConfig|Edi|0.16.4
react-native-react-redux|EQu|2.0.6
vsc-material-theme-icons|equ|3.1.4
prettier-vscode|esb|10.1.0
comment-anchors|Exo|1.10.3
vscode-open-in-github|fab|1.3.0
vscode-firefox-debug|fir|2.9.10
auto-close-tag|for|0.5.14
auto-rename-tag|for|0.1.10
html-preview-vscode|geo|0.2.5
codespaces|Git|1.16.2
remotehub|Git|0.62.0
vscode-github-actions|git|0.26.2
vscode-pull-request-github|Git|0.74.1
live-sass|gle|6.1.1
gobystrok|GoB|0.0.1
vscode-graphql|Gra|0.8.19
vscode-graphql-syntax|Gra|1.2.2
bettercomment|Gru|0.0.15
vscode-gp-postman-pat|Gru|0.9.7
vue-snippets|hol|1.0.4
vscode-slonik-live-server|hoo|1.0.14
hq-live-server|hqj|0.0.11
vscode-react-typescript|inf|1.3.1
easy-snippet|inu|0.6.3
hungry-delete|jas|1.7.0
search-node-modules|jas|1.3.0
react-vscode-extension-pack|jaw|1.0.0
Angular2|joh|16.0.1
vsc-python-indent|Kev|1.18.0
vscode-mjml-template-literal|kos|0.1.0
mjml-snippets|kvn|1.1.0
angular-pack|lau|1.0.0
react-pack|lau|1.0.0
vue-pack|lau|1.0.0
vs-color-picker|lih|1.0.0
live-server-qr|luc|0.0.2
aws-cli-configure|mar|0.3.0
php-namespace-resolver|Meh|1.1.9
vscode-language-babel|mgm|0.0.40
code-beautifier|mic|2.3.3
vscode-checkpoints|mic|1.3.3
dotenv|mik|1.0.1
goto-next-previous-member|mis|0.0.6
vscode-mjml|mjm|1.0.6
vscode-html-format|moh|0.1.2
vscode-duplicate|mrm|1.2.1
azure-dev|ms-|0.7.0
vscode-docker|ms-|1.27.0
vscode-edge-devtools|ms-|2.1.3
python|ms-|2023.18.0
vscode-pylance|ms-|2023.10.50
atom-keybindings|ms-|3.3.0
azure-repos|ms-|0.38.0
azurecli|ms-|0.5.0
remote-repositories|ms-|0.40.0
vscode-github-issue-notebooks|ms-|0.0.130
vscode-typescript-next|ms-|5.3.20231026
vscode-react-native|msj|1.12.1
java-prettier-formatter|mwp|0.1.6
html-live-server|nav|0.1.0
live-server-preview|neg|0.1.4
php-docblocker|nei|2.7.0
abracadabra|nic|8.1.4
copy-json-path|nid|0.3.0
autodocstring|njp|0.6.1
prettier-standard-vscode|num|1.0.2
vetur|oct|0.37.3
laravel-blade|one|1.34.0
heroku-command|pko|0.0.8
tns-cli|pko|0.0.3
vscode-css-peek|pra|4.4.1
vscode-thunder-client|ran|2.14.1
vscode-handlebars-mjml|rbr|1.2.0
vscode-sort-json|ric|1.20.0
format-html-in-php|rif|1.7.0
LiveServer|rit|5.7.9
es7-react-js-snippets|rod|1.9.3
vs-code-prettier-eslint|rve|5.1.0
partial-diff|ryu|1.4.3
salesforcedx-vscode-core|sal|59.1.2
vscode-sass-format|sas|1.1.7
vscode-javascript-booster|sbu|14.0.1
angular-cli|seg|0.0.19
html5-boilerplate|sid|1.1.1
html-to-css-autocompletion|sol|1.1.2
sass-indented|syl|1.8.28
snippets|tah|3.1.0
icons|tal|3.7.0
bootstrap4-vscode|the|6.1.0
errorlens|use|3.15.0
sfdx-cli|vib|0.0.1
intellicode-api-usage-examples|Vis|0.2.8
vscodeintellicode|Vis|1.2.30
vscode-icons|vsc|12.6.0
vim|vsc|1.26.2
bootstrap-3-snippets|wcw|0.1.0
jinja|who|0.0.8
vscode-import-cost|wix|3.3.0
eno|Wsc|2.3.53
html-snippets|wsc|1.0.6
JavaScriptSnippets|xab|1.8.0
ReactSnippets|xab|2.4.0
php-debug|xde|1.33.1
php-pack|xde|1.0.3
five-server|yan|0.2.3
vscode-surround|yat|1.5.0
emmet-live|yse|1.0.0
bootstrap-v4-snippets|Zac|1.1.3
vscode-react|zha|0.0.5
html-css-class-completion|Zig|1.20.0
php-intellisense|zob|1.3.3

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
py29gd2263:30856252
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
3biah626:30602489
89544117:30613380
showlangstatbar:30737416
03d35959:30757346
pythonfmttext:30731395
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
pythonnosmt12:30797651
pythonidxpt:30866567
pythonnoceb:30805159
copilotsettingt:30859503
dsvsc013:30795093
dsvsc014:30804076
pythonmhint1:30842940
dsvsc015:30845448
pythontestfixtcf:30871695
pythonregdiag2:30871582
pyreplss1:30865275
pythonmypyd1cf:30859727
pythoncet0:30866520
h48ei257:30870396
pythontbext0:30864172

```

</details>

**Comment by chrmarti** [comment]
Could you describe in more detail what you are doing that does not work?

**Comment by jmcclinton** [comment]
I am in a email development course using MJML code. I am trying to edit the code in VS and it doesn't allow me to type in new information. It seems like it's in read only mode. I am using Macbook Pro.

**Comment by chrmarti** [comment]
Try opening the file with Quick Open by pressing `Ctrl + P`, typing the file name and pressing Enter. If that also gives you a read-only editor, please check the file permissions.

**Comment by jmcclinton** [comment]
Thanks. It's works now. ;-)

**Comment by jmcclinton** [comment]
Thanks!
