### ISSUE TITLE
In-progress badge on SCM activity bar icon gets overwritten prematurely by count badge

### ISSUE THREAD

**Issue by gjsjohnmurray** [microsoft/vscode#196801]
Type: <b>Bug</b>

An extension I maintain creates multiple SourceControl objects and implements a command to refresh them all in parallel. When an object has completed its refresh (adding/removing/updating its SourceControlResourceGroups) it updates its count property. When this happens for the first object the progress (clock) badge on the SCM icon in the activity bar gets replaced by that count, thus giving the user the impression that the refresh has completed if they have switched to a different activity and so don't see the ongoing progress bar animation across the top of the SOURCE CONTROL pane.

When ProgressService adds the clock badge using ActivityService it specifies `priority: 100`, which sounds like it is supposed to give this badge priority over a count badge:

https://github.com/microsoft/vscode/blob/5a8659ad664d784a7b2fd7f08a3ec1fb741e1cec/src/vs/workbench/services/progress/browser/progressService.ts#L455

But it doesn't seem to have that effect.

I will try to prepare a sample extension that demonstrates the issue.

VS Code version: Code - Insiders 1.84.0-insider (9ea20d5e2473f400e7eeaebf5b98def771155146, 2023-10-26T21:24:03.029Z)
OS version: Windows_NT x64 10.0.22621
Modes:

**Comment by lszomoru** [comment]
Adding @sandy081 as he seems to have recently changed the referenced line.

**Comment by sandy081** [comment]
Would be waiting for the sample extension. Thanks in advance for doing so.

Can you also please check the behaviour in older version of VS Code?

**Comment by gjsjohnmurray** [comment]
For the repro:
1. Clone https://github.com/gjsjohnmurray/vscode-extension-samples/tree/show-196801 
2. Open the source-control-sample folder.
3. Build and run.
4. In EDH window, close any already-open folder/workspace, and optionally create an empty profile to rule out other extensions and odd settings.
5. From palette run `Open JSFiddle`. Accept the default (demo), then in the local folder dialog create/choose a scratch folder, and trust it if prompted.
6. Switch to SCM view.
7. Run `Developer: Reload Window` and watch the SCM side bar and activity bar icon badge:

![junk](https://github.com/microsoft/vscode/assets/6726799/a657b6ba-d3bc-45eb-a535-f31c7d0f65cd)

Notice how the first SourceControl completes its withProgress refresh after 4 seconds, updates the input box placeholder to report this, and sets its count property. At this point the second SourceControl is half way through its 8-second refresh, and the progress bar animation continues, but the clock badge on the activity bar icon has been displaced by the count badge (4) of the first one.

Behaviour on 1.83.1 is correct:

![junk](https://github.com/microsoft/vscode/assets/6726799/d7c6724c-c4d4-47be-91bc-e368e55283ef)

**Comment by gjsjohnmurray** [comment]
@sandy081 do you now have the info you need?

Seeing how this is apparently a 1.84 regression, will it be treated as a Candidate for the milestone?

**Comment by sandy081** [comment]
@gjsjohnmurray Thanks a lot for info and repro. This is indeed a regression and caused by the wrong prioritising of the badges. 

Tagged this as candidate.

**Comment by sandy081** [comment]
Adding verified label as @gjsjohnmurray verified it
