### ISSUE TITLE
Commands missing translations

### ISSUE THREAD

**Issue by razonyang** [microsoft/vscode#196840]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.83.1 (user setup)
- OS Version: Windows 11 Home 22H2

Steps to Reproduce:

1. `F1`

![image](https://github.com/microsoft/vscode/assets/17720932/8261bbe3-1526-4d02-bb1a-0c786389f089)

I installed VS Code on Microsoft Store, and I've tried to reinstall it via https://code.visualstudio.com/, but have no luck.

**Comment by aeschli** [comment]
The extension has the string, but maybe there's an issue loading the nls file.

- can you uninstall and install the WSL and Dev Container extensions?

**Comment by razonyang** [comment]
> * can you uninstall and install the WSL and Dev Container extensions?

I could not, I've switched a new disk and format the whole old disk... I'm unable to reproduce this issue on my new disk/OS. Sorry for couldn't provide further information.

**Comment by aeschli** [comment]
Closing the issue then
