### ISSUE TITLE
[tsx] Angular 2 inline templates

### ISSUE THREAD

**Issue by jgw96** [Microsoft/vscode#1968]
I love the code formatting feature in vscode, simply awesome, but not perfect in my opinion. I have been using angular 2 alot lately and have run into an issue where the code formatting feature will not format an inline html template. This would be ideal, especially when copy/pasting html into an inline template. Would love to hear what everyone has to say about this.

**Comment by dbaeumer** [comment]
This issue was moved to Microsoft/TypeScript#6477
