### ISSUE TITLE
Git decorators disappears after split editor is closed

### ISSUE THREAD

**Issue by svipas** [microsoft/vscode#196806]
Type: <b>Bug</b>

I'm not using any symlinks. I'm on macOS Sonoma 14.0 (23A344), Git 2.42.0, VS Code 1.83.1.

Steps to repro:

1. Open file and add a new line.

<img width="519" alt="image" src="https://github.com/microsoft/vscode/assets/10441177/99c25e4b-98a1-422b-b17c-6a2fb7969170">

2. Use "View: Split Editor" (CMD+\\).
3. Everything looks good, still git diff decorator is visible.
4. Close right editor and you will see that git diff decorators disappeared.

<img width="1182" alt="image" src="https://github.com/microsoft/vscode/assets/10441177/3c7061bd-297b-4b16-918a-bd535b4158a5">

5. If I use split editor again it shows git diff decorations in both editors.

<img width="1111" alt="image" src="https://github.com/microsoft/vscode/assets/10441177/36176524-b56d-489d-a318-2542dd8c830a">

My `.gitconfig`

```
[core]
	excludesfile = ~/.gitignore_global
	editor = code --wait
[credential]
	helper = store
[pull]
	ff = only
[push]
	autoSetupRemote = true
[init]
	defaultBranch = main
[diff]
	tool = default-difftool
[difftool "default-difftool"]
	cmd = code --wait --diff $LOCAL $REMOTE
[merge]
	tool = code
[mergetool "code"]
	cmd = code --wait --merge $REMOTE $LOCAL $BASE $MERGED
```

No errors in developer tools. To me this looks like UI regression, because it happens for me only when I close split editor (the right one), because if I open split editor again it shows git decorators in both editors. By the way this impacts scroll sidebar decorators too.

VS Code version: Code 1.83.1 (f1b07bd25dfad64b0167beb15359ae573aecd2cc, 2023-10-10T23:57:32.750Z)
OS version: Darwin arm64 23.0.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|5, 4, 6|
|Memory (System)|32.00GB (8.79GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|2.4.2
gitlens|eam|14.4.0
prettier-vscode|esb|10.1.0
copilot|Git|1.129.0
copilot-chat|Git|0.8.0
vscode-graphql|Gra|0.8.19
vscode-graphql-syntax|Gra|1.2.2
symbols|mig|0.0.15
vscode-react-native|msj|1.12.1
vscode-thunder-client|ran|2.14.1
vscode-fileutils|sle|3.10.3
vim|vsc|1.26.2
quokka-vscode|Wal|1.0.572

(1 theme extensions excluded)

</details>

**Comment by svipas** [comment]
I can't reproduce on VS Code Insiders, so I guess this is already being fixed?

**Comment by lszomoru** [comment]
@svipas, thanks for checking the behaviour in VS Code Insiders. I will go ahead and optimistically close this issue as the bug is fixed in Insiders and Stable will be updated towards the end of next week.

**Comment by svipas** [comment]
@lszomoru Sounds good, I will re-check when new release is available to be sure it is really fixed and will let you know here.

**Comment by svipas** [comment]
@lszomoru can confirm that issue in 1.84.0 (Stable) is fixed as well.
