### ISSUE TITLE
Terminal Freezes - Since Version Upgraded

### ISSUE THREAD

**Issue by fulostix** [microsoft/vscode#196838]
Type: <b>Bug</b>

Hi - Ever since upgrading to Version: 1.83.1.  My Visual Studio application gets hung up in the terminal.  Evenutally a popup appears that the applicatoin is busy. I click WAIT and eventually functionality is restored.  This did not happen prior to the update.

I am using the PowerShell extension primarily. 

VS Code version: Code 1.83.1 (f1b07bd25dfad64b0167beb15359ae573aecd2cc, 2023-10-10T23:48:05.904Z)
OS version: Windows_NT x64 10.0.19042
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.86GB (4.93GB free)|
|Process Argv|--crash-reporter-id 17bab612-f6a7-46ea-8ddf-2c90571da1b1|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-github|Kni|0.30.7
powershell|ms-|2023.8.0
vscode-xml|red|0.26.1
json|Zai|2.0.2

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
py29gd2263cf:30856253
vscaat:30438848
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
282f8724:30602487
89544117:30613380
showlangstatbar:30737416
962ge761:30841074
03d35959:30757346
pythonfmttext:30731395
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
pythonnosmt12:30797651
pythonidxpt:30866567
pythonnoceb:30805159
copilotsettingc:30859502
synctok:30869157
dsvsc013:30795093
dsvsc014:30804076
dsvsc015:30845448
pythontestfixtcf:30871695
pythonregdiag2:30871582
pyreplss1:30865275
pythonmypyd1cf:30859727
2e7ec940:30870395
pythontbext0:30864172

```

</details>

**Comment by meganrogge** [comment]
It looks like your report is missing some important information, See [this wiki page](https://github.com/microsoft/vscode/wiki/Terminal-Issues) for more info on how to report actionable terminal issues.
/label info-needed terminal

**Comment by fulostix** [comment]
![VS_Freezes](https://github.com/microsoft/vscode/assets/48022086/66e2cb2c-9c98-4194-b95c-e89669c3c374)
[settings.json](https://github.com/microsoft/vscode/files/13217210/settings.json)

Win 10 Ver: Microsoft Windows [Version 10.0.19042.3448]

Please let me know if you require any additional info.

**Comment by fulostix** [comment]
I also noticed a Pty Host error..here is a screenshot of that
![Terminal_Error](https://github.com/microsoft/vscode/assets/48022086/0812692e-397b-4fa7-aab8-36c103e275f5)

**Comment by meganrogge** [comment]
@Tyriar any ideas here?

**Comment by Tyriar** [comment]
@fulostix Is this a company machine? It could be admin policies or anti-virus preventing you from launching conpty.

**Comment by fulostix** [comment]
Hi - It is a computer machine, but it has only started locking up recently after the last update to Visual Studio Code.  I am able to work, but sometimes it will lock up 2 or 3 times within a few minutes.  Let me know if there is any other data I can provide for you.

**Comment by dancherb** [comment]
I also noticed my integrated terminal (running Git Bash, Windows 10) takes much longer to start after the most recent update. ~5000ms instead of ~200ms.

**Comment by meganrogge** [comment]
Please see https://github.com/Microsoft/vscode/wiki/Performance-Issues for creating actionable performance problem issues.
