### ISSUE TITLE
[Problem] User Interface : Sub-Panel Automatic Opening/Closing

### ISSUE THREAD

**Issue by Malix-off** [microsoft/vscode#196925]
## Summary

When a sub-panel does open/close automatically, it only open/close it parent panel

## Exemple

Taking the example of
- `"debug.internalConsoleOptions": "openOnSessionStart"`
- `"debug.console.closeOnEnd": false`
:

### Current

- **When a debug session ends**:
The whole debug console parent panel is closed, rather than only the debug console sub-panel to be collapsed
- **When a debug session starts**:
The whole debug console parent panel is opened, but the debug console, as a sub-panel is not expended if it wasn't expended before
![opened debug console parent panel](https://github.com/microsoft/vscode/assets/76160668/b275fa0a-78a6-4c67-8630-4373a2a3de7b)

## Expected

- **When a debug session ends**:
Collapse the debug console sub-panel
![collapsed debug console](https://github.com/microsoft/vscode/assets/76160668/ce5cef59-00a2-4387-a23d-1f52602856da)
- **When a debug session starts**:
Expend the debug console sub-panel
![expended debug console](https://github.com/microsoft/vscode/assets/76160668/f3ac01b0-8c01-4735-983d-a4897ba671f5)

**Comment by roblourens** [comment]
Does setting `"debug.internalConsoleOptions": "openOnSessionStart"` do it for you?

**Comment by Malix-off** [comment]
- [Comment Reply](https://github.com/microsoft/vscode/issues/196925#issuecomment-1785815370) from @roblourens :
  > Does setting "debug.internalConsoleOptions": "openOnSessionStart" do it for you?

  Not exactly, it's part of a more important UI problem in visual studio code.
  I'm going to convert this issue to make it about that

**Comment by roblourens** [comment]
Sorry, I don't follow, can you explain more?

**Comment by Malix-off** [comment]
@roblourens
When a sub-panel (or tab, idk the exact terminology) does open/close automatically (for example the default "debug" sub-panel), the whole panel area is open/closed rather than only the precise sub-panel to be collapsed/expanded
