### ISSUE TITLE
`Trace/breakpoint trap` when trying to build `vscode` from source on WSL2 with `./scripts/code.sh`

### ISSUE THREAD

**Issue by hamirmahal** [microsoft/vscode#196939]
Type: <b>Bug</b>

1. In WSL2, run `yarn watch` in one terminal, and wait for
```
[watch-client    ] [00:12:40] Starting compilation...
[watch-client    ] [00:12:40] Starting watch-api-proposal-names ...
[watch-client    ] [00:12:40] Starting compilation api-proposal-names...
[watch-client    ] [00:12:43] Finished compilation api-proposal-names with 0 errors after 2985 ms
[watch-extensions] [00:12:47] Finished clean-extension-html-language-features-server after 10719 ms
[watch-extensions] [00:12:47] Starting watch-extension:html-language-features-server ...
[watch-extensions] [00:13:24] Finished compilation extensions with 0 errors after 47400 ms
[watch-client    ] [00:14:33] Finished compilation with 0 errors after 113015 ms
[watch-client    ] [00:14:33] Starting compilation...
[watch-client    ] [00:14:33] Finished compilation with 0 errors after 12 ms
```
2. Open a separate terminal and run `./scripts/code.sh`.

VS Code version: Code 1.83.1 (f1b07bd25dfad64b0167beb15359ae573aecd2cc, 2023-10-10T23:48:05.904Z)
OS version: Windows_NT x64 10.0.19045
Modes:
Remote OS version: Linux x64 5.15.90.1-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz (8 x 4008)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.69GB (2.09GB free)|
|Process Argv|--crash-reporter-id c9908bf2-b959-4eef-80b9-87ca266caff7|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 5.15.90.1-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz (8 x 4008)|
|Memory (System)|7.61GB (0.16GB free)|
|VM|0%|
</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
remote-containers|ms-|0.315.1
remote-ssh|ms-|0.106.5
remote-wsl|ms-|0.81.8
remote-explorer|ms-|0.4.1
gitlens|eam|14.4.1
prettier-vscode|esb|10.1.0
copilot|Git|1.130.0
copilot-chat|Git|0.8.0
LiveServer|rit|5.7.9
rust-analyzer|rus|0.3.1713
vs-code-prettier-eslint|rve|5.1.0
code-spell-checker|str|3.0.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscorecescf:30445987
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
py29gd2263:30856252
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyonecf:30548226
2e4cg342:30602488
f6dab269:30613381
a9j8j154:30646983
showlangstatbar:30737416
0bi6i642:30841073
03d35959:30757346
ecj1e332:30736112
pythonfmttext:30731395
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
pythonnosmt12:30797651
pythonidxpt:30866567
pythonnoceb:30805159
copilotsettingc:30859502
dsvsc013:30795093
dsvsc014:30804076
dsvsc015:30845448
pythontestfixt:30871694
pythonregdiag2:30871582
pyreplss1:30865275
pythoncet0:30874138
pythontbext0cf:30864173

```

</details>

**Comment by hamirmahal** [comment]
# Actual behavior
```
hamir@SATAIIISSD:~/vscode (main)$ ./scripts/code.sh 
yarn run v1.22.19
$ node build/lib/electron
Done in 0.69s.
[00:14:45] Synchronizing built-in extensions...
[00:14:45] You can manage built-in extensions with the --builtin flag
[00:14:45] [github] ms-vscode.js-debug-companion@1.1.2 ✔︎
[00:14:45] [github] ms-vscode.js-debug@1.84.0 ✔︎
[00:14:45] [github] ms-vscode.vscode-js-profile-table@1.0.3 ✔︎
Trace/breakpoint trap
```

# Expected behavior
`./scripts/code.sh` runs successfully on WSL2.

**Comment by hamirmahal** [comment]
# Actual behavior
```
hamir@SATAIIISSD:~/vscode (main)$ ./scripts/code.sh 
yarn run v1.22.19
$ node build/lib/electron
Done in 0.69s.
[00:14:45] Synchronizing built-in extensions...
[00:14:45] You can manage built-in extensions with the --builtin flag
[00:14:45] [github] ms-vscode.js-debug-companion@1.1.2 ✔︎
[00:14:45] [github] ms-vscode.js-debug@1.84.0 ✔︎
[00:14:45] [github] ms-vscode.vscode-js-profile-table@1.0.3 ✔︎
Trace/breakpoint trap
```
# Expected behavior
`./scripts/code.sh` runs successfully on WSL2.

**Comment by hamirmahal** [comment]
Disclaimer: My PC's been acting really weird lately, and this might just be something I'm experiencing in isolation as the result of a hardware issue.

**Comment by hamirmahal** [comment]
![image](https://github.com/microsoft/vscode/assets/43425812/1c9b2dbe-17e2-42a1-a750-a62c08f40f14)

**Comment by hamirmahal** [comment]
The issue also occurs if I try to [build with  `Ctrl+Shift+B`](https://github.com/microsoft/vscode/wiki/How-to-Contribute#build) instead of using `yarn watch`.

**Comment by hamirmahal** [comment]
![image](https://github.com/microsoft/vscode/assets/43425812/f29bbf9b-3097-443b-9abd-30ba5fabd8fe)

**Comment by roblourens** [comment]
> Disclaimer: My PC's been acting really weird lately, and this might just be something I'm experiencing in isolation as the result of a hardware issue.

Seems like we should try to eliminate that?

**Comment by aeschli** [comment]
Sorry, I don't know what causes `Trace/breakpoint trap`. 
Running VS Code from WSL works for me. The display needs to be set, but nowadays that comes by default in WSL. Make sure you have all prerequisites installed as listed in https://github.com/microsoft/vscode/wiki/How-to-Contribute#prerequisites

Closing as non VS Code related
