### ISSUE TITLE
[UX] [Feature-request] Loss of focus due to intrusive hovering element

### ISSUE THREAD

**Issue by cnayan** [microsoft/vscode#196957]
I'm working on Dart application, but this issue can be seen in other languages as well.

1. **Code Actions - Light Bulb placement**
![image](https://github.com/microsoft/vscode/assets/2213067/5ae57ffa-54cd-4c54-a92c-4376ef971ab2)
In this screen grab, you will see the bulb on every array line I move to.
![image](https://github.com/microsoft/vscode/assets/2213067/c110656d-a128-4303-868f-ae5663eeba86)

IMHO, this is too distracting. If a visual element keep moving along very close to with my cursor, which is where my focus is, it is interfering. I use keyboard shortcuts mainly, and I like how Visual Studio places the light bulb to the left most part of the screen.

Proposed solution: Either move to light bulb to the left, near line number (like Visual Studio), or, allow its placement configuration.
![image](https://github.com/microsoft/vscode/assets/2213067/3ea7ca96-31bf-4807-91de-ff6b47539e34)

2. **Pop-ups:**
  a. **Type**: The type of the variable/element is displayed, hovering above the caret location. Most of the time, it overlaps with current line pixels.
![image](https://github.com/microsoft/vscode/assets/2213067/a5502613-fd4f-4261-9b91-7da08dd7a7b8)
  b. **Method signature**: The moment I type open bracket for a method call, couple of pop-ups come up - one for signature (above) and one is drop-down list for auto-completion (below).
![image](https://github.com/microsoft/vscode/assets/2213067/c994b936-a69d-41ba-94d9-06cc1ed90e65)
You can see how much visual interference these hovering pop-up element provide.

Proposed solution: I like how Visual Studio does a better job at managing the hovering elements, which is usually at the bottom of the line being edited.
![image](https://github.com/microsoft/vscode/assets/2213067/f4251b81-570f-41db-a05f-621b47a815ed)

Kindly rethink on the design and if possible, give option to customize the positioning via settings.

**Comment by rajneesh-18** [comment]
Anyone please describe all about the issue in the UX.

**Comment by cnayan** [comment]
I wish the light-bulb is a dismissable object.
Pressing ESC key doesn't make it disappear 😒

**Comment by cnayan** [comment]
Another example of visual elements overlap in focus area:
![image](https://github.com/microsoft/vscode/assets/2213067/4aef1597-f317-4aef-b550-06eb6971ff2d)

Notice how the bulb hovers over text.

**Comment by mjbvz** [comment]
You can set `"editor.lightbulb.enabled": false` if you are distracted by it. Code actions can still be triggered using commands or keyboard shortcuts

**Comment by cnayan** [comment]
@mjbvz You closed the topic, but this is not just about the light bulb. Kindly read the issues.
