### ISSUE TITLE
i can type text on css 

### ISSUE THREAD

**Issue by Kodoiku** [microsoft/vscode#196917]
Type: <b>Feature Request</b>

i try to learn css or even html but i can't write on css, system doesn't find "background" i think i'm on the wrong language but i can't find css, and when i need html i need to go manually on hmtl to select and type in it. sorry for my english....

VS Code version: Code 1.83.1 (f1b07bd25dfad64b0167beb15359ae573aecd2cc, 2023-10-10T23:48:05.904Z)
OS version: Windows_NT x64 10.0.22621
Modes:

**Comment by Kodoiku** [comment]
I attached screenshots, when I type "back" to find background it doesn't appear, same for a color as if I didn't have the right software, I'm a beginner so I can't find the solution De : Martin AeschlimannEnvoyé le :lundi 30 octobre 2023 11:24À : microsoft/vscodeCc : Kodoiku; AuthorObjet :Re: [microsoft/vscode] i can type text on css (Issue #196917) Please provide a small code sample that shows the problem.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by aeschli** [comment]
Pasting your sample in a new `test.css` file shows the following errors:
- `@font-face rule must define 'src' and 'font-family' properties`
- `Unknown property: 'mso-style-priority' and `Unknown property: 'mso-style-type'`

This looks expected. Maybe you are programming in a variant of css?

Also code completion inside a rule body seems to work:
![image](https://github.com/microsoft/vscode/assets/6461412/344dc38f-2844-40b0-a877-14f0e29c1dc4)


So from a VS Code standpoint, all seems to work as expected.

For programming help, I can not help you. Check out stackoverflow or other resources.
