### ISSUE TITLE
css stylesheet comment code block hint syntax error: at-rule or selector expectedcss(css-ruleorselectorexpected)

### ISSUE THREAD

**Issue by kelilive** [microsoft/vscode#196956]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.83.1
- OS Version: Windows 10 22H2 19045.3570

Steps to Reproduce:

**style.css**

**Issue 1:**

#top-menu .tm-icon:hover, #top-menu .tm-icon.open {
    /* background: rgba(0,0,0,0.2) */
}
![image](https://github.com/microsoft/vscode/assets/142982913/83cada70-fb91-4d06-b389-aa969cc0780f)

/* #top-menu .tm-icon:hover, #top-menu .tm-icon.open {
    /* background: rgba(0,0,0,0.2) */
} */
![image](https://github.com/microsoft/vscode/assets/142982913/d5d9ce9a-b41d-4631-9566-1b5bd3814fcf)

**Issue 2:**

.ie-block .browsers li {
    display: inline-block;
    *display: inline;
    *zoom: 1;
    padding: 0 10px;
}
![image](https://github.com/microsoft/vscode/assets/142982913/b49d32b6-aa72-4393-a35a-cd47cb40d49d)
![image](https://github.com/microsoft/vscode/assets/142982913/d6eac0c2-1dce-4559-ac91-a8887f57ba2b)

**Comment by aeschli** [comment]
```
/* #top-menu .tm-icon:hover, #top-menu .tm-icon.open {
/* background: rgba(0,0,0,0.2) */
} */
```
Nested comments is not supported by CSS. Your comment starts on the first line and ends with the first occurrence of `*?`


```
.ie-block .browsers li {
display: inline-block;
*display: inline;
*zoom: 1;
padding: 0 10px;
}
```

`*display` is invalid CSS. It was only used in older versions of IE. You can remove that code.

**Comment by kelilive** [comment]
Thank you!

You mean this style only works on older versions of Internet Explorer right? If `display `and `*display` appear together, the style will work on the next line, right? For newer browsers `*display` doesn't work whether it's written before or after, right?

Because I don't want to change its original stylesheet, the original author, who is also a very good front-end developer, came from a project 10 years ago with a project template called **SuperAdmin 1.0**.
That's why I wanted to lower the warning suppression level of vscode, even though I know it's an outdated style. When I open the file, I see that vscode suggests the change.

Other than that, it would be nice to be able to suppress various warnings (when I don't know how to fix them) in a more flexible way and configure them globally. Instead of referring to **WebStorm**'s complex warning management system, just keep **VS Code** philosophy of simplicity and ease of use, **Visual Studio** will handle it by taking the warning code and passing it through a configuration file, which may not be as rich in detail but is rather more friendly to most developers.

I've searched for **VS Code** and I'm not well versed enough in ide to know what to do. **I'm not sure if there's an option for syntax checking and turning off checking, plus if there's a specific way to manage warning types.** It would be great if you could point me specifically to the relevant help documentation, but if not that's fine too, thank you very much for the above answer.

Best wishes to you!

```css
.ie-block .Ops {
    color: #c20202;
    margin: 10px;
    font-size: 70px;
    text-shadow: 1px 1px 1px #000;
}

.ie-block p {
    font-size: 20px;
    letter-spacing: -.01em;
    color: #ccc;
    width: 960px;
    margin: 0 auto;
}

.ie-block .browsers {
    background: #eee;
    padding: 20px 0;
    list-style: none;
    margin: 30px 0;
}

.ie-block .browsers li {
    display: inline-block;
    *display: inline;
    *zoom: 1;
    padding: 0 10px;
}
```

```html
<!-- Older IE Message -->
<!--[if lt IE 10]>
    <div class="ie-block">
        <h1 class="Ops">Ooops!</h1>
        <p>This Gallery is not supported in older IE browsers. Please update your browser to any of the following,</p>
        <ul class="browsers">
            <li>
                <a href="https://www.google.com/intl/en/chrome/browser/">
                    <img src="img/browsers/chrome.png" alt="">
                    <div>Google Chrome</div>
                </a>
            </li>
            <li>
                <a href="http://www.mozilla.org/en-US/firefox/new/">
                    <img src="img/browsers/firefox.png" alt="">
                    <div>Mozilla Firefox</div>
                </a>
            </li>
            <li>
                <a href="http://www.opera.com/computer/windows">
                    <img src="img/browsers/opera.png" alt="">
                    <div>Opera</div>
                </a>
            </li>
            <li>
                <a href="http://safari.en.softonic.com/">
                    <img src="img/browsers/safari.png" alt="">
                    <div>Safari</div>
                </a>
            </li>
            <li>
                <a href="http://windows.microsoft.com/en-us/internet-explorer/downloads/ie-10/worldwide-languages">
                    <img src="img/browsers/ie.png" alt="">
                    <div>Internet Explorer(New)</div>
                </a>
            </li>
        </ul>
    </div>   
<![endif]-->
```

**Comment by kelilive** [comment]
> Nested comments is not supported by CSS. Your comment starts on the first line and ends with the first occurrence of *?

You gave me the most direct answer, but IDE did not. If the IDE would have been straightforward, I probably wouldn't have come here to submit. In this sense, the parser should be optimized to give multiple explanations of causes when the problem may be caused by multiple factors, it would be more user friendly and not more confusing for the developer.

**Comment by aeschli** [comment]
Sorry, there are no plans to support the (very) old IE star mode that was last used in IE7. IE7 is over 17 years old and has been retired. It is safe to say that IE7 is no longer available for most users.

I take note of your suggestion to detect and warn about nested comments.

**Comment by kelilive** [comment]
Totally understand that it would be better if these could be suppressed.
