### ISSUE TITLE
Language specific settings (e.g. wrap) cannot follow global setting

### ISSUE THREAD

**Issue by SRNissen** [microsoft/vscode#196959]
Type: <b>Feature Request</b>

See also various closed issues on similar-but-not-identical problems e.g.:

- https://github.com/microsoft/vscode/issues/45653
- https://github.com/microsoft/vscode/issues/170180

Steps to Reproduce:

1. Settings UI: Set global wrap to "bounded"
2. Settings UI: Set markdown wrap to "bounded"
3. Settings JSON: delete `"[markdown]"` object
4. Settings UI: Set global wrap to "off"

Actual:

- Global does not wrap
- Markdown wraps

Desired:

- Global does not wrap
- *Markdown also does not wrap*

Underlying issue:

With no rules for markdown in usersettings, VSCode uses the markdown defaultsettings, which contain `wrap:on`.

But I don't want markdown wrap "off", "on", "column" or "bounded" - I want markdown *like everything else.*

Possible solutions in order of preference:

- Additional usersetting "gobal overrides language specific" and "[language]:follow global"
- Additional usersetting "[language]:follow global"
- Additional usersetting "gobal overrides language specific"
- No change.

There are probably more possible solutions that I haven't thought of, and I have not considered `.editorconfig` and workspace specific settings.

VS Code version: Code 1.83.1 (f1b07bd25dfad64b0167beb15359ae573aecd2cc, 2023-10-10T23:45:31.402Z)
OS version: Linux x64 6.5.6-76060506-generic
Modes:

**Comment by sandy081** [comment]
This is as designed. Language override settings always take precedence than settings defined normally. In order to override language specific settings you should override as language specific settings only.

**Comment by SRNissen** [comment]
Of course it is "as designed." That's why I opened this as a feature request and not a bug report.

**Comment by sandy081** [comment]
There are no plans to change this behaviour. Thanks.
