### ISSUE TITLE
Extension 'ms-vsliveshare.vsliveshare-pack' not found.

### ISSUE THREAD

**Issue by devondragon** [microsoft/vscode#196907]
Type: <b>Bug</b>

Summary: the ms-vsliveshare.vsliveshare-pack extension cannot be found when attempting to upgrade it via the command line using --force.

The issue is that the ms-vsliveshare.vsliveshare-pack extension is shown in my extensions list 'code --list-extensions'.  

If I try to use the the command line to upgrade it, it lets me know that v0.4.0 is already installed, and I can use --force to update to the latest version, etc... 

However, when I try to use --force I get an error saying the extension cannot be found.

My console output: 

 >> code --install-extension ms-vsliveshare.vsliveshare-pack                                                                               
Installing extensions...
Extension 'ms-vsliveshare.vsliveshare-pack' v0.4.0 is already installed. Use '--force' option to update to latest version or provide '@<version>' to install a specific version, for example: 'ms-vsliveshare.vsliveshare-pack@1.2.3'.

>> code --force  --install-extension ms-vsliveshare.vsliveshare-pack                                                                       Installing extensions...
Extension 'ms-vsliveshare.vsliveshare-pack' not found.
Make sure you use the full extension ID, including the publisher, e.g.: ms-dotnettools.csharp
Failed Installing Extensions: ms-vsliveshare.vsliveshare-pack

This error was surfaced by running topgrade, which attempts to update all vscode extensions.  

VS Code version: Code 1.83.1 (Universal) (f1b07bd25dfad64b0167beb15359ae573aecd2cc, 2023-10-10T23:46:55.789Z)
OS version: Darwin arm64 23.1.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Max (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|4, 4, 4|
|Memory (System)|64.00GB (0.42GB free)|
|Process Argv|--crash-reporter-id fd22c868-d6c4-4d9a-9743-828e5a9c1d61|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (67)</summary>

Extension|Author (truncated)|Version
---|---|---
codesnap|adp|1.3.4
Bookmarks|ale|13.4.2
aws-toolkit-vscode|ama|1.96.0
markdown-preview-github-styles|bie|2.0.3
path-intellisense|chr|2.8.5
codestream|Cod|14.30.1
gitignore|cod|0.9.0
aws-cloudformation-yaml|Dan|0.2.2
macos-modern-theme|dav|2.3.19
vscode-eslint|dba|2.4.2
vscode-springboot-snippets|dev|1.2.0
java-decompiler|dgi|0.0.3
githistory|don|0.6.20
vscode-html-css|ecm|1.13.1
LogFileHighlighter|emi|2.16.0
json-tools|eri|1.0.2
copilot|Git|1.130.0
copilot-chat|Git|0.8.0
copilot-labs|Git|0.15.1019
vscode-github-actions|git|0.26.2
vscode-pull-request-github|Git|0.74.1
output-colorizer|IBM|0.1.2
java-properties|ith|0.0.2
mysql-syntax|jak|1.3.1
graphql-for-vscode|kum|1.15.3
lambda-snippets|log|1.0.0
javadoc-tools|mad|1.6.0
document|min|2.2.1
theme-monokai-pro-vscode|mon|1.2.1
vscode-docker|ms-|1.27.0
vscode-edge-devtools|ms-|2.1.3
remote-containers|ms-|0.315.1
vsliveshare-pack|ms-|0.4.0
gradle-language|nac|0.2.3
vscode-yaml-sort|Pas|6.5.9
ngrok-for-vscode|phi|1.10.1
material-icon-theme|PKi|4.31.0
vscode-thunder-client|ran|2.14.1
java|red|1.24.0
vscode-xml|red|0.26.1
vscode-yaml|red|1.14.0
ruby-lsp|Sho|0.4.13
even-better-toml|tam|0.19.2
ayu|tea|1.0.5
serverless-ide-vscode|Thr|0.6.1
tab-groups|usa|2.1.1
intellicode-api-usage-examples|Vis|0.2.8
vscodeintellicode|Vis|1.2.30
vscode-boot-dev-pack|vmw|0.2.1
vscode-spring-boot|vmw|1.49.0
vscode-gradle|vsc|3.13.3
vscode-java-debug|vsc|0.54.0
vscode-java-dependency|vsc|0.23.1
vscode-java-pack|vsc|0.25.15
vscode-java-test|vsc|0.40.0
vscode-lombok|vsc|1.1.0
vscode-maven|vsc|0.42.0
vscode-spring-boot-dashboard|vsc|0.13.1
vscode-spring-initializr|vsc|0.11.2
vscode-icons|vsc|12.6.0
gistfs|vsl|0.4.1
vscode-import-cost|wix|3.3.0
eno|Wsc|2.3.53
JavaScriptSnippets|xab|1.8.0
markdown-all-in-one|yzh|3.5.1
json|Zai|2.0.2
material-theme|zhu|3.16.2

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vstes627cf:30244335
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
py29gd2263:30856252
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
3biah626:30602489
89544117:30613380
2i9eh265:30646982
showlangstatbar:30737416
0bi6i642:30841073
a2ce3375:30757347
pythonfmttext:30731395
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
pythonnosmt12:30797651
pythonidxpt:30866567
pythonnoceb:30805159
copilotsettingc:30859502
synctok:30869157
dsvsc013:30795093
dsvsc014:30804076
dsvsc015:30845448
pythontestfixt:30871694
pythonregdiag2:30871582
pyreplss1:30865275
pythoncet0:30874138
2e7ec940:30870395
pythontbext0:30864172

```

</details>

**Comment by sandy081** [comment]
Can you please try `--verbose` flag and share the log with us?

**Comment by devondragon** [comment]
Log output attached.  Thanks!

[vsliveshare.txt](https://github.com/microsoft/vscode/files/13209643/vsliveshare.txt)

**Comment by devondragon** [comment]
Just checking in on this.  I am still getting the same error.

**Comment by sandy081** [comment]
It seems `ms-vsliveshare.vsliveshare-pack` extension does not exist in the Marketplace. So this is expected.
