### ISSUE TITLE
[themes] AutoDarkModeX changed windows theme to dark but VS Code stays in light theme

### ISSUE THREAD

**Issue by update-freak** [microsoft/vscode#196906]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.83.1
- OS Version: Windows 11 (current version)

Steps to Reproduce:

1. Install AutoDarkModeX (v10.4.1.1)
2. Set Auto Detect Color Scheme = enabled
3. VS Code should be open. AutoDarkModeX will now change the windows theme from light to dark or dark to light. When now VS Code is closed and opened again the theme of VS Code is the same as before (and not changed to be the same theme of windows).

=> in this case the theme of VS Code should be the samer as windows

**Comment by update-freak** [comment]
any news on that?

**Comment by aeschli** [comment]
This worked for me.
- VS Code open, dark, Auto Detect Color Scheme = enabled
- AutoDarkModeX (10.4.1.1) changes to light, VS Code changes to light
- Close VS Code, reopen VS Code. VS Code is still light

**Comment by update-freak** [comment]
@aeschli Did you try it over a longer period with multiple switches from dark to light and back?

**Comment by update-freak** [comment]
yesterday I have the strange behaviour that I opened VSCode on the evening (system war dark theme) and then VSCode switched from dark to light theme -> dark theme was here correct

**Comment by update-freak** [comment]
with the current version it seams to be solved. I did not had the problem which I mentioned above several days. Therefore I close this ticket
