### ISSUE TITLE
Testing web extension in vscode.dev does not work anymore (https://code.visualstudio.com/api/extension-guides/web-extensions#test-your-web-extension-in-vscode.dev)

### ISSUE THREAD

**Issue by boltex** [microsoft/vscode#196922]
Does this issue occur when all extensions are disabled?: Yes

Version: 1.83.1 (user setup)
Commit: f1b07bd25dfad64b0167beb15359ae573aecd2cc
Date: 2023-10-10T23:48:05.904Z
Electron: 25.8.4
ElectronBuildId: 24154031
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.19045

Steps to Reproduce:

1. clone any sample extension from https://github.com/microsoft/vscode-extension-samples made for the web, such as [helloworld-web-sample](https://github.com/microsoft/vscode-extension-samples/tree/main/helloworld-web-sample),  and **add at least one custom svg icon for a command in the package.json** file, or some **other resource file used by a webview**.
2. Compile and start your extension with this method to test it on vscode.dev: https://code.visualstudio.com/api/extension-guides/web-extensions#test-your-web-extension-in-vscode.dev
3. Notice that the icons or other resources fail to show up as they did a few weeks ago. (console shows The FetchEvent for "https://localhost:5000/resources/dark/box00.svg" resulted in a network error response: Cross-Origin-Resource-Policy prevented from serving the response to the client. and similar messages for the extensions inner resources)

**I've been using this method of testing my extension many times in the past few years, and now it stopped working somewhere in the past few weeks.**
(See below for BEFORE / AFTER screenshots)

![image](https://github.com/microsoft/vscode/assets/847716/f76eedd7-ee1b-46d1-93fb-5690ab0c96cf)

Here's the before screenshot:
![image](https://github.com/microsoft/vscode/assets/847716/0fe3c136-d0e8-476a-a403-301a1818ecbb)

But now it looks like this (notice icons lacking in the sidebar menu on the left and the webview on the right is also lacking css and images):
![image](https://github.com/microsoft/vscode/assets/847716/fa8f7afd-8ba8-4700-a7f3-ca723130e228)

**Comment by mjbvz** [comment]
The errors tell you the issue: the [`Cross-Origin-Resource-Policy` header](https://developer.mozilla.org/en-US/docs/Web/HTTP/Cross-Origin_Resource_Policy) is missing. Cross origin isolation was turned on in VS code 1.83: https://code.visualstudio.com/updates/v1_83#_vscodedev-is-now-cross-origin-isolated

On your local development server, just make sure any webview content is served  `Cross-Origin-Resource-Policy: cross-origin`. Different development servers have different ways of setting this but usually you can set it using either a command line flag or configuration file

**Comment by boltex** [comment]
@mjbvz Thanks! :) but this info should be noted on the https://code.visualstudio.com/api/extension-guides/web-extensions#test-your-web-extension-in-vscode.dev section with more details. (I for one, have no idea how to go about doing what you suggested)

**Comment by boltex** [comment]
@mjbvz Thanks to your guidance, I've found the solution: as you said the Cross-origin-Resource-Policy header is now required, and the `--cors `option is not enough anymore when launching the `npx serve` command.  **_(IT SHOUD BE ADDED TO THE DOCUMENTATION)_**

A serve.json file with this content needs to be present at the base of your extension being served, _perhaps also enter it's name to your .gitignore file_ : 
```
{
    "headers": [
        {
            "source": "**",
            "headers": [
                {
                    "key": "Cross-Origin-Resource-Policy",
                    "value": "cross-origin"
                },
                {
                    "key": "Access-Control-Allow-Origin",
                    "value": "*"
                }
            ]
        }
    ]
}
```

**Comment by boltex** [comment]
@mjbvz oops I meant '.vscodeignore' file.
