### ISSUE TITLE
Display Welcome Page only when opening a new Window

### ISSUE THREAD

**Issue by rebornix** [Microsoft/vscode#19691]
- VSCode Version: 1.9.0-Insiders
- OS Version: macOS

Steps to Reproduce:

1. Enable Welcome Page
2. Open a new Window

When the window is launched, Code will open an untitled file first and then open the Welcome Tab. Since the Welcome Page is active and introductory, we don't need necessarily open the untitled file at the beginning while we can put a `new file` action in the Welcome Page *Start* section

![screen shot 2017-02-01 at 1 24 39 pm](https://cloud.githubusercontent.com/assets/876920/22526880/d009d9ae-e881-11e6-9aa8-f08c3215f9d1.png)

**Comment by chrmarti** [comment]
Tracked with #19689
