### ISSUE TITLE
Expose icon identifier for language icon

### ISSUE THREAD

**Issue by pokey** [microsoft/vscode#196986]
It would be great if we could use language icons. For example, in a tree view, I'd like to be able to set the icon for a tree item to the icon of the language for the active editor, eg

```ts
   this.iconPath = new ThemeIcon(`lang-${window.activeTextEditor.document.languageId}`);
```

**Comment by aeschli** [comment]
The file icon theme is in charge of providing icons for file types, names or the file language.
If you want to use a file icon theme in your tree, you can do so by setting the resourceUri on the tree item and setting `ThemeIcon.File` as icon. You are then consistent in what is shown in the explorer or in the editor.

Now, we have language icons, that are defined by languages, but these are just fallbacks if a file icon theme does not have an icon for the given language. Only few languages define theme, typically the more exotic languages.

So I think the right approach is to use the file icon as explained above

**Comment by pokey** [comment]
If the tree item doesn't correspond to a file, what should I use for the resource uri? If I use the uri of the active editor, then the tree item will turn red if the editor has errors, which is not what I want, because the icon doesn't represent the current editor.

For what it's worth, we'd like to use this for indicating that certain scopes in Cursorless are language-specific. See https://github.com/cursorless-dev/cursorless/issues/1982

**Comment by aeschli** [comment]
You can make up a resource URI. Give it a custom scheme to won't get errors. All that matters is the file name and the path.
That's what the VS Code language picker does as well.

**Comment by pokey** [comment]
Huh ok, so I just need to use the correct file extension on the dummy resource URI? How do I know which file extension to use for a given language id?

**Comment by aeschli** [comment]
Youi can come up with list, or use the trick described in https://github.com/cursorless-dev/cursorless/issues/1982#issuecomment-1788814711

**Comment by pokey** [comment]
Ah cool I couldn't make heads or tails of that code snippet so figured I'd ask here. I'm surprised that doesn't miss built-in languages; looks like it's just reading extensions, but I just wired it up in https://github.com/cursorless-dev/cursorless/pull/2006 and it's working great! Up to you I guess what to do with this issue; feels like a hack but the hack works so 🤷

Thanks for your help!
