### ISSUE TITLE
When will the inline chat API be available in the released VS Code?

### ISSUE THREAD

**Issue by luhc228** [microsoft/vscode#196935]
Hello! I am a VS Code extension developer. I want to use the inline chat API on my extension to chat with GPT in TextEditor, just like github-copilot-chat extension. When will the inline chat API be available in the released VS Code? Why the github-copilot-chat can use the proposal api in released VS Code? 

https://github.com/microsoft/vscode/blob/c9e43572d1f938cec80c1c26200092c01b2dce2e/src/vscode-dts/vscode.proposed.interactive.d.ts

Releated [issue](https://github.com/microsoft/vscode/issues/193334)

**Comment by jrieken** [comment]
We cannot say when the API is ready for finalization. This is usually a lengthy process because we don't change API once it has shipped. For inline chat significant changes are on the radar, e.g might be replaced with the chatAgent2 proposal.

**Comment by icnahom** [comment]
How is the GitHub Copilot extension providing this feature?

**Comment by Zane-XY** [comment]
> We cannot say when the API is ready for finalization. This is usually a lengthy process because we don't change API once it has shipped. For inline chat significant changes are on the radar, e.g might be replaced with the chatAgent2 proposal.

@jrieken what is `chatAgent2 proposal`, can I read it somewhere?
