### ISSUE TITLE
Extension list does not always load

### ISSUE THREAD

**Issue by varnk** [Microsoft/vscode#19695]
- VSCode Version: Code 1.8.1 (ee428b0eead68bf0fb99ab5fdc4439be227b6281, 2016-12-19T14:49:23.350Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions:

|Extension|Author|Version|
|---|---|---|
|code-gnu-global|austin|0.2.1|
|cpptools|ms-vscode|0.10.0|
|csharp|ms-vscode|1.6.2|
|qub-xml|qub|0.3.0|

---
This is an intermittent problem.  Sometimes it works and sometimes it doesn't.
Steps to Reproduce:

1.  Clock on Extensions
2.  Select Popular (or any other extension list to load from internet)
3.  List does not populate

**Comment by joaomoreno** [comment]
Are you behind a proxy?

**Comment by varnk** [comment]
Sorry.  I didn't get a notification for you response.  The answer to your question is... yes, I am behind a firewall.  However, I have provided proxy information and logon information in Code.  Still, sometimes the list doesn't load.

**Comment by joaomoreno** [comment]
#22214
