### ISSUE TITLE
Activation `onCommand` sometimes never returns when there are multiple extension hosts

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#196969]
I have only seen this in Codespaces so far. In short, this promise never completes:

https://github.com/microsoft/vscode/blob/61bc7a3db659af6acc29e715a8ba840e3c892144/src/vs/workbench/services/commands/common/commandService.ts#L71-L72

I was able to debug a little, and it seems that one of the extension host manager never completes the `activateByEvent` call:

https://github.com/microsoft/vscode/blob/61bc7a3db659af6acc29e715a8ba840e3c892144/src/vs/workbench/services/extensions/common/abstractExtensionService.ts#L909

https://github.com/microsoft/vscode/blob/61bc7a3db659af6acc29e715a8ba840e3c892144/src/vs/workbench/services/extensions/common/extensionHostManager.ts#L359-L371

This issue doesn't reproduce every time. So far, I've only reproduced the issue on Codespaces that were recently started, but of the 3 test setups I've made, it has repro'd in each one after the codespace was restarted.

**Comment by alexr00** [comment]
Two ways I've repro'd so far:
1. Restart or start a currently stopped Codespace
2. Make a change in a file
3. Stage the file in the git SCM view

1. Restart or start a currently stopped Codespace associated with a PR that has comments from you
2. Expand a comment and use the pencil icon to edit the comment

**Comment by alexdima** [comment]
After debugging together, we have found that the web worker extension host was terminated, but it looks like the code is not aware of this, so it keeps trying to communicate with the defunct web worker extension host.

**Comment by alexr00** [comment]
Screenshot of threads while debugging:

![image](https://github.com/microsoft/vscode/assets/38270282/3e616960-85d0-4fa6-a93a-3a4269088186)

It should actually look like this:

![image](https://github.com/microsoft/vscode/assets/38270282/c88661c0-2dd9-42d0-95e6-a1615987e6ad)

You can see that there's a weird empty thread in and there's no webworker iframe or extension host.

**Comment by alexr00** [comment]
I spent about 10 minutes try to repro and couldn't. Marking as verified.

**Comment by alexr00** [comment]
Reopening as I saw this again.
