### ISSUE TITLE
"Go" menu doesn't disappear when the cursor moves away from the "go" menu

### ISSUE THREAD

**Issue by amberUCP** [microsoft/vscode#196987]
Type: <b>Bug</b>

When I'm using VS Code and the mouse hovers over the "Go" button on the top menu, the drop down appears and remains there even after the mouse has long moved. I have to change the UI to make it useable. Closing the entire application and re-starting is the only thing that makes the menu go away, and it appears again if the mouse goes over the button!: 
![vscodebug](https://github.com/microsoft/vscode/assets/145543558/56100306-771d-40b4-bf40-7929e6fa0b21)

VS Code version: Code 1.83.1 (Universal) (f1b07bd25dfad64b0167beb15359ae573aecd2cc, 2023-10-10T23:46:55.789Z)
OS version: Darwin arm64 23.0.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|4, 3, 3|
|Memory (System)|16.00GB (0.07GB free)|
|Process Argv|--crash-reporter-id 91b3cd62-7c6c-4786-a205-b7a395510161|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (39)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-openapi|42C|4.18.6
swagger-viewer|Arj|3.1.2
azurite|Azu|3.27.0
vscode-node-readme|ben|3.0.2
simple-react-snippets|bur|1.2.7
toggle-format-on-save|cbr|0.2.0
vscode-eslint|dba|2.4.2
gitlens|eam|14.4.1
vscode-npm-script|eg2|0.3.29
prettier-vscode|esb|10.1.0
kotlin|fwc|0.2.32
terraform|has|2.28.2
vscode-test-explorer|hbe|2.21.1
plantuml|jeb|2.17.5
vscode-nuget-package-manager|jmr|1.1.6
csharpextensions|kre|1.7.3
markdown-formatter|mer|0.9.7
azure-pipelines|ms-|1.228.0
vscode-azureresourcegroups|ms-|0.7.5
vscode-logicapps|ms-|1.2.9
vscode-dotnet-runtime|ms-|1.8.1
playwright|ms-|1.0.16
azure-account|ms-|0.11.6
live-server|ms-|0.4.11
test-adapter-converter|ms-|0.1.8
vsliveshare|ms-|1.0.5883
gradle-language|nac|0.2.3
abracadabra|nic|9.0.2
hocus-pocus|nic|1.7.0
emoji|Per|1.0.1
java|red|1.24.0
vscode-yaml|red|1.14.0
vscode-gradle-extension-pack|ric|0.0.4
vscode-coverage-gutters|rya|2.11.0
intellicode-api-usage-examples|Vis|0.2.8
vscodeintellicode|Vis|1.2.30
vscode-gradle|vsc|3.13.3
vscode-java-debug|vsc|0.54.0
vscode-java-test|vsc|0.40.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
py29gd2263cf:30856253
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
3biah626:30602489
89544117:30613380
showlangstatbar:30737416
a2ce3375:30757347
pythonfmttext:30731395
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
pythonnosmt12:30797651
pythonidxpt:30866567
pythonnoceb:30805159
copilotsettingt:30859503
synctok:30869157
dsvsc013:30795093
dsvsc014:30804076
dsvsc015:30845448
pythontestfixt:30871694
pythonregdiag2:30871582
pyreplss1:30865275
pythoncet00cf:30874137
2e7ec940:30870395
pythontbext0:30864172

```

</details>

**Comment by sbatten** [comment]
This is a native menu, so it appearing and disappearing is controlled by the OS. Please let me know if I misunderstand.
