### ISSUE TITLE
[Debug] Console HTTP links match incorrectly

### ISSUE THREAD

**Issue by userpixel** [Microsoft/vscode#197]
VS Code show the following output in the console:

![image](https://cloud.githubusercontent.com/assets/835750/11268334/9579a9c6-8eb0-11e5-87e8-1b1a45eb932c.png)

Google Chrome shows this one:

![image](https://cloud.githubusercontent.com/assets/835750/11268351/a42f7252-8eb0-11e5-9ea7-7bd2ff67788e.png)

The source code links are not matched correctly in the VS Code, therefore when I click on the first link for example, VC Code tries to access a file on drive `p:/` which obviously doesn't exist:

![image](https://cloud.githubusercontent.com/assets/835750/11268405/da189d94-8eb0-11e5-8b44-1459d0985191.png)

**Comment by isidorn** [comment]
@bpasero our link detection is failing here. Can we improve it to handle this case?

**Comment by bpasero** [comment]
The detection currently works only for file paths and not for http links. But we can beef it up I think. However, if we move the repl to an editor, we would benefit from automatic link detection imho.

**Comment by GordonSmith** [comment]
Bonus Points - enable markdown formatting in console outputs?

**Comment by isidorn** [comment]
That is a seperate feature request - which relies heavly on https://github.com/Microsoft/vscode/issues/11462

**Comment by TeknoloGenie** [comment]
Any progress on this?

**Comment by isidorn** [comment]
There are plans to investigate into improving this in the January milesonte. But no progress at the moment

**Comment by weinand** [comment]
@isidorn I suggest to include this in the work already done for #17085

**Comment by isidorn** [comment]
fyi @michelkaporin

**Comment by michelkaporin** [comment]
Update: HTTP links will not be incorrectly matched now per #17085 PR, however not yet navigable.

**Comment by isidorn** [comment]
Dup of https://github.com/Microsoft/vscode/issues/34026

**Comment by auchenberg** [comment]
We are tracking the sourcemapping of file paths on exceptions here, https://github.com/Microsoft/vscode-chrome-debug-core/issues/235
