### ISSUE TITLE
Add " ctrl + shift + T " , shortcut to reopen recently closed files, like in chrome and sublime text.

### ISSUE THREAD

**Issue by pixieaka** [Microsoft/vscode#19703]

**Comment by Maktm** [comment]
I'm pretty certain this feature already exists on Version 1.8.1 (if not on earlier version).

**Comment by pixieaka** [comment]
i close file from ctrl + w ,, and after this i press ctrl + shift + T  and it not working

plus in sublime text and chrome this shortcut open all history tabs but in visual studio code it just open recent file only if i press it again it not open the previous tabs

**Comment by pixieaka** [comment]
please give the ctrl + shift + T shortcut try in sublime text first to know what i mean

**Comment by pixieaka** [comment]
or you just try it on google chrome this shortcut open all history tabs not only the last closed file

**Comment by pixieaka** [comment]
yeah when i close the tab from "X" in tab it working,, but when i just close it from " ctrl + w " it not working, it just show me the last file i have been closed from the "X" in tab.

**Comment by pixieaka** [comment]
yeah when i close the tab from "X" in tab it working,, but when i just close it from " ctrl + w " it not working, it just show me the last file i have closed from the "X" in tab.

**Comment by pixieaka** [comment]
yeah when i close the tab from "X" in tabs bar it working,, but when i just close it from " ctrl + w " it not working, it just show me the last file i have closed from the "X" in tabs bar.

**Comment by pixieaka** [comment]
yeah when i just open the file without any edit it not working it just open edited files only

**Comment by pixieaka** [comment]
yeah when i just open the file and close it without any edit it not save in history. this what i'm taking about

and in sublime text also when i close the whole program and open it again it save recent tabs but in @code  it clear the history when i close the software

**Comment by pixieaka** [comment]
yeah when i just open the file and close it without any edit it not save in history. this what i'm taking about

and in sublime text also when i close the whole program and open it again it save recent tabs but in @code it clear the history when i exit the @code and reopened.

**Comment by pixieaka** [comment]
yeah when i just opened the file and close it without any edit it not save in history. this what i'm taking about

and in sublime text also when i close the whole program and open it again it save recent tabs but in @code it clear the history when i exit the @code and reopened.

**Comment by pixieaka** [comment]
yeah when i just opened the file and close it without any edit it not save in history. this what i'm taking about

and in sublime text also when i close the whole program and open it again it save recent tabs but in @code it clear the history when i exit from the @code and reopen it again.

**Comment by pixieaka** [comment]
yeah when i opened the file and close it without any edit it not save in history. this what i'm taking about

and in sublime text also when i close the whole program and open it again it save recent tabs but in @code it clear the history when i exit from the @code and reopen it again.

**Comment by pixieaka** [comment]
yeah it already exists but the problem is when i opened the file and close it without any edit it not save in history. this what i'm taking about

and in sublime text also when i close the whole program and open it again it save recent tabs but in @code it clear the history when i exit from the @code and reopen it again.

**Comment by bpasero** [comment]
Try with  `"workbench.editor.enablePreview": false`
