### ISSUE TITLE
Debug console filter box is not wide enough to read placeholder

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#197072]
In the Korean language pack several characters are cut off and the input is not resizable. ![image](https://github.com/microsoft/vscode/assets/2193314/a8e38feb-93a4-4f1e-9e63-36d99cfaf9ae)
![image](https://github.com/microsoft/vscode/assets/2193314/232525ab-bd61-4862-8fd2-0cb52dc1d4df)

Additionally the hover does not include the history hint:

![image](https://github.com/microsoft/vscode/assets/2193314/fc502345-2390-4fcd-a34e-35fc075399f8)

**Comment by roblourens** [comment]
Do you think it's enough to fix the hover? It does change its width based on the window size at least.

**Comment by Tyriar** [comment]
Yeah I think that's enough since it doesn't happen in English
