### ISSUE TITLE
Add "(Administrator)" suffix to window title when running as administrator in Windows

### ISSUE THREAD

**Issue by daviwil** [Microsoft/vscode#19707]
- VSCode Version: 1.8.1, 1.9.0-insiders
- OS Version: Windows 10 Anniversary

Steps to Reproduce:

1. Run VS Code / Insiders as administrator by right-clicking the icon and clicking "Run as Administrator"
2. Observe window title does not indicate that Code is running as administrator

Since running as administrator works pretty well now, the only thing that's missing is an indication that the window has been run as administrator.  Visual Studio (and other apps) use the title bar to indicate this:

![image](https://cloud.githubusercontent.com/assets/79405/22539525/6f8c8ce0-e8cf-11e6-885f-720ea355c7f5.png)

**Comment by arkon** [comment]
I was hoping to work on this issue and I figured out how to implement it, but it seems that translation strings need to be modified, which are [seemingly done by a third party](https://github.com/Microsoft/vscode/issues/4109).

The suffix would need to be added within [this block](https://github.com/Microsoft/vscode/blob/ef2d41293d766e2554245e3f887d4e39b27ac819/src/vs/workbench/services/history/browser/history.ts#L240), and using [some method](http://stackoverflow.com/a/37670360) to determine if the application is being run with Admin privileges.

I suppose this would need to be implemented by the VS Code team?

**Comment by bpasero** [comment]
@arkon I think the biggest issue is that I am not sure how to find out that VS Code runs as "Admin". If someone has an idea, I am happy to add it 👍

**Comment by arkon** [comment]
@bpasero I linked to a StackOverflow thread about that previously that should work: http://stackoverflow.com/a/37670360

**Comment by bpasero** [comment]
Ugly. Imho this should go into either a native node module or better, into [Electron](https://github.com/atom/electron) itself (`process.isElevated`).

**Comment by arkon** [comment]
Maybe we should request it upstream for Electron to expose functions to check if we're running as administrator (Windows) or root (UNIX)?

**Comment by bpasero** [comment]
We can, but only with a PR 👍

**Comment by arkon** [comment]
@bpasero Seems like they might favour users using a separate node module for checking for elevated privileges rather than having it implemented as part of Electron (https://github.com/electron/electron/pull/8980#issuecomment-289514100).

**Comment by arkon** [comment]
Since they suggested [is-elevated](https://github.com/sindresorhus/is-elevated), I suppose we could use that here?

**Comment by bpasero** [comment]
Last time I checked these modules seem to spawn a process on Windows at least? That is not a solution I would want. A module should use some native code to find out if the user is Admin or not.

**Comment by arkon** [comment]
Hmm, perhaps you could voice your opinion on that electron thread then?

**Comment by bpasero** [comment]
@arkon sorry I missed your reference to that PR, it looks very cool. Any reason you could not make that a native module? VS Code would use it right away.

**Comment by arkon** [comment]
@bpasero Is "native module" referring to [this](https://nodejs.org/api/addons.html)?

**Comment by bpasero** [comment]
@arkon exactly! since you already did the hard part of writing the C code, putting this to a native module is not a lot of work imho. See for example this module that we are using which does that: https://github.com/the-ress/node-windows-foreground-love

**Comment by arkon** [comment]
@bpasero Ah, I see! I'll try my hand at making a native module then.

**Comment by bpasero** [comment]
Awesome 👍

**Comment by arkon** [comment]
I've published [native-is-elevated](https://github.com/arkon/native-is-elevated) to NPM.

**Comment by bpasero** [comment]
Thanks, I will look into this for April!

**Comment by daviwil** [comment]
Awesome, nice work @arkon!

**Comment by bpasero** [comment]
I played around with the library and noticed that on Windows calling into the module can take 32ms (on my fast macbook pro, running in a VM). Given our performance work we are doing I am feeling not so easy adding this to the startup. I also noticed that the library is not needed on mac or linux where finding out if the user is root or not is [`very easy`](https://github.com/Microsoft/vscode/blob/ben/electron/src/vs/base/common/platform.ts#L50).

I think what we can do is the following:
* only install the module on Windows by making it windows dependent and an optional dependency (similar to our use of [`windows-foreground-love`](https://www.npmjs.com/package/windows-foreground-love))
* call into it delayed after the critical startup path is left (similar to how we check for integrity only after a [timeout](https://github.com/Microsoft/vscode/blob/ben/electron/src/vs/platform/integrity/node/integrityServiceImpl.ts#L134))

**Comment by arkon** [comment]
Would it help if [native-is-elevated](https://github.com/arkon/native-is-elevated)'s `isElevated()` function were to return a promise?

**Comment by bpasero** [comment]
@arkon good point, maybe not a promise but a typical function callback, as with other functions in node that are long running.

Though could you actually implement that because it seems your call in C land is sync?

**Comment by arkon** [comment]
@bpasero It ought to be possible. I found [this example](https://gist.github.com/bellbind/b69c3aa266cffe43940c) of using promises, and it seems like [Nan](https://github.com/nodejs/nan) could be useful for implementing callbacks. I'll give it a shot.

**Comment by bpasero** [comment]
Yeah thats what I think too. That is why my initial reaction was to call this method only after a delay. I can look into it, actually requiring the module is not what takes time, it is calling into that method so we can probably keep that module on all platforms.

**Comment by rwatts3** [comment]
I'm noticing some fallout that may be related to this issue. 
I am receiving a popup saying it is not safe to run insiders as an administrator, and it states in the title bar that i'm running as an administrator, even though I didn't choose "Run As Administrator" when I started the program. I can confirm that I have opened insiders normally as I did prior to this release , however I can not find a way to deactivate the warning notification.

**Comment by bpasero** [comment]
Yeah maybe it is too aggressive to show this on Windows where it is more likely that you run as admin. I can take it out again.

**Comment by bpasero** [comment]
**Verification:**
Run Code as Administrator on Windows and verify that the title includes the information that you are running as admin.

**Comment by ramya-rao-a** [comment]
@bpasero Any reason we are going with the square brackets [] instead of the normal ones () ?

![image](https://user-images.githubusercontent.com/16890566/35652395-4735f726-0698-11e8-92be-e681701f0124.png)

**Comment by bpasero** [comment]
@ramya-rao-a no, I just picked that style up from the other decorations we had ("Unsupported" and "Extension Development Host"). 

![image](https://user-images.githubusercontent.com/900690/35663577-3bcbfae4-071e-11e8-9b4a-014a78e9ee34.png)

**Comment by ramya-rao-a** [comment]
got it
