### ISSUE TITLE
Thick Consolas Font

### ISSUE THREAD

**Issue by Maktm** [Microsoft/vscode#19705]
- VSCode Version: 1.8.1
- OS Version: Windows 7 Ultimate Service Pack 1

Steps to Reproduce:

1. Open VS code using the Dark/Dark+ themes
2. Compare the font to the one Visual Studio renders

Here's a side-by-side comparison:

VS Code vs. Visual Studio:

![VS Code Consolas Font](http://i.imgur.com/qdasKWA.png) ![](http://i.imgur.com/7YOkCK3.png)

Notice how Visual Studio's rendered version is thinner.

I tried setting the weight of the font using `editor.fontWeight` and setting it to the lowest possible value (100) but it's the same (surprisingly even for values 200, 300 etc.). This [issue](https://github.com/Microsoft/vscode/issues/381url) has been referenced before but has produced no results and so I'm creating this issue to see if someone can get it fixed.

**Comment by alexandrudima** [comment]
All font rendering is ultimately handled by Chromium. There is no code change that we could do AFAIK. 

Perhaps you can log an issue or find an existing one on their issue tracker -- https://bugs.chromium.org/p/chromium/issues/list

**Comment by alexandrudima** [comment]
This is an upstream issue (possibly within Chromium), and there are no known workarounds that we could implement on our side. This means there is no possible code change for us to do in VS Code sources to improve things. 

To keep the number of issues in our inbox at a manageable level, we’re closing issues that have been on the backlog for a long time but haven’t gained traction or that are not actionable. Thank you for your time and understanding.

**Comment by Maktm** [comment]
I've reported this to chromium and the team couldn't reproduce this.
https://bugs.chromium.org/p/chromium/issues/detail?id=788922#c2
