### ISSUE TITLE
CPU Usage spikes with Antimalware Service Executable

### ISSUE THREAD

**Issue by larqitos** [Microsoft/vscode#19702]
- VSCode Version: Code 1.8.1 (ee428b0eead68bf0fb99ab5fdc4439be227b6281, 2016-12-19T14:49:23.350Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

CPU Gets consumed up to 100% with no end in sight. 
![cpuconsumption](https://cloud.githubusercontent.com/assets/6106448/22533309/4b40e836-e8bb-11e6-801e-595eb61fd73a.png)

Steps to Reproduce:

1. Open Visual Studio Code
2. Open a folder with lots of folders in visual studio code
3. Disco

**Comment by bpasero** [comment]
To find out more about this issue, we need to get at the process that is causing the high load. VS Code creates multiple processes, each with different tasks. Depending on your OS you can get at the full command line of the process and paste it here. On Mac, the **Activity Monitor** allows to find the `PID` of the process and from a terminal `ps aux | grep <pid>` reveals its arguments. 

![image](https://cloud.githubusercontent.com/assets/900690/18907063/65806550-856a-11e6-8b2e-83da9111445d.png)

On Windows a tool like **[Process Explorer](https://technet.microsoft.com/en-us/sysinternals/processexplorer.aspx)** helps:

![image](https://cloud.githubusercontent.com/assets/900690/18907037/476f0aa8-856a-11e6-8ac3-4c1f3e803f32.png)

Once you have the information please update this issue with it. Thanks!

**Comment by larqitos** [comment]
Sure I went ahead and ran process explorer and here is the offending process. 7252 I am including a screenshot. It consumes anywhere from 32-64% of the CPU and the rest is consumed by the anti malware service on my windows machine. 
![process](https://cloud.githubusercontent.com/assets/6106448/22560386/62a90940-e942-11e6-878b-eab512ba2265.png)

**Comment by larqitos** [comment]
After seeing it was related to the extension host I realized that its probably an issue with an extension I am running and sure enough as soon as I disabled the offending extension problem solved. Thanks for the help. 
![extension](https://cloud.githubusercontent.com/assets/6106448/22560578/264df34c-e943-11e6-8edd-1a585e82570b.png)

**Comment by bpasero** [comment]
Reading your description it seems that the issue originates from an extension and not VS Code itself. Thereby I will close this issue and kindly ask you to report this issue against the extension repository. 

Most extensions are on GitHub as well so it should be easy to file it against the extension. If you open an extension on the market place, click on the **Support** link to find out more.

<img width="196" alt="screen shot 2016-05-05 at 12 51 17" src="https://cloud.githubusercontent.com/assets/900690/15041943/263e2282-12c0-11e6-9a33-d2b3b500d61b.png">

Thanks again for your feedback!

**Comment by stereokai** [comment]
@larqitos how did you find the offending extension?

**Comment by stereokai** [comment]
@bpasero is there any resource with tips on finding performance-inhibiting extensions?
