### ISSUE TITLE
Do not auto update extensions that do not contain code to a version that has code

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#197022]
If an extension that does not have code wants to update to a new version that contains code we should explicitly ask the user if this is ok for them. With a warning dialog.

Example: user installs a theme, and two months later that Theme wants to ship some code. User should be prompted.

**Comment by alefragnani** [comment]
Hi @isidorn ,

This is a great idea, and I think that a similar warning could be displayed in other two scenarios

* if an extension adds new dependencies (`extensionDependencies` entry)
* if an extension pack receives new extensions

Thank you

**Comment by isidorn** [comment]
Closing as done, as now there is a dialog warning the user when extension updates from no-code to code.
