### ISSUE TITLE
add linux bash support in inbuilt terminal of VSCoDE 

### ISSUE THREAD

**Issue by veerendra-nath** [Microsoft/vscode#19708]
in inbuilt terminal of vscode the , if wish to enter the bash console (Linux bash is added in windows 10.1607 version) its says bash command not found, 
all other commands works well but bash 👎

**Comment by Tyriar** [comment]
See the documentation for how to configure this https://code.visualstudio.com/docs/editor/integrated-terminal#_configuration, namely adding this to your settings.json file:

```js
// Bash on Ubuntu (on Windows)
"terminal.integrated.shell.windows": "C:\\Windows\\sysnative\\bash.exe"
```

**Comment by veerendra-nath** [comment]
thank you!! 👍
