### ISSUE TITLE
Diff editor doesn't seem to scroll to first diff anymore

### ISSUE THREAD

**Issue by rzhao271** [microsoft/vscode#197019]
On the latest Insiders on Windows, I'm noticing that after editing a file, when I want to view the diff of the file by clicking on it in the SCM view, the diff editor doesn't seem to automatically scroll to the first diff anymore.

I'm wondering whether this is a regression or an intentional change?
Also let me know what logs I can add to this issue to help debug.

**Comment by hediet** [comment]
Cannot reproduce:



![Image](https://github.com/microsoft/vscode/assets/2931520/9941c612-2955-4ced-a5ae-cb56e0cecb85)

**Comment by rzhao271** [comment]
I haven't seen it recently either
Closing
