### ISSUE TITLE
Consider editor associations when opening notebook results in search

### ISSUE THREAD

**Issue by andreamah** [microsoft/vscode#197088]
As discussed in https://github.com/microsoft/vscode/pull/192358, we should consider editor associations when deciding whether to open the result as a notebook in notebook search.

**Comment by andreamah** [comment]
To verify, enable `search.experimental.closedNotebookRichContentResults` and:

1. Add to `workbench.editorAssociations`:
```
  "workbench.editorAssociations": {
    "*.ipynb": "default"
  },
 ```
2. Search for something in an ipynb file that only shows up in the raw text (ie: `"cell_type":`). The result should appear in the search.
3. Remove the setting and rerun the search.
4. The result shouldn't be there anymore.

**Comment by joyceerhl** [comment]
After I remove the setting and rerun the search I still see results from the raw JSON

**Comment by andreamah** [comment]
Hmm, I can't seem to repro on the latest main. Closing.
