### ISSUE TITLE
Cannot use Visual Studio Code (mssql extension) to connect to Azure SQL Data Warehouse

### ISSUE THREAD

**Issue by kevinvngo** [Microsoft/vscode#19700]
- VSCode Version: Code 1.8.1 (ee428b0eead68bf0fb99ab5fdc4439be227b6281, 2016-12-19T14:49:23.350Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

|Extension|Author|Version|
|---|---|---|
|mssql|ms-mssql|0.2.0|

---

Steps to Reproduce:

1.  Ctrl + shift + p
2.  Connect to database
3.  Connect to an Azure SQL Data Warehouse instance
     FAILS WITH: ..."Incorrect syntax near 'ANSI_NULLS'. (image attached)

Note: connecting to just the logical server and master works 

![image](https://cloud.githubusercontent.com/assets/15145589/22531717/95d78356-e897-11e6-9340-b8d569de9874.png)

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/vscode-mssql#667
