### ISSUE TITLE
Add Pinning

### ISSUE THREAD

**Issue by Linxford** [microsoft/vscode#197045]
It will be of great use, if we can pin some important files or folders in the panel while coding for easy access

**Comment by gjsjohnmurray** [comment]
For files, are you familiar with the pinned tabs feature?

https://code.visualstudio.com/docs/editor/custom-layout#_pinned-tabs

**Comment by gjsjohnmurray** [comment]
Previously #76302, which points to #76904

**Comment by gjsjohnmurray** [comment]
Did you try using an extension such as https://marketplace.visualstudio.com/items?itemName=howardzuo.vscode-favorites?
