### ISSUE TITLE
Can't download C/C++ plus

### ISSUE THREAD

**Issue by savent404** [Microsoft/vscode#19704]
- VSCode Version: Code 1.8.1 (ee428b0eead68bf0fb99ab5fdc4439be227b6281, 2016-12-19T14:49:23.350Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

|Extension|Author|Version|
|---|---|---|
|code-gnu-global|austin|0.2.1|
|githistory|donjayamanne|0.1.5|
|CppSnippets|hars|0.0.6|
|vscode-clang|mitaki28|0.2.1|
|cpptools|ms-vscode|0.10.0|
|language-vscode-javascript-angular2|nwallace|0.0.11|
|MDTools|seanmcbreen|1.0.0|
|python|tht13|0.2.3|

---

Steps to Reproduce:

1. This is the output:
Updating C/C++ dependencies...
Downloading package 'C/C++ language components (Windows)' Failed at stage: downloadPackages
Error: read ECONNRESET
Finished

**Comment by bpasero** [comment]
Reading your description it seems that the issue originates from an extension and not VS Code itself. Thereby I will close this issue and kindly ask you to report this issue against the extension repository. 

Most extensions are on GitHub as well so it should be easy to file it against the extension. If you open an extension on the market place, click on the **Support** link to find out more.

<img width="196" alt="screen shot 2016-05-05 at 12 51 17" src="https://cloud.githubusercontent.com/assets/900690/15041943/263e2282-12c0-11e6-9a33-d2b3b500d61b.png">

Thanks again for your feedback!

**Comment by sean-mcmanus** [comment]
@savent404 Yeah, that message is from the cpptools extension. It sounds like there's a problem with internet connection. Did you get it resolved?
