### ISSUE TITLE
Electron Dev Tools: Context Menus Are Behind The Window

### ISSUE THREAD

**Issue by hediet** [microsoft/vscode#197067]
On windows, context menu in the code oss dev tools are basically unusable:

![Image](https://github.com/microsoft/vscode/assets/2931520/2ce0795b-4e18-408c-a279-c288bd150964)

I think it has been like this for some weeks. This is a real productivity blocker, especially since the VS Code debugger is [also quite broken when debugging code oss](https://github.com/microsoft/vscode/issues/196078).

**Comment by deepak1556** [comment]
The feature that broke this behavior in the runtime is not trivial, I will take a look this week. You can start the application with `--disable-features="WidgetLayering"` as a workaround.

I will merge this to https://github.com/microsoft/vscode/issues/193206
