### ISSUE TITLE
Ctrl+F should start searching within the text area only

### ISSUE THREAD

**Issue by ceremcem** [microsoft/vscode#197041]
I need an option to search only inside the current document when I type `Ctrl+F`, no matter where I clicked last. I need to get rid of searching within the document tree by typing `Ctrl+F` after I clicked a document within the document tree. (We have `Ctrl+Shift+F` for that, right?)
```[tasklist]
### Tasks
```

**Comment by IllusionMH** [comment]
Looks like duplicate of #168144 and #155924

<kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>F</kbd>(content search) is quite different from filter functionality inside of Explorer so it's not a replacement

**Comment by ceremcem** [comment]
This is a duplicate, correct. However it didn't solve this problem.

**Comment by joaomoreno** [comment]
@ceremcem It should solve the problem. Did you use `Ctrl` instead of `Cmd`?

**Comment by ceremcem** [comment]
Yes, I'm using `Ctrl`. My demand is having `Ctrl+F` and not any other key combination.

**Comment by joaomoreno** [comment]
[Again](https://github.com/microsoft/vscode/issues/197041#issuecomment-1786419659), please set [this](https://github.com/microsoft/vscode/issues/168144#issuecomment-1339520532) in your keyboard settings:

```
{
    "key": "ctrl+f",
    "command": "-list.find",
    "when": "listFocus && treeSupportsFind"
}
```

**Comment by ceremcem** [comment]
@joaomoreno it doesn't work. 

Are you able to show a screen record where: 

* You open a folder with multiple documents
* Click the document tree
* Press `Ctrl+F`
* The search bar is appeared on the right most side, which is ready to search within the opened document?


I want to get rid of the following behavior: 

https://github.com/microsoft/vscode/assets/6639874/23070cb0-0e1d-49e0-8d0a-03cc225dcb24

**Comment by ceremcem** [comment]
Voila! I opened `Keyboard Shortcuts` editor, searched for `list.find` with `Ctrl+f` shortcut and removed it. Thank you!

![image](https://github.com/microsoft/vscode/assets/6639874/deb4fb55-558b-4026-9707-1c33bfdeb5a1)

**Comment by joaomoreno** [comment]
Sorry for not realizing the context key change. Will update the original post as well.
