### ISSUE TITLE
SEGMENTATION FAULT?

### ISSUE THREAD

**Issue by gregproffit** [microsoft/vscode#197043]
ADD ISSUE DESCRIPTION HERE

Version: 1.83.1
Commit: f1b07bd25dfad64b0167beb15359ae573aecd2cc
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36
Embedder: codespaces

**Comment by gregproffit** [comment]
I keep getting this error when running check50 for the cs50 2022 python problem set 7, "Regular, Um, Expressions"

:( correct um.py passes all test_um.py checks
    failed to execute program due to segmentation fault

**Comment by brettcannon** [comment]
Could you follow the instructions at https://aka.ms/pvsc-bug to file a bug for the Python extension for VS Code? Unfortunately there's not enough information here to know what caused the segfault.
