### ISSUE TITLE
Reg :- My Codespace is not working

### ISSUE THREAD

**Issue by MohamedIrfaan-4038** [microsoft/vscode#197052]
Hi, My codespace is not working properly since a week . The issue is that my codespace is stuck in the loading page. Please rectify the problem asap.

Version: 1.83.1
Commit: f1b07bd25dfad64b0167beb15359ae573aecd2cc
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36
Embedder: codespaces

**Comment by andreamah** [comment]
Please file this under the issues tracker for Codespaces. https://github.com/orgs/community/discussions/categories/codespaces
