### ISSUE TITLE
Add clipboard ring

### ISSUE THREAD

**Issue by stannynuytkens** [Microsoft/vscode#19709]
In Visual Studio it's possible to cycle through [clipboard history][1] contents using CTRL+SHIFT+V.
It would be nice to have this in Code too! _(+make size configurable?)_

[1]:https://blogs.msdn.microsoft.com/zainnab/2010/01/02/how-to-cycle-through-the-clipboard-ring-to-paste-different-things

**Comment by CodeCabbie** [comment]
Can't believe this isn't part of VSCode. It's so useful in VS. Would rather not rely on an extension for something as simple and fundamental as this.
Really would be great.

**Comment by stannynuytkens** [comment]
CTRL+SHIFT+V is currently bound to

```
{
  "command": "markdown.showPreview",
  "key": "ctrl+shift+v",
  "when": "editorFocus"
}
```

**Comment by aefernandes** [comment]
Have you tried this extension: [(https://marketplace.visualstudio.com/items?itemName=Anjali.clipboard-history)](url) (the size is configurable, and you can selectively edit and delete clipboard contents)

**Comment by stannynuytkens** [comment]
Thanks @aefernandes, I will use it for now but I really think people should vote whether they'd like this
built-in or keep it as an extension? This seems like native functionality for the editor. Anyway I'll look into the source code and maybe I'll do a PR :smile:

**Comment by stannynuytkens** [comment]
Issue #6144 is related, was closed...?

**Comment by Nauss** [comment]
I'm trying out code and I am actually surprised this is not built-in. I'll use the extension for now but would love to get the native feature.

**Comment by ni3net** [comment]
Ctrl+Shit+V, I used to do in Visual Studio
it should be a native feature

**Comment by osaft** [comment]
+1 (but ⌘-k ⌘-v)

**Comment by tsrich** [comment]
+1

**Comment by imskull** [comment]
+1 can't believe not a build-in feature.

**Comment by andystod** [comment]
+1

**Comment by lelong37** [comment]
+10

**Comment by evegreen** [comment]
+1

**Comment by sensiloles** [comment]
+1
