### ISSUE TITLE
workbench.action.quickchat.toggle should send query even when quick chat was open

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#197076]
Repro:

1. focus terminal
2. ctrl/cmd+i
3. Run some query
4. focus terminal
5. ctrl/cmd+i, quick chat if focused only, query is not added

cc @TylerLeonhardt

**Comment by rzhao271** [comment]
When I press Ctrl+I in the terminal, nothing happens. For this issue, was it mapped to the quick chat command?

**Comment by chrmarti** [comment]
For me `Cmd+I` on mac works. Verified the fix with that.

A remaining issue is that in this case the `@terminal` is selected, so it is overwritten when I start typing. This is unlike when the QuickChat was not open before. Will open a new issue for that.
