### ISSUE TITLE
/root/.vscode-server/bin/f1b07bd25dfad64b0167beb15359ae573aecd2cc/node_modules/@vscode/ripgrep/bin/rg consume full cpu

### ISSUE THREAD

**Issue by NormanTrinh** [microsoft/vscode#197055]
- VS Code Version: 1.83.1
- OS Version: Linux Mint 21.2 XFCE

Steps to Reproduce:

1. docker run -it ubuntu:20.04
2. Attach Visual Studio Code

 The result look like this
![img](https://imgur.com/1BIzrXi.png)

**Comment by roblourens** [comment]
Still an issue with the latest version?

You could try disabling `search.followSymlinks`
