### ISSUE TITLE
Jittery horizontal scroll experience in Copilot Chat view

### ISSUE THREAD

**Issue by hawkticehurst** [microsoft/vscode#197119]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: `1.84.0-insider`
- OS Version: `macOS 13.6`

Steps to Reproduce:

1. Open GitHub Copilot Chat view (i.e. `Chat: Focus on GitHub Copilot View`)
2. Make sure `chat.editor.wordWrap` setting is configured to "off"
2. Create a prompt that will generate/render a code snippet as part of the answer
3. Using a mouse pad and two-finger drag (at least on macOS) try to horizontally scroll within the code snippet
4. Issue: There should be a jittery experience where both horizontal and vertical scrolling will occur

More context:

I found a tiny UX paper cut when using the GitHub Copilot Chat view when horizontally scrolling to view a code snippet, I always end up scrolling a little bit vertically (cause human fingers 🤷🏻‍♂️), leading to a shaky/jittery experience.

It would be nice if when using the mousepad to horizontal scroll on a code snippet, vertical scrolling was somehow dampened or disabled.

Video example:

https://github.com/microsoft/vscode/assets/39639992/7d9565f5-d764-4800-bc94-0cbdd01663ee

**Comment by hawkticehurst** [comment]
Looks like I don't have permission to assign people to issues, so cc @daviddossett / @roblourens

**Comment by roblourens** [comment]
I bet it would be nice to do the same in notebooks- when the editor handles a horizontal scroll event, it should capture the event and not bubble it up to the list to also do vertical scrolling simultaneously.

@rebornix What do you think, and do you know where in the editor code this happens?
