### ISSUE TITLE
Color Decorators bad behavior on mouseclick

### ISSUE THREAD

**Issue by LatenPath** [microsoft/vscode#197172]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.84.0
- OS Version: Windows 10 x64 10.0.19045

Steps to Reproduce:

1. I have turn-off all of my extension before this reproduce. After I goto `settings.json` for change theme color, I face this issue:
![image](https://github.com/microsoft/vscode/assets/145383056/01cb1567-584b-42cc-b4b5-181ec0adcc98)
As you can see, `editor.Color Decorators` only show icon before the color of `statusBar.debuggingBackground`. Before the one above is nothing.
That the 1st issue.
2. After that, I hover over the icon to select color. That what popup:
![image](https://github.com/microsoft/vscode/assets/145383056/a10e88a6-5b66-4257-b353-856857bcfea3)
And this is normal popup:
![image](https://github.com/microsoft/vscode/assets/145383056/cf999dd2-fac6-448d-8848-8156bc8db343)
That the 2nd issue.
3. After that,I click to select a random color. The popup panel disappear immediately! It only not disappear on mouse hover. Any mouse click on the panel, it will cause disappear => this make color selection too hard.
![Code_NRqgN5fogO](https://github.com/microsoft/vscode/assets/145383056/bb02de66-d5ed-446b-9891-c3f4e5fa25f5)
That not just an issue now... That a confused my mind!

Hope I can have it back soon. Thank you sir! ...and if we can, please fix this error too:
![image](https://github.com/microsoft/vscode/assets/145383056/ec6745dd-e831-41a9-9cfb-ab979d9ed0ba)
We need a way to disable built-in Color Decorators and wont affect other color-picker extentions.

**Comment by aiday-mar** [comment]
Hi thank you for filing the issue. This issue should be closed by the following PR which was developed by a community developer https://github.com/microsoft/vscode/pull/198100. The fix should be inside the next insiders build quite soon and the next stable build in around a month.
