### ISSUE TITLE
[Accessibility] Support go to next and previous codeblock within Copilot Accessible View

### ISSUE THREAD

**Issue by jooyoungseo** [microsoft/vscode#197155]
Type: <b>Feature Request</b>

CC @meganrogge 

When users open Accessible View for Copilot Chat response and when the response contains codeblock, please allow users to quickly jump to the next and previous codeblock within the accessible view by pressing the ctrl+alt+PgUp/PgDown key. Currently, users have to close the accessible view in order to reach the codeblock.

VS Code version: Code - Insiders 1.84.0-insider (d037ac076cee195194f93ce6fe2bdfe2969cc82d, 2023-11-01T10:16:52.814Z)
OS version: Windows_NT x64 10.0.22621
Modes:

**Comment by meganrogge** [comment]
Unfortunately, this is pretty involved to do. 

Does using the go to symbol quick pick help here?

**Comment by meganrogge** [comment]
started investigating on `merogge/symbol`

**Comment by meganrogge** [comment]
To verify:

1. Run a chat request that produces several code blocks
2. Use the go to next/previous actions /key bindings to navigate between them
