### ISSUE TITLE
Stop 'Find All References' From switching to file when only one reference is found

### ISSUE THREAD

**Issue by Triangle4** [microsoft/vscode#197110]
I work with unity and c# on a game that has thousands of files (scripts) in it.
Previously, when you would use Find All References (By right clicking over a variable or method) it would show you where it was used.
In a recent update, this behaviour has changed slightly, and it really slows down a workflow that depends on it.

If only a single reference is found, vscode then switches to that file.
The issue with this, is sometimes were just checking to see if a variable or method was used anywhere unexpected, or anywhere we forgot about.
If it switches every time, especially when we are doing a thorough check of a file, we have to close the file, re-orient ourselves back to what we were looking at in the file we are running QA on, and then rinse and repeat. This adds 5-15 minutes to a QA workflow.

One might say, "Use code lens". To which I say, if you ever use code lens in vscode when trying to delete variables and methods that are no longer in use, you will learn very quickly that code lens doesn't show you ALL references.
This can make a big mess.
Also, code lens is incredibly bulky, resource intensive and sometimes displays 0 references when something is used somewhere else in your project. So it is not an option at all.

I am not very good at english, so this is the best I can do to explain the request. I hope someone can implement this, it seems like such a necessary thing, that perhaps it is implemented somewhere and no one has talked about it on the internet.

**Comment by IllusionMH** [comment]
Doesn't happen for me for JS/TS.

Is it reproducible for you in other languages? Maybe C# specific behavior, not VS Code

**Comment by Triangle4** [comment]
In Java, I can confirm that if there is only one reference to a defined method, it does NOT switch. 
So if this is the case, who is in control of this? Omnisharp server?

**Comment by jrieken** [comment]
This doesn't reproduce anymore, tho I do remember a bug that would have caused this. Might also be that in the meantime C# would cause this by not returning the definition of symbol when asking for its references
