### ISSUE TITLE
Please hide .DS_Store files on Mac OS

### ISSUE THREAD

**Issue by ultra133** [microsoft/vscode#197130]
Type: <b>Feature Request</b>

Mac OS creates annoying .DS_Store files in all directories you visit with Finder, and it is impossible to turn this off.
Please an an Option to hide these files entirely an all Explorer views.

VS Code version: Code 1.83.1 (Universal) (f1b07bd25dfad64b0167beb15359ae573aecd2cc, 2023-10-10T23:46:55.789Z)
OS version: Darwin arm64 23.1.0
Modes:

**Comment by lramos15** [comment]
These should already be hidden based on this setting

<img width="530" alt="image" src="https://github.com/microsoft/vscode/assets/4544166/ddb83c5b-c5e8-4efb-af7b-bf700fd53f33">

**Comment by ultra133** [comment]
Well, I have the same setting, but I see the .DS_Store files in Solution Explorer. Maybe this is an issue specific to C# Dev Kit?

**Comment by lramos15** [comment]
> Well, I have the same setting, but I see the .DS_Store files in Solution Explorer. Maybe this is an issue specific to C# Dev Kit?

Yes that is right, please file an issue with them. The Solution Explorer is not the File Explorer
