### ISSUE TITLE
Apply `vscode-textPreformat-background` in webviews

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode#197154]
From https://github.com/microsoft/vscode/issues/197123

We should fix `code` block styling in Markdown previews in main as well, from discussing with @daviddossett we want to make the styling consistent across chat, settings UI, and extension webviews

**Comment by rzhao271** [comment]
The three greys look different to me. I'm unsure whether those are the colours I should be comparing.

![A screen shot of code blocks in Copilot Chat, in a Settings editor setting description, and for a version tag of an extension](https://github.com/microsoft/vscode/assets/7199958/a247e603-0828-4333-a6a2-303861163992)

**Comment by joyceerhl** [comment]
To verify this you just need to confirm that there is a background for `code` blocks, since it used to just be a brownish foreground color.
