### ISSUE TITLE
Accessibility: explorer.openEditors.visible = 0 does not prevent "Open Editors" from popping up

### ISSUE THREAD

**Issue by tgrushka** [microsoft/vscode#197121]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 
- OS Version: 

Steps to Reproduce:

1. Open settings.json and add `{ "explorer.openEditors.visible": 0 }`
2. Notice that Open Editors keeps popping up every time VS Code is opened in the same or new project.

I am a legally blind user of this product. This is a major accessibility issue as when I'm trying to scroll through the explorer view and click on a file, suddenly the "Open Editors" appears and pushes my explorer view down. I don't understand why suddenly this was forced to be unconfigurable by the user, as this wasn't a problem before. What might be a "convenience feature" for some is an accessibility nightmare for others. Disabling the ability for the user to prevent this pane from showing up was not well thought out. I notice this issue has been filed before and just silently closed or ignored by stating that there is a UI control for this by clicking the three dots menu. Again, an accessibility barrier.

Please consider this a bug, not a feature request, as the feature already existed and does somehow exist, though control has been taken away from the user. Thank you.

Version: 1.84.0-insider
Commit: 60182c7e1a666961ded4d0319c154f52d85daf30
Date: 2023-10-30T23:42:53.278Z
Electron: 25.9.2
ElectronBuildId: 24603566
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Darwin arm64 23.1.0

**Comment by bpasero** [comment]
Sorry to hear that, the setting does not hide the view. It needs to be hidden from the view menu.

@meganrogge @sandy081 what is the accessible way of hiding a view?

**Comment by meganrogge** [comment]
> this was forced to be unconfigurable by the user, as this wasn't a problem before

is this a new feature? @bpasero

**Comment by bpasero** [comment]
Its not a new feature but we removed the ability to configure this via settings because it is configurable via our usual view management. It felt wrong to have 2 ways when all other views follow the standard way.

**Comment by meganrogge** [comment]
When I right click on the view, and toggle open editors off, it's hidden for me. @tgrushka does that work for you?

**Comment by meganrogge** [comment]
@tgrushka closing this as we've moved over to using view management instead of that setting
