### ISSUE TITLE
Show Toggle Developer Tools under the View menu

### ISSUE THREAD

**Issue by CaiusTSM** [Microsoft/vscode#1971]
Hello, I was thinking that it might make a bit more sense to put the Toggle Developer Tools in view, as it brings up a developer view pane. Right now it is under the help menu. Just a small thing bugging me :)

**Comment by isidorn** [comment]
I think it belongs in the help menu since it should not be too visible.
Forwared to Ben for opinions

**Comment by bpasero** [comment]
Valid feature request, but will not change it for the reasons mentioned.
