### ISSUE TITLE
Activity bar not work after upgrading to v1.84.0

### ISSUE THREAD

**Issue by recallwei** [microsoft/vscode#197190]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.84.0 
- OS Version: macOS Sonoma 14.0

Steps to Reproduce:

`ActivityBar.location: top` can only be assigned by settings.json, but still not work after change the value to `top`

![image](https://github.com/microsoft/vscode/assets/62941121/974c3094-1ce6-4d60-9782-259a7765e443)

**Comment by recallwei** [comment]
Even also not work in Insider.
![image](https://github.com/microsoft/vscode/assets/62941121/481ef4c8-daf9-453f-9b09-498660fbb7a5)

**Comment by gjsjohnmurray** [comment]
Did you see this in the release notes?

> supported only when the custom title bar is enabled ("window.titleBarStyle": "custom").

**Comment by recallwei** [comment]
![image](https://github.com/microsoft/vscode/assets/62941121/4793997d-cdda-4979-a42e-49f1e541b3f1)
I used this before.

**Comment by recallwei** [comment]
> Did you see this in the release notes?
> 
> > supported only when the custom title bar is enabled ("window.titleBarStyle": "custom").
![image](https://github.com/microsoft/vscode/assets/62941121/4793997d-cdda-4979-a42e-49f1e541b3f1)
I used this before.

**Comment by gjsjohnmurray** [comment]
Does it make any difference if you change nativeTabs to false?

**Comment by recallwei** [comment]
> Does it make any difference if you change nativeTabs to false?

yeah, it works after changing to false

**Comment by otaviof** [comment]
Additionally, native full screen must be `enabled` before the activity bar buttons shows on top.

```json
{
    "window.nativeFullScreen": true
}
```

**Comment by recallwei** [comment]
🙏 Thanks, everyone.
