### ISSUE TITLE
HTML/JS/TS/SCSS/etc. class/id definition peeking

### ISSUE THREAD

**Issue by sqnkov** [Microsoft/vscode#19715]
Unfortunately , class/id etc. definition peeking `(Alt+F12)` is not appearing or if so, it appears extremely slow. And that is IF it decides to show or not. It works at random for me. (small and large projects)

- VSCode Version: 1.8.1
- OS Version: Windows

Steps to Reproduce:

1. Select a class/id , use `Alt+F12` shortcut on it.
2. Sit and wait forever/for a long period.

I also tried installing The [vscode-css-peek ](https://github.com/pranaygp/vscode-css-peek)extension just for trial, but the issue remains the same.

I think this might be Git related. It tends to show a peek (really slow or not at all) when there are no files in the Git queue.

![ylnx7b3wws](https://cloud.githubusercontent.com/assets/9406520/22558510/a178972e-e976-11e6-973f-77b03e10d2f7.gif)

> This is reproducable each time I start vscode.

Current plugin set:

```
ActiveFileInStatusBar - Version :1.0.2
auto-rename-tag - Version :0.0.11
beautify - Version :0.7.3
Bookmarks - Version :0.10.2
code-settings-sync - Version :2.4.3
color-highlight - Version :1.3.0
githistory - Version :0.1.5
gitignore - Version :0.5.0
guides - Version :0.6.1
html-css-class-completion - Version :1.0.3
html-snippets - Version :0.0.18
HTMLHint - Version :0.3.3
htmltagwrap - Version :0.0.3
indenticator - Version :0.2.1
jquerysnippets - Version :0.0.1
lorem-ipsum - Version :1.0.0
path-intellisense - Version :1.2.0
php-intellisense - Version :0.0.12
sass-indented - Version :1.3.0
stylelint - Version :0.21.2
terminal - Version :0.0.6
Theme-Easyballs - Version :0.0.2
vscode-autoprefixer - Version :2.0.0
vscode-color - Version :0.2.2
vscode-csscomb - Version :4.0.0
vscode-eslint - Version :1.2.2
vscode-gutter-preview - Version :0.8.2
vscode-npm-script - Version :0.1.8
vscode-scss - Version :0.6.0
vscode-simple-icons - Version :0.8.1
vscode-svgviewer - Version :1.3.0
```

**Comment by bpasero** [comment]
Not sure if this is caused by an extension?

**Comment by sqnkov** [comment]
Just after posting this issue, I removed the `vscode-css-peek` and `vscode-file-peek` that are the only `peek`-related plugins in my editor.

And to be sure, I tested it a moment ago on a colleague's machine. Same thing. Peeking or `go to definition` is virtually impossible.

**Comment by bpasero** [comment]
Thanks, I am just not sure if we provide this out of the box or not. Because if not, this issue should be moved to the related extension that provides it.

**Comment by aeschli** [comment]
The built-in VSCode html support does not support 'Goto/peek declaration' into css files.
Please file the issue against the extension that adds this.

**Comment by sqnkov** [comment]
https://code.visualstudio.com/docs/editor/editingevolved

Ctrl + F , type Peek in the search field.

**Comment by aeschli** [comment]
The richness of language feature support varies across the different languages.
HTML, for example, doesn't provide a goto declaration except for code references in embedded JavaScript code. It does NOT look at CSS files that are also in your folder. Invoking Goto Declaration on a class name has no effect. 
Custom extensions can add functionality. If it ever worked (but very slow) then that points to an issue in that extension.
