### ISSUE TITLE
A VSC window crashes on regex search with a specific string in the opened file

### ISSUE THREAD

**Issue by vortigont** [microsoft/vscode#197196]
Does this issue occur when all extensions are disabled?: Yes

Version: 1.84.0 (user setup)
Commit: d037ac076cee195194f93ce6fe2bdfe2969cc82d
Date: 2023-11-01T11:29:04.398Z
Electron: 25.9.2
ElectronBuildId: 24603566
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.19045

Steps to Reproduce:

1. create a new text file `test.txt`
2. paste the following string `        //httpCallback(F("sys_AUTODISCOVERY"), "", false); // реализация AUTODISCOVERY`
3. open search dialog with Ctrl-f
4. enable use regex with Alt-R 
5. start entering following regex `F\((.+)+\)`

window will freeze for several seconds, then a dialog will pop up with window close/reload

**Comment by andreamah** [comment]
This seems like catastrophic backtracking 

/duplicate https://github.com/microsoft/vscode/issues/30874
