### ISSUE TITLE
Provide setting for hiding chat margin

### ISSUE THREAD

**Issue by losnappas** [microsoft/vscode#197138]
I would like a setting like `editor.glyphMargin`, except for hiding the "inline chat" feature buttons (the + buttons).

Alternatively, `editor.glyphMargin` should also control that.

**Comment by aiday-mar** [comment]
Hi thanks for filing the issue. When you mention the inline chat feature buttons, what exactly are you referring to?

**Comment by losnappas** [comment]
My bad, I guess it is something created by an extension and not just something built-in that was just "turned on" by an extension. Was talking about this plus sign which exists in the "Cody AI" extension, the button does open a chat.

![Screenshot from 2023-11-01 16-02-33](https://github.com/microsoft/vscode/assets/25119292/10ac5d0d-9d5b-44d6-880d-4caf746c480a)
