### ISSUE TITLE
Add right-click menu option "collapse children"

### ISSUE THREAD

**Issue by grkuntzmd** [Microsoft/vscode#19713]
- VSCode Version: 1.8.1
- OS Version: Ubuntu 16.10

Add an option to the right-click menu in the Explorer to collapse the children under a folder.

**Comment by bpasero** [comment]
This feature request will not be considered in the next [6-12 months roadmap](https://github.com/Microsoft/vscode/wiki/Roadmap) and as such will be closed to keep the number of issues we have to maintain actionable. Thanks for understanding and happy coding!
