### ISSUE TITLE
Environment collection should not be applied on hidden terminals (non-windows)

### ISSUE THREAD

**Issue by karrtikr** [microsoft/vscode#197187]
Does this issue occur when all extensions are disabled?: Yes/No

Version: 1.85.0-insider
OS: Linux (codespaces)

### WORKS FINE ON WINDOWS

Steps to Reproduce:

`(.venv)` in the terminal prompt is contributed via env collection by Python extension.

Normal terminal:
![image](https://github.com/microsoft/vscode/assets/13199757/31970172-d62a-4aa9-9754-8ebcffc71a18)

Hovering says that collection is applied.

Hidden terminal:
![image](https://github.com/microsoft/vscode/assets/13199757/aedf6e87-db19-4362-86fb-ad5e1f71d76a)

Although it says that no environment collection is contributed upon hovering, collection is still applied as can be seen in the terminal prompt.

**Comment by Tyriar** [comment]
@karrtikr it seems like this is actually a bug where the initially hidden terminal doesn't show the applied environments but should? Making a terminal hidden was just meant to be about visibility, not environment?

**Comment by karrtikr** [comment]
I'm fine if we change hidden terminals to also apply environment collection, as long as we get support for https://github.com/microsoft/vscode/issues/194819.

Python extension decided not to send activate commands to hidden terminals: https://github.com/microsoft/vscode-remote-release/issues/1760, as hidden terminals are considered private terminals belonging to a specific extension. One could probably argue similarly for not applying environment collection to such terminals.

**Comment by karrtikr** [comment]
Based on offline discussion we're continue to go with NOT applying environment collection to hidden terminals.

**Comment by karrtikr** [comment]
We investigated that env collection from shell integration in unix is still being applied on hidden terminals, i.e `applyAtShellIntegration: true` is still being applied when it should not. Any further updates? @Tyriar

**Comment by Tyriar** [comment]
Code to disable for `hideFromUser` terminals:

https://github.com/microsoft/vscode/blob/145af9d6d5426aa3303fddf8090b866fdd2a49d1/src/vs/workbench/contrib/terminal/browser/terminalProcessManager.ts#L439

https://github.com/microsoft/vscode/blob/145af9d6d5426aa3303fddf8090b866fdd2a49d1/src/vs/workbench/contrib/terminal/electron-sandbox/localTerminalBackend.ts#L376

Where `VSCODE_ENV_` vars are set:

https://github.com/microsoft/vscode/blob/145af9d6d5426aa3303fddf8090b866fdd2a49d1/src/vs/platform/terminal/common/environmentVariableCollection.ts#L88-L91

**Comment by Tyriar** [comment]
I cannot reproduce this on Windows or macOS. Steps:

1. Open Code - OSS
2. Open a terminal
3. Run `env` and verify the environment does not include `FOO`
4. Install terminal-sample from vscode-extension-samples via symlink
5. Reload
6. Open a terminal
7. Run `env` and verify the environment _does_ `FOO`
8. Run `Terminal API: Create Terminal (hideFromUser)`
9. Run `Terminal API: Show Terminal` and select the new terminal
10. Run `env` and verify the environment does not include `FOO`

Maybe you had the variable set in the parent environment (main/server?) which is why it showed up?

**Comment by karrtikr** [comment]
Please try it on Linux, this issue doesn't exist on Windows. And I don't have a macOS to verify.

**Comment by Tyriar** [comment]
Thanks, missed the remote bit

**Comment by karrtikr** [comment]
Seems like this behavior has now changed with: https://github.com/microsoft/vscode/pull/208036. So we should either reopen this one or https://github.com/microsoft/vscode/issues/194819, to accomplish https://github.com/microsoft/vscode/issues/194819#issuecomment-2004800950.

**Comment by Tyriar** [comment]
@karrtikr you can accomplish https://github.com/microsoft/vscode/issues/194819 by using `strictEnv`

**Comment by karrtikr** [comment]
I see, suppose if `strictEnv` is `true`, but no `env` is passed explicitly, I assume system environment variables and shell initialization scripts are still applied?

> When this is false (default), the environment will be based on the window's environment and also apply configured platform settings like terminal.integrated.env.windows on top.

What does window's environment mean here and will it be applied if `strictEnv` is `true`, but no `env` is passed.

**Comment by karrtikr** [comment]
> If you don't want env collections you must pass strictEnv, which means you need to provide the entire environment.

We don't have any environment to provide, all we want to do is skip applying env collection while the rest of the environment stays as-is, can you guide us on how to _exactly_ use `strictEnv` to achieve that?

**Comment by Tyriar** [comment]
@karrtikr basing the environment on `{ ...process.env }` should do the trick

**Comment by karrtikr** [comment]
Gotcha, will try that. I assume shell initialization and integration scripts are still run?

**Comment by Tyriar** [comment]
@karrtikr looking at the code, I think shell integration does activate even when strictEnv is set

**Comment by rzhao271** [comment]
What are some verification steps for this issue?

**Comment by Tyriar** [comment]
@rzhao271 steps at https://github.com/microsoft/vscode/issues/197187#issuecomment-1971325388, remote only

**Comment by karrtikr** [comment]
@Tyriar Actually we reverted the change made in this issue with https://github.com/microsoft/vscode/issues/197187#issuecomment-2004828951, so even hidden terminals have environment collection applied by default now.

**Comment by Tyriar** [comment]
@karrtikr :+1:

So the steps are:

1. Open a terminal
2. Run `env` and verify the environment does not include `FOO`
3. Install terminal-sample from vscode-extension-samples via symlink
4. Reload
5. Open a terminal
6. Run `env` and verify the environment _does_ `FOO`
7. Run `Terminal API: Create Terminal (hideFromUser)`
8. Run `Terminal API: Show Terminal` and select the new terminal
9. Run `env` and verify the environment ***does*** include `FOO`

**Comment by rzhao271** [comment]
@Tyriar How do I do step 3? Am I opening the terminal-sample workspace after cloning and creating a symlink to it?

**Comment by Tyriar** [comment]
@rzhao271 you can build the extension and do it in the insiders extension development host
