### ISSUE TITLE
Settings override don't working

### ISSUE THREAD

**Issue by IgorNovozhilov** [Microsoft/vscode#19714]
- VSCode Version: 
![2017-02-02_15h29_01](https://cloud.githubusercontent.com/assets/3082812/22550356/af913c14-e960-11e6-9e71-d430a231d75e.png)

- OS Version: win7 pro

Steps to Reproduce:

1. use settings override
![2017-02-02_15h30_12](https://cloud.githubusercontent.com/assets/3082812/22550295/762bff90-e960-11e6-9829-1359cb333a45.png)
![2017-02-02_15h28_54](https://cloud.githubusercontent.com/assets/3082812/22550296/770539d6-e960-11e6-939e-9a49dddb0f56.png)

2. it's don't working
![2017-02-02_16h00_03](https://cloud.githubusercontent.com/assets/3082812/22550353/acefe398-e960-11e6-9bac-cd7bea66675d.png)

**Comment by IgorNovozhilov** [comment]
in the previous build it worked

**Comment by IgorNovozhilov** [comment]
https://github.com/Microsoft/vscode/issues/19511

**Comment by bpasero** [comment]
Yes, we did not manage to support all editor settings in this first version of the feature. We plan to support this very soon in our insider build.

**Comment by IgorNovozhilov** [comment]
very sad :disappointed:

**Comment by bpasero** [comment]
@IgorNovozhilov did you try out if the editor config extension helps you? https://marketplace.visualstudio.com/items?itemName=EditorConfig.EditorConfig

**Comment by IgorNovozhilov** [comment]
Yes, I've been using it. I thought it would be a great replacement for the for "EditorConfig"

**Comment by bpasero** [comment]
@IgorNovozhilov if you do not mind our insider release, I think @sandy081 has already fixed this issue and it would be available in our nightly builds very soon (maybe even tomorrow if we release 1.9 today).

**Comment by takentui** [comment]
Yeap, it's works! Thank you!
