### ISSUE TITLE
Activity Bar: Position Top - Didn't remove the Activity Bar area on the left

### ISSUE THREAD

**Issue by alefragnani** [microsoft/vscode#197185]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.84.0 (user setup)
- OS Version: Windows 10

Steps to Reproduce:

1. Updated to 1.84.0
2. Choose Activity Bar Position / Top option
3. The icons appears at the top, but the Activity Bar area on the left is still there

![image](https://github.com/microsoft/vscode/assets/3781424/18dc8c4b-dd35-4ba4-bf16-da29a24108ee)
> Updated the image to display the entire VS Code window, and better identifying the empty panel

4. Running `View: Reset View Locations` didn't fix the issue
5. Restaring VS Code didn't fix the issue
6. Moving the Activity Bar to the rignt, didn't fix the issue

Thank you

**Comment by gjsjohnmurray** [comment]
This is behaving as designed. What are you expecting to see happen?

**Comment by alefragnani** [comment]
I was expecting it to _remove_ that Side pane (at left), since the icons are now on Top. Just like the Insiders release does.

![image](https://github.com/microsoft/vscode/assets/3781424/434c7e9f-322a-4b29-b742-4c85cfa746a0)

**Comment by alefragnani** [comment]
I update the title and comments to properly identify what I was calling _Side bar/left panel_ as the **Activity Bar** area. 

Sorry for the confusion.

**Comment by sandy081** [comment]
@alefragnani Are you able to reproduce it consistently? If so, do you see any errors in the dev tools console? Can you please check if you can repro it in a new profile?

**Comment by alefragnani** [comment]
@sandy081 ,

Yes, it _was_ consistently reproductible, up until I opened VS Code via command line, using `--disable-extensions`. Now, it is working as expected. Really weird.

What I have tried, beyond steps 4, 5 and 6 from the original comment

7. Switched to another profile, didn't fix the issue
8. Switched to the Default profile, didn't fix the issue
9. Opened empty workspace, didn't fix the issue

I have opened dev tools console as you asked, but no relevant message were reported. 

Just out of curiosity, these are the extensions that I had installed on the original profile:

extension|author|version
-- | -- | --
Bookmarks | ale | 13.4.2
copy-word | ale | 3.11.0
numbered-bookmarks | ale | 8.4.0
project-manager | ale | 12.7.0
separators | ale | 2.5.0
vscode-unj-solution | ale | 1.1.0
gitlens | eam | 14.4.1
csharp | ms- | 1.26.0
vscode-dotnet-runtime | ms- | 2.0.0
vscode-jumpy | wma | 0.3.1

Not sure how/why, but now it is working. Let me know if you need any additional information, otherwise, feel free to close the issue if there is nothing else to investigate/fix.

Thank you

**Comment by sandy081** [comment]
I can only think that one of these extensions is changing the VS Code styling. Are you able to repro again with these extensions enabled?

**Comment by alefragnani** [comment]
Not anymore. 

Once I started VS Code via command line once, using the `--disable-extensions` parameter, the issue is gone. I can restart VS Code and it is working perfectly.

**Comment by sandy081** [comment]
Ok. Closing as it cannot be reproduced.
