### ISSUE TITLE
Dark Modern code blocks lack color 

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode#197123]
Expected

![image](https://github.com/microsoft/vscode/assets/30305945/7074ed9b-89b2-4668-84fe-c46ab0c37f23)

Actual

![image](https://github.com/microsoft/vscode/assets/30305945/360d71e8-296b-4448-9955-a07faec98712)

**Comment by joyceerhl** [comment]
Regressed in https://github.com/microsoft/vscode/commit/243e6cec5096b301259ca1f780e50b135f308d33

**Comment by bhavyaus** [comment]
The markdown preview in the chat is also broken for Dark Modern but is fixed by your change:

![Image](https://github.com/microsoft/vscode/assets/25044782/b3283a5f-51ce-485c-9878-194c786117eb)

**Comment by bhavyaus** [comment]
And the markdown preview in the settings editor:

![Image](https://github.com/microsoft/vscode/assets/25044782/759d0418-08bd-4182-a710-a8274248d12a)

**Comment by joyceerhl** [comment]
I looked into this some more and have the following findings
* `code` block rendering is broken for Dark Modern, Light Modern, Dark HC and Light HC
* What changed: we added a new theme token, `vscode-textPreformat-background`, adopted it in chat.css and settingsEditor2.css, and updated the values for `vscode-textPreformat-foreground` to look good with a different background color
* But we didn't adopt `vscode-textPreformat-background` token for `code` blocks in Markdown previews, which is why `vscode-textPreformat-background` is broken for Markdown preview

Some options
* Adopt `vscode-textPreformat-background` for `code` blocks in Markdown preview -- this amounts to a rather drastic styling change for Markdown previews 
    ![image](https://github.com/microsoft/vscode/assets/30305945/7ae2973d-43ee-497c-a2ab-a3d554c3c12d)

* Revert https://github.com/microsoft/vscode/commit/243e6cec5096b301259ca1f780e50b135f308d33
* Revert the change to `vscode-textPreformat-foreground` and drop the usage of `vscode-textPreformat-background` so that Markdown preview, chat, and settings UI are in a reasonable state for all themes, which I attempted in https://github.com/microsoft/vscode/pull/197124

**Comment by gregvanl** [comment]
Also affects the Extensions Details page since it is a Markdown preview

![image](https://github.com/microsoft/vscode/assets/12818376/60996a18-e4dd-43a8-8db3-709e3dc82f2a)

**Comment by joyceerhl** [comment]
Verification: for Light/Dark Modern and Light/Dark HC, make sure that `code` blocks are properly rendered in Markdown preview, settings UI and chat
