### ISSUE TITLE
User settings.json opens two columns, and is annoying

### ISSUE THREAD

**Issue by fastmarketo** [microsoft/vscode#197175]
![01](https://github.com/microsoft/vscode/assets/6827222/cd00be49-3b4d-44fd-a410-c2187ff494b4)

User settings.json opens two columns, and is annoying

**Comment by rzhao271** [comment]
Do you have the `workbench.settings.useSplitJSON` setting enabled?
If not, does the issue occur when extensions are disabled?

**Comment by fastmarketo** [comment]
Thanks, As soon as I unchecked it, every was sorted. Thanks again sir, Thanks.

![image](https://github.com/microsoft/vscode/assets/6827222/549b2f4a-56fc-4ef3-8304-53b42a2acc38)
