### ISSUE TITLE
Standard view shortcuts no longer working when primary bar is hidden

### ISSUE THREAD

**Issue by DP19** [microsoft/vscode#197169]
Type: <b>Bug</b>

Steps to Repro:

- Open VS Code and hide activity bar
- Open Explorer
- Reload window
- Open Search view using keyboard
🐛 Cannot open Explorer view using keyboard

----

In previous versions of VS code the shift + CMD + E would always open the Explorer tab. With this version it no longer works if the Activity Bar is hidden.

Looks like the system shortcut has either added or changed the when condition to ` "when": "viewContainer.workbench.view.explorer.enabled"` . 

If i do show the bar this shortcut works again. I've just removed the condition but curious as to why it was added to begin with? May not be a bug

Opened this as "Standard View shortcuts" because it seems this has also been added for `View: Show Extensions`, `View: Show Run and Debug`, & `View: Show Explorer`

VS Code version: Code 1.84.0 (Universal) (d037ac076cee195194f93ce6fe2bdfe2969cc82d, 2023-11-01T11:30:19.406Z)
OS version: Darwin arm64 22.6.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|2, 2, 3|
|Memory (System)|32.00GB (0.21GB free)|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
circleci|Cir|1.23.0
vscode-simpler-icons|dav|1.6.5
go|gol|0.39.1
terraform|has|2.28.2
vetur|oct|0.37.3
vscode-commons|red|0.0.6
vscode-xml|red|0.26.1
vscode-yaml|red|1.14.0

(1 theme extensions excluded)

</details>

**Comment by DP19** [comment]
```
2023-11-01 16:07:27.071 [info] [KeybindingService]: | Resolving shift+meta+[KeyE]
2023-11-01 16:07:27.071 [info] [KeybindingService]: \ From 1 keybinding entries, no when clauses matched the context.
```
Turned on the shortcut debugging and put the when clause back in place and that is indeed the issue. Searching the code base for the when clause doesn't yield any results except in issues so I'm unsure of where / why this changed or even if it has with this version

**Comment by JoeRoddy** [comment]
Same issue on 1.84
Mac OS 14.1

Removing the when condition fixed it for me as well:
![image](https://github.com/microsoft/vscode/assets/16690442/accb25f6-b790-4998-824e-1ec51cf375a8)

Delete everything => press enter

**Comment by JoeRoddy** [comment]
This issue is also affecting extensions (Command + Shift + X)

But not some others, like source control (Command + Shift + G)

**Comment by ChrisVilches** [comment]
Confirmed this on my PC. It doesn't work when the icon buttons (activity bar) are hidden.

In my case (Ubuntu), `CTRL + SHIFT + E` stopped working. It used to show the Explorer.

I can show the search bar with `CTRL + SHIFT + F` but cannot go back to the Explorer with `CTRL + SHIFT + E`.

Removing this line from `~/.config/Code/User/settings.json` worked:

```
"workbench.activityBar.location": "hidden"
```

This shows the buttons again, and makes the shortcut `CTRL + SHIFT + E` work again.

**Comment by mishi321** [comment]
Thoes two shortcuts default condition confused me, I always work without activityBar, instead I use shortcuts to reach anywhere.

**Comment by svipas** [comment]
Exactly same issue, shortcuts should work no matter what you have inside `workbench.activityBar.location` setting.

**Comment by adns44** [comment]
I experience same issue. Can not use keyboard sshortcuts to open and focus on explorer. I use JAWS screen reader and Windows. The line mentioned by @ChrisVilches 
```
"workbench.activityBar.location": "hidden"
```
fixed my issue. On Windows, easyest way is to open command palette (ctrl-shift-p), search for `Preferences: Open User Settings (JSON)` and press enter. In the JSON file search the mentioned line, delete it and press CTRL+s, CTRL+f4. Keyboard shorcuts works again.

Thanks for this idea:)

**Comment by naoyeye** [comment]
<img width="476" alt="image" src="https://github.com/microsoft/vscode/assets/434428/caa4894b-5e27-40c3-83ce-885d4b0efae6">

my Activity Bar was hidden before, today I found that the 'Show Explorer' shortcut keys didn’t work.


<img width="675" alt="image" src="https://github.com/microsoft/vscode/assets/434428/fbdd89d2-3485-4e13-bbd1-8762b92bc407">

try to change the Activity Bar to 'side' or 'top' and then change it back to 'hidden', worked for me.

**Comment by jacobcassidy** [comment]
To add more clarity on this issue which I didn't see mentioned here:

- In the control panel, after you select `View: Hide Activity Bar`, there is no option to show it again. There should be a setting for `View: Show Activity Bar`.

- If the Activity Bar is hidden and you select `View: Focus Activity Bar` the UI space for the Activity Bar will be revealed, but the Activity Bar content/icons will still be hidden. This setting should either show the Activity Bar again in full or the setting should not be shown when the Actiivity Bar is hidden.

**Comment by sandy081** [comment]
@jacobcassidy Your issue is completely different from this issue. Please follow up with this https://github.com/microsoft/vscode/issues/197297 for your issue.

**Comment by bhavyaus** [comment]
Verified that this has been fixed in the latest insiders. Closing this issue.
