### ISSUE TITLE
Horizontal Primary Side Bar for Mobile users

### ISSUE THREAD

**Issue by TheAlan404** [microsoft/vscode#197133]
The primary side bar is kinda the biggiest issue while trying to use VSCode on mobile. It would be nice if the buttons were able to be stacked horizontally on top instead of taking 25% of the screen space.

**Comment by gjsjohnmurray** [comment]
Upcoming 1.84 allows you to move the Activity Bar to become tabs at the top of the Primary Side Bar.

**Comment by sbatten** [comment]
yep, this is possible now
