### ISSUE TITLE
Debugger launching msedge -> browser extension are removed

### ISSUE THREAD

**Issue by vanowm** [microsoft/vscode#197150]
Type: <b>Bug</b>

When MS Edge launched from 2 different workspaces, it looses previously installed extensions.
How to reproduce:
1) Create `test1.code-worspace` and `test2.code-workspace` files with this code:
```
{
	"folders": [],
	"launch": {
		"version": "0.2.0",
		"configurations": [
			{
				"name": "Launch Edge",
				"request": "launch",
				"type": "msedge",
				"version": "stable"
			},
		]
	}
}
```
2) open `test1` workspace and run the debugger "Launch Edge"
3) in the opened Edge browser install any extension.
4) close browser and relaunch it again, confirm the extension still installed and functional.
5) open `test2` workspace and run the debugger "Launch Edge"
6) close Edge browser
7) open `test1` workspace and run the debugger again.
8) previously installed extension is no longer there.

VS Code version: Code 1.83.1 (f1b07bd25dfad64b0167beb15359ae573aecd2cc, 2023-10-10T23:48:05.904Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz (16 x 3600)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|63.67GB (34.39GB free)|
|Process Argv|--verbose|
|Screen Reader|no|
|VM|50%|
</details><details><summary>Extensions (86)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|3.0.2
vscode-javascript-repl|ach|0.7.4
vscode-userscript|adp|1.3.2
Bookmarks|ale|13.4.2
tsl-problem-matcher|amo|0.6.2
vscode-scriptmonkey|and|0.0.8
chronicler|arc|0.1.16
autolispext|Aut|1.6.2
vscode-log-viewer|ber|0.14.1
github-markdown-preview|bie|0.3.0
markdown-checkbox|bie|0.4.0
markdown-emoji|bie|0.3.0
markdown-footnotes|bie|0.1.1
markdown-mermaid|bie|1.20.0
markdown-preview-github-styles|bie|2.0.3
markdown-yaml-preamble|bie|0.1.0
vscode-intelephense-client|bme|1.9.5
git-exclude|bou|0.3.1
phpserver|bra|3.0.2
insert-unicode|bru|0.15.1
turbo-console-log|Cha|2.9.6
jsdoc-generator|cry|2.0.1
autoit|Dam|1.0.12
vscode-eslint|dba|2.4.2
xml|Dot|2.5.1
gitlens|eam|14.4.1
EditorConfig|Edi|0.16.4
vscode-great-icons|emm|2.1.102
prettier-vscode|esb|10.1.0
vscode-macros|EXC|1.4.1
vscode-highlight|fab|1.9.0
vscode-firefox-debug|fir|2.9.10
auto-rename-tag|for|0.1.10
copilot|Git|1.132.526
copilot-chat|Git|0.8.0
copilot-labs|Git|0.15.1019
remotehub|Git|0.62.0
vscode-pull-request-github|Git|0.74.1
triggertaskonsave|Gru|0.2.17
reg|ion|1.1.0
vscode-peacock|joh|4.2.2
minifyall|jos|2.10.0
node-module-intellisense|lei|1.5.0
Lisp|mat|0.1.12
render-crlf|med|1.7.1
vscode-language-babel|mgm|0.0.40
git-graph|mhu|1.30.0
document|min|2.2.1
vscode-filesize|mkx|3.1.0
vscode-apache|mrm|1.2.0
vscode-edge-devtools|ms-|2.1.3
isort|ms-|2023.10.1
python|ms-|2023.18.0
vscode-pylance|ms-|2023.10.50
hexeditor|ms-|1.9.12
js-debug-nightly|ms-|2023.10.3117
live-server|ms-|0.4.11
remote-repositories|ms-|0.40.0
test-adapter-converter|ms-|0.1.8
debugger-for-edge|msj|1.0.15
color-highlight|nau|2.5.0
vscode-auto-scroll|pej|1.1.0
vscode-versionlens|pfl|1.9.1
vscode-phpunit|rec|3.2.0
vscode-xml|red|0.26.1
format-html-in-php|rif|1.7.0
vs-code-prettier-eslint|rve|5.1.0
multi-command|ryu|1.6.0
vbsvscode|Ser|1.2.1
swapdiff|sha|0.2.2
comment-divider|sta|0.4.0
code-spell-checker|str|3.0.1
vscode-stylelint|sty|1.2.4
tabnine-vscode|Tab|3.19.0
tauri-vscode|tau|0.2.6
pdf|tom|1.2.2
vscode-ltex|val|13.1.0
intellicode-api-usage-examples|Vis|0.2.8
vscodeintellicode|Vis|1.2.30
vscode-wakatime|Wak|24.2.3
vscode-backup|Wes|0.0.6
eno|Wsc|2.3.53
php-debug|xde|1.33.1
local-history|xyz|1.8.1
json-color-token|yec|1.3.3
html-css-class-completion|Zig|1.20.0

</details>

**Comment by vanowm** [comment]
This is probably `vscode-js-debug` extension bug https://github.com/microsoft/vscode-js-debug/issues/1877

**Comment by vanowm** [comment]
This is not an extension issue. The problem is reproducible with no extensions, with fresh portable VSCode.

**Comment by connor4312** [comment]
Duplicates https://github.com/microsoft/vscode-js-debug/issues/1877

**Comment by vanowm** [comment]
this looks like the other way around, since the issue is reproduceable without the extension, the other issue would be a duplicate of this one.
