### ISSUE TITLE
When the side view isn't shown, there's barely any padding on the left

### ISSUE THREAD

**Issue by mybearworld** [microsoft/vscode#197178]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.84.0
- OS Version: Windows 11

Steps to Reproduce:

1. Set the Activity Bar to top or hidden
2. ![VSCode with the activity bar set to top. On the left, there is barely any padding, which looks bad. Normally, there is more padding on the lft.](https://github.com/microsoft/vscode/assets/130385691/50c58452-202c-43ad-9b67-bc8e6cdad502)

**Comment by gjsjohnmurray** [comment]
Why do you want padding on the left?

**Comment by mybearworld** [comment]
> Why do you want padding on the left?

1. There's padding on the right in most views, so having it on the left too is more consistent:
   ![VSCode with the Activity Bar set to top, with the settings open. While there is no padding on the left, the settings view adds padding on the right.](https://github.com/microsoft/vscode/assets/130385691/27e69ff4-8ab7-4a4a-a910-13a3e39025d9)
2. It's also there when the Activity Bar is set to left:
   ![The left part of VSCode when the Activity Bar is set to the side.](https://github.com/microsoft/vscode/assets/130385691/1447d1c5-4b62-42a0-a02c-a428f8070218)

**Comment by mybearworld** [comment]
Also, the focus border doesn't actually show on the left:

![The Activity Bar on top where the explorer is focused - the border shows up, but not on the left, because of the window border and lack of padding.](https://github.com/microsoft/vscode/assets/130385691/323f967f-2e8e-484c-a806-62f88bb59d58)

**Comment by gjsjohnmurray** [comment]
@sandy081 I can repro the missing left edge of the focus rectangle, but only when the window isn't maximized.

**Comment by gjsjohnmurray** [comment]
Maybe related to the missing right edge of the focus rectangle in unmaximized window, I just noticed that when activity bar is at the side its selected-item bar is thinner (only 1px) on an unmaximized window:

![image](https://github.com/microsoft/vscode/assets/6726799/730e9d83-c6f2-4667-8a1e-490d00832a7d)

When maximized the blue bar is 2px wide:

![image](https://github.com/microsoft/vscode/assets/6726799/49458f27-f594-417c-ab91-aad4a04af451)

**Comment by mybearworld** [comment]
I never use VSCode maximized, so I never knew the bar was supposed to be thicker...

**Comment by albertosantini** [comment]
Of course, when the side bar is on the right, the focus border doesn't actually show on the right.
It seems it is missing also when maximized.

**Comment by sandy081** [comment]
Regarding padding and focus line, do you see the same when activity bar is hidden?

**Comment by mybearworld** [comment]
> Regarding padding and focus line, do you see the same when activity bar is hidden?

I do. I'll edit the issue to reflect that

**Comment by sandy081** [comment]
Can you please create a separate issue for focus border?

**Comment by mybearworld** [comment]
> Can you please create a separate issue for focus border?

Done - #197235

**Comment by sbatten** [comment]
I think the workbench overall doesn't account for a pixel or 2 which are eaten by the window border itself. You can see this if you move the side bar to the righht. CLosing other issue as I think they have the same cause.
