### ISSUE TITLE
The JS/TS language service immediately crashed 5 times. The service will not be restarted.

### ISSUE THREAD

**Issue by Dmarcotrigiano** [microsoft/vscode#197112]
Type: <b>Bug</b>

Any time I try to restart my TS language server it crashes 5 times.

VS Code version: Code 1.83.1 (f1b07bd25dfad64b0167beb15359ae573aecd2cc, 2023-10-10T23:48:05.904Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Remote OS version: Linux x64 5.15.90.1-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 9 7950X3D 16-Core Processor           (32 x 4200)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|63.12GB (33.56GB free)|
|Process Argv|--crash-reporter-id 96944f72-8e54-4013-a310-14662d584bf7|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 5.15.90.1-microsoft-standard-WSL2|
|CPUs|AMD Ryzen 9 7950X3D 16-Core Processor (32 x 4200)|
|Memory (System)|30.91GB (28.36GB free)|
|VM|0%|
</details><details><summary>Extensions (23)</summary>

Extension|Author (truncated)|Version
---|---|---
terraform|4op|0.2.5
es7-react-js-snippets|dsz|4.4.3
remotehub|Git|0.62.0
vscode-graphql-syntax|Gra|1.2.2
vscord|Leo|5.1.18
dotenv|mik|1.0.1
jupyter-keymap|ms-|1.1.2
remote-containers|ms-|0.318.0
remote-ssh|ms-|0.106.5
remote-ssh-edit|ms-|0.86.0
remote-wsl|ms-|0.81.8
azure-repos|ms-|0.38.0
remote-repositories|ms-|0.40.0
JavaScriptSnippets|xab|1.8.0
vscode-eslint|dba|2.4.2
prettier-vscode|esb|10.1.0
vscode-jest-runner|fir|0.4.69
copilot|Git|1.132.0
copilot-chat|Git|0.8.0
vscode-github-actions|git|0.26.2
vscode-github-actions|me-|3.0.1
vscode-docker|ms-|1.27.0
vscode-yaml|red|1.14.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
py29gd2263:30856252
vscaat:30438848
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
282f8724:30602487
89544117:30613380
showlangstatbar:30737416
03d35959:30757346
pythonfmttext:30731395
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
pythonnosmt12:30797651
pythonidxpt:30866567
pythonnoceb:30805159
copilotsettingc:30859502
synctok:30869157
dsvsc013:30795093
dsvsc014:30804076
dsvsc015:30845448
pythontestfixt:30871694
pythonregdiag2:30871582
pyreplss1:30865275
pythoncet00cf:30874137
pythontbext0:30864172

```

</details>

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

**Comment by Dmarcotrigiano** [comment]
It does not, I do not have this issue anymore. Should I not be selecting
the prompt that appears in my VSCode for issues that I have not
troubleshooted myself?

**Comment by mjbvz** [comment]
Thanks for checking. Yes you should do some basic troubleshooting before opening an issue as often the issue has already been fixed or an extension is the root cause
