### ISSUE TITLE
revealInExplorer command doesn't work when explorer is not visibile

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#197268]
Type: <b>Bug</b>

1. Focus in chat view or another view so that the explorer is not visible
2. Trigger the `revealInExplorer` command with a folder that exists

**bug**
Explorer shows but the file is not revealed. The same command works if the explorer is visibile

You can test this using `yo code` with this command implementation:

```ts
	let disposable = vscode.commands.registerCommand('test-ext.helloWorld', () => {
		const uri = vscode.Uri.joinPath(vscode.workspace.workspaceFolders![0].uri, 'test');
		vscode.commands.executeCommand('revealInExplorer', uri);
	});
```

VS Code version: Code - Insiders 1.85.0-insider (Universal) (a9d8fbca9ec9a7914f2077a83ca66a08c7e10f83, 2023-11-02T09:04:13.888Z)
OS version: Darwin arm64 23.1.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M2 Max (12 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|7, 8, 8|
|Memory (System)|64.00GB (8.54GB free)|
|Process Argv|--crash-reporter-id 0fffb5da-9cd7-46fd-9e7f-a1564e8c5fda|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by mjbvz** [comment]
Seems to be caused by this code which triggers a second call to reveal the active editor file when the explorer is revealed:

https://github.com/microsoft/vscode/blob/17dd2608a86b1e9a9126ba3269cebcfe1d627850/src/vs/workbench/contrib/files/browser/views/explorerView.ts#L306

**Comment by rzhao271** [comment]
I don't get what "Explorer shows but the file is not revealed." means. Is the assumption that the folder is non-empty?

**Comment by mjbvz** [comment]
I just tested and verified it is fixed

@rzhao271 When this command is run, it is supposed to open the explorer and also highlight/select the target file in the explorer. That second part is what wasn't working
