### ISSUE TITLE
Show editor dirty state when tab bar is hidden

### ISSUE THREAD

**Issue by jkiss** [microsoft/vscode#197298]
it's a awsome feature to hide tab bar, but I can NOT comfirm wether this file saved or not when hide tab bar

**Comment by gjsjohnmurray** [comment]
A workaround is probably to use the `window.title` setting, which can include a `${dirty}` element.

**Comment by gjsjohnmurray** [comment]
Indeed, it seems to be included in the default value for this property. @jkiss aren't you seeing an indicator at the beginning of the window title when the current editor has unsaved changes?

**Comment by benibenj** [comment]
If a user has no tab bar, has a command center and uses the default window title values, then we just show the name of the current file. It however would make sense to include the dirty state in this case.

**Comment by gjsjohnmurray** [comment]
@benibenj here's what I'm seeing on 1.84 on Windows with Command Center enabled, default window title, and a dirty file open in my folder:

![image](https://github.com/microsoft/vscode/assets/6726799/586433a8-20fc-4e99-a5cf-319d74471016)

And after Ctrl+Z to undo the change:

![image](https://github.com/microsoft/vscode/assets/6726799/5bdddc6b-9732-4a61-b962-d13da5eb686a)

**Comment by benibenj** [comment]
@gjsjohnmurray can you confirm that you have exactly the following value for `window.title`: `${dirty}${activeEditorShort}${separator}${rootName}${separator}${profileName}${separator}${appName}`

You are seeing more text than default in the command center, which is normally due to not using the default value.

**Comment by gjsjohnmurray** [comment]
@benibenj aha, it's because I have set a separator:

`"terminal.integrated.tabs.separator": " ● "`

**Comment by gjsjohnmurray** [comment]
To summarise, I haven't set `window.title` but I **have** set `window.titleSeparator`.

**Comment by benibenj** [comment]
Yes, that is it. We check if the user has a custom title format which is also affected by changing `titleSeparator`. By changing any title formatting, we assume you want to see the title instead of just workspace name (or file name when tabs are hidden)

**Comment by gjsjohnmurray** [comment]
OK, so maybe it's reasonable for the default behaviour to become that `{dirty}` is added when tabs are hidden.

Meanwhile @jkiss a workaround is to set `"winodw.titleSeparator": " -  "` (Note - two trailing spaces following the `-`).

**Comment by bpasero** [comment]
👍 to include dirty indicator in command center by default without the user having to change something.

**Comment by jkiss** [comment]
@gjsjohnmurray hi, I'm a MacOS user, so there is really NOT a unsave indicator at anywhere 😢 
![image](https://github.com/microsoft/vscode/assets/3231326/c392a009-fd63-40b8-b4a7-faefbe206041)

**Comment by jkiss** [comment]
@gjsjohnmurray hi, I'm a MacOS user, so there is really NOT a unsave indicator at anywhere 😢
![image](https://github.com/microsoft/vscode/assets/3231326/38389234-e9c6-4a80-bd6e-747b2eb94893)

**Comment by jkiss** [comment]
@gjsjohnmurray ok, there is a BIG dot, could I set this dot color to red or yellow?
![image](https://github.com/microsoft/vscode/assets/3231326/451ea1e3-3d8c-4ed4-a086-09dc07f3c016)

**Comment by benibenj** [comment]
verification steps:
1. Hide tabs: `workbench.editor.showTabs: "hidden"`
2. Show Command Center
3. Make sure to use default `window.title` value
4. Make active file dirty
5. Command center should display the dirty icon in front of the file name
