### ISSUE TITLE
(HEAD+changes)-to-branch diff view

### ISSUE THREAD

**Issue by tinganho** [Microsoft/vscode#1972]
Since many follows a pull-request flow. It would be ideal if a developer could see a (HEAD+changes)-to-branch diff views and not ont only Changes-to-HEAD diff view as it is currently.

Many make some changes and makes some commits on a feature or bug branch. They push the new commits to their fork and review the changes before submitting a pull request. The review is a diff against, most likely, an upstream master branch. The problem is, that it is time consuming to make many micro changes online by force pushing etc. It would be more ideal if this diff view could be viewed locally in VSCode and not only on Github.

**Comment by joaomoreno** [comment]
Give this extension a try: [githistory](https://marketplace.visualstudio.com/items/donjayamanne.githistory).

**Comment by tinganho** [comment]
I don't think that one is user friendly at all. I'm not even sure it can do what I asked for.

**Comment by joaomoreno** [comment]
I see, you don't want to compare file by file, but an overview of what has changed between two commits.

Marking it as duplicate of #68

**Comment by tinganho** [comment]
@joaomoreno why not just add a dropdown on the git tab. Where you can choose which branch you want to compare to? The default one is comparing to HEAD as it is right now. It would solve a very big problem.

**Comment by joaomoreno** [comment]
Pull requests are more than welcome! Wanna give it a try?

**Comment by tinganho** [comment]
I have some unfinished business to deal with. I can probably give it a try with in a non-distant future.
