### ISSUE TITLE
Current tab highlighting isn't displayed

### ISSUE THREAD

**Issue by leonjanzen-work** [microsoft/vscode#197266]
![Thin blue line after window resize](https://github.com/microsoft/vscode/assets/6565814/4f218754-b6a4-4758-b980-5af05db3a7fb)
![Normal blue line](https://github.com/microsoft/vscode/assets/6565814/6fc6df52-6ffb-457b-9ff6-44f50bb7384a)
<img width="168" alt="Missing blue line" src="https://github.com/microsoft/vscode/assets/6565814/cba070d2-07c7-4a6d-93b9-7a85cde73296">
Type: <b>Bug</b>

I usually have a few rows of open tabs, and the blue highlighting ("Dark modern" theme) showing my currently active tab seems to be hidden behind the title bar, and then I can't see it anymore. If I resize my VS Code window, it comes back for a while (but always thinner than the same blue line on the second row of tabs), and then after half an hour or so, I notice that it's no longer visable again.

VS Code version: Code 1.84.0 (d037ac076cee195194f93ce6fe2bdfe2969cc82d, 2023-11-01T11:29:04.398Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz (12 x 3192)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.84GB (2.34GB free)|
|Process Argv|--crash-reporter-id 35bae971-461f-4f21-80a9-129d237f328e|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (29)</summary>

Extension|Author (truncated)|Version
---|---|---
sas-syntax|77q|1.0.8
vscode-sql-formatter|adp|1.4.4
vscode-intelephense-client|bme|1.9.5
go-to-character-position|dav|2.0.0
vscode-pdf|mat|0.0.6
rainbow-csv|mec|3.8.0
data-workspace-vscode|ms-|0.5.0
mssql|ms-|1.21.0
sql-bindings-vscode|ms-|0.4.0
sql-database-projects-vscode|ms-|1.3.1
isort|ms-|2023.10.1
python|ms-|2023.20.0
vscode-pylance|ms-|2023.10.50
jupyter|ms-|2023.10.1003070148
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.17
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-slideshow|ms-|0.1.5
remote-ssh|ms-|0.107.0
remote-wsl|ms-|0.81.8
vscode-remote-extensionpack|ms-|0.24.0
live-server|ms-|0.4.11
powershell|ms-|2023.8.0
remote-explorer|ms-|0.4.1
remote-server|ms-|1.5.0
vscode-sanddance|msr|4.1.0
mysql-shell-for-vs-code|Ora|1.13.6
gitblame|wad|10.5.1
twig|wha|1.0.2

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
py29gd2263:30856252
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
282f8724:30602487
89544117:30613380
showlangstatbar:30737416
03d35959:30757346
ecj1e332:30736112
pythonfmttext:30731395
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
pythonnosmt12:30797651
pythonidxpt:30866567
pythonnoceb:30805159
copilotsettingc:30859502
synctok:30869157
dsvsc013:30795093
dsvsc014:30804076
dsvsc015:30845448
pythontestfixt:30871694
pythonregdiag2:30871582
pyreplss1:30865275
pythoncet00cf:30874137
pythontbext0:30864172

```

</details>

**Comment by bpasero** [comment]
I think I had a duplicate for this one from another users, does not seem like a new regression.

**Comment by benibenj** [comment]
@leonjanzen-work could you let us know if you changed any settings related to tabs?

**Comment by bpasero** [comment]
Oh found it, maybe a duplicate of https://github.com/microsoft/vscode/issues/192376

**Comment by leonjanzen-work** [comment]
Yes, it looks like that's the same issue. I'll add to that bug report instead.
