### ISSUE TITLE
[WelcomeUX] Wrongly “unbound” shortcuts in playground

### ISSUE THREAD

**Issue by mquandalle** [Microsoft/vscode#19726]
Hi,

VSCode 1.9 has a new editor playground that explains the different shortcuts in a prose:

![selection_126](https://cloud.githubusercontent.com/assets/1730702/22563900/bb9a0578-e982-11e6-9d66-3cf6f0534b00.png)

On the above screenshot, I'm not sure if the sentence “press unbound or unbound” is the expected text in case there are no shortcuts bound for that particular actions or if it is a bug, but that certainly feels weird.

The second point is that I happen to have shortcuts defined for these actions (“add a new cursor above or below”), so there is certainly a bug here.

I'm on Ubuntu, with a French keyboard layout, if that may be of any relevance.

**Comment by Tyriar** [comment]
Related to https://github.com/Microsoft/vscode/issues/18902

**Comment by chrmarti** [comment]
@mquandalle Have you configured keybindings other than the default ones? If so, could you post that part of your keybindings.json?

**Comment by borekb** [comment]
Having the same issue, these are my keybindings:

```js
[
    {
        "key": "ctrl+d",
        "command": "editor.action.deleteLines",
        "when": "editorTextFocus"
    },
    {
        "key": "ctrl+right",
        "command": "cursorWordStartRight",
        "when": "editorTextFocus"
    },
    {
        "key": "ctrl+shift+right",
        "command": "cursorWordStartRightSelect",
        "when": "editorTextFocus"
    },
    {
        "key": "ctrl+left",
        "command": "cursorWordStartLeft",
        "when": "editorTextFocus"
    },
    {
        "key": "ctrl+shift+left",
        "command": "cursorWordStartLeftSelect",
        "when": "editorTextFocus"
    },
    {
        "key": "ctrl+shift+s",
        "command": "workbench.action.files.saveAll"
    },
    {
        "key": "alt+shift+l",
        "command": "workbench.files.action.showActiveFileInExplorer"
    }
]
```

**Comment by borekb** [comment]
Sorry, deleted my previous comment, the issue was that I had `Ctrl+Alt+UpArrow` and `Ctrl+Alt+DownArrow` redefined.

**Comment by mquandalle** [comment]
@chrmarti, no I haven't customized these keybindings, though if I remember correctly the shortcut was specific to my particular keyboard layout. Weirdly I currently can't find these particular settings (add a cursor above or below) in the left panel of new settings UI.

**Comment by chrmarti** [comment]
@borekb Are you on Linux?

**Comment by mquandalle** [comment]
Yes, Ubuntu 16.04

**Comment by mquandalle** [comment]
I reported the missing setting entries in #19857.

**Comment by mquandalle** [comment]
Hum, I restarted VSCode, and the problem is now fixed:

![selection_130](https://cloud.githubusercontent.com/assets/1730702/22597711/071f049a-ea31-11e6-9e2a-97c4c9fa8047.png)

**Comment by chrmarti** [comment]
Closing as not reproducible. Please reopen if you see this again and append your keybindings.json. Thanks.

**Comment by mquandalle** [comment]
Oh, I actually restarted code with `--disable-extensions` a few hours ago without realizing that this was the reason for the non-reproducibility.

So to be clear, I can reproduce the “press unbound and unbound” message again when starting code normally, with the extensions enable, and the problem doesn't appear if I launch code with `--disable-extensions`.

Do you have some tool to identify which extensions is causing the bug? Or do I have to switch them on and off one by one manually?

**Comment by chrmarti** [comment]
Filed Microsoft/vscode-sublime-keybindings#41.
