### ISSUE TITLE
Star mark or save option for my favorite feature from the release note. 

### ISSUE THREAD

**Issue by imostafizur** [microsoft/vscode#197208]
Every month Microsoft releases so many new features for developers. Among all these new features some are extremely good and helpful for a particular developer, but sometimes we forget about these awesome features. Then we have to check these release notes again and that is time-consuming. Make an option that we can give a star mark to my favorite vscode feature then that can see from vscode whenever I want to see it

**Comment by mjbvz** [comment]
Seems like a complex solution to a niche problem. I suggest you either bookmark sections from the web release notes or creates your own list from the in-product release notes
