### ISSUE TITLE
Custom context menus don't appear

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#197252]
Not sure why this doesn't happen on Insiders for me. Context menus don't appear on Windows where native context menus aren't used.

But the call stack I see is:

1. Showing a context menu fires an event https://github.com/microsoft/vscode/blob/5eb1fa759598db6c69f39331506e7222aecf59e5/src/vs/platform/contextview/browser/contextMenuService.ts#L69
1. This is listened to by the hover service https://github.com/microsoft/vscode/blob/5eb1fa759598db6c69f39331506e7222aecf59e5/src/vs/workbench/services/hover/browser/hoverService.ts#L40 and calls doHideHover
1. doHideHover calls `_contextViewService.hideContextView()`
1. This disposable gets called which immediately closes the context menu https://github.com/microsoft/vscode/blob/5eb1fa759598db6c69f39331506e7222aecf59e5/src/vs/base/browser/ui/contextview/contextview.ts#L364

Probably related to https://github.com/microsoft/vscode/commit/32f0bc498bb20a6e3a09a979a6e055af0b55b684

**Comment by sandy081** [comment]
This change is not yet released to insiders, that could be the reason.
