### ISSUE TITLE
Fedora: @recommended extensions are not showing

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode#19721]
Install 1.9 stable candidate on Fedora (27240e71ef390bf2d66307e677c2a333cebf75af, 64bit, rpm)

- open a .java file
- dialog opens that recommends you to install the Java extension
- Agree to look at the recommended extensions
- extensions view is empty

- enter 'Java' as search string. Extensions are shown (so the connection seems to work)

Same when picking 'Recommended extensions' from the viewlet menu. All other menu items work.

**Comment by aeschli** [comment]
@joaomoreno @sandy081 Any idea? Is it a packaging issue?

**Comment by sandy081** [comment]
I suspect this is a dup of #19613

**Comment by joaomoreno** [comment]
Yes! Only fixed for February. It's not a regression.
