### ISSUE TITLE
My extension is ignoring http.proxyStrictSSL config setting

### ISSUE THREAD

**Issue by Jakobud** [Microsoft/vscode#19725]
- VSCode Version: 1.9.0
- OS Version: OSX 10.11.6

My extension, [vscode-cdnjs](https://github.com/Jakobud/vscode-cdnjs) makes various calls to:

```
https://api.cdnjs.com
```

The extension uses the [GOT](https://github.com/sindresorhus/got) http request library. This http request library is essentially a wrapper around the Node.js http/https modules in order to simplify http requests and the data returned.

I have discovered that if a user is behind a proxy, that [they will get certificate errors](https://github.com/Jakobud/vscode-cdnjs/issues/2) when my extension tries to access `https://api.cdnjs.com`. (The user needs to set `strict-ssl=false` when using `npm` as well so it's definitely an issue with their proxy)

They set the VSCode configuration value `"http.proxyStrictSSL": false` but this did not seem to make a difference.

So my question: Why does my extension appear to ignore the `proxyStrictSSL` configuration setting? I would assume that the `GOT` extension is using VSCode's (Electron) Node.js http/https modules under the hood and would therefore obey this setting. But it doesn't seem to be the case.

Also is there a way to reliably verify if an extension is abiding to this setting?

**Comment by joaomoreno** [comment]
Your extension can read the `http.proxyStrictSSL` configuration setting and use it accordingly when making requests. Not sure if GOT supports the `strictSSL` setting.

**Comment by Jakobud** [comment]
Thank you for the response. So I'm trying to understand this setting a bit more. If an extension makes http/https calls, this setting doesn't set the `rejectUnauthorized` option for all http/https calls? But it's rather just a user preference and any extensions that make http/https calls should look at this setting to determine what to set `rejectUnauthorized` to?

So does this setting not really do anything by itself? Is it only there for extensions to use when making decisions around SSL connections?

**Comment by joaomoreno** [comment]
Yes, the `http/https` modules are stateless, you must use that setting for every request you make.

**Comment by Jakobud** [comment]
Thank you for the clarification. Is this anywhere in the documentation?
