### ISSUE TITLE
Code actions should be available in the context menu for additional discoverablity

### ISSUE THREAD

**Issue by RobbyCBennett** [microsoft/vscode#197261]
Right now, [code actions](https://code.visualstudio.com/docs/editor/refactoring#_code-actions-quick-fixes-and-refactorings) may be hard to discover in comparison with right-clicking something. Code actions have some of the most useful features, such as quick fixes to warnings/errors, ignoring specific warnings, viewing documentation, refactoring, etc. 

Why code actions are not as discoverable, compared to the right-click menu:
- They are listed as the command "Quick Fix" which hides the broad functionality of them.
- The right click menu is far more intuitive.

As an example, the extension "TypeScript and JavaScript Language Features" utilizes the right click menu with some of its code actions; some of them are available under "Refactor...".

The other code actions should also be available on the context menu.

**Comment by mjbvz** [comment]
Our custom widget to that shows information that context menus cannot. Also for discoverability,  the lightbulb in the editor indicates when code actions are available. This+keyboard shortcuts is the most common way users get to code actions, much more so than the context menu
