### ISSUE TITLE
Nearest Quick Fix keyboard shortcut

### ISSUE THREAD

**Issue by Zenthae** [microsoft/vscode#197293]
Type: <b>Bug</b>

If I activate quick fix when my cursor is on a line where there is an error, it says “no code action available”. The new feature state that it should activate the quick fix for the nearest error.

![image](https://github.com/microsoft/vscode/assets/32647899/36859e7b-1a39-4b3c-9fbc-d8c15d4f88b6)

I tested with all extensions disabled and it behave the same. Maybe I misunderstood something ?

VS Code version: Code 1.84.0 (d037ac076cee195194f93ce6fe2bdfe2969cc82d, 2023-11-01T11:29:04.398Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Remote OS version: Linux x64 5.15.90.1-microsoft-standard-WSL2

**Comment by justschen** [comment]
hi @Zenthae this is because there actually are no code actions available. could you give it a try with actual code in a language specific text file/workspace!

**Comment by justschen** [comment]
When hovering over `mkdirss`, there are also no code actions. That is why you're not getting actions at the end of the line.

However, this did reveal a bug where if you did not have the import, the quick fix will not show up.

**Comment by justschen** [comment]
yep, these are better examples! this is similar to what I was encountering here. https://github.com/microsoft/vscode/issues/197654 

It should be fixed in the latest insiders now!
