### ISSUE TITLE
VS Code, Business Central  - Error: An internal error has occurred

### ISSUE THREAD

**Issue by annlii** [microsoft/vscode#197232]
Type: <b>Bug</b>

When I press F5 (publish with debugging) the error Error: An internal error has occurred occurs. I want to debbug Business Central but I am not able to. Any suggestions how to deal with this issue?

VS Code version: Code 1.84.0 (d037ac076cee195194f93ce6fe2bdfe2969cc82d, 2023-11-01T11:29:04.398Z)
OS version: Windows_NT x64 10.0.17763
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD EPYC 7402P 24-Core Processor                (4 x 2800)|
|GPU Status|2d_canvas: unavailable_software<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>opengl: disabled_off<br>rasterization: disabled_software<br>raw_draw: disabled_off_ok<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software<br>webgpu: unavailable_software|
|Load (avg)|undefined|
|Memory (System)|15.77GB (9.12GB free)|
|Process Argv|--crash-reporter-id 9f70674f-be5a-4190-b7ae-846c53067dfc|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
xlf-editor|aar|1.1.52
al-code-outline|and|3.0.53
al-codeactions|dav|1.0.33
al|ms-|13.0.887907
test-adapter-converter|ms-|0.1.8
xliff-sync|rva|1.4.0
code-spell-checker|str|3.0.1
crs-al-language-extension|wal|1.5.29

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscorecescf:30445987
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
py29gd2263:30856252
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
2e4cg342:30602488
89544117:30613380
showlangstatbar:30737416
03d35959:30757346
pythonfmttext:30731395
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
pythonnosmt12:30797651
pythonidxpt:30866567
pythonnoceb:30805159
synctok:30869157
dsvsc013:30795093
dsvsc014:30804076
pythonmhint1:30842940
dsvsc015:30845448
pythontestfixtcf:30871695
pythonregdiag2:30871582
pyreplss1:30865275
pythonmypyd1:30879173
pythoncet0:30874138
pythontbext0:30879054

```

</details>

**Comment by roblourens** [comment]
Please file an issue on the debug extension you're using

**Comment by annlii** [comment]
> Please file an issue on the debug extension you're using

What debug extension you mean? I use standard debug.

**Comment by petrosmaglis** [comment]
I am facing the same issue.
After having restarted sandbox environment, the Business Central debug session is opening but still cannot debug. It is hanging. Any ideas or suggestions? I tried with a previous version of VS Code but nothing changed.

Business Central V23

[Window Title]
Visual Studio Code
Version: 1.84.0 (user setup)
Commit: d037ac076cee195194f93ce6fe2bdfe2969cc82d
Date: 2023-11-01T11:29:04.398Z (2 days ago)
Electron: 25.9.2
ElectronBuildId: 24603566
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.19045
