### ISSUE TITLE
[Feature] Undock view into separate editor

### ISSUE THREAD

**Issue by aiday-mar** [microsoft/vscode#197219]
We were discussing the panel chat with @isidorn, and I said we could perhaps have a command to undock the copilot chat view. I think this is currently possible by placing the view into an editor and then undocking the editor, but could we perhaps have a command which would directly do that? I think it would be useful in the case of copilot-chat because the panel chat takes up quite a lot of space.

**Comment by isidorn** [comment]
@bpasero right now I can open an editor in the aux floating window. How could we make it smoother for the user to do the same for the Chat view (and other views)?

My feeling is that Drag and Drop out of the main windows is the way to make this smooth to use. You pointed me to this https://github.com/microsoft/vscode/issues/8171 Do we know how big of an Electron investment that is?

**Comment by bpasero** [comment]
@aiday-mar if you want you can already easily implement this with the API we have today. See this action for example:

https://github.com/microsoft/vscode/blob/42f5594892084c2db0e08fa52d19288d87698779/src/vs/workbench/browser/parts/editor/editorActions.ts#L2482-L2494

All you need to do is to call `createAuxiliaryEditorPart` and then open an editor in there and thats it. You can open a chat editor there.

As for how to trigger this, there is currently nothing else than actions, i.e. no DND operation possible.

**Comment by bpasero** [comment]
Sounds good. If we end up with many actions like these, maybe we can simplify things and allow a new option on the `IEditorService.openEditor` method. But we can still make this later.

**Comment by eamodio** [comment]
I added support for this in GitLens for our Commit Graph, but it was non-trivial to get working (and I don't have them sharing state). So it would be great if this was something built in that extensions could leverage.

**Comment by bpasero** [comment]
We can certainly have an API for opening editors in floating windows, maybe via a new synthetic view column, but we currently do not allow opening anything but editors in floating windows for the time being.

**Comment by theslyprofessor** [comment]
> @aiday-mar if you want you can already easily implement this with the API we have today. See this action for example:
> 
> https://github.com/microsoft/vscode/blob/42f5594892084c2db0e08fa52d19288d87698779/src/vs/workbench/browser/parts/editor/editorActions.ts#L2482-L2494
> 
> All you need to do is to call `createAuxiliaryEditorPart` and then open an editor in there (into `auxiliaryEditorPart.activeGroup`) and thats it. You can open a chat editor there.
> 
> As for how to trigger this, there is currently nothing else than actions, i.e. no DND operation possible. We would have to figure out how to detect a drop that occurs outside of the window.

Is this code intended to allow us to undock github copilot's chat? Where is a good resource for how to implement this into my environment? I don't know which file to put all this into.

**Comment by aiday-mar** [comment]
To verify:

- Install the Copilot and the Copilot Chat extensions in VS Code. Open the Panel Chat view.
- Send a couple of requests to Copilot, ask several questions.
- Click on the `Open Session in New Window` button in the three dots menu. 
- Verify the chat session appears in a separate window.

<img width="760" alt="Screenshot 2023-11-27 at 12 38 17" src="https://github.com/microsoft/vscode/assets/61460952/ead04df9-01c3-4ca9-9f3f-1c79e10f5540">

**Comment by isidorn** [comment]
Works well -> verified

I just could not figure out why am I getting the 🔒 icon in the title area in the floating window? @bpasero might know?
![Screenshot 2023-11-27 at 14 08 31](https://github.com/microsoft/vscode/assets/1926584/ca5f5802-8155-43e0-86dc-ca4fbd0ed963)

**Comment by gjsjohnmurray** [comment]
All aux windows surface that button intentionally as it seems more likely that users may want to prevent the window from being used by other documents.
