### ISSUE TITLE
Is Visual Studio Code eventually going to replace Visual Studio?

### ISSUE THREAD

**Issue by soljohnston777** [Microsoft/vscode#19722]
Is Visual Studio Code eventually going to replace Visual Studio?

It is simple to use, yet powerful.  
Programmers actually like it!

I think if Microsoft should go towards this direction.  Especially if the libraries could be picked and used easily throughout instead of like in Visual Studio where the code breaks at every line as you are typing it (then you have to pick options for that line).

I never liked that Visual studio is not very intuitive.  Visual Studio Code, on the other hand, I welcome using for all my projects because of it's simplicity and the ability to control debuggers better.

**Comment by chrisdias** [comment]
I'm glad you like VS Code, but no, it won't replace Visual Studio :). There are many reasons for this -
 VS has a ton of functionality that doesn't make sense to simply rebuild in VS Code, the user models are different - for example, VS Code is file/folder based and loosely coupled to other tools whereas VS provides an integrated end to end experience, and more.
