### ISSUE TITLE
Improve Top Activity Bar Overflow Handling 

### ISSUE THREAD

**Issue by dlschmidt** [microsoft/vscode#197281]
The new position setting is a great addition to VSCode to gain more horizontal space! However, the overflow handling is currently a bit unfortunate. If there are additional actions which don't fit in one line, the tabs will be truncated.
<img width="267" alt="Bildschirmfoto 2023-11-02 um 22 44 55" src="https://github.com/microsoft/vscode/assets/20640295/fd7132a1-49ce-40fe-bab4-6edcf417a44e">
<img width="267" alt="Bildschirmfoto 2023-11-02 um 22 45 01" src="https://github.com/microsoft/vscode/assets/20640295/7ef8949e-2814-4bff-9027-28574410ee3a">

It would be great to change this behaviour for more consistency, i.e. by putting the actions one line below. If neccessary, this could be changed via a setting or configuration item.

Further, the title could be still be shown to fill the blank the empty space left to the actions (if they would be placed one line below). So, just how it is done currently when the activity bar is placed at the side as usual:
<img width="304" alt="image" src="https://github.com/microsoft/vscode/assets/20640295/8dfec6db-b9a6-4a2a-a2a6-c3eb6f56a050">

**Comment by gjsjohnmurray** [comment]
See #197285

The Extensions one seems to be a bad citizen.

**Comment by dlschmidt** [comment]
No idea how I missed to see that its only a problem with the extensions menu.

I will close it in favour of #197285
