### ISSUE TITLE
[Accessibility] Support smart accessible terminal buffer mode

### ISSUE THREAD

**Issue by jooyoungseo** [microsoft/vscode#197244]
Type: <b>Feature Request</b>

CC @meganrogge 

Please consider auto-activiating accessible view in terminal when user hit enter key. In most cases, screen reader users want to open accessible view after executing command in terminal. Thus, pressing Enter key can do:

1. Send the current command to terminal.

1. Open Accessible View immediately.

Rather than having this as the default mode, we could consider adding this as a custom user setting.

VS Code version: Code - Insiders 1.85.0-insider (a9d8fbca9ec9a7914f2077a83ca66a08c7e10f83, 2023-11-02T09:02:24.464Z)
OS version: Windows_NT x64 10.0.22621
Modes:

**Comment by meganrogge** [comment]
This makes sense. @Tyriar let us know if you have any thoughts.

**Comment by jooyoungseo** [comment]
I imagine this mode can boost the productivity because VSCode now send user typing in Accessible View directly to the active terminal. If this mode is added, users will experience more seamless round trip between terminal input and accessible view without having to press Alt+F2 and ESC.

**Comment by meganrogge** [comment]
To verify, enable `terminal.integrated.accessibleViewFocusOnCommandExecution`. Run a command in the terminal. The accessible view should open.
