### ISSUE TITLE
html.format.wrapAttributes: "force" and "force-align" breaks indentation

### ISSUE THREAD

**Issue by tiago-plank** [Microsoft/vscode#19727]
- VSCode Version: Code 1.9.0 (27240e71ef390bf2d66307e677c2a333cebf75af, 2017-02-02T08:31:00.827Z)
- OS Version: Windows_NT ia32 6.3.9600
- Extensions: All extensions disabled

---

Steps to Reproduce:

1. Set html.format.wrapAttributes to `force ` or `force-align`
2. Write an  html tag with 2 or more attributes
3. Execute `editor.action.formatDocument`

Sample html:

```
<div attr-1 attr-2 attr-3>
    <p>Test</p>
</div>
```

Expected result:

```
<div attr-1
    attr-2
    attr-3>
    <p>Test</p>
</div>
```

Actual result:

```
<div attr-1
    attr-2
    attr-3>
    <p>Test</p>
    </div>

```

**Comment by eamodio** [comment]
I also didn't notice a difference between `force` and `force-align`, I expected `force-align` to align the attributes to the first unwrapped attribute, but that doesn't seem to be the case.

**Comment by kf-ireneuszpatalas** [comment]
Hi guys,

I don't know why, but it's another application using jsbeautifier which haven't read the documentation carefully. The correct option for wrapAttributes is **force-aligned**, not **force-align**. 
VS Code will treat is as warning, but it will work and correctly wrap attributes and align them to first one.
Still the result is not correct:
```HTML
<div attr-1
     attr-2
     attr-3>
    <p>Test</p>
    </div>
```

That's another story and is already reported here beautify-web/js-beautify#1103

**Comment by aeschli** [comment]
Good catch with the wrong settings schema: I created https://github.com/Microsoft/vscode/issues/19849, planed for the next rebuild.

**Comment by aeschli** [comment]
Closing this issue. Waiting for beautify-web/js-beautify#1103 to be fixed.

**Comment by Montago** [comment]
Would it be possible to extend the options of wrapping with "auto-align" ??

"force-align" will force wrapping + aligning them...

but let say i don't want to wrap EVERY SINGLE HTML ELEMENT, but only the long ones - and then do them manually .. 

so, "auto-align" would only align those that are already wrapped.

**Comment by aeschli** [comment]
@Montago Please file suggestions to https://github.com/beautify-web/js-beautify which is the formatter we use.
