### ISSUE TITLE
Activity Bar doesn't fill full width in Top position

### ISSUE THREAD

**Issue by ris58h** [microsoft/vscode#197216]
Steps to Reproduce:

1. Set `workbench.activityBar.location` setting to `top`.

Expected result:

Activity Bar fills the available horizontal space and shows as many items as possible.

Actual result:

Activity Bar has an unnecessary left padding/margin.

https://github.com/microsoft/vscode/assets/511242/534fadc4-efdb-4211-9a59-f28533a09aa7

**Comment by ris58h** [comment]
Probably related to https://github.com/microsoft/vscode/issues/197285

**Comment by sharkooon** [comment]
Having the same issue, those 2 icons (explorer and Extentions) will fit correctly in top bar, but now it shows large empty space and 3 dots for Additional Views.

<img width="412" alt="Scherm­afbeelding 2023-11-06 om 19 00 34" src="https://github.com/microsoft/vscode/assets/533123/e957b48a-37bd-499c-b5f1-19f4fa514a9f">
<img width="375" alt="Scherm­afbeelding 2023-11-06 om 19 00 27" src="https://github.com/microsoft/vscode/assets/533123/e24434bd-58c5-4c08-89f6-f8ddbddc0cab">
