### ISSUE TITLE
VS Code color picker doing some weird stuff

### ISSUE THREAD

**Issue by karo-yousefi** [microsoft/vscode#197277]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.84.0
- OS Version: Windows_NT x64 10.0.19045

Steps to Reproduce:

The built-in color picker apparently is bugged. 

When I was using the color picker in a CSS file, some weird things were happening. Here is a video showcasing the problem:

https://github.com/microsoft/vscode/assets/88065530/94aab2fd-d8d4-488c-8e57-65053cce8267

If the video is not clear enough. Here is the problem:

1. Any click on the color picker menu (on **anywhere**) Will close the menu. Which I guess is not intended cause most of the time you need multiple clicks to choose a color. As far as I know, Closing should only happen if  the user clicks outside of the menu,

2. Sometimes the color picker generates another color code (hex or RGB or ...) and replaces some parts of the original color code, Making some unusable color codes. For example, adding a hex color code to an RGB one. 

3. The color code mode sometimes resets to RGB when the user opens the menu and it does not remember the color code. So If you want to use hex, Every single time you need to change the color code mode back to hex.

**Comment by kraviznina98** [comment]
Same problem here too with color picker closing prematurely.

**Comment by razielDE** [comment]
Same here! Thank you for posting this.
I'm experiencing everything that you mentioned:
- closes on first click, when I'd expect it to stay open so that I can keep tweaking the color;
- resets to RGB when I'm in HEX;
- pastes RGB color code into the previous HEX code, making a weird looking unusable color.

This was definitely working fine not long ago.

**Comment by paczaj-code** [comment]
Same problem - really weird behaviour.

**Comment by shrfrn** [comment]
Same here

**Comment by sangmort** [comment]
Another person having the same exact issue. 

The switching to RGB when I'm in hex is the most infuriating part.

**Comment by aiday-mar** [comment]
Hi thank you for filing the issue. This issue should be closed by the following PR which was developed by a community developer https://github.com/microsoft/vscode/pull/198100. The fix should be inside the next insiders build quite soon and the next stable build in around a month.

**Comment by murningstar** [comment]
Still having this issue

**Comment by aiday-mar** [comment]
Hi @murningstar can you please provide here the version number of the editor you are seeing, you can find it under `About visual studio code - (insiders0` in the global toolbar.

**Comment by murningstar** [comment]
@aiday-mar, hi! 
Version: 1.84.2 (user setup)
Commit: 1a5daa3a0231a0fbba4f14db7ec463cf99d7768e
Date: 2023-11-09T10:51:52.184Z
Electron: 25.9.2
ElectronBuildId: 24603566
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.19045

**Comment by aiday-mar** [comment]
Hi @murningstar thank you for responding. Yes it appears you are on the stable version of VS Code which does not contain the fix yet. If you would like to have the fix now, you can install VS Code Insiders which is updated every day on the following link (https://code.visualstudio.com/insiders/)

**Comment by therpgmaster** [comment]
When is this fix planned for mainstream release?

**Comment by aiday-mar** [comment]
Hi @therpgmaster, the mainstream release should come out end of this week. The fix is in 1.85.

**Comment by kalecake** [comment]
I'm having the same issue :')
