### ISSUE TITLE
Typescript Implemenation Code Lens sometimes missing references

### ISSUE THREAD

**Issue by rchl** [microsoft/vscode#197286]
Type: <b>Bug</b>

Typescript Language Features can report incorrect count of implementation references with typescript's "Implementation" code lenses enabled.

To reproduce:
1. Enable the `typescript.implementationsCodeLens.enabled` option
2. Checkout vscode repo
3. Open this file and location in the editor: https://github.com/microsoft/vscode/blob/0acd2722684e02649a30cd7e4ef0f5c4772e5ab2/extensions/typescript-language-features/src/languageFeatures/codeLens/baseCodeLensProvider.ts#L59-L59

You should see "2 implementations" code lens above the `extractSymbol` abstract method.

![Screenshot 2023-11-02 at 23 12 40](https://github.com/microsoft/vscode/assets/153197/bba47b76-74ba-41b6-b7b6-70d261f518df)

Now switch TypeScript version from the status field to a workspace version, for example, and notice that it shows "0 implementations" now.

![Screenshot 2023-11-02 at 23 13 25](https://github.com/microsoft/vscode/assets/153197/cb9aefa0-475a-4605-8fab-4ac2f898dab5)

The issue is not with the specific Typescript version but with the fact that resolving code lenses very early during tserver initialization sends the `implementation` request to the "syntax" server which returns no references. Making some edit to the file after the fact (once the project has initialized) sends the request to the "semantic" server which returns correct amount of references.

This issue can appear on just opening the file in theory but it's hard to reproduce due to the fact that different extensions initialize and seem to invalidate the code lenses cache and make vscode retry code lens resolving, hiding the issue.

VS Code version: Code 1.84.0 (Universal) (d037ac076cee195194f93ce6fe2bdfe2969cc82d, 2023-11-01T11:30:19.406Z)
OS version: Darwin arm64 23.1.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M2 Pro (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|2, 3, 2|
|Memory (System)|16.00GB (0.21GB free)|
|Process Argv|--crash-reporter-id fdbd5e9e-6baa-48b2-9384-5ef393218a3d|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
ruff|cha|2023.44.0
volarjs-labs|joh|1.9.1
vscode-docker|ms-|1.27.0
python|ms-|2023.20.0
vscode-pylance|ms-|2023.10.50
jupyter|ms-|2023.10.1003070148
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.17
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-slideshow|ms-|0.1.5
remote-containers|ms-|0.321.0
volar|Vue|1.8.23

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
py29gd2263:30856252
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
282f8724:30602487
89544117:30613380
2i9eh265:30646982
showlangstatbar:30737416
03d35959:30757346
pythonfmttext:30731395
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
pythonnosmt12:30797651
pythonidxpt:30866567
pythonnoceb:30805159
synctok:30869157
dsvsc013:30795093
dsvsc014:30804076
dsvsc015:30845448
pythontestfixt:30871694
pythonregdiag2:30871582
pyreplss1:30879912
pythonmypyd1:30879173
pythoncet0:30874138
pythontbext0:30879054

```

</details>

**Comment by eleanorjboyd** [comment]
@mjbvz, how do I test this? Specifically `Now switch TypeScript version from the status field to a workspace version, ` is a part I am unsure about the rest of the steps seem clear.

**Comment by mjbvz** [comment]
@eleanorjboyd In this case you need:

1. Create an abstract class that is implemented in another files:

```ts
// foo.ts
export abstract class Foo {
    abstract bar(): void;
}
```

```ts
import { Foo } from './foo'

class CFoo extends Foo {
  bar() {}
}
```

2. Open only the file with the abstract class (`foo.ts`)
1. Run the `Restart TS Server command`

Then confirm that the implementations code lens shows `1 implementation` instead of zero
