### ISSUE TITLE
Incorrect tab titles showing for `window.nativeTabs`

### ISSUE THREAD

**Issue by henryuj** [microsoft/vscode#197225]
Type: <b>Bug</b>

### Reproduction:
- Enable `window.nativeTabs`
- Open 2 tabs with different folders
- Click on tab 1
- Open a tab with `workbench.action.newWindowTab` (from the command palette or hotkey) - we'll call this tab 2

### Actual result:
- Tab 2 takes the title of tab 3 (angular-tour-of-heroes)
- Tab 3 takes the title of tab 2 (Visual Studio Code)

<img width="1449" alt="image" src="https://github.com/microsoft/vscode/assets/149679211/f4ebba0e-4f58-48e4-a71f-219d6ffdea1e">

<img width="1434" alt="image" src="https://github.com/microsoft/vscode/assets/149679211/022121b2-81c8-4985-a0af-a2dff971f219">

### Expected result 
- Tab 2 should have the title of "Visual Studio Code"
- Tab 3 should keep it's title of "angular-tour-of-heroes"

VS Code version: Code 1.84.0 (Universal) (d037ac076cee195194f93ce6fe2bdfe2969cc82d, 2023-11-01T11:30:19.406Z)
OS version: Darwin arm64 23.1.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.06GB free)|
|Process Argv|--crash-reporter-id 12c71725-c76a-42f7-a224-56b26c5fac71|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (62)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|3.0.2
vscode-css-formatter|aes|1.0.2
project-manager|ale|12.7.0
vscode-sqlite|ale|0.14.1
ng-template|Ang|16.1.8
vscode-django|bat|1.14.0
vscode-intelephense-client|bme|1.9.5
vscode-tailwindcss|bra|0.10.2
vscode-jetbrains-icon-theme|cha|2.11.1
vscode-eslint|dba|2.4.2
binary-plist|dni|0.11.3
gitlens|eam|14.4.1
prettier-vscode|esb|10.1.0
auto-rename-tag|for|0.1.10
terminal|for|0.0.10
prettier-sql-vscode|inf|1.6.0
solidity|Jua|0.0.165
vscode-sshfs|Kel|1.26.1
auto-comment-blocks|kev|1.0.1
vscode-clangd|llv|0.1.24
markdown-converter|man|5.2.1
pretty-formatter|mbl|0.2.2
rainbow-csv|mec|3.8.0
git-graph|mhu|1.30.0
dotenv|mik|1.0.1
vscode-docker|ms-|1.27.0
black-formatter|ms-|2023.4.1
isort|ms-|2023.10.1
python|ms-|2023.20.0
vscode-pylance|ms-|2023.10.50
jupyter|ms-|2023.10.1003070148
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.17
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-slideshow|ms-|0.1.5
vsliveshare|ms-|1.0.5892
vscode-open-iterm2|mus|0.0.4
hide-gitignored|npx|1.1.0
indent-rainbow|ode|8.3.1
laravel-blade|one|1.34.0
prisma|Pri|5.5.2
java|red|1.24.0
vscode-xml|red|0.26.1
phpdoc-comment-vscode-plugin|rex|1.3.0
llvm|RRe|0.1.1
scala|sca|0.5.7
markdown-preview-enhanced|shd|0.8.10
javafx-support|shr|0.0.1
autoimport|ste|1.5.4
svelte-vscode|sve|107.12.0
logos-vscode|tal|1.0.1
even-better-toml|tam|0.19.2
pdf|tom|1.2.2
in-your-face-incredible|TTO|1.1.0
intellicode-api-usage-examples|Vis|0.2.8
vscodeintellicode|Vis|1.2.30
vscode-java-debug|vsc|0.55.0
vscode-java-pack|vsc|0.25.15
vscode-java-test|vsc|0.40.1
vscode-maven|vsc|0.43.0
volar|Vue|1.8.22
copy-with-line-numbers|yas|0.0.4

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
py29gd2263:30856252
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
3biah626:30602489
f6dab269:30613381
2i9eh265:30646982
showlangstatbar:30737416
03d35959:30757346
pythonfmttext:30731395
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
pythonnosmt12:30797651
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30869155
dsvsc013:30795093
dsvsc014:30804076
dsvsc015:30845448
pythontestfixtcf:30871695
pythonregdiag2:30871582
pyreplss1:30865275
pythonmypyd1:30879173
pythoncet0:30874138
pythontbext0:30879054

```

</details>

**Comment by bpasero** [comment]
But for us to address this, we need a reliable repro.

**Comment by henryuj** [comment]
@bpasero I've managed to create a repro! The initial post has been edited to show this now.

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by henryuj** [comment]
Successfully reproduced on nightly build

Version: 1.85.0-insider (Universal)
Commit: a9d8fbca9ec9a7914f2077a83ca66a08c7e10f83
Date: 2023-11-02T09:04:13.888Z
Electron: 25.9.2
ElectronBuildId: 24603566
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Darwin arm64 23.1.0

**Comment by henryuj** [comment]
It may be worth noting this is happening on macOS Sonoma 14.1

**Comment by bpasero** [comment]
I cannot reproduce and I am on macOS Sonoma 14.1 as well:

![Recording 2023-11-02 at 17 14 32](https://github.com/microsoft/vscode/assets/900690/c65553fe-a57a-4f67-a901-99205945ed03)

For me the 2nd tab gets the correct window title as far as I can tell.

**Comment by henryli17** [comment]
Here is a video of me reproducing the issue on another machine (M1 Air 2020)

https://github.com/microsoft/vscode/assets/44710606/75b7acb4-6ea9-4515-bced-67e7c6d3a509

**Comment by bpasero** [comment]
I followed your exact steps and can also not reproduce. I wonder if any setting you configured triggers this.

Can you try to run `code --disable-extensions --user-data-dir <directory>` where `<directory>` is an empty folder? This will ensure Code is starting with a fresh data directory, e.g. no specific settings and without any extensions running.

**Comment by henryuj** [comment]
Still get the same issue - window title is "Welcome - Movies" but tab title is "Welcome"

![image](https://github.com/microsoft/vscode/assets/149679211/41ab1383-2a41-46e8-9505-89c1db395594)

**Comment by bpasero** [comment]
Sorry I am not sure what this is...

**Comment by henryuj** [comment]
I have a feeling this is an issue with macOS Sonoma as this only started happening after I updated.

I've also tried an older version of VS Code (1.80) where I didn't experience this issue previously and am able to reproduce it there. Will close this issue for now.
