### ISSUE TITLE
workbench.action.maximizeEditor command is missing

### ISSUE THREAD

**Issue by AnrDaemon** [microsoft/vscode#197227]
Type: <b>Bug</b>

I've had a keybind bound to the `workbench.action.maximizeEditor` command I've been using repeatedly. Now it is gone.

The new `workbench.action.maximizeEditorHideSidebar` is a no replacement for it, as it **hides** all other editor groups. Not what I wanted from it. I still need other group's tabs clearly visible, as they are opened project files I use as references. Sometimes opening them side by side, sometimes collapsing to only the headers. But never I want them hidden.

VS Code version: Code 1.84.0 (d037ac076cee195194f93ce6fe2bdfe2969cc82d, 2023-11-01T11:29:04.398Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-8145U CPU @ 2.10GHz (4 x 2304)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|7.86GB (1.15GB free)|
|Process Argv|--folder-uri file:///d%3A/Profiles/anrdaemon/Documents/hk/invapi-php|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by AnrDaemon** [comment]
An alternate solution for me would be to allow the so-called "web panels" - side bar panels containing open project files, read-only with a button to reopen them for editing.

**Comment by benibenj** [comment]
You can use the command `workbench.action.toggleMaximizeEditorGroup` to maximize/unmaximize the active editor group. If you want to have different shortcuts depending on the maximized state, you can use context keys with your shortcuts (`When` state).

With `maximizedEditorGroup` you make your shortcut only run if it is maximized (or not).
`multipleEditorGroup` (true if more then 1 editor group) could also be helpful depending on the shortcuts you are creating.

**Comment by benibenj** [comment]
We renamed the old maximize feature to `expand`. You can use the `Expand Editor Group` (`workbench.action.minimizeOtherEditors`) command.

**Comment by AnrDaemon** [comment]
The `workbench.action.minimizeOtherEditorsHideSidebar` command would be a good addition to the mix.

**Comment by benibenj** [comment]
You are right, I will add it back. Until it's available, you can use the `workbench.action.closeSidebar` command together with `workbench.action.minimizeOtherEditors`.

**Comment by AnrDaemon** [comment]
Sorry, I don't quite get it. How would I call two commands with a single keybind?

**Comment by benibenj** [comment]
You can run multiple commands with a single shortcut in the following way:
`{
		"key": "ctrl+k",
		"command": "runCommands",
		"args": {
			"commands": [
				"workbench.action.closeSidebar",
				"workbench.action.minimizeOtherEditors"
			]
		}
	}`
