### ISSUE TITLE
Activity Bar Position Top - missing Accounts and Manage icons

### ISSUE THREAD

**Issue by jano23** [microsoft/vscode#197280]
Does this issue occur when all extensions are disabled?: Yes

Version: 1.84.0 (system setup)
Date: 2023-11-01T11:29:04.398Z
Electron: 25.9.2
ElectronBuildId: 24603566
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.22621

Steps to Reproduce:

1.  Right-click Activity bar
2. Activity Bar Position > Top

**Comment by gjsjohnmurray** [comment]
Don't you have them here?

![image](https://github.com/microsoft/vscode/assets/6726799/fd7ac7fa-9584-4cc5-8e4e-a6de5f2ea79d)

**Comment by jano23** [comment]
Ok, yes!
Had not looked there.
Thanks!
This can be closed

**Comment by gerryqd** [comment]
> Don't you have them here?
> 
> ![image](https://user-images.githubusercontent.com/6726799/280146838-fd7ac7fa-9584-4cc5-8e4e-a6de5f2ea79d.png)

While, can I have option to hide the account icon?

If I set "Activity Bar position" to "Side", I can hide the icon, while after I switch its position to "Top", the "Account" icon displays.

**Comment by gjsjohnmurray** [comment]
@gerryqd there is another open issue about that.

@jano23 please close your issue at the GitHub site.
