### ISSUE TITLE
Unpin Editor button displayed over unpinned editors

### ISSUE THREAD

**Issue by IllusionMH** [microsoft/vscode#197230]
Type: <b>Bug</b>

It's unexpected that "Unpin Editor" button is displayed when I don't have pinned editors on separate row, and more annoying that it covers icon/title of other editors.
![image](https://github.com/microsoft/vscode/assets/1312662/a172f3fa-8016-4cc2-8985-abe1bf039fa4)
![image](https://github.com/microsoft/vscode/assets/1312662/2ea651e6-33fd-4362-9f03-69fe7a9a7b14)

VS Code version: Code - Insiders 1.85.0-insider (a9d8fbca9ec9a7914f2077a83ca66a08c7e10f83, 2023-11-02T09:02:24.464Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz (8 x 2995)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.50GB (17.69GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by bpasero** [comment]
🤔 is this a regression from https://github.com/microsoft/vscode/pull/196896 ?

**Comment by benibenj** [comment]
@IllusionMH could you tell me which editor tabs related settings you are using? (`showTabs`, `pinned tab sizing`, `tab-sizing`, `pinned tabs on separate row`, `tab action location`, `wrap tabs` ...)

**Comment by IllusionMH** [comment]
@benibenj From that list of settings all are default with only "workbench.editor.pinnedTabSizing" changed to `compact`

```json
"workbench.editor.showTabs": "multiple",
"workbench.editor.tabSizing": "fit",
"workbench.editor.wrapTabs": false,
"workbench.editor.pinnedTabSizing": "compact", //changed
"workbench.editor.pinnedTabsOnSeparateRow": false,
"workbench.editor.tabActionLocation": "right"
```

Let me know if you need more info

**Comment by bpasero** [comment]
@benibenj please do not forget to set milestones for your issues

**Comment by IllusionMH** [comment]
Works as expected now! Thanks!
