### ISSUE TITLE
Floating terminal

### ISSUE THREAD

**Issue by Morgy93** [microsoft/vscode#197240]
Type: <b>Feature Request</b>

Since the floating tabs are not available, I'd like to have a floating terminal.

VS Code version: Code - Insiders 1.84.0-insider (d037ac076cee195194f93ce6fe2bdfe2969cc82d, 2023-11-01T10:21:14.199Z)
OS version: Darwin arm64 23.0.0
Modes:

**Comment by Morgy93** [comment]
Related https://github.com/microsoft/vscode/issues/10121#issuecomment-1790316086

**Comment by meganrogge** [comment]
You can do this by creating a terminal in the editor area and then running the command in [#10121 (comment)](https://github.com/microsoft/vscode/issues/10121#issuecomment-1790316086)
