### ISSUE TITLE
View: Focus Activity Bar is broken when Activity Bar Position Hidden

### ISSUE THREAD

**Issue by dacapoday** [microsoft/vscode#197297]
Steps to Reproduce:

1. Select the Activity Bar Position as Hidden
2. Call Command: View: Focus Activity Bar 

Then:
![xxx1](https://github.com/microsoft/vscode/assets/9378047/b07ff566-9034-47e3-b3ec-451bedf5c3a4)

Activity Bar still takes up screen space, but doesn't display the icons

Version: 1.84.0
Commit: d037ac076cee195194f93ce6fe2bdfe2969cc82d
Date: 2023-11-01T11:29:04.398Z
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Code/1.84.0 Chrome/114.0.5735.289 Electron/25.9.2 Safari/537.36

**Comment by gjsjohnmurray** [comment]
Probably #197169

**Comment by sandy081** [comment]
Not related to https://github.com/microsoft/vscode/issues/197169
