### ISSUE TITLE
v1.9 not receiving ENV vars when opened from console

### ISSUE THREAD

**Issue by rgamba** [Microsoft/vscode#19729]
- VSCode Version: 1.9
- OS Version: 10.11.5

Steps to Reproduce:

1. `$ export MYVAR=test`
2. `code .`
3. Inside the vscode terminal `exho MYVAR` <- variables are not passed! This screws with my virtualenv. Is there a way around this?

Thanks

**Comment by Tyriar** [comment]
Did you have an instance of VS Code already running? VS Code's environment is set when you launch the first window.

**Comment by rgamba** [comment]
That was the problem, thanks! BTW awesome improvements in this version.

**Comment by Tyriar** [comment]
Great to hear! :smiley:
