### ISSUE TITLE
Focus bar on side bar view isn't shown without activity bar

### ISSUE THREAD

**Issue by mybearworld** [microsoft/vscode#197235]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.84.0
- OS Version: Windows 11

Steps to Reproduce:

1. Put the activity bar top or hidden
2. Restore the window if necessary - this doesn't occur when maximized
3. Click on the explorer bar
   ![The explorer focused with the activity bar hidden in VSCode. While there is a border to signify the focus, it's not shown on the left.](https://github.com/microsoft/vscode/assets/130385691/62012ecd-ec1f-476a-a644-534f51b9efe6)

Related to #197178 - fixing that would probably fix this

**Comment by T-256** [comment]
do not related, but sash is thinner on find widget of terminal too:
![image](https://github.com/microsoft/vscode/assets/132141463/45f6e798-e593-4362-b491-12496620eebb)

versus editor find widget:
![image](https://github.com/microsoft/vscode/assets/132141463/53a39c51-c8ac-4f14-9024-a66c583a5c83)
