### ISSUE TITLE
running vs code on ubuntu

### ISSUE THREAD

**Issue by sawankumawat** [microsoft/vscode#197348]
Type: <b>Bug</b>

From last two months I am facing problems in running the vscode in ubuntu. While opening the vs code from the terminal or directly from the icon, it shows just pixelated boxes and the editor does not open, but when I open it using the option "Launch using dedicated graphics card
![Screenshot from 2023-11-03 16-30-09](https://github.com/microsoft/vscode/assets/124118453/63270aea-e6d9-4d64-8199-bb660c55808e)
", then only it opens. I tried reinstalling it but then the same problems again appears after some time. I am attaching the screenshot for the reference 

VS Code version: Code 1.84.0 (d037ac076cee195194f93ce6fe2bdfe2969cc82d, 2023-11-01T11:28:21.782Z)
OS version: Linux x64 5.15.0-88-generic
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 5800H with Radeon Graphics (16 x 1938)|
|GPU Status|2d_canvas: unavailable_software<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>opengl: disabled_off<br>rasterization: disabled_software<br>raw_draw: disabled_off_ok<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software<br>webgpu: disabled_off|
|Load (avg)|1, 1, 1|
|Memory (System)|15.03GB (10.68GB free)|
|Process Argv|--unity-launch --crash-reporter-id d53561c3-8b73-4e2a-8f81-69f89b250ff7|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
py29gd2263:30880072
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
282f8724:30602487
89544117:30613380
showlangstatbar:30737416
03d35959:30757346
pythonfmttext:30731395
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
pythonnosmt12:30797651
pythonidxpt:30866567
pythonnoceb:30805159
dsvsc013:30795093
dsvsc014:30804076
dsvsc015:30845448
pythontestfixtcf:30871695
pythonregdiag2:30871582
pythonmypyd1:30879173
pythoncet0:30874138
pythontbext0:30879054

```

</details>

**Comment by deepak1556** [comment]
Can you attach the logs from `code --verbose`

**Comment by sawankumawat** [comment]
I am attaching the terminal output for code --verbose in the log file.
[Uploading stdout.log…]()

**Comment by deepak1556** [comment]
The log file link is incorrect, can you please reattach it.

**Comment by sawankumawat** [comment]
Please find the log file in the link below
[https://drive.google.com/file/d/1O-KWii645K_dtRexCn43MrYqSxEPwFDJ/view?usp=sharing](url)

**Comment by deepak1556** [comment]
Thanks for the logs, it is the same issue as https://github.com/microsoft/vscode/issues/190437

Remove the gpu cache as a temporary workaround `rm -rf ~/config/Code/GPUCache`
