### ISSUE TITLE
DirtyDiffWidget should respect config diffEditor.ignoreTrimWhitespace

### ISSUE THREAD

**Issue by hsfzxjy** [microsoft/vscode#197339]
Type: **bug**

Currently the mini diff editor created by clicking gutter won't show whitespace-only changes, which should indeed respect config `diffEditor.ignoreTrimWhitespace`.

![image](https://github.com/microsoft/vscode/assets/4702188/5fb225e1-e6f9-4f0e-9caf-a86709ffc3e8)

Version: 1.84.0
Commit: d037ac076cee195194f93ce6fe2bdfe2969cc82d
Date: 2023-11-01T11:28:21.782Z
Electron: 25.9.2
ElectronBuildId: 24603566
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Linux x64 5.15.0-87-generic

**Comment by hediet** [comment]
Thanks! I just enabled it now always.
I don't think it should consider the setting, as files appear changed in git if there are whitespace changes.
