### ISSUE TITLE
Commit message box rendered weirdly when SCM view is unhidden

### ISSUE THREAD

**Issue by ulugbekna** [microsoft/vscode#197350]
Commit message rendered weirdly 

![Image](https://github.com/microsoft/vscode/assets/16353531/a4df43c6-d822-4a77-8105-d7ab0b9ac452)

# Repro: 

I don't have exact steps, so

1. Open SCM view 
2. Try hiding the sidebar, switching to explorer view, then switch back to SCM view 

# Version

Version: 1.85.0-insider
Commit: a9d8fbca9ec9a7914f2077a83ca66a08c7e10f83
Date: 2023-11-02T09:12:38.373Z
Electron: 25.9.2
ElectronBuildId: 24603566
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Darwin arm64 23.0.0

**Comment by lszomoru** [comment]
I believe that this should be fixed. 
Closing it optimistically but please feel free to reopen in case you are able to reproduce.
