### ISSUE TITLE
Allow to show editor actions in title bar even when tabs are visible

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#197343]
The new support for showing editor actions in the title is very nice, but limited to when tabs are disabled. I suggest to make this a setting that users can turn on irrespective of how tabs are displayed.

This could possibly help for:
* https://github.com/microsoft/vscode/issues/115136
* https://github.com/microsoft/vscode/issues/196361

**Comment by gjsjohnmurray** [comment]
Presumably related to #196609

**Comment by benibenj** [comment]
Closing as this has been in insiders for 2 weeks. I also added toggling the setting in the title bar when tabs are hidden. (#198494)

**Comment by gjsjohnmurray** [comment]
Looking great, except that until #198494 lands in the next Insiders build steps 6 and 7 aren't possible.
