### ISSUE TITLE
VSCode doesn't update to 1.9 on macOS Sierra

### ISSUE THREAD

**Issue by DethAriel** [Microsoft/vscode#19730]
- VSCode Version: 1.8.1
- OS Version: macOS Sierra 10.12.3

Steps to Reproduce:

1. Open VSCode
2. Code / Check for updates
3. Observe a popup saying "An update is ready to install. Visual Studio Code is trying to add a new helper tool", which asks for credentials
4. Enter credentials, hit "Add Helper" button
5. Now a notification in VSCode appears - hit "Update Now"
6. VSCode closes after that
7. ???
8. No profit - it does not start again by itself. Opening it manually results in returning to step 1.

Restart didn't help either, though this was a desperate thing to try

**Comment by arkon** [comment]
I updated to 1.9.0 using macOS 10.12.3 as well, but I didn't encounter anything about a helper, and it worked fine.

**Comment by DethAriel** [comment]
@arkon hm, I'm wondering what that helper thing is...

**Comment by aliokan** [comment]
the same here, with a fresh install (2 days ago) 
- VSCode Version: 1.8.1
- OS Version: macOS Sierra 10.12.3
- MacBook Pro (13-inch, 2016, Two Thunderbolt 3 ports)

**Comment by ihappycoder** [comment]
I'm also have the same problem, (VSCode 1.8.1, MacOS Sierra 10.12.2, MBP 13 (early 2015))

**Comment by ihappycoder** [comment]
@DethAriel @aliokan 
I solved this problem by open VSCode as from terminal as root and then it updated for me without any problems.
`$sudo /Applications/Visual\ Studio\ Code.app/Contents/MacOS/Electron `

**Comment by joaomoreno** [comment]
#7426

**Comment by perlun** [comment]
@ihappycoder Opening as root and updating as such worked for me also, but it's more of a workaround than a proper fix I guess (1.10 will have the same problem then?).

**Comment by perlun** [comment]
I'm seeing a bunch of these in my system.log:

```
Feb  3 11:14:16 ecvaawplun5 com.apple.xpc.launchd[1] (com.microsoft.VSCode.ShipIt): Service only ran for 0 seconds. Pushing respawn out by 2 seconds.
Feb  3 11:14:18 ecvaawplun5 com.apple.xpc.launchd[1] (com.microsoft.VSCode.ShipIt[34082]): Service could not initialize: 16C67: xpcproxy + 11765 [1475][286733C4-18D9-396D-B01B-A096BE5B1DC1]: 0xd
Feb  3 11:14:18 ecvaawplun5 com.apple.xpc.launchd[1] (com.microsoft.VSCode.ShipIt): Service only ran for 0 seconds. Pushing respawn out by 2 seconds.
Feb  3 11:14:20 ecvaawplun5 com.apple.xpc.launchd[1] (com.microsoft.VSCode.ShipIt[34086]): Service could not initialize: 16C67: xpcproxy + 11765 [1475][286733C4-18D9-396D-B01B-A096BE5B1DC1]: 0xd
Feb  3 11:14:20 ecvaawplun5 com.apple.xpc.launchd[1] (com.microsoft.VSCode.ShipIt): Service only ran for 0 seconds. Pushing respawn out by 2 seconds.
Feb  3 11:14:21 ecvaawplun5 com.apple.xpc.launchd[1] (com.apple.nowplayingtouchui): Service only ran for 0 seconds. Pushing respawn out by 10 seconds.
Feb  3 11:14:23 ecvaawplun5 com.apple.xpc.launchd[1] (com.microsoft.VSCode.ShipIt[34088]): Service could not initialize: 16C67: xpcproxy + 11765 [1475][286733C4-18D9-396D-B01B-A096BE5B1DC1]: 0xd
```

**Comment by perlun** [comment]
(Ah, that seems to be solvable by rebooting according to https://github.com/Microsoft/vscode/issues/10718)

**Comment by perlun** [comment]
Hmm, I'm back at the `Service only ran for 0 seconds` phase now, trying to update and reboot didn't even help. 😭

**Comment by joaomoreno** [comment]
1. Never open it as root.
2. Clean up everything, since now you have files and folders owned by root. This means the app bundle and the `Application Support` vscode folder.
3. Reinstall VS Code.
4. Read [this comment](https://github.com/Microsoft/vscode/issues/7426#issuecomment-277737150).
