### ISSUE TITLE
Missing git changed file count after using top activity bar

### ISSUE THREAD

**Issue by recallwei** [microsoft/vscode#197384]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.84.0
- OS Version: macOS 14.0

Steps to Reproduce:

After upgrading to 1.84.0, the Git change count is missing.
I don’t know if it’s caused by using the top activity bar.
Only these config properties I changed to enable the top activity bar:
```json
{
  "workbench.activityBar.location": "top",
  "window.titleBarStyle": "custom",
  "window.nativeFullScreen": true,
  "window.nativeTabs": true
}
```
But even when I recovered my old settings, it still did not work.

Now:

I make a change but git does not show me the count, When I'm working on multiple projects in my workspace, it's hard for me to distinguish which ones I've made changes to.

<img width="487" alt="image" src="https://github.com/microsoft/vscode/assets/62941121/30d84077-1a84-41b5-896a-66aed5684923">

---

Another machine still has not upgraded to 1.84.0:

<img width="363" alt="image" src="https://github.com/microsoft/vscode/assets/62941121/d6e55ab9-a45d-47b6-a735-09317f0af2c6">

**Comment by gjsjohnmurray** [comment]
What is your `scm.providerCountBadge` setting?

**Comment by recallwei** [comment]
> What is your `scm.providerCountBadge` setting

@gjsjohnmurray 

I have not modified this value, so this item does not appear in mt user `settings.json`.
Then I added this to my `settings.json`,
`auto` is not working when I have multiple projects in the workspace:

<img width="865" alt="image" src="https://github.com/microsoft/vscode/assets/62941121/63bc3e00-f306-40db-980c-8698e7abd505">

---

After changing to `visible`, it took effect.

<img width="758" alt="image" src="https://github.com/microsoft/vscode/assets/62941121/965d3fff-b04a-4c9a-818a-2ced0474098d">

**Comment by recallwei** [comment]
At the same time, I found another problem. Does this attribute conflict with the top activity bar? After I set it, I can no longer make my activity bar appear at the top.

Is this issue related to #197190?

<img width="1062" alt="image" src="https://github.com/microsoft/vscode/assets/62941121/d3626087-1cb6-449c-9708-9f6438ada1fe">

My user settings: [settings.json](https://github.com/microsoft/vscode/files/13255467/settings.json)


​

**Comment by gjsjohnmurray** [comment]
A 1.84 change intentionally suppresses 0 badges on this view when that setting value is `auto`.

I think your `nativeTabs` setting needs to be false if you want a top activity bar.

**Comment by recallwei** [comment]
After changing `window.nativeTabs` to false:
Default behaviour:
<img width="888" alt="image" src="https://github.com/microsoft/vscode/assets/62941121/8014eda7-5ecf-4bc8-aea0-9d76ac292f35">

Then add `"scm.providerCountBadge": "auto"`, that is what I expected.

<img width="916" alt="image" src="https://github.com/microsoft/vscode/assets/62941121/d2f638b6-169c-4cd3-a97f-8281d712f9dd">

**Comment by gjsjohnmurray** [comment]
Looks correct.

**Comment by recallwei** [comment]
Everything seems to work fine for me.
