### ISSUE TITLE
Provide a way to theme diff highlights

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#19735]
Right now themes cannot determine the colors of the git diff highlight colors meaning that if you want the theme to be readable you *must* select foreground colors that have sufficient contrast on both the green and the red colors.

This image has uses a comment foreground that looks great on the background but is completely unreadable on the light green diff highlight:

![image](https://cloud.githubusercontent.com/assets/2193314/22565594/930ed6e6-e93d-11e6-8120-d82d5ab57b74.png)

Ideally themes would be able to define this color since the color appears within the editor.

**Comment by rotemdan** [comment]
I was just about to suggest this ;)

Also, it would be nice to be able to customize the colors of the small vertical marks that appear for changes in the code (I'm not sure how they are called). It would be nice to be able to aesthetically match them with the theme colors :), and make sure they have sufficient contrast for darker themes, I guess.

![clipboard01](https://cloud.githubusercontent.com/assets/8589488/22621089/14c909ee-eb24-11e6-812b-fe290fb2e3db.png)

**Comment by akamud** [comment]
+1, people are asking for this for my theme

**Comment by tinacious** [comment]
+1 – I would also love to support this in my theme! 😄 

Highlighted line additions are completely unreadable with my theme's comment colour (a lighter grey on a dark grey). It would be great to be able to change the diff colours (at least the foreground).

![image](https://cloud.githubusercontent.com/assets/1856992/23690034/a123971c-038c-11e7-8382-8434cd8c79e1.png)

**Comment by akamud** [comment]
I see this is closed, but can you provide more info about what theme creators need to do to provide coloring for diff?

**Comment by Tyriar** [comment]
@akamud the public API is still being worked on so we don't have documentation for it yet.
