### ISSUE TITLE
Top Activity bar reverts to side after its visibility is toggled off and back on in the `Customize Layout...` control

### ISSUE THREAD

**Issue by gjsjohnmurray** [microsoft/vscode#197322]
Type: <b>Bug</b>

1. Set `"workbench.activityBar.location": "top"`
2. Run command `Customize Layout...`
3. Click the eye icon at the end of the Activity Bar row to hide it from the top of the Primary Side Bar
4. Click that eye icon again

:bug: the Activity Bar reappears at the side instead of at the top.

Suggested solution is to replace the toggle behaviour in Customize Layout with a set of 3 mutually-exclusive checkable options, similar to how the Panel Alignment section of that layout control works.

VS Code version: Code 1.84.0 (d037ac076cee195194f93ce6fe2bdfe2969cc82d, 2023-11-01T11:29:04.398Z)
OS version: Windows_NT x64 10.0.22621
Modes:

**Comment by joaomoreno** [comment]
This is fixed.
