### ISSUE TITLE
Markdown headers don't render

### ISSUE THREAD

**Issue by Ghik90** [microsoft/vscode#197369]
Type: <b>Bug</b>

Hello,

This issue is temperamental and involves headers not being rendered larger than regular text in a markdown document when hashtags are used to define them (with a space in between the hashtag and text). Furthermore, the hashtags that define the header are themselves rendered.

This doesn't always happen (sometimes the headers are rendered as normal), but the vast majority of times the headers are not rendered. The headers are being recognised (the text turns blue) but they are not displaying properly. This issue persists after restarting VS Code, reinstalling VS Code and disabling all extensions.

Screenshots illustrating the bug:

<img width="226" alt="Screenshot 2023-11-03 at 13 39 10" src="https://github.com/microsoft/vscode/assets/149801566/99b41c95-14f7-4648-b5e2-048d9a990053">

<img width="234" alt="Screenshot 2023-11-03 at 13 39 04" src="https://github.com/microsoft/vscode/assets/149801566/73226bd4-95b6-467c-9045-c21e3da39890">

VS Code version: Code 1.84.0 (Universal) (d037ac076cee195194f93ce6fe2bdfe2969cc82d, 2023-11-01T11:30:19.406Z)
OS version: Darwin arm64 22.4.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|8.00GB (0.06GB free)|
|Process Argv|--crash-reporter-id 6672976a-ac16-4e73-aaf4-12181690a40f|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2023.20.0
vscode-pylance|ms-|2023.11.10
jupyter|ms-|2023.10.1003070148
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.17
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-slideshow|ms-|0.1.5

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
py29gd2263:30880072
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
2e4cg342:30602488
89544117:30613380
a9j8j154:30646983
showlangstatbar:30737416
03d35959:30757346
pythonfmttext:30731395
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
pythonnosmt12:30797651
pythonidxpt:30866567
pythonnoceb:30805159
synctok:30869157
dsvsc013:30795093
dsvsc014:30804076
dsvsc015:30845448
pythontestfixtcf:30871695
pythonregdiag2:30871582
pythonmypyd1:30879173
pythoncet00cf:30874137
pythontbext0:30879054

```

</details>

**Comment by mjbvz** [comment]
Can you please share some markdown text which causes this issue. I'm not able to reproduce it right now

**Comment by Ghik90** [comment]
Thank you for your reply.

Some markdown text that caused the bug is the following:

# Header
## Header
## Subheader

(a .md file with this text is attached)
[testcode.md](https://github.com/microsoft/vscode/files/13325766/testcode.md)


Aside: I have discovered that rendering the #'s (by writing just # on the line) and then going back in to add text reliably produces headings. This is an annoying workaround though and does not address the underlying issue.

**Comment by mjbvz** [comment]
Thanks. This is because there's a non breaking space between the `#` and the header text

This is the [expected behavior for commonmark](https://spec.commonmark.org/dingus/?text=%23%C2%A0Header%0A%23%23%20Header%0A%23%23%C2%A0Subheader)

Replacing it with a real space will fix the issue

**Comment by Ghik90** [comment]
Thanks very much for your help mjbvz.
