### ISSUE TITLE
Interface Overview can be wrong after reordering Viewlets 

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode#19736]
- VSCode Version: Code 1.9.0 (27240e71ef390bf2d66307e677c2a333cebf75af, 2017-02-02T08:23:30.856Z)
- OS Version: Darwin x64 15.6.0
- Extensions:

|Extension|Author|Version|
|---|---|---|
|vscode-eslint|dbaeumer|1.2.2|
|tslint|eg2|0.8.1|
|debugger-for-chrome|msjsdiag|2.5.1|
|vetur|octref|0.3.0|
|language-stylus|sysoev|1.6.0|
|vim|vscodevim|0.5.2|

---

![image](https://cloud.githubusercontent.com/assets/4033249/22565807/8282ab44-e957-11e6-8e01-877f55dce1a4.png)

**Comment by chrmarti** [comment]
Tracked with #18861
