### ISSUE TITLE
Insiders: Context menu (right click), Manage, and Accounts don't show up after mid-day update

### ISSUE THREAD

**Issue by IllusionMH** [microsoft/vscode#197370]
Type: <b>Bug</b>

After second update today it's no longer possible to get context meny in editor, Explorer and everywhere else in app.
Also it's not possible to open Manage and Accounts from activity bar, or click on ... for views.
<kbd>Shift</kbd>+<kbd>F10</kbd> does nothing as well.

Looks like from menus only main menu works as expected.

I don't see any errors in DevTools console

VS Code version: Code - Insiders 1.85.0-insider (1ef160d5bc6aab85b74e34c98d7861c7727a37ec, 2023-11-03T11:39:32.113Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz (8 x 2995)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.50GB (13.49GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by IllusionMH** [comment]
Probably duplicate or related to #197252
@sandy081 is it possible to have another build today, because it's really hard to use VS Code without all context menus?

**Comment by connor4312** [comment]
A new Insiders is en-route

**Comment by IllusionMH** [comment]
Update is available and it works as expected with it!
Thanks!
