### ISSUE TITLE
"Suggest: Preview" not work

### ISSUE THREAD

**Issue by Zhoucheng133** [microsoft/vscode#197357]
- VS Code Version: 1.84.0
- OS Version: macOS 14.1

Steps to Reproduce:

1. Enable the setting: Suggest: Preview
2. The preview not shown when I not type the keywords from head

For example: 
I type the "cons" in js file, it can preview "console"
BUT when I type the "log" in js file, it doesn't show any preview, although I can press enter to complete typing "console.log"
Here's the screenshot: 👀
![截屏2023-11-03 19 55 03](https://github.com/microsoft/vscode/assets/54197427/f75205c8-abe9-4b9e-b09f-c68edc50f3b2)
![截屏2023-11-03 19 51 01](https://github.com/microsoft/vscode/assets/54197427/3dd7877c-563e-4457-9f6e-eac07ac4d15b)

I think it's a bug because former version can preview it.

I tried the Insider version and it still have this problem.

**Comment by hediet** [comment]
/duplicate This is by design: It is very difficult to show a preview that is not an extension of what you currently typed (`console.log` is not an extension of `log`).
