### ISSUE TITLE
Editor Part Options: Only Validate Changed Settings

### ISSUE THREAD

**Issue by benibenj** [microsoft/vscode#197323]
We validate all settings every time a setting has changed in the editor part. Only changed settings require validation.

// cc @bpasero

**Comment by bpasero** [comment]
@benibenj I would actually go one step further: only validate settings that the user has configured. All others will already be configured as default.

I think https://github.com/microsoft/vscode/issues/125422 is the real fix here to have this done within config service.

**Comment by benibenj** [comment]
Yes, I totally agree
