### ISSUE TITLE
TypeScript language service died unexpectedly 5 times in the last 5 Minutes

### ISSUE THREAD

**Issue by JBeans99** [Microsoft/vscode#19737]
- VSCode Version: Code 1.9.0 (27240e71ef390bf2d66307e677c2a333cebf75af, 2017-02-02T08:31:00.827Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions:

|Extension|Author|Version|
|---|---|---|
|jshint|dbaeumer|0.10.15|
|vscode-eslint|dbaeumer|1.2.2|
|vscode-npm-script|eg2|0.1.8|
|vscode-npm|fknop|3.3.0|
|beautify|HookyQR|0.7.3|
|sp-tools|Mike|0.3.0|

---

Steps to Reproduce:

1. working in SharePoint WebDav folder -> ` \\Local-SP-Server.com@SSL\DavWWWRoot\SubSite\SiteAssets `

2. When I first open VS Code then open a .js file I receive continuous errors that the Typescript Service has failed (*The TypeScript language service died unexpectedly 5 times in the last 5 Minutes.
RetryClose*). The error pops up continuously until I close the file or VS Code. 

3. Errors will stop after closing the .js file and re-opening it. Once I re-open the .js file i will get the error again, but this time the error message stays at the top of the screen and i can hit escape to clear the error.

4. This also happened in the version of VS Code previous to v1.9.0

   **Sidenote:** 
   I uninstalled the *sp-tools* extension and i'm still having the same issue. Also, I was getting this error before i installed all other extensions listed above.

**Comment by mjbvz** [comment]
Thank you for the detailed report. I've opened https://github.com/Microsoft/TypeScript/issues/13874 against TypeScript to track this.
