### ISSUE TITLE
State `SaveStrategy.IMMEDIATE` is risky

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#197372]
I noticed how we seem to be having a `SaveStrategy.IMMEDIATE` that is only used in `ServerUserDataProfilesService`:

https://github.com/microsoft/vscode/blob/d27b275d84163830b07392eef60b06c3f19cc59b/src/vs/platform/userDataProfile/node/userDataProfile.ts#L115

In that case we seem to not be using a `ThrottledDelayer` for writing. But that will have pretty bad consequences because it can leave `writeFile` calls hanging even after `close`. The unit test failure here actually shows it:

https://dev.azure.com/monacotools/a6d41577-0fa3-498e-af22-257312ff0545/_build/results?buildId=241378

I think this might have been introduced via https://github.dev/microsoft/vscode/pull/152994

**Comment by sandy081** [comment]
This strategy was introduced by https://github.com/microsoft/vscode/pull/174232.

I do not remember why we need immediate in server. 

I saw your change and I hope `0ms` flush delayer for immediate should work.

**Comment by bpasero** [comment]
I think the importance here is to always use the delayer, even when its with a delay of `0ms`, because it was not only used to delay the saves, but also to aggregate them 👍
