### ISSUE TITLE
Allow hiding Accounts icon when Activity Bar Position is Top

### ISSUE THREAD

**Issue by dacapoday** [microsoft/vscode#197306]
You can hide any other content in the title bar
![cc1](https://github.com/microsoft/vscode/assets/9378047/e5d32d10-917e-4697-b6bc-a7a248d180c3)

You can hide Accounts icon when Activity Bar Position Side
![cc2](https://github.com/microsoft/vscode/assets/9378047/d46147c0-e5b7-4ce9-a0a0-6d766ca67d84)

But you can't hide Accounts icon in the title bar when Activity Bar Position Top
![cc3](https://github.com/microsoft/vscode/assets/9378047/01075eb6-110d-4afc-8716-3bd9de20cd94)

Recap: https://github.com/microsoft/vscode/issues/118692#issuecomment-1790357664

Version: 1.84.0
Commit: d037ac076cee195194f93ce6fe2bdfe2969cc82d
Date: 2023-11-01T11:29:04.398Z (1 day ago)
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Code/1.84.0 Chrome/114.0.5735.289 Electron/25.9.2 Safari/537.36

**Comment by noisnemid** [comment]
1.86.2, still not fixed.

**Comment by gjsjohnmurray** [comment]
@noisnemid when/if this gets implemented the issue will be updated and closed.

**Comment by benibenj** [comment]
Added support for hiding accounts action in the title bar when right clicking on it.
