### ISSUE TITLE
Add mouseover background and foreground colors to buttons

### ISSUE THREAD

**Issue by zhouxinghong** [microsoft/vscode#197345]
### This UI design layout is great! 👍👍
![image](https://github.com/microsoft/vscode/assets/54253524/6dd8641e-cec7-485f-a9c6-2f411f10316c)

**If you can add a mouse-over background color and foreground color to the button, the entire UI display effect will be even more wonderful!**
Windows 10

**Comment by gjsjohnmurray** [comment]
Good point. When in the side position an unselected Activity Bar icon's foreground colour changes upon hover. That also happens on the Secondary Side Bar tab icons, and on the Panel tab labels.

/assign @sandy081

**Comment by AndreasBackx** [comment]
I asked this question last week at https://github.com/microsoft/vscode-discussions/discussions/912. I assume that this means it's not supported yet, or rather undocumented?

**Comment by zephyrtronium** [comment]
Per #202032, I'd like the ability to theme the entire activity bar when it's in top position, particularly to assign background and foreground colors independently of the sidebar (and also independently of the activity bar in side position).

Personally, I'd prefer to be able to style it according to the same behavior that the side-position activity bar has: the bar has its own background color, the active item has a different background color, and active and inactive icons have independent foreground colors. In particular, I'd want equivalents to at least the following theme colors:

- `activityBar.background`
- `activityBar.activeBackground`
- `activityBar.foreground`
- `activityBar.inactiveForeground`

Probably the rest of the activity bar colors should have top-position equivalents as well, but I happen not to use them.

My reading of OP is that @zhouxinghong wants the top activity bar to be styled more like a list of buttons with the side bar's background color, similar to how input options work. I'm not sure whether those are mutually exclusive requirements, but if it's possible to make both available, it should be the theme that makes the decision of which to use, not a user setting.

**Comment by zhouxinghong** [comment]
I can't understand your needs, but adding mouseover background color and foreground color to the icon button is the most basic need.

**Comment by sandy081** [comment]
Added following colors

```
"workbench.colorCustomizations": {
    "activityBarTop.foreground": "#0b1691",
    "activityBarTop.activeBorder": "#ff0000",
    "activityBarTop.inactiveForeground": "#ff0000",
  },
```

to customise acitivity bar item when it is on top like below

<img width="338" alt="image" src="https://github.com/microsoft/vscode/assets/10746682/205c1853-99ab-4ef9-b68f-a882f2547361">

**Comment by zhouxinghong** [comment]
Previous versions of the following foreground colors already existed
```
"workbench.colorCustomizations": {
     "activityBarTop.foreground": "#0b1691",
     "activityBarTop.activeBorder": "#ff0000",
     "activityBarTop.inactiveForeground": "#ff0000",
   },
```

**Comment by zhouxinghong** [comment]
Even if the properties are set to different names, the same effect can be achieved. Why reinvent the wheel?

**Comment by zhouxinghong** [comment]
The above approach cannot achieve the following requirements: https://github.com/microsoft/vscode/issues/197345

**Comment by zhouxinghong** [comment]
@gjsjohnmurray `Good point. When in the side position an unselected Activity Bar icon's foreground colour changes upon hover. That also happens on the Secondary Side Bar tab icons, and on the Panel tab labels.`

**Comment by zephyrtronium** [comment]
> Added following colors
> 
> ```
> "workbench.colorCustomizations": {
>     "activityBarTop.foreground": "#0b1691",
>     "activityBarTop.activeBorder": "#ff0000",
>     "activityBarTop.inactiveForeground": "#ff0000",
>   },
> ```

This list of colors (nor `activityBarTop.dropBorder` also added in c005fc3) doesn't seem to allow coloring the *background* of the activity bar independent of the sidebar. I want to emphasize the activity bar as a separate control, similar to sidebar section headers. I also agree that it doesn't solve @zhouxinghong's request for a hover background color. @sandy081, should we open separate issues as feature requests now that this one is closed?

**Comment by zhouxinghong** [comment]
@gjsjohnmurray @sandy081 @zephyrtronium The following foreground colors have existed in previous versions, in vscode 1.40 and earlier.

"workbench.colorCustomizations": {
     "activityBarTop.foreground": "#0b1691",
     "activityBarTop.activeBorder": "#ff0000",
     "activityBarTop.inactiveForeground": "#ff0000",
   },

**Comment by sandy081** [comment]
@zephyrtronium mouseover foreground color is supported by `activityBarTop.foreground` - This is same in all places 

- activity bar on top
- secondary side bar
- panel

mouseover background and mouseover border color is not supported in any of the above places. Hence they are not supported.

**Comment by zephyrtronium** [comment]
> mouseover background and mouseover border color is not supported in any of the above places. Hence they are not supported.

Hence why we are asking for them. As well as non-mouseover background colors for the activity bar on the top, like it has when it is on the side.

**Comment by sandy081** [comment]
Please file a separate issue for the other colours which you would like to want.

**Comment by zhouxinghong** [comment]
@sandy081 What I want to say is that your work ability is so poor that you can't solve even a single problem. . .

**Comment by zephyrtronium** [comment]
> Please file a separate issue for the other colours which you would like to want.

I created #203036 for the colors I'd like. Thanks for your patience, @sandy081.

@zhouxinghong Please don't be disrespectful. Comments like that will get no one anything they want. This community has a code of conduct available at https://opensource.microsoft.com/codeofconduct/. I suggest you read, understand, and follow it, particularly the portions regarding acceptable and unacceptable behavior. Derogatory personal attacks are in the latter category.

**Comment by zhouxinghong** [comment]
> > Please file a separate issue for the other colours which you would like to want.
> 
> I created #203036 for the colors I'd like. Thanks for your patience, @sandy081.
> 
> @zhouxinghong Please don't be disrespectful. Comments like that will get no one anything they want. This community has a code of conduct available at https://opensource.microsoft.com/codeofconduct/. I suggest you read, understand, and follow it, particularly the portions regarding acceptable and unacceptable behavior. Derogatory personal attacks are in the latter category.

**Comment by zhouxinghong** [comment]
I plan to give up vscode from now on because I have submitted too many reasonable improvement plans to vscode in the past few years, but no one has effectively solved them. I found a better vscode replacement solution Fleet IDE

**Comment by dbaeumer** [comment]
Verified that "activityBarTop.foreground" works
