### ISSUE TITLE
vscode 1.9 breaks my syntax theme.

### ISSUE THREAD

**Issue by pmkary** [Microsoft/vscode#19734]
- VSCode Version: 1.9
- OS Version: macOS Sierra

I had a [theme](https://marketplace.visualstudio.com/items?itemName=karyfoundation.theme-karyfoundation-themes) which used to be fully colored and it now looks like this:

<img width="493" alt="screen shot 2017-02-02 at 11 06 07 pm" src="https://cloud.githubusercontent.com/assets/2157285/22565110/3888ed7e-e99c-11e6-83a5-ca287ebd2e90.png">

What I did with my theme was I defined [specific token values](https://github.com/karyfoundation/karyfoundation.themeX/blob/master/karyfoundation.themeX/theme.yml) by opening up the developer tools and going through the tokenizer classes. What I see right now is this problem within my themes are caused by the new way you handle these tokens:

<img width="259" alt="screen shot 2017-02-02 at 11 09 17 pm" src="https://cloud.githubusercontent.com/assets/2157285/22565284/d85edfa2-e99c-11e6-8f28-a46bef22eb1d.png">

So what should I do right now? I should dump down my theme right? Remove all the language specific tokens and stick with the basic tmLanguage stuff?

**Comment by triceam** [comment]
I'm seeing the exact same thing.   Looking now to see what our options are...

**Comment by triceam** [comment]
OK, I looked into mine.  I was able to fix it by using conventions here: http://manual.macromates.com/en/language_grammars#naming_conventions

Where before I was using names of CSS classes used inside of VS Code, like "info-token".  So I replaced "info-token" with "string.quoted" etc... to match all of the supported classes in the grammar.

**Comment by Tyriar** [comment]
Yes previously you needed to inspect the CSS classes via devtools, this followed CSS' specificity rules which didn't match how textmate/sublime actually act though. Now you can run "Inspect TM Scopes" via the command palette to see the scopes and their priority:

![image](https://cloud.githubusercontent.com/assets/2193314/22566720/ef90558a-e941-11e6-9e82-87eb8a15b397.png)

Unfortunately this will break some themes but we're moving from what was a broken system to a correct one.

**Comment by Tyriar** [comment]
Read more in the release notes https://code.visualstudio.com/updates/v1_9#_new-tools-for-inspecting-textmate-scopes

**Comment by triceam** [comment]
Thanks! Took 5 mins to fix & already pushed a fix: https://marketplace.visualstudio.com/items?itemName=IBM.output-colorizer

**Comment by Tyriar** [comment]
@triceam :zap:

**Comment by pmkary** [comment]
@Tyriar that wasn't broken actually, to me that was a super-power, I had so many rules defined and I was really happy with it. I had 127 rules defined and it was perfect. However I agree that the new system is much faster to render. But still that was a super power

**Comment by Tyriar** [comment]
@pmkary I found after building my own theme over the last week that the theme building experience is *so much better* and you're also able to do a whole lot more and get more specific. It's just a shame that themes built for the old system could break as a result.

**Comment by pmkary** [comment]
@Tyriar I hope it be so. Please let this issue be open so that I can investigate the abilities and tell you if old themes can be imported to the new system.

**Comment by pmkary** [comment]
Dear @Tyriar. Thanks a lot for your explanations. I just [published a new version of my theme](https://marketplace.visualstudio.com/items?itemName=karyfoundation.theme-karyfoundation-themes) with all of the problems solved.

<img width="705" alt="screen shot 2017-02-03 at 4 29 12 am" src="https://cloud.githubusercontent.com/assets/2157285/22575212/5b3259aa-e9c9-11e6-9502-8acd2ecbbc20.png">

The problem was that my rules no longer existed there. Many of the definitions were the same but the names did change. So I think it's not about the new syntax highlighter but some new definitions.

From now on I will check the theme every 2 days to the release. But you can have a notice being published? Atom has this change in definitions in like 2 months from now and they have already opened up an issue in my repo warning me. I think having something like this in your blog or twitter would be great.

**Comment by Tyriar** [comment]
@pmkary I doubt a change this dramatic will happen again any time soon, but yeah we probably should have done a better job informing people. Glad the problems are fixed :smiley:

**Comment by alexandrudima** [comment]
Sorry for the breakage and thanks for working through it! :heart:

We have a blog post draft explaining what changed in depth (will be published soon) -- https://github.com/Microsoft/vscode-docs/blob/vnext/blogs/2017/02/15/textmate-sematics.md

**Comment by pmkary** [comment]
@alexandrudima, @Tyriar  thanks a lot! You guys really are the coolest dev team I've ever witnessed. The fact that you can release every once in a month with this level of stability and with this crazy load of issues you manage to always be this kind and answer with this depth makes me respect you in a way I've never had about any other team. So thanks a lot for all you've done and all this very kind answers you always have when I get in touch. So please don't say sorry! I'm really sorry if in anyways caused you to say that.

Also @Tyriar the feature you introduced for `Inspecting TM Scopes` is the coolest thing ever. I had one written for myself. now I have a much better one thanks to you guys! 👍 

@alexandrudima I'm still waiting for one more talk from you! :D

**Comment by Tyriar** [comment]
@pmkary this was all @alexandrudima's work, I'm just a fan too :wink:

**Comment by pmkary** [comment]
@Tyriar @alexandrudima :D
