### ISSUE TITLE
[Accessibility] Add a setting to display git branch info in title bar

### ISSUE THREAD

**Issue by jooyoungseo** [microsoft/vscode#197498]
Type: <b>Feature Request</b>

CC @meganrogge 

This feature request was already proposed in the past via #20016, but locked without a solution.

Identifying currently working branch is essential for any users, but it is even more time-consuiming for screen reader users b/c the current status bar implementation requires the multiple keyboard navigation (e.g., pressing F6/Shift+F6 to focus in status bar and moving left/right arrows to manually focus in the git branch tag button).

Since every screen reader provides a keybinding reading an active title bar, having it there will provide users with a more instant access.

VS Code version: Code - Insiders 1.85.0-insider (e55009850900a64eeb37b2228c79855ceff63914, 2023-11-03T15:11:12.179Z)
OS version: Windows_NT x64 10.0.22621
Modes:

**Comment by meganrogge** [comment]
@joaomoreno this seems like a fair request with a decent amount of attention and the possibility for a lot of impact (accessibility wise). Could we please consider it?

**Comment by lszomoru** [comment]
Starting with today's VS Code Insiders release, there are two new window title variables: `${activeRepositoryName}` and `${activeRepositoryBranchName}`. Please give them a try and let me know if you see any issues. Thank you!

@bpasero, thanks for your help with implementing this!
