### ISSUE TITLE
command 'extension.togglecodeinline' not found when attempting to toggle integrated terminal with ctrl + `

### ISSUE THREAD

**Issue by mdarens** [Microsoft/vscode#19742]
- VSCode Version: Code 1.9.0 (27240e71ef390bf2d66307e677c2a333cebf75af, 2017-02-02T08:31:00.827Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

|Extension|Author|Version|
|---|---|---|
|rainbow-brackets|2gua|0.0.6|
|Handlebars|andrejunges|0.2.0|
|npm-intellisense|christian-kohler|1.2.1|
|path-intellisense|christian-kohler|1.2.0|
|vscode-eslint|dbaeumer|1.2.2|
|vscode-npm-source|dkundel|1.0.0|
|LogFileHighlighter|emilast|1.0.1|
|flow-for-vscode|flowtype|0.4.0|
|auto-close-tag|formulahendry|0.3.9|
|auto-rename-tag|formulahendry|0.0.11|
|rest-client|humao|0.9.0|
|mdhelper|joshbax|0.0.9|
|csharp|ms-vscode|1.6.2|
|debugger-for-chrome|msjsdiag|2.5.1|
|indent-rainbow|oderwat|0.4.1|
|vscode-subword-navigation|ow|1.1.5|
|vscode-icons|robertohuertasm|7.1.2|
|vscode-flow|rtorr|276.3.0|
|Spell|seanmcbreen|0.9.1|
|vscode-open-in-github|sysoev|1.3.1|
|jsx|TwentyChung|0.0.1|
|ReactSnippets|xabikos|1.2.0|

---

User Settings:

```json
// Place your settings in this file to overwrite the default settings
{
    "editor.fontFamily": "'Fira Code', Consolas, 'Courier New', monospace",
    "editor.fontSize": 14,
    "editor.fontLigatures": true,
	"editor.renderWhitespace": "boundary",
	"editor.trimAutoWhitespace": true,
	"eslint.autoFixOnSave": true,
	"eslint.validate": [
		"javascript",
		"javascriptreact"
	],
	"npm-intellisense.importQuotes": "\"",
	"npm-intellisense.packageSubfoldersIntellisense": true,
	"files.associations": {"*.example":"jsx","*.html":"handlebars"}
,
"window.zoomLevel": 0,
"vsicons.projectDetection.autoReload": true,
"terminal.integrated.shell.windows": "C:\\Program Files\\Git\\bin\\bash.exe"
}
```
Steps to Reproduce:

1. Attempt to open the integrated terminal with `ctrl` + `` ` ``
2. Observe that it doesn't open, but you do get a warning toaster:
> command 'extension.togglecodeinline' not found

(using `ctrl` + `` ` `` to toggle the terminal _off_ once opened via the palette menu works as expected)

**Comment by Tyriar** [comment]
You have an extension that has registered the command `extension.togglecodeinline` with a default keybinding that overrides the terminal's keybinding. Bless GitHub's global search because it's easy to find the culprit (mdhelper) :wink: https://github.com/search?q=togglecodeinline&type=Code&utf8=%E2%9C%93

You can work around this for now by removing the keybinding by adding this to your keybindings.json file:

```js
{ "command": "extension.togglecodeinline", "key": "ctrl+`", "when": "editorTextFocus" },
```

I filed an issue against the extension to see if they can change the keybinding https://github.com/joshbax-msft/mdhelper/issues/1
