### ISSUE TITLE
VS Code is stuck with infinite loading on Safari v16 and lower

### ISSUE THREAD

**Issue by raphaeldn28** [microsoft/vscode#197473]
ADD ISSUE DESCRIPTION HERE

It does not matter which file I load or opem, it is stuck with infinite loading 

Version: 1.84.0
Commit: d037ac076cee195194f93ce6fe2bdfe2969cc82d
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36
Embedder: codespaces

**Comment by Raubzeug** [comment]
I have the same issue. I've done some investigations and found out the problem is here https://github.com/microsoft/vscode/blob/7425fbc5f30456a4d1c17698a60274f6d48b6baf/src/vs/base/common/tfIdf.ts#L92 . It doest works with Safari < v17 because of error `invalid group specifier name`.

**Comment by rzhao271** [comment]
I do have an older macOS VM, but it doesn't seem to be booting right now. My current macOS device is on Safari 17.

@raphaeldn28 @Raubzeug is the issue fixed for either of you?

One way to test is to launch https://insiders.vscode.dev, and then to search just "a" in the Settings editor while having GitHub Copilot Chat disabled or not installed. If the Settings editor is able to finish the search, then the fix worked.

**Comment by Raubzeug** [comment]
@rzhao271 Hi! I've just checked with Safari 15 and 16 and https://insiders.vscode.dev doest'n work. The problem is here now:

<img width="982" alt="Screenshot 2023-11-30 at 10 08 03" src="https://github.com/microsoft/vscode/assets/42094364/bccdf2e7-0798-4c30-b901-311f97073b07">

By the way, it works properly with Safari 17.

**Comment by rzhao271** [comment]
I finally confirmed the unexpected token issue with a VM, but I'm unsure which part of the code it comes from.
