### ISSUE TITLE
Unable to hide the new buttons on the title bar

### ISSUE THREAD

**Issue by HolyBlackCat** [microsoft/vscode#197454]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.84.0
- OS Version: Manjaro Linux

Steps to Reproduce:

1. Open VSC, enable the custom title bar if not already enabled.
2. Observe those buttons:
![pic](https://github.com/microsoft/vscode/assets/20289055/468b651d-2f82-4506-a259-b631f7eec94c)

There seems to be no way to hide them, neither using `settings.json` nor by right-clicking them.

Given that everything else on the title bar can be hidden (the menu, the command center, the layout controls), I believe those buttons must be hiddable as well.

**Comment by benibenj** [comment]
You can hide account, but we wont be allowing to hide settings for the time being

**Comment by usernamehw** [comment]
Workaround is to use [Custom CSS](https://marketplace.visualstudio.com/items?itemName=be5invis.vscode-custom-css)

```css
.titlebar-container .titlebar-right .monaco-action-bar {
	opacity: 0 !important;
}
```
