### ISSUE TITLE
Scrollbar for inline chat is off the screen which makes it confusing

### ISSUE THREAD

**Issue by TylerLeonhardt** [microsoft/vscode#197416]
Gif upload isn't working so sadly have to upload a zip...

[Recording 2023-11-03 at 15.25.21.gif.zip](https://github.com/microsoft/vscode/files/13255117/Recording.2023-11-03.at.15.25.21.gif.zip)

Anyway steps are:
* Get Copilot to output something big like another test
* be confused that the visible scrollbar doesn't apply to the diff but rather the editor

This is a UI bug so I don't think you need the logs but lmk if you do.

**Comment by ulugbekna** [comment]
cc @alexdima again so that it doesn't go unnoticed

**Comment by jrieken** [comment]
Closing because the new `live3` mode will take care of this because we won't show editors inside editors anymore.
