### ISSUE TITLE
In a future release, would it be possible to expose the interaction of `comments.createCommentController` to create a `comment`, adding more parameters to make it more customizable?

### ISSUE THREAD

**Issue by czfadmin** [microsoft/vscode#197484]
Type: <b>Feature Request</b>

Hello. Would it be possible to consider fully liberalizing the interaction of a `comment` created by `comment.createCommentController`, instead of just creating the data and rendering it automatically in the `Comments` view? It is desirable to expose this interaction and make it more generic, so that extension developers can modify and customize the contents of the `CommentingRangeProvider` in the documentation and the gutter command bindings shown above, and to add the option to not automatically create a `Comments` panel view with the data created.

![image](https://github.com/microsoft/vscode/assets/13393959/f5898da0-101d-4492-812b-61d13954615c)

VS Code version: Code 1.84.0 (d037ac076cee195194f93ce6fe2bdfe2969cc82d, 2023-11-01T11:29:04.398Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Remote OS version: Linux x64 5.15.90.1-microsoft-standard-WSL2

**Comment by alexr00** [comment]
>  so that extension developers can modify and customize the contents of the CommentingRangeProvider in the documentation and the gutter command bindings shown above

I'm not sure I understand this, can you elaborate? 

> to add the option to not automatically create a Comments panel view with the data created.

Comments will always be added to the Comments view, but the user has control over whether it shows. Users can hide it and cause it to never show again with the setting `"comments.openView": "never"`.

**Comment by czfadmin** [comment]
> 
> I'm not sure I understand this, can you elaborate?
> 

Since this is a great feature, I was wondering if it would be possible to expose the API for creating and interacting with comment creation, so that the user can customize the content of the gutter and the `start discussion` to make this feature more versatile. 

![image](https://github.com/microsoft/vscode/assets/13393959/3563de91-5a9f-429d-bed6-de52d22e07ac)


> Comments will always be added to the Comments view, but the user has control over whether it shows. Users can hide it and cause it to never show again with the setting `"comments.openView": "never"`.

Thanks for the solution, the `comments` panel can be turned off. But if there are more than one extension developer , using this api, and the `comments.openView`, is not set to `never`, will the content in this panel be messed up.

**Comment by alexr00** [comment]
> customize the content of the gutter

What would you want to put in the gutter?

>  and the `start discussion`

This makes sense to me. Would you want this to be the same for every comment from your provider? We already have `CommentOptions`, which we could add a new `threadLabel` to:
https://github.com/microsoft/vscode/blob/77bc48052be38f30a5c6fc3cb703e306c0a8baef/src/vscode-dts/vscode.d.ts#L16593-L16606

> But if there are more than one extension developer , using this api, and the comments.openView, is not set to never, will the content in this panel be messed up.

Can you elaborate further? If you have multiple extensions contributing comments then they will all show up here.

**Comment by czfadmin** [comment]
> What would you want to put in the gutter?

I want to change the icon on the gutter.

> This makes sense to me. Would you want this to be the same for every comment from your provider? We already have `CommentOptions`, which we could add a new `threadLabel` to:

Thanks for your help, I didn't notice these options.👍

> Can you elaborate further? If you have multiple extensions contributing comments then they will all show up here.
This is created by creating two different controllers and will appear in the same place. Will this make it unclear which comment was created by which controller?
As shown below
![image](https://github.com/microsoft/vscode/assets/13393959/86ded6cc-4c1e-46a3-a4f4-a70b99b84174)

**Comment by alexr00** [comment]
> This is created by creating two different controllers and will appear in the same place. Will this make it unclear which comment was created by which controller?

This does make it clear, thanks! I'll add some label in there so that it's clear which comments come from which controller.

**Comment by czfadmin** [comment]
> This does make it clear, thanks! I'll add some label in there so that it's clear which comments come from which controller.

Yes, this is what I mean. Can you please add an option that allows developers to choose whether to populate the added comment data into this panel? Because sometimes we may just want to use this interactive method to create content and Fill it into the view you created without reappearing in the default comments panel. Please consider whether you can add this function. Thank you for your work.

**Comment by alexr00** [comment]
The Comments view is intended to be the central place to view all comments. At this time we will not provide a way for extension authors to exclude comments from the Comments view.

**Comment by alexr00** [comment]
When there are multiple comment controllers we will show the controller's label in the view now:

![image](https://github.com/microsoft/vscode/assets/38270282/908f10f8-b5af-4e69-9edf-4c881e2fb3eb)

For changing the "Start Discussion" I have opened https://github.com/microsoft/vscode/issues/197939.

**Comment by czfadmin** [comment]
@alexr00 👍Really cool, thumbs up for your hard work. This is a great feature.

**Comment by TylerLeonhardt** [comment]
@alexr00 could we get some verification steps?

**Comment by alexr00** [comment]
To verify:
- Install 2 extensions that provide commenting (ex. GitHub Pull Requests and Issues and the comments sample from https://github.com/microsoft/vscode-extension-samples)
- Leave comments using both providers
- Open the comments view. Verify that you can tell which comments belong to each comments provider
