### ISSUE TITLE
SCM - add visual indication for closed repositories

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode#197466]
I've only noticed this recently, but I can reproduce it in both the latest insiders and 1.84.0 -- though the behavior between them is slightly different.

I have a workspace file that contains 6 folders, each folder is a Git repo. In 1.84.0 only 5 repos are discovered and it is always the last repo in the workspace that is missing. While in the latest insiders, only 3 repos are discovered and again it is always the same set, but oddly it isn't the first 3.

I can reproduce this 100% of the time even with all extensions disabled and FWIW GitLens doesn't have any issue discovering all the repositories.

**Comment by gjsjohnmurray** [comment]
Maybe the diagnostic steps at https://github.com/microsoft/vscode/issues/194528#issuecomment-1744971351 can help.

**Comment by eamodio** [comment]
@gjsjohnmurray Thanks! Apparently they were "closed" -- was there a change recently when "closed" state is now persisted?

**Comment by eamodio** [comment]
Some visual indication (somewhere) that there are closed repositories would be very helpful.

**Comment by xqrdot** [comment]
@eamodio have you found a workaround for the issue? I guess I have the same problem, although can't see repositories being reported as "closed".

**Comment by lszomoru** [comment]
VS Code 1.87 (February 2024 release) will include changes to show an action in the "Source Control Repositories" view title bar to reopen closed repositories. The action will only be shown if there are any closed repositories. Users can also hide the action and then it will be moved into the `...` menu.

<img width="377" alt="image" src="https://github.com/microsoft/vscode/assets/3372902/380c9005-0ab2-4a00-9696-6ef18fb3d2fa">

**Comment by hediet** [comment]
> Confirm that a new action is shown in the "Source Control Repositories" view's title bar

I don't see it

![Code_-_Insiders_RSlatz20yn](https://github.com/microsoft/vscode/assets/2931520/f86c0ad4-b958-4f51-b960-de3b07e78d13)

**Comment by gjsjohnmurray** [comment]
@hediet have you hidden your "Source Control **Repositories**" view? Context menu of the "Source Control" view's titlebar should indicate that.

**Comment by hediet** [comment]
Even there I didn't see it

**Comment by lszomoru** [comment]
@hediet, do you mind sharing a recording with the "Source Control Repositories" view? Thanks!

**Comment by hediet** [comment]
![Code_-_Insiders_mdyQXhbKnG](https://github.com/microsoft/vscode/assets/2931520/bb65551e-5407-442c-a7f8-da55048e1f95)

**Comment by lszomoru** [comment]
Thank you! Fix should be available in Thursday's VS Code Insiders release.
