### ISSUE TITLE
Aux window: Main window editor hangs or is slow on aux window minimize

### ISSUE THREAD

**Issue by alexandruavadanii** [microsoft/vscode#197420]
Type: <b>Bug</b>

This is most likely a recent regression, as I just started seeing it today:
1. Start with a main window and an aux window
2. Maximize (full screen) the main window
3. Minimize the aux window
4. (Occasionally you need to wait for a while until the slowness manifests)
5. Restoring the aux window brings everything back to normal instantly

Expected result: nothing special
Actual result: main window is either extremely laggy or just stops redrawing the editor (notice that some parts are still updated correctly, e.g. the current function name at the top - I don't know how we call that part of the workbench).

Nothing in the developer tools console.

![Recording 2023-11-04 at 01 19 38](https://github.com/microsoft/vscode/assets/11544783/50079ec8-11cd-42a5-81d7-50def3ec2a6f)

VS Code version: Code - Insiders 1.85.0-insider (e55009850900a64eeb37b2228c79855ceff63914, 2023-11-03T15:11:12.179Z)
OS version: Windows_NT x64 10.0.18362
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.81GB (1.95GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by bpasero** [comment]
Wow, this reproduces even on macOS. Great finding. 

@deepak1556 any clues? Steps:
* have multiple editors open
* move one out as floating window
* minimize that floating window
* try to open more editors in the main window
* 🐛 editors do not even open

Is this some throttling happening?

**Comment by bpasero** [comment]
Actually I think this is not a perf issue but a rendering issue. Other things like panels or views still function, it is only the editor that does not render. So maybe the editor still thinks the other window has focus?

**Comment by bpasero** [comment]
Caused by https://github.com/microsoft/vscode/commit/1a3461f764c5ff26eba9447eec49ff2db4971a0d

**Comment by alexandruavadanii** [comment]
/verified

Thank you for the extremely quick fix, @bpasero !
