### ISSUE TITLE
please add the features to give input when debugging a c++ file

### ISSUE THREAD

**Issue by Pabitra969** [microsoft/vscode#197476]

**Comment by Pabitra969** [comment]
when give a breakpoint at the input line of a and try to debug the debug session stops because the debugger is unable to take user input when the program is debugging.
so it is possible to give the program input through terminal when debugging that will solve the problem. Hope my concern is clear to everyone.

**Comment by roblourens** [comment]
Please check the docs or file this on the C++ debug extension, thanks
