### ISSUE TITLE
Find and replace capture group/backreference inserts `undefined` instead of empty string

### ISSUE THREAD

**Issue by calebmosher** [Microsoft/vscode#19740]
- VSCode Version: 1.9.0
- OS Version: OSX 10.11.6

Steps to Reproduce:

1. Execute find/replace with regex.
2. Using backreference replacements (e.g. `$1`, `$2`...), if the capture group did not capture anything, VS Code outputs `"undefined"` instead of the expected `""` (empty string).

This just started happening after upgrading to 1.9.0 today (02/02/17) and was not doing this yesterday.

**Comment by Tyriar** [comment]
@roblourens may be worth fixing for stability build?

**Comment by roblourens** [comment]
I can't repro this. Can you give a specific example?

@sandy081?

**Comment by calebmosher** [comment]
__Steps to Reproduce:__
1. Open a blank new document.
1. Type `abcd`.
1. Bring up find (⌘F or Edit->Find)
1. Click small arrow on the left of find modal to open replace module.
1. Activate regex find (⌥⌘R or click __[.*]__ icon)
1. Type `a(z)?` in first input.
1. Type `a{$1}` in second input.
1. Execute replace (⇧⌘1 or click __[c<-b]__ icon).

__Actual behavior:__
`abcd` is replaced by `a{undefined}bcd`

__Expected Behavior:__
`abcd` is replaced by `a{}bcd`

---

This is the way it works in Chrome and Node:
```js
> 'abcd'.replace(/a(z)?/, 'a{$1}')
"a{}bcd"
```
...and the way it was working in VS Code before updating to 1.9.0 earlier today.

**Comment by roblourens** [comment]
Ok, I see it. It doesn't repro with something like `a(\d*)` that I was trying.

**Comment by sandy081** [comment]
This could be due to the changes done by @alexandrudima #18111 ? Because I do not see this happening from Search view.
