### ISSUE TITLE
No local history (timeline) for Jupyter notebook

### ISSUE THREAD

**Issue by TianYuanSX** [microsoft/vscode#197496]
Type: <b>Bug</b>

It seems timeline doesn't work for Jupyter notebook (*.ipynb), either for automatic or mannual save and create entry.
The timeline only contains one entry (edit, 1 wk).
![Snipaste_2023-11-06_11-47-07](https://github.com/microsoft/vscode/assets/19888391/22d607f5-d71a-4461-ba86-3bcda5fa8605)

VS Code version: Code 1.84.0 (d037ac076cee195194f93ce6fe2bdfe2969cc82d, 2023-11-01T11:29:04.398Z)
OS version: Windows_NT x64 10.0.22621
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|12th Gen Intel(R) Core(TM) i5-1240P (16 x 2112)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|23.72GB (12.21GB free)|
|Process Argv|--crash-reporter-id 8d20b302-145d-4845-8b24-014bc8e14051|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (20)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-office|cwe|3.1.8
vscode-markdownlint|Dav|0.52.0
black-formatter|ms-|2023.4.1
isort|ms-|2023.10.1
python|ms-|2023.20.0
vscode-pylance|ms-|2023.11.10
jupyter|ms-|2023.10.1003070148
jupyter-renderers|ms-|1.0.17
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-slideshow|ms-|0.1.5
remote-ssh|ms-|0.107.0
remote-ssh-edit|ms-|0.86.0
remote-explorer|ms-|0.4.1
vs-keybindings|ms-|0.2.1
autodocstring|njp|0.6.1
vscode-yaml|red|1.14.0
markdown-preview-enhanced|shd|0.8.10
code-spell-checker|str|3.0.1
snakeviz|til|0.0.2
markdown-all-in-one|yzh|3.5.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263:30335439
vscoreces:30445986
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
py29gd2263:30880072
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
3biah626:30602489
f6dab269:30613381
showlangstatbar:30737416
ecj1e332:30736112
pythonfmttext:30731395
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
pythonnosmt12:30797651
pythonidxpt:30866567
pythonnoceb:30805159
dsvsc013:30795093
dsvsc014:30804076
dsvsc015:30845448
pythontestfixtcf:30871695
pythonregdiag2:30871582
pyreplss2:30879913
pythonmypyd1:30879173
pythoncet0:30874138
pythontbext0:30879054
dsvsc016:30880769
dsvsc017:30880892
dsvsc018cf:30880895

```

</details>

**Comment by TianYuanSX** [comment]
Hi, the timeline I mentioned is the local history (VS code built-in feature), not the git.
Local history for text files (*.py) works fine. But for *.ipynb, sometimes it doesn't works.
Attach please find a gif file showing the issue.
![existing_ipynb](https://github.com/microsoft/vscode/assets/19888391/183b58fc-8ebd-4969-9373-ba8c04a73519)

I just tried to create a new Jupyterbook and found it worked. Just local history seems only store changes such as inserting new cell. Changes within the cell are not tracked. 
![newbook](https://github.com/microsoft/vscode/assets/19888391/9f50bce8-8583-47e9-a0a6-431e464785e9)

I also noticed that large files may be exlcuded. What's the limits? 
> Local History will track recentchanges as you save them unlessthe file has been excluded or istoo large. Source Control has notbeen configured.

**Comment by lszomoru** [comment]
Thanks for the clarifications. Assigning the issue to @bpasero.

**Comment by bpasero** [comment]
I can see a local history for GitHub issue notebooks, so I think something is wrong with that kind of notebook:

![image](https://github.com/microsoft/vscode/assets/900690/012b3f13-1bdf-477d-9324-539d8eef10fa)

**Comment by bpasero** [comment]
I cannot reproduce even with Jupyter notebooks from a simple test. For each save I see an entry. If you reveal the entries in the OS explorer from the context menu, is there anything strange going on in the folder? Like corrupted notebook files?

![Screenshot 2024-02-02 at 09 03 31](https://github.com/microsoft/vscode/assets/900690/7b644412-398e-42c9-9e93-2cca0dec5398)

**Comment by bpasero** [comment]
Btw there is a max file size that by default is set to `256kb` via the `workbench.localHistory.maxFileSize`. Is the notebook maybe just exceeding the file size?

**Comment by TianYuanSX** [comment]
Oh. I just tried. It works if the file size is below the limit. And I can manually create entry if it succeeds the limit.
My bad. Sorry for taking your much effort.
