### ISSUE TITLE
Issue with Locator.js Extension: Path Error in VS Code

### ISSUE THREAD

**Issue by sushantkadam15** [microsoft/vscode#197450]
Does this issue occur when all extensions are disabled?: Yes
Steps to Reproduce:

1. Updated the VS Code to the latest version
2. Use the Locator.js Extension and go to VS Code Window Log:

- VS Code Version: 1.84.0 (Universal)
- OS Version: macOS Venture 13.5.2 (22G91)

I'm encountering an issue with the Locator.js extension in VS Code, which allows me to navigate directly to React components from the browser. It was working fine previously but has now stopped functioning. The path format used by Locator.js is as follows:

`vscode://file/${projectPath}${filePath}:${line}:${column}`

Here are the steps I've taken to resolve the issue:
1. Reinstalled VS Code.
2. Reinstalled the Locator.js extension.

After some investigation, I found the following error in the VS Code Window Log:
```
2023-11-03 09:13:07.831 [error] [uncaught exception in main]: [UriError]: If a URI does not contain an authority component, then the path cannot begin with two slash characters ("//"): Error: [UriError]: If a URI does not contain an authority component, then the path cannot begin with two slash characters ("//")
```

Others have reported the same: https://github.com/infi-pc/locatorjs/issues/127

I've been searching for a solution but haven't been able to find one. Any assistance would be greatly appreciated.

**Comment by mjbvz** [comment]
Please start by filing this issue against that extension

**Comment by amananku26** [comment]
is there any alternate option for this locatorsJS?

**Comment by sushantkadam15** [comment]
@amananku26  Here's a workaround: https://github.com/infi-pc/locatorjs/issues/127#issuecomment-1801180366

**Comment by lzw10168** [comment]
![image](https://github.com/microsoft/vscode/assets/67814702/bcd0d720-6098-42ca-8983-f53e4dcdf047)

vscode://file/${projectPath}${filePath}:${line}:${column}
This configuration in vscode 1.85.0, chrome 120, is fine
