### ISSUE TITLE
Switching profiles causes unnecessary reload after extension updated 

### ISSUE THREAD

**Issue by RichardLuo0** [microsoft/vscode#197434]
Let's say two profiles share one extension, and you have updated this extension (including the reload step) in one profile, when you switch to another profile, vscode will tell you it needs to reload to complete updating the extension which you have already updated.

- VS Code Version: 1.84.0
- OS Version: Windows 11

Steps to Reproduce:

1. Create profile A and B
2. Install one same extension to both profiles
3. Update the extension then reload in profile A
4. switch to profile B
5. vscode will prompt that it needs to reload

**Comment by sandy081** [comment]
This is because, this extension is scoped to the profile and therefore update will update the extension only in that profile.
