### ISSUE TITLE
Workspace folder settings override

### ISSUE THREAD

**Issue by rustyx** [microsoft/vscode#197406]
I know that I can have per-workspace settings and also per-folder settings within the workspace.

The per-folder settings are stored in `<folder>/.vscode/settings.json`.

The problem with that is, many projects commit the .vscode folder into git. This makes it difficult to have custom per-folder settings, because the version from git will override those any time it changes in git (even if using --assume-unchanged or gitignore).

Hence hereby a request to make it possible to store per-folder settings in the workspace settings file itself.

For example, like this:

```
{
    "folders": [
        {
            "path": "projectA",
            "settings": {
                // folder settings
                . . .
                . . .
            }
        },
        {
            "path": "projectB",
            "settings": {
                // folder settings
                . . .
                . . .
            }
        }
    ],
    "settings": {
        // workspace settings
    }
}
```

Whether they are ranked lower or higher than the actual per-folder settings doesn't matter much to me currently. But it would be good to have it both ways, maybe with a flag.

**Comment by sandy081** [comment]
/duplicate

This request is similar to having local workspace settings which is already filed.

**Comment by rustyx** [comment]
@sandy081 normally when closing a ticket as duplicate a link to the duplicate should be included. Do you mind adding the link? Because I couldn't find it.

**Comment by sandy081** [comment]
https://github.com/microsoft/vscode/issues/40233
