### ISSUE TITLE
EFNF construction of XMLDecl in doc comment incorrectly previewed as empty string

### ISSUE THREAD

**Issue by nektro** [microsoft/vscode#197461]
Does this issue occur when all extensions are disabled?: Yes

```
Version: 1.78.2
Commit: b3e4e68a0bc097f0ae7907b217c1119af9e03435
Date: 2023-05-10T14:47:05.613Z
Electron: 22.5.2
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Linux x64 6.1.35
Sandboxed: No
```

Linux Version: NixOS 23.05 (Stoat) x86_64

Steps to Reproduce:

![image](https://github.com/microsoft/vscode/assets/5464072/01fe31aa-86d3-4fd8-9da9-2ab05782a761)

```js
/**
 * XMLDecl   ::=   '<?xml' VersionInfo EncodingDecl? SDDecl? S? '?>'
 */
function foo() {
    //
}

foo();
```

**Comment by nektro** [comment]
a friend pointed out wrapping the comment line in backticks works around the issue. it seems to think it is actual xml markup and strips it out, as many markdown parsers do, leaving only the surrounding single quotes

**Comment by mjbvz** [comment]
Yes this is expected and the proper fix is to use backticks. Otherwise it will be parsed as an invalid html element and stripped out
