### ISSUE TITLE
Change Zoom / font size on a per window basis

### ISSUE THREAD

**Issue by jwknz** [Microsoft/vscode#19747]
Currently zooming in on multiple windows affects all windows, not just the active one.
Would be nice to see this changed - I use 2 different screen sizes, so gets a bit annoying at the best of times. 

- VSCode Version: 1.9.0
- OS Version: macOS Sierra

Steps to Reproduce:

1. CMD+

**Comment by bpasero** [comment]
It is possible to configure  "window.zoomLevel" as a workspace setting to have zoom levels per window. The default action to zoom in will just not write to the workspace setting but global settings so the impact is on all windows.

Closing, as there is a workaround.

**Comment by jwknz** [comment]
So that sets a zoom for a preset workspace right? What about dynamic zoom? I want to be on a per window basis.

**Comment by jwknz** [comment]
@code team said it couldn't be done - and what you say is not what I mean

**Comment by bpasero** [comment]
@jwknz we do not support dynamic zoom outside of settings. You want to zoom without persisting this?
