### ISSUE TITLE
multi-cursor editing bug

### ISSUE THREAD

**Issue by smarts** [Microsoft/vscode#19744]
- VSCode Version: Code 1.9.0 (27240e71ef390bf2d66307e677c2a333cebf75af, 2017-02-02T08:31:00.827Z)
- OS Version: Windows_NT ia32 10.0.10586
- Extensions:

|Extension|Author|Version|
|---|---|---|
|csharp|ms-vscode|1.6.2|
|vscode-docker|PeterJausovec|0.0.11|

---

Steps to Reproduce:

1. open a file with multiple lines of text
2. Try to add a cursor by pressing Ctrl+Alt+DownArrow
3. The OS (Windows) captures this keystroke and rotates the screen display 180 degrees

**Comment by bpasero** [comment]
@smarts you can change keybindings to prevent this from happening (File > Preferences > Keybindings).

**Comment by smarts** [comment]
True. I'm just wondering if the default keybinding makes sense for Windows. Seems troublesome. I'll leave that to you guys though. Feel free to close the issue if you want =)

**Comment by EthanR** [comment]
Changing key bindings is always an option.
But on many Windows environments this is the default behavior, it is also note worthy that these are the instructions and keystrokes given in the Welcome, Interactive Playground tutorial.
![image](https://cloud.githubusercontent.com/assets/602856/23968263/6b0429c8-0998-11e7-9261-fe03a73b14de.png)

**Comment by alexandrudima** [comment]
Some display drivers decide to *eat* these keybindings at the OS level for e.g. rotating the screen. If you don't find that function useful, simply configure the other software to no longer capture those keybindings.
