### ISSUE TITLE
Visual Studio Code crashes when using native title bar under Wayland

### ISSUE THREAD

**Issue by PossiblyNocturnal** [microsoft/vscode#197497]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 
```
1.84.0
d037ac076cee195194f93ce6fe2bdfe2969cc82d
x64
```
- OS Version: 
```
Arch Linux x64
Linux 6.5.9-arch2-1
KDE Plasma 5.27.9
```

Steps to Reproduce:

1. Run vsc with --ozone-platform-hint=auto
2. If it successfully launched, try maximizing the application

Between multiple reinstalls, issue shifted between crashing when attempting to maximize vsc window and just instantly crashing without anything appearing. This seems to persist in insiders version as well, unfortunately. Using Custom title bar does not result in the crash, however.

[Pastebin link containing output acquired from running](https://pastebin.com/U4wypKgb) ``` WAYLAND_DEBUG=1 code --ozone-platform-hint=auto --verbose```

Attached zip archived .dmp file from vsc crash diretory as per native crash report guidelines below
[2da6cde1-5f83-40c7-831b-c5d0f7d39786.zip](https://github.com/microsoft/vscode/files/13261125/2da6cde1-5f83-40c7-831b-c5d0f7d39786.zip)

**Comment by SConaway** [comment]
Happens using latest VSCode insiders too. 

Here is a `.dmp` from my machine. 
[fbc6535c-0e20-4f88-a348-d03034599c00.zip](https://github.com/microsoft/vscode/files/13301260/fbc6535c-0e20-4f88-a348-d03034599c00.zip). 

I'm running Fedora Asahi Remix (so aarch64) on KDE Plasma. Might try switching to Gnome and seeing if it happens

**Comment by PossiblyNocturnal** [comment]
> Happens using latest VSCode insiders too.
> 
> Here is a `.dmp` from my machine. [fbc6535c-0e20-4f88-a348-d03034599c00.zip](https://github.com/microsoft/vscode/files/13301260/fbc6535c-0e20-4f88-a348-d03034599c00.zip).
> 
> I'm running Fedora Asahi Remix (so aarch64) on KDE Plasma.
> 
> On Gnome, this issue doesn't happen but the entire window is blurry (launching it with same options)

Can confirm, this doesn't seem to be happening on GNOME, so it's limited to KDE Wayland session it seems

**Comment by etdr** [comment]
Same thing here.

[Here](https://pb.ivo.st/?a70f5e7a85f7380a#5LAeubXw97zrPRbqa1fbzkpj8yJA7nFnYPBHSUwrWRxb) is the output from running `WAYLAND_DEBUG=1 code --ozone-platform-hint=auto --verbose` as in the original post.

[Here](https://github.com/microsoft/vscode/files/13452897/vscrash.zip) is a zip of my crash dump.

**Comment by Leuchak** [comment]
> > Happens using latest VSCode insiders too.
> > Here is a `.dmp` from my machine. [fbc6535c-0e20-4f88-a348-d03034599c00.zip](https://github.com/microsoft/vscode/files/13301260/fbc6535c-0e20-4f88-a348-d03034599c00.zip).
> > I'm running Fedora Asahi Remix (so aarch64) on KDE Plasma.
> > On Gnome, this issue doesn't happen but the entire window is blurry (launching it with same options)
> 
> Can confirm, this doesn't seem to be happening on GNOME, so it's limited to KDE Wayland session it seems

I'm using gnome 45 on arch x64 with linux 6.6.3  on wayland and I have this problem.
For me, the bug occurs only when opening new windows. I mean, let's say the computer has just started. I open VSCode, and the previously opened projects open in a minimized state. If I maximize the window, all instances of VSCode crash. If I reopen VSCode, the windows will still be minimized, but this time I can maximize them without any issues. After that, if I open a new project/folder in a new instance of VSCode, it will open in a minimized state. If I maximize this instance, all instances of VSCode will crash. I can reopen VSCode, and all previously opened projects will open again in a minimized state, but this time I will be able to maximize them without crashing.

**Comment by stlaz** [comment]
looks like a duplicate of https://github.com/microsoft/vscode/issues/184124

**Comment by akhiljalagam** [comment]
At the moment, I am utilizing Xwayland until a solution is available.

**Comment by PossiblyNocturnal** [comment]
Revisited this again after installing KDE Neon: seems like the issue is gone for me (maybe it was something I messed up myself couple of months ago which led to the crash or maybe this was fixed in one of the updates throughout couple of months I've been using Fedora with GNOME).
 
Everything is working as expected, so I'll close this issue now.
