### ISSUE TITLE
Running or debugging any Java code in Windows 10 with Arabic regional setting will not run or debug

### ISSUE THREAD

**Issue by EldesoukyElkhouly** [microsoft/vscode#197481]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version:  all versions
- OS Version:  windows 10 , windows 11

Steps to Reproduce:

1.  If windows regional setting Arabic (Egypt) run and debug any java code stuck and do not do anything -no output no run-
2.  If I change regional setting to English (US) its wok fine booth run and debug
3. This don't happen In Linux (any disto) only windows with Arabic locals
4. How to run and debug java without changing regional setting for the whole system?

**Comment by roblourens** [comment]
Please file this on the Java extension repo, thanks
