### ISSUE TITLE
Powershell is the default and the only terminal from VSCode when using the new 1.9.0 version of vscode.

### ISSUE THREAD

**Issue by amarzavery** [Microsoft/vscode#19746]
- VSCode Version: 1.9.0
- OS Version: Win 10

I upgraded to the new version of VS Code and found it astonishing that it forces me to use powershell !! Why dont we have an option to use command prompt? Why would you ever want powershell to be the default.

![image](https://cloud.githubusercontent.com/assets/4521223/22568119/6e5065b8-e947-11e6-8796-724cbb97dbfb.png)

**Comment by Tyriar** [comment]
Yes PowerShell is now the default to align with the direction Windows is going. You can easily change this back by adding the following to your settings.json file:

```js
"terminal.integrated.shell.windows": "C:\\Windows\\sysnative\\cmd.exe"
```

You can read more about the switch in the release notes https://code.visualstudio.com/updates/v1_9#_integrated-terminal-improvements
