### ISSUE TITLE
Explorer shortcut key doesn't always work

### ISSUE THREAD

**Issue by stevemckenzie** [microsoft/vscode#197455]
Type: <b>Bug</b>

Pretty easy to reproduce.

* View > Appearance > Activity Bar Position > Hidden
* Close VS Code
* Reopen VS Code
* Use the shortcut key to switch to "Find in Project" so the explorer view becomes hidden in the left panel
* Use the shortcut key to switch back to the explorer (command + option + e)

At this point the shortcut key will not work. If I change the activity bar position to be displayed again, it will work again and I can  hide the activity bar again. The issue will come back once I close and restart VS Code.

VS Code version: Code 1.84.0 (d037ac076cee195194f93ce6fe2bdfe2969cc82d, 2023-11-01T11:30:19.406Z)
OS version: Darwin x64 22.6.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz (8 x 4200)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|4, 4, 4|
|Memory (System)|32.00GB (1.02GB free)|
|Process Argv|--crash-reporter-id ca897f4b-f06b-4c46-9d09-91632f387a91|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (39)</summary>

Extension|Author (truncated)|Version
---|---|---
heroicons|afz|0.0.5
project-manager|ale|12.7.0
vscode-tailwindcss|bra|0.10.3
npm-intellisense|chr|1.4.5
path-intellisense|chr|2.8.5
vscode-svgviewer|css|2.0.0
vscode-eslint|dba|2.4.2
javascript-ejs-support|Dig|1.3.3
gitlens|eam|14.4.1
vscode-html-css|ecm|1.13.1
prettier-vscode|esb|10.1.0
figma-vscode-extension|fig|0.2.7
auto-close-tag|for|0.5.14
copilot|Git|1.133.0
copilot-chat|Git|0.10.0
jbockle-format-files|jbo|3.4.0
isort|ms-|2023.10.1
python|ms-|2023.20.0
vscode-pylance|ms-|2023.11.10
jupyter|ms-|2023.10.1003070148
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.17
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-slideshow|ms-|0.1.5
color-highlight|nau|2.5.0
vs-sequential-number|nep|1.1.0
title|nil|0.1.0
vscode-css-peek|pra|4.4.1
prisma|Pri|5.5.2
ejs-language-support|Qas|0.0.1
seti-icons|qin|0.1.3
es6-mocha-snippets|spo|0.2.2
sort-lines|Tyr|1.11.0
vscode-todo-highlight|way|1.0.5
vscode-import-cost|wix|3.3.0
change-case|wma|1.0.0
pretty-ts-errors|yoa|0.5.2
sort-js-object-keys|zen|1.0.6
html-css-class-completion|Zig|1.20.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscorecescf:30445987
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
py29gd2263:30880072
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
282f8724:30602487
89544117:30613380
showlangstatbar:30737416
pythonfmttext:30731395
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
pythonnosmt12:30797651
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30869155
dsvsc013:30795093
dsvsc014:30804076
dsvsc015:30845448
pythontestfixt:30871694
pythonregdiag2:30871582
pyreplss2:30879913
pythonmypyd1:30879173
pythoncet00cf:30874137
pythontbext0:30879054
dsvsc016cf:30880770

```

</details>

**Comment by peter-fb** [comment]
This seems to be a duplicate of #197169.

**Comment by stevemckenzie** [comment]
@peter-fb thanks.
