### ISSUE TITLE
Turn off modified elsewhere

### ISSUE THREAD

**Issue by lorsonblair** [microsoft/vscode#197410]
This is not an issue per say, but how can I turn this off and edit setting.json as before? Also, where are the settings modified? Thanks.

**Comment by rzhao271** [comment]
If you hover over modified elsewhere, it should show you where else the setting was modified.

Also, can you clarify what you mean by "edit setting.json as before"?

**Comment by lorsonblair** [comment]
Ok thank you. 

There was an "edit in settings.json" link in Quick Suggestions that allowed you to change the settings in an editor.
