### ISSUE TITLE
Global list styles prevent disabling colors

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#197574]
We set up this stylesheet of global css rules that apply to all lists: https://github.com/microsoft/vscode/blob/7d2c73944dba9e957ccc52557be681f5a7ae0cb0/src/vs/platform/list/browser/listService.ts#L82-L83

We also set up rules per-list, which usually override the global rules

<img width="429" alt="image" src="https://github.com/microsoft/vscode/assets/323878/ce20f51e-2c01-468e-bbbc-88b0aae83570">

and so I have never understood what the purpose of the global rules are. If I try to disable a style rule by setting a style to `undefined` in `overrideStyles` when I create my tree, then the per-list rule is gone but the global list rule still applies, so I can really only override it with my own `!important` rule. This has caused issues in notebooks and chat, and after talking to @aeschli about it I noticed that it shows up in the problems view with this black lightbulb as well

<img width="142" alt="image" src="https://github.com/microsoft/vscode/assets/323878/d6953aab-0683-4e7a-bb4c-fbc1f3b69004">

and in chat we have to work around it for the avatar codicon and our toolbars

<img width="395" alt="image" src="https://github.com/microsoft/vscode/assets/323878/139d4400-9051-4f62-bf07-103db6916bcd">

so I want to find out what the purpose of the global list rules is and whether we can get rid of it. Do you know @joaomoreno?

**Comment by joaomoreno** [comment]
I really don't any more. If you find out that we'd do just fine without it, I'd be happy to review a PR!

**Comment by mjbvz** [comment]
Removed this in #228173. I tested a bunch of lists throughout the workbench but please let me know if you notice any regressions
