### ISSUE TITLE
Documents about context menu 

### ISSUE THREAD

**Issue by modz4567** [microsoft/vscode#197519]
Hi any documents about the shell context menu not duplicating when installing also is it using spare packages for this would like more information  about this please

**Comment by Tyriar** [comment]
Please provide a screenshot or [a gif](https://gifcap.dev/) illustrating the problem (attaching images won't work via email, you need to go to github.com). See [this wiki page](https://github.com/microsoft/vscode/wiki/Terminal-Issues) for more general info on how to report actionable terminal issues.

/label "info-needed"

**Comment by modz4567** [comment]
It's not an issue just no documents about the context menu not duplicated I'm trying to find about but nothing that I can find
