### ISSUE TITLE
    "window.menuBarVisibility": "hidden" fails after restart

### ISSUE THREAD

**Issue by LordZane** [Microsoft/vscode#19754]
- VSCode Version: Code 1.9.0 (27240e71ef390bf2d66307e677c2a333cebf75af, 2017-02-02T08:31:00.827Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

|Extension|Author|Version|
|---|---|---|
|theme-atom-one-dark|andischerer|0.0.1|
|better-toml|bungcip|0.2.0|
|python|donjayamanne|0.5.6|
|EditorConfig|EditorConfig|0.3.4|
|vscode-icon-theme|jtlowe|1.4.0|
|vscode-rust|kalitaalexey|0.3.6|
|MagicPython|magicstack|1.0.3|
|atom-keybindings|ms-vscode|1.8.3|
|csharp|ms-vscode|1.6.2|
|debug|webfreak|0.16.0|

---

Steps to Reproduce:

1. Set `"window.menuBarVisibility": "hidden"` (menu bar goes hidden and works fine)
2. Close and reopen vscode
3. Menubar is open

**Comment by LordZane** [comment]
Weird, it suddenly stopped happening after messing around with my settings file, I think I had a value set wrong somewhere

**Comment by xwvvvvwx** [comment]
I can reproduce with 1.9.0 on linux 64bit (nixOS).

I can still reproduce even after disabling all addons and settings except `"window.menuBarVisibility": "hidden"`.

I am only able to reproduce with the release build downloaded from the website. I cannot reproduce with a dev version built locally (even from the same commit as the 1.9.0 release)
