### ISSUE TITLE
Setting a breakpoint on VScode Windows breaks processing of node worker_threads when the project has a special character in the path

### ISSUE THREAD

**Issue by seanjb** [microsoft/vscode#197599]
I was running into issues debugging any code using node worker_threads. Code would debug fine until it reached the creation of the worker thread where the process would start but nothing would happen. 
This issue only occurred when breakpoints were set and enabled. If no breakpoints were enabled the code ran successfully. 
Having a Special Character in my name all of my source code was ultimatly under a folder containing my name in the path Seán hence the issue was affecting me but not others.

Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.84.1
- OS Version: Windows_NT x64 10.0.22621

**Steps to Reproduce:**

1. Checkout the bug reproduction code here https://github.com/seanjb/node-worker-debug-issue to a path such as `C:\tools\replicáte\node-worker-debug-issue` note the special character in the path name.
2. Open the folder in vscode and attempt to debug (use script Bug V1 or Bug V2) ensuring no breakpoints are set. Process will run and close successfully. 
3. Set a breakpoint anywhere in any file. Then debug again. The debugger freezes after the worker thread has been started. The worker thread process is visible but produces no output and the process does not complete.

**Workaround** 
Move your project code to a path without special characters and it will bebug with breakpoints fine.

**Comment by seanjb** [comment]
Debugger logs when the issue was encountered running code under a path with a special character `C:\tools\replicáte\node-worker-debug-issue`
[vscode-debugadapter-ea6ad81b-bp-special-char.json.gz](https://github.com/microsoft/vscode/files/13273762/vscode-debugadapter-ea6ad81b-bp-special-char.json.gz)

Debugger loads when the issue was NOT encountered running same code under a path with no special character `C:\tools\replicáte\node-worker-debug-issue` 
[vscode-debugadapter-cb1870d8.json-bp-no-speical-char.gz](https://github.com/microsoft/vscode/files/13273766/vscode-debugadapter-cb1870d8.json-bp-no-speical-char.gz)

**Comment by connor4312** [comment]
Duplicate the upstream issue: https://github.com/nodejs/node/issues/50516
