### ISSUE TITLE
Enable reopening of closed tabs

### ISSUE THREAD

**Issue by mabtoptechnologies** [microsoft/vscode#197582]
Enable reopening of closed tabs

**Comment by bhainesva** [comment]
Does the "View: Reopen Closed Editor" command do what you want?

**Comment by benibenj** [comment]
@mabtoptechnologies, you can use the command "View: Reopen Closed Editor" as @bhainesva mentioned. Is this what you were looking for?

**Comment by mabtoptechnologies** [comment]
> Does the "View: Reopen Closed Editor" command do what you want?

Requesting if it should be added on the context menu when i right click of the tab
![Screenshot (19)](https://github.com/microsoft/vscode/assets/122657979/b46e7f9f-2cd4-44f0-980b-d1350589e489)

**Comment by benibenj** [comment]
We are not planning on adding it to the context menu as there is already a lot off actions in it.
