### ISSUE TITLE
Missing package in https://update.code.visualstudio.com/1.84.0/win32-archive/stable

### ISSUE THREAD

**Issue by blrobl** [microsoft/vscode#197554]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.84.0
- OS Version: Windows_NT x64 10.0.22621

Steps to Reproduce:

1. Have a script like this:
 ```
import { runTests } from 'vscode-test';
async function main() {
....

        // Download VS Code, unzip it and run the integration test
        await runTests(
            {
                extensionDevelopmentPath,
                extensionTestsPath,
});
...
    } 
}
```

2. When running it I get:

Downloading VS Code 1.84.0 from https://update.code.visualstudio.com/1.84.0/win32-archive/stable
Failed to get VS Code archive location
Failed to run tests
Error: Failed to download and unzip VS Code 1.84.0
    at Object.<anonymous> (D:\a\_work\1\s\source\Prod\vscode-al\node_modules\vscode-test\out\download.js:255:27)
    at step (D:\a\_work\1\s\source\Prod\vscode-al\node_modules\vscode-test\out\download.js:36:23)
    at Object.throw (D:\a\_work\1\s\source\Prod\vscode-al\node_modules\vscode-test\out\download.js:17:53)
    at rejected (D:\a\_work\1\s\source\Prod\vscode-al\node_modules\vscode-test\out\download.js:9:65)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

3. I'm running latest version of vscode-test and it works if I use the code below, so I assume you forgot to upload the package to the link, which is says Not Found. However, it's weird that I get redirected to win32-archive.
```
        await runTests(
            {
                version: '1.83.1',
                extensionDevelopmentPath,
                extensionTestsPath
            });
```

**Comment by alexr00** [comment]
We've deprecated the Windows 32-bit builds. There's been a banner in VS Code that says "VS Code on Windows 32-bit will soon stop receiving updates. Consider upgrading to the 64-bit build." since the August release (https://github.com/microsoft/vscode/pull/189031).

**Comment by joaomoreno** [comment]
Actually, we should fix this in vscode-test: https://github.com/microsoft/vscode-test/pull/242
