### ISSUE TITLE
After update to 1.9.0

### ISSUE THREAD

**Issue by SudhanshuAggarwal** [Microsoft/vscode#19755]
![image](https://cloud.githubusercontent.com/assets/1918182/22569867/fe178d9c-e94d-11e6-9cce-d65eacdcfd7d.png)
This is extremely severe issue. All my cs files are like this now. The code has been smushed together completely.

- VSCode Version: 1.9.0
- OS Version:Mac OSX El Capitan 10.11.6

Steps to Reproduce:

1. Update VSCode to 1.9.0
2. Restart VSCode

**Comment by mquandalle** [comment]
Have you tried to run VSCode with `code --disable-extensions` to see if that changes something?

**Comment by jack-pallot** [comment]
I wonder if this is related to the monospace optimisations?!

A possible fix might be to add "editor.disableMonospaceOptimizations": true to your settings.json file.

**Comment by SudhanshuAggarwal** [comment]
Ill try that and let you know.

**Comment by SudhanshuAggarwal** [comment]
@mquandalle  and @jack-pallot neither worked.

**Comment by jack-pallot** [comment]
The only other thing I can think of is the possibility of your line-height reverting back after the update. If I set my editor line-height to a low value I can sort of get the effect you have above. I'd try bumping this up a lot to see if it makes any difference. Also, check your workspace settings as well as your user ones.

"editor.lineHeight": 40,

**Comment by Tyriar** [comment]
Yes this looks like `editor.lineHeight` is at fault. Can you share your `settings.json` file?

**Comment by Suzal3579** [comment]
Only **CS files** you say? @SudhanshuAggarwal .For me it was for every file opened in VS Code. Did you try @jack-pallot 's solution mentioned above about **editor.lineHeight**?

I installed a lower version ( V 1.8.1) of VS Code due to this issue.

**Comment by SudhanshuAggarwal** [comment]
I will try it soon. Sorry i was away from the computer for a bit. I can't even see the settings file because it's cramped like this too. I'll have to copy paste it outside somewhere and then find this variable and change it and see if that works

**Comment by SudhanshuAggarwal** [comment]
Oh my god yes! there was an entry of lineHeight 0.8 on my user settings file for VSCode. Definitely got added because of update. Setting it back to 40 fixed the issue. Hopefully helps others! Thank you!

**Comment by alexandrudima** [comment]
:+1: Thank you for following up.
