### ISSUE TITLE
UI Bug

### ISSUE THREAD

**Issue by sulthonzh** [Microsoft/vscode#19759]
- VSCode Version: 1.9.0
- OS Version:Ubuntu_16.04_x64

![bug code](https://cloud.githubusercontent.com/assets/4921059/22572763/29dfa286-e9d8-11e6-9f7c-2d74af561c7b.png)

Steps to Reproduce:
Not bug code reporting, only bug UI like pict. :D

**Comment by chrmarti** [comment]
Tracked with #18861
