### ISSUE TITLE
Can't override cmd+enter in terminal

### ISSUE THREAD

**Issue by atombender** [Microsoft/vscode#19751]
Tried this:

```
	{
		"key": "cmd+enter",
		"command": "workbench.action.focusActiveEditorGroup",
		"when": "terminalFocus"
	},
	{
		"key": "shift+cmd+enter",
		"command": "workbench.action.terminal.focus",
		"when": "terminalFocus"
	},
```

However, the terminal pane seems to hijack `cmd+enter`. It's not possible to override it. Same with `cmd+shift+enter`.

**Comment by kaiwood** [comment]
Confirmed. But shortcut works if you add ` workbench.action.focusActiveEditorGroup` to `terminal.integrated.commandsToSkipShell` in the settings.

**Comment by atombender** [comment]
So it does, thanks. That setting seems really hacky. And it seems that to override it, I have to include the whole list in my override, which isn't going to be future proof (is there a way to append only?).

**Comment by Tyriar** [comment]
Yes this is as designed unfortunately, I created https://github.com/Microsoft/vscode/issues/19770 to capture the thoughts I've been having on this problem.
