### ISSUE TITLE
[Feature Request] UI Theme vs Syntax Theme

### ISSUE THREAD

**Issue by gerardp** [Microsoft/vscode#19752]
It would be great to be able to change the theme of the application (tabs, tree view, status bar…) but not the syntax theme

Something like this (atom): 

![captura de pantalla 2017-02-02 a las 21 57 26](https://cloud.githubusercontent.com/assets/168353/22568947/f98ccfa6-e995-11e6-8de4-4d0f21da21b6.png)

Thanks

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/3112
