### ISSUE TITLE
Ordering of items in command palette is not as expected

### ISSUE THREAD

**Issue by stewartadam** [Microsoft/vscode#19757]
Somewhat of a more minor UX issue, but ...

- VSCode Version: 1.9.0
- OS Version: macOS 12.10.3

Steps to Reproduce:

1. Cmd+Shift+P
2. Type 'Install'

Expected result: Offers to install extensions
Actual result: First hit is 'Disable all installed extensions', the exact opposite

**Comment by bpasero** [comment]
Lets mark this as duplicate of https://github.com/Microsoft/vscode/issues/14727
