### ISSUE TITLE
High CPU Usage - 20%

### ISSUE THREAD

**Issue by odmro** [microsoft/vscode#197540]
Type: <b>Performance Issue</b>

While it's open. 

VS Code version: Code 1.84.0 (d037ac076cee195194f93ce6fe2bdfe2969cc82d, 2023-11-01T11:28:21.782Z)
OS version: Linux x64 6.5.9-200.fc38.x86_64
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 3 5425U with Radeon Graphics (8 x 4141)|
|GPU Status|2d_canvas: unavailable_software<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>opengl: disabled_off<br>rasterization: disabled_software<br>raw_draw: disabled_off_ok<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software<br>webgpu: disabled_off|
|Load (avg)|2, 2, 1|
|Memory (System)|6.60GB (1.46GB free)|
|Process Argv|--unity-launch --crash-reporter-id edf66a41-a97e-46b8-87e3-d7ba5c2295d2|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|cinnamon|
|XDG_CURRENT_DESKTOP|X-Cinnamon|
|XDG_SESSION_DESKTOP|cinnamon|
|XDG_SESSION_TYPE|x11|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	   169	 18888	code main
    0	    41	 18891	   zygote
    0	   210	 18927	     gpu-process
    0	    41	 18892	   zygote
    0	     7	 18894	     zygote
    0	   338	 18978	window [1] (Release Notes: 1.84.0 - V3 - Visual Studio Code)
    1	   724	 19382	       window
    0	   101	 19650	window [2] (Issue Reporter)
    0	    61	 18932	   utility-network-service
    0	   122	 19032	extensionHost [1]
    0	   101	 19163	     electron-nodejs (/usr/share/code/code --ms-enable-electron-run-as-node --max-old-space-size=3072 /usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js --serverMode partialSemantic --useInferredProjectPerProjectRoot --disableAutomaticTypingAcquisition --cancellationPipeName /tmp/vscode-typescript1000/4d9e9846e00fdecc2cdf/tscancellation-5b3547d0920b52c021fa.tmp* --locale en --noGetErrOnBackgroundUpdate --validateDefaultNpmLocation --useNodeIpc)
    0	   210	 19164	     electron-nodejs (/usr/share/code/code --ms-enable-electron-run-as-node --max-old-space-size=3072 /usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js --useInferredProjectPerProjectRoot --enableTelemetry --cancellationPipeName /tmp/vscode-typescript1000/4d9e9846e00fdecc2cdf/tscancellation-c45f8bae83e29efd81f2.tmp* --locale en --noGetErrOnBackgroundUpdate --validateDefaultNpmLocation --useNodeIpc)
    0	    74	 19183	       electron-nodejs (/usr/share/code/code --ms-enable-electron-run-as-node /usr/share/code/resources/app/extensions/node_modules/typescript/lib/typingsInstaller.js --globalTypingsCacheLocation /home/odm/.cache/typescript/5.2 --enableTelemetry --typesMapLocation /usr/share/code/resources/app/extensions/node_modules/typescript/lib/typesMap.json --validateDefaultNpmLocation)
    0	    68	 19352	     electron-nodejs (/usr/share/code/code --ms-enable-electron-run-as-node /usr/share/code/resources/app/extensions/json-language-features/server/dist/node/jsonServerMain --node-ipc --clientProcessId=19032)
    0	    88	 19042	shared-process
    0	     0	 19666	     /usr/bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0	   108	 19043	fileWatcher [1]
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (Release Notes: 1.84.0 - V3 - Visual Studio Code)
|    Folder (V3): more than 20218 files
|      File types: php(15149) md(532) json(313) stub(204) woff2(140) rst(74)
|                  js(51) dist(41) gitignore(34) css(29)
|      Conf files: dockerfile(12) package.json(2) makefile(2);
```

</details>
<details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-sql-formatter|adp|1.4.4
ascii-tree-generator|apr|1.2.4
smarty-template-support|asw|2.1.1
vscode-tailwindcss|bra|0.10.3
auto-close-tag|for|0.5.14
vscode-mysql|for|0.5.0
atom-keybindings|ms-|3.3.0
sftp|Nat|1.16.3
vscode-xml|red|0.26.1

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
py29gd2263:30880072
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
282f8724:30602487
f6dab269:30613381
vscrpc:30673769
showlangstatbar:30737416
pythonfmttext:30731395
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
pythonnosmt12:30797651
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30869155
dsvsc013:30795093
dsvsc014:30804076
dsvsc015:30845448
pythontestfixtcf:30871695
pythonregdiag2:30871582
pyreplss2:30879913
pythonmypyd1:30879173
pythoncet0:30874138
pythontbext0:30879054

```

</details>

**Comment by odmro** [comment]
It seems that the main issue is caused by the number of current workspace number of files

|  Window (Release Notes: 1.84.0 - V3 - Visual Studio Code)
|    Folder (V3): more than 20218 files
|      File types: php(15149) md(532) json(313) stub(204) woff2(140) rst(74)
|                  js(51) dist(41) gitignore(34) css(29)
|      Conf files: dockerfile(12) package.json(2) makefile(2);

Once I open a smaller folder, the CPU usage drops back to normal

**Comment by bpasero** [comment]
Can you follow this wiki and post the results back here to understand more about why performance is so bad for you: https://github.com/Microsoft/vscode/wiki/Performance-Issues

Thanks!
