### ISSUE TITLE
Opening Local Folders is Unsupported on Android

### ISSUE THREAD

**Issue by cbrngrz** [microsoft/vscode#197508]
Related: https://github.com/microsoft/vscode/issues/149899

Using Galaxy Tablet S9+, latest version of Chrome browser. Same issue using the "app" version that is downloaded after visiting vscode.dev.

 Getting the error message:

```
Opening Local Folders is Unsupported
Your browser doesn't support opening local folders.
You can either open single files or open a remote repository
```

Steps to reproduce:
1. Navigate to vscode.dev
2. Select "Open Folder"

According to the previous issue, it says its related to the browser supporting the API, however I'm using Chrome which looks to be fully supported. This doesn't seem to be an issue on Windows using Chrome.

**Comment by danielo515** [comment]
Latest version of chrome shows the same problem

**Comment by Tym-not-Tym** [comment]
I tried it on Microsoft edge browser,  same problem.

**Comment by DRSDavidSoft** [comment]
Same issue on Galaxy Tab S10 Ultra on both Edge and Chrome.

Can the VS Code team contact the Edge for Android team to add the missing folder open APIs?

**Comment by iboros445** [comment]
Same here, anyone found a browser that supports the feature?

**Comment by Palash90** [comment]
Same here, tried to open using Chrome on Android, it is not working.

**Comment by Tym-not-Tym** [comment]
The only solution available right now is tunneling. However, you are
supposed to have a running PC.
