### ISSUE TITLE
"show task log" shows a notification instead of a log

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#197598]
- Run "Show task log" command
- Get a notification, "there are task errors", click  "show output"
- I don't see any log or errors

![Recording 2023-11-06 at 17 07 24](https://github.com/microsoft/vscode/assets/323878/5c47798b-db2c-4cb2-b3e7-df207d808c8f)

Heard something about task logging during standup and noticed this.

**Comment by meganrogge** [comment]
Oh actually, the task changes didn't make it into insider's today. So not convinced this is a bug or related to the changes. Will investigate

**Comment by meganrogge** [comment]
Anything interesting with your task config/ had you made changes to it?

**Comment by roblourens** [comment]
No, I see this in every window currently. for example, in a single-folder window with the vscode repo

**Comment by meganrogge** [comment]
My task changes went in 10 hrs ago and the latest build was 18 hrs ago. I also cannot reproduce 🤔

**Comment by meganrogge** [comment]
I can reproduce in an old stable

**Comment by roblourens** [comment]
I wasn't saying your changes did it, just that it seems wrong
