### ISSUE TITLE
Reordering tabs takes file out of preview mode

### ISSUE THREAD

**Issue by whitlockjc** [Microsoft/vscode#19756]
- VSCode Version: Code 1.9.0 (27240e71ef390bf2d66307e677c2a333cebf75af, 2017-02-02T08:23:30.856Z)
- OS Version: Darwin x64 16.4.0
- Extensions:

|Extension|Author|Version|
|---|---|---|
|bazel-code|DevonDCarew|0.1.3|
|vscode-docker|PeterJausovec|0.0.11|
|vscode-theme-onedark|akamud|0.3.1|
|Go|lukehoban|0.6.53|
|Theme-MaterialKit|ms-vscode|0.1.1|

---

Steps to Reproduce:

1. Open multiple files
2. Open a file in preview mode
3. Move the tab for the file in preview mode

When the tab is moved, the file is no longer in preview mode.

**Comment by bpasero** [comment]
I am closing this as "works as designed". Moving the tab is something we take as action to mark the tab important.
