### ISSUE TITLE
Prompted for workspace trust in empty window when installing Copilot Chat

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode#197570]
1. Open an empty window
2. Install Copilot Chat
3. :bug: get prompted to trust the workspace before I can proceed to install the extension

**Comment by lszomoru** [comment]
@joyceerhl, what is the value of the `security.workspace.trust.emptyWindow` setting?

**Comment by joyceerhl** [comment]
It is the default:
<img width="973" alt="image" src="https://github.com/microsoft/vscode/assets/30305945/8517624c-2f99-47d0-bf97-6d50ba7cc4d2">

**Comment by Kemeros** [comment]
Even without Copilot Chat, restricted mode activates itself in empty window for me:

![image](https://github.com/microsoft/vscode/assets/15658976/6ee0f236-0588-4f0b-bd11-6774b48b56e9)

**Comment by lszomoru** [comment]
@joyceerhl, I am unable to reproduce this with the latest VS Code Insiders release. Are you still able to reproduce? Thanks!
