### ISSUE TITLE
php is not working inside tags <?php ?>

### ISSUE THREAD

**Issue by arthur0071** [microsoft/vscode#197685]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: i searched but i dont found it, i install it today 
- OS Version: windows 11

Steps to Reproduce:

1. try to use php
2.doest works
look this image: 
![image](https://github.com/microsoft/vscode/assets/150199900/6f7fcef5-a257-4bb5-a5ef-9fe9da94119b)
i tried so many times and dont work, but i have another error : when i run the file and go to chrome, this happens : 
![image](https://github.com/microsoft/vscode/assets/150199900/25e27f05-22b4-41ef-a5c6-b7e4cc49b96e)

**Comment by arthur0071** [comment]
esqueci de editar o texto, mas não desativo as extensões

**Comment by arthur0071** [comment]
I forgot to edit the text, but I don't disable the extensions

**Comment by RedCMD** [comment]
seems the html grammar just doesn't support php

**Comment by burtek** [comment]
How exactly are you opening the php file in browser? You need a php-capable server software to run php files locally (and probavly rename file to .php or change the server's config).

Also, running of php files has nothing to do with vscode.

**Comment by arthur0071** [comment]
> How exactly are you opening the php file in browser? You need a php-capable server software to run php files locally (and probavly rename file to .php or change the server's config).
> 
> Also, running of php files has nothing to do with vscode.

oh i tried to run with the server wamp and it works, thanks
