### ISSUE TITLE
Report disappears

### ISSUE THREAD

**Issue by durandt** [microsoft/vscode#197615]
Type: <b>Bug</b>

I started an issue, alt-tabed to the terminal and chrome, alt-tab back and the issue editor was gone from VSCode... Now I will have to start writing my issue from scratch again. Duh. 

VS Code version: Code 1.84.1 (Universal) (2b35e1e6d88f1ce073683991d1eff5284a32690f, 2023-11-06T12:37:18.666Z)
OS version: Darwin x64 22.6.0
Modes:

<details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
csdevkit|ms-|1.0.14
csharp|ms-|2.9.20
dotnet-maui|ms-|0.4.9
vscode-dotnet-runtime|ms-|2.0.0
vscodeintellicode-csharp|ms-|0.1.26

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
py29gd2263cf:30880073
vscaac:30438847
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
2e4cg342:30602488
89544117:30613380
showlangstatbar:30737416
pythonfmttext:30731395
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
pythonnosmt12:30797651
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30869155
dsvsc013:30795093
dsvsc014:30804076
dsvsc015:30845448
pythontestfixtcf:30871695
pythonregdiag2:30871582
pythonmypyd1:30879173
pythoncet00cf:30874137
pythontbext0:30879054
dsvsc016:30880769
dsvsc017cf:30880893
aa_t_chat:30882232

```

</details>

**Comment by gjsjohnmurray** [comment]
I wasn't able to reproduce this on Windows, so maybe its a macOS thing.

**Comment by durandt** [comment]
@gjsjohnmurray Sorry, my brain has thawed since this morning and I just now realised I had mixed up Chrome's `Report an issue...` dialog with VSCode's `Report Issue` dialog. I had started the former instead of the later.
