### ISSUE TITLE
Extra characters being rendered in terminal

### ISSUE THREAD

**Issue by jackbrown** [Microsoft/vscode#19766]
- VSCode Version: Code 1.9.0 (27240e71ef390bf2d66307e677c2a333cebf75af, 2017-02-02T08:23:30.856Z)
- OS Version: Darwin x64 16.3.0
- Extensions:

|Extension|Author|Version|
|---|---|---|
|EditorConfig|EditorConfig|0.3.4|
|code-settings-sync|Shan|2.4.3|
|project-manager|alefragnani|0.13.2|
|vscode-eslint|dbaeumer|1.2.2|
|githistory|donjayamanne|0.1.5|
|vscode-npm-script|eg2|0.1.8|
|code-runner|formulahendry|0.6.7|
|sass-lint|glen-84|0.0.3|
|debugger-for-chrome|msjsdiag|2.5.1|
|chai-snippets|nwhatt|0.1.0|
|better-merge|pprice|0.5.1|
|cucumber|stevejpurves|0.9.6|
|language-stylus|sysoev|1.6.0|
|open-in-browser|techer|0.0.3|
|expresssnippet|vladmrnv|0.0.8|
|gitblame|waderyan|1.3.0|

---

Steps to Reproduce:

1. Open the terminal
2. Run any command

I'm seeing extra characters rendered at the end of output

![image](https://cloud.githubusercontent.com/assets/2359358/22574561/c6b3f76c-ea03-11e6-9eeb-b0b076b3ea98.png)

**Comment by Tyriar** [comment]
What's in your settings.json file?

**Comment by jackbrown** [comment]
@Tyriar 

```
{
    "terminal.integrated.shell.osx": "/usr/local/bin/fish",
    //disable default javascript validator replaced by eslint
    "javascript.validate.enable": false,
    "editor.fontSize": 13,
    "editor.tabSize": 2,
    "search.exclude": {
        ".git": true,
        "*.js.html": true,
        "coverage": true,
        "dist": true,
        "lib": true,
        "node_modules": true,
        "tmp": true
    },
    "files.insertFinalNewline": true,
    "files.trimTrailingWhitespace": true,
    "editor.renderWhitespace": "boundary",
    "window.zoomLevel": 0,
    "workbench.activityBar.visible": true,
    "sync.gist": "",
    "sync.lastUpload": "2017-01-09T00:28:42.765Z",
    "sync.autoDownload": false,
    "sync.autoUpload": false,
    "sync.lastDownload": "1970-01-01T00:00:00.000Z",
    "sync.version": 243,
    "sync.showSummary": true,
    "sync.forceDownload": false,
    "sync.workspaceSync": false,
    "sync.anonymousGist": false
  }
```

**Comment by Tyriar** [comment]
What will likely workaround this is adding the following:

```js
"terminal.integrated.flowControl": false
```

When true `^S` and `^Q` are being sent for the terminal to "catch up" with the backing process, currently it's enabled for all but zsh due to oh-my-zsh overriding the keybindings. I guess fish doesn't support it too.

Please let me know if the work around fixes it :smile:

**Comment by jackbrown** [comment]
@Tyriar that work around is working great 😄

**Comment by Tyriar** [comment]
Thanks, I'll make an exception for `fish` as well then.

**Comment by Tyriar** [comment]
Making this a candidate for the stability build as it will be pretty annoying for `fish` users.

**Comment by Tyriar** [comment]
Pushed to `release/1.9 `.

**Comment by Tyriar** [comment]
Verification steps:

- Set `$SHELL` to `/bin/bash`
- `terminal.integrated.flowControl` setting should be true
- Set `$SHELL` to `fish`
- `terminal.integrated.flowControl` setting should be false
- Set `$SHELL` to `/bin/fish`
- `terminal.integrated.flowControl` setting should be false

Note that you don't need to install `fish` to verify, just change `$SHELL` and relaunch..

**Comment by joaomoreno** [comment]
@Tyriar Is this really a candidate?

- Doesn't seem to be a regression
- Not critical, just a few random characters visible in the terminal, still usable
- No data loss
- Low impact: only `fish` users

I'm trying to limit the number of candidate issues.

**Comment by Tyriar** [comment]
@joaomoreno I put it in because:

- It is a regression
- It happens with other shells as well, such as `julia` https://github.com/Microsoft/vscode/issues/19815, it may also happen with other programming language shells too such as python, ruby's irb, haskell's ghci, etc
- The example above is the simple case where it only shows once. Doing an `ls -l` in a 20+ line folder for example, `^S^Q` will likely appear multiple times throughout the output, potentially in the middle of lines
- It was reported twice in a short period after releasing
- It's a very simple and safe fix; limiting use of `^S` and `^Q` to bash only

**Comment by joaomoreno** [comment]
Thanks, makes total sense!

**Comment by joaomoreno** [comment]
I'll verify this.

**Comment by joaomoreno** [comment]
Your fix seems in:

```
git branch --contains   8d0a979
  release/1.9
```

But it doesn't seem fixed, when using Powershell in OS X.

![image](https://cloud.githubusercontent.com/assets/22350/22697376/886395f2-ed51-11e6-8899-f0a2a304b379.png)

**Comment by joaomoreno** [comment]
Verified after discussion with @Tyriar

**Comment by adriaanthomas** [comment]
FWIW on 1.9.1 I still had this problem;

* my default shell is bash (`SHELL=/bin/bash`)
* I open a terminal in VS code, bash starts
* sometimes I need powershell so I'll open it from bash (by typing `powershell` in bash)
* whatever you do in PS, VS Code's process still sees `SHELL=/bin/bash` (I tried setting it in `$PROFILE` to `$env:SHELL = (Get-Command powershell).Path`). So 723b20093d2f525e84cdf94a52f7695d1d539273 does not work for me, and powershell is still unusable in VS Code terminal
* So I ended up setting `"terminal.integrated.flowControl": false` in my user settings and all is OK

**Comment by aliozgur** [comment]
I'm on latest 1.9.1 and the problem persists.

**Comment by Tyriar** [comment]
Yes this is still expected when `$SHELL` is bash but you launch another shell. I'm still thinking about the best way to handle this while still getting the benefits of flow control for bash. 

If you do this frequently please change the setting to false.

**Comment by Tyriar** [comment]
I've also marked the setting as experimental in upstream and may remove it entirely if there is no good solution.

**Comment by aliozgur** [comment]
Setting "terminal.integrated.flowControl" to false fixed the issue in my environment. 
MaxOS Sierra
VS Code 1.9.1

**Comment by AndreasHassing** [comment]
I open VSC with Fish shell (`code .` opens current directory in VSC), and it seems that VSC uses Bash internally.

I still need to disable `flowControl` to avoid the extra characters.

**Comment by tadayosi** [comment]
Hi @Tyriar,

I'm facing the same issue with bash on 1.9.1. I'd like to know why `terminal.integrated.flowControl` needs to be default to `true` for bash. Could you explain please?

Thank you.

**Comment by Tyriar** [comment]
I actually removed the feature completely from insiders today as I don't feel the benefits outweigh the negatives. You'll be able to remove that from your settings come v1.10.
