### ISSUE TITLE
The "expand" button for the bottom panel has disappeared.

### ISSUE THREAD

**Issue by sartyukhov** [microsoft/vscode#197682]
Type: <b>Bug</b>

Previously, there was an "expand" button right here (as shown in the screenshot).

<img width="444" alt="Снимок экрана 2023-11-07 в 23 53 47" src="https://github.com/microsoft/vscode/assets/23495999/0576c012-d0a0-413d-9442-bfb5d6dc8386">

This button would expand the bottom panel to full screen. It seems to have disappeared in one of the versions. Is there a way to bring it back through settings? That button was extremely convenient for me. 
Thank you.

VS Code version: Code 1.84.1 (2b35e1e6d88f1ce073683991d1eff5284a32690f, 2023-11-06T12:37:31.808Z)
OS version: Darwin arm64 23.1.0
Modes:

**Comment by gjsjohnmurray** [comment]
What alignment option have you set for the Panel?

**Comment by sartyukhov** [comment]
@gjsjohnmurray oh you are right, thank you
