### ISSUE TITLE
Editor actions in title does not seem to work

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#197607]
Steps:
* begin with multi tabs showing
* open an editor
* hide tab bar
* ✅ actions move to the top
* close editor
* open same editor
* 🐛 actions are not visible anymore, there is just a "..."

<img width="1348" alt="image" src="https://github.com/microsoft/vscode/assets/900690/e1645769-4227-43c2-91a5-1857c059f013">

**Comment by benibenj** [comment]
When creating the editor actions we rely on the `onDidChange` event to tell us when actions change. However, this event is not set when there is no active pane. In that case we should have a different event trigger the onDidChange event such as onDidChangeActiveEditor for example
