### ISSUE TITLE
Switch from tslint's no-unused-variables to tsc's noUnusedLocals

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#19769]
Because the former prints a deprecation message now. Blocked on https://github.com/Microsoft/TypeScript/issues/13120 - all of our actions that are registered with a decorator will error as unused.

**Comment by myknbani** [comment]
i think it has been undeprecated, since the linter does not interrupt compilation

**Comment by roblourens** [comment]
Not worth keeping this around.
