### ISSUE TITLE
search Follow Symlinks use cpu too much time on macos, please fixed it. I have no money to buy computer like m3.

### ISSUE THREAD

**Issue by zhangchunsheng** [microsoft/vscode#197608]
search Follow Symlinks use cpu too much time on macos, please fixed it. I have no money to buy computer like m3.

Version: 1.84.0 (Universal)
Commit: d037ac076cee195194f93ce6fe2bdfe2969cc82d
Date: 2023-11-01T11:30:19.406Z (5 days ago)
Electron: 25.9.2
ElectronBuildId: 24603566
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Darwin x64 22.6.0

**Comment by gjsjohnmurray** [comment]
The performance cost of having search follow symlinks is noted at https://github.com/microsoft/vscode/wiki/Search-Issues#slow-search-rg-running-for-a-long-time-or-consuming-lots-of-cpumemory

**Comment by andreamah** [comment]
Unfortunately, following symlinks have high performance as mentioned above and we are not planning on further optimizing this at this point.
