### ISSUE TITLE
Terminal top padding is too wide which occupies too many spaces.

### ISSUE THREAD

**Issue by Celthi** [microsoft/vscode#197611]
Does this issue occur when all extensions are disabled?: Yes/No

<html>
<body>

CPUs | Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz (12 x 3192)
-- | --
GPU Status | 2d_canvas: enabled canvas_oop_rasterization: enabled_on direct_rendering_display_compositor: disabled_off_ok gpu_compositing: enabled multiple_raster_threads: enabled_on opengl: enabled_on rasterization: enabled raw_draw: disabled_off_ok video_decode: enabled video_encode: enabled vulkan: disabled_off webgl: enabled webgl2: enabled webgpu: enabled
Load (avg) |  
Memory (System) | 15.80GB (5.39GB free)
Process Argv | --crash-reporter-id 375d3e2d-1bbf-46b3-8417-66f415b138c2
Screen Reader | no
VM | 0%
<img width="390" alt="image" src="https://github.com/microsoft/vscode/assets/5187962/fba695cc-8aa4-47df-b847-6c0417050b65">

</body>
</html>

**Comment by meganrogge** [comment]
Did you zoom?

likely /duplicate #130995

**Comment by Celthi** [comment]
@meganrogge I didn't zoom. I don't think they are duplicated.

**Comment by meganrogge** [comment]
Full screen screenshot would help and/or gif. 

Does changing `terminal.integrated.gpuAcceleration` help?

Does changing the shell type help?

**Comment by Celthi** [comment]
Changing the shell type does help if I rerender the terminal.
This indicates that it should be shell specific and then I think it is caused by [some settings of the shell](https://github.com/Celthi/MyConfig/blob/master/.zshrc), thus I'll close this issue. Great thanks for the help!
