### ISSUE TITLE
Cannot reliably open a folder from CLI with `code .`

### ISSUE THREAD

**Issue by stewartadam** [Microsoft/vscode#19761]
- VSCode Version: 1.9.0
- OS Version: macOS 10.12.3

Steps to Reproduce:

1. Open VS Code
2. Close all CMD+W until all windows are gone, but app is still open
3. Issue `code .` from terminal

Expected Result: VS Code opens with folder pane expanded showing contents of $PWD from my shell, 
Actual results: New untitled document opens

**Comment by Tyriar** [comment]
/cc @chrmarti due to welcome page?

I can't repro this in Linux

**Comment by Tyriar** [comment]
@stewartadam does this reproduce 100% of the time for you?

**Comment by stewartadam** [comment]
Yup, with instructions above it's 100% repro.

There's inconsistencies in the behavior between different VS Code states -- I've also seen this happen in some other configurations (e.g. running `code .` when app is not open at all, or when it is but with another project, or when it is open but not with a project).

**Comment by joaomoreno** [comment]
@stewartadam What do you get when running `which code` from the command line?

**Comment by stewartadam** [comment]
No output, exit status 1 -- I was using the following snippet in my profile:
```
code () {
    if [[ $# = 0 ]]
    then
        open -a "Visual Studio Code"
    else
        [[ $1 = /* ]] && F="$1" || F="$PWD/${1#./}"
        open -a "Visual Studio Code" --args "$F"
    fi
}
```

I removed this and used the "Install 'code' command in PATH" that was introduced in 1.0 and it's working a lot better now - thanks! Since I believe the snippet above was part of the older installation instructions, we may want to add an FAQ entry on [this page](https://code.visualstudio.com/docs/setup/mac) indicated to remove the profile function.

**Comment by joaomoreno** [comment]
Thanks for staying with us for so long! I'll make sure we write something up in the docs.
