### ISSUE TITLE
Don't call registerColor from registerThemingParticipant

### ISSUE THREAD

**Issue by hediet** [microsoft/vscode#197635]
Don't call registerColor from registerThemingParticipant, as this only works by accident.
`registerThemingParticipant` applies the theme to the registered color variables. At this point, no new colors should be registered.

https://github.com/microsoft/vscode/blob/e373517c9ec8c476403cf6838b864f3371708a3e/src/vs/workbench/contrib/interactive/browser/interactive.contribution.ts#L762-L788

Consider assigning these colors a 100% transparent color as default value. Then you can use a conditional check to only use this color if it is non-transparent, otherwise use the default color.

**Comment by amunger** [comment]
> Then you can use a conditional check to only use this color if it is non-transparent, otherwise use the default color.

Where would that take place? Inside of registerThemingParticipant?
We're using the Color as a `ThemeColor` object within the [jupyter extension here](https://github.com/microsoft/vscode-jupyter/blob/b8301b91156be853ab76f309e4ea7003438390b8/src/interactive-window/editor-integration/decorator.ts#L85), so we can't just adjust the css.

**Comment by hediet** [comment]
@aeschli do you know what they should do best here?
