### ISSUE TITLE
Newer vscode versions for ubuntu cause the navigation bar to turn white

### ISSUE THREAD

**Issue by MajorTomMan** [microsoft/vscode#197697]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:  1.84.1
- OS Version: Linux version 5.4.0-150-generic (buildd@bos03-amd64-012) (gcc version 7.5.0 (Ubuntu 7.5.0-3ubuntu1~18.04)) #167~18.04.1-Ubuntu SMP Wed May 24 00:51:42 UTC 2023

Steps to Reproduce:
You can see it as soon as you open vscode on Ubuntu, and no matter what theme you switch to, three-way or official, the top navigation bar is always white, even with a black theme. As a side note, this bug has been around for the last two to three versions.
here is screenshot
![Screenshot from 2023-11-08 11-40-22](https://github.com/microsoft/vscode/assets/47267913/df6d5e54-0b78-43eb-8770-c514639dcaf3)

**Comment by aiday-mar** [comment]
Hey Deepak, not sure who to assign, I thouhgt it's maybe related to electron? Feel free to reassign.

**Comment by deepak1556** [comment]
Are you using the native titlebar `"window.titleBarStyle": "native"` ?

**Comment by MajorTomMan** [comment]
> Are you using the native titlebar `"window.titleBarStyle": "native"` ?

The user json file didn't have this setting, but when I changed it to custom, this problem was solved, thanks!
