### ISSUE TITLE
Restrict quick open file to project files

### ISSUE THREAD

**Issue by nurp** [microsoft/vscode#19762]
- VSCode Version: 1.9.0
- OS Version: Windows 10

Steps to Reproduce:

1. ctrl+p
2. type index.html

I expect the first result to be the file in the current project folder (because 1. it is in local project, 2. it is the most recently opened, 3. most recently edited).

But it is a file that exist in completely different folder and not in the project. Because of this, I keep editing the wrong file.

**Comment by adambene** [comment]
+1

**Comment by shukerullah** [comment]
Any news on this issue?

**Comment by aliva** [comment]
This is really annoying to see unrelated files.

**Comment by jpike88** [comment]
This is seriously, SERIOUSLY annoying. I see files in my ~/Downloads folder, ~/Desktop, even when I have a workspace open that doesn't include those folders... how is this not being treated as a priority????

**Comment by jpike88** [comment]
And this is incorrect labelled. This is not a feature request, it's a bug.

**Comment by roblourens** [comment]
The only files that should show up there are files that have been opened in that workspace at some point. Some people want to be able to easily access these, some people don't want them at all. I think one thing that would help is being able to easily remove individual entries without clearing all editor history, e.g. an X icon on each row.

Also see issues here, https://github.com/microsoft/vscode/issues/27317, https://github.com/microsoft/vscode/issues/5806 to sort files closer to the current file, and I am pretty sure there is an issue to prioritize files in the current folder which I can't find right now.
