### ISSUE TITLE
characters don't repeat when `ApplePressAndHoldEnabled` is on

### ISSUE THREAD

**Issue by dluc** [Microsoft/vscode#19764]
- VSCode Version: Code 1.9.0 (27240e71ef390bf2d66307e677c2a333cebf75af, 2017-02-02T08:23:30.856Z)
- OS Version: Darwin x64 15.6.0
- Extensions:

|Extension|Author|Version|
|---|---|---|
|vscode-docker|PeterJausovec|0.0.7|
|scala|daltonjorge|0.0.4|
|githistory|donjayamanne|0.1.0|
|javadebugger|donjayamanne|0.0.2|
|python|donjayamanne|0.5.2|
|vscode-npm-script|eg2|0.0.21|
|json-tools|eriklynd|1.0.2|
|vscode-npm|fknop|3.3.0|
|code-runner|formulahendry|0.5.0|
|vscode-javac|georgewfraser|0.0.23|
|PowerShell|ms-vscode|0.7.2|
|csharp|ms-vscode|1.5.2|
|Ruby|rebornix|0.10.1|
|java|redhat|0.0.7|
|startanyshell|remcoros|0.3.1|
|vscode-icons|robertohuertasm|4.0.1|
|HOCON|sabieber|0.0.1|

---

Steps to Reproduce:

1. enable ApplePressAndHoldEnabled (see http://lifehacker.com/5826055/make-your-keyboard-keys-repeat-properly-when-held-down-in-mac-os-x-lion) (this is enabled by default on all MacOS installations)
2. Hold down the "a" key
3. The editor shows only one "a" letter instead of "aaaaaaaaaaaaaa...."

somehow some applications are not affected by this annoyance, e.g. iTerm2. It would be nice if VSCode could do something about it.

**Comment by kutsan** [comment]
Same problem here.

**Comment by alexandrudima** [comment]
This is an upstream issue (possibly within Chromium), and there are no known workarounds that we could implement on our side. This means there is no possible code change for us to do in VS Code sources to improve things. 

To keep the number of issues in our inbox at a manageable level, we’re closing issues that have been on the backlog for a long time but haven’t gained traction or that are not actionable. Thank you for your time and understanding.
