### ISSUE TITLE
style: activiy icon size is weird

### ISSUE THREAD

**Issue by jiawei-hong** [microsoft/vscode#197648]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.84.1
- OS Version: macOS Sonoma(14.0)

Steps to Reproduce:

1. change the color theme to high contrast theme
2. you will see the activity bar icon size and the border is weird

![before](https://github.com/microsoft/vscode/assets/32186630/0e722c95-35a7-4896-99e8-79627bfdc45e)

**Comment by gjsjohnmurray** [comment]
pinging @sandy081
