### ISSUE TITLE
VSCode is quite slow to start

### ISSUE THREAD

**Issue by dluc** [Microsoft/vscode#19768]
- VSCode Version: Code 1.9.0 (27240e71ef390bf2d66307e677c2a333cebf75af, 2017-02-02T08:23:30.856Z)
- OS Version: Darwin x64 15.6.0
- Extensions:

|Extension|Author|Version|
|---|---|---|
|vscode-docker|PeterJausovec|0.0.7|
|scala|daltonjorge|0.0.4|
|githistory|donjayamanne|0.1.0|
|javadebugger|donjayamanne|0.0.2|
|python|donjayamanne|0.5.2|
|vscode-npm-script|eg2|0.0.21|
|json-tools|eriklynd|1.0.2|
|vscode-npm|fknop|3.3.0|
|code-runner|formulahendry|0.5.0|
|vscode-javac|georgewfraser|0.0.23|
|PowerShell|ms-vscode|0.7.2|
|csharp|ms-vscode|1.5.2|
|Ruby|rebornix|0.10.1|
|java|redhat|0.0.7|
|startanyshell|remcoros|0.3.1|
|vscode-icons|robertohuertasm|4.0.1|
|HOCON|sabieber|0.0.1|

---

I set VSCode as the default editor for many file types, so that I can double click and have them open in VSCode :-) I noticed quite soon the impact on my workflow, i.e. the time spent waiting for files to open. For comparison I reverted back to Sublime Text as the default editor and the difference is very visible.

From a quick test using `time <command>` it appears that VSCode is at least twice as slow, and perhaps slower when the default editor is already open (i.e. the open instance could be reused to open the new file)

**Comment by bpasero** [comment]
@dluc when you feel a slow start you can use our new command to report a performance issue and that includes all the times spend. I am closing this one and wait for your report. You can do it via Cmd+Shift+P > Report Performance Issue

**Comment by dluc** [comment]
@bpasero 

- VSCode Version: <code>Code 1.9.0 (27240e71ef390bf2d66307e677c2a333cebf75af, 2017-02-02T08:23:30.856Z)</code>
- OS Version: <code>Darwin x64 15.6.0</code>
- CPUs: <code>Intel(R) Core(TM) i7-4960HQ CPU @ 2.60GHz (8 x 2600)</code>
- Memory (System): <code>16.00GB (0.02GB free)</code>
- Memory (Process): <code>163.79MB working set (0.00MB peak, 111.86MB private, 74.14MB shared)</code>
- Load (avg): <code>1, 1, 1</code>
- VM: <code>0%</code>
- Initial Startup: <code>no</code>
- Screen Reader: <code>no</code>
- Empty Workspace: <code>yes</code>
- Timings:

|Component|Task|Time (ms)|
|---|---|---|
|renderer|window.loadUrl() => begin to require(workbench.main.js)|267|
|renderer|require(workbench.main.js)|1067|
|renderer|create extension host => extensions onReady()|752|
|renderer|restore viewlet|0|
|renderer|restore editor view state|411|
|renderer|overall workbench load|637|
|main + renderer|start => extensions ready|2185|
|main + renderer|start => workbench ready|1983|

**Comment by bpasero** [comment]
@dluc thanks, those timings look quite good to me. Note that we still look into performance via https://github.com/Microsoft/vscode/issues/15455
