### ISSUE TITLE
color palette closes on click while toggeling to different color options (rgb/hsl/hex)

### ISSUE THREAD

**Issue by kkoli-9528** [microsoft/vscode#197677]
Type: <b>Bug</b>

Just enter any color and try to toggle to different color options.

VS Code version: Code 1.84.1 (2b35e1e6d88f1ce073683991d1eff5284a32690f, 2023-11-06T12:35:59.022Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-10600K CPU @ 4.10GHz (12 x 4104)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.90GB (24.13GB free)|
|Process Argv|--crash-reporter-id 931b4403-2786-4c06-803d-e5393af1fb4b|
|Screen Reader|no|
|VM|67%|
</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
prettier-vscode|esb|10.1.0
auto-rename-tag|for|0.1.10
code-runner|for|0.12.1
live-sass|gle|6.1.1
minify|Hoo|0.4.3
python|ms-|2023.20.0
vscode-pylance|ms-|2023.11.10
LiveServer|rit|5.7.9
es7-react-js-snippets|rod|1.9.3
vscode-icons|vsc|12.6.0
JavaScriptSnippets|xab|1.8.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
py29gd2263cf:30880073
vscaat:30438848
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
3biah626:30602489
f6dab269:30613381
a9j8j154:30646983
showlangstatbar:30737416
pythonfmttext:30731395
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
welcomedialog:30882109
pythonnosmt12:30797651
pythonidxpt:30866567
pythonnoceb:30805159
synctok:30869157
dsvsc013:30795093
dsvsc014:30804076
dsvsc015:30845448
pythontestfixtcf:30871695
pythonregdiag2:30871582
pyreplss2:30879913
pythonmypyd1:30879173
pythoncet00cf:30874137
pythontbext0:30879054
aa_t_chat:30882232

```

</details>

**Comment by kkoli-9528** [comment]
Could you please confirm if this is indeed a bug?

**Comment by aiday-mar** [comment]
Yes yes this is a bug, thank you for commenting here.

**Comment by kkoli-9528** [comment]
Could you kindly provide guidance on the procedure to follow after identifying a bug?

**Comment by aiday-mar** [comment]
Hi you have identified and reported an issue. Now it is up to the developer team to fix it. Thank you for taking the time to do this :)

**Comment by kkoli-9528** [comment]
Could you please inform me of how I can determine if the issue has been resolved?

**Comment by kkoli-9528** [comment]
I wanted to express my gratitude for the time you've taken to explain these things to me. Your positive attitude has made understanding them even more enjoyable. I truly appreciate it.

**Comment by kkoli-9528** [comment]
Could you please provide an update on the current status?

**Comment by aiday-mar** [comment]
Hey @kkoli-9528, yes apologies. This issue should be closed as of now, since a community user has made a PR to fix this issue (https://github.com/microsoft/vscode/pull/198100).
