### ISSUE TITLE
ResizeObserver loop completed with undelivered notifications

### ISSUE THREAD

**Issue by simonh1000** [microsoft/vscode#197629]
Does this issue occur when all extensions are disabled?: Yes/No

VS Code Version: n/a
Monaco editor: 0.44
OS Version: MacOs Sanoma
Steps to Reproduce:

1 Use monaco editor in a webpack dev environment
2 see https://github.com/microsoft/vscode/issues/183324#issuecomment-1758217137 - basically the merged fix does not cover all situations

**Comment by hediet** [comment]
Please create an issue in the monaco editor repository and provide a repro. Thanks!
