### ISSUE TITLE
Code lenses with unresolved commands show up as `!!MISSING: command!!`

### ISSUE THREAD

**Issue by michaelpj** [microsoft/vscode#197643]
Does this issue occur when all extensions are disabled?: Yes

A code lens with no command shows up as `!!MISSING: command!!`.

This is clearly deliberate, see the [implementation](https://github.com/microsoft/vscode/blob/e456d35d5ceb855f2b971003b3b7b13d9af20228/src/vs/workbench/api/common/extHostLanguageFeatures.ts#L107) and the [test for the behaviour](https://github.com/microsoft/vscode/blob/e456d35d5ceb855f2b971003b3b7b13d9af20228/src/vs/workbench/api/test/browser/extHostLanguageFeatures.test.ts#L276).

However, this interacts badly with `codeLens/resolve`. If the resolve request fails (for example, if the document has been changed such that the old lens is now stale), then the code lens will still appear with `!!!MISSING: command!!`, even though this is "normal" operation.

The behaviour I would expect is for the code lens not to be displayed in this case. The current behaviour makes a lot of sense for simple code lens providers that don't rely on `codeLens/resolve`, since in that case not providing a command is questionable and it's useful for it to show up obviously. But in the case where we've _resolved_ the lens and got a failure, I think it would make much more sense to just not display the lens.

This was discovered by a user of the Haskell Language Server after we implemented `codeLens/resolve`: https://github.com/haskell/haskell-language-server/issues/3827b

- VS Code Version: I don't know what the user was using, but the behaviour is clearly present in the source code on master
- OS Version: ditto

Steps to Reproduce:

1. Write a code lens resolve handler that fails
2. Observe ugly lenses

**Comment by jrieken** [comment]
> The behaviour I would expect is for the code lens not to be displayed in this case. The current behaviour makes a lot of sense for simple code lens providers that don't rely on codeLens/resolve, since in that case not providing a command is questionable and it's useful for it to show up obviously. But in the case where we've resolved the lens and got a failure, I think it would make much more sense to just not display the lens.

We don't remove these lenses to not introduce flicker (all lines would shift up by a little). I agree that today's fallback isn't great, a dash might be better, but it should also be clear that the extension should always try to resolve successfully and that failure is pretty bad here (because the UI space for code lense commands is already reserved)

**Comment by jrieken** [comment]
Decided to go with the (existing) "no commands" rendering but we will also start to log extension errors for this

<img width="644" alt="Screenshot 2023-12-04 at 16 23 29" src="https://github.com/microsoft/vscode/assets/1794099/20688f4b-96b6-4628-827a-6e87f01fcc12">

**Comment by michaelpj** [comment]
Just one thought: what about simply blank space? So we'd have the space in the UI, which would look a little odd, but we wouldn't be forcing what is ultimately a diagnostic message into the user's face unless they look in the log.

**Comment by jrieken** [comment]
I experimented with that but kinda looks like a rendering glitch and you keep staring at it waiting for an update
