### ISSUE TITLE
Move the debug panels to the bottom

### ISSUE THREAD

**Issue by yysc622** [microsoft/vscode#197696]
When debugging code, the values of variables are too long, and the left or right positions are too small to be fully displayed, which is very inconvenient.
So, can we have an option to display the debugging panel at the bottom?

![image](https://github.com/microsoft/vscode/assets/77236294/f693a50c-fcc8-4de8-84f5-923f670ea3e2) 
![image](https://github.com/microsoft/vscode/assets/77236294/2794bc29-d77c-40d7-9279-189c85ce139c)

**Comment by IllusionMH** [comment]
Have you tried to drag it to bottom panel?

**Comment by gjsjohnmurray** [comment]
@IllusionMH is correct. Either drag Variables alone down there or, starting with 1.84, drag the Run & Debug icon off the Activity Bar and drop it onto the Panel.

**Comment by yysc622** [comment]
I see, thanks...
