### ISSUE TITLE
Add shortcut/binding to toggle tabs hidden/visible

### ISSUE THREAD

**Issue by PrimeTimeTran** [microsoft/vscode#197753]
Could we add a key binding to toggle between show and hide tabs in the terminal view?
I've researched and don't think there 's one.

Terminal tabs menu visible:
<img width="1728" alt="Screenshot 2023-11-08 at 11 21 45 AM" src="https://github.com/microsoft/vscode/assets/16382165/9a27c64c-fa4b-41b3-81bd-19f1e7eab237">

Terminal tabs menu hidden with tab 1 visible:
<img width="1728" alt="Screenshot 2023-11-08 at 11 24 08 AM" src="https://github.com/microsoft/vscode/assets/16382165/da32591b-be38-4397-9937-be13b3cea164">

Terminal tabs menu hidden with tab 2 visible:
<img width="1728" alt="Screenshot 2023-11-08 at 11 25 09 AM" src="https://github.com/microsoft/vscode/assets/16382165/950392a9-fb65-483f-8ae8-1a91dbf81efe">

Thanks in advance

**Comment by meganrogge** [comment]
Thanks for the request. Tabs are meant to be a nice experience for all users, so it's not a common use case to switch between having them and not. Thus, we will not add this. What is your use case/ why do you disable tabs?

**Comment by PrimeTimeTran** [comment]
My use case would be the same as why we can enable bindings for show/hide/toggle for the activity bar, primary & secondary sidebar, status bar, editor tabs, and editor breadcrumbs; to enable users to create more screen space to focus on their main activity.

**Comment by meganrogge** [comment]
Thanks, my question was actually why are you ever using the view of the tabs that doesn't contain that info at a glance?

You can shrink the screen space the tabs occupy to be very minimal
![image](https://github.com/microsoft/vscode/assets/29464607/5cab6c5c-2cb0-4034-9c09-83401038b59b)

**Comment by Tyriar** [comment]
@PrimeTimeTran sorry but we won't be doing this as the dropdown UX is only still offered as a legacy option as it doesn't cost us much to maintain. The narrow tabs is probably the closest to what you're after. Alternatively you could find/create an extension that adds the terminal could to the status bar for example.
