### ISSUE TITLE
Theme & theme extension problem in 1.9

### ISSUE THREAD

**Issue by offbeatful** [Microsoft/vscode#19774]
- VSCode Version: 1.9
- OS Version: Windows 10

Just upgraded to 1.9 and noticed that my custom theme become 'broken'. It is no longer support distinct colors. Original theme supports it but mine is not. Also it seems the whole approach to css is changed. Please see screenshots below.
![theme_original](https://cloud.githubusercontent.com/assets/3128894/22576508/cec7c124-e989-11e6-8bc5-39d26829ff68.png)
![theme_custom](https://cloud.githubusercontent.com/assets/3128894/22576507/cec772d2-e989-11e6-97a5-2e30a1cebf2a.png)

More important I can't debug theme extension to fix it. When trying to debug (f5) it doesn't lunch another instance of visual studio code to select theme. Is there any guidelines to edit theme extensions post 1.9?

**Comment by Tyriar** [comment]
Yes there were a bunch of changes to the theme system to make it more inline with textmate. See release notes for the full story: https://code.visualstudio.com/updates/v1_9#_theme-matching-rules-now-respect-textmate-semantics

This is a related issue which might also be helpful https://github.com/Microsoft/vscode/issues/19734

Basically you want to use this now:

![image](https://cloud.githubusercontent.com/assets/2193314/22576929/8ce0ef30-e973-11e6-93de-66e2a7a2491b.png)

Which gives you this:

![image](https://cloud.githubusercontent.com/assets/2193314/22576944/9c765f5c-e973-11e6-840e-204585b667a2.png)

The scopes at the bottom are what you work with now, not CSS classes.

**Comment by alexandrudima** [comment]
@offbeatful 

We have a blog post draft explaining what changed in depth (will be published soon) -- https://github.com/Microsoft/vscode-docs/blob/vnext/blogs/2017/02/15/textmate-sematics.md

Here is another earlier explanation --
https://github.com/Microsoft/vscode/issues/18357#issuecomment-271709334
