### ISSUE TITLE
Vi Mode in 'Accessible View' Affected by v1.84.1 Update

### ISSUE THREAD

**Issue by jh-leong** [microsoft/vscode#197792]
In previous versions, with the use of `workbench.action.terminal.focusAccessibleBuffer` and the [VSCodeVim](https://github.com/VSCodeVim/Vim) extension, I could easily select and copy terminal output content in the "Accessible View" via Vi mode.

However, in the [v1.84.1](https://code.visualstudio.com/updates/v1_84#_accessible-view-improvements) update, I noticed a change that "The Accessible View now closes when a user starts typing and focuses the prior element for a smoother work flow.".

This change prevents me from using Vi mode to select content in the "Accessible View."

Could you please consider providing an option that allows users to choose whether or not this feature is enabled? Alternatively, are there any other solutions to this issue?

**Comment by jh-leong** [comment]
Related to #196023

**Comment by jh-leong** [comment]
@meganrogge can you take a look at this one? Thanks!

**Comment by meganrogge** [comment]
To verify, disable `accessibility.accessibleView.closeOnKeyPress` and make sure the view does not close on key press.

**Comment by jh-leong** [comment]
> To verify, disable `accessibility.accessibleView.closeOnKeyPress` and make sure the view does not close on key press.

Fixed now! Thanks for the quick resolution!
