### ISSUE TITLE
Menu Bar Resets to Visible When Reopening Window

### ISSUE THREAD

**Issue by sprinkle131313** [Microsoft/vscode#19777]
- VSCode Version: Version 1.9.0 Commit 27240e71ef390bf2d66307e677c2a333cebf75af
- OS Version: Windows 10

Steps to Reproduce:

1. Open VSCode window
2. Set user setting `"window.menuBarVisibility": "hidden"`, which should make the menubar hidden
3. Close VSCode
4. Reopen VSCode, the menu bar is now visible

**Comment by bpasero** [comment]
This is very unfortunate. A fix will be available in our next 1.10 insider release.

**Comment by xwvvvvwx** [comment]
@bpasero did I miss something? Pretty sure this was working when I submitted the original PR?

Was so excited to have had my change go in 😞

**Comment by bpasero** [comment]
@xwvvvvwx yes it did work, but we did a refactoring that for some reason broke it. See my comment in https://github.com/Microsoft/vscode/commit/1a813ef39de9a19d3686176bd0afe2f09a047479
