### ISSUE TITLE
[scss] error when @function inside @keyframes

### ISSUE THREAD

**Issue by n9** [microsoft/vscode#197742]
Type: <b>Bug</b>

It is similar to already fixed https://github.com/microsoft/vscode/issues/47285. 
But currently, the failure is caused by `@function` inside `@keyframes`.

```scss
@keyframes foo {
    @function bar() {
        @return ()
    }
}
```

Error messages:
```
[{
	"resource": "Untitled-1",
	"owner": "_generated_diagnostic_collection_name_#1",
	"code": "css-rcurlyexpected",
	"severity": 8,
	"message": "} expected",
	"source": "scss",
	"startLineNumber": 2,
	"startColumn": 5,
	"endLineNumber": 2,
	"endColumn": 14
},{
	"resource": "Untitled-1",
	"owner": "_generated_diagnostic_collection_name_#1",
	"code": "css-ruleorselectorexpected",
	"severity": 8,
	"message": "at-rule or selector expected",
	"source": "scss",
	"startLineNumber": 5,
	"startColumn": 1,
	"endLineNumber": 5,
	"endColumn": 2
}]
```

VS Code version: Code 1.84.1 (2b35e1e6d88f1ce073683991d1eff5284a32690f, 2023-11-06T12:35:59.022Z)
OS version: Windows_NT x64 10.0.19045
Modes:

**Comment by meadowsjared** [comment]
I get the same error using `@include` withing `@keyframes`:
![image](https://github.com/microsoft/vscode/assets/1596759/c4d4fa63-e8b1-4daa-8d9f-dc15a583f45f)
![image](https://github.com/microsoft/vscode/assets/1596759/be6ff867-6758-4c24-819d-c006789c2c42)
![image](https://github.com/microsoft/vscode/assets/1596759/463a64c6-6932-43a9-ad27-8dc8f36bc7b4)
it appears the `@keyframes` parser does not play nice with `@function` as well as `@include`

**Comment by TylerLeonhardt** [comment]
No more errors. Verified ✅ 

`@function bar()` should probably be highlighted in:
```scss
@keyframes foo {
    @function bar() {
        @return ()
    }
}
```

I'll open a separate issue for that.
