### ISSUE TITLE
"Generate Commit Message" function button blocks view of text which is underneath it.

### ISSUE THREAD

**Issue by RockBacon9922** [microsoft/vscode#197784]
Does this issue occur when all extensions are disabled?:  No
Requires Github Copilot Extension

- VS Code Version: 1.84.1
- OS Version: Ventura 13.5.1

Steps to Reproduce:

1.  Write a short commit message.
2. You will see that the "generate commit message" button partially covers the commit message.

**Comment by lszomoru** [comment]
Thanks for filing this issue. This has been fixed in the latest Insiders release.
