### ISSUE TITLE
Native crash in windows integration tests

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#197711]
https://dev.azure.com/vscode/VSCode/_build/results?buildId=107827&view=artifacts&pathAsName=false&type=publishedArtifacts

[eb29d7f2-0c29-444e-89df-bbbf00738685.dmp.zip](https://github.com/microsoft/vscode/files/13293450/eb29d7f2-0c29-444e-89df-bbbf00738685.dmp.zip)

**Comment by deepak1556** [comment]
Tracked in https://github.com/microsoft/vscode/issues/197710
