### ISSUE TITLE
The IDE suddenly turned purple

### ISSUE THREAD

**Issue by bNobo** [microsoft/vscode#197719]
Type: <b>Bug</b>

The bar menu on top and to the left are now purple. I can't change it, I tried to modify theme but it keeps purple whatever theme I choose.

![image](https://github.com/microsoft/vscode/assets/11414291/c7eac54f-ba67-41a7-bd38-e80bb68c92f4)

![image](https://github.com/microsoft/vscode/assets/11414291/6d9e4afb-8876-4274-aca0-f7b83a32ce70)

VS Code version: Code 1.84.1 (2b35e1e6d88f1ce073683991d1eff5284a32690f, 2023-11-06T12:35:59.022Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|23.82GB (7.84GB free)|
|Process Argv|--crash-reporter-id f9a6c103-9728-4fec-a1e7-b288f3d73a26|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|17.0.0
go|gol|0.39.1
easy-less|mrc|2.0.0
vscode-docker|ms-|1.27.0
vscode-dotnet-runtime|ms-|2.0.0
hexeditor|ms-|1.9.12
vscode-paste-image|mus|1.0.4

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
py29gd2263:30880072
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
282f8724:30602487
f6dab269:30613381
2i9eh265:30646982
showlangstatbar:30737416
pythonfmttext:30731395
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
welcomedialog:30882109
pythonnosmt12:30797651
pythonidxpt:30866567
pythonnoceb:30805159
dsvsc013:30795093
dsvsc014:30804076
dsvsc015:30845448
pythontestfixtcf:30871695
pythonregdiag2:30871582
pyreplss2:30879913
pythonmypyd1:30879173
pythoncet0:30874138
pythontbext0:30879054
dsvsc017cf:30880893
aa_t_chat:30882232

```

</details>

**Comment by gjsjohnmurray** [comment]
Does the problem also occur after you close your folder and use Command Palette to run `Profiles: Create a Temporary Profile`?

**Comment by bNobo** [comment]
The theme get back to normal immediatly after "File > Close Folder" and become purple again after re-opening the same folder. The theme keeps normal when I open another folder. So it seems to be related to that specific "ngx-passport-auth" folder. It's weird because it's a new folder, I've just cloned it.

**Comment by gjsjohnmurray** [comment]
I guess its .vscode folder contains a settings.json file that is overriding some colors.

**Comment by bNobo** [comment]
Effectively, a developer from our team forgot to add the `.vscode` folder to `.gitignore` and so his personal settings was added to the git repo.

Thanks for your help and sorry for the false positive.

**Comment by gjsjohnmurray** [comment]
:+1: Please close your issue.
