### ISSUE TITLE
[Regression] "Copy deleted line" menu in inline git diff is unusable, closes immediately after opening

### ISSUE THREAD

**Issue by HolyBlackCat** [microsoft/vscode#197743]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.84.1
- OS Version: Manjaro Linux, also Windows 10

Steps to Reproduce:

1. Open a Git repo.
2. Delete a line in a tracked file, to see the red triangle on the left.
3. Click the red triangle to open an inline diff.
4. Hover the deleted line to see the gray lightbulb icon:

![pic](https://github.com/microsoft/vscode/assets/20289055/a96d280f-800f-4091-8882-4185fffd5498)

5. Try to click the lightbulb icon to open the context menu.
6. Observe that the menu closes immediately (after a single frame, it seems), it's impossible to click anything in it.

**Comment by ADTC** [comment]
Can confirm this regression bug in `1.84.2`.

@HolyBlackCat as a workaround you can right-click the line to get the menu.

**Comment by lszomoru** [comment]
> Can confirm this regression bug in 1.84.2, also in regular Diff Editor (opened from source control).

@hediet, could you please take an initial look to this one? Thanks!

**Comment by hediet** [comment]
This is fixed now.
