### ISSUE TITLE
Cannot scroll in tmux when ssh to the server in a local integrated terminal

### ISSUE THREAD

**Issue by ZeroRin** [microsoft/vscode#197787]
Type: <b>Bug</b>

1. open a local project in vscode and open an integrated terminal
2. ssh to a server and attach to a `tmux` session
3. `ctrl+b [` and try to scroll
the whole `tmux` window got scrolled down and reveal histories before attaching the session
![image](https://github.com/microsoft/vscode/assets/14952735/01c2b72f-bc6e-4899-84ff-a2916f9fce47)

I only experience it when ssh to a server in a local workspace. when i open a remote workspace directly everything work as expected. It works even if i open a remote workspace in one server and then ssh to another server. the local machine is windows and servers are linux

VS Code version: Code 1.84.1 (2b35e1e6d88f1ce073683991d1eff5284a32690f, 2023-11-06T12:35:59.022Z)
OS version: Windows_NT x64 10.0.19045
Modes:
Remote OS version: Linux x64 4.15.0-208-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-9600KF CPU @ 3.70GHz (6 x 3696)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.93GB (18.38GB free)|
|Process Argv|--crash-reporter-id 5256b527-2907-4999-af58-0cda0ec119d8|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: 10.214.241.16|
|OS|Linux x64 4.15.0-208-generic|
|CPUs|Intel(R) Xeon(R) Gold 6240 CPU @ 2.60GHz (72 x 3300)|
|Memory (System)|251.42GB (209.55GB free)|
|VM|0%|
</details><details><summary>Extensions (46)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-sqlite|ale|0.14.1
vscode-pandoc|Chr|0.4.5
githistory|don|0.6.20
gitlens|eam|2023.11.817
html-preview-vscode|geo|0.2.5
gc-excelviewer|Gra|4.2.58
vscode-json5|Kat|1.0.1
pandoc-markdown-preview|kzv|0.4.1
hjson|lak|0.3.2
json-table-viewer|len|0.0.5
MagicPython|mag|1.1.0
rainbow-csv|mec|3.8.0
compare-folders|mos|0.23.0
vscode-json5|mrm|1.0.0
vscode-language-pack-zh-hans|MS-|1.84.2023110809
csharp|ms-|2.9.20
vscode-dotnet-runtime|ms-|2.0.0
black-formatter|ms-|2023.6.0
isort|ms-|2023.10.1
python|ms-|2023.20.0
vscode-pylance|ms-|2023.11.11
jupyter|ms-|2023.10.1003070148
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.17
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-slideshow|ms-|0.1.5
remote-ssh|ms-|0.107.0
remote-ssh-edit|ms-|0.86.0
hexeditor|ms-|1.9.12
remote-explorer|ms-|0.4.1
remote-server|ms-|1.6.2023110809
autodocstring|njp|0.6.1
hexeditor|not|1.8.2
pandocciter|not|0.10.3
prettier-standard-vscode|num|1.0.2
vscode-auto-scroll|pej|1.1.0
sqlite-viewer|qwt|0.3.13
vscode-data-preview|Ran|2.3.0
vscode-sort-json|ric|1.20.0
lua|sum|3.7.1
even-better-toml|tam|0.19.2
pandoc|tan|0.1.1
vscode-markdown-paste-image|tel|1.0.2
learn-vim|vin|0.0.28
jinja|who|0.0.8
markdown-all-in-one|yzh|3.5.1

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
py29gd2263:30880072
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
3biah626:30602489
f6dab269:30613381
a9j8j154:30646983
showlangstatbar:30737416
pythonfmttext:30731395
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
welcomedialogc:30882110
pythonnosmt12:30797651
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30869155
dsvsc013:30795093
dsvsc014:30804076
dsvsc015:30845448
pythontestfixtcf:30871695
pythonregdiag2cf:30871583
pythonmypyd1:30879173
pythoncet0:30874138
pythontbext0:30879054
dsvsc016cf:30880770
dsvsc018cf:30880895
aa_t_chat:30882232

```

</details>

**Comment by Tyriar** [comment]
This looks like an issue with our old terminal backend "winpty", going forward we are focusing our efforts on the new backend "conpty" which is build by the Console team at Microsoft and should fix many issues with the terminal under Windows. You will need to upgrade Windows to use conpty. You can read more about ConPTY [here](https://github.com/Microsoft/vscode/issues/57803#issuecomment-449495423) and [here](https://github.com/microsoft/vscode/wiki/Terminal-Issues#why-did-you-close-my-issue).

/duplicate https://github.com/Microsoft/vscode/issues/45693

**Comment by ZeroRin** [comment]
> This looks like an issue with our old terminal backend "winpty", going forward we are focusing our efforts on the new backend "conpty" which is build by the Console team at Microsoft and should fix many issues with the terminal under Windows. You will need to upgrade Windows to use conpty. You can read more about ConPTY [here](https://github.com/Microsoft/vscode/issues/57803#issuecomment-449495423) and [here](https://github.com/microsoft/vscode/wiki/Terminal-Issues#why-did-you-close-my-issue).
> 
> /duplicate #45693

I have "Windows Enable Conpty" turned on but the issue persists. it seems that my windows version when creating the issue (19045) already met the requirement (18309+), also i had upgraded to win11 recently (22631 now) yet i still cannot scroll as expected in integrated terminal connecting to a remote server
