### ISSUE TITLE
Hover of single view in secondary sidebar shows wrong title

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode#197788]
If you move a single view to the secondary sidebar, the tooltip on the icon only shows the "contextual" title, rather than both the contextual title and the view title.

![image](https://github.com/microsoft/vscode/assets/641685/5474d05f-80ab-486e-9424-88b44abeb7c5)

**Comment by eamodio** [comment]
Here's how it should really look -- taken from the activity bar at the top:

![image](https://github.com/microsoft/vscode/assets/641685/9011a39b-1bf9-417c-aa41-ed90e4b08229)

**Comment by bpasero** [comment]
Isn't this fixed @benibenj ?

![image](https://github.com/microsoft/vscode/assets/900690/ff0515db-3418-444b-a9aa-37de1d052739)

**Comment by eamodio** [comment]
@benibenj this isn't fixed -- the behavior is the same as reported

This is from today's build -- there is no title/header for this view
![image](https://github.com/microsoft/vscode/assets/641685/9295a6e9-9ee1-4df1-a4a4-a7e31804c9f5)

**Comment by benibenj** [comment]
The title of this issue confused me, it's talking about the hover. You are right, this is not fixed. Reopening

**Comment by eamodio** [comment]
The tooltip really isn't the bug -- the tooltip is the "view container" not the "view".

The issue is when a view is in the Secondary Side Bar, it gets an icon for its "view container" with a tooltip, but the view itself doesn't have a header or title. Which is vaguely similar to what happens when a single view is in a container in the normal sidebar -- the view title gets collapsed into the view container header. So not only does that not happen in the tooltip, but worse is that the title isnt visible at all.

Now if you add more than 1 view into the same container then the "collasping" stops and each view gets a visible header

![image](https://github.com/microsoft/vscode/assets/641685/02d46d44-84b1-4472-addc-8d054bce8195)

So I'm am suggesting that we should stop collapsing the view into the container on the Secondary Side Bar -- which would mimic the behavior we have today if you change the Side Bar to top or bottom, e.g. still show the header for the single view

**Comment by eamodio** [comment]
As an alternative (though IMO much less ideal), we could use the space below to put the combined title.

![image](https://github.com/microsoft/vscode/assets/641685/9094a87f-7567-43ca-b119-022952eb5246)

So in that space it could say "GitLens: Commits" (since GitLens is the container title, and Commits is the view title), and if I switched to the Copilot tab, then it would say something like "Copilot: Chat"

**Comment by eamodio** [comment]
@benibenj DOH, I just realized I'm really talking about https://github.com/microsoft/vscode/issues/197789 above. This case was purely about the tooltip so sorry about that.

Given that, this issue is still a problem too -- in that the tooltip is only the view container and not both the container and the view. But if https://github.com/microsoft/vscode/issues/197789 gets fixed this becomes a non-issue (assuming the dedicated view header approach)

**Comment by benibenj** [comment]
After discussing this we came to the conclusion that this is not the approach we want to take to fix this case. The hover title of the view container should not be including the title of any views inside the container. Having a fix like #197789 would be the proper solution to this problem.
