### ISSUE TITLE
Offline web vscode Error

### ISSUE THREAD

**Issue by PauletteASuare** [microsoft/vscode#197747]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.84.1
- OS Version: Debian 12

Steps to Reproduce:

1. Disable your internet connection.
2. run this command on the CLI: `code serve-web --without-connection-token --user-data-dir /home/myuser`
3. open a browser and try to open vscode on the web: `http://127.0.0.1:8000`

So you can see this error:

`error error getting latest version: Could not check for update: error requesting https://update.code.visualstudio.com/api/latest/server-linux-x64-web/stable: error sending request for url (https://update.code.visualstudio.com/api/latest/server-linux-x64-web/stable): error trying to connect: dns error: failed to lookup address information: Temporary failure in name resolution`

**Comment by connor4312** [comment]
`serve-web` will not work until you have an internet connection. If you have an internet connection once and go to the server, and then go offline later, it will fall back to reusing the last version it pulled. But it needs this at least once to download the VS Code server.
