### ISSUE TITLE
When on Fullscreen, Alt + tab makes the screen blink

### ISSUE THREAD

**Issue by Ripper1992** [Microsoft/vscode#19776]
When on Fullscreen, Alt + tab makes the screen blink.

Steps
1 - Press F11 to open fullscreen
2 - Change something in the document, then press Alt + Tab 

I think its better to identify this issue using more than one monitor, to see the actual "refreshing" of the vscode

**Comment by bpasero** [comment]
@Ripper1992 can you share a video or so how this looks like? Also, what OS are you on?
