### ISSUE TITLE
Open With Code context menu does not appear in Windows 11

### ISSUE THREAD

**Issue by valhristov** [microsoft/vscode#197724]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.84.1 (didn't work with the versions from 2 weeks ago too)
- OS Version: Windows 11 Enterprise 64bit, 22H2, Build 22621.2283, Windows Feature Experience Pack 1000.22662.1000.0

This issue seems to have been reported before in #127365 (and several other issues), but even though it was closed as fixed, it still doesn't work for me.

Steps to Reproduce:

1. Install VS Code, check both "Add 'Open With Code' action..." checkboxes in the setup wizard.
2. After the setup finishes, right click on a file or directory:
   Expected: "Open With Code" context menu is present
   Actual: "Open With Code" context menu is missing. The menu appears in the "old" context menu.

I shot a short video showing what's happening: [installing-vs-code.zip](https://github.com/microsoft/vscode/files/13296100/installing-vs-code.zip)

Additional info:
- My user is not administrator
- When I run the setup as administrator, it complains that it is not designed to run as administrator, and the result is the same
- To get administrator rights we use some software for elevation - "Admin by Request"
- Both of my drives are encrypted with bit locker
- This is a corporate computer, and it has applied administrative policies. If a policy is preventing VS Code from adding the context menu, let me know which one could be the problem and I can argue with our admins to disable it
- Apparently Windows Terminal and WinRar are able to add context menus (as seen on the video)

**Comment by gjsjohnmurray** [comment]
AFAIK https://github.com/microsoft/vscode/issues/127365#issuecomment-1288635483 still applies, and only Insiders will insert an entry into the first-level Windows 11 context menu.

Pinging @joaomoreno for confirmation and perhaps a status update about when Stable will catch up.

**Comment by Prajval-1608** [comment]
Any idea when it is planned to be added for regular VSCode?

**Comment by deepak1556** [comment]
Adding the feature to stable is tracked under https://github.com/microsoft/vscode/issues/183297, please follow that issue for updates.

In the meantime, please check if you are able to get the menu added successfully with our insiders version https://code.visualstudio.com/insiders
