### ISSUE TITLE
Empty launch.json causes files to take a few seconds to save

### ISSUE THREAD

**Issue by jessezhang91** [Microsoft/vscode#19773]
I have noticed the latest version 1.9.0 on Windows 10 and OSX 10.11 seems to taking quite a while to save a file. After I hit save, it usually takes about 4 seconds before the editor dirty dot goes away. If I try to close the editor before it goes away, I get a dialog about unsaved changes. I'm pretty sure this isn't just a UI bug as I have to wait the 4 seconds or so before being able to run commands using that file and its changes.

This happens to all files including settings and such. I have tested it with and without extensions.

- VSCode Version: 1.9.0
- OS Version: Windows 10 and OSX 10.11

**Comment by bpasero** [comment]
I wonder if this issue is being caused by an installed extension. Can you try to run VS Code without extensions? From the command line (NOT the integrated terminal in Code), execute: `code --disable-extensions` and try your steps again to see if it reproduces. If you see it is an issue with the extension, please file it against the extension repository itself.

**Comment by jessezhang91** [comment]
@bpasero Thanks for the response.

I did some testing since I realized I was experiencing this issue on the same codebase on both computers. When working outside the codebase, saves were immediate.

I went back in and started deleting things to see what was causing the slowdown. I found that deleting launch.json and restarting VSCode "fixes" the issue.

**Comment by bpasero** [comment]
Are you able to share this workspace for me to reproduce?

**Comment by jessezhang91** [comment]
```
mkdir .vscode
touch .vscode/launch.json
touch dummy-file.md
code --disable-extensions .
```

After VSCode launches, try editing and saving to `dummy-file.md`.

**Comment by ookblah** [comment]
I was also experiencing this issue and Jesse's solution worked.

**Comment by bpasero** [comment]
@jessezhang91 @ookblah can you share your user settings? Btw I cannot reproduce.

**Comment by jessezhang91** [comment]
@bpasero I think I might've found the exact error:
```
TypeError: Cannot convert undefined or null to object
    at t.get [as keys] (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:69:31447)
    at file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:94:21688
    at Array.forEach (native)
    at file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:94:21639
    at Array.forEach (native)
    at t.get [as keys] (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:94:21568)
    at t.keys (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:94:25587)
    at t.values (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:94:25664)
    at file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:133:19303
    at then (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:32:19172)
```

This seems to show up on windows that I end up having an issue.

I believe the launch.json file has to also be empty for this to occur. I ended up putting an empty object in launch.json, reload, and it seems to work. As to why I had an empty launch.json to begin with... I have no idea.

**Comment by bpasero** [comment]
The stack leads to here: https://github.com/Microsoft/vscode/blob/1.9.0/src/vs/platform/configuration/common/model.ts#L113

@jessezhang91 my feeling is you have a settings.json (either user or workspace) with malformed content, can you attach it?

**Comment by jessezhang91** [comment]
I did a test with my users and workspace settings as an empty object `{}`. The launch.json in .vscode is a completely empty file.

**Comment by bpasero** [comment]
@jessezhang91 and you see this crash stack trace everytime you try to save in the developer console?

**Comment by jessezhang91** [comment]
@bpasero Yes, on save and when I open a folder containing an empty `.vscode/launch.json`.

**Comment by bpasero** [comment]
@jessezhang91 can you maybe when devtools are open go to the "Sources" tab and enable "break on error" and then save just to see if you are able to hit the breakpoint when this happens so that we know more exactly where this bug happens?

![image](https://cloud.githubusercontent.com/assets/900690/22635619/12939fe2-ec35-11e6-9757-d6ac8c214c35.png)

**Comment by sandy081** [comment]
Fixing the error seen in the console is fixing the lag while saving. But, I am not able to figure out why is this causing the lag. I would need to investigate more on the relation between this and the lag.

**Comment by sandy081** [comment]
Found the catch. It is because above error is causing Extension host to be not initialized and the main thread is triggering and waiting for ext host save participants which will not finish but only times out. Hence the lag.

**Comment by bpasero** [comment]
@sandy081 awesome findings, that makes sense 👍
