### ISSUE TITLE
Intel Mac Python Formatter Failure

### ISSUE THREAD

**Issue by Yipky** [microsoft/vscode#197700]
Does this issue occur when all extensions are disabled?: No

- VS Code Version: 1.84.1
- OS Version: macOS 12.7.1

I updated my VSCode recently, and found my Python formatter not work. I used the autopep8 installed by pip before.

I just format my code as usual, and then VSCode told me to install a formatter extension. I can't format my code after the extension installation and editing the defaultFormatter. I have tried to reinstall my vscode, but nothing works.

Here are my setting.json.
`{
    "security.workspace.trust.enabled": false,
    "[python]": {
        "editor.defaultFormatter": "ms-python.black-formatter"
    }
}`

**Comment by Yipky** [comment]
Beside, I install the VSCode formatter extension on the m1 Mac by the same method, and everything works well.
It is worth noting that the failure appeared after VSCode update.

**Comment by brettcannon** [comment]
> I updated my VSCode recently, and found my Python formatter not work. I used the autopep8 installed by pip before.

This is expected as we have moved all tool support to separate extensions; https://code.visualstudio.com/updates/v1_84#_deprecated-builtin-linting-and-formatting-features covers the details. For autopep8, you can install the [autopep8 extension](https://marketplace.visualstudio.com/items?itemName=ms-python.autopep8).
