### ISSUE TITLE
Launch another window via --new-window-if-not-first appears to be broken

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#19775]
- VSCode Version: Code - Insiders 1.9.0-insider (27240e71ef390bf2d66307e677c2a333cebf75af, 2017-02-01T11:43:14.109Z)
- OS Version: Linux x64 4.8.0-34-generic
- Extensions:

|Extension|Author|Version|
|---|---|---|
|EditorConfig|EditorConfig|0.3.4|
|lorem-ipsum|Tyriar|1.0.0|
|theme-glacier|Tyriar|0.0.10|
|theme-sapphire|Tyriar|0.0.3|
|vscode-svgviewer|cssho|1.3.0|
|python|donjayamanne|0.5.7|
|tslint|eg2|0.8.1|
|git-project-manager|felipecaputo|1.0.1|
|vsc-travis-ci-status|felixrieseberg|1.0.5|
|md-navigate|jrieken|0.0.1|
|vscode-scss|mrmlnc|0.6.0|
|csharp|ms-vscode|1.6.2|
|seti-icons|qinjia|0.1.3|
|java|redhat|0.0.9|
|annotator|ryu1kn|0.10.1|

---

**Comment by Tyriar** [comment]
There is also a problem where opening files via nautilus will always open a new window.

**Comment by Tyriar** [comment]
Pushed to `release/1.9`.

**Comment by Tyriar** [comment]
Verification steps under Ubuntu:

1. Launch VS Code
2. On the 'task bar' shift+click or middle click on the VS Code app icon, a new window should launch
3. Open the file browser (nautilus)
4. Right click a text file and select open with other application
5. Select VS Code and hit Select, the file should *reuse* a window, not create a new one

**Comment by joaomoreno** [comment]
I'll verify this.

**Comment by joaomoreno** [comment]
Verified!
