### ISSUE TITLE
Space leading trail should be enabled by default

### ISSUE THREAD

**Issue by Doko-Demo-Doa** [Microsoft/vscode#19787]
- VSCode Version: 2.1.5
- OS Version: Mac OS X El Capitan

Just a feature request: Space leading trail should be enabled by default. Yes it is able to be enabled but would be more awesome if it's default.

**Comment by bpasero** [comment]
fyi @alexandrudima @rebornix

**Comment by alexandrudima** [comment]
This feature request will not be considered in the next [6-12 months roadmap](https://github.com/Microsoft/vscode/wiki/Roadmap) and as such will be closed to keep the number of issues we have to maintain actionable. Thanks for understanding and happy coding!
