### ISSUE TITLE
[Windows] Launch VsCode from Administrator Cmd App

### ISSUE THREAD

**Issue by NikoAri** [microsoft/vscode#197851]
Does this issue occur when all extensions are disabled?: Yes/No
Yes

- VS Code Version: 1.84.2
- OS Version: Windows 11

Steps to Reproduce:

1. In Windows 11, launch Cmd App as Administrator
2. In Cmd App, type: code

Result:

Error Window with following content:
The window terminated unexpectedly (reason: 'launch-failed', code: '18')
We are sorry for the inconvenience. You can reopen the window to continue where you left off.
![image](https://github.com/microsoft/vscode/assets/43590492/745655ad-d194-4e69-9317-8a4482675217)

Expected Result:

No error

**Comment by PzkpfwV** [comment]
This problem also occurs for VSCode Insider (1.85.0-insider)

Version: 1.85.0-insider (system setup)
Submission: f346494c77e1245505e53a2ddcab3bfb4ee52e08
Electron: 25.9.2
ElectronBuildId: 24603566
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.22631

**Comment by a123298** [comment]
I'm experiencing the same symptom 

Version: 1.84.2 (system setup)
Commit: 1a5daa3a0231a0fbba4f14db7ec463cf99d7768e
Date: 2023-11-09T10:51:52.184Z
Electron: 25.9.2
ElectronBuildId: 24603566
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.19044

**Comment by grevanthkris** [comment]
Any resolution for this ?

**Comment by deepak1556** [comment]
Error code indicates application sandbox does not support creating process in your environment. Please follow the steps in https://code.visualstudio.com/updates/v1_80#_disable-chromium-sandbox to workaround this issue.
