### ISSUE TITLE
ghci in integrated Terminal doesn't go to newline on reaching line width limit

### ISSUE THREAD

**Issue by chrismark** [Microsoft/vscode#19785]
- VSCode Version: Code 1.9.0 (27240e71ef390bf2d66307e677c2a333cebf75af, 2017-02-02T08:31:00.827Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

|Extension|Author|Version|
|---|---|---|
|vscode-npm-source|dkundel|1.0.0|
|githistory|donjayamanne|0.1.5|
|python|donjayamanne|0.5.6|
|language-haskell|justusadam|1.4.4|

---

Steps to Reproduce:

1. have haskell's ghci installed
2. open terminal (ctrl + `)
2. run ghci
3. type a long line longer than the window width
4, observe line doesn't go to new line, stays on same line
5. observe the very rightmost character on edge of terminal keep getting replaced by the new characters being typed

Doesn't seem to happen in node's and python's interactive environment.

**Comment by Tyriar** [comment]
Closing this off as it's a minor issue related to upstream cygwin/winpty.
