### ISSUE TITLE
Remote develop: ability to code locally but run remotely (quick sync & switch)

### ISSUE THREAD

**Issue by scruel** [microsoft/vscode#197897]
Currently, we can remotely develop with VS Code extensions, the overall development experience with it is quite great, and it is way better than other IDEs.

However now I am writing a cross-platform project (same code) and have two servers to operate, for convenience, I am using [mutagen](https://github.com/mutagen-io/mutagen/releases/tag/v0.17.2) for synchronizing project files (server specific files are ignored), and using terminal feature to manually connect the server via SSH, then type commands to run manually.
For example, if I need to run `test.py`, I will need to copy/paste `python test.py` three times, then hit the "enter" key to run...
To get the full experience which provided by VS Code plugins (e.g., auto interceptor detection), I have to open at least two VS Code windows simultaneously. If I changed the working file, then I have to do the same thing again in every terminal/windows...

I wonder if VS Code can consider such scenario and give me a better experience just in one single window, the current remote development plugin can't handle, it will run everything on the server (without UI), in the meantime the host client is just a web UI render which connected with the remote API on server, which have separate settings, plugins, etc.

PyCharm have related sync features, but it also won't provide me a good experience, the ideal usage steps are as following:
- Code locally, you can now test or run locally
- Click the "Open remote window" button on the left bottom of the VS Code window, it will have a new option called "Switch to server", click it to select server like the "connect to server" option, then need to input/select the server path for synchronizing, the difference here is that the opened file won't be changed, and we can still write code locally, VS Code will try to start a demon process to sync files.
- After VS Code connected to the server and sync all files (can have conflicts resolver here also), the window won't reload only if necessary, and we will have terminal changed, detected interceptors list got refreshed automatically, etc.
- For host installed plugins, instead of manually installed them again on server, we can now have the same button to **enabled** it remotely, so that it will replace the features partially, those plugins won't need to install repeatedly on server, will keep enabled, like `Excalidraw`, `WakaTime`, `Copilot`, etc.
- Do what ever you want, just like remotely connected to the server before.

For example, if I am writing `test.py` locally on my host, and if I want to test it on the server#1, I can:
- Just click to switch to server#1
- (at the first time) Enter the sync target directory (ignore files setting can be pre-configured in `.vscode` folder)
- VS Code will create target directory if it not exists, sync and let me resolve conflicts if it exists.
- (manually or auto pop tip bubble to enable, at the first time) Go to the "Plugin Panel" to enable some necessary plugins.
- With enabled plugins, VS Code reload plugin data, set previous plugin settings, reload window if necessary.
- (at the first time, or need to change in the future) Select the interceptor.
- Now I click "Run" button to run `test.py`, VS Code will type the right server paths and activate the right interceptor for me to run the script.
- Additionally, VS Code will record the history of all servers which switched before, and start a sync process in the background, I can see the list easily, and disable/enable some sync process with one button if I need to.

As we can see, if I am not using server#1 to run the project at the first time, the only thing I need to do is click to switch and run! What a lifesaver! :)

This is just a proposal, and I know it won't be easy to implement, hope it can be done in the future.

**Comment by roblourens** [comment]
Sorry, I think this doesn't really fit into vscode. Like you say, we have local and remote windows but for your specific scenario you will have to roll it yourself. Maybe an extension can help make it smoother.
