### ISSUE TITLE
Microsoft and Microsoft Entra ID as authentication providers for remote tunnels

### ISSUE THREAD

**Issue by kfot** [microsoft/vscode#197861]
As a developer, I would like to use Microsoft and Microsoft Entra ID as authentication providers to use remote tunnels. This functionality is officially supported by the [devtunnels](https://learn.microsoft.com/en-us/azure/developer/dev-tunnels/overview). I believe this is already a WIP, as there is already an option in VSCode to connect to a tunnel using MS, but not to create one (Otherwise that's a bug due to the lack of the symmetry).

**Comment by connor4312** [comment]
This is already available in the latest version of VS Code. You will be prompted to choose a provider when running `code tunnel`, or you can manually do so with `code tunnel user login --provider microsoft`
