### ISSUE TITLE
Goto symbol in workspace ignores methods in prototype object

### ISSUE THREAD

**Issue by hansanghoon** [Microsoft/vscode#19782]
- VSCode Version: Code 1.9.0 (27240e71ef390bf2d66307e677c2a333cebf75af, 2017-02-02T08:23:30.856Z)
- OS Version: Darwin x64 16.4.0
- Extensions:

|Extension|Author|Version|
|---|---|---|
|beautify|HookyQR|0.7.3|
|vscode-eslint|dbaeumer|1.2.2|
|vscode-dash|deerawan|1.3.0|
|bower|donjayamanne|0.0.3|
|vscode-babel-coloring|dzannotti|0.0.4|
|debugger-for-chrome|msjsdiag|2.5.1|
|polymer-ide|polymer|0.3.0|
|java|redhat|0.0.9|
|elm|sbrink|0.8.3|
|JavaScriptSnippets|xabikos|1.2.0|

---

Steps to Reproduce:

1. create a.js file contains something like `MyComponent.prototype.helloWorld = function(){}`
2. create b.js file `function myHello() {}`
3. type cmd+shift+o + `"hello"` in file `a.js` shows helloWorld function
4. type cmd+shift+o + `"hello"` in file `b.js` shows myHello function
5. type cmd+t + `"hello"` in file `a.js` shows myHello function
6. type cmd+t + `"hello"` in file `b.js` shows myHello function

I expect that in step 5/6 both helloWorld and myHello function would show up, but only function declaration was showed up. Is their any way to show both of them?

**Comment by mjbvz** [comment]
Thank you for reporting this. I've opened a bug to track this on the TypeScript side: https://github.com/Microsoft/TypeScript/issues/13875
