### ISSUE TITLE
Debug Console panel font cannot be changed

### ISSUE THREAD

**Issue by pgobin** [Microsoft/vscode#19786]
- VSCode Version: 1.9
- OS Version: Mac OS 10.12
- No extensions

## Steps to Reproduce:

1. Go to settings and change `editor.fontFamily` and `terminal.integrated.fontFamily`
2. Save
3. Open Debug Console
4. Notice font is jarringly different

I want to be able to customize the Debug Console font family and size so that I can see consistent character spacing and readability throughout the panels of the application that provide output.

Currently, VSCode only allows you to change the font family and size in the editor and terminal.

## See attached image:

<img width="1440" alt="screen shot 2017-02-02 at 9 11 25 pm" src="https://cloud.githubusercontent.com/assets/998044/22580315/2d0943a0-e98c-11e6-80ee-c93d6f695536.png">

**Comment by isidorn** [comment]
Dup of #1957
