### ISSUE TITLE
Preview does not work well

### ISSUE THREAD

**Issue by XiangruiCAI** [Microsoft/vscode#19789]
- VSCode Version: Code 1.9.0 (27240e71ef390bf2d66307e677c2a333cebf75af, 2017-02-02T08:21:13.228Z)
- OS Version: Linux x64 4.4.0-59-generic
- Extensions:

|Extension|Author|Version|
|---|---|---|
|latex-workshop|James-Yu|0.2.11|
|Encryptor|RushFrisby|0.3.1|
|code-settings-sync|Shan|2.4.3|
|path-intellisense|christian-kohler|1.2.0|
|vscode-gist|dbankier|0.5.2|
|githistory|donjayamanne|0.1.5|
|python|donjayamanne|0.5.7|
|gitlens|eamodio|1.4.3|
|CppSnippets|hars|0.0.6|
|ftp-simple|humy2833|0.4.14|
|cpptools|ms-vscode|0.10.0|
|latex|ms-vscode|0.1.3|
|todotasks|sandy081|0.4.0|
|rewrap|stkb|1.1.0|
|spellchecker|swyphcosmo|1.2.9|
|vim|vscodevim|0.5.2|

---

Steps to Reproduce:

1. set "window.zoomLevel: 2"
2. open any preview window, for instance, "release note" in "help".

**The preview page does not fill the full window.** I notice this problem form version 1.8.0. Thanks!
![image](https://cloud.githubusercontent.com/assets/16046954/22581185/35199792-ea19-11e6-9d2b-cd12bf498c61.png)

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/5745
