### ISSUE TITLE
Voice: support other languages than english

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#197837]
Currently we only support english as language for speech to text recognition. We should allow a user to pick another language that we then download and add to the extension somehow.

**Comment by rzhao271** [comment]
I got the following error trying to select French (Canada)
```
Failed to install extension 'vscode-speech-language-pack-fr-ca': Error: Extension 'vscode-speech-language-pack-fr-ca' introuvable.
```

It can't find a `vscode-speech-language-pack-fr-ca` extension.

**Comment by TylerLeonhardt** [comment]
I also saw what @rzhao271 pointed out.

That said, when I manually installed the extension via the marketplace then everything worked.

**Comment by rzhao271** [comment]
I'll leave this feature request open because I believe the current flow would confuse users.
I also noticed while checking the pipelines that a bunch of the extensions did not publish due to hitting a 12 hour rate limit, though I'm not sure where that rate limit comes from.

**Comment by bpasero** [comment]
**Verification Steps:**
* install https://marketplace.visualstudio.com/items?itemName=ms-vscode.vscode-speech
* configure `accessibility.voice.speechLanguage` to a non-default language
* open a text editor and dictate (`Ctrl+Alt+V` or `Cmd+Alt+V`)
* you should get prompted to install the necessary language pack
* wait for that to complete
* verify the extension appears as installed
* start editor dictate again and verify your language is recognised
