### ISSUE TITLE
/usr/share/code/bin/code-tunnel: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.29' not found

### ISSUE THREAD

**Issue by rastenis** [microsoft/vscode#197854]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version:  1.84.1
- OS Version:  Debian 10 (Buster)

Steps to Reproduce:

1.  run `code serve-web --help` on a machine with Debian 10, or any machine that has GLIBC version 2.28 or lower.

Result: 
```
➜  code serve-web --help                                                                                                                                                                                    
/usr/share/code/bin/code-tunnel: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.29' not found (required by /usr/share/code/bin/code-tunnel)     
```

Expected result:
serve-web works, and serves the web UI for VS Code

----

This seems to have been a problem since the introduction of the `serve-web` command in VS Code ~1.82.0. 

I have also tried `code-insiders` to no avail.

Is there a workaround to make the command work?

**Comment by connor4312** [comment]
Duplicates https://github.com/microsoft/vscode/issues/192685
