### ISSUE TITLE
typescript type textMate scopes highlighting error

### ISSUE THREAD

**Issue by shaddollxz** [microsoft/vscode#197829]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.84.1
- OS Version: macOS 14.0

I have the following TypeScript code, and its return type is a union type. However, the colors for syntax highlighting are inconsistent in the same location (data and arg). I found that this is due to their different TextMate scopes.

```typescript
declare function getCb():
  | { data: string; cb: (arg: string) => void }
  | { data: number; cb: (arg: number) => void }
```
like :
![图片](https://github.com/microsoft/vscode/assets/56341682/3e7cfa53-e19b-4a78-8764-882805326d75)
scopes :
![图片](https://github.com/microsoft/vscode/assets/56341682/74d7b330-b550-4ad5-8a96-1e2bcc0a8de1)
![图片](https://github.com/microsoft/vscode/assets/56341682/019d64f3-dc85-4a1d-bf7c-9a99906e4d70)

**Comment by shaddollxz** [comment]
In function generics, if there is a line break within the generic, the issue with mismatched scopes for syntax highlighting can also occur

![图片](https://github.com/microsoft/vscode/assets/56341682/6822d712-fd51-416e-9736-1eaa4e5699c7)

**Comment by RedCMD** [comment]
prob should move report to https://github.com/microsoft/TypeScript-TmLanguage/tree/master
