### ISSUE TITLE
Improve concurrency of git commands

### ISSUE THREAD

**Issue by Silic0nS0ldier** [Microsoft/vscode#19783]
- VSCode Version: Code 1.9.0 (27240e71ef390bf2d66307e677c2a333cebf75af, 2017-02-02T08:31:00.827Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

|Extension|Author|Version|
|---|---|---|
|vscode-twig-pack|bajdzis|1.0.0|
|githistory|donjayamanne|0.1.5|
|python|donjayamanne|0.5.7|
|xml|DotJoshJohnson|1.7.0|
|vscode-html-css|ecmel|0.0.33|
|live-html-previewer|hdg|0.0.1|
|vscode-apache|mrmlnc|1.1.0|
|mssql|ms-mssql|0.2.0|
|csharp|ms-vscode|1.6.2|
|team|ms-vsts|1.108.0|
|vscode-docker|PeterJausovec|0.0.11|

---

Steps to Reproduce:

1. Create a git repo.
2. Create 2 or more files.
3. Add each file to staging individually, without waiting for previous file to be shown as staged.
4. VS Code will show the error `There was an issue running a git operation. Please review the output or use a console to check the state of your repository.`

This kind of issue can be encountered in git itself if using 2 terminals for the same repo. Reason this is a VS Code issue and not git (git should throw an error for this to prevent corruptions), is that VS Code is aggressively refreshing the git status after each file is added, creating an increased likelihood for it to trip over its own git operation.

**Comment by joaomoreno** [comment]
I agree that concurrency here is troublesome and especially in Windows this is noticeable.

But unfortunately not calling `git status` isn't an option. It will just create the next issue: "git view doesn't show all the changes in my repository".

**Comment by Silic0nS0ldier** [comment]
@joaomoreno I get what you mean. And I agree that calling `git status` is required.

Just throwing an idea out there, but what if instead of attempting to execute it immediately, it added to an 'execution stack'.

Hmm... If git supports staging multiple files at once, it would be feasible to have a checkbox approach to staging files? (even if git doesn't support staging multiple files at once, it would likely reduce the number of concurrency errors, as you would be able to string the commands together)

**Comment by kumarharsh** [comment]
+1 for the staging multiple files at once, just like the trusty old `git-gui` does it (`Click`, `shift+Click`, `Ctrl+T`). Clicking one-by-one in vscode is very tiresome and sometimes prone to errors because the staged and unstaged changes list changes in height, thus changing the scroll-position of the view, and I end up mistakenly staging the wrong file many times.

**Comment by joaomoreno** [comment]
@kumarharsh Maybe something like this?

![kapture 2017-02-03 at 17 53 48](https://cloud.githubusercontent.com/assets/22350/22600193/be96ed4c-ea39-11e6-8f07-5ad62958bf9f.gif)

**Comment by kumarharsh** [comment]
@joaomoreno yes exactly! But... I cant seem to do this on mine

**Comment by joaomoreno** [comment]
Hold <kbd>Shift</kbd> for range selection. Or <kbd>Ctrl</kbd> (<kdb>Cmd</kbd>) for single selection. Make sure you're not on the Preview SCM work (by default you are not).

**Comment by kumarharsh** [comment]
Oh my... I think I've tried it so many times , it never worked. Maybe i was trying it wrong. When did this land?

**Comment by Silic0nS0ldier** [comment]
@joaomoreno That multiple file selection for staging is in VS Code! I never knew! As @kumarharsh asked, when did this land?

On the topic of git concurrency, a way to stack git operations when these conflicts occur would be nice. Previously I mentioned an automatic 'execution stack', but I think that would take to much control away, so perhaps instead allow a failed git operation to be added the queue by the developer explicitly. The idea being you could string the actions together, and do something else while it executes the tasks. (and not waste time fighting with git concurrency)

**Comment by joaomoreno** [comment]
Much improved since. Due to [`retryRun`](https://github.com/Microsoft/vscode/blob/master/extensions/git/src/model.ts#L538)
