### ISSUE TITLE
Explorer not showing random directories

### ISSUE THREAD

**Issue by schilling-ryan** [microsoft/vscode#197850]
Type: <b>Bug</b>

> Issue troubleshooting has identified that the issue is with Visual Studio Code. 
When opening several project directories, I see some directories and files do not appear although I can go to them in Windows Explorer and even use Open File in VSC to explicitly open a file in those directories, at which point only that file and the directory path to that file show up and then as soon as I close the editor for that file, the file and path go away again. I have deleted the directory and recloned the repo but that didn't make any difference. The directories that disappear seem to have their own .vscode (reminant from merging multiple projects together) and deleting that .vscode dir from the missing directory makes it show back up.

VS Code version: Code 1.84.1 (2b35e1e6d88f1ce073683991d1eff5284a32690f, 2023-11-06T12:35:59.022Z)
OS version: Windows_NT x64 10.0.22621
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz (8 x 1805)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.73GB (17.80GB free)|
|Process Argv|--crash-reporter-id 20d2edbc-a5f1-48d7-a292-bb1db86a2e86|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
py29gd2263:30880072
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
282f8724:30602487
f6dab269:30613381
a9j8j154:30646983
showlangstatbar:30737416
pythonfmttext:30731395
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
pythonnosmt12:30797651
pythonidxpt:30866567
pythonnoceb:30805159
synctok:30869157
dsvsc013:30795093
dsvsc014:30804076
dsvsc015:30845448
pythontestfixtcf:30871695
pythonregdiag2:30871582
pyreplss2:30879913
pythonmypyd1:30879173
pythoncet0:30885854
pythontbext0:30879054
dsvsc016cf:30880770
dsvsc017:30880892
aa_t_chat:30882232

```

</details>

This seems related to https://github.com/microsoft/vscode/issues/195497 although that was not resolved as they never provided the above info. I have had someone else verify this behavior too; I have 1.84.1 and he has 1.84.2 with both exhibiting the same behavior.

**Comment by lramos15** [comment]
It's likely that you have exclusion settings in those .vscode folders. Would you be willing to share the project or is it confidential?

**Comment by schilling-ryan** [comment]
Hi, yes this project contains proprietary info unfortunately. I saw there is an exclusion for .vscode directories but not sure how that would play into this because the directory that is missing contains some golang files as well as other directories aside from just the .vscode. It's an easy enough workaround to just delete the nested .vscode since we probably don't want it there anyway but just seems odd behavior to mark the whole directory as hidden because it contains a .vscode. The root of my repo contains a .vscode and it doesn't hide when I go up a level

**Comment by schilling-ryan** [comment]
I see them erroneously added to the root of my repo and then in the Settings --> Workspace --> Files:Exclude at the bottom of the list. Removing them from there made them show back up, not sure who added them but seems it's working as expected now.
