### ISSUE TITLE
BUG IN THE VERSION 1.84.1

### ISSUE THREAD

**Issue by Oscar-Serna** [microsoft/vscode#197838]
Type: <b>Bug</b>

Problem in the native color palette.

It is removed when you finish clicking, the color codes pile up, semicolons are removed and it gives an error.

You can't choose colors, shades, anything.

You can't work at all with the native palette.

Note: It is not a mistake of my extensions
I tried with version 1.83 from September and everything works correctly, please solve it.

VS Code version: Code 1.84.1 (2b35e1e6d88f1ce073683991d1eff5284a32690f, 2023-11-06T12:35:59.022Z)
OS version: Windows_NT x64 10.0.22621
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-10300H CPU @ 2.50GHz (8 x 2496)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|7.87GB (1.55GB free)|
|Process Argv|--crash-reporter-id dd146827-40ea-4d0c-989f-0a356a748022|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (56)</summary>

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|17.0.0
es7-react-js-snippets|dsz|4.4.3
prettier-vscode|esb|10.1.0
file-icons|fil|1.1.0
auto-rename-tag|for|0.1.10
c-cpp-runner|fra|9.2.1
rest-client|hum|0.25.1
ftp-simple|hum|0.7.6
cge-x3d-vscode|kag|0.0.8
vscode-gutter-preview|kis|0.30.0
fluent-icons|mig|0.0.18
sql-snippet|Mil|0.0.4
vscode-docker|ms-|1.27.0
vscode-language-pack-es|MS-|1.84.2023110809
csharp|ms-|2.10.28
vscode-dotnet-runtime|ms-|2.0.0
isort|ms-|2023.10.1
python|ms-|2023.20.0
vscode-pylance|ms-|2023.11.10
jupyter|ms-|2023.10.1003070148
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.17
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-slideshow|ms-|0.1.5
remote-ssh|ms-|0.107.0
remote-ssh-edit|ms-|0.86.0
remote-wsl|ms-|0.81.8
cpptools|ms-|1.17.5
cpptools-extension-pack|ms-|1.3.0
remote-explorer|ms-|0.4.1
remote-server|ms-|1.5.0
indent-rainbow|ode|8.3.1
material-icon-theme|PKi|4.31.0
vscode-thunder-client|ran|2.15.3
java|red|1.24.0
LiveServer|rit|5.7.9
synthwave-vscode|Rob|0.1.15
trailing-spaces|sha|0.4.1
guides|spy|0.9.3
ayu|tea|1.0.5
pdf|tom|1.2.2
vscode-counter|uct|3.2.2
errorlens|use|3.15.0
vscode-lldb|vad|1.10.0
highlight-matching-tag|vin|0.11.0
intellicode-api-usage-examples|Vis|0.2.8
vscodeintellicode|Vis|1.2.30
vscode-java-debug|vsc|0.55.0
vscode-java-dependency|vsc|0.23.2
vscode-java-pack|vsc|0.25.15
vscode-java-test|vsc|0.40.1
vscode-maven|vsc|0.43.0
vscode-icons|vsc|12.6.0
vscode-wakatime|Wak|24.4.0
JavaScriptSnippets|xab|1.8.0
material-theme|zhu|3.16.2

(6 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263cf:30335440
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
py29gd2263:30880072
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
2e4cg342:30602488
89544117:30613380
a9j8j154:30646983
showlangstatbar:30737416
pythonfmttext:30731395
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
welcomedialog:30882109
pythonnosmt12:30797651
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30869155
dsvsc013:30795093
dsvsc014:30804076
dsvsc015:30845448
pythontestfixtcf:30871695
pythonregdiag2:30871582
pythonmypyd1:30879173
pythoncet0:30874138
2e7ec940:30884756
pythontbext0:30879054
dsvsc017cf:30880893
aa_t_chat:30882232

```

</details>

**Comment by gjsjohnmurray** [comment]
Maybe related to #197818

**Comment by Nouman-khan-dev** [comment]
I am facing the same issue after updating the vs code.

**Comment by aiday-mar** [comment]
Hi thank you for filing the issue. This issue should be closed by the following PR which was developed by a community developer https://github.com/microsoft/vscode/pull/198100. The fix should be inside the next insiders build quite soon and the next stable build in around a month.
