### ISSUE TITLE
`\w` cannot match non-ascii characters in the search panel when the file is opened

### ISSUE THREAD

**Issue by stone-zeng** [microsoft/vscode#197807]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.84.1 (Universal)
- Commit: 2b35e1e6d88f1ce073683991d1eff5284a32690f
- Date: 2023-11-06T12:37:18.666Z
- Electron: 25.9.2
- ElectronBuildId: 24603566
- Chromium: 114.0.5735.289
- Node.js: 18.15.0
- V8: 11.4.183.29-electron.0
- OS: Darwin x64 22.6.0

Steps to Reproduce:

1. Create a file with the following content:

   ```
   ax 1x Пx 字x あx
   ```

2. Open the search panel and enter `\wx`, with regex mode enabled. The search result will be:

   <img width="273" alt="Screenshot 2023-11-09 at 16 38 39" src="https://github.com/microsoft/vscode/assets/18233088/64ea28fb-f2fd-4116-a650-167984158ca9">

3. Open the file and search again, but now `Пx`, `字x` and `あx` will not be matched:

   <img width="481" alt="Screenshot 2023-11-09 at 16 41 07" src="https://github.com/microsoft/vscode/assets/18233088/99576c42-3507-4642-9897-4b8737980639">

I also notice that in the Find Widget, `\w` will not match non-ascii characters:

<img width="533" alt="Screenshot 2023-11-09 at 16 42 51" src="https://github.com/microsoft/vscode/assets/18233088/972e1771-37e2-41ae-9484-f6a41df571a7">

Is it intentionally that the experiences between these two place are inconsistent?

**Comment by IllusionMH** [comment]
For open files JS (V8) regexp engine is used and it's intentionally.
`\w` in JS newer matched non-ascii, you'll need to use https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Regular_expressions/Unicode_character_class_escape feature.

**Comment by andreamah** [comment]
The above is the correct way to approach this.

**Comment by stone-zeng** [comment]
Could you please consider to clarify this difference in the [docs](https://code.visualstudio.com/docs/editor/codebasics#_find-and-replace)?
