### ISSUE TITLE
`editor.action.showHover` collides with `Cmd+K I` for inline chat

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode#197864]
@meganrogge ran into this. Should we maybe reconsider this keybinding now that inline chat also uses `Cmd+K I`?

https://github.com/microsoft/vscode/blob/cd98a2cd54d9ea5f15273a43215a2389b6763488/src/vs/editor/contrib/hover/browser/hover.ts#L409

**Comment by ulugbekna** [comment]
Alex is right. Please, reopen if there's something we're missing.
