### ISSUE TITLE
workbench.action.terminal.runSelectedText w/PowerShell inserts extraneous >>

### ISSUE THREAD

**Issue by devinscodev** [Microsoft/vscode#19788]
- VSCode Version: 1.9.0
- OS Version: Windows 10

Steps to Reproduce:

1. Make sure PowerShell is the active shell
2. Type any shell command into an editor, highlight it, open the command palette, and run the "Run Selected Text in Active Terminal" command
3. After running the command, ">>" will be appended to the line after the prompt line

Expected behavior:
Nothing should be inserted after the prompt line

In the image below, the first command was run directly in the terminal and outputs correctly. The second command was run by using the "Run Selected Text in Active Terminal" command on the text in the editor. After this command ran, an extraneous ">>" appears after the new terminal prompt.

![capture](https://cloud.githubusercontent.com/assets/6452466/22581007/8974097a-e9a2-11e6-91e0-bc2bdeb15ce4.JPG)

**Comment by Tyriar** [comment]
@daviwil can you repro this one?

**Comment by mscloudops** [comment]
@Tyriar I've the same here :/ 

With line selection : 

![image](https://cloud.githubusercontent.com/assets/25929992/23455857/809ae1fa-fe71-11e6-9c71-51fe4292d081.png)

Wihtout line selection : 

![image](https://cloud.githubusercontent.com/assets/25929992/23455781/22f5ecb6-fe71-11e6-8695-1332e56c9493.png)

Any idea ?

**Comment by daviwil** [comment]
Yeah, this is similar to issues others have filed when running selections in the terminal when PSReadline is loaded.  Here's one: https://github.com/Microsoft/vscode/issues/9715.  I'm planning on using VS Code's built-in run selection command for the PowerShell extension in an upcoming release so I'll see if I can fix it on our side then.

**Comment by mscloudops** [comment]
Ok thx ! 
👍

**Comment by Tyriar** [comment]
This is probably related to sending `Write-Host "Hello world"\r\n` when only `\n` is probably needed.

**Comment by Tyriar** [comment]
This is actually related to PSReadline since 32-bit PS (which doesn't load PSReadline) works just fine. @daviwil is this something that would be fixed upstream do you think?

**Comment by daviwil** [comment]
Yeah, I'll see if I can fix that in PSReadline before we try to look for other solutions.

**Comment by Tyriar** [comment]
@daviwil I might close this off for now, let me know if the fix should be in vscode :smiley:
