### ISSUE TITLE
Recent dynamic launch configurations in the debug sidebar drop-down are confusing and it's not obvious how to remove them

### ISSUE THREAD

**Issue by DanTup** [microsoft/vscode#197821]
From the drop-down menu on the debug side-bar, I can choose a debugger type and select an automatic launch configuration:

https://github.com/microsoft/vscode/assets/1078012/145ce7b5-b4ee-4342-af38-66a4b2b42b11

After I've done this, that launch configuration shows in the drop-down list even after a restart:

![image](https://github.com/microsoft/vscode/assets/1078012/0a4cd0c9-f521-4c9a-a55a-1ec3205e706a)

This confused me (and a user at https://github.com/Dart-Code/Dart-Code/issues/4830#issuecomment-1803736511) because it's not clear where this is coming from (especially if it was some time ago that you performed the initial actions above) and it's not clear how to delete it.

Digging through the VS Code code, I found that in https://github.com/microsoft/vscode/commit/12aa93aacd80e844464b33dcac055c4c29f6d4e1 an option was adding to delete these, but it's only visible if you run the **Debug: Select and Start Debugging** command:

![image](https://github.com/microsoft/vscode/assets/1078012/b3b924c6-318a-4cae-8a1d-e79ee0a72644)

If you don't know about this command and/or did not use it to initially "create" this recent launch configuration, it's unlikely you will discover this.

I think it could be clearer where this config came from (and perhaps there should be a divider between those that are explicitly in your workspace, and those that are just "recently used dynamic" ones), and it would be much better if there was to remove it from this drop-down menu.

**Comment by roblourens** [comment]
I'm not sure what I expect here for a way to remove these, but there should probably be something that differentiates them.

**Comment by connor4312** [comment]
There's not much of a way to remove them unless we move away from a native `<select>`. I would be a fan of having a custom select in the product but I don't think one exists yet.

**Comment by connor4312** [comment]
I think we should merge this into https://github.com/microsoft/vscode/issues/140980; better UI for dynamic launch configs could also allow removal
