### ISSUE TITLE
Unable to reuse opened browser pages when debugging VS Code on the Web side

### ISSUE THREAD

**Issue by yiliang114** [microsoft/vscode#197898]
When I use the `code-server.sh` or  `code-web.sh`  script to debug the vscode on the web side, every time I execute the script again, I will reopen a page instead of reusing the page that has been opened before. This results in more and more of the same debug pages in the browser

Reproduction steps:

1. clone vscode source code.
2. yarn i
3. Use `cmd + shift + b` to compile vscode and builtin extension, then call `./scripts/code-web.sh` to start web
4. The browser opens `http://localhost:8080/` by default
5. Exit `./scripts/code-web.sh` and re-execute.
6. The browser opens `http://localhost:8080/` again.

![bug124](https://github.com/microsoft/vscode/assets/11473889/363fca7e-9539-46eb-9d18-258b1035e2f4)

Version: 1.84.2
Commit: 1a5daa3a0231a0fbba4f14db7ec463cf99d7768e
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36
Embedder: vscode.dev

**Comment by yiliang114** [comment]
related to https://github.com/sindresorhus/open/issues/179.  

Reference code in create react app: 

https://github.com/facebook/create-react-app/blob/0a827f69ab0d2ee3871ba9b71350031d8a81b7ae/packages/react-dev-utils/openBrowser.js#L95

Similar implementation in vite: 

https://github.com/vitejs/vite/blob/2687dbbd4e19c86f9888ee784c9b51598e8b79ca/packages/vite/src/node/server/openBrowser.ts#L97

**Comment by roblourens** [comment]
Maybe it works to reload instead of starting the script over again and again? We probably wouldn't fix this but maybe would take a PR that doesn't complicate the script too much

**Comment by roblourens** [comment]
You can submit a simple PR if you like but I'm going to close this

**Comment by yiliang114** [comment]
> You can submit a simple PR if you like but I'm going to close this

I'll give it a try
