### ISSUE TITLE
Git - Stage / Unstage / Revert Selected Ranges should only appear or be available where useful in Diff Editor context menu

### ISSUE THREAD

**Issue by ADTC** [microsoft/vscode#197875]
When in the Diff Editor for a **Working Tree** diff:

* Stage Selected Ranges: ✅ works
* Unstage Selected Ranges: ❌ does nothing
* Revert Selected Ranges: ✅ works

When in the Diff Editor for an **Index** diff:

* Stage Selected Ranges: ❌ does nothing
* Unstage Selected Ranges: ✅ works
* Revert Selected Ranges: ❌ does nothing

Currently the context menu shows and enables all the three possible options. This is kind of confusing, because there are actions in the context menu which don't do anything meaningful.

My suggestion: Available items in the context menu should vary depending on context. Any menu item that ❌ "does nothing" should be hidden from the context menu, or at least they should be disabled.

Case in point: The menu shown when right-clicking a deleted line varies depending on context. #9475

Related: #175786 #105920 #48676

**Comment by ADTC** [comment]
Following up on this @lszomoru if it's possible to do this. It doesn't quite make sense to include menu items that are guaranteed to be inert in the given context, right? The menu itself is already very long, so removing them will make it slightly shorter which is appreciated. 🙂

**Comment by lszomoru** [comment]
This has been fixed in the latest VS Code Insiders release.
```
Version: 1.97.0-insider
Commit: cf2ebd91b8e42e3bc5ab0e85e3323c886a977ffe
Date: 2024-12-18T06:50:13.779Z
Electron: 32.2.6
ElectronBuildId: 10629634
Chromium: 128.0.6613.186
Node.js: 20.18.1
V8: 12.8.374.38-electron.0
OS: Darwin arm64 24.2.0
```
