### ISSUE TITLE
Last update causes Color Picker to disappear immediately after any color modification

### ISSUE THREAD

**Issue by alexchexes** [microsoft/vscode#197818]
Does this issue occur when all extensions are disabled?: Yes (Bisected)

- VS Code Version: 1.84.1 (user setup)
- OS Version: Win 10 LTSC (Windows_NT x64 10.0.19044)

Steps to Reproduce:

1. Activate the color picker by hovering over the hex code (for instance, during customization of your color scheme).
2. Alter the current color using the color picker, adjusting aspects like hue, saturation, or opacity.
3. Notice that the color picker popup closes immediately following any modification. In contrast, prior to the version 1.84.1 update, it remained open, facilitating easier fine-tuning of interface colors. For example, one could adjust a color, save the changes (Ctrl+S), see the result, refine the color further, and repeat the process, all without needing to reopen the color picker since it remained visible.

Screencapture:

https://github.com/microsoft/vscode/assets/49966773/6e0d3c00-867b-4496-99c2-ec8d9de8960b

**Comment by C0nanT** [comment]
It's happening to me too, and on top of that the color hex code is changing to rgb automatically when you select a new color.

**Comment by anthonypillot** [comment]
I've this issue too.

Visual Studio Code version:
> Version: 1.84.2
> Commit: 1a5daa3a0231a0fbba4f14db7ec463cf99d7768e
> Date: 2023-11-09T10:52:57.054Z
> Electron: 25.9.2
> ElectronBuildId: 24603566
> Chromium: 114.0.5735.289
> Node.js: 18.15.0
> V8: 11.4.183.29-electron.0
> OS: Darwin arm64 23.1.0

OS:
<img width="439" alt="image" src="https://github.com/microsoft/vscode/assets/51130139/00632f17-0b47-4aa8-9dcd-c6a915675e78">

**Comment by anthonypillot** [comment]
I've this issue too.

Visual Studio Code version:
> Version: 1.84.2
> Commit: 1a5daa3a0231a0fbba4f14db7ec463cf99d7768e
> Date: 2023-11-09T10:52:57.054Z
> Electron: 25.9.2
> ElectronBuildId: 24603566
> Chromium: 114.0.5735.289
> Node.js: 18.15.0
> V8: 11.4.183.29-electron.0
> OS: Darwin arm64 23.1.0

On macOS Sonoma `14.1.1` - `M2`.

**Comment by Elyticus** [comment]
Does anyone found a solution for this or we have to wait for the next update from MS?

**Comment by aiday-mar** [comment]
Hi @Elyctius, a PR has been opened by a community user (https://github.com/microsoft/vscode/pull/198100) which should fix this error

**Comment by aiday-mar** [comment]
Hi thank you for filing the issue. This issue should be closed by the following PR which was developed by a community developer https://github.com/microsoft/vscode/pull/198100. The fix should be inside the next insiders build quite soon and the next stable build in around a month.

**Comment by alexchexes** [comment]
Thank you! Looking forward for the next stable release.

**Comment by aiday-mar** [comment]
Hi @paulrobertpine, this problem should be fixed in version 1.85. What version are you on?

**Comment by paulrobertpine** [comment]
Hello @aiday-mar I am version 1.84.2 but when I go to updates it says none are pending
