### ISSUE TITLE
WHERE is NORMAL COMMAND PROMPT in TERMINAL?

### ISSUE THREAD

**Issue by bromoapp** [Microsoft/vscode#19784]
- VSCode Version: Code 1.9.0 (27240e71ef390bf2d66307e677c2a333cebf75af, 2017-02-02T08:31:00.827Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

|Extension|Author|Version|
|---|---|---|
|vscode-elixir|mjmcloug|0.1.1|
|vscode-docker|PeterJausovec|0.0.11|
|erlang-otp|yuce|0.2.1|

I really get frustrated here... I just updates your Visual Studio Code to the latest updates ... now I CANNOT ACCESS my Elixir Shell by typing IEX from Terminal, and this is really really BUGGED me since I'm using your product to code my Elixir project!... WHY can't you keep the normal COMMAND PROMPT terminal instead of POWERSHELL???

Steps to Reproduce:

1. Just install Erlang and Elixir runtime
2. Install Elixir and Erlang plugin for VSC
3. Open terminal and type IEX in terminal ... it doesn't open Elixir terminal where I usually compile and etc.

**Comment by Matticusau** [comment]
The shift to PowerShell is clearly outlined in the Release Notes. https://code.visualstudio.com/updates/v1_9#_integrated-terminal-improvements

The release notes clearly provide the following workaround to reset this setting:
You can change this back to cmd.exe by setting terminal.integrated.shell.windows to "cmd.exe" in your settings.json file.

Take note though that you need to set that setting in your User settings, it is no longer allowed in the Workspace settings..... that's documented as another issue...... more on that and changing the settings also in the release notes.

**Comment by Tyriar** [comment]
Thanks @Matticusau, and apologies for the inconvenience @bromoapp :smiley:

**Comment by bromoapp** [comment]
Thanks ... you guys really safe me 👍
