### ISSUE TITLE
Improve toolbar icon size

### ISSUE THREAD

**Issue by zhouxinghong** [microsoft/vscode#197805]
Improve toolbar icon size

Keep the icon size of number 1 and number 2 the same.
![image](https://github.com/microsoft/vscode/assets/54253524/ab80f56e-3aca-419b-aebd-d17f196a1659)
You should be able to find that the icon size of number 1 is obviously too large, and you need to further improve it to make the icon size reach an optimal and ideal state. 😜

environment
 "window.zoomLevel": 2,
vscode 1.84.1
Windows 10 19044

**Comment by lszomoru** [comment]
@sandy081, is this something that you could take a look?

**Comment by sandy081** [comment]
Number 1 is the activity bar and not the tool bar and has bigger icons as designed.

**Comment by zhouxinghong** [comment]
Appropriately reduce the size of icon No. 1, and the overall appearance will be better. You can think about it carefully. . .

It is recommended that the size of icon No. 1 be consistent with the size of icon No. 2 for better appearance.
